LLVM: lib/DebugInfo/CodeView/AppendingTypeTableBuilder.cpp File Reference
AppendingTypeTableBuilder.cpp File Reference
#include "llvm/DebugInfo/CodeView/AppendingTypeTableBuilder.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/DebugInfo/CodeView/ContinuationRecordBuilder.h"
#include "llvm/DebugInfo/CodeView/RecordSerialization.h"
#include "llvm/DebugInfo/CodeView/TypeIndex.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/BinaryByteStream.h"
#include "llvm/Support/BinaryStreamWriter.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstring>
Functions
static ArrayRef< uint8_t > stabilize (BumpPtrAllocator &RecordStorage, ArrayRef< uint8_t > Record)
Function Documentation
stabilize()
static ArrayRef< uint8_t > stabilize (BumpPtrAllocator & RecordStorage, ArrayRef< uint8_t > Record) static
Definition at line 77 of file AppendingTypeTableBuilder.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate().
Referenced by llvm::codeview::MergingTypeTableBuilder::insertRecordAs(), llvm::codeview::AppendingTypeTableBuilder::insertRecordBytes(), llvm::codeview::AppendingTypeTableBuilder::replaceType(), llvm::codeview::GlobalTypeTableBuilder::replaceType(), and llvm::codeview::MergingTypeTableBuilder::replaceType().