LLVM: lib/Transforms/IPO/AttributorAttributes.cpp File Reference
AttributorAttributes.cpp File Reference
#include "llvm/Transforms/IPO/Attributor.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/SCCIterator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumeBundleQueries.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/CaptureTracking.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LazyValueInfo.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Assumptions.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/NoFolder.h"
#include "llvm/Support/Alignment.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/IPO/ArgumentPromotion.h"
#include "llvm/Transforms/Utils/Local.h"
#include <cassert>
Classes
struct llvm::DenseMapInfo< AAPointerInfo::Access >
Helper for AA::PointerInfo::Acccess DenseMap/Set usage.
struct llvm::DenseMapInfo< AA::PointerInfo ::OffsetAndSize >
Helper that allows OffsetAndSize as a key in a DenseMap.
struct llvm::AccessAsInstructionInfo
Helper for AA::PointerInfo::Acccess DenseMap/Set usage ignoring everythign but the instruction.
struct llvm::AA::PointerInfo::OffsetAndSize
Helper to represent an access offset and size, with logic to deal with uncertainty and check for overlapping accesses.
struct llvm::AA::PointerInfo::State
}
struct AAPointerInfoImpl
struct AAPointerInfoFloating
struct AAPointerInfoFloating::OffsetInfo
Helper struct, will support ranges eventually.
struct AAPointerInfoReturned
struct AAPointerInfoArgument
struct AAPointerInfoCallSiteArgument
struct AAPointerInfoCallSiteReturned
struct AANoUnwindImpl
--------------------—NoUnwind Function Attribute-----------------------—
struct AANoUnwindFunction
struct AANoUnwindCallSite
NoUnwind attribute deduction for a call sites.
class AAReturnedValuesImpl
------------------— Function Return Values ----------------------------—
struct AAReturnedValuesFunction
struct AAReturnedValuesCallSite
Returned values information for a call sites.
struct AANoSyncImpl
---------------------— NoSync Function Attribute ----------------------—
struct AANoSyncFunction
struct AANoSyncCallSite
NoSync attribute deduction for a call sites.
struct AANoFreeImpl
---------------------— No-Free Attributes -------------------------—
struct AANoFreeFunction
struct AANoFreeCallSite
NoFree attribute deduction for a call sites.
struct AANoFreeFloating
NoFree attribute for floating values.
struct AANoFreeArgument
NoFree attribute for a call site argument.
struct AANoFreeCallSiteArgument
NoFree attribute for call site arguments.
struct AANoFreeReturned
NoFree attribute for function return value.
struct AANoFreeCallSiteReturned
NoFree attribute deduction for a call site return value.
struct AANonNullImpl
struct AANonNullFloating
NonNull attribute for a floating value.
struct AANonNullReturned
NonNull attribute for function return value.
struct AANonNullArgument
NonNull attribute for function argument.
struct AANonNullCallSiteArgument
struct AANonNullCallSiteReturned
NonNull attribute for a call site return position.
struct AANoRecurseImpl
---------------------— No-Recurse Attributes -------------------------—
struct AANoRecurseFunction
struct AANoRecurseCallSite
NoRecurse attribute deduction for a call sites.
struct AAUndefinedBehaviorImpl
-----------------— Undefined-Behavior Attributes ---------------------—
struct AAUndefinedBehaviorFunction
struct AAWillReturnImpl
struct AAWillReturnFunction
struct AAWillReturnCallSite
WillReturn attribute deduction for a call sites.
struct AAReachabilityImpl
----------------—AAReachability Attribute-----------------------—
struct AAReachabilityFunction
struct AANoAliasImpl
---------------------— NoAlias Argument Attribute ---------------------—
struct AANoAliasFloating
NoAlias attribute for a floating value.
struct AANoAliasArgument
NoAlias attribute for an argument.
struct AANoAliasCallSiteArgument
struct AANoAliasReturned
NoAlias attribute for function return value.
struct AANoAliasCallSiteReturned
NoAlias attribute deduction for a call site return value.
struct AAIsDeadValueImpl
----------------—AAIsDead Function Attribute--------------------—
struct AAIsDeadFloating
struct AAIsDeadArgument
struct AAIsDeadCallSiteArgument
struct AAIsDeadCallSiteReturned
struct AAIsDeadReturned
struct AAIsDeadFunction
struct AAIsDeadCallSite
Liveness information for a call sites.
struct AADereferenceableImpl
-----------------— Dereferenceable Argument Attribute -----------------—
struct AADereferenceableFloating
Dereferenceable attribute for a floating value.
struct AADereferenceableReturned
Dereferenceable attribute for a return value.
struct AADereferenceableArgument
Dereferenceable attribute for an argument.
struct AADereferenceableCallSiteArgument
Dereferenceable attribute for a call site argument.
struct AADereferenceableCallSiteReturned
Dereferenceable attribute deduction for a call site return value.
struct AAAlignImpl
struct AAAlignFloating
Align attribute for a floating value.
struct AAAlignReturned
Align attribute for function return value.
struct AAAlignArgument
Align attribute for function argument.
struct AAAlignCallSiteArgument
struct AAAlignCallSiteReturned
Align attribute deduction for a call site return value.
struct AANoReturnImpl
---------------— Function No-Return Attribute -------------------------—
struct AANoReturnFunction
struct AANoReturnCallSite
NoReturn attribute deduction for a call sites.
struct AANoCaptureImpl
--------------------— Variable Capturing ------------------------------—
struct AACaptureUseTracker
Attributor-aware capture tracker.
struct AANoCaptureArgument
NoCapture attribute for function arguments.
struct AANoCaptureCallSiteArgument
NoCapture attribute for call site arguments.
struct AANoCaptureFloating
NoCapture attribute for floating values.
struct AANoCaptureReturned
NoCapture attribute for function return value.
struct AANoCaptureCallSiteReturned
NoCapture attribute deduction for a call site return value.
struct AAValueSimplifyImpl
struct AAValueSimplifyArgument
struct AAValueSimplifyReturned
struct AAValueSimplifyFloating
struct AAValueSimplifyFunction
struct AAValueSimplifyCallSite
struct AAValueSimplifyCallSiteReturned
struct AAValueSimplifyCallSiteArgument
struct AAHeapToStackFunction
--------------------— Heap-To-Stack Conversion ------------------------—
struct AAHeapToStackFunction::AllocationInfo
struct AAHeapToStackFunction::DeallocationInfo
struct AAPrivatizablePtrImpl
--------------------— Privatizable Pointers ---------------------------—
struct AAPrivatizablePtrArgument
struct AAPrivatizablePtrFloating
struct AAPrivatizablePtrCallSiteArgument
struct AAPrivatizablePtrCallSiteReturned
struct AAPrivatizablePtrReturned
struct AAMemoryBehaviorImpl
-----------------— Memory Behavior Attributes -------------------------—
struct AAMemoryBehaviorFloating
Memory behavior attribute for a floating value.
struct AAMemoryBehaviorArgument
Memory behavior attribute for function argument.
struct AAMemoryBehaviorCallSiteArgument
struct AAMemoryBehaviorCallSiteReturned
Memory behavior attribute for a call site return position.
struct AAMemoryBehaviorFunction
An AA to represent the memory behavior function attributes.
struct AAMemoryBehaviorCallSite
AAMemoryBehavior attribute for call sites.
struct AAMemoryLocationImpl
struct AAMemoryLocationImpl::AccessInfo
Helper struct to tie together an instruction that has a read or write effect with the pointer it accesses (if any).
struct AAMemoryLocationFunction
An AA to represent the memory behavior function attributes.
struct AAMemoryLocationCallSite
AAMemoryLocation attribute for call sites.
struct AAValueConstantRangeImpl
---------------— Value Constant Range Attribute ----------------------—
struct AAValueConstantRangeArgument
struct AAValueConstantRangeReturned
struct AAValueConstantRangeFloating
struct AAValueConstantRangeFunction
struct AAValueConstantRangeCallSite
struct AAValueConstantRangeCallSiteReturned
struct AAValueConstantRangeCallSiteArgument
struct AAPotentialValuesImpl
---------------— Potential Values Attribute ----------------------—
struct AAPotentialValuesArgument
struct AAPotentialValuesReturned
struct AAPotentialValuesFloating
struct AAPotentialValuesFunction
struct AAPotentialValuesCallSite
struct AAPotentialValuesCallSiteReturned
struct AAPotentialValuesCallSiteArgument
struct AANoUndefImpl
---------------------— NoUndef Attribute ------------------------------—
struct AANoUndefFloating
struct AANoUndefReturned
struct AANoUndefArgument
struct AANoUndefCallSiteArgument
struct AANoUndefCallSiteReturned
struct AACallEdgesImpl
struct AACallEdgesCallSite
struct AACallEdgesFunction
struct AAFunctionReachabilityFunction
struct AAAssumptionInfoImpl
-------------------— Assumption Propagation ---------------------------—
struct AAAssumptionInfoFunction
Propagates assumption information from parent functions to all of their successors.
struct AAAssumptionInfoCallSite
Assumption Info defined for call sites.
Namespaces
namespace llvm
/file This file defines the SmallVector class.
namespace llvm::AA
Abstract Attribute helper functions.
namespace llvm::AA::PointerInfo
Macros
#define DEBUG_TYPE "attributor"
#define BUILD_STAT_MSG_IR_ATTR(TYPE, NAME) ("Number of " #TYPE " marked '" #NAME "'")
#define BUILD_STAT_NAME(NAME, TYPE) NumIR##TYPE##_##NAME
#define STATS_DECL_(NAME, MSG) STATISTIC(NAME, MSG);
#define STATS_DECL(NAME, TYPE, MSG) STATS_DECL_(BUILD_STAT_NAME(NAME, TYPE), MSG);
#define STATS_TRACK(NAME, TYPE) ++(BUILD_STAT_NAME(NAME, TYPE));
#define STATS_DECLTRACK(NAME, TYPE, MSG)
#define STATS_DECLTRACK_ARG_ATTR(NAME) STATS_DECLTRACK(NAME, Arguments, BUILD_STAT_MSG_IR_ATTR(arguments, NAME))
#define STATS_DECLTRACK_CSARG_ATTR(NAME)
#define STATS_DECLTRACK_FN_ATTR(NAME) STATS_DECLTRACK(NAME, Function, BUILD_STAT_MSG_IR_ATTR(functions, NAME))
#define STATS_DECLTRACK_CS_ATTR(NAME) STATS_DECLTRACK(NAME, CS, BUILD_STAT_MSG_IR_ATTR(call site, NAME))
#define STATS_DECLTRACK_FNRET_ATTR(NAME)
#define STATS_DECLTRACK_CSRET_ATTR(NAME)
#define STATS_DECLTRACK_FLOATING_ATTR(NAME)
#define PIPE_OPERATOR(CLASS)
#define SWITCH_PK_INV(CLASS, PK, POS_NAME)
#define SWITCH_PK_CREATE(CLASS, IRP, PK, SUFFIX)
#define CREATE_FUNCTION_ABSTRACT_ATTRIBUTE_FOR_POSITION(CLASS)
#define CREATE_VALUE_ABSTRACT_ATTRIBUTE_FOR_POSITION(CLASS)
#define CREATE_ALL_ABSTRACT_ATTRIBUTE_FOR_POSITION(CLASS)
#define CREATE_FUNCTION_ONLY_ABSTRACT_ATTRIBUTE_FOR_POSITION(CLASS)
#define CREATE_NON_RET_ABSTRACT_ATTRIBUTE_FOR_POSITION(CLASS)
Functions
STATISTIC (NumAAs, "Number of abstract attributes created")
template<>
ChangeStatus llvm::clampStateAndIndicateChange< DerefState > (DerefState &S, const DerefState &R)
static const Value * getPointerOperand (const Instruction *I, bool AllowVolatile)
Get pointer operand of memory accessing instruction.
static Value * constructPointer (Type *ResTy, Type *PtrElemTy, Value *Ptr, int64_t Offset, IRBuilder< NoFolder > &IRB, const DataLayout &DL)
Helper function to create a pointer of type ResTy, based on Ptr, and advanced by Offset bytes.
template<typename StateTy >
static bool genericValueTraversal (Attributor &A, IRPosition IRP, const AbstractAttribute &QueryingAA, StateTy &State, function_ref< bool(Value &, const Instruction *, StateTy &, bool)> VisitValueCB, const Instruction *CtxI, bool &UsedAssumedInformation, bool UseValueSimplify=true, int MaxValues=16, function_ref< Value *(Value *)> StripCB=nullptr, bool Intraprocedural=false)
Recursively visit all values that might become IRP at some point.
const Value * stripAndAccumulateMinimalOffsets (Attributor &A, const AbstractAttribute &QueryingAA, const Value *Val, const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool UseAssumed=false)
static const Value * getMinimalBaseOfPointer (Attributor &A, const AbstractAttribute &QueryingAA, const Value *Ptr, int64_t &BytesOffset, const DataLayout &DL, bool AllowNonInbounds=false)
template<typename AAType , typename StateType = typename AAType::StateType>
static void clampReturnedValueStates (Attributor &A, const AAType &QueryingAA, StateType &S, const IRPosition::CallBaseContext *CBContext=nullptr)
Clamp the information known for all returned values of a function (identified by QueryingAA) into S.
template<class AAType , typename StateType = typename AAType::StateType>
static void followUsesInContext (AAType &AA, Attributor &A, MustBeExecutedContextExplorer &Explorer, const Instruction *CtxI, SetVector< const Use * > &Uses, StateType &State)
Helper function to accumulate uses.
template<class AAType , typename StateType = typename AAType::StateType>
static void followUsesInMBEC (AAType &AA, Attributor &A, StateType &S, Instruction &CtxI)
Use the must-be-executed-context around I to add information into S.
static int64_t getKnownNonNullAndDerefBytesForUse (Attributor &A, const AbstractAttribute &QueryingAA, Value &AssociatedValue, const Use *U, const Instruction *I, bool &IsNonNull, bool &TrackUse)
---------------------— NonNull Argument Attribute ---------------------—
static bool mayContainUnboundedCycle (Function &F, Attributor &A)
---------------------— Will-Return Attributes -------------------------—
static bool identifyAliveSuccessors (Attributor &A, const CallBase &CB, AbstractAttribute &AA, SmallVectorImpl< const Instruction * > &AliveSuccessors)
static bool identifyAliveSuccessors (Attributor &A, const InvokeInst &II, AbstractAttribute &AA, SmallVectorImpl< const Instruction * > &AliveSuccessors)
static bool identifyAliveSuccessors (Attributor &A, const BranchInst &BI, AbstractAttribute &AA, SmallVectorImpl< const Instruction * > &AliveSuccessors)
static bool identifyAliveSuccessors (Attributor &A, const SwitchInst &SI, AbstractAttribute &AA, SmallVectorImpl< const Instruction * > &AliveSuccessors)
static unsigned getKnownAlignForUse (Attributor &A, AAAlign &QueryingAA, Value &AssociatedValue, const Use *U, const Instruction *I, bool &TrackUse)
Variables
static cl::opt< bool > ManifestInternal ("attributor-manifest-internal", cl::Hidden, cl::desc("Manifest Attributor internal string attributes."), cl::init(false))
static cl::opt< int > MaxHeapToStackSize ("max-heap-to-stack-size", cl::init(128), cl::Hidden)
static cl::opt< unsigned, true > MaxPotentialValues ("attributor-max-potential-values", cl::Hidden, cl::desc("Maximum number of potential values to be " "tracked for each position."), cl::location(llvm::PotentialConstantIntValuesState::MaxPotentialValues), cl::init(7))
static cl::opt< unsigned > MaxInterferingWrites ("attributor-max-interfering-writes", cl::Hidden, cl::desc("Maximum number of interfering writes to " "check before assuming all might interfere."), cl::init(6))
Macro Definition Documentation
BUILD_STAT_MSG_IR_ATTR
#define BUILD_STAT_MSG_IR_ATTR (TYPE, NAME) ("Number of " #TYPE " marked '" #NAME "'")
Definition at line 94 of file AttributorAttributes.cpp.
BUILD_STAT_NAME
#define BUILD_STAT_NAME (NAME, TYPE) NumIR##TYPE##_##NAME
Definition at line 96 of file AttributorAttributes.cpp.
Referenced by AAIsDeadFunction::manifest(), AAUndefinedBehaviorFunction::trackStatistics(), and AAHeapToStackFunction::trackStatistics().
CREATE_ALL_ABSTRACT_ATTRIBUTE_FOR_POSITION
#define CREATE_ALL_ABSTRACT_ATTRIBUTE_FOR_POSITION (CLASS)
Value:
  CLASS &CLASS::createForPosition(const IRPosition &IRP, Attributor &A) {      \
    CLASS *AA = nullptr;                                                       \
    switch (IRP.getPositionKind()) {                                           \
      SWITCH_PK_INV(CLASS, IRP_INVALID, "invalid")                             \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_FUNCTION, Function)                     \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_CALL_SITE, CallSite)                    \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_FLOAT, Floating)                        \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_ARGUMENT, Argument)                     \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_RETURNED, Returned)                     \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_CALL_SITE_RETURNED, CallSiteReturned)   \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_CALL_SITE_ARGUMENT, CallSiteArgument)   \
    }                                                                          \
    return *AA;                                                                \
  }
Definition at line 10121 of file AttributorAttributes.cpp.
CREATE_FUNCTION_ABSTRACT_ATTRIBUTE_FOR_POSITION
#define CREATE_FUNCTION_ABSTRACT_ATTRIBUTE_FOR_POSITION (CLASS)
Value:
  CLASS &CLASS::createForPosition(const IRPosition &IRP, Attributor &A) {      \
    CLASS *AA = nullptr;                                                       \
    switch (IRP.getPositionKind()) {                                           \
      SWITCH_PK_INV(CLASS, IRP_INVALID, "invalid")                             \
      SWITCH_PK_INV(CLASS, IRP_FLOAT, "floating")                              \
      SWITCH_PK_INV(CLASS, IRP_ARGUMENT, "argument")                           \
      SWITCH_PK_INV(CLASS, IRP_RETURNED, "returned")                           \
      SWITCH_PK_INV(CLASS, IRP_CALL_SITE_RETURNED, "call site returned")       \
      SWITCH_PK_INV(CLASS, IRP_CALL_SITE_ARGUMENT, "call site argument")       \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_FUNCTION, Function)                     \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_CALL_SITE, CallSite)                    \
    }                                                                          \
    return *AA;                                                                \
  }
Definition at line 10089 of file AttributorAttributes.cpp.
CREATE_FUNCTION_ONLY_ABSTRACT_ATTRIBUTE_FOR_POSITION
#define CREATE_FUNCTION_ONLY_ABSTRACT_ATTRIBUTE_FOR_POSITION (CLASS)
Value:
  CLASS &CLASS::createForPosition(const IRPosition &IRP, Attributor &A) {      \
    CLASS *AA = nullptr;                                                       \
    switch (IRP.getPositionKind()) {                                           \
      SWITCH_PK_INV(CLASS, IRP_INVALID, "invalid")                             \
      SWITCH_PK_INV(CLASS, IRP_ARGUMENT, "argument")                           \
      SWITCH_PK_INV(CLASS, IRP_FLOAT, "floating")                              \
      SWITCH_PK_INV(CLASS, IRP_RETURNED, "returned")                           \
      SWITCH_PK_INV(CLASS, IRP_CALL_SITE_RETURNED, "call site returned")       \
      SWITCH_PK_INV(CLASS, IRP_CALL_SITE_ARGUMENT, "call site argument")       \
      SWITCH_PK_INV(CLASS, IRP_CALL_SITE, "call site")                         \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_FUNCTION, Function)                     \
    }                                                                          \
    return *AA;                                                                \
  }
Definition at line 10137 of file AttributorAttributes.cpp.
CREATE_NON_RET_ABSTRACT_ATTRIBUTE_FOR_POSITION
#define CREATE_NON_RET_ABSTRACT_ATTRIBUTE_FOR_POSITION (CLASS)
Value:
  CLASS &CLASS::createForPosition(const IRPosition &IRP, Attributor &A) {      \
    CLASS *AA = nullptr;                                                       \
    switch (IRP.getPositionKind()) {                                           \
      SWITCH_PK_INV(CLASS, IRP_INVALID, "invalid")                             \
      SWITCH_PK_INV(CLASS, IRP_RETURNED, "returned")                           \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_FUNCTION, Function)                     \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_CALL_SITE, CallSite)                    \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_FLOAT, Floating)                        \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_ARGUMENT, Argument)                     \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_CALL_SITE_RETURNED, CallSiteReturned)   \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_CALL_SITE_ARGUMENT, CallSiteArgument)   \
    }                                                                          \
    return *AA;                                                                \
  }
Definition at line 10153 of file AttributorAttributes.cpp.
CREATE_VALUE_ABSTRACT_ATTRIBUTE_FOR_POSITION
#define CREATE_VALUE_ABSTRACT_ATTRIBUTE_FOR_POSITION (CLASS)
Value:
  CLASS &CLASS::createForPosition(const IRPosition &IRP, Attributor &A) {      \
    CLASS *AA = nullptr;                                                       \
    switch (IRP.getPositionKind()) {                                           \
      SWITCH_PK_INV(CLASS, IRP_INVALID, "invalid")                             \
      SWITCH_PK_INV(CLASS, IRP_FUNCTION, "function")                           \
      SWITCH_PK_INV(CLASS, IRP_CALL_SITE, "call site")                         \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_FLOAT, Floating)                        \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_ARGUMENT, Argument)                     \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_RETURNED, Returned)                     \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_CALL_SITE_RETURNED, CallSiteReturned)   \
      SWITCH_PK_CREATE(CLASS, IRP, IRP_CALL_SITE_ARGUMENT, CallSiteArgument)   \
    }                                                                          \
    return *AA;                                                                \
  }
Definition at line 10105 of file AttributorAttributes.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "attributor"
Definition at line 53 of file AttributorAttributes.cpp.
PIPE_OPERATOR
#define PIPE_OPERATOR (CLASS)
Value:
  raw_ostream &operator<<(raw_ostream &OS, const CLASS &AA) {                  \
    return OS << static_cast<const AbstractAttribute &>(AA);                   \
  }
Definition at line 128 of file AttributorAttributes.cpp.
STATS_DECL
#define STATS_DECL (NAME, TYPE, MSG) STATS_DECL_(BUILD_STAT_NAME(NAME, TYPE), MSG);
Definition at line 98 of file AttributorAttributes.cpp.
Referenced by AAIsDeadFunction::manifest(), AAUndefinedBehaviorFunction::trackStatistics(), and AAHeapToStackFunction::trackStatistics().
STATS_DECL_
#define STATS_DECL_ (NAME, MSG) STATISTIC(NAME, MSG);
Definition at line 97 of file AttributorAttributes.cpp.
STATS_DECLTRACK
#define STATS_DECLTRACK (NAME, TYPE, MSG)
Value:
  {                                                                            \
    STATS_DECL(NAME, TYPE, MSG)                                                \
    STATS_TRACK(NAME, TYPE)                                                    \
  }
Definition at line 101 of file AttributorAttributes.cpp.
Referenced by AAReturnedValuesImpl::manifest(), and AAAlignImpl::manifest().
STATS_DECLTRACK_ARG_ATTR
#define STATS_DECLTRACK_ARG_ATTR (NAME) STATS_DECLTRACK(NAME, Arguments, BUILD_STAT_MSG_IR_ATTR(arguments, NAME))
Definition at line 106 of file AttributorAttributes.cpp.
Referenced by AAReturnedValuesFunction::trackStatistics(), AANoFreeArgument::trackStatistics(), AANonNullArgument::trackStatistics(), AANoAliasArgument::trackStatistics(), AAIsDeadArgument::trackStatistics(), AADereferenceableArgument::trackStatistics(), AAAlignArgument::trackStatistics(), AANoCaptureArgument::trackStatistics(), AAValueSimplifyArgument::trackStatistics(), AAPrivatizablePtrArgument::trackStatistics(), AAMemoryBehaviorArgument::trackStatistics(), AAValueConstantRangeArgument::trackStatistics(), AAPotentialValuesArgument::trackStatistics(), and AANoUndefArgument::trackStatistics().
STATS_DECLTRACK_CS_ATTR
#define STATS_DECLTRACK_CS_ATTR (NAME) STATS_DECLTRACK(NAME, CS, BUILD_STAT_MSG_IR_ATTR(call site, NAME))
Definition at line 113 of file AttributorAttributes.cpp.
Referenced by AANoUnwindCallSite::trackStatistics(), AANoSyncCallSite::trackStatistics(), AANoFreeCallSite::trackStatistics(), AANoRecurseCallSite::trackStatistics(), AAWillReturnCallSite::trackStatistics(), AADereferenceableCallSiteReturned::trackStatistics(), AAAlignCallSiteReturned::trackStatistics(), AANoReturnCallSite::trackStatistics(), AAValueSimplifyCallSite::trackStatistics(), AAMemoryBehaviorCallSite::trackStatistics(), AAMemoryLocationCallSite::trackStatistics(), AAValueConstantRangeCallSite::trackStatistics(), and AAPotentialValuesCallSite::trackStatistics().
STATS_DECLTRACK_CSARG_ATTR
#define STATS_DECLTRACK_CSARG_ATTR (NAME)
Value:
  STATS_DECLTRACK(NAME, CSArguments,                                           \
                  BUILD_STAT_MSG_IR_ATTR(call site arguments, NAME))
Definition at line 108 of file AttributorAttributes.cpp.
Referenced by AANoFreeCallSiteArgument::trackStatistics(), AANonNullCallSiteArgument::trackStatistics(), AANoAliasCallSiteArgument::trackStatistics(), AAIsDeadCallSiteArgument::trackStatistics(), AADereferenceableCallSiteArgument::trackStatistics(), AAAlignCallSiteArgument::trackStatistics(), AANoCaptureCallSiteArgument::trackStatistics(), AAValueSimplifyCallSiteArgument::trackStatistics(), AAPrivatizablePtrCallSiteArgument::trackStatistics(), AAMemoryBehaviorCallSiteArgument::trackStatistics(), AAValueConstantRangeCallSiteArgument::trackStatistics(), AAPotentialValuesCallSiteArgument::trackStatistics(), and AANoUndefCallSiteArgument::trackStatistics().
STATS_DECLTRACK_CSRET_ATTR
#define STATS_DECLTRACK_CSRET_ATTR (NAME)
Value:
  STATS_DECLTRACK(NAME, CSReturn,                                              \
                  BUILD_STAT_MSG_IR_ATTR(call site returns, NAME))
Definition at line 118 of file AttributorAttributes.cpp.
Referenced by AANoFreeCallSiteReturned::trackStatistics(), AANonNullCallSiteReturned::trackStatistics(), AANoAliasCallSiteReturned::trackStatistics(), AAIsDeadCallSiteReturned::trackStatistics(), AANoCaptureCallSiteReturned::trackStatistics(), AAValueSimplifyCallSiteReturned::trackStatistics(), AAPrivatizablePtrCallSiteReturned::trackStatistics(), AAValueConstantRangeCallSiteReturned::trackStatistics(), AAPotentialValuesCallSiteReturned::trackStatistics(), and AANoUndefCallSiteReturned::trackStatistics().
STATS_DECLTRACK_FLOATING_ATTR
#define STATS_DECLTRACK_FLOATING_ATTR (NAME)
Value:
  STATS_DECLTRACK(NAME, Floating,                                              \
                  ("Number of floating values known to be '" #NAME "'"))
Definition at line 121 of file AttributorAttributes.cpp.
Referenced by AANoFreeFloating::trackStatistics(), AANoAliasFloating::trackStatistics(), AAIsDeadFloating::trackStatistics(), AADereferenceableFloating::trackStatistics(), AAAlignFloating::trackStatistics(), AANoCaptureFloating::trackStatistics(), AAValueSimplifyFloating::trackStatistics(), AAPrivatizablePtrFloating::trackStatistics(), AAMemoryBehaviorFloating::trackStatistics(), AAValueConstantRangeFloating::trackStatistics(), and AAPotentialValuesFloating::trackStatistics().
STATS_DECLTRACK_FN_ATTR
#define STATS_DECLTRACK_FN_ATTR (NAME) STATS_DECLTRACK(NAME, Function, BUILD_STAT_MSG_IR_ATTR(functions, NAME))
Definition at line 111 of file AttributorAttributes.cpp.
Referenced by AANoUnwindFunction::trackStatistics(), AANoSyncFunction::trackStatistics(), AANoFreeFunction::trackStatistics(), AANoRecurseFunction::trackStatistics(), AAWillReturnFunction::trackStatistics(), AAReachabilityFunction::trackStatistics(), AANoReturnFunction::trackStatistics(), AAValueSimplifyFunction::trackStatistics(), AAMemoryBehaviorFunction::trackStatistics(), AAMemoryLocationFunction::trackStatistics(), AAValueConstantRangeFunction::trackStatistics(), and AAPotentialValuesFunction::trackStatistics().
STATS_DECLTRACK_FNRET_ATTR
#define STATS_DECLTRACK_FNRET_ATTR (NAME)
Value:
  STATS_DECLTRACK(NAME, FunctionReturn,                                        \
                  BUILD_STAT_MSG_IR_ATTR(function returns, NAME))
Definition at line 115 of file AttributorAttributes.cpp.
Referenced by AANonNullFloating::trackStatistics(), AANonNullReturned::trackStatistics(), AANoAliasReturned::trackStatistics(), AAIsDeadReturned::trackStatistics(), AADereferenceableReturned::trackStatistics(), AAAlignReturned::trackStatistics(), AAValueSimplifyReturned::trackStatistics(), AAPrivatizablePtrReturned::trackStatistics(), AAValueConstantRangeReturned::trackStatistics(), AAPotentialValuesReturned::trackStatistics(), AANoUndefFloating::trackStatistics(), and AANoUndefReturned::trackStatistics().
STATS_TRACK
#define STATS_TRACK (NAME, TYPE) ++(BUILD_STAT_NAME(NAME, TYPE));
Definition at line 100 of file AttributorAttributes.cpp.
SWITCH_PK_CREATE
#define SWITCH_PK_CREATE (CLASS, IRP, PK, SUFFIX)
Value:
  case IRPosition::PK:                                                         \
    AA = new (A.Allocator) CLASS##SUFFIX(IRP, A);                              \
    ++NumAAs;                                                                  \
    break;
Definition at line 10083 of file AttributorAttributes.cpp.
SWITCH_PK_INV
#define SWITCH_PK_INV (CLASS, PK, POS_NAME)
Value:
  case IRPosition::PK:                                                         \
    llvm_unreachable("Cannot create " #CLASS " for a " POS_NAME " position!");
Definition at line 10079 of file AttributorAttributes.cpp.
Function Documentation
clampReturnedValueStates()
template<typename AAType , typename StateType = typename AAType::StateType> static void clampReturnedValueStates (Attributor & A, const AAType & QueryingAA, StateType & S, const IRPosition::CallBaseContext * CBContext = nullptr) static
Clamp the information known for all returned values of a function (identified by QueryingAA) into S.
Definition at line 480 of file AttributorAttributes.cpp.
References A, assert(), llvm::dbgs(), llvm::IRPosition::IRP_CALL_SITE_RETURNED, llvm::IRPosition::IRP_RETURNED, LLVM_DEBUG, T, and llvm::IRPosition::value().
constructPointer()
static Value * constructPointer (Type * ResTy, Type * PtrElemTy, Value * Ptr, int64_t Offset, IRBuilder< NoFolder > & IRB, const DataLayout & DL) static
Helper function to create a pointer of type ResTy, based on Ptr, and advanced by Offset bytes.
To aid later analysis the method tries to build getelement pointer instructions that traverse the natural type of Ptr if possible. If that fails, the remaining offset is adjusted byte-wise, hence through a cast to i8*.
TODO: This could probably live somewhere more prominantly if it doesn't already exist.
Definition at line 209 of file AttributorAttributes.cpp.
References assert(), llvm::dbgs(), DL, llvm::Value::getName(), llvm::Value::getType(), LLVM_DEBUG, Offset, and llvm::StringRef::str().
Referenced by AAPrivatizablePtrArgument::createInitialization(), and AAPrivatizablePtrArgument::createReplacementValues().
followUsesInContext()
template<class AAType , typename StateType = typename AAType::StateType> static void followUsesInContext (AAType & AA, Attributor & A, MustBeExecutedContextExplorer & Explorer, const Instruction * CtxI, SetVector< const Use * > & Uses, StateType & State) static
Helper function to accumulate uses.
Definition at line 683 of file AttributorAttributes.cpp.
References A, llvm::MustBeExecutedContextExplorer::begin(), llvm::MustBeExecutedContextExplorer::end(), llvm::MustBeExecutedContextExplorer::findInContextOf(), and Uses.
Referenced by followUsesInMBEC().
followUsesInMBEC()
template<class AAType , typename StateType = typename AAType::StateType> static void followUsesInMBEC (AAType & AA, Attributor & A, StateType & S, Instruction & CtxI) static
Use the must-be-executed-context around I to add information into S.
The AAType class is required to have followUseInMBEC method with the following signature and behaviour:
bool followUseInMBEC(Attributor &A, const Use *U, const Instruction *I) U - Underlying use. I - The user of the U. Returns true if the value should be tracked transitively.
Definition at line 710 of file AttributorAttributes.cpp.
References A, llvm::BB, llvm::MustBeExecutedContextExplorer::checkForAllContext(), followUsesInContext(), I, and Uses.
Referenced by AANonNullImpl::initialize(), AADereferenceableImpl::initialize(), AAAlignImpl::initialize(), and AANoUndefFloating::initialize().
genericValueTraversal()
template<typename StateTy > static bool genericValueTraversal (Attributor & A, IRPosition IRP, const AbstractAttribute & QueryingAA, StateTy & State, function_ref< bool(Value &, const Instruction *, StateTy &, bool)> VisitValueCB, const Instruction * CtxI, bool & UsedAssumedInformation, bool UseValueSimplify = true, int MaxValues = 16, function_ref< Value *(Value *)> StripCB = nullptr, bool Intraprocedural = false) static
Recursively visit all values that might become IRP at some point.
This will be done by looking through cast instructions, selects, phis, and calls with the "returned" attribute. Once we cannot look through the value any further, the callback VisitValueCB is invoked and passed the current value, the State, and a flag to indicate if we stripped anything. Stripped means that we unpacked the value associated with IRP at least once. Note that the value used for the callback may still be the value associated with IRP (due to PHIs). To limit how much effort is invested, we will never visit more values than specified by MaxValues. If Intraprocedural is set to true only values valid in the scope of CtxI will be visited and simplification into other scopes is prevented.
Definition at line 259 of file AttributorAttributes.cpp.
References A, Arg, C, llvm::dbgs(), F, llvm::IRPosition::function(), I, LLVM_DEBUG, and SI.
Referenced by llvm::AA::getAssumedUnderlyingObjects().
getKnownAlignForUse()
static unsigned getKnownAlignForUse (Attributor & A, AAAlign & QueryingAA, Value & AssociatedValue, const Use * U, const Instruction * I, bool & TrackUse) static
Definition at line 4401 of file AttributorAttributes.cpp.
References A, llvm::abs(), llvm::sampleprof::Base, llvm::IRPosition::callsite_argument(), DL, gcd(), GEP, llvm::LoadInst::getAlign(), llvm::GetPointerBaseWithConstantOffset(), llvm::LoadInst::getPointerOperand(), llvm::greatestCommonDivisor(), I, llvm::NONE, Offset, llvm::PowerOf2Floor(), and SI.
Referenced by AAAlignImpl::followUseInMBEC().
getKnownNonNullAndDerefBytesForUse()
static int64_t getKnownNonNullAndDerefBytesForUse (Attributor & A, const AbstractAttribute & QueryingAA, Value & AssociatedValue, const Use * U, const Instruction * I, bool & IsNonNull, bool & TrackUse) static
---------------------— NonNull Argument Attribute ---------------------—
Corner case when an offset is 0.
Definition at line 2260 of file AttributorAttributes.cpp.
References A, llvm::sampleprof::Base, llvm::IRPosition::callsite_argument(), DL, F, llvm::Function::getFunction(), llvm::getKnowledgeFromUse(), getMinimalBaseOfPointer(), llvm::MemoryLocation::getOrNone(), llvm::Type::getPointerAddressSpace(), llvm::GetPointerBaseWithConstantOffset(), I, llvm::NONE, llvm::NullPointerIsDefined(), and Offset.
Referenced by AADereferenceableImpl::followUseInMBEC(), and AANonNullImpl::followUseInMBEC().
getMinimalBaseOfPointer()
static const Value * getMinimalBaseOfPointer (Attributor & A, const AbstractAttribute & QueryingAA, const Value * Ptr, int64_t & BytesOffset, const DataLayout & DL, bool AllowNonInbounds = false) static
Definition at line 466 of file AttributorAttributes.cpp.
References A, llvm::sampleprof::Base, DL, llvm::Value::getType(), and stripAndAccumulateMinimalOffsets().
Referenced by getKnownNonNullAndDerefBytesForUse().
getPointerOperand()
static const Value * getPointerOperand (const Instruction * I, bool AllowVolatile) static
Get pointer operand of memory accessing instruction.
If I is not a memory accessing instruction, return nullptr. If AllowVolatile, is set to false and the instruction is volatile, return nullptr.
Definition at line 177 of file AttributorAttributes.cpp.
References I, and SI.
identifyAliveSuccessors() [1/4]
static bool identifyAliveSuccessors (Attributor & A, const BranchInst & BI, AbstractAttribute & AA, SmallVectorImpl< const Instruction * > & AliveSuccessors) static
Definition at line 3983 of file AttributorAttributes.cpp.
References A, C, llvm::BasicBlock::front(), llvm::BranchInst::getCondition(), llvm::BranchInst::getNumSuccessors(), and llvm::BranchInst::getSuccessor().
identifyAliveSuccessors() [2/4]
static bool identifyAliveSuccessors (Attributor & A, const CallBase & CB, AbstractAttribute & AA, SmallVectorImpl< const Instruction * > & AliveSuccessors) static
Definition at line 3941 of file AttributorAttributes.cpp.
References A, llvm::IRPosition::callsite_function(), llvm::BasicBlock::front(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::Instruction::getSuccessor(), llvm::Instruction::isTerminator(), and llvm::OPTIONAL.
Referenced by identifyAliveSuccessors(), and AAIsDeadFunction::updateImpl().
identifyAliveSuccessors() [3/4]
static bool identifyAliveSuccessors (Attributor & A, const InvokeInst & II, AbstractAttribute & AA, SmallVectorImpl< const Instruction * > & AliveSuccessors) static
Definition at line 3958 of file AttributorAttributes.cpp.
References A, llvm::IRPosition::callsite_function(), llvm::BasicBlock::front(), llvm::Instruction::getFunction(), llvm::InvokeInst::getUnwindDest(), identifyAliveSuccessors(), llvm::AAIsDead::mayCatchAsynchronousExceptions(), and llvm::OPTIONAL.
identifyAliveSuccessors() [4/4]
static bool identifyAliveSuccessors (Attributor & A, const SwitchInst & SI, AbstractAttribute & AA, SmallVectorImpl< const Instruction * > & AliveSuccessors) static
Definition at line 4008 of file AttributorAttributes.cpp.
References A, C, SI, and llvm::successors().
mayContainUnboundedCycle()
static bool mayContainUnboundedCycle (Function & F, Attributor & A) static
---------------------— Will-Return Attributes -------------------------—
Definition at line 2900 of file AttributorAttributes.cpp.
References A, F, llvm::ScalarEvolution::getSmallConstantMaxTripCount(), llvm::mayContainIrreducibleControl(), and llvm::scc_begin().
Referenced by AAWillReturnFunction::initialize().
STATISTIC()
STATISTIC (NumAAs , "Number of abstract attributes created")
stripAndAccumulateMinimalOffsets()
const Value * stripAndAccumulateMinimalOffsets (Attributor & A, const AbstractAttribute & QueryingAA, const Value * Val, const DataLayout & DL, APInt & Offset, bool AllowNonInbounds, bool UseAssumed = false)
Definition at line 440 of file AttributorAttributes.cpp.
References A, DL, Offset, llvm::Value::stripAndAccumulateConstantOffsets(), and llvm::IRPosition::value().
Referenced by getMinimalBaseOfPointer(), and AADereferenceableFloating::updateImpl().
Variable Documentation
ManifestInternal
cl::opt< bool > ManifestInternal("attributor-manifest-internal", cl::Hidden, cl::desc("Manifest Attributor internal string attributes."), cl::init(false)) ("attributor-manifest-internal" , cl::Hidden , cl::desc("Manifest Attributor internal string attributes.") , cl::init(false)) static
Referenced by AANoCaptureImpl::getDeducedAttributes().
MaxHeapToStackSize
cl::opt< int > MaxHeapToStackSize("max-heap-to-stack-size", cl::init(128), cl::Hidden) ("max-heap-to-stack-size" , cl::init(128) , cl::Hidden) static
Referenced by AAHeapToStackFunction::updateImpl().
MaxInterferingWrites
cl::opt< unsigned > MaxInterferingWrites("attributor-max-interfering-writes", cl::Hidden, cl::desc("Maximum number of interfering writes to " "check before assuming all might interfere."), cl::init(6)) ("attributor-max-interfering-writes" , cl::Hidden , cl::desc("Maximum number of interfering writes to " "check before assuming all might interfere.") , cl::init(6)) static
Referenced by AAPointerInfoImpl::forallInterferingWrites().
MaxPotentialValues
cl::opt< unsigned, true > MaxPotentialValues("attributor-max-potential-values", cl::Hidden, cl::desc("Maximum number of potential values to be " "tracked for each position."), cl::location(llvm::PotentialConstantIntValuesState::MaxPotentialValues), cl::init(7)) ("attributor-max-potential-values" , cl::Hidden , cl::desc("Maximum number of potential values to be " "tracked for each position.") , cl::location(llvm::PotentialConstantIntValuesState::MaxPotentialValues) , cl::init(7)) static