LLVM: lib/CodeGen/CallingConvLower.cpp File Reference
CallingConvLower.cpp File Reference
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/SaveAndRestore.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
Functions
static bool isValueTypeInRegForCC (CallingConv::ID CC, MVT VT)
Function Documentation
isValueTypeInRegForCC()
static bool isValueTypeInRegForCC (CallingConv::ID CC, MVT VT) static
Definition at line 198 of file CallingConvLower.cpp.
References llvm::MVT::isInteger(), llvm::MVT::isVector(), llvm::CallingConv::X86_FastCall, and llvm::CallingConv::X86_VectorCall.
Referenced by llvm::CCState::getRemainingRegParmsForType().