LLVM: llvm::RISCVFrameLowering Class Reference
llvm::RISCVFrameLowering Class Reference
#include "Target/RISCV/RISCVFrameLowering.h"
Public Member Functions
RISCVFrameLowering (const RISCVSubtarget &STI)
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
StackOffset getFrameIndexReference (const MachineFunction &MF, int FI, Register &FrameReg) const override
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS) const override
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS) const override
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
bool hasBP (const MachineFunction &MF) const
bool hasReservedCallFrame (const MachineFunction &MF) const override
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const override
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const override
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, MutableArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const override
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
uint64_t getFirstSPAdjustAmount (const MachineFunction &MF) const
bool canUseAsPrologue (const MachineBasicBlock &MBB) const override
Check whether or not the given MBB can be used as a prologue for the target.
bool canUseAsEpilogue (const MachineBasicBlock &MBB) const override
Check whether or not the given MBB can be used as a epilogue for the target.
bool isSupportedStackID (TargetStackID::Value ID) const override
TargetStackID::Value getStackIDForScalableVectors () const override
Returns the StackID that scalable vectors should be associated with.
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align(1), bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
Align getStackAlign () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
Align getTransientStackAlign () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual unsigned getStackAlignmentSkew (const MachineFunction &MF) const
Return the skew that has to be applied to stack alignment under certain conditions (e.g.
virtual bool isStackIdSafeForLocalArea (unsigned StackId) const
This method returns whether or not it is safe for an object with the given stack id to be bundled into the local area.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool allocateScavengingFrameIndexesNearIncomingSP (const MachineFunction &MF) const
Control the placement of special register scavenging spill slots when allocating a stack frame.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI, unsigned &MinCSFrameIndex, unsigned &MaxCSFrameIndex) const
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
virtual bool targetHandlesStackFrameRounding () const
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
virtual bool enableShrinkWrapping (const MachineFunction &MF) const
Returns true if the target will correctly handle shrink wrapping.
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual bool enableCalleeSaveSkip (const MachineFunction &MF) const
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
virtual void emitCalleeSavedFrameMovesFullCFA (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI) const
With basic block sections, emit callee saved frame moves for basic blocks that are in a different section.
virtual void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Replace a StackProbe stub (if any) with the actual probe code inline.
virtual bool stackProbeFunctionModifiesSP () const
Does the stack probe function call return with a modified stack pointer?
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual bool keepFramePointer (const MachineFunction &MF) const
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual StackOffset getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, Register &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual StackOffset getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
virtual void processFunctionBeforeFrameIndicesReplaced (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameIndicesReplaced - This method is called immediately before MO_FrameIndex operands are eliminated, but after the frame is finalized.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual bool isProfitableForNoCSROpt (const Function &F) const
Check if the no-CSR optimisation is profitable for the given function.
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual Register getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
virtual DwarfFrameBase getDwarfFrameBase (const MachineFunction &MF) const
Return the frame base information to be encoded in the DWARF subprogram debug info.
Protected Attributes
const RISCVSubtarget & STI
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp , StackGrowsDown }
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Detailed Description
Definition at line 22 of file RISCVFrameLowering.h.
Constructor & Destructor Documentation
RISCVFrameLowering()
llvm::RISCVFrameLowering::RISCVFrameLowering (const RISCVSubtarget & STI) inline explicit
Definition at line 24 of file RISCVFrameLowering.h.
Member Function Documentation
canUseAsEpilogue()
bool RISCVFrameLowering::canUseAsEpilogue (const MachineBasicBlock & MBB) const override virtual
Check whether or not the given MBB can be used as a epilogue for the target.
The epilogue will be inserted before the first terminator of that block. This method is used by the shrink-wrapping pass to decide if MBB will be correctly handled by the target. As soon as the target enable shrink-wrapping without overriding this method, we assume that each basic block is a valid epilogue.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1136 of file RISCVFrameLowering.cpp.
References llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getParent(), MBB, llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_empty(), and llvm::MachineBasicBlock::succ_size().
canUseAsPrologue()
bool RISCVFrameLowering::canUseAsPrologue (const MachineBasicBlock & MBB) const override virtual
Check whether or not the given MBB can be used as a prologue for the target.
The prologue will be inserted first in this basic block. This method is used by the shrink-wrapping pass to decide if MBB will be correctly handled by the target. As soon as the target enable shrink-wrapping without overriding this method, we assume that each basic block is a valid prologue.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1119 of file RISCVFrameLowering.cpp.
References llvm::RegScavenger::enterBasicBlock(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getParent(), llvm::RegScavenger::isRegUsed(), and MBB.
determineCalleeSaves()
void RISCVFrameLowering::determineCalleeSaves (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS) const override virtual
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
The default implementation checks populates the SavedRegs bitset with all registers which are modified in the function, targets may override this function to save additional registers. This method also sets up the register scavenger ensuring there is a free register or a frameindex available. This method should not be called by any passes outside of PEI, because it may change state passed in by MF and RS. The preferred interface outside PEI is getCalleeSaves.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 799 of file RISCVFrameLowering.cpp.
References contains(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::RISCVABI::getBPReg(), llvm::MachineRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), hasBP(), llvm::MachineFrameInfo::hasCalls(), llvm::Function::hasFnAttribute(), hasFP(), llvm::RISCVSubtarget::hasStdExtF(), and llvm::BitVector::set().
eliminateCallFramePseudoInstr()
MachineBasicBlock::iterator RISCVFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions. Returns an iterator pointing to the instruction after the replaced one.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 972 of file RISCVFrameLowering.cpp.
References llvm::TargetFrameLowering::alignSPAdjust(), DL, llvm::MachineBasicBlock::erase(), hasReservedCallFrame(), MBB, MI, and llvm::MachineInstr::NoFlags.
emitEpilogue()
void RISCVFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 546 of file RISCVFrameLowering.cpp.
References assert(), llvm::MachineBasicBlock::begin(), DL, emitSCSEpilogue(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::FrameDestroy, llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::Function::getCallingConv(), getFirstSPAdjustAmount(), llvm::MachineBasicBlock::getFirstTerminator(), getFPReg(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), getNonLibcallCSI(), llvm::RISCVSubtarget::getRegisterInfo(), getSPReg(), llvm::MachineFrameInfo::getStackSize(), llvm::CallingConv::GHC, hasFP(), llvm::MachineFrameInfo::hasVarSizedObjects(), MBB, MBBI, and STI.
emitPrologue()
void RISCVFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 345 of file RISCVFrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineFrameInfo::adjustsStack(), llvm::alignTo(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MCCFIInstruction::cfiDefCfa(), llvm::MCCFIInstruction::cfiDefCfaOffset(), llvm::MCCFIInstruction::createOffset(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::LLVMContext::diagnose(), DL, emitSCSPrologue(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::FrameSetup, llvm::RISCVABI::getBPReg(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::Function::getCallingConv(), llvm::Function::getContext(), getFirstSPAdjustAmount(), getFPReg(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::RISCVSubtarget::getInstrInfo(), getLibCallID(), llvm::MachineFrameInfo::getMaxAlign(), getNonLibcallCSI(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFunction::getRegInfo(), llvm::RISCVSubtarget::getRegisterInfo(), getSPReg(), llvm::MachineFrameInfo::getStackSize(), llvm::RISCVSubtarget::getXLen(), llvm::CallingConv::GHC, hasBP(), hasFP(), llvm::RISCVSubtarget::isRegisterReservedByUser(), llvm::Log2(), MBB, MBBI, Offset, llvm::MachineInstrBuilder::setMIFlag(), size(), STI, TII, and llvm::Align::value().
getFirstSPAdjustAmount()
uint64_t RISCVFrameLowering::getFirstSPAdjustAmount (const MachineFunction & MF) const
Definition at line 1011 of file RISCVFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::TargetFrameLowering::getStackAlign(), and llvm::Align::value().
Referenced by emitEpilogue(), emitPrologue(), and getFrameIndexReference().
getFrameIndexReference()
StackOffset RISCVFrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, Register & FrameReg) const override virtual
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
Returns the displacement from the frame register to the stack frame of the specified index, along with the frame register used (in output arg FrameReg).
The offset is returned directly, and the base register is returned via FrameReg.
This is the default implementation which is overridden for some targets.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 629 of file RISCVFrameLowering.cpp.
References llvm::alignTo(), assert(), llvm::TargetStackID::Default, llvm::StackOffset::get(), llvm::RISCVABI::getBPReg(), llvm::MachineFrameInfo::getCalleeSavedInfo(), getFirstSPAdjustAmount(), llvm::StackOffset::getFixed(), llvm::MachineFunction::getFrameInfo(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::MachineFunction::getInfo(), getNonLibcallCSI(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getOffsetAdjustment(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::StackOffset::getScalable(), llvm::MachineFrameInfo::getStackID(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), hasBP(), hasFP(), llvm::TargetRegisterInfo::hasStackRealignment(), llvm::MachineFrameInfo::isFixedObjectIndex(), Offset, and llvm::TargetStackID::ScalableVector.
getStackIDForScalableVectors()
TargetStackID::Value RISCVFrameLowering::getStackIDForScalableVectors () const override virtual
Returns the StackID that scalable vectors should be associated with.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1178 of file RISCVFrameLowering.cpp.
References llvm::TargetStackID::ScalableVector.
hasBP()
bool RISCVFrameLowering::hasBP (const MachineFunction & MF) const
Definition at line 236 of file RISCVFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::RISCVSubtarget::getRegisterInfo(), hasReservedCallFrame(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFrameInfo::isMaxCallFrameSizeComputed(), STI, and TRI.
Referenced by determineCalleeSaves(), emitPrologue(), getFrameIndexReference(), and llvm::RISCVRegisterInfo::getReservedRegs().
hasFP()
bool RISCVFrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register.
For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 227 of file RISCVFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFrameInfo::isFrameAddressTaken(), and llvm::TargetMachine::Options.
Referenced by determineCalleeSaves(), emitEpilogue(), emitPrologue(), getFrameIndexReference(), llvm::RISCVRegisterInfo::getReservedRegs(), hasReservedCallFrame(), and processFunctionBeforeFrameFinalized().
hasReservedCallFrame()
bool RISCVFrameLowering::hasReservedCallFrame (const MachineFunction & MF) const override virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 966 of file RISCVFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), hasFP(), hasRVVFrameObject(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by eliminateCallFramePseudoInstr(), and hasBP().
isSupportedStackID()
bool RISCVFrameLowering::isSupportedStackID (TargetStackID::Value ID) const override virtual
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1165 of file RISCVFrameLowering.cpp.
References llvm::TargetStackID::Default, llvm_unreachable, llvm::TargetStackID::NoAlloc, llvm::TargetStackID::ScalableVector, llvm::TargetStackID::SGPRSpill, and llvm::TargetStackID::WasmLocal.
processFunctionBeforeFrameFinalized()
void RISCVFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS) const override virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 885 of file RISCVFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::MachineFrameInfo::CreateStackObject(), llvm::TargetStackID::Default, llvm::MachineFrameInfo::estimateStackSize(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getObjectSize(), llvm::TargetFrameLowering::getStackAlign(), llvm::MachineFrameInfo::getStackID(), llvm::MachineFunction::getSubtarget(), hasFP(), hasRVVSpillWithFIs(), Size, TII, and llvm::Align::value().
restoreCalleeSavedRegisters()
bool RISCVFrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, MutableArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo * TRI) const override virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
If it returns true, and any of the registers in CSI is not restored, it sets the corresponding Restored flag in CSI to false. Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1074 of file RISCVFrameLowering.cpp.
References llvm::MachineInstrBuilder::addExternalSymbol(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::CS, DL, llvm::MachineBasicBlock::end(), llvm::MachineInstr::FrameDestroy, llvm::TargetSubtargetInfo::getInstrInfo(), getNonLibcallCSI(), llvm::MachineBasicBlock::getParent(), getRestoreLibCallName(), llvm::MachineFunction::getSubtarget(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), MBB, MI, llvm::RISCVII::MO_CALL, llvm::MachineInstrBuilder::setMIFlag(), TII, and TRI.
spillCalleeSavedRegisters()
bool RISCVFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1037 of file RISCVFrameLowering.cpp.
References llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineBasicBlock::addLiveIn(), llvm::BuildMI(), llvm::CS, DL, llvm::MachineBasicBlock::end(), llvm::MachineInstr::FrameSetup, llvm::TargetSubtargetInfo::getInstrInfo(), getNonLibcallCSI(), llvm::MachineBasicBlock::getParent(), getSpillLibCallName(), llvm::MachineFunction::getSubtarget(), llvm::MachineBasicBlock::isLiveIn(), MBB, MI, llvm::RISCVII::MO_CALL, llvm::MachineInstrBuilder::setMIFlag(), llvm::HexagonInstrInfo::storeRegToStackSlot(), TII, and TRI.
Member Data Documentation
STI
const RISCVSubtarget& llvm::RISCVFrameLowering::STI protected
Definition at line 72 of file RISCVFrameLowering.h.
Referenced by emitEpilogue(), emitPrologue(), and hasBP().
The documentation for this class was generated from the following files:
lib/Target/RISCV/RISCVFrameLowering.h
lib/Target/RISCV/RISCVFrameLowering.cpp