LLVM: llvm::GetElementPtrInst Class Reference
llvm::GetElementPtrInst Class Reference
an instruction for type-safe pointer arithmetic to access elements of arrays and structs
#include "llvm/IR/Instructions.h"
Public Member Functions
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
Type * getSourceElementType () const
void setSourceElementType (Type *Ty)
void setResultElementType (Type *Ty)
Type * getResultElementType () const
unsigned getAddressSpace () const
Returns the address space of this instruction's pointer type.
op_iterator idx_begin ()
const_op_iterator idx_begin () const
op_iterator idx_end ()
const_op_iterator idx_end () const
iterator_range< op_iterator > indices ()
iterator_range< const_op_iterator > indices () const
Value * getPointerOperand ()
const Value * getPointerOperand () const
Type * getPointerOperandType () const
Method to return the pointer operand as a PointerType.
unsigned getPointerAddressSpace () const
Returns the address space of the pointer operand.
unsigned getNumIndices () const
bool hasIndices () const
bool hasAllZeroIndices () const
Return true if all of the indices of this GEP are zeros.
bool hasAllConstantIndices () const
Return true if all of the indices of this GEP are constant integers.
void setIsInBounds (bool b=true)
Set or clear the inbounds flag on this GEP instruction.
bool isInBounds () const
Determine whether the GEP has the inbounds flag.
bool accumulateConstantOffset (const DataLayout &DL, APInt &Offset) const
Accumulate the constant address offset of this GEP if possible.
bool collectOffset (const DataLayout &DL, unsigned BitWidth, MapVector< Value *, APInt > &VariableOffsets, APInt &ConstantOffset) const
Public Member Functions inherited from llvm::Instruction
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
Instruction * user_back ()
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
const Instruction * user_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
const Module * getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Module * getModule ()
const Function * getFunction () const
Return the function this instruction belongs to.
Function * getFunction ()
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
SymbolTableList< Instruction >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
void insertBefore (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
void insertAfter (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
void moveBefore (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
void moveBefore (BasicBlock &BB, SymbolTableList< Instruction >::iterator I)
Unlink this instruction and insert into BB before I.
void moveAfter (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
bool comesBefore (const Instruction *Other) const
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
unsigned getOpcode () const
Returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isExceptionalTerminator () const
bool isOnlyUserOfAnyOperand ()
It checks if this instruction is the only user of at least one of its operands.
bool isIndirectTerminator () const
bool isLogicalShift () const
Return true if this is a logical shift left or a logical shift right.
bool isArithmeticShift () const
Return true if this is an arithmetic shift right.
bool isBitwiseLogicOp () const
Return true if this is and/or/xor.
bool hasMetadata () const
Return true if this instruction has any metadata attached to it.
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
Return true if this instruction has the given type of metadata attached.
MDNode * getMetadata (unsigned KindID) const
Get the metadata of given kind attached to this Instruction.
MDNode * getMetadata (StringRef Kind) const
Get the metadata of given kind attached to this Instruction.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Get all metadata attached to this Instruction.
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
This does the same thing as getAllMetadata, except that it filters out the debug location.
void setMetadata (unsigned KindID, MDNode *Node)
Set the metadata of the specified kind to the specified node.
void setMetadata (StringRef Kind, MDNode *Node)
void copyMetadata (const Instruction &SrcInst, ArrayRef< unsigned > WL=ArrayRef< unsigned >())
Copy metadata from SrcInst to this instruction.
void swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
void addAnnotationMetadata (StringRef Annotation)
Adds an !annotation metadata node with Annotation to this instruction.
AAMDNodes getAAMetadata () const
Returns the AA metadata for this instruction.
void setAAMetadata (const AAMDNodes &N)
Sets the AA metadata on this instruction from the AAMDNodes structure.
bool extractProfMetadata (uint64_t &TrueVal, uint64_t &FalseVal) const
Retrieve the raw weight values of a conditional branch or select.
bool extractProfTotalWeight (uint64_t &TotalVal) const
Retrieve total raw weight values of a branch.
void setDebugLoc (DebugLoc Loc)
Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
Return the debug location for this node as a DebugLoc.
void setHasNoUnsignedWrap (bool b=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedWrap (bool b=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
void setIsExact (bool b=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
bool hasNoUnsignedWrap () const
Determine whether the no unsigned wrap flag is set.
bool hasNoSignedWrap () const
Determine whether the no signed wrap flag is set.
bool hasPoisonGeneratingFlags () const
Return true if this operator has flags which may cause this instruction to evaluate to poison despite having non-poison inputs.
void dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
void dropUndefImplyingAttrsAndUnknownMetadata (ArrayRef< unsigned > KnownIDs={})
This function drops non-debug unknown metadata (through dropUnknownNonDebugMetadata).
bool isExact () const
Determine whether the exact flag is set.
void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
void setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
bool isFast () const
Determine whether all fast-math-flags are set.
bool hasAllowReassoc () const
Determine whether the allow-reassociation flag is set.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
bool hasAllowContract () const
Determine whether the allow-contract flag is set.
bool hasApproxFunc () const
Determine whether the approximate-math-functions flag is set.
FastMathFlags getFastMathFlags () const
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
void copyIRFlags (const Value *V, bool IncludeWrapFlags=true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
void andIRFlags (const Value *V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
void applyMergedLocation (const DILocation *LocA, const DILocation *LocB)
Merge 2 debug locations and apply it to the Instruction.
void updateLocationAfterHoist ()
Updates the debug location given that the instruction has been hoisted from a block to a predecessor of that block.
void dropLocation ()
Drop the instruction's debug location.
bool isAssociative () const LLVM_READONLY
Return true if the instruction is associative:
bool isCommutative () const LLVM_READONLY
Return true if the instruction is commutative:
bool isIdempotent () const
Return true if the instruction is idempotent:
bool isNilpotent () const
Return true if the instruction is nilpotent:
bool mayWriteToMemory () const
Return true if this instruction may modify memory.
bool mayReadFromMemory () const
Return true if this instruction may read memory.
bool mayReadOrWriteMemory () const
Return true if this instruction may read or write memory.
bool isAtomic () const
Return true if this instruction has an AtomicOrdering of unordered or higher.
bool hasAtomicLoad () const
Return true if this atomic instruction loads from memory.
bool hasAtomicStore () const
Return true if this atomic instruction stores to memory.
bool isVolatile () const
Return true if this instruction has a volatile memory access.
bool mayThrow () const
Return true if this instruction may throw an exception.
bool isFenceLike () const
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
bool mayHaveSideEffects () const
Return true if the instruction may have side effects.
bool isSafeToRemove () const
Return true if the instruction can be removed if the result is unused.
bool willReturn () const
Return true if the instruction will return (unwinding is considered as a form of returning control flow here).
bool isEHPad () const
Return true if the instruction is a variety of EH-block.
bool isLifetimeStartOrEnd () const
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
bool isLaunderOrStripInvariantGroup () const
Return true if the instruction is a llvm.launder.invariant.group or llvm.strip.invariant.group.
bool isDebugOrPseudoInst () const
Return true if the instruction is a DbgInfoIntrinsic or PseudoProbeInst.
const Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the next non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false)
const Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the previous non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false)
Instruction * clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
bool isIdenticalTo (const Instruction *I) const
Return true if the specified instruction is exactly identical to the current one.
bool isIdenticalToWhenDefined (const Instruction *I) const
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
This function determines if the specified instruction executes the same operation as the current one.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Return true if there are any uses of this instruction in blocks other than the specified block.
unsigned getNumSuccessors () const
Return the number of successors that this instruction has.
BasicBlock * getSuccessor (unsigned Idx) const
Return the specified successor. This instruction must be a terminator.
void setSuccessor (unsigned Idx, BasicBlock *BB)
Update the specified successor to point at the provided block.
void replaceSuccessorWith (BasicBlock *OldBB, BasicBlock *NewBB)
Replace specified successor OldBB to point at the provided block.
void dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs)
Drop all unknown metadata except for debug locations.
void dropUnknownNonDebugMetadata ()
void dropUnknownNonDebugMetadata (unsigned ID1)
void dropUnknownNonDebugMetadata (unsigned ID1, unsigned ID2)
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isTransitiveUsedByMetadataOnly () const
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
Instruction * getPrevNode ()
const Instruction * getPrevNode () const
Get the previous node, or nullptr for the list head.
Instruction * getNextNode ()
Get the next node, or nullptr for the list tail.
const Instruction * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static GetElementPtrInst * Create (Type *PointeeType, Value *Ptr, ArrayRef< Value * > IdxList, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
static GetElementPtrInst * Create (Type *PointeeType, Value *Ptr, ArrayRef< Value * > IdxList, const Twine &NameStr, BasicBlock *InsertAtEnd)
static GetElementPtrInst * CreateInBounds (Type *PointeeType, Value *Ptr, ArrayRef< Value * > IdxList, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
Create an "inbounds" getelementptr.
static GetElementPtrInst * CreateInBounds (Type *PointeeType, Value *Ptr, ArrayRef< Value * > IdxList, const Twine &NameStr, BasicBlock *InsertAtEnd)
static Type * getIndexedType (Type *Ty, ArrayRef< Value * > IdxList)
Returns the result type of a getelementptr with the given source element type and indexes.
static Type * getIndexedType (Type *Ty, ArrayRef< Constant * > IdxList)
static Type * getIndexedType (Type *Ty, ArrayRef< uint64_t > IdxList)
static Type * getTypeAtIndex (Type *Ty, Value *Idx)
Return the type of the element at the given index of an indexable type.
static Type * getTypeAtIndex (Type *Ty, uint64_t Idx)
static unsigned getPointerOperandIndex ()
static Type * getGEPReturnType (Type *ElTy, Value *Ptr, ArrayRef< Value * > IdxList)
Returns the pointer type returned by the GEP instruction, which may be a vector of pointers.
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isUnaryOp (unsigned Opcode)
static bool isBinaryOp (unsigned Opcode)
static bool isIntDivRem (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isBitwiseLogicOp (unsigned Opcode)
Determine if the Opcode is and/or/xor.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isFuncletPad (unsigned OpCode)
Determine if the OpCode is one of the FuncletPadInst instructions.
static bool isExceptionalTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator related to exception handling.
static bool isIndirectTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator with indirect targets.
static bool isAssociative (unsigned Opcode)
static bool isCommutative (unsigned Opcode)
static bool isIdempotent (unsigned Opcode)
static bool isNilpotent (unsigned Opcode)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Member Functions
GetElementPtrInst * cloneImpl () const
Protected Member Functions inherited from llvm::Instruction
~Instruction ()
template<typename BitfieldElement >
BitfieldElement::Type getSubclassData () const
template<typename BitfieldElement >
void setSubclassData (typename BitfieldElement::Type Value)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Protected Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Friends
class Instruction
Additional Inherited Members
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0 , CompareUsingScalarTypes = 1<<1 }
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
enum TermOps
enum UnaryOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum FuncletPadOps
enum OtherOps
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::Instruction
using OpaqueField = Bitfield::Element<uint16_t, 0, 15>
template<unsigned Offset>
using AlignmentBitfieldElementT
template<unsigned Offset>
using BoolBitfieldElementT = typename Bitfield::Element<bool, Offset, 1>
template<unsigned Offset>
using AtomicOrderingBitfieldElementT
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
an instruction for type-safe pointer arithmetic to access elements of arrays and structs
Definition at line 930 of file Instructions.h.
Member Function Documentation
accumulateConstantOffset()
bool GetElementPtrInst::accumulateConstantOffset (const DataLayout & DL, APInt & Offset) const
Accumulate the constant address offset of this GEP if possible.
This routine accepts an APInt into which it will accumulate the constant offset of this GEP if the GEP is in fact constant. If the GEP is not all-constant, it returns false and the value of the offset APInt is undefined (it is not preserved!). The APInt passed into this routine must be at least as wide as the IntPtr type for the address space of the base GEP pointer.
Definition at line 1814 of file Instructions.cpp.
References DL, llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and Offset.
classof() [1/2]
static bool llvm::GetElementPtrInst::classof (const Instruction * I) inline static
Definition at line 1136 of file Instructions.h.
References I, and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by classof().
classof() [2/2]
static bool llvm::GetElementPtrInst::classof (const Value * V) inline static
Definition at line 1139 of file Instructions.h.
References classof(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
cloneImpl()
GetElementPtrInst * GetElementPtrInst::cloneImpl () const protected
Definition at line 4604 of file Instructions.cpp.
References llvm::User::getNumOperands().
collectOffset()
bool GetElementPtrInst::collectOffset (const DataLayout & DL, unsigned BitWidth, MapVector< Value *, APInt > & VariableOffsets, APInt & ConstantOffset) const
Definition at line 1820 of file Instructions.cpp.
References llvm::BitWidth, DL, and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Create() [1/2]
static GetElementPtrInst * llvm::GetElementPtrInst::Create (Type * PointeeType, Value * Ptr, ArrayRef< Value * > IdxList, const Twine & NameStr, BasicBlock * InsertAtEnd) inline static
Definition at line 968 of file Instructions.h.
References assert(), llvm::Type::getScalarType(), and llvm::Value::getType().
Create() [2/2]
static GetElementPtrInst * llvm::GetElementPtrInst::Create (Type * PointeeType, Value * Ptr, ArrayRef< Value * > IdxList, const Twine & NameStr = "", Instruction * InsertBefore = nullptr) inline static
Definition at line 956 of file Instructions.h.
References assert(), llvm::Type::getScalarType(), and llvm::Value::getType().
Referenced by buildNew(), convertBitCastToGEP(), llvm::IRBuilderBase::CreateConstGEP1_32(), llvm::IRBuilderBase::CreateConstGEP1_64(), llvm::IRBuilderBase::CreateConstGEP2_32(), llvm::IRBuilderBase::CreateConstGEP2_64(), llvm::IRBuilderBase::CreateGEP(), llvm::IRBuilderBase::CreateGEP(), CreateInBounds(), CreateInBounds(), doPromotion(), llvm::InstCombinerImpl::foldPHIArgGEPIntoPHI(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::fuzzerop::gepDescriptor(), llvm::ConstantExpr::getAsInstruction(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitGEPOfGEP(), llvm::InstCombinerImpl::visitGetElementPtrInst(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
CreateInBounds() [1/2]
static GetElementPtrInst * llvm::GetElementPtrInst::CreateInBounds (Type * PointeeType, Value * Ptr, ArrayRef< Value * > IdxList, const Twine & NameStr, BasicBlock * InsertAtEnd) inline static
Definition at line 992 of file Instructions.h.
References Create(), and GEP.
CreateInBounds() [2/2]
static GetElementPtrInst * llvm::GetElementPtrInst::CreateInBounds (Type * PointeeType, Value * Ptr, ArrayRef< Value * > IdxList, const Twine & NameStr = "", Instruction * InsertBefore = nullptr) inline static
Create an "inbounds" getelementptr.
See the documentation for the "inbounds" flag in LangRef.html for details.
Definition at line 983 of file Instructions.h.
References Create(), and GEP.
Referenced by llvm::IRBuilderBase::CreateConstInBoundsGEP1_32(), llvm::IRBuilderBase::CreateConstInBoundsGEP1_64(), llvm::IRBuilderBase::CreateConstInBoundsGEP2_32(), llvm::IRBuilderBase::CreateConstInBoundsGEP2_64(), llvm::IRBuilderBase::CreateInBoundsGEP(), llvm::IRBuilderBase::CreateInBoundsGEP(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::ConstantExpr::getAsInstruction(), simplifyAllocaArraySize(), tryToShorten(), llvm::InstCombinerImpl::visitGEPOfGEP(), and llvm::InstCombinerImpl::visitGetElementPtrInst().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::GetElementPtrInst::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
getAddressSpace()
unsigned llvm::GetElementPtrInst::getAddressSpace () const inline
Returns the address space of this instruction's pointer type.
Definition at line 1017 of file Instructions.h.
References getPointerAddressSpace().
getGEPReturnType()
static Type * llvm::GetElementPtrInst::getGEPReturnType (Type * ElTy, Value * Ptr, ArrayRef< Value * > IdxList) inline static
Returns the pointer type returned by the GEP instruction, which may be a vector of pointers.
Definition at line 1076 of file Instructions.h.
References llvm::checkGEPType(), llvm::VectorType::get(), llvm::PointerType::get(), getIndexedType(), llvm::Type::getScalarType(), llvm::Value::getType(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::ConstantFoldGetElementPtr(), llvm::IRBuilderBase::CreatePreserveArrayAccessIndex(), and llvm::IRBuilderBase::CreatePreserveStructAccessIndex().
getIndexedType() [1/3]
Type * GetElementPtrInst::getIndexedType (Type * Ty, ArrayRef< Constant * > IdxList) static
Definition at line 1772 of file Instructions.cpp.
References getIndexedTypeInternal().
getIndexedType() [2/3]
Type * GetElementPtrInst::getIndexedType (Type * Ty, ArrayRef< uint64_t > IdxList) static
Definition at line 1777 of file Instructions.cpp.
References getIndexedTypeInternal().
getIndexedType() [3/3]
Type * GetElementPtrInst::getIndexedType (Type * Ty, ArrayRef< Value * > IdxList) static
Returns the result type of a getelementptr with the given source element type and indexes.
Null is returned if the indices are invalid for the specified source element type.
Definition at line 1768 of file Instructions.cpp.
References getIndexedTypeInternal().
Referenced by canReplaceGEPIdxWithZero(), llvm::ConstantFoldGetElementPtr(), doPromotion(), getGEPReturnType(), llvm::ConstantExpr::getGetElementPtr(), and SimplifyGEPInst().
getNumIndices()
unsigned llvm::GetElementPtrInst::getNumIndices () const inline
Definition at line 1098 of file Instructions.h.
References llvm::User::getNumOperands().
getPointerAddressSpace()
unsigned llvm::GetElementPtrInst::getPointerAddressSpace () const inline
Returns the address space of the pointer operand.
Definition at line 1070 of file Instructions.h.
References llvm::Type::getPointerAddressSpace(), and getPointerOperandType().
Referenced by getAddressSpace().
getPointerOperand() [1/2]
Value * llvm::GetElementPtrInst::getPointerOperand () inline
Definition at line 1053 of file Instructions.h.
References llvm::User::getOperand().
Referenced by getPointerOperandType().
getPointerOperand() [2/2]
const Value * llvm::GetElementPtrInst::getPointerOperand () const inline
Definition at line 1056 of file Instructions.h.
References llvm::User::getOperand().
getPointerOperandIndex()
static unsigned llvm::GetElementPtrInst::getPointerOperandIndex () inline static
Definition at line 1059 of file Instructions.h.
getPointerOperandType()
Type * llvm::GetElementPtrInst::getPointerOperandType () const inline
Method to return the pointer operand as a PointerType.
Definition at line 1065 of file Instructions.h.
References getPointerOperand(), and llvm::Value::getType().
Referenced by getPointerAddressSpace().
getResultElementType()
Type * llvm::GetElementPtrInst::getResultElementType () const inline
Definition at line 1010 of file Instructions.h.
References assert(), and llvm::Value::getType().
getSourceElementType()
Type * llvm::GetElementPtrInst::getSourceElementType () const inline
Definition at line 1005 of file Instructions.h.
Referenced by llvm::InstCombinerImpl::foldPHIArgGEPIntoPHI().
getTypeAtIndex() [1/2]
Type * GetElementPtrInst::getTypeAtIndex (Type * Ty, uint64_t Idx) static
Definition at line 1743 of file Instructions.cpp.
References Idx, and llvm::Vector.
getTypeAtIndex() [2/2]
Type * GetElementPtrInst::getTypeAtIndex (Type * Ty, Value * Idx) static
Return the type of the element at the given index of an indexable type.
This is equivalent to "getIndexedType(Agg, {Zero, Idx})".
Returns null if the type can't be indexed, or the given index is not legal for the given type.
Definition at line 1728 of file Instructions.cpp.
References Idx, and llvm::Vector.
Referenced by convertBitCastToGEP(), doPromotion(), FoldBitCast(), llvm::ScalarEvolution::getGEPExpr(), getIndexedTypeInternal(), and llvm::InstCombinerImpl::visitGetElementPtrInst().
hasAllConstantIndices()
bool GetElementPtrInst::hasAllConstantIndices () const
Return true if all of the indices of this GEP are constant integers.
hasAllConstantIndices - Return true if all of the indices of this GEP are constant integers.
If so, the result pointer and the first operand have a constant offset between them.
Definition at line 1798 of file Instructions.cpp.
References llvm::User::getNumOperands(), and llvm::User::getOperand().
hasAllZeroIndices()
bool GetElementPtrInst::hasAllZeroIndices () const
Return true if all of the indices of this GEP are zeros.
hasAllZeroIndices - Return true if all of the indices of this GEP are zeros.
If so, the result pointer and the first operand have the same value, just potentially different types.
Definition at line 1784 of file Instructions.cpp.
References llvm::User::getNumOperands(), and llvm::User::getOperand().
hasIndices()
bool llvm::GetElementPtrInst::hasIndices () const inline
Definition at line 1102 of file Instructions.h.
References llvm::User::getNumOperands().
idx_begin() [1/2]
op_iterator llvm::GetElementPtrInst::idx_begin () inline
Definition at line 1040 of file Instructions.h.
References llvm::User::op_begin().
Referenced by indices(), and indices().
idx_begin() [2/2]
const_op_iterator llvm::GetElementPtrInst::idx_begin () const inline
Definition at line 1041 of file Instructions.h.
References llvm::User::op_begin().
idx_end() [1/2]
op_iterator llvm::GetElementPtrInst::idx_end () inline
Definition at line 1042 of file Instructions.h.
References llvm::User::op_end().
Referenced by indices(), and indices().
idx_end() [2/2]
const_op_iterator llvm::GetElementPtrInst::idx_end () const inline
Definition at line 1043 of file Instructions.h.
References llvm::User::op_end().
indices() [1/2]
iterator_range< op_iterator > llvm::GetElementPtrInst::indices () inline
Definition at line 1045 of file Instructions.h.
References idx_begin(), idx_end(), and llvm::make_range().
indices() [2/2]
iterator_range< const_op_iterator > llvm::GetElementPtrInst::indices () const inline
Definition at line 1049 of file Instructions.h.
References idx_begin(), idx_end(), and llvm::make_range().
isInBounds()
bool GetElementPtrInst::isInBounds () const
Determine whether the GEP has the inbounds flag.
Definition at line 1810 of file Instructions.cpp.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
setIsInBounds()
void GetElementPtrInst::setIsInBounds (bool b = true)
Set or clear the inbounds flag on this GEP instruction.
See LangRef.html for the meaning of inbounds on a getelementptr.
Definition at line 1806 of file Instructions.cpp.
References B, and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::InstCombinerImpl::visitGetElementPtrInst().
setResultElementType()
void llvm::GetElementPtrInst::setResultElementType (Type * Ty) inline
Definition at line 1008 of file Instructions.h.
setSourceElementType()
void llvm::GetElementPtrInst::setSourceElementType (Type * Ty) inline
Definition at line 1007 of file Instructions.h.
Friends And Related Symbol Documentation
Instruction
friend class Instruction friend
Definition at line 951 of file Instructions.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Instructions.h
lib/IR/Instructions.cpp