LLVM: llvm::ThreadSafeRefCountedBase< Derived > Class Template Reference
llvm::ThreadSafeRefCountedBase< Derived > Class Template Reference
A thread-safe version of RefCountedBase.
#include "llvm/ADT/IntrusiveRefCntPtr.h"
Public Member Functions
void Retain () const
void Release () const
Protected Member Functions
ThreadSafeRefCountedBase ()=default
ThreadSafeRefCountedBase (const ThreadSafeRefCountedBase &)
ThreadSafeRefCountedBase & operator= (const ThreadSafeRefCountedBase &)=delete
~ThreadSafeRefCountedBase ()
Detailed Description
template<class Derived>
class llvm::ThreadSafeRefCountedBase< Derived >
A thread-safe version of RefCountedBase.
Definition at line 106 of file IntrusiveRefCntPtr.h.
Constructor & Destructor Documentation
ThreadSafeRefCountedBase() [1/2]
template<class Derived > llvm::ThreadSafeRefCountedBase< Derived >::ThreadSafeRefCountedBase () protected default
ThreadSafeRefCountedBase() [2/2]
template<class Derived > llvm::ThreadSafeRefCountedBase< Derived >::ThreadSafeRefCountedBase (const ThreadSafeRefCountedBase< Derived > &) inline protected
Definition at line 111 of file IntrusiveRefCntPtr.h.
~ThreadSafeRefCountedBase()
template<class Derived > llvm::ThreadSafeRefCountedBase< Derived >::~ThreadSafeRefCountedBase () inline protected
Definition at line 116 of file IntrusiveRefCntPtr.h.
References assert().
Member Function Documentation
operator=()
template<class Derived > ThreadSafeRefCountedBase & llvm::ThreadSafeRefCountedBase< Derived >::operator= (const ThreadSafeRefCountedBase< Derived > &) protected delete
Release()
template<class Derived > void llvm::ThreadSafeRefCountedBase< Derived >::Release () const inline
Definition at line 129 of file IntrusiveRefCntPtr.h.
References assert().
Referenced by llvm::orc::ResourceTracker::~ResourceTracker().
Retain()
template<class Derived > void llvm::ThreadSafeRefCountedBase< Derived >::Retain () const inline
Definition at line 127 of file IntrusiveRefCntPtr.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/IntrusiveRefCntPtr.h