LLVM: llvm::ImmutableGraph< NodeValueT, EdgeValueT >::Node Class Reference
llvm::ImmutableGraph< NodeValueT, EdgeValueT >::Node Class Reference
#include "Target/X86/ImmutableGraph.h"
Public Member Functions
const node_value_type & getValue () const
const Edge * edges_begin () const
const Edge * edges_end () const
ArrayRef< Edge > edges () const
Friends
class ImmutableGraph
template<typename >
class ImmutableGraphBuilder
Detailed Description
template<typename NodeValueT, typename EdgeValueT>
class llvm::ImmutableGraph< NodeValueT, EdgeValueT >::Node
Definition at line 58 of file ImmutableGraph.h.
Member Function Documentation
edges()
template<typename NodeValueT , typename EdgeValueT > ArrayRef< Edge > llvm::ImmutableGraph< NodeValueT, EdgeValueT >::Node::edges () const inline
Definition at line 74 of file ImmutableGraph.h.
References llvm::ImmutableGraph< NodeValueT, EdgeValueT >::Node::edges_begin(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::Node::edges_end(), and llvm::makeArrayRef().
edges_begin()
template<typename NodeValueT , typename EdgeValueT > const Edge * llvm::ImmutableGraph< NodeValueT, EdgeValueT >::Node::edges_begin () const inline
Definition at line 68 of file ImmutableGraph.h.
Referenced by llvm::ImmutableGraph< NodeValueT, EdgeValueT >::Node::edges().
edges_end()
template<typename NodeValueT , typename EdgeValueT > const Edge * llvm::ImmutableGraph< NodeValueT, EdgeValueT >::Node::edges_end () const inline
Definition at line 73 of file ImmutableGraph.h.
Referenced by llvm::ImmutableGraph< NodeValueT, EdgeValueT >::Node::edges().
getValue()
template<typename NodeValueT , typename EdgeValueT > const node_value_type & llvm::ImmutableGraph< NodeValueT, EdgeValueT >::Node::getValue () const inline
Definition at line 66 of file ImmutableGraph.h.
Friends And Related Symbol Documentation
ImmutableGraph
template<typename NodeValueT , typename EdgeValueT > friend class ImmutableGraph friend
Definition at line 59 of file ImmutableGraph.h.
ImmutableGraphBuilder
template<typename NodeValueT , typename EdgeValueT > template<typename > friend class ImmutableGraphBuilder friend
Definition at line 60 of file ImmutableGraph.h.
The documentation for this class was generated from the following file:
lib/Target/X86/ImmutableGraph.h