LLVM: llvm::BaseRecord Class Reference
llvm::BaseRecord Class Reference
#include "llvm/TableGen/DirectiveEmitter.h"
Public Member Functions
BaseRecord (const llvm::Record *Def)
StringRef getName () const
StringRef getAlternativeName () const
std::string getFormattedName ()
bool isDefault () const
StringRef getRecordName () const
Protected Attributes
const llvm::Record * Def
Detailed Description
Definition at line 70 of file DirectiveEmitter.h.
Constructor & Destructor Documentation
BaseRecord()
llvm::BaseRecord::BaseRecord (const llvm::Record * Def) inline explicit
Definition at line 72 of file DirectiveEmitter.h.
Member Function Documentation
getAlternativeName()
StringRef llvm::BaseRecord::getAlternativeName () const inline
Definition at line 76 of file DirectiveEmitter.h.
References Def, and llvm::Record::getValueAsString().
getFormattedName()
std::string llvm::BaseRecord::getFormattedName () inline
Definition at line 82 of file DirectiveEmitter.h.
References Def, llvm::Record::getValueAsString(), N, Name, and llvm::StringRef::str().
getName()
StringRef llvm::BaseRecord::getName () const inline
Definition at line 74 of file DirectiveEmitter.h.
References Def, and llvm::Record::getValueAsString().
getRecordName()
StringRef llvm::BaseRecord::getRecordName () const inline
Definition at line 92 of file DirectiveEmitter.h.
References Def, and llvm::Record::getName().
isDefault()
bool llvm::BaseRecord::isDefault () const inline
Definition at line 89 of file DirectiveEmitter.h.
References Def, and llvm::Record::getValueAsBit().
Member Data Documentation
Def
const llvm::Record* llvm::BaseRecord::Def protected
Definition at line 95 of file DirectiveEmitter.h.
Referenced by llvm::Directive::getAllowedClauses(), llvm::Directive::getAllowedExclusiveClauses(), llvm::Directive::getAllowedOnceClauses(), getAlternativeName(), llvm::Clause::getClangClass(), llvm::Clause::getFlangClass(), getFormattedName(), llvm::Clause::getFormattedParserClassName(), getName(), getRecordName(), llvm::Directive::getRequiredClauses(), and isDefault().
The documentation for this class was generated from the following file:
include/llvm/TableGen/DirectiveEmitter.h