LLVM: llvm::raw_ostream Class Reference
llvm::raw_ostream Class Reference abstract
This class implements an extremely fast bulk output stream that can only output to a stream.
#include "llvm/Support/raw_ostream.h"
Public Types
enum class OStreamKind { OK_OStream , OK_FDStream }
enum class Colors {
BLACK = 0 , RED , GREEN , YELLOW ,
BLUE , MAGENTA , CYAN , WHITE ,
SAVEDCOLOR , RESET
}
using uuid_t = uint8_t[16]
Output a formatted UUID with dash separators.
Public Member Functions
raw_ostream (bool unbuffered=false, OStreamKind K=OStreamKind::OK_OStream)
raw_ostream (const raw_ostream &)=delete
void operator= (const raw_ostream &)=delete
virtual ~raw_ostream ()
uint64_t tell () const
tell - Return the current offset with the file.
OStreamKind get_kind () const
virtual void reserveExtraSpace (uint64_t ExtraSize)
If possible, pre-allocate ExtraSize bytes for stream data.
void SetBuffered ()
Set the stream to be buffered, with an automatically determined buffer size.
void SetBufferSize (size_t Size)
Set the stream to be buffered, using the specified buffer size.
size_t GetBufferSize () const
void SetUnbuffered ()
Set the stream to be unbuffered.
size_t GetNumBytesInBuffer () const
void flush ()
raw_ostream & operator<< (char C)
raw_ostream & operator<< (unsigned char C)
raw_ostream & operator<< (signed char C)
raw_ostream & operator<< (StringRef Str)
raw_ostream & operator<< (const char *Str)
raw_ostream & operator<< (const std::string &Str)
raw_ostream & operator<< (const SmallVectorImpl< char > &Str)
raw_ostream & operator<< (unsigned long N)
raw_ostream & operator<< (long N)
raw_ostream & operator<< (unsigned long long N)
raw_ostream & operator<< (long long N)
raw_ostream & operator<< (const void *P)
raw_ostream & operator<< (unsigned int N)
raw_ostream & operator<< (int N)
raw_ostream & operator<< (double N)
raw_ostream & write_hex (unsigned long long N)
Output N in hexadecimal, without any prefix or padding.
raw_ostream & operator<< (Colors C)
raw_ostream & write_uuid (const uuid_t UUID)
raw_ostream & write_escaped (StringRef Str, bool UseHexEscapes=false)
Output Str, turning '\', '\t', '
', '"', and anything that doesn't satisfy llvm::isPrint into an escape sequence.
raw_ostream & write (unsigned char C)
raw_ostream & write (const char *Ptr, size_t Size)
raw_ostream & operator<< (const format_object_base &Fmt)
raw_ostream & operator<< (const FormattedString &)
raw_ostream & operator<< (const FormattedNumber &)
raw_ostream & operator<< (const formatv_object_base &)
raw_ostream & operator<< (const FormattedBytes &)
raw_ostream & indent (unsigned NumSpaces)
indent - Insert 'NumSpaces' spaces.
raw_ostream & write_zeros (unsigned NumZeros)
write_zeros - Insert 'NumZeros' nulls.
virtual raw_ostream & changeColor (enum Colors Color, bool Bold=false, bool BG=false)
Changes the foreground color of text that will be output from this point forward.
virtual raw_ostream & resetColor ()
Resets the colors to terminal defaults.
virtual raw_ostream & reverseColor ()
Reverses the foreground and background colors.
virtual bool is_displayed () const
This function determines if this stream is connected to a "tty" or "console" window.
virtual bool has_colors () const
This function determines if this stream is displayed and supports colors.
virtual void enable_colors (bool enable)
bool colors_enabled () const
void tie (raw_ostream *TieTo)
Tie this stream to the specified stream.
Static Public Attributes
static constexpr Colors BLACK = Colors::BLACK
static constexpr Colors RED = Colors::RED
static constexpr Colors GREEN = Colors::GREEN
static constexpr Colors YELLOW = Colors::YELLOW
static constexpr Colors BLUE = Colors::BLUE
static constexpr Colors MAGENTA = Colors::MAGENTA
static constexpr Colors CYAN = Colors::CYAN
static constexpr Colors WHITE = Colors::WHITE
static constexpr Colors SAVEDCOLOR = Colors::SAVEDCOLOR
static constexpr Colors RESET = Colors::RESET
Protected Member Functions
void SetBuffer (char *BufferStart, size_t Size)
Use the provided buffer as the raw_ostream buffer.
virtual size_t preferred_buffer_size () const
Return an efficient buffer size for the underlying output mechanism.
const char * getBufferStart () const
Return the beginning of the current stream buffer, or 0 if the stream is unbuffered.
Detailed Description
This class implements an extremely fast bulk output stream that can only output to a stream.
It does not support seeking, reopening, rewinding, line buffered disciplines etc. It is a simple buffer that outputs a chunk at a time.
Definition at line 54 of file raw_ostream.h.
Member Typedef Documentation
uuid_t
using llvm::raw_ostream::uuid_t = uint8_t[16]
Output a formatted UUID with dash separators.
Definition at line 273 of file raw_ostream.h.
Member Enumeration Documentation
Colors
enum class llvm::raw_ostream::Colors strong
Enumerator
BLACK
RED
GREEN
YELLOW
BLUE
MAGENTA
CYAN
WHITE
SAVEDCOLOR
RESET
Definition at line 98 of file raw_ostream.h.
OStreamKind
enum class llvm::raw_ostream::OStreamKind strong
Enumerator
OK_OStream
OK_FDStream
Definition at line 57 of file raw_ostream.h.
Constructor & Destructor Documentation
raw_ostream() [1/2]
llvm::raw_ostream::raw_ostream (bool unbuffered = false, OStreamKind K = OStreamKind::OK_OStream) inline explicit
Definition at line 122 of file raw_ostream.h.
raw_ostream() [2/2]
llvm::raw_ostream::raw_ostream (const raw_ostream &) delete
~raw_ostream()
raw_ostream::~raw_ostream () virtual
Definition at line 76 of file raw_ostream.cpp.
References assert().
Member Function Documentation
changeColor()
raw_ostream & raw_ostream::changeColor (enum Colors Color, bool Bold = false, bool BG = false) virtual
Changes the foreground color of text that will be output from this point forward.
Parameters
Color ANSI color to use, the special SAVEDCOLOR can be used to change only the bold attribute, and keep colors untouched
Bold bold/brighter text, default false
BG if true change the background, default: change foreground
Returns
itself so it can be used within << invocations
Reimplemented in llvm::formatted_raw_ostream.
Definition at line 521 of file raw_ostream.cpp.
References llvm::sys::Process::OutputBold(), llvm::sys::Process::OutputColor(), SAVEDCOLOR, and write().
Referenced by llvm::formatted_raw_ostream::changeColor(), llvm::WithColor::changeColor(), operator<<(), and llvm::WithColor::WithColor().
colors_enabled()
bool llvm::raw_ostream::colors_enabled () const inline
Definition at line 334 of file raw_ostream.h.
enable_colors()
virtual void llvm::raw_ostream::enable_colors (bool enable) inline virtual
Definition at line 332 of file raw_ostream.h.
Referenced by llvm::raw_fd_ostream::raw_fd_ostream().
flush()
void llvm::raw_ostream::flush () inline
Definition at line 187 of file raw_ostream.h.
Referenced by llvm::TarWriter::append(), llvm::object::ArchiveMemberHeader::ArchiveMemberHeader(), llvm::raw_fd_ostream::close(), computeMemberData(), computeStringTable(), llvm::LTOCodeGenerator::DiagnosticHandler(), llvm::pdb::PDBSymbol::dumpChildStats(), llvm::pdb::PDBSymbol::dumpProperties(), fail(), flattenCommandLine(), llvm::json::OStream::flush(), llvm::ScopedPrinter::flush(), llvm::Attribute::getAsString(), getBlockName(), getBranchCondString(), getDebugLocString(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getEdgeAttributes(), llvm::LazyCallGraph::SCC::getName(), llvm::LazyCallGraph::RefSCC::getName(), llvm::object::ArchiveMemberHeader::getName(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getNodeAttributes(), handleDiagnostic(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsSameAsFreshTree(), LLVMGetDiagInfoDescription(), LLVMTargetMachineEmit(), llvm::CodeViewYAML::detail::UnknownSymbolRecord::map(), llvm::DiagnosticInfoUnsupported::print(), llvm::opt::OptTable::printHelp(), llvm::AMDGPUInstPrinter::printInst(), llvm::PrintStatistics(), llvm::PrintStatisticsJSON(), reportError(), reportOpenError(), rescheduleLexographically(), llvm::AMDGPUSimplifyLibCallsPass::run(), llvm::raw_fd_ostream::seek(), llvm::LoopVectorizationCostModel::selectVectorizationFactor(), SetBufferSize(), llvm::setProfMetadata(), SetUnbuffered(), llvm::raw_sha1_ostream::sha1(), llvm::formatv_object_base::str(), llvm::sys::StrError(), llvm::unittest::TempFile::TempFile(), llvm::PeelingModuloScheduleExpander::validateAgainstModuloScheduleExpander(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyLevels(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyReachability(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty(), llvm::writeArchiveToStream(), llvm::writeToOutput(), writeToResolutionFile(), llvm::object::writeUniversalBinaryToStream(), llvm::circular_raw_ostream::~circular_raw_ostream(), llvm::gsym::FileWriter::~FileWriter(), llvm::formatted_raw_ostream::~formatted_raw_ostream(), llvm::raw_fd_ostream::~raw_fd_ostream(), llvm::raw_null_ostream::~raw_null_ostream(), and llvm::raw_os_ostream::~raw_os_ostream().
get_kind()
OStreamKind llvm::raw_ostream::get_kind () const inline
Definition at line 138 of file raw_ostream.h.
Referenced by llvm::raw_fd_stream::classof().
GetBufferSize()
size_t llvm::raw_ostream::GetBufferSize () const inline
Definition at line 161 of file raw_ostream.h.
References preferred_buffer_size().
getBufferStart()
const char * llvm::raw_ostream::getBufferStart () const inline protected
Return the beginning of the current stream buffer, or 0 if the stream is unbuffered.
Definition at line 377 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::getColumn(), llvm::formatted_raw_ostream::getLine(), llvm::orc::DumpObjects::operator()(), and llvm::formatted_raw_ostream::PadToColumn().
GetNumBytesInBuffer()
size_t llvm::raw_ostream::GetNumBytesInBuffer () const inline
Definition at line 179 of file raw_ostream.h.
Referenced by llvm::formatted_raw_ostream::getColumn(), llvm::formatted_raw_ostream::getLine(), llvm::formatted_raw_ostream::PadToColumn(), and tell().
has_colors()
virtual bool llvm::raw_ostream::has_colors () const inline virtual
This function determines if this stream is displayed and supports colors.
The result is unaffected by calls to enable_color().
Reimplemented in llvm::raw_fd_ostream.
Definition at line 328 of file raw_ostream.h.
References is_displayed().
Referenced by llvm::WithColor::colorsEnabled().
indent()
raw_ostream & raw_ostream::indent (unsigned NumSpaces)
indent - Insert 'NumSpaces' spaces.
Definition at line 496 of file raw_ostream.cpp.
Referenced by llvm::LoopBase< BasicBlock, Loop >::addBasicBlockToLoop(), llvm::IndexedReference::computeRefCost(), llvm::gsym::GsymReader::dump(), llvm::dwarf::UnwindRow::dump(), llvm::dwarf::CFIProgram::dump(), llvm::pdb::IPDBSourceFile::dump(), llvm::DWARFDie::dump(), llvm::LexicalScope::dump(), dumpAttribute(), llvm::DWARFLocationTable::dumpLocationList(), DumpNodes(), DumpNodesr(), llvm::LPPassManager::dumpPassStructure(), llvm::RGPassManager::dumpPassStructure(), llvm::FPPassManager::dumpPassStructure(), llvm::Pass::dumpPassStructure(), dumpRanges(), llvm::DWARFDebugLoc::dumpRawEntry(), llvm::DWARFDebugLoclists::dumpRawEntry(), llvm::pdb::dumpSymbolField(), llvm::pdb::dumpSymbolIdField(), llvm::DWARFDebugLine::Row::dumpTableHeader(), llvm::MCPseudoProbeInlineTree::emit(), llvm::MCPseudoProbe::emit(), llvm::StringMatcher::Emit(), emitBasicBlockLoopComments(), llvm::detail::PadAdapter< T >::format(), llvm::IndexedReference::hasSpacialReuse(), operator<<(), operator<<(), operator<<(), llvm::operator<<(), llvm::gsym::operator<<(), llvm::RegionBase< RegionTraits< MachineFunction > >::outermostLoopInRegion(), llvm::formatted_raw_ostream::PadToColumn(), llvm::DWARFDebugLine::LineTable::parse(), llvm::MIPrinter::print(), llvm::slpvectorizer::BoUpSLP::VLOperands::print(), llvm::RegionBase< Tr >::print(), llvm::LoopAccessLegacyAnalysis::print(), llvm::MachineBasicBlock::print(), llvm::PredicatedScalarEvolution::print(), llvm::MemoryDepChecker::Dependence::print(), llvm::RuntimePointerChecking::print(), llvm::LoopAccessInfo::print(), llvm::WebAssemblyException::print(), llvm::SCEVEqualPredicate::print(), llvm::SCEVWrapPredicate::print(), llvm::sampleprof::FunctionSamples::print(), llvm::RuntimePointerChecking::printChecks(), PrintChildLoopComment(), llvm::cl::Option::printEnumValHelpStr(), llvm::cl::generic_parser_base::printGenericOptionDiff(), PrintHelpOptionList(), llvm::cl::Option::printHelpStr(), llvm::cl::basic_parser_impl::printOptionName(), PrintParentLoopComment(), llvm::TargetRegistry::printRegisteredTargetsForVersion(), printrWithDepthHelper(), printWithSpacePadding(), and llvm::LoopAccessInfoPrinterPass::run().
is_displayed()
virtual bool llvm::raw_ostream::is_displayed () const inline virtual
This function determines if this stream is connected to a "tty" or "console" window.
That is, the output would be displayed to the user rather than being put on a pipe or stored in a file.
Reimplemented in llvm::circular_raw_ostream, llvm::formatted_raw_ostream, and llvm::raw_fd_ostream.
Definition at line 324 of file raw_ostream.h.
Referenced by has_colors(), llvm::circular_raw_ostream::is_displayed(), and llvm::formatted_raw_ostream::is_displayed().
operator<<() [1/21]
raw_ostream & llvm::raw_ostream::operator<< (char C) inline
Definition at line 192 of file raw_ostream.h.
References C, and write().
Referenced by operator<<().
operator<<() [2/21]
raw_ostream & raw_ostream::operator<< (Colors C)
Definition at line 144 of file raw_ostream.cpp.
References C, changeColor(), RESET, and resetColor().
operator<<() [3/21]
raw_ostream & llvm::raw_ostream::operator<< (const char * Str) inline
Definition at line 228 of file raw_ostream.h.
References operator<<().
operator<<() [4/21]
raw_ostream & raw_ostream::operator<< (const format_object_base & Fmt)
Definition at line 308 of file raw_ostream.cpp.
References assert(), llvm::format_object_base::print(), and write().
operator<<() [5/21]
raw_ostream & raw_ostream::operator<< (const FormattedBytes & FB)
Definition at line 402 of file raw_ostream.cpp.
References llvm::alignTo(), assert(), I, indent(), llvm::Log2_64_Ceil(), llvm::Lower, Offset, Size, llvm::Upper, and llvm::write_hex().
operator<<() [6/21]
raw_ostream & raw_ostream::operator<< (const FormattedNumber & FN)
Definition at line 379 of file raw_ostream.cpp.
References indent(), llvm::Integer, llvm::Lower, llvm::PrefixLower, llvm::PrefixUpper, llvm::Upper, llvm::write_hex(), and llvm::write_integer().
operator<<() [7/21]
raw_ostream & raw_ostream::operator<< (const FormattedString & FS)
Definition at line 353 of file raw_ostream.cpp.
References indent(), llvm::FormattedString::JustifyCenter, llvm::FormattedString::JustifyLeft, llvm::FormattedString::JustifyNone, and llvm::FormattedString::JustifyRight.
operator<<() [8/21]
raw_ostream & raw_ostream::operator<< (const formatv_object_base & Obj)
Definition at line 348 of file raw_ostream.cpp.
References llvm::formatv_object_base::format().
operator<<() [9/21]
raw_ostream & llvm::raw_ostream::operator<< (const SmallVectorImpl< char > & Str) inline
Definition at line 246 of file raw_ostream.h.
References write().
operator<<() [10/21]
raw_ostream & llvm::raw_ostream::operator<< (const std::string & Str) inline
Definition at line 235 of file raw_ostream.h.
References write().
operator<<() [11/21]
raw_ostream & raw_ostream::operator<< (const void * P)
Definition at line 202 of file raw_ostream.cpp.
References P, llvm::PrefixLower, and llvm::write_hex().
operator<<() [12/21]
raw_ostream & raw_ostream::operator<< (double N)
Definition at line 207 of file raw_ostream.cpp.
References llvm::Exponent, N, and llvm::write_double().
operator<<() [13/21]
raw_ostream & llvm::raw_ostream::operator<< (int N) inline
Definition at line 260 of file raw_ostream.h.
References N.
operator<<() [14/21]
raw_ostream & raw_ostream::operator<< (long long N)
Definition at line 134 of file raw_ostream.cpp.
References llvm::Integer, N, and llvm::write_integer().
operator<<() [15/21]
raw_ostream & raw_ostream::operator<< (long N)
Definition at line 124 of file raw_ostream.cpp.
References llvm::Integer, N, and llvm::write_integer().
operator<<() [16/21]
raw_ostream & llvm::raw_ostream::operator<< (signed char C) inline
Definition at line 206 of file raw_ostream.h.
References C, and write().
operator<<() [17/21]
raw_ostream & llvm::raw_ostream::operator<< (StringRef Str) inline
Definition at line 213 of file raw_ostream.h.
References Size, and write().
operator<<() [18/21]
raw_ostream & llvm::raw_ostream::operator<< (unsigned char C) inline
Definition at line 199 of file raw_ostream.h.
References C, and write().
operator<<() [19/21]
raw_ostream & llvm::raw_ostream::operator<< (unsigned int N) inline
Definition at line 256 of file raw_ostream.h.
References N.
operator<<() [20/21]
raw_ostream & raw_ostream::operator<< (unsigned long long N)
Definition at line 129 of file raw_ostream.cpp.
References llvm::Integer, N, and llvm::write_integer().
operator<<() [21/21]
raw_ostream & raw_ostream::operator<< (unsigned long N)
Definition at line 119 of file raw_ostream.cpp.
References llvm::Integer, N, and llvm::write_integer().
operator=()
void llvm::raw_ostream::operator= (const raw_ostream &) delete
preferred_buffer_size()
size_t raw_ostream::preferred_buffer_size () const protected virtual
Return an efficient buffer size for the underlying output mechanism.
Definition at line 86 of file raw_ostream.cpp.
Referenced by GetBufferSize(), and SetBuffered().
reserveExtraSpace()
virtual void llvm::raw_ostream::reserveExtraSpace (uint64_t ExtraSize) inline virtual
If possible, pre-allocate ExtraSize bytes for stream data.
i.e. it extends internal buffers to keep additional ExtraSize bytes. So that the stream could keep at least tell() + ExtraSize bytes without re-allocations. reserveExtraSpace() does not change the size/data of the stream.
Reimplemented in llvm::raw_string_ostream, and llvm::raw_svector_ostream.
Definition at line 149 of file raw_ostream.h.
resetColor()
raw_ostream & raw_ostream::resetColor () virtual
Resets the colors to terminal defaults.
Call this when you are done outputting colored text, or before program exit.
Reimplemented in llvm::formatted_raw_ostream.
Definition at line 534 of file raw_ostream.cpp.
References llvm::sys::Process::ResetColor(), and write().
Referenced by operator<<(), llvm::WithColor::resetColor(), and llvm::formatted_raw_ostream::resetColor().
reverseColor()
raw_ostream & raw_ostream::reverseColor () virtual
Reverses the foreground and background colors.
Reimplemented in llvm::formatted_raw_ostream.
Definition at line 543 of file raw_ostream.cpp.
References llvm::sys::Process::OutputReverse(), and write().
Referenced by llvm::formatted_raw_ostream::reverseColor().
SetBuffer()
void llvm::raw_ostream::SetBuffer (char * BufferStart, size_t Size) inline protected
Use the provided buffer as the raw_ostream buffer.
This is intended for use only by subclasses which can arrange for the output to go directly into the desired output buffer, instead of being copied on each flush.
Definition at line 368 of file raw_ostream.h.
References Size.
SetBuffered()
void raw_ostream::SetBuffered ()
Set the stream to be buffered, with an automatically determined buffer size.
Definition at line 91 of file raw_ostream.cpp.
References preferred_buffer_size(), SetBufferSize(), SetUnbuffered(), and Size.
Referenced by write(), and write().
SetBufferSize()
void llvm::raw_ostream::SetBufferSize (size_t Size) inline
Set the stream to be buffered, using the specified buffer size.
Definition at line 156 of file raw_ostream.h.
References flush(), and Size.
Referenced by SetBuffered().
SetUnbuffered()
void llvm::raw_ostream::SetUnbuffered () inline
Set the stream to be unbuffered.
When unbuffered, the stream will flush after every write. This routine will also flush the buffer immediately when the stream is being set to unbuffered.
Definition at line 174 of file raw_ostream.h.
References flush().
Referenced by llvm::buffer_unique_ostream::buffer_unique_ostream(), llvm::raw_string_ostream::raw_string_ostream(), llvm::raw_svector_ostream::raw_svector_ostream(), and SetBuffered().
tell()
uint64_t llvm::raw_ostream::tell () const inline
tell - Return the current offset with the file.
Definition at line 136 of file raw_ostream.h.
References GetNumBytesInBuffer().
Referenced by llvm::gsym::FileWriter::alignTo(), llvm::TarWriter::append(), llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), llvm::DWARFYAML::emitDebugRanges(), pad(), printLine(), printWithSpacePadding(), llvm::raw_pwrite_stream::pwrite(), llvm::RISCVAsmBackend::relaxDwarfLineAddr(), llvm::raw_string_ostream::reserveExtraSpace(), llvm::raw_svector_ostream::reserveExtraSpace(), llvm::gsym::FileWriter::tell(), llvm::ProfOStream::tell(), writeCOFF(), writeDIE(), writeDWARFExpression(), llvm::MachObjectWriter::writeDysymtabLoadCommand(), writeFragment(), llvm::MachObjectWriter::writeHeader(), llvm::MachObjectWriter::writeLinkeditLoadCommand(), llvm::MachObjectWriter::writeLinkerOptionsLoadCommand(), writeListEntry(), writeListEntry(), llvm::MachObjectWriter::writeObject(), llvm::MachObjectWriter::writeSection(), llvm::MCAssembler::writeSectionData(), llvm::MachObjectWriter::writeSegmentLoadCommand(), writeSymbolTable(), writeSymbolTableHeader(), and llvm::MachObjectWriter::writeSymtabLoadCommand().
tie()
void llvm::raw_ostream::tie (raw_ostream * TieTo) inline
Tie this stream to the specified stream.
Replaces any existing tied-to stream. Specifying a nullptr unties the stream.
Definition at line 338 of file raw_ostream.h.
write() [1/2]
raw_ostream & raw_ostream::write (const char * Ptr, size_t Size)
Definition at line 239 of file raw_ostream.cpp.
References assert(), LLVM_UNLIKELY, SetBuffered(), Size, and write().
write() [2/2]
raw_ostream & raw_ostream::write (unsigned char C)
Definition at line 219 of file raw_ostream.cpp.
References C, LLVM_UNLIKELY, SetBuffered(), and write().
Referenced by changeColor(), llvm::InstrProfRecordWriterTrait::EmitData(), llvm::DWARFYAML::emitDebugAbbrev(), llvm::DWARFYAML::emitDebugInfo(), llvm::DWARFYAML::emitDebugLine(), llvm::DWARFYAML::emitDebugStr(), emitExternalFile(), emitFileEntry(), EmitInlineAsmStr(), llvm::InstrProfRecordWriterTrait::EmitKey(), emitMagic(), emitPubSection(), emitStrTab(), emitVersion(), llvm::circular_raw_ostream::flushBufferWithBanner(), llvm::remarks::BitstreamRemarkSerializerHelper::flushToStream(), llvm::DWARFYAML::Data::getAbbrevTableContentByIndex(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), printBSDMemberHeader(), resetColor(), reverseColor(), llvm::remarks::StringTable::serialize(), write(), llvm::msgpack::Writer::write(), write(), llvm::write_hex(), write_padding(), write_unsigned_impl(), writeArrayData(), llvm::yaml::BinaryRef::writeAsBinary(), llvm::yaml::BinaryRef::writeAsHex(), llvm::WriteBitcodeToFile(), writeCOFF(), llvm::gsym::FileWriter::writeData(), writeDIE(), writeDWARFLists(), llvm::msgpack::Writer::writeExt(), writeExtendedOpcode(), llvm::writeFileAtomically(), writeFragment(), llvm::writeIndexToFile(), writeInteger(), writeListEntry(), llvm::ARMAsmBackend::writeNopData(), llvm::CSKYAsmBackend::writeNopData(), llvm::RISCVAsmBackend::writeNopData(), llvm::gsym::FileWriter::writeSLEB(), writeSymbolTable(), llvm::writeThinLinkBitcodeToFile(), llvm::gsym::FileWriter::writeU16(), llvm::gsym::FileWriter::writeU32(), llvm::gsym::FileWriter::writeU64(), llvm::gsym::FileWriter::writeU8(), writeUint32(), writeUint64(), writeUint8(), llvm::gsym::FileWriter::writeULEB(), llvm::object::writeUniversalBinaryToStream(), writeWithCommas(), llvm::yaml::yaml2archive(), and ZeroFillBytes().
write_escaped()
raw_ostream & raw_ostream::write_escaped (StringRef Str, bool UseHexEscapes = false)
Output Str, turning '\', '\t', '
', '"', and anything that doesn't satisfy llvm::isPrint into an escape sequence.
Definition at line 162 of file raw_ostream.cpp.
Referenced by llvm::object::ArchiveMemberHeader::ArchiveMemberHeader(), llvm::AsmToken::dump(), llvm::DWARFContext::dump(), llvm::DWARFFormValue::dump(), llvm::StringToOffsetTable::EmitString(), llvm::object::ArchiveMemberHeader::getName(), llvm::PrettyStackTraceProgram::print(), llvm::Pattern::printSubstitutions(), and llvm::AArch64ExternalSymbolizer::tryAddingSymbolicOperand().
write_hex()
raw_ostream & raw_ostream::write_hex (unsigned long long N)
Output N in hexadecimal, without any prefix or padding.
Definition at line 139 of file raw_ostream.cpp.
References llvm::Lower, N, and llvm::write_hex().
Referenced by dumpDataAux(), printExpr(), printHex32(), and llvm::HexagonShuffler::shuffle().
write_uuid()
raw_ostream & raw_ostream::write_uuid (const uuid_t UUID)
Definition at line 152 of file raw_ostream.cpp.
References llvm::format(), and Idx.
Referenced by dumpUUID(), and llvm::yaml::ScalarTraits< uuid_t >::output().
write_zeros()
raw_ostream & raw_ostream::write_zeros (unsigned NumZeros)
write_zeros - Insert 'NumZeros' nulls.
Definition at line 501 of file raw_ostream.cpp.
Referenced by llvm::gsym::FileWriter::alignTo(), llvm::DWARFYAML::Data::getAbbrevTableContentByIndex(), llvm::RISCVAsmBackend::relaxDwarfLineAddr(), writeCOFF(), llvm::MachObjectWriter::writeLinkerOptionsLoadCommand(), llvm::AVRAsmBackend::writeNopData(), llvm::MipsAsmBackend::writeNopData(), llvm::MachObjectWriter::writeObject(), and llvm::object::writeUniversalBinaryToStream().
Member Data Documentation
BLACK
constexpr raw_ostream::Colors raw_ostream::BLACK = Colors::BLACK static constexpr
Definition at line 111 of file raw_ostream.h.
Referenced by llvm::WithColor::WithColor().
BLUE
constexpr raw_ostream::Colors raw_ostream::BLUE = Colors::BLUE static constexpr
Definition at line 115 of file raw_ostream.h.
Referenced by llvm::WithColor::WithColor().
CYAN
constexpr raw_ostream::Colors raw_ostream::CYAN = Colors::CYAN static constexpr
Definition at line 117 of file raw_ostream.h.
Referenced by llvm::WithColor::WithColor().
GREEN
constexpr raw_ostream::Colors raw_ostream::GREEN = Colors::GREEN static constexpr
Definition at line 113 of file raw_ostream.h.
Referenced by llvm::SMDiagnostic::print(), and llvm::WithColor::WithColor().
MAGENTA
constexpr raw_ostream::Colors raw_ostream::MAGENTA = Colors::MAGENTA static constexpr
Definition at line 116 of file raw_ostream.h.
Referenced by llvm::WithColor::WithColor().
RED
constexpr raw_ostream::Colors raw_ostream::RED = Colors::RED static constexpr
Definition at line 112 of file raw_ostream.h.
Referenced by llvm::WithColor::WithColor().
RESET
constexpr raw_ostream::Colors raw_ostream::RESET = Colors::RESET static constexpr
Definition at line 120 of file raw_ostream.h.
SAVEDCOLOR
constexpr raw_ostream::Colors raw_ostream::SAVEDCOLOR = Colors::SAVEDCOLOR static constexpr
Definition at line 119 of file raw_ostream.h.
Referenced by changeColor(), and llvm::SMDiagnostic::print().
WHITE
constexpr raw_ostream::Colors raw_ostream::WHITE = Colors::WHITE static constexpr
Definition at line 118 of file raw_ostream.h.
YELLOW
constexpr raw_ostream::Colors raw_ostream::YELLOW = Colors::YELLOW static constexpr
Definition at line 114 of file raw_ostream.h.
Referenced by llvm::WithColor::WithColor().
The documentation for this class was generated from the following files:
include/llvm/Support/raw_ostream.h
lib/Support/raw_ostream.cpp