LLVM: llvm::ConstantFolder Class Reference
llvm::ConstantFolder Class Reference final
ConstantFolder - Create constants with minimum, target independent, folding.
#include "llvm/IR/ConstantFolder.h"
Public Member Functions
ConstantFolder ()=default
Value * FoldAdd (Value *LHS, Value *RHS, bool HasNUW=false, bool HasNSW=false) const override
Value * FoldAnd (Value *LHS, Value *RHS) const override
Value * FoldOr (Value *LHS, Value *RHS) const override
Value * FoldICmp (CmpInst::Predicate P, Value *LHS, Value *RHS) const override
Value * FoldGEP (Type *Ty, Value *Ptr, ArrayRef< Value * > IdxList, bool IsInBounds=false) const override
Value * FoldSelect (Value *C, Value *True, Value *False) const override
Constant * CreateFAdd (Constant *LHS, Constant *RHS) const override
Constant * CreateSub (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Constant * CreateFSub (Constant *LHS, Constant *RHS) const override
Constant * CreateMul (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Constant * CreateFMul (Constant *LHS, Constant *RHS) const override
Constant * CreateUDiv (Constant *LHS, Constant *RHS, bool isExact=false) const override
Constant * CreateSDiv (Constant *LHS, Constant *RHS, bool isExact=false) const override
Constant * CreateFDiv (Constant *LHS, Constant *RHS) const override
Constant * CreateURem (Constant *LHS, Constant *RHS) const override
Constant * CreateSRem (Constant *LHS, Constant *RHS) const override
Constant * CreateFRem (Constant *LHS, Constant *RHS) const override
Constant * CreateShl (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Constant * CreateLShr (Constant *LHS, Constant *RHS, bool isExact=false) const override
Constant * CreateAShr (Constant *LHS, Constant *RHS, bool isExact=false) const override
Constant * CreateOr (Constant *LHS, Constant *RHS) const
Constant * CreateXor (Constant *LHS, Constant *RHS) const override
Constant * CreateBinOp (Instruction::BinaryOps Opc, Constant *LHS, Constant *RHS) const override
Constant * CreateNeg (Constant *C, bool HasNUW=false, bool HasNSW=false) const override
Constant * CreateFNeg (Constant *C) const override
Constant * CreateNot (Constant *C) const override
Constant * CreateUnOp (Instruction::UnaryOps Opc, Constant *C) const override
Constant * CreateCast (Instruction::CastOps Op, Constant *C, Type *DestTy) const override
Constant * CreatePointerCast (Constant *C, Type *DestTy) const override
Constant * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const override
Constant * CreateIntCast (Constant *C, Type *DestTy, bool isSigned) const override
Constant * CreateFPCast (Constant *C, Type *DestTy) const override
Constant * CreateBitCast (Constant *C, Type *DestTy) const override
Constant * CreateIntToPtr (Constant *C, Type *DestTy) const override
Constant * CreatePtrToInt (Constant *C, Type *DestTy) const override
Constant * CreateZExtOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreateSExtOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreateTruncOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreateFCmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const override
Constant * CreateExtractElement (Constant *Vec, Constant *Idx) const override
Constant * CreateInsertElement (Constant *Vec, Constant *NewElt, Constant *Idx) const override
Constant * CreateShuffleVector (Constant *V1, Constant *V2, ArrayRef< int > Mask) const override
Constant * CreateExtractValue (Constant *Agg, ArrayRef< unsigned > IdxList) const override
Constant * CreateInsertValue (Constant *Agg, Constant *Val, ArrayRef< unsigned > IdxList) const override
Public Member Functions inherited from llvm::IRBuilderFolder
virtual ~IRBuilderFolder ()
Detailed Description
ConstantFolder - Create constants with minimum, target independent, folding.
Definition at line 29 of file ConstantFolder.h.
Constructor & Destructor Documentation
ConstantFolder()
llvm::ConstantFolder::ConstantFolder () explicit default
Member Function Documentation
CreateAShr()
Constant * llvm::ConstantFolder::CreateAShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 160 of file ConstantFolder.h.
References llvm::ConstantExpr::getAShr().
CreateBinOp()
Constant * llvm::ConstantFolder::CreateBinOp (Instruction::BinaryOps Opc, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 173 of file ConstantFolder.h.
References llvm::ConstantExpr::get().
CreateBitCast()
Constant * llvm::ConstantFolder::CreateBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 226 of file ConstantFolder.h.
References C, CreateCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
CreateCast()
Constant * llvm::ConstantFolder::CreateCast (Instruction::CastOps Op, Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 203 of file ConstantFolder.h.
References C, and llvm::ConstantExpr::getCast().
Referenced by CreateBitCast(), CreateIntToPtr(), and CreatePtrToInt().
CreateExtractElement()
Constant * llvm::ConstantFolder::CreateExtractElement (Constant * Vec, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 263 of file ConstantFolder.h.
References llvm::ConstantExpr::getExtractElement(), and Idx.
CreateExtractValue()
Constant * llvm::ConstantFolder::CreateExtractValue (Constant * Agg, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 277 of file ConstantFolder.h.
References llvm::ConstantExpr::getExtractValue().
CreateFAdd()
Constant * llvm::ConstantFolder::CreateFAdd (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 102 of file ConstantFolder.h.
References llvm::ConstantExpr::getFAdd().
CreateFCmp()
Constant * llvm::ConstantFolder::CreateFCmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 254 of file ConstantFolder.h.
References llvm::ConstantExpr::getCompare(), and P.
CreateFDiv()
Constant * llvm::ConstantFolder::CreateFDiv (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 134 of file ConstantFolder.h.
References llvm::ConstantExpr::getFDiv().
CreateFMul()
Constant * llvm::ConstantFolder::CreateFMul (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 120 of file ConstantFolder.h.
References llvm::ConstantExpr::getFMul().
CreateFNeg()
Constant * llvm::ConstantFolder::CreateFNeg (Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 187 of file ConstantFolder.h.
References C, and llvm::ConstantExpr::getFNeg().
CreateFPCast()
Constant * llvm::ConstantFolder::CreateFPCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 222 of file ConstantFolder.h.
References C, and llvm::ConstantExpr::getFPCast().
CreateFRem()
Constant * llvm::ConstantFolder::CreateFRem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 146 of file ConstantFolder.h.
References llvm::ConstantExpr::getFRem().
CreateFSub()
Constant * llvm::ConstantFolder::CreateFSub (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 111 of file ConstantFolder.h.
References llvm::ConstantExpr::getFSub().
CreateInsertElement()
Constant * llvm::ConstantFolder::CreateInsertElement (Constant * Vec, Constant * NewElt, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 267 of file ConstantFolder.h.
References llvm::ConstantExpr::getInsertElement(), and Idx.
CreateInsertValue()
Constant * llvm::ConstantFolder::CreateInsertValue (Constant * Agg, Constant * Val, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 282 of file ConstantFolder.h.
References llvm::ConstantExpr::getInsertValue().
CreateIntCast()
Constant * llvm::ConstantFolder::CreateIntCast (Constant * C, Type * DestTy, bool isSigned) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 217 of file ConstantFolder.h.
References C, and llvm::ConstantExpr::getIntegerCast().
CreateIntToPtr()
Constant * llvm::ConstantFolder::CreateIntToPtr (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 230 of file ConstantFolder.h.
References C, CreateCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
CreateLShr()
Constant * llvm::ConstantFolder::CreateLShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 155 of file ConstantFolder.h.
References llvm::ConstantExpr::getLShr().
CreateMul()
Constant * llvm::ConstantFolder::CreateMul (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 115 of file ConstantFolder.h.
References llvm::ConstantExpr::getMul().
CreateNeg()
Constant * llvm::ConstantFolder::CreateNeg (Constant * C, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 182 of file ConstantFolder.h.
References C, and llvm::ConstantExpr::getNeg().
CreateNot()
Constant * llvm::ConstantFolder::CreateNot (Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 191 of file ConstantFolder.h.
References C, and llvm::ConstantExpr::getNot().
CreateOr()
Constant * llvm::ConstantFolder::CreateOr (Constant * LHS, Constant * RHS) const inline
Definition at line 165 of file ConstantFolder.h.
References llvm::ConstantExpr::getOr().
CreatePointerBitCastOrAddrSpaceCast()
Constant * llvm::ConstantFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 212 of file ConstantFolder.h.
References C, and llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast().
CreatePointerCast()
Constant * llvm::ConstantFolder::CreatePointerCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 208 of file ConstantFolder.h.
References C, and llvm::ConstantExpr::getPointerCast().
CreatePtrToInt()
Constant * llvm::ConstantFolder::CreatePtrToInt (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 234 of file ConstantFolder.h.
References C, and CreateCast().
CreateSDiv()
Constant * llvm::ConstantFolder::CreateSDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 129 of file ConstantFolder.h.
References llvm::ConstantExpr::getSDiv().
CreateSExtOrBitCast()
Constant * llvm::ConstantFolder::CreateSExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 242 of file ConstantFolder.h.
References C, and llvm::ConstantExpr::getSExtOrBitCast().
CreateShl()
Constant * llvm::ConstantFolder::CreateShl (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 150 of file ConstantFolder.h.
References llvm::ConstantExpr::getShl().
CreateShuffleVector()
Constant * llvm::ConstantFolder::CreateShuffleVector (Constant * V1, Constant * V2, ArrayRef< int > Mask) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 272 of file ConstantFolder.h.
References llvm::ConstantExpr::getShuffleVector().
CreateSRem()
Constant * llvm::ConstantFolder::CreateSRem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 142 of file ConstantFolder.h.
References llvm::ConstantExpr::getSRem().
CreateSub()
Constant * llvm::ConstantFolder::CreateSub (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 106 of file ConstantFolder.h.
References llvm::ConstantExpr::getSub().
CreateTruncOrBitCast()
Constant * llvm::ConstantFolder::CreateTruncOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 246 of file ConstantFolder.h.
References C, and llvm::ConstantExpr::getTruncOrBitCast().
CreateUDiv()
Constant * llvm::ConstantFolder::CreateUDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 124 of file ConstantFolder.h.
References llvm::ConstantExpr::getUDiv().
CreateUnOp()
Constant * llvm::ConstantFolder::CreateUnOp (Instruction::UnaryOps Opc, Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 195 of file ConstantFolder.h.
References C, and llvm::ConstantExpr::get().
CreateURem()
Constant * llvm::ConstantFolder::CreateURem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 138 of file ConstantFolder.h.
References llvm::ConstantExpr::getURem().
CreateXor()
Constant * llvm::ConstantFolder::CreateXor (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 169 of file ConstantFolder.h.
References llvm::ConstantExpr::getXor().
CreateZExtOrBitCast()
Constant * llvm::ConstantFolder::CreateZExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 238 of file ConstantFolder.h.
References C, and llvm::ConstantExpr::getZExtOrBitCast().
FoldAdd()
Value * llvm::ConstantFolder::FoldAdd (Value * LHS, Value * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 41 of file ConstantFolder.h.
References llvm::ConstantExpr::getAdd().
FoldAnd()
Value * llvm::ConstantFolder::FoldAnd (Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 50 of file ConstantFolder.h.
References llvm::ConstantExpr::getAnd().
FoldGEP()
Value * llvm::ConstantFolder::FoldGEP (Type * Ty, Value * Ptr, ArrayRef< Value * > IdxList, bool IsInBounds = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 74 of file ConstantFolder.h.
References llvm::any_of(), llvm::ConstantExpr::getGetElementPtr(), and llvm::ConstantExpr::getInBoundsGetElementPtr().
FoldICmp()
Value * llvm::ConstantFolder::FoldICmp (CmpInst::Predicate P, Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 66 of file ConstantFolder.h.
References llvm::ConstantExpr::getCompare(), and P.
FoldOr()
Value * llvm::ConstantFolder::FoldOr (Value * LHS, Value * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 58 of file ConstantFolder.h.
References llvm::ConstantExpr::getOr().
FoldSelect()
Value * llvm::ConstantFolder::FoldSelect (Value * C, Value * True, Value * False) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 89 of file ConstantFolder.h.
References C, and llvm::ConstantExpr::getSelect().
The documentation for this class was generated from the following files:
include/llvm/IR/ConstantFolder.h
lib/IR/IRBuilder.cpp