LLVM: llvm::SystemZXPLINK64Registers Class Reference
llvm::SystemZXPLINK64Registers Class Reference
XPLINK64 calling convention specific use registers Particular to z/OS when in 64 bit mode.
#include "Target/SystemZ/SystemZRegisterInfo.h"
Public Member Functions
int getReturnFunctionAddressRegister () override final
int getStackPointerRegister () override final
int getFramePointerRegister () override final
int getAddressOfCalleeRegister ()
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override final
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID CC) const override final
int getCallFrameSize () override final
int getStackPointerBias () override final
~SystemZXPLINK64Registers ()
Destroys the object. Bogus destructor overriding base class destructor.
Public Member Functions inherited from llvm::SystemZCallingConventionRegisters
virtual ~SystemZCallingConventionRegisters ()
Destroys the object.
Detailed Description
XPLINK64 calling convention specific use registers Particular to z/OS when in 64 bit mode.
Definition at line 82 of file SystemZRegisterInfo.h.
Constructor & Destructor Documentation
~SystemZXPLINK64Registers()
llvm::SystemZXPLINK64Registers::~SystemZXPLINK64Registers () inline
Destroys the object. Bogus destructor overriding base class destructor.
Definition at line 105 of file SystemZRegisterInfo.h.
Member Function Documentation
getAddressOfCalleeRegister()
int llvm::SystemZXPLINK64Registers::getAddressOfCalleeRegister () inline
Definition at line 92 of file SystemZRegisterInfo.h.
getCalleeSavedRegs()
const MCPhysReg * SystemZXPLINK64Registers::getCalleeSavedRegs (const MachineFunction * MF) const final override virtual
Returns
an array of all the callee saved registers.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 192 of file SystemZRegisterInfo.cpp.
References llvm::MachineFunction::getSubtarget(), and llvm::SystemZSubtarget::hasVector().
getCallFrameSize()
int llvm::SystemZXPLINK64Registers::getCallFrameSize () inline final override virtual
Returns
the offset to the locals area.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 100 of file SystemZRegisterInfo.h.
getCallPreservedMask()
const uint32_t * SystemZXPLINK64Registers::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const final override virtual
Returns
the mask of all the call preserved registers.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 214 of file SystemZRegisterInfo.cpp.
References llvm::MachineFunction::getSubtarget(), and llvm::SystemZSubtarget::hasVector().
getFramePointerRegister()
int llvm::SystemZXPLINK64Registers::getFramePointerRegister () inline final override virtual
Returns
the register that keeps the frame pointer address.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 90 of file SystemZRegisterInfo.h.
getReturnFunctionAddressRegister()
int llvm::SystemZXPLINK64Registers::getReturnFunctionAddressRegister () inline final override virtual
Returns
the register that keeps the return function address.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 84 of file SystemZRegisterInfo.h.
getStackPointerBias()
int llvm::SystemZXPLINK64Registers::getStackPointerBias () inline final override virtual
Returns
the stack pointer bias.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 102 of file SystemZRegisterInfo.h.
getStackPointerRegister()
int llvm::SystemZXPLINK64Registers::getStackPointerRegister () inline final override virtual
Returns
the register that keeps the stack pointer address.
Implements llvm::SystemZCallingConventionRegisters.
Definition at line 88 of file SystemZRegisterInfo.h.
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZRegisterInfo.h
lib/Target/SystemZ/SystemZRegisterInfo.cpp