LLVM: llvm::MCPseudoProbeDecoder Class Reference
llvm::MCPseudoProbeDecoder Class Reference
#include "llvm/MC/MCPseudoProbe.h"
Public Member Functions
bool buildGUID2FuncDescMap (const uint8_t *Start, std::size_t Size)
bool buildAddress2ProbeMap (const uint8_t *Start, std::size_t Size)
void printGUID2FuncDescMap (raw_ostream &OS)
void printProbeForAddress (raw_ostream &OS, uint64_t Address)
void printProbesForAllAddresses (raw_ostream &OS)
const MCDecodedPseudoProbe * getCallProbeForAddr (uint64_t Address) const
const MCPseudoProbeFuncDesc * getFuncDescForGUID (uint64_t GUID) const
void getInlineContextForProbe (const MCDecodedPseudoProbe *Probe, SmallVectorImpl< MCPseduoProbeFrameLocation > &InlineContextStack, bool IncludeLeaf) const
const AddressProbesMap & getAddress2ProbesMap () const
AddressProbesMap & getAddress2ProbesMap ()
const GUIDProbeFunctionMap & getGUID2FuncDescMap () const
const MCPseudoProbeFuncDesc * getInlinerDescForProbe (const MCDecodedPseudoProbe *Probe) const
const MCDecodedPseudoProbeInlineTree & getDummyInlineRoot () const
Detailed Description
Definition at line 326 of file MCPseudoProbe.h.
Member Function Documentation
buildAddress2ProbeMap()
bool MCPseudoProbeDecoder::buildAddress2ProbeMap (const uint8_t * Start, std::size_t Size)
Definition at line 360 of file MCPseudoProbe.cpp.
References llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::addProbes(), Addr, assert(), llvm::MCDecodedPseudoProbeInlineTree::ChildrenToProcess, llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::getChildren(), llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::getOrAddNode(), llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Guid, I, Offset, llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Parent, and Size.
buildGUID2FuncDescMap()
bool MCPseudoProbeDecoder::buildGUID2FuncDescMap (const uint8_t * Start, std::size_t Size)
Definition at line 315 of file MCPseudoProbe.cpp.
References assert(), Name, llvm::XCOFF::NameSize, and Size.
getAddress2ProbesMap() [1/2]
AddressProbesMap & llvm::MCPseudoProbeDecoder::getAddress2ProbesMap () inline
Definition at line 388 of file MCPseudoProbe.h.
getAddress2ProbesMap() [2/2]
const AddressProbesMap & llvm::MCPseudoProbeDecoder::getAddress2ProbesMap () const inline
Definition at line 384 of file MCPseudoProbe.h.
getCallProbeForAddr()
const MCDecodedPseudoProbe * MCPseudoProbeDecoder::getCallProbeForAddr (uint64_t Address) const
Definition at line 522 of file MCPseudoProbe.cpp.
References assert().
getDummyInlineRoot()
const MCDecodedPseudoProbeInlineTree & llvm::MCPseudoProbeDecoder::getDummyInlineRoot () const inline
Definition at line 397 of file MCPseudoProbe.h.
getFuncDescForGUID()
const MCPseudoProbeFuncDesc * MCPseudoProbeDecoder::getFuncDescForGUID (uint64_t GUID) const
Definition at line 541 of file MCPseudoProbe.cpp.
References assert().
Referenced by getInlineContextForProbe(), and getInlinerDescForProbe().
getGUID2FuncDescMap()
const GUIDProbeFunctionMap & llvm::MCPseudoProbeDecoder::getGUID2FuncDescMap () const inline
Definition at line 390 of file MCPseudoProbe.h.
getInlineContextForProbe()
void MCPseudoProbeDecoder::getInlineContextForProbe (const MCDecodedPseudoProbe * Probe, SmallVectorImpl< MCPseduoProbeFrameLocation > & InlineContextStack, bool IncludeLeaf) const
Definition at line 547 of file MCPseudoProbe.cpp.
References getFuncDescForGUID(), llvm::MCPseudoProbeBase::getGuid(), llvm::MCPseudoProbeBase::getIndex(), and llvm::MCDecodedPseudoProbe::getInlineContext().
getInlinerDescForProbe()
const MCPseudoProbeFuncDesc * MCPseudoProbeDecoder::getInlinerDescForProbe (const MCDecodedPseudoProbe * Probe) const
Definition at line 561 of file MCPseudoProbe.cpp.
References getFuncDescForGUID(), and llvm::MCDecodedPseudoProbe::getInlineTreeNode().
printGUID2FuncDescMap()
void MCPseudoProbeDecoder::printGUID2FuncDescMap (raw_ostream & OS)
Definition at line 487 of file MCPseudoProbe.cpp.
References I.
printProbeForAddress()
void MCPseudoProbeDecoder::printProbeForAddress (raw_ostream & OS, uint64_t Address)
Definition at line 497 of file MCPseudoProbe.cpp.
Referenced by printProbesForAllAddresses().
printProbesForAllAddresses()
void MCPseudoProbeDecoder::printProbesForAllAddresses (raw_ostream & OS)
Definition at line 508 of file MCPseudoProbe.cpp.
References printProbeForAddress().
The documentation for this class was generated from the following files:
include/llvm/MC/MCPseudoProbe.h
lib/MC/MCPseudoProbe.cpp