LLVM: llvm::VarBitInit Class Reference
llvm::VarBitInit Class Reference final
Opcode{0} - Represent access to one bit of a variable or field.
#include "llvm/TableGen/Record.h"
Public Member Functions
VarBitInit (const VarBitInit &)=delete
VarBitInit & operator= (const VarBitInit &)=delete
Init * getBitVar () const
unsigned getBitNum () const
std::string getAsString () const override
Convert this value to a literal form.
Init * resolveReferences (Resolver &R) const override
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
Init * getBit (unsigned B) const override
Get the Init value of the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Get the type of the Init as a RecTy.
Init * getCastTo (RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This function is used to implement the bit range selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This function is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
Is this a complete value with no unset (uninitialized) subvalues?
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print this value.
virtual std::string getAsUnquotedString () const
Convert this value to a literal form, without adding quotes around a string.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
Static Public Member Functions
static bool classof (const Init *I)
static VarBitInit * get (TypedInit *T, unsigned B)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_DagInit , IK_DefInit , IK_FieldInit , IK_IntInit ,
IK_ListInit , IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit ,
IK_UnOpInit , IK_LastOpInit , IK_CondOpInit , IK_FoldOpInit ,
IK_IsAOpInit , IK_AnonymousNameInit , IK_StringInit , IK_VarInit ,
IK_VarListElementInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
Opcode{0} - Represent access to one bit of a variable or field.
Definition at line 1116 of file Record.h.
Constructor & Destructor Documentation
VarBitInit()
llvm::VarBitInit::VarBitInit (const VarBitInit &) delete
Member Function Documentation
classof()
static bool llvm::VarBitInit::classof (const Init * I) inline static
Definition at line 1133 of file Record.h.
References I, and llvm::Init::IK_VarBitInit.
get()
VarBitInit * VarBitInit::get (TypedInit * T, unsigned B) static
Definition at line 1729 of file Record.cpp.
References B, and I.
Referenced by llvm::TypedInit::convertInitializerBitRange(), llvm::OpInit::getBit(), llvm::CondOpInit::getBit(), llvm::FoldOpInit::getBit(), llvm::IsAOpInit::getBit(), llvm::VarInit::getBit(), llvm::VarListElementInit::getBit(), and llvm::FieldInit::getBit().
getAsString()
std::string VarBitInit::getAsString () const override virtual
Convert this value to a literal form.
Implements llvm::Init.
Definition at line 1736 of file Record.cpp.
References llvm::Init::getAsString().
getBit()
Init * llvm::VarBitInit::getBit (unsigned Bit) const inline override virtual
Get the Init value of the specified bit.
Implements llvm::Init.
Definition at line 1145 of file Record.h.
References assert(), and B.
getBitNum()
unsigned llvm::VarBitInit::getBitNum () const inline
Definition at line 1140 of file Record.h.
Referenced by resolveReferences().
getBitVar()
Init * llvm::VarBitInit::getBitVar () const inline
Definition at line 1139 of file Record.h.
operator=()
VarBitInit & llvm::VarBitInit::operator= (const VarBitInit &) delete
resolveReferences()
Init * VarBitInit::resolveReferences (Resolver & R) const override virtual
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1740 of file Record.cpp.
References getBitNum(), I, and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp