LLVM: llvm::DwarfCFIException Class Reference
llvm::DwarfCFIException Class Reference
#include "CodeGen/AsmPrinter/DwarfException.h"
Public Member Functions
DwarfCFIException (AsmPrinter *A)
~DwarfCFIException () override
void endModule () override
Emit all exception information that should come after the content.
void beginFunction (const MachineFunction *MF) override
Gather pre-function exception information.
void endFunction (const MachineFunction *) override
Gather and emit post-function exception information.
void beginFragment (const MachineBasicBlock *MBB, ExceptionSymbolProvider ESP) override
void beginBasicBlock (const MachineBasicBlock &MBB) override
Process beginning of a basic block during basic block sections.
void endBasicBlock (const MachineBasicBlock &MBB) override
Process end of a basic block during basic block sections.
Public Member Functions inherited from llvm::EHStreamer
EHStreamer (AsmPrinter *A)
~EHStreamer () override
void setSymbolSize (const MCSymbol *Sym, uint64_t Size) override
For symbols that have a size designated (e.g.
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void endInstruction () override
Process end of an instruction.
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
virtual void beginModule (Module *M)
virtual void beginFunclet (const MachineBasicBlock &MBB, MCSymbol *Sym=nullptr)
Emit target-specific EH funclet machinery.
virtual void endFunclet ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::EHStreamer
static bool callToNoUnwindFunction (const MachineInstr *MI)
Return ‘true’ if this is a call to a function marked ‘nounwind’.
Protected Types inherited from llvm::EHStreamer
using RangeMapType = DenseMap<MCSymbol *, PadRange>
Protected Member Functions inherited from llvm::DwarfCFIExceptionBase
DwarfCFIExceptionBase (AsmPrinter *A)
void markFunctionEnd () override
void endFragment () override
Protected Member Functions inherited from llvm::EHStreamer
void computeActionsTable (const SmallVectorImpl< const LandingPadInfo * > &LandingPads, SmallVectorImpl< ActionEntry > &Actions, SmallVectorImpl< unsigned > &FirstActions)
Compute the actions table and gather the first action index for each landing pad site.
void computePadMap (const SmallVectorImpl< const LandingPadInfo * > &LandingPads, RangeMapType &PadMap)
virtual void computeCallSiteTable (SmallVectorImpl< CallSiteEntry > &CallSites, SmallVectorImpl< CallSiteRange > &CallSiteRanges, const SmallVectorImpl< const LandingPadInfo * > &LandingPads, const SmallVectorImpl< unsigned > &FirstActions)
Compute the call-site table and the call-site ranges.
MCSymbol * emitExceptionTable ()
Emit landing pads and actions.
virtual void emitTypeInfos (unsigned TTypeEncoding, MCSymbol *TTBaseLabel)
Static Protected Member Functions inherited from llvm::EHStreamer
static unsigned sharedTypeIDs (const LandingPadInfo *L, const LandingPadInfo *R)
How many leading type ids two landing pads have in common.
static bool isFilterEHSelector (int Selector)
static bool isCleanupEHSelector (int Selector)
static bool isCatchEHSelector (int Selector)
Protected Attributes inherited from llvm::DwarfCFIExceptionBase
bool shouldEmitCFI = false
Per-function flag to indicate if frame CFI info should be emitted.
bool hasEmittedCFISections = false
Per-module flag to indicate if .cfi_section has beeen emitted.
Protected Attributes inherited from llvm::EHStreamer
AsmPrinter * Asm
Target of directive emission.
MachineModuleInfo * MMI
Collected machine module information.
Detailed Description
Definition at line 37 of file DwarfException.h.
Constructor & Destructor Documentation
DwarfCFIException()
DwarfCFIException::DwarfCFIException (AsmPrinter * A)
Definition at line 53 of file DwarfCFIException.cpp.
~DwarfCFIException()
DwarfCFIException::~DwarfCFIException () override
Definition at line 56 of file DwarfCFIException.cpp.
Member Function Documentation
beginBasicBlock()
void DwarfCFIException::beginBasicBlock (const MachineBasicBlock & MBB) override virtual
Process beginning of a basic block during basic block sections.
Reimplemented from llvm::AsmPrinterHandler.
Definition at line 182 of file DwarfCFIException.cpp.
References beginFragment(), getExceptionSym(), and MBB.
beginFragment()
void DwarfCFIException::beginFragment (const MachineBasicBlock * MBB, ExceptionSymbolProvider ESP) override virtual
Reimplemented from llvm::AsmPrinterHandler.
Definition at line 131 of file DwarfCFIException.cpp.
References llvm::MachineModuleInfo::addPersonality(), llvm::EHStreamer::Asm, assert(), llvm::AsmPrinter::Debug, llvm::AsmPrinter::EH, F, llvm::TargetOptions::ForceDwarfFrameSection, llvm::TargetLoweringObjectFile::getCFIPersonalitySymbol(), llvm::MachineFunction::getFunction(), llvm::TargetLoweringObjectFile::getLSDAEncoding(), llvm::AsmPrinter::getModuleCFISectionType(), llvm::AsmPrinter::getObjFileLowering(), llvm::MachineBasicBlock::getParent(), llvm::TargetLoweringObjectFile::getPersonalityEncoding(), llvm::DwarfCFIExceptionBase::hasEmittedCFISections, MBB, llvm::EHStreamer::MMI, llvm::TargetMachine::Options, llvm::AsmPrinter::OutStreamer, P, llvm::DwarfCFIExceptionBase::shouldEmitCFI, and llvm::AsmPrinter::TM.
Referenced by beginBasicBlock(), and beginFunction().
beginFunction()
void DwarfCFIException::beginFunction (const MachineFunction * MF) override virtual
Gather pre-function exception information.
Assumes being emitted immediately after the function entry point.
Implements llvm::AsmPrinterHandler.
Definition at line 86 of file DwarfCFIException.cpp.
References llvm::EHStreamer::Asm, llvm::MachineFunction::begin(), beginFragment(), llvm::classifyEHPersonality(), llvm::dwarf::DW_EH_PE_omit, F, llvm::MCContext::getAsmInfo(), llvm::MachineModuleInfo::getContext(), llvm::MCAsmInfo::getExceptionHandlingType(), getExceptionSym(), llvm::MachineFunction::getFunction(), llvm::AsmPrinter::getFunctionCFISectionType(), llvm::MachineFunction::getLandingPads(), llvm::TargetLoweringObjectFile::getLSDAEncoding(), llvm::MachineFunction::getMMI(), llvm::AsmPrinter::getObjFileLowering(), llvm::TargetLoweringObjectFile::getPersonalityEncoding(), llvm::isNoOpWithoutInvoke(), llvm::AsmPrinter::needsCFIForDebug(), llvm::AsmPrinter::None, llvm::None, llvm::DwarfCFIExceptionBase::shouldEmitCFI, and llvm::MCAsmInfo::usesCFIForEH().
endBasicBlock()
void DwarfCFIException::endBasicBlock (const MachineBasicBlock & MBB) override virtual
Process end of a basic block during basic block sections.
Reimplemented from llvm::AsmPrinterHandler.
Definition at line 186 of file DwarfCFIException.cpp.
References llvm::EHStreamer::Asm, llvm::AsmPrinter::OutStreamer, and llvm::DwarfCFIExceptionBase::shouldEmitCFI.
endFunction()
void DwarfCFIException::endFunction (const MachineFunction * MF) override virtual
Gather and emit post-function exception information.
endFunction - Gather and emit post-function exception information.
Implements llvm::AsmPrinterHandler.
Definition at line 175 of file DwarfCFIException.cpp.
References llvm::EHStreamer::emitExceptionTable().
endModule()
void DwarfCFIException::endModule () override virtual
Emit all exception information that should come after the content.
endModule - Emit all exception information that should come after the content.
Implements llvm::AsmPrinterHandler.
Definition at line 60 of file DwarfCFIException.cpp.
References llvm::EHStreamer::Asm, llvm::dwarf::DW_EH_PE_indirect, llvm::TargetLoweringObjectFile::emitPersonalityValue(), llvm::AsmPrinter::getDataLayout(), llvm::AsmPrinter::getObjFileLowering(), llvm::MachineModuleInfo::getPersonalities(), llvm::TargetLoweringObjectFile::getPersonalityEncoding(), llvm::AsmPrinter::getSymbol(), llvm::AsmPrinter::MAI, llvm::EHStreamer::MMI, llvm::AsmPrinter::OutStreamer, and llvm::MCAsmInfo::usesCFIForEH().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/DwarfException.h
lib/CodeGen/AsmPrinter/DwarfCFIException.cpp