LLVM: llvm::LiveRange Class Reference
llvm::LiveRange Class Reference
This class represents the liveness of a register, stack slot, etc.
#include "llvm/CodeGen/LiveInterval.h"
Classes
struct Segment
This represents a simple continuous liveness interval for a value.
Public Types
using Segments = SmallVector<Segment, 2>
using VNInfoList = SmallVector<VNInfo *, 2>
using SegmentSet = std::set<Segment>
using iterator = Segments::iterator
using const_iterator = Segments::const_iterator
using vni_iterator = VNInfoList::iterator
using const_vni_iterator = VNInfoList::const_iterator
Public Member Functions
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
vni_iterator vni_begin ()
vni_iterator vni_end ()
const_vni_iterator vni_begin () const
const_vni_iterator vni_end () const
LiveRange (bool UseSegmentSet=false)
Constructs a new LiveRange object.
LiveRange (const LiveRange &Other, BumpPtrAllocator &Allocator)
Constructs a new LiveRange object by copying segments and valnos from another LiveRange.
void assign (const LiveRange &Other, BumpPtrAllocator &Allocator)
Copies values numbers and live segments from Other into this range.
iterator advanceTo (iterator I, SlotIndex Pos)
advanceTo - Advance the specified iterator to point to the Segment containing the specified position, or end() if the position is past the end of the range.
const_iterator advanceTo (const_iterator I, SlotIndex Pos) const
iterator find (SlotIndex Pos)
find - Return an iterator pointing to the first segment that ends after Pos, or end().
const_iterator find (SlotIndex Pos) const
void clear ()
size_t size () const
bool hasAtLeastOneValue () const
bool containsOneValue () const
unsigned getNumValNums () const
VNInfo * getValNumInfo (unsigned ValNo)
getValNumInfo - Returns pointer to the specified val#.
const VNInfo * getValNumInfo (unsigned ValNo) const
bool containsValue (const VNInfo *VNI) const
containsValue - Returns true if VNI belongs to this range.
VNInfo * getNextValue (SlotIndex def, VNInfo::Allocator &VNInfoAllocator)
getNextValue - Create a new value number and return it.
VNInfo * createDeadDef (SlotIndex Def, VNInfo::Allocator &VNIAlloc)
createDeadDef - Make sure the range has a value defined at Def.
VNInfo * createDeadDef (VNInfo *VNI)
Create a def of value VNI.
VNInfo * createValueCopy (const VNInfo *orig, VNInfo::Allocator &VNInfoAllocator)
Create a copy of the given value.
void RenumberValues ()
RenumberValues - Renumber all values in order of appearance and remove unused values.
VNInfo * MergeValueNumberInto (VNInfo *V1, VNInfo *V2)
MergeValueNumberInto - This method is called when two value numbers are found to be equivalent.
void MergeSegmentsInAsValue (const LiveRange &RHS, VNInfo *LHSValNo)
Merge all of the live segments of a specific val# in RHS into this live range as the specified value number.
void MergeValueInAsValue (const LiveRange &RHS, const VNInfo *RHSValNo, VNInfo *LHSValNo)
MergeValueInAsValue - Merge all of the segments of a specific val# in RHS into this live range as the specified value number.
bool empty () const
SlotIndex beginIndex () const
beginIndex - Return the lowest numbered slot covered.
SlotIndex endIndex () const
endNumber - return the maximum point of the range of the whole, exclusive.
bool expiredAt (SlotIndex index) const
bool liveAt (SlotIndex index) const
const Segment * getSegmentContaining (SlotIndex Idx) const
Return the segment that contains the specified index, or null if there is none.
Segment * getSegmentContaining (SlotIndex Idx)
Return the live segment that contains the specified index, or null if there is none.
VNInfo * getVNInfoAt (SlotIndex Idx) const
getVNInfoAt - Return the VNInfo that is live at Idx, or NULL.
VNInfo * getVNInfoBefore (SlotIndex Idx) const
getVNInfoBefore - Return the VNInfo that is live up to but not necessarilly including Idx, or NULL.
iterator FindSegmentContaining (SlotIndex Idx)
Return an iterator to the segment that contains the specified index, or end() if there is none.
const_iterator FindSegmentContaining (SlotIndex Idx) const
bool overlaps (const LiveRange &other) const
overlaps - Return true if the intersection of the two live ranges is not empty.
bool overlaps (const LiveRange &Other, const CoalescerPair &CP, const SlotIndexes &) const
overlaps - Return true if the two ranges have overlapping segments that are not coalescable according to CP.
bool overlaps (SlotIndex Start, SlotIndex End) const
overlaps - Return true if the live range overlaps an interval specified by [Start, End).
bool overlapsFrom (const LiveRange &Other, const_iterator StartPos) const
overlapsFrom - Return true if the intersection of the two live ranges is not empty.
bool covers (const LiveRange &Other) const
Returns true if all segments of the Other live range are completely covered by this live range.
iterator addSegment (Segment S)
Add the specified Segment to this range, merging segments as appropriate.
std::pair< VNInfo *, bool > extendInBlock (ArrayRef< SlotIndex > Undefs, SlotIndex StartIdx, SlotIndex Kill)
Attempt to extend a value defined after StartIdx to include Use.
VNInfo * extendInBlock (SlotIndex StartIdx, SlotIndex Kill)
Simplified version of the above "extendInBlock", which assumes that no register lanes are undefined by <def,read-undef> operands.
void join (LiveRange &Other, const int *ValNoAssignments, const int *RHSValNoAssignments, SmallVectorImpl< VNInfo * > &NewVNInfo)
join - Join two live ranges (this, and other) together.
bool isLocal (SlotIndex Start, SlotIndex End) const
True iff this segment is a single segment that lies between the specified boundaries, exclusively.
void removeSegment (SlotIndex Start, SlotIndex End, bool RemoveDeadValNo=false)
Remove the specified segment from this range.
void removeSegment (Segment S, bool RemoveDeadValNo=false)
iterator removeSegment (iterator I, bool RemoveDeadValNo=false)
Remove segment pointed to by iterator I from this range.
void removeValNoIfDead (VNInfo *ValNo)
Mark ValNo for deletion if no segments in this range use it.
LiveQueryResult Query (SlotIndex Idx) const
Query Liveness at Idx.
void removeValNo (VNInfo *ValNo)
removeValNo - Remove all the segments defined by the specified value#.
bool isZeroLength (SlotIndexes *Indexes) const
Returns true if the live range is zero length, i.e.
bool isLiveAtIndexes (ArrayRef< SlotIndex > Slots) const
bool operator< (const LiveRange &other) const
bool isUndefIn (ArrayRef< SlotIndex > Undefs, SlotIndex Begin, SlotIndex End) const
Returns true if there is an explicit "undef" between Begin End.
void flushSegmentSet ()
Flush segment set into the regular segment vector.
template<typename Range , typename OutputIt >
bool findIndexesLiveAt (Range &&R, OutputIt O) const
Stores indexes from the input index sequence R at which this LiveRange is live to the output O iterator.
void print (raw_ostream &OS) const
void dump () const
void verify () const
Walk the range and assert if any invariants fail to hold.
Public Attributes
Segments segments
VNInfoList valnos
std::unique_ptr< SegmentSet > segmentSet
Protected Member Functions
void append (const LiveRange::Segment S)
Append a segment to the list of segments.
Friends
class LiveRangeUpdater
Detailed Description
This class represents the liveness of a register, stack slot, etc.
It manages an ordered list of Segment objects. The Segments are organized in a static single assignment form: At places where a new value is defined or different values reach a CFG join a new segment with a new value number is used.
Definition at line 157 of file LiveInterval.h.
Member Typedef Documentation
const_iterator
using llvm::LiveRange::const_iterator = Segments::const_iterator
Definition at line 213 of file LiveInterval.h.
const_vni_iterator
using llvm::LiveRange::const_vni_iterator = VNInfoList::const_iterator
Definition at line 222 of file LiveInterval.h.
iterator
using llvm::LiveRange::iterator = Segments::iterator
Definition at line 212 of file LiveInterval.h.
Segments
using llvm::LiveRange::Segments = SmallVector<Segment, 2>
Definition at line 200 of file LiveInterval.h.
SegmentSet
using llvm::LiveRange::SegmentSet = std::set<Segment>
Definition at line 209 of file LiveInterval.h.
vni_iterator
using llvm::LiveRange::vni_iterator = VNInfoList::iterator
Definition at line 221 of file LiveInterval.h.
VNInfoList
using llvm::LiveRange::VNInfoList = SmallVector<VNInfo *, 2>
Definition at line 201 of file LiveInterval.h.
Constructor & Destructor Documentation
LiveRange() [1/2]
llvm::LiveRange::LiveRange (bool UseSegmentSet = false) inline
Constructs a new LiveRange object.
Definition at line 231 of file LiveInterval.h.
LiveRange() [2/2]
llvm::LiveRange::LiveRange (const LiveRange & Other, BumpPtrAllocator & Allocator) inline
Constructs a new LiveRange object by copying segments and valnos from another LiveRange.
Definition at line 237 of file LiveInterval.h.
References assert(), assign(), and llvm::Other.
Member Function Documentation
addSegment()
LiveRange::iterator LiveRange::addSegment (Segment S)
Add the specified Segment to this range, merging segments as appropriate.
This returns an iterator to the inserted segment (which may have grown since it was inserted).
Definition at line 548 of file LiveInterval.cpp.
References end(), and segmentSet.
Referenced by llvm::LiveRegMatrix::checkInterference(), createSegmentsForValues(), and llvm::MachineBasicBlock::SplitCriticalEdge().
advanceTo() [1/2]
const_iterator llvm::LiveRange::advanceTo (const_iterator I, SlotIndex Pos) const inline
Definition at line 271 of file LiveInterval.h.
References assert(), end(), endIndex(), and I.
advanceTo() [2/2]
iterator llvm::LiveRange::advanceTo (iterator I, SlotIndex Pos) inline
advanceTo - Advance the specified iterator to point to the Segment containing the specified position, or end() if the position is past the end of the range.
If no Segment contains this position, but the position is in a hole, this method returns an iterator pointing to the Segment immediately after the hole.
Definition at line 263 of file LiveInterval.h.
References assert(), end(), endIndex(), and I.
Referenced by covers(), llvm::LiveIntervalUnion::extract(), and isLiveAtIndexes().
append()
void LiveRange::append (const LiveRange::Segment S) protected
Append a segment to the list of segments.
Definition at line 558 of file LiveInterval.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), segments, and llvm::LiveRange::Segment::start.
assign()
void llvm::LiveRange::assign (const LiveRange & Other, BumpPtrAllocator & Allocator) inline
Copies values numbers and live segments from Other into this range.
Definition at line 244 of file LiveInterval.h.
References assert(), createValueCopy(), llvm::Other, llvm::SmallVectorTemplateBase< T, bool >::push_back(), segments, and valnos.
Referenced by LiveRange().
begin() [1/2]
iterator llvm::LiveRange::begin () inline
Definition at line 215 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and segments.
Referenced by llvm::LiveRangeUpdater::add(), llvm::LiveIntervals::addKillFlags(), llvm::LiveIntervals::checkRegMaskInterference(), covers(), llvm::LiveIntervalUnion::extract(), find(), llvm::LiveRangeUpdater::flush(), join(), MergeValueNumberInto(), overlaps(), overlaps(), overlapsFrom(), llvm::LiveRangeUpdater::print(), llvm::LiveIntervalUnion::unify(), and verify().
begin() [2/2]
const_iterator llvm::LiveRange::begin () const inline
Definition at line 218 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and segments.
beginIndex()
SlotIndex llvm::LiveRange::beginIndex () const inline
beginIndex - Return the lowest numbered slot covered.
Definition at line 377 of file LiveInterval.h.
References assert(), empty(), llvm::SmallVectorTemplateCommon< T, typename >::front(), and segments.
Referenced by llvm::LiveIntervals::intervalIsInOneMBB(), isLocal(), llvm::LiveInterval::operator<(), and operator<().
clear()
void llvm::LiveRange::clear () inline
Definition at line 292 of file LiveInterval.h.
References llvm::SmallVectorImpl< T >::clear(), segments, and valnos.
Referenced by llvm::LiveIntervalCalc::calculate(), and llvm::LiveIntervals::HMEditor::updateAllRanges().
containsOneValue()
bool llvm::LiveRange::containsOneValue () const inline
Definition at line 303 of file LiveInterval.h.
References llvm::SmallVectorBase< Size_T >::size(), and valnos.
containsValue()
bool llvm::LiveRange::containsValue (const VNInfo * VNI) const inline
containsValue - Returns true if VNI belongs to this range.
Definition at line 317 of file LiveInterval.h.
References getNumValNums(), and getValNumInfo().
covers()
bool LiveRange::covers (const LiveRange & Other) const
Returns true if all segments of the Other live range are completely covered by this live range.
Adjacent live ranges do not affect the covering:the liverange [1,5](5,10] covers (3,7].
Definition at line 494 of file LiveInterval.cpp.
References advanceTo(), begin(), empty(), end(), I, llvm::Last, and llvm::Other.
Referenced by llvm::LiveIntervals::HMEditor::updateAllRanges(), and llvm::LiveInterval::verify().
createDeadDef() [1/2]
VNInfo * LiveRange::createDeadDef (SlotIndex Def, VNInfo::Allocator & VNIAlloc)
createDeadDef - Make sure the range has a value defined at Def.
If one already exists, return it. Otherwise allocate a new value and add liveness for a dead def.
Definition at line 370 of file LiveInterval.cpp.
References segmentSet.
Referenced by createDeadDef().
createDeadDef() [2/2]
VNInfo * LiveRange::createDeadDef (VNInfo * VNI)
Create a def of value VNI.
Return VNI. If there already exists a definition at VNI->def, the value defined there must be VNI.
Definition at line 378 of file LiveInterval.cpp.
References segmentSet.
createValueCopy()
VNInfo * llvm::LiveRange::createValueCopy (const VNInfo * orig, VNInfo::Allocator & VNInfoAllocator) inline
Create a copy of the given value.
The new value will be identical except for the Value number.
Definition at line 341 of file LiveInterval.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase< Size_T >::size(), and valnos.
Referenced by assign().
dump()
LLVM_DUMP_METHOD void LiveRange::dump () const
Definition at line 1056 of file LiveInterval.cpp.
References llvm::dbgs().
empty()
bool llvm::LiveRange::empty () const inline
Definition at line 374 of file LiveInterval.h.
References llvm::SmallVectorBase< Size_T >::empty(), and segments.
Referenced by llvm::LiveIntervals::addKillFlags(), beginIndex(), llvm::LiveIntervalCalc::calculate(), llvm::LiveRegMatrix::checkInterference(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::LiveRegMatrix::checkRegUnitInterference(), covers(), endIndex(), llvm::LiveIntervalUnion::extract(), find(), llvm::LiveIntervals::intervalIsInOneMBB(), join(), overlaps(), overlaps(), overlapsFrom(), print(), removeValNo(), and llvm::LiveIntervalUnion::unify().
end() [1/2]
iterator llvm::LiveRange::end () inline
Definition at line 216 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and segments.
Referenced by llvm::LiveRangeUpdater::add(), llvm::LiveIntervals::addKillFlags(), addSegment(), advanceTo(), advanceTo(), llvm::LiveIntervals::checkRegMaskInterference(), covers(), llvm::LiveIntervalUnion::extract(), find(), FindSegmentContaining(), FindSegmentContaining(), getSegmentContaining(), getSegmentContaining(), getVNInfoAt(), getVNInfoBefore(), isLiveAtIndexes(), isPlainlyKilled(), join(), liveAt(), MergeValueNumberInto(), overlaps(), overlapsFrom(), llvm::LiveRangeUpdater::print(), Query(), removeSegment(), llvm::LiveIntervalUnion::unify(), and verify().
end() [2/2]
const_iterator llvm::LiveRange::end () const inline
Definition at line 219 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and segments.
endIndex()
SlotIndex llvm::LiveRange::endIndex () const inline
endNumber - return the maximum point of the range of the whole, exclusive.
Definition at line 384 of file LiveInterval.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), empty(), and segments.
Referenced by advanceTo(), advanceTo(), llvm::LiveIntervals::checkRegMaskInterference(), expiredAt(), find(), llvm::LiveIntervals::intervalIsInOneMBB(), and isLocal().
expiredAt()
bool llvm::LiveRange::expiredAt (SlotIndex index) const inline
Definition at line 389 of file LiveInterval.h.
References endIndex().
Referenced by regJustKilledBefore().
extendInBlock() [1/2]
std::pair< VNInfo *, bool > LiveRange::extendInBlock (ArrayRef< SlotIndex > Undefs, SlotIndex StartIdx, SlotIndex Kill)
Attempt to extend a value defined after StartIdx to include Use.
Both StartIdx and Use should be in the same basic block. In case of subranges, an extension could be prevented by an explicit "undef" caused by a <def,read-undef> on a non-overlapping lane. The list of location of such "undefs" should be provided in Undefs. The return value is a pair: the first element is VNInfo of the value that was extended (possibly nullptr), the second is a boolean value indicating whether an "undef" was encountered. If this range is live before Use in the basic block that starts at StartIdx, and there is no intervening "undef", extend it to be live up to Use, and return the pair {value, false}. If there is no segment before Use and there is no "undef" between StartIdx and Use, return {nullptr, false}. If there is an "undef" before Use, return {nullptr, true}.
Definition at line 564 of file LiveInterval.cpp.
References segmentSet.
Referenced by llvm::LiveRangeCalc::extend().
extendInBlock() [2/2]
VNInfo * LiveRange::extendInBlock (SlotIndex StartIdx, SlotIndex Kill)
Simplified version of the above "extendInBlock", which assumes that no register lanes are undefined by <def,read-undef> operands.
If this range is live before Use in the basic block that starts at StartIdx, extend it to be live up to Use, and return the value. If there is no segment before Use, return nullptr.
Definition at line 573 of file LiveInterval.cpp.
References segmentSet.
find() [1/2]
LiveRange::iterator LiveRange::find (SlotIndex Pos)
find - Return an iterator pointing to the first segment that ends after Pos, or end().
This is the same as advanceTo(begin(), Pos), but faster when searching large ranges.
If Pos is contained in a Segment, that segment is returned. If Pos is in a hole, the following Segment is returned. If Pos is beyond endIndex, end() is returned.
Definition at line 350 of file LiveInterval.cpp.
References begin(), empty(), end(), endIndex(), I, and size().
Referenced by llvm::LiveRangeUpdater::add(), find(), FindSegmentContaining(), FindSegmentContaining(), isLiveAtIndexes(), isPlainlyKilled(), liveAt(), overlaps(), Query(), and removeSegment().
find() [2/2]
const_iterator llvm::LiveRange::find (SlotIndex Pos) const inline
Definition at line 288 of file LiveInterval.h.
References find().
findIndexesLiveAt()
template<typename Range , typename OutputIt > bool llvm::LiveRange::findIndexesLiveAt (Range && R, OutputIt O) const inline
Stores indexes from the input index sequence R at which this LiveRange is live to the output O iterator.
R is a range of ascending sorted random access iterators to the input indexes. Indexes stored at O are ascending sorted so it can be used directly in the subsequent search (for example for subranges). Returns true if found at least one index.
Definition at line 619 of file LiveInterval.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), Idx, llvm::is_sorted(), and segments.
FindSegmentContaining() [1/2]
iterator llvm::LiveRange::FindSegmentContaining (SlotIndex Idx) inline
Return an iterator to the segment that contains the specified index, or end() if there is none.
Definition at line 428 of file LiveInterval.h.
References end(), find(), I, and Idx.
Referenced by getSegmentContaining(), getSegmentContaining(), getVNInfoAt(), getVNInfoBefore(), and moveAndTeeForMultiUse().
FindSegmentContaining() [2/2]
const_iterator llvm::LiveRange::FindSegmentContaining (SlotIndex Idx) const inline
Definition at line 433 of file LiveInterval.h.
References end(), find(), I, and Idx.
flushSegmentSet()
void LiveRange::flushSegmentSet ()
Flush segment set into the regular segment vector.
The method is to be called after the live range has been created, if use of the segment set was activated in the constructor of the live range.
Definition at line 805 of file LiveInterval.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::SmallVectorBase< Size_T >::empty(), segments, segmentSet, and verify().
getNextValue()
VNInfo * llvm::LiveRange::getNextValue (SlotIndex def, VNInfo::Allocator & VNInfoAllocator) inline
getNextValue - Create a new value number and return it.
MIIdx specifies the instruction that defines the value number.
Definition at line 323 of file LiveInterval.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase< Size_T >::size(), and valnos.
getNumValNums()
unsigned llvm::LiveRange::getNumValNums () const inline
Definition at line 305 of file LiveInterval.h.
References llvm::SmallVectorBase< Size_T >::size(), and valnos.
Referenced by llvm::ConnectedVNInfoEqClasses::Classify(), containsValue(), join(), and print().
getSegmentContaining() [1/2]
Segment * llvm::LiveRange::getSegmentContaining (SlotIndex Idx) inline
Return the live segment that contains the specified index, or null if there is none.
Definition at line 407 of file LiveInterval.h.
References end(), FindSegmentContaining(), I, and Idx.
getSegmentContaining() [2/2]
const Segment * llvm::LiveRange::getSegmentContaining (SlotIndex Idx) const inline
Return the segment that contains the specified index, or null if there is none.
Definition at line 400 of file LiveInterval.h.
References end(), FindSegmentContaining(), I, and Idx.
Referenced by llvm::X86InstrInfo::classifyLEAReg(), llvm::RISCVInstrInfo::convertToThreeAddress(), llvm::RegPressureTracker::getLiveThroughAt(), removeDeadSegment(), and llvm::LiveIntervals::shrinkToUses().
getValNumInfo() [1/2]
VNInfo * llvm::LiveRange::getValNumInfo (unsigned ValNo) inline
getValNumInfo - Returns pointer to the specified val#.
Definition at line 309 of file LiveInterval.h.
References valnos.
Referenced by containsValue(), join(), and print().
getValNumInfo() [2/2]
const VNInfo * llvm::LiveRange::getValNumInfo (unsigned ValNo) const inline
Definition at line 312 of file LiveInterval.h.
References valnos.
getVNInfoAt()
VNInfo * llvm::LiveRange::getVNInfoAt (SlotIndex Idx) const inline
getVNInfoAt - Return the VNInfo that is live at Idx, or NULL.
Definition at line 413 of file LiveInterval.h.
References end(), FindSegmentContaining(), I, and Idx.
Referenced by llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::SplitEditor::enterIntvAfter(), llvm::SplitEditor::enterIntvAtEnd(), llvm::SplitEditor::enterIntvBefore(), llvm::SIRegisterInfo::findReachingDef(), hasOneUse(), llvm::SplitEditor::leaveIntvAfter(), llvm::SplitEditor::leaveIntvAtTop(), llvm::SplitEditor::leaveIntvBefore(), moveAndTeeForMultiUse(), llvm::SplitEditor::overlapIntv(), llvm::LiveIntervals::removePhysRegDefAt(), llvm::LiveIntervals::removeVRegDefAt(), and llvm::MachineBasicBlock::SplitCriticalEdge().
getVNInfoBefore()
VNInfo * llvm::LiveRange::getVNInfoBefore (SlotIndex Idx) const inline
getVNInfoBefore - Return the VNInfo that is live up to but not necessarilly including Idx, or NULL.
Use this to find the reaching def used by an instruction at this SlotIndex position.
Definition at line 421 of file LiveInterval.h.
References end(), FindSegmentContaining(), I, and Idx.
Referenced by llvm::ConnectedVNInfoEqClasses::Classify(), llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), getVRegDef(), llvm::LiveIntervals::hasPHIKill(), oneUseDominatesOtherUses(), llvm::SplitEditor::overlapIntv(), and llvm::ScheduleDAGMILive::updatePressureDiffs().
hasAtLeastOneValue()
bool llvm::LiveRange::hasAtLeastOneValue () const inline
Definition at line 301 of file LiveInterval.h.
References llvm::SmallVectorBase< Size_T >::empty(), and valnos.
Referenced by isPlainlyKilled(), and llvm::LiveIntervals::repairIntervalsInRange().
isLiveAtIndexes()
bool LiveRange::isLiveAtIndexes (ArrayRef< SlotIndex > Slots) const
Definition at line 815 of file LiveInterval.cpp.
References advanceTo(), end(), and find().
Referenced by llvm::VirtRegAuxInfo::weightCalcHelper().
isLocal()
bool llvm::LiveRange::isLocal (SlotIndex Start, SlotIndex End) const inline
True iff this segment is a single segment that lies between the specified boundaries, exclusively.
Vregs live across a backedge are not considered local. The boundaries are expected to lie within an extended basic block, so vregs that are not live out should contain no holes.
Definition at line 510 of file LiveInterval.h.
References beginIndex(), and endIndex().
isUndefIn()
bool llvm::LiveRange::isUndefIn (ArrayRef< SlotIndex > Undefs, SlotIndex Begin, SlotIndex End) const inline
Returns true if there is an explicit "undef" between Begin End.
Definition at line 599 of file LiveInterval.h.
References llvm::any_of(), and Idx.
isZeroLength()
bool llvm::LiveRange::isZeroLength (SlotIndexes * Indexes) const inline
Returns true if the live range is zero length, i.e.
no live segments span instructions. It doesn't pay to spill such a range.
Definition at line 578 of file LiveInterval.h.
References llvm::SlotIndex::getBaseIndex(), llvm::SlotIndexes::getNextNonNullIndex(), and segments.
Referenced by llvm::VirtRegAuxInfo::weightCalcHelper().
join()
void LiveRange::join (LiveRange & Other, const int * ValNoAssignments, const int * RHSValNoAssignments, SmallVectorImpl< VNInfo * > & NewVNInfo)
join - Join two live ranges (this, and other) together.
This applies mappings to the value numbers in the LHS/RHS ranges as specified. If the ranges are not joinable, this aborts.
Definition at line 642 of file LiveInterval.cpp.
References llvm::LiveRangeUpdater::add(), assert(), begin(), E, empty(), end(), llvm::SmallVectorImpl< T >::erase(), getNumValNums(), getValNumInfo(), I, llvm::Other, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::resize(), segments, valnos, and verify().
liveAt()
bool llvm::LiveRange::liveAt (SlotIndex index) const inline
Definition at line 393 of file LiveInterval.h.
References end(), and find().
Referenced by llvm::GCNDownwardRPTracker::advanceBeforeNext(), getLiveLanesAt(), llvm::RegPressureTracker::getLiveLanesAt(), llvm::LiveIntervals::isLiveInToMBB(), llvm::LiveIntervals::isLiveOutOfMBB(), rematerializeCheapDef(), llvm::MachineBasicBlock::SplitCriticalEdge(), and subRangeLiveAt().
MergeSegmentsInAsValue()
void LiveRange::MergeSegmentsInAsValue (const LiveRange & RHS, VNInfo * LHSValNo)
Merge all of the live segments of a specific val# in RHS into this live range as the specified value number.
Merge all of the segments in RHS into this live range as the specified value number.
The segments in RHS are allowed to overlap with segments in the current range, it will replace the value numbers of the overlaped live segments with the specified value number.
The segments in RHS are allowed to overlap with segments in the current range, but only if the overlapping segments have the specified value number.
Definition at line 725 of file LiveInterval.cpp.
References llvm::LiveRangeUpdater::add().
MergeValueInAsValue()
void LiveRange::MergeValueInAsValue (const LiveRange & RHS, const VNInfo * RHSValNo, VNInfo * LHSValNo)
MergeValueInAsValue - Merge all of the segments of a specific val# in RHS into this live range as the specified value number.
MergeValueInAsValue - Merge all of the live segments of a specific val# in RHS into this live range as the specified value number.
The segments in RHS are allowed to overlap with segments in the current range, but only if the overlapping segments have the specified value number.
The segments in RHS are allowed to overlap with segments in the current range, it will replace the value numbers of the overlaped segments with the specified value number.
Definition at line 737 of file LiveInterval.cpp.
References llvm::LiveRangeUpdater::add().
MergeValueNumberInto()
VNInfo * LiveRange::MergeValueNumberInto (VNInfo * V1, VNInfo * V2)
MergeValueNumberInto - This method is called when two value numbers are found to be equivalent.
MergeValueNumberInto - This method is called when two value nubmers are found to be equivalent.
This eliminates V1, replacing all segments with the V1 value number with the V2 value number. This can cause merging of V1/V2 values numbers and compaction of the value space.
Definition at line 750 of file LiveInterval.cpp.
References assert(), begin(), end(), llvm::SmallVectorImpl< T >::erase(), I, segments, and std::swap().
operator<()
bool llvm::LiveRange::operator< (const LiveRange & other) const inline
Definition at line 591 of file LiveInterval.h.
References beginIndex().
overlaps() [1/3]
bool llvm::LiveRange::overlaps (const LiveRange & other) const inline
overlaps - Return true if the intersection of the two live ranges is not empty.
Definition at line 440 of file LiveInterval.h.
References begin(), empty(), and overlapsFrom().
Referenced by llvm::LiveRegMatrix::checkRegUnitInterference().
overlaps() [2/3]
bool LiveRange::overlaps (const LiveRange & Other, const CoalescerPair & CP, const SlotIndexes & Indexes) const
overlaps - Return true if the two ranges have overlapping segments that are not coalescable according to CP.
Overlapping segments where one range is defined by a coalescable copy are allowed.
Definition at line 445 of file LiveInterval.cpp.
References assert(), empty(), end(), find(), llvm::SlotIndexes::getInstructionFromIndex(), I, llvm::Other, and std::swap().
overlaps() [3/3]
bool LiveRange::overlaps (SlotIndex Start, SlotIndex End) const
overlaps - Return true if the live range overlaps an interval specified by [Start, End).
Definition at line 488 of file LiveInterval.cpp.
References assert(), begin(), I, and llvm::lower_bound().
overlapsFrom()
bool LiveRange::overlapsFrom (const LiveRange & Other, const_iterator StartPos) const
overlapsFrom - Return true if the intersection of the two live ranges is not empty.
The specified iterator is a hint that we can begin scanning the Other range starting at I.
Definition at line 404 of file LiveInterval.cpp.
References assert(), begin(), empty(), end(), and std::swap().
Referenced by overlaps().
print()
void LiveRange::print (raw_ostream & OS) const
Definition at line 1011 of file LiveInterval.cpp.
References assert(), empty(), getNumValNums(), getValNumInfo(), segments, vni_begin(), and vni_end().
Referenced by llvm::LiveRangeUpdater::dump(), and llvm::operator<<().
Query()
LiveQueryResult llvm::LiveRange::Query (SlotIndex Idx) const inline
Query Liveness at Idx.
The sub-instruction slot of Idx doesn't matter, only the instruction it refers to is considered.
Definition at line 533 of file LiveInterval.h.
References llvm::VNInfo::def, E, end(), find(), I, Idx, llvm::SlotIndex::isEarlierInstr(), and llvm::SlotIndex::isSameInstr().
Referenced by llvm::ScheduleDAGMILive::computeCyclicCriticalPath(), llvm::RegisterOperands::detectDeadDefs(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::LiveIntervals::handleMoveIntoNewBundle(), hasOneUse(), isDefBetween(), isDefInSubRange(), llvm::LiveIntervals::pruneValue(), llvm::LiveIntervals::shrinkToUses(), and llvm::ScheduleDAGMILive::updatePressureDiffs().
removeSegment() [1/3]
LiveRange::iterator LiveRange::removeSegment (iterator I, bool RemoveDeadValNo = false)
Remove segment pointed to by iterator I from this range.
Definition at line 619 of file LiveInterval.cpp.
References llvm::SmallVectorImpl< T >::erase(), I, removeValNoIfDead(), and segments.
removeSegment() [2/3]
void llvm::LiveRange::removeSegment (Segment S, bool RemoveDeadValNo = false) inline
Definition at line 520 of file LiveInterval.h.
References llvm::LiveRange::Segment::end, removeSegment(), and llvm::LiveRange::Segment::start.
removeSegment() [3/3]
void LiveRange::removeSegment (SlotIndex Start, SlotIndex End, bool RemoveDeadValNo = false)
Remove the specified segment from this range.
Note that the segment must be a single Segment in its entirety.
Note that the segment must be in a single Segment in its entirety.
Definition at line 583 of file LiveInterval.cpp.
References assert(), end(), llvm::SmallVectorImpl< T >::erase(), find(), I, llvm::SmallVectorImpl< T >::insert(), removeValNoIfDead(), and segments.
Referenced by moveForSingleUse(), llvm::LiveIntervals::pruneValue(), removeDeadSegment(), removeSegment(), llvm::LiveIntervals::shrinkToUses(), and llvm::MachineBasicBlock::SplitCriticalEdge().
removeValNo()
void LiveRange::removeValNo (VNInfo * ValNo)
removeValNo - Remove all the segments defined by the specified value#.
Also remove the value# from value# list.
Definition at line 634 of file LiveInterval.cpp.
References empty(), llvm::erase_if(), segments, and llvm::LiveRange::Segment::valno.
Referenced by llvm::LiveIntervals::removePhysRegDefAt(), llvm::LiveIntervals::removeVRegDefAt(), and stripValuesNotDefiningMask().
removeValNoIfDead()
void LiveRange::removeValNoIfDead (VNInfo * ValNo)
Mark ValNo for deletion if no segments in this range use it.
Definition at line 627 of file LiveInterval.cpp.
References llvm::none_of(), and llvm::LiveRange::Segment::valno.
Referenced by removeSegment(), and removeSegment().
RenumberValues()
void LiveRange::RenumberValues ()
RenumberValues - Renumber all values in order of appearance and remove unused values.
RenumberValues - Renumber all values in order of appearance and delete the remaining unused values.
Definition at line 531 of file LiveInterval.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), segments, llvm::SmallVectorBase< Size_T >::size(), and valnos.
Referenced by llvm::LiveRangeEdit::eliminateDeadDefs(), and llvm::SplitEditor::finish().
size()
size_t llvm::LiveRange::size () const inline
Definition at line 297 of file LiveInterval.h.
References segments, and llvm::SmallVectorBase< Size_T >::size().
Referenced by find(), and llvm::TargetRegisterInfo::shouldRegionSplitForVirtReg().
verify()
void LiveRange::verify () const
Walk the range and assert if any invariants fail to hold.
Note that this is a no-op when asserts are disabled.
Definition at line 1070 of file LiveInterval.cpp.
References assert(), begin(), E, end(), I, llvm::SmallVectorBase< Size_T >::size(), and valnos.
Referenced by llvm::LiveRangeUpdater::flush(), flushSegmentSet(), and join().
vni_begin() [1/2]
vni_iterator llvm::LiveRange::vni_begin () inline
Definition at line 224 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and valnos.
Referenced by llvm::VirtRegAuxInfo::isRematerializable(), print(), and llvm::LiveIntervals::shrinkToUses().
vni_begin() [2/2]
const_vni_iterator llvm::LiveRange::vni_begin () const inline
Definition at line 227 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and valnos.
vni_end() [1/2]
vni_iterator llvm::LiveRange::vni_end () inline
Definition at line 225 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and valnos.
Referenced by llvm::VirtRegAuxInfo::isRematerializable(), print(), and llvm::LiveIntervals::shrinkToUses().
vni_end() [2/2]
const_vni_iterator llvm::LiveRange::vni_end () const inline
Definition at line 228 of file LiveInterval.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and valnos.
Friends And Related Symbol Documentation
LiveRangeUpdater
friend class LiveRangeUpdater friend
Definition at line 668 of file LiveInterval.h.
Member Data Documentation
segments
Segments llvm::LiveRange::segments
Definition at line 203 of file LiveInterval.h.
Referenced by llvm::LiveRangeUpdater::add(), append(), assign(), begin(), begin(), beginIndex(), clear(), empty(), end(), end(), endIndex(), findIndexesLiveAt(), llvm::LiveRangeUpdater::flush(), flushSegmentSet(), llvm::LiveInterval::getSize(), isZeroLength(), join(), MergeValueNumberInto(), print(), removeSegment(), removeSegment(), removeValNo(), RenumberValues(), llvm::LiveIntervals::shrinkToUses(), and size().
segmentSet
std::unique_ptr<SegmentSet> llvm::LiveRange::segmentSet
Definition at line 210 of file LiveInterval.h.
Referenced by llvm::LiveRangeUpdater::add(), addSegment(), createDeadDef(), createDeadDef(), extendInBlock(), extendInBlock(), and flushSegmentSet().
valnos
VNInfoList llvm::LiveRange::valnos
Definition at line 204 of file LiveInterval.h.
Referenced by assign(), llvm::ConnectedVNInfoEqClasses::Classify(), clear(), containsOneValue(), createValueCopy(), llvm::SplitEditor::finish(), getNextValue(), getNumValNums(), getValNumInfo(), getValNumInfo(), hasAtLeastOneValue(), llvm::LiveIntervals::hasPHIKill(), join(), RenumberValues(), llvm::LiveIntervals::shrinkToUses(), stripValuesNotDefiningMask(), verify(), vni_begin(), vni_begin(), vni_end(), and vni_end().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveInterval.h
lib/CodeGen/LiveInterval.cpp