LLVM: llvm::RuntimeDyldImpl Class Reference
llvm::RuntimeDyldImpl Class Reference abstract
#include "ExecutionEngine/RuntimeDyld/RuntimeDyldImpl.h"
Public Member Functions
RuntimeDyldImpl (RuntimeDyld::MemoryManager &MemMgr, JITSymbolResolver &Resolver)
virtual ~RuntimeDyldImpl ()
void setProcessAllSections (bool ProcessAllSections)
virtual std::unique_ptr< RuntimeDyld::LoadedObjectInfo > loadObject (const object::ObjectFile &Obj)=0
uint64_t getSectionLoadAddress (unsigned SectionID) const
uint8_t * getSectionAddress (unsigned SectionID) const
StringRef getSectionContent (unsigned SectionID) const
uint8_t * getSymbolLocalAddress (StringRef Name) const
unsigned getSymbolSectionID (StringRef Name) const
JITEvaluatedSymbol getSymbol (StringRef Name) const
std::map< StringRef, JITEvaluatedSymbol > getSymbolTable () const
void resolveRelocations ()
void resolveLocalRelocations ()
void reassignSectionAddress (unsigned SectionID, uint64_t Addr)
void mapSectionAddress (const void *LocalAddress, uint64_t TargetAddress)
bool hasError ()
void clearError ()
StringRef getErrorString ()
virtual bool isCompatibleFile (const ObjectFile &Obj) const =0
void setNotifyStubEmitted (NotifyStubEmittedFunction NotifyStubEmitted)
virtual void registerEHFrames ()
void deregisterEHFrames ()
virtual Error finalizeLoad (const ObjectFile &ObjImg, ObjSectionToIDMap &SectionMap)
Static Public Member Functions
static void finalizeAsync (std::unique_ptr< RuntimeDyldImpl > This, unique_function< void(object::OwningBinary< object::ObjectFile >, std::unique_ptr< RuntimeDyld::LoadedObjectInfo >, Error)> OnEmitted, object::OwningBinary< object::ObjectFile > O, std::unique_ptr< RuntimeDyld::LoadedObjectInfo > Info)
Protected Types
typedef std::deque< SectionEntry > SectionList
typedef unsigned SID
typedef std::map< SectionRef, unsigned > ObjSectionToIDMap
typedef std::vector< SymbolRef > CommonSymbolList
typedef SmallVector< RelocationEntry, 64 > RelocationList
typedef std::map< RelocationValueRef, uintptr_t > StubMap
using NotifyStubEmittedFunction
Protected Member Functions
virtual unsigned getMaxStubSize () const =0
virtual unsigned getStubAlignment ()=0
void writeInt16BE (uint8_t *Addr, uint16_t Value)
void writeInt32BE (uint8_t *Addr, uint32_t Value)
void writeInt64BE (uint8_t *Addr, uint64_t Value)
virtual void setMipsABI (const ObjectFile &Obj)
uint64_t readBytesUnaligned (uint8_t *Src, unsigned Size) const
Endian-aware read Read the least significant Size bytes from Src.
void writeBytesUnaligned (uint64_t Value, uint8_t *Dst, unsigned Size) const
Endian-aware write.
virtual Expected< JITSymbolFlags > getJITSymbolFlags (const SymbolRef &Sym)
Generate JITSymbolFlags from a libObject symbol.
virtual uint64_t modifyAddressBasedOnFlags (uint64_t Addr, JITSymbolFlags Flags) const
Modify the given target address based on the given symbol flags.
Error emitCommonSymbols (const ObjectFile &Obj, CommonSymbolList &CommonSymbols, uint64_t CommonSize, uint32_t CommonAlign)
Given the common symbols discovered in the object file, emit a new section for them and update the symbol mappings in the object and symbol table.
Expected< unsigned > emitSection (const ObjectFile &Obj, const SectionRef &Section, bool IsCode)
Emits section data from the object file to the MemoryManager.
Expected< unsigned > findOrEmitSection (const ObjectFile &Obj, const SectionRef &Section, bool IsCode, ObjSectionToIDMap &LocalSections)
Find Section in LocalSections.
void addRelocationForSection (const RelocationEntry &RE, unsigned SectionID)
void addRelocationForSymbol (const RelocationEntry &RE, StringRef SymbolName)
uint8_t * createStubFunction (uint8_t *Addr, unsigned AbiVariant=0)
Emits long jump instruction to Addr.
void resolveRelocationList (const RelocationList &Relocs, uint64_t Value)
Resolves relocations from Relocs list with address from Value.
virtual void resolveRelocation (const RelocationEntry &RE, uint64_t Value)=0
A object file specific relocation resolver.
virtual Expected< relocation_iterator > processRelocationRef (unsigned SectionID, relocation_iterator RelI, const ObjectFile &Obj, ObjSectionToIDMap &ObjSectionToID, StubMap &Stubs)=0
Parses one or more object file relocations (some object files use relocation pairs) and stores it to Relocations or SymbolRelocations (this depends on the object file type).
void applyExternalSymbolRelocations (const StringMap< JITEvaluatedSymbol > ExternalSymbolMap)
Error resolveExternalSymbols ()
Resolve relocations to external symbols.
Error computeTotalAllocSize (const ObjectFile &Obj, uint64_t &CodeSize, uint32_t &CodeAlign, uint64_t &RODataSize, uint32_t &RODataAlign, uint64_t &RWDataSize, uint32_t &RWDataAlign)
unsigned computeGOTSize (const ObjectFile &Obj)
unsigned computeSectionStubBufSize (const ObjectFile &Obj, const SectionRef &Section)
Expected< ObjSectionToIDMap > loadObjectImpl (const object::ObjectFile &Obj)
virtual size_t getGOTEntrySize ()
virtual bool relocationNeedsGot (const RelocationRef &R) const
virtual bool relocationNeedsStub (const RelocationRef &R) const
Protected Attributes
RuntimeDyld::MemoryManager & MemMgr
JITSymbolResolver & Resolver
SectionList Sections
RTDyldSymbolTable GlobalSymbolTable
std::unordered_map< unsigned, RelocationList > Relocations
StringMap< RelocationList > ExternalSymbolRelocations
Triple::ArchType Arch
bool IsTargetLittleEndian
bool IsMipsO32ABI
bool IsMipsN32ABI
bool IsMipsN64ABI
bool ProcessAllSections
sys::Mutex lock
NotifyStubEmittedFunction NotifyStubEmitted
bool HasError
std::string ErrorStr
Static Protected Attributes
static const unsigned AbsoluteSymbolSection = ~0U
Friends
class RuntimeDyld::LoadedObjectInfo
Detailed Description
Definition at line 238 of file RuntimeDyldImpl.h.
Member Typedef Documentation
CommonSymbolList
typedef std::vector<SymbolRef> llvm::RuntimeDyldImpl::CommonSymbolList protected
Definition at line 267 of file RuntimeDyldImpl.h.
NotifyStubEmittedFunction
using llvm::RuntimeDyldImpl::NotifyStubEmittedFunction protected
Initial value:
    RuntimeDyld::NotifyStubEmittedFunction
Definition at line 310 of file RuntimeDyldImpl.h.
ObjSectionToIDMap
typedef std::map<SectionRef, unsigned> llvm::RuntimeDyldImpl::ObjSectionToIDMap protected
Definition at line 261 of file RuntimeDyldImpl.h.
RelocationList
typedef SmallVector<RelocationEntry, 64> llvm::RuntimeDyldImpl::RelocationList protected
Definition at line 274 of file RuntimeDyldImpl.h.
SectionList
typedef std::deque<SectionEntry> llvm::RuntimeDyldImpl::SectionList protected
Definition at line 253 of file RuntimeDyldImpl.h.
SID
typedef unsigned llvm::RuntimeDyldImpl::SID protected
Definition at line 256 of file RuntimeDyldImpl.h.
StubMap
typedef std::map<RelocationValueRef, uintptr_t> llvm::RuntimeDyldImpl::StubMap protected
Definition at line 286 of file RuntimeDyldImpl.h.
Constructor & Destructor Documentation
RuntimeDyldImpl()
llvm::RuntimeDyldImpl::RuntimeDyldImpl (RuntimeDyld::MemoryManager & MemMgr, JITSymbolResolver & Resolver) inline
Definition at line 449 of file RuntimeDyldImpl.h.
~RuntimeDyldImpl()
RuntimeDyldImpl::~RuntimeDyldImpl () virtual
Definition at line 69 of file RuntimeDyld.cpp.
Member Function Documentation
addRelocationForSection()
void llvm::RuntimeDyldImpl::addRelocationForSection (const RelocationEntry & RE, unsigned SectionID) protected
Definition at line 952 of file RuntimeDyld.cpp.
Referenced by llvm::RuntimeDyldCOFFAArch64::processRelocationRef(), llvm::RuntimeDyldCOFFI386::processRelocationRef(), llvm::RuntimeDyldCOFFThumb::processRelocationRef(), llvm::RuntimeDyldCOFFX86_64::processRelocationRef(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), llvm::RuntimeDyldMachOI386::processRelocationRef(), llvm::RuntimeDyldMachOX86_64::processRelocationRef(), llvm::RuntimeDyldELF::processRelocationRef(), and llvm::RuntimeDyldMachO::processScatteredVANILLA().
addRelocationForSymbol()
void llvm::RuntimeDyldImpl::addRelocationForSymbol (const RelocationEntry & RE, StringRef SymbolName) protected
Definition at line 957 of file RuntimeDyld.cpp.
References assert().
Referenced by llvm::RuntimeDyldCOFF::getDLLImportOffset(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), llvm::RuntimeDyldCOFFAArch64::processRelocationRef(), llvm::RuntimeDyldCOFFI386::processRelocationRef(), llvm::RuntimeDyldCOFFThumb::processRelocationRef(), llvm::RuntimeDyldCOFFX86_64::processRelocationRef(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), llvm::RuntimeDyldMachOI386::processRelocationRef(), llvm::RuntimeDyldMachOX86_64::processRelocationRef(), and llvm::RuntimeDyldELF::processRelocationRef().
applyExternalSymbolRelocations()
void llvm::RuntimeDyldImpl::applyExternalSymbolRelocations (const StringMap< JITEvaluatedSymbol > ExternalSymbolMap) protected
Definition at line 1116 of file RuntimeDyld.cpp.
References Addr, assert(), llvm::dbgs(), llvm::format(), LLVM_DEBUG, Name, llvm::report_fatal_error(), and UINT64_MAX.
clearError()
void llvm::RuntimeDyldImpl::clearError () inline
Definition at line 561 of file RuntimeDyldImpl.h.
References HasError.
computeGOTSize()
unsigned llvm::RuntimeDyldImpl::computeGOTSize (const ObjectFile & Obj) protected
Definition at line 650 of file RuntimeDyld.cpp.
References llvm::object::ObjectFile::section_begin(), llvm::object::ObjectFile::section_end(), and SI.
computeSectionStubBufSize()
unsigned llvm::RuntimeDyldImpl::computeSectionStubBufSize (const ObjectFile & Obj, const SectionRef & Section) protected
Definition at line 668 of file RuntimeDyld.cpp.
References llvm::report_fatal_error(), llvm::object::ObjectFile::section_begin(), llvm::object::ObjectFile::section_end(), SI, and llvm::toString().
computeTotalAllocSize()
Error llvm::RuntimeDyldImpl::computeTotalAllocSize (const ObjectFile & Obj, uint64_t & CodeSize, uint32_t & CodeAlign, uint64_t & RODataSize, uint32_t & RODataAlign, uint64_t & RWDataSize, uint32_t & RWDataAlign) protected
Definition at line 536 of file RuntimeDyld.cpp.
References Align, llvm::alignTo(), llvm::computeAllocationSizeForSections(), E, I, llvm::isReadOnlyData(), llvm::isRequiredForExecution(), llvm::isTLS(), Name, llvm::object::ObjectFile::section_begin(), llvm::object::ObjectFile::section_end(), SI, Size, llvm::Error::success(), llvm::object::SymbolicFile::symbol_begin(), and llvm::object::SymbolicFile::symbol_end().
createStubFunction()
uint8_t * llvm::RuntimeDyldImpl::createStubFunction (uint8_t * Addr, unsigned AbiVariant = 0) protected
Emits long jump instruction to Addr.
Returns
Pointer to the memory area for emitting target address.
Definition at line 976 of file RuntimeDyld.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_32, llvm::Triple::aarch64_be, Addr, llvm::Triple::arm, llvm::Triple::armeb, llvm::ELF::EF_MIPS_ARCH, llvm::ELF::EF_MIPS_ARCH_32R6, llvm::ELF::EF_MIPS_ARCH_64R6, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::Triple::systemz, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by llvm::RuntimeDyldCOFFAArch64::generateRelocationStub(), llvm::RuntimeDyldCOFFX86_64::generateRelocationStub(), and llvm::RuntimeDyldELF::processRelocationRef().
deregisterEHFrames()
void llvm::RuntimeDyldImpl::deregisterEHFrames ()
Definition at line 78 of file RuntimeDyld.cpp.
emitCommonSymbols()
Error llvm::RuntimeDyldImpl::emitCommonSymbols (const ObjectFile & Obj, CommonSymbolList & CommonSymbols, uint64_t CommonSize, uint32_t CommonAlign) protected
Given the common symbols discovered in the object file, emit a new section for them and update the symbol mappings in the object and symbol table.
Definition at line 746 of file RuntimeDyld.cpp.
References Addr, Align, llvm::dbgs(), llvm::format(), LLVM_DEBUG, Name, Offset, llvm::offsetToAlignment(), llvm::report_fatal_error(), Size, and llvm::Error::success().
emitSection()
Expected< unsigned > llvm::RuntimeDyldImpl::emitSection (const ObjectFile & Obj, const SectionRef & Section, bool IsCode) protected
Emits section data from the object file to the MemoryManager.
Parameters
IsCode if it's true then allocateCodeSection() will be used for emits, else allocateDataSection() will be used.
Returns
SectionID.
Definition at line 802 of file RuntimeDyld.cpp.
References Addr, llvm::StringRef::data(), llvm::dbgs(), E, llvm::format(), llvm::isReadOnlyData(), llvm::isRequiredForExecution(), llvm::isTLS(), llvm::isZeroInit(), LLVM_DEBUG, Name, and llvm::report_fatal_error().
finalizeAsync()
void llvm::RuntimeDyldImpl::finalizeAsync (std::unique_ptr< RuntimeDyldImpl > This, unique_function< void(object::OwningBinary< object::ObjectFile >, std::unique_ptr< RuntimeDyld::LoadedObjectInfo >, Error)> OnEmitted, object::OwningBinary< object::ObjectFile > O, std::unique_ptr< RuntimeDyld::LoadedObjectInfo > Info) static
Copy the result into a StringMap, where the keys are held by value.
Definition at line 1223 of file RuntimeDyld.cpp.
References assert(), llvm::inconvertibleErrorCode(), Name, and llvm::Error::success().
Referenced by llvm::jitLinkForORC().
finalizeLoad()
virtual Error llvm::RuntimeDyldImpl::finalizeLoad (const ObjectFile & ObjImg, ObjSectionToIDMap & SectionMap) inline virtual
Reimplemented in llvm::RuntimeDyldCOFFX86_64, llvm::RuntimeDyldELF, llvm::RuntimeDyldMachOCRTPBase< Impl >, llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOAArch64 >, llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOARM >, llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOI386 >, and llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOX86_64 >.
Definition at line 576 of file RuntimeDyldImpl.h.
References llvm::Error::success().
findOrEmitSection()
Expected< unsigned > llvm::RuntimeDyldImpl::findOrEmitSection (const ObjectFile & Obj, const SectionRef & Section, bool IsCode, ObjSectionToIDMap & LocalSections) protected
Find Section in LocalSections.
If the secton is not found - emit it and store in LocalSections.
Parameters
IsCode if it's true then allocateCodeSection() will be used for emmits, else allocateDataSection() will be used.
Returns
SectionID.
Definition at line 933 of file RuntimeDyld.cpp.
Referenced by llvm::RuntimeDyldMachO::getRelocationValueRef(), llvm::RuntimeDyldCOFFAArch64::processRelocationRef(), llvm::RuntimeDyldCOFFI386::processRelocationRef(), llvm::RuntimeDyldCOFFThumb::processRelocationRef(), llvm::RuntimeDyldCOFFX86_64::processRelocationRef(), llvm::RuntimeDyldELF::processRelocationRef(), and llvm::RuntimeDyldMachO::processScatteredVANILLA().
getErrorString()
StringRef llvm::RuntimeDyldImpl::getErrorString () inline
Definition at line 564 of file RuntimeDyldImpl.h.
References ErrorStr.
getGOTEntrySize()
virtual size_t llvm::RuntimeDyldImpl::getGOTEntrySize () inline protected virtual
Reimplemented in llvm::RuntimeDyldELF.
Definition at line 436 of file RuntimeDyldImpl.h.
getJITSymbolFlags()
Expected< JITSymbolFlags > llvm::RuntimeDyldImpl::getJITSymbolFlags (const SymbolRef & Sym) protected virtual
Generate JITSymbolFlags from a libObject symbol.
Reimplemented in llvm::RuntimeDyldMachOARM.
Definition at line 742 of file RuntimeDyld.cpp.
References llvm::JITSymbolFlags::fromObjectSymbol().
Referenced by llvm::RuntimeDyldMachOARM::getJITSymbolFlags().
getMaxStubSize()
virtual unsigned llvm::RuntimeDyldImpl::getMaxStubSize () const protected pure virtual
Implemented in llvm::RuntimeDyldCOFFAArch64, llvm::RuntimeDyldCOFFI386, llvm::RuntimeDyldCOFFThumb, llvm::RuntimeDyldCOFFX86_64, llvm::RuntimeDyldMachOAArch64, llvm::RuntimeDyldMachOARM, llvm::RuntimeDyldMachOI386, and llvm::RuntimeDyldMachOX86_64.
Referenced by getSectionContent().
getSectionAddress()
uint8_t * llvm::RuntimeDyldImpl::getSectionAddress (unsigned SectionID) const inline
Definition at line 471 of file RuntimeDyldImpl.h.
References AbsoluteSymbolSection, and Sections.
Referenced by getSymbolLocalAddress().
getSectionContent()
StringRef llvm::RuntimeDyldImpl::getSectionContent (unsigned SectionID) const inline
Definition at line 478 of file RuntimeDyldImpl.h.
References AbsoluteSymbolSection, getMaxStubSize(), and Sections.
getSectionLoadAddress()
uint64_t llvm::RuntimeDyldImpl::getSectionLoadAddress (unsigned SectionID) const inline
Definition at line 464 of file RuntimeDyldImpl.h.
References AbsoluteSymbolSection, and Sections.
Referenced by getSymbol(), and getSymbolTable().
getStubAlignment()
virtual unsigned llvm::RuntimeDyldImpl::getStubAlignment () protected pure virtual
Implemented in llvm::RuntimeDyldCOFFAArch64, llvm::RuntimeDyldCOFFI386, llvm::RuntimeDyldCOFFThumb, llvm::RuntimeDyldCOFFX86_64, llvm::RuntimeDyldMachOAArch64, llvm::RuntimeDyldMachOARM, llvm::RuntimeDyldMachOI386, and llvm::RuntimeDyldMachOX86_64.
getSymbol()
JITEvaluatedSymbol llvm::RuntimeDyldImpl::getSymbol (StringRef Name) const inline
Definition at line 507 of file RuntimeDyldImpl.h.
References AbsoluteSymbolSection, llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), getSectionLoadAddress(), GlobalSymbolTable, modifyAddressBasedOnFlags(), and Name.
getSymbolLocalAddress()
uint8_t * llvm::RuntimeDyldImpl::getSymbolLocalAddress (StringRef Name) const inline
Definition at line 487 of file RuntimeDyldImpl.h.
References AbsoluteSymbolSection, llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), getSectionAddress(), GlobalSymbolTable, and Name.
getSymbolSectionID()
unsigned llvm::RuntimeDyldImpl::getSymbolSectionID (StringRef Name) const inline
Definition at line 500 of file RuntimeDyldImpl.h.
References llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), GlobalSymbolTable, and Name.
getSymbolTable()
std::map< StringRef, JITEvaluatedSymbol > llvm::RuntimeDyldImpl::getSymbolTable () const inline
Definition at line 527 of file RuntimeDyldImpl.h.
References getSectionLoadAddress(), and GlobalSymbolTable.
hasError()
bool llvm::RuntimeDyldImpl::hasError () inline
Definition at line 558 of file RuntimeDyldImpl.h.
References HasError.
isCompatibleFile()
virtual bool llvm::RuntimeDyldImpl::isCompatibleFile (const ObjectFile & Obj) const pure virtual
Implemented in llvm::RuntimeDyldCOFF, llvm::RuntimeDyldELF, and llvm::RuntimeDyldMachO.
loadObject()
virtual std::unique_ptr< RuntimeDyld::LoadedObjectInfo > llvm::RuntimeDyldImpl::loadObject (const object::ObjectFile & Obj) pure virtual
Implemented in llvm::RuntimeDyldELF, llvm::RuntimeDyldMachO, and llvm::RuntimeDyldCOFF.
loadObjectImpl()
Expected< RuntimeDyldImpl::ObjSectionToIDMap > llvm::RuntimeDyldImpl::loadObjectImpl (const object::ObjectFile & Obj) protected
Definition at line 184 of file RuntimeDyld.cpp.
References Addr, Align, llvm::alignTo(), llvm::dbgs(), E, llvm::format(), llvm::object::ObjectFile::getArch(), llvm::object::Binary::getFileName(), llvm::getOffset(), I, llvm::object::Binary::isLittleEndian(), LLVM_DEBUG, Name, llvm::object::ObjectFile::section_begin(), llvm::object::ObjectFile::section_end(), SI, Size, llvm::object::SymbolRef::ST_Data, llvm::object::SymbolRef::ST_File, llvm::object::SymbolRef::ST_Function, llvm::object::SymbolRef::ST_Other, llvm::object::SymbolRef::ST_Unknown, llvm::object::SymbolicFile::symbol_begin(), llvm::object::SymbolicFile::symbol_end(), and llvm::object::ObjectFile::symbols().
Referenced by llvm::RuntimeDyldELF::loadObject(), llvm::RuntimeDyldMachO::loadObject(), and llvm::RuntimeDyldCOFF::loadObject().
mapSectionAddress()
void llvm::RuntimeDyldImpl::mapSectionAddress (const void * LocalAddress, uint64_t TargetAddress)
Definition at line 162 of file RuntimeDyld.cpp.
References llvm_unreachable.
modifyAddressBasedOnFlags()
virtual uint64_t llvm::RuntimeDyldImpl::modifyAddressBasedOnFlags (uint64_t Addr, JITSymbolFlags Flags) const inline protected virtual
Modify the given target address based on the given symbol flags.
This can be used by subclasses to tweak addresses based on symbol flags, For example: the MachO/ARM target uses it to set the low bit if the target is a thumb symbol.
Reimplemented in llvm::RuntimeDyldMachOARM.
Definition at line 355 of file RuntimeDyldImpl.h.
References Addr.
Referenced by getSymbol().
processRelocationRef()
virtual Expected< relocation_iterator > llvm::RuntimeDyldImpl::processRelocationRef (unsigned SectionID, relocation_iterator RelI, const ObjectFile & Obj, ObjSectionToIDMap & ObjSectionToID, StubMap & Stubs) protected pure virtual
Parses one or more object file relocations (some object files use relocation pairs) and stores it to Relocations or SymbolRelocations (this depends on the object file type).
Returns
Iterator to the next relocation that needs to be parsed.
Implemented in llvm::RuntimeDyldCOFFAArch64, llvm::RuntimeDyldCOFFI386, llvm::RuntimeDyldCOFFThumb, llvm::RuntimeDyldCOFFX86_64, llvm::RuntimeDyldMachOAArch64, llvm::RuntimeDyldMachOARM, llvm::RuntimeDyldMachOI386, llvm::RuntimeDyldMachOX86_64, and llvm::RuntimeDyldELF.
readBytesUnaligned()
uint64_t llvm::RuntimeDyldImpl::readBytesUnaligned (uint8_t * Src, unsigned Size) const protected
Endian-aware read Read the least significant Size bytes from Src.
Definition at line 711 of file RuntimeDyld.cpp.
References Size.
Referenced by llvm::RuntimeDyldMachOARM::decodeAddend(), llvm::RuntimeDyldMachO::memcpyAddend(), llvm::RuntimeDyldCOFFI386::processRelocationRef(), llvm::RuntimeDyldCOFFThumb::processRelocationRef(), llvm::RuntimeDyldCOFFX86_64::processRelocationRef(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::RuntimeDyldMachO::processScatteredVANILLA(), and llvm::RuntimeDyldMachOARM::resolveRelocation().
reassignSectionAddress()
void llvm::RuntimeDyldImpl::reassignSectionAddress (unsigned SectionID, uint64_t Addr)
Definition at line 1084 of file RuntimeDyld.cpp.
References Addr, llvm::dbgs(), llvm::format(), getName(), and LLVM_DEBUG.
registerEHFrames()
void llvm::RuntimeDyldImpl::registerEHFrames () virtual
Reimplemented in llvm::RuntimeDyldELF, llvm::RuntimeDyldMachOCRTPBase< Impl >, llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOAArch64 >, llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOARM >, llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOI386 >, llvm::RuntimeDyldMachOCRTPBase< RuntimeDyldMachOX86_64 >, llvm::RuntimeDyldCOFFAArch64, llvm::RuntimeDyldCOFFI386, llvm::RuntimeDyldCOFFThumb, and llvm::RuntimeDyldCOFFX86_64.
Definition at line 76 of file RuntimeDyld.cpp.
relocationNeedsGot()
virtual bool llvm::RuntimeDyldImpl::relocationNeedsGot (const RelocationRef & R) const inline protected virtual
Definition at line 439 of file RuntimeDyldImpl.h.
relocationNeedsStub()
virtual bool llvm::RuntimeDyldImpl::relocationNeedsStub (const RelocationRef & R) const inline protected virtual
Definition at line 444 of file RuntimeDyldImpl.h.
resolveExternalSymbols()
Error llvm::RuntimeDyldImpl::resolveExternalSymbols () protected
Resolve relocations to external symbols.
Definition at line 1167 of file RuntimeDyld.cpp.
References assert(), Name, and llvm::Error::success().
resolveLocalRelocations()
void llvm::RuntimeDyldImpl::resolveLocalRelocations ()
Definition at line 147 of file RuntimeDyld.cpp.
References Addr, llvm::dbgs(), llvm::format(), Idx, and LLVM_DEBUG.
resolveRelocation()
virtual void llvm::RuntimeDyldImpl::resolveRelocation (const RelocationEntry & RE, uint64_t Value) protected pure virtual
A object file specific relocation resolver.
Parameters
RE The relocation to be resolved
Value Target symbol address to apply the relocation action
Implemented in llvm::RuntimeDyldELF, llvm::RuntimeDyldCOFFAArch64, llvm::RuntimeDyldCOFFI386, llvm::RuntimeDyldCOFFThumb, llvm::RuntimeDyldCOFFX86_64, llvm::RuntimeDyldELFMips, llvm::RuntimeDyldMachOAArch64, llvm::RuntimeDyldMachOARM, llvm::RuntimeDyldMachOI386, and llvm::RuntimeDyldMachOX86_64.
resolveRelocationList()
void llvm::RuntimeDyldImpl::resolveRelocationList (const RelocationList & Relocs, uint64_t Value) protected
Resolves relocations from Relocs list with address from Value.
Definition at line 1104 of file RuntimeDyld.cpp.
References llvm::object::resolveRelocation(), and llvm::SmallVectorBase< Size_T >::size().
resolveRelocations()
void llvm::RuntimeDyldImpl::resolveRelocations ()
Definition at line 123 of file RuntimeDyld.cpp.
References llvm::dumpSectionMemory(), LLVM_DEBUG, and llvm::toString().
setMipsABI()
virtual void llvm::RuntimeDyldImpl::setMipsABI (const ObjectFile & Obj) inline protected virtual
Definition at line 335 of file RuntimeDyldImpl.h.
References IsMipsN32ABI, IsMipsN64ABI, and IsMipsO32ABI.
setNotifyStubEmitted()
void llvm::RuntimeDyldImpl::setNotifyStubEmitted (NotifyStubEmittedFunction NotifyStubEmitted) inline
Definition at line 568 of file RuntimeDyldImpl.h.
References NotifyStubEmitted.
setProcessAllSections()
void llvm::RuntimeDyldImpl::setProcessAllSections (bool ProcessAllSections) inline
Definition at line 457 of file RuntimeDyldImpl.h.
References ProcessAllSections.
writeBytesUnaligned()
void llvm::RuntimeDyldImpl::writeBytesUnaligned (uint64_t Value, uint8_t * Dst, unsigned Size) const protected
Endian-aware write.
Write the least significant Size bytes from Value to Dst.
Definition at line 725 of file RuntimeDyld.cpp.
References Size.
Referenced by llvm::RuntimeDyldCOFFI386::resolveRelocation(), llvm::RuntimeDyldCOFFThumb::resolveRelocation(), llvm::RuntimeDyldCOFFX86_64::resolveRelocation(), llvm::RuntimeDyldMachOAArch64::resolveRelocation(), llvm::RuntimeDyldMachOARM::resolveRelocation(), llvm::RuntimeDyldMachOI386::resolveRelocation(), and llvm::RuntimeDyldMachOX86_64::resolveRelocation().
writeInt16BE()
void llvm::RuntimeDyldImpl::writeInt16BE (uint8_t * Addr, uint16_t Value) inline protected
Definition at line 320 of file RuntimeDyldImpl.h.
References Addr, llvm::support::big, IsTargetLittleEndian, and llvm::support::little.
writeInt32BE()
void llvm::RuntimeDyldImpl::writeInt32BE (uint8_t * Addr, uint32_t Value) inline protected
Definition at line 325 of file RuntimeDyldImpl.h.
References Addr, llvm::support::big, IsTargetLittleEndian, and llvm::support::little.
Referenced by llvm::RuntimeDyldELF::processRelocationRef().
writeInt64BE()
void llvm::RuntimeDyldImpl::writeInt64BE (uint8_t * Addr, uint64_t Value) inline protected
Definition at line 330 of file RuntimeDyldImpl.h.
References Addr, llvm::support::big, IsTargetLittleEndian, and llvm::support::little.
Friends And Related Symbol Documentation
RuntimeDyld::LoadedObjectInfo
friend class RuntimeDyld::LoadedObjectInfo friend
Definition at line 239 of file RuntimeDyldImpl.h.
Member Data Documentation
AbsoluteSymbolSection
const unsigned llvm::RuntimeDyldImpl::AbsoluteSymbolSection = ~0U static protected
Definition at line 241 of file RuntimeDyldImpl.h.
Referenced by getSectionAddress(), getSectionContent(), getSectionLoadAddress(), getSymbol(), and getSymbolLocalAddress().
Arch
Triple::ArchType llvm::RuntimeDyldImpl::Arch protected
Definition at line 288 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldCOFF::create(), llvm::RuntimeDyldELF::create(), llvm::RuntimeDyldMachO::create(), llvm::RuntimeDyldELF::getGOTEntrySize(), and llvm::RuntimeDyldELF::processRelocationRef().
ErrorStr
std::string llvm::RuntimeDyldImpl::ErrorStr protected
Definition at line 318 of file RuntimeDyldImpl.h.
Referenced by getErrorString(), llvm::RuntimeDyldELF::loadObject(), llvm::RuntimeDyldMachO::loadObject(), and llvm::RuntimeDyldCOFF::loadObject().
ExternalSymbolRelocations
StringMap<RelocationList> llvm::RuntimeDyldImpl::ExternalSymbolRelocations protected
Definition at line 283 of file RuntimeDyldImpl.h.
GlobalSymbolTable
RTDyldSymbolTable llvm::RuntimeDyldImpl::GlobalSymbolTable protected
Definition at line 264 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldMachO::getRelocationValueRef(), getSymbol(), getSymbolLocalAddress(), getSymbolSectionID(), getSymbolTable(), llvm::RuntimeDyldMachOARM::isAddrTargetThumb(), llvm::RuntimeDyldMachOARM::processRelocationRef(), and llvm::RuntimeDyldELF::processRelocationRef().
HasError
bool llvm::RuntimeDyldImpl::HasError protected
Definition at line 317 of file RuntimeDyldImpl.h.
Referenced by clearError(), hasError(), llvm::RuntimeDyldELF::loadObject(), llvm::RuntimeDyldMachO::loadObject(), and llvm::RuntimeDyldCOFF::loadObject().
IsMipsN32ABI
bool llvm::RuntimeDyldImpl::IsMipsN32ABI protected
Definition at line 291 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldELF::finalizeLoad(), llvm::RuntimeDyldELF::getGOTEntrySize(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::RuntimeDyldELFMips::resolveRelocation(), and setMipsABI().
IsMipsN64ABI
bool llvm::RuntimeDyldImpl::IsMipsN64ABI protected
Definition at line 292 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldELF::finalizeLoad(), llvm::RuntimeDyldELF::getGOTEntrySize(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::RuntimeDyldELFMips::resolveRelocation(), and setMipsABI().
IsMipsO32ABI
bool llvm::RuntimeDyldImpl::IsMipsO32ABI protected
Definition at line 290 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldELF::finalizeLoad(), llvm::RuntimeDyldELF::getGOTEntrySize(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::RuntimeDyldELFMips::resolveRelocation(), and setMipsABI().
IsTargetLittleEndian
bool llvm::RuntimeDyldImpl::IsTargetLittleEndian protected
Definition at line 289 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldELF::processRelocationRef(), writeInt16BE(), writeInt32BE(), and writeInt64BE().
lock
sys::Mutex llvm::RuntimeDyldImpl::lock protected
Definition at line 308 of file RuntimeDyldImpl.h.
MemMgr
RuntimeDyld::MemoryManager& llvm::RuntimeDyldImpl::MemMgr protected
Definition at line 244 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldCOFF::create(), llvm::RuntimeDyldELF::create(), llvm::RuntimeDyldMachO::create(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::RuntimeDyldELF::registerEHFrames(), and llvm::RuntimeDyldCOFFX86_64::registerEHFrames().
NotifyStubEmitted
NotifyStubEmittedFunction llvm::RuntimeDyldImpl::NotifyStubEmitted protected
Definition at line 312 of file RuntimeDyldImpl.h.
Referenced by setNotifyStubEmitted().
ProcessAllSections
bool llvm::RuntimeDyldImpl::ProcessAllSections protected
Definition at line 296 of file RuntimeDyldImpl.h.
Referenced by setProcessAllSections().
Relocations
std::unordered_map<unsigned, RelocationList> llvm::RuntimeDyldImpl::Relocations protected
Definition at line 278 of file RuntimeDyldImpl.h.
Resolver
JITSymbolResolver& llvm::RuntimeDyldImpl::Resolver protected
Definition at line 247 of file RuntimeDyldImpl.h.
Sections
SectionList llvm::RuntimeDyldImpl::Sections protected
Definition at line 254 of file RuntimeDyldImpl.h.
Referenced by llvm::RuntimeDyldMachOAArch64::decodeAddend(), llvm::RuntimeDyldMachOARM::decodeAddend(), llvm::RuntimeDyldMachO::dumpRelocationToResolve(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::RuntimeDyldCOFFAArch64::generateRelocationStub(), llvm::RuntimeDyldCOFFX86_64::generateRelocationStub(), llvm::RuntimeDyldCOFF::getDLLImportOffset(), llvm::RuntimeDyldMachO::getSection(), getSectionAddress(), getSectionContent(), getSectionLoadAddress(), llvm::RuntimeDyldMachOARM::isAddrTargetThumb(), llvm::RuntimeDyldMachO::memcpyAddend(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), llvm::RuntimeDyldCOFFAArch64::processRelocationRef(), llvm::RuntimeDyldCOFFI386::processRelocationRef(), llvm::RuntimeDyldCOFFThumb::processRelocationRef(), llvm::RuntimeDyldCOFFX86_64::processRelocationRef(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::RuntimeDyldMachO::processScatteredVANILLA(), llvm::RuntimeDyldELF::registerEHFrames(), llvm::RuntimeDyldCOFFX86_64::registerEHFrames(), llvm::RuntimeDyldELF::resolveRelocation(), llvm::RuntimeDyldCOFFAArch64::resolveRelocation(), llvm::RuntimeDyldCOFFI386::resolveRelocation(), llvm::RuntimeDyldCOFFThumb::resolveRelocation(), llvm::RuntimeDyldCOFFX86_64::resolveRelocation(), llvm::RuntimeDyldELFMips::resolveRelocation(), llvm::RuntimeDyldMachOAArch64::resolveRelocation(), llvm::RuntimeDyldMachOARM::resolveRelocation(), llvm::RuntimeDyldMachOI386::resolveRelocation(), and llvm::RuntimeDyldMachOX86_64::resolveRelocation().
The documentation for this class was generated from the following files:
lib/ExecutionEngine/RuntimeDyld/RuntimeDyldImpl.h
lib/ExecutionEngine/RuntimeDyld/RuntimeDyld.cpp