LLVM: llvm::DeadArgumentEliminationPass Class Reference
llvm::DeadArgumentEliminationPass Class Reference
Eliminate dead arguments (and return values) from functions.
#include "llvm/Transforms/IPO/DeadArgumentElimination.h"
Classes
struct RetOrArg
Struct that represents (part of) either a return value or a function argument.
Public Types
enum Liveness { Live , MaybeLive }
Liveness enum - During our initial pass over the program, we determine that things are either alive or maybe alive.
using UseMap = std::multimap<RetOrArg, RetOrArg>
using LiveSet = std::set<RetOrArg>
using LiveFuncSet = std::set<const Function *>
using UseVector = SmallVector<RetOrArg, 5>
Public Member Functions
DeadArgumentEliminationPass (bool ShouldHackArguments_=false)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &)
RetOrArg CreateRet (const Function *F, unsigned Idx)
Convenience wrapper.
RetOrArg CreateArg (const Function *F, unsigned Idx)
Convenience wrapper.
Public Member Functions inherited from llvm::PassInfoMixin< DeadArgumentEliminationPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Attributes
UseMap Uses
This maps a return value or argument to any MaybeLive return values or arguments it uses.
LiveSet LiveValues
This set contains all values that have been determined to be live.
LiveFuncSet LiveFunctions
This set contains all values that are cannot be changed in any way.
bool ShouldHackArguments = false
This allows this pass to do double-duty as the dead arg hacking pass (used only by bugpoint).
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< DeadArgumentEliminationPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Eliminate dead arguments (and return values) from functions.
Definition at line 38 of file DeadArgumentElimination.h.
Member Typedef Documentation
LiveFuncSet
using llvm::DeadArgumentEliminationPass::LiveFuncSet = std::set<const Function *>
Definition at line 110 of file DeadArgumentElimination.h.
LiveSet
using llvm::DeadArgumentEliminationPass::LiveSet = std::set<RetOrArg>
Definition at line 109 of file DeadArgumentElimination.h.
UseMap
using llvm::DeadArgumentEliminationPass::UseMap = std::multimap<RetOrArg, RetOrArg>
Definition at line 91 of file DeadArgumentElimination.h.
UseVector
using llvm::DeadArgumentEliminationPass::UseVector = SmallVector<RetOrArg, 5>
Definition at line 118 of file DeadArgumentElimination.h.
Member Enumeration Documentation
Liveness
enum llvm::DeadArgumentEliminationPass::Liveness
Liveness enum - During our initial pass over the program, we determine that things are either alive or maybe alive.
We don't mark anything explicitly dead (even if we know they are), since anything not alive with no registered uses (in Uses) will never be marked alive and will thus become dead in the end.
Enumerator
Live
MaybeLive
Definition at line 74 of file DeadArgumentElimination.h.
Constructor & Destructor Documentation
DeadArgumentEliminationPass()
llvm::DeadArgumentEliminationPass::DeadArgumentEliminationPass (bool ShouldHackArguments_ = false) inline
Definition at line 76 of file DeadArgumentElimination.h.
Member Function Documentation
CreateArg()
RetOrArg llvm::DeadArgumentEliminationPass::CreateArg (const Function * F, unsigned Idx) inline
Convenience wrapper.
Definition at line 87 of file DeadArgumentElimination.h.
References F, and Idx.
Referenced by values().
CreateRet()
RetOrArg llvm::DeadArgumentEliminationPass::CreateRet (const Function * F, unsigned Idx) inline
Convenience wrapper.
Definition at line 82 of file DeadArgumentElimination.h.
References F, and Idx.
Referenced by values().
run()
PreservedAnalyses DeadArgumentEliminationPass::run (Module & M, ModuleAnalysisManager &)
Definition at line 1089 of file DeadArgumentElimination.cpp.
References llvm::PreservedAnalyses::all(), Changed, llvm::dbgs(), F, LLVM_DEBUG, llvm::make_early_inc_range(), and llvm::PreservedAnalyses::none().
Member Data Documentation
LiveFunctions
LiveFuncSet llvm::DeadArgumentEliminationPass::LiveFunctions
This set contains all values that are cannot be changed in any way.
Definition at line 116 of file DeadArgumentElimination.h.
Referenced by values().
LiveValues
LiveSet llvm::DeadArgumentEliminationPass::LiveValues
This set contains all values that have been determined to be live.
Definition at line 113 of file DeadArgumentElimination.h.
Referenced by value().
ShouldHackArguments
bool llvm::DeadArgumentEliminationPass::ShouldHackArguments = false
This allows this pass to do double-duty as the dead arg hacking pass (used only by bugpoint).
Definition at line 122 of file DeadArgumentElimination.h.
Uses
UseMap llvm::DeadArgumentEliminationPass::Uses
This maps a return value or argument to any MaybeLive return values or arguments it uses.
This allows the MaybeLive values to be marked live when any of its users is marked live. For example (indices are left out for clarity):
Uses[ret F] = ret G This means that F calls G, and F returns the value returned by G.
Uses[arg F] = ret G This means that some function calls G and passes its result as an argument to F.
Uses[ret F] = arg F This means that F returns one of its own arguments.
Uses[arg F] = arg G This means that G calls F and passes one of its own (G's) arguments directly to F.
Definition at line 107 of file DeadArgumentElimination.h.
Referenced by uses().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/DeadArgumentElimination.h
lib/Transforms/IPO/DeadArgumentElimination.cpp