LLVM: llvm::PriorityInlineOrder< PriorityT > Class Template Reference
llvm::PriorityInlineOrder< PriorityT > Class Template Reference
#include "llvm/Analysis/InlineOrder.h"
Public Member Functions
size_t size () override
void push (const T &Elt) override
T pop () override
const_reference front () override
void erase_if (function_ref< bool(T)> Pred) override
Public Member Functions inherited from llvm::InlineOrder< std::pair< CallBase *, int > >
virtual ~InlineOrder ()=default
virtual void push (const std::pair< CallBase *, int > &Elt)=0
virtual void erase_if (function_ref< bool(std::pair< CallBase *, int >)> Pred)=0
bool empty ()
Additional Inherited Members
Public Types inherited from llvm::InlineOrder< std::pair< CallBase *, int > >
using reference
using const_reference
Detailed Description
template<typename PriorityT>
class llvm::PriorityInlineOrder< PriorityT >
Definition at line 92 of file InlineOrder.h.
Member Function Documentation
erase_if()
template<typename PriorityT > void llvm::PriorityInlineOrder< PriorityT >::erase_if (function_ref< bool(T)> Pred) inline override
Definition at line 158 of file InlineOrder.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::erase_if(), and P.
front()
template<typename PriorityT > const_reference llvm::PriorityInlineOrder< PriorityT >::front () inline override virtual
Implements llvm::InlineOrder< std::pair< CallBase *, int > >.
Definition at line 150 of file InlineOrder.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::front(), and llvm::PriorityInlineOrder< PriorityT >::size().
pop()
template<typename PriorityT > T llvm::PriorityInlineOrder< PriorityT >::pop () inline override virtual
Implements llvm::InlineOrder< std::pair< CallBase *, int > >.
Definition at line 138 of file InlineOrder.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), and llvm::PriorityInlineOrder< PriorityT >::size().
push()
template<typename PriorityT > void llvm::PriorityInlineOrder< PriorityT >::push (const T & Elt) inline override
Definition at line 128 of file InlineOrder.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
size()
template<typename PriorityT > size_t llvm::PriorityInlineOrder< PriorityT >::size () inline override virtual
Implements llvm::InlineOrder< std::pair< CallBase *, int > >.
Definition at line 126 of file InlineOrder.h.
References llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::PriorityInlineOrder< PriorityT >::front(), and llvm::PriorityInlineOrder< PriorityT >::pop().
The documentation for this class was generated from the following file:
include/llvm/Analysis/InlineOrder.h