LLVM: llvm::AArch64Subtarget Class Reference
llvm::AArch64Subtarget Class Reference final
#include "Target/AArch64/AArch64Subtarget.h"
Public Types
enum ARMProcFamilyEnum : uint8_t {
Others , A64FX , AppleA7 , AppleA10 ,
AppleA11 , AppleA12 , AppleA13 , AppleA14 ,
Carmel , CortexA35 , CortexA53 , CortexA55 ,
CortexA510 , CortexA57 , CortexA65 , CortexA72 ,
CortexA73 , CortexA75 , CortexA76 , CortexA77 ,
CortexA78 , CortexA78C , CortexA710 , CortexR82 ,
CortexX1 , CortexX1C , CortexX2 , ExynosM3 ,
Falkor , Kryo , NeoverseE1 , NeoverseN1 ,
NeoverseN2 , Neoverse512TVB , NeoverseV1 , Saphira ,
ThunderX2T99 , ThunderX , ThunderXT81 , ThunderXT83 ,
ThunderXT88 , ThunderX3T110 , TSV110
}
Public Member Functions
AArch64Subtarget (const Triple &TT, const std::string &CPU, const std::string &TuneCPU, const std::string &FS, const TargetMachine &TM, bool LittleEndian, unsigned MinSVEVectorSizeInBitsOverride=0, unsigned MaxSVEVectorSizeInBitsOverride=0)
This constructor initializes the data members to match that of the specified triple.
const AArch64SelectionDAGInfo * getSelectionDAGInfo () const override
const AArch64FrameLowering * getFrameLowering () const override
const AArch64TargetLowering * getTargetLowering () const override
const AArch64InstrInfo * getInstrInfo () const override
const AArch64RegisterInfo * getRegisterInfo () const override
const CallLowering * getCallLowering () const override
const InlineAsmLowering * getInlineAsmLowering () const override
InstructionSelector * getInstructionSelector () const override
const LegalizerInfo * getLegalizerInfo () const override
const RegisterBankInfo * getRegBankInfo () const override
const Triple & getTargetTriple () const
bool enableMachineScheduler () const override
bool enablePostRAScheduler () const override
ARMProcFamilyEnum getProcFamily () const
Returns ARM processor family.
bool hasV8_0aOps () const
bool hasV8_1aOps () const
bool hasV8_2aOps () const
bool hasV8_3aOps () const
bool hasV8_4aOps () const
bool hasV8_5aOps () const
bool hasV9_0aOps () const
bool hasV9_1aOps () const
bool hasV9_2aOps () const
bool hasV9_3aOps () const
bool hasV8_0rOps () const
bool hasZeroCycleRegMove () const
bool hasZeroCycleZeroingGP () const
bool hasZeroCycleZeroingFP () const
bool hasZeroCycleZeroingFPWorkaround () const
bool requiresStrictAlign () const
bool isXRaySupported () const override
unsigned getMinVectorRegisterBitWidth () const
bool isXRegisterReserved (size_t i) const
unsigned getNumXRegisterReserved () const
bool isXRegCustomCalleeSaved (size_t i) const
bool hasCustomCallingConv () const
bool hasFPARMv8 () const
bool hasNEON () const
bool hasCrypto () const
bool hasDotProd () const
bool hasCRC () const
bool hasLSE () const
bool hasLSE2 () const
bool hasRAS () const
bool hasRDM () const
bool hasSM4 () const
bool hasSHA3 () const
bool hasSHA2 () const
bool hasAES () const
bool hasCONTEXTIDREL2 () const
bool balanceFPOps () const
bool predictableSelectIsExpensive () const
bool hasCustomCheapAsMoveHandling () const
bool hasExynosCheapAsMoveHandling () const
bool isMisaligned128StoreSlow () const
bool isPaired128Slow () const
bool isSTRQroSlow () const
bool useAlternateSExtLoadCVTF32Pattern () const
bool hasArithmeticBccFusion () const
bool hasArithmeticCbzFusion () const
bool hasCmpBccFusion () const
bool hasFuseAddress () const
bool hasFuseAES () const
bool hasFuseArithmeticLogic () const
bool hasFuseCCSelect () const
bool hasFuseCryptoEOR () const
bool hasFuseLiterals () const
bool hasFusion () const
Return true if the CPU supports any kind of instruction fusion.
bool hardenSlsRetBr () const
bool hardenSlsBlr () const
bool hardenSlsNoComdat () const
bool useEL1ForTP () const
bool useEL2ForTP () const
bool useEL3ForTP () const
bool useRSqrt () const
bool force32BitJumpTables () const
unsigned getMaxInterleaveFactor () const
unsigned getVectorInsertExtractBaseCost () const
unsigned getCacheLineSize () const override
unsigned getPrefetchDistance () const override
unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const override
unsigned getMaxPrefetchIterationsAhead () const override
unsigned getPrefFunctionLogAlignment () const
unsigned getPrefLoopLogAlignment () const
unsigned getMaxBytesForLoopAlignment () const
unsigned getMaximumJumpTableSize () const
unsigned getWideningBaseCost () const
bool useExperimentalZeroingPseudos () const
bool useScalarIncVL () const
bool supportsAddressTopByteIgnored () const
CPU has TBI (top byte of addresses is ignored during HW address translation) and OS enables it.
bool hasPerfMon () const
bool hasFullFP16 () const
bool hasFP16FML () const
bool hasSPE () const
bool hasLSLFast () const
bool hasSVE () const
bool hasSVE2 () const
bool hasRCPC () const
bool hasAggressiveFMA () const
bool hasAlternativeNZCV () const
bool hasFRInt3264 () const
bool hasSpecRestrict () const
bool hasSSBS () const
bool hasSB () const
bool hasPredRes () const
bool hasCCDP () const
bool hasBTI () const
bool hasRandGen () const
bool hasMTE () const
bool hasTME () const
bool hasSVE2AES () const
bool hasSVE2SM4 () const
bool hasSVE2SHA3 () const
bool hasSVE2BitPerm () const
bool hasMatMulInt8 () const
bool hasMatMulFP32 () const
bool hasMatMulFP64 () const
bool hasBF16 () const
bool hasFineGrainedTraps () const
bool hasEnhancedCounterVirtualization () const
bool hasSME () const
bool hasSMEF64 () const
bool hasSMEI64 () const
bool hasStreamingSVE () const
bool isLittleEndian () const
bool isTargetDarwin () const
bool isTargetIOS () const
bool isTargetLinux () const
bool isTargetWindows () const
bool isTargetAndroid () const
bool isTargetFuchsia () const
bool isTargetCOFF () const
bool isTargetELF () const
bool isTargetMachO () const
bool isTargetILP32 () const
bool useAA () const override
bool outlineAtomics () const
bool hasVH () const
bool hasPAN () const
bool hasLOR () const
bool hasPsUAO () const
bool hasPAN_RWV () const
bool hasCCPP () const
bool hasPAuth () const
bool hasJS () const
bool hasCCIDX () const
bool hasComplxNum () const
bool hasNV () const
bool hasMPAM () const
bool hasDIT () const
bool hasTRACEV8_4 () const
bool hasAM () const
bool hasAMVS () const
bool hasXS () const
bool hasWFxT () const
bool hasHCX () const
bool hasLS64 () const
bool hasSEL2 () const
bool hasTLB_RMI () const
bool hasFlagM () const
bool hasRCPC_IMMO () const
bool hasEL2VMSA () const
bool hasEL3 () const
bool hasHBC () const
bool hasMOPS () const
bool fixCortexA53_835769 () const
bool addrSinkUsingGEPs () const override
bool useSmallAddressing () const
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
unsigned ClassifyGlobalReference (const GlobalValue *GV, const TargetMachine &TM) const
ClassifyGlobalReference - Find the target operand flags that describe how a global value should be referenced for the current subtarget.
unsigned classifyGlobalFunctionReference (const GlobalValue *GV, const TargetMachine &TM) const
void overrideSchedPolicy (MachineSchedPolicy &Policy, unsigned NumRegionInstrs) const override
bool enableEarlyIfConversion () const override
bool enableAdvancedRASplitCost () const override
std::unique_ptr< PBQPRAConstraint > getCustomPBQPConstraints () const override
bool isCallingConvWin64 (CallingConv::ID CC) const
bool swiftAsyncContextIsDynamicallySet () const
Return whether FrameLowering should always set the "extended frame present" bit in FP, or set it based on a symbol in the runtime.
void mirFileLoaded (MachineFunction &MF) const override
unsigned getMaxSVEVectorSizeInBits () const
unsigned getMinSVEVectorSizeInBits () const
bool useSVEForFixedLengthVectors () const
unsigned getVScaleForTuning () const
Protected Attributes
ARMProcFamilyEnum ARMProcFamily = Others
ARMProcFamily - ARM processor family: Cortex-A53, Cortex-A57, and others.
bool HasV8_0aOps = false
bool HasV8_1aOps = false
bool HasV8_2aOps = false
bool HasV8_3aOps = false
bool HasV8_4aOps = false
bool HasV8_5aOps = false
bool HasV8_6aOps = false
bool HasV8_7aOps = false
bool HasV8_8aOps = false
bool HasV9_0aOps = false
bool HasV9_1aOps = false
bool HasV9_2aOps = false
bool HasV9_3aOps = false
bool HasV8_0rOps = false
bool HasCONTEXTIDREL2 = false
bool HasEL2VMSA = false
bool HasEL3 = false
bool HasFPARMv8 = false
bool HasNEON = false
bool HasCrypto = false
bool HasDotProd = false
bool HasCRC = false
bool HasLSE = false
bool HasLSE2 = false
bool HasRAS = false
bool HasRDM = false
bool HasPerfMon = false
bool HasFullFP16 = false
bool HasFP16FML = false
bool HasSPE = false
bool FixCortexA53_835769 = false
bool HasVH = false
bool HasPAN = false
bool HasLOR = false
bool HasPsUAO = false
bool HasPAN_RWV = false
bool HasCCPP = false
bool HasSVE = false
bool UseExperimentalZeroingPseudos = false
bool UseScalarIncVL = false
bool HasSM4 = false
bool HasSHA3 = false
bool HasSHA2 = false
bool HasAES = false
bool HasPAuth = false
bool HasJS = false
bool HasCCIDX = false
bool HasComplxNum = false
bool HasNV = false
bool HasMPAM = false
bool HasDIT = false
bool HasTRACEV8_4 = false
bool HasAM = false
bool HasSEL2 = false
bool HasTLB_RMI = false
bool HasFlagM = false
bool HasRCPC_IMMO = false
bool HasLSLFast = false
bool HasRCPC = false
bool HasAggressiveFMA = false
bool HasAlternativeNZCV = false
bool HasFRInt3264 = false
bool HasSpecRestrict = false
bool HasSSBS = false
bool HasSB = false
bool HasPredRes = false
bool HasCCDP = false
bool HasBTI = false
bool HasRandGen = false
bool HasMTE = false
bool HasTME = false
bool HasBF16 = false
bool HasMatMulInt8 = false
bool HasMatMulFP32 = false
bool HasMatMulFP64 = false
bool HasAMVS = false
bool HasFineGrainedTraps = false
bool HasEnhancedCounterVirtualization = false
bool HasXS = false
bool HasWFxT = false
bool HasHCX = false
bool HasLS64 = false
bool HasHBC = false
bool HasMOPS = false
bool HasSVE2 = false
bool HasSVE2AES = false
bool HasSVE2SM4 = false
bool HasSVE2SHA3 = false
bool HasSVE2BitPerm = false
bool HasRME = false
bool HasSME = false
bool HasSMEF64 = false
bool HasSMEI64 = false
bool HasStreamingSVE = false
bool HasAppleA7SysReg = false
bool HasETE = false
bool HasTRBE = false
bool HasBRBE = false
bool HasSPE_EEF = false
bool HasZeroCycleRegMove = false
bool HasZeroCycleZeroing = false
bool HasZeroCycleZeroingGP = false
bool HasZeroCycleZeroingFPWorkaround = false
bool HasZeroCycleZeroingFP = true
bool StrictAlign = false
bool NegativeImmediates = true
unsigned MinVectorRegisterBitWidth = 64
bool OutlineAtomics = false
bool PredictableSelectIsExpensive = false
bool BalanceFPOps = false
bool CustomAsCheapAsMove = false
bool ExynosAsCheapAsMove = false
bool UsePostRAScheduler = false
bool Misaligned128StoreIsSlow = false
bool Paired128IsSlow = false
bool STRQroIsSlow = false
bool UseAlternateSExtLoadCVTF32Pattern = false
bool HasArithmeticBccFusion = false
bool HasArithmeticCbzFusion = false
bool HasCmpBccFusion = false
bool HasFuseAddress = false
bool HasFuseAES = false
bool HasFuseArithmeticLogic = false
bool HasFuseCCSelect = false
bool HasFuseCryptoEOR = false
bool HasFuseLiterals = false
bool DisableLatencySchedHeuristic = false
bool UseRSqrt = false
bool Force32BitJumpTables = false
bool UseEL1ForTP = false
bool UseEL2ForTP = false
bool UseEL3ForTP = false
bool AllowTaggedGlobals = false
bool HardenSlsRetBr = false
bool HardenSlsBlr = false
bool HardenSlsNoComdat = false
uint8_t MaxInterleaveFactor = 2
uint8_t VectorInsertExtractBaseCost = 3
uint16_t CacheLineSize = 0
uint16_t PrefetchDistance = 0
uint16_t MinPrefetchStride = 1
unsigned MaxPrefetchIterationsAhead = UINT_MAX
unsigned PrefFunctionLogAlignment = 0
unsigned PrefLoopLogAlignment = 0
unsigned MaxBytesForLoopAlignment = 0
unsigned MaxJumpTableSize = 0
unsigned WideningBaseCost = 0
BitVector ReserveXRegister
BitVector CustomCallSavedXRegs
bool IsLittle
unsigned MinSVEVectorSizeInBits
unsigned MaxSVEVectorSizeInBits
unsigned VScaleForTuning = 2
Triple TargetTriple
TargetTriple - What processor and OS we're targeting.
AArch64FrameLowering FrameLowering
AArch64InstrInfo InstrInfo
AArch64SelectionDAGInfo TSInfo
AArch64TargetLowering TLInfo
std::unique_ptr< CallLowering > CallLoweringInfo
GlobalISel related APIs.
std::unique_ptr< InlineAsmLowering > InlineAsmLoweringInfo
std::unique_ptr< InstructionSelector > InstSelector
std::unique_ptr< LegalizerInfo > Legalizer
std::unique_ptr< RegisterBankInfo > RegBankInfo
Detailed Description
Definition at line 38 of file AArch64Subtarget.h.
Member Enumeration Documentation
ARMProcFamilyEnum
enum llvm::AArch64Subtarget::ARMProcFamilyEnum : uint8_t
Enumerator
Others
A64FX
AppleA7
AppleA10
AppleA11
AppleA12
AppleA13
AppleA14
Carmel
CortexA35
CortexA53
CortexA55
CortexA510
CortexA57
CortexA65
CortexA72
CortexA73
CortexA75
CortexA76
CortexA77
CortexA78
CortexA78C
CortexA710
CortexR82
CortexX1
CortexX1C
CortexX2
ExynosM3
Falkor
Kryo
NeoverseE1
NeoverseN1
NeoverseN2
Neoverse512TVB
NeoverseV1
Saphira
ThunderX2T99
ThunderX
ThunderXT81
ThunderXT83
ThunderXT88
ThunderX3T110
TSV110
Definition at line 40 of file AArch64Subtarget.h.
Constructor & Destructor Documentation
AArch64Subtarget()
AArch64Subtarget::AArch64Subtarget (const Triple & TT, const std::string & CPU, const std::string & TuneCPU, const std::string & FS, const TargetMachine & TM, bool LittleEndian, unsigned MinSVEVectorSizeInBitsOverride = 0, unsigned MaxSVEVectorSizeInBitsOverride = 0)
This constructor initializes the data members to match that of the specified triple.
Definition at line 227 of file AArch64Subtarget.cpp.
References CallLoweringInfo, llvm::createAArch64InstructionSelector(), getRegisterInfo(), getTargetLowering(), InlineAsmLoweringInfo, InstSelector, llvm::AArch64::isX18ReservedByDefault(), RegBankInfo, ReserveXRegister, llvm::BitVector::reset(), llvm::BitVector::set(), and TM.
Member Function Documentation
addrSinkUsingGEPs()
bool llvm::AArch64Subtarget::addrSinkUsingGEPs () const inline override
Definition at line 591 of file AArch64Subtarget.h.
References isTargetILP32(), and useAA().
balanceFPOps()
bool llvm::AArch64Subtarget::balanceFPOps () const inline
Definition at line 416 of file AArch64Subtarget.h.
References BalanceFPOps.
Referenced by getCustomPBQPConstraints().
classifyGlobalFunctionReference()
unsigned AArch64Subtarget::classifyGlobalFunctionReference (const GlobalValue * GV, const TargetMachine & TM) const
Definition at line 314 of file AArch64Subtarget.cpp.
References ClassifyGlobalReference(), F, llvm::GlobalValue::getParent(), getTargetTriple(), llvm::GlobalValue::hasInternalLinkage(), isTargetMachO(), llvm::CodeModel::Large, llvm::AArch64II::MO_GOT, llvm::AArch64II::MO_NO_FLAG, TM, and UseNonLazyBind.
ClassifyGlobalReference()
unsigned AArch64Subtarget::ClassifyGlobalReference (const GlobalValue * GV, const TargetMachine & TM) const
ClassifyGlobalReference - Find the target operand flags that describe how a global value should be referenced for the current subtarget.
Find the target operand flags that describe how a global value should be referenced for the current subtarget.
Definition at line 282 of file AArch64Subtarget.cpp.
References AllowTaggedGlobals, llvm::GlobalValue::getParent(), getTargetTriple(), llvm::GlobalValue::getValueType(), llvm::GlobalValue::hasDLLImportStorageClass(), llvm::GlobalValue::hasExternalWeakLinkage(), isTargetMachO(), llvm::CodeModel::Large, llvm::AArch64II::MO_COFFSTUB, llvm::AArch64II::MO_DLLIMPORT, llvm::AArch64II::MO_GOT, llvm::AArch64II::MO_NC, llvm::AArch64II::MO_NO_FLAG, llvm::AArch64II::MO_TAGGED, llvm::CodeModel::Tiny, TM, and useSmallAddressing().
Referenced by classifyGlobalFunctionReference(), llvm::AArch64InstrInfo::expandPostRAPseudo(), matchFoldGlobalOffset(), and performGlobalAddressCombine().
enableAdvancedRASplitCost()
bool llvm::AArch64Subtarget::enableAdvancedRASplitCost () const inline override
Definition at line 626 of file AArch64Subtarget.h.
enableEarlyIfConversion()
bool AArch64Subtarget::enableEarlyIfConversion () const override
Definition at line 347 of file AArch64Subtarget.cpp.
References EnableEarlyIfConvert.
enableMachineScheduler()
bool llvm::AArch64Subtarget::enableMachineScheduler () const inline override
Definition at line 353 of file AArch64Subtarget.h.
enablePostRAScheduler()
bool llvm::AArch64Subtarget::enablePostRAScheduler () const inline override
Definition at line 354 of file AArch64Subtarget.h.
References UsePostRAScheduler.
fixCortexA53_835769()
bool llvm::AArch64Subtarget::fixCortexA53_835769 () const inline
Definition at line 589 of file AArch64Subtarget.h.
References FixCortexA53_835769.
force32BitJumpTables()
bool llvm::AArch64Subtarget::force32BitJumpTables () const inline
Definition at line 454 of file AArch64Subtarget.h.
References Force32BitJumpTables.
getCacheLineSize()
unsigned llvm::AArch64Subtarget::getCacheLineSize () const inline override
Definition at line 459 of file AArch64Subtarget.h.
References CacheLineSize.
getCallLowering()
const CallLowering * AArch64Subtarget::getCallLowering () const override
Definition at line 259 of file AArch64Subtarget.cpp.
References CallLoweringInfo.
getCustomPBQPConstraints()
std::unique_ptr< PBQPRAConstraint > AArch64Subtarget::getCustomPBQPConstraints () const override
Definition at line 363 of file AArch64Subtarget.cpp.
References balanceFPOps().
getFrameLowering()
const AArch64FrameLowering * llvm::AArch64Subtarget::getFrameLowering () const inline override
Definition at line 337 of file AArch64Subtarget.h.
References FrameLowering.
getInlineAsmLowering()
const InlineAsmLowering * AArch64Subtarget::getInlineAsmLowering () const override
Definition at line 263 of file AArch64Subtarget.cpp.
References InlineAsmLoweringInfo.
getInstrInfo()
const AArch64InstrInfo * llvm::AArch64Subtarget::getInstrInfo () const inline override
Definition at line 343 of file AArch64Subtarget.h.
References InstrInfo.
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::AArch64FrameLowering::emitPrologue(), getRegisterInfo(), llvm::AArch64TargetLowering::insertCopiesSplitCSR(), InsertReturnAddressAuth(), llvm::AArch64CallLowering::lowerCall(), and signOutlinedFunction().
getInstructionSelector()
InstructionSelector * AArch64Subtarget::getInstructionSelector () const override
Definition at line 267 of file AArch64Subtarget.cpp.
References InstSelector.
getLegalizerInfo()
const LegalizerInfo * AArch64Subtarget::getLegalizerInfo () const override
Definition at line 271 of file AArch64Subtarget.cpp.
getMaxBytesForLoopAlignment()
unsigned llvm::AArch64Subtarget::getMaxBytesForLoopAlignment () const inline
Definition at line 475 of file AArch64Subtarget.h.
References MaxBytesForLoopAlignment.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering().
getMaximumJumpTableSize()
unsigned llvm::AArch64Subtarget::getMaximumJumpTableSize () const inline
Definition at line 479 of file AArch64Subtarget.h.
References MaxJumpTableSize.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering().
getMaxInterleaveFactor()
unsigned llvm::AArch64Subtarget::getMaxInterleaveFactor () const inline
Definition at line 455 of file AArch64Subtarget.h.
References MaxInterleaveFactor.
Referenced by llvm::AArch64TTIImpl::getMaxInterleaveFactor().
getMaxPrefetchIterationsAhead()
unsigned llvm::AArch64Subtarget::getMaxPrefetchIterationsAhead () const inline override
Definition at line 467 of file AArch64Subtarget.h.
References MaxPrefetchIterationsAhead.
getMaxSVEVectorSizeInBits()
unsigned llvm::AArch64Subtarget::getMaxSVEVectorSizeInBits () const inline
Definition at line 672 of file AArch64Subtarget.h.
References assert(), HasSVE, and MaxSVEVectorSizeInBits.
Referenced by llvm::AArch64TargetLowering::lowerInterleavedLoad(), and llvm::AArch64TargetLowering::lowerInterleavedStore().
getMinPrefetchStride()
unsigned llvm::AArch64Subtarget::getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const inline override
Definition at line 461 of file AArch64Subtarget.h.
References MinPrefetchStride.
getMinSVEVectorSizeInBits()
unsigned llvm::AArch64Subtarget::getMinSVEVectorSizeInBits () const inline
Definition at line 677 of file AArch64Subtarget.h.
References assert(), HasSVE, and MinSVEVectorSizeInBits.
Referenced by llvm::AArch64TargetLowering::getNumInterleavedAccesses(), llvm::AArch64TargetLowering::isLegalInterleavedAccessType(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), performFPExtendCombine(), performSTORECombine(), and useSVEForFixedLengthVectors().
getMinVectorRegisterBitWidth()
unsigned llvm::AArch64Subtarget::getMinVectorRegisterBitWidth () const inline
Definition at line 392 of file AArch64Subtarget.h.
References MinVectorRegisterBitWidth.
getNumXRegisterReserved()
unsigned llvm::AArch64Subtarget::getNumXRegisterReserved () const inline
Definition at line 397 of file AArch64Subtarget.h.
References llvm::BitVector::count(), and ReserveXRegister.
Referenced by llvm::AArch64RegisterInfo::getRegPressureLimit().
getPrefetchDistance()
unsigned llvm::AArch64Subtarget::getPrefetchDistance () const inline override
Definition at line 460 of file AArch64Subtarget.h.
References PrefetchDistance.
getPrefFunctionLogAlignment()
unsigned llvm::AArch64Subtarget::getPrefFunctionLogAlignment () const inline
Definition at line 470 of file AArch64Subtarget.h.
References PrefFunctionLogAlignment.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering().
getPrefLoopLogAlignment()
unsigned llvm::AArch64Subtarget::getPrefLoopLogAlignment () const inline
Definition at line 473 of file AArch64Subtarget.h.
References PrefLoopLogAlignment.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering().
getProcFamily()
ARMProcFamilyEnum llvm::AArch64Subtarget::getProcFamily () const inline
Returns ARM processor family.
Avoid this function! CPU specifics should be kept local to this class and preferably modeled with SubtargetFeatures or properties in initializeProperties().
Definition at line 362 of file AArch64Subtarget.h.
References ARMProcFamily.
Referenced by llvm::AArch64TargetLowering::getTargetMMOFlags(), and llvm::AArch64TTIImpl::getUnrollingPreferences().
getRegBankInfo()
const RegisterBankInfo * AArch64Subtarget::getRegBankInfo () const override
Definition at line 275 of file AArch64Subtarget.cpp.
References RegBankInfo.
Referenced by llvm::AArch64CallLowering::lowerCall().
getRegisterInfo()
const AArch64RegisterInfo * llvm::AArch64Subtarget::getRegisterInfo () const inline override
Definition at line 344 of file AArch64Subtarget.h.
References getInstrInfo(), and llvm::AArch64InstrInfo::getRegisterInfo().
Referenced by AArch64Subtarget(), llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AArch64FrameLowering::canUseAsPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::AArch64InstrInfo::expandPostRAPseudo(), findScratchNonCalleeSaveRegister(), llvm::AArch64TargetLowering::insertCopiesSplitCSR(), InsertSEH(), llvm::AArch64CallLowering::lowerCall(), and llvm::AArch64CallLowering::lowerFormalArguments().
getSelectionDAGInfo()
const AArch64SelectionDAGInfo * llvm::AArch64Subtarget::getSelectionDAGInfo () const inline override
Definition at line 334 of file AArch64Subtarget.h.
References TSInfo.
getTargetLowering()
const AArch64TargetLowering * llvm::AArch64Subtarget::getTargetLowering () const inline override
Definition at line 340 of file AArch64Subtarget.h.
References TLInfo.
Referenced by AArch64Subtarget(), llvm::AArch64FrameLowering::canUseRedZone(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset(), finishStackBlock(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCallPreservedMask(), llvm::AArch64RegisterInfo::getDarwinCalleeSavedRegs(), llvm::AArch64RegisterInfo::getDarwinCallPreservedMask(), and produceCompactUnwindFrame().
getTargetTriple()
const Triple & llvm::AArch64Subtarget::getTargetTriple () const inline
Definition at line 352 of file AArch64Subtarget.h.
References TargetTriple.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), classifyGlobalFunctionReference(), ClassifyGlobalReference(), llvm::AArch64TargetLowering::getSDagStackGuard(), llvm::AArch64TargetLowering::getSSPStackGuardCheck(), llvm::AArch64TargetLowering::insertSSPDeclarations(), and swiftAsyncContextIsDynamicallySet().
getVectorInsertExtractBaseCost()
unsigned llvm::AArch64Subtarget::getVectorInsertExtractBaseCost () const inline
Definition at line 456 of file AArch64Subtarget.h.
References VectorInsertExtractBaseCost.
Referenced by llvm::AArch64TTIImpl::getVectorInstrCost().
getVScaleForTuning()
unsigned llvm::AArch64Subtarget::getVScaleForTuning () const inline
Definition at line 687 of file AArch64Subtarget.h.
References VScaleForTuning.
getWideningBaseCost()
unsigned llvm::AArch64Subtarget::getWideningBaseCost () const inline
Definition at line 481 of file AArch64Subtarget.h.
References WideningBaseCost.
Referenced by llvm::AArch64TTIImpl::getArithmeticInstrCost().
hardenSlsBlr()
bool llvm::AArch64Subtarget::hardenSlsBlr () const inline
Definition at line 446 of file AArch64Subtarget.h.
References HardenSlsBlr.
Referenced by llvm::getBLRCallOpcode().
hardenSlsNoComdat()
bool llvm::AArch64Subtarget::hardenSlsNoComdat () const inline
Definition at line 447 of file AArch64Subtarget.h.
References HardenSlsNoComdat.
hardenSlsRetBr()
bool llvm::AArch64Subtarget::hardenSlsRetBr () const inline
Definition at line 445 of file AArch64Subtarget.h.
References HardenSlsRetBr.
hasAES()
bool llvm::AArch64Subtarget::hasAES () const inline
Definition at line 414 of file AArch64Subtarget.h.
References HasAES.
hasAggressiveFMA()
bool llvm::AArch64Subtarget::hasAggressiveFMA () const inline
Definition at line 501 of file AArch64Subtarget.h.
References HasAggressiveFMA.
Referenced by llvm::AArch64TargetLowering::enableAggressiveFMAFusion().
hasAlternativeNZCV()
bool llvm::AArch64Subtarget::hasAlternativeNZCV () const inline
Definition at line 502 of file AArch64Subtarget.h.
References HasAlternativeNZCV.
hasAM()
bool llvm::AArch64Subtarget::hasAM () const inline
Definition at line 574 of file AArch64Subtarget.h.
References HasAM.
hasAMVS()
bool llvm::AArch64Subtarget::hasAMVS () const inline
Definition at line 575 of file AArch64Subtarget.h.
References HasAMVS.
hasArithmeticBccFusion()
bool llvm::AArch64Subtarget::hasArithmeticBccFusion () const inline
Definition at line 428 of file AArch64Subtarget.h.
References HasArithmeticBccFusion.
Referenced by hasFusion().
hasArithmeticCbzFusion()
bool llvm::AArch64Subtarget::hasArithmeticCbzFusion () const inline
Definition at line 429 of file AArch64Subtarget.h.
References HasArithmeticCbzFusion.
Referenced by hasFusion().
hasBF16()
bool llvm::AArch64Subtarget::hasBF16 () const inline
Definition at line 523 of file AArch64Subtarget.h.
References HasBF16.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), performLD1ReplicateCombine(), performLDNT1Combine(), performST1Combine(), and performSTNT1Combine().
hasBTI()
bool llvm::AArch64Subtarget::hasBTI () const inline
Definition at line 509 of file AArch64Subtarget.h.
References HasBTI.
hasCCDP()
bool llvm::AArch64Subtarget::hasCCDP () const inline
Definition at line 508 of file AArch64Subtarget.h.
References HasCCDP.
hasCCIDX()
bool llvm::AArch64Subtarget::hasCCIDX () const inline
Definition at line 567 of file AArch64Subtarget.h.
References HasCCIDX.
hasCCPP()
bool llvm::AArch64Subtarget::hasCCPP () const inline
Definition at line 563 of file AArch64Subtarget.h.
References HasCCPP.
hasCmpBccFusion()
bool llvm::AArch64Subtarget::hasCmpBccFusion () const inline
Definition at line 430 of file AArch64Subtarget.h.
References HasCmpBccFusion.
hasComplxNum()
bool llvm::AArch64Subtarget::hasComplxNum () const inline
Definition at line 568 of file AArch64Subtarget.h.
References HasComplxNum.
hasCONTEXTIDREL2()
bool llvm::AArch64Subtarget::hasCONTEXTIDREL2 () const inline
Definition at line 415 of file AArch64Subtarget.h.
References HasCONTEXTIDREL2.
hasCRC()
bool llvm::AArch64Subtarget::hasCRC () const inline
Definition at line 406 of file AArch64Subtarget.h.
References HasCRC.
hasCrypto()
bool llvm::AArch64Subtarget::hasCrypto () const inline
Definition at line 404 of file AArch64Subtarget.h.
References HasCrypto.
hasCustomCallingConv()
bool llvm::AArch64Subtarget::hasCustomCallingConv () const inline
Definition at line 401 of file AArch64Subtarget.h.
References llvm::BitVector::any(), and CustomCallSavedXRegs.
Referenced by llvm::AArch64CallLowering::lowerCall(), and llvm::AArch64CallLowering::lowerFormalArguments().
hasCustomCheapAsMoveHandling()
bool llvm::AArch64Subtarget::hasCustomCheapAsMoveHandling () const inline
Definition at line 420 of file AArch64Subtarget.h.
References CustomAsCheapAsMove.
Referenced by llvm::AArch64InstrInfo::isAsCheapAsAMove().
hasDIT()
bool llvm::AArch64Subtarget::hasDIT () const inline
Definition at line 572 of file AArch64Subtarget.h.
References HasDIT.
hasDotProd()
bool llvm::AArch64Subtarget::hasDotProd () const inline
Definition at line 405 of file AArch64Subtarget.h.
References HasDotProd.
hasEL2VMSA()
bool llvm::AArch64Subtarget::hasEL2VMSA () const inline
Definition at line 584 of file AArch64Subtarget.h.
References HasEL2VMSA.
hasEL3()
bool llvm::AArch64Subtarget::hasEL3 () const inline
Definition at line 585 of file AArch64Subtarget.h.
References HasEL3.
hasEnhancedCounterVirtualization()
bool llvm::AArch64Subtarget::hasEnhancedCounterVirtualization () const inline
Definition at line 525 of file AArch64Subtarget.h.
References HasEnhancedCounterVirtualization.
hasExynosCheapAsMoveHandling()
bool llvm::AArch64Subtarget::hasExynosCheapAsMoveHandling () const inline
Definition at line 421 of file AArch64Subtarget.h.
References ExynosAsCheapAsMove.
Referenced by llvm::AArch64InstrInfo::isAsCheapAsAMove().
hasFineGrainedTraps()
bool llvm::AArch64Subtarget::hasFineGrainedTraps () const inline
Definition at line 524 of file AArch64Subtarget.h.
References HasFineGrainedTraps.
hasFlagM()
bool llvm::AArch64Subtarget::hasFlagM () const inline
Definition at line 582 of file AArch64Subtarget.h.
References HasFlagM.
hasFP16FML()
bool llvm::AArch64Subtarget::hasFP16FML () const inline
Definition at line 495 of file AArch64Subtarget.h.
References HasFP16FML.
hasFPARMv8()
bool llvm::AArch64Subtarget::hasFPARMv8 () const inline
Definition at line 402 of file AArch64Subtarget.h.
References HasFPARMv8.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AArch64TargetLowering::getOptimalMemOpLLT(), and llvm::AArch64TargetLowering::getOptimalMemOpType().
hasFRInt3264()
bool llvm::AArch64Subtarget::hasFRInt3264 () const inline
Definition at line 503 of file AArch64Subtarget.h.
References HasFRInt3264.
hasFullFP16()
bool llvm::AArch64Subtarget::hasFullFP16 () const inline
Definition at line 494 of file AArch64Subtarget.h.
References HasFullFP16.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AArch64TTIImpl::getCmpSelInstrCost(), llvm::AArch64TTIImpl::getMinMaxReductionCost(), llvm::AArch64TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::AArch64TargetLowering::isFPImmLegal(), performFpToIntCombine(), and llvm::AArch64TargetLowering::shouldConvertFpToSat().
hasFuseAddress()
bool llvm::AArch64Subtarget::hasFuseAddress () const inline
Definition at line 431 of file AArch64Subtarget.h.
References HasFuseAddress.
hasFuseAES()
bool llvm::AArch64Subtarget::hasFuseAES () const inline
Definition at line 432 of file AArch64Subtarget.h.
References HasFuseAES.
Referenced by hasFusion().
hasFuseArithmeticLogic()
bool llvm::AArch64Subtarget::hasFuseArithmeticLogic () const inline
Definition at line 433 of file AArch64Subtarget.h.
References HasFuseArithmeticLogic.
Referenced by hasFusion().
hasFuseCCSelect()
bool llvm::AArch64Subtarget::hasFuseCCSelect () const inline
Definition at line 434 of file AArch64Subtarget.h.
References HasFuseCCSelect.
Referenced by hasFusion().
hasFuseCryptoEOR()
bool llvm::AArch64Subtarget::hasFuseCryptoEOR () const inline
Definition at line 435 of file AArch64Subtarget.h.
References HasFuseCryptoEOR.
hasFuseLiterals()
bool llvm::AArch64Subtarget::hasFuseLiterals () const inline
Definition at line 436 of file AArch64Subtarget.h.
References HasFuseLiterals.
Referenced by hasFusion(), and llvm::AArch64TargetLowering::isFPImmLegal().
hasFusion()
bool llvm::AArch64Subtarget::hasFusion () const inline
Return true if the CPU supports any kind of instruction fusion.
Definition at line 439 of file AArch64Subtarget.h.
References hasArithmeticBccFusion(), hasArithmeticCbzFusion(), hasFuseAES(), hasFuseArithmeticLogic(), hasFuseCCSelect(), and hasFuseLiterals().
hasHBC()
bool llvm::AArch64Subtarget::hasHBC () const inline
Definition at line 586 of file AArch64Subtarget.h.
References HasHBC.
hasHCX()
bool llvm::AArch64Subtarget::hasHCX () const inline
Definition at line 578 of file AArch64Subtarget.h.
References HasHCX.
hasJS()
bool llvm::AArch64Subtarget::hasJS () const inline
Definition at line 566 of file AArch64Subtarget.h.
References HasJS.
hasLOR()
bool llvm::AArch64Subtarget::hasLOR () const inline
Definition at line 559 of file AArch64Subtarget.h.
References HasLOR.
hasLS64()
bool llvm::AArch64Subtarget::hasLS64 () const inline
Definition at line 579 of file AArch64Subtarget.h.
References HasLS64.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), and llvm::AArch64TargetLowering::getAsmOperandValueType().
hasLSE()
bool llvm::AArch64Subtarget::hasLSE () const inline
Definition at line 407 of file AArch64Subtarget.h.
References HasLSE.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), ReplaceCMP_SWAP_128Results(), llvm::AArch64TargetLowering::shouldExpandAtomicCmpXchgInIR(), and llvm::AArch64TargetLowering::shouldExpandAtomicRMWInIR().
hasLSE2()
bool llvm::AArch64Subtarget::hasLSE2 () const inline
Definition at line 408 of file AArch64Subtarget.h.
References HasLSE2.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AArch64TargetLowering::isOpSuitableForLDPSTP(), and llvm::AArch64TargetLowering::LowerOperation().
hasLSLFast()
bool llvm::AArch64Subtarget::hasLSLFast () const inline
Definition at line 497 of file AArch64Subtarget.h.
References HasLSLFast.
hasMatMulFP32()
bool llvm::AArch64Subtarget::hasMatMulFP32 () const inline
Definition at line 519 of file AArch64Subtarget.h.
References HasMatMulFP32.
hasMatMulFP64()
bool llvm::AArch64Subtarget::hasMatMulFP64 () const inline
Definition at line 520 of file AArch64Subtarget.h.
References HasMatMulFP64.
hasMatMulInt8()
bool llvm::AArch64Subtarget::hasMatMulInt8 () const inline
Definition at line 518 of file AArch64Subtarget.h.
References HasMatMulInt8.
hasMOPS()
bool llvm::AArch64Subtarget::hasMOPS () const inline
Definition at line 587 of file AArch64Subtarget.h.
References HasMOPS.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemmove(), and llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset().
hasMPAM()
bool llvm::AArch64Subtarget::hasMPAM () const inline
Definition at line 571 of file AArch64Subtarget.h.
References HasMPAM.
hasMTE()
bool llvm::AArch64Subtarget::hasMTE () const inline
Definition at line 511 of file AArch64Subtarget.h.
References HasMTE.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering().
hasNEON()
bool llvm::AArch64Subtarget::hasNEON () const inline
Definition at line 403 of file AArch64Subtarget.h.
References HasNEON.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysRegTuple(), foldVectorXorShiftIntoCmp(), llvm::AArch64TargetLowering::getOptimalMemOpLLT(), llvm::AArch64TargetLowering::getOptimalMemOpType(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), performFDivCombine(), performFpToIntCombine(), performIntToFpCombine(), and llvm::AArch64InstrInfo::storeRegToStackSlot().
hasNV()
bool llvm::AArch64Subtarget::hasNV () const inline
Definition at line 570 of file AArch64Subtarget.h.
References HasNV.
hasPAN()
bool llvm::AArch64Subtarget::hasPAN () const inline
Definition at line 558 of file AArch64Subtarget.h.
References HasPAN.
hasPAN_RWV()
bool llvm::AArch64Subtarget::hasPAN_RWV () const inline
Definition at line 562 of file AArch64Subtarget.h.
References HasPAN_RWV.
hasPAuth()
bool llvm::AArch64Subtarget::hasPAuth () const inline
Definition at line 565 of file AArch64Subtarget.h.
References HasPAuth.
Referenced by llvm::AArch64FrameLowering::emitPrologue(), InsertReturnAddressAuth(), and signOutlinedFunction().
hasPerfMon()
bool llvm::AArch64Subtarget::hasPerfMon () const inline
Definition at line 493 of file AArch64Subtarget.h.
References HasPerfMon.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering().
hasPredRes()
bool llvm::AArch64Subtarget::hasPredRes () const inline
Definition at line 507 of file AArch64Subtarget.h.
References HasPredRes.
hasPsUAO()
bool llvm::AArch64Subtarget::hasPsUAO () const inline
Definition at line 561 of file AArch64Subtarget.h.
References HasPsUAO.
hasRandGen()
bool llvm::AArch64Subtarget::hasRandGen () const inline
Definition at line 510 of file AArch64Subtarget.h.
References HasRandGen.
hasRAS()
bool llvm::AArch64Subtarget::hasRAS () const inline
Definition at line 409 of file AArch64Subtarget.h.
References HasRAS.
hasRCPC()
bool llvm::AArch64Subtarget::hasRCPC () const inline
Definition at line 500 of file AArch64Subtarget.h.
References HasRCPC.
hasRCPC_IMMO()
bool llvm::AArch64Subtarget::hasRCPC_IMMO () const inline
Definition at line 583 of file AArch64Subtarget.h.
References HasRCPC_IMMO.
hasRDM()
bool llvm::AArch64Subtarget::hasRDM () const inline
Definition at line 410 of file AArch64Subtarget.h.
References HasRDM.
hasSB()
bool llvm::AArch64Subtarget::hasSB () const inline
Definition at line 506 of file AArch64Subtarget.h.
References HasSB.
hasSEL2()
bool llvm::AArch64Subtarget::hasSEL2 () const inline
Definition at line 580 of file AArch64Subtarget.h.
References HasSEL2.
hasSHA2()
bool llvm::AArch64Subtarget::hasSHA2 () const inline
Definition at line 413 of file AArch64Subtarget.h.
References HasSHA2.
hasSHA3()
bool llvm::AArch64Subtarget::hasSHA3 () const inline
Definition at line 412 of file AArch64Subtarget.h.
References HasSHA3.
hasSM4()
bool llvm::AArch64Subtarget::hasSM4 () const inline
Definition at line 411 of file AArch64Subtarget.h.
References HasSM4.
hasSME()
bool llvm::AArch64Subtarget::hasSME () const inline
Definition at line 530 of file AArch64Subtarget.h.
References HasSME.
hasSMEF64()
bool llvm::AArch64Subtarget::hasSMEF64 () const inline
Definition at line 531 of file AArch64Subtarget.h.
References HasSMEF64.
hasSMEI64()
bool llvm::AArch64Subtarget::hasSMEI64 () const inline
Definition at line 532 of file AArch64Subtarget.h.
References HasSMEI64.
hasSPE()
bool llvm::AArch64Subtarget::hasSPE () const inline
Definition at line 496 of file AArch64Subtarget.h.
References HasSPE.
hasSpecRestrict()
bool llvm::AArch64Subtarget::hasSpecRestrict () const inline
Definition at line 504 of file AArch64Subtarget.h.
References HasSpecRestrict.
hasSSBS()
bool llvm::AArch64Subtarget::hasSSBS () const inline
Definition at line 505 of file AArch64Subtarget.h.
References HasSSBS.
hasStreamingSVE()
bool llvm::AArch64Subtarget::hasStreamingSVE () const inline
Definition at line 533 of file AArch64Subtarget.h.
References HasStreamingSVE.
hasSVE()
bool llvm::AArch64Subtarget::hasSVE () const inline
Definition at line 498 of file AArch64Subtarget.h.
References HasSVE.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::AArch64RegisterInfo::hasBasePointer(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::AArch64TargetLowering::shouldExpandGetActiveLaneMask(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::AArch64RegisterInfo::useFPForScavengingIndex(), and useSVEForFixedLengthVectors().
hasSVE2()
bool llvm::AArch64Subtarget::hasSVE2 () const inline
Definition at line 499 of file AArch64Subtarget.h.
References HasSVE2.
hasSVE2AES()
bool llvm::AArch64Subtarget::hasSVE2AES () const inline
Definition at line 514 of file AArch64Subtarget.h.
References HasSVE2AES.
hasSVE2BitPerm()
bool llvm::AArch64Subtarget::hasSVE2BitPerm () const inline
Definition at line 517 of file AArch64Subtarget.h.
References HasSVE2BitPerm.
hasSVE2SHA3()
bool llvm::AArch64Subtarget::hasSVE2SHA3 () const inline
Definition at line 516 of file AArch64Subtarget.h.
References HasSVE2SHA3.
hasSVE2SM4()
bool llvm::AArch64Subtarget::hasSVE2SM4 () const inline
Definition at line 515 of file AArch64Subtarget.h.
References HasSVE2SM4.
hasTLB_RMI()
bool llvm::AArch64Subtarget::hasTLB_RMI () const inline
Definition at line 581 of file AArch64Subtarget.h.
References HasTLB_RMI.
hasTME()
bool llvm::AArch64Subtarget::hasTME () const inline
Definition at line 512 of file AArch64Subtarget.h.
References HasTME.
hasTRACEV8_4()
bool llvm::AArch64Subtarget::hasTRACEV8_4 () const inline
Definition at line 573 of file AArch64Subtarget.h.
References HasTRACEV8_4.
hasV8_0aOps()
bool llvm::AArch64Subtarget::hasV8_0aOps () const inline
Definition at line 366 of file AArch64Subtarget.h.
References HasV8_0aOps.
hasV8_0rOps()
bool llvm::AArch64Subtarget::hasV8_0rOps () const inline
Definition at line 376 of file AArch64Subtarget.h.
References HasV8_0rOps.
hasV8_1aOps()
bool llvm::AArch64Subtarget::hasV8_1aOps () const inline
Definition at line 367 of file AArch64Subtarget.h.
References HasV8_1aOps.
hasV8_2aOps()
bool llvm::AArch64Subtarget::hasV8_2aOps () const inline
Definition at line 368 of file AArch64Subtarget.h.
References HasV8_2aOps.
hasV8_3aOps()
bool llvm::AArch64Subtarget::hasV8_3aOps () const inline
Definition at line 369 of file AArch64Subtarget.h.
References HasV8_3aOps.
hasV8_4aOps()
bool llvm::AArch64Subtarget::hasV8_4aOps () const inline
Definition at line 370 of file AArch64Subtarget.h.
References HasV8_4aOps.
hasV8_5aOps()
bool llvm::AArch64Subtarget::hasV8_5aOps () const inline
Definition at line 371 of file AArch64Subtarget.h.
References HasV8_5aOps.
hasV9_0aOps()
bool llvm::AArch64Subtarget::hasV9_0aOps () const inline
Definition at line 372 of file AArch64Subtarget.h.
References HasV9_0aOps.
hasV9_1aOps()
bool llvm::AArch64Subtarget::hasV9_1aOps () const inline
Definition at line 373 of file AArch64Subtarget.h.
References HasV9_1aOps.
hasV9_2aOps()
bool llvm::AArch64Subtarget::hasV9_2aOps () const inline
Definition at line 374 of file AArch64Subtarget.h.
References HasV9_2aOps.
hasV9_3aOps()
bool llvm::AArch64Subtarget::hasV9_3aOps () const inline
Definition at line 375 of file AArch64Subtarget.h.
References HasV9_3aOps.
hasVH()
bool llvm::AArch64Subtarget::hasVH () const inline
Definition at line 557 of file AArch64Subtarget.h.
References HasVH.
hasWFxT()
bool llvm::AArch64Subtarget::hasWFxT () const inline
Definition at line 577 of file AArch64Subtarget.h.
References HasWFxT.
hasXS()
bool llvm::AArch64Subtarget::hasXS () const inline
Definition at line 576 of file AArch64Subtarget.h.
References HasXS.
hasZeroCycleRegMove()
bool llvm::AArch64Subtarget::hasZeroCycleRegMove () const inline
Definition at line 378 of file AArch64Subtarget.h.
References HasZeroCycleRegMove.
Referenced by llvm::AArch64InstrInfo::copyPhysReg().
hasZeroCycleZeroingFP()
bool llvm::AArch64Subtarget::hasZeroCycleZeroingFP () const inline
Definition at line 382 of file AArch64Subtarget.h.
References HasZeroCycleZeroingFP.
Referenced by llvm::AArch64InstrInfo::isAsCheapAsAMove().
hasZeroCycleZeroingFPWorkaround()
bool llvm::AArch64Subtarget::hasZeroCycleZeroingFPWorkaround () const inline
Definition at line 384 of file AArch64Subtarget.h.
References HasZeroCycleZeroingFPWorkaround.
hasZeroCycleZeroingGP()
bool llvm::AArch64Subtarget::hasZeroCycleZeroingGP () const inline
Definition at line 380 of file AArch64Subtarget.h.
References HasZeroCycleZeroingGP.
Referenced by llvm::AArch64InstrInfo::copyPhysReg(), and llvm::AArch64InstrInfo::isAsCheapAsAMove().
isCallingConvWin64()
bool llvm::AArch64Subtarget::isCallingConvWin64 (CallingConv::ID CC) const inline
Definition at line 630 of file AArch64Subtarget.h.
References llvm::CallingConv::C, llvm::CallingConv::Fast, isTargetWindows(), llvm::CallingConv::Swift, and llvm::CallingConv::Win64.
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), and llvm::AArch64FrameLowering::emitPrologue().
isLittleEndian()
bool llvm::AArch64Subtarget::isLittleEndian () const inline
Definition at line 535 of file AArch64Subtarget.h.
References IsLittle.
isMisaligned128StoreSlow()
bool llvm::AArch64Subtarget::isMisaligned128StoreSlow () const inline
Definition at line 422 of file AArch64Subtarget.h.
References Misaligned128StoreIsSlow.
Referenced by llvm::AArch64TargetLowering::allowsMisalignedMemoryAccesses(), llvm::AArch64TargetLowering::allowsMisalignedMemoryAccesses(), llvm::AArch64TTIImpl::getMemoryOpCost(), and splitStores().
isPaired128Slow()
bool llvm::AArch64Subtarget::isPaired128Slow () const inline
Definition at line 423 of file AArch64Subtarget.h.
References Paired128IsSlow.
Referenced by llvm::AArch64InstrInfo::isCandidateToMergeOrPair().
isSTRQroSlow()
bool llvm::AArch64Subtarget::isSTRQroSlow () const inline
Definition at line 424 of file AArch64Subtarget.h.
References STRQroIsSlow.
isTargetAndroid()
bool llvm::AArch64Subtarget::isTargetAndroid () const inline
Definition at line 541 of file AArch64Subtarget.h.
References llvm::Triple::isAndroid(), and TargetTriple.
Referenced by llvm::AArch64TargetLowering::getIRStackGuard(), llvm::AArch64TargetLowering::getSafeStackPointerLocation(), and llvm::AArch64TargetLowering::useLoadStackGuardNode().
isTargetCOFF()
bool llvm::AArch64Subtarget::isTargetCOFF () const inline
Definition at line 544 of file AArch64Subtarget.h.
References llvm::Triple::isOSBinFormatCOFF(), and TargetTriple.
isTargetDarwin()
bool llvm::AArch64Subtarget::isTargetDarwin () const inline
Definition at line 537 of file AArch64Subtarget.h.
References llvm::Triple::isOSDarwin(), and TargetTriple.
Referenced by CC_AArch64_Custom_Block(), llvm::AArch64TargetLowering::CCAssignFnForCall(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCallPreservedMask(), llvm::AArch64RegisterInfo::getDarwinCalleeSavedRegs(), llvm::AArch64RegisterInfo::getDarwinCallPreservedMask(), llvm::AArch64RegisterInfo::getThisReturnPreservedMask(), llvm::AArch64TargetLowering::getVaListSizeInBits(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::AArch64CallLowering::lowerFormalArguments(), and llvm::AArch64TargetLowering::shouldExpandShift().
isTargetELF()
bool llvm::AArch64Subtarget::isTargetELF () const inline
Definition at line 545 of file AArch64Subtarget.h.
References llvm::Triple::isOSBinFormatELF(), and TargetTriple.
isTargetFuchsia()
bool llvm::AArch64Subtarget::isTargetFuchsia () const inline
Definition at line 542 of file AArch64Subtarget.h.
References llvm::Triple::isOSFuchsia(), and TargetTriple.
Referenced by llvm::AArch64TargetLowering::getIRStackGuard(), llvm::AArch64TargetLowering::getSafeStackPointerLocation(), and llvm::AArch64TargetLowering::useLoadStackGuardNode().
isTargetILP32()
bool llvm::AArch64Subtarget::isTargetILP32 () const inline
Definition at line 548 of file AArch64Subtarget.h.
References llvm::Triple::getEnvironment(), llvm::Triple::GNUILP32, llvm::Triple::isArch32Bit(), and TargetTriple.
Referenced by addrSinkUsingGEPs(), CC_AArch64_Custom_Block(), llvm::AArch64TargetLowering::CCAssignFnForCall(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AArch64FrameLowering::emitPrologue(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), and llvm::AArch64CallLowering::lowerFormalArguments().
isTargetIOS()
bool llvm::AArch64Subtarget::isTargetIOS () const inline
Definition at line 538 of file AArch64Subtarget.h.
References llvm::Triple::isiOS(), and TargetTriple.
isTargetLinux()
bool llvm::AArch64Subtarget::isTargetLinux () const inline
Definition at line 539 of file AArch64Subtarget.h.
References llvm::Triple::isOSLinux(), and TargetTriple.
Referenced by llvm::AArch64RegisterInfo::getCustomEHPadPreservedMask().
isTargetMachO()
bool llvm::AArch64Subtarget::isTargetMachO () const inline
Definition at line 546 of file AArch64Subtarget.h.
References llvm::Triple::isOSBinFormatMachO(), and TargetTriple.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), CC_AArch64_Custom_Block(), classifyGlobalFunctionReference(), ClassifyGlobalReference(), and produceCompactUnwindFrame().
isTargetWindows()
bool llvm::AArch64Subtarget::isTargetWindows () const inline
Definition at line 540 of file AArch64Subtarget.h.
References llvm::Triple::isOSWindows(), and TargetTriple.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AArch64TargetLowering::CCAssignFnForCall(), llvm::AArch64FrameLowering::determineCalleeSaves(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::AArch64TargetLowering::getVaListSizeInBits(), isCallingConvWin64(), llvm::AArch64LegalizerInfo::legalizeIntrinsic(), llvm::AArch64TargetLowering::shouldExpandShift(), and windowsRequiresStackProbe().
isXRaySupported()
bool llvm::AArch64Subtarget::isXRaySupported () const inline override
Definition at line 390 of file AArch64Subtarget.h.
isXRegCustomCalleeSaved()
bool llvm::AArch64Subtarget::isXRegCustomCalleeSaved (size_t i) const inline
Definition at line 398 of file AArch64Subtarget.h.
References CustomCallSavedXRegs.
Referenced by llvm::AArch64RegisterInfo::UpdateCustomCalleeSavedRegs(), and llvm::AArch64RegisterInfo::UpdateCustomCallPreservedMask().
isXRegisterReserved()
bool llvm::AArch64Subtarget::isXRegisterReserved (size_t i) const inline
Definition at line 396 of file AArch64Subtarget.h.
References ReserveXRegister.
Referenced by computeCalleeSaveRegisterPairs(), and llvm::AArch64RegisterInfo::getReservedRegs().
mirFileLoaded()
void AArch64Subtarget::mirFileLoaded (MachineFunction & MF) const override
Definition at line 367 of file AArch64Subtarget.cpp.
References llvm::MachineFrameInfo::computeMaxCallFrameSize(), llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::isMaxCallFrameSizeComputed().
outlineAtomics()
bool llvm::AArch64Subtarget::outlineAtomics () const inline
Definition at line 555 of file AArch64Subtarget.h.
References OutlineAtomics.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), ReplaceCMP_SWAP_128Results(), llvm::AArch64TargetLowering::shouldExpandAtomicCmpXchgInIR(), and llvm::AArch64TargetLowering::shouldExpandAtomicRMWInIR().
overrideSchedPolicy()
void AArch64Subtarget::overrideSchedPolicy (MachineSchedPolicy & Policy, unsigned NumRegionInstrs) const override
Definition at line 335 of file AArch64Subtarget.cpp.
References llvm::MachineSchedPolicy::DisableLatencyHeuristic, DisableLatencySchedHeuristic, llvm::MachineSchedPolicy::OnlyBottomUp, and llvm::MachineSchedPolicy::OnlyTopDown.
ParseSubtargetFeatures()
void llvm::AArch64Subtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
predictableSelectIsExpensive()
bool llvm::AArch64Subtarget::predictableSelectIsExpensive () const inline
Definition at line 417 of file AArch64Subtarget.h.
References PredictableSelectIsExpensive.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering().
requiresStrictAlign()
bool llvm::AArch64Subtarget::requiresStrictAlign () const inline
Definition at line 388 of file AArch64Subtarget.h.
References StrictAlign.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AArch64TargetLowering::allowsMisalignedMemoryAccesses(), llvm::AArch64TargetLowering::allowsMisalignedMemoryAccesses(), and llvm::AArch64TTIImpl::enableMemCmpExpansion().
supportsAddressTopByteIgnored()
bool AArch64Subtarget::supportsAddressTopByteIgnored () const
CPU has TBI (top byte of addresses is ignored during HW address translation) and OS enables it.
Definition at line 351 of file AArch64Subtarget.cpp.
References llvm::Triple::getiOSVersion(), llvm::Triple::isiOS(), TargetTriple, and UseAddressTopByteIgnored.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), and performSTORECombine().
swiftAsyncContextIsDynamicallySet()
bool llvm::AArch64Subtarget::swiftAsyncContextIsDynamicallySet () const inline
Return whether FrameLowering should always set the "extended frame present" bit in FP, or set it based on a symbol in the runtime.
Definition at line 645 of file AArch64Subtarget.h.
References llvm::Triple::Darwin, getTargetTriple(), llvm::Triple::IOS, llvm::Triple::MacOSX, llvm::Triple::TvOS, and llvm::Triple::WatchOS.
Referenced by llvm::AArch64FrameLowering::emitPrologue().
useAA()
bool AArch64Subtarget::useAA () const override
Definition at line 377 of file AArch64Subtarget.cpp.
References UseAA.
Referenced by addrSinkUsingGEPs().
useAlternateSExtLoadCVTF32Pattern()
bool llvm::AArch64Subtarget::useAlternateSExtLoadCVTF32Pattern () const inline
Definition at line 425 of file AArch64Subtarget.h.
References UseAlternateSExtLoadCVTF32Pattern.
useEL1ForTP()
bool llvm::AArch64Subtarget::useEL1ForTP () const inline
Definition at line 449 of file AArch64Subtarget.h.
References UseEL1ForTP.
useEL2ForTP()
bool llvm::AArch64Subtarget::useEL2ForTP () const inline
Definition at line 450 of file AArch64Subtarget.h.
References UseEL2ForTP.
useEL3ForTP()
bool llvm::AArch64Subtarget::useEL3ForTP () const inline
Definition at line 451 of file AArch64Subtarget.h.
References UseEL3ForTP.
useExperimentalZeroingPseudos()
bool llvm::AArch64Subtarget::useExperimentalZeroingPseudos () const inline
Definition at line 483 of file AArch64Subtarget.h.
References UseExperimentalZeroingPseudos.
useRSqrt()
bool llvm::AArch64Subtarget::useRSqrt () const inline
Definition at line 453 of file AArch64Subtarget.h.
References UseRSqrt.
useScalarIncVL()
bool llvm::AArch64Subtarget::useScalarIncVL () const inline
Definition at line 487 of file AArch64Subtarget.h.
References UseScalarIncVL.
useSmallAddressing()
bool llvm::AArch64Subtarget::useSmallAddressing () const inline
Definition at line 597 of file AArch64Subtarget.h.
References llvm::TargetMachine::getCodeModel(), llvm::TargetLoweringBase::getTargetMachine(), llvm::CodeModel::Kernel, llvm::CodeModel::Small, and TLInfo.
Referenced by ClassifyGlobalReference().
useSVEForFixedLengthVectors()
bool llvm::AArch64Subtarget::useSVEForFixedLengthVectors () const inline
Definition at line 682 of file AArch64Subtarget.h.
References getMinSVEVectorSizeInBits(), and hasSVE().
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::AArch64TargetLowering::isLegalInterleavedAccessType(), llvm::AArch64TargetLowering::mergeStoresAfterLegalization(), performFPExtendCombine(), performSTORECombine(), and llvm::AArch64TTIImpl::useNeonVector().
Member Data Documentation
AllowTaggedGlobals
bool llvm::AArch64Subtarget::AllowTaggedGlobals = false protected
Definition at line 271 of file AArch64Subtarget.h.
Referenced by ClassifyGlobalReference().
ARMProcFamily
ARMProcFamilyEnum llvm::AArch64Subtarget::ARMProcFamily = Others protected
ARMProcFamily - ARM processor family: Cortex-A53, Cortex-A57, and others.
Definition at line 88 of file AArch64Subtarget.h.
Referenced by getProcFamily().
BalanceFPOps
bool llvm::AArch64Subtarget::BalanceFPOps = false protected
Definition at line 248 of file AArch64Subtarget.h.
Referenced by balanceFPOps().
CacheLineSize
uint16_t llvm::AArch64Subtarget::CacheLineSize = 0 protected
Definition at line 277 of file AArch64Subtarget.h.
Referenced by getCacheLineSize().
CallLoweringInfo
std::unique_ptr<CallLowering> llvm::AArch64Subtarget::CallLoweringInfo protected
GlobalISel related APIs.
Definition at line 308 of file AArch64Subtarget.h.
Referenced by AArch64Subtarget(), and getCallLowering().
CustomAsCheapAsMove
bool llvm::AArch64Subtarget::CustomAsCheapAsMove = false protected
Definition at line 249 of file AArch64Subtarget.h.
Referenced by hasCustomCheapAsMoveHandling().
CustomCallSavedXRegs
BitVector llvm::AArch64Subtarget::CustomCallSavedXRegs protected
Definition at line 291 of file AArch64Subtarget.h.
Referenced by hasCustomCallingConv(), and isXRegCustomCalleeSaved().
DisableLatencySchedHeuristic
bool llvm::AArch64Subtarget::DisableLatencySchedHeuristic = false protected
Definition at line 265 of file AArch64Subtarget.h.
Referenced by overrideSchedPolicy().
ExynosAsCheapAsMove
bool llvm::AArch64Subtarget::ExynosAsCheapAsMove = false protected
Definition at line 250 of file AArch64Subtarget.h.
Referenced by hasExynosCheapAsMoveHandling().
FixCortexA53_835769
bool llvm::AArch64Subtarget::FixCortexA53_835769 = false protected
Definition at line 122 of file AArch64Subtarget.h.
Referenced by fixCortexA53_835769().
Force32BitJumpTables
bool llvm::AArch64Subtarget::Force32BitJumpTables = false protected
Definition at line 267 of file AArch64Subtarget.h.
Referenced by force32BitJumpTables().
FrameLowering
AArch64FrameLowering llvm::AArch64Subtarget::FrameLowering protected
Definition at line 302 of file AArch64Subtarget.h.
Referenced by getFrameLowering().
HardenSlsBlr
bool llvm::AArch64Subtarget::HardenSlsBlr = false protected
Definition at line 273 of file AArch64Subtarget.h.
Referenced by hardenSlsBlr().
HardenSlsNoComdat
bool llvm::AArch64Subtarget::HardenSlsNoComdat = false protected
Definition at line 274 of file AArch64Subtarget.h.
Referenced by hardenSlsNoComdat().
HardenSlsRetBr
bool llvm::AArch64Subtarget::HardenSlsRetBr = false protected
Definition at line 272 of file AArch64Subtarget.h.
Referenced by hardenSlsRetBr().
HasAES
bool llvm::AArch64Subtarget::HasAES = false protected
Definition at line 143 of file AArch64Subtarget.h.
Referenced by hasAES().
HasAggressiveFMA
bool llvm::AArch64Subtarget::HasAggressiveFMA = false protected
Definition at line 164 of file AArch64Subtarget.h.
Referenced by hasAggressiveFMA().
HasAlternativeNZCV
bool llvm::AArch64Subtarget::HasAlternativeNZCV = false protected
Definition at line 167 of file AArch64Subtarget.h.
Referenced by hasAlternativeNZCV().
HasAM
bool llvm::AArch64Subtarget::HasAM = false protected
Definition at line 156 of file AArch64Subtarget.h.
Referenced by hasAM().
HasAMVS
bool llvm::AArch64Subtarget::HasAMVS = false protected
Definition at line 184 of file AArch64Subtarget.h.
Referenced by hasAMVS().
HasAppleA7SysReg
bool llvm::AArch64Subtarget::HasAppleA7SysReg = false protected
Definition at line 215 of file AArch64Subtarget.h.
HasArithmeticBccFusion
bool llvm::AArch64Subtarget::HasArithmeticBccFusion = false protected
Definition at line 256 of file AArch64Subtarget.h.
Referenced by hasArithmeticBccFusion().
HasArithmeticCbzFusion
bool llvm::AArch64Subtarget::HasArithmeticCbzFusion = false protected
Definition at line 257 of file AArch64Subtarget.h.
Referenced by hasArithmeticCbzFusion().
HasBF16
bool llvm::AArch64Subtarget::HasBF16 = false protected
Definition at line 180 of file AArch64Subtarget.h.
Referenced by hasBF16().
HasBRBE
bool llvm::AArch64Subtarget::HasBRBE = false protected
Definition at line 220 of file AArch64Subtarget.h.
HasBTI
bool llvm::AArch64Subtarget::HasBTI = false protected
Definition at line 174 of file AArch64Subtarget.h.
Referenced by hasBTI().
HasCCDP
bool llvm::AArch64Subtarget::HasCCDP = false protected
Definition at line 173 of file AArch64Subtarget.h.
Referenced by hasCCDP().
HasCCIDX
bool llvm::AArch64Subtarget::HasCCIDX = false protected
Definition at line 148 of file AArch64Subtarget.h.
Referenced by hasCCIDX().
HasCCPP
bool llvm::AArch64Subtarget::HasCCPP = false protected
Definition at line 132 of file AArch64Subtarget.h.
Referenced by hasCCPP().
HasCmpBccFusion
bool llvm::AArch64Subtarget::HasCmpBccFusion = false protected
Definition at line 258 of file AArch64Subtarget.h.
Referenced by hasCmpBccFusion().
HasComplxNum
bool llvm::AArch64Subtarget::HasComplxNum = false protected
Definition at line 149 of file AArch64Subtarget.h.
Referenced by hasComplxNum().
HasCONTEXTIDREL2
bool llvm::AArch64Subtarget::HasCONTEXTIDREL2 = false protected
Definition at line 105 of file AArch64Subtarget.h.
Referenced by hasCONTEXTIDREL2().
HasCRC
bool llvm::AArch64Subtarget::HasCRC = false protected
Definition at line 112 of file AArch64Subtarget.h.
Referenced by hasCRC().
HasCrypto
bool llvm::AArch64Subtarget::HasCrypto = false protected
Definition at line 110 of file AArch64Subtarget.h.
Referenced by hasCrypto().
HasDIT
bool llvm::AArch64Subtarget::HasDIT = false protected
Definition at line 154 of file AArch64Subtarget.h.
Referenced by hasDIT().
HasDotProd
bool llvm::AArch64Subtarget::HasDotProd = false protected
Definition at line 111 of file AArch64Subtarget.h.
Referenced by hasDotProd().
HasEL2VMSA
bool llvm::AArch64Subtarget::HasEL2VMSA = false protected
Definition at line 106 of file AArch64Subtarget.h.
Referenced by hasEL2VMSA().
HasEL3
bool llvm::AArch64Subtarget::HasEL3 = false protected
Definition at line 107 of file AArch64Subtarget.h.
Referenced by hasEL3().
HasEnhancedCounterVirtualization
bool llvm::AArch64Subtarget::HasEnhancedCounterVirtualization = false protected
Definition at line 186 of file AArch64Subtarget.h.
Referenced by hasEnhancedCounterVirtualization().
HasETE
bool llvm::AArch64Subtarget::HasETE = false protected
Definition at line 218 of file AArch64Subtarget.h.
HasFineGrainedTraps
bool llvm::AArch64Subtarget::HasFineGrainedTraps = false protected
Definition at line 185 of file AArch64Subtarget.h.
Referenced by hasFineGrainedTraps().
HasFlagM
bool llvm::AArch64Subtarget::HasFlagM = false protected
Definition at line 159 of file AArch64Subtarget.h.
Referenced by hasFlagM().
HasFP16FML
bool llvm::AArch64Subtarget::HasFP16FML = false protected
Definition at line 119 of file AArch64Subtarget.h.
Referenced by hasFP16FML().
HasFPARMv8
bool llvm::AArch64Subtarget::HasFPARMv8 = false protected
Definition at line 108 of file AArch64Subtarget.h.
Referenced by hasFPARMv8().
HasFRInt3264
bool llvm::AArch64Subtarget::HasFRInt3264 = false protected
Definition at line 168 of file AArch64Subtarget.h.
Referenced by hasFRInt3264().
HasFullFP16
bool llvm::AArch64Subtarget::HasFullFP16 = false protected
Definition at line 118 of file AArch64Subtarget.h.
Referenced by hasFullFP16().
HasFuseAddress
bool llvm::AArch64Subtarget::HasFuseAddress = false protected
Definition at line 259 of file AArch64Subtarget.h.
Referenced by hasFuseAddress().
HasFuseAES
bool llvm::AArch64Subtarget::HasFuseAES = false protected
Definition at line 260 of file AArch64Subtarget.h.
Referenced by hasFuseAES().
HasFuseArithmeticLogic
bool llvm::AArch64Subtarget::HasFuseArithmeticLogic = false protected
Definition at line 261 of file AArch64Subtarget.h.
Referenced by hasFuseArithmeticLogic().
HasFuseCCSelect
bool llvm::AArch64Subtarget::HasFuseCCSelect = false protected
Definition at line 262 of file AArch64Subtarget.h.
Referenced by hasFuseCCSelect().
HasFuseCryptoEOR
bool llvm::AArch64Subtarget::HasFuseCryptoEOR = false protected
Definition at line 263 of file AArch64Subtarget.h.
Referenced by hasFuseCryptoEOR().
HasFuseLiterals
bool llvm::AArch64Subtarget::HasFuseLiterals = false protected
Definition at line 264 of file AArch64Subtarget.h.
Referenced by hasFuseLiterals().
HasHBC
bool llvm::AArch64Subtarget::HasHBC = false protected
Definition at line 195 of file AArch64Subtarget.h.
Referenced by hasHBC().
HasHCX
bool llvm::AArch64Subtarget::HasHCX = false protected
Definition at line 191 of file AArch64Subtarget.h.
Referenced by hasHCX().
HasJS
bool llvm::AArch64Subtarget::HasJS = false protected
Definition at line 147 of file AArch64Subtarget.h.
Referenced by hasJS().
HasLOR
bool llvm::AArch64Subtarget::HasLOR = false protected
Definition at line 127 of file AArch64Subtarget.h.
Referenced by hasLOR().
HasLS64
bool llvm::AArch64Subtarget::HasLS64 = false protected
Definition at line 192 of file AArch64Subtarget.h.
Referenced by hasLS64().
HasLSE
bool llvm::AArch64Subtarget::HasLSE = false protected
Definition at line 113 of file AArch64Subtarget.h.
Referenced by hasLSE().
HasLSE2
bool llvm::AArch64Subtarget::HasLSE2 = false protected
Definition at line 114 of file AArch64Subtarget.h.
Referenced by hasLSE2().
HasLSLFast
bool llvm::AArch64Subtarget::HasLSLFast = false protected
Definition at line 162 of file AArch64Subtarget.h.
Referenced by hasLSLFast().
HasMatMulFP32
bool llvm::AArch64Subtarget::HasMatMulFP32 = false protected
Definition at line 182 of file AArch64Subtarget.h.
Referenced by hasMatMulFP32().
HasMatMulFP64
bool llvm::AArch64Subtarget::HasMatMulFP64 = false protected
Definition at line 183 of file AArch64Subtarget.h.
Referenced by hasMatMulFP64().
HasMatMulInt8
bool llvm::AArch64Subtarget::HasMatMulInt8 = false protected
Definition at line 181 of file AArch64Subtarget.h.
Referenced by hasMatMulInt8().
HasMOPS
bool llvm::AArch64Subtarget::HasMOPS = false protected
Definition at line 196 of file AArch64Subtarget.h.
Referenced by hasMOPS().
HasMPAM
bool llvm::AArch64Subtarget::HasMPAM = false protected
Definition at line 153 of file AArch64Subtarget.h.
Referenced by hasMPAM().
HasMTE
bool llvm::AArch64Subtarget::HasMTE = false protected
Definition at line 176 of file AArch64Subtarget.h.
Referenced by hasMTE().
HasNEON
bool llvm::AArch64Subtarget::HasNEON = false protected
Definition at line 109 of file AArch64Subtarget.h.
Referenced by hasNEON().
HasNV
bool llvm::AArch64Subtarget::HasNV = false protected
Definition at line 152 of file AArch64Subtarget.h.
Referenced by hasNV().
HasPAN
bool llvm::AArch64Subtarget::HasPAN = false protected
Definition at line 126 of file AArch64Subtarget.h.
Referenced by hasPAN().
HasPAN_RWV
bool llvm::AArch64Subtarget::HasPAN_RWV = false protected
Definition at line 131 of file AArch64Subtarget.h.
Referenced by hasPAN_RWV().
HasPAuth
bool llvm::AArch64Subtarget::HasPAuth = false protected
Definition at line 146 of file AArch64Subtarget.h.
Referenced by hasPAuth().
HasPerfMon
bool llvm::AArch64Subtarget::HasPerfMon = false protected
Definition at line 117 of file AArch64Subtarget.h.
Referenced by hasPerfMon().
HasPredRes
bool llvm::AArch64Subtarget::HasPredRes = false protected
Definition at line 172 of file AArch64Subtarget.h.
Referenced by hasPredRes().
HasPsUAO
bool llvm::AArch64Subtarget::HasPsUAO = false protected
Definition at line 130 of file AArch64Subtarget.h.
Referenced by hasPsUAO().
HasRandGen
bool llvm::AArch64Subtarget::HasRandGen = false protected
Definition at line 175 of file AArch64Subtarget.h.
Referenced by hasRandGen().
HasRAS
bool llvm::AArch64Subtarget::HasRAS = false protected
Definition at line 115 of file AArch64Subtarget.h.
Referenced by hasRAS().
HasRCPC
bool llvm::AArch64Subtarget::HasRCPC = false protected
Definition at line 163 of file AArch64Subtarget.h.
Referenced by hasRCPC().
HasRCPC_IMMO
bool llvm::AArch64Subtarget::HasRCPC_IMMO = false protected
Definition at line 160 of file AArch64Subtarget.h.
Referenced by hasRCPC_IMMO().
HasRDM
bool llvm::AArch64Subtarget::HasRDM = false protected
Definition at line 116 of file AArch64Subtarget.h.
Referenced by hasRDM().
HasRME
bool llvm::AArch64Subtarget::HasRME = false protected
Definition at line 206 of file AArch64Subtarget.h.
HasSB
bool llvm::AArch64Subtarget::HasSB = false protected
Definition at line 171 of file AArch64Subtarget.h.
Referenced by hasSB().
HasSEL2
bool llvm::AArch64Subtarget::HasSEL2 = false protected
Definition at line 157 of file AArch64Subtarget.h.
Referenced by hasSEL2().
HasSHA2
bool llvm::AArch64Subtarget::HasSHA2 = false protected
Definition at line 142 of file AArch64Subtarget.h.
Referenced by hasSHA2().
HasSHA3
bool llvm::AArch64Subtarget::HasSHA3 = false protected
Definition at line 141 of file AArch64Subtarget.h.
Referenced by hasSHA3().
HasSM4
bool llvm::AArch64Subtarget::HasSM4 = false protected
Definition at line 140 of file AArch64Subtarget.h.
Referenced by hasSM4().
HasSME
bool llvm::AArch64Subtarget::HasSME = false protected
Definition at line 209 of file AArch64Subtarget.h.
Referenced by hasSME().
HasSMEF64
bool llvm::AArch64Subtarget::HasSMEF64 = false protected
Definition at line 210 of file AArch64Subtarget.h.
Referenced by hasSMEF64().
HasSMEI64
bool llvm::AArch64Subtarget::HasSMEI64 = false protected
Definition at line 211 of file AArch64Subtarget.h.
Referenced by hasSMEI64().
HasSPE
bool llvm::AArch64Subtarget::HasSPE = false protected
Definition at line 120 of file AArch64Subtarget.h.
Referenced by hasSPE().
HasSPE_EEF
bool llvm::AArch64Subtarget::HasSPE_EEF = false protected
Definition at line 221 of file AArch64Subtarget.h.
HasSpecRestrict
bool llvm::AArch64Subtarget::HasSpecRestrict = false protected
Definition at line 169 of file AArch64Subtarget.h.
Referenced by hasSpecRestrict().
HasSSBS
bool llvm::AArch64Subtarget::HasSSBS = false protected
Definition at line 170 of file AArch64Subtarget.h.
Referenced by hasSSBS().
HasStreamingSVE
bool llvm::AArch64Subtarget::HasStreamingSVE = false protected
Definition at line 212 of file AArch64Subtarget.h.
Referenced by hasStreamingSVE().
HasSVE
bool llvm::AArch64Subtarget::HasSVE = false protected
Definition at line 135 of file AArch64Subtarget.h.
Referenced by getMaxSVEVectorSizeInBits(), getMinSVEVectorSizeInBits(), and hasSVE().
HasSVE2
bool llvm::AArch64Subtarget::HasSVE2 = false protected
Definition at line 199 of file AArch64Subtarget.h.
Referenced by hasSVE2().
HasSVE2AES
bool llvm::AArch64Subtarget::HasSVE2AES = false protected
Definition at line 200 of file AArch64Subtarget.h.
Referenced by hasSVE2AES().
HasSVE2BitPerm
bool llvm::AArch64Subtarget::HasSVE2BitPerm = false protected
Definition at line 203 of file AArch64Subtarget.h.
Referenced by hasSVE2BitPerm().
HasSVE2SHA3
bool llvm::AArch64Subtarget::HasSVE2SHA3 = false protected
Definition at line 202 of file AArch64Subtarget.h.
Referenced by hasSVE2SHA3().
HasSVE2SM4
bool llvm::AArch64Subtarget::HasSVE2SM4 = false protected
Definition at line 201 of file AArch64Subtarget.h.
Referenced by hasSVE2SM4().
HasTLB_RMI
bool llvm::AArch64Subtarget::HasTLB_RMI = false protected
Definition at line 158 of file AArch64Subtarget.h.
Referenced by hasTLB_RMI().
HasTME
bool llvm::AArch64Subtarget::HasTME = false protected
Definition at line 177 of file AArch64Subtarget.h.
Referenced by hasTME().
HasTRACEV8_4
bool llvm::AArch64Subtarget::HasTRACEV8_4 = false protected
Definition at line 155 of file AArch64Subtarget.h.
Referenced by hasTRACEV8_4().
HasTRBE
bool llvm::AArch64Subtarget::HasTRBE = false protected
Definition at line 219 of file AArch64Subtarget.h.
HasV8_0aOps
bool llvm::AArch64Subtarget::HasV8_0aOps = false protected
Definition at line 90 of file AArch64Subtarget.h.
Referenced by hasV8_0aOps().
HasV8_0rOps
bool llvm::AArch64Subtarget::HasV8_0rOps = false protected
Definition at line 103 of file AArch64Subtarget.h.
Referenced by hasV8_0rOps().
HasV8_1aOps
bool llvm::AArch64Subtarget::HasV8_1aOps = false protected
Definition at line 91 of file AArch64Subtarget.h.
Referenced by hasV8_1aOps().
HasV8_2aOps
bool llvm::AArch64Subtarget::HasV8_2aOps = false protected
Definition at line 92 of file AArch64Subtarget.h.
Referenced by hasV8_2aOps().
HasV8_3aOps
bool llvm::AArch64Subtarget::HasV8_3aOps = false protected
Definition at line 93 of file AArch64Subtarget.h.
Referenced by hasV8_3aOps().
HasV8_4aOps
bool llvm::AArch64Subtarget::HasV8_4aOps = false protected
Definition at line 94 of file AArch64Subtarget.h.
Referenced by hasV8_4aOps().
HasV8_5aOps
bool llvm::AArch64Subtarget::HasV8_5aOps = false protected
Definition at line 95 of file AArch64Subtarget.h.
Referenced by hasV8_5aOps().
HasV8_6aOps
bool llvm::AArch64Subtarget::HasV8_6aOps = false protected
Definition at line 96 of file AArch64Subtarget.h.
HasV8_7aOps
bool llvm::AArch64Subtarget::HasV8_7aOps = false protected
Definition at line 97 of file AArch64Subtarget.h.
HasV8_8aOps
bool llvm::AArch64Subtarget::HasV8_8aOps = false protected
Definition at line 98 of file AArch64Subtarget.h.
HasV9_0aOps
bool llvm::AArch64Subtarget::HasV9_0aOps = false protected
Definition at line 99 of file AArch64Subtarget.h.
Referenced by hasV9_0aOps().
HasV9_1aOps
bool llvm::AArch64Subtarget::HasV9_1aOps = false protected
Definition at line 100 of file AArch64Subtarget.h.
Referenced by hasV9_1aOps().
HasV9_2aOps
bool llvm::AArch64Subtarget::HasV9_2aOps = false protected
Definition at line 101 of file AArch64Subtarget.h.
Referenced by hasV9_2aOps().
HasV9_3aOps
bool llvm::AArch64Subtarget::HasV9_3aOps = false protected
Definition at line 102 of file AArch64Subtarget.h.
Referenced by hasV9_3aOps().
HasVH
bool llvm::AArch64Subtarget::HasVH = false protected
Definition at line 125 of file AArch64Subtarget.h.
Referenced by hasVH().
HasWFxT
bool llvm::AArch64Subtarget::HasWFxT = false protected
Definition at line 190 of file AArch64Subtarget.h.
Referenced by hasWFxT().
HasXS
bool llvm::AArch64Subtarget::HasXS = false protected
Definition at line 189 of file AArch64Subtarget.h.
Referenced by hasXS().
HasZeroCycleRegMove
bool llvm::AArch64Subtarget::HasZeroCycleRegMove = false protected
Definition at line 224 of file AArch64Subtarget.h.
Referenced by hasZeroCycleRegMove().
HasZeroCycleZeroing
bool llvm::AArch64Subtarget::HasZeroCycleZeroing = false protected
Definition at line 227 of file AArch64Subtarget.h.
HasZeroCycleZeroingFP
bool llvm::AArch64Subtarget::HasZeroCycleZeroingFP = true protected
Definition at line 235 of file AArch64Subtarget.h.
Referenced by hasZeroCycleZeroingFP().
HasZeroCycleZeroingFPWorkaround
bool llvm::AArch64Subtarget::HasZeroCycleZeroingFPWorkaround = false protected
Definition at line 229 of file AArch64Subtarget.h.
Referenced by hasZeroCycleZeroingFPWorkaround().
HasZeroCycleZeroingGP
bool llvm::AArch64Subtarget::HasZeroCycleZeroingGP = false protected
Definition at line 228 of file AArch64Subtarget.h.
Referenced by hasZeroCycleZeroingGP().
InlineAsmLoweringInfo
std::unique_ptr<InlineAsmLowering> llvm::AArch64Subtarget::InlineAsmLoweringInfo protected
Definition at line 309 of file AArch64Subtarget.h.
Referenced by AArch64Subtarget(), and getInlineAsmLowering().
InstrInfo
AArch64InstrInfo llvm::AArch64Subtarget::InstrInfo protected
Definition at line 303 of file AArch64Subtarget.h.
Referenced by getInstrInfo().
InstSelector
std::unique_ptr<InstructionSelector> llvm::AArch64Subtarget::InstSelector protected
Definition at line 310 of file AArch64Subtarget.h.
Referenced by AArch64Subtarget(), and getInstructionSelector().
IsLittle
bool llvm::AArch64Subtarget::IsLittle protected
Definition at line 293 of file AArch64Subtarget.h.
Referenced by isLittleEndian().
Legalizer
std::unique_ptr<LegalizerInfo> llvm::AArch64Subtarget::Legalizer protected
Definition at line 311 of file AArch64Subtarget.h.
MaxBytesForLoopAlignment
unsigned llvm::AArch64Subtarget::MaxBytesForLoopAlignment = 0 protected
Definition at line 283 of file AArch64Subtarget.h.
Referenced by getMaxBytesForLoopAlignment().
MaxInterleaveFactor
uint8_t llvm::AArch64Subtarget::MaxInterleaveFactor = 2 protected
Definition at line 275 of file AArch64Subtarget.h.
Referenced by getMaxInterleaveFactor().
MaxJumpTableSize
unsigned llvm::AArch64Subtarget::MaxJumpTableSize = 0 protected
Definition at line 284 of file AArch64Subtarget.h.
Referenced by getMaximumJumpTableSize().
MaxPrefetchIterationsAhead
unsigned llvm::AArch64Subtarget::MaxPrefetchIterationsAhead = UINT_MAX protected
Definition at line 280 of file AArch64Subtarget.h.
Referenced by getMaxPrefetchIterationsAhead().
MaxSVEVectorSizeInBits
unsigned llvm::AArch64Subtarget::MaxSVEVectorSizeInBits protected
Definition at line 296 of file AArch64Subtarget.h.
Referenced by getMaxSVEVectorSizeInBits().
MinPrefetchStride
uint16_t llvm::AArch64Subtarget::MinPrefetchStride = 1 protected
Definition at line 279 of file AArch64Subtarget.h.
Referenced by getMinPrefetchStride().
MinSVEVectorSizeInBits
unsigned llvm::AArch64Subtarget::MinSVEVectorSizeInBits protected
Definition at line 295 of file AArch64Subtarget.h.
Referenced by getMinSVEVectorSizeInBits().
MinVectorRegisterBitWidth
unsigned llvm::AArch64Subtarget::MinVectorRegisterBitWidth = 64 protected
Definition at line 244 of file AArch64Subtarget.h.
Referenced by getMinVectorRegisterBitWidth().
Misaligned128StoreIsSlow
bool llvm::AArch64Subtarget::Misaligned128StoreIsSlow = false protected
Definition at line 252 of file AArch64Subtarget.h.
Referenced by isMisaligned128StoreSlow().
NegativeImmediates
bool llvm::AArch64Subtarget::NegativeImmediates = true protected
Definition at line 241 of file AArch64Subtarget.h.
OutlineAtomics
bool llvm::AArch64Subtarget::OutlineAtomics = false protected
Definition at line 246 of file AArch64Subtarget.h.
Referenced by outlineAtomics().
Paired128IsSlow
bool llvm::AArch64Subtarget::Paired128IsSlow = false protected
Definition at line 253 of file AArch64Subtarget.h.
Referenced by isPaired128Slow().
PredictableSelectIsExpensive
bool llvm::AArch64Subtarget::PredictableSelectIsExpensive = false protected
Definition at line 247 of file AArch64Subtarget.h.
Referenced by predictableSelectIsExpensive().
PrefetchDistance
uint16_t llvm::AArch64Subtarget::PrefetchDistance = 0 protected
Definition at line 278 of file AArch64Subtarget.h.
Referenced by getPrefetchDistance().
PrefFunctionLogAlignment
unsigned llvm::AArch64Subtarget::PrefFunctionLogAlignment = 0 protected
Definition at line 281 of file AArch64Subtarget.h.
Referenced by getPrefFunctionLogAlignment().
PrefLoopLogAlignment
unsigned llvm::AArch64Subtarget::PrefLoopLogAlignment = 0 protected
Definition at line 282 of file AArch64Subtarget.h.
Referenced by getPrefLoopLogAlignment().
RegBankInfo
std::unique_ptr<RegisterBankInfo> llvm::AArch64Subtarget::RegBankInfo protected
Definition at line 312 of file AArch64Subtarget.h.
Referenced by AArch64Subtarget(), and getRegBankInfo().
ReserveXRegister
BitVector llvm::AArch64Subtarget::ReserveXRegister protected
Definition at line 288 of file AArch64Subtarget.h.
Referenced by AArch64Subtarget(), getNumXRegisterReserved(), and isXRegisterReserved().
StrictAlign
bool llvm::AArch64Subtarget::StrictAlign = false protected
Definition at line 238 of file AArch64Subtarget.h.
Referenced by requiresStrictAlign().
STRQroIsSlow
bool llvm::AArch64Subtarget::STRQroIsSlow = false protected
Definition at line 254 of file AArch64Subtarget.h.
Referenced by isSTRQroSlow().
TargetTriple
Triple llvm::AArch64Subtarget::TargetTriple protected
TargetTriple - What processor and OS we're targeting.
Definition at line 300 of file AArch64Subtarget.h.
Referenced by getTargetTriple(), isTargetAndroid(), isTargetCOFF(), isTargetDarwin(), isTargetELF(), isTargetFuchsia(), isTargetILP32(), isTargetIOS(), isTargetLinux(), isTargetMachO(), isTargetWindows(), and supportsAddressTopByteIgnored().
TLInfo
AArch64TargetLowering llvm::AArch64Subtarget::TLInfo protected
Definition at line 305 of file AArch64Subtarget.h.
Referenced by getTargetLowering(), and useSmallAddressing().
TSInfo
AArch64SelectionDAGInfo llvm::AArch64Subtarget::TSInfo protected
Definition at line 304 of file AArch64Subtarget.h.
Referenced by getSelectionDAGInfo().
UseAlternateSExtLoadCVTF32Pattern
bool llvm::AArch64Subtarget::UseAlternateSExtLoadCVTF32Pattern = false protected
Definition at line 255 of file AArch64Subtarget.h.
Referenced by useAlternateSExtLoadCVTF32Pattern().
UseEL1ForTP
bool llvm::AArch64Subtarget::UseEL1ForTP = false protected
Definition at line 268 of file AArch64Subtarget.h.
Referenced by useEL1ForTP().
UseEL2ForTP
bool llvm::AArch64Subtarget::UseEL2ForTP = false protected
Definition at line 269 of file AArch64Subtarget.h.
Referenced by useEL2ForTP().
UseEL3ForTP
bool llvm::AArch64Subtarget::UseEL3ForTP = false protected
Definition at line 270 of file AArch64Subtarget.h.
Referenced by useEL3ForTP().
UseExperimentalZeroingPseudos
bool llvm::AArch64Subtarget::UseExperimentalZeroingPseudos = false protected
Definition at line 136 of file AArch64Subtarget.h.
Referenced by useExperimentalZeroingPseudos().
UsePostRAScheduler
bool llvm::AArch64Subtarget::UsePostRAScheduler = false protected
Definition at line 251 of file AArch64Subtarget.h.
Referenced by enablePostRAScheduler().
UseRSqrt
bool llvm::AArch64Subtarget::UseRSqrt = false protected
Definition at line 266 of file AArch64Subtarget.h.
Referenced by useRSqrt().
UseScalarIncVL
bool llvm::AArch64Subtarget::UseScalarIncVL = false protected
Definition at line 137 of file AArch64Subtarget.h.
Referenced by useScalarIncVL().
VectorInsertExtractBaseCost
uint8_t llvm::AArch64Subtarget::VectorInsertExtractBaseCost = 3 protected
Definition at line 276 of file AArch64Subtarget.h.
Referenced by getVectorInsertExtractBaseCost().
VScaleForTuning
unsigned llvm::AArch64Subtarget::VScaleForTuning = 2 protected
Definition at line 297 of file AArch64Subtarget.h.
Referenced by getVScaleForTuning().
WideningBaseCost
unsigned llvm::AArch64Subtarget::WideningBaseCost = 0 protected
Definition at line 285 of file AArch64Subtarget.h.
Referenced by getWideningBaseCost().
The documentation for this class was generated from the following files:
lib/Target/AArch64/AArch64Subtarget.h
lib/Target/AArch64/AArch64Subtarget.cpp