LLVM: llvm::BasicAAResult Class Reference
llvm::BasicAAResult Class Reference
This is the AA result object for the basic, local, and stateless alias analysis.
#include "llvm/Analysis/BasicAliasAnalysis.h"
Classes
struct DecomposedGEP
Public Member Functions
BasicAAResult (const DataLayout &DL, const Function &F, const TargetLibraryInfo &TLI, AssumptionCache &AC, DominatorTree *DT=nullptr, PhiValues *PV=nullptr)
BasicAAResult (const BasicAAResult &Arg)
BasicAAResult (BasicAAResult &&Arg)
bool invalidate (Function &Fn, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &Inv)
Handle invalidation events in the new pass manager.
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
Checks to see if the specified callsite can clobber the specified memory object.
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
Chases pointers until we find a (constant global) or not.
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
Get the location associated with a pointer argument of a callsite.
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
Returns the behavior when calling the given call site.
FunctionModRefBehavior getModRefBehavior (const Function *Fn)
Returns the behavior when calling the given function.
Public Member Functions inherited from llvm::AAResultBase< BasicAAResult >
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase< BasicAAResult >
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)
AAResultBase (AAResultBase &&Arg)
AAResultsProxy getBestAAResults ()
Get a proxy for the best AA result set to query at this time.
Detailed Description
This is the AA result object for the basic, local, and stateless alias analysis.
It implements the AA query interface in an entirely stateless manner. As one consequence, it is never invalidated due to IR changes. While it does retain some storage, that is used as an optimization and not to preserve information from query to query. However it does retain handles to various other analyses and must be recomputed when those analyses are.
Definition at line 46 of file BasicAliasAnalysis.h.
Constructor & Destructor Documentation
BasicAAResult() [1/3]
llvm::BasicAAResult::BasicAAResult (const DataLayout & DL, const Function & F, const TargetLibraryInfo & TLI, AssumptionCache & AC, DominatorTree * DT = nullptr, PhiValues * PV = nullptr) inline
Definition at line 57 of file BasicAliasAnalysis.h.
References DL, and F.
BasicAAResult() [2/3]
llvm::BasicAAResult::BasicAAResult (const BasicAAResult & Arg) inline
Definition at line 62 of file BasicAliasAnalysis.h.
References DL, and F.
BasicAAResult() [3/3]
llvm::BasicAAResult::BasicAAResult (BasicAAResult && Arg) inline
Definition at line 65 of file BasicAliasAnalysis.h.
References DL, and F.
Member Function Documentation
alias()
AliasResult BasicAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI)
Definition at line 892 of file BasicAliasAnalysis.cpp.
References assert(), and notDifferentParent().
Referenced by getModRefInfo().
getArgModRefInfo()
ModRefInfo BasicAAResult::getArgModRefInfo (const CallBase * Call, unsigned ArgIdx)
Get the location associated with a pointer argument of a callsite.
Definition at line 854 of file BasicAliasAnalysis.cpp.
References llvm::AAResultBase< DerivedT >::getArgModRefInfo(), isWriteOnlyParam(), llvm::Mod, llvm::NoModRef, and llvm::Ref.
getModRefBehavior() [1/2]
FunctionModRefBehavior BasicAAResult::getModRefBehavior (const CallBase * Call)
Returns the behavior when calling the given call site.
Definition at line 771 of file BasicAliasAnalysis.cpp.
References llvm::FMRB_DoesNotAccessMemory, llvm::FMRB_OnlyAccessesArgumentPointees, llvm::FMRB_OnlyAccessesInaccessibleMem, llvm::FMRB_OnlyAccessesInaccessibleOrArgMem, llvm::FMRB_OnlyReadsMemory, llvm::FMRB_OnlyWritesMemory, llvm::FMRB_UnknownModRefBehavior, llvm::AAResultBase< BasicAAResult >::getBestAAResults(), and getModRefBehavior().
Referenced by getModRefBehavior(), and getModRefInfo().
getModRefBehavior() [2/2]
FunctionModRefBehavior BasicAAResult::getModRefBehavior (const Function * F)
Returns the behavior when calling the given function.
For use when the call site is not known.
Definition at line 805 of file BasicAliasAnalysis.cpp.
References F, llvm::FMRB_DoesNotAccessMemory, llvm::FMRB_OnlyAccessesArgumentPointees, llvm::FMRB_OnlyAccessesInaccessibleMem, llvm::FMRB_OnlyAccessesInaccessibleOrArgMem, llvm::FMRB_OnlyReadsMemory, llvm::FMRB_OnlyWritesMemory, and llvm::FMRB_UnknownModRefBehavior.
getModRefInfo() [1/2]
ModRefInfo BasicAAResult::getModRefInfo (const CallBase * Call, const MemoryLocation & Loc, AAQueryInfo & AAQI)
Checks to see if the specified callsite can clobber the specified memory object.
Since we only look at local properties of this function, we really can't say much about this query. We do, however, use simple "address taken" analysis on local objects.
Definition at line 906 of file BasicAliasAnalysis.cpp.
References alias(), assert(), llvm::AAQueryInfo::CI, llvm::clearMust(), llvm::MemoryLocation::getBeforeOrAfter(), llvm::AAResultBase< BasicAAResult >::getBestAAResults(), llvm::MemoryLocation::getForDest(), llvm::MemoryLocation::getForSource(), llvm::AAResultBase< DerivedT >::getModRefInfo(), llvm::getUnderlyingObject(), isIntrinsicCall(), llvm::isMallocOrCallocLikeFn(), llvm::isModAndRefSet(), llvm::isNoModRef(), llvm::CaptureInfo::isNotCapturedBeforeOrAt(), llvm::Mod, llvm::ModRef, llvm::AliasResult::MustAlias, llvm::AliasResult::NoAlias, llvm::NoModRef, notDifferentParent(), llvm::Object, llvm::Ref, llvm::setMod(), llvm::setMust(), and llvm::setRef().
getModRefInfo() [2/2]
ModRefInfo BasicAAResult::getModRefInfo (const CallBase * Call1, const CallBase * Call2, AAQueryInfo & AAQI)
Definition at line 1076 of file BasicAliasAnalysis.cpp.
References llvm::createModRefInfo(), getModRefBehavior(), llvm::AAResultBase< DerivedT >::getModRefInfo(), isIntrinsicCall(), llvm::isModSet(), llvm::Mod, llvm::NoModRef, and llvm::Ref.
invalidate()
bool BasicAAResult::invalidate (Function & Fn, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator & Inv)
Handle invalidation events in the new pass manager.
Definition at line 89 of file BasicAliasAnalysis.cpp.
References llvm::AnalysisManager< IRUnitT, ExtraArgTs >::Invalidator::invalidate().
pointsToConstantMemory()
bool BasicAAResult::pointsToConstantMemory (const MemoryLocation & Loc, AAQueryInfo & AAQI, bool OrLocal)
Chases pointers until we find a (constant global) or not.
Returns whether the given pointer value points to memory that is local to the function, with global constants being considered local to all functions.
Definition at line 707 of file BasicAliasAnalysis.cpp.
References llvm::append_range(), assert(), llvm::getUnderlyingObject(), llvm::AAResultBase< DerivedT >::pointsToConstantMemory(), and SI.
The documentation for this class was generated from the following files:
include/llvm/Analysis/BasicAliasAnalysis.h
lib/Analysis/BasicAliasAnalysis.cpp