LLVM: llvm::MachineModuleInfo Class Reference
llvm::MachineModuleInfo Class Reference
This class contains meta information specific to a module.
#include "llvm/CodeGen/MachineModuleInfo.h"
Public Member Functions
MachineModuleInfo (const LLVMTargetMachine *TM=nullptr)
MachineModuleInfo (const LLVMTargetMachine *TM, MCContext *ExtContext)
MachineModuleInfo (MachineModuleInfo &&MMII)
~MachineModuleInfo ()
void initialize ()
void finalize ()
const LLVMTargetMachine & getTarget () const
const MCContext & getContext () const
MCContext & getContext ()
const Module * getModule () const
MachineFunction & getOrCreateMachineFunction (Function &F)
Returns the MachineFunction constructed for the IR function F.
MachineFunction * getMachineFunction (const Function &F) const
Returns the MachineFunction associated to IR function F if there is one, otherwise nullptr.
void deleteMachineFunctionFor (Function &F)
Delete the MachineFunction MF and reset the link in the IR Function to Machine Function map.
template<typename Ty >
Ty & getObjFileInfo ()
Keep track of various per-module pieces of information for backends that would like to do so.
template<typename Ty >
const Ty & getObjFileInfo () const
bool hasDebugInfo () const
Returns true if valid debug info is present.
void setDebugInfoAvailability (bool avail)
bool usesMSVCFloatingPoint () const
void setUsesMSVCFloatingPoint (bool b)
bool usesMorestackAddr () const
void setUsesMorestackAddr (bool b)
bool hasSplitStack () const
void setHasSplitStack (bool b)
bool hasNosplitStack () const
void setHasNosplitStack (bool b)
MCSymbol * getAddrLabelSymbol (const BasicBlock *BB)
Return the symbol to be used for the specified basic block when its address is taken.
ArrayRef< MCSymbol * > getAddrLabelSymbolToEmit (const BasicBlock *BB)
Return the symbol to be used for the specified basic block when its address is taken.
void takeDeletedSymbolsForFunction (const Function *F, std::vector< MCSymbol * > &Result)
If the specified function has had any references to address-taken blocks generated, but the block got deleted, return the symbol now so we can emit it.
bool invalidate (Module &, const PreservedAnalyses &, ModuleAnalysisManager::Invalidator &)
Friends
class MachineModuleInfoWrapperPass
class MachineModuleAnalysis
Exception Handling
void setCurrentCallSite (unsigned Site)
Set the call site currently being processed.
unsigned getCurrentCallSite ()
Get the call site currently being processed, if any.
void addPersonality (const Function *Personality)
Provide the personality function for the exception information.
const std::vector< const Function * > & getPersonalities () const
Return array of personality functions ever seen.
Detailed Description
This class contains meta information specific to a module.
Queries can be made by different debugging and exception handling schemes and reformated for specific use.
Definition at line 77 of file MachineModuleInfo.h.
Constructor & Destructor Documentation
MachineModuleInfo() [1/3]
MachineModuleInfo::MachineModuleInfo (const LLVMTargetMachine * TM = nullptr) explicit
Definition at line 236 of file MachineModuleInfo.cpp.
References initialize(), and TM.
MachineModuleInfo() [2/3]
MachineModuleInfo::MachineModuleInfo (const LLVMTargetMachine * TM, MCContext * ExtContext) explicit
Definition at line 244 of file MachineModuleInfo.cpp.
References initialize(), and TM.
MachineModuleInfo() [3/3]
MachineModuleInfo::MachineModuleInfo (MachineModuleInfo && MMII)
Definition at line 218 of file MachineModuleInfo.cpp.
~MachineModuleInfo()
MachineModuleInfo::~MachineModuleInfo ()
Definition at line 254 of file MachineModuleInfo.cpp.
References finalize().
Member Function Documentation
addPersonality()
void MachineModuleInfo::addPersonality (const Function * Personality)
Provide the personality function for the exception information.
Definition at line 278 of file MachineModuleInfo.cpp.
References llvm::is_contained().
Referenced by llvm::MachineFunction::addLandingPad(), and llvm::DwarfCFIException::beginFragment().
deleteMachineFunctionFor()
void MachineModuleInfo::deleteMachineFunctionFor (Function & F)
Delete the MachineFunction MF and reset the link in the IR Function to Machine Function map.
Definition at line 315 of file MachineModuleInfo.cpp.
References F.
finalize()
void MachineModuleInfo::finalize ()
Definition at line 205 of file MachineModuleInfo.cpp.
Referenced by llvm::MachineModuleInfoWrapperPass::doFinalization(), and ~MachineModuleInfo().
getAddrLabelSymbol()
MCSymbol * llvm::MachineModuleInfo::getAddrLabelSymbol (const BasicBlock * BB) inline
Return the symbol to be used for the specified basic block when its address is taken.
This cannot be its normal LBB label because the block may be accessed outside its containing function.
Definition at line 236 of file MachineModuleInfo.h.
References llvm::BB, and getAddrLabelSymbolToEmit().
Referenced by llvm::AsmPrinter::GetBlockAddressSymbol(), and llvm::AsmPrinter::GetBlockAddressSymbol().
getAddrLabelSymbolToEmit()
ArrayRef< MCSymbol * > MachineModuleInfo::getAddrLabelSymbolToEmit (const BasicBlock * BB)
Return the symbol to be used for the specified basic block when its address is taken.
If other blocks were RAUW'd to this one, we may have to emit them as well, return the whole set.
Definition at line 259 of file MachineModuleInfo.cpp.
References llvm::BB, llvm::MMIAddrLabelMap::getAddrLabelSymbolToEmit(), and getContext().
Referenced by llvm::AsmPrinter::emitBasicBlockStart(), and getAddrLabelSymbol().
getContext() [1/2]
MCContext & llvm::MachineModuleInfo::getContext () inline
Definition at line 169 of file MachineModuleInfo.h.
References Context.
getContext() [2/2]
const MCContext & llvm::MachineModuleInfo::getContext () const inline
Definition at line 166 of file MachineModuleInfo.h.
References Context.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::DwarfCFIException::beginFunction(), llvm::DebugHandlerBase::beginInstruction(), buildDefCFAReg(), llvm::MachineModuleInfoWrapperPass::doInitialization(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMovesFullCFA(), llvm::X86AsmPrinter::emitEndOfAsmFile(), EmitInlineAsmStr(), emitNonLazyStubs(), llvm::AArch64FrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::X86AsmPrinter::emitStartOfAsmFile(), llvm::X86FrameLowering::enableShrinkWrapping(), llvm::DebugHandlerBase::endInstruction(), getAddrLabelSymbolToEmit(), llvm::TargetLoweringObjectFileXCOFF::getEHInfoTableSymbol(), llvm::PPCFrameLowering::inlineStackProbe(), recoverFramePointer(), and transformCallee().
getCurrentCallSite()
unsigned llvm::MachineModuleInfo::getCurrentCallSite () inline
Get the call site currently being processed, if any.
return zero if none.
Definition at line 260 of file MachineModuleInfo.h.
getMachineFunction()
MachineFunction * MachineModuleInfo::getMachineFunction (const Function & F) const
Returns the MachineFunction associated to IR function F if there is one, otherwise nullptr.
Definition at line 286 of file MachineModuleInfo.cpp.
References F, and I.
Referenced by llvm::AArch64InstrInfo::getOutliningType(), llvm::ARMBaseInstrInfo::getOutliningType(), and llvm::MIRParserImpl::parseMachineFunction().
getModule()
const Module * llvm::MachineModuleInfo::getModule () const inline
Definition at line 173 of file MachineModuleInfo.h.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::AMDGPUMachineModuleInfo::AMDGPUMachineModuleInfo(), llvm::ThunkInserter< Derived >::createThunkFunction(), llvm::DwarfDebug::DwarfDebug(), llvm::MachineInstr::emitError(), EmitInlineAsmStr(), llvm::WebAssemblyAsmPrinter::emitLinkage(), llvm::X86FrameLowering::emitPrologue(), llvm::WinCFGuard::endModule(), llvm::WinException::endModule(), llvm::X86TargetLowering::expandIndirectJTBranch(), llvm::AsmPrinter::getDataLayout(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), and llvm::X86AsmPrinter::runOnMachineFunction().
getObjFileInfo() [1/2]
template<typename Ty > Ty & llvm::MachineModuleInfo::getObjFileInfo () inline
Keep track of various per-module pieces of information for backends that would like to do so.
Definition at line 190 of file MachineModuleInfo.h.
Referenced by llvm::AsmPrinter::doFinalization(), llvm::ARMAsmPrinter::emitEndOfAsmFile(), llvm::WebAssemblyAsmPrinter::emitExternalDecls(), emitNonLazyStubs(), llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), and llvm::SparcELFTargetObjectFile::getTTypeGlobalReference().
getObjFileInfo() [2/2]
template<typename Ty > const Ty & llvm::MachineModuleInfo::getObjFileInfo () const inline
Definition at line 197 of file MachineModuleInfo.h.
getOrCreateMachineFunction()
MachineFunction & MachineModuleInfo::getOrCreateMachineFunction (Function & F)
Returns the MachineFunction constructed for the IR function F.
Creates a new MachineFunction if none exists yet.
Definition at line 291 of file MachineModuleInfo.cpp.
References F, llvm::TargetMachine::getSubtargetImpl(), and I.
Referenced by createFrameHelperMachineFunction(), llvm::ThunkInserter< Derived >::createThunkFunction(), llvm::MIRParserImpl::parseMachineFunction(), and llvm::AMDGPUResourceUsageAnalysis::runOnSCC().
getPersonalities()
const std::vector< const Function * > & llvm::MachineModuleInfo::getPersonalities () const inline
Return array of personality functions ever seen.
Definition at line 266 of file MachineModuleInfo.h.
Referenced by llvm::DwarfCFIException::endModule().
getTarget()
const LLVMTargetMachine & llvm::MachineModuleInfo::getTarget () const inline
Definition at line 164 of file MachineModuleInfo.h.
References TM.
Referenced by EmitInlineAsmStr(), and llvm::MIRParserImpl::parseMachineFunction().
hasDebugInfo()
bool llvm::MachineModuleInfo::hasDebugInfo () const inline
Returns true if valid debug info is present.
Definition at line 202 of file MachineModuleInfo.h.
Referenced by llvm::DebugHandlerBase::beginInstruction(), llvm::DwarfDebug::beginModule(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::M68kFrameLowering::eliminateCallFramePseudoInstr(), llvm::M68kFrameLowering::emitPrologue(), llvm::DebugHandlerBase::endInstruction(), llvm::CodeViewDebug::endModule(), llvm::DwarfDebug::endModule(), llvm::AsmPrinter::getFunctionCFISectionType(), hasDebugInfo(), needFuncLabelsForEHOrDebugInfo(), llvm::MachineFunction::needsFrameMoves(), and llvm::FastISel::selectIntrinsicCall().
hasNosplitStack()
bool llvm::MachineModuleInfo::hasNosplitStack () const inline
Definition at line 225 of file MachineModuleInfo.h.
Referenced by llvm::AsmPrinter::doFinalization().
hasSplitStack()
bool llvm::MachineModuleInfo::hasSplitStack () const inline
Definition at line 217 of file MachineModuleInfo.h.
Referenced by llvm::AsmPrinter::doFinalization().
initialize()
void MachineModuleInfo::initialize ()
Definition at line 196 of file MachineModuleInfo.cpp.
Referenced by llvm::MachineModuleInfoWrapperPass::doInitialization(), MachineModuleInfo(), and MachineModuleInfo().
invalidate()
bool llvm::MachineModuleInfo::invalidate (Module & , const PreservedAnalyses & , ModuleAnalysisManager::Invalidator &) inline
Definition at line 272 of file MachineModuleInfo.h.
setCurrentCallSite()
void llvm::MachineModuleInfo::setCurrentCallSite (unsigned Site) inline
Set the call site currently being processed.
Definition at line 256 of file MachineModuleInfo.h.
setDebugInfoAvailability()
void llvm::MachineModuleInfo::setDebugInfoAvailability (bool avail) inline
Definition at line 203 of file MachineModuleInfo.h.
Referenced by llvm::CodeViewDebug::beginModule(), and llvm::AsmPrinter::doInitialization().
setHasNosplitStack()
void llvm::MachineModuleInfo::setHasNosplitStack (bool b) inline
Definition at line 229 of file MachineModuleInfo.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), and llvm::X86FrameLowering::adjustForSegmentedStacks().
setHasSplitStack()
void llvm::MachineModuleInfo::setHasSplitStack (bool b) inline
Definition at line 221 of file MachineModuleInfo.h.
setUsesMorestackAddr()
void llvm::MachineModuleInfo::setUsesMorestackAddr (bool b) inline
Definition at line 213 of file MachineModuleInfo.h.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks().
setUsesMSVCFloatingPoint()
void llvm::MachineModuleInfo::setUsesMSVCFloatingPoint (bool b) inline
Definition at line 207 of file MachineModuleInfo.h.
Referenced by computeUsesMSVCFloatingPoint().
takeDeletedSymbolsForFunction()
void MachineModuleInfo::takeDeletedSymbolsForFunction (const Function * F, std::vector< MCSymbol * > & Result)
If the specified function has had any references to address-taken blocks generated, but the block got deleted, return the symbol now so we can emit it.
This prevents emitting a reference to a symbol that has no definition.
Definition at line 266 of file MachineModuleInfo.cpp.
References F, and takeDeletedSymbolsForFunction().
Referenced by takeDeletedSymbolsForFunction().
usesMorestackAddr()
bool llvm::MachineModuleInfo::usesMorestackAddr () const inline
Definition at line 209 of file MachineModuleInfo.h.
Referenced by llvm::AsmPrinter::doFinalization().
usesMSVCFloatingPoint()
bool llvm::MachineModuleInfo::usesMSVCFloatingPoint () const inline
Definition at line 205 of file MachineModuleInfo.h.
Referenced by computeUsesMSVCFloatingPoint(), and llvm::X86AsmPrinter::emitEndOfAsmFile().
Friends And Related Symbol Documentation
MachineModuleAnalysis
friend class MachineModuleAnalysis friend
Definition at line 79 of file MachineModuleInfo.h.
MachineModuleInfoWrapperPass
friend class MachineModuleInfoWrapperPass friend
Definition at line 78 of file MachineModuleInfo.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineModuleInfo.h
lib/CodeGen/MachineModuleInfo.cpp