LLVM: llvm::ARMSubtarget Class Reference
llvm::ARMSubtarget Class Reference
#include "Target/ARM/ARMSubtarget.h"
Public Types
enum ARMLdStMultipleTiming { DoubleIssue , DoubleIssueCheckUnalignedAccess , SingleIssue , SingleIssuePlusExtras }
What kind of timing do load multiple/store multiple instructions have.
Public Member Functions
ARMSubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const ARMBaseTargetMachine &TM, bool IsLittle, bool MinSize=false)
This constructor initializes the data members to match that of the specified triple.
unsigned getMaxInlineSizeThreshold () const
getMaxInlineSizeThreshold - Returns the maximum memset / memcpy size that still makes it profitable to inline the call.
unsigned getMaxMemcpyTPInlineSizeThreshold () const
getMaxMemcpyTPInlineSizeThreshold - Returns the maximum size that still makes it profitable to inline a llvm.memcpy as a Tail Predicated loop.
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
ARMSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
initializeSubtargetDependencies - Initializes using a CPU and feature string so that we can use initializer lists for subtarget initialization.
const ARMSelectionDAGInfo * getSelectionDAGInfo () const override
const ARMBaseInstrInfo * getInstrInfo () const override
const ARMTargetLowering * getTargetLowering () const override
const ARMFrameLowering * getFrameLowering () const override
const ARMBaseRegisterInfo * getRegisterInfo () const override
const CallLowering * getCallLowering () const override
InstructionSelector * getInstructionSelector () const override
const LegalizerInfo * getLegalizerInfo () const override
const RegisterBankInfo * getRegBankInfo () const override
void computeIssueWidth ()
bool hasV4TOps () const
bool hasV5TOps () const
bool hasV5TEOps () const
bool hasV6Ops () const
bool hasV6MOps () const
bool hasV6KOps () const
bool hasV6T2Ops () const
bool hasV7Ops () const
bool hasV8Ops () const
bool hasV8_1aOps () const
bool hasV8_2aOps () const
bool hasV8_3aOps () const
bool hasV8_4aOps () const
bool hasV8_5aOps () const
bool hasV8_6aOps () const
bool hasV8_7aOps () const
bool hasV8_8aOps () const
bool hasV9_0aOps () const
bool hasV9_1aOps () const
bool hasV9_2aOps () const
bool hasV9_3aOps () const
bool hasV8MBaselineOps () const
bool hasV8MMainlineOps () const
bool hasV8_1MMainlineOps () const
bool hasMVEIntegerOps () const
bool hasMVEFloatOps () const
bool hasCDEOps () const
bool hasFPRegs () const
bool hasFPRegs16 () const
bool hasFPRegs64 () const
bool hasARMOps () const
bool hasVFP2Base () const
bool hasVFP3Base () const
bool hasVFP4Base () const
bool hasFPARMv8Base () const
bool hasNEON () const
bool hasSHA2 () const
bool hasAES () const
bool hasCrypto () const
bool hasDotProd () const
bool hasCRC () const
bool hasRAS () const
bool hasLOB () const
bool hasPACBTI () const
bool hasVirtualization () const
bool useNEONForSinglePrecisionFP () const
bool hasDivideInThumbMode () const
bool hasDivideInARMMode () const
bool hasDataBarrier () const
bool hasFullDataBarrier () const
bool hasV7Clrex () const
bool hasAcquireRelease () const
bool hasAnyDataBarrier () const
bool useMulOps () const
bool useFPVMLx () const
bool useFPVFMx () const
bool useFPVFMx16 () const
bool useFPVFMx64 () const
bool hasVMLxForwarding () const
bool isFPBrccSlow () const
bool hasFP64 () const
bool hasPerfMon () const
bool hasTrustZone () const
bool has8MSecExt () const
bool hasZeroCycleZeroing () const
bool hasFPAO () const
bool isProfitableToUnpredicate () const
bool hasSlowVGETLNi32 () const
bool hasSlowVDUP32 () const
bool preferVMOVSR () const
bool preferISHSTBarriers () const
bool expandMLx () const
bool hasVMLxHazards () const
bool hasSlowOddRegister () const
bool hasSlowLoadDSubregister () const
bool useWideStrideVFP () const
bool hasMuxedUnits () const
bool dontWidenVMOVS () const
bool useSplatVFPToNeon () const
bool useNEONForFPMovs () const
bool checkVLDnAccessAlignment () const
bool nonpipelinedVFP () const
bool prefers32BitThumb () const
bool avoidCPSRPartialUpdate () const
bool cheapPredicableCPSRDef () const
bool avoidMOVsShifterOperand () const
bool hasRetAddrStack () const
bool hasBranchPredictor () const
bool hasMPExtension () const
bool hasDSP () const
bool useNaClTrap () const
bool useSjLjEH () const
bool hasSB () const
bool genLongCalls () const
bool genExecuteOnly () const
bool hasBaseDSP () const
bool hasFP16 () const
bool hasD32 () const
bool hasFullFP16 () const
bool hasFP16FML () const
bool hasBF16 () const
bool hasFuseAES () const
bool hasFuseLiterals () const
bool hasFusion () const
Return true if the CPU supports any kind of instruction fusion.
bool hasMatMulInt8 () const
const Triple & getTargetTriple () const
bool isTargetDarwin () const
bool isTargetIOS () const
bool isTargetWatchOS () const
bool isTargetWatchABI () const
bool isTargetLinux () const
bool isTargetNaCl () const
bool isTargetNetBSD () const
bool isTargetWindows () const
bool isTargetCOFF () const
bool isTargetELF () const
bool isTargetMachO () const
bool isTargetAEABI () const
bool isTargetGNUAEABI () const
bool isTargetMuslAEABI () const
bool isTargetEHABICompatible () const
bool isTargetHardFloat () const
bool isTargetAndroid () const
bool isXRaySupported () const override
bool isAPCS_ABI () const
bool isAAPCS_ABI () const
bool isAAPCS16_ABI () const
bool isROPI () const
bool isRWPI () const
bool useMachineScheduler () const
bool disablePostRAScheduler () const
bool useSoftFloat () const
bool isThumb () const
bool hasMinSize () const
bool isThumb1Only () const
bool isThumb2 () const
bool hasThumb2 () const
bool isMClass () const
bool isRClass () const
bool isAClass () const
bool isReadTPHard () const
bool isR9Reserved () const
MCPhysReg getFramePointerReg () const
bool splitFramePushPop (const MachineFunction &MF) const
Returns true if the frame setup is split into two separate pushes (first r0-r7,lr then r8-r11), principally so that the frame pointer is adjacent to lr.
bool useStride4VFPs () const
bool useMovt () const
bool supportsTailCall () const
bool allowsUnalignedMem () const
bool restrictIT () const
const std::string & getCPUString () const
bool isLittle () const
unsigned getMispredictionPenalty () const
bool enableMachineScheduler () const override
Returns true if machine scheduler should be enabled.
bool enablePostRAScheduler () const override
True for some subtargets at > -O0.
bool enablePostRAMachineScheduler () const override
True for some subtargets at > -O0.
bool enableSubRegLiveness () const override
Check whether this subtarget wants to use subregister liveness.
bool useAA () const override
Enable use of alias analysis during code generation (during MI scheduling, DAGCombine, etc.).
bool enableAtomicExpand () const override
const InstrItineraryData * getInstrItineraryData () const override
getInstrItins - Return the instruction itineraries based on subtarget selection.
Align getStackAlignment () const
getStackAlignment - Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
unsigned getMaxInterleaveFactor () const
unsigned getPartialUpdateClearance () const
ARMLdStMultipleTiming getLdStMultipleTiming () const
int getPreISelOperandLatencyAdjustment () const
bool isGVIndirectSymbol (const GlobalValue *GV) const
True if the GV will be accessed via an indirect symbol.
bool isGVInGOT (const GlobalValue *GV) const
Returns the constant pool modifier needed to access the GV.
bool useFastISel () const
True if fast-isel is used.
unsigned getReturnOpcode () const
Returns the correct return opcode for the current feature set.
bool allowPositionIndependentMovt () const
Allow movt+movw for PIC global address calculation.
unsigned getPrefLoopLogAlignment () const
unsigned getMVEVectorCostFactor (TargetTransformInfo::TargetCostKind CostKind) const
bool ignoreCSRForAllocationOrder (const MachineFunction &MF, unsigned PhysReg) const override
unsigned getGPRAllocationOrder (const MachineFunction &MF) const
bool fixCMSE_CVE_2021_35465 () const
bool hardenSlsRetBr () const
bool hardenSlsBlr () const
bool hardenSlsNoComdat () const
bool getNoBTIAtReturnTwice () const
bool isCortexA5 () const
bool isCortexA7 () const
bool isCortexA8 () const
bool isCortexA9 () const
bool isCortexA15 () const
bool isSwift () const
bool isCortexM3 () const
bool isCortexM7 () const
bool isLikeA9 () const
bool isCortexR5 () const
bool isKrait () const
Protected Types
enum ARMProcFamilyEnum {
Others , CortexA12 , CortexA15 , CortexA17 ,
CortexA32 , CortexA35 , CortexA5 , CortexA53 ,
CortexA55 , CortexA57 , CortexA7 , CortexA72 ,
CortexA73 , CortexA75 , CortexA76 , CortexA77 ,
CortexA78 , CortexA78C , CortexA710 , CortexA8 ,
CortexA9 , CortexM3 , CortexM7 , CortexR4 ,
CortexR4F , CortexR5 , CortexR52 , CortexR7 ,
CortexX1 , CortexX1C , Exynos , Krait ,
Kryo , NeoverseN1 , NeoverseN2 , NeoverseV1 ,
Swift
}
enum ARMProcClassEnum { None , AClass , MClass , RClass }
enum ARMArchEnum {
ARMv2 , ARMv2a , ARMv3 , ARMv3m ,
ARMv4 , ARMv4t , ARMv5 , ARMv5t ,
ARMv5te , ARMv5tej , ARMv6 , ARMv6k ,
ARMv6kz , ARMv6m , ARMv6sm , ARMv6t2 ,
ARMv7a , ARMv7em , ARMv7m , ARMv7r ,
ARMv7ve , ARMv81a , ARMv82a , ARMv83a ,
ARMv84a , ARMv85a , ARMv86a , ARMv87a ,
ARMv88a , ARMv8a , ARMv8mBaseline , ARMv8mMainline ,
ARMv8r , ARMv81mMainline , ARMv9a , ARMv91a ,
ARMv92a , ARMv93a
}
Protected Attributes
ARMProcFamilyEnum ARMProcFamily = Others
ARMProcFamily - ARM processor family: Cortex-A8, Cortex-A9, and others.
ARMProcClassEnum ARMProcClass = None
ARMProcClass - ARM processor class: None, AClass, RClass or MClass.
ARMArchEnum ARMArch = ARMv4t
ARMArch - ARM architecture.
bool HasV4TOps = false
HasV4TOps, HasV5TOps, HasV5TEOps, HasV6Ops, HasV6MOps, HasV6KOps, HasV6T2Ops, HasV7Ops, HasV8Ops - Specify whether target support specific ARM ISA variants.
bool HasV5TOps = false
bool HasV5TEOps = false
bool HasV6Ops = false
bool HasV6MOps = false
bool HasV6KOps = false
bool HasV6T2Ops = false
bool HasV7Ops = false
bool HasV8Ops = false
bool HasV8_1aOps = false
bool HasV8_2aOps = false
bool HasV8_3aOps = false
bool HasV8_4aOps = false
bool HasV8_5aOps = false
bool HasV8_6aOps = false
bool HasV8_8aOps = false
bool HasV8_7aOps = false
bool HasV9_0aOps = false
bool HasV9_1aOps = false
bool HasV9_2aOps = false
bool HasV9_3aOps = false
bool HasV8MBaselineOps = false
bool HasV8MMainlineOps = false
bool HasV8_1MMainlineOps = false
bool HasMVEIntegerOps = false
bool HasMVEFloatOps = false
bool HasCDEOps = false
bool HasVFPv2 = false
HasVFPv2, HasVFPv3, HasVFPv4, HasFPARMv8, HasNEON - Specify what floating point ISAs are supported.
bool HasVFPv3 = false
bool HasVFPv4 = false
bool HasFPARMv8 = false
bool HasNEON = false
bool HasFPRegs = false
bool HasFPRegs16 = false
bool HasFPRegs64 = false
bool HasVFPv2SP = false
Versions of the VFP flags restricted to single precision, or to 16 d-registers, or both.
bool HasVFPv3SP = false
bool HasVFPv4SP = false
bool HasFPARMv8SP = false
bool HasVFPv3D16 = false
bool HasVFPv4D16 = false
bool HasFPARMv8D16 = false
bool HasVFPv3D16SP = false
bool HasVFPv4D16SP = false
bool HasFPARMv8D16SP = false
bool HasDotProd = false
HasDotProd - True if the ARMv8.2A dot product instructions are supported.
bool UseNEONForSinglePrecisionFP = false
UseNEONForSinglePrecisionFP - if the NEONFP attribute has been specified.
bool UseMulOps = false
UseMulOps - True if non-microcoded fused integer multiply-add and multiply-subtract instructions should be used.
bool SlowFPVMLx = false
SlowFPVMLx - If the VFP2 / NEON instructions are available, indicates whether the FP VML[AS] instructions are slow (if so, don't use them).
bool SlowFPVFMx = false
SlowFPVFMx - If the VFP4 / NEON instructions are available, indicates whether the FP VFM[AS] instructions are slow (if so, don't use them).
bool HasVMLxForwarding = false
HasVMLxForwarding - If true, NEON has special multiplier accumulator forwarding to allow mul + mla being issued back to back.
bool SlowFPBrcc = false
SlowFPBrcc - True if floating point compare + branch is slow.
bool InThumbMode = false
InThumbMode - True if compiling for Thumb, false for ARM.
bool UseSoftFloat = false
UseSoftFloat - True if we're using software floating point features.
bool UseMISched = false
UseMISched - True if MachineScheduler should be used for this subtarget.
bool DisablePostRAScheduler = false
DisablePostRAScheduler - False if scheduling should happen again after register allocation.
bool HasThumb2 = false
HasThumb2 - True if Thumb2 instructions are supported.
bool NoARM = false
NoARM - True if subtarget does not support ARM mode execution.
bool ReserveR9 = false
ReserveR9 - True if R9 is not available as a general purpose register.
bool NoMovt = false
NoMovt - True if MOVT / MOVW pairs are not used for materialization of 32-bit imms (including global addresses).
bool SupportsTailCall = false
SupportsTailCall - True if the OS supports tail call.
bool HasFP16 = false
HasFP16 - True if subtarget supports half-precision FP conversions.
bool HasFullFP16 = false
HasFullFP16 - True if subtarget supports half-precision FP operations.
bool HasFP16FML = false
HasFP16FML - True if subtarget supports half-precision FP fml operations.
bool HasBF16 = false
HasBF16 - True if subtarget supports BFloat16 floating point operations.
bool HasMatMulInt8 = false
HasMatMulInt8 - True if subtarget supports 8-bit integer matrix multiply.
bool HasD32 = false
HasD32 - True if subtarget has the full 32 double precision FP registers for VFPv3.
bool HasHardwareDivideInThumb = false
HasHardwareDivide - True if subtarget supports [su]div in Thumb mode.
bool HasHardwareDivideInARM = false
HasHardwareDivideInARM - True if subtarget supports [su]div in ARM mode.
bool HasDataBarrier = false
HasDataBarrier - True if the subtarget supports DMB / DSB data barrier instructions.
bool HasFullDataBarrier = false
HasFullDataBarrier - True if the subtarget supports DFB data barrier instruction.
bool HasV7Clrex = false
HasV7Clrex - True if the subtarget supports CLREX instructions.
bool HasAcquireRelease = false
HasAcquireRelease - True if the subtarget supports v8 atomics (LDA/LDAEX etc) instructions.
bool Pref32BitThumb = false
Pref32BitThumb - If true, codegen would prefer 32-bit Thumb instructions over 16-bit ones.
bool AvoidCPSRPartialUpdate = false
AvoidCPSRPartialUpdate - If true, codegen would avoid using instructions that partially update CPSR and add false dependency on the previous CPSR setting instruction.
bool CheapPredicableCPSRDef = false
CheapPredicableCPSRDef - If true, disable +1 predication cost for instructions updating CPSR.
bool AvoidMOVsShifterOperand = false
AvoidMOVsShifterOperand - If true, codegen should avoid using flag setting movs with shifter operand (i.e.
bool HasRetAddrStack = false
HasRetAddrStack - Some processors perform return stack prediction.
bool HasBranchPredictor = true
HasBranchPredictor - True if the subtarget has a branch predictor.
bool HasMPExtension = false
HasMPExtension - True if the subtarget supports Multiprocessing extension (ARMv7 only).
bool HasVirtualization = false
HasVirtualization - True if the subtarget supports the Virtualization extension.
bool HasFP64 = false
HasFP64 - If true, the floating point unit supports double precision.
bool HasPerfMon = false
If true, the processor supports the Performance Monitor Extensions.
bool HasTrustZone = false
HasTrustZone - if true, processor supports TrustZone security extensions.
bool Has8MSecExt = false
Has8MSecExt - if true, processor supports ARMv8-M Security Extensions.
bool HasSHA2 = false
HasSHA2 - if true, processor supports SHA1 and SHA256.
bool HasAES = false
HasAES - if true, processor supports AES.
bool HasCrypto = false
HasCrypto - if true, processor supports Cryptography extensions.
bool HasCRC = false
HasCRC - if true, processor supports CRC instructions.
bool HasRAS = false
HasRAS - if true, the processor supports RAS extensions.
bool HasLOB = false
HasLOB - if true, the processor supports the Low Overhead Branch extension.
bool HasPACBTI = false
bool HasZeroCycleZeroing = false
If true, the instructions "vmov.i32 d0, #0" and "vmov.i32 q0, #0" are particularly effective at zeroing a VFP register.
bool HasFPAO = false
HasFPAO - if true, processor does positive address offset computation faster.
bool HasFuseAES = false
HasFuseAES - if true, processor executes back to back AES instruction pairs faster.
bool HasFuseLiterals = false
HasFuseLiterals - if true, processor executes back to back bottom and top halves of literal generation faster.
bool IsProfitableToUnpredicate = false
If true, if conversion may decide to leave some instructions unpredicated.
bool HasSlowVGETLNi32 = false
If true, VMOV will be favored over VGETLNi32.
bool HasSlowVDUP32 = false
If true, VMOV will be favored over VDUP.
bool PreferVMOVSR = false
If true, VMOVSR will be favored over VMOVDRR.
bool PreferISHST = false
If true, ISHST barriers will be used for Release semantics.
bool SlowOddRegister = false
If true, a VLDM/VSTM starting with an odd register number is considered to take more microops than single VLDRS/VSTRS.
bool SlowLoadDSubregister = false
If true, loading into a D subregister will be penalized.
bool UseWideStrideVFP = false
If true, use a wider stride when allocating VFP registers.
bool HasMuxedUnits = false
If true, the AGU and NEON/FPU units are multiplexed.
bool DontWidenVMOVS = false
If true, VMOVS will never be widened to VMOVD.
bool SplatVFPToNeon = false
If true, splat a register between VFP and NEON instructions.
bool ExpandMLx = false
If true, run the MLx expansion pass.
bool HasVMLxHazards = false
If true, VFP/NEON VMLA/VMLS have special RAW hazards.
bool ReadTPHard = false
bool UseNEONForFPMovs = false
If true, VMOVRS, VMOVSR and VMOVS will be converted from VFP to NEON.
bool CheckVLDnAlign = false
If true, VLDn instructions take an extra cycle for unaligned accesses.
bool NonpipelinedVFP = false
If true, VFP instructions are not pipelined.
bool StrictAlign = false
StrictAlign - If true, the subtarget disallows unaligned memory accesses for some types.
bool RestrictIT = false
RestrictIT - If true, the subtarget disallows generation of deprecated IT blocks to conform to ARMv8 rule.
bool HasDSP = false
HasDSP - If true, the subtarget supports the DSP (saturating arith and such) instructions.
bool UseNaClTrap = false
NaCl TRAP instruction is generated instead of the regular TRAP.
bool GenLongCalls = false
Generate calls via indirect call instructions.
bool GenExecuteOnly = false
Generate code that does not contain data access to code sections.
bool UnsafeFPMath = false
Target machine allowed unsafe FP math (such as use of NEON fp)
bool UseSjLjEH = false
UseSjLjEH - If true, the target uses SjLj exception handling (e.g. iOS).
bool HasSB = false
Has speculation barrier.
bool NegativeImmediates = true
Implicitly convert an instruction to a different one if its immediates cannot be encoded.
bool FixCMSE_CVE_2021_35465 = false
Mitigate against the cve-2021-35465 security vulnurability.
bool HardenSlsRetBr = false
Harden against Straight Line Speculation for Returns and Indirect Branches.
bool HardenSlsBlr = false
Harden against Straight Line Speculation for indirect calls.
bool HardenSlsNoComdat = false
Generate thunk code for SLS mitigation in the normal text section.
Align stackAlignment = Align(4)
stackAlignment - The minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function.
std::string CPUString
CPUString - String name of used CPU.
unsigned MaxInterleaveFactor = 1
unsigned PartialUpdateClearance = 0
Clearance before partial register updates (in number of instructions)
ARMLdStMultipleTiming LdStMultipleTiming = SingleIssue
What kind of timing do load multiple/store multiple have (double issue, single issue etc).
int PreISelOperandLatencyAdjustment = 2
The adjustment that we need to apply to get the operand latency from the operand cycle returned by the itinerary data for pre-ISel operands.
unsigned PrefLoopLogAlignment = 0
What alignment is preferred for loop bodies, in log2(bytes).
unsigned MVEVectorCostFactor = 0
The cost factor for MVE instructions, representing the multiple beats an.
bool OptMinSize = false
OptMinSize - True if we're optimising for minimum code size, equal to the function attribute.
bool IsLittle
IsLittle - The target is Little Endian.
Triple TargetTriple
TargetTriple - What processor and OS we're targeting.
MCSchedModel SchedModel
SchedModel - Processor specific instruction costs.
InstrItineraryData InstrItins
Selected instruction itineraries (one entry per itinerary class.)
bool NoBTIAtReturnTwice = false
NoBTIAtReturnTwice - Don't place a BTI instruction after return-twice constructs (setjmp)
const TargetOptions & Options
Options passed via command line that could influence the target.
const ARMBaseTargetMachine & TM
Detailed Description
Definition at line 47 of file ARMSubtarget.h.
Member Enumeration Documentation
ARMArchEnum
enum llvm::ARMSubtarget::ARMArchEnum protected
Enumerator
ARMv2
ARMv2a
ARMv3
ARMv3m
ARMv4
ARMv4t
ARMv5
ARMv5t
ARMv5te
ARMv5tej
ARMv6
ARMv6k
ARMv6kz
ARMv6m
ARMv6sm
ARMv6t2
ARMv7a
ARMv7em
ARMv7m
ARMv7r
ARMv7ve
ARMv81a
ARMv82a
ARMv83a
ARMv84a
ARMv85a
ARMv86a
ARMv87a
ARMv88a
ARMv8a
ARMv8mBaseline
ARMv8mMainline
ARMv8r
ARMv81mMainline
ARMv9a
ARMv91a
ARMv92a
ARMv93a
Definition at line 96 of file ARMSubtarget.h.
ARMLdStMultipleTiming
enum llvm::ARMSubtarget::ARMLdStMultipleTiming
What kind of timing do load multiple/store multiple instructions have.
Enumerator
DoubleIssue
Can load/store 2 registers/cycle.
DoubleIssueCheckUnalignedAccess
Can load/store 2 registers/cycle, but needs an extra cycle if the access is not 64-bit aligned.
SingleIssue
Can load/store 1 register/cycle.
SingleIssuePlusExtras
Can load/store 1 register/cycle, but needs an extra cycle for address computation and potentially also for register writeback.
Definition at line 139 of file ARMSubtarget.h.
ARMProcClassEnum
enum llvm::ARMSubtarget::ARMProcClassEnum protected
Enumerator
None
AClass
MClass
RClass
Definition at line 89 of file ARMSubtarget.h.
ARMProcFamilyEnum
enum llvm::ARMSubtarget::ARMProcFamilyEnum protected
Enumerator
Others
CortexA12
CortexA15
CortexA17
CortexA32
CortexA35
CortexA5
CortexA53
CortexA55
CortexA57
CortexA7
CortexA72
CortexA73
CortexA75
CortexA76
CortexA77
CortexA78
CortexA78C
CortexA710
CortexA8
CortexA9
CortexM3
CortexM7
CortexR4
CortexR4F
CortexR5
CortexR52
CortexR7
CortexX1
CortexX1C
Exynos
Krait
Kryo
NeoverseN1
NeoverseN2
NeoverseV1
Swift
Definition at line 49 of file ARMSubtarget.h.
Constructor & Destructor Documentation
ARMSubtarget()
ARMSubtarget::ARMSubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const ARMBaseTargetMachine & TM, bool IsLittle, bool MinSize = false)
This constructor initializes the data members to match that of the specified triple.
Definition at line 96 of file ARMSubtarget.cpp.
References llvm::createARMInstructionSelector(), getRegisterInfo(), getTargetLowering(), and TM.
Member Function Documentation
allowPositionIndependentMovt()
bool llvm::ARMSubtarget::allowPositionIndependentMovt () const inline
Allow movt+movw for PIC global address calculation.
ELF does not have GOT relocations for movt+movw. ROPI does not use GOT.
Definition at line 943 of file ARMSubtarget.h.
References isROPI(), and isTargetELF().
allowsUnalignedMem()
bool llvm::ARMSubtarget::allowsUnalignedMem () const inline
Definition at line 868 of file ARMSubtarget.h.
References StrictAlign.
Referenced by llvm::ARMTargetLowering::allowsMisalignedMemoryAccesses().
avoidCPSRPartialUpdate()
bool llvm::ARMSubtarget::avoidCPSRPartialUpdate () const inline
Definition at line 738 of file ARMSubtarget.h.
References AvoidCPSRPartialUpdate.
avoidMOVsShifterOperand()
bool llvm::ARMSubtarget::avoidMOVsShifterOperand () const inline
Definition at line 740 of file ARMSubtarget.h.
References AvoidMOVsShifterOperand.
cheapPredicableCPSRDef()
bool llvm::ARMSubtarget::cheapPredicableCPSRDef () const inline
Definition at line 739 of file ARMSubtarget.h.
References CheapPredicableCPSRDef.
checkVLDnAccessAlignment()
bool llvm::ARMSubtarget::checkVLDnAccessAlignment () const inline
Definition at line 735 of file ARMSubtarget.h.
References CheckVLDnAlign.
Referenced by adjustDefLatency(), and llvm::ARMBaseInstrInfo::getOperandLatency().
computeIssueWidth()
void llvm::ARMSubtarget::computeIssueWidth ()
disablePostRAScheduler()
bool llvm::ARMSubtarget::disablePostRAScheduler () const inline
Definition at line 828 of file ARMSubtarget.h.
References DisablePostRAScheduler.
Referenced by enablePostRAMachineScheduler(), and enablePostRAScheduler().
dontWidenVMOVS()
bool llvm::ARMSubtarget::dontWidenVMOVS () const inline
Definition at line 732 of file ARMSubtarget.h.
References DontWidenVMOVS.
Referenced by llvm::ARMBaseInstrInfo::expandPostRAPseudo().
enableAtomicExpand()
bool ARMSubtarget::enableAtomicExpand () const override
Definition at line 420 of file ARMSubtarget.cpp.
References hasAnyDataBarrier().
enableMachineScheduler()
bool ARMSubtarget::enableMachineScheduler () const override
Returns true if machine scheduler should be enabled.
Definition at line 381 of file ARMSubtarget.cpp.
References hasMinSize(), isMClass(), and useMachineScheduler().
Referenced by enablePostRAMachineScheduler(), and enablePostRAScheduler().
enablePostRAMachineScheduler()
bool ARMSubtarget::enablePostRAMachineScheduler () const override
True for some subtargets at > -O0.
Definition at line 412 of file ARMSubtarget.cpp.
References disablePostRAScheduler(), enableMachineScheduler(), and isThumb1Only().
enablePostRAScheduler()
bool ARMSubtarget::enablePostRAScheduler () const override
True for some subtargets at > -O0.
Definition at line 403 of file ARMSubtarget.cpp.
References disablePostRAScheduler(), enableMachineScheduler(), and isThumb1Only().
enableSubRegLiveness()
bool ARMSubtarget::enableSubRegLiveness () const override
Check whether this subtarget wants to use subregister liveness.
Definition at line 394 of file ARMSubtarget.cpp.
References EnableSubRegLiveness, and hasMVEIntegerOps().
expandMLx()
bool llvm::ARMSubtarget::expandMLx () const inline
Definition at line 726 of file ARMSubtarget.h.
References ExpandMLx.
fixCMSE_CVE_2021_35465()
bool llvm::ARMSubtarget::fixCMSE_CVE_2021_35465 () const inline
Definition at line 960 of file ARMSubtarget.h.
References FixCMSE_CVE_2021_35465.
genExecuteOnly()
bool llvm::ARMSubtarget::genExecuteOnly () const inline
Definition at line 749 of file ARMSubtarget.h.
References GenExecuteOnly.
Referenced by llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::ARMAsmPrinter::emitInstruction(), isExecuteOnlyFunction(), llvm::ARMAsmPrinter::lowerOperand(), llvm::ARMAsmPrinter::printOperand(), and useMovt().
genLongCalls()
bool llvm::ARMSubtarget::genLongCalls () const inline
Definition at line 748 of file ARMSubtarget.h.
References GenLongCalls.
Referenced by llvm::ARMCallLowering::lowerCall().
getCallLowering()
const CallLowering * ARMSubtarget::getCallLowering () const override
Definition at line 127 of file ARMSubtarget.cpp.
getCPUString()
const std::string & llvm::ARMSubtarget::getCPUString () const inline
Definition at line 872 of file ARMSubtarget.h.
References CPUString.
getFrameLowering()
const ARMFrameLowering * llvm::ARMSubtarget::getFrameLowering () const inline override
Definition at line 592 of file ARMSubtarget.h.
Referenced by llvm::ThumbRegisterInfo::eliminateFrameIndex(), and llvm::ARMFrameLowering::emitPrologue().
getFramePointerReg()
MCPhysReg llvm::ARMSubtarget::getFramePointerReg () const inline
Definition at line 844 of file ARMSubtarget.h.
References isTargetDarwin(), isTargetWindows(), and isThumb().
Referenced by llvm::ARMBaseRegisterInfo::canRealignStack(), llvm::ARMAsmPrinter::emitInstruction(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::ARMBaseRegisterInfo::getReservedRegs(), llvm::ARMBaseRegisterInfo::isInlineAsmReadOnlyReg(), and splitFramePushPop().
getGPRAllocationOrder()
unsigned ARMSubtarget::getGPRAllocationOrder (const MachineFunction & MF) const
Definition at line 453 of file ARMSubtarget.cpp.
References llvm::MachineFunction::getFunction(), llvm::Function::hasMinSize(), isThumb1Only(), and isThumb2().
getInstrInfo()
const ARMBaseInstrInfo * llvm::ARMSubtarget::getInstrInfo () const inline override
Definition at line 584 of file ARMSubtarget.h.
Referenced by llvm::ARMTargetLowering::AdjustInstrPostInstrSelection(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::ARMFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), emitThumb1LoadConstPool(), llvm::ARMTargetLowering::getSchedulingPreference(), llvm::ARMCallLowering::lowerCall(), llvm::ThumbRegisterInfo::resolveFrameIndex(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), and llvm::Thumb1FrameLowering::spillCalleeSavedRegisters().
getInstrItineraryData()
const InstrItineraryData * llvm::ARMSubtarget::getInstrItineraryData () const inline override
getInstrItins - Return the instruction itineraries based on subtarget selection.
Definition at line 899 of file ARMSubtarget.h.
References InstrItins.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
getInstructionSelector()
InstructionSelector * ARMSubtarget::getInstructionSelector () const override
Definition at line 131 of file ARMSubtarget.cpp.
getLdStMultipleTiming()
ARMLdStMultipleTiming llvm::ARMSubtarget::getLdStMultipleTiming () const inline
Definition at line 912 of file ARMSubtarget.h.
References LdStMultipleTiming.
Referenced by llvm::ARMBaseInstrInfo::getNumMicroOps().
getLegalizerInfo()
const LegalizerInfo * ARMSubtarget::getLegalizerInfo () const override
Definition at line 135 of file ARMSubtarget.cpp.
getMaxInlineSizeThreshold()
unsigned llvm::ARMSubtarget::getMaxInlineSizeThreshold () const inline
getMaxInlineSizeThreshold - Returns the maximum memset / memcpy size that still makes it profitable to inline the call.
Definition at line 562 of file ARMSubtarget.h.
Referenced by llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), and shouldGenerateInlineTPLoop().
getMaxInterleaveFactor()
unsigned llvm::ARMSubtarget::getMaxInterleaveFactor () const inline
Definition at line 908 of file ARMSubtarget.h.
References MaxInterleaveFactor.
getMaxMemcpyTPInlineSizeThreshold()
unsigned llvm::ARMSubtarget::getMaxMemcpyTPInlineSizeThreshold () const inline
getMaxMemcpyTPInlineSizeThreshold - Returns the maximum size that still makes it profitable to inline a llvm.memcpy as a Tail Predicated loop.
This threshold should only be used for constant size inputs.
Definition at line 570 of file ARMSubtarget.h.
Referenced by shouldGenerateInlineTPLoop().
getMispredictionPenalty()
unsigned ARMSubtarget::getMispredictionPenalty () const
Definition at line 377 of file ARMSubtarget.cpp.
References llvm::MCSchedModel::MispredictPenalty, and SchedModel.
Referenced by llvm::ARMBaseInstrInfo::isProfitableToIfCvt().
getMVEVectorCostFactor()
unsigned llvm::ARMSubtarget::getMVEVectorCostFactor (TargetTransformInfo::TargetCostKind CostKind) const inline
Definition at line 950 of file ARMSubtarget.h.
References CostKind, MVEVectorCostFactor, and llvm::TargetTransformInfo::TCK_CodeSize.
Referenced by llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::ARMTTIImpl::getArithmeticReductionCost(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::ARMTTIImpl::getExtendedAddReductionCost(), llvm::ARMTTIImpl::getGatherScatterOpCost(), llvm::ARMTTIImpl::getInterleavedMemoryOpCost(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::ARMTTIImpl::getMaskedMemoryOpCost(), llvm::ARMTTIImpl::getMemoryOpCost(), and llvm::ARMTTIImpl::getShuffleCost().
getNoBTIAtReturnTwice()
bool llvm::ARMSubtarget::getNoBTIAtReturnTwice () const inline
Definition at line 966 of file ARMSubtarget.h.
References NoBTIAtReturnTwice.
getPartialUpdateClearance()
unsigned llvm::ARMSubtarget::getPartialUpdateClearance () const inline
Definition at line 910 of file ARMSubtarget.h.
References PartialUpdateClearance.
Referenced by llvm::ARMBaseInstrInfo::getPartialRegUpdateClearance().
getPrefLoopLogAlignment()
unsigned llvm::ARMSubtarget::getPrefLoopLogAlignment () const inline
Definition at line 947 of file ARMSubtarget.h.
References PrefLoopLogAlignment.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
getPreISelOperandLatencyAdjustment()
int llvm::ARMSubtarget::getPreISelOperandLatencyAdjustment () const inline
Definition at line 916 of file ARMSubtarget.h.
References PreISelOperandLatencyAdjustment.
Referenced by llvm::ARMBaseInstrInfo::getOperandLatency().
getRegBankInfo()
const RegisterBankInfo * ARMSubtarget::getRegBankInfo () const override
Definition at line 139 of file ARMSubtarget.cpp.
Referenced by llvm::ARMCallLowering::lowerCall().
getRegisterInfo()
const ARMBaseRegisterInfo * llvm::ARMSubtarget::getRegisterInfo () const inline override
Definition at line 596 of file ARMSubtarget.h.
Referenced by ARMSubtarget(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), and llvm::ARMCallLowering::lowerCall().
getReturnOpcode()
unsigned llvm::ARMSubtarget::getReturnOpcode () const inline
Returns the correct return opcode for the current feature set.
Use BX if available to allow mixing thumb/arm code, but fall back to plain mov pc,lr on ARMv4.
Definition at line 932 of file ARMSubtarget.h.
References hasV4TOps(), and isThumb().
Referenced by llvm::ARMBaseInstrInfo::buildOutlinedFrame().
getSelectionDAGInfo()
const ARMSelectionDAGInfo * llvm::ARMSubtarget::getSelectionDAGInfo () const inline override
Definition at line 580 of file ARMSubtarget.h.
getStackAlignment()
Align llvm::ARMSubtarget::getStackAlignment () const inline
getStackAlignment - Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
Definition at line 906 of file ARMSubtarget.h.
References stackAlignment.
Referenced by llvm::ARMBaseInstrInfo::getOutliningType().
getTargetLowering()
const ARMTargetLowering * llvm::ARMSubtarget::getTargetLowering () const inline override
Definition at line 588 of file ARMSubtarget.h.
Referenced by AlignBlocks(), ARMSubtarget(), llvm::ARMSelectionDAGInfo::EmitSpecializedLibcall(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCallPreservedMask(), and PerformXORCombine().
getTargetTriple()
const Triple & llvm::ARMSubtarget::getTargetTriple () const inline
Definition at line 770 of file ARMSubtarget.h.
References TargetTriple.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMTargetLowering::getSDagStackGuard(), llvm::ARMTargetLowering::getSSPStackGuardCheck(), and llvm::ARMTargetLowering::insertSSPDeclarations().
hardenSlsBlr()
bool llvm::ARMSubtarget::hardenSlsBlr () const inline
Definition at line 963 of file ARMSubtarget.h.
References HardenSlsBlr.
Referenced by llvm::getBLXOpcode(), llvm::getBLXpredOpcode(), and llvm::gettBLXrOpcode().
hardenSlsNoComdat()
bool llvm::ARMSubtarget::hardenSlsNoComdat () const inline
Definition at line 964 of file ARMSubtarget.h.
References HardenSlsNoComdat.
hardenSlsRetBr()
bool llvm::ARMSubtarget::hardenSlsRetBr () const inline
Definition at line 962 of file ARMSubtarget.h.
References HardenSlsRetBr.
has8MSecExt()
bool llvm::ARMSubtarget::has8MSecExt () const inline
Definition at line 718 of file ARMSubtarget.h.
References Has8MSecExt.
hasAcquireRelease()
bool llvm::ARMSubtarget::hasAcquireRelease () const inline
Definition at line 700 of file ARMSubtarget.h.
References HasAcquireRelease.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
hasAES()
bool llvm::ARMSubtarget::hasAES () const inline
Definition at line 682 of file ARMSubtarget.h.
References HasAES.
hasAnyDataBarrier()
bool llvm::ARMSubtarget::hasAnyDataBarrier () const inline
Definition at line 702 of file ARMSubtarget.h.
References HasDataBarrier, hasV6Ops(), and isThumb().
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), and enableAtomicExpand().
hasARMOps()
bool llvm::ARMSubtarget::hasARMOps () const inline
Definition at line 674 of file ARMSubtarget.h.
References NoARM.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), and isXRaySupported().
hasBaseDSP()
bool llvm::ARMSubtarget::hasBaseDSP () const inline
Definition at line 750 of file ARMSubtarget.h.
References hasDSP(), hasV5TEOps(), and isThumb().
Referenced by AddCombineTo64BitSMLAL16(), and llvm::ARMTargetLowering::ARMTargetLowering().
hasBF16()
bool llvm::ARMSubtarget::hasBF16 () const inline
Definition at line 761 of file ARMSubtarget.h.
References HasBF16.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
hasBranchPredictor()
bool llvm::ARMSubtarget::hasBranchPredictor () const inline
Definition at line 742 of file ARMSubtarget.h.
References HasBranchPredictor.
Referenced by llvm::ARMTTIImpl::getUnrollingPreferences(), and llvm::ARMBaseInstrInfo::isProfitableToIfCvt().
hasCDEOps()
bool llvm::ARMSubtarget::hasCDEOps () const inline
Definition at line 653 of file ARMSubtarget.h.
References HasCDEOps.
hasCRC()
bool llvm::ARMSubtarget::hasCRC () const inline
Definition at line 685 of file ARMSubtarget.h.
References HasCRC.
hasCrypto()
bool llvm::ARMSubtarget::hasCrypto () const inline
Definition at line 683 of file ARMSubtarget.h.
References HasCrypto.
hasD32()
bool llvm::ARMSubtarget::hasD32 () const inline
Definition at line 758 of file ARMSubtarget.h.
References HasD32.
Referenced by llvm::ARMBaseRegisterInfo::getReservedRegs().
hasDataBarrier()
bool llvm::ARMSubtarget::hasDataBarrier () const inline
Definition at line 697 of file ARMSubtarget.h.
References HasDataBarrier.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), LowerATOMIC_FENCE(), and llvm::ARMTargetLowering::makeDMB().
hasDivideInARMMode()
bool llvm::ARMSubtarget::hasDivideInARMMode () const inline
Definition at line 696 of file ARMSubtarget.h.
References HasHardwareDivideInARM.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
hasDivideInThumbMode()
bool llvm::ARMSubtarget::hasDivideInThumbMode () const inline
Definition at line 695 of file ARMSubtarget.h.
References HasHardwareDivideInThumb.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
hasDotProd()
bool llvm::ARMSubtarget::hasDotProd () const inline
Definition at line 684 of file ARMSubtarget.h.
References HasDotProd.
hasDSP()
bool llvm::ARMSubtarget::hasDSP () const inline
Definition at line 744 of file ARMSubtarget.h.
References HasDSP.
Referenced by AddCombineTo64bitMLAL(), AddCombineTo64bitUMAAL(), llvm::ARMTargetLowering::ARMTargetLowering(), hasBaseDSP(), LowerADDSUBSAT(), PerformORCombineToBFI(), PerformORCombineToSMULWBT(), and PerformUMLALCombine().
hasFP16()
bool llvm::ARMSubtarget::hasFP16 () const inline
Definition at line 757 of file ARMSubtarget.h.
References HasFP16.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
hasFP16FML()
bool llvm::ARMSubtarget::hasFP16FML () const inline
Definition at line 760 of file ARMSubtarget.h.
References HasFP16FML.
hasFP64()
bool llvm::ARMSubtarget::hasFP64 () const inline
Definition at line 715 of file ARMSubtarget.h.
References HasFP64.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::expandPostRAPseudo(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::ARMTargetLowering::isFPImmLegal(), llvm::ARMTTIImpl::isLoweredToCall(), LowerFP_TO_INT_SAT(), llvm::ARMTTIImpl::maybeLoweredToCall(), PerformVMOVRRDCombine(), llvm::ARMTargetLowering::shouldConvertFpToSat(), and useFPVFMx64().
hasFPAO()
bool llvm::ARMSubtarget::hasFPAO () const inline
Definition at line 720 of file ARMSubtarget.h.
References HasFPAO.
Referenced by llvm::ARMTargetLowering::getScalingFactorCost().
hasFPARMv8Base()
bool llvm::ARMSubtarget::hasFPARMv8Base () const inline
Definition at line 679 of file ARMSubtarget.h.
References HasFPARMv8D16SP.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMTTIImpl::isLoweredToCall(), and llvm::ARMTTIImpl::maybeLoweredToCall().
hasFPRegs()
bool llvm::ARMSubtarget::hasFPRegs () const inline
Definition at line 654 of file ARMSubtarget.h.
References HasFPRegs.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
hasFPRegs16()
bool llvm::ARMSubtarget::hasFPRegs16 () const inline
Definition at line 655 of file ARMSubtarget.h.
References HasFPRegs16.
Referenced by isLegalT2AddressImmediate().
hasFPRegs64()
bool llvm::ARMSubtarget::hasFPRegs64 () const inline
Definition at line 656 of file ARMSubtarget.h.
References HasFPRegs64.
hasFullDataBarrier()
bool llvm::ARMSubtarget::hasFullDataBarrier () const inline
Definition at line 698 of file ARMSubtarget.h.
References HasFullDataBarrier.
hasFullFP16()
bool llvm::ARMSubtarget::hasFullFP16 () const inline
Definition at line 759 of file ARMSubtarget.h.
References HasFullFP16.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::ARMTargetLowering::isFNegFree(), llvm::ARMTargetLowering::isFPImmLegal(), llvm::ARMTTIImpl::isLoweredToCall(), LowerFP_TO_INT_SAT(), llvm::ARMTTIImpl::maybeLoweredToCall(), and useFPVFMx16().
hasFuseAES()
bool llvm::ARMSubtarget::hasFuseAES () const inline
Definition at line 763 of file ARMSubtarget.h.
References HasFuseAES.
Referenced by hasFusion().
hasFuseLiterals()
bool llvm::ARMSubtarget::hasFuseLiterals () const inline
Definition at line 764 of file ARMSubtarget.h.
References HasFuseLiterals.
Referenced by hasFusion().
hasFusion()
bool llvm::ARMSubtarget::hasFusion () const inline
Return true if the CPU supports any kind of instruction fusion.
Definition at line 766 of file ARMSubtarget.h.
References hasFuseAES(), and hasFuseLiterals().
hasLOB()
bool llvm::ARMSubtarget::hasLOB () const inline
Definition at line 687 of file ARMSubtarget.h.
References HasLOB.
Referenced by AlignBlocks(), llvm::ARMTargetLowering::ARMTargetLowering(), and llvm::ARMTTIImpl::isHardwareLoopProfitable().
hasMatMulInt8()
bool llvm::ARMSubtarget::hasMatMulInt8 () const inline
Definition at line 768 of file ARMSubtarget.h.
References HasMatMulInt8.
hasMinSize()
bool llvm::ARMSubtarget::hasMinSize () const inline
Definition at line 831 of file ARMSubtarget.h.
References OptMinSize.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), enableMachineScheduler(), llvm::ARMTargetLowering::shouldExpandShift(), and llvm::tryFoldSPUpdateIntoPushPop().
hasMPExtension()
bool llvm::ARMSubtarget::hasMPExtension () const inline
Definition at line 743 of file ARMSubtarget.h.
References HasMPExtension.
Referenced by LowerPREFETCH().
hasMuxedUnits()
bool llvm::ARMSubtarget::hasMuxedUnits () const inline
Definition at line 731 of file ARMSubtarget.h.
References HasMuxedUnits.
hasMVEFloatOps()
bool llvm::ARMSubtarget::hasMVEFloatOps () const inline
Definition at line 652 of file ARMSubtarget.h.
References HasMVEFloatOps.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::ARMTTIImpl::getMemoryOpCost(), llvm::ARMTargetLowering::getSetCCResultType(), isLegalT2AddressImmediate(), LowerFP_TO_INT_SAT(), PerformFAddVSelectCombine(), and llvm::ARMTargetLowering::shouldConvertFpToSat().
hasMVEIntegerOps()
bool llvm::ARMSubtarget::hasMVEIntegerOps () const inline
Definition at line 651 of file ARMSubtarget.h.
References HasMVEIntegerOps.
Referenced by llvm::ARMTargetLowering::allowsMisalignedMemoryAccesses(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMTTIImpl::emitGetActiveLaneMask(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), enableSubRegLiveness(), llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::ARMTTIImpl::getArithmeticReductionCost(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCFInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::ARMTTIImpl::getExtendedAddReductionCost(), llvm::ARMTTIImpl::getGatherScatterOpCost(), llvm::ARMTTIImpl::getInterleavedMemoryOpCost(), llvm::ARMTTIImpl::getIntrinsicInstrCost(), llvm::ARMBaseRegisterInfo::getLargestLegalSuperClass(), llvm::ARMTTIImpl::getMaskedMemoryOpCost(), llvm::ARMTargetLowering::getMaxSupportedInterleaveFactor(), llvm::ARMTTIImpl::getMemoryOpCost(), llvm::ARMTargetLowering::getPostIndexedAddressParts(), llvm::ARMTTIImpl::getPreferredAddressingMode(), llvm::ARMTargetLowering::getPreIndexedAddressParts(), llvm::ARMTargetLowering::getRegClassFor(), llvm::ARMTargetLowering::getSetCCResultType(), llvm::ARMTTIImpl::getShuffleCost(), llvm::ARMTTIImpl::getVectorInstrCost(), llvm::ARMTargetLowering::isLegalInterleavedAccessType(), llvm::ARMTTIImpl::isLegalMaskedGather(), llvm::ARMTTIImpl::isLegalMaskedLoad(), isLegalT2AddressImmediate(), llvm::ARMTTIImpl::isLoweredToCall(), llvm::ARMTargetLowering::isShuffleMaskLegal(), llvm::ARMTargetLowering::isVectorLoadExtDesirable(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), LowerSTORE(), LowerTruncate(), LowerVectorExtend(), PerformADDVecReduce(), PerformANDCombine(), PerformMULCombine(), PerformORCombine(), PerformSELECTCombine(), PerformSTORECombine(), PerformSUBCombine(), PerformVCMPCombine(), PerformVDUPCombine(), PerformVDUPLANECombine(), PerformVSELECTCombine(), PerformVSetCCToVCTPCombine(), PerformXORCombine(), llvm::ARMTTIImpl::preferInLoopReduction(), llvm::ARMTTIImpl::preferPredicatedReductionSelect(), llvm::ARMTTIImpl::preferPredicateOverEpilogue(), llvm::ARMTargetLowering::shouldConvertSplatType(), llvm::ARMTargetLowering::shouldSinkOperands(), and llvm::ARMBaseInstrInfo::storeRegToStackSlot().
hasNEON()
bool llvm::ARMSubtarget::hasNEON () const inline
Definition at line 680 of file ARMSubtarget.h.
References HasNEON.
Referenced by AddCombineBUILD_VECTORToVPADDL(), llvm::ARMTargetLowering::allowsMisalignedMemoryAccesses(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMTargetLowering::canCombineStoreAndExtract(), checkNumAlignedDPRCS2Regs(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::ARMTTIImpl::getAddressComputationCost(), llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::ARMTTIImpl::getCFInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), llvm::ARMBaseInstrInfo::getExecutionDomain(), llvm::ARMBaseRegisterInfo::getLargestLegalSuperClass(), llvm::ARMTargetLowering::getMaxSupportedInterleaveFactor(), llvm::ARMTTIImpl::getMemoryOpCost(), llvm::ARMTargetLowering::getOptimalMemOpType(), llvm::ARMTargetLowering::getRegClassFor(), llvm::ARMTTIImpl::getShuffleCost(), llvm::ARMTTIImpl::getVectorInstrCost(), llvm::ARMTargetLowering::isLegalInterleavedAccessType(), isLegalT2AddressImmediate(), llvm::ARMTargetLowering::isShuffleMaskLegal(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::LowerXConstraint(), PerformANDCombine(), PerformLOADCombine(), PerformORCombine(), PerformSTORECombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPCombine(), llvm::ARMTargetLowering::preferIncOfAddToSubOfNot(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::ARMTargetLowering::shouldSinkOperands(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), and useNEONForSinglePrecisionFP().
hasPACBTI()
bool llvm::ARMSubtarget::hasPACBTI () const inline
Definition at line 688 of file ARMSubtarget.h.
References HasPACBTI.
hasPerfMon()
bool llvm::ARMSubtarget::hasPerfMon () const inline
Definition at line 716 of file ARMSubtarget.h.
References HasPerfMon.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
hasRAS()
bool llvm::ARMSubtarget::hasRAS () const inline
Definition at line 686 of file ARMSubtarget.h.
References HasRAS.
hasRetAddrStack()
bool llvm::ARMSubtarget::hasRetAddrStack () const inline
Definition at line 741 of file ARMSubtarget.h.
References HasRetAddrStack.
hasSB()
bool llvm::ARMSubtarget::hasSB () const inline
Definition at line 747 of file ARMSubtarget.h.
References HasSB.
hasSHA2()
bool llvm::ARMSubtarget::hasSHA2 () const inline
Definition at line 681 of file ARMSubtarget.h.
References HasSHA2.
hasSlowLoadDSubregister()
bool llvm::ARMSubtarget::hasSlowLoadDSubregister () const inline
Definition at line 729 of file ARMSubtarget.h.
References SlowLoadDSubregister.
Referenced by llvm::ARMTTIImpl::getVectorInstrCost().
hasSlowOddRegister()
bool llvm::ARMSubtarget::hasSlowOddRegister () const inline
Definition at line 728 of file ARMSubtarget.h.
References SlowOddRegister.
hasSlowVDUP32()
bool llvm::ARMSubtarget::hasSlowVDUP32 () const inline
Definition at line 723 of file ARMSubtarget.h.
References HasSlowVDUP32.
hasSlowVGETLNi32()
bool llvm::ARMSubtarget::hasSlowVGETLNi32 () const inline
Definition at line 722 of file ARMSubtarget.h.
References HasSlowVGETLNi32.
hasThumb2()
bool llvm::ARMSubtarget::hasThumb2 () const inline
Definition at line 834 of file ARMSubtarget.h.
References HasThumb2.
Referenced by PerformORCombineToSMULWBT().
hasTrustZone()
bool llvm::ARMSubtarget::hasTrustZone () const inline
Definition at line 717 of file ARMSubtarget.h.
References HasTrustZone.
hasV4TOps()
bool llvm::ARMSubtarget::hasV4TOps () const inline
Definition at line 627 of file ARMSubtarget.h.
References HasV4TOps.
Referenced by llvm::ARMAsmPrinter::emitInstruction(), and getReturnOpcode().
hasV5TEOps()
bool llvm::ARMSubtarget::hasV5TEOps () const inline
Definition at line 629 of file ARMSubtarget.h.
References HasV5TEOps.
Referenced by hasBaseDSP(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), LowerPREFETCH(), LowerSTORE(), and llvm::ARMBaseInstrInfo::storeRegToStackSlot().
hasV5TOps()
bool llvm::ARMSubtarget::hasV5TOps () const inline
Definition at line 628 of file ARMSubtarget.h.
References HasV5TOps.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMAsmPrinter::emitInstruction(), llvm::ARMTargetLowering::PerformCMOVCombine(), and llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters().
hasV6KOps()
bool llvm::ARMSubtarget::hasV6KOps () const inline
Definition at line 632 of file ARMSubtarget.h.
References HasV6KOps.
hasV6MOps()
bool llvm::ARMSubtarget::hasV6MOps () const inline
Definition at line 631 of file ARMSubtarget.h.
References HasV6MOps.
hasV6Ops()
bool llvm::ARMSubtarget::hasV6Ops () const inline
Definition at line 630 of file ARMSubtarget.h.
References HasV6Ops.
Referenced by AddCombineTo64bitMLAL(), AddCombineTo64bitUMAAL(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMTargetLowering::ExpandInlineAsm(), llvm::ARMTTIImpl::getIntImmCostInst(), hasAnyDataBarrier(), isXRaySupported(), LowerADDSUBSAT(), LowerATOMIC_FENCE(), llvm::ARMTargetLowering::makeDMB(), PerformORCombineToSMULWBT(), PerformUMLALCombine(), llvm::ARMTargetLowering::shouldAlignPointerArgs(), and useFastISel().
hasV6T2Ops()
bool llvm::ARMSubtarget::hasV6T2Ops () const inline
Definition at line 633 of file ARMSubtarget.h.
References HasV6T2Ops.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ConstantMaterializationCost(), emitAligningInstructions(), llvm::ARMTTIImpl::getIntImmCost(), llvm::ARMTargetLowering::isCheapToSpeculateCtlz(), llvm::ARMTargetLowering::isCheapToSpeculateCttz(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::ARMTargetLowering::PerformCMOVCombine(), and PerformORCombineToBFI().
hasV7Clrex()
bool llvm::ARMSubtarget::hasV7Clrex () const inline
Definition at line 699 of file ARMSubtarget.h.
References HasV7Clrex.
hasV7Ops()
bool llvm::ARMSubtarget::hasV7Ops () const inline
Definition at line 634 of file ARMSubtarget.h.
References HasV7Ops.
Referenced by llvm::ARMTargetLowering::allowsMisalignedMemoryAccesses(), emitAligningInstructions(), llvm::ARMTargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), and LowerPREFETCH().
hasV8_1aOps()
bool llvm::ARMSubtarget::hasV8_1aOps () const inline
Definition at line 636 of file ARMSubtarget.h.
References HasV8_1aOps.
hasV8_1MMainlineOps()
bool llvm::ARMSubtarget::hasV8_1MMainlineOps () const inline
Definition at line 650 of file ARMSubtarget.h.
References HasV8_1MMainlineOps.
Referenced by llvm::ARMFrameLowering::assignCalleeSavedSpillSlots(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::enableShrinkWrapping(), and getMaxFPOffset().
hasV8_2aOps()
bool llvm::ARMSubtarget::hasV8_2aOps () const inline
Definition at line 637 of file ARMSubtarget.h.
References HasV8_2aOps.
hasV8_3aOps()
bool llvm::ARMSubtarget::hasV8_3aOps () const inline
Definition at line 638 of file ARMSubtarget.h.
References HasV8_3aOps.
hasV8_4aOps()
bool llvm::ARMSubtarget::hasV8_4aOps () const inline
Definition at line 639 of file ARMSubtarget.h.
References HasV8_4aOps.
hasV8_5aOps()
bool llvm::ARMSubtarget::hasV8_5aOps () const inline
Definition at line 640 of file ARMSubtarget.h.
References HasV8_5aOps.
hasV8_6aOps()
bool llvm::ARMSubtarget::hasV8_6aOps () const inline
Definition at line 641 of file ARMSubtarget.h.
References HasV8_6aOps.
hasV8_7aOps()
bool llvm::ARMSubtarget::hasV8_7aOps () const inline
Definition at line 642 of file ARMSubtarget.h.
References HasV8_7aOps.
hasV8_8aOps()
bool llvm::ARMSubtarget::hasV8_8aOps () const inline
Definition at line 643 of file ARMSubtarget.h.
References HasV8_8aOps.
hasV8MBaselineOps()
bool llvm::ARMSubtarget::hasV8MBaselineOps () const inline
Definition at line 648 of file ARMSubtarget.h.
References HasV8MBaselineOps.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::ARMTargetLowering::shouldExpandAtomicCmpXchgInIR(), llvm::ARMTargetLowering::shouldExpandAtomicRMWInIR(), and useMovt().
hasV8MMainlineOps()
bool llvm::ARMSubtarget::hasV8MMainlineOps () const inline
Definition at line 649 of file ARMSubtarget.h.
References HasV8MMainlineOps.
hasV8Ops()
bool llvm::ARMSubtarget::hasV8Ops () const inline
Definition at line 635 of file ARMSubtarget.h.
References HasV8Ops.
hasV9_0aOps()
bool llvm::ARMSubtarget::hasV9_0aOps () const inline
Definition at line 644 of file ARMSubtarget.h.
References HasV9_0aOps.
hasV9_1aOps()
bool llvm::ARMSubtarget::hasV9_1aOps () const inline
Definition at line 645 of file ARMSubtarget.h.
References HasV9_1aOps.
hasV9_2aOps()
bool llvm::ARMSubtarget::hasV9_2aOps () const inline
Definition at line 646 of file ARMSubtarget.h.
References HasV9_2aOps.
hasV9_3aOps()
bool llvm::ARMSubtarget::hasV9_3aOps () const inline
Definition at line 647 of file ARMSubtarget.h.
References HasV9_3aOps.
hasVFP2Base()
bool llvm::ARMSubtarget::hasVFP2Base () const inline
Definition at line 676 of file ARMSubtarget.h.
References HasVFPv2SP.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMBaseInstrInfo::CreateTargetPostRAHazardRecognizer(), llvm::ARMTTIImpl::getCastInstrCost(), llvm::ARMRegisterBankInfo::getInstrMapping(), llvm::ARMTTIImpl::getIntImmCostInst(), llvm::ARMBaseRegisterInfo::getSjLjDispatchPreservedMask(), isLegalAddressImmediate(), isLegalT2AddressImmediate(), llvm::ARMTTIImpl::isLoweredToCall(), llvm::ARMTargetLowering::LowerXConstraint(), and llvm::ARMTargetLowering::shouldConvertFpToSat().
hasVFP3Base()
bool llvm::ARMSubtarget::hasVFP3Base () const inline
Definition at line 677 of file ARMSubtarget.h.
References HasVFPv3D16SP.
Referenced by llvm::ARMTargetLowering::isFPImmLegal().
hasVFP4Base()
bool llvm::ARMSubtarget::hasVFP4Base () const inline
Definition at line 678 of file ARMSubtarget.h.
References HasVFPv4D16SP.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), and useFPVFMx().
hasVirtualization()
bool llvm::ARMSubtarget::hasVirtualization () const inline
Definition at line 689 of file ARMSubtarget.h.
References HasVirtualization.
hasVMLxForwarding()
bool llvm::ARMSubtarget::hasVMLxForwarding () const inline
Definition at line 713 of file ARMSubtarget.h.
References HasVMLxForwarding.
Referenced by PerformVMULCombine().
hasVMLxHazards()
bool llvm::ARMSubtarget::hasVMLxHazards () const inline
Definition at line 727 of file ARMSubtarget.h.
References HasVMLxHazards.
hasZeroCycleZeroing()
bool llvm::ARMSubtarget::hasZeroCycleZeroing () const inline
Definition at line 719 of file ARMSubtarget.h.
References HasZeroCycleZeroing.
ignoreCSRForAllocationOrder()
bool ARMSubtarget::ignoreCSRForAllocationOrder (const MachineFunction & MF, unsigned PhysReg) const override
Definition at line 484 of file ARMSubtarget.cpp.
References llvm::MachineFunction::getFunction(), llvm::Function::hasMinSize(), and isThumb2().
initializeSubtargetDependencies()
ARMSubtarget & ARMSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
initializeSubtargetDependencies - Initializes using a CPU and feature string so that we can use initializer lists for subtarget initialization.
Definition at line 80 of file ARMSubtarget.cpp.
isAAPCS16_ABI()
bool ARMSubtarget::isAAPCS16_ABI () const
Definition at line 344 of file ARMSubtarget.cpp.
References llvm::ARMBaseTargetMachine::ARM_ABI_AAPCS16, llvm::ARMBaseTargetMachine::ARM_ABI_UNKNOWN, assert(), llvm::ARMBaseTargetMachine::TargetABI, and TM.
isAAPCS_ABI()
bool ARMSubtarget::isAAPCS_ABI () const
Definition at line 339 of file ARMSubtarget.cpp.
References llvm::ARMBaseTargetMachine::ARM_ABI_AAPCS, llvm::ARMBaseTargetMachine::ARM_ABI_AAPCS16, llvm::ARMBaseTargetMachine::ARM_ABI_UNKNOWN, assert(), llvm::ARMBaseTargetMachine::TargetABI, and TM.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
isAClass()
bool llvm::ARMSubtarget::isAClass () const inline
Definition at line 837 of file ARMSubtarget.h.
References AClass, and ARMProcClass.
isAPCS_ABI()
bool ARMSubtarget::isAPCS_ABI () const
Definition at line 335 of file ARMSubtarget.cpp.
References llvm::ARMBaseTargetMachine::ARM_ABI_APCS, llvm::ARMBaseTargetMachine::ARM_ABI_UNKNOWN, assert(), llvm::ARMBaseTargetMachine::TargetABI, and TM.
isCortexA15()
bool llvm::ARMSubtarget::isCortexA15 () const inline
Definition at line 665 of file ARMSubtarget.h.
References ARMProcFamily, and CortexA15.
Referenced by isLikeA9().
isCortexA5()
bool llvm::ARMSubtarget::isCortexA5 () const inline
These functions are obsolete, please consider adding subtarget features or properties instead of calling them.
Definition at line 661 of file ARMSubtarget.h.
References ARMProcFamily, and CortexA5.
isCortexA7()
bool llvm::ARMSubtarget::isCortexA7 () const inline
Definition at line 662 of file ARMSubtarget.h.
References ARMProcFamily, and CortexA7.
Referenced by adjustDefLatency(), and llvm::ARMBaseInstrInfo::getOperandLatency().
isCortexA8()
bool llvm::ARMSubtarget::isCortexA8 () const inline
Definition at line 663 of file ARMSubtarget.h.
References ARMProcFamily, and CortexA8.
Referenced by adjustDefLatency(), llvm::ARMBaseInstrInfo::getExecutionDomain(), and llvm::ARMBaseInstrInfo::getOperandLatency().
isCortexA9()
bool llvm::ARMSubtarget::isCortexA9 () const inline
Definition at line 664 of file ARMSubtarget.h.
References ARMProcFamily, and CortexA9.
Referenced by isLikeA9().
isCortexM3()
bool llvm::ARMSubtarget::isCortexM3 () const inline
Definition at line 667 of file ARMSubtarget.h.
References ARMProcFamily, and CortexM3.
isCortexM7()
bool llvm::ARMSubtarget::isCortexM7 () const inline
Definition at line 668 of file ARMSubtarget.h.
References ARMProcFamily, and CortexM7.
Referenced by llvm::ARMBaseInstrInfo::CreateTargetMIHazardRecognizer().
isCortexR5()
bool llvm::ARMSubtarget::isCortexR5 () const inline
Definition at line 670 of file ARMSubtarget.h.
References ARMProcFamily, and CortexR5.
isFPBrccSlow()
bool llvm::ARMSubtarget::isFPBrccSlow () const inline
Definition at line 714 of file ARMSubtarget.h.
References SlowFPBrcc.
Referenced by canChangeToInt().
isGVIndirectSymbol()
bool ARMSubtarget::isGVIndirectSymbol (const GlobalValue * GV) const
True if the GV will be accessed via an indirect symbol.
Definition at line 358 of file ARMSubtarget.cpp.
References llvm::GlobalValue::getParent(), llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalValue::isDeclarationForLinker(), llvm::TargetMachine::isPositionIndependent(), isTargetMachO(), llvm::TargetMachine::shouldAssumeDSOLocal(), and TM.
Referenced by llvm::ARMBaseInstrInfo::expandLoadStackGuardBase().
isGVInGOT()
bool ARMSubtarget::isGVInGOT (const GlobalValue * GV) const
Returns the constant pool modifier needed to access the GV.
Definition at line 372 of file ARMSubtarget.cpp.
References llvm::GlobalValue::getParent(), llvm::TargetMachine::isPositionIndependent(), isTargetELF(), llvm::TargetMachine::shouldAssumeDSOLocal(), and TM.
Referenced by llvm::ARMBaseInstrInfo::expandLoadStackGuardBase().
isKrait()
bool llvm::ARMSubtarget::isKrait () const inline
Definition at line 671 of file ARMSubtarget.h.
References ARMProcFamily, and Krait.
Referenced by isLikeA9().
isLikeA9()
bool llvm::ARMSubtarget::isLikeA9 () const inline
Definition at line 669 of file ARMSubtarget.h.
References isCortexA15(), isCortexA9(), and isKrait().
Referenced by adjustDefLatency(), and llvm::ARMBaseInstrInfo::getOperandLatency().
isLittle()
bool llvm::ARMSubtarget::isLittle () const inline
Definition at line 874 of file ARMSubtarget.h.
References IsLittle.
Referenced by llvm::ARMTargetLowering::allowsMisalignedMemoryAccesses(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::getPostIndexedAddressParts(), llvm::ARMTargetLowering::getPreIndexedAddressParts(), PerformMVEVMULLCombine(), and PerformVMOVRRDCombine().
isMClass()
bool llvm::ARMSubtarget::isMClass () const inline
Definition at line 835 of file ARMSubtarget.h.
References ARMProcClass, and MClass.
Referenced by llvm::ARMTargetLowering::alignLoopsWithOptSize(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMBaseInstrInfo::copyFromCPSR(), llvm::ARMBaseInstrInfo::copyToCPSR(), enableMachineScheduler(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::ARMTTIImpl::getPreferredAddressingMode(), llvm::ARMTTIImpl::getUnrollingPreferences(), LowerATOMIC_FENCE(), llvm::ARMTargetLowering::makeDMB(), llvm::ARMTargetLowering::shouldAlignPointerArgs(), llvm::ARMTargetLowering::shouldExpandAtomicCmpXchgInIR(), llvm::ARMTargetLowering::shouldExpandAtomicLoadInIR(), llvm::ARMTargetLowering::shouldExpandAtomicRMWInIR(), llvm::ARMTargetLowering::shouldExpandAtomicStoreInIR(), and llvm::ARMBaseInstrInfo::shouldOutlineFromFunctionByDefault().
isProfitableToUnpredicate()
bool llvm::ARMSubtarget::isProfitableToUnpredicate () const inline
Definition at line 721 of file ARMSubtarget.h.
References IsProfitableToUnpredicate.
Referenced by llvm::ARMBaseInstrInfo::isProfitableToUnpredicate().
isR9Reserved()
bool llvm::ARMSubtarget::isR9Reserved () const inline
Definition at line 840 of file ARMSubtarget.h.
References HasV6Ops, isTargetMachO(), and ReserveR9.
Referenced by llvm::ARMBaseRegisterInfo::getRegPressureLimit(), and llvm::ARMBaseRegisterInfo::getReservedRegs().
isRClass()
bool llvm::ARMSubtarget::isRClass () const inline
Definition at line 836 of file ARMSubtarget.h.
References ARMProcClass, and RClass.
isReadTPHard()
bool llvm::ARMSubtarget::isReadTPHard () const inline
Definition at line 838 of file ARMSubtarget.h.
References ReadTPHard.
Referenced by llvm::ARMBaseInstrInfo::expandLoadStackGuardBase().
isROPI()
bool ARMSubtarget::isROPI () const
Definition at line 349 of file ARMSubtarget.cpp.
References llvm::TargetMachine::getRelocationModel(), llvm::Reloc::ROPI, llvm::Reloc::ROPI_RWPI, and TM.
Referenced by allowPositionIndependentMovt(), llvm::ARMAsmPrinter::emitJumpTableAddrs(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), and promoteToConstantPool().
isRWPI()
bool ARMSubtarget::isRWPI () const
Definition at line 353 of file ARMSubtarget.cpp.
References llvm::TargetMachine::getRelocationModel(), llvm::Reloc::ROPI_RWPI, llvm::Reloc::RWPI, and TM.
Referenced by llvm::ARMBaseInstrInfo::expandLoadStackGuardBase().
isSwift()
bool llvm::ARMSubtarget::isSwift () const inline
Definition at line 666 of file ARMSubtarget.h.
References ARMProcFamily, and Swift.
Referenced by adjustDefLatency(), llvm::ARMBaseInstrInfo::getNumMicroOps(), and llvm::ARMBaseInstrInfo::getOperandLatency().
isTargetAEABI()
bool llvm::ARMSubtarget::isTargetAEABI () const inline
Definition at line 792 of file ARMSubtarget.h.
References llvm::Triple::EABI, llvm::Triple::EABIHF, llvm::Triple::getEnvironment(), isTargetDarwin(), isTargetWindows(), and TargetTriple.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), and llvm::ARMAsmPrinter::emitEndOfAsmFile().
isTargetAndroid()
bool llvm::ARMSubtarget::isTargetAndroid () const inline
Definition at line 816 of file ARMSubtarget.h.
References llvm::Triple::isAndroid(), and TargetTriple.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
isTargetCOFF()
bool llvm::ARMSubtarget::isTargetCOFF () const inline
Definition at line 781 of file ARMSubtarget.h.
References llvm::Triple::isOSBinFormatCOFF(), and TargetTriple.
Referenced by llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), and llvm::ARMAsmPrinter::runOnMachineFunction().
isTargetDarwin()
bool llvm::ARMSubtarget::isTargetDarwin () const inline
Definition at line 772 of file ARMSubtarget.h.
References llvm::Triple::isOSDarwin(), and TargetTriple.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMAsmPrinter::emitInstruction(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCallPreservedMask(), getFramePointerReg(), llvm::ARMBaseRegisterInfo::getThisReturnPreservedMask(), llvm::ARMBaseRegisterInfo::getTLSCallPreservedMask(), isTargetAEABI(), isTargetGNUAEABI(), isTargetMuslAEABI(), and useFPVFMx().
isTargetEHABICompatible()
bool llvm::ARMSubtarget::isTargetEHABICompatible () const inline
Definition at line 810 of file ARMSubtarget.h.
References llvm::Triple::isTargetEHABICompatible(), and TargetTriple.
Referenced by llvm::ARMAsmPrinter::emitInstruction().
isTargetELF()
bool llvm::ARMSubtarget::isTargetELF () const inline
Definition at line 782 of file ARMSubtarget.h.
References llvm::Triple::isOSBinFormatELF(), and TargetTriple.
Referenced by allowPositionIndependentMovt(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARMAsmPrinter::emitXXStructor(), and isGVInGOT().
isTargetGNUAEABI()
bool llvm::ARMSubtarget::isTargetGNUAEABI () const inline
Definition at line 797 of file ARMSubtarget.h.
References llvm::Triple::getEnvironment(), llvm::Triple::GNUEABI, llvm::Triple::GNUEABIHF, isTargetDarwin(), isTargetWindows(), and TargetTriple.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), and llvm::ARMAsmPrinter::emitEndOfAsmFile().
isTargetHardFloat()
bool ARMSubtarget::isTargetHardFloat () const
Definition at line 333 of file ARMSubtarget.cpp.
References llvm::ARMBaseTargetMachine::isTargetHardFloat(), and TM.
isTargetIOS()
bool llvm::ARMSubtarget::isTargetIOS () const inline
Definition at line 773 of file ARMSubtarget.h.
References llvm::Triple::isiOS(), and TargetTriple.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
isTargetLinux()
bool llvm::ARMSubtarget::isTargetLinux () const inline
Definition at line 776 of file ARMSubtarget.h.
References llvm::Triple::isOSLinux(), and TargetTriple.
Referenced by useFastISel().
isTargetMachO()
bool llvm::ARMSubtarget::isTargetMachO () const inline
Definition at line 783 of file ARMSubtarget.h.
References llvm::Triple::isOSBinFormatMachO(), and TargetTriple.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMBaseInstrInfo::buildOutlinedFrame(), llvm::ARMAsmPrinter::emitInstruction(), llvm::ARMAsmPrinter::emitMachineConstantPoolValue(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::ARMBaseInstrInfo::insertOutlinedCall(), isGVIndirectSymbol(), isR9Reserved(), and useFastISel().
isTargetMuslAEABI()
bool llvm::ARMSubtarget::isTargetMuslAEABI () const inline
Definition at line 802 of file ARMSubtarget.h.
References llvm::Triple::getEnvironment(), isTargetDarwin(), isTargetWindows(), llvm::Triple::MuslEABI, llvm::Triple::MuslEABIHF, and TargetTriple.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), and llvm::ARMAsmPrinter::emitEndOfAsmFile().
isTargetNaCl()
bool llvm::ARMSubtarget::isTargetNaCl () const inline
Definition at line 777 of file ARMSubtarget.h.
References llvm::Triple::isOSNaCl(), and TargetTriple.
Referenced by useFastISel().
isTargetNetBSD()
bool llvm::ARMSubtarget::isTargetNetBSD () const inline
Definition at line 778 of file ARMSubtarget.h.
References llvm::Triple::isOSNetBSD(), and TargetTriple.
isTargetWatchABI()
bool llvm::ARMSubtarget::isTargetWatchABI () const inline
Definition at line 775 of file ARMSubtarget.h.
References llvm::Triple::isWatchABI(), and TargetTriple.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), and useStride4VFPs().
isTargetWatchOS()
bool llvm::ARMSubtarget::isTargetWatchOS () const inline
Definition at line 774 of file ARMSubtarget.h.
References llvm::Triple::isWatchOS(), and TargetTriple.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering().
isTargetWindows()
bool llvm::ARMSubtarget::isTargetWindows () const inline
Definition at line 779 of file ARMSubtarget.h.
References llvm::Triple::isOSWindows(), and TargetTriple.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::ARMAsmPrinter::emitInstruction(), llvm::ARMFrameLowering::emitPrologue(), getDivRemArgList(), getFramePointerReg(), isTargetAEABI(), isTargetGNUAEABI(), isTargetMuslAEABI(), isXRaySupported(), llvm::ARMTargetLowering::LowerOperation(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::ARMTargetLowering::shouldExpandShift(), and useMovt().
isThumb()
bool llvm::ARMSubtarget::isThumb () const inline
Definition at line 830 of file ARMSubtarget.h.
References InThumbMode.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMBaseInstrInfo::buildOutlinedFrame(), llvm::ConstantMaterializationCost(), llvm::ARMBaseInstrInfo::copyFromCPSR(), llvm::ARMBaseInstrInfo::copyToCPSR(), llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::ARMTTIImpl::getCmpSelInstrCost(), getFramePointerReg(), llvm::ARMTTIImpl::getIntImmCost(), llvm::ARMTTIImpl::getIntImmCostInst(), llvm::ARMTargetLowering::getRegForInlineAsmConstraint(), getReturnOpcode(), llvm::ARMTargetLowering::getSingleConstraintMatchWeight(), hasAnyDataBarrier(), hasBaseDSP(), llvm::ARMBaseInstrInfo::insertOutlinedCall(), llvm::ARMTargetLowering::isLegalAddImmediate(), llvm::ARMTargetLowering::isLegalICmpImmediate(), LowerATOMIC_FENCE(), llvm::ARMCallLowering::lowerCall(), LowerPREFETCH(), llvm::ARMTargetLowering::makeDMB(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), PerformORCombineToSMULWBT(), llvm::ARMTargetLowering::shouldExpandAtomicCmpXchgInIR(), llvm::ARMTargetLowering::shouldExpandAtomicRMWInIR(), and useFastISel().
isThumb1Only()
bool llvm::ARMSubtarget::isThumb1Only () const inline
Definition at line 832 of file ARMSubtarget.h.
References HasThumb2, and InThumbMode.
Referenced by llvm::ARMTargetLowering::AdjustInstrPostInstrSelection(), llvm::ARMBaseInstrInfo::areLoadsFromSameBasePtr(), llvm::ARMTargetLowering::ARMTargetLowering(), attachMEMCPYScratchRegs(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), llvm::ARMAsmPrinter::emitJumpTableTBInst(), llvm::ThumbRegisterInfo::emitLoadConstPool(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), enablePostRAMachineScheduler(), enablePostRAScheduler(), llvm::ARMTTIImpl::getArithmeticInstrCost(), getGPRAllocationOrder(), llvm::ThumbRegisterInfo::getLargestLegalSuperClass(), llvm::ThumbRegisterInfo::getPointerRegClass(), llvm::ARMTargetLowering::getPostIndexedAddressParts(), llvm::ARMTargetLowering::getPreIndexedAddressParts(), llvm::ARMTargetLowering::getRegForInlineAsmConstraint(), llvm::ARMBaseRegisterInfo::getSjLjDispatchPreservedMask(), llvm::ARMTTIImpl::getUnrollingPreferences(), llvm::ARMTargetLowering::isDesirableToCommuteWithShift(), isLegalAddressImmediate(), llvm::ARMTargetLowering::isLegalAddressingMode(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::ARMCallLowering::lowerCall(), LowerPREFETCH(), LowerSTORE(), PerformAddcSubcCombine(), PerformADDECombine(), PerformAddeSubeCombine(), PerformANDCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), PerformMULCombine(), PerformORCombine(), PerformORCombineToBFI(), PerformXORCombine(), llvm::ARMTargetLowering::preferIncOfAddToSubOfNot(), llvm::ThumbRegisterInfo::resolveFrameIndex(), llvm::ThumbRegisterInfo::rewriteFrameIndex(), llvm::ARMTargetLowering::shouldFoldConstantShiftPairToMask(), llvm::ARMBaseInstrInfo::shouldScheduleLoadsNear(), splitFramePushPop(), useFastISel(), and llvm::ThumbRegisterInfo::useFPForScavengingIndex().
isThumb2()
bool llvm::ARMSubtarget::isThumb2 () const inline
Definition at line 833 of file ARMSubtarget.h.
References HasThumb2, and InThumbMode.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::CreateTargetPostRAHazardRecognizer(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMBaseInstrInfo::extraSizeToPredicateInstructions(), getGPRAllocationOrder(), llvm::ARMTTIImpl::getIntImmCost(), llvm::ARMTTIImpl::getIntImmCostInst(), llvm::ARMTargetLowering::getPostIndexedAddressParts(), llvm::ARMTTIImpl::getPreferredAddressingMode(), llvm::ARMTargetLowering::getPreIndexedAddressParts(), ignoreCSRForAllocationOrder(), llvm::ARMTargetLowering::isLegalAddImmediate(), isLegalAddressImmediate(), llvm::ARMTargetLowering::isLegalAddressingMode(), llvm::ARMTargetLowering::isLegalICmpImmediate(), llvm::ARMBaseInstrInfo::isProfitableToIfCvt(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), LowerPREFETCH(), and llvm::ARMBaseInstrInfo::predictBranchSizeForIfCvt().
isXRaySupported()
bool ARMSubtarget::isXRaySupported () const override
Definition at line 143 of file ARMSubtarget.cpp.
References hasARMOps(), hasV6Ops(), and isTargetWindows().
nonpipelinedVFP()
bool llvm::ARMSubtarget::nonpipelinedVFP () const inline
Definition at line 736 of file ARMSubtarget.h.
References NonpipelinedVFP.
ParseSubtargetFeatures()
void llvm::ARMSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
preferISHSTBarriers()
bool llvm::ARMSubtarget::preferISHSTBarriers () const inline
Definition at line 725 of file ARMSubtarget.h.
References PreferISHST.
Referenced by llvm::ARMTargetLowering::emitLeadingFence(), and LowerATOMIC_FENCE().
prefers32BitThumb()
bool llvm::ARMSubtarget::prefers32BitThumb () const inline
Definition at line 737 of file ARMSubtarget.h.
References Pref32BitThumb.
preferVMOVSR()
bool llvm::ARMSubtarget::preferVMOVSR () const inline
Definition at line 724 of file ARMSubtarget.h.
References PreferVMOVSR.
restrictIT()
bool llvm::ARMSubtarget::restrictIT () const inline
Definition at line 870 of file ARMSubtarget.h.
References RestrictIT.
Referenced by llvm::ARMBaseInstrInfo::extraSizeToPredicateInstructions(), and llvm::ARMBaseInstrInfo::isPredicable().
splitFramePushPop()
bool llvm::ARMSubtarget::splitFramePushPop (const MachineFunction & MF) const inline
Returns true if the frame setup is split into two separate pushes (first r0-r7,lr then r8-r11), principally so that the frame pointer is adjacent to lr.
This is always required on Thumb1-only targets, as the push and pop instructions can't access the high registers.
Definition at line 854 of file ARMSubtarget.h.
References llvm::TargetOptions::DisableFramePointerElim(), getFramePointerReg(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getTarget(), isThumb1Only(), llvm::TargetMachine::Options, and llvm::ARMFunctionInfo::shouldSignReturnAddress().
Referenced by llvm::ARMFrameLowering::determineCalleeSaves(), llvm::ARMFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), and llvm::ARMBaseRegisterInfo::getCalleeSavedRegs().
supportsTailCall()
bool llvm::ARMSubtarget::supportsTailCall () const inline
Definition at line 866 of file ARMSubtarget.h.
References SupportsTailCall.
useAA()
bool llvm::ARMSubtarget::useAA () const inline override
Enable use of alias analysis during code generation (during MI scheduling, DAGCombine, etc.).
Definition at line 892 of file ARMSubtarget.h.
useFastISel()
bool ARMSubtarget::useFastISel () const
True if fast-isel is used.
Definition at line 438 of file ARMSubtarget.cpp.
References llvm::TargetOptions::EnableFastISel, ForceFastISel, hasV6Ops(), isTargetLinux(), isTargetMachO(), isTargetNaCl(), isThumb(), isThumb1Only(), llvm::TargetMachine::Options, and TM.
Referenced by llvm::ARM::createFastISel().
useFPVFMx()
bool llvm::ARMSubtarget::useFPVFMx () const inline
Definition at line 708 of file ARMSubtarget.h.
References hasVFP4Base(), isTargetDarwin(), and SlowFPVFMx.
Referenced by useFPVFMx16(), and useFPVFMx64().
useFPVFMx16()
bool llvm::ARMSubtarget::useFPVFMx16 () const inline
Definition at line 711 of file ARMSubtarget.h.
References hasFullFP16(), and useFPVFMx().
useFPVFMx64()
bool llvm::ARMSubtarget::useFPVFMx64 () const inline
Definition at line 712 of file ARMSubtarget.h.
References hasFP64(), and useFPVFMx().
useFPVMLx()
bool llvm::ARMSubtarget::useFPVMLx () const inline
Definition at line 707 of file ARMSubtarget.h.
References SlowFPVMLx.
useMachineScheduler()
bool llvm::ARMSubtarget::useMachineScheduler () const inline
Definition at line 827 of file ARMSubtarget.h.
References UseMISched.
Referenced by enableMachineScheduler().
useMovt()
bool ARMSubtarget::useMovt () const
Definition at line 430 of file ARMSubtarget.cpp.
References genExecuteOnly(), hasV8MBaselineOps(), isTargetWindows(), NoMovt, and OptMinSize.
Referenced by llvm::ConstantMaterializationCost().
useMulOps()
bool llvm::ARMSubtarget::useMulOps () const inline
Definition at line 706 of file ARMSubtarget.h.
References UseMulOps.
Referenced by AddCombineTo64bitMLAL().
useNaClTrap()
bool llvm::ARMSubtarget::useNaClTrap () const inline
Definition at line 745 of file ARMSubtarget.h.
References UseNaClTrap.
useNEONForFPMovs()
bool llvm::ARMSubtarget::useNEONForFPMovs () const inline
Definition at line 734 of file ARMSubtarget.h.
References UseNEONForFPMovs.
Referenced by llvm::ARMBaseInstrInfo::getExecutionDomain().
useNEONForSinglePrecisionFP()
bool llvm::ARMSubtarget::useNEONForSinglePrecisionFP () const inline
Definition at line 691 of file ARMSubtarget.h.
References hasNEON(), and UseNEONForSinglePrecisionFP.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), and llvm::ARMTargetLowering::findRepresentativeClass().
useSjLjEH()
bool llvm::ARMSubtarget::useSjLjEH () const inline
Definition at line 746 of file ARMSubtarget.h.
References UseSjLjEH.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMTargetLowering::getExceptionPointerRegister(), and llvm::ARMTargetLowering::getExceptionSelectorRegister().
useSoftFloat()
bool llvm::ARMSubtarget::useSoftFloat () const inline
Definition at line 829 of file ARMSubtarget.h.
References UseSoftFloat.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMBaseRegisterInfo::getSjLjDispatchPreservedMask(), and llvm::ARMTargetLowering::useSoftFloat().
useSplatVFPToNeon()
bool llvm::ARMSubtarget::useSplatVFPToNeon () const inline
Definition at line 733 of file ARMSubtarget.h.
References SplatVFPToNeon.
useStride4VFPs()
bool ARMSubtarget::useStride4VFPs () const
Definition at line 422 of file ARMSubtarget.cpp.
References isTargetWatchABI(), OptMinSize, and useWideStrideVFP().
useWideStrideVFP()
bool llvm::ARMSubtarget::useWideStrideVFP () const inline
Definition at line 730 of file ARMSubtarget.h.
References UseWideStrideVFP.
Referenced by useStride4VFPs().
Member Data Documentation
ARMArch
ARMArchEnum llvm::ARMSubtarget::ARMArch = ARMv4t protected
ARMArch - ARM architecture.
Definition at line 160 of file ARMSubtarget.h.
ARMProcClass
ARMProcClassEnum llvm::ARMSubtarget::ARMProcClass = None protected
ARMProcClass - ARM processor class: None, AClass, RClass or MClass.
Definition at line 157 of file ARMSubtarget.h.
Referenced by isAClass(), isMClass(), and isRClass().
ARMProcFamily
ARMProcFamilyEnum llvm::ARMSubtarget::ARMProcFamily = Others protected
ARMProcFamily - ARM processor family: Cortex-A8, Cortex-A9, and others.
Definition at line 154 of file ARMSubtarget.h.
Referenced by isCortexA15(), isCortexA5(), isCortexA7(), isCortexA8(), isCortexA9(), isCortexM3(), isCortexM7(), isCortexR5(), isKrait(), and isSwift().
AvoidCPSRPartialUpdate
bool llvm::ARMSubtarget::AvoidCPSRPartialUpdate = false protected
AvoidCPSRPartialUpdate - If true, codegen would avoid using instructions that partially update CPSR and add false dependency on the previous CPSR setting instruction.
Definition at line 322 of file ARMSubtarget.h.
Referenced by avoidCPSRPartialUpdate().
AvoidMOVsShifterOperand
bool llvm::ARMSubtarget::AvoidMOVsShifterOperand = false protected
AvoidMOVsShifterOperand - If true, codegen should avoid using flag setting movs with shifter operand (i.e.
asr, lsl, lsr).
Definition at line 330 of file ARMSubtarget.h.
Referenced by avoidMOVsShifterOperand().
CheapPredicableCPSRDef
bool llvm::ARMSubtarget::CheapPredicableCPSRDef = false protected
CheapPredicableCPSRDef - If true, disable +1 predication cost for instructions updating CPSR.
Enabled for Cortex-A57.
Definition at line 326 of file ARMSubtarget.h.
Referenced by cheapPredicableCPSRDef().
CheckVLDnAlign
bool llvm::ARMSubtarget::CheckVLDnAlign = false protected
If true, VLDn instructions take an extra cycle for unaligned accesses.
Definition at line 446 of file ARMSubtarget.h.
Referenced by checkVLDnAccessAlignment().
CPUString
std::string llvm::ARMSubtarget::CPUString protected
CPUString - String name of used CPU.
Definition at line 504 of file ARMSubtarget.h.
Referenced by getCPUString().
DisablePostRAScheduler
bool llvm::ARMSubtarget::DisablePostRAScheduler = false protected
DisablePostRAScheduler - False if scheduling should happen again after register allocation.
Definition at line 255 of file ARMSubtarget.h.
Referenced by disablePostRAScheduler().
DontWidenVMOVS
bool llvm::ARMSubtarget::DontWidenVMOVS = false protected
If true, VMOVS will never be widened to VMOVD.
Definition at line 428 of file ARMSubtarget.h.
Referenced by dontWidenVMOVS().
ExpandMLx
bool llvm::ARMSubtarget::ExpandMLx = false protected
If true, run the MLx expansion pass.
Definition at line 434 of file ARMSubtarget.h.
Referenced by expandMLx().
FixCMSE_CVE_2021_35465
bool llvm::ARMSubtarget::FixCMSE_CVE_2021_35465 = false protected
Mitigate against the cve-2021-35465 security vulnurability.
Definition at line 487 of file ARMSubtarget.h.
Referenced by fixCMSE_CVE_2021_35465().
GenExecuteOnly
bool llvm::ARMSubtarget::GenExecuteOnly = false protected
Generate code that does not contain data access to code sections.
Definition at line 471 of file ARMSubtarget.h.
Referenced by genExecuteOnly().
GenLongCalls
bool llvm::ARMSubtarget::GenLongCalls = false protected
Generate calls via indirect call instructions.
Definition at line 468 of file ARMSubtarget.h.
Referenced by genLongCalls().
HardenSlsBlr
bool llvm::ARMSubtarget::HardenSlsBlr = false protected
Harden against Straight Line Speculation for indirect calls.
Definition at line 494 of file ARMSubtarget.h.
Referenced by hardenSlsBlr().
HardenSlsNoComdat
bool llvm::ARMSubtarget::HardenSlsNoComdat = false protected
Generate thunk code for SLS mitigation in the normal text section.
Definition at line 497 of file ARMSubtarget.h.
Referenced by hardenSlsNoComdat().
HardenSlsRetBr
bool llvm::ARMSubtarget::HardenSlsRetBr = false protected
Harden against Straight Line Speculation for Returns and Indirect Branches.
Definition at line 491 of file ARMSubtarget.h.
Referenced by hardenSlsRetBr().
Has8MSecExt
bool llvm::ARMSubtarget::Has8MSecExt = false protected
Has8MSecExt - if true, processor supports ARMv8-M Security Extensions.
Definition at line 362 of file ARMSubtarget.h.
Referenced by has8MSecExt().
HasAcquireRelease
bool llvm::ARMSubtarget::HasAcquireRelease = false protected
HasAcquireRelease - True if the subtarget supports v8 atomics (LDA/LDAEX etc) instructions.
Definition at line 313 of file ARMSubtarget.h.
Referenced by hasAcquireRelease().
HasAES
bool llvm::ARMSubtarget::HasAES = false protected
HasAES - if true, processor supports AES.
Definition at line 368 of file ARMSubtarget.h.
Referenced by hasAES().
HasBF16
bool llvm::ARMSubtarget::HasBF16 = false protected
HasBF16 - True if subtarget supports BFloat16 floating point operations.
Definition at line 285 of file ARMSubtarget.h.
Referenced by hasBF16().
HasBranchPredictor
bool llvm::ARMSubtarget::HasBranchPredictor = true protected
HasBranchPredictor - True if the subtarget has a branch predictor.
Having a branch predictor or not changes the expected cost of taking a branch which affects the choice of whether to use predicated instructions.
Definition at line 339 of file ARMSubtarget.h.
Referenced by hasBranchPredictor().
HasCDEOps
bool llvm::ARMSubtarget::HasCDEOps = false protected
Definition at line 191 of file ARMSubtarget.h.
Referenced by hasCDEOps().
HasCRC
bool llvm::ARMSubtarget::HasCRC = false protected
HasCRC - if true, processor supports CRC instructions.
Definition at line 374 of file ARMSubtarget.h.
Referenced by hasCRC().
HasCrypto
bool llvm::ARMSubtarget::HasCrypto = false protected
HasCrypto - if true, processor supports Cryptography extensions.
Definition at line 371 of file ARMSubtarget.h.
Referenced by hasCrypto().
HasD32
bool llvm::ARMSubtarget::HasD32 = false protected
HasD32 - True if subtarget has the full 32 double precision FP registers for VFPv3.
Definition at line 292 of file ARMSubtarget.h.
Referenced by hasD32().
HasDataBarrier
bool llvm::ARMSubtarget::HasDataBarrier = false protected
HasDataBarrier - True if the subtarget supports DMB / DSB data barrier instructions.
Definition at line 302 of file ARMSubtarget.h.
Referenced by hasAnyDataBarrier(), and hasDataBarrier().
HasDotProd
bool llvm::ARMSubtarget::HasDotProd = false protected
HasDotProd - True if the ARMv8.2A dot product instructions are supported.
Definition at line 218 of file ARMSubtarget.h.
Referenced by hasDotProd().
HasDSP
bool llvm::ARMSubtarget::HasDSP = false protected
HasDSP - If true, the subtarget supports the DSP (saturating arith and such) instructions.
Definition at line 462 of file ARMSubtarget.h.
Referenced by hasDSP().
HasFP16
bool llvm::ARMSubtarget::HasFP16 = false protected
HasFP16 - True if subtarget supports half-precision FP conversions.
Definition at line 276 of file ARMSubtarget.h.
Referenced by hasFP16().
HasFP16FML
bool llvm::ARMSubtarget::HasFP16FML = false protected
HasFP16FML - True if subtarget supports half-precision FP fml operations.
Definition at line 282 of file ARMSubtarget.h.
Referenced by hasFP16FML().
HasFP64
bool llvm::ARMSubtarget::HasFP64 = false protected
HasFP64 - If true, the floating point unit supports double precision.
Definition at line 351 of file ARMSubtarget.h.
Referenced by hasFP64().
HasFPAO
bool llvm::ARMSubtarget::HasFPAO = false protected
HasFPAO - if true, processor does positive address offset computation faster.
Definition at line 389 of file ARMSubtarget.h.
Referenced by hasFPAO().
HasFPARMv8
bool llvm::ARMSubtarget::HasFPARMv8 = false protected
Definition at line 198 of file ARMSubtarget.h.
HasFPARMv8D16
bool llvm::ARMSubtarget::HasFPARMv8D16 = false protected
Definition at line 212 of file ARMSubtarget.h.
HasFPARMv8D16SP
bool llvm::ARMSubtarget::HasFPARMv8D16SP = false protected
Definition at line 215 of file ARMSubtarget.h.
Referenced by hasFPARMv8Base().
HasFPARMv8SP
bool llvm::ARMSubtarget::HasFPARMv8SP = false protected
Definition at line 209 of file ARMSubtarget.h.
HasFPRegs
bool llvm::ARMSubtarget::HasFPRegs = false protected
Definition at line 200 of file ARMSubtarget.h.
Referenced by hasFPRegs().
HasFPRegs16
bool llvm::ARMSubtarget::HasFPRegs16 = false protected
Definition at line 201 of file ARMSubtarget.h.
Referenced by hasFPRegs16().
HasFPRegs64
bool llvm::ARMSubtarget::HasFPRegs64 = false protected
Definition at line 202 of file ARMSubtarget.h.
Referenced by hasFPRegs64().
HasFullDataBarrier
bool llvm::ARMSubtarget::HasFullDataBarrier = false protected
HasFullDataBarrier - True if the subtarget supports DFB data barrier instruction.
Definition at line 306 of file ARMSubtarget.h.
Referenced by hasFullDataBarrier().
HasFullFP16
bool llvm::ARMSubtarget::HasFullFP16 = false protected
HasFullFP16 - True if subtarget supports half-precision FP operations.
Definition at line 279 of file ARMSubtarget.h.
Referenced by hasFullFP16().
HasFuseAES
bool llvm::ARMSubtarget::HasFuseAES = false protected
HasFuseAES - if true, processor executes back to back AES instruction pairs faster.
Definition at line 393 of file ARMSubtarget.h.
Referenced by hasFuseAES().
HasFuseLiterals
bool llvm::ARMSubtarget::HasFuseLiterals = false protected
HasFuseLiterals - if true, processor executes back to back bottom and top halves of literal generation faster.
Definition at line 397 of file ARMSubtarget.h.
Referenced by hasFuseLiterals().
HasHardwareDivideInARM
bool llvm::ARMSubtarget::HasHardwareDivideInARM = false protected
HasHardwareDivideInARM - True if subtarget supports [su]div in ARM mode.
Definition at line 298 of file ARMSubtarget.h.
Referenced by hasDivideInARMMode().
HasHardwareDivideInThumb
bool llvm::ARMSubtarget::HasHardwareDivideInThumb = false protected
HasHardwareDivide - True if subtarget supports [su]div in Thumb mode.
Definition at line 295 of file ARMSubtarget.h.
Referenced by hasDivideInThumbMode().
HasLOB
bool llvm::ARMSubtarget::HasLOB = false protected
HasLOB - if true, the processor supports the Low Overhead Branch extension.
Definition at line 380 of file ARMSubtarget.h.
Referenced by hasLOB().
HasMatMulInt8
bool llvm::ARMSubtarget::HasMatMulInt8 = false protected
HasMatMulInt8 - True if subtarget supports 8-bit integer matrix multiply.
Definition at line 288 of file ARMSubtarget.h.
Referenced by hasMatMulInt8().
HasMPExtension
bool llvm::ARMSubtarget::HasMPExtension = false protected
HasMPExtension - True if the subtarget supports Multiprocessing extension (ARMv7 only).
Definition at line 343 of file ARMSubtarget.h.
Referenced by hasMPExtension().
HasMuxedUnits
bool llvm::ARMSubtarget::HasMuxedUnits = false protected
If true, the AGU and NEON/FPU units are multiplexed.
Definition at line 425 of file ARMSubtarget.h.
Referenced by hasMuxedUnits().
HasMVEFloatOps
bool llvm::ARMSubtarget::HasMVEFloatOps = false protected
Definition at line 190 of file ARMSubtarget.h.
Referenced by hasMVEFloatOps().
HasMVEIntegerOps
bool llvm::ARMSubtarget::HasMVEIntegerOps = false protected
Definition at line 189 of file ARMSubtarget.h.
Referenced by hasMVEIntegerOps().
HasNEON
bool llvm::ARMSubtarget::HasNEON = false protected
Definition at line 199 of file ARMSubtarget.h.
Referenced by hasNEON().
HasPACBTI
bool llvm::ARMSubtarget::HasPACBTI = false protected
Definition at line 382 of file ARMSubtarget.h.
Referenced by hasPACBTI().
HasPerfMon
bool llvm::ARMSubtarget::HasPerfMon = false protected
If true, the processor supports the Performance Monitor Extensions.
These include a generic cycle-counter as well as more fine-grained (often implementation-specific) events.
Definition at line 356 of file ARMSubtarget.h.
Referenced by hasPerfMon().
HasRAS
bool llvm::ARMSubtarget::HasRAS = false protected
HasRAS - if true, the processor supports RAS extensions.
Definition at line 377 of file ARMSubtarget.h.
Referenced by hasRAS().
HasRetAddrStack
bool llvm::ARMSubtarget::HasRetAddrStack = false protected
HasRetAddrStack - Some processors perform return stack prediction.
CodeGen should avoid issue "normal" call instructions to callees which do not return.
Definition at line 334 of file ARMSubtarget.h.
Referenced by hasRetAddrStack().
HasSB
bool llvm::ARMSubtarget::HasSB = false protected
Has speculation barrier.
Definition at line 480 of file ARMSubtarget.h.
Referenced by hasSB().
HasSHA2
bool llvm::ARMSubtarget::HasSHA2 = false protected
HasSHA2 - if true, processor supports SHA1 and SHA256.
Definition at line 365 of file ARMSubtarget.h.
Referenced by hasSHA2().
HasSlowVDUP32
bool llvm::ARMSubtarget::HasSlowVDUP32 = false protected
If true, VMOV will be favored over VDUP.
Definition at line 406 of file ARMSubtarget.h.
Referenced by hasSlowVDUP32().
HasSlowVGETLNi32
bool llvm::ARMSubtarget::HasSlowVGETLNi32 = false protected
If true, VMOV will be favored over VGETLNi32.
Definition at line 403 of file ARMSubtarget.h.
Referenced by hasSlowVGETLNi32().
HasThumb2
bool llvm::ARMSubtarget::HasThumb2 = false protected
HasThumb2 - True if Thumb2 instructions are supported.
Definition at line 258 of file ARMSubtarget.h.
Referenced by hasThumb2(), isThumb1Only(), and isThumb2().
HasTrustZone
bool llvm::ARMSubtarget::HasTrustZone = false protected
HasTrustZone - if true, processor supports TrustZone security extensions.
Definition at line 359 of file ARMSubtarget.h.
Referenced by hasTrustZone().
HasV4TOps
bool llvm::ARMSubtarget::HasV4TOps = false protected
HasV4TOps, HasV5TOps, HasV5TEOps, HasV6Ops, HasV6MOps, HasV6KOps, HasV6T2Ops, HasV7Ops, HasV8Ops - Specify whether target support specific ARM ISA variants.
Definition at line 165 of file ARMSubtarget.h.
Referenced by hasV4TOps().
HasV5TEOps
bool llvm::ARMSubtarget::HasV5TEOps = false protected
Definition at line 167 of file ARMSubtarget.h.
Referenced by hasV5TEOps().
HasV5TOps
bool llvm::ARMSubtarget::HasV5TOps = false protected
Definition at line 166 of file ARMSubtarget.h.
Referenced by hasV5TOps().
HasV6KOps
bool llvm::ARMSubtarget::HasV6KOps = false protected
Definition at line 170 of file ARMSubtarget.h.
Referenced by hasV6KOps().
HasV6MOps
bool llvm::ARMSubtarget::HasV6MOps = false protected
Definition at line 169 of file ARMSubtarget.h.
Referenced by hasV6MOps().
HasV6Ops
bool llvm::ARMSubtarget::HasV6Ops = false protected
Definition at line 168 of file ARMSubtarget.h.
Referenced by hasV6Ops(), and isR9Reserved().
HasV6T2Ops
bool llvm::ARMSubtarget::HasV6T2Ops = false protected
Definition at line 171 of file ARMSubtarget.h.
Referenced by hasV6T2Ops().
HasV7Clrex
bool llvm::ARMSubtarget::HasV7Clrex = false protected
HasV7Clrex - True if the subtarget supports CLREX instructions.
Definition at line 309 of file ARMSubtarget.h.
Referenced by hasV7Clrex().
HasV7Ops
bool llvm::ARMSubtarget::HasV7Ops = false protected
Definition at line 172 of file ARMSubtarget.h.
Referenced by hasV7Ops().
HasV8_1aOps
bool llvm::ARMSubtarget::HasV8_1aOps = false protected
Definition at line 174 of file ARMSubtarget.h.
Referenced by hasV8_1aOps().
HasV8_1MMainlineOps
bool llvm::ARMSubtarget::HasV8_1MMainlineOps = false protected
Definition at line 188 of file ARMSubtarget.h.
Referenced by hasV8_1MMainlineOps().
HasV8_2aOps
bool llvm::ARMSubtarget::HasV8_2aOps = false protected
Definition at line 175 of file ARMSubtarget.h.
Referenced by hasV8_2aOps().
HasV8_3aOps
bool llvm::ARMSubtarget::HasV8_3aOps = false protected
Definition at line 176 of file ARMSubtarget.h.
Referenced by hasV8_3aOps().
HasV8_4aOps
bool llvm::ARMSubtarget::HasV8_4aOps = false protected
Definition at line 177 of file ARMSubtarget.h.
Referenced by hasV8_4aOps().
HasV8_5aOps
bool llvm::ARMSubtarget::HasV8_5aOps = false protected
Definition at line 178 of file ARMSubtarget.h.
Referenced by hasV8_5aOps().
HasV8_6aOps
bool llvm::ARMSubtarget::HasV8_6aOps = false protected
Definition at line 179 of file ARMSubtarget.h.
Referenced by hasV8_6aOps().
HasV8_7aOps
bool llvm::ARMSubtarget::HasV8_7aOps = false protected
Definition at line 181 of file ARMSubtarget.h.
Referenced by hasV8_7aOps().
HasV8_8aOps
bool llvm::ARMSubtarget::HasV8_8aOps = false protected
Definition at line 180 of file ARMSubtarget.h.
Referenced by hasV8_8aOps().
HasV8MBaselineOps
bool llvm::ARMSubtarget::HasV8MBaselineOps = false protected
Definition at line 186 of file ARMSubtarget.h.
Referenced by hasV8MBaselineOps().
HasV8MMainlineOps
bool llvm::ARMSubtarget::HasV8MMainlineOps = false protected
Definition at line 187 of file ARMSubtarget.h.
Referenced by hasV8MMainlineOps().
HasV8Ops
bool llvm::ARMSubtarget::HasV8Ops = false protected
Definition at line 173 of file ARMSubtarget.h.
Referenced by hasV8Ops().
HasV9_0aOps
bool llvm::ARMSubtarget::HasV9_0aOps = false protected
Definition at line 182 of file ARMSubtarget.h.
Referenced by hasV9_0aOps().
HasV9_1aOps
bool llvm::ARMSubtarget::HasV9_1aOps = false protected
Definition at line 183 of file ARMSubtarget.h.
Referenced by hasV9_1aOps().
HasV9_2aOps
bool llvm::ARMSubtarget::HasV9_2aOps = false protected
Definition at line 184 of file ARMSubtarget.h.
Referenced by hasV9_2aOps().
HasV9_3aOps
bool llvm::ARMSubtarget::HasV9_3aOps = false protected
Definition at line 185 of file ARMSubtarget.h.
Referenced by hasV9_3aOps().
HasVFPv2
bool llvm::ARMSubtarget::HasVFPv2 = false protected
HasVFPv2, HasVFPv3, HasVFPv4, HasFPARMv8, HasNEON - Specify what floating point ISAs are supported.
Definition at line 195 of file ARMSubtarget.h.
HasVFPv2SP
bool llvm::ARMSubtarget::HasVFPv2SP = false protected
Versions of the VFP flags restricted to single precision, or to 16 d-registers, or both.
Definition at line 206 of file ARMSubtarget.h.
Referenced by hasVFP2Base().
HasVFPv3
bool llvm::ARMSubtarget::HasVFPv3 = false protected
Definition at line 196 of file ARMSubtarget.h.
HasVFPv3D16
bool llvm::ARMSubtarget::HasVFPv3D16 = false protected
Definition at line 210 of file ARMSubtarget.h.
HasVFPv3D16SP
bool llvm::ARMSubtarget::HasVFPv3D16SP = false protected
Definition at line 213 of file ARMSubtarget.h.
Referenced by hasVFP3Base().
HasVFPv3SP
bool llvm::ARMSubtarget::HasVFPv3SP = false protected
Definition at line 207 of file ARMSubtarget.h.
HasVFPv4
bool llvm::ARMSubtarget::HasVFPv4 = false protected
Definition at line 197 of file ARMSubtarget.h.
HasVFPv4D16
bool llvm::ARMSubtarget::HasVFPv4D16 = false protected
Definition at line 211 of file ARMSubtarget.h.
HasVFPv4D16SP
bool llvm::ARMSubtarget::HasVFPv4D16SP = false protected
Definition at line 214 of file ARMSubtarget.h.
Referenced by hasVFP4Base().
HasVFPv4SP
bool llvm::ARMSubtarget::HasVFPv4SP = false protected
Definition at line 208 of file ARMSubtarget.h.
HasVirtualization
bool llvm::ARMSubtarget::HasVirtualization = false protected
HasVirtualization - True if the subtarget supports the Virtualization extension.
Definition at line 347 of file ARMSubtarget.h.
Referenced by hasVirtualization().
HasVMLxForwarding
bool llvm::ARMSubtarget::HasVMLxForwarding = false protected
HasVMLxForwarding - If true, NEON has special multiplier accumulator forwarding to allow mul + mla being issued back to back.
Definition at line 239 of file ARMSubtarget.h.
Referenced by hasVMLxForwarding().
HasVMLxHazards
bool llvm::ARMSubtarget::HasVMLxHazards = false protected
If true, VFP/NEON VMLA/VMLS have special RAW hazards.
Definition at line 437 of file ARMSubtarget.h.
Referenced by hasVMLxHazards().
HasZeroCycleZeroing
bool llvm::ARMSubtarget::HasZeroCycleZeroing = false protected
If true, the instructions "vmov.i32 d0, #0" and "vmov.i32 q0, #0" are particularly effective at zeroing a VFP register.
Definition at line 386 of file ARMSubtarget.h.
Referenced by hasZeroCycleZeroing().
InstrItins
InstrItineraryData llvm::ARMSubtarget::InstrItins protected
Selected instruction itineraries (one entry per itinerary class.)
Definition at line 541 of file ARMSubtarget.h.
Referenced by getInstrItineraryData().
InThumbMode
bool llvm::ARMSubtarget::InThumbMode = false protected
InThumbMode - True if compiling for Thumb, false for ARM.
Definition at line 245 of file ARMSubtarget.h.
Referenced by isThumb(), isThumb1Only(), and isThumb2().
IsLittle
bool llvm::ARMSubtarget::IsLittle protected
IsLittle - The target is Little Endian.
Definition at line 532 of file ARMSubtarget.h.
Referenced by isLittle().
IsProfitableToUnpredicate
bool llvm::ARMSubtarget::IsProfitableToUnpredicate = false protected
If true, if conversion may decide to leave some instructions unpredicated.
Definition at line 400 of file ARMSubtarget.h.
Referenced by isProfitableToUnpredicate().
LdStMultipleTiming
ARMLdStMultipleTiming llvm::ARMSubtarget::LdStMultipleTiming = SingleIssue protected
What kind of timing do load multiple/store multiple have (double issue, single issue etc).
Definition at line 513 of file ARMSubtarget.h.
Referenced by getLdStMultipleTiming().
MaxInterleaveFactor
unsigned llvm::ARMSubtarget::MaxInterleaveFactor = 1 protected
Definition at line 506 of file ARMSubtarget.h.
Referenced by getMaxInterleaveFactor().
MVEVectorCostFactor
unsigned llvm::ARMSubtarget::MVEVectorCostFactor = 0 protected
The cost factor for MVE instructions, representing the multiple beats an.
Definition at line 525 of file ARMSubtarget.h.
Referenced by getMVEVectorCostFactor().
NegativeImmediates
bool llvm::ARMSubtarget::NegativeImmediates = true protected
Implicitly convert an instruction to a different one if its immediates cannot be encoded.
For example, ADD r0, r1, #FFFFFFFF -> SUB r0, r1, #1.
Definition at line 484 of file ARMSubtarget.h.
NoARM
bool llvm::ARMSubtarget::NoARM = false protected
NoARM - True if subtarget does not support ARM mode execution.
Definition at line 261 of file ARMSubtarget.h.
Referenced by hasARMOps().
NoBTIAtReturnTwice
bool llvm::ARMSubtarget::NoBTIAtReturnTwice = false protected
NoBTIAtReturnTwice - Don't place a BTI instruction after return-twice constructs (setjmp)
Definition at line 545 of file ARMSubtarget.h.
Referenced by getNoBTIAtReturnTwice().
NoMovt
bool llvm::ARMSubtarget::NoMovt = false protected
NoMovt - True if MOVT / MOVW pairs are not used for materialization of 32-bit imms (including global addresses).
Definition at line 268 of file ARMSubtarget.h.
Referenced by useMovt().
NonpipelinedVFP
bool llvm::ARMSubtarget::NonpipelinedVFP = false protected
If true, VFP instructions are not pipelined.
Definition at line 449 of file ARMSubtarget.h.
Referenced by nonpipelinedVFP().
Options
const TargetOptions& llvm::ARMSubtarget::Options protected
Options passed via command line that could influence the target.
Definition at line 548 of file ARMSubtarget.h.
OptMinSize
bool llvm::ARMSubtarget::OptMinSize = false protected
OptMinSize - True if we're optimising for minimum code size, equal to the function attribute.
Definition at line 529 of file ARMSubtarget.h.
Referenced by hasMinSize(), useMovt(), and useStride4VFPs().
PartialUpdateClearance
unsigned llvm::ARMSubtarget::PartialUpdateClearance = 0 protected
Clearance before partial register updates (in number of instructions)
Definition at line 509 of file ARMSubtarget.h.
Referenced by getPartialUpdateClearance().
Pref32BitThumb
bool llvm::ARMSubtarget::Pref32BitThumb = false protected
Pref32BitThumb - If true, codegen would prefer 32-bit Thumb instructions over 16-bit ones.
Definition at line 317 of file ARMSubtarget.h.
Referenced by prefers32BitThumb().
PreferISHST
bool llvm::ARMSubtarget::PreferISHST = false protected
If true, ISHST barriers will be used for Release semantics.
Definition at line 412 of file ARMSubtarget.h.
Referenced by preferISHSTBarriers().
PreferVMOVSR
bool llvm::ARMSubtarget::PreferVMOVSR = false protected
If true, VMOVSR will be favored over VMOVDRR.
Definition at line 409 of file ARMSubtarget.h.
Referenced by preferVMOVSR().
PrefLoopLogAlignment
unsigned llvm::ARMSubtarget::PrefLoopLogAlignment = 0 protected
What alignment is preferred for loop bodies, in log2(bytes).
Definition at line 520 of file ARMSubtarget.h.
Referenced by getPrefLoopLogAlignment().
PreISelOperandLatencyAdjustment
int llvm::ARMSubtarget::PreISelOperandLatencyAdjustment = 2 protected
The adjustment that we need to apply to get the operand latency from the operand cycle returned by the itinerary data for pre-ISel operands.
Definition at line 517 of file ARMSubtarget.h.
Referenced by getPreISelOperandLatencyAdjustment().
ReadTPHard
bool llvm::ARMSubtarget::ReadTPHard = false protected
Definition at line 440 of file ARMSubtarget.h.
Referenced by isReadTPHard().
ReserveR9
bool llvm::ARMSubtarget::ReserveR9 = false protected
ReserveR9 - True if R9 is not available as a general purpose register.
Definition at line 264 of file ARMSubtarget.h.
Referenced by isR9Reserved().
RestrictIT
bool llvm::ARMSubtarget::RestrictIT = false protected
RestrictIT - If true, the subtarget disallows generation of deprecated IT blocks to conform to ARMv8 rule.
Definition at line 458 of file ARMSubtarget.h.
Referenced by restrictIT().
SchedModel
MCSchedModel llvm::ARMSubtarget::SchedModel protected
SchedModel - Processor specific instruction costs.
Definition at line 538 of file ARMSubtarget.h.
Referenced by getMispredictionPenalty().
SlowFPBrcc
bool llvm::ARMSubtarget::SlowFPBrcc = false protected
SlowFPBrcc - True if floating point compare + branch is slow.
Definition at line 242 of file ARMSubtarget.h.
Referenced by isFPBrccSlow().
SlowFPVFMx
bool llvm::ARMSubtarget::SlowFPVFMx = false protected
SlowFPVFMx - If the VFP4 / NEON instructions are available, indicates whether the FP VFM[AS] instructions are slow (if so, don't use them).
Definition at line 235 of file ARMSubtarget.h.
Referenced by useFPVFMx().
SlowFPVMLx
bool llvm::ARMSubtarget::SlowFPVMLx = false protected
SlowFPVMLx - If the VFP2 / NEON instructions are available, indicates whether the FP VML[AS] instructions are slow (if so, don't use them).
Definition at line 231 of file ARMSubtarget.h.
Referenced by useFPVMLx().
SlowLoadDSubregister
bool llvm::ARMSubtarget::SlowLoadDSubregister = false protected
If true, loading into a D subregister will be penalized.
Definition at line 419 of file ARMSubtarget.h.
Referenced by hasSlowLoadDSubregister().
SlowOddRegister
bool llvm::ARMSubtarget::SlowOddRegister = false protected
If true, a VLDM/VSTM starting with an odd register number is considered to take more microops than single VLDRS/VSTRS.
Definition at line 416 of file ARMSubtarget.h.
Referenced by hasSlowOddRegister().
SplatVFPToNeon
bool llvm::ARMSubtarget::SplatVFPToNeon = false protected
If true, splat a register between VFP and NEON instructions.
Definition at line 431 of file ARMSubtarget.h.
Referenced by useSplatVFPToNeon().
stackAlignment
Align llvm::ARMSubtarget::stackAlignment = Align(4) protected
stackAlignment - The minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function.
Definition at line 501 of file ARMSubtarget.h.
Referenced by getStackAlignment().
StrictAlign
bool llvm::ARMSubtarget::StrictAlign = false protected
StrictAlign - If true, the subtarget disallows unaligned memory accesses for some types.
For details, see ARMTargetLowering::allowsMisalignedMemoryAccesses().
Definition at line 454 of file ARMSubtarget.h.
Referenced by allowsUnalignedMem().
SupportsTailCall
bool llvm::ARMSubtarget::SupportsTailCall = false protected
SupportsTailCall - True if the OS supports tail call.
The dynamic linker must be able to synthesize call stubs for interworking between ARM and Thumb.
Definition at line 273 of file ARMSubtarget.h.
Referenced by supportsTailCall().
TargetTriple
Triple llvm::ARMSubtarget::TargetTriple protected
TargetTriple - What processor and OS we're targeting.
Definition at line 535 of file ARMSubtarget.h.
Referenced by getTargetTriple(), isTargetAEABI(), isTargetAndroid(), isTargetCOFF(), isTargetDarwin(), isTargetEHABICompatible(), isTargetELF(), isTargetGNUAEABI(), isTargetIOS(), isTargetLinux(), isTargetMachO(), isTargetMuslAEABI(), isTargetNaCl(), isTargetNetBSD(), isTargetWatchABI(), isTargetWatchOS(), and isTargetWindows().
TM
const ARMBaseTargetMachine& llvm::ARMSubtarget::TM protected
Definition at line 550 of file ARMSubtarget.h.
Referenced by ARMSubtarget(), isAAPCS16_ABI(), isAAPCS_ABI(), isAPCS_ABI(), isGVIndirectSymbol(), isGVInGOT(), isROPI(), isRWPI(), isTargetHardFloat(), and useFastISel().
UnsafeFPMath
bool llvm::ARMSubtarget::UnsafeFPMath = false protected
Target machine allowed unsafe FP math (such as use of NEON fp)
Definition at line 474 of file ARMSubtarget.h.
UseMISched
bool llvm::ARMSubtarget::UseMISched = false protected
UseMISched - True if MachineScheduler should be used for this subtarget.
Definition at line 251 of file ARMSubtarget.h.
Referenced by useMachineScheduler().
UseMulOps
bool llvm::ARMSubtarget::UseMulOps = false protected
UseMulOps - True if non-microcoded fused integer multiply-add and multiply-subtract instructions should be used.
Definition at line 227 of file ARMSubtarget.h.
Referenced by useMulOps().
UseNaClTrap
bool llvm::ARMSubtarget::UseNaClTrap = false protected
NaCl TRAP instruction is generated instead of the regular TRAP.
Definition at line 465 of file ARMSubtarget.h.
Referenced by useNaClTrap().
UseNEONForFPMovs
bool llvm::ARMSubtarget::UseNEONForFPMovs = false protected
If true, VMOVRS, VMOVSR and VMOVS will be converted from VFP to NEON.
Definition at line 443 of file ARMSubtarget.h.
Referenced by useNEONForFPMovs().
UseNEONForSinglePrecisionFP
bool llvm::ARMSubtarget::UseNEONForSinglePrecisionFP = false protected
UseNEONForSinglePrecisionFP - if the NEONFP attribute has been specified.
Use the method useNEONForSinglePrecisionFP() to determine if NEON should actually be used.
Definition at line 223 of file ARMSubtarget.h.
Referenced by useNEONForSinglePrecisionFP().
UseSjLjEH
bool llvm::ARMSubtarget::UseSjLjEH = false protected
UseSjLjEH - If true, the target uses SjLj exception handling (e.g. iOS).
Definition at line 477 of file ARMSubtarget.h.
Referenced by useSjLjEH().
UseSoftFloat
bool llvm::ARMSubtarget::UseSoftFloat = false protected
UseSoftFloat - True if we're using software floating point features.
Definition at line 248 of file ARMSubtarget.h.
Referenced by useSoftFloat().
UseWideStrideVFP
bool llvm::ARMSubtarget::UseWideStrideVFP = false protected
If true, use a wider stride when allocating VFP registers.
Definition at line 422 of file ARMSubtarget.h.
Referenced by useWideStrideVFP().
The documentation for this class was generated from the following files:
lib/Target/ARM/ARMSubtarget.h
lib/Target/ARM/ARMSubtarget.cpp