LLVM: llvm::AttributeSet Class Reference
llvm::AttributeSet Class Reference
#include "llvm/IR/Attributes.h"
Public Types
using iterator = const Attribute *
Public Member Functions
AttributeSet ()=default
AttributeSet is a trivially copyable value type.
AttributeSet (const AttributeSet &)=default
~AttributeSet ()=default
bool operator== (const AttributeSet &O) const
bool operator!= (const AttributeSet &O) const
LLVM_NODISCARD AttributeSet addAttribute (LLVMContext &C, Attribute::AttrKind Kind) const
Add an argument attribute.
LLVM_NODISCARD AttributeSet addAttribute (LLVMContext &C, StringRef Kind, StringRef Value=StringRef()) const
Add a target-dependent attribute.
LLVM_NODISCARD AttributeSet addAttributes (LLVMContext &C, AttributeSet AS) const
Add attributes to the attribute set.
LLVM_NODISCARD AttributeSet removeAttribute (LLVMContext &C, Attribute::AttrKind Kind) const
Remove the specified attribute from this set.
LLVM_NODISCARD AttributeSet removeAttribute (LLVMContext &C, StringRef Kind) const
Remove the specified attribute from this set.
LLVM_NODISCARD AttributeSet removeAttributes (LLVMContext &C, const AttributeMask &AttrsToRemove) const
Remove the specified attributes from this set.
unsigned getNumAttributes () const
Return the number of attributes in this set.
bool hasAttributes () const
Return true if attributes exists in this set.
bool hasAttribute (Attribute::AttrKind Kind) const
Return true if the attribute exists in this set.
bool hasAttribute (StringRef Kind) const
Return true if the attribute exists in this set.
Attribute getAttribute (Attribute::AttrKind Kind) const
Return the attribute object.
Attribute getAttribute (StringRef Kind) const
Return the target-dependent attribute object.
MaybeAlign getAlignment () const
MaybeAlign getStackAlignment () const
uint64_t getDereferenceableBytes () const
uint64_t getDereferenceableOrNullBytes () const
Type * getByValType () const
Type * getStructRetType () const
Type * getByRefType () const
Type * getPreallocatedType () const
Type * getInAllocaType () const
Type * getElementType () const
std::pair< unsigned, Optional< unsigned > > getAllocSizeArgs () const
unsigned getVScaleRangeMin () const
Optional< unsigned > getVScaleRangeMax () const
std::string getAsString (bool InAttrGrp=false) const
bool hasParentContext (LLVMContext &C) const
Return true if this attribute set belongs to the LLVMContext.
iterator begin () const
iterator end () const
void dump () const
Static Public Member Functions
static AttributeSet get (LLVMContext &C, const AttrBuilder &B)
static AttributeSet get (LLVMContext &C, ArrayRef< Attribute > Attrs)
Friends
template<typename Ty , typename Enable >
struct DenseMapInfo
Detailed Description
Definition at line 269 of file Attributes.h.
Member Typedef Documentation
iterator
using llvm::AttributeSet::iterator = const Attribute *
Definition at line 361 of file Attributes.h.
Constructor & Destructor Documentation
AttributeSet() [1/2]
llvm::AttributeSet::AttributeSet () default
AttributeSet is a trivially copyable value type.
Referenced by get(), and get().
AttributeSet() [2/2]
llvm::AttributeSet::AttributeSet (const AttributeSet &) default
~AttributeSet()
llvm::AttributeSet::~AttributeSet () default
Member Function Documentation
addAttribute() [1/2]
AttributeSet AttributeSet::addAttribute (LLVMContext & C, Attribute::AttrKind Kind) const
Add an argument attribute.
Returns a new set because attribute sets are immutable.
Definition at line 585 of file Attributes.cpp.
References addAttributes(), B, C, get(), and hasAttribute().
addAttribute() [2/2]
AttributeSet AttributeSet::addAttribute (LLVMContext & C, StringRef Kind, StringRef Value = StringRef()) const
Add a target-dependent attribute.
Returns a new set because attribute sets are immutable.
Definition at line 593 of file Attributes.cpp.
References addAttributes(), B, C, and get().
addAttributes()
AttributeSet AttributeSet::addAttributes (LLVMContext & C, AttributeSet AS) const
Add attributes to the attribute set.
Returns a new set because attribute sets are immutable.
Definition at line 600 of file Attributes.cpp.
References B, C, get(), and hasAttributes().
Referenced by addAttribute(), and addAttribute().
begin()
AttributeSet::iterator AttributeSet::begin () const
Definition at line 725 of file Attributes.cpp.
References llvm::AttributeSetNode::begin().
dump()
LLVM_DUMP_METHOD void AttributeSet::dump () const
Definition at line 734 of file Attributes.cpp.
References llvm::dbgs(), and getAsString().
end()
AttributeSet::iterator AttributeSet::end () const
Definition at line 729 of file Attributes.cpp.
References llvm::AttributeSetNode::end().
get() [1/2]
AttributeSet AttributeSet::get (LLVMContext & C, ArrayRef< Attribute > Attrs) static
Definition at line 581 of file Attributes.cpp.
References AttributeSet(), C, and llvm::AttributeSetNode::get().
get() [2/2]
AttributeSet AttributeSet::get (LLVMContext & C, const AttrBuilder & B) static
Definition at line 577 of file Attributes.cpp.
References AttributeSet(), B, C, and llvm::AttributeSetNode::get().
Referenced by addAttribute(), addAttribute(), llvm::AttributeList::addAttributeAtIndex(), addAttributes(), llvm::AttributeList::addAttributesAtIndex(), llvm::AttributeList::addParamAttribute(), llvm::AttributeList::get(), llvm::AttributeList::get(), llvm::AttributeList::get(), legalizeCallAttributes(), llvm::promoteCall(), removeAttribute(), removeAttribute(), and removeAttributes().
getAlignment()
MaybeAlign AttributeSet::getAlignment () const
Definition at line 660 of file Attributes.cpp.
References llvm::AttributeSetNode::getAlignment(), and llvm::None.
Referenced by llvm::AttributeList::getParamAlignment(), and llvm::AttributeList::getRetAlignment().
getAllocSizeArgs()
std::pair< unsigned, Optional< unsigned > > AttributeSet::getAllocSizeArgs () const
Definition at line 700 of file Attributes.cpp.
References llvm::AttributeSetNode::getAllocSizeArgs().
getAsString()
std::string AttributeSet::getAsString (bool InAttrGrp = false) const
Definition at line 713 of file Attributes.cpp.
References llvm::AttributeSetNode::getAsString().
Referenced by dump(), and llvm::AttributeList::getAsString().
getAttribute() [1/2]
Attribute AttributeSet::getAttribute (Attribute::AttrKind Kind) const
Return the attribute object.
Definition at line 652 of file Attributes.cpp.
References llvm::Attribute, and llvm::AttributeSetNode::getAttribute().
Referenced by llvm::AttributeList::getAttributeAtIndex(), and llvm::AttributeList::getAttributeAtIndex().
getAttribute() [2/2]
Attribute AttributeSet::getAttribute (StringRef Kind) const
Return the target-dependent attribute object.
Definition at line 656 of file Attributes.cpp.
References llvm::Attribute, and llvm::AttributeSetNode::getAttribute().
getByRefType()
Type * AttributeSet::getByRefType () const
Definition at line 676 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttributeType().
Referenced by llvm::AttributeList::getParamByRefType().
getByValType()
Type * AttributeSet::getByValType () const
Definition at line 680 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttributeType().
Referenced by llvm::AttributeList::getParamByValType().
getDereferenceableBytes()
uint64_t AttributeSet::getDereferenceableBytes () const
Definition at line 668 of file Attributes.cpp.
References llvm::AttributeSetNode::getDereferenceableBytes().
Referenced by llvm::AttributeList::getParamDereferenceableBytes(), and llvm::AttributeList::getRetDereferenceableBytes().
getDereferenceableOrNullBytes()
uint64_t AttributeSet::getDereferenceableOrNullBytes () const
Definition at line 672 of file Attributes.cpp.
References llvm::AttributeSetNode::getDereferenceableOrNullBytes().
Referenced by llvm::AttributeList::getParamDereferenceableOrNullBytes(), and llvm::AttributeList::getRetDereferenceableOrNullBytes().
getElementType()
Type * AttributeSet::getElementType () const
Definition at line 696 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttributeType().
Referenced by llvm::AttributeList::getParamElementType().
getInAllocaType()
Type * AttributeSet::getInAllocaType () const
Definition at line 692 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttributeType().
Referenced by llvm::AttributeList::getParamInAllocaType().
getNumAttributes()
unsigned AttributeSet::getNumAttributes () const
Return the number of attributes in this set.
Definition at line 640 of file Attributes.cpp.
References llvm::AttributeSetNode::getNumAttributes().
getPreallocatedType()
Type * AttributeSet::getPreallocatedType () const
Definition at line 688 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttributeType().
Referenced by llvm::AttributeList::getParamPreallocatedType().
getStackAlignment()
MaybeAlign AttributeSet::getStackAlignment () const
Definition at line 664 of file Attributes.cpp.
References llvm::AttributeSetNode::getStackAlignment(), and llvm::None.
Referenced by llvm::AttributeList::getFnStackAlignment(), llvm::AttributeList::getParamStackAlignment(), and llvm::AttributeList::getRetStackAlignment().
getStructRetType()
Type * AttributeSet::getStructRetType () const
Definition at line 684 of file Attributes.cpp.
References llvm::AttributeSetNode::getAttributeType().
Referenced by llvm::AttributeList::getParamStructRetType().
getVScaleRangeMax()
Optional< unsigned > AttributeSet::getVScaleRangeMax () const
Definition at line 709 of file Attributes.cpp.
References llvm::AttributeSetNode::getVScaleRangeMax(), and llvm::None.
getVScaleRangeMin()
unsigned AttributeSet::getVScaleRangeMin () const
Definition at line 705 of file Attributes.cpp.
References llvm::AttributeSetNode::getVScaleRangeMin().
hasAttribute() [1/2]
bool AttributeSet::hasAttribute (Attribute::AttrKind Kind) const
Return true if the attribute exists in this set.
Definition at line 644 of file Attributes.cpp.
References llvm::AttributeSetNode::hasAttribute().
Referenced by addAttribute(), llvm::AttributeList::hasAttributeAtIndex(), llvm::AttributeList::hasAttributeAtIndex(), llvm::GlobalVariable::hasImplicitSection(), removeAttribute(), and removeAttribute().
hasAttribute() [2/2]
bool AttributeSet::hasAttribute (StringRef Kind) const
Return true if the attribute exists in this set.
Definition at line 648 of file Attributes.cpp.
References llvm::AttributeSetNode::hasAttribute().
hasAttributes()
bool llvm::AttributeSet::hasAttributes () const inline
Return true if attributes exists in this set.
Definition at line 329 of file Attributes.h.
Referenced by addAttributes(), llvm::AttributeList::hasAttributesAtIndex(), hasParentContext(), and llvm::AttributeList::print().
hasParentContext()
bool AttributeSet::hasParentContext (LLVMContext & C) const
Return true if this attribute set belongs to the LLVMContext.
Definition at line 717 of file Attributes.cpp.
References assert(), C, hasAttributes(), and llvm::AttributeSetNode::Profile().
operator!=()
bool llvm::AttributeSet::operator!= (const AttributeSet & O) const inline
Definition at line 293 of file Attributes.h.
operator==()
bool llvm::AttributeSet::operator== (const AttributeSet & O) const inline
Definition at line 292 of file Attributes.h.
removeAttribute() [1/2]
AttributeSet AttributeSet::removeAttribute (LLVMContext & C, Attribute::AttrKind Kind) const
Remove the specified attribute from this set.
Returns a new set because attribute sets are immutable.
Definition at line 613 of file Attributes.cpp.
References B, C, get(), and hasAttribute().
removeAttribute() [2/2]
AttributeSet AttributeSet::removeAttribute (LLVMContext & C, StringRef Kind) const
Remove the specified attribute from this set.
Returns a new set because attribute sets are immutable.
Definition at line 621 of file Attributes.cpp.
References B, C, get(), and hasAttribute().
removeAttributes()
AttributeSet AttributeSet::removeAttributes (LLVMContext & C, const AttributeMask & AttrsToRemove) const
Remove the specified attributes from this set.
Returns a new set because attribute sets are immutable.
Definition at line 629 of file Attributes.cpp.
References B, C, and get().
Friends And Related Symbol Documentation
DenseMapInfo
template<typename Ty , typename Enable > friend struct DenseMapInfo friend
Definition at line 271 of file Attributes.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Attributes.h
lib/IR/Attributes.cpp