LLVM: llvm::codeview::DebugCrossModuleImportsSubsectionRef Class Reference
llvm::codeview::DebugCrossModuleImportsSubsectionRef Class Reference final
#include "llvm/DebugInfo/CodeView/DebugCrossImpSubsection.h"
Public Member Functions
DebugCrossModuleImportsSubsectionRef ()
Error initialize (BinaryStreamReader Reader)
Error initialize (BinaryStreamRef Stream)
Iterator begin () const
Iterator end () const
Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionRef (DebugSubsectionKind Kind)
virtual ~DebugSubsectionRef ()
DebugSubsectionKind kind () const
Static Public Member Functions
static bool classof (const DebugSubsectionRef *S)
Static Public Member Functions inherited from llvm::codeview::DebugSubsectionRef
static bool classof (const DebugSubsectionRef *S)
Additional Inherited Members
Protected Attributes inherited from llvm::codeview::DebugSubsectionRef
DebugSubsectionKind Kind
Detailed Description
Definition at line 47 of file DebugCrossImpSubsection.h.
Constructor & Destructor Documentation
DebugCrossModuleImportsSubsectionRef()
llvm::codeview::DebugCrossModuleImportsSubsectionRef::DebugCrossModuleImportsSubsectionRef () inline
Definition at line 52 of file DebugCrossImpSubsection.h.
Member Function Documentation
begin()
Iterator llvm::codeview::DebugCrossModuleImportsSubsectionRef::begin () const inline
Definition at line 62 of file DebugCrossImpSubsection.h.
References llvm::VarStreamArray< ValueType, Extractor >::begin().
classof()
static bool llvm::codeview::DebugCrossModuleImportsSubsectionRef::classof (const DebugSubsectionRef * S) inline static
Definition at line 55 of file DebugCrossImpSubsection.h.
References llvm::codeview::CrossScopeImports, and llvm::codeview::DebugSubsectionRef::kind().
end()
Iterator llvm::codeview::DebugCrossModuleImportsSubsectionRef::end () const inline
Definition at line 63 of file DebugCrossImpSubsection.h.
References llvm::VarStreamArray< ValueType, Extractor >::end().
initialize() [1/2]
Error DebugCrossModuleImportsSubsectionRef::initialize (BinaryStreamReader Reader)
Definition at line 44 of file DebugCrossImpSubsection.cpp.
References llvm::BinaryStreamReader::bytesRemaining(), and llvm::BinaryStreamReader::readArray().
initialize() [2/2]
Error DebugCrossModuleImportsSubsectionRef::initialize (BinaryStreamRef Stream)
Definition at line 49 of file DebugCrossImpSubsection.cpp.
References initialize().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/DebugCrossImpSubsection.h
lib/DebugInfo/CodeView/DebugCrossImpSubsection.cpp