LLVM: llvm::sampleprof::CSProfileConverter Class Reference
llvm::sampleprof::CSProfileConverter Class Reference
#include "llvm/ProfileData/SampleProf.h"
Classes
struct FrameNode
Public Member Functions
CSProfileConverter (SampleProfileMap &Profiles)
void convertProfiles ()
Detailed Description
Definition at line 1187 of file SampleProf.h.
Constructor & Destructor Documentation
CSProfileConverter()
CSProfileConverter::CSProfileConverter (SampleProfileMap & Profiles)
Definition at line 486 of file SampleProf.cpp.
References assert().
Member Function Documentation
convertProfiles()
void CSProfileConverter::convertProfiles ()
Definition at line 547 of file SampleProf.cpp.
References convertProfiles().
Referenced by convertProfiles().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProf.h
lib/ProfileData/SampleProf.cpp