LLVM: llvm::DWARFContext Class Reference
llvm::DWARFContext Class Reference
DWARFContext This data structure is the top level entity that deals with dwarf debug information parsing.
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
Classes
struct DIEsForAddress
Wraps the returned DIEs for a given address.
Public Types
enum class ProcessDebugRelocations { Process , Ignore }
using unit_iterator_range = DWARFUnitVector::iterator_range
using compile_unit_range = DWARFUnitVector::compile_unit_range
Public Types inherited from llvm::DIContext
enum DIContextKind { CK_DWARF , CK_PDB }
Public Member Functions
DWARFContext (std::unique_ptr< const DWARFObject > DObj, std::string DWPName="", std::function< void(Error)> RecoverableErrorHandler=WithColor::defaultErrorHandler, std::function< void(Error)> WarningHandler=WithColor::defaultWarningHandler)
~DWARFContext ()
DWARFContext (DWARFContext &)=delete
DWARFContext & operator= (DWARFContext &)=delete
const DWARFObject & getDWARFObj () const
void dump (raw_ostream &OS, DIDumpOptions DumpOpts, std::array< Optional< uint64_t >, DIDT_ID_Count > DumpOffsets)
Dump a textual representation to OS.
void dump (raw_ostream &OS, DIDumpOptions DumpOpts) override
bool verify (raw_ostream &OS, DIDumpOptions DumpOpts={}) override
unit_iterator_range info_section_units ()
Get units from .debug_info in this context.
const DWARFUnitVector & getNormalUnitsVector ()
unit_iterator_range types_section_units ()
Get units from .debug_types in this context.
compile_unit_range compile_units ()
Get compile units in this context.
unit_iterator_range normal_units ()
Get all normal compile/type units in this context.
unit_iterator_range dwo_info_section_units ()
Get units from .debug_info..dwo in the DWO context.
const DWARFUnitVector & getDWOUnitsVector ()
unit_iterator_range dwo_types_section_units ()
Get units from .debug_types.dwo in the DWO context.
compile_unit_range dwo_compile_units ()
Get compile units in the DWO context.
unit_iterator_range dwo_units ()
Get all units in the DWO context.
unsigned getNumCompileUnits ()
Get the number of compile units in this context.
unsigned getNumTypeUnits ()
Get the number of type units in this context.
unsigned getNumDWOCompileUnits ()
Get the number of compile units in the DWO context.
unsigned getNumDWOTypeUnits ()
Get the number of type units in the DWO context.
DWARFUnit * getUnitAtIndex (unsigned index)
Get the unit at the specified index.
DWARFUnit * getDWOUnitAtIndex (unsigned index)
Get the unit at the specified index for the DWO units.
DWARFCompileUnit * getDWOCompileUnitForHash (uint64_t Hash)
DWARFTypeUnit * getTypeUnitForHash (uint16_t Version, uint64_t Hash, bool IsDWO)
DWARFCompileUnit * getCompileUnitForOffset (uint64_t Offset)
Return the compile unit that includes an offset (relative to .debug_info).
DWARFDie getDIEForOffset (uint64_t Offset)
Get a DIE given an exact offset.
unsigned getMaxVersion ()
unsigned getMaxDWOVersion ()
void setMaxVersionIfGreater (unsigned Version)
const DWARFUnitIndex & getCUIndex ()
DWARFGdbIndex & getGdbIndex ()
const DWARFUnitIndex & getTUIndex ()
const DWARFDebugAbbrev * getDebugAbbrev ()
Get a pointer to the parsed DebugAbbrev object.
const DWARFDebugLoc * getDebugLoc ()
Get a pointer to the parsed DebugLoc object.
const DWARFDebugAbbrev * getDebugAbbrevDWO ()
Get a pointer to the parsed dwo abbreviations object.
const DWARFDebugAranges * getDebugAranges ()
Get a pointer to the parsed DebugAranges object.
Expected< const DWARFDebugFrame * > getDebugFrame ()
Get a pointer to the parsed frame information object.
Expected< const DWARFDebugFrame * > getEHFrame ()
Get a pointer to the parsed eh frame information object.
const DWARFDebugMacro * getDebugMacinfo ()
Get a pointer to the parsed DebugMacinfo information object.
const DWARFDebugMacro * getDebugMacinfoDWO ()
Get a pointer to the parsed DebugMacinfoDWO information object.
const DWARFDebugMacro * getDebugMacro ()
Get a pointer to the parsed DebugMacro information object.
const DWARFDebugMacro * getDebugMacroDWO ()
Get a pointer to the parsed DebugMacroDWO information object.
const DWARFDebugNames & getDebugNames ()
Get a reference to the parsed accelerator table object.
const AppleAcceleratorTable & getAppleNames ()
Get a reference to the parsed accelerator table object.
const AppleAcceleratorTable & getAppleTypes ()
Get a reference to the parsed accelerator table object.
const AppleAcceleratorTable & getAppleNamespaces ()
Get a reference to the parsed accelerator table object.
const AppleAcceleratorTable & getAppleObjC ()
Get a reference to the parsed accelerator table object.
const DWARFDebugLine::LineTable * getLineTableForUnit (DWARFUnit *U)
Get a pointer to a parsed line table corresponding to a compile unit.
Expected< const DWARFDebugLine::LineTable * > getLineTableForUnit (DWARFUnit *U, function_ref< void(Error)> RecoverableErrorHandler)
Get a pointer to a parsed line table corresponding to a compile unit.
DataExtractor getStringExtractor () const
DataExtractor getStringDWOExtractor () const
DataExtractor getLineStringExtractor () const
DIEsForAddress getDIEsForAddress (uint64_t Address)
Get the compilation unit, the function DIE and lexical block DIE for the given address where applicable.
DILineInfo getLineInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
DILineInfoTable getLineInfoForAddressRange (object::SectionedAddress Address, uint64_t Size, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
DIInliningInfo getInliningInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier()) override
std::vector< DILocal > getLocalsForAddress (object::SectionedAddress Address) override
bool isLittleEndian () const
std::shared_ptr< DWARFContext > getDWOContext (StringRef AbsolutePath)
const MCRegisterInfo * getRegisterInfo () const
function_ref< void(Error)> getRecoverableErrorHandler ()
function_ref< void(Error)> getWarningHandler ()
Error loadRegisterInfo (const object::ObjectFile &Obj)
Loads register info for the architecture of the provided object file.
uint8_t getCUAddrSize ()
Get address size from CUs.
Triple::ArchType getArch () const
DWARFCompileUnit * getCompileUnitForAddress (uint64_t Address)
Return the compile unit which contains instruction with provided address.
Public Member Functions inherited from llvm::DIContext
DIContext (DIContextKind K)
virtual ~DIContext ()=default
DIContextKind getKind () const
Static Public Member Functions
static bool classof (const DIContext *DICtx)
static unsigned getMaxSupportedVersion ()
static bool isSupportedVersion (unsigned version)
static SmallVector< uint8_t, 3 > getSupportedAddressSizes ()
static bool isAddressSizeSupported (unsigned AddressSize)
template<typename... Ts>
static Error checkAddressSizeSupported (unsigned AddressSize, std::error_code EC, char const *Fmt, const Ts &...Vals)
static std::unique_ptr< DWARFContext > create (const object::ObjectFile &Obj, ProcessDebugRelocations RelocAction=ProcessDebugRelocations::Process, const LoadedObjectInfo *L=nullptr, std::string DWPName="", std::function< void(Error)> RecoverableErrorHandler=WithColor::defaultErrorHandler, std::function< void(Error)> WarningHandler=WithColor::defaultWarningHandler)
static std::unique_ptr< DWARFContext > create (const StringMap< std::unique_ptr< MemoryBuffer > > &Sections, uint8_t AddrSize, bool isLittleEndian=sys::IsLittleEndianHost, std::function< void(Error)> RecoverableErrorHandler=WithColor::defaultErrorHandler, std::function< void(Error)> WarningHandler=WithColor::defaultWarningHandler)
Detailed Description
DWARFContext This data structure is the top level entity that deals with dwarf debug information parsing.
The actual data is supplied through DWARFObj.
Definition at line 53 of file DWARFContext.h.
Member Typedef Documentation
compile_unit_range
using llvm::DWARFContext::compile_unit_range = DWARFUnitVector::compile_unit_range
Definition at line 151 of file DWARFContext.h.
unit_iterator_range
using llvm::DWARFContext::unit_iterator_range = DWARFUnitVector::iterator_range
Definition at line 150 of file DWARFContext.h.
Member Enumeration Documentation
ProcessDebugRelocations
enum class llvm::DWARFContext::ProcessDebugRelocations strong
Enumerator
Process
Ignore
Definition at line 419 of file DWARFContext.h.
Constructor & Destructor Documentation
DWARFContext() [1/2]
DWARFContext::DWARFContext (std::unique_ptr< const DWARFObject > DObj, std::string DWPName = "", std::function< void(Error)> RecoverableErrorHandler = WithColor::defaultErrorHandler, std::function< void(Error)> WarningHandler = WithColor::defaultWarningHandler)
Definition at line 67 of file DWARFContext.cpp.
~DWARFContext()
DWARFContext::~DWARFContext () default
DWARFContext() [2/2]
llvm::DWARFContext::DWARFContext (DWARFContext &) delete
Member Function Documentation
checkAddressSizeSupported()
template<typename... Ts> static Error llvm::DWARFContext::checkAddressSizeSupported (unsigned AddressSize, std::error_code EC, char const * Fmt, const Ts &... Vals) inline static
Definition at line 392 of file DWARFContext.h.
References llvm::format(), getSupportedAddressSizes(), isAddressSizeSupported(), Size, llvm::raw_string_ostream::str(), and llvm::Error::success().
Referenced by llvm::DWARFDebugRangeList::extract(), llvm::DWARFUnitHeader::extract(), llvm::DWARFDebugArangeSet::extract(), and llvm::DWARFListTableHeader::extract().
classof()
static bool llvm::DWARFContext::classof (const DIContext * DICtx) inline static
Definition at line 134 of file DWARFContext.h.
References llvm::DIContext::CK_DWARF, and llvm::DIContext::getKind().
compile_units()
compile_unit_range llvm::DWARFContext::compile_units () inline
Get compile units in this context.
Definition at line 174 of file DWARFContext.h.
References info_section_units(), llvm::isCompileUnit(), and llvm::make_filter_range().
Referenced by llvm::gsym::DwarfTransformer::convert(), dump(), llvm::DWARFDebugAranges::generate(), and getCUAddrSize().
create() [1/2]
std::unique_ptr< DWARFContext > DWARFContext::create (const object::ObjectFile & Obj, ProcessDebugRelocations RelocAction = ProcessDebugRelocations::Process, const LoadedObjectInfo * L = nullptr, std::string DWPName = "", std::function< void(Error)> RecoverableErrorHandler = WithColor::defaultErrorHandler, std::function< void(Error)> WarningHandler = WithColor::defaultWarningHandler) static
Definition at line 1998 of file DWARFContext.cpp.
Referenced by llvm::InstrProfCorrelatorImpl< IntPtrT >::get(), and getDWOContext().
create() [2/2]
std::unique_ptr< DWARFContext > DWARFContext::create (const StringMap< std::unique_ptr< MemoryBuffer > > & Sections, uint8_t AddrSize, bool isLittleEndian = sys::IsLittleEndianHost, std::function< void(Error)> RecoverableErrorHandler = WithColor::defaultErrorHandler, std::function< void(Error)> WarningHandler = WithColor::defaultWarningHandler) static
Definition at line 2011 of file DWARFContext.cpp.
References isLittleEndian().
dump() [1/2]
void llvm::DWARFContext::dump (raw_ostream & OS, DIDumpOptions DumpOpts) inline override virtual
Implements llvm::DIContext.
Definition at line 143 of file DWARFContext.h.
References llvm::DIDT_ID_Count, and dump().
dump() [2/2]
void DWARFContext::dump (raw_ostream & OS, DIDumpOptions DumpOpts, std::array< Optional< uint64_t >, DIDT_ID_Count > DumpOffsets)
Dump a textual representation to OS.
If any DumpOffsets are present, dump only the record at the specified offset.
Definition at line 346 of file DWARFContext.cpp.
References compile_units(), llvm::Data, DF, llvm::DIDT_All, llvm::DIDT_UUID, llvm::DWARFGdbIndex::dump(), llvm::DWARFDebugAbbrev::dump(), llvm::DWARFDebugArangeSet::dump(), llvm::DWARFUnitIndex::dump(), llvm::AppleAcceleratorTable::dump(), llvm::DWARFDebugNames::dump(), llvm::DWARFDebugLoc::dump(), dump(), dumpAddrSection(), dumpLoclistsSection(), dumpPubTableSection(), dumpRnglistsSection(), dumpStringOffsetsSection(), llvm::DIDumpOptions::DumpType, dumpUUID(), dwo_info_section_units(), dwo_types_section_units(), dwo_units(), E, llvm::sys::path::extension(), llvm::DWARFDebugArangeSet::extract(), llvm::format(), getAppleNames(), getAppleNamespaces(), getAppleObjC(), getAppleTypes(), llvm::DataExtractor::getCStr(), getCUAddrSize(), getCUIndex(), getDebugAbbrev(), getDebugAbbrevDWO(), getDebugFrame(), getDebugLoc(), getDebugMacinfo(), getDebugMacinfoDWO(), getDebugMacro(), getDebugMacroDWO(), getDebugNames(), getEHFrame(), getGdbIndex(), getMaxVersion(), getNumCompileUnits(), getNumDWOCompileUnits(), getNumDWOTypeUnits(), getNumTypeUnits(), getRegisterInfo(), getTUIndex(), I, info_section_units(), isLittleEndian(), llvm::DataExtractor::isValidOffset(), Name, llvm::DIDumpOptions::noImplicitRecursion(), llvm::None, normal_units(), Offset, llvm::DIDumpOptions::RecoverableErrorHandler, llvm::Error::success(), types_section_units(), llvm::DIDumpOptions::Verbose, llvm::DIDumpOptions::WarningHandler, and llvm::raw_ostream::write_escaped().
Referenced by dump(), and dump().
dwo_compile_units()
compile_unit_range llvm::DWARFContext::dwo_compile_units () inline
Get compile units in the DWO context.
Definition at line 207 of file DWARFContext.h.
References dwo_info_section_units(), llvm::isCompileUnit(), and llvm::make_filter_range().
Referenced by getDWOCompileUnitForHash().
dwo_info_section_units()
unit_iterator_range llvm::DWARFContext::dwo_info_section_units () inline
Get units from .debug_info..dwo in the DWO context.
Definition at line 188 of file DWARFContext.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::DWARFUnitVector::getNumInfoUnits().
Referenced by dump(), dwo_compile_units(), and getMaxDWOVersion().
dwo_types_section_units()
unit_iterator_range llvm::DWARFContext::dwo_types_section_units () inline
Get units from .debug_types.dwo in the DWO context.
Definition at line 200 of file DWARFContext.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::DWARFUnitVector::getNumInfoUnits().
Referenced by dump().
dwo_units()
unit_iterator_range llvm::DWARFContext::dwo_units () inline
Get all units in the DWO context.
Definition at line 216 of file DWARFContext.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by dump(), and getTypeUnitForHash().
getAppleNames()
const AppleAcceleratorTable & DWARFContext::getAppleNames ()
Get a reference to the parsed accelerator table object.
Definition at line 935 of file DWARFContext.cpp.
References getAccelTable(), and isLittleEndian().
Referenced by dump().
getAppleNamespaces()
const AppleAcceleratorTable & DWARFContext::getAppleNamespaces ()
Get a reference to the parsed accelerator table object.
Definition at line 945 of file DWARFContext.cpp.
References getAccelTable(), and isLittleEndian().
Referenced by dump().
getAppleObjC()
const AppleAcceleratorTable & DWARFContext::getAppleObjC ()
Get a reference to the parsed accelerator table object.
Definition at line 951 of file DWARFContext.cpp.
References getAccelTable(), and isLittleEndian().
Referenced by dump().
getAppleTypes()
const AppleAcceleratorTable & DWARFContext::getAppleTypes ()
Get a reference to the parsed accelerator table object.
Definition at line 940 of file DWARFContext.cpp.
References getAccelTable(), and isLittleEndian().
Referenced by dump().
getArch()
Triple::ArchType llvm::DWARFContext::getArch () const inline
Definition at line 447 of file DWARFContext.h.
References getDWARFObj(), and llvm::DWARFObject::getFile().
Referenced by getDebugFrame(), and getEHFrame().
getCompileUnitForAddress()
DWARFCompileUnit * DWARFContext::getCompileUnitForAddress (uint64_t Address)
Return the compile unit which contains instruction with provided address.
TODO: change input parameter from "uint64_t Address" into "SectionedAddress Address"
Definition at line 1026 of file DWARFContext.cpp.
References llvm::DWARFDebugAranges::findAddress(), getCompileUnitForOffset(), and getDebugAranges().
Referenced by getDIEsForAddress(), getInliningInfoForAddress(), getLineInfoForAddress(), getLineInfoForAddressRange(), and getLocalsForAddress().
getCompileUnitForOffset()
DWARFCompileUnit * DWARFContext::getCompileUnitForOffset (uint64_t Offset)
Return the compile unit that includes an offset (relative to .debug_info).
Definition at line 1020 of file DWARFContext.cpp.
References llvm::DWARFUnitVector::getUnitForOffset(), and Offset.
Referenced by getCompileUnitForAddress().
getCUAddrSize()
uint8_t DWARFContext::getCUAddrSize ()
Get address size from CUs.
TODO: refactor compile_units() to make this const.
Definition at line 2038 of file DWARFContext.cpp.
References compile_units().
Referenced by dump().
getCUIndex()
const DWARFUnitIndex & DWARFContext::getCUIndex ()
Definition at line 774 of file DWARFContext.cpp.
References isLittleEndian().
Referenced by dump(), and getDWOCompileUnitForHash().
getDebugAbbrev()
const DWARFDebugAbbrev * DWARFContext::getDebugAbbrev ()
Get a pointer to the parsed DebugAbbrev object.
Definition at line 806 of file DWARFContext.cpp.
References isLittleEndian().
Referenced by dump(), and llvm::DWARFVerifier::handleDebugAbbrev().
getDebugAbbrevDWO()
const DWARFDebugAbbrev * DWARFContext::getDebugAbbrevDWO ()
Get a pointer to the parsed dwo abbreviations object.
Definition at line 817 of file DWARFContext.cpp.
References isLittleEndian().
Referenced by dump(), and llvm::DWARFVerifier::handleDebugAbbrev().
getDebugAranges()
const DWARFDebugAranges * DWARFContext::getDebugAranges ()
Get a pointer to the parsed DebugAranges object.
Definition at line 841 of file DWARFContext.cpp.
Referenced by getCompileUnitForAddress().
getDebugFrame()
Expected< const DWARFDebugFrame * > DWARFContext::getDebugFrame ()
Get a pointer to the parsed frame information object.
Definition at line 850 of file DWARFContext.cpp.
References DF, E, getArch(), and isLittleEndian().
Referenced by dump().
getDebugLoc()
const DWARFDebugLoc * DWARFContext::getDebugLoc ()
Get a pointer to the parsed DebugLoc object.
Definition at line 827 of file DWARFContext.cpp.
References getNumCompileUnits(), getUnitAtIndex(), and isLittleEndian().
Referenced by dump().
getDebugMacinfo()
const DWARFDebugMacro * DWARFContext::getDebugMacinfo ()
Get a pointer to the parsed DebugMacinfo information object.
Definition at line 904 of file DWARFContext.cpp.
Referenced by dump().
getDebugMacinfoDWO()
const DWARFDebugMacro * DWARFContext::getDebugMacinfoDWO ()
Get a pointer to the parsed DebugMacinfoDWO information object.
Definition at line 910 of file DWARFContext.cpp.
Referenced by dump().
getDebugMacro()
const DWARFDebugMacro * DWARFContext::getDebugMacro ()
Get a pointer to the parsed DebugMacro information object.
Definition at line 892 of file DWARFContext.cpp.
Referenced by dump().
getDebugMacroDWO()
const DWARFDebugMacro * DWARFContext::getDebugMacroDWO ()
Get a pointer to the parsed DebugMacroDWO information object.
Definition at line 898 of file DWARFContext.cpp.
Referenced by dump().
getDebugNames()
const DWARFDebugNames & DWARFContext::getDebugNames ()
Get a reference to the parsed accelerator table object.
Definition at line 930 of file DWARFContext.cpp.
References getAccelTable(), and isLittleEndian().
Referenced by dump().
getDIEForOffset()
DWARFDie DWARFContext::getDIEForOffset (uint64_t Offset)
Get a DIE given an exact offset.
Definition at line 754 of file DWARFContext.cpp.
References llvm::DWARFUnitVector::getUnitForOffset(), and Offset.
getDIEsForAddress()
DWARFContext::DIEsForAddress DWARFContext::getDIEsForAddress (uint64_t Address)
Get the compilation unit, the function DIE and lexical block DIE for the given address where applicable.
TODO: change input parameter from "uint64_t Address" into "SectionedAddress Address"
Definition at line 1033 of file DWARFContext.cpp.
References llvm::append_range(), getCompileUnitForAddress(), and llvm::DIE::getTag().
getDWARFObj()
const DWARFObject & llvm::DWARFContext::getDWARFObj () const inline
Definition at line 132 of file DWARFContext.h.
Referenced by dumpAttribute(), llvm::DWARFVerifier::DWARFVerifier(), llvm::DWARFDebugAranges::generate(), getArch(), llvm::DWARFVerifier::handleAccelTables(), llvm::DWARFVerifier::handleDebugAbbrev(), and llvm::DWARFVerifier::handleDebugInfo().
getDWOCompileUnitForHash()
DWARFCompileUnit * DWARFContext::getDWOCompileUnitForHash (uint64_t Hash)
Definition at line 724 of file DWARFContext.cpp.
References dwo_compile_units(), getCUIndex(), llvm::DWARFUnitVector::getUnitForIndexEntry(), and llvm::dwarf::toUnsigned().
getDWOContext()
std::shared_ptr< DWARFContext > DWARFContext::getDWOContext (StringRef AbsolutePath)
Definition at line 1401 of file DWARFContext.cpp.
References llvm::consumeError(), create(), llvm::object::ObjectFile::createObjectFile(), and Ignore.
getDWOUnitAtIndex()
DWARFUnit * llvm::DWARFContext::getDWOUnitAtIndex (unsigned index) inline
Get the unit at the specified index for the DWO units.
Definition at line 252 of file DWARFContext.h.
getDWOUnitsVector()
const DWARFUnitVector & llvm::DWARFContext::getDWOUnitsVector () inline
Definition at line 194 of file DWARFContext.h.
Referenced by llvm::DWARFVerifier::handleDebugInfo().
getEHFrame()
Expected< const DWARFDebugFrame * > DWARFContext::getEHFrame ()
Get a pointer to the parsed eh frame information object.
Definition at line 876 of file DWARFContext.cpp.
References DF, E, getArch(), and isLittleEndian().
Referenced by dump().
getGdbIndex()
DWARFGdbIndex & DWARFContext::getGdbIndex ()
Definition at line 796 of file DWARFContext.cpp.
Referenced by dump().
getInliningInfoForAddress()
DIInliningInfo DWARFContext::getInliningInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) override virtual
Implements llvm::DIContext.
Definition at line 1332 of file DWARFContext.cpp.
References llvm::DILineInfo::Column, llvm::DILineInfo::Discriminator, llvm::DILineInfo::FileName, llvm::DWARFDie::find(), llvm::DILineInfoSpecifier::FLIKind, llvm::DILineInfoSpecifier::FNKind, llvm::DILineInfo::FunctionName, llvm::DWARFDie::getCallerFrame(), getCompileUnitForAddress(), llvm::DWARFDie::getDeclFile(), llvm::DWARFDie::getDeclLine(), llvm::DWARFDebugLine::LineTable::getFileLineInfoForAddress(), llvm::DWARFDebugLine::LineTable::getFileNameByIndex(), getLineTableForUnit(), llvm::DWARFDie::getSubroutineName(), llvm::DILineInfo::Line, Name, llvm::DILineInfo::StartAddress, llvm::DILineInfo::StartFileName, llvm::DILineInfo::StartLine, and llvm::dwarf::toSectionedAddress().
Referenced by llvm::gsym::DwarfTransformer::verify().
getLineInfoForAddress()
DILineInfo DWARFContext::getLineInfoForAddress (object::SectionedAddress Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) override virtual
Implements llvm::DIContext.
Definition at line 1256 of file DWARFContext.cpp.
References llvm::DILineInfoSpecifier::FLIKind, llvm::DILineInfoSpecifier::FNKind, getCompileUnitForAddress(), getFunctionNameAndStartLineForAddress(), and getLineTableForUnit().
Referenced by llvm::gsym::DwarfTransformer::verify().
getLineInfoForAddressRange()
DILineInfoTable DWARFContext::getLineInfoForAddressRange (object::SectionedAddress Address, uint64_t Size, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) override virtual
Implements llvm::DIContext.
Definition at line 1277 of file DWARFContext.cpp.
References llvm::DILineInfo::BadString, llvm::DILineInfoSpecifier::FLIKind, llvm::DILineInfoSpecifier::FNKind, getCompileUnitForAddress(), llvm::DWARFDebugLine::LineTable::getFileNameByIndex(), getFunctionNameAndStartLineForAddress(), getLineTableForUnit(), llvm::DWARFDebugLine::LineTable::lookupAddressRange(), llvm::DWARFDebugLine::LineTable::Rows, and Size.
getLineStringExtractor()
DataExtractor llvm::DWARFContext::getLineStringExtractor () const inline
Definition at line 348 of file DWARFContext.h.
Referenced by llvm::DWARFFormValue::getAsCString().
getLineTableForUnit() [1/2]
const DWARFDebugLine::LineTable * DWARFContext::getLineTableForUnit (DWARFUnit * U)
Get a pointer to a parsed line table corresponding to a compile unit.
Report any parsing issues as warnings on stderr.
Definition at line 957 of file DWARFContext.cpp.
References getLineTableForUnit().
Referenced by llvm::gsym::CUInfo::CUInfo(), getInliningInfoForAddress(), getLineInfoForAddress(), getLineInfoForAddressRange(), and getLineTableForUnit().
getLineTableForUnit() [2/2]
Expected< const DWARFDebugLine::LineTable * > DWARFContext::getLineTableForUnit (DWARFUnit * U, function_ref< void(Error)> RecoverableErrorHandler)
Get a pointer to a parsed line table corresponding to a compile unit.
Report any recoverable parsing problems using the handler.
Definition at line 967 of file DWARFContext.cpp.
References isLittleEndian(), Offset, and llvm::dwarf::toSectionOffset().
getLocalsForAddress()
std::vector< DILocal > DWARFContext::getLocalsForAddress (object::SectionedAddress Address) override virtual
Implements llvm::DIContext.
Definition at line 1244 of file DWARFContext.cpp.
References getCompileUnitForAddress().
getMaxDWOVersion()
unsigned llvm::DWARFContext::getMaxDWOVersion () inline
Definition at line 272 of file DWARFContext.h.
References dwo_info_section_units().
getMaxSupportedVersion()
static unsigned llvm::DWARFContext::getMaxSupportedVersion () inline static
Definition at line 380 of file DWARFContext.h.
Referenced by llvm::DWARFUnitHeader::extract(), and isSupportedVersion().
getMaxVersion()
unsigned llvm::DWARFContext::getMaxVersion () inline
Definition at line 266 of file DWARFContext.h.
References info_section_units().
Referenced by dump().
getNormalUnitsVector()
const DWARFUnitVector & llvm::DWARFContext::getNormalUnitsVector () inline
Definition at line 161 of file DWARFContext.h.
Referenced by llvm::DWARFVerifier::handleDebugInfo().
getNumCompileUnits()
unsigned llvm::DWARFContext::getNumCompileUnits () inline
Get the number of compile units in this context.
Definition at line 222 of file DWARFContext.h.
References llvm::DWARFUnitVector::getNumInfoUnits().
Referenced by dump(), and getDebugLoc().
getNumDWOCompileUnits()
unsigned llvm::DWARFContext::getNumDWOCompileUnits () inline
Get the number of compile units in the DWO context.
Definition at line 234 of file DWARFContext.h.
References llvm::DWARFUnitVector::getNumInfoUnits().
Referenced by dump().
getNumDWOTypeUnits()
unsigned llvm::DWARFContext::getNumDWOTypeUnits () inline
Get the number of type units in the DWO context.
Definition at line 240 of file DWARFContext.h.
References llvm::DWARFUnitVector::getNumTypesUnits().
Referenced by dump().
getNumTypeUnits()
unsigned llvm::DWARFContext::getNumTypeUnits () inline
Get the number of type units in this context.
Definition at line 228 of file DWARFContext.h.
References llvm::DWARFUnitVector::getNumTypesUnits().
Referenced by dump().
getRecoverableErrorHandler()
function_ref< void(Error)> llvm::DWARFContext::getRecoverableErrorHandler () inline
Definition at line 413 of file DWARFContext.h.
Referenced by llvm::DWARFDebugAranges::generate().
getRegisterInfo()
const MCRegisterInfo * llvm::DWARFContext::getRegisterInfo () const inline
Definition at line 411 of file DWARFContext.h.
Referenced by dump().
getStringDWOExtractor()
DataExtractor llvm::DWARFContext::getStringDWOExtractor () const inline
Definition at line 345 of file DWARFContext.h.
getStringExtractor()
DataExtractor llvm::DWARFContext::getStringExtractor () const inline
Definition at line 342 of file DWARFContext.h.
Referenced by llvm::DWARFFormValue::getAsCString().
getSupportedAddressSizes()
static SmallVector< uint8_t, 3 > llvm::DWARFContext::getSupportedAddressSizes () inline static
Definition at line 385 of file DWARFContext.h.
Referenced by checkAddressSizeSupported(), and isAddressSizeSupported().
getTUIndex()
const DWARFUnitIndex & DWARFContext::getTUIndex ()
Definition at line 785 of file DWARFContext.cpp.
References llvm::DW_SECT_EXT_TYPES, and isLittleEndian().
Referenced by dump(), and getTypeUnitForHash().
getTypeUnitForHash()
DWARFTypeUnit * DWARFContext::getTypeUnitForHash (uint16_t Version, uint64_t Hash, bool IsDWO)
Definition at line 696 of file DWARFContext.cpp.
References dwo_units(), getTUIndex(), llvm::DWARFUnitVector::getUnitForIndexEntry(), and normal_units().
getUnitAtIndex()
DWARFUnit * llvm::DWARFContext::getUnitAtIndex (unsigned index) inline
Get the unit at the specified index.
Definition at line 246 of file DWARFContext.h.
Referenced by getDebugLoc().
getWarningHandler()
function_ref< void(Error)> llvm::DWARFContext::getWarningHandler () inline
Definition at line 417 of file DWARFContext.h.
info_section_units()
unit_iterator_range llvm::DWARFContext::info_section_units () inline
Get units from .debug_info in this context.
Definition at line 154 of file DWARFContext.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::DWARFUnitVector::getNumInfoUnits().
Referenced by compile_units(), dump(), and getMaxVersion().
isAddressSizeSupported()
static bool llvm::DWARFContext::isAddressSizeSupported (unsigned AddressSize) inline static
Definition at line 388 of file DWARFContext.h.
References getSupportedAddressSizes(), and llvm::is_contained().
Referenced by checkAddressSizeSupported(), and llvm::DWARFDebugRangeList::RangeListEntry::isBaseAddressSelectionEntry().
isLittleEndian()
bool llvm::DWARFContext::isLittleEndian () const inline
Definition at line 379 of file DWARFContext.h.
Referenced by create(), dump(), llvm::DWARFDebugAranges::generate(), getAppleNames(), getAppleNamespaces(), getAppleObjC(), getAppleTypes(), getCUIndex(), getDebugAbbrev(), getDebugAbbrevDWO(), getDebugFrame(), getDebugLoc(), getDebugNames(), getEHFrame(), getLineTableForUnit(), getTUIndex(), llvm::DWARFVerifier::handleAccelTables(), and isVariableIndexable().
isSupportedVersion()
static bool llvm::DWARFContext::isSupportedVersion (unsigned version) inline static
Definition at line 381 of file DWARFContext.h.
References getMaxSupportedVersion().
Referenced by llvm::DWARFUnitHeader::extract().
loadRegisterInfo()
Error DWARFContext::loadRegisterInfo (const object::ObjectFile & Obj)
Loads register info for the architecture of the provided object file.
Improves readability of dumped DWARF expressions. Requires the caller to have initialized the relevant target descriptions.
Definition at line 2021 of file DWARFContext.cpp.
References llvm::Target::createMCRegInfo(), llvm::createStringError(), llvm::object::ObjectFile::getArch(), llvm::invalid_argument, llvm::TargetRegistry::lookupTarget(), llvm::Error::success(), llvm::Triple::UnknownOS, and llvm::Triple::UnknownVendor.
normal_units()
unit_iterator_range llvm::DWARFContext::normal_units () inline
Get all normal compile/type units in this context.
Definition at line 182 of file DWARFContext.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by dump(), and getTypeUnitForHash().
operator=()
DWARFContext & llvm::DWARFContext::operator= (DWARFContext &) delete
setMaxVersionIfGreater()
void llvm::DWARFContext::setMaxVersionIfGreater (unsigned Version) inline
Definition at line 278 of file DWARFContext.h.
References Version.
types_section_units()
unit_iterator_range llvm::DWARFContext::types_section_units () inline
Get units from .debug_types in this context.
Definition at line 167 of file DWARFContext.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::DWARFUnitVector::getNumInfoUnits().
Referenced by dump().
verify()
bool DWARFContext::verify (raw_ostream & OS, DIDumpOptions DumpOpts = {}) override virtual
Reimplemented from llvm::DIContext.
Definition at line 761 of file DWARFContext.cpp.
References llvm::DIDumpOptions::DumpType, and Success.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFContext.h
lib/DebugInfo/DWARF/DWARFContext.cpp