LLVM: llvm::SDNodeIterator Class Reference
llvm::SDNodeIterator Class Reference
#include "llvm/CodeGen/SelectionDAGNodes.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = SDNode
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
bool operator== (const SDNodeIterator &x) const
bool operator!= (const SDNodeIterator &x) const
pointer operator* () const
pointer operator-> () const
SDNodeIterator & operator++ ()
SDNodeIterator operator++ (int)
size_t operator- (SDNodeIterator Other) const
unsigned getOperand () const
const SDNode * getNode () const
Static Public Member Functions
static SDNodeIterator begin (const SDNode *N)
static SDNodeIterator end (const SDNode *N)
Detailed Description
Definition at line 2836 of file SelectionDAGNodes.h.
Member Typedef Documentation
difference_type
using llvm::SDNodeIterator::difference_type = std::ptrdiff_t
Definition at line 2845 of file SelectionDAGNodes.h.
iterator_category
using llvm::SDNodeIterator::iterator_category = std::forward_iterator_tag
Definition at line 2843 of file SelectionDAGNodes.h.
pointer
using llvm::SDNodeIterator::pointer = value_type *
Definition at line 2846 of file SelectionDAGNodes.h.
reference
using llvm::SDNodeIterator::reference = value_type &
Definition at line 2847 of file SelectionDAGNodes.h.
value_type
using llvm::SDNodeIterator::value_type = SDNode
Definition at line 2844 of file SelectionDAGNodes.h.
Member Function Documentation
begin()
static SDNodeIterator llvm::SDNodeIterator::begin (const SDNode * N) inline static
Definition at line 2872 of file SelectionDAGNodes.h.
References N.
Referenced by llvm::GraphTraits< SDNode * >::child_begin(), llvm::DOTGraphTraits< SelectionDAG * >::getEdgeSourceLabel(), llvm::DOTGraphTraits< SelectionDAG * >::getEdgeTarget(), and llvm::TargetLowering::SimplifyDemandedBits().
end()
static SDNodeIterator llvm::SDNodeIterator::end (const SDNode * N) inline static
Definition at line 2873 of file SelectionDAGNodes.h.
References N.
Referenced by llvm::GraphTraits< SDNode * >::child_end(), and llvm::TargetLowering::SimplifyDemandedBits().
getNode()
const SDNode * llvm::SDNodeIterator::getNode () const inline
Definition at line 2878 of file SelectionDAGNodes.h.
getOperand()
unsigned llvm::SDNodeIterator::getOperand () const inline
Definition at line 2877 of file SelectionDAGNodes.h.
operator!=()
bool llvm::SDNodeIterator::operator!= (const SDNodeIterator & x) const inline
Definition at line 2852 of file SelectionDAGNodes.h.
References operator==().
operator*()
pointer llvm::SDNodeIterator::operator* () const inline
Definition at line 2854 of file SelectionDAGNodes.h.
Referenced by operator->().
operator++() [1/2]
SDNodeIterator & llvm::SDNodeIterator::operator++ () inline
Definition at line 2859 of file SelectionDAGNodes.h.
operator++() [2/2]
SDNodeIterator llvm::SDNodeIterator::operator++ (int) inline
Definition at line 2863 of file SelectionDAGNodes.h.
operator-()
size_t llvm::SDNodeIterator::operator- (SDNodeIterator Other) const inline
Definition at line 2866 of file SelectionDAGNodes.h.
References assert(), Node::Node(), and llvm::Other.
operator->()
pointer llvm::SDNodeIterator::operator-> () const inline
Definition at line 2857 of file SelectionDAGNodes.h.
References operator*().
operator==()
bool llvm::SDNodeIterator::operator== (const SDNodeIterator & x) const inline
Definition at line 2849 of file SelectionDAGNodes.h.
Referenced by operator!=().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/SelectionDAGNodes.h