LLVM: llvm::Directive Class Reference
llvm::Directive Class Reference
#include "llvm/TableGen/DirectiveEmitter.h"
Public Member Functions
Directive (const llvm::Record *Def)
std::vector< Record * > getAllowedClauses () const
std::vector< Record * > getAllowedOnceClauses () const
std::vector< Record * > getAllowedExclusiveClauses () const
std::vector< Record * > getRequiredClauses () const
Public Member Functions inherited from llvm::BaseRecord
BaseRecord (const llvm::Record *Def)
StringRef getName () const
StringRef getAlternativeName () const
std::string getFormattedName ()
bool isDefault () const
StringRef getRecordName () const
Additional Inherited Members
Protected Attributes inherited from llvm::BaseRecord
const llvm::Record * Def
Detailed Description
Definition at line 100 of file DirectiveEmitter.h.
Constructor & Destructor Documentation
Directive()
llvm::Directive::Directive (const llvm::Record * Def) inline explicit
Definition at line 102 of file DirectiveEmitter.h.
Member Function Documentation
getAllowedClauses()
std::vector< Record * > llvm::Directive::getAllowedClauses () const inline
Definition at line 104 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def, and llvm::Record::getValueAsListOfDefs().
getAllowedExclusiveClauses()
std::vector< Record * > llvm::Directive::getAllowedExclusiveClauses () const inline
Definition at line 112 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def, and llvm::Record::getValueAsListOfDefs().
getAllowedOnceClauses()
std::vector< Record * > llvm::Directive::getAllowedOnceClauses () const inline
Definition at line 108 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def, and llvm::Record::getValueAsListOfDefs().
getRequiredClauses()
std::vector< Record * > llvm::Directive::getRequiredClauses () const inline
Definition at line 116 of file DirectiveEmitter.h.
References llvm::BaseRecord::Def, and llvm::Record::getValueAsListOfDefs().
The documentation for this class was generated from the following file:
include/llvm/TableGen/DirectiveEmitter.h