LLVM: llvm::NVPTXSubtarget Class Reference
llvm::NVPTXSubtarget Class Reference
#include "Target/NVPTX/NVPTXSubtarget.h"
Public Member Functions
NVPTXSubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const NVPTXTargetMachine &TM)
This constructor initializes the data members to match that of the specified module.
const TargetFrameLowering * getFrameLowering () const override
const NVPTXInstrInfo * getInstrInfo () const override
const NVPTXRegisterInfo * getRegisterInfo () const override
const NVPTXTargetLowering * getTargetLowering () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
bool hasAtomAddF64 () const
bool hasAtomScope () const
bool hasAtomBitwise64 () const
bool hasAtomMinMax64 () const
bool hasLDG () const
bool hasHWROT32 () const
bool hasImageHandles () const
bool hasFP16Math () const
bool allowFP16Math () const
unsigned int getSmVersion () const
std::string getTargetName () const
unsigned getPTXVersion () const
NVPTXSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
Detailed Description
Definition at line 31 of file NVPTXSubtarget.h.
Constructor & Destructor Documentation
NVPTXSubtarget()
NVPTXSubtarget::NVPTXSubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const NVPTXTargetMachine & TM)
This constructor initializes the data members to match that of the specified module.
Definition at line 48 of file NVPTXSubtarget.cpp.
Member Function Documentation
allowFP16Math()
bool NVPTXSubtarget::allowFP16Math () const
Definition at line 65 of file NVPTXSubtarget.cpp.
References hasFP16Math(), and NoF16Math.
Referenced by llvm::NVPTXTargetLowering::NVPTXTargetLowering().
getFrameLowering()
const TargetFrameLowering * llvm::NVPTXSubtarget::getFrameLowering () const inline override
Definition at line 57 of file NVPTXSubtarget.h.
getInstrInfo()
const NVPTXInstrInfo * llvm::NVPTXSubtarget::getInstrInfo () const inline override
Definition at line 60 of file NVPTXSubtarget.h.
getPTXVersion()
unsigned llvm::NVPTXSubtarget::getPTXVersion () const inline
Definition at line 83 of file NVPTXSubtarget.h.
Referenced by llvm::NVPTXTargetLowering::NVPTXTargetLowering().
getRegisterInfo()
const NVPTXRegisterInfo * llvm::NVPTXSubtarget::getRegisterInfo () const inline override
Definition at line 61 of file NVPTXSubtarget.h.
Referenced by llvm::NVPTXTargetLowering::NVPTXTargetLowering().
getSelectionDAGInfo()
const SelectionDAGTargetInfo * llvm::NVPTXSubtarget::getSelectionDAGInfo () const inline override
Definition at line 67 of file NVPTXSubtarget.h.
getSmVersion()
unsigned int llvm::NVPTXSubtarget::getSmVersion () const inline
Definition at line 80 of file NVPTXSubtarget.h.
References SmVersion.
Referenced by llvm::NVPTXTargetMachine::adjustPassManager(), llvm::NVPTXTargetLowering::getPrototype(), llvm::NVPTXTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::NVPTXTargetLowering(), and llvm::NVPTXTargetMachine::registerPassBuilderCallbacks().
getTargetLowering()
const NVPTXTargetLowering * llvm::NVPTXSubtarget::getTargetLowering () const inline override
Definition at line 64 of file NVPTXSubtarget.h.
Referenced by llvm::NVPTXTargetLowering::LowerFormalArguments().
getTargetName()
std::string llvm::NVPTXSubtarget::getTargetName () const inline
Definition at line 81 of file NVPTXSubtarget.h.
hasAtomAddF64()
bool llvm::NVPTXSubtarget::hasAtomAddF64 () const inline
Definition at line 71 of file NVPTXSubtarget.h.
References SmVersion.
hasAtomBitwise64()
bool llvm::NVPTXSubtarget::hasAtomBitwise64 () const inline
Definition at line 73 of file NVPTXSubtarget.h.
References SmVersion.
hasAtomMinMax64()
bool llvm::NVPTXSubtarget::hasAtomMinMax64 () const inline
Definition at line 74 of file NVPTXSubtarget.h.
References SmVersion.
hasAtomScope()
bool llvm::NVPTXSubtarget::hasAtomScope () const inline
Definition at line 72 of file NVPTXSubtarget.h.
References SmVersion.
hasFP16Math()
bool llvm::NVPTXSubtarget::hasFP16Math () const inline
Definition at line 78 of file NVPTXSubtarget.h.
References SmVersion.
Referenced by allowFP16Math().
hasHWROT32()
bool llvm::NVPTXSubtarget::hasHWROT32 () const inline
Definition at line 76 of file NVPTXSubtarget.h.
References SmVersion.
hasImageHandles()
bool NVPTXSubtarget::hasImageHandles () const
Definition at line 55 of file NVPTXSubtarget.cpp.
References llvm::NVPTX::CUDA, and llvm::NVPTXTargetMachine::getDrvInterface().
hasLDG()
bool llvm::NVPTXSubtarget::hasLDG () const inline
Definition at line 75 of file NVPTXSubtarget.h.
References SmVersion.
Referenced by canLowerToLDG().
initializeSubtargetDependencies()
NVPTXSubtarget & NVPTXSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
Definition at line 33 of file NVPTXSubtarget.cpp.
References ParseSubtargetFeatures().
ParseSubtargetFeatures()
void llvm::NVPTXSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
Referenced by initializeSubtargetDependencies().
The documentation for this class was generated from the following files:
lib/Target/NVPTX/NVPTXSubtarget.h
lib/Target/NVPTX/NVPTXSubtarget.cpp