LLVM: llvm::msgpack::ArrayDocNode Class Reference
llvm::msgpack::ArrayDocNode Class Reference
A DocNode that is an array.
#include "llvm/BinaryFormat/MsgPackDocument.h"
Public Member Functions
ArrayDocNode ()=default
ArrayDocNode (DocNode &N)
size_t size () const
bool empty () const
DocNode & back () const
ArrayTy::iterator begin ()
ArrayTy::iterator end ()
void push_back (DocNode N)
DocNode & operator[] (size_t Index)
Element access. This extends the array if necessary, with empty nodes.
Public Member Functions inherited from llvm::msgpack::DocNode
DocNode ()
bool isMap () const
bool isArray () const
bool isScalar () const
bool isString () const
bool isEmpty () const
Type getKind () const
Document * getDocument () const
int64_t & getInt ()
uint64_t & getUInt ()
bool & getBool ()
double & getFloat ()
int64_t getInt () const
uint64_t getUInt () const
bool getBool () const
double getFloat () const
StringRef getString () const
ArrayDocNode & getArray (bool Convert=false)
Get an ArrayDocNode for an array node.
MapDocNode & getMap (bool Convert=false)
Get a MapDocNode for a map node.
std::string toString () const
Convert this node to a string, assuming it is scalar.
StringRef fromString (StringRef S, StringRef Tag="")
Convert the StringRef and use it to set this DocNode (assuming scalar).
DocNode & operator= (const char *Val)
Convenience assignment operators.
DocNode & operator= (StringRef Val)
DocNode & operator= (bool Val)
DocNode & operator= (int Val)
DocNode & operator= (unsigned Val)
DocNode & operator= (int64_t Val)
DocNode & operator= (uint64_t Val)
Additional Inherited Members
Public Types inherited from llvm::msgpack::DocNode
typedef std::map< DocNode, DocNode > MapTy
typedef std::vector< DocNode > ArrayTy
Protected Attributes inherited from llvm::msgpack::DocNode
union {
int64_t Int
uint64_t UInt
bool Bool
double Float
StringRef Raw
ArrayTy * Array
MapTy * Map
};
Detailed Description
A DocNode that is an array.
Definition at line 249 of file MsgPackDocument.h.
Constructor & Destructor Documentation
ArrayDocNode() [1/2]
llvm::msgpack::ArrayDocNode::ArrayDocNode () default
ArrayDocNode() [2/2]
llvm::msgpack::ArrayDocNode::ArrayDocNode (DocNode & N) inline
Definition at line 252 of file MsgPackDocument.h.
References llvm::msgpack::Array, assert(), and llvm::msgpack::DocNode::getKind().
Member Function Documentation
back()
DocNode & llvm::msgpack::ArrayDocNode::back () const inline
Definition at line 257 of file MsgPackDocument.h.
References llvm::msgpack::DocNode::Array.
begin()
ArrayTy::iterator llvm::msgpack::ArrayDocNode::begin () inline
Definition at line 258 of file MsgPackDocument.h.
References llvm::msgpack::DocNode::Array.
empty()
bool llvm::msgpack::ArrayDocNode::empty () const inline
Definition at line 256 of file MsgPackDocument.h.
References size().
end()
ArrayTy::iterator llvm::msgpack::ArrayDocNode::end () inline
Definition at line 259 of file MsgPackDocument.h.
References llvm::msgpack::DocNode::Array.
operator[]()
DocNode & ArrayDocNode::operator[] (size_t Index)
Element access. This extends the array if necessary, with empty nodes.
Array element access. This extends the array if necessary.
Definition at line 66 of file MsgPackDocument.cpp.
References llvm::msgpack::DocNode::Array, llvm::msgpack::DocNode::getDocument(), Index, and size().
push_back()
void llvm::msgpack::ArrayDocNode::push_back (DocNode N) inline
Definition at line 260 of file MsgPackDocument.h.
References llvm::msgpack::DocNode::Array, assert(), llvm::msgpack::DocNode::getDocument(), and N.
size()
size_t llvm::msgpack::ArrayDocNode::size () const inline
Definition at line 255 of file MsgPackDocument.h.
References llvm::msgpack::DocNode::Array.
Referenced by empty(), and operator[]().
The documentation for this class was generated from the following files:
include/llvm/BinaryFormat/MsgPackDocument.h
lib/BinaryFormat/MsgPackDocument.cpp