LLVM: llvm::StackMapParser< Endianness > Class Template Reference
llvm::StackMapParser< Endianness > Class Template Reference
A parser for the latest stackmap format. At the moment, latest=V3.
#include "llvm/Object/StackMapParser.h"
Classes
class AccessorIterator
class ConstantAccessor
Accessor for constants.
class FunctionAccessor
Accessor for function records.
class LiveOutAccessor
Accessor for stackmap live-out fields.
class LocationAccessor
Accessor for location records.
class RecordAccessor
Accessor for stackmap records.
Public Types
enum class LocationKind : uint8_t {
Register = 1 , Direct = 2 , Indirect = 3 , Constant = 4 ,
ConstantIndex = 5
}
using function_iterator = AccessorIterator<FunctionAccessor>
using constant_iterator = AccessorIterator<ConstantAccessor>
using record_iterator = AccessorIterator<RecordAccessor>
Public Member Functions
StackMapParser (ArrayRef< uint8_t > StackMapSection)
Construct a parser for a version-3 stackmap.
unsigned getVersion () const
Get the version number of this stackmap. (Always returns 3).
uint32_t getNumFunctions () const
Get the number of functions in the stack map.
uint32_t getNumConstants () const
Get the number of large constants in the stack map.
uint32_t getNumRecords () const
Get the number of stackmap records in the stackmap.
FunctionAccessor getFunction (unsigned FunctionIndex) const
Return an FunctionAccessor for the given function index.
function_iterator functions_begin () const
Begin iterator for functions.
function_iterator functions_end () const
End iterator for functions.
iterator_range< function_iterator > functions () const
Iterator range for functions.
ConstantAccessor getConstant (unsigned ConstantIndex) const
Return the large constant at the given index.
constant_iterator constants_begin () const
Begin iterator for constants.
constant_iterator constants_end () const
End iterator for constants.
iterator_range< constant_iterator > constants () const
Iterator range for constants.
RecordAccessor getRecord (unsigned RecordIndex) const
Return a RecordAccessor for the given record index.
record_iterator records_begin () const
Begin iterator for records.
record_iterator records_end () const
End iterator for records.
iterator_range< record_iterator > records () const
Iterator range for records.
Static Public Member Functions
static Error validateHeader (ArrayRef< uint8_t > StackMapSection)
Validates the header of the specified stack map section.
Detailed Description
template<support::endianness Endianness>
class llvm::StackMapParser< Endianness >
A parser for the latest stackmap format. At the moment, latest=V3.
Definition at line 25 of file StackMapParser.h.
Member Typedef Documentation
constant_iterator
template<support::endianness Endianness> using llvm::StackMapParser< Endianness >::constant_iterator = AccessorIterator<ConstantAccessor>
Definition at line 342 of file StackMapParser.h.
function_iterator
template<support::endianness Endianness> using llvm::StackMapParser< Endianness >::function_iterator = AccessorIterator<FunctionAccessor>
Definition at line 341 of file StackMapParser.h.
record_iterator
template<support::endianness Endianness> using llvm::StackMapParser< Endianness >::record_iterator = AccessorIterator<RecordAccessor>
Definition at line 343 of file StackMapParser.h.
Member Enumeration Documentation
LocationKind
template<support::endianness Endianness> enum class llvm::StackMapParser::LocationKind : uint8_t strong
Enumerator
Register
Direct
Indirect
Constant
ConstantIndex
Definition at line 106 of file StackMapParser.h.
Constructor & Destructor Documentation
StackMapParser()
template<support::endianness Endianness> llvm::StackMapParser< Endianness >::StackMapParser (ArrayRef< uint8_t > StackMapSection) inline
Construct a parser for a version-3 stackmap.
StackMap data will be read from the given array.
Definition at line 307 of file StackMapParser.h.
References assert(), E, llvm::StackMapParser< Endianness >::getNumConstants(), llvm::StackMapParser< Endianness >::getNumFunctions(), llvm::StackMapParser< Endianness >::getNumRecords(), and I.
Member Function Documentation
constants()
template<support::endianness Endianness> iterator_range< constant_iterator > llvm::StackMapParser< Endianness >::constants () const inline
Iterator range for constants.
Definition at line 405 of file StackMapParser.h.
References llvm::StackMapParser< Endianness >::constants_begin(), llvm::StackMapParser< Endianness >::constants_end(), and llvm::make_range().
constants_begin()
template<support::endianness Endianness> constant_iterator llvm::StackMapParser< Endianness >::constants_begin () const inline
Begin iterator for constants.
Definition at line 393 of file StackMapParser.h.
References llvm::StackMapParser< Endianness >::getConstant().
Referenced by llvm::StackMapParser< Endianness >::constants().
constants_end()
template<support::endianness Endianness> constant_iterator llvm::StackMapParser< Endianness >::constants_end () const inline
End iterator for constants.
Definition at line 398 of file StackMapParser.h.
References llvm::ArrayRef< T >::data(), and llvm::StackMapParser< Endianness >::getNumConstants().
Referenced by llvm::StackMapParser< Endianness >::constants().
functions()
template<support::endianness Endianness> iterator_range< function_iterator > llvm::StackMapParser< Endianness >::functions () const inline
Iterator range for functions.
Definition at line 382 of file StackMapParser.h.
References llvm::StackMapParser< Endianness >::functions_begin(), llvm::StackMapParser< Endianness >::functions_end(), and llvm::make_range().
functions_begin()
template<support::endianness Endianness> function_iterator llvm::StackMapParser< Endianness >::functions_begin () const inline
Begin iterator for functions.
Definition at line 370 of file StackMapParser.h.
References llvm::StackMapParser< Endianness >::getFunction().
Referenced by llvm::StackMapParser< Endianness >::functions().
functions_end()
template<support::endianness Endianness> function_iterator llvm::StackMapParser< Endianness >::functions_end () const inline
End iterator for functions.
Definition at line 375 of file StackMapParser.h.
References llvm::ArrayRef< T >::data(), and llvm::StackMapParser< Endianness >::getNumFunctions().
Referenced by llvm::StackMapParser< Endianness >::functions().
getConstant()
template<support::endianness Endianness> ConstantAccessor llvm::StackMapParser< Endianness >::getConstant (unsigned ConstantIndex) const inline
Return the large constant at the given index.
Definition at line 387 of file StackMapParser.h.
References llvm::StackMapParser< Endianness >::ConstantIndex, and llvm::ArrayRef< T >::data().
Referenced by llvm::StackMapParser< Endianness >::constants_begin().
getFunction()
template<support::endianness Endianness> FunctionAccessor llvm::StackMapParser< Endianness >::getFunction (unsigned FunctionIndex) const inline
Return an FunctionAccessor for the given function index.
Definition at line 364 of file StackMapParser.h.
References llvm::ArrayRef< T >::data().
Referenced by llvm::StackMapParser< Endianness >::functions_begin().
getNumConstants()
template<support::endianness Endianness> uint32_t llvm::StackMapParser< Endianness >::getNumConstants () const inline
Get the number of large constants in the stack map.
Definition at line 354 of file StackMapParser.h.
Referenced by llvm::StackMapParser< Endianness >::constants_end(), and llvm::StackMapParser< Endianness >::StackMapParser().
getNumFunctions()
template<support::endianness Endianness> uint32_t llvm::StackMapParser< Endianness >::getNumFunctions () const inline
Get the number of functions in the stack map.
Definition at line 349 of file StackMapParser.h.
Referenced by llvm::StackMapParser< Endianness >::functions_end(), and llvm::StackMapParser< Endianness >::StackMapParser().
getNumRecords()
template<support::endianness Endianness> uint32_t llvm::StackMapParser< Endianness >::getNumRecords () const inline
Get the number of stackmap records in the stackmap.
Definition at line 359 of file StackMapParser.h.
Referenced by llvm::StackMapParser< Endianness >::records_begin(), llvm::StackMapParser< Endianness >::records_end(), and llvm::StackMapParser< Endianness >::StackMapParser().
getRecord()
template<support::endianness Endianness> RecordAccessor llvm::StackMapParser< Endianness >::getRecord (unsigned RecordIndex) const inline
Return a RecordAccessor for the given record index.
Definition at line 410 of file StackMapParser.h.
References llvm::ArrayRef< T >::data().
Referenced by llvm::StackMapParser< Endianness >::records_begin(), and llvm::StackMapParser< Endianness >::records_end().
getVersion()
template<support::endianness Endianness> unsigned llvm::StackMapParser< Endianness >::getVersion () const inline
Get the version number of this stackmap. (Always returns 3).
Definition at line 346 of file StackMapParser.h.
records()
template<support::endianness Endianness> iterator_range< record_iterator > llvm::StackMapParser< Endianness >::records () const inline
Iterator range for records.
Definition at line 433 of file StackMapParser.h.
References llvm::make_range(), llvm::StackMapParser< Endianness >::records_begin(), and llvm::StackMapParser< Endianness >::records_end().
records_begin()
template<support::endianness Endianness> record_iterator llvm::StackMapParser< Endianness >::records_begin () const inline
Begin iterator for records.
Definition at line 416 of file StackMapParser.h.
References llvm::StackMapParser< Endianness >::getNumRecords(), and llvm::StackMapParser< Endianness >::getRecord().
Referenced by llvm::StackMapParser< Endianness >::records().
records_end()
template<support::endianness Endianness> record_iterator llvm::StackMapParser< Endianness >::records_end () const inline
End iterator for records.
Definition at line 423 of file StackMapParser.h.
References llvm::StackMapParser< Endianness >::getNumRecords(), and llvm::StackMapParser< Endianness >::getRecord().
Referenced by llvm::StackMapParser< Endianness >::records().
validateHeader()
template<support::endianness Endianness> static Error llvm::StackMapParser< Endianness >::validateHeader (ArrayRef< uint8_t > StackMapSection) inline static
Validates the header of the specified stack map section.
Definition at line 325 of file StackMapParser.h.
References llvm::object::createError(), and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/Object/StackMapParser.h