LLVM: llvm::AArch64TargetMachine Class Reference
llvm::AArch64TargetMachine Class Reference
#include "Target/AArch64/AArch64TargetMachine.h"
Public Member Functions
AArch64TargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool JIT, bool IsLittleEndian)
Create an AArch64 architecture model.
~AArch64TargetMachine () override
const AArch64Subtarget * getSubtargetImpl (const Function &F) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
const AArch64Subtarget * getSubtargetImpl () const =delete
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
TargetTransformInfo getTargetTransformInfo (const Function &F) override
Return a TargetTransformInfo for a given function.
TargetLoweringObjectFile * getObjFileLowering () const override
yaml::MachineFunctionInfo * createDefaultFuncInfoYAML () const override
Allocate and return a default initialized instance of the YAML representation for the MachineFunctionInfo.
yaml::MachineFunctionInfo * convertFuncInfoToYAML (const MachineFunction &MF) const override
Allocate and initialize an instance of the YAML representation of the MachineFunctionInfo.
bool parseMachineFunctionInfo (const yaml::MachineFunctionInfo &, PerFunctionMIParsingState &PFS, SMDiagnostic &Error, SMRange &SourceRange) const override
Parse out the target's MachineFunctionInfo from the YAML reprsentation.
bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const override
Returns true if a cast between SrcAS and DestAS is a noop.
Public Member Functions inherited from llvm::LLVMTargetMachine
TargetTransformInfo getTargetTransformInfo (const Function &F) override
Get a TargetTransformInfo implementation for the target.
bool addPassesToEmitFile (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, bool DisableVerify=true, MachineModuleInfoWrapperPass *MMIWP=nullptr) override
Add passes to the specified pass manager to get the specified file emitted.
virtual Error buildCodeGenPipeline (ModulePassManager &, MachineFunctionPassManager &, MachineFunctionAnalysisManager &, raw_pwrite_stream &, raw_pwrite_stream *, CodeGenFileType, CGPassBuilderOption, PassInstrumentationCallbacks *)
virtual std::pair< StringRef, bool > getPassNameFromLegacyName (StringRef)
bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_pwrite_stream &Out, bool DisableVerify=true) override
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
virtual bool isMachineVerifierClean () const
Returns true if the target is expected to pass all machine verifier checks.
bool addAsmPrinter (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Context)
Adds an AsmPrinter pass to the pipeline that prints assembly or machine code from the MI representation.
Expected< std::unique_ptr< MCStreamer > > createMCStreamer (raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Ctx)
virtual bool usesPhysRegsForValues () const
True if the target uses physical regs (as nearly all targets do).
virtual bool useIPRA () const
True if the target wants to use interprocedural register allocation by default.
virtual int unqualifiedInlineAsmVariant () const
The default variant to use in unqualified asm instructions.
Public Member Functions inherited from llvm::TargetMachine
TargetMachine (const TargetMachine &)=delete
void operator= (const TargetMachine &)=delete
virtual ~TargetMachine ()
const Target & getTarget () const
const Triple & getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
void setTargetFeatureString (StringRef FS)
template<typename STC >
const STC & getSubtarget (const Function &F) const
This method returns a pointer to the specified type of TargetSubtargetInfo.
const DataLayout createDataLayout () const
Create a DataLayout.
bool isCompatibleDataLayout (const DataLayout &Candidate) const
Test if a DataLayout if compatible with the CodeGen for this target.
unsigned getPointerSize (unsigned AS) const
Get the pointer size for this target.
unsigned getPointerSizeInBits (unsigned AS) const
unsigned getProgramPointerSize () const
unsigned getAllocaPointerSize () const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
Return target specific asm information.
const MCRegisterInfo * getMCRegisterInfo () const
const MCInstrInfo * getMCInstrInfo () const
const MCSubtargetInfo * getMCSubtargetInfo () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
If intrinsic information is available, return it. If not, return null.
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
Returns the code generation relocation model.
CodeModel::Model getCodeModel () const
Returns the code model.
bool isPositionIndependent () const
bool shouldAssumeDSOLocal (const Module &M, const GlobalValue *GV) const
bool useEmulatedTLS () const
Returns true if this target uses emulated TLS.
TLSModel::Model getTLSModel (const GlobalValue *GV) const
Returns the TLS model which should be used for the given global variable.
CodeGenOpt::Level getOptLevel () const
Returns the optimization level: None, Less, Default, or Aggressive.
void setOptLevel (CodeGenOpt::Level Level)
Overrides the optimization level.
void setFastISel (bool Enable)
bool getO0WantsFastISel ()
void setO0WantsFastISel (bool Enable)
void setGlobalISel (bool Enable)
void setGlobalISelAbort (GlobalISelAbortMode Mode)
void setMachineOutliner (bool Enable)
void setSupportsDefaultOutlining (bool Enable)
void setSupportsDebugEntryValues (bool Enable)
bool getAIXExtendedAltivecABI () const
bool getUniqueSectionNames () const
bool getUniqueBasicBlockSectionNames () const
Return true if unique basic block section names must be generated.
bool getDataSections () const
Return true if data objects should be emitted into their own section, corresponds to -fdata-sections.
bool getFunctionSections () const
Return true if functions should be emitted into their own section, corresponding to -ffunction-sections.
bool getIgnoreXCOFFVisibility () const
Return true if visibility attribute should not be emitted in XCOFF, corresponding to -mignore-xcoff-visibility.
bool getXCOFFTracebackTable () const
Return true if XCOFF traceback table should be emitted, corresponding to -xcoff-traceback-table.
llvm::BasicBlockSection getBBSectionsType () const
If basic blocks should be emitted into their own section, corresponding to -fbasic-block-sections.
const MemoryBuffer * getBBSectionsFuncListBuf () const
Get the list of functions and basic block ids that need unique sections.
void setPGOOption (Optional< PGOOptions > PGOOpt)
const Optional< PGOOptions > & getPGOOption () const
virtual unsigned getAssumedAddrSpace (const Value *V) const
If the specified generic pointer could be assumed as a pointer to a specific address space, return that address space.
virtual std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const
If the specified predicate checks whether a generic pointer falls within a specified address space, return that generic pointer and the address space being queried.
TargetIRAnalysis getTargetIRAnalysis ()
Get a TargetIRAnalysis appropriate for the target.
virtual void adjustPassManager (PassManagerBuilder &)
Allow the target to modify the pass manager, e.g.
virtual void registerPassBuilderCallbacks (PassBuilder &)
Allow the target to modify the pass pipeline with New Pass Manager (similar to adjustPassManager for Legacy Pass manager).
virtual void registerDefaultAliasAnalyses (AAManager &)
Allow the target to register alias analyses with the AAManager for use with the new pass manager.
virtual bool targetSchedulesPostRAScheduling () const
True if subtarget inserts the final scheduling pass on its own.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV) const
virtual unsigned getSjLjDataSize () const
Protected Attributes
std::unique_ptr< TargetLoweringObjectFile > TLOF
StringMap< std::unique_ptr< AArch64Subtarget > > SubtargetMap
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
The Target that this machine was created for.
const DataLayout DL
DataLayout for the target: keep ABI type size and alignment.
Triple TargetTriple
Triple string, CPU name, and target feature strings the TargetMachine instance is created with.
std::string TargetCPU
std::string TargetFS
Reloc::Model RM = Reloc::Static
CodeModel::Model CMModel = CodeModel::Small
CodeGenOpt::Level OptLevel = CodeGenOpt::Default
std::unique_ptr< const MCAsmInfo > AsmInfo
Contains target specific asm information.
std::unique_ptr< const MCRegisterInfo > MRI
std::unique_ptr< const MCInstrInfo > MII
std::unique_ptr< const MCSubtargetInfo > STI
unsigned RequireStructuredCFG: 1
unsigned O0WantsFastISel: 1
Optional< PGOOptions > PGOOption = None
Additional Inherited Members
Static Public Member Functions inherited from llvm::TargetMachine
static std::pair< int, int > parseBinutilsVersion (StringRef Version)
Public Attributes inherited from llvm::TargetMachine
const TargetOptions DefaultOptions
TargetOptions Options
Static Public Attributes inherited from llvm::TargetMachine
static constexpr unsigned DefaultSjLjDataSize = 32
The integer bit size to use for SjLj based exception handling.
Protected Member Functions inherited from llvm::LLVMTargetMachine
LLVMTargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Detailed Description
Definition at line 23 of file AArch64TargetMachine.h.
Constructor & Destructor Documentation
AArch64TargetMachine()
AArch64TargetMachine::AArch64TargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool JIT, bool IsLittleEndian)
Create an AArch64 architecture model.
Definition at line 298 of file AArch64TargetMachine.cpp.
References llvm::Triple::aarch64_32, llvm::Disable, EnableGlobalISelAtO, llvm::TargetMachine::getCodeModel(), llvm::TargetMachine::getMCAsmInfo(), llvm::TargetMachine::getOptLevel(), llvm::Triple::GNUILP32, llvm::LLVMTargetMachine::initAsmInfo(), llvm::CodeModel::Kernel, llvm::CodeModel::Large, llvm::TargetOptions::NoTrapAfterNoreturn, llvm::TargetMachine::setGlobalISel(), llvm::TargetMachine::setGlobalISelAbort(), llvm::TargetMachine::setMachineOutliner(), llvm::TargetMachine::setSupportsDebugEntryValues(), llvm::TargetMachine::setSupportsDefaultOutlining(), llvm::CodeModel::Small, llvm::CodeModel::Tiny, llvm::TargetOptions::TLSSize, and llvm::TargetOptions::TrapUnreachable.
~AArch64TargetMachine()
AArch64TargetMachine::~AArch64TargetMachine () override default
Member Function Documentation
convertFuncInfoToYAML()
yaml::MachineFunctionInfo * AArch64TargetMachine::convertFuncInfoToYAML (const MachineFunction & MF) const override virtual
Allocate and initialize an instance of the YAML representation of the MachineFunctionInfo.
Reimplemented from llvm::TargetMachine.
Definition at line 800 of file AArch64TargetMachine.cpp.
References llvm::MachineFunction::getInfo().
createDefaultFuncInfoYAML()
yaml::MachineFunctionInfo * AArch64TargetMachine::createDefaultFuncInfoYAML () const override virtual
Allocate and return a default initialized instance of the YAML representation for the MachineFunctionInfo.
Reimplemented from llvm::TargetMachine.
Definition at line 795 of file AArch64TargetMachine.cpp.
createPassConfig()
TargetPassConfig * AArch64TargetMachine::createPassConfig (PassManagerBase & PM) override virtual
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 511 of file AArch64TargetMachine.cpp.
getObjFileLowering()
TargetLoweringObjectFile * llvm::AArch64TargetMachine::getObjFileLowering () const inline override virtual
Reimplemented from llvm::TargetMachine.
Definition at line 46 of file AArch64TargetMachine.h.
References TLOF.
getSubtargetImpl() [1/2]
const AArch64Subtarget * llvm::AArch64TargetMachine::getSubtargetImpl () const delete
getSubtargetImpl() [2/2]
const AArch64Subtarget * AArch64TargetMachine::getSubtargetImpl (const Function &) const override virtual
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 362 of file AArch64TargetMachine.cpp.
References assert(), F, I, llvm::TargetMachine::resetTargetOptions(), SubtargetMap, SVEVectorBitsMaxOpt, SVEVectorBitsMinOpt, llvm::TargetMachine::TargetCPU, llvm::TargetMachine::TargetFS, and llvm::TargetMachine::TargetTriple.
getTargetTransformInfo()
TargetTransformInfo AArch64TargetMachine::getTargetTransformInfo (const Function & F) override virtual
Return a TargetTransformInfo for a given function.
The returned TargetTransformInfo is specialized to the subtarget corresponding to F.
Reimplemented from llvm::TargetMachine.
Definition at line 507 of file AArch64TargetMachine.cpp.
References F.
isNoopAddrSpaceCast()
bool llvm::AArch64TargetMachine::isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const inline override virtual
Returns true if a cast between SrcAS and DestAS is a noop.
Reimplemented from llvm::TargetMachine.
Definition at line 59 of file AArch64TargetMachine.h.
parseMachineFunctionInfo()
bool AArch64TargetMachine::parseMachineFunctionInfo (const yaml::MachineFunctionInfo & , PerFunctionMIParsingState & PFS, SMDiagnostic & Error, SMRange & SourceRange) const override virtual
Parse out the target's MachineFunctionInfo from the YAML reprsentation.
Reimplemented from llvm::TargetMachine.
Definition at line 805 of file AArch64TargetMachine.cpp.
References llvm::MachineFunction::getInfo(), and llvm::PerFunctionMIParsingState::MF.
Member Data Documentation
SubtargetMap
StringMap<std::unique_ptr<AArch64Subtarget> > llvm::AArch64TargetMachine::SubtargetMap mutable protected
Definition at line 26 of file AArch64TargetMachine.h.
Referenced by getSubtargetImpl().
TLOF
std::unique_ptr<TargetLoweringObjectFile> llvm::AArch64TargetMachine::TLOF protected
Definition at line 25 of file AArch64TargetMachine.h.
Referenced by getObjFileLowering().
The documentation for this class was generated from the following files:
lib/Target/AArch64/AArch64TargetMachine.h
lib/Target/AArch64/AArch64TargetMachine.cpp