LLVM: llvm::jitlink::InProcessMemoryManager::IPInFlightAlloc Class Reference
llvm::jitlink::InProcessMemoryManager::IPInFlightAlloc Class Reference
Public Member Functions
IPInFlightAlloc (InProcessMemoryManager &MemMgr, LinkGraph &G, BasicLayout BL, sys::MemoryBlock StandardSegments, sys::MemoryBlock FinalizationSegments)
void finalize (OnFinalizedFunction OnFinalized) override
Called to transfer working memory to the target and apply finalization.
void abandon (OnAbandonedFunction OnAbandoned) override
Called prior to finalization if the allocation should be abandoned.
Public Member Functions inherited from llvm::jitlink::JITLinkMemoryManager::InFlightAlloc
virtual ~InFlightAlloc ()
Expected< FinalizedAlloc > finalize ()
Synchronous convenience version of finalize.
Additional Inherited Members
Public Types inherited from llvm::jitlink::JITLinkMemoryManager::InFlightAlloc
using OnFinalizedFunction = unique_function<void(Expected<FinalizedAlloc>)>
using OnAbandonedFunction = unique_function<void(Error)>
Detailed Description
Definition at line 231 of file JITLinkMemoryManager.cpp.
Constructor & Destructor Documentation
IPInFlightAlloc()
llvm::jitlink::InProcessMemoryManager::IPInFlightAlloc::IPInFlightAlloc (InProcessMemoryManager & MemMgr, LinkGraph & G, BasicLayout BL, sys::MemoryBlock StandardSegments, sys::MemoryBlock FinalizationSegments) inline
Definition at line 234 of file JITLinkMemoryManager.cpp.
References G.
Member Function Documentation
abandon()
void llvm::jitlink::InProcessMemoryManager::IPInFlightAlloc::abandon (OnAbandonedFunction OnAbandoned) inline override virtual
Called prior to finalization if the allocation should be abandoned.
Implements llvm::jitlink::JITLinkMemoryManager::InFlightAlloc.
Definition at line 267 of file JITLinkMemoryManager.cpp.
References llvm::errorCodeToError(), llvm::joinErrors(), llvm::sys::Memory::releaseMappedMemory(), and llvm::Error::success().
finalize()
void llvm::jitlink::InProcessMemoryManager::IPInFlightAlloc::finalize (OnFinalizedFunction OnFinalized) inline override virtual
Called to transfer working memory to the target and apply finalization.
Implements llvm::jitlink::JITLinkMemoryManager::InFlightAlloc.
Definition at line 241 of file JITLinkMemoryManager.cpp.
References llvm::jitlink::LinkGraph::allocActions(), llvm::errorCodeToError(), and llvm::sys::Memory::releaseMappedMemory().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/JITLink/JITLinkMemoryManager.cpp