LLVM: AMDGPUMCInstLower Class Reference
AMDGPUMCInstLower Class Reference
#include "Target/AMDGPU/AMDGPUMCInstLower.h"
Public Member Functions
AMDGPUMCInstLower (MCContext &ctx, const TargetSubtargetInfo &ST, const AsmPrinter &AP)
bool lowerOperand (const MachineOperand &MO, MCOperand &MCOp) const
void lower (const MachineInstr *MI, MCInst &OutMI) const
Lower a MachineInstr to an MCInst.
Detailed Description
Definition at line 29 of file AMDGPUMCInstLower.h.
Constructor & Destructor Documentation
AMDGPUMCInstLower()
AMDGPUMCInstLower::AMDGPUMCInstLower (MCContext & ctx, const TargetSubtargetInfo & ST, const AsmPrinter & AP)
Definition at line 39 of file AMDGPUMCInstLower.cpp.
Member Function Documentation
lower()
void AMDGPUMCInstLower::lower (const MachineInstr * MI, MCInst & OutMI) const
Lower a MachineInstr to an MCInst.
Definition at line 116 of file AMDGPUMCInstLower.cpp.
References C, llvm::MCOperand::createImm(), llvm::TargetSubtargetInfo::getInstrInfo(), lowerOperand(), MI, and TII.
lowerOperand()
bool AMDGPUMCInstLower::lowerOperand (const MachineOperand & MO, MCOperand & MCOp) const
Definition at line 65 of file AMDGPUMCInstLower.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCConstantExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getMCSymbol(), llvm::AsmPrinter::getNameWithPrefix(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getReg(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm::MCSymbol::getVariableValue(), getVariantKind(), llvm_unreachable, llvm::MachineOperand::MO_ExternalSymbol, llvm::SIInstrInfo::MO_FAR_BRANCH_OFFSET, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_MCSymbol, llvm::MachineOperand::MO_Register, llvm::MachineOperand::MO_RegisterMask, Offset, and llvm::MCSymbol::setExternal().
Referenced by lower(), and R600MCInstLower::lower().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUMCInstLower.h
lib/Target/AMDGPU/AMDGPUMCInstLower.cpp