LLVM: QualType Class Reference
QualType Class Reference final
#include "llvm/Demangle/ItaniumDemangle.h"
Public Member Functions
QualType (const Node *Child_, Qualifiers Quals_)
template<typename Fn >
void match (Fn F) const
bool hasRHSComponentSlow (OutputBuffer &OB) const override
bool hasArraySlow (OutputBuffer &OB) const override
bool hasFunctionSlow (OutputBuffer &OB) const override
void printLeft (OutputBuffer &OB) const override
void printRight (OutputBuffer &OB) const override
Public Member Functions inherited from Node
Node (Kind K_, Cache RHSComponentCache_=Cache::No, Cache ArrayCache_=Cache::No, Cache FunctionCache_=Cache::No)
template<typename Fn >
void visit (Fn F) const
Visit the most-derived object corresponding to this object.
bool hasRHSComponent (OutputBuffer &OB) const
bool hasArray (OutputBuffer &OB) const
bool hasFunction (OutputBuffer &OB) const
Kind getKind () const
virtual const Node * getSyntaxNode (OutputBuffer &) const
void print (OutputBuffer &OB) const
virtual StringView getBaseName () const
virtual ~Node ()=default
DEMANGLE_DUMP_METHOD void dump () const
Protected Member Functions
void printQuals (OutputBuffer &OB) const
Protected Attributes
const Qualifiers Quals
const Node * Child
Additional Inherited Members
Public Types inherited from Node
enum Kind : unsigned char
enum class Cache : unsigned char { Yes , No , Unknown }
Three-way bool to track a cached value.
Public Attributes inherited from Node
Cache RHSComponentCache
Tracks if this node has a component on its right side, in which case we need to call printRight.
Cache ArrayCache
Track if this node is a (possibly qualified) array type.
Cache FunctionCache
Track if this node is a (possibly qualified) function type.
Detailed Description
Definition at line 437 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
QualType()
QualType::QualType (const Node * Child_, Qualifiers Quals_) inline
Definition at line 452 of file ItaniumDemangle.h.
Member Function Documentation
hasArraySlow()
bool QualType::hasArraySlow (OutputBuffer & OB) const inline override virtual
Reimplemented from Node.
Definition at line 462 of file ItaniumDemangle.h.
References Child, and Node::hasArray().
hasFunctionSlow()
bool QualType::hasFunctionSlow (OutputBuffer & OB) const inline override virtual
Reimplemented from Node.
Definition at line 465 of file ItaniumDemangle.h.
References Child, and Node::hasFunction().
hasRHSComponentSlow()
bool QualType::hasRHSComponentSlow (OutputBuffer & OB) const inline override virtual
Reimplemented from Node.
Definition at line 459 of file ItaniumDemangle.h.
References Child, and Node::hasRHSComponent().
match()
template<typename Fn > void QualType::match (Fn F) const inline
Definition at line 457 of file ItaniumDemangle.h.
References Child, F, and Quals.
printLeft()
void QualType::printLeft (OutputBuffer & OB) const inline override virtual
Implements Node.
Definition at line 469 of file ItaniumDemangle.h.
References Child, Node::printLeft(), and printQuals().
printQuals()
void QualType::printQuals (OutputBuffer & OB) const inline protected
Definition at line 442 of file ItaniumDemangle.h.
References QualConst, QualRestrict, Quals, and QualVolatile.
Referenced by printLeft().
printRight()
void QualType::printRight (OutputBuffer & OB) const inline override virtual
Reimplemented from Node.
Definition at line 474 of file ItaniumDemangle.h.
References Child, and Node::printRight().
Member Data Documentation
Child
const Node* QualType::Child protected
Definition at line 440 of file ItaniumDemangle.h.
Referenced by hasArraySlow(), hasFunctionSlow(), hasRHSComponentSlow(), match(), printLeft(), and printRight().
Quals
const Qualifiers QualType::Quals protected
Definition at line 439 of file ItaniumDemangle.h.
Referenced by match(), and printQuals().
The documentation for this class was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h