LLVM: llvm::SCEVLoopAddRecRewriter Class Reference
llvm::SCEVLoopAddRecRewriter Class Reference
The SCEVLoopAddRecRewriter takes a scalar evolution expression and applies the Map (Loop -> SCEV) to all AddRecExprs.
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
Public Member Functions
SCEVLoopAddRecRewriter (ScalarEvolution &SE, LoopToScevMapT &M)
const SCEV * visitAddRecExpr (const SCEVAddRecExpr *Expr)
Public Member Functions inherited from llvm::SCEVRewriteVisitor< SCEVLoopAddRecRewriter >
SCEVRewriteVisitor (ScalarEvolution &SE)
const SCEV * visit (const SCEV *S)
const SCEV * visitConstant (const SCEVConstant *Constant)
const SCEV * visitPtrToIntExpr (const SCEVPtrToIntExpr *Expr)
const SCEV * visitTruncateExpr (const SCEVTruncateExpr *Expr)
const SCEV * visitZeroExtendExpr (const SCEVZeroExtendExpr *Expr)
const SCEV * visitSignExtendExpr (const SCEVSignExtendExpr *Expr)
const SCEV * visitAddExpr (const SCEVAddExpr *Expr)
const SCEV * visitMulExpr (const SCEVMulExpr *Expr)
const SCEV * visitUDivExpr (const SCEVUDivExpr *Expr)
const SCEV * visitAddRecExpr (const SCEVAddRecExpr *Expr)
const SCEV * visitSMaxExpr (const SCEVSMaxExpr *Expr)
const SCEV * visitUMaxExpr (const SCEVUMaxExpr *Expr)
const SCEV * visitSMinExpr (const SCEVSMinExpr *Expr)
const SCEV * visitUMinExpr (const SCEVUMinExpr *Expr)
const SCEV * visitSequentialUMinExpr (const SCEVSequentialUMinExpr *Expr)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *Expr)
Public Member Functions inherited from llvm::SCEVVisitor< SC, RetVal >
RetVal visit (const SCEV *S)
RetVal visitCouldNotCompute (const SCEVCouldNotCompute *S)
Static Public Member Functions
static const SCEV * rewrite (const SCEV *Scev, LoopToScevMapT &Map, ScalarEvolution &SE)
Additional Inherited Members
Protected Attributes inherited from llvm::SCEVRewriteVisitor< SCEVLoopAddRecRewriter >
ScalarEvolution & SE
DenseMap< const SCEV *, const SCEV * > RewriteResults
Detailed Description
The SCEVLoopAddRecRewriter takes a scalar evolution expression and applies the Map (Loop -> SCEV) to all AddRecExprs.
Definition at line 934 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
SCEVLoopAddRecRewriter()
llvm::SCEVLoopAddRecRewriter::SCEVLoopAddRecRewriter (ScalarEvolution & SE, LoopToScevMapT & M) inline
Definition at line 937 of file ScalarEvolutionExpressions.h.
Member Function Documentation
rewrite()
static const SCEV * llvm::SCEVLoopAddRecRewriter::rewrite (const SCEV * Scev, LoopToScevMapT & Map, ScalarEvolution & SE) inline static
Definition at line 940 of file ScalarEvolutionExpressions.h.
References Rewriter, and llvm::SCEVRewriteVisitor< SCEVLoopAddRecRewriter >::SE.
visitAddRecExpr()
const SCEV * llvm::SCEVLoopAddRecRewriter::visitAddRecExpr (const SCEVAddRecExpr * Expr) inline
Definition at line 946 of file ScalarEvolutionExpressions.h.
References llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::ScalarEvolution::getAddRecExpr(), llvm::SCEVAddRecExpr::getLoop(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::SCEVNAryExpr::operands(), Operands, llvm::SCEVRewriteVisitor< SCEVLoopAddRecRewriter >::SE, and llvm::SCEVRewriteVisitor< SCEVLoopAddRecRewriter >::visit().
The documentation for this class was generated from the following file:
include/llvm/Analysis/ScalarEvolutionExpressions.h