LLVM: llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory Class Reference
llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory Class Reference
#include "llvm/ADT/ImmutableMap.h"
Public Member Functions
Factory (bool canonicalize=true)
Factory (BumpPtrAllocator &Alloc, bool canonicalize=true)
Factory (const Factory &)=delete
Factory & operator= (const Factory &)=delete
ImmutableMap getEmptyMap ()
LLVM_NODISCARD ImmutableMap add (ImmutableMap Old, key_type_ref K, data_type_ref D)
LLVM_NODISCARD ImmutableMap remove (ImmutableMap Old, key_type_ref K)
TreeTy::Factory * getTreeFactory () const
Detailed Description
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>>
class llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory
Definition at line 83 of file ImmutableMap.h.
Constructor & Destructor Documentation
Factory() [1/3]
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::Factory (bool canonicalize = true) inline
Definition at line 88 of file ImmutableMap.h.
Factory() [2/3]
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::Factory (BumpPtrAllocator & Alloc, bool canonicalize = true) inline
Definition at line 90 of file ImmutableMap.h.
References F.
Factory() [3/3]
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::Factory (const Factory &) delete
Member Function Documentation
add()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> LLVM_NODISCARD ImmutableMap llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::add (ImmutableMap Old, key_type_ref K, data_type_ref D) inline
Definition at line 98 of file ImmutableMap.h.
References D, F, llvm::ImmutableMap< KeyT, ValT, ValInfo >::ImmutableMap(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root, and T.
getEmptyMap()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> ImmutableMap llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::getEmptyMap () inline
Definition at line 96 of file ImmutableMap.h.
References F, and llvm::ImmutableMap< KeyT, ValT, ValInfo >::ImmutableMap().
getTreeFactory()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> TreeTy::Factory * llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::getTreeFactory () const inline
Definition at line 109 of file ImmutableMap.h.
References F.
operator=()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> Factory & llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::operator= (const Factory &) delete
remove()
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> LLVM_NODISCARD ImmutableMap llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::remove (ImmutableMap Old, key_type_ref K) inline
Definition at line 104 of file ImmutableMap.h.
References F, llvm::ImmutableMap< KeyT, ValT, ValInfo >::ImmutableMap(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root, and T.
The documentation for this class was generated from the following file:
include/llvm/ADT/ImmutableMap.h