LLVM: llvm::DWARFUnitHeader Class Reference
llvm::DWARFUnitHeader Class Reference
Base class describing the header of any kind of "unit." Some information is specific to certain unit types.
#include "llvm/DebugInfo/DWARF/DWARFUnit.h"
Public Member Functions
bool extract (DWARFContext &Context, const DWARFDataExtractor &debug_info, uint64_t *offset_ptr, DWARFSectionKind SectionKind)
Parse a unit header from debug_info starting at offset_ptr.
bool applyIndexEntry (const DWARFUnitIndex::Entry *Entry)
uint64_t getOffset () const
const dwarf::FormParams & getFormParams () const
uint16_t getVersion () const
dwarf::DwarfFormat getFormat () const
uint8_t getAddressByteSize () const
uint8_t getRefAddrByteSize () const
uint8_t getDwarfOffsetByteSize () const
uint64_t getLength () const
uint64_t getAbbrOffset () const
Optional< uint64_t > getDWOId () const
void setDWOId (uint64_t Id)
const DWARFUnitIndex::Entry * getIndexEntry () const
uint64_t getTypeHash () const
uint64_t getTypeOffset () const
uint8_t getUnitType () const
bool isTypeUnit () const
uint8_t getSize () const
uint8_t getUnitLengthFieldByteSize () const
uint64_t getNextUnitOffset () const
Detailed Description
Base class describing the header of any kind of "unit." Some information is specific to certain unit types.
We separate this class out so we can parse the header before deciding what specific kind of unit to construct.
Definition at line 47 of file DWARFUnit.h.
Member Function Documentation
applyIndexEntry()
bool DWARFUnitHeader::applyIndexEntry (const DWARFUnitIndex::Entry * Entry)
Definition at line 334 of file DWARFUnit.cpp.
References assert(), llvm::DWARFUnitIndex::Entry::getContribution(), getLength(), and getUnitLengthFieldByteSize().
extract()
bool DWARFUnitHeader::extract (DWARFContext & Context, const DWARFDataExtractor & debug_info, uint64_t * offset_ptr, DWARFSectionKind SectionKind)
Parse a unit header from debug_info starting at offset_ptr.
Note that SectionKind is used as a hint to guess the unit type for DWARF formats prior to DWARFv5. In DWARFv5 the unit type is explicitly defined in the header and the hint is ignored.
Definition at line 233 of file DWARFUnit.cpp.
References llvm::dwarf::FormParams::AddrSize, assert(), llvm::DWARFContext::checkAddressSizeSupported(), llvm::createStringError(), llvm::DW_SECT_EXT_TYPES, llvm::dwarf::FormParams::Format, getAddressByteSize(), llvm::dwarf::FormParams::getDwarfOffsetByteSize(), getLength(), llvm::DWARFContext::getMaxSupportedVersion(), getNextUnitOffset(), getUnitLengthFieldByteSize(), getVersion(), llvm::invalid_argument, llvm::DWARFContext::isSupportedVersion(), isTypeUnit(), llvm::joinErrors(), llvm::Error::success(), and llvm::dwarf::FormParams::Version.
getAbbrOffset()
uint64_t llvm::DWARFUnitHeader::getAbbrOffset () const inline
Definition at line 91 of file DWARFUnit.h.
Referenced by llvm::DWARFUnit::getAbbreviationsOffset(), and llvm::DWARFUnit::getAbbrOffset().
getAddressByteSize()
uint8_t llvm::DWARFUnitHeader::getAddressByteSize () const inline
Definition at line 85 of file DWARFUnit.h.
References llvm::dwarf::FormParams::AddrSize.
Referenced by extract(), llvm::DWARFUnit::findRnglistFromOffset(), and llvm::DWARFUnit::getAddressByteSize().
getDwarfOffsetByteSize()
uint8_t llvm::DWARFUnitHeader::getDwarfOffsetByteSize () const inline
Definition at line 87 of file DWARFUnit.h.
References llvm::dwarf::FormParams::getDwarfOffsetByteSize().
Referenced by llvm::DWARFUnit::getDwarfOffsetByteSize().
getDWOId()
Optional< uint64_t > llvm::DWARFUnitHeader::getDWOId () const inline
Definition at line 92 of file DWARFUnit.h.
Referenced by llvm::DWARFUnit::getDWOId().
getFormat()
dwarf::DwarfFormat llvm::DWARFUnitHeader::getFormat () const inline
Definition at line 84 of file DWARFUnit.h.
References llvm::dwarf::FormParams::Format.
Referenced by llvm::DWARFUnit::determineStringOffsetsTableContribution(), llvm::DWARFUnit::determineStringOffsetsTableContributionDWO(), llvm::DWARFUnit::getFormat(), and llvm::DWARFUnit::tryExtractDIEsIfNeeded().
getFormParams()
const dwarf::FormParams & llvm::DWARFUnitHeader::getFormParams () const inline
Definition at line 82 of file DWARFUnit.h.
Referenced by llvm::DWARFUnit::getFormParams().
getIndexEntry()
const DWARFUnitIndex::Entry * llvm::DWARFUnitHeader::getIndexEntry () const inline
Definition at line 97 of file DWARFUnit.h.
Referenced by llvm::DWARFUnit::determineStringOffsetsTableContributionDWO(), llvm::DWARFUnit::getLineTableOffset(), and llvm::DWARFUnit::tryExtractDIEsIfNeeded().
getLength()
uint64_t llvm::DWARFUnitHeader::getLength () const inline
Definition at line 90 of file DWARFUnit.h.
Referenced by applyIndexEntry(), extract(), and llvm::DWARFUnit::getLength().
getNextUnitOffset()
uint64_t llvm::DWARFUnitHeader::getNextUnitOffset () const inline
Definition at line 108 of file DWARFUnit.h.
References getUnitLengthFieldByteSize().
Referenced by extract(), and llvm::DWARFUnit::getNextUnitOffset().
getOffset()
uint64_t llvm::DWARFUnitHeader::getOffset () const inline
Definition at line 81 of file DWARFUnit.h.
Referenced by llvm::DWARFUnit::getOffset().
getRefAddrByteSize()
uint8_t llvm::DWARFUnitHeader::getRefAddrByteSize () const inline
Definition at line 86 of file DWARFUnit.h.
References llvm::dwarf::FormParams::getRefAddrByteSize().
Referenced by llvm::DWARFUnit::getRefAddrByteSize().
getSize()
uint8_t llvm::DWARFUnitHeader::getSize () const inline
Definition at line 104 of file DWARFUnit.h.
Referenced by llvm::DWARFUnit::getHeaderSize().
getTypeHash()
uint64_t llvm::DWARFUnitHeader::getTypeHash () const inline
Definition at line 98 of file DWARFUnit.h.
Referenced by llvm::DWARFTypeUnit::getTypeHash().
getTypeOffset()
uint64_t llvm::DWARFUnitHeader::getTypeOffset () const inline
Definition at line 99 of file DWARFUnit.h.
Referenced by llvm::DWARFTypeUnit::getTypeOffset().
getUnitLengthFieldByteSize()
uint8_t llvm::DWARFUnitHeader::getUnitLengthFieldByteSize () const inline
Definition at line 105 of file DWARFUnit.h.
References llvm::dwarf::FormParams::Format, and llvm::dwarf::getUnitLengthFieldByteSize().
Referenced by applyIndexEntry(), extract(), and getNextUnitOffset().
getUnitType()
uint8_t llvm::DWARFUnitHeader::getUnitType () const inline
Definition at line 100 of file DWARFUnit.h.
Referenced by llvm::DWARFUnit::getUnitType().
getVersion()
uint16_t llvm::DWARFUnitHeader::getVersion () const inline
Definition at line 83 of file DWARFUnit.h.
References llvm::dwarf::FormParams::Version.
Referenced by extract(), llvm::DWARFUnit::getVersion(), and llvm::DWARFUnit::tryExtractDIEsIfNeeded().
isTypeUnit()
bool llvm::DWARFUnitHeader::isTypeUnit () const inline
Definition at line 101 of file DWARFUnit.h.
Referenced by extract(), and llvm::DWARFUnit::isTypeUnit().
setDWOId()
void llvm::DWARFUnitHeader::setDWOId (uint64_t Id) inline
Definition at line 93 of file DWARFUnit.h.
References assert().
Referenced by llvm::DWARFUnit::setDWOId(), and llvm::DWARFUnit::tryExtractDIEsIfNeeded().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFUnit.h
lib/DebugInfo/DWARF/DWARFUnit.cpp