LLVM: lib/Transforms/Coroutines/CoroSplit.cpp File Reference
CoroSplit.cpp File Reference
#include "llvm/Transforms/Coroutines/CoroSplit.h"
#include "CoroInstr.h"
#include "CoroInternal.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/CallGraphSCCPass.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/LazyCallGraph.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/Verifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/PrettyStackTrace.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/CallGraphUpdater.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/ValueMapper.h"
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <iterator>
Macros
#define DEBUG_TYPE "coro-split"
Functions
static void maybeFreeRetconStorage (IRBuilder<> &Builder, const coro::Shape &Shape, Value *FramePtr, CallGraph *CG)
static bool replaceCoroEndAsync (AnyCoroEndInst *End)
Replace an llvm.coro.end.async.
static void replaceFallthroughCoroEnd (AnyCoroEndInst *End, const coro::Shape &Shape, Value *FramePtr, bool InResume, CallGraph *CG)
Replace a non-unwind call to llvm.coro.end.
static void markCoroutineAsDone (IRBuilder<> &Builder, const coro::Shape &Shape, Value *FramePtr)
static void replaceUnwindCoroEnd (AnyCoroEndInst *End, const coro::Shape &Shape, Value *FramePtr, bool InResume, CallGraph *CG)
Replace an unwind call to llvm.coro.end.
static void replaceCoroEnd (AnyCoroEndInst *End, const coro::Shape &Shape, Value *FramePtr, bool InResume, CallGraph *CG)
static void createResumeEntryBlock (Function &F, coro::Shape &Shape)
static FunctionType * getFunctionTypeFromAsyncSuspend (AnyCoroSuspendInst *Suspend)
static Function * createCloneDeclaration (Function &OrigF, coro::Shape &Shape, const Twine &Suffix, Module::iterator InsertBefore, AnyCoroSuspendInst *ActiveSuspend)
static void replaceSwiftErrorOps (Function &F, coro::Shape &Shape, ValueToValueMapTy *VMap)
static void addFramePointerAttrs (AttributeList &Attrs, LLVMContext &Context, unsigned ParamIndex, uint64_t Size, Align Alignment)
static void addAsyncContextAttrs (AttributeList &Attrs, LLVMContext &Context, unsigned ParamIndex)
static void addSwiftSelfAttrs (AttributeList &Attrs, LLVMContext &Context, unsigned ParamIndex)
static Function * createClone (Function &F, const Twine &Suffix, coro::Shape &Shape, CoroCloner::Kind FKind)
static void removeCoroEnds (const coro::Shape &Shape, CallGraph *CG)
Remove calls to llvm.coro.end in the original function.
static void updateAsyncFuncPointerContextSize (coro::Shape &Shape)
static void replaceFrameSizeAndAlignment (coro::Shape &Shape)
static void setCoroInfo (Function &F, coro::Shape &Shape, ArrayRef< Function * > Fns)
static void updateCoroFrame (coro::Shape &Shape, Function *ResumeFn, Function *DestroyFn, Function *CleanupFn)
static void postSplitCleanup (Function &F)
static void scanPHIsAndUpdateValueMap (Instruction *Prev, BasicBlock *NewBlock, DenseMap< Value *, Value * > &ResolvedValues)
static bool simplifyTerminatorLeadingToRet (Instruction *InitialInst)
static bool shouldBeMustTail (const CallInst &CI, const Function &F)
static void addMustTailToCoroResumes (Function &F)
static void handleNoSuspendCoroutine (coro::Shape &Shape)
static bool hasCallsInBlockBetween (Instruction *From, Instruction *To)
static bool hasCallsInBlocksBetween (BasicBlock *SaveBB, BasicBlock *ResDesBB)
static bool hasCallsBetween (Instruction *Save, Instruction *ResumeOrDestroy)
static bool simplifySuspendPoint (CoroSuspendInst *Suspend, CoroBeginInst *CoroBegin)
static void simplifySuspendPoints (coro::Shape &Shape)
static void splitSwitchCoroutine (Function &F, coro::Shape &Shape, SmallVectorImpl< Function * > &Clones)
static void replaceAsyncResumeFunction (CoroSuspendAsyncInst *Suspend, Value *Continuation)
Coerce the arguments in p FnArgs according to p FnTy in p static CallArgs void coerceArguments (IRBuilder<> &Builder, FunctionType *FnTy, ArrayRef< Value * > FnArgs, SmallVectorImpl< Value * > &CallArgs)
static void splitAsyncCoroutine (Function &F, coro::Shape &Shape, SmallVectorImpl< Function * > &Clones)
static void splitRetconCoroutine (Function &F, coro::Shape &Shape, SmallVectorImpl< Function * > &Clones)
static coro::Shape splitCoroutine (Function &F, SmallVectorImpl< Function * > &Clones, bool OptimizeFrame)
static void updateCallGraphAfterCoroutineSplit (Function &F, const coro::Shape &Shape, const SmallVectorImpl< Function * > &Clones, CallGraph &CG, CallGraphSCC &SCC)
static void updateCallGraphAfterCoroutineSplit (LazyCallGraph::Node &N, const coro::Shape &Shape, const SmallVectorImpl< Function * > &Clones, LazyCallGraph::SCC &C, LazyCallGraph &CG, CGSCCAnalysisManager &AM, CGSCCUpdateResult &UR, FunctionAnalysisManager &FAM)
static void prepareForSplit (Function &F, CallGraph &CG, bool MarkForAsyncRestart=false)
static void createDevirtTriggerFunc (CallGraph &CG, CallGraphSCC &SCC)
Replace a call to llvm coro prepare static retcon void replacePrepare (CallInst *Prepare, LazyCallGraph &CG, LazyCallGraph::SCC &C)
Replace a call to llvm coro prepare static retcon void replacePrepare (CallInst *Prepare, CallGraph &CG)
static bool replaceAllPrepares (Function *PrepareFn, LazyCallGraph &CG, LazyCallGraph::SCC &C)
Remove calls to llvm coro prepare a barrier meant to prevent IPO from operating on calls to a retcon coroutine before it s been split This is only safe to do after we ve split all retcon coroutines in the module We can do that this in this pass because this pass does promise to split all retcon coroutines (as opposed to switch coroutines, which are lowered in multiple stages). static bool replaceAllPrepares(Function *PrepareFn
for (Use &P :llvm::make_early_inc_range(PrepareFn->uses()))
static bool declaresCoroSplitIntrinsics (const Module &M)
static void addPrepareFunction (const Module &M, SmallVectorImpl< Function * > &Fns, StringRef Name)
INITIALIZE_PASS_BEGIN (CoroSplitLegacy, "coro-split", "Split coroutine into a set of functions driving its state machine", false, false) INITIALIZE_PASS_END(CoroSplitLegacy
Variables
Remove calls to llvm coro prepare retcon
Remove calls to llvm coro prepare a barrier meant to prevent IPO from operating on calls to a retcon coroutine before it s been split This is only safe to do after we ve split all retcon coroutines in the module We can do that this in this pass because this pass does promise to split all retcon CallGraph & CG
return Changed
coro split
coro Split coroutine into a set of functions driving its state machine
coro Split coroutine into a set of functions driving its state false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "coro-split"
Definition at line 78 of file CoroSplit.cpp.
Function Documentation
addAsyncContextAttrs()
static void addAsyncContextAttrs (AttributeList & Attrs, LLVMContext & Context, unsigned ParamIndex) static
Definition at line 849 of file CoroSplit.cpp.
addFramePointerAttrs()
static void addFramePointerAttrs (AttributeList & Attrs, LLVMContext & Context, unsigned ParamIndex, uint64_t Size, Align Alignment) static
Definition at line 838 of file CoroSplit.cpp.
References Size.
addMustTailToCoroResumes()
static void addMustTailToCoroResumes (Function & F) static
Definition at line 1352 of file CoroSplit.cpp.
References F, I, instructions, llvm::removeUnreachableBlocks(), shouldBeMustTail(), simplifyTerminatorLeadingToRet(), and llvm::CallInst::TCK_MustTail.
Referenced by splitSwitchCoroutine().
addPrepareFunction()
static void addPrepareFunction (const Module & M, SmallVectorImpl< Function * > & Fns, StringRef Name) static
Definition at line 2170 of file CoroSplit.cpp.
References Name.
Referenced by llvm::CoroSplitPass::run().
addSwiftSelfAttrs()
static void addSwiftSelfAttrs (AttributeList & Attrs, LLVMContext & Context, unsigned ParamIndex) static
Definition at line 856 of file CoroSplit.cpp.
coerceArguments()
Coerce the arguments in p FnArgs according to p FnTy in p static CallArgs void coerceArguments (IRBuilder<> & Builder, FunctionType * FnTy, ArrayRef< Value * > FnArgs, SmallVectorImpl< Value * > & CallArgs) static
Definition at line 1608 of file CoroSplit.cpp.
References assert(), and getType().
Referenced by llvm::coro::createMustTailCall().
coroutines()
Remove calls to llvm coro prepare a barrier meant to prevent IPO from operating on calls to a retcon coroutine before it s been split This is only safe to do after we ve split all retcon coroutines in the module We can do that this in this pass because this pass does promise to split all retcon coroutines (as opposed to switch coroutines, which are lowered in multiple stages)
createClone()
static Function * createClone (Function & F, const Twine & Suffix, coro::Shape & Shape, CoroCloner::Kind FKind) static
Definition at line 1059 of file CoroSplit.cpp.
References F.
Referenced by splitSwitchCoroutine().
createCloneDeclaration()
static Function * createCloneDeclaration (Function & OrigF, coro::Shape & Shape, const Twine & Suffix, Module::iterator InsertBefore, AnyCoroSuspendInst * ActiveSuspend) static
Definition at line 494 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::Function::addParamAttr(), llvm::Function::Create(), getFunctionTypeFromAsyncSuspend(), llvm::Value::getName(), llvm::GlobalValue::getParent(), and llvm::coro::Shape::getResumeFunctionType().
Referenced by splitAsyncCoroutine(), and splitRetconCoroutine().
createDevirtTriggerFunc()
static void createDevirtTriggerFunc (CallGraph & CG, CallGraphSCC & SCC) static
Definition at line 2021 of file CoroSplit.cpp.
References C, CG, CORO_DEVIRT_TRIGGER_FN, llvm::Function::Create(), llvm::ReturnInst::Create(), and llvm::BasicBlock::Create().
createResumeEntryBlock()
static void createResumeEntryBlock (Function & F, coro::Shape & Shape) static
Definition at line 359 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), Builder, C, llvm::coro::Shape::CoroSuspends, llvm::BasicBlock::Create(), llvm::PHINode::Create(), F, FramePtr, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::ConstantTokenNone::get(), llvm::coro::Shape::getIndex(), llvm::coro::Shape::getIndexType(), llvm::coro::Shape::getSwitchIndexField(), markCoroutineAsDone(), llvm::coro::Shape::SwitchLoweringStorage::ResumeEntryBlock, llvm::coro::Shape::SwitchLoweringStorage::ResumeSwitch, and llvm::coro::Shape::SwitchLowering.
Referenced by splitSwitchCoroutine().
declaresCoroSplitIntrinsics()
static bool declaresCoroSplitIntrinsics (const Module & M) static
Definition at line 2164 of file CoroSplit.cpp.
References llvm::coro::declaresIntrinsics().
Referenced by llvm::CoroSplitPass::run().
for()
for (Use &P :llvm::make_early_inc_rangePrepareFn->uses())
Definition at line 2154 of file CoroSplit.cpp.
References CG, Changed, P, and replacePrepare().
getFunctionTypeFromAsyncSuspend()
static FunctionType * getFunctionTypeFromAsyncSuspend (AnyCoroSuspendInst * Suspend) static
Definition at line 486 of file CoroSplit.cpp.
References llvm::Function::getContext(), llvm::BasicBlock::getParent(), and llvm::Instruction::getParent().
Referenced by createCloneDeclaration().
handleNoSuspendCoroutine()
static void handleNoSuspendCoroutine (coro::Shape & Shape) static
Definition at line 1375 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, Builder, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::FrameAlign, llvm::coro::Shape::FrameTy, llvm::UndefValue::get(), and llvm::coro::replaceCoroFree().
Referenced by splitCoroutine().
hasCallsBetween()
static bool hasCallsBetween (Instruction * Save, Instruction * ResumeOrDestroy) static
Definition at line 1451 of file CoroSplit.cpp.
References llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::Instruction::getParent(), hasCallsInBlockBetween(), and hasCallsInBlocksBetween().
Referenced by simplifySuspendPoint().
hasCallsInBlockBetween()
static bool hasCallsInBlockBetween (Instruction * From, Instruction * To) static
Definition at line 1410 of file CoroSplit.cpp.
References From, llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), and I.
Referenced by hasCallsBetween(), and hasCallsInBlocksBetween().
hasCallsInBlocksBetween()
static bool hasCallsInBlocksBetween (BasicBlock * SaveBB, BasicBlock * ResDesBB) static
Definition at line 1422 of file CoroSplit.cpp.
References llvm::BB, hasCallsInBlockBetween(), and llvm::predecessors().
Referenced by hasCallsBetween().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (CoroSplitLegacy , "coro-split" , "Split coroutine into a set of functions driving its state machine" , false , false)
markCoroutineAsDone()
static void markCoroutineAsDone (IRBuilder<> & Builder, const coro::Shape & Shape, Value * FramePtr) static
Definition at line 292 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), FramePtr, llvm::coro::Shape::FrameTy, llvm::ConstantPointerNull::get(), llvm::StructType::getTypeAtIndex(), and llvm::coro::Shape::SwitchFieldIndex::Resume.
Referenced by createResumeEntryBlock(), and replaceUnwindCoroEnd().
maybeFreeRetconStorage()
static void maybeFreeRetconStorage (IRBuilder<> & Builder, const coro::Shape & Shape, Value * FramePtr, CallGraph * CG) static
Definition at line 170 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), CG, llvm::coro::Shape::emitDealloc(), FramePtr, llvm::coro::Shape::RetconLoweringStorage::IsFrameInlineInStorage, and llvm::coro::Shape::RetconLowering.
Referenced by replaceFallthroughCoroEnd(), and replaceUnwindCoroEnd().
postSplitCleanup()
static void postSplitCleanup (Function & F) static
Definition at line 1174 of file CoroSplit.cpp.
References llvm::errs(), F, llvm::removeUnreachableBlocks(), llvm::report_fatal_error(), and llvm::verifyFunction().
Referenced by splitSwitchCoroutine(), updateCallGraphAfterCoroutineSplit(), and updateCallGraphAfterCoroutineSplit().
prepareForSplit()
static void prepareForSplit (Function & F, CallGraph & CG, bool MarkForAsyncRestart = false) static
Definition at line 1984 of file CoroSplit.cpp.
References assert(), ASYNC_RESTART_AFTER_SPLIT, CG, CORO_DEVIRT_TRIGGER_FN, CORO_PRESPLIT_ATTR, llvm::CallInst::Create(), F, llvm::ConstantPointerNull::get(), llvm::IndirectCall, PREPARED_FOR_SPLIT, and llvm::CoroSubFnInst::RestartTrigger.
removeCoroEnds()
static void removeCoroEnds (const coro::Shape & Shape, CallGraph * CG) static
Remove calls to llvm.coro.end in the original function.
Definition at line 1067 of file CoroSplit.cpp.
References CG, llvm::coro::Shape::CoroEnds, llvm::coro::Shape::FramePtr, and replaceCoroEnd().
Referenced by updateCallGraphAfterCoroutineSplit().
replaceAllPrepares()
static bool replaceAllPrepares (Function * PrepareFn, LazyCallGraph & CG, LazyCallGraph::SCC & C) static
Definition at line 2133 of file CoroSplit.cpp.
References C, CG, Changed, llvm::make_early_inc_range(), P, and replacePrepare().
Referenced by llvm::CoroSplitPass::run().
replaceAsyncResumeFunction()
static void replaceAsyncResumeFunction (CoroSuspendAsyncInst * Suspend, Value * Continuation) static
Definition at line 1593 of file CoroSplit.cpp.
References Builder, llvm::UndefValue::get(), llvm::Function::getContext(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::CoroSuspendAsyncInst::getResumeFunction(), llvm::CoroSuspendAsyncInst::ResumeFunctionArg, and llvm::User::setOperand().
Referenced by splitAsyncCoroutine().
replaceCoroEnd()
static void replaceCoroEnd (AnyCoroEndInst * End, const coro::Shape & Shape, Value * FramePtr, bool InResume, CallGraph * CG) static
Definition at line 344 of file CoroSplit.cpp.
References CG, FramePtr, llvm::ConstantInt::getFalse(), llvm::ConstantInt::getTrue(), replaceFallthroughCoroEnd(), and replaceUnwindCoroEnd().
Referenced by removeCoroEnds().
replaceCoroEndAsync()
static bool replaceCoroEndAsync (AnyCoroEndInst * End) static
Replace an llvm.coro.end.async.
Will inline the must tail call function call if there is one.
Returns
true if cleanup of the coro.end block is needed, false otherwise.
Definition at line 184 of file CoroSplit.cpp.
References assert(), llvm::BB, Builder, llvm::ilist_node_impl< OptionsT >::getIterator(), and llvm::InlineFunction().
Referenced by replaceFallthroughCoroEnd().
replaceFallthroughCoroEnd()
static void replaceFallthroughCoroEnd (AnyCoroEndInst * End, const coro::Shape & Shape, Value * FramePtr, bool InResume, CallGraph * CG) static
Replace a non-unwind call to llvm.coro.end.
Definition at line 227 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::BB, Builder, CG, FramePtr, llvm::ConstantPointerNull::get(), llvm::UndefValue::get(), llvm::coro::Shape::getResumeFunctionType(), llvm::FunctionType::getReturnType(), maybeFreeRetconStorage(), replaceCoroEndAsync(), and RetTy.
Referenced by replaceCoroEnd().
replaceFrameSizeAndAlignment()
static void replaceFrameSizeAndAlignment (coro::Shape & Shape) static
Definition at line 1088 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::coro::Shape::CoroAligns, llvm::coro::Shape::CoroSizes, llvm::CS, DL, llvm::coro::Shape::FrameAlign, llvm::coro::Shape::FrameTy, llvm::ConstantInt::get(), Size, updateAsyncFuncPointerContextSize(), and llvm::Align::value().
Referenced by splitCoroutine().
replacePrepare() [1/2]
Replace a call to llvm coro prepare static retcon void replacePrepare (CallInst * Prepare, CallGraph & CG) static
Definition at line 2080 of file CoroSplit.cpp.
References CG, llvm::Use::getUser(), and llvm::make_early_inc_range().
replacePrepare() [2/2]
Replace a call to llvm coro prepare static retcon void replacePrepare (CallInst * Prepare, LazyCallGraph & CG, LazyCallGraph::SCC & C) static
Definition at line 2044 of file CoroSplit.cpp.
References llvm::make_early_inc_range().
Referenced by for(), and replaceAllPrepares().
replaceSwiftErrorOps()
static void replaceSwiftErrorOps (Function & F, coro::Shape & Shape, ValueToValueMapTy * VMap) static
Definition at line 614 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, Arg, assert(), Builder, llvm::coro::Shape::CoroSuspends, F, llvm::Value::getType(), and llvm::coro::Shape::SwiftErrorOps.
Referenced by splitCoroutine().
replaceUnwindCoroEnd()
static void replaceUnwindCoroEnd (AnyCoroEndInst * End, const coro::Shape & Shape, Value * FramePtr, bool InResume, CallGraph * CG) static
Replace an unwind call to llvm.coro.end.
Definition at line 306 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, Builder, CG, FramePtr, markCoroutineAsDone(), maybeFreeRetconStorage(), and llvm::LLVMContext::OB_funclet.
Referenced by replaceCoroEnd().
scanPHIsAndUpdateValueMap()
static void scanPHIsAndUpdateValueMap (Instruction * Prev, BasicBlock * NewBlock, DenseMap< Value *, Value * > & ResolvedValues) static
Definition at line 1189 of file CoroSplit.cpp.
References llvm::Instruction::getParent().
Referenced by simplifyTerminatorLeadingToRet().
setCoroInfo()
static void setCoroInfo (Function & F, coro::Shape & Shape, ArrayRef< Function * > Fns) static
Definition at line 1125 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), C, F, llvm::ConstantArray::get(), llvm::GlobalValue::getParent(), llvm::ConstantExpr::getPointerCast(), llvm::coro::Shape::getSwitchCoroId(), llvm::GlobalValue::getType(), and llvm::CoroIdInst::setInfo().
Referenced by splitSwitchCoroutine().
shouldBeMustTail()
static bool shouldBeMustTail (const CallInst & CI, const Function & F) static
Definition at line 1317 of file CoroSplit.cpp.
References F, llvm::CallBase::getAttributes(), llvm::CallBase::getCallingConv(), llvm::CallBase::getFunctionType(), and llvm::CallBase::isInlineAsm().
Referenced by addMustTailToCoroResumes().
simplifySuspendPoint()
static bool simplifySuspendPoint (CoroSuspendInst * Suspend, CoroBeginInst * CoroBegin) static
Definition at line 1476 of file CoroSplit.cpp.
References Callee, llvm::BranchInst::Create(), llvm::Instruction::eraseFromParent(), llvm::CallBase::getCalledOperand(), llvm::CoroSuspendInst::getCoroSave(), llvm::Instruction::getParent(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), llvm::BasicBlock::getSinglePredecessor(), hasCallsBetween(), I, llvm::Value::replaceAllUsesWith(), and llvm::Value::stripPointerCasts().
Referenced by simplifySuspendPoints().
simplifySuspendPoints()
static void simplifySuspendPoints (coro::Shape & Shape) static
Definition at line 1536 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, I, N, SI, simplifySuspendPoint(), and std::swap().
Referenced by splitCoroutine().
simplifyTerminatorLeadingToRet()
static bool simplifyTerminatorLeadingToRet (Instruction * InitialInst) static
Definition at line 1206 of file CoroSplit.cpp.
References assert(), llvm::BB, Cond, llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldTerminator(), DL, llvm::BasicBlock::getFirstNonPHIOrDbgOrLifetime(), I, llvm::isInstructionTriviallyDead(), llvm::ReplaceInstWithInst(), scanPHIsAndUpdateValueMap(), and SI.
Referenced by addMustTailToCoroResumes().
splitAsyncCoroutine()
static void splitAsyncCoroutine (Function & F, coro::Shape & Shape, SmallVectorImpl< Function * > & Clones) static
Definition at line 1639 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), llvm::coro::Shape::AsyncLowering, Builder, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, llvm::BasicBlock::Create(), createCloneDeclaration(), llvm::coro::createMustTailCall(), F, llvm::coro::Shape::AsyncLoweringStorage::FrameOffset, FramePtr, llvm::coro::Shape::FramePtr, llvm::CoroBeginInst::getId(), Idx, llvm::InlineFunction(), llvm::CoroSuspendAsyncInst::MustTailCallFuncArg, llvm::Value::replaceAllUsesWith(), and replaceAsyncResumeFunction().
Referenced by splitCoroutine().
splitCoroutine()
static coro::Shape splitCoroutine (Function & F, SmallVectorImpl< Function * > & Clones, bool OptimizeFrame) static
Definition at line 1880 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, F, handleNoSuspendCoroutine(), llvm::removeUnreachableBlocks(), replaceFrameSizeAndAlignment(), replaceSwiftErrorOps(), simplifySuspendPoints(), splitAsyncCoroutine(), splitRetconCoroutine(), and splitSwitchCoroutine().
Referenced by llvm::CoroSplitPass::run().
splitRetconCoroutine()
static void splitRetconCoroutine (Function & F, coro::Shape & Shape, SmallVectorImpl< Function * > & Clones) static
Definition at line 1736 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), Builder, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroSuspends, llvm::BasicBlock::Create(), createCloneDeclaration(), DL, E, llvm::coro::Shape::emitAlloc(), F, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::UndefValue::get(), llvm::MachineFunction::getDataLayout(), llvm::CoroBeginInst::getId(), llvm::MachineBasicBlock::getParent(), llvm::coro::Shape::getRetconResultTypes(), llvm::Value::getType(), I, llvm::coro::Shape::RetconLoweringStorage::IsFrameInlineInStorage, llvm::Value::replaceAllUsesWith(), llvm::coro::Shape::RetconLowering, RetTy, llvm::coro::Shape::RetconLoweringStorage::ReturnBlock, and Size.
Referenced by splitCoroutine().
splitSwitchCoroutine()
static void splitSwitchCoroutine (Function & F, coro::Shape & Shape, SmallVectorImpl< Function * > & Clones) static
Definition at line 1561 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, addMustTailToCoroResumes(), assert(), createClone(), createResumeEntryBlock(), F, postSplitCleanup(), setCoroInfo(), and updateCoroFrame().
Referenced by splitCoroutine().
updateAsyncFuncPointerContextSize()
static void updateAsyncFuncPointerContextSize (coro::Shape & Shape) static
Definition at line 1073 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), llvm::coro::Shape::AsyncLoweringStorage::AsyncFuncPointer, llvm::coro::Shape::AsyncLowering, llvm::coro::Shape::AsyncLoweringStorage::ContextSize, llvm::ConstantStruct::get(), llvm::ConstantInt::get(), llvm::GlobalVariable::getInitializer(), and llvm::GlobalVariable::setInitializer().
Referenced by replaceFrameSizeAndAlignment().
updateCallGraphAfterCoroutineSplit() [1/2]
static void updateCallGraphAfterCoroutineSplit (Function & F, const coro::Shape & Shape, const SmallVectorImpl< Function * > & Clones, CallGraph & CG, CallGraphSCC & SCC) static
Definition at line 1924 of file CoroSplit.cpp.
References CG, llvm::coro::Shape::CoroBegin, F, postSplitCleanup(), removeCoroEnds(), and llvm::coro::updateCallGraph().
Referenced by llvm::CoroSplitPass::run().
updateCallGraphAfterCoroutineSplit() [2/2]
static void updateCallGraphAfterCoroutineSplit (LazyCallGraph::Node & N, const coro::Shape & Shape, const SmallVectorImpl< Function * > & Clones, LazyCallGraph::SCC & C, LazyCallGraph & CG, CGSCCAnalysisManager & AM, CGSCCUpdateResult & UR, FunctionAnalysisManager & FAM) static
Definition at line 1937 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, C, CG, llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroEnds, FAM, llvm::ConstantInt::getFalse(), N, postSplitCleanup(), llvm::updateCGAndAnalysisManagerForCGSCCPass(), and llvm::updateCGAndAnalysisManagerForFunctionPass().
updateCoroFrame()
static void updateCoroFrame (coro::Shape & Shape, Function * ResumeFn, Function * DestroyFn, Function * CleanupFn) static
Definition at line 1149 of file CoroSplit.cpp.
References llvm::coro::Shape::ABI, assert(), Builder, llvm::coro::Shape::SwitchFieldIndex::Destroy, llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::coro::Shape::getSwitchCoroId(), and llvm::coro::Shape::SwitchFieldIndex::Resume.
Referenced by splitSwitchCoroutine().
Variable Documentation
CG
Remove calls to llvm coro prepare a barrier meant to prevent IPO from operating on calls to a retcon coroutine before it s been split This is only safe to do after we ve split all retcon coroutines in the module We can do that this in this pass because this pass does promise to split all retcon CallGraph& CG
Initial value:
{
  bool Changed = false
Definition at line 2152 of file CoroSplit.cpp.
Referenced by addCallToCallGraph(), llvm::GlobalsAAResult::analyzeModule(), buildCGN(), llvm::CallGraphDOTInfo::CallGraphDOTInfo(), llvm::CallGraphNode::CallGraphNode(), llvm::CallGraphSCC::CallGraphSCC(), createDevirtTriggerFunc(), deduceFunctionAttributeInRPO(), llvm::LegacyInlinerBase::doFinalization(), llvm::LegacyInlinerBase::doInitialization(), llvm::AMDGPUResourceUsageAnalysis::doInitialization(), llvm::coro::Shape::emitAlloc(), llvm::coro::Shape::emitDealloc(), expandBounds(), for(), llvm::CallGraphSCC::getCallGraph(), llvm::CallGraphDOTInfo::getCallGraph(), llvm::CallGraphUpdater::initialize(), llvm::LegacyInlinerBase::inlineCalls(), inlineCallsImpl(), llvm::InternalizePass::internalizeModule(), llvm::internalizeModule(), maybeFreeRetconStorage(), llvm::GraphTraits< CallGraph * >::nodes_begin(), llvm::GraphTraits< const CallGraph * >::nodes_begin(), llvm::GraphTraits< CallGraph * >::nodes_end(), llvm::GraphTraits< const CallGraph * >::nodes_end(), prepareForSplit(), llvm::RuntimePointerChecking::print(), llvm::SyntheticCountsUtils< CallGraphType >::propagate(), removeCoroEnds(), llvm::LegacyInlinerBase::removeDeadFunctions(), replaceAllPrepares(), replaceCoroEnd(), replaceFallthroughCoroEnd(), replacePrepare(), replaceUnwindCoroEnd(), llvm::FunctionAnalysisManagerCGSCCProxy::run(), llvm::RequireAnalysisPass< AnalysisT, LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & >::run(), llvm::CGSCCToFunctionPassAdaptor::run(), llvm::CoroSplitPass::run(), llvm::ArgumentPromotionPass::run(), llvm::AttributorCGSCCPass::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::InlinerPass::run(), llvm::OpenMPOptCGSCCPass::run(), llvm::DevirtSCCRepeatedPass::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor::run(), llvm::ReversePostOrderFunctionAttrsPass::run(), llvm::SampleProfileLoaderPass::run(), llvm::SyntheticCountsPropagation::run(), llvm::coro::updateCallGraph(), updateCallGraphAfterCoroutineSplit(), updateCallGraphAfterCoroutineSplit(), and UpdateCallGraphAfterInlining().
Changed
return Changed
Definition at line 2161 of file CoroSplit.cpp.
Referenced by addArgumentAttrs(), addArgumentAttrsFromCallsites(), addArgumentReturnedAttrs(), addDiscriminators(), addNoAliasAttrs(), llvm::cflaa::CFLGraph::addNode(), addNonNullAttrs(), addNoRecurseAttrs(), addNoReturnAttrs(), addNoSyncAttr(), addReadAttrs(), addSegmentsWithValNo(), addWillReturn(), AlignBlocks(), bitTrackingDCE(), llvm::RISCVInstrInfo::buildOutlinedFrame(), AAMemoryLocationImpl::categorizeAccessedLocations(), AAMemoryLocationImpl::categorizeArgumentPointerLocations(), AAMemoryLocationImpl::categorizePtrValue(), CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), llvm::Combiner::combineMachineInstrs(), llvm::SampleProfileLoaderBaseImpl< BT >::computeAndPropagateWeights(), llvm::SampleProfileLoaderBaseImpl< BT >::computeBlockWeights(), llvm::rdf::Liveness::computePhiInfo(), llvm::DIExpression::constantFold(), llvm::ConstantFoldTerminator(), constantFoldTerminators(), llvm::ListInit::convertInitializerTo(), convertToRelativeLookupTables(), deduceFunctionAttributeInRPO(), llvm::DeleteDeadPHIs(), deleteLoopIfDead(), llvm::DependenceInfo::depends(), deriveAttrsInPostOrder(), doCallSiteSplitting(), doDefKillClear(), llvm::FPPassManager::doFinalization(), llvm::legacy::FunctionPassManagerImpl::doFinalization(), llvm::FPPassManager::doInitialization(), llvm::legacy::FunctionPassManagerImpl::doInitialization(), eliminateAvailableExternally(), eliminateConstraints(), EliminateDuplicatePHINodesNaiveImpl(), EliminateDuplicatePHINodesSetBasedImpl(), eliminateLoadsAcrossLoops(), llvm::Value::eraseMetadata(), llvm::CallGraphUpdater::finalize(), llvm::finalizeBundles(), llvm::SSAUpdaterImpl< UpdaterT >::FindDominators(), findLIVLoopCondition(), findLIVLoopCondition(), llvm::SSAUpdaterImpl< UpdaterT >::FindPHIPlacement(), FixIrreducibleImpl(), Flatten(), llvm::PPCInstrInfo::FoldImmediate(), FoldTwoEntryPHINode(), for(), llvm::formDedicatedExitBlocks(), llvm::formLCSSA(), llvm::formLCSSAForInstructions(), formLCSSAOnAllLoops(), llvm::formLCSSARecursively(), ForwardSwitchConditionToPHI(), llvm::InstCombinerImpl::freezeDominatedUses(), llvm::Pass::getAnalysis(), llvm::Pass::getAnalysisID(), llvm::ScalarEvolution::getLosslessPtrToIntExpr(), llvm::ScalarEvolution::getSequentialMinMaxExpr(), llvm::DependenceInfo::getSplitIteration(), AAPointerInfoFloating::handleAccess(), hoistAndMergeSGPRInits(), llvm::hoistRegion(), AAMemoryLocationImpl::indicatePessimisticFixpoint(), inferAllPrototypeAttributes(), llvm::inferAttributesFromOthers(), inferAttrsFromFunctionBodies(), inferConvergent(), llvm::inferLibFuncAttributes(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), inlineCallsImpl(), inlineGetBaseAndOffset(), llvm::objcarc::BundledRetainClaimRVs::insertAfterInvokes(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::InternalizePass::internalizeModule(), isLoopDead(), iterativelySimplifyCFG(), llvm::Legalizer::legalizeMachineFunction(), LinearizeExprTree(), lowerAtomics(), llvm::LowerDbgDeclare(), lowerExpectIntrinsic(), lowerIntrinsics(), lowerLoadRelative(), llvm::makeFollowupLoopID(), llvm::Loop::makeLoopInvariant(), llvm::Loop::makeLoopInvariant(), makeReducible(), AAReturnedValuesImpl::manifest(), AAIsDeadArgument::manifest(), AAAlignImpl::manifest(), AAAlignCallSiteArgument::manifest(), AAValueSimplifyImpl::manifest(), AAValueSimplifyReturned::manifest(), AAValueSimplifyCallSiteArgument::manifest(), AAValueConstantRangeImpl::manifest(), AAAssumptionInfoFunction::manifest(), AAAssumptionInfoCallSite::manifest(), markAliveBlocks(), maybeRewriteToDrop(), llvm::BitTracker::RegisterCell::meet(), mergeBlocksIntoPredecessors(), mergeConditionalStores(), llvm::VPlanTransforms::mergeReplicateRegions(), llvm::SIInstrInfo::moveToVALU(), llvm::nameUnamedGlobals(), OptimizeAwayTrappingUsesOfLoads(), OptimizeAwayTrappingUsesOfValue(), optimizeDivRem(), OptimizeEmptyGlobalCXXDtors(), OptimizeFunctions(), OptimizeGlobalAliases(), optimizeGlobalsInModule(), OptimizeGlobalVars(), false::LibCallsShrinkWrap::perform(), processAbsIntrinsic(), processBinOp(), processCallSite(), processGlobal(), processInternalGlobal(), processPHI(), llvm::ARMBlockPlacement::processPostOrderLoops(), processSwitch(), promoteAllocasToVector(), promoteIndirectCalls(), promoteMemoryToRegister(), propagateLocalCopies(), llvm::SampleProfileLoaderBaseImpl< BT >::propagateThroughEdges(), llvm::SampleProfileLoaderBaseImpl< BT >::propagateWeights(), ReduceLoopStrength(), llvm::removeUnreachableBlocks(), removeUnusedBlocksFromParent(), replaceAllPrepares(), replaceDominatedUses(), rescheduleCanonically(), rescheduleLexographically(), llvm::BitsInit::resolveReferences(), llvm::ListInit::resolveReferences(), llvm::CondOpInit::resolveReferences(), llvm::VarDefInit::resolveReferences(), rewriteDebugUsers(), llvm::DAGTypeLegalizer::run(), llvm::rdf::CopyPropagation::run(), llvm::legacy::FunctionPassManagerImpl::run(), llvm::NewGVNPass::run(), llvm::ReplaceWithVeclib::run(), llvm::UnreachableBlockElimPass::run(), llvm::CoroElidePass::run(), llvm::PGOMemOPSizeOpt::run(), llvm::ObjCARCOptPass::run(), llvm::ObjCARCContractPass::run(), llvm::CorrelatedValuePropagationPass::run(), llvm::RedundantDbgInstEliminationPass::run(), llvm::GVNPass::run(), llvm::IRCEPass::run(), llvm::InferAddressSpacesPass::run(), llvm::InstSimplifyPass::run(), llvm::JumpThreadingPass::run(), llvm::LoopDataPrefetchPass::run(), llvm::LoopDistributePass::run(), llvm::LoopFusePass::run(), llvm::LoopLoadEliminationPass::run(), llvm::LoopUnrollPass::run(), llvm::RegToMemPass::run(), llvm::ScalarizerPass::run(), llvm::SpeculativeExecutionPass::run(), llvm::StructurizeCFGPass::run(), llvm::TailCallElimPass::run(), llvm::LoopSimplifyPass::run(), llvm::LowerInvokePass::run(), llvm::UnifyFunctionExitNodesPass::run(), llvm::LoadStoreVectorizerPass::run(), llvm::SLPVectorizerPass::run(), llvm::AMDGPUSimplifyLibCallsPass::run(), llvm::AMDGPUUseNativeCallsPass::run(), llvm::AMDGPUPromoteAllocaPass::run(), llvm::AMDGPUPromoteAllocaToVectorPass::run(), llvm::ControlHeightReductionPass::run(), llvm::DSEPass::run(), llvm::LoopSinkPass::run(), llvm::ArgumentPromotionPass::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::InlinerPass::run(), llvm::OpenMPOptCGSCCPass::run(), llvm::LoopRotatePass::run(), llvm::LoopFullUnrollPass::run(), llvm::LNICMPass::run(), llvm::LoopFlattenPass::run(), llvm::ModuleInlinerPass::run(), llvm::HotColdSplitting::run(), llvm::legacy::PassManagerImpl::run(), llvm::AlwaysInlinerPass::run(), llvm::DeadArgumentEliminationPass::run(), llvm::GlobalDCEPass::run(), llvm::PoisonCheckingPass::run(), llvm::CrossDSOCFIPass::run(), llvm::LowerTypeTestsPass::run(), llvm::OpenMPOptPass::run(), llvm::RewriteStatepointsForGC::run(), llvm::AMDGPUPrintfRuntimeBindingPass::run(), runAttributorOnFunctions(), runCVP(), llvm::runFunctionSpecialization(), runImpl(), llvm::AlignmentFromAssumptionsPass::runImpl(), llvm::NaryReassociatePass::runImpl(), runImpl(), runImpl(), runImpl(), llvm::LoopVectorizePass::runImpl(), llvm::SLPVectorizerPass::runImpl(), llvm::JumpThreadingPass::runImpl(), llvm::SpeculativeExecutionPass::runImpl(), runImpl(), llvm::RewriteSymbolPass::runImpl(), runNVVMIntrRange(), runOnBasicBlock(), runOnBasicBlock(), llvm::FPPassManager::runOnFunction(), llvm::LPPassManager::runOnFunction(), llvm::RGPassManager::runOnFunction(), llvm::UnifyFunctionExitNodesLegacyPass::runOnFunction(), runOnFunction(), llvm::MIRProfileLoader::runOnFunction(), llvm::LoadStoreOpt::runOnMachineFunction(), llvm::Localizer::runOnMachineFunction(), llvm::ARMBlockPlacement::runOnMachineFunction(), llvm::FPPassManager::runOnModule(), llvm::AMDGPUPerfHintAnalysis::runOnSCC(), runPartiallyInlineLibCalls(), llvm::SelectionDAG::salvageDebugInfo(), llvm::SetVector< T, Vector, Set >::set_union(), llvm::set_union(), setArgsNoUndef(), simplifyAndDCEInstruction(), llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative(), simplifyFunctionCFG(), llvm::ScalarEvolution::SimplifyICmpOperands(), llvm::simplifyLoop(), simplifyLoopCFG(), simplifyLoopInst(), llvm::simplifyLoopIVs(), simplifyOneLoop(), sink(), SinkCommonCodeFromPredecessors(), sinkLoopInvariantInstructions(), llvm::sinkRegion(), llvm::sinkRegionForLoopNest(), llvm::InnerLoopVectorizer::sinkScalarOperands(), llvm::VPlanTransforms::sinkScalarOperands(), splitGlobals(), llvm::SplitIndirectBrCriticalEdges(), STATISTIC(), STATISTIC(), STATISTIC(), stripDeadDebugInfoImpl(), llvm::stripDebugifyMetadata(), llvm::stripDebugInfo(), llvm::StripDebugInfo(), llvm::stripNonLineTableDebugInfo(), tailMergeBlocksWithSimilarFunctionTerminators(), llvm::thinLTOPropagateFunctionAttrs(), llvm::SelectionDAG::transferDbgValues(), AAPointerInfoImpl::translateAndAddCalleeState(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), tryToVectorizeSequence(), unswitchAllTrivialConditions(), AAPointerInfoFloating::updateImpl(), AAPointerInfoCallSiteArgument::updateImpl(), AAReturnedValuesImpl::updateImpl(), AAIsDeadCallSiteReturned::updateImpl(), AAAlignCallSiteArgument::updateImpl(), AAHeapToStackFunction::updateImpl(), AAMemoryLocationFunction::updateImpl(), AAMemoryLocationCallSite::updateImpl(), AAAssumptionInfoFunction::updateImpl(), AAAssumptionInfoCallSite::updateImpl(), AAMemoryLocationImpl::updateStateAndAccessesMap(), updateSuccessor(), llvm::UpgradeModuleFlags(), UpgradeRetainReleaseMarker(), llvm::InstCombinerImpl::visitAdd(), llvm::SCEVRewriteVisitor< SC >::visitAddExpr(), llvm::SCEVRewriteVisitor< SC >::visitAddRecExpr(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitMul(), llvm::SCEVRewriteVisitor< SC >::visitMulExpr(), llvm::SCEVRewriteVisitor< SC >::visitSequentialUMinExpr(), llvm::SCEVRewriteVisitor< SC >::visitSMaxExpr(), llvm::SCEVRewriteVisitor< SC >::visitSMinExpr(), llvm::InstCombinerImpl::visitSub(), llvm::SCEVRewriteVisitor< SC >::visitUDivExpr(), llvm::SCEVRewriteVisitor< SC >::visitUMaxExpr(), llvm::SCEVRewriteVisitor< SC >::visitUMinExpr(), and llvm::SwitchInstProfUpdateWrapper::~SwitchInstProfUpdateWrapper().
false
coro Split coroutine into a set of functions driving its state false
Definition at line 2353 of file CoroSplit.cpp.
machine
coro Split coroutine into a set of functions driving its state machine
Definition at line 2353 of file CoroSplit.cpp.
retcon
Remove calls to llvm coro prepare retcon
Definition at line 2146 of file CoroSplit.cpp.
split
coro split
Definition at line 2352 of file CoroSplit.cpp.
Referenced by llvm::StringRef::split().