LLVM: lib/Support/CrashRecoveryContext.cpp File Reference
CrashRecoveryContext.cpp File Reference
#include "llvm/Support/CrashRecoveryContext.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Signals.h"
#include "llvm/Support/ThreadLocal.h"
#include "llvm/Support/thread.h"
#include <mutex>
#include <setjmp.h>
#include "llvm/Support/ExitCodes.h"
#include <signal.h>
Functions
static void installExceptionOrSignalHandlers ()
static void uninstallExceptionOrSignalHandlers ()
static void CrashRecoverySignalHandler (int Signal)
static void setThreadBackgroundPriority ()
static bool hasThreadBackgroundPriority ()
static void RunSafelyOnThread_Dispatch (void *UserData)
Variables
static ManagedStatic< std::mutex > gCrashRecoveryContextMutex
static bool gCrashRecoveryEnabled = false
static ManagedStatic< sys::ThreadLocal< const CrashRecoveryContext > > tlIsRecoveringFromCrash
static const int Signals []
static const unsigned NumSignals = array_lengthof(Signals)
static struct sigaction PrevActions [NumSignals]
Function Documentation
CrashRecoverySignalHandler()
static void CrashRecoverySignalHandler (int Signal) static
Definition at line 354 of file CrashRecoveryContext.cpp.
References llvm::CrashRecoveryContext::Disable().
Referenced by installExceptionOrSignalHandlers().
hasThreadBackgroundPriority()
static bool hasThreadBackgroundPriority () static
Definition at line 476 of file CrashRecoveryContext.cpp.
Referenced by llvm::CrashRecoveryContext::RunSafelyOnThread().
installExceptionOrSignalHandlers()
static void installExceptionOrSignalHandlers () static
Definition at line 395 of file CrashRecoveryContext.cpp.
References CrashRecoverySignalHandler(), NumSignals, PrevActions, and Signals.
Referenced by llvm::CrashRecoveryContext::Enable().
RunSafelyOnThread_Dispatch()
static void RunSafelyOnThread_Dispatch (void * UserData) static
Definition at line 493 of file CrashRecoveryContext.cpp.
References setThreadBackgroundPriority().
Referenced by llvm::CrashRecoveryContext::RunSafelyOnThread().
setThreadBackgroundPriority()
static void setThreadBackgroundPriority () static
Definition at line 470 of file CrashRecoveryContext.cpp.
Referenced by RunSafelyOnThread_Dispatch().
uninstallExceptionOrSignalHandlers()
static void uninstallExceptionOrSignalHandlers () static
Definition at line 407 of file CrashRecoveryContext.cpp.
References NumSignals, PrevActions, and Signals.
Referenced by llvm::CrashRecoveryContext::Disable().
Variable Documentation
gCrashRecoveryContextMutex
ManagedStatic<std::mutex> gCrashRecoveryContextMutex static
Definition at line 91 of file CrashRecoveryContext.cpp.
Referenced by llvm::CrashRecoveryContext::Disable(), and llvm::CrashRecoveryContext::Enable().
gCrashRecoveryEnabled
bool gCrashRecoveryEnabled = false static
Definition at line 92 of file CrashRecoveryContext.cpp.
Referenced by llvm::CrashRecoveryContext::Disable(), llvm::CrashRecoveryContext::Enable(), llvm::CrashRecoveryContext::GetCurrent(), and llvm::CrashRecoveryContext::RunSafely().
NumSignals
const unsigned NumSignals = array_lengthof(Signals) static
Definition at line 351 of file CrashRecoveryContext.cpp.
Referenced by installExceptionOrSignalHandlers(), and uninstallExceptionOrSignalHandlers().
PrevActions
struct sigaction PrevActions[NumSignals] static
Definition at line 352 of file CrashRecoveryContext.cpp.
Referenced by installExceptionOrSignalHandlers(), and uninstallExceptionOrSignalHandlers().
Signals
const int Signals[] static
Initial value:
=
    { SIGABRT, SIGBUS, SIGFPE, SIGILL, SIGSEGV, SIGTRAP }
Definition at line 349 of file CrashRecoveryContext.cpp.
Referenced by installExceptionOrSignalHandlers(), and uninstallExceptionOrSignalHandlers().
tlIsRecoveringFromCrash
ManagedStatic<sys::ThreadLocal<const CrashRecoveryContext> > tlIsRecoveringFromCrash static
Definition at line 95 of file CrashRecoveryContext.cpp.
Referenced by llvm::CrashRecoveryContext::isRecoveringFromCrash(), and llvm::CrashRecoveryContext::~CrashRecoveryContext().