LLVM: lib/CodeGen/MachineBasicBlock.cpp File Reference
MachineBasicBlock.cpp File Reference
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/LiveVariables.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SlotIndexes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/ModuleSlotTracker.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/Support/DataTypes.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "codegen"
Functions
static void unbundleSingleMI (MachineInstr *MI)
Prepare MI to be removed from its bundle.
Variables
static cl::opt< bool > PrintSlotIndexes ("print-slotindexes", cl::desc("When printing machine IR, annotate instructions and blocks with " "SlotIndexes when available"), cl::init(true), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "codegen"
Definition at line 41 of file MachineBasicBlock.cpp.
Function Documentation
unbundleSingleMI()
static void unbundleSingleMI (MachineInstr * MI) static
Prepare MI to be removed from its bundle.
This fixes bundle flags on MI's neighboring instructions so the bundle won't be broken by removing MI.
Definition at line 1286 of file MachineBasicBlock.cpp.
References MI.
Referenced by llvm::MachineBasicBlock::erase(), and llvm::MachineBasicBlock::remove_instr().
Variable Documentation
PrintSlotIndexes
cl::opt< bool > PrintSlotIndexes("print-slotindexes", cl::desc("When printing machine IR, annotate instructions and blocks with " "SlotIndexes when available"), cl::init(true), cl::Hidden) ("print-slotindexes" , cl::desc("When printing machine IR, annotate instructions and blocks with " "SlotIndexes when available") , cl::init(true) , cl::Hidden) static
Referenced by llvm::MachineBasicBlock::print().