LLVM: llvm::omp Namespace Reference
llvm::omp Namespace Reference
Classes
struct AssumptionClauseMappingInfo
Helper to describe assume clauses.
struct GV
Defines various target-specific GPU grid values that must be consistent between host RTL (plugin), device RTL, and clang.
struct OMPContext
The context for a source location is made up of active property traits, e.g., device={kind(host)}, and constructs traits which describe the nesting in OpenMP constructs at the location.
struct VariantMatchInfo
Variant match information describes the required traits and how they are scored (via the ScoresMap).
Typedefs
using Kernel = Function *
Summary of a kernel (=entry point for target offloading).
using KernelSet = SetVector<Kernel>
Set of kernels in the module.
Enumerations
enum class InternalControlVar { ICV_DATA_ENV }
IDs for all Internal Control Variables (ICVs).
enum class ICVInitValue { ICV_INIT_VALUE }
enum class RuntimeFunction { OMP_RTL }
IDs for all omp runtime library (RTL) functions.
enum class DefaultKind { OMP_DEFAULT_KIND }
IDs for the different default kinds.
enum class IdentFlag { OMP_IDENT_FLAG }
IDs for all omp runtime library ident_t flag encodings (see their defintion in openmp/runtime/src/kmp.h).
enum class OMPScheduleType {
StaticChunked = 33 , Static = 34 , DistributeChunked = 91 , Distribute = 92 ,
DynamicChunked = 35 , GuidedChunked = 36 , Runtime = 37 , Auto = 38 ,
StaticBalancedChunked = 45 , GuidedSimd = 46 , RuntimeSimd = 47 , ModifierMonotonic ,
ModifierNonmonotonic , ModifierMask = ModifierMonotonic | ModifierNonmonotonic
}
enum OMPTgtExecModeFlags : int8_t { OMP_TGT_EXEC_MODE_GENERIC = 1 << 0 , OMP_TGT_EXEC_MODE_SPMD = 1 << 1 , OMP_TGT_EXEC_MODE_GENERIC_SPMD }
enum class AddressSpace : unsigned {
Generic = 0 , Global = 1 , Shared = 3 , Constant = 4 ,
Local = 5
}
enum class OMPInteropType { Unknown , Target , TargetSync }
enum class TraitSet { OMP_TRAIT_SET }
OpenMP Context related IDs and helpers.
enum class TraitSelector { OMP_TRAIT_SELECTOR }
IDs for all OpenMP context selector trait (device={kind/isa...}/...).
enum class TraitProperty { OMP_TRAIT_PROPERTY , OMP_LAST_TRAIT_PROPERTY }
IDs for all OpenMP context trait properties (host/gpu/bsc/llvm/...)
Functions
std::string getAllAssumeClauseOptions ()
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
TraitSet getOpenMPContextTraitSetKind (StringRef Str)
Parse Str and return the trait set it matches or TraitSet::invalid.
TraitSet getOpenMPContextTraitSetForSelector (TraitSelector Selector)
Return the trait set for which Selector is a selector.
TraitSet getOpenMPContextTraitSetForProperty (TraitProperty Property)
Return the trait set for which Property is a property.
StringRef getOpenMPContextTraitSetName (TraitSet Kind)
Return a textual representation of the trait set Kind.
TraitSelector getOpenMPContextTraitSelectorKind (StringRef Str)
Parse Str and return the trait set it matches or TraitSelector::invalid.
TraitSelector getOpenMPContextTraitSelectorForProperty (TraitProperty Property)
Return the trait selector for which Property is a property.
StringRef getOpenMPContextTraitSelectorName (TraitSelector Kind)
Return a textual representation of the trait selector Kind.
TraitProperty getOpenMPContextTraitPropertyKind (TraitSet Set, TraitSelector Selector, StringRef Str)
Parse Str and return the trait property it matches in the set Set and selector Selector or TraitProperty::invalid.
TraitProperty getOpenMPContextTraitPropertyForSelector (TraitSelector Selector)
Return the trait property for a singleton selector Selector.
StringRef getOpenMPContextTraitPropertyName (TraitProperty Kind, StringRef RawString)
Return a textual representation of the trait property Kind, which might be the raw string we parsed (RawString) if we do not translate the property into a (distinct) enum.
StringRef getOpenMPContextTraitPropertyFullName (TraitProperty Kind)
Return a textual representation of the trait property Kind with selector and set name included.
std::string listOpenMPContextTraitSets ()
Return a string listing all trait sets.
std::string listOpenMPContextTraitSelectors (TraitSet Set)
Return a string listing all trait selectors for Set.
std::string listOpenMPContextTraitProperties (TraitSet Set, TraitSelector Selector)
Return a string listing all trait properties for Set and Selector.
bool isValidTraitSelectorForTraitSet (TraitSelector Selector, TraitSet Set, bool &AllowsTraitScore, bool &RequiresProperty)
}
bool isValidTraitPropertyForTraitSetAndSelector (TraitProperty Property, TraitSelector Selector, TraitSet Set)
Return true if Property can be nested in Selector and Set.
bool isVariantApplicableInContext (const VariantMatchInfo &VMI, const OMPContext &Ctx, bool DeviceSetOnly=false)
Return true if VMI is applicable in Ctx, that is, all traits required by VMI are available in the OpenMP context Ctx.
int getBestVariantMatchForContext (const SmallVectorImpl< VariantMatchInfo > &VMIs, const OMPContext &Ctx)
Return the index (into VMIs) of the variant with the highest score from the ones applicble in Ctx.
template<unsigned wavesize>
constexpr const GV & getAMDGPUGridValues ()
bool containsOpenMP (Module &M)
Helper to determine if M contains OpenMP.
bool isOpenMPDevice (Module &M)
Helper to determine if M is a OpenMP target offloading device module.
KernelSet getDeviceKernels (Module &M)
Get OpenMP device kernels in M.
Variables
static constexpr AssumptionClauseMappingInfo AssumptionClauseMappings []
All known assume clauses.
static constexpr GV AMDGPUGridValues64
For AMDGPU GPUs.
static constexpr GV AMDGPUGridValues32
static constexpr GV NVPTXGridValues
For Nvidia GPUs.
Typedef Documentation
Kernel
using llvm::omp::Kernel = Function *
Summary of a kernel (=entry point for target offloading).
Definition at line 21 of file OpenMPOpt.h.
KernelSet
using llvm::omp::KernelSet = SetVector<Kernel>
Set of kernels in the module.
Definition at line 24 of file OpenMPOpt.h.
Enumeration Type Documentation
AddressSpace
enum class llvm::omp::AddressSpace : unsigned strong
Enumerator
Generic
Global
Shared
Constant
Local
Definition at line 108 of file OMPConstants.h.
DefaultKind
enum class llvm::omp::DefaultKind strong
IDs for the different default kinds.
Enumerator
OMP_DEFAULT_KIND
Definition at line 55 of file OMPConstants.h.
ICVInitValue
enum class llvm::omp::ICVInitValue strong
Enumerator
ICV_INIT_VALUE
Definition at line 36 of file OMPConstants.h.
IdentFlag
enum class llvm::omp::IdentFlag strong
IDs for all omp runtime library ident_t flag encodings (see their defintion in openmp/runtime/src/kmp.h).
Enumerator
OMP_IDENT_FLAG
Definition at line 66 of file OMPConstants.h.
InternalControlVar
enum class llvm::omp::InternalControlVar strong
IDs for all Internal Control Variables (ICVs).
Enumerator
ICV_DATA_ENV
Definition at line 27 of file OMPConstants.h.
OMPInteropType
enum class llvm::omp::OMPInteropType strong
Note
This needs to be kept in sync with interop.h enum kmp_interop_type_t.:
Enumerator
Unknown
Target
TargetSync
Definition at line 117 of file OMPConstants.h.
OMPScheduleType
enum class llvm::omp::OMPScheduleType strong
Note
This needs to be kept in sync with kmp.h enum sched_type. Todo: Update kmp.h to include this file, and remove the enums in kmp.h To complete this, more enum values will need to be moved here.
Enumerator
StaticChunked
Static
DistributeChunked
Distribute
DynamicChunked
GuidedChunked
Runtime
Auto
StaticBalancedChunked
GuidedSimd
RuntimeSimd
ModifierMonotonic
ModifierNonmonotonic
ModifierMask
Definition at line 78 of file OMPConstants.h.
OMPTgtExecModeFlags
enum llvm::omp::OMPTgtExecModeFlags : int8_t
Enumerator
OMP_TGT_EXEC_MODE_GENERIC
OMP_TGT_EXEC_MODE_SPMD
OMP_TGT_EXEC_MODE_GENERIC_SPMD
Definition at line 100 of file OMPConstants.h.
RuntimeFunction
enum class llvm::omp::RuntimeFunction strong
IDs for all omp runtime library (RTL) functions.
Enumerator
OMP_RTL
Definition at line 46 of file OMPConstants.h.
TraitProperty
enum class llvm::omp::TraitProperty strong
IDs for all OpenMP context trait properties (host/gpu/bsc/llvm/...)
Enumerator
OMP_TRAIT_PROPERTY
OMP_LAST_TRAIT_PROPERTY
Definition at line 45 of file OMPContext.h.
TraitSelector
enum class llvm::omp::TraitSelector strong
IDs for all OpenMP context selector trait (device={kind/isa...}/...).
Enumerator
OMP_TRAIT_SELECTOR
Definition at line 39 of file OMPContext.h.
TraitSet
enum class llvm::omp::TraitSet strong
OpenMP Context related IDs and helpers.
{ IDs for all OpenMP context selector trait sets (construct/device/...).
Enumerator
OMP_TRAIT_SET
Definition at line 33 of file OMPContext.h.
Function Documentation
containsOpenMP()
bool llvm::omp::containsOpenMP (Module & M)
Helper to determine if M contains OpenMP.
Definition at line 5142 of file OpenMPOpt.cpp.
Referenced by llvm::OpenMPOptCGSCCPass::run(), and llvm::OpenMPOptPass::run().
getAllAssumeClauseOptions()
std::string llvm::omp::getAllAssumeClauseOptions () inline
Definition at line 44 of file OMPAssume.h.
References AssumptionClauseMappings.
getAMDGPUGridValues()
template<unsigned wavesize> constexpr const GV & llvm::omp::getAMDGPUGridValues () constexpr
Definition at line 102 of file OMPGridValues.h.
References AMDGPUGridValues32, and AMDGPUGridValues64.
getBestVariantMatchForContext()
int llvm::omp::getBestVariantMatchForContext (const SmallVectorImpl< VariantMatchInfo > & VMIs, const OMPContext & Ctx)
Return the index (into VMIs) of the variant with the highest score from the ones applicble in Ctx.
See llvm::isVariantApplicableInContext.
Definition at line 342 of file OMPContext.cpp.
References llvm::APInt::eq(), getVariantMatchScore(), isStrictSubset(), isVariantApplicableInContextHelper(), and llvm::APInt::ult().
getDeviceKernels()
KernelSet llvm::omp::getDeviceKernels (Module & M)
Get OpenMP device kernels in M.
Definition at line 5114 of file OpenMPOpt.cpp.
References llvm::MDString::getString(), and llvm::NamedMDNode::operands().
Referenced by llvm::OpenMPOptCGSCCPass::run(), and llvm::OpenMPOptPass::run().
getOpenMPContextTraitPropertyForSelector()
TraitProperty llvm::omp::getOpenMPContextTraitPropertyForSelector (TraitSelector Selector)
Return the trait property for a singleton selector Selector.
Definition at line 456 of file OMPContext.cpp.
References getOpenMPContextTraitSelectorName().
getOpenMPContextTraitPropertyFullName()
StringRef llvm::omp::getOpenMPContextTraitPropertyFullName (TraitProperty Kind)
Return a textual representation of the trait property Kind with selector and set name included.
Definition at line 478 of file OMPContext.cpp.
References llvm_unreachable.
Referenced by llvm::omp::OMPContext::OMPContext().
getOpenMPContextTraitPropertyKind()
TraitProperty llvm::omp::getOpenMPContextTraitPropertyKind (TraitSet Set, TraitSelector Selector, StringRef Str)
Parse Str and return the trait property it matches in the set Set and selector Selector or TraitProperty::invalid.
Definition at line 443 of file OMPContext.cpp.
getOpenMPContextTraitPropertyName()
StringRef llvm::omp::getOpenMPContextTraitPropertyName (TraitProperty Kind, StringRef RawString)
Return a textual representation of the trait property Kind, which might be the raw string we parsed (RawString) if we do not translate the property into a (distinct) enum.
Definition at line 466 of file OMPContext.cpp.
References llvm_unreachable.
Referenced by isVariantApplicableInContextHelper().
getOpenMPContextTraitSelectorForProperty()
TraitSelector llvm::omp::getOpenMPContextTraitSelectorForProperty (TraitProperty Property)
Return the trait selector for which Property is a property.
Definition at line 424 of file OMPContext.cpp.
References llvm_unreachable.
Referenced by getVariantMatchScore(), and isVariantApplicableInContextHelper().
getOpenMPContextTraitSelectorKind()
TraitSelector llvm::omp::getOpenMPContextTraitSelectorKind (StringRef Str)
Parse Str and return the trait set it matches or TraitSelector::invalid.
Definition at line 416 of file OMPContext.cpp.
getOpenMPContextTraitSelectorName()
StringRef llvm::omp::getOpenMPContextTraitSelectorName (TraitSelector Kind)
Return a textual representation of the trait selector Kind.
Definition at line 433 of file OMPContext.cpp.
References llvm_unreachable.
Referenced by getOpenMPContextTraitPropertyForSelector().
getOpenMPContextTraitSetForProperty()
TraitSet llvm::omp::getOpenMPContextTraitSetForProperty (TraitProperty Property)
Return the trait set for which Property is a property.
Definition at line 397 of file OMPContext.cpp.
References llvm_unreachable.
Referenced by llvm::omp::OMPContext::addTrait(), llvm::omp::VariantMatchInfo::addTrait(), getVariantMatchScore(), and isVariantApplicableInContextHelper().
getOpenMPContextTraitSetForSelector()
TraitSet llvm::omp::getOpenMPContextTraitSetForSelector (TraitSelector Selector)
Return the trait set for which Selector is a selector.
Definition at line 387 of file OMPContext.cpp.
References llvm_unreachable.
getOpenMPContextTraitSetKind()
TraitSet llvm::omp::getOpenMPContextTraitSetKind (StringRef Str)
Parse Str and return the trait set it matches or TraitSet::invalid.
Definition at line 379 of file OMPContext.cpp.
getOpenMPContextTraitSetName()
StringRef llvm::omp::getOpenMPContextTraitSetName (TraitSet Kind)
Return a textual representation of the trait set Kind.
Definition at line 406 of file OMPContext.cpp.
References llvm_unreachable.
isOpenMPDevice()
bool llvm::omp::isOpenMPDevice (Module & M)
Helper to determine if M is a OpenMP target offloading device module.
Definition at line 5150 of file OpenMPOpt.cpp.
Referenced by llvm::OpenMPOptCGSCCPass::run(), and llvm::OpenMPOptPass::run().
isValidTraitPropertyForTraitSetAndSelector()
bool llvm::omp::isValidTraitPropertyForTraitSetAndSelector (TraitProperty Property, TraitSelector Selector, TraitSet Set)
Return true if Property can be nested in Selector and Set.
Definition at line 503 of file OMPContext.cpp.
References llvm_unreachable.
isValidTraitSelectorForTraitSet()
bool llvm::omp::isValidTraitSelectorForTraitSet (TraitSelector Selector, TraitSet Set, bool & AllowsTraitScore, bool & RequiresProperty)
}
Return true if Selector can be nested in Set. Also sets AllowsTraitScore and RequiresProperty to true/false if the user can specify a score for properties in Selector and if the Selector requires at least one property.
Definition at line 488 of file OMPContext.cpp.
References llvm_unreachable.
isVariantApplicableInContext()
bool llvm::omp::isVariantApplicableInContext (const VariantMatchInfo & VMI, const OMPContext & Ctx, bool DeviceSetOnly = false)
Return true if VMI is applicable in Ctx, that is, all traits required by VMI are available in the OpenMP context Ctx.
If DeviceSetOnly is true, only the device selector set, if present, are checked. Note that we still honor extension traits provided by the user.
Definition at line 265 of file OMPContext.cpp.
References isVariantApplicableInContextHelper().
listOpenMPContextTraitProperties()
std::string llvm::omp::listOpenMPContextTraitProperties (TraitSet Set, TraitSelector Selector)
Return a string listing all trait properties for Set and Selector.
Definition at line 536 of file OMPContext.cpp.
listOpenMPContextTraitSelectors()
std::string llvm::omp::listOpenMPContextTraitSelectors (TraitSet Set)
Return a string listing all trait selectors for Set.
Definition at line 525 of file OMPContext.cpp.
listOpenMPContextTraitSets()
std::string llvm::omp::listOpenMPContextTraitSets ()
Return a string listing all trait sets.
Definition at line 515 of file OMPContext.cpp.
LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE()
llvm::omp::LLVM_ENABLE_BITMASK_ENUMS_IN_NAMESPACE ()
Variable Documentation
AMDGPUGridValues32
constexpr GV llvm::omp::AMDGPUGridValues32 static constexpr
Initial value:
= {
    256,
    32,
    128,
    896,
    1024,
    256,
}
Definition at line 93 of file OMPGridValues.h.
Referenced by getAMDGPUGridValues().
AMDGPUGridValues64
constexpr GV llvm::omp::AMDGPUGridValues64 static constexpr
Initial value:
= {
    256,
    64,
    128,
    896,
    1024,
    256,
}
For AMDGPU GPUs.
Definition at line 84 of file OMPGridValues.h.
Referenced by getAMDGPUGridValues().
AssumptionClauseMappings
constexpr AssumptionClauseMappingInfo llvm::omp::AssumptionClauseMappings[] static constexpr
Initial value:
= {
#define OMP_ASSUME_CLAUSE(Identifier, StartsWith, HasDirectiveList,            HasExpression)
                                                                               \
}
All known assume clauses.
Definition at line 37 of file OMPAssume.h.
Referenced by getAllAssumeClauseOptions().
NVPTXGridValues
constexpr GV llvm::omp::NVPTXGridValues static constexpr
Initial value:
= {
    256,
    32,
    1024,
    896,
    1024,
    128,
}
For Nvidia GPUs.
Definition at line 108 of file OMPGridValues.h.