LLVM: false Namespace Reference
false Namespace Reference
Classes
class Chain
A Chain is a sequence of instructions that are linked together by an accumulation operand.
struct GCPtrLivenessData
struct GepNode
struct in_set
struct IntervalSorter
class LibCallsShrinkWrap
struct PartiallyConstructedSafepointRecord
struct SingleLoopExtractor
SingleLoopExtractor - For bugpoint.
Typedefs
using DefiningValueMapTy = MapVector<Value *, Value *>
using PointerToBaseTy = MapVector<Value *, Value *>
using StatepointLiveSetTy = SetVector<Value *>
using RematerializedValueMapTy
Functions
raw_ostream & operator<< (raw_ostream &OS, const GepNode &GN)
template<typename NodeContainer >
void dump_node_container (raw_ostream &OS, const NodeContainer &S)
raw_ostream & operator<< (raw_ostream &OS, const NodeVect &S) LLVM_ATTRIBUTE_UNUSED
raw_ostream & operator<< (raw_ostream &OS, const NodeToUsesMap &M) LLVM_ATTRIBUTE_UNUSED
Typedef Documentation
DefiningValueMapTy
using false::DefiningValueMapTy = MapVector<Value *, Value *>
Definition at line 260 of file RewriteStatepointsForGC.cpp.
PointerToBaseTy
using false::PointerToBaseTy = MapVector<Value *, Value *>
Definition at line 261 of file RewriteStatepointsForGC.cpp.
RematerializedValueMapTy
using false::RematerializedValueMapTy
Initial value:
    MapVector<AssertingVH<Instruction>, AssertingVH<Value>>
Definition at line 263 of file RewriteStatepointsForGC.cpp.
StatepointLiveSetTy
using false::StatepointLiveSetTy = SetVector<Value *>
Definition at line 262 of file RewriteStatepointsForGC.cpp.
Function Documentation
dump_node_container()
template<typename NodeContainer > void false::dump_node_container (raw_ostream & OS, const NodeContainer & S)
Definition at line 276 of file HexagonCommonGEP.cpp.
References dump_node_container(), E, and I.
Referenced by dump_node_container(), and operator<<().
operator<<() [1/3]
raw_ostream & false::operator<< (raw_ostream & OS, const GepNode & GN)
Definition at line 219 of file HexagonCommonGEP.cpp.
operator<<() [2/3]
raw_ostream & false::operator<< (raw_ostream & OS, const NodeToUsesMap & M)
Definition at line 292 of file HexagonCommonGEP.cpp.
References I.
operator<<() [3/3]
raw_ostream & false::operator<< (raw_ostream & OS, const NodeVect & S)
Definition at line 285 of file HexagonCommonGEP.cpp.
References dump_node_container().