LLVM: lib/Target/PowerPC/PPCTargetTransformInfo.cpp File Reference
PPCTargetTransformInfo.cpp File Reference
#include "PPCTargetTransformInfo.h"
#include "llvm/Analysis/CodeMetrics.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/BasicTTIImpl.h"
#include "llvm/CodeGen/CostTable.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetSchedule.h"
#include "llvm/IR/IntrinsicsPowerPC.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Transforms/InstCombine/InstCombiner.h"
#include "llvm/Transforms/Utils/Local.h"
Macros
#define DEBUG_TYPE "ppctti"
Functions
static bool isMMAType (Type *Ty)
static bool memAddrUsesCTR (const Value *MemAddr, const PPCTargetMachine &TM, SmallPtrSetImpl< const Value * > &Visited)
Variables
static cl::opt< bool > DisablePPCConstHoist ("disable-ppc-constant-hoisting", cl::desc("disable constant hoisting on PPC"), cl::init(false), cl::Hidden)
static cl::opt< unsigned > CacheLineSize ("ppc-loop-prefetch-cache-line", cl::Hidden, cl::init(64), cl::desc("The loop prefetch cache line size"))
static cl::opt< bool > EnablePPCColdCC ("ppc-enable-coldcc", cl::Hidden, cl::init(false), cl::desc("Enable using coldcc calling conv for cold " "internal functions"))
static cl::opt< bool > LsrNoInsnsCost ("ppc-lsr-no-insns-cost", cl::Hidden, cl::init(false), cl::desc("Do not add instruction count to lsr cost model"))
static cl::opt< unsigned > SmallCTRLoopThreshold ("min-ctr-loop-threshold", cl::init(4), cl::Hidden, cl::desc("Loops with a constant trip count smaller than " "this value will not use the count register."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ppctti"
Definition at line 26 of file PPCTargetTransformInfo.cpp.
Function Documentation
isMMAType()
static bool isMMAType (Type * Ty) static
Definition at line 323 of file PPCTargetTransformInfo.cpp.
Referenced by llvm::PPCTTIImpl::vectorCostAdjustmentFactor().
memAddrUsesCTR()
static bool memAddrUsesCTR (const Value * MemAddr, const PPCTargetMachine & TM, SmallPtrSetImpl< const Value * > & Visited) static
Definition at line 348 of file PPCTargetTransformInfo.cpp.
References llvm::TLSModel::GeneralDynamic, llvm::TLSModel::LocalDynamic, memAddrUsesCTR(), and TM.
Referenced by llvm::PPCTTIImpl::isHardwareLoopProfitable(), and memAddrUsesCTR().
Variable Documentation
CacheLineSize
cl::opt< unsigned > CacheLineSize("ppc-loop-prefetch-cache-line", cl::Hidden, cl::init(64), cl::desc("The loop prefetch cache line size")) ("ppc-loop-prefetch-cache-line" , cl::Hidden , cl::init(64) , cl::desc("The loop prefetch cache line size")) static
Referenced by llvm::IndexedReference::computeRefCost(), llvm::AMDGPUTargetAsmStreamer::EmitCodeEnd(), llvm::AMDGPUTargetELFStreamer::EmitCodeEnd(), and llvm::PPCTTIImpl::getCacheLineSize().
DisablePPCConstHoist
cl::opt< bool > DisablePPCConstHoist("disable-ppc-constant-hoisting", cl::desc("disable constant hoisting on PPC"), cl::init(false), cl::Hidden) ("disable-ppc-constant-hoisting" , cl::desc("disable constant hoisting on PPC") , cl::init(false) , cl::Hidden) static
Referenced by llvm::PPCTTIImpl::getIntImmCost(), llvm::PPCTTIImpl::getIntImmCostInst(), and llvm::PPCTTIImpl::getIntImmCostIntrin().
EnablePPCColdCC
cl::opt< bool > EnablePPCColdCC("ppc-enable-coldcc", cl::Hidden, cl::init(false), cl::desc("Enable using coldcc calling conv for cold " "internal functions")) ("ppc-enable-coldcc" , cl::Hidden , cl::init(false) , cl::desc("Enable using coldcc calling conv for cold " "internal functions")) static
Referenced by llvm::PPCTTIImpl::useColdCCForColdCall().
LsrNoInsnsCost
cl::opt< bool > LsrNoInsnsCost("ppc-lsr-no-insns-cost", cl::Hidden, cl::init(false), cl::desc("Do not add instruction count to lsr cost model")) ("ppc-lsr-no-insns-cost" , cl::Hidden , cl::init(false) , cl::desc("Do not add instruction count to lsr cost model")) static
Referenced by llvm::PPCTTIImpl::isLSRCostLess().
SmallCTRLoopThreshold
cl::opt< unsigned > SmallCTRLoopThreshold("min-ctr-loop-threshold", cl::init(4), cl::Hidden, cl::desc("Loops with a constant trip count smaller than " "this value will not use the count register.")) ("min-ctr-loop-threshold" , cl::init(4) , cl::Hidden , cl::desc("Loops with a constant trip count smaller than " "this value will not use the count register.")) static
Referenced by llvm::PPCTTIImpl::isHardwareLoopProfitable().