LLVM: lib/Support/regcomp.c File Reference
regcomp.c File Reference
#include <sys/types.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <limits.h>
#include <stdlib.h>
#include "regex_impl.h"
#include "regutils.h"
#include "regex2.h"
#include "llvm/Config/config.h"
#include "llvm/Support/Compiler.h"
Classes
struct cclass
struct cname
struct parse
Macros
#define NPAREN 10 /* we need to remember () 1-9 for back refs */
#define PEEK() (*p->next)
#define PEEK2() (*(p->next+1))
#define MORE() (p->next < p->end)
#define MORE2() (p->next+1 < p->end)
#define SEE(c) (MORE() && PEEK() == (c))
#define SEETWO(a, b) (MORE() && MORE2() && PEEK() == (a) && PEEK2() == (b))
#define EAT(c) ((SEE(c)) ? (NEXT(), 1) : 0)
#define EATTWO(a, b) ((SEETWO(a, b)) ? (NEXT2(), 1) : 0)
#define NEXT() (p->next++)
#define NEXT2() (p->next += 2)
#define NEXTn(n) (p->next += (n))
#define GETNEXT() (*p->next++)
#define SETERROR(e) seterr(p, (e))
#define REQUIRE(co, e) (void)((co) || SETERROR(e))
#define MUSTSEE(c, e) (REQUIRE(MORE() && PEEK() == (c), e))
#define MUSTEAT(c, e) (REQUIRE(MORE() && GETNEXT() == (c), e))
#define MUSTNOTSEE(c, e) (REQUIRE(!MORE() || PEEK() != (c), e))
#define EMIT(op, sopnd) doemit(p, (sop)(op), (size_t)(sopnd))
#define INSERT(op, pos) doinsert(p, (sop)(op), HERE()-(pos)+1, pos)
#define AHEAD(pos) dofwd(p, pos, HERE()-(pos))
#define ASTERN(sop, pos) EMIT(sop, HERE()-pos)
#define HERE() (p->slen)
#define THERE() (p->slen - 1)
#define THERETHERE() (p->slen - 2)
#define DROP(n) (p->slen -= (n))
#define DUPMAX 255
#define INFINITY (DUPMAX + 1)
#define never 0 /* some <assert.h>s have bugs too */
#define GOODFLAGS(f) ((f)&~REG_DUMP)
#define BACKSL (1<<CHAR_BIT)
#define N 2
#define INF 3
#define REP(f, t) ((f)*8 + (t))
#define MAP(n) (((n) <= 1) ? (n) : ((n) == INFINITY) ? INF : N)
Functions
static void p_ere (struct parse *, int)
static void p_ere_exp (struct parse *)
static void p_str (struct parse *)
static void p_bre (struct parse *, int, int)
static int p_simp_re (struct parse *, int)
static int p_count (struct parse *)
static void p_bracket (struct parse *)
static void p_b_term (struct parse *, cset *)
static void p_b_cclass (struct parse *, cset *)
static void p_b_eclass (struct parse *, cset *)
static char p_b_symbol (struct parse *)
static char p_b_coll_elem (struct parse *, int)
static char othercase (int)
static void bothcases (struct parse *, int)
static void ordinary (struct parse *, int)
static void nonnewline (struct parse *)
static void repeat (struct parse *, sopno, int, int)
static int seterr (struct parse *, int)
static cset * allocset (struct parse *)
static void freeset (struct parse *, cset *)
static int freezeset (struct parse *, cset *)
static int firstch (struct parse *, cset *)
static int nch (struct parse *, cset *)
static void mcadd (struct parse *, cset *, const char *)
static void mcinvert (struct parse *, cset *)
static void mccase (struct parse *, cset *)
static int isinsets (struct re_guts *, int)
static int samesets (struct re_guts *, int, int)
static void categorize (struct parse *, struct re_guts *)
static sopno dupl (struct parse *, sopno, sopno)
static void doemit (struct parse *, sop, size_t)
static void doinsert (struct parse *, sop, size_t, sopno)
static void dofwd (struct parse *, sopno, sop)
static void enlarge (struct parse *, sopno)
static void stripsnug (struct parse *, struct re_guts *)
static void findmust (struct parse *, struct re_guts *)
static sopno pluscount (struct parse *, struct re_guts *)
int llvm_regcomp (llvm_regex_t *preg, const char *pattern, int cflags)
Variables
static struct cclass cclasses []
static struct cname cnames []
static char nuls [10]
Macro Definition Documentation
AHEAD
#define AHEAD (pos) dofwd(p, pos, HERE()-(pos))
Definition at line 269 of file regcomp.c.
Referenced by p_ere(), p_ere_exp(), and repeat().
ASTERN
#define ASTERN (sop, pos) EMIT(sop, HERE()-pos)
Definition at line 270 of file regcomp.c.
Referenced by p_ere(), p_ere_exp(), p_simp_re(), and repeat().
BACKSL
#define BACKSL (1<<CHAR_BIT)
DROP
#define DROP (n) (p->slen -= (n))
Definition at line 274 of file regcomp.c.
Referenced by p_bre(), and repeat().
DUPMAX
#define DUPMAX 255
Definition at line 279 of file regcomp.c.
Referenced by p_count().
EAT
#define EAT (c) ((SEE(c)) ? (NEXT(), 1) : 0)
Definition at line 256 of file regcomp.c.
Referenced by p_b_term(), p_bracket(), p_bre(), p_ere(), p_ere_exp(), and p_simp_re().
EATTWO
#define EATTWO (a, b) ((SEETWO(a, b)) ? (NEXT2(), 1) : 0)
Definition at line 257 of file regcomp.c.
Referenced by p_b_symbol(), p_b_term(), and p_simp_re().
EMIT
#define EMIT (op, sopnd) doemit(p, (sop)(op), (size_t)(sopnd))
Definition at line 267 of file regcomp.c.
Referenced by doinsert(), llvm_regcomp(), ordinary(), p_bracket(), p_bre(), p_ere(), p_ere_exp(), p_simp_re(), and repeat().
GETNEXT
#define GETNEXT () (*p->next++)
Definition at line 261 of file regcomp.c.
Referenced by p_b_symbol(), p_count(), p_ere_exp(), p_simp_re(), and p_str().
GOODFLAGS
#define GOODFLAGS (f) ((f)&~REG_DUMP)
HERE
#define HERE () (p->slen)
Definition at line 271 of file regcomp.c.
Referenced by doinsert(), dupl(), p_bre(), p_ere(), p_ere_exp(), p_simp_re(), and repeat().
INF
#define INF 3
INFINITY
#define INFINITY (DUPMAX + 1)
Definition at line 281 of file regcomp.c.
Referenced by p_ere_exp(), and p_simp_re().
INSERT
#define INSERT (op, pos) doinsert(p, (sop)(op), HERE()-(pos)+1, pos)
Definition at line 268 of file regcomp.c.
Referenced by p_ere(), p_ere_exp(), p_simp_re(), and repeat().
MAP
#define MAP (n) (((n) <= 1) ? (n) : ((n) == INFINITY) ? INF : N)
MORE
#define MORE () (p->next < p->end)
Definition at line 252 of file regcomp.c.
Referenced by llvm::Combiner::combineMachineInstrs(), INITIALIZE_PASS(), p_b_cclass(), p_b_coll_elem(), p_b_symbol(), p_b_term(), p_bracket(), p_bre(), p_count(), p_ere(), p_ere_exp(), p_simp_re(), p_str(), reportGISelDiagnostic(), llvm::reportGISelFailure(), llvm::reportGISelFailure(), llvm::reportGISelWarning(), llvm::InstructionSelect::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), and llvm::MIRProfileLoader::setInitVals().
MORE2
#define MORE2 () (p->next+1 < p->end)
Definition at line 253 of file regcomp.c.
Referenced by p_b_term(), and p_ere_exp().
MUSTEAT
#define MUSTEAT (c, e) (REQUIRE(MORE() && GETNEXT() == (c), e))
Definition at line 265 of file regcomp.c.
Referenced by p_bracket(), and p_ere_exp().
MUSTNOTSEE
#define MUSTNOTSEE (c, e) (REQUIRE(!MORE() || PEEK() != (c), e))
Definition at line 266 of file regcomp.c.
MUSTSEE
#define MUSTSEE (c, e) (REQUIRE(MORE() && PEEK() == (c), e))
Definition at line 264 of file regcomp.c.
N
#define N 2
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-14/llvm/include/llvm/ADT/ilist_node.h, and /Users/rift/code/other/llvm-doxygen/llvm-project-14/llvm/include/llvm/Transforms/Utils/Local.h.
never
#define never 0 /* some <assert.h>s have bugs too */
Definition at line 286 of file regcomp.c.
Referenced by firstch().
NEXT
#define NEXT () (p->next++)
Definition at line 258 of file regcomp.c.
Referenced by p_b_cclass(), p_b_coll_elem(), p_b_term(), p_ere_exp(), and p_simp_re().
NEXT2
#define NEXT2 () (p->next += 2)
Definition at line 259 of file regcomp.c.
Referenced by p_b_term().
NEXTn
#define NEXTn (n) (p->next += (n))
Definition at line 260 of file regcomp.c.
Referenced by p_bracket().
NPAREN
#define NPAREN 10 /* we need to remember () 1-9 for back refs */
Definition at line 201 of file regcomp.c.
Referenced by doinsert(), llvm_regcomp(), p_ere_exp(), and p_simp_re().
PEEK
#define PEEK () (*p->next)
Definition at line 250 of file regcomp.c.
Referenced by p_b_cclass(), p_b_term(), p_bracket(), p_count(), p_ere(), p_ere_exp(), and p_simp_re().
PEEK2
#define PEEK2 () (*(p->next+1))
Definition at line 251 of file regcomp.c.
Referenced by p_b_term(), and p_ere_exp().
REP
#define REP (f, t) ((f)*8 + (t))
REQUIRE
#define REQUIRE (co, e) (void)((co) || SETERROR(e))
Definition at line 263 of file regcomp.c.
Referenced by p_b_symbol(), p_b_term(), p_bre(), p_count(), p_ere(), p_ere_exp(), p_simp_re(), and p_str().
SEE
#define SEE (c) (MORE() && PEEK() == (c))
Definition at line 254 of file regcomp.c.
Referenced by p_b_term(), p_ere(), and p_ere_exp().
SEETWO
#define SEETWO (a, b) (MORE() && MORE2() && PEEK() == (a) && PEEK2() == (b))
Definition at line 255 of file regcomp.c.
Referenced by p_b_coll_elem(), p_bracket(), p_bre(), and p_simp_re().
SETERROR
#define SETERROR (e) seterr(p, (e))
Definition at line 262 of file regcomp.c.
Referenced by allocset(), enlarge(), llvm_regcomp(), mcadd(), p_b_cclass(), p_b_coll_elem(), p_b_term(), p_ere_exp(), p_simp_re(), repeat(), and stripsnug().
THERE
#define THERE () (p->slen - 1)
Definition at line 272 of file regcomp.c.
Referenced by llvm_regcomp(), p_ere(), p_ere_exp(), and repeat().
THERETHERE
#define THERETHERE () (p->slen - 2)
Definition at line 273 of file regcomp.c.
Referenced by p_ere_exp(), and repeat().
Function Documentation
allocset()
static cset * allocset (struct parse * p) static
Definition at line 1194 of file regcomp.c.
References assert(), re_guts::csetsize, parse::g, cset::hash, cset::mask, cset::multis, parse::ncsalloc, re_guts::ncsets, cset::ptr, REG_ESPACE, re_guts::setbits, SETERROR, re_guts::sets, and cset::smultis.
Referenced by p_bracket().
bothcases()
static void bothcases (struct parse * p, int ch) static
Definition at line 1047 of file regcomp.c.
References assert(), parse::end, parse::next, othercase(), and p_bracket().
Referenced by ordinary().
categorize()
static void categorize (struct parse * p, struct re_guts * g) static
Definition at line 1424 of file regcomp.c.
References re_guts::categories, parse::error, isinsets(), re_guts::ncategories, and samesets().
Referenced by llvm_regcomp().
doemit()
static void doemit (struct parse * p, sop op, size_t opnd) static
Definition at line 1475 of file regcomp.c.
References assert(), enlarge(), parse::error, op, OPSHIFT, parse::slen, SOP, parse::ssize, and parse::strip.
dofwd()
static void dofwd (struct parse * p, sopno pos, sop value) static
Definition at line 1532 of file regcomp.c.
References assert(), parse::error, OP, OPSHIFT, parse::strip, and value.
doinsert()
static void doinsert (struct parse * p, sop op, size_t opnd, sopno pos) static
Definition at line 1497 of file regcomp.c.
References assert(), EMIT, parse::error, HERE, NPAREN, op, parse::pbegin, parse::pend, and parse::strip.
dupl()
static sopno dupl (struct parse * p, sopno start, sopno finish) static
Definition at line 1449 of file regcomp.c.
References assert(), enlarge(), HERE, parse::slen, parse::ssize, and parse::strip.
Referenced by p_ere_exp(), p_simp_re(), and repeat().
enlarge()
static void enlarge (struct parse * p, sopno size) static
Definition at line 1546 of file regcomp.c.
References REG_ESPACE, SETERROR, size(), parse::ssize, and parse::strip.
Referenced by doemit(), and dupl().
findmust()
static void findmust (struct parse * p, struct re_guts * g) static
Definition at line 1597 of file regcomp.c.
References assert(), parse::error, re_guts::iflags, LLVM_FALLTHROUGH, re_guts::mlen, re_guts::must, O_CH, O_QUEST, OCH_, OCHAR, OEND, OLPAREN, OOR2, OP, OPLUS_, OPND, OQUEST_, ORPAREN, REGEX_BAD, scan(), and re_guts::strip.
Referenced by llvm_regcomp().
firstch()
static int firstch (struct parse * p, cset * cs) static
Definition at line 1308 of file regcomp.c.
References assert(), CHIN, re_guts::csetsize, parse::g, and never.
Referenced by p_bracket().
freeset()
static void freeset (struct parse * p, cset * cs) static
Definition at line 1255 of file regcomp.c.
References CHsub, re_guts::csetsize, parse::g, re_guts::ncsets, and re_guts::sets.
Referenced by freezeset(), and p_bracket().
freezeset()
static int freezeset (struct parse * p, cset * cs) static
Definition at line 1277 of file regcomp.c.
References CHIN, re_guts::csetsize, freeset(), parse::g, cset::hash, re_guts::ncsets, and re_guts::sets.
Referenced by p_bracket().
isinsets()
static int isinsets (struct re_guts * g, int c) static
Definition at line 1389 of file regcomp.c.
References re_guts::csetsize, re_guts::ncsets, and re_guts::setbits.
Referenced by categorize().
llvm_regcomp()
int llvm_regcomp (llvm_regex_t * preg, const char * pattern, int cflags)
Definition at line 293 of file regcomp.c.
References re_guts::backrefs, re_guts::categories, categorize(), re_guts::catspace, re_guts::cflags, re_guts::csetsize, EMIT, parse::end, parse::error, findmust(), re_guts::firststate, parse::g, GOODFLAGS, re_guts::iflags, re_guts::laststate, llvm_regfree(), re_guts::magic, MAGIC1, MAGIC2, re_guts::mlen, re_guts::must, re_guts::nbol, NC, re_guts::ncategories, parse::ncsalloc, re_guts::ncsets, re_guts::neol, parse::next, NPAREN, re_guts::nplus, re_guts::nsub, OEND, OUT, p_bre(), p_ere(), p_str(), parse::pbegin, parse::pend, pluscount(), llvm_regex::re_endp, llvm_regex::re_g, llvm_regex::re_magic, llvm_regex::re_nsub, REG_ASSERT, REG_ESPACE, REG_EXTENDED, REG_INVARG, REG_NOSPEC, REG_PEND, REGEX_BAD, re_guts::setbits, SETERROR, re_guts::sets, parse::slen, parse::ssize, parse::strip, stripsnug(), and THERE.
Referenced by llvm::Regex::Regex().
mcadd()
static void mcadd (struct parse * p, cset * cs, const char * cp) static
Definition at line 1340 of file regcomp.c.
References llvm_strlcpy(), cset::multis, REG_ESPACE, SETERROR, and cset::smultis.
mccase()
static void mccase (struct parse * p, cset * cs) static
Definition at line 1380 of file regcomp.c.
References assert(), and cset::multis.
Referenced by p_bracket().
mcinvert()
static void mcinvert (struct parse * p, cset * cs) static
Definition at line 1367 of file regcomp.c.
References assert(), and cset::multis.
Referenced by p_bracket().
nch()
static int nch (struct parse * p, cset * cs) static
Definition at line 1324 of file regcomp.c.
References CHIN, re_guts::csetsize, and parse::g.
Referenced by p_bracket().
nonnewline()
static void nonnewline (struct parse * p) static
Definition at line 1089 of file regcomp.c.
References assert(), parse::end, parse::next, and p_bracket().
Referenced by p_ere_exp(), and p_simp_re().
ordinary()
static void ordinary (struct parse * p, int ch) static
Definition at line 1070 of file regcomp.c.
References bothcases(), re_guts::categories, re_guts::cflags, EMIT, parse::g, re_guts::ncategories, OCHAR, othercase(), and REG_ICASE.
Referenced by p_bracket(), p_ere_exp(), p_simp_re(), and p_str().
othercase()
static char othercase (int ch) static
Definition at line 1029 of file regcomp.c.
References assert().
Referenced by bothcases(), ordinary(), and p_bracket().
p_b_cclass()
static void p_b_cclass (struct parse * p, cset * cs) static
Definition at line 939 of file regcomp.c.
References cclasses, CHadd, cclass::chars, MCadd, MORE, cclass::multis, cclass::name, parse::next, NEXT, PEEK, REG_ECTYPE, and SETERROR.
Referenced by p_b_term().
p_b_coll_elem()
static char p_b_coll_elem (struct parse * p, int endc) static
Definition at line 1002 of file regcomp.c.
References cnames, cname::code, MORE, cname::name, parse::next, NEXT, REG_EBRACK, REG_ECOLLATE, SEETWO, and SETERROR.
Referenced by p_b_eclass(), and p_b_symbol().
p_b_eclass()
static void p_b_eclass (struct parse * p, cset * cs) static
Definition at line 972 of file regcomp.c.
References CHadd, and p_b_coll_elem().
Referenced by p_b_term().
p_b_symbol()
static char p_b_symbol (struct parse * p) static
Definition at line 984 of file regcomp.c.
References EATTWO, GETNEXT, MORE, p_b_coll_elem(), REG_EBRACK, REG_ECOLLATE, REQUIRE, and value.
Referenced by p_b_term().
p_b_term()
static void p_b_term (struct parse * p, cset * cs) static
Definition at line 876 of file regcomp.c.
References CHadd, EAT, EATTWO, MORE, MORE2, NEXT, NEXT2, p_b_cclass(), p_b_eclass(), p_b_symbol(), PEEK, PEEK2, REG_EBRACK, REG_ECOLLATE, REG_ECTYPE, REG_ERANGE, REQUIRE, SEE, and SETERROR.
Referenced by p_bracket().
p_bracket()
static void p_bracket (struct parse * p) static
Definition at line 797 of file regcomp.c.
References allocset(), assert(), re_guts::cflags, CHadd, CHIN, CHsub, re_guts::csetsize, EAT, EMIT, parse::end, parse::error, firstch(), freeset(), freezeset(), parse::g, mccase(), mcinvert(), MORE, cset::multis, MUSTEAT, nch(), parse::next, NEXTn, OANYOF, OBOW, OEOW, ordinary(), othercase(), p_b_term(), PEEK, REG_EBRACK, REG_ICASE, REG_NEWLINE, and SEETWO.
Referenced by bothcases(), nonnewline(), p_ere_exp(), and p_simp_re().
p_bre()
static void p_bre (struct parse * p, int end1, int end2) static
Definition at line 629 of file regcomp.c.
References DROP, EAT, EMIT, parse::g, HERE, re_guts::iflags, MORE, re_guts::nbol, re_guts::neol, OBOL, OEOL, p_simp_re(), REG_EMPTY, REQUIRE, SEETWO, USEBOL, and USEEOL.
Referenced by llvm_regcomp(), and p_simp_re().
p_count()
static int p_count (struct parse * p) static
Definition at line 776 of file regcomp.c.
References DUPMAX, GETNEXT, MORE, PEEK, REG_BADBR, and REQUIRE.
Referenced by p_ere_exp(), and p_simp_re().
p_ere()
static void p_ere (struct parse * p, int stop) static
Definition at line 393 of file regcomp.c.
References AHEAD, assert(), ASTERN, EAT, EMIT, HERE, INSERT, MORE, O_CH, OCH_, OOR1, OOR2, p_ere_exp(), PEEK, REG_EMPTY, REQUIRE, SEE, and THERE.
Referenced by llvm_regcomp(), and p_ere_exp().
p_ere_exp()
static void p_ere_exp (struct parse * p) static
Definition at line 436 of file regcomp.c.
References AHEAD, assert(), ASTERN, re_guts::backrefs, re_guts::cflags, dupl(), EAT, EMIT, parse::g, GETNEXT, HERE, re_guts::iflags, INFINITY, INSERT, LLVM_FALLTHROUGH, MORE, MORE2, MUSTEAT, re_guts::nbol, re_guts::neol, NEXT, nonnewline(), NPAREN, re_guts::nsub, O_BACK, O_CH, O_PLUS, O_QUEST, OANY, OBACK_, OBOL, OCH_, OEOL, OLPAREN, OOR1, OOR2, OP, OPLUS_, OQUEST_, ordinary(), ORPAREN, p_bracket(), p_count(), p_ere(), parse::pbegin, PEEK, PEEK2, parse::pend, REG_BADBR, REG_BADRPT, REG_EBRACE, REG_EESCAPE, REG_EMPTY, REG_EPAREN, REG_ESUBREG, REG_NEWLINE, repeat(), REQUIRE, SEE, SETERROR, parse::strip, THERE, THERETHERE, USEBOL, and USEEOL.
Referenced by p_ere().
p_simp_re()
static int p_simp_re (struct parse * p, int starordinary) static
Definition at line 660 of file regcomp.c.
References assert(), ASTERN, re_guts::backrefs, BACKSL, re_guts::cflags, dupl(), EAT, EATTWO, EMIT, parse::g, GETNEXT, HERE, INFINITY, INSERT, LLVM_FALLTHROUGH, MORE, NEXT, nonnewline(), NPAREN, re_guts::nsub, O_BACK, O_PLUS, O_QUEST, OANY, OBACK_, OLPAREN, OP, OPLUS_, OQUEST_, ordinary(), ORPAREN, p_bracket(), p_bre(), p_count(), parse::pbegin, PEEK, parse::pend, REG_BADBR, REG_BADRPT, REG_EBRACE, REG_EESCAPE, REG_EPAREN, REG_ESUBREG, REG_NEWLINE, repeat(), REQUIRE, SEETWO, SETERROR, and parse::strip.
Referenced by p_bre().
p_str()
static void p_str (struct parse * p) static
Definition at line 611 of file regcomp.c.
References GETNEXT, MORE, ordinary(), REG_EMPTY, and REQUIRE.
Referenced by llvm_regcomp().
pluscount()
static sopno pluscount (struct parse * p, struct re_guts * g) static
Definition at line 1675 of file regcomp.c.
References parse::error, re_guts::iflags, O_PLUS, OEND, OP, OPLUS_, REGEX_BAD, scan(), and re_guts::strip.
Referenced by llvm_regcomp().
repeat()
static void repeat (struct parse * p, sopno start, int from, int to) static
Definition at line 1111 of file regcomp.c.
References AHEAD, assert(), ASTERN, DROP, dupl(), EMIT, parse::error, HERE, INF, INSERT, MAP, N, O_CH, O_PLUS, OCH_, OOR1, OOR2, OPLUS_, REG_ASSERT, REP, repeat(), SETERROR, THERE, and THERETHERE.
Referenced by p_ere_exp(), p_simp_re(), and repeat().
samesets()
static int samesets (struct re_guts * g, int c1, int c2) static
Definition at line 1406 of file regcomp.c.
References re_guts::csetsize, re_guts::ncsets, and re_guts::setbits.
Referenced by categorize().
seterr()
static int seterr (struct parse * p, int e) static
Definition at line 1181 of file regcomp.c.
References parse::end, parse::error, parse::next, and nuls.
stripsnug()
static void stripsnug (struct parse * p, struct re_guts * g) static
Definition at line 1571 of file regcomp.c.
References re_guts::nstates, REG_ESPACE, SETERROR, parse::slen, parse::strip, and re_guts::strip.
Referenced by llvm_regcomp().
Variable Documentation
cclasses
struct cclass cclasses[] static
Initial value:
= {
  { "alnum",  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\
0123456789",        ""} ,
  { "alpha",  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
          ""} ,
  { "blank",  " \t",    ""} ,
  { "cntrl",  "\007\b\t\n\v\f\r\1\2\3\4\5\6\16\17\20\21\22\23\24\
\25\26\27\30\31\32\33\34\35\36\37\177", ""} ,
  { "digit",  "0123456789", ""} ,
  { "graph",  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\
0123456789!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~",
          ""} ,
  { "lower",  "abcdefghijklmnopqrstuvwxyz",
          ""} ,
  { "print",  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz\
0123456789!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ ",
          ""} ,
  { "punct",  "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~",
          ""} ,
  { "space",  "\t\n\v\f\r ",  ""} ,
  { "upper",  "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
          ""} ,
  { "xdigit", "0123456789ABCDEFabcdef",
          ""} ,
  { NULL,   0,    "" }
}
Referenced by p_b_cclass().
cnames
struct cname cnames[] static
Referenced by p_b_coll_elem().
nuls
char nuls[10] static
Definition at line 244 of file regcomp.c.
Referenced by seterr().