LLVM: lib/Analysis/RegionPrinter.cpp File Reference
RegionPrinter.cpp File Reference
#include "llvm/Analysis/RegionPrinter.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/DOTGraphTraitsPass.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/Analysis/RegionInfo.h"
#include "llvm/Analysis/RegionIterator.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/IR/LegacyPassManager.h"
Classes
struct llvm::DOTGraphTraits< RegionNode * >
struct llvm::DOTGraphTraits< RegionInfo * >
Namespaces
namespace llvm
/file This file defines the SmallVector class.
Functions
INITIALIZE_PASS (RegionPrinter, "dot-regions", "Print regions of function to 'dot' file", true, true) INITIALIZE_PASS(RegionOnlyPrinter
dot regions Print regions of function to dot file (with no function bodies)"
dot regions Print regions of function to dot true INITIALIZE_PASS (RegionViewer, "view-regions", "View regions of function", true, true) INITIALIZE_PASS(RegionOnlyViewer
dot regions Print regions of function to dot true view regions View regions of function (with no function bodies)"
static void viewRegionInfo (RegionInfo *RI, bool ShortNames)
static void invokeFunctionPass (const Function *F, FunctionPass *ViewerPass)
Variables
static cl::opt< bool > onlySimpleRegions ("only-simple-regions", cl::desc("Show only simple regions in the graphviz viewer"), cl::Hidden, cl::init(false))
onlySimpleRegion - Show only the simple regions in the RegionViewer.
dot regions only
dot regions Print regions of function to dot true
Function Documentation
file()
dot regions Print regions of function to dot file (with no function bodies)
Referenced by llvm::gcovOneInput(), and llvm::llvm_unreachable_internal().
function()
dot regions Print regions of function to dot true view regions View regions of function (with no function bodies)
INITIALIZE_PASS() [1/2]
INITIALIZE_PASS (RegionPrinter , "dot-regions" , "Print regions of function to 'dot' file" , true , true)
INITIALIZE_PASS() [2/2]
dot regions Print regions of function to dot true INITIALIZE_PASS (RegionViewer , "view-regions" , "View regions of function" , true , true)
invokeFunctionPass()
static void invokeFunctionPass (const Function * F, FunctionPass * ViewerPass) static
Definition at line 241 of file RegionPrinter.cpp.
References llvm::legacy::FunctionPassManager::add(), assert(), llvm::legacy::FunctionPassManager::doFinalization(), llvm::legacy::FunctionPassManager::doInitialization(), F, and llvm::legacy::FunctionPassManager::run().
Referenced by llvm::viewRegion(), and llvm::viewRegionOnly().
viewRegionInfo()
static void viewRegionInfo (RegionInfo * RI, bool ShortNames) static
Definition at line 231 of file RegionPrinter.cpp.
References assert(), F, llvm::RegionInfoBase< Tr >::getTopLevelRegion(), and llvm::ViewGraph().
Referenced by llvm::viewRegion(), and llvm::viewRegionOnly().
Variable Documentation
only
dot regions Print regions of function to dot true view regions only
Definition at line 205 of file RegionPrinter.cpp.
onlySimpleRegions
cl::opt< bool > onlySimpleRegions("only-simple-regions", cl::desc("Show only simple regions in the graphviz viewer"), cl::Hidden, cl::init(false)) ("only-simple-regions" , cl::desc("Show only simple regions in the graphviz viewer") , cl::Hidden , cl::init(false)) static
onlySimpleRegion - Show only the simple regions in the RegionViewer.
Referenced by llvm::DOTGraphTraits< RegionInfo * >::printRegionCluster().
true
dot regions Print regions of function to dot true view regions View regions of true
Definition at line 206 of file RegionPrinter.cpp.