LLVM: llvm::DenseMapInfo< MemOpKey > Struct Reference
llvm::DenseMapInfo< MemOpKey > Struct Reference
Provide DenseMapInfo for MemOpKey.
Public Types
using PtrInfo = DenseMapInfo<const MachineOperand *>
Static Public Member Functions
static MemOpKey getEmptyKey ()
static MemOpKey getTombstoneKey ()
static unsigned getHashValue (const MemOpKey &Val)
static bool isEqual (const MemOpKey &LHS, const MemOpKey &RHS)
Detailed Description
Provide DenseMapInfo for MemOpKey.
Definition at line 118 of file X86OptimizeLEAs.cpp.
Member Typedef Documentation
PtrInfo
using llvm::DenseMapInfo< MemOpKey >::PtrInfo = DenseMapInfo<const MachineOperand *>
Definition at line 119 of file X86OptimizeLEAs.cpp.
Member Function Documentation
getEmptyKey()
static MemOpKey llvm::DenseMapInfo< MemOpKey >::getEmptyKey () inline static
Definition at line 121 of file X86OptimizeLEAs.cpp.
getHashValue()
static unsigned llvm::DenseMapInfo< MemOpKey >::getHashValue (const MemOpKey & Val) inline static
Definition at line 133 of file X86OptimizeLEAs.cpp.
References assert(), llvm::MachineOperand::getBlockAddress(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getMCSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getType(), llvm::hash_combine(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, and llvm::MachineOperand::MO_MCSymbol.
getTombstoneKey()
static MemOpKey llvm::DenseMapInfo< MemOpKey >::getTombstoneKey () inline static
Definition at line 127 of file X86OptimizeLEAs.cpp.
isEqual()
static bool llvm::DenseMapInfo< MemOpKey >::isEqual (const MemOpKey & LHS, const MemOpKey & RHS) inline static
Definition at line 176 of file X86OptimizeLEAs.cpp.
References RHS.
The documentation for this struct was generated from the following file:
lib/Target/X86/X86OptimizeLEAs.cpp