LLVM: llvm::BoundsCheckingPass Struct Reference
llvm::BoundsCheckingPass Struct Reference
A pass to instrument code and perform run-time bounds checking on loads, stores, and other memory intrinsics.
#include "llvm/Transforms/Instrumentation/BoundsChecking.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< BoundsCheckingPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< BoundsCheckingPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A pass to instrument code and perform run-time bounds checking on loads, stores, and other memory intrinsics.
Definition at line 19 of file BoundsChecking.h.
Member Function Documentation
isRequired()
static bool llvm::BoundsCheckingPass::isRequired () inline static
Definition at line 21 of file BoundsChecking.h.
run()
PreservedAnalyses BoundsCheckingPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 214 of file BoundsChecking.cpp.
References addBoundsChecking(), llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::none().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Instrumentation/BoundsChecking.h
lib/Transforms/Instrumentation/BoundsChecking.cpp