LLVM: AAValueConstantRangeFloating Struct Reference
AAValueConstantRangeFloating Struct Reference
Public Member Functions
AAValueConstantRangeFloating (const IRPosition &IRP, Attributor &A)
void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
bool calculateBinaryOperator (Attributor &A, BinaryOperator *BinOp, IntegerRangeState &T, const Instruction *CtxI, SmallVectorImpl< const AAValueConstantRange * > &QuerriedAAs)
bool calculateCastInst (Attributor &A, CastInst *CastI, IntegerRangeState &T, const Instruction *CtxI, SmallVectorImpl< const AAValueConstantRange * > &QuerriedAAs)
bool calculateCmpInst (Attributor &A, CmpInst *CmpI, IntegerRangeState &T, const Instruction *CtxI, SmallVectorImpl< const AAValueConstantRange * > &QuerriedAAs)
ChangeStatus updateImpl (Attributor &A) override
See AbstractAttribute::updateImpl(...).
void trackStatistics () const override
See AbstractAttribute::trackStatistics()
Public Member Functions inherited from AAValueConstantRangeImpl
AAValueConstantRangeImpl (const IRPosition &IRP, Attributor &A)
void initialize (Attributor &A) override
See AbstractAttribute::initialize(..).
const std::string getAsStr () const override
See AbstractAttribute::getAsStr().
const SCEV * getSCEV (Attributor &A, const Instruction *I=nullptr) const
Helper function to get a SCEV expr for the associated value at program point I.
ConstantRange getConstantRangeFromSCEV (Attributor &A, const Instruction *I=nullptr) const
Helper function to get a range from SCEV for the associated value at program point I.
ConstantRange getConstantRangeFromLVI (Attributor &A, const Instruction *CtxI=nullptr) const
Helper function to get a range from LVI for the associated value at program point I.
bool isValidCtxInstructionForOutsideAnalysis (Attributor &A, const Instruction *CtxI, bool AllowAACtxI) const
Return true if CtxI is valid for querying outside analyses.
ConstantRange getKnownConstantRange (Attributor &A, const Instruction *CtxI=nullptr) const override
See AAValueConstantRange::getKnownConstantRange(..).
ConstantRange getAssumedConstantRange (Attributor &A, const Instruction *CtxI=nullptr) const override
See AAValueConstantRange::getAssumedConstantRange(..).
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest()
Public Member Functions inherited from llvm::AAValueConstantRange
AAValueConstantRange (const IRPosition &IRP, Attributor &A)
IntegerRangeState & getState () override
See AbstractAttribute::getState(...).
const IntegerRangeState & getState () const override
Optional< ConstantInt * > getAssumedConstantInt (Attributor &A, const Instruction *CtxI=nullptr) const
Return an assumed constant for the associated value a program point CtxI.
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::StateWrapper< IntegerRangeState, AbstractAttribute, uint32_t >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (const IRPosition &IRP)
virtual ~AbstractAttribute ()=default
Virtual destructor.
virtual bool isQueryAA () const
A query AA is always scheduled as long as we do updates because it does lazy computation that cannot be determined to be done from the outside.
const IRPosition & getIRPosition () const
Return an IR position, see struct IRPosition.
IRPosition & getIRPosition ()
void print (raw_ostream &OS) const override
Helper functions, for debug purposes only.
virtual void printWithDeps (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::IRPosition
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getCalleeArgNo () const
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
int getCallSiteArgNo () const
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Kind getPositionKind () const
Return the associated position kind.
bool hasAttr (ArrayRef< Attribute::AttrKind > AKs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
TODO: Figure out if the attribute related helper functions should live here or somewhere else.
void getAttrs (ArrayRef< Attribute::AttrKind > AKs, SmallVectorImpl< Attribute > &Attrs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
Return the attributes of any kind in AKs existing in the IR at a position that will affect this one.
void removeAttrs (ArrayRef< Attribute::AttrKind > AKs) const
Remove the attribute of kind AKs existing in the IR at this position.
bool isAnyCallSitePosition () const
bool isArgumentPosition () const
Return true if the position is an argument or call site argument.
IRPosition stripCallBaseContext () const
Return the same position without the call base context.
const CallBaseContext * getCallBaseContext () const
Get the call base context from the position.
bool hasCallBaseContext () const
Check if the position has any call base context.
operator void * () const
}
Public Member Functions inherited from llvm::AADepGraphNode
virtual ~AADepGraphNode ()=default
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
TinyPtrVector< DepTy > & getDeps ()
Public Member Functions inherited from llvm::IntegerRangeState
IntegerRangeState (uint32_t BitWidth)
IntegerRangeState (const ConstantRange &CR)
uint32_t getBitWidth () const
Return associated values' bit width.
bool isValidState () const override
See AbstractState::isValidState()
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint()
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
ConstantRange getKnown () const
Return the known state encoding.
ConstantRange getAssumed () const
Return the assumed state encoding.
void unionAssumed (const ConstantRange &R)
Unite assumed range with the passed state.
void unionAssumed (const IntegerRangeState &R)
See IntegerRangeState::unionAssumed(..).
void unionKnown (const ConstantRange &R)
Unite known range with the passed state.
void unionKnown (const IntegerRangeState &R)
See IntegerRangeState::unionKnown(..).
void intersectKnown (const ConstantRange &R)
Intersect known range with the passed state.
void intersectKnown (const IntegerRangeState &R)
See IntegerRangeState::intersectKnown(..).
bool operator== (const IntegerRangeState &R) const
Equality for IntegerRangeState.
IntegerRangeState operator^= (const IntegerRangeState &R)
"Clamp" this state with R.
IntegerRangeState operator&= (const IntegerRangeState &R)
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
Public Attributes
int NumChanges = 0
Tracker to bail after too many widening steps of the constant range.
Public Attributes inherited from llvm::IntegerRangeState
uint32_t BitWidth
Bitwidth of the associated value.
ConstantRange Assumed
State representing assumed range, initially set to empty.
ConstantRange Known
State representing known range, initially set to [-inf, inf].
Static Public Attributes
static constexpr int MaxNumChanges = 5
Upper bound for the number of allowed changes (=widening steps) for the constant range before we give up.
Static Public Attributes inherited from llvm::AAValueConstantRange
static const char ID = 0
Unique ID (due to the unique address)
Static Public Attributes inherited from llvm::IRPosition
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Additional Inherited Members
Public Types inherited from AAValueConstantRangeImpl
using StateType = IntegerRangeState
Public Types inherited from llvm::AAValueConstantRange
using Base = StateWrapper<IntegerRangeState, AbstractAttribute, uint32_t>
Public Types inherited from llvm::StateWrapper< IntegerRangeState, AbstractAttribute, uint32_t >
using StateType
Provide static access to the type of the state.
Public Types inherited from llvm::AbstractAttribute
using StateType = AbstractState
Public Types inherited from llvm::IRPosition
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
using CallBaseContext = CallBase
Public Types inherited from llvm::AADepGraphNode
using DepTy = PointerIntPair<AADepGraphNode *, 1>
using iterator
using aaiterator
Static Public Member Functions inherited from AAValueConstantRangeImpl
static MDNode * getMDNodeForConstantRange (Type *Ty, LLVMContext &Ctx, const ConstantRange &AssumedConstantRange)
Helper function to create MDNode for range metadata.
static bool isBetterRange (const ConstantRange &Assumed, MDNode *KnownRanges)
Return true if Assumed is included in KnownRanges.
static bool setRangeMetadataIfisBetterRange (Instruction *I, const ConstantRange &AssumedConstantRange)
Helper function to set range metadata.
Static Public Member Functions inherited from llvm::AAValueConstantRange
static AAValueConstantRange & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAValueConstantRange.
Static Public Member Functions inherited from llvm::AbstractAttribute
static bool classof (const AADepGraphNode *DGN)
This function is used to identify if an DGN is of type AbstractAttribute so that the dyn_cast and cast can use such information to cast an AADepGraphNode to an AbstractAttribute.
Static Public Member Functions inherited from llvm::IRPosition
static const IRPosition value (const Value &V, const CallBaseContext *CBContext=nullptr)
Create a position describing the value of V.
static const IRPosition inst (const Instruction &I, const CallBaseContext *CBContext=nullptr)
Create a position describing the instruction I.
static const IRPosition function (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg, const CallBaseContext *CBContext=nullptr)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP, const CallBaseContext *CBContext=nullptr)
Create a position with function scope matching the "context" of IRP.
Static Public Member Functions inherited from llvm::IntegerRangeState
static ConstantRange getWorstState (uint32_t BitWidth)
Return the worst possible representable state.
static ConstantRange getBestState (uint32_t BitWidth)
Return the best possible representable state.
static ConstantRange getBestState (const IntegerRangeState &IRS)
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
Protected Member Functions inherited from llvm::AADepGraphNode
operator AbstractAttribute * ()
Static Protected Member Functions inherited from llvm::AADepGraphNode
static AADepGraphNode * DepGetVal (DepTy &DT)
static AbstractAttribute * DepGetValAA (DepTy &DT)
Protected Attributes inherited from llvm::AADepGraphNode
TinyPtrVector< DepTy > Deps
Set of dependency graph nodes which should be updated if this one is updated.
Detailed Description
Definition at line 8349 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
AAValueConstantRangeFloating()
AAValueConstantRangeFloating::AAValueConstantRangeFloating (const IRPosition & IRP, Attributor & A) inline
Definition at line 8350 of file AttributorAttributes.cpp.
Member Function Documentation
calculateBinaryOperator()
bool AAValueConstantRangeFloating::calculateBinaryOperator (Attributor & A, BinaryOperator * BinOp, IntegerRangeState & T, const Instruction * CtxI, SmallVectorImpl< const AAValueConstantRange * > & QuerriedAAs) inline
Definition at line 8399 of file AttributorAttributes.cpp.
References A, llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), and llvm::IRPosition::value().
calculateCastInst()
bool AAValueConstantRangeFloating::calculateCastInst (Attributor & A, CastInst * CastI, IntegerRangeState & T, const Instruction * CtxI, SmallVectorImpl< const AAValueConstantRange * > & QuerriedAAs) inline
Definition at line 8451 of file AttributorAttributes.cpp.
References A, assert(), getBitWidth(), llvm::Value::getType(), llvm::Type::isIntegerTy(), and llvm::IRPosition::value().
calculateCmpInst()
bool AAValueConstantRangeFloating::calculateCmpInst (Attributor & A, CmpInst * CmpI, IntegerRangeState & T, const Instruction * CtxI, SmallVectorImpl< const AAValueConstantRange * > & QuerriedAAs) inline
Definition at line 8483 of file AttributorAttributes.cpp.
References A, assert(), llvm::dbgs(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), LLVM_DEBUG, llvm::ConstantRange::makeAllowedICmpRegion(), and llvm::IRPosition::value().
initialize()
void AAValueConstantRangeFloating::initialize (Attributor & A) inline override virtual
See AbstractAttribute::initialize(...).
Reimplemented from llvm::AbstractAttribute.
Definition at line 8354 of file AttributorAttributes.cpp.
References A, C, llvm::dbgs(), getBitWidth(), llvm::getConstantRangeFromMetadata(), llvm::Instruction::getMetadata(), AAValueConstantRangeImpl::initialize(), and LLVM_DEBUG.
trackStatistics()
void AAValueConstantRangeFloating::trackStatistics () const inline override virtual
See AbstractAttribute::trackStatistics()
Implements llvm::AbstractAttribute.
Definition at line 8641 of file AttributorAttributes.cpp.
References STATS_DECLTRACK_FLOATING_ATTR.
updateImpl()
ChangeStatus AAValueConstantRangeFloating::updateImpl (Attributor & A) inline override virtual
See AbstractAttribute::updateImpl(...).
Implements llvm::AbstractAttribute.
Definition at line 8557 of file AttributorAttributes.cpp.
References A, llvm::clampStateAndIndicateChange(), llvm::dbgs(), getBitWidth(), I, LLVM_DEBUG, T, llvm::IntegerRangeState::unionAssumed(), and llvm::IRPosition::value().
Member Data Documentation
MaxNumChanges
constexpr int AAValueConstantRangeFloating::MaxNumChanges = 5 static constexpr
Upper bound for the number of allowed changes (=widening steps) for the constant range before we give up.
Definition at line 8650 of file AttributorAttributes.cpp.
NumChanges
int AAValueConstantRangeFloating::NumChanges = 0
Tracker to bail after too many widening steps of the constant range.
Definition at line 8646 of file AttributorAttributes.cpp.
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp