LLVM: llvm::Win64EH::UnwindInfo Struct Reference
llvm::Win64EH::UnwindInfo Struct Reference
UnwindInfo - An entry in the exception table.
#include "llvm/Support/Win64EH.h"
Public Member Functions
uint8_t getVersion () const
uint8_t getFlags () const
uint8_t getFrameRegister () const
uint8_t getFrameOffset () const
void * getLanguageSpecificData ()
Return pointer to language specific data part of UnwindInfo.
const void * getLanguageSpecificData () const
Return pointer to language specific data part of UnwindInfo.
uint32_t getLanguageSpecificHandlerOffset () const
Return image-relative offset of language-specific exception handler.
void setLanguageSpecificHandlerOffset (uint32_t offset)
Set image-relative offset of language-specific exception handler.
void * getExceptionData ()
Return pointer to exception-specific data.
RuntimeFunction * getChainedFunctionEntry ()
Return pointer to chained unwind info.
const RuntimeFunction * getChainedFunctionEntry () const
Return pointer to chained unwind info.
Public Attributes
uint8_t VersionAndFlags
uint8_t PrologSize
uint8_t NumCodes
uint8_t FrameRegisterAndOffset
UnwindCode UnwindCodes [1]
Detailed Description
UnwindInfo - An entry in the exception table.
Definition at line 100 of file Win64EH.h.
Member Function Documentation
getChainedFunctionEntry() [1/2]
RuntimeFunction * llvm::Win64EH::UnwindInfo::getChainedFunctionEntry () inline
Return pointer to chained unwind info.
Definition at line 157 of file Win64EH.h.
References getLanguageSpecificData().
getChainedFunctionEntry() [2/2]
const RuntimeFunction * llvm::Win64EH::UnwindInfo::getChainedFunctionEntry () const inline
Return pointer to chained unwind info.
Definition at line 162 of file Win64EH.h.
References getLanguageSpecificData().
getExceptionData()
void * llvm::Win64EH::UnwindInfo::getExceptionData () inline
Return pointer to exception-specific data.
Definition at line 151 of file Win64EH.h.
References getLanguageSpecificData().
getFlags()
uint8_t llvm::Win64EH::UnwindInfo::getFlags () const inline
Definition at line 110 of file Win64EH.h.
References VersionAndFlags.
getFrameOffset()
uint8_t llvm::Win64EH::UnwindInfo::getFrameOffset () const inline
Definition at line 116 of file Win64EH.h.
References FrameRegisterAndOffset.
getFrameRegister()
uint8_t llvm::Win64EH::UnwindInfo::getFrameRegister () const inline
Definition at line 113 of file Win64EH.h.
References FrameRegisterAndOffset.
getLanguageSpecificData() [1/2]
void * llvm::Win64EH::UnwindInfo::getLanguageSpecificData () inline
Return pointer to language specific data part of UnwindInfo.
Definition at line 129 of file Win64EH.h.
References NumCodes, and UnwindCodes.
Referenced by getChainedFunctionEntry(), getChainedFunctionEntry(), getExceptionData(), getLanguageSpecificHandlerOffset(), and setLanguageSpecificHandlerOffset().
getLanguageSpecificData() [2/2]
const void * llvm::Win64EH::UnwindInfo::getLanguageSpecificData () const inline
Return pointer to language specific data part of UnwindInfo.
Definition at line 134 of file Win64EH.h.
References NumCodes, and UnwindCodes.
getLanguageSpecificHandlerOffset()
uint32_t llvm::Win64EH::UnwindInfo::getLanguageSpecificHandlerOffset () const inline
Return image-relative offset of language-specific exception handler.
Definition at line 139 of file Win64EH.h.
References getLanguageSpecificData().
getVersion()
uint8_t llvm::Win64EH::UnwindInfo::getVersion () const inline
Definition at line 107 of file Win64EH.h.
References VersionAndFlags.
setLanguageSpecificHandlerOffset()
void llvm::Win64EH::UnwindInfo::setLanguageSpecificHandlerOffset (uint32_t offset) inline
Set image-relative offset of language-specific exception handler.
Definition at line 145 of file Win64EH.h.
References getLanguageSpecificData().
Member Data Documentation
FrameRegisterAndOffset
uint8_t llvm::Win64EH::UnwindInfo::FrameRegisterAndOffset
Definition at line 104 of file Win64EH.h.
Referenced by getFrameOffset(), and getFrameRegister().
NumCodes
uint8_t llvm::Win64EH::UnwindInfo::NumCodes
Definition at line 103 of file Win64EH.h.
Referenced by getLanguageSpecificData(), and getLanguageSpecificData().
PrologSize
uint8_t llvm::Win64EH::UnwindInfo::PrologSize
Definition at line 102 of file Win64EH.h.
UnwindCodes
UnwindCode llvm::Win64EH::UnwindInfo::UnwindCodes[1]
Definition at line 105 of file Win64EH.h.
Referenced by getLanguageSpecificData(), and getLanguageSpecificData().
VersionAndFlags
uint8_t llvm::Win64EH::UnwindInfo::VersionAndFlags
Definition at line 101 of file Win64EH.h.
Referenced by getFlags(), and getVersion().
The documentation for this struct was generated from the following file:
include/llvm/Support/Win64EH.h