LLVM: llvm::object::coff_tls_directory< IntTy > Struct Template Reference
llvm::object::coff_tls_directory< IntTy > Struct Template Reference
#include "llvm/Object/COFF.h"
Public Member Functions
uint32_t getAlignment () const
void setAlignment (uint32_t Align)
Public Attributes
IntTy StartAddressOfRawData
IntTy EndAddressOfRawData
IntTy AddressOfIndex
IntTy AddressOfCallBacks
support::ulittle32_t SizeOfZeroFill
support::ulittle32_t Characteristics
Detailed Description
template<typename IntTy>
struct llvm::object::coff_tls_directory< IntTy >
Definition at line 569 of file COFF.h.
Member Function Documentation
getAlignment()
template<typename IntTy > uint32_t llvm::object::coff_tls_directory< IntTy >::getAlignment () const inline
Definition at line 577 of file COFF.h.
References llvm::object::coff_tls_directory< IntTy >::Characteristics, and llvm::COFF::IMAGE_SCN_ALIGN_MASK.
setAlignment()
template<typename IntTy > void llvm::object::coff_tls_directory< IntTy >::setAlignment (uint32_t Align) inline
Definition at line 585 of file COFF.h.
References assert(), llvm::object::coff_tls_directory< IntTy >::Characteristics, llvm::isPowerOf2_32(), and llvm::Log2_32().
Member Data Documentation
AddressOfCallBacks
template<typename IntTy > IntTy llvm::object::coff_tls_directory< IntTy >::AddressOfCallBacks
Definition at line 573 of file COFF.h.
AddressOfIndex
template<typename IntTy > IntTy llvm::object::coff_tls_directory< IntTy >::AddressOfIndex
Definition at line 572 of file COFF.h.
Characteristics
template<typename IntTy > support::ulittle32_t llvm::object::coff_tls_directory< IntTy >::Characteristics
Definition at line 575 of file COFF.h.
Referenced by llvm::object::coff_tls_directory< IntTy >::getAlignment(), and llvm::object::coff_tls_directory< IntTy >::setAlignment().
EndAddressOfRawData
template<typename IntTy > IntTy llvm::object::coff_tls_directory< IntTy >::EndAddressOfRawData
Definition at line 571 of file COFF.h.
SizeOfZeroFill
template<typename IntTy > support::ulittle32_t llvm::object::coff_tls_directory< IntTy >::SizeOfZeroFill
Definition at line 574 of file COFF.h.
StartAddressOfRawData
template<typename IntTy > IntTy llvm::object::coff_tls_directory< IntTy >::StartAddressOfRawData
Definition at line 570 of file COFF.h.
The documentation for this struct was generated from the following file:
include/llvm/Object/COFF.h