LLVM: llvm::rdf::NodeAddr< T > Struct Template Reference
llvm::rdf::NodeAddr< T > Struct Template Reference
#include "llvm/CodeGen/RDFGraph.h"
Public Member Functions
NodeAddr ()=default
NodeAddr (T A, NodeId I)
template<typename S >
NodeAddr (const NodeAddr< S > &NA)
bool operator== (const NodeAddr< T > &NA) const
bool operator!= (const NodeAddr< T > &NA) const
Public Attributes
T Addr = nullptr
NodeId Id = 0
Detailed Description
template<typename T>
struct llvm::rdf::NodeAddr< T >
Definition at line 334 of file RDFGraph.h.
Constructor & Destructor Documentation
NodeAddr() [1/3]
template<typename T > llvm::rdf::NodeAddr< T >::NodeAddr () default
NodeAddr() [2/3]
template<typename T > llvm::rdf::NodeAddr< T >::NodeAddr (T A, NodeId I) inline
Definition at line 336 of file RDFGraph.h.
NodeAddr() [3/3]
template<typename T > template<typename S > llvm::rdf::NodeAddr< T >::NodeAddr (const NodeAddr< S > & NA) inline
Definition at line 340 of file RDFGraph.h.
Member Function Documentation
operator!=()
template<typename T > bool llvm::rdf::NodeAddr< T >::operator!= (const NodeAddr< T > & NA) const inline
Definition at line 347 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::operator==().
operator==()
template<typename T > bool llvm::rdf::NodeAddr< T >::operator== (const NodeAddr< T > & NA) const inline
Definition at line 343 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, assert(), and llvm::rdf::NodeAddr< T >::Id.
Referenced by llvm::rdf::NodeAddr< T >::operator!=().
Member Data Documentation
Addr
template<typename T > T llvm::rdf::NodeAddr< T >::Addr = nullptr
Definition at line 351 of file RDFGraph.h.
Referenced by llvm::rdf::NodeAddr< T >::operator==().
Id
template<typename T > NodeId llvm::rdf::NodeAddr< T >::Id = 0
Definition at line 352 of file RDFGraph.h.
Referenced by llvm::rdf::NodeAddr< T >::operator==().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/RDFGraph.h