LLVM: llvm::PreservedCFGCheckerInstrumentation::BBGuard Struct Reference
llvm::PreservedCFGCheckerInstrumentation::BBGuard Struct Reference final
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
BBGuard (const BasicBlock *BB)
void deleted () override
Callback for Value destruction.
void allUsesReplacedWith (Value *) override
Callback for Value RAUW.
bool isPoisoned () const
Public Member Functions inherited from llvm::CallbackVH
CallbackVH ()
CallbackVH (Value *P)
CallbackVH (const Value *P)
operator Value * () const
Public Member Functions inherited from llvm::ValueHandleBase
ValueHandleBase (HandleBaseKind Kind)
ValueHandleBase (HandleBaseKind Kind, Value *V)
~ValueHandleBase ()
Value * operator= (Value *RHS)
Value * operator= (const ValueHandleBase &RHS)
Value * operator-> () const
Value & operator* () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::ValueHandleBase
static void ValueIsDeleted (Value *V)
static void ValueIsRAUWd (Value *Old, Value *New)
Protected Types inherited from llvm::ValueHandleBase
enum HandleBaseKind { Assert , Callback , Weak , WeakTracking }
This indicates what sub class the handle actually is.
Protected Member Functions inherited from llvm::CallbackVH
~CallbackVH ()=default
CallbackVH (const CallbackVH &)=default
CallbackVH & operator= (const CallbackVH &)=default
void setValPtr (Value *P)
Protected Member Functions inherited from llvm::ValueHandleBase
ValueHandleBase (const ValueHandleBase &RHS)
ValueHandleBase (HandleBaseKind Kind, const ValueHandleBase &RHS)
Value * getValPtr () const
void RemoveFromUseList ()
Remove this ValueHandle from its current use list.
void clearValPtr ()
Clear the underlying pointer without clearing the use list.
Static Protected Member Functions inherited from llvm::ValueHandleBase
static bool isValid (Value *V)
Detailed Description
Definition at line 110 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
BBGuard()
llvm::PreservedCFGCheckerInstrumentation::BBGuard::BBGuard (const BasicBlock * BB) inline
Definition at line 111 of file StandardInstrumentations.h.
Member Function Documentation
allUsesReplacedWith()
void llvm::PreservedCFGCheckerInstrumentation::BBGuard::allUsesReplacedWith (Value *) inline override virtual
Callback for Value RAUW.
Called when this->getValPtr()->replaceAllUsesWith(new_value) is called, before any of the uses have actually been replaced. If WeakTrackingVH were implemented as a CallbackVH, it would use this method to call setValPtr(new_value). AssertingVH would do nothing in this method.
Reimplemented from llvm::CallbackVH.
Definition at line 113 of file StandardInstrumentations.h.
References llvm::CallbackVH::deleted().
deleted()
void llvm::PreservedCFGCheckerInstrumentation::BBGuard::deleted () inline override virtual
Callback for Value destruction.
Called when this->getValPtr() is destroyed, inside ~Value(), so you may call any non-virtual Value method on getValPtr(), but no subclass methods. If WeakTrackingVH were implemented as a CallbackVH, it would use this method to call setValPtr(NULL). AssertingVH would use this method to cause an assertion failure.
All implementations must remove the reference from this object to the Value that's being destroyed.
Reimplemented from llvm::CallbackVH.
Definition at line 112 of file StandardInstrumentations.h.
References llvm::CallbackVH::deleted().
isPoisoned()
bool llvm::PreservedCFGCheckerInstrumentation::BBGuard::isPoisoned () const inline
Definition at line 114 of file StandardInstrumentations.h.
References llvm::ValueHandleBase::getValPtr().
The documentation for this struct was generated from the following file:
include/llvm/Passes/StandardInstrumentations.h