LLVM: lib/Target/SystemZ/SystemZMachineScheduler.cpp File Reference
SystemZMachineScheduler.cpp File Reference
#include "SystemZMachineScheduler.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
Macros
#define DEBUG_TYPE "machine-scheduler"
Functions
static MachineBasicBlock * getSingleSchedPred (MachineBasicBlock *MBB, const MachineLoop *Loop)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-scheduler"
Definition at line 22 of file SystemZMachineScheduler.cpp.
Function Documentation
getSingleSchedPred()
static MachineBasicBlock * getSingleSchedPred (MachineBasicBlock * MBB, const MachineLoop * Loop) static
Definition at line 40 of file SystemZMachineScheduler.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::LoopBase< BlockT, LoopT >::getHeader(), MBB, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_size(), and llvm::MachineBasicBlock::predecessors().
Referenced by llvm::SystemZPostRASchedStrategy::enterMBB().