LLVM: lib/Target/X86/X86FastTileConfig.cpp File Reference
X86FastTileConfig.cpp File Reference
#include "X86.h"
#include "X86InstrBuilder.h"
#include "X86MachineFunctionInfo.h"
#include "X86RegisterInfo.h"
#include "X86Subtarget.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/InitializePasses.h"
Macros
#define DEBUG_TYPE "fasttileconfig"
Functions
INITIALIZE_PASS_BEGIN (X86FastTileConfig, DEBUG_TYPE, "Fast Tile Register Configure", false, false) INITIALIZE_PASS_END(X86FastTileConfig
Fast Tile Register static false bool isTilePhysReg (MachineOperand &Op)
static unsigned getTilePhysRegIdx (MachineOperand *Op)
static void adjustRowCfg (unsigned TIdx, MachineInstr *MI)
static void adjustColCfg (unsigned TIdx, MachineInstr *MI)
Variables
DEBUG_TYPE
Fast Tile Register Configure
Fast Tile Register false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "fasttileconfig"
Definition at line 36 of file X86FastTileConfig.cpp.
Function Documentation
adjustColCfg()
static void adjustColCfg (unsigned TIdx, MachineInstr * MI) inline static
Definition at line 118 of file X86FastTileConfig.cpp.
References MI, and Offset.
adjustRowCfg()
static void adjustRowCfg (unsigned TIdx, MachineInstr * MI) inline static
Definition at line 113 of file X86FastTileConfig.cpp.
References MI, and Offset.
getTilePhysRegIdx()
static unsigned getTilePhysRegIdx (MachineOperand * Op) static
Definition at line 108 of file X86FastTileConfig.cpp.
References assert(), and isTilePhysReg().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (X86FastTileConfig , DEBUG_TYPE , "Fast Tile Register Configure" , false , false)
isTilePhysReg()
Fast Tile Register static false bool isTilePhysReg (MachineOperand & Op) static
Definition at line 98 of file X86FastTileConfig.cpp.
Referenced by getTilePhysRegIdx().
Variable Documentation
Configure
Fast Tile Register Configure
Definition at line 96 of file X86FastTileConfig.cpp.
DEBUG_TYPE
DEBUG_TYPE
Definition at line 95 of file X86FastTileConfig.cpp.
false
Fast Tile Register false
Definition at line 96 of file X86FastTileConfig.cpp.