LLVM: lib/Target/ARM/TargetInfo/ARMTargetInfo.cpp File Reference
ARMTargetInfo.cpp File Reference
#include "TargetInfo/ARMTargetInfo.h"
#include "llvm/Support/TargetRegistry.h"
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARMTargetInfo ()
Function Documentation
LLVMInitializeARMTargetInfo()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeARMTargetInfo ()
Definition at line 30 of file ARMTargetInfo.cpp.
References A, llvm::Triple::arm, llvm::Triple::armeb, B, llvm::getTheARMBETarget(), llvm::getTheARMLETarget(), llvm::getTheThumbBETarget(), llvm::getTheThumbLETarget(), llvm::Triple::thumb, llvm::Triple::thumbeb, X, and Y.