LLVM: lib/CodeGen/CalcSpillWeights.cpp File Reference
CalcSpillWeights.cpp File Reference
#include "llvm/CodeGen/CalcSpillWeights.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/CodeGen/LiveInterval.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <tuple>
Macros
#define DEBUG_TYPE "calcspillweights"
Functions
static Register copyHint (const MachineInstr *MI, unsigned Reg, const TargetRegisterInfo &TRI, const MachineRegisterInfo &MRI)
static bool isRematerializable (const LiveInterval &LI, const LiveIntervals &LIS, const VirtRegMap &VRM, const TargetInstrInfo &TII)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "calcspillweights"
Definition at line 29 of file CalcSpillWeights.cpp.
Function Documentation
copyHint()
static Register copyHint (const MachineInstr * MI, unsigned Reg, const TargetRegisterInfo & TRI, const MachineRegisterInfo & MRI) static
Definition at line 45 of file CalcSpillWeights.cpp.
References llvm::Register::isVirtualRegister(), MI, MRI, rc, Register, and TRI.
Referenced by llvm::VirtRegAuxInfo::weightCalcHelper().
isRematerializable()
static bool isRematerializable (const LiveInterval & LI, const LiveIntervals & LIS, const VirtRegMap & VRM, const TargetInstrInfo & TII) static
Definition at line 79 of file CalcSpillWeights.cpp.
References assert(), E, llvm::LiveIntervals::getAliasAnalysis(), llvm::LiveIntervals::getInstructionFromIndex(), llvm::LiveIntervals::getInterval(), llvm::VirtRegMap::getOriginal(), I, llvm::Register::isVirtualRegister(), MI, llvm::LiveInterval::reg(), TII, llvm::LiveRange::vni_begin(), and llvm::LiveRange::vni_end().
Referenced by llvm::VirtRegAuxInfo::weightCalcHelper().