LLVM: llvm::WebAssemblyTargetStreamer Class Reference
llvm::WebAssemblyTargetStreamer Class Reference abstract
WebAssembly-specific streamer interface, to implement support WebAssembly-specific assembly directives.
#include "Target/WebAssembly/MCTargetDesc/WebAssemblyTargetStreamer.h"
Public Member Functions
WebAssemblyTargetStreamer (MCStreamer &S)
virtual void emitLocal (ArrayRef< wasm::ValType > Types)=0
.local
virtual void emitEndFunc ()=0
.endfunc
virtual void emitFunctionType (const MCSymbolWasm *Sym)=0
.functype
virtual void emitIndIdx (const MCExpr *Value)=0
.indidx
virtual void emitGlobalType (const MCSymbolWasm *Sym)=0
.globaltype
virtual void emitTableType (const MCSymbolWasm *Sym)=0
.tabletype
virtual void emitEventType (const MCSymbolWasm *Sym)=0
.eventtype
virtual void emitImportModule (const MCSymbolWasm *Sym, StringRef ImportModule)=0
.import_module
virtual void emitImportName (const MCSymbolWasm *Sym, StringRef ImportName)=0
.import_name
virtual void emitExportName (const MCSymbolWasm *Sym, StringRef ExportName)=0
.export_name
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void finish ()
Protected Member Functions
void emitValueType (wasm::ValType Type)
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
WebAssembly-specific streamer interface, to implement support WebAssembly-specific assembly directives.
Definition at line 28 of file WebAssemblyTargetStreamer.h.
Constructor & Destructor Documentation
WebAssemblyTargetStreamer()
WebAssemblyTargetStreamer::WebAssemblyTargetStreamer (MCStreamer & S) explicit
Definition at line 27 of file WebAssemblyTargetStreamer.cpp.
Member Function Documentation
emitEndFunc()
virtual void llvm::WebAssemblyTargetStreamer::emitEndFunc () pure virtual
.endfunc
Implemented in llvm::WebAssemblyTargetAsmStreamer, llvm::WebAssemblyTargetWasmStreamer, and llvm::WebAssemblyTargetNullStreamer.
emitEventType()
virtual void llvm::WebAssemblyTargetStreamer::emitEventType (const MCSymbolWasm * Sym) pure virtual
.eventtype
Implemented in llvm::WebAssemblyTargetNullStreamer, llvm::WebAssemblyTargetAsmStreamer, and llvm::WebAssemblyTargetWasmStreamer.
Referenced by llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile().
emitExportName()
virtual void llvm::WebAssemblyTargetStreamer::emitExportName (const MCSymbolWasm * Sym, StringRef ExportName) pure virtual
.export_name
Implemented in llvm::WebAssemblyTargetNullStreamer, llvm::WebAssemblyTargetAsmStreamer, and llvm::WebAssemblyTargetWasmStreamer.
Referenced by llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile().
emitFunctionType()
virtual void llvm::WebAssemblyTargetStreamer::emitFunctionType (const MCSymbolWasm * Sym) pure virtual
.functype
Implemented in llvm::WebAssemblyTargetNullStreamer, llvm::WebAssemblyTargetAsmStreamer, and llvm::WebAssemblyTargetWasmStreamer.
Referenced by llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile(), and llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart().
emitGlobalType()
virtual void llvm::WebAssemblyTargetStreamer::emitGlobalType (const MCSymbolWasm * Sym) pure virtual
.globaltype
Implemented in llvm::WebAssemblyTargetNullStreamer, llvm::WebAssemblyTargetAsmStreamer, and llvm::WebAssemblyTargetWasmStreamer.
Referenced by llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile().
emitImportModule()
virtual void llvm::WebAssemblyTargetStreamer::emitImportModule (const MCSymbolWasm * Sym, StringRef ImportModule) pure virtual
.import_module
Implemented in llvm::WebAssemblyTargetNullStreamer, llvm::WebAssemblyTargetAsmStreamer, and llvm::WebAssemblyTargetWasmStreamer.
Referenced by llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile().
emitImportName()
virtual void llvm::WebAssemblyTargetStreamer::emitImportName (const MCSymbolWasm * Sym, StringRef ImportName) pure virtual
.import_name
Implemented in llvm::WebAssemblyTargetNullStreamer, llvm::WebAssemblyTargetAsmStreamer, and llvm::WebAssemblyTargetWasmStreamer.
Referenced by llvm::WebAssemblyAsmPrinter::emitEndOfAsmFile().
emitIndIdx()
virtual void llvm::WebAssemblyTargetStreamer::emitIndIdx (const MCExpr * Value) pure virtual
.indidx
Implemented in llvm::WebAssemblyTargetNullStreamer, llvm::WebAssemblyTargetAsmStreamer, and llvm::WebAssemblyTargetWasmStreamer.
Referenced by llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart().
emitLocal()
virtual void llvm::WebAssemblyTargetStreamer::emitLocal (ArrayRef< wasm::ValType > Types) pure virtual
.local
Implemented in llvm::WebAssemblyTargetAsmStreamer, llvm::WebAssemblyTargetWasmStreamer, and llvm::WebAssemblyTargetNullStreamer.
Referenced by llvm::WebAssemblyAsmPrinter::emitFunctionBodyStart().
emitTableType()
virtual void llvm::WebAssemblyTargetStreamer::emitTableType (const MCSymbolWasm * Sym) pure virtual
.tabletype
Implemented in llvm::WebAssemblyTargetNullStreamer, llvm::WebAssemblyTargetAsmStreamer, and llvm::WebAssemblyTargetWasmStreamer.
emitValueType()
void WebAssemblyTargetStreamer::emitValueType (wasm::ValType Type) protected
Definition at line 30 of file WebAssemblyTargetStreamer.cpp.
References llvm::MCStreamer::emitIntValue(), and llvm::MCTargetStreamer::Streamer.
Referenced by llvm::WebAssemblyTargetWasmStreamer::emitLocal().
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/MCTargetDesc/WebAssemblyTargetStreamer.h
lib/Target/WebAssembly/MCTargetDesc/WebAssemblyTargetStreamer.cpp