LLVM: llvm::AliasSetTracker Class Reference
llvm::AliasSetTracker Class Reference
#include "llvm/Analysis/AliasSetTracker.h"
Public Types
using iterator = ilist<AliasSet>::iterator
using const_iterator = ilist<AliasSet>::const_iterator
Public Member Functions
AliasSetTracker (AAResults &AA)
Create an empty collection of AliasSets, and use the specified alias analysis object to disambiguate load and store addresses.
AliasSetTracker (AAResults &AA, MemorySSA *MSSA, Loop *L)
~AliasSetTracker ()
void add (Value *Ptr, LocationSize Size, const AAMDNodes &AAInfo)
These methods are used to add different types of instructions to the alias sets.
void add (LoadInst *LI)
void add (StoreInst *SI)
void add (VAArgInst *VAAI)
void add (AnyMemSetInst *MSI)
void add (AnyMemTransferInst *MTI)
void add (Instruction *I)
void add (BasicBlock &BB)
void add (const AliasSetTracker &AST)
void addUnknown (Instruction *I)
void addAllInstructionsInLoopUsingMSSA ()
void clear ()
const ilist< AliasSet > & getAliasSets () const
Return the alias sets that are active.
AliasSet & getAliasSetFor (const MemoryLocation &MemLoc)
Return the alias set which contains the specified memory location.
AAResults & getAliasAnalysis () const
Return the underlying alias analysis object used by this tracker.
void deleteValue (Value *PtrVal)
This method is used to remove a pointer value from the AliasSetTracker entirely.
void copyValue (Value *From, Value *To)
This method should be used whenever a preexisting value in the program is copied or cloned, introducing a new value.
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
void print (raw_ostream &OS) const
void dump () const
Friends
class AliasSet
Detailed Description
Definition at line 327 of file AliasSetTracker.h.
Member Typedef Documentation
const_iterator
using llvm::AliasSetTracker::const_iterator = ilist<AliasSet>::const_iterator
Definition at line 415 of file AliasSetTracker.h.
iterator
using llvm::AliasSetTracker::iterator = ilist<AliasSet>::iterator
Definition at line 414 of file AliasSetTracker.h.
Constructor & Destructor Documentation
AliasSetTracker() [1/2]
llvm::AliasSetTracker::AliasSetTracker (AAResults & AA) inline explicit
Create an empty collection of AliasSets, and use the specified alias analysis object to disambiguate load and store addresses.
Definition at line 359 of file AliasSetTracker.h.
AliasSetTracker() [2/2]
llvm::AliasSetTracker::AliasSetTracker (AAResults & AA, MemorySSA * MSSA, Loop * L) inline explicit
Definition at line 360 of file AliasSetTracker.h.
~AliasSetTracker()
llvm::AliasSetTracker::~AliasSetTracker () inline
Definition at line 362 of file AliasSetTracker.h.
References clear().
Member Function Documentation
add() [1/9]
void AliasSetTracker::add (AnyMemSetInst * MSI)
Definition at line 420 of file AliasSetTracker.cpp.
References llvm::MemoryLocation::getForDest().
add() [2/9]
void AliasSetTracker::add (AnyMemTransferInst * MTI)
Definition at line 424 of file AliasSetTracker.cpp.
References llvm::MemoryLocation::getForDest(), and llvm::MemoryLocation::getForSource().
add() [3/9]
void AliasSetTracker::add (BasicBlock & BB)
Definition at line 513 of file AliasSetTracker.cpp.
References add(), and I.
add() [4/9]
void AliasSetTracker::add (const AliasSetTracker & AST)
Definition at line 518 of file AliasSetTracker.cpp.
References add(), assert(), llvm::AliasSet::begin(), E, and llvm::AliasSet::end().
add() [5/9]
void AliasSetTracker::add (Instruction * I)
Definition at line 458 of file AliasSetTracker.cpp.
References add(), addUnknown(), Arg, llvm::clearMod(), llvm::createModRefInfo(), llvm::enumerate(), llvm::AAResults::getArgModRefInfo(), llvm::MemoryLocation::getForArgument(), llvm::AAResults::getModRefBehavior(), I, llvm::intersectModRef(), llvm::isModSet(), llvm::isNoModRef(), llvm::isRefSet(), MRI, and SI.
add() [6/9]
void AliasSetTracker::add (LoadInst * LI)
Definition at line 404 of file AliasSetTracker.cpp.
References addUnknown(), llvm::MemoryLocation::get(), llvm::LoadInst::getOrdering(), and llvm::isStrongerThanMonotonic().
add() [7/9]
void AliasSetTracker::add (StoreInst * SI)
Definition at line 410 of file AliasSetTracker.cpp.
References addUnknown(), llvm::MemoryLocation::get(), llvm::isStrongerThanMonotonic(), and SI.
add() [8/9]
void AliasSetTracker::add (VAArgInst * VAAI)
Definition at line 416 of file AliasSetTracker.cpp.
References llvm::MemoryLocation::get().
add() [9/9]
void AliasSetTracker::add (Value * Ptr, LocationSize Size, const AAMDNodes & AAInfo)
These methods are used to add different types of instructions to the alias sets.
Adding a new instruction can result in one of three actions happening:
If the instruction doesn't alias any other sets, create a new set.
If the instruction aliases exactly one set, add it to the set
If the instruction aliases multiple sets, merge the sets, and add the instruction to the result.
These methods return true if inserting the instruction resulted in the addition of a new alias set (i.e., the pointer did not alias anything).
Definition at line 399 of file AliasSetTracker.cpp.
References Size.
Referenced by add(), add(), add(), addAllInstructionsInLoopUsingMSSA(), and computeAliasSet().
addAllInstructionsInLoopUsingMSSA()
void AliasSetTracker::addAllInstructionsInLoopUsingMSSA ()
Definition at line 542 of file AliasSetTracker.cpp.
References add(), assert(), llvm::LoopBase< BlockT, LoopT >::blocks(), and llvm::MemorySSA::getBlockAccesses().
addUnknown()
void AliasSetTracker::addUnknown (Instruction * I)
Definition at line 429 of file AliasSetTracker.cpp.
References AliasSet, and llvm::Instruction::mayReadOrWriteMemory().
Referenced by add(), add(), and add().
begin() [1/2]
iterator llvm::AliasSetTracker::begin () inline
Definition at line 420 of file AliasSetTracker.h.
begin() [2/2]
const_iterator llvm::AliasSetTracker::begin () const inline
Definition at line 417 of file AliasSetTracker.h.
Referenced by llvm::canSinkOrHoistInst().
clear()
void AliasSetTracker::clear ()
Definition at line 284 of file AliasSetTracker.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and I.
Referenced by ~AliasSetTracker().
copyValue()
void AliasSetTracker::copyValue (Value * From, Value * To)
This method should be used whenever a preexisting value in the program is copied or cloned, introducing a new value.
Note that it is ok for clients that use this method to introduce the same value multiple times: if the tracker already knows about a value, it will ignore the request.
Definition at line 584 of file AliasSetTracker.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as(), From, and I.
Referenced by llvm::hoistRegion().
deleteValue()
void AliasSetTracker::deleteValue (Value * PtrVal)
This method is used to remove a pointer value from the AliasSetTracker entirely.
It should be used when an instruction is deleted from the program to update the AST. If you don't use this, you would have dangling pointers to deleted instructions.
Definition at line 556 of file AliasSetTracker.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as(), and I.
Referenced by eraseInstruction().
dump()
LLVM_DUMP_METHOD void AliasSetTracker::dump () const
Definition at line 710 of file AliasSetTracker.cpp.
References llvm::dbgs(), and print().
end() [1/2]
iterator llvm::AliasSetTracker::end () inline
Definition at line 421 of file AliasSetTracker.h.
end() [2/2]
const_iterator llvm::AliasSetTracker::end () const inline
Definition at line 418 of file AliasSetTracker.h.
Referenced by llvm::canSinkOrHoistInst().
getAliasAnalysis()
AAResults & llvm::AliasSetTracker::getAliasAnalysis () const inline
Return the underlying alias analysis object used by this tracker.
Definition at line 400 of file AliasSetTracker.h.
Referenced by llvm::AliasSet::mergeSetIn().
getAliasSetFor()
AliasSet & AliasSetTracker::getAliasSetFor (const MemoryLocation & MemLoc)
Return the alias set which contains the specified memory location.
If the memory location aliases two or more existing alias sets, will have the effect of merging those alias sets before the single resulting alias set is returned.
Definition at line 348 of file AliasSetTracker.cpp.
References AliasSet, assert(), and Size.
Referenced by llvm::canSinkOrHoistInst(), and pointerInvalidatedByLoop().
getAliasSets()
const ilist< AliasSet > & llvm::AliasSetTracker::getAliasSets () const inline
Return the alias sets that are active.
Definition at line 391 of file AliasSetTracker.h.
print()
void AliasSetTracker::print (raw_ostream & OS) const
Definition at line 698 of file AliasSetTracker.cpp.
References llvm::AliasSet::print(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size().
Referenced by dump(), and llvm::operator<<().
Friends And Related Symbol Documentation
AliasSet
friend class AliasSet friend
Definition at line 427 of file AliasSetTracker.h.
Referenced by addUnknown(), and getAliasSetFor().
The documentation for this class was generated from the following files:
include/llvm/Analysis/AliasSetTracker.h
lib/Analysis/AliasSetTracker.cpp