LLVM: llvm::IRSimilarityAnalysisPrinterPass Class Reference
llvm::IRSimilarityAnalysisPrinterPass Class Reference
Printer pass that uses IRSimilarityAnalysis.
#include "llvm/Analysis/IRSimilarityIdentifier.h"
Public Member Functions
IRSimilarityAnalysisPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< IRSimilarityAnalysisPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass that uses IRSimilarityAnalysis.
Definition at line 778 of file IRSimilarityIdentifier.h.
Constructor & Destructor Documentation
IRSimilarityAnalysisPrinterPass()
llvm::IRSimilarityAnalysisPrinterPass::IRSimilarityAnalysisPrinterPass (raw_ostream & OS) inline explicit
Definition at line 783 of file IRSimilarityIdentifier.h.
Member Function Documentation
run()
PreservedAnalyses IRSimilarityAnalysisPrinterPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 917 of file IRSimilarityIdentifier.cpp.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::IRSimilarity::IRSimilarityIdentifier::getSimilarity().
The documentation for this class was generated from the following files:
include/llvm/Analysis/IRSimilarityIdentifier.h
lib/Analysis/IRSimilarityIdentifier.cpp