LLVM: llvm::codeview::CodeViewRecordStreamer Class Reference
llvm::codeview::CodeViewRecordStreamer Class Reference abstract
#include "llvm/DebugInfo/CodeView/CodeViewRecordIO.h"
Public Member Functions
virtual void emitBytes (StringRef Data)=0
virtual void emitIntValue (uint64_t Value, unsigned Size)=0
virtual void emitBinaryData (StringRef Data)=0
virtual void AddComment (const Twine &T)=0
virtual void AddRawComment (const Twine &T)=0
virtual bool isVerboseAsm ()=0
virtual std::string getTypeName (TypeIndex TI)=0
virtual ~CodeViewRecordStreamer ()=default
Detailed Description
Definition at line 31 of file CodeViewRecordIO.h.
Constructor & Destructor Documentation
~CodeViewRecordStreamer()
virtual llvm::codeview::CodeViewRecordStreamer::~CodeViewRecordStreamer () virtual default
Member Function Documentation
AddComment()
virtual void llvm::codeview::CodeViewRecordStreamer::AddComment (const Twine & T) pure virtual
AddRawComment()
virtual void llvm::codeview::CodeViewRecordStreamer::AddRawComment (const Twine & T) pure virtual
Referenced by llvm::codeview::CodeViewRecordIO::emitRawComment().
emitBinaryData()
virtual void llvm::codeview::CodeViewRecordStreamer::emitBinaryData (StringRef Data) pure virtual
Referenced by llvm::codeview::CodeViewRecordIO::mapByteVectorTail().
emitBytes()
virtual void llvm::codeview::CodeViewRecordStreamer::emitBytes (StringRef Data) pure virtual
Referenced by llvm::codeview::CodeViewRecordIO::endRecord(), llvm::codeview::CodeViewRecordIO::mapGuid(), llvm::codeview::CodeViewRecordIO::mapObject(), and llvm::codeview::CodeViewRecordIO::mapStringZ().
emitIntValue()
virtual void llvm::codeview::CodeViewRecordStreamer::emitIntValue (uint64_t Value, unsigned Size) pure virtual
Referenced by llvm::codeview::CodeViewRecordIO::mapInteger(), llvm::codeview::CodeViewRecordIO::mapInteger(), and llvm::codeview::CodeViewRecordIO::mapVectorN().
getTypeName()
virtual std::string llvm::codeview::CodeViewRecordStreamer::getTypeName (TypeIndex TI) pure virtual
Referenced by llvm::codeview::CodeViewRecordIO::mapInteger().
isVerboseAsm()
virtual bool llvm::codeview::CodeViewRecordStreamer::isVerboseAsm () pure virtual
Referenced by llvm::codeview::CodeViewRecordIO::emitRawComment().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/CodeViewRecordIO.h