LLVM: llvm::VPReplicateRecipe Class Reference
llvm::VPReplicateRecipe Class Reference
VPReplicateRecipe replicates a given instruction producing multiple scalar copies of the original scalar type, one per lane, instead of producing a single copy of widened type for all lanes.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
template<typename IterT >
VPReplicateRecipe (Instruction *I, iterator_range< IterT > Operands, bool IsUniform, bool IsPredicated=false)
~VPReplicateRecipe () override=default
void execute (VPTransformState &State) override
Generate replicas of the desired Ingredient.
void setAlsoPack (bool Pack)
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the recipe.
bool isUniform () const
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC)
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
VPUser * toVPUser ()
Returns a pointer to a VPUser, if the recipe inherits from VPUser or nullptr otherwise.
Instruction * getUnderlyingInstr ()
Returns the underlying instruction, if the recipe is a VPValue or nullptr otherwise.
const Instruction * getUnderlyingInstr () const
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPValue (unsigned I=0)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I=0) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()
VPUser (ArrayRef< VPValue * > Operands)
VPUser (std::initializer_list< VPValue * > Operands)
template<typename IterT >
VPUser (iterator_range< IterT > Operands)
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
Public Member Functions inherited from llvm::VPValue
Value * getUnderlyingValue ()
Return the underlying Value attached to this VPValue.
const Value * getUnderlyingValue () const
VPValue (Value *UV=nullptr, VPDef *Def=nullptr)
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser ()
Returns true if the value has more than one unique user.
void replaceAllUsesWith (VPValue *New)
VPDef * getDef ()
Value * getLiveInIRValue ()
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
Static Public Member Functions
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPValue *V)
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::VPUser
static bool classof (const VPDef *Recipe)
Method to support type inquiry through isa, cast, and dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Types inherited from llvm::VPValue
enum {
VPValueSC , VPVInstructionSC , VPVMemoryInstructionSC , VPVReductionSC ,
VPVReplicateSC , VPVWidenSC , VPVWidenCallSC , VPVWidenGEPSC ,
VPVWidenSelectSC
}
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
Protected Member Functions inherited from llvm::VPValue
VPValue (const unsigned char SC, Value *UV=nullptr, VPDef *Def=nullptr)
void setUnderlyingValue (Value *Val)
Protected Attributes inherited from llvm::VPValue
Value * UnderlyingVal
VPDef * Def
Pointer to the VPDef that defines this VPValue.
Detailed Description
VPReplicateRecipe replicates a given instruction producing multiple scalar copies of the original scalar type, one per lane, instead of producing a single copy of widened type for all lanes.
If the instruction is known to be uniform only one copy, per lane zero, will be generated.
Definition at line 1181 of file VPlan.h.
Constructor & Destructor Documentation
VPReplicateRecipe()
template<typename IterT > llvm::VPReplicateRecipe::VPReplicateRecipe (Instruction * I, iterator_range< IterT > Operands, bool IsUniform, bool IsPredicated = false) inline
Definition at line 1193 of file VPlan.h.
References I, and Operands.
~VPReplicateRecipe()
llvm::VPReplicateRecipe::~VPReplicateRecipe () override default
Member Function Documentation
classof() [1/2]
static bool llvm::VPReplicateRecipe::classof (const VPDef * D) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 1209 of file VPlan.h.
References D, and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
classof() [2/2]
static bool llvm::VPReplicateRecipe::classof (const VPValue * V) inline static
Definition at line 1213 of file VPlan.h.
References llvm::VPValue::VPVReplicateSC.
execute()
void VPReplicateRecipe::execute (VPTransformState & State) override virtual
Generate replicas of the desired Ingredient.
Replicas will be generated for all parts and lanes unless a specific part and lane are specified in the State.
Implements llvm::VPRecipeBase.
Definition at line 9065 of file LoopVectorize.cpp.
References assert(), llvm::VectorType::get(), llvm::PoisonValue::get(), and getType().
isUniform()
bool llvm::VPReplicateRecipe::isUniform () const inline
Definition at line 1228 of file VPlan.h.
print()
void VPReplicateRecipe::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the recipe.
Implements llvm::VPDef.
Definition at line 955 of file VPlan.cpp.
References getOpcode(), llvm::Instruction::getOpcodeName(), llvm::Value::getType(), llvm::VPRecipeBase::getUnderlyingInstr(), llvm::Type::isVoidTy(), llvm::VPValue::printAsOperand(), and llvm::VPUser::printOperands().
setAlsoPack()
void llvm::VPReplicateRecipe::setAlsoPack (bool Pack) inline
Definition at line 1222 of file VPlan.h.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/LoopVectorize.cpp
lib/Transforms/Vectorize/VPlan.cpp