LLVM: llvm::CodeGenCoverage Class Reference
llvm::CodeGenCoverage Class Reference
#include "llvm/Support/CodeGenCoverage.h"
Public Types
using const_covered_iterator = BitVector::const_set_bits_iterator
Public Member Functions
CodeGenCoverage ()
void setCovered (uint64_t RuleID)
bool isCovered (uint64_t RuleID) const
iterator_range< const_covered_iterator > covered () const
bool parse (MemoryBuffer &Buffer, StringRef BackendName)
bool emit (StringRef FilePrefix, StringRef BackendName) const
void reset ()
Protected Attributes
BitVector RuleCoverage
Detailed Description
Definition at line 20 of file CodeGenCoverage.h.
Member Typedef Documentation
const_covered_iterator
using llvm::CodeGenCoverage::const_covered_iterator = BitVector::const_set_bits_iterator
Definition at line 25 of file CodeGenCoverage.h.
Constructor & Destructor Documentation
CodeGenCoverage()
CodeGenCoverage::CodeGenCoverage ()
Definition at line 26 of file CodeGenCoverage.cpp.
Member Function Documentation
covered()
iterator_range< CodeGenCoverage::const_covered_iterator > CodeGenCoverage::covered () const
Definition at line 41 of file CodeGenCoverage.cpp.
References RuleCoverage, and llvm::BitVector::set_bits().
Referenced by llvm::InstructionSelect::runOnMachineFunction().
emit()
bool CodeGenCoverage::emit (StringRef FilePrefix, StringRef BackendName) const
Definition at line 78 of file CodeGenCoverage.cpp.
References CoveragePrefix, llvm::BitVector::empty(), llvm::sys::Process::getProcessId(), I, llvm::Lock, llvm::sys::fs::OF_Append, OutputMutex, RuleCoverage, llvm::BitVector::set_bits(), and llvm::to_string().
Referenced by llvm::InstructionSelect::runOnMachineFunction().
isCovered()
bool CodeGenCoverage::isCovered (uint64_t RuleID) const
Definition at line 34 of file CodeGenCoverage.cpp.
References RuleCoverage, and llvm::BitVector::size().
parse()
bool CodeGenCoverage::parse (MemoryBuffer & Buffer, StringRef BackendName)
Definition at line 45 of file CodeGenCoverage.cpp.
References llvm::StringRef::equals(), llvm::MemoryBuffer::getBufferEnd(), llvm::MemoryBuffer::getBufferStart(), llvm::support::native, llvm::support::endian::read64(), and setCovered().
reset()
void CodeGenCoverage::reset ()
Definition at line 111 of file CodeGenCoverage.cpp.
References llvm::BitVector::resize(), and RuleCoverage.
setCovered()
void CodeGenCoverage::setCovered (uint64_t RuleID)
Definition at line 28 of file CodeGenCoverage.cpp.
References llvm::BitVector::resize(), RuleCoverage, and llvm::BitVector::size().
Referenced by llvm::InstructionSelector::executeMatchTable(), and parse().
Member Data Documentation
RuleCoverage
BitVector llvm::CodeGenCoverage::RuleCoverage protected
Definition at line 22 of file CodeGenCoverage.h.
Referenced by covered(), emit(), isCovered(), reset(), and setCovered().
The documentation for this class was generated from the following files:
include/llvm/Support/CodeGenCoverage.h
lib/Support/CodeGenCoverage.cpp