LLVM: llvm::WebAssemblyAsmPrinter Class Reference
llvm::WebAssemblyAsmPrinter Class Reference final
#include "Target/WebAssembly/WebAssemblyAsmPrinter.h"
Public Member Functions
WebAssemblyAsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
const WebAssemblySubtarget & getSubtarget () const
void addSignature (std::unique_ptr< wasm::WasmSignature > &&Sig)
bool runOnMachineFunction (MachineFunction &MF) override
Emit the specified function out to the OutStreamer.
void emitEndOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the end of their file.
void EmitProducerInfo (Module &M)
void EmitTargetFeatures (Module &M)
void emitJumpTableInfo () override
Print assembly representations of the jump tables used by the current function to the current output stream.
void emitConstantPool () override
Print to the current output stream assembly representations of the constants in the constant pool MCP.
void emitFunctionBodyStart () override
Targets can override this to emit stuff before the first basic block in the function.
void emitInstruction (const MachineInstr *MI) override
Targets should implement this to emit instructions.
bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, const char *ExtraCode, raw_ostream &OS) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNo, const char *ExtraCode, raw_ostream &OS) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
MVT getRegType (unsigned RegNo) const
std::string regToString (const MachineOperand &MO)
WebAssemblyTargetStreamer * getTargetStreamer ()
MCSymbolWasm * getMCSymbolForFunction (const Function *F, bool EnableEmEH, wasm::WasmSignature *Sig, bool &InvokeDetected)
Public Member Functions inherited from llvm::AsmPrinter
~AsmPrinter () override
DwarfDebug * getDwarfDebug ()
DwarfDebug * getDwarfDebug () const
uint16_t getDwarfVersion () const
void setDwarfVersion (uint16_t Version)
bool isDwarf64 () const
unsigned int getDwarfOffsetByteSize () const
Returns 4 for DWARF32 and 8 for DWARF64.
unsigned int getUnitLengthFieldByteSize () const
Returns 4 for DWARF32 and 12 for DWARF64.
bool isPositionIndependent () const
bool isVerbose () const
Return true if assembly output should contain comments.
unsigned getFunctionNumber () const
Return a unique ID for the current function.
virtual const MCSymbol * getFunctionFrameSymbol () const
Return symbol for the function pseudo stack if the stack frame is not a register based.
MCSymbol * getFunctionBegin () const
MCSymbol * getFunctionEnd () const
MCSymbol * getMBBExceptionSym (const MachineBasicBlock &MBB)
const TargetLoweringObjectFile & getObjFileLowering () const
Return information about object file lowering.
const DataLayout & getDataLayout () const
Return information about data layout.
unsigned getPointerSize () const
Return the pointer size from the TargetMachine.
const MCSubtargetInfo & getSubtargetInfo () const
Return information about subtarget.
void EmitToStreamer (MCStreamer &S, const MCInst &Inst)
void emitInitialRawDwarfLocDirective (const MachineFunction &MF)
Emits inital debug location directive.
const MCSection * getCurrentSection () const
Return the current section we are emitting to.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV) const
MCSymbol * getSymbol (const GlobalValue *GV) const
MCSymbol * getSymbolPreferLocal (const GlobalValue &GV) const
Similar to getSymbol() but preferred for references.
void recordSled (MCSymbol *Sled, const MachineInstr &MI, SledKind Kind, uint8_t Version=0)
void emitXRayTable ()
Emit a table with all XRay instrumentation points.
void emitPatchableFunctionEntries ()
void getAnalysisUsage (AnalysisUsage &AU) const override
Record analysis usage.
bool doInitialization (Module &M) override
Set up the AsmPrinter when we are working on a new module.
bool doFinalization (Module &M) override
Shut down the asmprinter.
virtual void SetupMachineFunction (MachineFunction &MF)
This should be called when a new MachineFunction is being processed from runOnMachineFunction.
void emitFunctionBody ()
This method emits the body and trailer for a function.
void emitCFIInstruction (const MachineInstr &MI)
void emitFrameAlloc (const MachineInstr &MI)
void emitStackSizeSection (const MachineFunction &MF)
void emitBBAddrMapSection (const MachineFunction &MF)
void emitPseudoProbe (const MachineInstr &MI)
void emitRemarksSection (remarks::RemarkStreamer &RS)
CFIMoveType needsCFIMoves () const
bool needsOnlyDebugCFIMoves () const
Returns false if needsCFIMoves() == CFI_M_EH for any function in the module.
bool needsSEHMoves ()
virtual void emitGlobalVariable (const GlobalVariable *GV)
Emit the specified global variable to the .s file.
bool emitSpecialLLVMGlobal (const GlobalVariable *GV)
Check to see if the specified global is a special global used by LLVM.
void preprocessXXStructorList (const DataLayout &DL, const Constant *List, SmallVector< Structor, 8 > &Structors)
This method gathers an array of Structors and then sorts them out by Priority.
virtual void emitXXStructorList (const DataLayout &DL, const Constant *List, bool IsCtor)
This method emits llvm.global_ctors or llvm.global_dtors list.
void emitAlignment (Align Alignment, const GlobalObject *GV=nullptr) const
Emit an alignment directive to the specified power of two boundary.
virtual const MCExpr * lowerConstant (const Constant *CV)
Lower the specified LLVM Constant to an MCExpr.
void emitGlobalConstant (const DataLayout &DL, const Constant *CV)
Print a general LLVM constant to the .s file.
void computeGlobalGOTEquivs (Module &M)
Unnamed constant global variables solely contaning a pointer to another globals variable act like a global variable "proxy", or GOT equivalents, i.e., it's only used to hold the address of the latter.
void emitGlobalGOTEquivs ()
Constant expressions using GOT equivalent globals may not be eligible for PC relative GOT entry conversion, in such cases we need to emit the proxies we previously omitted in EmitGlobalVariable.
void emitStackMaps (StackMaps &SM)
Emit the stack maps.
void addAsmPrinterHandler (HandlerInfo Handler)
virtual void emitStartOfAsmFile (Module &)
This virtual method can be overridden by targets that want to emit something at the start of their file.
virtual void emitFunctionBodyEnd ()
Targets can override this to emit stuff after the last basic block in the function.
virtual void emitBasicBlockStart (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the start of a basic block.
virtual void emitBasicBlockEnd (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the end of a basic block.
virtual MCSymbol * GetCPISymbol (unsigned CPID) const
Return the symbol for the specified constant pool entry.
virtual void emitFunctionEntryLabel ()
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
virtual void emitFunctionDescriptor ()
virtual void emitMachineConstantPoolValue (MachineConstantPoolValue *MCPV)
virtual void emitXXStructor (const DataLayout &DL, const Constant *CV)
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
virtual bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const
Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
virtual void emitImplicitDef (const MachineInstr *MI) const
Targets can override this to customize the output of IMPLICIT_DEF instructions in verbose mode.
void emitNops (unsigned N)
Emit N NOP instructions.
MCSymbol * createTempSymbol (const Twine &Name) const
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
Return the MCSymbol for the specified ExternalSymbol.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
Return the MCSymbol used to satisfy BlockAddress uses of the specified basic block.
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
This is just convenient handler for printing offsets.
void emitInt8 (int Value) const
Emit a byte directive and value.
void emitInt16 (int Value) const
Emit a short directive and value.
void emitInt32 (int Value) const
Emit a long directive and value.
void emitInt64 (uint64_t Value) const
Emit a long long directive and value.
void emitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
Emit something like ".long Hi-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels.
void emitLabelDifferenceAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo) const
Emit something like ".uleb128 Hi-Lo".
void emitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label.
void emitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label" where the size in bytes of the directive is specified by Size and Label specifies the label.
void emitSLEB128 (int64_t Value, const char *Desc=nullptr) const
Emit the specified signed leb128 value.
void emitULEB128 (uint64_t Value, const char *Desc=nullptr, unsigned PadTo=0) const
Emit the specified unsigned leb128 value.
void emitEncodingByte (unsigned Val, const char *Desc=nullptr) const
Emit a .byte 42 directive that corresponds to an encoding.
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
virtual void emitTTypeReference (const GlobalValue *GV, unsigned Encoding)
Emit reference to a ttype global with a specified encoding.
void emitDwarfSymbolReference (const MCSymbol *Label, bool ForceOffset=false) const
Emit a reference to a symbol for use in dwarf.
void emitDwarfStringOffset (DwarfStringPoolEntry S) const
Emit the 4- or 8-byte offset of a string from the start of its section.
void emitDwarfStringOffset (DwarfStringPoolEntryRef S) const
Emit the 4-or 8-byte offset of a string from the start of its section.
void emitDwarfOffset (const MCSymbol *Label, uint64_t Offset) const
Emit something like ".long Label + Offset" or ".quad Label + Offset" depending on the DWARF format.
void emitDwarfLengthOrOffset (uint64_t Value) const
Emit 32- or 64-bit value depending on the DWARF format.
void maybeEmitDwarf64Mark () const
Emit a special value of 0xffffffff if producing 64-bit debugging info.
void emitDwarfUnitLength (uint64_t Length, const Twine &Comment) const
Emit a unit length field.
void emitDwarfUnitLength (const MCSymbol *Hi, const MCSymbol *Lo, const Twine &Comment) const
Emit a unit length field.
void emitCallSiteOffset (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Encoding) const
Emit reference to a call site with a specified encoding.
void emitCallSiteValue (uint64_t Value, unsigned Encoding) const
Emit an integer value corresponding to the call site encoding.
virtual unsigned getISAEncoding ()
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
virtual void emitDebugValue (const MCExpr *Value, unsigned Size) const
Emit the directive and value for debug thread local expression.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
template<typename T >
void emitDwarfAbbrevs (const T &Abbrevs) const
Emit Dwarf abbreviation table.
void emitDwarfAbbrev (const DIEAbbrev &Abbrev) const
void emitDwarfDIE (const DIE &Die) const
Recursively emit Dwarf DIE tree.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, const char *Code) const
Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself.
virtual void PrintSymbolOperand (const MachineOperand &MO, raw_ostream &OS)
Print the MachineOperand as a symbol.
virtual void emitInlineAsmStart () const
Let the target do anything it needs to do before emitting inlineasm.
virtual void emitInlineAsmEnd (const MCSubtargetInfo &StartInfo, const MCSubtargetInfo *EndInfo) const
Let the target do anything it needs to do after emitting inlineasm.
void emitVisibility (MCSymbol *Sym, unsigned Visibility, bool IsDefinition=true) const
This emits visibility information about symbol, if this is supported by the target.
virtual void emitLinkage (const GlobalValue *GV, MCSymbol *GVSym) const
This emits linkage information about GVSym based on GV, if this is supported by the target.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Additional Inherited Members
Public Types inherited from llvm::AsmPrinter
enum class SledKind : uint8_t {
FUNCTION_ENTER = 0 , FUNCTION_EXIT = 1 , TAIL_CALL = 2 , LOG_ARGS_ENTER = 3 ,
CUSTOM_EVENT = 4 , TYPED_EVENT = 5
}
enum CFIMoveType { CFI_M_None , CFI_M_EH , CFI_M_Debug }
using GOTEquivUsePair = std::pair<const GlobalVariable *, unsigned>
Map global GOT equivalent MCSymbols to GlobalVariables and keep track of its number of uses by other globals.
Static Public Member Functions inherited from llvm::AsmPrinter
static Align getGVAlignment (const GlobalObject *GV, const DataLayout &DL, Align InAlign=Align(1))
Return the alignment for the specified GV.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::AsmPrinter
TargetMachine & TM
Target machine description.
const MCAsmInfo * MAI
Target Asm Printer information.
MCContext & OutContext
This is the context for the output file that we are streaming.
std::unique_ptr< MCStreamer > OutStreamer
This is the MCStreamer object for the file we are generating.
MachineFunction * MF = nullptr
The current machine function.
MachineModuleInfo * MMI = nullptr
This is a pointer to the current MachineModuleInfo.
MachineDominatorTree * MDT = nullptr
This is a pointer to the current MachineDominatorTree.
MachineLoopInfo * MLI = nullptr
This is a pointer to the current MachineLoopInfo.
MachineOptimizationRemarkEmitter * ORE
Optimization remark emitter.
MCSymbol * CurrentPatchableFunctionEntrySym = nullptr
The symbol for the entry in __patchable_function_entires.
MCSymbol * CurrentFnSym = nullptr
The symbol for the current function.
MCSymbol * CurrentFnDescSym = nullptr
The symbol for the current function descriptor on AIX.
MCSymbol * CurrentFnSymForSize = nullptr
The symbol used to represent the start of the current function for the purpose of calculating its size (e.g.
MapVector< unsigned, MBBSectionRange > MBBSectionRanges
MapVector< const MCSymbol *, GOTEquivUsePair > GlobalGOTEquivs
SmallVector< XRayFunctionEntry, 4 > Sleds
Protected Member Functions inherited from llvm::AsmPrinter
AsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes inherited from llvm::AsmPrinter
MCSymbol * CurrentFnBegin = nullptr
std::vector< HandlerInfo > Handlers
A vector of all debug/EH info emitters we should use.
size_t NumUserHandlers = 0
Detailed Description
Definition at line 21 of file WebAssemblyAsmPrinter.h.
Constructor & Destructor Documentation
WebAssemblyAsmPrinter()
llvm::WebAssemblyAsmPrinter::WebAssemblyAsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > Streamer) inline explicit
Definition at line 36 of file WebAssemblyAsmPrinter.h.
Member Function Documentation
addSignature()
void llvm::WebAssemblyAsmPrinter::addSignature (std::unique_ptr< wasm::WasmSignature > && Sig) inline
Definition at line 46 of file WebAssemblyAsmPrinter.h.
Referenced by emitEndOfAsmFile(), and emitFunctionBodyStart().
emitConstantPool()
void WebAssemblyAsmPrinter::emitConstantPool () override virtual
Print to the current output stream assembly representations of the constants in the constant pool MCP.
EmitConstantPool - Print to the current output stream assembly representations of the constants in the constant pool MCP.
This is used to print out constants which have been "spilled to memory" by the code generator.
Reimplemented from llvm::AsmPrinter.
Definition at line 386 of file WebAssemblyAsmPrinter.cpp.
References assert(), llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstants(), and llvm::AsmPrinter::MF.
emitEndOfAsmFile()
void WebAssemblyAsmPrinter::emitEndOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 172 of file WebAssemblyAsmPrinter.cpp.
References addSignature(), llvm::computeSignatureVTs(), llvm::MCConstantExpr::create(), llvm::WebAssemblyTargetStreamer::emitEventType(), llvm::WebAssemblyTargetStreamer::emitExportName(), llvm::WebAssemblyTargetStreamer::emitFunctionType(), llvm::WebAssemblyTargetStreamer::emitGlobalType(), llvm::WebAssemblyTargetStreamer::emitImportModule(), llvm::WebAssemblyTargetStreamer::emitImportName(), EmitProducerInfo(), EmitTargetFeatures(), EnableEmException, EnableEmSjLj, F, G, getMCSymbolForFunction(), llvm::SectionKind::getMetadata(), llvm::MDString::getString(), llvm::AsmPrinter::getSymbol(), llvm::MCContext::getSymbols(), getTargetStreamer(), llvm::MCContext::getWasmSection(), Name, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, Results, llvm::signatureFromMVTs(), Size, llvm::AsmPrinter::TM, llvm::wasm::WASM_SYMBOL_TYPE_EVENT, llvm::wasm::WASM_SYMBOL_TYPE_FUNCTION, and llvm::wasm::WASM_SYMBOL_TYPE_GLOBAL.
emitFunctionBodyStart()
void WebAssemblyAsmPrinter::emitFunctionBodyStart () override virtual
Targets can override this to emit stuff before the first basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 395 of file WebAssemblyAsmPrinter.cpp.
References addSignature(), assert(), llvm::computeSignatureVTs(), llvm::AsmPrinter::CurrentFnSym, llvm::AsmPrinter::emitFunctionBodyStart(), llvm::WebAssemblyTargetStreamer::emitFunctionType(), llvm::WebAssemblyTargetStreamer::emitIndIdx(), llvm::WebAssemblyTargetStreamer::emitLocal(), F, llvm::MachineFunction::getFunction(), llvm::WebAssemblyFunctionInfo::getLocals(), getTargetStreamer(), Idx, llvm::AsmPrinter::lowerConstant(), llvm::AsmPrinter::MF, llvm::signatureFromMVTs(), llvm::AsmPrinter::TM, llvm::valTypesFromMVTs(), and llvm::wasm::WASM_SYMBOL_TYPE_FUNCTION.
emitInstruction()
void WebAssemblyAsmPrinter::emitInstruction (const MachineInstr *) override virtual
Targets should implement this to emit instructions.
Reimplemented from llvm::AsmPrinter.
Definition at line 424 of file WebAssemblyAsmPrinter.cpp.
References llvm::dbgs(), llvm::AsmPrinter::EmitToStreamer(), llvm::AsmPrinter::isVerbose(), LLVM_DEBUG, llvm::WebAssemblyMCInstLower::lower(), MI, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
emitJumpTableInfo()
void WebAssemblyAsmPrinter::emitJumpTableInfo () override virtual
Print assembly representations of the jump tables used by the current function to the current output stream.
emit a .set directive for each unique entry.
Reimplemented from llvm::AsmPrinter.
Definition at line 391 of file WebAssemblyAsmPrinter.cpp.
EmitProducerInfo()
void WebAssemblyAsmPrinter::EmitProducerInfo (Module & M)
Definition at line 279 of file WebAssemblyAsmPrinter.cpp.
References Debug, E, llvm::SectionKind::getMetadata(), llvm::MCContext::getWasmSection(), I, llvm::dwarf::LanguageString(), Name, llvm::AsmPrinter::OutContext, and llvm::AsmPrinter::OutStreamer.
Referenced by emitEndOfAsmFile().
EmitTargetFeatures()
void WebAssemblyAsmPrinter::EmitTargetFeatures (Module & M)
Definition at line 330 of file WebAssemblyAsmPrinter.cpp.
References F, llvm::SectionKind::getMetadata(), llvm::MCContext::getWasmSection(), I, Name, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::wasm::WASM_FEATURE_PREFIX_DISALLOWED, llvm::wasm::WASM_FEATURE_PREFIX_REQUIRED, llvm::wasm::WASM_FEATURE_PREFIX_USED, and llvm::WebAssemblyFeatureKV.
Referenced by emitEndOfAsmFile().
getMCSymbolForFunction()
MCSymbolWasm * WebAssemblyAsmPrinter::getMCSymbolForFunction (const Function * F, bool EnableEmEH, wasm::WasmSignature * Sig, bool & InvokeDetected)
Definition at line 150 of file WebAssemblyAsmPrinter.cpp.
References assert(), F, getEmscriptenInvokeSymbolName(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::AsmPrinter::getSymbol(), isEmscriptenInvokeName(), llvm::report_fatal_error(), and llvm::WebAssembly::signatureToString().
Referenced by emitEndOfAsmFile().
getPassName()
StringRef llvm::WebAssemblyAsmPrinter::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 41 of file WebAssemblyAsmPrinter.h.
getRegType()
MVT WebAssemblyAsmPrinter::getRegType (unsigned RegNo) const
Definition at line 59 of file WebAssemblyAsmPrinter.cpp.
References llvm::errs(), llvm::MVT::f32, llvm::MVT::f64, llvm::MachineRegisterInfo::getRegClass(), llvm::WebAssemblySubtarget::getRegisterInfo(), llvm::MVT::i32, llvm::MVT::i64, LLVM_DEBUG, llvm_unreachable, llvm::MVT::Other, TRI, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, and llvm::MVT::v8i16.
getSubtarget()
const WebAssemblySubtarget & llvm::WebAssemblyAsmPrinter::getSubtarget () const inline
Definition at line 45 of file WebAssemblyAsmPrinter.h.
getTargetStreamer()
WebAssemblyTargetStreamer * WebAssemblyAsmPrinter::getTargetStreamer ()
Definition at line 81 of file WebAssemblyAsmPrinter.cpp.
References llvm::AsmPrinter::OutStreamer.
Referenced by emitEndOfAsmFile(), and emitFunctionBodyStart().
PrintAsmMemoryOperand()
bool WebAssemblyAsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & OS) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented from llvm::AsmPrinter.
Definition at line 512 of file WebAssemblyAsmPrinter.cpp.
References MI, and llvm::AsmPrinter::PrintAsmMemoryOperand().
PrintAsmOperand()
bool WebAssemblyAsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & O) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Targets should override this to format as appropriate for machine specific ExtraCodes or when the arch-independent handling would be too complex otherwise.
Reimplemented from llvm::AsmPrinter.
Definition at line 474 of file WebAssemblyAsmPrinter.cpp.
References assert(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getOffset(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getType(), llvm::AsmPrinter::MAI, MI, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::MCSymbol::print(), llvm::AsmPrinter::PrintAsmOperand(), llvm::AsmPrinter::printOffset(), llvm::AsmPrinter::PrintSymbolOperand(), and regToString().
regToString()
std::string WebAssemblyAsmPrinter::regToString (const MachineOperand & MO)
Definition at line 71 of file WebAssemblyAsmPrinter.cpp.
References assert(), llvm::MachineOperand::getReg(), llvm::WebAssemblyFunctionInfo::getWAReg(), llvm::Register::isVirtualRegister(), llvm::WebAssemblyFunctionInfo::isVRegStackified(), and llvm::WebAssemblyFunctionInfo::UnusedReg.
Referenced by PrintAsmOperand().
runOnMachineFunction()
bool llvm::WebAssemblyAsmPrinter::runOnMachineFunction (MachineFunction & MF) inline override virtual
Emit the specified function out to the OutStreamer.
Reimplemented from llvm::AsmPrinter.
Definition at line 54 of file WebAssemblyAsmPrinter.h.
References llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), MRI, and llvm::AsmPrinter::runOnMachineFunction().
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/WebAssemblyAsmPrinter.h
lib/Target/WebAssembly/WebAssemblyAsmPrinter.cpp