LLVM: llvm::InductionDescriptor Class Reference
llvm::InductionDescriptor Class Reference
A struct for saving information about induction variables.
#include "llvm/Analysis/IVDescriptors.h"
Public Types
enum InductionKind { IK_NoInduction , IK_IntInduction , IK_PtrInduction , IK_FpInduction }
This enum represents the kinds of inductions that we support.
Public Member Functions
InductionDescriptor ()=default
Default constructor - creates an invalid induction.
Value * getStartValue () const
InductionKind getKind () const
const SCEV * getStep () const
BinaryOperator * getInductionBinOp () const
ConstantInt * getConstIntStepValue () const
bool hasUnsafeAlgebra ()
Returns true if the induction type is FP and the binary operator does not have the "fast-math" property.
Instruction * getUnsafeAlgebraInst ()
Returns induction operator that does not have "fast-math" property and requires FP unsafe mode.
Instruction::BinaryOps getInductionOpcode () const
Returns binary opcode of the induction operator.
const SmallVectorImpl< Instruction * > & getCastInsts () const
Returns a reference to the type cast instructions in the induction update chain, that are redundant when guarded with a runtime SCEV overflow check.
Static Public Member Functions
static bool isInductionPHI (PHINode *Phi, const Loop *L, ScalarEvolution *SE, InductionDescriptor &D, const SCEV *Expr=nullptr, SmallVectorImpl< Instruction * > *CastsToIgnore=nullptr)
Returns true if Phi is an induction in the loop L.
static bool isFPInductionPHI (PHINode *Phi, const Loop *L, ScalarEvolution *SE, InductionDescriptor &D)
Returns true if Phi is a floating point induction in the loop L.
static bool isInductionPHI (PHINode *Phi, const Loop *L, PredicatedScalarEvolution &PSE, InductionDescriptor &D, bool Assume=false)
Returns true if Phi is a loop L induction, in the context associated with the run-time predicate of PSE.
Detailed Description
A struct for saving information about induction variables.
Definition at line 257 of file IVDescriptors.h.
Member Enumeration Documentation
InductionKind
enum llvm::InductionDescriptor::InductionKind
This enum represents the kinds of inductions that we support.
Enumerator
IK_NoInduction
Not an induction variable.
IK_IntInduction
Integer induction variable. Step = C.
IK_PtrInduction
Pointer induction var. Step = C / sizeof(elem).
IK_FpInduction
Floating point induction variable.
Definition at line 260 of file IVDescriptors.h.
Constructor & Destructor Documentation
InductionDescriptor()
llvm::InductionDescriptor::InductionDescriptor () default
Default constructor - creates an invalid induction.
Referenced by isFPInductionPHI(), and isInductionPHI().
Member Function Documentation
getCastInsts()
const SmallVectorImpl< Instruction * > & llvm::InductionDescriptor::getCastInsts () const inline
Returns a reference to the type cast instructions in the induction update chain, that are redundant when guarded with a runtime SCEV overflow check.
Definition at line 333 of file IVDescriptors.h.
getConstIntStepValue()
ConstantInt * InductionDescriptor::getConstIntStepValue () const
Definition at line 942 of file IVDescriptors.cpp.
getInductionBinOp()
BinaryOperator * llvm::InductionDescriptor::getInductionBinOp () const inline
Definition at line 274 of file IVDescriptors.h.
getInductionOpcode()
Instruction::BinaryOps llvm::InductionDescriptor::getInductionOpcode () const inline
Returns binary opcode of the induction operator.
Definition at line 325 of file IVDescriptors.h.
References llvm::BinaryOperator::getOpcode(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::InnerLoopVectorizer::createVectorIntOrFpInductionPHI().
getKind()
InductionKind llvm::InductionDescriptor::getKind () const inline
Definition at line 272 of file IVDescriptors.h.
Referenced by llvm::VPlanTransforms::VPInstructionsToVPRecipes(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
getStartValue()
Value * llvm::InductionDescriptor::getStartValue () const inline
Definition at line 271 of file IVDescriptors.h.
Referenced by llvm::InnerLoopVectorizer::createInductionResumeValues(), llvm::VPlanTransforms::VPInstructionsToVPRecipes(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
getStep()
const SCEV * llvm::InductionDescriptor::getStep () const inline
Definition at line 273 of file IVDescriptors.h.
Referenced by llvm::InnerLoopVectorizer::createInductionResumeValues(), llvm::InnerLoopVectorizer::fixupIVUsers(), and llvm::InnerLoopVectorizer::widenPHIInstruction().
getUnsafeAlgebraInst()
Instruction * llvm::InductionDescriptor::getUnsafeAlgebraInst () inline
Returns induction operator that does not have "fast-math" property and requires FP unsafe mode.
Definition at line 315 of file IVDescriptors.h.
References IK_FpInduction.
hasUnsafeAlgebra()
bool llvm::InductionDescriptor::hasUnsafeAlgebra () inline
Returns true if the induction type is FP and the binary operator does not have the "fast-math" property.
Such operation requires a relaxed FP mode.
Definition at line 308 of file IVDescriptors.h.
References IK_FpInduction.
isFPInductionPHI()
bool InductionDescriptor::isFPInductionPHI (PHINode * Phi, const Loop * L, ScalarEvolution * SE, InductionDescriptor & D) static
Returns true if Phi is a floating point induction in the loop L.
If Phi is an induction, the induction descriptor D will contain the data describing this induction.
Definition at line 948 of file IVDescriptors.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), D, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::ScalarEvolution::getUnknown(), I, IK_FpInduction, InductionDescriptor(), and llvm::Type::isFloatingPointTy().
Referenced by isInductionPHI().
isInductionPHI() [1/2]
bool InductionDescriptor::isInductionPHI (PHINode * Phi, const Loop * L, PredicatedScalarEvolution & PSE, InductionDescriptor & D, bool Assume = false) static
Returns true if Phi is a loop L induction, in the context associated with the run-time predicate of PSE.
If Assume is true, this can add further SCEV predicates to PSE in order to prove that Phi is an induction. If Phi is an induction, D will contain the data describing this induction.
Definition at line 1106 of file IVDescriptors.cpp.
References D, llvm::dbgs(), llvm::PredicatedScalarEvolution::getAsAddRec(), getCastsForInductionPHI(), llvm::PredicatedScalarEvolution::getSCEV(), llvm::PredicatedScalarEvolution::getSE(), llvm::Value::getType(), isFPInductionPHI(), isInductionPHI(), and LLVM_DEBUG.
isInductionPHI() [2/2]
bool InductionDescriptor::isInductionPHI (PHINode * Phi, const Loop * L, ScalarEvolution * SE, InductionDescriptor & D, const SCEV * Expr = nullptr, SmallVectorImpl< Instruction * > * CastsToIgnore = nullptr) static
Returns true if Phi is an induction in the loop L.
If Phi is an induction, the induction descriptor D will contain the data describing this induction. If by some other means the caller has a better SCEV expression for Phi than the one returned by the ScalarEvolution analysis, it can be passed through Expr. If the def-use chain associated with the phi includes casts (that we know we can ignore under proper runtime checks), they are passed through CastsToIgnore.
Definition at line 1150 of file IVDescriptors.cpp.
References assert(), D, llvm::dbgs(), DL, llvm::ScalarEvolution::getConstant(), llvm::Module::getDataLayout(), llvm::PHINode::getIncomingValueForBlock(), llvm::SCEVAddRecExpr::getLoop(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::Instruction::getModule(), llvm::ScalarEvolution::getSCEV(), llvm::ConstantInt::getSExtValue(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::ConstantInt::getType(), llvm::Value::getType(), IK_IntInduction, IK_PtrInduction, InductionDescriptor(), llvm::ScalarEvolution::isLoopInvariant(), LLVM_DEBUG, and Size.
Referenced by findLoopComponents(), llvm::Loop::LoopBounds::getBounds(), llvm::Loop::getInductionDescriptor(), llvm::Loop::getInductionVariable(), llvm::Loop::isAuxiliaryInductionVariable(), and isInductionPHI().
The documentation for this class was generated from the following files:
include/llvm/Analysis/IVDescriptors.h
lib/Analysis/IVDescriptors.cpp