LLVM: llvm::MemoryAccess Class Reference
llvm::MemoryAccess Class Reference
#include "llvm/Analysis/MemorySSA.h"
Public Types
using AllAccessType
using DefsOnlyType
using iterator = user_iterator
The user iterators for a memory access.
using const_iterator = const_user_iterator
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Public Member Functions
MemoryAccess (const MemoryAccess &)=delete
MemoryAccess & operator= (const MemoryAccess &)=delete
void * operator new (size_t)=delete
BasicBlock * getBlock () const
void print (raw_ostream &OS) const
void dump () const
memoryaccess_def_iterator defs_begin ()
This iterator walks over all of the defs in a given MemoryAccess.
const_memoryaccess_def_iterator defs_begin () const
memoryaccess_def_iterator defs_end ()
const_memoryaccess_def_iterator defs_end () const
AllAccessType::self_iterator getIterator ()
Get the iterators for the all access list and the defs only list We default to the all access list.
AllAccessType::const_self_iterator getIterator () const
AllAccessType::reverse_self_iterator getReverseIterator ()
AllAccessType::const_reverse_self_iterator getReverseIterator () const
DefsOnlyType::self_iterator getDefsIterator ()
DefsOnlyType::const_self_iterator getDefsIterator () const
DefsOnlyType::reverse_self_iterator getReverseDefsIterator ()
DefsOnlyType::const_reverse_self_iterator getReverseDefsIterator () const
Public Member Functions inherited from llvm::DerivedUser
DerivedUser (Type *Ty, unsigned VK, Use *U, unsigned NumOps, DeleteValueTy DeleteValue)
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_impl< OptionsT >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Member Functions
void setBlock (BasicBlock *BB)
Used by MemorySSA to change the block of a MemoryAccess when it is moved.
unsigned getID () const
Used for debugging and tracking things about MemoryAccesses.
MemoryAccess (LLVMContext &C, unsigned Vty, DeleteValueTy DeleteValue, BasicBlock *BB, unsigned NumOperands)
~MemoryAccess ()=default
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Protected Member Functions inherited from llvm::ilist_node_impl< OptionsT >
ilist_node_impl ()=default
Friends
class MemoryDef
class MemoryPhi
class MemorySSA
class MemoryUse
class MemoryUseOrDef
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::DerivedUser
using DeleteValueTy = void (*)(DerivedUser *)
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< OptionsT >
using self_iterator = ilist_iterator<OptionsT, false, false>
using const_self_iterator = ilist_iterator<OptionsT, false, true>
using reverse_self_iterator = ilist_iterator<OptionsT, true, false>
using const_reverse_self_iterator = ilist_iterator<OptionsT, true, true>
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
Definition at line 140 of file MemorySSA.h.
Member Typedef Documentation
AllAccessType
using llvm::MemoryAccess::AllAccessType
Initial value:
      ilist_node<MemoryAccess, ilist_tag<MSSAHelpers::AllAccessTag>>
Definition at line 145 of file MemorySSA.h.
const_iterator
using llvm::MemoryAccess::const_iterator = const_user_iterator
Definition at line 169 of file MemorySSA.h.
DefsOnlyType
using llvm::MemoryAccess::DefsOnlyType
Initial value:
      ilist_node<MemoryAccess, ilist_tag<MSSAHelpers::DefsOnlyTag>>
Definition at line 147 of file MemorySSA.h.
iterator
using llvm::MemoryAccess::iterator = user_iterator
The user iterators for a memory access.
Definition at line 168 of file MemorySSA.h.
Constructor & Destructor Documentation
MemoryAccess() [1/2]
llvm::MemoryAccess::MemoryAccess (const MemoryAccess &) delete
MemoryAccess() [2/2]
llvm::MemoryAccess::MemoryAccess (LLVMContext & C, unsigned Vty, DeleteValueTy DeleteValue, BasicBlock * BB, unsigned NumOperands) inline protected
Definition at line 221 of file MemorySSA.h.
~MemoryAccess()
llvm::MemoryAccess::~MemoryAccess () protected default
Member Function Documentation
classof()
static bool llvm::MemoryAccess::classof (const Value * V) inline static
Definition at line 157 of file MemorySSA.h.
References llvm::ilist_node_impl< OptionsT >::ilist_node_impl().
defs_begin() [1/2]
memoryaccess_def_iterator llvm::MemoryAccess::defs_begin () inline
This iterator walks over all of the defs in a given MemoryAccess.
For MemoryPhi nodes, this walks arguments. For MemoryUse/MemoryDef, this walks the defining access.
Definition at line 1130 of file MemorySSA.h.
defs_begin() [2/2]
const_memoryaccess_def_iterator llvm::MemoryAccess::defs_begin () const inline
Definition at line 1134 of file MemorySSA.h.
defs_end() [1/2]
memoryaccess_def_iterator llvm::MemoryAccess::defs_end () inline
Definition at line 1138 of file MemorySSA.h.
Referenced by llvm::upward_defs_iterator::operator*(), and llvm::upward_defs_iterator::operator++().
defs_end() [2/2]
const_memoryaccess_def_iterator llvm::MemoryAccess::defs_end () const inline
Definition at line 1142 of file MemorySSA.h.
dump()
void MemoryAccess::dump () const
Definition at line 2212 of file MemorySSA.cpp.
References llvm::dbgs(), and llvm::MemorySSA::print().
getBlock()
BasicBlock * llvm::MemoryAccess::getBlock () const inline
Definition at line 162 of file MemorySSA.h.
Referenced by llvm::MemorySSAUpdater::createMemoryAccessAfter(), llvm::MemorySSAUpdater::createMemoryAccessBefore(), hasPartialIVCondition(), llvm::MemorySSAUpdater::insertDef(), llvm::MemorySSAUpdater::insertUse(), llvm::MemorySSAUpdater::moveAfter(), llvm::MemorySSAUpdater::moveBefore(), pointerInvalidatedByBlockWithMSSA(), llvm::MemorySSA::removeFromLists(), and llvm::MemorySSA::removeFromLookups().
getDefsIterator() [1/2]
DefsOnlyType::self_iterator llvm::MemoryAccess::getDefsIterator () inline
Definition at line 193 of file MemorySSA.h.
References llvm::ilist_node_impl< OptionsT >::getIterator().
Referenced by llvm::MemorySSAUpdater::insertDef().
getDefsIterator() [2/2]
DefsOnlyType::const_self_iterator llvm::MemoryAccess::getDefsIterator () const inline
Definition at line 196 of file MemorySSA.h.
References llvm::ilist_node_impl< OptionsT >::getIterator().
getID()
unsigned llvm::MemoryAccess::getID () const inline protected
Used for debugging and tracking things about MemoryAccesses.
Guaranteed unique among MemoryAccesses, no guarantees otherwise.
Definition at line 664 of file MemorySSA.h.
References assert(), and llvm::ilist_node_impl< OptionsT >::ilist_node_impl().
Referenced by llvm::MemoryUse::isOptimized(), llvm::MemoryUse::print(), llvm::MemoryPhi::print(), and llvm::MemoryDef::setOptimized().
getIterator() [1/2]
AllAccessType::self_iterator llvm::MemoryAccess::getIterator () inline
Get the iterators for the all access list and the defs only list We default to the all access list.
Definition at line 181 of file MemorySSA.h.
References llvm::ilist_node_impl< OptionsT >::getIterator().
Referenced by llvm::MemorySSAUpdater::createMemoryAccessAfter(), llvm::MemorySSAUpdater::createMemoryAccessBefore(), llvm::MemorySSAUpdater::moveAfter(), and llvm::MemorySSAUpdater::moveBefore().
getIterator() [2/2]
AllAccessType::const_self_iterator llvm::MemoryAccess::getIterator () const inline
Definition at line 184 of file MemorySSA.h.
References llvm::ilist_node_impl< OptionsT >::getIterator().
getReverseDefsIterator() [1/2]
DefsOnlyType::reverse_self_iterator llvm::MemoryAccess::getReverseDefsIterator () inline
Definition at line 199 of file MemorySSA.h.
References llvm::ilist_node_impl< OptionsT >::getReverseIterator().
getReverseDefsIterator() [2/2]
DefsOnlyType::const_reverse_self_iterator llvm::MemoryAccess::getReverseDefsIterator () const inline
Definition at line 202 of file MemorySSA.h.
References llvm::ilist_node_impl< OptionsT >::getReverseIterator().
getReverseIterator() [1/2]
AllAccessType::reverse_self_iterator llvm::MemoryAccess::getReverseIterator () inline
Definition at line 187 of file MemorySSA.h.
References llvm::ilist_node_impl< OptionsT >::getReverseIterator().
getReverseIterator() [2/2]
AllAccessType::const_reverse_self_iterator llvm::MemoryAccess::getReverseIterator () const inline
Definition at line 190 of file MemorySSA.h.
References llvm::ilist_node_impl< OptionsT >::getReverseIterator().
operator new()
void * llvm::MemoryAccess::operator new (size_t) delete
operator=()
MemoryAccess & llvm::MemoryAccess::operator= (const MemoryAccess &) delete
print()
void MemoryAccess::print (raw_ostream & OS) const
Definition at line 2141 of file MemorySSA.cpp.
References llvm_unreachable, and llvm::MemorySSA::print().
Referenced by llvm::operator<<().
setBlock()
void llvm::MemoryAccess::setBlock (BasicBlock * BB) inline protected
Used by MemorySSA to change the block of a MemoryAccess when it is moved.
Definition at line 215 of file MemorySSA.h.
Friends And Related Symbol Documentation
MemoryDef
friend class MemoryDef friend
Definition at line 207 of file MemorySSA.h.
MemoryPhi
friend class MemoryPhi friend
Definition at line 208 of file MemorySSA.h.
MemorySSA
friend class MemorySSA friend
Definition at line 209 of file MemorySSA.h.
MemoryUse
friend class MemoryUse friend
Definition at line 210 of file MemorySSA.h.
MemoryUseOrDef
friend class MemoryUseOrDef friend
Definition at line 211 of file MemorySSA.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/MemorySSA.h
lib/Analysis/MemorySSA.cpp