LLVM: llvm::orc::EHFrameRegistrationPlugin Class Reference
llvm::orc::EHFrameRegistrationPlugin Class Reference
#include "llvm/ExecutionEngine/Orc/ObjectLinkingLayer.h"
Public Member Functions
EHFrameRegistrationPlugin (ExecutionSession &ES, std::unique_ptr< jitlink::EHFrameRegistrar > Registrar)
void modifyPassConfig (MaterializationResponsibility &MR, const Triple &TT, jitlink::PassConfiguration &PassConfig) override
Error notifyEmitted (MaterializationResponsibility &MR) override
Error notifyFailed (MaterializationResponsibility &MR) override
Error notifyRemovingResources (ResourceKey K) override
void notifyTransferringResources (ResourceKey DstKey, ResourceKey SrcKey) override
Public Member Functions inherited from llvm::orc::ObjectLinkingLayer::Plugin
virtual ~Plugin ()
virtual void notifyLoaded (MaterializationResponsibility &MR)
virtual LocalDependenciesMap getSyntheticSymbolLocalDependencies (MaterializationResponsibility &MR)
Return any dependencies that synthetic symbols (e.g.
Additional Inherited Members
Public Types inherited from llvm::orc::ObjectLinkingLayer::Plugin
using JITLinkSymbolVector = std::vector<const jitlink::Symbol *>
using LocalDependenciesMap = DenseMap<SymbolStringPtr, JITLinkSymbolVector>
Detailed Description
Definition at line 182 of file ObjectLinkingLayer.h.
Constructor & Destructor Documentation
EHFrameRegistrationPlugin()
llvm::orc::EHFrameRegistrationPlugin::EHFrameRegistrationPlugin (ExecutionSession & ES, std::unique_ptr< jitlink::EHFrameRegistrar > Registrar)
Definition at line 565 of file ObjectLinkingLayer.cpp.
Member Function Documentation
modifyPassConfig()
void llvm::orc::EHFrameRegistrationPlugin::modifyPassConfig (MaterializationResponsibility & MR, const Triple & TT, jitlink::PassConfiguration & PassConfig) override virtual
Reimplemented from llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 569 of file ObjectLinkingLayer.cpp.
References Addr, assert(), llvm::jitlink::createEHFrameRecorderPass(), llvm::Lock, llvm::jitlink::PassConfiguration::PostFixupPasses, and Size.
notifyEmitted()
Error llvm::orc::EHFrameRegistrationPlugin::notifyEmitted (MaterializationResponsibility & MR) override virtual
Reimplemented from llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 584 of file ObjectLinkingLayer.cpp.
References assert(), llvm::Lock, llvm::Error::success(), and llvm::orc::MaterializationResponsibility::withResourceKeyDo().
notifyFailed()
Error llvm::orc::EHFrameRegistrationPlugin::notifyFailed (MaterializationResponsibility & MR) override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 607 of file ObjectLinkingLayer.cpp.
References llvm::Lock, and llvm::Error::success().
notifyRemovingResources()
Error llvm::orc::EHFrameRegistrationPlugin::notifyRemovingResources (ResourceKey K) override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 614 of file ObjectLinkingLayer.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), I, llvm::joinErrors(), llvm::orc::ExecutionSession::runSessionLocked(), and llvm::Error::success().
notifyTransferringResources()
void llvm::orc::EHFrameRegistrationPlugin::notifyTransferringResources (ResourceKey DstKey, ResourceKey SrcKey) override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 638 of file ObjectLinkingLayer.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and SI.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/ObjectLinkingLayer.h
lib/ExecutionEngine/Orc/ObjectLinkingLayer.cpp