LLVM: llvm::orc::TargetProcessControl Class Reference
llvm::orc::TargetProcessControl Class Reference abstract
TargetProcessControl supports interaction with a JIT target process.
#include "llvm/ExecutionEngine/Orc/TargetProcessControl.h"
Classes
struct LookupRequest
A pair of a dylib and a set of symbols to be looked up.
class MemoryAccess
APIs for manipulating memory in the target process.
Public Member Functions
virtual ~TargetProcessControl ()
SymbolStringPtr intern (StringRef SymName)
Intern a symbol name in the SymbolStringPool.
std::shared_ptr< SymbolStringPool > getSymbolStringPool () const
Return a shared pointer to the SymbolStringPool for this instance.
const Triple & getTargetTriple () const
Return the Triple for the target process.
unsigned getPageSize () const
Get the page size for the target process.
MemoryAccess & getMemoryAccess () const
Return a MemoryAccess object for the target process.
jitlink::JITLinkMemoryManager & getMemMgr () const
Return a JITLinkMemoryManager for the target process.
virtual Expected< tpctypes::DylibHandle > loadDylib (const char *DylibPath)=0
Load the dynamic library at the given path and return a handle to it.
virtual Expected< std::vector< tpctypes::LookupResult > > lookupSymbols (ArrayRef< LookupRequest > Request)=0
Search for symbols in the target process.
virtual Expected< int32_t > runAsMain (JITTargetAddress MainFnAddr, ArrayRef< std::string > Args)=0
Run function with a main-like signature.
virtual Expected< tpctypes::WrapperFunctionResult > runWrapper (JITTargetAddress WrapperFnAddr, ArrayRef< uint8_t > ArgBuffer)=0
Run a wrapper function with signature:
virtual Error disconnect ()=0
Disconnect from the target process.
Protected Member Functions
TargetProcessControl (std::shared_ptr< SymbolStringPool > SSP)
Protected Attributes
std::shared_ptr< SymbolStringPool > SSP
Triple TargetTriple
unsigned PageSize = 0
MemoryAccess * MemAccess = nullptr
jitlink::JITLinkMemoryManager * MemMgr = nullptr
Detailed Description
TargetProcessControl supports interaction with a JIT target process.
Definition at line 32 of file TargetProcessControl.h.
Constructor & Destructor Documentation
~TargetProcessControl()
llvm::orc::TargetProcessControl::~TargetProcessControl () virtual
Definition at line 23 of file TargetProcessControl.cpp.
TargetProcessControl()
llvm::orc::TargetProcessControl::TargetProcessControl (std::shared_ptr< SymbolStringPool > SSP) inline protected
Definition at line 155 of file TargetProcessControl.h.
Member Function Documentation
disconnect()
virtual Error llvm::orc::TargetProcessControl::disconnect () pure virtual
Disconnect from the target process.
This should be called after the JIT session is shut down.
Implemented in llvm::orc::SelfTargetProcessControl.
getMemMgr()
jitlink::JITLinkMemoryManager & llvm::orc::TargetProcessControl::getMemMgr () const inline
Return a JITLinkMemoryManager for the target process.
Definition at line 119 of file TargetProcessControl.h.
References MemMgr.
getMemoryAccess()
MemoryAccess & llvm::orc::TargetProcessControl::getMemoryAccess () const inline
Return a MemoryAccess object for the target process.
Definition at line 116 of file TargetProcessControl.h.
References MemAccess.
getPageSize()
unsigned llvm::orc::TargetProcessControl::getPageSize () const inline
Get the page size for the target process.
Definition at line 113 of file TargetProcessControl.h.
References PageSize.
getSymbolStringPool()
std::shared_ptr< SymbolStringPool > llvm::orc::TargetProcessControl::getSymbolStringPool () const inline
Return a shared pointer to the SymbolStringPool for this instance.
Definition at line 107 of file TargetProcessControl.h.
References SSP.
getTargetTriple()
const Triple & llvm::orc::TargetProcessControl::getTargetTriple () const inline
Return the Triple for the target process.
Definition at line 110 of file TargetProcessControl.h.
References TargetTriple.
Referenced by llvm::orc::TPCEHFrameRegistrar::Create(), and llvm::orc::TPCIndirectionUtils::Create().
intern()
SymbolStringPtr llvm::orc::TargetProcessControl::intern (StringRef SymName) inline
Intern a symbol name in the SymbolStringPool.
Definition at line 104 of file TargetProcessControl.h.
References SSP.
Referenced by llvm::orc::TPCEHFrameRegistrar::Create().
loadDylib()
virtual Expected< tpctypes::DylibHandle > llvm::orc::TargetProcessControl::loadDylib (const char * DylibPath) pure virtual
Load the dynamic library at the given path and return a handle to it.
If LibraryPath is null this function will return the global handle for the target process.
Implemented in llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >, and llvm::orc::SelfTargetProcessControl.
Referenced by llvm::orc::TPCEHFrameRegistrar::Create(), and llvm::orc::TPCDynamicLibrarySearchGenerator::Load().
lookupSymbols()
virtual Expected< std::vector< tpctypes::LookupResult > > llvm::orc::TargetProcessControl::lookupSymbols (ArrayRef< LookupRequest > Request) pure virtual
Search for symbols in the target process.
The result of the lookup is a 2-dimentional array of target addresses that correspond to the lookup order. If a required symbol is not found then this method will return an error. If a weakly referenced symbol is not found then it be assigned a '0' value in the result. that correspond to the lookup order.
Implemented in llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >, and llvm::orc::SelfTargetProcessControl.
Referenced by llvm::orc::TPCEHFrameRegistrar::Create(), and llvm::orc::TPCDynamicLibrarySearchGenerator::tryToGenerate().
runAsMain()
virtual Expected< int32_t > llvm::orc::TargetProcessControl::runAsMain (JITTargetAddress MainFnAddr, ArrayRef< std::string > Args) pure virtual
Run function with a main-like signature.
Implemented in llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >, and llvm::orc::SelfTargetProcessControl.
runWrapper()
virtual Expected< tpctypes::WrapperFunctionResult > llvm::orc::TargetProcessControl::runWrapper (JITTargetAddress WrapperFnAddr, ArrayRef< uint8_t > ArgBuffer) pure virtual
Run a wrapper function with signature:
CWrapperFunctionResult fn(uint8_t *Data, uint64_t Size);
{.cpp}
Implemented in llvm::orc::OrcRPCTargetProcessControlBase< RPCEndpointT >, and llvm::orc::SelfTargetProcessControl.
Referenced by llvm::orc::TPCEHFrameRegistrar::deregisterEHFrames(), and llvm::orc::TPCEHFrameRegistrar::registerEHFrames().
Member Data Documentation
MemAccess
MemoryAccess* llvm::orc::TargetProcessControl::MemAccess = nullptr protected
Definition at line 161 of file TargetProcessControl.h.
Referenced by getMemoryAccess(), and llvm::orc::SelfTargetProcessControl::SelfTargetProcessControl().
MemMgr
jitlink::JITLinkMemoryManager* llvm::orc::TargetProcessControl::MemMgr = nullptr protected
Definition at line 162 of file TargetProcessControl.h.
Referenced by llvm::orc::SelfTargetProcessControl::Create(), getMemMgr(), and llvm::orc::SelfTargetProcessControl::SelfTargetProcessControl().
PageSize
unsigned llvm::orc::TargetProcessControl::PageSize = 0 protected
Definition at line 160 of file TargetProcessControl.h.
Referenced by llvm::orc::SelfTargetProcessControl::Create(), getPageSize(), and llvm::orc::SelfTargetProcessControl::SelfTargetProcessControl().
SSP
std::shared_ptr<SymbolStringPool> llvm::orc::TargetProcessControl::SSP protected
Definition at line 158 of file TargetProcessControl.h.
Referenced by llvm::orc::SelfTargetProcessControl::Create(), getSymbolStringPool(), and intern().
TargetTriple
Triple llvm::orc::TargetProcessControl::TargetTriple protected
Definition at line 159 of file TargetProcessControl.h.
Referenced by getTargetTriple(), and llvm::orc::SelfTargetProcessControl::SelfTargetProcessControl().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcessControl.h
lib/ExecutionEngine/Orc/TargetProcessControl.cpp