LLVM: llvm::AArch64LegalizerInfo Class Reference
llvm::AArch64LegalizerInfo Class Reference
This class provides the information for the target register banks.
#include "Target/AArch64/GISel/AArch64LegalizerInfo.h"
Public Member Functions
AArch64LegalizerInfo (const AArch64Subtarget &ST)
bool legalizeCustom (LegalizerHelper &Helper, MachineInstr &MI) const override
Called for instructions with the Custom LegalizationAction.
bool legalizeIntrinsic (LegalizerHelper &Helper, MachineInstr &MI) const override
Public Member Functions inherited from llvm::LegalizerInfo
LegalizerInfo ()
virtual ~LegalizerInfo ()=default
unsigned getOpcodeIdxForOpcode (unsigned Opcode) const
unsigned getActionDefinitionsIdx (unsigned Opcode) const
void computeTables ()
Compute any ancillary tables needed to quickly decide how an operation should be handled.
void verify (const MCInstrInfo &MII) const
Perform simple self-diagnostic and assert if there is anything obviously wrong with the actions set up.
void setAction (const InstrAspect &Aspect, LegalizeAction Action)
More friendly way to set an action for common types that have an LLT representation.
void setLegalizeScalarToDifferentSizeStrategy (const unsigned Opcode, const unsigned TypeIdx, SizeChangeStrategy S)
The setAction calls record the non-size-changing legalization actions to take on specificly-sized types.
void setLegalizeVectorElementToDifferentSizeStrategy (const unsigned Opcode, const unsigned TypeIdx, SizeChangeStrategy S)
See also setLegalizeScalarToDifferentSizeStrategy.
const LegalizeRuleSet & getActionDefinitions (unsigned Opcode) const
Get the action definitions for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (unsigned Opcode)
Get the action definition builder for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (std::initializer_list< unsigned > Opcodes)
Get the action definition builder for the given set of opcodes.
void aliasActionDefinitions (unsigned OpcodeTo, unsigned OpcodeFrom)
LegalizeActionStep getAction (const LegalityQuery &Query) const
Determine what action should be taken to legalize the described instruction.
LegalizeActionStep getAction (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
Determine what action should be taken to legalize the given generic instruction.
bool isLegal (const LegalityQuery &Query) const
bool isLegalOrCustom (const LegalityQuery &Query) const
bool isLegal (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
bool isLegalOrCustom (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
virtual unsigned getExtOpcodeForWideningConstant (LLT SmallTy) const
Return the opcode (SEXT/ZEXT/ANYEXT) that should be performed while widening a constant of type SmallTy which targets can override.
Additional Inherited Members
Public Types inherited from llvm::LegalizerInfo
using SizeAndAction = std::pair<uint16_t, LegalizeAction>
using SizeAndActionsVec = std::vector<SizeAndAction>
using SizeChangeStrategy
Static Public Member Functions inherited from llvm::LegalizerInfo
static bool needsLegalizingToDifferentSize (const LegalizeAction Action)
static SizeAndActionsVec unsupportedForDifferentSizes (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular operation consists of only supporting a specific set of type sizes.
static SizeAndActionsVec widenToLargerTypesAndNarrowToLargest (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular operation consists of widening the type to a large legal type, unless there is no such type and then instead it should be narrowed to the largest legal type.
static SizeAndActionsVec widenToLargerTypesUnsupportedOtherwise (const SizeAndActionsVec &v)
static SizeAndActionsVec narrowToSmallerAndUnsupportedIfTooSmall (const SizeAndActionsVec &v)
static SizeAndActionsVec narrowToSmallerAndWidenToSmallest (const SizeAndActionsVec &v)
static SizeAndActionsVec moreToWiderTypesAndLessToWidest (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular vector operation consists of having more elements in the vector, to a type that is legal.
static SizeAndActionsVec increaseToLargerTypesAndDecreaseToLargest (const SizeAndActionsVec &v, LegalizeAction IncreaseAction, LegalizeAction DecreaseAction)
Helper function to implement many typical SizeChangeStrategy functions.
static SizeAndActionsVec decreaseToSmallerTypesAndIncreaseToSmallest (const SizeAndActionsVec &v, LegalizeAction DecreaseAction, LegalizeAction IncreaseAction)
Helper function to implement many typical SizeChangeStrategy functions.
Detailed Description
This class provides the information for the target register banks.
Definition at line 27 of file AArch64LegalizerInfo.h.
Constructor & Destructor Documentation
AArch64LegalizerInfo()
AArch64LegalizerInfo::AArch64LegalizerInfo (const AArch64Subtarget & ST)
Definition at line 36 of file AArch64LegalizerInfo.cpp.
References llvm::LegalityPredicates::all(), llvm::LegalityPredicates::atomicOrderingAtLeastOrStrongerThan(), llvm::LegalizeRuleSet::clampMaxNumElements(), llvm::LegalizeRuleSet::clampNumElements(), llvm::LegalizeRuleSet::clampScalar(), llvm::LegalizerInfo::computeTables(), llvm::LegalizeRuleSet::custom(), llvm::LegalizeRuleSet::customForCartesianProduct(), llvm::LegalizeRuleSet::customIf(), llvm::LegalizeRuleSet::fewerElementsIf(), llvm::LegalizerInfo::getActionDefinitionsBuilder(), llvm::LLT::getAddressSpace(), llvm::LLT::getElementType(), llvm::LLT::getSizeInBits(), llvm::LLT::isPointer(), llvm::isPowerOf2_32(), llvm::LLT::isVector(), llvm::LegalityPredicates::isVector(), llvm::LegalizeRuleSet::legalFor(), llvm::LegalizeRuleSet::legalForCartesianProduct(), llvm::LegalizeRuleSet::legalForTypesWithMemDesc(), llvm::LegalizeRuleSet::legalIf(), llvm::LegalizeRuleSet::libcallFor(), llvm::Log2_32_Ceil(), llvm::LegalizeRuleSet::lower(), llvm::LegalizeRuleSet::lowerIf(), llvm::LegalizeRuleSet::lowerIfMemSizeNotPow2(), llvm::LegalizeRuleSet::maxScalarIf(), llvm::LegalizeRuleSet::minScalar(), llvm::LegalizeRuleSet::minScalarEltSameAsIf(), llvm::LegalizeRuleSet::minScalarOrEltIf(), llvm::LegalizeRuleSet::minScalarSameAs(), llvm::Monotonic, llvm::LegalizeRuleSet::moreElementsToNextPow2(), llvm::LLT::pointer(), llvm::LLT::scalar(), llvm::LegalizeMutations::scalarize(), llvm::LegalizeRuleSet::scalarize(), llvm::CodeModel::Small, llvm::LegalityPredicates::typeInSet(), llvm::LegalityPredicates::typeIs(), llvm::LegalizeRuleSet::unsupportedIf(), llvm::LegalizeRuleSet::unsupportedIfMemSizeNotPow2(), llvm::LLT::vector(), verify, llvm::LegalizeRuleSet::widenScalarIf(), llvm::LegalizeMutations::widenScalarOrEltToNextPow2(), and llvm::LegalizeRuleSet::widenScalarToNextPow2().
Member Function Documentation
legalizeCustom()
bool AArch64LegalizerInfo::legalizeCustom (LegalizerHelper & Helper, MachineInstr & MI) const override virtual
Called for instructions with the Custom LegalizationAction.
Reimplemented from llvm::LegalizerInfo.
Definition at line 697 of file AArch64LegalizerInfo.cpp.
References llvm::MachineIRBuilder::getMRI(), llvm_unreachable, MI, llvm::LegalizerHelper::MIRBuilder, MRI, and llvm::LegalizerHelper::Observer.
legalizeIntrinsic()
bool AArch64LegalizerInfo::legalizeIntrinsic (LegalizerHelper & Helper, MachineInstr & MI) const override virtual
Returns
true if MI is either legal or has been legalized and false if not legal. Return true if MI is either legal or has been legalized and false if not legal.
Reimplemented from llvm::LegalizerInfo.
Definition at line 823 of file AArch64LegalizerInfo.cpp.
The documentation for this class was generated from the following files:
lib/Target/AArch64/GISel/AArch64LegalizerInfo.h
lib/Target/AArch64/GISel/AArch64LegalizerInfo.cpp