LLVM: llvm::orc::BasicObjectLayerMaterializationUnit Class Reference
llvm::orc::BasicObjectLayerMaterializationUnit Class Reference
Materializes the given object file (represented by a MemoryBuffer instance) by calling 'emit' on the given ObjectLayer.
#include "llvm/ExecutionEngine/Orc/Layer.h"
Public Member Functions
BasicObjectLayerMaterializationUnit (ObjectLayer &L, std::unique_ptr< MemoryBuffer > O, SymbolFlagsMap SymbolFlags, SymbolStringPtr InitSymbol)
StringRef getName () const override
Return the buffer's identifier as the name for this MaterializationUnit.
Public Member Functions inherited from llvm::orc::MaterializationUnit
MaterializationUnit (SymbolFlagsMap InitalSymbolFlags, SymbolStringPtr InitSymbol)
virtual ~MaterializationUnit ()
const SymbolFlagsMap & getSymbols () const
Return the set of symbols that this source provides.
const SymbolStringPtr & getInitializerSymbol () const
Returns the initialization symbol for this MaterializationUnit (if any).
void doDiscard (const JITDylib &JD, const SymbolStringPtr &Name)
Called by JITDylibs to notify MaterializationUnits that the given symbol has been overridden.
Static Public Member Functions
static Expected< std::unique_ptr< BasicObjectLayerMaterializationUnit > > Create (ObjectLayer &L, std::unique_ptr< MemoryBuffer > O)
Additional Inherited Members
Protected Attributes inherited from llvm::orc::MaterializationUnit
SymbolFlagsMap SymbolFlags
SymbolStringPtr InitSymbol
Detailed Description
Materializes the given object file (represented by a MemoryBuffer instance) by calling 'emit' on the given ObjectLayer.
Definition at line 158 of file Layer.h.
Constructor & Destructor Documentation
BasicObjectLayerMaterializationUnit()
llvm::orc::BasicObjectLayerMaterializationUnit::BasicObjectLayerMaterializationUnit (ObjectLayer & L, std::unique_ptr< MemoryBuffer > O, SymbolFlagsMap SymbolFlags, SymbolStringPtr InitSymbol)
Definition at line 188 of file Layer.cpp.
Referenced by Create().
Member Function Documentation
Create()
Expected< std::unique_ptr< BasicObjectLayerMaterializationUnit > > llvm::orc::BasicObjectLayerMaterializationUnit::Create (ObjectLayer & L, std::unique_ptr< MemoryBuffer > O) static
Definition at line 172 of file Layer.cpp.
References BasicObjectLayerMaterializationUnit(), llvm::orc::ObjectLayer::getExecutionSession(), llvm::orc::getObjectSymbolInfo(), and llvm::orc::MaterializationUnit::InitSymbol.
Referenced by llvm::orc::ObjectLayer::add().
getName()
StringRef llvm::orc::BasicObjectLayerMaterializationUnit::getName () const override virtual
Return the buffer's identifier as the name for this MaterializationUnit.
Implements llvm::orc::MaterializationUnit.
Definition at line 194 of file Layer.cpp.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Layer.h
lib/ExecutionEngine/Orc/Layer.cpp