LLVM: llvm::ImmutableGraph< NodeValueT, EdgeValueT > Class Template Reference
llvm::ImmutableGraph< NodeValueT, EdgeValueT > Class Template Reference
#include "Target/X86/ImmutableGraph.h"
Classes
class Edge
class EdgeSet
class Node
class NodeSet
Public Types
using node_value_type = NodeValueT
using edge_value_type = EdgeValueT
using size_type = int
Public Member Functions
ArrayRef< Node > nodes () const
const Node * nodes_begin () const
const Node * nodes_end () const
ArrayRef< Edge > edges () const
const Edge * edges_begin () const
const Edge * edges_end () const
size_type nodes_size () const
size_type edges_size () const
size_type getNodeIndex (const Node &N) const
size_type getEdgeIndex (const Edge &E) const
Protected Member Functions
ImmutableGraph (std::unique_ptr< Node[]> Nodes, std::unique_ptr< Edge[]> Edges, size_type NodesSize, size_type EdgesSize)
ImmutableGraph (const ImmutableGraph &)=delete
ImmutableGraph (ImmutableGraph &&)=delete
ImmutableGraph & operator= (const ImmutableGraph &)=delete
ImmutableGraph & operator= (ImmutableGraph &&)=delete
Friends
template<typename >
class ImmutableGraphBuilder
Detailed Description
template<typename NodeValueT, typename EdgeValueT>
class llvm::ImmutableGraph< NodeValueT, EdgeValueT >
Definition at line 38 of file ImmutableGraph.h.
Member Typedef Documentation
edge_value_type
template<typename NodeValueT , typename EdgeValueT > using llvm::ImmutableGraph< NodeValueT, EdgeValueT >::edge_value_type = EdgeValueT
Definition at line 44 of file ImmutableGraph.h.
node_value_type
template<typename NodeValueT , typename EdgeValueT > using llvm::ImmutableGraph< NodeValueT, EdgeValueT >::node_value_type = NodeValueT
Definition at line 43 of file ImmutableGraph.h.
size_type
template<typename NodeValueT , typename EdgeValueT > using llvm::ImmutableGraph< NodeValueT, EdgeValueT >::size_type = int
Definition at line 45 of file ImmutableGraph.h.
Constructor & Destructor Documentation
ImmutableGraph() [1/3]
template<typename NodeValueT , typename EdgeValueT > llvm::ImmutableGraph< NodeValueT, EdgeValueT >::ImmutableGraph (std::unique_ptr< Node[]> Nodes, std::unique_ptr< Edge[]> Edges, size_type NodesSize, size_type EdgesSize) inline protected
Definition at line 80 of file ImmutableGraph.h.
ImmutableGraph() [2/3]
template<typename NodeValueT , typename EdgeValueT > llvm::ImmutableGraph< NodeValueT, EdgeValueT >::ImmutableGraph (const ImmutableGraph< NodeValueT, EdgeValueT > &) protected delete
ImmutableGraph() [3/3]
template<typename NodeValueT , typename EdgeValueT > llvm::ImmutableGraph< NodeValueT, EdgeValueT >::ImmutableGraph (ImmutableGraph< NodeValueT, EdgeValueT > &&) protected delete
Member Function Documentation
edges()
template<typename NodeValueT , typename EdgeValueT > ArrayRef< Edge > llvm::ImmutableGraph< NodeValueT, EdgeValueT >::edges () const inline
Definition at line 94 of file ImmutableGraph.h.
References llvm::makeArrayRef().
Referenced by llvm::ImmutableGraph< NodeValueT, EdgeValueT >::edges_begin(), and llvm::ImmutableGraph< NodeValueT, EdgeValueT >::edges_end().
edges_begin()
template<typename NodeValueT , typename EdgeValueT > const Edge * llvm::ImmutableGraph< NodeValueT, EdgeValueT >::edges_begin () const inline
Definition at line 95 of file ImmutableGraph.h.
References llvm::ImmutableGraph< NodeValueT, EdgeValueT >::edges().
Referenced by llvm::ImmutableGraph< NodeValueT, EdgeValueT >::getEdgeIndex(), and llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator::operator*().
edges_end()
template<typename NodeValueT , typename EdgeValueT > const Edge * llvm::ImmutableGraph< NodeValueT, EdgeValueT >::edges_end () const inline
Definition at line 96 of file ImmutableGraph.h.
References llvm::ImmutableGraph< NodeValueT, EdgeValueT >::edges().
edges_size()
template<typename NodeValueT , typename EdgeValueT > size_type llvm::ImmutableGraph< NodeValueT, EdgeValueT >::edges_size () const inline
Definition at line 99 of file ImmutableGraph.h.
getEdgeIndex()
template<typename NodeValueT , typename EdgeValueT > size_type llvm::ImmutableGraph< NodeValueT, EdgeValueT >::getEdgeIndex (const Edge & E) const inline
Definition at line 106 of file ImmutableGraph.h.
References E, and llvm::ImmutableGraph< NodeValueT, EdgeValueT >::edges_begin().
getNodeIndex()
template<typename NodeValueT , typename EdgeValueT > size_type llvm::ImmutableGraph< NodeValueT, EdgeValueT >::getNodeIndex (const Node & N) const inline
Definition at line 102 of file ImmutableGraph.h.
References N, and llvm::ImmutableGraph< NodeValueT, EdgeValueT >::nodes_begin().
nodes()
template<typename NodeValueT , typename EdgeValueT > ArrayRef< Node > llvm::ImmutableGraph< NodeValueT, EdgeValueT >::nodes () const inline
Definition at line 90 of file ImmutableGraph.h.
References llvm::makeArrayRef().
Referenced by llvm::ImmutableGraph< NodeValueT, EdgeValueT >::nodes_begin(), and llvm::ImmutableGraph< NodeValueT, EdgeValueT >::nodes_end().
nodes_begin()
template<typename NodeValueT , typename EdgeValueT > const Node * llvm::ImmutableGraph< NodeValueT, EdgeValueT >::nodes_begin () const inline
Definition at line 91 of file ImmutableGraph.h.
References llvm::ImmutableGraph< NodeValueT, EdgeValueT >::nodes().
Referenced by llvm::ImmutableGraph< NodeValueT, EdgeValueT >::getNodeIndex(), and llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator::operator*().
nodes_end()
template<typename NodeValueT , typename EdgeValueT > const Node * llvm::ImmutableGraph< NodeValueT, EdgeValueT >::nodes_end () const inline
Definition at line 92 of file ImmutableGraph.h.
References llvm::ImmutableGraph< NodeValueT, EdgeValueT >::nodes().
nodes_size()
template<typename NodeValueT , typename EdgeValueT > size_type llvm::ImmutableGraph< NodeValueT, EdgeValueT >::nodes_size () const inline
Definition at line 98 of file ImmutableGraph.h.
operator=() [1/2]
template<typename NodeValueT , typename EdgeValueT > ImmutableGraph & llvm::ImmutableGraph< NodeValueT, EdgeValueT >::operator= (const ImmutableGraph< NodeValueT, EdgeValueT > &) protected delete
operator=() [2/2]
template<typename NodeValueT , typename EdgeValueT > ImmutableGraph & llvm::ImmutableGraph< NodeValueT, EdgeValueT >::operator= (ImmutableGraph< NodeValueT, EdgeValueT > &&) protected delete
Friends And Related Symbol Documentation
ImmutableGraphBuilder
template<typename NodeValueT , typename EdgeValueT > template<typename > friend class ImmutableGraphBuilder friend
Definition at line 40 of file ImmutableGraph.h.
The documentation for this class was generated from the following file:
lib/Target/X86/ImmutableGraph.h