LLVM: llvm::orc::shared::detail::ResultTraits< RetT > Class Template Reference
llvm::orc::shared::detail::ResultTraits< RetT > Class Template Reference
#include "llvm/ExecutionEngine/Orc/Shared/RPCUtils.h"
Public Types
using ErrorReturnType = Expected<RetT>
using ReturnPromiseType = std::promise<ErrorReturnType>
using ReturnFutureType = std::future<ErrorReturnType>
Static Public Member Functions
static ErrorReturnType createBlankErrorReturnValue ()
static void consumeAbandoned (ErrorReturnType RetOrErr)
Detailed Description
template<typename RetT>
class llvm::orc::shared::detail::ResultTraits< RetT >
Definition at line 217 of file RPCUtils.h.
Member Typedef Documentation
ErrorReturnType
template<typename RetT > using llvm::orc::shared::detail::ResultTraits< RetT >::ErrorReturnType = Expected<RetT>
Definition at line 220 of file RPCUtils.h.
ReturnFutureType
template<typename RetT > using llvm::orc::shared::detail::ResultTraits< RetT >::ReturnFutureType = std::future<ErrorReturnType>
Definition at line 233 of file RPCUtils.h.
ReturnPromiseType
template<typename RetT > using llvm::orc::shared::detail::ResultTraits< RetT >::ReturnPromiseType = std::promise<ErrorReturnType>
Definition at line 230 of file RPCUtils.h.
Member Function Documentation
consumeAbandoned()
template<typename RetT > static void llvm::orc::shared::detail::ResultTraits< RetT >::consumeAbandoned (ErrorReturnType RetOrErr) inline static
Definition at line 243 of file RPCUtils.h.
References llvm::consumeError().
Referenced by llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callB(), and llvm::orc::shared::MultiThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callNB().
createBlankErrorReturnValue()
template<typename RetT > static ErrorReturnType llvm::orc::shared::detail::ResultTraits< RetT >::createBlankErrorReturnValue () inline static
Definition at line 238 of file RPCUtils.h.
Referenced by llvm::orc::shared::SingleThreadedRPCEndpoint< ChannelT, FunctionIdT, SequenceNumberT >::callB().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/RPCUtils.h