LLVM: llvm::CallbackVH Class Reference
llvm::CallbackVH Class Reference
Value handle with callbacks on RAUW and destruction.
#include "llvm/IR/ValueHandle.h"
Public Member Functions
CallbackVH ()
CallbackVH (Value *P)
CallbackVH (const Value *P)
operator Value * () const
virtual void deleted ()
Callback for Value destruction.
virtual void allUsesReplacedWith (Value *)
Callback for Value RAUW.
Public Member Functions inherited from llvm::ValueHandleBase
ValueHandleBase (HandleBaseKind Kind)
ValueHandleBase (HandleBaseKind Kind, Value *V)
~ValueHandleBase ()
Value * operator= (Value *RHS)
Value * operator= (const ValueHandleBase &RHS)
Value * operator-> () const
Value & operator* () const
Protected Member Functions
~CallbackVH ()=default
CallbackVH (const CallbackVH &)=default
CallbackVH & operator= (const CallbackVH &)=default
void setValPtr (Value *P)
Protected Member Functions inherited from llvm::ValueHandleBase
ValueHandleBase (const ValueHandleBase &RHS)
ValueHandleBase (HandleBaseKind Kind, const ValueHandleBase &RHS)
Value * getValPtr () const
void RemoveFromUseList ()
Remove this ValueHandle from its current use list.
void clearValPtr ()
Clear the underlying pointer without clearing the use list.
Additional Inherited Members
Static Public Member Functions inherited from llvm::ValueHandleBase
static void ValueIsDeleted (Value *V)
static void ValueIsRAUWd (Value *Old, Value *New)
Protected Types inherited from llvm::ValueHandleBase
enum HandleBaseKind { Assert , Callback , Weak , WeakTracking }
This indicates what sub class the handle actually is.
Static Protected Member Functions inherited from llvm::ValueHandleBase
static bool isValid (Value *V)
Detailed Description
Value handle with callbacks on RAUW and destruction.
This is a value handle that allows subclasses to define callbacks that run when the underlying Value has RAUW called on it or is destroyed. This class can be used as the key of a map, as long as the user takes it out of the map before calling setValPtr() (since the map has to rearrange itself when the pointer changes). Unlike ValueHandleBase, this class has a vtable.
Definition at line 383 of file ValueHandle.h.
Constructor & Destructor Documentation
~CallbackVH()
llvm::CallbackVH::~CallbackVH () protected default
CallbackVH() [1/4]
llvm::CallbackVH::CallbackVH (const CallbackVH &) protected default
CallbackVH() [2/4]
llvm::CallbackVH::CallbackVH () inline
Definition at line 395 of file ValueHandle.h.
CallbackVH() [3/4]
llvm::CallbackVH::CallbackVH (Value * P) inline
Definition at line 396 of file ValueHandle.h.
CallbackVH() [4/4]
llvm::CallbackVH::CallbackVH (const Value * P) inline
Definition at line 397 of file ValueHandle.h.
Member Function Documentation
allUsesReplacedWith()
virtual void llvm::CallbackVH::allUsesReplacedWith (Value *) inline virtual
Callback for Value RAUW.
Called when this->getValPtr()->replaceAllUsesWith(new_value) is called, before any of the uses have actually been replaced. If WeakTrackingVH were implemented as a CallbackVH, it would use this method to call setValPtr(new_value). AssertingVH would do nothing in this method.
Reimplemented in llvm::cflaa::FunctionHandle< AAResult >, llvm::PreservedCFGCheckerInstrumentation::CFG::BBGuard, llvm::ValueMapCallbackVH< KeyT, ValueT, Config >, and llvm::MMIAddrLabelMapCallbackPtr.
Definition at line 423 of file ValueHandle.h.
deleted()
virtual void llvm::CallbackVH::deleted () inline virtual
Callback for Value destruction.
Called when this->getValPtr() is destroyed, inside ~Value(), so you may call any non-virtual Value method on getValPtr(), but no subclass methods. If WeakTrackingVH were implemented as a CallbackVH, it would use this method to call setValPtr(NULL). AssertingVH would use this method to cause an assertion failure.
All implementations must remove the reference from this object to the Value that's being destroyed.
Reimplemented in llvm::bfi_detail::BFICallbackVH< BasicBlock, BFIImplT >, llvm::cflaa::FunctionHandle< AAResult >, llvm::ValueMapCallbackVH< KeyT, ValueT, Config >, llvm::PreservedCFGCheckerInstrumentation::CFG::BBGuard, and llvm::MMIAddrLabelMapCallbackPtr.
Definition at line 414 of file ValueHandle.h.
References setValPtr().
Referenced by llvm::PreservedCFGCheckerInstrumentation::CFG::BBGuard::allUsesReplacedWith(), and llvm::PreservedCFGCheckerInstrumentation::CFG::BBGuard::deleted().
operator Value *()
llvm::CallbackVH::operator Value * () const inline
Definition at line 399 of file ValueHandle.h.
References llvm::ValueHandleBase::getValPtr().
operator=()
CallbackVH & llvm::CallbackVH::operator= (const CallbackVH &) protected default
setValPtr()
void llvm::CallbackVH::setValPtr (Value * P) inline protected
Definition at line 390 of file ValueHandle.h.
References llvm::ValueHandleBase::operator=(), and P.
Referenced by deleted(), and llvm::IVStrideUse::setUser().
The documentation for this class was generated from the following files:
include/llvm/IR/ValueHandle.h
lib/IR/Value.cpp