LLVM: llvm::TarWriter Class Reference
llvm::TarWriter Class Reference
#include "llvm/Support/TarWriter.h"
Public Member Functions
void append (StringRef Path, StringRef Data)
Static Public Member Functions
static Expected< std::unique_ptr< TarWriter > > create (StringRef OutputPath, StringRef BaseDir)
Detailed Description
Definition at line 18 of file TarWriter.h.
Member Function Documentation
append()
void TarWriter::append (StringRef Path, StringRef Data)
Definition at line 184 of file TarWriter.cpp.
References BlockSize, llvm::sys::path::convert_to_slash(), llvm::Data, llvm::raw_ostream::flush(), llvm::StringSet< AllocatorTy >::insert(), Name, pad(), llvm::raw_fd_ostream::seek(), splitUstar(), llvm::raw_ostream::tell(), writePaxHeader(), and writeUstarHeader().
create()
Expected< std::unique_ptr< TarWriter > > TarWriter::create (StringRef OutputPath, StringRef BaseDir) static
Definition at line 169 of file TarWriter.cpp.
The documentation for this class was generated from the following files:
include/llvm/Support/TarWriter.h
lib/Support/TarWriter.cpp