LLVM: llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > Class Template Reference
llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > Class Template Reference
The class represents the base of a range of indexed_accessor_iterators.
#include "llvm/ADT/STLExtras.h"
Classes
class iterator
An iterator element of this range.
Public Types
using RangeBaseT
Public Member Functions
indexed_accessor_range_base (iterator begin, iterator end)
indexed_accessor_range_base (const iterator_range< iterator > &range)
indexed_accessor_range_base (BaseT base, ptrdiff_t count)
iterator begin () const
iterator end () const
ReferenceT operator[] (unsigned index) const
ReferenceT front () const
ReferenceT back () const
template<typename OtherT >
bool operator== (const OtherT &other) const
Compare this range with another.
template<typename OtherT >
bool operator!= (const OtherT &other) const
size_t size () const
Return the size of this range.
bool empty () const
Return if the range is empty.
DerivedT slice (size_t n, size_t m) const
Drop the first N elements, and keep M elements.
DerivedT drop_front (size_t n=1) const
Drop the first n elements.
DerivedT drop_back (size_t n=1) const
Drop the last n elements.
DerivedT take_front (size_t n=1) const
Take the first n elements.
DerivedT take_back (size_t n=1) const
Take the last n elements.
template<typename RangeT , typename = std::enable_if_t<std::is_constructible< RangeT, iterator_range<iterator>>::value>>
operator RangeT () const
Allow conversion to any type accepting an iterator_range.
const BaseT & getBase () const
Returns the base of this range.
Protected Member Functions
indexed_accessor_range_base (const indexed_accessor_range_base &)=default
indexed_accessor_range_base (indexed_accessor_range_base &&)=default
indexed_accessor_range_base & operator= (const indexed_accessor_range_base &)=default
Protected Attributes
BaseT base
The base that owns the provided range of values.
ptrdiff_t count
The size from the owning range.
Detailed Description
template<typename DerivedT, typename BaseT, typename T, typename PointerT = T *, typename ReferenceT = T &>
class llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >
The class represents the base of a range of indexed_accessor_iterators.
It provides support for many different range functionalities, e.g. drop_front/slice/etc.. Derived range classes must implement the following static methods:
ReferenceT dereference_iterator(const BaseT &base, ptrdiff_t index)
Dereference an iterator pointing to the base object at the given index.
BaseT offset_base(const BaseT &base, ptrdiff_t index)
Return a new base that is offset from the provide base by 'index' elements.
Definition at line 1083 of file STLExtras.h.
Member Typedef Documentation
RangeBaseT
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> using llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::RangeBaseT
Initial value:
      indexed_accessor_range_base<DerivedT, BaseT, T, PointerT, ReferenceT>
Definition at line 1085 of file STLExtras.h.
Constructor & Destructor Documentation
indexed_accessor_range_base() [1/5]
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (iterator begin, iterator end) inline
Definition at line 1107 of file STLExtras.h.
indexed_accessor_range_base() [2/5]
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (const iterator_range< iterator > & range) inline
Definition at line 1110 of file STLExtras.h.
indexed_accessor_range_base() [3/5]
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (BaseT base, ptrdiff_t count) inline
Definition at line 1112 of file STLExtras.h.
indexed_accessor_range_base() [4/5]
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (const indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > &) protected default
indexed_accessor_range_base() [5/5]
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::indexed_accessor_range_base (indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > &&) protected default
Member Function Documentation
back()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> ReferenceT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::back () const inline
Definition at line 1125 of file STLExtras.h.
References assert(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::empty(), and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
begin()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> iterator llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::begin () const inline
Definition at line 1115 of file STLExtras.h.
References llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::base.
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator==().
drop_back()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> DerivedT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_back (size_t n = 1) const inline
Drop the last n elements.
Definition at line 1158 of file STLExtras.h.
References assert(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::base, and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::take_front().
drop_front()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> DerivedT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_front (size_t n = 1) const inline
Drop the first n elements.
Definition at line 1153 of file STLExtras.h.
References assert(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size(), and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::slice().
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::take_back().
empty()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> bool llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::empty () const inline
Return if the range is empty.
Definition at line 1144 of file STLExtras.h.
References llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::back(), and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::front().
end()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> iterator llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::end () const inline
Definition at line 1116 of file STLExtras.h.
References llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::base, and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::count.
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator==().
front()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> ReferenceT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::front () const inline
Definition at line 1121 of file STLExtras.h.
References assert(), and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::empty().
getBase()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> const BaseT & llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::getBase () const inline
Returns the base of this range.
Definition at line 1183 of file STLExtras.h.
References llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::base.
operator RangeT()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> template<typename RangeT , typename = std::enable_if_t<std::is_constructible< RangeT, iterator_range<iterator>>::value>> llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator RangeT () const inline
Allow conversion to any type accepting an iterator_range.
Definition at line 1178 of file STLExtras.h.
operator!=()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> template<typename OtherT > bool llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator!= (const OtherT & other) const inline
Definition at line 1136 of file STLExtras.h.
operator=()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> indexed_accessor_range_base & llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator= (const indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT > &) protected default
operator==()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> template<typename OtherT > bool llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator== (const OtherT & other) const inline
Compare this range with another.
Definition at line 1131 of file STLExtras.h.
References llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::begin(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::end(), and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
operator[]()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> ReferenceT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator[] (unsigned index) const inline
Definition at line 1117 of file STLExtras.h.
References assert(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::base, and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
size()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> size_t llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size () const inline
Return the size of this range.
Definition at line 1141 of file STLExtras.h.
References llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::count.
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::back(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_back(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_front(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::empty(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator==(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator[](), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::slice(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::take_back(), and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::take_front().
slice()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> DerivedT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::slice (size_t n, size_t m) const inline
Drop the first N elements, and keep M elements.
Definition at line 1147 of file STLExtras.h.
References assert(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::base, and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_front().
take_back()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> DerivedT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::take_back (size_t n = 1) const inline
Take the last n elements.
Definition at line 1170 of file STLExtras.h.
References llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_front(), and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
take_front()
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> DerivedT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::take_front (size_t n = 1) const inline
Take the first n elements.
Definition at line 1164 of file STLExtras.h.
References llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_back(), and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
Member Data Documentation
base
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> BaseT llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::base protected
The base that owns the provided range of values.
Definition at line 1198 of file STLExtras.h.
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::begin(), llvm::indexed_accessor_range< DerivedT, BaseT, T, PointerT, ReferenceT >::dereference_iterator(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::drop_back(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::end(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::getBase(), llvm::indexed_accessor_range< DerivedT, BaseT, T, PointerT, ReferenceT >::getBase(), llvm::indexed_accessor_range< DerivedT, BaseT, T, PointerT, ReferenceT >::getStartIndex(), llvm::indexed_accessor_range< DerivedT, BaseT, T, PointerT, ReferenceT >::offset_base(), llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::operator[](), and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::slice().
count
template<typename DerivedT , typename BaseT , typename T , typename PointerT = T *, typename ReferenceT = T &> ptrdiff_t llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::count protected
The size from the owning range.
Definition at line 1200 of file STLExtras.h.
Referenced by llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::end(), and llvm::detail::indexed_accessor_range_base< DerivedT, BaseT, T, PointerT, ReferenceT >::size().
The documentation for this class was generated from the following file:
include/llvm/ADT/STLExtras.h