LLVM: llvm::orc::Platform Class Reference
llvm::orc::Platform Class Reference abstract
Platforms set up standard symbols and mediate interactions between dynamic initializers (e.g.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
virtual ~Platform ()
virtual Error setupJITDylib (JITDylib &JD)=0
This method will be called outside the session lock each time a JITDylib is created (unless it is created with EmptyJITDylib set) to allow the Platform to install any JITDylib specific standard symbols (e.g __dso_handle).
virtual Error notifyAdding (ResourceTracker &RT, const MaterializationUnit &MU)=0
This method will be called under the ExecutionSession lock each time a MaterializationUnit is added to a JITDylib.
virtual Error notifyRemoving (ResourceTracker &RT)=0
This method will be called under the ExecutionSession lock when a ResourceTracker is removed.
Static Public Member Functions
static Expected< DenseMap< JITDylib *, SymbolMap > > lookupInitSymbols (ExecutionSession &ES, const DenseMap< JITDylib *, SymbolLookupSet > &InitSyms)
A utility function for looking up initializer symbols.
Detailed Description
Platforms set up standard symbols and mediate interactions between dynamic initializers (e.g.
C++ static constructors) and ExecutionSession state. Note that Platforms do not automatically run initializers: clients are still responsible for doing this.
Definition at line 1194 of file Core.h.
Constructor & Destructor Documentation
~Platform()
llvm::orc::Platform::~Platform () virtual
Definition at line 1672 of file Core.cpp.
Member Function Documentation
lookupInitSymbols()
Expected< DenseMap< JITDylib *, SymbolMap > > llvm::orc::Platform::lookupInitSymbols (ExecutionSession & ES, const DenseMap< JITDylib *, SymbolLookupSet > & InitSyms) static
A utility function for looking up initializer symbols.
Performs a blocking lookup for the given symbols in each of the given JITDylibs.
Definition at line 1674 of file Core.cpp.
References assert(), llvm::dbgs(), llvm::joinErrors(), LLVM_DEBUG, llvm::Lock, llvm::orc::ExecutionSession::lookup(), llvm::orc::MatchAllSymbols, llvm::orc::NoDependenciesToRegister, llvm::orc::Ready, llvm::orc::Static, and llvm::Error::success().
Referenced by llvm::orc::MachOPlatform::getInitializerSequence().
notifyAdding()
virtual Error llvm::orc::Platform::notifyAdding (ResourceTracker & RT, const MaterializationUnit & MU) pure virtual
This method will be called under the ExecutionSession lock each time a MaterializationUnit is added to a JITDylib.
Implemented in llvm::orc::MachOPlatform.
notifyRemoving()
virtual Error llvm::orc::Platform::notifyRemoving (ResourceTracker & RT) pure virtual
This method will be called under the ExecutionSession lock when a ResourceTracker is removed.
Implemented in llvm::orc::MachOPlatform.
setupJITDylib()
virtual Error llvm::orc::Platform::setupJITDylib (JITDylib & JD) pure virtual
This method will be called outside the session lock each time a JITDylib is created (unless it is created with EmptyJITDylib set) to allow the Platform to install any JITDylib specific standard symbols (e.g __dso_handle).
Implemented in llvm::orc::MachOPlatform.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp