LLVM: llvm::IRBuilder< FolderTy, InserterTy > Class Template Reference
llvm::IRBuilder< FolderTy, InserterTy > Class Template Reference
This provides a uniform API for creating instructions and inserting them into a basic block: either at the end of a BasicBlock, or at a specific iterator location in a block.
#include "llvm/IR/IRBuilder.h"
Public Member Functions
IRBuilder (LLVMContext &C, FolderTy Folder, InserterTy Inserter=InserterTy(), MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (LLVMContext &C, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (BasicBlock *TheBB, FolderTy Folder, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (BasicBlock *TheBB, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (Instruction *IP, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (BasicBlock *TheBB, BasicBlock::iterator IP, FolderTy Folder, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (BasicBlock *TheBB, BasicBlock::iterator IP, MDNode *FPMathTag=nullptr, ArrayRef< OperandBundleDef > OpBundles=None)
IRBuilder (const IRBuilder &)=delete
Avoid copying the full IRBuilder.
InserterTy & getInserter ()
Public Member Functions inherited from llvm::IRBuilderBase
IRBuilderBase (LLVMContext &context, const IRBuilderFolder &Folder, const IRBuilderDefaultInserter &Inserter, MDNode *FPMathTag, ArrayRef< OperandBundleDef > OpBundles)
template<typename InstTy >
InstTy * Insert (InstTy *I, const Twine &Name="") const
Insert and return the specified instruction.
Constant * Insert (Constant *C, const Twine &="") const
No-op overload to handle constants.
Value * Insert (Value *V, const Twine &Name="") const
void ClearInsertionPoint ()
Clear the insertion point: created instructions will not be inserted into a block.
BasicBlock * GetInsertBlock () const
BasicBlock::iterator GetInsertPoint () const
LLVMContext & getContext () const
void SetInsertPoint (BasicBlock *TheBB)
This specifies that created instructions should be appended to the end of the specified block.
void SetInsertPoint (Instruction *I)
This specifies that created instructions should be inserted before the specified instruction.
void SetInsertPoint (BasicBlock *TheBB, BasicBlock::iterator IP)
This specifies that created instructions should be inserted at the specified point.
void SetCurrentDebugLocation (DebugLoc L)
Set location information used by debugging information.
void CollectMetadataToCopy (Instruction *Src, ArrayRef< unsigned > MetadataKinds)
Collect metadata with IDs MetadataKinds from Src which should be added to all created instructions.
DebugLoc getCurrentDebugLocation () const
Get location information used by debugging information.
void SetInstDebugLocation (Instruction *I) const
If this builder has a current debug location, set it on the specified instruction.
void AddMetadataToInst (Instruction *I) const
Add all entries in MetadataToCopy to I.
Type * getCurrentFunctionReturnType () const
Get the return type of the current function that we're emitting into.
InsertPoint saveIP () const
Returns the current insert point.
InsertPoint saveAndClearIP ()
Returns the current insert point, clearing it in the process.
void restoreIP (InsertPoint IP)
Sets the current insert point to a previously-saved location.
MDNode * getDefaultFPMathTag () const
Get the floating point math metadata being used.
FastMathFlags getFastMathFlags () const
Get the flags to be applied to created floating point ops.
FastMathFlags & getFastMathFlags ()
void clearFastMathFlags ()
Clear the fast-math flags.
void setDefaultFPMathTag (MDNode *FPMathTag)
Set the floating point math metadata to be used.
void setFastMathFlags (FastMathFlags NewFMF)
Set the fast-math flags to be used with generated fp-math operators.
void setIsFPConstrained (bool IsCon)
Enable/Disable use of constrained floating point math.
bool getIsFPConstrained ()
Query for the use of constrained floating point math.
void setDefaultConstrainedExcept (fp::ExceptionBehavior NewExcept)
Set the exception handling to be used with constrained floating point.
void setDefaultConstrainedRounding (RoundingMode NewRounding)
Set the rounding mode handling to be used with constrained floating point.
fp::ExceptionBehavior getDefaultConstrainedExcept ()
Get the exception handling used with constrained floating point.
RoundingMode getDefaultConstrainedRounding ()
Get the rounding mode handling used with constrained floating point.
void setConstrainedFPFunctionAttr ()
void setConstrainedFPCallAttr (CallBase *I)
void setDefaultOperandBundles (ArrayRef< OperandBundleDef > OpBundles)
GlobalVariable * CreateGlobalString (StringRef Str, const Twine &Name="", unsigned AddressSpace=0, Module *M=nullptr)
Make a new global variable with initializer type i8*.
ConstantInt * getInt1 (bool V)
Get a constant value representing either true or false.
ConstantInt * getTrue ()
Get the constant value for i1 true.
ConstantInt * getFalse ()
Get the constant value for i1 false.
ConstantInt * getInt8 (uint8_t C)
Get a constant 8-bit value.
ConstantInt * getInt16 (uint16_t C)
Get a constant 16-bit value.
ConstantInt * getInt32 (uint32_t C)
Get a constant 32-bit value.
ConstantInt * getInt64 (uint64_t C)
Get a constant 64-bit value.
ConstantInt * getIntN (unsigned N, uint64_t C)
Get a constant N-bit value, zero extended or truncated from a 64-bit value.
ConstantInt * getInt (const APInt &AI)
Get a constant integer value.
IntegerType * getInt1Ty ()
Fetch the type representing a single bit.
IntegerType * getInt8Ty ()
Fetch the type representing an 8-bit integer.
IntegerType * getInt16Ty ()
Fetch the type representing a 16-bit integer.
IntegerType * getInt32Ty ()
Fetch the type representing a 32-bit integer.
IntegerType * getInt64Ty ()
Fetch the type representing a 64-bit integer.
IntegerType * getInt128Ty ()
Fetch the type representing a 128-bit integer.
IntegerType * getIntNTy (unsigned N)
Fetch the type representing an N-bit integer.
Type * getHalfTy ()
Fetch the type representing a 16-bit floating point value.
Type * getBFloatTy ()
Fetch the type representing a 16-bit brain floating point value.
Type * getFloatTy ()
Fetch the type representing a 32-bit floating point value.
Type * getDoubleTy ()
Fetch the type representing a 64-bit floating point value.
Type * getVoidTy ()
Fetch the type representing void.
PointerType * getInt8PtrTy (unsigned AddrSpace=0)
Fetch the type representing a pointer to an 8-bit integer value.
IntegerType * getIntPtrTy (const DataLayout &DL, unsigned AddrSpace=0)
Fetch the type representing a pointer to an integer value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, uint64_t Size, MaybeAlign Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memset to the specified pointer and the specified value.
CallInst * CreateMemSet (Value *Ptr, Value *Val, Value *Size, MaybeAlign Align, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateElementUnorderedAtomicMemSet (Value *Ptr, Value *Val, uint64_t Size, Align Alignment, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert an element unordered-atomic memset of the region of memory starting at the given pointer to the given value.
CallInst * CreateElementUnorderedAtomicMemSet (Value *Ptr, Value *Val, Value *Size, Align Alignment, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemCpy (Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert a memcpy between the specified pointers.
CallInst * CreateMemTransferInst (Intrinsic::ID IntrID, Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemCpy (Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemCpyInline (Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, Value *Size)
CallInst * CreateElementUnorderedAtomicMemCpy (Value *Dst, Align DstAlign, Value *Src, Align SrcAlign, Value *Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert an element unordered-atomic memcpy between the specified pointers.
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateElementUnorderedAtomicMemCpy(Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes Align instead")
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateElementUnorderedAtomicMemCpy(Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes Align instead")
CallInst * CreateMemMove (Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, uint64_t Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateMemMove (Value *Dst, MaybeAlign DstAlign, Value *Src, MaybeAlign SrcAlign, Value *Size, bool isVolatile=false, MDNode *TBAATag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
CallInst * CreateElementUnorderedAtomicMemMove (Value *Dst, Align DstAlign, Value *Src, Align SrcAlign, Value *Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr)
Create and insert an element unordered-atomic memmove between the specified pointers.
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateElementUnorderedAtomicMemMove(Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, uint64_t Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes Align instead")
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateElementUnorderedAtomicMemMove(Value *Dst, unsigned DstAlign, Value *Src, unsigned SrcAlign, Value *Size, uint32_t ElementSize, MDNode *TBAATag=nullptr, MDNode *TBAAStructTag=nullptr, MDNode *ScopeTag=nullptr, MDNode *NoAliasTag=nullptr), "Use the version that takes Align instead")
CallInst * CreateFAddReduce (Value *Acc, Value *Src)
Create a vector fadd reduction intrinsic of the source vector.
CallInst * CreateFMulReduce (Value *Acc, Value *Src)
Create a vector fmul reduction intrinsic of the source vector.
CallInst * CreateAddReduce (Value *Src)
Create a vector int add reduction intrinsic of the source vector.
CallInst * CreateMulReduce (Value *Src)
Create a vector int mul reduction intrinsic of the source vector.
CallInst * CreateAndReduce (Value *Src)
Create a vector int AND reduction intrinsic of the source vector.
CallInst * CreateOrReduce (Value *Src)
Create a vector int OR reduction intrinsic of the source vector.
CallInst * CreateXorReduce (Value *Src)
Create a vector int XOR reduction intrinsic of the source vector.
CallInst * CreateIntMaxReduce (Value *Src, bool IsSigned=false)
Create a vector integer max reduction intrinsic of the source vector.
CallInst * CreateIntMinReduce (Value *Src, bool IsSigned=false)
Create a vector integer min reduction intrinsic of the source vector.
CallInst * CreateFPMaxReduce (Value *Src)
Create a vector float max reduction intrinsic of the source vector.
CallInst * CreateFPMinReduce (Value *Src)
Create a vector float min reduction intrinsic of the source vector.
CallInst * CreateLifetimeStart (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.start intrinsic.
CallInst * CreateLifetimeEnd (Value *Ptr, ConstantInt *Size=nullptr)
Create a lifetime.end intrinsic.
CallInst * CreateInvariantStart (Value *Ptr, ConstantInt *Size=nullptr)
Create a call to invariant.start intrinsic.
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateMaskedLoad(Value *Ptr, unsigned Alignment, Value *Mask, Value *PassThru=nullptr, const Twine &Name=""), "Use the version that takes Align instead")
Create a call to Masked Load intrinsic.
CallInst * CreateMaskedLoad (Value *Ptr, Align Alignment, Value *Mask, Value *PassThru=nullptr, const Twine &Name="")
Create a call to a Masked Load intrinsic.
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateMaskedStore(Value *Val, Value *Ptr, unsigned Alignment, Value *Mask), "Use the version that takes Align instead")
Create a call to Masked Store intrinsic.
CallInst * CreateMaskedStore (Value *Val, Value *Ptr, Align Alignment, Value *Mask)
Create a call to a Masked Store intrinsic.
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateMaskedGather(Value *Ptrs, unsigned Alignment, Value *Mask=nullptr, Value *PassThru=nullptr, const Twine &Name=""), "Use the version that takes Align instead")
Create a call to Masked Gather intrinsic.
CallInst * CreateMaskedGather (Value *Ptrs, Align Alignment, Value *Mask=nullptr, Value *PassThru=nullptr, const Twine &Name="")
Create a call to Masked Gather intrinsic.
LLVM_ATTRIBUTE_DEPRECATED (CallInst *CreateMaskedScatter(Value *Val, Value *Ptrs, unsigned Alignment, Value *Mask=nullptr), "Use the version that takes Align instead")
Create a call to Masked Scatter intrinsic.
CallInst * CreateMaskedScatter (Value *Val, Value *Ptrs, Align Alignment, Value *Mask=nullptr)
Create a call to Masked Scatter intrinsic.
CallInst * CreateAssumption (Value *Cond, ArrayRef< OperandBundleDef > OpBundles=llvm::None)
Create an assume intrinsic call that allows the optimizer to assume that the provided condition will be true.
Instruction * CreateNoAliasScopeDeclaration (Value *Scope)
Create a llvm.experimental.noalias.scope.decl intrinsic call.
Instruction * CreateNoAliasScopeDeclaration (MDNode *ScopeTag)
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, ArrayRef< Value * > CallArgs, Optional< ArrayRef< Value * > > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, uint32_t Flags, ArrayRef< Value * > CallArgs, Optional< ArrayRef< Use > > TransitionArgs, Optional< ArrayRef< Use > > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create a call to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
CallInst * CreateGCStatepointCall (uint64_t ID, uint32_t NumPatchBytes, Value *ActualCallee, ArrayRef< Use > CallArgs, Optional< ArrayRef< Value * > > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Conveninence function for the common case when CallArgs are filled in using makeArrayRef(CS.arg_begin(), CS.arg_end()); Use needs to be .get()'ed to get the Value pointer.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > InvokeArgs, Optional< ArrayRef< Value * > > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, uint32_t Flags, ArrayRef< Value * > InvokeArgs, Optional< ArrayRef< Use > > TransitionArgs, Optional< ArrayRef< Use > > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
Create an invoke to the experimental.gc.statepoint intrinsic to start a new statepoint sequence.
InvokeInst * CreateGCStatepointInvoke (uint64_t ID, uint32_t NumPatchBytes, Value *ActualInvokee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Use > InvokeArgs, Optional< ArrayRef< Value * > > DeoptArgs, ArrayRef< Value * > GCArgs, const Twine &Name="")
CallInst * CreateGCResult (Instruction *Statepoint, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.result intrinsic to extract the result from a call wrapped in a statepoint.
CallInst * CreateGCRelocate (Instruction *Statepoint, int BaseOffset, int DerivedOffset, Type *ResultType, const Twine &Name="")
Create a call to the experimental.gc.relocate intrinsics to project the relocated value of one pointer from the statepoint.
Value * CreateVScale (Constant *Scaling, const Twine &Name="")
Create a call to llvm.vscale, multiplied by Scaling.
CallInst * CreateUnaryIntrinsic (Intrinsic::ID ID, Value *V, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with 1 operand which is mangled on its type.
CallInst * CreateBinaryIntrinsic (Intrinsic::ID ID, Value *LHS, Value *RHS, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with 2 operands which is mangled on the first type.
CallInst * CreateIntrinsic (Intrinsic::ID ID, ArrayRef< Type * > Types, ArrayRef< Value * > Args, Instruction *FMFSource=nullptr, const Twine &Name="")
Create a call to intrinsic ID with args, mangled using Types.
CallInst * CreateMinNum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the minnum intrinsic.
CallInst * CreateMaxNum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the maxnum intrinsic.
CallInst * CreateMinimum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the minimum intrinsic.
CallInst * CreateMaximum (Value *LHS, Value *RHS, const Twine &Name="")
Create call to the maximum intrinsic.
CallInst * CreateExtractVector (Type *DstType, Value *SrcVec, Value *Idx, const Twine &Name="")
Create a call to the experimental.vector.extract intrinsic.
CallInst * CreateInsertVector (Type *DstType, Value *SrcVec, Value *SubVec, Value *Idx, const Twine &Name="")
Create a call to the experimental.vector.insert intrinsic.
ReturnInst * CreateRetVoid ()
Create a 'ret void' instruction.
ReturnInst * CreateRet (Value *V)
Create a 'ret <val>' instruction.
ReturnInst * CreateAggregateRet (Value *const *retVals, unsigned N)
Create a sequence of N insertvalue instructions, with one Value from the retVals array each, that build a aggregate return value one value at a time, and a ret instruction to return the resulting aggregate value.
BranchInst * CreateBr (BasicBlock *Dest)
Create an unconditional 'br label X' instruction.
BranchInst * CreateCondBr (Value *Cond, BasicBlock *True, BasicBlock *False, MDNode *BranchWeights=nullptr, MDNode *Unpredictable=nullptr)
Create a conditional 'br Cond, TrueDest, FalseDest' instruction.
BranchInst * CreateCondBr (Value *Cond, BasicBlock *True, BasicBlock *False, Instruction *MDSrc)
Create a conditional 'br Cond, TrueDest, FalseDest' instruction.
SwitchInst * CreateSwitch (Value *V, BasicBlock *Dest, unsigned NumCases=10, MDNode *BranchWeights=nullptr, MDNode *Unpredictable=nullptr)
Create a switch instruction with the specified value, default dest, and with a hint for the number of cases that will be added (for efficient allocation).
IndirectBrInst * CreateIndirectBr (Value *Addr, unsigned NumDests=10)
Create an indirect branch instruction with the specified address operand, with an optional hint for the number of destinations that will be added (for efficient allocation).
InvokeInst * CreateInvoke (FunctionType *Ty, Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
Create an invoke instruction.
InvokeInst * CreateInvoke (FunctionType *Ty, Value *Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > Args=None, const Twine &Name="")
InvokeInst * CreateInvoke (FunctionCallee Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
InvokeInst * CreateInvoke (FunctionCallee Callee, BasicBlock *NormalDest, BasicBlock *UnwindDest, ArrayRef< Value * > Args=None, const Twine &Name="")
CallBrInst * CreateCallBr (FunctionType *Ty, Value *Callee, BasicBlock *DefaultDest, ArrayRef< BasicBlock * > IndirectDests, ArrayRef< Value * > Args=None, const Twine &Name="")
Create a callbr instruction.
CallBrInst * CreateCallBr (FunctionType *Ty, Value *Callee, BasicBlock *DefaultDest, ArrayRef< BasicBlock * > IndirectDests, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
CallBrInst * CreateCallBr (FunctionCallee Callee, BasicBlock *DefaultDest, ArrayRef< BasicBlock * > IndirectDests, ArrayRef< Value * > Args=None, const Twine &Name="")
CallBrInst * CreateCallBr (FunctionCallee Callee, BasicBlock *DefaultDest, ArrayRef< BasicBlock * > IndirectDests, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="")
ResumeInst * CreateResume (Value *Exn)
CleanupReturnInst * CreateCleanupRet (CleanupPadInst *CleanupPad, BasicBlock *UnwindBB=nullptr)
CatchSwitchInst * CreateCatchSwitch (Value *ParentPad, BasicBlock *UnwindBB, unsigned NumHandlers, const Twine &Name="")
CatchPadInst * CreateCatchPad (Value *ParentPad, ArrayRef< Value * > Args, const Twine &Name="")
CleanupPadInst * CreateCleanupPad (Value *ParentPad, ArrayRef< Value * > Args=None, const Twine &Name="")
CatchReturnInst * CreateCatchRet (CatchPadInst *CatchPad, BasicBlock *BB)
UnreachableInst * CreateUnreachable ()
Value * CreateAdd (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWAdd (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateNUWAdd (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateSub (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWSub (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateNUWSub (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateMul (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWMul (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateNUWMul (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateUDiv (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateExactUDiv (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateSDiv (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateExactSDiv (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateURem (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateSRem (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateShl (Value *LHS, Value *RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateShl (Value *LHS, const APInt &RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateShl (Value *LHS, uint64_t RHS, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateLShr (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateLShr (Value *LHS, const APInt &RHS, const Twine &Name="", bool isExact=false)
Value * CreateLShr (Value *LHS, uint64_t RHS, const Twine &Name="", bool isExact=false)
Value * CreateAShr (Value *LHS, Value *RHS, const Twine &Name="", bool isExact=false)
Value * CreateAShr (Value *LHS, const APInt &RHS, const Twine &Name="", bool isExact=false)
Value * CreateAShr (Value *LHS, uint64_t RHS, const Twine &Name="", bool isExact=false)
Value * CreateAnd (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateAnd (Value *LHS, const APInt &RHS, const Twine &Name="")
Value * CreateAnd (Value *LHS, uint64_t RHS, const Twine &Name="")
Value * CreateAnd (ArrayRef< Value * > Ops)
Value * CreateOr (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateOr (Value *LHS, const APInt &RHS, const Twine &Name="")
Value * CreateOr (Value *LHS, uint64_t RHS, const Twine &Name="")
Value * CreateOr (ArrayRef< Value * > Ops)
Value * CreateXor (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateXor (Value *LHS, const APInt &RHS, const Twine &Name="")
Value * CreateXor (Value *LHS, uint64_t RHS, const Twine &Name="")
Value * CreateFAdd (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFAddFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateFSub (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFSubFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateFMul (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFMulFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateFDiv (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFDivFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateFRem (Value *L, Value *R, const Twine &Name="", MDNode *FPMD=nullptr)
Value * CreateFRemFMF (Value *L, Value *R, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateBinOp (Instruction::BinaryOps Opc, Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateConstrainedFPBinOp (Intrinsic::ID ID, Value *L, Value *R, Instruction *FMFSource=nullptr, const Twine &Name="", MDNode *FPMathTag=nullptr, Optional< RoundingMode > Rounding=None, Optional< fp::ExceptionBehavior > Except=None)
Value * CreateNeg (Value *V, const Twine &Name="", bool HasNUW=false, bool HasNSW=false)
Value * CreateNSWNeg (Value *V, const Twine &Name="")
Value * CreateNUWNeg (Value *V, const Twine &Name="")
Value * CreateFNeg (Value *V, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFNegFMF (Value *V, Instruction *FMFSource, const Twine &Name="")
Copy fast-math-flags from an instruction rather than using the builder's default FMF.
Value * CreateNot (Value *V, const Twine &Name="")
Value * CreateUnOp (Instruction::UnaryOps Opc, Value *V, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateNAryOp (unsigned Opc, ArrayRef< Value * > Ops, const Twine &Name="", MDNode *FPMathTag=nullptr)
Create either a UnaryOperator or BinaryOperator depending on Opc.
AllocaInst * CreateAlloca (Type *Ty, unsigned AddrSpace, Value *ArraySize=nullptr, const Twine &Name="")
AllocaInst * CreateAlloca (Type *Ty, Value *ArraySize=nullptr, const Twine &Name="")
LoadInst * CreateLoad (Type *Ty, Value *Ptr, const char *Name)
Provided to resolve 'CreateLoad(Ty, Ptr, "...")' correctly, instead of converting the string to 'bool' for the isVolatile parameter.
LoadInst * CreateLoad (Type *Ty, Value *Ptr, const Twine &Name="")
LoadInst * CreateLoad (Type *Ty, Value *Ptr, bool isVolatile, const Twine &Name="")
LoadInst * CreateLoad (Value *Ptr, const char *Name)
LoadInst * CreateLoad (Value *Ptr, const Twine &Name="")
LoadInst * CreateLoad (Value *Ptr, bool isVolatile, const Twine &Name="")
StoreInst * CreateStore (Value *Val, Value *Ptr, bool isVolatile=false)
LLVM_ATTRIBUTE_DEPRECATED (LoadInst *CreateAlignedLoad(Type *Ty, Value *Ptr, unsigned Align, const char *Name), "Use the version that takes NaybeAlign instead")
LoadInst * CreateAlignedLoad (Type *Ty, Value *Ptr, MaybeAlign Align, const char *Name)
LLVM_ATTRIBUTE_DEPRECATED (LoadInst *CreateAlignedLoad(Type *Ty, Value *Ptr, unsigned Align, const Twine &Name=""), "Use the version that takes MaybeAlign instead")
LoadInst * CreateAlignedLoad (Type *Ty, Value *Ptr, MaybeAlign Align, const Twine &Name="")
LLVM_ATTRIBUTE_DEPRECATED (LoadInst *CreateAlignedLoad(Type *Ty, Value *Ptr, unsigned Align, bool isVolatile, const Twine &Name=""), "Use the version that takes MaybeAlign instead")
LoadInst * CreateAlignedLoad (Type *Ty, Value *Ptr, MaybeAlign Align, bool isVolatile, const Twine &Name="")
LLVM_ATTRIBUTE_DEPRECATED (LoadInst *CreateAlignedLoad(Value *Ptr, unsigned Align, const char *Name), "Use the version that takes MaybeAlign instead")
LLVM_ATTRIBUTE_DEPRECATED (LoadInst *CreateAlignedLoad(Value *Ptr, unsigned Align, const Twine &Name=""), "Use the version that takes MaybeAlign instead")
LLVM_ATTRIBUTE_DEPRECATED (LoadInst *CreateAlignedLoad(Value *Ptr, unsigned Align, bool isVolatile, const Twine &Name=""), "Use the version that takes MaybeAlign instead")
LoadInst * CreateAlignedLoad (Value *Ptr, MaybeAlign Align, const char *Name)
LoadInst * CreateAlignedLoad (Value *Ptr, MaybeAlign Align, const Twine &Name="")
LoadInst * CreateAlignedLoad (Value *Ptr, MaybeAlign Align, bool isVolatile, const Twine &Name="")
LLVM_ATTRIBUTE_DEPRECATED (StoreInst *CreateAlignedStore(Value *Val, Value *Ptr, unsigned Align, bool isVolatile=false), "Use the version that takes MaybeAlign instead")
StoreInst * CreateAlignedStore (Value *Val, Value *Ptr, MaybeAlign Align, bool isVolatile=false)
FenceInst * CreateFence (AtomicOrdering Ordering, SyncScope::ID SSID=SyncScope::System, const Twine &Name="")
AtomicCmpXchgInst * CreateAtomicCmpXchg (Value *Ptr, Value *Cmp, Value *New, AtomicOrdering SuccessOrdering, AtomicOrdering FailureOrdering, SyncScope::ID SSID=SyncScope::System)
AtomicRMWInst * CreateAtomicRMW (AtomicRMWInst::BinOp Op, Value *Ptr, Value *Val, AtomicOrdering Ordering, SyncScope::ID SSID=SyncScope::System)
Value * CreateGEP (Value *Ptr, ArrayRef< Value * > IdxList, const Twine &Name="")
Value * CreateGEP (Type *Ty, Value *Ptr, ArrayRef< Value * > IdxList, const Twine &Name="")
Value * CreateInBoundsGEP (Value *Ptr, ArrayRef< Value * > IdxList, const Twine &Name="")
Value * CreateInBoundsGEP (Type *Ty, Value *Ptr, ArrayRef< Value * > IdxList, const Twine &Name="")
Value * CreateGEP (Value *Ptr, Value *Idx, const Twine &Name="")
Value * CreateGEP (Type *Ty, Value *Ptr, Value *Idx, const Twine &Name="")
Value * CreateInBoundsGEP (Type *Ty, Value *Ptr, Value *Idx, const Twine &Name="")
Value * CreateConstGEP1_32 (Value *Ptr, unsigned Idx0, const Twine &Name="")
Value * CreateConstGEP1_32 (Type *Ty, Value *Ptr, unsigned Idx0, const Twine &Name="")
Value * CreateConstInBoundsGEP1_32 (Type *Ty, Value *Ptr, unsigned Idx0, const Twine &Name="")
Value * CreateConstGEP2_32 (Type *Ty, Value *Ptr, unsigned Idx0, unsigned Idx1, const Twine &Name="")
Value * CreateConstInBoundsGEP2_32 (Type *Ty, Value *Ptr, unsigned Idx0, unsigned Idx1, const Twine &Name="")
Value * CreateConstGEP1_64 (Type *Ty, Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstGEP1_64 (Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstInBoundsGEP1_64 (Type *Ty, Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstInBoundsGEP1_64 (Value *Ptr, uint64_t Idx0, const Twine &Name="")
Value * CreateConstGEP2_64 (Type *Ty, Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateConstGEP2_64 (Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateConstInBoundsGEP2_64 (Type *Ty, Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateConstInBoundsGEP2_64 (Value *Ptr, uint64_t Idx0, uint64_t Idx1, const Twine &Name="")
Value * CreateStructGEP (Type *Ty, Value *Ptr, unsigned Idx, const Twine &Name="")
Value * CreateStructGEP (Value *Ptr, unsigned Idx, const Twine &Name="")
Constant * CreateGlobalStringPtr (StringRef Str, const Twine &Name="", unsigned AddressSpace=0, Module *M=nullptr)
Same as CreateGlobalString, but return a pointer with "i8*" type instead of a pointer to array of i8.
Value * CreateTrunc (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateZExt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateSExt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateZExtOrTrunc (Value *V, Type *DestTy, const Twine &Name="")
Create a ZExt or Trunc from the integer value V to DestTy.
Value * CreateSExtOrTrunc (Value *V, Type *DestTy, const Twine &Name="")
Create a SExt or Trunc from the integer value V to DestTy.
Value * CreateFPToUI (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPToSI (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateUIToFP (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateSIToFP (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPTrunc (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPExt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreatePtrToInt (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateIntToPtr (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateAddrSpaceCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateZExtOrBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateSExtOrBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateTruncOrBitCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateCast (Instruction::CastOps Op, Value *V, Type *DestTy, const Twine &Name="")
Value * CreatePointerCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreatePointerBitCastOrAddrSpaceCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateIntCast (Value *V, Type *DestTy, bool isSigned, const Twine &Name="")
Value * CreateBitOrPointerCast (Value *V, Type *DestTy, const Twine &Name="")
Value * CreateFPCast (Value *V, Type *DestTy, const Twine &Name="")
CallInst * CreateConstrainedFPCast (Intrinsic::ID ID, Value *V, Type *DestTy, Instruction *FMFSource=nullptr, const Twine &Name="", MDNode *FPMathTag=nullptr, Optional< RoundingMode > Rounding=None, Optional< fp::ExceptionBehavior > Except=None)
Value * CreateIntCast (Value *, Type *, const char *)=delete
Value * CreateICmpEQ (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpNE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpUGT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpUGE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpULT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpULE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSGT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSGE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSLT (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateICmpSLE (Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmpOEQ (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpOGT (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpOGE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpOLT (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpOLE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpONE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpORD (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUNO (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUEQ (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUGT (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUGE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpULT (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpULE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpUNE (Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateICmp (CmpInst::Predicate P, Value *LHS, Value *RHS, const Twine &Name="")
Value * CreateFCmp (CmpInst::Predicate P, Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateCmp (CmpInst::Predicate Pred, Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
Value * CreateFCmpS (CmpInst::Predicate P, Value *LHS, Value *RHS, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateConstrainedFPCmp (Intrinsic::ID ID, CmpInst::Predicate P, Value *L, Value *R, const Twine &Name="", Optional< fp::ExceptionBehavior > Except=None)
PHINode * CreatePHI (Type *Ty, unsigned NumReservedValues, const Twine &Name="")
CallInst * CreateCall (FunctionType *FTy, Value *Callee, ArrayRef< Value * > Args=None, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateCall (FunctionType *FTy, Value *Callee, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateCall (FunctionCallee Callee, ArrayRef< Value * > Args=None, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateCall (FunctionCallee Callee, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > OpBundles, const Twine &Name="", MDNode *FPMathTag=nullptr)
CallInst * CreateConstrainedFPCall (Function *Callee, ArrayRef< Value * > Args, const Twine &Name="", Optional< RoundingMode > Rounding=None, Optional< fp::ExceptionBehavior > Except=None)
Value * CreateSelect (Value *C, Value *True, Value *False, const Twine &Name="", Instruction *MDFrom=nullptr)
VAArgInst * CreateVAArg (Value *List, Type *Ty, const Twine &Name="")
Value * CreateExtractElement (Value *Vec, Value *Idx, const Twine &Name="")
Value * CreateExtractElement (Value *Vec, uint64_t Idx, const Twine &Name="")
Value * CreateInsertElement (Value *Vec, Value *NewElt, Value *Idx, const Twine &Name="")
Value * CreateInsertElement (Value *Vec, Value *NewElt, uint64_t Idx, const Twine &Name="")
Value * CreateShuffleVector (Value *V1, Value *V2, Value *Mask, const Twine &Name="")
LLVM_ATTRIBUTE_DEPRECATED (Value *CreateShuffleVector(Value *V1, Value *V2, ArrayRef< uint32_t > Mask, const Twine &Name=""), "Pass indices as 'int' instead")
Value * CreateShuffleVector (Value *V1, Value *V2, ArrayRef< int > Mask, const Twine &Name="")
See class ShuffleVectorInst for a description of the mask representation.
Value * CreateShuffleVector (Value *V, ArrayRef< int > Mask, const Twine &Name="")
Create a unary shuffle.
Value * CreateExtractValue (Value *Agg, ArrayRef< unsigned > Idxs, const Twine &Name="")
Value * CreateInsertValue (Value *Agg, Value *Val, ArrayRef< unsigned > Idxs, const Twine &Name="")
LandingPadInst * CreateLandingPad (Type *Ty, unsigned NumClauses, const Twine &Name="")
Value * CreateFreeze (Value *V, const Twine &Name="")
Value * CreateIsNull (Value *Arg, const Twine &Name="")
Return an i1 value testing if Arg is null.
Value * CreateIsNotNull (Value *Arg, const Twine &Name="")
Return an i1 value testing if Arg is not null.
Value * CreatePtrDiff (Value *LHS, Value *RHS, const Twine &Name="")
Return the i64 difference between two pointer values, dividing out the size of the pointed-to objects.
Value * CreateLaunderInvariantGroup (Value *Ptr)
Create a launder.invariant.group intrinsic call.
Value * CreateStripInvariantGroup (Value *Ptr)
Create a strip.invariant.group intrinsic call.
Value * CreateVectorSplat (unsigned NumElts, Value *V, const Twine &Name="")
Return a vector value that contains.
Value * CreateVectorSplat (ElementCount EC, Value *V, const Twine &Name="")
Return a vector value that contains.
Value * CreateExtractInteger (const DataLayout &DL, Value *From, IntegerType *ExtractedTy, uint64_t Offset, const Twine &Name)
Return a value that has been extracted from a larger integer type.
Value * CreatePreserveArrayAccessIndex (Type *ElTy, Value *Base, unsigned Dimension, unsigned LastIndex, MDNode *DbgInfo)
Value * CreatePreserveUnionAccessIndex (Value *Base, unsigned FieldIndex, MDNode *DbgInfo)
Value * CreatePreserveStructAccessIndex (Type *ElTy, Value *Base, unsigned Index, unsigned FieldIndex, MDNode *DbgInfo)
CallInst * CreateAlignmentAssumption (const DataLayout &DL, Value *PtrValue, unsigned Alignment, Value *OffsetValue=nullptr)
Create an assume intrinsic call that represents an alignment assumption on the provided pointer.
CallInst * CreateAlignmentAssumption (const DataLayout &DL, Value *PtrValue, Value *Alignment, Value *OffsetValue=nullptr)
Create an assume intrinsic call that represents an alignment assumption on the provided pointer.
Additional Inherited Members
Protected Attributes inherited from llvm::IRBuilderBase
BasicBlock * BB
BasicBlock::iterator InsertPt
LLVMContext & Context
const IRBuilderFolder & Folder
const IRBuilderDefaultInserter & Inserter
MDNode * DefaultFPMathTag
FastMathFlags FMF
bool IsFPConstrained
fp::ExceptionBehavior DefaultConstrainedExcept
RoundingMode DefaultConstrainedRounding
ArrayRef< OperandBundleDef > DefaultOperandBundles
Detailed Description
template<typename FolderTy = ConstantFolder, typename InserterTy = IRBuilderDefaultInserter>
class llvm::IRBuilder< FolderTy, InserterTy >
This provides a uniform API for creating instructions and inserting them into a basic block: either at the end of a BasicBlock, or at a specific iterator location in a block.
Note that the builder does not expose the full generality of LLVM instructions. For access to extra instruction properties, use the mutators (e.g. setVolatile) on the instructions after they have been created. Convenience state exists to specify fast-math flags and fp-math tags.
The first template argument specifies a class to use for creating constants. This defaults to creating minimally folded constants. The second template argument allows clients to specify custom insertion hooks that are called on every newly created insertion.
Definition at line 2673 of file IRBuilder.h.
Constructor & Destructor Documentation
IRBuilder() [1/8]
template<typename FolderTy = ConstantFolder, typename InserterTy = IRBuilderDefaultInserter> llvm::IRBuilder< FolderTy, InserterTy >::IRBuilder (LLVMContext & C, FolderTy Folder, InserterTy Inserter = InserterTy(), MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline
Definition at line 2679 of file IRBuilder.h.
IRBuilder() [2/8]
template<typename FolderTy = ConstantFolder, typename InserterTy = IRBuilderDefaultInserter> llvm::IRBuilder< FolderTy, InserterTy >::IRBuilder (LLVMContext & C, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline explicit
Definition at line 2685 of file IRBuilder.h.
IRBuilder() [3/8]
template<typename FolderTy = ConstantFolder, typename InserterTy = IRBuilderDefaultInserter> llvm::IRBuilder< FolderTy, InserterTy >::IRBuilder (BasicBlock * TheBB, FolderTy Folder, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline explicit
Definition at line 2689 of file IRBuilder.h.
References llvm::IRBuilderBase::SetInsertPoint().
IRBuilder() [4/8]
template<typename FolderTy = ConstantFolder, typename InserterTy = IRBuilderDefaultInserter> llvm::IRBuilder< FolderTy, InserterTy >::IRBuilder (BasicBlock * TheBB, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline explicit
Definition at line 2697 of file IRBuilder.h.
References llvm::IRBuilderBase::SetInsertPoint().
IRBuilder() [5/8]
template<typename FolderTy = ConstantFolder, typename InserterTy = IRBuilderDefaultInserter> llvm::IRBuilder< FolderTy, InserterTy >::IRBuilder (Instruction * IP, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline explicit
Definition at line 2704 of file IRBuilder.h.
References llvm::IRBuilderBase::SetInsertPoint().
IRBuilder() [6/8]
template<typename FolderTy = ConstantFolder, typename InserterTy = IRBuilderDefaultInserter> llvm::IRBuilder< FolderTy, InserterTy >::IRBuilder (BasicBlock * TheBB, BasicBlock::iterator IP, FolderTy Folder, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline
Definition at line 2711 of file IRBuilder.h.
References llvm::IRBuilderBase::SetInsertPoint().
IRBuilder() [7/8]
template<typename FolderTy = ConstantFolder, typename InserterTy = IRBuilderDefaultInserter> llvm::IRBuilder< FolderTy, InserterTy >::IRBuilder (BasicBlock * TheBB, BasicBlock::iterator IP, MDNode * FPMathTag = nullptr, ArrayRef< OperandBundleDef > OpBundles = None) inline
Definition at line 2719 of file IRBuilder.h.
References llvm::IRBuilderBase::SetInsertPoint().
IRBuilder() [8/8]
template<typename FolderTy = ConstantFolder, typename InserterTy = IRBuilderDefaultInserter> llvm::IRBuilder< FolderTy, InserterTy >::IRBuilder (const IRBuilder< FolderTy, InserterTy > &) delete
Avoid copying the full IRBuilder.
Prefer using InsertPointGuard or FastMathFlagGuard instead.
Member Function Documentation
getInserter()
template<typename FolderTy = ConstantFolder, typename InserterTy = IRBuilderDefaultInserter> InserterTy & llvm::IRBuilder< FolderTy, InserterTy >::getInserter () inline
Definition at line 2731 of file IRBuilder.h.
The documentation for this class was generated from the following file:
include/llvm/IR/IRBuilder.h