LLVM: llvm::pdb::GSIHashTable Class Reference
llvm::pdb::GSIHashTable Class Reference
A readonly view of a hash table used in the globals and publics streams.
#include "llvm/DebugInfo/PDB/Native/GlobalsStream.h"
Public Types
typedef GSIHashHeader iterator
Public Member Functions
Error read (BinaryStreamReader &Reader)
uint32_t getVerSignature () const
uint32_t getVerHeader () const
uint32_t getHashRecordSize () const
uint32_t getNumBuckets () const
GSIHashIterator begin () const
GSIHashIterator end () const
Public Attributes
const GSIHashHeader * HashHdr
FixedStreamArray< PSHashRecord > HashRecords
FixedStreamArray< support::ulittle32_t > HashBitmap
FixedStreamArray< support::ulittle32_t > HashBuckets
std::array< int32_t, IPHR_HASH+1 > BucketMap
Detailed Description
A readonly view of a hash table used in the globals and publics streams.
Most clients will only want to iterate this to get symbol record offsets into the PDB symbol stream.
Definition at line 50 of file GlobalsStream.h.
Member Typedef Documentation
iterator
typedef GSIHashHeader llvm::pdb::GSIHashTable::iterator
Definition at line 65 of file GlobalsStream.h.
Member Function Documentation
begin()
GSIHashIterator llvm::pdb::GSIHashTable::begin () const inline
Definition at line 66 of file GlobalsStream.h.
References llvm::FixedStreamArray< T >::begin(), and HashRecords.
end()
GSIHashIterator llvm::pdb::GSIHashTable::end () const inline
Definition at line 67 of file GlobalsStream.h.
References llvm::FixedStreamArray< T >::end(), and HashRecords.
getHashRecordSize()
uint32_t llvm::pdb::GSIHashTable::getHashRecordSize () const inline
Definition at line 62 of file GlobalsStream.h.
References HashHdr, and llvm::pdb::GSIHashHeader::HrSize.
getNumBuckets()
uint32_t llvm::pdb::GSIHashTable::getNumBuckets () const inline
Definition at line 63 of file GlobalsStream.h.
References HashHdr, and llvm::pdb::GSIHashHeader::NumBuckets.
getVerHeader()
uint32_t llvm::pdb::GSIHashTable::getVerHeader () const inline
Definition at line 61 of file GlobalsStream.h.
References HashHdr, and llvm::pdb::GSIHashHeader::VerHdr.
getVerSignature()
uint32_t llvm::pdb::GSIHashTable::getVerSignature () const inline
Definition at line 60 of file GlobalsStream.h.
References HashHdr, and llvm::pdb::GSIHashHeader::VerSignature.
read()
Error GSIHashTable::read (BinaryStreamReader & Reader)
Definition at line 171 of file GlobalsStream.cpp.
References BucketMap, HashBitmap, HashBuckets, HashHdr, HashRecords, llvm::pdb::GSIHashHeader::HrSize, readGSIHashBuckets(), readGSIHashHeader(), readGSIHashRecords(), and llvm::Error::success().
Referenced by llvm::pdb::GlobalsStream::reload(), and llvm::pdb::PublicsStream::reload().
Member Data Documentation
BucketMap
std::array<int32_t, IPHR_HASH + 1> llvm::pdb::GSIHashTable::BucketMap
Definition at line 56 of file GlobalsStream.h.
Referenced by llvm::pdb::GlobalsStream::findRecordsByName(), and read().
HashBitmap
FixedStreamArray<support::ulittle32_t> llvm::pdb::GSIHashTable::HashBitmap
Definition at line 54 of file GlobalsStream.h.
Referenced by read().
HashBuckets
FixedStreamArray<support::ulittle32_t> llvm::pdb::GSIHashTable::HashBuckets
Definition at line 55 of file GlobalsStream.h.
Referenced by llvm::pdb::GlobalsStream::findRecordsByName(), and read().
HashHdr
const GSIHashHeader* llvm::pdb::GSIHashTable::HashHdr
Definition at line 52 of file GlobalsStream.h.
Referenced by getHashRecordSize(), getNumBuckets(), getVerHeader(), getVerSignature(), and read().
HashRecords
FixedStreamArray<PSHashRecord> llvm::pdb::GSIHashTable::HashRecords
Definition at line 53 of file GlobalsStream.h.
Referenced by begin(), end(), llvm::pdb::GlobalsStream::findRecordsByName(), and read().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/GlobalsStream.h
lib/DebugInfo/PDB/Native/GlobalsStream.cpp