LLVM: llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl > Class Template Reference
llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl > Class Template Reference
#include "ExecutionEngine/JITLink/BasicGOTAndStubsBuilder.h"
Public Member Functions
BasicGOTAndStubsBuilder (LinkGraph &G)
void run ()
Protected Member Functions
Symbol & getGOTEntrySymbol (Symbol &Target)
Symbol & getStubSymbol (Symbol &Target)
Protected Attributes
LinkGraph & G
Detailed Description
template<typename BuilderImpl>
class llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >
Definition at line 23 of file BasicGOTAndStubsBuilder.h.
Constructor & Destructor Documentation
BasicGOTAndStubsBuilder()
template<typename BuilderImpl > llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::BasicGOTAndStubsBuilder (LinkGraph & G) inline
Definition at line 25 of file BasicGOTAndStubsBuilder.h.
Member Function Documentation
getGOTEntrySymbol()
template<typename BuilderImpl > Symbol & llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::getGOTEntrySymbol (Symbol & Target) inline protected
Definition at line 54 of file BasicGOTAndStubsBuilder.h.
References assert(), llvm::dbgs(), llvm::Target::getName(), and LLVM_DEBUG.
Referenced by llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::run().
getStubSymbol()
template<typename BuilderImpl > Symbol & llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::getStubSymbol (Symbol & Target) inline protected
Definition at line 76 of file BasicGOTAndStubsBuilder.h.
References assert(), llvm::dbgs(), llvm::Target::getName(), and LLVM_DEBUG.
Referenced by llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::run().
run()
template<typename BuilderImpl > void llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::run () inline
Definition at line 27 of file BasicGOTAndStubsBuilder.h.
References B, llvm::jitlink::LinkGraph::blocks(), llvm::dbgs(), E, llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::G, llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::getGOTEntrySymbol(), llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::getStubSymbol(), LLVM_DEBUG, and llvm::jitlink::printEdge().
Member Data Documentation
G
template<typename BuilderImpl > LinkGraph& llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::G protected
Definition at line 95 of file BasicGOTAndStubsBuilder.h.
Referenced by llvm::jitlink::BasicGOTAndStubsBuilder< BuilderImpl >::run().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/JITLink/BasicGOTAndStubsBuilder.h