LLVM: llvm::VPWidenIntOrFpInductionRecipe Class Reference
llvm::VPWidenIntOrFpInductionRecipe Class Reference
A recipe for handling phi nodes of integer and floating-point inductions, producing their vector and scalar values.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPWidenIntOrFpInductionRecipe (PHINode *IV, VPValue *Start, TruncInst *Trunc=nullptr)
~VPWidenIntOrFpInductionRecipe () override=default
void execute (VPTransformState &State) override
Generate the vectorized and scalarized versions of the phi node as needed by their users.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the recipe.
VPValue * getStartValue ()
Returns the start value of the induction.
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC)
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
VPUser * toVPUser ()
Returns a pointer to a VPUser, if the recipe inherits from VPUser or nullptr otherwise.
Instruction * getUnderlyingInstr ()
Returns the underlying instruction, if the recipe is a VPValue or nullptr otherwise.
const Instruction * getUnderlyingInstr () const
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPValue (unsigned I=0)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I=0) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()
VPUser (ArrayRef< VPValue * > Operands)
VPUser (std::initializer_list< VPValue * > Operands)
template<typename IterT >
VPUser (iterator_range< IterT > Operands)
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
Static Public Member Functions
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::VPUser
static bool classof (const VPDef *Recipe)
Method to support type inquiry through isa, cast, and dyn_cast.
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
Detailed Description
A recipe for handling phi nodes of integer and floating-point inductions, producing their vector and scalar values.
Definition at line 946 of file VPlan.h.
Constructor & Destructor Documentation
VPWidenIntOrFpInductionRecipe()
llvm::VPWidenIntOrFpInductionRecipe::VPWidenIntOrFpInductionRecipe (PHINode * IV, VPValue * Start, TruncInst * Trunc = nullptr) inline
Definition at line 951 of file VPlan.h.
~VPWidenIntOrFpInductionRecipe()
llvm::VPWidenIntOrFpInductionRecipe::~VPWidenIntOrFpInductionRecipe () override default
Member Function Documentation
classof()
static bool llvm::VPWidenIntOrFpInductionRecipe::classof (const VPDef * D) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 963 of file VPlan.h.
References D, and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
execute()
void VPWidenIntOrFpInductionRecipe::execute (VPTransformState & State) override virtual
Generate the vectorized and scalarized versions of the phi node as needed by their users.
Implements llvm::VPRecipeBase.
Definition at line 8976 of file LoopVectorize.cpp.
References assert().
getStartValue()
VPValue * llvm::VPWidenIntOrFpInductionRecipe::getStartValue () inline
Returns the start value of the induction.
Definition at line 976 of file VPlan.h.
References llvm::VPUser::getOperand().
print()
void VPWidenIntOrFpInductionRecipe::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the recipe.
Implements llvm::VPDef.
Definition at line 889 of file VPlan.cpp.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/LoopVectorize.cpp
lib/Transforms/Vectorize/VPlan.cpp