LLVM: llvm::CallGraph Class Reference
llvm::CallGraph Class Reference
The basic data container for the call graph of a Module of IR.
#include "llvm/Analysis/CallGraph.h"
Public Types
using iterator = FunctionMapTy::iterator
using const_iterator = FunctionMapTy::const_iterator
Public Member Functions
CallGraph (Module &M)
CallGraph (CallGraph &&Arg)
~CallGraph ()
void print (raw_ostream &OS) const
void dump () const
Module & getModule () const
Returns the module the call graph corresponds to.
bool invalidate (Module &, const PreservedAnalyses &PA, ModuleAnalysisManager::Invalidator &)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
const CallGraphNode * operator[] (const Function *F) const
Returns the call graph node for the provided function.
CallGraphNode * operator[] (const Function *F)
Returns the call graph node for the provided function.
CallGraphNode * getExternalCallingNode () const
Returns the CallGraphNode which is used to represent undetermined calls into the callgraph.
CallGraphNode * getCallsExternalNode () const
void ReplaceExternalCallEdge (CallGraphNode *Old, CallGraphNode *New)
Old node has been deleted, and New is to be used in its place, update the ExternalCallingNode.
Function * removeFunctionFromModule (CallGraphNode *CGN)
Unlink the function from this module, returning it.
CallGraphNode * getOrInsertFunction (const Function *F)
Similar to operator[], but this will insert a new CallGraphNode for F if one does not already exist.
void populateCallGraphNode (CallGraphNode *CGN)
Populate CGN based on the calls inside the associated function.
void addToCallGraph (Function *F)
Add a function to the call graph, and link the node to all of the functions that it calls.
Detailed Description
The basic data container for the call graph of a Module of IR.
This class exposes both the interface to the call graph for a module of IR.
The core call graph itself can also be updated to reflect changes to the IR.
Definition at line 73 of file CallGraph.h.
Member Typedef Documentation
const_iterator
using llvm::CallGraph::const_iterator = FunctionMapTy::const_iterator
Definition at line 99 of file CallGraph.h.
iterator
using llvm::CallGraph::iterator = FunctionMapTy::iterator
Definition at line 98 of file CallGraph.h.
Constructor & Destructor Documentation
CallGraph() [1/2]
CallGraph::CallGraph (Module & M) explicit
Definition at line 33 of file CallGraph.cpp.
References addToCallGraph(), F, and llvm::isDbgInfoIntrinsic().
CallGraph() [2/2]
CallGraph::CallGraph (CallGraph && Arg)
Definition at line 42 of file CallGraph.cpp.
References Arg, and P.
~CallGraph()
CallGraph::~CallGraph ()
Definition at line 55 of file CallGraph.cpp.
References I.
Member Function Documentation
addToCallGraph()
void CallGraph::addToCallGraph (Function * F)
Add a function to the call graph, and link the node to all of the functions that it calls.
Definition at line 77 of file CallGraph.cpp.
References llvm::CallGraphNode::addCalledFunction(), F, getOrInsertFunction(), and populateCallGraphNode().
Referenced by CallGraph(), and llvm::CallGraphUpdater::registerOutlinedFunction().
begin() [1/2]
iterator llvm::CallGraph::begin () inline
Definition at line 107 of file CallGraph.h.
begin() [2/2]
const_iterator llvm::CallGraph::begin () const inline
Definition at line 109 of file CallGraph.h.
dump()
LLVM_DUMP_METHOD void CallGraph::dump () const
Definition at line 141 of file CallGraph.cpp.
References llvm::dbgs(), and print().
end() [1/2]
iterator llvm::CallGraph::end () inline
Definition at line 108 of file CallGraph.h.
end() [2/2]
const_iterator llvm::CallGraph::end () const inline
Definition at line 110 of file CallGraph.h.
getCallsExternalNode()
CallGraphNode * llvm::CallGraph::getCallsExternalNode () const inline
Definition at line 130 of file CallGraph.h.
getExternalCallingNode()
CallGraphNode * llvm::CallGraph::getExternalCallingNode () const inline
Returns the CallGraphNode which is used to represent undetermined calls into the callgraph.
Definition at line 128 of file CallGraph.h.
Referenced by llvm::CallGraphUpdater::finalize().
getModule()
Module & llvm::CallGraph::getModule () const inline
Returns the module the call graph corresponds to.
Definition at line 102 of file CallGraph.h.
Referenced by llvm::CallGraphSCCPass::skipSCC().
getOrInsertFunction()
CallGraphNode * CallGraph::getOrInsertFunction (const Function * F)
Similar to operator[], but this will insert a new CallGraphNode for F if one does not already exist.
Definition at line 173 of file CallGraph.cpp.
References assert(), and F.
Referenced by addToCallGraph(), llvm::CallGraphUpdater::finalize(), populateCallGraphNode(), llvm::CallGraphUpdater::reanalyzeFunction(), llvm::CallGraphNode::removeCallEdgeFor(), llvm::CallGraphNode::replaceCallEdge(), llvm::CallGraphUpdater::replaceCallSite(), and llvm::CallGraphUpdater::replaceFunctionWith().
invalidate()
bool CallGraph::invalidate (Module & , const PreservedAnalyses & PA, ModuleAnalysisManager::Invalidator &)
Definition at line 68 of file CallGraph.cpp.
References llvm::PreservedAnalyses::getChecker().
operator[]() [1/2]
CallGraphNode * llvm::CallGraph::operator[] (const Function * F) inline
Returns the call graph node for the provided function.
Definition at line 120 of file CallGraph.h.
References assert(), F, and I.
operator[]() [2/2]
const CallGraphNode * llvm::CallGraph::operator[] (const Function * F) const inline
Returns the call graph node for the provided function.
Definition at line 113 of file CallGraph.h.
References assert(), F, and I.
populateCallGraphNode()
void CallGraph::populateCallGraphNode (CallGraphNode * CGN)
Populate CGN based on the calls inside the associated function.
Definition at line 89 of file CallGraph.cpp.
References Callee, F, llvm::forEachCallbackFunction(), llvm::Function::getFunction(), getOrInsertFunction(), I, and llvm::Intrinsic::isLeaf().
Referenced by addToCallGraph(), and llvm::CallGraphUpdater::reanalyzeFunction().
print()
void CallGraph::print (raw_ostream & OS) const
Definition at line 118 of file CallGraph.cpp.
References llvm::Function::getFunction(), I, if(), and llvm::sort().
Referenced by dump().
removeFunctionFromModule()
Function * CallGraph::removeFunctionFromModule (CallGraphNode * CGN)
Unlink the function from this module, returning it.
Because this removes the function from the module, the call graph node is destroyed. This is only valid if the function does not call any other functions (ie, there are no edges in it's CGN). The easiest way to do this is to dropAllReferences before calling this.
Definition at line 160 of file CallGraph.cpp.
References assert(), and F.
Referenced by llvm::CallGraphUpdater::finalize().
ReplaceExternalCallEdge()
void CallGraph::ReplaceExternalCallEdge (CallGraphNode * Old, CallGraphNode * New)
Old node has been deleted, and New is to be used in its place, update the ExternalCallingNode.
Definition at line 144 of file CallGraph.cpp.
Referenced by llvm::CallGraphUpdater::replaceFunctionWith().
The documentation for this class was generated from the following files:
include/llvm/Analysis/CallGraph.h
lib/Analysis/CallGraph.cpp