LLVM: llvm::DivergenceAnalysis Class Reference
llvm::DivergenceAnalysis Class Reference
Generic divergence analysis for reducible CFGs.
#include "llvm/Analysis/DivergenceAnalysis.h"
Public Member Functions
DivergenceAnalysis (const Function &F, const Loop *RegionLoop, const DominatorTree &DT, const LoopInfo &LI, SyncDependenceAnalysis &SDA, bool IsLCSSAForm)
This instance will analyze the whole function F or the loop RegionLoop.
const Loop * getRegionLoop () const
The loop that defines the analyzed region (if any).
const Function & getFunction () const
bool inRegion (const BasicBlock &BB) const
Whether BB is part of the region.
bool inRegion (const Instruction &I) const
Whether I is part of the region.
void addUniformOverride (const Value &UniVal)
Mark UniVal as a value that is always uniform.
bool markDivergent (const Value &DivVal)
Mark DivVal as a value that is always divergent.
void compute ()
Propagate divergence to all instructions in the region.
bool hasDetectedDivergence () const
Whether any value was marked or analyzed to be divergent.
bool isAlwaysUniform (const Value &Val) const
Whether Val will always return a uniform value regardless of its operands.
bool isDivergent (const Value &Val) const
Whether Val is divergent at its definition.
bool isDivergentUse (const Use &U) const
Whether U is divergent.
void print (raw_ostream &OS, const Module *) const
Detailed Description
Generic divergence analysis for reducible CFGs.
This analysis propagates divergence in a data-parallel context from sources of divergence to all users. It requires reducible CFGs. All assignments should be in SSA form.
Definition at line 37 of file DivergenceAnalysis.h.
Constructor & Destructor Documentation
DivergenceAnalysis()
DivergenceAnalysis::DivergenceAnalysis (const Function & F, const Loop * RegionLoop, const DominatorTree & DT, const LoopInfo & LI, SyncDependenceAnalysis & SDA, bool IsLCSSAForm)
This instance will analyze the whole function F or the loop RegionLoop.
Parameters
RegionLoop if non-null the analysis is restricted to RegionLoop. Otherwise the whole function is analyzed.
IsLCSSAForm whether the analysis may assume that the IR in the region in in LCSSA form.
Definition at line 93 of file DivergenceAnalysis.cpp.
Member Function Documentation
addUniformOverride()
void DivergenceAnalysis::addUniformOverride (const Value & UniVal)
Mark UniVal as a value that is always uniform.
Definition at line 107 of file DivergenceAnalysis.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
Referenced by llvm::GPUDivergenceAnalysis::GPUDivergenceAnalysis().
compute()
void DivergenceAnalysis::compute ()
Propagate divergence to all instructions in the region.
Divergence is seeded by calls to markDivergent.
Definition at line 313 of file DivergenceAnalysis.cpp.
References assert(), I, and isDivergent().
Referenced by llvm::GPUDivergenceAnalysis::GPUDivergenceAnalysis().
getFunction()
const Function & llvm::DivergenceAnalysis::getFunction () const inline
Definition at line 52 of file DivergenceAnalysis.h.
References F.
Referenced by llvm::GPUDivergenceAnalysis::getFunction(), and llvm::GPUDivergenceAnalysis::print().
getRegionLoop()
const Loop * llvm::DivergenceAnalysis::getRegionLoop () const inline
The loop that defines the analyzed region (if any).
Definition at line 51 of file DivergenceAnalysis.h.
hasDetectedDivergence()
bool llvm::DivergenceAnalysis::hasDetectedDivergence () const inline
Whether any value was marked or analyzed to be divergent.
Definition at line 72 of file DivergenceAnalysis.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty().
Referenced by llvm::GPUDivergenceAnalysis::hasDivergence().
inRegion() [1/2]
bool DivergenceAnalysis::inRegion (const BasicBlock & BB) const
Whether BB is part of the region.
Definition at line 132 of file DivergenceAnalysis.cpp.
References llvm::LoopBase< BlockT, LoopT >::contains(), and llvm::BasicBlock::getParent().
Referenced by inRegion().
inRegion() [2/2]
bool DivergenceAnalysis::inRegion (const Instruction & I) const
Whether I is part of the region.
Definition at line 128 of file DivergenceAnalysis.cpp.
References I, and inRegion().
isAlwaysUniform()
bool DivergenceAnalysis::isAlwaysUniform (const Value & Val) const
Whether Val will always return a uniform value regardless of its operands.
Definition at line 333 of file DivergenceAnalysis.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::contains().
Referenced by markDivergent().
isDivergent()
bool DivergenceAnalysis::isDivergent (const Value & Val) const
Whether Val is divergent at its definition.
Definition at line 337 of file DivergenceAnalysis.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::contains().
Referenced by compute(), llvm::GPUDivergenceAnalysis::isDivergent(), isDivergentUse(), and print().
isDivergentUse()
bool DivergenceAnalysis::isDivergentUse (const Use & U) const
Whether U is divergent.
Uses of a uniform value can be divergent.
Definition at line 341 of file DivergenceAnalysis.cpp.
References I, and isDivergent().
Referenced by llvm::GPUDivergenceAnalysis::isDivergentUse().
markDivergent()
bool DivergenceAnalysis::markDivergent (const Value & DivVal)
Mark DivVal as a value that is always divergent.
Will not do so if isAlwaysUniform(DivVal).
Returns
Whether the tracked divergence state of DivVal changed.
Definition at line 99 of file DivergenceAnalysis.cpp.
References assert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), and isAlwaysUniform().
Referenced by llvm::GPUDivergenceAnalysis::GPUDivergenceAnalysis().
print()
void DivergenceAnalysis::print (raw_ostream & OS, const Module *) const
Definition at line 347 of file DivergenceAnalysis.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty(), I, instructions, and isDivergent().
Referenced by llvm::GPUDivergenceAnalysis::print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/DivergenceAnalysis.h
lib/Analysis/DivergenceAnalysis.cpp