LLVM: llvm::orc::tpctypes::WrapperFunctionResult Class Reference
llvm::orc::tpctypes::WrapperFunctionResult Class Reference
C++ wrapper function result: Same as CWrapperFunctionResult but auto-releases memory.
#include "llvm/ExecutionEngine/Orc/Shared/TargetProcessControlTypes.h"
Public Member Functions
WrapperFunctionResult ()
Create a default WrapperFunctionResult.
WrapperFunctionResult (CWrapperFunctionResult R)
Create a WrapperFunctionResult from a CWrapperFunctionResult.
WrapperFunctionResult (const WrapperFunctionResult &)=delete
WrapperFunctionResult & operator= (const WrapperFunctionResult &)=delete
WrapperFunctionResult (WrapperFunctionResult &&Other)
WrapperFunctionResult & operator= (WrapperFunctionResult &&Other)
~WrapperFunctionResult ()
CWrapperFunctionResult release ()
Relinquish ownership of and return the CWrapperFunctionResult.
ArrayRef< uint8_t > getData () const
Get an ArrayRef covering the data in the result.
Detailed Description
C++ wrapper function result: Same as CWrapperFunctionResult but auto-releases memory.
Definition at line 82 of file TargetProcessControlTypes.h.
Constructor & Destructor Documentation
WrapperFunctionResult() [1/4]
llvm::orc::tpctypes::WrapperFunctionResult::WrapperFunctionResult () inline
Create a default WrapperFunctionResult.
Definition at line 85 of file TargetProcessControlTypes.h.
WrapperFunctionResult() [2/4]
llvm::orc::tpctypes::WrapperFunctionResult::WrapperFunctionResult (CWrapperFunctionResult R) inline
Create a WrapperFunctionResult from a CWrapperFunctionResult.
This instance takes ownership of the result object and will automatically call the Destroy member upon destruction.
Definition at line 90 of file TargetProcessControlTypes.h.
WrapperFunctionResult() [3/4]
llvm::orc::tpctypes::WrapperFunctionResult::WrapperFunctionResult (const WrapperFunctionResult &) delete
WrapperFunctionResult() [4/4]
llvm::orc::tpctypes::WrapperFunctionResult::WrapperFunctionResult (WrapperFunctionResult && Other) inline
Definition at line 95 of file TargetProcessControlTypes.h.
References llvm::Other, and std::swap().
~WrapperFunctionResult()
llvm::orc::tpctypes::WrapperFunctionResult::~WrapperFunctionResult () inline
Definition at line 108 of file TargetProcessControlTypes.h.
Member Function Documentation
getData()
ArrayRef< uint8_t > llvm::orc::tpctypes::WrapperFunctionResult::getData () const inline
Get an ArrayRef covering the data in the result.
Definition at line 122 of file TargetProcessControlTypes.h.
operator=() [1/2]
WrapperFunctionResult & llvm::orc::tpctypes::WrapperFunctionResult::operator= (const WrapperFunctionResult &) delete
operator=() [2/2]
WrapperFunctionResult & llvm::orc::tpctypes::WrapperFunctionResult::operator= (WrapperFunctionResult && Other) inline
Definition at line 100 of file TargetProcessControlTypes.h.
References llvm::Other, and std::swap().
release()
CWrapperFunctionResult llvm::orc::tpctypes::WrapperFunctionResult::release () inline
Relinquish ownership of and return the CWrapperFunctionResult.
Definition at line 114 of file TargetProcessControlTypes.h.
References std::swap().
Referenced by llvm_orc_deregisterEHFrameSectionWrapper(), and llvm_orc_registerEHFrameSectionWrapper().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/TargetProcessControlTypes.h