LLVM: llvm::objcarc::ObjCARCAAResult Class Reference
llvm::objcarc::ObjCARCAAResult Class Reference
This is a simple alias analysis implementation that uses knowledge of ARC constructs to answer queries.
#include "llvm/Analysis/ObjCARCAliasAnalysis.h"
Public Member Functions
ObjCARCAAResult (const DataLayout &DL)
ObjCARCAAResult (ObjCARCAAResult &&Arg)
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &)
Handle invalidation events from the new pass manager.
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Public Member Functions inherited from llvm::AAResultBase< ObjCARCAAResult >
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase< ObjCARCAAResult >
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)
AAResultBase (AAResultBase &&Arg)
AAResultsProxy getBestAAResults ()
Get a proxy for the best AA result set to query at this time.
Detailed Description
This is a simple alias analysis implementation that uses knowledge of ARC constructs to answer queries.
TODO: This class could be generalized to know about other ObjC-specific tricks. Such as knowing that ivars in the non-fragile ABI are non-aliasing even though their offsets are dynamic.
Definition at line 37 of file ObjCARCAliasAnalysis.h.
Constructor & Destructor Documentation
ObjCARCAAResult() [1/2]
llvm::objcarc::ObjCARCAAResult::ObjCARCAAResult (const DataLayout & DL) inline explicit
Definition at line 43 of file ObjCARCAliasAnalysis.h.
References DL.
ObjCARCAAResult() [2/2]
llvm::objcarc::ObjCARCAAResult::ObjCARCAAResult (ObjCARCAAResult && Arg) inline
Definition at line 44 of file ObjCARCAliasAnalysis.h.
References DL.
Member Function Documentation
alias()
AliasResult ObjCARCAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI)
Definition at line 39 of file ObjCARCAliasAnalysis.cpp.
References llvm::AAResultBase< DerivedT >::alias(), llvm::objcarc::EnableARCOpts, llvm::MemoryLocation::getBeforeOrAfter(), llvm::objcarc::GetRCIdentityRoot(), llvm::objcarc::GetUnderlyingObjCPtr(), llvm::MayAlias, and llvm::NoAlias.
getModRefBehavior() [1/3]
FunctionModRefBehavior llvm::AAResultBase< DerivedT >::getModRefBehavior (const CallBase * Call) inline
Definition at line 1088 of file AliasAnalysis.h.
getModRefBehavior() [2/3]
FunctionModRefBehavior llvm::AAResultBase< DerivedT >::getModRefBehavior (const Function * F) inline
Definition at line 1092 of file AliasAnalysis.h.
getModRefBehavior() [3/3]
FunctionModRefBehavior ObjCARCAAResult::getModRefBehavior (const Function * F)
Definition at line 97 of file ObjCARCAliasAnalysis.cpp.
References llvm::objcarc::EnableARCOpts, F, llvm::FMRB_DoesNotAccessMemory, llvm::objcarc::GetFunctionClass(), llvm::AAResultBase< DerivedT >::getModRefBehavior(), and llvm::objcarc::NoopCast.
getModRefInfo() [1/3]
ModRefInfo llvm::AAResultBase< DerivedT >::getModRefInfo (const CallBase * Call, const MemoryLocation & Loc, AAQueryInfo & AAQI) inline
Definition at line 1096 of file AliasAnalysis.h.
getModRefInfo() [2/3]
ModRefInfo ObjCARCAAResult::getModRefInfo (const CallBase * Call, const MemoryLocation & Loc, AAQueryInfo & AAQI)
Definition at line 111 of file ObjCARCAliasAnalysis.cpp.
References llvm::objcarc::Autorelease, llvm::objcarc::AutoreleasepoolPush, llvm::objcarc::AutoreleaseRV, llvm::objcarc::Call, llvm::objcarc::EnableARCOpts, llvm::objcarc::FusedRetainAutorelease, llvm::objcarc::FusedRetainAutoreleaseRV, llvm::objcarc::GetBasicARCInstKind(), llvm::AAResultBase< DerivedT >::getModRefInfo(), llvm::NoModRef, llvm::objcarc::NoopCast, llvm::objcarc::Retain, and llvm::objcarc::RetainRV.
getModRefInfo() [3/3]
ModRefInfo llvm::AAResultBase< DerivedT >::getModRefInfo (const CallBase * Call1, const CallBase * Call2, AAQueryInfo & AAQI) inline
Definition at line 1101 of file AliasAnalysis.h.
invalidate()
bool llvm::objcarc::ObjCARCAAResult::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator &) inline
Handle invalidation events from the new pass manager.
By definition, this result is stateless and so remains valid.
Definition at line 50 of file ObjCARCAliasAnalysis.h.
pointsToConstantMemory()
bool ObjCARCAAResult::pointsToConstantMemory (const MemoryLocation & Loc, AAQueryInfo & AAQI, bool OrLocal)
Definition at line 73 of file ObjCARCAliasAnalysis.cpp.
References llvm::objcarc::EnableARCOpts, llvm::MemoryLocation::getBeforeOrAfter(), llvm::objcarc::GetRCIdentityRoot(), llvm::objcarc::GetUnderlyingObjCPtr(), and llvm::AAResultBase< DerivedT >::pointsToConstantMemory().
The documentation for this class was generated from the following files:
include/llvm/Analysis/ObjCARCAliasAnalysis.h
lib/Analysis/ObjCARCAliasAnalysis.cpp