LLVM: llvm::SCEVExpanderCleaner Class Reference
llvm::SCEVExpanderCleaner Class Reference
Helper to remove instructions inserted during SCEV expansion, unless they are marked as used.
#include "llvm/Transforms/Utils/ScalarEvolutionExpander.h"
Public Member Functions
SCEVExpanderCleaner (SCEVExpander &Expander, DominatorTree &DT)
~SCEVExpanderCleaner ()
void markResultUsed ()
Indicate that the result of the expansion is used.
Detailed Description
Helper to remove instructions inserted during SCEV expansion, unless they are marked as used.
Definition at line 491 of file ScalarEvolutionExpander.h.
Constructor & Destructor Documentation
SCEVExpanderCleaner()
llvm::SCEVExpanderCleaner::SCEVExpanderCleaner (SCEVExpander & Expander, DominatorTree & DT) inline
Definition at line 501 of file ScalarEvolutionExpander.h.
~SCEVExpanderCleaner()
llvm::SCEVExpanderCleaner::~SCEVExpanderCleaner ()
Definition at line 2685 of file ScalarEvolutionExpander.cpp.
References A, llvm::all_of(), assert(), B, llvm::SCEVExpander::clear(), llvm::DominatorTree::dominates(), llvm::UndefValue::get(), llvm::SCEVExpander::getAllInsertedInstructions(), I, and llvm::stable_sort().
Member Function Documentation
markResultUsed()
void llvm::SCEVExpanderCleaner::markResultUsed () inline
Indicate that the result of the expansion is used.
Definition at line 507 of file ScalarEvolutionExpander.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/ScalarEvolutionExpander.h
lib/Transforms/Utils/ScalarEvolutionExpander.cpp