LLVM: llvm::CallGraphSCC Class Reference
llvm::CallGraphSCC Class Reference
CallGraphSCC - This is a single SCC that a CallGraphSCCPass is run on.
#include "llvm/Analysis/CallGraphSCCPass.h"
Public Types
using iterator = std::vector<CallGraphNode *>::const_iterator
Public Member Functions
CallGraphSCC (CallGraph &cg, void *context)
void initialize (ArrayRef< CallGraphNode * > NewNodes)
bool isSingular () const
unsigned size () const
void ReplaceNode (CallGraphNode *Old, CallGraphNode *New)
ReplaceNode - This informs the SCC and the pass manager that the specified Old node has been deleted, and New is to be used in its place.
void DeleteNode (CallGraphNode *Old)
DeleteNode - This informs the SCC and the pass manager that the specified Old node has been deleted.
iterator begin () const
iterator end () const
const CallGraph & getCallGraph ()
Detailed Description
CallGraphSCC - This is a single SCC that a CallGraphSCCPass is run on.
Definition at line 87 of file CallGraphSCCPass.h.
Member Typedef Documentation
iterator
using llvm::CallGraphSCC::iterator = std::vector<CallGraphNode *>::const_iterator
Definition at line 110 of file CallGraphSCCPass.h.
Constructor & Destructor Documentation
CallGraphSCC()
llvm::CallGraphSCC::CallGraphSCC (CallGraph & cg, void * context) inline
Definition at line 93 of file CallGraphSCCPass.h.
References CG.
Member Function Documentation
begin()
iterator llvm::CallGraphSCC::begin () const inline
Definition at line 112 of file CallGraphSCCPass.h.
Referenced by createDevirtTriggerFunc(), and llvm::coro::updateCallGraph().
DeleteNode()
void CallGraphSCC::DeleteNode (CallGraphNode * Old)
DeleteNode - This informs the SCC and the pass manager that the specified Old node has been deleted.
Definition at line 609 of file CallGraphSCCPass.cpp.
Referenced by llvm::CallGraphUpdater::removeFunction().
end()
iterator llvm::CallGraphSCC::end () const inline
Definition at line 113 of file CallGraphSCCPass.h.
Referenced by createDevirtTriggerFunc(), and llvm::coro::updateCallGraph().
getCallGraph()
const CallGraph & llvm::CallGraphSCC::getCallGraph () inline
Definition at line 115 of file CallGraphSCCPass.h.
References CG.
Referenced by llvm::CallGraphSCCPass::skipSCC().
initialize()
void llvm::CallGraphSCC::initialize (ArrayRef< CallGraphNode * > NewNodes) inline
Definition at line 95 of file CallGraphSCCPass.h.
Referenced by createDevirtTriggerFunc(), and llvm::coro::updateCallGraph().
isSingular()
bool llvm::CallGraphSCC::isSingular () const inline
Definition at line 99 of file CallGraphSCCPass.h.
Referenced by inlineCallsImpl().
ReplaceNode()
void CallGraphSCC::ReplaceNode (CallGraphNode * Old, CallGraphNode * New)
ReplaceNode - This informs the SCC and the pass manager that the specified Old node has been deleted, and New is to be used in its place.
This informs the SCC and the pass manager that the specified Old node has been deleted, and New is to be used in its place.
Definition at line 591 of file CallGraphSCCPass.cpp.
References assert().
Referenced by llvm::CallGraphUpdater::replaceFunctionWith().
size()
unsigned llvm::CallGraphSCC::size () const inline
Definition at line 100 of file CallGraphSCCPass.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/CallGraphSCCPass.h
lib/Analysis/CallGraphSCCPass.cpp