LLVM: llvm::orc::shared::SerializationTraits< ChannelT, tpctypes::WrapperFunctionResult, tpctypes::WrapperFunctionResult, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > > Class Template Reference
llvm::orc::shared::SerializationTraits< ChannelT, tpctypes::WrapperFunctionResult, tpctypes::WrapperFunctionResult, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > > Class Template Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/OrcRPCTPCServer.h"
Static Public Member Functions
static Error serialize (ChannelT &C, const tpctypes::WrapperFunctionResult &E)
static Error deserialize (ChannelT &C, tpctypes::WrapperFunctionResult &E)
Detailed Description
template<typename ChannelT>
class llvm::orc::shared::SerializationTraits< ChannelT, tpctypes::WrapperFunctionResult, tpctypes::WrapperFunctionResult, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >
Definition at line 237 of file OrcRPCTPCServer.h.
Member Function Documentation
deserialize()
template<typename ChannelT > static Error llvm::orc::shared::SerializationTraits< ChannelT, tpctypes::WrapperFunctionResult, tpctypes::WrapperFunctionResult, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::deserialize (ChannelT & C, tpctypes::WrapperFunctionResult & E) inline static
Definition at line 252 of file OrcRPCTPCServer.h.
References C, llvm::orc::shared::deserializeSeq(), E, llvm::orc::tpctypes::CWrapperFunctionResult::Size, and llvm::Error::success().
serialize()
template<typename ChannelT > static Error llvm::orc::shared::SerializationTraits< ChannelT, tpctypes::WrapperFunctionResult, tpctypes::WrapperFunctionResult, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::serialize (ChannelT & C, const tpctypes::WrapperFunctionResult & E) inline static
Definition at line 241 of file OrcRPCTPCServer.h.
References C, llvm::Data, E, llvm::orc::shared::serializeSeq(), and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/TargetProcess/OrcRPCTPCServer.h