LLVM: llvm::object::TapiUniversal Class Reference
llvm::object::TapiUniversal Class Reference
#include "llvm/Object/TapiUniversal.h"
Classes
class object_iterator
class ObjectForArch
Public Member Functions
TapiUniversal (MemoryBufferRef Source, Error &Err)
~TapiUniversal () override
object_iterator begin_objects () const
object_iterator end_objects () const
iterator_range< object_iterator > objects () const
uint32_t getNumberOfObjects () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
virtual Error initContent ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isTapiUniversal () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isCOFFImportFile () const
bool isIR () const
bool isMinidump () const
bool isTapiFile () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static Expected< std::unique_ptr< TapiUniversal > > create (MemoryBufferRef Source)
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::Binary
static Error checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_COFFImportFile , ID_IR ,
ID_TapiUniversal , ID_TapiFile , ID_Minidump , ID_WinRes ,
ID_StartObjects , ID_COFF , ID_XCOFF32 , ID_XCOFF64 ,
ID_ELF32L , ID_ELF32B , ID_ELF64L , ID_ELF64B ,
ID_MachO32L , ID_MachO32B , ID_MachO64L , ID_MachO64B ,
ID_Wasm , ID_EndObjects
}
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 26 of file TapiUniversal.h.
Constructor & Destructor Documentation
TapiUniversal()
TapiUniversal::TapiUniversal (MemoryBufferRef Source, Error & Err)
Definition at line 23 of file TapiUniversal.cpp.
References llvm::MachO::TextAPIReader::get(), and Name.
Referenced by create().
~TapiUniversal()
TapiUniversal::~TapiUniversal () override default
Member Function Documentation
begin_objects()
object_iterator llvm::object::TapiUniversal::begin_objects () const inline
Definition at line 95 of file TapiUniversal.h.
Referenced by objects().
classof()
static bool llvm::object::TapiUniversal::classof (const Binary * v) inline static
Definition at line 106 of file TapiUniversal.h.
create()
Expected< std::unique_ptr< TapiUniversal > > TapiUniversal::create (MemoryBufferRef Source) static
Definition at line 55 of file TapiUniversal.cpp.
References llvm::Error::success(), and TapiUniversal().
Referenced by llvm::object::createBinary().
end_objects()
object_iterator llvm::object::TapiUniversal::end_objects () const inline
Definition at line 96 of file TapiUniversal.h.
Referenced by objects().
getNumberOfObjects()
uint32_t llvm::object::TapiUniversal::getNumberOfObjects () const inline
Definition at line 104 of file TapiUniversal.h.
objects()
iterator_range< object_iterator > llvm::object::TapiUniversal::objects () const inline
Definition at line 100 of file TapiUniversal.h.
References begin_objects(), end_objects(), and llvm::make_range().
The documentation for this class was generated from the following files:
include/llvm/Object/TapiUniversal.h
lib/Object/TapiUniversal.cpp