LLVM: llvm::orc::TPCIndirectionUtils Class Reference
llvm::orc::TPCIndirectionUtils Class Reference
Provides TargetProcessControl based indirect stubs, trampoline pool and lazy call through manager.
#include "llvm/ExecutionEngine/Orc/TPCIndirectionUtils.h"
Classes
class ABISupport
ABI support base class.
Public Member Functions
TargetProcessControl & getTargetProcessControl () const
Return a reference to the TargetProcessControl object.
ABISupport & getABISupport () const
Return a reference to the ABISupport object for this instance.
Error cleanup ()
Release memory for resources held by this instance.
Expected< JITTargetAddress > writeResolverBlock (JITTargetAddress ReentryFnAddr, JITTargetAddress ReentryCtxAddr)
Write resolver code to the target process and return its address.
JITTargetAddress getResolverBlockAddress () const
Returns the address of the Resolver block.
std::unique_ptr< IndirectStubsManager > createIndirectStubsManager ()
Create an IndirectStubsManager for the target process.
TrampolinePool & getTrampolinePool ()
Create a TrampolinePool for the target process.
LazyCallThroughManager & createLazyCallThroughManager (ExecutionSession &ES, JITTargetAddress ErrorHandlerAddr)
Create a LazyCallThroughManager.
LazyCallThroughManager & getLazyCallThroughManager ()
Create a LazyCallThroughManager for the target process.
Static Public Member Functions
template<typename ORCABI >
static std::unique_ptr< TPCIndirectionUtils > CreateWithABI (TargetProcessControl &TPC)
Create using the given ABI class.
static Expected< std::unique_ptr< TPCIndirectionUtils > > Create (TargetProcessControl &TPC)
Create based on the TargetProcessControl triple.
Friends
class TPCIndirectionUtilsAccess
Detailed Description
Provides TargetProcessControl based indirect stubs, trampoline pool and lazy call through manager.
Definition at line 30 of file TPCIndirectionUtils.h.
Member Function Documentation
cleanup()
Error llvm::orc::TPCIndirectionUtils::cleanup ()
Release memory for resources held by this instance.
This must be called prior to destruction of the class.
Definition at line 269 of file TPCIndirectionUtils.cpp.
References A, llvm::joinErrors(), and llvm::Error::success().
Create()
Expected< std::unique_ptr< TPCIndirectionUtils > > llvm::orc::TPCIndirectionUtils::Create (TargetProcessControl & TPC) static
Create based on the TargetProcessControl triple.
Definition at line 237 of file TPCIndirectionUtils.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_32, llvm::orc::TargetProcessControl::getTargetTriple(), llvm::inconvertibleErrorCode(), llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::x86, and llvm::Triple::x86_64.
createIndirectStubsManager()
std::unique_ptr< IndirectStubsManager > llvm::orc::TPCIndirectionUtils::createIndirectStubsManager ()
Create an IndirectStubsManager for the target process.
Definition at line 314 of file TPCIndirectionUtils.cpp.
createLazyCallThroughManager()
LazyCallThroughManager & llvm::orc::TPCIndirectionUtils::createLazyCallThroughManager (ExecutionSession & ES, JITTargetAddress ErrorHandlerAddr)
Create a LazyCallThroughManager.
This function should only be called once.
Definition at line 324 of file TPCIndirectionUtils.cpp.
References assert().
CreateWithABI()
template<typename ORCABI > std::unique_ptr< TPCIndirectionUtils > llvm::orc::TPCIndirectionUtils::CreateWithABI (TargetProcessControl & TPC) static
Create using the given ABI class.
Definition at line 214 of file TPCIndirectionUtils.h.
getABISupport()
ABISupport & llvm::orc::TPCIndirectionUtils::getABISupport () const inline
Return a reference to the ABISupport object for this instance.
Definition at line 93 of file TPCIndirectionUtils.h.
getLazyCallThroughManager()
LazyCallThroughManager & llvm::orc::TPCIndirectionUtils::getLazyCallThroughManager () inline
Create a LazyCallThroughManager for the target process.
Definition at line 123 of file TPCIndirectionUtils.h.
References assert().
Referenced by llvm::orc::setUpInProcessLCTMReentryViaTPCIU().
getResolverBlockAddress()
JITTargetAddress llvm::orc::TPCIndirectionUtils::getResolverBlockAddress () const inline
Returns the address of the Resolver block.
Returns zero if the writeResolverBlock method has not previously been called.
Definition at line 108 of file TPCIndirectionUtils.h.
getTargetProcessControl()
TargetProcessControl & llvm::orc::TPCIndirectionUtils::getTargetProcessControl () const inline
Return a reference to the TargetProcessControl object.
Definition at line 90 of file TPCIndirectionUtils.h.
getTrampolinePool()
TrampolinePool & llvm::orc::TPCIndirectionUtils::getTrampolinePool ()
Create a TrampolinePool for the target process.
Definition at line 318 of file TPCIndirectionUtils.cpp.
writeResolverBlock()
Expected< JITTargetAddress > llvm::orc::TPCIndirectionUtils::writeResolverBlock (JITTargetAddress ReentryFnAddr, JITTargetAddress ReentryCtxAddr)
Write resolver code to the target process and return its address.
This must be called before any call to createTrampolinePool or createLazyCallThroughManager.
Definition at line 286 of file TPCIndirectionUtils.cpp.
References assert(), llvm::sys::Memory::MF_EXEC, and llvm::sys::Memory::MF_READ.
Referenced by llvm::orc::setUpInProcessLCTMReentryViaTPCIU().
Friends And Related Symbol Documentation
TPCIndirectionUtilsAccess
friend class TPCIndirectionUtilsAccess friend
Definition at line 31 of file TPCIndirectionUtils.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TPCIndirectionUtils.h
lib/ExecutionEngine/Orc/TPCIndirectionUtils.cpp