LLVM: lib/Transforms/Coroutines/CoroCleanup.cpp File Reference
CoroCleanup.cpp File Reference
#include "llvm/Transforms/Coroutines/CoroCleanup.h"
#include "CoroInternal.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Scalar.h"
Macros
#define DEBUG_TYPE "coro-cleanup"
Functions
static void simplifyCFG (Function &F)
static void lowerSubFn (IRBuilder<> &Builder, CoroSubFnInst *SubFn)
static bool declaresCoroCleanupIntrinsics (const Module &M)
INITIALIZE_PASS (CoroCleanupLegacy, "coro-cleanup", "Lower all coroutine related intrinsics", false, false) Pass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "coro-cleanup"
Definition at line 19 of file CoroCleanup.cpp.
Function Documentation
declaresCoroCleanupIntrinsics()
static bool declaresCoroCleanupIntrinsics (const Module & M) static
Definition at line 97 of file CoroCleanup.cpp.
References llvm::coro::declaresIntrinsics().
Referenced by llvm::CoroCleanupPass::run().
INITIALIZE_PASS()
INITIALIZE_PASS (CoroCleanupLegacy , "coro-cleanup" , "Lower all coroutine related intrinsics" , false , false)
Definition at line 147 of file CoroCleanup.cpp.
lowerSubFn()
static void lowerSubFn (IRBuilder<> & Builder, CoroSubFnInst * SubFn) static
Definition at line 39 of file CoroCleanup.cpp.
References FramePtr, and llvm::StructType::get().
simplifyCFG()
static void simplifyCFG (Function & F) static
Definition at line 30 of file CoroCleanup.cpp.
References llvm::legacy::FunctionPassManager::add(), llvm::createCFGSimplificationPass(), llvm::legacy::FunctionPassManager::doFinalization(), llvm::legacy::FunctionPassManager::doInitialization(), F, and llvm::legacy::FunctionPassManager::run().