LLVM: lib/MC/MCAsmInfo.cpp File Reference
MCAsmInfo.cpp File Reference
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Support/CommandLine.h"
Enumerations
enum DefaultOnOff { Default , Enable , Disable }
Variables
static cl::opt< DefaultOnOff > DwarfExtendedLoc ("dwarf-extended-loc", cl::Hidden, cl::desc("Disable emission of the extended flags in .loc directives."), cl::values(clEnumVal(Default, "Default for platform"), clEnumVal(Enable, "Enabled"), clEnumVal(Disable, "Disabled")), cl::init(Default))
cl::opt< cl::boolOrDefault > UseLEB128Directives ("use-leb128-directives", cl::Hidden, cl::desc("Disable the usage of LEB128 directives, and generate .byte instead."), cl::init(cl::BOU_UNSET))
Enumeration Type Documentation
DefaultOnOff
enum DefaultOnOff
Enumerator
Default
Enable
Disable
Definition at line 23 of file MCAsmInfo.cpp.
Variable Documentation
DwarfExtendedLoc
cl::opt< DefaultOnOff > DwarfExtendedLoc("dwarf-extended-loc", cl::Hidden, cl::desc("Disable emission of the extended flags in .loc directives."), cl::values(clEnumVal(Default, "Default for platform"), clEnumVal(Enable, "Enabled"), clEnumVal(Disable, "Disabled")), cl::init(Default)) ("dwarf-extended-loc" , cl::Hidden , cl::desc("Disable emission of the extended flags in .loc directives.") , cl::values(clEnumVal(Default, "Default for platform"), clEnumVal(Enable, "Enabled"), clEnumVal(Disable, "Disabled")) , cl::init(Default)) static
Referenced by llvm::MCAsmInfo::MCAsmInfo().
UseLEB128Directives
cl::opt< cl::boolOrDefault > UseLEB128Directives("use-leb128-directives", cl::Hidden, cl::desc("Disable the usage of LEB128 directives, and generate .byte instead."), cl::init(cl::BOU_UNSET)) ("use-leb128-directives" , cl::Hidden , cl::desc("Disable the usage of LEB128 directives, and generate .byte instead.") , cl::init(cl::BOU_UNSET))
Referenced by llvm::MCAsmInfo::MCAsmInfo(), and llvm::MCAsmInfoXCOFF::MCAsmInfoXCOFF().