LLVM: llvm::elfabi Namespace Reference
llvm::elfabi Namespace Reference
Classes
struct DynamicEntries
class ELFStub
struct ELFSymbol
Typedefs
typedef uint16_t ELFArch
Enumerations
enum class ELFTarget { ELF32LE , ELF32BE , ELF64LE , ELF64BE }
enum class ELFSymbolType {
NoType = ELF::STT_NOTYPE , Object = ELF::STT_OBJECT , Func = ELF::STT_FUNC , TLS = ELF::STT_TLS ,
Unknown = 16
}
Functions
Expected< std::unique_ptr< ELFStub > > readELFFile (MemoryBufferRef Buf)
Attempt to read a binary ELF file from a MemoryBuffer.
Error writeBinaryStub (StringRef FilePath, const ELFStub &Stub, ELFTarget OutputFormat, bool WriteIfChanged=false)
Attempt to write a binary ELF stub.
const VersionTuple TBEVersionCurrent (1, 0)
Expected< std::unique_ptr< ELFStub > > readTBEFromBuffer (StringRef Buf)
Attempts to read an ELF interface file from a StringRef buffer.
Error writeTBEToOutputStream (raw_ostream &OS, const ELFStub &Stub)
Attempts to write an ELF interface file to a raw_ostream.
template<class ELFT >
static void initELFHeader (typename ELFT::Ehdr &ElfHeader, uint16_t Machine)
This initializes an ELF file header with information specific to a binary dynamic shared object.
static Expected< StringRef > terminatedSubstr (StringRef Str, size_t Offset)
This function behaves similarly to StringRef::substr(), but attempts to terminate the returned StringRef at the first null terminator.
Error appendToError (Error Err, StringRef After)
This function takes an error, and appends a string of text to the end of that error.
template<class ELFT >
static Error populateDynamic (DynamicEntries &Dyn, typename ELFT::DynRange DynTable)
This function populates a DynamicEntries struct using an ELFT::DynRange.
static ELFSymbolType convertInfoToType (uint8_t Info)
This function extracts symbol type from a symbol's st_info member and maps it to an ELFSymbolType enum.
template<class ELFT >
static ELFSymbol createELFSym (StringRef SymName, const typename ELFT::Sym &RawSym)
This function creates an ELFSymbol and populates all members using information from a binary ELFT::Sym.
template<class ELFT >
static Error populateSymbols (ELFStub &TargetStub, const typename ELFT::SymRange DynSym, StringRef DynStr)
This function populates an ELFStub with symbols using information read from an ELF binary.
template<class ELFT >
static Expected< std::unique_ptr< ELFStub > > buildStub (const ELFObjectFile< ELFT > &ElfObj)
Returns a new ELFStub with all members populated from an ELFObjectFile.
template<class ELFT >
static Error writeELFBinaryToFile (StringRef FilePath, const ELFStub &Stub, bool WriteIfChanged)
This function opens a file for writing and then writes a binary ELF stub to the file.
Typedef Documentation
ELFArch
typedef uint16_t llvm::elfabi::ELFArch
Definition at line 25 of file ELFStub.h.
Enumeration Type Documentation
ELFSymbolType
enum class llvm::elfabi::ELFSymbolType strong
Enumerator
NoType
Object
Func
TLS
Unknown
Definition at line 27 of file ELFStub.h.
ELFTarget
enum class llvm::elfabi::ELFTarget strong
Enumerator
ELF32LE
ELF32BE
ELF64LE
ELF64BE
Definition at line 27 of file ELFObjHandler.h.
Function Documentation
appendToError()
Error llvm::elfabi::appendToError (Error Err, StringRef After)
This function takes an error, and appends a string of text to the end of that error.
Since "appending" to an Error isn't supported behavior of an Error, this function technically creates a new error with the combined message and consumes the old error.
Parameters
Err Source error.
After Text to append at the end of Err's error message.
Definition at line 360 of file ELFObjHandler.cpp.
References llvm::consumeError(), llvm::createError(), and llvm::raw_string_ostream::str().
Referenced by buildStub().
buildStub()
template<class ELFT > static Expected< std::unique_ptr< ELFStub > > llvm::elfabi::buildStub (const ELFObjectFile< ELFT > & ElfObj) static
Returns a new ELFStub with all members populated from an ELFObjectFile.
Parameters
ElfObj Source ELFObjectFile.
Definition at line 527 of file ELFObjHandler.cpp.
References appendToError(), and terminatedSubstr().
Referenced by readELFFile().
convertInfoToType()
static ELFSymbolType llvm::elfabi::convertInfoToType (uint8_t Info) static
This function extracts symbol type from a symbol's st_info member and maps it to an ELFSymbolType enum.
Currently, STT_NOTYPE, STT_OBJECT, STT_FUNC, and STT_TLS are supported. Other symbol types are mapped to ELFSymbolType::Unknown.
Parameters
Info Binary symbol st_info to extract symbol type from.
Definition at line 449 of file ELFObjHandler.cpp.
References Func, NoType, Object, llvm::ELF::STT_FUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_TLS, TLS, and Unknown.
Referenced by createELFSym().
createELFSym()
template<class ELFT > static ELFSymbol llvm::elfabi::createELFSym (StringRef SymName, const typename ELFT::Sym & RawSym) static
This function creates an ELFSymbol and populates all members using information from a binary ELFT::Sym.
Parameters
SymName The desired name of the ELFSymbol.
RawSym ELFT::Sym to extract symbol information from.
Definition at line 471 of file ELFObjHandler.cpp.
References convertInfoToType(), Func, and llvm::ELF::STB_WEAK.
initELFHeader()
template<class ELFT > static void llvm::elfabi::initELFHeader (typename ELFT::Ehdr & ElfHeader, uint16_t Machine) static
This initializes an ELF file header with information specific to a binary dynamic shared object.
Offsets, indexes, links, etc. for section and program headers are just zero-initialized as they will be updated elsewhere.
Parameters
ElfHeader Target ELFT::Ehdr to populate.
Machine Target architecture (e_machine from ELF specifications).
Definition at line 53 of file ELFObjHandler.cpp.
References llvm::ELF::EI_CLASS, llvm::ELF::EI_DATA, llvm::ELF::EI_MAG0, llvm::ELF::EI_MAG1, llvm::ELF::EI_MAG2, llvm::ELF::EI_MAG3, llvm::ELF::EI_OSABI, llvm::ELF::EI_VERSION, llvm::ELF::ELFCLASS32, llvm::ELF::ELFCLASS64, llvm::ELF::ELFDATA2LSB, llvm::ELF::ELFDATA2MSB, llvm::ELF::ElfMagic, llvm::ELF::ELFOSABI_NONE, llvm::ELF::ET_DYN, llvm::ELF::EV_CURRENT, and llvm::support::little.
populateDynamic()
template<class ELFT > static Error llvm::elfabi::populateDynamic (DynamicEntries & Dyn, typename ELFT::DynRange DynTable) static
This function populates a DynamicEntries struct using an ELFT::DynRange.
After populating the struct, the members are validated with some basic sanity checks.
Parameters
Dyn Target DynamicEntries struct to populate.
DynTable Source dynamic table.
Definition at line 376 of file ELFObjHandler.cpp.
References llvm::createError(), llvm::createStringError(), llvm::elfabi::DynamicEntries::DynSymAddr, llvm::elfabi::DynamicEntries::ElfHash, llvm::elfabi::DynamicEntries::GnuHash, llvm::Optional< T >::hasValue(), llvm::elfabi::DynamicEntries::NeededLibNames, Offset, llvm::elfabi::DynamicEntries::SONameOffset, llvm::elfabi::DynamicEntries::StrSize, llvm::elfabi::DynamicEntries::StrTabAddr, and llvm::Error::success().
populateSymbols()
template<class ELFT > static Error llvm::elfabi::populateSymbols (ELFStub & TargetStub, const typename ELFT::SymRange DynSym, StringRef DynStr) static
This function populates an ELFStub with symbols using information read from an ELF binary.
Parameters
TargetStub ELFStub to add symbols to.
DynSym Range of dynamic symbols to add to TargetStub.
DynStr StringRef to the dynamic string table.
Definition at line 498 of file ELFObjHandler.cpp.
References llvm::ELF::STB_GLOBAL, llvm::ELF::STB_WEAK, llvm::ELF::STV_DEFAULT, llvm::ELF::STV_PROTECTED, llvm::Error::success(), and terminatedSubstr().
readELFFile()
Expected< std::unique_ptr< ELFStub > > llvm::elfabi::readELFFile (MemoryBufferRef Buf)
Attempt to read a binary ELF file from a MemoryBuffer.
Definition at line 645 of file ELFObjHandler.cpp.
References buildStub(), llvm::object::createBinary(), llvm::createStringError(), llvm::dyn_cast(), and llvm::not_supported.
readTBEFromBuffer()
Expected< std::unique_ptr< ELFStub > > llvm::elfabi::readTBEFromBuffer (StringRef Buf)
Attempts to read an ELF interface file from a StringRef buffer.
Definition at line 123 of file TBEHandler.cpp.
References llvm::createStringError(), and TBEVersionCurrent().
TBEVersionCurrent()
const VersionTuple llvm::elfabi::TBEVersionCurrent (1 , 0)
Referenced by readTBEFromBuffer().
terminatedSubstr()
static Expected< StringRef > llvm::elfabi::terminatedSubstr (StringRef Str, size_t Offset) static
This function behaves similarly to StringRef::substr(), but attempts to terminate the returned StringRef at the first null terminator.
If no null terminator is found, an error is returned.
Parameters
Str Source string to create a substring from.
Offset The start index of the desired substring.
Definition at line 342 of file ELFObjHandler.cpp.
References llvm::createError(), llvm::StringRef::find(), llvm::StringRef::npos, Offset, and llvm::StringRef::substr().
Referenced by buildStub(), and populateSymbols().
writeBinaryStub()
Error llvm::elfabi::writeBinaryStub (StringRef FilePath, const ELFStub & Stub, ELFTarget OutputFormat, bool WriteIfChanged = false)
Attempt to write a binary ELF stub.
This function determines appropriate ELFType using the passed ELFTarget and then writes a binary ELF stub to a specified file path.
Parameters
FilePath File path for writing the ELF binary.
Stub Source ELFStub to generate a binary ELF stub from.
OutputFormat Target ELFType to write binary as.
WriteIfChanged Whether or not to preserve timestamp if the output stays the same.
Definition at line 666 of file ELFObjHandler.cpp.
References ELF32BE, ELF32LE, ELF64BE, ELF64LE, llvm_unreachable, and WriteIfChanged.
writeELFBinaryToFile()
template<class ELFT > static Error llvm::elfabi::writeELFBinaryToFile (StringRef FilePath, const ELFStub & Stub, bool WriteIfChanged) static
This function opens a file for writing and then writes a binary ELF stub to the file.
Parameters
FilePath File path for writing the ELF binary.
Stub Source ELFStub to generate a binary ELF stub from.
Definition at line 611 of file ELFObjHandler.cpp.
References llvm::FileOutputBuffer::create(), llvm::createStringError(), llvm::MemoryBuffer::getFile(), llvm::invalid_argument, memcmp, llvm::Error::success(), llvm::toString(), and WriteIfChanged.
writeTBEToOutputStream()
Error llvm::elfabi::writeTBEToOutputStream (raw_ostream & OS, const ELFStub & Stub)
Attempts to write an ELF interface file to a raw_ostream.
Definition at line 138 of file TBEHandler.cpp.
References llvm::Error::success().