LLVM: lib/Support/Program.cpp File Reference
Program.cpp File Reference
#include "llvm/Support/Program.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/raw_ostream.h"
#include <system_error>
#include "Unix/Program.inc"
Functions
static bool Execute (ProcessInfo &PI, StringRef Program, ArrayRef< StringRef > Args, Optional< ArrayRef< StringRef > > Env, ArrayRef< Optional< StringRef > > Redirects, unsigned MemoryLimit, std::string *ErrMsg, BitVector *AffinityMask)
Function Documentation
Execute()
static bool Execute (ProcessInfo & PI, StringRef Program, ArrayRef< StringRef > Args, Optional< ArrayRef< StringRef > > Env, ArrayRef< Optional< StringRef > > Redirects, unsigned MemoryLimit, std::string * ErrMsg, BitVector * AffinityMask) static
Referenced by llvm::mca::Context::createDefaultPipeline(), llvm::sys::ExecuteAndWait(), and llvm::sys::ExecuteNoWait().