LLVM: lib/ExecutionEngine/Orc/TargetProcess/RegisterEHFrames.cpp File Reference
RegisterEHFrames.cpp File Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/RegisterEHFrames.h"
#include "llvm/Config/config.h"
#include "llvm/ExecutionEngine/JITSymbol.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/DynamicLibrary.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/FormatVariadic.h"
Namespaces
namespace llvm
This class represents lattice values for constants.
namespace llvm::orc
Macros
#define DEBUG_TYPE "orc"
Functions
void llvm::orc::__register_frame (const void *)
void llvm::orc::__deregister_frame (const void *)
Error llvm::orc::registerFrameWrapper (const void *P)
Error llvm::orc::deregisterFrameWrapper (const void *P)
Error llvm::orc::registerEHFrameSection (const void *EHFrameSectionAddr, size_t EHFrameSectionSize)
Register frames in the given eh-frame section with libunwind.
Error llvm::orc::deregisterEHFrameSection (const void *EHFrameSectionAddr, size_t EHFrameSectionSize)
Unregister frames in the given eh-frame section with libunwind.
CWrapperFunctionResult llvm_orc_registerEHFrameSectionWrapper (uint8_t *Data, uint64_t Size)
CWrapperFunctionResult llvm_orc_deregisterEHFrameSectionWrapper (uint8_t *Data, uint64_t Size)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "orc"
Definition at line 22 of file RegisterEHFrames.cpp.
Function Documentation
llvm_orc_deregisterEHFrameSectionWrapper()
CWrapperFunctionResult llvm_orc_deregisterEHFrameSectionWrapper (uint8_t * Data, uint64_t Size)
Definition at line 185 of file RegisterEHFrames.cpp.
References llvm::cantFail(), llvm::Data, llvm::orc::deregisterEHFrameSection(), llvm::orc::tpctypes::WrapperFunctionResult::release(), Size, and llvm::toString().
llvm_orc_registerEHFrameSectionWrapper()
CWrapperFunctionResult llvm_orc_registerEHFrameSectionWrapper (uint8_t * Data, uint64_t Size)
Definition at line 159 of file RegisterEHFrames.cpp.
References llvm::cantFail(), llvm::Data, llvm::orc::registerEHFrameSection(), llvm::orc::tpctypes::WrapperFunctionResult::release(), Size, and llvm::toString().