LLVM: lib/Target/RISCV/MCTargetDesc/RISCVInstPrinter.cpp File Reference
RISCVInstPrinter.cpp File Reference
#include "RISCVInstPrinter.h"
#include "RISCVBaseInfo.h"
#include "RISCVMCExpr.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "RISCVGenAsmWriter.inc"
#include "RISCVGenCompressInstEmitter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
#define PRINT_ALIAS_INSTR
#define GEN_UNCOMPRESS_INSTR
Variables
static cl::opt< bool > NoAliases ("riscv-no-aliases", cl::desc("Disable the emission of assembler pseudo instructions"), cl::init(false), cl::Hidden)
static cl::opt< bool > ArchRegNames ("riscv-arch-reg-names", cl::desc("Print architectural register names rather than the " "ABI names (such as x2 instead of sp)"), cl::init(false), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 27 of file RISCVInstPrinter.cpp.
GEN_UNCOMPRESS_INSTR
#define GEN_UNCOMPRESS_INSTR
Definition at line 34 of file RISCVInstPrinter.cpp.
PRINT_ALIAS_INSTR
#define PRINT_ALIAS_INSTR
Definition at line 30 of file RISCVInstPrinter.cpp.
Variable Documentation
ArchRegNames
cl::opt< bool > ArchRegNames("riscv-arch-reg-names", cl::desc("Print architectural register names rather than the " "ABI names (such as x2 instead of sp)"), cl::init(false), cl::Hidden) ("riscv-arch-reg-names" , cl::desc("Print architectural register names rather than the " "ABI names (such as x2 instead of sp)") , cl::init(false) , cl::Hidden) static
Referenced by llvm::RISCVInstPrinter::applyTargetSpecificCLOption(), and llvm::RISCVInstPrinter::getRegisterName().
NoAliases
cl::opt< bool > NoAliases("riscv-no-aliases", cl::desc("Disable the emission of assembler pseudo instructions"), cl::init(false), cl::Hidden) ("riscv-no-aliases" , cl::desc("Disable the emission of assembler pseudo instructions") , cl::init(false) , cl::Hidden) static
Referenced by AddAliasScopeMetadata(), llvm::RISCVInstPrinter::applyTargetSpecificCLOption(), and llvm::RISCVInstPrinter::printInst().