LLVM: lib/Transforms/Scalar/Scalar.cpp File Reference
Scalar.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm-c/Initialization.h"
#include "llvm-c/Transforms/Scalar.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/Analysis/ScopedNoAliasAA.h"
#include "llvm/Analysis/TypeBasedAliasAnalysis.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/IR/Verifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/Transforms/Scalar/GVN.h"
#include "llvm/Transforms/Scalar/Scalarizer.h"
#include "llvm/Transforms/Scalar/SimpleLoopUnswitch.h"
#include "llvm/Transforms/Utils/UnifyFunctionExitNodes.h"
Functions
void LLVMAddLoopSimplifyCFGPass (LLVMPassManagerRef PM)
void LLVMInitializeScalarOpts (LLVMPassRegistryRef R)
void LLVMAddAggressiveDCEPass (LLVMPassManagerRef PM)
See llvm::createAggressiveDCEPass function.
void LLVMAddDCEPass (LLVMPassManagerRef PM)
See llvm::createDeadCodeEliminationPass function.
void LLVMAddBitTrackingDCEPass (LLVMPassManagerRef PM)
See llvm::createBitTrackingDCEPass function.
void LLVMAddAlignmentFromAssumptionsPass (LLVMPassManagerRef PM)
See llvm::createAlignmentFromAssumptionsPass function.
void LLVMAddCFGSimplificationPass (LLVMPassManagerRef PM)
See llvm::createCFGSimplificationPass function.
void LLVMAddDeadStoreEliminationPass (LLVMPassManagerRef PM)
See llvm::createDeadStoreEliminationPass function.
void LLVMAddScalarizerPass (LLVMPassManagerRef PM)
See llvm::createScalarizerPass function.
void LLVMAddGVNPass (LLVMPassManagerRef PM)
See llvm::createGVNPass function.
void LLVMAddNewGVNPass (LLVMPassManagerRef PM)
See llvm::createGVNPass function.
void LLVMAddMergedLoadStoreMotionPass (LLVMPassManagerRef PM)
See llvm::createMergedLoadStoreMotionPass function.
void LLVMAddIndVarSimplifyPass (LLVMPassManagerRef PM)
See llvm::createIndVarSimplifyPass function.
void LLVMAddInstructionSimplifyPass (LLVMPassManagerRef PM)
See llvm::createInstSimplifyLegacyPass function.
void LLVMAddJumpThreadingPass (LLVMPassManagerRef PM)
See llvm::createJumpThreadingPass function.
void LLVMAddLoopSinkPass (LLVMPassManagerRef PM)
void LLVMAddLICMPass (LLVMPassManagerRef PM)
See llvm::createLICMPass function.
void LLVMAddLoopDeletionPass (LLVMPassManagerRef PM)
See llvm::createLoopDeletionPass function.
void LLVMAddLoopFlattenPass (LLVMPassManagerRef PM)
void LLVMAddLoopIdiomPass (LLVMPassManagerRef PM)
See llvm::createLoopIdiomPass function.
void LLVMAddLoopRotatePass (LLVMPassManagerRef PM)
See llvm::createLoopRotatePass function.
void LLVMAddLoopRerollPass (LLVMPassManagerRef PM)
See llvm::createLoopRerollPass function.
void LLVMAddLoopUnrollPass (LLVMPassManagerRef PM)
See llvm::createLoopUnrollPass function.
void LLVMAddLoopUnrollAndJamPass (LLVMPassManagerRef PM)
See llvm::createLoopUnrollAndJamPass function.
void LLVMAddLoopUnswitchPass (LLVMPassManagerRef PM)
See llvm::createLoopUnswitchPass function.
void LLVMAddLowerAtomicPass (LLVMPassManagerRef PM)
See llvm::createLowerAtomicPass function.
void LLVMAddMemCpyOptPass (LLVMPassManagerRef PM)
See llvm::createMemCpyOptPass function.
void LLVMAddPartiallyInlineLibCallsPass (LLVMPassManagerRef PM)
See llvm::createPartiallyInlineLibCallsPass function.
void LLVMAddReassociatePass (LLVMPassManagerRef PM)
See llvm::createReassociatePass function.
void LLVMAddSCCPPass (LLVMPassManagerRef PM)
See llvm::createSCCPPass function.
void LLVMAddScalarReplAggregatesPass (LLVMPassManagerRef PM)
See llvm::createSROAPass function.
void LLVMAddScalarReplAggregatesPassSSA (LLVMPassManagerRef PM)
See llvm::createSROAPass function.
void LLVMAddScalarReplAggregatesPassWithThreshold (LLVMPassManagerRef PM, int Threshold)
See llvm::createSROAPass function.
void LLVMAddSimplifyLibCallsPass (LLVMPassManagerRef PM)
See llvm::createSimplifyLibCallsPass function.
void LLVMAddTailCallEliminationPass (LLVMPassManagerRef PM)
See llvm::createTailCallEliminationPass function.
void LLVMAddDemoteMemoryToRegisterPass (LLVMPassManagerRef PM)
See llvm::demotePromoteMemoryToRegisterPass function.
void LLVMAddVerifierPass (LLVMPassManagerRef PM)
See llvm::createVerifierPass function.
void LLVMAddCorrelatedValuePropagationPass (LLVMPassManagerRef PM)
See llvm::createCorrelatedValuePropagationPass function.
void LLVMAddEarlyCSEPass (LLVMPassManagerRef PM)
See llvm::createEarlyCSEPass function.
void LLVMAddEarlyCSEMemSSAPass (LLVMPassManagerRef PM)
See llvm::createEarlyCSEPass function.
void LLVMAddGVNHoistLegacyPass (LLVMPassManagerRef PM)
void LLVMAddTypeBasedAliasAnalysisPass (LLVMPassManagerRef PM)
See llvm::createTypeBasedAliasAnalysisPass function.
void LLVMAddScopedNoAliasAAPass (LLVMPassManagerRef PM)
See llvm::createScopedNoAliasAAPass function.
void LLVMAddBasicAliasAnalysisPass (LLVMPassManagerRef PM)
See llvm::createBasicAliasAnalysisPass function.
void LLVMAddLowerConstantIntrinsicsPass (LLVMPassManagerRef PM)
See llvm::createLowerConstantIntrinsicsPass function.
void LLVMAddLowerExpectIntrinsicPass (LLVMPassManagerRef PM)
See llvm::createLowerExpectIntrinsicPass function.
void LLVMAddUnifyFunctionExitNodesPass (LLVMPassManagerRef PM)
See llvm::createUnifyFunctionExitNodesPass function.
Function Documentation
LLVMAddGVNHoistLegacyPass()
void LLVMAddGVNHoistLegacyPass (LLVMPassManagerRef PM)
Definition at line 281 of file Scalar.cpp.
References llvm::createGVNHoistPass(), and llvm::unwrap().
LLVMAddLoopFlattenPass()
void LLVMAddLoopFlattenPass (LLVMPassManagerRef PM)
Definition at line 192 of file Scalar.cpp.
References llvm::createLoopFlattenPass(), and llvm::unwrap().
LLVMAddLoopSimplifyCFGPass()
void LLVMAddLoopSimplifyCFGPass (LLVMPassManagerRef PM)
Definition at line 120 of file Scalar.cpp.
References llvm::createLoopSimplifyCFGPass(), and llvm::unwrap().
LLVMAddLoopSinkPass()
void LLVMAddLoopSinkPass (LLVMPassManagerRef PM)
Definition at line 180 of file Scalar.cpp.
References llvm::createLoopSinkPass(), and llvm::unwrap().