LLVM: llvm::InstrProfValueSiteRecord Struct Reference
llvm::InstrProfValueSiteRecord Struct Reference
#include "llvm/ProfileData/InstrProf.h"
Public Member Functions
InstrProfValueSiteRecord ()
template<class InputIterator >
InstrProfValueSiteRecord (InputIterator F, InputIterator L)
void sortByTargetValues ()
Sort ValueData ascending by Value.
void sortByCount ()
Sort ValueData Descending by Count.
void merge (InstrProfValueSiteRecord &Input, uint64_t Weight, function_ref< void(instrprof_error)> Warn)
Merge data from another InstrProfValueSiteRecord Optionally scale merged counts by Weight.
void scale (uint64_t N, uint64_t D, function_ref< void(instrprof_error)> Warn)
Scale up value profile data counts by N (Numerator) / D (Denominator).
void overlap (InstrProfValueSiteRecord &Input, uint32_t ValueKind, OverlapStats &Overlap, OverlapStats &FuncLevelOverlap)
Compute the overlap b/w this record and Input record.
Public Attributes
std::list< InstrProfValueData > ValueData
Value profiling data pairs at a given value site.
Detailed Description
Definition at line 657 of file InstrProf.h.
Constructor & Destructor Documentation
InstrProfValueSiteRecord() [1/2]
llvm::InstrProfValueSiteRecord::InstrProfValueSiteRecord () inline
Definition at line 661 of file InstrProf.h.
References ValueData.
InstrProfValueSiteRecord() [2/2]
template<class InputIterator > llvm::InstrProfValueSiteRecord::InstrProfValueSiteRecord (InputIterator F, InputIterator L) inline
Definition at line 663 of file InstrProf.h.
Member Function Documentation
merge()
void llvm::InstrProfValueSiteRecord::merge (InstrProfValueSiteRecord & Input, uint64_t Weight, function_ref< void(instrprof_error)> Warn)
Merge data from another InstrProfValueSiteRecord Optionally scale merged counts by Weight.
Definition at line 605 of file InstrProf.cpp.
References llvm::counter_overflow, I, llvm::SaturatingMultiplyAdd(), sortByTargetValues(), and ValueData.
overlap()
void llvm::InstrProfValueSiteRecord::overlap (InstrProfValueSiteRecord & Input, uint32_t ValueKind, OverlapStats & Overlap, OverlapStats & FuncLevelOverlap)
Compute the overlap b/w this record and Input record.
Definition at line 505 of file InstrProf.cpp.
References llvm::OverlapStats::Base, I, llvm::OverlapStats::Overlap, llvm::OverlapStats::score(), sortByTargetValues(), llvm::OverlapStats::Test, llvm::CountSumOrPercent::ValueCounts, and ValueData.
scale()
void llvm::InstrProfValueSiteRecord::scale (uint64_t N, uint64_t D, function_ref< void(instrprof_error)> Warn)
Scale up value profile data counts by N (Numerator) / D (Denominator).
Definition at line 628 of file InstrProf.cpp.
References llvm::counter_overflow, D, I, N, llvm::SaturatingMultiply(), and ValueData.
sortByCount()
void llvm::InstrProfValueSiteRecord::sortByCount () inline
Sort ValueData Descending by Count.
Definition at line 934 of file InstrProf.h.
References ValueData.
sortByTargetValues()
void llvm::InstrProfValueSiteRecord::sortByTargetValues () inline
Sort ValueData ascending by Value.
Definition at line 667 of file InstrProf.h.
References ValueData.
Referenced by merge(), and overlap().
Member Data Documentation
ValueData
std::list<InstrProfValueData> llvm::InstrProfValueSiteRecord::ValueData
Value profiling data pairs at a given value site.
Definition at line 659 of file InstrProf.h.
Referenced by InstrProfValueSiteRecord(), merge(), overlap(), scale(), sortByCount(), and sortByTargetValues().
The documentation for this struct was generated from the following files:
include/llvm/ProfileData/InstrProf.h
lib/ProfileData/InstrProf.cpp