LLVM: llvm::BitstreamEntry Struct Reference
llvm::BitstreamEntry Struct Reference
When advancing through a bitstream cursor, each advance can discover a few different kinds of entries:
#include "llvm/Bitstream/BitstreamReader.h"
Public Types
enum { Error , EndBlock , SubBlock , Record }
Static Public Member Functions
static BitstreamEntry getError ()
static BitstreamEntry getEndBlock ()
static BitstreamEntry getSubBlock (unsigned ID)
static BitstreamEntry getRecord (unsigned AbbrevID)
Public Attributes
enum llvm::BitstreamEntry:: { ... } Kind
unsigned ID
Detailed Description
When advancing through a bitstream cursor, each advance can discover a few different kinds of entries:
Definition at line 307 of file BitstreamReader.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
Error
EndBlock
SubBlock
Record
Definition at line 308 of file BitstreamReader.h.
Member Function Documentation
getEndBlock()
static BitstreamEntry llvm::BitstreamEntry::getEndBlock () inline static
Definition at line 322 of file BitstreamReader.h.
References E, EndBlock, and Kind.
Referenced by llvm::BitstreamCursor::advance().
getError()
static BitstreamEntry llvm::BitstreamEntry::getError () inline static
Definition at line 318 of file BitstreamReader.h.
References E, Error, and Kind.
Referenced by llvm::BitstreamCursor::advance().
getRecord()
static BitstreamEntry llvm::BitstreamEntry::getRecord (unsigned AbbrevID) inline static
Definition at line 330 of file BitstreamReader.h.
References E, Kind, and Record.
Referenced by llvm::BitstreamCursor::advance().
getSubBlock()
static BitstreamEntry llvm::BitstreamEntry::getSubBlock (unsigned ID) inline static
Definition at line 326 of file BitstreamReader.h.
References E, ID, Kind, and SubBlock.
Referenced by llvm::BitstreamCursor::advance().
Member Data Documentation
ID
unsigned llvm::BitstreamEntry::ID
Definition at line 316 of file BitstreamReader.h.
Referenced by getSubBlock().
[]
enum { ... } llvm::BitstreamEntry::Kind
Referenced by getEndBlock(), getError(), getRecord(), and getSubBlock().
The documentation for this struct was generated from the following file:
include/llvm/Bitstream/BitstreamReader.h