LLVM: llvm::mca::ResourceUsage Struct Reference
llvm::mca::ResourceUsage Struct Reference
Helper used by class InstrDesc to describe how hardware resources are used.
#include "llvm/MCA/Instruction.h"
Public Member Functions
ResourceUsage (CycleSegment Cycles, unsigned Units=1)
unsigned size () const
bool isReserved () const
void setReserved ()
Public Attributes
CycleSegment CS
unsigned NumUnits
Detailed Description
Helper used by class InstrDesc to describe how hardware resources are used.
This class describes how many resource units of a specific resource kind (and how many cycles) are "used" by an instruction.
Definition at line 337 of file Instruction.h.
Constructor & Destructor Documentation
ResourceUsage()
llvm::mca::ResourceUsage::ResourceUsage (CycleSegment Cycles, unsigned Units = 1) inline
Definition at line 340 of file Instruction.h.
Member Function Documentation
isReserved()
bool llvm::mca::ResourceUsage::isReserved () const inline
Definition at line 343 of file Instruction.h.
References CS, and llvm::mca::CycleSegment::isReserved().
setReserved()
void llvm::mca::ResourceUsage::setReserved () inline
Definition at line 344 of file Instruction.h.
References CS, and llvm::mca::CycleSegment::setReserved().
size()
unsigned llvm::mca::ResourceUsage::size () const inline
Definition at line 342 of file Instruction.h.
References CS, and llvm::mca::CycleSegment::size().
Member Data Documentation
CS
CycleSegment llvm::mca::ResourceUsage::CS
Definition at line 338 of file Instruction.h.
Referenced by isReserved(), setReserved(), and size().
NumUnits
unsigned llvm::mca::ResourceUsage::NumUnits
Definition at line 339 of file Instruction.h.
The documentation for this struct was generated from the following file:
include/llvm/MCA/Instruction.h