LLVM: llvm::omp::OpenMPInModule Struct Reference
llvm::omp::OpenMPInModule Struct Reference
Helper to remember if the module contains OpenMP (runtime calls), to be used foremost with containsOpenMP.
#include "llvm/Transforms/IPO/OpenMPOpt.h"
Public Member Functions
OpenMPInModule & operator= (bool Found)
bool isKnown ()
operator bool ()
bool containsOMPRuntimeCalls (Function *F) const
Does this function F contain any OpenMP runtime calls?
SmallPtrSetImpl< Kernel > & getKernels ()
Return the known kernels (=GPU entry points) in the module.
void identifyKernels (Module &M)
Identify kernels in the module and populate the Kernels set.
Friends
bool containsOpenMP (Module &M, OpenMPInModule &OMPInModule)
Helper to determine if M contains OpenMP (runtime calls).
Detailed Description
Helper to remember if the module contains OpenMP (runtime calls), to be used foremost with containsOpenMP.
Definition at line 25 of file OpenMPOpt.h.
Member Function Documentation
containsOMPRuntimeCalls()
bool llvm::omp::OpenMPInModule::containsOMPRuntimeCalls (Function * F) const inline
Does this function F contain any OpenMP runtime calls?
Definition at line 37 of file OpenMPOpt.h.
References F.
getKernels()
SmallPtrSetImpl< Kernel > & llvm::omp::OpenMPInModule::getKernels () inline
Return the known kernels (=GPU entry points) in the module.
Definition at line 42 of file OpenMPOpt.h.
identifyKernels()
void OpenMPInModule::identifyKernels (Module & M)
Identify kernels in the module and populate the Kernels set.
Definition at line 2395 of file OpenMPOpt.cpp.
References llvm::MDString::getString(), and llvm::NamedMDNode::operands().
Referenced by llvm::omp::containsOpenMP().
isKnown()
bool llvm::omp::OpenMPInModule::isKnown () inline
Definition at line 33 of file OpenMPOpt.h.
Referenced by llvm::omp::containsOpenMP().
operator bool()
llvm::omp::OpenMPInModule::operator bool () inline
Definition at line 34 of file OpenMPOpt.h.
operator=()
OpenMPInModule & llvm::omp::OpenMPInModule::operator= (bool Found) inline
Definition at line 26 of file OpenMPOpt.h.
Friends And Related Symbol Documentation
containsOpenMP
bool containsOpenMP (Module & M, OpenMPInModule & OMPInModule) friend
Helper to determine if M contains OpenMP (runtime calls).
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/OpenMPOpt.h
lib/Transforms/IPO/OpenMPOpt.cpp