LLVM: llvm::AANoCapture Struct Reference
llvm::AANoCapture Struct Reference
An abstract interface for all nocapture attributes.
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
enum {
NOT_CAPTURED_IN_MEM = 1 << 0 , NOT_CAPTURED_IN_INT = 1 << 1 , NOT_CAPTURED_IN_RET = 1 << 2 , NO_CAPTURE_MAYBE_RETURNED = NOT_CAPTURED_IN_MEM | NOT_CAPTURED_IN_INT ,
NO_CAPTURE
}
State encoding bits.
Public Types inherited from llvm::StateWrapper< BitIntegerState< uint16_t, 7, 0 >, AbstractAttribute >
using StateType
Provide static access to the type of the state.
Public Types inherited from llvm::AbstractAttribute
using StateType = AbstractState
Public Types inherited from llvm::IRPosition
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
Public Types inherited from llvm::AADepGraphNode
using DepTy = PointerIntPair<AADepGraphNode *, 1>
using iterator
using aaiterator
Public Types inherited from llvm::BitIntegerState< uint16_t, 7, 0 >
using base_t
Public Types inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
using base_t = base_ty
Public Member Functions
AANoCapture (const IRPosition &IRP, Attributor &A)
bool isKnownNoCapture () const
Return true if we know that the underlying value is not captured in its respective scope.
bool isAssumedNoCapture () const
Return true if we assume that the underlying value is not captured in its respective scope.
bool isKnownNoCaptureMaybeReturned () const
Return true if we know that the underlying value is not captured in its respective scope but we allow it to escape through a "return".
bool isAssumedNoCaptureMaybeReturned () const
Return true if we assume that the underlying value is not captured in its respective scope but we allow it to escape through a "return".
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::IRAttribute< Attribute::NoCapture, StateWrapper< BitIntegerState< uint16_t, 7, 0 >, AbstractAttribute > >
IRAttribute (const IRPosition &IRP)
virtual void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
Attribute::AttrKind getAttrKind () const
Return the kind that identifies the abstract attribute implementation.
virtual void getDeducedAttributes (LLVMContext &Ctx, SmallVectorImpl< Attribute > &Attrs) const
Return the deduced attributes in Attrs.
Public Member Functions inherited from llvm::StateWrapper< BitIntegerState< uint16_t, 7, 0 >, AbstractAttribute >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (const IRPosition &IRP)
virtual ~AbstractAttribute ()
Virtual destructor.
const IRPosition & getIRPosition () const
Return an IR position, see struct IRPosition.
IRPosition & getIRPosition ()
void print (raw_ostream &OS) const override
Helper functions, for debug purposes only.
virtual void printWithDeps (raw_ostream &OS) const
void dump () const
virtual const std::string getAsStr () const =0
This function should return the "summarized" assumed state as string.
Public Member Functions inherited from llvm::IRPosition
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getCalleeArgNo () const
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
int getCallSiteArgNo () const
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Kind getPositionKind () const
Return the associated position kind.
bool hasAttr (ArrayRef< Attribute::AttrKind > AKs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
TODO: Figure out if the attribute related helper functions should live here or somewhere else.
void getAttrs (ArrayRef< Attribute::AttrKind > AKs, SmallVectorImpl< Attribute > &Attrs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
Return the attributes of any kind in AKs existing in the IR at a position that will affect this one.
void removeAttrs (ArrayRef< Attribute::AttrKind > AKs) const
Remove the attribute of kind AKs existing in the IR at this position.
bool isAnyCallSitePosition () const
bool isArgumentPosition () const
Return true if the position is an argument or call site argument.
operator void * () const
}
Public Member Functions inherited from llvm::AADepGraphNode
virtual ~AADepGraphNode ()
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
TinyPtrVector< DepTy > & getDeps ()
Public Member Functions inherited from llvm::BitIntegerState< uint16_t, 7, 0 >
bool isKnown (base_t BitsEncoding) const
Return true if the bits set in BitsEncoding are "known bits".
bool isAssumed (base_t BitsEncoding) const
Return true if the bits set in BitsEncoding are "assumed bits".
BitIntegerState & addKnownBits (base_t Bits)
Add the bits in BitsEncoding to the "known bits".
BitIntegerState & removeAssumedBits (base_t BitsEncoding)
Remove the bits in BitsEncoding from the "assumed bits" if not known.
BitIntegerState & removeKnownBits (base_t BitsEncoding)
Remove the bits in BitsEncoding from the "known bits".
BitIntegerState & intersectAssumedBits (base_t BitsEncoding)
Keep only "assumed bits" also set in BitsEncoding but all known ones.
Public Member Functions inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
IntegerStateBase ()
IntegerStateBase (base_t Assumed)
bool isValidState () const override
See AbstractState::isValidState() NOTE: For now we simply pretend that the worst possible state is invalid.
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint()
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
base_t getKnown () const
Return the known state encoding.
base_t getAssumed () const
Return the assumed state encoding.
bool operator== (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Equality for IntegerStateBase.
bool operator!= (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Inequality for IntegerStateBase.
void operator^= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator+= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator|= (const IntegerStateBase< base_t, BestState, WorstState > &R)
void operator&= (const IntegerStateBase< base_t, BestState, WorstState > &R)
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()
Static Public Member Functions
static AANoCapture & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AANoCapture.
Static Public Member Functions inherited from llvm::AbstractAttribute
static bool classof (const AADepGraphNode *DGN)
This function is used to identify if an DGN is of type AbstractAttribute so that the dyn_cast and cast can use such information to cast an AADepGraphNode to an AbstractAttribute.
Static Public Member Functions inherited from llvm::IRPosition
static const IRPosition value (const Value &V)
Create a position describing the value of V.
static const IRPosition function (const Function &F)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP)
Create a position with function scope matching the "context" of IRP.
Static Public Member Functions inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
static constexpr base_t getBestState ()
Return the best possible representable state.
static constexpr base_t getBestState (const IntegerStateBase &)
static constexpr base_t getWorstState ()
Return the worst possible representable state.
static constexpr base_t getWorstState (const IntegerStateBase &)
Static Public Attributes
static const char ID = 0
Unique ID (due to the unique address)
Static Public Attributes inherited from llvm::IRPosition
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Additional Inherited Members
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
virtual void trackStatistics () const =0
Hook to enable custom statistic tracking, called after manifest that resulted in a change if statistics are enabled.
virtual ChangeStatus updateImpl (Attributor &A)=0
The actual update/transfer function which has to be implemented by the derived classes.
Protected Member Functions inherited from llvm::AADepGraphNode
operator AbstractAttribute * ()
Protected Member Functions inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
virtual void handleNewAssumedValue (base_t Value)=0
Handle a new assumed value Value. Subtype dependent.
virtual void handleNewKnownValue (base_t Value)=0
Handle a new known value Value. Subtype dependent.
virtual void joinOR (base_t AssumedValue, base_t KnownValue)=0
Handle a value Value. Subtype dependent.
virtual void joinAND (base_t AssumedValue, base_t KnownValue)=0
Handle a new assumed value Value. Subtype dependent.
Static Protected Member Functions inherited from llvm::AADepGraphNode
static AADepGraphNode * DepGetVal (DepTy &DT)
static AbstractAttribute * DepGetValAA (DepTy &DT)
Protected Attributes inherited from llvm::AADepGraphNode
TinyPtrVector< DepTy > Deps
Set of dependency graph nodes which should be updated if this one is updated.
Protected Attributes inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
base_t Known = getWorstState()
The known state encoding in an integer of type base_t.
base_t Assumed = getBestState()
The assumed state encoding in an integer of type base_t.
Detailed Description
An abstract interface for all nocapture attributes.
Definition at line 3060 of file Attributor.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
State encoding bits.
A set bit in the state means the property holds. NO_CAPTURE is the best possible state, 0 the worst possible state.
Enumerator
NOT_CAPTURED_IN_MEM
NOT_CAPTURED_IN_INT
NOT_CAPTURED_IN_RET
NO_CAPTURE_MAYBE_RETURNED
If we do not capture the value in memory or through integers we can only communicate it back as a derived pointer.
NO_CAPTURE
If we do not capture the value in memory, through integers, or as a derived pointer we know it is not captured.
Definition at line 3068 of file Attributor.h.
Constructor & Destructor Documentation
AANoCapture()
llvm::AANoCapture::AANoCapture (const IRPosition & IRP, Attributor & A) inline
Definition at line 3064 of file Attributor.h.
Member Function Documentation
classof()
static bool llvm::AANoCapture::classof (const AbstractAttribute * AA) inline static
This function should return true if the type of the AA is AANoCapture.
Definition at line 3113 of file Attributor.h.
References llvm::AbstractAttribute::getIdAddr(), and ID.
createForPosition()
static AANoCapture & llvm::AANoCapture::createForPosition (const IRPosition & IRP, Attributor & A) static
Create an abstract attribute view for the position IRP.
getIdAddr()
const char * llvm::AANoCapture::getIdAddr () const inline override virtual
See AbstractAttribute::getIdAddr()
Implements llvm::AbstractAttribute.
Definition at line 3110 of file Attributor.h.
References ID.
getName()
const std::string llvm::AANoCapture::getName () const inline override virtual
See AbstractAttribute::getName()
Implements llvm::AbstractAttribute.
Definition at line 3107 of file Attributor.h.
isAssumedNoCapture()
bool llvm::AANoCapture::isAssumedNoCapture () const inline
Return true if we assume that the underlying value is not captured in its respective scope.
Definition at line 3089 of file Attributor.h.
References llvm::BitIntegerState< uint16_t, 7, 0 >::isAssumed(), and NO_CAPTURE.
isAssumedNoCaptureMaybeReturned()
bool llvm::AANoCapture::isAssumedNoCaptureMaybeReturned () const inline
Return true if we assume that the underlying value is not captured in its respective scope but we allow it to escape through a "return".
Definition at line 3099 of file Attributor.h.
References llvm::BitIntegerState< uint16_t, 7, 0 >::isAssumed(), and NO_CAPTURE_MAYBE_RETURNED.
isKnownNoCapture()
bool llvm::AANoCapture::isKnownNoCapture () const inline
Return true if we know that the underlying value is not captured in its respective scope.
Definition at line 3085 of file Attributor.h.
References llvm::BitIntegerState< uint16_t, 7, 0 >::isKnown(), and NO_CAPTURE.
isKnownNoCaptureMaybeReturned()
bool llvm::AANoCapture::isKnownNoCaptureMaybeReturned () const inline
Return true if we know that the underlying value is not captured in its respective scope but we allow it to escape through a "return".
Definition at line 3093 of file Attributor.h.
References llvm::BitIntegerState< uint16_t, 7, 0 >::isKnown(), and NO_CAPTURE_MAYBE_RETURNED.
Member Data Documentation
ID
const char AANoCapture::ID = 0 static
Unique ID (due to the unique address)
Definition at line 3118 of file Attributor.h.
Referenced by classof(), and getIdAddr().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/AttributorAttributes.cpp