LLVM: lib/CodeGen/TargetLoweringBase.cpp File Reference
TargetLoweringBase.cpp File Reference
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RuntimeLibcalls.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/Utils/SizeOpts.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <iterator>
#include <string>
#include <tuple>
#include <utility>
#include "llvm/IR/RuntimeLibcalls.def"
#include "llvm/IR/ConstrainedOps.def"
#include "llvm/IR/Instruction.def"
Macros
#define HANDLE_LIBCALL(code, name) setLibcallName(RTLIB::code, name);
#define LCALLS(A, B) { A##B##_RELAX, A##B##_ACQ, A##B##_REL, A##B##_ACQ_REL }
#define LCALL5(A) LCALLS(A, 1), LCALLS(A, 2), LCALLS(A, 4), LCALLS(A, 8), LCALLS(A, 16)
#define OP_TO_LIBCALL(Name, Enum)
#define DAG_INSTRUCTION(NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) setOperationAction(ISD::STRICT_##DAGN, VT, Expand);
#define HANDLE_INST(NUM, OPCODE, CLASS) OPCODE = NUM,
#define LAST_OTHER_INST(NUM) InstructionOpcodesCount = NUM
Functions
static bool darwinHasSinCos (const Triple &TT)
static void InitCmpLibcallCCs (ISD::CondCode *CCs)
InitCmpLibcallCCs - Set default comparison libcall CC.
static unsigned getVectorTypeBreakdownMVT (MVT VT, MVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT, TargetLoweringBase *TLI)
static StringRef getRecipEstimateForFunc (MachineFunction &MF)
Get the reciprocal estimate attribute string for a function that will override the target defaults.
static std::string getReciprocalOpName (bool IsSqrt, EVT VT)
Construct a string for the given reciprocal operation of the given type.
static bool parseRefinementStep (StringRef In, size_t &Position, uint8_t &Value)
Return the character position and value (a single numeric character) of a customized refinement operation in the input string if it exists.
static int getOpEnabled (bool IsSqrt, EVT VT, StringRef Override)
For the input attribute string, return one of the ReciprocalEstimate enum status values (enabled, disabled, or not specified) for this operation on the specified data type.
static int getOpRefinementSteps (bool IsSqrt, EVT VT, StringRef Override)
For the input attribute string, return the customized refinement step count for this operation on the specified data type.
Variables
static cl::opt< bool > JumpIsExpensiveOverride ("jump-is-expensive", cl::init(false), cl::desc("Do not create extra branches to split comparison logic."), cl::Hidden)
static cl::opt< unsigned > MinimumJumpTableEntries ("min-jump-table-entries", cl::init(4), cl::Hidden, cl::desc("Set minimum number of entries to use a jump table."))
static cl::opt< unsigned > MaximumJumpTableSize ("max-jump-table-size", cl::init(UINT_MAX), cl::Hidden, cl::desc("Set maximum size of jump tables."))
static cl::opt< unsigned > JumpTableDensity ("jump-table-density", cl::init(10), cl::Hidden, cl::desc("Minimum density for building a jump table in " "a normal function"))
Minimum jump table density for normal functions.
static cl::opt< unsigned > OptsizeJumpTableDensity ("optsize-jump-table-density", cl::init(40), cl::Hidden, cl::desc("Minimum density for building a jump table in " "an optsize function"))
Minimum jump table density for -Os or -Oz functions.
static cl::opt< bool > DisableStrictNodeMutation ("disable-strictnode-mutation", cl::desc("Don't mutate strict-float node to a legalize node"), cl::init(false), cl::Hidden)
static cl::opt< int > MinPercentageForPredictableBranch ("min-predictable-branch", cl::init(99), cl::desc("Minimum percentage (0-100) that a condition must be either true " "or false to assume that the condition is predictable"), cl::Hidden)
Macro Definition Documentation
DAG_INSTRUCTION
#define DAG_INSTRUCTION (NAME, NARG, ROUND_MODE, INTRINSIC, DAGN) setOperationAction(ISD::STRICT_##DAGN, VT, Expand);
HANDLE_INST
#define HANDLE_INST (NUM, OPCODE, CLASS) OPCODE = NUM,
HANDLE_LIBCALL
#define HANDLE_LIBCALL (code, name) setLibcallName(RTLIB::code, name);
LAST_OTHER_INST
#define LAST_OTHER_INST (NUM) InstructionOpcodesCount = NUM
LCALL5
#define LCALL5 (A) LCALLS(A, 1), LCALLS(A, 2), LCALLS(A, 4), LCALLS(A, 8), LCALLS(A, 16)
LCALLS
#define LCALLS (A, B) { A##B##_RELAX, A##B##_ACQ, A##B##_REL, A##B##_ACQ_REL }
OP_TO_LIBCALL
#define OP_TO_LIBCALL (Name, Enum)
Value:
  case Name:                                                                   \
    switch (VT.SimpleTy) {                                                     \
    default:                                                                   \
      return UNKNOWN_LIBCALL;                                                  \
    case MVT::i8:                                                              \
      return Enum##_1;                                                         \
    case MVT::i16:                                                             \
      return Enum##_2;                                                         \
    case MVT::i32:                                                             \
      return Enum##_4;                                                         \
    case MVT::i64:                                                             \
      return Enum##_8;                                                         \
    case MVT::i128:                                                            \
      return Enum##_16;                                                        \
    }
Function Documentation
darwinHasSinCos()
static bool darwinHasSinCos (const Triple & TT) static
Definition at line 102 of file TargetLoweringBase.cpp.
References assert(), and llvm::Triple::x86.
getOpEnabled()
static int getOpEnabled (bool IsSqrt, EVT VT, StringRef Override) static
For the input attribute string, return one of the ReciprocalEstimate enum status values (enabled, disabled, or not specified) for this operation on the specified data type.
Definition at line 2061 of file TargetLoweringBase.cpp.
References llvm::TargetLoweringBase::Disabled, llvm::StringRef::empty(), llvm::TargetLoweringBase::Enabled, getReciprocalOpName(), parseRefinementStep(), llvm::StringRef::split(), llvm::StringRef::substr(), and llvm::TargetLoweringBase::Unspecified.
Referenced by llvm::TargetLoweringBase::getRecipEstimateDivEnabled(), and llvm::TargetLoweringBase::getRecipEstimateSqrtEnabled().
getOpRefinementSteps()
static int getOpRefinementSteps (bool IsSqrt, EVT VT, StringRef Override) static
For the input attribute string, return the customized refinement step count for this operation on the specified data type.
If the step count does not exist, return the ReciprocalEstimate enum value for unspecified.
Definition at line 2121 of file TargetLoweringBase.cpp.
References assert(), llvm::StringRef::empty(), getReciprocalOpName(), parseRefinementStep(), llvm::StringRef::split(), llvm::StringRef::substr(), and llvm::TargetLoweringBase::Unspecified.
Referenced by llvm::TargetLoweringBase::getDivRefinementSteps(), and llvm::TargetLoweringBase::getSqrtRefinementSteps().
getRecipEstimateForFunc()
static StringRef getRecipEstimateForFunc (MachineFunction & MF) static
Get the reciprocal estimate attribute string for a function that will override the target defaults.
Definition at line 2009 of file TargetLoweringBase.cpp.
References F, llvm::Function::getFnAttribute(), llvm::MachineFunction::getFunction(), and llvm::Attribute::getValueAsString().
Referenced by llvm::TargetLoweringBase::getDivRefinementSteps(), llvm::TargetLoweringBase::getRecipEstimateDivEnabled(), llvm::TargetLoweringBase::getRecipEstimateSqrtEnabled(), and llvm::TargetLoweringBase::getSqrtRefinementSteps().
getReciprocalOpName()
static std::string getReciprocalOpName (bool IsSqrt, EVT VT) static
Construct a string for the given reciprocal operation of the given type.
This string should match the corresponding option to the front-end's "-mrecip" flag assuming those strings have been passed through in an attribute string. For example, "vec-divf" for a division of a vXf32.
Definition at line 2018 of file TargetLoweringBase.cpp.
References assert(), llvm::MVT::f32, llvm::MVT::f64, llvm::EVT::getScalarType(), llvm::EVT::isVector(), and Name.
Referenced by getOpEnabled(), and getOpRefinementSteps().
getVectorTypeBreakdownMVT()
static unsigned getVectorTypeBreakdownMVT (MVT VT, MVT & IntermediateVT, unsigned & NumIntermediates, MVT & RegisterVT, TargetLoweringBase * TLI) static
Definition at line 1075 of file TargetLoweringBase.cpp.
References llvm::LinearPolySize< ElementCount >::getFixed(), llvm::TargetLoweringBase::getRegisterType(), llvm::MVT::getVectorElementCount(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorVT(), llvm::isPowerOf2_32(), llvm::MVT::isScalableVector(), llvm::TargetLoweringBase::isTypeLegal(), llvm_unreachable, and llvm::NextPowerOf2().
Referenced by llvm::TargetLoweringBase::computeRegisterProperties().
InitCmpLibcallCCs()
static void InitCmpLibcallCCs (ISD::CondCode * CCs) static
InitCmpLibcallCCs - Set default comparison libcall CC.
Definition at line 651 of file TargetLoweringBase.cpp.
References llvm::ISD::SETCC_INVALID, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, and llvm::ISD::SETNE.
Referenced by llvm::TargetLoweringBase::TargetLoweringBase().
parseRefinementStep()
static bool parseRefinementStep (StringRef In, size_t & Position, uint8_t & Value) static
Return the character position and value (a single numeric character) of a customized refinement operation in the input string if it exists.
Return false if there is no customized refinement step count.
Definition at line 2038 of file TargetLoweringBase.cpp.
References llvm::StringRef::npos, and llvm::report_fatal_error().
Referenced by getOpEnabled(), and getOpRefinementSteps().
Variable Documentation
DisableStrictNodeMutation
cl::opt< bool > DisableStrictNodeMutation("disable-strictnode-mutation", cl::desc("Don't mutate strict-float node to a legalize node"), cl::init(false), cl::Hidden) ("disable-strictnode-mutation" , cl::desc("Don't mutate strict-float node to a legalize node") , cl::init(false) , cl::Hidden) static
Referenced by llvm::TargetLoweringBase::TargetLoweringBase().
JumpIsExpensiveOverride
cl::opt< bool > JumpIsExpensiveOverride("jump-is-expensive", cl::init(false), cl::desc("Do not create extra branches to split comparison logic."), cl::Hidden) ("jump-is-expensive" , cl::init(false) , cl::desc("Do not create extra branches to split comparison logic.") , cl::Hidden) static
Referenced by llvm::TargetLoweringBase::setJumpIsExpensive(), and llvm::TargetLoweringBase::TargetLoweringBase().
JumpTableDensity
cl::opt< unsigned > JumpTableDensity("jump-table-density", cl::init(10), cl::Hidden, cl::desc("Minimum density for building a jump table in " "a normal function")) ("jump-table-density" , cl::init(10) , cl::Hidden , cl::desc("Minimum density for building a jump table in " "a normal function")) static
Minimum jump table density for normal functions.
Referenced by llvm::TargetLoweringBase::getMinimumJumpTableDensity().
MaximumJumpTableSize
cl::opt< unsigned > MaximumJumpTableSize("max-jump-table-size", cl::init(UINT_MAX), cl::Hidden, cl::desc("Set maximum size of jump tables.")) ("max-jump-table-size" , cl::init(UINT_MAX) , cl::Hidden , cl::desc("Set maximum size of jump tables.")) static
Referenced by llvm::TargetLoweringBase::getMaximumJumpTableSize(), and llvm::TargetLoweringBase::setMaximumJumpTableSize().
MinimumJumpTableEntries
cl::opt< unsigned > MinimumJumpTableEntries("min-jump-table-entries", cl::init(4), cl::Hidden, cl::desc("Set minimum number of entries to use a jump table.")) ("min-jump-table-entries" , cl::init(4) , cl::Hidden , cl::desc("Set minimum number of entries to use a jump table.")) static
Referenced by llvm::TargetLoweringBase::getMinimumJumpTableEntries(), and llvm::TargetLoweringBase::setMinimumJumpTableEntries().
MinPercentageForPredictableBranch
cl::opt< int > MinPercentageForPredictableBranch("min-predictable-branch", cl::init(99), cl::desc("Minimum percentage (0-100) that a condition must be either true " "or false to assume that the condition is predictable"), cl::Hidden) ("min-predictable-branch" , cl::init(99) , cl::desc("Minimum percentage (0-100) that a condition must be either true " "or false to assume that the condition is predictable") , cl::Hidden) static
Referenced by llvm::TargetLoweringBase::getPredictableBranchThreshold().
OptsizeJumpTableDensity
cl::opt< unsigned > OptsizeJumpTableDensity("optsize-jump-table-density", cl::init(40), cl::Hidden, cl::desc("Minimum density for building a jump table in " "an optsize function")) ("optsize-jump-table-density" , cl::init(40) , cl::Hidden , cl::desc("Minimum density for building a jump table in " "an optsize function")) static
Minimum jump table density for -Os or -Oz functions.
Referenced by llvm::TargetLoweringBase::getMinimumJumpTableDensity().