LLVM: lib/Target/AArch64/AArch64MachineFunctionInfo.cpp File Reference
AArch64MachineFunctionInfo.cpp File Reference
This file implements AArch64-specific per-machine-function information.
#include "AArch64MachineFunctionInfo.h"
#include "AArch64InstrInfo.h"
#include "AArch64Subtarget.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
Functions
static std::pair< bool, bool > GetSignReturnAddress (const Function &F)
static bool ShouldSignWithBKey (const Function &F, const AArch64Subtarget &STI)
Detailed Description
This file implements AArch64-specific per-machine-function information.
Definition in file AArch64MachineFunctionInfo.cpp.
Function Documentation
GetSignReturnAddress()
static std::pair< bool, bool > GetSignReturnAddress (const Function & F) static
Definition at line 40 of file AArch64MachineFunctionInfo.cpp.
References llvm::All, assert(), and F.
Referenced by llvm::AArch64FunctionInfo::AArch64FunctionInfo(), and llvm::ARMFunctionInfo::ARMFunctionInfo().
ShouldSignWithBKey()
static bool ShouldSignWithBKey (const Function & F, const AArch64Subtarget & STI) static
Definition at line 69 of file AArch64MachineFunctionInfo.cpp.
References assert(), F, llvm::AArch64Subtarget::getTargetTriple(), and llvm::Triple::isOSWindows().
Referenced by llvm::AArch64FunctionInfo::AArch64FunctionInfo().