LLVM: lib/CodeGen/AggressiveAntiDepBreaker.cpp File Reference
AggressiveAntiDepBreaker.cpp File Reference
#include "AggressiveAntiDepBreaker.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterClassInfo.h"
#include "llvm/CodeGen/ScheduleDAG.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <utility>
Macros
#define DEBUG_TYPE "post-RA-sched"
Functions
static void AntiDepEdges (const SUnit *SU, std::vector< const SDep * > &Edges)
AntiDepEdges - Return in Edges the anti- and output- dependencies in SU that we want to consider for breaking.
static const SUnit * CriticalPathStep (const SUnit *SU)
CriticalPathStep - Return the next SUnit after SU on the bottom-up critical path.
Variables
static cl::opt< int > DebugDiv ("agg-antidep-debugdiv", cl::desc("Debug control for aggressive anti-dep breaker"), cl::init(0), cl::Hidden)
static cl::opt< int > DebugMod ("agg-antidep-debugmod", cl::desc("Debug control for aggressive anti-dep breaker"), cl::init(0), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "post-RA-sched"
Definition at line 41 of file AggressiveAntiDepBreaker.cpp.
Function Documentation
AntiDepEdges()
static void AntiDepEdges (const SUnit * SU, std::vector< const SDep * > & Edges) static
AntiDepEdges - Return in Edges the anti- and output- dependencies in SU that we want to consider for breaking.
Definition at line 258 of file AggressiveAntiDepBreaker.cpp.
References llvm::SDep::Anti, llvm::SDep::Output, and llvm::SUnit::Preds.
Referenced by llvm::AggressiveAntiDepBreaker::BreakAntiDependencies().
CriticalPathStep()
static const SUnit * CriticalPathStep (const SUnit * SU) static
CriticalPathStep - Return the next SUnit after SU on the bottom-up critical path.
Definition at line 270 of file AggressiveAntiDepBreaker.cpp.
References llvm::SDep::Anti, llvm::SDep::getSUnit(), and llvm::SUnit::Preds.
Referenced by llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), and llvm::CriticalAntiDepBreaker::BreakAntiDependencies().
Variable Documentation
DebugDiv
cl::opt< int > DebugDiv("agg-antidep-debugdiv", cl::desc("Debug control for aggressive anti-dep breaker"), cl::init(0), cl::Hidden) ("agg-antidep-debugdiv" , cl::desc("Debug control for aggressive anti-dep breaker") , cl::init(0) , cl::Hidden) static
DebugMod
cl::opt< int > DebugMod("agg-antidep-debugmod", cl::desc("Debug control for aggressive anti-dep breaker"), cl::init(0), cl::Hidden) ("agg-antidep-debugmod" , cl::desc("Debug control for aggressive anti-dep breaker") , cl::init(0) , cl::Hidden) static