LLVM: lib/Target/ARM/ARMHazardRecognizer.cpp File Reference
ARMHazardRecognizer.cpp File Reference
#include "ARMHazardRecognizer.h"
#include "ARMBaseInstrInfo.h"
#include "ARMBaseRegisterInfo.h"
#include "ARMSubtarget.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/ScheduleDAG.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
Functions
static bool hasRAWHazard (MachineInstr *DefMI, MachineInstr *MI, const TargetRegisterInfo &TRI)
static bool getBaseOffset (const MachineInstr &MI, const MachineOperand *&BaseOp, int64_t &Offset)
Variables
static cl::opt< int > DataBankMask ("arm-data-bank-mask", cl::init(-1), cl::Hidden)
static cl::opt< bool > AssumeITCMConflict ("arm-assume-itcm-bankconflict", cl::init(false), cl::Hidden)
Function Documentation
getBaseOffset()
static bool getBaseOffset (const MachineInstr & MI, const MachineOperand *& BaseOp, int64_t & Offset) static
Definition at line 109 of file ARMHazardRecognizer.cpp.
References llvm::ARMII::AddrModeMask, llvm::ARMII::AddrModeT1_1, llvm::ARMII::AddrModeT1_2, llvm::ARMII::AddrModeT1_4, llvm::ARMII::AddrModeT2_i12, llvm::ARMII::AddrModeT2_i8, llvm::ARMII::AddrModeT2_i8s4, llvm::ARMII::IndexModeMask, llvm::ARMII::IndexModePost, llvm::ARMII::IndexModePre, llvm::ARMII::IndexModeShift, llvm::ARMII::IndexModeUpd, MI, llvm::Offset, and TSFlags.
Referenced by llvm::ARMBankConflictHazardRecognizer::getHazardType().
hasRAWHazard()
static bool hasRAWHazard (MachineInstr * DefMI, MachineInstr * MI, const TargetRegisterInfo & TRI) static
Definition at line 28 of file ARMHazardRecognizer.cpp.
References DefMI, llvm::ARMII::DomainMask, llvm::ARMII::DomainNEON, llvm::ARMII::DomainVFP, llvm::MCInstrDesc::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), MI, TRI, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::ARMHazardRecognizerFPMLx::getHazardType().
Variable Documentation
AssumeITCMConflict
cl::opt< bool > AssumeITCMConflict("arm-assume-itcm-bankconflict", cl::init(false), cl::Hidden) ("arm-assume-itcm-bankconflict" , cl::init(false) , cl::Hidden) static
DataBankMask
cl::opt< int > DataBankMask("arm-data-bank-mask", cl::init(-1), cl::Hidden) ("arm-data-bank-mask" , cl::init(-1) , cl::Hidden) static