LLVM: lib/Target/AVR/AsmParser/AVRAsmParser.cpp File Reference
AVRAsmParser.cpp File Reference
#include "AVR.h"
#include "AVRRegisterInfo.h"
#include "MCTargetDesc/AVRMCELFStreamer.h"
#include "MCTargetDesc/AVRMCExpr.h"
#include "MCTargetDesc/AVRMCTargetDesc.h"
#include "TargetInfo/AVRTargetInfo.h"
#include "llvm/ADT/APInt.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include <array>
#include <sstream>
#include "AVRGenAsmMatcher.inc"
Macros
#define DEBUG_TYPE "avr-asm-parser"
#define GET_ASSEMBLER_HEADER
#define GET_REGISTER_MATCHER
#define GET_MATCHER_IMPLEMENTATION
Functions
static unsigned MatchRegisterName (StringRef Name)
Maps from the set of all register names to a register number.
static unsigned MatchRegisterAltName (StringRef Name)
Maps from the set of all alternative registernames to a register number.
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAVRAsmParser ()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "avr-asm-parser"
Definition at line 35 of file AVRAsmParser.cpp.
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 51 of file AVRAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 736 of file AVRAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 735 of file AVRAsmParser.cpp.
Function Documentation
LLVMInitializeAVRAsmParser()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAVRAsmParser ()
Definition at line 731 of file AVRAsmParser.cpp.
References llvm::getTheAVRTarget(), and X.
MatchRegisterAltName()
static unsigned MatchRegisterAltName (StringRef Name) static
Maps from the set of all alternative registernames to a register number.
Note
Referenced by llvm::LoongArchTargetLowering::getRegisterByName(), llvm::RISCVTargetLowering::getRegisterByName(), matchRegisterNameHelper(), matchRegisterNameHelper(), and matchRegisterNameHelper().
MatchRegisterName()
static unsigned MatchRegisterName (StringRef Name) static
Maps from the set of all register names to a register number.
Note