LLVM: llvm::logicalview::LVReaderHandler Class Reference
llvm::logicalview::LVReaderHandler Class Reference
#include "llvm/DebugInfo/LogicalView/LVReaderHandler.h"
Public Member Functions
LVReaderHandler ()=delete
LVReaderHandler (ArgVector &Objects, ScopedPrinter &W, LVOptions &ReaderOptions)
LVReaderHandler (const LVReaderHandler &)=delete
LVReaderHandler & operator= (const LVReaderHandler &)=delete
~LVReaderHandler ()
Error createReader (StringRef Filename, LVReaders &Readers)
Error process ()
Expected< LVReader * > createReader (StringRef Pathname)
void deleteReader (LVReader *Reader)
void print (raw_ostream &OS) const
void dump () const
Detailed Description
Definition at line 41 of file LVReaderHandler.h.
Constructor & Destructor Documentation
LVReaderHandler() [1/3]
llvm::logicalview::LVReaderHandler::LVReaderHandler () delete
LVReaderHandler() [2/3]
llvm::logicalview::LVReaderHandler::LVReaderHandler (ArgVector & Objects, ScopedPrinter & W, LVOptions & ReaderOptions) inline
Definition at line 68 of file LVReaderHandler.h.
References llvm::logicalview::setOptions().
LVReaderHandler() [3/3]
llvm::logicalview::LVReaderHandler::LVReaderHandler (const LVReaderHandler &) delete
~LVReaderHandler()
llvm::logicalview::LVReaderHandler::~LVReaderHandler () inline
Definition at line 75 of file LVReaderHandler.h.
Member Function Documentation
createReader() [1/2]
Error llvm::logicalview::LVReaderHandler::createReader (StringRef Filename, LVReaders & Readers) inline
Definition at line 77 of file LVReaderHandler.h.
References llvm::logicalview::Filename.
createReader() [2/2]
Expected< LVReader * > llvm::logicalview::LVReaderHandler::createReader (StringRef Pathname) inline
Definition at line 82 of file LVReaderHandler.h.
References llvm::logicalview::Pathname.
deleteReader()
void llvm::logicalview::LVReaderHandler::deleteReader (LVReader * Reader) inline
Definition at line 88 of file LVReaderHandler.h.
dump()
void llvm::logicalview::LVReaderHandler::dump () const inline
Definition at line 93 of file LVReaderHandler.h.
References llvm::dbgs(), and print().
operator=()
LVReaderHandler & llvm::logicalview::LVReaderHandler::operator= (const LVReaderHandler &) delete
print()
void LVReaderHandler::print (raw_ostream & OS) const
Definition at line 194 of file LVReaderHandler.cpp.
Referenced by dump().
process()
Error LVReaderHandler::process ()
Definition at line 24 of file LVReaderHandler.cpp.
References llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/LVReaderHandler.h
lib/DebugInfo/LogicalView/LVReaderHandler.cpp