LLVM: llvm::object::ImportDirectoryEntryRef Class Reference
llvm::object::ImportDirectoryEntryRef Class Reference
#include "llvm/Object/COFF.h"
Public Member Functions
ImportDirectoryEntryRef ()=default
ImportDirectoryEntryRef (const coff_import_directory_table_entry *Table, uint32_t I, const COFFObjectFile *Owner)
bool operator== (const ImportDirectoryEntryRef &Other) const
void moveNext ()
imported_symbol_iterator imported_symbol_begin () const
imported_symbol_iterator imported_symbol_end () const
iterator_range< imported_symbol_iterator > imported_symbols () const
imported_symbol_iterator lookup_table_begin () const
imported_symbol_iterator lookup_table_end () const
iterator_range< imported_symbol_iterator > lookup_table_symbols () const
Error getName (StringRef &Result) const
Error getImportLookupTableRVA (uint32_t &Result) const
Error getImportAddressTableRVA (uint32_t &Result) const
Error getImportTableEntry (const coff_import_directory_table_entry *&Result) const
Detailed Description
Definition at line 1111 of file COFF.h.
Constructor & Destructor Documentation
ImportDirectoryEntryRef() [1/2]
llvm::object::ImportDirectoryEntryRef::ImportDirectoryEntryRef () default
ImportDirectoryEntryRef() [2/2]
llvm::object::ImportDirectoryEntryRef::ImportDirectoryEntryRef (const coff_import_directory_table_entry * Table, uint32_t I, const COFFObjectFile * Owner) inline
Definition at line 1114 of file COFF.h.
Member Function Documentation
getImportAddressTableRVA()
Error ImportDirectoryEntryRef::getImportAddressTableRVA (uint32_t & Result) const
Definition at line 1488 of file COFFObjectFile.cpp.
References llvm::object::coff_import_directory_table_entry::ImportAddressTableRVA, and llvm::Error::success().
getImportLookupTableRVA()
Error ImportDirectoryEntryRef::getImportLookupTableRVA (uint32_t & Result) const
Definition at line 1483 of file COFFObjectFile.cpp.
References llvm::object::coff_import_directory_table_entry::ImportLookupTableRVA, and llvm::Error::success().
getImportTableEntry()
Error ImportDirectoryEntryRef::getImportTableEntry (const coff_import_directory_table_entry *& Result) const
Definition at line 1398 of file COFFObjectFile.cpp.
References llvm::object::Binary::Data, and llvm::object::getObject().
getName()
Error ImportDirectoryEntryRef::getName (StringRef & Result) const
Definition at line 1473 of file COFFObjectFile.cpp.
References E, llvm::object::COFFObjectFile::getRvaPtr(), llvm::object::coff_import_directory_table_entry::NameRVA, and llvm::Error::success().
imported_symbol_begin()
imported_symbol_iterator ImportDirectoryEntryRef::imported_symbol_begin () const
Definition at line 1442 of file COFFObjectFile.cpp.
References importedSymbolBegin().
Referenced by imported_symbols().
imported_symbol_end()
imported_symbol_iterator ImportDirectoryEntryRef::imported_symbol_end () const
Definition at line 1448 of file COFFObjectFile.cpp.
References importedSymbolEnd().
Referenced by imported_symbols().
imported_symbols()
iterator_range< imported_symbol_iterator > ImportDirectoryEntryRef::imported_symbols () const
Definition at line 1454 of file COFFObjectFile.cpp.
References imported_symbol_begin(), imported_symbol_end(), and llvm::make_range().
lookup_table_begin()
imported_symbol_iterator ImportDirectoryEntryRef::lookup_table_begin () const
Definition at line 1458 of file COFFObjectFile.cpp.
References importedSymbolBegin().
Referenced by lookup_table_symbols().
lookup_table_end()
imported_symbol_iterator ImportDirectoryEntryRef::lookup_table_end () const
Definition at line 1463 of file COFFObjectFile.cpp.
References importedSymbolEnd().
Referenced by lookup_table_symbols().
lookup_table_symbols()
iterator_range< imported_symbol_iterator > ImportDirectoryEntryRef::lookup_table_symbols () const
Definition at line 1469 of file COFFObjectFile.cpp.
References lookup_table_begin(), lookup_table_end(), and llvm::make_range().
moveNext()
void ImportDirectoryEntryRef::moveNext ()
Definition at line 1390 of file COFFObjectFile.cpp.
operator==()
bool ImportDirectoryEntryRef::operator== (const ImportDirectoryEntryRef & Other) const
Definition at line 1385 of file COFFObjectFile.cpp.
References llvm::Other.
The documentation for this class was generated from the following files:
include/llvm/Object/COFF.h
lib/Object/COFFObjectFile.cpp