LLVM: llvm::ModuloScheduleExpander Class Reference
llvm::ModuloScheduleExpander Class Reference
The ModuloScheduleExpander takes a ModuloSchedule and expands it in-place, rewriting the old loop and inserting prologs and epilogs as required.
#include "llvm/CodeGen/ModuloSchedule.h"
Public Types
using InstrChangesTy = DenseMap<MachineInstr *, std::pair<unsigned, int64_t>>
Public Member Functions
ModuloScheduleExpander (MachineFunction &MF, ModuloSchedule &S, LiveIntervals &LIS, InstrChangesTy InstrChanges)
Create a new ModuloScheduleExpander.
void expand ()
Performs the actual expansion.
void cleanup ()
Performs final cleanup after expansion.
MachineBasicBlock * getRewrittenKernel ()
Returns the newly rewritten kernel block, or nullptr if this was optimized away.
Detailed Description
The ModuloScheduleExpander takes a ModuloSchedule and expands it in-place, rewriting the old loop and inserting prologs and epilogs as required.
Definition at line 160 of file ModuloSchedule.h.
Member Typedef Documentation
InstrChangesTy
using llvm::ModuloScheduleExpander::InstrChangesTy = DenseMap<MachineInstr *, std::pair<unsigned, int64_t>>
Definition at line 162 of file ModuloSchedule.h.
Constructor & Destructor Documentation
ModuloScheduleExpander()
llvm::ModuloScheduleExpander::ModuloScheduleExpander (MachineFunction & MF, ModuloSchedule & S, LiveIntervals & LIS, InstrChangesTy InstrChanges) inline
Create a new ModuloScheduleExpander.
InstrChanges Modifications to make to instructions with memory operands. FIXME: InstrChanges is opaque and is an implementation detail of an optimization in MachinePipeliner that crosses abstraction boundaries.
Definition at line 264 of file ModuloSchedule.h.
References MRI, and TII.
Member Function Documentation
cleanup()
void ModuloScheduleExpander::cleanup ()
Performs final cleanup after expansion.
Definition at line 184 of file ModuloSchedule.cpp.
References llvm::MachineBasicBlock::clear(), llvm::MachineBasicBlock::eraseFromParent(), I, and llvm::LiveIntervals::RemoveMachineInstrFromMaps().
expand()
void ModuloScheduleExpander::expand ()
Performs the actual expansion.
Definition at line 67 of file ModuloSchedule.cpp.
References llvm::ModuloSchedule::getInstructions(), llvm::ModuloSchedule::getLoop(), llvm::ModuloSchedule::getStage(), llvm::MachineLoop::getTopBlock(), MI, llvm::MachineBasicBlock::pred_begin(), Reg, llvm::MachineRegisterInfo::use_operands(), and UseMI.
getRewrittenKernel()
MachineBasicBlock * llvm::ModuloScheduleExpander::getRewrittenKernel () inline
Returns the newly rewritten kernel block, or nullptr if this was optimized away.
Definition at line 277 of file ModuloSchedule.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/ModuloSchedule.h
lib/CodeGen/ModuloSchedule.cpp