LLVM: llvm::MSP430TargetELFStreamer Class Reference
llvm::MSP430TargetELFStreamer Class Reference
Public Member Functions
MCELFStreamer & getStreamer ()
MSP430TargetELFStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 28 of file MSP430ELFStreamer.cpp.
Constructor & Destructor Documentation
MSP430TargetELFStreamer()
llvm::MSP430TargetELFStreamer::MSP430TargetELFStreamer (MCStreamer & S, const MCSubtargetInfo & STI)
Definition at line 35 of file MSP430ELFStreamer.cpp.
References llvm::MSP430Attrs::CMSmall, llvm::MSP430Attrs::DMSmall, llvm::MCStreamer::emitBytes(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getContext(), llvm::MCContext::getELFSection(), getStreamer(), llvm::MCSubtargetInfo::hasFeature(), llvm::MSP430Attrs::ISAMSP430, llvm::MSP430Attrs::ISAMSP430X, llvm::ELF::SHT_MSP430_ATTRIBUTES, llvm::MCTargetStreamer::Streamer, llvm::MCStreamer::switchSection(), llvm::MSP430Attrs::TagCodeModel, llvm::MSP430Attrs::TagDataModel, and llvm::MSP430Attrs::TagISA.
Member Function Documentation
getStreamer()
MCELFStreamer & llvm::MSP430TargetELFStreamer::getStreamer ()
Definition at line 70 of file MSP430ELFStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
Referenced by MSP430TargetELFStreamer().
The documentation for this class was generated from the following file:
lib/Target/MSP430/MCTargetDesc/MSP430ELFStreamer.cpp