LLVM: llvm::orc::shared::SPSSerializationTraits< SPSString, StringRef > Class Reference
llvm::orc::shared::SPSSerializationTraits< SPSString, StringRef > Class Reference
Serialization for StringRefs.
#include "llvm/ExecutionEngine/Orc/Shared/SimplePackedSerialization.h"
Static Public Member Functions
static size_t size (const StringRef &S)
static bool serialize (SPSOutputBuffer &OB, StringRef S)
static bool deserialize (SPSInputBuffer &IB, StringRef &S)
Detailed Description
Serialization for StringRefs.
Serialization is as for regular strings. Deserialization points directly into the blob.
Definition at line 513 of file SimplePackedSerialization.h.
Member Function Documentation
deserialize()
static bool llvm::orc::shared::SPSSerializationTraits< SPSString, StringRef >::deserialize (SPSInputBuffer & IB, StringRef & S) inline static
Definition at line 528 of file SimplePackedSerialization.h.
References llvm::Data, and Size.
serialize()
static bool llvm::orc::shared::SPSSerializationTraits< SPSString, StringRef >::serialize (SPSOutputBuffer & OB, StringRef S) inline static
Definition at line 520 of file SimplePackedSerialization.h.
References llvm::StringRef::data(), llvm::StringRef::empty(), and llvm::StringRef::size().
size()
static size_t llvm::orc::shared::SPSSerializationTraits< SPSString, StringRef >::size (const StringRef & S) inline static
Definition at line 515 of file SimplePackedSerialization.h.
References llvm::StringRef::size().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/SimplePackedSerialization.h