LLVM: llvm::GCStatepointInst Class Reference
llvm::GCStatepointInst Class Reference
Represents a gc.statepoint intrinsic call.
#include "llvm/IR/Statepoint.h"
Public Types
enum {
IDPos = 0 , NumPatchBytesPos = 1 , CalledFunctionPos = 2 , NumCallArgsPos = 3 ,
FlagsPos = 4 , CallArgsBeginPos = 5
}
Public Types inherited from llvm::CallBase
using bundle_op_iterator = BundleOpInfo *
using const_bundle_op_iterator = const BundleOpInfo *
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0 , CompareUsingScalarTypes = 1<<1 }
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
enum TermOps
enum UnaryOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum FuncletPadOps
enum OtherOps
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Public Member Functions
GCStatepointInst ()=delete
GCStatepointInst (const GCStatepointInst &)=delete
GCStatepointInst & operator= (const GCStatepointInst &)=delete
uint64_t getID () const
Return the ID associated with this statepoint.
uint32_t getNumPatchBytes () const
Return the number of patchable bytes associated with this statepoint.
int getNumCallArgs () const
Number of arguments to be passed to the actual callee.
uint64_t getFlags () const
Value * getActualCalledOperand () const
Return the value actually being called or invoked.
Function * getActualCalledFunction () const
Returns the function called if this is a wrapping a direct call, and null otherwise.
Type * getActualReturnType () const
Return the type of the value returned by the call underlying the statepoint.
size_t actual_arg_size () const
Return the number of arguments to the underlying call.
const_op_iterator actual_arg_begin () const
Return an iterator to the begining of the arguments to the underlying call.
const_op_iterator actual_arg_end () const
Return an end iterator of the arguments to the underlying call.
iterator_range< const_op_iterator > actual_args () const
range adapter for actual call arguments
const_op_iterator gc_transition_args_begin () const
const_op_iterator gc_transition_args_end () const
iterator_range< const_op_iterator > gc_transition_args () const
range adapter for GC transition arguments
const_op_iterator deopt_begin () const
const_op_iterator deopt_end () const
iterator_range< const_op_iterator > deopt_operands () const
range adapter for vm state arguments
const_op_iterator gc_args_begin () const
Returns an iterator to the begining of the argument range describing gc values for the statepoint.
const_op_iterator gc_args_end () const
Return an end iterator for the gc argument range.
iterator_range< const_op_iterator > gc_args () const
range adapter for gc arguments
std::vector< const GCRelocateInst * > getGCRelocates () const
Get list of all gc reloactes linked to this statepoint May contain several relocations for the same base/derived pair.
Public Member Functions inherited from llvm::CallBase
FunctionType * getFunctionType () const
void mutateFunctionType (FunctionType *FTy)
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
User::op_iterator data_operands_begin ()
data_operands_begin/data_operands_end - Return iterators iterating over the call / invoke argument list and bundle operands.
User::const_op_iterator data_operands_begin () const
User::op_iterator data_operands_end ()
User::const_op_iterator data_operands_end () const
iterator_range< User::op_iterator > data_ops ()
iterator_range< User::const_op_iterator > data_ops () const
bool data_operands_empty () const
unsigned data_operands_size () const
bool isDataOperand (const Use *U) const
bool isDataOperand (Value::const_user_iterator UI) const
unsigned getDataOperandNo (Value::const_user_iterator UI) const
Given a value use iterator, return the data operand corresponding to it.
unsigned getDataOperandNo (const Use *U) const
Given a use for a data operand, get the data operand number that corresponds to it.
User::op_iterator arg_begin ()
Return the iterator pointing to the beginning of the argument list.
User::const_op_iterator arg_begin () const
User::op_iterator arg_end ()
Return the iterator pointing to the end of the argument list.
User::const_op_iterator arg_end () const
iterator_range< User::op_iterator > args ()
Iteration adapter for range-for loops.
iterator_range< User::const_op_iterator > args () const
bool arg_empty () const
unsigned arg_size () const
Value * getArgOperand (unsigned i) const
void setArgOperand (unsigned i, Value *v)
const Use & getArgOperandUse (unsigned i) const
Wrappers for getting the Use of a call argument.
Use & getArgOperandUse (unsigned i)
bool isArgOperand (const Use *U) const
bool isArgOperand (Value::const_user_iterator UI) const
unsigned getArgOperandNo (const Use *U) const
Given a use for a arg operand, get the arg operand number that corresponds to it.
unsigned getArgOperandNo (Value::const_user_iterator UI) const
Given a value use iterator, return the arg operand number corresponding to it.
bool hasArgument (const Value *V) const
Returns true if this CallSite passes the given Value* as an argument to the called function.
Value * getCalledOperand () const
const Use & getCalledOperandUse () const
Use & getCalledOperandUse ()
Function * getCalledFunction () const
Returns the function called, or null if this is an indirect function invocation or the function signature does not match the call signature.
bool isIndirectCall () const
Return true if the callsite is an indirect call.
bool isCallee (Value::const_user_iterator UI) const
Determine whether the passed iterator points to the callee operand's Use.
bool isCallee (const Use *U) const
Determine whether this Use is the callee operand's Use.
Function * getCaller ()
Helper to get the caller (the parent function).
const Function * getCaller () const
bool isMustTailCall () const
Tests if this call site must be tail call optimized.
bool isTailCall () const
Tests if this call site is marked as a tail call.
Intrinsic::ID getIntrinsicID () const
Returns the intrinsic ID of the intrinsic called or Intrinsic::not_intrinsic if the called function is not an intrinsic, or if this is an indirect call.
void setCalledOperand (Value *V)
void setCalledFunction (Function *Fn)
Sets the function called, including updating the function type.
void setCalledFunction (FunctionCallee Fn)
Sets the function called, including updating the function type.
void setCalledFunction (FunctionType *FTy, Value *Fn)
Sets the function called, including updating to the specified function type.
CallingConv::ID getCallingConv () const
void setCallingConv (CallingConv::ID CC)
bool isInlineAsm () const
Check if this call is an inline asm statement.
AttributeList getAttributes () const
Return the parameter attributes for this call.
void setAttributes (AttributeList A)
Set the parameter attributes for this call.
bool hasFnAttr (Attribute::AttrKind Kind) const
Determine whether this call has the given attribute.
bool hasFnAttr (StringRef Kind) const
Determine whether this call has the given attribute.
void addAttributeAtIndex (unsigned i, Attribute::AttrKind Kind)
adds the attribute to the list of attributes.
void addAttributeAtIndex (unsigned i, Attribute Attr)
adds the attribute to the list of attributes.
void addFnAttr (Attribute::AttrKind Kind)
Adds the attribute to the function.
void addFnAttr (Attribute Attr)
Adds the attribute to the function.
void addRetAttr (Attribute::AttrKind Kind)
Adds the attribute to the return value.
void addRetAttr (Attribute Attr)
Adds the attribute to the return value.
void addParamAttr (unsigned ArgNo, Attribute::AttrKind Kind)
Adds the attribute to the indicated argument.
void addParamAttr (unsigned ArgNo, Attribute Attr)
Adds the attribute to the indicated argument.
void removeAttributeAtIndex (unsigned i, Attribute::AttrKind Kind)
removes the attribute from the list of attributes.
void removeAttributeAtIndex (unsigned i, StringRef Kind)
removes the attribute from the list of attributes.
void removeFnAttrs (const AttributeMask &AttrsToRemove)
Removes the attributes from the function.
void removeFnAttr (Attribute::AttrKind Kind)
Removes the attribute from the function.
void removeRetAttr (Attribute::AttrKind Kind)
Removes the attribute from the return value.
void removeRetAttrs (const AttributeMask &AttrsToRemove)
Removes the attributes from the return value.
void removeParamAttr (unsigned ArgNo, Attribute::AttrKind Kind)
Removes the attribute from the given argument.
void removeParamAttr (unsigned ArgNo, StringRef Kind)
Removes the attribute from the given argument.
void removeParamAttrs (unsigned ArgNo, const AttributeMask &AttrsToRemove)
Removes the attributes from the given argument.
void addDereferenceableParamAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable attribute to the list of attributes.
void addDereferenceableRetAttr (uint64_t Bytes)
adds the dereferenceable attribute to the list of attributes.
bool hasRetAttr (Attribute::AttrKind Kind) const
Determine whether the return value has the given attribute.
bool hasRetAttr (StringRef Kind) const
Determine whether the return value has the given attribute.
bool paramHasAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Determine whether the argument or parameter has the given attribute.
Attribute getAttributeAtIndex (unsigned i, Attribute::AttrKind Kind) const
Get the attribute of a given kind at a position.
Attribute getAttributeAtIndex (unsigned i, StringRef Kind) const
Get the attribute of a given kind at a position.
Attribute getFnAttr (StringRef Kind) const
Get the attribute of a given kind for the function.
Attribute getFnAttr (Attribute::AttrKind Kind) const
Get the attribute of a given kind for the function.
Attribute getParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Get the attribute of a given kind from a given arg.
Attribute getParamAttr (unsigned ArgNo, StringRef Kind) const
Get the attribute of a given kind from a given arg.
bool dataOperandHasImpliedAttr (unsigned i, Attribute::AttrKind Kind) const
Return true if the data operand at index i has the attribute A.
bool doesNotCapture (unsigned OpNo) const
Determine whether this data operand is not captured.
bool isByValArgument (unsigned ArgNo) const
Determine whether this argument is passed by value.
bool isInAllocaArgument (unsigned ArgNo) const
Determine whether this argument is passed in an alloca.
bool isPassPointeeByValueArgument (unsigned ArgNo) const
Determine whether this argument is passed by value, in an alloca, or is preallocated.
bool isPassingUndefUB (unsigned ArgNo) const
Determine whether passing undef to this argument is undefined behavior.
bool hasInAllocaArgument () const
Determine if there are is an inalloca argument.
bool doesNotAccessMemory (unsigned OpNo) const
bool onlyReadsMemory (unsigned OpNo) const
bool onlyWritesMemory (unsigned OpNo) const
MaybeAlign getRetAlign () const
Extract the alignment of the return value.
MaybeAlign getParamAlign (unsigned ArgNo) const
Extract the alignment for a call or parameter (0=unknown).
MaybeAlign getParamStackAlign (unsigned ArgNo) const
Type * getParamByValType (unsigned ArgNo) const
Extract the byval type for a call or parameter.
Type * getParamPreallocatedType (unsigned ArgNo) const
Extract the preallocated type for a call or parameter.
Type * getParamInAllocaType (unsigned ArgNo) const
Extract the inalloca type for a call or parameter.
Type * getParamStructRetType (unsigned ArgNo) const
Extract the sret type for a call or parameter.
Type * getParamElementType (unsigned ArgNo) const
Extract the elementtype type for a parameter.
uint64_t getRetDereferenceableBytes () const
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
uint64_t getParamDereferenceableBytes (unsigned i) const
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
uint64_t getRetDereferenceableOrNullBytes () const
Extract the number of dereferenceable_or_null bytes for a call (0=unknown).
uint64_t getParamDereferenceableOrNullBytes (unsigned i) const
Extract the number of dereferenceable_or_null bytes for a parameter (0=unknown).
bool isReturnNonNull () const
Return true if the return value is known to be not null.
bool returnDoesNotAlias () const
Determine if the return value is marked with NoAlias attribute.
Value * getReturnedArgOperand () const
If one of the arguments has the 'returned' attribute, returns its operand value.
Value * getArgOperandWithAttribute (Attribute::AttrKind Kind) const
If one of the arguments has the specified attribute, returns its operand value.
bool isNoBuiltin () const
Return true if the call should not be treated as a call to a builtin.
bool isStrictFP () const
Determine if the call requires strict floating point semantics.
bool isNoInline () const
Return true if the call should not be inlined.
void setIsNoInline ()
MemoryEffects getMemoryEffects () const
void setMemoryEffects (MemoryEffects ME)
bool doesNotAccessMemory () const
Determine if the call does not access memory.
void setDoesNotAccessMemory ()
bool onlyReadsMemory () const
Determine if the call does not access or only reads memory.
void setOnlyReadsMemory ()
bool onlyWritesMemory () const
Determine if the call does not access or only writes memory.
void setOnlyWritesMemory ()
bool onlyAccessesArgMemory () const
Determine if the call can access memmory only using pointers based on its arguments.
void setOnlyAccessesArgMemory ()
bool onlyAccessesInaccessibleMemory () const
Determine if the function may only access memory that is inaccessible from the IR.
void setOnlyAccessesInaccessibleMemory ()
bool onlyAccessesInaccessibleMemOrArgMem () const
Determine if the function may only access memory that is either inaccessible from the IR or pointed to by its arguments.
void setOnlyAccessesInaccessibleMemOrArgMem ()
bool doesNotReturn () const
Determine if the call cannot return.
void setDoesNotReturn ()
bool doesNoCfCheck () const
Determine if the call should not perform indirect branch tracking.
bool doesNotThrow () const
Determine if the call cannot unwind.
void setDoesNotThrow ()
bool cannotDuplicate () const
Determine if the invoke cannot be duplicated.
void setCannotDuplicate ()
bool cannotMerge () const
Determine if the call cannot be tail merged.
void setCannotMerge ()
bool isConvergent () const
Determine if the invoke is convergent.
void setConvergent ()
void setNotConvergent ()
bool hasStructRetAttr () const
Determine if the call returns a structure through first pointer argument.
bool hasByValArgument () const
Determine if any call argument is an aggregate passed by value.
unsigned getNumOperandBundles () const
Return the number of operand bundles associated with this User.
bool hasOperandBundles () const
Return true if this User has any operand bundles.
unsigned getBundleOperandsStartIndex () const
Return the index of the first bundle operand in the Use array.
unsigned getBundleOperandsEndIndex () const
Return the index of the last bundle operand in the Use array.
bool isBundleOperand (unsigned Idx) const
Return true if the operand at index Idx is a bundle operand.
bool isOperandBundleOfType (uint32_t ID, unsigned Idx) const
Return true if the operand at index Idx is a bundle operand that has tag ID ID.
bool isBundleOperand (const Use *U) const
Returns true if the use is a bundle operand.
bool isBundleOperand (Value::const_user_iterator UI) const
unsigned getNumTotalBundleOperands () const
Return the total number operands (not operand bundles) used by every operand bundle in this OperandBundleUser.
OperandBundleUse getOperandBundleAt (unsigned Index) const
Return the operand bundle at a specific index.
unsigned countOperandBundlesOfType (StringRef Name) const
Return the number of operand bundles with the tag Name attached to this instruction.
unsigned countOperandBundlesOfType (uint32_t ID) const
Return the number of operand bundles with the tag ID attached to this instruction.
std::optional< OperandBundleUse > getOperandBundle (StringRef Name) const
Return an operand bundle by name, if present.
std::optional< OperandBundleUse > getOperandBundle (uint32_t ID) const
Return an operand bundle by tag ID, if present.
void getOperandBundlesAsDefs (SmallVectorImpl< OperandBundleDef > &Defs) const
Return the list of operand bundles attached to this instruction as a vector of OperandBundleDefs.
OperandBundleUse getOperandBundleForOperand (unsigned OpIdx) const
Return the operand bundle for the operand at index OpIdx.
bool hasReadingOperandBundles () const
Return true if this operand bundle user has operand bundles that may read from the heap.
bool hasClobberingOperandBundles () const
Return true if this operand bundle user has operand bundles that may write to the heap.
bool bundleOperandHasAttr (unsigned OpIdx, Attribute::AttrKind A) const
Return true if the bundle operand at index OpIdx has the attribute A.
bool hasIdenticalOperandBundleSchema (const CallBase &Other) const
Return true if Other has the same sequence of operand bundle tags with the same number of operands on each one of them as this OperandBundleUser.
bool hasOperandBundlesOtherThan (ArrayRef< uint32_t > IDs) const
Return true if this operand bundle user contains operand bundles with tags other than those specified in IDs.
OperandBundleUse operandBundleFromBundleOpInfo (const BundleOpInfo &BOI) const
Simple helper function to map a BundleOpInfo to an OperandBundleUse.
bundle_op_iterator bundle_op_info_begin ()
Return the start of the list of BundleOpInfo instances associated with this OperandBundleUser.
const_bundle_op_iterator bundle_op_info_begin () const
Return the start of the list of BundleOpInfo instances associated with this OperandBundleUser.
bundle_op_iterator bundle_op_info_end ()
Return the end of the list of BundleOpInfo instances associated with this OperandBundleUser.
const_bundle_op_iterator bundle_op_info_end () const
Return the end of the list of BundleOpInfo instances associated with this OperandBundleUser.
iterator_range< bundle_op_iterator > bundle_op_infos ()
Return the range [bundle_op_info_begin, bundle_op_info_end).
iterator_range< const_bundle_op_iterator > bundle_op_infos () const
Return the range [bundle_op_info_begin, bundle_op_info_end).
op_iterator populateBundleOperandInfos (ArrayRef< OperandBundleDef > Bundles, const unsigned BeginIndex)
Populate the BundleOpInfo instances and the Use& vector from Bundles.
BundleOpInfo & getBundleOpInfoForOperand (unsigned OpIdx)
Return the BundleOpInfo for the operand at index OpIdx.
const BundleOpInfo & getBundleOpInfoForOperand (unsigned OpIdx) const
Public Member Functions inherited from llvm::Instruction
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
Instruction * user_back ()
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
const Instruction * user_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
const Module * getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Module * getModule ()
const Function * getFunction () const
Return the function this instruction belongs to.
Function * getFunction ()
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
SymbolTableList< Instruction >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
void insertBefore (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
void insertAfter (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
SymbolTableList< Instruction >::iterator insertInto (BasicBlock *ParentBB, SymbolTableList< Instruction >::iterator It)
Inserts an unlinked instruction into ParentBB at position It and returns the iterator of the inserted instruction.
void moveBefore (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
void moveBefore (BasicBlock &BB, SymbolTableList< Instruction >::iterator I)
Unlink this instruction and insert into BB before I.
void moveAfter (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
bool comesBefore (const Instruction *Other) const
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
Instruction * getInsertionPointAfterDef ()
Get the first insertion point at which the result of this instruction is defined.
unsigned getOpcode () const
Returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isExceptionalTerminator () const
bool isOnlyUserOfAnyOperand ()
It checks if this instruction is the only user of at least one of its operands.
bool isLogicalShift () const
Return true if this is a logical shift left or a logical shift right.
bool isArithmeticShift () const
Return true if this is an arithmetic shift right.
bool isBitwiseLogicOp () const
Return true if this is and/or/xor.
bool hasMetadata () const
Return true if this instruction has any metadata attached to it.
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
Return true if this instruction has the given type of metadata attached.
MDNode * getMetadata (unsigned KindID) const
Get the metadata of given kind attached to this Instruction.
MDNode * getMetadata (StringRef Kind) const
Get the metadata of given kind attached to this Instruction.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Get all metadata attached to this Instruction.
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
This does the same thing as getAllMetadata, except that it filters out the debug location.
void setMetadata (unsigned KindID, MDNode *Node)
Set the metadata of the specified kind to the specified node.
void setMetadata (StringRef Kind, MDNode *Node)
void copyMetadata (const Instruction &SrcInst, ArrayRef< unsigned > WL=ArrayRef< unsigned >())
Copy metadata from SrcInst to this instruction.
void swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
void addAnnotationMetadata (StringRef Annotation)
Adds an !annotation metadata node with Annotation to this instruction.
AAMDNodes getAAMetadata () const
Returns the AA metadata for this instruction.
void setAAMetadata (const AAMDNodes &N)
Sets the AA metadata on this instruction from the AAMDNodes structure.
bool extractProfTotalWeight (uint64_t &TotalVal) const
Retrieve total raw weight values of a branch.
void setDebugLoc (DebugLoc Loc)
Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
Return the debug location for this node as a DebugLoc.
void setHasNoUnsignedWrap (bool b=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedWrap (bool b=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
void setIsExact (bool b=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
bool hasNoUnsignedWrap () const LLVM_READONLY
Determine whether the no unsigned wrap flag is set.
bool hasNoSignedWrap () const LLVM_READONLY
Determine whether the no signed wrap flag is set.
bool hasPoisonGeneratingFlags () const LLVM_READONLY
Return true if this operator has flags which may cause this instruction to evaluate to poison despite having non-poison inputs.
void dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
bool hasPoisonGeneratingMetadata () const LLVM_READONLY
Return true if this instruction has poison-generating metadata.
void dropPoisonGeneratingMetadata ()
Drops metadata that may generate poison.
bool hasPoisonGeneratingFlagsOrMetadata () const
Return true if this instruction has poison-generating flags or metadata.
void dropPoisonGeneratingFlagsAndMetadata ()
Drops flags and metadata that may generate poison.
void dropUndefImplyingAttrsAndUnknownMetadata (ArrayRef< unsigned > KnownIDs={})
This function drops non-debug unknown metadata (through dropUnknownNonDebugMetadata).
bool isExact () const LLVM_READONLY
Determine whether the exact flag is set.
void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
void setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
bool isFast () const LLVM_READONLY
Determine whether all fast-math-flags are set.
bool hasAllowReassoc () const LLVM_READONLY
Determine whether the allow-reassociation flag is set.
bool hasNoNaNs () const LLVM_READONLY
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const LLVM_READONLY
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const LLVM_READONLY
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const LLVM_READONLY
Determine whether the allow-reciprocal flag is set.
bool hasAllowContract () const LLVM_READONLY
Determine whether the allow-contract flag is set.
bool hasApproxFunc () const LLVM_READONLY
Determine whether the approximate-math-functions flag is set.
FastMathFlags getFastMathFlags () const LLVM_READONLY
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
void copyIRFlags (const Value *V, bool IncludeWrapFlags=true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
void andIRFlags (const Value *V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
void applyMergedLocation (const DILocation *LocA, const DILocation *LocB)
Merge 2 debug locations and apply it to the Instruction.
void updateLocationAfterHoist ()
Updates the debug location given that the instruction has been hoisted from a block to a predecessor of that block.
void dropLocation ()
Drop the instruction's debug location.
void mergeDIAssignID (ArrayRef< const Instruction * > SourceInstructions)
Merge the DIAssignID metadata from this instruction and those attached to instructions in SourceInstructions.
bool isAssociative () const LLVM_READONLY
Return true if the instruction is associative:
bool isCommutative () const LLVM_READONLY
Return true if the instruction is commutative:
bool isIdempotent () const
Return true if the instruction is idempotent:
bool isNilpotent () const
Return true if the instruction is nilpotent:
bool mayWriteToMemory () const LLVM_READONLY
Return true if this instruction may modify memory.
bool mayReadFromMemory () const LLVM_READONLY
Return true if this instruction may read memory.
bool mayReadOrWriteMemory () const
Return true if this instruction may read or write memory.
bool isAtomic () const LLVM_READONLY
Return true if this instruction has an AtomicOrdering of unordered or higher.
bool hasAtomicLoad () const LLVM_READONLY
Return true if this atomic instruction loads from memory.
bool hasAtomicStore () const LLVM_READONLY
Return true if this atomic instruction stores to memory.
bool isVolatile () const LLVM_READONLY
Return true if this instruction has a volatile memory access.
bool mayThrow () const LLVM_READONLY
Return true if this instruction may throw an exception.
bool isFenceLike () const
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
bool mayHaveSideEffects () const LLVM_READONLY
Return true if the instruction may have side effects.
bool isSafeToRemove () const LLVM_READONLY
Return true if the instruction can be removed if the result is unused.
bool willReturn () const LLVM_READONLY
Return true if the instruction will return (unwinding is considered as a form of returning control flow here).
bool isEHPad () const
Return true if the instruction is a variety of EH-block.
bool isLifetimeStartOrEnd () const LLVM_READONLY
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
bool isLaunderOrStripInvariantGroup () const LLVM_READONLY
Return true if the instruction is a llvm.launder.invariant.group or llvm.strip.invariant.group.
bool isDebugOrPseudoInst () const LLVM_READONLY
Return true if the instruction is a DbgInfoIntrinsic or PseudoProbeInst.
const Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the next non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false)
const Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the previous non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false)
Instruction * clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
bool isIdenticalTo (const Instruction *I) const LLVM_READONLY
Return true if the specified instruction is exactly identical to the current one.
bool isIdenticalToWhenDefined (const Instruction *I) const LLVM_READONLY
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const LLVM_READONLY
This function determines if the specified instruction executes the same operation as the current one.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const LLVM_READONLY
Return true if there are any uses of this instruction in blocks other than the specified block.
unsigned getNumSuccessors () const LLVM_READONLY
Return the number of successors that this instruction has.
BasicBlock * getSuccessor (unsigned Idx) const LLVM_READONLY
Return the specified successor. This instruction must be a terminator.
void setSuccessor (unsigned Idx, BasicBlock *BB)
Update the specified successor to point at the provided block.
void replaceSuccessorWith (BasicBlock *OldBB, BasicBlock *NewBB)
Replace specified successor OldBB to point at the provided block.
void dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs)
Drop all unknown metadata except for debug locations.
void dropUnknownNonDebugMetadata ()
void dropUnknownNonDebugMetadata (unsigned ID1)
void dropUnknownNonDebugMetadata (unsigned ID1, unsigned ID2)
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
Instruction * getPrevNode ()
const Instruction * getPrevNode () const
Get the previous node, or nullptr for the list head.
Instruction * getNextNode ()
Get the next node, or nullptr for the list tail.
const Instruction * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const CallBase *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::CallBase
static CallBase * Create (CallBase *CB, ArrayRef< OperandBundleDef > Bundles, Instruction *InsertPt=nullptr)
Create a clone of CB with a different set of operand bundles and insert it before InsertPt.
static CallBase * Create (CallBase *CB, OperandBundleDef Bundle, Instruction *InsertPt=nullptr)
Create a clone of CB with the operand bundle with the tag matching Bundle's tag replaced with Bundle, and insert it before InsertPt.
static CallBase * addOperandBundle (CallBase *CB, uint32_t ID, OperandBundleDef OB, Instruction *InsertPt=nullptr)
Create a clone of CB with operand bundle OB added.
static CallBase * removeOperandBundle (CallBase *CB, uint32_t ID, Instruction *InsertPt=nullptr)
Create a clone of CB with operand bundle ID removed.
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isUnaryOp (unsigned Opcode)
static bool isBinaryOp (unsigned Opcode)
static bool isIntDivRem (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isBitwiseLogicOp (unsigned Opcode)
Determine if the Opcode is and/or/xor.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isFuncletPad (unsigned OpCode)
Determine if the OpCode is one of the FuncletPadInst instructions.
static bool isExceptionalTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator related to exception handling.
static bool isAssociative (unsigned Opcode)
static bool isCommutative (unsigned Opcode)
static bool isIdempotent (unsigned Opcode)
static bool isNilpotent (unsigned Opcode)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::CallBase
using CallInstReservedField = Bitfield::Element<unsigned, 0, 2>
using CallingConvField
Protected Types inherited from llvm::Instruction
using OpaqueField = Bitfield::Element<uint16_t, 0, 15>
template<unsigned Offset>
using AlignmentBitfieldElementT
template<unsigned Offset>
using BoolBitfieldElementT = typename Bitfield::Element<bool, Offset, 1>
template<unsigned Offset>
using AtomicOrderingBitfieldElementT
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::CallBase
template<class... ArgsTy>
CallBase (AttributeList const &A, FunctionType *FT, ArgsTy &&... Args)
bool hasDescriptor () const
unsigned getNumSubclassExtraOperands () const
unsigned getNumSubclassExtraOperandsDynamic () const
Get the number of extra operands for instructions that don't have a fixed number of extra operands.
Instruction (const Instruction &)=delete
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::Instruction
~Instruction ()
template<typename BitfieldElement >
BitfieldElement::Type getSubclassData () const
template<typename BitfieldElement >
void setSubclassData (typename BitfieldElement::Type Value)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Protected Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Static Protected Member Functions inherited from llvm::CallBase
static unsigned CountBundleInputs (ArrayRef< OperandBundleDef > Bundles)
Return the total number of values used in Bundles.
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::CallBase
AttributeList Attrs
parameter attributes for callable
FunctionType * FTy
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Static Protected Attributes inherited from llvm::CallBase
static constexpr int CalledOperandOpEndIdx = -1
The last operand is the called operand.
Detailed Description
Represents a gc.statepoint intrinsic call.
This extends directly from CallBase as the IntrinsicInst only supports calls and gc.statepoint is invokable.
Definition at line 61 of file Statepoint.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
IDPos
NumPatchBytesPos
CalledFunctionPos
NumCallArgsPos
FlagsPos
CallArgsBeginPos
Definition at line 77 of file Statepoint.h.
Constructor & Destructor Documentation
GCStatepointInst() [1/2]
llvm::GCStatepointInst::GCStatepointInst () delete
GCStatepointInst() [2/2]
llvm::GCStatepointInst::GCStatepointInst (const GCStatepointInst &) delete
Member Function Documentation
actual_arg_begin()
const_op_iterator llvm::GCStatepointInst::actual_arg_begin () const inline
Return an iterator to the begining of the arguments to the underlying call.
Definition at line 131 of file Statepoint.h.
References llvm::CallBase::arg_begin(), llvm::CallBase::arg_size(), assert(), and CallArgsBeginPos.
Referenced by actual_arg_end(), and actual_args().
actual_arg_end()
const_op_iterator llvm::GCStatepointInst::actual_arg_end () const inline
Return an end iterator of the arguments to the underlying call.
Definition at line 136 of file Statepoint.h.
References actual_arg_begin(), actual_arg_size(), llvm::CallBase::arg_end(), assert(), and I.
Referenced by actual_args().
actual_arg_size()
size_t llvm::GCStatepointInst::actual_arg_size () const inline
Return the number of arguments to the underlying call.
Definition at line 129 of file Statepoint.h.
References getNumCallArgs().
Referenced by actual_arg_end().
actual_args()
iterator_range< const_op_iterator > llvm::GCStatepointInst::actual_args () const inline
range adapter for actual call arguments
Definition at line 142 of file Statepoint.h.
References actual_arg_begin(), actual_arg_end(), and llvm::make_range().
classof() [1/2]
static bool llvm::GCStatepointInst::classof (const CallBase * I) inline static
Definition at line 67 of file Statepoint.h.
References I.
Referenced by classof().
classof() [2/2]
static bool llvm::GCStatepointInst::classof (const Value * V) inline static
Definition at line 73 of file Statepoint.h.
References classof(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
deopt_begin()
const_op_iterator llvm::GCStatepointInst::deopt_begin () const inline
Definition at line 162 of file Statepoint.h.
References llvm::CallBase::arg_end(), llvm::CallBase::getOperandBundle(), and llvm::LLVMContext::OB_deopt.
Referenced by deopt_operands().
deopt_end()
const_op_iterator llvm::GCStatepointInst::deopt_end () const inline
Definition at line 167 of file Statepoint.h.
References llvm::CallBase::arg_end(), llvm::CallBase::getOperandBundle(), and llvm::LLVMContext::OB_deopt.
Referenced by deopt_operands().
deopt_operands()
iterator_range< const_op_iterator > llvm::GCStatepointInst::deopt_operands () const inline
range adapter for vm state arguments
Definition at line 174 of file Statepoint.h.
References deopt_begin(), deopt_end(), and llvm::make_range().
gc_args()
iterator_range< const_op_iterator > llvm::GCStatepointInst::gc_args () const inline
range adapter for gc arguments
Definition at line 194 of file Statepoint.h.
References gc_args_begin(), gc_args_end(), and llvm::make_range().
gc_args_begin()
const_op_iterator llvm::GCStatepointInst::gc_args_begin () const inline
Returns an iterator to the begining of the argument range describing gc values for the statepoint.
Definition at line 180 of file Statepoint.h.
References llvm::CallBase::arg_end(), llvm::CallBase::getOperandBundle(), and llvm::LLVMContext::OB_gc_live.
Referenced by gc_args().
gc_args_end()
const_op_iterator llvm::GCStatepointInst::gc_args_end () const inline
Return an end iterator for the gc argument range.
Definition at line 187 of file Statepoint.h.
References llvm::CallBase::arg_end(), llvm::CallBase::getOperandBundle(), and llvm::LLVMContext::OB_gc_live.
Referenced by gc_args().
gc_transition_args()
iterator_range< const_op_iterator > llvm::GCStatepointInst::gc_transition_args () const inline
range adapter for GC transition arguments
Definition at line 158 of file Statepoint.h.
References gc_transition_args_begin(), gc_transition_args_end(), and llvm::make_range().
gc_transition_args_begin()
const_op_iterator llvm::GCStatepointInst::gc_transition_args_begin () const inline
Definition at line 146 of file Statepoint.h.
References llvm::CallBase::arg_end(), llvm::CallBase::getOperandBundle(), and llvm::LLVMContext::OB_gc_transition.
Referenced by gc_transition_args().
gc_transition_args_end()
const_op_iterator llvm::GCStatepointInst::gc_transition_args_end () const inline
Definition at line 151 of file Statepoint.h.
References llvm::CallBase::arg_end(), llvm::CallBase::getOperandBundle(), and llvm::LLVMContext::OB_gc_transition.
Referenced by gc_transition_args().
getActualCalledFunction()
Function * llvm::GCStatepointInst::getActualCalledFunction () const inline
Returns the function called if this is a wrapping a direct call, and null otherwise.
Definition at line 116 of file Statepoint.h.
References getActualCalledOperand(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
getActualCalledOperand()
Value * llvm::GCStatepointInst::getActualCalledOperand () const inline
Return the value actually being called or invoked.
Definition at line 110 of file Statepoint.h.
References CalledFunctionPos, and llvm::CallBase::getArgOperand().
Referenced by getActualCalledFunction().
getActualReturnType()
Type * llvm::GCStatepointInst::getActualReturnType () const inline
Return the type of the value returned by the call underlying the statepoint.
Definition at line 122 of file Statepoint.h.
References CalledFunctionPos, llvm::CallBase::getParamElementType(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
getFlags()
uint64_t llvm::GCStatepointInst::getFlags () const inline
Definition at line 105 of file Statepoint.h.
References FlagsPos, llvm::CallBase::getArgOperand(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
getGCRelocates()
std::vector< const GCRelocateInst * > llvm::GCStatepointInst::getGCRelocates () const inline
Get list of all gc reloactes linked to this statepoint May contain several relocations for the same base/derived pair.
For example this could happen due to relocations on unwinding path of invoke.
Definition at line 206 of file Statepoint.h.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and users.
getID()
uint64_t llvm::GCStatepointInst::getID () const inline
Return the ID associated with this statepoint.
Definition at line 87 of file Statepoint.h.
References llvm::CallBase::getArgOperand(), IDPos, and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
getNumCallArgs()
int llvm::GCStatepointInst::getNumCallArgs () const inline
Number of arguments to be passed to the actual callee.
Definition at line 101 of file Statepoint.h.
References llvm::CallBase::getArgOperand(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and NumCallArgsPos.
Referenced by actual_arg_size().
getNumPatchBytes()
uint32_t llvm::GCStatepointInst::getNumPatchBytes () const inline
Return the number of patchable bytes associated with this statepoint.
Definition at line 92 of file Statepoint.h.
References assert(), llvm::CallBase::getArgOperand(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and NumPatchBytesPos.
operator=()
GCStatepointInst & llvm::GCStatepointInst::operator= (const GCStatepointInst &) delete
The documentation for this class was generated from the following file:
include/llvm/IR/Statepoint.h