LLVM: llvm::ICmpInst Class Reference
llvm::ICmpInst Class Reference
This instruction compares its operands according to the predicate given to the constructor.
#include "llvm/IR/Instructions.h"
Public Member Functions
ICmpInst (Instruction *InsertBefore, Predicate pred, Value *LHS, Value *RHS, const Twine &NameStr="")
Constructor with insert-before-instruction semantics.
ICmpInst (BasicBlock &InsertAtEnd, Predicate pred, Value *LHS, Value *RHS, const Twine &NameStr="")
Constructor with insert-at-end semantics.
ICmpInst (Predicate pred, Value *LHS, Value *RHS, const Twine &NameStr="")
Constructor with no-insertion semantics.
Predicate getSignedPredicate () const
For example, EQ->EQ, SLE->SLE, UGT->SGT, etc.
Predicate getUnsignedPredicate () const
For example, EQ->EQ, SLE->ULE, UGT->UGT, etc.
bool isEquality () const
Return true if this predicate is either EQ or NE.
bool isCommutative () const
bool isRelational () const
Return true if the predicate is relational (not EQ or NE).
void swapOperands ()
Exchange the two operands to this instruction in such a way that it does not modify the semantics of the instruction.
Public Member Functions inherited from llvm::CmpInst
void * operator new (size_t S)
void operator delete (void *Ptr)
OtherOps getOpcode () const
Get the opcode casted to the right type.
Predicate getPredicate () const
Return the predicate for this instruction.
void setPredicate (Predicate P)
Set the predicate for this instruction to the specified value.
bool isFPPredicate () const
bool isIntPredicate () const
Predicate getInversePredicate () const
For example, EQ -> NE, UGT -> ULE, SLT -> SGE, OEQ -> UNE, UGT -> OLE, OLT -> UGE, etc.
Predicate getOrderedPredicate () const
Predicate getSwappedPredicate () const
For example, EQ->EQ, SLE->SGE, ULT->UGT, OEQ->OEQ, ULE->UGE, OLT->OGT, etc.
bool isStrictPredicate () const
bool isNonStrictPredicate () const
Predicate getStrictPredicate () const
For example, SGE -> SGT, SLE -> SLT, ULE -> ULT, UGE -> UGT.
Predicate getNonStrictPredicate () const
For example, SGT -> SGE, SLT -> SLE, ULT -> ULE, UGT -> UGE.
Predicate getFlippedStrictnessPredicate () const
For predicate of kind "is X or equal to 0" returns the predicate "is X".
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide more efficient getOperand methods.
void swapOperands ()
This is just a convenience that dispatches to the subclasses.
bool isCommutative () const
This is just a convenience that dispatches to the subclasses.
bool isEquality () const
Determine if this is an equals/not equals predicate.
bool isRelational () const
Return true if the predicate is relational (not EQ or NE).
bool isSigned () const
bool isUnsigned () const
Predicate getSignedPredicate ()
For example, ULT->SLT, ULE->SLE, UGT->SGT, UGE->SGE, SLT->Failed assert.
Predicate getUnsignedPredicate ()
For example, SLT->ULT, SLE->ULE, SGT->UGT, SGE->UGE, ULT->Failed assert.
Predicate getFlippedSignednessPredicate ()
For example, SLT->ULT, ULT->SLT, SLE->ULE, ULE->SLE, EQ->Failed assert.
bool isTrueWhenEqual () const
This is just a convenience.
bool isFalseWhenEqual () const
This is just a convenience.
Public Member Functions inherited from llvm::Instruction
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
Instruction * user_back ()
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
const Instruction * user_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
const Module * getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Module * getModule ()
const Function * getFunction () const
Return the function this instruction belongs to.
Function * getFunction ()
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
SymbolTableList< Instruction >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
void insertBefore (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
void insertAfter (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
SymbolTableList< Instruction >::iterator insertInto (BasicBlock *ParentBB, SymbolTableList< Instruction >::iterator It)
Inserts an unlinked instruction into ParentBB at position It and returns the iterator of the inserted instruction.
void moveBefore (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
void moveBefore (BasicBlock &BB, SymbolTableList< Instruction >::iterator I)
Unlink this instruction and insert into BB before I.
void moveAfter (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
bool comesBefore (const Instruction *Other) const
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
Instruction * getInsertionPointAfterDef ()
Get the first insertion point at which the result of this instruction is defined.
unsigned getOpcode () const
Returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isExceptionalTerminator () const
bool isOnlyUserOfAnyOperand ()
It checks if this instruction is the only user of at least one of its operands.
bool isLogicalShift () const
Return true if this is a logical shift left or a logical shift right.
bool isArithmeticShift () const
Return true if this is an arithmetic shift right.
bool isBitwiseLogicOp () const
Return true if this is and/or/xor.
bool hasMetadata () const
Return true if this instruction has any metadata attached to it.
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
Return true if this instruction has the given type of metadata attached.
MDNode * getMetadata (unsigned KindID) const
Get the metadata of given kind attached to this Instruction.
MDNode * getMetadata (StringRef Kind) const
Get the metadata of given kind attached to this Instruction.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Get all metadata attached to this Instruction.
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
This does the same thing as getAllMetadata, except that it filters out the debug location.
void setMetadata (unsigned KindID, MDNode *Node)
Set the metadata of the specified kind to the specified node.
void setMetadata (StringRef Kind, MDNode *Node)
void copyMetadata (const Instruction &SrcInst, ArrayRef< unsigned > WL=ArrayRef< unsigned >())
Copy metadata from SrcInst to this instruction.
void swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
void addAnnotationMetadata (StringRef Annotation)
Adds an !annotation metadata node with Annotation to this instruction.
AAMDNodes getAAMetadata () const
Returns the AA metadata for this instruction.
void setAAMetadata (const AAMDNodes &N)
Sets the AA metadata on this instruction from the AAMDNodes structure.
bool extractProfTotalWeight (uint64_t &TotalVal) const
Retrieve total raw weight values of a branch.
void setDebugLoc (DebugLoc Loc)
Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
Return the debug location for this node as a DebugLoc.
void setHasNoUnsignedWrap (bool b=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedWrap (bool b=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
void setIsExact (bool b=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
bool hasNoUnsignedWrap () const LLVM_READONLY
Determine whether the no unsigned wrap flag is set.
bool hasNoSignedWrap () const LLVM_READONLY
Determine whether the no signed wrap flag is set.
bool hasPoisonGeneratingFlags () const LLVM_READONLY
Return true if this operator has flags which may cause this instruction to evaluate to poison despite having non-poison inputs.
void dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
bool hasPoisonGeneratingMetadata () const LLVM_READONLY
Return true if this instruction has poison-generating metadata.
void dropPoisonGeneratingMetadata ()
Drops metadata that may generate poison.
bool hasPoisonGeneratingFlagsOrMetadata () const
Return true if this instruction has poison-generating flags or metadata.
void dropPoisonGeneratingFlagsAndMetadata ()
Drops flags and metadata that may generate poison.
void dropUndefImplyingAttrsAndUnknownMetadata (ArrayRef< unsigned > KnownIDs={})
This function drops non-debug unknown metadata (through dropUnknownNonDebugMetadata).
bool isExact () const LLVM_READONLY
Determine whether the exact flag is set.
void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
void setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
bool isFast () const LLVM_READONLY
Determine whether all fast-math-flags are set.
bool hasAllowReassoc () const LLVM_READONLY
Determine whether the allow-reassociation flag is set.
bool hasNoNaNs () const LLVM_READONLY
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const LLVM_READONLY
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const LLVM_READONLY
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const LLVM_READONLY
Determine whether the allow-reciprocal flag is set.
bool hasAllowContract () const LLVM_READONLY
Determine whether the allow-contract flag is set.
bool hasApproxFunc () const LLVM_READONLY
Determine whether the approximate-math-functions flag is set.
FastMathFlags getFastMathFlags () const LLVM_READONLY
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
void copyIRFlags (const Value *V, bool IncludeWrapFlags=true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
void andIRFlags (const Value *V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
void applyMergedLocation (const DILocation *LocA, const DILocation *LocB)
Merge 2 debug locations and apply it to the Instruction.
void updateLocationAfterHoist ()
Updates the debug location given that the instruction has been hoisted from a block to a predecessor of that block.
void dropLocation ()
Drop the instruction's debug location.
void mergeDIAssignID (ArrayRef< const Instruction * > SourceInstructions)
Merge the DIAssignID metadata from this instruction and those attached to instructions in SourceInstructions.
bool isAssociative () const LLVM_READONLY
Return true if the instruction is associative:
bool isCommutative () const LLVM_READONLY
Return true if the instruction is commutative:
bool isIdempotent () const
Return true if the instruction is idempotent:
bool isNilpotent () const
Return true if the instruction is nilpotent:
bool mayWriteToMemory () const LLVM_READONLY
Return true if this instruction may modify memory.
bool mayReadFromMemory () const LLVM_READONLY
Return true if this instruction may read memory.
bool mayReadOrWriteMemory () const
Return true if this instruction may read or write memory.
bool isAtomic () const LLVM_READONLY
Return true if this instruction has an AtomicOrdering of unordered or higher.
bool hasAtomicLoad () const LLVM_READONLY
Return true if this atomic instruction loads from memory.
bool hasAtomicStore () const LLVM_READONLY
Return true if this atomic instruction stores to memory.
bool isVolatile () const LLVM_READONLY
Return true if this instruction has a volatile memory access.
bool mayThrow () const LLVM_READONLY
Return true if this instruction may throw an exception.
bool isFenceLike () const
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
bool mayHaveSideEffects () const LLVM_READONLY
Return true if the instruction may have side effects.
bool isSafeToRemove () const LLVM_READONLY
Return true if the instruction can be removed if the result is unused.
bool willReturn () const LLVM_READONLY
Return true if the instruction will return (unwinding is considered as a form of returning control flow here).
bool isEHPad () const
Return true if the instruction is a variety of EH-block.
bool isLifetimeStartOrEnd () const LLVM_READONLY
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
bool isLaunderOrStripInvariantGroup () const LLVM_READONLY
Return true if the instruction is a llvm.launder.invariant.group or llvm.strip.invariant.group.
bool isDebugOrPseudoInst () const LLVM_READONLY
Return true if the instruction is a DbgInfoIntrinsic or PseudoProbeInst.
const Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the next non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false)
const Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the previous non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false)
Instruction * clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
bool isIdenticalTo (const Instruction *I) const LLVM_READONLY
Return true if the specified instruction is exactly identical to the current one.
bool isIdenticalToWhenDefined (const Instruction *I) const LLVM_READONLY
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const LLVM_READONLY
This function determines if the specified instruction executes the same operation as the current one.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const LLVM_READONLY
Return true if there are any uses of this instruction in blocks other than the specified block.
unsigned getNumSuccessors () const LLVM_READONLY
Return the number of successors that this instruction has.
BasicBlock * getSuccessor (unsigned Idx) const LLVM_READONLY
Return the specified successor. This instruction must be a terminator.
void setSuccessor (unsigned Idx, BasicBlock *BB)
Update the specified successor to point at the provided block.
void replaceSuccessorWith (BasicBlock *OldBB, BasicBlock *NewBB)
Replace specified successor OldBB to point at the provided block.
void dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs)
Drop all unknown metadata except for debug locations.
void dropUnknownNonDebugMetadata ()
void dropUnknownNonDebugMetadata (unsigned ID1)
void dropUnknownNonDebugMetadata (unsigned ID1, unsigned ID2)
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
Instruction * getPrevNode ()
const Instruction * getPrevNode () const
Get the previous node, or nullptr for the list head.
Instruction * getNextNode ()
Get the next node, or nullptr for the list tail.
const Instruction * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static Predicate getSignedPredicate (Predicate pred)
This is a static version that you can use without an instruction.
static Predicate getUnsignedPredicate (Predicate pred)
This is a static version that you can use without an instruction.
static bool isEquality (Predicate P)
Return true if this predicate is either EQ or NE.
static bool isRelational (Predicate P)
Return true if the predicate is relational (not EQ or NE).
static bool isGT (Predicate P)
Return true if the predicate is SGT or UGT.
static bool isLT (Predicate P)
Return true if the predicate is SLT or ULT.
static bool isGE (Predicate P)
Return true if the predicate is SGE or UGE.
static bool isLE (Predicate P)
Return true if the predicate is SLE or ULE.
static auto predicates ()
Returns the sequence of all ICmp predicates.
static bool compare (const APInt &LHS, const APInt &RHS, ICmpInst::Predicate Pred)
Return result of LHS Pred RHS comparison.
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::CmpInst
static auto FCmpPredicates ()
Returns the sequence of all FCmp predicates.
static auto ICmpPredicates ()
Returns the sequence of all ICmp predicates.
static CmpInst * Create (OtherOps Op, Predicate predicate, Value *S1, Value *S2, const Twine &Name="", Instruction *InsertBefore=nullptr)
Construct a compare instruction, given the opcode, the predicate and the two operands.
static CmpInst * Create (OtherOps Op, Predicate predicate, Value *S1, Value *S2, const Twine &Name, BasicBlock *InsertAtEnd)
Construct a compare instruction, given the opcode, the predicate and the two operands.
static bool isFPPredicate (Predicate P)
static bool isIntPredicate (Predicate P)
static StringRef getPredicateName (Predicate P)
static Predicate getOrderedPredicate (Predicate Pred)
Returns the ordered variant of a floating point compare.
static Predicate getInversePredicate (Predicate pred)
For example, EQ -> NE, UGT -> ULE, SLT -> SGE, OEQ -> UNE, UGT -> OLE, OLT -> UGE, etc.
static Predicate getSwappedPredicate (Predicate pred)
This is a static version that you can use without an instruction available.
static bool isStrictPredicate (Predicate predicate)
This is a static version that you can use without an instruction available.
static bool isNonStrictPredicate (Predicate predicate)
This is a static version that you can use without an instruction available.
static Predicate getStrictPredicate (Predicate pred)
This is a static version that you can use without an instruction available.
static Predicate getNonStrictPredicate (Predicate pred)
This is a static version that you can use without an instruction available.
static Predicate getFlippedStrictnessPredicate (Predicate pred)
This is a static version that you can use without an instruction available.
static bool isEquality (Predicate pred)
Determine if this is an equals/not equals predicate.
static bool isRelational (Predicate P)
Return true if the predicate is relational (not EQ or NE).
static Predicate getSignedPredicate (Predicate pred)
For example, ULT->SLT, ULE->SLE, UGT->SGT, UGE->SGE, SLT->Failed assert.
static Predicate getUnsignedPredicate (Predicate pred)
For example, SLT->ULT, SLE->ULE, SGT->UGT, SGE->UGE, ULT->Failed assert.
static Predicate getFlippedSignednessPredicate (Predicate pred)
For example, SLT->ULT, ULT->SLT, SLE->ULE, ULE->SLE, EQ->Failed assert.
static bool isUnsigned (Predicate predicate)
static bool isSigned (Predicate predicate)
static bool isOrdered (Predicate predicate)
Determine if the predicate is an ordered operation.
static bool isUnordered (Predicate predicate)
Determine if the predicate is an unordered operation.
static bool isTrueWhenEqual (Predicate predicate)
Determine if the predicate is true when comparing a value with itself.
static bool isFalseWhenEqual (Predicate predicate)
Determine if the predicate is false when comparing a value with itself.
static bool isImpliedTrueByMatchingCmp (Predicate Pred1, Predicate Pred2)
Determine if Pred1 implies Pred2 is true when two compares have matching operands.
static bool isImpliedFalseByMatchingCmp (Predicate Pred1, Predicate Pred2)
Determine if Pred1 implies Pred2 is false when two compares have matching operands.
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
static Type * makeCmpResultType (Type *opnd_type)
Create a result type for fcmp/icmp.
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isUnaryOp (unsigned Opcode)
static bool isBinaryOp (unsigned Opcode)
static bool isIntDivRem (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isBitwiseLogicOp (unsigned Opcode)
Determine if the Opcode is and/or/xor.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isFuncletPad (unsigned OpCode)
Determine if the OpCode is one of the FuncletPadInst instructions.
static bool isExceptionalTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator related to exception handling.
static bool isAssociative (unsigned Opcode)
static bool isCommutative (unsigned Opcode)
static bool isIdempotent (unsigned Opcode)
static bool isNilpotent (unsigned Opcode)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Member Functions
ICmpInst * cloneImpl () const
Clone an identical ICmpInst.
Protected Member Functions inherited from llvm::CmpInst
CmpInst (Type *ty, Instruction::OtherOps op, Predicate pred, Value *LHS, Value *RHS, const Twine &Name="", Instruction *InsertBefore=nullptr, Instruction *FlagsSource=nullptr)
CmpInst (Type *ty, Instruction::OtherOps op, Predicate pred, Value *LHS, Value *RHS, const Twine &Name, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::Instruction
~Instruction ()
template<typename BitfieldElement >
BitfieldElement::Type getSubclassData () const
template<typename BitfieldElement >
void setSubclassData (typename BitfieldElement::Type Value)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Protected Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Friends
class Instruction
Additional Inherited Members
Public Types inherited from llvm::CmpInst
enum Predicate : unsigned {
FCMP_FALSE = 0 , FCMP_OEQ = 1 , FCMP_OGT = 2 , FCMP_OGE = 3 ,
FCMP_OLT = 4 , FCMP_OLE = 5 , FCMP_ONE = 6 , FCMP_ORD = 7 ,
FCMP_UNO = 8 , FCMP_UEQ = 9 , FCMP_UGT = 10 , FCMP_UGE = 11 ,
FCMP_ULT = 12 , FCMP_ULE = 13 , FCMP_UNE = 14 , FCMP_TRUE = 15 ,
FIRST_FCMP_PREDICATE = FCMP_FALSE , LAST_FCMP_PREDICATE = FCMP_TRUE , BAD_FCMP_PREDICATE = FCMP_TRUE + 1 , ICMP_EQ = 32 ,
ICMP_NE = 33 , ICMP_UGT = 34 , ICMP_UGE = 35 , ICMP_ULT = 36 ,
ICMP_ULE = 37 , ICMP_SGT = 38 , ICMP_SGE = 39 , ICMP_SLT = 40 ,
ICMP_SLE = 41 , FIRST_ICMP_PREDICATE = ICMP_EQ , LAST_ICMP_PREDICATE = ICMP_SLE , BAD_ICMP_PREDICATE = ICMP_SLE + 1
}
This enumeration lists the possible predicates for CmpInst subclasses.
using PredicateField
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0 , CompareUsingScalarTypes = 1<<1 }
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
enum TermOps
enum UnaryOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum FuncletPadOps
enum OtherOps
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::Instruction
using OpaqueField = Bitfield::Element<uint16_t, 0, 15>
template<unsigned Offset>
using AlignmentBitfieldElementT
template<unsigned Offset>
using BoolBitfieldElementT = typename Bitfield::Element<bool, Offset, 1>
template<unsigned Offset>
using AtomicOrderingBitfieldElementT
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
This instruction compares its operands according to the predicate given to the constructor.
It only operates on integers or pointers. The operands must be identical types. Represent an integer comparison operator.
Definition at line 1197 of file Instructions.h.
Constructor & Destructor Documentation
ICmpInst() [1/3]
llvm::ICmpInst::ICmpInst (Instruction * InsertBefore, Predicate pred, Value * LHS, Value * RHS, const Twine & NameStr = "") inline
Constructor with insert-before-instruction semantics.
Parameters
InsertBefore Where to insert
pred The predicate to use for the comparison
LHS The left-hand-side of the expression
RHS The right-hand-side of the expression
NameStr Name of the instruction
Definition at line 1218 of file Instructions.h.
Referenced by cloneImpl().
ICmpInst() [2/3]
llvm::ICmpInst::ICmpInst (BasicBlock & InsertAtEnd, Predicate pred, Value * LHS, Value * RHS, const Twine & NameStr = "") inline
Constructor with insert-at-end semantics.
Parameters
InsertAtEnd Block to insert into.
pred The predicate to use for the comparison
LHS The left-hand-side of the expression
RHS The right-hand-side of the expression
NameStr Name of the instruction
Definition at line 1233 of file Instructions.h.
ICmpInst() [3/3]
llvm::ICmpInst::ICmpInst (Predicate pred, Value * LHS, Value * RHS, const Twine & NameStr = "") inline
Constructor with no-insertion semantics.
Parameters
pred The predicate to use for the comparison
LHS The left-hand-side of the expression
RHS The right-hand-side of the expression
NameStr Name of the instruction
Definition at line 1248 of file Instructions.h.
Member Function Documentation
classof() [1/2]
static bool llvm::ICmpInst::classof (const Instruction * I) inline static
Definition at line 1355 of file Instructions.h.
References I.
classof() [2/2]
static bool llvm::ICmpInst::classof (const Value * V) inline static
Definition at line 1358 of file Instructions.h.
cloneImpl()
ICmpInst * ICmpInst::cloneImpl () const protected
Clone an identical ICmpInst.
Definition at line 4809 of file Instructions.cpp.
References llvm::CmpInst::getPredicate(), and ICmpInst().
compare()
bool ICmpInst::compare (const APInt & LHS, const APInt & RHS, ICmpInst::Predicate Pred) static
Return result of LHS Pred RHS comparison.
Definition at line 4336 of file Instructions.cpp.
References assert(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::CmpInst::isIntPredicate(), and llvm_unreachable.
Referenced by computePointerICmp(), llvm::ConstantFoldCompareInstruction(), llvm::SelectionDAG::FoldSetCC(), llvm::PatternMatch::icmp_pred_with_threshold::isValue(), and simplifyBinaryIntrinsic().
getSignedPredicate() [1/2]
Predicate llvm::ICmpInst::getSignedPredicate () const inline
For example, EQ->EQ, SLE->SLE, UGT->SGT, etc.
Returns
the predicate that would be the result if the operand were regarded as signed. Return the signed version of the predicate
Definition at line 1264 of file Instructions.h.
Referenced by computePointerICmp(), llvm::ConstantFoldCompareInstOperands(), llvm::InstCombinerImpl::foldGEPICmp(), llvm::InstCombinerImpl::foldICmpBinOp(), foldICmpXNegX(), llvm::InstCombinerImpl::insertRangeTest(), and transformToIndexedCompare().
getSignedPredicate() [2/2]
ICmpInst::Predicate ICmpInst::getSignedPredicate (Predicate pred) static
This is a static version that you can use without an instruction.
Return the signed version of the predicate.
Definition at line 4141 of file Instructions.cpp.
References llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm_unreachable, and pred.
getUnsignedPredicate() [1/2]
Predicate llvm::ICmpInst::getUnsignedPredicate () const inline
For example, EQ->EQ, SLE->ULE, UGT->UGT, etc.
Returns
the predicate that would be the result if the operand were regarded as unsigned. Return the unsigned version of the predicate
Definition at line 1276 of file Instructions.h.
Referenced by llvm::InstCombinerImpl::foldICmpWithZextOrSext(), llvm::InstCombiner::getFlippedStrictnessPredicateAndConstant(), llvm::LegalizerHelper::narrowScalar(), simplifyAndOrOfICmpsWithLimitConst(), and simplifyICmpInst().
getUnsignedPredicate() [2/2]
ICmpInst::Predicate ICmpInst::getUnsignedPredicate (Predicate pred) static
This is a static version that you can use without an instruction.
Return the unsigned version of the predicate.
Definition at line 4154 of file Instructions.cpp.
References llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm_unreachable, and pred.
isCommutative()
bool llvm::ICmpInst::isCommutative () const inline
Returns
true if the predicate of this ICmpInst is commutative Determine if this relation is commutative.
Definition at line 1298 of file Instructions.h.
isEquality() [1/2]
bool llvm::ICmpInst::isEquality () const inline
Return true if this predicate is either EQ or NE.
This also tests for commutativity.
Definition at line 1292 of file Instructions.h.
Referenced by canonicalizeCmpWithConstant(), computePointerICmp(), llvm::ConstantFoldCompareInstruction(), countToEliminateCompares(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), llvm::InstCombinerImpl::foldGEPICmp(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpWithZero(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmpsAsymmetric(), foldReductionIdiom(), foldSelectBinOpIdentity(), foldSelectICmpAnd(), llvm::InstCombinerImpl::foldSelectOpOp(), foldSelectZeroOrMul(), foldUnsignedUnderflowCheck(), llvm::ValueLatticeElement::getCompare(), getMaskedTypeForICmpPair(), llvm::CmpInst::isEquality(), matchICmpRedundantTrunc(), llvm::InstCombinerImpl::matchThreeWayIntCompare(), llvm::LegalizerHelper::narrowScalar(), normalizePredicate(), llvm::predicatesFoldable(), simplifyAndOrOfICmpsWithLimitConst(), simplifyICmpInst(), llvm::ScalarEvolution::SimplifyICmpOperands(), simplifyICmpWithBinOp(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithConstant(), and simplifyUnsignedRangeCheck().
isEquality() [2/2]
static bool llvm::ICmpInst::isEquality (Predicate P) inline static
Return true if this predicate is either EQ or NE.
This also tests for commutativity.
Definition at line 1286 of file Instructions.h.
References P.
Referenced by llvm::InstCombinerImpl::foldAllocaCmp(), llvm::InstCombinerImpl::foldICmpWithZextOrSext(), foldSelectICmpAndOr(), getValueFromICmpCondition(), isAllocSiteRemovable(), and simplifyAndOrOfICmpsWithLimitConst().
isGE()
static bool llvm::ICmpInst::isGE (Predicate P) inline static
Return true if the predicate is SGE or UGE.
Definition at line 1326 of file Instructions.h.
References P.
isGT()
static bool llvm::ICmpInst::isGT (Predicate P) inline static
Return true if the predicate is SGT or UGT.
Definition at line 1314 of file Instructions.h.
References P.
isLE()
static bool llvm::ICmpInst::isLE (Predicate P) inline static
Return true if the predicate is SLE or ULE.
Definition at line 1332 of file Instructions.h.
References P.
isLT()
static bool llvm::ICmpInst::isLT (Predicate P) inline static
Return true if the predicate is SLT or ULT.
Definition at line 1320 of file Instructions.h.
References P.
isRelational() [1/2]
bool llvm::ICmpInst::isRelational () const inline
Return true if the predicate is relational (not EQ or NE).
Definition at line 1302 of file Instructions.h.
Referenced by llvm::InstCombiner::getFlippedStrictnessPredicateAndConstant(), llvm::ScalarEvolution::getLoopInvariantExitCondDuringFirstIterationsImpl(), IsKnownPredicateViaAddRecStart(), and isSignTest().
isRelational() [2/2]
static bool llvm::ICmpInst::isRelational (Predicate P) inline static
Return true if the predicate is relational (not EQ or NE).
Definition at line 1308 of file Instructions.h.
References P.
predicates()
static auto llvm::ICmpInst::predicates () inline static
Returns the sequence of all ICmp predicates.
Definition at line 1338 of file Instructions.h.
swapOperands()
void llvm::ICmpInst::swapOperands () inline
Exchange the two operands to this instruction in such a way that it does not modify the semantics of the instruction.
The predicate value may be changed to retain the same result if the predicate is order dependent (e.g. ult). Swap operands and adjust predicate.
Definition at line 1345 of file Instructions.h.
Friends And Related Symbol Documentation
Instruction
friend class Instruction friend
Definition at line 1211 of file Instructions.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Instructions.h
lib/IR/Instructions.cpp