LLVM: llvm::IntervalTree< PointT, ValueT, DataT > Class Template Reference
llvm::IntervalTree< PointT, ValueT, DataT > Class Template Reference
#include "llvm/ADT/IntervalTree.h"
Classes
class find_iterator
Public Types
enum class Sorting { Ascending , Descending }
using PointType = PointT
using ValueType = ValueT
using DataType = DataT
using Allocator = BumpPtrAllocator
using IntervalReferences = SmallVector<const DataType *, 4>
Public Member Functions
IntervalTree (Allocator &NodeAllocator)
~IntervalTree ()
bool empty () const
Return true when no intervals are mapped.
void clear ()
Remove all entries.
void insert (PointType Left, PointType Right, ValueType Value)
Add a mapping of [Left;Right] to Value.
IntervalReferences getContaining (PointType Point) const
Return all the intervals in their natural tree location, that contain the given point.
void print (raw_ostream &OS, bool HexFormat=true)
Print the interval tree.
void create ()
Create the interval tree.
find_iterator find (PointType Point) const
Iterator to start a find operation; it returns find_end() if the tree has not been built.
find_iterator find_end () const
Iterator to end find operation.
Static Public Member Functions
static void sortIntervals (IntervalReferences &IntervalSet, Sorting Sort)
Sort the given intervals using the following sort options: Ascending: return the intervals with the smallest at the front.
Detailed Description
template<typename PointT, typename ValueT, typename DataT = IntervalData<PointT, ValueT>>
class llvm::IntervalTree< PointT, ValueT, DataT >
Definition at line 249 of file IntervalTree.h.
Member Typedef Documentation
Allocator
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> using llvm::IntervalTree< PointT, ValueT, DataT >::Allocator = BumpPtrAllocator
Definition at line 259 of file IntervalTree.h.
DataType
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> using llvm::IntervalTree< PointT, ValueT, DataT >::DataType = DataT
Definition at line 258 of file IntervalTree.h.
IntervalReferences
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> using llvm::IntervalTree< PointT, ValueT, DataT >::IntervalReferences = SmallVector<const DataType *, 4>
Definition at line 262 of file IntervalTree.h.
PointType
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> using llvm::IntervalTree< PointT, ValueT, DataT >::PointType = PointT
Definition at line 256 of file IntervalTree.h.
ValueType
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> using llvm::IntervalTree< PointT, ValueT, DataT >::ValueType = ValueT
Definition at line 257 of file IntervalTree.h.
Member Enumeration Documentation
Sorting
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> enum class llvm::IntervalTree::Sorting strong
Enumerator
Ascending
Descending
Definition at line 261 of file IntervalTree.h.
Constructor & Destructor Documentation
IntervalTree()
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> llvm::IntervalTree< PointT, ValueT, DataT >::IntervalTree (Allocator & NodeAllocator) inline explicit
Definition at line 592 of file IntervalTree.h.
~IntervalTree()
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> llvm::IntervalTree< PointT, ValueT, DataT >::~IntervalTree () inline
Definition at line 594 of file IntervalTree.h.
References llvm::IntervalTree< PointT, ValueT, DataT >::clear().
Member Function Documentation
clear()
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> void llvm::IntervalTree< PointT, ValueT, DataT >::clear () inline
Remove all entries.
Definition at line 600 of file IntervalTree.h.
Referenced by llvm::logicalview::LVRange::startSearch(), and llvm::IntervalTree< PointT, ValueT, DataT >::~IntervalTree().
create()
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> void llvm::IntervalTree< PointT, ValueT, DataT >::create () inline
Create the interval tree.
Definition at line 647 of file IntervalTree.h.
References assert(), llvm::Data, llvm::IntervalTree< PointT, ValueT, DataT >::empty(), and llvm::Last.
Referenced by llvm::logicalview::LVRange::startSearch().
empty()
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> bool llvm::IntervalTree< PointT, ValueT, DataT >::empty () const inline
Return true when no intervals are mapped.
Definition at line 597 of file IntervalTree.h.
Referenced by llvm::IntervalTree< PointT, ValueT, DataT >::create(), llvm::IntervalTree< PointT, ValueT, DataT >::find(), llvm::IntervalTree< PointT, ValueT, DataT >::getContaining(), and llvm::IntervalTree< PointT, ValueT, DataT >::insert().
find()
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> find_iterator llvm::IntervalTree< PointT, ValueT, DataT >::find (PointType Point) const inline
Iterator to start a find operation; it returns find_end() if the tree has not been built.
There is no support to iterate over all the elements of the tree.
Definition at line 681 of file IntervalTree.h.
References llvm::IntervalTree< PointT, ValueT, DataT >::empty(), and llvm::IntervalTree< PointT, ValueT, DataT >::find_end().
Referenced by llvm::IntervalTree< PointT, ValueT, DataT >::getContaining(), and llvm::logicalview::LVRange::getEntry().
find_end()
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> find_iterator llvm::IntervalTree< PointT, ValueT, DataT >::find_end () const inline
Iterator to end find operation.
Definition at line 688 of file IntervalTree.h.
Referenced by llvm::IntervalTree< PointT, ValueT, DataT >::find(), llvm::IntervalTree< PointT, ValueT, DataT >::getContaining(), and llvm::logicalview::LVRange::getEntry().
getContaining()
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> IntervalReferences llvm::IntervalTree< PointT, ValueT, DataT >::getContaining (PointType Point) const inline
Return all the intervals in their natural tree location, that contain the given point.
Definition at line 617 of file IntervalTree.h.
References assert(), E, llvm::IntervalTree< PointT, ValueT, DataT >::empty(), llvm::IntervalTree< PointT, ValueT, DataT >::find(), and llvm::IntervalTree< PointT, ValueT, DataT >::find_end().
insert()
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> void llvm::IntervalTree< PointT, ValueT, DataT >::insert (PointType Left, PointType Right, ValueType Value) inline
Add a mapping of [Left;Right] to Value.
Definition at line 610 of file IntervalTree.h.
References assert(), llvm::IntervalTree< PointT, ValueT, DataT >::empty(), llvm::Left, and llvm::Right.
Referenced by llvm::logicalview::LVRange::startSearch().
print()
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> void llvm::IntervalTree< PointT, ValueT, DataT >::print (raw_ostream & OS, bool HexFormat = true) inline
Print the interval tree.
When HexFormat is true, the interval tree interval ranges and associated values are printed in hexadecimal format.
Definition at line 642 of file IntervalTree.h.
Referenced by llvm::logicalview::LVRange::startSearch().
sortIntervals()
template<typename PointT , typename ValueT , typename DataT = IntervalData<PointT, ValueT>> static void llvm::IntervalTree< PointT, ValueT, DataT >::sortIntervals (IntervalReferences & IntervalSet, Sorting Sort) inline static
Sort the given intervals using the following sort options: Ascending: return the intervals with the smallest at the front.
Descending: return the intervals with the biggest at the front.
Definition at line 628 of file IntervalTree.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/IntervalTree.h