LLVM: llvm::logicalview::LVScopeFunctionInlined Class Reference
llvm::logicalview::LVScopeFunctionInlined Class Reference final
#include "llvm/DebugInfo/LogicalView/Core/LVScope.h"
Public Member Functions
LVScopeFunctionInlined ()
LVScopeFunctionInlined (const LVScopeFunctionInlined &)=delete
LVScopeFunctionInlined & operator= (const LVScopeFunctionInlined &)=delete
~LVScopeFunctionInlined ()=default
uint32_t getDiscriminator () const override
void setDiscriminator (uint32_t Value) override
uint32_t getCallLineNumber () const override
void setCallLineNumber (uint32_t Number) override
size_t getCallFilenameIndex () const override
void setCallFilenameIndex (size_t Index) override
std::string lineNumberAsString (bool ShowZero=false) const override
void resolveExtra () override
bool equals (const LVScope *Scope) const override
LVScope * findEqualScope (const LVScopes *Scopes) const override
void printExtra (raw_ostream &OS, bool Full=true) const override
Public Member Functions inherited from llvm::logicalview::LVScopeFunction
LVScopeFunction ()
LVScopeFunction (const LVScopeFunction &)=delete
LVScopeFunction & operator= (const LVScopeFunction &)=delete
virtual ~LVScopeFunction ()=default
LVScope * getReference () const override
void setReference (LVScope *Scope) override
void setReference (LVElement *Element) override
StringRef getEncodedArgs () const override
void setEncodedArgs (StringRef EncodedArgs) override
void setLinkageName (StringRef LinkageName) override
StringRef getLinkageName () const override
size_t getLinkageNameIndex () const override
void setName (StringRef ObjectName) override
void resolveReferences () override
Public Member Functions inherited from llvm::logicalview::LVScope
LVScope ()
LVScope (const LVScope &)=delete
LVScope & operator= (const LVScope &)=delete
virtual ~LVScope ()
KIND (LVScopeKind, IsAggregate)
KIND (LVScopeKind, IsArray)
KIND_2 (LVScopeKind, IsBlock, CanHaveRanges, CanHaveLines)
KIND_1 (LVScopeKind, IsCallSite, IsFunction)
KIND_1 (LVScopeKind, IsCatchBlock, IsBlock)
KIND_1 (LVScopeKind, IsClass, IsAggregate)
KIND_3 (LVScopeKind, IsCompileUnit, CanHaveRanges, CanHaveLines, TransformName)
KIND_1 (LVScopeKind, IsEntryPoint, IsFunction)
KIND (LVScopeKind, IsEnumeration)
KIND_2 (LVScopeKind, IsFunction, CanHaveRanges, CanHaveLines)
KIND_1 (LVScopeKind, IsFunctionType, IsFunction)
KIND_2 (LVScopeKind, IsInlinedFunction, IsFunction, IsInlined)
KIND_1 (LVScopeKind, IsLabel, IsFunction)
KIND_1 (LVScopeKind, IsLexicalBlock, IsBlock)
KIND (LVScopeKind, IsMember)
KIND (LVScopeKind, IsNamespace)
KIND_1 (LVScopeKind, IsRoot, TransformName)
KIND_1 (LVScopeKind, IsStructure, IsAggregate)
KIND_1 (LVScopeKind, IsSubprogram, IsFunction)
KIND (LVScopeKind, IsTemplate)
KIND (LVScopeKind, IsTemplateAlias)
KIND (LVScopeKind, IsTemplatePack)
KIND_1 (LVScopeKind, IsTryBlock, IsBlock)
KIND_1 (LVScopeKind, IsUnion, IsAggregate)
PROPERTY (Property, HasDiscriminator)
PROPERTY (Property, CanHaveRanges)
PROPERTY (Property, CanHaveLines)
PROPERTY (Property, HasGlobals)
PROPERTY (Property, HasLocals)
PROPERTY (Property, HasLines)
PROPERTY (Property, HasScopes)
PROPERTY (Property, HasSymbols)
PROPERTY (Property, HasTypes)
PROPERTY (Property, IsComdat)
PROPERTY (Property, HasComdatScopes)
PROPERTY (Property, HasRanges)
PROPERTY (Property, AddedMissing)
bool isCompileUnit () const override
bool isRoot () const override
const char * kind () const override
const LVLines * getLines () const
const LVLocations * getRanges () const
const LVScopes * getScopes () const
const LVSymbols * getSymbols () const
const LVTypes * getTypes () const
const LVElements * getChildren () const
void addElement (LVElement *Element)
void addElement (LVLine *Line)
void addElement (LVScope *Scope)
void addElement (LVSymbol *Symbol)
void addElement (LVType *Type)
void addObject (LVLocation *Location)
void addObject (LVAddress LowerAddress, LVAddress UpperAddress)
void addToChildren (LVElement *Element)
void addMissingElements (LVScope *Reference)
void traverseParentsAndChildren (LVObjectGetFunction GetFunction, LVObjectSetFunction SetFunction)
size_t lineCount () const
size_t rangeCount () const
size_t scopeCount () const
size_t symbolCount () const
size_t typeCount () const
LVScope * outermostParent (LVAddress Address)
void getLocations (LVLocations &LocationList, LVValidLocation ValidLocation, bool RecordInvalid=false)
void getRanges (LVLocations &LocationList, LVValidLocation ValidLocation, bool RecordInvalid=false)
void getRanges (LVRange &RangeList)
unsigned getCoverageFactor () const
Error doPrint (bool Split, bool Match, bool Print, raw_ostream &OS, bool Full=true) const override
void sort ()
bool getTemplateParameterTypes (LVTypes &Params)
LVScope * getCompileUnitParent () const override
StringRef resolveReferencesChain ()
bool removeElement (LVElement *Element) override
void updateLevel (LVScope *Parent, bool Moved) override
void resolve () override
void resolveName () override
void getQualifiedName (std::string &QualifiedName) const
void encodeTemplateArguments (std::string &Name) const
void encodeTemplateArguments (std::string &Name, const LVTypes *Types) const
void resolveElements ()
virtual void markMissingParents (const LVScope *Target, bool TraverseChildren)
virtual bool equalNumberOfChildren (const LVScope *Scope) const
void report (LVComparePass Pass) override
void print (raw_ostream &OS, bool Full=true) const override
virtual void printWarnings (raw_ostream &OS, bool Full=true) const
virtual void printMatchedElements (raw_ostream &OS, bool UseMatchedElements)
void dump () const override
Public Member Functions inherited from llvm::logicalview::LVElement
LVElement (LVSubclassID ID)
LVElement (const LVElement &)=delete
LVElement & operator= (const LVElement &)=delete
virtual ~LVElement ()=default
LVSubclassID getSubclassID () const
PROPERTY (Property, IsLine)
PROPERTY (Property, IsScope)
PROPERTY (Property, IsSymbol)
PROPERTY (Property, IsType)
PROPERTY (Property, IsEnumClass)
PROPERTY (Property, IsExternal)
PROPERTY (Property, HasType)
PROPERTY (Property, HasAugmentedName)
PROPERTY (Property, IsTypedefReduced)
PROPERTY (Property, IsArrayResolved)
PROPERTY (Property, IsMemberPointerResolved)
PROPERTY (Property, IsTemplateResolved)
PROPERTY (Property, IsInlined)
PROPERTY (Property, IsInlinedAbstract)
PROPERTY (Property, InvalidFilename)
PROPERTY (Property, HasReference)
PROPERTY (Property, HasReferenceAbstract)
PROPERTY (Property, HasReferenceExtension)
PROPERTY (Property, HasReferenceSpecification)
PROPERTY (Property, QualifiedResolved)
PROPERTY (Property, IncludeInPrint)
PROPERTY (Property, IsStatic)
PROPERTY (Property, TransformName)
PROPERTY (Property, IsScoped)
PROPERTY (Property, IsNested)
PROPERTY (Property, IsScopedAlready)
PROPERTY (Property, IsArtificial)
PROPERTY (Property, IsReferencedType)
PROPERTY (Property, IsSystem)
PROPERTY (Property, OffsetFromTypeIndex)
PROPERTY (Property, IsAnonymous)
bool isNamed () const override
bool isTyped () const override
bool isFiled () const override
bool getIsKindType () const
bool getIsKindScope () const
StringRef getName () const override
StringRef getPathname () const
void setFilename (StringRef Filename)
void setQualifiedName (StringRef Name)
StringRef getQualifiedName () const
size_t getNameIndex () const
size_t getQualifiedNameIndex () const
StringRef getTypeName () const
virtual StringRef getProducer () const
virtual void setProducer (StringRef ProducerName)
virtual void setReference (LVSymbol *Symbol)
virtual void setReference (LVType *Type)
size_t getFilenameIndex () const
void setFilenameIndex (size_t Index)
void setFile (LVElement *Reference=nullptr)
virtual bool isBase () const
virtual bool isTemplateParam () const
virtual uint32_t getBitSize () const
virtual void setBitSize (uint32_t Size)
virtual int64_t getCount () const
virtual void setCount (int64_t Value)
virtual int64_t getLowerBound () const
virtual void setLowerBound (int64_t Value)
virtual int64_t getUpperBound () const
virtual void setUpperBound (int64_t Value)
virtual std::pair< unsigned, unsigned > getBounds () const
virtual void setBounds (unsigned Lower, unsigned Upper)
virtual std::string getValue () const
virtual void setValue (StringRef Value)
virtual size_t getValueIndex () const
uint32_t getAccessibilityCode () const
void setAccessibilityCode (uint32_t Access)
StringRef accessibilityString (uint32_t Access=dwarf::DW_ACCESS_private) const
uint32_t getInlineCode () const
void setInlineCode (uint32_t Code)
StringRef inlineCodeString (uint32_t Code) const
uint32_t getVirtualityCode () const
void setVirtualityCode (uint32_t Virtuality)
StringRef virtualityString (uint32_t Virtuality=dwarf::DW_VIRTUALITY_none) const
StringRef externalString () const
LVElement * getType () const
LVType * getTypeAsType () const
LVScope * getTypeAsScope () const
void setType (LVElement *Element=nullptr)
void setGenericType (LVElement *Element)
StringRef getTypeQualifiedName () const
StringRef typeAsString () const
std::string typeOffsetAsString () const
std::string discriminatorAsString () const
LVScope * traverseParents (LVScopeGetFunction GetFunction) const
LVScope * getFunctionParent () const
void printReference (raw_ostream &OS, bool Full, LVElement *Parent) const
void printLinkageName (raw_ostream &OS, bool Full, LVElement *Parent, LVScope *Scope) const
void printLinkageName (raw_ostream &OS, bool Full, LVElement *Parent) const
void resolveFullname (LVElement *BaseType, StringRef Name=emptyString())
void generateName (std::string &Prefix) const
void generateName ()
void resolveParents ()
bool referenceMatch (const LVElement *Element) const
bool equals (const LVElement *Element) const
Public Member Functions inherited from llvm::logicalview::LVObject
LVObject ()
LVObject & operator= (const LVObject &)=delete
virtual ~LVObject ()=default
PROPERTY (Property, IsLocation)
PROPERTY (Property, IsGlobalReference)
PROPERTY (Property, IsGeneratedName)
PROPERTY (Property, IsResolved)
PROPERTY (Property, IsResolvedName)
PROPERTY (Property, IsDiscarded)
PROPERTY (Property, IsOptimized)
PROPERTY (Property, IsAdded)
PROPERTY (Property, IsMatched)
PROPERTY (Property, IsMissing)
PROPERTY (Property, IsMissingLink)
PROPERTY (Property, IsInCompare)
PROPERTY (Property, IsFileFromReference)
PROPERTY (Property, IsLineFromReference)
PROPERTY (Property, HasMoved)
PROPERTY (Property, HasPattern)
PROPERTY (Property, IsFinalized)
PROPERTY (Property, IsReferenced)
PROPERTY (Property, HasCodeViewLocation)
bool isLined () const
dwarf::Tag getTag () const
void setTag (dwarf::Tag Tag)
dwarf::Attribute getAttr () const
void setAttr (dwarf::Attribute Attr)
LVSmall getOpcode () const
void setOpcode (LVSmall Opcode)
LVOffset getOffset () const
void setOffset (LVOffset DieOffset)
LVLevel getLevel () const
void setLevel (LVLevel Level)
LVElement * getParent () const
LVScope * getParentScope () const
LVSymbol * getParentSymbol () const
void setParent (LVScope *Scope)
void setParent (LVSymbol *Symbol)
void resetParent ()
virtual LVAddress getLowerAddress () const
virtual void setLowerAddress (LVAddress Address)
virtual LVAddress getUpperAddress () const
virtual void setUpperAddress (LVAddress Address)
uint32_t getLineNumber () const
void setLineNumber (uint32_t Number)
std::string indentAsString () const
std::string indentAsString (LVLevel Level) const
virtual std::string noLineAsString (bool ShowZero) const
std::string lineNumberAsStringStripped (bool ShowZero=false) const
void printAttributes (raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full, StringRef Name, LVObject *Parent, StringRef Value, bool UseQuotes=false, bool PrintRef=false) const
void markBranchAsMissing ()
uint64_t getID () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::logicalview::LVScope
static bool classof (const LVElement *Element)
static void markMissingParents (const LVScopes *References, const LVScopes *Targets, bool TraverseChildren)
static bool equals (const LVScopes *References, const LVScopes *Targets)
static LVScopeDispatch & getDispatch ()
Static Public Member Functions inherited from llvm::logicalview::LVElement
static LVElementDispatch & getDispatch ()
Protected Member Functions inherited from llvm::logicalview::LVScope
void resolveTemplate ()
void printEncodedArgs (raw_ostream &OS, bool Full) const
void printActiveRanges (raw_ostream &OS, bool Full=true) const
virtual void printSizes (raw_ostream &OS) const
virtual void printSummary (raw_ostream &OS) const
Protected Member Functions inherited from llvm::logicalview::LVElement
void printFileIndex (raw_ostream &OS, bool Full=true) const override
Protected Member Functions inherited from llvm::logicalview::LVObject
std::string lineAsString (uint32_t LineNumber, LVHalf Discriminator, bool ShowZero) const
std::string referenceAsString (uint32_t LineNumber, bool Spaces) const
Protected Attributes inherited from llvm::logicalview::LVScope
LVAutoTypes * Types = nullptr
LVAutoSymbols * Symbols = nullptr
LVAutoScopes * Scopes = nullptr
LVAutoLines * Lines = nullptr
LVAutoLocations * Ranges = nullptr
LVElements * Children = nullptr
Protected Attributes inherited from llvm::logicalview::LVElement
LVElement * ElementType = nullptr
Detailed Description
Definition at line 697 of file LVScope.h.
Constructor & Destructor Documentation
LVScopeFunctionInlined() [1/2]
llvm::logicalview::LVScopeFunctionInlined::LVScopeFunctionInlined () inline
Definition at line 703 of file LVScope.h.
LVScopeFunctionInlined() [2/2]
llvm::logicalview::LVScopeFunctionInlined::LVScopeFunctionInlined (const LVScopeFunctionInlined &) delete
~LVScopeFunctionInlined()
llvm::logicalview::LVScopeFunctionInlined::~LVScopeFunctionInlined () default
Member Function Documentation
equals()
bool LVScopeFunctionInlined::equals (const LVScope * Scope) const override virtual
Reimplemented from llvm::logicalview::LVScopeFunction.
Definition at line 1916 of file LVScope.cpp.
References llvm::logicalview::LVScopeFunction::equals(), getCallFilenameIndex(), getCallLineNumber(), and getDiscriminator().
findEqualScope()
LVScope * LVScopeFunctionInlined::findEqualScope (const LVScopes * Scopes) const override virtual
Reimplemented from llvm::logicalview::LVScopeFunction.
Definition at line 1933 of file LVScope.cpp.
References llvm::logicalview::LVScopeFunction::findEqualScope(), and llvm::logicalview::LVScope::Scopes.
getCallFilenameIndex()
size_t llvm::logicalview::LVScopeFunctionInlined::getCallFilenameIndex () const inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 716 of file LVScope.h.
Referenced by equals().
getCallLineNumber()
uint32_t llvm::logicalview::LVScopeFunctionInlined::getCallLineNumber () const inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 714 of file LVScope.h.
Referenced by equals(), and lineNumberAsString().
getDiscriminator()
uint32_t llvm::logicalview::LVScopeFunctionInlined::getDiscriminator () const inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 708 of file LVScope.h.
References llvm::logicalview::Discriminator.
Referenced by equals(), and lineNumberAsString().
lineNumberAsString()
std::string llvm::logicalview::LVScopeFunctionInlined::lineNumberAsString (bool ShowZero = false) const inline override virtual
Reimplemented from llvm::logicalview::LVObject.
Definition at line 723 of file LVScope.h.
References getCallLineNumber(), getDiscriminator(), and llvm::logicalview::LVObject::lineAsString().
operator=()
LVScopeFunctionInlined & llvm::logicalview::LVScopeFunctionInlined::operator= (const LVScopeFunctionInlined &) delete
printExtra()
void LVScopeFunctionInlined::printExtra (raw_ostream & OS, bool Full = true) const override virtual
Reimplemented from llvm::logicalview::LVScopeFunction.
Definition at line 1937 of file LVScope.cpp.
References llvm::Full, and llvm::logicalview::LVScopeFunction::printExtra().
resolveExtra()
void LVScopeFunctionInlined::resolveExtra () override virtual
Reimplemented from llvm::logicalview::LVScopeFunction.
Definition at line 1910 of file LVScope.cpp.
References llvm::logicalview::LVScope::resolveTemplate().
setCallFilenameIndex()
void llvm::logicalview::LVScopeFunctionInlined::setCallFilenameIndex (size_t Index) inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 717 of file LVScope.h.
setCallLineNumber()
void llvm::logicalview::LVScopeFunctionInlined::setCallLineNumber (uint32_t Number) inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 715 of file LVScope.h.
References llvm::Number.
setDiscriminator()
void llvm::logicalview::LVScopeFunctionInlined::setDiscriminator (uint32_t Value) inline override virtual
Reimplemented from llvm::logicalview::LVElement.
Definition at line 709 of file LVScope.h.
References llvm::logicalview::Discriminator.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVScope.h
lib/DebugInfo/LogicalView/Core/LVScope.cpp