LLVM: llvm::MCTargetAsmParser Class Reference
llvm::MCTargetAsmParser Class Reference abstract
MCTargetAsmParser - Generic interface to target specific assembly parsers.
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
Public Types
enum MatchResultTy {
Match_InvalidOperand , Match_InvalidTiedOperand , Match_MissingFeature , Match_MnemonicFail ,
Match_Success , Match_NearMisses , FIRST_TARGET_MATCH_RESULT_TY
}
Public Member Functions
MCTargetAsmParser (const MCTargetAsmParser &)=delete
MCTargetAsmParser & operator= (const MCTargetAsmParser &)=delete
~MCTargetAsmParser () override
const MCSubtargetInfo & getSTI () const
const FeatureBitset & getAvailableFeatures () const
void setAvailableFeatures (const FeatureBitset &Value)
bool isParsingMSInlineAsm ()
void setParsingMSInlineAsm (bool Value)
MCTargetOptions getTargetOptions () const
void setSemaCallback (MCAsmParserSemaCallback *Callback)
virtual bool parsePrimaryExpr (const MCExpr *&Res, SMLoc &EndLoc)
virtual bool parseRegister (MCRegister &Reg, SMLoc &StartLoc, SMLoc &EndLoc)=0
virtual OperandMatchResultTy tryParseRegister (MCRegister &Reg, SMLoc &StartLoc, SMLoc &EndLoc)=0
tryParseRegister - parse one register if possible
virtual bool ParseInstruction (ParseInstructionInfo &Info, StringRef Name, SMLoc NameLoc, OperandVector &Operands)=0
ParseInstruction - Parse one assembly instruction.
virtual bool ParseInstruction (ParseInstructionInfo &Info, StringRef Name, AsmToken Token, OperandVector &Operands)
virtual bool ParseDirective (AsmToken DirectiveID)=0
ParseDirective - Parse a target specific assembler directive.
virtual bool MatchAndEmitInstruction (SMLoc IDLoc, unsigned &Opcode, OperandVector &Operands, MCStreamer &Out, uint64_t &ErrorInfo, bool MatchingInlineAsm)=0
MatchAndEmitInstruction - Recognize a series of operands of a parsed instruction as an actual MCInst and emit it to the specified MCStreamer.
virtual bool OmitRegisterFromClobberLists (unsigned RegNo)
Allows targets to let registers opt out of clobber lists.
virtual unsigned validateTargetOperandClass (MCParsedAsmOperand &Op, unsigned Kind)
Allow a target to add special case operand matching for things that tblgen doesn't/can't handle effectively.
virtual unsigned checkEarlyTargetMatchPredicate (MCInst &Inst, const OperandVector &Operands)
Validate the instruction match against any complex target predicates before rendering any operands to it.
virtual unsigned checkTargetMatchPredicate (MCInst &Inst)
checkTargetMatchPredicate - Validate the instruction match against any complex target predicates not expressible via match classes.
virtual void convertToMapAndConstraints (unsigned Kind, const OperandVector &Operands)=0
virtual bool areEqualRegs (const MCParsedAsmOperand &Op1, const MCParsedAsmOperand &Op2) const
Returns whether two operands are registers and are equal.
virtual bool equalIsAsmAssignment ()
virtual bool isLabel (AsmToken &Token)
virtual bool starIsStartOfStatement ()
virtual const MCExpr * applyModifierToExpr (const MCExpr *E, MCSymbolRefExpr::VariantKind, MCContext &Ctx)
virtual void doBeforeLabelEmit (MCSymbol *Symbol, SMLoc IDLoc)
virtual void onLabelParsed (MCSymbol *Symbol)
virtual void flushPendingInstructions (MCStreamer &Out)
Ensure that all previously parsed instructions have been emitted to the output streamer, if the target does not emit them immediately.
virtual const MCExpr * createTargetUnaryExpr (const MCExpr *E, AsmToken::TokenKind OperatorToken, MCContext &Ctx)
virtual void onBeginOfFile ()
virtual void onEndOfFile ()
Public Member Functions inherited from llvm::MCAsmParserExtension
MCAsmParserExtension (const MCAsmParserExtension &)=delete
MCAsmParserExtension & operator= (const MCAsmParserExtension &)=delete
virtual ~MCAsmParserExtension ()
virtual void Initialize (MCAsmParser &Parser)
Initialize the extension for parsing using the given Parser.
MCContext & getContext ()
MCAsmLexer & getLexer ()
const MCAsmLexer & getLexer () const
MCAsmParser & getParser ()
const MCAsmParser & getParser () const
SourceMgr & getSourceManager ()
MCStreamer & getStreamer ()
bool Warning (SMLoc L, const Twine &Msg)
bool Error (SMLoc L, const Twine &Msg, SMRange Range=SMRange())
void Note (SMLoc L, const Twine &Msg)
bool TokError (const Twine &Msg)
const AsmToken & Lex ()
const AsmToken & getTok ()
bool parseToken (AsmToken::TokenKind T, const Twine &Msg="unexpected token")
bool parseEOL ()
bool parseMany (function_ref< bool()> parseOne, bool hasComma=true)
bool parseOptionalToken (AsmToken::TokenKind T)
bool ParseDirectiveCGProfile (StringRef, SMLoc)
ParseDirectiveCGProfile ::= .cg_profile identifier, identifier, <number>
bool check (bool P, const Twine &Msg)
bool check (bool P, SMLoc Loc, const Twine &Msg)
bool addErrorSuffix (const Twine &Suffix)
bool HasBracketExpressions () const
Protected Member Functions
MCTargetAsmParser (MCTargetOptions const &, const MCSubtargetInfo &STI, const MCInstrInfo &MII)
MCSubtargetInfo & copySTI ()
Create a copy of STI and return a non-const reference to it.
Protected Member Functions inherited from llvm::MCAsmParserExtension
MCAsmParserExtension ()
Protected Attributes
FeatureBitset AvailableFeatures
AvailableFeatures - The current set of available features.
bool ParsingMSInlineAsm = false
ParsingMSInlineAsm - Are we parsing ms-style inline assembly?
MCAsmParserSemaCallback * SemaCallback = nullptr
SemaCallback - The Sema callback implementation.
MCTargetOptions MCOptions
Set of options which affects instrumentation of inline assembly.
const MCSubtargetInfo * STI
Current STI.
const MCInstrInfo & MII
Protected Attributes inherited from llvm::MCAsmParserExtension
bool BracketExpressionsSupported = false
Additional Inherited Members
Static Protected Member Functions inherited from llvm::MCAsmParserExtension
template<typename T , bool(T::*)(StringRef, SMLoc) Handler>
static bool HandleDirective (MCAsmParserExtension *Target, StringRef Directive, SMLoc DirectiveLoc)
Detailed Description
MCTargetAsmParser - Generic interface to target specific assembly parsers.
Definition at line 315 of file MCTargetAsmParser.h.
Member Enumeration Documentation
MatchResultTy
enum llvm::MCTargetAsmParser::MatchResultTy
Enumerator
Match_InvalidOperand
Match_InvalidTiedOperand
Match_MissingFeature
Match_MnemonicFail
Match_Success
Match_NearMisses
FIRST_TARGET_MATCH_RESULT_TY
Definition at line 317 of file MCTargetAsmParser.h.
Constructor & Destructor Documentation
MCTargetAsmParser() [1/2]
MCTargetAsmParser::MCTargetAsmParser (MCTargetOptions const & MCOptions, const MCSubtargetInfo & STI, const MCInstrInfo & MII) protected
Definition at line 14 of file MCTargetAsmParser.cpp.
MCTargetAsmParser() [2/2]
llvm::MCTargetAsmParser::MCTargetAsmParser (const MCTargetAsmParser &) delete
~MCTargetAsmParser()
MCTargetAsmParser::~MCTargetAsmParser () override default
Member Function Documentation
applyModifierToExpr()
virtual const MCExpr * llvm::MCTargetAsmParser::applyModifierToExpr (const MCExpr * E, MCSymbolRefExpr::VariantKind , MCContext & Ctx) inline virtual
Definition at line 478 of file MCTargetAsmParser.h.
areEqualRegs()
virtual bool llvm::MCTargetAsmParser::areEqualRegs (const MCParsedAsmOperand & Op1, const MCParsedAsmOperand & Op2) const inline virtual
Returns whether two operands are registers and are equal.
This is used by the tied-operands checks in the AsmMatcher. This method can be overridden to allow e.g. a sub- or super-register as the tied operand.
Definition at line 466 of file MCTargetAsmParser.h.
References llvm::MCParsedAsmOperand::getReg(), and llvm::MCParsedAsmOperand::isReg().
checkEarlyTargetMatchPredicate()
virtual unsigned llvm::MCTargetAsmParser::checkEarlyTargetMatchPredicate (MCInst & Inst, const OperandVector & Operands) inline virtual
Validate the instruction match against any complex target predicates before rendering any operands to it.
Definition at line 450 of file MCTargetAsmParser.h.
References Match_Success.
checkTargetMatchPredicate()
virtual unsigned llvm::MCTargetAsmParser::checkTargetMatchPredicate (MCInst & Inst) inline virtual
checkTargetMatchPredicate - Validate the instruction match against any complex target predicates not expressible via match classes.
Definition at line 456 of file MCTargetAsmParser.h.
References Match_Success.
convertToMapAndConstraints()
virtual void llvm::MCTargetAsmParser::convertToMapAndConstraints (unsigned Kind, const OperandVector & Operands) pure virtual
copySTI()
MCSubtargetInfo & MCTargetAsmParser::copySTI () protected
Create a copy of STI and return a non-const reference to it.
Definition at line 21 of file MCTargetAsmParser.cpp.
References llvm::MCAsmParserExtension::getContext(), getSTI(), llvm::MCContext::getSubtargetCopy(), and STI.
createTargetUnaryExpr()
virtual const MCExpr * llvm::MCTargetAsmParser::createTargetUnaryExpr (const MCExpr * E, AsmToken::TokenKind OperatorToken, MCContext & Ctx) inline virtual
Definition at line 493 of file MCTargetAsmParser.h.
doBeforeLabelEmit()
virtual void llvm::MCTargetAsmParser::doBeforeLabelEmit (MCSymbol * Symbol, SMLoc IDLoc) inline virtual
Definition at line 485 of file MCTargetAsmParser.h.
equalIsAsmAssignment()
virtual bool llvm::MCTargetAsmParser::equalIsAsmAssignment () inline virtual
Definition at line 472 of file MCTargetAsmParser.h.
flushPendingInstructions()
virtual void llvm::MCTargetAsmParser::flushPendingInstructions (MCStreamer & Out) inline virtual
Ensure that all previously parsed instructions have been emitted to the output streamer, if the target does not emit them immediately.
Definition at line 491 of file MCTargetAsmParser.h.
getAvailableFeatures()
const FeatureBitset & llvm::MCTargetAsmParser::getAvailableFeatures () const inline
Definition at line 360 of file MCTargetAsmParser.h.
References AvailableFeatures.
getSTI()
const MCSubtargetInfo & MCTargetAsmParser::getSTI () const
Definition at line 27 of file MCTargetAsmParser.cpp.
References STI.
Referenced by copySTI().
getTargetOptions()
MCTargetOptions llvm::MCTargetAsmParser::getTargetOptions () const inline
Definition at line 370 of file MCTargetAsmParser.h.
References MCOptions.
isLabel()
virtual bool llvm::MCTargetAsmParser::isLabel (AsmToken & Token) inline virtual
Definition at line 474 of file MCTargetAsmParser.h.
isParsingMSInlineAsm()
bool llvm::MCTargetAsmParser::isParsingMSInlineAsm () inline
Definition at line 367 of file MCTargetAsmParser.h.
References ParsingMSInlineAsm.
MatchAndEmitInstruction()
virtual bool llvm::MCTargetAsmParser::MatchAndEmitInstruction (SMLoc IDLoc, unsigned & Opcode, OperandVector & Operands, MCStreamer & Out, uint64_t & ErrorInfo, bool MatchingInlineAsm) pure virtual
MatchAndEmitInstruction - Recognize a series of operands of a parsed instruction as an actual MCInst and emit it to the specified MCStreamer.
This returns false on success and returns true on failure to match.
On failure, the target parser is responsible for emitting a diagnostic explaining the match failure.
OmitRegisterFromClobberLists()
virtual bool llvm::MCTargetAsmParser::OmitRegisterFromClobberLists (unsigned RegNo) inline virtual
Allows targets to let registers opt out of clobber lists.
Definition at line 436 of file MCTargetAsmParser.h.
onBeginOfFile()
virtual void llvm::MCTargetAsmParser::onBeginOfFile () inline virtual
Definition at line 500 of file MCTargetAsmParser.h.
onEndOfFile()
virtual void llvm::MCTargetAsmParser::onEndOfFile () inline virtual
Definition at line 503 of file MCTargetAsmParser.h.
onLabelParsed()
virtual void llvm::MCTargetAsmParser::onLabelParsed (MCSymbol * Symbol) inline virtual
Definition at line 487 of file MCTargetAsmParser.h.
operator=()
MCTargetAsmParser & llvm::MCTargetAsmParser::operator= (const MCTargetAsmParser &) delete
ParseDirective()
virtual bool llvm::MCTargetAsmParser::ParseDirective (AsmToken DirectiveID) pure virtual
ParseDirective - Parse a target specific assembler directive.
The parser is positioned following the directive name. The target specific directive parser should parse the entire directive doing or recording any target specific work, or return true and do nothing if the directive is not target specific. If the directive is specific for the target, the entire line is parsed up to and including the end-of-statement token and false is returned.
Parameters
DirectiveID - the identifier token of the directive.
ParseInstruction() [1/2]
virtual bool llvm::MCTargetAsmParser::ParseInstruction (ParseInstructionInfo & Info, StringRef Name, AsmToken Token, OperandVector & Operands) inline virtual
Definition at line 407 of file MCTargetAsmParser.h.
References llvm::AsmToken::getLoc(), Name, Operands, and ParseInstruction().
ParseInstruction() [2/2]
virtual bool llvm::MCTargetAsmParser::ParseInstruction (ParseInstructionInfo & Info, StringRef Name, SMLoc NameLoc, OperandVector & Operands) pure virtual
ParseInstruction - Parse one assembly instruction.
The parser is positioned following the instruction name. The target specific instruction parser should parse the entire instruction and construct the appropriate MCInst, or emit an error. On success, the entire line should be parsed up to and including the end-of-statement token. On failure, the parser is not required to read to the end of the line.
Parameters
Name - The instruction name.
NameLoc - The source location of the name.
Operands [out] - The list of parsed operands, this returns ownership of them to the caller.
Returns
True on failure.
Referenced by ParseInstruction().
parsePrimaryExpr()
virtual bool llvm::MCTargetAsmParser::parsePrimaryExpr (const MCExpr *& Res, SMLoc & EndLoc) inline virtual
Definition at line 377 of file MCTargetAsmParser.h.
References llvm::MCAsmParserExtension::getParser(), and llvm::MCAsmParser::parsePrimaryExpr().
parseRegister()
virtual bool llvm::MCTargetAsmParser::parseRegister (MCRegister & Reg, SMLoc & StartLoc, SMLoc & EndLoc) pure virtual
setAvailableFeatures()
void llvm::MCTargetAsmParser::setAvailableFeatures (const FeatureBitset & Value) inline
Definition at line 363 of file MCTargetAsmParser.h.
References AvailableFeatures.
Referenced by XtensaAsmParser::XtensaAsmParser().
setParsingMSInlineAsm()
void llvm::MCTargetAsmParser::setParsingMSInlineAsm (bool Value) inline
Definition at line 368 of file MCTargetAsmParser.h.
References ParsingMSInlineAsm.
setSemaCallback()
void llvm::MCTargetAsmParser::setSemaCallback (MCAsmParserSemaCallback * Callback) inline
Definition at line 372 of file MCTargetAsmParser.h.
References SemaCallback.
starIsStartOfStatement()
virtual bool llvm::MCTargetAsmParser::starIsStartOfStatement () inline virtual
Definition at line 476 of file MCTargetAsmParser.h.
tryParseRegister()
virtual OperandMatchResultTy llvm::MCTargetAsmParser::tryParseRegister (MCRegister & Reg, SMLoc & StartLoc, SMLoc & EndLoc) pure virtual
tryParseRegister - parse one register if possible
Check whether a register specification can be parsed at the current location, without failing the entire parse if it can't. Must not consume tokens if the parse fails.
validateTargetOperandClass()
virtual unsigned llvm::MCTargetAsmParser::validateTargetOperandClass (MCParsedAsmOperand & Op, unsigned Kind) inline virtual
Allow a target to add special case operand matching for things that tblgen doesn't/can't handle effectively.
For example, literal immediates on ARM. TableGen expects a token operand, but the parser will recognize them as immediates.
Definition at line 442 of file MCTargetAsmParser.h.
References Match_InvalidOperand.
Member Data Documentation
AvailableFeatures
FeatureBitset llvm::MCTargetAsmParser::AvailableFeatures protected
AvailableFeatures - The current set of available features.
Definition at line 335 of file MCTargetAsmParser.h.
Referenced by getAvailableFeatures(), and setAvailableFeatures().
MCOptions
MCTargetOptions llvm::MCTargetAsmParser::MCOptions protected
Set of options which affects instrumentation of inline assembly.
Definition at line 345 of file MCTargetAsmParser.h.
Referenced by getTargetOptions().
MII
const MCInstrInfo& llvm::MCTargetAsmParser::MII protected
Definition at line 350 of file MCTargetAsmParser.h.
ParsingMSInlineAsm
bool llvm::MCTargetAsmParser::ParsingMSInlineAsm = false protected
ParsingMSInlineAsm - Are we parsing ms-style inline assembly?
Definition at line 338 of file MCTargetAsmParser.h.
Referenced by isParsingMSInlineAsm(), and setParsingMSInlineAsm().
SemaCallback
MCAsmParserSemaCallback* llvm::MCTargetAsmParser::SemaCallback = nullptr protected
SemaCallback - The Sema callback implementation.
Must be set when parsing ms-style inline assembly.
Definition at line 342 of file MCTargetAsmParser.h.
Referenced by setSemaCallback().
STI
const MCSubtargetInfo* llvm::MCTargetAsmParser::STI protected
Current STI.
Definition at line 348 of file MCTargetAsmParser.h.
Referenced by copySTI(), getSTI(), and XtensaAsmParser::XtensaAsmParser().
The documentation for this class was generated from the following files:
include/llvm/MC/MCParser/MCTargetAsmParser.h
lib/MC/MCParser/MCTargetAsmParser.cpp