LLVM: llvm::object::CommonArchiveMemberHeader< T > Class Template Reference
llvm::object::CommonArchiveMemberHeader< T > Class Template Reference
#include "llvm/Object/Archive.h"
Public Member Functions
CommonArchiveMemberHeader (const Archive *Parent, const T *RawHeaderPtr)
StringRef getRawAccessMode () const override
StringRef getRawLastModified () const override
StringRef getRawUID () const override
StringRef getRawGID () const override
uint64_t getOffset () const override
uint64_t getSizeOf () const override
Returns the size in bytes of the format-defined member header of the concrete archive type.
Public Member Functions inherited from llvm::object::AbstractArchiveMemberHeader
virtual std::unique_ptr< AbstractArchiveMemberHeader > clone () const =0
virtual ~AbstractArchiveMemberHeader ()=default
virtual Expected< StringRef > getRawName () const =0
Get the name without looking up long names.
virtual Expected< StringRef > getName (uint64_t Size) const =0
Get the name looking up long names.
virtual Expected< uint64_t > getSize () const =0
virtual Expected< const char * > getNextChildLoc () const =0
Get next file member location.
virtual Expected< bool > isThin () const =0
Expected< sys::fs::perms > getAccessMode () const
Expected< sys::TimePoint< std::chrono::seconds > > getLastModified () const
Expected< unsigned > getUID () const
Expected< unsigned > getGID () const
Public Attributes
T const * ArMemHdr
Public Attributes inherited from llvm::object::AbstractArchiveMemberHeader
const Archive * Parent
Additional Inherited Members
Protected Member Functions inherited from llvm::object::AbstractArchiveMemberHeader
AbstractArchiveMemberHeader (const Archive *Parent)
Detailed Description
template<typename T>
class llvm::object::CommonArchiveMemberHeader< T >
Definition at line 77 of file Archive.h.
Constructor & Destructor Documentation
CommonArchiveMemberHeader()
template<typename T > llvm::object::CommonArchiveMemberHeader< T >::CommonArchiveMemberHeader (const Archive * Parent, const T * RawHeaderPtr) inline
Definition at line 79 of file Archive.h.
Member Function Documentation
getOffset()
template<class T > uint64_t CommonArchiveMemberHeader::getOffset () const override virtual
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 87 of file Archive.cpp.
getRawAccessMode()
template<class T > StringRef CommonArchiveMemberHeader::getRawAccessMode () const override virtual
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 70 of file Archive.cpp.
References getFieldRawString().
getRawGID()
template<class T > StringRef CommonArchiveMemberHeader::getRawGID () const override virtual
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 83 of file Archive.cpp.
getRawLastModified()
template<class T > StringRef CommonArchiveMemberHeader::getRawLastModified () const override virtual
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 75 of file Archive.cpp.
References getFieldRawString().
getRawUID()
template<class T > StringRef CommonArchiveMemberHeader::getRawUID () const override virtual
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 79 of file Archive.cpp.
References getFieldRawString().
getSizeOf()
template<typename T > uint64_t llvm::object::CommonArchiveMemberHeader< T >::getSizeOf () const inline override virtual
Returns the size in bytes of the format-defined member header of the concrete archive type.
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 87 of file Archive.h.
References T.
Member Data Documentation
ArMemHdr
template<typename T > T const* llvm::object::CommonArchiveMemberHeader< T >::ArMemHdr
Definition at line 89 of file Archive.h.
The documentation for this class was generated from the following files:
include/llvm/Object/Archive.h
lib/Object/Archive.cpp