LLVM: llvm::MemoryUse Class Reference
llvm::MemoryUse Class Reference final
Represents read-only accesses to memory.
#include "llvm/Analysis/MemorySSA.h"
Public Member Functions
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (MemoryAccess)
MemoryUse (LLVMContext &C, MemoryAccess *DMA, Instruction *MI, BasicBlock *BB)
void * operator new (size_t S)
void operator delete (void *Ptr)
void print (raw_ostream &OS) const
void setOptimized (MemoryAccess *DMA)
bool isOptimized () const
Whether the MemoryUse is optimized.
MemoryAccess * getOptimized () const
void resetOptimized ()
Public Member Functions inherited from llvm::MemoryUseOrDef
void * operator new (size_t)=delete
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (MemoryAccess)
Instruction * getMemoryInst () const
Get the instruction that this MemoryUse represents.
MemoryAccess * getDefiningAccess () const
Get the access that produces the memory state used by this Use.
bool isOptimized () const
Do we have an optimized use?
MemoryAccess * getOptimized () const
Return the MemoryAccess associated with the optimized use, or nullptr.
void setOptimized (MemoryAccess *)
Sets the optimized use for a MemoryDef.
void resetOptimized ()
Reset the ID of what this MemoryUse was optimized to, causing it to be rewalked by the walker if necessary.
Public Member Functions inherited from llvm::MemoryAccess
MemoryAccess (const MemoryAccess &)=delete
MemoryAccess & operator= (const MemoryAccess &)=delete
void * operator new (size_t)=delete
BasicBlock * getBlock () const
void print (raw_ostream &OS) const
void dump () const
memoryaccess_def_iterator defs_begin ()
This iterator walks over all of the defs in a given MemoryAccess.
const_memoryaccess_def_iterator defs_begin () const
memoryaccess_def_iterator defs_end ()
const_memoryaccess_def_iterator defs_end () const
AllAccessType::self_iterator getIterator ()
Get the iterators for the all access list and the defs only list We default to the all access list.
AllAccessType::const_self_iterator getIterator () const
AllAccessType::reverse_self_iterator getReverseIterator ()
AllAccessType::const_reverse_self_iterator getReverseIterator () const
DefsOnlyType::self_iterator getDefsIterator ()
DefsOnlyType::const_self_iterator getDefsIterator () const
DefsOnlyType::reverse_self_iterator getReverseDefsIterator ()
DefsOnlyType::const_reverse_self_iterator getReverseDefsIterator () const
Public Member Functions inherited from llvm::DerivedUser
DerivedUser (Type *Ty, unsigned VK, Use *U, unsigned NumOps, DeleteValueTy DeleteValue)
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_impl< OptionsT >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const Value *MA)
Static Public Member Functions inherited from llvm::MemoryUseOrDef
static bool classof (const Value *MA)
Static Public Member Functions inherited from llvm::MemoryAccess
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Friends
class MemorySSA
Additional Inherited Members
Public Types inherited from llvm::MemoryAccess
using AllAccessType
using DefsOnlyType
using iterator = user_iterator
The user iterators for a memory access.
using const_iterator = const_user_iterator
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::DerivedUser
using DeleteValueTy = void (*)(DerivedUser *)
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< OptionsT >
using self_iterator = ilist_iterator<OptionsT, false, false>
using const_self_iterator = ilist_iterator<OptionsT, false, true>
using reverse_self_iterator = ilist_iterator<OptionsT, true, false>
using const_reverse_self_iterator = ilist_iterator<OptionsT, true, true>
Protected Member Functions inherited from llvm::MemoryUseOrDef
MemoryUseOrDef (LLVMContext &C, MemoryAccess *DMA, unsigned Vty, DeleteValueTy DeleteValue, Instruction *MI, BasicBlock *BB, unsigned NumOperands)
~MemoryUseOrDef ()=default
void setDefiningAccess (MemoryAccess *DMA, bool Optimized=false)
Protected Member Functions inherited from llvm::MemoryAccess
void setBlock (BasicBlock *BB)
Used by MemorySSA to change the block of a MemoryAccess when it is moved.
unsigned getID () const
Used for debugging and tracking things about MemoryAccesses.
MemoryAccess (LLVMContext &C, unsigned Vty, DeleteValueTy DeleteValue, BasicBlock *BB, unsigned NumOperands)
~MemoryAccess ()=default
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Protected Member Functions inherited from llvm::ilist_node_impl< OptionsT >
ilist_node_impl ()=default
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
Represents read-only accesses to memory.
In particular, the set of Instructions that will be represented by MemoryUse's is exactly the set of Instructions for which AliasAnalysis::getModRefInfo returns "Ref".
Definition at line 312 of file MemorySSA.h.
Constructor & Destructor Documentation
MemoryUse()
llvm::MemoryUse::MemoryUse (LLVMContext & C, MemoryAccess * DMA, Instruction * MI, BasicBlock * BB) inline
Definition at line 316 of file MemorySSA.h.
Member Function Documentation
classof()
static bool llvm::MemoryUse::classof (const Value * MA) inline static
Definition at line 324 of file MemorySSA.h.
References llvm::Value::getValueID(), and llvm::ilist_node_impl< OptionsT >::ilist_node_impl().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::MemoryUse::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (MemoryAccess)
getOptimized()
MemoryAccess * llvm::MemoryUse::getOptimized () const inline
Definition at line 342 of file MemorySSA.h.
References llvm::MemoryUseOrDef::getDefiningAccess().
isOptimized()
bool llvm::MemoryUse::isOptimized () const inline
Whether the MemoryUse is optimized.
If ensureOptimizedUses() was called, uses will usually be optimized, but this is not guaranteed (e.g. due to invalidation and optimization limits.)
Definition at line 338 of file MemorySSA.h.
References llvm::MemoryUseOrDef::getDefiningAccess(), and llvm::MemoryAccess::getID().
operator delete()
void llvm::MemoryUse::operator delete (void * Ptr) inline
Definition at line 322 of file MemorySSA.h.
References Ptr.
operator new()
void * llvm::MemoryUse::operator new (size_t S) inline
Definition at line 321 of file MemorySSA.h.
print()
void MemoryUse::print (raw_ostream & OS) const
Definition at line 2205 of file MemorySSA.cpp.
References llvm::MemoryAccess::getID(), and LiveOnEntryStr.
resetOptimized()
void llvm::MemoryUse::resetOptimized () inline
Definition at line 346 of file MemorySSA.h.
References llvm::INVALID_MEMORYACCESS_ID.
setOptimized()
void llvm::MemoryUse::setOptimized (MemoryAccess * DMA) inline
Definition at line 330 of file MemorySSA.h.
References llvm::User::setOperand().
Friends And Related Symbol Documentation
MemorySSA
friend class MemorySSA friend
Definition at line 351 of file MemorySSA.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/MemorySSA.h
lib/Analysis/MemorySSA.cpp