LLVM: llvm::dxil::UAVResource Class Reference
llvm::dxil::UAVResource Class Reference
#include "Target/DirectX/DXILResource.h"
Public Member Functions
UAVResource (uint32_t I, hlsl::FrontendResource R)
MDNode * write () const
void print (raw_ostream &O) const
Additional Inherited Members
Protected Types inherited from llvm::dxil::ResourceBase
enum class ComponentType : uint32_t {
Invalid = 0 , I1 , I16 , U16 ,
I32 , U32 , I64 , U64 ,
F16 , F32 , F64 , SNormF16 ,
UNormF16 , SNormF32 , UNormF32 , SNormF64 ,
UNormF64 , PackedS8x32 , PackedU8x32 , LastEntry
}
using Kinds = hlsl::ResourceKind
Protected Member Functions inherited from llvm::dxil::ResourceBase
ResourceBase (uint32_t I, hlsl::FrontendResource R)
void write (LLVMContext &Ctx, MutableArrayRef< Metadata * > Entries) const
void print (raw_ostream &O, StringRef IDPrefix, StringRef BindingPrefix) const
Static Protected Member Functions inherited from llvm::dxil::ResourceBase
static StringRef getKindName (Kinds Kind)
static void printKind (Kinds Kind, unsigned Alignment, raw_ostream &OS, bool SRV=false, bool HasCounter=false, uint32_t SampleCount=0)
static StringRef getComponentTypeName (ComponentType CompType)
static void printComponentType (Kinds Kind, ComponentType CompType, unsigned Alignment, raw_ostream &OS)
Protected Attributes inherited from llvm::dxil::ResourceBase
uint32_t ID
GlobalVariable * GV
StringRef Name
uint32_t Space
uint32_t LowerBound
uint32_t RangeSize
Detailed Description
Definition at line 95 of file DXILResource.h.
Constructor & Destructor Documentation
UAVResource()
UAVResource::UAVResource (uint32_t I, hlsl::FrontendResource R)
Definition at line 233 of file DXILResource.cpp.
Member Function Documentation
print()
void UAVResource::print (raw_ostream & O) const
Definition at line 240 of file DXILResource.cpp.
References llvm::dxil::ResourceBase::ExtendedProperties::ElementType, llvm::dxil::ResourceBase::Invalid, llvm::left_justify(), llvm::dxil::ResourceBase::Name, llvm::dxil::ResourceBase::print(), llvm::dxil::ResourceBase::printComponentType(), llvm::dxil::ResourceBase::printKind(), and llvm::right_justify().
write()
MDNode * UAVResource::write () const
Definition at line 349 of file DXILResource.cpp.
References B, llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::Value::getContext(), llvm::dxil::ResourceBase::GV, and llvm::dxil::ResourceBase::write().
The documentation for this class was generated from the following files:
lib/Target/DirectX/DXILResource.h
lib/Target/DirectX/DXILResource.cpp