LLVM: llvm::orc::TrampolinePool Class Reference
llvm::orc::TrampolinePool Class Reference abstract
Base class for pools of compiler re-entry trampolines.
#include "llvm/ExecutionEngine/Orc/IndirectionUtils.h"
Public Types
using NotifyLandingResolvedFunction
using ResolveLandingFunction
Public Member Functions
virtual ~TrampolinePool ()
Expected< JITTargetAddress > getTrampoline ()
Get an available trampoline address.
void releaseTrampoline (JITTargetAddress TrampolineAddr)
Returns the given trampoline to the pool for re-use.
Protected Member Functions
virtual Error grow ()=0
Protected Attributes
std::mutex TPMutex
std::vector< JITTargetAddress > AvailableTrampolines
Detailed Description
Base class for pools of compiler re-entry trampolines.
These trampolines are callable addresses that save all register state before calling a supplied function to return the trampoline landing address, then restore all state before jumping to that address. They are used by various ORC APIs to support lazy compilation
Definition at line 63 of file IndirectionUtils.h.
Member Typedef Documentation
NotifyLandingResolvedFunction
using llvm::orc::TrampolinePool::NotifyLandingResolvedFunction
Initial value:
      unique_function<void(JITTargetAddress) const>
Definition at line 65 of file IndirectionUtils.h.
ResolveLandingFunction
using llvm::orc::TrampolinePool::ResolveLandingFunction
Initial value:
 unique_function<void(
      JITTargetAddress TrampolineAddr,
      NotifyLandingResolvedFunction OnLandingResolved) const>
Definition at line 68 of file IndirectionUtils.h.
Constructor & Destructor Documentation
~TrampolinePool()
llvm::orc::TrampolinePool::~TrampolinePool () virtual default
Member Function Documentation
getTrampoline()
Expected< JITTargetAddress > llvm::orc::TrampolinePool::getTrampoline () inline
Get an available trampoline address.
Returns an error if no trampoline can be created.
Definition at line 76 of file IndirectionUtils.h.
References assert(), AvailableTrampolines, grow(), and TPMutex.
Referenced by llvm::orc::LazyCallThroughManager::getCallThroughTrampoline().
grow()
virtual Error llvm::orc::TrampolinePool::grow () protected pure virtual
Referenced by getTrampoline().
releaseTrampoline()
void llvm::orc::TrampolinePool::releaseTrampoline (JITTargetAddress TrampolineAddr) inline
Returns the given trampoline to the pool for re-use.
Definition at line 89 of file IndirectionUtils.h.
References AvailableTrampolines, and TPMutex.
Member Data Documentation
AvailableTrampolines
std::vector<JITTargetAddress> llvm::orc::TrampolinePool::AvailableTrampolines protected
Definition at line 98 of file IndirectionUtils.h.
Referenced by getTrampoline(), and releaseTrampoline().
TPMutex
std::mutex llvm::orc::TrampolinePool::TPMutex protected
Definition at line 97 of file IndirectionUtils.h.
Referenced by getTrampoline(), and releaseTrampoline().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/IndirectionUtils.h
lib/ExecutionEngine/Orc/IndirectionUtils.cpp