LLVM: llvm::coverage::RawCoverageFilenamesReader Class Reference
llvm::coverage::RawCoverageFilenamesReader Class Reference
Reader for the raw coverage filenames.
#include "llvm/ProfileData/Coverage/CoverageMappingReader.h"
Public Member Functions
RawCoverageFilenamesReader (StringRef Data, std::vector< std::string > &Filenames, StringRef CompilationDir="")
RawCoverageFilenamesReader (const RawCoverageFilenamesReader &)=delete
RawCoverageFilenamesReader & operator= (const RawCoverageFilenamesReader &)=delete
Error read (CovMapVersion Version)
Additional Inherited Members
Protected Member Functions inherited from llvm::coverage::RawCoverageReader
RawCoverageReader (StringRef Data)
Error readULEB128 (uint64_t &Result)
Error readIntMax (uint64_t &Result, uint64_t MaxPlus1)
Error readSize (uint64_t &Result)
Error readString (StringRef &Result)
Protected Attributes inherited from llvm::coverage::RawCoverageReader
StringRef Data
Detailed Description
Reader for the raw coverage filenames.
Definition at line 223 of file CoverageMappingReader.h.
Constructor & Destructor Documentation
RawCoverageFilenamesReader() [1/2]
llvm::coverage::RawCoverageFilenamesReader::RawCoverageFilenamesReader (StringRef Data, std::vector< std::string > & Filenames, StringRef CompilationDir = "") inline
Definition at line 231 of file CoverageMappingReader.h.
RawCoverageFilenamesReader() [2/2]
llvm::coverage::RawCoverageFilenamesReader::RawCoverageFilenamesReader (const RawCoverageFilenamesReader &) delete
Member Function Documentation
operator=()
RawCoverageFilenamesReader & llvm::coverage::RawCoverageFilenamesReader::operator= (const RawCoverageFilenamesReader &) delete
read()
Error RawCoverageFilenamesReader::read (CovMapVersion Version)
Definition at line 101 of file CoverageMappingReader.cpp.
References llvm::consumeError(), llvm::coverage::RawCoverageReader::Data, llvm::compression::zlib::decompress(), llvm::coverage::decompression_failed, llvm::compression::zlib::isAvailable(), llvm::coverage::malformed, llvm::coverage::RawCoverageReader::readSize(), llvm::coverage::RawCoverageReader::readULEB128(), llvm::StringRef::substr(), llvm::dwarf::toStringRef(), and llvm::coverage::Version4.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMappingReader.h
lib/ProfileData/Coverage/CoverageMappingReader.cpp