LLVM: llvm::LoopBase< BlockT, LoopT > Class Template Reference
llvm::LoopBase< BlockT, LoopT > Class Template Reference
Instances of this class are used to represent loops that are detected in the flow graph.
#include "llvm/Analysis/LoopInfo.h"
Public Types
typedef std::vector< LoopT * >::const_iterator iterator
typedef std::vector< LoopT * >::const_reverse_iterator reverse_iterator
typedef ArrayRef< BlockT * >::const_iterator block_iterator
typedef std::pair< BlockT *, BlockT * > Edge
Edge type.
Public Member Functions
unsigned getLoopDepth () const
Return the nesting level of this loop.
BlockT * getHeader () const
LoopT * getParentLoop () const
Return the parent loop if it exists or nullptr for top level loops.
const LoopT * getOutermostLoop () const
Get the outermost loop in which this loop is contained.
LoopT * getOutermostLoop ()
void setParentLoop (LoopT *L)
This is a raw interface for bypassing addChildLoop.
bool contains (const LoopT *L) const
Return true if the specified loop is contained within in this loop.
bool contains (const BlockT *BB) const
Return true if the specified basic block is in this loop.
template<class InstT >
bool contains (const InstT *Inst) const
Return true if the specified instruction is in this loop.
const std::vector< LoopT * > & getSubLoops () const
Return the loops contained entirely within this loop.
std::vector< LoopT * > & getSubLoopsVector ()
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
bool isInnermost () const
Return true if the loop does not contain any (natural) loops.
bool isOutermost () const
Return true if the loop does not have a parent (natural) loop.
ArrayRef< BlockT * > getBlocks () const
Get a list of the basic blocks which make up this loop.
block_iterator block_begin () const
block_iterator block_end () const
iterator_range< block_iterator > blocks () const
unsigned getNumBlocks () const
Get the number of blocks in this loop in constant time.
std::vector< BlockT * > & getBlocksVector ()
Return a direct, mutable handle to the blocks vector so that we can mutate it efficiently with techniques like std::remove.
SmallPtrSetImpl< const BlockT * > & getBlocksSet ()
Return a direct, mutable handle to the blocks set so that we can mutate it efficiently.
const SmallPtrSetImpl< const BlockT * > & getBlocksSet () const
Return a direct, immutable handle to the blocks set.
bool isInvalid () const
Return true if this loop is no longer valid.
bool isLoopExiting (const BlockT *BB) const
True if terminator in the block can branch to another block that is outside of the current loop.
bool isLoopLatch (const BlockT *BB) const
unsigned getNumBackEdges () const
Calculate the number of back edges to the loop header.
void getExitingBlocks (SmallVectorImpl< BlockT * > &ExitingBlocks) const
Return all blocks inside the loop that have successors outside of the loop.
BlockT * getExitingBlock () const
If getExitingBlocks would return exactly one block, return that block.
void getExitBlocks (SmallVectorImpl< BlockT * > &ExitBlocks) const
Return all of the successor blocks of this loop.
BlockT * getExitBlock () const
If getExitBlocks would return exactly one block, return that block.
bool hasDedicatedExits () const
Return true if no exit block for the loop has a predecessor that is outside the loop.
void getUniqueExitBlocks (SmallVectorImpl< BlockT * > &ExitBlocks) const
Return all unique successor blocks of this loop.
void getUniqueNonLatchExitBlocks (SmallVectorImpl< BlockT * > &ExitBlocks) const
Return all unique successor blocks of this loop except successors from Latch block are not considered.
BlockT * getUniqueExitBlock () const
If getUniqueExitBlocks would return exactly one block, return that block.
bool hasNoExitBlocks () const
Return true if this loop does not have any exit blocks.
void getExitEdges (SmallVectorImpl< Edge > &ExitEdges) const
Return all pairs of (inside_block,outside_block).
BlockT * getLoopPreheader () const
If there is a preheader for this loop, return it.
BlockT * getLoopPredecessor () const
If the given loop's header has exactly one unique predecessor outside the loop, return it.
BlockT * getLoopLatch () const
If there is a single latch block for this loop, return it.
void getLoopLatches (SmallVectorImpl< BlockT * > &LoopLatches) const
Return all loop latch blocks of this loop.
SmallVector< const LoopT *, 4 > getLoopsInPreorder () const
Return all loops in the loop nest rooted by the loop in preorder, with siblings in forward program order.
SmallVector< LoopT *, 4 > getLoopsInPreorder ()
void addBasicBlockToLoop (BlockT *NewBB, LoopInfoBase< BlockT, LoopT > &LI)
This method is used by other analyses to update loop information.
void replaceChildLoopWith (LoopT *OldChild, LoopT *NewChild)
This is used when splitting loops up.
void addChildLoop (LoopT *NewChild)
Add the specified loop to be a child of this loop.
LoopT * removeChildLoop (iterator I)
This removes the specified child from being a subloop of this loop.
LoopT * removeChildLoop (LoopT *Child)
This removes the specified child from being a subloop of this loop.
void addBlockEntry (BlockT *BB)
This adds a basic block directly to the basic block list.
void reverseBlock (unsigned from)
interface to reverse Blocks[from, end of loop] in this loop
void reserveBlocks (unsigned size)
interface to do reserve() for Blocks
void moveToHeader (BlockT *BB)
This method is used to move BB (which must be part of this loop) to be the loop header of the loop (the block that dominates all others).
void removeBlockFromLoop (BlockT *BB)
This removes the specified basic block from the current loop, updating the Blocks as appropriate.
void verifyLoop () const
Verify loop structure.
void verifyLoopNest (DenseSet< const LoopT * > *Loops) const
Verify loop structure of this loop and all nested loops.
bool isAnnotatedParallel () const
Returns true if the loop is annotated parallel.
void print (raw_ostream &OS, bool Verbose=false, bool PrintNested=true, unsigned Depth=0) const
Print loop with all the BBs inside it.
Static Public Member Functions
template<class Type >
static void getInnerLoopsInPreorder (const LoopT &L, SmallVectorImpl< Type > &PreOrderLoops)
Return all inner loops in the loop nest rooted by the loop in preorder, with siblings in forward program order.
Protected Member Functions
LoopBase ()
This creates an empty loop.
LoopBase (BlockT *BB)
~LoopBase ()
Friends
class LoopInfoBase< BlockT, LoopT >
Detailed Description
template<class BlockT, class LoopT>
class llvm::LoopBase< BlockT, LoopT >
Instances of this class are used to represent loops that are detected in the flow graph.
Definition at line 74 of file LoopInfo.h.
Member Typedef Documentation
block_iterator
template<class BlockT , class LoopT > typedef ArrayRef<BlockT*>::const_iterator llvm::LoopBase< BlockT, LoopT >::block_iterator
Definition at line 192 of file LoopInfo.h.
Edge
template<class BlockT , class LoopT > typedef std::pair<BlockT *, BlockT *> llvm::LoopBase< BlockT, LoopT >::Edge
Edge type.
Definition at line 326 of file LoopInfo.h.
iterator
template<class BlockT , class LoopT > typedef std::vector<LoopT*>::const_iterator llvm::LoopBase< BlockT, LoopT >::iterator
Definition at line 168 of file LoopInfo.h.
reverse_iterator
template<class BlockT , class LoopT > typedef std::vector<LoopT*>::const_reverse_iterator llvm::LoopBase< BlockT, LoopT >::reverse_iterator
Definition at line 170 of file LoopInfo.h.
Constructor & Destructor Documentation
LoopBase() [1/2]
template<class BlockT , class LoopT > llvm::LoopBase< BlockT, LoopT >::LoopBase () inline protected
This creates an empty loop.
Definition at line 506 of file LoopInfo.h.
LoopBase() [2/2]
template<class BlockT , class LoopT > llvm::LoopBase< BlockT, LoopT >::LoopBase (BlockT * BB) inline explicit protected
Definition at line 508 of file LoopInfo.h.
~LoopBase()
template<class BlockT , class LoopT > llvm::LoopBase< BlockT, LoopT >::~LoopBase () inline protected
Definition at line 522 of file LoopInfo.h.
Member Function Documentation
addBasicBlockToLoop()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop (BlockT * NewBB, LoopInfoBase< BlockT, LoopT > & LIB)
This method is used by other analyses to update loop information.
addBasicBlockToLoop - This method is used by other analyses to update loop information.
NewBB is set to be a new member of the current loop. Because of this, it is added as a member of all parent loops, and is added to the specified LoopInfo object as being in the current basic block. It is not valid to replace the loop header with this method.
Definition at line 258 of file LoopInfoImpl.h.
References assert(), and contains().
Referenced by cloneLoopBlocks(), llvm::cloneLoopWithPreheader(), insertUniqueBackedgeBlock(), and UpdateAnalysisInformation().
addBlockEntry()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::addBlockEntry (BlockT * BB) inline
This adds a basic block directly to the basic block list.
This should only be used by transformations that create new loops. Other transformations should use addBasicBlockToLoop.
Definition at line 440 of file LoopInfo.h.
References assert(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
addChildLoop()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::addChildLoop (LoopT * NewChild) inline
Add the specified loop to be a child of this loop.
This updates the loop depth of the new child.
Definition at line 412 of file LoopInfo.h.
References assert(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by llvm::cloneLoopWithPreheader(), createNaturalLoopInternal(), and llvm::VPRegionBlock::execute().
begin()
template<class BlockT , class LoopT > iterator llvm::LoopBase< BlockT, LoopT >::begin () const inline
Definition at line 171 of file LoopInfo.h.
References llvm::LoopBase< BlockT, LoopT >::getSubLoops().
Referenced by llvm::appendReversedLoopsToWorklist(), llvm::LoopInfo::erase(), isLoopDead(), llvm::LoopFullUnrollPass::run(), llvm::UnrollAndJamLoop(), and llvm::ScalarEvolution::verify().
block_begin()
template<class BlockT , class LoopT > block_iterator llvm::LoopBase< BlockT, LoopT >::block_begin () const inline
Definition at line 193 of file LoopInfo.h.
References llvm::LoopBase< BlockT, LoopT >::getBlocks().
Referenced by llvm::LoopBase< BlockT, LoopT >::blocks(), llvm::deleteDeadLoop(), detectPopcountIdiom(), and detectShiftUntilZeroIdiom().
block_end()
template<class BlockT , class LoopT > block_iterator llvm::LoopBase< BlockT, LoopT >::block_end () const inline
Definition at line 194 of file LoopInfo.h.
References llvm::LoopBase< BlockT, LoopT >::getBlocks().
Referenced by llvm::LoopBase< BlockT, LoopT >::blocks(), and llvm::deleteDeadLoop().
blocks()
template<class BlockT , class LoopT > iterator_range< block_iterator > llvm::LoopBase< BlockT, LoopT >::blocks () const inline
Definition at line 195 of file LoopInfo.h.
References assert(), llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), llvm::LoopBase< BlockT, LoopT >::isInvalid(), and llvm::make_range().
Referenced by llvm::ApproximateLoopSize(), buildClonedLoopBlocks(), canLoopBeDeleted(), canTailPredicateLoop(), llvm::cloneLoop(), collectUnswitchCandidates(), computeHeuristicUnrollFactor(), llvm::SimpleLoopSafetyInfo::computeLoopSafetyInfo(), llvm::ICFLoopSafetyInfo::computeLoopSafetyInfo(), countToEliminateCompares(), deleteDeadBlocksFromLoop(), deleteDeadClonedBlocks(), llvm::deleteDeadLoop(), llvm::LoopInfo::erase(), findBestNonTrivialUnswitchCandidate(), llvm::findSplitCandidate(), foreachMemoryAccess(), llvm::formDedicatedExitBlocks(), getFalkorUnrollingPreferences(), llvm::BasicTTIImplBase< T >::getUnrollingPreferences(), llvm::SystemZTTIImpl::getUnrollingPreferences(), llvm::WebAssemblyTTIImpl::getUnrollingPreferences(), hoistLoopToNewParent(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), isLoopDead(), isSafeForNoNTrivialUnswitching(), mayLoopAccessLocation(), mayLoopAccessLocation(), mergeBlocksIntoPredecessors(), partitionLoopBlocks(), llvm::peelLoop(), peelToTurnInvariantLoadsDerefencebale(), populateDependencyMatrix(), llvm::LoopVectorizationLegality::prepareToFoldTailByMasking(), llvm::printLoop(), rebuildLoopAfterUnswitch(), separateNestedLoop(), simplifyOneLoop(), sinkLoopInvariantInstructions(), llvm::UnrollLoop(), and llvm::UnrollRuntimeLoopRemainder().
contains() [1/3]
template<class BlockT , class LoopT > bool llvm::LoopBase< BlockT, LoopT >::contains (const BlockT * BB) const inline
Return true if the specified basic block is in this loop.
Definition at line 149 of file LoopInfo.h.
References assert(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
contains() [2/3]
template<class BlockT , class LoopT > template<class InstT > bool llvm::LoopBase< BlockT, LoopT >::contains (const InstT * Inst) const inline
Return true if the specified instruction is in this loop.
Definition at line 155 of file LoopInfo.h.
References llvm::LoopBase< BlockT, LoopT >::contains().
contains() [3/3]
template<class BlockT , class LoopT > bool llvm::LoopBase< BlockT, LoopT >::contains (const LoopT * L) const inline
Return true if the specified loop is contained within in this loop.
Definition at line 139 of file LoopInfo.h.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by llvm::RecurrenceDescriptor::AddReductionVar(), llvm::LoopSafetyInfo::allLoopPathsLeadToBlock(), analyzeLoopUnrollCost(), llvm::LoopAccessInfo::blockNeedsPredication(), llvm::breakLoopBackedge(), buildPartialInvariantUnswitchConditionalBranch(), CalculateUnswitchCostMultiplier(), canConstantEvolve(), canProveExitOnFirstIteration(), CanProveNotTakenFirstIteration(), canRotateDeoptimizingLatchExit(), llvm::canSinkOrHoistInst(), checkMixedPrecision(), checkOuterLoopInsts(), cloneLoopBlocks(), collectCastInstrs(), llvm::collectChildrenInLoop(), llvm::CodeMetrics::collectEphemeralValues(), collectTransitivePredecessors(), computeBlocksDominatingExits(), computeUnlikelySuccessors(), ConnectEpilog(), ConnectProlog(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::VPRecipeBuilder::createBlockInMask(), createFoldedExitCond(), createInvariantCond(), llvm::deleteDeadLoop(), dependsOnLocalPhi(), llvm::ICFLoopSafetyInfo::doesNotWriteMemoryBefore(), llvm::ICFLoopSafetyInfo::doesNotWriteMemoryBefore(), llvm::MustBeExecutedContextExplorer::findBackwardJoinPoint(), llvm::findDefsUsedOutsideOfLoop(), findLoopComponents(), findPHIToPartitionLoops(), llvm::InnerLoopVectorizer::fixupIVUsers(), llvm::formDedicatedExitBlocks(), llvm::formLCSSAForInstructions(), llvm::ScalarEvolution::getAddRecExpr(), getCastsForInductionPHI(), llvm::ScalarEvolution::getConstantMaxTripCountFromArray(), getEstimatedTripCount(), getInsertPointForUses(), llvm::LoopBase< BlockT, LoopT >::getLoopLatches(), llvm::LoopBase< BlockT, LoopT >::getNumBackEdges(), getSingleSchedPred(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), hasHardUserWithinLoop(), llvm::hasOutsideLoopUser(), llvm::hasPartialIVCondition(), hasUsesOutsideLoop(), initBranchWeights(), llvm::DivergenceAnalysisImpl::inRegion(), llvm::InsertPreheaderForLoop(), inSubLoop(), isBlockInLCSSAForm(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), llvm::InductionDescriptor::isFPInductionPHI(), isFreeInLoop(), llvm::HardwareLoopInfo::isHardwareLoopCandidate(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), isInteresting(), llvm::LoopBase< BlockT, LoopT >::isLoopExiting(), llvm::LoopBase< BlockT, LoopT >::isLoopLatch(), isNotUsedOrFreeInLoop(), IVUseShouldUsePostIncValue(), llvm::LPPassManager::markLoopAsDeleted(), llvm::LPMUpdater::markLoopAsDeleted(), llvm::MergeBlockSuccessorsIntoGivenBlocks(), llvm::LoopBodyTraits::LoopBodyFilter::operator()(), optimizeLoopExitWithUnknownExitCount(), llvm::peelLoop(), placeSplitBlockCarefully(), pointerInvalidatedByLoop(), llvm::LoopVectorizationLegality::prepareToFoldTailByMasking(), profitableToRotateLoopExitingLatch(), llvm::promoteLoopAccessesToScalars(), pushIVUsers(), rebuildLoopAfterUnswitch(), recomputeLoopBlockSet(), replaceLoopInvariantUses(), replaceLoopPHINodesWithPreheaderValues(), llvm::rewriteLoopExitValues(), llvm::GuardWideningPass::run(), separateNestedLoop(), shouldSpeculateInstrs(), simplifyLoopInst(), simplifyOneLoop(), sink(), sinkInstruction(), splitPredecessorsOfLoopExit(), unifyLoopExits(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchAllTrivialConditions(), unswitchTrivialBranch(), unswitchTrivialSwitch(), UpdateAnalysisInformation(), visitPointers(), llvm::LoopBlocksTraversal::visitPreorder(), and llvm::LoopInfo::wouldBeOutOfLoopUseRequiringLCSSA().
end()
template<class BlockT , class LoopT > iterator llvm::LoopBase< BlockT, LoopT >::end () const inline
Definition at line 172 of file LoopInfo.h.
References llvm::LoopBase< BlockT, LoopT >::getSubLoops().
Referenced by llvm::appendReversedLoopsToWorklist(), llvm::LoopInfo::erase(), isLoopDead(), llvm::LoopFullUnrollPass::run(), and llvm::ScalarEvolution::verify().
getBlocks()
template<class BlockT , class LoopT > ArrayRef< BlockT * > llvm::LoopBase< BlockT, LoopT >::getBlocks () const inline
Get a list of the basic blocks which make up this loop.
Definition at line 188 of file LoopInfo.h.
References assert(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by llvm::OpenMPIRBuilder::applySimd(), llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), llvm::canSinkOrHoistInst(), checkMixedPrecision(), checkOuterLoopInsts(), llvm::cloneLoopWithPreheader(), llvm::SimpleLoopSafetyInfo::computeLoopSafetyInfo(), DbgGatherSalvagableDVI(), llvm::findDefsUsedOutsideOfLoop(), llvm::ScalarEvolution::getConstantMaxTripCountFromArray(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::AArch64TTIImpl::getUnrollingPreferences(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), llvm::ARMTTIImpl::getUnrollingPreferences(), llvm::RISCVTTIImpl::getUnrollingPreferences(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), llvm::peelLoop(), pointerInvalidatedByLoop(), llvm::PredicatedScalarEvolution::print(), separateNestedLoop(), llvm::simplifyLoopAfterUnroll(), llvm::SinkAndHoistLICMFlags::SinkAndHoistLICMFlags(), llvm::UnrollAndJamLoop(), and llvm::UnrollLoop().
getBlocksSet() [1/2]
template<class BlockT , class LoopT > SmallPtrSetImpl< const BlockT * > & llvm::LoopBase< BlockT, LoopT >::getBlocksSet () inline
Return a direct, mutable handle to the blocks set so that we can mutate it efficiently.
Definition at line 215 of file LoopInfo.h.
References assert(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by rebuildLoopAfterUnswitch().
getBlocksSet() [2/2]
template<class BlockT , class LoopT > const SmallPtrSetImpl< const BlockT * > & llvm::LoopBase< BlockT, LoopT >::getBlocksSet () const inline
Return a direct, immutable handle to the blocks set.
Definition at line 221 of file LoopInfo.h.
References assert(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
getBlocksVector()
template<class BlockT , class LoopT > std::vector< BlockT * > & llvm::LoopBase< BlockT, LoopT >::getBlocksVector () inline
Return a direct, mutable handle to the blocks vector so that we can mutate it efficiently with techniques like std::remove.
Definition at line 209 of file LoopInfo.h.
References assert(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by rebuildLoopAfterUnswitch().
getExitBlock()
template<class BlockT , class LoopT > BlockT * llvm::LoopBase< BlockT, LoopT >::getExitBlock () const
If getExitBlocks would return exactly one block, return that block.
getExitBlock - If getExitBlocks would return exactly one block, return that block.
Otherwise return null.
Definition at line 107 of file LoopInfoImpl.h.
References llvm::getExitBlockHelper().
Referenced by checkLoopsStructure(), DoFlattenLoopPair(), llvm::LoopNest::getInterveningInstructions(), isEligibleLoopForm(), ReduceLoopStrength(), llvm::splitLoopBound(), and llvm::LoopVersioning::versionLoop().
getExitBlocks()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::getExitBlocks (SmallVectorImpl< BlockT * > & ExitBlocks) const
Return all of the successor blocks of this loop.
getExitBlocks - Return all of the successor blocks of this loop.
These are the blocks outside of the current loop which are branched to.
Definition at line 64 of file LoopInfoImpl.h.
References assert(), contains(), and llvm::ilist_node_impl< OptionsT >::ilist_node_impl().
Referenced by llvm::formLCSSA(), llvm::formLCSSAForInstructions(), llvm::ARMTTIImpl::getUnrollingPreferences(), hoistLoopToNewParent(), llvm::printLoop(), and llvm::UnrollLoop().
getExitEdges()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::getExitEdges (SmallVectorImpl< Edge > & ExitEdges) const
Return all pairs of (inside_block,outside_block).
getExitEdges - Return all pairs of (inside_block,outside_block).
Definition at line 164 of file LoopInfoImpl.h.
References assert(), contains(), and llvm::ilist_node_impl< OptionsT >::ilist_node_impl().
Referenced by llvm::peelLoop().
getExitingBlock()
template<class BlockT , class LoopT > BlockT * llvm::LoopBase< BlockT, LoopT >::getExitingBlock () const
If getExitingBlocks would return exactly one block, return that block.
getExitingBlock - If getExitingBlocks would return exactly one block, return that block.
Otherwise return null.
Definition at line 48 of file LoopInfoImpl.h.
References llvm::any_of(), assert(), contains(), llvm::ilist_node_impl< OptionsT >::ilist_node_impl(), and isExitBlock().
Referenced by addUsersInExitBlock(), llvm::canSplitLoopBound(), checkLoopsStructure(), DoFlattenLoopPair(), eliminateLoadsAcrossLoops(), findLoopComponents(), llvm::ScalarEvolution::getConstantMaxTripCountFromArray(), isEligibleLoopForm(), peelToTurnInvariantLoadsDerefencebale(), shouldSpeculateInstrs(), llvm::splitLoopBound(), tryToUnrollLoop(), llvm::UnrollAndJamLoop(), and llvm::UnrollRuntimeLoopRemainder().
getExitingBlocks()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::getExitingBlocks (SmallVectorImpl< BlockT * > & ExitingBlocks) const
Return all blocks inside the loop that have successors outside of the loop.
getExitingBlocks - Return all blocks inside the loop that have successors outside of the loop.
These are the blocks inside of the current loop which branch out. The returned list is always unique.
Definition at line 33 of file LoopInfoImpl.h.
References assert(), contains(), and llvm::ilist_node_impl< OptionsT >::ilist_node_impl().
Referenced by canLoopBeDeleted(), canProfitablyUnrollMultiExitLoop(), deleteLoopIfDead(), getMinAnalyzeableBackedgeTakenCount(), llvm::SCEVExpander::getRelatedExistingExpansion(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), llvm::ARMTTIImpl::getUnrollingPreferences(), llvm::RISCVTTIImpl::getUnrollingPreferences(), llvm::hasPartialIVCondition(), initBranchWeights(), llvm::HardwareLoopInfo::isHardwareLoopCandidate(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), peelToTurnInvariantLoadsDerefencebale(), PrintLoopInfo(), simplifyOneLoop(), tryToUnrollLoop(), unifyLoopExits(), and llvm::UnrollLoop().
getHeader()
template<class BlockT , class LoopT > BlockT * llvm::LoopBase< BlockT, LoopT >::getHeader () const inline
Definition at line 105 of file LoopInfo.h.
References llvm::LoopBase< BlockT, LoopT >::getBlocks().
Referenced by llvm::BlockFrequencyInfoImplBase::addLoopSuccessorsToDist(), llvm::RecurrenceDescriptor::AddReductionVar(), AddRuntimeUnrollDisableMetaData(), llvm::addStringMetadataToLoop(), llvm::LoopSafetyInfo::allLoopPathsLeadToBlock(), llvm::LoopVectorizeHints::allowVectorization(), analyzeLoopUnrollCost(), llvm::LoopVersioning::annotateInstWithNoAlias(), llvm::ScalarEvolution::applyLoopGuards(), llvm::LoopBlocksTraversal::begin(), llvm::breakLoopBackedge(), canConstantEvolve(), canFoldTermCondOfLoop(), canProveExitOnFirstIteration(), CanProveNotTakenFirstIteration(), llvm::canSplitLoopBound(), llvm::LoopVectorizationLegality::canVectorize(), CanWidenIV(), checkIsIndPhi(), checkLoopsStructure(), checkMixedPrecision(), checkOuterLoopInsts(), checkOverflow(), checkPHIs(), cloneLoopBlocks(), CloneLoopBlocks(), llvm::cloneLoopWithPreheader(), collectTransitivePredecessors(), collectUnswitchCandidates(), llvm::LoopSafetyInfo::computeBlockColors(), computeBlocksDominatingExits(), llvm::SimpleLoopSafetyInfo::computeLoopSafetyInfo(), llvm::computePeelCount(), llvm::computeUnrollCount(), llvm::VPRecipeBuilder::createBlockInMask(), createHWLoopAnalysis(), createLVAnalysis(), createStringMetadata(), llvm::InnerLoopVectorizer::createVectorLoopSkeleton(), llvm::deleteDeadLoop(), deleteLoopIfDead(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), DisableAllLoopOptsOnLoop(), llvm::ICFLoopSafetyInfo::doesNotWriteMemoryBefore(), DoFlattenLoopPair(), DoInitialMatch(), emitBasicBlockLoopComments(), llvm::InnerLoopVectorizer::emitMemRuntimeChecks(), llvm::LoopVectorizeHints::emitRemarkWithHints(), llvm::LoopBlocksTraversal::end(), llvm::SystemZPostRASchedStrategy::enterMBB(), llvm::MustBeExecutedContextExplorer::findBackwardJoinPoint(), findBestNonTrivialUnswitchCandidate(), llvm::MustBeExecutedContextExplorer::findForwardJoinPoint(), FindLoopCounter(), llvm::MachineLoopInfo::findLoopPreheader(), findPHIToPartitionLoops(), FlattenLoopPair(), llvm::formLCSSA(), llvm::gatherUnrollingPreferences(), llvm::ScalarEvolution::getAddRecExpr(), getDebugLocString(), getExpectedExitLoopLatchBranch(), GetInductionVariable(), getInnermostLoopFor(), llvm::LoopNest::getInterveningInstructions(), getIVIncrement(), llvm::LoopBase< BlockT, LoopT >::getLoopLatches(), llvm::BlockFrequencyInfoImplBase::getLoopName(), getLoopPhiForCounter(), llvm::LoopBase< BlockT, LoopT >::getNumBackEdges(), llvm::ARMTTIImpl::getPreferredAddressingMode(), getScalarEpilogueLowering(), getSingleSchedPred(), llvm::BasicTTIImplBase< T >::getUnrollingPreferences(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), llvm::ARMTTIImpl::getUnrollingPreferences(), llvm::RISCVTTIImpl::getUnrollingPreferences(), llvm::hasPartialIVCondition(), INITIALIZE_PASS(), llvm::InnerLoopVectorizer::InnerLoopVectorizer(), llvm::InsertPreheaderForLoop(), insertUniqueBackedgeBlock(), llvm::ScalarEvolution::isAvailableAtLoopEntry(), llvm::LoopVectorizationLegality::isConsecutivePtr(), llvm::isDereferenceableAndAlignedInLoop(), isEligibleLoopForm(), isEpilogProfitable(), isExistingPhi(), llvm::isFinite(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), llvm::InductionDescriptor::isFPInductionPHI(), llvm::SimpleLoopSafetyInfo::isGuaranteedToExecute(), llvm::isGuaranteedToExecuteForEveryIteration(), llvm::HardwareLoopInfo::isHardwareLoopCandidate(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), isIntegerLoopHeaderPHI(), isLoadConditional(), isLoadInvariantInLoop(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), isLoopCounter(), isLoopDead(), llvm::ScalarEvolution::isLoopEntryGuardedByCond(), llvm::LoopBase< BlockT, LoopT >::isLoopLatch(), llvm::isMustProgress(), llvm::RecurrenceDescriptor::isReductionPHI(), llvm::isSafeToUnrollAndJam(), llvm::IVUsers::IVUsers(), maybeEndlessLoop(), llvm::LoopBodyTraits::LoopBodyFilter::operator()(), llvm::AArch64TargetLowering::optimizeExtendOrTruncateConversion(), llvm::peelLoop(), peelToTurnInvariantLoadsDerefencebale(), llvm::LoopVectorizationPlanner::plan(), populateWorklist(), preheader(), llvm::LoopVersioning::prepareNoAliasMetadata(), llvm::SCEV::print(), llvm::IVUsers::print(), llvm::EpilogueVectorizerMainLoop::printDebugTracesAtEnd(), llvm::EpilogueVectorizerEpilogueLoop::printDebugTracesAtEnd(), llvm::printLoop(), PrintLoopInfo(), PrintParentLoopComment(), llvm::LoopVectorizePass::processLoop(), processLoopInVPlanNativePath(), profitableToRotateLoopExitingLatch(), PushLoopPHIs(), recomputeLoopBlockSet(), ReduceLoopStrength(), llvm::SCEVExpander::replaceCongruentIVs(), replaceLoopPHINodesWithPreheaderValues(), llvm::LoopAccessInfoPrinterPass::run(), llvm::DDGAnalysis::run(), llvm::DDGAnalysisPrinterPass::run(), llvm::LoopCachePrinterPass::run(), llvm::GuardWideningPass::run(), llvm::IndVarSimplifyPass::run(), llvm::LICMPass::run(), llvm::LoopBoundSplitPass::run(), llvm::LoopDeletionPass::run(), llvm::LoopIdiomRecognizePass::run(), llvm::LoopRotatePass::run(), llvm::LoopFullUnrollPass::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::LoopVersioningLICMPass::run(), llvm::LPPassManager::runOnFunction(), llvm::IVUsersWrapperPass::runOnLoop(), llvm::SwingSchedulerDAG::schedule(), separateNestedLoop(), llvm::LoopVectorizeHints::setAlreadyVectorized(), llvm::setLoopEstimatedTripCount(), llvm::ScalarEvolution::SimplifyICmpOperands(), llvm::simplifyLoopAfterUnroll(), simplifyLoopInst(), llvm::simplifyLoopIVs(), simplifyOneLoop(), llvm::sinkRegionForLoopNest(), llvm::LoopPass::skipLoop(), llvm::splitLoopBound(), llvm::VPRecipeBuilder::tryToCreateWidenRecipe(), tryToUnrollAndJamLoop(), tryToUnrollLoop(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchAllTrivialConditions(), unswitchLoop(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), unswitchTrivialSwitch(), updateLatchBranchWeightsForRemainderLoop(), llvm::MachineTraceMetrics::Ensemble::verify(), llvm::LoopVersioning::versionLoop(), violatesLegacyMultiExitLoopCheck(), visitPointers(), and warnAboutLeftoverTransformations().
getInnerLoopsInPreorder()
template<class BlockT , class LoopT > template<class Type > static void llvm::LoopBase< BlockT, LoopT >::getInnerLoopsInPreorder (const LoopT & L, SmallVectorImpl< Type > & PreOrderLoops) inline static
Return all inner loops in the loop nest rooted by the loop in preorder, with siblings in forward program order.
Definition at line 362 of file LoopInfo.h.
Referenced by llvm::LoopBase< BlockT, LoopT >::getLoopsInPreorder(), and llvm::LoopBase< BlockT, LoopT >::getLoopsInPreorder().
getLoopDepth()
template<class BlockT , class LoopT > unsigned llvm::LoopBase< BlockT, LoopT >::getLoopDepth () const inline
Return the nesting level of this loop.
An outer-most loop has depth 1, for consistency with loop depth values used for basic blocks, where depth 0 is used for blocks not inside any loops.
Definition at line 97 of file LoopInfo.h.
References assert(), D, and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by checkDependencies(), emitBasicBlockLoopComments(), llvm::ScalarEvolution::getAddRecExpr(), llvm::LoopNest::getLoopsAtDepth(), llvm::AArch64TTIImpl::getUnrollingPreferences(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), llvm::IndexedReference::hasTemporalReuse(), and PrintParentLoopComment().
getLoopLatch()
template<class BlockT , class LoopT > BlockT * llvm::LoopBase< BlockT, LoopT >::getLoopLatch () const
If there is a single latch block for this loop, return it.
getLoopLatch - If there is a single latch block for this loop, return it.
A latch block is a block that contains a branch back to the header.
Definition at line 232 of file LoopInfoImpl.h.
References assert(), and contains().
Referenced by llvm::analyzeICmp(), analyzeLoopUnrollCost(), areInnerLoopLatchPHIsSupported(), areOuterLoopExitPHIsSupported(), llvm::LoopAccessInfo::blockNeedsPredication(), breakBackedgeIfNotTaken(), llvm::breakLoopBackedge(), CalculateUnswitchCostMultiplier(), canFoldTermCondOfLoop(), canProveExitOnFirstIteration(), canRotateDeoptimizingLatchExit(), checkLoopsStructure(), checkPHIs(), cloneLoopBlocks(), CloneLoopBlocks(), llvm::InnerLoopVectorizer::completeLoopSkeleton(), ConnectEpilog(), ConnectProlog(), constantFoldTerminators(), countToEliminateCompares(), llvm::InnerLoopVectorizer::createVectorLoopSkeleton(), DoFlattenLoopPair(), findLoopComponents(), FindLoopCounter(), llvm::MachineLoopInfo::findLoopPreheader(), llvm::findSplitCandidate(), llvm::VPRecipeBuilder::fixHeaderPhis(), llvm::InnerLoopVectorizer::fixReduction(), llvm::InnerLoopVectorizer::fixupIVUsers(), getCastsForInductionPHI(), llvm::ScalarEvolution::getConstantMaxTripCountFromArray(), getExpectedExitLoopLatchBranch(), llvm::LoopNest::getInterveningInstructions(), getIVIncrement(), getMinAnalyzeableBackedgeTakenCount(), getOuterLoopLatchCmp(), llvm::hasIterationCountInvariantInParent(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), llvm::InductionDescriptor::isInductionPHI(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), isLoopCounter(), llvm::isSafeToUnrollAndJam(), IVUseShouldUsePostIncValue(), needsLFTR(), llvm::peelLoop(), peelToTurnInvariantLoadsDerefencebale(), ReduceLoopStrength(), llvm::SCEVExpander::replaceCongruentIVs(), simplifyOneLoop(), SplitBlockPredecessorsImpl(), llvm::splitLoopBound(), llvm::VPRecipeBuilder::tryToCreateWidenRecipe(), tryToUnrollAndJamLoop(), tryToUnrollLoop(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), updateLatchBranchWeightsForRemainderLoop(), and violatesLegacyMultiExitLoopCheck().
getLoopLatches()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::getLoopLatches (SmallVectorImpl< BlockT * > & LoopLatches) const inline
Return all loop latch blocks of this loop.
A latch block is a block that contains a branch back to the header.
Definition at line 351 of file LoopInfo.h.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::LoopBase< BlockT, LoopT >::getHeader(), H, and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by doesStoreDominatesAllLatches().
getLoopPredecessor()
template<class BlockT , class LoopT > BlockT * llvm::LoopBase< BlockT, LoopT >::getLoopPredecessor () const
If the given loop's header has exactly one unique predecessor outside the loop, return it.
getLoopPredecessor - If the given loop's header has exactly one unique predecessor outside the loop, return it.
Otherwise return null. This is less strict that the loop "preheader" concept, which requires the predecessor to have exactly one successor.
Definition at line 211 of file LoopInfoImpl.h.
References assert(), and contains().
Referenced by llvm::ScalarEvolution::applyLoopGuards(), canProveExitOnFirstIteration(), and llvm::GuardWideningPass::run().
getLoopPreheader()
template<class BlockT , class LoopT > BlockT * llvm::LoopBase< BlockT, LoopT >::getLoopPreheader () const
If there is a preheader for this loop, return it.
getLoopPreheader - If there is a preheader for this loop, return it.
A loop has a preheader if there is only one edge to the header of the loop from outside of the loop. If this is the case, the block branching to the header of the loop is the preheader node.
This method returns null if there is no preheader for the loop.
A loop has a preheader if there is only one edge to the header of the loop from outside of the loop and it is legal to hoist instructions into the predecessor. If this is the case, the block branching to the header of the loop is the preheader node.
This method returns null if there is no preheader for the loop.
Definition at line 183 of file LoopInfoImpl.h.
References assert(), and SI.
Referenced by llvm::RecurrenceDescriptor::AddReductionVar(), analyzeLoopUnrollCost(), buildPartialInvariantUnswitchConditionalBranch(), CanGenerateTest(), canLoopBeDeleted(), CanProveNotTakenFirstIteration(), checkIsIndPhi(), checkLoopsStructure(), checkOverflow(), checkPHIs(), cloneLoopBlocks(), llvm::cloneLoopWithPreheader(), llvm::InnerLoopVectorizer::createVectorLoopSkeleton(), createWidenInductionRecipes(), llvm::deleteDeadLoop(), deleteLoopIfDead(), detectPopcountIdiom(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), detectShiftUntilZeroIdiom(), DoFlattenLoopPair(), llvm::LoopVectorizationPlanner::executePlan(), findBBsToSinkInto(), llvm::MachineLoopInfo::findLoopPreheader(), FindWidenableTerminatorAboveLoop(), llvm::LoopNest::getInterveningInstructions(), GetLoopInvariantInsertPosition(), llvm::hoistRegion(), isEpilogProfitable(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), llvm::InductionDescriptor::isInductionPHI(), isLoopNeverExecuted(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::peelLoop(), preheader(), llvm::printLoop(), llvm::promoteLoopAccessesToScalars(), rebuildLoopAfterUnswitch(), recomputeLoopBlockSet(), ReduceLoopStrength(), replaceLoopPHINodesWithPreheaderValues(), llvm::LoopSinkPass::run(), simplifyOneLoop(), sinkLoopInvariantInstructions(), llvm::splitLoopBound(), llvm::VPRecipeBuilder::tryToCreateWidenRecipe(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), unswitchTrivialSwitch(), and llvm::LoopVersioning::versionLoop().
getLoopsInPreorder() [1/2]
template<class BlockT , class LoopT > SmallVector< LoopT *, 4 > llvm::LoopBase< BlockT, LoopT >::getLoopsInPreorder () inline
Definition at line 385 of file LoopInfo.h.
References llvm::LoopBase< BlockT, LoopT >::getInnerLoopsInPreorder().
getLoopsInPreorder() [2/2]
template<class BlockT , class LoopT > SmallVector< const LoopT *, 4 > llvm::LoopBase< BlockT, LoopT >::getLoopsInPreorder () const inline
Return all loops in the loop nest rooted by the loop in preorder, with siblings in forward program order.
Definition at line 378 of file LoopInfo.h.
References llvm::LoopBase< BlockT, LoopT >::getInnerLoopsInPreorder().
Referenced by checkDependencies(), llvm::cloneLoopWithPreheader(), llvm::isSafeToUnrollAndJam(), and partitionOuterLoopBlocks().
getNumBackEdges()
template<class BlockT , class LoopT > unsigned llvm::LoopBase< BlockT, LoopT >::getNumBackEdges () const inline
Calculate the number of back edges to the loop header.
Definition at line 267 of file LoopInfo.h.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::LoopBase< BlockT, LoopT >::getHeader(), H, and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), insertUniqueBackedgeBlock(), and simplifyOneLoop().
getNumBlocks()
template<class BlockT , class LoopT > unsigned llvm::LoopBase< BlockT, LoopT >::getNumBlocks () const inline
Get the number of blocks in this loop in constant time.
Invalidate the loop, indicating that it is no longer a loop.
Definition at line 202 of file LoopInfo.h.
References assert(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by llvm::LoopBlocksTraversal::begin(), buildClonedLoopBlocks(), llvm::LoopVectorizationLegality::canVectorize(), detectShiftUntilBitTestIdiom(), detectShiftUntilZeroIdiom(), llvm::ARMTTIImpl::getPreferredAddressingMode(), llvm::ARMTTIImpl::getUnrollingPreferences(), llvm::RISCVTTIImpl::getUnrollingPreferences(), llvm::LoopBlocksDFS::isComplete(), llvm::LoopBlocksDFS::LoopBlocksDFS(), and llvm::ARMTTIImpl::preferPredicateOverEpilogue().
getOutermostLoop() [1/2]
template<class BlockT , class LoopT > LoopT * llvm::LoopBase< BlockT, LoopT >::getOutermostLoop () inline
Definition at line 125 of file LoopInfo.h.
getOutermostLoop() [2/2]
template<class BlockT , class LoopT > const LoopT * llvm::LoopBase< BlockT, LoopT >::getOutermostLoop () const inline
Get the outermost loop in which this loop is contained.
This may be the loop itself, if it already is the outermost loop.
Definition at line 118 of file LoopInfo.h.
Referenced by llvm::breakLoopBackedge(), llvm::ScalarEvolution::forgetTopmostLoop(), and getOutermostLoop().
getParentLoop()
template<class BlockT , class LoopT > LoopT * llvm::LoopBase< BlockT, LoopT >::getParentLoop () const inline
Return the parent loop if it exists or nullptr for top level loops.
A loop is either top-level in a function (that is, it is not contained in any other loop) or it is entirely enclosed in some other loop. If a loop is top-level, it has no parent, otherwise its parent is the innermost loop in which it is enclosed.
Definition at line 114 of file LoopInfo.h.
Referenced by llvm::LPPassManager::addLoop(), CalculateUnswitchCostMultiplier(), checkLoopsStructure(), cloneLoopBlocks(), CloneLoopBlocks(), llvm::cloneLoopWithPreheader(), llvm::deleteDeadLoop(), emitBasicBlockLoopComments(), llvm::LoopInfo::erase(), Flatten(), llvm::SITargetLowering::getPrefLoopAlignment(), getTopMostExitingLoop(), llvm::hasIterationCountInvariantInParent(), hoistLoopToNewParent(), llvm::LoopBase< BlockT, LoopT >::isOutermost(), llvm::peelLoop(), llvm::ScalarEvolution::print(), PrintParentLoopComment(), rebuildLoopAfterUnswitch(), llvm::rewriteLoopExitValues(), llvm::FunctionToLoopPassAdaptor::run(), llvm::LoopUnrollPass::run(), llvm::LoopFullUnrollPass::run(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::runWithoutLoopNestPasses(), separateNestedLoop(), tryToUnrollLoop(), unifyLoopExits(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), and unswitchNontrivialInvariants().
getSubLoops()
template<class BlockT , class LoopT > const std::vector< LoopT * > & llvm::LoopBase< BlockT, LoopT >::getSubLoops () const inline
Return the loops contained entirely within this loop.
Definition at line 160 of file LoopInfo.h.
References assert(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by areInnerLoopLatchPHIsSupported(), llvm::LoopBase< BlockT, LoopT >::begin(), checkLoopsStructure(), dependsOnLocalPhi(), llvm::LoopBase< BlockT, LoopT >::end(), llvm::formLCSSARecursively(), getInnerMostLoop(), llvm::LoopNest::getMaxPerfectDepth(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), isEligibleLoopForm(), llvm::LoopBase< BlockT, LoopT >::isInnermost(), llvm::isSafeToUnrollAndJam(), partitionLoopBlocks(), populateWorklist(), llvm::LoopBase< BlockT, LoopT >::rbegin(), llvm::LoopBase< BlockT, LoopT >::rend(), separateNestedLoop(), tryToUnrollAndJamLoop(), and llvm::UnrollAndJamLoop().
getSubLoopsVector()
template<class BlockT , class LoopT > std::vector< LoopT * > & llvm::LoopBase< BlockT, LoopT >::getSubLoopsVector () inline
Definition at line 164 of file LoopInfo.h.
References assert(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by deleteDeadBlocksFromLoop(), and rebuildLoopAfterUnswitch().
getUniqueExitBlock()
template<class BlockT , class LoopT > BlockT * llvm::LoopBase< BlockT, LoopT >::getUniqueExitBlock () const
If getUniqueExitBlocks would return exactly one block, return that block.
Otherwise return null.
Definition at line 158 of file LoopInfoImpl.h.
References llvm::getExitBlockHelper().
Referenced by addUsersInExitBlock(), areOuterLoopExitPHIsSupported(), llvm::InnerLoopVectorizer::createVectorLoopSkeleton(), llvm::deleteDeadLoop(), deleteLoopIfDead(), llvm::MustBeExecutedContextExplorer::findForwardJoinPoint(), llvm::InnerLoopVectorizer::fixupIVUsers(), and llvm::LoopVersioning::versionLoop().
getUniqueExitBlocks()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::getUniqueExitBlocks (SmallVectorImpl< BlockT * > & ExitBlocks) const
Return all unique successor blocks of this loop.
These are the blocks outside of the current loop which are branched to.
Definition at line 142 of file LoopInfoImpl.h.
References llvm::getUniqueExitBlocksHelper().
Referenced by canLoopBeDeleted(), canRotateDeoptimizingLatchExit(), isSafeForNoNTrivialUnswitching(), llvm::rewriteLoopExitValues(), sink(), splitPredecessorsOfLoopExit(), and unswitchNontrivialInvariants().
getUniqueNonLatchExitBlocks()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::getUniqueNonLatchExitBlocks (SmallVectorImpl< BlockT * > & ExitBlocks) const
Return all unique successor blocks of this loop except successors from Latch block are not considered.
If the exit comes from Latch has also non Latch predecessor in a loop it will be added to ExitBlocks. These are the blocks outside of the current loop which are branched to.
Definition at line 149 of file LoopInfoImpl.h.
References assert(), and llvm::getUniqueExitBlocksHelper().
Referenced by llvm::canPeel(), peelToTurnInvariantLoadsDerefencebale(), llvm::UnrollRuntimeLoopRemainder(), and violatesLegacyMultiExitLoopCheck().
hasDedicatedExits()
template<class BlockT , class LoopT > bool llvm::LoopBase< BlockT, LoopT >::hasDedicatedExits () const
Return true if no exit block for the loop has a predecessor that is outside the loop.
Definition at line 112 of file LoopInfoImpl.h.
References contains(), and llvm::ilist_node_impl< OptionsT >::ilist_node_impl().
Referenced by llvm::deleteDeadLoop(), and deleteLoopIfDead().
hasNoExitBlocks()
template<class BlockT , class LoopT > bool llvm::LoopBase< BlockT, LoopT >::hasNoExitBlocks () const
Return true if this loop does not have any exit blocks.
Definition at line 95 of file LoopInfoImpl.h.
References llvm::getExitBlockHelper().
Referenced by llvm::deleteDeadLoop(), deleteLoopIfDead(), and isLoopDead().
isAnnotatedParallel()
template<class BlockT , class LoopT > bool llvm::LoopBase< BlockT, LoopT >::isAnnotatedParallel () const inline
Returns true if the loop is annotated parallel.
Derived classes can override this method using static template polymorphism.
Definition at line 496 of file LoopInfo.h.
isInnermost()
template<class BlockT , class LoopT > bool llvm::LoopBase< BlockT, LoopT >::isInnermost () const inline
Return true if the loop does not contain any (natural) loops.
Definition at line 182 of file LoopInfo.h.
References llvm::LoopBase< BlockT, LoopT >::getSubLoops().
Referenced by analyzeLoopUnrollCost(), canFoldTermCondOfLoop(), llvm::canSplitLoopBound(), llvm::LoopVectorizationLegality::canVectorize(), collectSupportedLoops(), llvm::computePeelCount(), eliminateLoadsAcrossLoops(), emitBasicBlockLoopComments(), llvm::LoopInfo::erase(), llvm::ScalarEvolution::getConstantMaxTripCountFromArray(), llvm::HexagonTTIImpl::getPeelingPreferences(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), llvm::LoopVectorizationPlanner::plan(), llvm::LoopVectorizationPlanner::planInVPlanNativePath(), llvm::ARMTTIImpl::preferPredicateOverEpilogue(), llvm::LoopVectorizePass::processLoop(), and runImpl().
isInvalid()
template<class BlockT , class LoopT > bool llvm::LoopBase< BlockT, LoopT >::isInvalid () const inline
Return true if this loop is no longer valid.
The only valid use of this helper is "assert(L.isInvalid())" or equivalent, since IsInvalid is set to true by the destructor. In other words, if this accessor returns true, the caller has already triggered UB by calling this accessor; and so it can only be called in a context where a return value of true indicates a programmer error.
Definition at line 232 of file LoopInfo.h.
Referenced by llvm::LoopBase< BlockT, LoopT >::addBlockEntry(), llvm::LoopBase< BlockT, LoopT >::addChildLoop(), llvm::LoopBase< BlockT, LoopT >::blocks(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::LoopInfo::erase(), llvm::LoopBase< BlockT, LoopT >::getBlocks(), llvm::LoopBase< BlockT, LoopT >::getBlocksSet(), llvm::LoopBase< BlockT, LoopT >::getBlocksSet(), llvm::LoopBase< BlockT, LoopT >::getBlocksVector(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::LoopBase< BlockT, LoopT >::getLoopLatches(), llvm::LoopBase< BlockT, LoopT >::getNumBackEdges(), llvm::LoopBase< BlockT, LoopT >::getNumBlocks(), llvm::LoopBase< BlockT, LoopT >::getSubLoops(), llvm::LoopBase< BlockT, LoopT >::getSubLoopsVector(), llvm::LoopBase< BlockT, LoopT >::isLoopExiting(), llvm::LoopBase< BlockT, LoopT >::isLoopLatch(), llvm::LoopBase< BlockT, LoopT >::moveToHeader(), llvm::LoopBase< BlockT, LoopT >::removeBlockFromLoop(), llvm::LoopBase< BlockT, LoopT >::removeChildLoop(), llvm::LoopBase< BlockT, LoopT >::reserveBlocks(), llvm::LoopBase< BlockT, LoopT >::reverseBlock(), and llvm::LoopBase< BlockT, LoopT >::setParentLoop().
isLoopExiting()
template<class BlockT , class LoopT > bool llvm::LoopBase< BlockT, LoopT >::isLoopExiting (const BlockT * BB) const inline
True if terminator in the block can branch to another block that is outside of the current loop.
BB must be inside the loop.
Definition at line 242 of file LoopInfo.h.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by llvm::breakLoopBackedge(), llvm::VPRecipeBuilder::createEdgeMask(), getExpectedExitLoopLatchBranch(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), getTopMostExitingLoop(), llvm::AMDGPUTTIImpl::getUnrollingPreferences(), mustBeFiniteCountedLoop(), tryToUnrollLoop(), llvm::UnrollLoop(), violatesLegacyMultiExitLoopCheck(), and llvm::VirtRegAuxInfo::weightCalcHelper().
isLoopLatch()
template<class BlockT , class LoopT > bool llvm::LoopBase< BlockT, LoopT >::isLoopLatch (const BlockT * BB) const inline
Definition at line 256 of file LoopInfo.h.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::LoopBase< BlockT, LoopT >::getHeader(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by llvm::HardwareLoopInfo::isHardwareLoopCandidate().
isOutermost()
template<class BlockT , class LoopT > bool llvm::LoopBase< BlockT, LoopT >::isOutermost () const inline
Return true if the loop does not have a parent (natural) loop.
Definition at line 185 of file LoopInfo.h.
References llvm::LoopBase< BlockT, LoopT >::getParentLoop().
Referenced by llvm::LPPassManager::addLoop(), llvm::LoopInfo::erase(), llvm::CacheCost::getCacheCost(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::run(), and llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::runWithLoopNestPasses().
moveToHeader()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::moveToHeader (BlockT * BB) inline
This method is used to move BB (which must be part of this loop) to be the loop header of the loop (the block that dominates all others).
Definition at line 460 of file LoopInfo.h.
References assert(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by separateNestedLoop(), and UpdateAnalysisInformation().
print()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::print (raw_ostream & OS, bool Verbose = false, bool PrintNested = true, unsigned Depth = 0) const
Print loop with all the BBs inside it.
Definition at line 394 of file LoopInfoImpl.h.
References llvm::Depth, H, and llvm::raw_ostream::indent().
Referenced by llvm::operator<<().
rbegin()
template<class BlockT , class LoopT > reverse_iterator llvm::LoopBase< BlockT, LoopT >::rbegin () const inline
Definition at line 173 of file LoopInfo.h.
References llvm::LoopBase< BlockT, LoopT >::getSubLoops().
removeBlockFromLoop()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::removeBlockFromLoop (BlockT * BB) inline
This removes the specified basic block from the current loop, updating the Blocks as appropriate.
This does not update the mapping in the LoopInfo class.
Definition at line 477 of file LoopInfo.h.
References assert(), llvm::find(), I, and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by separateNestedLoop().
removeChildLoop() [1/2]
template<class BlockT , class LoopT > LoopT * llvm::LoopBase< BlockT, LoopT >::removeChildLoop (iterator I) inline
This removes the specified child from being a subloop of this loop.
The loop is not deleted, as it will presumably be inserted into another loop.
Definition at line 421 of file LoopInfo.h.
References assert(), I, and llvm::LoopBase< BlockT, LoopT >::isInvalid().
Referenced by llvm::LoopInfo::erase(), rebuildLoopAfterUnswitch(), llvm::LoopBase< BlockT, LoopT >::removeChildLoop(), and separateNestedLoop().
removeChildLoop() [2/2]
template<class BlockT , class LoopT > LoopT * llvm::LoopBase< BlockT, LoopT >::removeChildLoop (LoopT * Child) inline
This removes the specified child from being a subloop of this loop.
The loop is not deleted, as it will presumably be inserted into another loop.
Definition at line 433 of file LoopInfo.h.
References llvm::find(), and llvm::LoopBase< BlockT, LoopT >::removeChildLoop().
rend()
template<class BlockT , class LoopT > reverse_iterator llvm::LoopBase< BlockT, LoopT >::rend () const inline
Definition at line 174 of file LoopInfo.h.
References llvm::LoopBase< BlockT, LoopT >::getSubLoops().
replaceChildLoopWith()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::replaceChildLoopWith (LoopT * OldChild, LoopT * NewChild)
This is used when splitting loops up.
replaceChildLoopWith - This is used when splitting loops up.
It replaces the OldChild entry in our children list with NewChild, and updates the parent pointer of OldChild to be null and the NewChild to be this loop. This updates the loop depth of the new child.
Definition at line 288 of file LoopInfoImpl.h.
Referenced by separateNestedLoop().
reserveBlocks()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::reserveBlocks (unsigned size) inline
interface to do reserve() for Blocks
Definition at line 453 of file LoopInfo.h.
References assert(), llvm::LoopBase< BlockT, LoopT >::isInvalid(), and size().
reverseBlock()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::reverseBlock (unsigned from) inline
interface to reverse Blocks[from, end of loop] in this loop
Definition at line 447 of file LoopInfo.h.
References assert(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
setParentLoop()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::setParentLoop (LoopT * L) inline
This is a raw interface for bypassing addChildLoop.
Definition at line 133 of file LoopInfo.h.
References assert(), and llvm::LoopBase< BlockT, LoopT >::isInvalid().
verifyLoop()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::verifyLoop () const
Verify loop structure.
verifyLoop - Verify loop structure
Definition at line 302 of file LoopInfoImpl.h.
Referenced by createNaturalLoopInternal(), llvm::FunctionToLoopPassAdaptor::run(), llvm::LPPassManager::runOnFunction(), and unifyLoopExits().
verifyLoopNest()
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::verifyLoopNest (DenseSet< const LoopT * > * Loops) const
Verify loop structure of this loop and all nested loops.
verifyLoop - Verify loop structure of this loop and all nested loops.
Definition at line 382 of file LoopInfoImpl.h.
References assert(), E, I, and Loops.
Friends And Related Symbol Documentation
LoopInfoBase< BlockT, LoopT >
template<class BlockT , class LoopT > friend class LoopInfoBase< BlockT, LoopT > friend
Definition at line 499 of file LoopInfo.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/LoopInfo.h
include/llvm/Analysis/LoopInfoImpl.h