LLVM: llvm::GVNExpression::LoadExpression Class Reference
llvm::GVNExpression::LoadExpression Class Reference final
#include "llvm/Transforms/Scalar/GVNExpression.h"
Public Member Functions
LoadExpression (unsigned NumOperands, LoadInst *L, const MemoryAccess *MemoryLeader)
LoadExpression (enum ExpressionType EType, unsigned NumOperands, LoadInst *L, const MemoryAccess *MemoryLeader)
LoadExpression ()=delete
LoadExpression (const LoadExpression &)=delete
LoadExpression & operator= (const LoadExpression &)=delete
~LoadExpression () override
LoadInst * getLoadInst () const
void setLoadInst (LoadInst *L)
bool equals (const Expression &Other) const override
bool exactlyEquals (const Expression &Other) const override
void printInternal (raw_ostream &OS, bool PrintEType) const override
Public Member Functions inherited from llvm::GVNExpression::MemoryExpression
MemoryExpression (unsigned NumOperands, enum ExpressionType EType, const MemoryAccess *MemoryLeader)
MemoryExpression ()=delete
MemoryExpression (const MemoryExpression &)=delete
MemoryExpression & operator= (const MemoryExpression &)=delete
hash_code getHashValue () const override
bool equals (const Expression &Other) const override
const MemoryAccess * getMemoryLeader () const
void setMemoryLeader (const MemoryAccess *ML)
Public Member Functions inherited from llvm::GVNExpression::BasicExpression
BasicExpression (unsigned NumOperands)
BasicExpression (unsigned NumOperands, ExpressionType ET)
BasicExpression ()=delete
BasicExpression (const BasicExpression &)=delete
BasicExpression & operator= (const BasicExpression &)=delete
~BasicExpression () override
void swapOperands (unsigned First, unsigned Second)
Swap two operands.
Value * getOperand (unsigned N) const
void setOperand (unsigned N, Value *V)
unsigned getNumOperands () const
op_iterator op_begin ()
op_iterator op_end ()
const_op_iterator op_begin () const
const_op_iterator op_end () const
iterator_range< op_iterator > operands ()
iterator_range< const_op_iterator > operands () const
void op_push_back (Value *Arg)
bool op_empty () const
void allocateOperands (RecyclerType &Recycler, BumpPtrAllocator &Allocator)
void deallocateOperands (RecyclerType &Recycler)
void setType (Type *T)
Type * getType () const
Public Member Functions inherited from llvm::GVNExpression::Expression
Expression (ExpressionType ET=ET_Base, unsigned O=~2U)
Expression (const Expression &)=delete
Expression & operator= (const Expression &)=delete
virtual ~Expression ()
bool operator!= (const Expression &Other) const
bool operator== (const Expression &Other) const
hash_code getComputedHash () const
unsigned getOpcode () const
void setOpcode (unsigned opcode)
ExpressionType getExpressionType () const
void print (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Static Public Member Functions
static bool classof (const Expression *EB)
Static Public Member Functions inherited from llvm::GVNExpression::MemoryExpression
static bool classof (const Expression *EB)
Static Public Member Functions inherited from llvm::GVNExpression::BasicExpression
static bool classof (const Expression *EB)
Static Public Member Functions inherited from llvm::GVNExpression::Expression
static unsigned getEmptyKey ()
static unsigned getTombstoneKey ()
Additional Inherited Members
Public Types inherited from llvm::GVNExpression::BasicExpression
using op_iterator = Value **
using const_op_iterator = Value *const *
Detailed Description
Definition at line 328 of file GVNExpression.h.
Constructor & Destructor Documentation
LoadExpression() [1/4]
llvm::GVNExpression::LoadExpression::LoadExpression (unsigned NumOperands, LoadInst * L, const MemoryAccess * MemoryLeader) inline
Definition at line 333 of file GVNExpression.h.
LoadExpression() [2/4]
llvm::GVNExpression::LoadExpression::LoadExpression (enum ExpressionType EType, unsigned NumOperands, LoadInst * L, const MemoryAccess * MemoryLeader) inline
Definition at line 337 of file GVNExpression.h.
LoadExpression() [3/4]
llvm::GVNExpression::LoadExpression::LoadExpression () delete
LoadExpression() [4/4]
llvm::GVNExpression::LoadExpression::LoadExpression (const LoadExpression &) delete
~LoadExpression()
llvm::GVNExpression::LoadExpression::~LoadExpression () override default
Member Function Documentation
classof()
static bool llvm::GVNExpression::LoadExpression::classof (const Expression * EB) inline static
Definition at line 346 of file GVNExpression.h.
References llvm::GVNExpression::ET_Load, and llvm::GVNExpression::Expression::getExpressionType().
equals()
bool LoadExpression::equals (const Expression & Other) const override virtual
Reimplemented from llvm::GVNExpression::BasicExpression.
Definition at line 910 of file NewGVN.cpp.
References equalsLoadStoreHelper(), and llvm::Other.
exactlyEquals()
bool llvm::GVNExpression::LoadExpression::exactlyEquals (const Expression & Other) const inline override virtual
Reimplemented from llvm::GVNExpression::Expression.
Definition at line 354 of file GVNExpression.h.
References llvm::GVNExpression::Expression::exactlyEquals(), getLoadInst(), and llvm::Other.
getLoadInst()
LoadInst * llvm::GVNExpression::LoadExpression::getLoadInst () const inline
Definition at line 350 of file GVNExpression.h.
Referenced by exactlyEquals().
operator=()
LoadExpression & llvm::GVNExpression::LoadExpression::operator= (const LoadExpression &) delete
printInternal()
void llvm::GVNExpression::LoadExpression::printInternal (raw_ostream & OS, bool PrintEType) const inline override virtual
Reimplemented from llvm::GVNExpression::BasicExpression.
Definition at line 360 of file GVNExpression.h.
References llvm::GVNExpression::MemoryExpression::getMemoryLeader(), and llvm::GVNExpression::BasicExpression::printInternal().
setLoadInst()
void llvm::GVNExpression::LoadExpression::setLoadInst (LoadInst * L) inline
Definition at line 351 of file GVNExpression.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/GVNExpression.h
lib/Transforms/Scalar/NewGVN.cpp