LLVM: llvm::DWARFDebugMacro Class Reference
llvm::DWARFDebugMacro Class Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugMacro.h"
Public Member Functions
DWARFDebugMacro ()=default
void dump (raw_ostream &OS) const
Print the macro list found within the debug_macinfo/debug_macro section.
Error parseMacro (DWARFUnitVector::compile_unit_range Units, DataExtractor StringExtractor, DWARFDataExtractor MacroData)
Error parseMacinfo (DWARFDataExtractor MacroData)
bool empty () const
Return whether the section has any entries.
bool hasEntryForOffset (uint64_t Offset) const
Detailed Description
Definition at line 23 of file DWARFDebugMacro.h.
Constructor & Destructor Documentation
DWARFDebugMacro()
llvm::DWARFDebugMacro::DWARFDebugMacro () default
Member Function Documentation
dump()
void DWARFDebugMacro::dump (raw_ostream & OS) const
Print the macro list found within the debug_macinfo/debug_macro section.
Definition at line 42 of file DWARFDebugMacro.cpp.
References llvm::dwarf::DW_MACINFO_end_file, llvm::dwarf::DW_MACINFO_start_file, llvm::dwarf::DW_MACINFO_vendor_ext, E, llvm::format(), llvm::WithColor::get(), llvm::dwarf::GnuMacroString(), I, llvm::dwarf::MacinfoString(), llvm::Macro, and llvm::dwarf::MacroString().
empty()
bool llvm::DWARFDebugMacro::empty () const inline
Return whether the section has any entries.
Definition at line 126 of file DWARFDebugMacro.h.
hasEntryForOffset()
bool llvm::DWARFDebugMacro::hasEntryForOffset (uint64_t Offset) const inline
Definition at line 128 of file DWARFDebugMacro.h.
References llvm::List, and llvm::Offset.
parseMacinfo()
Error llvm::DWARFDebugMacro::parseMacinfo (DWARFDataExtractor MacroData) inline
Definition at line 121 of file DWARFDebugMacro.h.
parseMacro()
Error llvm::DWARFDebugMacro::parseMacro (DWARFUnitVector::compile_unit_range Units, DataExtractor StringExtractor, DWARFDataExtractor MacroData) inline
Definition at line 115 of file DWARFDebugMacro.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugMacro.h
lib/DebugInfo/DWARF/DWARFDebugMacro.cpp