LLVM: llvm::SymbolRemappingParseError Class Reference
llvm::SymbolRemappingParseError Class Reference
#include "llvm/Support/SymbolRemappingReader.h"
Public Member Functions
SymbolRemappingParseError (StringRef File, int64_t Line, const Twine &Message)
void log (llvm::raw_ostream &OS) const override
Print an error message to an output stream.
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
StringRef getFileName () const
int64_t getLineNum () const
StringRef getMessage () const
Public Member Functions inherited from llvm::ErrorInfo< SymbolRemappingParseError >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual std::string message () const
Return the error message as a string.
template<typename ErrorInfoT >
bool isA () const
Static Public Attributes
static char ID
Additional Inherited Members
Static Public Member Functions inherited from llvm::ErrorInfo< SymbolRemappingParseError >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Detailed Description
Definition at line 70 of file SymbolRemappingReader.h.
Constructor & Destructor Documentation
SymbolRemappingParseError()
llvm::SymbolRemappingParseError::SymbolRemappingParseError (StringRef File, int64_t Line, const Twine & Message) inline
Definition at line 72 of file SymbolRemappingReader.h.
Member Function Documentation
convertToErrorCode()
std::error_code llvm::SymbolRemappingParseError::convertToErrorCode () const inline override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 78 of file SymbolRemappingReader.h.
References llvm::inconvertibleErrorCode().
getFileName()
StringRef llvm::SymbolRemappingParseError::getFileName () const inline
Definition at line 82 of file SymbolRemappingReader.h.
getLineNum()
int64_t llvm::SymbolRemappingParseError::getLineNum () const inline
Definition at line 83 of file SymbolRemappingReader.h.
Referenced by llvm::sampleprof::SampleProfileReaderItaniumRemapper::create().
getMessage()
StringRef llvm::SymbolRemappingParseError::getMessage () const inline
Definition at line 84 of file SymbolRemappingReader.h.
Referenced by llvm::sampleprof::SampleProfileReaderItaniumRemapper::create().
log()
void llvm::SymbolRemappingParseError::log (llvm::raw_ostream & OS) const inline override virtual
Print an error message to an output stream.
Implements llvm::ErrorInfoBase.
Definition at line 75 of file SymbolRemappingReader.h.
Member Data Documentation
ID
char SymbolRemappingParseError::ID static
Definition at line 86 of file SymbolRemappingReader.h.
The documentation for this class was generated from the following files:
include/llvm/Support/SymbolRemappingReader.h
lib/Support/SymbolRemappingReader.cpp