LLVM: llvm::logicalview::LVLocationSymbol Class Reference
llvm::logicalview::LVLocationSymbol Class Reference final
#include "llvm/DebugInfo/LogicalView/Core/LVLocation.h"
Public Member Functions
LVLocationSymbol ()
LVLocationSymbol (const LVLocationSymbol &)=delete
LVLocationSymbol & operator= (const LVLocationSymbol &)=delete
~LVLocationSymbol ()
void addObject (LVAddress LowPC, LVAddress HighPC, LVUnsigned SectionOffset, uint64_t LocDescOffset) override
void addObject (LVSmall Opcode, LVUnsigned Operand1, LVUnsigned Operand2) override
void printRawExtra (raw_ostream &OS, bool Full=true) const override
void printExtra (raw_ostream &OS, bool Full=true) const override
Public Member Functions inherited from llvm::logicalview::LVLocation
LVLocation ()
LVLocation (const LVLocation &)=delete
LVLocation & operator= (const LVLocation &)=delete
virtual ~LVLocation ()=default
PROPERTY (Property, IsAddressRange)
PROPERTY (Property, IsBaseClassOffset)
PROPERTY (Property, IsBaseClassStep)
PROPERTY_1 (Property, IsClassOffset, IsLocationSimple)
PROPERTY_1 (Property, IsFixedAddress, IsLocationSimple)
PROPERTY (Property, IsLocationSimple)
PROPERTY (Property, IsGapEntry)
PROPERTY (Property, IsOperationList)
PROPERTY (Property, IsOperation)
PROPERTY (Property, IsRegister)
PROPERTY_1 (Property, IsStackOffset, IsLocationSimple)
PROPERTY (Property, IsDiscardedRange)
PROPERTY (Property, IsInvalidRange)
PROPERTY (Property, IsInvalidLower)
PROPERTY (Property, IsInvalidUpper)
PROPERTY (Property, IsCallSite)
const char * kind () const override
const LVLine * getLowerLine () const
void setLowerLine (LVLine *Line)
const LVLine * getUpperLine () const
void setUpperLine (LVLine *Line)
LVAddress getLowerAddress () const override
void setLowerAddress (LVAddress Address) override
LVAddress getUpperAddress () const override
void setUpperAddress (LVAddress Address) override
std::string getIntervalInfo () const
bool validateRanges ()
void printInterval (raw_ostream &OS, bool Full=true) const
void printRaw (raw_ostream &OS, bool Full=true) const
void print (raw_ostream &OS, bool Full=true) const override
void dump () const override
Public Member Functions inherited from llvm::logicalview::LVObject
LVObject ()
LVObject & operator= (const LVObject &)=delete
virtual ~LVObject ()=default
PROPERTY (Property, IsLocation)
PROPERTY (Property, IsGlobalReference)
PROPERTY (Property, IsGeneratedName)
PROPERTY (Property, IsResolved)
PROPERTY (Property, IsResolvedName)
PROPERTY (Property, IsDiscarded)
PROPERTY (Property, IsOptimized)
PROPERTY (Property, IsAdded)
PROPERTY (Property, IsMatched)
PROPERTY (Property, IsMissing)
PROPERTY (Property, IsMissingLink)
PROPERTY (Property, IsInCompare)
PROPERTY (Property, IsFileFromReference)
PROPERTY (Property, IsLineFromReference)
PROPERTY (Property, HasMoved)
PROPERTY (Property, HasPattern)
PROPERTY (Property, IsFinalized)
PROPERTY (Property, IsReferenced)
PROPERTY (Property, HasCodeViewLocation)
virtual bool isNamed () const
virtual bool isTyped () const
virtual bool isFiled () const
bool isLined () const
dwarf::Tag getTag () const
void setTag (dwarf::Tag Tag)
dwarf::Attribute getAttr () const
void setAttr (dwarf::Attribute Attr)
LVSmall getOpcode () const
void setOpcode (LVSmall Opcode)
LVOffset getOffset () const
void setOffset (LVOffset DieOffset)
LVLevel getLevel () const
void setLevel (LVLevel Level)
virtual StringRef getName () const
virtual void setName (StringRef ObjectName)
LVElement * getParent () const
LVScope * getParentScope () const
LVSymbol * getParentSymbol () const
void setParent (LVScope *Scope)
void setParent (LVSymbol *Symbol)
void resetParent ()
uint32_t getLineNumber () const
void setLineNumber (uint32_t Number)
std::string indentAsString () const
std::string indentAsString (LVLevel Level) const
virtual std::string noLineAsString (bool ShowZero) const
virtual std::string lineNumberAsString (bool ShowZero=false) const
std::string lineNumberAsStringStripped (bool ShowZero=false) const
virtual Error doPrint (bool Split, bool Match, bool Print, raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full, StringRef Name, LVObject *Parent, StringRef Value, bool UseQuotes=false, bool PrintRef=false) const
void markBranchAsMissing ()
uint64_t getID () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::logicalview::LVLocation
static bool calculateCoverage (LVLocations *Locations, unsigned &Factor, float &Percentage)
static void print (LVLocations *Locations, raw_ostream &OS, bool Full=true)
Protected Member Functions inherited from llvm::logicalview::LVLocation
void setKind ()
Protected Member Functions inherited from llvm::logicalview::LVObject
std::string lineAsString (uint32_t LineNumber, LVHalf Discriminator, bool ShowZero) const
std::string referenceAsString (uint32_t LineNumber, bool Spaces) const
virtual void printFileIndex (raw_ostream &OS, bool Full=true) const
Protected Attributes inherited from llvm::logicalview::LVLocation
LVLine * LowerLine = nullptr
LVLine * UpperLine = nullptr
LVAddress LowPC = 0
LVAddress HighPC = 0
Detailed Description
Definition at line 173 of file LVLocation.h.
Constructor & Destructor Documentation
LVLocationSymbol() [1/2]
llvm::logicalview::LVLocationSymbol::LVLocationSymbol () inline
Definition at line 180 of file LVLocation.h.
LVLocationSymbol() [2/2]
llvm::logicalview::LVLocationSymbol::LVLocationSymbol (const LVLocationSymbol &) delete
~LVLocationSymbol()
llvm::logicalview::LVLocationSymbol::~LVLocationSymbol () inline
Definition at line 183 of file LVLocation.h.
Member Function Documentation
addObject() [1/2]
void LVLocationSymbol::addObject (LVAddress LowPC, LVAddress HighPC, LVUnsigned SectionOffset, uint64_t LocDescOffset) override virtual
Reimplemented from llvm::logicalview::LVLocation.
Definition at line 561 of file LVLocation.cpp.
References llvm::logicalview::LVLocation::HighPC, llvm::logicalview::LVLocation::LowPC, llvm::logicalview::LVLocation::setKind(), llvm::logicalview::LVLocation::setLowerAddress(), llvm::logicalview::LVObject::setOffset(), llvm::logicalview::LVLocation::setUpperAddress(), and UINT64_MAX.
addObject() [2/2]
void LVLocationSymbol::addObject (LVSmall Opcode, LVUnsigned Operand1, LVUnsigned Operand2) override virtual
Reimplemented from llvm::logicalview::LVLocation.
Definition at line 579 of file LVLocation.cpp.
References llvm::logicalview::LVObject::Opcode.
operator=()
LVLocationSymbol & llvm::logicalview::LVLocationSymbol::operator= (const LVLocationSymbol &) delete
printExtra()
void LVLocationSymbol::printExtra (raw_ostream & OS, bool Full = true) const override virtual
Reimplemented from llvm::logicalview::LVLocation.
Definition at line 652 of file LVLocation.cpp.
References llvm::Full, llvm::logicalview::LVObject::getParentSymbol(), Operation, llvm::logicalview::LVObject::printAttributes(), and llvm::logicalview::LVLocation::printInterval().
printRawExtra()
void LVLocationSymbol::printRawExtra (raw_ostream & OS, bool Full = true) const override virtual
Reimplemented from llvm::logicalview::LVLocation.
Definition at line 615 of file LVLocation.cpp.
References llvm::Full, and Operation.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVLocation.h
lib/DebugInfo/LogicalView/Core/LVLocation.cpp