LLVM: llvm::codeview::CVSymbolVisitor Class Reference
llvm::codeview::CVSymbolVisitor Class Reference
#include "llvm/DebugInfo/CodeView/CVSymbolVisitor.h"
Classes
struct FilterOptions
Public Member Functions
CVSymbolVisitor (SymbolVisitorCallbacks &Callbacks)
Error visitSymbolRecord (CVSymbol &Record)
Error visitSymbolRecord (CVSymbol &Record, uint32_t Offset)
Error visitSymbolStream (const CVSymbolArray &Symbols)
Error visitSymbolStream (const CVSymbolArray &Symbols, uint32_t InitialOffset)
Error visitSymbolStreamFiltered (const CVSymbolArray &Symbols, const FilterOptions &Filter)
Detailed Description
Definition at line 19 of file CVSymbolVisitor.h.
Constructor & Destructor Documentation
CVSymbolVisitor()
CVSymbolVisitor::CVSymbolVisitor (SymbolVisitorCallbacks & Callbacks)
Definition at line 21 of file CVSymbolVisitor.cpp.
Member Function Documentation
visitSymbolRecord() [1/2]
Error CVSymbolVisitor::visitSymbolRecord (CVSymbol & Record)
Definition at line 58 of file CVSymbolVisitor.cpp.
References llvm::codeview::EC, finishVisitation(), and llvm::codeview::SymbolVisitorCallbacks::visitSymbolBegin().
Referenced by llvm::codeview::CVSymbolDumper::dump(), visitSymbolStream(), visitSymbolStream(), and visitSymbolStreamFiltered().
visitSymbolRecord() [2/2]
Error CVSymbolVisitor::visitSymbolRecord (CVSymbol & Record, uint32_t Offset)
Definition at line 64 of file CVSymbolVisitor.cpp.
References llvm::codeview::EC, finishVisitation(), llvm::Offset, and llvm::codeview::SymbolVisitorCallbacks::visitSymbolBegin().
visitSymbolStream() [1/2]
Error CVSymbolVisitor::visitSymbolStream (const CVSymbolArray & Symbols)
Definition at line 70 of file CVSymbolVisitor.cpp.
References llvm::codeview::EC, I, llvm::Error::success(), llvm::codeview::Symbols, and visitSymbolRecord().
Referenced by llvm::codeview::CVSymbolDumper::dump(), and visitSymbolStreamFiltered().
visitSymbolStream() [2/2]
Error CVSymbolVisitor::visitSymbolStream (const CVSymbolArray & Symbols, uint32_t InitialOffset)
Definition at line 78 of file CVSymbolVisitor.cpp.
References llvm::codeview::EC, I, llvm::Error::success(), llvm::codeview::Symbols, and visitSymbolRecord().
visitSymbolStreamFiltered()
Error CVSymbolVisitor::visitSymbolStreamFiltered (const CVSymbolArray & Symbols, const FilterOptions & Filter)
Definition at line 88 of file CVSymbolVisitor.cpp.
References llvm::createStringError(), llvm::codeview::EC, llvm::Filter, llvm::codeview::getScopeEndOffset(), llvm::inconvertibleErrorCode(), llvm::codeview::CVRecord< Kind >::kind(), llvm::Error::success(), llvm::codeview::symbolEndsScope(), llvm::codeview::symbolOpensScope(), llvm::codeview::Symbols, visitSymbolRecord(), and visitSymbolStream().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/CVSymbolVisitor.h
lib/DebugInfo/CodeView/CVSymbolVisitor.cpp