LLVM: llvm::TLSVariableHoistPass Class Reference
llvm::TLSVariableHoistPass Class Reference
#include "llvm/Transforms/Scalar/TLSVariableHoist.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
bool runImpl (Function &F, DominatorTree &DT, LoopInfo &LI)
Optimize expensive TLS variables in the given function.
Public Member Functions inherited from llvm::PassInfoMixin< TLSVariableHoistPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< TLSVariableHoistPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 103 of file TLSVariableHoist.h.
Member Function Documentation
run()
PreservedAnalyses TLSVariableHoistPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 282 of file TLSVariableHoist.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserveSet(), and runImpl().
runImpl()
bool TLSVariableHoistPass::runImpl (Function & F, DominatorTree & DT, LoopInfo & LI)
Optimize expensive TLS variables in the given function.
Definition at line 262 of file TLSVariableHoist.cpp.
References assert(), llvm::Function::getAttributes(), llvm::AttributeList::hasFnAttr(), llvm::Function::hasOptNone(), and TLSLoadHoist.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/TLSVariableHoist.h
lib/Transforms/Scalar/TLSVariableHoist.cpp