LLVM: llvm::PBQP::RegAlloc::RegAllocSolverImpl Class Reference
llvm::PBQP::RegAlloc::RegAllocSolverImpl Class Reference
#include "llvm/CodeGen/RegAllocPBQP.h"
Classes
struct EdgeMetadata
Public Types
using RawVector = PBQP::Vector
using RawMatrix = PBQP::Matrix
using Vector = PBQP::Vector
using Matrix = RAMatrix
using CostAllocator = PBQP::PoolCostAllocator<Vector, Matrix>
using NodeId = GraphBase::NodeId
using EdgeId = GraphBase::EdgeId
using NodeMetadata = RegAlloc::NodeMetadata
using GraphMetadata = RegAlloc::GraphMetadata
using Graph = PBQP::Graph<RegAllocSolverImpl>
Public Member Functions
RegAllocSolverImpl (Graph &G)
Solution solve ()
void handleAddNode (NodeId NId)
void handleRemoveNode (NodeId NId)
void handleSetNodeCosts (NodeId NId, const Vector &newCosts)
void handleAddEdge (EdgeId EId)
void handleDisconnectEdge (EdgeId EId, NodeId NId)
void handleReconnectEdge (EdgeId EId, NodeId NId)
void handleUpdateCosts (EdgeId EId, const Matrix &NewCosts)
Detailed Description
Definition at line 270 of file RegAllocPBQP.h.
Member Typedef Documentation
CostAllocator
using llvm::PBQP::RegAlloc::RegAllocSolverImpl::CostAllocator = PBQP::PoolCostAllocator<Vector, Matrix>
Definition at line 279 of file RegAllocPBQP.h.
EdgeId
using llvm::PBQP::RegAlloc::RegAllocSolverImpl::EdgeId = GraphBase::EdgeId
Definition at line 282 of file RegAllocPBQP.h.
Graph
using llvm::PBQP::RegAlloc::RegAllocSolverImpl::Graph = PBQP::Graph<RegAllocSolverImpl>
Definition at line 288 of file RegAllocPBQP.h.
GraphMetadata
using llvm::PBQP::RegAlloc::RegAllocSolverImpl::GraphMetadata = RegAlloc::GraphMetadata
Definition at line 286 of file RegAllocPBQP.h.
Matrix
using llvm::PBQP::RegAlloc::RegAllocSolverImpl::Matrix = RAMatrix
Definition at line 278 of file RegAllocPBQP.h.
NodeId
using llvm::PBQP::RegAlloc::RegAllocSolverImpl::NodeId = GraphBase::NodeId
Definition at line 281 of file RegAllocPBQP.h.
NodeMetadata
using llvm::PBQP::RegAlloc::RegAllocSolverImpl::NodeMetadata = RegAlloc::NodeMetadata
Definition at line 284 of file RegAllocPBQP.h.
RawMatrix
using llvm::PBQP::RegAlloc::RegAllocSolverImpl::RawMatrix = PBQP::Matrix
Definition at line 276 of file RegAllocPBQP.h.
RawVector
using llvm::PBQP::RegAlloc::RegAllocSolverImpl::RawVector = PBQP::Vector
Definition at line 275 of file RegAllocPBQP.h.
Vector
using llvm::PBQP::RegAlloc::RegAllocSolverImpl::Vector = PBQP::Vector
Definition at line 277 of file RegAllocPBQP.h.
Constructor & Destructor Documentation
RegAllocSolverImpl()
llvm::PBQP::RegAlloc::RegAllocSolverImpl::RegAllocSolverImpl (Graph & G) inline
Definition at line 290 of file RegAllocPBQP.h.
References G.
Member Function Documentation
handleAddEdge()
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleAddEdge (EdgeId EId) inline
Definition at line 310 of file RegAllocPBQP.h.
References llvm::PBQP::Graph< SolverT >::getEdgeNode1Id(), llvm::PBQP::Graph< SolverT >::getEdgeNode2Id(), and handleReconnectEdge().
handleAddNode()
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleAddNode (NodeId NId) inline
Definition at line 301 of file RegAllocPBQP.h.
References assert(), llvm::PBQP::Vector::getLength(), llvm::PBQP::Graph< SolverT >::getNodeCosts(), llvm::PBQP::Graph< SolverT >::getNodeMetadata(), and llvm::PBQP::RegAlloc::NodeMetadata::setup().
handleDisconnectEdge()
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleDisconnectEdge (EdgeId EId, NodeId NId) inline
Definition at line 315 of file RegAllocPBQP.h.
References llvm::PBQP::Graph< SolverT >::getEdgeCosts(), llvm::PBQP::Graph< SolverT >::getEdgeNode2Id(), and llvm::PBQP::Graph< SolverT >::getNodeMetadata().
handleReconnectEdge()
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleReconnectEdge (EdgeId EId, NodeId NId) inline
Definition at line 322 of file RegAllocPBQP.h.
References llvm::PBQP::Graph< SolverT >::getEdgeCosts(), llvm::PBQP::Graph< SolverT >::getEdgeNode2Id(), and llvm::PBQP::Graph< SolverT >::getNodeMetadata().
Referenced by handleAddEdge().
handleRemoveNode()
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleRemoveNode (NodeId NId) inline
Definition at line 307 of file RegAllocPBQP.h.
handleSetNodeCosts()
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleSetNodeCosts (NodeId NId, const Vector & newCosts) inline
Definition at line 308 of file RegAllocPBQP.h.
handleUpdateCosts()
void llvm::PBQP::RegAlloc::RegAllocSolverImpl::handleUpdateCosts (EdgeId EId, const Matrix & NewCosts) inline
Definition at line 328 of file RegAllocPBQP.h.
References llvm::PBQP::Graph< SolverT >::getEdgeCosts(), llvm::PBQP::Graph< SolverT >::getEdgeNode1Id(), llvm::PBQP::Graph< SolverT >::getEdgeNode2Id(), and llvm::PBQP::Graph< SolverT >::getNodeMetadata().
solve()
Solution llvm::PBQP::RegAlloc::RegAllocSolverImpl::solve () inline
Definition at line 292 of file RegAllocPBQP.h.
References llvm::PBQP::backpropagate(), llvm::PBQP::Graph< SolverT >::setSolver(), and llvm::PBQP::Graph< SolverT >::unsetSolver().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/RegAllocPBQP.h