LLVM: llvm::OffloadEntriesInfoManager::OffloadEntryInfo Class Reference
llvm::OffloadEntriesInfoManager::OffloadEntryInfo Class Reference
Base class of the entries info.
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
Public Types
enum OffloadingEntryInfoKinds : unsigned { OffloadingEntryInfoTargetRegion = 0 , OffloadingEntryInfoDeviceGlobalVar = 1 , OffloadingEntryInfoInvalid = ~0u }
Kind of a given entry.
Public Member Functions
bool isValid () const
unsigned getOrder () const
OffloadingEntryInfoKinds getKind () const
uint32_t getFlags () const
void setFlags (uint32_t NewFlags)
Constant * getAddress () const
void setAddress (Constant *V)
Static Public Member Functions
static bool classof (const OffloadEntryInfo *Info)
Protected Member Functions
OffloadEntryInfo ()=delete
OffloadEntryInfo (OffloadingEntryInfoKinds Kind)
OffloadEntryInfo (OffloadingEntryInfoKinds Kind, unsigned Order, uint32_t Flags)
~OffloadEntryInfo ()=default
Detailed Description
Base class of the entries info.
Definition at line 1939 of file OMPIRBuilder.h.
Member Enumeration Documentation
OffloadingEntryInfoKinds
enum llvm::OffloadEntriesInfoManager::OffloadEntryInfo::OffloadingEntryInfoKinds : unsigned
Kind of a given entry.
Enumerator
OffloadingEntryInfoTargetRegion
Entry is a target region.
OffloadingEntryInfoDeviceGlobalVar
Entry is a declare target variable.
OffloadingEntryInfoInvalid
Invalid entry info.
Definition at line 1942 of file OMPIRBuilder.h.
Constructor & Destructor Documentation
OffloadEntryInfo() [1/3]
llvm::OffloadEntriesInfoManager::OffloadEntryInfo::OffloadEntryInfo () protected delete
OffloadEntryInfo() [2/3]
llvm::OffloadEntriesInfoManager::OffloadEntryInfo::OffloadEntryInfo (OffloadingEntryInfoKinds Kind) inline explicit protected
Definition at line 1953 of file OMPIRBuilder.h.
OffloadEntryInfo() [3/3]
llvm::OffloadEntriesInfoManager::OffloadEntryInfo::OffloadEntryInfo (OffloadingEntryInfoKinds Kind, unsigned Order, uint32_t Flags) inline explicit protected
Definition at line 1954 of file OMPIRBuilder.h.
~OffloadEntryInfo()
llvm::OffloadEntriesInfoManager::OffloadEntryInfo::~OffloadEntryInfo () protected default
Member Function Documentation
classof()
static bool llvm::OffloadEntriesInfoManager::OffloadEntryInfo::classof (const OffloadEntryInfo * Info) inline static
Definition at line 1970 of file OMPIRBuilder.h.
getAddress()
Constant * llvm::OffloadEntriesInfoManager::OffloadEntryInfo::getAddress () const inline
Definition at line 1965 of file OMPIRBuilder.h.
getFlags()
uint32_t llvm::OffloadEntriesInfoManager::OffloadEntryInfo::getFlags () const inline
Definition at line 1963 of file OMPIRBuilder.h.
getKind()
OffloadingEntryInfoKinds llvm::OffloadEntriesInfoManager::OffloadEntryInfo::getKind () const inline
Definition at line 1962 of file OMPIRBuilder.h.
getOrder()
unsigned llvm::OffloadEntriesInfoManager::OffloadEntryInfo::getOrder () const inline
Definition at line 1961 of file OMPIRBuilder.h.
isValid()
bool llvm::OffloadEntriesInfoManager::OffloadEntryInfo::isValid () const inline
Definition at line 1960 of file OMPIRBuilder.h.
setAddress()
void llvm::OffloadEntriesInfoManager::OffloadEntryInfo::setAddress (Constant * V) inline
Definition at line 1966 of file OMPIRBuilder.h.
References assert(), and llvm::WeakTrackingVH::pointsToAliveValue().
Referenced by llvm::OffloadEntriesInfoManager::OffloadEntryInfoDeviceGlobalVar::OffloadEntryInfoDeviceGlobalVar(), and llvm::OffloadEntriesInfoManager::OffloadEntryInfoTargetRegion::OffloadEntryInfoTargetRegion().
setFlags()
void llvm::OffloadEntriesInfoManager::OffloadEntryInfo::setFlags (uint32_t NewFlags) inline
Definition at line 1964 of file OMPIRBuilder.h.
The documentation for this class was generated from the following file:
include/llvm/Frontend/OpenMP/OMPIRBuilder.h