LLVM: llvm::CastInst Class Reference
llvm::CastInst Class Reference
This is the base class for all instructions that perform data casts.
#include "llvm/IR/InstrTypes.h"
Public Member Functions
bool isIntegerCast () const
There are several places where we need to know if a cast instruction only deals with integer source and destination types.
bool isLosslessCast () const
A lossless cast is one that does not alter the basic value.
bool isNoopCast (const DataLayout &DL) const
Determine if this cast is a no-op cast.
Instruction::CastOps getOpcode () const
Return the opcode of this CastInst.
Type * getSrcTy () const
Return the source type, as a convenience.
Type * getDestTy () const
Return the destination type, as a convenience.
Public Member Functions inherited from llvm::UnaryInstruction
void * operator new (size_t S)
void operator delete (void *Ptr)
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
Public Member Functions inherited from llvm::Instruction
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
Instruction * user_back ()
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
const Instruction * user_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
const Module * getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Module * getModule ()
const Function * getFunction () const
Return the function this instruction belongs to.
Function * getFunction ()
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
SymbolTableList< Instruction >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
void insertBefore (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
void insertAfter (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
SymbolTableList< Instruction >::iterator insertInto (BasicBlock *ParentBB, SymbolTableList< Instruction >::iterator It)
Inserts an unlinked instruction into ParentBB at position It and returns the iterator of the inserted instruction.
void moveBefore (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
void moveBefore (BasicBlock &BB, SymbolTableList< Instruction >::iterator I)
Unlink this instruction and insert into BB before I.
void moveAfter (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
bool comesBefore (const Instruction *Other) const
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
Instruction * getInsertionPointAfterDef ()
Get the first insertion point at which the result of this instruction is defined.
unsigned getOpcode () const
Returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isExceptionalTerminator () const
bool isOnlyUserOfAnyOperand ()
It checks if this instruction is the only user of at least one of its operands.
bool isLogicalShift () const
Return true if this is a logical shift left or a logical shift right.
bool isArithmeticShift () const
Return true if this is an arithmetic shift right.
bool isBitwiseLogicOp () const
Return true if this is and/or/xor.
bool hasMetadata () const
Return true if this instruction has any metadata attached to it.
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
Return true if this instruction has the given type of metadata attached.
MDNode * getMetadata (unsigned KindID) const
Get the metadata of given kind attached to this Instruction.
MDNode * getMetadata (StringRef Kind) const
Get the metadata of given kind attached to this Instruction.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Get all metadata attached to this Instruction.
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
This does the same thing as getAllMetadata, except that it filters out the debug location.
void setMetadata (unsigned KindID, MDNode *Node)
Set the metadata of the specified kind to the specified node.
void setMetadata (StringRef Kind, MDNode *Node)
void copyMetadata (const Instruction &SrcInst, ArrayRef< unsigned > WL=ArrayRef< unsigned >())
Copy metadata from SrcInst to this instruction.
void swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
void addAnnotationMetadata (StringRef Annotation)
Adds an !annotation metadata node with Annotation to this instruction.
AAMDNodes getAAMetadata () const
Returns the AA metadata for this instruction.
void setAAMetadata (const AAMDNodes &N)
Sets the AA metadata on this instruction from the AAMDNodes structure.
bool extractProfTotalWeight (uint64_t &TotalVal) const
Retrieve total raw weight values of a branch.
void setDebugLoc (DebugLoc Loc)
Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
Return the debug location for this node as a DebugLoc.
void setHasNoUnsignedWrap (bool b=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedWrap (bool b=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
void setIsExact (bool b=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
bool hasNoUnsignedWrap () const LLVM_READONLY
Determine whether the no unsigned wrap flag is set.
bool hasNoSignedWrap () const LLVM_READONLY
Determine whether the no signed wrap flag is set.
bool hasPoisonGeneratingFlags () const LLVM_READONLY
Return true if this operator has flags which may cause this instruction to evaluate to poison despite having non-poison inputs.
void dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
bool hasPoisonGeneratingMetadata () const LLVM_READONLY
Return true if this instruction has poison-generating metadata.
void dropPoisonGeneratingMetadata ()
Drops metadata that may generate poison.
bool hasPoisonGeneratingFlagsOrMetadata () const
Return true if this instruction has poison-generating flags or metadata.
void dropPoisonGeneratingFlagsAndMetadata ()
Drops flags and metadata that may generate poison.
void dropUndefImplyingAttrsAndUnknownMetadata (ArrayRef< unsigned > KnownIDs={})
This function drops non-debug unknown metadata (through dropUnknownNonDebugMetadata).
bool isExact () const LLVM_READONLY
Determine whether the exact flag is set.
void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
void setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
bool isFast () const LLVM_READONLY
Determine whether all fast-math-flags are set.
bool hasAllowReassoc () const LLVM_READONLY
Determine whether the allow-reassociation flag is set.
bool hasNoNaNs () const LLVM_READONLY
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const LLVM_READONLY
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const LLVM_READONLY
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const LLVM_READONLY
Determine whether the allow-reciprocal flag is set.
bool hasAllowContract () const LLVM_READONLY
Determine whether the allow-contract flag is set.
bool hasApproxFunc () const LLVM_READONLY
Determine whether the approximate-math-functions flag is set.
FastMathFlags getFastMathFlags () const LLVM_READONLY
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
void copyIRFlags (const Value *V, bool IncludeWrapFlags=true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
void andIRFlags (const Value *V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
void applyMergedLocation (const DILocation *LocA, const DILocation *LocB)
Merge 2 debug locations and apply it to the Instruction.
void updateLocationAfterHoist ()
Updates the debug location given that the instruction has been hoisted from a block to a predecessor of that block.
void dropLocation ()
Drop the instruction's debug location.
void mergeDIAssignID (ArrayRef< const Instruction * > SourceInstructions)
Merge the DIAssignID metadata from this instruction and those attached to instructions in SourceInstructions.
bool isAssociative () const LLVM_READONLY
Return true if the instruction is associative:
bool isCommutative () const LLVM_READONLY
Return true if the instruction is commutative:
bool isIdempotent () const
Return true if the instruction is idempotent:
bool isNilpotent () const
Return true if the instruction is nilpotent:
bool mayWriteToMemory () const LLVM_READONLY
Return true if this instruction may modify memory.
bool mayReadFromMemory () const LLVM_READONLY
Return true if this instruction may read memory.
bool mayReadOrWriteMemory () const
Return true if this instruction may read or write memory.
bool isAtomic () const LLVM_READONLY
Return true if this instruction has an AtomicOrdering of unordered or higher.
bool hasAtomicLoad () const LLVM_READONLY
Return true if this atomic instruction loads from memory.
bool hasAtomicStore () const LLVM_READONLY
Return true if this atomic instruction stores to memory.
bool isVolatile () const LLVM_READONLY
Return true if this instruction has a volatile memory access.
bool mayThrow () const LLVM_READONLY
Return true if this instruction may throw an exception.
bool isFenceLike () const
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
bool mayHaveSideEffects () const LLVM_READONLY
Return true if the instruction may have side effects.
bool isSafeToRemove () const LLVM_READONLY
Return true if the instruction can be removed if the result is unused.
bool willReturn () const LLVM_READONLY
Return true if the instruction will return (unwinding is considered as a form of returning control flow here).
bool isEHPad () const
Return true if the instruction is a variety of EH-block.
bool isLifetimeStartOrEnd () const LLVM_READONLY
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
bool isLaunderOrStripInvariantGroup () const LLVM_READONLY
Return true if the instruction is a llvm.launder.invariant.group or llvm.strip.invariant.group.
bool isDebugOrPseudoInst () const LLVM_READONLY
Return true if the instruction is a DbgInfoIntrinsic or PseudoProbeInst.
const Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the next non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false)
const Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the previous non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false)
Instruction * clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
bool isIdenticalTo (const Instruction *I) const LLVM_READONLY
Return true if the specified instruction is exactly identical to the current one.
bool isIdenticalToWhenDefined (const Instruction *I) const LLVM_READONLY
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const LLVM_READONLY
This function determines if the specified instruction executes the same operation as the current one.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const LLVM_READONLY
Return true if there are any uses of this instruction in blocks other than the specified block.
unsigned getNumSuccessors () const LLVM_READONLY
Return the number of successors that this instruction has.
BasicBlock * getSuccessor (unsigned Idx) const LLVM_READONLY
Return the specified successor. This instruction must be a terminator.
void setSuccessor (unsigned Idx, BasicBlock *BB)
Update the specified successor to point at the provided block.
void replaceSuccessorWith (BasicBlock *OldBB, BasicBlock *NewBB)
Replace specified successor OldBB to point at the provided block.
void dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs)
Drop all unknown metadata except for debug locations.
void dropUnknownNonDebugMetadata ()
void dropUnknownNonDebugMetadata (unsigned ID1)
void dropUnknownNonDebugMetadata (unsigned ID1, unsigned ID2)
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
Instruction * getPrevNode ()
const Instruction * getPrevNode () const
Get the previous node, or nullptr for the list head.
Instruction * getNextNode ()
Get the next node, or nullptr for the list tail.
const Instruction * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static CastInst * Create (Instruction::CastOps, Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Provides a way to construct any of the CastInst subclasses using an opcode instead of the subclass's constructor.
static CastInst * Create (Instruction::CastOps, Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Provides a way to construct any of the CastInst subclasses using an opcode instead of the subclass's constructor.
static CastInst * CreateZExtOrBitCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a ZExt or BitCast cast instruction.
static CastInst * CreateZExtOrBitCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a ZExt or BitCast cast instruction.
static CastInst * CreateSExtOrBitCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a SExt or BitCast cast instruction.
static CastInst * CreateSExtOrBitCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a SExt or BitCast cast instruction.
static CastInst * CreatePointerCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a BitCast AddrSpaceCast, or a PtrToInt cast instruction.
static CastInst * CreatePointerCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a BitCast, AddrSpaceCast or a PtrToInt cast instruction.
static CastInst * CreatePointerBitCastOrAddrSpaceCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a BitCast or an AddrSpaceCast cast instruction.
static CastInst * CreatePointerBitCastOrAddrSpaceCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a BitCast or an AddrSpaceCast cast instruction.
static CastInst * CreateBitOrPointerCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a BitCast, a PtrToInt, or an IntToPTr cast instruction.
static CastInst * CreateIntegerCast (Value *S, Type *Ty, bool isSigned, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a ZExt, BitCast, or Trunc for int -> int casts.
static CastInst * CreateIntegerCast (Value *S, Type *Ty, bool isSigned, const Twine &Name, BasicBlock *InsertAtEnd)
Create a ZExt, BitCast, or Trunc for int -> int casts.
static CastInst * CreateFPCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create an FPExt, BitCast, or FPTrunc for fp -> fp casts.
static CastInst * CreateFPCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create an FPExt, BitCast, or FPTrunc for fp -> fp casts.
static CastInst * CreateTruncOrBitCast (Value *S, Type *Ty, const Twine &Name="", Instruction *InsertBefore=nullptr)
Create a Trunc or BitCast cast instruction.
static CastInst * CreateTruncOrBitCast (Value *S, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
Create a Trunc or BitCast cast instruction.
static bool isBitCastable (Type *SrcTy, Type *DestTy)
Check whether a bitcast between these types is valid.
static bool isBitOrNoopPointerCastable (Type *SrcTy, Type *DestTy, const DataLayout &DL)
Check whether a bitcast, inttoptr, or ptrtoint cast between these types is valid and a no-op.
static Instruction::CastOps getCastOpcode (const Value *Val, bool SrcIsSigned, Type *Ty, bool DstIsSigned)
Returns the opcode necessary to cast Val into Ty using usual casting rules.
static bool isNoopCast (Instruction::CastOps Opcode, Type *SrcTy, Type *DstTy, const DataLayout &DL)
A no-op cast is one that can be effected without changing any bits.
static unsigned isEliminableCastPair (Instruction::CastOps firstOpcode, Instruction::CastOps secondOpcode, Type *SrcTy, Type *MidTy, Type *DstTy, Type *SrcIntPtrTy, Type *MidIntPtrTy, Type *DstIntPtrTy)
Determine how a pair of casts can be eliminated, if they can be at all.
static bool castIsValid (Instruction::CastOps op, Type *SrcTy, Type *DstTy)
This method can be used to determine if a cast from SrcTy to DstTy using Opcode op is valid or not.
static bool castIsValid (Instruction::CastOps op, Value *S, Type *DstTy)
static bool classof (const Instruction *I)
Methods for support type inquiry through isa, cast, and dyn_cast:
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::UnaryInstruction
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isUnaryOp (unsigned Opcode)
static bool isBinaryOp (unsigned Opcode)
static bool isIntDivRem (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isBitwiseLogicOp (unsigned Opcode)
Determine if the Opcode is and/or/xor.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isFuncletPad (unsigned OpCode)
Determine if the OpCode is one of the FuncletPadInst instructions.
static bool isExceptionalTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator related to exception handling.
static bool isAssociative (unsigned Opcode)
static bool isCommutative (unsigned Opcode)
static bool isIdempotent (unsigned Opcode)
static bool isNilpotent (unsigned Opcode)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Member Functions
CastInst (Type *Ty, unsigned iType, Value *S, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
Constructor with insert-before-instruction semantics for subclasses.
CastInst (Type *Ty, unsigned iType, Value *S, const Twine &NameStr, BasicBlock *InsertAtEnd)
Constructor with insert-at-end-of-block semantics for subclasses.
Protected Member Functions inherited from llvm::UnaryInstruction
UnaryInstruction (Type *Ty, unsigned iType, Value *V, Instruction *IB=nullptr)
UnaryInstruction (Type *Ty, unsigned iType, Value *V, BasicBlock *IAE)
Protected Member Functions inherited from llvm::Instruction
~Instruction ()
template<typename BitfieldElement >
BitfieldElement::Type getSubclassData () const
template<typename BitfieldElement >
void setSubclassData (typename BitfieldElement::Type Value)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Protected Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Additional Inherited Members
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0 , CompareUsingScalarTypes = 1<<1 }
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
enum TermOps
enum UnaryOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum FuncletPadOps
enum OtherOps
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::Instruction
using OpaqueField = Bitfield::Element<uint16_t, 0, 15>
template<unsigned Offset>
using AlignmentBitfieldElementT
template<unsigned Offset>
using BoolBitfieldElementT = typename Bitfield::Element<bool, Offset, 1>
template<unsigned Offset>
using AtomicOrderingBitfieldElementT
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
This is the base class for all instructions that perform data casts.
It is simply provided so that instruction category testing can be performed with code like:
if (isa<CastInst>(Instr)) { ... } Base class of casting instructions.
Definition at line 428 of file InstrTypes.h.
Constructor & Destructor Documentation
CastInst() [1/2]
llvm::CastInst::CastInst (Type * Ty, unsigned iType, Value * S, const Twine & NameStr = "", Instruction * InsertBefore = nullptr) inline protected
Constructor with insert-before-instruction semantics for subclasses.
Definition at line 431 of file InstrTypes.h.
CastInst() [2/2]
llvm::CastInst::CastInst (Type * Ty, unsigned iType, Value * S, const Twine & NameStr, BasicBlock * InsertAtEnd) inline protected
Constructor with insert-at-end-of-block semantics for subclasses.
Definition at line 437 of file InstrTypes.h.
Member Function Documentation
castIsValid() [1/2]
bool CastInst::castIsValid (Instruction::CastOps op, Type * SrcTy, Type * DstTy) static
This method can be used to determine if a cast from SrcTy to DstTy using Opcode op is valid or not.
Check that the construction parameters for a CastInst are correct.
Returns
true iff the proposed cast is valid. Determine if a cast is valid without creating one.
This could be broken out into the separate constructors but it is useful to have it in one place and to eliminate the redundant code for getting the sizes of the types involved.
Definition at line 3739 of file Instructions.cpp.
References llvm::ElementCount::getFixed(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and op.
Referenced by llvm::AddrSpaceCastInst::AddrSpaceCastInst(), llvm::AddrSpaceCastInst::AddrSpaceCastInst(), llvm::BitCastInst::BitCastInst(), llvm::BitCastInst::BitCastInst(), llvm::ConstantFoldLoadThroughBitcast(), Create(), Create(), llvm::FPExtInst::FPExtInst(), llvm::FPExtInst::FPExtInst(), llvm::FPToSIInst::FPToSIInst(), llvm::FPToSIInst::FPToSIInst(), llvm::FPToUIInst::FPToUIInst(), llvm::FPToUIInst::FPToUIInst(), llvm::FPTruncInst::FPTruncInst(), llvm::FPTruncInst::FPTruncInst(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::ConstantExpr::getBitCast(), llvm::ConstantExpr::getCast(), llvm::IntToPtrInst::IntToPtrInst(), llvm::IntToPtrInst::IntToPtrInst(), isNoopCast(), llvm::PtrToIntInst::PtrToIntInst(), llvm::PtrToIntInst::PtrToIntInst(), llvm::SExtInst::SExtInst(), llvm::SExtInst::SExtInst(), llvm::SIToFPInst::SIToFPInst(), llvm::SIToFPInst::SIToFPInst(), llvm::TruncInst::TruncInst(), llvm::TruncInst::TruncInst(), llvm::UIToFPInst::UIToFPInst(), llvm::UIToFPInst::UIToFPInst(), llvm::UpgradeARCRuntime(), llvm::ZExtInst::ZExtInst(), and llvm::ZExtInst::ZExtInst().
castIsValid() [2/2]
static bool llvm::CastInst::castIsValid (Instruction::CastOps op, Value * S, Type * DstTy) inline static
Definition at line 689 of file InstrTypes.h.
References llvm::Value::getType(), and op.
classof() [1/2]
static bool llvm::CastInst::classof (const Instruction * I) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 694 of file InstrTypes.h.
References I.
classof() [2/2]
static bool llvm::CastInst::classof (const Value * V) inline static
Definition at line 697 of file InstrTypes.h.
Create() [1/2]
CastInst * CastInst::Create (Instruction::CastOps op, Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Provides a way to construct any of the CastInst subclasses using an opcode instead of the subclass's constructor.
The opcode must be in the CastOps category. This constructor has insert-at-end-of-block semantics to automatically insert the new CastInst at the end of InsertAtEnd (if its non-null). Construct any of the CastInst subclasses
Parameters
op The opcode for the cast instruction
S The value to be casted (operand 0)
Ty The type to which operand is casted
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 3376 of file Instructions.cpp.
References assert(), castIsValid(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm_unreachable, Name, and op.
Create() [2/2]
CastInst * CastInst::Create (Instruction::CastOps op, Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Provides a way to construct any of the CastInst subclasses using an opcode instead of the subclass's constructor.
The opcode must be in the CastOps category (Instruction::isCast(opcode) returns true). This constructor has insert-before-instruction semantics to automatically insert the new CastInst before InsertBefore (if it is non-null). Construct any of the CastInst subclasses
Parameters
op The opcode of the cast instruction
S The value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 3354 of file Instructions.cpp.
References assert(), castIsValid(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm_unreachable, Name, and op.
Referenced by buildNew(), canonicalizeBitCastExtElt(), llvm::InstCombinerImpl::commonCastTransforms(), CreateBitOrPointerCast(), llvm::NoFolder::CreateCast(), llvm::IRBuilderBase::CreateCast(), CreateFPCast(), CreateFPCast(), CreateIntegerCast(), CreateIntegerCast(), CreatePointerBitCastOrAddrSpaceCast(), CreatePointerBitCastOrAddrSpaceCast(), CreatePointerCast(), CreatePointerCast(), CreateSExtOrBitCast(), CreateSExtOrBitCast(), CreateTruncOrBitCast(), CreateTruncOrBitCast(), CreateZExtOrBitCast(), CreateZExtOrBitCast(), llvm::InstCombinerImpl::EvaluateInDifferentType(), llvm::InstCombinerImpl::foldAddWithConstant(), foldCastShuffle(), foldCtpop(), llvm::InstCombinerImpl::foldPHIArgOpIntoPHI(), llvm::InstCombinerImpl::foldSelectOpOp(), llvm::InstCombinerImpl::FoldShiftByConstant(), llvm::ConstantExpr::getAsInstruction(), llvm::PPCTTIImpl::instCombineIntrinsic(), narrowInsElt(), llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts(), simplifyNvvmIntrinsic(), SinkCast(), sinkLifetimeStartMarkers(), SinkShiftAndTruncate(), llvm::UpgradeBitCastInst(), llvm::InstCombinerImpl::visitBitCast(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitFPExt(), llvm::InstCombinerImpl::visitFPTrunc(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitSExt(), and llvm::InstCombinerImpl::visitShuffleVectorInst().
CreateBitOrPointerCast()
CastInst * CastInst::CreateBitOrPointerCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create a BitCast, a PtrToInt, or an IntToPTr cast instruction.
If the value is a pointer type and the destination an integer type, creates a PtrToInt cast. If the value is an integer type and the destination a pointer type, creates an IntToPtr cast. Otherwise, creates a bitcast.
Parameters
S The pointer value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 3509 of file Instructions.cpp.
References Create(), llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), and Name.
Referenced by createRetBitCast(), createWrapper(), foldBitCastBitwiseLogic(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), llvm::promoteCall(), and llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad().
CreateFPCast() [1/2]
CastInst * CastInst::CreateFPCast (Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Create an FPExt, BitCast, or FPTrunc for fp -> fp casts.
Parameters
S The floating point value to be casted
Ty The floating point type to cast to
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 3561 of file Instructions.cpp.
References assert(), llvm::CallingConv::C, Create(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and Name.
CreateFPCast() [2/2]
CastInst * CastInst::CreateFPCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create an FPExt, BitCast, or FPTrunc for fp -> fp casts.
Parameters
S The floating point value to be casted
Ty The floating point type to cast to
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 3548 of file Instructions.cpp.
References assert(), llvm::CallingConv::C, Create(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and Name.
Referenced by llvm::NoFolder::CreateFPCast(), llvm::IRBuilderBase::CreateFPCast(), and llvm::InstCombinerImpl::visitFPTrunc().
CreateIntegerCast() [1/2]
CastInst * CastInst::CreateIntegerCast (Value * S, Type * Ty, bool isSigned, const Twine & Name, BasicBlock * InsertAtEnd) static
Create a ZExt, BitCast, or Trunc for int -> int casts.
Parameters
S The integer value to be casted (operand 0)
Ty The integer type to which operand is casted
isSigned Whether to regard S as signed or not
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 3534 of file Instructions.cpp.
References assert(), llvm::CallingConv::C, Create(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), isSigned(), and Name.
CreateIntegerCast() [2/2]
CastInst * CastInst::CreateIntegerCast (Value * S, Type * Ty, bool isSigned, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create a ZExt, BitCast, or Trunc for int -> int casts.
Parameters
S The pointer value to be casted (operand 0)
Ty The type to which cast should be made
isSigned Whether to regard S as signed or not
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 3520 of file Instructions.cpp.
References assert(), llvm::CallingConv::C, Create(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), isSigned(), and Name.
Referenced by llvm::NoFolder::CreateIntCast(), llvm::IRBuilderBase::CreateIntCast(), createMalloc(), llvm::InstCombinerImpl::EvaluateInDifferentType(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitPtrToInt(), llvm::InstCombinerImpl::visitSExt(), and llvm::InstCombinerImpl::visitTrunc().
CreatePointerBitCastOrAddrSpaceCast() [1/2]
CastInst * CastInst::CreatePointerBitCastOrAddrSpaceCast (Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Create a BitCast or an AddrSpaceCast cast instruction.
Parameters
S The pointer value to be casted (operand 0)
Ty The type to which operand is casted
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 3483 of file Instructions.cpp.
References assert(), Create(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::Type::isPtrOrPtrVectorTy(), and Name.
Referenced by llvm::NoFolder::CreatePointerBitCastOrAddrSpaceCast(), llvm::IRBuilderBase::CreatePointerBitCastOrAddrSpaceCast(), CreatePointerCast(), CreatePointerCast(), rewriteMemOpOfSelect(), and llvm::InstCombinerImpl::visitGetElementPtrInst().
CreatePointerBitCastOrAddrSpaceCast() [2/2]
CastInst * CastInst::CreatePointerBitCastOrAddrSpaceCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create a BitCast or an AddrSpaceCast cast instruction.
Parameters
S The pointer value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 3496 of file Instructions.cpp.
References assert(), Create(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::Type::isPtrOrPtrVectorTy(), and Name.
CreatePointerCast() [1/2]
CastInst * CastInst::CreatePointerCast (Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Create a BitCast AddrSpaceCast, or a PtrToInt cast instruction.
Parameters
S The pointer value to be casted (operand 0)
Ty The type to which operand is casted
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 3446 of file Instructions.cpp.
References assert(), Create(), CreatePointerBitCastOrAddrSpaceCast(), llvm::Value::getType(), llvm::Type::isPtrOrPtrVectorTy(), llvm::Type::isVectorTy(), and Name.
Referenced by llvm::NoFolder::CreatePointerCast(), llvm::IRBuilderBase::CreatePointerCast(), llvm::CodeExtractor::findAllocas(), llvm::InnerLoopVectorizer::getOrCreateTripCount(), insertLifetimeMarkersSurroundingCall(), tryToShorten(), and llvm::InstCombinerImpl::visitPHINode().
CreatePointerCast() [2/2]
CastInst * CastInst::CreatePointerCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create a BitCast, AddrSpaceCast or a PtrToInt cast instruction.
Create a BitCast or a PtrToInt cast instruction.
Parameters
S The pointer value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 3465 of file Instructions.cpp.
References assert(), Create(), CreatePointerBitCastOrAddrSpaceCast(), llvm::Value::getType(), llvm::Type::isPtrOrPtrVectorTy(), llvm::Type::isVectorTy(), and Name.
CreateSExtOrBitCast() [1/2]
CastInst * CastInst::CreateSExtOrBitCast (Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Create a SExt or BitCast cast instruction.
Parameters
S The value to be casted (operand 0)
Ty The type to which operand is casted
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 3422 of file Instructions.cpp.
References Create(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and Name.
CreateSExtOrBitCast() [2/2]
CastInst * CastInst::CreateSExtOrBitCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create a SExt or BitCast cast instruction.
Parameters
S The value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 3414 of file Instructions.cpp.
References Create(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and Name.
Referenced by llvm::NoFolder::CreateSExtOrBitCast(), and llvm::IRBuilderBase::CreateSExtOrBitCast().
CreateTruncOrBitCast() [1/2]
CastInst * CastInst::CreateTruncOrBitCast (Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Create a Trunc or BitCast cast instruction.
Parameters
S The value to be casted (operand 0)
Ty The type to which operand is casted
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 3438 of file Instructions.cpp.
References Create(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and Name.
CreateTruncOrBitCast() [2/2]
CastInst * CastInst::CreateTruncOrBitCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create a Trunc or BitCast cast instruction.
Parameters
S The value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 3430 of file Instructions.cpp.
References Create(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and Name.
Referenced by llvm::NoFolder::CreateTruncOrBitCast(), llvm::IRBuilderBase::CreateTruncOrBitCast(), and llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract().
CreateZExtOrBitCast() [1/2]
CastInst * CastInst::CreateZExtOrBitCast (Value * S, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) static
Create a ZExt or BitCast cast instruction.
Parameters
S The value to be casted (operand 0)
Ty The type to which operand is casted
Name The name for the instruction
InsertAtEnd The block to insert the instruction into
Definition at line 3406 of file Instructions.cpp.
References Create(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and Name.
CreateZExtOrBitCast() [2/2]
CastInst * CastInst::CreateZExtOrBitCast (Value * S, Type * Ty, const Twine & Name = "", Instruction * InsertBefore = nullptr) static
Create a ZExt or BitCast cast instruction.
Parameters
S The value to be casted (operand 0)
Ty The type to which cast should be made
Name Name for the instruction
InsertBefore Place to insert the instruction
Definition at line 3398 of file Instructions.cpp.
References Create(), llvm::Type::getScalarSizeInBits(), llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and Name.
Referenced by llvm::NoFolder::CreateZExtOrBitCast(), llvm::IRBuilderBase::CreateZExtOrBitCast(), llvm::InstCombinerImpl::foldPHIArgZextsIntoPHI(), processSExt(), llvm::InstCombinerImpl::visitUDiv(), and llvm::InstCombinerImpl::visitURem().
getCastOpcode()
Instruction::CastOps CastInst::getCastOpcode (const Value * Val, bool SrcIsSigned, Type * Ty, bool DstIsSigned) static
Returns the opcode necessary to cast Val into Ty using usual casting rules.
Infer the opcode for cast operand and type
Parameters
Val The value to cast
SrcIsSigned Whether to treat the source as signed
Ty The Type to which the value should be casted
DstIsSigned Whether to treate the dest. as signed
Definition at line 3636 of file Instructions.cpp.
References assert(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm_unreachable.
Referenced by LLVMGetCastOpcode().
getDestTy()
Type * llvm::CastInst::getDestTy () const inline
Return the destination type, as a convenience.
Definition at line 682 of file InstrTypes.h.
References getType().
Referenced by constantFoldUser().
getOpcode()
Instruction::CastOps llvm::CastInst::getOpcode () const inline
Return the opcode of this CastInst.
Definition at line 675 of file InstrTypes.h.
References llvm::Instruction::getOpcode().
Referenced by llvm::AddrSpaceCastInst::AddrSpaceCastInst(), llvm::AddrSpaceCastInst::AddrSpaceCastInst(), llvm::BitCastInst::BitCastInst(), llvm::BitCastInst::BitCastInst(), llvm::InstCombinerImpl::commonCastTransforms(), constantFoldUser(), llvm::FPExtInst::FPExtInst(), llvm::FPExtInst::FPExtInst(), llvm::FPToSIInst::FPToSIInst(), llvm::FPToSIInst::FPToSIInst(), llvm::FPToUIInst::FPToUIInst(), llvm::FPToUIInst::FPToUIInst(), llvm::FPTruncInst::FPTruncInst(), llvm::FPTruncInst::FPTruncInst(), llvm::IntToPtrInst::IntToPtrInst(), llvm::IntToPtrInst::IntToPtrInst(), isIntegerCast(), isLosslessCast(), isNoopCast(), llvm::PtrToIntInst::PtrToIntInst(), llvm::PtrToIntInst::PtrToIntInst(), llvm::SExtInst::SExtInst(), llvm::SExtInst::SExtInst(), shrinkInsertElt(), SinkCast(), llvm::SIToFPInst::SIToFPInst(), llvm::SIToFPInst::SIToFPInst(), llvm::TruncInst::TruncInst(), llvm::TruncInst::TruncInst(), llvm::UIToFPInst::UIToFPInst(), llvm::UIToFPInst::UIToFPInst(), visitIVCast(), llvm::ZExtInst::ZExtInst(), and llvm::ZExtInst::ZExtInst().
getSrcTy()
Type * llvm::CastInst::getSrcTy () const inline
Return the source type, as a convenience.
Definition at line 680 of file InstrTypes.h.
Referenced by llvm::InstCombinerImpl::commonCastTransforms(), and foldLogicCastConstant().
isBitCastable()
bool CastInst::isBitCastable (Type * SrcTy, Type * DestTy) static
Check whether a bitcast between these types is valid.
Parameters
SrcTy The Type from which the value should be cast.
DestTy The Type to which the value should be cast.
Definition at line 3574 of file Instructions.cpp.
Referenced by llvm::coro::Shape::buildFrom(), and isBitOrNoopPointerCastable().
isBitOrNoopPointerCastable()
bool CastInst::isBitOrNoopPointerCastable (Type * SrcTy, Type * DestTy, const DataLayout & DL) static
Check whether a bitcast, inttoptr, or ptrtoint cast between these types is valid and a no-op.
This ensures that any pointer<->integer cast has enough bits in the integer and any other cast is a bitcast.
Parameters
SrcTy The Type from which the value should be cast.
DestTy The Type to which the value should be cast.
Definition at line 3614 of file Instructions.cpp.
References DL, and isBitCastable().
Referenced by llvm::InnerLoopVectorizer::createBitOrPointerCast(), createWrapper(), getAvailableLoadStore(), llvm::isLegalToPromote(), and tryPromoteAllocaToVector().
isEliminableCastPair()
unsigned CastInst::isEliminableCastPair (Instruction::CastOps firstOp, Instruction::CastOps secondOp, Type * SrcTy, Type * MidTy, Type * DstTy, Type * SrcIntPtrTy, Type * MidIntPtrTy, Type * DstIntPtrTy) static
Determine how a pair of casts can be eliminated, if they can be at all.
This function determines if a pair of casts can be eliminated and what opcode should be used in the elimination.
This is a helper function for both CastInst and ConstantExpr.
Returns
0 if the CastInst pair can't be eliminated, otherwise returns Instruction::CastOps value for a cast that can replace the pair, casting SrcTy to DstTy. Determine if a cast pair is eliminable
This assumes that there are two instructions like this:
F = firstOpcode SrcTy x to MidTy
S = secondOpcode MidTy F to DstTy The function returns a resultOpcode so these two casts can be replaced with:
Replacement = resultOpcode SrcTy x to DstTy If no such cast is permitted, the function returns 0.
Parameters
firstOp Opcode of first cast
secondOp Opcode of second cast
SrcTy SrcTy of 1st cast
MidTy DstTy of 1st cast & SrcTy of 2nd cast
DstTy DstTy of 2nd cast
SrcIntPtrTy Integer type corresponding to Ptr SrcTy, or null
MidIntPtrTy Integer type corresponding to Ptr MidTy, or null
DstIntPtrTy Integer type corresponding to Ptr DstTy, or null
Definition at line 3129 of file Instructions.cpp.
References assert(), DisableI2pP2iOpt, llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm_unreachable.
Referenced by foldConstantCastPair(), and simplifyCastInst().
isIntegerCast()
bool CastInst::isIntegerCast () const
There are several places where we need to know if a cast instruction only deals with integer source and destination types.
To simplify that logic, this method is provided.
Returns
true iff the cast has only integral typed operand and dest type. Determine if this is an integer-only cast.
Definition at line 3049 of file Instructions.cpp.
References getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm::Type::isIntegerTy().
isLosslessCast()
bool CastInst::isLosslessCast () const
A lossless cast is one that does not alter the basic value.
It implies a no-op cast but is more stringent, preventing things like int->float, long->double, or int->ptr.
Returns
true iff the cast is lossless. Determine if this is a lossless cast.
Definition at line 3062 of file Instructions.cpp.
References getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by isSafeToEliminateVarargsCast().
isNoopCast() [1/2]
bool CastInst::isNoopCast (const DataLayout & DL) const
Determine if this cast is a no-op cast.
Parameters
DL is the DataLayout to determine pointer size.
Definition at line 3117 of file Instructions.cpp.
References DL, getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), and isNoopCast().
isNoopCast() [2/2]
bool CastInst::isNoopCast (Instruction::CastOps Opcode, Type * SrcTy, Type * DestTy, const DataLayout & DL) static
A no-op cast is one that can be effected without changing any bits.
This function determines if the CastInst does not require any bits to be changed in order to effect the cast.
It implies that the source and destination types are the same size. The DataLayout argument is to determine the pointer size when examining casts involving Integer and Pointer types. They are no-op casts if the integer is the same size as the pointer. However, pointer size varies with platform. Note that a precondition of this method is that the cast is legal - i.e. the instruction formed with these operands would verify.
Essentially, it identifies cases where no code gen is necessary for the cast, hence the name no-op cast. For example, the following are all no-op casts:
bitcast i32* x to i8*
bitcast <2 x i32> x to <4 x i16>
ptrtoint i32* x to i32 ; on 32-bit plaforms only
Determine if the described cast is a no-op.
Parameters
Opcode Opcode of cast
SrcTy SrcTy of cast
DestTy DstTy of cast
DL DataLayout to get the Int Ptr type from.
Definition at line 3087 of file Instructions.cpp.
References assert(), castIsValid(), DL, llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm_unreachable.
Referenced by isNoopCast(), and isNoopPtrIntCastPair().
The documentation for this class was generated from the following files:
include/llvm/IR/InstrTypes.h
lib/IR/Instructions.cpp