LLVM: llvm::mca::Context Class Reference
llvm::mca::Context Class Reference
#include "llvm/MCA/Context.h"
Public Member Functions
Context (const MCRegisterInfo &R, const MCSubtargetInfo &S)
Context (const Context &C)=delete
Context & operator= (const Context &C)=delete
const MCRegisterInfo & getMCRegisterInfo () const
const MCSubtargetInfo & getMCSubtargetInfo () const
void addHardwareUnit (std::unique_ptr< HardwareUnit > H)
std::unique_ptr< Pipeline > createDefaultPipeline (const PipelineOptions &Opts, SourceMgr &SrcMgr, CustomBehaviour &CB)
Construct a basic pipeline for simulating an out-of-order pipeline.
std::unique_ptr< Pipeline > createInOrderPipeline (const PipelineOptions &Opts, SourceMgr &SrcMgr, CustomBehaviour &CB)
Construct a basic pipeline for simulating an in-order pipeline.
Detailed Description
Definition at line 51 of file Context.h.
Constructor & Destructor Documentation
Context() [1/2]
llvm::mca::Context::Context (const MCRegisterInfo & R, const MCSubtargetInfo & S) inline
Definition at line 57 of file Context.h.
References MRI.
Context() [2/2]
llvm::mca::Context::Context (const Context & C) delete
Member Function Documentation
addHardwareUnit()
void llvm::mca::Context::addHardwareUnit (std::unique_ptr< HardwareUnit > H) inline
Definition at line 64 of file Context.h.
References H.
Referenced by createDefaultPipeline(), and createInOrderPipeline().
createDefaultPipeline()
std::unique_ptr< Pipeline > llvm::mca::Context::createDefaultPipeline (const PipelineOptions & Opts, SourceMgr & SrcMgr, CustomBehaviour & CB)
Construct a basic pipeline for simulating an out-of-order pipeline.
This pipeline consists of Fetch, Dispatch, Execute, and Retire stages.
Definition at line 32 of file Context.cpp.
References addHardwareUnit(), llvm::mca::PipelineOptions::AssumeNoAlias, createInOrderPipeline(), llvm::mca::PipelineOptions::DecodersThroughput, llvm::mca::PipelineOptions::DispatchWidth, llvm::mca::PipelineOptions::EnableBottleneckAnalysis, Execute(), llvm::MCSubtargetInfo::getSchedModel(), llvm::MCSchedModel::isOutOfOrder(), llvm::mca::PipelineOptions::LoadQueueSize, llvm::mca::PipelineOptions::MicroOpQueueSize, llvm::mca::PipelineOptions::RegisterFileSize, llvm::SrcMgr, and llvm::mca::PipelineOptions::StoreQueueSize.
createInOrderPipeline()
std::unique_ptr< Pipeline > llvm::mca::Context::createInOrderPipeline (const PipelineOptions & Opts, SourceMgr & SrcMgr, CustomBehaviour & CB)
Construct a basic pipeline for simulating an in-order pipeline.
This pipeline consists of Fetch, InOrderIssue, and Retire stages.
Definition at line 73 of file Context.cpp.
References addHardwareUnit(), llvm::mca::PipelineOptions::AssumeNoAlias, llvm::MCSubtargetInfo::getSchedModel(), llvm::mca::PipelineOptions::LoadQueueSize, llvm::mca::PipelineOptions::RegisterFileSize, llvm::SrcMgr, and llvm::mca::PipelineOptions::StoreQueueSize.
Referenced by createDefaultPipeline().
getMCRegisterInfo()
const MCRegisterInfo & llvm::mca::Context::getMCRegisterInfo () const inline
Definition at line 61 of file Context.h.
References MRI.
getMCSubtargetInfo()
const MCSubtargetInfo & llvm::mca::Context::getMCSubtargetInfo () const inline
Definition at line 62 of file Context.h.
operator=()
Context & llvm::mca::Context::operator= (const Context & C) delete
The documentation for this class was generated from the following files:
include/llvm/MCA/Context.h
lib/MCA/Context.cpp