LLVM: llvm::ilist_node_impl< OptionsT > Class Template Reference
llvm::ilist_node_impl< OptionsT > Class Template Reference
Implementation for an ilist node.
#include "llvm/ADT/ilist_node.h"
Public Member Functions
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Protected Types
using self_iterator = ilist_iterator<OptionsT, false, false>
using const_self_iterator = ilist_iterator<OptionsT, false, true>
using reverse_self_iterator = ilist_iterator<OptionsT, true, false>
using const_reverse_self_iterator = ilist_iterator<OptionsT, true, true>
Protected Member Functions
ilist_node_impl ()=default
Friends
struct ilist_detail::NodeAccess
class ilist_sentinel< OptionsT >
class ilist_iterator< OptionsT, false, false >
class ilist_iterator< OptionsT, false, true >
class ilist_iterator< OptionsT, true, false >
class ilist_iterator< OptionsT, true, true >
Detailed Description
template<class OptionsT>
class llvm::ilist_node_impl< OptionsT >
Implementation for an ilist node.
Templated on an appropriate ilist_detail::node_options, usually computed by ilist_detail::compute_node_options.
This is a wrapper around ilist_node_base whose main purpose is to provide type safety: you can't insert nodes of ilist_node_impl into the wrong simple_ilist or iplist.
Definition at line 40 of file ilist_node.h.
Member Typedef Documentation
const_reverse_self_iterator
template<class OptionsT > using llvm::ilist_node_impl< OptionsT >::const_reverse_self_iterator = ilist_iterator<OptionsT, true, true> protected
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-16/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 57 of file ilist_node.h.
const_self_iterator
template<class OptionsT > using llvm::ilist_node_impl< OptionsT >::const_self_iterator = ilist_iterator<OptionsT, false, true> protected
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-16/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 55 of file ilist_node.h.
reverse_self_iterator
template<class OptionsT > using llvm::ilist_node_impl< OptionsT >::reverse_self_iterator = ilist_iterator<OptionsT, true, false> protected
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-16/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 56 of file ilist_node.h.
self_iterator
template<class OptionsT > using llvm::ilist_node_impl< OptionsT >::self_iterator = ilist_iterator<OptionsT, false, false> protected
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-16/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 54 of file ilist_node.h.
Constructor & Destructor Documentation
ilist_node_impl()
template<class OptionsT > llvm::ilist_node_impl< OptionsT >::ilist_node_impl () protected default
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-16/llvm/include/llvm/ADT/ilist_node.h.
Referenced by llvm::CodeGenPassBuilder< DerivedT >::addBlockPlacement(), llvm::CodeGenPassBuilder< DerivedT >::addCodeGenPrepare(), llvm::CodeGenPassBuilder< DerivedT >::addCoreISelPasses(), llvm::CodeGenPassBuilder< DerivedT >::addFastRegAlloc(), llvm::CodeGenPassBuilder< DerivedT >::addIRPasses(), llvm::CodeGenPassBuilder< DerivedT >::addISelPasses(), llvm::CodeGenPassBuilder< DerivedT >::addISelPrepare(), llvm::CodeGenPassBuilder< DerivedT >::addMachineLateOptimization(), llvm::CodeGenPassBuilder< DerivedT >::addMachinePasses(), llvm::CodeGenPassBuilder< DerivedT >::addMachineSSAOptimization(), llvm::AccelTable< DataT >::addName(), llvm::CodeGenPassBuilder< DerivedT >::addOptimizedRegAlloc(), llvm::CodeGenPassBuilder< DerivedT >::addPassesToHandleExceptions(), llvm::InstrProfCorrelatorImpl< IntPtrT >::addProbe(), llvm::CodeGenPassBuilder< DerivedT >::addRegAllocPass(), llvm::CodeGenPassBuilder< DerivedT >::addRegAssignmentFast(), llvm::CodeGenPassBuilder< DerivedT >::addRegAssignmentOptimized(), llvm::CodeGenPassBuilder< DerivedT >::addTargetRegisterAllocator(), adjustByValArgAlignment(), llvm::AliasSet::aliasesUnknownInst(), llvm::LoopInfoBase< BlockT, LoopT >::analyze(), llvm::GenericUniformityAnalysisImpl< ContextT >::analyzeControlDivergence(), llvm::IRComparer< T >::analyzeIR(), llvm::object::ELFFile< ELFT >::android_relas(), llvm::APInt::APInt(), llvm::SampleProfileInference< BT >::apply(), llvm::SampleProfileLoaderBaseImpl< BT >::applyProfi(), llvm::CodeGenPassBuilder< DerivedT >::buildPipeline(), llvm::ForwardDominanceFrontierBase< BlockT >::calculate(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), llvm::APInt::ceilLogBase2(), llvm::MemoryUseOrDef::classof(), llvm::MemoryUse::classof(), llvm::MemoryAccess::classof(), llvm::APInt::clearAllBits(), llvm::APInt::clearBit(), llvm::ShuffleVectorSDNode::commuteMask(), llvm::IRComparer< T >::compare(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::compareDomSet(), llvm::GenericUniformityAnalysisImpl< ContextT >::compute(), llvm::RegionBase< Tr >::contains(), containsConstantInAddMulChain(), llvm::InstrProfCorrelatorImpl< IntPtrT >::correlateProfileData(), costAndCollectOperands(), llvm::APInt::countLeadingZeros(), llvm::APInt::countTrailingZeros(), llvm::AbstractDependenceGraphBuilder< GraphType >::createDefUseEdges(), llvm::AbstractDependenceGraphBuilder< GraphType >::createFineGrainedNodes(), llvm::AbstractDependenceGraphBuilder< GraphType >::createMemoryDependencyEdges(), llvm::ThunkInserter< Derived, InsertedThunksTy >::createThunkFunction(), llvm::dbgs(), llvm::object::ELFFile< ELFT >::decodeBBAddrMap(), DEFINE_SIMPLE_CONVERSION_FUNCTIONS(), llvm::MutableArrayRef< T >::drop_until(), llvm::MutableArrayRef< T >::drop_while(), llvm::DWARFListTableBase< DWARFListType >::dump(), llvm::SDNode::dumpr(), llvm::SDNode::dumpr(), llvm::InstrProfCorrelatorImpl< IntPtrT >::dumpYaml(), llvm::object::ELFFile< ELFT >::dynamicEntries(), llvm::DWARFListTableBase< DWARFListType >::extract(), llvm::RuntimeDyldMachOCRTPBase< Impl >::finalizeLoad(), llvm::SampleProfileLoaderBaseImpl< BT >::findEquivalenceClasses(), llvm::SampleProfileLoaderBaseImpl< BT >::findEquivalencesFor(), llvm::findVCToolChainViaSetupConfig(), llvm::IRComparer< T >::generateFunctionData(), llvm::InstrProfCorrelatorImpl< IntPtrT >::get(), llvm::GlobalAlias::getAliasee(), llvm::GlobalAlias::getAliasee(), llvm::SampleProfileLoaderBaseImpl< BT >::getBlockWeight(), llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::BuildVectorSDNode::getConstantFPSplatNode(), llvm::BuildVectorSDNode::getConstantFPSplatNode(), llvm::SDNode::getConstantOperandAPInt(), llvm::SDNode::getConstantOperandVal(), llvm::BuildVectorSDNode::getConstantRawBits(), llvm::BuildVectorSDNode::getConstantSplatNode(), llvm::BuildVectorSDNode::getConstantSplatNode(), llvm::PredicateBase::getConstraint(), llvm::RegionBase< Tr >::getEnteringBlock(), llvm::LoopBase< BlockT, LoopT >::getExitBlocks(), llvm::GenericCycle< ContextT >::getExitBlocks(), llvm::LoopBase< BlockT, LoopT >::getExitEdges(), llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), llvm::RegionBase< RegionTraits< MachineFunction > >::getExitingBlock(), llvm::RegionBase< Tr >::getExitingBlock(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), llvm::RegionBase< Tr >::getExitingBlocks(), llvm::ARM::getFPUFeatures(), llvm::LifetimeSDNode::getFrameIndex(), llvm::MemoryAccess::getID(), llvm::GlobalVariable::getInitializer(), llvm::GlobalVariable::getInitializer(), llvm::Function::getInstructionCount(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInPreorder(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInReverseSiblingPreorder(), llvm::SDNode::getMachineOpcode(), llvm::RegionBase< Tr >::getNameStr(), llvm::NamedMDNode::getOperand(), llvm::SDNode::getOperationName(), llvm::MemoryUseOrDef::getOptimized(), llvm::Function::getPersonalityFn(), llvm::IRSimilarity::IRInstructionData::getPredicate(), llvm::Function::getPrefixData(), llvm::Function::getPrologueData(), llvm::MemSDNode::getRawSubclassData(), llvm::InstrProfReaderIndex< HashTableImpl >::getRecords(), llvm::InstrProfReaderIndex< HashTableImpl >::getRecords(), llvm::BuildVectorSDNode::getRepeatedSequence(), llvm::GlobalIFunc::getResolver(), llvm::GlobalIFunc::getResolver(), llvm::GlobalIFunc::getResolverFunction(), llvm::Function::getSectionPrefix(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::BuildVectorSDNode::getSplatValue(), llvm::getStructTM(), llvm::Function::getSubprogram(), llvm::IVStrideUse::getUser(), llvm::GlobalVariable::GlobalVariable(), llvm::GlobalVariable::GlobalVariable(), llvm::SmallVectorTemplateBase< T, bool >::grow(), llvm::SmallVectorBase< Size_T >::grow_pod(), llvm::TextChangeReporter< IRUnitT >::handleInitialIR(), llvm::ChangeReporter< IRUnitT >::handleIRAfterPass(), llvm::Function::hasAddressTaken(), llvm::LoopBase< BlockT, LoopT >::hasDedicatedExits(), llvm::SDNode::hasNUsesOfValue(), llvm::SDNode::hasPredecessorHelper(), impliesPoison(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::PopulateLoopsDFS< BlockT, LoopT >::insertIntoLoop(), IsAvailableOnEntry(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::isEdgeFeasible(), llvm::VPGatherScatterSDNode::isIndexScaled(), llvm::MaskedGatherScatterSDNode::isIndexScaled(), llvm::APInt::isMask(), llvm::APInt::isOneBitSet(), llvm::MemoryUseOrDef::isOptimized(), llvm::APInt::isSameValue(), llvm::APInt::isShiftedMask(), LLVMBinaryGetType(), LLVMOrcCreateRTDyldObjectLinkingLayerWithMCJITMemoryManagerLikeCallbacks(), llvm::localCache(), llvm::Function::lookupIntrinsicID(), llvm::SmallVectorBase< Size_T >::mallocForGrow(), llvm::GenericUniformityAnalysisImpl< ContextT >::markDefsDivergent(), llvm::MaskedScatterSDNode::MaskedScatterSDNode(), llvm::MaskedStoreSDNode::MaskedStoreSDNode(), llvm::simple_ilist< T, Options >::merge(), llvm::APInt::operator&=(), llvm::ScaledNumber< DigitsT >::operator*=(), llvm::APInt::operator++(), llvm::AliasSet::iterator::operator++(), llvm::SDNode::use_iterator::operator++(), llvm::operator-(), llvm::APInt::operator--(), llvm::ScaledNumber< DigitsT >::operator/=(), llvm::APSInt::operator<<=(), llvm::APInt::operator=(), llvm::APInt::operator=(), llvm::operator~(), llvm::GenericUniformityAnalysisImpl< ContextT >::print(), llvm::SampleProfileLoaderBaseImpl< BT >::printBlockEquivalence(), llvm::SampleProfileLoaderBaseImpl< BT >::propagateThroughEdges(), llvm::symbolize::CachedBinary::pushEvictor(), llvm::BuildVectorSDNode::recastRawBits(), llvm::SmallVectorBase< Size_T >::replaceAllocation(), llvm::RegionBase< Tr >::replaceEntryRecursive(), llvm::RegionBase< Tr >::replaceExitRecursive(), llvm::OrderedChangedData< T >::report(), llvm::MemoryUseOrDef::resetOptimized(), llvm::ThunkInserter< Derived, InsertedThunksTy >::run(), llvm::ScaledNumber< DigitsT >::scale(), llvm::scc_member_iterator< GraphT, GT >::scc_member_iterator(), llvm::SCEVExprContains(), SCEVMinMaxExprContains(), llvm::SDNode::SDNode(), llvm::GlobalAlias::setAliasee(), llvm::APInt::setAllBits(), llvm::APInt::setBits(), llvm::IRSimilarity::IRInstructionData::setBranchSuccessors(), llvm::IRSimilarity::IRInstructionData::setCalleeName(), llvm::Function::setEntryCount(), llvm::GlobalVariable::setInitializer(), llvm::MemoryUseOrDef::setOptimized(), llvm::Function::setPersonalityFn(), llvm::IRSimilarity::IRInstructionData::setPHIPredecessors(), llvm::Function::setPrefixData(), llvm::Function::setPrologueData(), llvm::GlobalIFunc::setResolver(), llvm::Function::setSectionPrefix(), llvm::StoreSDNode::setTruncatingStore(), llvm::APInt::shl(), llvm::AbstractDependenceGraphBuilder< GraphType >::simplify(), simplifyNvvmIntrinsic(), llvm::MutableArrayRef< T >::slice(), llvm::AbstractDependenceGraphBuilder< GraphType >::sortNodesTopologically(), llvm::Function::splice(), llvm::MutableArrayRef< T >::take_until(), llvm::MutableArrayRef< T >::take_while(), llvm::SmallVectorTemplateBase< T, bool >::takeAllocationForGrow(), llvm::object::ELFFile< ELFT >::toMappedAddr(), llvm::UnrollLoop(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), llvm::BlockFrequencyInfoImpl< BT >::verifyMatch(), llvm::Function::viewCFG(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::VPLoadSDNode::VPLoadSDNode(), llvm::VPStoreSDNode::VPStoreSDNode(), and llvm::VPStridedStoreSDNode::VPStridedStoreSDNode().
Member Function Documentation
getIterator() [1/2]
template<class OptionsT > self_iterator llvm::ilist_node_impl< OptionsT >::getIterator () inline
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-16/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 82 of file ilist_node.h.
Referenced by llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::GCNSubtarget::adjustSchedDependency(), llvm::HexagonInstrInfo::analyzeBranch(), analyzeCompressibleUses(), applyDebugify(), llvm::CombinerHelper::applyExtendThroughPhis(), AMDGPUCombinerHelper::applyFoldableFneg(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), AttemptToFoldSymbolOffsetDifference(), bbHasFallthrough(), BBHasFallthrough(), canFallThroughTo(), llvm::AAResults::canInstructionRangeModRef(), canSplitCallSite(), llvm::MemorySSAUpdater::changeToUnreachable(), llvm::changeToUnreachable(), llvm::cloneAndAdaptNoAliasScopes(), llvm::CloneAndPruneIntoFromInst(), llvm::CloneFunctionInto(), CloneInstructionsIntoPredecessorBlockAndUpdateSSAUses(), llvm::cloneLoopWithPreheader(), llvm::MachineFunction::cloneMachineInstrBundle(), collectCallSiteParameters(), llvm::MIRPrinter::convertCallSiteObjects(), copyMustTailReturn(), llvm::SplitAnalysis::countLiveBlocks(), llvm::PeelingModuloScheduleExpander::CreateLCSSAExitingBlock(), llvm::OpenMPIRBuilder::createParallel(), createRetBitCast(), llvm::OpenMPIRBuilder::createSections(), createTileStore(), detectPopcountIdiom(), detectShiftUntilZeroIdiom(), llvm::ARMBaseInstrInfo::duplicate(), llvm::JumpThreadingPass::duplicateCondBranchOnPHIIntoPred(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::VETargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), emitFROUND(), llvm::BPFTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), emitLoadM0FromVGPRLoop(), EmitLoweredCascadedSelect(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::PPCTargetLowering::emitProbedAlloca(), emitReadCycleWidePseudo(), emitSelectPseudo(), emitSelectPseudo(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitXBegin(), llvm::Function::eraseFromParent(), llvm::GlobalAlias::eraseFromParent(), llvm::GlobalIFunc::eraseFromParent(), llvm::GlobalVariable::eraseFromParent(), llvm::Module::eraseNamedMetadata(), llvm::examineCFlagsUse(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::expandDivision(), llvm::VEInstrInfo::expandExtendStackPseudo(), llvm::SIInstrInfo::expandPostRAPseudo(), llvm::expandRemainder(), llvm::SparcTargetLowering::expandSelectCC(), llvm::OpenMPIRBuilder::finalize(), findDependencies(), findInitTrampolineFromBB(), findLiveSetAtInst(), llvm::CodeExtractor::findOrCreateBlockForHoisting(), llvm::ARMBlockPlacement::fixBackwardsWLS(), fixupPHIOpBanks(), llvm::AMDGPULibCalls::fold(), llvm::FoldReturnIntoUncondBranch(), for(), getAllocaPos(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::MachineLoop::getBottomBlock(), llvm::MemoryAccess::getDefsIterator(), llvm::MemoryAccess::getDefsIterator(), llvm::MemoryDependenceResults::getDependency(), llvm::BasicBlock::getFirstInsertionPt(), llvm::BasicBlock::getFirstNonPHIOrDbgOrAlloca(), llvm::MemoryAccess::getIterator(), llvm::MemoryAccess::getIterator(), llvm::LexicalScopes::getMachineBasicBlocks(), getNextBlock(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), llvm::MachineLoop::getTopBlock(), llvm::GlobalVariable::GlobalVariable(), handleADRP(), HandleInlinedEHPad(), HandleInlinedLandingPad(), llvm::LiveIntervals::handleMoveIntoNewBundle(), llvm::objcarc::BottomUpPtrState::HandlePotentialUse(), llvm::hoistAllInstructionsInto(), INITIALIZE_PASS(), llvm::InlineFunction(), inlineRetainOrClaimRVCalls(), llvm::PPCFrameLowering::inlineStackProbe(), llvm::Instruction::insertAfter(), llvm::VPRecipeBase::insertAfter(), llvm::Instruction::insertBefore(), llvm::VPRecipeBase::insertBefore(), llvm::HexagonInstrInfo::insertBranch(), insertDAGNode(), insertDAGNode(), insertDivByZeroTrap(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::BasicBlock::insertInto(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::SlotIndexes::insertMBBInMaps(), llvm::InstCombiner::InsertNewInstBefore(), llvm::SIInstrInfo::insertSelect(), insertSinCosCall(), insertUniqueBackedgeBlock(), llvm::Instruction::Instruction(), llvm::MachineInstr::isIdenticalTo(), llvm::InstructionSelector::isObviouslySafeToFold(), isSafeAndProfitableToSinkLoad(), llvm::isSafeToLoadUnconditionally(), isSafeToSinkLoad(), llvm::isValidAssumeForContext(), jumpTableFollowsTB(), llvm::AMDGPULegalizerInfo::legalizeIntrinsic(), LLVMInsertExistingBasicBlockAfterInsertBlock(), LLVMPositionBuilder(), LowerCallResults(), LowerFPToInt(), MayContainThrowingOrExitingCall(), MergeCompatibleInvokesImpl(), llvm::BasicBlock::moveAfter(), llvm::Instruction::moveAfter(), llvm::MachineBasicBlock::moveAfter(), moveBBContents(), llvm::BasicBlock::moveBefore(), llvm::Instruction::moveBefore(), llvm::MachineBasicBlock::moveBefore(), MoveVPNOTBeforeFirstUser(), llvm::ShuffleBlockStrategy::mutate(), llvm::InstDeleterIRStrategy::mutate(), llvm::SIInstrInfo::optimizeCompareInstr(), optimizeDivRem(), OptimizeGlobalAddressOfAllocation(), optimizeSQRT(), packCmovGroup(), llvm::peelLoop(), placeSplitBlockCarefully(), programUndefinedIfUndefOrPoison(), llvm::recomputeVPTBlockMask(), reinsertVectorIndexAdd(), llvm::removeAllNonTerminatorAndEHPadInstructions(), llvm::Function::removeFromParent(), llvm::GlobalAlias::removeFromParent(), llvm::GlobalIFunc::removeFromParent(), llvm::GlobalVariable::removeFromParent(), removeGlobalCtors(), llvm::MemoryDependenceResults::removeInstruction(), llvm::MachineFunction::RenumberBlocks(), llvm::SlotIndexes::repairIndexesInRange(), ReplaceCallWith(), replaceCoroEndAsync(), replaceSubOverflowUses(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::ARMBlockPlacement::revertWhileToDoLoop(), llvm::InstCombinerImpl::run(), llvm::CFIFixup::runOnMachineFunction(), llvm::MachineFunction::salvageCopySSAImpl(), llvm::IRBuilderBase::SetInsertPoint(), split(), splitBlock(), llvm::SplitBlockAndInsertIfThenElse(), SplitBlockAndInsertIfThenImpl(), llvm::splitBlockBefore(), SplitBlockImpl(), splitCallSite(), llvm::OutlinableRegion::splitCandidate(), llvm::SplitKnownCriticalEdge(), splitMBB(), TryToShrinkGlobalToBoolean(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), llvm::UpgradeARCRuntime(), llvm::UpgradeIntrinsicCall(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), verifyCFIntrinsic(), and llvm::InstCombinerImpl::visitGEPOfBitcast().
getIterator() [2/2]
template<class OptionsT > const_self_iterator llvm::ilist_node_impl< OptionsT >::getIterator () const inline
Definition at line 83 of file ilist_node.h.
getReverseIterator() [1/2]
template<class OptionsT > reverse_self_iterator llvm::ilist_node_impl< OptionsT >::getReverseIterator () inline
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-16/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 85 of file ilist_node.h.
Referenced by collectCallSiteParameters(), llvm::AsmPrinter::emitCFIInstruction(), findDominatingValue(), llvm::MemoryAccess::getReverseDefsIterator(), llvm::MemoryAccess::getReverseDefsIterator(), llvm::MemoryAccess::getReverseIterator(), llvm::MemoryAccess::getReverseIterator(), INITIALIZE_PASS(), llvm::CombinerHelper::matchTruncStoreMerge(), llvm::PeelingModuloScheduleExpander::peelPrologAndEpilogs(), llvm::MachineFunction::salvageCopySSAImpl(), and splitCallSite().
getReverseIterator() [2/2]
template<class OptionsT > const_reverse_self_iterator llvm::ilist_node_impl< OptionsT >::getReverseIterator () const inline
Definition at line 89 of file ilist_node.h.
isSentinel()
template<class OptionsT > bool llvm::ilist_node_impl< OptionsT >::isSentinel () const inline
Check whether this is the sentinel node.
This requires sentinel tracking to be explicitly enabled. Use the ilist_sentinel_tracking<true> option to get this API.
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-16/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 100 of file ilist_node.h.
Referenced by EliminateDuplicatePHINodesSetBasedImpl().
Friends And Related Symbol Documentation
ilist_detail::NodeAccess
template<class OptionsT > friend struct ilist_detail::NodeAccess friend
Definition at line 46 of file ilist_node.h.
ilist_iterator< OptionsT, false, false >
template<class OptionsT > friend class ilist_iterator< OptionsT, false, false > friend
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-16/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 46 of file ilist_node.h.
ilist_iterator< OptionsT, false, true >
template<class OptionsT > friend class ilist_iterator< OptionsT, false, true > friend
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-16/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 46 of file ilist_node.h.
ilist_iterator< OptionsT, true, false >
template<class OptionsT > friend class ilist_iterator< OptionsT, true, false > friend
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-16/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 46 of file ilist_node.h.
ilist_iterator< OptionsT, true, true >
template<class OptionsT > friend class ilist_iterator< OptionsT, true, true > friend
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-16/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 46 of file ilist_node.h.
ilist_sentinel< OptionsT >
template<class OptionsT > friend class ilist_sentinel< OptionsT > friend
Definition at line 46 of file ilist_node.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/ilist_node.h