LLVM: llvm::ShuffleVectorInst Class Reference
llvm::ShuffleVectorInst Class Reference
This instruction constructs a fixed permutation of two input vectors.
#include "llvm/IR/Instructions.h"
Public Member Functions
ShuffleVectorInst (Value *V1, Value *Mask, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
ShuffleVectorInst (Value *V1, Value *Mask, const Twine &NameStr, BasicBlock *InsertAtEnd)
ShuffleVectorInst (Value *V1, ArrayRef< int > Mask, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
ShuffleVectorInst (Value *V1, ArrayRef< int > Mask, const Twine &NameStr, BasicBlock *InsertAtEnd)
ShuffleVectorInst (Value *V1, Value *V2, Value *Mask, const Twine &NameStr="", Instruction *InsertBefor=nullptr)
ShuffleVectorInst (Value *V1, Value *V2, Value *Mask, const Twine &NameStr, BasicBlock *InsertAtEnd)
ShuffleVectorInst (Value *V1, Value *V2, ArrayRef< int > Mask, const Twine &NameStr="", Instruction *InsertBefor=nullptr)
ShuffleVectorInst (Value *V1, Value *V2, ArrayRef< int > Mask, const Twine &NameStr, BasicBlock *InsertAtEnd)
void * operator new (size_t S)
void operator delete (void *Ptr)
void commute ()
Swap the operands and adjust the mask to preserve the semantics of the instruction.
VectorType * getType () const
Overload to return most specific vector type.
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
int getMaskValue (unsigned Elt) const
Return the shuffle mask value of this instruction for the given element index.
void getShuffleMask (SmallVectorImpl< int > &Result) const
Return the mask for this instruction as a vector of integers.
Constant * getShuffleMaskForBitcode () const
Return the mask for this instruction, for use in bitcode.
void setShuffleMask (ArrayRef< int > Mask)
ArrayRef< int > getShuffleMask () const
bool changesLength () const
Return true if this shuffle returns a vector with a different number of elements than its source vectors.
bool increasesLength () const
Return true if this shuffle returns a vector with a greater number of elements than its source vectors.
bool isSingleSource () const
Return true if this shuffle chooses elements from exactly one source vector without changing the length of that vector.
bool isIdentity () const
Return true if this shuffle chooses elements from exactly one source vector without lane crossings and does not change the number of elements from its input vectors.
bool isIdentityWithPadding () const
Return true if this shuffle lengthens exactly one source vector with undefs in the high elements.
bool isIdentityWithExtract () const
Return true if this shuffle extracts the first N elements of exactly one source vector.
bool isConcat () const
Return true if this shuffle concatenates its 2 source vectors.
bool isSelect () const
Return true if this shuffle chooses elements from its source vectors without lane crossings and all operands have the same number of elements.
bool isReverse () const
Return true if this shuffle swaps the order of elements from exactly one source vector.
bool isZeroEltSplat () const
Return true if all elements of this shuffle are the same value as the first element of exactly one source vector without changing the length of that vector.
bool isTranspose () const
Return true if this shuffle transposes the elements of its inputs without changing the length of the vectors.
bool isSplice (int &Index) const
Return true if this shuffle splices two inputs without changing the length of the vectors.
bool isExtractSubvectorMask (int &Index) const
Return true if this shuffle mask is an extract subvector mask.
bool isInsertSubvectorMask (int &NumSubElts, int &Index) const
Return true if this shuffle mask is an insert subvector mask.
bool isReplicationMask (int &ReplicationFactor, int &VF) const
Return true if this shuffle mask is a replication mask.
bool isOneUseSingleSourceMask (int VF) const
Return true if this shuffle mask is a one-use-single-source("clustered") mask.
Public Member Functions inherited from llvm::Instruction
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
Instruction * user_back ()
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
const Instruction * user_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
const Module * getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Module * getModule ()
const Function * getFunction () const
Return the function this instruction belongs to.
Function * getFunction ()
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
SymbolTableList< Instruction >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
void insertBefore (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
void insertAfter (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
SymbolTableList< Instruction >::iterator insertInto (BasicBlock *ParentBB, SymbolTableList< Instruction >::iterator It)
Inserts an unlinked instruction into ParentBB at position It and returns the iterator of the inserted instruction.
void moveBefore (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
void moveBefore (BasicBlock &BB, SymbolTableList< Instruction >::iterator I)
Unlink this instruction and insert into BB before I.
void moveAfter (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
bool comesBefore (const Instruction *Other) const
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
Instruction * getInsertionPointAfterDef ()
Get the first insertion point at which the result of this instruction is defined.
unsigned getOpcode () const
Returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isExceptionalTerminator () const
bool isOnlyUserOfAnyOperand ()
It checks if this instruction is the only user of at least one of its operands.
bool isLogicalShift () const
Return true if this is a logical shift left or a logical shift right.
bool isArithmeticShift () const
Return true if this is an arithmetic shift right.
bool isBitwiseLogicOp () const
Return true if this is and/or/xor.
bool hasMetadata () const
Return true if this instruction has any metadata attached to it.
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
Return true if this instruction has the given type of metadata attached.
MDNode * getMetadata (unsigned KindID) const
Get the metadata of given kind attached to this Instruction.
MDNode * getMetadata (StringRef Kind) const
Get the metadata of given kind attached to this Instruction.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Get all metadata attached to this Instruction.
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
This does the same thing as getAllMetadata, except that it filters out the debug location.
void setMetadata (unsigned KindID, MDNode *Node)
Set the metadata of the specified kind to the specified node.
void setMetadata (StringRef Kind, MDNode *Node)
void copyMetadata (const Instruction &SrcInst, ArrayRef< unsigned > WL=ArrayRef< unsigned >())
Copy metadata from SrcInst to this instruction.
void swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
void addAnnotationMetadata (StringRef Annotation)
Adds an !annotation metadata node with Annotation to this instruction.
AAMDNodes getAAMetadata () const
Returns the AA metadata for this instruction.
void setAAMetadata (const AAMDNodes &N)
Sets the AA metadata on this instruction from the AAMDNodes structure.
bool extractProfTotalWeight (uint64_t &TotalVal) const
Retrieve total raw weight values of a branch.
void setDebugLoc (DebugLoc Loc)
Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
Return the debug location for this node as a DebugLoc.
void setHasNoUnsignedWrap (bool b=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedWrap (bool b=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
void setIsExact (bool b=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
bool hasNoUnsignedWrap () const LLVM_READONLY
Determine whether the no unsigned wrap flag is set.
bool hasNoSignedWrap () const LLVM_READONLY
Determine whether the no signed wrap flag is set.
bool hasPoisonGeneratingFlags () const LLVM_READONLY
Return true if this operator has flags which may cause this instruction to evaluate to poison despite having non-poison inputs.
void dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
bool hasPoisonGeneratingMetadata () const LLVM_READONLY
Return true if this instruction has poison-generating metadata.
void dropPoisonGeneratingMetadata ()
Drops metadata that may generate poison.
bool hasPoisonGeneratingFlagsOrMetadata () const
Return true if this instruction has poison-generating flags or metadata.
void dropPoisonGeneratingFlagsAndMetadata ()
Drops flags and metadata that may generate poison.
void dropUndefImplyingAttrsAndUnknownMetadata (ArrayRef< unsigned > KnownIDs={})
This function drops non-debug unknown metadata (through dropUnknownNonDebugMetadata).
bool isExact () const LLVM_READONLY
Determine whether the exact flag is set.
void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
void setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
bool isFast () const LLVM_READONLY
Determine whether all fast-math-flags are set.
bool hasAllowReassoc () const LLVM_READONLY
Determine whether the allow-reassociation flag is set.
bool hasNoNaNs () const LLVM_READONLY
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const LLVM_READONLY
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const LLVM_READONLY
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const LLVM_READONLY
Determine whether the allow-reciprocal flag is set.
bool hasAllowContract () const LLVM_READONLY
Determine whether the allow-contract flag is set.
bool hasApproxFunc () const LLVM_READONLY
Determine whether the approximate-math-functions flag is set.
FastMathFlags getFastMathFlags () const LLVM_READONLY
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
void copyIRFlags (const Value *V, bool IncludeWrapFlags=true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
void andIRFlags (const Value *V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
void applyMergedLocation (const DILocation *LocA, const DILocation *LocB)
Merge 2 debug locations and apply it to the Instruction.
void updateLocationAfterHoist ()
Updates the debug location given that the instruction has been hoisted from a block to a predecessor of that block.
void dropLocation ()
Drop the instruction's debug location.
void mergeDIAssignID (ArrayRef< const Instruction * > SourceInstructions)
Merge the DIAssignID metadata from this instruction and those attached to instructions in SourceInstructions.
bool isAssociative () const LLVM_READONLY
Return true if the instruction is associative:
bool isCommutative () const LLVM_READONLY
Return true if the instruction is commutative:
bool isIdempotent () const
Return true if the instruction is idempotent:
bool isNilpotent () const
Return true if the instruction is nilpotent:
bool mayWriteToMemory () const LLVM_READONLY
Return true if this instruction may modify memory.
bool mayReadFromMemory () const LLVM_READONLY
Return true if this instruction may read memory.
bool mayReadOrWriteMemory () const
Return true if this instruction may read or write memory.
bool isAtomic () const LLVM_READONLY
Return true if this instruction has an AtomicOrdering of unordered or higher.
bool hasAtomicLoad () const LLVM_READONLY
Return true if this atomic instruction loads from memory.
bool hasAtomicStore () const LLVM_READONLY
Return true if this atomic instruction stores to memory.
bool isVolatile () const LLVM_READONLY
Return true if this instruction has a volatile memory access.
bool mayThrow () const LLVM_READONLY
Return true if this instruction may throw an exception.
bool isFenceLike () const
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
bool mayHaveSideEffects () const LLVM_READONLY
Return true if the instruction may have side effects.
bool isSafeToRemove () const LLVM_READONLY
Return true if the instruction can be removed if the result is unused.
bool willReturn () const LLVM_READONLY
Return true if the instruction will return (unwinding is considered as a form of returning control flow here).
bool isEHPad () const
Return true if the instruction is a variety of EH-block.
bool isLifetimeStartOrEnd () const LLVM_READONLY
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
bool isLaunderOrStripInvariantGroup () const LLVM_READONLY
Return true if the instruction is a llvm.launder.invariant.group or llvm.strip.invariant.group.
bool isDebugOrPseudoInst () const LLVM_READONLY
Return true if the instruction is a DbgInfoIntrinsic or PseudoProbeInst.
const Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the next non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getNextNonDebugInstruction (bool SkipPseudoOp=false)
const Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false) const
Return a pointer to the previous non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getPrevNonDebugInstruction (bool SkipPseudoOp=false)
Instruction * clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
bool isIdenticalTo (const Instruction *I) const LLVM_READONLY
Return true if the specified instruction is exactly identical to the current one.
bool isIdenticalToWhenDefined (const Instruction *I) const LLVM_READONLY
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const LLVM_READONLY
This function determines if the specified instruction executes the same operation as the current one.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const LLVM_READONLY
Return true if there are any uses of this instruction in blocks other than the specified block.
unsigned getNumSuccessors () const LLVM_READONLY
Return the number of successors that this instruction has.
BasicBlock * getSuccessor (unsigned Idx) const LLVM_READONLY
Return the specified successor. This instruction must be a terminator.
void setSuccessor (unsigned Idx, BasicBlock *BB)
Update the specified successor to point at the provided block.
void replaceSuccessorWith (BasicBlock *OldBB, BasicBlock *NewBB)
Replace specified successor OldBB to point at the provided block.
void dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs)
Drop all unknown metadata except for debug locations.
void dropUnknownNonDebugMetadata ()
void dropUnknownNonDebugMetadata (unsigned ID1)
void dropUnknownNonDebugMetadata (unsigned ID1, unsigned ID2)
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
Instruction * getPrevNode ()
const Instruction * getPrevNode () const
Get the previous node, or nullptr for the list head.
Instruction * getNextNode ()
Get the next node, or nullptr for the list tail.
const Instruction * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool isValidOperands (const Value *V1, const Value *V2, const Value *Mask)
Return true if a shufflevector instruction can be formed with the specified operands.
static bool isValidOperands (const Value *V1, const Value *V2, ArrayRef< int > Mask)
static void getShuffleMask (const Constant *Mask, SmallVectorImpl< int > &Result)
Convert the input shuffle mask operand to a vector of integers.
static Constant * convertShuffleMaskForBitcode (ArrayRef< int > Mask, Type *ResultTy)
static bool isSingleSourceMask (ArrayRef< int > Mask)
Return true if this shuffle mask chooses elements from exactly one source vector.
static bool isSingleSourceMask (const Constant *Mask)
static bool isIdentityMask (ArrayRef< int > Mask)
Return true if this shuffle mask chooses elements from exactly one source vector without lane crossings.
static bool isIdentityMask (const Constant *Mask)
static bool isSelectMask (ArrayRef< int > Mask)
Return true if this shuffle mask chooses elements from its source vectors without lane crossings.
static bool isSelectMask (const Constant *Mask)
static bool isReverseMask (ArrayRef< int > Mask)
Return true if this shuffle mask swaps the order of elements from exactly one source vector.
static bool isReverseMask (const Constant *Mask)
static bool isZeroEltSplatMask (ArrayRef< int > Mask)
Return true if this shuffle mask chooses all elements with the same value as the first element of exactly one source vector.
static bool isZeroEltSplatMask (const Constant *Mask)
static bool isTransposeMask (ArrayRef< int > Mask)
Return true if this shuffle mask is a transpose mask.
static bool isTransposeMask (const Constant *Mask)
static bool isSpliceMask (ArrayRef< int > Mask, int &Index)
Return true if this shuffle mask is a splice mask, concatenating the two inputs together and then extracts an original width vector starting from the splice index.
static bool isSpliceMask (const Constant *Mask, int &Index)
static bool isExtractSubvectorMask (ArrayRef< int > Mask, int NumSrcElts, int &Index)
Return true if this shuffle mask is an extract subvector mask.
static bool isExtractSubvectorMask (const Constant *Mask, int NumSrcElts, int &Index)
static bool isInsertSubvectorMask (ArrayRef< int > Mask, int NumSrcElts, int &NumSubElts, int &Index)
Return true if this shuffle mask is an insert subvector mask.
static bool isInsertSubvectorMask (const Constant *Mask, int NumSrcElts, int &NumSubElts, int &Index)
static bool isReplicationMask (ArrayRef< int > Mask, int &ReplicationFactor, int &VF)
Return true if this shuffle mask replicates each of the VF elements in a vector ReplicationFactor times.
static bool isReplicationMask (const Constant *Mask, int &ReplicationFactor, int &VF)
static bool isOneUseSingleSourceMask (ArrayRef< int > Mask, int VF)
Return true if this shuffle mask represents "clustered" mask of size VF, i.e.
static void commuteShuffleMask (MutableArrayRef< int > Mask, unsigned InVecNumElts)
Change values in a shuffle permute mask assuming the two vector operands of length InVecNumElts have swapped position.
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isUnaryOp (unsigned Opcode)
static bool isBinaryOp (unsigned Opcode)
static bool isIntDivRem (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isBitwiseLogicOp (unsigned Opcode)
Determine if the Opcode is and/or/xor.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isFuncletPad (unsigned OpCode)
Determine if the OpCode is one of the FuncletPadInst instructions.
static bool isExceptionalTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator related to exception handling.
static bool isAssociative (unsigned Opcode)
static bool isCommutative (unsigned Opcode)
static bool isIdempotent (unsigned Opcode)
static bool isNilpotent (unsigned Opcode)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Member Functions
ShuffleVectorInst * cloneImpl () const
Protected Member Functions inherited from llvm::Instruction
~Instruction ()
template<typename BitfieldElement >
BitfieldElement::Type getSubclassData () const
template<typename BitfieldElement >
void setSubclassData (typename BitfieldElement::Type Value)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Protected Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Friends
class Instruction
Additional Inherited Members
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0 , CompareUsingScalarTypes = 1<<1 }
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
enum TermOps
enum UnaryOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum FuncletPadOps
enum OtherOps
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::Instruction
using OpaqueField = Bitfield::Element<uint16_t, 0, 15>
template<unsigned Offset>
using AlignmentBitfieldElementT
template<unsigned Offset>
using BoolBitfieldElementT = typename Bitfield::Element<bool, Offset, 1>
template<unsigned Offset>
using AtomicOrderingBitfieldElementT
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
This instruction constructs a fixed permutation of two input vectors.
For each element of the result vector, the shuffle mask selects an element from one of the input vectors to copy to the result. Non-negative elements in the mask represent an index into the concatenated pair of input vectors. UndefMaskElem (-1) specifies that the result element is undefined.
For scalable vectors, all the elements of the mask must be 0 or -1. This requirement may be relaxed in the future.
Definition at line 2017 of file Instructions.h.
Constructor & Destructor Documentation
ShuffleVectorInst() [1/8]
ShuffleVectorInst::ShuffleVectorInst (Value * V1, Value * Mask, const Twine & NameStr = "", Instruction * InsertBefore = nullptr)
Definition at line 2055 of file Instructions.cpp.
Referenced by cloneImpl().
ShuffleVectorInst() [2/8]
ShuffleVectorInst::ShuffleVectorInst (Value * V1, Value * Mask, const Twine & NameStr, BasicBlock * InsertAtEnd)
Definition at line 2060 of file Instructions.cpp.
ShuffleVectorInst() [3/8]
ShuffleVectorInst::ShuffleVectorInst (Value * V1, ArrayRef< int > Mask, const Twine & NameStr = "", Instruction * InsertBefore = nullptr)
Definition at line 2065 of file Instructions.cpp.
ShuffleVectorInst() [4/8]
ShuffleVectorInst::ShuffleVectorInst (Value * V1, ArrayRef< int > Mask, const Twine & NameStr, BasicBlock * InsertAtEnd)
Definition at line 2071 of file Instructions.cpp.
ShuffleVectorInst() [5/8]
ShuffleVectorInst::ShuffleVectorInst (Value * V1, Value * V2, Value * Mask, const Twine & NameStr = "", Instruction * InsertBefor = nullptr)
Definition at line 2076 of file Instructions.cpp.
References assert(), getShuffleMask(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), isValidOperands(), Name, llvm::Value::setName(), and setShuffleMask().
ShuffleVectorInst() [6/8]
ShuffleVectorInst::ShuffleVectorInst (Value * V1, Value * V2, Value * Mask, const Twine & NameStr, BasicBlock * InsertAtEnd)
Definition at line 2095 of file Instructions.cpp.
References assert(), getShuffleMask(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), isValidOperands(), Name, llvm::Value::setName(), and setShuffleMask().
ShuffleVectorInst() [7/8]
ShuffleVectorInst::ShuffleVectorInst (Value * V1, Value * V2, ArrayRef< int > Mask, const Twine & NameStr = "", Instruction * InsertBefor = nullptr)
Definition at line 2113 of file Instructions.cpp.
References assert(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), isValidOperands(), Name, llvm::Value::setName(), and setShuffleMask().
ShuffleVectorInst() [8/8]
ShuffleVectorInst::ShuffleVectorInst (Value * V1, Value * V2, ArrayRef< int > Mask, const Twine & NameStr, BasicBlock * InsertAtEnd)
Definition at line 2129 of file Instructions.cpp.
References assert(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), isValidOperands(), Name, llvm::Value::setName(), and setShuffleMask().
Member Function Documentation
changesLength()
bool llvm::ShuffleVectorInst::changesLength () const inline
Return true if this shuffle returns a vector with a different number of elements than its source vectors.
Examples: shufflevector <4 x n> A, <4 x n> B, <1,2,3> shufflevector <4 x n> A, <4 x n> B, <1,2,3,4,5>
Definition at line 2102 of file Instructions.h.
References getType().
classof() [1/2]
static bool llvm::ShuffleVectorInst::classof (const Instruction * I) inline static
Definition at line 2434 of file Instructions.h.
References I, and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
classof() [2/2]
static bool llvm::ShuffleVectorInst::classof (const Value * V) inline static
Definition at line 2437 of file Instructions.h.
cloneImpl()
ShuffleVectorInst * ShuffleVectorInst::cloneImpl () const protected
Definition at line 4936 of file Instructions.cpp.
References llvm::User::getOperand(), getShuffleMask(), and ShuffleVectorInst().
commute()
void ShuffleVectorInst::commute ()
Swap the operands and adjust the mask to preserve the semantics of the instruction.
Definition at line 2145 of file Instructions.cpp.
References assert(), getMaskValue(), getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), setShuffleMask(), and llvm::UndefMaskElem.
Referenced by llvm::InstCombinerImpl::visitShuffleVectorInst().
commuteShuffleMask()
static void llvm::ShuffleVectorInst::commuteShuffleMask (MutableArrayRef< int > Mask, unsigned InVecNumElts) inline static
Change values in a shuffle permute mask assuming the two vector operands of length InVecNumElts have swapped position.
Definition at line 2422 of file Instructions.h.
References assert(), and Idx.
Referenced by foldSelectShuffleOfSelectShuffle(), foldShuffleWithInsert(), and simplifyShuffleVectorInst().
convertShuffleMaskForBitcode()
Constant * ShuffleVectorInst::convertShuffleMaskForBitcode (ArrayRef< int > Mask, Type * ResultTy) static
Definition at line 2264 of file Instructions.cpp.
References llvm::all_equal(), assert(), llvm::ConstantVector::get(), llvm::VectorType::get(), llvm::UndefValue::get(), llvm::ConstantInt::get(), llvm::Type::getContext(), llvm::Type::getInt32Ty(), llvm::Constant::getNullValue(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), Int32Ty, and llvm::UndefMaskElem.
Referenced by setShuffleMask(), and llvm::ShuffleVectorConstantExpr::ShuffleVectorConstantExpr().
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::ShuffleVectorInst::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
getMaskValue()
int llvm::ShuffleVectorInst::getMaskValue (unsigned Elt) const inline
Return the shuffle mask value of this instruction for the given element index.
Return UndefMaskElem if the element is undef.
Definition at line 2072 of file Instructions.h.
Referenced by commute(), and llvm::findScalarElement().
getShuffleMask() [1/3]
ArrayRef< int > llvm::ShuffleVectorInst::getShuffleMask () const inline
Definition at line 2096 of file Instructions.h.
Referenced by cloneImpl(), llvm::IRBuilderBase::CreateShuffleVector(), isConcat(), isIdentityWithExtract(), isIdentityWithPadding(), LLVMConstShuffleVector(), ShuffleVectorInst(), ShuffleVectorInst(), and llvm::UpgradeIntrinsicCall().
getShuffleMask() [2/3]
void ShuffleVectorInst::getShuffleMask (const Constant * Mask, SmallVectorImpl< int > & Result) static
Convert the input shuffle mask operand to a vector of integers.
Undefined elements of the mask are returned as UndefMaskElem.
Definition at line 2225 of file Instructions.cpp.
References assert(), llvm::CallingConv::C, I, and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::X86TargetLowering::lowerInterleavedStore(), llvm::InstCombinerImpl::simplifyBinOpSplats(), and llvm::InstCombinerImpl::visitShuffleVectorInst().
getShuffleMask() [3/3]
void llvm::ShuffleVectorInst::getShuffleMask (SmallVectorImpl< int > & Result) const inline
Return the mask for this instruction as a vector of integers.
Undefined elements of the mask are returned as UndefMaskElem.
Definition at line 2081 of file Instructions.h.
getShuffleMaskForBitcode()
Constant * llvm::ShuffleVectorInst::getShuffleMaskForBitcode () const inline
Return the mask for this instruction, for use in bitcode.
TODO: This is temporary until we decide a new bitcode encoding for shufflevector.
Definition at line 2089 of file Instructions.h.
getType()
VectorType * llvm::ShuffleVectorInst::getType () const inline
Overload to return most specific vector type.
Definition at line 2063 of file Instructions.h.
References llvm::Value::getType().
Referenced by commute(), llvm::findScalarElement(), isConcat(), isIdentityWithExtract(), isIdentityWithPadding(), isOneUseSingleSourceMask(), isReplicationMask(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::X86TargetLowering::lowerInterleavedStore(), setShuffleMask(), llvm::ARMTargetLowering::shouldConvertSplatType(), and llvm::InstCombinerImpl::visitShuffleVectorInst().
increasesLength()
bool llvm::ShuffleVectorInst::increasesLength () const inline
Return true if this shuffle returns a vector with a greater number of elements than its source vectors.
Example: shufflevector <2 x n> A, <2 x n> B, <1,2,3>
Definition at line 2113 of file Instructions.h.
References getType().
isConcat()
bool ShuffleVectorInst::isConcat () const
Return true if this shuffle concatenates its 2 source vectors.
This returns false if either input is undefined. In that case, the shuffle is is better classified as an identity with padding operation.
Definition at line 2580 of file Instructions.cpp.
References getShuffleMask(), getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and isIdentityMaskImpl().
isExtractSubvectorMask() [1/3]
bool ShuffleVectorInst::isExtractSubvectorMask (ArrayRef< int > Mask, int NumSrcElts, int & Index) static
Return true if this shuffle mask is an extract subvector mask.
A valid extract subvector mask returns a smaller vector from a single source operand. The base extraction index is returned as well.
Definition at line 2434 of file Instructions.cpp.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), isSingleSourceMaskImpl(), and llvm::Offset.
Referenced by areExtractShuffleVectors().
isExtractSubvectorMask() [2/3]
static bool llvm::ShuffleVectorInst::isExtractSubvectorMask (const Constant * Mask, int NumSrcElts, int & Index) inline static
Definition at line 2330 of file Instructions.h.
References assert().
isExtractSubvectorMask() [3/3]
bool llvm::ShuffleVectorInst::isExtractSubvectorMask (int & Index) const inline
Return true if this shuffle mask is an extract subvector mask.
Definition at line 2343 of file Instructions.h.
References getType().
isIdentity()
bool llvm::ShuffleVectorInst::isIdentity () const inline
Return true if this shuffle chooses elements from exactly one source vector without lane crossings and does not change the number of elements from its input vectors.
Example: shufflevector <4 x n> A, <4 x n> B, <4,undef,6,undef>
Definition at line 2164 of file Instructions.h.
References getType().
isIdentityMask() [1/2]
bool ShuffleVectorInst::isIdentityMask (ArrayRef< int > Mask) static
Return true if this shuffle mask chooses elements from exactly one source vector without lane crossings.
A shuffle using this mask is not necessarily a no-op because it may change the number of elements from its input vectors or it may provide demanded bits knowledge via undef lanes. Example: <undef,undef,2,3>
Definition at line 2320 of file Instructions.cpp.
References isIdentityMaskImpl().
Referenced by foldSelectShuffleOfSelectShuffle(), llvm::X86TTIImpl::getShuffleCost(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), isRepeatedNonIdentityClusteredMask(), llvm::ARMTargetLowering::isShuffleMaskLegal(), and reorderOrder().
isIdentityMask() [2/2]
static bool llvm::ShuffleVectorInst::isIdentityMask (const Constant * Mask) inline static
Definition at line 2147 of file Instructions.h.
References assert().
isIdentityWithExtract()
bool ShuffleVectorInst::isIdentityWithExtract () const
Return true if this shuffle extracts the first N elements of exactly one source vector.
Definition at line 2563 of file Instructions.cpp.
References getShuffleMask(), getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and isIdentityMaskImpl().
isIdentityWithPadding()
bool ShuffleVectorInst::isIdentityWithPadding () const
Return true if this shuffle lengthens exactly one source vector with undefs in the high elements.
Definition at line 2536 of file Instructions.cpp.
References getShuffleMask(), getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and isIdentityMaskImpl().
isInsertSubvectorMask() [1/3]
bool ShuffleVectorInst::isInsertSubvectorMask (ArrayRef< int > Mask, int NumSrcElts, int & NumSubElts, int & Index) static
Return true if this shuffle mask is an insert subvector mask.
A valid insert subvector mask inserts the lowest elements of a second source operand into an in-place first source operand operand. Both the sub vector width and the insertion index is returned.
Definition at line 2463 of file Instructions.cpp.
References assert(), llvm::APInt::getZero(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), isIdentityMaskImpl(), and isSingleSourceMaskImpl().
isInsertSubvectorMask() [2/3]
static bool llvm::ShuffleVectorInst::isInsertSubvectorMask (const Constant * Mask, int NumSrcElts, int & NumSubElts, int & Index) inline static
Definition at line 2360 of file Instructions.h.
References assert().
isInsertSubvectorMask() [3/3]
bool llvm::ShuffleVectorInst::isInsertSubvectorMask (int & NumSubElts, int & Index) const inline
Return true if this shuffle mask is an insert subvector mask.
Definition at line 2373 of file Instructions.h.
References getType().
isOneUseSingleSourceMask() [1/2]
bool ShuffleVectorInst::isOneUseSingleSourceMask (ArrayRef< int > Mask, int VF) static
Return true if this shuffle mask represents "clustered" mask of size VF, i.e.
each index between [0..VF) is used exactly once in each submask of size VF. For example, the mask for VF=4 is: 0, 1, 2, 3, 3, 2, 0, 1 - "clustered", because each submask of size 4 (0,1,2,3 and 3,2,0,1) uses indices [0..VF) exactly one time. 0, 1, 2, 3, 3, 3, 1, 0 - not "clustered", because element 3 is used twice in the second submask (3,3,1,0) and index 2 is not used at all.
Definition at line 2684 of file Instructions.cpp.
References llvm::all_of(), llvm::for_each(), Idx, llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm::UndefMaskElem.
Referenced by llvm::slpvectorizer::BoUpSLP::getReorderingData(), and isOneUseSingleSourceMask().
isOneUseSingleSourceMask() [2/2]
bool ShuffleVectorInst::isOneUseSingleSourceMask (int VF) const
Return true if this shuffle mask is a one-use-single-source("clustered") mask.
Return true if this shuffle mask is a replication mask.
Definition at line 2704 of file Instructions.cpp.
References getType(), isOneUseSingleSourceMask(), and isSingleSourceMask().
isReplicationMask() [1/3]
bool ShuffleVectorInst::isReplicationMask (ArrayRef< int > Mask, int & ReplicationFactor, int & VF) static
Return true if this shuffle mask replicates each of the VF elements in a vector ReplicationFactor times.
For example, the mask for ReplicationFactor=3 and VF=4 is: <0,0,0,1,1,1,2,2,2,3,3,3>
Definition at line 2623 of file Instructions.cpp.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::is_contained(), isReplicationMaskWithParams(), llvm::reverse(), size(), and llvm::UndefMaskElem.
isReplicationMask() [2/3]
static bool llvm::ShuffleVectorInst::isReplicationMask (const Constant * Mask, int & ReplicationFactor, int & VF) inline static
Definition at line 2390 of file Instructions.h.
References assert().
isReplicationMask() [3/3]
bool ShuffleVectorInst::isReplicationMask (int & ReplicationFactor, int & VF) const
Return true if this shuffle mask is a replication mask.
Definition at line 2669 of file Instructions.cpp.
References getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and isReplicationMaskWithParams().
isReverse()
bool llvm::ShuffleVectorInst::isReverse () const inline
Return true if this shuffle swaps the order of elements from exactly one source vector.
Example: shufflevector <4 x n> A, <4 x n> B, <3,undef,1,undef> TODO: Optionally allow length-changing shuffles.
Definition at line 2230 of file Instructions.h.
References isReverseMask().
isReverseMask() [1/2]
bool ShuffleVectorInst::isReverseMask (ArrayRef< int > Mask) static
Return true if this shuffle mask swaps the order of elements from exactly one source vector.
Example: <7,6,undef,4> This assumes that vector operands are the same length as the mask.
Definition at line 2326 of file Instructions.cpp.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and isSingleSourceMask().
Referenced by llvm::BasicTTIImplBase< T >::improveShuffleKindFromMask().
isReverseMask() [2/2]
static bool llvm::ShuffleVectorInst::isReverseMask (const Constant * Mask) inline static
Definition at line 2219 of file Instructions.h.
References assert(), and isReverseMask().
isSelect()
bool llvm::ShuffleVectorInst::isSelect () const inline
Return true if this shuffle chooses elements from its source vectors without lane crossings and all operands have the same number of elements.
In other words, this shuffle is equivalent to a vector select with a constant condition operand. Example: shufflevector <4 x n> A, <4 x n> B, <undef,1,6,3> This returns false if the mask does not choose from both input vectors. In that case, the shuffle is better classified as an identity shuffle. TODO: Optionally allow length-changing shuffles.
Definition at line 2210 of file Instructions.h.
isSelectMask() [1/2]
bool ShuffleVectorInst::isSelectMask (ArrayRef< int > Mask) static
Return true if this shuffle mask chooses elements from its source vectors without lane crossings.
A shuffle using this mask would be equivalent to a vector select with a constant condition operand. Example: <4,1,6,undef> This returns false if the mask does not choose from both input vectors. In that case, the shuffle is better classified as an identity shuffle. This assumes that vector operands are the same length as the mask (a length-changing shuffle can never be equivalent to a vector select).
Definition at line 2356 of file Instructions.cpp.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and isSingleSourceMask().
Referenced by foldSelectShuffleOfSelectShuffle(), and llvm::BasicTTIImplBase< T >::improveShuffleKindFromMask().
isSelectMask() [2/2]
static bool llvm::ShuffleVectorInst::isSelectMask (const Constant * Mask) inline static
Definition at line 2195 of file Instructions.h.
References assert().
isSingleSource()
bool llvm::ShuffleVectorInst::isSingleSource () const inline
Return true if this shuffle chooses elements from exactly one source vector without changing the length of that vector.
Example: shufflevector <4 x n> A, <4 x n> B, <3,0,undef,3> TODO: Optionally allow length-changing shuffles.
Definition at line 2137 of file Instructions.h.
isSingleSourceMask() [1/2]
bool ShuffleVectorInst::isSingleSourceMask (ArrayRef< int > Mask) static
Return true if this shuffle mask chooses elements from exactly one source vector.
Example: <7,5,undef,7> This assumes that vector operands are the same length as the mask.
Definition at line 2302 of file Instructions.cpp.
References isSingleSourceMaskImpl().
Referenced by isOneUseSingleSourceMask(), isReverseMask(), isSelectMask(), and isZeroEltSplatMask().
isSingleSourceMask() [2/2]
static bool llvm::ShuffleVectorInst::isSingleSourceMask (const Constant * Mask) inline static
Definition at line 2126 of file Instructions.h.
References assert().
isSplice()
bool llvm::ShuffleVectorInst::isSplice (int & Index) const inline
Return true if this shuffle splices two inputs without changing the length of the vectors.
This operation concatenates the two inputs together and then extracts an original width vector starting from the splice index. Example: shufflevector <4 x n> A, <4 x n> B, <1,2,3,4>
Definition at line 2321 of file Instructions.h.
isSpliceMask() [1/2]
bool ShuffleVectorInst::isSpliceMask (ArrayRef< int > Mask, int & Index) static
Return true if this shuffle mask is a splice mask, concatenating the two inputs together and then extracts an original width vector starting from the splice index.
Example: shufflevector <4 x n> A, <4 x n> B, <1,2,3,4>
Definition at line 2403 of file Instructions.cpp.
References E, I, and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::BasicTTIImplBase< T >::improveShuffleKindFromMask().
isSpliceMask() [2/2]
static bool llvm::ShuffleVectorInst::isSpliceMask (const Constant * Mask, int & Index) inline static
Definition at line 2310 of file Instructions.h.
References assert().
isTranspose()
bool llvm::ShuffleVectorInst::isTranspose () const inline
Return true if this shuffle transposes the elements of its inputs without changing the length of the vectors.
This operation may also be known as a merge or interleave. See the description for isTransposeMask() for the exact specification. Example: shufflevector <4 x n> A, <4 x n> B, <0,4,2,6>
Definition at line 2301 of file Instructions.h.
isTransposeMask() [1/2]
bool ShuffleVectorInst::isTransposeMask (ArrayRef< int > Mask) static
Return true if this shuffle mask is a transpose mask.
Transpose vector masks transpose a 2xn matrix. They read corresponding even- or odd-numbered vector elements from two n-dimensional source vectors and write each result into consecutive elements of an n-dimensional destination vector. Two shuffles are necessary to complete the transpose, one for the even elements and another for the odd elements. This description closely follows how the TRN1 and TRN2 AArch64 instructions operate.
For example, a simple 2x2 matrix can be transposed with:
; Original matrix m0 = < a, b > m1 = < c, d >
; Transposed matrix t0 = < a, c > = shufflevector m0, m1, < 0, 2 > t1 = < b, d > = shufflevector m0, m1, < 1, 3 >
For matrices having greater than n columns, the resulting nx2 transposed matrix is stored in two result vectors such that one vector contains interleaved elements from all the even-numbered rows and the other vector contains interleaved elements from all the odd-numbered rows. For example, a 2x4 matrix can be transposed with:
; Original matrix m0 = < a, b, c, d > m1 = < e, f, g, h >
; Transposed matrix t0 = < a, e, c, g > = shufflevector m0, m1 < 0, 4, 2, 6 > t1 = < b, f, d, h > = shufflevector m0, m1 < 1, 5, 3, 7 >
Definition at line 2369 of file Instructions.cpp.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm::isPowerOf2_32().
Referenced by llvm::BasicTTIImplBase< T >::improveShuffleKindFromMask().
isTransposeMask() [2/2]
static bool llvm::ShuffleVectorInst::isTransposeMask (const Constant * Mask) inline static
Definition at line 2289 of file Instructions.h.
References assert().
isValidOperands() [1/2]
bool ShuffleVectorInst::isValidOperands (const Value * V1, const Value * V2, ArrayRef< int > Mask) static
Definition at line 2163 of file Instructions.cpp.
References llvm::all_equal(), llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm::UndefMaskElem.
isValidOperands() [2/2]
bool ShuffleVectorInst::isValidOperands (const Value * V1, const Value * V2, const Value * Mask) static
Return true if a shufflevector instruction can be formed with the specified operands.
Definition at line 2183 of file Instructions.cpp.
References llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::Type::isVectorTy(), and llvm::User::Op().
Referenced by llvm::ConstantExpr::getShuffleVector(), llvm::ShuffleVectorConstantExpr::ShuffleVectorConstantExpr(), ShuffleVectorInst(), ShuffleVectorInst(), ShuffleVectorInst(), ShuffleVectorInst(), and validShuffleVectorIndex().
isZeroEltSplat()
bool llvm::ShuffleVectorInst::isZeroEltSplat () const inline
Return true if all elements of this shuffle are the same value as the first element of exactly one source vector without changing the length of that vector.
Example: shufflevector <4 x n> A, <4 x n> B, <undef,0,undef,0> TODO: Optionally allow length-changing shuffles. TODO: Optionally allow splats from other elements.
Definition at line 2252 of file Instructions.h.
isZeroEltSplatMask() [1/2]
bool ShuffleVectorInst::isZeroEltSplatMask (ArrayRef< int > Mask) static
Return true if this shuffle mask chooses all elements with the same value as the first element of exactly one source vector.
Example: <4,undef,undef,4> This assumes that vector operands are the same length as the mask.
Definition at line 2344 of file Instructions.cpp.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and isSingleSourceMask().
Referenced by llvm::BasicTTIImplBase< T >::improveShuffleKindFromMask().
isZeroEltSplatMask() [2/2]
static bool llvm::ShuffleVectorInst::isZeroEltSplatMask (const Constant * Mask) inline static
Definition at line 2239 of file Instructions.h.
References assert().
operator delete()
void llvm::ShuffleVectorInst::operator delete (void * Ptr) inline
Definition at line 2048 of file Instructions.h.
References Ptr.
operator new()
void * llvm::ShuffleVectorInst::operator new (size_t S) inline
Definition at line 2047 of file Instructions.h.
setShuffleMask()
void ShuffleVectorInst::setShuffleMask (ArrayRef< int > Mask)
Definition at line 2259 of file Instructions.cpp.
References convertShuffleMaskForBitcode(), and getType().
Referenced by commute(), ShuffleVectorInst(), ShuffleVectorInst(), ShuffleVectorInst(), and ShuffleVectorInst().
Friends And Related Symbol Documentation
Instruction
friend class Instruction friend
Definition at line 2023 of file Instructions.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Instructions.h
lib/IR/Instructions.cpp