LLVM: llvm::sampleprof::SampleProfileWriterText Class Reference
llvm::sampleprof::SampleProfileWriterText Class Reference
Sample-based profile writer (text format).
#include "llvm/ProfileData/SampleProfWriter.h"
Public Member Functions
std::error_code writeSample (const FunctionSamples &S) override
Write samples to a text file.
Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
virtual ~SampleProfileWriter ()=default
virtual std::error_code write (const SampleProfileMap &ProfileMap)
Write all the sample profiles in the given map of samples.
raw_ostream & getOutputStream ()
virtual void setProfileSymbolList (ProfileSymbolList *PSL)
virtual void setToCompressAllSections ()
virtual void setUseMD5 ()
virtual void setPartialProfile ()
virtual void resetSecLayout (SectionLayout SL)
Protected Member Functions
SampleProfileWriterText (std::unique_ptr< raw_ostream > &OS)
std::error_code writeHeader (const SampleProfileMap &ProfileMap) override
Write a file header for the profile file.
Protected Member Functions inherited from llvm::sampleprof::SampleProfileWriter
SampleProfileWriter (std::unique_ptr< raw_ostream > &OS)
virtual std::error_code writeFuncProfiles (const SampleProfileMap &ProfileMap)
void computeSummary (const SampleProfileMap &ProfileMap)
Compute summary for this profile.
Friends
ErrorOr< std::unique_ptr< SampleProfileWriter > > SampleProfileWriter::create (std::unique_ptr< raw_ostream > &OS, SampleProfileFormat Format)
Additional Inherited Members
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileWriter
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (StringRef Filename, SampleProfileFormat Format)
Profile writer factory.
static ErrorOr< std::unique_ptr< SampleProfileWriter > > create (std::unique_ptr< raw_ostream > &OS, SampleProfileFormat Format)
Create a new stream writer based on the value of Format.
Protected Attributes inherited from llvm::sampleprof::SampleProfileWriter
std::unique_ptr< raw_ostream > OutputStream
Output stream where to emit the profile to.
std::unique_ptr< ProfileSummary > Summary
Profile summary.
SampleProfileFormat Format = SPF_None
Profile format.
Detailed Description
Sample-based profile writer (text format).
Definition at line 96 of file SampleProfWriter.h.
Constructor & Destructor Documentation
SampleProfileWriterText()
llvm::sampleprof::SampleProfileWriterText::SampleProfileWriterText (std::unique_ptr< raw_ostream > & OS) inline protected
Definition at line 101 of file SampleProfWriter.h.
Member Function Documentation
writeHeader()
std::error_code llvm::sampleprof::SampleProfileWriterText::writeHeader (const SampleProfileMap & ProfileMap) inline override protected virtual
Write a file header for the profile file.
Implements llvm::sampleprof::SampleProfileWriter.
Definition at line 104 of file SampleProfWriter.h.
References llvm::success.
writeSample()
std::error_code SampleProfileWriterText::writeSample (const FunctionSamples & S) override virtual
Write samples to a text file.
Note: it may be tempting to implement this in terms of FunctionSamples::print(). Please don't. The dump functionality is intended for debugging and has no specified form.
The format used here is more structured and deliberate because it needs to be parsed by the SampleProfileReaderText class.
Implements llvm::sampleprof::SampleProfileWriter.
Definition at line 470 of file SampleProfWriter.cpp.
References llvm::sampleprof::SampleContext::getAllAttributes(), llvm::sampleprof::FunctionSamples::getBodySamples(), llvm::sampleprof::FunctionSamples::getCallsiteSamples(), llvm::sampleprof::FunctionSamples::getContext(), llvm::sampleprof::FunctionSamples::getFunctionHash(), llvm::sampleprof::FunctionSamples::getHeadSamples(), llvm::sampleprof::FunctionSamples::getName(), llvm::sampleprof::FunctionSamples::getTotalSamples(), I, llvm::sampleprof::SampleProfileWriter::OutputStream, llvm::sampleprof::FunctionSamples::ProfileIsCS, llvm::sampleprof::FunctionSamples::ProfileIsProbeBased, llvm::success, llvm::sampleprof::SampleContext::toString(), and writeSample().
Referenced by writeSample().
Friends And Related Symbol Documentation
SampleProfileWriter::create
ErrorOr< std::unique_ptr< SampleProfileWriter > > SampleProfileWriter::create (std::unique_ptr< raw_ostream > & OS, SampleProfileFormat Format) friend
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfWriter.h
lib/ProfileData/SampleProfWriter.cpp