LLVM: llvm::coverage::InstantiationGroup Class Reference
llvm::coverage::InstantiationGroup Class Reference
An instantiation group contains a FunctionRecord list, such that each record corresponds to a distinct instantiation of the same function.
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
Public Member Functions
InstantiationGroup (const InstantiationGroup &)=delete
InstantiationGroup (InstantiationGroup &&)=default
size_t size () const
Get the number of instantiations in this group.
unsigned getLine () const
Get the line where the common function was defined.
unsigned getColumn () const
Get the column where the common function was defined.
bool hasName () const
Check if the instantiations in this group have a common mangled name.
StringRef getName () const
Get the common mangled name for instantiations in this group.
uint64_t getTotalExecutionCount () const
Get the total execution count of all instantiations in this group.
ArrayRef< const FunctionRecord * > getInstantiations () const
Get the instantiations in this group.
Friends
class CoverageMapping
Detailed Description
An instantiation group contains a FunctionRecord list, such that each record corresponds to a distinct instantiation of the same function.
Note that it's possible for a function to have more than one instantiation (consider C++ template specializations or static inline functions).
Definition at line 478 of file CoverageMapping.h.
Constructor & Destructor Documentation
InstantiationGroup() [1/2]
llvm::coverage::InstantiationGroup::InstantiationGroup (const InstantiationGroup &) delete
InstantiationGroup() [2/2]
llvm::coverage::InstantiationGroup::InstantiationGroup (InstantiationGroup &&) default
Member Function Documentation
getColumn()
unsigned llvm::coverage::InstantiationGroup::getColumn () const inline
Get the column where the common function was defined.
Definition at line 500 of file CoverageMapping.h.
getInstantiations()
ArrayRef< const FunctionRecord * > llvm::coverage::InstantiationGroup::getInstantiations () const inline
Get the instantiations in this group.
Definition at line 525 of file CoverageMapping.h.
getLine()
unsigned llvm::coverage::InstantiationGroup::getLine () const inline
Get the line where the common function was defined.
Definition at line 497 of file CoverageMapping.h.
getName()
StringRef llvm::coverage::InstantiationGroup::getName () const inline
Get the common mangled name for instantiations in this group.
Definition at line 511 of file CoverageMapping.h.
References assert(), and hasName().
getTotalExecutionCount()
uint64_t llvm::coverage::InstantiationGroup::getTotalExecutionCount () const inline
Get the total execution count of all instantiations in this group.
Definition at line 517 of file CoverageMapping.h.
References F.
hasName()
bool llvm::coverage::InstantiationGroup::hasName () const inline
Check if the instantiations in this group have a common mangled name.
Definition at line 503 of file CoverageMapping.h.
References E, I, and Name.
Referenced by getName().
size()
size_t llvm::coverage::InstantiationGroup::size () const inline
Get the number of instantiations in this group.
Definition at line 494 of file CoverageMapping.h.
Friends And Related Symbol Documentation
CoverageMapping
friend class CoverageMapping friend
Definition at line 479 of file CoverageMapping.h.
The documentation for this class was generated from the following file:
include/llvm/ProfileData/Coverage/CoverageMapping.h