LLVM: llvm::logicalview::LVOperation Class Reference
llvm::logicalview::LVOperation Class Reference final
#include "llvm/DebugInfo/LogicalView/Core/LVLocation.h"
Public Member Functions
LVOperation ()=delete
LVOperation (LVSmall Opcode, LVUnsigned Operand1, LVUnsigned Operand2)
LVOperation (const LVOperation &)=delete
LVOperation & operator= (const LVOperation &)=delete
~LVOperation ()=default
LVSmall getOpcode () const
uint64_t getOperand1 () const
uint64_t getOperand2 () const
std::string getOperandsDWARFInfo ()
std::string getOperandsCodeViewInfo ()
void print (raw_ostream &OS, bool Full=true) const
void dump ()
Detailed Description
Definition at line 27 of file LVLocation.h.
Constructor & Destructor Documentation
LVOperation() [1/3]
llvm::logicalview::LVOperation::LVOperation () delete
LVOperation() [2/3]
llvm::logicalview::LVOperation::LVOperation (LVSmall Opcode, LVUnsigned Operand1, LVUnsigned Operand2) inline
Definition at line 40 of file LVLocation.h.
References Operands.
LVOperation() [3/3]
llvm::logicalview::LVOperation::LVOperation (const LVOperation &) delete
~LVOperation()
llvm::logicalview::LVOperation::~LVOperation () default
Member Function Documentation
dump()
void llvm::logicalview::LVOperation::dump () inline
Definition at line 58 of file LVLocation.h.
References llvm::dbgs(), and print().
getOpcode()
LVSmall llvm::logicalview::LVOperation::getOpcode () const inline
Definition at line 49 of file LVLocation.h.
getOperand1()
uint64_t llvm::logicalview::LVOperation::getOperand1 () const inline
Definition at line 50 of file LVLocation.h.
References Operands.
getOperand2()
uint64_t llvm::logicalview::LVOperation::getOperand2 () const inline
Definition at line 51 of file LVLocation.h.
References Operands.
getOperandsCodeViewInfo()
std::string LVOperation::getOperandsCodeViewInfo ()
Definition at line 347 of file LVLocation.cpp.
References llvm::format(), llvm::logicalview::getCodeViewOperationCode(), llvm::logicalview::getReader(), llvm::logicalview::LVReader::getRegisterName(), llvm::logicalview::hexString(), and llvm::String.
getOperandsDWARFInfo()
std::string LVOperation::getOperandsDWARFInfo ()
Definition at line 27 of file LVLocation.cpp.
References llvm::dwarf::DW_OP_hi_user, llvm::format(), llvm::logicalview::getReader(), getRegisterName(), llvm::logicalview::LVReader::getRegisterName(), llvm::logicalview::hexString(), llvm::logicalview::LVLocationMemberOffset, and llvm::String.
operator=()
LVOperation & llvm::logicalview::LVOperation::operator= (const LVOperation &) delete
print()
void LVOperation::print (raw_ostream & OS, bool Full = true) const
Definition at line 23 of file LVLocation.cpp.
Referenced by dump().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVLocation.h
lib/DebugInfo/LogicalView/Core/LVLocation.cpp