LLVM: llvm::VEInstPrinter Class Reference
llvm::VEInstPrinter Class Reference
#include "Target/VE/MCTargetDesc/VEInstPrinter.h"
Public Member Functions
VEInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printRegName (raw_ostream &OS, MCRegister Reg) const override
Print the assembler register name.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &OS) override
Print the specified MCInst to the specified raw_ostream.
std::pair< const char *, uint64_t > getMnemonic (const MCInst *MI) override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
bool printAliasInstr (const MCInst *, uint64_t Address, const MCSubtargetInfo &, raw_ostream &)
void printInstruction (const MCInst *, uint64_t, const MCSubtargetInfo &, raw_ostream &)
void printOperand (const MCInst *MI, int OpNum, const MCSubtargetInfo &STI, raw_ostream &OS)
void printMemASXOperand (const MCInst *MI, int OpNum, const MCSubtargetInfo &STI, raw_ostream &OS, const char *Modifier=nullptr)
void printMemASOperandASX (const MCInst *MI, int OpNum, const MCSubtargetInfo &STI, raw_ostream &OS, const char *Modifier=nullptr)
void printMemASOperandRRM (const MCInst *MI, int OpNum, const MCSubtargetInfo &STI, raw_ostream &OS, const char *Modifier=nullptr)
void printMemASOperandHM (const MCInst *MI, int OpNum, const MCSubtargetInfo &STI, raw_ostream &OS, const char *Modifier=nullptr)
void printMImmOperand (const MCInst *MI, int OpNum, const MCSubtargetInfo &STI, raw_ostream &OS)
void printCCOperand (const MCInst *MI, int OpNum, const MCSubtargetInfo &STI, raw_ostream &OS)
void printRDOperand (const MCInst *MI, int OpNum, const MCSubtargetInfo &STI, raw_ostream &OS)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (MCRegister Reg, unsigned AltIdx=VE::NoRegAltName)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
Detailed Description
Definition at line 21 of file VEInstPrinter.h.
Constructor & Destructor Documentation
VEInstPrinter()
llvm::VEInstPrinter::VEInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 23 of file VEInstPrinter.h.
Member Function Documentation
getMnemonic()
std::pair< const char *, uint64_t > llvm::VEInstPrinter::getMnemonic (const MCInst * MI) override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
getRegisterName()
static const char * llvm::VEInstPrinter::getRegisterName (MCRegister Reg, unsigned AltIdx = VE::NoRegAltName) static
Referenced by llvm::VETargetAsmStreamer::emitVERegisterIgnore(), llvm::VETargetAsmStreamer::emitVERegisterScratch(), and printRegName().
printAliasInstr()
bool llvm::VEInstPrinter::printAliasInstr (const MCInst * , uint64_t Address, const MCSubtargetInfo & , raw_ostream &)
Referenced by printInst().
printCCOperand()
void VEInstPrinter::printCCOperand (const MCInst * MI, int OpNum, const MCSubtargetInfo & STI, raw_ostream & OS)
Definition at line 206 of file VEInstPrinter.cpp.
References CC, MI, and llvm::VECondCodeToString().
printInst()
void VEInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 39 of file VEInstPrinter.cpp.
References MI, printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), and printInstruction().
printInstruction()
void llvm::VEInstPrinter::printInstruction (const MCInst * , uint64_t , const MCSubtargetInfo & , raw_ostream &)
Referenced by printInst().
printMemASOperandASX()
void VEInstPrinter::printMemASOperandASX (const MCInst * MI, int OpNum, const MCSubtargetInfo & STI, raw_ostream & OS, const char * Modifier = nullptr)
Definition at line 111 of file VEInstPrinter.cpp.
References MI, and printOperand().
printMemASOperandHM()
void VEInstPrinter::printMemASOperandHM (const MCInst * MI, int OpNum, const MCSubtargetInfo & STI, raw_ostream & OS, const char * Modifier = nullptr)
Definition at line 173 of file VEInstPrinter.cpp.
References MI, and printOperand().
printMemASOperandRRM()
void VEInstPrinter::printMemASOperandRRM (const MCInst * MI, int OpNum, const MCSubtargetInfo & STI, raw_ostream & OS, const char * Modifier = nullptr)
Definition at line 142 of file VEInstPrinter.cpp.
References MI, and printOperand().
printMemASXOperand()
void VEInstPrinter::printMemASXOperand (const MCInst * MI, int OpNum, const MCSubtargetInfo & STI, raw_ostream & OS, const char * Modifier = nullptr)
Definition at line 67 of file VEInstPrinter.cpp.
References MI, and printOperand().
printMImmOperand()
void VEInstPrinter::printMImmOperand (const MCInst * MI, int OpNum, const MCSubtargetInfo & STI, raw_ostream & OS)
Definition at line 196 of file VEInstPrinter.cpp.
References MI.
printOperand()
void VEInstPrinter::printOperand (const MCInst * MI, int OpNum, const MCSubtargetInfo & STI, raw_ostream & OS)
Definition at line 47 of file VEInstPrinter.cpp.
References assert(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::MCInstPrinter::MAI, MI, llvm::MCExpr::print(), and printRegName().
Referenced by printMemASOperandASX(), printMemASOperandHM(), printMemASOperandRRM(), and printMemASXOperand().
printRDOperand()
void VEInstPrinter::printRDOperand (const MCInst * MI, int OpNum, const MCSubtargetInfo & STI, raw_ostream & OS)
Definition at line 212 of file VEInstPrinter.cpp.
References MI, and llvm::VERDToString().
printRegName()
void VEInstPrinter::printRegName (raw_ostream & OS, MCRegister Reg) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 30 of file VEInstPrinter.cpp.
References llvm::MCRegisterClass::contains(), llvm::MCRegisterInfo::getRegClass(), getRegisterName(), and llvm::MCInstPrinter::MRI.
Referenced by printOperand().
The documentation for this class was generated from the following files:
lib/Target/VE/MCTargetDesc/VEInstPrinter.h
lib/Target/VE/MCTargetDesc/VEInstPrinter.cpp