LLVM: llvm::DISubprogram Class Reference
llvm::DISubprogram Class Reference
Subprogram description.
#include "llvm/IR/DebugInfoMetadata.h"
Public Types
enum DISPFlags : uint32_t { SPFlagNonvirtual = SPFlagZero , SPFlagVirtuality = SPFlagVirtual | SPFlagPureVirtual }
Debug info subprogram flags.
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic , FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range<op_iterator>
Public Types inherited from llvm::Metadata
enum MetadataKind
Public Member Functions
DEFINE_MDNODE_GET (DISubprogram,(DIScope *Scope, StringRef Name, StringRef LinkageName, DIFile *File, unsigned Line, DISubroutineType *Type, unsigned ScopeLine, DIType *ContainingType, unsigned VirtualIndex, int ThisAdjustment, DIFlags Flags, DISPFlags SPFlags, DICompileUnit *Unit, DITemplateParameterArray TemplateParams=nullptr, DISubprogram *Declaration=nullptr, DINodeArray RetainedNodes=nullptr, DITypeArray ThrownTypes=nullptr, DINodeArray Annotations=nullptr, StringRef TargetFuncName=""),(Scope, Name, LinkageName, File, Line, Type, ScopeLine, ContainingType, VirtualIndex, ThisAdjustment, Flags, SPFlags, Unit, TemplateParams, Declaration, RetainedNodes, ThrownTypes, Annotations, TargetFuncName)) DEFINE_MDNODE_GET(DISubprogram
Public Member Functions inherited from llvm::DILocalScope
DISubprogram * getSubprogram () const
Get the subprogram for this scope.
DILocalScope * getNonLexicalBlockFileScope () const
Get the first non DILexicalBlockFile scope of this scope.
Public Member Functions inherited from llvm::DIScope
DIFile * getFile () const
StringRef getFilename () const
StringRef getDirectory () const
std::optional< StringRef > getSource () const
StringRef getName () const
DIScope * getScope () const
Metadata * getRawFile () const
Return the raw underlying file.
Public Member Functions inherited from llvm::DINode
dwarf::Tag getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
void dumpTree () const
User-friendly dump in tree shape.
void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static DISPFlags getFlag (StringRef Flag)
static StringRef getFlagString (DISPFlags Flag)
static DISPFlags splitFlags (DISPFlags Flags, SmallVectorImpl< DISPFlags > &SplitFlags)
Split up a flags bitfield for easier printing.
static DISPFlags toSPFlags (bool IsLocalToUnit, bool IsDefinition, bool IsOptimized, unsigned Virtuality=SPFlagNonvirtual, bool IsMainSubprogram=false)
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DILocalScope
static DILocalScope * cloneScopeForSubprogram (DILocalScope &RootScope, DISubprogram &NewSP, LLVMContext &Ctx, DenseMap< const MDNode *, MDNode * > &Cache)
Traverses the scope chain rooted at RootScope until it hits a Subprogram, recreating the chain with "NewSP" instead.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIScope
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static DIFlags getFlag (StringRef Flag)
static StringRef getFlagString (DIFlags Flag)
static DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
Public Attributes
Metadata * Scope
Metadata MDString * Name
Metadata MDString MDString * LinkageName
Metadata MDString MDString Metadata * File
Metadata MDString MDString Metadata unsigned Line
Metadata MDString MDString Metadata unsigned Metadata * Type
Metadata MDString MDString Metadata unsigned Metadata unsigned ScopeLine
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata * ContainingType
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned VirtualIndex
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int ThisAdjustment
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags Flags
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags SPFlags
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata * Unit
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata Metadata * TemplateParams = nullptr
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata Metadata Metadata * Declaration = nullptr
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata Metadata Metadata Metadata * RetainedNodes = nullptr
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata Metadata Metadata Metadata Metadata * ThrownTypes = nullptr
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata Metadata Metadata Metadata Metadata Metadata * Annotations = nullptr
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata Metadata Metadata Metadata Metadata Metadata MDString * TargetFuncName
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range<MDOperand *>
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DILocalScope
DILocalScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops)
~DILocalScope ()=default
Protected Member Functions inherited from llvm::DIScope
DIScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops)
~DIScope ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~DINode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~MDNode ()=default
void * operator new (size_t Size, size_t NumOps, StorageType Storage)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Subprogram description.
Definition at line 1851 of file DebugInfoMetadata.h.
Member Enumeration Documentation
DISPFlags
enum llvm::DISubprogram::DISPFlags : uint32_t
Debug info subprogram flags.
Enumerator
SPFlagNonvirtual
SPFlagVirtuality
Definition at line 1866 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
static bool llvm::DISubprogram::classof (const Metadata * MD) inline static
Definition at line 2113 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
DEFINE_MDNODE_GET()
llvm::DISubprogram::DEFINE_MDNODE_GET (DISubprogram , (DIScope *Scope, StringRef Name, StringRef LinkageName, DIFile *File, unsigned Line, DISubroutineType *Type, unsigned ScopeLine, DIType *ContainingType, unsigned VirtualIndex, int ThisAdjustment, DIFlags Flags, DISPFlags SPFlags, DICompileUnit *Unit, DITemplateParameterArray TemplateParams=nullptr, DISubprogram *Declaration=nullptr, DINodeArray RetainedNodes=nullptr, DITypeArray ThrownTypes=nullptr, DINodeArray Annotations=nullptr, StringRef TargetFuncName="") , (Scope, Name, LinkageName, File, Line, Type, ScopeLine, ContainingType, VirtualIndex, ThisAdjustment, Flags, SPFlags, Unit, TemplateParams, Declaration, RetainedNodes, ThrownTypes, Annotations, TargetFuncName))
getFlag()
DISubprogram::DISPFlags DISubprogram::getFlag (StringRef Flag) static
Definition at line 1006 of file DebugInfoMetadata.cpp.
Referenced by llvm::LLParser::parseMDField().
getFlagString()
StringRef DISubprogram::getFlagString (DISPFlags Flag) static
Definition at line 1013 of file DebugInfoMetadata.cpp.
References SPFlagVirtuality.
splitFlags()
DISubprogram::DISPFlags DISubprogram::splitFlags (DISPFlags Flags, SmallVectorImpl< DISPFlags > & SplitFlags) static
Split up a flags bitfield for easier printing.
Split Flags into SplitFlags, a vector of its components. Returns any remaining (unrecognized) bits.
Definition at line 1027 of file DebugInfoMetadata.cpp.
toSPFlags()
DISubprogram::DISPFlags DISubprogram::toSPFlags (bool IsLocalToUnit, bool IsDefinition, bool IsOptimized, unsigned Virtuality = SPFlagNonvirtual, bool IsMainSubprogram = false) static
Definition at line 950 of file DebugInfoMetadata.cpp.
References SPFlagVirtuality.
Referenced by pack_into_DISPFlags().
Friends And Related Symbol Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 1852 of file DebugInfoMetadata.h.
MDNode
friend class MDNode friend
Definition at line 1853 of file DebugInfoMetadata.h.
Member Data Documentation
Annotations
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata Metadata Metadata Metadata Metadata Metadata* llvm::DISubprogram::Annotations = nullptr
Definition at line 1961 of file DebugInfoMetadata.h.
ContainingType
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata* llvm::DISubprogram::ContainingType
Definition at line 1957 of file DebugInfoMetadata.h.
Declaration
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata Metadata Metadata* llvm::DISubprogram::Declaration = nullptr
Definition at line 1959 of file DebugInfoMetadata.h.
File
Metadata MDString MDString Metadata* llvm::DISubprogram::File
Definition at line 1955 of file DebugInfoMetadata.h.
Flags
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags llvm::DISubprogram::Flags
Definition at line 1958 of file DebugInfoMetadata.h.
Line
Metadata MDString MDString Metadata unsigned llvm::DISubprogram::Line
Definition at line 1956 of file DebugInfoMetadata.h.
LinkageName
Metadata MDString MDString* llvm::DISubprogram::LinkageName
Definition at line 1955 of file DebugInfoMetadata.h.
Name
Metadata MDString* llvm::DISubprogram::Name
Definition at line 1955 of file DebugInfoMetadata.h.
RetainedNodes
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata Metadata Metadata Metadata* llvm::DISubprogram::RetainedNodes = nullptr
Definition at line 1960 of file DebugInfoMetadata.h.
Scope
Metadata* llvm::DISubprogram::Scope
Definition at line 1955 of file DebugInfoMetadata.h.
ScopeLine
Metadata MDString MDString Metadata unsigned Metadata unsigned llvm::DISubprogram::ScopeLine
Definition at line 1956 of file DebugInfoMetadata.h.
SPFlags
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags llvm::DISubprogram::SPFlags
Definition at line 1958 of file DebugInfoMetadata.h.
TargetFuncName
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata Metadata Metadata Metadata Metadata Metadata MDString* llvm::DISubprogram::TargetFuncName
Definition at line 1961 of file DebugInfoMetadata.h.
TemplateParams
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata Metadata* llvm::DISubprogram::TemplateParams = nullptr
Definition at line 1959 of file DebugInfoMetadata.h.
ThisAdjustment
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int llvm::DISubprogram::ThisAdjustment
Definition at line 1957 of file DebugInfoMetadata.h.
ThrownTypes
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata Metadata Metadata Metadata Metadata* llvm::DISubprogram::ThrownTypes = nullptr
Definition at line 1960 of file DebugInfoMetadata.h.
Type
Metadata MDString MDString Metadata unsigned Metadata* llvm::DISubprogram::Type
Definition at line 1956 of file DebugInfoMetadata.h.
Unit
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned int DIFlags DISPFlags Metadata* llvm::DISubprogram::Unit
Definition at line 1958 of file DebugInfoMetadata.h.
VirtualIndex
Metadata MDString MDString Metadata unsigned Metadata unsigned Metadata unsigned llvm::DISubprogram::VirtualIndex
Definition at line 1957 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp