LLVM: llvm::Module Class Reference
llvm::Module Class Reference
A Module instance is used to store all the information related to an LLVM module.
#include "llvm/IR/Module.h"
Classes
class debug_compile_units_iterator
An iterator for DICompileUnits that skips those marked NoDebug.
struct ModuleFlagEntry
Public Member Functions
void dropTriviallyDeadConstantArrays ()
Destroy ConstantArrays in LLVMContext if they are not used.
bool getSemanticInterposition () const
Returns whether semantic interposition is to be respected.
void setSemanticInterposition (bool)
Set whether semantic interposition is to be respected.
bool getRtLibUseGOT () const
Returns true if PLT should be avoided for RTLib calls.
void setRtLibUseGOT ()
Set that PLT should be avoid for RTLib calls.
UWTableKind getUwtable () const
Get/set whether synthesized functions should get the uwtable attribute.
void setUwtable (UWTableKind Kind)
FramePointerKind getFramePointer () const
Get/set whether synthesized functions should get the "frame-pointer" attribute.
void setFramePointer (FramePointerKind Kind)
StringRef getStackProtectorGuard () const
Get/set what kind of stack protector guard to use.
void setStackProtectorGuard (StringRef Kind)
StringRef getStackProtectorGuardReg () const
Get/set which register to use as the stack protector guard register.
void setStackProtectorGuardReg (StringRef Reg)
StringRef getStackProtectorGuardSymbol () const
Get/set a symbol to use as the stack protector guard.
void setStackProtectorGuardSymbol (StringRef Symbol)
int getStackProtectorGuardOffset () const
Get/set what offset from the stack protector to use.
void setStackProtectorGuardOffset (int Offset)
unsigned getOverrideStackAlignment () const
Get/set the stack alignment overridden from the default.
void setOverrideStackAlignment (unsigned Align)
void setOwnedMemoryBuffer (std::unique_ptr< MemoryBuffer > MB)
Take ownership of the given memory buffer.
void setPartialSampleProfileRatio (const ModuleSummaryIndex &Index)
Set the partial sample profile ratio in the profile summary module flag, if applicable.
StringRef getDarwinTargetVariantTriple () const
Get the target variant triple which is a string describing a variant of the target host platform.
void setDarwinTargetVariantTriple (StringRef T)
Set the target variant triple which is a string describing a variant of the target host platform.
VersionTuple getDarwinTargetVariantSDKVersion () const
Get the target variant version build SDK version metadata.
void setDarwinTargetVariantSDKVersion (VersionTuple Version)
Set the target variant version build SDK version metadata.
Constructors
Module (StringRef ModuleID, LLVMContext &C)
The Module constructor.
~Module ()
The module destructor. This will dropAllReferences.
Module Level Accessors
const std::string & getModuleIdentifier () const
Get the module identifier which is, essentially, the name of the module.
unsigned getInstructionCount () const
Returns the number of non-debug IR instructions in the module.
const std::string & getSourceFileName () const
Get the module's original source file name.
StringRef getName () const
Get a short "name" for the module.
const std::string & getDataLayoutStr () const
Get the data layout string for the module's target platform.
const DataLayout & getDataLayout () const
Get the data layout for the module's target platform.
const std::string & getTargetTriple () const
Get the target triple which is a string describing the target host.
LLVMContext & getContext () const
Get the global data context.
const std::string & getModuleInlineAsm () const
Get any module-scope inline assembly blocks.
std::unique_ptr< RandomNumberGenerator > createRNG (const StringRef Name) const
Get a RandomNumberGenerator salted for use with this module.
bool shouldEmitInstrCountChangedRemark ()
Return true if size-info optimization remark is enabled, false otherwise.
Module Level Mutators
void setModuleIdentifier (StringRef ID)
Set the module identifier.
void setSourceFileName (StringRef Name)
Set the module's original source file name.
void setDataLayout (StringRef Desc)
Set the data layout.
void setDataLayout (const DataLayout &Other)
void setTargetTriple (StringRef T)
Set the target triple.
void setModuleInlineAsm (StringRef Asm)
Set the module-scope inline assembly blocks.
void appendModuleInlineAsm (StringRef Asm)
Append to the module-scope inline assembly blocks.
Generic Value Accessors
GlobalValue * getNamedValue (StringRef Name) const
Return the global value in the module with the specified name, of arbitrary type.
unsigned getNumNamedValues () const
Return the number of global values in the module.
unsigned getMDKindID (StringRef Name) const
Return a unique non-zero ID for the specified metadata kind.
void getMDKindNames (SmallVectorImpl< StringRef > &Result) const
Populate client supplied SmallVector with the name for custom metadata IDs registered in this LLVMContext.
void getOperandBundleTags (SmallVectorImpl< StringRef > &Result) const
Populate client supplied SmallVector with the bundle tags registered in this LLVMContext.
std::vector< StructType * > getIdentifiedStructTypes () const
std::string getUniqueIntrinsicName (StringRef BaseName, Intrinsic::ID Id, const FunctionType *Proto)
Return a unique name for an intrinsic whose mangling is based on an unnamed type.
Function Accessors
FunctionCallee getOrInsertFunction (StringRef Name, FunctionType *T, AttributeList AttributeList)
Look up the specified function in the module symbol table.
FunctionCallee getOrInsertFunction (StringRef Name, FunctionType *T)
template<typename... ArgsTy>
FunctionCallee getOrInsertFunction (StringRef Name, AttributeList AttributeList, Type *RetTy, ArgsTy... Args)
Look up the specified function in the module symbol table.
template<typename... ArgsTy>
FunctionCallee getOrInsertFunction (StringRef Name, Type *RetTy, ArgsTy... Args)
Same as above, but without the attributes.
template<typename... ArgsTy>
FunctionCallee getOrInsertFunction (StringRef Name, AttributeList AttributeList, FunctionType *Invalid, ArgsTy... Args)=delete
Function * getFunction (StringRef Name) const
Look up the specified function in the module symbol table.
Global Variable Accessors
GlobalVariable * getGlobalVariable (StringRef Name) const
Look up the specified global variable in the module symbol table.
GlobalVariable * getGlobalVariable (StringRef Name, bool AllowInternal) const
getGlobalVariable - Look up the specified global variable in the module symbol table.
GlobalVariable * getGlobalVariable (StringRef Name, bool AllowInternal=false)
const GlobalVariable * getNamedGlobal (StringRef Name) const
Return the global variable in the module with the specified name, of arbitrary type.
GlobalVariable * getNamedGlobal (StringRef Name)
Constant * getOrInsertGlobal (StringRef Name, Type *Ty, function_ref< GlobalVariable *()> CreateGlobalCallback)
Look up the specified global in the module symbol table.
Constant * getOrInsertGlobal (StringRef Name, Type *Ty)
Look up the specified global in the module symbol table.
Global Alias Accessors
GlobalAlias * getNamedAlias (StringRef Name) const
Return the global alias in the module with the specified name, of arbitrary type.
Global IFunc Accessors
GlobalIFunc * getNamedIFunc (StringRef Name) const
Return the global ifunc in the module with the specified name, of arbitrary type.
Named Metadata Accessors
NamedMDNode * getNamedMetadata (const Twine &Name) const
Return the first NamedMDNode in the module with the specified name.
NamedMDNode * getOrInsertNamedMetadata (StringRef Name)
Return the named MDNode in the module with the specified name.
void eraseNamedMetadata (NamedMDNode *NMD)
Remove the given NamedMDNode from this module and delete it.
Comdat Accessors
Comdat * getOrInsertComdat (StringRef Name)
Return the Comdat in the module with the specified name.
Module Flags Accessors
void getModuleFlagsMetadata (SmallVectorImpl< ModuleFlagEntry > &Flags) const
Returns the module flags in the provided vector.
Metadata * getModuleFlag (StringRef Key) const
Return the corresponding value if Key appears in module flags, otherwise return null.
NamedMDNode * getModuleFlagsMetadata () const
Returns the NamedMDNode in the module that represents module-level flags.
NamedMDNode * getOrInsertModuleFlagsMetadata ()
Returns the NamedMDNode in the module that represents module-level flags.
void addModuleFlag (ModFlagBehavior Behavior, StringRef Key, Metadata *Val)
Add a module-level flag to the module-level flags metadata.
void addModuleFlag (ModFlagBehavior Behavior, StringRef Key, Constant *Val)
void addModuleFlag (ModFlagBehavior Behavior, StringRef Key, uint32_t Val)
void addModuleFlag (MDNode *Node)
void setModuleFlag (ModFlagBehavior Behavior, StringRef Key, Metadata *Val)
Like addModuleFlag but replaces the old module flag if it already exists.
Materialization
void setMaterializer (GVMaterializer *GVM)
Sets the GVMaterializer to GVM.
GVMaterializer * getMaterializer () const
Retrieves the GVMaterializer, if any, for this Module.
bool isMaterialized () const
llvm::Error materialize (GlobalValue *GV)
Make sure the GlobalValue is fully read.
llvm::Error materializeAll ()
Make sure all GlobalValues in this Module are fully read and clear the Materializer.
llvm::Error materializeMetadata ()
Global Variable Iteration
global_iterator global_begin ()
const_global_iterator global_begin () const
global_iterator global_end ()
const_global_iterator global_end () const
size_t global_size () const
bool global_empty () const
iterator_range< global_iterator > globals ()
iterator_range< const_global_iterator > globals () const
Function Iteration
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_t size () const
bool empty () const
iterator_range< iterator > functions ()
iterator_range< const_iterator > functions () const
Alias Iteration
alias_iterator alias_begin ()
const_alias_iterator alias_begin () const
alias_iterator alias_end ()
const_alias_iterator alias_end () const
size_t alias_size () const
bool alias_empty () const
iterator_range< alias_iterator > aliases ()
iterator_range< const_alias_iterator > aliases () const
IFunc Iteration
ifunc_iterator ifunc_begin ()
const_ifunc_iterator ifunc_begin () const
ifunc_iterator ifunc_end ()
const_ifunc_iterator ifunc_end () const
size_t ifunc_size () const
bool ifunc_empty () const
iterator_range< ifunc_iterator > ifuncs ()
iterator_range< const_ifunc_iterator > ifuncs () const
Named Metadata Iteration
named_metadata_iterator named_metadata_begin ()
const_named_metadata_iterator named_metadata_begin () const
named_metadata_iterator named_metadata_end ()
const_named_metadata_iterator named_metadata_end () const
size_t named_metadata_size () const
bool named_metadata_empty () const
iterator_range< named_metadata_iterator > named_metadata ()
iterator_range< const_named_metadata_iterator > named_metadata () const
debug_compile_units_iterator debug_compile_units_begin () const
debug_compile_units_iterator debug_compile_units_end () const
iterator_range< debug_compile_units_iterator > debug_compile_units () const
Return an iterator for all DICompileUnits listed in this Module's llvm.dbg.cu named metadata node and aren't explicitly marked as NoDebug.
Utility functions for printing and dumping Module objects
void print (raw_ostream &OS, AssemblyAnnotationWriter *AAW, bool ShouldPreserveUseListOrder=false, bool IsForDebug=false) const
Print the module to an output stream with an optional AssemblyAnnotationWriter.
void dump () const
Dump the module to stderr (for debugging).
void dropAllReferences ()
This function causes all the subinstructions to "let go" of all references that they are maintaining.
Utility functions for querying Debug information.
unsigned getNumberRegisterParameters () const
Returns the Number of Register ParametersDwarf Version by checking module flags.
unsigned getDwarfVersion () const
Returns the Dwarf Version by checking module flags.
bool isDwarf64 () const
Returns the DWARF format by checking module flags.
unsigned getCodeViewFlag () const
Returns the CodeView Version by checking module flags.
Utility functions for querying and setting PIC level
PICLevel::Level getPICLevel () const
Returns the PIC level (small or large model)
void setPICLevel (PICLevel::Level PL)
Set the PIC level (small or large model)
Utility functions for querying and setting PIE level
PIELevel::Level getPIELevel () const
Returns the PIE level (small or large model)
void setPIELevel (PIELevel::Level PL)
Set the PIE level (small or large model)
Utility function for querying and setting code model
std::optional< CodeModel::Model > getCodeModel () const
Returns the code model (tiny, small, kernel, medium or large model)
void setCodeModel (CodeModel::Model CL)
Set the code model (tiny, small, kernel, medium or large)
Utility functions for querying and setting PGO summary
void setProfileSummary (Metadata *M, ProfileSummary::Kind Kind)
Attach profile summary metadata to this module.
Metadata * getProfileSummary (bool IsCS) const
Returns profile summary metadata.
Utility functions for querying and setting the build SDK version
void setSDKVersion (const VersionTuple &V)
Attach a build SDK version metadata to this module.
VersionTuple getSDKVersion () const
Get the build SDK version metadata.
Types And Enumerations
enum ModFlagBehavior {
Error = 1 , Warning = 2 , Require = 3 , Override = 4 ,
Append = 5 , AppendUnique = 6 , Max = 7 , Min = 8 ,
ModFlagBehaviorFirstVal = Error , ModFlagBehaviorLastVal = Min
}
This enumeration defines the supported behaviors of module flags.
using GlobalListType = SymbolTableList<GlobalVariable>
The type for the list of global variables.
using FunctionListType = SymbolTableList<Function>
The type for the list of functions.
using AliasListType = SymbolTableList<GlobalAlias>
The type for the list of aliases.
using IFuncListType = SymbolTableList<GlobalIFunc>
The type for the list of ifuncs.
using NamedMDListType = ilist<NamedMDNode>
The type for the list of named metadata.
using ComdatSymTabType = StringMap<Comdat>
The type of the comdat "symbol" table.
using NamedMDSymTabType = StringMap<NamedMDNode *>
The type for mapping names to named metadata.
using global_iterator = GlobalListType::iterator
The Global Variable iterator.
using const_global_iterator = GlobalListType::const_iterator
The Global Variable constant iterator.
using iterator = FunctionListType::iterator
The Function iterators.
using const_iterator = FunctionListType::const_iterator
The Function constant iterator.
using reverse_iterator = FunctionListType::reverse_iterator
The Function reverse iterator.
using const_reverse_iterator = FunctionListType::const_reverse_iterator
The Function constant reverse iterator.
using alias_iterator = AliasListType::iterator
The Global Alias iterators.
using const_alias_iterator = AliasListType::const_iterator
The Global Alias constant iterator.
using ifunc_iterator = IFuncListType::iterator
The Global IFunc iterators.
using const_ifunc_iterator = IFuncListType::const_iterator
The Global IFunc constant iterator.
using named_metadata_iterator = NamedMDListType::iterator
The named metadata iterators.
using const_named_metadata_iterator = NamedMDListType::const_iterator
The named metadata constant iterators.
static bool isValidModFlagBehavior (Metadata *MD, ModFlagBehavior &MFB)
Checks if Metadata represents a valid ModFlagBehavior, and stores the converted result in MFB.
static bool isValidModuleFlag (const MDNode &ModFlag, ModFlagBehavior &MFB, MDString *&Key, Metadata *&Val)
Check if the given module flag metadata represents a valid module flag, and store the flag behavior, the key string and the value metadata.
Convenience iterators
using global_object_iterator
using const_global_object_iterator
using global_value_iterator
using const_global_value_iterator
iterator_range< global_object_iterator > global_objects ()
iterator_range< const_global_object_iterator > global_objects () const
iterator_range< global_value_iterator > global_values ()
iterator_range< const_global_value_iterator > global_values () const
Member Variables
class Constant
Direct access to the globals list, functions list, and symbol table
static GlobalListType Module::* getSublistAccess (GlobalVariable *)
static FunctionListType Module::* getSublistAccess (Function *)
static AliasListType Module::* getSublistAccess (GlobalAlias *)
static IFuncListType Module::* getSublistAccess (GlobalIFunc *)
static NamedMDListType Module::* getSublistAccess (NamedMDNode *)
const GlobalListType & getGlobalList () const
Get the Module's list of global variables (constant).
GlobalListType & getGlobalList ()
Get the Module's list of global variables.
const FunctionListType & getFunctionList () const
Get the Module's list of functions (constant).
FunctionListType & getFunctionList ()
Get the Module's list of functions.
const AliasListType & getAliasList () const
Get the Module's list of aliases (constant).
AliasListType & getAliasList ()
Get the Module's list of aliases.
const IFuncListType & getIFuncList () const
Get the Module's list of ifuncs (constant).
IFuncListType & getIFuncList ()
Get the Module's list of ifuncs.
const NamedMDListType & getNamedMDList () const
Get the Module's list of named metadata (constant).
NamedMDListType & getNamedMDList ()
Get the Module's list of named metadata.
const ValueSymbolTable & getValueSymbolTable () const
Get the symbol table of global variable and function identifiers.
ValueSymbolTable & getValueSymbolTable ()
Get the Module's symbol table of global variable and function identifiers.
const ComdatSymTabType & getComdatSymbolTable () const
Get the Module's symbol table for COMDATs (constant).
ComdatSymTabType & getComdatSymbolTable ()
Get the Module's symbol table for COMDATs.
Detailed Description
A Module instance is used to store all the information related to an LLVM module.
Modules are the top level container of all other LLVM Intermediate Representation (IR) objects. Each module directly contains a list of globals variables, a list of functions, a list of libraries (or other modules) this module depends on, a symbol table, and various data about the target's characteristics.
A module maintains a GlobalList object that is used to hold all constant references to global variables in the module. When a global variable is destroyed, it should have no entries in the GlobalList. The main container class for the LLVM Intermediate Representation.
Definition at line 65 of file Module.h.
Member Typedef Documentation
alias_iterator
using llvm::Module::alias_iterator = AliasListType::iterator
The Global Alias iterators.
Definition at line 100 of file Module.h.
AliasListType
using llvm::Module::AliasListType = SymbolTableList<GlobalAlias>
The type for the list of aliases.
Definition at line 74 of file Module.h.
ComdatSymTabType
using llvm::Module::ComdatSymTabType = StringMap<Comdat>
The type of the comdat "symbol" table.
Definition at line 80 of file Module.h.
const_alias_iterator
using llvm::Module::const_alias_iterator = AliasListType::const_iterator
The Global Alias constant iterator.
Definition at line 102 of file Module.h.
const_global_iterator
using llvm::Module::const_global_iterator = GlobalListType::const_iterator
The Global Variable constant iterator.
Definition at line 87 of file Module.h.
const_global_object_iterator
using llvm::Module::const_global_object_iterator
Initial value:
      concat_iterator<const GlobalObject, const_iterator,
                      const_global_iterator>
Definition at line 685 of file Module.h.
const_global_value_iterator
using llvm::Module::const_global_value_iterator
Initial value:
      concat_iterator<const GlobalValue, const_iterator, const_global_iterator,
                      const_alias_iterator, const_ifunc_iterator>
Definition at line 695 of file Module.h.
const_ifunc_iterator
using llvm::Module::const_ifunc_iterator = IFuncListType::const_iterator
The Global IFunc constant iterator.
Definition at line 107 of file Module.h.
const_iterator
using llvm::Module::const_iterator = FunctionListType::const_iterator
The Function constant iterator.
Definition at line 92 of file Module.h.
const_named_metadata_iterator
using llvm::Module::const_named_metadata_iterator = NamedMDListType::const_iterator
The named metadata constant iterators.
Definition at line 112 of file Module.h.
const_reverse_iterator
using llvm::Module::const_reverse_iterator = FunctionListType::const_reverse_iterator
The Function constant reverse iterator.
Definition at line 97 of file Module.h.
FunctionListType
using llvm::Module::FunctionListType = SymbolTableList<Function>
The type for the list of functions.
Definition at line 72 of file Module.h.
global_iterator
using llvm::Module::global_iterator = GlobalListType::iterator
The Global Variable iterator.
Definition at line 85 of file Module.h.
global_object_iterator
using llvm::Module::global_object_iterator
Initial value:
      concat_iterator<GlobalObject, iterator, global_iterator>
Definition at line 683 of file Module.h.
global_value_iterator
using llvm::Module::global_value_iterator
Initial value:
      concat_iterator<GlobalValue, iterator, global_iterator, alias_iterator,
                      ifunc_iterator>
Definition at line 692 of file Module.h.
GlobalListType
using llvm::Module::GlobalListType = SymbolTableList<GlobalVariable>
The type for the list of global variables.
Definition at line 70 of file Module.h.
ifunc_iterator
using llvm::Module::ifunc_iterator = IFuncListType::iterator
The Global IFunc iterators.
Definition at line 105 of file Module.h.
IFuncListType
using llvm::Module::IFuncListType = SymbolTableList<GlobalIFunc>
The type for the list of ifuncs.
Definition at line 76 of file Module.h.
iterator
using llvm::Module::iterator = FunctionListType::iterator
The Function iterators.
Definition at line 90 of file Module.h.
named_metadata_iterator
using llvm::Module::named_metadata_iterator = NamedMDListType::iterator
The named metadata iterators.
Definition at line 110 of file Module.h.
NamedMDListType
using llvm::Module::NamedMDListType = ilist<NamedMDNode>
The type for the list of named metadata.
Definition at line 78 of file Module.h.
NamedMDSymTabType
using llvm::Module::NamedMDSymTabType = StringMap<NamedMDNode *>
The type for mapping names to named metadata.
Definition at line 82 of file Module.h.
reverse_iterator
using llvm::Module::reverse_iterator = FunctionListType::reverse_iterator
The Function reverse iterator.
Definition at line 95 of file Module.h.
Member Enumeration Documentation
ModFlagBehavior
enum llvm::Module::ModFlagBehavior
This enumeration defines the supported behaviors of module flags.
Enumerator
Error
Emits an error if two values disagree, otherwise the resulting value is that of the operands.
Warning
Emits a warning if two values disagree.
The result value will be the operand for the flag from the first module being linked.
Require
Adds a requirement that another module flag be present and have a specified value after linking is performed.
The value must be a metadata pair, where the first element of the pair is the ID of the module flag to be restricted, and the second element of the pair is the value the module flag should be restricted to. This behavior can be used to restrict the allowable results (via triggering of an error) of linking IDs with the Override behavior.
Override
Uses the specified value, regardless of the behavior or value of the other module.
If both modules specify Override, but the values differ, an error will be emitted.
Append
Appends the two values, which are required to be metadata nodes.
AppendUnique
Appends the two values, which are required to be metadata nodes.
However, duplicate entries in the second list are dropped during the append operation.
Max
Takes the max of the two values, which are required to be integers.
Min
Takes the min of the two values, which are required to be integers.
ModFlagBehaviorFirstVal
ModFlagBehaviorLastVal
Definition at line 115 of file Module.h.
Constructor & Destructor Documentation
Module()
Module::Module (StringRef ModuleID, LLVMContext & C) explicit
The Module constructor.
Note that there is no default constructor. You must provide a name for the module upon construction.
Definition at line 72 of file Module.cpp.
~Module()
Module::~Module ()
The module destructor. This will dropAllReferences.
Definition at line 78 of file Module.cpp.
References llvm::iplist_impl< IntrusiveListT, TraitsT >::clear(), and dropAllReferences().
Member Function Documentation
addModuleFlag() [1/4]
void Module::addModuleFlag (MDNode * Node)
Definition at line 366 of file Module.cpp.
References llvm::NamedMDNode::addOperand(), assert(), and getOrInsertModuleFlagsMetadata().
addModuleFlag() [2/4]
void Module::addModuleFlag (ModFlagBehavior Behavior, StringRef Key, Constant * Val)
Definition at line 357 of file Module.cpp.
References addModuleFlag(), and llvm::ConstantAsMetadata::get().
addModuleFlag() [3/4]
void Module::addModuleFlag (ModFlagBehavior Behavior, StringRef Key, Metadata * Val)
Add a module-level flag to the module-level flags metadata.
addModuleFlag - Add a module-level flag to the module-level flags metadata.
It will create the module-level flags named metadata if it doesn't already exist.
Definition at line 349 of file Module.cpp.
References llvm::NamedMDNode::addOperand(), llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MDString::get(), llvm::ConstantInt::get(), llvm::Type::getInt32Ty(), getOrInsertModuleFlagsMetadata(), and Int32Ty.
Referenced by addModuleFlag(), addModuleFlag(), setCodeModel(), setDarwinTargetVariantTriple(), setFramePointer(), setModuleFlag(), setOverrideStackAlignment(), setPICLevel(), setPIELevel(), setRtLibUseGOT(), setSemanticInterposition(), setStackProtectorGuard(), setStackProtectorGuardOffset(), setStackProtectorGuardReg(), setStackProtectorGuardSymbol(), and setUwtable().
addModuleFlag() [4/4]
void Module::addModuleFlag (ModFlagBehavior Behavior, StringRef Key, uint32_t Val)
Definition at line 361 of file Module.cpp.
References addModuleFlag(), llvm::ConstantInt::get(), llvm::Type::getInt32Ty(), and Int32Ty.
alias_begin() [1/2]
alias_iterator llvm::Module::alias_begin () inline
Definition at line 647 of file Module.h.
Referenced by LLVMGetPreviousGlobalAlias().
alias_begin() [2/2]
const_alias_iterator llvm::Module::alias_begin () const inline
Definition at line 648 of file Module.h.
alias_empty()
bool llvm::Module::alias_empty () const inline
Definition at line 652 of file Module.h.
alias_end() [1/2]
alias_iterator llvm::Module::alias_end () inline
Definition at line 649 of file Module.h.
Referenced by LLVMGetNextGlobalAlias().
alias_end() [2/2]
const_alias_iterator llvm::Module::alias_end () const inline
Definition at line 650 of file Module.h.
alias_size()
size_t llvm::Module::alias_size () const inline
Definition at line 651 of file Module.h.
aliases() [1/2]
iterator_range< alias_iterator > llvm::Module::aliases () inline
Definition at line 654 of file Module.h.
References llvm::make_range().
Referenced by dropAllReferences(), global_values(), global_values(), and llvm::thinLTOFinalizeInModule().
aliases() [2/2]
iterator_range< const_alias_iterator > llvm::Module::aliases () const inline
Definition at line 657 of file Module.h.
References llvm::make_range().
appendModuleInlineAsm()
void llvm::Module::appendModuleInlineAsm (StringRef Asm) inline
Append to the module-scope inline assembly blocks.
A trailing newline is added if the input doesn't have one.
Definition at line 313 of file Module.h.
begin() [1/2]
iterator llvm::Module::begin () inline
Definition at line 625 of file Module.h.
Referenced by llvm::FunctionAnalysisManagerCGSCCProxy::run(), llvm::CoroSplitPass::run(), and llvm::OpenMPOptCGSCCPass::run().
begin() [2/2]
const_iterator llvm::Module::begin () const inline
Definition at line 626 of file Module.h.
createRNG()
std::unique_ptr< RandomNumberGenerator > Module::createRNG (const StringRef Name) const
Get a RandomNumberGenerator salted for use with this module.
The RNG can be seeded via -rng-seed=<uint64> and is salted with the ModuleID and the provided pass salt. The returned RNG should not be shared across threads or passes.
A unique RNG per pass ensures a reproducible random stream even when other randomness consuming passes are added or removed. In addition, the random stream will be reproducible across LLVM versions when the pass does not change.
Definition at line 88 of file Module.cpp.
References llvm::sys::path::filename(), getModuleIdentifier(), and Name.
debug_compile_units()
iterator_range< debug_compile_units_iterator > llvm::Module::debug_compile_units () const inline
Return an iterator for all DICompileUnits listed in this Module's llvm.dbg.cu named metadata node and aren't explicitly marked as NoDebug.
Definition at line 782 of file Module.h.
References llvm::make_range().
debug_compile_units_begin()
debug_compile_units_iterator llvm::Module::debug_compile_units_begin () const inline
Definition at line 769 of file Module.h.
debug_compile_units_end()
debug_compile_units_iterator llvm::Module::debug_compile_units_end () const inline
Definition at line 774 of file Module.h.
dropAllReferences()
void Module::dropAllReferences ()
This function causes all the subinstructions to "let go" of all references that they are maintaining.
This allows one to 'delete' a whole class at a time, even though there may be circular references... first all references are dropped, and all use counts go to zero. Then everything is delete'd for real. Note that no operations are valid on an object that has "dropped all references", except operator delete.
Definition at line 534 of file Module.cpp.
References aliases(), F, globals(), and ifuncs().
Referenced by ~Module().
dropTriviallyDeadConstantArrays()
void Module::dropTriviallyDeadConstantArrays ()
Destroy ConstantArrays in LLVMContext if they are not used.
ConstantArrays constructed during linking can cause quadratic memory explosion. Releasing all unused constants can cause a 20% LTO compile-time slowdown for a large application.
NOTE: Constants are currently owned by LLVMContext. This can then only be called where all uses of the LLVMContext are understood.
Definition at line 169 of file LLVMContextImpl.cpp.
Referenced by llvm::IRMover::move().
dump()
LLVM_DUMP_METHOD void Module::dump () const
Dump the module to stderr (for debugging).
Definition at line 4946 of file AsmWriter.cpp.
References llvm::dbgs(), and print().
empty()
bool llvm::Module::empty () const inline
Definition at line 634 of file Module.h.
end() [1/2]
iterator llvm::Module::end () inline
Definition at line 627 of file Module.h.
end() [2/2]
const_iterator llvm::Module::end () const inline
Definition at line 628 of file Module.h.
eraseNamedMetadata()
void Module::eraseNamedMetadata (NamedMDNode * NMD)
Remove the given NamedMDNode from this module and delete it.
eraseNamedMetadata - Remove the given NamedMDNode from this module and delete it.
Definition at line 272 of file Module.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::erase(), and llvm::ilist_node_impl< OptionsT >::getIterator().
Referenced by llvm::NamedMDNode::eraseFromParent().
functions() [1/2]
iterator_range< iterator > llvm::Module::functions () inline
Definition at line 636 of file Module.h.
References llvm::make_range().
Referenced by global_objects(), global_objects(), global_values(), and global_values().
functions() [2/2]
iterator_range< const_iterator > llvm::Module::functions () const inline
Definition at line 639 of file Module.h.
References llvm::make_range().
getAliasList() [1/2]
AliasListType & llvm::Module::getAliasList () inline
Get the Module's list of aliases.
Definition at line 569 of file Module.h.
getAliasList() [2/2]
const AliasListType & llvm::Module::getAliasList () const inline
Get the Module's list of aliases (constant).
Definition at line 567 of file Module.h.
Referenced by llvm::GlobalAlias::eraseFromParent(), and llvm::GlobalAlias::removeFromParent().
getCodeModel()
std::optional< CodeModel::Model > Module::getCodeModel () const
Returns the code model (tiny, small, kernel, medium or large model)
Definition at line 618 of file Module.cpp.
References getModuleFlag().
getCodeViewFlag()
unsigned Module::getCodeViewFlag () const
Returns the CodeView Version by checking module flags.
Returns zero if not present in module.
Definition at line 568 of file Module.cpp.
References getModuleFlag().
Referenced by llvm::X86FrameLowering::emitPrologue(), and llvm::X86AsmPrinter::runOnMachineFunction().
getComdatSymbolTable() [1/2]
ComdatSymTabType & llvm::Module::getComdatSymbolTable () inline
Get the Module's symbol table for COMDATs.
Definition at line 601 of file Module.h.
getComdatSymbolTable() [2/2]
const ComdatSymTabType & llvm::Module::getComdatSymbolTable () const inline
Get the Module's symbol table for COMDATs (constant).
Definition at line 599 of file Module.h.
getContext()
LLVMContext & llvm::Module::getContext () const inline
Get the global data context.
Returns
LLVMContext - a container for LLVM's global information
Definition at line 262 of file Module.h.
References Context.
Referenced by llvm::AMDGPUMachineModuleInfo::AMDGPUMachineModuleInfo(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), llvm::OpenMPIRBuilder::createReductions(), llvm::MachineInstr::emitError(), emitErrorMsg(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), EmitInlineAsmStr(), llvm::SinkInstructionStrategy::mutate(), llvm::parseConstantValue(), llvm::parseTypeAtBeginning(), setDarwinTargetVariantTriple(), setPartialSampleProfileRatio(), setStackProtectorGuard(), setStackProtectorGuardReg(), setStackProtectorGuardSymbol(), and SwitchToLookupTable().
getDarwinTargetVariantSDKVersion()
VersionTuple Module::getDarwinTargetVariantSDKVersion () const
Get the target variant version build SDK version metadata.
An empty version is returned if no such metadata is attached.
Definition at line 846 of file Module.cpp.
References getModuleFlag(), and getSDKVersionMD().
getDarwinTargetVariantTriple()
StringRef Module::getDarwinTargetVariantTriple () const
Get the target variant triple which is a string describing a variant of the target host platform.
For example, Mac Catalyst can be a variant target triple for a macOS target.
Returns
a string containing the target variant triple.
Definition at line 835 of file Module.cpp.
References getModuleFlag().
getDataLayout()
const DataLayout & Module::getDataLayout () const
Get the data layout for the module's target platform.
Definition at line 398 of file Module.cpp.
Referenced by AddAlignmentAssumptions(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), buildOverlapMapAndRecordDeclares(), canFoldTermCondOfLoop(), CanProveNotTakenFirstIteration(), llvm::CloneAndPruneIntoFromInst(), llvm::FunctionComparator::cmpTypes(), collectFrameAlloca(), computeAllocaDefaultAlign(), computeLoadStoreDefaultAlign(), computeRecurrenceType(), computeUnlikelySuccessors(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::IRBuilderBase::CreateAlignedLoad(), llvm::IRBuilderBase::CreateAlignedStore(), llvm::IRBuilderBase::CreateAlloca(), llvm::IRBuilderBase::CreateAlloca(), llvm::IRBuilderBase::CreateAtomicCmpXchg(), llvm::IRBuilderBase::CreateAtomicRMW(), llvm::OpenMPIRBuilder::createReductions(), createWrapper(), llvm::DependenceInfo::depends(), llvm::AsmPrinter::emitAlignment(), llvm::AsmPrinter::emitGlobalVariable(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::emitLinkerFlagsForGlobalCOFF(), llvm::LoongArchTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::RISCVTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::AsmPrinter::emitSpecialLLVMGlobal(), llvm::expandAtomicRMWToCmpXchg(), FindLoopCounter(), findPHIToPartitionLoops(), llvm::MemoryLocation::get(), getAlign(), llvm::memtag::getAllocaSizeInBytes(), llvm::getAllocSize(), getAtomicOpSize(), llvm::getConstantDataArrayInfo(), llvm::ScalarEvolution::getDataLayout(), llvm::AsmPrinter::getDataLayout(), llvm::MachineIRBuilder::getDataLayout(), llvm::MachineFunction::getDataLayout(), getELFSectionNameForGlobal(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::VNCoercion::getLoadLoadClobberFullWidthSize(), llvm::ExecutionEngine::getMangledName(), llvm::Mangler::getNameWithPrefix(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::DependenceInfo::getSplitIteration(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::FunctionLoweringInfo::getValueFromVirtualReg(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), insertSpills(), instCombineLD1GatherIndex(), instCombineST1ScatterIndex(), llvm::orc::IRMaterializationUnit::IRMaterializationUnit(), llvm::isDereferenceableAndAlignedInLoop(), llvm::InductionDescriptor::isInductionPHI(), llvm::GCNTTIImpl::isInlineAsmSourceOfDivergence(), isLoadInvariantInLoop(), llvm::SystemZSubtarget::isPC32DBLSymbol(), isPointerValueDeadOnEntryToFunction(), isSafePHIToSpeculate(), llvm::isSafeToSpeculativelyExecuteWithOpcode(), IsSmallObject(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), maybePrintCallAddrSpace(), NegateValue(), peelToTurnInvariantLoadsDerefencebale(), performGlobalAddressCombine(), llvm::JumpThreadingPass::processBlock(), llvm::JumpThreadingPass::processImpliedCondition(), processInternalGlobal(), llvm::promoteLoopAccessesToScalars(), llvm::ReadByteArrayFromGlobal(), ReduceLoopStrength(), llvm::LoopIdiomRecognizePass::run(), llvm::LoopRotatePass::run(), llvm::ConstantHoistingPass::runImpl(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::FunctionLoweringInfo::set(), llvm::simplifyCFG(), llvm::SimplifyInstructionsInBlock(), llvm::simplifyLoopAfterUnroll(), simplifyLoopInst(), simplifyOneLoop(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), llvm::simplifyRetainedKnowledge(), simplifyX86immShift(), simplifyX86varShift(), splitGlobal(), llvm::splitLoopBound(), llvm::JumpThreadingPass::threadGuard(), TryToShrinkGlobalToBoolean(), llvm::UnrollRuntimeLoopRemainder(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::LoopVersioning::versionLoop(), and visitIVCast().
getDataLayoutStr()
const std::string & llvm::Module::getDataLayoutStr () const inline
Get the data layout string for the module's target platform.
This is equivalent to getDataLayout()->getStringRepresentation().
Definition at line 249 of file Module.h.
References DL.
getDwarfVersion()
unsigned Module::getDwarfVersion () const
Returns the Dwarf Version by checking module flags.
Definition at line 556 of file Module.cpp.
References getModuleFlag().
Referenced by llvm::DwarfDebug::DwarfDebug().
getFramePointer()
FramePointerKind Module::getFramePointer () const
Get/set whether synthesized functions should get the "frame-pointer" attribute.
Definition at line 685 of file Module.cpp.
References getModuleFlag().
getFunction()
Function * Module::getFunction (StringRef Name) const
Look up the specified function in the module symbol table.
If it does not exist, return null.
Definition at line 175 of file Module.cpp.
References getNamedValue(), and Name.
Referenced by collectUnswitchCandidates(), llvm::MipsTargetLowering::getOpndList(), llvm::MipsCCState::getSpecialCallingConvForCallee(), llvm::SelectionDAG::getSymbolFunctionGlobalAddress(), and llvm::VFABI::getVectorVariantNames().
getFunctionList() [1/2]
FunctionListType & llvm::Module::getFunctionList () inline
Get the Module's list of functions.
Definition at line 561 of file Module.h.
getFunctionList() [2/2]
const FunctionListType & llvm::Module::getFunctionList () const inline
Get the Module's list of functions (constant).
Definition at line 559 of file Module.h.
Referenced by llvm::Function::eraseFromParent(), and llvm::Function::removeFromParent().
getGlobalList() [1/2]
GlobalListType & llvm::Module::getGlobalList () inline
Get the Module's list of global variables.
Definition at line 552 of file Module.h.
getGlobalList() [2/2]
const GlobalListType & llvm::Module::getGlobalList () const inline
Get the Module's list of global variables (constant).
Definition at line 550 of file Module.h.
Referenced by llvm::GlobalVariable::eraseFromParent(), llvm::GlobalVariable::GlobalVariable(), OptimizeGlobalAddressOfAllocation(), llvm::GlobalVariable::removeFromParent(), and TryToShrinkGlobalToBoolean().
getGlobalVariable() [1/3]
GlobalVariable * llvm::Module::getGlobalVariable (StringRef Name) const inline
Look up the specified global variable in the module symbol table.
If it does not exist, return null. If AllowInternal is set to true, this function will return types that have InternalLinkage. By default, these types are not returned.
Definition at line 414 of file Module.h.
References getGlobalVariable(), and Name.
getGlobalVariable() [2/3]
GlobalVariable * Module::getGlobalVariable (StringRef Name, bool AllowLocal) const
getGlobalVariable - Look up the specified global variable in the module symbol table.
If it does not exist, return null. The type argument should be the underlying type of the global, i.e., it should not have the top-level PointerType, which represents the address of the global. If AllowLocal is set to true, this function will return types that have an local. By default, these types are not returned.
Definition at line 190 of file Module.cpp.
References getNamedValue(), and Name.
getGlobalVariable() [3/3]
GlobalVariable * llvm::Module::getGlobalVariable (StringRef Name, bool AllowInternal = false) inline
Definition at line 420 of file Module.h.
References getGlobalVariable(), and Name.
getIdentifiedStructTypes()
std::vector< StructType * > Module::getIdentifiedStructTypes () const
Definition at line 463 of file Module.cpp.
getIFuncList() [1/2]
IFuncListType & llvm::Module::getIFuncList () inline
Get the Module's list of ifuncs.
Definition at line 578 of file Module.h.
getIFuncList() [2/2]
const IFuncListType & llvm::Module::getIFuncList () const inline
Get the Module's list of ifuncs (constant).
Definition at line 576 of file Module.h.
Referenced by llvm::GlobalIFunc::eraseFromParent(), and llvm::GlobalIFunc::removeFromParent().
getInstructionCount()
unsigned Module::getInstructionCount () const
Returns the number of non-debug IR instructions in the module.
This is equivalent to the sum of the IR instruction counts of each function contained in the module.
Definition at line 575 of file Module.cpp.
References F.
getMaterializer()
GVMaterializer * llvm::Module::getMaterializer () const inline
Retrieves the GVMaterializer, if any, for this Module.
Definition at line 533 of file Module.h.
getMDKindID()
unsigned Module::getMDKindID (StringRef Name) const
Return a unique non-zero ID for the specified metadata kind.
getMDKindID - Return a unique non-zero ID for the specified metadata kind.
This ID is uniqued across modules in the current LLVMContext.
Definition at line 120 of file Module.cpp.
References Name.
getMDKindNames()
void Module::getMDKindNames (SmallVectorImpl< StringRef > & Result) const
Populate client supplied SmallVector with the name for custom metadata IDs registered in this LLVMContext.
getMDKindNames - Populate client supplied SmallVector with the name for custom metadata IDs registered in this LLVMContext.
ID #0 is not used, so it is filled in as an empty string.
Definition at line 127 of file Module.cpp.
getModuleFlag()
Metadata * Module::getModuleFlag (StringRef Key) const
Return the corresponding value if Key appears in module flags, otherwise return null.
Definition at line 322 of file Module.cpp.
References getModuleFlagsMetadata().
Referenced by getCodeModel(), getCodeViewFlag(), getDarwinTargetVariantSDKVersion(), getDarwinTargetVariantTriple(), getDwarfVersion(), getFramePointer(), getNumberRegisterParameters(), getOverrideStackAlignment(), getPICLevel(), getPIELevel(), getProfileSummary(), getRtLibUseGOT(), getSDKVersion(), getSemanticInterposition(), getStackProtectorGuard(), getStackProtectorGuardOffset(), getStackProtectorGuardReg(), getStackProtectorGuardSymbol(), getUwtable(), isDwarf64(), and llvm::X86AsmPrinter::runOnMachineFunction().
getModuleFlagsMetadata() [1/2]
NamedMDNode * Module::getModuleFlagsMetadata () const
Returns the NamedMDNode in the module that represents module-level flags.
getModuleFlagsMetadata - Returns the NamedMDNode in the module that represents module-level flags.
This method returns null if there are no module-level flags.
Definition at line 335 of file Module.cpp.
References getNamedMetadata().
Referenced by getModuleFlag(), and getModuleFlagsMetadata().
getModuleFlagsMetadata() [2/2]
void Module::getModuleFlagsMetadata (SmallVectorImpl< ModuleFlagEntry > & Flags) const
Returns the module flags in the provided vector.
getModuleFlagsMetadata - Returns the module flags in the provided vector.
Definition at line 303 of file Module.cpp.
References getModuleFlagsMetadata(), and isValidModuleFlag().
getModuleIdentifier()
const std::string & llvm::Module::getModuleIdentifier () const inline
Get the module identifier which is, essentially, the name of the module.
Returns
the module identifier as a string
Definition at line 228 of file Module.h.
Referenced by createRNG(), llvm::ThinLTOCodeGenerator::crossModuleImport(), llvm::ThinLTOCodeGenerator::emitImports(), llvm::ThinLTOCodeGenerator::gatherImportedSummariesForModule(), getDebugLocString(), llvm::ThinLTOCodeGenerator::internalize(), llvm::DiagnosticInfoIgnoringInvalidDebugMetadata::print(), and llvm::ThinLTOCodeGenerator::promote().
getModuleInlineAsm()
const std::string & llvm::Module::getModuleInlineAsm () const inline
Get any module-scope inline assembly blocks.
Returns
a string containing the module-scope inline assembly blocks.
Definition at line 266 of file Module.h.
getName()
StringRef llvm::Module::getName () const inline
Get a short "name" for the module.
This is useful for debugging or logging. It is essentially a convenience wrapper around getModuleIdentifier().
Definition at line 245 of file Module.h.
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), llvm::AsmPrinter::emitStackUsage(), and llvm::ThinLTOCodeGenerator::run().
getNamedAlias()
GlobalAlias * Module::getNamedAlias (StringRef Name) const
Return the global alias in the module with the specified name, of arbitrary type.
This method returns null if a global with the specified name is not found.
Definition at line 240 of file Module.cpp.
References getNamedValue(), and Name.
getNamedGlobal() [1/2]
GlobalVariable * llvm::Module::getNamedGlobal (StringRef Name) inline
Definition at line 432 of file Module.h.
References Name.
getNamedGlobal() [2/2]
const GlobalVariable * llvm::Module::getNamedGlobal (StringRef Name) const inline
Return the global variable in the module with the specified name, of arbitrary type.
This method returns null if a global with the specified name is not found.
Definition at line 429 of file Module.h.
References getGlobalVariable(), and Name.
getNamedIFunc()
GlobalIFunc * Module::getNamedIFunc (StringRef Name) const
Return the global ifunc in the module with the specified name, of arbitrary type.
This method returns null if a global with the specified name is not found.
Definition at line 244 of file Module.cpp.
References getNamedValue(), and Name.
getNamedMDList() [1/2]
NamedMDListType & llvm::Module::getNamedMDList () inline
Get the Module's list of named metadata.
Definition at line 587 of file Module.h.
getNamedMDList() [2/2]
const NamedMDListType & llvm::Module::getNamedMDList () const inline
Get the Module's list of named metadata (constant).
Definition at line 585 of file Module.h.
getNamedMetadata()
NamedMDNode * Module::getNamedMetadata (const Twine & Name) const
Return the first NamedMDNode in the module with the specified name.
getNamedMetadata - Return the first NamedMDNode in the module with the specified name.
This method returns null if a NamedMDNode with the specified name is not found.
Definition at line 251 of file Module.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::lookup(), and Name.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), and getModuleFlagsMetadata().
getNamedValue()
GlobalValue * Module::getNamedValue (StringRef Name) const
Return the global value in the module with the specified name, of arbitrary type.
getNamedValue - Return the first global value in the module with the specified name, of arbitrary type.
This method returns null if a global with the specified name is not found.
Definition at line 110 of file Module.cpp.
References getValueSymbolTable(), lookup(), and Name.
Referenced by getComdatGVForCOFF(), getFunction(), getGlobalVariable(), getNamedAlias(), getNamedIFunc(), getOrInsertFunction(), getOrInsertGlobal(), and getUniqueIntrinsicName().
getNumberRegisterParameters()
unsigned Module::getNumberRegisterParameters () const
Returns the Number of Register ParametersDwarf Version by checking module flags.
Definition at line 548 of file Module.cpp.
References getModuleFlag().
Referenced by markRegisterParameterAttributes().
getNumNamedValues()
unsigned Module::getNumNamedValues () const
Return the number of global values in the module.
Definition at line 114 of file Module.cpp.
References getValueSymbolTable(), and llvm::ValueSymbolTable::size().
getOperandBundleTags()
void Module::getOperandBundleTags (SmallVectorImpl< StringRef > & Result) const
Populate client supplied SmallVector with the bundle tags registered in this LLVMContext.
The bundle tags are ordered by increasing bundle IDs.
See also
LLVMContext::getOperandBundleTagID
Definition at line 131 of file Module.cpp.
getOrInsertComdat()
Comdat * Module::getOrInsertComdat (StringRef Name)
Return the Comdat in the module with the specified name.
It is created if it didn't already exist.
Definition at line 582 of file Module.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::insert(), and Name.
getOrInsertFunction() [1/5]
template<typename... ArgsTy> FunctionCallee llvm::Module::getOrInsertFunction (StringRef Name, AttributeList AttributeList, FunctionType * Invalid, ArgsTy... Args) delete
getOrInsertFunction() [2/5]
template<typename... ArgsTy> FunctionCallee llvm::Module::getOrInsertFunction (StringRef Name, AttributeList AttributeList, Type * RetTy, ArgsTy... Args) inline
Look up the specified function in the module symbol table.
If it does not exist, add a prototype for the function and return it. This function guarantees to return a constant of pointer to the specified function type or a ConstantExpr BitCast of that type if the named function has a different type. This version of the method takes a list of function arguments, which makes it easier for clients to use.
Definition at line 380 of file Module.h.
References Name, and RetTy.
getOrInsertFunction() [3/5]
FunctionCallee Module::getOrInsertFunction (StringRef Name, FunctionType * T)
Definition at line 168 of file Module.cpp.
References getOrInsertFunction(), and Name.
getOrInsertFunction() [4/5]
FunctionCallee Module::getOrInsertFunction (StringRef Name, FunctionType * T, AttributeList AttributeList)
Look up the specified function in the module symbol table.
Four possibilities:
If it does not exist, add a prototype for the function and return it.
Otherwise, if the existing function has the correct prototype, return the existing function.
Finally, the function exists but has the wrong prototype: return the function with a constantexpr cast to the right prototype.
In all cases, the returned value is a FunctionCallee wrapper around the 'FunctionType T' passed in, as well as a 'Value' either of the Function or the bitcast to the function.
Note: For library calls getOrInsertLibFunc() should be used instead.
Definition at line 144 of file Module.cpp.
References llvm::Function::Create(), llvm::GlobalValue::ExternalLinkage, F, llvm::PointerType::get(), llvm::ConstantExpr::getBitCast(), getNamedValue(), llvm::DataLayout::getProgramAddressSpace(), Name, and llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back().
Referenced by getOrInsertFunction().
getOrInsertFunction() [5/5]
template<typename... ArgsTy> FunctionCallee llvm::Module::getOrInsertFunction (StringRef Name, Type * RetTy, ArgsTy... Args) inline
Same as above, but without the attributes.
Definition at line 391 of file Module.h.
References Name, and RetTy.
getOrInsertGlobal() [1/2]
Constant * Module::getOrInsertGlobal (StringRef Name, Type * Ty)
Look up the specified global in the module symbol table.
If required, this overload constructs the global variable using its constructor's defaults.
Definition at line 226 of file Module.cpp.
References llvm::GlobalValue::ExternalLinkage, getOrInsertGlobal(), and Name.
getOrInsertGlobal() [2/2]
Constant * Module::getOrInsertGlobal (StringRef Name, Type * Ty, function_ref< GlobalVariable *()> CreateGlobalCallback)
Look up the specified global in the module symbol table.
getOrInsertGlobal - Look up the specified global in the module symbol table.
If it does not exist, invoke a callback to create a declaration of the global and return it. The global is constantexpr casted to the expected type if necessary.
If it does not exist, add a declaration of the global and return it.
Else, the global exists but has the wrong type: return the function with a constantexpr cast to the right type.
Finally, if the existing global is the correct declaration, return the existing global.
Definition at line 205 of file Module.cpp.
References assert(), llvm::PointerType::get(), llvm::ConstantExpr::getBitCast(), getNamedValue(), llvm::GlobalValue::getType(), and Name.
Referenced by getOrInsertGlobal().
getOrInsertModuleFlagsMetadata()
NamedMDNode * Module::getOrInsertModuleFlagsMetadata ()
Returns the NamedMDNode in the module that represents module-level flags.
getOrInsertModuleFlagsMetadata - Returns the NamedMDNode in the module that represents module-level flags.
If module-level flags aren't found, it creates the named metadata that contains them.
Definition at line 342 of file Module.cpp.
References getOrInsertNamedMetadata().
Referenced by addModuleFlag(), addModuleFlag(), and setModuleFlag().
getOrInsertNamedMetadata()
NamedMDNode * Module::getOrInsertNamedMetadata (StringRef Name)
Return the named MDNode in the module with the specified name.
getOrInsertNamedMetadata - Return the first named MDNode in the module with the specified name.
This method returns a new NamedMDNode if a NamedMDNode with the specified name is not found.
Definition at line 260 of file Module.cpp.
References Name.
Referenced by getOrInsertModuleFlagsMetadata().
getOverrideStackAlignment()
unsigned Module::getOverrideStackAlignment () const
Get/set the stack alignment overridden from the default.
Definition at line 742 of file Module.cpp.
References getModuleFlag().
getPICLevel()
PICLevel::Level Module::getPICLevel () const
Returns the PIC level (small or large model)
Definition at line 588 of file Module.cpp.
References getModuleFlag(), and llvm::PICLevel::NotPIC.
getPIELevel()
PIELevel::Level Module::getPIELevel () const
Returns the PIE level (small or large model)
Definition at line 604 of file Module.cpp.
References llvm::PIELevel::Default, and getModuleFlag().
Referenced by llvm::TargetMachine::getTLSModel().
getProfileSummary()
Metadata * Module::getProfileSummary (bool IsCS) const
Returns profile summary metadata.
When IsCS is true, use the context sensitive profile summary.
Definition at line 643 of file Module.cpp.
References getModuleFlag().
Referenced by setPartialSampleProfileRatio().
getRtLibUseGOT()
bool Module::getRtLibUseGOT () const
Returns true if PLT should be avoided for RTLib calls.
Definition at line 666 of file Module.cpp.
References getModuleFlag().
getSDKVersion()
VersionTuple Module::getSDKVersion () const
Get the build SDK version metadata.
An empty version is returned if no such metadata is attached.
Definition at line 796 of file Module.cpp.
References getModuleFlag(), and getSDKVersionMD().
getSemanticInterposition()
bool Module::getSemanticInterposition () const
Returns whether semantic interposition is to be respected.
Definition at line 648 of file Module.cpp.
References getModuleFlag().
Referenced by llvm::GlobalValue::isInterposable().
getSourceFileName()
const std::string & llvm::Module::getSourceFileName () const inline
Get the module's original source file name.
When compiling from bitcode, this is taken from a bitcode record where it was recorded. For other compiles it is the same as the ModuleID, which would contain the source file name.
Definition at line 239 of file Module.h.
Referenced by selectExplicitSectionGlobal(), and llvm::thinLTOInternalizeModule().
getStackProtectorGuard()
StringRef Module::getStackProtectorGuard () const
Get/set what kind of stack protector guard to use.
Definition at line 695 of file Module.cpp.
References getModuleFlag().
getStackProtectorGuardOffset()
int Module::getStackProtectorGuardOffset () const
Get/set what offset from the stack protector to use.
Definition at line 731 of file Module.cpp.
References getModuleFlag().
Referenced by llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), and llvm::X86TargetLowering::getIRStackGuard().
getStackProtectorGuardReg()
StringRef Module::getStackProtectorGuardReg () const
Get/set which register to use as the stack protector guard register.
The empty string is equivalent to "global". Other values may be "tls" or "sysreg".
Definition at line 707 of file Module.cpp.
References getModuleFlag().
getStackProtectorGuardSymbol()
StringRef Module::getStackProtectorGuardSymbol () const
Get/set a symbol to use as the stack protector guard.
Definition at line 719 of file Module.cpp.
References getModuleFlag().
getSublistAccess() [1/5]
static FunctionListType Module::* llvm::Module::getSublistAccess (Function *) inline static
Definition at line 562 of file Module.h.
getSublistAccess() [2/5]
static AliasListType Module::* llvm::Module::getSublistAccess (GlobalAlias *) inline static
Definition at line 571 of file Module.h.
getSublistAccess() [3/5]
static IFuncListType Module::* llvm::Module::getSublistAccess (GlobalIFunc *) inline static
Definition at line 580 of file Module.h.
getSublistAccess() [4/5]
static GlobalListType Module::* llvm::Module::getSublistAccess (GlobalVariable *) inline static
Definition at line 554 of file Module.h.
getSublistAccess() [5/5]
static NamedMDListType Module::* llvm::Module::getSublistAccess (NamedMDNode *) inline static
Definition at line 589 of file Module.h.
getTargetTriple()
const std::string & llvm::Module::getTargetTriple () const inline
Get the target triple which is a string describing the target host.
Returns
a string containing the target triple.
Definition at line 258 of file Module.h.
Referenced by llvm::ModuleSymbolTable::addModule(), calculateCXXStateNumbers(), llvm::GlobalObject::canIncreaseAlignment(), llvm::ThinLTOCodeGenerator::crossModuleImport(), llvm::ThinLTOCodeGenerator::emitImports(), llvm::ThinLTOCodeGenerator::gatherImportedSummariesForModule(), llvm::LTOModule::getTargetTriple(), llvm::ThinLTOCodeGenerator::internalize(), llvm::TargetLibraryInfoImpl::isCallingConvCCompatible(), llvm::ThinLTOCodeGenerator::optimize(), and llvm::ThinLTOCodeGenerator::promote().
getUniqueIntrinsicName()
std::string Module::getUniqueIntrinsicName (StringRef BaseName, Intrinsic::ID Id, const FunctionType * Proto)
Return a unique name for an intrinsic whose mangling is based on an unnamed type.
The Proto represents the function prototype.
Definition at line 477 of file Module.cpp.
References F, getNamedValue(), and llvm::StringMap< ValueTy, AllocatorTy >::insert().
getUwtable()
UWTableKind Module::getUwtable () const
Get/set whether synthesized functions should get the uwtable attribute.
Definition at line 675 of file Module.cpp.
References getModuleFlag(), and llvm::None.
getValueSymbolTable() [1/2]
ValueSymbolTable & llvm::Module::getValueSymbolTable () inline
Get the Module's symbol table of global variable and function identifiers.
Definition at line 596 of file Module.h.
getValueSymbolTable() [2/2]
const ValueSymbolTable & llvm::Module::getValueSymbolTable () const inline
Get the symbol table of global variable and function identifiers.
Definition at line 594 of file Module.h.
Referenced by getNamedValue(), and getNumNamedValues().
global_begin() [1/2]
global_iterator llvm::Module::global_begin () inline
Definition at line 607 of file Module.h.
Referenced by LLVMGetPreviousGlobal().
global_begin() [2/2]
const_global_iterator llvm::Module::global_begin () const inline
Definition at line 608 of file Module.h.
global_empty()
bool llvm::Module::global_empty () const inline
Definition at line 612 of file Module.h.
global_end() [1/2]
global_iterator llvm::Module::global_end () inline
Definition at line 609 of file Module.h.
Referenced by LLVMGetNextGlobal().
global_end() [2/2]
const_global_iterator llvm::Module::global_end () const inline
Definition at line 610 of file Module.h.
global_objects() [1/2]
iterator_range< Module::global_object_iterator > Module::global_objects ()
Definition at line 413 of file Module.cpp.
References functions(), and globals().
Referenced by llvm::thinLTOFinalizeInModule().
global_objects() [2/2]
iterator_range< Module::const_global_object_iterator > Module::global_objects () const
Definition at line 417 of file Module.cpp.
References functions(), and globals().
global_size()
size_t llvm::Module::global_size () const inline
Definition at line 611 of file Module.h.
global_values() [1/2]
iterator_range< Module::global_value_iterator > Module::global_values ()
Definition at line 421 of file Module.cpp.
References aliases(), functions(), globals(), and ifuncs().
global_values() [2/2]
iterator_range< Module::const_global_value_iterator > Module::global_values () const
Definition at line 425 of file Module.cpp.
References aliases(), functions(), globals(), and ifuncs().
globals() [1/2]
iterator_range< global_iterator > llvm::Module::globals () inline
Definition at line 614 of file Module.h.
References llvm::make_range().
Referenced by dropAllReferences(), global_objects(), global_objects(), global_values(), global_values(), and llvm::thinLTOFinalizeInModule().
globals() [2/2]
iterator_range< const_global_iterator > llvm::Module::globals () const inline
Definition at line 617 of file Module.h.
References llvm::make_range().
ifunc_begin() [1/2]
ifunc_iterator llvm::Module::ifunc_begin () inline
Definition at line 665 of file Module.h.
ifunc_begin() [2/2]
const_ifunc_iterator llvm::Module::ifunc_begin () const inline
Definition at line 666 of file Module.h.
ifunc_empty()
bool llvm::Module::ifunc_empty () const inline
Definition at line 670 of file Module.h.
ifunc_end() [1/2]
ifunc_iterator llvm::Module::ifunc_end () inline
Definition at line 667 of file Module.h.
ifunc_end() [2/2]
const_ifunc_iterator llvm::Module::ifunc_end () const inline
Definition at line 668 of file Module.h.
ifunc_size()
size_t llvm::Module::ifunc_size () const inline
Definition at line 669 of file Module.h.
ifuncs() [1/2]
iterator_range< ifunc_iterator > llvm::Module::ifuncs () inline
Definition at line 672 of file Module.h.
References llvm::make_range().
Referenced by dropAllReferences(), global_values(), and global_values().
ifuncs() [2/2]
iterator_range< const_ifunc_iterator > llvm::Module::ifuncs () const inline
Definition at line 675 of file Module.h.
References llvm::make_range().
isDwarf64()
bool Module::isDwarf64 () const
Returns the DWARF format by checking module flags.
Definition at line 563 of file Module.cpp.
References getModuleFlag().
Referenced by llvm::DwarfDebug::DwarfDebug().
isMaterialized()
bool llvm::Module::isMaterialized () const inline
Definition at line 534 of file Module.h.
isValidModFlagBehavior()
bool Module::isValidModFlagBehavior (Metadata * MD, ModFlagBehavior & MFB) static
Checks if Metadata represents a valid ModFlagBehavior, and stores the converted result in MFB.
Definition at line 277 of file Module.cpp.
References ModFlagBehaviorFirstVal, and ModFlagBehaviorLastVal.
Referenced by isValidModuleFlag().
isValidModuleFlag()
bool Module::isValidModuleFlag (const MDNode & ModFlag, ModFlagBehavior & MFB, MDString *& Key, Metadata *& Val) static
Check if the given module flag metadata represents a valid module flag, and store the flag behavior, the key string and the value metadata.
Definition at line 288 of file Module.cpp.
References isValidModFlagBehavior().
Referenced by getModuleFlagsMetadata(), and setModuleFlag().
materialize()
Error Module::materialize (GlobalValue * GV)
Make sure the GlobalValue is fully read.
Definition at line 439 of file Module.cpp.
References llvm::Error::success().
Referenced by llvm::GlobalValue::materialize().
materializeAll()
Error Module::materializeAll ()
Make sure all GlobalValues in this Module are fully read and clear the Materializer.
Definition at line 446 of file Module.cpp.
References llvm::Error::success().
materializeMetadata()
Error Module::materializeMetadata ()
Definition at line 453 of file Module.cpp.
References llvm::Error::success().
named_metadata() [1/2]
iterator_range< named_metadata_iterator > llvm::Module::named_metadata () inline
Definition at line 719 of file Module.h.
References llvm::make_range().
named_metadata() [2/2]
iterator_range< const_named_metadata_iterator > llvm::Module::named_metadata () const inline
Definition at line 722 of file Module.h.
References llvm::make_range().
named_metadata_begin() [1/2]
named_metadata_iterator llvm::Module::named_metadata_begin () inline
Definition at line 706 of file Module.h.
named_metadata_begin() [2/2]
const_named_metadata_iterator llvm::Module::named_metadata_begin () const inline
Definition at line 707 of file Module.h.
named_metadata_empty()
bool llvm::Module::named_metadata_empty () const inline
Definition at line 717 of file Module.h.
named_metadata_end() [1/2]
named_metadata_iterator llvm::Module::named_metadata_end () inline
Definition at line 711 of file Module.h.
named_metadata_end() [2/2]
const_named_metadata_iterator llvm::Module::named_metadata_end () const inline
Definition at line 712 of file Module.h.
named_metadata_size()
size_t llvm::Module::named_metadata_size () const inline
Definition at line 716 of file Module.h.
print()
void Module::print (raw_ostream & OS, AssemblyAnnotationWriter * AAW, bool ShouldPreserveUseListOrder = false, bool IsForDebug = false) const
Print the module to an output stream with an optional AssemblyAnnotationWriter.
If ShouldPreserveUseListOrder, then include uselistorder directives so that use-lists can be recreated when reading the assembly.
Definition at line 4612 of file AsmWriter.cpp.
Referenced by llvm::yaml::BlockScalarTraits< Module >::output().
rbegin() [1/2]
reverse_iterator llvm::Module::rbegin () inline
Definition at line 629 of file Module.h.
rbegin() [2/2]
const_reverse_iterator llvm::Module::rbegin () const inline
Definition at line 630 of file Module.h.
rend() [1/2]
reverse_iterator llvm::Module::rend () inline
Definition at line 631 of file Module.h.
rend() [2/2]
const_reverse_iterator llvm::Module::rend () const inline
Definition at line 632 of file Module.h.
setCodeModel()
void Module::setCodeModel (CodeModel::Model CL)
Set the code model (tiny, small, kernel, medium or large)
Definition at line 628 of file Module.cpp.
References addModuleFlag(), and Error.
setDarwinTargetVariantSDKVersion()
void Module::setDarwinTargetVariantSDKVersion (VersionTuple Version)
Set the target variant version build SDK version metadata.
Definition at line 850 of file Module.cpp.
References addSDKVersionMD().
setDarwinTargetVariantTriple()
void Module::setDarwinTargetVariantTriple (StringRef T)
Set the target variant triple which is a string describing a variant of the target host platform.
Definition at line 841 of file Module.cpp.
References addModuleFlag(), llvm::MDString::get(), getContext(), and Override.
setDataLayout() [1/2]
void Module::setDataLayout (const DataLayout & Other)
Definition at line 396 of file Module.cpp.
References llvm::Other.
setDataLayout() [2/2]
void Module::setDataLayout (StringRef Desc)
Set the data layout.
Definition at line 392 of file Module.cpp.
References llvm::DataLayout::reset().
setFramePointer()
void Module::setFramePointer (FramePointerKind Kind)
Definition at line 691 of file Module.cpp.
References addModuleFlag(), and Max.
setMaterializer()
void Module::setMaterializer (GVMaterializer * GVM)
Sets the GVMaterializer to GVM.
This module must not yet have a Materializer. To reset the materializer for a module that already has one, call materializeAll first. Destroying this module will destroy its materializer without materializing any more GlobalValues. Without destroying the Module, there is no way to detach or destroy a materializer without materializing all the GVs it controls, to avoid leaving orphan unmaterialized GVs.
Definition at line 432 of file Module.cpp.
References assert().
setModuleFlag()
void Module::setModuleFlag (ModFlagBehavior Behavior, StringRef Key, Metadata * Val)
Like addModuleFlag but replaces the old module flag if it already exists.
Definition at line 375 of file Module.cpp.
References addModuleFlag(), E, getOrInsertModuleFlagsMetadata(), I, and isValidModuleFlag().
Referenced by setProfileSummary().
setModuleIdentifier()
void llvm::Module::setModuleIdentifier (StringRef ID) inline
Set the module identifier.
Definition at line 291 of file Module.h.
setModuleInlineAsm()
void llvm::Module::setModuleInlineAsm (StringRef Asm) inline
Set the module-scope inline assembly blocks.
A trailing newline is added if the input doesn't have one.
Definition at line 305 of file Module.h.
setOverrideStackAlignment()
void Module::setOverrideStackAlignment (unsigned Align)
Definition at line 749 of file Module.cpp.
References addModuleFlag(), and Error.
setOwnedMemoryBuffer()
void Module::setOwnedMemoryBuffer (std::unique_ptr< MemoryBuffer > MB)
Take ownership of the given memory buffer.
Definition at line 662 of file Module.cpp.
setPartialSampleProfileRatio()
void Module::setPartialSampleProfileRatio (const ModuleSummaryIndex & Index)
Set the partial sample profile ratio in the profile summary module flag, if applicable.
Definition at line 815 of file Module.cpp.
References getContext(), llvm::ProfileSummary::getFromMD(), llvm::ProfileSummary::getKind(), llvm::ProfileSummary::getMD(), llvm::ProfileSummary::getNumCounts(), getProfileSummary(), llvm::ProfileSummary::isPartialProfile(), llvm::ProfileSummary::PSK_Sample, llvm::ProfileSummary::setPartialProfileRatio(), and setProfileSummary().
setPICLevel()
void Module::setPICLevel (PICLevel::Level PL)
Set the PIC level (small or large model)
Definition at line 598 of file Module.cpp.
References addModuleFlag(), and Min.
setPIELevel()
void Module::setPIELevel (PIELevel::Level PL)
Set the PIE level (small or large model)
Definition at line 614 of file Module.cpp.
References addModuleFlag(), and Max.
setProfileSummary()
void Module::setProfileSummary (Metadata * M, ProfileSummary::Kind Kind)
Attach profile summary metadata to this module.
Definition at line 636 of file Module.cpp.
References Error, llvm::ProfileSummary::PSK_CSInstr, and setModuleFlag().
Referenced by setPartialSampleProfileRatio().
setRtLibUseGOT()
void Module::setRtLibUseGOT ()
Set that PLT should be avoid for RTLib calls.
Definition at line 671 of file Module.cpp.
References addModuleFlag(), and Max.
setSDKVersion()
void Module::setSDKVersion (const VersionTuple & V)
Attach a build SDK version metadata to this module.
Definition at line 767 of file Module.cpp.
References addSDKVersionMD().
setSemanticInterposition()
void Module::setSemanticInterposition (bool SI)
Set whether semantic interposition is to be respected.
Definition at line 658 of file Module.cpp.
References addModuleFlag(), Error, and SI.
setSourceFileName()
void llvm::Module::setSourceFileName (StringRef Name) inline
Set the module's original source file name.
Definition at line 294 of file Module.h.
References Name.
setStackProtectorGuard()
void Module::setStackProtectorGuard (StringRef Kind)
Definition at line 702 of file Module.cpp.
References addModuleFlag(), Error, llvm::MDString::get(), and getContext().
setStackProtectorGuardOffset()
void Module::setStackProtectorGuardOffset (int Offset)
Definition at line 738 of file Module.cpp.
References addModuleFlag(), Error, and llvm::Offset.
setStackProtectorGuardReg()
void Module::setStackProtectorGuardReg (StringRef Reg)
Definition at line 714 of file Module.cpp.
References addModuleFlag(), Error, llvm::MDString::get(), and getContext().
setStackProtectorGuardSymbol()
void Module::setStackProtectorGuardSymbol (StringRef Symbol)
Definition at line 726 of file Module.cpp.
References addModuleFlag(), Error, llvm::MDString::get(), and getContext().
setTargetTriple()
void llvm::Module::setTargetTriple (StringRef T) inline
Set the target triple.
Definition at line 301 of file Module.h.
Referenced by llvm::LTOModule::setTargetTriple().
setUwtable()
void Module::setUwtable (UWTableKind Kind)
Definition at line 681 of file Module.cpp.
References addModuleFlag(), and Max.
shouldEmitInstrCountChangedRemark()
bool llvm::Module::shouldEmitInstrCountChangedRemark () inline
Return true if size-info optimization remark is enabled, false otherwise.
Definition at line 281 of file Module.h.
size()
size_t llvm::Module::size () const inline
Definition at line 633 of file Module.h.
Friends And Related Symbol Documentation
Constant
friend class Constant friend
Definition at line 210 of file Module.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Module.h
lib/IR/AsmWriter.cpp
lib/IR/LLVMContextImpl.cpp
lib/IR/Module.cpp