LLVM: llvm::sampleprof::SampleProfileReaderCompactBinary Class Reference
llvm::sampleprof::SampleProfileReaderCompactBinary Class Reference
#include "llvm/ProfileData/SampleProfReader.h"
Public Member Functions
SampleProfileReaderCompactBinary (std::unique_ptr< MemoryBuffer > B, LLVMContext &C)
std::error_code readImpl () override
Read samples only for functions to use.
bool collectFuncsFromModule () override
Collect functions with definitions in Module M.
bool useMD5 () override
Return whether names in the profile are all MD5 numbers.
Public Member Functions inherited from llvm::sampleprof::SampleProfileReaderBinary
SampleProfileReaderBinary (std::unique_ptr< MemoryBuffer > B, LLVMContext &C, SampleProfileFormat Format=SPF_None)
std::vector< StringRef > * getNameTable () override
It includes all the names that have samples either in outline instance or inline instance.
Public Member Functions inherited from llvm::sampleprof::SampleProfileReader
SampleProfileReader (std::unique_ptr< MemoryBuffer > B, LLVMContext &C, SampleProfileFormat Format=SPF_None)
virtual ~SampleProfileReader ()=default
void setDiscriminatorMaskedBitFrom (FSDiscriminatorPass P)
Set the bits for FS discriminators.
uint32_t getDiscriminatorMask () const
Get the bitmask the discriminators: For FS profiles, return the bit mask for this pass.
std::error_code read ()
The interface to read sample profiles from the associated file.
void dumpFunctionProfile (SampleContext FContext, raw_ostream &OS=dbgs())
Print the profile for FContext on stream OS.
void dump (raw_ostream &OS=dbgs())
Print all the profiles on stream OS.
void dumpJson (raw_ostream &OS=dbgs())
Print all the profiles on stream OS in the JSON format.
FunctionSamples * getSamplesFor (const Function &F)
Return the samples collected for function F.
FunctionSamples * getOrCreateSamplesFor (const Function &F)
Return the samples collected for function F, create empty FunctionSamples if it doesn't exist.
virtual FunctionSamples * getSamplesFor (StringRef Fname)
Return the samples collected for function F.
SampleProfileMap & getProfiles ()
Return all the profiles.
void reportError (int64_t LineNumber, const Twine &Msg) const
Report a parse error message.
ProfileSummary & getSummary () const
Return the profile summary.
MemoryBuffer * getBuffer () const
SampleProfileFormat getFormat () const
Return the profile format.
bool profileIsProbeBased () const
Whether input profile is based on pseudo probes.
bool profileIsCS () const
Whether input profile is fully context-sensitive.
bool profileIsPreInlined () const
Whether input profile contains ShouldBeInlined contexts.
virtual std::unique_ptr< ProfileSymbolList > getProfileSymbolList ()
virtual bool dumpSectionInfo (raw_ostream &OS=dbgs())
virtual void setSkipFlatProf (bool Skip)
Don't read profile without context if the flag is set.
virtual bool hasUniqSuffix ()
Return whether any name in the profile contains ".__uniq." suffix.
SampleProfileReaderItaniumRemapper * getRemapper ()
void setModule (const Module *Mod)
Static Public Member Functions
static bool hasFormat (const MemoryBuffer &Buffer)
Return true if Buffer is in the format supported by this class.
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileReader
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (const std::string Filename, LLVMContext &C, FSDiscriminatorPass P=FSDiscriminatorPass::Base, const std::string RemapFilename="")
Create a sample profile reader appropriate to the file format.
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (std::unique_ptr< MemoryBuffer > &B, LLVMContext &C, FSDiscriminatorPass P=FSDiscriminatorPass::Base, const std::string RemapFilename="")
Create a sample profile reader from the supplied memory buffer.
Additional Inherited Members
Protected Member Functions inherited from llvm::sampleprof::SampleProfileReaderBinary
template<typename T >
ErrorOr< T > readNumber ()
Read a numeric value of type T from the profile.
template<typename T >
ErrorOr< T > readUnencodedNumber ()
Read a numeric value of type T from the profile.
ErrorOr< StringRef > readString ()
Read a string from the profile.
template<typename T >
ErrorOr< uint32_t > readStringIndex (T &Table)
Read the string index and check whether it overflows the table.
bool at_eof () const
Return true if we've reached the end of file.
std::error_code readFuncProfile (const uint8_t *Start)
Read the next function profile instance.
std::error_code readProfile (FunctionSamples &FProfile)
Read the contents of the given profile instance.
std::error_code readMagicIdent ()
Read the contents of Magic number and Version number.
std::error_code readSummary ()
Read profile summary.
virtual ErrorOr< SampleContext > readSampleContextFromTable ()
Protected Member Functions inherited from llvm::sampleprof::SampleProfileReader
void computeSummary ()
Compute summary for this profile.
Static Protected Member Functions inherited from llvm::sampleprof::SampleProfileReader
static std::unique_ptr< ProfileSummary > takeSummary (SampleProfileReader &Reader)
Take ownership of the summary of this reader.
Protected Attributes inherited from llvm::sampleprof::SampleProfileReaderBinary
const uint8_t * Data = nullptr
Points to the current location in the buffer.
const uint8_t * End = nullptr
Points to the end of the buffer.
std::vector< StringRef > NameTable
Function name table.
Protected Attributes inherited from llvm::sampleprof::SampleProfileReader
SampleProfileMap Profiles
Map every function to its associated profile.
LLVMContext & Ctx
LLVM context used to emit diagnostics.
std::unique_ptr< MemoryBuffer > Buffer
Memory buffer holding the profile file.
std::unordered_set< std::string > MD5NameBuffer
Extra name buffer holding names created on demand.
std::unique_ptr< ProfileSummary > Summary
Profile summary information.
std::unique_ptr< SampleProfileReaderItaniumRemapper > Remapper
bool ProfileIsProbeBased = false
Whether samples are collected based on pseudo probes.
bool ProfileIsCS = false
Whether function profiles are context-sensitive flat profiles.
bool ProfileIsPreInlined = false
Whether function profile contains ShouldBeInlined contexts.
uint32_t CSProfileCount = 0
Number of context-sensitive profiles.
bool ProfileIsFS = false
Whether the function profiles use FS discriminators.
SampleProfileFormat Format = SPF_None
The format of sample.
const Module * M = nullptr
The current module being compiled if SampleProfileReader is used by compiler.
uint32_t MaskedBitFrom = 31
Zero out the discriminator bits higher than bit MaskedBitFrom (0 based).
Detailed Description
Definition at line 810 of file SampleProfReader.h.
Constructor & Destructor Documentation
SampleProfileReaderCompactBinary()
llvm::sampleprof::SampleProfileReaderCompactBinary::SampleProfileReaderCompactBinary (std::unique_ptr< MemoryBuffer > B, LLVMContext & C) inline
Definition at line 827 of file SampleProfReader.h.
Member Function Documentation
collectFuncsFromModule()
bool SampleProfileReaderCompactBinary::collectFuncsFromModule () override virtual
Collect functions with definitions in Module M.
Return true if the reader has been given a module.
Reimplemented from llvm::sampleprof::SampleProfileReader.
Definition at line 1467 of file SampleProfReader.cpp.
References F, llvm::sampleprof::FunctionSamples::getCanonicalFnName(), and llvm::sampleprof::SampleProfileReader::M.
Referenced by readImpl().
hasFormat()
bool SampleProfileReaderCompactBinary::hasFormat (const MemoryBuffer & Buffer) static
Return true if Buffer is in the format supported by this class.
Definition at line 1546 of file SampleProfReader.cpp.
References llvm::sampleprof::SampleProfileReader::Buffer, llvm::sampleprof::SampleProfileReaderBinary::Data, llvm::decodeULEB128(), llvm::sampleprof::SPF_Compact_Binary, and llvm::sampleprof::SPMagic().
Referenced by llvm::sampleprof::SampleProfileReader::create().
readImpl()
std::error_code SampleProfileReaderCompactBinary::readImpl () override virtual
Read samples only for functions to use.
Reimplemented from llvm::sampleprof::SampleProfileReaderBinary.
Definition at line 1013 of file SampleProfReader.cpp.
References llvm::sampleprof::SampleProfileReader::Buffer, collectFuncsFromModule(), llvm::sampleprof::SampleProfileReaderBinary::Data, llvm::MD5Hash(), Name, llvm::Offset, llvm::sampleprof::FunctionSamples::ProfileIsFS, llvm::sampleprof::SampleProfileReader::ProfileIsFS, ProfileIsFSDisciminator, llvm::sampleprof::SampleProfileReaderBinary::readFuncProfile(), and llvm::success.
useMD5()
bool llvm::sampleprof::SampleProfileReaderCompactBinary::useMD5 () inline override virtual
Return whether names in the profile are all MD5 numbers.
Reimplemented from llvm::sampleprof::SampleProfileReader.
Definition at line 842 of file SampleProfReader.h.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfReader.h
lib/ProfileData/SampleProfReader.cpp