LLVM: llvm::AMDGPU::VOPD::InstInfo Class Reference
llvm::AMDGPU::VOPD::InstInfo Class Reference
#include "Target/AMDGPU/Utils/AMDGPUBaseInfo.h"
Public Types
using RegIndices = std::array<unsigned, Component::MAX_OPR_NUM>
Public Member Functions
InstInfo (const MCInstrDesc &OpX, const MCInstrDesc &OpY)
InstInfo (const ComponentInfo &OprInfoX, const ComponentInfo &OprInfoY)
const ComponentInfo & operator[] (size_t ComponentIdx) const
bool hasInvalidOperand (std::function< unsigned(unsigned, unsigned)> GetRegIdx) const
std::optional< unsigned > getInvalidCompOperandIndex (std::function< unsigned(unsigned, unsigned)> GetRegIdx) const
Detailed Description
Definition at line 721 of file AMDGPUBaseInfo.h.
Member Typedef Documentation
RegIndices
using llvm::AMDGPU::VOPD::InstInfo::RegIndices = std::array<unsigned, Component::MAX_OPR_NUM>
Definition at line 726 of file AMDGPUBaseInfo.h.
Constructor & Destructor Documentation
InstInfo() [1/2]
llvm::AMDGPU::VOPD::InstInfo::InstInfo (const MCInstrDesc & OpX, const MCInstrDesc & OpY) inline
Definition at line 728 of file AMDGPUBaseInfo.h.
InstInfo() [2/2]
llvm::AMDGPU::VOPD::InstInfo::InstInfo (const ComponentInfo & OprInfoX, const ComponentInfo & OprInfoY) inline
Definition at line 731 of file AMDGPUBaseInfo.h.
Member Function Documentation
getInvalidCompOperandIndex()
std::optional< unsigned > llvm::AMDGPU::VOPD::InstInfo::getInvalidCompOperandIndex (std::function< unsigned(unsigned, unsigned)> GetRegIdx) const
Definition at line 563 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::VOPD::BANKS_NUM, llvm::AMDGPU::VOPD::MAX_OPR_NUM, llvm::AMDGPU::VOPD::X, and llvm::AMDGPU::VOPD::Y.
Referenced by hasInvalidOperand().
hasInvalidOperand()
bool llvm::AMDGPU::VOPD::InstInfo::hasInvalidOperand (std::function< unsigned(unsigned, unsigned)> GetRegIdx) const inline
Definition at line 743 of file AMDGPUBaseInfo.h.
References getInvalidCompOperandIndex().
operator[]()
const ComponentInfo & llvm::AMDGPU::VOPD::InstInfo::operator[] (size_t ComponentIdx) const inline
Definition at line 734 of file AMDGPUBaseInfo.h.
References assert(), and llvm::AMDGPU::VOPD::COMPONENTS_NUM.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.h
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp