LLVM: llvm::jitlink::COFFLinkGraphBuilder Class Reference
llvm::jitlink::COFFLinkGraphBuilder Class Reference abstract
#include "ExecutionEngine/JITLink/COFFLinkGraphBuilder.h"
Public Member Functions
virtual ~COFFLinkGraphBuilder ()
Expected< std::unique_ptr< LinkGraph > > buildGraph ()
Protected Types
using COFFSectionIndex = int32_t
using COFFSymbolIndex = int32_t
Protected Member Functions
COFFLinkGraphBuilder (const object::COFFObjectFile &Obj, Triple TT, LinkGraph::GetEdgeKindNameFunction GetEdgeKindName)
LinkGraph & getGraph () const
const object::COFFObjectFile & getObject () const
virtual Error addRelocations ()=0
Error graphifySections ()
Error graphifySymbols ()
void setGraphSymbol (COFFSectionIndex SecIndex, COFFSymbolIndex SymIndex, Symbol &Sym)
Symbol * getGraphSymbol (COFFSymbolIndex SymIndex) const
void setGraphBlock (COFFSectionIndex SecIndex, Block *B)
Block * getGraphBlock (COFFSectionIndex SecIndex) const
object::COFFObjectFile::section_iterator_range sections () const
template<typename RelocHandlerFunction >
Error forEachRelocation (const object::SectionRef &RelSec, RelocHandlerFunction &&Func, bool ProcessDebugSections=false)
Traverse all matching relocation records in the given section.
template<typename ClassT , typename RelocHandlerMethod >
Error forEachRelocation (const object::SectionRef &RelSec, ClassT *Instance, RelocHandlerMethod &&Method, bool ProcessDebugSections=false)
Traverse all matching relocation records in the given section.
Detailed Description
Definition at line 32 of file COFFLinkGraphBuilder.h.
Member Typedef Documentation
COFFSectionIndex
using llvm::jitlink::COFFLinkGraphBuilder::COFFSectionIndex = int32_t protected
Definition at line 38 of file COFFLinkGraphBuilder.h.
COFFSymbolIndex
using llvm::jitlink::COFFLinkGraphBuilder::COFFSymbolIndex = int32_t protected
Definition at line 39 of file COFFLinkGraphBuilder.h.
Constructor & Destructor Documentation
~COFFLinkGraphBuilder()
llvm::jitlink::COFFLinkGraphBuilder::~COFFLinkGraphBuilder () virtual default
COFFLinkGraphBuilder()
llvm::jitlink::COFFLinkGraphBuilder::COFFLinkGraphBuilder (const object::COFFObjectFile & Obj, Triple TT, LinkGraph::GetEdgeKindNameFunction GetEdgeKindName) protected
Definition at line 26 of file COFFLinkGraphBuilder.cpp.
References llvm::dbgs(), llvm::object::Binary::getFileName(), and LLVM_DEBUG.
Member Function Documentation
addRelocations()
virtual Error llvm::jitlink::COFFLinkGraphBuilder::addRelocations () protected pure virtual
Referenced by buildGraph().
buildGraph()
Expected< std::unique_ptr< LinkGraph > > llvm::jitlink::COFFLinkGraphBuilder::buildGraph ()
Definition at line 79 of file COFFLinkGraphBuilder.cpp.
References addRelocations(), graphifySections(), and graphifySymbols().
forEachRelocation() [1/2]
template<typename ClassT , typename RelocHandlerMethod > Error llvm::jitlink::COFFLinkGraphBuilder::forEachRelocation (const object::SectionRef & RelSec, ClassT * Instance, RelocHandlerMethod && Method, bool ProcessDebugSections = false) inline protected
Traverse all matching relocation records in the given section.
Convenience wrapper to allow passing a member function for the handler.
Definition at line 99 of file COFFLinkGraphBuilder.h.
References forEachRelocation().
forEachRelocation() [2/2]
template<typename RelocHandlerFunction > Error llvm::jitlink::COFFLinkGraphBuilder::forEachRelocation (const object::SectionRef & RelSec, RelocHandlerFunction && Func, bool ProcessDebugSections = false) protected
Traverse all matching relocation records in the given section.
The handler function Func should be callable with this signature: Error(const object::RelocationRef&, const object::SectionRef&, Section &)
Definition at line 185 of file COFFLinkGraphBuilder.h.
References llvm::dbgs(), llvm::object::COFFObjectFile::getCOFFSection(), getGraphBlock(), llvm::object::COFFObjectFile::getSectionName(), llvm::inconvertibleErrorCode(), LLVM_DEBUG, Name, and llvm::Error::success().
Referenced by forEachRelocation().
getGraph()
LinkGraph & llvm::jitlink::COFFLinkGraphBuilder::getGraph () const inline protected
Definition at line 44 of file COFFLinkGraphBuilder.h.
getGraphBlock()
Block * llvm::jitlink::COFFLinkGraphBuilder::getGraphBlock (COFFSectionIndex SecIndex) const inline protected
Definition at line 74 of file COFFLinkGraphBuilder.h.
Referenced by forEachRelocation().
getGraphSymbol()
Symbol * llvm::jitlink::COFFLinkGraphBuilder::getGraphSymbol (COFFSymbolIndex SymIndex) const inline protected
Definition at line 61 of file COFFLinkGraphBuilder.h.
getObject()
const object::COFFObjectFile & llvm::jitlink::COFFLinkGraphBuilder::getObject () const inline protected
Definition at line 46 of file COFFLinkGraphBuilder.h.
graphifySections()
Error llvm::jitlink::COFFLinkGraphBuilder::graphifySections () protected
Definition at line 121 of file COFFLinkGraphBuilder.cpp.
References B, llvm::Data, llvm::dbgs(), llvm::orc::Exec, llvm::COFF::IMAGE_SCN_CNT_UNINITIALIZED_DATA, llvm::COFF::IMAGE_SCN_MEM_EXECUTE, llvm::COFF::IMAGE_SCN_MEM_READ, llvm::COFF::IMAGE_SCN_MEM_WRITE, LLVM_DEBUG, llvm::orc::Read, setGraphBlock(), llvm::Error::success(), and llvm::orc::Write.
Referenced by buildGraph().
graphifySymbols()
Error llvm::jitlink::COFFLinkGraphBuilder::graphifySymbols () protected
Definition at line 190 of file COFFLinkGraphBuilder.cpp.
References Characteristics, llvm::dbgs(), llvm::formatv(), llvm::COFF::isReservedSectionNumber(), LLVM_DEBUG, setGraphSymbol(), llvm::Error::success(), llvm::object::coff_aux_weak_external::TagIndex, and llvm::dwarf::toString().
Referenced by buildGraph().
sections()
object::COFFObjectFile::section_iterator_range llvm::jitlink::COFFLinkGraphBuilder::sections () const inline protected
Definition at line 81 of file COFFLinkGraphBuilder.h.
References llvm::object::ObjectFile::sections().
setGraphBlock()
void llvm::jitlink::COFFLinkGraphBuilder::setGraphBlock (COFFSectionIndex SecIndex, Block * B) inline protected
Definition at line 68 of file COFFLinkGraphBuilder.h.
References assert(), B, and llvm::COFF::isReservedSectionNumber().
Referenced by graphifySections().
setGraphSymbol()
void llvm::jitlink::COFFLinkGraphBuilder::setGraphSymbol (COFFSectionIndex SecIndex, COFFSymbolIndex SymIndex, Symbol & Sym) inline protected
Definition at line 53 of file COFFLinkGraphBuilder.h.
References assert(), llvm::jitlink::Symbol::getOffset(), and llvm::COFF::isReservedSectionNumber().
Referenced by graphifySymbols().
The documentation for this class was generated from the following files:
lib/ExecutionEngine/JITLink/COFFLinkGraphBuilder.h
lib/ExecutionEngine/JITLink/COFFLinkGraphBuilder.cpp