LLVM: llvm::parallel::TaskGroup Class Reference
llvm::parallel::TaskGroup Class Reference
#include "llvm/Support/Parallel.h"
Public Member Functions
TaskGroup ()
~TaskGroup ()
void spawn (std::function< void()> f)
void execute (std::function< void()> f)
void sync () const
Detailed Description
Definition at line 78 of file Parallel.h.
Constructor & Destructor Documentation
TaskGroup()
llvm::parallel::TaskGroup::TaskGroup ()
Definition at line 164 of file Parallel.cpp.
~TaskGroup()
llvm::parallel::TaskGroup::~TaskGroup ()
Definition at line 165 of file Parallel.cpp.
References llvm::parallel::detail::Latch::sync(), and llvm::parallel::TaskGroupInstances.
Member Function Documentation
execute()
void llvm::parallel::TaskGroup::execute (std::function< void()> f)
Definition at line 186 of file Parallel.cpp.
References F, spawn(), and llvm::parallel::strategy.
spawn()
void llvm::parallel::TaskGroup::spawn (std::function< void()> f)
Definition at line 172 of file Parallel.cpp.
References llvm::parallel::detail::Latch::dec(), F, and llvm::parallel::detail::Latch::inc().
Referenced by execute(), and llvm::parallelFor().
sync()
void llvm::parallel::TaskGroup::sync () const inline
Definition at line 106 of file Parallel.h.
References llvm::parallel::detail::Latch::sync().
The documentation for this class was generated from the following files:
include/llvm/Support/Parallel.h
lib/Support/Parallel.cpp