LLVM: llvm::NodeSet Class Reference
llvm::NodeSet Class Reference
A NodeSet contains a set of SUnit DAG nodes with additional information that assigns a priority to the set.
#include "llvm/CodeGen/MachinePipeliner.h"
Public Types
using iterator = SetVector<SUnit *>::const_iterator
Public Member Functions
NodeSet ()=default
NodeSet (iterator S, iterator E)
bool insert (SUnit *SU)
void insert (iterator S, iterator E)
template<typename UnaryPredicate >
bool remove_if (UnaryPredicate P)
unsigned count (SUnit *SU) const
bool hasRecurrence ()
unsigned size () const
bool empty () const
SUnit * getNode (unsigned i) const
void setRecMII (unsigned mii)
void setColocate (unsigned c)
void setExceedPressure (SUnit *SU)
bool isExceedSU (SUnit *SU)
int compareRecMII (NodeSet &RHS)
int getRecMII ()
void computeNodeSetInfo (SwingSchedulerDAG *SSD)
Summarize node functions for the entire node set.
unsigned getLatency ()
unsigned getMaxDepth ()
void clear ()
operator SetVector< SUnit * > & ()
bool operator> (const NodeSet &RHS) const
Sort the node sets by importance.
bool operator== (const NodeSet &RHS) const
bool operator!= (const NodeSet &RHS) const
iterator begin ()
iterator end ()
void print (raw_ostream &os) const
LLVM_DUMP_METHOD void dump () const
Detailed Description
A NodeSet contains a set of SUnit DAG nodes with additional information that assigns a priority to the set.
Definition at line 322 of file MachinePipeliner.h.
Member Typedef Documentation
iterator
using llvm::NodeSet::iterator = SetVector<SUnit *>::const_iterator
Definition at line 333 of file MachinePipeliner.h.
Constructor & Destructor Documentation
NodeSet() [1/2]
llvm::NodeSet::NodeSet () default
NodeSet() [2/2]
llvm::NodeSet::NodeSet (iterator S, iterator E) inline
Definition at line 336 of file MachinePipeliner.h.
References llvm::Latency.
Member Function Documentation
begin()
iterator llvm::NodeSet::begin () inline
Definition at line 432 of file MachinePipeliner.h.
clear()
void llvm::NodeSet::clear () inline
Definition at line 398 of file MachinePipeliner.h.
compareRecMII()
int llvm::NodeSet::compareRecMII (NodeSet & RHS) inline
Definition at line 382 of file MachinePipeliner.h.
computeNodeSetInfo()
void llvm::NodeSet::computeNodeSetInfo (SwingSchedulerDAG * SSD) inline
Summarize node functions for the entire node set.
Definition at line 387 of file MachinePipeliner.h.
count()
unsigned llvm::NodeSet::count (SUnit * SU) const inline
Definition at line 364 of file MachinePipeliner.h.
dump()
LLVM_DUMP_METHOD void NodeSet::dump () const
Definition at line 2978 of file MachinePipeliner.cpp.
References llvm::dbgs(), and llvm::print().
empty()
bool llvm::NodeSet::empty () const inline
Definition at line 370 of file MachinePipeliner.h.
end()
iterator llvm::NodeSet::end () inline
Definition at line 433 of file MachinePipeliner.h.
getLatency()
unsigned llvm::NodeSet::getLatency () inline
Definition at line 394 of file MachinePipeliner.h.
References llvm::Latency.
getMaxDepth()
unsigned llvm::NodeSet::getMaxDepth () inline
Definition at line 396 of file MachinePipeliner.h.
getNode()
SUnit * llvm::NodeSet::getNode (unsigned i) const inline
Definition at line 372 of file MachinePipeliner.h.
getRecMII()
int llvm::NodeSet::getRecMII () inline
Definition at line 384 of file MachinePipeliner.h.
hasRecurrence()
bool llvm::NodeSet::hasRecurrence () inline
Definition at line 366 of file MachinePipeliner.h.
insert() [1/2]
void llvm::NodeSet::insert (iterator S, iterator E) inline
Definition at line 358 of file MachinePipeliner.h.
References E.
insert() [2/2]
bool llvm::NodeSet::insert (SUnit * SU) inline
Definition at line 356 of file MachinePipeliner.h.
Referenced by nodes_for_root().
isExceedSU()
bool llvm::NodeSet::isExceedSU (SUnit * SU) inline
Definition at line 380 of file MachinePipeliner.h.
operator SetVector< SUnit * > &()
llvm::NodeSet::operator SetVector< SUnit * > & () inline
Definition at line 408 of file MachinePipeliner.h.
operator!=()
bool llvm::NodeSet::operator!= (const NodeSet & RHS) const inline
Definition at line 430 of file MachinePipeliner.h.
References operator==().
operator==()
bool llvm::NodeSet::operator== (const NodeSet & RHS) const inline
Definition at line 425 of file MachinePipeliner.h.
Referenced by operator!=().
operator>()
bool llvm::NodeSet::operator> (const NodeSet & RHS) const inline
Sort the node sets by importance.
First, rank them by recurrence MII, then by mobility (least mobile done first), and finally by depth. Each node set may contain a colocate value which is used as the first tie breaker, if it's set.
Definition at line 414 of file MachinePipeliner.h.
print()
void NodeSet::print (raw_ostream & os) const
Definition at line 2952 of file MachinePipeliner.cpp.
References I, MaxDepth, and size().
remove_if()
template<typename UnaryPredicate > bool llvm::NodeSet::remove_if (UnaryPredicate P) inline
Definition at line 360 of file MachinePipeliner.h.
References P.
setColocate()
void llvm::NodeSet::setColocate (unsigned c) inline
Definition at line 376 of file MachinePipeliner.h.
setExceedPressure()
void llvm::NodeSet::setExceedPressure (SUnit * SU) inline
Definition at line 378 of file MachinePipeliner.h.
setRecMII()
void llvm::NodeSet::setRecMII (unsigned mii) inline
Definition at line 374 of file MachinePipeliner.h.
size()
unsigned llvm::NodeSet::size () const inline
Definition at line 368 of file MachinePipeliner.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachinePipeliner.h
lib/CodeGen/MachinePipeliner.cpp