LLVM: llvm::objcopy::wasm::Writer Class Reference
llvm::objcopy::wasm::Writer Class Reference
#include "ObjCopy/wasm/WasmWriter.h"
Public Member Functions
Writer (Object &Obj, raw_ostream &Out)
Error write ()
Detailed Description
Definition at line 20 of file WasmWriter.h.
Constructor & Destructor Documentation
Writer()
llvm::objcopy::wasm::Writer::Writer (Object & Obj, raw_ostream & Out) inline
Definition at line 22 of file WasmWriter.h.
Member Function Documentation
write()
Error llvm::objcopy::wasm::Writer::write ()
Definition at line 57 of file WasmWriter.cpp.
References llvm::StringRef::data(), llvm::objcopy::wasm::Object::Header, I, llvm::wasm::WasmObjectHeader::Magic, llvm::raw_ostream::reserveExtraSpace(), llvm::objcopy::wasm::Object::Sections, llvm::StringRef::size(), llvm::Error::success(), llvm::wasm::WasmObjectHeader::Version, llvm::raw_ostream::write(), and llvm::support::endian::write32le().
The documentation for this class was generated from the following files:
lib/ObjCopy/wasm/WasmWriter.h
lib/ObjCopy/wasm/WasmWriter.cpp