LLVM: llvm::ARMBaseTargetMachine Class Reference
llvm::ARMBaseTargetMachine Class Reference
#include "Target/ARM/ARMTargetMachine.h"
Public Types
enum ARMABI { ARM_ABI_UNKNOWN , ARM_ABI_APCS , ARM_ABI_AAPCS , ARM_ABI_AAPCS16 }
Public Member Functions
ARMBaseTargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool isLittle)
Create an ARM architecture model.
~ARMBaseTargetMachine () override
const ARMSubtarget * getSubtargetImpl (const Function &F) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
const ARMSubtarget * getSubtargetImpl () const =delete
bool isLittleEndian () const
TargetTransformInfo getTargetTransformInfo (const Function &F) const override
Return a TargetTransformInfo for a given function.
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
TargetLoweringObjectFile * getObjFileLowering () const override
bool isTargetHardFloat () const
bool targetSchedulesPostRAScheduling () const override
True if subtarget inserts the final scheduling pass on its own.
MachineFunctionInfo * createMachineFunctionInfo (BumpPtrAllocator &Allocator, const Function &F, const TargetSubtargetInfo *STI) const override
Create the target's instance of MachineFunctionInfo.
bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const override
Returns true if a cast between SrcAS and DestAS is a noop.
Public Member Functions inherited from llvm::LLVMTargetMachine
TargetTransformInfo getTargetTransformInfo (const Function &F) const override
Get a TargetTransformInfo implementation for the target.
bool addPassesToEmitFile (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, bool DisableVerify=true, MachineModuleInfoWrapperPass *MMIWP=nullptr) override
Add passes to the specified pass manager to get the specified file emitted.
virtual Error buildCodeGenPipeline (ModulePassManager &, MachineFunctionPassManager &, MachineFunctionAnalysisManager &, raw_pwrite_stream &, raw_pwrite_stream *, CodeGenFileType, CGPassBuilderOption, PassInstrumentationCallbacks *)
virtual std::pair< StringRef, bool > getPassNameFromLegacyName (StringRef)
bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_pwrite_stream &Out, bool DisableVerify=true) override
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
virtual bool isMachineVerifierClean () const
Returns true if the target is expected to pass all machine verifier checks.
bool addAsmPrinter (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Context)
Adds an AsmPrinter pass to the pipeline that prints assembly or machine code from the MI representation.
Expected< std::unique_ptr< MCStreamer > > createMCStreamer (raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Ctx)
virtual bool usesPhysRegsForValues () const
True if the target uses physical regs (as nearly all targets do).
virtual bool useIPRA () const
True if the target wants to use interprocedural register allocation by default.
virtual int unqualifiedInlineAsmVariant () const
The default variant to use in unqualified asm instructions.
Public Member Functions inherited from llvm::TargetMachine
TargetMachine (const TargetMachine &)=delete
void operator= (const TargetMachine &)=delete
virtual ~TargetMachine ()
const Target & getTarget () const
const Triple & getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
void setTargetFeatureString (StringRef FS)
virtual yaml::MachineFunctionInfo * createDefaultFuncInfoYAML () const
Allocate and return a default initialized instance of the YAML representation for the MachineFunctionInfo.
virtual yaml::MachineFunctionInfo * convertFuncInfoToYAML (const MachineFunction &MF) const
Allocate and initialize an instance of the YAML representation of the MachineFunctionInfo.
virtual bool parseMachineFunctionInfo (const yaml::MachineFunctionInfo &, PerFunctionMIParsingState &PFS, SMDiagnostic &Error, SMRange &SourceRange) const
Parse out the target's MachineFunctionInfo from the YAML reprsentation.
template<typename STC >
const STC & getSubtarget (const Function &F) const
This method returns a pointer to the specified type of TargetSubtargetInfo.
const DataLayout createDataLayout () const
Create a DataLayout.
bool isCompatibleDataLayout (const DataLayout &Candidate) const
Test if a DataLayout if compatible with the CodeGen for this target.
unsigned getPointerSize (unsigned AS) const
Get the pointer size for this target.
unsigned getPointerSizeInBits (unsigned AS) const
unsigned getProgramPointerSize () const
unsigned getAllocaPointerSize () const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
Return target specific asm information.
const MCRegisterInfo * getMCRegisterInfo () const
const MCInstrInfo * getMCInstrInfo () const
const MCSubtargetInfo * getMCSubtargetInfo () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
If intrinsic information is available, return it. If not, return null.
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
Returns the code generation relocation model.
CodeModel::Model getCodeModel () const
Returns the code model.
void setCodeModel (CodeModel::Model CM)
Set the code model.
bool isPositionIndependent () const
bool shouldAssumeDSOLocal (const Module &M, const GlobalValue *GV) const
bool useEmulatedTLS () const
Returns true if this target uses emulated TLS.
TLSModel::Model getTLSModel (const GlobalValue *GV) const
Returns the TLS model which should be used for the given global variable.
CodeGenOpt::Level getOptLevel () const
Returns the optimization level: None, Less, Default, or Aggressive.
void setOptLevel (CodeGenOpt::Level Level)
Overrides the optimization level.
void setFastISel (bool Enable)
bool getO0WantsFastISel ()
void setO0WantsFastISel (bool Enable)
void setGlobalISel (bool Enable)
void setGlobalISelAbort (GlobalISelAbortMode Mode)
void setMachineOutliner (bool Enable)
void setSupportsDefaultOutlining (bool Enable)
void setSupportsDebugEntryValues (bool Enable)
void setCFIFixup (bool Enable)
bool getAIXExtendedAltivecABI () const
bool getUniqueSectionNames () const
bool getUniqueBasicBlockSectionNames () const
Return true if unique basic block section names must be generated.
bool getDataSections () const
Return true if data objects should be emitted into their own section, corresponds to -fdata-sections.
bool getFunctionSections () const
Return true if functions should be emitted into their own section, corresponding to -ffunction-sections.
bool getIgnoreXCOFFVisibility () const
Return true if visibility attribute should not be emitted in XCOFF, corresponding to -mignore-xcoff-visibility.
bool getXCOFFTracebackTable () const
Return true if XCOFF traceback table should be emitted, corresponding to -xcoff-traceback-table.
llvm::BasicBlockSection getBBSectionsType () const
If basic blocks should be emitted into their own section, corresponding to -fbasic-block-sections.
const MemoryBuffer * getBBSectionsFuncListBuf () const
Get the list of functions and basic block ids that need unique sections.
void setPGOOption (std::optional< PGOOptions > PGOOpt)
const std::optional< PGOOptions > & getPGOOption () const
virtual unsigned getAssumedAddrSpace (const Value *V) const
If the specified generic pointer could be assumed as a pointer to a specific address space, return that address space.
virtual std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const
If the specified predicate checks whether a generic pointer falls within a specified address space, return that generic pointer and the address space being queried.
TargetIRAnalysis getTargetIRAnalysis () const
Get a TargetIRAnalysis appropriate for the target.
virtual void registerPassBuilderCallbacks (PassBuilder &)
Allow the target to modify the pass pipeline.
virtual void registerDefaultAliasAnalyses (AAManager &)
Allow the target to register alias analyses with the AAManager for use with the new pass manager.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV) const
virtual unsigned getSjLjDataSize () const
virtual unsigned getAddressSpaceForPseudoSourceKind (unsigned Kind) const
getAddressSpaceForPseudoSourceKind - Given the kind of memory (e.g.
Public Attributes
enum llvm::ARMBaseTargetMachine::ARMABI TargetABI
Public Attributes inherited from llvm::TargetMachine
const TargetOptions DefaultOptions
TargetOptions Options
Protected Attributes
std::unique_ptr< TargetLoweringObjectFile > TLOF
bool isLittle
StringMap< std::unique_ptr< ARMSubtarget > > SubtargetMap
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
The Target that this machine was created for.
const DataLayout DL
DataLayout for the target: keep ABI type size and alignment.
Triple TargetTriple
Triple string, CPU name, and target feature strings the TargetMachine instance is created with.
std::string TargetCPU
std::string TargetFS
Reloc::Model RM = Reloc::Static
CodeModel::Model CMModel = CodeModel::Small
CodeGenOpt::Level OptLevel = CodeGenOpt::Default
std::unique_ptr< const MCAsmInfo > AsmInfo
Contains target specific asm information.
std::unique_ptr< const MCRegisterInfo > MRI
std::unique_ptr< const MCInstrInfo > MII
std::unique_ptr< const MCSubtargetInfo > STI
unsigned RequireStructuredCFG: 1
unsigned O0WantsFastISel: 1
std::optional< PGOOptions > PGOOption
Additional Inherited Members
Static Public Member Functions inherited from llvm::TargetMachine
static std::pair< int, int > parseBinutilsVersion (StringRef Version)
Static Public Attributes inherited from llvm::TargetMachine
static constexpr unsigned DefaultSjLjDataSize = 32
The integer bit size to use for SjLj based exception handling.
Protected Member Functions inherited from llvm::LLVMTargetMachine
LLVMTargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Detailed Description
Definition at line 27 of file ARMTargetMachine.h.
Member Enumeration Documentation
ARMABI
enum llvm::ARMBaseTargetMachine::ARMABI
Enumerator
ARM_ABI_UNKNOWN
ARM_ABI_APCS
ARM_ABI_AAPCS
ARM_ABI_AAPCS16
Definition at line 29 of file ARMTargetMachine.h.
Constructor & Destructor Documentation
ARMBaseTargetMachine()
ARMBaseTargetMachine::ARMBaseTargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, const TargetOptions & Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool isLittle)
Create an ARM architecture model.
Definition at line 218 of file ARMTargetMachine.cpp.
References llvm::FloatABI::Default, llvm::Default, llvm::EABI5, llvm::TargetOptions::EABIVersion, llvm::TargetOptions::FloatABIType, llvm::Triple::getEnvironment(), llvm::GNU, llvm::Triple::GNUEABI, llvm::Triple::GNUEABIHF, llvm::FloatABI::Hard, llvm::LLVMTargetMachine::initAsmInfo(), llvm::Triple::isOSDarwin(), llvm::Triple::isOSWindows(), isTargetHardFloat(), llvm::Triple::MuslEABI, llvm::Triple::MuslEABIHF, llvm::TargetOptions::NoTrapAfterNoreturn, llvm::TargetMachine::Options, llvm::TargetMachine::setMachineOutliner(), llvm::TargetMachine::setSupportsDebugEntryValues(), llvm::TargetMachine::setSupportsDefaultOutlining(), llvm::FloatABI::Soft, llvm::TargetMachine::TargetTriple, llvm::TargetOptions::TrapUnreachable, and llvm::Unknown.
~ARMBaseTargetMachine()
ARMBaseTargetMachine::~ARMBaseTargetMachine () override default
Member Function Documentation
createMachineFunctionInfo()
MachineFunctionInfo * ARMBaseTargetMachine::createMachineFunctionInfo (BumpPtrAllocator & Allocator, const Function & F, const TargetSubtargetInfo * STI) const override virtual
Create the target's instance of MachineFunctionInfo.
Reimplemented from llvm::TargetMachine.
Definition at line 269 of file ARMTargetMachine.cpp.
References F, and llvm::TargetMachine::STI.
createPassConfig()
arm execution domain ARM Execution Domain false TargetPassConfig * ARMBaseTargetMachine::createPassConfig (PassManagerBase & PM) override virtual
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 407 of file ARMTargetMachine.cpp.
getObjFileLowering()
TargetLoweringObjectFile * llvm::ARMBaseTargetMachine::getObjFileLowering () const inline override virtual
Reimplemented from llvm::TargetMachine.
Definition at line 61 of file ARMTargetMachine.h.
References TLOF.
getSubtargetImpl() [1/2]
const ARMSubtarget * llvm::ARMBaseTargetMachine::getSubtargetImpl () const delete
getSubtargetImpl() [2/2]
const ARMSubtarget * ARMBaseTargetMachine::getSubtargetImpl (const Function &) const override virtual
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 277 of file ARMTargetMachine.cpp.
References F, llvm::Attribute::getValueAsString(), I, isLittle, llvm::Attribute::isValid(), llvm::TargetMachine::resetTargetOptions(), llvm::StringRef::str(), SubtargetMap, llvm::TargetMachine::TargetCPU, llvm::TargetMachine::TargetFS, and llvm::TargetMachine::TargetTriple.
getTargetTransformInfo()
TargetTransformInfo ARMBaseTargetMachine::getTargetTransformInfo (const Function & F) const override virtual
Return a TargetTransformInfo for a given function.
The returned TargetTransformInfo is specialized to the subtarget corresponding to F.
Reimplemented from llvm::TargetMachine.
Definition at line 321 of file ARMTargetMachine.cpp.
References F.
isLittleEndian()
bool llvm::ARMBaseTargetMachine::isLittleEndian () const inline
Definition at line 54 of file ARMTargetMachine.h.
References isLittle.
isNoopAddrSpaceCast()
bool llvm::ARMBaseTargetMachine::isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const inline override virtual
Returns true if a cast between SrcAS and DestAS is a noop.
Reimplemented from llvm::TargetMachine.
Definition at line 82 of file ARMTargetMachine.h.
isTargetHardFloat()
bool llvm::ARMBaseTargetMachine::isTargetHardFloat () const inline
Definition at line 65 of file ARMTargetMachine.h.
References ARM_ABI_AAPCS16, llvm::Triple::ARMSubArch_v7em, llvm::Triple::EABIHF, llvm::Triple::getEnvironment(), llvm::Triple::getSubArch(), llvm::Triple::GNUEABIHF, llvm::Triple::isOSBinFormatMachO(), llvm::Triple::isOSWindows(), llvm::Triple::MuslEABIHF, TargetABI, and llvm::TargetMachine::TargetTriple.
Referenced by ARMBaseTargetMachine(), and llvm::ARMSubtarget::isTargetHardFloat().
targetSchedulesPostRAScheduling()
bool llvm::ARMBaseTargetMachine::targetSchedulesPostRAScheduling () const inline override virtual
True if subtarget inserts the final scheduling pass on its own.
Branch relaxation, which must happen after block placement, can on some targets (e.g. SystemZ) expose additional post-RA scheduling opportunities.
Reimplemented from llvm::TargetMachine.
Definition at line 75 of file ARMTargetMachine.h.
Member Data Documentation
isLittle
bool llvm::ARMBaseTargetMachine::isLittle protected
Definition at line 38 of file ARMTargetMachine.h.
Referenced by getSubtargetImpl(), and isLittleEndian().
SubtargetMap
StringMap<std::unique_ptr<ARMSubtarget> > llvm::ARMBaseTargetMachine::SubtargetMap mutable protected
Definition at line 39 of file ARMTargetMachine.h.
Referenced by getSubtargetImpl().
TargetABI
enum llvm::ARMBaseTargetMachine::ARMABI llvm::ARMBaseTargetMachine::TargetABI
Referenced by llvm::ARMSubtarget::isAAPCS16_ABI(), llvm::ARMSubtarget::isAAPCS_ABI(), llvm::ARMSubtarget::isAPCS_ABI(), and isTargetHardFloat().
TLOF
std::unique_ptr<TargetLoweringObjectFile> llvm::ARMBaseTargetMachine::TLOF protected
Definition at line 37 of file ARMTargetMachine.h.
Referenced by getObjFileLowering().
The documentation for this class was generated from the following files:
lib/Target/ARM/ARMTargetMachine.h
lib/Target/ARM/ARMTargetMachine.cpp