LLVM: lib/ObjectYAML/CodeViewYAMLDebugSections.cpp File Reference
CodeViewYAMLDebugSections.cpp File Reference
#include "llvm/ObjectYAML/CodeViewYAMLDebugSections.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/DebugInfo/CodeView/CodeViewError.h"
#include "llvm/DebugInfo/CodeView/DebugChecksumsSubsection.h"
#include "llvm/DebugInfo/CodeView/DebugCrossExSubsection.h"
#include "llvm/DebugInfo/CodeView/DebugCrossImpSubsection.h"
#include "llvm/DebugInfo/CodeView/DebugFrameDataSubsection.h"
#include "llvm/DebugInfo/CodeView/DebugInlineeLinesSubsection.h"
#include "llvm/DebugInfo/CodeView/DebugLinesSubsection.h"
#include "llvm/DebugInfo/CodeView/DebugStringTableSubsection.h"
#include "llvm/DebugInfo/CodeView/DebugSubsection.h"
#include "llvm/DebugInfo/CodeView/DebugSubsectionVisitor.h"
#include "llvm/DebugInfo/CodeView/DebugSymbolRVASubsection.h"
#include "llvm/DebugInfo/CodeView/DebugSymbolsSubsection.h"
#include "llvm/DebugInfo/CodeView/Line.h"
#include "llvm/DebugInfo/CodeView/StringsAndChecksums.h"
#include "llvm/DebugInfo/CodeView/TypeIndex.h"
#include "llvm/ObjectYAML/CodeViewYAMLSymbols.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/BinaryStreamReader.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/YAMLTraits.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <memory>
#include <string>
#include <tuple>
#include <vector>
Classes
struct llvm::CodeViewYAML::detail::YAMLSubsectionBase
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::CodeViewYAML
namespace llvm::CodeViewYAML::detail
Functions
static Expected< SourceFileChecksumEntry > convertOneChecksum (const DebugStringTableSubsectionRef &Strings, const FileChecksumEntry &CS)
static Expected< StringRef > getFileName (const DebugStringTableSubsectionRef &Strings, const DebugChecksumsSubsectionRef &Checksums, uint32_t FileID)
Function Documentation
convertOneChecksum()
static Expected< SourceFileChecksumEntry > convertOneChecksum (const DebugStringTableSubsectionRef & Strings, const FileChecksumEntry & CS) static
Definition at line 541 of file CodeViewYAMLDebugSections.cpp.
References llvm::codeview::FileChecksumEntry::Checksum, llvm::codeview::FileChecksumEntry::FileNameOffset, and llvm::codeview::FileChecksumEntry::Kind.
getFileName()
static Expected< StringRef > getFileName (const DebugStringTableSubsectionRef & Strings, const DebugChecksumsSubsectionRef & Checksums, uint32_t FileID) static
Definition at line 555 of file CodeViewYAMLDebugSections.cpp.
References llvm::VarStreamArray< ValueType, Extractor >::at(), llvm::VarStreamArray< ValueType, Extractor >::end(), llvm::codeview::DebugChecksumsSubsectionRef::getArray(), and llvm::Offset.
Referenced by llvm::object::WindowsResource::getHeadEntry().