LLVM: lib/Target/CSKY/CSKYInstrInfo.cpp File Reference
CSKYInstrInfo.cpp File Reference
#include "CSKYInstrInfo.h"
#include "CSKYConstantPoolValue.h"
#include "CSKYMachineFunctionInfo.h"
#include "CSKYTargetMachine.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/MC/MCContext.h"
#include "CSKYGenInstrInfo.inc"
Macros
#define DEBUG_TYPE "csky-instr-info"
#define GET_INSTRINFO_CTOR_DTOR
Functions
static void parseCondBranch (MachineInstr &LastInst, MachineBasicBlock *&Target, SmallVectorImpl< MachineOperand > &Cond)
static unsigned getOppositeBranchOpc (unsigned Opcode)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "csky-instr-info"
Definition at line 20 of file CSKYInstrInfo.cpp.
GET_INSTRINFO_CTOR_DTOR
#define GET_INSTRINFO_CTOR_DTOR
Definition at line 24 of file CSKYInstrInfo.cpp.
Function Documentation
getOppositeBranchOpc()
static unsigned getOppositeBranchOpc (unsigned Opcode) static
Definition at line 190 of file CSKYInstrInfo.cpp.
References llvm_unreachable.
Referenced by llvm::CSKYInstrInfo::reverseBranchCondition(), and llvm::LoongArchInstrInfo::reverseBranchCondition().
parseCondBranch()
static void parseCondBranch (MachineInstr & LastInst, MachineBasicBlock *& Target, SmallVectorImpl< MachineOperand > & Cond) static
Definition at line 35 of file CSKYInstrInfo.cpp.
References assert(), Cond, llvm::MachineOperand::CreateImm(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MCInstrDesc::isConditionalBranch().