LLVM: lib/Analysis/DomPrinter.cpp File Reference
DomPrinter.cpp File Reference
#include "llvm/Analysis/DomPrinter.h"
#include "llvm/Analysis/DOTGraphTraitsPass.h"
#include "llvm/Analysis/PostDominators.h"
#include "llvm/InitializePasses.h"
Functions
INITIALIZE_PASS(DomViewerWrapperPass, "view-dom", "View dominance tree of function", false, false) char DomOnlyViewerWrapperPass INITIALIZE_PASS(DomOnlyViewerWrapperPass, "view-dom-only", "View dominance tree of function (with no function bodies)", false, false) char PostDomViewerWrapperPass INITIALIZE_PASS(PostDomViewerWrapperPass, "view-postdom", "View postdominance tree of function", false, false) char PostDomOnlyViewerWrapperPass INITIALIZE_PASS (PostDomOnlyViewerWrapperPass, "view-postdom-only", "View postdominance tree of function " "(with no function bodies)", false, false) namespace
INITIALIZE_PASS(DomPrinterWrapperPass, "dot-dom", "Print dominance tree of function to 'dot' file", false, false) char DomOnlyPrinterWrapperPass INITIALIZE_PASS(DomOnlyPrinterWrapperPass, "dot-dom-only", "Print dominance tree of function to 'dot' file " "(with no function bodies)", false, false) char PostDomPrinterWrapperPass INITIALIZE_PASS(PostDomPrinterWrapperPass, "dot-postdom", "Print postdominance tree of function to 'dot' file", false, false) char PostDomOnlyPrinterWrapperPass INITIALIZE_PASS (PostDomOnlyPrinterWrapperPass, "dot-postdom-only", "Print postdominance tree of function to 'dot' file " "(with no function bodies)", false, false) FunctionPass *llvm
Function Documentation
INITIALIZE_PASS() [1/2]
INITIALIZE_PASS(DomPrinterWrapperPass, "dot-dom", "Print dominance tree of function to 'dot' file", false, false) char DomOnlyPrinterWrapperPass INITIALIZE_PASS(DomOnlyPrinterWrapperPass, "dot-dom-only", "Print dominance tree of function to 'dot' file " "(with no function bodies)", false, false) char PostDomPrinterWrapperPass INITIALIZE_PASS(PostDomPrinterWrapperPass, "dot-postdom", "Print postdominance tree of function to 'dot' file", false, false) char PostDomOnlyPrinterWrapperPass INITIALIZE_PASS (PostDomOnlyPrinterWrapperPass , "dot-postdom-only" , "Print postdominance tree of function to 'dot' file " "(with no function bodies)" , false , false)
Definition at line 205 of file DomPrinter.cpp.
INITIALIZE_PASS() [2/2]
INITIALIZE_PASS(DomViewerWrapperPass, "view-dom", "View dominance tree of function", false, false) char DomOnlyViewerWrapperPass INITIALIZE_PASS(DomOnlyViewerWrapperPass, "view-dom-only", "View dominance tree of function (with no function bodies)", false, false) char PostDomViewerWrapperPass INITIALIZE_PASS(PostDomViewerWrapperPass, "view-postdom", "View postdominance tree of function", false, false) char PostDomOnlyViewerWrapperPass INITIALIZE_PASS (PostDomOnlyViewerWrapperPass , "view-postdom-only" , "View postdominance tree of function " "(with no function bodies)" , false , false)
Definition at line 127 of file DomPrinter.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::ilist_node_impl< OptionsT >::ilist_node_impl(), llvm::initializeDomOnlyPrinterWrapperPassPass(), llvm::initializeDomPrinterWrapperPassPass(), llvm::initializePostDomOnlyPrinterWrapperPassPass(), and llvm::initializePostDomPrinterWrapperPassPass().