LLVM: lib/Target/DirectX/DXILWriter/DXILBitcodeWriter.cpp File Reference
DXILBitcodeWriter.cpp File Reference
#include "DXILBitcodeWriter.h"
#include "DXILValueEnumerator.h"
#include "DirectXIRPasses/PointerTypeAnalysis.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Bitcode/BitcodeCommon.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Bitcode/LLVMBitCodes.h"
#include "llvm/Bitstream/BitCodes.h"
#include "llvm/Bitstream/BitstreamWriter.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalIFunc.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ModuleSummaryIndex.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/UseListOrder.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Object/IRSymtab.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ModRef.h"
#include "llvm/Support/SHA1.h"
#include "llvm/IR/Metadata.def"
Classes
class llvm::dxil::DXILBitcodeWriter
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::dxil
Macros
#define HANDLE_MDNODE_LEAF(CLASS) CLASS##AbbrevID,
#define HANDLE_MDNODE_LEAF(CLASS) unsigned CLASS##Abbrev = 0;
#define HANDLE_MDNODE_LEAF(CLASS)
Enumerations
enum llvm::dxil::MetadataAbbrev : unsigned { llvm::dxil::LastPlusOne }
Functions
static uint64_t rotateSign (APInt Val)
static uint64_t rotateSign (DISubrange::BoundType Val)
Macro Definition Documentation
HANDLE_MDNODE_LEAF [1/3]
#define HANDLE_MDNODE_LEAF (CLASS) CLASS##AbbrevID,
Definition at line 60 of file DXILBitcodeWriter.cpp.
HANDLE_MDNODE_LEAF [2/3]
#define HANDLE_MDNODE_LEAF (CLASS) unsigned CLASS##Abbrev = 0;
Definition at line 60 of file DXILBitcodeWriter.cpp.
HANDLE_MDNODE_LEAF [3/3]
#define HANDLE_MDNODE_LEAF (CLASS)
Value:
  case Metadata::CLASS##Kind:                                                  \
    if (MDAbbrevs)                                                             \
      write##CLASS(cast<CLASS>(N), Record,                                     \
                   (*MDAbbrevs)[MetadataAbbrev::CLASS##AbbrevID]);             \
    else                                                                       \
      write##CLASS(cast<CLASS>(N), Record, CLASS##Abbrev);                     \
    continue;
Definition at line 60 of file DXILBitcodeWriter.cpp.
Function Documentation
rotateSign() [1/2]
static uint64_t rotateSign (APInt Val) static
Definition at line 1399 of file DXILBitcodeWriter.cpp.
References llvm::APInt::getSExtValue(), and I.
Referenced by rotateSign().
rotateSign() [2/2]
static uint64_t rotateSign (DISubrange::BoundType Val) static
Definition at line 1405 of file DXILBitcodeWriter.cpp.
References llvm::ConstantInt::getValue(), and rotateSign().