LLVM: lib/ObjectYAML/ELFEmitter.cpp File Reference
ELFEmitter.cpp File Reference
The ELF component of yaml2obj.
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/StringTableBuilder.h"
#include "llvm/Object/ELFObjectFile.h"
#include "llvm/Object/ELFTypes.h"
#include "llvm/ObjectYAML/DWARFEmitter.h"
#include "llvm/ObjectYAML/DWARFYAML.h"
#include "llvm/ObjectYAML/ELFYAML.h"
#include "llvm/ObjectYAML/yaml2obj.h"
#include "llvm/Support/EndianStream.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/WithColor.h"
#include "llvm/Support/YAMLTraits.h"
#include "llvm/Support/raw_ostream.h"
#include <optional>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::yaml
Functions
template<class T >
static size_t arrayDataSize (ArrayRef< T > A)
template<class T >
static void writeArrayData (raw_ostream &OS, ArrayRef< T > A)
template<class T >
static void zero (T &Obj)
template<class ELFT >
static void overrideFields (ELFYAML::Section *From, typename ELFT::Shdr &To)
static uint64_t writeContent (ContiguousBlobAccumulator &CBA, const std::optional< yaml::BinaryRef > &Content, const std::optional< llvm::yaml::Hex64 > &Size)
static StringRef getDefaultLinkSec (unsigned SecType)
static size_t findFirstNonGlobal (ArrayRef< ELFYAML::Symbol > Symbols)
static bool shouldEmitDWARF (DWARFYAML::Data &DWARF, StringRef Name)
template<class ELFT >
Expected< uint64_t > emitDWARF (typename ELFT::Shdr &SHeader, StringRef Name, const DWARFYAML::Data &DWARF, ContiguousBlobAccumulator &CBA)
static bool isMips64EL (const ELFYAML::Object &Obj)
bool llvm::yaml::yaml2elf (ELFYAML::Object &Doc, raw_ostream &Out, ErrorHandler EH, uint64_t MaxSize)
Variables
constexpr char SuffixStart = '('
constexpr char SuffixEnd = ')'
Detailed Description
The ELF component of yaml2obj.
Definition in file ELFEmitter.cpp.
Function Documentation
arrayDataSize()
template<class T > static size_t arrayDataSize (ArrayRef< T > A) static
Definition at line 328 of file ELFEmitter.cpp.
References A, and T.
Referenced by writeArrayData().
emitDWARF()
template<class ELFT > Expected< uint64_t > emitDWARF (typename ELFT::Shdr & SHeader, StringRef Name, const DWARFYAML::Data & DWARF, ContiguousBlobAccumulator & CBA)
Definition at line 1074 of file ELFEmitter.cpp.
References llvm::DWARFYAML::getDWARFEmitterByName, and Name.
findFirstNonGlobal()
static size_t findFirstNonGlobal (ArrayRef< ELFYAML::Symbol > Symbols) static
Definition at line 929 of file ELFEmitter.cpp.
References I, and llvm::ELF::STB_LOCAL.
getDefaultLinkSec()
static StringRef getDefaultLinkSec (unsigned SecType) static
Definition at line 734 of file ELFEmitter.cpp.
References llvm::ELF::SHT_DYNSYM, llvm::ELF::SHT_GNU_HASH, llvm::ELF::SHT_GNU_verdef, llvm::ELF::SHT_GNU_verneed, llvm::ELF::SHT_GNU_versym, llvm::ELF::SHT_GROUP, llvm::ELF::SHT_HASH, llvm::ELF::SHT_LLVM_ADDRSIG, llvm::ELF::SHT_LLVM_CALL_GRAPH_PROFILE, llvm::ELF::SHT_REL, llvm::ELF::SHT_RELA, and llvm::ELF::SHT_SYMTAB.
isMips64EL()
static bool isMips64EL (const ELFYAML::Object & Obj) static
Definition at line 1260 of file ELFEmitter.cpp.
References llvm::ELFYAML::FileHeader::Class, llvm::ELFYAML::FileHeader::Data, llvm::ELF::ELFCLASS64, llvm::ELF::ELFDATA2LSB, llvm::ELF::EM_MIPS, llvm::ELFYAML::Object::getMachine(), and llvm::ELFYAML::Object::Header.
Referenced by llvm::object::ELFFile< ELFT >::getRelocationSymbol(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::getRInfo(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::getRInfo(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::getSymbol(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::getSymbol(), llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, false >, false >::getType(), and llvm::object::Elf_Rel_Impl< ELFType< TargetEndianness, true >, false >::getType().
overrideFields()
template<class ELFT > static void overrideFields (ELFYAML::Section * From, typename ELFT::Shdr & To) static
Definition at line 634 of file ELFEmitter.cpp.
References From.
shouldEmitDWARF()
static bool shouldEmitDWARF (DWARFYAML::Data & DWARF, StringRef Name) static
Definition at line 1068 of file ELFEmitter.cpp.
References llvm::DWARFYAML::Data::getNonEmptySectionNames(), and Name.
writeArrayData()
template<class T > static void writeArrayData (raw_ostream & OS, ArrayRef< T > A) static
Definition at line 332 of file ELFEmitter.cpp.
References A, arrayDataSize(), and llvm::raw_ostream::write().
writeContent()
static uint64_t writeContent (ContiguousBlobAccumulator & CBA, const std::optional< yaml::BinaryRef > & Content, const std::optional< llvm::yaml::Hex64 > & Size) static
Definition at line 718 of file ELFEmitter.cpp.
References Content, and Size.
zero()
template<class T > static void zero (T & Obj) static
Definition at line 336 of file ELFEmitter.cpp.
Referenced by llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNSWNeg(), llvm::BinaryOperator::CreateNSWNeg(), llvm::BinaryOperator::CreateNUWNeg(), and llvm::BinaryOperator::CreateNUWNeg().
Variable Documentation
SuffixEnd
constexpr char SuffixEnd = ')' constexpr
Definition at line 686 of file ELFEmitter.cpp.
Referenced by llvm::ELFYAML::appendUniqueSuffix(), llvm::ELFYAML::dropUniqueSuffix(), and parseRD().
SuffixStart
constexpr char SuffixStart = '(' constexpr
Definition at line 685 of file ELFEmitter.cpp.
Referenced by llvm::ELFYAML::appendUniqueSuffix(), and llvm::ELFYAML::dropUniqueSuffix().