LLVM: Contexts
Contexts
LLVM-C: C interface to LLVM » Core
Typedefs
typedef void(* LLVMDiagnosticHandler) (LLVMDiagnosticInfoRef, void *)
typedef void(* LLVMYieldCallback) (LLVMContextRef, void *)
Functions
LLVMContextRef LLVMContextCreate (void)
Create a new context.
LLVMContextRef LLVMGetGlobalContext (void)
Obtain the global context instance.
void LLVMContextSetDiagnosticHandler (LLVMContextRef C, LLVMDiagnosticHandler Handler, void *DiagnosticContext)
Set the diagnostic handler for this context.
LLVMDiagnosticHandler LLVMContextGetDiagnosticHandler (LLVMContextRef C)
Get the diagnostic handler of this context.
void * LLVMContextGetDiagnosticContext (LLVMContextRef C)
Get the diagnostic context of this context.
void LLVMContextSetYieldCallback (LLVMContextRef C, LLVMYieldCallback Callback, void *OpaqueHandle)
Set the yield callback function for this context.
LLVMBool LLVMContextShouldDiscardValueNames (LLVMContextRef C)
Retrieve whether the given context is set to discard all value names.
void LLVMContextSetDiscardValueNames (LLVMContextRef C, LLVMBool Discard)
Set whether the given context discards all value names.
void LLVMContextSetOpaquePointers (LLVMContextRef C, LLVMBool OpaquePointers)
Set whether the given context is in opaque pointer mode.
void LLVMContextDispose (LLVMContextRef C)
Destroy a context instance.
char * LLVMGetDiagInfoDescription (LLVMDiagnosticInfoRef DI)
Return a string representation of the DiagnosticInfo.
LLVMDiagnosticSeverity LLVMGetDiagInfoSeverity (LLVMDiagnosticInfoRef DI)
Return an enum LLVMDiagnosticSeverity.
unsigned LLVMGetMDKindIDInContext (LLVMContextRef C, const char *Name, unsigned SLen)
unsigned LLVMGetMDKindID (const char *Name, unsigned SLen)
unsigned LLVMGetEnumAttributeKindForName (const char *Name, size_t SLen)
Return an unique id given the name of a enum attribute, or 0 if no attribute by that name exists.
unsigned LLVMGetLastEnumAttributeKind (void)
LLVMAttributeRef LLVMCreateEnumAttribute (LLVMContextRef C, unsigned KindID, uint64_t Val)
Create an enum attribute.
unsigned LLVMGetEnumAttributeKind (LLVMAttributeRef A)
Get the unique id corresponding to the enum attribute passed as argument.
uint64_t LLVMGetEnumAttributeValue (LLVMAttributeRef A)
Get the enum attribute's value.
LLVMAttributeRef LLVMCreateTypeAttribute (LLVMContextRef C, unsigned KindID, LLVMTypeRef type_ref)
Create a type attribute.
LLVMTypeRef LLVMGetTypeAttributeValue (LLVMAttributeRef A)
Get the type attribute's value.
LLVMAttributeRef LLVMCreateStringAttribute (LLVMContextRef C, const char *K, unsigned KLength, const char *V, unsigned VLength)
Create a string attribute.
const char * LLVMGetStringAttributeKind (LLVMAttributeRef A, unsigned *Length)
Get the string attribute's kind.
const char * LLVMGetStringAttributeValue (LLVMAttributeRef A, unsigned *Length)
Get the string attribute's value.
LLVMBool LLVMIsEnumAttribute (LLVMAttributeRef A)
Check for the different types of attributes.
LLVMBool LLVMIsStringAttribute (LLVMAttributeRef A)
LLVMBool LLVMIsTypeAttribute (LLVMAttributeRef A)
LLVMTypeRef LLVMGetTypeByName2 (LLVMContextRef C, const char *Name)
Obtain a Type from a context by its registered name.
Detailed Description
Contexts are execution states for the core LLVM IR system.
Most types are tied to a context instance. Multiple contexts can exist simultaneously. A single context is not thread safe. However, different contexts can execute on different threads simultaneously.
Typedef Documentation
LLVMDiagnosticHandler
typedef void(* LLVMDiagnosticHandler) (LLVMDiagnosticInfoRef, void *)
Definition at line 511 of file Core.h.
LLVMYieldCallback
typedef void(* LLVMYieldCallback) (LLVMContextRef, void *)
Definition at line 512 of file Core.h.
Function Documentation
LLVMContextCreate()
LLVMContextRef LLVMContextCreate (void)
Create a new context.
Every call to this function should be paired with a call to LLVMContextDispose() or the context will leak memory.
Definition at line 93 of file Core.cpp.
References llvm::wrap().
LLVMContextDispose()
void LLVMContextDispose (LLVMContextRef C)
Destroy a context instance.
This should be called for every call to LLVMContextCreate() or memory will be leaked.
Definition at line 136 of file Core.cpp.
References llvm::CallingConv::C, and llvm::unwrap().
LLVMContextGetDiagnosticContext()
void * LLVMContextGetDiagnosticContext (LLVMContextRef C)
Get the diagnostic context of this context.
Definition at line 113 of file Core.cpp.
References llvm::CallingConv::C, and llvm::unwrap().
LLVMContextGetDiagnosticHandler()
LLVMDiagnosticHandler LLVMContextGetDiagnosticHandler (LLVMContextRef C)
Get the diagnostic handler of this context.
Definition at line 108 of file Core.cpp.
References llvm::CallingConv::C, LLVM_EXTENSION, and llvm::unwrap().
LLVMContextSetDiagnosticHandler()
void LLVMContextSetDiagnosticHandler (LLVMContextRef C, LLVMDiagnosticHandler Handler, void * DiagnosticContext)
Set the diagnostic handler for this context.
Definition at line 99 of file Core.cpp.
References llvm::CallingConv::C, LLVM_EXTENSION, and llvm::unwrap().
LLVMContextSetDiscardValueNames()
void LLVMContextSetDiscardValueNames (LLVMContextRef C, LLVMBool Discard)
Set whether the given context discards all value names.
If true, only the names of GlobalValue objects will be available in the IR. This can be used to save memory and runtime, especially in release mode.
See also
LLVMContext::setDiscardValueNames()
Definition at line 128 of file Core.cpp.
References llvm::CallingConv::C, and llvm::unwrap().
LLVMContextSetOpaquePointers()
void LLVMContextSetOpaquePointers (LLVMContextRef C, LLVMBool OpaquePointers)
Set whether the given context is in opaque pointer mode.
See also
LLVMContext::setOpaquePointers()
Definition at line 132 of file Core.cpp.
References llvm::CallingConv::C, and llvm::unwrap().
LLVMContextSetYieldCallback()
void LLVMContextSetYieldCallback (LLVMContextRef C, LLVMYieldCallback Callback, void * OpaqueHandle)
Set the yield callback function for this context.
See also
LLVMContext::setYieldCallback()
Definition at line 117 of file Core.cpp.
References llvm::CallingConv::C, LLVM_EXTENSION, and llvm::unwrap().
LLVMContextShouldDiscardValueNames()
LLVMBool LLVMContextShouldDiscardValueNames (LLVMContextRef C)
Retrieve whether the given context is set to discard all value names.
See also
LLVMContext::shouldDiscardValueNames()
Definition at line 124 of file Core.cpp.
References llvm::CallingConv::C, and llvm::unwrap().
LLVMCreateEnumAttribute()
LLVMAttributeRef LLVMCreateEnumAttribute (LLVMContextRef C, unsigned KindID, uint64_t Val)
Create an enum attribute.
Definition at line 157 of file Core.cpp.
References llvm::CallingConv::C, llvm::unwrap(), and llvm::wrap().
LLVMCreateStringAttribute()
LLVMAttributeRef LLVMCreateStringAttribute (LLVMContextRef C, const char * K, unsigned KLength, const char * V, unsigned VLength)
Create a string attribute.
Definition at line 187 of file Core.cpp.
References llvm::CallingConv::C, llvm::unwrap(), and llvm::wrap().
LLVMCreateTypeAttribute()
LLVMAttributeRef LLVMCreateTypeAttribute (LLVMContextRef C, unsigned KindID, LLVMTypeRef type_ref)
Create a type attribute.
Definition at line 175 of file Core.cpp.
References llvm::CallingConv::C, llvm::unwrap(), and llvm::wrap().
LLVMGetDiagInfoDescription()
char * LLVMGetDiagInfoDescription (LLVMDiagnosticInfoRef DI)
Return a string representation of the DiagnosticInfo.
Use LLVMDisposeMessage to free the string.
See also
DiagnosticInfo::print()
Definition at line 221 of file Core.cpp.
References llvm::raw_ostream::flush(), LLVMCreateMessage(), and llvm::unwrap().
LLVMGetDiagInfoSeverity()
LLVMDiagnosticSeverity LLVMGetDiagInfoSeverity (LLVMDiagnosticInfoRef DI)
Return an enum LLVMDiagnosticSeverity.
See also
DiagnosticInfo::getSeverity()
Definition at line 232 of file Core.cpp.
References llvm::DS_Note, llvm::DS_Remark, llvm::DS_Warning, LLVMDSError, LLVMDSNote, LLVMDSRemark, LLVMDSWarning, and llvm::unwrap().
LLVMGetEnumAttributeKind()
unsigned LLVMGetEnumAttributeKind (LLVMAttributeRef A)
Get the unique id corresponding to the enum attribute passed as argument.
Definition at line 164 of file Core.cpp.
References A, llvm::Attribute::getKindAsEnum(), and llvm::unwrap().
LLVMGetEnumAttributeKindForName()
unsigned LLVMGetEnumAttributeKindForName (const char * Name, size_t SLen)
Return an unique id given the name of a enum attribute, or 0 if no attribute by that name exists.
See http://llvm.org/docs/LangRef.html#parameter-attributes and http://llvm.org/docs/LangRef.html#function-attributes for the list of available attributes.
NB: Attribute names and/or id are subject to change without going through the C API deprecation cycle.
Definition at line 149 of file Core.cpp.
References Name.
LLVMGetEnumAttributeValue()
uint64_t LLVMGetEnumAttributeValue (LLVMAttributeRef A)
Get the enum attribute's value.
0 is returned if none exists.
Definition at line 168 of file Core.cpp.
References A, and llvm::unwrap().
LLVMGetGlobalContext()
LLVMContextRef LLVMGetGlobalContext (void)
Obtain the global context instance.
Definition at line 97 of file Core.cpp.
References getGlobalContext(), and llvm::wrap().
Referenced by LLVMGetBitcodeModule(), LLVMGetBitcodeModule2(), LLVMParseBitcode(), and LLVMParseBitcode2().
LLVMGetLastEnumAttributeKind()
unsigned LLVMGetLastEnumAttributeKind (void)
Definition at line 153 of file Core.cpp.
LLVMGetMDKindID()
unsigned LLVMGetMDKindID (const char * Name, unsigned SLen)
Definition at line 145 of file Core.cpp.
References LLVMGetGlobalContext(), LLVMGetMDKindIDInContext(), and Name.
LLVMGetMDKindIDInContext()
unsigned LLVMGetMDKindIDInContext (LLVMContextRef C, const char * Name, unsigned SLen)
Definition at line 140 of file Core.cpp.
References llvm::CallingConv::C, Name, and llvm::unwrap().
Referenced by LLVMGetMDKindID().
LLVMGetStringAttributeKind()
const char * LLVMGetStringAttributeKind (LLVMAttributeRef A, unsigned * Length)
Get the string attribute's kind.
Definition at line 194 of file Core.cpp.
References A, llvm::Attribute::getKindAsString(), llvm::Length, llvm::StringRef::size(), and llvm::unwrap().
LLVMGetStringAttributeValue()
const char * LLVMGetStringAttributeValue (LLVMAttributeRef A, unsigned * Length)
Get the string attribute's value.
Definition at line 201 of file Core.cpp.
References A, llvm::Attribute::getValueAsString(), llvm::Length, llvm::StringRef::size(), and llvm::unwrap().
LLVMGetTypeAttributeValue()
LLVMTypeRef LLVMGetTypeAttributeValue (LLVMAttributeRef A)
Get the type attribute's value.
Definition at line 182 of file Core.cpp.
References A, llvm::unwrap(), and llvm::wrap().
LLVMGetTypeByName2()
LLVMTypeRef LLVMGetTypeByName2 (LLVMContextRef C, const char * Name)
Obtain a Type from a context by its registered name.
Definition at line 777 of file Core.cpp.
References llvm::CallingConv::C, llvm::StructType::getTypeByName(), Name, llvm::unwrap(), and llvm::wrap().
LLVMIsEnumAttribute()
LLVMBool LLVMIsEnumAttribute (LLVMAttributeRef A)
Check for the different types of attributes.
Definition at line 208 of file Core.cpp.
References A, and llvm::unwrap().
LLVMIsStringAttribute()
LLVMBool LLVMIsStringAttribute (LLVMAttributeRef A)
Definition at line 213 of file Core.cpp.
References A, llvm::Attribute::isStringAttribute(), and llvm::unwrap().
LLVMIsTypeAttribute()
LLVMBool LLVMIsTypeAttribute (LLVMAttributeRef A)
Definition at line 217 of file Core.cpp.
References A, llvm::Attribute::isTypeAttribute(), and llvm::unwrap().