LLVM: lib/Target/Hexagon/HexagonISelDAGToDAG.cpp File Reference
HexagonISelDAGToDAG.cpp File Reference
#include "HexagonISelDAGToDAG.h"
#include "Hexagon.h"
#include "HexagonISelLowering.h"
#include "HexagonMachineFunctionInfo.h"
#include "HexagonTargetMachine.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsHexagon.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "HexagonGenDAGISel.inc"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "hexagon-isel"
#define PASS_NAME "Hexagon DAG->DAG Pattern Instruction Selection"
#define GET_DAGISEL_BODY HexagonDAGToDAGISel
Functions
FunctionPass * llvm::createHexagonISelDag (HexagonTargetMachine &TM, CodeGenOpt::Level OptLevel)
createHexagonISelDag - This pass converts a legalized DAG into a Hexagon-specific DAG, ready for instruction scheduling.
static bool isMemOPCandidate (SDNode *I, SDNode *U)
static bool isOpcodeHandled (const SDNode *N)
static unsigned getPowerOf2Factor (SDValue Val)
static bool willShiftRightEliminate (SDValue V, unsigned Amount)
static bool isTargetConstant (const SDValue &V)
Variables
static cl::opt< bool > EnableAddressRebalancing ("isel-rebalance-addr", cl::Hidden, cl::init(true), cl::desc("Rebalance address calculation trees to improve " "instruction selection"))
static cl::opt< bool > RebalanceOnlyForOptimizations ("rebalance-only-opt", cl::Hidden, cl::init(false), cl::desc("Rebalance address tree only if this allows optimizations"))
static cl::opt< bool > RebalanceOnlyImbalancedTrees ("rebalance-only-imbal", cl::Hidden, cl::init(false), cl::desc("Rebalance address tree only if it is imbalanced"))
static cl::opt< bool > CheckSingleUse ("hexagon-isel-su", cl::Hidden, cl::init(true), cl::desc("Enable checking of SDNode's single-use status"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "hexagon-isel"
Definition at line 27 of file HexagonISelDAGToDAG.cpp.
GET_DAGISEL_BODY
#define GET_DAGISEL_BODY HexagonDAGToDAGISel
Definition at line 55 of file HexagonISelDAGToDAG.cpp.
PASS_NAME
#define PASS_NAME "Hexagon DAG->DAG Pattern Instruction Selection"
Definition at line 28 of file HexagonISelDAGToDAG.cpp.
Function Documentation
getPowerOf2Factor()
static unsigned getPowerOf2Factor (SDValue Val) static
Returns
the value x for which 2^x is a factor of Val
Definition at line 1861 of file HexagonISelDAGToDAG.cpp.
References llvm::CallingConv::C, llvm::SDValue::getConstantOperandVal(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::ISD::MUL, and llvm::ISD::SHL.
isMemOPCandidate()
static bool isMemOPCandidate (SDNode * I, SDNode * U) static
Definition at line 981 of file HexagonISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::SDNode::getOperand(), I, llvm::ISD::LOAD, llvm::ISD::OR, llvm::ISD::STORE, and llvm::ISD::SUB.
isOpcodeHandled()
static bool isOpcodeHandled (const SDNode * N) static
Definition at line 1675 of file HexagonISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::MUL, N, and llvm::ISD::SHL.
isTargetConstant()
static bool isTargetConstant (const SDValue & V) static
Definition at line 1925 of file HexagonISelDAGToDAG.cpp.
References llvm::HexagonISD::CONST32, and llvm::HexagonISD::CONST32_GP.
willShiftRightEliminate()
static bool willShiftRightEliminate (SDValue V, unsigned Amount) static
Returns
true if V>>Amount will eliminate V's operation on its child
Definition at line 1884 of file HexagonISelDAGToDAG.cpp.
References llvm::SDValue::getOperand(), llvm::ISD::MUL, and llvm::ISD::SHL.
Variable Documentation
CheckSingleUse
cl::opt< bool > CheckSingleUse("hexagon-isel-su", cl::Hidden, cl::init(true), cl::desc("Enable checking of SDNode's single-use status")) ("hexagon-isel-su" , cl::Hidden , cl::init(true) , cl::desc("Enable checking of SDNode's single-use status")) static
EnableAddressRebalancing
cl::opt< bool > EnableAddressRebalancing("isel-rebalance-addr", cl::Hidden, cl::init(true), cl::desc("Rebalance address calculation trees to improve " "instruction selection")) ("isel-rebalance-addr" , cl::Hidden , cl::init(true) , cl::desc("Rebalance address calculation trees to improve " "instruction selection")) static
Referenced by llvm::HexagonDAGToDAGISel::PreprocessISelDAG().
RebalanceOnlyForOptimizations
cl::opt< bool > RebalanceOnlyForOptimizations("rebalance-only-opt", cl::Hidden, cl::init(false), cl::desc("Rebalance address tree only if this allows optimizations")) ("rebalance-only-opt" , cl::Hidden , cl::init(false) , cl::desc("Rebalance address tree only if this allows optimizations")) static
RebalanceOnlyImbalancedTrees
cl::opt< bool > RebalanceOnlyImbalancedTrees("rebalance-only-imbal", cl::Hidden, cl::init(false), cl::desc("Rebalance address tree only if it is imbalanced")) ("rebalance-only-imbal" , cl::Hidden , cl::init(false) , cl::desc("Rebalance address tree only if it is imbalanced")) static