LLVM: lib/Target/LoongArch/LoongArchFrameLowering.cpp File Reference
LoongArchFrameLowering.cpp File Reference
#include "LoongArchFrameLowering.h"
#include "LoongArchMachineFunctionInfo.h"
#include "LoongArchSubtarget.h"
#include "MCTargetDesc/LoongArchBaseInfo.h"
#include "MCTargetDesc/LoongArchMCTargetDesc.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/MC/MCDwarf.h"
Macros
#define DEBUG_TYPE "loongarch-frame-lowering"
Functions
static uint64_t estimateFunctionSizeInBytes (const LoongArchInstrInfo *TII, const MachineFunction &MF)
static bool needScavSlotForCFR (MachineFunction &MF)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loongarch-frame-lowering"
Definition at line 28 of file LoongArchFrameLowering.cpp.
Function Documentation
estimateFunctionSizeInBytes()
static uint64_t estimateFunctionSizeInBytes (const LoongArchInstrInfo * TII, const MachineFunction & MF) static
Definition at line 122 of file LoongArchFrameLowering.cpp.
References MBB, MI, and TII.
Referenced by llvm::LoongArchFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::RISCVFrameLowering::processFunctionBeforeFrameFinalized().
needScavSlotForCFR()
static bool needScavSlotForCFR (MachineFunction & MF) static
Definition at line 131 of file LoongArchFrameLowering.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::LoongArchSubtarget::hasBasicF(), MBB, and MI.
Referenced by llvm::LoongArchFrameLowering::processFunctionBeforeFrameFinalized().