LLVM: lib/DebugInfo/LogicalView/Core/LVElement.cpp File Reference
LVElement.cpp File Reference
#include "llvm/DebugInfo/LogicalView/Core/LVElement.h"
#include "llvm/DebugInfo/LogicalView/Core/LVReader.h"
#include "llvm/DebugInfo/LogicalView/Core/LVScope.h"
#include "llvm/DebugInfo/LogicalView/Core/LVSymbol.h"
#include "llvm/DebugInfo/LogicalView/Core/LVType.h"
Macros
#define DEBUG_TYPE "Element"
Functions
static size_t getStringIndex (StringRef Name)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "Element"
Definition at line 22 of file LVElement.cpp.
Function Documentation
getStringIndex()
static size_t getStringIndex (StringRef Name) static
Definition at line 77 of file LVElement.cpp.
References llvm::logicalview::LVStringPool::getIndex(), llvm::logicalview::getStringPool(), llvm::logicalview::Name, llvm::logicalview::options(), llvm::logicalview::Pathname, llvm::StringRef::rfind(), llvm::StringRef::substr(), and llvm::logicalview::transformPath().
Referenced by llvm::logicalview::LVElement::setFilename(), and llvm::logicalview::LVElement::setName().