LLVM: lib/Target/MSP430/MSP430TargetMachine.cpp File Reference
MSP430TargetMachine.cpp File Reference
#include "MSP430TargetMachine.h"
#include "MSP430.h"
#include "MSP430MachineFunctionInfo.h"
#include "TargetInfo/MSP430TargetInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/LegacyPassManager.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include <optional>
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMSP430Target ()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM)
static std::string computeDataLayout (const Triple &TT, StringRef CPU, const TargetOptions &Options)
Function Documentation
computeDataLayout()
static std::string computeDataLayout (const Triple & TT, StringRef CPU, const TargetOptions & Options) static
Definition at line 37 of file MSP430TargetMachine.cpp.
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM) static
Definition at line 33 of file MSP430TargetMachine.cpp.
References llvm::Reloc::Static.
LLVMInitializeMSP430Target()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMSP430Target ()
Definition at line 26 of file MSP430TargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheMSP430Target(), llvm::initializeMSP430DAGToDAGISelPass(), and X.