LLVM: lib/DebugInfo/PDB/Native/NativeTypePointer.cpp File Reference
NativeTypePointer.cpp File Reference
#include "llvm/DebugInfo/PDB/Native/NativeTypePointer.h"
#include "llvm/DebugInfo/PDB/Native/NativeSession.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include <cassert>
Functions
static bool isInheritanceKind (const MemberPointerInfo &MPI, PointerToMemberRepresentation P1, PointerToMemberRepresentation P2)
Function Documentation
isInheritanceKind()
static bool isInheritanceKind (const MemberPointerInfo & MPI, PointerToMemberRepresentation P1, PointerToMemberRepresentation P2) inline static
Definition at line 159 of file NativeTypePointer.cpp.
References llvm::codeview::MemberPointerInfo::getRepresentation().
Referenced by llvm::pdb::NativeTypePointer::isMultipleInheritance(), llvm::pdb::NativeTypePointer::isSingleInheritance(), and llvm::pdb::NativeTypePointer::isVirtualInheritance().