LLVM: lib/Target/PowerPC/Disassembler/PPCDisassembler.cpp File Reference
PPCDisassembler.cpp File Reference
#include "MCTargetDesc/PPCMCTargetDesc.h"
#include "TargetInfo/PowerPCTargetInfo.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Endian.h"
#include "PPCGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "ppc-disassembler"
#define DecodePointerLikeRegClass0 DecodeGPRCRegisterClass
#define DecodePointerLikeRegClass1 DecodeGPRC_NOR0RegisterClass
#define DecodeQSRCRegisterClass DecodeQFRCRegisterClass
#define DecodeQBRCRegisterClass DecodeQFRCRegisterClass
Typedefs
typedef MCDisassembler::DecodeStatus DecodeStatus
Functions
static MCDisassembler * createPPCDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
static MCDisassembler * createPPCLEDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializePowerPCDisassembler ()
static DecodeStatus decodeCondBrTarget (MCInst &Inst, unsigned Imm, uint64_t, const MCDisassembler *)
static DecodeStatus decodeDirectBrTarget (MCInst &Inst, unsigned Imm, uint64_t, const MCDisassembler *)
template<std::size_t N>
static DecodeStatus decodeRegisterClass (MCInst &Inst, uint64_t RegNo, const MCPhysReg(&Regs)[N])
static DecodeStatus DecodeCRRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeCRBITRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeF4RCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeF8RCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVFRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVRRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVSRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVSFRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVSSRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRC_NOR0RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeG8RCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeG8pRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeG8RC_NOX0RegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSPERCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeACCRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeWACCRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeWACC_HIRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
DecodeStatus DecodeDMRROWRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDMRROWpRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeDMRRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
DecodeStatus DecodeDMRpRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVSRpRCRegisterClass (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeUImmOperand (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeSImmOperand (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeImmZeroOperand (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeVSRpEvenOperands (MCInst &Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeMemRIOperands (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeMemRIXOperands (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeMemRIHashOperands (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeMemRIX16Operands (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeMemRI34PCRelOperands (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeMemRI34Operands (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeSPE8Operands (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeSPE4Operands (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeSPE2Operands (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeCRBitMOperand (MCInst &Inst, uint64_t Imm, int64_t Address, const MCDisassembler *Decoder)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ppc-disassembler"
Definition at line 22 of file PPCDisassembler.cpp.
DecodePointerLikeRegClass0
#define DecodePointerLikeRegClass0 DecodeGPRCRegisterClass
Definition at line 175 of file PPCDisassembler.cpp.
DecodePointerLikeRegClass1
#define DecodePointerLikeRegClass1 DecodeGPRC_NOR0RegisterClass
Definition at line 176 of file PPCDisassembler.cpp.
DecodeQBRCRegisterClass
#define DecodeQBRCRegisterClass DecodeQFRCRegisterClass
Definition at line 236 of file PPCDisassembler.cpp.
DecodeQSRCRegisterClass
#define DecodeQSRCRegisterClass DecodeQFRCRegisterClass
Definition at line 235 of file PPCDisassembler.cpp.
Typedef Documentation
DecodeStatus
typedef MCDisassembler::DecodeStatus DecodeStatus
Definition at line 24 of file PPCDisassembler.cpp.
Function Documentation
createPPCDisassembler()
static MCDisassembler * createPPCDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 41 of file PPCDisassembler.cpp.
Referenced by LLVMInitializePowerPCDisassembler().
createPPCLEDisassembler()
static MCDisassembler * createPPCLEDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 47 of file PPCDisassembler.cpp.
Referenced by LLVMInitializePowerPCDisassembler().
DecodeACCRCRegisterClass()
static DecodeStatus DecodeACCRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 184 of file PPCDisassembler.cpp.
References decodeRegisterClass().
decodeCondBrTarget()
static DecodeStatus decodeCondBrTarget (MCInst & Inst, unsigned Imm, uint64_t , const MCDisassembler *) static
Definition at line 65 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
decodeCRBitMOperand()
static DecodeStatus decodeCRBitMOperand (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 442 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::countTrailingZeros(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
DecodeCRBITRCRegisterClass()
static DecodeStatus DecodeCRBITRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 97 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeCRRCRegisterClass()
static DecodeStatus DecodeCRRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 91 of file PPCDisassembler.cpp.
References decodeRegisterClass().
decodeDirectBrTarget()
static DecodeStatus decodeDirectBrTarget (MCInst & Inst, unsigned Imm, uint64_t , const MCDisassembler *) static
Definition at line 72 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::Offset, and llvm::MCDisassembler::Success.
DecodeDMRpRCRegisterClass()
DecodeStatus DecodeDMRpRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder)
Definition at line 224 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeDMRRCRegisterClass()
static DecodeStatus DecodeDMRRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 216 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeDMRROWpRCRegisterClass()
static DecodeStatus DecodeDMRROWpRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 210 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeDMRROWRCRegisterClass()
DecodeStatus DecodeDMRROWRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder)
Definition at line 204 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeF4RCRegisterClass()
static DecodeStatus DecodeF4RCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 103 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeF8RCRegisterClass()
static DecodeStatus DecodeF8RCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 109 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeG8pRCRegisterClass()
static DecodeStatus DecodeG8pRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 163 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeG8RC_NOX0RegisterClass()
static DecodeStatus DecodeG8RC_NOX0RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 170 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeG8RCRegisterClass()
static DecodeStatus DecodeG8RCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 157 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeGPRC_NOR0RegisterClass()
static DecodeStatus DecodeGPRC_NOR0RegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 152 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeGPRCRegisterClass()
static DecodeStatus DecodeGPRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 145 of file PPCDisassembler.cpp.
References decodeRegisterClass().
decodeImmZeroOperand()
static DecodeStatus decodeImmZeroOperand (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 256 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by decodeMemRI34PCRelOperands().
decodeMemRI34Operands()
static DecodeStatus decodeMemRI34Operands (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 379 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
decodeMemRI34PCRelOperands()
static DecodeStatus decodeMemRI34PCRelOperands (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 365 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), and decodeImmZeroOperand().
decodeMemRIHashOperands()
static DecodeStatus decodeMemRIHashOperands (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 332 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
decodeMemRIOperands()
static DecodeStatus decodeMemRIOperands (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 274 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::sampleprof::Base, llvm::MCInst::begin(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCInst::getOpcode(), llvm::MCInst::insert(), and llvm::MCDisassembler::Success.
decodeMemRIX16Operands()
static DecodeStatus decodeMemRIX16Operands (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 349 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
decodeMemRIXOperands()
static DecodeStatus decodeMemRIXOperands (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 310 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::sampleprof::Base, llvm::MCInst::begin(), llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), llvm::MCInst::getOpcode(), llvm::MCInst::insert(), and llvm::MCDisassembler::Success.
decodeRegisterClass()
template<std::size_t N> static DecodeStatus decodeRegisterClass (MCInst & Inst, uint64_t RegNo, const MCPhysReg(&) Regs[N]) static
Definition at line 84 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createReg(), N, and llvm::MCDisassembler::Success.
Referenced by DecodeACCRCRegisterClass(), DecodeCRBITRCRegisterClass(), DecodeCRRCRegisterClass(), DecodeDMRpRCRegisterClass(), DecodeDMRRCRegisterClass(), DecodeDMRROWpRCRegisterClass(), DecodeDMRROWRCRegisterClass(), DecodeF4RCRegisterClass(), DecodeF8RCRegisterClass(), DecodeG8pRCRegisterClass(), DecodeG8RC_NOX0RegisterClass(), DecodeG8RCRegisterClass(), DecodeGPRC_NOR0RegisterClass(), DecodeGPRCRegisterClass(), DecodeSPERCRegisterClass(), DecodeVFRCRegisterClass(), DecodeVRRCRegisterClass(), DecodeVSFRCRegisterClass(), DecodeVSRCRegisterClass(), DecodeVSRpRCRegisterClass(), DecodeVSSRCRegisterClass(), DecodeWACC_HIRCRegisterClass(), and DecodeWACCRCRegisterClass().
decodeSImmOperand()
template<unsigned N> static DecodeStatus decodeSImmOperand (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 248 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
decodeSPE2Operands()
static DecodeStatus decodeSPE2Operands (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 426 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
decodeSPE4Operands()
static DecodeStatus decodeSPE4Operands (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 410 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
decodeSPE8Operands()
static DecodeStatus decodeSPE8Operands (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 394 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::sampleprof::Base, llvm::MCOperand::createImm(), llvm::MCOperand::createReg(), and llvm::MCDisassembler::Success.
DecodeSPERCRegisterClass()
static DecodeStatus DecodeSPERCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 178 of file PPCDisassembler.cpp.
References decodeRegisterClass().
decodeUImmOperand()
template<unsigned N> static DecodeStatus decodeUImmOperand (MCInst & Inst, uint64_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 239 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
DecodeVFRCRegisterClass()
static DecodeStatus DecodeVFRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 115 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeVRRCRegisterClass()
static DecodeStatus DecodeVRRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 121 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeVSFRCRegisterClass()
static DecodeStatus DecodeVSFRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 133 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeVSRCRegisterClass()
static DecodeStatus DecodeVSRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 127 of file PPCDisassembler.cpp.
References decodeRegisterClass().
decodeVSRpEvenOperands()
static DecodeStatus decodeVSRpEvenOperands (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 265 of file PPCDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeVSRpRCRegisterClass()
static DecodeStatus DecodeVSRpRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 229 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeVSSRCRegisterClass()
static DecodeStatus DecodeVSSRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 139 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeWACC_HIRCRegisterClass()
static DecodeStatus DecodeWACC_HIRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 196 of file PPCDisassembler.cpp.
References decodeRegisterClass().
DecodeWACCRCRegisterClass()
static DecodeStatus DecodeWACCRCRegisterClass (MCInst & Inst, uint64_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 190 of file PPCDisassembler.cpp.
References decodeRegisterClass().
LLVMInitializePowerPCDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializePowerPCDisassembler ()
Definition at line 53 of file PPCDisassembler.cpp.
References createPPCDisassembler(), createPPCLEDisassembler(), llvm::getThePPC32LETarget(), llvm::getThePPC32Target(), llvm::getThePPC64LETarget(), llvm::getThePPC64Target(), and llvm::TargetRegistry::RegisterMCDisassembler().