LLVM: lib/Remarks/RemarkLinker.cpp File Reference
RemarkLinker.cpp File Reference
#include "llvm/Remarks/RemarkLinker.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Object/SymbolicFile.h"
#include "llvm/Remarks/RemarkParser.h"
#include "llvm/Remarks/RemarkSerializer.h"
#include "llvm/Support/Error.h"
#include <optional>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
static Expected< StringRef > getRemarksSectionName (const object::ObjectFile &Obj)
static bool shouldKeepRemark (const Remark &R)
Function Documentation
getRemarksSectionName()
static Expected< StringRef > getRemarksSectionName (const object::ObjectFile & Obj) static
Definition at line 30 of file RemarkLinker.cpp.
References llvm::createStringError(), and llvm::object::Binary::isMachO().
Referenced by llvm::remarks::getRemarksSectionContents().
shouldKeepRemark()
static bool shouldKeepRemark (const Remark & R) static
Definition at line 70 of file RemarkLinker.cpp.
Referenced by llvm::remarks::RemarkLinker::link().