LLVM: lib/CodeGen/SelectionDAG/SelectionDAGDumper.cpp File Reference
SelectionDAGDumper.cpp File Reference
#include "SDNodeDbgValue.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/CodeGen/ISDOpcodes.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/ModuleSlotTracker.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MachineValueType.h"
#include "llvm/Support/Printable.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetIntrinsicInfo.h"
#include "llvm/Target/TargetMachine.h"
#include <cstdint>
#include <iterator>
#include "llvm/IR/VPIntrinsics.def"
Macros
#define BEGIN_REGISTER_VP_SDNODE(SDID, LEGALARG, NAME, ...)
Typedefs
using VisitedSDNodeSet = SmallPtrSet<const SDNode *, 32>
Functions
static Printable PrintNodeId (const SDNode &Node)
static void printMemOperand (raw_ostream &OS, const MachineMemOperand &MMO, const MachineFunction *MF, const Module *M, const MachineFrameInfo *MFI, const TargetInstrInfo *TII, LLVMContext &Ctx)
static void printMemOperand (raw_ostream &OS, const MachineMemOperand &MMO, const SelectionDAG *G)
static bool shouldPrintInline (const SDNode &Node, const SelectionDAG *G)
Return true if this node is so simple that we should just print it inline if it appears as an operand.
static void DumpNodes (const SDNode *N, unsigned indent, const SelectionDAG *G)
static bool printOperand (raw_ostream &OS, const SelectionDAG *G, const SDValue Value)
static void DumpNodesr (raw_ostream &OS, const SDNode *N, unsigned indent, const SelectionDAG *G, VisitedSDNodeSet &once)
static void printrWithDepthHelper (raw_ostream &OS, const SDNode *N, const SelectionDAG *G, unsigned depth, unsigned indent)
Variables
static cl::opt< bool > VerboseDAGDumping ("dag-dump-verbose", cl::Hidden, cl::desc("Display more information when dumping selection " "DAG nodes."))
Macro Definition Documentation
BEGIN_REGISTER_VP_SDNODE
#define BEGIN_REGISTER_VP_SDNODE (SDID, LEGALARG, NAME, ...)
Value:
  case ISD::SDID:                                                              \
    return #NAME;
Typedef Documentation
VisitedSDNodeSet
using VisitedSDNodeSet = SmallPtrSet<const SDNode *, 32>
Definition at line 984 of file SelectionDAGDumper.cpp.
Function Documentation
DumpNodes()
static void DumpNodes (const SDNode * N, unsigned indent, const SelectionDAG * G) static
Definition at line 918 of file SelectionDAGDumper.cpp.
References llvm::dbgs(), DumpNodes(), G, llvm::raw_ostream::indent(), N, and shouldPrintInline().
Referenced by llvm::SelectionDAG::dump(), and DumpNodes().
DumpNodesr()
static void DumpNodesr (raw_ostream & OS, const SDNode * N, unsigned indent, const SelectionDAG * G, VisitedSDNodeSet & once) static
Definition at line 986 of file SelectionDAGDumper.cpp.
References DumpNodesr(), G, llvm::raw_ostream::indent(), N, and printOperand().
Referenced by DumpNodesr(), llvm::SDNode::dumpr(), and llvm::SDNode::dumpr().
printMemOperand() [1/2]
static void printMemOperand (raw_ostream & OS, const MachineMemOperand & MMO, const MachineFunction * MF, const Module * M, const MachineFrameInfo * MFI, const TargetInstrInfo * TII, LLVMContext & Ctx) static
Definition at line 528 of file SelectionDAGDumper.cpp.
References llvm::MachineFunction::getFunction(), llvm::ModuleSlotTracker::incorporateFunction(), llvm::MachineMemOperand::print(), and TII.
Referenced by llvm::SDNode::print_details(), and printMemOperand().
printMemOperand() [2/2]
static void printMemOperand (raw_ostream & OS, const MachineMemOperand & MMO, const SelectionDAG * G) static
Definition at line 539 of file SelectionDAGDumper.cpp.
References G, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::GlobalValue::getParent(), and printMemOperand().
PrintNodeId()
static Printable PrintNodeId (const SDNode & Node) static
Definition at line 517 of file SelectionDAGDumper.cpp.
Referenced by llvm::SDDbgValue::print(), printOperand(), and llvm::SDNode::printr().
printOperand()
static bool printOperand (raw_ostream & OS, const SelectionDAG * G, const SDValue Value) static
Definition at line 963 of file SelectionDAGDumper.cpp.
References G, PrintNodeId(), and shouldPrintInline().
Referenced by DumpNodesr(), llvm::SDNode::print(), printAddress(), and llvm::SystemZAsmPrinter::PrintAsmOperand().
printrWithDepthHelper()
static void printrWithDepthHelper (raw_ostream & OS, const SDNode * N, const SelectionDAG * G, unsigned depth, unsigned indent) static
Definition at line 1024 of file SelectionDAGDumper.cpp.
References G, llvm::raw_ostream::indent(), N, llvm::MVT::Other, and printrWithDepthHelper().
Referenced by llvm::SDNode::printrWithDepth(), and printrWithDepthHelper().
shouldPrintInline()
static bool shouldPrintInline (const SDNode & Node, const SelectionDAG * G) static
Return true if this node is so simple that we should just print it inline if it appears as an operand.
Definition at line 907 of file SelectionDAGDumper.cpp.
References llvm::ISD::EntryToken, G, and VerboseDAGDumping.
Referenced by llvm::SelectionDAG::dump(), DumpNodes(), and printOperand().
Variable Documentation
VerboseDAGDumping
cl::opt< bool > VerboseDAGDumping("dag-dump-verbose", cl::Hidden, cl::desc("Display more information when dumping selection " "DAG nodes.")) ("dag-dump-verbose" , cl::Hidden , cl::desc("Display more information when dumping selection " "DAG nodes.")) static
Referenced by llvm::SelectionDAG::dump(), llvm::SDNode::print(), llvm::SDNode::print_details(), and shouldPrintInline().