LLVM: lib/Target/SPIRV/SPIRVRegularizer.cpp File Reference
SPIRVRegularizer.cpp File Reference
#include "SPIRV.h"
#include "SPIRVTargetMachine.h"
#include "llvm/Demangle/Demangle.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/PassManager.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include <list>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "spirv-regularizer"
Functions
void llvm::initializeSPIRVRegularizerPass (PassRegistry &)
INITIALIZE_PASS (SPIRVRegularizer, DEBUG_TYPE, "SPIR-V Regularizer", false, false) void SPIRVRegularizer
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-regularizer"
Definition at line 24 of file SPIRVRegularizer.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (SPIRVRegularizer , DEBUG_TYPE , "SPIR-V Regularizer" , false , false)
Definition at line 58 of file SPIRVRegularizer.cpp.
References llvm::CallingConv::C, llvm::InsertElementInst::Create(), llvm::dbgs(), F, llvm::MetadataAsValue::get(), llvm::PoisonValue::get(), llvm::ConstantInt::get(), llvm::ValueAsMetadata::get(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Instruction::getParent(), Idx, instructions, LLVM_DEBUG, llvm::User::replaceUsesOfWith(), llvm::User::setOperand(), and Users.