LLVM: lib/CodeGen/StackMaps.cpp File Reference
StackMaps.cpp File Reference
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/ADT/DenseMapInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Twine.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <iterator>
#include <utility>
Macros
#define DEBUG_TYPE "stackmaps"
Functions
static uint64_t getConstMetaVal (const MachineInstr &MI, unsigned Idx)
static unsigned getDwarfRegNum (unsigned Reg, const TargetRegisterInfo *TRI)
Go up the super-register chain until we hit a valid dwarf register number.
Variables
static cl::opt< int > StackMapVersion ("stackmap-version", cl::init(3), cl::Hidden, cl::desc("Specify the stackmap encoding version (default = 3)"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "stackmaps"
Definition at line 40 of file StackMaps.cpp.
Function Documentation
getConstMetaVal()
static uint64_t getConstMetaVal (const MachineInstr & MI, unsigned Idx) static
Definition at line 48 of file StackMaps.cpp.
References assert(), Idx, and MI.
Referenced by llvm::StatepointOpers::getFirstGCPtrIdx(), llvm::StatepointOpers::getGCPointerMap(), llvm::StatepointOpers::getNumAllocaIdx(), llvm::StatepointOpers::getNumGcMapEntriesIdx(), and llvm::StatepointOpers::getNumGCPtrIdx().
getDwarfRegNum()
static unsigned getDwarfRegNum (unsigned Reg, const TargetRegisterInfo * TRI) static
Go up the super-register chain until we hit a valid dwarf register number.
Definition at line 195 of file StackMaps.cpp.
References assert(), llvm::MCRegisterInfo::DiffListIterator::isValid(), and TRI.
Referenced by llvm::AArch64RegisterInfo::getOffsetOpcodes(), and llvm::RISCVRegisterInfo::getOffsetOpcodes().
Variable Documentation
StackMapVersion
cl::opt< int > StackMapVersion("stackmap-version", cl::init(3), cl::Hidden, cl::desc("Specify the stackmap encoding version (default = 3)")) ("stackmap-version" , cl::init(3) , cl::Hidden , cl::desc("Specify the stackmap encoding version (default = 3)")) static
Referenced by llvm::StackMaps::StackMaps().