LLVM: llvm::DebuginfodServer Struct Reference
llvm::DebuginfodServer Struct Reference
#include "llvm/Debuginfod/Debuginfod.h"
Public Member Functions
DebuginfodServer (DebuginfodLog &Log, DebuginfodCollection &Collection)
Public Attributes
HTTPServer Server
DebuginfodLog & Log
DebuginfodCollection & Collection
Detailed Description
Definition at line 137 of file Debuginfod.h.
Constructor & Destructor Documentation
DebuginfodServer()
llvm::DebuginfodServer::DebuginfodServer (DebuginfodLog & Log, DebuginfodCollection & Collection)
Definition at line 510 of file Debuginfod.cpp.
References llvm::cantFail(), Collection, llvm::consumeError(), llvm::DebuginfodCollection::findDebugBinaryPath(), llvm::HTTPServer::get(), Server, llvm::HTTPServerRequest::setResponse(), and llvm::streamFile().
Member Data Documentation
Collection
DebuginfodCollection& llvm::DebuginfodServer::Collection
Definition at line 140 of file Debuginfod.h.
Referenced by DebuginfodServer().
Log
DebuginfodLog& llvm::DebuginfodServer::Log
Definition at line 139 of file Debuginfod.h.
Server
HTTPServer llvm::DebuginfodServer::Server
Definition at line 138 of file Debuginfod.h.
Referenced by DebuginfodServer().
The documentation for this struct was generated from the following files:
include/llvm/Debuginfod/Debuginfod.h
lib/Debuginfod/Debuginfod.cpp