LLVM: llvm::DWARFTypePrinter Struct Reference
llvm::DWARFTypePrinter Struct Reference
#include "llvm/DebugInfo/DWARF/DWARFTypePrinter.h"
Public Member Functions
DWARFTypePrinter (raw_ostream &OS)
void appendTypeTagName (dwarf::Tag T)
Dump the name encoded in the type tag.
void appendArrayType (const DWARFDie &D)
DWARFDie skipQualifiers (DWARFDie D)
bool needsParens (DWARFDie D)
void appendPointerLikeTypeBefore (DWARFDie D, DWARFDie Inner, StringRef Ptr)
DWARFDie appendUnqualifiedNameBefore (DWARFDie D, std::string *OriginalFullName=nullptr)
void appendUnqualifiedNameAfter (DWARFDie D, DWARFDie Inner, bool SkipFirstParamIfArtificial=false)
void appendQualifiedName (DWARFDie D)
DWARFDie appendQualifiedNameBefore (DWARFDie D)
bool appendTemplateParameters (DWARFDie D, bool *FirstParameter=nullptr)
void decomposeConstVolatile (DWARFDie &N, DWARFDie &T, DWARFDie &C, DWARFDie &V)
void appendConstVolatileQualifierAfter (DWARFDie N)
void appendConstVolatileQualifierBefore (DWARFDie N)
void appendUnqualifiedName (DWARFDie D, std::string *OriginalFullName=nullptr)
Recursively append the DIE type name when applicable.
void appendSubroutineNameAfter (DWARFDie D, DWARFDie Inner, bool SkipFirstParamIfArtificial, bool Const, bool Volatile)
void appendScopes (DWARFDie D)
Public Attributes
raw_ostream & OS
bool Word = true
bool EndedWithTemplate = false
Detailed Description
Definition at line 24 of file DWARFTypePrinter.h.
Constructor & Destructor Documentation
DWARFTypePrinter()
llvm::DWARFTypePrinter::DWARFTypePrinter (raw_ostream & OS) inline
Definition at line 29 of file DWARFTypePrinter.h.
Member Function Documentation
appendArrayType()
void llvm::DWARFTypePrinter::appendArrayType (const DWARFDie & D)
Definition at line 18 of file DWARFTypePrinter.cpp.
References llvm::CallingConv::C, D, EndedWithTemplate, llvm::dwarf::LanguageLowerBound(), and OS.
Referenced by appendUnqualifiedNameAfter().
appendConstVolatileQualifierAfter()
void llvm::DWARFTypePrinter::appendConstVolatileQualifierAfter (DWARFDie N)
Definition at line 473 of file DWARFTypePrinter.cpp.
References appendSubroutineNameAfter(), appendUnqualifiedNameAfter(), llvm::CallingConv::C, decomposeConstVolatile(), N, llvm::resolveReferencedType(), and T.
Referenced by appendUnqualifiedNameAfter().
appendConstVolatileQualifierBefore()
void llvm::DWARFTypePrinter::appendConstVolatileQualifierBefore (DWARFDie N)
Definition at line 484 of file DWARFTypePrinter.cpp.
References A, appendQualifiedNameBefore(), llvm::CallingConv::C, decomposeConstVolatile(), N, OS, llvm::resolveReferencedType(), T, and Word.
Referenced by appendUnqualifiedNameBefore().
appendPointerLikeTypeBefore()
void llvm::DWARFTypePrinter::appendPointerLikeTypeBefore (DWARFDie D, DWARFDie Inner, StringRef Ptr)
Definition at line 85 of file DWARFTypePrinter.cpp.
References appendQualifiedNameBefore(), EndedWithTemplate, needsParens(), OS, Ptr, and Word.
Referenced by appendUnqualifiedNameBefore().
appendQualifiedName()
void llvm::DWARFTypePrinter::appendQualifiedName (DWARFDie D)
Definition at line 299 of file DWARFTypePrinter.cpp.
References appendScopes(), appendUnqualifiedName(), D, and llvm::scopedTAGs().
Referenced by appendSubroutineNameAfter(), appendTemplateParameters(), appendUnqualifiedNameBefore(), and llvm::dumpTypeQualifiedName().
appendQualifiedNameBefore()
DWARFDie llvm::DWARFTypePrinter::appendQualifiedNameBefore (DWARFDie D)
Definition at line 304 of file DWARFTypePrinter.cpp.
References appendScopes(), appendUnqualifiedNameBefore(), D, and llvm::scopedTAGs().
Referenced by appendConstVolatileQualifierBefore(), appendPointerLikeTypeBefore(), and appendUnqualifiedNameBefore().
appendScopes()
void llvm::DWARFTypePrinter::appendScopes (DWARFDie D)
Definition at line 637 of file DWARFTypePrinter.cpp.
References appendScopes(), appendUnqualifiedName(), D, llvm::DWARFDie::getParent(), OS, and P.
Referenced by appendQualifiedName(), appendQualifiedNameBefore(), and appendScopes().
appendSubroutineNameAfter()
void llvm::DWARFTypePrinter::appendSubroutineNameAfter (DWARFDie D, DWARFDie Inner, bool SkipFirstParamIfArtificial, bool Const, bool Volatile)
Definition at line 522 of file DWARFTypePrinter.cpp.
References appendQualifiedName(), appendUnqualifiedNameAfter(), CC, D, EndedWithTemplate, OS, P, llvm::resolveReferencedType(), and T.
Referenced by appendConstVolatileQualifierAfter(), and appendUnqualifiedNameAfter().
appendTemplateParameters()
bool llvm::DWARFTypePrinter::appendTemplateParameters (DWARFDie D, bool * FirstParameter = nullptr)
Definition at line 309 of file DWARFTypePrinter.cpp.
References appendQualifiedName(), appendTemplateParameters(), assert(), llvm::CallingConv::C, D, EndedWithTemplate, llvm::format(), Name, OS, llvm::resolveReferencedType(), llvm::to_string(), and llvm::dwarf::toString().
Referenced by appendTemplateParameters(), and appendUnqualifiedNameBefore().
appendTypeTagName()
void llvm::DWARFTypePrinter::appendTypeTagName (dwarf::Tag T)
Dump the name encoded in the type tag.
Definition at line 7 of file DWARFTypePrinter.cpp.
References OS, llvm::StringRef::size(), and llvm::dwarf::TagString().
Referenced by appendUnqualifiedNameBefore().
appendUnqualifiedName()
void llvm::DWARFTypePrinter::appendUnqualifiedName (DWARFDie D, std::string * OriginalFullName = nullptr)
Recursively append the DIE type name when applicable.
Definition at line 515 of file DWARFTypePrinter.cpp.
References appendUnqualifiedNameAfter(), appendUnqualifiedNameBefore(), and D.
Referenced by appendQualifiedName(), appendScopes(), and llvm::dumpTypeUnqualifiedName().
appendUnqualifiedNameAfter()
void llvm::DWARFTypePrinter::appendUnqualifiedNameAfter (DWARFDie D, DWARFDie Inner, bool SkipFirstParamIfArtificial = false)
Definition at line 215 of file DWARFTypePrinter.cpp.
References appendArrayType(), appendConstVolatileQualifierAfter(), appendSubroutineNameAfter(), appendUnqualifiedNameAfter(), D, needsParens(), OS, and llvm::resolveReferencedType().
Referenced by appendConstVolatileQualifierAfter(), appendSubroutineNameAfter(), appendUnqualifiedName(), and appendUnqualifiedNameAfter().
appendUnqualifiedNameBefore()
DWARFDie llvm::DWARFTypePrinter::appendUnqualifiedNameBefore (DWARFDie D, std::string * OriginalFullName = nullptr)
Definition at line 98 of file DWARFTypePrinter.cpp.
References appendConstVolatileQualifierBefore(), appendPointerLikeTypeBefore(), appendQualifiedName(), appendQualifiedNameBefore(), appendTemplateParameters(), appendTypeTagName(), assert(), D, EndedWithTemplate, Name, needsParens(), llvm::StringRef::npos, OS, llvm::resolveReferencedType(), llvm::dwarf::toString(), and Word.
Referenced by appendQualifiedNameBefore(), and appendUnqualifiedName().
decomposeConstVolatile()
void llvm::DWARFTypePrinter::decomposeConstVolatile (DWARFDie & N, DWARFDie & T, DWARFDie & C, DWARFDie & V)
Definition at line 458 of file DWARFTypePrinter.cpp.
References llvm::CallingConv::C, N, llvm::resolveReferencedType(), and T.
Referenced by appendConstVolatileQualifierAfter(), and appendConstVolatileQualifierBefore().
needsParens()
bool llvm::DWARFTypePrinter::needsParens (DWARFDie D)
Definition at line 79 of file DWARFTypePrinter.cpp.
References D, and skipQualifiers().
Referenced by appendPointerLikeTypeBefore(), appendUnqualifiedNameAfter(), and appendUnqualifiedNameBefore().
skipQualifiers()
DWARFDie llvm::DWARFTypePrinter::skipQualifiers (DWARFDie D)
Definition at line 72 of file DWARFTypePrinter.cpp.
References D, and llvm::resolveReferencedType().
Referenced by needsParens().
Member Data Documentation
EndedWithTemplate
bool llvm::DWARFTypePrinter::EndedWithTemplate = false
Definition at line 27 of file DWARFTypePrinter.h.
Referenced by appendArrayType(), appendPointerLikeTypeBefore(), appendSubroutineNameAfter(), appendTemplateParameters(), and appendUnqualifiedNameBefore().
OS
raw_ostream& llvm::DWARFTypePrinter::OS
Definition at line 25 of file DWARFTypePrinter.h.
Referenced by appendArrayType(), appendConstVolatileQualifierBefore(), appendPointerLikeTypeBefore(), appendScopes(), appendSubroutineNameAfter(), appendTemplateParameters(), appendTypeTagName(), appendUnqualifiedNameAfter(), and appendUnqualifiedNameBefore().
Word
bool llvm::DWARFTypePrinter::Word = true
Definition at line 26 of file DWARFTypePrinter.h.
Referenced by appendConstVolatileQualifierBefore(), appendPointerLikeTypeBefore(), and appendUnqualifiedNameBefore().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFTypePrinter.h
lib/DebugInfo/DWARF/DWARFTypePrinter.cpp