LLVM: llvm::SelectPatternResult Struct Reference
llvm::SelectPatternResult Struct Reference
#include "llvm/Analysis/ValueTracking.h"
Static Public Member Functions
static bool isMinOrMax (SelectPatternFlavor SPF)
When implementing this min/max pattern as fcmp; select, does the fcmp have to be ordered?
Public Attributes
SelectPatternFlavor Flavor
SelectPatternNaNBehavior NaNBehavior
bool Ordered
Only applicable if Flavor is SPF_FMINNUM or SPF_FMAXNUM.
Detailed Description
Definition at line 713 of file ValueTracking.h.
Member Function Documentation
isMinOrMax()
static bool llvm::SelectPatternResult::isMinOrMax (SelectPatternFlavor SPF) inline static
When implementing this min/max pattern as fcmp; select, does the fcmp have to be ordered?
Return true if SPF is a min or a max pattern.
Definition at line 722 of file ValueTracking.h.
References llvm::SPF_ABS, llvm::SPF_NABS, and llvm::SPF_UNKNOWN.
Referenced by llvm::canConvertToMinOrMaxIntrinsic(), computeKnownBitsFromOperator(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::RecurrenceDescriptor::getReductionOpChain(), matchMinMaxOfMinMax(), and simplifySelectWithICmpCond().
Member Data Documentation
Flavor
SelectPatternFlavor llvm::SelectPatternResult::Flavor
Definition at line 714 of file ValueTracking.h.
Referenced by computeKnownBitsFromOperator(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::ARMTTIImpl::getCmpSelInstrCost(), isSignedMinMaxClamp(), isSSATMinMaxPattern(), matchMinMaxOfMinMax(), simplifySelectWithICmpCond(), and llvm::InstCombinerImpl::visitMul().
NaNBehavior
SelectPatternNaNBehavior llvm::SelectPatternResult::NaNBehavior
Definition at line 715 of file ValueTracking.h.
Ordered
bool llvm::SelectPatternResult::Ordered
Only applicable if Flavor is SPF_FMINNUM or SPF_FMAXNUM.
Definition at line 717 of file ValueTracking.h.
The documentation for this struct was generated from the following file:
include/llvm/Analysis/ValueTracking.h