LLVM: llvm::remarks::YAMLStrTabMetaSerializer Struct Reference
llvm::remarks::YAMLStrTabMetaSerializer Struct Reference
#include "llvm/Remarks/YAMLRemarkSerializer.h"
Public Member Functions
YAMLStrTabMetaSerializer (raw_ostream &OS, std::optional< StringRef > ExternalFilename, const StringTable &StrTab)
void emit () override
Public Member Functions inherited from llvm::remarks::YAMLMetaSerializer
YAMLMetaSerializer (raw_ostream &OS, std::optional< StringRef > ExternalFilename)
Public Member Functions inherited from llvm::remarks::MetaSerializer
MetaSerializer (raw_ostream &OS)
virtual ~MetaSerializer ()=default
This is just an interface.
Public Attributes
const StringTable & StrTab
The string table is part of the metadata.
Public Attributes inherited from llvm::remarks::YAMLMetaSerializer
std::optional< StringRef > ExternalFilename
Public Attributes inherited from llvm::remarks::MetaSerializer
raw_ostream & OS
The open raw_ostream that the metadata is emitted to.
Detailed Description
Definition at line 94 of file YAMLRemarkSerializer.h.
Constructor & Destructor Documentation
YAMLStrTabMetaSerializer()
llvm::remarks::YAMLStrTabMetaSerializer::YAMLStrTabMetaSerializer (raw_ostream & OS, std::optional< StringRef > ExternalFilename, const StringTable & StrTab) inline
Definition at line 98 of file YAMLRemarkSerializer.h.
Member Function Documentation
emit()
void YAMLStrTabMetaSerializer::emit () override virtual
Reimplemented from llvm::remarks::YAMLMetaSerializer.
Definition at line 250 of file YAMLRemarkSerializer.cpp.
References emitExternalFile(), emitMagic(), emitStrTab(), emitVersion(), llvm::remarks::YAMLMetaSerializer::ExternalFilename, llvm::remarks::MetaSerializer::OS, and StrTab.
Member Data Documentation
StrTab
const StringTable& llvm::remarks::YAMLStrTabMetaSerializer::StrTab
The string table is part of the metadata.
Definition at line 96 of file YAMLRemarkSerializer.h.
Referenced by emit().
The documentation for this struct was generated from the following files:
include/llvm/Remarks/YAMLRemarkSerializer.h
lib/Remarks/YAMLRemarkSerializer.cpp