LLVM: llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > > Struct Reference
llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > > Struct Reference
#include "llvm/ObjectYAML/ELFYAML.h"
Static Public Member Functions
static void mapping (IO &IO, std::unique_ptr< ELFYAML::Chunk > &C)
static std::string validate (IO &io, std::unique_ptr< ELFYAML::Chunk > &C)
Detailed Description
Definition at line 948 of file ELFYAML.h.
Member Function Documentation
mapping()
void llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::mapping (IO & IO, std::unique_ptr< ELFYAML::Chunk > & C) static
Definition at line 1533 of file ELFYAML.cpp.
References assert(), llvm::ELFYAML::dropUniqueSuffix(), llvm::ELF::EM_ARM, llvm::ELF::EM_MIPS, llvm::yaml::fillMapping(), llvm::yaml::getStringValue(), llvm::yaml::groupSectionMapping(), llvm::yaml::isInteger(), Name, llvm::ELFYAML::StackSizesSection::nameMatches(), llvm::yaml::sectionHeaderTableMapping(), llvm::yaml::sectionMapping(), llvm::yaml::setStringValue(), llvm::ELF::SHT_ARM_EXIDX, llvm::ELF::SHT_DYNAMIC, llvm::ELF::SHT_GNU_HASH, llvm::ELF::SHT_GNU_verdef, llvm::ELF::SHT_GNU_verneed, llvm::ELF::SHT_GNU_versym, llvm::ELF::SHT_GROUP, llvm::ELF::SHT_HASH, llvm::ELF::SHT_LLVM_ADDRSIG, llvm::ELF::SHT_LLVM_BB_ADDR_MAP, llvm::ELF::SHT_LLVM_BB_ADDR_MAP_V0, llvm::ELF::SHT_LLVM_CALL_GRAPH_PROFILE, llvm::ELF::SHT_LLVM_DEPENDENT_LIBRARIES, llvm::ELF::SHT_LLVM_LINKER_OPTIONS, llvm::ELF::SHT_MIPS_ABIFLAGS, llvm::ELF::SHT_NOBITS, llvm::ELF::SHT_NOTE, llvm::ELF::SHT_REL, llvm::ELF::SHT_RELA, llvm::ELF::SHT_RELR, llvm::ELF::SHT_SYMTAB_SHNDX, llvm::StringRef::startswith(), llvm::Type::Type(), Type, and llvm::ELFYAML::SectionHeaderTable::TypeStr.
validate()
std::string llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::validate (IO & io, std::unique_ptr< ELFYAML::Chunk > & C) static
Definition at line 1691 of file ELFYAML.cpp.
References llvm::CallingConv::C, llvm::ELFYAML::Section::Content, llvm::count_if(), E, F, llvm::ELFYAML::Section::getEntries(), I, Name, P, and llvm::ELFYAML::Section::Size.
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/ELFYAML.h
lib/ObjectYAML/ELFYAML.cpp