LLVM: llvm::rdf::NodeAllocator Struct Reference
llvm::rdf::NodeAllocator Struct Reference
#include "llvm/CodeGen/RDFGraph.h"
Public Types
enum { NodeMemSize = 32 }
Public Member Functions
NodeAllocator (uint32_t NPB=4096)
NodeBase * ptr (NodeId N) const
NodeId id (const NodeBase *P) const
NodeAddr< NodeBase * > New ()
void clear ()
Detailed Description
Definition at line 374 of file RDFGraph.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
NodeMemSize
Definition at line 376 of file RDFGraph.h.
Constructor & Destructor Documentation
NodeAllocator()
llvm::rdf::NodeAllocator::NodeAllocator (uint32_t NPB = 4096) inline
Definition at line 378 of file RDFGraph.h.
References assert(), and llvm::isPowerOf2_32().
Member Function Documentation
clear()
void NodeAllocator::clear ()
Definition at line 387 of file RDFGraph.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Reset().
id()
NodeId NodeAllocator::id (const NodeBase * P) const
Definition at line 375 of file RDFGraph.cpp.
References A, B, Idx, llvm_unreachable, NodeMemSize, and P.
New()
NodeAddr< NodeBase * > NodeAllocator::New ()
Definition at line 363 of file RDFGraph.cpp.
References NodeMemSize.
ptr()
NodeBase * llvm::rdf::NodeAllocator::ptr (NodeId N) const inline
Definition at line 384 of file RDFGraph.h.
References N, NodeMemSize, and llvm::Offset.
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFGraph.h
lib/CodeGen/RDFGraph.cpp