LLVM: llvm::AMDGPU::SIModeRegisterDefaults Struct Reference
llvm::AMDGPU::SIModeRegisterDefaults Struct Reference
#include "Target/AMDGPU/Utils/AMDGPUBaseInfo.h"
Public Member Functions
SIModeRegisterDefaults ()
SIModeRegisterDefaults (const Function &F)
bool operator== (const SIModeRegisterDefaults Other) const
bool allFP32Denormals () const
bool allFP64FP16Denormals () const
uint32_t fpDenormModeSPValue () const
Get the encoding value for the FP_DENORM bits of the mode register for the FP32 denormal mode.
uint32_t fpDenormModeDPValue () const
Get the encoding value for the FP_DENORM bits of the mode register for the FP64/FP16 denormal mode.
bool isInlineCompatible (SIModeRegisterDefaults CalleeMode) const
Static Public Member Functions
static SIModeRegisterDefaults getDefaultForCallingConv (CallingConv::ID CC)
static bool oneWayCompatible (bool CallerMode, bool CalleeMode)
Returns true if a flag is compatible if it's enabled in the callee, but disabled in the caller.
Public Attributes
bool IEEE: 1
Floating point opcodes that support exception flag gathering quiet and propagate signaling NaN inputs per IEEE 754-2008.
bool DX10Clamp: 1
Used by the vector ALU to force DX10-style treatment of NaNs: when set, clamp NaN to zero; otherwise, pass NaN through.
DenormalMode FP32Denormals
If this is set, neither input or output denormals are flushed for most f32 instructions.
DenormalMode FP64FP16Denormals
If this is set, neither input or output denormals are flushed for both f64 and f16/v2f16 instructions.
Detailed Description
Definition at line 1298 of file AMDGPUBaseInfo.h.
Constructor & Destructor Documentation
SIModeRegisterDefaults() [1/2]
llvm::AMDGPU::SIModeRegisterDefaults::SIModeRegisterDefaults () inline
Definition at line 1317 of file AMDGPUBaseInfo.h.
SIModeRegisterDefaults() [2/2]
llvm::AMDGPU::SIModeRegisterDefaults::SIModeRegisterDefaults (const Function & F)
Definition at line 2605 of file AMDGPUBaseInfo.cpp.
References DX10Clamp, F, FP32Denormals, FP64FP16Denormals, getDefaultForCallingConv(), IEEE, and llvm::parseDenormalFPAttribute().
Member Function Documentation
allFP32Denormals()
bool llvm::AMDGPU::SIModeRegisterDefaults::allFP32Denormals () const inline
Definition at line 1337 of file AMDGPUBaseInfo.h.
References FP32Denormals, and llvm::DenormalMode::getIEEE().
Referenced by hasFP32Denormals(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPUTargetLowering::LowerDIVREM24(), and llvm::AMDGPUTargetLowering::LowerUDIVREM64().
allFP64FP16Denormals()
bool llvm::AMDGPU::SIModeRegisterDefaults::allFP64FP16Denormals () const inline
Definition at line 1341 of file AMDGPUBaseInfo.h.
References FP64FP16Denormals, and llvm::DenormalMode::getIEEE().
Referenced by hasFP64FP16Denormals(), and llvm::AMDGPULegalizerInfo::legalizeFMad().
fpDenormModeDPValue()
uint32_t llvm::AMDGPU::SIModeRegisterDefaults::fpDenormModeDPValue () const inline
Get the encoding value for the FP_DENORM bits of the mode register for the FP64/FP16 denormal mode.
Definition at line 1359 of file AMDGPUBaseInfo.h.
References FP64FP16Denormals, FP_DENORM_FLUSH_IN, FP_DENORM_FLUSH_IN_FLUSH_OUT, FP_DENORM_FLUSH_NONE, FP_DENORM_FLUSH_OUT, llvm::DenormalMode::getPreserveSign(), llvm::DenormalMode::Input, llvm::DenormalMode::Output, and llvm::DenormalMode::PreserveSign.
fpDenormModeSPValue()
uint32_t llvm::AMDGPU::SIModeRegisterDefaults::fpDenormModeSPValue () const inline
Get the encoding value for the FP_DENORM bits of the mode register for the FP32 denormal mode.
Definition at line 1347 of file AMDGPUBaseInfo.h.
References FP32Denormals, FP_DENORM_FLUSH_IN, FP_DENORM_FLUSH_IN_FLUSH_OUT, FP_DENORM_FLUSH_NONE, FP_DENORM_FLUSH_OUT, llvm::DenormalMode::getPreserveSign(), llvm::DenormalMode::Input, llvm::DenormalMode::Output, and llvm::DenormalMode::PreserveSign.
getDefaultForCallingConv()
static SIModeRegisterDefaults llvm::AMDGPU::SIModeRegisterDefaults::getDefaultForCallingConv (CallingConv::ID CC) inline static
Definition at line 1325 of file AMDGPUBaseInfo.h.
References CC, IEEE, llvm::AMDGPU::isShader(), and Mode.
Referenced by SIModeRegisterDefaults().
isInlineCompatible()
bool llvm::AMDGPU::SIModeRegisterDefaults::isInlineCompatible (SIModeRegisterDefaults CalleeMode) const inline
Definition at line 1377 of file AMDGPUBaseInfo.h.
References DX10Clamp, FP32Denormals, FP64FP16Denormals, IEEE, llvm::DenormalMode::Input, oneWayCompatible(), llvm::DenormalMode::Output, and llvm::DenormalMode::PreserveSign.
oneWayCompatible()
static bool llvm::AMDGPU::SIModeRegisterDefaults::oneWayCompatible (bool CallerMode, bool CalleeMode) inline static
Returns true if a flag is compatible if it's enabled in the callee, but disabled in the caller.
Definition at line 1371 of file AMDGPUBaseInfo.h.
Referenced by isInlineCompatible().
operator==()
bool llvm::AMDGPU::SIModeRegisterDefaults::operator== (const SIModeRegisterDefaults Other) const inline
Definition at line 1331 of file AMDGPUBaseInfo.h.
References DX10Clamp, FP32Denormals, FP64FP16Denormals, IEEE, and llvm::Other.
Member Data Documentation
DX10Clamp
bool llvm::AMDGPU::SIModeRegisterDefaults::DX10Clamp
Used by the vector ALU to force DX10-style treatment of NaNs: when set, clamp NaN to zero; otherwise, pass NaN through.
Definition at line 1307 of file AMDGPUBaseInfo.h.
Referenced by isInlineCompatible(), operator==(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), and SIModeRegisterDefaults().
FP32Denormals
DenormalMode llvm::AMDGPU::SIModeRegisterDefaults::FP32Denormals
If this is set, neither input or output denormals are flushed for most f32 instructions.
Definition at line 1311 of file AMDGPUBaseInfo.h.
Referenced by allFP32Denormals(), fpDenormModeSPValue(), isInlineCompatible(), operator==(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), and SIModeRegisterDefaults().
FP64FP16Denormals
DenormalMode llvm::AMDGPU::SIModeRegisterDefaults::FP64FP16Denormals
If this is set, neither input or output denormals are flushed for both f64 and f16/v2f16 instructions.
Definition at line 1315 of file AMDGPUBaseInfo.h.
Referenced by allFP64FP16Denormals(), fpDenormModeDPValue(), isInlineCompatible(), operator==(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), and SIModeRegisterDefaults().
IEEE
bool llvm::AMDGPU::SIModeRegisterDefaults::IEEE
Floating point opcodes that support exception flag gathering quiet and propagate signaling NaN inputs per IEEE 754-2008.
Min_dx10 and max_dx10 become IEEE 754- 2008 compliant due to signaling NaN propagation and quieting.
Definition at line 1303 of file AMDGPUBaseInfo.h.
Referenced by getDefaultForCallingConv(), isInlineCompatible(), llvm::AMDGPULegalizerInfo::legalizeFFloor(), llvm::AMDGPULegalizerInfo::legalizeMinNumMaxNum(), llvm::AMDGPULegalizerInfo::legalizeRsqClampIntrinsic(), operator==(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), and SIModeRegisterDefaults().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.h
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.cpp