LLVM: llvm::MDNodeInfo< NodeTy > Struct Template Reference
llvm::MDNodeInfo< NodeTy > Struct Template Reference
DenseMapInfo for MDNode subclasses.
#include "IR/LLVMContextImpl.h"
Public Types
using KeyTy = MDNodeKeyImpl<NodeTy>
using SubsetEqualTy = MDNodeSubsetEqualImpl<NodeTy>
Static Public Member Functions
static NodeTy * getEmptyKey ()
static NodeTy * getTombstoneKey ()
static unsigned getHashValue (const KeyTy &Key)
static unsigned getHashValue (const NodeTy *N)
static bool isEqual (const KeyTy &LHS, const NodeTy *RHS)
static bool isEqual (const NodeTy *LHS, const NodeTy *RHS)
Detailed Description
template<class NodeTy>
struct llvm::MDNodeInfo< NodeTy >
DenseMapInfo for MDNode subclasses.
Definition at line 1315 of file LLVMContextImpl.h.
Member Typedef Documentation
KeyTy
template<class NodeTy > using llvm::MDNodeInfo< NodeTy >::KeyTy = MDNodeKeyImpl<NodeTy>
Definition at line 1316 of file LLVMContextImpl.h.
SubsetEqualTy
template<class NodeTy > using llvm::MDNodeInfo< NodeTy >::SubsetEqualTy = MDNodeSubsetEqualImpl<NodeTy>
Definition at line 1317 of file LLVMContextImpl.h.
Member Function Documentation
getEmptyKey()
template<class NodeTy > static NodeTy * llvm::MDNodeInfo< NodeTy >::getEmptyKey () inline static
Definition at line 1319 of file LLVMContextImpl.h.
Referenced by llvm::MDNodeInfo< NodeTy >::isEqual(), and llvm::MDNodeInfo< NodeTy >::isEqual().
getHashValue() [1/2]
template<class NodeTy > static unsigned llvm::MDNodeInfo< NodeTy >::getHashValue (const KeyTy & Key) inline static
Definition at line 1327 of file LLVMContextImpl.h.
getHashValue() [2/2]
template<class NodeTy > static unsigned llvm::MDNodeInfo< NodeTy >::getHashValue (const NodeTy * N) inline static
Definition at line 1329 of file LLVMContextImpl.h.
References N.
getTombstoneKey()
template<class NodeTy > static NodeTy * llvm::MDNodeInfo< NodeTy >::getTombstoneKey () inline static
Definition at line 1323 of file LLVMContextImpl.h.
Referenced by llvm::MDNodeInfo< NodeTy >::isEqual(), and llvm::MDNodeInfo< NodeTy >::isEqual().
isEqual() [1/2]
template<class NodeTy > static bool llvm::MDNodeInfo< NodeTy >::isEqual (const KeyTy & LHS, const NodeTy * RHS) inline static
Definition at line 1333 of file LLVMContextImpl.h.
References llvm::MDNodeInfo< NodeTy >::getEmptyKey(), and llvm::MDNodeInfo< NodeTy >::getTombstoneKey().
isEqual() [2/2]
template<class NodeTy > static bool llvm::MDNodeInfo< NodeTy >::isEqual (const NodeTy * LHS, const NodeTy * RHS) inline static
Definition at line 1339 of file LLVMContextImpl.h.
References llvm::MDNodeInfo< NodeTy >::getEmptyKey(), and llvm::MDNodeInfo< NodeTy >::getTombstoneKey().
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h