LLVM: llvm::coverage::CovMapFunctionRecordV3 Struct Reference
llvm::coverage::CovMapFunctionRecordV3 Struct Reference
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
Public Types
using ThisT = CovMapFunctionRecordV3
Public Member Functions
CovMapFunctionRecordV3 ()=delete
template<support::endianness Endian>
uint64_t getFuncHash () const
template<support::endianness Endian>
uint64_t getDataSize () const
template<support::endianness Endian>
uint64_t getFuncNameRef () const
template<support::endianness Endian>
Error getFuncName (InstrProfSymtab &ProfileNames, StringRef &FuncName) const
template<support::endianness Endian>
uint64_t getFilenamesRef () const
Get the filename set reference.
template<support::endianness Endian>
StringRef getCoverageMapping (const char *) const
Read the inline coverage mapping.
template<support::endianness Endian>
std::pair< const char *, const CovMapFunctionRecordV3 * > advanceByOne (const char *) const
Detailed Description
Definition at line 926 of file CoverageMapping.h.
Member Typedef Documentation
ThisT
using llvm::coverage::CovMapFunctionRecordV3::ThisT = CovMapFunctionRecordV3
Definition at line 927 of file CoverageMapping.h.
Constructor & Destructor Documentation
CovMapFunctionRecordV3()
llvm::coverage::CovMapFunctionRecordV3::CovMapFunctionRecordV3 () delete
Referenced by advanceByOne().
Member Function Documentation
advanceByOne()
template<support::endianness Endian> std::pair< const char *, const CovMapFunctionRecordV3 * > llvm::coverage::CovMapFunctionRecordV3::advanceByOne (const char *) const inline
Definition at line 969 of file CoverageMapping.h.
References Align, assert(), CovMapFunctionRecordV3(), llvm::isAddrAligned(), and llvm::offsetToAlignedAddr().
getCoverageMapping()
template<support::endianness Endian> StringRef llvm::coverage::CovMapFunctionRecordV3::getCoverageMapping (const char *) const inline
Read the inline coverage mapping.
Ignore the buffer parameter, it is for out-of-line coverage mapping data only.
Definition at line 961 of file CoverageMapping.h.
getDataSize()
template<support::endianness Endian> uint64_t llvm::coverage::CovMapFunctionRecordV3::getDataSize () const inline
Definition at line 939 of file CoverageMapping.h.
getFilenamesRef()
template<support::endianness Endian> uint64_t llvm::coverage::CovMapFunctionRecordV3::getFilenamesRef () const inline
Get the filename set reference.
Definition at line 954 of file CoverageMapping.h.
getFuncHash()
template<support::endianness Endian> uint64_t llvm::coverage::CovMapFunctionRecordV3::getFuncHash () const inline
Definition at line 935 of file CoverageMapping.h.
getFuncName()
template<support::endianness Endian> Error llvm::coverage::CovMapFunctionRecordV3::getFuncName (InstrProfSymtab & ProfileNames, StringRef & FuncName) const inline
Definition at line 948 of file CoverageMapping.h.
getFuncNameRef()
template<support::endianness Endian> uint64_t llvm::coverage::CovMapFunctionRecordV3::getFuncNameRef () const inline
Definition at line 943 of file CoverageMapping.h.
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/Coverage/CoverageMapping.h