LLVM: llvm::DerefState Struct Reference
llvm::DerefState Struct Reference
State for dereferenceable attribute.
#include "llvm/Transforms/IPO/Attributor.h"
Static Public Member Functions
static DerefState getBestState ()
static DerefState getBestState (const DerefState &)
static DerefState getWorstState ()
Return the worst possible representable state.
static DerefState getWorstState (const DerefState &)
Public Attributes
IncIntegerState DerefBytesState
State representing for dereferenceable bytes.
std::map< int64_t, uint64_t > AccessedBytesMap
Map representing for accessed memory offsets and sizes.
Additional Inherited Members
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
virtual bool isValidState () const =0
Return if this abstract state is in a valid state.
virtual bool isAtFixpoint () const =0
Return if this abstract state is fixed, thus does not need to be updated if information changes as it cannot change itself.
virtual ChangeStatus indicateOptimisticFixpoint ()=0
Indicate that the abstract state should converge to the optimistic state.
virtual ChangeStatus indicatePessimisticFixpoint ()=0
Indicate that the abstract state should converge to the pessimistic state.
Detailed Description
State for dereferenceable attribute.
Definition at line 3701 of file Attributor.h.
Member Function Documentation
getBestState() [1/2]
static DerefState llvm::DerefState::getBestState () inline static
Definition at line 3703 of file Attributor.h.
getBestState() [2/2]
static DerefState llvm::DerefState::getBestState (const DerefState &) inline static
Definition at line 3704 of file Attributor.h.
References getBestState().
Referenced by getBestState().
getWorstState() [1/2]
static DerefState llvm::DerefState::getWorstState () inline static
Return the worst possible representable state.
Definition at line 3707 of file Attributor.h.
Referenced by getWorstState().
getWorstState() [2/2]
static DerefState llvm::DerefState::getWorstState (const DerefState &) inline static
Definition at line 3712 of file Attributor.h.
References getWorstState().
Member Data Documentation
AccessedBytesMap
std::map<int64_t, uint64_t> llvm::DerefState::AccessedBytesMap
Map representing for accessed memory offsets and sizes.
A key is Offset and a value is size. If there is a load/store instruction something like, p[offset] = v; (offset, sizeof(v)) will be inserted to this map. std::map is used because we want to iterate keys in ascending order.
Definition at line 3725 of file Attributor.h.
DerefBytesState
IncIntegerState llvm::DerefState::DerefBytesState
State representing for dereferenceable bytes.
Definition at line 3717 of file Attributor.h.
Referenced by llvm::clampStateAndIndicateChange< DerefState >(), llvm::AADereferenceable::getAssumedDereferenceableBytes(), and llvm::AADereferenceable::getKnownDereferenceableBytes().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h