LLVM: lib/Transforms/Utils/SymbolRewriter.cpp File Reference
SymbolRewriter.cpp File Reference
#include "llvm/Transforms/Utils/SymbolRewriter.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/ilist.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Regex.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/YAMLParser.h"
#include <memory>
#include <string>
#include <vector>
Macros
#define DEBUG_TYPE "symbol-rewriter"
Functions
static void rewriteComdat (Module &M, GlobalObject *GO, const std::string &Source, const std::string &Target)
INITIALIZE_PASS (RewriteSymbolsLegacyPass, "rewrite-symbols", "Rewrite Symbols", false, false) ModulePass *llvm
Variables
static cl::list< std::string > RewriteMapFiles ("rewrite-map-file", cl::desc("Symbol Rewrite Map"), cl::value_desc("filename"), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "symbol-rewriter"
Definition at line 88 of file SymbolRewriter.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RewriteSymbolsLegacyPass , "rewrite-symbols" , "Rewrite Symbols" , false , false)
Definition at line 576 of file SymbolRewriter.cpp.
rewriteComdat()
static void rewriteComdat (Module & M, GlobalObject * GO, const std::string & Source, const std::string & Target) static
Definition at line 95 of file SymbolRewriter.cpp.
References llvm::CallingConv::C, llvm::GlobalObject::getComdat(), llvm::GlobalObject::setComdat(), and llvm::Comdat::setSelectionKind().
Variable Documentation
RewriteMapFiles
cl::list< std::string > RewriteMapFiles("rewrite-map-file", cl::desc("Symbol Rewrite Map"), cl::value_desc("filename"), cl::Hidden) ("rewrite-map-file" , cl::desc("Symbol Rewrite Map") , cl::value_desc("filename") , cl::Hidden) static