LLVM: lib/Target/SystemZ/SystemZSelectionDAGInfo.cpp File Reference
SystemZSelectionDAGInfo.cpp File Reference
#include "SystemZTargetMachine.h"
#include "llvm/CodeGen/SelectionDAG.h"
Macros
#define DEBUG_TYPE "systemz-selectiondag-info"
Functions
static unsigned getMemMemLenAdj (unsigned Op)
static SDValue createMemMemNode (SelectionDAG &DAG, const SDLoc &DL, unsigned Op, SDValue Chain, SDValue Dst, SDValue Src, SDValue LenAdj, SDValue Byte)
static SDValue emitMemMemImm (SelectionDAG &DAG, const SDLoc &DL, unsigned Op, SDValue Chain, SDValue Dst, SDValue Src, uint64_t Size, SDValue Byte=SDValue())
static SDValue emitMemMemReg (SelectionDAG &DAG, const SDLoc &DL, unsigned Op, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, SDValue Byte=SDValue())
static SDValue memsetStore (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Dst, uint64_t ByteVal, uint64_t Size, Align Alignment, MachinePointerInfo DstPtrInfo)
static SDValue addIPMSequence (const SDLoc &DL, SDValue CCReg, SelectionDAG &DAG)
static std::pair< SDValue, SDValue > getBoundedStrlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, SDValue Limit)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "systemz-selectiondag-info"
Definition at line 18 of file SystemZSelectionDAGInfo.cpp.
Function Documentation
addIPMSequence()
static SDValue addIPMSequence (const SDLoc & DL, SDValue CCReg, SelectionDAG & DAG) static
Definition at line 162 of file SystemZSelectionDAGInfo.cpp.
References DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i32, llvm::SystemZISD::IPM, llvm::SystemZ::IPM_CC, llvm::ISD::SHL, and llvm::ISD::SRA.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp(), and llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp().
createMemMemNode()
static SDValue createMemMemNode (SelectionDAG & DAG, const SDLoc & DL, unsigned Op, SDValue Chain, SDValue Dst, SDValue Src, SDValue LenAdj, SDValue Byte) static
Definition at line 24 of file SystemZSelectionDAGInfo.cpp.
References llvm::SystemZISD::CLC, DL, llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::SystemZISD::MEMSET_MVC, and llvm::MVT::Other.
Referenced by emitMemMemImm(), and emitMemMemReg().
emitMemMemImm()
static SDValue emitMemMemImm (SelectionDAG & DAG, const SDLoc & DL, unsigned Op, SDValue Chain, SDValue Dst, SDValue Src, uint64_t Size, SDValue Byte = SDValue()) static
Definition at line 41 of file SystemZSelectionDAGInfo.cpp.
References assert(), createMemMemNode(), DL, llvm::SelectionDAG::getConstant(), getMemMemLenAdj(), and Size.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcpy(), and llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset().
emitMemMemReg()
static SDValue emitMemMemReg (SelectionDAG & DAG, const SDLoc & DL, unsigned Op, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, SDValue Byte = SDValue()) static
Definition at line 50 of file SystemZSelectionDAGInfo.cpp.
References llvm::ISD::ADD, createMemMemNode(), DL, llvm::SelectionDAG::getConstant(), getMemMemLenAdj(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::MVT::i64, and Size.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcpy(), and llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset().
getBoundedStrlen()
static std::pair< SDValue, SDValue > getBoundedStrlen (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Src, SDValue Limit) static
Definition at line 242 of file SystemZSelectionDAGInfo.cpp.
References DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::MVT::Other, llvm::SystemZISD::SEARCH_STRING, and llvm::ISD::SUB.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrlen(), and llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen().
getMemMemLenAdj()
static unsigned getMemMemLenAdj (unsigned Op) static
Definition at line 20 of file SystemZSelectionDAGInfo.cpp.
References llvm::SystemZISD::MEMSET_MVC.
Referenced by emitMemMemImm(), and emitMemMemReg().
memsetStore()
static SDValue memsetStore (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Dst, uint64_t ByteVal, uint64_t Size, Align Alignment, MachinePointerInfo DstPtrInfo) static
Definition at line 77 of file SystemZSelectionDAGInfo.cpp.
References DL, llvm::SelectionDAG::getConstant(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getStore(), I, and Size.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset().