LLVM: lib/IR/Type.cpp File Reference
Type.cpp File Reference
#include "llvm/IR/Type.h"
#include "LLVMContextImpl.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/TypeSize.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <utility>
Functions
static TargetTypeInfo getTargetTypeInfo (const TargetExtType *Ty)
Function Documentation
getTargetTypeInfo()
static TargetTypeInfo getTargetTypeInfo (const TargetExtType * Ty) static
Definition at line 850 of file Type.cpp.
References llvm::CallingConv::C, llvm::TargetExtType::CanBeGlobal, llvm::Type::getInt8PtrTy(), llvm::Type::getVoidTy(), llvm::TargetExtType::HasZeroInit, and Name.
Referenced by llvm::TargetExtType::getLayoutType(), and llvm::TargetExtType::hasProperty().