LLVM: lib/Transforms/Utils/UnifyLoopExits.cpp File Reference
UnifyLoopExits.cpp File Reference
#include "llvm/Transforms/Utils/UnifyLoopExits.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/Analysis/DomTreeUpdater.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Dominators.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "unify-loop-exits"
Functions
INITIALIZE_PASS_BEGIN (UnifyLoopExitsLegacyPass, "unify-loop-exits", "Fixup each natural loop to have a single exit block", false, false) INITIALIZE_PASS_END(UnifyLoopExitsLegacyPass
unify loop Fixup each natural loop to have a single exit static false void restoreSSA (const DominatorTree &DT, const Loop *L, const SetVector< BasicBlock * > &Incoming, BasicBlock *LoopExitBlock)
static bool unifyLoopExits (DominatorTree &DT, LoopInfo &LI, Loop *L)
static bool runImpl (LoopInfo &LI, DominatorTree &DT)
Variables
static cl::opt< unsigned > MaxBooleansInControlFlowHub ("max-booleans-in-control-flow-hub", cl::init(32), cl::Hidden, cl::desc("Set the maximum number of outgoing blocks for using a boolean " "value to record the exiting block in CreateControlFlowHub."))
unify loop exits
unify loop Fixup each natural loop to have a single exit block
unify loop Fixup each natural loop to have a single exit false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "unify-loop-exits"
Definition at line 30 of file UnifyLoopExits.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (UnifyLoopExitsLegacyPass , "unify-loop-exits" , "Fixup each natural loop to have a single exit block" , false , false)
restoreSSA()
unify loop Fixup each natural loop to have a single exit static false void restoreSSA (const DominatorTree & DT, const Loop * L, const SetVector< BasicBlock * > & Incoming, BasicBlock * LoopExitBlock) static
Definition at line 91 of file UnifyLoopExits.cpp.
References llvm::PHINode::Create(), llvm::dbgs(), llvm::UndefValue::get(), I, and LLVM_DEBUG.
Referenced by unifyLoopExits().
runImpl()
static bool runImpl (LoopInfo & LI, DominatorTree & DT) static
Definition at line 219 of file UnifyLoopExits.cpp.
References llvm::dbgs(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopDepth(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInPreorder(), LLVM_DEBUG, Loops, and unifyLoopExits().
unifyLoopExits()
static bool unifyLoopExits (DominatorTree & DT, LoopInfo & LI, Loop * L) static
Definition at line 146 of file UnifyLoopExits.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::CreateControlFlowHub(), llvm::dbgs(), G, llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), LLVM_DEBUG, MaxBooleansInControlFlowHub, restoreSSA(), llvm::successors(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), llvm::DominatorTreeBase< NodeT, IsPostDom >::verify(), and llvm::LoopBase< BlockT, LoopT >::verifyLoop().
Referenced by runImpl().
Variable Documentation
block
unify loop Fixup each natural loop to have a single exit block
Definition at line 72 of file UnifyLoopExits.cpp.
Referenced by llvm::GenericSSAContext< Function >::appendBlockDefs(), llvm::GenericSSAContext< MachineFunction >::appendBlockDefs(), llvm::GenericSSAContext< Function >::appendBlockDefs(), llvm::GenericSSAContext< Function >::appendBlockTerms(), llvm::GenericSSAContext< MachineFunction >::appendBlockTerms(), llvm::GenericSSAContext< Function >::appendBlockTerms(), llvm::BCBlockRAII::BCBlockRAII(), blake3_compress_in_place(), blake3_compress_in_place_avx512(), blake3_compress_in_place_portable(), blake3_compress_in_place_sse2(), blake3_compress_in_place_sse41(), blake3_compress_xof(), blake3_compress_xof_avx512(), blake3_compress_xof_portable(), blake3_compress_xof_sse2(), blake3_compress_xof_sse41(), blake3_hash16_avx512(), blake3_hash4_avx512(), blake3_hash4_sse2(), blake3_hash4_sse41(), blake3_hash8_avx2(), blake3_hash8_avx512(), compress_pre(), compress_pre(), llvm::GCOVBlock::getCyclesCount(), llvm::GenericUniformityAnalysisImpl< ContextT >::initialize(), LLVMSetSuccessor(), make_output(), parent_output(), llvm::GenericUniformityAnalysisImpl< ContextT >::print(), and llvm::GCOVFile::readGCDA().
exits
unify loop exits
Definition at line 71 of file UnifyLoopExits.cpp.
false
unify loop Fixup each natural loop to have a single exit false
Definition at line 73 of file UnifyLoopExits.cpp.
MaxBooleansInControlFlowHub
cl::opt< unsigned > MaxBooleansInControlFlowHub("max-booleans-in-control-flow-hub", cl::init(32), cl::Hidden, cl::desc("Set the maximum number of outgoing blocks for using a boolean " "value to record the exiting block in CreateControlFlowHub.")) ("max-booleans-in-control-flow-hub" , cl::init(32) , cl::Hidden , cl::desc("Set the maximum number of outgoing blocks for using a boolean " "value to record the exiting block in CreateControlFlowHub.")) static
Referenced by unifyLoopExits().