LLVM: lib/Target/VE/VETargetTransformInfo.h File Reference
VETargetTransformInfo.h File Reference
This file a TargetTransformInfo::Concept conforming object specific to the VE target machine.
#include "VE.h"
#include "VETargetMachine.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/BasicTTIImpl.h"
Classes
class llvm::VETTIImpl
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define VEC_VP_CASE(SUFFIX)
Functions
static llvm::Type * getVectorElementType (llvm::Type *Ty)
static llvm::Type * getLaneType (llvm::Type *Ty)
static bool isVectorLaneType (llvm::Type &ElemTy)
Detailed Description
This file a TargetTransformInfo::Concept conforming object specific to the VE target machine.
It uses the target's detailed information to provide more precise answers to certain TTI queries, while letting the target independent and default TTI implementations handle the rest.
Definition in file VETargetTransformInfo.h.
Macro Definition Documentation
VEC_VP_CASE
#define VEC_VP_CASE (SUFFIX)
Value:
  case Intrinsic::vp_reduce_##SUFFIX:                                          \
  case Intrinsic::vector_reduce_##SUFFIX:
Function Documentation
getLaneType()
static llvm::Type * getLaneType (llvm::Type * Ty) static
Definition at line 28 of file VETargetTransformInfo.h.
References getVectorElementType().
Referenced by llvm::VETTIImpl::isLegalMaskedGather(), llvm::VETTIImpl::isLegalMaskedLoad(), llvm::VETTIImpl::isLegalMaskedScatter(), and llvm::VETTIImpl::isLegalMaskedStore().
getVectorElementType()
static llvm::Type * getVectorElementType (llvm::Type * Ty) static
Definition at line 24 of file VETargetTransformInfo.h.
Referenced by getLaneType(), and llvm::HexagonTargetLowering::LowerINSERT_VECTOR_ELT().
isVectorLaneType()
static bool isVectorLaneType (llvm::Type & ElemTy) static
Definition at line 35 of file VETargetTransformInfo.h.
Referenced by llvm::VETTIImpl::isLegalMaskedGather(), llvm::VETTIImpl::isLegalMaskedLoad(), llvm::VETTIImpl::isLegalMaskedScatter(), and llvm::VETTIImpl::isLegalMaskedStore().