LLVM: lib/Target/AMDGPU/AMDGPUISelLowering.cpp File Reference
AMDGPUISelLowering.cpp File Reference
This is the parent TargetLowering class for hardware code gen targets.
#include "AMDGPUISelLowering.h"
#include "AMDGPU.h"
#include "AMDGPUInstrInfo.h"
#include "AMDGPUMachineFunction.h"
#include "SIMachineFunctionInfo.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/GlobalISel/GISelKnownBits.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Target/TargetMachine.h"
#include "AMDGPUGenCallingConv.inc"
Macros
#define NODE_NAME_CASE(node) case AMDGPUISD::node: return #node;
Functions
static LLVM_READNONE bool fnegFoldsIntoOpcode (unsigned Opc)
static bool fnegFoldsIntoOp (const SDNode *N)
static LLVM_READONLY bool opMustUseVOP3Encoding (const SDNode *N, MVT VT)
returns true if the operation will definitely need to use a 64-bit encoding, and thus will use a VOP3 encoding regardless of the source modifiers.
static LLVM_READONLY bool selectSupportsSourceMods (const SDNode *N)
Return true if v_cndmask_b32 will support fabs/fneg source modifiers for the type for ISD::SELECT.
static LLVM_READONLY bool hasSourceMods (const SDNode *N)
static SDValue peekFNeg (SDValue Val)
static SDValue peekFPSignOps (SDValue Val)
static SDValue extractF64Exponent (SDValue Hi, const SDLoc &SL, SelectionDAG &DAG)
static bool valueIsKnownNeverF32Denorm (SDValue Src)
Return true if it's known that Src can never be an f32 denormal value.
static bool allowApproxFunc (const SelectionDAG &DAG, SDNodeFlags Flags)
static bool needsDenormHandlingF32 (const SelectionDAG &DAG, SDValue Src, SDNodeFlags Flags)
static SDValue getMad (SelectionDAG &DAG, const SDLoc &SL, EVT VT, SDValue X, SDValue Y, SDValue C, SDNodeFlags Flags=SDNodeFlags())
static bool isCtlzOpc (unsigned Opc)
static bool isCttzOpc (unsigned Opc)
static bool isU24 (SDValue Op, SelectionDAG &DAG)
static bool isI24 (SDValue Op, SelectionDAG &DAG)
static SDValue simplifyMul24 (SDNode *Node24, TargetLowering::DAGCombinerInfo &DCI)
template<typename IntTy >
static SDValue constantFoldBFE (SelectionDAG &DAG, IntTy Src0, uint32_t Offset, uint32_t Width, const SDLoc &DL)
static bool hasVolatileUser (SDNode *Val)
static SDValue getMul24 (SelectionDAG &DAG, const SDLoc &SL, SDValue N0, SDValue N1, unsigned Size, bool Signed)
static SDValue getAddOneOp (const SDNode *V)
If V is an add of a constant 1, returns the other operand.
static SDValue distributeOpThroughSelect (TargetLowering::DAGCombinerInfo &DCI, unsigned Op, const SDLoc &SL, SDValue Cond, SDValue N1, SDValue N2)
static bool isInv2Pi (const APFloat &APF)
static unsigned inverseMinMax (unsigned Opc)
static int getOrCreateFixedStackObject (MachineFrameInfo &MFI, unsigned Size, int64_t Offset)
static unsigned workitemIntrinsicDim (unsigned ID)
Variables
static cl::opt< bool > AMDGPUBypassSlowDiv ("amdgpu-bypass-slow-div", cl::desc("Skip 64-bit divide for dynamic 32-bit values"), cl::init(true))
Detailed Description
This is the parent TargetLowering class for hardware code gen targets.
Definition in file AMDGPUISelLowering.cpp.
Macro Definition Documentation
NODE_NAME_CASE
#define NODE_NAME_CASE (node) case AMDGPUISD::node: return #node;
Definition at line 5127 of file AMDGPUISelLowering.cpp.
Referenced by llvm::AMDGPUTargetLowering::getTargetNodeName(), llvm::LoongArchTargetLowering::getTargetNodeName(), llvm::RISCVTargetLowering::getTargetNodeName(), and llvm::X86TargetLowering::getTargetNodeName().
Function Documentation
allowApproxFunc()
static bool allowApproxFunc (const SelectionDAG & DAG, SDNodeFlags Flags) static
Definition at line 2479 of file AMDGPUISelLowering.cpp.
References llvm::SelectionDAG::getTarget(), llvm::TargetMachine::Options, and Options.
Referenced by llvm::AMDGPULegalizerInfo::legalizeFExp(), and llvm::AMDGPUTargetLowering::lowerFEXP().
constantFoldBFE()
template<typename IntTy > static SDValue constantFoldBFE (SelectionDAG & DAG, IntTy Src0, uint32_t Offset, uint32_t Width, const SDLoc & DL) static
Definition at line 3512 of file AMDGPUISelLowering.cpp.
References DL, llvm::SelectionDAG::getConstant(), and llvm::Offset.
distributeOpThroughSelect()
static SDValue distributeOpThroughSelect (TargetLowering::DAGCombinerInfo & DCI, unsigned Op, const SDLoc & SL, SDValue Cond, SDValue N1, SDValue N2) static
Definition at line 4278 of file AMDGPUISelLowering.cpp.
References Cond, llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), and llvm::ISD::SELECT.
Referenced by llvm::AMDGPUTargetLowering::foldFreeOpFromSelect().
extractF64Exponent()
static SDValue extractF64Exponent (SDValue Hi, const SDLoc & SL, SelectionDAG & DAG) static
Definition at line 2304 of file AMDGPUISelLowering.cpp.
References llvm::AMDGPUISD::BFE_U32, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::Hi, and llvm::ISD::SUB.
Referenced by llvm::AMDGPULegalizerInfo::legalizeIntrinsicTrunc(), and llvm::AMDGPUTargetLowering::LowerFTRUNC().
fnegFoldsIntoOp()
static bool fnegFoldsIntoOp (const SDNode * N) static
Definition at line 605 of file AMDGPUISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, fnegFoldsIntoOpcode(), N, and llvm::ISD::SELECT.
Referenced by llvm::AMDGPUTargetLowering::foldFreeOpFromSelect(), llvm::AMDGPUTargetLowering::performFNegCombine(), and llvm::AMDGPUTargetLowering::shouldFoldFNegIntoSrc().
fnegFoldsIntoOpcode()
static LLVM_READNONE bool fnegFoldsIntoOpcode (unsigned Opc) static
Definition at line 571 of file AMDGPUISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::FADD, llvm::ISD::FCANONICALIZE, llvm::ISD::FMA, llvm::ISD::FMAD, llvm::AMDGPUISD::FMAX_LEGACY, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::AMDGPUISD::FMED3, llvm::AMDGPUISD::FMIN_LEGACY, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, llvm::ISD::FMUL, llvm::AMDGPUISD::FMUL_LEGACY, llvm::ISD::FNEARBYINT, llvm::ISD::FRINT, llvm::ISD::FSIN, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm_unreachable, llvm::AMDGPUISD::RCP, llvm::AMDGPUISD::RCP_IFLAG, llvm::AMDGPUISD::RCP_LEGACY, llvm::ISD::SELECT, and llvm::AMDGPUISD::SIN_HW.
Referenced by fnegFoldsIntoOp().
getAddOneOp()
static SDValue getAddOneOp (const SDNode * V) static
If V is an add of a constant 1, returns the other operand.
Otherwise return SDValue().
Definition at line 4011 of file AMDGPUISelLowering.cpp.
References llvm::ISD::ADD, and llvm::CallingConv::C.
Referenced by llvm::AMDGPUTargetLowering::performMulCombine().
getMad()
static SDValue getMad (SelectionDAG & DAG, const SDLoc & SL, EVT VT, SDValue X, SDValue Y, SDValue C, SDNodeFlags Flags = SDNodeFlags()) static
Definition at line 2587 of file AMDGPUISelLowering.cpp.
References llvm::CallingConv::C, llvm::ISD::FADD, llvm::ISD::FMUL, llvm::SelectionDAG::getNode(), llvm::Mul, X, and Y.
Referenced by llvm::AMDGPULegalizerInfo::legalizeFExp(), llvm::AMDGPULegalizerInfo::legalizeFlogCommon(), llvm::AMDGPUTargetLowering::lowerFEXP(), and llvm::AMDGPUTargetLowering::LowerFLOGCommon().
getMul24()
static SDValue getMul24 (SelectionDAG & DAG, const SDLoc & SL, SDValue N0, SDValue N1, unsigned Size, bool Signed) static
Definition at line 3993 of file AMDGPUISelLowering.cpp.
References llvm::ISD::BUILD_PAIR, llvm::SelectionDAG::getNode(), llvm::AMDGPUISD::MUL_I24, llvm::AMDGPUISD::MUL_U24, llvm::AMDGPUISD::MULHI_I24, llvm::AMDGPUISD::MULHI_U24, Signed, and Size.
getOrCreateFixedStackObject()
static int getOrCreateFixedStackObject (MachineFrameInfo & MFI, unsigned Size, int64_t Offset) static
Definition at line 5034 of file AMDGPUISelLowering.cpp.
References assert(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), I, llvm::Offset, and Size.
Referenced by llvm::AMDGPUTargetLowering::loadStackInputValue().
hasSourceMods()
static LLVM_READONLY bool hasSourceMods (const SDNode * N) static
Definition at line 642 of file AMDGPUISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::CopyToReg, llvm::AMDGPUISD::DIV_SCALE, llvm::ISD::FDIV, llvm::ISD::FREM, llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, N, llvm::ISD::SELECT, and selectSupportsSourceMods().
hasVolatileUser()
static bool hasVolatileUser (SDNode * Val) static
Definition at line 3523 of file AMDGPUISelLowering.cpp.
References llvm::SDNode::uses().
Referenced by llvm::AMDGPUTargetLowering::performLoadCombine().
inverseMinMax()
static unsigned inverseMinMax (unsigned Opc) static
Definition at line 4459 of file AMDGPUISelLowering.cpp.
References llvm::AMDGPUISD::FMAX_LEGACY, llvm::ISD::FMAXNUM, llvm::ISD::FMAXNUM_IEEE, llvm::AMDGPUISD::FMIN_LEGACY, llvm::ISD::FMINNUM, llvm::ISD::FMINNUM_IEEE, and llvm_unreachable.
isCtlzOpc()
static bool isCtlzOpc (unsigned Opc) static
Definition at line 2929 of file AMDGPUISelLowering.cpp.
References llvm::ISD::CTLZ, and llvm::ISD::CTLZ_ZERO_UNDEF.
Referenced by llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), and llvm::AMDGPUTargetLowering::performCtlz_CttzCombine().
isCttzOpc()
static bool isCttzOpc (unsigned Opc) static
Definition at line 2933 of file AMDGPUISelLowering.cpp.
References llvm::ISD::CTTZ, and llvm::ISD::CTTZ_ZERO_UNDEF.
Referenced by llvm::AMDGPUTargetLowering::LowerCTLZ_CTTZ(), and llvm::AMDGPUTargetLowering::performCtlz_CttzCombine().
isI24()
static bool isI24 (SDValue Op, SelectionDAG & DAG) static
Definition at line 3453 of file AMDGPUISelLowering.cpp.
References llvm::EVT::getSizeInBits(), and llvm::AMDGPUTargetLowering::numBitsSigned().
Referenced by llvm::AMDGPUTargetLowering::performMulCombine(), llvm::AMDGPUTargetLowering::performMulhsCombine(), and llvm::AMDGPUTargetLowering::performMulLoHiCombine().
isInv2Pi()
static bool isInv2Pi (const APFloat & APF) static
Definition at line 4424 of file AMDGPUISelLowering.cpp.
References llvm::APFloatBase::IEEEdouble(), llvm::APFloatBase::IEEEhalf(), and llvm::APFloatBase::IEEEsingle().
isU24()
static bool isU24 (SDValue Op, SelectionDAG & DAG) static
Definition at line 3449 of file AMDGPUISelLowering.cpp.
References llvm::AMDGPUTargetLowering::numBitsUnsigned().
Referenced by llvm::AMDGPUTargetLowering::performMulCombine(), llvm::AMDGPUTargetLowering::performMulhuCombine(), and llvm::AMDGPUTargetLowering::performMulLoHiCombine().
needsDenormHandlingF32()
static bool needsDenormHandlingF32 (const SelectionDAG & DAG, SDValue Src, SDNodeFlags Flags) static
Definition at line 2486 of file AMDGPUISelLowering.cpp.
References llvm::MachineFunction::getDenormalMode(), llvm::SelectionDAG::getMachineFunction(), llvm::APFloatBase::IEEEsingle(), llvm::DenormalMode::Input, llvm::DenormalMode::PreserveSign, and valueIsKnownNeverF32Denorm().
Referenced by llvm::AMDGPULegalizerInfo::getScaledLogInput(), llvm::AMDGPUTargetLowering::getScaledLogInput(), llvm::AMDGPULegalizerInfo::legalizeFExp(), llvm::AMDGPULegalizerInfo::legalizeFExp2(), llvm::AMDGPUTargetLowering::lowerFEXP(), and llvm::AMDGPUTargetLowering::lowerFEXP2().
opMustUseVOP3Encoding()
static LLVM_READONLY bool opMustUseVOP3Encoding (const SDNode * N, MVT VT) static
returns true if the operation will definitely need to use a 64-bit encoding, and thus will use a VOP3 encoding regardless of the source modifiers.
Definition at line 626 of file AMDGPUISelLowering.cpp.
References N, and llvm::ISD::SELECT.
peekFNeg()
static SDValue peekFNeg (SDValue Val) static
Definition at line 1493 of file AMDGPUISelLowering.cpp.
References llvm::ISD::FNEG, llvm::SDValue::getOpcode(), and llvm::SDValue::getOperand().
Referenced by llvm::AMDGPUTargetLowering::combineFMinMaxLegacy().
peekFPSignOps()
static SDValue peekFPSignOps (SDValue Val) static
Definition at line 1500 of file AMDGPUISelLowering.cpp.
References llvm::ISD::FABS, llvm::ISD::FCOPYSIGN, llvm::ISD::FNEG, llvm::SDValue::getOpcode(), and llvm::SDValue::getOperand().
Referenced by llvm::AMDGPUTargetLowering::performIntrinsicWOChainCombine().
selectSupportsSourceMods()
static LLVM_READONLY bool selectSupportsSourceMods (const SDNode * N) static
Return true if v_cndmask_b32 will support fabs/fneg source modifiers for the type for ISD::SELECT.
Definition at line 634 of file AMDGPUISelLowering.cpp.
References N.
Referenced by llvm::AMDGPUTargetLowering::foldFreeOpFromSelect(), and hasSourceMods().
simplifyMul24()
static SDValue simplifyMul24 (SDNode * Node24, TargetLowering::DAGCombinerInfo & DCI) static
Definition at line 3460 of file AMDGPUISelLowering.cpp.
References llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::ISD::INTRINSIC_WO_CHAIN, LHS, llvm_unreachable, llvm::AMDGPUISD::MUL_I24, llvm::AMDGPUISD::MUL_U24, llvm::AMDGPUISD::MULHI_I24, llvm::AMDGPUISD::MULHI_U24, RHS, llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifyMultipleUseDemandedBits().
Referenced by llvm::AMDGPUTargetLowering::PerformDAGCombine(), and llvm::AMDGPUTargetLowering::performIntrinsicWOChainCombine().
valueIsKnownNeverF32Denorm()
static bool valueIsKnownNeverF32Denorm (SDValue Src) static
Return true if it's known that Src can never be an f32 denormal value.
Definition at line 2466 of file AMDGPUISelLowering.cpp.
References llvm::ISD::FP16_TO_FP, llvm::ISD::FP_EXTEND, and llvm_unreachable.
Referenced by needsDenormHandlingF32(), and needsDenormHandlingF32().
workitemIntrinsicDim()
static unsigned workitemIntrinsicDim (unsigned ID) static
Definition at line 5322 of file AMDGPUISelLowering.cpp.
References llvm_unreachable.
Referenced by llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode().
Variable Documentation
AMDGPUBypassSlowDiv
cl::opt< bool > AMDGPUBypassSlowDiv("amdgpu-bypass-slow-div", cl::desc("Skip 64-bit divide for dynamic 32-bit values"), cl::init(true)) ("amdgpu-bypass-slow-div" , cl::desc("Skip 64-bit divide for dynamic 32-bit values") , cl::init(true)) static
Referenced by llvm::AMDGPUTargetLowering::AMDGPUTargetLowering().