LLVM: lib/CodeGen/BasicBlockSections.cpp File Reference
BasicBlockSections.cpp File Reference
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/CodeGen/BasicBlockSectionUtils.h"
#include "llvm/CodeGen/BasicBlockSectionsProfileReader.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Target/TargetMachine.h"
#include <optional>
Functions
INITIALIZE_PASS_BEGIN (BasicBlockSections, "bbsections-prepare", "Prepares for basic block sections, by splitting functions " "into clusters of basic blocks.", false, false) INITIALIZE_PASS_END(BasicBlockSections
bbsections Prepares for basic block by splitting functions into clusters of basic static false void updateBranches (MachineFunction &MF, const SmallVector< MachineBasicBlock * > &PreLayoutFallThroughs)
bool getBBClusterInfoForFunction (const MachineFunction &MF, BasicBlockSectionsProfileReader *BBSectionsProfileReader, DenseMap< unsigned, BBClusterInfo > &V)
static void assignSections (MachineFunction &MF, const DenseMap< unsigned, BBClusterInfo > &FuncBBClusterInfo)
static bool hasInstrProfHashMismatch (MachineFunction &MF)
Variables
static cl::opt< bool > BBSectionsDetectSourceDrift ("bbsections-detect-source-drift", cl::desc("This checks if there is a fdo instr. profile hash " "mismatch for this function"), cl::init(true), cl::Hidden)
bbsections prepare
bbsections Prepares for basic block sections
bbsections Prepares for basic block by splitting functions into clusters of basic blocks
bbsections Prepares for basic block by splitting functions into clusters of basic false
Function Documentation
assignSections()
static void assignSections (MachineFunction & MF, const DenseMap< unsigned, BBClusterInfo > & FuncBBClusterInfo) static
Definition at line 207 of file BasicBlockSections.cpp.
References llvm::All, assert(), llvm::MBBSectionID::ColdSectionID, llvm::MBBSectionID::ExceptionSectionID, llvm::MachineBasicBlock::getBBIDOrNumber(), llvm::TargetMachine::getBBSectionsType(), llvm::MachineBasicBlock::getNumber(), llvm::MachineBasicBlock::getSectionID(), llvm::MachineFunction::getTarget(), llvm::MachineFunction::hasBBSections(), I, llvm::MachineBasicBlock::isEHPad(), MBB, and llvm::MachineBasicBlock::setSectionID().
getBBClusterInfoForFunction()
bool getBBClusterInfoForFunction (const MachineFunction & MF, BasicBlockSectionsProfileReader * BBSectionsProfileReader, DenseMap< unsigned, BBClusterInfo > & V)
Definition at line 173 of file BasicBlockSections.cpp.
References llvm::BasicBlockSectionsProfileReader::getBBClusterInfoForFunction(), llvm::MachineFunction::getName(), and P.
Referenced by INITIALIZE_PASS().
hasInstrProfHashMismatch()
static bool hasInstrProfHashMismatch (MachineFunction & MF) static
Definition at line 300 of file BasicBlockSections.cpp.
References BBSectionsDetectSourceDrift, llvm::MachineFunction::getFunction(), llvm::GlobalObject::getMetadata(), and N.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (BasicBlockSections , "bbsections-prepare" , "Prepares for basic block sections, by splitting functions " "into clusters of basic blocks." , false , false)
updateBranches()
bbsections Prepares for basic block by splitting functions into clusters of basic static false void updateBranches (MachineFunction & MF, const SmallVector< MachineBasicBlock * > & PreLayoutFallThroughs) static
Definition at line 140 of file BasicBlockSections.cpp.
References llvm::HexagonInstrInfo::analyzeBranch(), Cond, llvm::MachineBasicBlock::findBranchDebugLoc(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineBasicBlock::getNumber(), llvm::MachineBasicBlock::isEndSection(), MBB, TBB, TII, and llvm::MachineBasicBlock::updateTerminator().
Referenced by llvm::sortBasicBlocksAndUpdateBranches().
Variable Documentation
BBSectionsDetectSourceDrift
cl::opt< bool > BBSectionsDetectSourceDrift("bbsections-detect-source-drift", cl::desc("This checks if there is a fdo instr. profile hash " "mismatch for this function"), cl::init(true), cl::Hidden) ("bbsections-detect-source-drift" , cl::desc("This checks if there is a fdo instr. profile hash " "mismatch for this function") , cl::init(true) , cl::Hidden) static
Referenced by hasInstrProfHashMismatch().
blocks
bbsections Prepares for basic block by splitting functions into clusters of basic blocks
Definition at line 134 of file BasicBlockSections.cpp.
Referenced by blake3_hash16_avx512(), blake3_hash4_avx512(), blake3_hash4_sse2(), blake3_hash4_sse41(), blake3_hash8_avx2(), blake3_hash8_avx512(), blake3_hash_many(), blake3_hash_many_avx2(), blake3_hash_many_avx512(), blake3_hash_many_portable(), blake3_hash_many_sse2(), blake3_hash_many_sse41(), llvm::deleteDeadLoop(), llvm::GCOVBlock::getCyclesCount(), llvm::LoopBase< BlockT, LoopT >::getExitBlocks(), llvm::GenericCycle< ContextT >::getExitBlocks(), llvm::LoopBase< BlockT, LoopT >::getExitEdges(), llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), hash_one_avx512(), hash_one_portable(), hash_one_sse2(), hash_one_sse41(), hasOnlyUniformBranches(), and llvm::RegionBase< RegionTraits< MachineFunction > >::outermostLoopInRegion().
false
bbsections Prepares for basic block by splitting functions into clusters of basic false
Definition at line 135 of file BasicBlockSections.cpp.
prepare
bbsections prepare
Definition at line 132 of file BasicBlockSections.cpp.
Referenced by llvm::jitlink::ELFLinkGraphBuilder< ELFT >::buildGraph().
sections
bbsections Prepares for basic block sections
Definition at line 133 of file BasicBlockSections.cpp.
Referenced by llvm::object::ELFFile< ELFT >::dynamicEntries(), llvm::object::ELFFile< ELFT >::getDynSymtabSize(), llvm::object::ELFFile< ELFT >::getSection(), llvm::object::ELFFile< ELFT >::getSectionAndRelocations(), llvm::object::ELFFile< ELFT >::getSectionName(), llvm::object::ELFFile< ELFT >::getSHNDXTable(), llvm::object::ELFFile< ELFT >::getStringTableForSymtab(), and LLVMObjectFileCopySectionIterator().