LLVM: lib/Analysis/CFGPrinter.cpp File Reference
CFGPrinter.cpp File Reference
#include "llvm/Analysis/CFGPrinter.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/GraphWriter.h"
Functions
static void writeCFGToDotFile (Function &F, BlockFrequencyInfo *BFI, BranchProbabilityInfo *BPI, uint64_t MaxFreq, bool CFGOnly=false)
static void viewCFG (Function &F, const BlockFrequencyInfo *BFI, const BranchProbabilityInfo *BPI, uint64_t MaxFreq, bool CFGOnly=false)
INITIALIZE_PASS (CFGViewerLegacyPass, "view-cfg", "View CFG of function", false, true) PreservedAnalyses CFGViewerPass
INITIALIZE_PASS (CFGOnlyViewerLegacyPass, "view-cfg-only", "View CFG of function (with no function bodies)", false, true) PreservedAnalyses CFGOnlyViewerPass
INITIALIZE_PASS (CFGPrinterLegacyPass, "dot-cfg", "Print CFG of function to 'dot' file", false, true) PreservedAnalyses CFGPrinterPass
INITIALIZE_PASS (CFGOnlyPrinterLegacyPass, "dot-cfg-only", "Print CFG of function to 'dot' file (with no function bodies)", false, true) PreservedAnalyses CFGOnlyPrinterPass
Variables
static cl::opt< std::string > CFGFuncName ("cfg-func-name", cl::Hidden, cl::desc("The name of a function (or its substring)" " whose CFG is viewed/printed."))
static cl::opt< std::string > CFGDotFilenamePrefix ("cfg-dot-filename-prefix", cl::Hidden, cl::desc("The prefix used for the CFG dot file names."))
static cl::opt< bool > HideUnreachablePaths ("cfg-hide-unreachable-paths", cl::init(false))
static cl::opt< bool > HideDeoptimizePaths ("cfg-hide-deoptimize-paths", cl::init(false))
static cl::opt< double > HideColdPaths ("cfg-hide-cold-paths", cl::init(0.0), cl::desc("Hide blocks with relative frequency below the given value"))
static cl::opt< bool > ShowHeatColors ("cfg-heat-colors", cl::init(true), cl::Hidden, cl::desc("Show heat colors in CFG"))
static cl::opt< bool > UseRawEdgeWeight ("cfg-raw-weights", cl::init(false), cl::Hidden, cl::desc("Use raw weights for labels. " "Use percentages as default."))
static cl::opt< bool > ShowEdgeWeight ("cfg-weights", cl::init(false), cl::Hidden, cl::desc("Show edges labeled with weights"))
Function Documentation
INITIALIZE_PASS() [1/4]
INITIALIZE_PASS (CFGOnlyPrinterLegacyPass , "dot-cfg-only" , "Print CFG of function to 'dot' file (with no function bodies)" , false , true)
Definition at line 244 of file CFGPrinter.cpp.
References llvm::PreservedAnalyses::all(), CFGFuncName, F, llvm::getMaxFreq(), and writeCFGToDotFile().
INITIALIZE_PASS() [2/4]
INITIALIZE_PASS (CFGOnlyViewerLegacyPass , "view-cfg-only" , "View CFG of function (with no function bodies)" , false , true)
Definition at line 163 of file CFGPrinter.cpp.
References llvm::PreservedAnalyses::all(), CFGFuncName, F, llvm::getMaxFreq(), and viewCFG().
INITIALIZE_PASS() [3/4]
INITIALIZE_PASS (CFGPrinterLegacyPass , "dot-cfg" , "Print CFG of function to 'dot' file" , false , true)
Definition at line 204 of file CFGPrinter.cpp.
References llvm::PreservedAnalyses::all(), CFGFuncName, F, llvm::getMaxFreq(), and writeCFGToDotFile().
INITIALIZE_PASS() [4/4]
INITIALIZE_PASS (CFGViewerLegacyPass , "view-cfg" , "View CFG of function" , false , true)
Definition at line 123 of file CFGPrinter.cpp.
References llvm::PreservedAnalyses::all(), CFGFuncName, F, llvm::getMaxFreq(), and viewCFG().
viewCFG()
static void viewCFG (Function & F, const BlockFrequencyInfo * BFI, const BranchProbabilityInfo * BPI, uint64_t MaxFreq, bool CFGOnly = false) static
Definition at line 84 of file CFGPrinter.cpp.
References CFGOnly, F, ShowEdgeWeight, ShowHeatColors, UseRawEdgeWeight, and llvm::ViewGraph().
Referenced by INITIALIZE_PASS(), and INITIALIZE_PASS().
writeCFGToDotFile()
static void writeCFGToDotFile (Function & F, BlockFrequencyInfo * BFI, BranchProbabilityInfo * BPI, uint64_t MaxFreq, bool CFGOnly = false) static
Definition at line 62 of file CFGPrinter.cpp.
References CFGDotFilenamePrefix, CFGOnly, llvm::errs(), F, llvm::sys::fs::OF_Text, ShowEdgeWeight, ShowHeatColors, UseRawEdgeWeight, and llvm::WriteGraph().
Referenced by INITIALIZE_PASS(), and INITIALIZE_PASS().
Variable Documentation
CFGDotFilenamePrefix
cl::opt< std::string > CFGDotFilenamePrefix("cfg-dot-filename-prefix", cl::Hidden, cl::desc("The prefix used for the CFG dot file names.")) ("cfg-dot-filename-prefix" , cl::Hidden , cl::desc("The prefix used for the CFG dot file names.")) static
Referenced by writeCFGToDotFile().
CFGFuncName
cl::opt< std::string > CFGFuncName("cfg-func-name", cl::Hidden, cl::desc("The name of a function (or its substring)" " whose CFG is viewed/printed.")) ("cfg-func-name" , cl::Hidden , cl::desc("The name of a function (or its substring)" " whose CFG is viewed/printed.")) static
Referenced by INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), and llvm::Function::viewCFG().
HideColdPaths
cl::opt< double > HideColdPaths("cfg-hide-cold-paths", cl::init(0.0), cl::desc("Hide blocks with relative frequency below the given value")) ("cfg-hide-cold-paths" , cl::init(0.0) , cl::desc("Hide blocks with relative frequency below the given value")) static
HideDeoptimizePaths
cl::opt< bool > HideDeoptimizePaths("cfg-hide-deoptimize-paths", cl::init(false)) ("cfg-hide-deoptimize-paths" , cl::init(false)) static
HideUnreachablePaths
cl::opt< bool > HideUnreachablePaths("cfg-hide-unreachable-paths", cl::init(false)) ("cfg-hide-unreachable-paths" , cl::init(false)) static
ShowEdgeWeight
cl::opt< bool > ShowEdgeWeight("cfg-weights", cl::init(false), cl::Hidden, cl::desc("Show edges labeled with weights")) ("cfg-weights" , cl::init(false) , cl::Hidden , cl::desc("Show edges labeled with weights")) static
Referenced by viewCFG(), and writeCFGToDotFile().
ShowHeatColors
cl::opt< bool > ShowHeatColors("cfg-heat-colors", cl::init(true), cl::Hidden, cl::desc("Show heat colors in CFG")) ("cfg-heat-colors" , cl::init(true) , cl::Hidden , cl::desc("Show heat colors in CFG")) static
Referenced by viewCFG(), and writeCFGToDotFile().
UseRawEdgeWeight
cl::opt< bool > UseRawEdgeWeight("cfg-raw-weights", cl::init(false), cl::Hidden, cl::desc("Use raw weights for labels. " "Use percentages as default.")) ("cfg-raw-weights" , cl::init(false) , cl::Hidden , cl::desc("Use raw weights for labels. " "Use percentages as default.")) static
Referenced by viewCFG(), and writeCFGToDotFile().