LLVM: llvm::ModuleSummaryIndexAnalysis Class Reference
llvm::ModuleSummaryIndexAnalysis Class Reference
Analysis pass to provide the ModuleSummaryIndex object.
#include "llvm/Analysis/ModuleSummaryAnalysis.h"
Public Types
using Result = ModuleSummaryIndex
Public Member Functions
Result run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< DerivedT >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::AnalysisInfoMixin< ModuleSummaryIndexAnalysis >
static AnalysisKey * ID ()
Returns an opaque, unique ID for this analysis type.
Static Public Member Functions inherited from llvm::PassInfoMixin< DerivedT >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Analysis pass to provide the ModuleSummaryIndex object.
Definition at line 44 of file ModuleSummaryAnalysis.h.
Member Typedef Documentation
Result
using llvm::ModuleSummaryIndexAnalysis::Result = ModuleSummaryIndex
Definition at line 51 of file ModuleSummaryAnalysis.h.
Member Function Documentation
run()
ModuleSummaryIndex ModuleSummaryIndexAnalysis::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 997 of file ModuleSummaryAnalysis.cpp.
References llvm::buildModuleSummaryIndex(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::needsParamAccessSummary().
The documentation for this class was generated from the following files:
include/llvm/Analysis/ModuleSummaryAnalysis.h
lib/Analysis/ModuleSummaryAnalysis.cpp