LLVM: llvm::object::ENDRecord Class Reference
llvm::object::ENDRecord Class Reference
#include "llvm/Object/GOFF.h"
Static Public Member Functions
static Error getData (const uint8_t *Record, SmallString< 256 > &CompleteData)
static uint16_t getNameLength (const uint8_t *Record)
Static Public Member Functions inherited from llvm::object::Record
static Error getContinuousData (const uint8_t *Record, uint16_t DataLength, int DataIndex, SmallString< 256 > &CompleteData)
static bool isContinued (const uint8_t *Record)
static bool isContinuation (const uint8_t *Record)
Additional Inherited Members
Static Protected Member Functions inherited from llvm::object::Record
static void getBits (const uint8_t *Bytes, uint8_t ByteIndex, uint8_t BitIndex, uint8_t Length, uint8_t &Value)
Get bit field of specified byte.
template<class T >
static void get (const uint8_t *Bytes, uint8_t ByteIndex, T &Value)
Detailed Description
Definition at line 270 of file GOFF.h.
Member Function Documentation
getData()
Error ENDRecord::getData (const uint8_t * Record, SmallString< 256 > & CompleteData) static
Definition at line 479 of file GOFFObjectFile.cpp.
References llvm::object::Record::getContinuousData(), getNameLength(), and llvm::Length.
getNameLength()
static uint16_t llvm::object::ENDRecord::getNameLength (const uint8_t * Record) inline static
Definition at line 274 of file GOFF.h.
References llvm::Length.
Referenced by getData().
The documentation for this class was generated from the following files:
include/llvm/Object/GOFF.h
lib/Object/GOFFObjectFile.cpp