LLVM: llvm::GlobalObject Class Reference
llvm::GlobalObject Class Reference
#include "llvm/IR/GlobalObject.h"
Public Types
enum VCallVisibility { VCallVisibilityPublic = 0 , VCallVisibilityLinkageUnit = 1 , VCallVisibilityTranslationUnit = 2 }
Public Types inherited from llvm::GlobalValue
enum LinkageTypes {
ExternalLinkage = 0 , AvailableExternallyLinkage , LinkOnceAnyLinkage , LinkOnceODRLinkage ,
WeakAnyLinkage , WeakODRLinkage , AppendingLinkage , InternalLinkage ,
PrivateLinkage , ExternalWeakLinkage , CommonLinkage
}
An enumeration for the kinds of linkage for global values.
enum VisibilityTypes { DefaultVisibility = 0 , HiddenVisibility , ProtectedVisibility }
An enumeration for the kinds of visibility of global values.
enum DLLStorageClassTypes { DefaultStorageClass = 0 , DLLImportStorageClass = 1 , DLLExportStorageClass = 2 }
Storage classes of global values for PE targets.
enum ThreadLocalMode {
NotThreadLocal = 0 , GeneralDynamicTLSModel , LocalDynamicTLSModel , InitialExecTLSModel ,
LocalExecTLSModel
}
enum class UnnamedAddr { None , Local , Global }
using GUID = uint64_t
Declare a type to represent a global unique identifier for a global value.
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Public Member Functions
GlobalObject (const GlobalObject &)=delete
uint64_t getAlignment () const
FIXME: Remove this function once transition to Align is over.
MaybeAlign getAlign () const
Returns the alignment of the given variable or function.
void setAlignment (Align Align)
Sets the alignment attribute of the GlobalObject.
void setAlignment (MaybeAlign Align)
Sets the alignment attribute of the GlobalObject.
unsigned getGlobalObjectSubClassData () const
void setGlobalObjectSubClassData (unsigned Val)
bool hasSection () const
Check if this global has a custom object file section.
StringRef getSection () const
Get the custom section of this global if it has one.
void setSection (StringRef S)
Change the section for this global.
bool hasComdat () const
const Comdat * getComdat () const
Comdat * getComdat ()
void setComdat (Comdat *C)
void copyMetadata (const GlobalObject *Src, unsigned Offset)
Copy metadata from Src, adjusting offsets by Offset.
void addTypeMetadata (unsigned Offset, Metadata *TypeID)
void setVCallVisibilityMetadata (VCallVisibility Visibility)
VCallVisibility getVCallVisibility () const
bool canIncreaseAlignment () const
Returns true if the alignment of the value can be unilaterally increased.
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
void clearMetadata ()
Erase all metadata attached to this Value.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
Public Member Functions inherited from llvm::GlobalValue
GlobalValue (const GlobalValue &)=delete
unsigned getAddressSpace () const
bool hasGlobalUnnamedAddr () const
bool hasAtLeastLocalUnnamedAddr () const
Returns true if this value's address is not significant in this module.
UnnamedAddr getUnnamedAddr () const
void setUnnamedAddr (UnnamedAddr Val)
bool hasComdat () const
const Comdat * getComdat () const
Comdat * getComdat ()
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
void setVisibility (VisibilityTypes V)
bool isThreadLocal () const
If the value is "Thread Local", its value isn't shared by the threads.
void setThreadLocal (bool Val)
void setThreadLocalMode (ThreadLocalMode Val)
ThreadLocalMode getThreadLocalMode () const
DLLStorageClassTypes getDLLStorageClass () const
bool hasDLLImportStorageClass () const
bool hasDLLExportStorageClass () const
void setDLLStorageClass (DLLStorageClassTypes C)
bool hasSection () const
StringRef getSection () const
PointerType * getType () const
Global values are always pointers.
Type * getValueType () const
bool isImplicitDSOLocal () const
void setDSOLocal (bool Local)
bool isDSOLocal () const
bool hasPartition () const
StringRef getPartition () const
void setPartition (StringRef Part)
bool hasSanitizerMetadata () const
const SanitizerMetadata & getSanitizerMetadata () const
void setSanitizerMetadata (SanitizerMetadata Meta)
void removeSanitizerMetadata ()
bool isTagged () const
bool isDefinitionExact () const
Return true if the currently visible definition of this global (if any) is exactly the definition we will see at runtime.
bool hasExactDefinition () const
Return true if this global has an exact defintion.
bool isInterposable () const
Return true if this global's definition can be substituted with an arbitrary definition at link time or load time.
bool canBenefitFromLocalAlias () const
bool hasExternalLinkage () const
bool hasAvailableExternallyLinkage () const
bool hasLinkOnceLinkage () const
bool hasLinkOnceAnyLinkage () const
bool hasLinkOnceODRLinkage () const
bool hasWeakLinkage () const
bool hasWeakAnyLinkage () const
bool hasWeakODRLinkage () const
bool hasAppendingLinkage () const
bool hasInternalLinkage () const
bool hasPrivateLinkage () const
bool hasLocalLinkage () const
bool hasExternalWeakLinkage () const
bool hasCommonLinkage () const
bool hasValidDeclarationLinkage () const
void setLinkage (LinkageTypes LT)
LinkageTypes getLinkage () const
bool isDiscardableIfUnused () const
bool isWeakForLinker () const
std::string getGlobalIdentifier () const
Return the modified name for this global value suitable to be used as the key for a global lookup (e.g.
GUID getGUID () const
Return a 64-bit global unique ID constructed from global value name (i.e.
bool isDeclaration () const
Return true if the primary definition of this global value is outside of the current translation unit.
bool isDeclarationForLinker () const
bool isStrongDefinitionForLinker () const
Returns true if this global's definition will be the one chosen by the linker.
const GlobalObject * getAliaseeObject () const
GlobalObject * getAliaseeObject ()
bool isAbsoluteSymbolRef () const
Returns whether this is a reference to an absolute symbol.
std::optional< ConstantRange > getAbsoluteSymbolRange () const
If this is an absolute symbol reference, returns the range of the symbol, otherwise returns std::nullopt.
void removeFromParent ()
This method unlinks 'this' from the containing module, but does not delete it.
void eraseFromParent ()
This method unlinks 'this' from the containing module and deletes it.
Module * getParent ()
Get the module that this global value is contained inside of...
const Module * getParent () const
bool canBeOmittedFromSymbolTable () const
True if GV can be left out of the object symbol table.
bool isMaterializable () const
If this function's Module is being lazily streamed in functions from disk or some other source, this method can be used to check to see if the function has been read in yet or not.
Error materialize ()
Make sure this GlobalValue is fully read.
Public Member Functions inherited from llvm::Constant
void operator= (const Constant &)=delete
Constant (const Constant &)=delete
bool isNullValue () const
Return true if this is the value that would be returned by getNullValue.
bool isOneValue () const
Returns true if the value is one.
bool isNotOneValue () const
Return true if the value is not the one value, or, for vectors, does not contain one value elements.
bool isAllOnesValue () const
Return true if this is the value that would be returned by getAllOnesValue.
bool isNegativeZeroValue () const
Return true if the value is what would be returned by getZeroValueForNegation.
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value, or, for vectors, does not contain smallest signed value elements.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool isFiniteNonZeroFP () const
Return true if this is a finite and non-zero floating-point scalar constant or a fixed width vector constant with all finite and non-zero elements.
bool isNormalFP () const
Return true if this is a normal (as opposed to denormal, infinity, nan, or zero) floating-point scalar constant or a vector constant with all normal elements.
bool hasExactInverseFP () const
Return true if this scalar has an exact multiplicative inverse or this vector has an exact multiplicative inverse for each element in the vector.
bool isNaN () const
Return true if this is a floating-point NaN constant or a vector floating-point constant with all NaN elements.
bool isElementWiseEqual (Value *Y) const
Return true if this constant and a constant 'Y' are element-wise equal.
bool containsUndefOrPoisonElement () const
Return true if this is a vector constant that includes any undef or poison elements.
bool containsPoisonElement () const
Return true if this is a vector constant that includes any poison elements.
bool containsUndefElement () const
Return true if this is a vector constant that includes any strictly undef (not poison) elements.
bool containsConstantExpression () const
Return true if this is a fixed width vector constant that includes any constant expressions.
bool isThreadDependent () const
Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
Return true if the constant has users other than constant expressions and other dangling things.
bool needsRelocation () const
This method classifies the entry according to whether or not it may generate a relocation entry (either static or dynamic).
bool needsDynamicRelocation () const
Constant * getAggregateElement (unsigned Elt) const
For aggregates (struct/array/vector) return the constant that corresponds to the specified element if possible, or null if not.
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue (bool AllowUndefs=false) const
If all elements of the vector constant have the same value, return that value.
const APInt & getUniqueInteger () const
If C is a constant integer then return its value, otherwise C must be a vector of constant integers, all equal, and the common value is returned.
void destroyConstant ()
Called if some element of this constant is no longer valid.
void handleOperandChange (Value *, Value *)
This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants.
void removeDeadConstantUsers () const
If there are any dead constant users dangling off of this constant, remove them.
bool hasOneLiveUse () const
Return true if the constant has exactly one live use.
bool hasZeroLiveUses () const
Return true if the constant has no live uses.
const Constant * stripPointerCasts () const
Constant * stripPointerCasts ()
bool isManifestConstant () const
Return true if a constant is ConstantData or a ConstantAggregate or ConstantExpr that contain only ConstantData.
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
std::optional< int64_t > getPointerOffsetFrom (const Value *Other, const DataLayout &DL) const
If this ptr is provably equal to Other plus a constant offset, return that offset in bytes.
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::GlobalValue
static UnnamedAddr getMinUnnamedAddr (UnnamedAddr A, UnnamedAddr B)
static LinkageTypes getLinkOnceLinkage (bool ODR)
static LinkageTypes getWeakLinkage (bool ODR)
static bool isExternalLinkage (LinkageTypes Linkage)
static bool isAvailableExternallyLinkage (LinkageTypes Linkage)
static bool isLinkOnceAnyLinkage (LinkageTypes Linkage)
static bool isLinkOnceODRLinkage (LinkageTypes Linkage)
static bool isLinkOnceLinkage (LinkageTypes Linkage)
static bool isWeakAnyLinkage (LinkageTypes Linkage)
static bool isWeakODRLinkage (LinkageTypes Linkage)
static bool isWeakLinkage (LinkageTypes Linkage)
static bool isAppendingLinkage (LinkageTypes Linkage)
static bool isInternalLinkage (LinkageTypes Linkage)
static bool isPrivateLinkage (LinkageTypes Linkage)
static bool isLocalLinkage (LinkageTypes Linkage)
static bool isExternalWeakLinkage (LinkageTypes Linkage)
static bool isCommonLinkage (LinkageTypes Linkage)
static bool isValidDeclarationLinkage (LinkageTypes Linkage)
static bool isInterposableLinkage (LinkageTypes Linkage)
Whether the definition of this global may be replaced by something non-equivalent at link time.
static bool isDiscardableIfUnused (LinkageTypes Linkage)
Whether the definition of this global may be discarded if it is not used in its compilation unit.
static bool isWeakForLinker (LinkageTypes Linkage)
Whether the definition of this global may be replaced at link time.
static StringRef dropLLVMManglingEscape (StringRef Name)
If the given string begins with the GlobalValue name mangling escape character '\1', drop it.
static std::string getGlobalIdentifier (StringRef Name, GlobalValue::LinkageTypes Linkage, StringRef FileName)
Return the modified name for a global value suitable to be used as the key for a global lookup (e.g.
static GUID getGUID (StringRef GlobalName)
Return a 64-bit global unique ID constructed from global value name (i.e.
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
Constructor to create a '0' constant of arbitrary type.
static Constant * getAllOnesValue (Type *Ty)
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Return the value for an integer or pointer constant, or a vector thereof, with the given scalar value.
static Constant * replaceUndefsWith (Constant *C, Constant *Replacement)
Try to replace undefined constant C or undefined elements in C with Replacement.
static Constant * mergeUndefsWith (Constant *C, Constant *Other)
Merges undefs of a Constant with another Constant, along with the undefs already present.
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Types
enum { LastAlignmentBit = 5 , HasSectionHashEntryBit , GlobalObjectBits }
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Protected Member Functions
GlobalObject (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name, unsigned AddressSpace=0)
~GlobalObject ()
void copyAttributesFrom (const GlobalObject *Src)
Protected Member Functions inherited from llvm::GlobalValue
GlobalValue (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name, unsigned AddressSpace)
unsigned getGlobalValueSubClassData () const
void setGlobalValueSubClassData (unsigned V)
void setParent (Module *parent)
~GlobalValue ()
void copyAttributesFrom (const GlobalValue *Src)
Copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
~Constant ()=default
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Protected Attributes
Comdat * ObjComdat = nullptr
Protected Attributes inherited from llvm::GlobalValue
Type * ValueType
unsigned Linkage: 4
unsigned Visibility: 2
unsigned UnnamedAddrVal: 2
unsigned DllStorageClass: 2
unsigned ThreadLocal: 3
unsigned HasLLVMReservedName: 1
True if the function's name starts with "llvm.".
unsigned IsDSOLocal: 1
If true then there is a definition within the same linkage unit and that definition cannot be runtime preempted.
unsigned HasPartition: 1
True if this symbol has a partition name assigned (see https://lld.llvm.org/Partitions.html).
unsigned HasSanitizerMetadata: 1
True if this symbol has sanitizer metadata available.
Intrinsic::ID IntID = (Intrinsic::ID)0U
The intrinsic ID for this subclass (which must be a Function).
Module * Parent = nullptr
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Static Protected Attributes
static const unsigned GlobalObjectSubClassDataBits
Static Protected Attributes inherited from llvm::GlobalValue
static const unsigned GlobalValueSubClassDataBits = 15
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Detailed Description
Definition at line 27 of file GlobalObject.h.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
LastAlignmentBit
HasSectionHashEntryBit
GlobalObjectBits
Definition at line 52 of file GlobalObject.h.
VCallVisibility
enum llvm::GlobalObject::VCallVisibility
Enumerator
VCallVisibilityPublic
VCallVisibilityLinkageUnit
VCallVisibilityTranslationUnit
Definition at line 32 of file GlobalObject.h.
Constructor & Destructor Documentation
GlobalObject() [1/2]
llvm::GlobalObject::GlobalObject (Type * Ty, ValueTy VTy, Use * Ops, unsigned NumOps, LinkageTypes Linkage, const Twine & Name, unsigned AddressSpace = 0) inline protected
Definition at line 43 of file GlobalObject.h.
References llvm::GlobalValue::setGlobalValueSubClassData().
~GlobalObject()
GlobalObject::~GlobalObject () protected
Definition at line 98 of file Globals.cpp.
References setComdat().
GlobalObject() [2/2]
llvm::GlobalObject::GlobalObject (const GlobalObject &) delete
Member Function Documentation
addMetadata() [1/2]
void Value::addMetadata (StringRef Kind, MDNode & MD)
Definition at line 609 of file Metadata.cpp.
addMetadata() [2/2]
void Value::addMetadata (unsigned KindID, MDNode & MD)
Add a metadata attachment.
Definition at line 608 of file Metadata.cpp.
Referenced by llvm::GlobalVariable::addDebugInfo(), addTypeMetadata(), llvm::CloneFunctionInto(), llvm::CloneModule(), copyMetadata(), llvm::OpenMPIRBuilder::getOrCreateRuntimeFunction(), and setVCallVisibilityMetadata().
addTypeMetadata()
void GlobalObject::addTypeMetadata (unsigned Offset, Metadata * TypeID)
Definition at line 1693 of file Metadata.cpp.
References addMetadata(), llvm::ConstantAsMetadata::get(), llvm::MDTuple::get(), llvm::ConstantInt::get(), llvm::Value::getContext(), llvm::Type::getInt64Ty(), and llvm::Offset.
canIncreaseAlignment()
bool GlobalObject::canIncreaseAlignment () const
Returns true if the alignment of the value can be unilaterally increased.
Note that for functions this is the alignment of the code, not the alignment of a function pointer.
Definition at line 287 of file Globals.cpp.
References getAlign(), llvm::Module::getTargetTriple(), hasSection(), llvm::GlobalValue::isDSOLocal(), llvm::Triple::isOSBinFormatELF(), llvm::GlobalValue::isStrongDefinitionForLinker(), and llvm::GlobalValue::Parent.
classof()
static bool llvm::GlobalObject::classof (const Value * V) inline static
Definition at line 159 of file GlobalObject.h.
clearMetadata()
void Value::clearMetadata ()
Erase all metadata attached to this Value.
Definition at line 618 of file Metadata.cpp.
Referenced by llvm::Function::dropAllReferences(), and llvm::GlobalVariable::dropAllReferences().
copyAttributesFrom()
void GlobalObject::copyAttributesFrom (const GlobalObject * Src) protected
Definition at line 138 of file Globals.cpp.
References llvm::GlobalValue::copyAttributesFrom(), setAlignment(), and setSection().
Referenced by llvm::Function::copyAttributesFrom(), llvm::GlobalIFunc::copyAttributesFrom(), and llvm::GlobalVariable::copyAttributesFrom().
copyMetadata()
void GlobalObject::copyMetadata (const GlobalObject * Src, unsigned Offset)
Copy metadata from Src, adjusting offsets by Offset.
Definition at line 1652 of file Metadata.cpp.
References addMetadata(), llvm::copy(), E, llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::ConstantInt::get(), llvm::Value::getContext(), llvm::Offset, and llvm::Other.
Referenced by doPromotion().
eraseMetadata()
bool Value::eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
Returns
true if any metadata was removed.
Definition at line 615 of file Metadata.cpp.
Referenced by setVCallVisibilityMetadata().
getAlign()
MaybeAlign llvm::GlobalObject::getAlign () const inline
Returns the alignment of the given variable or function.
Note that for functions this is the alignment of the code, not the alignment of a function pointer.
Definition at line 79 of file GlobalObject.h.
References llvm::Data, llvm::decodeMaybeAlign(), and llvm::GlobalValue::getGlobalValueSubClassData().
Referenced by llvm::AMDGPUMachineFunction::allocateLDSGlobal(), canIncreaseAlignment(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), getAlign(), getAlignment(), llvm::AsmPrinter::getGVAlignment(), llvm::DataLayout::getPreferredAlign(), hasTocDataAttr(), replace(), setAlignment(), setAlignment(), llvm::AMDGPUMachineFunction::setDynLDSAlign(), SRAGlobal(), and llvm::ObjectSizeOffsetVisitor::visitGlobalVariable().
getAlignment()
uint64_t llvm::GlobalObject::getAlignment () const inline
FIXME: Remove this function once transition to Align is over.
Definition at line 70 of file GlobalObject.h.
References getAlign(), and llvm::Align::value().
getAllMetadata()
void Value::getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > & MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
The first element of each pair returned is the KindID, the second element is the metadata value. Attachments with the same ID appear in insertion order.
Definition at line 582 of file Metadata.cpp.
Referenced by llvm::CloneFunctionInto(), and hasMetadataOtherThanDebugLoc().
getComdat() [1/2]
Comdat * llvm::GlobalObject::getComdat () inline
Definition at line 129 of file GlobalObject.h.
References ObjComdat.
getComdat() [2/2]
const Comdat * llvm::GlobalObject::getComdat () const inline
Definition at line 128 of file GlobalObject.h.
References ObjComdat.
Referenced by hasComdat(), maybePrintComdat(), and rewriteComdat().
getGlobalObjectSubClassData()
unsigned llvm::GlobalObject::getGlobalObjectSubClassData () const inline
Definition at line 93 of file GlobalObject.h.
References llvm::GlobalValue::getGlobalValueSubClassData(), and GlobalObjectBits.
Referenced by setGlobalObjectSubClassData().
getMetadata() [1/4]
MDNode * Value::getMetadata (StringRef Kind) const
Definition at line 566 of file Metadata.cpp.
getMetadata() [2/4]
void Value::getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > & MDs) const
Definition at line 574 of file Metadata.cpp.
getMetadata() [3/4]
MDNode * Value::getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
These functions require that the value have at most a single attachment of the given kind, and return nullptr if such an attachment is missing.
Definition at line 565 of file Metadata.cpp.
Referenced by calcUniqueIDUpdateFlagsAndSize(), llvm::GlobalVariable::getDebugInfo(), llvm::Function::getEntryCount(), llvm::Function::getImportGUIDs(), getLinkedToSymbol(), getReqdWorkGroupSize(), llvm::Function::getSectionPrefix(), llvm::Function::getSubprogram(), getVCallVisibility(), hasInstrProfHashMismatch(), processUse(), and splitGlobal().
getMetadata() [4/4]
void Value::getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > & MDs) const
Appends all attachments with the given ID to MDs in insertion order.
If the Value has no attachments with the given ID, or if ID is invalid, leaves MDs unchanged.
Definition at line 573 of file Metadata.cpp.
getSection()
StringRef llvm::GlobalObject::getSection () const inline
Get the custom section of this global if it has one.
If this global does not have a custom section, this will be empty and the default object file section (.text, .data, etc) will be used.
Definition at line 117 of file GlobalObject.h.
References hasSection().
Referenced by llvm::FunctionComparator::compareSignature(), llvm::AsmPrinter::emitSpecialLLVMGlobal(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileXCOFF::getExplicitSectionGlobal(), llvm::AMDGPUTargetObjectFile::getExplicitSectionGlobal(), DXILTargetObjectFile::getExplicitSectionGlobal(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::XCoreTargetObjectFile::getExplicitSectionGlobal(), removeFromUsedList(), selectExplicitSectionGlobal(), and llvm::HexagonTargetObjectFile::SelectSectionForGlobal().
getVCallVisibility()
GlobalObject::VCallVisibility GlobalObject::getVCallVisibility () const
Definition at line 1712 of file Metadata.cpp.
References assert(), getMetadata(), and VCallVisibilityPublic.
Referenced by splitGlobal().
hasComdat()
bool llvm::GlobalObject::hasComdat () const inline
Definition at line 127 of file GlobalObject.h.
References getComdat().
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), getFuncAddrForProfData(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileWasm::SelectSectionForGlobal(), and shouldUsePublicSymbol().
hasMetadata() [1/3]
bool llvm::Value::hasMetadata () const inline
Return true if this value has any metadata attached to it.
Definition at line 585 of file Value.h.
Referenced by llvm::OpenMPIRBuilder::getOrCreateRuntimeFunction(), needFuncLabels(), shouldUsePublicSymbol(), and splitGlobal().
hasMetadata() [2/3]
bool llvm::Value::hasMetadata (StringRef Kind) const inline
Definition at line 592 of file Value.h.
hasMetadata() [3/3]
bool llvm::Value::hasMetadata (unsigned KindID) const inline
Return true if this value has the given type of metadata attached.
Definition at line 589 of file Value.h.
hasSection()
bool llvm::GlobalObject::hasSection () const inline
Check if this global has a custom object file section.
This is more efficient than calling getSection() and checking for an empty string.
Definition at line 109 of file GlobalObject.h.
References llvm::GlobalValue::getGlobalValueSubClassData(), and HasSectionHashEntryBit.
Referenced by canIncreaseAlignment(), llvm::FunctionComparator::compareSignature(), llvm::TargetLoweringObjectFileXCOFF::getExplicitSectionGlobal(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::AsmPrinter::getGVAlignment(), llvm::DataLayout::getPreferredAlign(), getSection(), isSuitableForBSS(), isUnmergeableGlobal(), llvm::TargetLoweringObjectFile::SectionForGlobal(), llvm::AVRTargetObjectFile::SelectSectionForGlobal(), and setSection().
setAlignment() [1/2]
void GlobalObject::setAlignment (Align Align)
Sets the alignment attribute of the GlobalObject.
Definition at line 128 of file Globals.cpp.
References assert(), llvm::encode(), getAlign(), llvm::GlobalValue::getGlobalValueSubClassData(), llvm::Value::MaximumAlignment, and llvm::GlobalValue::setGlobalValueSubClassData().
Referenced by copyAttributesFrom(), llvm::createPrivateGlobalForString(), llvm::embedBitcodeInModule(), and llvm::embedBufferInModule().
setAlignment() [2/2]
void GlobalObject::setAlignment (MaybeAlign Align)
Sets the alignment attribute of the GlobalObject.
This method will be deprecated as the alignment property should always be defined.
Definition at line 119 of file Globals.cpp.
References assert(), llvm::encode(), getAlign(), llvm::GlobalValue::getGlobalValueSubClassData(), llvm::Value::MaximumAlignment, and llvm::GlobalValue::setGlobalValueSubClassData().
setComdat()
void GlobalObject::setComdat (Comdat * C)
Definition at line 196 of file Globals.cpp.
References llvm::CallingConv::C, and ObjComdat.
Referenced by rewriteComdat(), and ~GlobalObject().
setGlobalObjectSubClassData()
void llvm::GlobalObject::setGlobalObjectSubClassData (unsigned Val) inline
Definition at line 98 of file GlobalObject.h.
References assert(), getGlobalObjectSubClassData(), llvm::GlobalValue::getGlobalValueSubClassData(), GlobalObjectBits, and llvm::GlobalValue::setGlobalValueSubClassData().
setMetadata() [1/2]
void Value::setMetadata (StringRef Kind, MDNode * Node)
Definition at line 603 of file Metadata.cpp.
References assert(), llvm::MDNode::operands(), and size().
setMetadata() [2/2]
void Value::setMetadata (unsigned KindID, MDNode * Node)
Set a particular kind of metadata attachment.
Sets the given attachment to MD, erasing it if MD is nullptr or replacing it if it already exists.
Definition at line 602 of file Metadata.cpp.
Referenced by llvm::embedBufferInModule(), llvm::Function::setEntryCount(), llvm::Function::setSectionPrefix(), and llvm::Function::setSubprogram().
setSection()
void GlobalObject::setSection (StringRef S)
Change the section for this global.
Setting the section to the empty string tells LLVM to choose an appropriate default object file section.
Definition at line 250 of file Globals.cpp.
References llvm::StringRef::empty(), llvm::Value::getContext(), llvm::LLVMContextImpl::GlobalObjectSections, hasSection(), HasSectionHashEntryBit, llvm::LLVMContext::pImpl, llvm::UniqueStringSaver::save(), and llvm::LLVMContextImpl::Saver.
Referenced by appendToUsedList(), copyAttributesFrom(), llvm::embedBitcodeInModule(), and llvm::embedBufferInModule().
setVCallVisibilityMetadata()
void GlobalObject::setVCallVisibilityMetadata (VCallVisibility Visibility)
Definition at line 1702 of file Metadata.cpp.
References addMetadata(), eraseMetadata(), llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::ConstantInt::get(), llvm::Value::getContext(), llvm::Type::getInt64Ty(), and llvm::GlobalValue::Visibility.
Member Data Documentation
GlobalObjectSubClassDataBits
const unsigned llvm::GlobalObject::GlobalObjectSubClassDataBits static protected
Initial value:
=
      GlobalValueSubClassDataBits - GlobalObjectBits
Definition at line 58 of file GlobalObject.h.
ObjComdat
Comdat* llvm::GlobalObject::ObjComdat = nullptr protected
Definition at line 51 of file GlobalObject.h.
Referenced by getComdat(), getComdat(), and setComdat().
The documentation for this class was generated from the following files:
include/llvm/IR/GlobalObject.h
lib/IR/Globals.cpp
lib/IR/Metadata.cpp