LLVM: llvm::GCNSchedStage Class Reference
llvm::GCNSchedStage Class Reference
#include "Target/AMDGPU/GCNSchedStrategy.h"
Public Member Functions
virtual bool initGCNSchedStage ()
virtual void finalizeGCNSchedStage ()
virtual bool initGCNRegion ()
void setupNewBlock ()
void finalizeGCNRegion ()
void checkScheduling ()
ScheduleMetrics getScheduleMetrics (const std::vector< SUnit > &InputSchedule)
ScheduleMetrics getScheduleMetrics (const GCNScheduleDAGMILive &DAG)
unsigned computeSUnitReadyCycle (const SUnit &SU, unsigned CurrCycle, DenseMap< unsigned, unsigned > &ReadyCycles, const TargetSchedModel &SM)
virtual bool shouldRevertScheduling (unsigned WavesAfter)
bool isRegionWithExcessRP () const
bool mayCauseSpilling (unsigned WavesAfter)
void revertScheduling ()
void advanceRegion ()
virtual ~GCNSchedStage ()=default
Protected Member Functions
GCNSchedStage (GCNSchedStageID StageID, GCNScheduleDAGMILive &DAG)
Protected Attributes
GCNScheduleDAGMILive & DAG
GCNSchedStrategy & S
MachineFunction & MF
SIMachineFunctionInfo & MFI
const GCNSubtarget & ST
const GCNSchedStageID StageID
MachineBasicBlock * CurrentMBB = nullptr
unsigned RegionIdx = 0
std::vector< MachineInstr * > Unsched
GCNRegPressure PressureBefore
GCNRegPressure PressureAfter
std::vector< std::unique_ptr< ScheduleDAGMutation > > SavedMutations
Detailed Description
Definition at line 245 of file GCNSchedStrategy.h.
Constructor & Destructor Documentation
GCNSchedStage()
GCNSchedStage::GCNSchedStage (GCNSchedStageID StageID, GCNScheduleDAGMILive & DAG) protected
Definition at line 687 of file GCNSchedStrategy.cpp.
~GCNSchedStage()
virtual llvm::GCNSchedStage::~GCNSchedStage () virtual default
Member Function Documentation
advanceRegion()
void llvm::GCNSchedStage::advanceRegion () inline
Definition at line 320 of file GCNSchedStrategy.h.
References RegionIdx.
checkScheduling()
void GCNSchedStage::checkScheduling ()
Definition at line 914 of file GCNSchedStrategy.cpp.
References DAG, llvm::dbgs(), llvm::GCNRegPressure::getAGPRNum(), llvm::GCNSubtarget::getMaxNumSGPRs(), llvm::GCNSubtarget::getMaxNumVGPRs(), llvm::SIMachineFunctionInfo::getMinAllowedOccupancy(), llvm::GCNRegPressure::getOccupancy(), llvm::AMDGPUSubtarget::getOccupancyWithLocalMemSize(), llvm::GCNRegPressure::getSGPRNum(), llvm::GCNSchedStrategy::getTargetOccupancy(), llvm::GCNRegPressure::getVGPRNum(), llvm::GCNSubtarget::hasGFX90AInsts(), llvm::SIMachineFunctionInfo::limitOccupancy(), LLVM_DEBUG, MF, MFI, PressureAfter, PressureBefore, llvm::print(), RegionIdx, llvm::BitVector::reset(), revertScheduling(), S, llvm::GCNSchedStrategy::SGPRCriticalLimit, shouldRevertScheduling(), ST, and llvm::GCNSchedStrategy::VGPRCriticalLimit.
Referenced by finalizeGCNRegion().
computeSUnitReadyCycle()
unsigned GCNSchedStage::computeSUnitReadyCycle (const SUnit & SU, unsigned CurrCycle, DenseMap< unsigned, unsigned > & ReadyCycles, const TargetSchedModel & SM)
Definition at line 985 of file GCNSchedStrategy.cpp.
References D, DAG, DefMI, llvm::ScheduleDAGInstrs::getSUnit(), llvm::Latency, llvm::SUnit::NodeNum, and llvm::SUnit::Preds.
Referenced by getScheduleMetrics(), and getScheduleMetrics().
finalizeGCNRegion()
void GCNSchedStage::finalizeGCNRegion ()
Definition at line 896 of file GCNSchedStrategy.cpp.
References checkScheduling(), DAG, llvm::ScheduleDAGInstrs::exitRegion(), llvm::GCNSchedStrategy::HasHighPressure, llvm::ScheduleDAGMI::Mutations, llvm::ScheduleDAGInstrs::RegionBegin, llvm::ScheduleDAGInstrs::RegionEnd, RegionIdx, S, SavedMutations, StageID, and llvm::UnclusteredHighRPReschedule.
finalizeGCNSchedStage()
void GCNSchedStage::finalizeGCNSchedStage () virtual
Reimplemented in llvm::UnclusteredHighRPStage.
Definition at line 774 of file GCNSchedStrategy.cpp.
References DAG, llvm::dbgs(), llvm::ScheduleDAGMI::finishBlock(), LLVM_DEBUG, and StageID.
Referenced by llvm::UnclusteredHighRPStage::finalizeGCNSchedStage().
getScheduleMetrics() [1/2]
ScheduleMetrics GCNSchedStage::getScheduleMetrics (const GCNScheduleDAGMILive & DAG)
Definition at line 1063 of file GCNSchedStrategy.cpp.
References computeSUnitReadyCycle(), DAG, llvm::dbgs(), llvm::SUnit::getInstr(), llvm::GCNSubtarget::getInstrInfo(), llvm::SIInstrInfo::getSchedModel(), llvm::ScheduleDAGInstrs::getSUnit(), LLVM_DEBUG, MI, printScheduleModel(), llvm::ScheduleMetrics::ScaleFactor, and ST.
getScheduleMetrics() [2/2]
ScheduleMetrics GCNSchedStage::getScheduleMetrics (const std::vector< SUnit > & InputSchedule)
Definition at line 1030 of file GCNSchedStrategy.cpp.
References computeSUnitReadyCycle(), llvm::dbgs(), llvm::GCNSubtarget::getInstrInfo(), llvm::SIInstrInfo::getSchedModel(), LLVM_DEBUG, printScheduleModel(), llvm::ScheduleMetrics::ScaleFactor, and ST.
Referenced by llvm::UnclusteredHighRPStage::shouldRevertScheduling().
initGCNRegion()
bool GCNSchedStage::initGCNRegion () virtual
Reimplemented in llvm::UnclusteredHighRPStage, llvm::ClusteredLowOccStage, and llvm::PreRARematStage.
Definition at line 795 of file GCNSchedStrategy.cpp.
References llvm::ScheduleDAGMI::addMutation(), llvm::ScheduleDAGInstrs::begin(), llvm::createIGroupLPDAGMutation(), CurrentMBB, DAG, llvm::dbgs(), llvm::MachineBasicBlock::end(), llvm::ScheduleDAGInstrs::end(), llvm::ScheduleDAGMILive::enterRegion(), llvm::MachineBasicBlock::getName(), llvm::MachineFunction::getName(), llvm::getRegPressure(), llvm::GCNSchedStrategy::HasHighPressure, I, llvm::ILPInitialSchedule, isRegionWithExcessRP(), llvm::GCNSchedStrategy::KnownExcessRP, LLVM_DEBUG, MF, llvm::ScheduleDAG::MRI, llvm::ScheduleDAGMI::Mutations, llvm::ScheduleDAGInstrs::NumRegionInstrs, llvm::OccInitialSchedule, PressureBefore, llvm::print(), llvm::printMBBReference(), llvm::ScheduleDAGInstrs::RegionBegin, llvm::ScheduleDAGInstrs::RegionEnd, RegionIdx, S, SavedMutations, setupNewBlock(), StageID, llvm::UnclusteredHighRPReschedule, and Unsched.
Referenced by llvm::UnclusteredHighRPStage::initGCNRegion(), llvm::ClusteredLowOccStage::initGCNRegion(), and llvm::PreRARematStage::initGCNRegion().
initGCNSchedStage()
bool GCNSchedStage::initGCNSchedStage () virtual
Reimplemented in llvm::UnclusteredHighRPStage, llvm::ClusteredLowOccStage, and llvm::PreRARematStage.
Definition at line 691 of file GCNSchedStrategy.cpp.
References DAG, llvm::dbgs(), llvm::ScheduleDAGMI::LIS, LLVM_DEBUG, and StageID.
Referenced by llvm::UnclusteredHighRPStage::initGCNSchedStage(), llvm::ClusteredLowOccStage::initGCNSchedStage(), and llvm::PreRARematStage::initGCNSchedStage().
isRegionWithExcessRP()
bool llvm::GCNSchedStage::isRegionWithExcessRP () const inline
Definition at line 310 of file GCNSchedStrategy.h.
References DAG, and RegionIdx.
Referenced by initGCNRegion(), mayCauseSpilling(), and llvm::UnclusteredHighRPStage::shouldRevertScheduling().
mayCauseSpilling()
bool GCNSchedStage::mayCauseSpilling (unsigned WavesAfter)
Definition at line 1186 of file GCNSchedStrategy.cpp.
References llvm::dbgs(), llvm::SIMachineFunctionInfo::getMinWavesPerEU(), isRegionWithExcessRP(), llvm::GCNRegPressure::less(), LLVM_DEBUG, MFI, PressureAfter, PressureBefore, and ST.
Referenced by llvm::OccInitialScheduleStage::shouldRevertScheduling(), llvm::UnclusteredHighRPStage::shouldRevertScheduling(), llvm::ClusteredLowOccStage::shouldRevertScheduling(), llvm::PreRARematStage::shouldRevertScheduling(), and llvm::ILPInitialScheduleStage::shouldRevertScheduling().
revertScheduling()
void GCNSchedStage::revertScheduling ()
Definition at line 1197 of file GCNSchedStrategy.cpp.
References llvm::RegisterOperands::adjustLaneLiveness(), llvm::ScheduleDAGInstrs::BB, llvm::RegisterOperands::collect(), DAG, llvm::dbgs(), llvm::RegisterOperands::detectDeadDefs(), llvm::LiveIntervals::getInstructionIndex(), llvm::GCNSchedStrategy::getNextStage(), llvm::GCNRegPressure::getOccupancy(), llvm::SlotIndex::getRegSlot(), llvm::LiveIntervals::handleMove(), llvm::GCNSchedStrategy::hasNextStage(), llvm::MachineBasicBlock::insert(), llvm::ScheduleDAGMI::LIS, LLVM_DEBUG, MI, llvm::ScheduleDAG::MRI, llvm::ScheduleDAGMI::placeDebugValues(), PressureBefore, llvm::ScheduleDAGInstrs::RegionBegin, llvm::ScheduleDAGInstrs::RegionEnd, RegionIdx, llvm::MachineBasicBlock::remove(), S, llvm::ScheduleDAGMILive::ShouldTrackLaneMasks, ST, llvm::ScheduleDAG::TRI, llvm::UnclusteredHighRPReschedule, and Unsched.
Referenced by checkScheduling().
setupNewBlock()
void GCNSchedStage::setupNewBlock ()
Definition at line 883 of file GCNSchedStrategy.cpp.
References CurrentMBB, DAG, llvm::ScheduleDAGMI::finishBlock(), llvm::ILPInitialSchedule, llvm::OccInitialSchedule, llvm::ScheduleDAGInstrs::RegionBegin, RegionIdx, StageID, and llvm::ScheduleDAGMI::startBlock().
Referenced by initGCNRegion().
shouldRevertScheduling()
bool GCNSchedStage::shouldRevertScheduling (unsigned WavesAfter) virtual
Reimplemented in llvm::OccInitialScheduleStage, llvm::UnclusteredHighRPStage, llvm::ClusteredLowOccStage, llvm::PreRARematStage, and llvm::ILPInitialScheduleStage.
Definition at line 1098 of file GCNSchedStrategy.cpp.
References DAG.
Referenced by checkScheduling(), llvm::OccInitialScheduleStage::shouldRevertScheduling(), llvm::UnclusteredHighRPStage::shouldRevertScheduling(), llvm::ClusteredLowOccStage::shouldRevertScheduling(), and llvm::PreRARematStage::shouldRevertScheduling().
Member Data Documentation
CurrentMBB
MachineBasicBlock* llvm::GCNSchedStage::CurrentMBB = nullptr protected
Definition at line 260 of file GCNSchedStrategy.h.
Referenced by initGCNRegion(), and setupNewBlock().
DAG
GCNScheduleDAGMILive& llvm::GCNSchedStage::DAG protected
Definition at line 247 of file GCNSchedStrategy.h.
Referenced by checkScheduling(), computeSUnitReadyCycle(), finalizeGCNRegion(), finalizeGCNSchedStage(), llvm::UnclusteredHighRPStage::finalizeGCNSchedStage(), getScheduleMetrics(), initGCNRegion(), llvm::UnclusteredHighRPStage::initGCNRegion(), llvm::ClusteredLowOccStage::initGCNRegion(), llvm::PreRARematStage::initGCNRegion(), initGCNSchedStage(), llvm::UnclusteredHighRPStage::initGCNSchedStage(), llvm::ClusteredLowOccStage::initGCNSchedStage(), llvm::PreRARematStage::initGCNSchedStage(), isRegionWithExcessRP(), revertScheduling(), setupNewBlock(), shouldRevertScheduling(), and llvm::UnclusteredHighRPStage::shouldRevertScheduling().
MF
MachineFunction& llvm::GCNSchedStage::MF protected
Definition at line 251 of file GCNSchedStrategy.h.
Referenced by checkScheduling(), initGCNRegion(), llvm::UnclusteredHighRPStage::initGCNSchedStage(), and llvm::PreRARematStage::initGCNSchedStage().
MFI
SIMachineFunctionInfo& llvm::GCNSchedStage::MFI protected
Definition at line 253 of file GCNSchedStrategy.h.
Referenced by checkScheduling(), llvm::UnclusteredHighRPStage::initGCNSchedStage(), llvm::PreRARematStage::initGCNSchedStage(), and mayCauseSpilling().
PressureAfter
GCNRegPressure llvm::GCNSchedStage::PressureAfter protected
Definition at line 272 of file GCNSchedStrategy.h.
Referenced by checkScheduling(), mayCauseSpilling(), llvm::OccInitialScheduleStage::shouldRevertScheduling(), and llvm::ClusteredLowOccStage::shouldRevertScheduling().
PressureBefore
GCNRegPressure llvm::GCNSchedStage::PressureBefore protected
Definition at line 269 of file GCNSchedStrategy.h.
Referenced by checkScheduling(), initGCNRegion(), mayCauseSpilling(), revertScheduling(), llvm::OccInitialScheduleStage::shouldRevertScheduling(), llvm::UnclusteredHighRPStage::shouldRevertScheduling(), and llvm::ClusteredLowOccStage::shouldRevertScheduling().
RegionIdx
unsigned llvm::GCNSchedStage::RegionIdx = 0 protected
Definition at line 263 of file GCNSchedStrategy.h.
Referenced by advanceRegion(), checkScheduling(), finalizeGCNRegion(), initGCNRegion(), llvm::UnclusteredHighRPStage::initGCNRegion(), llvm::ClusteredLowOccStage::initGCNRegion(), llvm::PreRARematStage::initGCNRegion(), isRegionWithExcessRP(), revertScheduling(), and setupNewBlock().
S
GCNSchedStrategy& llvm::GCNSchedStage::S protected
Definition at line 249 of file GCNSchedStrategy.h.
Referenced by checkScheduling(), finalizeGCNRegion(), llvm::UnclusteredHighRPStage::finalizeGCNSchedStage(), initGCNRegion(), llvm::UnclusteredHighRPStage::initGCNSchedStage(), llvm::PreRARematStage::initGCNSchedStage(), revertScheduling(), and llvm::UnclusteredHighRPStage::shouldRevertScheduling().
SavedMutations
std::vector<std::unique_ptr<ScheduleDAGMutation> > llvm::GCNSchedStage::SavedMutations protected
Definition at line 274 of file GCNSchedStrategy.h.
Referenced by finalizeGCNRegion(), llvm::UnclusteredHighRPStage::finalizeGCNSchedStage(), initGCNRegion(), and llvm::UnclusteredHighRPStage::initGCNSchedStage().
ST
const GCNSubtarget& llvm::GCNSchedStage::ST protected
Definition at line 255 of file GCNSchedStrategy.h.
Referenced by checkScheduling(), getScheduleMetrics(), getScheduleMetrics(), llvm::PreRARematStage::initGCNSchedStage(), mayCauseSpilling(), revertScheduling(), and llvm::UnclusteredHighRPStage::shouldRevertScheduling().
StageID
const GCNSchedStageID llvm::GCNSchedStage::StageID protected
Definition at line 257 of file GCNSchedStrategy.h.
Referenced by finalizeGCNRegion(), finalizeGCNSchedStage(), llvm::UnclusteredHighRPStage::finalizeGCNSchedStage(), initGCNRegion(), initGCNSchedStage(), and setupNewBlock().
Unsched
std::vector<MachineInstr *> llvm::GCNSchedStage::Unsched protected
Definition at line 266 of file GCNSchedStrategy.h.
Referenced by initGCNRegion(), and revertScheduling().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNSchedStrategy.h
lib/Target/AMDGPU/GCNSchedStrategy.cpp