LLVM: llvm::DominatorTreeBase< NodeT, IsPostDom > Class Template Reference
llvm::DominatorTreeBase< NodeT, IsPostDom > Class Template Reference
Core dominator tree base class.
#include "llvm/Support/GenericDomTree.h"
Public Types
enum class VerificationLevel { Fast , Basic , Full }
using NodeTrait = DomTreeNodeTraits<NodeT>
using NodeType = typename NodeTrait::NodeType
using NodePtr = typename NodeTrait::NodePtr
using ParentPtr = typename NodeTrait::ParentPtr
using ParentType = std::remove_pointer_t<ParentPtr>
using UpdateType = cfg::Update<NodePtr>
using UpdateKind = cfg::UpdateKind
using root_iterator = typename SmallVectorImpl<NodeT *>::iterator
Iteration over roots.
using const_root_iterator = typename SmallVectorImpl<NodeT *>::const_iterator
Public Member Functions
DominatorTreeBase ()=default
DominatorTreeBase (DominatorTreeBase &&Arg)
DominatorTreeBase & operator= (DominatorTreeBase &&RHS)
DominatorTreeBase (const DominatorTreeBase &)=delete
DominatorTreeBase & operator= (const DominatorTreeBase &)=delete
root_iterator root_begin ()
const_root_iterator root_begin () const
root_iterator root_end ()
const_root_iterator root_end () const
size_t root_size () const
iterator_range< root_iterator > roots ()
iterator_range< const_root_iterator > roots () const
bool isPostDominator () const
isPostDominator - Returns true if analysis based of postdoms
bool compare (const DominatorTreeBase &Other) const
compare - Return false if the other dominator tree base matches this dominator tree base.
DomTreeNodeBase< NodeT > * getNode (const NodeT *BB) const
getNode - return the (Post)DominatorTree node for the specified basic block.
DomTreeNodeBase< NodeT > * operator[] (const NodeT *BB) const
See getNode.
DomTreeNodeBase< NodeT > * getRootNode ()
getRootNode - This returns the entry node for the CFG of the function.
const DomTreeNodeBase< NodeT > * getRootNode () const
void getDescendants (NodeT *R, SmallVectorImpl< NodeT * > &Result) const
Get all nodes dominated by R, including R itself.
bool properlyDominates (const DomTreeNodeBase< NodeT > *A, const DomTreeNodeBase< NodeT > *B) const
properlyDominates - Returns true iff A dominates B and A != B.
bool properlyDominates (const NodeT *A, const NodeT *B) const
bool isReachableFromEntry (const NodeT *A) const
isReachableFromEntry - Return true if A is dominated by the entry block of the function containing it.
bool isReachableFromEntry (const DomTreeNodeBase< NodeT > *A) const
bool dominates (const DomTreeNodeBase< NodeT > *A, const DomTreeNodeBase< NodeT > *B) const
dominates - Returns true iff A dominates B.
bool dominates (const NodeT *A, const NodeT *B) const
NodeT * getRoot () const
NodeT * findNearestCommonDominator (NodeT *A, NodeT *B) const
Find nearest common dominator basic block for basic block A and B.
const NodeT * findNearestCommonDominator (const NodeT *A, const NodeT *B) const
bool isVirtualRoot (const DomTreeNodeBase< NodeT > *A) const
void applyUpdates (ArrayRef< UpdateType > Updates)
Inform the dominator tree about a sequence of CFG edge insertions and deletions and perform a batch update on the tree.
void applyUpdates (ArrayRef< UpdateType > Updates, ArrayRef< UpdateType > PostViewUpdates)
void insertEdge (NodeT *From, NodeT *To)
Inform the dominator tree about a CFG edge insertion and update the tree.
void deleteEdge (NodeT *From, NodeT *To)
Inform the dominator tree about a CFG edge deletion and update the tree.
DomTreeNodeBase< NodeT > * addNewBlock (NodeT *BB, NodeT *DomBB)
Add a new node to the dominator tree information.
DomTreeNodeBase< NodeT > * setNewRoot (NodeT *BB)
Add a new node to the forward dominator tree and make it a new root.
void changeImmediateDominator (DomTreeNodeBase< NodeT > *N, DomTreeNodeBase< NodeT > *NewIDom)
changeImmediateDominator - This method is used to update the dominator tree information when a node's immediate dominator changes.
void changeImmediateDominator (NodeT *BB, NodeT *NewBB)
void eraseNode (NodeT *BB)
eraseNode - Removes a node from the dominator tree.
void splitBlock (NodeT *NewBB)
splitBlock - BB is split and now it has one successor.
void print (raw_ostream &O) const
print - Convert to human readable form
void updateDFSNumbers () const
updateDFSNumbers - Assign In and Out numbers to the nodes while walking dominator tree in dfs order.
void recalculate (ParentType &Func)
recalculate - compute a dominator tree for the given function
void recalculate (ParentType &Func, ArrayRef< UpdateType > Updates)
bool verify (VerificationLevel VL=VerificationLevel::Full) const
verify - checks if the tree is correct.
void reset ()
Static Public Attributes
static constexpr bool IsPostDominator = IsPostDom
static constexpr UpdateKind Insert = UpdateKind::Insert
static constexpr UpdateKind Delete = UpdateKind::Delete
Protected Types
using DomTreeNodeMapType
Protected Member Functions
void addRoot (NodeT *BB)
DomTreeNodeBase< NodeT > * createChild (NodeT *BB, DomTreeNodeBase< NodeT > *IDom)
DomTreeNodeBase< NodeT > * createNode (NodeT *BB)
template<class N >
void Split (typename GraphTraits< N >::NodeRef NewBB)
void addRoot (MachineBasicBlock *MBB)
Protected Attributes
SmallVector< NodeT *, IsPostDom ? 4 :1 > Roots
DomTreeNodeMapType DomTreeNodes
DomTreeNodeBase< NodeT > * RootNode = nullptr
ParentPtr Parent = nullptr
bool DFSInfoValid = false
unsigned int SlowQueries = 0
Friends
struct DomTreeBuilder::SemiNCAInfo< DominatorTreeBase >
Detailed Description
template<typename NodeT, bool IsPostDom>
class llvm::DominatorTreeBase< NodeT, IsPostDom >
Core dominator tree base class.
This class is a generic template over graph nodes. It is instantiated for various graphs in the LLVM IR or in the code generator.
Definition at line 243 of file GenericDomTree.h.
Member Typedef Documentation
const_root_iterator
template<typename NodeT , bool IsPostDom> using llvm::DominatorTreeBase< NodeT, IsPostDom >::const_root_iterator = typename SmallVectorImpl<NodeT *>::const_iterator
Definition at line 311 of file GenericDomTree.h.
DomTreeNodeMapType
template<typename NodeT , bool IsPostDom> using llvm::DominatorTreeBase< NodeT, IsPostDom >::DomTreeNodeMapType protected
Initial value:
     DenseMap<NodeT *, std::unique_ptr<DomTreeNodeBase<NodeT>>>
Definition at line 267 of file GenericDomTree.h.
NodePtr
template<typename NodeT , bool IsPostDom> using llvm::DominatorTreeBase< NodeT, IsPostDom >::NodePtr = typename NodeTrait::NodePtr
Definition at line 249 of file GenericDomTree.h.
NodeTrait
template<typename NodeT , bool IsPostDom> using llvm::DominatorTreeBase< NodeT, IsPostDom >::NodeTrait = DomTreeNodeTraits<NodeT>
Definition at line 247 of file GenericDomTree.h.
NodeType
template<typename NodeT , bool IsPostDom> using llvm::DominatorTreeBase< NodeT, IsPostDom >::NodeType = typename NodeTrait::NodeType
Definition at line 248 of file GenericDomTree.h.
ParentPtr
template<typename NodeT , bool IsPostDom> using llvm::DominatorTreeBase< NodeT, IsPostDom >::ParentPtr = typename NodeTrait::ParentPtr
Definition at line 250 of file GenericDomTree.h.
ParentType
template<typename NodeT , bool IsPostDom> using llvm::DominatorTreeBase< NodeT, IsPostDom >::ParentType = std::remove_pointer_t<ParentPtr>
Definition at line 253 of file GenericDomTree.h.
root_iterator
template<typename NodeT , bool IsPostDom> using llvm::DominatorTreeBase< NodeT, IsPostDom >::root_iterator = typename SmallVectorImpl<NodeT *>::iterator
Iteration over roots.
This may include multiple blocks if we are computing post dominators. For forward dominators, this will always be a single block (the entry block).
Definition at line 310 of file GenericDomTree.h.
UpdateKind
template<typename NodeT , bool IsPostDom> using llvm::DominatorTreeBase< NodeT, IsPostDom >::UpdateKind = cfg::UpdateKind
Definition at line 257 of file GenericDomTree.h.
UpdateType
template<typename NodeT , bool IsPostDom> using llvm::DominatorTreeBase< NodeT, IsPostDom >::UpdateType = cfg::Update<NodePtr>
Definition at line 256 of file GenericDomTree.h.
Member Enumeration Documentation
VerificationLevel
template<typename NodeT , bool IsPostDom> enum class llvm::DominatorTreeBase::VerificationLevel strong
Enumerator
Fast
Basic
Full
Definition at line 261 of file GenericDomTree.h.
Constructor & Destructor Documentation
DominatorTreeBase() [1/3]
template<typename NodeT , bool IsPostDom> llvm::DominatorTreeBase< NodeT, IsPostDom >::DominatorTreeBase () default
DominatorTreeBase() [2/3]
template<typename NodeT , bool IsPostDom> llvm::DominatorTreeBase< NodeT, IsPostDom >::DominatorTreeBase (DominatorTreeBase< NodeT, IsPostDom > && Arg) inline
Definition at line 281 of file GenericDomTree.h.
References Arg.
DominatorTreeBase() [3/3]
template<typename NodeT , bool IsPostDom> llvm::DominatorTreeBase< NodeT, IsPostDom >::DominatorTreeBase (const DominatorTreeBase< NodeT, IsPostDom > &) delete
Member Function Documentation
addNewBlock()
template<typename NodeT , bool IsPostDom> DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT, IsPostDom >::addNewBlock (NodeT * BB, NodeT * DomBB) inline
Add a new node to the dominator tree information.
This creates a new node as a child of DomBB dominator node, linking it into the children list of the immediate dominator.
Parameters
BB New node in CFG.
DomBB CFG node that is dominator for BB.
Returns
New dominator tree node that represents new CFG node.
Definition at line 636 of file GenericDomTree.h.
References assert(), llvm::DominatorTreeBase< NodeT, IsPostDom >::createChild(), llvm::DominatorTreeBase< NodeT, IsPostDom >::DFSInfoValid, and llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode().
Referenced by cloneLoopBlocks(), CloneLoopBlocks(), llvm::cloneLoopWithPreheader(), llvm::DominatorTreeBase< NodeT, IsPostDom >::Split(), SplitBlockImpl(), llvm::UnrollAndJamLoop(), and llvm::UnrollLoop().
addRoot() [1/2]
void llvm::DominatorTreeBase< MachineBasicBlock, false >::addRoot (MachineBasicBlock * MBB) inline protected
Definition at line 35 of file MachineDominators.h.
References MBB.
addRoot() [2/2]
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::addRoot (NodeT * BB) inline protected
Definition at line 833 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot().
applyUpdates() [1/2]
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::applyUpdates (ArrayRef< UpdateType > Updates) inline
Inform the dominator tree about a sequence of CFG edge insertions and deletions and perform a batch update on the tree.
This function should be used when there were multiple CFG updates after the last dominator tree update. It takes care of performing the updates in sync with the CFG and optimizes away the redundant operations that cancel each other. The functions expects the sequence of updates to be balanced. Eg.:
{{Insert, A, B}, {Delete, A, B}, {Insert, A, B}} is fine, because logically it results in a single insertions.
{{Insert, A, B}, {Insert, A, B}} is invalid, because it doesn't make sense to insert the same edge twice.
What's more, the functions assumes that it's safe to ask every node in the CFG about its children and inverse children. This implies that deletions of CFG edges must not delete the CFG nodes before calling this function.
The applyUpdates function can reorder the updates and remove redundant ones internally (as long as it is done in a deterministic fashion). The batch updater is also able to detect sequences of zero and exactly one update – it's optimized to do less work in these cases.
Note that for postdominators it automatically takes care of applying updates on reverse edges internally (so there's no need to swap the From and To pointers when constructing DominatorTree::UpdateType). The type of updates is the same for DomTreeBase<T> and PostDomTreeBase<T> with the same template parameter T.
Parameters
Updates An ordered sequence of updates to perform. The current CFG and the reverse of these updates provides the pre-view of the CFG.
Definition at line 561 of file GenericDomTree.h.
References llvm::DomTreeBuilder::ApplyUpdates().
Referenced by llvm::DomTreeUpdater::applyUpdates(), llvm::DomTreeUpdater::applyUpdatesPermissive(), injectPendingInvariantConditions(), splitBlock(), unswitchNontrivialInvariants(), and unswitchTrivialSwitch().
applyUpdates() [2/2]
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::applyUpdates (ArrayRef< UpdateType > Updates, ArrayRef< UpdateType > PostViewUpdates) inline
Parameters
Updates An ordered sequence of updates to perform. The current CFG and the reverse of these updates provides the pre-view of the CFG.
PostViewUpdates An ordered sequence of update to perform in order to obtain a post-view of the CFG. The DT will be updated assuming the obtained PostViewCFG is the desired end state.
Definition at line 572 of file GenericDomTree.h.
References llvm::append_range(), and llvm::DomTreeBuilder::ApplyUpdates().
changeImmediateDominator() [1/2]
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator (DomTreeNodeBase< NodeT > * N, DomTreeNodeBase< NodeT > * NewIDom) inline
changeImmediateDominator - This method is used to update the dominator tree information when a node's immediate dominator changes.
Definition at line 672 of file GenericDomTree.h.
References assert(), llvm::DominatorTreeBase< NodeT, IsPostDom >::DFSInfoValid, and N.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), cloneLoopBlocks(), llvm::cloneLoopWithPreheader(), ConnectEpilog(), ConnectProlog(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), llvm::InnerLoopVectorizer::createVectorLoopSkeleton(), llvm::InnerLoopVectorizer::emitIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitIterationCountCheck(), llvm::InnerLoopVectorizer::emitSCEVChecks(), llvm::peelLoop(), simplifyOneLoop(), llvm::DominatorTreeBase< NodeT, IsPostDom >::Split(), SplitBlockImpl(), llvm::splitLoopBound(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), and llvm::LoopVersioning::versionLoop().
changeImmediateDominator() [2/2]
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator (NodeT * BB, NodeT * NewBB) inline
Definition at line 679 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode().
compare()
template<typename NodeT , bool IsPostDom> bool llvm::DominatorTreeBase< NodeT, IsPostDom >::compare (const DominatorTreeBase< NodeT, IsPostDom > & Other) const inline
compare - Return false if the other dominator tree base matches this dominator tree base.
Otherwise return true.
Definition at line 333 of file GenericDomTree.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::DominatorTreeBase< NodeT, IsPostDom >::DomTreeNodes, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::Other, llvm::DominatorTreeBase< NodeT, IsPostDom >::Parent, llvm::DominatorTreeBase< NodeT, IsPostDom >::Roots, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), and llvm::SmallVectorBase< Size_T >::size().
createChild()
template<typename NodeT , bool IsPostDom> DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT, IsPostDom >::createChild (NodeT * BB, DomTreeNodeBase< NodeT > * IDom) inline protected
Definition at line 835 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::DomTreeNodes.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::addNewBlock().
createNode()
template<typename NodeT , bool IsPostDom> DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT, IsPostDom >::createNode (NodeT * BB) inline protected
Definition at line 841 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::DomTreeNodes.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot().
deleteEdge()
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::deleteEdge (NodeT * From, NodeT * To) inline
Inform the dominator tree about a CFG edge deletion and update the tree.
This function has to be called just after making the update on the actual CFG. An internal functions checks if the edge doesn't exist in the CFG in DEBUG mode. There cannot be any other updates that the dominator tree doesn't know about.
Note that for postdominators it automatically takes care of deleting a reverse edge internally (so there's no need to swap the parameters).
Definition at line 619 of file GenericDomTree.h.
References assert(), llvm::DomTreeBuilder::DeleteEdge(), From, and llvm::DominatorTreeBase< NodeT, IsPostDom >::Parent.
Referenced by DoFlattenLoopPair(), replaceArgumentUses(), and unswitchTrivialBranch().
dominates() [1/2]
template<typename NodeT , bool IsPostDom> bool llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates (const DomTreeNodeBase< NodeT > * A, const DomTreeNodeBase< NodeT > * B) const inline
dominates - Returns true iff A dominates B.
Note that this is not a constant time operation!
Definition at line 432 of file GenericDomTree.h.
References A, assert(), B, llvm::DominatorTreeBase< NodeT, IsPostDom >::DFSInfoValid, llvm::DominatorTreeBase< NodeT, IsPostDom >::isReachableFromEntry(), llvm::DominatorTreeBase< NodeT, IsPostDom >::SlowQueries, and llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers().
Referenced by llvm::PostDominatorTree::dominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::Split().
dominates() [2/2]
template<typename NodeT , bool IsPostDom> bool llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates (const NodeT * A, const NodeT * B) const
Definition at line 940 of file GenericDomTree.h.
References A, B, and dominates().
eraseNode()
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::eraseNode (NodeT * BB) inline
eraseNode - Removes a node from the dominator tree.
Block must not dominate any other blocks. Removes node from its immediate dominator's children list. Deletes dominator node associated with basic block BB.
Definition at line 686 of file GenericDomTree.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::DominatorTreeBase< NodeT, IsPostDom >::DFSInfoValid, llvm::DominatorTreeBase< NodeT, IsPostDom >::DomTreeNodes, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::find(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), I, llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::DominatorTreeBase< NodeT, IsPostDom >::Roots, and std::swap().
Referenced by simplifyOneLoop().
findNearestCommonDominator() [1/2]
template<typename NodeT , bool IsPostDom> const NodeT * llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator (const NodeT * A, const NodeT * B) const inline
Definition at line 514 of file GenericDomTree.h.
References A, B, and llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator().
findNearestCommonDominator() [2/2]
template<typename NodeT , bool IsPostDom> NodeT * llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator (NodeT * A, NodeT * B) const inline
Find nearest common dominator basic block for basic block A and B.
A and B must have tree nodes.
Definition at line 484 of file GenericDomTree.h.
References A, assert(), B, llvm::DomTreeNodeTraits< NodeT >::getEntryNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::isPostDominator(), and std::swap().
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::Split().
getDescendants()
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::getDescendants (NodeT * R, SmallVectorImpl< NodeT * > & Result) const inline
Get all nodes dominated by R, including R itself.
Definition at line 390 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), and N.
Referenced by replaceArgumentUses().
getNode()
template<typename NodeT , bool IsPostDom> DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode (const NodeT * BB) const inline
getNode - return the (Post)DominatorTree node for the specified basic block.
This is the same as using operator[] on this class. The result may (but is not required to) be null for a forward (backwards) statically unreachable block.
Definition at line 367 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::DomTreeNodes, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::addNewBlock(), llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), checkAndReplaceCondition(), checkHoistValue(), cloneLoopBlocks(), CloneLoopBlocks(), llvm::cloneLoopWithPreheader(), collectUnswitchCandidatesWithInjections(), compareCmp(), llvm::ValueDFS_Compare::comparePHIRelated(), computeBlocksDominatingExits(), containsUnconditionalCallSafepoint(), domTreeLevelBefore(), eliminateConstraints(), llvm::InnerLoopVectorizer::emitIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitIterationCountCheck(), llvm::DominatorTreeBase< NodeT, IsPostDom >::eraseNode(), llvm::MustBeExecutedContextExplorer::findBackwardJoinPoint(), findBestInsertionSet(), llvm::MustBeExecutedContextExplorer::findForwardJoinPoint(), llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator(), llvm::formLCSSAForInstructions(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getDescendants(), getDominatees(), getDominators(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), llvm::hoistRegion(), hoistValue(), isGuaranteedNotToBeUndefOrPoison(), llvm::DominatorTreeBase< NodeT, IsPostDom >::isReachableFromEntry(), llvm::MergeBlockIntoPredecessor(), llvm::DominatorTreeBase< NodeT, IsPostDom >::operator[](), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::peelLoop(), preheader(), llvm::GuardWideningPass::run(), llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot(), shouldSplitOnPredicatedArgument(), simplifyOneLoop(), simplifyUsingControlFlow(), SinkInstruction(), llvm::sinkRegionForLoopNest(), llvm::DominatorTreeBase< NodeT, IsPostDom >::Split(), SplitBlockImpl(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), and llvm::MemorySSA::verifyPrevDefInPhis().
getRoot()
template<typename NodeT , bool IsPostDom> NodeT * llvm::DominatorTreeBase< NodeT, IsPostDom >::getRoot () const inline
Definition at line 477 of file GenericDomTree.h.
References assert().
Referenced by llvm::ForwardDominanceFrontierBase< BlockT >::analyze(), getFreezeInsertPt(), and nearest_common_dominatee().
getRootNode() [1/2]
template<typename NodeT , bool IsPostDom> DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT, IsPostDom >::getRootNode () inline
getRootNode - This returns the entry node for the CFG of the function.
If this tree represents the post-dominance relations for a function, however, this root may be a node with the block == NULL. This is the case when there are multiple exit nodes from a particular function. Consumers of post-dominance information must be capable of dealing with this possibility.
Definition at line 386 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::RootNode.
Referenced by llvm::PredicateInfoBuilder::buildPredicateInfo(), llvm::GraphTraits< DominatorTree * >::getEntryNode(), llvm::GraphTraits< PostDominatorTree * >::getEntryNode(), llvm::MemorySSA::OptimizeUses::optimizeUses(), llvm::DominatorTreeBase< NodeT, IsPostDom >::print(), llvm::GuardWideningPass::run(), UpdateAnalysisInformation(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers().
getRootNode() [2/2]
template<typename NodeT , bool IsPostDom> const DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT, IsPostDom >::getRootNode () const inline
Definition at line 387 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::RootNode.
insertEdge()
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::insertEdge (NodeT * From, NodeT * To) inline
Inform the dominator tree about a CFG edge insertion and update the tree.
This function has to be called just before or just after making the update on the actual CFG. There cannot be any other updates that the dominator tree doesn't know about.
Note that for postdominators it automatically takes care of inserting a reverse edge internally (so there's no need to swap the parameters).
Definition at line 601 of file GenericDomTree.h.
References assert(), From, llvm::DomTreeBuilder::InsertEdge(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::Parent.
Referenced by replaceArgumentUses(), and unswitchTrivialBranch().
isPostDominator()
template<typename NodeT , bool IsPostDom> bool llvm::DominatorTreeBase< NodeT, IsPostDom >::isPostDominator () const inline
isPostDominator - Returns true if analysis based of postdoms
Definition at line 329 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::IsPostDominator.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator(), llvm::DominatorTreeBase< NodeT, IsPostDom >::isReachableFromEntry(), llvm::DominatorTreeBase< NodeT, IsPostDom >::isVirtualRoot(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot().
isReachableFromEntry() [1/2]
template<typename NodeT , bool IsPostDom> bool llvm::DominatorTreeBase< NodeT, IsPostDom >::isReachableFromEntry (const DomTreeNodeBase< NodeT > * A) const inline
Definition at line 427 of file GenericDomTree.h.
References A.
isReachableFromEntry() [2/2]
template<typename NodeT , bool IsPostDom> bool llvm::DominatorTreeBase< NodeT, IsPostDom >::isReachableFromEntry (const NodeT * A) const inline
isReachableFromEntry - Return true if A is dominated by the entry block of the function containing it.
Definition at line 421 of file GenericDomTree.h.
References A, assert(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::isPostDominator(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::isReachableFromEntry().
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::isReachableFromEntry(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::Split().
isVirtualRoot()
template<typename NodeT , bool IsPostDom> bool llvm::DominatorTreeBase< NodeT, IsPostDom >::isVirtualRoot (const DomTreeNodeBase< NodeT > * A) const inline
Definition at line 522 of file GenericDomTree.h.
References A, and llvm::DominatorTreeBase< NodeT, IsPostDom >::isPostDominator().
operator=() [1/2]
template<typename NodeT , bool IsPostDom> DominatorTreeBase & llvm::DominatorTreeBase< NodeT, IsPostDom >::operator= (const DominatorTreeBase< NodeT, IsPostDom > &) delete
operator=() [2/2]
template<typename NodeT , bool IsPostDom> DominatorTreeBase & llvm::DominatorTreeBase< NodeT, IsPostDom >::operator= (DominatorTreeBase< NodeT, IsPostDom > && RHS) inline
Definition at line 291 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::DFSInfoValid, llvm::DominatorTreeBase< NodeT, IsPostDom >::DomTreeNodes, llvm::DominatorTreeBase< NodeT, IsPostDom >::Parent, llvm::DominatorTreeBase< NodeT, IsPostDom >::RootNode, llvm::DominatorTreeBase< NodeT, IsPostDom >::Roots, and llvm::DominatorTreeBase< NodeT, IsPostDom >::SlowQueries.
operator[]()
template<typename NodeT , bool IsPostDom> DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT, IsPostDom >::operator[] (const NodeT * BB) const inline
See getNode.
Definition at line 375 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode().
print()
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::print (raw_ostream & O) const inline
print - Convert to human readable form
Definition at line 726 of file GenericDomTree.h.
References llvm::Block, llvm::DominatorTreeBase< NodeT, IsPostDom >::DFSInfoValid, llvm::DominatorTreeBase< NodeT, IsPostDom >::getRootNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::IsPostDominator, llvm::DominatorTreeBase< NodeT, IsPostDom >::Roots, and llvm::DominatorTreeBase< NodeT, IsPostDom >::SlowQueries.
Referenced by llvm::PostDominatorTreeWrapperPass::print(), and llvm::DominatorTreeWrapperPass::print().
properlyDominates() [1/2]
template<typename NodeT , bool IsPostDom> bool llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates (const DomTreeNodeBase< NodeT > * A, const DomTreeNodeBase< NodeT > * B) const inline
properlyDominates - Returns true iff A dominates B and A != B.
Note that this is not a constant time operation!
Definition at line 408 of file GenericDomTree.h.
References A, B, and llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates().
Referenced by llvm::ForwardDominanceFrontierBase< BlockT >::calculate(), ConstructSSAForLoadSet(), llvm::InnerLoopVectorizer::emitIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitIterationCountCheck(), and isLoadInvariantInLoop().
properlyDominates() [2/2]
template<typename NodeT , bool IsPostDom> bool llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates (const NodeT * A, const NodeT * B) const
Definition at line 952 of file GenericDomTree.h.
References A, B, and dominates().
recalculate() [1/2]
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::recalculate (ParentType & Func) inline
recalculate - compute a dominator tree for the given function
Definition at line 795 of file GenericDomTree.h.
References llvm::DomTreeBuilder::Calculate(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::Parent.
Referenced by AddAliasScopeMetadata(), AddAlignmentAssumptions(), llvm::OptimizationRemarkEmitter::OptimizationRemarkEmitter(), llvm::PostDominatorTree::PostDominatorTree(), llvm::DomTreeUpdater::recalculate(), llvm::DominatorTreeAnalysis::run(), llvm::PlaceSafepointsPass::runImpl(), and llvm::PostDominatorTreeWrapperPass::runOnFunction().
recalculate() [2/2]
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::recalculate (ParentType & Func, ArrayRef< UpdateType > Updates) inline
Definition at line 800 of file GenericDomTree.h.
References llvm::DomTreeBuilder::CalculateWithUpdates(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::Parent.
reset()
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::reset () inline
Definition at line 823 of file GenericDomTree.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::DominatorTreeBase< NodeT, IsPostDom >::DFSInfoValid, llvm::DominatorTreeBase< NodeT, IsPostDom >::DomTreeNodes, llvm::DominatorTreeBase< NodeT, IsPostDom >::Parent, llvm::DominatorTreeBase< NodeT, IsPostDom >::RootNode, llvm::DominatorTreeBase< NodeT, IsPostDom >::Roots, and llvm::DominatorTreeBase< NodeT, IsPostDom >::SlowQueries.
Referenced by llvm::MachineDominatorTree::getBase(), llvm::PostDominatorTreeWrapperPass::releaseMemory(), and llvm::DominatorTreeWrapperPass::releaseMemory().
root_begin() [1/2]
template<typename NodeT , bool IsPostDom> root_iterator llvm::DominatorTreeBase< NodeT, IsPostDom >::root_begin () inline
Definition at line 313 of file GenericDomTree.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::Roots.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::roots(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::roots().
root_begin() [2/2]
template<typename NodeT , bool IsPostDom> const_root_iterator llvm::DominatorTreeBase< NodeT, IsPostDom >::root_begin () const inline
Definition at line 314 of file GenericDomTree.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::Roots.
root_end() [1/2]
template<typename NodeT , bool IsPostDom> root_iterator llvm::DominatorTreeBase< NodeT, IsPostDom >::root_end () inline
Definition at line 315 of file GenericDomTree.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::Roots.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::roots(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::roots().
root_end() [2/2]
template<typename NodeT , bool IsPostDom> const_root_iterator llvm::DominatorTreeBase< NodeT, IsPostDom >::root_end () const inline
Definition at line 316 of file GenericDomTree.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::Roots.
root_size()
template<typename NodeT , bool IsPostDom> size_t llvm::DominatorTreeBase< NodeT, IsPostDom >::root_size () const inline
Definition at line 318 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::Roots, and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::ForwardDominanceFrontierBase< BlockT >::analyze().
roots() [1/2]
template<typename NodeT , bool IsPostDom> iterator_range< root_iterator > llvm::DominatorTreeBase< NodeT, IsPostDom >::roots () inline
Definition at line 320 of file GenericDomTree.h.
References llvm::make_range(), llvm::DominatorTreeBase< NodeT, IsPostDom >::root_begin(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::root_end().
roots() [2/2]
template<typename NodeT , bool IsPostDom> iterator_range< const_root_iterator > llvm::DominatorTreeBase< NodeT, IsPostDom >::roots () const inline
Definition at line 323 of file GenericDomTree.h.
References llvm::make_range(), llvm::DominatorTreeBase< NodeT, IsPostDom >::root_begin(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::root_end().
setNewRoot()
template<typename NodeT , bool IsPostDom> DomTreeNodeBase< NodeT > * llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot (NodeT * BB) inline
Add a new node to the forward dominator tree and make it a new root.
Parameters
BB New node in CFG.
Returns
New dominator tree node that represents new CFG node.
Definition at line 649 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::addRoot(), assert(), llvm::DominatorTreeBase< NodeT, IsPostDom >::createNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::DomTreeNodes, llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::isPostDominator(), llvm::DominatorTreeBase< NodeT, IsPostDom >::RootNode, llvm::DominatorTreeBase< NodeT, IsPostDom >::Roots, and llvm::SmallVectorBase< Size_T >::size().
Referenced by UpdateAnalysisInformation().
Split()
template<typename NodeT , bool IsPostDom> template<class N > void llvm::DominatorTreeBase< NodeT, IsPostDom >::Split (typename GraphTraits< N >::NodeRef NewBB) inline protected
Definition at line 850 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::addNewBlock(), assert(), llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), llvm::children(), llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::isReachableFromEntry().
splitBlock()
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::splitBlock (NodeT * NewBB) inline
splitBlock - BB is split and now it has one successor.
Update dominator tree to reflect this change.
Definition at line 717 of file GenericDomTree.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::IsPostDominator.
Referenced by insertUniqueBackedgeBlock(), and UpdateAnalysisInformation().
updateDFSNumbers()
template<typename NodeT , bool IsPostDom> void llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers () const inline
updateDFSNumbers - Assign In and Out numbers to the nodes while walking dominator tree in dfs order.
Definition at line 749 of file GenericDomTree.h.
References assert(), llvm::DominatorTreeBase< NodeT, IsPostDom >::DFSInfoValid, llvm::DominatorTreeBase< NodeT, IsPostDom >::getRootNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::Parent, and llvm::DominatorTreeBase< NodeT, IsPostDom >::SlowQueries.
Referenced by llvm::PredicateInfoBuilder::buildPredicateInfo(), llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), eliminateConstraints(), llvm::isSafeToMoveBefore(), and llvm::SLPVectorizerPass::runImpl().
verify()
template<typename NodeT , bool IsPostDom> bool llvm::DominatorTreeBase< NodeT, IsPostDom >::verify (VerificationLevel VL = VerificationLevel::Full) const inline
verify - checks if the tree is correct.
There are 3 level of verification:
Full – verifies if the tree is correct by making sure all the properties (including the parent and the sibling property) hold. Takes O(N^3) time.
Basic – checks if the tree is correct, but compares it to a freshly constructed tree instead of checking the sibling property. Takes O(N^2) time.
Fast – checks basic tree structure and compares it with a freshly constructed tree. Takes O(N^2) time worst case, but is faster in practise (same as tree construction).
Definition at line 819 of file GenericDomTree.h.
References llvm::DomTreeBuilder::Verify().
Referenced by llvm::InnerLoopVectorizer::completeLoopSkeleton(), createNaturalLoopInternal(), llvm::hoistRegion(), injectPendingInvariantConditions(), llvm::peelLoop(), llvm::LoopBoundSplitPass::run(), llvm::SimpleLoopUnswitchPass::run(), runImpl(), simplifyFunctionCFG(), unifyLoopExits(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchTrivialSwitch(), llvm::PostDominatorTreeWrapperPass::verifyAnalysis(), and llvm::DominatorTreeWrapperPass::verifyAnalysis().
Friends And Related Symbol Documentation
DomTreeBuilder::SemiNCAInfo< DominatorTreeBase >
template<typename NodeT , bool IsPostDom> friend struct DomTreeBuilder::SemiNCAInfo< DominatorTreeBase > friend
Definition at line 274 of file GenericDomTree.h.
Member Data Documentation
Delete
template<typename NodeT , bool IsPostDom> constexpr UpdateKind llvm::DominatorTreeBase< NodeT, IsPostDom >::Delete = UpdateKind::Delete static constexpr
Definition at line 259 of file GenericDomTree.h.
Referenced by llvm::MemorySSAUpdater::applyUpdates(), and unswitchTrivialSwitch().
DFSInfoValid
template<typename NodeT , bool IsPostDom> bool llvm::DominatorTreeBase< NodeT, IsPostDom >::DFSInfoValid = false mutable protected
Definition at line 273 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::addNewBlock(), llvm::DominatorTreeBase< NodeT, IsPostDom >::changeImmediateDominator(), llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::eraseNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::operator=(), llvm::DominatorTreeBase< NodeT, IsPostDom >::print(), llvm::DominatorTreeBase< NodeT, IsPostDom >::reset(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers().
DomTreeNodes
template<typename NodeT , bool IsPostDom> DomTreeNodeMapType llvm::DominatorTreeBase< NodeT, IsPostDom >::DomTreeNodes protected
Definition at line 269 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::compare(), llvm::DominatorTreeBase< NodeT, IsPostDom >::createChild(), llvm::DominatorTreeBase< NodeT, IsPostDom >::createNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::eraseNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::operator=(), llvm::DominatorTreeBase< NodeT, IsPostDom >::reset(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot().
Insert
template<typename NodeT , bool IsPostDom> constexpr UpdateKind llvm::DominatorTreeBase< NodeT, IsPostDom >::Insert = UpdateKind::Insert static constexpr
Definition at line 258 of file GenericDomTree.h.
Referenced by llvm::MemorySSAUpdater::applyUpdates(), and unswitchTrivialSwitch().
IsPostDominator
template<typename NodeT , bool IsPostDom> constexpr bool llvm::DominatorTreeBase< NodeT, IsPostDom >::IsPostDominator = IsPostDom static constexpr
Definition at line 254 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::isPostDominator(), llvm::DominatorTreeBase< NodeT, IsPostDom >::print(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::splitBlock().
Parent
template<typename NodeT , bool IsPostDom> ParentPtr llvm::DominatorTreeBase< NodeT, IsPostDom >::Parent = nullptr protected
Definition at line 271 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::compare(), llvm::DominatorTreeBase< NodeT, IsPostDom >::deleteEdge(), llvm::DominatorTree::DominatorTree(), llvm::DominatorTreeBase< NodeT, IsPostDom >::insertEdge(), llvm::DominatorTreeBase< NodeT, IsPostDom >::operator=(), llvm::DominatorTreeBase< NodeT, IsPostDom >::recalculate(), llvm::DominatorTreeBase< NodeT, IsPostDom >::recalculate(), llvm::DominatorTreeBase< NodeT, IsPostDom >::reset(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers().
RootNode
template<typename NodeT , bool IsPostDom> DomTreeNodeBase<NodeT>* llvm::DominatorTreeBase< NodeT, IsPostDom >::RootNode = nullptr protected
Definition at line 270 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::getRootNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getRootNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::operator=(), llvm::DominatorTreeBase< NodeT, IsPostDom >::reset(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot().
Roots
template<typename NodeT , bool IsPostDom> SmallVector<NodeT *, IsPostDom ? 4 : 1> llvm::DominatorTreeBase< NodeT, IsPostDom >::Roots protected
Definition at line 265 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::compare(), llvm::DominatorTreeBase< NodeT, IsPostDom >::eraseNode(), llvm::DominatorTreeBase< NodeT, IsPostDom >::operator=(), llvm::DominatorTreeBase< NodeT, IsPostDom >::print(), llvm::DominatorTreeBase< NodeT, IsPostDom >::reset(), llvm::DominatorTreeBase< NodeT, IsPostDom >::root_begin(), llvm::DominatorTreeBase< NodeT, IsPostDom >::root_begin(), llvm::DominatorTreeBase< NodeT, IsPostDom >::root_end(), llvm::DominatorTreeBase< NodeT, IsPostDom >::root_end(), llvm::DominatorTreeBase< NodeT, IsPostDom >::root_size(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot().
SlowQueries
template<typename NodeT , bool IsPostDom> unsigned int llvm::DominatorTreeBase< NodeT, IsPostDom >::SlowQueries = 0 mutable protected
Definition at line 274 of file GenericDomTree.h.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::operator=(), llvm::DominatorTreeBase< NodeT, IsPostDom >::print(), llvm::DominatorTreeBase< NodeT, IsPostDom >::reset(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineSSAContext.h
include/llvm/Support/GenericDomTree.h