LLVM: llvm::TGVarScope Class Reference
llvm::TGVarScope Class Reference
#include "TableGen/TGParser.h"
Public Types
enum ScopeKind { SK_Local , SK_Record , SK_ForeachLoop , SK_MultiClass }
Public Member Functions
TGVarScope (std::unique_ptr< TGVarScope > Parent)
TGVarScope (std::unique_ptr< TGVarScope > Parent, Record *Rec)
TGVarScope (std::unique_ptr< TGVarScope > Parent, ForeachLoop *Loop)
TGVarScope (std::unique_ptr< TGVarScope > Parent, MultiClass *Multiclass)
std::unique_ptr< TGVarScope > extractParent ()
Init * getVar (RecordKeeper &Records, MultiClass *ParsingMultiClass, StringInit *Name, SMRange NameLoc, bool TrackReferenceLocs) const
bool varAlreadyDefined (StringRef Name) const
void addVar (StringRef Name, Init *I)
bool isOutermost () const
Detailed Description
Definition at line 88 of file TGParser.h.
Member Enumeration Documentation
ScopeKind
enum llvm::TGVarScope::ScopeKind
Enumerator
SK_Local
SK_Record
SK_ForeachLoop
SK_MultiClass
Definition at line 90 of file TGParser.h.
Constructor & Destructor Documentation
TGVarScope() [1/4]
llvm::TGVarScope::TGVarScope (std::unique_ptr< TGVarScope > Parent) inline
Definition at line 102 of file TGParser.h.
TGVarScope() [2/4]
llvm::TGVarScope::TGVarScope (std::unique_ptr< TGVarScope > Parent, Record * Rec) inline
Definition at line 104 of file TGParser.h.
TGVarScope() [3/4]
llvm::TGVarScope::TGVarScope (std::unique_ptr< TGVarScope > Parent, ForeachLoop * Loop) inline
Definition at line 106 of file TGParser.h.
TGVarScope() [4/4]
llvm::TGVarScope::TGVarScope (std::unique_ptr< TGVarScope > Parent, MultiClass * Multiclass) inline
Definition at line 108 of file TGParser.h.
Member Function Documentation
addVar()
void llvm::TGVarScope::addVar (StringRef Name, Init * I) inline
Definition at line 130 of file TGParser.h.
References assert(), I, and Name.
extractParent()
std::unique_ptr< TGVarScope > llvm::TGVarScope::extractParent () inline
Definition at line 112 of file TGParser.h.
getVar()
Init * TGVarScope::getVar (RecordKeeper & Records, MultiClass * ParsingMultiClass, StringInit * Name, SMRange NameLoc, bool TrackReferenceLocs) const
Definition at line 137 of file TGParser.cpp.
References assert(), llvm::StringRecTy::get(), llvm::VarInit::get(), llvm::VarInit::getNameInit(), llvm::Record::getValue(), llvm::Record::isClass(), llvm::Record::isTemplateArg(), llvm::ForeachLoop::IterVar, Name, QualifyName(), llvm::MultiClass::Rec, SK_ForeachLoop, SK_Local, SK_MultiClass, and SK_Record.
isOutermost()
bool llvm::TGVarScope::isOutermost () const inline
Definition at line 136 of file TGParser.h.
varAlreadyDefined()
bool llvm::TGVarScope::varAlreadyDefined (StringRef Name) const inline
Definition at line 122 of file TGParser.h.
References Name.
The documentation for this class was generated from the following files:
lib/TableGen/TGParser.h
lib/TableGen/TGParser.cpp