LLVM: llvm::DominatorTree Class Reference
llvm::DominatorTree Class Reference
Concrete subclass of DominatorTreeBase that is used to compute a normal dominator tree.
#include "llvm/IR/Dominators.h"
Public Types
using Base = DominatorTreeBase<BasicBlock, false>
Public Types inherited from llvm::DominatorTreeBase< BasicBlock, false >
enum VerificationLevel
using NodeTrait
using NodeType
using NodePtr
using ParentPtr
using ParentType
using UpdateType
using UpdateKind
using root_iterator
Iteration over roots.
using const_root_iterator
Public Member Functions
DominatorTree ()=default
DominatorTree (Function &F)
DominatorTree (DominatorTree &DT, DomTreeBuilder::BBUpdates U)
bool invalidate (Function &F, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &)
Handle invalidation explicitly.
bool dominates (const BasicBlock *BB, const Use &U) const
Return true if the (end of the) basic block BB dominates the use U.
bool dominates (const Value *Def, const Use &U) const
Return true if value Def dominates use U, in the sense that Def is available at U, and could be substituted as the used value without violating the SSA dominance requirement.
bool dominates (const Value *Def, const Instruction *User) const
Return true if value Def dominates all possible uses inside instruction User.
bool dominates (const Instruction *Def, const BasicBlock *BB) const
Returns true if Def would dominate a use in any instruction in BB.
bool dominates (const BasicBlockEdge &BBE, const Use &U) const
Return true if an edge dominates a use.
bool dominates (const BasicBlockEdge &BBE, const BasicBlock *BB) const
bool dominates (const BasicBlockEdge &BBE1, const BasicBlockEdge &BBE2) const
Returns true if edge BBE1 dominates edge BBE2.
bool isReachableFromEntry (const Use &U) const
Provide an overload for a Use.
Instruction * findNearestCommonDominator (Instruction *I1, Instruction *I2) const
Find the nearest instruction I that dominates both I1 and I2, in the sense that a result produced before I will be available at both I1 and I2.
void viewGraph (const Twine &Name, const Twine &Title)
void viewGraph ()
Public Member Functions inherited from llvm::DominatorTreeBase< BasicBlock, false >
DominatorTreeBase ()=default
DominatorTreeBase (DominatorTreeBase &&Arg)
DominatorTreeBase (const DominatorTreeBase &)=delete
DominatorTreeBase & operator= (DominatorTreeBase &&RHS)
DominatorTreeBase & operator= (const DominatorTreeBase &)=delete
root_iterator root_begin ()
const_root_iterator root_begin () const
root_iterator root_end ()
const_root_iterator root_end () const
size_t root_size () const
iterator_range< root_iterator > roots ()
iterator_range< const_root_iterator > roots () const
bool isPostDominator () const
isPostDominator - Returns true if analysis based of postdoms
bool compare (const DominatorTreeBase &Other) const
compare - Return false if the other dominator tree base matches this dominator tree base.
DomTreeNodeBase< BasicBlock > * getNode (const BasicBlock *BB) const
getNode - return the (Post)DominatorTree node for the specified basic block.
DomTreeNodeBase< BasicBlock > * operator[] (const BasicBlock *BB) const
See getNode.
DomTreeNodeBase< BasicBlock > * getRootNode ()
getRootNode - This returns the entry node for the CFG of the function.
const DomTreeNodeBase< BasicBlock > * getRootNode () const
void getDescendants (BasicBlock *R, SmallVectorImpl< BasicBlock * > &Result) const
Get all nodes dominated by R, including R itself.
bool properlyDominates (const DomTreeNodeBase< BasicBlock > *A, const DomTreeNodeBase< BasicBlock > *B) const
properlyDominates - Returns true iff A dominates B and A != B.
bool properlyDominates (const BasicBlock *A, const BasicBlock *B) const
bool isReachableFromEntry (const BasicBlock *A) const
isReachableFromEntry - Return true if A is dominated by the entry block of the function containing it.
bool isReachableFromEntry (const DomTreeNodeBase< BasicBlock > *A) const
bool dominates (const DomTreeNodeBase< BasicBlock > *A, const DomTreeNodeBase< BasicBlock > *B) const
dominates - Returns true iff A dominates B.
bool dominates (const BasicBlock *A, const BasicBlock *B) const
BasicBlock * getRoot () const
BasicBlock * findNearestCommonDominator (BasicBlock *A, BasicBlock *B) const
Find nearest common dominator basic block for basic block A and B.
const BasicBlock * findNearestCommonDominator (const BasicBlock *A, const BasicBlock *B) const
bool isVirtualRoot (const DomTreeNodeBase< BasicBlock > *A) const
void applyUpdates (ArrayRef< UpdateType > Updates)
Inform the dominator tree about a sequence of CFG edge insertions and deletions and perform a batch update on the tree.
void applyUpdates (ArrayRef< UpdateType > Updates, ArrayRef< UpdateType > PostViewUpdates)
void insertEdge (BasicBlock *From, BasicBlock *To)
Inform the dominator tree about a CFG edge insertion and update the tree.
void deleteEdge (BasicBlock *From, BasicBlock *To)
Inform the dominator tree about a CFG edge deletion and update the tree.
DomTreeNodeBase< BasicBlock > * addNewBlock (BasicBlock *BB, BasicBlock *DomBB)
Add a new node to the dominator tree information.
DomTreeNodeBase< BasicBlock > * setNewRoot (BasicBlock *BB)
Add a new node to the forward dominator tree and make it a new root.
void changeImmediateDominator (DomTreeNodeBase< BasicBlock > *N, DomTreeNodeBase< BasicBlock > *NewIDom)
changeImmediateDominator - This method is used to update the dominator tree information when a node's immediate dominator changes.
void changeImmediateDominator (BasicBlock *BB, BasicBlock *NewBB)
void eraseNode (BasicBlock *BB)
eraseNode - Removes a node from the dominator tree.
void splitBlock (BasicBlock *NewBB)
splitBlock - BB is split and now it has one successor.
void print (raw_ostream &O) const
print - Convert to human readable form
void updateDFSNumbers () const
updateDFSNumbers - Assign In and Out numbers to the nodes while walking dominator tree in dfs order.
void recalculate (ParentType &Func)
recalculate - compute a dominator tree for the given function
void recalculate (ParentType &Func, ArrayRef< UpdateType > Updates)
bool verify (VerificationLevel VL=VerificationLevel::Full) const
verify - checks if the tree is correct.
void reset ()
Additional Inherited Members
Static Public Attributes inherited from llvm::DominatorTreeBase< BasicBlock, false >
static constexpr bool IsPostDominator
static constexpr UpdateKind Insert
static constexpr UpdateKind Delete
Protected Types inherited from llvm::DominatorTreeBase< BasicBlock, false >
using DomTreeNodeMapType
Protected Member Functions inherited from llvm::DominatorTreeBase< BasicBlock, false >
void addRoot (BasicBlock *BB)
void addRoot (MachineBasicBlock *MBB)
DomTreeNodeBase< BasicBlock > * createChild (BasicBlock *BB, DomTreeNodeBase< BasicBlock > *IDom)
DomTreeNodeBase< BasicBlock > * createNode (BasicBlock *BB)
void Split (typename GraphTraits< N >::NodeRef NewBB)
Protected Attributes inherited from llvm::DominatorTreeBase< BasicBlock, false >
SmallVector< BasicBlock *, IsPostDom ? 4 :1 > Roots
DomTreeNodeMapType DomTreeNodes
DomTreeNodeBase< BasicBlock > * RootNode
ParentPtr Parent
bool DFSInfoValid
unsigned int SlowQueries
Detailed Description
Concrete subclass of DominatorTreeBase that is used to compute a normal dominator tree.
Definition: A block is said to be forward statically reachable if there is a path from the entry of the function to the block. A statically reachable block may become statically unreachable during optimization.
A forward unreachable block may appear in the dominator tree, or it may not. If it does, dominance queries will return results as if all reachable blocks dominate it. When asking for a Node corresponding to a potentially unreachable block, calling code must handle the case where the block was unreachable and the result of getNode() is nullptr.
Generally, a block known to be unreachable when the dominator tree is constructed will not be in the tree. One which becomes unreachable after the dominator tree is initially constructed may still exist in the tree, even if the tree is properly updated. Calling code should not rely on the preceding statements; this is stated only to assist human understanding.
Definition at line 166 of file Dominators.h.
Member Typedef Documentation
Base
using llvm::DominatorTree::Base = DominatorTreeBase<BasicBlock, false>
Definition at line 168 of file Dominators.h.
Constructor & Destructor Documentation
DominatorTree() [1/3]
llvm::DominatorTree::DominatorTree () default
DominatorTree() [2/3]
llvm::DominatorTree::DominatorTree (Function & F) inline explicit
Definition at line 171 of file Dominators.h.
References F.
DominatorTree() [3/3]
llvm::DominatorTree::DominatorTree (DominatorTree & DT, DomTreeBuilder::BBUpdates U) inline explicit
Definition at line 172 of file Dominators.h.
References llvm::DominatorTreeBase< NodeT, IsPostDom >::Parent.
Member Function Documentation
dominates() [1/7]
bool DominatorTree::dominates (const BasicBlock * BB, const Use & U) const
Return true if the (end of the) basic block BB dominates the use U.
Definition at line 122 of file Dominators.cpp.
References dominates(), llvm::Instruction::getParent(), and llvm::DominatorTreeBase< BasicBlock, false >::properlyDominates().
Referenced by llvm::LoopSafetyInfo::allLoopPathsLeadToBlock(), llvm::ScalarEvolution::applyLoopGuards(), llvm::LoopAccessInfo::blockNeedsPredication(), BrPHIToSelect(), CalculateUnswitchCostMultiplier(), canProveExitOnFirstIteration(), checkBasicSSA(), checkHoistValue(), CompareSCEVComplexity(), containsUnconditionalCallSafepoint(), doesStoreDominatesAllLatches(), dominates(), dominates(), dominates(), dominates(), dominates(), llvm::MemorySSA::dominates(), llvm::MemorySSA::dominates(), dominates(), dominates(), llvm::InstCombinerImpl::dominatesAllUses(), llvm::EpilogueVectorizerEpilogueLoop::emitMinimumVectorEpilogueIterCountCheck(), findBasePointers(), findBBsToSinkInto(), findBestNonTrivialUnswitchCandidate(), findCallsAtConstantOffset(), llvm::InnerLoopVectorizer::fixCrossIterationPHIs(), foldConsecutiveLoads(), llvm::InstCombinerImpl::foldFreezeIntoRecurrence(), foldGuardedFunnelShift(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), llvm::formLCSSAForInstructions(), llvm::InstCombinerImpl::freezeOtherUses(), generateReproducer(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), getFreezeInsertPt(), getInsertPointForUses(), getInvariantGroupClobberingInstruction(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), llvm::SCEVExpander::getIVIncOperand(), getMinAnalyzeableBackedgeTakenCount(), getReductionInstr(), llvm::SCEVExpander::getRelatedExistingExpansion(), llvm::InstCombinerImpl::handlePotentiallyDeadSuccessors(), llvm::SCEVExpander::hoistIVInc(), llvm::hoistRegion(), hoistValue(), insertParsePoints(), insertSpills(), llvm::ScalarEvolution::instructionCouldExistWitthOperands(), IsAcceptableTarget(), IsBackEdge(), llvm::ScalarEvolution::isBasicBlockEntryGuardedByCond(), llvm::isControlFlowEquivalent(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), isFullDominator(), llvm::HardwareLoopInfo::isHardwareLoopCandidate(), isKnownNonNullFromDominatingCondition(), llvm::ScalarEvolution::isKnownViaInduction(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), llvm::isOverflowIntrinsicNoWrap(), llvm::isPotentiallyReachableFromMany(), llvm::isReachedBefore(), llvm::isSafeToMoveBefore(), llvm::isValidAssumeForContext(), IVUseShouldUsePostIncValue(), liesBetween(), llvm::mustExecuteUBIfPoisonOnPathTo(), nearest_common_dominatee(), optimizeDivRem(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), partitionLoopBlocks(), peelToTurnInvariantLoadsDerefencebale(), PickMostRelevantLoop(), PrintDebugDomInfo(), llvm::promoteLoopAccessesToScalars(), llvm::replaceDominatedUsesWith(), llvm::replaceDominatedUsesWith(), reportMayClobberedLoad(), rewriteDebugUsers(), rewriteSingleStoreAlloca(), llvm::InstCombinerImpl::run(), llvm::PlaceSafepointsPass::runImpl(), separateNestedLoop(), simplifyCommonValuePhi(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), simplifyUsingControlFlow(), SinkInstruction(), sinkLifetimeStartMarkers(), llvm::PHITransAddr::translateValue(), unswitchNontrivialInvariants(), valueDominatesPHI(), llvm::InstCombinerImpl::visitAnd(), and llvm::InstCombinerImpl::visitOr().
dominates() [2/7]
bool DominatorTree::dominates (const BasicBlockEdge & BBE, const BasicBlock * BB) const
Definition at line 200 of file Dominators.cpp.
References dominates(), End, and llvm::predecessors().
dominates() [3/7]
bool DominatorTree::dominates (const BasicBlockEdge & BBE, const Use & U) const
Return true if an edge dominates a use.
If BBE is not a unique edge between start and end of the edge, it can never dominate the use.
Definition at line 250 of file Dominators.cpp.
References dominates(), llvm::PHINode::getIncomingBlock(), and llvm::Instruction::getParent().
dominates() [4/7]
bool DominatorTree::dominates (const BasicBlockEdge & BBE1, const BasicBlockEdge & BBE2) const
Returns true if edge BBE1 dominates edge BBE2.
Definition at line 337 of file Dominators.cpp.
References dominates().
dominates() [5/7]
bool DominatorTree::dominates (const Instruction * Def, const BasicBlock * BB) const
Returns true if Def would dominate a use in any instruction in BB.
If Def is an instruction in BB, then Def does not dominate BB.
Does not accept Value to avoid ambiguity with dominance checks between two basic blocks.
Definition at line 174 of file Dominators.cpp.
References dominates(), E, and isReachableFromEntry().
dominates() [6/7]
bool DominatorTree::dominates (const Value * Def, const Instruction * User) const
Return true if value Def dominates all possible uses inside instruction User.
Same comments as for the Use-based API apply.
Definition at line 135 of file Dominators.cpp.
References assert(), dominates(), and isReachableFromEntry().
dominates() [7/7]
bool DominatorTree::dominates (const Value * Def, const Use & U) const
Return true if value Def dominates use U, in the sense that Def is available at U, and could be substituted as the used value without violating the SSA dominance requirement.
In particular, it is worth noting that:
Non-instruction Defs dominate everything.
Def does not dominate a use in Def itself (outside of degenerate cases like unreachable code or trivial phi cycles).
Invoke Defs only dominate uses in their default destination.
Definition at line 268 of file Dominators.cpp.
References assert(), dominates(), E, llvm::Instruction::getParent(), and isReachableFromEntry().
findNearestCommonDominator()
Instruction * DominatorTree::findNearestCommonDominator (Instruction * I1, Instruction * I2) const
Find the nearest instruction I that dominates both I1 and I2, in the sense that a result produced before I will be available at both I1 and I2.
Definition at line 344 of file Dominators.cpp.
References findNearestCommonDominator(), and isReachableFromEntry().
Referenced by Prefetch::addInstruction(), ConnectEpilog(), ConnectProlog(), findCommonDominator(), findNearestCommonDominator(), getInsertPointForUses(), llvm::isControlFlowEquivalent(), nearest_common_dominator(), llvm::nonStrictlyPostDominate(), llvm::peelLoop(), runMoveAutoInit(), SinkInstruction(), llvm::UnrollLoop(), and usersDominator().
invalidate()
bool DominatorTree::invalidate (Function & F, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator &)
Handle invalidation explicitly.
Definition at line 113 of file Dominators.cpp.
References llvm::PreservedAnalyses::getChecker().
isReachableFromEntry()
bool DominatorTree::isReachableFromEntry (const Use & U) const
Provide an overload for a Use.
Definition at line 321 of file Dominators.cpp.
References I, and isReachableFromEntry().
Referenced by buildExtractionBlockSet(), llvm::PredicateInfoBuilder::buildPredicateInfo(), checkClobberSanity(), collectUnswitchCandidatesWithInjections(), deleteDeadBlocksFromLoop(), deleteDeadClonedBlocks(), llvm::deleteDeadLoop(), dominates(), dominates(), dominates(), findBestInsertionSet(), findNearestCommonDominator(), llvm::InstCombinerImpl::foldBinopWithPhiOperands(), llvm::InstCombinerImpl::foldOpIntoPhi(), foldUnusualPatterns(), llvm::formLCSSAForInstructions(), llvm::FunctionPropertiesInfo::getFunctionPropertiesInfo(), getInsertPointForUses(), llvm::MemorySSAUpdater::insertDef(), insertParsePoints(), llvm::ScalarEvolution::isBasicBlockEntryGuardedByCond(), isBlockInLCSSAForm(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), llvm::isPotentiallyReachable(), llvm::isPotentiallyReachableFromMany(), isReachableFromEntry(), makeReducible(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), ProcessBlock(), llvm::InstCombinerImpl::run(), llvm::TruncInstCombine::run(), runImpl(), llvm::JumpThreadingPass::runImpl(), llvm::RewriteStatepointsForGC::runOnFunction(), simplifyLoopInst(), simplifyUsingControlFlow(), sink(), SinkInstruction(), llvm::PHITransAddr::translateValue(), and UpdateAnalysisInformation().
viewGraph() [1/2]
void DominatorTree::viewGraph ()
Definition at line 36 of file DomPrinter.cpp.
References llvm::errs(), and viewGraph().
Referenced by viewGraph().
viewGraph() [2/2]
void DominatorTree::viewGraph (const Twine & Name, const Twine & Title)
Definition at line 28 of file DomPrinter.cpp.
References llvm::errs(), Name, and llvm::ViewGraph().
The documentation for this class was generated from the following files:
include/llvm/IR/Dominators.h
lib/Analysis/DomPrinter.cpp
lib/IR/Dominators.cpp