LLVM: llvm::objcopy::elf::SectionWriter Class Reference
llvm::objcopy::elf::SectionWriter Class Reference abstract
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
virtual ~SectionWriter ()=default
Error visit (const Section &Sec) override
Error visit (const OwnedDataSection &Sec) override
Error visit (const StringTableSection &Sec) override
Error visit (const DynamicRelocationSection &Sec) override
Error visit (const SymbolTableSection &Sec) override=0
Error visit (const RelocationSection &Sec) override=0
Error visit (const GnuDebugLinkSection &Sec) override=0
Error visit (const GroupSection &Sec) override=0
Error visit (const SectionIndexSection &Sec) override=0
Error visit (const CompressedSection &Sec) override=0
Error visit (const DecompressedSection &Sec) override=0
SectionWriter (WritableMemoryBuffer &Buf)
Public Member Functions inherited from llvm::objcopy::elf::SectionVisitor
virtual ~SectionVisitor ()=default
Protected Attributes
WritableMemoryBuffer & Out
Detailed Description
Definition at line 107 of file ELFObject.h.
Constructor & Destructor Documentation
~SectionWriter()
virtual llvm::objcopy::elf::SectionWriter::~SectionWriter () virtual default
SectionWriter()
llvm::objcopy::elf::SectionWriter::SectionWriter (WritableMemoryBuffer & Buf) inline explicit
Definition at line 126 of file ELFObject.h.
Member Function Documentation
visit() [1/11]
Error llvm::objcopy::elf::SectionWriter::visit (const CompressedSection & Sec) override pure virtual
Implements llvm::objcopy::elf::SectionVisitor.
Implemented in llvm::objcopy::elf::ELFSectionWriter< ELFT >, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::IHexSectionWriterBase.
visit() [2/11]
Error llvm::objcopy::elf::SectionWriter::visit (const DecompressedSection & Sec) override pure virtual
Implements llvm::objcopy::elf::SectionVisitor.
Implemented in llvm::objcopy::elf::ELFSectionWriter< ELFT >, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::IHexSectionWriterBase.
visit() [3/11]
Error SectionWriter::visit (const DynamicRelocationSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionVisitor.
Definition at line 1008 of file ELFObject.cpp.
References llvm::copy(), llvm::WritableMemoryBuffer::getBufferStart(), llvm::objcopy::elf::SectionBase::Offset, Out, and llvm::Error::success().
visit() [4/11]
Error llvm::objcopy::elf::SectionWriter::visit (const GnuDebugLinkSection & Sec) override pure virtual
Implements llvm::objcopy::elf::SectionVisitor.
Implemented in llvm::objcopy::elf::ELFSectionWriter< ELFT >, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::IHexSectionWriterBase.
visit() [5/11]
Error llvm::objcopy::elf::SectionWriter::visit (const GroupSection & Sec) override pure virtual
Implements llvm::objcopy::elf::SectionVisitor.
Implemented in llvm::objcopy::elf::ELFSectionWriter< ELFT >, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::IHexSectionWriterBase.
visit() [6/11]
Error SectionWriter::visit (const OwnedDataSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionVisitor.
Definition at line 439 of file ELFObject.cpp.
References llvm::copy(), llvm::objcopy::elf::SectionBase::Offset, and llvm::Error::success().
visit() [7/11]
Error llvm::objcopy::elf::SectionWriter::visit (const RelocationSection & Sec) override pure virtual
Implements llvm::objcopy::elf::SectionVisitor.
Implemented in llvm::objcopy::elf::ELFSectionWriter< ELFT >, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::IHexSectionWriterBase.
visit() [8/11]
Error SectionWriter::visit (const Section & Sec) override virtual
Implements llvm::objcopy::elf::SectionVisitor.
Definition at line 170 of file ELFObject.cpp.
References llvm::copy(), llvm::objcopy::elf::SectionBase::Offset, llvm::ELF::SHT_NOBITS, llvm::Error::success(), and llvm::objcopy::elf::SectionBase::Type.
visit() [9/11]
Error llvm::objcopy::elf::SectionWriter::visit (const SectionIndexSection & Sec) override pure virtual
Implements llvm::objcopy::elf::SectionVisitor.
Implemented in llvm::objcopy::elf::ELFSectionWriter< ELFT >, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::IHexSectionWriterBase.
visit() [10/11]
Error SectionWriter::visit (const StringTableSection & Sec) override virtual
Implements llvm::objcopy::elf::SectionVisitor.
Definition at line 583 of file ELFObject.cpp.
References llvm::WritableMemoryBuffer::getBufferStart(), llvm::objcopy::elf::SectionBase::Offset, Out, llvm::Error::success(), and llvm::StringTableBuilder::write().
visit() [11/11]
Error llvm::objcopy::elf::SectionWriter::visit (const SymbolTableSection & Sec) override pure virtual
Implements llvm::objcopy::elf::SectionVisitor.
Implemented in llvm::objcopy::elf::ELFSectionWriter< ELFT >, llvm::objcopy::elf::BinarySectionWriter, and llvm::objcopy::elf::IHexSectionWriterBase.
Member Data Documentation
Out
WritableMemoryBuffer& llvm::objcopy::elf::SectionWriter::Out protected
Definition at line 109 of file ELFObject.h.
Referenced by visit(), and visit().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp