LLVM: llvm::MemDerefPrinterPass Class Reference
llvm::MemDerefPrinterPass Class Reference
#include "llvm/Analysis/MemDerefPrinter.h"
Public Member Functions
MemDerefPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< MemDerefPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< MemDerefPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 15 of file MemDerefPrinter.h.
Constructor & Destructor Documentation
MemDerefPrinterPass()
llvm::MemDerefPrinterPass::MemDerefPrinterPass (raw_ostream & OS) inline
Definition at line 19 of file MemDerefPrinter.h.
References OS.
Member Function Documentation
run()
PreservedAnalyses MemDerefPrinterPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 21 of file MemDerefPrinter.cpp.
References llvm::PreservedAnalyses::all(), DL, F, llvm::MachineFunction::getDataLayout(), llvm::MachineBasicBlock::getParent(), I, instructions, llvm::isDereferenceableAndAlignedPointer(), and llvm::isDereferenceablePointer().
The documentation for this class was generated from the following files:
include/llvm/Analysis/MemDerefPrinter.h
lib/Analysis/MemDerefPrinter.cpp