LLVM: llvm::PseudoProbeVerifier Class Reference
llvm::PseudoProbeVerifier Class Reference
#include "llvm/Transforms/IPO/SampleProfileProbe.h"
Public Member Functions
void registerCallbacks (PassInstrumentationCallbacks &PIC)
void runAfterPass (StringRef PassID, Any IR)
Detailed Description
Definition at line 48 of file SampleProfileProbe.h.
Member Function Documentation
registerCallbacks()
void PseudoProbeVerifier::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 84 of file SampleProfileProbe.cpp.
References IR, P, PIC, llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), runAfterPass(), and VerifyPseudoProbe.
Referenced by llvm::StandardInstrumentations::registerCallbacks().
runAfterPass()
void PseudoProbeVerifier::runAfterPass (StringRef PassID, Any IR)
Definition at line 94 of file SampleProfileProbe.cpp.
References llvm::CallingConv::C, llvm::dbgs(), F, IR, llvm_unreachable, runAfterPass(), and llvm::StringRef::str().
Referenced by registerCallbacks(), and runAfterPass().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/SampleProfileProbe.h
lib/Transforms/IPO/SampleProfileProbe.cpp