LLVM: llvm::objcopy::elf::SymbolTableSection Class Reference
llvm::objcopy::elf::SymbolTableSection Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
SymbolTableSection ()
void addSymbol (Twine Name, uint8_t Bind, uint8_t Type, SectionBase *DefinedIn, uint64_t Value, uint8_t Visibility, uint16_t Shndx, uint64_t SymbolSize)
void prepareForLayout ()
bool empty () const
bool indicesChanged () const
void setShndxTable (SectionIndexSection *ShndxTable)
const SectionIndexSection * getShndxTable () const
void fillShndxTable ()
const SectionBase * getStrTab () const
Expected< const Symbol * > getSymbolByIndex (uint32_t Index) const
Expected< Symbol * > getSymbolByIndex (uint32_t Index)
void updateSymbols (function_ref< void(Symbol &)> Callable)
Error removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove) override
Error initialize (SectionTableRef SecTable) override
void finalize () override
Error accept (SectionVisitor &Visitor) const override
Error accept (MutableSectionVisitor &Visitor) override
Error removeSymbols (function_ref< bool(const Symbol &)> ToRemove) override
void replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > &FromTo) override
Public Member Functions inherited from llvm::objcopy::elf::SectionBase
SectionBase ()=default
SectionBase (const SectionBase &)=default
virtual ~SectionBase ()=default
virtual void markSymbols ()
virtual bool hasContents () const
virtual void onRemove ()
virtual void restoreSymTabLink (SymbolTableSection &)
Static Public Member Functions
static bool classof (const SectionBase *S)
Protected Types
using SymPtr = std::unique_ptr<Symbol>
Protected Attributes
std::vector< std::unique_ptr< Symbol > > Symbols
StringTableSection * SymbolNames = nullptr
SectionIndexSection * SectionIndexTable = nullptr
bool IndicesChanged = false
Additional Inherited Members
Public Attributes inherited from llvm::objcopy::elf::SectionBase
std::string Name
Segment * ParentSegment = nullptr
uint64_t HeaderOffset = 0
uint32_t Index = 0
uint32_t OriginalIndex = 0
uint64_t OriginalFlags = 0
uint64_t OriginalType = ELF::SHT_NULL
uint64_t OriginalOffset = std::numeric_limits<uint64_t>::max()
uint64_t Addr = 0
uint64_t Align = 1
uint32_t EntrySize = 0
uint64_t Flags = 0
uint64_t Info = 0
uint64_t Link = ELF::SHN_UNDEF
uint64_t NameIndex = 0
uint64_t Offset = 0
uint64_t Size = 0
uint64_t Type = ELF::SHT_NULL
ArrayRef< uint8_t > OriginalData
bool HasSymbol = false
Detailed Description
Definition at line 688 of file ELFObject.h.
Member Typedef Documentation
SymPtr
using llvm::objcopy::elf::SymbolTableSection::SymPtr = std::unique_ptr<Symbol> protected
Definition at line 700 of file ELFObject.h.
Constructor & Destructor Documentation
SymbolTableSection()
llvm::objcopy::elf::SymbolTableSection::SymbolTableSection () inline
Definition at line 703 of file ELFObject.h.
References llvm::objcopy::elf::SectionBase::OriginalType, and llvm::ELF::SHT_SYMTAB.
Member Function Documentation
accept() [1/2]
Error SymbolTableSection::accept (MutableSectionVisitor & Visitor) override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 865 of file ELFObject.cpp.
References llvm::objcopy::elf::MutableSectionVisitor::visit().
accept() [2/2]
Error SymbolTableSection::accept (SectionVisitor & Visitor) const override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 861 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionVisitor::visit().
addSymbol()
void SymbolTableSection::addSymbol (Twine Name, uint8_t Bind, uint8_t Type, SectionBase * DefinedIn, uint64_t Value, uint8_t Visibility, uint16_t Shndx, uint64_t SymbolSize)
Definition at line 697 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::EntrySize, llvm::objcopy::elf::SectionBase::HasSymbol, llvm::objcopy::elf::SectionBase::Name, llvm::ELF::SHN_LORESERVE, llvm::objcopy::elf::SectionBase::Size, Sym, llvm::objcopy::elf::SYMBOL_SIMPLE_INDEX, Symbols, and llvm::objcopy::elf::SectionBase::Type.
Referenced by llvm::objcopy::elf::Object::addNewSymbolTable(), and addSymbol().
classof()
static bool llvm::objcopy::elf::SymbolTableSection::classof (const SectionBase * S) inline static
Definition at line 733 of file ELFObject.h.
References llvm::objcopy::elf::SectionBase::OriginalType, and llvm::ELF::SHT_SYMTAB.
empty()
bool llvm::objcopy::elf::SymbolTableSection::empty () const inline
Definition at line 710 of file ELFObject.h.
References Symbols.
Referenced by handleArgs(), removeUnneededSections(), and replaceAndRemoveSections().
fillShndxTable()
void SymbolTableSection::fillShndxTable ()
Definition at line 814 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionIndexSection::addIndex(), SectionIndexTable, llvm::ELF::SHN_LORESERVE, llvm::ELF::SHN_UNDEF, Sym, and Symbols.
finalize()
void SymbolTableSection::finalize () override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 785 of file ELFObject.cpp.
References llvm::objcopy::elf::StringTableSection::findIndex(), llvm::objcopy::elf::SectionBase::Index, llvm::objcopy::elf::SectionBase::Link, llvm::ELF::STB_LOCAL, Sym, SymbolNames, and Symbols.
getShndxTable()
const SectionIndexSection * llvm::objcopy::elf::SymbolTableSection::getShndxTable () const inline
Definition at line 715 of file ELFObject.h.
References SectionIndexTable.
getStrTab()
const SectionBase * llvm::objcopy::elf::SymbolTableSection::getStrTab () const inline
Definition at line 717 of file ELFObject.h.
References SymbolNames.
Referenced by removeUnneededSections(), and replaceAndRemoveSections().
getSymbolByIndex() [1/2]
Expected< Symbol * > SymbolTableSection::getSymbolByIndex (uint32_t Index)
Definition at line 835 of file ELFObject.cpp.
References getSymbolByIndex(), and Sym.
getSymbolByIndex() [2/2]
Expected< const Symbol * > SymbolTableSection::getSymbolByIndex (uint32_t Index) const
Definition at line 828 of file ELFObject.cpp.
References llvm::createStringError(), llvm::objcopy::elf::SectionBase::Index, llvm::invalid_argument, and Symbols.
Referenced by getSymbolByIndex(), and initRelocations().
indicesChanged()
bool llvm::objcopy::elf::SymbolTableSection::indicesChanged () const inline
Definition at line 711 of file ELFObject.h.
References IndicesChanged.
initialize()
Error SymbolTableSection::initialize (SectionTableRef SecTable) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 769 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::Link, and llvm::objcopy::elf::SectionBase::Size.
Referenced by llvm::objcopy::elf::Object::addNewSymbolTable().
prepareForLayout()
void SymbolTableSection::prepareForLayout ()
Definition at line 798 of file ELFObject.cpp.
References llvm::objcopy::elf::StringTableSection::addString(), llvm::objcopy::elf::SectionIndexSection::reserve(), SectionIndexTable, Sym, SymbolNames, and Symbols.
removeSectionReferences()
Error SymbolTableSection::removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 722 of file ELFObject.cpp.
References llvm::createStringError(), llvm::invalid_argument, llvm::objcopy::elf::SectionBase::Name, removeSymbols(), SectionIndexTable, Sym, SymbolNames, and ToRemove.
removeSymbols()
Error SymbolTableSection::removeSymbols (function_ref< bool(const Symbol &)> ToRemove) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 748 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::EntrySize, IndicesChanged, llvm::objcopy::elf::SectionBase::Size, llvm::Error::success(), Sym, Symbols, and ToRemove.
Referenced by removeSectionReferences().
replaceSectionReferences()
void SymbolTableSection::replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > & FromTo) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 762 of file ELFObject.cpp.
References Sym, and Symbols.
setShndxTable()
void llvm::objcopy::elf::SymbolTableSection::setShndxTable (SectionIndexSection * ShndxTable) inline
Definition at line 712 of file ELFObject.h.
References SectionIndexTable.
Referenced by llvm::objcopy::elf::SectionIndexSection::initialize().
updateSymbols()
void SymbolTableSection::updateSymbols (function_ref< void(Symbol &)> Callable)
Definition at line 739 of file ELFObject.cpp.
References llvm::drop_begin(), llvm::ELF::STB_LOCAL, Sym, and Symbols.
Referenced by updateAndRemoveSymbols().
Member Data Documentation
IndicesChanged
bool llvm::objcopy::elf::SymbolTableSection::IndicesChanged = false protected
Definition at line 698 of file ELFObject.h.
Referenced by indicesChanged(), and removeSymbols().
SectionIndexTable
SectionIndexSection* llvm::objcopy::elf::SymbolTableSection::SectionIndexTable = nullptr protected
Definition at line 697 of file ELFObject.h.
Referenced by fillShndxTable(), getShndxTable(), prepareForLayout(), removeSectionReferences(), and setShndxTable().
SymbolNames
StringTableSection* llvm::objcopy::elf::SymbolTableSection::SymbolNames = nullptr protected
Definition at line 696 of file ELFObject.h.
Referenced by finalize(), getStrTab(), prepareForLayout(), and removeSectionReferences().
Symbols
std::vector<std::unique_ptr<Symbol> > llvm::objcopy::elf::SymbolTableSection::Symbols protected
Definition at line 695 of file ELFObject.h.
Referenced by addSymbol(), empty(), fillShndxTable(), finalize(), getSymbolByIndex(), prepareForLayout(), removeSymbols(), replaceSectionReferences(), updateSymbols(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), and llvm::objcopy::elf::ELFSectionSizer< ELFT >::visit().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp