LLVM: llvm::mca::RISCVInstrumentManager Class Reference
llvm::mca::RISCVInstrumentManager Class Reference
#include "Target/RISCV/MCA/RISCVCustomBehaviour.h"
Public Member Functions
RISCVInstrumentManager (const MCSubtargetInfo &STI, const MCInstrInfo &MCII)
bool shouldIgnoreInstruments () const override
Returns true if llvm-mca should ignore instruments.
bool supportsInstrumentType (StringRef Type) const override
UniqueInstrument createInstrument (StringRef Desc, StringRef Data) override
Create a Instrument for RISC-V target.
SmallVector< UniqueInstrument > createInstruments (const MCInst &Inst) override
Return a list of unique pointers to Instruments, where each Instrument is allocated by this function.
unsigned getSchedClassID (const MCInstrInfo &MCII, const MCInst &MCI, const SmallVector< Instrument * > &IVec) const override
Using the Instrument, returns a SchedClassID to use instead of the SchedClassID that belongs to the MCI or the original SchedClassID.
Public Member Functions inherited from llvm::mca::InstrumentManager
InstrumentManager (const MCSubtargetInfo &STI, const MCInstrInfo &MCII)
virtual ~InstrumentManager ()=default
Additional Inherited Members
Protected Attributes inherited from llvm::mca::InstrumentManager
const MCSubtargetInfo & STI
const MCInstrInfo & MCII
Detailed Description
Definition at line 53 of file RISCVCustomBehaviour.h.
Constructor & Destructor Documentation
RISCVInstrumentManager()
llvm::mca::RISCVInstrumentManager::RISCVInstrumentManager (const MCSubtargetInfo & STI, const MCInstrInfo & MCII) inline
Definition at line 55 of file RISCVCustomBehaviour.h.
Member Function Documentation
createInstrument()
UniqueInstrument llvm::mca::RISCVInstrumentManager::createInstrument (llvm::StringRef Desc, llvm::StringRef Data) override virtual
Create a Instrument for RISC-V target.
Reimplemented from llvm::mca::InstrumentManager.
Definition at line 100 of file RISCVCustomBehaviour.cpp.
References llvm::Data, llvm::dbgs(), llvm::mca::RISCVLMULInstrument::DESC_NAME, llvm::mca::RISCVSEWInstrument::DESC_NAME, llvm::mca::RISCVLMULInstrument::isDataValid(), llvm::mca::RISCVSEWInstrument::isDataValid(), and LLVM_DEBUG.
Referenced by createInstruments().
createInstruments()
SmallVector< UniqueInstrument > llvm::mca::RISCVInstrumentManager::createInstruments (const MCInst & Inst) override virtual
Return a list of unique pointers to Instruments, where each Instrument is allocated by this function.
See createInstrument to create Instrument from a description and data.
Reimplemented from llvm::mca::InstrumentManager.
Definition at line 125 of file RISCVCustomBehaviour.cpp.
References createInstrument(), llvm::dbgs(), llvm::mca::RISCVLMULInstrument::DESC_NAME, llvm::mca::RISCVSEWInstrument::DESC_NAME, llvm::MCOperand::getImm(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::RISCVVType::getSEW(), llvm::RISCVVType::getVLMUL(), LLVM_DEBUG, llvm_unreachable, llvm::RISCVII::LMUL_1, llvm::RISCVII::LMUL_2, llvm::RISCVII::LMUL_4, llvm::RISCVII::LMUL_8, llvm::RISCVII::LMUL_F2, llvm::RISCVII::LMUL_F4, llvm::RISCVII::LMUL_F8, llvm::RISCVII::LMUL_RESERVED, and SEW.
getSchedClassID()
unsigned llvm::mca::RISCVInstrumentManager::getSchedClassID (const MCInstrInfo & MCII, const MCInst & MCI, const SmallVector< Instrument * > & IVec) const override virtual
Using the Instrument, returns a SchedClassID to use instead of the SchedClassID that belongs to the MCI or the original SchedClassID.
Reimplemented from llvm::mca::InstrumentManager.
Definition at line 189 of file RISCVCustomBehaviour.cpp.
References llvm::dbgs(), llvm::mca::RISCVLMULInstrument::DESC_NAME, llvm::mca::RISCVSEWInstrument::DESC_NAME, llvm::MCInstrInfo::get(), llvm::mca::Instrument::getData(), llvm::mca::RISCVLMULInstrument::getLMUL(), llvm::MCInstrInfo::getName(), llvm::MCInstrDesc::getSchedClass(), I, LLVM_DEBUG, llvm::mca::InstrumentManager::MCII, and SEW.
shouldIgnoreInstruments()
bool llvm::mca::RISCVInstrumentManager::shouldIgnoreInstruments () const inline override virtual
Returns true if llvm-mca should ignore instruments.
Reimplemented from llvm::mca::InstrumentManager.
Definition at line 58 of file RISCVCustomBehaviour.h.
supportsInstrumentType()
bool llvm::mca::RISCVInstrumentManager::supportsInstrumentType (llvm::StringRef Type) const override virtual
Reimplemented from llvm::mca::InstrumentManager.
Definition at line 93 of file RISCVCustomBehaviour.cpp.
References llvm::mca::RISCVLMULInstrument::DESC_NAME, and llvm::mca::RISCVSEWInstrument::DESC_NAME.
The documentation for this class was generated from the following files:
lib/Target/RISCV/MCA/RISCVCustomBehaviour.h
lib/Target/RISCV/MCA/RISCVCustomBehaviour.cpp