LLVM: llvm::sampleprof::ProfileConverter Class Reference
llvm::sampleprof::ProfileConverter Class Reference
Helper class for profile conversion.
#include "llvm/ProfileData/SampleProf.h"
Classes
struct FrameNode
Public Member Functions
ProfileConverter (SampleProfileMap &Profiles)
void convertCSProfiles ()
Static Public Member Functions
static void flattenProfile (SampleProfileMap &ProfileMap, bool ProfileIsCS=false)
static void flattenProfile (const SampleProfileMap &InputProfiles, SampleProfileMap &OutputProfiles, bool ProfileIsCS=false)
Detailed Description
Helper class for profile conversion.
It supports full context-sensitive profile to nested profile conversion, nested profile to flatten profile conversion, etc.
Definition at line 1334 of file SampleProf.h.
Constructor & Destructor Documentation
ProfileConverter()
ProfileConverter::ProfileConverter (SampleProfileMap & Profiles)
Definition at line 479 of file SampleProf.cpp.
References assert().
Member Function Documentation
convertCSProfiles()
void ProfileConverter::convertCSProfiles ()
Definition at line 547 of file SampleProf.cpp.
References convertCSProfiles().
Referenced by convertCSProfiles().
flattenProfile() [1/2]
static void llvm::sampleprof::ProfileConverter::flattenProfile (const SampleProfileMap & InputProfiles, SampleProfileMap & OutputProfiles, bool ProfileIsCS = false) inline static
Definition at line 1366 of file SampleProf.h.
References I.
flattenProfile() [2/2]
static void llvm::sampleprof::ProfileConverter::flattenProfile (SampleProfileMap & ProfileMap, bool ProfileIsCS = false) inline static
Definition at line 1359 of file SampleProf.h.
References flattenProfile().
Referenced by flattenProfile().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProf.h
lib/ProfileData/SampleProf.cpp