LLVM: llvm::dwarflinker_parallel::StringTable Class Reference
llvm::dwarflinker_parallel::StringTable Class Reference
This class prepares strings for emission into .debug_str table: translates string if necessary, assigns index and offset, keeps in order.
#include "llvm/DWARFLinkerParallel/StringTable.h"
Public Member Functions
StringTable (StringPool &Strings, std::function< StringRef(StringRef)> StringsTranslator)
~StringTable ()
StringEntry * add (StringEntry *String)
Add string to the vector of strings which should be emitted.
void clear ()
Erase contents of StringsForEmission.
void forEach (function_ref< void(DwarfStringPoolEntryRef)> Handler) const
Enumerate all strings in sequential order and call Handler for each string.
std::function< StringRef(StringRef)> getTranslator ()
Protected Attributes
StringsVector StringEntriesForEmission
List of strings for emission.
StringPool & Strings
String pool for the translated strings.
std::function< StringRef(StringRef)> StringsTranslator
Translator for the strings.
Detailed Description
This class prepares strings for emission into .debug_str table: translates string if necessary, assigns index and offset, keeps in order.
Definition at line 22 of file StringTable.h.
Constructor & Destructor Documentation
StringTable()
llvm::dwarflinker_parallel::StringTable::StringTable (StringPool & Strings, std::function< StringRef(StringRef)> StringsTranslator) inline
Definition at line 24 of file StringTable.h.
~StringTable()
llvm::dwarflinker_parallel::StringTable::~StringTable () inline
Definition at line 27 of file StringTable.h.
Member Function Documentation
add()
StringEntry * llvm::dwarflinker_parallel::StringTable::add (StringEntry * String) inline
Add string to the vector of strings which should be emitted.
Translate input string if neccessary, assign index and offset.
Returns
updated string entry.
Definition at line 32 of file StringTable.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase< Size_T >::empty(), llvm::dwarflinker_parallel::StringPool::getAllocatorRef(), llvm::ConcurrentHashTableByPtr< KeyTy, KeyDataTy, AllocatorTy, Info >::insert(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase< Size_T >::size(), llvm::String, StringEntriesForEmission, Strings, and StringsTranslator.
clear()
void llvm::dwarflinker_parallel::StringTable::clear () inline
Erase contents of StringsForEmission.
Definition at line 61 of file StringTable.h.
References llvm::SmallVectorImpl< T >::clear(), and StringEntriesForEmission.
forEach()
void llvm::dwarflinker_parallel::StringTable::forEach (function_ref< void(DwarfStringPoolEntryRef)> Handler) const inline
Enumerate all strings in sequential order and call Handler for each string.
Definition at line 65 of file StringTable.h.
References StringEntriesForEmission.
getTranslator()
std::function< StringRef(StringRef)> llvm::dwarflinker_parallel::StringTable::getTranslator () inline
Definition at line 70 of file StringTable.h.
References StringsTranslator.
Referenced by llvm::dwarflinker_parallel::DWARFLinkerImpl::createEmitter().
Member Data Documentation
StringEntriesForEmission
StringsVector llvm::dwarflinker_parallel::StringTable::StringEntriesForEmission protected
List of strings for emission.
Definition at line 76 of file StringTable.h.
Referenced by add(), clear(), and forEach().
Strings
StringPool& llvm::dwarflinker_parallel::StringTable::Strings protected
String pool for the translated strings.
Definition at line 79 of file StringTable.h.
Referenced by add().
StringsTranslator
std::function<StringRef(StringRef)> llvm::dwarflinker_parallel::StringTable::StringsTranslator protected
Translator for the strings.
Definition at line 82 of file StringTable.h.
Referenced by add(), and getTranslator().
The documentation for this class was generated from the following file:
include/llvm/DWARFLinkerParallel/StringTable.h