LLVM: llvm::CSKYConstantPool Class Reference
llvm::CSKYConstantPool Class Reference
#include "Target/CSKY/MCTargetDesc/CSKYTargetStreamer.h"
Public Member Functions
CSKYConstantPool ()=default
const MCExpr * addEntry (MCStreamer &Streamer, const MCExpr *Value, unsigned Size, SMLoc Loc, const MCExpr *AdjustExpr)
void emitAll (MCStreamer &Streamer)
bool empty ()
void clearCache ()
Detailed Description
Definition at line 18 of file CSKYTargetStreamer.h.
Constructor & Destructor Documentation
CSKYConstantPool()
llvm::CSKYConstantPool::CSKYConstantPool () default
Member Function Documentation
addEntry()
const MCExpr * CSKYConstantPool::addEntry (MCStreamer & Streamer, const MCExpr * Value, unsigned Size, SMLoc Loc, const MCExpr * AdjustExpr)
Definition at line 42 of file CSKYTargetStreamer.cpp.
References llvm::CallingConv::C, llvm::CSKYMCExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createSub(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and Size.
clearCache()
void CSKYConstantPool::clearCache ()
Definition at line 77 of file CSKYTargetStreamer.cpp.
emitAll()
void CSKYConstantPool::emitAll (MCStreamer & Streamer)
Definition at line 23 of file CSKYTargetStreamer.cpp.
References Align, llvm::SmallVectorImpl< T >::clear(), llvm::MCStreamer::emitCodeAlignment(), llvm::MCStreamer::emitDataRegion(), llvm::MCStreamer::emitLabel(), llvm::MCStreamer::emitValue(), llvm::SmallVectorBase< Size_T >::empty(), llvm::MCStreamer::getContext(), llvm::MCContext::getSubtargetInfo(), llvm::MCDR_DataRegion, llvm::MCDR_DataRegionEnd, and llvm::MCStreamer::switchSection().
empty()
bool CSKYConstantPool::empty ()
Definition at line 75 of file CSKYTargetStreamer.cpp.
References llvm::SmallVectorBase< Size_T >::empty().
The documentation for this class was generated from the following files:
lib/Target/CSKY/MCTargetDesc/CSKYTargetStreamer.h
lib/Target/CSKY/MCTargetDesc/CSKYTargetStreamer.cpp