LLVM: llvm::FunctionSpecializer Class Reference
llvm::FunctionSpecializer Class Reference
#include "llvm/Transforms/IPO/FunctionSpecialization.h"
Public Member Functions
FunctionSpecializer (SCCPSolver &Solver, Module &M, FunctionAnalysisManager *FAM, std::function< BlockFrequencyInfo &(Function &)> GetBFI, std::function< const TargetLibraryInfo &(Function &)> GetTLI, std::function< TargetTransformInfo &(Function &)> GetTTI, std::function< AssumptionCache &(Function &)> GetAC)
~FunctionSpecializer ()
bool run ()
Attempt to specialize functions in the module to enable constant propagation across function boundaries.
InstCostVisitor getInstCostVisitorFor (Function *F)
Cost getSpecializationBonus (Argument *A, Constant *C, InstCostVisitor &Visitor)
Compute a bonus for replacing argument A with constant C.
Detailed Description
Definition at line 157 of file FunctionSpecialization.h.
Constructor & Destructor Documentation
FunctionSpecializer()
llvm::FunctionSpecializer::FunctionSpecializer (SCCPSolver & Solver, Module & M, FunctionAnalysisManager * FAM, std::function< BlockFrequencyInfo &(Function &)> GetBFI, std::function< const TargetLibraryInfo &(Function &)> GetTLI, std::function< TargetTransformInfo &(Function &)> GetTTI, std::function< AssumptionCache &(Function &)> GetAC) inline
Definition at line 178 of file FunctionSpecialization.h.
References FAM.
~FunctionSpecializer()
FunctionSpecializer::~FunctionSpecializer ()
Definition at line 462 of file FunctionSpecialization.cpp.
References llvm::dbgs(), and LLVM_DEBUG.
Member Function Documentation
getInstCostVisitorFor()
InstCostVisitor llvm::FunctionSpecializer::getInstCostVisitorFor (Function * F) inline
Definition at line 191 of file FunctionSpecialization.h.
References F.
getSpecializationBonus()
Cost FunctionSpecializer::getSpecializationBonus (Argument * A, Constant * C, InstCostVisitor & Visitor)
Compute a bonus for replacing argument A with constant C.
Definition at line 793 of file FunctionSpecialization.cpp.
References A, llvm::CallingConv::C, llvm::dbgs(), llvm::InlineCost::getCostDelta(), llvm::getInlineCost(), llvm::getInlineParams(), llvm::InstCostVisitor::getUserBonus(), llvm::InlineConstants::IndirectCallThreshold, llvm::InlineCost::isAlways(), llvm::SCCPSolver::isBlockExecutable(), llvm::InlineCost::isVariable(), and LLVM_DEBUG.
run()
bool FunctionSpecializer::run ()
Attempt to specialize functions in the module to enable constant propagation across function boundaries.
Returns
true if at least one function is specialized.
Definition at line 476 of file FunctionSpecialization.cpp.
References Arg, llvm::SpecSig::Args, assert(), llvm::Spec::CallSites, llvm::Spec::Clone, llvm::CodeMetrics::collectEphemeralValues(), llvm::dbgs(), End, llvm::Spec::F, F, ForceSpecialization, llvm::Value::getName(), llvm::SCCPSolver::getTrackedRetVals(), I, llvm::SCCPSolver::isOverdefined(), llvm::SCCPSolver::isStructLatticeConstant(), LLVM_DEBUG, MaxClones, Metrics, MinFunctionSize, N, llvm::SCCPSolver::resetLatticeValueFor(), llvm::Spec::Score, llvm::Spec::Sig, llvm::SCCPSolver::solveWhileResolvedUndefs(), llvm::SCCPSolver::solveWhileResolvedUndefsIn(), and SpecializeLiteralConstant.
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/FunctionSpecialization.h
lib/Transforms/IPO/FunctionSpecialization.cpp