LLVM: llvm::orc::SelfExecutorProcessControl Class Reference
llvm::orc::SelfExecutorProcessControl Class Reference
A ExecutorProcessControl implementation targeting the current process.
#include "llvm/ExecutionEngine/Orc/ExecutorProcessControl.h"
Public Member Functions
SelfExecutorProcessControl (std::shared_ptr< SymbolStringPool > SSP, std::unique_ptr< TaskDispatcher > D, Triple TargetTriple, unsigned PageSize, std::unique_ptr< jitlink::JITLinkMemoryManager > MemMgr)
Expected< tpctypes::DylibHandle > loadDylib (const char *DylibPath) override
Load the dynamic library at the given path and return a handle to it.
Expected< std::vector< tpctypes::LookupResult > > lookupSymbols (ArrayRef< LookupRequest > Request) override
Search for symbols in the target process.
Expected< int32_t > runAsMain (ExecutorAddr MainFnAddr, ArrayRef< std::string > Args) override
Run function with a main-like signature.
Expected< int32_t > runAsVoidFunction (ExecutorAddr VoidFnAddr) override
Run function with a int (*)(void) signature.
Expected< int32_t > runAsIntFunction (ExecutorAddr IntFnAddr, int Arg) override
Run function with a int (*)(int) signature.
void callWrapperAsync (ExecutorAddr WrapperFnAddr, IncomingWFRHandler OnComplete, ArrayRef< char > ArgBuffer) override
Run a wrapper function in the executor.
Error disconnect () override
Disconnect from the target process.
Public Member Functions inherited from llvm::orc::ExecutorProcessControl
ExecutorProcessControl (std::shared_ptr< SymbolStringPool > SSP, std::unique_ptr< TaskDispatcher > D)
virtual ~ExecutorProcessControl ()
ExecutionSession & getExecutionSession ()
Return the ExecutionSession associated with this instance.
SymbolStringPtr intern (StringRef SymName)
Intern a symbol name in the SymbolStringPool.
std::shared_ptr< SymbolStringPool > getSymbolStringPool () const
Return a shared pointer to the SymbolStringPool for this instance.
TaskDispatcher & getDispatcher ()
const Triple & getTargetTriple () const
Return the Triple for the target process.
unsigned getPageSize () const
Get the page size for the target process.
const JITDispatchInfo & getJITDispatchInfo () const
Get the JIT dispatch function and context address for the executor.
MemoryAccess & getMemoryAccess () const
Return a MemoryAccess object for the target process.
jitlink::JITLinkMemoryManager & getMemMgr () const
Return a JITLinkMemoryManager for the target process.
const StringMap< std::vector< char > > & getBootstrapMap () const
Returns the bootstrap map.
template<typename T , typename SPSTagT >
Error getBootstrapMapValue (StringRef Key, std::optional< T > &Val) const
Look up and SPS-deserialize a bootstrap map value.
const StringMap< ExecutorAddr > & getBootstrapSymbolsMap () const
Returns the bootstrap symbol map.
Error getBootstrapSymbols (ArrayRef< std::pair< ExecutorAddr &, StringRef > > Pairs) const
For each (ExecutorAddr&, StringRef) pair, looks up the string in the bootstrap symbols map and writes its address to the ExecutorAddr if found.
template<typename RunPolicyT , typename FnT >
void callWrapperAsync (RunPolicyT &&Runner, ExecutorAddr WrapperFnAddr, FnT &&OnComplete, ArrayRef< char > ArgBuffer)
Run a wrapper function in the executor using the given Runner to dispatch OnComplete when the result is ready.
template<typename FnT >
void callWrapperAsync (ExecutorAddr WrapperFnAddr, FnT &&OnComplete, ArrayRef< char > ArgBuffer)
Run a wrapper function in the executor.
shared::WrapperFunctionResult callWrapper (ExecutorAddr WrapperFnAddr, ArrayRef< char > ArgBuffer)
Run a wrapper function in the executor.
template<typename SPSSignature , typename RunPolicyT , typename SendResultT , typename... ArgTs>
void callSPSWrapperAsync (RunPolicyT &&Runner, ExecutorAddr WrapperFnAddr, SendResultT &&SendResult, const ArgTs &...Args)
Run a wrapper function using SPS to serialize the arguments and deserialize the results.
template<typename SPSSignature , typename SendResultT , typename... ArgTs>
void callSPSWrapperAsync (ExecutorAddr WrapperFnAddr, SendResultT &&SendResult, const ArgTs &...Args)
Run a wrapper function using SPS to serialize the arguments and deserialize the results.
template<typename SPSSignature , typename... WrapperCallArgTs>
Error callSPSWrapper (ExecutorAddr WrapperFnAddr, WrapperCallArgTs &&...WrapperCallArgs)
Run a wrapper function using SPS to serialize the arguments and deserialize the results.
Static Public Member Functions
static Expected< std::unique_ptr< SelfExecutorProcessControl > > Create (std::shared_ptr< SymbolStringPool > SSP=nullptr, std::unique_ptr< TaskDispatcher > D=nullptr, std::unique_ptr< jitlink::JITLinkMemoryManager > MemMgr=nullptr)
Create a SelfExecutorProcessControl with the given symbol string pool and memory manager.
Additional Inherited Members
Protected Attributes inherited from llvm::orc::ExecutorProcessControl
std::shared_ptr< SymbolStringPool > SSP
std::unique_ptr< TaskDispatcher > D
ExecutionSession * ES = nullptr
Triple TargetTriple
unsigned PageSize = 0
JITDispatchInfo JDI
MemoryAccess * MemAccess = nullptr
jitlink::JITLinkMemoryManager * MemMgr = nullptr
StringMap< std::vector< char > > BootstrapMap
StringMap< ExecutorAddr > BootstrapSymbols
Detailed Description
A ExecutorProcessControl implementation targeting the current process.
Definition at line 455 of file ExecutorProcessControl.h.
Constructor & Destructor Documentation
SelfExecutorProcessControl()
llvm::orc::SelfExecutorProcessControl::SelfExecutorProcessControl (std::shared_ptr< SymbolStringPool > SSP, std::unique_ptr< TaskDispatcher > D, Triple TargetTriple, unsigned PageSize, std::unique_ptr< jitlink::JITLinkMemoryManager > MemMgr)
Definition at line 26 of file ExecutorProcessControl.cpp.
References llvm::orc::ExecutorAddr::fromPtr(), llvm::sys::Process::getPageSizeEstimate(), llvm::Triple::isOSBinFormatMachO(), llvm::orc::ExecutorProcessControl::JDI, llvm::orc::ExecutorProcessControl::MemAccess, llvm::orc::ExecutorProcessControl::MemMgr, llvm::orc::ExecutorProcessControl::PageSize, and llvm::orc::ExecutorProcessControl::TargetTriple.
Member Function Documentation
callWrapperAsync()
void llvm::orc::SelfExecutorProcessControl::callWrapperAsync (ExecutorAddr WrapperFnAddr, IncomingWFRHandler OnComplete, ArrayRef< char > ArgBuffer) override virtual
Run a wrapper function in the executor.
The given WFRHandler will be called on the result when it is returned.
The wrapper function should be callable as:
CWrapperFunctionResult fn(uint8_t *Data, uint64_t Size);
{.cpp}
Implements llvm::orc::ExecutorProcessControl.
Definition at line 128 of file ExecutorProcessControl.cpp.
References llvm::Data, and Size.
Create()
Expected< std::unique_ptr< SelfExecutorProcessControl > > llvm::orc::SelfExecutorProcessControl::Create (std::shared_ptr< SymbolStringPool > SSP = nullptr, std::unique_ptr< TaskDispatcher > D = nullptr, std::unique_ptr< jitlink::JITLinkMemoryManager > MemMgr = nullptr) static
Create a SelfExecutorProcessControl with the given symbol string pool and memory manager.
If no symbol string pool is given then one will be created. If no memory manager is given a jitlink::InProcessMemoryManager will be created and used by default.
Definition at line 48 of file ExecutorProcessControl.cpp.
References llvm::orc::ExecutorProcessControl::D, llvm::sys::Process::getPageSize(), llvm::sys::getProcessTriple(), llvm::orc::ExecutorProcessControl::MemMgr, llvm::orc::ExecutorProcessControl::PageSize, and llvm::orc::ExecutorProcessControl::SSP.
Referenced by llvm::orc::LLJIT::LLJIT(), and llvm::orc::LLJITBuilderState::prepareForConstruction().
disconnect()
Error llvm::orc::SelfExecutorProcessControl::disconnect () override virtual
Disconnect from the target process.
This should be called after the JIT session is shut down.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 137 of file ExecutorProcessControl.cpp.
References llvm::orc::ExecutorProcessControl::D, and llvm::Error::success().
loadDylib()
Expected< tpctypes::DylibHandle > llvm::orc::SelfExecutorProcessControl::loadDylib (const char * DylibPath) override virtual
Load the dynamic library at the given path and return a handle to it.
If LibraryPath is null this function will return the global handle for the target process.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 76 of file ExecutorProcessControl.cpp.
References llvm::orc::ExecutorAddr::fromPtr(), llvm::sys::DynamicLibrary::getPermanentLibrary(), and llvm::inconvertibleErrorCode().
lookupSymbols()
Expected< std::vector< tpctypes::LookupResult > > llvm::orc::SelfExecutorProcessControl::lookupSymbols (ArrayRef< LookupRequest > Request) override virtual
Search for symbols in the target process.
The result of the lookup is a 2-dimentional array of target addresses that correspond to the lookup order. If a required symbol is not found then this method will return an error. If a weakly referenced symbol is not found then it be assigned a '0' value.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 85 of file ExecutorProcessControl.cpp.
References Addr, llvm::orc::ExecutorAddr::fromPtr(), llvm::sys::DynamicLibrary::getAddressOfSymbol(), llvm::orc::RequiredSymbol, llvm::orc::ExecutorProcessControl::SSP, and Sym.
runAsIntFunction()
Expected< int32_t > llvm::orc::SelfExecutorProcessControl::runAsIntFunction (ExecutorAddr IntFnAddr, int Arg) override virtual
Run function with a int (*)(int) signature.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 123 of file ExecutorProcessControl.cpp.
References Arg, and llvm::orc::runAsIntFunction().
runAsMain()
Expected< int32_t > llvm::orc::SelfExecutorProcessControl::runAsMain (ExecutorAddr MainFnAddr, ArrayRef< std::string > Args) override virtual
Run function with a main-like signature.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 110 of file ExecutorProcessControl.cpp.
References llvm::orc::runAsMain().
runAsVoidFunction()
Expected< int32_t > llvm::orc::SelfExecutorProcessControl::runAsVoidFunction (ExecutorAddr VoidFnAddr) override virtual
Run function with a int (*)(void) signature.
Implements llvm::orc::ExecutorProcessControl.
Definition at line 117 of file ExecutorProcessControl.cpp.
References llvm::orc::runAsVoidFunction().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/ExecutorProcessControl.h
lib/ExecutionEngine/Orc/ExecutorProcessControl.cpp