LLVM: llvm::MachineModuleInfoWrapperPass Class Reference
llvm::MachineModuleInfoWrapperPass Class Reference
#include "llvm/CodeGen/MachineModuleInfo.h"
Public Member Functions
MachineModuleInfoWrapperPass (const LLVMTargetMachine *TM=nullptr)
MachineModuleInfoWrapperPass (const LLVMTargetMachine *TM, MCContext *ExtContext)
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
bool doFinalization (Module &) override
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
MachineModuleInfo & getMMI ()
const MachineModuleInfo & getMMI () const
Public Member Functions inherited from llvm::ImmutablePass
ImmutablePass (char &pid)
~ImmutablePass () override
virtual void initializePass ()
initializePass - This method may be overriden by immutable passes to allow them to perform various initialization actions they require.
ImmutablePass * getAsImmutablePass () override
bool runOnModule (Module &) override
ImmutablePasses are never run.
Public Member Functions inherited from llvm::ModulePass
ModulePass (char &pid)
~ModulePass () override
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a module printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Module Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::ModulePass
bool skipModule (Module &M) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 203 of file MachineModuleInfo.h.
Constructor & Destructor Documentation
MachineModuleInfoWrapperPass() [1/2]
MachineModuleInfoWrapperPass::MachineModuleInfoWrapperPass (const LLVMTargetMachine * TM = nullptr) explicit
Definition at line 171 of file MachineModuleInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineModuleInfoWrapperPassPass().
MachineModuleInfoWrapperPass() [2/2]
MachineModuleInfoWrapperPass::MachineModuleInfoWrapperPass (const LLVMTargetMachine * TM, MCContext * ExtContext) explicit
Definition at line 177 of file MachineModuleInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineModuleInfoWrapperPassPass().
Member Function Documentation
doFinalization()
bool MachineModuleInfoWrapperPass::doFinalization (Module &) override virtual
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
Reimplemented from llvm::Pass.
Definition at line 233 of file MachineModuleInfo.cpp.
References llvm::MachineModuleInfo::finalize().
doInitialization()
bool MachineModuleInfoWrapperPass::doInitialization (Module &) override virtual
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Reimplemented from llvm::Pass.
Definition at line 213 of file MachineModuleInfo.cpp.
References DisableDebugInfoPrinting, llvm::MachineModuleInfo::getContext(), getLocCookie(), llvm::MachineModuleInfo::initialize(), llvm::MCContext::setDiagnosticHandler(), and llvm::SrcMgr.
getMMI() [1/2]
MachineModuleInfo & llvm::MachineModuleInfoWrapperPass::getMMI () inline
Definition at line 217 of file MachineModuleInfo.h.
getMMI() [2/2]
const MachineModuleInfo & llvm::MachineModuleInfoWrapperPass::getMMI () const inline
Definition at line 218 of file MachineModuleInfo.h.
Member Data Documentation
ID
char llvm::MachineModuleInfoWrapperPass::ID static
Definition at line 207 of file MachineModuleInfo.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineModuleInfo.h
lib/CodeGen/MachineModuleInfo.cpp