LLVM: llvm::objcopy::macho::MachOWriter Class Reference
llvm::objcopy::macho::MachOWriter Class Reference
#include "ObjCopy/MachO/MachOWriter.h"
Public Member Functions
MachOWriter (Object &O, bool Is64Bit, bool IsLittleEndian, StringRef OutputFileName, uint64_t PageSize, raw_ostream &Out)
size_t totalSize () const
Error finalize ()
Error write ()
Detailed Description
Definition at line 24 of file MachOWriter.h.
Constructor & Destructor Documentation
MachOWriter()
llvm::objcopy::macho::MachOWriter::MachOWriter (Object & O, bool Is64Bit, bool IsLittleEndian, StringRef OutputFileName, uint64_t PageSize, raw_ostream & Out) inline
Definition at line 62 of file MachOWriter.h.
Member Function Documentation
finalize()
Error MachOWriter::finalize ()
Definition at line 658 of file MachOWriter.cpp.
References llvm::objcopy::macho::MachOLayoutBuilder::layout().
Referenced by llvm::objcopy::macho::executeObjcopyOnBinary().
totalSize()
size_t MachOWriter::totalSize () const
Definition at line 39 of file MachOWriter.cpp.
References assert(), llvm::objcopy::macho::Object::Binds, llvm::objcopy::macho::Object::ChainedFixupsCommandIndex, llvm::objcopy::macho::Object::CodeSignatureCommandIndex, llvm::objcopy::macho::Object::DataInCodeCommandIndex, llvm::objcopy::macho::Object::DyLdInfoCommandIndex, llvm::objcopy::macho::Object::DylibCodeSignDRsIndex, llvm::objcopy::macho::Object::DySymTabCommandIndex, llvm::objcopy::macho::Object::Exports, llvm::objcopy::macho::Object::ExportsTrieCommandIndex, llvm::objcopy::macho::Object::FunctionStartsCommandIndex, llvm::objcopy::macho::Object::IndirectSymTable, llvm::objcopy::macho::Object::LazyBinds, llvm::objcopy::macho::Object::LinkerOptimizationHintCommandIndex, llvm::objcopy::macho::Object::LoadCommands, llvm::objcopy::macho::RebaseInfo::Opcodes, llvm::objcopy::macho::BindInfo::Opcodes, llvm::objcopy::macho::WeakBindInfo::Opcodes, llvm::objcopy::macho::LazyBindInfo::Opcodes, llvm::objcopy::macho::Object::Rebases, llvm::ArrayRef< T >::size(), llvm::objcopy::macho::IndirectSymbolTable::Symbols, llvm::objcopy::macho::Object::SymTabCommandIndex, llvm::objcopy::macho::ExportInfo::Trie, and llvm::objcopy::macho::Object::WeakBinds.
Referenced by write().
write()
Error MachOWriter::write ()
Definition at line 660 of file MachOWriter.cpp.
References llvm::createStringError(), llvm::WritableMemoryBuffer::getNewMemBuffer(), llvm::not_enough_memory, llvm::Error::success(), totalSize(), and llvm::Twine::utohexstr().
Referenced by llvm::objcopy::macho::executeObjcopyOnBinary().
The documentation for this class was generated from the following files:
lib/ObjCopy/MachO/MachOWriter.h
lib/ObjCopy/MachO/MachOWriter.cpp