LLVM: llvm::DIMacroFile Class Reference
llvm::DIMacroFile Class Reference
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
DEFINE_MDNODE_GET (DIMacroFile,(unsigned MIType, unsigned Line, DIFile *File, DIMacroNodeArray Elements),(MIType, Line, File, Elements)) DEFINE_MDNODE_GET(DIMacroFile
unsigned unsigned Metadata Metadata Elements TempDIMacroFile clone () const
void replaceElements (DIMacroNodeArray Elements)
unsigned getLine () const
DIFile * getFile () const
DIMacroNodeArray getElements () const
Metadata * getRawFile () const
Metadata * getRawElements () const
Public Member Functions inherited from llvm::DIMacroNode
unsigned getMacinfoType () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
void dumpTree () const
User-friendly dump in tree shape.
void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIMacroNode
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
static MDNode * getMergedProfMetadata (MDNode *A, MDNode *B, const Instruction *AInstr, const Instruction *BInstr)
Merge !prof metadata from two instructions.
Public Attributes
unsigned MIType
unsigned unsigned Line
unsigned unsigned Metadata * File
unsigned unsigned Metadata Metadata * Elements
unsigned unsigned Metadata Metadata MIType
unsigned unsigned Metadata Metadata Line
unsigned unsigned Metadata Metadata File
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range<op_iterator>
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range<MDOperand *>
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DIMacroNode
DIMacroNode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned MIType, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~DIMacroNode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~MDNode ()=default
void * operator new (size_t Size, size_t NumOps, StorageType Storage)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DIMacroNode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Definition at line 3645 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
static bool llvm::DIMacroFile::classof (const Metadata * MD) inline static
Definition at line 3704 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
clone()
unsigned unsigned Metadata Metadata Elements TempDIMacroFile llvm::DIMacroFile::clone () const inline
Definition at line 3683 of file DebugInfoMetadata.h.
DEFINE_MDNODE_GET()
llvm::DIMacroFile::DEFINE_MDNODE_GET (DIMacroFile , (unsigned MIType, unsigned Line, DIFile *File, DIMacroNodeArray Elements) , (MIType, Line, File, Elements))
getElements()
DIMacroNodeArray llvm::DIMacroFile::getElements () const inline
Definition at line 3697 of file DebugInfoMetadata.h.
References getRawElements().
Referenced by replaceElements().
getFile()
DIFile * llvm::DIMacroFile::getFile () const inline
Definition at line 3695 of file DebugInfoMetadata.h.
References getRawFile().
getLine()
unsigned llvm::DIMacroFile::getLine () const inline
Definition at line 3694 of file DebugInfoMetadata.h.
getRawElements()
Metadata * llvm::DIMacroFile::getRawElements () const inline
Definition at line 3702 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getElements().
getRawFile()
Metadata * llvm::DIMacroFile::getRawFile () const inline
Definition at line 3701 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getFile().
replaceElements()
void llvm::DIMacroFile::replaceElements (DIMacroNodeArray Elements) inline
Definition at line 3685 of file DebugInfoMetadata.h.
References assert(), Elements, getElements(), llvm::is_contained(), and llvm::MDNode::replaceOperandWith().
Friends And Related Symbol Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 3646 of file DebugInfoMetadata.h.
MDNode
friend class MDNode friend
Definition at line 3647 of file DebugInfoMetadata.h.
Member Data Documentation
Elements
unsigned unsigned Metadata Metadata* llvm::DIMacroFile::Elements
Definition at line 3680 of file DebugInfoMetadata.h.
Referenced by replaceElements().
File [1/2]
unsigned unsigned Metadata* llvm::DIMacroFile::File
Definition at line 3679 of file DebugInfoMetadata.h.
File [2/2]
unsigned unsigned Metadata Metadata llvm::DIMacroFile::File
Definition at line 3681 of file DebugInfoMetadata.h.
Line [1/2]
unsigned unsigned llvm::DIMacroFile::Line
Definition at line 3679 of file DebugInfoMetadata.h.
Line [2/2]
unsigned unsigned Metadata Metadata llvm::DIMacroFile::Line
Definition at line 3681 of file DebugInfoMetadata.h.
MIType [1/2]
unsigned llvm::DIMacroFile::MIType
Definition at line 3679 of file DebugInfoMetadata.h.
MIType [2/2]
unsigned unsigned Metadata Metadata llvm::DIMacroFile::MIType
Definition at line 3681 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp