LLVM: llvm::jitlink::COFFDirectiveParser Class Reference
llvm::jitlink::COFFDirectiveParser Class Reference
Parser for the MSVC specific preprocessor directives.
#include "ExecutionEngine/JITLink/COFFDirectiveParser.h"
Public Member Functions
Expected< opt::InputArgList > parse (StringRef Str)
Detailed Description
Parser for the MSVC specific preprocessor directives.
https://docs.microsoft.com/en-us/cpp/preprocessor/comment-c-cpp?view=msvc-160
Definition at line 36 of file COFFDirectiveParser.h.
Member Function Documentation
parse()
Expected< opt::InputArgList > COFFDirectiveParser::parse (StringRef Str)
Definition at line 64 of file COFFDirectiveParser.cpp.
References llvm::StringRef::data(), llvm::dbgs(), LLVM_DEBUG, optTable, llvm::StringSaver::save(), and llvm::cl::TokenizeWindowsCommandLineNoCopy().
The documentation for this class was generated from the following files:
lib/ExecutionEngine/JITLink/COFFDirectiveParser.h
lib/ExecutionEngine/JITLink/COFFDirectiveParser.cpp