LLVM: llvm::AssumptionPrinterPass Class Reference
llvm::AssumptionPrinterPass Class Reference
Printer pass for the AssumptionAnalysis results.
#include "llvm/Analysis/AssumptionCache.h"
Public Member Functions
AssumptionPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< AssumptionPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< AssumptionPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the AssumptionAnalysis results.
Definition at line 185 of file AssumptionCache.h.
Constructor & Destructor Documentation
AssumptionPrinterPass()
llvm::AssumptionPrinterPass::AssumptionPrinterPass (raw_ostream & OS) inline explicit
Definition at line 189 of file AssumptionCache.h.
References OS.
Member Function Documentation
run()
PreservedAnalyses AssumptionPrinterPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 284 of file AssumptionCache.cpp.
References llvm::PreservedAnalyses::all(), llvm::AssumptionCache::assumptions(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and OS.
The documentation for this class was generated from the following files:
include/llvm/Analysis/AssumptionCache.h
lib/Analysis/AssumptionCache.cpp