LLVM: llvm::ValueAsMetadata Class Reference
llvm::ValueAsMetadata Class Reference
Value wrapper in the Metadata hierarchy.
#include "llvm/IR/Metadata.h"
Public Member Functions
Value * getValue () const
Type * getType () const
LLVMContext & getContext () const
SmallVector< Metadata * > getAllArgListUsers ()
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static ValueAsMetadata * get (Value *V)
static ConstantAsMetadata * getConstant (Value *C)
static LocalAsMetadata * getLocal (Value *Local)
static ValueAsMetadata * getIfExists (Value *V)
static ConstantAsMetadata * getConstantIfExists (Value *C)
static LocalAsMetadata * getLocalIfExists (Value *Local)
static void handleDeletion (Value *V)
static void handleRAUW (Value *From, Value *To)
static bool classof (const Metadata *MD)
Protected Member Functions
ValueAsMetadata (unsigned ID, Value *V)
~ValueAsMetadata ()=default
void replaceAllUsesWith (Metadata *MD)
Handle collisions after Value::replaceAllUsesWith().
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Friends
class ReplaceableMetadataImpl
class LLVMContextImpl
Additional Inherited Members
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Value wrapper in the Metadata hierarchy.
This is a custom value handle that allows other metadata to refer to classes in the Value hierarchy.
Because of full uniquing support, each value is only wrapped by a single ValueAsMetadata object, so the lookup maps are far more efficient than those using ValueHandleBase.
Definition at line 344 of file Metadata.h.
Constructor & Destructor Documentation
ValueAsMetadata()
llvm::ValueAsMetadata::ValueAsMetadata (unsigned ID, Value * V) inline protected
Definition at line 356 of file Metadata.h.
References assert().
~ValueAsMetadata()
llvm::ValueAsMetadata::~ValueAsMetadata () protected default
Member Function Documentation
classof()
static bool llvm::ValueAsMetadata::classof (const Metadata * MD) inline static
Definition at line 406 of file Metadata.h.
References llvm::Metadata::getMetadataID().
get()
ValueAsMetadata * ValueAsMetadata::get (Value * V) static
Definition at line 394 of file Metadata.cpp.
References assert(), and llvm::CallingConv::C.
Referenced by addModuleFlags(), llvm::memprof::buildCallstackMetadata(), llvm::hlsl::FrontendResource::FrontendResource(), getAsMetadata(), getConstant(), getDbgIntrinsicValueImpl(), getLocal(), llvm::DIArgList::handleChangedOperand(), INITIALIZE_PASS(), llvm::DIBuilder::insertDbgAssign(), LLVMValueAsMetadata(), llvm::DbgVariableIntrinsic::replaceVariableLocationOp(), llvm::DbgVariableIntrinsic::replaceVariableLocationOp(), restorePreTransformState(), llvm::ReplaceableMetadataImpl::SalvageDebugInfo(), llvm::DbgAssignIntrinsic::setAddress(), llvm::DbgAssignIntrinsic::setValue(), updateDVIWithLocation(), and updateDVIWithLocations().
getAllArgListUsers()
SmallVector< Metadata * > llvm::ValueAsMetadata::getAllArgListUsers () inline
Definition at line 388 of file Metadata.h.
References llvm::ReplaceableMetadataImpl::getAllArgListUsers().
getConstant()
static ConstantAsMetadata * llvm::ValueAsMetadata::getConstant (Value * C) inline static
Definition at line 366 of file Metadata.h.
References llvm::CallingConv::C, and get().
Referenced by llvm::ConstantAsMetadata::get(), and wrapConstantAsMetadata().
getConstantIfExists()
static ConstantAsMetadata * llvm::ValueAsMetadata::getConstantIfExists (Value * C) inline static
Definition at line 376 of file Metadata.h.
References llvm::CallingConv::C, and getIfExists().
Referenced by llvm::ConstantAsMetadata::getIfExists().
getContext()
LLVMContext & llvm::ValueAsMetadata::getContext () const inline
Definition at line 386 of file Metadata.h.
getIfExists()
ValueAsMetadata * ValueAsMetadata::getIfExists (Value * V) static
Definition at line 413 of file Metadata.cpp.
References assert().
Referenced by getConstantIfExists(), and getLocalIfExists().
getLocal()
static LocalAsMetadata * llvm::ValueAsMetadata::getLocal (Value * Local) inline static
Definition at line 370 of file Metadata.h.
References get().
Referenced by llvm::LocalAsMetadata::get().
getLocalIfExists()
static LocalAsMetadata * llvm::ValueAsMetadata::getLocalIfExists (Value * Local) inline static
Definition at line 380 of file Metadata.h.
References getIfExists().
Referenced by llvm::LocalAsMetadata::getIfExists().
getType()
Type * llvm::ValueAsMetadata::getType () const inline
Definition at line 385 of file Metadata.h.
getValue()
Value * llvm::ValueAsMetadata::getValue () const inline
Definition at line 384 of file Metadata.h.
Referenced by llvm::ConstantAsMetadata::getValue(), handleDeletion(), and handleRAUW().
handleDeletion()
void ValueAsMetadata::handleDeletion (Value * V) static
Definition at line 418 of file Metadata.cpp.
References assert(), getValue(), I, and replaceAllUsesWith().
Referenced by llvm::Value::~Value().
handleRAUW()
void ValueAsMetadata::handleRAUW (Value * From, Value * To) static
Definition at line 437 of file Metadata.cpp.
References assert(), llvm::CallingConv::C, From, llvm::ConstantAsMetadata::get(), getLocalFunctionMetadata(), llvm::Value::getType(), getValue(), I, llvm::Value::IsUsedByMD, and replaceAllUsesWith().
Referenced by llvm::Instruction::~Instruction().
replaceAllUsesWith()
void llvm::ValueAsMetadata::replaceAllUsesWith (Metadata * MD) inline protected
Handle collisions after Value::replaceAllUsesWith().
RAUW isn't supported directly for ValueAsMetadata, but if the wrapped Value gets RAUW'ed and the target already exists, this is used to merge the two metadata nodes.
Definition at line 401 of file Metadata.h.
References llvm::ReplaceableMetadataImpl::replaceAllUsesWith().
Referenced by handleDeletion(), and handleRAUW().
Friends And Related Symbol Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 346 of file Metadata.h.
ReplaceableMetadataImpl
friend class ReplaceableMetadataImpl friend
Definition at line 345 of file Metadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Metadata.h
lib/IR/Metadata.cpp