LLVM: llvm::CSKYConstantPoolMBB Class Reference
llvm::CSKYConstantPoolMBB Class Reference
CSKYConstantPoolMBB - CSKY-specific constantpool value of a machine basic block.
#include "Target/CSKY/CSKYConstantPoolValue.h"
Public Member Functions
const MachineBasicBlock * getMBB () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const CSKYConstantPoolMBB *A) const
Public Member Functions inherited from llvm::CSKYConstantPoolValue
const char * getModifierText () const
unsigned getPCAdjustment () const
bool mustAddCurrentAddress () const
CSKYCP::CSKYCPModifier getModifier () const
unsigned getLabelID () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isMachineBasicBlock () const
bool isJT () const
bool isConstPool () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const CSKYConstantPoolValue *A) const
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, Align Alignment)
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
virtual unsigned getSizeInBytes (const DataLayout &DL) const
Static Public Member Functions
static CSKYConstantPoolMBB * Create (Type *Ty, const MachineBasicBlock *Mbb, unsigned PCAdjust)
static bool classof (const CSKYConstantPoolValue *ACPV)
Additional Inherited Members
Protected Member Functions inherited from llvm::CSKYConstantPoolValue
CSKYConstantPoolValue (Type *Ty, CSKYCP::CSKYCPKind Kind, unsigned PCAdjust, CSKYCP::CSKYCPModifier Modifier, bool AddCurrentAddress, unsigned ID=0)
Protected Attributes inherited from llvm::CSKYConstantPoolValue
CSKYCP::CSKYCPKind Kind
unsigned PCAdjust
CSKYCP::CSKYCPModifier Modifier
bool AddCurrentAddress
unsigned LabelId = 0
Detailed Description
CSKYConstantPoolMBB - CSKY-specific constantpool value of a machine basic block.
Definition at line 173 of file CSKYConstantPoolValue.h.
Member Function Documentation
addSelectionDAGCSEId()
void CSKYConstantPoolMBB::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 187 of file CSKYConstantPoolValue.cpp.
References llvm::CSKYConstantPoolValue::addSelectionDAGCSEId().
classof()
static bool llvm::CSKYConstantPoolMBB::classof (const CSKYConstantPoolValue * ACPV) inline static
Definition at line 194 of file CSKYConstantPoolValue.h.
Create()
CSKYConstantPoolMBB * CSKYConstantPoolMBB::Create (Type * Ty, const MachineBasicBlock * Mbb, unsigned PCAdjust) static
Definition at line 176 of file CSKYConstantPoolValue.cpp.
References llvm::CSKYCP::ADDR, and llvm::CSKYConstantPoolValue::PCAdjust.
equals()
bool llvm::CSKYConstantPoolMBB::equals (const CSKYConstantPoolMBB * A) const inline
Definition at line 190 of file CSKYConstantPoolValue.h.
References A, llvm::CSKYConstantPoolValue::equals(), and MBB.
getExistingMachineCPValue()
int CSKYConstantPoolMBB::getExistingMachineCPValue (MachineConstantPool * CP, Align Alignment) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 182 of file CSKYConstantPoolValue.cpp.
getMBB()
const MachineBasicBlock * llvm::CSKYConstantPoolMBB::getMBB () const inline
Definition at line 183 of file CSKYConstantPoolValue.h.
References MBB.
print()
void CSKYConstantPoolMBB::print (raw_ostream & O) const override virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Definition at line 192 of file CSKYConstantPoolValue.cpp.
References llvm::MachineBasicBlock::getNumber(), and llvm::CSKYConstantPoolValue::print().
The documentation for this class was generated from the following files:
lib/Target/CSKY/CSKYConstantPoolValue.h
lib/Target/CSKY/CSKYConstantPoolValue.cpp