LLVM: llvm::jitlink::i386::PLTTableManager Class Reference
llvm::jitlink::i386::PLTTableManager Class Reference
Procedure Linkage Table Builder.
#include "llvm/ExecutionEngine/JITLink/i386.h"
Public Member Functions
PLTTableManager (GOTTableManager &GOT)
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Section & getStubsSection (LinkGraph &G)
Public Member Functions inherited from llvm::jitlink::TableManager< PLTTableManager >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Static Public Member Functions
static StringRef getSectionName ()
Public Attributes
GOTTableManager & GOT
Section * PLTSection = nullptr
Detailed Description
Procedure Linkage Table Builder.
Definition at line 385 of file i386.h.
Constructor & Destructor Documentation
PLTTableManager()
llvm::jitlink::i386::PLTTableManager::PLTTableManager (GOTTableManager & GOT) inline
Definition at line 387 of file i386.h.
Member Function Documentation
createEntry()
Symbol & llvm::jitlink::i386::PLTTableManager::createEntry (LinkGraph & G, Symbol & Target) inline
Definition at line 407 of file i386.h.
References llvm::jitlink::i386::createAnonymousPointerJumpStub(), G, llvm::jitlink::TableManager< TableManagerImplT >::getEntryForTarget(), getStubsSection(), and GOT.
getSectionName()
static StringRef llvm::jitlink::i386::PLTTableManager::getSectionName () inline static
Definition at line 389 of file i386.h.
Referenced by getStubsSection().
getStubsSection()
Section & llvm::jitlink::i386::PLTTableManager::getStubsSection (LinkGraph & G) inline
Definition at line 413 of file i386.h.
References llvm::orc::Exec, G, getSectionName(), PLTSection, and llvm::orc::Read.
Referenced by createEntry().
visitEdge()
bool llvm::jitlink::i386::PLTTableManager::visitEdge (LinkGraph & G, Block * B, Edge & E) inline
Definition at line 391 of file i386.h.
References B, llvm::jitlink::i386::BranchPCRel32, llvm::jitlink::i386::BranchPCRel32ToPtrJumpStubBypassable, llvm::dbgs(), DEBUG_WITH_TYPE, E, llvm::formatv(), G, and llvm::jitlink::TableManager< PLTTableManager >::getEntryForTarget().
Member Data Documentation
GOT
GOTTableManager& llvm::jitlink::i386::PLTTableManager::GOT
Definition at line 420 of file i386.h.
Referenced by createEntry().
PLTSection
Section* llvm::jitlink::i386::PLTTableManager::PLTSection = nullptr
Definition at line 421 of file i386.h.
Referenced by getStubsSection().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/i386.h