LLVM: llvm::object::ESDRecord Class Reference
llvm::object::ESDRecord Class Reference
#include "llvm/Object/GOFF.h"
Static Public Member Functions
static Error getData (const uint8_t *Record, SmallString< 256 > &CompleteData)
static void getSymbolType (const uint8_t *Record, GOFF::ESDSymbolType &SymbolType)
static void getEsdId (const uint8_t *Record, uint32_t &EsdId)
static void getParentEsdId (const uint8_t *Record, uint32_t &EsdId)
static void getOffset (const uint8_t *Record, uint32_t &Offset)
static void getLength (const uint8_t *Record, uint32_t &Length)
static void getNameSpaceId (const uint8_t *Record, GOFF::ESDNameSpaceId &Id)
static void getFillBytePresent (const uint8_t *Record, bool &Present)
static void getNameMangled (const uint8_t *Record, bool &Mangled)
static void getRenamable (const uint8_t *Record, bool &Renamable)
static void getRemovable (const uint8_t *Record, bool &Removable)
static void getFillByteValue (const uint8_t *Record, uint8_t &Fill)
static void getAdaEsdId (const uint8_t *Record, uint32_t &EsdId)
static void getSortPriority (const uint8_t *Record, uint32_t &Priority)
static void getAmode (const uint8_t *Record, GOFF::ESDAmode &Amode)
static void getRmode (const uint8_t *Record, GOFF::ESDRmode &Rmode)
static void getTextStyle (const uint8_t *Record, GOFF::ESDTextStyle &Style)
static void getBindingAlgorithm (const uint8_t *Record, GOFF::ESDBindingAlgorithm &Algorithm)
static void getTaskingBehavior (const uint8_t *Record, GOFF::ESDTaskingBehavior &TaskingBehavior)
static void getReadOnly (const uint8_t *Record, bool &ReadOnly)
static void getExecutable (const uint8_t *Record, GOFF::ESDExecutable &Executable)
static void getDuplicateSeverity (const uint8_t *Record, GOFF::ESDDuplicateSymbolSeverity &DSS)
static void getBindingStrength (const uint8_t *Record, GOFF::ESDBindingStrength &Strength)
static void getLoadingBehavior (const uint8_t *Record, GOFF::ESDLoadingBehavior &Behavior)
static void getIndirectReference (const uint8_t *Record, bool &Indirect)
static void getBindingScope (const uint8_t *Record, GOFF::ESDBindingScope &Scope)
static void getLinkageType (const uint8_t *Record, GOFF::ESDLinkageType &Type)
static void getAlignment (const uint8_t *Record, GOFF::ESDAlignment &Alignment)
static uint16_t getNameLength (const uint8_t *Record)
Static Public Member Functions inherited from llvm::object::Record
static Error getContinuousData (const uint8_t *Record, uint16_t DataLength, int DataIndex, SmallString< 256 > &CompleteData)
static bool isContinued (const uint8_t *Record)
static bool isContinuation (const uint8_t *Record)
Static Public Attributes
static const uint8_t ESDMaxUncontinuedNameLength = 8
Number of bytes for name; any more must go in continuation.
static const uint16_t MaxNameLength = 32 * 1024
Maximum name length for ESD records and continuations.
Additional Inherited Members
Static Protected Member Functions inherited from llvm::object::Record
static void getBits (const uint8_t *Bytes, uint8_t ByteIndex, uint8_t BitIndex, uint8_t Length, uint8_t &Value)
Get bit field of specified byte.
template<class T >
static void get (const uint8_t *Bytes, uint8_t ByteIndex, T &Value)
Detailed Description
Definition at line 88 of file GOFF.h.
Member Function Documentation
getAdaEsdId()
static void llvm::object::ESDRecord::getAdaEsdId (const uint8_t * Record, uint32_t & EsdId) inline static
Definition at line 162 of file GOFF.h.
getAlignment()
static void llvm::object::ESDRecord::getAlignment (const uint8_t * Record, GOFF::ESDAlignment & Alignment) inline static
Definition at line 256 of file GOFF.h.
References llvm::object::Record::getBits().
getAmode()
static void llvm::object::ESDRecord::getAmode (const uint8_t * Record, GOFF::ESDAmode & Amode) inline static
Definition at line 170 of file GOFF.h.
getBindingAlgorithm()
static void llvm::object::ESDRecord::getBindingAlgorithm (const uint8_t * Record, GOFF::ESDBindingAlgorithm & Algorithm) inline static
Definition at line 188 of file GOFF.h.
References llvm::object::Record::getBits().
getBindingScope()
static void llvm::object::ESDRecord::getBindingScope (const uint8_t * Record, GOFF::ESDBindingScope & Scope) inline static
Definition at line 242 of file GOFF.h.
References llvm::object::Record::getBits().
getBindingStrength()
static void llvm::object::ESDRecord::getBindingStrength (const uint8_t * Record, GOFF::ESDBindingStrength & Strength) inline static
Definition at line 222 of file GOFF.h.
References llvm::object::Record::getBits().
getData()
Error ESDRecord::getData (const uint8_t * Record, SmallString< 256 > & CompleteData) static
Definition at line 473 of file GOFFObjectFile.cpp.
References llvm::object::Record::getContinuousData(), and getNameLength().
getDuplicateSeverity()
static void llvm::object::ESDRecord::getDuplicateSeverity (const uint8_t * Record, GOFF::ESDDuplicateSymbolSeverity & DSS) inline static
Definition at line 215 of file GOFF.h.
References llvm::object::Record::getBits().
getEsdId()
static void llvm::object::ESDRecord::getEsdId (const uint8_t * Record, uint32_t & EsdId) inline static
Definition at line 112 of file GOFF.h.
Referenced by llvm::object::GOFFObjectFile::GOFFObjectFile().
getExecutable()
static void llvm::object::ESDRecord::getExecutable (const uint8_t * Record, GOFF::ESDExecutable & Executable) inline static
Definition at line 208 of file GOFF.h.
References llvm::object::Record::getBits().
getFillBytePresent()
static void llvm::object::ESDRecord::getFillBytePresent (const uint8_t * Record, bool & Present) inline static
Definition at line 134 of file GOFF.h.
References llvm::object::Record::getBits().
getFillByteValue()
static void llvm::object::ESDRecord::getFillByteValue (const uint8_t * Record, uint8_t & Fill) inline static
Definition at line 158 of file GOFF.h.
getIndirectReference()
static void llvm::object::ESDRecord::getIndirectReference (const uint8_t * Record, bool & Indirect) inline static
Definition at line 236 of file GOFF.h.
References llvm::object::Record::getBits().
getLength()
static void llvm::object::ESDRecord::getLength (const uint8_t * Record, uint32_t & Length) inline static
Definition at line 124 of file GOFF.h.
References llvm::Length.
Referenced by llvm::object::GOFFObjectFile::GOFFObjectFile().
getLinkageType()
static void llvm::object::ESDRecord::getLinkageType (const uint8_t * Record, GOFF::ESDLinkageType & Type) inline static
Definition at line 249 of file GOFF.h.
References llvm::object::Record::getBits().
getLoadingBehavior()
static void llvm::object::ESDRecord::getLoadingBehavior (const uint8_t * Record, GOFF::ESDLoadingBehavior & Behavior) inline static
Definition at line 229 of file GOFF.h.
References llvm::object::Record::getBits().
getNameLength()
static uint16_t llvm::object::ESDRecord::getNameLength (const uint8_t * Record) inline static
Definition at line 263 of file GOFF.h.
References llvm::Length.
Referenced by getData().
getNameMangled()
static void llvm::object::ESDRecord::getNameMangled (const uint8_t * Record, bool & Mangled) inline static
Definition at line 140 of file GOFF.h.
References llvm::object::Record::getBits().
getNameSpaceId()
static void llvm::object::ESDRecord::getNameSpaceId (const uint8_t * Record, GOFF::ESDNameSpaceId & Id) inline static
Definition at line 128 of file GOFF.h.
getOffset()
static void llvm::object::ESDRecord::getOffset (const uint8_t * Record, uint32_t & Offset) inline static
Definition at line 120 of file GOFF.h.
References llvm::Offset.
getParentEsdId()
static void llvm::object::ESDRecord::getParentEsdId (const uint8_t * Record, uint32_t & EsdId) inline static
Definition at line 116 of file GOFF.h.
Referenced by llvm::object::GOFFObjectFile::GOFFObjectFile().
getReadOnly()
static void llvm::object::ESDRecord::getReadOnly (const uint8_t * Record, bool & ReadOnly) inline static
Definition at line 202 of file GOFF.h.
References llvm::object::Record::getBits().
getRemovable()
static void llvm::object::ESDRecord::getRemovable (const uint8_t * Record, bool & Removable) inline static
Definition at line 152 of file GOFF.h.
References llvm::object::Record::getBits().
getRenamable()
static void llvm::object::ESDRecord::getRenamable (const uint8_t * Record, bool & Renamable) inline static
Definition at line 146 of file GOFF.h.
References llvm::object::Record::getBits().
getRmode()
static void llvm::object::ESDRecord::getRmode (const uint8_t * Record, GOFF::ESDRmode & Rmode) inline static
Definition at line 176 of file GOFF.h.
getSortPriority()
static void llvm::object::ESDRecord::getSortPriority (const uint8_t * Record, uint32_t & Priority) inline static
Definition at line 166 of file GOFF.h.
getSymbolType()
static void llvm::object::ESDRecord::getSymbolType (const uint8_t * Record, GOFF::ESDSymbolType & SymbolType) inline static
Definition at line 105 of file GOFF.h.
Referenced by llvm::object::GOFFObjectFile::GOFFObjectFile(), and llvm::object::GOFFObjectFile::moveSymbolNext().
getTaskingBehavior()
static void llvm::object::ESDRecord::getTaskingBehavior (const uint8_t * Record, GOFF::ESDTaskingBehavior & TaskingBehavior) inline static
Definition at line 195 of file GOFF.h.
References llvm::object::Record::getBits().
getTextStyle()
static void llvm::object::ESDRecord::getTextStyle (const uint8_t * Record, GOFF::ESDTextStyle & Style) inline static
Definition at line 182 of file GOFF.h.
References llvm::object::Record::getBits().
Member Data Documentation
ESDMaxUncontinuedNameLength
const uint8_t llvm::object::ESDRecord::ESDMaxUncontinuedNameLength = 8 static
Number of bytes for name; any more must go in continuation.
This is the number of bytes that can fit into the data field of an ESD record.
Definition at line 93 of file GOFF.h.
MaxNameLength
const uint16_t llvm::object::ESDRecord::MaxNameLength = 32 * 1024 static
Maximum name length for ESD records and continuations.
This is the number of bytes that can fit into the data field of an ESD record AND following continuations. This is limited fundamentally by the 16 bit SIGNED length field.
Definition at line 99 of file GOFF.h.
The documentation for this class was generated from the following files:
include/llvm/Object/GOFF.h
lib/Object/GOFFObjectFile.cpp