LLVM: llvm::DWARFFormValue Class Reference
llvm::DWARFFormValue Class Reference
#include "llvm/DebugInfo/DWARF/DWARFFormValue.h"
Classes
struct UnitOffset
struct ValueType
Public Types
enum FormClass {
FC_Unknown , FC_Address , FC_Block , FC_Constant ,
FC_String , FC_Flag , FC_Reference , FC_Indirect ,
FC_SectionOffset , FC_Exprloc
}
Public Member Functions
DWARFFormValue (dwarf::Form F=dwarf::Form(0))
dwarf::Form getForm () const
uint64_t getRawUValue () const
bool isFormClass (FormClass FC) const
const DWARFUnit * getUnit () const
void dump (raw_ostream &OS, DIDumpOptions DumpOpts=DIDumpOptions()) const
void dumpSectionedAddress (raw_ostream &OS, DIDumpOptions DumpOpts, object::SectionedAddress SA) const
void dumpAddress (raw_ostream &OS, uint64_t Address) const
bool extractValue (const DWARFDataExtractor &Data, uint64_t *OffsetPtr, dwarf::FormParams FormParams, const DWARFContext *Context=nullptr, const DWARFUnit *Unit=nullptr)
Extracts a value in Data at offset *OffsetPtr.
bool extractValue (const DWARFDataExtractor &Data, uint64_t *OffsetPtr, dwarf::FormParams FormParams, const DWARFUnit *U)
std::optional< uint64_t > getAsReference () const
getAsFoo functions below return the extracted value as Foo if only DWARFFormValue has form class is suitable for representing Foo.
std::optional< UnitOffset > getAsRelativeReference () const
std::optional< uint64_t > getAsUnsignedConstant () const
std::optional< int64_t > getAsSignedConstant () const
Expected< const char * > getAsCString () const
std::optional< uint64_t > getAsAddress () const
std::optional< object::SectionedAddress > getAsSectionedAddress () const
std::optional< uint64_t > getAsSectionOffset () const
std::optional< ArrayRef< uint8_t > > getAsBlock () const
std::optional< uint64_t > getAsCStringOffset () const
std::optional< uint64_t > getAsReferenceUVal () const
std::optional< std::string > getAsFile (DILineInfoSpecifier::FileLineInfoKind Kind) const
Correctly extract any file paths from a form value.
bool skipValue (DataExtractor DebugInfoData, uint64_t *OffsetPtr, const dwarf::FormParams Params) const
Skip a form's value in DebugInfoData at the offset specified by OffsetPtr.
Static Public Member Functions
static DWARFFormValue createFromSValue (dwarf::Form F, int64_t V)
static DWARFFormValue createFromUValue (dwarf::Form F, uint64_t V)
static DWARFFormValue createFromPValue (dwarf::Form F, const char *V)
static DWARFFormValue createFromBlockValue (dwarf::Form F, ArrayRef< uint8_t > D)
static DWARFFormValue createFromUnit (dwarf::Form F, const DWARFUnit *Unit, uint64_t *OffsetPtr)
static std::optional< object::SectionedAddress > getAsSectionedAddress (const ValueType &Val, const dwarf::Form Form, const DWARFUnit *U)
static void dumpAddress (raw_ostream &OS, uint8_t AddressSize, uint64_t Address)
static void dumpAddressSection (const DWARFObject &Obj, raw_ostream &OS, DIDumpOptions DumpOpts, uint64_t SectionIndex)
static bool skipValue (dwarf::Form Form, DataExtractor DebugInfoData, uint64_t *OffsetPtr, const dwarf::FormParams FormParams)
Skip a form's value in DebugInfoData at the offset specified by OffsetPtr.
Detailed Description
Definition at line 26 of file DWARFFormValue.h.
Member Enumeration Documentation
FormClass
enum llvm::DWARFFormValue::FormClass
Enumerator
FC_Unknown
FC_Address
FC_Block
FC_Constant
FC_String
FC_Flag
FC_Reference
FC_Indirect
FC_SectionOffset
FC_Exprloc
Definition at line 28 of file DWARFFormValue.h.
Constructor & Destructor Documentation
DWARFFormValue()
llvm::DWARFFormValue::DWARFFormValue (dwarf::Form F = dwarf::Form(0)) inline
Definition at line 67 of file DWARFFormValue.h.
Member Function Documentation
createFromBlockValue()
DWARFFormValue DWARFFormValue::createFromBlockValue (dwarf::Form F, ArrayRef< uint8_t > D) static
Definition at line 94 of file DWARFFormValue.cpp.
References D, F, and llvm::DWARFFormValue::ValueType::uval.
createFromPValue()
DWARFFormValue DWARFFormValue::createFromPValue (dwarf::Form F, const char * V) static
Definition at line 90 of file DWARFFormValue.cpp.
References F.
Referenced by llvm::DWARFDebugLine::LineTable::parse(), and parseV2DirFileTables().
createFromSValue()
DWARFFormValue DWARFFormValue::createFromSValue (dwarf::Form F, int64_t V) static
Definition at line 82 of file DWARFFormValue.cpp.
References F.
Referenced by llvm::DWARFAbbreviationDeclaration::getAttributeValueFromOffset(), and llvm::DWARFAbbreviationDeclaration::AttributeSpec::getFormValue().
createFromUnit()
DWARFFormValue DWARFFormValue::createFromUnit (dwarf::Form F, const DWARFUnit * Unit, uint64_t * OffsetPtr) static
Definition at line 102 of file DWARFFormValue.cpp.
References extractValue(), and F.
createFromUValue()
DWARFFormValue DWARFFormValue::createFromUValue (dwarf::Form F, uint64_t V) static
Definition at line 86 of file DWARFFormValue.cpp.
References F.
Referenced by dumpAttribute().
dump()
void DWARFFormValue::dump (raw_ostream & OS, DIDumpOptions DumpOpts = DIDumpOptions()) const
Definition at line 382 of file DWARFFormValue.cpp.
References A, llvm::Address, dumpSectionedAddress(), llvm::format(), llvm::WithColor::get(), getAsSectionedAddress(), llvm::dwarf::getDwarfOffsetByteSize(), llvm::nulls(), llvm::Offset, OS, llvm::DIDumpOptions::ShowAddresses, llvm::DIDumpOptions::Verbose, and llvm::raw_ostream::write_escaped().
Referenced by llvm::DWARFDebugLine::Prologue::dump(), dumpAttribute(), and dumpLocationList().
dumpAddress() [1/2]
void llvm::DWARFFormValue::dumpAddress (raw_ostream & OS, uint64_t Address) const
Referenced by llvm::DWARFDebugArangeSet::Descriptor::dump(), llvm::DWARFAddressRange::dump(), llvm::RangeListEntry::dump(), dumpAttribute(), dumpSectionedAddress(), and llvm::DWARFDebugLine::LineTable::parse().
dumpAddress() [2/2]
void DWARFFormValue::dumpAddress (raw_ostream & OS, uint8_t AddressSize, uint64_t Address) static
Definition at line 353 of file DWARFFormValue.cpp.
References llvm::format(), and OS.
dumpAddressSection()
void DWARFFormValue::dumpAddressSection (const DWARFObject & Obj, raw_ostream & OS, DIDumpOptions DumpOpts, uint64_t SectionIndex) static
Definition at line 367 of file DWARFFormValue.cpp.
References llvm::format(), llvm::DWARFObject::getSectionNames(), OS, and llvm::DIDumpOptions::Verbose.
Referenced by llvm::DWARFAddressRange::dump(), llvm::DWARFDebugLoc::dumpRawEntry(), llvm::DWARFDebugLoclists::dumpRawEntry(), and dumpSectionedAddress().
dumpSectionedAddress()
void DWARFFormValue::dumpSectionedAddress (raw_ostream & OS, DIDumpOptions DumpOpts, object::SectionedAddress SA) const
Definition at line 359 of file DWARFFormValue.cpp.
References llvm::object::SectionedAddress::Address, dumpAddress(), dumpAddressSection(), OS, and llvm::object::SectionedAddress::SectionIndex.
Referenced by dump().
extractValue() [1/2]
bool DWARFFormValue::extractValue (const DWARFDataExtractor & Data, uint64_t * OffsetPtr, dwarf::FormParams FormParams, const DWARFContext * Context = nullptr, const DWARFUnit * Unit = nullptr)
Extracts a value in Data at offset *OffsetPtr.
The information in FormParams is needed to interpret some forms. The optional Context and Unit allows extracting information if the form refers to other sections (e.g., .debug_str).
Definition at line 220 of file DWARFFormValue.cpp.
References llvm::Data, llvm::errorToBool(), FP, llvm_unreachable, Size, and llvm::Error::success().
Referenced by createFromUnit(), extractValue(), llvm::DWARFAbbreviationDeclaration::getAttributeValueFromOffset(), and llvm::AppleAcceleratorTable::readAtoms().
extractValue() [2/2]
bool llvm::DWARFFormValue::extractValue (const DWARFDataExtractor & Data, uint64_t * OffsetPtr, dwarf::FormParams FormParams, const DWARFUnit * U) inline
Definition at line 103 of file DWARFFormValue.h.
References llvm::Data, and extractValue().
getAsAddress()
std::optional< uint64_t > DWARFFormValue::getAsAddress () const
Definition at line 634 of file DWARFFormValue.cpp.
References getAsSectionedAddress().
Referenced by dumpAttribute().
getAsBlock()
std::optional< ArrayRef< uint8_t > > DWARFFormValue::getAsBlock () const
Definition at line 728 of file DWARFFormValue.cpp.
References llvm::ArrayRef(), FC_Block, FC_Exprloc, and isFormClass().
Referenced by dumpLocationExpr().
getAsCString()
Expected< const char * > DWARFFormValue::getAsCString () const
Definition at line 591 of file DWARFFormValue.cpp.
References FC_String, llvm::dwarf::FormEncodingString(), llvm::DataExtractor::getCStr(), llvm::DWARFContext::getLineStringExtractor(), llvm::DWARFContext::getStringExtractor(), llvm::inconvertibleErrorCode(), isFormClass(), llvm::Offset, and llvm::StringRef::str().
getAsCStringOffset()
std::optional< uint64_t > DWARFFormValue::getAsCStringOffset () const
Definition at line 735 of file DWARFFormValue.cpp.
References FC_String, and isFormClass().
getAsFile()
std::optional< std::string > DWARFFormValue::getAsFile (DILineInfoSpecifier::FileLineInfoKind Kind) const
Correctly extract any file paths from a form value.
These attributes can be in the from DW_AT_decl_file or DW_AT_call_file attributes. We need to use the file index in the correct DWARFUnit's line table prologue, and each DWARFFormValue has the DWARFUnit the form value was extracted from.
Parameters
Kind The kind of path to extract.
Returns
A valid string value on success, or std::nullopt if the form class is not FC_Constant, or if the file index is not valid.
Definition at line 748 of file DWARFFormValue.cpp.
References FC_Constant, and isFormClass().
getAsReference()
std::optional< uint64_t > DWARFFormValue::getAsReference () const
getAsFoo functions below return the extracted value as Foo if only DWARFFormValue has form class is suitable for representing Foo.
Definition at line 668 of file DWARFFormValue.cpp.
References getAsRelativeReference().
getAsReferenceUVal()
std::optional< uint64_t > DWARFFormValue::getAsReferenceUVal () const
Definition at line 741 of file DWARFFormValue.cpp.
References FC_Reference, and isFormClass().
getAsRelativeReference()
std::optional< DWARFFormValue::UnitOffset > DWARFFormValue::getAsRelativeReference () const
Definition at line 675 of file DWARFFormValue.cpp.
References FC_Reference, and isFormClass().
Referenced by getAsReference().
getAsSectionedAddress() [1/2]
std::optional< object::SectionedAddress > DWARFFormValue::getAsSectionedAddress () const
Definition at line 664 of file DWARFFormValue.cpp.
References getAsSectionedAddress().
Referenced by dump(), getAsAddress(), and getAsSectionedAddress().
getAsSectionedAddress() [2/2]
std::optional< object::SectionedAddress > DWARFFormValue::getAsSectionedAddress (const ValueType & Val, const dwarf::Form Form, const DWARFUnit * U) static
Definition at line 640 of file DWARFFormValue.cpp.
References llvm::dwarf::doesFormBelongToClass(), and FC_Address.
getAsSectionOffset()
std::optional< uint64_t > DWARFFormValue::getAsSectionOffset () const
Definition at line 696 of file DWARFFormValue.cpp.
References FC_SectionOffset, and isFormClass().
Referenced by dumpAttribute(), and dumpLocationList().
getAsSignedConstant()
std::optional< int64_t > DWARFFormValue::getAsSignedConstant () const
Definition at line 709 of file DWARFFormValue.cpp.
References FC_Constant, FC_Flag, and isFormClass().
getAsUnsignedConstant()
std::optional< uint64_t > DWARFFormValue::getAsUnsignedConstant () const
Definition at line 702 of file DWARFFormValue.cpp.
References FC_Constant, FC_Flag, and isFormClass().
Referenced by dumpAttribute(), and llvm::AppleAcceleratorTable::readAtoms().
getForm()
dwarf::Form llvm::DWARFFormValue::getForm () const inline
Definition at line 80 of file DWARFFormValue.h.
Referenced by dumpAttribute(), dumpLocationList(), and llvm::AppleAcceleratorTable::validateForms().
getRawUValue()
uint64_t llvm::DWARFFormValue::getRawUValue () const inline
Definition at line 81 of file DWARFFormValue.h.
getUnit()
const DWARFUnit * llvm::DWARFFormValue::getUnit () const inline
Definition at line 84 of file DWARFFormValue.h.
isFormClass()
bool DWARFFormValue::isFormClass (DWARFFormValue::FormClass FC) const
Definition at line 216 of file DWARFFormValue.cpp.
References llvm::dwarf::doesFormBelongToClass().
Referenced by dumpAttribute(), dumpLocationExpr(), dumpLocationList(), getAsBlock(), getAsCString(), getAsCStringOffset(), getAsFile(), getAsReferenceUVal(), getAsRelativeReference(), getAsSectionOffset(), getAsSignedConstant(), getAsUnsignedConstant(), and llvm::AppleAcceleratorTable::validateForms().
skipValue() [1/2]
bool llvm::DWARFFormValue::skipValue (DataExtractor DebugInfoData, uint64_t * OffsetPtr, const dwarf::FormParams Params) const inline
Skip a form's value in DebugInfoData at the offset specified by OffsetPtr.
Skips the bytes for the current form and updates the offset.
Parameters
DebugInfoData The data where we want to skip the value.
OffsetPtr A reference to the offset that will be updated.
Params DWARF parameters to help interpret forms.
Returns
true on success, false if the form was not skipped.
Definition at line 148 of file DWARFFormValue.h.
References skipValue().
Referenced by llvm::DWARFDebugInfoEntry::extractFast(), llvm::DWARFAbbreviationDeclaration::getAttributeOffsetFromIndex(), getCUIdentifiers(), and skipValue().
skipValue() [2/2]
bool DWARFFormValue::skipValue (dwarf::Form Form, DataExtractor DebugInfoData, uint64_t * OffsetPtr, const dwarf::FormParams FormParams) static
Skip a form's value in DebugInfoData at the offset specified by OffsetPtr.
Skips the bytes for the specified form and updates the offset.
Parameters
Form The DW_FORM enumeration that indicates the form to skip.
DebugInfoData The data where we want to skip the value.
OffsetPtr A reference to the offset that will be updated.
FormParams DWARF parameters to help interpret forms.
Returns
true on success, false if the form was not skipped.
Definition at line 110 of file DWARFFormValue.cpp.
References llvm::dwarf::getFixedFormByteSize(), and size().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFFormValue.h
lib/DebugInfo/DWARF/DWARFFormValue.cpp