LLVM: llvm::ArgumentInit Class Reference
llvm::ArgumentInit Class Reference
#include "llvm/TableGen/Record.h"
Public Types
enum Kind { Positional , Named }
Public Member Functions
ArgumentInit (const ArgumentInit &)=delete
ArgumentInit & operator= (const ArgumentInit &)=delete
RecordKeeper & getRecordKeeper () const
bool isPositional () const
bool isNamed () const
Init * getValue () const
unsigned getIndex () const
Init * getName () const
ArgumentInit * cloneWithValue (Init *Value) const
void Profile (FoldingSetNodeID &ID) const
Init * resolveReferences (Resolver &R) const override
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
std::string getAsString () const override
Convert this value to a literal form.
bool isComplete () const override
Is this a complete value with no unset (uninitialized) subvalues?
bool isConcrete () const override
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
Init * getBit (unsigned Bit) const override
Get the Init value of the specified bit.
Init * getCastTo (RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
void print (raw_ostream &OS) const
Print this value.
virtual std::string getAsUnquotedString () const
Convert this value to a literal form, without adding quotes around a string.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
virtual Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This function is used to implement the bit range selection operator.
virtual RecTy * getFieldType (StringInit *FieldName) const
This function is used to implement the FieldInit class.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const Init *I)
static ArgumentInit * get (Init *Value, ArgAuxType Aux)
Protected Member Functions
ArgumentInit (Init *Value, ArgAuxType Aux)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_DagInit , IK_DefInit , IK_FieldInit , IK_IntInit ,
IK_ListInit , IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit ,
IK_UnOpInit , IK_LastOpInit , IK_CondOpInit , IK_FoldOpInit ,
IK_IsAOpInit , IK_ExistsOpInit , IK_AnonymousNameInit , IK_StringInit ,
IK_VarInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit , IK_ArgumentInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
Definition at line 487 of file Record.h.
Member Enumeration Documentation
Kind
enum llvm::ArgumentInit::Kind
Enumerator
Positional
Named
Definition at line 489 of file Record.h.
Constructor & Destructor Documentation
ArgumentInit() [1/2]
llvm::ArgumentInit::ArgumentInit (Init * Value, ArgAuxType Aux) inline explicit protected
Definition at line 499 of file Record.h.
Referenced by get().
ArgumentInit() [2/2]
llvm::ArgumentInit::ArgumentInit (const ArgumentInit &) delete
Member Function Documentation
classof()
static bool llvm::ArgumentInit::classof (const Init * I) inline static
Definition at line 506 of file Record.h.
References I, and llvm::Init::IK_ArgumentInit.
cloneWithValue()
ArgumentInit * llvm::ArgumentInit::cloneWithValue (Init * Value) const inline
Definition at line 524 of file Record.h.
References get().
Referenced by resolveReferences().
convertInitializerTo()
Init * llvm::ArgumentInit::convertInitializerTo (RecTy * Ty) const inline override virtual
Convert to a value whose type is Ty, or return null if this is not possible.
This can happen if the value's type is convertible to Ty, but there are unresolved references.
Implements llvm::Init.
Definition at line 542 of file Record.h.
get()
ArgumentInit * ArgumentInit::get (Init * Value, ArgAuxType Aux) static
Definition at line 385 of file Record.cpp.
References ArgumentInit(), llvm::RecordKeeper::getImpl(), I, and ProfileArgumentInit().
Referenced by cloneWithValue().
getAsString()
std::string llvm::ArgumentInit::getAsString () const inline override virtual
Convert this value to a literal form.
Implements llvm::Init.
Definition at line 529 of file Record.h.
References llvm::Init::getAsString(), getIndex(), getName(), isNamed(), isPositional(), and llvm_unreachable.
getBit()
Init * llvm::ArgumentInit::getBit (unsigned Bit) const inline override virtual
Get the Init value of the specified bit.
Implements llvm::Init.
Definition at line 540 of file Record.h.
getCastTo()
Init * llvm::ArgumentInit::getCastTo (RecTy * Ty) const inline override virtual
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Otherwise, return null.
Implements llvm::Init.
Definition at line 541 of file Record.h.
getIndex()
unsigned llvm::ArgumentInit::getIndex () const inline
Definition at line 516 of file Record.h.
References assert(), and isPositional().
Referenced by getAsString().
getName()
Init * llvm::ArgumentInit::getName () const inline
Definition at line 520 of file Record.h.
References assert(), and isNamed().
Referenced by getAsString().
getRecordKeeper()
RecordKeeper & llvm::ArgumentInit::getRecordKeeper () const inline
Definition at line 508 of file Record.h.
getValue()
Init * llvm::ArgumentInit::getValue () const inline
Definition at line 515 of file Record.h.
isComplete()
bool llvm::ArgumentInit::isComplete () const inline override virtual
Is this a complete value with no unset (uninitialized) subvalues?
Reimplemented from llvm::Init.
Definition at line 538 of file Record.h.
isConcrete()
bool llvm::ArgumentInit::isConcrete () const inline override virtual
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
Reimplemented from llvm::Init.
Definition at line 539 of file Record.h.
isNamed()
bool llvm::ArgumentInit::isNamed () const inline
Definition at line 513 of file Record.h.
References Named.
Referenced by getAsString(), and getName().
isPositional()
bool llvm::ArgumentInit::isPositional () const inline
Definition at line 512 of file Record.h.
References Positional.
Referenced by getAsString(), and getIndex().
operator=()
ArgumentInit & llvm::ArgumentInit::operator= (const ArgumentInit &) delete
Profile()
void ArgumentInit::Profile (FoldingSetNodeID & ID) const
Definition at line 381 of file Record.cpp.
References ProfileArgumentInit().
resolveReferences()
Init * ArgumentInit::resolveReferences (Resolver & R) const override virtual
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 400 of file Record.cpp.
References cloneWithValue().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp