LLVM: llvm::jitlink::ELFLinkGraphBuilder_aarch32< DataEndianness > Class Template Reference
llvm::jitlink::ELFLinkGraphBuilder_aarch32< DataEndianness > Class Template Reference
Public Member Functions
ELFLinkGraphBuilder_aarch32 (StringRef FileName, const llvm::object::ELFFile< ELFT > &Obj, Triple TT, SubtargetFeatures Features, aarch32::ArmConfig ArmCfg)
Public Member Functions inherited from llvm::jitlink::ELFLinkGraphBuilder< ELFType< DataEndianness, false > >
ELFLinkGraphBuilder (const object::ELFFile< ELFType< DataEndianness, false > > &Obj, Triple TT, SubtargetFeatures Features, StringRef FileName, LinkGraph::GetEdgeKindNameFunction GetEdgeKindName)
ELFLinkGraphBuilder & setProcessDebugSections (bool ProcessDebugSections)
Debug sections are included in the graph by default.
Expected< std::unique_ptr< LinkGraph > > buildGraph ()
Attempt to construct and return the LinkGraph.
Error forEachRelaRelocation (const typename ELFT::Shdr &RelSect, RelocHandlerFunction &&Func)
Error forEachRelRelocation (const typename ELFT::Shdr &RelSect, RelocHandlerFunction &&Func)
Public Member Functions inherited from llvm::jitlink::ELFLinkGraphBuilderBase
ELFLinkGraphBuilderBase (std::unique_ptr< LinkGraph > G)
virtual ~ELFLinkGraphBuilderBase ()
Protected Member Functions
TargetFlagsType makeTargetFlags (const typename ELFT::Sym &Sym) override
orc::ExecutorAddrDiff getRawOffset (const typename ELFT::Sym &Sym, TargetFlagsType Flags) override
Protected Member Functions inherited from llvm::jitlink::ELFLinkGraphBuilder< ELFType< DataEndianness, false > >
bool isRelocatable () const
void setGraphBlock (ELFSectionIndex SecIndex, Block *B)
Block * getGraphBlock (ELFSectionIndex SecIndex)
void setGraphSymbol (ELFSymbolIndex SymIndex, Symbol &Sym)
Symbol * getGraphSymbol (ELFSymbolIndex SymIndex)
Expected< std::pair< Linkage, Scope > > getSymbolLinkageAndScope (const typename ELFT::Sym &Sym, StringRef Name)
virtual TargetFlagsType makeTargetFlags (const typename ELFT::Sym &Sym)
Set the target flags on the given Symbol.
virtual orc::ExecutorAddrDiff getRawOffset (const typename ELFT::Sym &Sym, TargetFlagsType Flags)
Get the physical offset of the symbol on the target platform.
Error prepare ()
Error graphifySections ()
Error graphifySymbols ()
virtual bool excludeSection (const typename ELFT::Shdr &Sect) const
Override in derived classes to suppress certain sections in the link graph.
Error forEachRelaRelocation (const typename ELFT::Shdr &RelSect, RelocHandlerMethod &&Func)
Traverse all matching ELFT::Rela relocation records in the given section.
Error forEachRelaRelocation (const typename ELFT::Shdr &RelSect, ClassT *Instance, RelocHandlerMethod &&Method)
Traverse all matching rela relocation records in the given section.
Error forEachRelRelocation (const typename ELFT::Shdr &RelSect, RelocHandlerMethod &&Func)
Traverse all matching ELFT::Rel relocation records in the given section.
Error forEachRelRelocation (const typename ELFT::Shdr &RelSect, ClassT *Instance, RelocHandlerMethod &&Method)
Traverse all matching rel relocation records in the given section.
Protected Member Functions inherited from llvm::jitlink::ELFLinkGraphBuilderBase
Section & getCommonSection ()
Additional Inherited Members
Protected Types inherited from llvm::jitlink::ELFLinkGraphBuilder< ELFType< DataEndianness, false > >
using ELFSectionIndex
using ELFSymbolIndex
Static Protected Member Functions inherited from llvm::jitlink::ELFLinkGraphBuilderBase
static bool isDwarfSection (StringRef SectionName)
Protected Attributes inherited from llvm::jitlink::ELFLinkGraphBuilder< ELFType< DataEndianness, false > >
const ELFFile & Obj
ELFFile::Elf_Shdr_Range Sections
const ELFFile::Elf_Shdr * SymTabSec
StringRef SectionStringTab
bool ProcessDebugSections
DenseMap< ELFSectionIndex, Block * > GraphBlocks
DenseMap< ELFSymbolIndex, Symbol * > GraphSymbols
DenseMap< const typename ELFFile::Elf_Shdr *, ArrayRef< typename ELFFile::Elf_Word > > ShndxTables
Protected Attributes inherited from llvm::jitlink::ELFLinkGraphBuilderBase
std::unique_ptr< LinkGraph > G
Detailed Description
template<support::endianness DataEndianness>
class llvm::jitlink::ELFLinkGraphBuilder_aarch32< DataEndianness >
Definition at line 106 of file ELF_aarch32.cpp.
Constructor & Destructor Documentation
ELFLinkGraphBuilder_aarch32()
template<support::endianness DataEndianness> llvm::jitlink::ELFLinkGraphBuilder_aarch32< DataEndianness >::ELFLinkGraphBuilder_aarch32 (StringRef FileName, const llvm::object::ELFFile< ELFT > & Obj, Triple TT, SubtargetFeatures Features, aarch32::ArmConfig ArmCfg) inline
Definition at line 192 of file ELF_aarch32.cpp.
Member Function Documentation
getRawOffset()
template<support::endianness DataEndianness> orc::ExecutorAddrDiff llvm::jitlink::ELFLinkGraphBuilder_aarch32< DataEndianness >::getRawOffset (const typename ELFT::Sym & Sym, TargetFlagsType Flags) inline override protected
Definition at line 184 of file ELF_aarch32.cpp.
References assert(), llvm::jitlink::ELFLinkGraphBuilder_aarch32< DataEndianness >::makeTargetFlags(), and Sym.
makeTargetFlags()
template<support::endianness DataEndianness> TargetFlagsType llvm::jitlink::ELFLinkGraphBuilder_aarch32< DataEndianness >::makeTargetFlags (const typename ELFT::Sym & Sym) inline override protected
Definition at line 178 of file ELF_aarch32.cpp.
References Sym, and llvm::jitlink::aarch32::ThumbSymbol.
Referenced by llvm::jitlink::ELFLinkGraphBuilder_aarch32< DataEndianness >::getRawOffset().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/JITLink/ELF_aarch32.cpp