LLVM: llvm::InstDeleterIRStrategy Class Reference
llvm::InstDeleterIRStrategy Class Reference
Strategy that deletes instructions when the Module is too large.
#include "llvm/FuzzMutate/IRMutator.h"
Public Member Functions
uint64_t getWeight (size_t CurrentSize, size_t MaxSize, uint64_t CurrentWeight) override
Provide a weight to bias towards choosing this strategy for a mutation.
void mutate (Function &F, RandomIRBuilder &IB) override
void mutate (Instruction &Inst, RandomIRBuilder &IB) override
virtual void mutate (Module &M, RandomIRBuilder &IB)
virtual void mutate (Function &F, RandomIRBuilder &IB)
virtual void mutate (BasicBlock &BB, RandomIRBuilder &IB)
virtual void mutate (Instruction &I, RandomIRBuilder &IB)
Public Member Functions inherited from llvm::IRMutationStrategy
virtual ~IRMutationStrategy ()=default
Detailed Description
Strategy that deletes instructions when the Module is too large.
Definition at line 112 of file IRMutator.h.
Member Function Documentation
getWeight()
uint64_t InstDeleterIRStrategy::getWeight (size_t CurrentSize, size_t MaxSize, uint64_t CurrentWeight) override virtual
Provide a weight to bias towards choosing this strategy for a mutation.
The value of the weight is arbitrary, but a good default is "the number of distinct ways in which this strategy can mutate a unit". This can also be used to prefer strategies that shrink the overall size of the result when we start getting close to MaxSize.
Implements llvm::IRMutationStrategy.
Definition at line 156 of file IRMutator.cpp.
mutate() [1/6]
void IRMutationStrategy::mutate (BasicBlock & BB, RandomIRBuilder & IB) virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 53 of file IRMutator.cpp.
mutate() [2/6]
void IRMutationStrategy::mutate (Function & F, RandomIRBuilder & IB) virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 52 of file IRMutator.cpp.
mutate() [3/6]
void InstDeleterIRStrategy::mutate (Function & F, RandomIRBuilder & IB) override virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 173 of file IRMutator.cpp.
References eliminateDeadCode(), F, instructions, and mutate().
Referenced by mutate().
mutate() [4/6]
virtual void llvm::IRMutationStrategy::mutate (Instruction & I, RandomIRBuilder & IB) inline virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 54 of file IRMutator.h.
mutate() [5/6]
void InstDeleterIRStrategy::mutate (Instruction & Inst, RandomIRBuilder & IB) override virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 192 of file IRMutator.cpp.
References assert(), E, llvm::Instruction::eraseFromParent(), llvm::BasicBlock::getFirstInsertionPt(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Instruction::getParent(), llvm::Value::getType(), I, llvm::Instruction::isTerminator(), llvm::Type::isVoidTy(), llvm::fuzzerop::onlyType(), and llvm::Value::replaceAllUsesWith().
mutate() [6/6]
void IRMutationStrategy::mutate (Module & M, RandomIRBuilder & IB) virtual
Mutators for each IR unit. By default these forward to a contained instance of the next smaller unit.
Reimplemented from llvm::IRMutationStrategy.
Definition at line 51 of file IRMutator.cpp.
The documentation for this class was generated from the following files:
include/llvm/FuzzMutate/IRMutator.h
lib/FuzzMutate/IRMutator.cpp