LLVM: llvm::RecordResolver Class Reference
llvm::RecordResolver Class Reference final
Resolve all variables from a record except for unset variables.
#include "llvm/TableGen/Record.h"
Public Member Functions
RecordResolver (Record &R)
void setName (Init *NewName)
Init * resolve (Init *VarName) override
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
bool keepUnsetBits () const override
Public Member Functions inherited from llvm::Resolver
Resolver (Record *CurRec)
virtual ~Resolver ()=default
Record * getCurrentRecord () const
bool isFinal () const
void setFinal (bool Final)
Detailed Description
Resolve all variables from a record except for unset variables.
Definition at line 2244 of file Record.h.
Constructor & Destructor Documentation
RecordResolver()
llvm::RecordResolver::RecordResolver (Record & R) inline explicit
Definition at line 2250 of file Record.h.
Member Function Documentation
keepUnsetBits()
bool llvm::RecordResolver::keepUnsetBits () const inline override virtual
Reimplemented from llvm::Resolver.
Definition at line 2256 of file Record.h.
resolve()
Init * RecordResolver::resolve (Init * VarName) override virtual
Return the initializer for the given variable name (should normally be a StringInit), or nullptr if the name could not be resolved.
Implements llvm::Resolver.
Definition at line 3210 of file Record.cpp.
References llvm::Resolver::getCurrentRecord(), llvm::is_contained(), and llvm::Init::resolveReferences().
setName()
void llvm::RecordResolver::setName (Init * NewName) inline
Definition at line 2252 of file Record.h.
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp