LLVM: llvm::AddressRange Class Reference
llvm::AddressRange Class Reference
A class that represents an address range.
#include "llvm/ADT/AddressRanges.h"
Public Member Functions
AddressRange ()
AddressRange (uint64_t S, uint64_t E)
uint64_t start () const
uint64_t end () const
uint64_t size () const
uint64_t empty () const
bool contains (uint64_t Addr) const
bool contains (const AddressRange &R) const
bool intersects (const AddressRange &R) const
bool operator== (const AddressRange &R) const
bool operator!= (const AddressRange &R) const
bool operator< (const AddressRange &R) const
Detailed Description
A class that represents an address range.
The range is specified using a start and an end address: [Start, End).
Definition at line 22 of file AddressRanges.h.
Constructor & Destructor Documentation
AddressRange() [1/2]
llvm::AddressRange::AddressRange () inline
Definition at line 24 of file AddressRanges.h.
AddressRange() [2/2]
llvm::AddressRange::AddressRange (uint64_t S, uint64_t E) inline
Definition at line 25 of file AddressRanges.h.
References assert().
Member Function Documentation
contains() [1/2]
bool llvm::AddressRange::contains (const AddressRange & R) const inline
Definition at line 33 of file AddressRanges.h.
contains() [2/2]
bool llvm::AddressRange::contains (uint64_t Addr) const inline
Definition at line 32 of file AddressRanges.h.
References Addr.
Referenced by convertFunctionLineTable(), and llvm::gsym::FunctionInfo::lookup().
empty()
uint64_t llvm::AddressRange::empty () const inline
Definition at line 31 of file AddressRanges.h.
References size().
end()
uint64_t llvm::AddressRange::end () const inline
Definition at line 29 of file AddressRanges.h.
Referenced by llvm::gsym::FunctionInfo::endAddress(), and llvm::AddressRangesBase< T >::find().
intersects()
bool llvm::AddressRange::intersects (const AddressRange & R) const inline
Definition at line 36 of file AddressRanges.h.
operator!=()
bool llvm::AddressRange::operator!= (const AddressRange & R) const inline
Definition at line 42 of file AddressRanges.h.
operator<()
bool llvm::AddressRange::operator< (const AddressRange & R) const inline
Definition at line 43 of file AddressRanges.h.
operator==()
bool llvm::AddressRange::operator== (const AddressRange & R) const inline
Definition at line 39 of file AddressRanges.h.
size()
uint64_t llvm::AddressRange::size () const inline
Definition at line 30 of file AddressRanges.h.
Referenced by empty(), llvm::gsym::FunctionInfo::lookup(), and llvm::gsym::FunctionInfo::size().
start()
uint64_t llvm::AddressRange::start () const inline
Definition at line 28 of file AddressRanges.h.
Referenced by convertFunctionLineTable(), llvm::gsym::FunctionInfo::encode(), and llvm::gsym::FunctionInfo::startAddress().
The documentation for this class was generated from the following file:
include/llvm/ADT/AddressRanges.h