LLVM: llvm::InstModificationIRStrategy Class Reference
llvm::InstModificationIRStrategy Class Reference
Strategy that modifies instruction attributes and operands.
#include "llvm/FuzzMutate/IRMutator.h"
Public Member Functions
uint64_t getWeight (size_t CurrentSize, size_t MaxSize, uint64_t CurrentWeight) override
Provide a weight to bias towards choosing this strategy for a mutation.
void mutate (Instruction &Inst, RandomIRBuilder &IB) override
virtual void mutate (Module &M, RandomIRBuilder &IB)
virtual void mutate (Function &F, RandomIRBuilder &IB)
virtual void mutate (BasicBlock &BB, RandomIRBuilder &IB)
virtual void mutate (Instruction &I, RandomIRBuilder &IB)
Public Member Functions inherited from llvm::IRMutationStrategy
virtual ~IRMutationStrategy ()=default
Detailed Description
Strategy that modifies instruction attributes and operands.
Definition at line 123 of file IRMutator.h.
Member Function Documentation
getWeight()
uint64_t llvm::InstModificationIRStrategy::getWeight (size_t CurrentSize, size_t MaxSize, uint64_t CurrentWeight) inline override virtual
Provide a weight to bias towards choosing this strategy for a mutation.
The value of the weight is arbitrary, but a good default is "the number of distinct ways in which this strategy can mutate a unit". This can also be used to prefer strategies that shrink the overall size of the result when we start getting close to MaxSize.
Implements llvm::IRMutationStrategy.
Definition at line 125 of file IRMutator.h.
mutate() [1/5]
void IRMutationStrategy::mutate (BasicBlock & BB, RandomIRBuilder & IB) virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 53 of file IRMutator.cpp.
mutate() [2/5]
void IRMutationStrategy::mutate (Function & F, RandomIRBuilder & IB) virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 52 of file IRMutator.cpp.
mutate() [3/5]
virtual void llvm::IRMutationStrategy::mutate (Instruction & I, RandomIRBuilder & IB) inline virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 54 of file IRMutator.h.
mutate() [4/5]
void InstModificationIRStrategy::mutate (Instruction & Inst, RandomIRBuilder & IB) override virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 221 of file IRMutator.cpp.
References llvm::FastMathFlags::all(), llvm::CallingConv::C, llvm::CmpInst::FIRST_FCMP_PREDICATE, llvm::CmpInst::FIRST_ICMP_PREDICATE, GEP, llvm::Instruction::getFastMathFlags(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::hasAllowContract(), llvm::Instruction::hasAllowReassoc(), llvm::Instruction::hasAllowReciprocal(), llvm::Instruction::hasApproxFunc(), llvm::Instruction::hasNoInfs(), llvm::Instruction::hasNoNaNs(), llvm::Instruction::hasNoSignedWrap(), llvm::Instruction::hasNoSignedZeros(), llvm::Instruction::hasNoUnsignedWrap(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::Instruction::isExact(), llvm::CmpInst::LAST_FCMP_PREDICATE, llvm::CmpInst::LAST_ICMP_PREDICATE, llvm::makeSampler(), llvm::FastMathFlags::none(), llvm::Instruction::setFast(), llvm::Instruction::setHasAllowContract(), llvm::Instruction::setHasAllowReassoc(), llvm::Instruction::setHasAllowReciprocal(), llvm::Instruction::setHasApproxFunc(), llvm::Instruction::setHasNoInfs(), llvm::Instruction::setHasNoNaNs(), llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setHasNoSignedZeros(), llvm::Instruction::setHasNoUnsignedWrap(), llvm::Instruction::setIsExact(), llvm::User::setOperand(), and llvm::CmpInst::setPredicate().
mutate() [5/5]
void IRMutationStrategy::mutate (Module & M, RandomIRBuilder & IB) virtual
Mutators for each IR unit. By default these forward to a contained instance of the next smaller unit.
Reimplemented from llvm::IRMutationStrategy.
Definition at line 51 of file IRMutator.cpp.
The documentation for this class was generated from the following files:
include/llvm/FuzzMutate/IRMutator.h
lib/FuzzMutate/IRMutator.cpp