LLVM: llvm::DwarfStreamer Class Reference
llvm::DwarfStreamer Class Reference
The Dwarf streaming logic.
#include "llvm/DWARFLinker/DWARFStreamer.h"
Public Member Functions
DwarfStreamer (DWARFLinker::OutputFileType OutFileType, raw_pwrite_stream &OutFile, std::function< StringRef(StringRef Input)> Translator, DWARFLinker::messageHandler Warning)
Error init (Triple TheTriple, StringRef Swift5ReflectionSegmentName)
void finish () override
Dump the file to the disk.
AsmPrinter & getAsmPrinter () const override
Returns underlying AsmPrinter.
void switchToDebugInfoSection (unsigned DwarfVersion)
Set the current output section to debug_info and change the MC Dwarf version to DwarfVersion.
void emitCompileUnitHeader (CompileUnit &Unit, unsigned DwarfVersion) override
Emit the compilation unit header for Unit in the debug_info section.
void emitDIE (DIE &Die) override
Recursively emit the DIE tree rooted at Die.
void emitAbbrevs (const std::vector< std::unique_ptr< DIEAbbrev > > &Abbrevs, unsigned DwarfVersion) override
Emit the abbreviation table Abbrevs to the debug_abbrev section.
void emitPaperTrailWarningsDie (DIE &Die) override
Emit DIE containing warnings.
void emitSectionContents (StringRef SecData, StringRef SecName) override
Emit contents of section SecName From Obj.
void emitStrings (const NonRelocatableStringpool &Pool) override
Emit the string table described by Pool into .debug_str table.
void emitLineStrings (const NonRelocatableStringpool &Pool) override
Emit the string table described by Pool into .debug_line_str table.
void emitSwiftAST (StringRef Buffer) override
Emit the swift_ast section stored in Buffer.
void emitSwiftReflectionSection (llvm::binaryformat::Swift5ReflectionSectionKind ReflSectionKind, StringRef Buffer, uint32_t Alignment, uint32_t Size) override
Emit the swift reflection section stored in Buffer.
MCSymbol * emitDwarfDebugRangeListHeader (const CompileUnit &Unit) override
Emit debug ranges(.debug_ranges, .debug_rnglists) header.
void emitDwarfDebugRangeListFragment (const CompileUnit &Unit, const AddressRanges &LinkedRanges, PatchLocation Patch) override
Emit debug ranges(.debug_ranges, .debug_rnglists) fragment.
void emitDwarfDebugRangeListFooter (const CompileUnit &Unit, MCSymbol *EndLabel) override
Emit debug ranges(.debug_ranges, .debug_rnglists) footer.
MCSymbol * emitDwarfDebugLocListHeader (const CompileUnit &Unit) override
Emit debug locations(.debug_loc, .debug_loclists) header.
MCSymbol * emitDwarfDebugAddrsHeader (const CompileUnit &Unit) override
Emit .debug_addr header.
void emitDwarfDebugAddrs (const SmallVector< uint64_t > &Addrs, uint8_t AddrSize) override
Emit the addresses described by Addrs into .debug_addr table.
void emitDwarfDebugAddrsFooter (const CompileUnit &Unit, MCSymbol *EndLabel) override
Emit .debug_addr footer.
void emitDwarfDebugLocListFragment (const CompileUnit &Unit, const DWARFLocationExpressionsVector &LinkedLocationExpression, PatchLocation Patch, DebugAddrPool &AddrPool) override
Emit debug ranges(.debug_loc, .debug_loclists) fragment.
void emitDwarfDebugLocListFooter (const CompileUnit &Unit, MCSymbol *EndLabel) override
Emit debug ranges(.debug_loc, .debug_loclists) footer.
void emitDwarfDebugArangesTable (const CompileUnit &Unit, const AddressRanges &LinkedRanges) override
Emit .debug_aranges entries for Unit.
uint64_t getRangesSectionSize () const override
Returns size of generated .debug_ranges section.
uint64_t getRngListsSectionSize () const override
Returns size of generated .debug_rnglists section.
void emitLineTableForUnit (const DWARFDebugLine::LineTable &LineTable, const CompileUnit &Unit, OffsetsStringPool &DebugStrPool, OffsetsStringPool &DebugLineStrPool) override
Emit .debug_line table entry for specified LineTable.
uint64_t getLineSectionSize () const override
Returns size of generated .debug_line section.
void emitPubNamesForUnit (const CompileUnit &Unit) override
Emit the .debug_pubnames contribution for Unit.
void emitPubTypesForUnit (const CompileUnit &Unit) override
Emit the .debug_pubtypes contribution for Unit.
void emitCIE (StringRef CIEBytes) override
Emit a CIE.
void emitFDE (uint32_t CIEOffset, uint32_t AddreSize, uint64_t Address, StringRef Bytes) override
Emit an FDE with data Bytes.
void emitDebugNames (AccelTable< DWARF5AccelTableStaticData > &Table) override
Emit DWARF debug names.
void emitAppleNamespaces (AccelTable< AppleAccelTableStaticOffsetData > &Table) override
Emit Apple namespaces accelerator table.
void emitAppleNames (AccelTable< AppleAccelTableStaticOffsetData > &Table) override
Emit Apple names accelerator table.
void emitAppleObjc (AccelTable< AppleAccelTableStaticOffsetData > &Table) override
Emit Apple Objective-C accelerator table.
void emitAppleTypes (AccelTable< AppleAccelTableStaticTypeData > &Table) override
Emit Apple type accelerator table.
uint64_t getFrameSectionSize () const override
Returns size of generated .debug_frame section.
uint64_t getDebugInfoSectionSize () const override
Returns size of generated .debug_info section.
uint64_t getDebugMacInfoSectionSize () const override
Returns size of generated .debug_macinfo section.
uint64_t getDebugMacroSectionSize () const override
Returns size of generated .debug_macro section.
uint64_t getLocListsSectionSize () const override
Returns size of generated .debug_loclists section.
uint64_t getDebugAddrSectionSize () const override
Returns size of generated .debug_addr section.
void emitMacroTables (DWARFContext *Context, const Offset2UnitMap &UnitMacroMap, OffsetsStringPool &StringPool) override
Emit all available macro tables(DWARFv4 and DWARFv5).
Public Member Functions inherited from llvm::DwarfEmitter
virtual ~DwarfEmitter ()
Detailed Description
The Dwarf streaming logic.
All interactions with the MC layer that is used to build the debug information binary representation are handled in this class.
Definition at line 41 of file DWARFStreamer.h.
Constructor & Destructor Documentation
DwarfStreamer()
llvm::DwarfStreamer::DwarfStreamer (DWARFLinker::OutputFileType OutFileType, raw_pwrite_stream & OutFile, std::function< StringRef(StringRef Input)> Translator, DWARFLinker::messageHandler Warning) inline
Definition at line 43 of file DWARFStreamer.h.
Member Function Documentation
emitAbbrevs()
void llvm::DwarfStreamer::emitAbbrevs (const std::vector< std::unique_ptr< DIEAbbrev > > & Abbrevs, unsigned DwarfVersion) override virtual
Emit the abbreviation table Abbrevs to the debug_abbrev section.
Emit the Abbrevs array as the shared abbreviation table for the linked Dwarf file.
Implements llvm::DwarfEmitter.
Definition at line 197 of file DWARFStreamer.cpp.
References llvm::MCStreamer::switchSection().
emitAppleNames()
void llvm::DwarfStreamer::emitAppleNames (AccelTable< AppleAccelTableStaticOffsetData > & Table) override virtual
Emit Apple names accelerator table.
Implements llvm::DwarfEmitter.
Definition at line 304 of file DWARFStreamer.cpp.
References llvm::emitAppleAccelTable().
emitAppleNamespaces()
void llvm::DwarfStreamer::emitAppleNamespaces (AccelTable< AppleAccelTableStaticOffsetData > & Table) override virtual
Emit Apple namespaces accelerator table.
Implements llvm::DwarfEmitter.
Definition at line 296 of file DWARFStreamer.cpp.
References llvm::emitAppleAccelTable().
emitAppleObjc()
void llvm::DwarfStreamer::emitAppleObjc (AccelTable< AppleAccelTableStaticOffsetData > & Table) override virtual
Emit Apple Objective-C accelerator table.
Implements llvm::DwarfEmitter.
Definition at line 312 of file DWARFStreamer.cpp.
References llvm::emitAppleAccelTable().
emitAppleTypes()
void llvm::DwarfStreamer::emitAppleTypes (AccelTable< AppleAccelTableStaticTypeData > & Table) override virtual
Emit Apple type accelerator table.
Implements llvm::DwarfEmitter.
Definition at line 320 of file DWARFStreamer.cpp.
References llvm::emitAppleAccelTable().
emitCIE()
void llvm::DwarfStreamer::emitCIE (StringRef CIEBytes) override virtual
Emit a CIE.
Emit a CIE into the debug_frame section.
Implements llvm::DwarfEmitter.
Definition at line 1129 of file DWARFStreamer.cpp.
References llvm::MCStreamer::emitBytes(), and llvm::MCStreamer::switchSection().
emitCompileUnitHeader()
void llvm::DwarfStreamer::emitCompileUnitHeader (CompileUnit & Unit, unsigned DwarfVersion) override virtual
Emit the compilation unit header for Unit in the debug_info section.
As a side effect, this also switches the current Dwarf version of the MC layer to the one of U.getOrigUnit().
A Dwarf 4 section header is encoded as: uint32_t Unit length (omitting this field) uint16_t Version uint32_t Abbreviation table offset uint8_t Address size Leading to a total of 11 bytes.
A Dwarf 5 section header is encoded as: uint32_t Unit length (omitting this field) uint16_t Version uint8_t Unit type uint8_t Address size uint32_t Abbreviation table offset Leading to a total of 12 bytes.
The start of the unit within its section.
Implements llvm::DwarfEmitter.
Definition at line 162 of file DWARFStreamer.cpp.
References switchToDebugInfoSection().
emitDebugNames()
void llvm::DwarfStreamer::emitDebugNames (AccelTable< DWARF5AccelTableStaticData > & Table) override virtual
Emit DWARF debug names.
Implements llvm::DwarfEmitter.
Definition at line 273 of file DWARFStreamer.cpp.
References llvm::emitDWARF5AccelTable().
emitDIE()
void llvm::DwarfStreamer::emitDIE (DIE & Die) override virtual
Recursively emit the DIE tree rooted at Die.
Implements llvm::DwarfEmitter.
Definition at line 206 of file DWARFStreamer.cpp.
References llvm::DIE::getSize(), and llvm::MCStreamer::switchSection().
Referenced by emitPaperTrailWarningsDie().
emitDwarfDebugAddrs()
void llvm::DwarfStreamer::emitDwarfDebugAddrs (const SmallVector< uint64_t > & Addrs, uint8_t AddrSize) override virtual
Emit the addresses described by Addrs into .debug_addr table.
Emit the .debug_addr addresses stored in Addrs.
Implements llvm::DwarfEmitter.
Definition at line 641 of file DWARFStreamer.cpp.
References Addr.
emitDwarfDebugAddrsFooter()
void llvm::DwarfStreamer::emitDwarfDebugAddrsFooter (const CompileUnit & Unit, MCSymbol * EndLabel) override virtual
Emit .debug_addr footer.
Implements llvm::DwarfEmitter.
Definition at line 651 of file DWARFStreamer.cpp.
References llvm::MCStreamer::switchSection().
emitDwarfDebugAddrsHeader()
MCSymbol * llvm::DwarfStreamer::emitDwarfDebugAddrsHeader (const CompileUnit & Unit) override virtual
Emit .debug_addr header.
Implements llvm::DwarfEmitter.
Definition at line 611 of file DWARFStreamer.cpp.
References llvm::MCStreamer::switchSection().
emitDwarfDebugArangesTable()
void llvm::DwarfStreamer::emitDwarfDebugArangesTable (const CompileUnit & Unit, const AddressRanges & LinkedRanges) override virtual
Emit .debug_aranges entries for Unit.
Implements llvm::DwarfEmitter.
Definition at line 348 of file DWARFStreamer.cpp.
References Align, llvm::dwarf::DW_ARANGES_VERSION, llvm::MCStreamer::emitIntValue(), llvm::offsetToAlignment(), and llvm::MCStreamer::switchSection().
emitDwarfDebugLocListFooter()
void llvm::DwarfStreamer::emitDwarfDebugLocListFooter (const CompileUnit & Unit, MCSymbol * EndLabel) override virtual
Emit debug ranges(.debug_loc, .debug_loclists) footer.
Emit debug locations(.debug_loc, .debug_loclists) footer.
Implements llvm::DwarfEmitter.
Definition at line 558 of file DWARFStreamer.cpp.
References llvm::MCStreamer::switchSection().
emitDwarfDebugLocListFragment()
void llvm::DwarfStreamer::emitDwarfDebugLocListFragment (const CompileUnit & Unit, const DWARFLocationExpressionsVector & LinkedLocationExpression, PatchLocation Patch, DebugAddrPool & AddrPool) override virtual
Emit debug ranges(.debug_loc, .debug_loclists) fragment.
Emit debug locations(.debug_loc, .debug_loclists) fragment.
Implements llvm::DwarfEmitter.
Definition at line 544 of file DWARFStreamer.cpp.
emitDwarfDebugLocListHeader()
MCSymbol * llvm::DwarfStreamer::emitDwarfDebugLocListHeader (const CompileUnit & Unit) override virtual
Emit debug locations(.debug_loc, .debug_loclists) header.
Implements llvm::DwarfEmitter.
Definition at line 508 of file DWARFStreamer.cpp.
References llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), and llvm::MCStreamer::switchSection().
emitDwarfDebugRangeListFooter()
void llvm::DwarfStreamer::emitDwarfDebugRangeListFooter (const CompileUnit & Unit, MCSymbol * EndLabel) override virtual
Emit debug ranges(.debug_ranges, .debug_rnglists) footer.
Implements llvm::DwarfEmitter.
Definition at line 467 of file DWARFStreamer.cpp.
References llvm::MCStreamer::switchSection().
emitDwarfDebugRangeListFragment()
void llvm::DwarfStreamer::emitDwarfDebugRangeListFragment (const CompileUnit & Unit, const AddressRanges & LinkedRanges, PatchLocation Patch) override virtual
Emit debug ranges(.debug_ranges, .debug_rnglists) fragment.
Implements llvm::DwarfEmitter.
Definition at line 456 of file DWARFStreamer.cpp.
emitDwarfDebugRangeListHeader()
MCSymbol * llvm::DwarfStreamer::emitDwarfDebugRangeListHeader (const CompileUnit & Unit) override virtual
Emit debug ranges(.debug_ranges, .debug_rnglists) header.
Implements llvm::DwarfEmitter.
Definition at line 421 of file DWARFStreamer.cpp.
References llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), and llvm::MCStreamer::switchSection().
emitFDE()
void llvm::DwarfStreamer::emitFDE (uint32_t CIEOffset, uint32_t AddrSize, uint64_t Address, StringRef FDEBytes) override virtual
Emit an FDE with data Bytes.
Emit a FDE into the debug_frame section.
FDEBytes contains the FDE data without the length, CIE offset and address which will be replaced with the parameter values.
Implements llvm::DwarfEmitter.
Definition at line 1139 of file DWARFStreamer.cpp.
References llvm::MCStreamer::emitBytes(), llvm::MCStreamer::emitIntValue(), and llvm::MCStreamer::switchSection().
emitLineStrings()
void llvm::DwarfStreamer::emitLineStrings (const NonRelocatableStringpool & Pool) override virtual
Emit the string table described by Pool into .debug_line_str table.
Emit the debug_line_str section stored in Pool.
Implements llvm::DwarfEmitter.
Definition at line 262 of file DWARFStreamer.cpp.
References llvm::NonRelocatableStringpool::getEntriesForEmission().
emitLineTableForUnit()
void llvm::DwarfStreamer::emitLineTableForUnit (const DWARFDebugLine::LineTable & LineTable, const CompileUnit & Unit, OffsetsStringPool & DebugStrPool, OffsetsStringPool & DebugLineStrPool) override virtual
Emit .debug_line table entry for specified LineTable.
Implements llvm::DwarfEmitter.
Definition at line 715 of file DWARFStreamer.cpp.
References llvm::dwarf::DW_LENGTH_DWARF64, llvm::dwarf::DWARF64, llvm::MCStreamer::emitInt32(), llvm::DWARFDebugLine::LineTable::Prologue, and llvm::MCStreamer::switchSection().
emitMacroTables()
void llvm::DwarfStreamer::emitMacroTables (DWARFContext * Context, const Offset2UnitMap & UnitMacroMap, OffsetsStringPool & StringPool) override virtual
Emit all available macro tables(DWARFv4 and DWARFv5).
Use UnitMacroMap to get compilation unit by macro table offset. Side effects: Fill StringPool with macro strings, update DW_AT_macro_info, DW_AT_macros attributes for corresponding compile units.
Implements llvm::DwarfEmitter.
Definition at line 1150 of file DWARFStreamer.cpp.
References assert(), and llvm::MCStreamer::switchSection().
emitPaperTrailWarningsDie()
void llvm::DwarfStreamer::emitPaperTrailWarningsDie (DIE & Die) override virtual
Emit DIE containing warnings.
Implements llvm::DwarfEmitter.
Definition at line 238 of file DWARFStreamer.cpp.
References emitDIE(), getAsmPrinter(), llvm::DIE::getSize(), and switchToDebugInfoSection().
emitPubNamesForUnit()
void llvm::DwarfStreamer::emitPubNamesForUnit (const CompileUnit & Unit) override virtual
Emit the .debug_pubnames contribution for Unit.
Emit .debug_pubnames for Unit.
Implements llvm::DwarfEmitter.
Definition at line 1117 of file DWARFStreamer.cpp.
emitPubTypesForUnit()
void llvm::DwarfStreamer::emitPubTypesForUnit (const CompileUnit & Unit) override virtual
Emit the .debug_pubtypes contribution for Unit.
Emit .debug_pubtypes for Unit.
Implements llvm::DwarfEmitter.
Definition at line 1123 of file DWARFStreamer.cpp.
emitSectionContents()
void llvm::DwarfStreamer::emitSectionContents (StringRef SecData, StringRef SecName) override virtual
Emit contents of section SecName From Obj.
Implements llvm::DwarfEmitter.
Definition at line 213 of file DWARFStreamer.cpp.
References llvm::MCStreamer::emitBytes(), and llvm::MCStreamer::switchSection().
emitStrings()
void llvm::DwarfStreamer::emitStrings (const NonRelocatableStringpool & Pool) override virtual
Emit the string table described by Pool into .debug_str table.
Emit the debug_str section stored in Pool.
Implements llvm::DwarfEmitter.
Definition at line 250 of file DWARFStreamer.cpp.
References llvm::NonRelocatableStringpool::getEntriesForEmission().
emitSwiftAST()
void llvm::DwarfStreamer::emitSwiftAST (StringRef Buffer) override virtual
Emit the swift_ast section stored in Buffer.
Emit the swift_ast section stored in Buffers.
Implements llvm::DwarfEmitter.
Definition at line 329 of file DWARFStreamer.cpp.
References Align, llvm::MCStreamer::emitBytes(), and llvm::MCStreamer::switchSection().
emitSwiftReflectionSection()
void llvm::DwarfStreamer::emitSwiftReflectionSection (llvm::binaryformat::Swift5ReflectionSectionKind ReflSectionKind, StringRef Buffer, uint32_t Alignment, uint32_t Size) override virtual
Emit the swift reflection section stored in Buffer.
Implements llvm::DwarfEmitter.
Definition at line 336 of file DWARFStreamer.cpp.
References Align, llvm::MCStreamer::emitBytes(), and llvm::MCStreamer::switchSection().
finish()
void llvm::DwarfStreamer::finish () override virtual
Dump the file to the disk.
Implements llvm::DwarfEmitter.
Definition at line 139 of file DWARFStreamer.cpp.
References llvm::MCStreamer::finish().
getAsmPrinter()
AsmPrinter & llvm::DwarfStreamer::getAsmPrinter () const inline override virtual
Returns underlying AsmPrinter.
Implements llvm::DwarfEmitter.
Definition at line 55 of file DWARFStreamer.h.
Referenced by emitPaperTrailWarningsDie().
getDebugAddrSectionSize()
uint64_t llvm::DwarfStreamer::getDebugAddrSectionSize () const inline override virtual
Returns size of generated .debug_addr section.
Implements llvm::DwarfEmitter.
Definition at line 199 of file DWARFStreamer.h.
getDebugInfoSectionSize()
uint64_t llvm::DwarfStreamer::getDebugInfoSectionSize () const inline override virtual
Returns size of generated .debug_info section.
Implements llvm::DwarfEmitter.
Definition at line 183 of file DWARFStreamer.h.
getDebugMacInfoSectionSize()
uint64_t llvm::DwarfStreamer::getDebugMacInfoSectionSize () const inline override virtual
Returns size of generated .debug_macinfo section.
Implements llvm::DwarfEmitter.
Definition at line 187 of file DWARFStreamer.h.
getDebugMacroSectionSize()
uint64_t llvm::DwarfStreamer::getDebugMacroSectionSize () const inline override virtual
Returns size of generated .debug_macro section.
Implements llvm::DwarfEmitter.
Definition at line 191 of file DWARFStreamer.h.
getFrameSectionSize()
uint64_t llvm::DwarfStreamer::getFrameSectionSize () const inline override virtual
Returns size of generated .debug_frame section.
Implements llvm::DwarfEmitter.
Definition at line 181 of file DWARFStreamer.h.
getLineSectionSize()
uint64_t llvm::DwarfStreamer::getLineSectionSize () const inline override virtual
Returns size of generated .debug_line section.
Implements llvm::DwarfEmitter.
Definition at line 147 of file DWARFStreamer.h.
getLocListsSectionSize()
uint64_t llvm::DwarfStreamer::getLocListsSectionSize () const inline override virtual
Returns size of generated .debug_loclists section.
Implements llvm::DwarfEmitter.
Definition at line 195 of file DWARFStreamer.h.
getRangesSectionSize()
uint64_t llvm::DwarfStreamer::getRangesSectionSize () const inline override virtual
Returns size of generated .debug_ranges section.
Implements llvm::DwarfEmitter.
Definition at line 135 of file DWARFStreamer.h.
getRngListsSectionSize()
uint64_t llvm::DwarfStreamer::getRngListsSectionSize () const inline override virtual
Returns size of generated .debug_rnglists section.
Implements llvm::DwarfEmitter.
Definition at line 137 of file DWARFStreamer.h.
init()
Error llvm::DwarfStreamer::init (Triple TheTriple, StringRef Swift5ReflectionSegmentName)
Definition at line 31 of file DWARFStreamer.cpp.
References llvm::DWARFLinker::Assembly, llvm::Target::createAsmPrinter(), llvm::Target::createAsmStreamer(), llvm::Target::createMCAsmBackend(), llvm::Target::createMCAsmInfo(), llvm::Target::createMCCodeEmitter(), llvm::Target::createMCInstPrinter(), llvm::Target::createMCInstrInfo(), llvm::Target::createMCObjectFileInfo(), llvm::Target::createMCObjectStreamer(), llvm::Target::createMCRegInfo(), llvm::Target::createMCSubtargetInfo(), llvm::MCAsmBackend::createObjectWriter(), llvm::createStringError(), llvm::Target::createTargetMachine(), llvm::Triple::getTriple(), llvm::mc::InitMCTargetOptionsFromFlags(), llvm::TargetRegistry::lookupTarget(), llvm::MCTargetOptions::MCIncrementalLinkerCompatible, llvm::MCTargetOptions::MCRelaxAll, llvm::DWARFLinker::Object, and llvm::Error::success().
switchToDebugInfoSection()
void llvm::DwarfStreamer::switchToDebugInfoSection (unsigned DwarfVersion)
Set the current output section to debug_info and change the MC Dwarf version to DwarfVersion.
Definition at line 141 of file DWARFStreamer.cpp.
References llvm::MCStreamer::switchSection().
Referenced by emitCompileUnitHeader(), and emitPaperTrailWarningsDie().
The documentation for this class was generated from the following files:
include/llvm/DWARFLinker/DWARFStreamer.h
lib/DWARFLinker/DWARFStreamer.cpp