LLVM: llvm::dwarflinker_parallel::DwarfEmitterImpl Class Reference
llvm::dwarflinker_parallel::DwarfEmitterImpl Class Reference
The Dwarf emission logic.
#include "DWARFLinkerParallel/DWARFEmitterImpl.h"
Public Member Functions
DwarfEmitterImpl (DWARFLinker::OutputFileType OutFileType, raw_pwrite_stream &OutFile, std::function< StringRef(StringRef Input)> Translator, DWARFLinker::MessageHandlerTy Warning)
Error init (Triple TheTriple, StringRef Swift5ReflectionSegmentName)
void finish () override
Dump the file to the disk.
AsmPrinter & getAsmPrinter () const override
Returns underlying AsmPrinter.
void switchToDebugInfoSection (unsigned DwarfVersion)
Set the current output section to debug_info and change the MC Dwarf version to DwarfVersion.
void emitSwiftAST (StringRef Buffer) override
Emit the swift_ast section stored in Buffer.
void emitSwiftReflectionSection (llvm::binaryformat::Swift5ReflectionSectionKind ReflSectionKind, StringRef Buffer, uint32_t Alignment, uint32_t Size) override
Emit the swift reflection section stored in Buffer.
void emitPaperTrailWarningsDie (DIE &Die)
void emitSectionContents (StringRef SecData, StringRef SecName) override
Emit section named SecName with data SecData.
MCSymbol * emitTempSym (StringRef SecName, StringRef SymName) override
Emit temporarily symbol named SymName inside section SecName.
void emitAbbrevs (const SmallVector< std::unique_ptr< DIEAbbrev > > &Abbrevs, unsigned DwarfVersion)
void emitStrings (const StringTable &Strings)
void emitLineStrings (const StringTable &Strings)
void emitDebugNames (AccelTable< DWARF5AccelTableStaticData > &, UnitStartSymbolsTy &UnitOffsets)
void emitAppleNamespaces (AccelTable< AppleAccelTableStaticOffsetData > &)
void emitAppleNames (AccelTable< AppleAccelTableStaticOffsetData > &)
void emitAppleObjc (AccelTable< AppleAccelTableStaticOffsetData > &)
void emitAppleTypes (AccelTable< AppleAccelTableStaticTypeData > &)
MCSymbol * emitDwarfDebugRangeListHeader (const CompileUnit &Unit)
void emitDwarfDebugRangeListFragment (const CompileUnit &Unit, const AddressRanges &LinkedRanges, RangeAttrPatch &Patch)
void emitDwarfDebugRangeListFooter (const CompileUnit &Unit, MCSymbol *EndLabel)
MCSymbol * emitDwarfDebugLocListHeader (const CompileUnit &Unit)
void emitDwarfDebugLocListFragment (const CompileUnit &Unit, const DWARFLocationExpressionsVector &LinkedLocationExpression, LocAttrPatch &Patch)
void emitDwarfDebugLocListFooter (const CompileUnit &Unit, MCSymbol *EndLabel)
void emitDwarfDebugArangesTable (const CompileUnit &Unit, const AddressRanges &LinkedRanges)
void translateLineTable (DataExtractor LineData, uint64_t Offset)
void emitLineTableForUnit (MCDwarfLineTableParams Params, StringRef PrologueBytes, unsigned MinInstLength, std::vector< DWARFDebugLine::Row > &Rows, unsigned AdddressSize)
void emitLineTableForUnit (const DWARFDebugLine::LineTable &LineTable, const CompileUnit &Unit, const StringTable &Strings, const StringTable &LineTableStrings)
void emitPubNamesForUnit (const CompileUnit &Unit)
void emitPubTypesForUnit (const CompileUnit &Unit)
void emitCIE (StringRef CIEBytes)
void emitFDE (uint32_t CIEOffset, uint32_t AddreSize, uint64_t Address, StringRef Bytes)
void emitCompileUnitHeader (CompileUnit &Unit, unsigned DwarfVersion)
void emitDIE (DIE &Die)
void emitMacroTables (DWARFContext *Context, const Offset2UnitMapTy &UnitMacroMap, StringTable &Strings)
uint64_t getDebugLineSectionSize () const
Returns size of generated .debug_line section.
uint64_t getDebugFrameSectionSize () const
Returns size of generated .debug_frame section.
uint64_t getDebugRangesSectionSize () const
Returns size of generated .debug_ranges section.
uint64_t getDebugRngListsSectionSize () const
Returns size of generated .debug_rnglists section.
uint64_t getDebugInfoSectionSize () const
Returns size of generated .debug_info section.
uint64_t getDebugMacInfoSectionSize () const
Returns size of generated .debug_macinfo section.
uint64_t getDebugMacroSectionSize () const
Returns size of generated .debug_macro section.
uint64_t getDebugLocSectionSize () const
Returns size of generated .debug_loc section.
uint64_t getDebugLocListsSectionSize () const
Returns size of generated .debug_loclists section.
Public Member Functions inherited from llvm::dwarflinker_parallel::ExtraDwarfEmitter
virtual ~ExtraDwarfEmitter ()=default
Detailed Description
The Dwarf emission logic.
All interactions with the MC layer that is used to build the debug information binary representation are handled in this class.
Definition at line 57 of file DWARFEmitterImpl.h.
Constructor & Destructor Documentation
DwarfEmitterImpl()
llvm::dwarflinker_parallel::DwarfEmitterImpl::DwarfEmitterImpl (DWARFLinker::OutputFileType OutFileType, raw_pwrite_stream & OutFile, std::function< StringRef(StringRef Input)> Translator, DWARFLinker::MessageHandlerTy Warning) inline
Definition at line 59 of file DWARFEmitterImpl.h.
Member Function Documentation
emitAbbrevs()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitAbbrevs (const SmallVector< std::unique_ptr< DIEAbbrev > > & Abbrevs, unsigned DwarfVersion) inline
Definition at line 93 of file DWARFEmitterImpl.h.
emitAppleNames()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitAppleNames (AccelTable< AppleAccelTableStaticOffsetData > &) inline
Definition at line 105 of file DWARFEmitterImpl.h.
emitAppleNamespaces()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitAppleNamespaces (AccelTable< AppleAccelTableStaticOffsetData > &) inline
Definition at line 103 of file DWARFEmitterImpl.h.
emitAppleObjc()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitAppleObjc (AccelTable< AppleAccelTableStaticOffsetData > &) inline
Definition at line 107 of file DWARFEmitterImpl.h.
emitAppleTypes()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitAppleTypes (AccelTable< AppleAccelTableStaticTypeData > &) inline
Definition at line 109 of file DWARFEmitterImpl.h.
emitCIE()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitCIE (StringRef CIEBytes) inline
Definition at line 152 of file DWARFEmitterImpl.h.
emitCompileUnitHeader()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitCompileUnitHeader (CompileUnit & Unit, unsigned DwarfVersion) inline
Definition at line 157 of file DWARFEmitterImpl.h.
emitDebugNames()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitDebugNames (AccelTable< DWARF5AccelTableStaticData > & , UnitStartSymbolsTy & UnitOffsets) inline
Definition at line 100 of file DWARFEmitterImpl.h.
emitDIE()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitDIE (DIE & Die) inline
Definition at line 159 of file DWARFEmitterImpl.h.
emitDwarfDebugArangesTable()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitDwarfDebugArangesTable (const CompileUnit & Unit, const AddressRanges & LinkedRanges) inline
Definition at line 134 of file DWARFEmitterImpl.h.
emitDwarfDebugLocListFooter()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitDwarfDebugLocListFooter (const CompileUnit & Unit, MCSymbol * EndLabel) inline
Definition at line 131 of file DWARFEmitterImpl.h.
emitDwarfDebugLocListFragment()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitDwarfDebugLocListFragment (const CompileUnit & Unit, const DWARFLocationExpressionsVector & LinkedLocationExpression, LocAttrPatch & Patch) inline
Definition at line 126 of file DWARFEmitterImpl.h.
emitDwarfDebugLocListHeader()
MCSymbol * llvm::dwarflinker_parallel::DwarfEmitterImpl::emitDwarfDebugLocListHeader (const CompileUnit & Unit) inline
Definition at line 122 of file DWARFEmitterImpl.h.
emitDwarfDebugRangeListFooter()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitDwarfDebugRangeListFooter (const CompileUnit & Unit, MCSymbol * EndLabel) inline
Definition at line 119 of file DWARFEmitterImpl.h.
emitDwarfDebugRangeListFragment()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitDwarfDebugRangeListFragment (const CompileUnit & Unit, const AddressRanges & LinkedRanges, RangeAttrPatch & Patch) inline
Definition at line 115 of file DWARFEmitterImpl.h.
emitDwarfDebugRangeListHeader()
MCSymbol * llvm::dwarflinker_parallel::DwarfEmitterImpl::emitDwarfDebugRangeListHeader (const CompileUnit & Unit) inline
Definition at line 111 of file DWARFEmitterImpl.h.
emitFDE()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitFDE (uint32_t CIEOffset, uint32_t AddreSize, uint64_t Address, StringRef Bytes) inline
Definition at line 154 of file DWARFEmitterImpl.h.
emitLineStrings()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitLineStrings (const StringTable & Strings) inline
Definition at line 98 of file DWARFEmitterImpl.h.
emitLineTableForUnit() [1/2]
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitLineTableForUnit (const DWARFDebugLine::LineTable & LineTable, const CompileUnit & Unit, const StringTable & Strings, const StringTable & LineTableStrings) inline
Definition at line 144 of file DWARFEmitterImpl.h.
emitLineTableForUnit() [2/2]
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitLineTableForUnit (MCDwarfLineTableParams Params, StringRef PrologueBytes, unsigned MinInstLength, std::vector< DWARFDebugLine::Row > & Rows, unsigned AdddressSize) inline
Definition at line 139 of file DWARFEmitterImpl.h.
emitMacroTables()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitMacroTables (DWARFContext * Context, const Offset2UnitMapTy & UnitMacroMap, StringTable & Strings) inline
Definition at line 161 of file DWARFEmitterImpl.h.
emitPaperTrailWarningsDie()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitPaperTrailWarningsDie (DIE & Die) inline
Definition at line 85 of file DWARFEmitterImpl.h.
emitPubNamesForUnit()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitPubNamesForUnit (const CompileUnit & Unit) inline
Definition at line 148 of file DWARFEmitterImpl.h.
emitPubTypesForUnit()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitPubTypesForUnit (const CompileUnit & Unit) inline
Definition at line 150 of file DWARFEmitterImpl.h.
emitSectionContents()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitSectionContents (StringRef SecData, StringRef SecName) inline override virtual
Emit section named SecName with data SecData.
Implements llvm::dwarflinker_parallel::ExtraDwarfEmitter.
Definition at line 87 of file DWARFEmitterImpl.h.
emitStrings()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitStrings (const StringTable & Strings) inline
Definition at line 96 of file DWARFEmitterImpl.h.
emitSwiftAST()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitSwiftAST (StringRef Buffer) inline override virtual
Emit the swift_ast section stored in Buffer.
Implements llvm::dwarflinker_parallel::ExtraDwarfEmitter.
Definition at line 78 of file DWARFEmitterImpl.h.
emitSwiftReflectionSection()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::emitSwiftReflectionSection (llvm::binaryformat::Swift5ReflectionSectionKind ReflSectionKind, StringRef Buffer, uint32_t Alignment, uint32_t Size) inline override virtual
Emit the swift reflection section stored in Buffer.
Implements llvm::dwarflinker_parallel::ExtraDwarfEmitter.
Definition at line 81 of file DWARFEmitterImpl.h.
emitTempSym()
MCSymbol * llvm::dwarflinker_parallel::DwarfEmitterImpl::emitTempSym (StringRef SecName, StringRef SymName) inline override virtual
Emit temporarily symbol named SymName inside section SecName.
Implements llvm::dwarflinker_parallel::ExtraDwarfEmitter.
Definition at line 89 of file DWARFEmitterImpl.h.
finish()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::finish () inline override virtual
Dump the file to the disk.
Implements llvm::dwarflinker_parallel::ExtraDwarfEmitter.
Definition at line 69 of file DWARFEmitterImpl.h.
References llvm::MCStreamer::finish().
getAsmPrinter()
AsmPrinter & llvm::dwarflinker_parallel::DwarfEmitterImpl::getAsmPrinter () const inline override virtual
Returns underlying AsmPrinter.
Implements llvm::dwarflinker_parallel::ExtraDwarfEmitter.
Definition at line 71 of file DWARFEmitterImpl.h.
getDebugFrameSectionSize()
uint64_t llvm::dwarflinker_parallel::DwarfEmitterImpl::getDebugFrameSectionSize () const inline
Returns size of generated .debug_frame section.
Definition at line 169 of file DWARFEmitterImpl.h.
getDebugInfoSectionSize()
uint64_t llvm::dwarflinker_parallel::DwarfEmitterImpl::getDebugInfoSectionSize () const inline
Returns size of generated .debug_info section.
Definition at line 178 of file DWARFEmitterImpl.h.
getDebugLineSectionSize()
uint64_t llvm::dwarflinker_parallel::DwarfEmitterImpl::getDebugLineSectionSize () const inline
Returns size of generated .debug_line section.
Definition at line 166 of file DWARFEmitterImpl.h.
getDebugLocListsSectionSize()
uint64_t llvm::dwarflinker_parallel::DwarfEmitterImpl::getDebugLocListsSectionSize () const inline
Returns size of generated .debug_loclists section.
Definition at line 190 of file DWARFEmitterImpl.h.
getDebugLocSectionSize()
uint64_t llvm::dwarflinker_parallel::DwarfEmitterImpl::getDebugLocSectionSize () const inline
Returns size of generated .debug_loc section.
Definition at line 187 of file DWARFEmitterImpl.h.
getDebugMacInfoSectionSize()
uint64_t llvm::dwarflinker_parallel::DwarfEmitterImpl::getDebugMacInfoSectionSize () const inline
Returns size of generated .debug_macinfo section.
Definition at line 181 of file DWARFEmitterImpl.h.
getDebugMacroSectionSize()
uint64_t llvm::dwarflinker_parallel::DwarfEmitterImpl::getDebugMacroSectionSize () const inline
Returns size of generated .debug_macro section.
Definition at line 184 of file DWARFEmitterImpl.h.
getDebugRangesSectionSize()
uint64_t llvm::dwarflinker_parallel::DwarfEmitterImpl::getDebugRangesSectionSize () const inline
Returns size of generated .debug_ranges section.
Definition at line 172 of file DWARFEmitterImpl.h.
getDebugRngListsSectionSize()
uint64_t llvm::dwarflinker_parallel::DwarfEmitterImpl::getDebugRngListsSectionSize () const inline
Returns size of generated .debug_rnglists section.
Definition at line 175 of file DWARFEmitterImpl.h.
init()
Error llvm::dwarflinker_parallel::DwarfEmitterImpl::init (Triple TheTriple, StringRef Swift5ReflectionSegmentName)
Definition at line 23 of file DWARFEmitterImpl.cpp.
References llvm::dwarflinker_parallel::DWARFLinker::Assembly, llvm::Target::createAsmPrinter(), llvm::Target::createAsmStreamer(), llvm::Target::createMCAsmBackend(), llvm::Target::createMCAsmInfo(), llvm::Target::createMCCodeEmitter(), llvm::Target::createMCInstPrinter(), llvm::Target::createMCInstrInfo(), llvm::Target::createMCObjectFileInfo(), llvm::Target::createMCObjectStreamer(), llvm::Target::createMCRegInfo(), llvm::Target::createMCSubtargetInfo(), llvm::MCAsmBackend::createObjectWriter(), llvm::createStringError(), llvm::Target::createTargetMachine(), llvm::Triple::getTriple(), llvm::mc::InitMCTargetOptionsFromFlags(), llvm::TargetRegistry::lookupTarget(), llvm::MCTargetOptions::MCIncrementalLinkerCompatible, llvm::MCTargetOptions::MCRelaxAll, llvm::dwarflinker_parallel::DWARFLinker::Object, and llvm::Error::success().
switchToDebugInfoSection()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::switchToDebugInfoSection (unsigned DwarfVersion) inline
Set the current output section to debug_info and change the MC Dwarf version to DwarfVersion.
Definition at line 75 of file DWARFEmitterImpl.h.
translateLineTable()
void llvm::dwarflinker_parallel::DwarfEmitterImpl::translateLineTable (DataExtractor LineData, uint64_t Offset) inline
Definition at line 137 of file DWARFEmitterImpl.h.
The documentation for this class was generated from the following files:
lib/DWARFLinkerParallel/DWARFEmitterImpl.h
lib/DWARFLinkerParallel/DWARFEmitterImpl.cpp