LLVM: llvm::SDNode::use_iterator Class Reference
llvm::SDNode::use_iterator Class Reference
This class provides iterator support for SDUse operands that use a specific SDNode.
#include "llvm/CodeGen/SelectionDAGNodes.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = SDUse
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
use_iterator ()=default
use_iterator (const use_iterator &I)=default
use_iterator & operator= (const use_iterator &)=default
bool operator== (const use_iterator &x) const
bool operator!= (const use_iterator &x) const
bool atEnd () const
Return true if this iterator is at the end of uses list.
use_iterator & operator++ ()
use_iterator operator++ (int)
SDNode * operator* () const
Retrieve a pointer to the current user node.
SDNode * operator-> () const
SDUse & getUse () const
unsigned getOperandNo () const
Retrieve the operand # of this use in its user.
Friends
class SDNode
Detailed Description
This class provides iterator support for SDUse operands that use a specific SDNode.
Definition at line 750 of file SelectionDAGNodes.h.
Member Typedef Documentation
difference_type
using llvm::SDNode::use_iterator::difference_type = std::ptrdiff_t
Definition at line 760 of file SelectionDAGNodes.h.
iterator_category
using llvm::SDNode::use_iterator::iterator_category = std::forward_iterator_tag
Definition at line 758 of file SelectionDAGNodes.h.
pointer
using llvm::SDNode::use_iterator::pointer = value_type *
Definition at line 761 of file SelectionDAGNodes.h.
reference
using llvm::SDNode::use_iterator::reference = value_type &
Definition at line 762 of file SelectionDAGNodes.h.
value_type
using llvm::SDNode::use_iterator::value_type = SDUse
Definition at line 759 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
use_iterator() [1/2]
llvm::SDNode::use_iterator::use_iterator () default
use_iterator() [2/2]
llvm::SDNode::use_iterator::use_iterator (const use_iterator & I) default
Member Function Documentation
atEnd()
bool llvm::SDNode::use_iterator::atEnd () const inline
Return true if this iterator is at the end of uses list.
Definition at line 774 of file SelectionDAGNodes.h.
getOperandNo()
unsigned llvm::SDNode::use_iterator::getOperandNo () const inline
Retrieve the operand # of this use in its user.
Definition at line 798 of file SelectionDAGNodes.h.
References assert().
getUse()
SDUse & llvm::SDNode::use_iterator::getUse () const inline
Definition at line 795 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), and llvm::SelectionDAG::ReplaceAllUsesWith().
operator!=()
bool llvm::SDNode::use_iterator::operator!= (const use_iterator & x) const inline
Definition at line 769 of file SelectionDAGNodes.h.
References operator==().
operator*()
SDNode * llvm::SDNode::use_iterator::operator* () const inline
Retrieve a pointer to the current user node.
Definition at line 788 of file SelectionDAGNodes.h.
References assert().
Referenced by operator->().
operator++() [1/2]
use_iterator & llvm::SDNode::use_iterator::operator++ () inline
Definition at line 777 of file SelectionDAGNodes.h.
References assert().
operator++() [2/2]
use_iterator llvm::SDNode::use_iterator::operator++ (int) inline
Definition at line 783 of file SelectionDAGNodes.h.
References llvm::ilist_node_impl< OptionsT >::ilist_node_impl().
operator->()
SDNode * llvm::SDNode::use_iterator::operator-> () const inline
Definition at line 793 of file SelectionDAGNodes.h.
References operator*().
operator=()
use_iterator & llvm::SDNode::use_iterator::operator= (const use_iterator &) default
operator==()
bool llvm::SDNode::use_iterator::operator== (const use_iterator & x) const inline
Definition at line 768 of file SelectionDAGNodes.h.
Referenced by operator!=().
Friends And Related Symbol Documentation
SDNode
friend class SDNode friend
Definition at line 751 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/SelectionDAGNodes.h