LLVM: llvm::CSKYConstantPoolJT Class Reference
llvm::CSKYConstantPoolJT Class Reference
CSKY-specific constantpool value of a jump table.
#include "Target/CSKY/CSKYConstantPoolValue.h"
Public Member Functions
signed getJTI ()
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const CSKYConstantPoolJT *A) const
Public Member Functions inherited from llvm::CSKYConstantPoolValue
const char * getModifierText () const
unsigned getPCAdjustment () const
bool mustAddCurrentAddress () const
CSKYCP::CSKYCPModifier getModifier () const
unsigned getLabelID () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isMachineBasicBlock () const
bool isJT () const
bool isConstPool () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const CSKYConstantPoolValue *A) const
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, Align Alignment)
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
virtual unsigned getSizeInBytes (const DataLayout &DL) const
Static Public Member Functions
static CSKYConstantPoolJT * Create (Type *Ty, int JTI, unsigned PCAdj, CSKYCP::CSKYCPModifier Modifier)
static bool classof (const CSKYConstantPoolValue *ACPV)
Additional Inherited Members
Protected Member Functions inherited from llvm::CSKYConstantPoolValue
CSKYConstantPoolValue (Type *Ty, CSKYCP::CSKYCPKind Kind, unsigned PCAdjust, CSKYCP::CSKYCPModifier Modifier, bool AddCurrentAddress, unsigned ID=0)
Protected Attributes inherited from llvm::CSKYConstantPoolValue
CSKYCP::CSKYCPKind Kind
unsigned PCAdjust
CSKYCP::CSKYCPModifier Modifier
bool AddCurrentAddress
unsigned LabelId = 0
Detailed Description
CSKY-specific constantpool value of a jump table.
Definition at line 200 of file CSKYConstantPoolValue.h.
Member Function Documentation
addSelectionDAGCSEId()
void CSKYConstantPoolJT::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 219 of file CSKYConstantPoolValue.cpp.
References llvm::CSKYConstantPoolValue::addSelectionDAGCSEId().
classof()
static bool llvm::CSKYConstantPoolJT::classof (const CSKYConstantPoolValue * ACPV) inline static
Definition at line 221 of file CSKYConstantPoolValue.h.
Create()
CSKYConstantPoolJT * CSKYConstantPoolJT::Create (Type * Ty, int JTI, unsigned PCAdj, CSKYCP::CSKYCPModifier Modifier) static
Definition at line 209 of file CSKYConstantPoolValue.cpp.
References llvm::CSKYConstantPoolValue::Modifier.
equals()
bool llvm::CSKYConstantPoolJT::equals (const CSKYConstantPoolJT * A) const inline
Definition at line 217 of file CSKYConstantPoolValue.h.
References A, and llvm::CSKYConstantPoolValue::equals().
getExistingMachineCPValue()
int CSKYConstantPoolJT::getExistingMachineCPValue (MachineConstantPool * CP, Align Alignment) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 214 of file CSKYConstantPoolValue.cpp.
getJTI()
signed llvm::CSKYConstantPoolJT::getJTI () inline
Definition at line 210 of file CSKYConstantPoolValue.h.
print()
void CSKYConstantPoolJT::print (raw_ostream & O) const override virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Definition at line 224 of file CSKYConstantPoolValue.cpp.
References llvm::CSKYConstantPoolValue::print().
The documentation for this class was generated from the following files:
lib/Target/CSKY/CSKYConstantPoolValue.h
lib/Target/CSKY/CSKYConstantPoolValue.cpp