LLVM: llvm::mca::RetireStage Class Reference
llvm::mca::RetireStage Class Reference final
#include "llvm/MCA/Stages/RetireStage.h"
Public Member Functions
RetireStage (RetireControlUnit &R, RegisterFile &F, LSUnitBase &LS)
bool hasWorkToComplete () const override
Returns true if some instructions are still executing this stage.
Error cycleStart () override
Called once at the start of each cycle.
Error cycleEnd () override
Called once at the end of each cycle.
Error execute (InstRef &IR) override
The primary action that this stage performs on instruction IR.
void notifyInstructionRetired (const InstRef &IR) const
Public Member Functions inherited from llvm::mca::Stage
Stage ()=default
virtual ~Stage ()
virtual bool isAvailable (const InstRef &IR) const
Returns true if it can execute IR during this cycle.
virtual Error cycleResume ()
Called after the pipeline is resumed from pausing state.
void setNextInSequence (Stage *NextStage)
bool checkNextStage (const InstRef &IR) const
Error moveToTheNextStage (InstRef &IR)
Called when an instruction is ready to move the next pipeline stage.
void addListener (HWEventListener *Listener)
Add a listener to receive callbacks during the execution of this stage.
template<typename EventT >
void notifyEvent (const EventT &Event) const
Notify listeners of a particular hardware event.
Additional Inherited Members
Protected Member Functions inherited from llvm::mca::Stage
const std::set< HWEventListener * > & getListeners () const
Detailed Description
Definition at line 28 of file RetireStage.h.
Constructor & Destructor Documentation
RetireStage()
llvm::mca::RetireStage::RetireStage (RetireControlUnit & R, RegisterFile & F, LSUnitBase & LS) inline
Definition at line 38 of file RetireStage.h.
Member Function Documentation
cycleEnd()
llvm::Error llvm::mca::RetireStage::cycleEnd () override virtual
Called once at the end of each cycle.
Reimplemented from llvm::mca::Stage.
Definition at line 44 of file RetireStage.cpp.
References llvm::mca::RegisterFile::cycleEnd().
cycleStart()
llvm::Error llvm::mca::RetireStage::cycleStart () override virtual
Called once at the start of each cycle.
This can be used as a setup phase to prepare for the executions during the cycle.
Reimplemented from llvm::mca::Stage.
Definition at line 25 of file RetireStage.cpp.
References llvm::mca::RetireControlUnit::consumeCurrentToken(), llvm::mca::RegisterFile::cycleStart(), llvm::mca::RetireControlUnit::RUToken::Executed, llvm::mca::RetireControlUnit::getCurrentToken(), llvm::mca::RetireControlUnit::getMaxRetirePerCycle(), llvm::mca::RetireControlUnit::RUToken::IR, llvm::mca::RetireControlUnit::isEmpty(), and notifyInstructionRetired().
execute()
llvm::Error llvm::mca::RetireStage::execute (InstRef & IR) override virtual
The primary action that this stage performs on instruction IR.
Implements llvm::mca::Stage.
Definition at line 49 of file RetireStage.cpp.
References assert(), llvm::mca::Instruction::getRCUTokenID(), IR, llvm::mca::RegisterFile::onInstructionExecuted(), llvm::mca::RetireControlUnit::onInstructionExecuted(), and llvm::mca::RetireControlUnit::UnhandledTokenID.
hasWorkToComplete()
bool llvm::mca::RetireStage::hasWorkToComplete () const inline override virtual
Returns true if some instructions are still executing this stage.
Implements llvm::mca::Stage.
Definition at line 41 of file RetireStage.h.
notifyInstructionRetired()
void llvm::mca::RetireStage::notifyInstructionRetired (const InstRef & IR) const
Definition at line 60 of file RetireStage.cpp.
References llvm::dbgs(), llvm::mca::InstructionBase::getDefs(), llvm::mca::RegisterFile::getNumRegisterFiles(), IR, llvm::mca::InstructionBase::isMemOp(), LLVM_DEBUG, llvm::mca::LSUnitBase::onInstructionRetired(), and llvm::mca::RegisterFile::removeRegisterWrite().
Referenced by cycleStart().
The documentation for this class was generated from the following files:
include/llvm/MCA/Stages/RetireStage.h
lib/MCA/Stages/RetireStage.cpp