LLVM: llvm::dwarflinker_parallel::CompileUnit Class Reference
llvm::dwarflinker_parallel::CompileUnit Class Reference
Stores all information related to a compile unit, be it in its original instance of the object file or its brand new cloned and generated DIE tree.
#include "DWARFLinkerParallel/DWARFLinkerCompileUnit.h"
Public Member Functions
CompileUnit (LinkContext &, unsigned ID, StringRef ClangModuleName, DWARFFile &File, DWARFLinker::SwiftInterfacesMapTy *, UnitMessageHandlerTy WarningHandler)
CompileUnit (LinkContext &, DWARFUnit &OrigUnit, unsigned ID, StringRef ClangModuleName, DWARFFile &File, UnitMessageHandlerTy WarningHandler)
DWARFUnit & getOrigUnit () const
Returns paired compile unit from input DWARF.
const DWARFDebugInfoEntry * getFirstChildEntry (const DWARFDebugInfoEntry *Die) const
const DWARFDebugInfoEntry * getSiblingEntry (const DWARFDebugInfoEntry *Die) const
DWARFDie getParent (const DWARFDebugInfoEntry *Die)
DWARFDie getDIEAtIndex (unsigned Index)
const DWARFDebugInfoEntry * getDebugInfoEntry (unsigned Index) const
DWARFDie getUnitDIE (bool ExtractUnitDIEOnly=true)
DWARFDie getDIE (const DWARFDebugInfoEntry *Die)
uint32_t getDIEIndex (const DWARFDebugInfoEntry *Die) const
uint32_t getDIEIndex (const DWARFDie &Die) const
std::optional< DWARFFormValue > find (uint32_t DieIdx, ArrayRef< dwarf::Attribute > Attrs) const
std::optional< DWARFFormValue > find (const DWARFDebugInfoEntry *Die, ArrayRef< dwarf::Attribute > Attrs) const
std::optional< uint32_t > getDIEIndexForOffset (uint64_t Offset)
Public Member Functions inherited from llvm::dwarflinker_parallel::DwarfUnit
virtual ~DwarfUnit ()
DwarfUnit (unsigned ID, StringRef ClangModuleName, UnitMessageHandlerTy WarningHandler)
support::endianness getEndianness () const
Endiannes for the compile unit.
uint16_t getVersion () const
Return DWARF version.
uint16_t getHeaderSize () const
Return size of header of debug_info table.
uint8_t getAddressByteSize () const
Return size of address.
uint8_t getRefAddrByteSize () const
Return size of reference.
dwarf::DwarfFormat getDwarfFormat () const
Return format of the Dwarf(DWARF32 or DWARF64).
unsigned getUniqueID () const
Unique id of the unit.
uint16_t getLanguage () const
Return language of this unit.
void setUnitSize (uint64_t UnitSize)
Set size of this(newly generated) compile unit.
uint64_t getUnitSize () const
Returns size of this(newly generated) compile unit.
StringRef getUnitName () const
Returns this unit name.
StringRef getSysRoot ()
Return the DW_AT_LLVM_sysroot of the compile unit or an empty StringRef.
void setOutputDIE (DIE *UnitDie)
Create a Die for this unit.
DIE * getOutputUnitDIE () const
Return Die for this compile unit.
bool isClangModule () const
Return true if this compile unit is from Clang module.
const std::string & getClangModuleName () const
Return Clang module name;.
OutTablesFileTy & getOutDwarfBits ()
Returns generated file keeping debug tables for this compile unit.
void eraseDwarfBits ()
Erases generated file keeping debug tables for this compile unit.
MCSymbol * getLabelBegin ()
void setLabelBegin (MCSymbol *S)
void reportWarning (const Twine &Warning, const DWARFDie *Die=nullptr) const
Error reporting methods.
void reportWarning (Error Warning) const
Public Member Functions inherited from llvm::dwarflinker_parallel::OutputSections
uint64_t getStartOffset (DebugSectionKind SectionKind) const
When objects(f.e.
void setStartOffset (DebugSectionKind SectionKind, uint64_t Offset)
Set offset to the start of specified SectionKind debug section, corresponding to this object.
Additional Inherited Members
Public Types inherited from llvm::dwarflinker_parallel::OutputSections
enum class DebugSectionKind : uint8_t {
DebugInfo = 0 , DebugLine , DebugFrame , DebugRange ,
DebugRngLists , DebugLoc , DebugLocLists , DebugARanges ,
DebugAbbrev , DebugMacinfo , DebugMacro
}
List of tracked debug sections.
Static Public Member Functions inherited from llvm::dwarflinker_parallel::OutputSections
static std::optional< DebugSectionKind > parseDebugSectionName (StringRef Name)
Recognise the section name and match it with the DebugSectionKind.
Static Public Attributes inherited from llvm::dwarflinker_parallel::OutputSections
static constexpr size_t SectionKindsNum = 11
Protected Attributes inherited from llvm::dwarflinker_parallel::DwarfUnit
unsigned ID = 0
Unique ID for the unit.
dwarf::FormParams FormParams
Properties of the unit.
DIE * NewUnit = nullptr
DIE for newly generated compile unit.
uint16_t Language = 0
The DW_AT_language of this unit.
std::string UnitName
The name of this unit.
std::string SysRoot
The DW_AT_LLVM_sysroot of this unit.
std::string ClangModuleName
If this is a Clang module, this holds the module's name.
uint64_t UnitSize = 0
OutTablesFileTy OutDebugInfoBits
Elf file containg generated debug tables for this compile unit.
support::endianness Endianess = support::endianness::little
Endiannes for this compile unit.
MCSymbol * LabelBegin = nullptr
std::atomic< bool > IsInterconnectedCU = {false}
true if current unit references_to/is_referenced by other unit.
UnitMessageHandlerTy WarningHandler
Protected Attributes inherited from llvm::dwarflinker_parallel::OutputSections
std::array< uint64_t, SectionKindsNum > Offsets = {0}
Offsets to the debug sections composing this object.
Detailed Description
Stores all information related to a compile unit, be it in its original instance of the object file or its brand new cloned and generated DIE tree.
Definition at line 25 of file DWARFLinkerCompileUnit.h.
Constructor & Destructor Documentation
CompileUnit() [1/2]
llvm::dwarflinker_parallel::CompileUnit::CompileUnit (LinkContext & , unsigned ID, StringRef ClangModuleName, DWARFFile & File, DWARFLinker::SwiftInterfacesMapTy * , UnitMessageHandlerTy WarningHandler) inline
Definition at line 27 of file DWARFLinkerCompileUnit.h.
References llvm::dwarf::FormParams::AddrSize, llvm::dwarf::DWARF32, llvm::dwarflinker_parallel::DWARFFile::FileName, llvm::dwarf::FormParams::Format, llvm::dwarflinker_parallel::DwarfUnit::UnitName, and llvm::dwarf::FormParams::Version.
CompileUnit() [2/2]
llvm::dwarflinker_parallel::CompileUnit::CompileUnit (LinkContext & , DWARFUnit & OrigUnit, unsigned ID, StringRef ClangModuleName, DWARFFile & File, UnitMessageHandlerTy WarningHandler) inline
Definition at line 38 of file DWARFLinkerCompileUnit.h.
References llvm::dwarf::FormParams::AddrSize, llvm::dwarf::DWARF32, llvm::dwarflinker_parallel::DwarfUnit::Endianess, llvm::dwarflinker_parallel::DWARFFile::FileName, llvm::dwarf::FormParams::Format, llvm::DWARFUnit::getAddressByteSize(), llvm::DWARFUnit::getUnitDIE(), llvm::DWARFUnit::getVersion(), llvm::dwarflinker_parallel::DwarfUnit::Language, llvm::StringRef::str(), llvm::dwarflinker_parallel::DwarfUnit::SysRoot, llvm::dwarf::toStringRef(), llvm::dwarf::toUnsigned(), llvm::dwarflinker_parallel::DwarfUnit::UnitName, and llvm::dwarf::FormParams::Version.
The documentation for this class was generated from the following file:
lib/DWARFLinkerParallel/DWARFLinkerCompileUnit.h