LLVM: llvm::jitlink::aarch32::StubsManager< Flavor > Class Template Reference
llvm::jitlink::aarch32::StubsManager< Flavor > Class Template Reference
Stubs builder for a specific StubsFlavor.
#include "llvm/ExecutionEngine/JITLink/aarch32.h"
Public Member Functions
StubsManager ()=default
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Implements link-graph traversal via visitExistingEdges().
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Create a branch range extension stub for the class's flavor.
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Create a branch range extension stub with Thumb encoding for v7 CPUs.
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Public Member Functions inherited from llvm::jitlink::TableManager< StubsManager< Flavor > >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Static Public Member Functions
static StringRef getSectionName ()
Name of the object file section that will contain all our stubs.
Detailed Description
template<StubsFlavor Flavor>
class llvm::jitlink::aarch32::StubsManager< Flavor >
Stubs builder for a specific StubsFlavor.
Right now we only have one default stub kind, but we want to extend this and allow creation of specific kinds in the future (e.g. branch range extension or interworking).
Let's keep it simple for the moment and not wire this through a GOT.
Definition at line 238 of file aarch32.h.
Constructor & Destructor Documentation
StubsManager()
template<StubsFlavor Flavor> llvm::jitlink::aarch32::StubsManager< Flavor >::StubsManager () default
Member Function Documentation
createEntry() [1/3]
template<StubsFlavor Flavor> Symbol & llvm::jitlink::aarch32::StubsManager< Flavor >::createEntry (LinkGraph & G, Symbol & Target)
Create a branch range extension stub for the class's flavor.
createEntry() [2/3]
Symbol & llvm::jitlink::aarch32::StubsManager< Thumbv7 >::createEntry (LinkGraph & G, Symbol & Target)
Create a branch range extension stub with Thumb encoding for v7 CPUs.
createEntry() [3/3]
Symbol & llvm::jitlink::aarch32::StubsManager< Thumbv7 >::createEntry (LinkGraph & G, Symbol & Target)
Definition at line 450 of file aarch32.cpp.
References assert(), B, llvm::jitlink::aarch32::encodeRegMovtT1MovwT3(), G, LLVM_DEBUG, llvm::jitlink::aarch32::Thumb_MovtAbs, llvm::jitlink::aarch32::Thumb_MovwAbsNC, llvm::jitlink::aarch32::ThumbSymbol, and llvm::jitlink::aarch32::Thumbv7ABS.
getSectionName()
template<StubsFlavor Flavor> static StringRef llvm::jitlink::aarch32::StubsManager< Flavor >::getSectionName () inline static
Name of the object file section that will contain all our stubs.
Definition at line 243 of file aarch32.h.
visitEdge()
template<StubsFlavor Flavor> bool llvm::jitlink::aarch32::StubsManager< Flavor >::visitEdge (LinkGraph & G, Block * B, Edge & E) inline
Implements link-graph traversal via visitExistingEdges().
Definition at line 246 of file aarch32.h.
References B, llvm::dbgs(), DEBUG_WITH_TYPE, E, llvm::formatv(), G, llvm::jitlink::TableManager< StubsManager< Flavor > >::getEntryForTarget(), llvm::jitlink::aarch32::Thumb_Call, and llvm::jitlink::aarch32::Thumb_Jump24.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/aarch32.h