LLVM: llvm::SystemZMCExpr Class Reference
llvm::SystemZMCExpr Class Reference
#include "Target/SystemZ/MCTargetDesc/SystemZMCExpr.h"
Public Types
enum VariantKind { VK_SystemZ_None , VK_SystemZ_RCon , VK_SystemZ_VCon }
Public Types inherited from llvm::MCExpr
enum ExprKind : uint8_t {
Binary , Constant , SymbolRef , Unary ,
Target
}
Public Member Functions
VariantKind getKind () const
getOpcode - Get the kind of this expression.
const MCExpr * getSubExpr () const
getSubExpr - Get the child of this expression.
StringRef getVariantKindName () const
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCFragment * findAssociatedFragment () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Public Member Functions inherited from llvm::MCTargetExpr
virtual bool isEqualTo (const MCExpr *x) const
virtual bool inlineAssignedExpr () const
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool evaluateAsRelocatable (MCValue &Res, const MCAsmLayout *Layout, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAsmLayout &Layout) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static const SystemZMCExpr * create (VariantKind Kind, const MCExpr *Expr, MCContext &Ctx)
static bool classof (const MCExpr *E)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()=default
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc, unsigned SubclassData=0)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
unsigned getSubclassData () const
Detailed Description
Definition at line 18 of file SystemZMCExpr.h.
Member Enumeration Documentation
VariantKind
enum llvm::SystemZMCExpr::VariantKind
Enumerator
VK_SystemZ_None
VK_SystemZ_RCon
VK_SystemZ_VCon
Definition at line 22 of file SystemZMCExpr.h.
Member Function Documentation
classof()
static bool llvm::SystemZMCExpr::classof (const MCExpr * E) inline static
Definition at line 60 of file SystemZMCExpr.h.
References E, and llvm::MCExpr::Target.
create()
const SystemZMCExpr * SystemZMCExpr::create (VariantKind Kind, const MCExpr * Expr, MCContext & Ctx) static
Definition at line 15 of file SystemZMCExpr.cpp.
evaluateAsRelocatableImpl()
bool SystemZMCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout, const MCFixup * Fixup) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 39 of file SystemZMCExpr.cpp.
References llvm::MCExpr::evaluateAsRelocatable(), Fixup, llvm::MCValue::get(), llvm::MCValue::getConstant(), getKind(), getSubExpr(), llvm::MCValue::getSymA(), and llvm::MCValue::getSymB().
findAssociatedFragment()
MCFragment * llvm::SystemZMCExpr::findAssociatedFragment () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 53 of file SystemZMCExpr.h.
References llvm::MCExpr::findAssociatedFragment(), and getSubExpr().
fixELFSymbolsInTLSFixups()
void llvm::SystemZMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 58 of file SystemZMCExpr.h.
getKind()
VariantKind llvm::SystemZMCExpr::getKind () const inline
getOpcode - Get the kind of this expression.
Definition at line 40 of file SystemZMCExpr.h.
Referenced by evaluateAsRelocatableImpl(), and getVariantKindName().
getSubExpr()
const MCExpr * llvm::SystemZMCExpr::getSubExpr () const inline
getSubExpr - Get the child of this expression.
Definition at line 43 of file SystemZMCExpr.h.
Referenced by evaluateAsRelocatableImpl(), findAssociatedFragment(), and visitUsedExpr().
getVariantKindName()
StringRef SystemZMCExpr::getVariantKindName () const
Definition at line 20 of file SystemZMCExpr.cpp.
References getKind(), llvm_unreachable, VK_SystemZ_None, VK_SystemZ_RCon, and VK_SystemZ_VCon.
Referenced by printImpl().
printImpl()
void SystemZMCExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 33 of file SystemZMCExpr.cpp.
References getVariantKindName(), OS, and llvm::MCExpr::print().
visitUsedExpr()
void llvm::SystemZMCExpr::visitUsedExpr (MCStreamer & Streamer) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 50 of file SystemZMCExpr.h.
References getSubExpr(), and llvm::MCStreamer::visitUsedExpr().
The documentation for this class was generated from the following files:
lib/Target/SystemZ/MCTargetDesc/SystemZMCExpr.h
lib/Target/SystemZ/MCTargetDesc/SystemZMCExpr.cpp