LLVM: llvm::logicalview::LVDoubleMap< FirstKeyType, SecondKeyType, ValueType > Class Template Reference
llvm::logicalview::LVDoubleMap< FirstKeyType, SecondKeyType, ValueType > Class Template Reference
#include "llvm/DebugInfo/LogicalView/Core/LVSupport.h"
Public Member Functions
void add (FirstKeyType FirstKey, SecondKeyType SecondKey, ValueType Value)
LVSecondMapType * findMap (FirstKeyType FirstKey) const
ValueType find (FirstKeyType FirstKey, SecondKeyType SecondKey) const
ValueType find (SecondKeyType SecondKey) const
LVValueTypes find () const
Detailed Description
template<typename FirstKeyType, typename SecondKeyType, typename ValueType>
class llvm::logicalview::LVDoubleMap< FirstKeyType, SecondKeyType, ValueType >
Definition at line 144 of file LVSupport.h.
Member Function Documentation
add()
template<typename FirstKeyType , typename SecondKeyType , typename ValueType > void llvm::logicalview::LVDoubleMap< FirstKeyType, SecondKeyType, ValueType >::add (FirstKeyType FirstKey, SecondKeyType SecondKey, ValueType Value) inline
Definition at line 156 of file LVSupport.h.
find() [1/3]
template<typename FirstKeyType , typename SecondKeyType , typename ValueType > LVValueTypes llvm::logicalview::LVDoubleMap< FirstKeyType, SecondKeyType, ValueType >::find () const inline
Definition at line 200 of file LVSupport.h.
Referenced by llvm::logicalview::LVDoubleMap< FirstKeyType, SecondKeyType, ValueType >::find().
find() [2/3]
template<typename FirstKeyType , typename SecondKeyType , typename ValueType > ValueType llvm::logicalview::LVDoubleMap< FirstKeyType, SecondKeyType, ValueType >::find (FirstKeyType FirstKey, SecondKeyType SecondKey) const inline
Definition at line 182 of file LVSupport.h.
References llvm::logicalview::LVDoubleMap< FirstKeyType, SecondKeyType, ValueType >::findMap().
find() [3/3]
template<typename FirstKeyType , typename SecondKeyType , typename ValueType > ValueType llvm::logicalview::LVDoubleMap< FirstKeyType, SecondKeyType, ValueType >::find (SecondKeyType SecondKey) const inline
Definition at line 192 of file LVSupport.h.
References llvm::logicalview::LVDoubleMap< FirstKeyType, SecondKeyType, ValueType >::find().
findMap()
template<typename FirstKeyType , typename SecondKeyType , typename ValueType > LVSecondMapType * llvm::logicalview::LVDoubleMap< FirstKeyType, SecondKeyType, ValueType >::findMap (FirstKeyType FirstKey) const inline
Definition at line 174 of file LVSupport.h.
Referenced by llvm::logicalview::LVDoubleMap< FirstKeyType, SecondKeyType, ValueType >::find().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/LogicalView/Core/LVSupport.h