LLVM: llvm::objcopy::elf::CompressedSection Class Reference
llvm::objcopy::elf::CompressedSection Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
CompressedSection (const SectionBase &Sec, DebugCompressionType CompressionType, bool Is64Bits)
CompressedSection (ArrayRef< uint8_t > CompressedData, uint32_t ChType, uint64_t DecompressedSize, uint64_t DecompressedAlign)
uint64_t getDecompressedSize () const
uint64_t getDecompressedAlign () const
uint64_t getChType () const
Error accept (SectionVisitor &Visitor) const override
Error accept (MutableSectionVisitor &Visitor) override
Public Member Functions inherited from llvm::objcopy::elf::SectionBase
SectionBase ()=default
SectionBase (const SectionBase &)=default
virtual ~SectionBase ()=default
virtual Error initialize (SectionTableRef SecTable)
virtual void finalize ()
virtual Error removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove)
virtual Error removeSymbols (function_ref< bool(const Symbol &)> ToRemove)
virtual void markSymbols ()
virtual void replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > &)
virtual bool hasContents () const
virtual void onRemove ()
virtual void restoreSymTabLink (SymbolTableSection &)
Static Public Member Functions
static bool classof (const SectionBase *S)
Additional Inherited Members
Public Attributes inherited from llvm::objcopy::elf::SectionBase
std::string Name
Segment * ParentSegment = nullptr
uint64_t HeaderOffset = 0
uint32_t Index = 0
uint32_t OriginalIndex = 0
uint64_t OriginalFlags = 0
uint64_t OriginalType = ELF::SHT_NULL
uint64_t OriginalOffset = std::numeric_limits<uint64_t>::max()
uint64_t Addr = 0
uint64_t Align = 1
uint32_t EntrySize = 0
uint64_t Flags = 0
uint64_t Info = 0
uint64_t Link = ELF::SHN_UNDEF
uint64_t NameIndex = 0
uint64_t Offset = 0
uint64_t Size = 0
uint64_t Type = ELF::SHT_NULL
ArrayRef< uint8_t > OriginalData
bool HasSymbol = false
Detailed Description
Definition at line 540 of file ELFObject.h.
Constructor & Destructor Documentation
CompressedSection() [1/2]
CompressedSection::CompressedSection (const SectionBase & Sec, DebugCompressionType CompressionType, bool Is64Bits)
Definition at line 541 of file ELFObject.cpp.
References llvm::compression::compress(), llvm::objcopy::elf::SectionBase::OriginalData, llvm::ELF::SHF_COMPRESSED, llvm::SmallVectorBase< Size_T >::size(), and llvm::objcopy::elf::SectionBase::Size.
CompressedSection() [2/2]
CompressedSection::CompressedSection (ArrayRef< uint8_t > CompressedData, uint32_t ChType, uint64_t DecompressedSize, uint64_t DecompressedAlign)
Definition at line 556 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::OriginalData.
Member Function Documentation
accept() [1/2]
Error CompressedSection::accept (MutableSectionVisitor & Visitor) override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 568 of file ELFObject.cpp.
References llvm::objcopy::elf::MutableSectionVisitor::visit().
accept() [2/2]
Error CompressedSection::accept (SectionVisitor & Visitor) const override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 564 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionVisitor::visit().
classof()
static bool llvm::objcopy::elf::CompressedSection::classof (const SectionBase * S) inline static
Definition at line 562 of file ELFObject.h.
References llvm::objcopy::elf::SectionBase::OriginalFlags, and llvm::ELF::SHF_COMPRESSED.
getChType()
uint64_t llvm::objcopy::elf::CompressedSection::getChType () const inline
Definition at line 557 of file ELFObject.h.
getDecompressedAlign()
uint64_t llvm::objcopy::elf::CompressedSection::getDecompressedAlign () const inline
Definition at line 556 of file ELFObject.h.
Referenced by llvm::objcopy::elf::DecompressedSection::DecompressedSection().
getDecompressedSize()
uint64_t llvm::objcopy::elf::CompressedSection::getDecompressedSize () const inline
Definition at line 555 of file ELFObject.h.
Referenced by llvm::objcopy::elf::DecompressedSection::DecompressedSection().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp