LLVM: llvm::MCObjectFileInfo Class Reference
llvm::MCObjectFileInfo Class Reference
#include "llvm/MC/MCObjectFileInfo.h"
Public Member Functions
void initMCObjectFileInfo (MCContext &MCCtx, bool PIC, bool LargeCodeModel=false)
virtual ~MCObjectFileInfo ()
MCContext & getContext () const
bool getSupportsWeakOmittedEHFrame () const
bool getSupportsCompactUnwindWithoutEHFrame () const
bool getOmitDwarfIfHaveCompactUnwind () const
unsigned getFDEEncoding () const
unsigned getCompactUnwindDwarfEHFrameOnly () const
virtual unsigned getTextSectionAlignment () const
MCSection * getTextSection () const
MCSection * getDataSection () const
MCSection * getBSSSection () const
MCSection * getReadOnlySection () const
MCSection * getLSDASection () const
MCSection * getCompactUnwindSection () const
MCSection * getDwarfAbbrevSection () const
MCSection * getDwarfInfoSection () const
MCSection * getDwarfInfoSection (uint64_t Hash) const
MCSection * getDwarfLineSection () const
MCSection * getDwarfLineStrSection () const
MCSection * getDwarfFrameSection () const
MCSection * getDwarfPubNamesSection () const
MCSection * getDwarfPubTypesSection () const
MCSection * getDwarfGnuPubNamesSection () const
MCSection * getDwarfGnuPubTypesSection () const
const MCSection * getDwarfDebugInlineSection () const
MCSection * getDwarfStrSection () const
MCSection * getDwarfLocSection () const
MCSection * getDwarfARangesSection () const
MCSection * getDwarfRangesSection () const
MCSection * getDwarfRnglistsSection () const
MCSection * getDwarfLoclistsSection () const
MCSection * getDwarfMacinfoSection () const
MCSection * getDwarfMacroSection () const
MCSection * getDwarfDebugNamesSection () const
MCSection * getDwarfAccelNamesSection () const
MCSection * getDwarfAccelObjCSection () const
MCSection * getDwarfAccelNamespaceSection () const
MCSection * getDwarfAccelTypesSection () const
MCSection * getDwarfInfoDWOSection () const
MCSection * getDwarfTypesSection (uint64_t Hash) const
MCSection * getDwarfTypesDWOSection () const
MCSection * getDwarfAbbrevDWOSection () const
MCSection * getDwarfStrDWOSection () const
MCSection * getDwarfLineDWOSection () const
MCSection * getDwarfLocDWOSection () const
MCSection * getDwarfStrOffDWOSection () const
MCSection * getDwarfStrOffSection () const
MCSection * getDwarfAddrSection () const
MCSection * getDwarfRnglistsDWOSection () const
MCSection * getDwarfLoclistsDWOSection () const
MCSection * getDwarfMacroDWOSection () const
MCSection * getDwarfMacinfoDWOSection () const
MCSection * getDwarfCUIndexSection () const
MCSection * getDwarfTUIndexSection () const
MCSection * getDwarfSwiftASTSection () const
MCSection * getCOFFDebugSymbolsSection () const
MCSection * getCOFFDebugTypesSection () const
MCSection * getCOFFGlobalTypeHashesSection () const
MCSection * getTLSExtraDataSection () const
const MCSection * getTLSDataSection () const
MCSection * getTLSBSSSection () const
MCSection * getStackMapSection () const
MCSection * getFaultMapSection () const
MCSection * getRemarksSection () const
MCSection * getStackSizesSection (const MCSection &TextSec) const
MCSection * getBBAddrMapSection (const MCSection &TextSec) const
MCSection * getKCFITrapSection (const MCSection &TextSec) const
MCSection * getPseudoProbeSection (const MCSection &TextSec) const
MCSection * getPseudoProbeDescSection (StringRef FuncName) const
MCSection * getLLVMStatsSection () const
MCSection * getPCSection (StringRef Name, const MCSection *TextSec) const
MCSection * getDataRelROSection () const
const MCSection * getMergeableConst4Section () const
const MCSection * getMergeableConst8Section () const
const MCSection * getMergeableConst16Section () const
const MCSection * getMergeableConst32Section () const
const MCSection * getTLSTLVSection () const
const MCSection * getTLSThreadInitSection () const
const MCSection * getCStringSection () const
const MCSection * getUStringSection () const
MCSection * getTextCoalSection () const
const MCSection * getConstTextCoalSection () const
const MCSection * getConstDataSection () const
const MCSection * getDataCoalSection () const
const MCSection * getConstDataCoalSection () const
const MCSection * getDataCommonSection () const
MCSection * getDataBSSSection () const
const MCSection * getFourByteConstantSection () const
const MCSection * getEightByteConstantSection () const
const MCSection * getSixteenByteConstantSection () const
MCSection * getLazySymbolPointerSection () const
MCSection * getNonLazySymbolPointerSection () const
MCSection * getThreadLocalPointerSection () const
MCSection * getAddrSigSection () const
MCSection * getDrectveSection () const
MCSection * getPDataSection () const
MCSection * getXDataSection () const
MCSection * getSXDataSection () const
MCSection * getGEHContSection () const
MCSection * getGFIDsSection () const
MCSection * getGIATsSection () const
MCSection * getGLJMPSection () const
MCSection * getPPA1Section () const
MCSection * getADASection () const
MCSection * getTOCBaseSection () const
MCSection * getEHFrameSection () const
bool isPositionIndependent () const
MCSection * getSwift5ReflectionSection (llvm::binaryformat::Swift5ReflectionSectionKind ReflSectionKind)
void setSDKVersion (const VersionTuple &TheSDKVersion)
const VersionTuple & getSDKVersion () const
void setDarwinTargetVariantTriple (const Triple &T)
const Triple * getDarwinTargetVariantTriple () const
void setDarwinTargetVariantSDKVersion (const VersionTuple &TheSDKVersion)
const VersionTuple & getDarwinTargetVariantSDKVersion () const
Protected Attributes
bool SupportsWeakOmittedEHFrame = false
True if target object file supports a weak_definition of constant 0 for an omitted EH frame.
bool SupportsCompactUnwindWithoutEHFrame = false
True if the target object file supports emitting a compact unwind section without an associated EH frame section.
bool OmitDwarfIfHaveCompactUnwind = false
OmitDwarfIfHaveCompactUnwind - True if the target object file supports having some functions with compact unwind and other with dwarf unwind.
unsigned FDECFIEncoding = 0
FDE CFI encoding.
unsigned CompactUnwindDwarfEHFrameOnly = 0
Compact unwind encoding indicating that we should emit only an EH frame.
MCSection * TextSection = nullptr
Section directive for standard text.
MCSection * DataSection = nullptr
Section directive for standard data.
MCSection * BSSSection = nullptr
Section that is default initialized to zero.
MCSection * ReadOnlySection = nullptr
Section that is readonly and can contain arbitrary initialized data.
MCSection * LSDASection = nullptr
If exception handling is supported by the target, this is the section the Language Specific Data Area information is emitted to.
MCSection * CompactUnwindSection = nullptr
If exception handling is supported by the target and the target can support a compact representation of the CIE and FDE, this is the section to emit them into.
MCSection * DwarfAbbrevSection = nullptr
MCSection * DwarfInfoSection = nullptr
MCSection * DwarfLineSection = nullptr
MCSection * DwarfLineStrSection = nullptr
MCSection * DwarfFrameSection = nullptr
MCSection * DwarfPubTypesSection = nullptr
const MCSection * DwarfDebugInlineSection = nullptr
MCSection * DwarfStrSection = nullptr
MCSection * DwarfLocSection = nullptr
MCSection * DwarfARangesSection = nullptr
MCSection * DwarfRangesSection = nullptr
MCSection * DwarfMacinfoSection = nullptr
MCSection * DwarfMacroSection = nullptr
MCSection * DwarfPubNamesSection = nullptr
MCSection * DwarfDebugNamesSection = nullptr
Accelerator table sections.
MCSection * DwarfAccelNamesSection = nullptr
MCSection * DwarfAccelObjCSection = nullptr
MCSection * DwarfAccelNamespaceSection = nullptr
MCSection * DwarfAccelTypesSection = nullptr
MCSection * DwarfInfoDWOSection = nullptr
MCSection * DwarfTypesDWOSection = nullptr
MCSection * DwarfAbbrevDWOSection = nullptr
MCSection * DwarfStrDWOSection = nullptr
MCSection * DwarfLineDWOSection = nullptr
MCSection * DwarfLocDWOSection = nullptr
MCSection * DwarfStrOffDWOSection = nullptr
MCSection * DwarfMacinfoDWOSection = nullptr
MCSection * DwarfMacroDWOSection = nullptr
MCSection * DwarfStrOffSection = nullptr
The DWARF v5 string offset and address table sections.
MCSection * DwarfAddrSection = nullptr
MCSection * DwarfRnglistsSection = nullptr
The DWARF v5 range list section.
MCSection * DwarfLoclistsSection = nullptr
The DWARF v5 locations list section.
MCSection * DwarfRnglistsDWOSection = nullptr
The DWARF v5 range and location list sections for fission.
MCSection * DwarfLoclistsDWOSection = nullptr
MCSection * DwarfCUIndexSection = nullptr
MCSection * DwarfTUIndexSection = nullptr
MCSection * DwarfGnuPubNamesSection = nullptr
Section for newer gnu pubnames.
MCSection * DwarfGnuPubTypesSection = nullptr
Section for newer gnu pubtypes.
MCSection * DwarfSwiftASTSection = nullptr
MCSection * COFFDebugSymbolsSection = nullptr
MCSection * COFFDebugTypesSection = nullptr
MCSection * COFFGlobalTypeHashesSection = nullptr
MCSection * TLSExtraDataSection = nullptr
Extra TLS Variable Data section.
MCSection * TLSDataSection = nullptr
Section directive for Thread Local data. ELF, MachO, COFF, and Wasm.
MCSection * TLSBSSSection = nullptr
Section directive for Thread Local uninitialized data.
MCSection * StackMapSection = nullptr
StackMap section.
MCSection * FaultMapSection = nullptr
FaultMap section.
MCSection * RemarksSection = nullptr
Remarks section.
MCSection * EHFrameSection = nullptr
EH frame section.
MCSection * StackSizesSection = nullptr
Section containing metadata on function stack sizes.
MCSection * PseudoProbeSection = nullptr
Section for pseudo probe information used by AutoFDO.
MCSection * PseudoProbeDescSection = nullptr
MCSection * LLVMStatsSection = nullptr
MCSection * DataRelROSection = nullptr
MCSection * MergeableConst4Section = nullptr
MCSection * MergeableConst8Section = nullptr
MCSection * MergeableConst16Section = nullptr
MCSection * MergeableConst32Section = nullptr
MCSection * TLSTLVSection = nullptr
Section for thread local structure information.
const MCSection * TLSThreadInitSection = nullptr
Section for thread local data initialization functions.
MCSection * CStringSection = nullptr
MCSection * UStringSection = nullptr
MCSection * TextCoalSection = nullptr
MCSection * ConstTextCoalSection = nullptr
MCSection * ConstDataSection = nullptr
MCSection * DataCoalSection = nullptr
MCSection * ConstDataCoalSection = nullptr
MCSection * DataCommonSection = nullptr
MCSection * DataBSSSection = nullptr
MCSection * FourByteConstantSection = nullptr
MCSection * EightByteConstantSection = nullptr
MCSection * SixteenByteConstantSection = nullptr
MCSection * LazySymbolPointerSection = nullptr
MCSection * NonLazySymbolPointerSection = nullptr
MCSection * ThreadLocalPointerSection = nullptr
MCSection * AddrSigSection = nullptr
MCSection * DrectveSection = nullptr
COFF specific sections.
MCSection * PDataSection = nullptr
MCSection * XDataSection = nullptr
MCSection * SXDataSection = nullptr
MCSection * GEHContSection = nullptr
MCSection * GFIDsSection = nullptr
MCSection * GIATsSection = nullptr
MCSection * GLJMPSection = nullptr
MCSection * PPA1Section = nullptr
MCSection * ADASection = nullptr
MCSection * TOCBaseSection = nullptr
MCSection * ReadOnly8Section = nullptr
MCSection * ReadOnly16Section = nullptr
std::array< MCSection *, binaryformat::Swift5ReflectionSectionKind::last > Swift5ReflectionSections = {}
Detailed Description
Definition at line 28 of file MCObjectFileInfo.h.
Constructor & Destructor Documentation
~MCObjectFileInfo()
MCObjectFileInfo::~MCObjectFileInfo () virtual default
Member Function Documentation
getADASection()
MCSection * llvm::MCObjectFileInfo::getADASection () const inline
Definition at line 434 of file MCObjectFileInfo.h.
References ADASection.
getAddrSigSection()
MCSection * llvm::MCObjectFileInfo::getAddrSigSection () const inline
Definition at line 420 of file MCObjectFileInfo.h.
References AddrSigSection.
getBBAddrMapSection()
MCSection * MCObjectFileInfo::getBBAddrMapSection (const MCSection & TextSec) const
Definition at line 1135 of file MCObjectFileInfo.cpp.
References llvm::MCContext::IsELF, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_LINK_ORDER, and llvm::ELF::SHT_LLVM_BB_ADDR_MAP.
Referenced by llvm::AsmPrinter::emitBBAddrMapSection().
getBSSSection()
MCSection * llvm::MCObjectFileInfo::getBSSSection () const inline
Definition at line 266 of file MCObjectFileInfo.h.
References BSSSection.
Referenced by llvm::MCWinCOFFStreamer::emitLocalCommonSymbol().
getCOFFDebugSymbolsSection()
MCSection * llvm::MCObjectFileInfo::getCOFFDebugSymbolsSection () const inline
Definition at line 337 of file MCObjectFileInfo.h.
References COFFDebugSymbolsSection.
Referenced by llvm::CodeViewDebug::beginModule().
getCOFFDebugTypesSection()
MCSection * llvm::MCObjectFileInfo::getCOFFDebugTypesSection () const inline
Definition at line 340 of file MCObjectFileInfo.h.
References COFFDebugTypesSection.
getCOFFGlobalTypeHashesSection()
MCSection * llvm::MCObjectFileInfo::getCOFFGlobalTypeHashesSection () const inline
Definition at line 343 of file MCObjectFileInfo.h.
References COFFGlobalTypeHashesSection.
getCompactUnwindDwarfEHFrameOnly()
unsigned llvm::MCObjectFileInfo::getCompactUnwindDwarfEHFrameOnly () const inline
Definition at line 259 of file MCObjectFileInfo.h.
References CompactUnwindDwarfEHFrameOnly.
Referenced by llvm::MCDwarfFrameEmitter::Emit().
getCompactUnwindSection()
MCSection * llvm::MCObjectFileInfo::getCompactUnwindSection () const inline
Definition at line 269 of file MCObjectFileInfo.h.
References CompactUnwindSection.
Referenced by llvm::MCDwarfFrameEmitter::Emit(), and llvm::X86FrameLowering::enableShrinkWrapping().
getConstDataCoalSection()
const MCSection * llvm::MCObjectFileInfo::getConstDataCoalSection () const inline
Definition at line 397 of file MCObjectFileInfo.h.
References ConstDataCoalSection.
getConstDataSection()
const MCSection * llvm::MCObjectFileInfo::getConstDataSection () const inline
Definition at line 395 of file MCObjectFileInfo.h.
References ConstDataSection.
getConstTextCoalSection()
const MCSection * llvm::MCObjectFileInfo::getConstTextCoalSection () const inline
Definition at line 392 of file MCObjectFileInfo.h.
References ConstTextCoalSection.
getContext()
MCContext & llvm::MCObjectFileInfo::getContext () const inline
Definition at line 245 of file MCObjectFileInfo.h.
Referenced by llvm::TargetLoweringObjectFile::emitCGProfileMetadata(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::TargetLoweringObjectFile::getCallSiteEncoding(), llvm::TargetLoweringObjectFileELF::getCFIPersonalitySymbol(), llvm::TargetLoweringObjectFile::getDebugThreadLocalSymbol(), llvm::ARMElfTargetObjectFile::getDebugThreadLocalSymbol(), llvm::MipsTargetObjectFile::getDebugThreadLocalSymbol(), llvm::X86ELFTargetObjectFile::getDebugThreadLocalSymbol(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileXCOFF::getExplicitSectionGlobal(), DXILTargetObjectFile::getExplicitSectionGlobal(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::XCoreTargetObjectFile::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileXCOFF::getFunctionEntryPointSymbol(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::AArch64_MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::X86_64MachoTargetObjectFile::getIndirectSymViaGOTPCRel(), llvm::ARMElfTargetObjectFile::getIndirectSymViaRWPI(), llvm::TargetLoweringObjectFileELF::getSectionForCommandLines(), llvm::TargetLoweringObjectFileMachO::getSectionForCommandLines(), llvm::TargetLoweringObjectFileCOFF::getSectionForConstant(), llvm::TargetLoweringObjectFileXCOFF::getSectionForExternalReference(), llvm::TargetLoweringObjectFileXCOFF::getSectionForFunctionDescriptor(), llvm::TargetLoweringObjectFileELF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileXCOFF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileELF::getSectionForLSDA(), llvm::TargetLoweringObjectFileXCOFF::getSectionForLSDA(), llvm::TargetLoweringObjectFileELF::getSectionForMachineBasicBlock(), llvm::TargetLoweringObjectFileXCOFF::getSectionForTOCEntry(), llvm::TargetLoweringObjectFileELF::getStaticCtorSection(), llvm::TargetLoweringObjectFileCOFF::getStaticCtorSection(), llvm::TargetLoweringObjectFileWasm::getStaticCtorSection(), llvm::TargetLoweringObjectFileELF::getStaticDtorSection(), llvm::TargetLoweringObjectFileCOFF::getStaticDtorSection(), llvm::TargetMachine::getSymbol(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::RISCVMCObjectFileInfo::getTextSectionAlignment(), llvm::RISCVELFTargetObjectFile::getTextSectionAlignment(), llvm::TargetLoweringObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::ARMElfTargetObjectFile::getTTypeGlobalReference(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), llvm::X86_64MachoTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeReference(), llvm::TargetLoweringObjectFileELF::getUniqueSectionForFunction(), llvm::HexagonTargetObjectFile::Initialize(), llvm::LanaiTargetObjectFile::Initialize(), llvm::M68kELFTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), llvm::RISCVELFTargetObjectFile::Initialize(), llvm::TargetLoweringObjectFileELF::InitializeELF(), llvm::TargetLoweringObjectFileWasm::InitializeWasm(), llvm::TargetLoweringObjectFileELF::lowerDSOLocalEquivalent(), llvm::TargetLoweringObjectFileELF::lowerRelativeReference(), llvm::TargetLoweringObjectFileCOFF::lowerRelativeReference(), llvm::TargetLoweringObjectFileWasm::lowerRelativeReference(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::R600AsmPrinter::runOnMachineFunction(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileWasm::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileGOFF::SelectSectionForGlobal(), and llvm::AVRTargetObjectFile::SelectSectionForGlobal().
getCStringSection()
const MCSection * llvm::MCObjectFileInfo::getCStringSection () const inline
Definition at line 389 of file MCObjectFileInfo.h.
References CStringSection.
getDarwinTargetVariantSDKVersion()
const VersionTuple & llvm::MCObjectFileInfo::getDarwinTargetVariantSDKVersion () const inline
Definition at line 488 of file MCObjectFileInfo.h.
getDarwinTargetVariantTriple()
const Triple * llvm::MCObjectFileInfo::getDarwinTargetVariantTriple () const inline
Definition at line 480 of file MCObjectFileInfo.h.
getDataBSSSection()
MCSection * llvm::MCObjectFileInfo::getDataBSSSection () const inline
Definition at line 401 of file MCObjectFileInfo.h.
References DataBSSSection.
getDataCoalSection()
const MCSection * llvm::MCObjectFileInfo::getDataCoalSection () const inline
Definition at line 396 of file MCObjectFileInfo.h.
References DataCoalSection.
getDataCommonSection()
const MCSection * llvm::MCObjectFileInfo::getDataCommonSection () const inline
Definition at line 400 of file MCObjectFileInfo.h.
References DataCommonSection.
getDataRelROSection()
MCSection * llvm::MCObjectFileInfo::getDataRelROSection () const inline
Definition at line 370 of file MCObjectFileInfo.h.
References DataRelROSection.
getDataSection()
MCSection * llvm::MCObjectFileInfo::getDataSection () const inline
Definition at line 265 of file MCObjectFileInfo.h.
References DataSection.
Referenced by llvm::AsmPrinter::doFinalization(), and llvm::NVPTXTargetObjectFile::SelectSectionForGlobal().
getDrectveSection()
MCSection * llvm::MCObjectFileInfo::getDrectveSection () const inline
Definition at line 423 of file MCObjectFileInfo.h.
References DrectveSection.
Referenced by llvm::MCWinCOFFStreamer::emitCommonSymbol().
getDwarfAbbrevDWOSection()
MCSection * llvm::MCObjectFileInfo::getDwarfAbbrevDWOSection () const inline
Definition at line 316 of file MCObjectFileInfo.h.
References DwarfAbbrevDWOSection.
Referenced by isDwarfSection().
getDwarfAbbrevSection()
MCSection * llvm::MCObjectFileInfo::getDwarfAbbrevSection () const inline
Definition at line 270 of file MCObjectFileInfo.h.
References DwarfAbbrevSection.
Referenced by llvm::MCGenDwarfInfo::Emit(), llvm::DwarfUnit::emitCommonHeader(), EmitGenDwarfAbbrev(), and isDwarfSection().
getDwarfAccelNamespaceSection()
MCSection * llvm::MCObjectFileInfo::getDwarfAccelNamespaceSection () const inline
Definition at line 305 of file MCObjectFileInfo.h.
References DwarfAccelNamespaceSection.
Referenced by isDwarfSection().
getDwarfAccelNamesSection()
MCSection * llvm::MCObjectFileInfo::getDwarfAccelNamesSection () const inline
Definition at line 301 of file MCObjectFileInfo.h.
References DwarfAccelNamesSection.
Referenced by isDwarfSection().
getDwarfAccelObjCSection()
MCSection * llvm::MCObjectFileInfo::getDwarfAccelObjCSection () const inline
Definition at line 304 of file MCObjectFileInfo.h.
References DwarfAccelObjCSection.
Referenced by isDwarfSection().
getDwarfAccelTypesSection()
MCSection * llvm::MCObjectFileInfo::getDwarfAccelTypesSection () const inline
Definition at line 308 of file MCObjectFileInfo.h.
References DwarfAccelTypesSection.
Referenced by isDwarfSection().
getDwarfAddrSection()
MCSection * llvm::MCObjectFileInfo::getDwarfAddrSection () const inline
Definition at line 322 of file MCObjectFileInfo.h.
References DwarfAddrSection.
Referenced by llvm::DwarfCompileUnit::addAddrTableBase(), and isDwarfSection().
getDwarfARangesSection()
MCSection * llvm::MCObjectFileInfo::getDwarfARangesSection () const inline
Definition at line 291 of file MCObjectFileInfo.h.
References DwarfARangesSection.
Referenced by llvm::MCGenDwarfInfo::Emit(), EmitGenDwarfAranges(), and isDwarfSection().
getDwarfCUIndexSection()
MCSection * llvm::MCObjectFileInfo::getDwarfCUIndexSection () const inline
Definition at line 333 of file MCObjectFileInfo.h.
References DwarfCUIndexSection.
Referenced by isDwarfSection().
getDwarfDebugInlineSection()
const MCSection * llvm::MCObjectFileInfo::getDwarfDebugInlineSection () const inline
Definition at line 286 of file MCObjectFileInfo.h.
References DwarfDebugInlineSection.
Referenced by isDwarfSection().
getDwarfDebugNamesSection()
MCSection * llvm::MCObjectFileInfo::getDwarfDebugNamesSection () const inline
Definition at line 298 of file MCObjectFileInfo.h.
References DwarfDebugNamesSection.
Referenced by isDwarfSection().
getDwarfFrameSection()
MCSection * llvm::MCObjectFileInfo::getDwarfFrameSection () const inline
Definition at line 277 of file MCObjectFileInfo.h.
References DwarfFrameSection.
Referenced by llvm::MCDwarfFrameEmitter::Emit(), and isDwarfSection().
getDwarfGnuPubNamesSection()
MCSection * llvm::MCObjectFileInfo::getDwarfGnuPubNamesSection () const inline
Definition at line 280 of file MCObjectFileInfo.h.
References DwarfGnuPubNamesSection.
Referenced by isDwarfSection().
getDwarfGnuPubTypesSection()
MCSection * llvm::MCObjectFileInfo::getDwarfGnuPubTypesSection () const inline
Definition at line 283 of file MCObjectFileInfo.h.
References DwarfGnuPubTypesSection.
Referenced by isDwarfSection().
getDwarfInfoDWOSection()
MCSection * llvm::MCObjectFileInfo::getDwarfInfoDWOSection () const inline
Definition at line 311 of file MCObjectFileInfo.h.
References DwarfInfoDWOSection.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType(), and isDwarfSection().
getDwarfInfoSection() [1/2]
MCSection * llvm::MCObjectFileInfo::getDwarfInfoSection () const inline
Definition at line 271 of file MCObjectFileInfo.h.
References DwarfInfoSection.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType(), llvm::MCGenDwarfInfo::Emit(), EmitGenDwarfInfo(), and isDwarfSection().
getDwarfInfoSection() [2/2]
MCSection * llvm::MCObjectFileInfo::getDwarfInfoSection (uint64_t Hash) const inline
Definition at line 272 of file MCObjectFileInfo.h.
getDwarfLineDWOSection()
MCSection * llvm::MCObjectFileInfo::getDwarfLineDWOSection () const inline
Definition at line 318 of file MCObjectFileInfo.h.
References DwarfLineDWOSection.
Referenced by isDwarfSection().
getDwarfLineSection()
MCSection * llvm::MCObjectFileInfo::getDwarfLineSection () const inline
Definition at line 275 of file MCObjectFileInfo.h.
References DwarfLineSection.
Referenced by llvm::DwarfCompileUnit::applyStmtList(), llvm::MCDwarfLineTable::emit(), llvm::DwarfCompileUnit::initStmtList(), and isDwarfSection().
getDwarfLineStrSection()
MCSection * llvm::MCObjectFileInfo::getDwarfLineStrSection () const inline
Definition at line 276 of file MCObjectFileInfo.h.
References DwarfLineStrSection.
Referenced by isDwarfSection().
getDwarfLocDWOSection()
MCSection * llvm::MCObjectFileInfo::getDwarfLocDWOSection () const inline
Definition at line 319 of file MCObjectFileInfo.h.
References DwarfLocDWOSection.
Referenced by isDwarfSection().
getDwarfLoclistsDWOSection()
MCSection * llvm::MCObjectFileInfo::getDwarfLoclistsDWOSection () const inline
Definition at line 326 of file MCObjectFileInfo.h.
References DwarfLoclistsDWOSection.
getDwarfLoclistsSection()
MCSection * llvm::MCObjectFileInfo::getDwarfLoclistsSection () const inline
Definition at line 294 of file MCObjectFileInfo.h.
References DwarfLoclistsSection.
getDwarfLocSection()
MCSection * llvm::MCObjectFileInfo::getDwarfLocSection () const inline
Definition at line 290 of file MCObjectFileInfo.h.
References DwarfLocSection.
Referenced by isDwarfSection().
getDwarfMacinfoDWOSection()
MCSection * llvm::MCObjectFileInfo::getDwarfMacinfoDWOSection () const inline
Definition at line 330 of file MCObjectFileInfo.h.
References DwarfMacinfoDWOSection.
getDwarfMacinfoSection()
MCSection * llvm::MCObjectFileInfo::getDwarfMacinfoSection () const inline
Definition at line 295 of file MCObjectFileInfo.h.
References DwarfMacinfoSection.
Referenced by isDwarfSection().
getDwarfMacroDWOSection()
MCSection * llvm::MCObjectFileInfo::getDwarfMacroDWOSection () const inline
Definition at line 329 of file MCObjectFileInfo.h.
References DwarfMacroDWOSection.
getDwarfMacroSection()
MCSection * llvm::MCObjectFileInfo::getDwarfMacroSection () const inline
Definition at line 296 of file MCObjectFileInfo.h.
References DwarfMacroSection.
getDwarfPubNamesSection()
MCSection * llvm::MCObjectFileInfo::getDwarfPubNamesSection () const inline
Definition at line 278 of file MCObjectFileInfo.h.
References DwarfPubNamesSection.
Referenced by isDwarfSection().
getDwarfPubTypesSection()
MCSection * llvm::MCObjectFileInfo::getDwarfPubTypesSection () const inline
Definition at line 279 of file MCObjectFileInfo.h.
References DwarfPubTypesSection.
Referenced by isDwarfSection().
getDwarfRangesSection()
MCSection * llvm::MCObjectFileInfo::getDwarfRangesSection () const inline
Definition at line 292 of file MCObjectFileInfo.h.
References DwarfRangesSection.
Referenced by llvm::DwarfCompileUnit::addScopeRangeList(), emitGenDwarfRanges(), and isDwarfSection().
getDwarfRnglistsDWOSection()
MCSection * llvm::MCObjectFileInfo::getDwarfRnglistsDWOSection () const inline
Definition at line 323 of file MCObjectFileInfo.h.
References DwarfRnglistsDWOSection.
getDwarfRnglistsSection()
MCSection * llvm::MCObjectFileInfo::getDwarfRnglistsSection () const inline
Definition at line 293 of file MCObjectFileInfo.h.
References DwarfRnglistsSection.
Referenced by llvm::DwarfUnit::addRnglistsBase(), and emitGenDwarfRanges().
getDwarfStrDWOSection()
MCSection * llvm::MCObjectFileInfo::getDwarfStrDWOSection () const inline
Definition at line 317 of file MCObjectFileInfo.h.
References DwarfStrDWOSection.
Referenced by isDwarfSection().
getDwarfStrOffDWOSection()
MCSection * llvm::MCObjectFileInfo::getDwarfStrOffDWOSection () const inline
Definition at line 320 of file MCObjectFileInfo.h.
References DwarfStrOffDWOSection.
Referenced by isDwarfSection().
getDwarfStrOffSection()
MCSection * llvm::MCObjectFileInfo::getDwarfStrOffSection () const inline
Definition at line 321 of file MCObjectFileInfo.h.
References DwarfStrOffSection.
Referenced by llvm::DwarfUnit::addStringOffsetsStart(), and isDwarfSection().
getDwarfStrSection()
MCSection * llvm::MCObjectFileInfo::getDwarfStrSection () const inline
Definition at line 289 of file MCObjectFileInfo.h.
References DwarfStrSection.
Referenced by isDwarfSection().
getDwarfSwiftASTSection()
MCSection * llvm::MCObjectFileInfo::getDwarfSwiftASTSection () const inline
Definition at line 335 of file MCObjectFileInfo.h.
References DwarfSwiftASTSection.
Referenced by isDwarfSection().
getDwarfTUIndexSection()
MCSection * llvm::MCObjectFileInfo::getDwarfTUIndexSection () const inline
Definition at line 334 of file MCObjectFileInfo.h.
References DwarfTUIndexSection.
Referenced by isDwarfSection().
getDwarfTypesDWOSection()
MCSection * llvm::MCObjectFileInfo::getDwarfTypesDWOSection () const inline
Definition at line 315 of file MCObjectFileInfo.h.
References DwarfTypesDWOSection.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType(), and isDwarfSection().
getDwarfTypesSection()
MCSection * llvm::MCObjectFileInfo::getDwarfTypesSection (uint64_t Hash) const inline
Definition at line 312 of file MCObjectFileInfo.h.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
getEHFrameSection()
MCSection * llvm::MCObjectFileInfo::getEHFrameSection () const inline
Definition at line 439 of file MCObjectFileInfo.h.
References EHFrameSection.
getEightByteConstantSection()
const MCSection * llvm::MCObjectFileInfo::getEightByteConstantSection () const inline
Definition at line 405 of file MCObjectFileInfo.h.
References EightByteConstantSection.
getFaultMapSection()
MCSection * llvm::MCObjectFileInfo::getFaultMapSection () const inline
Definition at line 352 of file MCObjectFileInfo.h.
References FaultMapSection.
Referenced by llvm::FaultMaps::serializeToFaultMapSection().
getFDEEncoding()
unsigned llvm::MCObjectFileInfo::getFDEEncoding () const inline
Definition at line 257 of file MCObjectFileInfo.h.
References FDECFIEncoding.
getFourByteConstantSection()
const MCSection * llvm::MCObjectFileInfo::getFourByteConstantSection () const inline
Definition at line 402 of file MCObjectFileInfo.h.
References FourByteConstantSection.
getGEHContSection()
MCSection * llvm::MCObjectFileInfo::getGEHContSection () const inline
Definition at line 427 of file MCObjectFileInfo.h.
References GEHContSection.
Referenced by llvm::WinException::endModule().
getGFIDsSection()
MCSection * llvm::MCObjectFileInfo::getGFIDsSection () const inline
Definition at line 428 of file MCObjectFileInfo.h.
References GFIDsSection.
Referenced by llvm::WinCFGuard::endModule().
getGIATsSection()
MCSection * llvm::MCObjectFileInfo::getGIATsSection () const inline
Definition at line 429 of file MCObjectFileInfo.h.
References GIATsSection.
Referenced by llvm::WinCFGuard::endModule().
getGLJMPSection()
MCSection * llvm::MCObjectFileInfo::getGLJMPSection () const inline
Definition at line 430 of file MCObjectFileInfo.h.
References GLJMPSection.
Referenced by llvm::WinCFGuard::endModule().
getKCFITrapSection()
MCSection * MCObjectFileInfo::getKCFITrapSection (const MCSection & TextSec) const
Definition at line 1155 of file MCObjectFileInfo.cpp.
References llvm::MCContext::IsELF, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_LINK_ORDER, and llvm::ELF::SHT_PROGBITS.
Referenced by llvm::AsmPrinter::emitKCFITrapEntry().
getLazySymbolPointerSection()
MCSection * llvm::MCObjectFileInfo::getLazySymbolPointerSection () const inline
Definition at line 411 of file MCObjectFileInfo.h.
References LazySymbolPointerSection.
getLLVMStatsSection()
MCSection * MCObjectFileInfo::getLLVMStatsSection () const
Definition at line 1215 of file MCObjectFileInfo.cpp.
References LLVMStatsSection.
getLSDASection()
MCSection * llvm::MCObjectFileInfo::getLSDASection () const inline
Definition at line 268 of file MCObjectFileInfo.h.
References LSDASection.
getMergeableConst16Section()
const MCSection * llvm::MCObjectFileInfo::getMergeableConst16Section () const inline
Definition at line 377 of file MCObjectFileInfo.h.
References MergeableConst16Section.
getMergeableConst32Section()
const MCSection * llvm::MCObjectFileInfo::getMergeableConst32Section () const inline
Definition at line 380 of file MCObjectFileInfo.h.
References MergeableConst32Section.
getMergeableConst4Section()
const MCSection * llvm::MCObjectFileInfo::getMergeableConst4Section () const inline
Definition at line 371 of file MCObjectFileInfo.h.
References MergeableConst4Section.
getMergeableConst8Section()
const MCSection * llvm::MCObjectFileInfo::getMergeableConst8Section () const inline
Definition at line 374 of file MCObjectFileInfo.h.
References MergeableConst8Section.
getNonLazySymbolPointerSection()
MCSection * llvm::MCObjectFileInfo::getNonLazySymbolPointerSection () const inline
Definition at line 414 of file MCObjectFileInfo.h.
References NonLazySymbolPointerSection.
getOmitDwarfIfHaveCompactUnwind()
bool llvm::MCObjectFileInfo::getOmitDwarfIfHaveCompactUnwind () const inline
Definition at line 253 of file MCObjectFileInfo.h.
References OmitDwarfIfHaveCompactUnwind.
Referenced by llvm::MCDwarfFrameEmitter::Emit().
getPCSection()
MCSection * MCObjectFileInfo::getPCSection (StringRef Name, const MCSection * TextSec) const
Definition at line 1219 of file MCObjectFileInfo.cpp.
References getTextSection(), llvm::MCContext::IsELF, Name, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHF_WRITE, and llvm::ELF::SHT_PROGBITS.
Referenced by llvm::AsmPrinter::emitPCSections().
getPDataSection()
MCSection * llvm::MCObjectFileInfo::getPDataSection () const inline
Definition at line 424 of file MCObjectFileInfo.h.
References PDataSection.
getPPA1Section()
MCSection * llvm::MCObjectFileInfo::getPPA1Section () const inline
Definition at line 433 of file MCObjectFileInfo.h.
References PPA1Section.
getPseudoProbeDescSection()
MCSection * MCObjectFileInfo::getPseudoProbeDescSection (StringRef FuncName) const
Definition at line 1192 of file MCObjectFileInfo.cpp.
References llvm::StringRef::empty(), llvm::MCSectionELF::getFlags(), llvm::MCContext::IsELF, PseudoProbeDescSection, and llvm::ELF::SHF_GROUP.
getPseudoProbeSection()
MCSection * MCObjectFileInfo::getPseudoProbeSection (const MCSection & TextSec) const
Definition at line 1174 of file MCObjectFileInfo.cpp.
References llvm::MCSection::getName(), llvm::MCContext::IsELF, PseudoProbeSection, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_LINK_ORDER, and llvm::ELF::SHT_PROGBITS.
getReadOnlySection()
MCSection * llvm::MCObjectFileInfo::getReadOnlySection () const inline
Definition at line 267 of file MCObjectFileInfo.h.
References ReadOnlySection.
getRemarksSection()
MCSection * llvm::MCObjectFileInfo::getRemarksSection () const inline
Definition at line 353 of file MCObjectFileInfo.h.
References RemarksSection.
Referenced by llvm::AsmPrinter::emitRemarksSection().
getSDKVersion()
const VersionTuple & llvm::MCObjectFileInfo::getSDKVersion () const inline
Definition at line 474 of file MCObjectFileInfo.h.
getSixteenByteConstantSection()
const MCSection * llvm::MCObjectFileInfo::getSixteenByteConstantSection () const inline
Definition at line 408 of file MCObjectFileInfo.h.
References SixteenByteConstantSection.
getStackMapSection()
MCSection * llvm::MCObjectFileInfo::getStackMapSection () const inline
Definition at line 351 of file MCObjectFileInfo.h.
References StackMapSection.
Referenced by llvm::StackMaps::serializeToStackMapSection().
getStackSizesSection()
MCSection * MCObjectFileInfo::getStackSizesSection (const MCSection & TextSec) const
Definition at line 1116 of file MCObjectFileInfo.cpp.
References llvm::MCContext::IsELF, llvm::ELF::SHF_GROUP, llvm::ELF::SHF_LINK_ORDER, llvm::ELF::SHT_PROGBITS, and StackSizesSection.
Referenced by llvm::AsmPrinter::emitStackSizeSection().
getSupportsCompactUnwindWithoutEHFrame()
bool llvm::MCObjectFileInfo::getSupportsCompactUnwindWithoutEHFrame () const inline
Definition at line 250 of file MCObjectFileInfo.h.
References SupportsCompactUnwindWithoutEHFrame.
Referenced by llvm::MCDwarfFrameEmitter::Emit().
getSupportsWeakOmittedEHFrame()
bool llvm::MCObjectFileInfo::getSupportsWeakOmittedEHFrame () const inline
Definition at line 247 of file MCObjectFileInfo.h.
References SupportsWeakOmittedEHFrame.
getSwift5ReflectionSection()
MCSection * llvm::MCObjectFileInfo::getSwift5ReflectionSection (llvm::binaryformat::Swift5ReflectionSectionKind ReflSectionKind) inline
Definition at line 444 of file MCObjectFileInfo.h.
References Swift5ReflectionSections, and llvm::binaryformat::unknown.
getSXDataSection()
MCSection * llvm::MCObjectFileInfo::getSXDataSection () const inline
Definition at line 426 of file MCObjectFileInfo.h.
References SXDataSection.
Referenced by llvm::MCWinCOFFStreamer::emitCOFFSafeSEH().
getTextCoalSection()
MCSection * llvm::MCObjectFileInfo::getTextCoalSection () const inline
Definition at line 391 of file MCObjectFileInfo.h.
References TextCoalSection.
getTextSection()
MCSection * llvm::MCObjectFileInfo::getTextSection () const inline
Definition at line 264 of file MCObjectFileInfo.h.
References TextSection.
Referenced by llvm::MipsAsmPrinter::emitEndOfAsmFile(), llvm::X86AsmPrinter::emitStartOfAsmFile(), getPCSection(), and llvm::TargetLoweringObjectFileGOFF::SelectSectionForGlobal().
getTextSectionAlignment()
virtual unsigned llvm::MCObjectFileInfo::getTextSectionAlignment () const inline virtual
Reimplemented in llvm::RISCVMCObjectFileInfo, and llvm::RISCVELFTargetObjectFile.
Definition at line 263 of file MCObjectFileInfo.h.
getThreadLocalPointerSection()
MCSection * llvm::MCObjectFileInfo::getThreadLocalPointerSection () const inline
Definition at line 417 of file MCObjectFileInfo.h.
References ThreadLocalPointerSection.
getTLSBSSSection()
MCSection * llvm::MCObjectFileInfo::getTLSBSSSection () const inline
Definition at line 349 of file MCObjectFileInfo.h.
References TLSBSSSection.
Referenced by llvm::AsmPrinter::emitGlobalVariable().
getTLSDataSection()
const MCSection * llvm::MCObjectFileInfo::getTLSDataSection () const inline
Definition at line 348 of file MCObjectFileInfo.h.
References TLSDataSection.
getTLSExtraDataSection()
MCSection * llvm::MCObjectFileInfo::getTLSExtraDataSection () const inline
Definition at line 347 of file MCObjectFileInfo.h.
References TLSExtraDataSection.
Referenced by llvm::AsmPrinter::emitGlobalVariable().
getTLSThreadInitSection()
const MCSection * llvm::MCObjectFileInfo::getTLSThreadInitSection () const inline
Definition at line 386 of file MCObjectFileInfo.h.
References TLSThreadInitSection.
getTLSTLVSection()
const MCSection * llvm::MCObjectFileInfo::getTLSTLVSection () const inline
Definition at line 385 of file MCObjectFileInfo.h.
References TLSTLVSection.
getTOCBaseSection()
MCSection * llvm::MCObjectFileInfo::getTOCBaseSection () const inline
Definition at line 437 of file MCObjectFileInfo.h.
References TOCBaseSection.
getUStringSection()
const MCSection * llvm::MCObjectFileInfo::getUStringSection () const inline
Definition at line 390 of file MCObjectFileInfo.h.
References UStringSection.
getXDataSection()
MCSection * llvm::MCObjectFileInfo::getXDataSection () const inline
Definition at line 425 of file MCObjectFileInfo.h.
References XDataSection.
initMCObjectFileInfo()
void MCObjectFileInfo::initMCObjectFileInfo (MCContext & MCCtx, bool PIC, bool LargeCodeModel = false)
Definition at line 1042 of file MCObjectFileInfo.cpp.
References CompactUnwindDwarfEHFrameOnly, CompactUnwindSection, llvm::dwarf::DW_EH_PE_absptr, DwarfAccelNamespaceSection, DwarfAccelNamesSection, DwarfAccelObjCSection, DwarfAccelTypesSection, EHFrameSection, FDECFIEncoding, llvm::MCContext::IsCOFF, llvm::MCContext::IsDXContainer, llvm::MCContext::IsELF, llvm::MCContext::IsGOFF, llvm::MCContext::IsMachO, llvm::MCContext::IsSPIRV, llvm::MCContext::IsWasm, llvm::MCContext::IsXCOFF, OmitDwarfIfHaveCompactUnwind, PIC, SupportsCompactUnwindWithoutEHFrame, and SupportsWeakOmittedEHFrame.
Referenced by llvm::Target::createMCObjectFileInfo(), createRISCVMCObjectFileInfo(), and llvm::TargetLoweringObjectFile::Initialize().
isPositionIndependent()
bool llvm::MCObjectFileInfo::isPositionIndependent () const inline
Definition at line 441 of file MCObjectFileInfo.h.
Referenced by llvm::MipsAsmPrinter::emitStartOfAsmFile(), and llvm::TargetLoweringObjectFileELF::Initialize().
setDarwinTargetVariantSDKVersion()
void llvm::MCObjectFileInfo::setDarwinTargetVariantSDKVersion (const VersionTuple & TheSDKVersion) inline
Definition at line 484 of file MCObjectFileInfo.h.
setDarwinTargetVariantTriple()
void llvm::MCObjectFileInfo::setDarwinTargetVariantTriple (const Triple & T) inline
Definition at line 476 of file MCObjectFileInfo.h.
References T.
setSDKVersion()
void llvm::MCObjectFileInfo::setSDKVersion (const VersionTuple & TheSDKVersion) inline
Definition at line 470 of file MCObjectFileInfo.h.
Member Data Documentation
ADASection
MCSection* llvm::MCObjectFileInfo::ADASection = nullptr protected
Definition at line 230 of file MCObjectFileInfo.h.
Referenced by getADASection().
AddrSigSection
MCSection* llvm::MCObjectFileInfo::AddrSigSection = nullptr protected
Definition at line 216 of file MCObjectFileInfo.h.
Referenced by getAddrSigSection().
BSSSection
MCSection* llvm::MCObjectFileInfo::BSSSection = nullptr protected
Section that is default initialized to zero.
Definition at line 59 of file MCObjectFileInfo.h.
Referenced by getBSSSection(), llvm::XCoreTargetObjectFile::Initialize(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), llvm::HexagonTargetObjectFile::SelectSectionForGlobal(), and llvm::XCoreTargetObjectFile::SelectSectionForGlobal().
COFFDebugSymbolsSection
MCSection* llvm::MCObjectFileInfo::COFFDebugSymbolsSection = nullptr protected
Definition at line 140 of file MCObjectFileInfo.h.
Referenced by getCOFFDebugSymbolsSection().
COFFDebugTypesSection
MCSection* llvm::MCObjectFileInfo::COFFDebugTypesSection = nullptr protected
Definition at line 141 of file MCObjectFileInfo.h.
Referenced by getCOFFDebugTypesSection().
COFFGlobalTypeHashesSection
MCSection* llvm::MCObjectFileInfo::COFFGlobalTypeHashesSection = nullptr protected
Definition at line 142 of file MCObjectFileInfo.h.
Referenced by getCOFFGlobalTypeHashesSection().
CompactUnwindDwarfEHFrameOnly
unsigned llvm::MCObjectFileInfo::CompactUnwindDwarfEHFrameOnly = 0 protected
Compact unwind encoding indicating that we should emit only an EH frame.
Definition at line 50 of file MCObjectFileInfo.h.
Referenced by getCompactUnwindDwarfEHFrameOnly(), and initMCObjectFileInfo().
CompactUnwindSection
MCSection* llvm::MCObjectFileInfo::CompactUnwindSection = nullptr protected
If exception handling is supported by the target and the target can support a compact representation of the CIE and FDE, this is the section to emit them into.
Definition at line 74 of file MCObjectFileInfo.h.
Referenced by getCompactUnwindSection(), and initMCObjectFileInfo().
ConstDataCoalSection
MCSection* llvm::MCObjectFileInfo::ConstDataCoalSection = nullptr protected
Definition at line 207 of file MCObjectFileInfo.h.
Referenced by getConstDataCoalSection(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
ConstDataSection
MCSection* llvm::MCObjectFileInfo::ConstDataSection = nullptr protected
Definition at line 205 of file MCObjectFileInfo.h.
Referenced by getConstDataSection(), llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
ConstTextCoalSection
MCSection* llvm::MCObjectFileInfo::ConstTextCoalSection = nullptr protected
Definition at line 204 of file MCObjectFileInfo.h.
Referenced by getConstTextCoalSection(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
CStringSection
MCSection* llvm::MCObjectFileInfo::CStringSection = nullptr protected
Definition at line 201 of file MCObjectFileInfo.h.
Referenced by getCStringSection(), llvm::XCoreTargetObjectFile::Initialize(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), and llvm::XCoreTargetObjectFile::SelectSectionForGlobal().
DataBSSSection
MCSection* llvm::MCObjectFileInfo::DataBSSSection = nullptr protected
Definition at line 209 of file MCObjectFileInfo.h.
Referenced by getDataBSSSection(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
DataCoalSection
MCSection* llvm::MCObjectFileInfo::DataCoalSection = nullptr protected
Definition at line 206 of file MCObjectFileInfo.h.
Referenced by getDataCoalSection(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
DataCommonSection
MCSection* llvm::MCObjectFileInfo::DataCommonSection = nullptr protected
Definition at line 208 of file MCObjectFileInfo.h.
Referenced by getDataCommonSection(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
DataRelROSection
MCSection* llvm::MCObjectFileInfo::DataRelROSection = nullptr protected
Definition at line 183 of file MCObjectFileInfo.h.
Referenced by getDataRelROSection(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::XCoreTargetObjectFile::Initialize(), and llvm::XCoreTargetObjectFile::SelectSectionForGlobal().
DataSection
MCSection* llvm::MCObjectFileInfo::DataSection = nullptr protected
Section directive for standard data.
Definition at line 56 of file MCObjectFileInfo.h.
Referenced by getDataSection(), llvm::NVPTXTargetObjectFile::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFile::getSectionForConstant(), llvm::XCoreTargetObjectFile::Initialize(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), and llvm::XCoreTargetObjectFile::SelectSectionForGlobal().
DrectveSection
MCSection* llvm::MCObjectFileInfo::DrectveSection = nullptr protected
COFF specific sections.
Definition at line 219 of file MCObjectFileInfo.h.
Referenced by getDrectveSection().
DwarfAbbrevDWOSection
MCSection* llvm::MCObjectFileInfo::DwarfAbbrevDWOSection = nullptr protected
Definition at line 108 of file MCObjectFileInfo.h.
Referenced by getDwarfAbbrevDWOSection().
DwarfAbbrevSection
MCSection* llvm::MCObjectFileInfo::DwarfAbbrevSection = nullptr protected
Definition at line 78 of file MCObjectFileInfo.h.
Referenced by getDwarfAbbrevSection().
DwarfAccelNamespaceSection
MCSection* llvm::MCObjectFileInfo::DwarfAccelNamespaceSection = nullptr protected
Definition at line 102 of file MCObjectFileInfo.h.
Referenced by getDwarfAccelNamespaceSection(), and initMCObjectFileInfo().
DwarfAccelNamesSection
MCSection* llvm::MCObjectFileInfo::DwarfAccelNamesSection = nullptr protected
Definition at line 100 of file MCObjectFileInfo.h.
Referenced by getDwarfAccelNamesSection(), and initMCObjectFileInfo().
DwarfAccelObjCSection
MCSection* llvm::MCObjectFileInfo::DwarfAccelObjCSection = nullptr protected
Definition at line 101 of file MCObjectFileInfo.h.
Referenced by getDwarfAccelObjCSection(), and initMCObjectFileInfo().
DwarfAccelTypesSection
MCSection* llvm::MCObjectFileInfo::DwarfAccelTypesSection = nullptr protected
Definition at line 103 of file MCObjectFileInfo.h.
Referenced by getDwarfAccelTypesSection(), and initMCObjectFileInfo().
DwarfAddrSection
MCSection* llvm::MCObjectFileInfo::DwarfAddrSection = nullptr protected
Definition at line 118 of file MCObjectFileInfo.h.
Referenced by getDwarfAddrSection().
DwarfARangesSection
MCSection* llvm::MCObjectFileInfo::DwarfARangesSection = nullptr protected
Definition at line 87 of file MCObjectFileInfo.h.
Referenced by getDwarfARangesSection().
DwarfCUIndexSection
MCSection* llvm::MCObjectFileInfo::DwarfCUIndexSection = nullptr protected
Definition at line 129 of file MCObjectFileInfo.h.
Referenced by getDwarfCUIndexSection().
DwarfDebugInlineSection
const MCSection* llvm::MCObjectFileInfo::DwarfDebugInlineSection = nullptr protected
Definition at line 84 of file MCObjectFileInfo.h.
Referenced by getDwarfDebugInlineSection().
DwarfDebugNamesSection
MCSection* llvm::MCObjectFileInfo::DwarfDebugNamesSection = nullptr protected
Accelerator table sections.
DwarfDebugNamesSection is the DWARF v5 accelerator table, while DwarfAccelNamesSection, DwarfAccelObjCSection, DwarfAccelNamespaceSection, DwarfAccelTypesSection are pre-DWARF v5 extensions.
Definition at line 99 of file MCObjectFileInfo.h.
Referenced by getDwarfDebugNamesSection().
DwarfFrameSection
MCSection* llvm::MCObjectFileInfo::DwarfFrameSection = nullptr protected
Definition at line 82 of file MCObjectFileInfo.h.
Referenced by getDwarfFrameSection().
DwarfGnuPubNamesSection
MCSection* llvm::MCObjectFileInfo::DwarfGnuPubNamesSection = nullptr protected
Section for newer gnu pubnames.
Definition at line 133 of file MCObjectFileInfo.h.
Referenced by getDwarfGnuPubNamesSection().
DwarfGnuPubTypesSection
MCSection* llvm::MCObjectFileInfo::DwarfGnuPubTypesSection = nullptr protected
Section for newer gnu pubtypes.
Definition at line 135 of file MCObjectFileInfo.h.
Referenced by getDwarfGnuPubTypesSection().
DwarfInfoDWOSection
MCSection* llvm::MCObjectFileInfo::DwarfInfoDWOSection = nullptr protected
Definition at line 106 of file MCObjectFileInfo.h.
Referenced by getDwarfInfoDWOSection().
DwarfInfoSection
MCSection* llvm::MCObjectFileInfo::DwarfInfoSection = nullptr protected
Definition at line 79 of file MCObjectFileInfo.h.
Referenced by getDwarfInfoSection().
DwarfLineDWOSection
MCSection* llvm::MCObjectFileInfo::DwarfLineDWOSection = nullptr protected
Definition at line 110 of file MCObjectFileInfo.h.
Referenced by getDwarfLineDWOSection().
DwarfLineSection
MCSection* llvm::MCObjectFileInfo::DwarfLineSection = nullptr protected
Definition at line 80 of file MCObjectFileInfo.h.
Referenced by getDwarfLineSection().
DwarfLineStrSection
MCSection* llvm::MCObjectFileInfo::DwarfLineStrSection = nullptr protected
Definition at line 81 of file MCObjectFileInfo.h.
Referenced by getDwarfLineStrSection().
DwarfLocDWOSection
MCSection* llvm::MCObjectFileInfo::DwarfLocDWOSection = nullptr protected
Definition at line 111 of file MCObjectFileInfo.h.
Referenced by getDwarfLocDWOSection().
DwarfLoclistsDWOSection
MCSection* llvm::MCObjectFileInfo::DwarfLoclistsDWOSection = nullptr protected
Definition at line 126 of file MCObjectFileInfo.h.
Referenced by getDwarfLoclistsDWOSection().
DwarfLoclistsSection
MCSection* llvm::MCObjectFileInfo::DwarfLoclistsSection = nullptr protected
The DWARF v5 locations list section.
Definition at line 122 of file MCObjectFileInfo.h.
Referenced by getDwarfLoclistsSection().
DwarfLocSection
MCSection* llvm::MCObjectFileInfo::DwarfLocSection = nullptr protected
Definition at line 86 of file MCObjectFileInfo.h.
Referenced by getDwarfLocSection().
DwarfMacinfoDWOSection
MCSection* llvm::MCObjectFileInfo::DwarfMacinfoDWOSection = nullptr protected
Definition at line 113 of file MCObjectFileInfo.h.
Referenced by getDwarfMacinfoDWOSection().
DwarfMacinfoSection
MCSection* llvm::MCObjectFileInfo::DwarfMacinfoSection = nullptr protected
Definition at line 89 of file MCObjectFileInfo.h.
Referenced by getDwarfMacinfoSection().
DwarfMacroDWOSection
MCSection* llvm::MCObjectFileInfo::DwarfMacroDWOSection = nullptr protected
Definition at line 114 of file MCObjectFileInfo.h.
Referenced by getDwarfMacroDWOSection().
DwarfMacroSection
MCSection* llvm::MCObjectFileInfo::DwarfMacroSection = nullptr protected
Definition at line 90 of file MCObjectFileInfo.h.
Referenced by getDwarfMacroSection().
DwarfPubNamesSection
MCSection* llvm::MCObjectFileInfo::DwarfPubNamesSection = nullptr protected
Definition at line 93 of file MCObjectFileInfo.h.
Referenced by getDwarfPubNamesSection().
DwarfPubTypesSection
MCSection* llvm::MCObjectFileInfo::DwarfPubTypesSection = nullptr protected
Definition at line 83 of file MCObjectFileInfo.h.
Referenced by getDwarfPubTypesSection().
DwarfRangesSection
MCSection* llvm::MCObjectFileInfo::DwarfRangesSection = nullptr protected
Definition at line 88 of file MCObjectFileInfo.h.
Referenced by getDwarfRangesSection().
DwarfRnglistsDWOSection
MCSection* llvm::MCObjectFileInfo::DwarfRnglistsDWOSection = nullptr protected
The DWARF v5 range and location list sections for fission.
Definition at line 125 of file MCObjectFileInfo.h.
Referenced by getDwarfRnglistsDWOSection().
DwarfRnglistsSection
MCSection* llvm::MCObjectFileInfo::DwarfRnglistsSection = nullptr protected
The DWARF v5 range list section.
Definition at line 120 of file MCObjectFileInfo.h.
Referenced by getDwarfRnglistsSection().
DwarfStrDWOSection
MCSection* llvm::MCObjectFileInfo::DwarfStrDWOSection = nullptr protected
Definition at line 109 of file MCObjectFileInfo.h.
Referenced by getDwarfStrDWOSection().
DwarfStrOffDWOSection
MCSection* llvm::MCObjectFileInfo::DwarfStrOffDWOSection = nullptr protected
Definition at line 112 of file MCObjectFileInfo.h.
Referenced by getDwarfStrOffDWOSection().
DwarfStrOffSection
MCSection* llvm::MCObjectFileInfo::DwarfStrOffSection = nullptr protected
The DWARF v5 string offset and address table sections.
Definition at line 117 of file MCObjectFileInfo.h.
Referenced by getDwarfStrOffSection().
DwarfStrSection
MCSection* llvm::MCObjectFileInfo::DwarfStrSection = nullptr protected
Definition at line 85 of file MCObjectFileInfo.h.
Referenced by getDwarfStrSection().
DwarfSwiftASTSection
MCSection* llvm::MCObjectFileInfo::DwarfSwiftASTSection = nullptr protected
Definition at line 138 of file MCObjectFileInfo.h.
Referenced by getDwarfSwiftASTSection().
DwarfTUIndexSection
MCSection* llvm::MCObjectFileInfo::DwarfTUIndexSection = nullptr protected
Definition at line 130 of file MCObjectFileInfo.h.
Referenced by getDwarfTUIndexSection().
DwarfTypesDWOSection
MCSection* llvm::MCObjectFileInfo::DwarfTypesDWOSection = nullptr protected
Definition at line 107 of file MCObjectFileInfo.h.
Referenced by getDwarfTypesDWOSection().
EHFrameSection
MCSection* llvm::MCObjectFileInfo::EHFrameSection = nullptr protected
EH frame section.
It is initialized on demand so it can be overwritten (with uniquing).
Definition at line 170 of file MCObjectFileInfo.h.
Referenced by getEHFrameSection(), and initMCObjectFileInfo().
EightByteConstantSection
MCSection* llvm::MCObjectFileInfo::EightByteConstantSection = nullptr protected
Definition at line 211 of file MCObjectFileInfo.h.
Referenced by getEightByteConstantSection(), llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
FaultMapSection
MCSection* llvm::MCObjectFileInfo::FaultMapSection = nullptr protected
FaultMap section.
Definition at line 162 of file MCObjectFileInfo.h.
Referenced by getFaultMapSection().
FDECFIEncoding
unsigned llvm::MCObjectFileInfo::FDECFIEncoding = 0 protected
FDE CFI encoding.
Controls the encoding of the begin label in the .eh_frame section. Unlike the LSDA encoding, personality encoding, and type encodings, this is something that the assembler just "knows" about its target
Definition at line 47 of file MCObjectFileInfo.h.
Referenced by getFDEEncoding(), and initMCObjectFileInfo().
FourByteConstantSection
MCSection* llvm::MCObjectFileInfo::FourByteConstantSection = nullptr protected
Definition at line 210 of file MCObjectFileInfo.h.
Referenced by getFourByteConstantSection(), llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
GEHContSection
MCSection* llvm::MCObjectFileInfo::GEHContSection = nullptr protected
Definition at line 223 of file MCObjectFileInfo.h.
Referenced by getGEHContSection().
GFIDsSection
MCSection* llvm::MCObjectFileInfo::GFIDsSection = nullptr protected
Definition at line 224 of file MCObjectFileInfo.h.
Referenced by getGFIDsSection().
GIATsSection
MCSection* llvm::MCObjectFileInfo::GIATsSection = nullptr protected
Definition at line 225 of file MCObjectFileInfo.h.
Referenced by getGIATsSection().
GLJMPSection
MCSection* llvm::MCObjectFileInfo::GLJMPSection = nullptr protected
Definition at line 226 of file MCObjectFileInfo.h.
Referenced by getGLJMPSection().
LazySymbolPointerSection
MCSection* llvm::MCObjectFileInfo::LazySymbolPointerSection = nullptr protected
Definition at line 213 of file MCObjectFileInfo.h.
Referenced by getLazySymbolPointerSection().
LLVMStatsSection
MCSection* llvm::MCObjectFileInfo::LLVMStatsSection = nullptr protected
Definition at line 180 of file MCObjectFileInfo.h.
Referenced by getLLVMStatsSection().
LSDASection
MCSection* llvm::MCObjectFileInfo::LSDASection = nullptr protected
If exception handling is supported by the target, this is the section the Language Specific Data Area information is emitted to.
Definition at line 69 of file MCObjectFileInfo.h.
Referenced by getLSDASection(), llvm::TargetLoweringObjectFile::getSectionForLSDA(), llvm::TargetLoweringObjectFileELF::getSectionForLSDA(), llvm::TargetLoweringObjectFileXCOFF::getSectionForLSDA(), and llvm::ARMElfTargetObjectFile::Initialize().
MergeableConst16Section
MCSection* llvm::MCObjectFileInfo::MergeableConst16Section = nullptr protected
Definition at line 186 of file MCObjectFileInfo.h.
Referenced by getMergeableConst16Section(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::XCoreTargetObjectFile::getSectionForConstant(), llvm::XCoreTargetObjectFile::Initialize(), and llvm::XCoreTargetObjectFile::SelectSectionForGlobal().
MergeableConst32Section
MCSection* llvm::MCObjectFileInfo::MergeableConst32Section = nullptr protected
Definition at line 187 of file MCObjectFileInfo.h.
Referenced by getMergeableConst32Section(), and llvm::TargetLoweringObjectFileELF::getSectionForConstant().
MergeableConst4Section
MCSection* llvm::MCObjectFileInfo::MergeableConst4Section = nullptr protected
Definition at line 184 of file MCObjectFileInfo.h.
Referenced by getMergeableConst4Section(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::XCoreTargetObjectFile::getSectionForConstant(), llvm::XCoreTargetObjectFile::Initialize(), and llvm::XCoreTargetObjectFile::SelectSectionForGlobal().
MergeableConst8Section
MCSection* llvm::MCObjectFileInfo::MergeableConst8Section = nullptr protected
Definition at line 185 of file MCObjectFileInfo.h.
Referenced by getMergeableConst8Section(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::XCoreTargetObjectFile::getSectionForConstant(), llvm::XCoreTargetObjectFile::Initialize(), and llvm::XCoreTargetObjectFile::SelectSectionForGlobal().
NonLazySymbolPointerSection
MCSection* llvm::MCObjectFileInfo::NonLazySymbolPointerSection = nullptr protected
Definition at line 214 of file MCObjectFileInfo.h.
Referenced by getNonLazySymbolPointerSection().
OmitDwarfIfHaveCompactUnwind
bool llvm::MCObjectFileInfo::OmitDwarfIfHaveCompactUnwind = false protected
OmitDwarfIfHaveCompactUnwind - True if the target object file supports having some functions with compact unwind and other with dwarf unwind.
Definition at line 41 of file MCObjectFileInfo.h.
Referenced by getOmitDwarfIfHaveCompactUnwind(), and initMCObjectFileInfo().
PDataSection
MCSection* llvm::MCObjectFileInfo::PDataSection = nullptr protected
Definition at line 220 of file MCObjectFileInfo.h.
Referenced by getPDataSection().
PPA1Section
MCSection* llvm::MCObjectFileInfo::PPA1Section = nullptr protected
Definition at line 229 of file MCObjectFileInfo.h.
Referenced by getPPA1Section().
PseudoProbeDescSection
MCSection* llvm::MCObjectFileInfo::PseudoProbeDescSection = nullptr protected
Definition at line 177 of file MCObjectFileInfo.h.
Referenced by getPseudoProbeDescSection().
PseudoProbeSection
MCSection* llvm::MCObjectFileInfo::PseudoProbeSection = nullptr protected
Section for pseudo probe information used by AutoFDO.
Definition at line 176 of file MCObjectFileInfo.h.
Referenced by getPseudoProbeSection().
ReadOnly16Section
MCSection* llvm::MCObjectFileInfo::ReadOnly16Section = nullptr protected
Definition at line 235 of file MCObjectFileInfo.h.
Referenced by llvm::TargetLoweringObjectFileXCOFF::getSectionForConstant().
ReadOnly8Section
MCSection* llvm::MCObjectFileInfo::ReadOnly8Section = nullptr protected
Definition at line 234 of file MCObjectFileInfo.h.
Referenced by llvm::TargetLoweringObjectFileXCOFF::getSectionForConstant().
ReadOnlySection
MCSection* llvm::MCObjectFileInfo::ReadOnlySection = nullptr protected
Section that is readonly and can contain arbitrary initialized data.
Targets are not required to have a readonly section. If they don't, various bits of code will fall back to using the data section for constants.
Definition at line 65 of file MCObjectFileInfo.h.
Referenced by getReadOnlySection(), llvm::TargetLoweringObjectFile::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), llvm::TargetLoweringObjectFileXCOFF::getSectionForConstant(), llvm::NVPTXTargetObjectFile::getSectionForConstant(), llvm::XCoreTargetObjectFile::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileXCOFF::getSectionForJumpTable(), llvm::XCoreTargetObjectFile::Initialize(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), and llvm::XCoreTargetObjectFile::SelectSectionForGlobal().
RemarksSection
MCSection* llvm::MCObjectFileInfo::RemarksSection = nullptr protected
Remarks section.
Definition at line 165 of file MCObjectFileInfo.h.
Referenced by getRemarksSection().
SixteenByteConstantSection
MCSection* llvm::MCObjectFileInfo::SixteenByteConstantSection = nullptr protected
Definition at line 212 of file MCObjectFileInfo.h.
Referenced by llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), getSixteenByteConstantSection(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
StackMapSection
MCSection* llvm::MCObjectFileInfo::StackMapSection = nullptr protected
StackMap section.
Definition at line 159 of file MCObjectFileInfo.h.
Referenced by getStackMapSection().
StackSizesSection
MCSection* llvm::MCObjectFileInfo::StackSizesSection = nullptr protected
Section containing metadata on function stack sizes.
Definition at line 173 of file MCObjectFileInfo.h.
Referenced by getStackSizesSection().
SupportsCompactUnwindWithoutEHFrame
bool llvm::MCObjectFileInfo::SupportsCompactUnwindWithoutEHFrame = false protected
True if the target object file supports emitting a compact unwind section without an associated EH frame section.
Definition at line 36 of file MCObjectFileInfo.h.
Referenced by getSupportsCompactUnwindWithoutEHFrame(), and initMCObjectFileInfo().
SupportsWeakOmittedEHFrame
bool llvm::MCObjectFileInfo::SupportsWeakOmittedEHFrame = false protected
True if target object file supports a weak_definition of constant 0 for an omitted EH frame.
Definition at line 32 of file MCObjectFileInfo.h.
Referenced by getSupportsWeakOmittedEHFrame(), and initMCObjectFileInfo().
Swift5ReflectionSections
std::array<MCSection *, binaryformat::Swift5ReflectionSectionKind::last> llvm::MCObjectFileInfo::Swift5ReflectionSections = {} protected
Definition at line 239 of file MCObjectFileInfo.h.
Referenced by getSwift5ReflectionSection().
SXDataSection
MCSection* llvm::MCObjectFileInfo::SXDataSection = nullptr protected
Definition at line 222 of file MCObjectFileInfo.h.
Referenced by getSXDataSection().
TextCoalSection
MCSection* llvm::MCObjectFileInfo::TextCoalSection = nullptr protected
Definition at line 203 of file MCObjectFileInfo.h.
Referenced by getTextCoalSection(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
TextSection
MCSection* llvm::MCObjectFileInfo::TextSection = nullptr protected
Section directive for standard text.
Definition at line 53 of file MCObjectFileInfo.h.
Referenced by llvm::SPIRVTargetObjectFile::getExplicitSectionGlobal(), llvm::SPIRVTargetObjectFile::getSectionForConstant(), getTextSection(), llvm::ARMElfTargetObjectFile::Initialize(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), llvm::AMDGPUTargetObjectFile::SelectSectionForGlobal(), llvm::SPIRVTargetObjectFile::SelectSectionForGlobal(), and llvm::XCoreTargetObjectFile::SelectSectionForGlobal().
ThreadLocalPointerSection
MCSection* llvm::MCObjectFileInfo::ThreadLocalPointerSection = nullptr protected
Definition at line 215 of file MCObjectFileInfo.h.
Referenced by getThreadLocalPointerSection().
TLSBSSSection
MCSection* llvm::MCObjectFileInfo::TLSBSSSection = nullptr protected
Section directive for Thread Local uninitialized data.
Null if this target doesn't support a BSS section. ELF and MachO only.
Definition at line 156 of file MCObjectFileInfo.h.
Referenced by getTLSBSSSection(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
TLSDataSection
MCSection* llvm::MCObjectFileInfo::TLSDataSection = nullptr protected
Section directive for Thread Local data. ELF, MachO, COFF, and Wasm.
Definition at line 151 of file MCObjectFileInfo.h.
Referenced by getTLSDataSection(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal().
TLSExtraDataSection
MCSection* llvm::MCObjectFileInfo::TLSExtraDataSection = nullptr protected
Extra TLS Variable Data section.
If the target needs to put additional information for a TLS variable, it'll go here.
Definition at line 148 of file MCObjectFileInfo.h.
Referenced by getTLSExtraDataSection().
TLSThreadInitSection
const MCSection* llvm::MCObjectFileInfo::TLSThreadInitSection = nullptr protected
Section for thread local data initialization functions.
Definition at line 199 of file MCObjectFileInfo.h.
Referenced by getTLSThreadInitSection().
TLSTLVSection
MCSection* llvm::MCObjectFileInfo::TLSTLVSection = nullptr protected
Section for thread local structure information.
Contains the source code name of the variable, visibility and a pointer to the initial value (.tdata or .tbss).
Definition at line 195 of file MCObjectFileInfo.h.
Referenced by getTLSTLVSection().
TOCBaseSection
MCSection* llvm::MCObjectFileInfo::TOCBaseSection = nullptr protected
Definition at line 233 of file MCObjectFileInfo.h.
Referenced by getTOCBaseSection().
UStringSection
MCSection* llvm::MCObjectFileInfo::UStringSection = nullptr protected
Definition at line 202 of file MCObjectFileInfo.h.
Referenced by getUStringSection(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
XDataSection
MCSection* llvm::MCObjectFileInfo::XDataSection = nullptr protected
Definition at line 221 of file MCObjectFileInfo.h.
Referenced by getXDataSection().
The documentation for this class was generated from the following files:
include/llvm/MC/MCObjectFileInfo.h
lib/MC/MCObjectFileInfo.cpp