LLVM: llvm::sys::DynamicLibrary::HandleSet Class Reference
llvm::sys::DynamicLibrary::HandleSet Class Reference
Public Member Functions
HandleSet ()=default
~HandleSet ()
HandleList::iterator Find (void *Handle)
bool Contains (void *Handle)
bool AddLibrary (void *Handle, bool IsProcess=false, bool CanClose=true, bool AllowDuplicates=false)
void CloseLibrary (void *Handle)
void * LibLookup (const char *Symbol, DynamicLibrary::SearchOrdering Order)
void * Lookup (const char *Symbol, DynamicLibrary::SearchOrdering Order)
Static Public Member Functions
static void * DLOpen (const char *Filename, std::string *Err)
static void DLClose (void *Handle)
static void * DLSym (void *Handle, const char *Symbol)
Detailed Description
Definition at line 25 of file DynamicLibrary.cpp.
Constructor & Destructor Documentation
HandleSet()
llvm::sys::DynamicLibrary::HandleSet::HandleSet () default
~HandleSet()
llvm::sys::DynamicLibrary::HandleSet::~HandleSet ()
Member Function Documentation
AddLibrary()
bool llvm::sys::DynamicLibrary::HandleSet::AddLibrary (void * Handle, bool IsProcess = false, bool CanClose = true, bool AllowDuplicates = false) inline
Definition at line 44 of file DynamicLibrary.cpp.
References assert(), llvm::sys::DynamicLibrary::HandleSet::DLClose(), llvm::sys::DynamicLibrary::HandleSet::Find(), and LLVM_LIKELY.
CloseLibrary()
void llvm::sys::DynamicLibrary::HandleSet::CloseLibrary (void * Handle) inline
Definition at line 73 of file DynamicLibrary.cpp.
References llvm::sys::DynamicLibrary::HandleSet::DLClose(), and llvm::sys::DynamicLibrary::HandleSet::Find().
Contains()
bool llvm::sys::DynamicLibrary::HandleSet::Contains (void * Handle) inline
Definition at line 40 of file DynamicLibrary.cpp.
References llvm::sys::DynamicLibrary::HandleSet::Find().
DLClose()
static void llvm::sys::DynamicLibrary::HandleSet::DLClose (void * Handle) static
Referenced by llvm::sys::DynamicLibrary::HandleSet::AddLibrary(), and llvm::sys::DynamicLibrary::HandleSet::CloseLibrary().
DLOpen()
static void * llvm::sys::DynamicLibrary::HandleSet::DLOpen (const char * Filename, std::string * Err) static
Referenced by llvm::sys::DynamicLibrary::getLibrary(), and llvm::sys::DynamicLibrary::getPermanentLibrary().
DLSym()
static void * llvm::sys::DynamicLibrary::HandleSet::DLSym (void * Handle, const char * Symbol) static
Referenced by llvm::sys::DynamicLibrary::getAddressOfSymbol(), llvm::sys::DynamicLibrary::HandleSet::LibLookup(), and llvm::sys::DynamicLibrary::HandleSet::Lookup().
Find()
HandleList::iterator llvm::sys::DynamicLibrary::HandleSet::Find (void * Handle) inline
Definition at line 38 of file DynamicLibrary.cpp.
References llvm::find().
Referenced by llvm::sys::DynamicLibrary::HandleSet::AddLibrary(), llvm::sys::DynamicLibrary::HandleSet::CloseLibrary(), and llvm::sys::DynamicLibrary::HandleSet::Contains().
LibLookup()
void * llvm::sys::DynamicLibrary::HandleSet::LibLookup (const char * Symbol, DynamicLibrary::SearchOrdering Order) inline
Definition at line 81 of file DynamicLibrary.cpp.
References llvm::sys::DynamicLibrary::HandleSet::DLSym(), Ptr, llvm::reverse(), and llvm::sys::DynamicLibrary::SO_LoadOrder.
Referenced by llvm::sys::DynamicLibrary::HandleSet::Lookup().
Lookup()
void * llvm::sys::DynamicLibrary::HandleSet::Lookup (const char * Symbol, DynamicLibrary::SearchOrdering Order) inline
Definition at line 96 of file DynamicLibrary.cpp.
References assert(), llvm::sys::DynamicLibrary::HandleSet::DLSym(), llvm::sys::DynamicLibrary::HandleSet::LibLookup(), Ptr, llvm::sys::DynamicLibrary::SO_LoadedFirst, and llvm::sys::DynamicLibrary::SO_LoadedLast.
The documentation for this class was generated from the following file:
lib/Support/DynamicLibrary.cpp