LLVM: lib/Target/CSKY/MCTargetDesc/CSKYInstPrinter.cpp File Reference
CSKYInstPrinter.cpp File Reference
#include "CSKYInstPrinter.h"
#include "MCTargetDesc/CSKYBaseInfo.h"
#include "MCTargetDesc/CSKYMCExpr.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "CSKYGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "csky-asm-printer"
#define PRINT_ALIAS_INSTR
Variables
static cl::opt< bool > NoAliases ("csky-no-aliases", cl::desc("Disable the emission of assembler pseudo instructions"), cl::init(false), cl::Hidden)
static cl::opt< bool > ArchRegNames ("csky-arch-reg-names", cl::desc("Print architectural register names rather than the " "ABI names (such as r14 instead of sp)"), cl::init(false), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "csky-asm-printer"
Definition at line 32 of file CSKYInstPrinter.cpp.
PRINT_ALIAS_INSTR
#define PRINT_ALIAS_INSTR
Definition at line 35 of file CSKYInstPrinter.cpp.
Variable Documentation
ArchRegNames
cl::opt< bool > ArchRegNames("csky-arch-reg-names", cl::desc("Print architectural register names rather than the " "ABI names (such as r14 instead of sp)"), cl::init(false), cl::Hidden) ("csky-arch-reg-names" , cl::desc("Print architectural register names rather than the " "ABI names (such as r14 instead of sp)") , cl::init(false) , cl::Hidden) static
Referenced by llvm::CSKYInstPrinter::applyTargetSpecificCLOption(), llvm::RISCVInstPrinter::applyTargetSpecificCLOption(), llvm::CSKYInstPrinter::getRegisterName(), llvm::RISCVInstPrinter::getRegisterName(), llvm::CSKYInstPrinter::printOperand(), and llvm::RISCVInstPrinter::printRlist().
NoAliases
cl::opt< bool > NoAliases("csky-no-aliases", cl::desc("Disable the emission of assembler pseudo instructions"), cl::init(false), cl::Hidden) ("csky-no-aliases" , cl::desc("Disable the emission of assembler pseudo instructions") , cl::init(false) , cl::Hidden) static
Referenced by AddAliasScopeMetadata(), llvm::CSKYInstPrinter::applyTargetSpecificCLOption(), llvm::RISCVInstPrinter::printFRMArg(), llvm::CSKYInstPrinter::printInst(), and llvm::RISCVInstPrinter::printInst().