LLVM: lib/Demangle/Demangle.cpp File Reference
Demangle.cpp File Reference
#include "llvm/Demangle/Demangle.h"
#include "llvm/Demangle/StringViewExtras.h"
#include <cstdlib>
#include <string_view>
Functions
static bool isItaniumEncoding (std::string_view S)
static bool isRustEncoding (std::string_view S)
static bool isDLangEncoding (std::string_view S)
Function Documentation
isDLangEncoding()
static bool isDLangEncoding (std::string_view S) static
Definition at line 46 of file Demangle.cpp.
References starts_with().
Referenced by llvm::nonMicrosoftDemangle().
isItaniumEncoding()
static bool isItaniumEncoding (std::string_view S) static
Definition at line 39 of file Demangle.cpp.
References starts_with().
Referenced by llvm::nonMicrosoftDemangle().
isRustEncoding()
static bool isRustEncoding (std::string_view S) static
Definition at line 44 of file Demangle.cpp.
References starts_with().
Referenced by llvm::nonMicrosoftDemangle().