LLVM: lib/Support/DJB.cpp File Reference
DJB.cpp File Reference
#include "llvm/Support/DJB.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ConvertUTF.h"
#include "llvm/Support/Unicode.h"
Functions
static UTF32 chopOneUTF32 (StringRef &Buffer)
static StringRef toUTF8 (UTF32 C, MutableArrayRef< UTF8 > Storage)
static UTF32 foldCharDwarf (UTF32 C)
static std::optional< uint32_t > fastCaseFoldingDjbHash (StringRef Buffer, uint32_t H)
Function Documentation
chopOneUTF32()
static UTF32 chopOneUTF32 (StringRef & Buffer) static
Definition at line 21 of file DJB.cpp.
References assert(), llvm::StringRef::begin(), llvm::CallingConv::C, llvm::ConvertUTF8toUTF32(), llvm::StringRef::drop_front(), llvm::StringRef::empty(), llvm::StringRef::end(), and llvm::lenientConversion.
Referenced by llvm::caseFoldingDjbHash().
fastCaseFoldingDjbHash()
static std::optional< uint32_t > fastCaseFoldingDjbHash (StringRef Buffer, uint32_t H) static
Definition at line 60 of file DJB.cpp.
References llvm::CallingConv::C, and H.
Referenced by llvm::caseFoldingDjbHash().
foldCharDwarf()
static UTF32 foldCharDwarf (UTF32 C) static
Definition at line 51 of file DJB.cpp.
References llvm::CallingConv::C, and llvm::sys::unicode::foldCharSimple().
Referenced by llvm::caseFoldingDjbHash().
toUTF8()
static StringRef toUTF8 (UTF32 C, MutableArrayRef< UTF8 > Storage) static
Definition at line 37 of file DJB.cpp.
References assert(), llvm::CallingConv::C, llvm::conversionOK, llvm::ConvertUTF32toUTF8(), and llvm::strictConversion.
Referenced by llvm::caseFoldingDjbHash().