LLVM: lib/Target/LoongArch/MCTargetDesc/LoongArchMCExpr.cpp File Reference
LoongArchMCExpr.cpp File Reference
#include "LoongArchMCExpr.h"
#include "LoongArchAsmBackend.h"
#include "LoongArchFixupKinds.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbolELF.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
Macros
#define DEBUG_TYPE "loongarch-mcexpr"
Functions
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr *Expr, MCAssembler &Asm)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loongarch-mcexpr"
Definition at line 26 of file LoongArchMCExpr.cpp.
Function Documentation
fixELFSymbolsInTLSFixupsImpl()
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr * Expr, MCAssembler & Asm) static
Definition at line 185 of file LoongArchMCExpr.cpp.
References llvm::MCExpr::Binary, llvm::MCExpr::Constant, fixELFSymbolsInTLSFixupsImpl(), llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCBinaryExpr::getRHS(), llvm_unreachable, llvm::ELF::STT_TLS, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, and llvm::MCExpr::Unary.