LLVM: lib/DebugInfo/LogicalView/Core/LVReader.cpp File Reference
LVReader.cpp File Reference
#include "llvm/DebugInfo/LogicalView/Core/LVReader.h"
#include "llvm/DebugInfo/LogicalView/Core/LVLine.h"
#include "llvm/DebugInfo/LogicalView/Core/LVScope.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/FormatAdapters.h"
#include "llvm/Support/FormatVariadic.h"
#include <tuple>
Macros
#define DEBUG_TYPE "Reader"
Functions
bool checkIntegrityScopesTree (LVScope *Root)
Variables
LVReader * CurrentReader = nullptr
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "Reader"
Definition at line 24 of file LVReader.cpp.
Function Documentation
checkIntegrityScopesTree()
bool checkIntegrityScopesTree (LVScope * Root)
Definition at line 29 of file LVReader.cpp.
References llvm::dbgs(), llvm::First, llvm::fmt_repeat(), llvm::format(), llvm::formatv(), llvm::logicalview::LVObject::getID(), llvm::logicalview::LVScope::getLines(), llvm::logicalview::LVElement::getName(), llvm::logicalview::LVScope::getScopes(), llvm::logicalview::LVScope::getSymbols(), llvm::logicalview::LVScope::getTypes(), llvm::logicalview::Integrity, llvm::logicalview::LVObject::kind(), and llvm::logicalview::Scopes.
Referenced by llvm::logicalview::LVReader::doLoad().
Variable Documentation
CurrentReader
LVReader* CurrentReader = nullptr
Definition at line 153 of file LVReader.cpp.
Referenced by llvm::logicalview::LVReader::getInstance(), and llvm::logicalview::LVReader::setInstance().