LLVM: lib/Target/M68k/M68kInstrInfo.cpp File Reference
M68kInstrInfo.cpp File Reference
This file contains the M68k declaration of the TargetInstrInfo class.
#include "M68kInstrInfo.h"
#include "M68kInstrBuilder.h"
#include "M68kMachineFunction.h"
#include "M68kTargetMachine.h"
#include "MCTargetDesc/M68kMCCodeEmitter.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/LiveVariables.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Regex.h"
#include <functional>
#include "M68kGenInstrInfo.inc"
Macros
#define DEBUG_TYPE "M68k-instr-info"
#define GET_INSTRINFO_CTOR_DTOR
#define DEBUG_TYPE "m68k-create-global-base-reg"
#define PASS_NAME "M68k PIC Global Base Reg Initialization"
Functions
static M68k::CondCode getCondFromBranchOpc (unsigned BrOpc)
static bool Expand2AddrUndef (MachineInstrBuilder &MIB, const MCInstrDesc &Desc)
Expand a single-def pseudo instruction to a two-addr instruction with two undef reads of the register being defined.
Detailed Description
This file contains the M68k declaration of the TargetInstrInfo class.
Definition in file M68kInstrInfo.cpp.
Macro Definition Documentation
DEBUG_TYPE [1/2]
#define DEBUG_TYPE "M68k-instr-info"
Definition at line 35 of file M68kInstrInfo.cpp.
DEBUG_TYPE [2/2]
#define DEBUG_TYPE "m68k-create-global-base-reg"
Definition at line 35 of file M68kInstrInfo.cpp.
GET_INSTRINFO_CTOR_DTOR
#define GET_INSTRINFO_CTOR_DTOR
Definition at line 37 of file M68kInstrInfo.cpp.
PASS_NAME
#define PASS_NAME "M68k PIC Global Base Reg Initialization"
Definition at line 824 of file M68kInstrInfo.cpp.
Function Documentation
Expand2AddrUndef()
static bool Expand2AddrUndef (MachineInstrBuilder & MIB, const MCInstrDesc & Desc) static
Expand a single-def pseudo instruction to a two-addr instruction with two undef reads of the register being defined.
This is used for mapping: d0 = SETCS_C32d to: d0 = SUBX32dd d0<undef>, d0<undef>
Definition at line 560 of file M68kInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), assert(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::setDesc(), and llvm::RegState::Undef.
Referenced by llvm::M68kInstrInfo::expandPostRAPseudo(), and llvm::X86InstrInfo::expandPostRAPseudo().
getCondFromBranchOpc()
static M68k::CondCode getCondFromBranchOpc (unsigned BrOpc) static
Definition at line 48 of file M68kInstrInfo.cpp.
References llvm::M68k::COND_CC, llvm::M68k::COND_CS, llvm::M68k::COND_EQ, llvm::M68k::COND_GE, llvm::M68k::COND_GT, llvm::M68k::COND_HI, llvm::M68k::COND_INVALID, llvm::M68k::COND_LE, llvm::M68k::COND_LS, llvm::M68k::COND_LT, llvm::M68k::COND_MI, llvm::M68k::COND_NE, llvm::M68k::COND_PL, llvm::M68k::COND_VC, and llvm::M68k::COND_VS.
Referenced by parseCondBranch(), and llvm::M68kInstrInfo::removeBranch().