LLVM: lib/CodeGen/MachineModuleInfo.cpp File Reference
MachineModuleInfo.cpp File Reference
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCContext.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include <algorithm>
#include <cassert>
#include <memory>
#include <utility>
#include <vector>
Functions
static INITIALIZE_PASS(MachineModuleInfoWrapperPass, "machinemoduleinfo", "Machine Module Information", false, false) char MachineModuleInfoWrapperPass unsigned getLocCookie (const SMDiagnostic &SMD, const SourceMgr &SrcMgr, std::vector< const MDNode * > &LocInfos)
Variables
static cl::opt< bool > DisableDebugInfoPrinting ("disable-debug-info-print", cl::Hidden, cl::desc("Disable debug info printing"))
Function Documentation
getLocCookie()
static INITIALIZE_PASS(MachineModuleInfoWrapperPass, "machinemoduleinfo", "Machine Module Information", false, false) char MachineModuleInfoWrapperPass unsigned getLocCookie (const SMDiagnostic & SMD, const SourceMgr & SrcMgr, std::vector< const MDNode * > & LocInfos) static
Definition at line 188 of file MachineModuleInfo.cpp.
References llvm::SourceMgr::FindBufferContainingLoc(), and llvm::SrcMgr.
Referenced by llvm::MachineModuleInfoWrapperPass::doInitialization().
Variable Documentation
DisableDebugInfoPrinting
cl::opt< bool > DisableDebugInfoPrinting("disable-debug-info-print", cl::Hidden, cl::desc("Disable debug info printing")) ("disable-debug-info-print" , cl::Hidden , cl::desc("Disable debug info printing")) static
Referenced by llvm::MachineModuleInfoWrapperPass::doInitialization(), and llvm::MachineModuleAnalysis::run().