LLVM: lib/MC/MCFragment.cpp File Reference
MCFragment.cpp File Reference
#include "llvm/MC/MCFragment.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include <utility>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
static bool getLabelOffset (const MCAsmLayout &Layout, const MCSymbol &S, bool ReportError, uint64_t &Val)
static bool getSymbolOffsetImpl (const MCAsmLayout &Layout, const MCSymbol &S, bool ReportError, uint64_t &Val)
raw_ostream & llvm::operator<< (raw_ostream &OS, const MCFixup &AF)
Function Documentation
getLabelOffset()
static bool getLabelOffset (const MCAsmLayout & Layout, const MCSymbol & S, bool ReportError, uint64_t & Val) static
Definition at line 103 of file MCFragment.cpp.
References llvm::MCSymbol::getFragment(), llvm::MCAsmLayout::getFragmentOffset(), llvm::MCSymbol::getName(), llvm::MCSymbol::getOffset(), and llvm::report_fatal_error().
Referenced by getSymbolOffsetImpl().
getSymbolOffsetImpl()
static bool getSymbolOffsetImpl (const MCAsmLayout & Layout, const MCSymbol & S, bool ReportError, uint64_t & Val) static
Definition at line 115 of file MCFragment.cpp.
References A, B, llvm::MCExpr::evaluateAsValue(), getLabelOffset(), llvm::MCSymbol::getName(), getSymbolOffsetImpl(), llvm::MCSymbol::getVariableValue(), llvm::MCSymbol::isVariable(), llvm::Offset, and llvm::report_fatal_error().
Referenced by llvm::MCAsmLayout::getSymbolOffset(), llvm::MCAsmLayout::getSymbolOffset(), and getSymbolOffsetImpl().