LLVM: lib/Target/Mips/MipsTargetMachine.cpp File Reference
MipsTargetMachine.cpp File Reference
#include "MipsTargetMachine.h"
#include "MCTargetDesc/MipsABIInfo.h"
#include "MCTargetDesc/MipsMCTargetDesc.h"
#include "Mips.h"
#include "Mips16ISelDAGToDAG.h"
#include "MipsMachineFunction.h"
#include "MipsSEISelDAGToDAG.h"
#include "MipsSubtarget.h"
#include "MipsTargetObjectFile.h"
#include "MipsTargetTransformInfo.h"
#include "TargetInfo/MipsTargetInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/BasicTTIImpl.h"
#include "llvm/CodeGen/GlobalISel/CSEInfo.h"
#include "llvm/CodeGen/GlobalISel/IRTranslator.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelect.h"
#include "llvm/CodeGen/GlobalISel/Legalizer.h"
#include "llvm/CodeGen/GlobalISel/RegBankSelect.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetOptions.h"
#include <optional>
#include <string>
Macros
#define DEBUG_TYPE "mips"
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMipsTarget ()
static std::string computeDataLayout (const Triple &TT, StringRef CPU, const TargetOptions &Options, bool isLittle)
static Reloc::Model getEffectiveRelocModel (bool JIT, std::optional< Reloc::Model > RM)
Variables
static cl::opt< bool > EnableMulMulFix ("mfix4300", cl::init(false), cl::desc("Enable the VR4300 mulmul bug fix."), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mips"
Definition at line 49 of file MipsTargetMachine.cpp.
Function Documentation
computeDataLayout()
static std::string computeDataLayout (const Triple & TT, StringRef CPU, const TargetOptions & Options, bool isLittle) static
Definition at line 73 of file MipsTargetMachine.cpp.
References llvm::MipsABIInfo::computeTargetABI(), and Options.
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (bool JIT, std::optional< Reloc::Model > RM) static
Definition at line 109 of file MipsTargetMachine.cpp.
References llvm::Reloc::Static.
LLVMInitializeMipsTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMipsTarget ()
Definition at line 55 of file MipsTargetMachine.cpp.
References A, B, llvm::PassRegistry::getPassRegistry(), llvm::getTheMips64elTarget(), llvm::getTheMips64Target(), llvm::getTheMipselTarget(), llvm::getTheMipsTarget(), llvm::initializeGlobalISel(), llvm::initializeMicroMipsSizeReducePass(), llvm::initializeMipsBranchExpansionPass(), llvm::initializeMipsDAGToDAGISelPass(), llvm::initializeMipsDelaySlotFillerPass(), llvm::initializeMipsMulMulBugFixPass(), llvm::initializeMipsPostLegalizerCombinerPass(), llvm::initializeMipsPreLegalizerCombinerPass(), X, and Y.
Variable Documentation
EnableMulMulFix
cl::opt< bool > EnableMulMulFix("mfix4300", cl::init(false), cl::desc("Enable the VR4300 mulmul bug fix."), cl::Hidden) ("mfix4300" , cl::init(false) , cl::desc("Enable the VR4300 mulmul bug fix.") , cl::Hidden) static