LLVM: lib/CodeGen/MLRegallocEvictAdvisor.h File Reference
MLRegallocEvictAdvisor.h File Reference
#include "llvm/Analysis/MLModelRunner.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/SlotIndexes.h"
Classes
struct LRStartEndInfo
Functions
void extractInstructionFeatures (llvm::SmallVectorImpl< LRStartEndInfo > &LRPosInfo, MLModelRunner *RegallocRunner, function_ref< int(SlotIndex)> GetOpcode, function_ref< float(SlotIndex)> GetMBBFreq, function_ref< MachineBasicBlock *(SlotIndex)> GetMBBReference, const int InstructionsIndex, const int InstructionsMappingIndex, const int MBBFreqIndex, const int MBBMappingIndex, const SlotIndex LastIndex)
void extractMBBFrequency (const SlotIndex CurrentIndex, const size_t CurrentInstructionIndex, std::map< MachineBasicBlock *, size_t > &VisitedMBBs, function_ref< float(SlotIndex)> GetMBBFreq, MachineBasicBlock *CurrentMBBReference, MLModelRunner *RegallocRunner, const int MBBFreqIndex, const int MBBMappingIndex)
Variables
static const int64_t MaxInterferences = 32
static const int64_t CandidateVirtRegPos = MaxInterferences
static const int64_t NumberOfInterferences = CandidateVirtRegPos + 1
static const int ModelMaxSupportedInstructionCount = 300
static const std::vector< int64_t > InstructionsShape
static const std::vector< int64_t > InstructionsMappingShape
static const int64_t ModelMaxSupportedMBBCount = 100
static const std::vector< int64_t > MBBFrequencyShape
Function Documentation
extractInstructionFeatures()
void extractInstructionFeatures (llvm::SmallVectorImpl< LRStartEndInfo > & LRPosInfo, MLModelRunner * RegallocRunner, function_ref< int(SlotIndex)> GetOpcode, function_ref< float(SlotIndex)> GetMBBFreq, function_ref< MachineBasicBlock *(SlotIndex)> GetMBBReference, const int InstructionsIndex, const int InstructionsMappingIndex, const int MBBFreqIndex, const int MBBMappingIndex, const SlotIndex LastIndex)
Definition at line 943 of file MLRegallocEvictAdvisor.cpp.
References A, assert(), B, End, extractMBBFrequency(), llvm::SlotIndex::getNextIndex(), and ModelMaxSupportedInstructionCount.
extractMBBFrequency()
void extractMBBFrequency (const SlotIndex CurrentIndex, const size_t CurrentInstructionIndex, std::map< MachineBasicBlock *, size_t > & VisitedMBBs, function_ref< float(SlotIndex)> GetMBBFreq, MachineBasicBlock * CurrentMBBReference, MLModelRunner * RegallocRunner, const int MBBFreqIndex, const int MBBMappingIndex)
Definition at line 1060 of file MLRegallocEvictAdvisor.cpp.
References ModelMaxSupportedMBBCount.
Referenced by extractInstructionFeatures().
Variable Documentation
CandidateVirtRegPos
const int64_t CandidateVirtRegPos = MaxInterferences static
Definition at line 63 of file MLRegallocEvictAdvisor.h.
InstructionsMappingShape
const std::vector<int64_t> InstructionsMappingShape static
Initial value:
{
    1, NumberOfInterferences, ModelMaxSupportedInstructionCount}
Definition at line 81 of file MLRegallocEvictAdvisor.h.
InstructionsShape
const std::vector<int64_t> InstructionsShape static
Initial value:
{
    1, ModelMaxSupportedInstructionCount}
Definition at line 79 of file MLRegallocEvictAdvisor.h.
MaxInterferences
const int64_t MaxInterferences = 32 static
Definition at line 55 of file MLRegallocEvictAdvisor.h.
MBBFrequencyShape
const std::vector<int64_t> MBBFrequencyShape static
Initial value:
{1,
                                                    ModelMaxSupportedMBBCount}
Definition at line 90 of file MLRegallocEvictAdvisor.h.
ModelMaxSupportedInstructionCount
const int ModelMaxSupportedInstructionCount = 300 static
Definition at line 72 of file MLRegallocEvictAdvisor.h.
Referenced by extractInstructionFeatures().
ModelMaxSupportedMBBCount
const int64_t ModelMaxSupportedMBBCount = 100 static
Definition at line 89 of file MLRegallocEvictAdvisor.h.
Referenced by extractMBBFrequency().
NumberOfInterferences
const int64_t NumberOfInterferences = CandidateVirtRegPos + 1 static
Definition at line 64 of file MLRegallocEvictAdvisor.h.
Referenced by INITIALIZE_PASS().