LLVM: lib/Target/MSP430/MCTargetDesc/MSP430MCTargetDesc.cpp File Reference
MSP430MCTargetDesc.cpp File Reference
#include "MSP430MCTargetDesc.h"
#include "MSP430InstPrinter.h"
#include "MSP430MCAsmInfo.h"
#include "TargetInfo/MSP430TargetInfo.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "MSP430GenInstrInfo.inc"
#include "MSP430GenSubtargetInfo.inc"
#include "MSP430GenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createMSP430MCInstrInfo ()
static MCRegisterInfo * createMSP430MCRegisterInfo (const Triple &TT)
static MCAsmInfo * createMSP430MCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
static MCSubtargetInfo * createMSP430MCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCInstPrinter * createMSP430MCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMSP430TargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 26 of file MSP430MCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 25 of file MSP430MCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 32 of file MSP430MCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 29 of file MSP430MCTargetDesc.cpp.
Function Documentation
createMSP430MCAsmInfo()
static MCAsmInfo * createMSP430MCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT, const MCTargetOptions & Options) static
Definition at line 47 of file MSP430MCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::cfiDefCfa(), llvm::MCCFIInstruction::createOffset(), and MRI.
Referenced by LLVMInitializeMSP430TargetMC().
createMSP430MCInstPrinter()
static MCInstPrinter * createMSP430MCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 73 of file MSP430MCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeMSP430TargetMC().
createMSP430MCInstrInfo()
static MCInstrInfo * createMSP430MCInstrInfo () static
Definition at line 35 of file MSP430MCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeMSP430TargetMC().
createMSP430MCRegisterInfo()
static MCRegisterInfo * createMSP430MCRegisterInfo (const Triple & TT) static
Definition at line 41 of file MSP430MCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeMSP430TargetMC().
createMSP430MCSubtargetInfo()
static MCSubtargetInfo * createMSP430MCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 69 of file MSP430MCTargetDesc.cpp.
Referenced by LLVMInitializeMSP430TargetMC().
LLVMInitializeMSP430TargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeMSP430TargetMC ()
Definition at line 83 of file MSP430MCTargetDesc.cpp.
References llvm::createMSP430MCAsmBackend(), createMSP430MCAsmInfo(), llvm::createMSP430MCCodeEmitter(), createMSP430MCInstPrinter(), createMSP430MCInstrInfo(), createMSP430MCRegisterInfo(), createMSP430MCSubtargetInfo(), llvm::createMSP430ObjectTargetStreamer(), llvm::getTheMSP430Target(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCAsmInfo(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), and llvm::TargetRegistry::RegisterObjectTargetStreamer().