LLVM: llvm::AMDGPU::Exp Namespace Reference
llvm::AMDGPU::Exp Namespace Reference
Classes
struct ExpTgt
Enumerations
enum Target : unsigned {
ET_MRT0 = 0 , ET_MRT7 = 7 , ET_MRTZ = 8 , ET_NULL = 9 ,
ET_POS0 = 12 , ET_POS3 = 15 , ET_POS4 = 16 , ET_POS_LAST = ET_POS4 ,
ET_PRIM = 20 , ET_DUAL_SRC_BLEND0 = 21 , ET_DUAL_SRC_BLEND1 = 22 , ET_PARAM0 = 32 ,
ET_PARAM31 = 63 , ET_NULL_MAX_IDX = 0 , ET_MRTZ_MAX_IDX = 0 , ET_PRIM_MAX_IDX = 0 ,
ET_MRT_MAX_IDX = 7 , ET_POS_MAX_IDX = 4 , ET_DUAL_SRC_BLEND_MAX_IDX = 1 , ET_PARAM_MAX_IDX = 31 ,
ET_INVALID = 255
}
Functions
bool getTgtName (unsigned Id, StringRef &Name, int &Index)
unsigned getTgtId (const StringRef Name)
bool isSupportedTgtId (unsigned Id, const MCSubtargetInfo &STI)
Variables
static constexpr ExpTgt ExpTgtInfo []
Enumeration Type Documentation
Target
enum llvm::AMDGPU::Exp::Target : unsigned
Enumerator
ET_MRT0
ET_MRT7
ET_MRTZ
ET_NULL
ET_POS0
ET_POS3
ET_POS4
ET_POS_LAST
ET_PRIM
ET_DUAL_SRC_BLEND0
ET_DUAL_SRC_BLEND1
ET_PARAM0
ET_PARAM31
ET_NULL_MAX_IDX
ET_MRTZ_MAX_IDX
ET_PRIM_MAX_IDX
ET_MRT_MAX_IDX
ET_POS_MAX_IDX
ET_DUAL_SRC_BLEND_MAX_IDX
ET_PARAM_MAX_IDX
ET_INVALID
Definition at line 894 of file SIDefines.h.
Function Documentation
getTgtId()
LLVM_READONLY unsigned llvm::AMDGPU::Exp::getTgtId (const StringRef Name)
Definition at line 1635 of file AMDGPUBaseInfo.cpp.
References llvm::StringRef::drop_front(), ET_INVALID, ExpTgtInfo, llvm::StringRef::getAsInteger(), Name, and llvm::StringRef::size().
getTgtName()
bool llvm::AMDGPU::Exp::getTgtName (unsigned Id, StringRef & Name, int & Index)
Definition at line 1624 of file AMDGPUBaseInfo.cpp.
References ExpTgtInfo, and Name.
isSupportedTgtId()
LLVM_READNONE bool llvm::AMDGPU::Exp::isSupportedTgtId (unsigned Id, const MCSubtargetInfo & STI)
Definition at line 1658 of file AMDGPUBaseInfo.cpp.
References ET_DUAL_SRC_BLEND0, ET_DUAL_SRC_BLEND1, ET_NULL, ET_PARAM0, ET_PARAM31, ET_POS4, ET_PRIM, llvm::AMDGPU::isGFX10Plus(), and llvm::AMDGPU::isGFX11Plus().
Variable Documentation
ExpTgtInfo
constexpr ExpTgt llvm::AMDGPU::Exp::ExpTgtInfo[] static constexpr
Initial value:
= {
  {{"null"},           ET_NULL,            ET_NULL_MAX_IDX},
  {{"mrtz"},           ET_MRTZ,            ET_MRTZ_MAX_IDX},
  {{"prim"},           ET_PRIM,            ET_PRIM_MAX_IDX},
  {{"mrt"},            ET_MRT0,            ET_MRT_MAX_IDX},
  {{"pos"},            ET_POS0,            ET_POS_MAX_IDX},
  {{"dual_src_blend"}, ET_DUAL_SRC_BLEND0, ET_DUAL_SRC_BLEND_MAX_IDX},
  {{"param"},          ET_PARAM0,          ET_PARAM_MAX_IDX},
}
Definition at line 1614 of file AMDGPUBaseInfo.cpp.
Referenced by getTgtId(), and getTgtName().