LLVM: llvm::logicalview Namespace Reference
llvm::logicalview Namespace Reference
Classes
class LVBinaryReader
class LVCodeViewReader
class LVCompare
struct LVCounter
class LVDoubleMap
class LVElement
class LVELFReader
class LVLine
class LVLineAssembler
class LVLineDebug
class LVLocation
class LVLocationSymbol
class LVLogicalVisitor
class LVObject
class LVOperation
class LVOptions
class LVPatterns
class LVProperties
class LVRange
class LVRangeEntry
class LVReader
The logical reader owns of all the logical elements created during the debug information parsing.
class LVReaderHandler
class LVScope
class LVScopeAggregate
class LVScopeAlias
class LVScopeArray
class LVScopeCompileUnit
class LVScopeEnumeration
class LVScopeFormalPack
class LVScopeFunction
class LVScopeFunctionInlined
class LVScopeFunctionType
class LVScopeNamespace
class LVScopeRoot
class LVScopeTemplatePack
struct LVShared
class LVSplitContext
class LVStringPool
class LVSymbol
class LVSymbolTable
struct LVSymbolTableEntry
class LVSymbolVisitor
class LVSymbolVisitorDelegate
class LVType
class LVTypeDefinition
class LVTypeEnumerator
class LVTypeImport
class LVTypeParam
class LVTypeSubrange
class LVTypeVisitor
Typedefs
using LVPassEntry = std::tuple<LVReader *, LVElement *, LVComparePass>
using LVPassTable = std::vector<LVPassEntry>
using LVElementKindSet = std::set<LVElementKind>
using LVElementDispatch = std::map<LVElementKind, LVElementGetFunction>
using LVElementRequest = std::vector<LVElementGetFunction>
using LVLineKindSet = std::set<LVLineKind>
using LVLineDispatch = std::map<LVLineKind, LVLineGetFunction>
using LVLineRequest = std::vector<LVLineGetFunction>
using LVLineRange = std::pair<LVLine *, LVLine *>
using LVSectionIndex = uint64_t
using LVAddress = uint64_t
using LVHalf = uint16_t
using LVLevel = uint32_t
using LVOffset = uint64_t
using LVSigned = int64_t
using LVUnsigned = uint64_t
using LVSmall = uint8_t
using LVElementSetFunction = void (LVElement::*)()
using LVElementGetFunction = bool (LVElement::*)() const
using LVLineSetFunction = void (LVLine::*)()
using LVLineGetFunction = bool (LVLine::*)() const
using LVObjectSetFunction = void (LVObject::*)()
using LVObjectGetFunction = bool (LVObject::*)() const
using LVScopeSetFunction = void (LVScope::*)()
using LVScopeGetFunction = bool (LVScope::*)() const
using LVSymbolSetFunction = void (LVSymbol::*)()
using LVSymbolGetFunction = bool (LVSymbol::*)() const
using LVTypeSetFunction = void (LVType::*)()
using LVTypeGetFunction = bool (LVType::*)() const
using LVElements = SmallVector<LVElement *, 8>
using LVLines = SmallVector<LVLine *, 8>
using LVLocations = SmallVector<LVLocation *, 8>
using LVOperations = SmallVector<LVOperation *, 8>
using LVScopes = SmallVector<LVScope *, 8>
using LVSymbols = SmallVector<LVSymbol *, 8>
using LVTypes = SmallVector<LVType *, 8>
using LVOffsets = SmallVector<LVOffset, 8>
using LVValidLocation = bool (LVLocation::*)()
using LVOffsetSet = std::set<uint64_t>
using LVAttributeKindSet = std::set<LVAttributeKind>
using LVCompareKindSet = std::set<LVCompareKind>
using LVOutputKindSet = std::set<LVOutputKind>
using LVPrintKindSet = std::set<LVPrintKind>
using LVReportKindSet = std::set<LVReportKind>
using LVWarningKindSet = std::set<LVWarningKind>
using LVInternalKindSet = std::set<LVInternalKind>
using LVAddressRange = std::pair<LVAddress, LVAddress>
using LVRangeEntries = std::vector<LVRangeEntry>
using LVNameInfo = std::pair<LVAddress, uint64_t>
using LVPublicNames = std::map<LVScope *, LVNameInfo>
using LVPublicAddresses = std::map<LVAddress, LVNameInfo>
using LVScopeKindSet = std::set<LVScopeKind>
using LVScopeDispatch = std::map<LVScopeKind, LVScopeGetFunction>
using LVScopeRequest = std::vector<LVScopeGetFunction>
using LVOffsetElementMap = std::map<LVOffset, LVElement *>
using LVOffsetLinesMap = std::map<LVOffset, LVLines>
using LVOffsetLocationsMap = std::map<LVOffset, LVLocations>
using LVOffsetSymbolMap = std::map<LVOffset, LVSymbol *>
using LVTagOffsetsMap = std::map<dwarf::Tag, LVOffsets>
using LVSortValue = int
using LVSortFunction
using LVStringRefs = std::vector<StringRef>
using LVLexicalComponent = std::tuple<StringRef, StringRef>
using LVLexicalIndex
using LVSymbolKindSet = std::set<LVSymbolKind>
using LVSymbolDispatch = std::map<LVSymbolKind, LVSymbolGetFunction>
using LVSymbolRequest = std::vector<LVSymbolGetFunction>
using LVTypeKindSelection = std::set<LVTypeKind>
using LVTypeDispatch = std::map<LVTypeKind, LVTypeGetFunction>
using LVTypeRequest = std::vector<LVTypeGetFunction>
using LVReaders = std::vector<std::unique_ptr<LVReader>>
using ArgVector = std::vector<std::string>
using PdbOrObj = PointerUnion<object::ObjectFile *, pdb::PDBFile *>
using LVNames = SmallVector<StringRef, 16>
using AttributeSpec = DWARFAbbreviationDeclaration::AttributeSpec
using LVLineRecords = std::vector<TypeIndex>
using LVTypeKinds = std::set<TypeLeafKind>
using LVSymbolKinds = std::set<SymbolKind>
Enumerations
enum class LVSubclassID : unsigned char {
LV_ELEMENT , LV_LINE_FIRST , LV_LINE , LV_LINE_DEBUG ,
LV_LINE_ASSEMBLER , LV_LINE_LAST , lV_SCOPE_FIRST , LV_SCOPE ,
LV_SCOPE_AGGREGATE , LV_SCOPE_ALIAS , LV_SCOPE_ARRAY , LV_SCOPE_COMPILE_UNIT ,
LV_SCOPE_ENUMERATION , LV_SCOPE_FORMAL_PACK , LV_SCOPE_FUNCTION , LV_SCOPE_FUNCTION_INLINED ,
LV_SCOPE_FUNCTION_TYPE , LV_SCOPE_NAMESPACE , LV_SCOPE_ROOT , LV_SCOPE_TEMPLATE_PACK ,
LV_SCOPE_LAST , LV_SYMBOL_FIRST , LV_SYMBOL , LV_SYMBOL_LAST ,
LV_TYPE_FIRST , LV_TYPE , LV_TYPE_DEFINITION , LV_TYPE_ENUMERATOR ,
LV_TYPE_IMPORT , LV_TYPE_PARAM , LV_TYPE_SUBRANGE , LV_TYPE_LAST
}
enum class LVElementKind { Discarded , Global , Optimized , LastEntry }
enum class LVLineKind {
IsBasicBlock , IsDiscriminator , IsEndSequence , IsEpilogueBegin ,
IsLineDebug , IsLineAssembler , IsNewStatement , IsPrologueEnd ,
IsAlwaysStepInto , IsNeverStepInto , LastEntry
}
enum class LVBinaryType { NONE , ELF , COFF }
enum class LVComparePass { Missing , Added }
enum class LVAttributeKind {
All , Argument , Base , Coverage ,
Directories , Discarded , Discriminator , Encoded ,
Extended , Filename , Files , Format ,
Gaps , Generated , Global , Inserted ,
Level , Linkage , Local , Location ,
Offset , Pathname , Producer , Publics ,
Qualified , Qualifier , Range , Reference ,
Register , Standard , Subrange , System ,
Typename , Underlying , Zero
}
enum class LVCompareKind {
All , Lines , Scopes , Symbols ,
Types
}
enum class LVOutputKind { All , Split , Json , Text }
enum class LVPrintKind {
All , Elements , Instructions , Lines ,
Scopes , Sizes , Symbols , Summary ,
Types , Warnings
}
enum class LVReportKind {
All , Children , List , Parents ,
View
}
enum class LVWarningKind {
All , Coverages , Lines , Locations ,
Ranges
}
enum class LVInternalKind {
All , Cmdline , ID , Integrity ,
None , Tag
}
enum class LVScopeKind {
IsAggregate , IsArray , IsBlock , IsCallSite ,
IsCatchBlock , IsClass , IsCompileUnit , IsEntryPoint ,
IsEnumeration , IsFunction , IsFunctionType , IsInlinedFunction ,
IsLabel , IsLexicalBlock , IsMember , IsNamespace ,
IsRoot , IsStructure , IsSubprogram , IsTemplate ,
IsTemplateAlias , IsTemplatePack , IsTryBlock , IsUnion ,
LastEntry
}
enum class LVSortMode {
None = 0 , Kind , Line , Name ,
Offset
}
enum class LVSymbolKind {
IsCallSiteParameter , IsConstant , IsInheritance , IsMember ,
IsParameter , IsUnspecified , IsVariable , LastEntry
}
enum class LVTypeKind {
IsBase , IsConst , IsEnumerator , IsImport ,
IsImportDeclaration , IsImportModule , IsPointer , IsPointerMember ,
IsReference , IsRestrict , IsRvalueReference , IsSubrange ,
IsTemplateParam , IsTemplateTemplateParam , IsTemplateTypeParam , IsTemplateValueParam ,
IsTypedef , IsUnaligned , IsUnspecified , IsVolatile ,
IsModifier , LastEntry
}
Functions
LVCompare & getComparator ()
StringRef typeNone ()
StringRef typeVoid ()
StringRef typeInt ()
StringRef typeUnknown ()
StringRef emptyString ()
LVOptions & options ()
void setOptions (LVOptions *Options)
LVPatterns & patterns ()
LVReader & getReader ()
LVSplitContext & getReaderSplitContext ()
LVScopeCompileUnit * getReaderCompileUnit ()
LVSortFunction getSortFunction ()
LVSortValue compareKind (const LVObject *LHS, const LVObject *RHS)
LVSortValue compareLine (const LVObject *LHS, const LVObject *RHS)
LVSortValue compareName (const LVObject *LHS, const LVObject *RHS)
LVSortValue compareOffset (const LVObject *LHS, const LVObject *RHS)
LVSortValue compareRange (const LVObject *LHS, const LVObject *RHS)
LVSortValue sortByKind (const LVObject *LHS, const LVObject *RHS)
LVSortValue sortByLine (const LVObject *LHS, const LVObject *RHS)
LVSortValue sortByName (const LVObject *LHS, const LVObject *RHS)
LVStringPool & getStringPool ()
FormattedNumber hexValue (uint64_t N, unsigned Width=HEX_WIDTH, bool Upper=false)
std::string hexString (uint64_t Value, size_t Width=HEX_WIDTH)
std::string hexSquareString (uint64_t Value)
template<typename... Args>
std::string formatAttributes (const StringRef First, Args... Others)
template<typename MapType , typename KeyType , typename ValueType >
void addItem (MapType *Map, KeyType Key, ValueType Value)
std::string transformPath (StringRef Path)
std::string flattenedFilePath (StringRef Path)
std::string formattedKind (StringRef Kind)
std::string formattedName (StringRef Name)
std::string formattedNames (StringRef Name1, StringRef Name2)
LVLexicalComponent getInnerComponent (StringRef Name)
LVStringRefs getAllLexicalComponents (StringRef Name)
std::string getScopedName (const LVStringRefs &Components, StringRef BaseName={})
uint16_t getCodeViewOperationCode (uint8_t Code)
static TypeIndex getTrueType (TypeIndex &TI)
static StringRef getRecordName (LazyRandomTypeCollection &Types, TypeIndex TI)
Variables
const LVSmall LVLocationMemberOffset = 0
const LVAddress MaxAddress = std::numeric_limits<uint64_t>::max()
constexpr LVSectionIndex UndefinedSectionIndex = 0
const int HEX_WIDTH = 12
constexpr bool UpdateHighAddress = false
static const EnumEntry< TypeLeafKind > LeafTypeNames []
Typedef Documentation
ArgVector
using llvm::logicalview::ArgVector = std::vector<std::string>
Definition at line 31 of file LVReaderHandler.h.
AttributeSpec
using llvm::logicalview::AttributeSpec = DWARFAbbreviationDeclaration::AttributeSpec
Definition at line 31 of file LVELFReader.h.
LVAddress
using llvm::logicalview::LVAddress = uint64_t
Definition at line 37 of file LVObject.h.
LVAddressRange
using llvm::logicalview::LVAddressRange = std::pair<LVAddress, LVAddress>
Definition at line 23 of file LVRange.h.
LVAttributeKindSet
using llvm::logicalview::LVAttributeKindSet = std::set<LVAttributeKind>
Definition at line 131 of file LVOptions.h.
LVCompareKindSet
using llvm::logicalview::LVCompareKindSet = std::set<LVCompareKind>
Definition at line 140 of file LVOptions.h.
LVElementDispatch
using llvm::logicalview::LVElementDispatch = std::map<LVElementKind, LVElementGetFunction>
Definition at line 64 of file LVElement.h.
LVElementGetFunction
using llvm::logicalview::LVElementGetFunction = bool (LVElement::*)() const
Definition at line 65 of file LVObject.h.
LVElementKindSet
using llvm::logicalview::LVElementKindSet = std::set<LVElementKind>
Definition at line 63 of file LVElement.h.
LVElementRequest
using llvm::logicalview::LVElementRequest = std::vector<LVElementGetFunction>
Definition at line 65 of file LVElement.h.
LVElements
using llvm::logicalview::LVElements = SmallVector<LVElement *, 8>
Definition at line 77 of file LVObject.h.
LVElementSetFunction
using llvm::logicalview::LVElementSetFunction = void (LVElement::*)()
Definition at line 64 of file LVObject.h.
LVHalf
using llvm::logicalview::LVHalf = uint16_t
Definition at line 38 of file LVObject.h.
LVInternalKindSet
using llvm::logicalview::LVInternalKindSet = std::set<LVInternalKind>
Definition at line 190 of file LVOptions.h.
LVLevel
using llvm::logicalview::LVLevel = uint32_t
Definition at line 39 of file LVObject.h.
LVLexicalComponent
using llvm::logicalview::LVLexicalComponent = std::tuple<StringRef, StringRef>
Definition at line 35 of file LVSupport.h.
LVLexicalIndex
using llvm::logicalview::LVLexicalIndex
Initial value:
    std::tuple<LVStringRefs::size_type, LVStringRefs::size_type>
Definition at line 36 of file LVSupport.h.
LVLineDispatch
using llvm::logicalview::LVLineDispatch = std::map<LVLineKind, LVLineGetFunction>
Definition at line 36 of file LVLine.h.
LVLineGetFunction
using llvm::logicalview::LVLineGetFunction = bool (LVLine::*)() const
Definition at line 67 of file LVObject.h.
LVLineKindSet
using llvm::logicalview::LVLineKindSet = std::set<LVLineKind>
Definition at line 35 of file LVLine.h.
LVLineRange
using llvm::logicalview::LVLineRange = std::pair<LVLine *, LVLine *>
Definition at line 22 of file LVLocation.h.
LVLineRecords
using llvm::logicalview::LVLineRecords = std::vector<TypeIndex>
Definition at line 120 of file LVCodeViewVisitor.cpp.
LVLineRequest
using llvm::logicalview::LVLineRequest = std::vector<LVLineGetFunction>
Definition at line 37 of file LVLine.h.
LVLines
using llvm::logicalview::LVLines = SmallVector<LVLine *, 8>
Definition at line 78 of file LVObject.h.
LVLineSetFunction
using llvm::logicalview::LVLineSetFunction = void (LVLine::*)()
Definition at line 66 of file LVObject.h.
LVLocations
using llvm::logicalview::LVLocations = SmallVector<LVLocation *, 8>
Definition at line 79 of file LVObject.h.
LVNameInfo
using llvm::logicalview::LVNameInfo = std::pair<LVAddress, uint64_t>
Definition at line 29 of file LVScope.h.
LVNames
using llvm::logicalview::LVNames = SmallVector<StringRef, 16>
Definition at line 59 of file LVCodeViewReader.h.
LVObjectGetFunction
using llvm::logicalview::LVObjectGetFunction = bool (LVObject::*)() const
Definition at line 69 of file LVObject.h.
LVObjectSetFunction
using llvm::logicalview::LVObjectSetFunction = void (LVObject::*)()
Definition at line 68 of file LVObject.h.
LVOffset
using llvm::logicalview::LVOffset = uint64_t
Definition at line 40 of file LVObject.h.
LVOffsetElementMap
using llvm::logicalview::LVOffsetElementMap = std::map<LVOffset, LVElement *>
Definition at line 66 of file LVScope.h.
LVOffsetLinesMap
using llvm::logicalview::LVOffsetLinesMap = std::map<LVOffset, LVLines>
Definition at line 67 of file LVScope.h.
LVOffsetLocationsMap
using llvm::logicalview::LVOffsetLocationsMap = std::map<LVOffset, LVLocations>
Definition at line 68 of file LVScope.h.
LVOffsets
using llvm::logicalview::LVOffsets = SmallVector<LVOffset, 8>
Definition at line 85 of file LVObject.h.
LVOffsetSet
using llvm::logicalview::LVOffsetSet = std::set<uint64_t>
Definition at line 92 of file LVOptions.h.
LVOffsetSymbolMap
using llvm::logicalview::LVOffsetSymbolMap = std::map<LVOffset, LVSymbol *>
Definition at line 69 of file LVScope.h.
LVOperations
using llvm::logicalview::LVOperations = SmallVector<LVOperation *, 8>
Definition at line 80 of file LVObject.h.
LVOutputKindSet
using llvm::logicalview::LVOutputKindSet = std::set<LVOutputKind>
Definition at line 148 of file LVOptions.h.
LVPassEntry
using llvm::logicalview::LVPassEntry = std::tuple<LVReader *, LVElement *, LVComparePass>
Definition at line 25 of file LVCompare.h.
LVPassTable
using llvm::logicalview::LVPassTable = std::vector<LVPassEntry>
Definition at line 26 of file LVCompare.h.
LVPrintKindSet
using llvm::logicalview::LVPrintKindSet = std::set<LVPrintKind>
Definition at line 162 of file LVOptions.h.
LVPublicAddresses
using llvm::logicalview::LVPublicAddresses = std::map<LVAddress, LVNameInfo>
Definition at line 31 of file LVScope.h.
LVPublicNames
using llvm::logicalview::LVPublicNames = std::map<LVScope *, LVNameInfo>
Definition at line 30 of file LVScope.h.
LVRangeEntries
using llvm::logicalview::LVRangeEntries = std::vector<LVRangeEntry>
Definition at line 47 of file LVRange.h.
LVReaders
using llvm::logicalview::LVReaders = std::vector<std::unique_ptr<LVReader>>
Definition at line 30 of file LVReaderHandler.h.
LVReportKindSet
using llvm::logicalview::LVReportKindSet = std::set<LVReportKind>
Definition at line 171 of file LVOptions.h.
LVScopeDispatch
using llvm::logicalview::LVScopeDispatch = std::map<LVScopeKind, LVScopeGetFunction>
Definition at line 63 of file LVScope.h.
LVScopeGetFunction
using llvm::logicalview::LVScopeGetFunction = bool (LVScope::*)() const
Definition at line 71 of file LVObject.h.
LVScopeKindSet
using llvm::logicalview::LVScopeKindSet = std::set<LVScopeKind>
Definition at line 62 of file LVScope.h.
LVScopeRequest
using llvm::logicalview::LVScopeRequest = std::vector<LVScopeGetFunction>
Definition at line 64 of file LVScope.h.
LVScopes
using llvm::logicalview::LVScopes = SmallVector<LVScope *, 8>
Definition at line 81 of file LVObject.h.
LVScopeSetFunction
using llvm::logicalview::LVScopeSetFunction = void (LVScope::*)()
Definition at line 70 of file LVObject.h.
LVSectionIndex
using llvm::logicalview::LVSectionIndex = uint64_t
Definition at line 36 of file LVObject.h.
LVSigned
using llvm::logicalview::LVSigned = int64_t
Definition at line 41 of file LVObject.h.
LVSmall
using llvm::logicalview::LVSmall = uint8_t
Definition at line 43 of file LVObject.h.
LVSortFunction
using llvm::logicalview::LVSortFunction
Initial value:
 LVSortValue (*)(const LVObject *LHS,
                                       const LVObject *RHS)
Definition at line 32 of file LVSort.h.
LVSortValue
using llvm::logicalview::LVSortValue = int
Definition at line 31 of file LVSort.h.
LVStringRefs
using llvm::logicalview::LVStringRefs = std::vector<StringRef>
Definition at line 34 of file LVSupport.h.
LVSymbolDispatch
using llvm::logicalview::LVSymbolDispatch = std::map<LVSymbolKind, LVSymbolGetFunction>
Definition at line 33 of file LVSymbol.h.
LVSymbolGetFunction
using llvm::logicalview::LVSymbolGetFunction = bool (LVSymbol::*)() const
Definition at line 73 of file LVObject.h.
LVSymbolKinds
using llvm::logicalview::LVSymbolKinds = std::set<SymbolKind>
Definition at line 306 of file LVCodeViewVisitor.cpp.
LVSymbolKindSet
using llvm::logicalview::LVSymbolKindSet = std::set<LVSymbolKind>
Definition at line 32 of file LVSymbol.h.
LVSymbolRequest
using llvm::logicalview::LVSymbolRequest = std::vector<LVSymbolGetFunction>
Definition at line 34 of file LVSymbol.h.
LVSymbols
using llvm::logicalview::LVSymbols = SmallVector<LVSymbol *, 8>
Definition at line 82 of file LVObject.h.
LVSymbolSetFunction
using llvm::logicalview::LVSymbolSetFunction = void (LVSymbol::*)()
Definition at line 72 of file LVObject.h.
LVTagOffsetsMap
using llvm::logicalview::LVTagOffsetsMap = std::map<dwarf::Tag, LVOffsets>
Definition at line 70 of file LVScope.h.
LVTypeDispatch
using llvm::logicalview::LVTypeDispatch = std::map<LVTypeKind, LVTypeGetFunction>
Definition at line 47 of file LVType.h.
LVTypeGetFunction
using llvm::logicalview::LVTypeGetFunction = bool (LVType::*)() const
Definition at line 75 of file LVObject.h.
LVTypeKinds
using llvm::logicalview::LVTypeKinds = std::set<TypeLeafKind>
Definition at line 305 of file LVCodeViewVisitor.cpp.
LVTypeKindSelection
using llvm::logicalview::LVTypeKindSelection = std::set<LVTypeKind>
Definition at line 46 of file LVType.h.
LVTypeRequest
using llvm::logicalview::LVTypeRequest = std::vector<LVTypeGetFunction>
Definition at line 48 of file LVType.h.
LVTypes
using llvm::logicalview::LVTypes = SmallVector<LVType *, 8>
Definition at line 83 of file LVObject.h.
LVTypeSetFunction
using llvm::logicalview::LVTypeSetFunction = void (LVType::*)()
Definition at line 74 of file LVObject.h.
LVUnsigned
using llvm::logicalview::LVUnsigned = uint64_t
Definition at line 42 of file LVObject.h.
LVValidLocation
using llvm::logicalview::LVValidLocation = bool (LVLocation::*)()
Definition at line 93 of file LVObject.h.
LVWarningKindSet
using llvm::logicalview::LVWarningKindSet = std::set<LVWarningKind>
Definition at line 180 of file LVOptions.h.
PdbOrObj
using llvm::logicalview::PdbOrObj = PointerUnion<object::ObjectFile *, pdb::PDBFile *>
Definition at line 32 of file LVReaderHandler.h.
Enumeration Type Documentation
LVAttributeKind
enum class llvm::logicalview::LVAttributeKind strong
Enumerator
All
Argument
Base
Coverage
Directories
Discarded
Discriminator
Encoded
Extended
Filename
Files
Format
Gaps
Generated
Global
Inserted
Level
Linkage
Local
Location
Offset
Pathname
Producer
Publics
Qualified
Qualifier
Range
Reference
Register
Standard
Subrange
System
Typename
Underlying
Zero
Definition at line 94 of file LVOptions.h.
LVBinaryType
enum class llvm::logicalview::LVBinaryType strong
Enumerator
NONE
ELF
COFF
Definition at line 89 of file LVObject.h.
LVCompareKind
enum class llvm::logicalview::LVCompareKind strong
Enumerator
All
Lines
Scopes
Symbols
Types
Definition at line 133 of file LVOptions.h.
LVComparePass
enum class llvm::logicalview::LVComparePass strong
Enumerator
Missing
Added
Definition at line 90 of file LVObject.h.
LVElementKind
enum class llvm::logicalview::LVElementKind strong
Enumerator
Discarded
Global
Optimized
LastEntry
Definition at line 62 of file LVElement.h.
LVInternalKind
enum class llvm::logicalview::LVInternalKind strong
Enumerator
All
Cmdline
ID
Integrity
None
Tag
Definition at line 182 of file LVOptions.h.
LVLineKind
enum class llvm::logicalview::LVLineKind strong
Enumerator
IsBasicBlock
IsDiscriminator
IsEndSequence
IsEpilogueBegin
IsLineDebug
IsLineAssembler
IsNewStatement
IsPrologueEnd
IsAlwaysStepInto
IsNeverStepInto
LastEntry
Definition at line 22 of file LVLine.h.
LVOutputKind
enum class llvm::logicalview::LVOutputKind strong
Enumerator
All
Split
Json
Text
Definition at line 142 of file LVOptions.h.
LVPrintKind
enum class llvm::logicalview::LVPrintKind strong
Enumerator
All
Elements
Instructions
Lines
Scopes
Sizes
Symbols
Summary
Types
Warnings
Definition at line 150 of file LVOptions.h.
LVReportKind
enum class llvm::logicalview::LVReportKind strong
Enumerator
All
Children
List
Parents
View
Definition at line 164 of file LVOptions.h.
LVScopeKind
enum class llvm::logicalview::LVScopeKind strong
Enumerator
IsAggregate
IsArray
IsBlock
IsCallSite
IsCatchBlock
IsClass
IsCompileUnit
IsEntryPoint
IsEnumeration
IsFunction
IsFunctionType
IsInlinedFunction
IsLabel
IsLexicalBlock
IsMember
IsNamespace
IsRoot
IsStructure
IsSubprogram
IsTemplate
IsTemplateAlias
IsTemplatePack
IsTryBlock
IsUnion
LastEntry
Definition at line 35 of file LVScope.h.
LVSortMode
enum class llvm::logicalview::LVSortMode strong
Enumerator
None
Kind
Line
Name
Offset
Definition at line 22 of file LVSort.h.
LVSubclassID
enum class llvm::logicalview::LVSubclassID : unsigned char strong
Enumerator
LV_ELEMENT
LV_LINE_FIRST
LV_LINE
LV_LINE_DEBUG
LV_LINE_ASSEMBLER
LV_LINE_LAST
lV_SCOPE_FIRST
LV_SCOPE
LV_SCOPE_AGGREGATE
LV_SCOPE_ALIAS
LV_SCOPE_ARRAY
LV_SCOPE_COMPILE_UNIT
LV_SCOPE_ENUMERATION
LV_SCOPE_FORMAL_PACK
LV_SCOPE_FUNCTION
LV_SCOPE_FUNCTION_INLINED
LV_SCOPE_FUNCTION_TYPE
LV_SCOPE_NAMESPACE
LV_SCOPE_ROOT
LV_SCOPE_TEMPLATE_PACK
LV_SCOPE_LAST
LV_SYMBOL_FIRST
LV_SYMBOL
LV_SYMBOL_LAST
LV_TYPE_FIRST
LV_TYPE
LV_TYPE_DEFINITION
LV_TYPE_ENUMERATOR
LV_TYPE_IMPORT
LV_TYPE_PARAM
LV_TYPE_SUBRANGE
LV_TYPE_LAST
Definition at line 27 of file LVElement.h.
LVSymbolKind
enum class llvm::logicalview::LVSymbolKind strong
Enumerator
IsCallSiteParameter
IsConstant
IsInheritance
IsMember
IsParameter
IsUnspecified
IsVariable
LastEntry
Definition at line 22 of file LVSymbol.h.
LVTypeKind
enum class llvm::logicalview::LVTypeKind strong
Enumerator
IsBase
IsConst
IsEnumerator
IsImport
IsImportDeclaration
IsImportModule
IsPointer
IsPointerMember
IsReference
IsRestrict
IsRvalueReference
IsSubrange
IsTemplateParam
IsTemplateTemplateParam
IsTemplateTypeParam
IsTemplateValueParam
IsTypedef
IsUnaligned
IsUnspecified
IsVolatile
IsModifier
LastEntry
Definition at line 22 of file LVType.h.
LVWarningKind
enum class llvm::logicalview::LVWarningKind strong
Enumerator
All
Coverages
Lines
Locations
Ranges
Definition at line 173 of file LVOptions.h.
Function Documentation
addItem()
template<typename MapType , typename KeyType , typename ValueType > void llvm::logicalview::addItem (MapType * Map, KeyType Key, ValueType Value)
Definition at line 138 of file LVSupport.h.
compareKind()
LVSortValue llvm::logicalview::compareKind (const LVObject * LHS, const LVObject * RHS)
Definition at line 27 of file LVSort.cpp.
compareLine()
LVSortValue llvm::logicalview::compareLine (const LVObject * LHS, const LVObject * RHS)
Definition at line 33 of file LVSort.cpp.
compareName()
LVSortValue llvm::logicalview::compareName (const LVObject * LHS, const LVObject * RHS)
Definition at line 39 of file LVSort.cpp.
compareOffset()
LVSortValue llvm::logicalview::compareOffset (const LVObject * LHS, const LVObject * RHS)
Definition at line 45 of file LVSort.cpp.
Referenced by getSortFunction().
compareRange()
LVSortValue llvm::logicalview::compareRange (const LVObject * LHS, const LVObject * RHS)
Definition at line 51 of file LVSort.cpp.
Referenced by llvm::logicalview::LVScope::sort().
emptyString()
StringRef llvm::logicalview::emptyString ()
Definition at line 32 of file LVObject.cpp.
Referenced by llvm::logicalview::LVElement::resolveFullname().
flattenedFilePath()
std::string llvm::logicalview::flattenedFilePath (StringRef Path)
Definition at line 50 of file LVSupport.cpp.
References Name.
Referenced by llvm::logicalview::LVSplitContext::open().
formatAttributes()
template<typename... Args> std::string llvm::logicalview::formatAttributes (const StringRef First, Args... Others)
Definition at line 124 of file LVSupport.h.
References llvm::First, List, and Size.
Referenced by llvm::logicalview::LVScopeFunction::printExtra(), llvm::logicalview::LVSymbol::printExtra(), and llvm::logicalview::LVTypeImport::printExtra().
formattedKind()
std::string llvm::logicalview::formattedKind (StringRef Kind) inline
Definition at line 217 of file LVSupport.h.
Referenced by llvm::logicalview::LVElement::equals(), llvm::logicalview::LVLine::markMissingParents(), llvm::logicalview::LVScope::markMissingParents(), llvm::logicalview::LVSymbol::markMissingParents(), llvm::logicalview::LVType::markMissingParents(), llvm::logicalview::LVRange::print(), llvm::logicalview::LVLineDebug::printExtra(), llvm::logicalview::LVLineAssembler::printExtra(), llvm::logicalview::LVScope::printExtra(), llvm::logicalview::LVScopeAlias::printExtra(), llvm::logicalview::LVScopeArray::printExtra(), llvm::logicalview::LVScopeCompileUnit::printExtra(), llvm::logicalview::LVScopeEnumeration::printExtra(), llvm::logicalview::LVScopeFormalPack::printExtra(), llvm::logicalview::LVScopeFunction::printExtra(), llvm::logicalview::LVScopeNamespace::printExtra(), llvm::logicalview::LVScopeRoot::printExtra(), llvm::logicalview::LVScopeTemplatePack::printExtra(), llvm::logicalview::LVSymbol::printExtra(), llvm::logicalview::LVType::printExtra(), llvm::logicalview::LVTypeDefinition::printExtra(), llvm::logicalview::LVTypeEnumerator::printExtra(), llvm::logicalview::LVTypeImport::printExtra(), llvm::logicalview::LVTypeParam::printExtra(), llvm::logicalview::LVTypeSubrange::printExtra(), llvm::logicalview::LVScopeCompileUnit::printLocalNames(), and llvm::logicalview::LVScopeCompileUnit::printWarnings().
formattedName()
std::string llvm::logicalview::formattedName (StringRef Name) inline
Definition at line 221 of file LVSupport.h.
References Name.
Referenced by llvm::logicalview::LVElement::equals(), llvm::logicalview::LVCompare::execute(), llvm::logicalview::LVScope::markMissingParents(), llvm::logicalview::LVSymbol::markMissingParents(), llvm::logicalview::LVType::markMissingParents(), llvm::logicalview::LVRange::print(), llvm::logicalview::LVObject::printAttributes(), llvm::logicalview::LVLineDebug::printExtra(), llvm::logicalview::LVLineAssembler::printExtra(), llvm::logicalview::LVScope::printExtra(), llvm::logicalview::LVScopeAlias::printExtra(), llvm::logicalview::LVScopeArray::printExtra(), llvm::logicalview::LVScopeEnumeration::printExtra(), llvm::logicalview::LVScopeFormalPack::printExtra(), llvm::logicalview::LVScopeFunction::printExtra(), llvm::logicalview::LVScopeNamespace::printExtra(), llvm::logicalview::LVScopeRoot::printExtra(), llvm::logicalview::LVScopeTemplatePack::printExtra(), llvm::logicalview::LVSymbol::printExtra(), llvm::logicalview::LVType::printExtra(), llvm::logicalview::LVTypeDefinition::printExtra(), llvm::logicalview::LVTypeEnumerator::printExtra(), llvm::logicalview::LVTypeImport::printExtra(), llvm::logicalview::LVTypeParam::printExtra(), llvm::logicalview::LVTypeSubrange::printExtra(), llvm::logicalview::LVElement::printFileIndex(), llvm::logicalview::LVScopeCompileUnit::printLocalNames(), and llvm::logicalview::LVScopeCompileUnit::printWarnings().
formattedNames()
std::string llvm::logicalview::formattedNames (StringRef Name1, StringRef Name2) inline
Definition at line 225 of file LVSupport.h.
Referenced by llvm::logicalview::LVScope::printExtra(), llvm::logicalview::LVScopeAlias::printExtra(), llvm::logicalview::LVScopeEnumeration::printExtra(), llvm::logicalview::LVScopeFunction::printExtra(), llvm::logicalview::LVSymbol::printExtra(), and llvm::logicalview::LVTypeParam::printExtra().
getAllLexicalComponents()
LVStringRefs llvm::logicalview::getAllLexicalComponents (StringRef Name)
Definition at line 140 of file LVSupport.cpp.
References getAllLexicalIndexes(), and Name.
getCodeViewOperationCode()
uint16_t llvm::logicalview::getCodeViewOperationCode (uint8_t Code) inline
Definition at line 251 of file LVSupport.h.
References llvm::codeview::Code.
Referenced by llvm::logicalview::LVOperation::getOperandsCodeViewInfo().
getComparator()
LVCompare & llvm::logicalview::getComparator () inline
Definition at line 84 of file LVCompare.h.
References llvm::logicalview::LVCompare::getInstance().
Referenced by llvm::logicalview::LVLine::report(), llvm::logicalview::LVScope::report(), llvm::logicalview::LVSymbol::report(), and llvm::logicalview::LVType::report().
getInnerComponent()
LVLexicalComponent llvm::logicalview::getInnerComponent (StringRef Name)
Definition at line 120 of file LVSupport.cpp.
References getAllLexicalIndexes(), LastEntry, Name, llvm::codeview::Outer, and llvm::StringRef::substr().
Referenced by llvm::logicalview::LVElement::setInnerComponent(), llvm::logicalview::LVLogicalVisitor::visitKnownMember(), and llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
getReader()
LVReader & llvm::logicalview::getReader () inline
Definition at line 333 of file LVReader.h.
References llvm::logicalview::LVReader::getInstance().
Referenced by llvm::logicalview::LVScopeCompileUnit::addedElement(), llvm::logicalview::LVScopeCompileUnit::addedElement(), llvm::logicalview::LVScopeCompileUnit::addedElement(), llvm::logicalview::LVScopeCompileUnit::addedElement(), llvm::logicalview::LVSymbol::addLocation(), llvm::logicalview::LVScope::addMissingElements(), llvm::logicalview::LVScope::addObject(), llvm::logicalview::LVLocationSymbol::addObject(), llvm::logicalview::LVScope::doPrint(), llvm::logicalview::LVScopeRoot::doPrintMatches(), llvm::logicalview::LVCompare::execute(), llvm::logicalview::LVSymbolTable::getIndex(), llvm::logicalview::LVOperation::getOperandsCodeViewInfo(), llvm::logicalview::LVOperation::getOperandsDWARFInfo(), getReaderCompileUnit(), getReaderSplitContext(), llvm::logicalview::LVLocation::print(), llvm::logicalview::LVLine::print(), llvm::logicalview::LVLocation::print(), llvm::logicalview::LVScope::print(), llvm::logicalview::LVScopeCompileUnit::print(), llvm::logicalview::LVSymbol::print(), llvm::logicalview::LVType::print(), llvm::logicalview::LVElement::printLinkageName(), llvm::logicalview::LVScopeCompileUnit::printSizes(), llvm::logicalview::LVScopeCompileUnit::printWarnings(), llvm::logicalview::LVScopeRoot::processRangeInformation(), llvm::logicalview::LVScope::resolveElements(), llvm::logicalview::LVElement::setFile(), llvm::logicalview::LVScopeFunction::setName(), llvm::logicalview::LVSymbolTable::update(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), and llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
getReaderCompileUnit()
LVScopeCompileUnit * llvm::logicalview::getReaderCompileUnit () inline
Definition at line 337 of file LVReader.h.
References llvm::logicalview::LVReader::getCompileUnit(), and getReader().
Referenced by llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVSymbol::calculateCoverage(), llvm::logicalview::LVLine::print(), llvm::logicalview::LVScope::print(), llvm::logicalview::LVSymbol::print(), llvm::logicalview::LVType::print(), and llvm::logicalview::LVLocation::validateRanges().
getReaderSplitContext()
LVSplitContext & llvm::logicalview::getReaderSplitContext () inline
Definition at line 334 of file LVReader.h.
References getReader(), and llvm::logicalview::LVReader::getSplitContext().
Referenced by llvm::logicalview::LVScope::doPrint(), and llvm::logicalview::LVScopeRoot::doPrintMatches().
getRecordName()
static StringRef llvm::logicalview::getRecordName (LazyRandomTypeCollection & Types, TypeIndex TI) static
Definition at line 85 of file LVCodeViewVisitor.cpp.
References llvm::consumeError(), llvm::codeview::TypeDeserializer::deserializeAs(), llvm::Record::getName(), llvm::codeview::TypeIndex::isSimple(), and Types.
Referenced by llvm::logicalview::LVLogicalVisitor::visitKnownMember(), and llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
getScopedName()
std::string llvm::logicalview::getScopedName (const LVStringRefs & Components, StringRef BaseName = {})
Definition at line 153 of file LVSupport.cpp.
References Name.
getSortFunction()
LVSortFunction llvm::logicalview::getSortFunction ()
Definition at line 100 of file LVSort.cpp.
References compareOffset(), options(), sortByKind(), sortByLine(), and sortByName().
Referenced by llvm::logicalview::LVScopeCompileUnit::printMatchedElements(), and llvm::logicalview::LVScope::sort().
getStringPool()
LVStringPool & llvm::logicalview::getStringPool ()
Definition at line 27 of file LVSupport.cpp.
Referenced by llvm::logicalview::LVScopeCompileUnit::addFilename(), llvm::logicalview::LVScopeCompileUnit::getCompilationDirectory(), llvm::logicalview::LVScopeAggregate::getEncodedArgs(), llvm::logicalview::LVScopeFunction::getEncodedArgs(), llvm::logicalview::LVScopeRoot::getFileFormatName(), llvm::logicalview::LVScopeCompileUnit::getFilename(), llvm::logicalview::LVScopeFunction::getLinkageName(), llvm::logicalview::LVSymbol::getLinkageName(), llvm::logicalview::LVElement::getName(), llvm::logicalview::LVElement::getPathname(), llvm::logicalview::LVScopeCompileUnit::getProducer(), llvm::logicalview::LVElement::getQualifiedName(), getStringIndex(), llvm::logicalview::LVSymbol::getValue(), llvm::logicalview::LVTypeEnumerator::getValue(), llvm::logicalview::LVTypeParam::getValue(), llvm::logicalview::LVScopeCompileUnit::printLocalNames(), llvm::logicalview::LVScopeCompileUnit::setCompilationDirectory(), llvm::logicalview::LVScopeAggregate::setEncodedArgs(), llvm::logicalview::LVScopeFunction::setEncodedArgs(), llvm::logicalview::LVScopeRoot::setFileFormatName(), llvm::logicalview::LVScopeFunction::setLinkageName(), llvm::logicalview::LVSymbol::setLinkageName(), llvm::logicalview::LVElement::setName(), llvm::logicalview::LVScopeCompileUnit::setProducer(), llvm::logicalview::LVElement::setQualifiedName(), llvm::logicalview::LVSymbol::setValue(), llvm::logicalview::LVTypeEnumerator::setValue(), and llvm::logicalview::LVTypeParam::setValue().
getTrueType()
static TypeIndex llvm::logicalview::getTrueType (TypeIndex & TI) static
Definition at line 50 of file LVCodeViewVisitor.cpp.
References llvm::dbgs(), llvm::codeview::TypeIndex::getIndex(), LLVM_DEBUG, and llvm::codeview::TypeIndex::setIndex().
Referenced by llvm::logicalview::LVLogicalVisitor::visitKnownRecord().
hexSquareString()
std::string llvm::logicalview::hexSquareString (uint64_t Value) inline
Definition at line 118 of file LVSupport.h.
References hexString().
Referenced by llvm::logicalview::LVScope::addMissingElements(), llvm::logicalview::LVElement::equals(), llvm::logicalview::LVCompare::execute(), llvm::logicalview::LVScope::markMissingParents(), llvm::logicalview::LVObject::printAttributes(), llvm::logicalview::LVObject::printAttributes(), llvm::logicalview::LVScopeCompileUnit::printWarnings(), and llvm::logicalview::LVElement::typeOffsetAsString().
hexString()
std::string llvm::logicalview::hexString (uint64_t Value, size_t Width = HEX_WIDTH) inline
Definition at line 110 of file LVSupport.h.
References hexValue(), llvm::raw_string_ostream::str(), and llvm::String.
Referenced by llvm::logicalview::LVLocation::getIntervalInfo(), llvm::logicalview::LVOperation::getOperandsCodeViewInfo(), llvm::logicalview::LVOperation::getOperandsDWARFInfo(), hexSquareString(), llvm::logicalview::LVScopeCompileUnit::printLocalNames(), llvm::logicalview::LVLocation::printRaw(), and llvm::logicalview::LVScopeCompileUnit::printWarnings().
hexValue()
FormattedNumber llvm::logicalview::hexValue (uint64_t N, unsigned Width = HEX_WIDTH, bool Upper = false) inline
Definition at line 104 of file LVSupport.h.
References llvm::format_hex(), N, and llvm::Upper.
Referenced by llvm::logicalview::LVBinaryReader::createInstructions(), llvm::logicalview::LVBinaryReader::createInstructions(), hexString(), llvm::logicalview::LVBinaryReader::includeInlineeLines(), llvm::logicalview::LVLogicalVisitor::inlineSiteAnnotation(), llvm::logicalview::LVBinaryReader::mapVirtualAddress(), llvm::logicalview::LVBinaryReader::mapVirtualAddress(), llvm::logicalview::LVSymbolTable::print(), llvm::logicalview::LVBinaryReader::processLines(), llvm::logicalview::LVBinaryReader::processLines(), and llvm::logicalview::LVRange::startSearch().
options()
LVOptions & llvm::logicalview::options () inline
Definition at line 445 of file LVOptions.h.
References llvm::logicalview::LVOptions::getOptions().
Referenced by llvm::logicalview::LVPatterns::addGenericPatterns(), llvm::logicalview::LVPatterns::addOffsetPatterns(), llvm::logicalview::LVPatterns::addPatterns(), llvm::logicalview::LVSymbol::calculateCoverage(), llvm::logicalview::LVLocation::calculateCoverage(), llvm::logicalview::LVPatterns::clear(), llvm::logicalview::LVLogicalVisitor::createElement(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::logicalview::LVReader::createScopes(), llvm::logicalview::LVElement::discriminatorAsString(), llvm::logicalview::LVReader::doLoad(), llvm::logicalview::LVReader::doPrint(), llvm::logicalview::LVScope::doPrint(), llvm::logicalview::LVScopeRoot::doPrintMatches(), llvm::logicalview::LVScope::equalNumberOfChildren(), llvm::logicalview::LVElement::equals(), llvm::logicalview::LVScopeFunction::equals(), llvm::logicalview::LVCompare::execute(), llvm::logicalview::LVLocation::getIntervalInfo(), llvm::logicalview::LVType::getParameters(), getSortFunction(), getStringIndex(), llvm::logicalview::LVScopeCompileUnit::incrementPrintedLines(), llvm::logicalview::LVScopeCompileUnit::incrementPrintedScopes(), llvm::logicalview::LVScopeCompileUnit::incrementPrintedSymbols(), llvm::logicalview::LVScopeCompileUnit::incrementPrintedTypes(), llvm::logicalview::LVObject::indentAsString(), llvm::logicalview::LVLogicalVisitor::inlineSiteAnnotation(), llvm::logicalview::LVObject::lineAsString(), llvm::logicalview::LVCompare::LVCompare(), llvm::logicalview::LVTypeParam::LVTypeParam(), llvm::logicalview::LVScope::markMissingParents(), llvm::logicalview::LVLine::noLineAsString(), llvm::logicalview::LVReader::notifyAddedElement(), llvm::logicalview::LVReader::notifyAddedElement(), llvm::logicalview::LVReader::notifyAddedElement(), llvm::logicalview::LVReader::notifyAddedElement(), llvm::logicalview::LVLocation::print(), llvm::logicalview::LVRange::print(), llvm::logicalview::LVScope::print(), llvm::logicalview::LVScopeCompileUnit::print(), llvm::logicalview::LVScope::printActiveRanges(), llvm::logicalview::LVObject::printAttributes(), llvm::logicalview::LVObject::printAttributes(), llvm::logicalview::LVPatterns::printElement(), llvm::logicalview::LVPatterns::printElement(), llvm::logicalview::LVPatterns::printElement(), llvm::logicalview::LVPatterns::printElement(), llvm::logicalview::LVScope::printEncodedArgs(), llvm::logicalview::LVLineDebug::printExtra(), llvm::logicalview::LVScopeCompileUnit::printExtra(), llvm::logicalview::LVScopeRoot::printExtra(), llvm::logicalview::LVSymbol::printExtra(), llvm::logicalview::LVElement::printFileIndex(), llvm::logicalview::LVCompare::printItem(), llvm::logicalview::LVElement::printLinkageName(), llvm::logicalview::LVElement::printLinkageName(), llvm::logicalview::LVScopeCompileUnit::printLocalNames(), llvm::logicalview::LVScopeCompileUnit::printMatchedElements(), llvm::logicalview::LVPatterns::printObject(), llvm::logicalview::LVLogicalVisitor::printRecords(), llvm::logicalview::LVElement::printReference(), llvm::logicalview::LVReader::printScopes(), llvm::logicalview::LVScopeCompileUnit::printSizes(), llvm::logicalview::LVScopeCompileUnit::printSummary(), llvm::logicalview::LVScopeCompileUnit::printWarnings(), llvm::logicalview::LVBinaryReader::processLines(), llvm::logicalview::LVScopeRoot::processRangeInformation(), llvm::logicalview::LVScopeCompileUnit::processRangeLocationCoverage(), llvm::logicalview::LVScopeCompileUnit::propagatePatternMatch(), llvm::logicalview::LVTypeDefinition::resolveExtra(), llvm::logicalview::LVElement::resolveName(), llvm::logicalview::LVType::resolveName(), llvm::logicalview::LVScopeFunction::resolveReferences(), llvm::logicalview::LVScope::resolveTemplate(), llvm::logicalview::LVElement::setFile(), llvm::logicalview::LVElement::setGenericType(), llvm::logicalview::LVScope::traverseParentsAndChildren(), llvm::logicalview::LVElement::typeOffsetAsString(), llvm::logicalview::LVPatterns::updateReportOptions(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitKnownRecord(), llvm::logicalview::LVSymbolVisitor::visitSymbolBegin(), and llvm::logicalview::LVTypeVisitor::visitTypeBegin().
patterns()
LVPatterns & llvm::logicalview::patterns () inline
Definition at line 642 of file LVOptions.h.
References llvm::logicalview::LVPatterns::getPatterns().
Referenced by llvm::logicalview::LVReader::doLoad(), llvm::logicalview::LVReader::doPrintLine(), llvm::logicalview::LVReader::doPrintLocation(), llvm::logicalview::LVReader::doPrintScope(), llvm::logicalview::LVReader::doPrintSymbol(), llvm::logicalview::LVReader::doPrintType(), llvm::logicalview::LVBinaryReader::processLines(), llvm::logicalview::LVScope::resolveName(), llvm::logicalview::LVSymbol::resolveName(), and llvm::logicalview::LVType::resolveName().
setOptions()
void llvm::logicalview::setOptions (LVOptions * Options) inline
Definition at line 446 of file LVOptions.h.
References Options, and llvm::logicalview::LVOptions::setOptions().
Referenced by llvm::logicalview::LVReaderHandler::LVReaderHandler().
sortByKind()
LVSortValue llvm::logicalview::sortByKind (const LVObject * LHS, const LVObject * RHS)
Definition at line 65 of file LVSort.cpp.
References llvm::Left, and llvm::Right.
Referenced by getSortFunction().
sortByLine()
LVSortValue llvm::logicalview::sortByLine (const LVObject * LHS, const LVObject * RHS)
Definition at line 77 of file LVSort.cpp.
References llvm::Left, and llvm::Right.
Referenced by getSortFunction().
sortByName()
LVSortValue llvm::logicalview::sortByName (const LVObject * LHS, const LVObject * RHS)
Definition at line 89 of file LVSort.cpp.
References llvm::Left, and llvm::Right.
Referenced by getSortFunction().
transformPath()
std::string llvm::logicalview::transformPath (StringRef Path)
Definition at line 33 of file LVSupport.cpp.
References Name.
Referenced by getStringIndex().
typeInt()
StringRef llvm::logicalview::typeInt ()
Definition at line 30 of file LVObject.cpp.
typeNone()
StringRef llvm::logicalview::typeNone ()
Definition at line 28 of file LVObject.cpp.
typeUnknown()
StringRef llvm::logicalview::typeUnknown ()
Definition at line 31 of file LVObject.cpp.
typeVoid()
StringRef llvm::logicalview::typeVoid ()
Definition at line 29 of file LVObject.cpp.
Referenced by llvm::logicalview::LVElement::resolveFullname(), and llvm::logicalview::LVElement::typeAsString().
Variable Documentation
HEX_WIDTH
const int llvm::logicalview::HEX_WIDTH = 12
Definition at line 103 of file LVSupport.h.
LeafTypeNames
const EnumEntry<TypeLeafKind> llvm::logicalview::LeafTypeNames[] static
Initial value:
= {
#define CV_TYPE(enum, val)
}
Definition at line 78 of file LVCodeViewVisitor.cpp.
Referenced by llvm::logicalview::LVLogicalVisitor::printMemberBegin(), and llvm::logicalview::LVLogicalVisitor::printTypeBegin().
LVLocationMemberOffset
const LVSmall llvm::logicalview::LVLocationMemberOffset = 0
Definition at line 25 of file LVLocation.h.
Referenced by llvm::logicalview::LVSymbol::addLocationConstant(), and llvm::logicalview::LVOperation::getOperandsDWARFInfo().
MaxAddress
const LVAddress llvm::logicalview::MaxAddress = std::numeric_limits<uint64_t>::max()
Definition at line 87 of file LVObject.h.
Referenced by llvm::logicalview::LVRange::clear().
UndefinedSectionIndex
constexpr LVSectionIndex llvm::logicalview::UndefinedSectionIndex = 0 constexpr
Definition at line 28 of file LVReader.h.
Referenced by llvm::logicalview::LVSymbolTable::update().
UpdateHighAddress
constexpr bool llvm::logicalview::UpdateHighAddress = false constexpr
Definition at line 33 of file LVBinaryReader.h.