LLVM: llvm::RISCVZC Namespace Reference
llvm::RISCVZC Namespace Reference
Enumerations
enum RLISTENCODE {
RA = 4 , RA_S0 , RA_S0_S1 , RA_S0_S2 ,
RA_S0_S3 , RA_S0_S4 , RA_S0_S5 , RA_S0_S6 ,
RA_S0_S7 , RA_S0_S8 , RA_S0_S9 , RA_S0_S11 ,
INVALID_RLIST
}
Functions
unsigned encodeRlist (MCRegister EndReg, bool IsRV32E=false)
static unsigned getStackAdjBase (unsigned RlistVal, bool IsRV64, bool IsEABI)
static bool getSpimm (unsigned RlistVal, unsigned &SpimmVal, int64_t StackAdjustment, bool IsRV64, bool IsEABI)
void printRlist (unsigned SlistEncode, raw_ostream &OS)
void printSpimm (int64_t Spimm, raw_ostream &OS)
Enumeration Type Documentation
RLISTENCODE
enum llvm::RISCVZC::RLISTENCODE
Enumerator
RA
RA_S0
RA_S0_S1
RA_S0_S2
RA_S0_S3
RA_S0_S4
RA_S0_S5
RA_S0_S6
RA_S0_S7
RA_S0_S8
RA_S0_S9
RA_S0_S11
INVALID_RLIST
Definition at line 517 of file RISCVBaseInfo.h.
Function Documentation
encodeRlist()
unsigned llvm::RISCVZC::encodeRlist (MCRegister EndReg, bool IsRV32E = false) inline
Definition at line 534 of file RISCVBaseInfo.h.
References assert(), INVALID_RLIST, llvm_unreachable, RA, RA_S0, RA_S0_S1, RA_S0_S11, RA_S0_S2, RA_S0_S3, RA_S0_S4, RA_S0_S5, RA_S0_S6, RA_S0_S7, RA_S0_S8, and RA_S0_S9.
getSpimm()
static bool llvm::RISCVZC::getSpimm (unsigned RlistVal, unsigned & SpimmVal, int64_t StackAdjustment, bool IsRV64, bool IsEABI) inline static
Definition at line 619 of file RISCVBaseInfo.h.
References getStackAdjBase(), and INVALID_RLIST.
getStackAdjBase()
static unsigned llvm::RISCVZC::getStackAdjBase (unsigned RlistVal, bool IsRV64, bool IsEABI) inline static
Definition at line 568 of file RISCVBaseInfo.h.
References assert(), INVALID_RLIST, llvm_unreachable, RA, RA_S0, RA_S0_S1, RA_S0_S11, RA_S0_S2, RA_S0_S3, RA_S0_S4, RA_S0_S5, RA_S0_S6, RA_S0_S7, RA_S0_S8, and RA_S0_S9.
Referenced by getSpimm(), and llvm::RISCVInstPrinter::printSpimm().
printRlist()
void llvm::RISCVZC::printRlist (unsigned SlistEncode, raw_ostream & OS)
Definition at line 299 of file RISCVBaseInfo.cpp.
References OS.
printSpimm()
void llvm::RISCVZC::printSpimm (int64_t Spimm, raw_ostream & OS)
Definition at line 311 of file RISCVBaseInfo.cpp.
References OS.
Referenced by llvm::RISCVInstPrinter::printSpimm().