LLVM: llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext Struct Reference
llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext Struct Reference
Keeps track of data associated with one object during linking.
#include "DWARFLinkerParallel/DWARFLinkerImpl.h"
Classes
struct RefModuleUnit
Keep information for referenced clang module: already loaded DWARF info of the clang module and a CompileUnit of the module.
Public Types
using UnitListTy = SmallVector<std::unique_ptr<CompileUnit>>
using ModuleUnitListTy = SmallVector<RefModuleUnit>
Public Types inherited from llvm::dwarflinker_parallel::OutputSections
enum class DebugSectionKind : uint8_t {
DebugInfo = 0 , DebugLine , DebugFrame , DebugRange ,
DebugRngLists , DebugLoc , DebugLocLists , DebugARanges ,
DebugAbbrev , DebugMacinfo , DebugMacro
}
List of tracked debug sections.
Public Member Functions
LinkContext (DWARFFile &File)
void addModulesCompileUnit (RefModuleUnit &&Unit)
Add Compile Unit corresponding to the module.
support::endianness getEndianness ()
Return Endiannes of the source DWARF information.
CompileUnit * getUnitForOffset (CompileUnit &CU, uint64_t Offset) const
Similar to DWARFUnitSection::getUnitForOffset(), but returning our CompileUnit object instead.
Public Member Functions inherited from llvm::dwarflinker_parallel::OutputSections
uint64_t getStartOffset (DebugSectionKind SectionKind) const
When objects(f.e.
void setStartOffset (DebugSectionKind SectionKind, uint64_t Offset)
Set offset to the start of specified SectionKind debug section, corresponding to this object.
Public Attributes
DWARFFile & File
Object file descriptor.
UnitListTy CompileUnits
Set of Compilation Units(may be accessed asynchroniously for reading).
ModuleUnitListTy ModulesCompileUnits
Set of Compile Units for modules.
uint64_t OriginalDebugInfoSize = 0
Size of Debug info before optimizing.
OutTablesFileTy OutDebugInfoBytes
Output sections, common for all compilation units.
support::endianness Endianess = support::endianness::little
Endianness for the final file.
Additional Inherited Members
Static Public Member Functions inherited from llvm::dwarflinker_parallel::OutputSections
static std::optional< DebugSectionKind > parseDebugSectionName (StringRef Name)
Recognise the section name and match it with the DebugSectionKind.
Static Public Attributes inherited from llvm::dwarflinker_parallel::OutputSections
static constexpr size_t SectionKindsNum = 11
Protected Attributes inherited from llvm::dwarflinker_parallel::OutputSections
std::array< uint64_t, SectionKindsNum > Offsets = {0}
Offsets to the debug sections composing this object.
Detailed Description
Keeps track of data associated with one object during linking.
i.e. source file descriptor, compilation units, output data for compilation units common tables.
Definition at line 173 of file DWARFLinkerImpl.h.
Member Typedef Documentation
ModuleUnitListTy
using llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext::ModuleUnitListTy = SmallVector<RefModuleUnit>
Definition at line 188 of file DWARFLinkerImpl.h.
UnitListTy
using llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext::UnitListTy = SmallVector<std::unique_ptr<CompileUnit>>
Definition at line 174 of file DWARFLinkerImpl.h.
Constructor & Destructor Documentation
LinkContext()
llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext::LinkContext (DWARFFile & File) inline
Definition at line 208 of file DWARFLinkerImpl.h.
References CompileUnits, llvm::dwarflinker_parallel::DWARFFile::Dwarf, Endianess, File, and llvm::SmallVectorImpl< T >::reserve().
Member Function Documentation
addModulesCompileUnit()
void llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext::addModulesCompileUnit (RefModuleUnit && Unit) inline
Add Compile Unit corresponding to the module.
Definition at line 219 of file DWARFLinkerImpl.h.
References llvm::SmallVectorImpl< T >::emplace_back(), and ModulesCompileUnits.
getEndianness()
support::endianness llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext::getEndianness () inline
Return Endiannes of the source DWARF information.
Definition at line 224 of file DWARFLinkerImpl.h.
References Endianess.
getUnitForOffset()
CompileUnit * llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext::getUnitForOffset (CompileUnit & CU, uint64_t Offset) const
Similar to DWARFUnitSection::getUnitForOffset(), but returning our CompileUnit object instead.
Returns
pointer to compilation unit which corresponds Offset.
Definition at line 17 of file DWARFLinkerImpl.cpp.
References CompileUnits, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::Offset, and llvm::upper_bound().
Member Data Documentation
CompileUnits
UnitListTy llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext::CompileUnits
Set of Compilation Units(may be accessed asynchroniously for reading).
Definition at line 194 of file DWARFLinkerImpl.h.
Referenced by getUnitForOffset(), and LinkContext().
Endianess
support::endianness llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext::Endianess = support::endianness::little
Endianness for the final file.
Definition at line 206 of file DWARFLinkerImpl.h.
Referenced by getEndianness(), and LinkContext().
File
DWARFFile& llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext::File
Object file descriptor.
Definition at line 191 of file DWARFLinkerImpl.h.
Referenced by LinkContext().
ModulesCompileUnits
ModuleUnitListTy llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext::ModulesCompileUnits
Set of Compile Units for modules.
Definition at line 197 of file DWARFLinkerImpl.h.
Referenced by addModulesCompileUnit().
OriginalDebugInfoSize
uint64_t llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext::OriginalDebugInfoSize = 0
Size of Debug info before optimizing.
Definition at line 200 of file DWARFLinkerImpl.h.
OutDebugInfoBytes
OutTablesFileTy llvm::dwarflinker_parallel::DWARFLinkerImpl::LinkContext::OutDebugInfoBytes
Output sections, common for all compilation units.
Definition at line 203 of file DWARFLinkerImpl.h.
The documentation for this struct was generated from the following files:
lib/DWARFLinkerParallel/DWARFLinkerImpl.h
lib/DWARFLinkerParallel/DWARFLinkerImpl.cpp