LLVM: llvm::gsym::StringTable Struct Reference
llvm::gsym::StringTable Struct Reference
String tables in GSYM files are required to start with an empty string at offset zero.
#include "llvm/DebugInfo/GSYM/StringTable.h"
Public Member Functions
StringTable ()=default
StringTable (StringRef D)
StringRef operator[] (size_t Offset) const
StringRef getString (uint32_t Offset) const
void clear ()
Public Attributes
StringRef Data
Detailed Description
String tables in GSYM files are required to start with an empty string at offset zero.
Strings must be UTF8 NULL terminated strings.
Definition at line 21 of file StringTable.h.
Constructor & Destructor Documentation
StringTable() [1/2]
llvm::gsym::StringTable::StringTable () default
StringTable() [2/2]
llvm::gsym::StringTable::StringTable (StringRef D) inline
Definition at line 24 of file StringTable.h.
Member Function Documentation
clear()
void llvm::gsym::StringTable::clear () inline
Definition at line 33 of file StringTable.h.
References Data.
getString()
StringRef llvm::gsym::StringTable::getString (uint32_t Offset) const inline
Definition at line 26 of file StringTable.h.
References Data, End, llvm::StringRef::find(), llvm::Offset, llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by llvm::gsym::operator<<(), and operator[]().
operator[]()
StringRef llvm::gsym::StringTable::operator[] (size_t Offset) const inline
Definition at line 25 of file StringTable.h.
References getString(), and llvm::Offset.
Member Data Documentation
Data
StringRef llvm::gsym::StringTable::Data
Definition at line 22 of file StringTable.h.
Referenced by clear(), getString(), and llvm::gsym::operator<<().
The documentation for this struct was generated from the following file:
include/llvm/DebugInfo/GSYM/StringTable.h