LLVM: llvm::AAPotentialConstantValues Struct Reference
llvm::AAPotentialConstantValues Struct Reference
An abstract interface for potential values analysis.
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
using Base = StateWrapper<PotentialConstantIntValuesState, AbstractAttribute>
Public Types inherited from llvm::StateWrapper< PotentialConstantIntValuesState, AbstractAttribute >
using StateType
Provide static access to the type of the state.
Public Types inherited from llvm::AbstractAttribute
using StateType = AbstractState
Public Types inherited from llvm::IRPosition
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
using CallBaseContext = CallBase
Public Types inherited from llvm::AADepGraphNode
using DepTy = PointerIntPair<AADepGraphNode *, 1>
using DepSetTy = SmallSetVector<DepTy, 2>
using iterator = mapped_iterator<DepSetTy::iterator, decltype(&DepGetVal)>
using aaiterator
Public Types inherited from llvm::PotentialValuesState< MemberTy >
using SetTy = SmallSetVector<MemberTy, 8>
Public Member Functions
AAPotentialConstantValues (const IRPosition &IRP, Attributor &A)
PotentialConstantIntValuesState & getState () override
See AbstractAttribute::getState(...).
const PotentialConstantIntValuesState & getState () const override
std::optional< Constant * > getAssumedConstant (Attributor &A, const Instruction *CtxI=nullptr) const
Return assumed constant for the associated value.
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::StateWrapper< PotentialConstantIntValuesState, AbstractAttribute >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (const IRPosition &IRP)
virtual ~AbstractAttribute ()=default
Virtual destructor.
virtual void initialize (Attributor &A)
Initialize the state with the information in the Attributor A.
virtual bool isQueryAA () const
A query AA is always scheduled as long as we do updates because it does lazy computation that cannot be determined to be done from the outside.
const IRPosition & getIRPosition () const
Return an IR position, see struct IRPosition.
IRPosition & getIRPosition ()
void print (raw_ostream &OS) const
Helper functions, for debug purposes only.
void print (Attributor *, raw_ostream &OS) const override
virtual void printWithDeps (raw_ostream &OS) const
void dump () const
virtual const std::string getAsStr (Attributor *A) const =0
This function should return the "summarized" assumed state as string.
Public Member Functions inherited from llvm::IRPosition
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
bool isFunctionScope () const
Return true if this is a function or call site position.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getCalleeArgNo () const
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
int getCallSiteArgNo () const
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Value * getAttrListAnchor () const
Return the value attributes are attached to.
AttributeList getAttrList () const
Return the attributes associated with this function or call site scope.
void setAttrList (const AttributeList &AttrList) const
Update the attributes associated with this function or call site scope.
unsigned getNumArgs () const
Return the number of arguments associated with this function or call site scope.
Value * getArg (unsigned ArgNo) const
Return theargument ArgNo associated with this function or call site scope.
Kind getPositionKind () const
Return the associated position kind.
bool isAnyCallSitePosition () const
bool isArgumentPosition () const
Return true if the position is an argument or call site argument.
IRPosition stripCallBaseContext () const
Return the same position without the call base context.
const CallBaseContext * getCallBaseContext () const
Get the call base context from the position.
bool hasCallBaseContext () const
Check if the position has any call base context.
operator void * () const
}
Public Member Functions inherited from llvm::AADepGraphNode
virtual ~AADepGraphNode ()=default
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
void print (raw_ostream &OS) const
DepSetTy & getDeps ()
Public Member Functions inherited from llvm::PotentialValuesState< MemberTy >
PotentialValuesState ()
PotentialValuesState (bool IsValid)
bool isValidState () const override
See AbstractState::isValidState(...)
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
PotentialValuesState & getAssumed ()
Return the assumed state.
const PotentialValuesState & getAssumed () const
const SetTy & getAssumedSet () const
Return this set.
bool undefIsContained () const
Returns whether this state contains an undef value or not.
bool operator== (const PotentialValuesState &RHS) const
void unionAssumed (const MemberTy &C)
Union assumed set with the passed value.
void unionAssumed (const PotentialValuesState &PVS)
Union assumed set with assumed set of the passed state PVS.
void unionAssumedWithUndef ()
Union assumed set with an undef value.
PotentialValuesState operator^= (const PotentialValuesState &PVS)
"Clamp" this state with PVS.
PotentialValuesState operator&= (const PotentialValuesState &PVS)
bool contains (const MemberTy &V) const
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
Static Public Member Functions
static bool isValidIRPositionForInit (Attributor &A, const IRPosition &IRP)
See AbstractAttribute::isValidIRPositionForInit.
static bool requiresCallersForArgOrFunction ()
See AbstractAttribute::requiresCallersForArgOrFunction.
static AAPotentialConstantValues & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAPotentialConstantValues.
Static Public Member Functions inherited from llvm::AbstractAttribute
static bool classof (const AADepGraphNode *DGN)
This function is used to identify if an DGN is of type AbstractAttribute so that the dyn_cast and cast can use such information to cast an AADepGraphNode to an AbstractAttribute.
static bool hasTrivialInitializer ()
Return false if this AA does anything non-trivial (hence not done by default) in its initializer.
static bool requiresCalleeForCallBase ()
Return true if this AA requires a "callee" (or an associted function) for a call site positon.
static bool requiresCallersForArgOrFunction ()
Return true if this AA requires all callees for an argument or function positon.
static bool isValidIRPositionForInit (Attributor &A, const IRPosition &IRP)
Return false if an AA should not be created for IRP.
static bool isValidIRPositionForUpdate (Attributor &A, const IRPosition &IRP)
Return false if an AA should not be updated for IRP.
Static Public Member Functions inherited from llvm::IRPosition
static const IRPosition value (const Value &V, const CallBaseContext *CBContext=nullptr)
Create a position describing the value of V.
static const IRPosition inst (const Instruction &I, const CallBaseContext *CBContext=nullptr)
Create a position describing the instruction I.
static const IRPosition function (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg, const CallBaseContext *CBContext=nullptr)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP, const CallBaseContext *CBContext=nullptr)
Create a position with function scope matching the "context" of IRP.
Static Public Member Functions inherited from llvm::PotentialValuesState< MemberTy >
static PotentialValuesState getBestState ()
Return empty set as the best state of potential values.
static PotentialValuesState getBestState (const PotentialValuesState &PVS)
static PotentialValuesState getWorstState ()
Return full set as the worst state of potential values.
Static Public Attributes
static const char ID = 0
Unique ID (due to the unique address)
Static Public Attributes inherited from llvm::IRPosition
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Static Public Attributes inherited from llvm::PotentialValuesState< MemberTy >
static unsigned MaxPotentialValues = 0
Maximum number of potential values to be tracked.
Additional Inherited Members
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
virtual ChangeStatus manifest (Attributor &A)
Hook for the Attributor to trigger the manifestation of the information represented by the abstract attribute in the LLVM-IR.
virtual void trackStatistics () const =0
Hook to enable custom statistic tracking, called after manifest that resulted in a change if statistics are enabled.
virtual ChangeStatus updateImpl (Attributor &A)=0
The actual update/transfer function which has to be implemented by the derived classes.
Protected Member Functions inherited from llvm::AADepGraphNode
operator AbstractAttribute * ()
Protected Member Functions inherited from llvm::PotentialValuesState< MemberTy >
SetTy & getAssumedSet ()
Static Protected Member Functions inherited from llvm::AADepGraphNode
static AADepGraphNode * DepGetVal (const DepTy &DT)
static AbstractAttribute * DepGetValAA (const DepTy &DT)
Protected Attributes inherited from llvm::AADepGraphNode
DepSetTy Deps
Set of dependency graph nodes which should be updated if this one is updated.
Detailed Description
An abstract interface for potential values analysis.
This AA collects potential values for each IR position. An assumed set of potential values is initialized with the empty set (the best state) and it will grow monotonically as we find more potential values for this position. The set might be forced to the worst state, that is, to contain every possible value for this position in 2 cases.
We surpassed the MaxPotentialValues threshold. This includes the case that this position is affected (e.g. because of an operation) by a Value that is in the worst state.
We tried to initialize on a Value that we cannot handle (e.g. an operator we do not currently handle).
For non constant integers see AAPotentialValues.
Definition at line 5038 of file Attributor.h.
Member Typedef Documentation
Base
using llvm::AAPotentialConstantValues::Base = StateWrapper<PotentialConstantIntValuesState, AbstractAttribute>
Definition at line 5040 of file Attributor.h.
Constructor & Destructor Documentation
AAPotentialConstantValues()
llvm::AAPotentialConstantValues::AAPotentialConstantValues (const IRPosition & IRP, Attributor & A) inline
Definition at line 5041 of file Attributor.h.
Member Function Documentation
classof()
static bool llvm::AAPotentialConstantValues::classof (const AbstractAttribute * AA) inline static
This function should return true if the type of the AA is AAPotentialConstantValues.
Definition at line 5093 of file Attributor.h.
References llvm::AbstractAttribute::getIdAddr().
createForPosition()
static AAPotentialConstantValues & llvm::AAPotentialConstantValues::createForPosition (const IRPosition & IRP, Attributor & A) static
Create an abstract attribute view for the position IRP.
getAssumedConstant()
std::optional< Constant * > llvm::AAPotentialConstantValues::getAssumedConstant (Attributor & A, const Instruction * CtxI = nullptr) const inline
Return assumed constant for the associated value.
Definition at line 5065 of file Attributor.h.
References llvm::AADepGraphNode::begin(), llvm::UndefValue::get(), llvm::ConstantInt::get(), llvm::IRPosition::getAssociatedValue(), llvm::PotentialValuesState< MemberTy >::getAssumedSet(), llvm::Value::getType(), getType(), llvm::AA::getWithType(), llvm::PotentialValuesState< MemberTy >::isValidState(), size(), and llvm::PotentialValuesState< MemberTy >::undefIsContained().
getIdAddr()
const char * llvm::AAPotentialConstantValues::getIdAddr () const inline override virtual
See AbstractAttribute::getIdAddr()
Implements llvm::AbstractAttribute.
Definition at line 5089 of file Attributor.h.
References ID.
getName()
const std::string llvm::AAPotentialConstantValues::getName () const inline override virtual
See AbstractAttribute::getName()
Implements llvm::AbstractAttribute.
Definition at line 5084 of file Attributor.h.
getState() [1/2]
const PotentialConstantIntValuesState & llvm::AAPotentialConstantValues::getState () const inline override virtual
Implements llvm::AbstractAttribute.
Definition at line 5055 of file Attributor.h.
getState() [2/2]
PotentialConstantIntValuesState & llvm::AAPotentialConstantValues::getState () inline override virtual
See AbstractAttribute::getState(...).
Implements llvm::AbstractAttribute.
Definition at line 5054 of file Attributor.h.
isValidIRPositionForInit()
static bool llvm::AAPotentialConstantValues::isValidIRPositionForInit (Attributor & A, const IRPosition & IRP) inline static
See AbstractAttribute::isValidIRPositionForInit.
Definition at line 5044 of file Attributor.h.
References A, and llvm::AbstractAttribute::isValidIRPositionForInit().
requiresCallersForArgOrFunction()
static bool llvm::AAPotentialConstantValues::requiresCallersForArgOrFunction () inline static
See AbstractAttribute::requiresCallersForArgOrFunction.
Definition at line 5051 of file Attributor.h.
Member Data Documentation
ID
const char AAPotentialConstantValues::ID = 0 static
Unique ID (due to the unique address)
Definition at line 5098 of file Attributor.h.
Referenced by getIdAddr().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/AttributorAttributes.cpp