LLVM: llvm::AAPointerInfo::RangeList Struct Reference
llvm::AAPointerInfo::RangeList Struct Reference
A container for a list of ranges.
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
using RangeTy = AA::RangeTy
using VecTy = SmallVector<RangeTy>
using iterator = VecTy::iterator
using const_iterator = VecTy::const_iterator
using value_type = RangeTy
Public Member Functions
RangeList (const RangeTy &R)
RangeList (ArrayRef< int64_t > Offsets, int64_t Size)
RangeList ()=default
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
void push_back (const RangeTy &R)
unsigned size () const
bool operator== (const RangeList &OI) const
bool merge (const RangeList &RHS)
Merge the ranges in RHS into the current ranges.
std::pair< iterator, bool > insert (iterator Pos, const RangeTy &R)
Insert R at the given iterator Pos, and merge if necessary.
std::pair< iterator, bool > insert (const RangeTy &R)
Insert the given range R, maintaining sorted order.
void addToAllOffsets (int64_t Inc)
Add the increment Inc to the offset of every range.
bool isUnique () const
Return true iff there is exactly one range and it is known.
const RangeTy & getUnique () const
Return the unique range, assuming it exists.
bool isUnknown () const
Return true iff the list contains an unknown range.
iterator setUnknown ()
Discard all ranges and insert a single unknown range.
bool isUnassigned () const
Return true if no ranges have been inserted.
Static Public Member Functions
static void set_difference (const RangeList &L, const RangeList &R, RangeList &D)
Copy ranges from L that are not in R, into D.
Public Attributes
VecTy Ranges
Detailed Description
A container for a list of ranges.
Definition at line 5582 of file Attributor.h.
Member Typedef Documentation
const_iterator
using llvm::AAPointerInfo::RangeList::const_iterator = VecTy::const_iterator
Definition at line 5590 of file Attributor.h.
iterator
using llvm::AAPointerInfo::RangeList::iterator = VecTy::iterator
Definition at line 5589 of file Attributor.h.
RangeTy
using llvm::AAPointerInfo::RangeList::RangeTy = AA::RangeTy
Definition at line 5587 of file Attributor.h.
value_type
using llvm::AAPointerInfo::RangeList::value_type = RangeTy
Definition at line 5610 of file Attributor.h.
VecTy
using llvm::AAPointerInfo::RangeList::VecTy = SmallVector<RangeTy>
Definition at line 5588 of file Attributor.h.
Constructor & Destructor Documentation
RangeList() [1/3]
llvm::AAPointerInfo::RangeList::RangeList (const RangeTy & R) inline
Definition at line 5593 of file Attributor.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back(), and Ranges.
RangeList() [2/3]
llvm::AAPointerInfo::RangeList::RangeList (ArrayRef< int64_t > Offsets, int64_t Size) inline
Definition at line 5594 of file Attributor.h.
References assert(), llvm::SmallVectorImpl< T >::emplace_back(), Ranges, llvm::SmallVectorImpl< T >::reserve(), and Size.
RangeList() [3/3]
llvm::AAPointerInfo::RangeList::RangeList () default
Member Function Documentation
addToAllOffsets()
void llvm::AAPointerInfo::RangeList::addToAllOffsets (int64_t Inc) inline
Add the increment Inc to the offset of every range.
Definition at line 5689 of file Attributor.h.
References assert(), isUnassigned(), isUnknown(), and Ranges.
begin() [1/2]
iterator llvm::AAPointerInfo::RangeList::begin () inline
Definition at line 5604 of file Attributor.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and Ranges.
Referenced by llvm::AAPointerInfo::Access::begin().
begin() [2/2]
const_iterator llvm::AAPointerInfo::RangeList::begin () const inline
Definition at line 5606 of file Attributor.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and Ranges.
end() [1/2]
iterator llvm::AAPointerInfo::RangeList::end () inline
Definition at line 5605 of file Attributor.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and Ranges.
Referenced by llvm::AAPointerInfo::Access::end().
end() [2/2]
const_iterator llvm::AAPointerInfo::RangeList::end () const inline
Definition at line 5607 of file Attributor.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and Ranges.
getUnique()
const RangeTy & llvm::AAPointerInfo::RangeList::getUnique () const inline
Return the unique range, assuming it exists.
Definition at line 5705 of file Attributor.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::front(), isUnique(), and Ranges.
Referenced by llvm::AAPointerInfo::Access::getUniqueRange().
insert() [1/2]
std::pair< iterator, bool > llvm::AAPointerInfo::RangeList::insert (const RangeTy & R) inline
Insert the given range R, maintaining sorted order.
Returns
The place of insertion and true iff anything changed.
Definition at line 5684 of file Attributor.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), insert(), and Ranges.
insert() [2/2]
std::pair< iterator, bool > llvm::AAPointerInfo::RangeList::insert (iterator Pos, const RangeTy & R) inline
Insert R at the given iterator Pos, and merge if necessary.
This assumes that all ranges before Pos are OffsetLessThan R, and then maintains the sorted order for the suffix list.
Returns
The place of insertion and true iff anything changed.
Definition at line 5663 of file Attributor.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::insert(), isUnknown(), llvm::AA::RangeTy::OffsetLessThan(), Ranges, and setUnknown().
Referenced by llvm::AAPointerInfo::Access::addRange(), insert(), and merge().
isUnassigned()
bool llvm::AAPointerInfo::RangeList::isUnassigned () const inline
Return true if no ranges have been inserted.
Definition at line 5729 of file Attributor.h.
References Ranges, and llvm::SmallVectorBase< Size_T >::size().
Referenced by addToAllOffsets(), and isUnknown().
isUnique()
bool llvm::AAPointerInfo::RangeList::isUnique () const inline
Return true iff there is exactly one range and it is known.
Definition at line 5700 of file Attributor.h.
References llvm::SmallVectorTemplateCommon< T, typename >::front(), Ranges, and llvm::SmallVectorBase< Size_T >::size().
Referenced by getUnique(), and llvm::AAPointerInfo::Access::hasUniqueRange().
isUnknown()
bool llvm::AAPointerInfo::RangeList::isUnknown () const inline
Return true iff the list contains an unknown range.
Definition at line 5711 of file Attributor.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::front(), isUnassigned(), Ranges, and llvm::SmallVectorBase< Size_T >::size().
Referenced by addToAllOffsets(), insert(), and merge().
merge()
bool llvm::AAPointerInfo::RangeList::merge (const RangeList & RHS) inline
Merge the ranges in RHS into the current ranges.
Merging a list of unknown ranges makes the current list unknown.
Ranges with the same offset are merged according to RangeTy::operator&
Returns
true if the current RangeList changed.
Definition at line 5632 of file Attributor.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase< Size_T >::empty(), insert(), isUnknown(), Ranges, and setUnknown().
Referenced by llvm::AAPointerInfo::Access::operator&=().
operator==()
bool llvm::AAPointerInfo::RangeList::operator== (const RangeList & OI) const inline
Definition at line 5626 of file Attributor.h.
References Ranges.
push_back()
void llvm::AAPointerInfo::RangeList::push_back (const RangeTy & R) inline
Definition at line 5611 of file Attributor.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase< Size_T >::empty(), llvm::AA::RangeTy::OffsetLessThan(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and Ranges.
set_difference()
static void llvm::AAPointerInfo::RangeList::set_difference (const RangeList & L, const RangeList & R, RangeList & D) inline static
Copy ranges from L that are not in R, into D.
Definition at line 5618 of file Attributor.h.
References D, and llvm::AA::RangeTy::OffsetLessThan().
Referenced by llvm::AA::PointerInfo::State::addAccess().
setUnknown()
iterator llvm::AAPointerInfo::RangeList::setUnknown () inline
Discard all ranges and insert a single unknown range.
Definition at line 5722 of file Attributor.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::AA::RangeTy::getUnknown(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and Ranges.
Referenced by insert(), and merge().
size()
unsigned llvm::AAPointerInfo::RangeList::size () const inline
Definition at line 5624 of file Attributor.h.
References Ranges, and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::AAPointerInfo::Access::isMayAccess(), llvm::AAPointerInfo::Access::isMustAccess(), llvm::AAPointerInfo::Access::operator&=(), and llvm::AAPointerInfo::Access::verify().
Member Data Documentation
Ranges
VecTy llvm::AAPointerInfo::RangeList::Ranges
Definition at line 5591 of file Attributor.h.
Referenced by addToAllOffsets(), begin(), begin(), end(), end(), getUnique(), insert(), insert(), isUnassigned(), isUnique(), isUnknown(), merge(), operator==(), push_back(), RangeList(), RangeList(), setUnknown(), and size().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h