LLVM: llvm::SIInstrWorklist Struct Reference
llvm::SIInstrWorklist Struct Reference
Utility to store machine instructions worklist.
#include "Target/AMDGPU/SIInstrInfo.h"
Public Member Functions
SIInstrWorklist ()
void insert (MachineInstr *MI)
MachineInstr * top () const
void erase_top ()
bool empty () const
void clear ()
bool isDeferred (MachineInstr *MI)
SetVector< MachineInstr * > & getDeferredList ()
Detailed Description
Utility to store machine instructions worklist.
Definition at line 45 of file SIInstrInfo.h.
Constructor & Destructor Documentation
SIInstrWorklist()
llvm::SIInstrWorklist::SIInstrWorklist () inline
Definition at line 46 of file SIInstrInfo.h.
Member Function Documentation
clear()
void llvm::SIInstrWorklist::clear () inline
Definition at line 62 of file SIInstrInfo.h.
empty()
bool llvm::SIInstrWorklist::empty () const inline
Definition at line 60 of file SIInstrInfo.h.
Referenced by llvm::SIInstrInfo::moveToVALU().
erase_top()
void llvm::SIInstrWorklist::erase_top () inline
Definition at line 55 of file SIInstrInfo.h.
Referenced by llvm::SIInstrInfo::moveToVALU().
getDeferredList()
SetVector< MachineInstr * > & llvm::SIInstrWorklist::getDeferredList () inline
Definition at line 69 of file SIInstrInfo.h.
Referenced by llvm::SIInstrInfo::moveToVALU().
insert()
void SIInstrWorklist::insert (MachineInstr * MI)
Definition at line 6323 of file SIInstrInfo.cpp.
References llvm::AMDGPU::getNamedOperandIdx(), and MI.
isDeferred()
bool SIInstrWorklist::isDeferred (MachineInstr * MI)
Definition at line 6333 of file SIInstrInfo.cpp.
References MI.
Referenced by llvm::SIInstrInfo::moveToVALU().
top()
MachineInstr * llvm::SIInstrWorklist::top () const inline
Definition at line 50 of file SIInstrInfo.h.
Referenced by llvm::SIInstrInfo::moveToVALU().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/SIInstrInfo.h
lib/Target/AMDGPU/SIInstrInfo.cpp