LLVM: llvm::rdf::RegisterAggr Struct Reference
llvm::rdf::RegisterAggr Struct Reference
#include "llvm/CodeGen/RDFRegisters.h"
Classes
struct ref_iterator
Public Types
using unit_iterator = typename BitVector::const_set_bits_iterator
Public Member Functions
RegisterAggr (const PhysicalRegisterInfo &pri)
RegisterAggr (const RegisterAggr &RG)=default
unsigned size () const
bool empty () const
bool hasAliasOf (RegisterRef RR) const
bool hasCoverOf (RegisterRef RR) const
const PhysicalRegisterInfo & getPRI () const
bool operator== (const RegisterAggr &A) const
RegisterAggr & insert (RegisterRef RR)
RegisterAggr & insert (const RegisterAggr &RG)
RegisterAggr & intersect (RegisterRef RR)
RegisterAggr & intersect (const RegisterAggr &RG)
RegisterAggr & clear (RegisterRef RR)
RegisterAggr & clear (const RegisterAggr &RG)
RegisterRef intersectWith (RegisterRef RR) const
RegisterRef clearIn (RegisterRef RR) const
RegisterRef makeRegRef () const
size_t hash () const
ref_iterator ref_begin () const
ref_iterator ref_end () const
unit_iterator unit_begin () const
unit_iterator unit_end () const
iterator_range< ref_iterator > refs () const
iterator_range< unit_iterator > units () const
Static Public Member Functions
static bool isCoverOf (RegisterRef RA, RegisterRef RB, const PhysicalRegisterInfo &PRI)
Detailed Description
Definition at line 204 of file RDFRegisters.h.
Member Typedef Documentation
unit_iterator
using llvm::rdf::RegisterAggr::unit_iterator = typename BitVector::const_set_bits_iterator
Definition at line 272 of file RDFRegisters.h.
Constructor & Destructor Documentation
RegisterAggr() [1/2]
llvm::rdf::RegisterAggr::RegisterAggr (const PhysicalRegisterInfo & pri) inline
Definition at line 205 of file RDFRegisters.h.
Referenced by clear(), clearIn(), intersect(), and isCoverOf().
RegisterAggr() [2/2]
llvm::rdf::RegisterAggr::RegisterAggr (const RegisterAggr & RG) default
Member Function Documentation
clear() [1/2]
RegisterAggr & llvm::rdf::RegisterAggr::clear (const RegisterAggr & RG)
Definition at line 360 of file RDFRegisters.cpp.
References llvm::BitVector::reset().
clear() [2/2]
RegisterAggr & llvm::rdf::RegisterAggr::clear (RegisterRef RR)
Definition at line 356 of file RDFRegisters.cpp.
References clear(), insert(), and RegisterAggr().
Referenced by clear().
clearIn()
RegisterRef llvm::rdf::RegisterAggr::clearIn (RegisterRef RR) const
Definition at line 375 of file RDFRegisters.cpp.
References RegisterAggr().
Referenced by llvm::rdf::Liveness::computePhiInfo().
empty()
bool llvm::rdf::RegisterAggr::empty () const inline
Definition at line 210 of file RDFRegisters.h.
References llvm::BitVector::none().
getPRI()
const PhysicalRegisterInfo & llvm::rdf::RegisterAggr::getPRI () const inline
Definition at line 214 of file RDFRegisters.h.
hasAliasOf()
bool llvm::rdf::RegisterAggr::hasAliasOf (RegisterRef RR) const
Definition at line 300 of file RDFRegisters.cpp.
References llvm::BitVector::anyCommon(), llvm::rdf::PhysicalRegisterInfo::getMaskUnits(), llvm::rdf::PhysicalRegisterInfo::getTRI(), P, and llvm::BitVector::test().
hasCoverOf()
bool llvm::rdf::RegisterAggr::hasCoverOf (RegisterRef RR) const
Definition at line 313 of file RDFRegisters.cpp.
References llvm::rdf::PhysicalRegisterInfo::getMaskUnits(), llvm::rdf::PhysicalRegisterInfo::getTRI(), P, T, and llvm::BitVector::test().
hash()
size_t llvm::rdf::RegisterAggr::hash () const inline
Definition at line 236 of file RDFRegisters.h.
insert() [1/2]
RegisterAggr & llvm::rdf::RegisterAggr::insert (const RegisterAggr & RG)
Definition at line 342 of file RDFRegisters.cpp.
insert() [2/2]
RegisterAggr & llvm::rdf::RegisterAggr::insert (RegisterRef RR)
Definition at line 328 of file RDFRegisters.cpp.
References llvm::rdf::PhysicalRegisterInfo::getMaskUnits(), llvm::rdf::PhysicalRegisterInfo::getTRI(), P, and llvm::BitVector::set().
Referenced by llvm::rdf::DataFlowGraph::build(), clear(), llvm::rdf::Liveness::computePhiInfo(), and intersect().
intersect() [1/2]
RegisterAggr & llvm::rdf::RegisterAggr::intersect (const RegisterAggr & RG)
Definition at line 351 of file RDFRegisters.cpp.
intersect() [2/2]
RegisterAggr & llvm::rdf::RegisterAggr::intersect (RegisterRef RR)
Definition at line 347 of file RDFRegisters.cpp.
References insert(), intersect(), and RegisterAggr().
Referenced by intersect().
intersectWith()
RegisterRef llvm::rdf::RegisterAggr::intersectWith (RegisterRef RR) const
Definition at line 365 of file RDFRegisters.cpp.
References assert(), and T.
isCoverOf()
static bool llvm::rdf::RegisterAggr::isCoverOf (RegisterRef RA, RegisterRef RB, const PhysicalRegisterInfo & PRI) inline static
Definition at line 220 of file RDFRegisters.h.
References RA, and RegisterAggr().
Referenced by llvm::rdf::Liveness::getAllReachingDefs().
makeRegRef()
RegisterRef llvm::rdf::RegisterAggr::makeRegRef () const
Definition at line 379 of file RDFRegisters.cpp.
References F, llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::LaneBitmask::getAll(), llvm::rdf::PhysicalRegisterInfo::getTRI(), llvm::rdf::PhysicalRegisterInfo::getUnitAliases(), I, llvm::LaneBitmask::none(), P, and llvm::BitVector::test().
operator==()
bool llvm::rdf::RegisterAggr::operator== (const RegisterAggr & A) const inline
Definition at line 216 of file RDFRegisters.h.
References A.
ref_begin()
ref_iterator llvm::rdf::RegisterAggr::ref_begin () const inline
Definition at line 269 of file RDFRegisters.h.
Referenced by refs().
ref_end()
ref_iterator llvm::rdf::RegisterAggr::ref_end () const inline
Definition at line 270 of file RDFRegisters.h.
Referenced by refs().
refs()
iterator_range< ref_iterator > llvm::rdf::RegisterAggr::refs () const inline
Definition at line 276 of file RDFRegisters.h.
References llvm::make_range(), ref_begin(), and ref_end().
Referenced by llvm::rdf::DataFlowGraph::build(), and llvm::rdf::Liveness::resetLiveIns().
size()
unsigned llvm::rdf::RegisterAggr::size () const inline
Definition at line 209 of file RDFRegisters.h.
References llvm::BitVector::count().
unit_begin()
unit_iterator llvm::rdf::RegisterAggr::unit_begin () const inline
Definition at line 273 of file RDFRegisters.h.
References llvm::BitVector::set_bits_begin().
Referenced by units().
unit_end()
unit_iterator llvm::rdf::RegisterAggr::unit_end () const inline
Definition at line 274 of file RDFRegisters.h.
References llvm::BitVector::set_bits_end().
Referenced by units().
units()
iterator_range< unit_iterator > llvm::rdf::RegisterAggr::units () const inline
Definition at line 279 of file RDFRegisters.h.
References llvm::make_range(), unit_begin(), and unit_end().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFRegisters.h
lib/CodeGen/RDFRegisters.cpp