LLVM: llvm::BasicAAResult::DecomposedGEP Struct Reference
llvm::BasicAAResult::DecomposedGEP Struct Reference
Public Member Functions
void dump () const
void print (raw_ostream &OS) const
Public Attributes
const Value * Base
APInt Offset
SmallVector< VariableGEPIndex, 4 > VarIndices
std::optional< bool > InBounds
Detailed Description
Definition at line 493 of file BasicAliasAnalysis.cpp.
Member Function Documentation
dump()
void llvm::BasicAAResult::DecomposedGEP::dump () const inline
Definition at line 504 of file BasicAliasAnalysis.cpp.
References llvm::dbgs(), and llvm::BasicAAResult::DecomposedGEP::print().
print()
void llvm::BasicAAResult::DecomposedGEP::print (raw_ostream & OS) const inline
Definition at line 508 of file BasicAliasAnalysis.cpp.
References llvm::BasicAAResult::DecomposedGEP::Base, llvm::Value::getName(), llvm::BasicAAResult::DecomposedGEP::Offset, OS, llvm::SmallVectorBase< Size_T >::size(), and llvm::BasicAAResult::DecomposedGEP::VarIndices.
Referenced by llvm::BasicAAResult::DecomposedGEP::dump().
Member Data Documentation
Base
const Value* llvm::BasicAAResult::DecomposedGEP::Base
Definition at line 495 of file BasicAliasAnalysis.cpp.
Referenced by llvm::BasicAAResult::DecomposedGEP::print().
InBounds
std::optional<bool> llvm::BasicAAResult::DecomposedGEP::InBounds
Definition at line 502 of file BasicAliasAnalysis.cpp.
Offset
APInt llvm::BasicAAResult::DecomposedGEP::Offset
Definition at line 497 of file BasicAliasAnalysis.cpp.
Referenced by llvm::BasicAAResult::DecomposedGEP::print().
VarIndices
SmallVector<VariableGEPIndex, 4> llvm::BasicAAResult::DecomposedGEP::VarIndices
Definition at line 499 of file BasicAliasAnalysis.cpp.
Referenced by llvm::BasicAAResult::DecomposedGEP::print().
The documentation for this struct was generated from the following file:
lib/Analysis/BasicAliasAnalysis.cpp