LLVM: llvm::rdf::DataFlowGraph::DefStack Struct Reference
llvm::rdf::DataFlowGraph::DefStack Struct Reference
#include "llvm/CodeGen/RDFGraph.h"
Public Types
using iterator = Iterator
Public Member Functions
DefStack ()=default
bool empty () const
iterator top () const
iterator bottom () const
unsigned size () const
void push (Def DA)
void pop ()
void start_block (NodeId N)
void clear_block (NodeId N)
Friends
struct Iterator
Detailed Description
Definition at line 702 of file RDFGraph.h.
Member Typedef Documentation
iterator
using llvm::rdf::DataFlowGraph::DefStack::iterator = Iterator
Definition at line 744 of file RDFGraph.h.
Constructor & Destructor Documentation
DefStack()
llvm::rdf::DataFlowGraph::DefStack::DefStack () default
Member Function Documentation
bottom()
iterator llvm::rdf::DataFlowGraph::DefStack::bottom () const inline
Definition at line 747 of file RDFGraph.h.
References Iterator.
Referenced by empty(), and size().
clear_block()
void llvm::rdf::DataFlowGraph::DefStack::clear_block (NodeId N)
Definition at line 699 of file RDFGraph.cpp.
References assert(), N, and P.
empty()
bool llvm::rdf::DataFlowGraph::DefStack::empty () const inline
Definition at line 705 of file RDFGraph.h.
References bottom(), and top().
pop()
void llvm::rdf::DataFlowGraph::DefStack::pop ()
Definition at line 684 of file RDFGraph.cpp.
References assert(), and P.
push()
void llvm::rdf::DataFlowGraph::DefStack::push (Def DA) inline
Definition at line 750 of file RDFGraph.h.
size()
unsigned llvm::rdf::DataFlowGraph::DefStack::size () const
Definition at line 674 of file RDFGraph.cpp.
References bottom(), E, I, and top().
start_block()
void llvm::rdf::DataFlowGraph::DefStack::start_block (NodeId N)
Definition at line 691 of file RDFGraph.cpp.
References assert(), and N.
top()
iterator llvm::rdf::DataFlowGraph::DefStack::top () const inline
Definition at line 746 of file RDFGraph.h.
References Iterator.
Referenced by empty(), and size().
Friends And Related Symbol Documentation
Iterator
friend struct Iterator friend
Definition at line 756 of file RDFGraph.h.
Referenced by bottom(), and top().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFGraph.h
lib/CodeGen/RDFGraph.cpp