LLVM: llvm::DWARFDebugNames::Header Struct Reference
llvm::DWARFDebugNames::Header Struct Reference
DWARF v5 Name Index header.
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
Public Member Functions
Error extract (const DWARFDataExtractor &AS, uint64_t *Offset)
void dump (ScopedPrinter &W) const
Public Attributes
uint64_t UnitLength
dwarf::DwarfFormat Format
uint16_t Version
uint32_t CompUnitCount
uint32_t LocalTypeUnitCount
uint32_t ForeignTypeUnitCount
uint32_t BucketCount
uint32_t NameCount
uint32_t AbbrevTableSize
uint32_t AugmentationStringSize
SmallString< 8 > AugmentationString
Detailed Description
DWARF v5 Name Index header.
Definition at line 374 of file DWARFAcceleratorTable.h.
Member Function Documentation
dump()
void DWARFDebugNames::Header::dump (ScopedPrinter & W) const
Definition at line 431 of file DWARFAcceleratorTable.cpp.
References llvm::dwarf::FormatString().
extract()
Error DWARFDebugNames::Header::extract (const DWARFDataExtractor & AS, uint64_t * Offset)
Definition at line 445 of file DWARFAcceleratorTable.cpp.
References llvm::alignTo(), llvm::CallingConv::C, llvm::c_str(), llvm::createStringError(), E, llvm::DWARFDataExtractor::getInitialLength(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU8(), llvm::illegal_byte_sequence, llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::Offset, llvm::DataExtractor::skip(), and llvm::dwarf::toString().
Member Data Documentation
AbbrevTableSize
uint32_t llvm::DWARFDebugNames::Header::AbbrevTableSize
Definition at line 383 of file DWARFAcceleratorTable.h.
AugmentationString
SmallString<8> llvm::DWARFDebugNames::Header::AugmentationString
Definition at line 385 of file DWARFAcceleratorTable.h.
AugmentationStringSize
uint32_t llvm::DWARFDebugNames::Header::AugmentationStringSize
Definition at line 384 of file DWARFAcceleratorTable.h.
BucketCount
uint32_t llvm::DWARFDebugNames::Header::BucketCount
Definition at line 381 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::NameIndex::getBucketCount().
CompUnitCount
uint32_t llvm::DWARFDebugNames::Header::CompUnitCount
Definition at line 378 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::NameIndex::getCUCount().
ForeignTypeUnitCount
uint32_t llvm::DWARFDebugNames::Header::ForeignTypeUnitCount
Definition at line 380 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::NameIndex::getForeignTUCount().
Format
dwarf::DwarfFormat llvm::DWARFDebugNames::Header::Format
Definition at line 376 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::NameIndex::getNextUnitOffset().
LocalTypeUnitCount
uint32_t llvm::DWARFDebugNames::Header::LocalTypeUnitCount
Definition at line 379 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::NameIndex::getLocalTUCount().
NameCount
uint32_t llvm::DWARFDebugNames::Header::NameCount
Definition at line 382 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::NameIndex::getNameCount().
UnitLength
uint64_t llvm::DWARFDebugNames::Header::UnitLength
Definition at line 375 of file DWARFAcceleratorTable.h.
Referenced by llvm::DWARFDebugNames::NameIndex::getNextUnitOffset().
Version
uint16_t llvm::DWARFDebugNames::Header::Version
Definition at line 377 of file DWARFAcceleratorTable.h.
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h
lib/DebugInfo/DWARF/DWARFAcceleratorTable.cpp