LLVM: llvm::LegalityPredicates::TypePairAndMemDesc Struct Reference
llvm::LegalityPredicates::TypePairAndMemDesc Struct Reference
#include "llvm/CodeGen/GlobalISel/LegalizerInfo.h"
Public Member Functions
bool operator== (const TypePairAndMemDesc &Other) const
bool isCompatible (const TypePairAndMemDesc &Other) const
Public Attributes
LLT Type0
LLT Type1
LLT MemTy
uint64_t Align
Detailed Description
Definition at line 204 of file LegalizerInfo.h.
Member Function Documentation
isCompatible()
bool llvm::LegalityPredicates::TypePairAndMemDesc::isCompatible (const TypePairAndMemDesc & Other) const inline
Returns
true if this memory access is legal with for the access described by Other (The alignment is sufficient for the size and result type).
Definition at line 217 of file LegalizerInfo.h.
References llvm::Align::Align(), llvm::LLT::getSizeInBits(), MemTy, llvm::Other, Type0, and Type1.
operator==()
bool llvm::LegalityPredicates::TypePairAndMemDesc::operator== (const TypePairAndMemDesc & Other) const inline
Definition at line 210 of file LegalizerInfo.h.
References llvm::Align::Align(), MemTy, llvm::Other, Type0, and Type1.
Member Data Documentation
Align
uint64_t llvm::LegalityPredicates::TypePairAndMemDesc::Align
Definition at line 208 of file LegalizerInfo.h.
MemTy
LLT llvm::LegalityPredicates::TypePairAndMemDesc::MemTy
Definition at line 207 of file LegalizerInfo.h.
Referenced by isCompatible(), and operator==().
Type0
LLT llvm::LegalityPredicates::TypePairAndMemDesc::Type0
Definition at line 205 of file LegalizerInfo.h.
Referenced by isCompatible(), and operator==().
Type1
LLT llvm::LegalityPredicates::TypePairAndMemDesc::Type1
Definition at line 206 of file LegalizerInfo.h.
Referenced by isCompatible(), and operator==().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/GlobalISel/LegalizerInfo.h