LLVM: llvm::InferAddressSpacesPass Struct Reference
llvm::InferAddressSpacesPass Struct Reference
#include "llvm/Transforms/Scalar/InferAddressSpaces.h"
Public Member Functions
InferAddressSpacesPass ()
InferAddressSpacesPass (unsigned AddressSpace)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< InferAddressSpacesPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< InferAddressSpacesPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 16 of file InferAddressSpaces.h.
Constructor & Destructor Documentation
InferAddressSpacesPass() [1/2]
InferAddressSpacesPass::InferAddressSpacesPass ()
Definition at line 1312 of file InferAddressSpaces.cpp.
InferAddressSpacesPass() [2/2]
InferAddressSpacesPass::InferAddressSpacesPass (unsigned AddressSpace)
Definition at line 1314 of file InferAddressSpaces.cpp.
Member Function Documentation
run()
PreservedAnalyses InferAddressSpacesPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 1317 of file InferAddressSpaces.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserve(), and llvm::PreservedAnalyses::preserveSet().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Scalar/InferAddressSpaces.h
lib/Transforms/Scalar/InferAddressSpaces.cpp