LLVM: llvm::Win64EH::Instruction Struct Reference
llvm::Win64EH::Instruction Struct Reference
#include "llvm/MC/MCWin64EH.h"
Static Public Member Functions
static WinEH::Instruction PushNonVol (MCSymbol *L, unsigned Reg)
static WinEH::Instruction Alloc (MCSymbol *L, unsigned Size)
static WinEH::Instruction PushMachFrame (MCSymbol *L, bool Code)
static WinEH::Instruction SaveNonVol (MCSymbol *L, unsigned Reg, unsigned Offset)
static WinEH::Instruction SaveXMM (MCSymbol *L, unsigned Reg, unsigned Offset)
static WinEH::Instruction SetFPReg (MCSymbol *L, unsigned Reg, unsigned Off)
Detailed Description
Definition at line 25 of file MCWin64EH.h.
Member Function Documentation
Alloc()
static WinEH::Instruction llvm::Win64EH::Instruction::Alloc (MCSymbol * L, unsigned Size) inline static
Definition at line 29 of file MCWin64EH.h.
References Size, llvm::Win64EH::UOP_AllocLarge, and llvm::Win64EH::UOP_AllocSmall.
Referenced by llvm::MCStreamer::emitWinCFIAllocStack().
PushMachFrame()
static WinEH::Instruction llvm::Win64EH::Instruction::PushMachFrame (MCSymbol * L, bool Code) inline static
Definition at line 33 of file MCWin64EH.h.
References llvm::Win64EH::UOP_PushMachFrame.
Referenced by llvm::MCStreamer::emitWinCFIPushFrame().
PushNonVol()
static WinEH::Instruction llvm::Win64EH::Instruction::PushNonVol (MCSymbol * L, unsigned Reg) inline static
Definition at line 26 of file MCWin64EH.h.
References llvm::Win64EH::UOP_PushNonVol.
Referenced by llvm::MCStreamer::emitWinCFIPushReg().
SaveNonVol()
static WinEH::Instruction llvm::Win64EH::Instruction::SaveNonVol (MCSymbol * L, unsigned Reg, unsigned Offset) inline static
Definition at line 36 of file MCWin64EH.h.
References llvm::Offset, Reg, llvm::Win64EH::UOP_SaveNonVol, and llvm::Win64EH::UOP_SaveNonVolBig.
Referenced by llvm::MCStreamer::emitWinCFISaveReg().
SaveXMM()
static WinEH::Instruction llvm::Win64EH::Instruction::SaveXMM (MCSymbol * L, unsigned Reg, unsigned Offset) inline static
Definition at line 42 of file MCWin64EH.h.
References llvm::Offset, Reg, llvm::Win64EH::UOP_SaveXMM128, and llvm::Win64EH::UOP_SaveXMM128Big.
Referenced by llvm::MCStreamer::emitWinCFISaveXMM().
SetFPReg()
static WinEH::Instruction llvm::Win64EH::Instruction::SetFPReg (MCSymbol * L, unsigned Reg, unsigned Off) inline static
Definition at line 48 of file MCWin64EH.h.
References llvm::Win64EH::UOP_SetFPReg.
Referenced by llvm::MCStreamer::emitWinCFISetFrame().
The documentation for this struct was generated from the following file:
include/llvm/MC/MCWin64EH.h