LLVM: llvm::PatchLocation Struct Reference
llvm::PatchLocation Struct Reference
#include "llvm/DWARFLinker/DWARFLinkerCompileUnit.h"
Public Member Functions
PatchLocation ()=default
PatchLocation (DIE::value_iterator I)
PatchLocation (DIE::value_iterator I, int64_t Reloc)
void set (uint64_t New) const
uint64_t get () const
Public Attributes
DIE::value_iterator I
int64_t RelocAdjustment = 0
Detailed Description
Definition at line 34 of file DWARFLinkerCompileUnit.h.
Constructor & Destructor Documentation
PatchLocation() [1/3]
llvm::PatchLocation::PatchLocation () default
PatchLocation() [2/3]
llvm::PatchLocation::PatchLocation (DIE::value_iterator I) inline
Definition at line 39 of file DWARFLinkerCompileUnit.h.
PatchLocation() [3/3]
llvm::PatchLocation::PatchLocation (DIE::value_iterator I, int64_t Reloc) inline
Definition at line 40 of file DWARFLinkerCompileUnit.h.
Member Function Documentation
get()
uint64_t llvm::PatchLocation::get () const inline
Definition at line 50 of file DWARFLinkerCompileUnit.h.
References assert(), and I.
set()
void llvm::PatchLocation::set (uint64_t New) const inline
Definition at line 43 of file DWARFLinkerCompileUnit.h.
References assert(), and I.
Referenced by llvm::CompileUnit::fixupForwardReferences().
Member Data Documentation
I
DIE::value_iterator llvm::PatchLocation::I
Definition at line 35 of file DWARFLinkerCompileUnit.h.
Referenced by get(), and set().
RelocAdjustment
int64_t llvm::PatchLocation::RelocAdjustment = 0
Definition at line 36 of file DWARFLinkerCompileUnit.h.
The documentation for this struct was generated from the following file:
include/llvm/DWARFLinker/DWARFLinkerCompileUnit.h