LLVM: llvm::KnownFPClass Struct Reference
llvm::KnownFPClass Struct Reference
#include "llvm/Analysis/ValueTracking.h"
Public Member Functions
bool isKnownNever (FPClassTest Mask) const
Return true if it's known this can never be one of the mask entries.
bool isUnknown () const
bool isKnownNeverNaN () const
Return true if it's known this can never be a nan.
bool isKnownNeverInfinity () const
Return true if it's known this can never be an infinity.
bool isKnownNeverPosInfinity () const
Return true if it's known this can never be +infinity.
bool isKnownNeverNegInfinity () const
Return true if it's known this can never be -infinity.
bool isKnownNeverSubnormal () const
Return true if it's known this can never be a subnormal.
bool isKnownNeverPosSubnormal () const
Return true if it's known this can never be a positive subnormal.
bool isKnownNeverNegSubnormal () const
Return true if it's known this can never be a negative subnormal.
bool isKnownNeverZero () const
Return true if it's known this can never be a zero.
bool isKnownNeverPosZero () const
Return true if it's known this can never be a literal positive zero.
bool isKnownNeverNegZero () const
Return true if it's known this can never be a negative zero.
bool isKnownNeverLogicalZero (const Function &F, Type *Ty) const
Return true if it's know this can never be interpreted as a zero.
bool isKnownNeverLogicalNegZero (const Function &F, Type *Ty) const
Return true if it's know this can never be interpreted as a negative zero.
bool isKnownNeverLogicalPosZero (const Function &F, Type *Ty) const
Return true if it's know this can never be interpreted as a positive zero.
bool cannotBeOrderedLessThanZero () const
Return true if we can prove that the analyzed floating-point value is either NaN or never less than -0.0.
bool cannotBeOrderedGreaterThanZero () const
Return true if we can prove that the analyzed floating-point value is either NaN or never greater than -0.0.
KnownFPClass & operator|= (const KnownFPClass &RHS)
void knownNot (FPClassTest RuleOut)
void fneg ()
void fabs ()
bool signBitIsZeroOrNaN () const
Return true if the sign bit must be 0, ignoring the sign of nans.
void signBitMustBeZero ()
Assume the sign bit is zero.
void copysign (const KnownFPClass &Sign)
void propagateNaN (const KnownFPClass &Src, bool PreserveSign=false)
void propagateDenormal (const KnownFPClass &Src, const Function &F, Type *Ty)
Propagate knowledge from a source value that could be a denormal or zero.
void propagateCanonicalizingSrc (const KnownFPClass &Src, const Function &F, Type *Ty)
Report known classes if Src is evaluated through a potentially canonicalizing operation.
void resetAll ()
Public Attributes
FPClassTest KnownFPClasses = fcAllFlags
Floating-point classes the value could be one of.
std::optional< bool > SignBit
std::nullopt if the sign bit is unknown, true if the sign bit is definitely set or false if the sign bit is definitely unset.
Static Public Attributes
static constexpr FPClassTest OrderedLessThanZeroMask
static constexpr FPClassTest OrderedGreaterThanZeroMask
Detailed Description
Definition at line 233 of file ValueTracking.h.
Member Function Documentation
cannotBeOrderedGreaterThanZero()
bool llvm::KnownFPClass::cannotBeOrderedGreaterThanZero () const inline
Return true if we can prove that the analyzed floating-point value is either NaN or never greater than -0.0.
NaN --> true +0 --> true -0 --> true x > +0 --> false x < -0 --> true
Definition at line 337 of file ValueTracking.h.
References isKnownNever(), and OrderedGreaterThanZeroMask.
cannotBeOrderedLessThanZero()
bool llvm::KnownFPClass::cannotBeOrderedLessThanZero () const inline
Return true if we can prove that the analyzed floating-point value is either NaN or never less than -0.0.
 NaN --> true
  +0 --> true
  -0 --> true
x > +0 --> true x < -0 --> false
Definition at line 326 of file ValueTracking.h.
References isKnownNever(), and OrderedLessThanZeroMask.
Referenced by llvm::cannotBeOrderedLessThanZero(), and simplifyFCmpInst().
copysign()
void llvm::KnownFPClass::copysign (const KnownFPClass & Sign) inline
Definition at line 386 of file ValueTracking.h.
References llvm::fcInf, llvm::fcNan, llvm::fcNegative, llvm::fcNormal, llvm::fcPositive, llvm::fcSubnormal, llvm::fcZero, KnownFPClasses, and SignBit.
Referenced by computeKnownFPClass().
fabs()
void llvm::KnownFPClass::fabs () inline
Definition at line 359 of file ValueTracking.h.
References llvm::fcNegInf, llvm::fcNegNormal, llvm::fcNegSubnormal, llvm::fcNegZero, llvm::fcPosInf, llvm::fcPosNormal, llvm::fcPosSubnormal, llvm::fcPosZero, KnownFPClasses, and signBitMustBeZero().
Referenced by computeKnownFPClass().
fneg()
void llvm::KnownFPClass::fneg () inline
Definition at line 353 of file ValueTracking.h.
References llvm::fneg(), KnownFPClasses, and SignBit.
Referenced by computeKnownFPClass().
isKnownNever()
bool llvm::KnownFPClass::isKnownNever (FPClassTest Mask) const inline
Return true if it's known this can never be one of the mask entries.
Definition at line 242 of file ValueTracking.h.
References llvm::fcNone, and KnownFPClasses.
Referenced by cannotBeOrderedGreaterThanZero(), cannotBeOrderedLessThanZero(), isKnownNeverInfinity(), isKnownNeverNaN(), isKnownNeverNegInfinity(), isKnownNeverNegSubnormal(), isKnownNeverNegZero(), isKnownNeverPosInfinity(), isKnownNeverPosSubnormal(), isKnownNeverPosZero(), isKnownNeverSubnormal(), isKnownNeverZero(), and signBitIsZeroOrNaN().
isKnownNeverInfinity()
bool llvm::KnownFPClass::isKnownNeverInfinity () const inline
Return true if it's known this can never be an infinity.
Definition at line 256 of file ValueTracking.h.
References llvm::fcInf, and isKnownNever().
Referenced by llvm::isKnownNeverInfinity(), and llvm::isKnownNeverInfOrNaN().
isKnownNeverLogicalNegZero()
bool KnownFPClass::isKnownNeverLogicalNegZero (const Function & F, Type * Ty) const
Return true if it's know this can never be interpreted as a negative zero.
Definition at line 3871 of file ValueTracking.cpp.
References F, inputDenormalIsIEEEOrPosZero(), isKnownNeverNegSubnormal(), and isKnownNeverNegZero().
isKnownNeverLogicalPosZero()
bool KnownFPClass::isKnownNeverLogicalPosZero (const Function & F, Type * Ty) const
Return true if it's know this can never be interpreted as a positive zero.
Definition at line 3877 of file ValueTracking.cpp.
References F, llvm::DenormalMode::IEEE, isKnownNeverPosSubnormal(), isKnownNeverPosZero(), isKnownNeverSubnormal(), llvm_unreachable, llvm::DenormalMode::PositiveZero, and llvm::DenormalMode::PreserveSign.
isKnownNeverLogicalZero()
bool KnownFPClass::isKnownNeverLogicalZero (const Function & F, Type * Ty) const
Return true if it's know this can never be interpreted as a zero.
This extends isKnownNeverZero to cover the case where the assumed floating-point mode for the function interprets denormals as zero.
Definition at line 3866 of file ValueTracking.cpp.
References F, inputDenormalIsIEEE(), isKnownNeverSubnormal(), and isKnownNeverZero().
isKnownNeverNaN()
bool llvm::KnownFPClass::isKnownNeverNaN () const inline
Return true if it's known this can never be a nan.
Definition at line 251 of file ValueTracking.h.
References llvm::fcNan, and isKnownNever().
Referenced by computeKnownFPClass(), llvm::isKnownNeverInfOrNaN(), llvm::isKnownNeverNaN(), and simplifyFCmpInst().
isKnownNeverNegInfinity()
bool llvm::KnownFPClass::isKnownNeverNegInfinity () const inline
Return true if it's known this can never be -infinity.
Definition at line 266 of file ValueTracking.h.
References llvm::fcNegInf, and isKnownNever().
isKnownNeverNegSubnormal()
bool llvm::KnownFPClass::isKnownNeverNegSubnormal () const inline
Return true if it's known this can never be a negative subnormal.
Definition at line 281 of file ValueTracking.h.
References llvm::fcNegSubnormal, and isKnownNever().
Referenced by isKnownNeverLogicalNegZero().
isKnownNeverNegZero()
bool llvm::KnownFPClass::isKnownNeverNegZero () const inline
Return true if it's known this can never be a negative zero.
This means a literal -0 and does not include denormal inputs implicitly treated as -0.
Definition at line 298 of file ValueTracking.h.
References llvm::fcNegZero, and isKnownNever().
Referenced by llvm::cannotBeNegativeZero(), and isKnownNeverLogicalNegZero().
isKnownNeverPosInfinity()
bool llvm::KnownFPClass::isKnownNeverPosInfinity () const inline
Return true if it's known this can never be +infinity.
Definition at line 261 of file ValueTracking.h.
References llvm::fcPosInf, and isKnownNever().
isKnownNeverPosSubnormal()
bool llvm::KnownFPClass::isKnownNeverPosSubnormal () const inline
Return true if it's known this can never be a positive subnormal.
Definition at line 276 of file ValueTracking.h.
References llvm::fcPosSubnormal, and isKnownNever().
Referenced by isKnownNeverLogicalPosZero().
isKnownNeverPosZero()
bool llvm::KnownFPClass::isKnownNeverPosZero () const inline
Return true if it's known this can never be a literal positive zero.
Definition at line 292 of file ValueTracking.h.
References llvm::fcPosZero, and isKnownNever().
Referenced by isKnownNeverLogicalPosZero().
isKnownNeverSubnormal()
bool llvm::KnownFPClass::isKnownNeverSubnormal () const inline
Return true if it's known this can never be a subnormal.
Definition at line 271 of file ValueTracking.h.
References llvm::fcSubnormal, and isKnownNever().
Referenced by computeKnownFPClass(), isKnownNeverLogicalPosZero(), and isKnownNeverLogicalZero().
isKnownNeverZero()
bool llvm::KnownFPClass::isKnownNeverZero () const inline
Return true if it's known this can never be a zero.
This means a literal [+-]0, and does not include denormal inputs implicitly treated as [+-]0.
Definition at line 287 of file ValueTracking.h.
References llvm::fcZero, and isKnownNever().
Referenced by isKnownNeverLogicalZero().
isUnknown()
bool llvm::KnownFPClass::isUnknown () const inline
Definition at line 246 of file ValueTracking.h.
References llvm::fcAllFlags, KnownFPClasses, and SignBit.
Referenced by computeKnownFPClass().
knownNot()
void llvm::KnownFPClass::knownNot (FPClassTest RuleOut) inline
Definition at line 349 of file ValueTracking.h.
References KnownFPClasses.
Referenced by computeKnownFPClass(), computeKnownFPClassForFPTrunc(), and propagateNaN().
operator|=()
KnownFPClass & llvm::KnownFPClass::operator|= (const KnownFPClass & RHS) inline
Definition at line 341 of file ValueTracking.h.
References KnownFPClasses, and SignBit.
propagateCanonicalizingSrc()
void KnownFPClass::propagateCanonicalizingSrc (const KnownFPClass & Src, const Function & F, Type * Ty)
Report known classes if Src is evaluated through a potentially canonicalizing operation.
We can assume signaling nans will not be introduced, but cannot assume a denormal will be flushed under FTZ/DAZ.
This assumes a copy-like operation and will replace any currently known information.
Definition at line 3931 of file ValueTracking.cpp.
References F, propagateDenormal(), and propagateNaN().
Referenced by computeKnownFPClass().
propagateDenormal()
void KnownFPClass::propagateDenormal (const KnownFPClass & Src, const Function & F, Type * Ty)
Propagate knowledge from a source value that could be a denormal or zero.
We have to be conservative since output flushing is not guaranteed, so known-never-zero may not hold.
This assumes a copy-like operation and will replace any currently known information.
Definition at line 3902 of file ValueTracking.cpp.
References llvm::DenormalMode::Dynamic, F, llvm::fcNegZero, llvm::fcPosZero, llvm::DenormalMode::getIEEE(), llvm::DenormalMode::getPositiveZero(), KnownFPClasses, and llvm::DenormalMode::PositiveZero.
Referenced by propagateCanonicalizingSrc().
propagateNaN()
void llvm::KnownFPClass::propagateNaN (const KnownFPClass & Src, bool PreserveSign = false) inline
Definition at line 411 of file ValueTracking.h.
References llvm::fcNan, llvm::fcSNan, knownNot(), and SignBit.
Referenced by computeKnownFPClass(), computeKnownFPClassForFPTrunc(), and propagateCanonicalizingSrc().
resetAll()
void llvm::KnownFPClass::resetAll () inline
Definition at line 437 of file ValueTracking.h.
Referenced by computeKnownFPClass().
signBitIsZeroOrNaN()
bool llvm::KnownFPClass::signBitIsZeroOrNaN () const inline
Return true if the sign bit must be 0, ignoring the sign of nans.
Definition at line 376 of file ValueTracking.h.
References llvm::fcNegative, and isKnownNever().
signBitMustBeZero()
void llvm::KnownFPClass::signBitMustBeZero () inline
Assume the sign bit is zero.
Definition at line 381 of file ValueTracking.h.
References llvm::fcNan, llvm::fcPositive, KnownFPClasses, and SignBit.
Referenced by computeKnownFPClass(), and fabs().
Member Data Documentation
KnownFPClasses
FPClassTest llvm::KnownFPClass::KnownFPClasses = fcAllFlags
Floating-point classes the value could be one of.
Definition at line 235 of file ValueTracking.h.
Referenced by computeKnownFPClass(), copysign(), fabs(), fneg(), isKnownNever(), isUnknown(), knownNot(), operator|=(), propagateDenormal(), and signBitMustBeZero().
OrderedGreaterThanZeroMask
constexpr FPClassTest llvm::KnownFPClass::OrderedGreaterThanZeroMask static constexpr
Initial value:
=
      fcPosSubnormal | fcPosNormal | fcPosInf
Definition at line 315 of file ValueTracking.h.
Referenced by cannotBeOrderedGreaterThanZero(), and computeKnownFPClass().
OrderedLessThanZeroMask
constexpr FPClassTest llvm::KnownFPClass::OrderedLessThanZeroMask static constexpr
Initial value:
=
      fcNegSubnormal | fcNegNormal | fcNegInf
Definition at line 313 of file ValueTracking.h.
Referenced by cannotBeOrderedLessThanZero(), llvm::cannotBeOrderedLessThanZero(), computeKnownFPClass(), and computeKnownFPClassForFPTrunc().
SignBit
std::optional<bool> llvm::KnownFPClass::SignBit
std::nullopt if the sign bit is unknown, true if the sign bit is definitely set or false if the sign bit is definitely unset.
Definition at line 239 of file ValueTracking.h.
Referenced by computeKnownFPClass(), copysign(), fneg(), isUnknown(), operator|=(), propagateNaN(), and signBitMustBeZero().
The documentation for this struct was generated from the following files:
include/llvm/Analysis/ValueTracking.h
lib/Analysis/ValueTracking.cpp