LLVM: llvm::SetState< BaseTy > Struct Template Reference
llvm::SetState< BaseTy > Struct Template Reference
Simple state for a set.
#include "llvm/Transforms/IPO/Attributor.h"
Classes
struct SetContents
A wrapper around a set that has semantics for handling unions and intersections with a "universal" set that contains all elements.
Public Member Functions
SetState ()
SetState (const DenseSet< BaseTy > &Known)
Initializes the known state with an initial set and initializes the assumed state as universal.
bool isValidState () const override
See AbstractState::isValidState()
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint()
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
const SetContents & getKnown () const
Return the known state encoding.
const SetContents & getAssumed () const
Return the assumed state encoding.
bool setContains (const BaseTy &Elem) const
Returns if the set state contains the element.
bool getIntersection (const SetContents &RHS)
Performs the set intersection between this set and RHS.
bool getUnion (const SetContents &RHS)
Performs the set union between this set and RHS.
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
Detailed Description
template<typename BaseTy>
struct llvm::SetState< BaseTy >
Simple state for a set.
This represents a state containing a set of values. The interface supports modelling sets that contain all possible elements. The state's internal value is modified using union or intersection operations.
Definition at line 2980 of file Attributor.h.
Constructor & Destructor Documentation
SetState() [1/2]
template<typename BaseTy > llvm::SetState< BaseTy >::SetState () inline
Definition at line 3042 of file Attributor.h.
SetState() [2/2]
template<typename BaseTy > llvm::SetState< BaseTy >::SetState (const DenseSet< BaseTy > & Known) inline
Initializes the known state with an initial set and initializes the assumed state as universal.
Definition at line 3046 of file Attributor.h.
Member Function Documentation
getAssumed()
template<typename BaseTy > const SetContents & llvm::SetState< BaseTy >::getAssumed () const inline
Return the assumed state encoding.
Definition at line 3073 of file Attributor.h.
getIntersection()
template<typename BaseTy > bool llvm::SetState< BaseTy >::getIntersection (const SetContents & RHS) inline
Performs the set intersection between this set and RHS.
Returns true if changes were made.
Definition at line 3082 of file Attributor.h.
References llvm::SetState< BaseTy >::SetContents::getIntersection(), llvm::SetState< BaseTy >::SetContents::getSet(), llvm::SetState< BaseTy >::SetContents::getUnion(), llvm::SetState< BaseTy >::SetContents::isUniversal(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::size().
getKnown()
template<typename BaseTy > const SetContents & llvm::SetState< BaseTy >::getKnown () const inline
Return the known state encoding.
Definition at line 3070 of file Attributor.h.
getUnion()
template<typename BaseTy > bool llvm::SetState< BaseTy >::getUnion (const SetContents & RHS) inline
Performs the set union between this set and RHS.
Returns true if changes were made.
Definition at line 3097 of file Attributor.h.
References llvm::SetState< BaseTy >::SetContents::getUnion().
indicateOptimisticFixpoint()
template<typename BaseTy > ChangeStatus llvm::SetState< BaseTy >::indicateOptimisticFixpoint () inline override virtual
See AbstractState::indicateOptimisticFixpoint(...)
Implements llvm::AbstractState.
Definition at line 3056 of file Attributor.h.
References llvm::UNCHANGED.
indicatePessimisticFixpoint()
template<typename BaseTy > ChangeStatus llvm::SetState< BaseTy >::indicatePessimisticFixpoint () inline override virtual
See AbstractState::indicatePessimisticFixpoint(...)
Implements llvm::AbstractState.
Definition at line 3063 of file Attributor.h.
References llvm::CHANGED.
isAtFixpoint()
template<typename BaseTy > bool llvm::SetState< BaseTy >::isAtFixpoint () const inline override virtual
See AbstractState::isAtFixpoint()
Implements llvm::AbstractState.
Definition at line 3053 of file Attributor.h.
isValidState()
template<typename BaseTy > bool llvm::SetState< BaseTy >::isValidState () const inline override virtual
See AbstractState::isValidState()
Implements llvm::AbstractState.
Definition at line 3050 of file Attributor.h.
References llvm::SetState< BaseTy >::SetContents::empty().
setContains()
template<typename BaseTy > bool llvm::SetState< BaseTy >::setContains (const BaseTy & Elem) const inline
Returns if the set state contains the element.
Definition at line 3076 of file Attributor.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::contains(), and llvm::SetState< BaseTy >::SetContents::getSet().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h