LLVM: llvm::DOTGraphTraits< ScheduleDAGMI * > Struct Reference
llvm::DOTGraphTraits< ScheduleDAGMI * > Struct Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType >
std::string getNodeLabel (const void *, const GraphType &)
getNodeLabel - Given a node and a pointer to the top level graph, return the label to print in the node.
Static Public Member Functions
static std::string getGraphName (const ScheduleDAG *G)
static bool renderGraphFromBottomUp ()
static bool isNodeHidden (const SUnit *Node, const ScheduleDAG *G)
static std::string getEdgeAttributes (const SUnit *Node, SUnitIterator EI, const ScheduleDAG *Graph)
If you want to override the dot attributes printed for a particular edge, override this method.
static std::string getNodeLabel (const SUnit *SU, const ScheduleDAG *G)
static std::string getNodeDescription (const SUnit *SU, const ScheduleDAG *G)
static std::string getNodeAttributes (const SUnit *N, const ScheduleDAG *G)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType >
static std::string getGraphName (const GraphType &)
getGraphName - Return the label for the graph as a whole.
template<typename GraphType >
static std::string getGraphProperties (const GraphType &)
getGraphProperties - Return any custom properties that should be included in the top level graph structure for dot.
static bool renderGraphFromBottomUp ()
renderGraphFromBottomUp - If this function returns true, the graph is emitted bottom-up instead of top-down.
template<typename GraphType >
static bool isNodeHidden (const void *, const GraphType &)
isNodeHidden - If the function returns true, the given node is not displayed in the graph.
static bool renderNodesUsingHTML ()
template<typename GraphType >
static std::string getNodeIdentifierLabel (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeAttributes (const void *, const GraphType &)
If you want to specify custom node attributes, this is the place to do so.
template<typename EdgeIter , typename GraphType >
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
If you want to override the dot attributes printed for a particular edge, override this method.
template<typename EdgeIter >
static std::string getEdgeSourceLabel (const void *, EdgeIter)
getEdgeSourceLabel - If you want to label the edge source itself, implement this method.
template<typename EdgeIter >
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
edgeTargetsEdgeSource - This method returns true if this outgoing edge should actually target another edge source, not a node.
template<typename EdgeIter >
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
getEdgeTarget - If edgeTargetsEdgeSource returns true, this method is called to determine which outgoing edge of Node is the target of this edge.
static bool hasEdgeDestLabels ()
hasEdgeDestLabels - If this function returns true, the graph is able to provide labels for edge destinations.
static unsigned numEdgeDestLabels (const void *)
numEdgeDestLabels - If hasEdgeDestLabels, this function returns the number of incoming edge labels the given node has.
static std::string getEdgeDestLabel (const void *, unsigned)
getEdgeDestLabel - If hasEdgeDestLabels, this function returns the incoming edge label with the given index in the given node.
template<typename GraphType , typename GraphWriter >
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
addCustomGraphFeatures - If a graph is made up of more than just straight-forward nodes and edges, this is the place to put all of the custom stuff necessary.
Additional Inherited Members
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
Definition at line 4157 of file MachineScheduler.cpp.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< ScheduleDAGMI * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 4158 of file MachineScheduler.cpp.
Member Function Documentation
getEdgeAttributes()
static std::string llvm::DOTGraphTraits< ScheduleDAGMI * >::getEdgeAttributes (const SUnit * Node, SUnitIterator EI, const ScheduleDAG * Graph) inline static
If you want to override the dot attributes printed for a particular edge, override this method.
Definition at line 4177 of file MachineScheduler.cpp.
References llvm::SUnitIterator::isArtificialDep(), and llvm::SUnitIterator::isCtrlDep().
getGraphName()
static std::string llvm::DOTGraphTraits< ScheduleDAGMI * >::getGraphName (const ScheduleDAG * G) inline static
Definition at line 4160 of file MachineScheduler.cpp.
References G.
getNodeAttributes()
static std::string llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeAttributes (const SUnit * N, const ScheduleDAG * G) inline static
Definition at line 4203 of file MachineScheduler.cpp.
References G, llvm::DOT::getColorString(), llvm::SchedDFSResult::getSubtreeID(), llvm::ScheduleDAGMI::hasVRegLiveness(), and N.
getNodeDescription()
static std::string llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeDescription (const SUnit * SU, const ScheduleDAG * G) inline static
Definition at line 4199 of file MachineScheduler.cpp.
References G.
getNodeLabel()
static std::string llvm::DOTGraphTraits< ScheduleDAGMI * >::getNodeLabel (const SUnit * SU, const ScheduleDAG * G) inline static
Definition at line 4187 of file MachineScheduler.cpp.
References G, llvm::SchedDFSResult::getNumInstrs(), llvm::ScheduleDAGMI::hasVRegLiveness(), and llvm::SUnit::NodeNum.
isNodeHidden()
static bool llvm::DOTGraphTraits< ScheduleDAGMI * >::isNodeHidden (const SUnit * Node, const ScheduleDAG * G) inline static
Definition at line 4168 of file MachineScheduler.cpp.
References ViewMISchedCutoff.
renderGraphFromBottomUp()
static bool llvm::DOTGraphTraits< ScheduleDAGMI * >::renderGraphFromBottomUp () inline static
Definition at line 4164 of file MachineScheduler.cpp.
The documentation for this struct was generated from the following file:
lib/CodeGen/MachineScheduler.cpp