LLVM: llvm::AAMemoryLocation Struct Reference
llvm::AAMemoryLocation Struct Reference abstract
An abstract interface for all memory location attributes (readnone/argmemonly/inaccessiblememonly/inaccessibleorargmemonly).
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
enum {
ALL_LOCATIONS = 0 , NO_LOCAL_MEM = 1 << 0 , NO_CONST_MEM = 1 << 1 , NO_GLOBAL_INTERNAL_MEM = 1 << 2 ,
NO_GLOBAL_EXTERNAL_MEM = 1 << 3 , NO_GLOBAL_MEM = NO_GLOBAL_INTERNAL_MEM | NO_GLOBAL_EXTERNAL_MEM , NO_ARGUMENT_MEM = 1 << 4 , NO_INACCESSIBLE_MEM = 1 << 5 ,
NO_MALLOCED_MEM = 1 << 6 , NO_UNKOWN_MEM = 1 << 7 , NO_LOCATIONS , VALID_STATE = NO_LOCATIONS + 1 ,
BEST_STATE = NO_LOCATIONS | VALID_STATE
}
Encoding of different locations that could be accessed by a memory access.
enum AccessKind { NONE = 0 , READ = 1 << 0 , WRITE = 1 << 1 , READ_WRITE = READ | WRITE }
Simple enum to distinguish read/write/read-write accesses.
using MemoryLocationsKind = StateType::base_t
Public Types inherited from llvm::StateWrapper< BitIntegerState< uint32_t, 511 >, AbstractAttribute >
using StateType
Provide static access to the type of the state.
Public Types inherited from llvm::AbstractAttribute
using StateType = AbstractState
Public Types inherited from llvm::IRPosition
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
using CallBaseContext = CallBase
Public Types inherited from llvm::AADepGraphNode
using DepTy = PointerIntPair<AADepGraphNode *, 1>
using DepSetTy = SmallSetVector<DepTy, 2>
using iterator = mapped_iterator<DepSetTy::iterator, decltype(&DepGetVal)>
using aaiterator
Public Types inherited from llvm::BitIntegerState< uint32_t, 511 >
using super
using base_t
Public Types inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
using base_t = base_ty
Public Member Functions
AAMemoryLocation (const IRPosition &IRP, Attributor &A)
bool isKnownReadNone () const
Return true if we know that the associated functions has no observable accesses.
bool isAssumedReadNone () const
Return true if we assume that the associated functions has no observable accesses.
bool isKnowStackOnly () const
Return true if we know that the associated functions has at most local/stack accesses.
bool isAssumedStackOnly () const
Return true if we assume that the associated functions has at most local/stack accesses.
bool isKnownInaccessibleMemOnly () const
Return true if we know that the underlying value will only access inaccesible memory only (see Attribute::InaccessibleMemOnly).
bool isAssumedInaccessibleMemOnly () const
Return true if we assume that the underlying value will only access inaccesible memory only (see Attribute::InaccessibleMemOnly).
bool isKnownArgMemOnly () const
Return true if we know that the underlying value will only access argument pointees (see Attribute::ArgMemOnly).
bool isAssumedArgMemOnly () const
Return true if we assume that the underlying value will only access argument pointees (see Attribute::ArgMemOnly).
bool isKnownInaccessibleOrArgMemOnly () const
Return true if we know that the underlying value will only access inaccesible memory or argument pointees (see Attribute::InaccessibleOrArgMemOnly).
bool isAssumedInaccessibleOrArgMemOnly () const
Return true if we assume that the underlying value will only access inaccesible memory or argument pointees (see Attribute::InaccessibleOrArgMemOnly).
bool mayAccessArgMem () const
Return true if the underlying value may access memory through arguement pointers of the associated function, if any.
bool isAssumedSpecifiedMemOnly (MemoryLocationsKind MLK) const
Return true if only the memory locations specififed by MLK are assumed to be accessed by the associated function.
MemoryLocationsKind getAssumedNotAccessedLocation () const
Return the locations that are assumed to be not accessed by the associated function, if any.
virtual bool checkForAllAccessesToMemoryKind (function_ref< bool(const Instruction *, const Value *, AccessKind, MemoryLocationsKind)> Pred, MemoryLocationsKind MLK) const =0
Check Pred on all accesses to the memory kinds specified by MLK.
const std::string getAsStr (Attributor *A) const override
See AbstractState::getAsStr(Attributor).
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::IRAttribute< Attribute::ReadNone, StateWrapper< BitIntegerState< uint32_t, 511 >, AbstractAttribute >, AAMemoryLocation >
IRAttribute (const IRPosition &IRP)
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
Attribute::AttrKind getAttrKind () const
Return the kind that identifies the abstract attribute implementation.
virtual void getDeducedAttributes (Attributor &A, LLVMContext &Ctx, SmallVectorImpl< Attribute > &Attrs) const
Return the deduced attributes in Attrs.
Public Member Functions inherited from llvm::StateWrapper< BitIntegerState< uint32_t, 511 >, AbstractAttribute >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (const IRPosition &IRP)
virtual ~AbstractAttribute ()=default
Virtual destructor.
virtual void initialize (Attributor &A)
Initialize the state with the information in the Attributor A.
virtual bool isQueryAA () const
A query AA is always scheduled as long as we do updates because it does lazy computation that cannot be determined to be done from the outside.
const IRPosition & getIRPosition () const
Return an IR position, see struct IRPosition.
IRPosition & getIRPosition ()
void print (raw_ostream &OS) const
Helper functions, for debug purposes only.
void print (Attributor *, raw_ostream &OS) const override
virtual void printWithDeps (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::IRPosition
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
bool isFunctionScope () const
Return true if this is a function or call site position.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getCalleeArgNo () const
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
int getCallSiteArgNo () const
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Value * getAttrListAnchor () const
Return the value attributes are attached to.
AttributeList getAttrList () const
Return the attributes associated with this function or call site scope.
void setAttrList (const AttributeList &AttrList) const
Update the attributes associated with this function or call site scope.
unsigned getNumArgs () const
Return the number of arguments associated with this function or call site scope.
Value * getArg (unsigned ArgNo) const
Return theargument ArgNo associated with this function or call site scope.
Kind getPositionKind () const
Return the associated position kind.
bool isAnyCallSitePosition () const
bool isArgumentPosition () const
Return true if the position is an argument or call site argument.
IRPosition stripCallBaseContext () const
Return the same position without the call base context.
const CallBaseContext * getCallBaseContext () const
Get the call base context from the position.
bool hasCallBaseContext () const
Check if the position has any call base context.
operator void * () const
}
Public Member Functions inherited from llvm::AADepGraphNode
virtual ~AADepGraphNode ()=default
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
void print (raw_ostream &OS) const
DepSetTy & getDeps ()
Public Member Functions inherited from llvm::BitIntegerState< uint32_t, 511 >
BitIntegerState ()=default
BitIntegerState (base_t Assumed)
bool isKnown (base_t BitsEncoding=BestState) const
Return true if the bits set in BitsEncoding are "known bits".
bool isAssumed (base_t BitsEncoding=BestState) const
Return true if the bits set in BitsEncoding are "assumed bits".
BitIntegerState & addKnownBits (base_t Bits)
Add the bits in BitsEncoding to the "known bits".
BitIntegerState & removeAssumedBits (base_t BitsEncoding)
Remove the bits in BitsEncoding from the "assumed bits" if not known.
BitIntegerState & removeKnownBits (base_t BitsEncoding)
Remove the bits in BitsEncoding from the "known bits".
BitIntegerState & intersectAssumedBits (base_t BitsEncoding)
Keep only "assumed bits" also set in BitsEncoding but all known ones.
Public Member Functions inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
IntegerStateBase ()=default
IntegerStateBase (base_t Assumed)
bool isValidState () const override
See AbstractState::isValidState() NOTE: For now we simply pretend that the worst possible state is invalid.
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint()
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
base_t getKnown () const
Return the known state encoding.
base_t getAssumed () const
Return the assumed state encoding.
bool operator== (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Equality for IntegerStateBase.
bool operator!= (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Inequality for IntegerStateBase.
void operator^= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator+= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator|= (const IntegerStateBase< base_t, BestState, WorstState > &R)
void operator&= (const IntegerStateBase< base_t, BestState, WorstState > &R)
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
Static Public Member Functions
static bool hasTrivialInitializer ()
See AbstractAttribute::hasTrivialInitializer.
static bool isValidIRPositionForInit (Attributor &A, const IRPosition &IRP)
See AbstractAttribute::isValidIRPositionForInit.
static MemoryLocationsKind inverseLocation (MemoryLocationsKind Loc, bool AndLocalMem, bool AndConstMem)
Return the inverse of location Loc, thus for NO_XXX the return describes ONLY_XXX.
static std::string getMemoryLocationsAsStr (MemoryLocationsKind MLK)
Return the locations encoded by MLK as a readable string.
static AAMemoryLocation & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAMemoryLocation.
Static Public Member Functions inherited from llvm::IRAttribute< Attribute::ReadNone, StateWrapper< BitIntegerState< uint32_t, 511 >, AbstractAttribute >, AAMemoryLocation >
static bool hasTrivialInitializer ()
Most boolean IRAttribute AAs don't do anything non-trivial in their initializers while non-boolean ones often do.
static bool isImpliedByUndef ()
Return true if the IR attribute(s) associated with this AA are implied for an undef value.
static bool isImpliedByPoison ()
Return true if the IR attribute(s) associated with this AA are implied for an poison value.
static bool isImpliedByIR (Attributor &A, const IRPosition &IRP, Attribute::AttrKind ImpliedAttributeKind=AK, bool IgnoreSubsumingPositions=false)
Static Public Member Functions inherited from llvm::AbstractAttribute
static bool classof (const AADepGraphNode *DGN)
This function is used to identify if an DGN is of type AbstractAttribute so that the dyn_cast and cast can use such information to cast an AADepGraphNode to an AbstractAttribute.
static bool hasTrivialInitializer ()
Return false if this AA does anything non-trivial (hence not done by default) in its initializer.
static bool requiresCalleeForCallBase ()
Return true if this AA requires a "callee" (or an associted function) for a call site positon.
static bool requiresCallersForArgOrFunction ()
Return true if this AA requires all callees for an argument or function positon.
static bool isValidIRPositionForInit (Attributor &A, const IRPosition &IRP)
Return false if an AA should not be created for IRP.
static bool isValidIRPositionForUpdate (Attributor &A, const IRPosition &IRP)
Return false if an AA should not be updated for IRP.
Static Public Member Functions inherited from llvm::IRPosition
static const IRPosition value (const Value &V, const CallBaseContext *CBContext=nullptr)
Create a position describing the value of V.
static const IRPosition inst (const Instruction &I, const CallBaseContext *CBContext=nullptr)
Create a position describing the instruction I.
static const IRPosition function (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg, const CallBaseContext *CBContext=nullptr)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP, const CallBaseContext *CBContext=nullptr)
Create a position with function scope matching the "context" of IRP.
Static Public Member Functions inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
static constexpr base_t getBestState ()
Return the best possible representable state.
static constexpr base_t getBestState (const IntegerStateBase &)
static constexpr base_t getWorstState ()
Return the worst possible representable state.
static constexpr base_t getWorstState (const IntegerStateBase &)
Static Public Attributes
static const char ID = 0
Unique ID (due to the unique address)
Static Public Attributes inherited from llvm::IRAttribute< Attribute::ReadNone, StateWrapper< BitIntegerState< uint32_t, 511 >, AbstractAttribute >, AAMemoryLocation >
static constexpr Attribute::AttrKind IRAttributeKind
Compile time access to the IR attribute kind.
Static Public Attributes inherited from llvm::IRPosition
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Additional Inherited Members
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
virtual void trackStatistics () const =0
Hook to enable custom statistic tracking, called after manifest that resulted in a change if statistics are enabled.
virtual ChangeStatus updateImpl (Attributor &A)=0
The actual update/transfer function which has to be implemented by the derived classes.
Protected Member Functions inherited from llvm::AADepGraphNode
operator AbstractAttribute * ()
Protected Member Functions inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
virtual void handleNewAssumedValue (base_t Value)=0
Handle a new assumed value Value. Subtype dependent.
virtual void handleNewKnownValue (base_t Value)=0
Handle a new known value Value. Subtype dependent.
virtual void joinOR (base_t AssumedValue, base_t KnownValue)=0
Handle a value Value. Subtype dependent.
virtual void joinAND (base_t AssumedValue, base_t KnownValue)=0
Handle a new assumed value Value. Subtype dependent.
Static Protected Member Functions inherited from llvm::AADepGraphNode
static AADepGraphNode * DepGetVal (const DepTy &DT)
static AbstractAttribute * DepGetValAA (const DepTy &DT)
Protected Attributes inherited from llvm::AADepGraphNode
DepSetTy Deps
Set of dependency graph nodes which should be updated if this one is updated.
Protected Attributes inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
base_t Known = getWorstState()
The known state encoding in an integer of type base_t.
base_t Assumed = getBestState()
The assumed state encoding in an integer of type base_t.
Detailed Description
An abstract interface for all memory location attributes (readnone/argmemonly/inaccessiblememonly/inaccessibleorargmemonly).
Definition at line 4584 of file Attributor.h.
Member Typedef Documentation
MemoryLocationsKind
using llvm::AAMemoryLocation::MemoryLocationsKind = StateType::base_t
Definition at line 4589 of file Attributor.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Encoding of different locations that could be accessed by a memory access.
Enumerator
ALL_LOCATIONS
NO_LOCAL_MEM
NO_CONST_MEM
NO_GLOBAL_INTERNAL_MEM
NO_GLOBAL_EXTERNAL_MEM
NO_GLOBAL_MEM
NO_ARGUMENT_MEM
NO_INACCESSIBLE_MEM
NO_MALLOCED_MEM
NO_UNKOWN_MEM
NO_LOCATIONS
VALID_STATE
BEST_STATE
Definition at line 4606 of file Attributor.h.
AccessKind
enum llvm::AAMemoryLocation::AccessKind
Simple enum to distinguish read/write/read-write accesses.
Enumerator
NONE
READ
WRITE
READ_WRITE
Definition at line 4721 of file Attributor.h.
Constructor & Destructor Documentation
AAMemoryLocation()
llvm::AAMemoryLocation::AAMemoryLocation (const IRPosition & IRP, Attributor & A) inline
Definition at line 4591 of file Attributor.h.
Member Function Documentation
checkForAllAccessesToMemoryKind()
virtual bool llvm::AAMemoryLocation::checkForAllAccessesToMemoryKind (function_ref< bool(const Instruction *, const Value *, AccessKind, MemoryLocationsKind)> Pred, MemoryLocationsKind MLK) const pure virtual
Check Pred on all accesses to the memory kinds specified by MLK.
This method will evaluate Pred on all accesses (access instruction + underlying accessed memory pointer) and it will return true if Pred holds every time.
classof()
static bool llvm::AAMemoryLocation::classof (const AbstractAttribute * AA) inline static
This function should return true if the type of the AA is AAMemoryLocation.
Definition at line 4756 of file Attributor.h.
References llvm::AbstractAttribute::getIdAddr().
createForPosition()
static AAMemoryLocation & llvm::AAMemoryLocation::createForPosition (const IRPosition & IRP, Attributor & A) static
Create an abstract attribute view for the position IRP.
getAsStr()
const std::string llvm::AAMemoryLocation::getAsStr (Attributor * A) const inline override virtual
See AbstractState::getAsStr(Attributor).
Implements llvm::AbstractAttribute.
Definition at line 4744 of file Attributor.h.
References getAssumedNotAccessedLocation(), and getMemoryLocationsAsStr().
getAssumedNotAccessedLocation()
MemoryLocationsKind llvm::AAMemoryLocation::getAssumedNotAccessedLocation () const inline
Return the locations that are assumed to be not accessed by the associated function, if any.
Definition at line 4702 of file Attributor.h.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::getAssumed().
Referenced by getAsStr().
getIdAddr()
const char * llvm::AAMemoryLocation::getIdAddr () const inline override virtual
See AbstractAttribute::getIdAddr()
Implements llvm::AbstractAttribute.
Definition at line 4752 of file Attributor.h.
References ID.
getMemoryLocationsAsStr()
std::string AAMemoryLocation::getMemoryLocationsAsStr (AAMemoryLocation::MemoryLocationsKind MLK) static
Return the locations encoded by MLK as a readable string.
-----------------— Memory Locations Attributes ------------------------— Includes read-none, argmemonly, inaccessiblememonly,
inaccessiblememorargmemonly
Definition at line 8259 of file AttributorAttributes.cpp.
References NO_ARGUMENT_MEM, NO_CONST_MEM, NO_GLOBAL_EXTERNAL_MEM, NO_GLOBAL_INTERNAL_MEM, NO_INACCESSIBLE_MEM, NO_LOCAL_MEM, NO_LOCATIONS, NO_MALLOCED_MEM, and NO_UNKOWN_MEM.
Referenced by getAsStr().
getName()
const std::string llvm::AAMemoryLocation::getName () const inline override virtual
See AbstractAttribute::getName()
Implements llvm::AbstractAttribute.
Definition at line 4749 of file Attributor.h.
hasTrivialInitializer()
static bool llvm::AAMemoryLocation::hasTrivialInitializer () inline static
See AbstractAttribute::hasTrivialInitializer.
Definition at line 4594 of file Attributor.h.
inverseLocation()
static MemoryLocationsKind llvm::AAMemoryLocation::inverseLocation (MemoryLocationsKind Loc, bool AndLocalMem, bool AndConstMem) inline static
Return the inverse of location Loc, thus for NO_XXX the return describes ONLY_XXX.
The flags AndLocalMem and AndConstMem determine if local (=stack) and constant memory are allowed as well. Most of the time we do want them to be included, e.g., argmemonly allows accesses via argument pointers or local or constant memory accesses.
Definition at line 4712 of file Attributor.h.
References NO_CONST_MEM, NO_LOCAL_MEM, and NO_LOCATIONS.
Referenced by isAssumedArgMemOnly(), isAssumedInaccessibleMemOnly(), isAssumedInaccessibleOrArgMemOnly(), isAssumedStackOnly(), isKnownArgMemOnly(), isKnownInaccessibleMemOnly(), isKnownInaccessibleOrArgMemOnly(), and isKnowStackOnly().
isAssumedArgMemOnly()
bool llvm::AAMemoryLocation::isAssumedArgMemOnly () const inline
Return true if we assume that the underlying value will only access argument pointees (see Attribute::ArgMemOnly).
Definition at line 4670 of file Attributor.h.
References inverseLocation(), llvm::BitIntegerState< uint32_t, 511 >::isAssumed(), and NO_ARGUMENT_MEM.
isAssumedInaccessibleMemOnly()
bool llvm::AAMemoryLocation::isAssumedInaccessibleMemOnly () const inline
Return true if we assume that the underlying value will only access inaccesible memory only (see Attribute::InaccessibleMemOnly).
Definition at line 4658 of file Attributor.h.
References inverseLocation(), llvm::BitIntegerState< uint32_t, 511 >::isAssumed(), and NO_INACCESSIBLE_MEM.
isAssumedInaccessibleOrArgMemOnly()
bool llvm::AAMemoryLocation::isAssumedInaccessibleOrArgMemOnly () const inline
Return true if we assume that the underlying value will only access inaccesible memory or argument pointees (see Attribute::InaccessibleOrArgMemOnly).
Definition at line 4685 of file Attributor.h.
References inverseLocation(), llvm::BitIntegerState< uint32_t, 511 >::isAssumed(), NO_ARGUMENT_MEM, and NO_INACCESSIBLE_MEM.
isAssumedReadNone()
bool llvm::AAMemoryLocation::isAssumedReadNone () const inline
Return true if we assume that the associated functions has no observable accesses.
Definition at line 4634 of file Attributor.h.
References llvm::BitIntegerState< uint32_t, 511 >::isAssumed(), isAssumedStackOnly(), and NO_LOCATIONS.
isAssumedSpecifiedMemOnly()
bool llvm::AAMemoryLocation::isAssumedSpecifiedMemOnly (MemoryLocationsKind MLK) const inline
Return true if only the memory locations specififed by MLK are assumed to be accessed by the associated function.
Definition at line 4696 of file Attributor.h.
References llvm::BitIntegerState< uint32_t, 511 >::isAssumed().
isAssumedStackOnly()
bool llvm::AAMemoryLocation::isAssumedStackOnly () const inline
Return true if we assume that the associated functions has at most local/stack accesses.
Definition at line 4646 of file Attributor.h.
References inverseLocation(), llvm::BitIntegerState< uint32_t, 511 >::isAssumed(), and NO_LOCAL_MEM.
Referenced by isAssumedReadNone().
isKnownArgMemOnly()
bool llvm::AAMemoryLocation::isKnownArgMemOnly () const inline
Return true if we know that the underlying value will only access argument pointees (see Attribute::ArgMemOnly).
Definition at line 4664 of file Attributor.h.
References inverseLocation(), llvm::BitIntegerState< uint32_t, 511 >::isKnown(), and NO_ARGUMENT_MEM.
isKnownInaccessibleMemOnly()
bool llvm::AAMemoryLocation::isKnownInaccessibleMemOnly () const inline
Return true if we know that the underlying value will only access inaccesible memory only (see Attribute::InaccessibleMemOnly).
Definition at line 4652 of file Attributor.h.
References inverseLocation(), llvm::BitIntegerState< uint32_t, 511 >::isKnown(), and NO_INACCESSIBLE_MEM.
isKnownInaccessibleOrArgMemOnly()
bool llvm::AAMemoryLocation::isKnownInaccessibleOrArgMemOnly () const inline
Return true if we know that the underlying value will only access inaccesible memory or argument pointees (see Attribute::InaccessibleOrArgMemOnly).
Definition at line 4677 of file Attributor.h.
References inverseLocation(), llvm::BitIntegerState< uint32_t, 511 >::isKnown(), NO_ARGUMENT_MEM, and NO_INACCESSIBLE_MEM.
isKnownReadNone()
bool llvm::AAMemoryLocation::isKnownReadNone () const inline
Return true if we know that the associated functions has no observable accesses.
Definition at line 4630 of file Attributor.h.
References llvm::BitIntegerState< uint32_t, 511 >::isKnown(), and NO_LOCATIONS.
isKnowStackOnly()
bool llvm::AAMemoryLocation::isKnowStackOnly () const inline
Return true if we know that the associated functions has at most local/stack accesses.
Definition at line 4640 of file Attributor.h.
References inverseLocation(), llvm::BitIntegerState< uint32_t, 511 >::isKnown(), and NO_LOCAL_MEM.
isValidIRPositionForInit()
static bool llvm::AAMemoryLocation::isValidIRPositionForInit (Attributor & A, const IRPosition & IRP) inline static
See AbstractAttribute::isValidIRPositionForInit.
Definition at line 4597 of file Attributor.h.
References A.
mayAccessArgMem()
bool llvm::AAMemoryLocation::mayAccessArgMem () const inline
Return true if the underlying value may access memory through arguement pointers of the associated function, if any.
Definition at line 4692 of file Attributor.h.
References llvm::BitIntegerState< uint32_t, 511 >::isAssumed(), and NO_ARGUMENT_MEM.
Member Data Documentation
ID
const char AAMemoryLocation::ID = 0 static
Unique ID (due to the unique address)
Definition at line 4761 of file Attributor.h.
Referenced by getIdAddr().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/AttributorAttributes.cpp