LLVM: llvm::AMDGPU::Waitcnt Struct Reference
llvm::AMDGPU::Waitcnt Struct Reference
Represents the counter values to wait for in an s_waitcnt instruction.
#include "Target/AMDGPU/Utils/AMDGPUBaseInfo.h"
Public Member Functions
Waitcnt ()=default
Waitcnt (unsigned VmCnt, unsigned ExpCnt, unsigned LgkmCnt, unsigned VsCnt)
bool hasWait () const
bool hasWaitExceptVsCnt () const
bool hasWaitVsCnt () const
Waitcnt combined (const Waitcnt &Other) const
Static Public Member Functions
static Waitcnt allZero (bool HasVscnt)
static Waitcnt allZeroExceptVsCnt ()
Public Attributes
unsigned VmCnt = ~0u
unsigned ExpCnt = ~0u
unsigned LgkmCnt = ~0u
unsigned VsCnt = ~0u
Detailed Description
Represents the counter values to wait for in an s_waitcnt instruction.
Large values (including the maximum possible integer) can be used to represent "don't care" waits.
Definition at line 840 of file AMDGPUBaseInfo.h.
Constructor & Destructor Documentation
Waitcnt() [1/2]
llvm::AMDGPU::Waitcnt::Waitcnt () default
Referenced by allZero(), allZeroExceptVsCnt(), and combined().
Waitcnt() [2/2]
llvm::AMDGPU::Waitcnt::Waitcnt (unsigned VmCnt, unsigned ExpCnt, unsigned LgkmCnt, unsigned VsCnt) inline
Definition at line 847 of file AMDGPUBaseInfo.h.
Member Function Documentation
allZero()
static Waitcnt llvm::AMDGPU::Waitcnt::allZero (bool HasVscnt) inline static
Definition at line 850 of file AMDGPUBaseInfo.h.
References Waitcnt().
allZeroExceptVsCnt()
static Waitcnt llvm::AMDGPU::Waitcnt::allZeroExceptVsCnt () inline static
Definition at line 853 of file AMDGPUBaseInfo.h.
References Waitcnt().
combined()
Waitcnt llvm::AMDGPU::Waitcnt::combined (const Waitcnt & Other) const inline
Definition at line 867 of file AMDGPUBaseInfo.h.
References ExpCnt, LgkmCnt, llvm::Other, VmCnt, VsCnt, and Waitcnt().
hasWait()
bool llvm::AMDGPU::Waitcnt::hasWait () const inline
Definition at line 855 of file AMDGPUBaseInfo.h.
References ExpCnt, LgkmCnt, VmCnt, and VsCnt.
hasWaitExceptVsCnt()
bool llvm::AMDGPU::Waitcnt::hasWaitExceptVsCnt () const inline
Definition at line 859 of file AMDGPUBaseInfo.h.
References ExpCnt, LgkmCnt, and VmCnt.
hasWaitVsCnt()
bool llvm::AMDGPU::Waitcnt::hasWaitVsCnt () const inline
Definition at line 863 of file AMDGPUBaseInfo.h.
References VsCnt.
Member Data Documentation
ExpCnt
unsigned llvm::AMDGPU::Waitcnt::ExpCnt = ~0u
Definition at line 842 of file AMDGPUBaseInfo.h.
Referenced by combined(), hasWait(), and hasWaitExceptVsCnt().
LgkmCnt
unsigned llvm::AMDGPU::Waitcnt::LgkmCnt = ~0u
Definition at line 843 of file AMDGPUBaseInfo.h.
Referenced by combined(), hasWait(), and hasWaitExceptVsCnt().
VmCnt
unsigned llvm::AMDGPU::Waitcnt::VmCnt = ~0u
Definition at line 841 of file AMDGPUBaseInfo.h.
Referenced by combined(), hasWait(), and hasWaitExceptVsCnt().
VsCnt
unsigned llvm::AMDGPU::Waitcnt::VsCnt = ~0u
Definition at line 844 of file AMDGPUBaseInfo.h.
Referenced by combined(), hasWait(), and hasWaitVsCnt().
The documentation for this struct was generated from the following file:
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.h