LLVM: llvm::rdf::PhysicalRegisterInfo Struct Reference
llvm::rdf::PhysicalRegisterInfo Struct Reference
#include "llvm/CodeGen/RDFRegisters.h"
Public Member Functions
PhysicalRegisterInfo (const TargetRegisterInfo &tri, const MachineFunction &mf)
RegisterId getRegMaskId (const uint32_t *RM) const
const uint32_t * getRegMaskBits (RegisterId R) const
bool alias (RegisterRef RA, RegisterRef RB) const
std::set< RegisterId > getAliasSet (RegisterId Reg) const
RegisterRef getRefForUnit (uint32_t U) const
const BitVector & getMaskUnits (RegisterId MaskId) const
std::set< RegisterId > getUnits (RegisterRef RR) const
const BitVector & getUnitAliases (uint32_t U) const
RegisterRef mapTo (RegisterRef RR, unsigned R) const
const TargetRegisterInfo & getTRI () const
bool equal_to (RegisterRef A, RegisterRef B) const
bool less (RegisterRef A, RegisterRef B) const
void print (raw_ostream &OS, RegisterRef A) const
void print (raw_ostream &OS, const RegisterAggr &A) const
Detailed Description
Definition at line 141 of file RDFRegisters.h.
Constructor & Destructor Documentation
PhysicalRegisterInfo()
llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo (const TargetRegisterInfo & tri, const MachineFunction & mf)
Definition at line 28 of file RDFRegisters.cpp.
References assert(), B, E, F, llvm::MCRegister::from(), llvm::rdf::IndexedSet< T, N >::get(), llvm::LaneBitmask::getAll(), llvm::MCRegisterInfo::getNumRegs(), llvm::MCRegisterInfo::getNumRegUnits(), llvm::TargetRegisterInfo::getRegMasks(), I, llvm::rdf::IndexedSet< T, N >::insert(), llvm::MCRegUnitMaskIterator::isValid(), llvm::TargetRegisterClass::LaneMask, P, llvm::TargetRegisterInfo::regclasses(), llvm::MCRegisterInfo::regunits(), llvm::BitVector::set(), llvm::rdf::IndexedSet< T, N >::size(), and llvm::MCRegisterInfo::superregs_inclusive().
Member Function Documentation
alias()
bool llvm::rdf::PhysicalRegisterInfo::alias (RegisterRef RA, RegisterRef RB) const
Definition at line 107 of file RDFRegisters.cpp.
References llvm::rdf::disjoint(), getUnits(), and RA.
Referenced by llvm::rdf::Liveness::getAllReachingDefs().
equal_to()
bool llvm::rdf::PhysicalRegisterInfo::equal_to (RegisterRef A, RegisterRef B) const
Definition at line 187 of file RDFRegisters.cpp.
References A, B, llvm::LaneBitmask::getAll(), getTRI(), and llvm::MCRegUnitMaskIterator::isValid().
Referenced by llvm::rdf::DataFlowGraph::getNextRelated(), and llvm::rdf::CopyPropagation::run().
getAliasSet()
std::set< RegisterId > llvm::rdf::PhysicalRegisterInfo::getAliasSet (RegisterId Reg) const
Definition at line 111 of file RDFRegisters.cpp.
References assert(), llvm::MCRegisterInfo::getNumRegs(), getRegMaskBits(), llvm::rdf::RegisterRef::isMaskId(), llvm::rdf::RegisterRef::isRegId(), llvm::rdf::RegisterRef::isUnitId(), and llvm::MCRegAliasIterator::isValid().
getMaskUnits()
const BitVector & llvm::rdf::PhysicalRegisterInfo::getMaskUnits (RegisterId MaskId) const inline
Definition at line 162 of file RDFRegisters.h.
References llvm::Register::stackSlot2Index().
Referenced by llvm::rdf::RegisterAggr::hasAliasOf(), llvm::rdf::RegisterAggr::hasCoverOf(), and llvm::rdf::RegisterAggr::insert().
getRefForUnit()
RegisterRef llvm::rdf::PhysicalRegisterInfo::getRefForUnit (uint32_t U) const inline
Definition at line 158 of file RDFRegisters.h.
getRegMaskBits()
const uint32_t * llvm::rdf::PhysicalRegisterInfo::getRegMaskBits (RegisterId R) const inline
Definition at line 149 of file RDFRegisters.h.
References llvm::rdf::IndexedSet< T, N >::get(), and llvm::Register::stackSlot2Index().
Referenced by getAliasSet(), and getUnits().
getRegMaskId()
RegisterId llvm::rdf::PhysicalRegisterInfo::getRegMaskId (const uint32_t * RM) const inline
Definition at line 145 of file RDFRegisters.h.
References llvm::rdf::IndexedSet< T, N >::find(), and llvm::Register::index2StackSlot().
getTRI()
const TargetRegisterInfo & llvm::rdf::PhysicalRegisterInfo::getTRI () const inline
Definition at line 173 of file RDFRegisters.h.
Referenced by llvm::rdf::DataFlowGraph::build(), equal_to(), llvm::rdf::RegisterAggr::hasAliasOf(), llvm::rdf::RegisterAggr::hasCoverOf(), llvm::rdf::RegisterAggr::insert(), less(), and llvm::rdf::RegisterAggr::makeRegRef().
getUnitAliases()
const BitVector & llvm::rdf::PhysicalRegisterInfo::getUnitAliases (uint32_t U) const inline
Definition at line 168 of file RDFRegisters.h.
Referenced by llvm::rdf::RegisterAggr::makeRegRef().
getUnits()
std::set< RegisterId > llvm::rdf::PhysicalRegisterInfo::getUnits (RegisterRef RR) const
Definition at line 133 of file RDFRegisters.cpp.
References assert(), llvm::CallingConv::C, llvm::countr_zero(), E, llvm::MCRegisterInfo::getNumRegs(), getRegMaskBits(), I, llvm::MCRegisterInfo::regunits(), and T.
Referenced by alias().
less()
bool llvm::rdf::PhysicalRegisterInfo::less (RegisterRef A, RegisterRef B) const
Definition at line 230 of file RDFRegisters.cpp.
References A, B, llvm::LaneBitmask::getAll(), getTRI(), and llvm::MCRegUnitMaskIterator::isValid().
mapTo()
RegisterRef llvm::rdf::PhysicalRegisterInfo::mapTo (RegisterRef RR, unsigned R) const
Definition at line 172 of file RDFRegisters.cpp.
References llvm::TargetRegisterInfo::composeSubRegIndexLaneMask(), llvm::LaneBitmask::getAll(), llvm::MCRegisterInfo::getSubRegIndex(), Idx, llvm::TargetRegisterClass::LaneMask, llvm_unreachable, and llvm::TargetRegisterInfo::reverseComposeSubRegIndexLaneMask().
print() [1/2]
void llvm::rdf::PhysicalRegisterInfo::print (raw_ostream & OS, const RegisterAggr & A) const
Definition at line 293 of file RDFRegisters.cpp.
References A, OS, and llvm::printRegUnit().
print() [2/2]
void llvm::rdf::PhysicalRegisterInfo::print (raw_ostream & OS, RegisterRef A) const
Definition at line 275 of file RDFRegisters.cpp.
References A, assert(), llvm::format(), llvm::MCRegisterInfo::getName(), llvm::MCRegisterInfo::getNumRegs(), Idx, OS, llvm::printReg(), llvm::printRegUnit(), and llvm::Register::stackSlot2Index().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFRegisters.h
lib/CodeGen/RDFRegisters.cpp