LLVM: llvm::PatternMatch::NotForbidUndef_match< ValTy > Struct Template Reference
llvm::PatternMatch::NotForbidUndef_match< ValTy > Struct Template Reference
#include "llvm/IR/PatternMatch.h"
Public Member Functions
NotForbidUndef_match (const ValTy &V)
template<typename OpTy >
bool match (OpTy *V)
Public Attributes
ValTy Val
Detailed Description
template<typename ValTy>
struct llvm::PatternMatch::NotForbidUndef_match< ValTy >
Definition at line 2337 of file PatternMatch.h.
Constructor & Destructor Documentation
NotForbidUndef_match()
template<typename ValTy > llvm::PatternMatch::NotForbidUndef_match< ValTy >::NotForbidUndef_match (const ValTy & V) inline
Definition at line 2339 of file PatternMatch.h.
Member Function Documentation
match()
template<typename ValTy > template<typename OpTy > bool llvm::PatternMatch::NotForbidUndef_match< ValTy >::match (OpTy * V) inline
Definition at line 2341 of file PatternMatch.h.
References llvm::CallingConv::C, llvm::PatternMatch::m_APIntForbidUndef(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Xor(), llvm::PatternMatch::NotForbidUndef_match< ValTy >::match(), llvm::PatternMatch::NotForbidUndef_match< ValTy >::Val, and X.
Referenced by llvm::PatternMatch::NotForbidUndef_match< ValTy >::match().
Member Data Documentation
Val
template<typename ValTy > ValTy llvm::PatternMatch::NotForbidUndef_match< ValTy >::Val
Definition at line 2338 of file PatternMatch.h.
Referenced by llvm::PatternMatch::NotForbidUndef_match< ValTy >::match().
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h