LLVM: llvm::rdf::BlockNode Struct Reference
llvm::rdf::BlockNode Struct Reference
#include "llvm/CodeGen/RDFGraph.h"
Public Member Functions
MachineBasicBlock * getCode () const
void addPhi (Phi PA, const DataFlowGraph &G)
Public Member Functions inherited from llvm::rdf::CodeNode
template<typename T >
T getCode () const
void setCode (void *C)
Node getFirstMember (const DataFlowGraph &G) const
Node getLastMember (const DataFlowGraph &G) const
void addMember (Node NA, const DataFlowGraph &G)
void addMemberAfter (Node MA, Node NA, const DataFlowGraph &G)
void removeMember (Node NA, const DataFlowGraph &G)
NodeList members (const DataFlowGraph &G) const
template<typename Predicate >
NodeList members_if (Predicate P, const DataFlowGraph &G) const
Public Member Functions inherited from llvm::rdf::NodeBase
NodeBase ()=default
uint16_t getType () const
uint16_t getKind () const
uint16_t getFlags () const
NodeId getNext () const
uint16_t getAttrs () const
void setAttrs (uint16_t A)
void setFlags (uint16_t F)
void append (Node NA)
void init ()
void setNext (NodeId N)
Additional Inherited Members
Protected Attributes inherited from llvm::rdf::NodeBase
uint16_t Attrs
uint16_t Reserved
NodeId Next
union {
Ref_struct RefData
Code_struct CodeData
};
Detailed Description
Definition at line 643 of file RDFGraph.h.
Member Function Documentation
addPhi()
void llvm::rdf::BlockNode::addPhi (Phi PA, const DataFlowGraph & G)
Definition at line 539 of file RDFGraph.cpp.
References llvm::rdf::CodeNode::addMember(), llvm::rdf::CodeNode::addMemberAfter(), llvm::rdf::NodeAddr< T >::Addr, assert(), llvm::rdf::NodeAttrs::Code, llvm::rdf::NodeBase::CodeData, llvm::rdf::NodeBase::Code_struct::FirstM, G, llvm::rdf::CodeNode::getFirstMember(), llvm::rdf::NodeAddr< T >::Id, llvm::rdf::NodeAttrs::Phi, and llvm::rdf::NodeAttrs::Stmt.
getCode()
MachineBasicBlock * llvm::rdf::BlockNode::getCode () const inline
Definition at line 644 of file RDFGraph.h.
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFGraph.h
lib/CodeGen/RDFGraph.cpp