LLVM: lib/Target/VE/MCTargetDesc/VEMCTargetDesc.cpp File Reference
VEMCTargetDesc.cpp File Reference
#include "VEMCTargetDesc.h"
#include "TargetInfo/VETargetInfo.h"
#include "VEInstPrinter.h"
#include "VEMCAsmInfo.h"
#include "VETargetStreamer.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "VEGenInstrInfo.inc"
#include "VEGenSubtargetInfo.inc"
#include "VEGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCAsmInfo * createVEMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
static MCInstrInfo * createVEMCInstrInfo ()
static MCRegisterInfo * createVEMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createVEMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCTargetStreamer * createObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
static MCTargetStreamer * createTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint, bool isVerboseAsm)
static MCTargetStreamer * createNullTargetStreamer (MCStreamer &S)
static MCInstPrinter * createVEMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeVETargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 27 of file VEMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 26 of file VEMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 33 of file VEMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 30 of file VEMCTargetDesc.cpp.
Function Documentation
createNullTargetStreamer()
static MCTargetStreamer * createNullTargetStreamer (MCStreamer & S) static
Definition at line 76 of file VEMCTargetDesc.cpp.
Referenced by LLVMInitializeVETargetMC().
createObjectTargetStreamer()
static MCTargetStreamer * createObjectTargetStreamer (MCStreamer & S, const MCSubtargetInfo & STI) static
Definition at line 65 of file VEMCTargetDesc.cpp.
Referenced by LLVMInitializeVETargetMC().
createTargetAsmStreamer()
static MCTargetStreamer * createTargetAsmStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint, bool isVerboseAsm) static
Definition at line 69 of file VEMCTargetDesc.cpp.
References OS.
Referenced by LLVMInitializeVETargetMC().
createVEMCAsmInfo()
static MCAsmInfo * createVEMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT, const MCTargetOptions & Options) static
Definition at line 36 of file VEMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::cfiDefCfa(), and MRI.
Referenced by LLVMInitializeVETargetMC().
createVEMCInstPrinter()
static MCInstPrinter * createVEMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 80 of file VEMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeVETargetMC().
createVEMCInstrInfo()
static MCInstrInfo * createVEMCInstrInfo () static
Definition at line 45 of file VEMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeVETargetMC().
createVEMCRegisterInfo()
static MCRegisterInfo * createVEMCRegisterInfo (const Triple & TT) static
Definition at line 51 of file VEMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeVETargetMC().
createVEMCSubtargetInfo()
static MCSubtargetInfo * createVEMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 57 of file VEMCTargetDesc.cpp.
Referenced by LLVMInitializeVETargetMC().
LLVMInitializeVETargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeVETargetMC ()
Definition at line 88 of file VEMCTargetDesc.cpp.
References createNullTargetStreamer(), createObjectTargetStreamer(), createTargetAsmStreamer(), llvm::createVEAsmBackend(), createVEMCAsmInfo(), llvm::createVEMCCodeEmitter(), createVEMCInstPrinter(), createVEMCInstrInfo(), createVEMCRegisterInfo(), createVEMCSubtargetInfo(), llvm::getTheVETarget(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), llvm::TargetRegistry::RegisterObjectTargetStreamer(), and X.