LLVM: lib/MC/WinCOFFObjectWriter.cpp File Reference
WinCOFFObjectWriter.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCFragment.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolCOFF.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/MCWinCOFFObjectWriter.h"
#include "llvm/MC/StringTableBuilder.h"
#include "llvm/Support/CRC.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/EndianStream.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstring>
#include <ctime>
#include <memory>
#include <string>
#include <vector>
Macros
#define DEBUG_TYPE "WinCOFFObjectWriter"
Functions
static bool isDwoSection (const MCSection &Sec)
static uint32_t getAlignment (const MCSectionCOFF &Sec)
static uint64_t getSymbolValue (const MCSymbol &Symbol, const MCAsmLayout &Layout)
static bool isAssociative (const COFFSection &Section)
static std::time_t getTime ()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "WinCOFFObjectWriter"
Definition at line 54 of file WinCOFFObjectWriter.cpp.
Function Documentation
getAlignment()
static uint32_t getAlignment (const MCSectionCOFF & Sec) static
Definition at line 289 of file WinCOFFObjectWriter.cpp.
References llvm::MCSection::getAlign(), llvm::COFF::IMAGE_SCN_ALIGN_1024BYTES, llvm::COFF::IMAGE_SCN_ALIGN_128BYTES, llvm::COFF::IMAGE_SCN_ALIGN_16BYTES, llvm::COFF::IMAGE_SCN_ALIGN_1BYTES, llvm::COFF::IMAGE_SCN_ALIGN_2048BYTES, llvm::COFF::IMAGE_SCN_ALIGN_256BYTES, llvm::COFF::IMAGE_SCN_ALIGN_2BYTES, llvm::COFF::IMAGE_SCN_ALIGN_32BYTES, llvm::COFF::IMAGE_SCN_ALIGN_4096BYTES, llvm::COFF::IMAGE_SCN_ALIGN_4BYTES, llvm::COFF::IMAGE_SCN_ALIGN_512BYTES, llvm::COFF::IMAGE_SCN_ALIGN_64BYTES, llvm::COFF::IMAGE_SCN_ALIGN_8192BYTES, llvm::COFF::IMAGE_SCN_ALIGN_8BYTES, llvm_unreachable, and llvm::Align::value().
getSymbolValue()
static uint64_t getSymbolValue (const MCSymbol & Symbol, const MCAsmLayout & Layout) static
Definition at line 372 of file WinCOFFObjectWriter.cpp.
References llvm::MCAsmLayout::getSymbolOffset().
Referenced by llvm::object::ELFObjectFile< ELFT >::getSymbolAddress().
getTime()
static std::time_t getTime () static
Definition at line 1005 of file WinCOFFObjectWriter.cpp.
isAssociative()
static bool isAssociative (const COFFSection & Section) static
Definition at line 740 of file WinCOFFObjectWriter.cpp.
References llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE.
isDwoSection()
static bool isDwoSection (const MCSection & Sec) static
Definition at line 243 of file WinCOFFObjectWriter.cpp.
References llvm::StringRef::endswith(), and llvm::MCSection::getName().