LLVM: lib/Target/X86/X86ArgumentStackSlotRebase.cpp File Reference
X86ArgumentStackSlotRebase.cpp File Reference
#include "X86.h"
#include "X86InstrBuilder.h"
#include "X86MachineFunctionInfo.h"
#include "X86RegisterInfo.h"
#include "X86Subtarget.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Function.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
Macros
#define DEBUG_TYPE "x86argumentstackrebase"
Functions
INITIALIZE_PASS (X86ArgumentStackSlotPass, DEBUG_TYPE, "Argument Stack Rebase", false, false) FunctionPass *llvm
static Register getArgBaseReg (MachineFunction &MF)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86argumentstackrebase"
Definition at line 36 of file X86ArgumentStackSlotRebase.cpp.
Function Documentation
getArgBaseReg()
static Register getArgBaseReg (MachineFunction & MF) static
Definition at line 68 of file X86ArgumentStackSlotRebase.cpp.
References CC, F, llvm::MachineFunction::getFunction(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), and MRI.
INITIALIZE_PASS()
INITIALIZE_PASS (X86ArgumentStackSlotPass , DEBUG_TYPE , "Argument Stack Rebase" , false , false)
Definition at line 61 of file X86ArgumentStackSlotRebase.cpp.