LLVM: lib/Target/X86/X86InstrFoldTables.cpp File Reference
X86InstrFoldTables.cpp File Reference
#include "X86InstrFoldTables.h"
#include "X86InstrInfo.h"
#include "llvm/ADT/STLExtras.h"
#include <atomic>
#include <vector>
#include "X86GenFoldTables.inc"
Functions
static const X86MemoryFoldTableEntry * lookupFoldTableImpl (ArrayRef< X86MemoryFoldTableEntry > Table, unsigned RegOp)
static bool matchBroadcastSize (const X86MemoryFoldTableEntry &Entry, unsigned BroadcastBits)
Variables
static const X86MemoryFoldTableEntry BroadcastFoldTable2 []
static const X86MemoryFoldTableEntry BroadcastFoldTable3 []
static const X86MemoryFoldTableEntry BroadcastSizeFoldTable2 []
static const X86MemoryFoldTableEntry BroadcastSizeFoldTable3 []
Function Documentation
lookupFoldTableImpl()
static const X86MemoryFoldTableEntry * lookupFoldTableImpl (ArrayRef< X86MemoryFoldTableEntry > Table, unsigned RegOp) static
Definition at line 383 of file X86InstrFoldTables.cpp.
References assert(), BroadcastFoldTable2, BroadcastFoldTable3, BroadcastSizeFoldTable2, BroadcastSizeFoldTable3, llvm::Data, llvm::is_sorted(), llvm::lower_bound(), and llvm::TB_NO_FORWARD.
Referenced by llvm::lookupFoldTable(), and llvm::lookupTwoAddrFoldTable().
matchBroadcastSize()
static bool matchBroadcastSize (const X86MemoryFoldTableEntry & Entry, unsigned BroadcastBits) static
Definition at line 601 of file X86InstrFoldTables.cpp.
References llvm::TB_BCAST_D, llvm::TB_BCAST_MASK, llvm::TB_BCAST_Q, llvm::TB_BCAST_SD, and llvm::TB_BCAST_SS.
Referenced by llvm::lookupBroadcastFoldTable().
Variable Documentation
BroadcastFoldTable2
const X86MemoryFoldTableEntry BroadcastFoldTable2[] static
Definition at line 26 of file X86InstrFoldTables.cpp.
Referenced by lookupFoldTableImpl().
BroadcastFoldTable3
const X86MemoryFoldTableEntry BroadcastFoldTable3[] static
Definition at line 203 of file X86InstrFoldTables.cpp.
Referenced by lookupFoldTableImpl().
BroadcastSizeFoldTable2
const X86MemoryFoldTableEntry BroadcastSizeFoldTable2[] static
Definition at line 322 of file X86InstrFoldTables.cpp.
Referenced by lookupFoldTableImpl().
BroadcastSizeFoldTable3
const X86MemoryFoldTableEntry BroadcastSizeFoldTable3[] static
Initial value:
= {
  { X86::VPTERNLOGDZ128rri,    X86::VPTERNLOGQZ128rmbi,   TB_BCAST_Q },
  { X86::VPTERNLOGDZ256rri,    X86::VPTERNLOGQZ256rmbi,   TB_BCAST_Q },
  { X86::VPTERNLOGDZrri,       X86::VPTERNLOGQZrmbi,      TB_BCAST_Q },
  { X86::VPTERNLOGQZ128rri,    X86::VPTERNLOGDZ128rmbi,   TB_BCAST_D },
  { X86::VPTERNLOGQZ256rri,    X86::VPTERNLOGDZ256rmbi,   TB_BCAST_D },
  { X86::VPTERNLOGQZrri,       X86::VPTERNLOGDZrmbi,      TB_BCAST_D },
}
Definition at line 373 of file X86InstrFoldTables.cpp.
Referenced by lookupFoldTableImpl().