LLVM: lib/Target/X86/X86PreAMXConfig.cpp File Reference
X86PreAMXConfig.cpp File Reference
#include "X86.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/IntrinsicsX86.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "pre-amx-config"
Functions
static bool isAMXIntrinsic (IntrinsicInst *II)
static bool isTileLoad (IntrinsicInst *II)
static bool isTileStore (IntrinsicInst *II)
static bool onlyTileDef (IntrinsicInst *II)
static bool brokenVolatile (Instruction *I)
Variables
static const char PassName [] = "Pre AMX Tile Config"
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "pre-amx-config"
Definition at line 59 of file X86PreAMXConfig.cpp.
Function Documentation
brokenVolatile()
static bool brokenVolatile (Instruction * I) static
Definition at line 85 of file X86PreAMXConfig.cpp.
References I.
isAMXIntrinsic()
static bool isAMXIntrinsic (IntrinsicInst * II) static
Definition at line 61 of file X86PreAMXConfig.cpp.
References llvm::Value::getType(), llvm::Type::isX86_AMXTy(), and llvm::User::operands().
isTileLoad()
static bool isTileLoad (IntrinsicInst * II) static
Definition at line 68 of file X86PreAMXConfig.cpp.
References llvm::IntrinsicInst::getIntrinsicID().
isTileStore()
static bool isTileStore (IntrinsicInst * II) static
Definition at line 73 of file X86PreAMXConfig.cpp.
References llvm::IntrinsicInst::getIntrinsicID().
onlyTileDef()
static bool onlyTileDef (IntrinsicInst * II) static
Definition at line 78 of file X86PreAMXConfig.cpp.
References llvm::Value::getType(), llvm::Type::isX86_AMXTy(), and llvm::User::operands().
Variable Documentation
PassName
const char PassName[] = "Pre AMX Tile Config" static
Definition at line 407 of file X86PreAMXConfig.cpp.