LLVM: lib/Target/ARM/MCTargetDesc/ARMTargetStreamer.cpp File Reference
ARMTargetStreamer.cpp File Reference
#include "MCTargetDesc/ARMMCTargetDesc.h"
#include "llvm/MC/ConstantPools.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/ARMBuildAttributes.h"
#include "llvm/Support/TargetParser.h"
Functions
static ARMBuildAttrs::CPUArch getArchForCPU (const MCSubtargetInfo &STI)
static bool isV8M (const MCSubtargetInfo &STI)
Function Documentation
getArchForCPU()
static ARMBuildAttrs::CPUArch getArchForCPU (const MCSubtargetInfo & STI) static
Definition at line 132 of file ARMTargetStreamer.cpp.
References llvm::MCSubtargetInfo::getCPU(), llvm::MCSubtargetInfo::hasFeature(), llvm::ARMBuildAttrs::v4, llvm::ARMBuildAttrs::v4T, llvm::ARMBuildAttrs::v5T, llvm::ARMBuildAttrs::v5TE, llvm::ARMBuildAttrs::v5TEJ, llvm::ARMBuildAttrs::v6, llvm::ARMBuildAttrs::v6S_M, llvm::ARMBuildAttrs::v6T2, llvm::ARMBuildAttrs::v7, llvm::ARMBuildAttrs::v7E_M, llvm::ARMBuildAttrs::v8_1_M_Main, llvm::ARMBuildAttrs::v8_A, llvm::ARMBuildAttrs::v8_M_Base, llvm::ARMBuildAttrs::v8_M_Main, llvm::ARMBuildAttrs::v8_R, and llvm::ARMBuildAttrs::v9_A.
Referenced by llvm::ARMTargetStreamer::emitTargetAttributes().
isV8M()
static bool isV8M (const MCSubtargetInfo & STI) static
Definition at line 168 of file ARMTargetStreamer.cpp.
References llvm::MCSubtargetInfo::hasFeature().
Referenced by llvm::ARMTargetStreamer::emitTargetAttributes().