LLVM: lib/Bitstream/Reader/BitstreamReader.cpp File Reference
BitstreamReader.cpp File Reference
#include "llvm/Bitstream/BitstreamReader.h"
#include "llvm/ADT/StringRef.h"
#include <cassert>
#include <string>
Functions
static Error error (const char *Message)
static Expected< uint64_t > readAbbreviatedField (BitstreamCursor &Cursor, const BitCodeAbbrevOp &Op)
Function Documentation
error()
static Error error (const char * Message) static
Definition at line 20 of file BitstreamReader.cpp.
References llvm::createStringError().
readAbbreviatedField()
static Expected< uint64_t > readAbbreviatedField (BitstreamCursor & Cursor, const BitCodeAbbrevOp & Op) static
Definition at line 70 of file BitstreamReader.cpp.
References llvm::BitCodeAbbrevOp::Array, assert(), llvm::BitCodeAbbrevOp::Blob, llvm::BitCodeAbbrevOp::Char6, llvm::BitCodeAbbrevOp::DecodeChar6(), llvm::BitCodeAbbrevOp::Fixed, llvm_unreachable, and llvm::BitCodeAbbrevOp::VBR.
Referenced by llvm::BitstreamCursor::readRecord(), and llvm::BitstreamCursor::skipRecord().