LLVM: llvm::orc::DebugObject Class Reference
llvm::orc::DebugObject Class Reference abstract
The plugin creates a debug object from when JITLink starts processing the corresponding LinkGraph.
Public Types
using FinalizeContinuation = std::function<void(Expected<ExecutorAddrRange>)>
Public Member Functions
DebugObject (JITLinkMemoryManager &MemMgr, const JITLinkDylib *JD, ExecutionSession &ES)
void set (Requirement Req)
bool has (Requirement Req) const
void finalizeAsync (FinalizeContinuation OnFinalize)
virtual ~DebugObject ()
virtual void reportSectionTargetMemoryRange (StringRef Name, SectionRange TargetMem)
Protected Types
using InFlightAlloc = JITLinkMemoryManager::InFlightAlloc
using FinalizedAlloc = JITLinkMemoryManager::FinalizedAlloc
Protected Member Functions
virtual Expected< SimpleSegmentAlloc > finalizeWorkingMemory ()=0
Protected Attributes
JITLinkMemoryManager & MemMgr
const JITLinkDylib * JD = nullptr
Detailed Description
The plugin creates a debug object from when JITLink starts processing the corresponding LinkGraph.
It provides access to the pass configuration of the LinkGraph and calls the finalization function, once the resulting link artifact was emitted.
Definition at line 126 of file DebugObjectManagerPlugin.cpp.
Member Typedef Documentation
FinalizeContinuation
using llvm::orc::DebugObject::FinalizeContinuation = std::function<void(Expected<ExecutorAddrRange>)>
Definition at line 135 of file DebugObjectManagerPlugin.cpp.
FinalizedAlloc
using llvm::orc::DebugObject::FinalizedAlloc = JITLinkMemoryManager::FinalizedAlloc protected
Definition at line 153 of file DebugObjectManagerPlugin.cpp.
InFlightAlloc
using llvm::orc::DebugObject::InFlightAlloc = JITLinkMemoryManager::InFlightAlloc protected
Definition at line 152 of file DebugObjectManagerPlugin.cpp.
Constructor & Destructor Documentation
DebugObject()
llvm::orc::DebugObject::DebugObject (JITLinkMemoryManager & MemMgr, const JITLinkDylib * JD, ExecutionSession & ES) inline
Definition at line 128 of file DebugObjectManagerPlugin.cpp.
~DebugObject()
virtual llvm::orc::DebugObject::~DebugObject () inline virtual
Definition at line 139 of file DebugObjectManagerPlugin.cpp.
References llvm::jitlink::JITLinkMemoryManager::deallocate(), MemMgr, and llvm::orc::ExecutionSession::reportError().
Member Function Documentation
finalizeAsync()
void llvm::orc::DebugObject::finalizeAsync (FinalizeContinuation OnFinalize)
Definition at line 169 of file DebugObjectManagerPlugin.cpp.
References assert(), and finalizeWorkingMemory().
finalizeWorkingMemory()
virtual Expected< SimpleSegmentAlloc > llvm::orc::DebugObject::finalizeWorkingMemory () protected pure virtual
Implemented in llvm::orc::ELFDebugObject.
Referenced by finalizeAsync().
has()
bool llvm::orc::DebugObject::has (Requirement Req) const inline
Definition at line 133 of file DebugObjectManagerPlugin.cpp.
reportSectionTargetMemoryRange()
virtual void llvm::orc::DebugObject::reportSectionTargetMemoryRange (StringRef Name, SectionRange TargetMem) inline virtual
Reimplemented in llvm::orc::ELFDebugObject.
Definition at line 148 of file DebugObjectManagerPlugin.cpp.
set()
void llvm::orc::DebugObject::set (Requirement Req) inline
Definition at line 132 of file DebugObjectManagerPlugin.cpp.
Member Data Documentation
JD
const JITLinkDylib* llvm::orc::DebugObject::JD = nullptr protected
Definition at line 158 of file DebugObjectManagerPlugin.cpp.
Referenced by llvm::orc::ELFDebugObject::finalizeWorkingMemory().
MemMgr
JITLinkMemoryManager& llvm::orc::DebugObject::MemMgr protected
Definition at line 157 of file DebugObjectManagerPlugin.cpp.
Referenced by llvm::orc::ELFDebugObject::finalizeWorkingMemory(), and ~DebugObject().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/DebugObjectManagerPlugin.cpp