LLVM: llvm::SinkingPass Class Reference
llvm::SinkingPass Class Reference
Move instructions into successor blocks when possible.
#include "llvm/Transforms/Scalar/Sink.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< SinkingPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< SinkingPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Move instructions into successor blocks when possible.
Definition at line 24 of file Sink.h.
Member Function Documentation
run()
PreservedAnalyses SinkingPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 231 of file Sink.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), iterativelySinkInstructions(), and llvm::PreservedAnalyses::preserveSet().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/Sink.h
lib/Transforms/Scalar/Sink.cpp