LLVM: llvm::WebAssemblyTargetAsmStreamer Class Reference
llvm::WebAssemblyTargetAsmStreamer Class Reference final
This part is for ascii assembly output.
#include "Target/WebAssembly/MCTargetDesc/WebAssemblyTargetStreamer.h"
Public Member Functions
WebAssemblyTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &OS)
void emitLocal (ArrayRef< wasm::ValType > Types) override
.local
void emitFunctionType (const MCSymbolWasm *Sym) override
.functype
void emitIndIdx (const MCExpr *Value) override
.indidx
void emitGlobalType (const MCSymbolWasm *Sym) override
.globaltype
void emitTableType (const MCSymbolWasm *Sym) override
.tabletype
void emitTagType (const MCSymbolWasm *Sym) override
.tagtype
void emitImportModule (const MCSymbolWasm *Sym, StringRef ImportModule) override
.import_module
void emitImportName (const MCSymbolWasm *Sym, StringRef ImportName) override
.import_name
void emitExportName (const MCSymbolWasm *Sym, StringRef ExportName) override
.export_name
Public Member Functions inherited from llvm::WebAssemblyTargetStreamer
WebAssemblyTargetStreamer (MCStreamer &S)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Member Functions inherited from llvm::WebAssemblyTargetStreamer
void emitValueType (wasm::ValType Type)
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
This part is for ascii assembly output.
Definition at line 60 of file WebAssemblyTargetStreamer.h.
Constructor & Destructor Documentation
WebAssemblyTargetAsmStreamer()
WebAssemblyTargetAsmStreamer::WebAssemblyTargetAsmStreamer (MCStreamer & S, formatted_raw_ostream & OS)
Definition at line 34 of file WebAssemblyTargetStreamer.cpp.
Member Function Documentation
emitExportName()
void WebAssemblyTargetAsmStreamer::emitExportName (const MCSymbolWasm * Sym, StringRef ExportName) override virtual
.export_name
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 111 of file WebAssemblyTargetStreamer.cpp.
References llvm::MCSymbol::getName().
emitFunctionType()
void WebAssemblyTargetAsmStreamer::emitFunctionType (const MCSymbolWasm * Sym) override virtual
.functype
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 61 of file WebAssemblyTargetStreamer.cpp.
References assert(), llvm::MCSymbol::getName(), llvm::MCSymbolWasm::getSignature(), llvm::MCSymbolWasm::isFunction(), and llvm::WebAssembly::signatureToString().
emitGlobalType()
void WebAssemblyTargetAsmStreamer::emitGlobalType (const MCSymbolWasm * Sym) override virtual
.globaltype
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 68 of file WebAssemblyTargetStreamer.cpp.
References assert(), llvm::MCSymbolWasm::getGlobalType(), llvm::MCSymbol::getName(), llvm::MCSymbolWasm::isGlobal(), llvm::wasm::WasmGlobalType::Mutable, llvm::wasm::WasmGlobalType::Type, and llvm::WebAssembly::typeToString().
emitImportModule()
void WebAssemblyTargetAsmStreamer::emitImportModule (const MCSymbolWasm * Sym, StringRef ImportModule) override virtual
.import_module
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 99 of file WebAssemblyTargetStreamer.cpp.
References llvm::MCSymbol::getName().
emitImportName()
void WebAssemblyTargetAsmStreamer::emitImportName (const MCSymbolWasm * Sym, StringRef ImportName) override virtual
.import_name
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 105 of file WebAssemblyTargetStreamer.cpp.
References llvm::MCSymbol::getName().
emitIndIdx()
void WebAssemblyTargetAsmStreamer::emitIndIdx (const MCExpr * Value) override virtual
.indidx
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 117 of file WebAssemblyTargetStreamer.cpp.
emitLocal()
void WebAssemblyTargetAsmStreamer::emitLocal (ArrayRef< wasm::ValType > Types) override virtual
.local
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 54 of file WebAssemblyTargetStreamer.cpp.
References printTypes().
emitTableType()
void WebAssemblyTargetAsmStreamer::emitTableType (const MCSymbolWasm * Sym) override virtual
.tabletype
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 78 of file WebAssemblyTargetStreamer.cpp.
References assert(), llvm::MCSymbol::getName(), llvm::MCSymbolWasm::getTableType(), llvm::MCSymbolWasm::isTable(), llvm::WebAssembly::typeToString(), and llvm::wasm::WASM_LIMITS_FLAG_HAS_MAX.
emitTagType()
void WebAssemblyTargetAsmStreamer::emitTagType (const MCSymbolWasm * Sym) override virtual
.tagtype
Implements llvm::WebAssemblyTargetStreamer.
Definition at line 92 of file WebAssemblyTargetStreamer.cpp.
References assert(), llvm::MCSymbol::getName(), llvm::MCSymbolWasm::getSignature(), llvm::MCSymbolWasm::isTag(), llvm::wasm::WasmSignature::Params, and llvm::WebAssembly::typeListToString().
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/MCTargetDesc/WebAssemblyTargetStreamer.h
lib/Target/WebAssembly/MCTargetDesc/WebAssemblyTargetStreamer.cpp