LLVM: llvm::OpInit Class Reference
llvm::OpInit Class Reference abstract
Base class for operators.
#include "llvm/TableGen/Record.h"
Public Member Functions
OpInit (const OpInit &)=delete
OpInit & operator= (OpInit &)=delete
virtual OpInit * clone (ArrayRef< Init * > Operands) const =0
virtual unsigned getNumOperands () const =0
virtual Init * getOperand (unsigned i) const =0
Init * getBit (unsigned Bit) const override
Get the Init value of the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Get the type of the Init as a RecTy.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init * getCastTo (RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This function is used to implement the bit range selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This function is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
Is this a complete value with no unset (uninitialized) subvalues?
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print this value.
virtual std::string getAsString () const =0
Convert this value to a literal form.
virtual std::string getAsUnquotedString () const
Convert this value to a literal form, without adding quotes around a string.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
virtual Init * resolveReferences (Resolver &R) const
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
Static Public Member Functions
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Protected Member Functions
OpInit (InitKind K, RecTy *Type, uint8_t Opc)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_DagInit , IK_DefInit , IK_FieldInit , IK_IntInit ,
IK_ListInit , IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit ,
IK_UnOpInit , IK_LastOpInit , IK_CondOpInit , IK_FoldOpInit ,
IK_IsAOpInit , IK_ExistsOpInit , IK_AnonymousNameInit , IK_StringInit ,
IK_VarInit , IK_VarListElementInit , IK_VarBitInit , IK_VarDefInit ,
IK_LastTypedInit , IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
Base class for operators.
Definition at line 760 of file Record.h.
Constructor & Destructor Documentation
OpInit() [1/2]
llvm::OpInit::OpInit (InitKind K, RecTy * Type, uint8_t Opc) inline explicit protected
Definition at line 762 of file Record.h.
OpInit() [2/2]
llvm::OpInit::OpInit (const OpInit &) delete
Member Function Documentation
classof()
static bool llvm::OpInit::classof (const Init * I) inline static
Definition at line 769 of file Record.h.
References I, llvm::Init::IK_FirstOpInit, and llvm::Init::IK_LastOpInit.
clone()
virtual OpInit * llvm::OpInit::clone (ArrayRef< Init * > Operands) const pure virtual
Implemented in llvm::UnOpInit, llvm::BinOpInit, and llvm::TernOpInit.
getBit()
Init * OpInit::getBit (unsigned Bit) const override virtual
Get the Init value of the specified bit.
Implements llvm::Init.
Definition at line 746 of file Record.cpp.
References llvm::BitRecTy::get(), llvm::VarBitInit::get(), llvm::TypedInit::getRecordKeeper(), and llvm::TypedInit::getType().
getNumOperands()
virtual unsigned llvm::OpInit::getNumOperands () const pure virtual
Implemented in llvm::UnOpInit, llvm::BinOpInit, and llvm::TernOpInit.
getOperand()
virtual Init * llvm::OpInit::getOperand (unsigned i) const pure virtual
Implemented in llvm::UnOpInit, llvm::BinOpInit, and llvm::TernOpInit.
operator=()
OpInit & llvm::OpInit::operator= (OpInit &) delete
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp