LLVM: llvm::codeview::OneMethodRecord Class Reference
llvm::codeview::OneMethodRecord Class Reference
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
Public Member Functions
OneMethodRecord ()=default
OneMethodRecord (TypeRecordKind Kind)
OneMethodRecord (TypeIndex Type, MemberAttributes Attrs, int32_t VFTableOffset, StringRef Name)
OneMethodRecord (TypeIndex Type, MemberAccess Access, MethodKind MK, MethodOptions Options, int32_t VFTableOffset, StringRef Name)
TypeIndex getType () const
MethodKind getMethodKind () const
MethodOptions getOptions () const
MemberAccess getAccess () const
int32_t getVFTableOffset () const
StringRef getName () const
bool isIntroducingVirtual () const
Public Member Functions inherited from llvm::codeview::TypeRecord
TypeRecordKind getKind () const
Public Attributes
TypeIndex Type
MemberAttributes Attrs
int32_t VFTableOffset = 0
StringRef Name
Public Attributes inherited from llvm::codeview::TypeRecord
TypeRecordKind Kind
Additional Inherited Members
Protected Member Functions inherited from llvm::codeview::TypeRecord
TypeRecord ()=default
TypeRecord (TypeRecordKind Kind)
Detailed Description
Definition at line 720 of file TypeRecord.h.
Constructor & Destructor Documentation
OneMethodRecord() [1/4]
llvm::codeview::OneMethodRecord::OneMethodRecord () default
OneMethodRecord() [2/4]
llvm::codeview::OneMethodRecord::OneMethodRecord (TypeRecordKind Kind) inline explicit
Definition at line 723 of file TypeRecord.h.
OneMethodRecord() [3/4]
llvm::codeview::OneMethodRecord::OneMethodRecord (TypeIndex Type, MemberAttributes Attrs, int32_t VFTableOffset, StringRef Name) inline
Definition at line 724 of file TypeRecord.h.
OneMethodRecord() [4/4]
llvm::codeview::OneMethodRecord::OneMethodRecord (TypeIndex Type, MemberAccess Access, MethodKind MK, MethodOptions Options, int32_t VFTableOffset, StringRef Name) inline
Definition at line 728 of file TypeRecord.h.
Member Function Documentation
getAccess()
MemberAccess llvm::codeview::OneMethodRecord::getAccess () const inline
Definition at line 736 of file TypeRecord.h.
References Attrs, and llvm::codeview::MemberAttributes::getAccess().
getMethodKind()
MethodKind llvm::codeview::OneMethodRecord::getMethodKind () const inline
Definition at line 734 of file TypeRecord.h.
References Attrs, and llvm::codeview::MemberAttributes::getMethodKind().
Referenced by isIntroducingVirtual().
getName()
StringRef llvm::codeview::OneMethodRecord::getName () const inline
Definition at line 738 of file TypeRecord.h.
References Name.
getOptions()
MethodOptions llvm::codeview::OneMethodRecord::getOptions () const inline
Definition at line 735 of file TypeRecord.h.
References Attrs, and llvm::codeview::MemberAttributes::getFlags().
getType()
TypeIndex llvm::codeview::OneMethodRecord::getType () const inline
Definition at line 733 of file TypeRecord.h.
References Type.
getVFTableOffset()
int32_t llvm::codeview::OneMethodRecord::getVFTableOffset () const inline
Definition at line 737 of file TypeRecord.h.
References VFTableOffset.
isIntroducingVirtual()
bool llvm::codeview::OneMethodRecord::isIntroducingVirtual () const inline
Definition at line 740 of file TypeRecord.h.
References getMethodKind(), llvm::codeview::IntroducingVirtual, and llvm::codeview::PureIntroducingVirtual.
Member Data Documentation
Attrs
MemberAttributes llvm::codeview::OneMethodRecord::Attrs
Definition at line 746 of file TypeRecord.h.
Referenced by getAccess(), getMethodKind(), and getOptions().
Name
StringRef llvm::codeview::OneMethodRecord::Name
Definition at line 748 of file TypeRecord.h.
Referenced by getName().
Type
TypeIndex llvm::codeview::OneMethodRecord::Type
Definition at line 745 of file TypeRecord.h.
Referenced by getType().
VFTableOffset
int32_t llvm::codeview::OneMethodRecord::VFTableOffset = 0
Definition at line 747 of file TypeRecord.h.
Referenced by getVFTableOffset().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/CodeView/TypeRecord.h