LLVM: llvm::DIEValue Class Reference
llvm::DIEValue Class Reference
#include "llvm/CodeGen/DIE.h"
Public Types
enum Type { isNone }
Public Member Functions
DIEValue ()=default
DIEValue (const DIEValue &X)
DIEValue & operator= (const DIEValue &X)
~DIEValue ()
void emitValue (const AsmPrinter *AP) const
Emit value via the Dwarf writer.
unsigned sizeOf (const dwarf::FormParams &FormParams) const
Return the size of a value in bytes.
void print (raw_ostream &O) const
void dump () const
Type getType () const
Accessors.
dwarf::Attribute getAttribute () const
dwarf::Form getForm () const
operator bool () const
Detailed Description
Definition at line 369 of file DIE.h.
Member Enumeration Documentation
Type
enum llvm::DIEValue::Type
Enumerator
isNone
Definition at line 371 of file DIE.h.
Constructor & Destructor Documentation
DIEValue() [1/2]
llvm::DIEValue::DIEValue () default
DIEValue() [2/2]
llvm::DIEValue::DIEValue (const DIEValue & X) inline
Definition at line 457 of file DIE.h.
References X.
~DIEValue()
llvm::DIEValue::~DIEValue () inline
Definition at line 470 of file DIE.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void DIEValue::dump () const
Definition at line 359 of file DIE.cpp.
References llvm::dbgs(), and print().
emitValue()
void DIEValue::emitValue (const AsmPrinter * AP) const
Emit value via the Dwarf writer.
Definition at line 321 of file DIE.cpp.
References isNone, and llvm_unreachable.
getAttribute()
dwarf::Attribute llvm::DIEValue::getAttribute () const inline
Definition at line 488 of file DIE.h.
getForm()
dwarf::Form llvm::DIEValue::getForm () const inline
Definition at line 489 of file DIE.h.
getType()
Type llvm::DIEValue::getType () const inline
Accessors.
Definition at line 487 of file DIE.h.
operator bool()
llvm::DIEValue::operator bool () const inline explicit
Definition at line 490 of file DIE.h.
operator=()
DIEValue & llvm::DIEValue::operator= (const DIEValue & X) inline
Definition at line 461 of file DIE.h.
References X.
print()
LLVM_DUMP_METHOD void DIEValue::print (raw_ostream & O) const
Definition at line 346 of file DIE.cpp.
References isNone, and llvm_unreachable.
Referenced by dump().
sizeOf()
unsigned DIEValue::sizeOf (const dwarf::FormParams & FormParams) const
Return the size of a value in bytes.
Definition at line 333 of file DIE.cpp.
References isNone, and llvm_unreachable.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DIE.h
lib/CodeGen/AsmPrinter/DIE.cpp