LLVM: llvm::CodeGenPassBuilder< DerivedT >::AddIRPass Class Reference
llvm::CodeGenPassBuilder< DerivedT >::AddIRPass Class Reference
#include "llvm/CodeGen/CodeGenPassBuilder.h"
Public Member Functions
AddIRPass (ModulePassManager &MPM, bool DebugPM, bool Check=true)
~AddIRPass ()
template<typename PassT >
std::enable_if_t< is_detected< is_function_pass_t, PassT >::value > operator() (PassT &&Pass)
template<typename PassT >
std::enable_if_t< is_detected< is_module_pass_t, PassT >::value &&!is_detected< is_function_pass_t, PassT >::value > operator() (PassT &&Pass)
Detailed Description
template<typename DerivedT>
class llvm::CodeGenPassBuilder< DerivedT >::AddIRPass
Definition at line 154 of file CodeGenPassBuilder.h.
Constructor & Destructor Documentation
AddIRPass()
template<typename DerivedT > llvm::CodeGenPassBuilder< DerivedT >::AddIRPass::AddIRPass (ModulePassManager & MPM, bool DebugPM, bool Check = true) inline
Definition at line 156 of file CodeGenPassBuilder.h.
References Check, and MPM.
~AddIRPass()
template<typename DerivedT > llvm::CodeGenPassBuilder< DerivedT >::AddIRPass::~AddIRPass () inline
Definition at line 161 of file CodeGenPassBuilder.h.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), and llvm::createModuleToFunctionPassAdaptor().
Member Function Documentation
operator()() [1/2]
template<typename DerivedT > template<typename PassT > std::enable_if_t< is_detected< is_function_pass_t, PassT >::value > llvm::CodeGenPassBuilder< DerivedT >::AddIRPass::operator() (PassT && Pass) inline
Definition at line 168 of file CodeGenPassBuilder.h.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass().
operator()() [2/2]
template<typename DerivedT > template<typename PassT > std::enable_if_t< is_detected< is_module_pass_t, PassT >::value && !is_detected< is_function_pass_t, PassT >::value > llvm::CodeGenPassBuilder< DerivedT >::AddIRPass::operator() (PassT && Pass) inline
Definition at line 178 of file CodeGenPassBuilder.h.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), and assert().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/CodeGenPassBuilder.h