LLVM: llvm::Win64EH::ARM64UnwindEmitter Class Reference
llvm::Win64EH::ARM64UnwindEmitter Class Reference
#include "llvm/MC/MCWin64EH.h"
Public Member Functions
void Emit (MCStreamer &Streamer) const override
This emits the unwind info sections (.pdata and .xdata in PE/COFF).
void EmitUnwindInfo (MCStreamer &Streamer, WinEH::FrameInfo *FI, bool HandlerData) const override
Public Member Functions inherited from llvm::WinEH::UnwindEmitter
virtual ~UnwindEmitter ()
Detailed Description
Definition at line 67 of file MCWin64EH.h.
Member Function Documentation
Emit()
void llvm::Win64EH::ARM64UnwindEmitter::Emit (MCStreamer & Streamer) const override virtual
This emits the unwind info sections (.pdata and .xdata in PE/COFF).
Implements llvm::WinEH::UnwindEmitter.
Definition at line 2223 of file MCWin64EH.cpp.
References ARM64EmitUnwindInfo(), ARMEmitRuntimeFunction(), llvm::MCStreamer::getAssociatedPDataSection(), llvm::MCStreamer::getAssociatedXDataSection(), llvm::MCStreamer::getWinFrameInfos(), and llvm::MCStreamer::switchSection().
EmitUnwindInfo()
void llvm::Win64EH::ARM64UnwindEmitter::EmitUnwindInfo (MCStreamer & Streamer, WinEH::FrameInfo * FI, bool HandlerData) const override virtual
Implements llvm::WinEH::UnwindEmitter.
Definition at line 2248 of file MCWin64EH.cpp.
References ARM64EmitUnwindInfo(), llvm::MCStreamer::emitCFILabel(), llvm::MCStreamer::getAssociatedXDataSection(), info, and llvm::MCStreamer::switchSection().
The documentation for this class was generated from the following files:
include/llvm/MC/MCWin64EH.h
lib/MC/MCWin64EH.cpp