LLVM: llvm::R600TargetMachine Class Reference
llvm::R600TargetMachine Class Reference final
#include "Target/AMDGPU/R600TargetMachine.h"
Public Member Functions
R600TargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, TargetOptions Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool JIT)
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
const TargetSubtargetInfo * getSubtargetImpl (const Function &) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
TargetTransformInfo getTargetTransformInfo (const Function &F) const override
Get a TargetTransformInfo implementation for the target.
bool isMachineVerifierClean () const override
Returns true if the target is expected to pass all machine verifier checks.
Public Member Functions inherited from llvm::AMDGPUTargetMachine
AMDGPUTargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, TargetOptions Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL)
~AMDGPUTargetMachine () override
const TargetSubtargetInfo * getSubtargetImpl () const
TargetLoweringObjectFile * getObjFileLowering () const override
void adjustPassManager (PassManagerBuilder &) override
Allow the target to modify the pass manager, e.g.
void registerPassBuilderCallbacks (PassBuilder &PB) override
Allow the target to modify the pass pipeline with New Pass Manager (similar to adjustPassManager for Legacy Pass manager).
void registerDefaultAliasAnalyses (AAManager &) override
Allow the target to register alias analyses with the AAManager for use with the new pass manager.
bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const override
Returns true if a cast between SrcAS and DestAS is a noop.
unsigned getAssumedAddrSpace (const Value *V) const override
If the specified generic pointer could be assumed as a pointer to a specific address space, return that address space.
std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const override
If the specified predicate checks whether a generic pointer falls within a specified address space, return that generic pointer and the address space being queried.
unsigned getAddressSpaceForPseudoSourceKind (unsigned Kind) const override
getAddressSpaceForPseudoSourceKind - Given the kind of memory (e.g.
Public Member Functions inherited from llvm::LLVMTargetMachine
bool addPassesToEmitFile (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, bool DisableVerify=true, MachineModuleInfoWrapperPass *MMIWP=nullptr) override
Add passes to the specified pass manager to get the specified file emitted.
virtual Error buildCodeGenPipeline (ModulePassManager &, MachineFunctionPassManager &, MachineFunctionAnalysisManager &, raw_pwrite_stream &, raw_pwrite_stream *, CodeGenFileType, CGPassBuilderOption, PassInstrumentationCallbacks *)
virtual std::pair< StringRef, bool > getPassNameFromLegacyName (StringRef)
bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_pwrite_stream &Out, bool DisableVerify=true) override
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
bool addAsmPrinter (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Context)
Adds an AsmPrinter pass to the pipeline that prints assembly or machine code from the MI representation.
Expected< std::unique_ptr< MCStreamer > > createMCStreamer (raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Ctx)
virtual bool usesPhysRegsForValues () const
True if the target uses physical regs (as nearly all targets do).
virtual bool useIPRA () const
True if the target wants to use interprocedural register allocation by default.
virtual int unqualifiedInlineAsmVariant () const
The default variant to use in unqualified asm instructions.
Public Member Functions inherited from llvm::TargetMachine
TargetMachine (const TargetMachine &)=delete
void operator= (const TargetMachine &)=delete
virtual ~TargetMachine ()
const Target & getTarget () const
const Triple & getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
void setTargetFeatureString (StringRef FS)
virtual yaml::MachineFunctionInfo * createDefaultFuncInfoYAML () const
Allocate and return a default initialized instance of the YAML representation for the MachineFunctionInfo.
virtual yaml::MachineFunctionInfo * convertFuncInfoToYAML (const MachineFunction &MF) const
Allocate and initialize an instance of the YAML representation of the MachineFunctionInfo.
virtual bool parseMachineFunctionInfo (const yaml::MachineFunctionInfo &, PerFunctionMIParsingState &PFS, SMDiagnostic &Error, SMRange &SourceRange) const
Parse out the target's MachineFunctionInfo from the YAML reprsentation.
template<typename STC >
const STC & getSubtarget (const Function &F) const
This method returns a pointer to the specified type of TargetSubtargetInfo.
const DataLayout createDataLayout () const
Create a DataLayout.
bool isCompatibleDataLayout (const DataLayout &Candidate) const
Test if a DataLayout if compatible with the CodeGen for this target.
unsigned getPointerSize (unsigned AS) const
Get the pointer size for this target.
unsigned getPointerSizeInBits (unsigned AS) const
unsigned getProgramPointerSize () const
unsigned getAllocaPointerSize () const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
Return target specific asm information.
const MCRegisterInfo * getMCRegisterInfo () const
const MCInstrInfo * getMCInstrInfo () const
const MCSubtargetInfo * getMCSubtargetInfo () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
If intrinsic information is available, return it. If not, return null.
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
Returns the code generation relocation model.
CodeModel::Model getCodeModel () const
Returns the code model.
void setCodeModel (CodeModel::Model CM)
Set the code model.
bool isPositionIndependent () const
bool shouldAssumeDSOLocal (const Module &M, const GlobalValue *GV) const
bool useEmulatedTLS () const
Returns true if this target uses emulated TLS.
TLSModel::Model getTLSModel (const GlobalValue *GV) const
Returns the TLS model which should be used for the given global variable.
CodeGenOpt::Level getOptLevel () const
Returns the optimization level: None, Less, Default, or Aggressive.
void setOptLevel (CodeGenOpt::Level Level)
Overrides the optimization level.
void setFastISel (bool Enable)
bool getO0WantsFastISel ()
void setO0WantsFastISel (bool Enable)
void setGlobalISel (bool Enable)
void setGlobalISelAbort (GlobalISelAbortMode Mode)
void setMachineOutliner (bool Enable)
void setSupportsDefaultOutlining (bool Enable)
void setSupportsDebugEntryValues (bool Enable)
void setCFIFixup (bool Enable)
bool getAIXExtendedAltivecABI () const
bool getUniqueSectionNames () const
bool getUniqueBasicBlockSectionNames () const
Return true if unique basic block section names must be generated.
bool getDataSections () const
Return true if data objects should be emitted into their own section, corresponds to -fdata-sections.
bool getFunctionSections () const
Return true if functions should be emitted into their own section, corresponding to -ffunction-sections.
bool getIgnoreXCOFFVisibility () const
Return true if visibility attribute should not be emitted in XCOFF, corresponding to -mignore-xcoff-visibility.
bool getXCOFFTracebackTable () const
Return true if XCOFF traceback table should be emitted, corresponding to -xcoff-traceback-table.
llvm::BasicBlockSection getBBSectionsType () const
If basic blocks should be emitted into their own section, corresponding to -fbasic-block-sections.
const MemoryBuffer * getBBSectionsFuncListBuf () const
Get the list of functions and basic block ids that need unique sections.
void setPGOOption (Optional< PGOOptions > PGOOpt)
const Optional< PGOOptions > & getPGOOption () const
TargetIRAnalysis getTargetIRAnalysis () const
Get a TargetIRAnalysis appropriate for the target.
virtual bool targetSchedulesPostRAScheduling () const
True if subtarget inserts the final scheduling pass on its own.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV) const
virtual unsigned getSjLjDataSize () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::AMDGPUTargetMachine
static int64_t getNullPointerValue (unsigned AddrSpace)
Get the integer value of a null pointer in the given address space.
Static Public Member Functions inherited from llvm::TargetMachine
static std::pair< int, int > parseBinutilsVersion (StringRef Version)
Public Attributes inherited from llvm::TargetMachine
const TargetOptions DefaultOptions
TargetOptions Options
Static Public Attributes inherited from llvm::AMDGPUTargetMachine
static bool EnableLateStructurizeCFG = false
static bool EnableFunctionCalls = false
static bool EnableLowerModuleLDS = true
Static Public Attributes inherited from llvm::TargetMachine
static constexpr unsigned DefaultSjLjDataSize = 32
The integer bit size to use for SjLj based exception handling.
Protected Member Functions inherited from llvm::AMDGPUTargetMachine
StringRef getGPUName (const Function &F) const
StringRef getFeatureString (const Function &F) const
Protected Member Functions inherited from llvm::LLVMTargetMachine
LLVMTargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes inherited from llvm::AMDGPUTargetMachine
std::unique_ptr< TargetLoweringObjectFile > TLOF
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
The Target that this machine was created for.
const DataLayout DL
DataLayout for the target: keep ABI type size and alignment.
Triple TargetTriple
Triple string, CPU name, and target feature strings the TargetMachine instance is created with.
std::string TargetCPU
std::string TargetFS
Reloc::Model RM = Reloc::Static
CodeModel::Model CMModel = CodeModel::Small
CodeGenOpt::Level OptLevel = CodeGenOpt::Default
std::unique_ptr< const MCAsmInfo > AsmInfo
Contains target specific asm information.
std::unique_ptr< const MCRegisterInfo > MRI
std::unique_ptr< const MCInstrInfo > MII
std::unique_ptr< const MCSubtargetInfo > STI
unsigned RequireStructuredCFG: 1
unsigned O0WantsFastISel: 1
Optional< PGOOptions > PGOOption = None
Detailed Description
Definition at line 27 of file R600TargetMachine.h.
Constructor & Destructor Documentation
R600TargetMachine()
R600TargetMachine::R600TargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, TargetOptions Options, Optional< Reloc::Model > RM, Optional< CodeModel::Model > CM, CodeGenOpt::Level OL, bool JIT)
Definition at line 50 of file R600TargetMachine.cpp.
References EnableAMDGPUFunctionCallsOpt, llvm::AMDGPUTargetMachine::EnableFunctionCalls, and llvm::TargetMachine::setRequiresStructuredCFG().
Member Function Documentation
createPassConfig()
TargetPassConfig * R600TargetMachine::createPassConfig (PassManagerBase & PM) override virtual
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 141 of file R600TargetMachine.cpp.
getSubtargetImpl()
const TargetSubtargetInfo * R600TargetMachine::getSubtargetImpl (const Function &) const override virtual
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Implements llvm::AMDGPUTargetMachine.
Definition at line 66 of file R600TargetMachine.cpp.
References F, llvm::AMDGPUTargetMachine::getFeatureString(), llvm::AMDGPUTargetMachine::getGPUName(), I, llvm::TargetMachine::resetTargetOptions(), and llvm::TargetMachine::TargetTriple.
getTargetTransformInfo()
TargetTransformInfo R600TargetMachine::getTargetTransformInfo (const Function & F) const override virtual
Get a TargetTransformInfo implementation for the target.
The TTI returned uses the common code generator to answer queries about the IR.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 86 of file R600TargetMachine.cpp.
References F.
isMachineVerifierClean()
bool llvm::R600TargetMachine::isMachineVerifierClean () const inline override virtual
Returns true if the target is expected to pass all machine verifier checks.
This is a stopgap measure to fix targets one by one. We will remove this at some point and always enable the verifier when EXPENSIVE_CHECKS is enabled.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 43 of file R600TargetMachine.h.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/R600TargetMachine.h
lib/Target/AMDGPU/R600TargetMachine.cpp