LLVM: llvm::AppleAccelTableOffsetData Class Reference
llvm::AppleAccelTableOffsetData Class Reference
Accelerator table data implementation for simple Apple accelerator tables with just a DIE reference.
#include "llvm/CodeGen/AccelTable.h"
Public Member Functions
AppleAccelTableOffsetData (const DIE &D)
void emit (AsmPrinter *Asm) const override
void print (raw_ostream &OS) const override
Public Member Functions inherited from llvm::AccelTableData
virtual ~AccelTableData ()=default
bool operator< (const AccelTableData &Other) const
Static Public Attributes
static constexpr Atom Atoms []
Protected Member Functions
uint64_t order () const override
Protected Attributes
const DIE & Die
Additional Inherited Members
Static Public Member Functions inherited from llvm::AppleAccelTableData
static uint32_t hash (StringRef Buffer)
Detailed Description
Accelerator table data implementation for simple Apple accelerator tables with just a DIE reference.
Definition at line 320 of file AccelTable.h.
Constructor & Destructor Documentation
AppleAccelTableOffsetData()
llvm::AppleAccelTableOffsetData::AppleAccelTableOffsetData (const DIE & D) inline
Definition at line 322 of file AccelTable.h.
Member Function Documentation
emit()
void AppleAccelTableOffsetData::emit (AsmPrinter * Asm) const override virtual
Implements llvm::AppleAccelTableData.
Reimplemented in llvm::AppleAccelTableTypeData.
Definition at line 589 of file AccelTable.cpp.
References assert(), Die, and llvm::DIE::getDebugSectionOffset().
order()
uint64_t llvm::AppleAccelTableOffsetData::order () const inline override protected virtual
Implements llvm::AccelTableData.
Definition at line 333 of file AccelTable.h.
References Die, and llvm::DIE::getOffset().
print()
void AppleAccelTableOffsetData::print (raw_ostream & OS) const override virtual
Implements llvm::AccelTableData.
Reimplemented in llvm::AppleAccelTableTypeData.
Definition at line 689 of file AccelTable.cpp.
Member Data Documentation
Atoms
constexpr AppleAccelTableData::Atom AppleAccelTableOffsetData::Atoms static constexpr
Initial value:
= {
      Atom(dwarf::DW_ATOM_die_offset, dwarf::DW_FORM_data4)}
Definition at line 326 of file AccelTable.h.
Die
const DIE& llvm::AppleAccelTableOffsetData::Die protected
Definition at line 335 of file AccelTable.h.
Referenced by emit(), llvm::AppleAccelTableTypeData::emit(), and order().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/AccelTable.h
lib/CodeGen/AsmPrinter/AccelTable.cpp