LLVM: llvm::sampleprof::ProfileSymbolList Class Reference
llvm::sampleprof::ProfileSymbolList Class Reference
ProfileSymbolList records the list of function symbols shown up in the binary used to generate the profile.
#include "llvm/ProfileData/SampleProf.h"
Public Member Functions
void add (StringRef Name, bool copy=false)
copy indicates whether we need to copy the underlying memory for the input Name.
bool contains (StringRef Name)
void merge (const ProfileSymbolList &List)
unsigned size ()
void setToCompress (bool TC)
bool toCompress ()
std::error_code read (const uint8_t *Data, uint64_t ListSize)
std::error_code write (raw_ostream &OS)
void dump (raw_ostream &OS=dbgs()) const
Detailed Description
ProfileSymbolList records the list of function symbols shown up in the binary used to generate the profile.
It is useful to to discriminate a function being so cold as not to shown up in the profile and a function newly added.
Definition at line 1280 of file SampleProf.h.
Member Function Documentation
add()
void llvm::sampleprof::ProfileSymbolList::add (StringRef Name, bool copy = false) inline
copy indicates whether we need to copy the underlying memory for the input Name.
Definition at line 1284 of file SampleProf.h.
References llvm::copy(), and Name.
Referenced by merge(), and read().
contains()
bool llvm::sampleprof::ProfileSymbolList::contains (StringRef Name) inline
Definition at line 1292 of file SampleProf.h.
References Name.
dump()
void ProfileSymbolList::dump (raw_ostream & OS = dbgs()) const
Definition at line 455 of file SampleProf.cpp.
References llvm::sort().
merge()
void llvm::sampleprof::ProfileSymbolList::merge (const ProfileSymbolList & List) inline
Definition at line 1294 of file SampleProf.h.
References add(), and llvm::List.
read()
std::error_code ProfileSymbolList::read (const uint8_t * Data, uint64_t ListSize)
Definition at line 326 of file SampleProf.cpp.
References add(), llvm::Data, llvm::malformed, ProfileSymbolListCutOff, Size, and llvm::success.
setToCompress()
void llvm::sampleprof::ProfileSymbolList::setToCompress (bool TC) inline
Definition at line 1301 of file SampleProf.h.
size()
unsigned llvm::sampleprof::ProfileSymbolList::size () inline
Definition at line 1299 of file SampleProf.h.
Referenced by llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeProfileSymbolListSection().
toCompress()
bool llvm::sampleprof::ProfileSymbolList::toCompress () inline
Definition at line 1302 of file SampleProf.h.
Referenced by llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeOneSection().
write()
std::error_code ProfileSymbolList::write (raw_ostream & OS)
Definition at line 439 of file SampleProf.cpp.
References llvm::sort(), and llvm::success.
Referenced by llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeProfileSymbolListSection().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProf.h
lib/ProfileData/SampleProf.cpp