LLVM: llvm::pdb::PDBStringTableBuilder Class Reference
llvm::pdb::PDBStringTableBuilder Class Reference
#include "llvm/DebugInfo/PDB/Native/PDBStringTableBuilder.h"
Public Member Functions
uint32_t insert (StringRef S)
uint32_t getIdForString (StringRef S) const
StringRef getStringForId (uint32_t Id) const
uint32_t calculateSerializedSize () const
Error commit (BinaryStreamWriter &Writer) const
void setStrings (const codeview::DebugStringTableSubsection &Strings)
Detailed Description
Definition at line 43 of file PDBStringTableBuilder.h.
Member Function Documentation
calculateSerializedSize()
uint32_t PDBStringTableBuilder::calculateSerializedSize () const
Definition at line 140 of file PDBStringTableBuilder.cpp.
References llvm::codeview::DebugStringTableSubsection::calculateSerializedSize(), and Size.
Referenced by llvm::pdb::DbiStreamBuilder::calculateSerializedLength().
commit()
Error PDBStringTableBuilder::commit (BinaryStreamWriter & Writer) const
Definition at line 209 of file PDBStringTableBuilder.cpp.
References llvm::codeview::DebugStringTableSubsection::calculateSerializedSize(), and llvm::Error::success().
Referenced by llvm::pdb::DbiStreamBuilder::commit(), and llvm::pdb::PDBFileBuilder::commit().
getIdForString()
uint32_t PDBStringTableBuilder::getIdForString (StringRef S) const
Definition at line 50 of file PDBStringTableBuilder.cpp.
References llvm::codeview::DebugStringTableSubsection::getIdForString().
Referenced by llvm::pdb::StringTableHashTraits::hashLookupKey().
getStringForId()
StringRef PDBStringTableBuilder::getStringForId (uint32_t Id) const
Definition at line 54 of file PDBStringTableBuilder.cpp.
References llvm::codeview::DebugStringTableSubsection::getStringForId().
Referenced by llvm::pdb::StringTableHashTraits::storageKeyToLookupKey().
insert()
uint32_t PDBStringTableBuilder::insert (StringRef S)
Definition at line 46 of file PDBStringTableBuilder.cpp.
References llvm::codeview::DebugStringTableSubsection::insert().
Referenced by llvm::pdb::DbiStreamBuilder::addECName(), llvm::pdb::PDBFileBuilder::addInjectedSource(), and llvm::pdb::StringTableHashTraits::lookupKeyToStorageKey().
setStrings()
void PDBStringTableBuilder::setStrings (const codeview::DebugStringTableSubsection & Strings)
Definition at line 149 of file PDBStringTableBuilder.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/PDBStringTableBuilder.h
lib/DebugInfo/PDB/Native/PDBStringTableBuilder.cpp