LLVM: llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager Class Reference
llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager Class Reference
Simple page-based allocator.
#include "llvm/ExecutionEngine/Orc/TargetProcess/SimpleExecutorMemoryManager.h"
Public Member Functions
virtual ~SimpleExecutorMemoryManager ()
Expected< ExecutorAddr > allocate (uint64_t Size)
Error finalize (tpctypes::FinalizeRequest &FR)
Error deallocate (const std::vector< ExecutorAddr > &Bases)
Error shutdown () override
void addBootstrapSymbols (StringMap< ExecutorAddr > &M) override
Public Member Functions inherited from llvm::orc::ExecutorBootstrapService
virtual ~ExecutorBootstrapService ()
Detailed Description
Simple page-based allocator.
Definition at line 32 of file SimpleExecutorMemoryManager.h.
Constructor & Destructor Documentation
~SimpleExecutorMemoryManager()
llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::~SimpleExecutorMemoryManager () virtual
Definition at line 20 of file SimpleExecutorMemoryManager.cpp.
References assert(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty().
Member Function Documentation
addBootstrapSymbols()
void llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::addBootstrapSymbols (StringMap< ExecutorAddr > & M) override virtual
Implements llvm::orc::ExecutorBootstrapService.
Definition at line 200 of file SimpleExecutorMemoryManager.cpp.
References llvm::orc::ExecutorAddr::fromPtr(), llvm::orc::rt::SimpleExecutorMemoryManagerDeallocateWrapperName, llvm::orc::rt::SimpleExecutorMemoryManagerFinalizeWrapperName, llvm::orc::rt::SimpleExecutorMemoryManagerInstanceName, and llvm::orc::rt::SimpleExecutorMemoryManagerReserveWrapperName.
allocate()
Expected< ExecutorAddr > llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::allocate (uint64_t Size)
Definition at line 24 of file SimpleExecutorMemoryManager.cpp.
References llvm::sys::Memory::allocateMappedMemory(), assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::errorCodeToError(), llvm::orc::ExecutorAddr::fromPtr(), llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, and Size.
deallocate()
Error llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::deallocate (const std::vector< ExecutorAddr > & Bases)
Definition at line 151 of file SimpleExecutorMemoryManager.cpp.
References llvm::sampleprof::Base, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::formatv(), I, llvm::inconvertibleErrorCode(), llvm::joinErrors(), P, and llvm::Error::success().
finalize()
Error llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::finalize (tpctypes::FinalizeRequest & FR)
Definition at line 36 of file SimpleExecutorMemoryManager.cpp.
References assert(), llvm::sampleprof::Base, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::errorCodeToError(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::formatv(), llvm::orc::tpctypes::fromWireProtectionFlags(), I, llvm::inconvertibleErrorCode(), llvm::sys::Memory::InvalidateInstructionCache(), llvm::joinErrors(), LLVM_UNLIKELY, llvm::sys::Memory::protectMappedMemory(), llvm::sys::Memory::releaseMappedMemory(), llvm::Error::success(), and llvm::orc::tpctypes::WPF_Exec.
shutdown()
Error llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::shutdown () override virtual
Implements llvm::orc::ExecutorBootstrapService.
Definition at line 186 of file SimpleExecutorMemoryManager.cpp.
References llvm::joinErrors(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/TargetProcess/SimpleExecutorMemoryManager.h
lib/ExecutionEngine/Orc/TargetProcess/SimpleExecutorMemoryManager.cpp