LLVM: llvm::ModuleAddressSanitizerPass Class Reference
llvm::ModuleAddressSanitizerPass Class Reference
Public interface to the address sanitizer module pass for instrumenting code to check for various memory errors.
#include "llvm/Transforms/Instrumentation/AddressSanitizer.h"
Public Member Functions
ModuleAddressSanitizerPass (const AddressSanitizerOptions &Options, bool UseGlobalGC=true, bool UseOdrIndicator=false, AsanDtorKind DestructorKind=AsanDtorKind::Global)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Member Functions inherited from llvm::PassInfoMixin< ModuleAddressSanitizerPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< ModuleAddressSanitizerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Public interface to the address sanitizer module pass for instrumenting code to check for various memory errors.
This adds 'asan.module_ctor' to 'llvm.global_ctors'. This pass may also run intependently of the function address sanitizer.
Definition at line 36 of file AddressSanitizer.h.
Constructor & Destructor Documentation
ModuleAddressSanitizerPass()
ModuleAddressSanitizerPass::ModuleAddressSanitizerPass (const AddressSanitizerOptions & Options, bool UseGlobalGC = true, bool UseOdrIndicator = false, AsanDtorKind DestructorKind = AsanDtorKind::Global)
Definition at line 1123 of file AddressSanitizer.cpp.
Member Function Documentation
isRequired()
static bool llvm::ModuleAddressSanitizerPass::isRequired () inline static
Definition at line 46 of file AddressSanitizer.h.
printPipeline()
void ModuleAddressSanitizerPass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 1113 of file AddressSanitizer.cpp.
References llvm::AddressSanitizerOptions::CompileKernel, and printPipeline().
Referenced by printPipeline().
run()
PreservedAnalyses ModuleAddressSanitizerPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 1129 of file AddressSanitizer.cpp.
References llvm::PreservedAnalyses::all(), ClUseStackSafety, llvm::AddressSanitizerOptions::CompileKernel, F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), MAM, Modified, llvm::PreservedAnalyses::none(), llvm::AddressSanitizerOptions::Recover, llvm::AddressSanitizerOptions::UseAfterReturn, and llvm::AddressSanitizerOptions::UseAfterScope.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/AddressSanitizer.h
lib/Transforms/Instrumentation/AddressSanitizer.cpp