LLVM: llvm::AliasSet::iterator Class Reference
llvm::AliasSet::iterator Class Reference
Define an iterator for alias sets... this is just a forward iterator.
#include "llvm/Analysis/AliasSetTracker.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = PointerRec
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
iterator (PointerRec *CN=nullptr)
bool operator== (const iterator &x) const
bool operator!= (const iterator &x) const
value_type & operator* () const
value_type * operator-> () const
Value * getPointer () const
LocationSize getSize () const
AAMDNodes getAAInfo () const
iterator & operator++ ()
iterator operator++ (int)
Detailed Description
Define an iterator for alias sets... this is just a forward iterator.
Definition at line 228 of file AliasSetTracker.h.
Member Typedef Documentation
difference_type
using llvm::AliasSet::iterator::difference_type = std::ptrdiff_t
Definition at line 234 of file AliasSetTracker.h.
iterator_category
using llvm::AliasSet::iterator::iterator_category = std::forward_iterator_tag
Definition at line 232 of file AliasSetTracker.h.
pointer
using llvm::AliasSet::iterator::pointer = value_type *
Definition at line 235 of file AliasSetTracker.h.
reference
using llvm::AliasSet::iterator::reference = value_type &
Definition at line 236 of file AliasSetTracker.h.
value_type
using llvm::AliasSet::iterator::value_type = PointerRec
Definition at line 233 of file AliasSetTracker.h.
Constructor & Destructor Documentation
iterator()
llvm::AliasSet::iterator::iterator (PointerRec * CN = nullptr) inline explicit
Definition at line 238 of file AliasSetTracker.h.
Member Function Documentation
getAAInfo()
AAMDNodes llvm::AliasSet::iterator::getAAInfo () const inline
Definition at line 253 of file AliasSetTracker.h.
getPointer()
Value * llvm::AliasSet::iterator::getPointer () const inline
Definition at line 251 of file AliasSetTracker.h.
getSize()
LocationSize llvm::AliasSet::iterator::getSize () const inline
Definition at line 252 of file AliasSetTracker.h.
operator!=()
bool llvm::AliasSet::iterator::operator!= (const iterator & x) const inline
Definition at line 243 of file AliasSetTracker.h.
References operator==().
operator*()
value_type & llvm::AliasSet::iterator::operator* () const inline
Definition at line 245 of file AliasSetTracker.h.
References assert().
Referenced by operator->().
operator++() [1/2]
iterator & llvm::AliasSet::iterator::operator++ () inline
Definition at line 255 of file AliasSetTracker.h.
References assert().
operator++() [2/2]
iterator llvm::AliasSet::iterator::operator++ (int) inline
Definition at line 260 of file AliasSetTracker.h.
References llvm::ilist_node_impl< OptionsT >::ilist_node_impl().
operator->()
value_type * llvm::AliasSet::iterator::operator-> () const inline
Definition at line 249 of file AliasSetTracker.h.
References operator*().
operator==()
bool llvm::AliasSet::iterator::operator== (const iterator & x) const inline
Definition at line 240 of file AliasSetTracker.h.
Referenced by operator!=().
The documentation for this class was generated from the following file:
include/llvm/Analysis/AliasSetTracker.h