LLVM: llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator Class Reference
llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator Class Reference
#include "Target/X86/ImmutableGraph.h"
Public Member Functions
iterator (const EdgeSet &Set, size_type Begin)
iterator operator++ (int)
iterator & operator++ ()
Edge * operator* () const
bool operator== (const iterator &other) const
bool operator!= (const iterator &other) const
Detailed Description
template<typename NodeValueT, typename EdgeValueT>
class llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator
Definition at line 251 of file ImmutableGraph.h.
Constructor & Destructor Documentation
iterator()
template<typename NodeValueT , typename EdgeValueT > llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator::iterator (const EdgeSet & Set, size_type Begin) inline
Definition at line 261 of file ImmutableGraph.h.
Member Function Documentation
operator!=()
template<typename NodeValueT , typename EdgeValueT > bool llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator::operator!= (const iterator & other) const inline
Definition at line 280 of file ImmutableGraph.h.
operator*()
template<typename NodeValueT , typename EdgeValueT > Edge * llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator::operator* () const inline
Definition at line 272 of file ImmutableGraph.h.
References assert(), and llvm::ImmutableGraph< NodeValueT, EdgeValueT >::edges_begin().
operator++() [1/2]
template<typename NodeValueT , typename EdgeValueT > iterator & llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator::operator++ () inline
Definition at line 268 of file ImmutableGraph.h.
operator++() [2/2]
template<typename NodeValueT , typename EdgeValueT > iterator llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator::operator++ (int) inline
Definition at line 263 of file ImmutableGraph.h.
operator==()
template<typename NodeValueT , typename EdgeValueT > bool llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::iterator::operator== (const iterator & other) const inline
Definition at line 276 of file ImmutableGraph.h.
References assert().
The documentation for this class was generated from the following file:
lib/Target/X86/ImmutableGraph.h