LLVM: llvm::ToolOutputFile Class Reference
llvm::ToolOutputFile Class Reference
This class contains a raw_fd_ostream and adds a few extra features commonly needed for compiler-like tool output files:
#include "llvm/Support/ToolOutputFile.h"
Public Member Functions
ToolOutputFile (StringRef Filename, std::error_code &EC, sys::fs::OpenFlags Flags)
This constructor's arguments are passed to raw_fd_ostream's constructor.
ToolOutputFile (StringRef Filename, int FD)
raw_fd_ostream & os ()
Return the contained raw_fd_ostream.
StringRef getFilename ()
Return the filename initialized with.
void keep ()
Indicate that the tool's job wrt this output file has been successful and the file should not be deleted.
const std::string & outputFilename ()
Detailed Description
This class contains a raw_fd_ostream and adds a few extra features commonly needed for compiler-like tool output files:
The file is automatically deleted if the process is killed.
The file is automatically deleted when the ToolOutputFile object is destroyed unless the client calls keep().
Definition at line 26 of file ToolOutputFile.h.
Constructor & Destructor Documentation
ToolOutputFile() [1/2]
ToolOutputFile::ToolOutputFile (StringRef Filename, std::error_code & EC, sys::fs::OpenFlags Flags)
This constructor's arguments are passed to raw_fd_ostream's constructor.
Definition at line 40 of file ToolOutputFile.cpp.
References isStdout(), and llvm::outs().
ToolOutputFile() [2/2]
ToolOutputFile::ToolOutputFile (StringRef Filename, int FD)
Definition at line 55 of file ToolOutputFile.cpp.
Member Function Documentation
getFilename()
StringRef llvm::ToolOutputFile::getFilename () inline
Return the filename initialized with.
Definition at line 63 of file ToolOutputFile.h.
keep()
void llvm::ToolOutputFile::keep () inline
Indicate that the tool's job wrt this output file has been successful and the file should not be deleted.
Definition at line 67 of file ToolOutputFile.h.
Referenced by llvm::TableGenMain(), and llvm::LTOCodeGenerator::writeMergedModules().
os()
raw_fd_ostream & llvm::ToolOutputFile::os () inline
Return the contained raw_fd_ostream.
Definition at line 60 of file ToolOutputFile.h.
Referenced by llvm::TableGenMain(), and llvm::LTOCodeGenerator::writeMergedModules().
outputFilename()
const std::string & llvm::ToolOutputFile::outputFilename () inline
Definition at line 69 of file ToolOutputFile.h.
The documentation for this class was generated from the following files:
include/llvm/Support/ToolOutputFile.h
lib/Support/ToolOutputFile.cpp