LLVM: llvm::DWARFAbbreviationDeclaration Class Reference
llvm::DWARFAbbreviationDeclaration Class Reference
#include "llvm/DebugInfo/DWARF/DWARFAbbreviationDeclaration.h"
Classes
struct AttributeSpec
Public Types
using AttributeSpecVector = SmallVector<AttributeSpec, 8>
using attr_iterator_range
Public Member Functions
DWARFAbbreviationDeclaration ()
uint32_t getCode () const
uint8_t getCodeByteSize () const
dwarf::Tag getTag () const
bool hasChildren () const
attr_iterator_range attributes () const
dwarf::Form getFormByIndex (uint32_t idx) const
size_t getNumAttributes () const
dwarf::Attribute getAttrByIndex (uint32_t idx) const
bool getAttrIsImplicitConstByIndex (uint32_t idx) const
int64_t getAttrImplicitConstValueByIndex (uint32_t idx) const
Optional< uint32_t > findAttributeIndex (dwarf::Attribute attr) const
Get the index of the specified attribute.
Optional< DWARFFormValue > getAttributeValue (const uint64_t DIEOffset, const dwarf::Attribute Attr, const DWARFUnit &U) const
Extract a DWARF form value from a DIE specified by DIE offset.
uint64_t getAttributeOffsetFromIndex (uint32_t AttrIndex, uint64_t DIEOffset, const DWARFUnit &U) const
Compute an offset from a DIE specified by DIE offset and attribute index.
Optional< DWARFFormValue > getAttributeValueFromOffset (uint32_t AttrIndex, uint64_t Offset, const DWARFUnit &U) const
Extract a DWARF form value from a DIE speccified by attribute index and its offset.
bool extract (DataExtractor Data, uint64_t *OffsetPtr)
void dump (raw_ostream &OS) const
Optional< size_t > getFixedAttributesByteSize (const DWARFUnit &U) const
Detailed Description
Definition at line 27 of file DWARFAbbreviationDeclaration.h.
Member Typedef Documentation
attr_iterator_range
using llvm::DWARFAbbreviationDeclaration::attr_iterator_range
Initial value:
      iterator_range<AttributeSpecVector::const_iterator>
Definition at line 93 of file DWARFAbbreviationDeclaration.h.
AttributeSpecVector
using llvm::DWARFAbbreviationDeclaration::AttributeSpecVector = SmallVector<AttributeSpec, 8>
Definition at line 84 of file DWARFAbbreviationDeclaration.h.
Constructor & Destructor Documentation
DWARFAbbreviationDeclaration()
DWARFAbbreviationDeclaration::DWARFAbbreviationDeclaration ()
Definition at line 35 of file DWARFAbbreviationDeclaration.cpp.
Member Function Documentation
attributes()
attr_iterator_range llvm::DWARFAbbreviationDeclaration::attributes () const inline
Definition at line 96 of file DWARFAbbreviationDeclaration.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::DWARFDebugInfoEntry::extractFast().
dump()
void DWARFAbbreviationDeclaration::dump (raw_ostream & OS) const
Definition at line 128 of file DWARFAbbreviationDeclaration.cpp.
References llvm::formatv(), getCode(), getTag(), and hasChildren().
extract()
bool DWARFAbbreviationDeclaration::extract (DataExtractor Data, uint64_t * OffsetPtr)
Definition at line 40 of file DWARFAbbreviationDeclaration.cpp.
References A, llvm::Data, llvm::dwarf::DW_CHILDREN_yes, F, llvm::dwarf::getFixedFormByteSize(), Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Optional< T >::reset().
findAttributeIndex()
Optional< uint32_t > DWARFAbbreviationDeclaration::findAttributeIndex (dwarf::Attribute attr) const
Get the index of the specified attribute.
Searches the this abbreviation declaration for the index of the specified attribute.
Parameters
attr DWARF attribute to search for.
Returns
Optional index of the attribute if found, None otherwise.
Definition at line 142 of file DWARFAbbreviationDeclaration.cpp.
References llvm::None, and llvm::SmallVectorBase< Size_T >::size().
Referenced by getAttributeValue().
getAttrByIndex()
dwarf::Attribute llvm::DWARFAbbreviationDeclaration::getAttrByIndex (uint32_t idx) const inline
Definition at line 109 of file DWARFAbbreviationDeclaration.h.
References assert(), and llvm::SmallVectorBase< Size_T >::size().
getAttributeOffsetFromIndex()
uint64_t DWARFAbbreviationDeclaration::getAttributeOffsetFromIndex (uint32_t AttrIndex, uint64_t DIEOffset, const DWARFUnit & U) const
Compute an offset from a DIE specified by DIE offset and attribute index.
Parameters
AttrIndex an index of DWARF attribute.
DIEOffset the DIE offset that points to the ULEB128 abbreviation code in the .debug_info data.
U the DWARFUnit the contains the DIE.
Returns
an offset of the attribute.
Definition at line 150 of file DWARFAbbreviationDeclaration.cpp.
References Offset, and llvm::DWARFFormValue::skipValue().
Referenced by getAttributeValue().
getAttributeValue()
Optional< DWARFFormValue > DWARFAbbreviationDeclaration::getAttributeValue (const uint64_t DIEOffset, const dwarf::Attribute Attr, const DWARFUnit & U) const
Extract a DWARF form value from a DIE specified by DIE offset.
Extract an attribute value for a DWARFUnit given the DIE offset and the attribute.
Parameters
DIEOffset the DIE offset that points to the ULEB128 abbreviation code in the .debug_info data.
Attr DWARF attribute to search for.
U the DWARFUnit the contains the DIE.
Returns
Optional DWARF form value if the attribute was extracted.
Definition at line 187 of file DWARFAbbreviationDeclaration.cpp.
References findAttributeIndex(), getAttributeOffsetFromIndex(), getAttributeValueFromOffset(), llvm::None, and Offset.
getAttributeValueFromOffset()
Optional< DWARFFormValue > DWARFAbbreviationDeclaration::getAttributeValueFromOffset (uint32_t AttrIndex, uint64_t Offset, const DWARFUnit & U) const
Extract a DWARF form value from a DIE speccified by attribute index and its offset.
Parameters
AttrIndex an index of DWARF attribute.
Offset offset of the attribute.
U the DWARFUnit the contains the DIE.
Returns
Optional DWARF form value if the attribute was extracted.
Definition at line 168 of file DWARFAbbreviationDeclaration.cpp.
References assert(), llvm::DWARFFormValue::createFromSValue(), llvm::DWARFFormValue::extractValue(), llvm::DWARFAbbreviationDeclaration::AttributeSpec::Form, llvm::DWARFAbbreviationDeclaration::AttributeSpec::getImplicitConstValue(), llvm::DWARFAbbreviationDeclaration::AttributeSpec::isImplicitConst(), llvm::None, Offset, and llvm::SmallVectorBase< Size_T >::size().
Referenced by getAttributeValue().
getAttrImplicitConstValueByIndex()
int64_t llvm::DWARFAbbreviationDeclaration::getAttrImplicitConstValueByIndex (uint32_t idx) const inline
Definition at line 119 of file DWARFAbbreviationDeclaration.h.
References assert(), and llvm::SmallVectorBase< Size_T >::size().
getAttrIsImplicitConstByIndex()
bool llvm::DWARFAbbreviationDeclaration::getAttrIsImplicitConstByIndex (uint32_t idx) const inline
Definition at line 114 of file DWARFAbbreviationDeclaration.h.
References assert(), and llvm::SmallVectorBase< Size_T >::size().
getCode()
uint32_t llvm::DWARFAbbreviationDeclaration::getCode () const inline
Definition at line 88 of file DWARFAbbreviationDeclaration.h.
Referenced by dump().
getCodeByteSize()
uint8_t llvm::DWARFAbbreviationDeclaration::getCodeByteSize () const inline
Definition at line 89 of file DWARFAbbreviationDeclaration.h.
getFixedAttributesByteSize()
Optional< size_t > DWARFAbbreviationDeclaration::getFixedAttributesByteSize (const DWARFUnit & U) const
Definition at line 226 of file DWARFAbbreviationDeclaration.cpp.
References llvm::None.
Referenced by llvm::DWARFDebugInfoEntry::extractFast().
getFormByIndex()
dwarf::Form llvm::DWARFAbbreviationDeclaration::getFormByIndex (uint32_t idx) const inline
Definition at line 100 of file DWARFAbbreviationDeclaration.h.
References assert(), and llvm::SmallVectorBase< Size_T >::size().
getNumAttributes()
size_t llvm::DWARFAbbreviationDeclaration::getNumAttributes () const inline
Definition at line 105 of file DWARFAbbreviationDeclaration.h.
References llvm::SmallVectorBase< Size_T >::size().
getTag()
dwarf::Tag llvm::DWARFAbbreviationDeclaration::getTag () const inline
Definition at line 90 of file DWARFAbbreviationDeclaration.h.
Referenced by dump(), and llvm::DWARFDebugInfoEntry::getTag().
hasChildren()
bool llvm::DWARFAbbreviationDeclaration::hasChildren () const inline
Definition at line 91 of file DWARFAbbreviationDeclaration.h.
Referenced by dump(), and llvm::DWARFDebugInfoEntry::hasChildren().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFAbbreviationDeclaration.h
lib/DebugInfo/DWARF/DWARFAbbreviationDeclaration.cpp