LLVM: llvm::Pattern Class Reference
llvm::Pattern Class Reference
#include "FileCheck/FileCheckImpl.h"
Classes
struct Match
struct MatchResult
struct VariableProperties
Parsing information about a variable.
Public Member Functions
Pattern (Check::FileCheckType Ty, FileCheckPatternContext *Context, Optional< size_t > Line=None)
SMLoc getLoc () const
FileCheckPatternContext * getContext () const
bool parsePattern (StringRef PatternStr, StringRef Prefix, SourceMgr &SM, const FileCheckRequest &Req)
Parses the pattern in PatternStr and initializes this Pattern instance accordingly.
MatchResult match (StringRef Buffer, const SourceMgr &SM) const
Matches the pattern string against the input buffer Buffer.
void printSubstitutions (const SourceMgr &SM, StringRef Buffer, SMRange MatchRange, FileCheckDiag::MatchType MatchTy, std::vector< FileCheckDiag > *Diags) const
Prints the value of successful substitutions.
void printFuzzyMatch (const SourceMgr &SM, StringRef Buffer, std::vector< FileCheckDiag > *Diags) const
bool hasVariable () const
void printVariableDefs (const SourceMgr &SM, FileCheckDiag::MatchType MatchTy, std::vector< FileCheckDiag > *Diags) const
Check::FileCheckType getCheckTy () const
int getCount () const
Static Public Member Functions
static bool isValidVarNameStart (char C)
static Expected< VariableProperties > parseVariable (StringRef &Str, const SourceMgr &SM)
Parses the string at the start of Str for a variable name.
static Expected< std::unique_ptr< Expression > > parseNumericSubstitutionBlock (StringRef Expr, Optional< NumericVariable * > &DefinedNumericVariable, bool IsLegacyLineExpr, Optional< size_t > LineNumber, FileCheckPatternContext *Context, const SourceMgr &SM)
Parses Expr for a numeric substitution block at line LineNumber, or before input is parsed if LineNumber is None.
Detailed Description
Definition at line 614 of file FileCheckImpl.h.
Constructor & Destructor Documentation
Pattern()
llvm::Pattern::Pattern (Check::FileCheckType Ty, FileCheckPatternContext * Context, Optional< size_t > Line = None) inline
Definition at line 684 of file FileCheckImpl.h.
Member Function Documentation
getCheckTy()
Check::FileCheckType llvm::Pattern::getCheckTy () const inline
Definition at line 771 of file FileCheckImpl.h.
Referenced by llvm::FileCheckString::Check(), llvm::FileCheckString::CheckDag(), llvm::FileCheckString::CheckNext(), llvm::FileCheckString::CheckNot(), llvm::FileCheckString::CheckSame(), printFuzzyMatch(), printMatch(), and printNoMatch().
getContext()
FileCheckPatternContext * llvm::Pattern::getContext () const inline
Returns
the pointer to the global state for all patterns in this FileCheck instance.
Definition at line 693 of file FileCheckImpl.h.
getCount()
int llvm::Pattern::getCount () const inline
Definition at line 773 of file FileCheckImpl.h.
References llvm::Check::FileCheckType::getCount().
Referenced by llvm::FileCheckString::Check(), printMatch(), and printNoMatch().
getLoc()
SMLoc llvm::Pattern::getLoc () const inline
Returns
the location in source code.
Definition at line 689 of file FileCheckImpl.h.
Referenced by llvm::FileCheckString::CheckDag(), llvm::FileCheckString::CheckNot(), printFuzzyMatch(), printSubstitutions(), and printVariableDefs().
hasVariable()
bool llvm::Pattern::hasVariable () const inline
Definition at line 765 of file FileCheckImpl.h.
isValidVarNameStart()
bool Pattern::isValidVarNameStart (char C) static
Returns
whether C is a valid first character for a variable name.
Definition at line 437 of file FileCheck.cpp.
References llvm::CallingConv::C.
Referenced by parseVariable().
match()
Pattern::MatchResult Pattern::match (StringRef Buffer, const SourceMgr & SM) const
Matches the pattern string against the input buffer Buffer.
Returns
either (1) an error resulting in no match or (2) a match possibly with an error encountered while processing the match.
The GlobalVariableTable StringMap in the FileCheckPatternContext class instance provides the current values of FileCheck string variables and is updated if this match defines new values. Likewise, the GlobalNumericVariableTable StringMap in the same class provides the current values of FileCheck numeric variables and is updated if this match defines new numeric values.
Definition at line 1228 of file FileCheck.cpp.
References assert(), llvm::Check::CheckEmpty, llvm::Check::CheckEOF, llvm::StringRef::data(), E, llvm::StringRef::empty(), llvm::StringRef::find(), llvm::StringRef::find_insensitive(), llvm::NumericVariable::getImplicitFormat(), llvm::Substitution::getIndex(), llvm::Substitution::getResult(), llvm::handleErrors(), llvm::Regex::IgnoreCase, llvm::joinErrors(), llvm::Pattern::Match::Len, match(), llvm::Regex::Newline, llvm::StringRef::npos, llvm::Pattern::Match::Pos, llvm::NumericVariable::setValue(), llvm::StringRef::size(), and llvm::Error::success().
Referenced by llvm::FileCheckString::Check(), llvm::FileCheckString::CheckDag(), llvm::FileCheckString::CheckNot(), llvm::ifs::filterIFSSyms(), and match().
parseNumericSubstitutionBlock()
Expected< std::unique_ptr< Expression > > Pattern::parseNumericSubstitutionBlock (StringRef Expr, Optional< NumericVariable * > & DefinedNumericVariable, bool IsLegacyLineExpr, Optional< size_t > LineNumber, FileCheckPatternContext * Context, const SourceMgr & SM) static
Parses Expr for a numeric substitution block at line LineNumber, or before input is parsed if LineNumber is None.
Parameter IsLegacyLineExpr indicates whether Expr should be a legacy @LINE expression and Context points to the class instance holding the live string and numeric variables.
Returns
a pointer to the class instance representing the expression whose value must be substitued, or an error holding a diagnostic against SM if parsing fails. If substitution was successful, sets DefinedNumericVariable to point to the class representing the numeric variable defined in this numeric substitution block, or None if this block does not define any variable.
Definition at line 767 of file FileCheck.cpp.
References llvm::StringRef::consume_front(), llvm::StringRef::drop_front(), llvm::StringRef::empty(), llvm::StringRef::find(), llvm::Format, llvm::ErrorDiagnostic::get(), llvm::SMLoc::getFromPointer(), llvm::ExpressionFormat::HexLower, llvm::ExpressionFormat::HexUpper, llvm::StringRef::ltrim(), llvm::None, llvm::StringRef::npos, popFront(), llvm::StringRef::rtrim(), llvm::ExpressionFormat::Signed, SpaceChars, llvm::StringRef::substr(), llvm::StringRef::take_front(), and llvm::ExpressionFormat::Unsigned.
Referenced by llvm::FileCheckPatternContext::defineCmdlineVariables(), and parsePattern().
parsePattern()
bool Pattern::parsePattern (StringRef PatternStr, StringRef Prefix, SourceMgr & SM, const FileCheckRequest & Req)
Parses the pattern in PatternStr and initializes this Pattern instance accordingly.
Prefix provides which prefix is being matched, Req describes the global options that influence the parsing such as whitespace canonicalization, SM provides the SourceMgr used for error reports.
Returns
true in case of an error, false otherwise.
Definition at line 916 of file FileCheck.cpp.
References llvm::cantFail(), llvm::Check::CheckEmpty, llvm::Check::CheckNot, llvm::SourceMgr::DK_Error, llvm::errs(), llvm::Regex::escape(), llvm::SMLoc::getFromPointer(), llvm::FileCheckRequest::IgnoreCase, llvm::Check::FileCheckType::isLiteralMatch(), llvm::logAllUnhandledErrors(), llvm::FileCheckRequest::MatchFullLines, Name, llvm::FileCheckRequest::NoCanonicalizeWhiteSpace, llvm::StringRef::npos, parseNumericSubstitutionBlock(), parseVariable(), and llvm::SourceMgr::PrintMessage().
parseVariable()
Expected< Pattern::VariableProperties > Pattern::parseVariable (StringRef & Str, const SourceMgr & SM) static
Parses the string at the start of Str for a variable name.
Returns
a VariableProperties structure holding the variable name and whether it is the name of a pseudo variable, or an error holding a diagnostic against SM if parsing fail. If parsing was successful, also strips Str from the variable name.
Definition at line 440 of file FileCheck.cpp.
References E, llvm::ErrorDiagnostic::get(), I, isValidVarNameStart(), and Name.
Referenced by llvm::FileCheckPatternContext::defineCmdlineVariables(), and parsePattern().
printFuzzyMatch()
void Pattern::printFuzzyMatch (const SourceMgr & SM, StringRef Buffer, std::vector< FileCheckDiag > * Diags) const
Definition at line 1466 of file FileCheck.cpp.
References llvm::SourceMgr::DK_Note, getCheckTy(), getLoc(), llvm::FileCheckDiag::MatchFuzzy, llvm::StringRef::npos, llvm::SourceMgr::PrintMessage(), ProcessMatchResult(), llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by printNoMatch().
printSubstitutions()
void Pattern::printSubstitutions (const SourceMgr & SM, StringRef Buffer, SMRange MatchRange, FileCheckDiag::MatchType MatchTy, std::vector< FileCheckDiag > * Diags) const
Prints the value of successful substitutions.
Definition at line 1358 of file FileCheck.cpp.
References llvm::consumeError(), llvm::SourceMgr::DK_Note, llvm::Substitution::getFromString(), getLoc(), llvm::Substitution::getResult(), llvm::SourceMgr::PrintMessage(), llvm::SMRange::Start, llvm::raw_svector_ostream::str(), and llvm::raw_ostream::write_escaped().
Referenced by printMatch(), and printNoMatch().
printVariableDefs()
void Pattern::printVariableDefs (const SourceMgr & SM, FileCheckDiag::MatchType MatchTy, std::vector< FileCheckDiag > * Diags) const
Definition at line 1392 of file FileCheck.cpp.
References A, assert(), B, llvm::SourceMgr::DK_Note, llvm::StringMapImpl::empty(), llvm::SMLoc::getFromPointer(), getLoc(), Name, llvm::SourceMgr::PrintMessage(), llvm::sort(), and llvm::raw_svector_ostream::str().
Referenced by printMatch().
The documentation for this class was generated from the following files:
lib/FileCheck/FileCheckImpl.h
lib/FileCheck/FileCheck.cpp