LLVM: llvm::AArch64TargetStreamer Class Reference
llvm::AArch64TargetStreamer Class Reference
#include "Target/AArch64/MCTargetDesc/AArch64TargetStreamer.h"
Public Member Functions
AArch64TargetStreamer (MCStreamer &S)
~AArch64TargetStreamer () override
void finish () override
void emitConstantPools () override
const MCExpr * addConstantPoolEntry (const MCExpr *, unsigned Size, SMLoc Loc)
Callback used to implement the ldr= pseudo.
void emitCurrentConstantPool ()
Callback used to implemnt the .ltorg directive.
void emitNoteSection (unsigned Flags)
Callback used to implement the .note.gnu.property section.
virtual void emitInst (uint32_t Inst)
Callback used to implement the .inst directive.
virtual void emitDirectiveVariantPCS (MCSymbol *Symbol)
Callback used to implement the .variant_pcs directive.
virtual void emitARM64WinCFIAllocStack (unsigned Size)
virtual void emitARM64WinCFISaveR19R20X (int Offset)
virtual void emitARM64WinCFISaveFPLR (int Offset)
virtual void emitARM64WinCFISaveFPLRX (int Offset)
virtual void emitARM64WinCFISaveReg (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveRegX (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveRegP (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveRegPX (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveLRPair (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveFReg (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveFRegX (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveFRegP (unsigned Reg, int Offset)
virtual void emitARM64WinCFISaveFRegPX (unsigned Reg, int Offset)
virtual void emitARM64WinCFISetFP ()
virtual void emitARM64WinCFIAddFP (unsigned Size)
virtual void emitARM64WinCFINop ()
virtual void emitARM64WinCFISaveNext ()
virtual void emitARM64WinCFIPrologEnd ()
virtual void emitARM64WinCFIEpilogStart ()
virtual void emitARM64WinCFIEpilogEnd ()
virtual void emitARM64WinCFITrapFrame ()
virtual void emitARM64WinCFIMachineFrame ()
virtual void emitARM64WinCFIContext ()
virtual void emitARM64WinCFIClearUnwoundToCall ()
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 20 of file AArch64TargetStreamer.h.
Constructor & Destructor Documentation
AArch64TargetStreamer()
AArch64TargetStreamer::AArch64TargetStreamer (MCStreamer & S)
Definition at line 34 of file AArch64TargetStreamer.cpp.
~AArch64TargetStreamer()
AArch64TargetStreamer::~AArch64TargetStreamer () override default
Member Function Documentation
addConstantPoolEntry()
const MCExpr * AArch64TargetStreamer::addConstantPoolEntry (const MCExpr * Expr, unsigned Size, SMLoc Loc)
Callback used to implement the ldr= pseudo.
Add a new entry to the constant pool for the current section and return an MCExpr that can be used to refer to the constant pool location.
Definition at line 41 of file AArch64TargetStreamer.cpp.
References Size, and llvm::MCTargetStreamer::Streamer.
emitARM64WinCFIAddFP()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIAddFP (unsigned Size) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 60 of file AArch64TargetStreamer.h.
emitARM64WinCFIAllocStack()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIAllocStack (unsigned Size) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 46 of file AArch64TargetStreamer.h.
emitARM64WinCFIClearUnwoundToCall()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIClearUnwoundToCall () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 69 of file AArch64TargetStreamer.h.
emitARM64WinCFIContext()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIContext () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 68 of file AArch64TargetStreamer.h.
emitARM64WinCFIEpilogEnd()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIEpilogEnd () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 65 of file AArch64TargetStreamer.h.
emitARM64WinCFIEpilogStart()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIEpilogStart () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 64 of file AArch64TargetStreamer.h.
emitARM64WinCFIMachineFrame()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIMachineFrame () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 67 of file AArch64TargetStreamer.h.
emitARM64WinCFINop()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFINop () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 61 of file AArch64TargetStreamer.h.
emitARM64WinCFIPrologEnd()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFIPrologEnd () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 63 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveFPLR()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveFPLR (int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 48 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveFPLRX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveFPLRX (int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 49 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveFReg()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveFReg (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 55 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveFRegP()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveFRegP (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 57 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveFRegPX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveFRegPX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 58 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveFRegX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveFRegX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 56 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveLRPair()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveLRPair (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 54 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveNext()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveNext () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 62 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveR19R20X()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveR19R20X (int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 47 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveReg()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveReg (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 50 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveRegP()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveRegP (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 52 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveRegPX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveRegPX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 53 of file AArch64TargetStreamer.h.
emitARM64WinCFISaveRegX()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISaveRegX (unsigned Reg, int Offset) inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 51 of file AArch64TargetStreamer.h.
emitARM64WinCFISetFP()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFISetFP () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 59 of file AArch64TargetStreamer.h.
emitARM64WinCFITrapFrame()
virtual void llvm::AArch64TargetStreamer::emitARM64WinCFITrapFrame () inline virtual
Reimplemented in llvm::AArch64TargetWinCOFFStreamer.
Definition at line 66 of file AArch64TargetStreamer.h.
emitConstantPools()
void AArch64TargetStreamer::emitConstantPools () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 51 of file AArch64TargetStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
emitCurrentConstantPool()
void AArch64TargetStreamer::emitCurrentConstantPool ()
Callback used to implemnt the .ltorg directive.
Emit contents of constant pool for the current section.
Definition at line 47 of file AArch64TargetStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
emitDirectiveVariantPCS()
virtual void llvm::AArch64TargetStreamer::emitDirectiveVariantPCS (MCSymbol * Symbol) inline virtual
Callback used to implement the .variant_pcs directive.
Definition at line 44 of file AArch64TargetStreamer.h.
emitInst()
void AArch64TargetStreamer::emitInst (uint32_t Inst) virtual
Callback used to implement the .inst directive.
Definition at line 98 of file AArch64TargetStreamer.cpp.
References llvm::CallingConv::C, llvm::MCStreamer::emitBytes(), and llvm::MCTargetStreamer::getStreamer().
emitNoteSection()
void AArch64TargetStreamer::emitNoteSection (unsigned Flags)
Callback used to implement the .note.gnu.property section.
Definition at line 62 of file AArch64TargetStreamer.cpp.
References Align, llvm::MCStreamer::emitBytes(), llvm::MCStreamer::emitIntValue(), llvm::MCStreamer::emitValueToAlignment(), llvm::MCStreamer::endSection(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCTargetStreamer::getStreamer(), llvm::ELF::GNU_PROPERTY_AARCH64_FEATURE_1_AND, llvm::ELF::NT_GNU_PROPERTY_TYPE_0, llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_NOTE, llvm::MCStreamer::switchSection(), and value.
Referenced by finish().
finish()
void AArch64TargetStreamer::finish () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 57 of file AArch64TargetStreamer.cpp.
References emitNoteSection(), llvm::ELF::GNU_PROPERTY_AARCH64_FEATURE_1_BTI, and MarkBTIProperty.
The documentation for this class was generated from the following files:
lib/Target/AArch64/MCTargetDesc/AArch64TargetStreamer.h
lib/Target/AArch64/MCTargetDesc/AArch64TargetStreamer.cpp