LLVM: llvm::LoopVersioningLICMPass Class Reference
llvm::LoopVersioningLICMPass Class Reference
#include "llvm/Transforms/Scalar/LoopVersioningLICM.h"
Public Member Functions
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &LAR, LPMUpdater &U)
Public Member Functions inherited from llvm::PassInfoMixin< LoopVersioningLICMPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopVersioningLICMPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 19 of file LoopVersioningLICM.h.
Member Function Documentation
run()
PreservedAnalyses llvm::LoopVersioningLICMPass::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & LAR, LPMUpdater & U)
Definition at line 664 of file LoopVersioningLICM.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::getLoopPassPreservedAnalyses(), llvm::BasicBlock::getParent(), and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Scalar/LoopVersioningLICM.h
lib/Transforms/Scalar/LoopVersioningLICM.cpp