LLVM: llvm::vfs::YAMLVFSWriter Class Reference
llvm::vfs::YAMLVFSWriter Class Reference
#include "llvm/Support/VirtualFileSystem.h"
Public Member Functions
YAMLVFSWriter ()=default
void addFileMapping (StringRef VirtualPath, StringRef RealPath)
void addDirectoryMapping (StringRef VirtualPath, StringRef RealPath)
void setCaseSensitivity (bool CaseSensitive)
void setUseExternalNames (bool UseExtNames)
void setOverlayDir (StringRef OverlayDirectory)
const std::vector< YAMLVFSEntry > & getMappings () const
void write (llvm::raw_ostream &OS)
Detailed Description
Definition at line 1016 of file VirtualFileSystem.h.
Constructor & Destructor Documentation
YAMLVFSWriter()
llvm::vfs::YAMLVFSWriter::YAMLVFSWriter () default
Member Function Documentation
addDirectoryMapping()
void YAMLVFSWriter::addDirectoryMapping (StringRef VirtualPath, StringRef RealPath)
Definition at line 2583 of file VirtualFileSystem.cpp.
addFileMapping()
void YAMLVFSWriter::addFileMapping (StringRef VirtualPath, StringRef RealPath)
Definition at line 2579 of file VirtualFileSystem.cpp.
getMappings()
const std::vector< YAMLVFSEntry > & llvm::vfs::YAMLVFSWriter::getMappings () const inline
Definition at line 1042 of file VirtualFileSystem.h.
References Mappings.
Referenced by llvm::FileCollector::copyFiles().
setCaseSensitivity()
void llvm::vfs::YAMLVFSWriter::setCaseSensitivity (bool CaseSensitive) inline
Definition at line 1031 of file VirtualFileSystem.h.
Referenced by llvm::FileCollector::writeMapping().
setOverlayDir()
void llvm::vfs::YAMLVFSWriter::setOverlayDir (StringRef OverlayDirectory) inline
Definition at line 1037 of file VirtualFileSystem.h.
Referenced by llvm::FileCollector::writeMapping().
setUseExternalNames()
void llvm::vfs::YAMLVFSWriter::setUseExternalNames (bool UseExtNames) inline
Definition at line 1035 of file VirtualFileSystem.h.
Referenced by llvm::FileCollector::writeMapping().
write()
void YAMLVFSWriter::write (llvm::raw_ostream & OS)
Definition at line 2749 of file VirtualFileSystem.cpp.
References Mappings, and llvm::sort().
Referenced by llvm::FileCollector::writeMapping().
The documentation for this class was generated from the following files:
include/llvm/Support/VirtualFileSystem.h
lib/Support/VirtualFileSystem.cpp