LLVM: llvm::AIXException Class Reference
llvm::AIXException Class Reference
#include "CodeGen/AsmPrinter/DwarfException.h"
Public Member Functions
AIXException (AsmPrinter *A)
void markFunctionEnd () override
void endModule () override
Emit all sections that should come after the content.
void beginFunction (const MachineFunction *MF) override
Gather pre-function debug information.
void endFunction (const MachineFunction *MF) override
Gather post-function debug information.
Public Member Functions inherited from llvm::EHStreamer
EHStreamer (AsmPrinter *A)
~EHStreamer () override
void setSymbolSize (const MCSymbol *Sym, uint64_t Size) override
For symbols that have a size designated (e.g.
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void endInstruction () override
Process end of an instruction.
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
virtual void beginModule (Module *M)
virtual void beginFragment (const MachineBasicBlock *MBB, ExceptionSymbolProvider ESP)
virtual void beginFunclet (const MachineBasicBlock &MBB, MCSymbol *Sym=nullptr)
Emit target-specific EH funclet machinery.
virtual void endFunclet ()
virtual void beginBasicBlock (const MachineBasicBlock &MBB)
Process beginning of a basic block during basic block sections.
virtual void endBasicBlock (const MachineBasicBlock &MBB)
Process end of a basic block during basic block sections.
Additional Inherited Members
Static Public Member Functions inherited from llvm::EHStreamer
static bool callToNoUnwindFunction (const MachineInstr *MI)
Return ‘true’ if this is a call to a function marked ‘nounwind’.
Protected Types inherited from llvm::EHStreamer
using RangeMapType = DenseMap<MCSymbol *, PadRange>
Protected Member Functions inherited from llvm::DwarfCFIExceptionBase
DwarfCFIExceptionBase (AsmPrinter *A)
void markFunctionEnd () override
void endFragment () override
Protected Member Functions inherited from llvm::EHStreamer
void computeActionsTable (const SmallVectorImpl< const LandingPadInfo * > &LandingPads, SmallVectorImpl< ActionEntry > &Actions, SmallVectorImpl< unsigned > &FirstActions)
Compute the actions table and gather the first action index for each landing pad site.
void computePadMap (const SmallVectorImpl< const LandingPadInfo * > &LandingPads, RangeMapType &PadMap)
virtual void computeCallSiteTable (SmallVectorImpl< CallSiteEntry > &CallSites, SmallVectorImpl< CallSiteRange > &CallSiteRanges, const SmallVectorImpl< const LandingPadInfo * > &LandingPads, const SmallVectorImpl< unsigned > &FirstActions)
Compute the call-site table and the call-site ranges.
MCSymbol * emitExceptionTable ()
Emit landing pads and actions.
virtual void emitTypeInfos (unsigned TTypeEncoding, MCSymbol *TTBaseLabel)
Static Protected Member Functions inherited from llvm::EHStreamer
static unsigned sharedTypeIDs (const LandingPadInfo *L, const LandingPadInfo *R)
How many leading type ids two landing pads have in common.
static bool isFilterEHSelector (int Selector)
static bool isCleanupEHSelector (int Selector)
static bool isCatchEHSelector (int Selector)
Protected Attributes inherited from llvm::DwarfCFIExceptionBase
bool shouldEmitCFI = false
Per-function flag to indicate if frame CFI info should be emitted.
bool hasEmittedCFISections = false
Per-module flag to indicate if .cfi_section has beeen emitted.
Protected Attributes inherited from llvm::EHStreamer
AsmPrinter * Asm
Target of directive emission.
MachineModuleInfo * MMI
Collected machine module information.
Detailed Description
Definition at line 93 of file DwarfException.h.
Constructor & Destructor Documentation
AIXException()
llvm::AIXException::AIXException (AsmPrinter * A)
Definition at line 24 of file AIXException.cpp.
Member Function Documentation
beginFunction()
void llvm::AIXException::beginFunction (const MachineFunction * MF) inline override virtual
Gather pre-function debug information.
Every beginFunction(MF) call should be followed by an endFunction(MF) call.
Implements llvm::AsmPrinterHandler.
Definition at line 104 of file DwarfException.h.
endFunction()
void llvm::AIXException::endFunction (const MachineFunction * MF) override virtual
Gather post-function debug information.
Please note that some AsmPrinter implementations may not call beginFunction at all.
Implements llvm::AsmPrinterHandler.
Definition at line 76 of file AIXException.cpp.
References llvm::EHStreamer::Asm, assert(), llvm::EHStreamer::emitExceptionTable(), F, llvm::MachineFunction::getFunction(), llvm::TargetMachine::getSymbol(), llvm::TargetLoweringObjectFileXCOFF::ShouldEmitEHBlock(), and llvm::AsmPrinter::TM.
endModule()
void llvm::AIXException::endModule () inline override virtual
Emit all sections that should come after the content.
Implements llvm::AsmPrinterHandler.
Definition at line 103 of file DwarfException.h.
markFunctionEnd()
void llvm::AIXException::markFunctionEnd () override virtual
Reimplemented from llvm::AsmPrinterHandler.
Definition at line 26 of file AIXException.cpp.
References llvm::DwarfCFIExceptionBase::endFragment().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/DwarfException.h
lib/CodeGen/AsmPrinter/AIXException.cpp