LLVM: llvm::AttributeMask Class Reference
llvm::AttributeMask Class Reference
#include "llvm/IR/Attributes.h"
Public Member Functions
AttributeMask ()=default
AttributeMask (const AttributeMask &)=delete
AttributeMask (AttributeMask &&)=default
AttributeMask (AttributeSet AS)
AttributeMask & addAttribute (Attribute::AttrKind Val)
Add an attribute to the mask.
AttributeMask & addAttribute (Attribute A)
Add the Attribute object to the builder.
AttributeMask & addAttribute (StringRef A)
Add the target-dependent attribute to the builder.
bool contains (Attribute::AttrKind A) const
Return true if the builder has the specified attribute.
bool contains (StringRef A) const
Return true if the builder has the specified target-dependent attribute.
bool contains (Attribute A) const
Return true if the mask contains the specified attribute.
Detailed Description
Definition at line 963 of file Attributes.h.
Constructor & Destructor Documentation
AttributeMask() [1/4]
llvm::AttributeMask::AttributeMask () default
AttributeMask() [2/4]
llvm::AttributeMask::AttributeMask (const AttributeMask &) delete
AttributeMask() [3/4]
llvm::AttributeMask::AttributeMask (AttributeMask &&) default
AttributeMask() [4/4]
llvm::AttributeMask::AttributeMask (AttributeSet AS) inline
Definition at line 972 of file Attributes.h.
References A, and addAttribute().
Member Function Documentation
addAttribute() [1/3]
AttributeMask & llvm::AttributeMask::addAttribute (Attribute A) inline
Add the Attribute object to the builder.
Definition at line 986 of file Attributes.h.
References A, and addAttribute().
addAttribute() [2/3]
AttributeMask & llvm::AttributeMask::addAttribute (Attribute::AttrKind Val) inline
Add an attribute to the mask.
Definition at line 978 of file Attributes.h.
References assert(), and llvm::Attribute::EndAttrKinds.
Referenced by addAttribute(), AttributeMask(), getParamAndReturnAttributesToRemove(), and llvm::AttributeFuncs::getUBImplyingAttributes().
addAttribute() [3/3]
AttributeMask & llvm::AttributeMask::addAttribute (StringRef A) inline
Add the target-dependent attribute to the builder.
Definition at line 995 of file Attributes.h.
References A.
contains() [1/3]
bool llvm::AttributeMask::contains (Attribute A) const inline
Return true if the mask contains the specified attribute.
Definition at line 1011 of file Attributes.h.
References A, and contains().
contains() [2/3]
bool llvm::AttributeMask::contains (Attribute::AttrKind A) const inline
Return true if the builder has the specified attribute.
Definition at line 1001 of file Attributes.h.
References A, assert(), and llvm::Attribute::EndAttrKinds.
Referenced by contains(), llvm::AttrBuilder::overlaps(), and llvm::AttrBuilder::remove().
contains() [3/3]
bool llvm::AttributeMask::contains (StringRef A) const inline
Return true if the builder has the specified target-dependent attribute.
Definition at line 1008 of file Attributes.h.
References A.
The documentation for this class was generated from the following file:
include/llvm/IR/Attributes.h