LLVM: llvm::optional_detail::OptionalStorage< T, bool > Class Template Reference
llvm::optional_detail::OptionalStorage< T, bool > Class Template Reference
Storage for any type.
#include "llvm/ADT/Optional.h"
Public Member Functions
~OptionalStorage ()
constexpr OptionalStorage () noexcept
constexpr OptionalStorage (OptionalStorage const &other)
constexpr OptionalStorage (OptionalStorage &&other)
template<class... Args>
constexpr OptionalStorage (in_place_t, Args &&...args)
void reset () noexcept
constexpr bool has_value () const noexcept
constexpr bool hasValue () const noexcept
T & value () &noexcept
T & getValue () &noexcept
constexpr T const & value () const &noexcept
constexpr T const & getValue () const &noexcept
T && value () &&noexcept
T && getValue () &&noexcept
template<class... Args>
void emplace (Args &&...args)
OptionalStorage & operator= (T const &y)
OptionalStorage & operator= (T &&y)
OptionalStorage & operator= (OptionalStorage const &other)
OptionalStorage & operator= (OptionalStorage &&other)
Detailed Description
template<typename T, bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))>
class llvm::optional_detail::OptionalStorage< T, bool >
Storage for any type.
Definition at line 60 of file Optional.h.
Constructor & Destructor Documentation
~OptionalStorage()
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> llvm::optional_detail::OptionalStorage< T, bool >::~OptionalStorage () inline
Definition at line 68 of file Optional.h.
OptionalStorage() [1/4]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> constexpr llvm::optional_detail::OptionalStorage< T, bool >::OptionalStorage () inline constexpr noexcept
Definition at line 70 of file Optional.h.
OptionalStorage() [2/4]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> constexpr llvm::optional_detail::OptionalStorage< T, bool >::OptionalStorage (OptionalStorage< T, bool > const & other) inline constexpr
Definition at line 72 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::has_value(), and llvm::optional_detail::OptionalStorage< T, bool >::val.
OptionalStorage() [3/4]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> constexpr llvm::optional_detail::OptionalStorage< T, bool >::OptionalStorage (OptionalStorage< T, bool > && other) inline constexpr
Definition at line 77 of file Optional.h.
OptionalStorage() [4/4]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> template<class... Args> constexpr llvm::optional_detail::OptionalStorage< T, bool >::OptionalStorage (in_place_t , Args &&... args) inline explicit constexpr
Definition at line 84 of file Optional.h.
Member Function Documentation
emplace()
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> template<class... Args> void llvm::optional_detail::OptionalStorage< T, bool >::emplace (Args &&... args) inline
Definition at line 122 of file Optional.h.
References T.
Referenced by llvm::Optional< T >::emplace().
getValue() [1/3]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> T && llvm::optional_detail::OptionalStorage< T, bool >::getValue () && inline noexcept
Definition at line 117 of file Optional.h.
References assert().
getValue() [2/3]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> T & llvm::optional_detail::OptionalStorage< T, bool >::getValue () & inline noexcept
Definition at line 101 of file Optional.h.
References assert().
getValue() [3/3]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> constexpr T const & llvm::optional_detail::OptionalStorage< T, bool >::getValue () const & inline constexpr noexcept
Definition at line 109 of file Optional.h.
References assert().
has_value()
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> constexpr bool llvm::optional_detail::OptionalStorage< T, bool >::has_value () const inline constexpr noexcept
Definition at line 94 of file Optional.h.
Referenced by llvm::Optional< T >::has_value(), llvm::Optional< T >::hasValue(), llvm::optional_detail::OptionalStorage< T, bool >::operator=(), llvm::optional_detail::OptionalStorage< T, true >::operator=(), llvm::optional_detail::OptionalStorage< T, true >::operator=(), and llvm::optional_detail::OptionalStorage< T, bool >::OptionalStorage().
hasValue()
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> constexpr bool llvm::optional_detail::OptionalStorage< T, bool >::hasValue () const inline constexpr noexcept
Definition at line 95 of file Optional.h.
operator=() [1/4]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> OptionalStorage & llvm::optional_detail::OptionalStorage< T, bool >::operator= (OptionalStorage< T, bool > && other) inline
Definition at line 161 of file Optional.h.
References T.
operator=() [2/4]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> OptionalStorage & llvm::optional_detail::OptionalStorage< T, bool >::operator= (OptionalStorage< T, bool > const & other) inline
Definition at line 147 of file Optional.h.
References llvm::optional_detail::OptionalStorage< T, bool >::has_value(), T, and llvm::optional_detail::OptionalStorage< T, bool >::val.
operator=() [3/4]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> OptionalStorage & llvm::optional_detail::OptionalStorage< T, bool >::operator= (T && y) inline
Definition at line 137 of file Optional.h.
References T.
operator=() [4/4]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> OptionalStorage & llvm::optional_detail::OptionalStorage< T, bool >::operator= (T const & y) inline
Definition at line 128 of file Optional.h.
References T.
reset()
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> void llvm::optional_detail::OptionalStorage< T, bool >::reset () inline noexcept
Definition at line 87 of file Optional.h.
Referenced by llvm::optional_detail::OptionalStorage< T, true >::emplace(), and llvm::Optional< T >::reset().
value() [1/3]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> T && llvm::optional_detail::OptionalStorage< T, bool >::value () && inline noexcept
Definition at line 113 of file Optional.h.
References assert().
value() [2/3]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> T & llvm::optional_detail::OptionalStorage< T, bool >::value () & inline noexcept
Definition at line 97 of file Optional.h.
References assert().
Referenced by llvm::Optional< T >::getPointer(), llvm::Optional< T >::getPointer(), llvm::Optional< T >::getValue(), llvm::Optional< T >::getValue(), llvm::Optional< T >::getValue(), llvm::Optional< T >::operator*(), llvm::Optional< T >::value(), llvm::Optional< T >::value(), and llvm::Optional< T >::value().
value() [3/3]
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> constexpr T const & llvm::optional_detail::OptionalStorage< T, bool >::value () const & inline constexpr noexcept
Definition at line 105 of file Optional.h.
References assert().
Member Data Documentation
empty
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> char llvm::optional_detail::OptionalStorage< T, bool >::empty
Definition at line 62 of file Optional.h.
val
template<typename T , bool = (llvm::is_trivially_copy_constructible<T>::value && std::is_trivially_copy_assignable<T>::value && (llvm::is_trivially_move_constructible<T>::value || !std::is_move_constructible<T>::value) && (std::is_trivially_move_assignable<T>::value || !std::is_move_assignable<T>::value))> T llvm::optional_detail::OptionalStorage< T, bool >::val
Definition at line 63 of file Optional.h.
Referenced by llvm::optional_detail::OptionalStorage< T, true >::emplace(), llvm::optional_detail::OptionalStorage< T, true >::getValue(), llvm::optional_detail::OptionalStorage< T, true >::getValue(), llvm::optional_detail::OptionalStorage< T, true >::getValue(), llvm::optional_detail::OptionalStorage< T, bool >::operator=(), llvm::optional_detail::OptionalStorage< T, true >::operator=(), llvm::optional_detail::OptionalStorage< T, true >::operator=(), llvm::optional_detail::OptionalStorage< T, bool >::OptionalStorage(), llvm::optional_detail::OptionalStorage< T, true >::reset(), llvm::optional_detail::OptionalStorage< T, true >::value(), llvm::optional_detail::OptionalStorage< T, true >::value(), and llvm::optional_detail::OptionalStorage< T, true >::value().
The documentation for this class was generated from the following file:
include/llvm/ADT/Optional.h