LLVM: llvm::MCDwarfLineTable Class Reference
llvm::MCDwarfLineTable Class Reference
#include "llvm/MC/MCDwarf.h"
Public Member Functions
void emitCU (MCStreamer *MCOS, MCDwarfLineTableParams Params, Optional< MCDwarfLineStr > &LineStr) const
Expected< unsigned > tryGetFile (StringRef &Directory, StringRef &FileName, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, uint16_t DwarfVersion, unsigned FileNumber=0)
unsigned getFile (StringRef &Directory, StringRef &FileName, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, uint16_t DwarfVersion, unsigned FileNumber=0)
void setRootFile (StringRef Directory, StringRef FileName, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source)
void resetFileTable ()
bool hasRootFile () const
MCDwarfFile & getRootFile ()
const MCDwarfFile & getRootFile () const
bool isMD5UsageConsistent () const
MCSymbol * getLabel () const
void setLabel (MCSymbol *Label)
const SmallVectorImpl< std::string > & getMCDwarfDirs () const
SmallVectorImpl< std::string > & getMCDwarfDirs ()
const SmallVectorImpl< MCDwarfFile > & getMCDwarfFiles () const
SmallVectorImpl< MCDwarfFile > & getMCDwarfFiles ()
const MCLineSection & getMCLineSections () const
MCLineSection & getMCLineSections ()
Static Public Member Functions
static void emit (MCStreamer *MCOS, MCDwarfLineTableParams Params)
static void emitOne (MCStreamer *MCOS, MCSection *Section, const MCLineSection::MCDwarfLineEntryCollection &LineEntries)
Detailed Description
Definition at line 346 of file MCDwarf.h.
Member Function Documentation
emit()
void MCDwarfLineTable::emit (MCStreamer * MCOS, MCDwarfLineTableParams Params) static
Definition at line 256 of file MCDwarf.cpp.
References llvm::MCObjectFileInfo::getDwarfLineSection(), llvm::MCContext::getDwarfVersion(), llvm::MCContext::getMCDwarfLineTables(), and llvm::MCContext::getObjectFileInfo().
Referenced by llvm::MCObjectStreamer::finishImpl().
emitCU()
void MCDwarfLineTable::emitCU (MCStreamer * MCOS, MCDwarfLineTableParams Params, Optional< MCDwarfLineStr > & LineStr) const
Definition at line 549 of file MCDwarf.cpp.
References llvm::MCDwarfLineTableHeader::Emit(), emitOne(), and llvm::MCLineSection::getMCLineEntries().
emitOne()
void MCDwarfLineTable::emitOne (MCStreamer * MCOS, MCSection * Section, const MCLineSection::MCDwarfLineEntryCollection & LineEntries) static
Definition at line 166 of file MCDwarf.cpp.
References DWARF2_FLAG_BASIC_BLOCK, DWARF2_FLAG_EPILOGUE_BEGIN, DWARF2_FLAG_IS_STMT, DWARF2_FLAG_PROLOGUE_END, DWARF2_LINE_DEFAULT_IS_STMT, llvm::getULEB128Size(), INT64_MAX, and Size.
Referenced by emitCU().
getFile()
unsigned llvm::MCDwarfLineTable::getFile (StringRef & Directory, StringRef & FileName, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, uint16_t DwarfVersion, unsigned FileNumber = 0) inline
Definition at line 368 of file MCDwarf.h.
References llvm::cantFail(), and tryGetFile().
getLabel()
MCSymbol * llvm::MCDwarfLineTable::getLabel () const inline
Definition at line 396 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::Label.
Referenced by llvm::MCStreamer::getDwarfLineTableSymbol().
getMCDwarfDirs() [1/2]
SmallVectorImpl< std::string > & llvm::MCDwarfLineTable::getMCDwarfDirs () inline
Definition at line 408 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::MCDwarfDirs.
getMCDwarfDirs() [2/2]
const SmallVectorImpl< std::string > & llvm::MCDwarfLineTable::getMCDwarfDirs () const inline
Definition at line 404 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::MCDwarfDirs.
Referenced by llvm::MCContext::getMCDwarfDirs().
getMCDwarfFiles() [1/2]
SmallVectorImpl< MCDwarfFile > & llvm::MCDwarfLineTable::getMCDwarfFiles () inline
Definition at line 416 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::MCDwarfFiles.
getMCDwarfFiles() [2/2]
const SmallVectorImpl< MCDwarfFile > & llvm::MCDwarfLineTable::getMCDwarfFiles () const inline
Definition at line 412 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::MCDwarfFiles.
Referenced by llvm::MCContext::getMCDwarfFiles(), and llvm::MCContext::isValidDwarfFileNumber().
getMCLineSections() [1/2]
MCLineSection & llvm::MCDwarfLineTable::getMCLineSections () inline
Definition at line 423 of file MCDwarf.h.
getMCLineSections() [2/2]
const MCLineSection & llvm::MCDwarfLineTable::getMCLineSections () const inline
Definition at line 420 of file MCDwarf.h.
getRootFile() [1/2]
MCDwarfFile & llvm::MCDwarfLineTable::getRootFile () inline
Definition at line 390 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::RootFile.
Referenced by EmitGenDwarfInfo().
getRootFile() [2/2]
const MCDwarfFile & llvm::MCDwarfLineTable::getRootFile () const inline
Definition at line 391 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::RootFile.
hasRootFile()
bool llvm::MCDwarfLineTable::hasRootFile () const inline
Definition at line 388 of file MCDwarf.h.
References llvm::MCDwarfFile::Name, and llvm::MCDwarfLineTableHeader::RootFile.
isMD5UsageConsistent()
bool llvm::MCDwarfLineTable::isMD5UsageConsistent () const inline
Definition at line 394 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::isMD5UsageConsistent().
Referenced by llvm::MCContext::isDwarfMD5UsageConsistent().
resetFileTable()
void llvm::MCDwarfLineTable::resetFileTable () inline
Definition at line 386 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::resetFileTable().
setLabel()
void llvm::MCDwarfLineTable::setLabel (MCSymbol * Label) inline
Definition at line 400 of file MCDwarf.h.
References llvm::MCDwarfLineTableHeader::Label.
Referenced by llvm::MCStreamer::getDwarfLineTableSymbol().
setRootFile()
void llvm::MCDwarfLineTable::setRootFile (StringRef Directory, StringRef FileName, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source) inline
Definition at line 375 of file MCDwarf.h.
References llvm::MCDwarfFile::Checksum, llvm::MCDwarfLineTableHeader::CompilationDir, llvm::MCDwarfFile::DirIndex, llvm::MCDwarfLineTableHeader::HasSource, llvm::MCDwarfFile::Name, llvm::MCDwarfLineTableHeader::RootFile, llvm::MCDwarfFile::Source, and llvm::MCDwarfLineTableHeader::trackMD5Usage().
Referenced by llvm::MCContext::setMCLineTableRootFile().
tryGetFile()
Expected< unsigned > MCDwarfLineTable::tryGetFile (StringRef & Directory, StringRef & FileName, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, uint16_t DwarfVersion, unsigned FileNumber = 0)
Definition at line 562 of file MCDwarf.cpp.
References llvm::MCDwarfLineTableHeader::tryGetFile().
Referenced by llvm::MCContext::getDwarfFile(), and getFile().
The documentation for this class was generated from the following files:
include/llvm/MC/MCDwarf.h
lib/MC/MCDwarf.cpp