LLVM: llvm::DefaultInlineOrder< T, Container > Class Template Reference
llvm::DefaultInlineOrder< T, Container > Class Template Reference
#include "llvm/Analysis/InlineOrder.h"
Public Member Functions
size_t size () override
void push (const T &Elt) override
T pop () override
const_reference front () override
void erase_if (function_ref< bool(T)> Pred) override
Public Member Functions inherited from llvm::InlineOrder< T >
virtual ~InlineOrder ()=default
bool empty ()
Additional Inherited Members
Public Types inherited from llvm::InlineOrder< T >
using reference = T &
using const_reference = const T &
Detailed Description
template<typename T, typename Container = SmallVector<T, 16>>
class llvm::DefaultInlineOrder< T, Container >
Definition at line 44 of file InlineOrder.h.
Member Function Documentation
erase_if()
template<typename T , typename Container = SmallVector<T, 16>> void llvm::DefaultInlineOrder< T, Container >::erase_if (function_ref< bool(T)> Pred) inline override virtual
Implements llvm::InlineOrder< T >.
Definition at line 63 of file InlineOrder.h.
front()
template<typename T , typename Container = SmallVector<T, 16>> const_reference llvm::DefaultInlineOrder< T, Container >::front () inline override virtual
Implements llvm::InlineOrder< T >.
Definition at line 58 of file InlineOrder.h.
References assert(), and llvm::DefaultInlineOrder< T, Container >::size().
pop()
template<typename T , typename Container = SmallVector<T, 16>> T llvm::DefaultInlineOrder< T, Container >::pop () inline override virtual
Implements llvm::InlineOrder< T >.
Definition at line 53 of file InlineOrder.h.
References assert(), and llvm::DefaultInlineOrder< T, Container >::size().
push()
template<typename T , typename Container = SmallVector<T, 16>> void llvm::DefaultInlineOrder< T, Container >::push (const T & Elt) inline override virtual
Implements llvm::InlineOrder< T >.
Definition at line 51 of file InlineOrder.h.
size()
template<typename T , typename Container = SmallVector<T, 16>> size_t llvm::DefaultInlineOrder< T, Container >::size () inline override virtual
Implements llvm::InlineOrder< T >.
Definition at line 49 of file InlineOrder.h.
Referenced by llvm::DefaultInlineOrder< T, Container >::front(), and llvm::DefaultInlineOrder< T, Container >::pop().
The documentation for this class was generated from the following file:
include/llvm/Analysis/InlineOrder.h