LLVM: llvm::CSKYConstantPoolSymbol Class Reference
llvm::CSKYConstantPoolSymbol Class Reference
CSKYConstantPoolSymbol - CSKY-specific constantpool values for external symbols.
#include "Target/CSKY/CSKYConstantPoolValue.h"
Public Member Functions
StringRef getSymbol () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const CSKYConstantPoolSymbol *A) const
Public Member Functions inherited from llvm::CSKYConstantPoolValue
const char * getModifierText () const
unsigned getPCAdjustment () const
bool mustAddCurrentAddress () const
CSKYCP::CSKYCPModifier getModifier () const
unsigned getLabelID () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isMachineBasicBlock () const
bool isJT () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const CSKYConstantPoolValue *A) const
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, Align Alignment)
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
virtual unsigned getSizeInBytes (const DataLayout &DL) const
Static Public Member Functions
static CSKYConstantPoolSymbol * Create (Type *Ty, const char *S, unsigned PCAdjust, CSKYCP::CSKYCPModifier Modifier)
static bool classof (const CSKYConstantPoolValue *ACPV)
Additional Inherited Members
Protected Member Functions inherited from llvm::CSKYConstantPoolValue
CSKYConstantPoolValue (Type *Ty, CSKYCP::CSKYCPKind Kind, unsigned PCAdjust, CSKYCP::CSKYCPModifier Modifier, bool AddCurrentAddress, unsigned ID=0)
Protected Attributes inherited from llvm::CSKYConstantPoolValue
CSKYCP::CSKYCPKind Kind
unsigned PCAdjust
CSKYCP::CSKYCPModifier Modifier
bool AddCurrentAddress
unsigned LabelId = 0
Detailed Description
CSKYConstantPoolSymbol - CSKY-specific constantpool values for external symbols.
Definition at line 136 of file CSKYConstantPoolValue.h.
Member Function Documentation
addSelectionDAGCSEId()
void CSKYConstantPoolSymbol::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 143 of file CSKYConstantPoolValue.cpp.
References llvm::CSKYConstantPoolValue::addSelectionDAGCSEId().
classof()
static bool llvm::CSKYConstantPoolSymbol::classof (const CSKYConstantPoolValue * ACPV) inline static
Definition at line 159 of file CSKYConstantPoolValue.h.
Create()
CSKYConstantPoolSymbol * CSKYConstantPoolSymbol::Create (Type * Ty, const char * S, unsigned PCAdjust, CSKYCP::CSKYCPModifier Modifier) static
Definition at line 132 of file CSKYConstantPoolValue.cpp.
References llvm::CSKYConstantPoolValue::Modifier, and llvm::CSKYConstantPoolValue::PCAdjust.
Referenced by llvm::CSKYInstrInfo::getGlobalBaseReg().
equals()
bool llvm::CSKYConstantPoolSymbol::equals (const CSKYConstantPoolSymbol * A) const inline
Definition at line 155 of file CSKYConstantPoolValue.h.
References A, and llvm::CSKYConstantPoolValue::equals().
getExistingMachineCPValue()
int CSKYConstantPoolSymbol::getExistingMachineCPValue (MachineConstantPool * CP, Align Alignment) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 137 of file CSKYConstantPoolValue.cpp.
getSymbol()
StringRef llvm::CSKYConstantPoolSymbol::getSymbol () const inline
Definition at line 148 of file CSKYConstantPoolValue.h.
print()
void CSKYConstantPoolSymbol::print (raw_ostream & O) const override virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Definition at line 148 of file CSKYConstantPoolValue.cpp.
References llvm::CSKYConstantPoolValue::print().
The documentation for this class was generated from the following files:
lib/Target/CSKY/CSKYConstantPoolValue.h
lib/Target/CSKY/CSKYConstantPoolValue.cpp