LLVM: llvm::OpenMPOptCGSCCPass Class Reference
llvm::OpenMPOptCGSCCPass Class Reference
#include "llvm/Transforms/IPO/OpenMPOpt.h"
Public Member Functions
PreservedAnalyses run (LazyCallGraph::SCC &C, CGSCCAnalysisManager &AM, LazyCallGraph &CG, CGSCCUpdateResult &UR)
Public Member Functions inherited from llvm::PassInfoMixin< OpenMPOptCGSCCPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< OpenMPOptCGSCCPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 43 of file OpenMPOpt.h.
Member Function Documentation
run()
PreservedAnalyses OpenMPOptCGSCCPass::run (LazyCallGraph::SCC & C, CGSCCAnalysisManager & AM, LazyCallGraph & CG, CGSCCUpdateResult & UR)
Definition at line 5036 of file OpenMPOpt.cpp.
References A, llvm::PreservedAnalyses::all(), Allocator, llvm::Module::begin(), llvm::CallingConv::C, llvm::omp::containsOpenMP(), llvm::dbgs(), DEBUG_TYPE, llvm::AttributorConfig::DefaultInitializeLiveInternals, DisableOpenMPOptimizations, F, FAM, llvm::omp::getDeviceKernels(), llvm::Function::getFunction(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::CallGraphUpdater::initialize(), llvm::AttributorConfig::IsModulePass, llvm::omp::isOpenMPDevice(), LLVM_DEBUG, llvm::AttributorConfig::MaxFixpointIterations, N, llvm::PreservedAnalyses::none(), llvm::AttributorConfig::OREGetter, llvm::AttributorConfig::PassName, PrintModuleAfterOptimizations, PrintModuleBeforeOptimizations, llvm::AttributorConfig::RewriteSignatures, SetFixpointIterations, and TAG.
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/OpenMPOpt.h
lib/Transforms/IPO/OpenMPOpt.cpp