LLVM: llvm::orc::OrcV2CAPIHelper Class Reference
llvm::orc::OrcV2CAPIHelper Class Reference
Public Types
using PoolEntry = SymbolStringPtr::PoolEntry
using PoolEntryPtr = SymbolStringPtr::PoolEntryPtr
Static Public Member Functions
static PoolEntryPtr moveFromSymbolStringPtr (SymbolStringPtr S)
static SymbolStringPtr moveToSymbolStringPtr (PoolEntryPtr P)
static SymbolStringPtr copyToSymbolStringPtr (PoolEntryPtr P)
static PoolEntryPtr getRawPoolEntryPtr (const SymbolStringPtr &S)
static void retainPoolEntry (PoolEntryPtr P)
static void releasePoolEntry (PoolEntryPtr P)
static InProgressLookupState * extractLookupState (LookupState &LS)
static void resetLookupState (LookupState &LS, InProgressLookupState *IPLS)
Detailed Description
Definition at line 28 of file OrcV2CBindings.cpp.
Member Typedef Documentation
PoolEntry
using llvm::orc::OrcV2CAPIHelper::PoolEntry = SymbolStringPtr::PoolEntry
Definition at line 30 of file OrcV2CBindings.cpp.
PoolEntryPtr
using llvm::orc::OrcV2CAPIHelper::PoolEntryPtr = SymbolStringPtr::PoolEntryPtr
Definition at line 31 of file OrcV2CBindings.cpp.
Member Function Documentation
copyToSymbolStringPtr()
static SymbolStringPtr llvm::orc::OrcV2CAPIHelper::copyToSymbolStringPtr (PoolEntryPtr P) inline static
Definition at line 48 of file OrcV2CBindings.cpp.
References P.
extractLookupState()
static InProgressLookupState * llvm::orc::OrcV2CAPIHelper::extractLookupState (LookupState & LS) inline static
Definition at line 66 of file OrcV2CBindings.cpp.
Referenced by llvm::orc::CAPIDefinitionGenerator::tryToGenerate().
getRawPoolEntryPtr()
static PoolEntryPtr llvm::orc::OrcV2CAPIHelper::getRawPoolEntryPtr (const SymbolStringPtr & S) inline static
Definition at line 52 of file OrcV2CBindings.cpp.
Referenced by DEFINE_SIMPLE_CONVERSION_FUNCTIONS(), LLVMOrcCreateDynamicLibrarySearchGeneratorForPath(), LLVMOrcCreateDynamicLibrarySearchGeneratorForProcess(), LLVMOrcExecutionSessionLookup(), LLVMOrcMaterializationResponsibilityGetInitializerSymbol(), LLVMOrcMaterializationResponsibilityGetRequestedSymbols(), LLVMOrcMaterializationResponsibilityGetSymbols(), and llvm::orc::CAPIDefinitionGenerator::tryToGenerate().
moveFromSymbolStringPtr()
static PoolEntryPtr llvm::orc::OrcV2CAPIHelper::moveFromSymbolStringPtr (SymbolStringPtr S) inline static
Definition at line 34 of file OrcV2CBindings.cpp.
References llvm::orc::Result, and std::swap().
Referenced by LLVMOrcExecutionSessionIntern(), and LLVMOrcLLJITMangleAndIntern().
moveToSymbolStringPtr()
static SymbolStringPtr llvm::orc::OrcV2CAPIHelper::moveToSymbolStringPtr (PoolEntryPtr P) inline static
Definition at line 41 of file OrcV2CBindings.cpp.
References P.
Referenced by DEFINE_SIMPLE_CONVERSION_FUNCTIONS(), LLVMOrcCreateCustomMaterializationUnit(), LLVMOrcExecutionSessionLookup(), LLVMOrcLazyReexports(), LLVMOrcMaterializationResponsibilityAddDependencies(), LLVMOrcMaterializationResponsibilityDefineMaterializing(), and LLVMOrcMaterializationResponsibilityDelegate().
releasePoolEntry()
static void llvm::orc::OrcV2CAPIHelper::releasePoolEntry (PoolEntryPtr P) inline static
Definition at line 61 of file OrcV2CBindings.cpp.
References P.
Referenced by LLVMOrcReleaseSymbolStringPoolEntry().
resetLookupState()
static void llvm::orc::OrcV2CAPIHelper::resetLookupState (LookupState & LS, InProgressLookupState * IPLS) inline static
Definition at line 70 of file OrcV2CBindings.cpp.
Referenced by LLVMOrcLookupStateContinueLookup(), and llvm::orc::CAPIDefinitionGenerator::tryToGenerate().
retainPoolEntry()
static void llvm::orc::OrcV2CAPIHelper::retainPoolEntry (PoolEntryPtr P) inline static
Definition at line 56 of file OrcV2CBindings.cpp.
References P.
Referenced by LLVMOrcRetainSymbolStringPoolEntry().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/OrcV2CBindings.cpp