LLVM: llvm::DirectiveLanguage Class Reference
llvm::DirectiveLanguage Class Reference
#include "llvm/TableGen/DirectiveEmitter.h"
Public Member Functions
DirectiveLanguage (const llvm::RecordKeeper &Records)
StringRef getName () const
StringRef getCppNamespace () const
StringRef getDirectivePrefix () const
StringRef getClausePrefix () const
StringRef getClauseEnumSetClass () const
StringRef getFlangClauseBaseClass () const
bool hasMakeEnumAvailableInNamespace () const
bool hasEnableBitmaskEnumInNamespace () const
std::vector< Record * > getDirectives () const
std::vector< Record * > getClauses () const
bool HasValidityErrors () const
Detailed Description
Definition at line 11 of file DirectiveEmitter.h.
Constructor & Destructor Documentation
DirectiveLanguage()
llvm::DirectiveLanguage::DirectiveLanguage (const llvm::RecordKeeper & Records) inline explicit
Definition at line 13 of file DirectiveEmitter.h.
Member Function Documentation
getClauseEnumSetClass()
StringRef llvm::DirectiveLanguage::getClauseEnumSetClass () const inline
Definition at line 33 of file DirectiveEmitter.h.
References llvm::Record::getValueAsString().
getClausePrefix()
StringRef llvm::DirectiveLanguage::getClausePrefix () const inline
Definition at line 29 of file DirectiveEmitter.h.
References llvm::Record::getValueAsString().
getClauses()
std::vector< Record * > llvm::DirectiveLanguage::getClauses () const inline
Definition at line 53 of file DirectiveEmitter.h.
References llvm::RecordKeeper::getAllDerivedDefinitions().
getCppNamespace()
StringRef llvm::DirectiveLanguage::getCppNamespace () const inline
Definition at line 21 of file DirectiveEmitter.h.
References llvm::Record::getValueAsString().
getDirectivePrefix()
StringRef llvm::DirectiveLanguage::getDirectivePrefix () const inline
Definition at line 25 of file DirectiveEmitter.h.
References llvm::Record::getValueAsString().
getDirectives()
std::vector< Record * > llvm::DirectiveLanguage::getDirectives () const inline
Definition at line 49 of file DirectiveEmitter.h.
References llvm::RecordKeeper::getAllDerivedDefinitions().
getFlangClauseBaseClass()
StringRef llvm::DirectiveLanguage::getFlangClauseBaseClass () const inline
Definition at line 37 of file DirectiveEmitter.h.
References llvm::Record::getValueAsString().
getName()
StringRef llvm::DirectiveLanguage::getName () const inline
Definition at line 19 of file DirectiveEmitter.h.
References llvm::Record::getValueAsString().
hasEnableBitmaskEnumInNamespace()
bool llvm::DirectiveLanguage::hasEnableBitmaskEnumInNamespace () const inline
Definition at line 45 of file DirectiveEmitter.h.
References llvm::Record::getValueAsBit().
hasMakeEnumAvailableInNamespace()
bool llvm::DirectiveLanguage::hasMakeEnumAvailableInNamespace () const inline
Definition at line 41 of file DirectiveEmitter.h.
References llvm::Record::getValueAsBit().
HasValidityErrors()
bool llvm::DirectiveLanguage::HasValidityErrors () const
The documentation for this class was generated from the following file:
include/llvm/TableGen/DirectiveEmitter.h