LLVM: llvm::object::Decompressor Class Reference
llvm::object::Decompressor Class Reference
Decompressor helps to handle decompression of compressed sections.
#include "llvm/Object/Decompressor.h"
Public Member Functions
template<class T >
Error resizeAndDecompress (T &Out)
Resize the buffer and uncompress section data into it.
Error decompress (MutableArrayRef< uint8_t > Buffer)
Uncompress section data to raw buffer provided.
uint64_t getDecompressedSize ()
Return memory buffer size required for decompression.
Static Public Member Functions
static Expected< Decompressor > create (StringRef Name, StringRef Data, bool IsLE, bool Is64Bit)
Create decompressor object.
Detailed Description
Decompressor helps to handle decompression of compressed sections.
Definition at line 20 of file Decompressor.h.
Member Function Documentation
create()
Expected< Decompressor > Decompressor::create (StringRef Name, StringRef Data, bool IsLE, bool Is64Bit) static
Create decompressor object.
Parameters
Name Section name.
Data Section content.
IsLE Flag determines if Data is in little endian form.
Is64Bit Flag determines if object is 64 bit.
Definition at line 20 of file Decompressor.cpp.
References llvm::object::createError(), D, llvm::Data, and llvm::compression::zlib::isAvailable().
Referenced by handleCompressedSection().
decompress()
Error Decompressor::decompress (MutableArrayRef< uint8_t > Buffer)
Uncompress section data to raw buffer provided.
Parameters
Buffer Destination buffer.
Definition at line 58 of file Decompressor.cpp.
References Size, and llvm::compression::zlib::uncompress().
Referenced by resizeAndDecompress().
getDecompressedSize()
uint64_t llvm::object::Decompressor::getDecompressedSize () inline
Return memory buffer size required for decompression.
Definition at line 42 of file Decompressor.h.
resizeAndDecompress()
template<class T > Error llvm::object::Decompressor::resizeAndDecompress (T & Out) inline
Resize the buffer and uncompress section data into it.
Parameters
Out Destination buffer.
Definition at line 32 of file Decompressor.h.
References decompress().
The documentation for this class was generated from the following files:
include/llvm/Object/Decompressor.h
lib/Object/Decompressor.cpp