LLVM: llvm::InstVisitor< SubClass, RetTy > Class Template Reference
llvm::InstVisitor< SubClass, RetTy > Class Template Reference
Base class for instruction visitors.
#include "llvm/IR/InstVisitor.h"
Public Member Functions
template<class Iterator >
void visit (Iterator Start, Iterator End)
void visit (Module &M)
void visit (Function &F)
void visit (BasicBlock &BB)
void visit (Module *M)
void visit (Function *F)
void visit (BasicBlock *BB)
RetTy visit (Instruction *I)
RetTy visit (Instruction &I)
void visitModule (Module &M)
void visitFunction (Function &F)
void visitBasicBlock (BasicBlock &BB)
RetTy visitICmpInst (ICmpInst &I)
RetTy visitFCmpInst (FCmpInst &I)
RetTy visitAllocaInst (AllocaInst &I)
RetTy visitLoadInst (LoadInst &I)
RetTy visitStoreInst (StoreInst &I)
RetTy visitAtomicCmpXchgInst (AtomicCmpXchgInst &I)
RetTy visitAtomicRMWInst (AtomicRMWInst &I)
RetTy visitFenceInst (FenceInst &I)
RetTy visitGetElementPtrInst (GetElementPtrInst &I)
RetTy visitPHINode (PHINode &I)
RetTy visitTruncInst (TruncInst &I)
RetTy visitZExtInst (ZExtInst &I)
RetTy visitSExtInst (SExtInst &I)
RetTy visitFPTruncInst (FPTruncInst &I)
RetTy visitFPExtInst (FPExtInst &I)
RetTy visitFPToUIInst (FPToUIInst &I)
RetTy visitFPToSIInst (FPToSIInst &I)
RetTy visitUIToFPInst (UIToFPInst &I)
RetTy visitSIToFPInst (SIToFPInst &I)
RetTy visitPtrToIntInst (PtrToIntInst &I)
RetTy visitIntToPtrInst (IntToPtrInst &I)
RetTy visitBitCastInst (BitCastInst &I)
RetTy visitAddrSpaceCastInst (AddrSpaceCastInst &I)
RetTy visitSelectInst (SelectInst &I)
RetTy visitVAArgInst (VAArgInst &I)
RetTy visitExtractElementInst (ExtractElementInst &I)
RetTy visitInsertElementInst (InsertElementInst &I)
RetTy visitShuffleVectorInst (ShuffleVectorInst &I)
RetTy visitExtractValueInst (ExtractValueInst &I)
RetTy visitInsertValueInst (InsertValueInst &I)
RetTy visitLandingPadInst (LandingPadInst &I)
RetTy visitFuncletPadInst (FuncletPadInst &I)
RetTy visitCleanupPadInst (CleanupPadInst &I)
RetTy visitCatchPadInst (CatchPadInst &I)
RetTy visitFreezeInst (FreezeInst &I)
RetTy visitDbgDeclareInst (DbgDeclareInst &I)
RetTy visitDbgValueInst (DbgValueInst &I)
RetTy visitDbgVariableIntrinsic (DbgVariableIntrinsic &I)
RetTy visitDbgLabelInst (DbgLabelInst &I)
RetTy visitDbgInfoIntrinsic (DbgInfoIntrinsic &I)
RetTy visitMemSetInst (MemSetInst &I)
RetTy visitMemCpyInst (MemCpyInst &I)
RetTy visitMemCpyInlineInst (MemCpyInlineInst &I)
RetTy visitMemMoveInst (MemMoveInst &I)
RetTy visitMemTransferInst (MemTransferInst &I)
RetTy visitMemIntrinsic (MemIntrinsic &I)
RetTy visitVAStartInst (VAStartInst &I)
RetTy visitVAEndInst (VAEndInst &I)
RetTy visitVACopyInst (VACopyInst &I)
RetTy visitIntrinsicInst (IntrinsicInst &I)
RetTy visitCallInst (CallInst &I)
RetTy visitInvokeInst (InvokeInst &I)
RetTy visitCallBrInst (CallBrInst &I)
RetTy visitReturnInst (ReturnInst &I)
RetTy visitBranchInst (BranchInst &I)
RetTy visitSwitchInst (SwitchInst &I)
RetTy visitIndirectBrInst (IndirectBrInst &I)
RetTy visitResumeInst (ResumeInst &I)
RetTy visitUnreachableInst (UnreachableInst &I)
RetTy visitCleanupReturnInst (CleanupReturnInst &I)
RetTy visitCatchReturnInst (CatchReturnInst &I)
RetTy visitCatchSwitchInst (CatchSwitchInst &I)
RetTy visitTerminator (Instruction &I)
RetTy visitCastInst (CastInst &I)
RetTy visitUnaryOperator (UnaryOperator &I)
RetTy visitBinaryOperator (BinaryOperator &I)
RetTy visitCmpInst (CmpInst &I)
RetTy visitUnaryInstruction (UnaryInstruction &I)
RetTy visitCallBase (CallBase &I)
void visitInstruction (Instruction &I)
Detailed Description
template<typename SubClass, typename RetTy = void>
class llvm::InstVisitor< SubClass, RetTy >
Base class for instruction visitors.
Instruction visitors are used when you want to perform different actions for different kinds of instructions without having to use lots of casts and a big switch statement (in your code, that is).
To define your own visitor, inherit from this class, specifying your new type for the 'SubClass' template parameter, and "override" visitXXX functions in your class. I say "override" because this class is defined in terms of statically resolved overloading, not virtual functions.
For example, here is a visitor that counts the number of malloc instructions processed:
/// Declare the class. Note that we derive from InstVisitor instantiated /// with our new subclasses type. /// struct CountAllocaVisitor : public InstVisitor<CountAllocaVisitor> { unsigned Count; CountAllocaVisitor() : Count(0) {}
void visitAllocaInst(AllocaInst &AI) { ++Count; } };
And this class would be used like this: CountAllocaVisitor CAV; CAV.visit(function); NumAllocas = CAV.Count;
The defined has 'visit' methods for Instruction, and also for BasicBlock, Function, and Module, which recursively process all contained instructions.
Note that if you don't implement visitXXX for some instruction type, the visitXXX method for instruction superclass will be invoked. So if instructions are added in the future, they will be automatically supported, if you handle one of their superclasses.
The optional second template argument specifies the type that instruction visitation functions should return. If you specify this, you MUST provide an implementation of visitInstruction though!.
Note that this class is specifically designed as a template to avoid virtual function call overhead. Defining and using an InstVisitor is just as efficient as having your own switch statement over the instruction opcode.
Definition at line 78 of file InstVisitor.h.
Member Function Documentation
visit() [1/9]
template<typename SubClass , typename RetTy = void> void llvm::InstVisitor< SubClass, RetTy >::visit (BasicBlock & BB) inline
Definition at line 102 of file InstVisitor.h.
References llvm::BasicBlock::begin(), llvm::BasicBlock::end(), llvm::InstVisitor< SubClass, RetTy >::visit(), and llvm::InstVisitor< SubClass, RetTy >::visitBasicBlock().
visit() [2/9]
template<typename SubClass , typename RetTy = void> void llvm::InstVisitor< SubClass, RetTy >::visit (BasicBlock * BB) inline
Definition at line 110 of file InstVisitor.h.
References llvm::InstVisitor< SubClass, RetTy >::visit().
Referenced by llvm::InstVisitor< SubClass, RetTy >::visit().
visit() [3/9]
template<typename SubClass , typename RetTy = void> void llvm::InstVisitor< SubClass, RetTy >::visit (Function & F) inline
Definition at line 98 of file InstVisitor.h.
References F, llvm::InstVisitor< SubClass, RetTy >::visit(), and llvm::InstVisitor< SubClass, RetTy >::visitFunction().
visit() [4/9]
template<typename SubClass , typename RetTy = void> void llvm::InstVisitor< SubClass, RetTy >::visit (Function * F) inline
Definition at line 109 of file InstVisitor.h.
References F, and llvm::InstVisitor< SubClass, RetTy >::visit().
Referenced by llvm::InstVisitor< SubClass, RetTy >::visit().
visit() [5/9]
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visit (Instruction & I) inline
Definition at line 115 of file InstVisitor.h.
References I, and llvm_unreachable.
visit() [6/9]
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visit (Instruction * I) inline
Definition at line 111 of file InstVisitor.h.
References I, and llvm::InstVisitor< SubClass, RetTy >::visit().
Referenced by llvm::InstVisitor< SubClass, RetTy >::visit().
visit() [7/9]
template<typename SubClass , typename RetTy = void> template<class Iterator > void llvm::InstVisitor< SubClass, RetTy >::visit (Iterator Start, Iterator End) inline
Definition at line 87 of file InstVisitor.h.
References llvm::InstVisitor< SubClass, RetTy >::visit().
Referenced by llvm::IRSimilarity::IRInstructionMapper::convertToUnsignedVec(), llvm::InstVisitor< SubClass, RetTy >::visit(), llvm::InstVisitor< SubClass, RetTy >::visit(), llvm::InstVisitor< SubClass, RetTy >::visit(), and llvm::InstVisitor< SubClass, RetTy >::visit().
visit() [8/9]
template<typename SubClass , typename RetTy = void> void llvm::InstVisitor< SubClass, RetTy >::visit (Module & M) inline
Definition at line 94 of file InstVisitor.h.
References llvm::InstVisitor< SubClass, RetTy >::visit(), and llvm::InstVisitor< SubClass, RetTy >::visitModule().
visit() [9/9]
template<typename SubClass , typename RetTy = void> void llvm::InstVisitor< SubClass, RetTy >::visit (Module * M) inline
Definition at line 108 of file InstVisitor.h.
References llvm::InstVisitor< SubClass, RetTy >::visit().
Referenced by llvm::InstVisitor< SubClass, RetTy >::visit().
visitAddrSpaceCastInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitAddrSpaceCastInst (AddrSpaceCastInst & I) inline
Definition at line 188 of file InstVisitor.h.
References DELEGATE.
visitAllocaInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitAllocaInst (AllocaInst & I) inline
Definition at line 168 of file InstVisitor.h.
References DELEGATE.
visitAtomicCmpXchgInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitAtomicCmpXchgInst (AtomicCmpXchgInst & I) inline
Definition at line 171 of file InstVisitor.h.
References DELEGATE.
visitAtomicRMWInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitAtomicRMWInst (AtomicRMWInst & I) inline
Definition at line 172 of file InstVisitor.h.
References DELEGATE.
visitBasicBlock()
template<typename SubClass , typename RetTy = void> void llvm::InstVisitor< SubClass, RetTy >::visitBasicBlock (BasicBlock & BB) inline
Definition at line 143 of file InstVisitor.h.
Referenced by llvm::InstVisitor< SubClass, RetTy >::visit().
visitBinaryOperator()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitBinaryOperator (BinaryOperator & I) inline
Definition at line 262 of file InstVisitor.h.
References DELEGATE.
visitBitCastInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitBitCastInst (BitCastInst & I) inline
Definition at line 187 of file InstVisitor.h.
References DELEGATE.
visitBranchInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitBranchInst (BranchInst & I) inline
Definition at line 230 of file InstVisitor.h.
References I, and llvm::InstVisitor< SubClass, RetTy >::visitTerminator().
visitCallBase()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitCallBase (CallBase & I) inline
Definition at line 268 of file InstVisitor.h.
References DELEGATE, I, and llvm::InstVisitor< SubClass, RetTy >::visitTerminator().
visitCallBrInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitCallBrInst (CallBrInst & I) inline
Definition at line 223 of file InstVisitor.h.
References DELEGATE.
visitCallInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitCallInst (CallInst & I) inline
Definition at line 221 of file InstVisitor.h.
References DELEGATE.
visitCastInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitCastInst (CastInst & I) inline
Definition at line 260 of file InstVisitor.h.
References DELEGATE.
visitCatchPadInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitCatchPadInst (CatchPadInst & I) inline
Definition at line 199 of file InstVisitor.h.
References DELEGATE.
visitCatchReturnInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitCatchReturnInst (CatchReturnInst & I) inline
Definition at line 248 of file InstVisitor.h.
References I, and llvm::InstVisitor< SubClass, RetTy >::visitTerminator().
visitCatchSwitchInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitCatchSwitchInst (CatchSwitchInst & I) inline
Definition at line 251 of file InstVisitor.h.
References I, and llvm::InstVisitor< SubClass, RetTy >::visitTerminator().
visitCleanupPadInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitCleanupPadInst (CleanupPadInst & I) inline
Definition at line 198 of file InstVisitor.h.
References DELEGATE.
visitCleanupReturnInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitCleanupReturnInst (CleanupReturnInst & I) inline
Definition at line 245 of file InstVisitor.h.
References I, and llvm::InstVisitor< SubClass, RetTy >::visitTerminator().
visitCmpInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitCmpInst (CmpInst & I) inline
Definition at line 263 of file InstVisitor.h.
References DELEGATE.
visitDbgDeclareInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitDbgDeclareInst (DbgDeclareInst & I) inline
Definition at line 203 of file InstVisitor.h.
References DELEGATE.
visitDbgInfoIntrinsic()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitDbgInfoIntrinsic (DbgInfoIntrinsic & I) inline
Definition at line 208 of file InstVisitor.h.
References DELEGATE.
visitDbgLabelInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitDbgLabelInst (DbgLabelInst & I) inline
Definition at line 207 of file InstVisitor.h.
References DELEGATE.
visitDbgValueInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitDbgValueInst (DbgValueInst & I) inline
Definition at line 204 of file InstVisitor.h.
References DELEGATE.
visitDbgVariableIntrinsic()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitDbgVariableIntrinsic (DbgVariableIntrinsic & I) inline
Definition at line 205 of file InstVisitor.h.
References DELEGATE.
visitExtractElementInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitExtractElementInst (ExtractElementInst & I) inline
Definition at line 191 of file InstVisitor.h.
References DELEGATE.
visitExtractValueInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitExtractValueInst (ExtractValueInst & I) inline
Definition at line 194 of file InstVisitor.h.
References DELEGATE.
visitFCmpInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitFCmpInst (FCmpInst & I) inline
Definition at line 167 of file InstVisitor.h.
References DELEGATE.
visitFenceInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitFenceInst (FenceInst & I) inline
Definition at line 173 of file InstVisitor.h.
References DELEGATE.
visitFPExtInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitFPExtInst (FPExtInst & I) inline
Definition at line 180 of file InstVisitor.h.
References DELEGATE.
visitFPToSIInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitFPToSIInst (FPToSIInst & I) inline
Definition at line 182 of file InstVisitor.h.
References DELEGATE.
visitFPToUIInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitFPToUIInst (FPToUIInst & I) inline
Definition at line 181 of file InstVisitor.h.
References DELEGATE.
visitFPTruncInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitFPTruncInst (FPTruncInst & I) inline
Definition at line 179 of file InstVisitor.h.
References DELEGATE.
visitFreezeInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitFreezeInst (FreezeInst & I) inline
Definition at line 200 of file InstVisitor.h.
References DELEGATE.
visitFuncletPadInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitFuncletPadInst (FuncletPadInst & I) inline
Definition at line 197 of file InstVisitor.h.
References DELEGATE.
visitFunction()
template<typename SubClass , typename RetTy = void> void llvm::InstVisitor< SubClass, RetTy >::visitFunction (Function & F) inline
Definition at line 142 of file InstVisitor.h.
Referenced by llvm::InstVisitor< SubClass, RetTy >::visit().
visitGetElementPtrInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitGetElementPtrInst (GetElementPtrInst & I) inline
Definition at line 174 of file InstVisitor.h.
References DELEGATE.
visitICmpInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitICmpInst (ICmpInst & I) inline
Definition at line 166 of file InstVisitor.h.
References DELEGATE.
visitIndirectBrInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitIndirectBrInst (IndirectBrInst & I) inline
Definition at line 236 of file InstVisitor.h.
References I, and llvm::InstVisitor< SubClass, RetTy >::visitTerminator().
visitInsertElementInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitInsertElementInst (InsertElementInst & I) inline
Definition at line 192 of file InstVisitor.h.
References DELEGATE.
visitInsertValueInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitInsertValueInst (InsertValueInst & I) inline
Definition at line 195 of file InstVisitor.h.
References DELEGATE.
visitInstruction()
template<typename SubClass , typename RetTy = void> void llvm::InstVisitor< SubClass, RetTy >::visitInstruction (Instruction & I) inline
Definition at line 281 of file InstVisitor.h.
visitIntrinsicInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitIntrinsicInst (IntrinsicInst & I) inline
Definition at line 220 of file InstVisitor.h.
References DELEGATE.
visitIntToPtrInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitIntToPtrInst (IntToPtrInst & I) inline
Definition at line 186 of file InstVisitor.h.
References DELEGATE.
visitInvokeInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitInvokeInst (InvokeInst & I) inline
Definition at line 222 of file InstVisitor.h.
References DELEGATE.
visitLandingPadInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitLandingPadInst (LandingPadInst & I) inline
Definition at line 196 of file InstVisitor.h.
References DELEGATE.
visitLoadInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitLoadInst (LoadInst & I) inline
Definition at line 169 of file InstVisitor.h.
References DELEGATE.
visitMemCpyInlineInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitMemCpyInlineInst (MemCpyInlineInst & I) inline
Definition at line 211 of file InstVisitor.h.
References DELEGATE.
visitMemCpyInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitMemCpyInst (MemCpyInst & I) inline
Definition at line 210 of file InstVisitor.h.
References DELEGATE.
visitMemIntrinsic()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitMemIntrinsic (MemIntrinsic & I) inline
Definition at line 216 of file InstVisitor.h.
References DELEGATE.
visitMemMoveInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitMemMoveInst (MemMoveInst & I) inline
Definition at line 214 of file InstVisitor.h.
References DELEGATE.
visitMemSetInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitMemSetInst (MemSetInst & I) inline
Definition at line 209 of file InstVisitor.h.
References DELEGATE.
visitMemTransferInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitMemTransferInst (MemTransferInst & I) inline
Definition at line 215 of file InstVisitor.h.
References DELEGATE.
visitModule()
template<typename SubClass , typename RetTy = void> void llvm::InstVisitor< SubClass, RetTy >::visitModule (Module & M) inline
Definition at line 141 of file InstVisitor.h.
Referenced by llvm::InstVisitor< SubClass, RetTy >::visit().
visitPHINode()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitPHINode (PHINode & I) inline
Definition at line 175 of file InstVisitor.h.
References DELEGATE.
visitPtrToIntInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitPtrToIntInst (PtrToIntInst & I) inline
Definition at line 185 of file InstVisitor.h.
References DELEGATE.
visitResumeInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitResumeInst (ResumeInst & I) inline
Definition at line 239 of file InstVisitor.h.
References I, and llvm::InstVisitor< SubClass, RetTy >::visitTerminator().
visitReturnInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitReturnInst (ReturnInst & I) inline
Definition at line 227 of file InstVisitor.h.
References I, and llvm::InstVisitor< SubClass, RetTy >::visitTerminator().
visitSelectInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitSelectInst (SelectInst & I) inline
Definition at line 189 of file InstVisitor.h.
References DELEGATE.
visitSExtInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitSExtInst (SExtInst & I) inline
Definition at line 178 of file InstVisitor.h.
References DELEGATE.
visitShuffleVectorInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitShuffleVectorInst (ShuffleVectorInst & I) inline
Definition at line 193 of file InstVisitor.h.
References DELEGATE.
visitSIToFPInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitSIToFPInst (SIToFPInst & I) inline
Definition at line 184 of file InstVisitor.h.
References DELEGATE.
visitStoreInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitStoreInst (StoreInst & I) inline
Definition at line 170 of file InstVisitor.h.
References DELEGATE.
visitSwitchInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitSwitchInst (SwitchInst & I) inline
Definition at line 233 of file InstVisitor.h.
References I, and llvm::InstVisitor< SubClass, RetTy >::visitTerminator().
visitTerminator()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitTerminator (Instruction & I) inline
Definition at line 254 of file InstVisitor.h.
References DELEGATE.
Referenced by llvm::InstVisitor< SubClass, RetTy >::visitBranchInst(), llvm::InstVisitor< SubClass, RetTy >::visitCallBase(), llvm::InstVisitor< SubClass, RetTy >::visitCatchReturnInst(), llvm::InstVisitor< SubClass, RetTy >::visitCatchSwitchInst(), llvm::InstVisitor< SubClass, RetTy >::visitCleanupReturnInst(), llvm::InstVisitor< SubClass, RetTy >::visitIndirectBrInst(), llvm::InstVisitor< SubClass, RetTy >::visitResumeInst(), llvm::InstVisitor< SubClass, RetTy >::visitReturnInst(), llvm::InstVisitor< SubClass, RetTy >::visitSwitchInst(), and llvm::InstVisitor< SubClass, RetTy >::visitUnreachableInst().
visitTruncInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitTruncInst (TruncInst & I) inline
Definition at line 176 of file InstVisitor.h.
References DELEGATE.
visitUIToFPInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitUIToFPInst (UIToFPInst & I) inline
Definition at line 183 of file InstVisitor.h.
References DELEGATE.
visitUnaryInstruction()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitUnaryInstruction (UnaryInstruction & I) inline
Definition at line 264 of file InstVisitor.h.
References DELEGATE.
visitUnaryOperator()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitUnaryOperator (UnaryOperator & I) inline
Definition at line 261 of file InstVisitor.h.
References DELEGATE.
visitUnreachableInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitUnreachableInst (UnreachableInst & I) inline
Definition at line 242 of file InstVisitor.h.
References I, and llvm::InstVisitor< SubClass, RetTy >::visitTerminator().
visitVAArgInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitVAArgInst (VAArgInst & I) inline
Definition at line 190 of file InstVisitor.h.
References DELEGATE.
visitVACopyInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitVACopyInst (VACopyInst & I) inline
Definition at line 219 of file InstVisitor.h.
References DELEGATE.
visitVAEndInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitVAEndInst (VAEndInst & I) inline
Definition at line 218 of file InstVisitor.h.
References DELEGATE.
visitVAStartInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitVAStartInst (VAStartInst & I) inline
Definition at line 217 of file InstVisitor.h.
References DELEGATE.
visitZExtInst()
template<typename SubClass , typename RetTy = void> RetTy llvm::InstVisitor< SubClass, RetTy >::visitZExtInst (ZExtInst & I) inline
Definition at line 177 of file InstVisitor.h.
References DELEGATE.
The documentation for this class was generated from the following file:
include/llvm/IR/InstVisitor.h