LLVM: llvm::orc::CompileOnDemandLayer Class Reference
llvm::orc::CompileOnDemandLayer Class Reference
#include "llvm/ExecutionEngine/Orc/CompileOnDemandLayer.h"
Public Types
using IndirectStubsManagerBuilder
Builder for IndirectStubsManagers.
using GlobalValueSet = std::set<const GlobalValue *>
using PartitionFunction
Partitioning function.
Public Member Functions
CompileOnDemandLayer (ExecutionSession &ES, IRLayer &BaseLayer, LazyCallThroughManager &LCTMgr, IndirectStubsManagerBuilder BuildIndirectStubsManager)
Construct a CompileOnDemandLayer.
void setPartitionFunction (PartitionFunction Partition)
Sets the partition function.
void setImplMap (ImplSymbolMap *Imp)
Sets the ImplSymbolMap.
void emit (std::unique_ptr< MaterializationResponsibility > R, ThreadSafeModule TSM) override
Emits the given module.
Public Member Functions inherited from llvm::orc::IRLayer
IRLayer (ExecutionSession &ES, const IRSymbolMapper::ManglingOptions *&MO)
virtual ~IRLayer ()
ExecutionSession & getExecutionSession ()
Returns the ExecutionSession for this layer.
const IRSymbolMapper::ManglingOptions *& getManglingOptions () const
Get the mangling options for this layer.
void setCloneToNewContextOnEmit (bool CloneToNewContextOnEmit)
Sets the CloneToNewContextOnEmit flag (false by default).
bool getCloneToNewContextOnEmit () const
Returns the current value of the CloneToNewContextOnEmit flag.
virtual Error add (ResourceTrackerSP RT, ThreadSafeModule TSM)
Add a MaterializatinoUnit representing the given IR to the JITDylib targeted by the given tracker.
Error add (JITDylib &JD, ThreadSafeModule TSM)
Adds a MaterializationUnit representing the given IR to the given JITDylib.
Static Public Member Functions
static Optional< GlobalValueSet > compileRequested (GlobalValueSet Requested)
Off-the-shelf partitioning which compiles all requested symbols (usually a single function at a time).
static Optional< GlobalValueSet > compileWholeModule (GlobalValueSet Requested)
Off-the-shelf partitioning which compiles whole modules whenever any symbol in them is requested.
Friends
class PartitioningIRMaterializationUnit
Detailed Description
Definition at line 56 of file CompileOnDemandLayer.h.
Member Typedef Documentation
GlobalValueSet
using llvm::orc::CompileOnDemandLayer::GlobalValueSet = std::set<const GlobalValue *>
Definition at line 64 of file CompileOnDemandLayer.h.
IndirectStubsManagerBuilder
using llvm::orc::CompileOnDemandLayer::IndirectStubsManagerBuilder
Initial value:
      std::function<std::unique_ptr<IndirectStubsManager>()>
Builder for IndirectStubsManagers.
Definition at line 61 of file CompileOnDemandLayer.h.
PartitionFunction
using llvm::orc::CompileOnDemandLayer::PartitionFunction
Initial value:
      std::function<Optional<GlobalValueSet>(GlobalValueSet Requested)>
Partitioning function.
Definition at line 67 of file CompileOnDemandLayer.h.
Constructor & Destructor Documentation
CompileOnDemandLayer()
llvm::orc::CompileOnDemandLayer::CompileOnDemandLayer (ExecutionSession & ES, IRLayer & BaseLayer, LazyCallThroughManager & LCTMgr, IndirectStubsManagerBuilder BuildIndirectStubsManager)
Construct a CompileOnDemandLayer.
Definition at line 115 of file CompileOnDemandLayer.cpp.
Member Function Documentation
compileRequested()
Optional< CompileOnDemandLayer::GlobalValueSet > llvm::orc::CompileOnDemandLayer::compileRequested (GlobalValueSet Requested) static
Off-the-shelf partitioning which compiles all requested symbols (usually a single function at a time).
Definition at line 106 of file CompileOnDemandLayer.cpp.
compileWholeModule()
Optional< CompileOnDemandLayer::GlobalValueSet > llvm::orc::CompileOnDemandLayer::compileWholeModule (GlobalValueSet Requested) static
Off-the-shelf partitioning which compiles whole modules whenever any symbol in them is requested.
Definition at line 111 of file CompileOnDemandLayer.cpp.
References llvm::None.
emit()
void llvm::orc::CompileOnDemandLayer::emit (std::unique_ptr< MaterializationResponsibility > R, ThreadSafeModule TSM) override virtual
Emits the given module.
This should not be called by clients: it will be called by the JIT when a definition added via the add method is requested.
Implements llvm::orc::IRLayer.
Definition at line 129 of file CompileOnDemandLayer.cpp.
References assert(), llvm::orc::IRLayer::getExecutionSession(), llvm::orc::IRLayer::getManglingOptions(), llvm::orc::lazyReexports(), llvm::orc::MatchAllSymbols, Name, llvm::orc::reexports(), llvm::orc::ExecutionSession::reportError(), and llvm::orc::ThreadSafeModule::withModuleDo().
setImplMap()
void llvm::orc::CompileOnDemandLayer::setImplMap (ImplSymbolMap * Imp)
Sets the ImplSymbolMap.
Definition at line 126 of file CompileOnDemandLayer.cpp.
setPartitionFunction()
void llvm::orc::CompileOnDemandLayer::setPartitionFunction (PartitionFunction Partition)
Sets the partition function.
Definition at line 122 of file CompileOnDemandLayer.cpp.
Friends And Related Symbol Documentation
PartitioningIRMaterializationUnit
friend class PartitioningIRMaterializationUnit friend
Definition at line 57 of file CompileOnDemandLayer.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/CompileOnDemandLayer.h
lib/ExecutionEngine/Orc/CompileOnDemandLayer.cpp