LLVM: lib/DebugInfo/DWARF/DWARFDebugLine.cpp File Reference
DWARFDebugLine.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugLine.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/DebugInfo/DWARF/DWARFDataExtractor.h"
#include "llvm/DebugInfo/DWARF/DWARFDie.h"
#include "llvm/DebugInfo/DWARF/DWARFFormValue.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cinttypes>
#include <cstdint>
#include <cstdio>
#include <utility>
Typedefs
using FileLineInfoKind = DILineInfoSpecifier::FileLineInfoKind
Functions
static bool versionIsSupported (uint16_t Version)
static Error parseV2DirFileTables (const DWARFDataExtractor &DebugLineData, uint64_t *OffsetPtr, DWARFDebugLine::ContentTypeTracker &ContentTypes, std::vector< DWARFFormValue > &IncludeDirectories, std::vector< DWARFDebugLine::FileNameEntry > &FileNames)
static llvm::Expected< ContentDescriptors > parseV5EntryFormat (const DWARFDataExtractor &DebugLineData, uint64_t *OffsetPtr, DWARFDebugLine::ContentTypeTracker *ContentTypes)
static Error parseV5DirFileTables (const DWARFDataExtractor &DebugLineData, uint64_t *OffsetPtr, const dwarf::FormParams &FormParams, const DWARFContext &Ctx, const DWARFUnit *U, DWARFDebugLine::ContentTypeTracker &ContentTypes, std::vector< DWARFFormValue > &IncludeDirectories, std::vector< DWARFDebugLine::FileNameEntry > &FileNames)
static StringRef getOpcodeName (uint8_t Opcode, uint8_t OpcodeBase)
template<typename T >
static Optional< T > parseULEB128 (DWARFDataExtractor &Data, DataExtractor::Cursor &Cursor)
Parse a ULEB128 using the specified Cursor.
static bool isPathAbsoluteOnWindowsOrPosix (const Twine &Path)
static DWARFDebugLine::SectionParser::LineToUnitMap buildLineToUnitMap (DWARFUnitVector::iterator_range Units)
Typedef Documentation
FileLineInfoKind
using FileLineInfoKind = DILineInfoSpecifier::FileLineInfoKind
Definition at line 32 of file DWARFDebugLine.cpp.
Function Documentation
buildLineToUnitMap()
static DWARFDebugLine::SectionParser::LineToUnitMap buildLineToUnitMap (DWARFUnitVector::iterator_range Units) static
Definition at line 1427 of file DWARFDebugLine.cpp.
References llvm::dwarf::toSectionOffset().
Referenced by llvm::DWARFDebugLine::SectionParser::SectionParser().
getOpcodeName()
static StringRef getOpcodeName (uint8_t Opcode, uint8_t OpcodeBase) static
Definition at line 604 of file DWARFDebugLine.cpp.
References assert(), and llvm::dwarf::LNStandardString().
isPathAbsoluteOnWindowsOrPosix()
static bool isPathAbsoluteOnWindowsOrPosix (const Twine & Path) static
Definition at line 1343 of file DWARFDebugLine.cpp.
References llvm::sys::path::is_absolute(), llvm::sys::path::posix, and llvm::sys::path::windows.
Referenced by llvm::DWARFDebugLine::Prologue::getFileNameByIndex().
parseULEB128()
template<typename T > static Optional< T > parseULEB128 (DWARFDataExtractor & Data, DataExtractor::Cursor & Cursor) static
Parse a ULEB128 using the specified Cursor.
Returns
the parsed value on success, or None if Cursor is in a failing state.
Definition at line 720 of file DWARFDebugLine.cpp.
References llvm::Data, and llvm::None.
parseV2DirFileTables()
static Error parseV2DirFileTables (const DWARFDataExtractor & DebugLineData, uint64_t * OffsetPtr, DWARFDebugLine::ContentTypeTracker & ContentTypes, std::vector< DWARFFormValue > & IncludeDirectories, std::vector< DWARFDebugLine::FileNameEntry > & FileNames) static
Definition at line 183 of file DWARFDebugLine.cpp.
References llvm::consumeError(), llvm::DWARFFormValue::createFromPValue(), llvm::createStringError(), llvm::StringRef::data(), llvm::DWARFDebugLine::FileNameEntry::DirIdx, llvm::StringRef::empty(), llvm::DataExtractor::getCStrRef(), llvm::DataExtractor::getULEB128(), llvm::DWARFDebugLine::ContentTypeTracker::HasLength, llvm::DWARFDebugLine::ContentTypeTracker::HasModTime, llvm::invalid_argument, llvm::DWARFDebugLine::FileNameEntry::Length, llvm::DWARFDebugLine::FileNameEntry::ModTime, llvm::DWARFDebugLine::FileNameEntry::Name, Name, and llvm::Error::success().
Referenced by llvm::DWARFDebugLine::Prologue::parse().
parseV5DirFileTables()
static Error parseV5DirFileTables (const DWARFDataExtractor & DebugLineData, uint64_t * OffsetPtr, const dwarf::FormParams & FormParams, const DWARFContext & Ctx, const DWARFUnit * U, DWARFDebugLine::ContentTypeTracker & ContentTypes, std::vector< DWARFFormValue > & IncludeDirectories, std::vector< DWARFDebugLine::FileNameEntry > & FileNames) static
Definition at line 268 of file DWARFDebugLine.cpp.
References llvm::DWARFDebugLine::FileNameEntry::Checksum, llvm::createStringError(), llvm::DWARFDebugLine::FileNameEntry::DirIdx, llvm::DataExtractor::getULEB128(), I, llvm::invalid_argument, llvm::DWARFDebugLine::FileNameEntry::Length, llvm::DWARFDebugLine::FileNameEntry::ModTime, llvm::DWARFDebugLine::FileNameEntry::Name, parseV5EntryFormat(), llvm::DWARFDebugLine::FileNameEntry::Source, and llvm::Error::success().
Referenced by llvm::DWARFDebugLine::Prologue::parse().
parseV5EntryFormat()
static llvm::Expected< ContentDescriptors > parseV5EntryFormat (const DWARFDataExtractor & DebugLineData, uint64_t * OffsetPtr, DWARFDebugLine::ContentTypeTracker * ContentTypes) static
Definition at line 237 of file DWARFDebugLine.cpp.
References llvm::c_str(), llvm::createStringError(), llvm::DataExtractor::getU8(), llvm::DataExtractor::getULEB128(), I, llvm::invalid_argument, llvm::Error::success(), llvm::dwarf::toString(), and llvm::DWARFDebugLine::ContentTypeTracker::trackContentType().
Referenced by parseV5DirFileTables().
versionIsSupported()
static bool versionIsSupported (uint16_t Version) static
Definition at line 45 of file DWARFDebugLine.cpp.
Referenced by llvm::DWARFDebugLine::Prologue::dump(), and llvm::DWARFDebugLine::Prologue::parse().