LLVM: lib/IR/Globals.cpp File Reference
Globals.cpp File Reference
#include "LLVMContextImpl.h"
#include "llvm/ADT/Triple.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/IR/Value.def"
Macros
#define HANDLE_GLOBAL_VALUE(NAME)
#define HANDLE_GLOBAL_VALUE(NAME)
Typedefs
using SanitizerMetadata = GlobalValue::SanitizerMetadata
Functions
template<typename Operation >
static const GlobalObject * findBaseObject (const Constant *C, DenseSet< const GlobalAlias * > &Aliases, const Operation &Op)
Macro Definition Documentation
HANDLE_GLOBAL_VALUE [1/2]
#define HANDLE_GLOBAL_VALUE (NAME)
Value:
  case Value::NAME##Val:                                                       \
    return static_cast<NAME *>(this)->removeFromParent();
HANDLE_GLOBAL_VALUE [2/2]
#define HANDLE_GLOBAL_VALUE (NAME)
Value:
  case Value::NAME##Val:                                                       \
    return static_cast<NAME *>(this)->eraseFromParent();
Typedef Documentation
SanitizerMetadata
using SanitizerMetadata = GlobalValue::SanitizerMetadata
Definition at line 224 of file Globals.cpp.
Function Documentation
findBaseObject()
template<typename Operation > static const GlobalObject * findBaseObject (const Constant * C, DenseSet< const GlobalAlias * > & Aliases, const Operation & Op) static
Definition at line 321 of file Globals.cpp.
References llvm::CallingConv::C, findBaseObject(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), LHS, and RHS.
Referenced by llvm::GlobalIFunc::applyAlongResolverPath(), findBaseObject(), llvm::GlobalAlias::getAliaseeObject(), llvm::GlobalValue::getAliaseeObject(), and llvm::GlobalIFunc::getResolverFunction().