LLVM: Global Aliases
Global Aliases
LLVM-C: C interface to LLVM » Core » Values » Constants
Functions
LLVM_ATTRIBUTE_C_DEPRECATED (LLVMValueRef LLVMAddAlias(LLVMModuleRef M, LLVMTypeRef Ty, LLVMValueRef Aliasee, const char *Name), "Use LLVMAddAlias2 instead to support opaque pointers")
LLVMValueRef LLVMAddAlias2 (LLVMModuleRef M, LLVMTypeRef ValueTy, unsigned AddrSpace, LLVMValueRef Aliasee, const char *Name)
Add a GlobalAlias with the given value type, address space and aliasee.
LLVMValueRef LLVMGetNamedGlobalAlias (LLVMModuleRef M, const char *Name, size_t NameLen)
Obtain a GlobalAlias value from a Module by its name.
LLVMValueRef LLVMGetFirstGlobalAlias (LLVMModuleRef M)
Obtain an iterator to the first GlobalAlias in a Module.
LLVMValueRef LLVMGetLastGlobalAlias (LLVMModuleRef M)
Obtain an iterator to the last GlobalAlias in a Module.
LLVMValueRef LLVMGetNextGlobalAlias (LLVMValueRef GA)
Advance a GlobalAlias iterator to the next GlobalAlias.
LLVMValueRef LLVMGetPreviousGlobalAlias (LLVMValueRef GA)
Decrement a GlobalAlias iterator to the previous GlobalAlias.
LLVMValueRef LLVMAliasGetAliasee (LLVMValueRef Alias)
Retrieve the target value of an alias.
void LLVMAliasSetAliasee (LLVMValueRef Alias, LLVMValueRef Aliasee)
Set the target value of an alias.
Detailed Description
This group contains function that operate on global alias values.
See also
llvm::GlobalAlias
Function Documentation
LLVM_ATTRIBUTE_C_DEPRECATED()
LLVM_ATTRIBUTE_C_DEPRECATED (LLVMValueRef LLVMAddAliasLLVMModuleRef M, LLVMTypeRef Ty, LLVMValueRef Aliasee, const char *Name, "Use LLVMAddAlias2 instead to support opaque pointers")
LLVMAddAlias2()
LLVMValueRef LLVMAddAlias2 (LLVMModuleRef M, LLVMTypeRef ValueTy, unsigned AddrSpace, LLVMValueRef Aliasee, const char * Name)
Add a GlobalAlias with the given value type, address space and aliasee.
See also
llvm::GlobalAlias::create()
Definition at line 2237 of file Core.cpp.
References llvm::GlobalAlias::create(), llvm::GlobalValue::ExternalLinkage, Name, llvm::unwrap(), and llvm::wrap().
LLVMAliasGetAliasee()
LLVMValueRef LLVMAliasGetAliasee (LLVMValueRef Alias)
Retrieve the target value of an alias.
Definition at line 2282 of file Core.cpp.
References llvm::wrap().
LLVMAliasSetAliasee()
void LLVMAliasSetAliasee (LLVMValueRef Alias, LLVMValueRef Aliasee)
Set the target value of an alias.
Definition at line 2286 of file Core.cpp.
LLVMGetFirstGlobalAlias()
LLVMValueRef LLVMGetFirstGlobalAlias (LLVMModuleRef M)
Obtain an iterator to the first GlobalAlias in a Module.
See also
llvm::Module::alias_begin()
Definition at line 2250 of file Core.cpp.
References I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetLastGlobalAlias()
LLVMValueRef LLVMGetLastGlobalAlias (LLVMModuleRef M)
Obtain an iterator to the last GlobalAlias in a Module.
See also
llvm::Module::alias_end()
Definition at line 2258 of file Core.cpp.
References I, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMGetNamedGlobalAlias()
LLVMValueRef LLVMGetNamedGlobalAlias (LLVMModuleRef M, const char * Name, size_t NameLen)
Obtain a GlobalAlias value from a Module by its name.
The returned value corresponds to a llvm::GlobalAlias value.
See also
llvm::Module::getNamedAlias()
Definition at line 2245 of file Core.cpp.
References Name, llvm::unwrap(), and llvm::wrap().
LLVMGetNextGlobalAlias()
LLVMValueRef LLVMGetNextGlobalAlias (LLVMValueRef GA)
Advance a GlobalAlias iterator to the next GlobalAlias.
Returns NULL if the iterator was already at the end and there are no more global aliases.
Definition at line 2266 of file Core.cpp.
References llvm::Module::alias_end(), llvm::GlobalValue::getParent(), I, and llvm::wrap().
LLVMGetPreviousGlobalAlias()
LLVMValueRef LLVMGetPreviousGlobalAlias (LLVMValueRef GA)
Decrement a GlobalAlias iterator to the previous GlobalAlias.
Returns NULL if the iterator was already at the beginning and there are no previous global aliases.
Definition at line 2274 of file Core.cpp.
References llvm::Module::alias_begin(), llvm::GlobalValue::getParent(), I, and llvm::wrap().