LLVM: lib/InterfaceStub/IFSHandler.cpp File Reference
IFSHandler.cpp File Reference
#include "llvm/InterfaceStub/IFSHandler.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/InterfaceStub/IFSStub.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/GlobPattern.h"
#include "llvm/Support/LineIterator.h"
#include "llvm/Support/YAMLTraits.h"
#include <functional>
Classes
struct llvm::yaml::ScalarEnumerationTraits< IFSSymbolType >
YAML traits for ELFSymbolType.
struct llvm::yaml::ScalarTraits< IFSEndiannessType >
struct llvm::yaml::ScalarTraits< IFSBitWidthType >
struct llvm::yaml::MappingTraits< IFSTarget >
struct llvm::yaml::MappingTraits< IFSSymbol >
YAML traits for ELFSymbol.
struct llvm::yaml::MappingTraits< IFSStub >
YAML traits for ELFStub objects.
struct llvm::yaml::MappingTraits< IFSStubTriple >
YAML traits for ELFStubTriple objects.
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::yaml
Functions
bool usesTriple (StringRef Buf)
Attempt to determine if a Text stub uses target triple.
Function Documentation
usesTriple()
bool usesTriple (StringRef Buf)
Attempt to determine if a Text stub uses target triple.
Definition at line 166 of file IFSHandler.cpp.
References llvm::StringRef::contains(), I, llvm::line_iterator::is_at_eof(), llvm::StringRef::startswith(), and llvm::StringRef::trim().
Referenced by llvm::ifs::readIFSFromBuffer().