LLVM: lib/Analysis/ImportedFunctionsInliningStatistics.cpp File Reference
ImportedFunctionsInliningStatistics.cpp File Reference
#include "llvm/Analysis/Utils/ImportedFunctionsInliningStatistics.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <iomanip>
#include <sstream>
#include <string>
Functions
static std::string getStatString (const char *Msg, int32_t Fraction, int32_t All, const char *PercentageOfMsg, bool LineEnd=true)
Variables
cl::opt< InlinerFunctionImportStatsOpts > InlinerFunctionImportStats ("inliner-function-import-stats", cl::init(InlinerFunctionImportStatsOpts::No), cl::values(clEnumValN(InlinerFunctionImportStatsOpts::Basic, "basic", "basic statistics"), clEnumValN(InlinerFunctionImportStatsOpts::Verbose, "verbose", "printing of statistics for each inlined function")), cl::Hidden, cl::desc("Enable inliner stats for imported functions"))
Function Documentation
getStatString()
static std::string getStatString (const char * Msg, int32_t Fraction, int32_t All, const char * PercentageOfMsg, bool LineEnd = true) static
Definition at line 82 of file ImportedFunctionsInliningStatistics.cpp.
References llvm::All.
Referenced by llvm::ImportedFunctionsInliningStatistics::dump().
Variable Documentation
InlinerFunctionImportStats
cl::opt< InlinerFunctionImportStatsOpts > InlinerFunctionImportStats("inliner-function-import-stats", cl::init(InlinerFunctionImportStatsOpts::No), cl::values(clEnumValN(InlinerFunctionImportStatsOpts::Basic, "basic", "basic statistics"), clEnumValN(InlinerFunctionImportStatsOpts::Verbose, "verbose", "printing of statistics for each inlined function")), cl::Hidden, cl::desc("Enable inliner stats for imported functions")) ("inliner-function-import-stats" , cl::init(InlinerFunctionImportStatsOpts::No) , cl::values(clEnumValN(InlinerFunctionImportStatsOpts::Basic, "basic", "basic statistics"), clEnumValN(InlinerFunctionImportStatsOpts::Verbose, "verbose", "printing of statistics for each inlined function")) , cl::Hidden , cl::desc("Enable inliner stats for imported functions"))
Referenced by llvm::LegacyInlinerBase::doFinalization(), llvm::LegacyInlinerBase::doInitialization(), llvm::InlineAdvisor::InlineAdvisor(), inlineCallIfPossible(), and llvm::InlineAdvisor::~InlineAdvisor().