LLVM: lib/Object/IRSymtab.cpp File Reference
IRSymtab.cpp File Reference
#include "llvm/Object/IRSymtab.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Bitcode/BitcodeReader.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/StringTableBuilder.h"
#include "llvm/Object/ModuleSymbolTable.h"
#include "llvm/Object/SymbolicFile.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/StringSaver.h"
#include "llvm/Support/VCSRevision.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <string>
#include <utility>
#include <vector>
#include "llvm/IR/RuntimeLibcalls.def"
Macros
#define HANDLE_LIBCALL(code, name) name,
Functions
static Expected< FileContents > upgrade (ArrayRef< BitcodeModule > BMs)
Variables
cl::opt< bool > DisableBitcodeVersionUpgrade ("disable-bitcode-version-upgrade", cl::init(false), cl::Hidden, cl::desc("Disable automatic bitcode upgrade for version mismatch"))
static const char * PreservedSymbols []
Macro Definition Documentation
HANDLE_LIBCALL
#define HANDLE_LIBCALL (code, name) name,
Function Documentation
upgrade()
static Expected< FileContents > upgrade (ArrayRef< BitcodeModule > BMs) static
Definition at line 373 of file IRSymtab.cpp.
References llvm::irsymtab::build(), E, llvm::StringTableBuilder::finalizeInOrder(), llvm::StringTableBuilder::getSize(), llvm::StringTableBuilder::RAW, and llvm::StringTableBuilder::write().
Referenced by llvm::irsymtab::readBitcode().
Variable Documentation
DisableBitcodeVersionUpgrade
cl::opt< bool > DisableBitcodeVersionUpgrade("disable-bitcode-version-upgrade", cl::init(false), cl::Hidden, cl::desc("Disable automatic bitcode upgrade for version mismatch")) ("disable-bitcode-version-upgrade" , cl::init(false) , cl::Hidden , cl::desc("Disable automatic bitcode upgrade for version mismatch"))
Referenced by llvm::irsymtab::readBitcode().
PreservedSymbols
const char* PreservedSymbols[] static
Initial value:
= {
#define HANDLE_LIBCALL(code, name)
    "__ssp_canary_word",
    "__stack_chk_guard",
}
Definition at line 48 of file IRSymtab.cpp.