LLVM: llvm::SPIRV Namespace Reference
llvm::SPIRV Namespace Reference
Classes
class DTSortableEntry
struct ModuleAnalysisInfo
Typedefs
using InstrList = SmallVector<MachineInstr *>
using LocalToGlobalRegTable = std::map<Register, Register>
using RegisterAliasMapTy
Enumerations
enum class Capability : uint32_t {
Matrix = 0 , Shader = 1 , Geometry = 2 , Tessellation = 3 ,
Addresses = 4 , Linkage = 5 , Kernel = 6 , Vector16 = 7 ,
Float16Buffer = 8 , Float16 = 9 , Float64 = 10 , Int64 = 11 ,
Int64Atomics = 12 , ImageBasic = 13 , ImageReadWrite = 14 , ImageMipmap = 15 ,
Pipes = 17 , Groups = 18 , DeviceEnqueue = 19 , LiteralSampler = 20 ,
AtomicStorage = 21 , Int16 = 22 , TessellationPointSize = 23 , GeometryPointSize = 24 ,
ImageGatherExtended = 25 , StorageImageMultisample = 27 , UniformBufferArrayDynamicIndexing = 28 , SampledImageArrayDymnamicIndexing = 29 ,
ClipDistance = 32 , CullDistance = 33 , ImageCubeArray = 34 , SampleRateShading = 35 ,
ImageRect = 36 , SampledRect = 37 , GenericPointer = 38 , Int8 = 39 ,
InputAttachment = 40 , SparseResidency = 41 , MinLod = 42 , Sampled1D = 43 ,
Image1D = 44 , SampledCubeArray = 45 , SampledBuffer = 46 , ImageBuffer = 47 ,
ImageMSArray = 48 , StorageImageExtendedFormats = 49 , ImageQuery = 50 , DerivativeControl = 51 ,
InterpolationFunction = 52 , TransformFeedback = 53 , GeometryStreams = 54 , StorageImageReadWithoutFormat = 55 ,
StorageImageWriteWithoutFormat = 56 , MultiViewport = 57 , SubgroupDispatch = 58 , NamedBarrier = 59 ,
PipeStorage = 60 , GroupNonUniform = 61 , GroupNonUniformVote = 62 , GroupNonUniformArithmetic = 63 ,
GroupNonUniformBallot = 64 , GroupNonUniformShuffle = 65 , GroupNonUniformShuffleRelative = 66 , GroupNonUniformClustered = 67 ,
GroupNonUniformQuad = 68 , SubgroupBallotKHR = 4423 , DrawParameters = 4427 , SubgroupVoteKHR = 4431 ,
StorageBuffer16BitAccess = 4433 , StorageUniform16 = 4434 , StoragePushConstant16 = 4435 , StorageInputOutput16 = 4436 ,
DeviceGroup = 4437 , MultiView = 4439 , VariablePointersStorageBuffer = 4441 , VariablePointers = 4442 ,
AtomicStorageOps = 4445 , SampleMaskPostDepthCoverage = 4447 , StorageBuffer8BitAccess = 4448 , UniformAndStorageBuffer8BitAccess = 4449 ,
StoragePushConstant8 = 4450 , DenormPreserve = 4464 , DenormFlushToZero = 4465 , SignedZeroInfNanPreserve = 4466 ,
RoundingModeRTE = 4467 , RoundingModeRTZ = 4468 , Float16ImageAMD = 5008 , ImageGatherBiasLodAMD = 5009 ,
FragmentMaskAMD = 5010 , StencilExportEXT = 5013 , ImageReadWriteLodAMD = 5015 , SampleMaskOverrideCoverageNV = 5249 ,
GeometryShaderPassthroughNV = 5251 , ShaderViewportIndexLayerEXT = 5254 , ShaderViewportMaskNV = 5255 , ShaderStereoViewNV = 5259 ,
PerViewAttributesNV = 5260 , FragmentFullyCoveredEXT = 5265 , MeshShadingNV = 5266 , ShaderNonUniformEXT = 5301 ,
RuntimeDescriptorArrayEXT = 5302 , InputAttachmentArrayDynamicIndexingEXT = 5303 , UniformTexelBufferArrayDynamicIndexingEXT = 5304 , StorageTexelBufferArrayDynamicIndexingEXT = 5305 ,
UniformBufferArrayNonUniformIndexingEXT = 5306 , SampledImageArrayNonUniformIndexingEXT = 5307 , StorageBufferArrayNonUniformIndexingEXT = 5308 , StorageImageArrayNonUniformIndexingEXT = 5309 ,
InputAttachmentArrayNonUniformIndexingEXT = 5310 , UniformTexelBufferArrayNonUniformIndexingEXT = 5311 , StorageTexelBufferArrayNonUniformIndexingEXT = 5312 , RayTracingNV = 5340 ,
SubgroupShuffleINTEL = 5568 , SubgroupBufferBlockIOINTEL = 5569 , SubgroupImageBlockIOINTEL = 5570 , SubgroupImageMediaBlockIOINTEL = 5579 ,
SubgroupAvcMotionEstimationINTEL = 5696 , SubgroupAvcMotionEstimationIntraINTEL = 5697 , SubgroupAvcMotionEstimationChromaINTEL = 5698 , GroupNonUniformPartitionedNV = 5297 ,
VulkanMemoryModelKHR = 5345 , VulkanMemoryModelDeviceScopeKHR = 5346 , ImageFootprintNV = 5282 , FragmentBarycentricNV = 5284 ,
ComputeDerivativeGroupQuadsNV = 5288 , ComputeDerivativeGroupLinearNV = 5350 , FragmentDensityEXT = 5291 , PhysicalStorageBufferAddressesEXT = 5347 ,
CooperativeMatrixNV = 5357
}
enum class SourceLanguage : uint32_t {
Unknown = 0 , ESSL = 1 , GLSL = 2 , OpenCL_C = 3 ,
OpenCL_CPP = 4 , HLSL = 5
}
enum class AddressingModel : uint32_t { Logical = 0 , Physical32 = 1 , Physical64 = 2 , PhysicalStorageBuffer64EXT = 5348 }
enum class ExecutionModel : uint32_t {
Vertex = 0 , TessellationControl = 1 , TessellationEvaluation = 2 , Geometry = 3 ,
Fragment = 4 , GLCompute = 5 , Kernel = 6 , TaskNV = 5267 ,
MeshNV = 5268 , RayGenerationNV = 5313 , IntersectionNV = 5314 , AnyHitNV = 5315 ,
ClosestHitNV = 5316 , MissNV = 5317 , CallableNV = 5318
}
enum class MemoryModel : uint32_t { Simple = 0 , GLSL450 = 1 , OpenCL = 2 , VulkanKHR = 3 }
enum class ExecutionMode : uint32_t {
Invocations = 0 , SpacingEqual = 1 , SpacingFractionalEven = 2 , SpacingFractionalOdd = 3 ,
VertexOrderCw = 4 , VertexOrderCcw = 5 , PixelCenterInteger = 6 , OriginUpperLeft = 7 ,
OriginLowerLeft = 8 , EarlyFragmentTests = 9 , PointMode = 10 , Xfb = 11 ,
DepthReplacing = 12 , DepthGreater = 14 , DepthLess = 15 , DepthUnchanged = 16 ,
LocalSize = 17 , LocalSizeHint = 18 , InputPoints = 19 , InputLines = 20 ,
InputLinesAdjacency = 21 , Triangles = 22 , InputTrianglesAdjacency = 23 , Quads = 24 ,
Isolines = 25 , OutputVertices = 26 , OutputPoints = 27 , OutputLineStrip = 28 ,
OutputTriangleStrip = 29 , VecTypeHint = 30 , ContractionOff = 31 , Initializer = 33 ,
Finalizer = 34 , SubgroupSize = 35 , SubgroupsPerWorkgroup = 36 , SubgroupsPerWorkgroupId = 37 ,
LocalSizeId = 38 , LocalSizeHintId = 39 , PostDepthCoverage = 4446 , DenormPreserve = 4459 ,
DenormFlushToZero = 4460 , SignedZeroInfNanPreserve = 4461 , RoundingModeRTE = 4462 , RoundingModeRTZ = 4463 ,
StencilRefReplacingEXT = 5027 , OutputLinesNV = 5269 , DerivativeGroupQuadsNV = 5289 , DerivativeGroupLinearNV = 5290 ,
OutputTrianglesNV = 5298
}
enum class StorageClass : uint32_t {
UniformConstant = 0 , Input = 1 , Uniform = 2 , Output = 3 ,
Workgroup = 4 , CrossWorkgroup = 5 , Private = 6 , Function = 7 ,
Generic = 8 , PushConstant = 9 , AtomicCounter = 10 , Image = 11 ,
StorageBuffer = 12 , CallableDataNV = 5328 , IncomingCallableDataNV = 5329 , RayPayloadNV = 5338 ,
HitAttributeNV = 5339 , IncomingRayPayloadNV = 5342 , ShaderRecordBufferNV = 5343 , PhysicalStorageBufferEXT = 5349
}
enum class Dim : uint32_t {
DIM_1D = 0 , DIM_2D = 1 , DIM_3D = 2 , DIM_Cube = 3 ,
DIM_Rect = 4 , DIM_Buffer = 5 , DIM_SubpassData = 6
}
enum class SamplerAddressingMode : uint32_t {
None = 0 , ClampToEdge = 1 , Clamp = 2 , Repeat = 3 ,
RepeatMirrored = 4
}
enum class SamplerFilterMode : uint32_t { Nearest = 0 , Linear = 1 }
enum class ImageFormat : uint32_t {
Unknown = 0 , Rgba32f = 1 , Rgba16f = 2 , R32f = 3 ,
Rgba8 = 4 , Rgba8Snorm = 5 , Rg32f = 6 , Rg16f = 7 ,
R11fG11fB10f = 8 , R16f = 9 , Rgba16 = 10 , Rgb10A2 = 11 ,
Rg16 = 12 , Rg8 = 13 , R16 = 14 , R8 = 15 ,
Rgba16Snorm = 16 , Rg16Snorm = 17 , Rg8Snorm = 18 , R16Snorm = 19 ,
R8Snorm = 20 , Rgba32i = 21 , Rgba16i = 22 , Rgba8i = 23 ,
R32i = 24 , Rg32i = 25 , Rg16i = 26 , Rg8i = 27 ,
R16i = 28 , R8i = 29 , Rgba32ui = 30 , Rgba16ui = 31 ,
Rgba8ui = 32 , R32ui = 33 , Rgb10a2ui = 34 , Rg32ui = 35 ,
Rg16ui = 36 , Rg8ui = 37 , R16ui = 38 , R8ui = 39
}
enum class ImageChannelOrder : uint32_t {
R = 0 , A = 1 , RG = 2 , RA = 3 ,
RGB = 4 , RGBA = 5 , BGRA = 6 , ARGB = 7 ,
Intensity = 8 , Luminance = 9 , Rx = 10 , RGx = 11 ,
RGBx = 12 , Depth = 13 , DepthStencil = 14 , sRGB = 15 ,
sRGBx = 16 , sRGBA = 17 , sBGRA = 18 , ABGR = 19
}
enum class ImageChannelDataType : uint32_t {
SnormInt8 = 0 , SnormInt16 = 1 , UnormInt8 = 2 , UnormInt16 = 3 ,
UnormShort565 = 4 , UnormShort555 = 5 , UnormInt101010 = 6 , SignedInt8 = 7 ,
SignedInt16 = 8 , SignedInt32 = 9 , UnsignedInt8 = 10 , UnsignedInt16 = 11 ,
UnsigendInt32 = 12 , HalfFloat = 13 , Float = 14 , UnormInt24 = 15 ,
UnormInt101010_2 = 16
}
enum class ImageOperand : uint32_t {
None = 0x0 , Bias = 0x1 , Lod = 0x2 , Grad = 0x4 ,
ConstOffset = 0x8 , Offset = 0x10 , ConstOffsets = 0x20 , Sample = 0x40 ,
MinLod = 0x80 , MakeTexelAvailableKHR = 0x100 , MakeTexelVisibleKHR = 0x200 , NonPrivateTexelKHR = 0x400 ,
VolatileTexelKHR = 0x800 , SignExtend = 0x1000 , ZeroExtend = 0x2000
}
enum class FPFastMathMode : uint32_t {
None = 0x0 , NotNaN = 0x1 , NotInf = 0x2 , NSZ = 0x4 ,
AllowRecip = 0x8 , Fast = 0x10
}
enum class FPRoundingMode : uint32_t { RTE = 0 , RTZ = 1 , RTP = 2 , RTN = 3 }
enum class LinkageType : uint32_t { Export = 0 , Import = 1 }
enum class AccessQualifier : uint32_t { ReadOnly = 0 , WriteOnly = 1 , ReadWrite = 2 }
enum class FunctionParameterAttribute : uint32_t {
Zext = 0 , Sext = 1 , ByVal = 2 , Sret = 3 ,
NoAlias = 4 , NoCapture = 5 , NoWrite = 6 , NoReadWrite = 7
}
enum class Decoration : uint32_t {
RelaxedPrecision = 0 , SpecId = 1 , Block = 2 , BufferBlock = 3 ,
RowMajor = 4 , ColMajor = 5 , ArrayStride = 6 , MatrixStride = 7 ,
GLSLShared = 8 , GLSLPacked = 9 , CPacked = 10 , BuiltIn = 11 ,
NoPerspective = 13 , Flat = 14 , Patch = 15 , Centroid = 16 ,
Sample = 17 , Invariant = 18 , Restrict = 19 , Aliased = 20 ,
Volatile = 21 , Constant = 22 , Coherent = 23 , NonWritable = 24 ,
NonReadable = 25 , Uniform = 26 , UniformId = 27 , SaturatedConversion = 28 ,
Stream = 29 , Location = 30 , Component = 31 , Index = 32 ,
Binding = 33 , DescriptorSet = 34 , Offset = 35 , XfbBuffer = 36 ,
XfbStride = 37 , FuncParamAttr = 38 , FPRoundingMode = 39 , FPFastMathMode = 40 ,
LinkageAttributes = 41 , NoContraction = 42 , InputAttachmentIndex = 43 , Alignment = 44 ,
MaxByteOffset = 45 , AlignmentId = 46 , MaxByteOffsetId = 47 , NoSignedWrap = 4469 ,
NoUnsignedWrap = 4470 , ExplicitInterpAMD = 4999 , OverrideCoverageNV = 5248 , PassthroughNV = 5250 ,
ViewportRelativeNV = 5252 , SecondaryViewportRelativeNV = 5256 , PerPrimitiveNV = 5271 , PerViewNV = 5272 ,
PerVertexNV = 5273 , NonUniformEXT = 5300 , CountBuffer = 5634 , UserSemantic = 5635 ,
RestrictPointerEXT = 5355 , AliasedPointerEXT = 5356
}
enum class BuiltIn : uint32_t {
Position = 0 , PointSize = 1 , ClipDistance = 3 , CullDistance = 4 ,
VertexId = 5 , InstanceId = 6 , PrimitiveId = 7 , InvocationId = 8 ,
Layer = 9 , ViewportIndex = 10 , TessLevelOuter = 11 , TessLevelInner = 12 ,
TessCoord = 13 , PatchVertices = 14 , FragCoord = 15 , PointCoord = 16 ,
FrontFacing = 17 , SampleId = 18 , SamplePosition = 19 , SampleMask = 20 ,
FragDepth = 22 , HelperInvocation = 23 , NumWorkgroups = 24 , WorkgroupSize = 25 ,
WorkgroupId = 26 , LocalInvocationId = 27 , GlobalInvocationId = 28 , LocalInvocationIndex = 29 ,
WorkDim = 30 , GlobalSize = 31 , EnqueuedWorkgroupSize = 32 , GlobalOffset = 33 ,
GlobalLinearId = 34 , SubgroupSize = 36 , SubgroupMaxSize = 37 , NumSubgroups = 38 ,
NumEnqueuedSubgroups = 39 , SubgroupId = 40 , SubgroupLocalInvocationId = 41 , VertexIndex = 42 ,
InstanceIndex = 43 , SubgroupEqMask = 4416 , SubgroupGeMask = 4417 , SubgroupGtMask = 4418 ,
SubgroupLeMask = 4419 , SubgroupLtMask = 4420 , BaseVertex = 4424 , BaseInstance = 4425 ,
DrawIndex = 4426 , DeviceIndex = 4438 , ViewIndex = 4440 , BaryCoordNoPerspAMD = 4492 ,
BaryCoordNoPerspCentroidAMD = 4493 , BaryCoordNoPerspSampleAMD = 4494 , BaryCoordSmoothAMD = 4495 , BaryCoordSmoothCentroid = 4496 ,
BaryCoordSmoothSample = 4497 , BaryCoordPullModel = 4498 , FragStencilRefEXT = 5014 , ViewportMaskNV = 5253 ,
SecondaryPositionNV = 5257 , SecondaryViewportMaskNV = 5258 , PositionPerViewNV = 5261 , ViewportMaskPerViewNV = 5262 ,
FullyCoveredEXT = 5264 , TaskCountNV = 5274 , PrimitiveCountNV = 5275 , PrimitiveIndicesNV = 5276 ,
ClipDistancePerViewNV = 5277 , CullDistancePerViewNV = 5278 , LayerPerViewNV = 5279 , MeshViewCountNV = 5280 ,
MeshViewIndices = 5281 , BaryCoordNV = 5286 , BaryCoordNoPerspNV = 5287 , FragSizeEXT = 5292 ,
FragInvocationCountEXT = 5293 , LaunchIdNV = 5319 , LaunchSizeNV = 5320 , WorldRayOriginNV = 5321 ,
WorldRayDirectionNV = 5322 , ObjectRayOriginNV = 5323 , ObjectRayDirectionNV = 5324 , RayTminNV = 5325 ,
RayTmaxNV = 5326 , InstanceCustomIndexNV = 5327 , ObjectToWorldNV = 5330 , WorldToObjectNV = 5331 ,
HitTNV = 5332 , HitKindNV = 5333 , IncomingRayFlagsNV = 5351
}
enum class SelectionControl : uint32_t { None = 0x0 , Flatten = 0x1 , DontFlatten = 0x2 }
enum class LoopControl : uint32_t {
None = 0x0 , Unroll = 0x1 , DontUnroll = 0x2 , DependencyInfinite = 0x4 ,
DependencyLength = 0x8 , MinIterations = 0x10 , MaxIterations = 0x20 , IterationMultiple = 0x40 ,
PeelCount = 0x80 , PartialCount = 0x100
}
enum class FunctionControl : uint32_t {
None = 0x0 , Inline = 0x1 , DontInline = 0x2 , Pure = 0x4 ,
Const = 0x8
}
enum class MemorySemantics : uint32_t {
None = 0x0 , Acquire = 0x2 , Release = 0x4 , AcquireRelease = 0x8 ,
SequentiallyConsistent = 0x10 , UniformMemory = 0x40 , SubgroupMemory = 0x80 , WorkgroupMemory = 0x100 ,
CrossWorkgroupMemory = 0x200 , AtomicCounterMemory = 0x400 , ImageMemory = 0x800 , OutputMemoryKHR = 0x1000 ,
MakeAvailableKHR = 0x2000 , MakeVisibleKHR = 0x4000
}
enum class MemoryOperand : uint32_t {
None = 0x0 , Volatile = 0x1 , Aligned = 0x2 , Nontemporal = 0x4 ,
MakePointerAvailableKHR = 0x8 , MakePointerVisibleKHR = 0x10 , NonPrivatePointerKHR = 0x20
}
enum class Scope : uint32_t {
CrossDevice = 0 , Device = 1 , Workgroup = 2 , Subgroup = 3 ,
Invocation = 4 , QueueFamilyKHR = 5
}
enum class GroupOperation : uint32_t {
Reduce = 0 , InclusiveScan = 1 , ExclusiveScan = 2 , ClusteredReduce = 3 ,
PartitionedReduceNV = 6 , PartitionedInclusiveScanNV = 7 , PartitionedExclusiveScanNV = 8
}
enum class KernelEnqueueFlags : uint32_t { NoWait = 0 , WaitKernel = 1 , WaitWorkGroup = 2 }
enum class KernelProfilingInfo : uint32_t { None = 0x0 , CmdExecTime = 0x1 }
enum class InstructionSet : uint32_t { OpenCL_std = 0 , GLSL_std_450 = 1 , SPV_AMD_shader_trinary_minmax = 2 }
enum class Opcode : uint32_t { InBoundsPtrAccessChain = 70 , PtrCastToGeneric = 121 }
enum ModuleSectionType {
MB_EntryPoints , MB_DebugNames , MB_DebugModuleProcessed , MB_Annotations ,
MB_TypeConstVars , MB_ExtFuncDecls , NUM_MODULE_SECTIONS
}
Functions
StringRef getCapabilityName (Capability e)
StringRef getSourceLanguageName (SourceLanguage e)
StringRef getExecutionModelName (ExecutionModel e)
StringRef getAddressingModelName (AddressingModel e)
StringRef getMemoryModelName (MemoryModel e)
StringRef getExecutionModeName (ExecutionMode e)
StringRef getStorageClassName (StorageClass e)
StringRef getDimName (Dim dim)
StringRef getSamplerAddressingModeName (SamplerAddressingMode e)
StringRef getSamplerFilterModeName (SamplerFilterMode e)
StringRef getImageFormatName (ImageFormat e)
StringRef getImageChannelOrderName (ImageChannelOrder e)
StringRef getImageChannelDataTypeName (ImageChannelDataType e)
std::string getImageOperandName (uint32_t e)
std::string getFPFastMathModeName (uint32_t e)
StringRef getFPRoundingModeName (FPRoundingMode e)
StringRef getLinkageTypeName (LinkageType e)
StringRef getAccessQualifierName (AccessQualifier e)
StringRef getFunctionParameterAttributeName (FunctionParameterAttribute e)
StringRef getDecorationName (Decoration e)
StringRef getBuiltInName (BuiltIn e)
std::string getSelectionControlName (uint32_t e)
std::string getLoopControlName (uint32_t e)
std::string getFunctionControlName (uint32_t e)
std::string getMemorySemanticsName (uint32_t e)
std::string getMemoryOperandName (uint32_t e)
StringRef getScopeName (Scope e)
StringRef getGroupOperationName (GroupOperation e)
StringRef getKernelEnqueueFlagsName (KernelEnqueueFlags e)
StringRef getKernelProfilingInfoName (KernelProfilingInfo e)
std::string getExtInstSetName (InstructionSet e)
Typedef Documentation
InstrList
using llvm::SPIRV::InstrList = SmallVector<MachineInstr *>
Definition at line 42 of file SPIRVModuleAnalysis.h.
LocalToGlobalRegTable
using llvm::SPIRV::LocalToGlobalRegTable = std::map<Register, Register>
Definition at line 44 of file SPIRVModuleAnalysis.h.
RegisterAliasMapTy
using llvm::SPIRV::RegisterAliasMapTy
Initial value:
    std::map<const MachineFunction *, LocalToGlobalRegTable>
Definition at line 45 of file SPIRVModuleAnalysis.h.
Enumeration Type Documentation
AccessQualifier
enum class llvm::SPIRV::AccessQualifier : uint32_t strong
Enumerator
ReadOnly
WriteOnly
ReadWrite
Definition at line 437 of file SPIRVBaseInfo.h.
AddressingModel
enum class llvm::SPIRV::AddressingModel : uint32_t strong
Enumerator
Logical
Physical32
Physical64
PhysicalStorageBuffer64EXT
Definition at line 167 of file SPIRVBaseInfo.h.
BuiltIn
enum class llvm::SPIRV::BuiltIn : uint32_t strong
Enumerator
Position
PointSize
ClipDistance
CullDistance
VertexId
InstanceId
PrimitiveId
InvocationId
Layer
ViewportIndex
TessLevelOuter
TessLevelInner
TessCoord
PatchVertices
FragCoord
PointCoord
FrontFacing
SampleId
SamplePosition
SampleMask
FragDepth
HelperInvocation
NumWorkgroups
WorkgroupSize
WorkgroupId
LocalInvocationId
GlobalInvocationId
LocalInvocationIndex
WorkDim
GlobalSize
EnqueuedWorkgroupSize
GlobalOffset
GlobalLinearId
SubgroupSize
SubgroupMaxSize
NumSubgroups
NumEnqueuedSubgroups
SubgroupId
SubgroupLocalInvocationId
VertexIndex
InstanceIndex
SubgroupEqMask
SubgroupGeMask
SubgroupGtMask
SubgroupLeMask
SubgroupLtMask
BaseVertex
BaseInstance
DrawIndex
DeviceIndex
ViewIndex
BaryCoordNoPerspAMD
BaryCoordNoPerspCentroidAMD
BaryCoordNoPerspSampleAMD
BaryCoordSmoothAMD
BaryCoordSmoothCentroid
BaryCoordSmoothSample
BaryCoordPullModel
FragStencilRefEXT
ViewportMaskNV
SecondaryPositionNV
SecondaryViewportMaskNV
PositionPerViewNV
ViewportMaskPerViewNV
FullyCoveredEXT
TaskCountNV
PrimitiveCountNV
PrimitiveIndicesNV
ClipDistancePerViewNV
CullDistancePerViewNV
LayerPerViewNV
MeshViewCountNV
MeshViewIndices
BaryCoordNV
BaryCoordNoPerspNV
FragSizeEXT
FragInvocationCountEXT
LaunchIdNV
LaunchSizeNV
WorldRayOriginNV
WorldRayDirectionNV
ObjectRayOriginNV
ObjectRayDirectionNV
RayTminNV
RayTmaxNV
InstanceCustomIndexNV
ObjectToWorldNV
WorldToObjectNV
HitTNV
HitKindNV
IncomingRayFlagsNV
Definition at line 522 of file SPIRVBaseInfo.h.
Capability
enum class llvm::SPIRV::Capability : uint32_t strong
Enumerator
Matrix
Shader
Geometry
Tessellation
Addresses
Linkage
Kernel
Vector16
Float16Buffer
Float16
Float64
Int64
Int64Atomics
ImageBasic
ImageReadWrite
ImageMipmap
Pipes
Groups
DeviceEnqueue
LiteralSampler
AtomicStorage
Int16
TessellationPointSize
GeometryPointSize
ImageGatherExtended
StorageImageMultisample
UniformBufferArrayDynamicIndexing
SampledImageArrayDymnamicIndexing
ClipDistance
CullDistance
ImageCubeArray
SampleRateShading
ImageRect
SampledRect
GenericPointer
Int8
InputAttachment
SparseResidency
MinLod
Sampled1D
Image1D
SampledCubeArray
SampledBuffer
ImageBuffer
ImageMSArray
StorageImageExtendedFormats
ImageQuery
DerivativeControl
InterpolationFunction
TransformFeedback
GeometryStreams
StorageImageReadWithoutFormat
StorageImageWriteWithoutFormat
MultiViewport
SubgroupDispatch
NamedBarrier
PipeStorage
GroupNonUniform
GroupNonUniformVote
GroupNonUniformArithmetic
GroupNonUniformBallot
GroupNonUniformShuffle
GroupNonUniformShuffleRelative
GroupNonUniformClustered
GroupNonUniformQuad
SubgroupBallotKHR
DrawParameters
SubgroupVoteKHR
StorageBuffer16BitAccess
StorageUniform16
StoragePushConstant16
StorageInputOutput16
DeviceGroup
MultiView
VariablePointersStorageBuffer
VariablePointers
AtomicStorageOps
SampleMaskPostDepthCoverage
StorageBuffer8BitAccess
UniformAndStorageBuffer8BitAccess
StoragePushConstant8
DenormPreserve
DenormFlushToZero
SignedZeroInfNanPreserve
RoundingModeRTE
RoundingModeRTZ
Float16ImageAMD
ImageGatherBiasLodAMD
FragmentMaskAMD
StencilExportEXT
ImageReadWriteLodAMD
SampleMaskOverrideCoverageNV
GeometryShaderPassthroughNV
ShaderViewportIndexLayerEXT
ShaderViewportMaskNV
ShaderStereoViewNV
PerViewAttributesNV
FragmentFullyCoveredEXT
MeshShadingNV
ShaderNonUniformEXT
RuntimeDescriptorArrayEXT
InputAttachmentArrayDynamicIndexingEXT
UniformTexelBufferArrayDynamicIndexingEXT
StorageTexelBufferArrayDynamicIndexingEXT
UniformBufferArrayNonUniformIndexingEXT
SampledImageArrayNonUniformIndexingEXT
StorageBufferArrayNonUniformIndexingEXT
StorageImageArrayNonUniformIndexingEXT
InputAttachmentArrayNonUniformIndexingEXT
UniformTexelBufferArrayNonUniformIndexingEXT
StorageTexelBufferArrayNonUniformIndexingEXT
RayTracingNV
SubgroupShuffleINTEL
SubgroupBufferBlockIOINTEL
SubgroupImageBlockIOINTEL
SubgroupImageMediaBlockIOINTEL
SubgroupAvcMotionEstimationINTEL
SubgroupAvcMotionEstimationIntraINTEL
SubgroupAvcMotionEstimationChromaINTEL
GroupNonUniformPartitionedNV
VulkanMemoryModelKHR
VulkanMemoryModelDeviceScopeKHR
ImageFootprintNV
FragmentBarycentricNV
ComputeDerivativeGroupQuadsNV
ComputeDerivativeGroupLinearNV
FragmentDensityEXT
PhysicalStorageBufferAddressesEXT
CooperativeMatrixNV
Definition at line 24 of file SPIRVBaseInfo.h.
Decoration
enum class llvm::SPIRV::Decoration : uint32_t strong
Enumerator
RelaxedPrecision
SpecId
Block
BufferBlock
RowMajor
ColMajor
ArrayStride
MatrixStride
GLSLShared
GLSLPacked
CPacked
BuiltIn
NoPerspective
Flat
Patch
Centroid
Sample
Invariant
Restrict
Aliased
Volatile
Constant
Coherent
NonWritable
NonReadable
Uniform
UniformId
SaturatedConversion
Stream
Location
Component
Index
Binding
DescriptorSet
Offset
XfbBuffer
XfbStride
FuncParamAttr
FPRoundingMode
FPFastMathMode
LinkageAttributes
NoContraction
InputAttachmentIndex
Alignment
MaxByteOffset
AlignmentId
MaxByteOffsetId
NoSignedWrap
NoUnsignedWrap
ExplicitInterpAMD
OverrideCoverageNV
PassthroughNV
ViewportRelativeNV
SecondaryViewportRelativeNV
PerPrimitiveNV
PerViewNV
PerVertexNV
NonUniformEXT
CountBuffer
UserSemantic
RestrictPointerEXT
AliasedPointerEXT
Definition at line 456 of file SPIRVBaseInfo.h.
Dim
enum class llvm::SPIRV::Dim : uint32_t strong
Enumerator
DIM_1D
DIM_2D
DIM_3D
DIM_Cube
DIM_Rect
DIM_Buffer
DIM_SubpassData
Definition at line 279 of file SPIRVBaseInfo.h.
ExecutionMode
enum class llvm::SPIRV::ExecutionMode : uint32_t strong
Enumerator
Invocations
SpacingEqual
SpacingFractionalEven
SpacingFractionalOdd
VertexOrderCw
VertexOrderCcw
PixelCenterInteger
OriginUpperLeft
OriginLowerLeft
EarlyFragmentTests
PointMode
Xfb
DepthReplacing
DepthGreater
DepthLess
DepthUnchanged
LocalSize
LocalSizeHint
InputPoints
InputLines
InputLinesAdjacency
Triangles
InputTrianglesAdjacency
Quads
Isolines
OutputVertices
OutputPoints
OutputLineStrip
OutputTriangleStrip
VecTypeHint
ContractionOff
Initializer
Finalizer
SubgroupSize
SubgroupsPerWorkgroup
SubgroupsPerWorkgroupId
LocalSizeId
LocalSizeHintId
PostDepthCoverage
DenormPreserve
DenormFlushToZero
SignedZeroInfNanPreserve
RoundingModeRTE
RoundingModeRTZ
StencilRefReplacingEXT
OutputLinesNV
DerivativeGroupQuadsNV
DerivativeGroupLinearNV
OutputTrianglesNV
Definition at line 202 of file SPIRVBaseInfo.h.
ExecutionModel
enum class llvm::SPIRV::ExecutionModel : uint32_t strong
Enumerator
Vertex
TessellationControl
TessellationEvaluation
Geometry
Fragment
GLCompute
Kernel
TaskNV
MeshNV
RayGenerationNV
IntersectionNV
AnyHitNV
ClosestHitNV
MissNV
CallableNV
Definition at line 175 of file SPIRVBaseInfo.h.
FPFastMathMode
enum class llvm::SPIRV::FPFastMathMode : uint32_t strong
Enumerator
None
NotNaN
NotInf
NSZ
AllowRecip
Fast
Definition at line 413 of file SPIRVBaseInfo.h.
FPRoundingMode
enum class llvm::SPIRV::FPRoundingMode : uint32_t strong
Enumerator
RTE
RTZ
RTP
RTN
Definition at line 423 of file SPIRVBaseInfo.h.
FunctionControl
enum class llvm::SPIRV::FunctionControl : uint32_t strong
Enumerator
None
Inline
DontInline
Pure
Const
Definition at line 638 of file SPIRVBaseInfo.h.
FunctionParameterAttribute
enum class llvm::SPIRV::FunctionParameterAttribute : uint32_t strong
Enumerator
Zext
Sext
ByVal
Sret
NoAlias
NoCapture
NoWrite
NoReadWrite
Definition at line 444 of file SPIRVBaseInfo.h.
GroupOperation
enum class llvm::SPIRV::GroupOperation : uint32_t strong
Enumerator
Reduce
InclusiveScan
ExclusiveScan
ClusteredReduce
PartitionedReduceNV
PartitionedInclusiveScanNV
PartitionedExclusiveScanNV
Definition at line 686 of file SPIRVBaseInfo.h.
ImageChannelDataType
enum class llvm::SPIRV::ImageChannelDataType : uint32_t strong
Enumerator
SnormInt8
SnormInt16
UnormInt8
UnormInt16
UnormShort565
UnormShort555
UnormInt101010
SignedInt8
SignedInt16
SignedInt32
UnsignedInt8
UnsignedInt16
UnsigendInt32
HalfFloat
Float
UnormInt24
UnormInt101010_2
Definition at line 373 of file SPIRVBaseInfo.h.
ImageChannelOrder
enum class llvm::SPIRV::ImageChannelOrder : uint32_t strong
Enumerator
R
A
RG
RA
RGB
RGBA
BGRA
ARGB
Intensity
Luminance
Rx
RGx
RGBx
Depth
DepthStencil
sRGB
sRGBx
sRGBA
sBGRA
ABGR
Definition at line 349 of file SPIRVBaseInfo.h.
ImageFormat
enum class llvm::SPIRV::ImageFormat : uint32_t strong
Enumerator
Unknown
Rgba32f
Rgba16f
R32f
Rgba8
Rgba8Snorm
Rg32f
Rg16f
R11fG11fB10f
R16f
Rgba16
Rgb10A2
Rg16
Rg8
R16
R8
Rgba16Snorm
Rg16Snorm
Rg8Snorm
R16Snorm
R8Snorm
Rgba32i
Rgba16i
Rgba8i
R32i
Rg32i
Rg16i
Rg8i
R16i
R8i
Rgba32ui
Rgba16ui
Rgba8ui
R32ui
Rgb10a2ui
Rg32ui
Rg16ui
Rg8ui
R16ui
R8ui
Definition at line 305 of file SPIRVBaseInfo.h.
ImageOperand
enum class llvm::SPIRV::ImageOperand : uint32_t strong
Enumerator
None
Bias
Lod
Grad
ConstOffset
Offset
ConstOffsets
Sample
MinLod
MakeTexelAvailableKHR
MakeTexelVisibleKHR
NonPrivateTexelKHR
VolatileTexelKHR
SignExtend
ZeroExtend
Definition at line 394 of file SPIRVBaseInfo.h.
InstructionSet
enum class llvm::SPIRV::InstructionSet : uint32_t strong
Enumerator
OpenCL_std
GLSL_std_450
SPV_AMD_shader_trinary_minmax
Definition at line 710 of file SPIRVBaseInfo.h.
KernelEnqueueFlags
enum class llvm::SPIRV::KernelEnqueueFlags : uint32_t strong
Enumerator
NoWait
WaitKernel
WaitWorkGroup
Definition at line 697 of file SPIRVBaseInfo.h.
KernelProfilingInfo
enum class llvm::SPIRV::KernelProfilingInfo : uint32_t strong
Enumerator
None
CmdExecTime
Definition at line 704 of file SPIRVBaseInfo.h.
LinkageType
enum class llvm::SPIRV::LinkageType : uint32_t strong
Enumerator
Export
Import
Definition at line 431 of file SPIRVBaseInfo.h.
LoopControl
enum class llvm::SPIRV::LoopControl : uint32_t strong
Enumerator
None
Unroll
DontUnroll
DependencyInfinite
DependencyLength
MinIterations
MaxIterations
IterationMultiple
PeelCount
PartialCount
Definition at line 624 of file SPIRVBaseInfo.h.
MemoryModel
enum class llvm::SPIRV::MemoryModel : uint32_t strong
Enumerator
Simple
GLSL450
OpenCL
VulkanKHR
Definition at line 194 of file SPIRVBaseInfo.h.
MemoryOperand
enum class llvm::SPIRV::MemoryOperand : uint32_t strong
Enumerator
None
Volatile
Aligned
Nontemporal
MakePointerAvailableKHR
MakePointerVisibleKHR
NonPrivatePointerKHR
Definition at line 665 of file SPIRVBaseInfo.h.
MemorySemantics
enum class llvm::SPIRV::MemorySemantics : uint32_t strong
Enumerator
None
Acquire
Release
AcquireRelease
SequentiallyConsistent
UniformMemory
SubgroupMemory
WorkgroupMemory
CrossWorkgroupMemory
AtomicCounterMemory
ImageMemory
OutputMemoryKHR
MakeAvailableKHR
MakeVisibleKHR
Definition at line 647 of file SPIRVBaseInfo.h.
ModuleSectionType
enum llvm::SPIRV::ModuleSectionType
Enumerator
MB_EntryPoints
MB_DebugNames
MB_DebugModuleProcessed
MB_Annotations
MB_TypeConstVars
MB_ExtFuncDecls
NUM_MODULE_SECTIONS
Definition at line 30 of file SPIRVModuleAnalysis.h.
Opcode
enum class llvm::SPIRV::Opcode : uint32_t strong
Enumerator
InBoundsPtrAccessChain
PtrCastToGeneric
Definition at line 718 of file SPIRVBaseInfo.h.
SamplerAddressingMode
enum class llvm::SPIRV::SamplerAddressingMode : uint32_t strong
Enumerator
None
ClampToEdge
Clamp
Repeat
RepeatMirrored
Definition at line 290 of file SPIRVBaseInfo.h.
SamplerFilterMode
enum class llvm::SPIRV::SamplerFilterMode : uint32_t strong
Enumerator
Nearest
Linear
Definition at line 299 of file SPIRVBaseInfo.h.
Scope
enum class llvm::SPIRV::Scope : uint32_t strong
Enumerator
CrossDevice
Device
Workgroup
Subgroup
Invocation
QueueFamilyKHR
Definition at line 676 of file SPIRVBaseInfo.h.
SelectionControl
enum class llvm::SPIRV::SelectionControl : uint32_t strong
Enumerator
None
Flatten
DontFlatten
Definition at line 617 of file SPIRVBaseInfo.h.
SourceLanguage
enum class llvm::SPIRV::SourceLanguage : uint32_t strong
Enumerator
Unknown
ESSL
GLSL
OpenCL_C
OpenCL_CPP
HLSL
Definition at line 157 of file SPIRVBaseInfo.h.
StorageClass
enum class llvm::SPIRV::StorageClass : uint32_t strong
Enumerator
UniformConstant
Input
Uniform
Output
Workgroup
CrossWorkgroup
Private
Function
Generic
PushConstant
AtomicCounter
Image
StorageBuffer
CallableDataNV
IncomingCallableDataNV
RayPayloadNV
HitAttributeNV
IncomingRayPayloadNV
ShaderRecordBufferNV
PhysicalStorageBufferEXT
Definition at line 255 of file SPIRVBaseInfo.h.
Function Documentation
getAccessQualifierName()
StringRef llvm::SPIRV::getAccessQualifierName (AccessQualifier e)
Definition at line 590 of file SPIRVBaseInfo.cpp.
References CASE, llvm_unreachable, ReadOnly, ReadWrite, and WriteOnly.
Referenced by llvm::SPIRVInstPrinter::printAccessQualifier().
getAddressingModelName()
StringRef llvm::SPIRV::getAddressingModelName (AddressingModel e)
Definition at line 202 of file SPIRVBaseInfo.cpp.
References CASE, llvm_unreachable, Logical, Physical32, Physical64, and PhysicalStorageBuffer64EXT.
Referenced by llvm::SPIRVInstPrinter::printAddressingModel().
getBuiltInName()
StringRef llvm::SPIRV::getBuiltInName (BuiltIn e)
Definition at line 684 of file SPIRVBaseInfo.cpp.
References BaryCoordNoPerspAMD, BaryCoordNoPerspCentroidAMD, BaryCoordNoPerspNV, BaryCoordNoPerspSampleAMD, BaryCoordNV, BaryCoordPullModel, BaryCoordSmoothAMD, BaryCoordSmoothCentroid, BaryCoordSmoothSample, BaseInstance, BaseVertex, CASE, ClipDistance, ClipDistancePerViewNV, CullDistance, CullDistancePerViewNV, DeviceIndex, DrawIndex, EnqueuedWorkgroupSize, FragCoord, FragDepth, FragInvocationCountEXT, FragSizeEXT, FragStencilRefEXT, FrontFacing, FullyCoveredEXT, GlobalInvocationId, GlobalLinearId, GlobalOffset, GlobalSize, HelperInvocation, HitKindNV, HitTNV, IncomingRayFlagsNV, InstanceCustomIndexNV, InstanceId, InstanceIndex, InvocationId, LaunchIdNV, LaunchSizeNV, Layer, LayerPerViewNV, llvm_unreachable, LocalInvocationId, LocalInvocationIndex, MeshViewCountNV, MeshViewIndices, NumEnqueuedSubgroups, NumSubgroups, NumWorkgroups, ObjectRayDirectionNV, ObjectRayOriginNV, ObjectToWorldNV, PatchVertices, PointCoord, PointSize, PositionPerViewNV, PrimitiveCountNV, PrimitiveId, PrimitiveIndicesNV, RayTmaxNV, RayTminNV, SampleId, SampleMask, SamplePosition, SecondaryPositionNV, SecondaryViewportMaskNV, SubgroupEqMask, SubgroupGeMask, SubgroupGtMask, SubgroupId, SubgroupLeMask, SubgroupLocalInvocationId, SubgroupLtMask, SubgroupMaxSize, SubgroupSize, TaskCountNV, TessCoord, TessLevelInner, TessLevelOuter, VertexId, VertexIndex, ViewIndex, ViewportIndex, ViewportMaskNV, ViewportMaskPerViewNV, WorkDim, WorkgroupId, WorkgroupSize, WorldRayDirectionNV, WorldRayOriginNV, and WorldToObjectNV.
Referenced by llvm::SPIRVInstPrinter::printBuiltIn().
getCapabilityName()
StringRef llvm::SPIRV::getCapabilityName (Capability e)
Definition at line 31 of file SPIRVBaseInfo.cpp.
References Addresses, AtomicStorage, AtomicStorageOps, CASE, ClipDistance, ComputeDerivativeGroupLinearNV, ComputeDerivativeGroupQuadsNV, CooperativeMatrixNV, CullDistance, DenormFlushToZero, DenormPreserve, DerivativeControl, DeviceEnqueue, DeviceGroup, DrawParameters, Float16, Float16Buffer, Float16ImageAMD, Float64, FragmentBarycentricNV, FragmentDensityEXT, FragmentFullyCoveredEXT, FragmentMaskAMD, GenericPointer, Geometry, GeometryPointSize, GeometryShaderPassthroughNV, GeometryStreams, GroupNonUniform, GroupNonUniformArithmetic, GroupNonUniformBallot, GroupNonUniformClustered, GroupNonUniformPartitionedNV, GroupNonUniformQuad, GroupNonUniformShuffle, GroupNonUniformShuffleRelative, GroupNonUniformVote, Groups, Image1D, ImageBasic, ImageBuffer, ImageCubeArray, ImageFootprintNV, ImageGatherBiasLodAMD, ImageGatherExtended, ImageMipmap, ImageMSArray, ImageQuery, ImageReadWrite, ImageReadWriteLodAMD, ImageRect, InputAttachment, InputAttachmentArrayDynamicIndexingEXT, InputAttachmentArrayNonUniformIndexingEXT, Int16, Int64, Int64Atomics, Int8, InterpolationFunction, Kernel, LiteralSampler, llvm_unreachable, Matrix, MeshShadingNV, MinLod, MultiView, MultiViewport, NamedBarrier, PerViewAttributesNV, PhysicalStorageBufferAddressesEXT, Pipes, PipeStorage, RayTracingNV, RoundingModeRTE, RoundingModeRTZ, RuntimeDescriptorArrayEXT, Sampled1D, SampledBuffer, SampledCubeArray, SampledImageArrayDymnamicIndexing, SampledImageArrayNonUniformIndexingEXT, SampledRect, SampleMaskOverrideCoverageNV, SampleMaskPostDepthCoverage, SampleRateShading, Shader, ShaderNonUniformEXT, ShaderStereoViewNV, ShaderViewportIndexLayerEXT, ShaderViewportMaskNV, SignedZeroInfNanPreserve, SparseResidency, StencilExportEXT, StorageBuffer16BitAccess, StorageBuffer8BitAccess, StorageBufferArrayNonUniformIndexingEXT, StorageImageArrayNonUniformIndexingEXT, StorageImageExtendedFormats, StorageImageMultisample, StorageImageReadWithoutFormat, StorageImageWriteWithoutFormat, StorageInputOutput16, StoragePushConstant16, StoragePushConstant8, StorageTexelBufferArrayDynamicIndexingEXT, StorageTexelBufferArrayNonUniformIndexingEXT, StorageUniform16, SubgroupAvcMotionEstimationChromaINTEL, SubgroupAvcMotionEstimationINTEL, SubgroupAvcMotionEstimationIntraINTEL, SubgroupBallotKHR, SubgroupBufferBlockIOINTEL, SubgroupDispatch, SubgroupImageBlockIOINTEL, SubgroupImageMediaBlockIOINTEL, SubgroupShuffleINTEL, SubgroupVoteKHR, Tessellation, TessellationPointSize, TransformFeedback, UniformAndStorageBuffer8BitAccess, UniformBufferArrayDynamicIndexing, UniformBufferArrayNonUniformIndexingEXT, UniformTexelBufferArrayDynamicIndexingEXT, UniformTexelBufferArrayNonUniformIndexingEXT, VariablePointers, VariablePointersStorageBuffer, Vector16, VulkanMemoryModelDeviceScopeKHR, and VulkanMemoryModelKHR.
Referenced by llvm::SPIRVInstPrinter::printCapability().
getDecorationName()
StringRef llvm::SPIRV::getDecorationName (Decoration e)
Definition at line 615 of file SPIRVBaseInfo.cpp.
References Aliased, AliasedPointerEXT, Alignment, AlignmentId, ArrayStride, Binding, BufferBlock, CASE, Centroid, Coherent, ColMajor, Component, CountBuffer, CPacked, DescriptorSet, ExplicitInterpAMD, Flat, FuncParamAttr, GLSLPacked, GLSLShared, InputAttachmentIndex, Invariant, LinkageAttributes, llvm_unreachable, MatrixStride, MaxByteOffset, MaxByteOffsetId, NoContraction, NonReadable, NonUniformEXT, NonWritable, NoPerspective, NoSignedWrap, NoUnsignedWrap, Offset, OverrideCoverageNV, PassthroughNV, Patch, PerPrimitiveNV, PerVertexNV, PerViewNV, RelaxedPrecision, Restrict, RestrictPointerEXT, RowMajor, Sample, SaturatedConversion, SecondaryViewportRelativeNV, SpecId, Stream, Uniform, UniformId, UserSemantic, ViewportRelativeNV, Volatile, XfbBuffer, and XfbStride.
Referenced by llvm::SPIRVInstPrinter::printDecoration().
getDimName()
StringRef llvm::SPIRV::getDimName (Dim dim)
Definition at line 307 of file SPIRVBaseInfo.cpp.
References CASE_SUF, D, and llvm_unreachable.
Referenced by llvm::SPIRVInstPrinter::printDim().
getExecutionModelName()
StringRef llvm::SPIRV::getExecutionModelName (ExecutionModel e)
Definition at line 180 of file SPIRVBaseInfo.cpp.
References AnyHitNV, CallableNV, CASE, ClosestHitNV, Geometry, GLCompute, IntersectionNV, Kernel, llvm_unreachable, MeshNV, MissNV, RayGenerationNV, TaskNV, TessellationControl, TessellationEvaluation, and Vertex.
Referenced by llvm::SPIRVInstPrinter::printExecutionModel().
getExecutionModeName()
StringRef llvm::SPIRV::getExecutionModeName (ExecutionMode e)
Definition at line 224 of file SPIRVBaseInfo.cpp.
References CASE, ContractionOff, DenormFlushToZero, DenormPreserve, DepthGreater, DepthLess, DepthReplacing, DepthUnchanged, DerivativeGroupLinearNV, DerivativeGroupQuadsNV, EarlyFragmentTests, Finalizer, Initializer, InputLines, InputLinesAdjacency, InputPoints, InputTrianglesAdjacency, Invocations, Isolines, llvm_unreachable, LocalSize, LocalSizeHint, LocalSizeHintId, LocalSizeId, OriginLowerLeft, OriginUpperLeft, OutputLinesNV, OutputLineStrip, OutputPoints, OutputTrianglesNV, OutputTriangleStrip, OutputVertices, PixelCenterInteger, PointMode, PostDepthCoverage, Quads, RoundingModeRTE, RoundingModeRTZ, SignedZeroInfNanPreserve, SpacingEqual, SpacingFractionalEven, SpacingFractionalOdd, StencilRefReplacingEXT, SubgroupSize, SubgroupsPerWorkgroup, SubgroupsPerWorkgroupId, Triangles, VecTypeHint, VertexOrderCcw, VertexOrderCw, and Xfb.
Referenced by llvm::SPIRVInstPrinter::printExecutionMode().
getExtInstSetName()
std::string llvm::SPIRV::getExtInstSetName (InstructionSet e)
Definition at line 1072 of file SPIRVBaseInfo.cpp.
References CASE, GLSL_std_450, llvm_unreachable, OpenCL_std, and SPV_AMD_shader_trinary_minmax.
getFPFastMathModeName()
std::string llvm::SPIRV::getFPFastMathModeName (uint32_t e)
Definition at line 532 of file SPIRVBaseInfo.cpp.
References AllowRecip, Fast, None, NotInf, NotNaN, and NSZ.
Referenced by llvm::SPIRVInstPrinter::printFPFastMathMode().
getFPRoundingModeName()
StringRef llvm::SPIRV::getFPRoundingModeName (FPRoundingMode e)
Definition at line 570 of file SPIRVBaseInfo.cpp.
References CASE, llvm_unreachable, RTE, RTN, RTP, and RTZ.
Referenced by llvm::SPIRVInstPrinter::printFPRoundingMode().
getFunctionControlName()
std::string llvm::SPIRV::getFunctionControlName (uint32_t e)
Definition at line 864 of file SPIRVBaseInfo.cpp.
References Const, DontInline, Inline, None, and Pure.
Referenced by llvm::SPIRVInstPrinter::printFunctionControl().
getFunctionParameterAttributeName()
StringRef llvm::SPIRV::getFunctionParameterAttributeName (FunctionParameterAttribute e)
Definition at line 600 of file SPIRVBaseInfo.cpp.
References ByVal, CASE, llvm_unreachable, NoAlias, NoCapture, NoReadWrite, NoWrite, Sext, Sret, and Zext.
Referenced by llvm::SPIRVInstPrinter::printFunctionParameterAttribute().
getGroupOperationName()
StringRef llvm::SPIRV::getGroupOperationName (GroupOperation e)
Definition at line 1039 of file SPIRVBaseInfo.cpp.
References CASE, ClusteredReduce, ExclusiveScan, InclusiveScan, llvm_unreachable, PartitionedExclusiveScanNV, PartitionedInclusiveScanNV, PartitionedReduceNV, and Reduce.
Referenced by llvm::SPIRVInstPrinter::printGroupOperation().
getImageChannelDataTypeName()
StringRef llvm::SPIRV::getImageChannelDataTypeName (ImageChannelDataType e)
Definition at line 416 of file SPIRVBaseInfo.cpp.
References CASE, Float, HalfFloat, llvm_unreachable, SignedInt16, SignedInt32, SignedInt8, SnormInt16, SnormInt8, UnormInt101010, UnormInt101010_2, UnormInt16, UnormInt24, UnormInt8, UnormShort555, UnormShort565, UnsigendInt32, UnsignedInt16, and UnsignedInt8.
Referenced by llvm::SPIRVInstPrinter::printImageChannelDataType().
getImageChannelOrderName()
StringRef llvm::SPIRV::getImageChannelOrderName (ImageChannelOrder e)
Definition at line 389 of file SPIRVBaseInfo.cpp.
References A, ABGR, ARGB, BGRA, CASE, Depth, DepthStencil, Intensity, llvm_unreachable, Luminance, RA, RG, RGB, RGBA, RGBx, RGx, Rx, sBGRA, sRGB, sRGBA, and sRGBx.
Referenced by llvm::SPIRVInstPrinter::printImageChannelOrder().
getImageFormatName()
StringRef llvm::SPIRV::getImageFormatName (ImageFormat e)
Definition at line 342 of file SPIRVBaseInfo.cpp.
References CASE, llvm_unreachable, R11fG11fB10f, R16, R16f, R16i, R16Snorm, R16ui, R32f, R32i, R32ui, R8, R8i, R8Snorm, R8ui, Rg16, Rg16f, Rg16i, Rg16Snorm, Rg16ui, Rg32f, Rg32i, Rg32ui, Rg8, Rg8i, Rg8Snorm, Rg8ui, Rgb10A2, Rgb10a2ui, Rgba16, Rgba16f, Rgba16i, Rgba16Snorm, Rgba16ui, Rgba32f, Rgba32i, Rgba32ui, Rgba8, Rgba8i, Rgba8Snorm, Rgba8ui, and Unknown.
Referenced by llvm::SPIRVInstPrinter::printImageFormat().
getImageOperandName()
std::string llvm::SPIRV::getImageOperandName (uint32_t e)
Definition at line 440 of file SPIRVBaseInfo.cpp.
References Bias, ConstOffset, ConstOffsets, Grad, Lod, MakeTexelAvailableKHR, MakeTexelVisibleKHR, MinLod, None, NonPrivateTexelKHR, Offset, Sample, SignExtend, VolatileTexelKHR, and ZeroExtend.
Referenced by llvm::SPIRVInstPrinter::printImageOperand().
getKernelEnqueueFlagsName()
StringRef llvm::SPIRV::getKernelEnqueueFlagsName (KernelEnqueueFlags e)
Definition at line 1053 of file SPIRVBaseInfo.cpp.
References CASE, llvm_unreachable, NoWait, WaitKernel, and WaitWorkGroup.
Referenced by llvm::SPIRVInstPrinter::printKernelEnqueueFlags().
getKernelProfilingInfoName()
StringRef llvm::SPIRV::getKernelProfilingInfoName (KernelProfilingInfo e)
Definition at line 1063 of file SPIRVBaseInfo.cpp.
References CASE, CmdExecTime, llvm_unreachable, and None.
Referenced by llvm::SPIRVInstPrinter::printKernelProfilingInfo().
getLinkageTypeName()
StringRef llvm::SPIRV::getLinkageTypeName (LinkageType e)
Definition at line 581 of file SPIRVBaseInfo.cpp.
References CASE, Export, Import, and llvm_unreachable.
Referenced by llvm::SPIRVInstPrinter::printLinkageType().
getLoopControlName()
std::string llvm::SPIRV::getLoopControlName (uint32_t e)
Definition at line 802 of file SPIRVBaseInfo.cpp.
References DependencyInfinite, DependencyLength, DontUnroll, IterationMultiple, MaxIterations, MinIterations, None, PartialCount, PeelCount, and Unroll.
Referenced by llvm::SPIRVInstPrinter::printLoopControl().
getMemoryModelName()
StringRef llvm::SPIRV::getMemoryModelName (MemoryModel e)
Definition at line 213 of file SPIRVBaseInfo.cpp.
References CASE, GLSL450, llvm_unreachable, OpenCL, Simple, and VulkanKHR.
Referenced by llvm::SPIRVInstPrinter::printMemoryModel().
getMemoryOperandName()
std::string llvm::SPIRV::getMemoryOperandName (uint32_t e)
Definition at line 982 of file SPIRVBaseInfo.cpp.
References Aligned, MakePointerAvailableKHR, MakePointerVisibleKHR, None, NonPrivatePointerKHR, Nontemporal, and Volatile.
Referenced by llvm::SPIRVInstPrinter::printMemoryOperand().
getMemorySemanticsName()
std::string llvm::SPIRV::getMemorySemanticsName (uint32_t e)
Definition at line 896 of file SPIRVBaseInfo.cpp.
References Acquire, AcquireRelease, AtomicCounterMemory, CrossWorkgroupMemory, ImageMemory, MakeAvailableKHR, MakeVisibleKHR, None, OutputMemoryKHR, Release, SequentiallyConsistent, SubgroupMemory, UniformMemory, and WorkgroupMemory.
Referenced by llvm::SPIRVInstPrinter::printMemorySemantics().
getSamplerAddressingModeName()
StringRef llvm::SPIRV::getSamplerAddressingModeName (SamplerAddressingMode e)
Definition at line 321 of file SPIRVBaseInfo.cpp.
References CASE, Clamp, ClampToEdge, llvm_unreachable, None, Repeat, and RepeatMirrored.
Referenced by llvm::SPIRVInstPrinter::printSamplerAddressingMode().
getSamplerFilterModeName()
StringRef llvm::SPIRV::getSamplerFilterModeName (SamplerFilterMode e)
Definition at line 333 of file SPIRVBaseInfo.cpp.
References CASE, Linear, llvm_unreachable, and Nearest.
Referenced by llvm::SPIRVInstPrinter::printSamplerFilterMode().
getScopeName()
StringRef llvm::SPIRV::getScopeName (Scope e)
Definition at line 1026 of file SPIRVBaseInfo.cpp.
References CASE, CrossDevice, Device, Invocation, llvm_unreachable, QueueFamilyKHR, Subgroup, and Workgroup.
Referenced by llvm::SPIRVInstPrinter::printScope().
getSelectionControlName()
std::string llvm::SPIRV::getSelectionControlName (uint32_t e)
Definition at line 782 of file SPIRVBaseInfo.cpp.
References DontFlatten, Flatten, and None.
Referenced by llvm::SPIRVInstPrinter::printSelectionControl().
getSourceLanguageName()
StringRef llvm::SPIRV::getSourceLanguageName (SourceLanguage e)
Definition at line 167 of file SPIRVBaseInfo.cpp.
References CASE, ESSL, GLSL, HLSL, llvm_unreachable, OpenCL_C, OpenCL_CPP, and Unknown.
Referenced by llvm::SPIRVInstPrinter::printSourceLanguage().
getStorageClassName()
StringRef llvm::SPIRV::getStorageClassName (StorageClass e)
Definition at line 280 of file SPIRVBaseInfo.cpp.
References AtomicCounter, CallableDataNV, CASE, CrossWorkgroup, Generic, HitAttributeNV, Image, IncomingCallableDataNV, IncomingRayPayloadNV, llvm_unreachable, PhysicalStorageBufferEXT, Private, PushConstant, RayPayloadNV, ShaderRecordBufferNV, StorageBuffer, Uniform, UniformConstant, and Workgroup.
Referenced by llvm::SPIRVInstPrinter::printStorageClass().