LLVM: llvm::coverage Namespace Reference
llvm::coverage Namespace Reference
Namespaces
namespace accessors
This namespace defines accessors shared by different versions of coverage mapping records.
Classes
class BinaryCoverageReader
Reader for the coverage mapping data that is emitted by the frontend and stored in an object file.
struct CountedRegion
Associates a source range with an execution count.
struct Counter
A Counter is an abstract value that describes how to compute the execution count for a region of code using the collected profile count data.
struct CounterExpression
A Counter expression is a value that represents an arithmetic operation with two counters.
class CounterExpressionBuilder
A Counter expression builder is used to construct the counter expressions.
class CounterMappingContext
A Counter mapping context is used to connect the counters, expressions and the obtained counter values.
struct CounterMappingRegion
A Counter mapping region associates a source range with a specific counter.
class CoverageData
Coverage information to be processed or displayed.
class CoverageFilenamesSectionWriter
Writer of the filenames section for the instrumentation based code coverage.
class CoverageMapError
class CoverageMapping
The mapping of profile information to coverage data.
class CoverageMappingIterator
A file format agnostic iterator over coverage mapping data.
class CoverageMappingReader
struct CoverageMappingRecord
Coverage mapping information for a single function.
class CoverageMappingWriter
Writer for instrumentation based coverage mapping data.
struct CoverageSegment
The execution count information starting at a point in a file.
struct CovMapFunctionRecordV1
struct CovMapFunctionRecordV2
struct CovMapFunctionRecordV3
struct CovMapHeader
struct CovMapTraits
struct CovMapTraits< CovMapVersion::Version1, IntPtrT >
struct CovMapTraits< CovMapVersion::Version2, IntPtrT >
struct CovMapTraits< CovMapVersion::Version3, IntPtrT >
struct ExpansionRecord
Coverage information for a macro expansion or #included file.
struct FunctionRecord
Code coverage information for a single function.
class FunctionRecordIterator
Iterator over Functions, optionally filtered to a single file.
class InstantiationGroup
An instantiation group contains a FunctionRecord list, such that each record corresponds to a distinct instantiation of the same function.
class LineCoverageIterator
An iterator over the LineCoverageStats objects for lines described by a CoverageData instance.
class LineCoverageStats
Coverage statistics for a single line.
class RawCoverageFilenamesReader
Reader for the raw coverage filenames.
class RawCoverageMappingDummyChecker
Checks if the given coverage mapping data is exported for an unused function.
class RawCoverageMappingReader
Reader for the raw coverage mapping data.
class RawCoverageReader
Base class for the raw coverage mapping and filenames data readers.
Typedefs
using LineColPair = std::pair<unsigned, unsigned>
Enumerations
enum class coveragemap_error {
success = 0 , eof , no_data_found , unsupported_version ,
truncated , malformed , decompression_failed , invalid_or_missing_arch_specifier
}
enum CovMapVersion {
Version1 = 0 , Version2 = 1 , Version3 = 2 , Version4 = 3 ,
Version5 = 4 , Version6 = 5 , CurrentVersion = INSTR_PROF_COVMAP_VERSION
}
Functions
const std::error_category & coveragemap_category ()
std::error_code make_error_code (coveragemap_error E)
static iterator_range< LineCoverageIterator > getLineCoverageStats (const coverage::CoverageData &CD)
Get a LineCoverageIterator range for the lines described by CD.
Typedef Documentation
LineColPair
using llvm::coverage::LineColPair = std::pair<unsigned, unsigned>
Definition at line 205 of file CoverageMapping.h.
Enumeration Type Documentation
coveragemap_error
enum class llvm::coverage::coveragemap_error strong
Enumerator
success
eof
no_data_found
unsupported_version
truncated
malformed
decompression_failed
invalid_or_missing_arch_specifier
Definition at line 51 of file CoverageMapping.h.
CovMapVersion
enum llvm::coverage::CovMapVersion
Enumerator
Version1
Version2
Version3
Version4
Version5
Version6
CurrentVersion
Definition at line 992 of file CoverageMapping.h.
Function Documentation
coveragemap_category()
const std::error_category & llvm::coverage::coveragemap_category ()
Definition at line 901 of file CoverageMapping.cpp.
Referenced by make_error_code().
getLineCoverageStats()
static iterator_range< LineCoverageIterator > llvm::coverage::getLineCoverageStats (const coverage::CoverageData & CD) inline static
Get a LineCoverageIterator range for the lines described by CD.
Definition at line 736 of file CoverageMapping.h.
References llvm::make_range().
make_error_code()
std::error_code llvm::coverage::make_error_code (coveragemap_error E) inline
Definition at line 64 of file CoverageMapping.h.
References coveragemap_category(), and E.
Referenced by llvm::coverage::CoverageMapError::convertToErrorCode().