LLVM: llvm::symbolize Namespace Reference
llvm::symbolize Namespace Reference
Classes
class CachedBinary
class DIFetcher
The DIFetcher interface provides arbitrary mechanisms for obtaining debug info from an outside source.
class DIPrinter
class GNUPrinter
class JSONPrinter
class LLVMPrinter
class LLVMSymbolizer
class LocalDIFetcher
LocalDIFetcher searches local cache directories for debug info.
class MarkupFilter
Filter to convert parsed log symbolizer markup elements into human-readable text.
struct MarkupNode
A node of symbolizer markup.
class MarkupParser
Parses a log containing symbolizer markup into a sequence of nodes.
class PlainPrinterBase
struct PrinterConfig
struct Request
class SourceCode
class SymbolizableModule
class SymbolizableObjectFile
Typedefs
using FunctionNameKind = DILineInfoSpecifier::FunctionNameKind
using FileLineInfoKind = DILineInfoSpecifier::FileLineInfoKind
Functions
Optional< ArrayRef< uint8_t > > getBuildID (const ELFObjectFileBase *Obj)
static std::string toHex (uint64_t V)
static json::Object toJSON (const Request &Request, StringRef ErrorMsg="")
static StringRef takeTo (StringRef Str, StringRef::iterator Pos)
static void advanceTo (StringRef &Str, StringRef::iterator Pos)
static MarkupNode textNode (StringRef Text)
static StringRef getBuildIDStr (ArrayRef< uint8_t > BuildID)
Variables
static const char SGRSyntaxStr [] = "\033\\[([0-1]|3[0-7])m"
Typedef Documentation
FileLineInfoKind
using llvm::symbolize::FileLineInfoKind = DILineInfoSpecifier::FileLineInfoKind
Definition at line 46 of file Symbolize.h.
FunctionNameKind
typedef DILineInfoSpecifier::FunctionNameKind llvm::symbolize::FunctionNameKind = DILineInfoSpecifier::FunctionNameKind
Definition at line 21 of file SymbolizableModule.h.
Function Documentation
advanceTo()
static void llvm::symbolize::advanceTo (StringRef & Str, StringRef::iterator Pos) static
Definition at line 34 of file Markup.cpp.
Referenced by llvm::symbolize::MarkupParser::nextNode().
getBuildID()
Optional< ArrayRef< uint8_t > > llvm::symbolize::getBuildID (const ELFObjectFileBase * Obj)
Definition at line 332 of file Symbolize.cpp.
References llvm::dyn_cast(), getBuildID(), and llvm_unreachable.
Referenced by getBuildID().
getBuildIDStr()
static StringRef llvm::symbolize::getBuildIDStr (ArrayRef< uint8_t > BuildID) static
Definition at line 461 of file Symbolize.cpp.
takeTo()
static StringRef llvm::symbolize::takeTo (StringRef Str, StringRef::iterator Pos) static
Definition at line 31 of file Markup.cpp.
Referenced by llvm::symbolize::MarkupParser::nextNode().
textNode()
static MarkupNode llvm::symbolize::textNode (StringRef Text) static
Definition at line 145 of file Markup.cpp.
toHex()
static std::string llvm::symbolize::toHex (uint64_t V) static
Definition at line 278 of file DIPrinter.cpp.
References llvm::Twine::utohexstr().
Referenced by llvm::symbolize::JSONPrinter::print(), llvm::symbolize::JSONPrinter::print(), llvm::symbolize::JSONPrinter::print(), and toJSON().
toJSON()
static json::Object llvm::symbolize::toJSON (const Request & Request, StringRef ErrorMsg = "") static
Definition at line 282 of file DIPrinter.cpp.
References llvm::symbolize::Request::Address, llvm::symbolize::Request::ModuleName, llvm::StringRef::str(), and toHex().
Referenced by llvm::symbolize::JSONPrinter::print(), llvm::symbolize::JSONPrinter::print(), llvm::symbolize::JSONPrinter::print(), and llvm::symbolize::JSONPrinter::printError().
Variable Documentation
SGRSyntaxStr
const char llvm::symbolize::SGRSyntaxStr[] = "\033\\[([0-1]|3[0-7])m" static
Definition at line 26 of file Markup.cpp.