LLVM: lib/Target/AMDGPU/R600TargetMachine.cpp File Reference
R600TargetMachine.cpp File Reference
The AMDGPU-R600 target machine contains all of the hardware specific information needed to emit code for R600 GPUs.
#include "R600TargetMachine.h"
#include "AMDGPUTargetMachine.h"
#include "R600.h"
#include "R600MachineScheduler.h"
#include "R600TargetTransformInfo.h"
#include "llvm/Transforms/Scalar.h"
Classes
class R600PassConfig
Functions
static ScheduleDAGInstrs * createR600MachineScheduler (MachineSchedContext *C)
Variables
static cl::opt< bool > EnableR600StructurizeCFG ("r600-ir-structurize", cl::desc("Use StructurizeCFG IR pass"), cl::init(true))
static cl::opt< bool > EnableR600IfConvert ("r600-if-convert", cl::desc("Use if conversion pass"), cl::ReallyHidden, cl::init(true))
static cl::opt< bool, true > EnableAMDGPUFunctionCallsOpt ("amdgpu-function-calls", cl::desc("Enable AMDGPU function call support"), cl::location(AMDGPUTargetMachine::EnableFunctionCalls), cl::init(true), cl::Hidden)
static MachineSchedRegistry R600SchedRegistry ("r600", "Run R600's custom scheduler", createR600MachineScheduler)
Detailed Description
The AMDGPU-R600 target machine contains all of the hardware specific information needed to emit code for R600 GPUs.
Definition in file R600TargetMachine.cpp.
Function Documentation
createR600MachineScheduler()
static ScheduleDAGInstrs * createR600MachineScheduler (MachineSchedContext * C) static
Definition at line 38 of file R600TargetMachine.cpp.
References llvm::CallingConv::C.
Referenced by R600PassConfig::createMachineScheduler().
Variable Documentation
EnableAMDGPUFunctionCallsOpt
cl::opt< bool, true > EnableAMDGPUFunctionCallsOpt("amdgpu-function-calls", cl::desc("Enable AMDGPU function call support"), cl::location(AMDGPUTargetMachine::EnableFunctionCalls), cl::init(true), cl::Hidden) ("amdgpu-function-calls" , cl::desc("Enable AMDGPU function call support") , cl::location(AMDGPUTargetMachine::EnableFunctionCalls) , cl::init(true) , cl::Hidden) static
Referenced by llvm::R600TargetMachine::R600TargetMachine().
EnableR600IfConvert
cl::opt< bool > EnableR600IfConvert("r600-if-convert", cl::desc("Use if conversion pass"), cl::ReallyHidden, cl::init(true)) ("r600-if-convert" , cl::desc("Use if conversion pass") , cl::ReallyHidden , cl::init(true)) static
Referenced by R600PassConfig::addPreSched2().
EnableR600StructurizeCFG
cl::opt< bool > EnableR600StructurizeCFG("r600-ir-structurize", cl::desc("Use StructurizeCFG IR pass"), cl::init(true)) ("r600-ir-structurize" , cl::desc("Use StructurizeCFG IR pass") , cl::init(true)) static
Referenced by R600PassConfig::addPreISel().
R600SchedRegistry
MachineSchedRegistry R600SchedRegistry("r600", "Run R600's custom scheduler", createR600MachineScheduler) ("r600" , "Run R600's custom scheduler" , createR600MachineScheduler) static