LLVM: lib/CodeGen/RegAllocScore.cpp File Reference
RegAllocScore.cpp File Reference
#include "RegAllocScore.h"
#include "llvm/ADT/DenseMapInfo.h"
#include "llvm/ADT/STLForwardCompat.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/ilist_iterator.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBundleIterator.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "regalloc-score"
Variables
cl::opt< double > CopyWeight ("regalloc-copy-weight", cl::init(0.2), cl::Hidden)
cl::opt< double > LoadWeight ("regalloc-load-weight", cl::init(4.0), cl::Hidden)
cl::opt< double > StoreWeight ("regalloc-store-weight", cl::init(1.0), cl::Hidden)
cl::opt< double > CheapRematWeight ("regalloc-cheap-remat-weight", cl::init(0.2), cl::Hidden)
cl::opt< double > ExpensiveRematWeight ("regalloc-expensive-remat-weight", cl::init(1.0), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "regalloc-score"
Definition at line 38 of file RegAllocScore.cpp.
Variable Documentation
CheapRematWeight
cl::opt< double > CheapRematWeight("regalloc-cheap-remat-weight", cl::init(0.2), cl::Hidden) ("regalloc-cheap-remat-weight" , cl::init(0.2) , cl::Hidden)
Referenced by llvm::RegAllocScore::getScore().
CopyWeight
cl::opt< double > CopyWeight("regalloc-copy-weight", cl::init(0.2), cl::Hidden) ("regalloc-copy-weight" , cl::init(0.2) , cl::Hidden)
Referenced by llvm::RegAllocScore::getScore().
ExpensiveRematWeight
cl::opt< double > ExpensiveRematWeight("regalloc-expensive-remat-weight", cl::init(1.0), cl::Hidden) ("regalloc-expensive-remat-weight" , cl::init(1.0) , cl::Hidden)
Referenced by llvm::RegAllocScore::getScore().
LoadWeight
cl::opt< double > LoadWeight("regalloc-load-weight", cl::init(4.0), cl::Hidden) ("regalloc-load-weight" , cl::init(4.0) , cl::Hidden)
Referenced by llvm::RegAllocScore::getScore().
StoreWeight
cl::opt< double > StoreWeight("regalloc-store-weight", cl::init(1.0), cl::Hidden) ("regalloc-store-weight" , cl::init(1.0) , cl::Hidden)
Referenced by llvm::RegAllocScore::getScore().