LLVM: lib/Analysis/ScalarEvolutionAliasAnalysis.cpp File Reference
ScalarEvolutionAliasAnalysis.cpp File Reference
#include "llvm/Analysis/ScalarEvolutionAliasAnalysis.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/InitializePasses.h"
Functions
static bool canComputePointerDiff (ScalarEvolution &SE, const SCEV *A, const SCEV *B)
INITIALIZE_PASS_BEGIN (SCEVAAWrapperPass, "scev-aa", "ScalarEvolution-based Alias Analysis", false, true) INITIALIZE_PASS_END(SCEVAAWrapperPass
Variables
scev aa
scev ScalarEvolution based Alias Analysis
scev ScalarEvolution based Alias false
Function Documentation
canComputePointerDiff()
static bool canComputePointerDiff (ScalarEvolution & SE, const SCEV * A, const SCEV * B) static
Definition at line 27 of file ScalarEvolutionAliasAnalysis.cpp.
References A, B, llvm::ScalarEvolution::getEffectiveSCEVType(), and llvm::ScalarEvolution::instructionCouldExistWitthOperands().
Referenced by llvm::SCEVAAResult::alias().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (SCEVAAWrapperPass , "scev-aa" , "ScalarEvolution-based Alias Analysis" , false , true)
Variable Documentation
aa
scev aa
Definition at line 149 of file ScalarEvolutionAliasAnalysis.cpp.
Analysis
scev ScalarEvolution based Alias Analysis
Definition at line 150 of file ScalarEvolutionAliasAnalysis.cpp.
false
scev ScalarEvolution based Alias false
Definition at line 150 of file ScalarEvolutionAliasAnalysis.cpp.