LLVM: lib/Target/SPIRV/MCTargetDesc/SPIRVBaseInfo.h File Reference
SPIRVBaseInfo.h File Reference
#include "llvm/ADT/StringRef.h"
#include <string>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::SPIRV
Enumerations
enum class llvm::SPIRV::Capability : uint32_t {
llvm::SPIRV::Matrix = 0 , llvm::SPIRV::Shader = 1 , llvm::SPIRV::Geometry = 2 , llvm::SPIRV::Tessellation = 3 ,
llvm::SPIRV::Addresses = 4 , llvm::SPIRV::Linkage = 5 , llvm::SPIRV::Kernel = 6 , llvm::SPIRV::Vector16 = 7 ,
llvm::SPIRV::Float16Buffer = 8 , llvm::SPIRV::Float16 = 9 , llvm::SPIRV::Float64 = 10 , llvm::SPIRV::Int64 = 11 ,
llvm::SPIRV::Int64Atomics = 12 , llvm::SPIRV::ImageBasic = 13 , llvm::SPIRV::ImageReadWrite = 14 , llvm::SPIRV::ImageMipmap = 15 ,
llvm::SPIRV::Pipes = 17 , llvm::SPIRV::Groups = 18 , llvm::SPIRV::DeviceEnqueue = 19 , llvm::SPIRV::LiteralSampler = 20 ,
llvm::SPIRV::AtomicStorage = 21 , llvm::SPIRV::Int16 = 22 , llvm::SPIRV::TessellationPointSize = 23 , llvm::SPIRV::GeometryPointSize = 24 ,
llvm::SPIRV::ImageGatherExtended = 25 , llvm::SPIRV::StorageImageMultisample = 27 , llvm::SPIRV::UniformBufferArrayDynamicIndexing = 28 , llvm::SPIRV::SampledImageArrayDymnamicIndexing = 29 ,
llvm::SPIRV::ClipDistance = 32 , llvm::SPIRV::CullDistance = 33 , llvm::SPIRV::ImageCubeArray = 34 , llvm::SPIRV::SampleRateShading = 35 ,
llvm::SPIRV::ImageRect = 36 , llvm::SPIRV::SampledRect = 37 , llvm::SPIRV::GenericPointer = 38 , llvm::SPIRV::Int8 = 39 ,
llvm::SPIRV::InputAttachment = 40 , llvm::SPIRV::SparseResidency = 41 , llvm::SPIRV::MinLod = 42 , llvm::SPIRV::Sampled1D = 43 ,
llvm::SPIRV::Image1D = 44 , llvm::SPIRV::SampledCubeArray = 45 , llvm::SPIRV::SampledBuffer = 46 , llvm::SPIRV::ImageBuffer = 47 ,
llvm::SPIRV::ImageMSArray = 48 , llvm::SPIRV::StorageImageExtendedFormats = 49 , llvm::SPIRV::ImageQuery = 50 , llvm::SPIRV::DerivativeControl = 51 ,
llvm::SPIRV::InterpolationFunction = 52 , llvm::SPIRV::TransformFeedback = 53 , llvm::SPIRV::GeometryStreams = 54 , llvm::SPIRV::StorageImageReadWithoutFormat = 55 ,
llvm::SPIRV::StorageImageWriteWithoutFormat = 56 , llvm::SPIRV::MultiViewport = 57 , llvm::SPIRV::SubgroupDispatch = 58 , llvm::SPIRV::NamedBarrier = 59 ,
llvm::SPIRV::PipeStorage = 60 , llvm::SPIRV::GroupNonUniform = 61 , llvm::SPIRV::GroupNonUniformVote = 62 , llvm::SPIRV::GroupNonUniformArithmetic = 63 ,
llvm::SPIRV::GroupNonUniformBallot = 64 , llvm::SPIRV::GroupNonUniformShuffle = 65 , llvm::SPIRV::GroupNonUniformShuffleRelative = 66 , llvm::SPIRV::GroupNonUniformClustered = 67 ,
llvm::SPIRV::GroupNonUniformQuad = 68 , llvm::SPIRV::SubgroupBallotKHR = 4423 , llvm::SPIRV::DrawParameters = 4427 , llvm::SPIRV::SubgroupVoteKHR = 4431 ,
llvm::SPIRV::StorageBuffer16BitAccess = 4433 , llvm::SPIRV::StorageUniform16 = 4434 , llvm::SPIRV::StoragePushConstant16 = 4435 , llvm::SPIRV::StorageInputOutput16 = 4436 ,
llvm::SPIRV::DeviceGroup = 4437 , llvm::SPIRV::MultiView = 4439 , llvm::SPIRV::VariablePointersStorageBuffer = 4441 , llvm::SPIRV::VariablePointers = 4442 ,
llvm::SPIRV::AtomicStorageOps = 4445 , llvm::SPIRV::SampleMaskPostDepthCoverage = 4447 , llvm::SPIRV::StorageBuffer8BitAccess = 4448 , llvm::SPIRV::UniformAndStorageBuffer8BitAccess = 4449 ,
llvm::SPIRV::StoragePushConstant8 = 4450 , llvm::SPIRV::DenormPreserve = 4464 , llvm::SPIRV::DenormFlushToZero = 4465 , llvm::SPIRV::SignedZeroInfNanPreserve = 4466 ,
llvm::SPIRV::RoundingModeRTE = 4467 , llvm::SPIRV::RoundingModeRTZ = 4468 , llvm::SPIRV::Float16ImageAMD = 5008 , llvm::SPIRV::ImageGatherBiasLodAMD = 5009 ,
llvm::SPIRV::FragmentMaskAMD = 5010 , llvm::SPIRV::StencilExportEXT = 5013 , llvm::SPIRV::ImageReadWriteLodAMD = 5015 , llvm::SPIRV::SampleMaskOverrideCoverageNV = 5249 ,
llvm::SPIRV::GeometryShaderPassthroughNV = 5251 , llvm::SPIRV::ShaderViewportIndexLayerEXT = 5254 , llvm::SPIRV::ShaderViewportMaskNV = 5255 , llvm::SPIRV::ShaderStereoViewNV = 5259 ,
llvm::SPIRV::PerViewAttributesNV = 5260 , llvm::SPIRV::FragmentFullyCoveredEXT = 5265 , llvm::SPIRV::MeshShadingNV = 5266 , llvm::SPIRV::ShaderNonUniformEXT = 5301 ,
llvm::SPIRV::RuntimeDescriptorArrayEXT = 5302 , llvm::SPIRV::InputAttachmentArrayDynamicIndexingEXT = 5303 , llvm::SPIRV::UniformTexelBufferArrayDynamicIndexingEXT = 5304 , llvm::SPIRV::StorageTexelBufferArrayDynamicIndexingEXT = 5305 ,
llvm::SPIRV::UniformBufferArrayNonUniformIndexingEXT = 5306 , llvm::SPIRV::SampledImageArrayNonUniformIndexingEXT = 5307 , llvm::SPIRV::StorageBufferArrayNonUniformIndexingEXT = 5308 , llvm::SPIRV::StorageImageArrayNonUniformIndexingEXT = 5309 ,
llvm::SPIRV::InputAttachmentArrayNonUniformIndexingEXT = 5310 , llvm::SPIRV::UniformTexelBufferArrayNonUniformIndexingEXT = 5311 , llvm::SPIRV::StorageTexelBufferArrayNonUniformIndexingEXT = 5312 , llvm::SPIRV::RayTracingNV = 5340 ,
llvm::SPIRV::SubgroupShuffleINTEL = 5568 , llvm::SPIRV::SubgroupBufferBlockIOINTEL = 5569 , llvm::SPIRV::SubgroupImageBlockIOINTEL = 5570 , llvm::SPIRV::SubgroupImageMediaBlockIOINTEL = 5579 ,
llvm::SPIRV::SubgroupAvcMotionEstimationINTEL = 5696 , llvm::SPIRV::SubgroupAvcMotionEstimationIntraINTEL = 5697 , llvm::SPIRV::SubgroupAvcMotionEstimationChromaINTEL = 5698 , llvm::SPIRV::GroupNonUniformPartitionedNV = 5297 ,
llvm::SPIRV::VulkanMemoryModelKHR = 5345 , llvm::SPIRV::VulkanMemoryModelDeviceScopeKHR = 5346 , llvm::SPIRV::ImageFootprintNV = 5282 , llvm::SPIRV::FragmentBarycentricNV = 5284 ,
llvm::SPIRV::ComputeDerivativeGroupQuadsNV = 5288 , llvm::SPIRV::ComputeDerivativeGroupLinearNV = 5350 , llvm::SPIRV::FragmentDensityEXT = 5291 , llvm::SPIRV::PhysicalStorageBufferAddressesEXT = 5347 ,
llvm::SPIRV::CooperativeMatrixNV = 5357
}
enum class llvm::SPIRV::SourceLanguage : uint32_t {
llvm::SPIRV::Unknown = 0 , llvm::SPIRV::ESSL = 1 , llvm::SPIRV::GLSL = 2 , llvm::SPIRV::OpenCL_C = 3 ,
llvm::SPIRV::OpenCL_CPP = 4 , llvm::SPIRV::HLSL = 5
}
enum class llvm::SPIRV::AddressingModel : uint32_t { llvm::SPIRV::Logical = 0 , llvm::SPIRV::Physical32 = 1 , llvm::SPIRV::Physical64 = 2 , llvm::SPIRV::PhysicalStorageBuffer64EXT = 5348 }
enum class llvm::SPIRV::ExecutionModel : uint32_t {
llvm::SPIRV::Vertex = 0 , llvm::SPIRV::TessellationControl = 1 , llvm::SPIRV::TessellationEvaluation = 2 , llvm::SPIRV::Geometry = 3 ,
llvm::SPIRV::Fragment = 4 , llvm::SPIRV::GLCompute = 5 , llvm::SPIRV::Kernel = 6 , llvm::SPIRV::TaskNV = 5267 ,
llvm::SPIRV::MeshNV = 5268 , llvm::SPIRV::RayGenerationNV = 5313 , llvm::SPIRV::IntersectionNV = 5314 , llvm::SPIRV::AnyHitNV = 5315 ,
llvm::SPIRV::ClosestHitNV = 5316 , llvm::SPIRV::MissNV = 5317 , llvm::SPIRV::CallableNV = 5318
}
enum class llvm::SPIRV::MemoryModel : uint32_t { llvm::SPIRV::Simple = 0 , llvm::SPIRV::GLSL450 = 1 , llvm::SPIRV::OpenCL = 2 , llvm::SPIRV::VulkanKHR = 3 }
enum class llvm::SPIRV::ExecutionMode : uint32_t {
llvm::SPIRV::Invocations = 0 , llvm::SPIRV::SpacingEqual = 1 , llvm::SPIRV::SpacingFractionalEven = 2 , llvm::SPIRV::SpacingFractionalOdd = 3 ,
llvm::SPIRV::VertexOrderCw = 4 , llvm::SPIRV::VertexOrderCcw = 5 , llvm::SPIRV::PixelCenterInteger = 6 , llvm::SPIRV::OriginUpperLeft = 7 ,
llvm::SPIRV::OriginLowerLeft = 8 , llvm::SPIRV::EarlyFragmentTests = 9 , llvm::SPIRV::PointMode = 10 , llvm::SPIRV::Xfb = 11 ,
llvm::SPIRV::DepthReplacing = 12 , llvm::SPIRV::DepthGreater = 14 , llvm::SPIRV::DepthLess = 15 , llvm::SPIRV::DepthUnchanged = 16 ,
llvm::SPIRV::LocalSize = 17 , llvm::SPIRV::LocalSizeHint = 18 , llvm::SPIRV::InputPoints = 19 , llvm::SPIRV::InputLines = 20 ,
llvm::SPIRV::InputLinesAdjacency = 21 , llvm::SPIRV::Triangles = 22 , llvm::SPIRV::InputTrianglesAdjacency = 23 , llvm::SPIRV::Quads = 24 ,
llvm::SPIRV::Isolines = 25 , llvm::SPIRV::OutputVertices = 26 , llvm::SPIRV::OutputPoints = 27 , llvm::SPIRV::OutputLineStrip = 28 ,
llvm::SPIRV::OutputTriangleStrip = 29 , llvm::SPIRV::VecTypeHint = 30 , llvm::SPIRV::ContractionOff = 31 , llvm::SPIRV::Initializer = 33 ,
llvm::SPIRV::Finalizer = 34 , llvm::SPIRV::SubgroupSize = 35 , llvm::SPIRV::SubgroupsPerWorkgroup = 36 , llvm::SPIRV::SubgroupsPerWorkgroupId = 37 ,
llvm::SPIRV::LocalSizeId = 38 , llvm::SPIRV::LocalSizeHintId = 39 , llvm::SPIRV::PostDepthCoverage = 4446 , llvm::SPIRV::DenormPreserve = 4459 ,
llvm::SPIRV::DenormFlushToZero = 4460 , llvm::SPIRV::SignedZeroInfNanPreserve = 4461 , llvm::SPIRV::RoundingModeRTE = 4462 , llvm::SPIRV::RoundingModeRTZ = 4463 ,
llvm::SPIRV::StencilRefReplacingEXT = 5027 , llvm::SPIRV::OutputLinesNV = 5269 , llvm::SPIRV::DerivativeGroupQuadsNV = 5289 , llvm::SPIRV::DerivativeGroupLinearNV = 5290 ,
llvm::SPIRV::OutputTrianglesNV = 5298
}
enum class llvm::SPIRV::StorageClass : uint32_t {
llvm::SPIRV::UniformConstant = 0 , llvm::SPIRV::Input = 1 , llvm::SPIRV::Uniform = 2 , llvm::SPIRV::Output = 3 ,
llvm::SPIRV::Workgroup = 4 , llvm::SPIRV::CrossWorkgroup = 5 , llvm::SPIRV::Private = 6 , llvm::SPIRV::Function = 7 ,
llvm::SPIRV::Generic = 8 , llvm::SPIRV::PushConstant = 9 , llvm::SPIRV::AtomicCounter = 10 , llvm::SPIRV::Image = 11 ,
llvm::SPIRV::StorageBuffer = 12 , llvm::SPIRV::CallableDataNV = 5328 , llvm::SPIRV::IncomingCallableDataNV = 5329 , llvm::SPIRV::RayPayloadNV = 5338 ,
llvm::SPIRV::HitAttributeNV = 5339 , llvm::SPIRV::IncomingRayPayloadNV = 5342 , llvm::SPIRV::ShaderRecordBufferNV = 5343 , llvm::SPIRV::PhysicalStorageBufferEXT = 5349
}
enum class llvm::SPIRV::Dim : uint32_t {
llvm::SPIRV::DIM_1D = 0 , llvm::SPIRV::DIM_2D = 1 , llvm::SPIRV::DIM_3D = 2 , llvm::SPIRV::DIM_Cube = 3 ,
llvm::SPIRV::DIM_Rect = 4 , llvm::SPIRV::DIM_Buffer = 5 , llvm::SPIRV::DIM_SubpassData = 6
}
enum class llvm::SPIRV::SamplerAddressingMode : uint32_t {
llvm::SPIRV::None = 0 , llvm::SPIRV::ClampToEdge = 1 , llvm::SPIRV::Clamp = 2 , llvm::SPIRV::Repeat = 3 ,
llvm::SPIRV::RepeatMirrored = 4
}
enum class llvm::SPIRV::SamplerFilterMode : uint32_t { llvm::SPIRV::Nearest = 0 , llvm::SPIRV::Linear = 1 }
enum class llvm::SPIRV::ImageFormat : uint32_t {
llvm::SPIRV::Unknown = 0 , llvm::SPIRV::Rgba32f = 1 , llvm::SPIRV::Rgba16f = 2 , llvm::SPIRV::R32f = 3 ,
llvm::SPIRV::Rgba8 = 4 , llvm::SPIRV::Rgba8Snorm = 5 , llvm::SPIRV::Rg32f = 6 , llvm::SPIRV::Rg16f = 7 ,
llvm::SPIRV::R11fG11fB10f = 8 , llvm::SPIRV::R16f = 9 , llvm::SPIRV::Rgba16 = 10 , llvm::SPIRV::Rgb10A2 = 11 ,
llvm::SPIRV::Rg16 = 12 , llvm::SPIRV::Rg8 = 13 , llvm::SPIRV::R16 = 14 , llvm::SPIRV::R8 = 15 ,
llvm::SPIRV::Rgba16Snorm = 16 , llvm::SPIRV::Rg16Snorm = 17 , llvm::SPIRV::Rg8Snorm = 18 , llvm::SPIRV::R16Snorm = 19 ,
llvm::SPIRV::R8Snorm = 20 , llvm::SPIRV::Rgba32i = 21 , llvm::SPIRV::Rgba16i = 22 , llvm::SPIRV::Rgba8i = 23 ,
llvm::SPIRV::R32i = 24 , llvm::SPIRV::Rg32i = 25 , llvm::SPIRV::Rg16i = 26 , llvm::SPIRV::Rg8i = 27 ,
llvm::SPIRV::R16i = 28 , llvm::SPIRV::R8i = 29 , llvm::SPIRV::Rgba32ui = 30 , llvm::SPIRV::Rgba16ui = 31 ,
llvm::SPIRV::Rgba8ui = 32 , llvm::SPIRV::R32ui = 33 , llvm::SPIRV::Rgb10a2ui = 34 , llvm::SPIRV::Rg32ui = 35 ,
llvm::SPIRV::Rg16ui = 36 , llvm::SPIRV::Rg8ui = 37 , llvm::SPIRV::R16ui = 38 , llvm::SPIRV::R8ui = 39
}
enum class llvm::SPIRV::ImageChannelOrder : uint32_t {
llvm::SPIRV::R = 0 , llvm::SPIRV::A = 1 , llvm::SPIRV::RG = 2 , llvm::SPIRV::RA = 3 ,
llvm::SPIRV::RGB = 4 , llvm::SPIRV::RGBA = 5 , llvm::SPIRV::BGRA = 6 , llvm::SPIRV::ARGB = 7 ,
llvm::SPIRV::Intensity = 8 , llvm::SPIRV::Luminance = 9 , llvm::SPIRV::Rx = 10 , llvm::SPIRV::RGx = 11 ,
llvm::SPIRV::RGBx = 12 , llvm::SPIRV::Depth = 13 , llvm::SPIRV::DepthStencil = 14 , llvm::SPIRV::sRGB = 15 ,
llvm::SPIRV::sRGBx = 16 , llvm::SPIRV::sRGBA = 17 , llvm::SPIRV::sBGRA = 18 , llvm::SPIRV::ABGR = 19
}
enum class llvm::SPIRV::ImageChannelDataType : uint32_t {
llvm::SPIRV::SnormInt8 = 0 , llvm::SPIRV::SnormInt16 = 1 , llvm::SPIRV::UnormInt8 = 2 , llvm::SPIRV::UnormInt16 = 3 ,
llvm::SPIRV::UnormShort565 = 4 , llvm::SPIRV::UnormShort555 = 5 , llvm::SPIRV::UnormInt101010 = 6 , llvm::SPIRV::SignedInt8 = 7 ,
llvm::SPIRV::SignedInt16 = 8 , llvm::SPIRV::SignedInt32 = 9 , llvm::SPIRV::UnsignedInt8 = 10 , llvm::SPIRV::UnsignedInt16 = 11 ,
llvm::SPIRV::UnsigendInt32 = 12 , llvm::SPIRV::HalfFloat = 13 , llvm::SPIRV::Float = 14 , llvm::SPIRV::UnormInt24 = 15 ,
llvm::SPIRV::UnormInt101010_2 = 16
}
enum class llvm::SPIRV::ImageOperand : uint32_t {
llvm::SPIRV::None = 0x0 , llvm::SPIRV::Bias = 0x1 , llvm::SPIRV::Lod = 0x2 , llvm::SPIRV::Grad = 0x4 ,
llvm::SPIRV::ConstOffset = 0x8 , llvm::SPIRV::Offset = 0x10 , llvm::SPIRV::ConstOffsets = 0x20 , llvm::SPIRV::Sample = 0x40 ,
llvm::SPIRV::MinLod = 0x80 , llvm::SPIRV::MakeTexelAvailableKHR = 0x100 , llvm::SPIRV::MakeTexelVisibleKHR = 0x200 , llvm::SPIRV::NonPrivateTexelKHR = 0x400 ,
llvm::SPIRV::VolatileTexelKHR = 0x800 , llvm::SPIRV::SignExtend = 0x1000 , llvm::SPIRV::ZeroExtend = 0x2000
}
enum class llvm::SPIRV::FPFastMathMode : uint32_t {
llvm::SPIRV::None = 0x0 , llvm::SPIRV::NotNaN = 0x1 , llvm::SPIRV::NotInf = 0x2 , llvm::SPIRV::NSZ = 0x4 ,
llvm::SPIRV::AllowRecip = 0x8 , llvm::SPIRV::Fast = 0x10
}
enum class llvm::SPIRV::FPRoundingMode : uint32_t { llvm::SPIRV::RTE = 0 , llvm::SPIRV::RTZ = 1 , llvm::SPIRV::RTP = 2 , llvm::SPIRV::RTN = 3 }
enum class llvm::SPIRV::LinkageType : uint32_t { llvm::SPIRV::Export = 0 , llvm::SPIRV::Import = 1 }
enum class llvm::SPIRV::AccessQualifier : uint32_t { llvm::SPIRV::ReadOnly = 0 , llvm::SPIRV::WriteOnly = 1 , llvm::SPIRV::ReadWrite = 2 }
enum class llvm::SPIRV::FunctionParameterAttribute : uint32_t {
llvm::SPIRV::Zext = 0 , llvm::SPIRV::Sext = 1 , llvm::SPIRV::ByVal = 2 , llvm::SPIRV::Sret = 3 ,
llvm::SPIRV::NoAlias = 4 , llvm::SPIRV::NoCapture = 5 , llvm::SPIRV::NoWrite = 6 , llvm::SPIRV::NoReadWrite = 7
}
enum class llvm::SPIRV::Decoration : uint32_t {
llvm::SPIRV::RelaxedPrecision = 0 , llvm::SPIRV::SpecId = 1 , llvm::SPIRV::Block = 2 , llvm::SPIRV::BufferBlock = 3 ,
llvm::SPIRV::RowMajor = 4 , llvm::SPIRV::ColMajor = 5 , llvm::SPIRV::ArrayStride = 6 , llvm::SPIRV::MatrixStride = 7 ,
llvm::SPIRV::GLSLShared = 8 , llvm::SPIRV::GLSLPacked = 9 , llvm::SPIRV::CPacked = 10 , llvm::SPIRV::BuiltIn = 11 ,
llvm::SPIRV::NoPerspective = 13 , llvm::SPIRV::Flat = 14 , llvm::SPIRV::Patch = 15 , llvm::SPIRV::Centroid = 16 ,
llvm::SPIRV::Sample = 17 , llvm::SPIRV::Invariant = 18 , llvm::SPIRV::Restrict = 19 , llvm::SPIRV::Aliased = 20 ,
llvm::SPIRV::Volatile = 21 , llvm::SPIRV::Constant = 22 , llvm::SPIRV::Coherent = 23 , llvm::SPIRV::NonWritable = 24 ,
llvm::SPIRV::NonReadable = 25 , llvm::SPIRV::Uniform = 26 , llvm::SPIRV::UniformId = 27 , llvm::SPIRV::SaturatedConversion = 28 ,
llvm::SPIRV::Stream = 29 , llvm::SPIRV::Location = 30 , llvm::SPIRV::Component = 31 , llvm::SPIRV::Index = 32 ,
llvm::SPIRV::Binding = 33 , llvm::SPIRV::DescriptorSet = 34 , llvm::SPIRV::Offset = 35 , llvm::SPIRV::XfbBuffer = 36 ,
llvm::SPIRV::XfbStride = 37 , llvm::SPIRV::FuncParamAttr = 38 , llvm::SPIRV::FPRoundingMode = 39 , llvm::SPIRV::FPFastMathMode = 40 ,
llvm::SPIRV::LinkageAttributes = 41 , llvm::SPIRV::NoContraction = 42 , llvm::SPIRV::InputAttachmentIndex = 43 , llvm::SPIRV::Alignment = 44 ,
llvm::SPIRV::MaxByteOffset = 45 , llvm::SPIRV::AlignmentId = 46 , llvm::SPIRV::MaxByteOffsetId = 47 , llvm::SPIRV::NoSignedWrap = 4469 ,
llvm::SPIRV::NoUnsignedWrap = 4470 , llvm::SPIRV::ExplicitInterpAMD = 4999 , llvm::SPIRV::OverrideCoverageNV = 5248 , llvm::SPIRV::PassthroughNV = 5250 ,
llvm::SPIRV::ViewportRelativeNV = 5252 , llvm::SPIRV::SecondaryViewportRelativeNV = 5256 , llvm::SPIRV::PerPrimitiveNV = 5271 , llvm::SPIRV::PerViewNV = 5272 ,
llvm::SPIRV::PerVertexNV = 5273 , llvm::SPIRV::NonUniformEXT = 5300 , llvm::SPIRV::CountBuffer = 5634 , llvm::SPIRV::UserSemantic = 5635 ,
llvm::SPIRV::RestrictPointerEXT = 5355 , llvm::SPIRV::AliasedPointerEXT = 5356
}
enum class llvm::SPIRV::BuiltIn : uint32_t {
llvm::SPIRV::Position = 0 , llvm::SPIRV::PointSize = 1 , llvm::SPIRV::ClipDistance = 3 , llvm::SPIRV::CullDistance = 4 ,
llvm::SPIRV::VertexId = 5 , llvm::SPIRV::InstanceId = 6 , llvm::SPIRV::PrimitiveId = 7 , llvm::SPIRV::InvocationId = 8 ,
llvm::SPIRV::Layer = 9 , llvm::SPIRV::ViewportIndex = 10 , llvm::SPIRV::TessLevelOuter = 11 , llvm::SPIRV::TessLevelInner = 12 ,
llvm::SPIRV::TessCoord = 13 , llvm::SPIRV::PatchVertices = 14 , llvm::SPIRV::FragCoord = 15 , llvm::SPIRV::PointCoord = 16 ,
llvm::SPIRV::FrontFacing = 17 , llvm::SPIRV::SampleId = 18 , llvm::SPIRV::SamplePosition = 19 , llvm::SPIRV::SampleMask = 20 ,
llvm::SPIRV::FragDepth = 22 , llvm::SPIRV::HelperInvocation = 23 , llvm::SPIRV::NumWorkgroups = 24 , llvm::SPIRV::WorkgroupSize = 25 ,
llvm::SPIRV::WorkgroupId = 26 , llvm::SPIRV::LocalInvocationId = 27 , llvm::SPIRV::GlobalInvocationId = 28 , llvm::SPIRV::LocalInvocationIndex = 29 ,
llvm::SPIRV::WorkDim = 30 , llvm::SPIRV::GlobalSize = 31 , llvm::SPIRV::EnqueuedWorkgroupSize = 32 , llvm::SPIRV::GlobalOffset = 33 ,
llvm::SPIRV::GlobalLinearId = 34 , llvm::SPIRV::SubgroupSize = 36 , llvm::SPIRV::SubgroupMaxSize = 37 , llvm::SPIRV::NumSubgroups = 38 ,
llvm::SPIRV::NumEnqueuedSubgroups = 39 , llvm::SPIRV::SubgroupId = 40 , llvm::SPIRV::SubgroupLocalInvocationId = 41 , llvm::SPIRV::VertexIndex = 42 ,
llvm::SPIRV::InstanceIndex = 43 , llvm::SPIRV::SubgroupEqMask = 4416 , llvm::SPIRV::SubgroupGeMask = 4417 , llvm::SPIRV::SubgroupGtMask = 4418 ,
llvm::SPIRV::SubgroupLeMask = 4419 , llvm::SPIRV::SubgroupLtMask = 4420 , llvm::SPIRV::BaseVertex = 4424 , llvm::SPIRV::BaseInstance = 4425 ,
llvm::SPIRV::DrawIndex = 4426 , llvm::SPIRV::DeviceIndex = 4438 , llvm::SPIRV::ViewIndex = 4440 , llvm::SPIRV::BaryCoordNoPerspAMD = 4492 ,
llvm::SPIRV::BaryCoordNoPerspCentroidAMD = 4493 , llvm::SPIRV::BaryCoordNoPerspSampleAMD = 4494 , llvm::SPIRV::BaryCoordSmoothAMD = 4495 , llvm::SPIRV::BaryCoordSmoothCentroid = 4496 ,
llvm::SPIRV::BaryCoordSmoothSample = 4497 , llvm::SPIRV::BaryCoordPullModel = 4498 , llvm::SPIRV::FragStencilRefEXT = 5014 , llvm::SPIRV::ViewportMaskNV = 5253 ,
llvm::SPIRV::SecondaryPositionNV = 5257 , llvm::SPIRV::SecondaryViewportMaskNV = 5258 , llvm::SPIRV::PositionPerViewNV = 5261 , llvm::SPIRV::ViewportMaskPerViewNV = 5262 ,
llvm::SPIRV::FullyCoveredEXT = 5264 , llvm::SPIRV::TaskCountNV = 5274 , llvm::SPIRV::PrimitiveCountNV = 5275 , llvm::SPIRV::PrimitiveIndicesNV = 5276 ,
llvm::SPIRV::ClipDistancePerViewNV = 5277 , llvm::SPIRV::CullDistancePerViewNV = 5278 , llvm::SPIRV::LayerPerViewNV = 5279 , llvm::SPIRV::MeshViewCountNV = 5280 ,
llvm::SPIRV::MeshViewIndices = 5281 , llvm::SPIRV::BaryCoordNV = 5286 , llvm::SPIRV::BaryCoordNoPerspNV = 5287 , llvm::SPIRV::FragSizeEXT = 5292 ,
llvm::SPIRV::FragInvocationCountEXT = 5293 , llvm::SPIRV::LaunchIdNV = 5319 , llvm::SPIRV::LaunchSizeNV = 5320 , llvm::SPIRV::WorldRayOriginNV = 5321 ,
llvm::SPIRV::WorldRayDirectionNV = 5322 , llvm::SPIRV::ObjectRayOriginNV = 5323 , llvm::SPIRV::ObjectRayDirectionNV = 5324 , llvm::SPIRV::RayTminNV = 5325 ,
llvm::SPIRV::RayTmaxNV = 5326 , llvm::SPIRV::InstanceCustomIndexNV = 5327 , llvm::SPIRV::ObjectToWorldNV = 5330 , llvm::SPIRV::WorldToObjectNV = 5331 ,
llvm::SPIRV::HitTNV = 5332 , llvm::SPIRV::HitKindNV = 5333 , llvm::SPIRV::IncomingRayFlagsNV = 5351
}
enum class llvm::SPIRV::SelectionControl : uint32_t { llvm::SPIRV::None = 0x0 , llvm::SPIRV::Flatten = 0x1 , llvm::SPIRV::DontFlatten = 0x2 }
enum class llvm::SPIRV::LoopControl : uint32_t {
llvm::SPIRV::None = 0x0 , llvm::SPIRV::Unroll = 0x1 , llvm::SPIRV::DontUnroll = 0x2 , llvm::SPIRV::DependencyInfinite = 0x4 ,
llvm::SPIRV::DependencyLength = 0x8 , llvm::SPIRV::MinIterations = 0x10 , llvm::SPIRV::MaxIterations = 0x20 , llvm::SPIRV::IterationMultiple = 0x40 ,
llvm::SPIRV::PeelCount = 0x80 , llvm::SPIRV::PartialCount = 0x100
}
enum class llvm::SPIRV::FunctionControl : uint32_t {
llvm::SPIRV::None = 0x0 , llvm::SPIRV::Inline = 0x1 , llvm::SPIRV::DontInline = 0x2 , llvm::SPIRV::Pure = 0x4 ,
llvm::SPIRV::Const = 0x8
}
enum class llvm::SPIRV::MemorySemantics : uint32_t {
llvm::SPIRV::None = 0x0 , llvm::SPIRV::Acquire = 0x2 , llvm::SPIRV::Release = 0x4 , llvm::SPIRV::AcquireRelease = 0x8 ,
llvm::SPIRV::SequentiallyConsistent = 0x10 , llvm::SPIRV::UniformMemory = 0x40 , llvm::SPIRV::SubgroupMemory = 0x80 , llvm::SPIRV::WorkgroupMemory = 0x100 ,
llvm::SPIRV::CrossWorkgroupMemory = 0x200 , llvm::SPIRV::AtomicCounterMemory = 0x400 , llvm::SPIRV::ImageMemory = 0x800 , llvm::SPIRV::OutputMemoryKHR = 0x1000 ,
llvm::SPIRV::MakeAvailableKHR = 0x2000 , llvm::SPIRV::MakeVisibleKHR = 0x4000
}
enum class llvm::SPIRV::MemoryOperand : uint32_t {
llvm::SPIRV::None = 0x0 , llvm::SPIRV::Volatile = 0x1 , llvm::SPIRV::Aligned = 0x2 , llvm::SPIRV::Nontemporal = 0x4 ,
llvm::SPIRV::MakePointerAvailableKHR = 0x8 , llvm::SPIRV::MakePointerVisibleKHR = 0x10 , llvm::SPIRV::NonPrivatePointerKHR = 0x20
}
enum class llvm::SPIRV::Scope : uint32_t {
llvm::SPIRV::CrossDevice = 0 , llvm::SPIRV::Device = 1 , llvm::SPIRV::Workgroup = 2 , llvm::SPIRV::Subgroup = 3 ,
llvm::SPIRV::Invocation = 4 , llvm::SPIRV::QueueFamilyKHR = 5
}
enum class llvm::SPIRV::GroupOperation : uint32_t {
llvm::SPIRV::Reduce = 0 , llvm::SPIRV::InclusiveScan = 1 , llvm::SPIRV::ExclusiveScan = 2 , llvm::SPIRV::ClusteredReduce = 3 ,
llvm::SPIRV::PartitionedReduceNV = 6 , llvm::SPIRV::PartitionedInclusiveScanNV = 7 , llvm::SPIRV::PartitionedExclusiveScanNV = 8
}
enum class llvm::SPIRV::KernelEnqueueFlags : uint32_t { llvm::SPIRV::NoWait = 0 , llvm::SPIRV::WaitKernel = 1 , llvm::SPIRV::WaitWorkGroup = 2 }
enum class llvm::SPIRV::KernelProfilingInfo : uint32_t { llvm::SPIRV::None = 0x0 , llvm::SPIRV::CmdExecTime = 0x1 }
enum class llvm::SPIRV::InstructionSet : uint32_t { llvm::SPIRV::OpenCL_std = 0 , llvm::SPIRV::GLSL_std_450 = 1 , llvm::SPIRV::SPV_AMD_shader_trinary_minmax = 2 }
enum class llvm::SPIRV::Opcode : uint32_t { llvm::SPIRV::InBoundsPtrAccessChain = 70 , llvm::SPIRV::PtrCastToGeneric = 121 }
Functions
StringRef llvm::SPIRV::getCapabilityName (Capability e)
StringRef llvm::SPIRV::getSourceLanguageName (SourceLanguage e)
StringRef llvm::SPIRV::getAddressingModelName (AddressingModel e)
StringRef llvm::SPIRV::getExecutionModelName (ExecutionModel e)
StringRef llvm::SPIRV::getMemoryModelName (MemoryModel e)
StringRef llvm::SPIRV::getExecutionModeName (ExecutionMode e)
StringRef llvm::SPIRV::getStorageClassName (StorageClass e)
StringRef llvm::SPIRV::getDimName (Dim dim)
StringRef llvm::SPIRV::getSamplerAddressingModeName (SamplerAddressingMode e)
StringRef llvm::SPIRV::getSamplerFilterModeName (SamplerFilterMode e)
StringRef llvm::SPIRV::getImageFormatName (ImageFormat e)
StringRef llvm::SPIRV::getImageChannelOrderName (ImageChannelOrder e)
StringRef llvm::SPIRV::getImageChannelDataTypeName (ImageChannelDataType e)
std::string llvm::SPIRV::getImageOperandName (uint32_t e)
std::string llvm::SPIRV::getFPFastMathModeName (uint32_t e)
StringRef llvm::SPIRV::getFPRoundingModeName (FPRoundingMode e)
StringRef llvm::SPIRV::getLinkageTypeName (LinkageType e)
StringRef llvm::SPIRV::getAccessQualifierName (AccessQualifier e)
StringRef llvm::SPIRV::getFunctionParameterAttributeName (FunctionParameterAttribute e)
StringRef llvm::SPIRV::getDecorationName (Decoration e)
StringRef llvm::SPIRV::getBuiltInName (BuiltIn e)
std::string llvm::SPIRV::getSelectionControlName (uint32_t e)
std::string llvm::SPIRV::getLoopControlName (uint32_t e)
std::string llvm::SPIRV::getFunctionControlName (uint32_t e)
std::string llvm::SPIRV::getMemorySemanticsName (uint32_t e)
std::string llvm::SPIRV::getMemoryOperandName (uint32_t e)
StringRef llvm::SPIRV::getScopeName (Scope e)
StringRef llvm::SPIRV::getGroupOperationName (GroupOperation e)
StringRef llvm::SPIRV::getKernelEnqueueFlagsName (KernelEnqueueFlags e)
StringRef llvm::SPIRV::getKernelProfilingInfoName (KernelProfilingInfo e)
std::string llvm::SPIRV::getExtInstSetName (InstructionSet e)
template<class InstType >
std::string getSPIRVStringOperand (const InstType &MI, unsigned StartIndex)
Function Documentation
getSPIRVStringOperand()
template<class InstType > std::string getSPIRVStringOperand (const InstType & MI, unsigned StartIndex)
Definition at line 728 of file SPIRVBaseInfo.h.
References assert(), and MI.
Referenced by getStringImm(), and llvm::SPIRVInstPrinter::printStringImm().