LLVM: lib/Target/SPIRV/SPIRVGlobalRegistry.cpp File Reference
SPIRVGlobalRegistry.cpp File Reference
#include "SPIRVGlobalRegistry.h"
#include "SPIRV.h"
#include "SPIRVSubtarget.h"
#include "SPIRVTargetMachine.h"
#include "SPIRVUtils.h"
Functions
static Register createTypeVReg (MachineIRBuilder &MIRBuilder)
static Register createTypeVReg (MachineRegisterInfo &MRI)
static bool isOpenCLBuiltinType (const StructType *SType)
static bool isSPIRVBuiltinType (const StructType *SType)
static bool isSpecialType (const Type *Ty)
Function Documentation
createTypeVReg() [1/2]
static Register createTypeVReg (MachineIRBuilder & MIRBuilder) static
Definition at line 61 of file SPIRVGlobalRegistry.cpp.
References llvm::MachineIRBuilder::getMF(), llvm::MachineFunction::getRegInfo(), MRI, and llvm::LLT::scalar().
Referenced by llvm::SPIRVGlobalRegistry::getOrCreateSPIRVBoolType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVIntegerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), and llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType().
createTypeVReg() [2/2]
static Register createTypeVReg (MachineRegisterInfo & MRI) static
Definition at line 68 of file SPIRVGlobalRegistry.cpp.
References MRI, and llvm::LLT::scalar().
isOpenCLBuiltinType()
static bool isOpenCLBuiltinType (const StructType * SType) static
Definition at line 422 of file SPIRVGlobalRegistry.cpp.
Referenced by isSpecialType().
isSpecialType()
static bool isSpecialType (const Type * Ty) static
Definition at line 432 of file SPIRVGlobalRegistry.cpp.
References isOpenCLBuiltinType(), and isSPIRVBuiltinType().
isSPIRVBuiltinType()
static bool isSPIRVBuiltinType (const StructType * SType) static
Definition at line 427 of file SPIRVGlobalRegistry.cpp.
Referenced by isSpecialType().