LLVM: llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT > Struct Template Reference
llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT > Struct Template Reference
#include "llvm/Analysis/DOTGraphTraitsPass.h"
Public Member Functions
DOTGraphTraitsPrinter (StringRef GraphName)
virtual bool processFunction (Function &F, const typename AnalysisT::Result &Result)
Return true if this function should be processed.
PreservedAnalyses run (Function &F, FunctionAnalysisManager &FAM)
Public Member Functions inherited from llvm::PassInfoMixin< DerivedT >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Protected Member Functions
~DOTGraphTraitsPrinter ()
Avoid compiler warning "has virtual functions but non-virtual destructor [-Wnon-virtual-dtor]" in derived classes.
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< DerivedT >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
template<typename AnalysisT, bool IsSimple, typename GraphT = typename AnalysisT::Result *, typename AnalysisGraphTraitsT = DefaultAnalysisGraphTraits<typename AnalysisT::Result &, GraphT>>
struct llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >
Definition at line 109 of file DOTGraphTraitsPass.h.
Constructor & Destructor Documentation
DOTGraphTraitsPrinter()
template<typename AnalysisT , bool IsSimple, typename GraphT = typename AnalysisT::Result *, typename AnalysisGraphTraitsT = DefaultAnalysisGraphTraits<typename AnalysisT::Result &, GraphT>> llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::DOTGraphTraitsPrinter (StringRef GraphName) inline
Definition at line 112 of file DOTGraphTraitsPass.h.
~DOTGraphTraitsPrinter()
template<typename AnalysisT , bool IsSimple, typename GraphT = typename AnalysisT::Result *, typename AnalysisGraphTraitsT = DefaultAnalysisGraphTraits<typename AnalysisT::Result &, GraphT>> llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::~DOTGraphTraitsPrinter () inline protected
Avoid compiler warning "has virtual functions but non-virtual destructor [-Wnon-virtual-dtor]" in derived classes.
DOTGraphTraitsPrinter is also used as a mixin for avoiding repeated implementation of printer passes, ie there should be no runtime-polymorphisms/downcasting involving this class and hence no virtual destructor needed. Making this dtor protected stops accidental invocation when the derived class destructor should have been called. Those derived classes sould be marked final to avoid the warning.
Definition at line 147 of file DOTGraphTraitsPass.h.
Member Function Documentation
processFunction()
template<typename AnalysisT , bool IsSimple, typename GraphT = typename AnalysisT::Result *, typename AnalysisGraphTraitsT = DefaultAnalysisGraphTraits<typename AnalysisT::Result &, GraphT>> virtual bool llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::processFunction (Function & F, const typename AnalysisT::Result & Result) inline virtual
Return true if this function should be processed.
An implementation of this class my override this function to indicate that only certain functions should be viewed.
Parameters
Analysis The current analysis result for this function.
Definition at line 120 of file DOTGraphTraitsPass.h.
Referenced by llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::run().
run()
template<typename AnalysisT , bool IsSimple, typename GraphT = typename AnalysisT::Result *, typename AnalysisGraphTraitsT = DefaultAnalysisGraphTraits<typename AnalysisT::Result &, GraphT>> PreservedAnalyses llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::run (Function & F, FunctionAnalysisManager & FAM) inline
Definition at line 125 of file DOTGraphTraitsPass.h.
References llvm::PreservedAnalyses::all(), F, FAM, llvm::printGraphForFunction(), and llvm::DOTGraphTraitsPrinter< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::processFunction().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/DOTGraphTraitsPass.h