LLVM: M68kDisassembler Struct Reference
M68kDisassembler Struct Reference
A disassembler class for M68k.
Public Member Functions
M68kDisassembler (const MCSubtargetInfo &STI, MCContext &Ctx)
virtual ~M68kDisassembler ()
DecodeStatus getInstruction (MCInst &Instr, uint64_t &Size, ArrayRef< uint8_t > Bytes, uint64_t Address, raw_ostream &CStream) const override
Returns the disassembly of a single instruction.
Public Member Functions inherited from llvm::MCDisassembler
MCDisassembler (const MCSubtargetInfo &STI, MCContext &Ctx)
virtual ~MCDisassembler ()
virtual Optional< DecodeStatus > onSymbolStart (SymbolInfoTy &Symbol, uint64_t &Size, ArrayRef< uint8_t > Bytes, uint64_t Address, raw_ostream &CStream) const
Used to perform separate target specific disassembly for a particular symbol.
virtual uint64_t suggestBytesToSkip (ArrayRef< uint8_t > Bytes, uint64_t Address) const
Suggest a distance to skip in a buffer of data to find the next place to look for the start of an instruction.
bool tryAddingSymbolicOperand (MCInst &Inst, int64_t Value, uint64_t Address, bool IsBranch, uint64_t Offset, uint64_t OpSize, uint64_t InstSize) const
void tryAddingPcLoadReferenceComment (int64_t Value, uint64_t Address) const
void setSymbolizer (std::unique_ptr< MCSymbolizer > Symzer)
Set Symzer as the current symbolizer.
MCContext & getContext () const
const MCSubtargetInfo & getSubtargetInfo () const
Additional Inherited Members
Public Types inherited from llvm::MCDisassembler
enum DecodeStatus { Fail = 0 , SoftFail = 1 , Success = 3 }
Ternary decode status.
Public Attributes inherited from llvm::MCDisassembler
raw_ostream * CommentStream = nullptr
Protected Attributes inherited from llvm::MCDisassembler
const MCSubtargetInfo & STI
std::unique_ptr< MCSymbolizer > Symbolizer
Detailed Description
A disassembler class for M68k.
Definition at line 100 of file M68kDisassembler.cpp.
Constructor & Destructor Documentation
M68kDisassembler()
M68kDisassembler::M68kDisassembler (const MCSubtargetInfo & STI, MCContext & Ctx) inline
Definition at line 101 of file M68kDisassembler.cpp.
~M68kDisassembler()
virtual M68kDisassembler::~M68kDisassembler () inline virtual
Definition at line 103 of file M68kDisassembler.cpp.
Member Function Documentation
getInstruction()
DecodeStatus M68kDisassembler::getInstruction (MCInst & Instr, uint64_t & Size, ArrayRef< uint8_t > Bytes, uint64_t Address, raw_ostream & CStream) const override virtual
Returns the disassembly of a single instruction.
Parameters
Instr - An MCInst to populate with the contents of the instruction.
Size - A value to populate with the size of the instruction, or the number of bytes consumed while attempting to decode an invalid instruction.
Address - The address, in the memory space of region, of the first byte of the instruction.
Bytes - A reference to the actual bytes of the instruction.
CStream - The stream to print comments and annotations on.
Returns
- MCDisassembler::Success if the instruction is valid, MCDisassembler::SoftFail if the instruction was disassemblable but invalid, MCDisassembler::Fail if the instruction was invalid.
Implements llvm::MCDisassembler.
Definition at line 110 of file M68kDisassembler.cpp.
References Align, llvm::alignTo(), llvm::MCInst::getOpcode(), Idx, Insn, llvm::support::endian::read16be(), RoundUp(), Size, and llvm::MCDisassembler::STI.
The documentation for this struct was generated from the following file:
lib/Target/M68k/Disassembler/M68kDisassembler.cpp