LLVM: llvm::AAUndefinedBehavior Struct Reference
llvm::AAUndefinedBehavior Struct Reference abstract
An abstract attribute for undefined behavior.
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
using Base = StateWrapper<BooleanState, AbstractAttribute>
Public Types inherited from llvm::StateWrapper< BooleanState, AbstractAttribute >
using StateType
Provide static access to the type of the state.
Public Types inherited from llvm::AbstractAttribute
using StateType = AbstractState
Public Types inherited from llvm::IRPosition
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
using CallBaseContext = CallBase
Public Types inherited from llvm::AADepGraphNode
using DepTy = PointerIntPair<AADepGraphNode *, 1>
using iterator
using aaiterator
Public Types inherited from llvm::BooleanState
using super = IntegerStateBase<bool, true, false>
using base_t = IntegerStateBase::base_t
Public Types inherited from llvm::IntegerStateBase< bool, true, false >
using base_t
Public Member Functions
AAUndefinedBehavior (const IRPosition &IRP, Attributor &A)
bool isAssumedToCauseUB () const
Return true if "undefined behavior" is assumed.
virtual bool isAssumedToCauseUB (Instruction *I) const =0
Return true if "undefined behavior" is assumed for a specific instruction.
bool isKnownToCauseUB () const
Return true if "undefined behavior" is known.
virtual bool isKnownToCauseUB (Instruction *I) const =0
Return true if "undefined behavior" is known for a specific instruction.
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::StateWrapper< BooleanState, AbstractAttribute >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (const IRPosition &IRP)
virtual ~AbstractAttribute ()=default
Virtual destructor.
virtual void initialize (Attributor &A)
Initialize the state with the information in the Attributor A.
virtual bool isQueryAA () const
A query AA is always scheduled as long as we do updates because it does lazy computation that cannot be determined to be done from the outside.
const IRPosition & getIRPosition () const
Return an IR position, see struct IRPosition.
IRPosition & getIRPosition ()
void print (raw_ostream &OS) const override
Helper functions, for debug purposes only.
virtual void printWithDeps (raw_ostream &OS) const
void dump () const
virtual const std::string getAsStr () const =0
This function should return the "summarized" assumed state as string.
Public Member Functions inherited from llvm::IRPosition
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getCalleeArgNo () const
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
int getCallSiteArgNo () const
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Kind getPositionKind () const
Return the associated position kind.
bool hasAttr (ArrayRef< Attribute::AttrKind > AKs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
TODO: Figure out if the attribute related helper functions should live here or somewhere else.
void getAttrs (ArrayRef< Attribute::AttrKind > AKs, SmallVectorImpl< Attribute > &Attrs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
Return the attributes of any kind in AKs existing in the IR at a position that will affect this one.
void removeAttrs (ArrayRef< Attribute::AttrKind > AKs) const
Remove the attribute of kind AKs existing in the IR at this position.
bool isAnyCallSitePosition () const
bool isArgumentPosition () const
Return true if the position is an argument or call site argument.
IRPosition stripCallBaseContext () const
Return the same position without the call base context.
const CallBaseContext * getCallBaseContext () const
Get the call base context from the position.
bool hasCallBaseContext () const
Check if the position has any call base context.
operator void * () const
}
Public Member Functions inherited from llvm::AADepGraphNode
virtual ~AADepGraphNode ()=default
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
TinyPtrVector< DepTy > & getDeps ()
Public Member Functions inherited from llvm::BooleanState
BooleanState ()=default
BooleanState (base_t Assumed)
void setAssumed (bool Value)
Set the assumed value to Value but never below the known one.
void setKnown (bool Value)
Set the known and asssumed value to Value.
bool isAssumed () const
Return true if the state is assumed to hold.
bool isKnown () const
Return true if the state is known to hold.
Public Member Functions inherited from llvm::IntegerStateBase< bool, true, false >
IntegerStateBase ()=default
IntegerStateBase (base_t Assumed)
bool isValidState () const override
See AbstractState::isValidState() NOTE: For now we simply pretend that the worst possible state is invalid.
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint()
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
base_t getKnown () const
Return the known state encoding.
base_t getAssumed () const
Return the assumed state encoding.
bool operator== (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Equality for IntegerStateBase.
bool operator!= (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Inequality for IntegerStateBase.
void operator^= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator+= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator|= (const IntegerStateBase< base_t, BestState, WorstState > &R)
void operator&= (const IntegerStateBase< base_t, BestState, WorstState > &R)
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
Static Public Member Functions
static AAUndefinedBehavior & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAUndefineBehavior.
Static Public Member Functions inherited from llvm::AbstractAttribute
static bool classof (const AADepGraphNode *DGN)
This function is used to identify if an DGN is of type AbstractAttribute so that the dyn_cast and cast can use such information to cast an AADepGraphNode to an AbstractAttribute.
Static Public Member Functions inherited from llvm::IRPosition
static const IRPosition value (const Value &V, const CallBaseContext *CBContext=nullptr)
Create a position describing the value of V.
static const IRPosition inst (const Instruction &I, const CallBaseContext *CBContext=nullptr)
Create a position describing the instruction I.
static const IRPosition function (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg, const CallBaseContext *CBContext=nullptr)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP, const CallBaseContext *CBContext=nullptr)
Create a position with function scope matching the "context" of IRP.
Static Public Member Functions inherited from llvm::IntegerStateBase< bool, true, false >
static constexpr base_t getBestState ()
Return the best possible representable state.
static constexpr base_t getBestState (const IntegerStateBase &)
static constexpr base_t getWorstState ()
Return the worst possible representable state.
static constexpr base_t getWorstState (const IntegerStateBase &)
Static Public Attributes
static const char ID = 0
Unique ID (due to the unique address)
Static Public Attributes inherited from llvm::IRPosition
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Additional Inherited Members
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
virtual ChangeStatus manifest (Attributor &A)
Hook for the Attributor to trigger the manifestation of the information represented by the abstract attribute in the LLVM-IR.
virtual void trackStatistics () const =0
Hook to enable custom statistic tracking, called after manifest that resulted in a change if statistics are enabled.
virtual ChangeStatus updateImpl (Attributor &A)=0
The actual update/transfer function which has to be implemented by the derived classes.
Protected Member Functions inherited from llvm::AADepGraphNode
operator AbstractAttribute * ()
Protected Member Functions inherited from llvm::IntegerStateBase< bool, true, false >
virtual void handleNewAssumedValue (base_t Value)=0
Handle a new assumed value Value. Subtype dependent.
virtual void handleNewKnownValue (base_t Value)=0
Handle a new known value Value. Subtype dependent.
virtual void joinOR (base_t AssumedValue, base_t KnownValue)=0
Handle a value Value. Subtype dependent.
virtual void joinAND (base_t AssumedValue, base_t KnownValue)=0
Handle a new assumed value Value. Subtype dependent.
Static Protected Member Functions inherited from llvm::AADepGraphNode
static AADepGraphNode * DepGetVal (DepTy &DT)
static AbstractAttribute * DepGetValAA (DepTy &DT)
Protected Attributes inherited from llvm::AADepGraphNode
TinyPtrVector< DepTy > Deps
Set of dependency graph nodes which should be updated if this one is updated.
Protected Attributes inherited from llvm::IntegerStateBase< bool, true, false >
base_t Known
The known state encoding in an integer of type base_t.
base_t Assumed
The assumed state encoding in an integer of type base_t.
Detailed Description
An abstract attribute for undefined behavior.
Definition at line 3272 of file Attributor.h.
Member Typedef Documentation
Base
using llvm::AAUndefinedBehavior::Base = StateWrapper<BooleanState, AbstractAttribute>
Definition at line 3274 of file Attributor.h.
Constructor & Destructor Documentation
AAUndefinedBehavior()
llvm::AAUndefinedBehavior::AAUndefinedBehavior (const IRPosition & IRP, Attributor & A) inline
Definition at line 3275 of file Attributor.h.
Member Function Documentation
classof()
static bool llvm::AAUndefinedBehavior::classof (const AbstractAttribute * AA) inline static
This function should return true if the type of the AA is AAUndefineBehavior.
Definition at line 3301 of file Attributor.h.
References llvm::AbstractAttribute::getIdAddr().
createForPosition()
static AAUndefinedBehavior & llvm::AAUndefinedBehavior::createForPosition (const IRPosition & IRP, Attributor & A) static
Create an abstract attribute view for the position IRP.
getIdAddr()
const char * llvm::AAUndefinedBehavior::getIdAddr () const inline override virtual
See AbstractAttribute::getIdAddr()
Implements llvm::AbstractAttribute.
Definition at line 3297 of file Attributor.h.
References ID.
getName()
const std::string llvm::AAUndefinedBehavior::getName () const inline override virtual
See AbstractAttribute::getName()
Implements llvm::AbstractAttribute.
Definition at line 3294 of file Attributor.h.
isAssumedToCauseUB() [1/2]
bool llvm::AAUndefinedBehavior::isAssumedToCauseUB () const inline
Return true if "undefined behavior" is assumed.
Definition at line 3278 of file Attributor.h.
References llvm::IntegerStateBase< bool, true, false >::getAssumed().
isAssumedToCauseUB() [2/2]
virtual bool llvm::AAUndefinedBehavior::isAssumedToCauseUB (Instruction * I) const pure virtual
Return true if "undefined behavior" is assumed for a specific instruction.
isKnownToCauseUB() [1/2]
bool llvm::AAUndefinedBehavior::isKnownToCauseUB () const inline
Return true if "undefined behavior" is known.
Definition at line 3284 of file Attributor.h.
References llvm::IntegerStateBase< bool, true, false >::getKnown().
isKnownToCauseUB() [2/2]
virtual bool llvm::AAUndefinedBehavior::isKnownToCauseUB (Instruction * I) const pure virtual
Return true if "undefined behavior" is known for a specific instruction.
Member Data Documentation
ID
const char AAUndefinedBehavior::ID = 0 static
Unique ID (due to the unique address)
Definition at line 3306 of file Attributor.h.
Referenced by getIdAddr().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/AttributorAttributes.cpp