LLVM: llvm::AMDGPUPromoteKernelArgumentsPass Struct Reference
llvm::AMDGPUPromoteKernelArgumentsPass Struct Reference
#include "Target/AMDGPU/AMDGPU.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< AMDGPUPromoteKernelArgumentsPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< AMDGPUPromoteKernelArgumentsPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 106 of file AMDGPU.h.
Member Function Documentation
run()
PreservedAnalyses AMDGPUPromoteKernelArgumentsPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 208 of file AMDGPUPromoteKernelArguments.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserve(), and llvm::PreservedAnalyses::preserveSet().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/AMDGPU.h
lib/Target/AMDGPU/AMDGPUPromoteKernelArguments.cpp