LLVM: llvm::objcopy::elf::IHexRecord Struct Reference
llvm::objcopy::elf::IHexRecord Struct Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Types
enum Type {
Data = 0 , EndOfFile = 1 , SegmentAddr = 2 , StartAddr80x86 = 3 ,
ExtendedAddr = 4 , StartAddr = 5 , InvalidType = 6
}
Static Public Member Functions
static size_t getLength (size_t DataSize)
static size_t getLineLength (size_t DataSize)
static IHexLineData getLine (uint8_t Type, uint16_t Addr, ArrayRef< uint8_t > Data)
static Expected< IHexRecord > parse (StringRef Line)
static uint8_t getChecksum (StringRef S)
Public Attributes
uint16_t Addr
uint16_t Type
StringRef HexData
Detailed Description
Definition at line 196 of file ELFObject.h.
Member Enumeration Documentation
Type
enum llvm::objcopy::elf::IHexRecord::Type
Enumerator
Data
EndOfFile
SegmentAddr
StartAddr80x86
ExtendedAddr
StartAddr
InvalidType
Definition at line 230 of file ELFObject.h.
Member Function Documentation
getChecksum()
uint8_t IHexRecord::getChecksum (StringRef S) static
Definition at line 206 of file ELFObject.cpp.
References assert(), llvm::StringRef::drop_front(), llvm::StringRef::empty(), llvm::StringRef::size(), and llvm::StringRef::take_front().
getLength()
static size_t llvm::objcopy::elf::IHexRecord::getLength (size_t DataSize) inline static
Definition at line 206 of file ELFObject.h.
Referenced by getLineLength().
getLine()
IHexLineData IHexRecord::getLine (uint8_t Type, uint16_t Addr, ArrayRef< uint8_t > Data) static
Definition at line 216 of file ELFObject.cpp.
References Addr, assert(), llvm::Data, toHexStr(), and X.
Referenced by llvm::objcopy::elf::IHexSectionWriter::writeData().
getLineLength()
static size_t llvm::objcopy::elf::IHexRecord::getLineLength (size_t DataSize) inline static
Definition at line 212 of file ELFObject.h.
References getLength().
Referenced by llvm::objcopy::elf::IHexWriter::finalize(), and llvm::objcopy::elf::IHexSectionWriterBase::writeData().
parse()
Expected< IHexRecord > IHexRecord::parse (StringRef Line) static
Definition at line 298 of file ELFObject.cpp.
References Addr, assert(), checkChars(), checkRecord(), llvm::createStringError(), llvm::StringRef::drop_front(), E, llvm::StringRef::empty(), HexData, llvm::invalid_argument, llvm::StringRef::size(), and llvm::StringRef::substr().
Member Data Documentation
Addr
uint16_t llvm::objcopy::elf::IHexRecord::Addr
Definition at line 198 of file ELFObject.h.
Referenced by parse().
HexData
StringRef llvm::objcopy::elf::IHexRecord::HexData
Definition at line 202 of file ELFObject.h.
Referenced by parse().
Type
uint16_t llvm::objcopy::elf::IHexRecord::Type
Definition at line 200 of file ELFObject.h.
The documentation for this struct was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp