LLVM: llvm::objcopy::wasm::Object Struct Reference
llvm::objcopy::wasm::Object Struct Reference
#include "ObjCopy/wasm/WasmObject.h"
Public Member Functions
void addSectionWithOwnedContents (Section NewSection, std::unique_ptr< MemoryBuffer > &&Content)
void removeSections (function_ref< bool(const Section &)> ToRemove)
Public Attributes
llvm::wasm::WasmObjectHeader Header
std::vector< Section > Sections
Detailed Description
Definition at line 30 of file WasmObject.h.
Member Function Documentation
addSectionWithOwnedContents()
void llvm::objcopy::wasm::Object::addSectionWithOwnedContents (Section NewSection, std::unique_ptr< MemoryBuffer > && Content)
Definition at line 21 of file WasmObject.cpp.
References Content, and Sections.
Referenced by llvm::objcopy::wasm::handleArgs().
removeSections()
void llvm::objcopy::wasm::Object::removeSections (function_ref< bool(const Section &)> ToRemove)
Definition at line 27 of file WasmObject.cpp.
References llvm::erase_if(), Sections, and ToRemove.
Referenced by llvm::objcopy::wasm::removeSections().
Member Data Documentation
Header
llvm::wasm::WasmObjectHeader llvm::objcopy::wasm::Object::Header
Definition at line 31 of file WasmObject.h.
Referenced by llvm::objcopy::wasm::Writer::write().
Sections
std::vector<Section> llvm::objcopy::wasm::Object::Sections
Definition at line 33 of file WasmObject.h.
Referenced by addSectionWithOwnedContents(), llvm::objcopy::wasm::dumpSectionToFile(), removeSections(), and llvm::objcopy::wasm::Writer::write().
The documentation for this struct was generated from the following files:
lib/ObjCopy/wasm/WasmObject.h
lib/ObjCopy/wasm/WasmObject.cpp