LLVM: llvm::yaml::SIArgument Struct Reference
llvm::yaml::SIArgument Struct Reference
#include "Target/AMDGPU/SIMachineFunctionInfo.h"
Public Member Functions
SIArgument ()
SIArgument (const SIArgument &Other)
SIArgument & operator= (const SIArgument &Other)
~SIArgument ()
Static Public Member Functions
static SIArgument createArgument (bool IsReg)
Public Attributes
bool IsRegister
union {
StringValue RegisterName
unsigned StackOffset
};
Optional< unsigned > Mask
Detailed Description
Definition at line 113 of file SIMachineFunctionInfo.h.
Constructor & Destructor Documentation
SIArgument() [1/2]
llvm::yaml::SIArgument::SIArgument () inline
Definition at line 122 of file SIMachineFunctionInfo.h.
Referenced by createArgument().
SIArgument() [2/2]
llvm::yaml::SIArgument::SIArgument (const SIArgument & Other) inline
Definition at line 123 of file SIMachineFunctionInfo.h.
References IsRegister, Mask, llvm::Other, RegisterName, and llvm::StackOffset::StackOffset().
~SIArgument()
llvm::yaml::SIArgument::~SIArgument () inline
Definition at line 142 of file SIMachineFunctionInfo.h.
References IsRegister, and RegisterName.
Member Function Documentation
createArgument()
static SIArgument llvm::yaml::SIArgument::createArgument (bool IsReg) inline static
Definition at line 148 of file SIMachineFunctionInfo.h.
References SIArgument().
Referenced by convertArgumentInfo(), and llvm::yaml::MappingTraits< SIArgument >::mapping().
operator=()
SIArgument & llvm::yaml::SIArgument::operator= (const SIArgument & Other) inline
Definition at line 132 of file SIMachineFunctionInfo.h.
References IsRegister, Mask, llvm::Other, RegisterName, and llvm::StackOffset::StackOffset().
Member Data Documentation
[union]
union { ... } llvm::yaml::SIArgument
IsRegister
bool llvm::yaml::SIArgument::IsRegister
Definition at line 114 of file SIMachineFunctionInfo.h.
Referenced by operator=(), SIArgument(), and ~SIArgument().
Mask
Optional<unsigned> llvm::yaml::SIArgument::Mask
Definition at line 119 of file SIMachineFunctionInfo.h.
Referenced by convertArgumentInfo(), operator=(), and SIArgument().
RegisterName
StringValue llvm::yaml::SIArgument::RegisterName
Definition at line 116 of file SIMachineFunctionInfo.h.
Referenced by convertArgumentInfo(), operator=(), SIArgument(), and ~SIArgument().
StackOffset
unsigned llvm::yaml::SIArgument::StackOffset
Definition at line 117 of file SIMachineFunctionInfo.h.
Referenced by convertArgumentInfo().
The documentation for this struct was generated from the following file:
lib/Target/AMDGPU/SIMachineFunctionInfo.h