LLVM: llvm::PatternMatch::FNeg_match< Op_t > Struct Template Reference
llvm::PatternMatch::FNeg_match< Op_t > Struct Template Reference
#include "llvm/IR/PatternMatch.h"
Public Member Functions
FNeg_match (const Op_t &Op)
template<typename OpTy >
bool match (OpTy *V)
Public Attributes
Op_t X
Detailed Description
template<typename Op_t>
struct llvm::PatternMatch::FNeg_match< Op_t >
Definition at line 1002 of file PatternMatch.h.
Constructor & Destructor Documentation
FNeg_match()
template<typename Op_t > llvm::PatternMatch::FNeg_match< Op_t >::FNeg_match (const Op_t & Op) inline
Definition at line 1005 of file PatternMatch.h.
Member Function Documentation
match()
template<typename Op_t > template<typename OpTy > bool llvm::PatternMatch::FNeg_match< Op_t >::match (OpTy * V) inline
Definition at line 1006 of file PatternMatch.h.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::PatternMatch::FNeg_match< Op_t >::match(), and llvm::PatternMatch::FNeg_match< Op_t >::X.
Referenced by llvm::PatternMatch::FNeg_match< Op_t >::match().
Member Data Documentation
X
template<typename Op_t > Op_t llvm::PatternMatch::FNeg_match< Op_t >::X
Definition at line 1003 of file PatternMatch.h.
Referenced by llvm::PatternMatch::FNeg_match< Op_t >::match().
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h