LLVM: llvm::VERegisterInfo Struct Reference
llvm::VERegisterInfo Struct Reference
#include "Target/VE/VERegisterInfo.h"
Public Member Functions
VERegisterInfo ()
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Code Generation virtual methods...
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID CC) const override
const uint32_t * getNoPreservedMask () const override
BitVector getReservedRegs (const MachineFunction &MF) const override
bool isConstantPhysReg (MCRegister PhysReg) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Register getFrameRegister (const MachineFunction &MF) const override
Detailed Description
Definition at line 22 of file VERegisterInfo.h.
Constructor & Destructor Documentation
VERegisterInfo()
VERegisterInfo::VERegisterInfo ()
Definition at line 36 of file VERegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
void VERegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 489 of file VERegisterInfo.cpp.
References assert(), DL, llvm::VESubtarget::getInstrInfo(), llvm::VESubtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), MI, Offset, offsetToDisp(), TII, and TRI.
getCalleeSavedRegs()
const MCPhysReg * VERegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Code Generation virtual methods...
Definition at line 39 of file VERegisterInfo.cpp.
References llvm::CallingConv::Fast, llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), and llvm::CallingConv::PreserveAll.
getCallPreservedMask()
const uint32_t * VERegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const override
Definition at line 50 of file VERegisterInfo.cpp.
References llvm::CallingConv::Fast, and llvm::CallingConv::PreserveAll.
Referenced by llvm::VETargetLowering::lowerToTLSGeneralDynamicModel().
getFrameRegister()
Register VERegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 514 of file VERegisterInfo.cpp.
getNoPreservedMask()
const uint32_t * VERegisterInfo::getNoPreservedMask () const override
Definition at line 62 of file VERegisterInfo.cpp.
Referenced by llvm::VETargetLowering::emitSjLjDispatchBlock().
getPointerRegClass()
const TargetRegisterClass * VERegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind) const override
Definition at line 110 of file VERegisterInfo.cpp.
getReservedRegs()
BitVector VERegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 66 of file VERegisterInfo.cpp.
References llvm::BitVector::set().
isConstantPhysReg()
bool VERegisterInfo::isConstantPhysReg (MCRegister PhysReg) const override
Definition at line 99 of file VERegisterInfo.cpp.
The documentation for this struct was generated from the following files:
lib/Target/VE/VERegisterInfo.h
lib/Target/VE/VERegisterInfo.cpp