LLVM: llvm::wholeprogramdevirt::AccumBitVector Struct Reference
llvm::wholeprogramdevirt::AccumBitVector Struct Reference
#include "llvm/Transforms/IPO/WholeProgramDevirt.h"
Public Member Functions
std::pair< uint8_t *, uint8_t * > getPtrToData (uint64_t Pos, uint8_t Size)
void setLE (uint64_t Pos, uint64_t Val, uint8_t Size)
void setBE (uint64_t Pos, uint64_t Val, uint8_t Size)
void setBit (uint64_t Pos, bool b)
Public Attributes
std::vector< uint8_t > Bytes
std::vector< uint8_t > BytesUsed
Detailed Description
Definition at line 40 of file WholeProgramDevirt.h.
Member Function Documentation
getPtrToData()
std::pair< uint8_t *, uint8_t * > llvm::wholeprogramdevirt::AccumBitVector::getPtrToData (uint64_t Pos, uint8_t Size) inline
Definition at line 46 of file WholeProgramDevirt.h.
References Bytes, BytesUsed, and Size.
Referenced by setBE(), setBit(), and setLE().
setBE()
void llvm::wholeprogramdevirt::AccumBitVector::setBE (uint64_t Pos, uint64_t Val, uint8_t Size) inline
Definition at line 68 of file WholeProgramDevirt.h.
References assert(), getPtrToData(), I, and Size.
Referenced by llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBytes(), and llvm::wholeprogramdevirt::VirtualCallTarget::setBeforeBytes().
setBit()
void llvm::wholeprogramdevirt::AccumBitVector::setBit (uint64_t Pos, bool b) inline
Definition at line 79 of file WholeProgramDevirt.h.
References assert(), and getPtrToData().
Referenced by llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBit(), and llvm::wholeprogramdevirt::VirtualCallTarget::setBeforeBit().
setLE()
void llvm::wholeprogramdevirt::AccumBitVector::setLE (uint64_t Pos, uint64_t Val, uint8_t Size) inline
Definition at line 56 of file WholeProgramDevirt.h.
References assert(), getPtrToData(), I, and Size.
Referenced by llvm::wholeprogramdevirt::VirtualCallTarget::setAfterBytes(), and llvm::wholeprogramdevirt::VirtualCallTarget::setBeforeBytes().
Member Data Documentation
Bytes
std::vector<uint8_t> llvm::wholeprogramdevirt::AccumBitVector::Bytes
Definition at line 41 of file WholeProgramDevirt.h.
Referenced by llvm::wholeprogramdevirt::VirtualCallTarget::allocatedAfterBytes(), llvm::wholeprogramdevirt::VirtualCallTarget::allocatedBeforeBytes(), and getPtrToData().
BytesUsed
std::vector<uint8_t> llvm::wholeprogramdevirt::AccumBitVector::BytesUsed
Definition at line 44 of file WholeProgramDevirt.h.
Referenced by getPtrToData().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/WholeProgramDevirt.h