LLVM: lib/LTO/SummaryBasedOptimizations.cpp File Reference
SummaryBasedOptimizations.cpp File Reference
#include "llvm/LTO/SummaryBasedOptimizations.h"
#include "llvm/Analysis/SyntheticCountsUtils.h"
#include "llvm/IR/ModuleSummaryIndex.h"
#include "llvm/Support/CommandLine.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
static void initializeCounts (ModuleSummaryIndex &Index)
Variables
static cl::opt< bool > ThinLTOSynthesizeEntryCounts ("thinlto-synthesize-entry-counts", cl::init(false), cl::Hidden, cl::desc("Synthesize entry counts based on the summary"))
cl::opt< int > llvm::InitialSyntheticCount
Function Documentation
initializeCounts()
static void initializeCounts (ModuleSummaryIndex & Index) static
Definition at line 30 of file SummaryBasedOptimizations.cpp.
References llvm::CallingConv::C, F, and llvm::InitialSyntheticCount.
Referenced by llvm::computeSyntheticCounts(), and llvm::SyntheticCountsPropagation::run().
Variable Documentation
ThinLTOSynthesizeEntryCounts
cl::opt< bool > ThinLTOSynthesizeEntryCounts("thinlto-synthesize-entry-counts", cl::init(false), cl::Hidden, cl::desc("Synthesize entry counts based on the summary")) ("thinlto-synthesize-entry-counts" , cl::init(false) , cl::Hidden , cl::desc("Synthesize entry counts based on the summary")) static
Referenced by llvm::computeSyntheticCounts().