LLVM: lib/DebugInfo/CodeView/TypeDumpVisitor.cpp File Reference
TypeDumpVisitor.cpp File Reference
#include "llvm/DebugInfo/CodeView/TypeDumpVisitor.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/DebugInfo/CodeView/CVTypeVisitor.h"
#include "llvm/DebugInfo/CodeView/RecordSerialization.h"
#include "llvm/DebugInfo/CodeView/TypeCollection.h"
#include "llvm/DebugInfo/CodeView/TypeIndex.h"
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/ScopedPrinter.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/DebugInfo/CodeView/CodeViewTypes.def"
Macros
#define CV_TYPE(enum, val) {#enum, enum},
#define ENUM_ENTRY(enum_class, enum) { #enum, std::underlying_type < enum_class > ::type(enum_class::enum) }
#define TYPE_RECORD(ename, value, name)
Functions
static StringRef getLeafTypeName (TypeLeafKind LT)
Variables
static const EnumEntry< TypeLeafKind > LeafTypeNames []
static const EnumEntry< uint16_t > ClassOptionNames []
static const EnumEntry< uint8_t > MemberAccessNames []
static const EnumEntry< uint16_t > MethodOptionNames []
static const EnumEntry< uint16_t > MemberKindNames []
static const EnumEntry< uint8_t > PtrKindNames []
static const EnumEntry< uint8_t > PtrModeNames []
static const EnumEntry< uint16_t > PtrMemberRepNames []
static const EnumEntry< uint16_t > TypeModifierNames []
static const EnumEntry< uint8_t > CallingConventions []
static const EnumEntry< uint8_t > FunctionOptionEnum []
static const EnumEntry< uint16_t > LabelTypeEnum []
Macro Definition Documentation
CV_TYPE
#define CV_TYPE (enum, val) {#enum, enum},
ENUM_ENTRY
#define ENUM_ENTRY (enum_class, enum) { #enum, std::underlying_type < enum_class > ::type(enum_class::enum) }
Definition at line 29 of file TypeDumpVisitor.cpp.
TYPE_RECORD
#define TYPE_RECORD (ename, value, name)
Value:
  case ename:                                                                  \
    return #name;
Function Documentation
getLeafTypeName()
static StringRef getLeafTypeName (TypeLeafKind LT) static
Definition at line 150 of file TypeDumpVisitor.cpp.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberBegin(), llvm::codeview::TypeRecordMapping::visitMemberBegin(), llvm::codeview::TypeDumpVisitor::visitTypeBegin(), and llvm::codeview::TypeRecordMapping::visitTypeBegin().
Variable Documentation
CallingConventions
const EnumEntry<uint8_t> CallingConventions[] static
Initial value:
= {
    ENUM_ENTRY(CallingConvention, NearC),
    ENUM_ENTRY(CallingConvention, FarC),
    ENUM_ENTRY(CallingConvention, NearPascal),
    ENUM_ENTRY(CallingConvention, FarPascal),
    ENUM_ENTRY(CallingConvention, NearFast),
    ENUM_ENTRY(CallingConvention, FarFast),
    ENUM_ENTRY(CallingConvention, NearStdCall),
    ENUM_ENTRY(CallingConvention, FarStdCall),
    ENUM_ENTRY(CallingConvention, NearSysCall),
    ENUM_ENTRY(CallingConvention, FarSysCall),
    ENUM_ENTRY(CallingConvention, ThisCall),
    ENUM_ENTRY(CallingConvention, MipsCall),
    ENUM_ENTRY(CallingConvention, Generic),
    ENUM_ENTRY(CallingConvention, AlphaCall),
    ENUM_ENTRY(CallingConvention, PpcCall),
    ENUM_ENTRY(CallingConvention, SHCall),
    ENUM_ENTRY(CallingConvention, ArmCall),
    ENUM_ENTRY(CallingConvention, AM33Call),
    ENUM_ENTRY(CallingConvention, TriCall),
    ENUM_ENTRY(CallingConvention, SH5Call),
    ENUM_ENTRY(CallingConvention, M32RCall),
    ENUM_ENTRY(CallingConvention, ClrCall),
    ENUM_ENTRY(CallingConvention, Inline),
    ENUM_ENTRY(CallingConvention, NearVector),
}
Definition at line 111 of file TypeDumpVisitor.cpp.
ClassOptionNames
const EnumEntry<uint16_t> ClassOptionNames[] static
Initial value:
= {
    ENUM_ENTRY(ClassOptions, Packed),
    ENUM_ENTRY(ClassOptions, HasConstructorOrDestructor),
    ENUM_ENTRY(ClassOptions, HasOverloadedOperator),
    ENUM_ENTRY(ClassOptions, Nested),
    ENUM_ENTRY(ClassOptions, ContainsNestedClass),
    ENUM_ENTRY(ClassOptions, HasOverloadedAssignmentOperator),
    ENUM_ENTRY(ClassOptions, HasConversionOperator),
    ENUM_ENTRY(ClassOptions, ForwardReference),
    ENUM_ENTRY(ClassOptions, Scoped),
    ENUM_ENTRY(ClassOptions, HasUniqueName),
    ENUM_ENTRY(ClassOptions, Sealed),
    ENUM_ENTRY(ClassOptions, Intrinsic),
}
Definition at line 32 of file TypeDumpVisitor.cpp.
FunctionOptionEnum
const EnumEntry<uint8_t> FunctionOptionEnum[] static
Initial value:
= {
    ENUM_ENTRY(FunctionOptions, CxxReturnUdt),
    ENUM_ENTRY(FunctionOptions, Constructor),
    ENUM_ENTRY(FunctionOptions, ConstructorWithVirtualBases),
}
Definition at line 138 of file TypeDumpVisitor.cpp.
LabelTypeEnum
const EnumEntry<uint16_t> LabelTypeEnum[] static
Initial value:
= {
    ENUM_ENTRY(LabelType, Near), ENUM_ENTRY(LabelType, Far),
}
Definition at line 144 of file TypeDumpVisitor.cpp.
LeafTypeNames
const EnumEntry<TypeLeafKind> LeafTypeNames[] static
Initial value:
= {
#define CV_TYPE(enum, val)
}
Definition at line 24 of file TypeDumpVisitor.cpp.
Referenced by llvm::codeview::TypeDumpVisitor::visitMemberBegin(), llvm::codeview::TypeRecordMapping::visitMemberBegin(), llvm::codeview::TypeRecordMapping::visitTypeBegin(), llvm::codeview::TypeDumpVisitor::visitTypeBegin(), and llvm::codeview::TypeDumpVisitor::visitUnknownType().
MemberAccessNames
const EnumEntry<uint8_t> MemberAccessNames[] static
Initial value:
= {
    ENUM_ENTRY(MemberAccess, None), ENUM_ENTRY(MemberAccess, Private),
    ENUM_ENTRY(MemberAccess, Protected), ENUM_ENTRY(MemberAccess, Public),
}
Definition at line 47 of file TypeDumpVisitor.cpp.
MemberKindNames
const EnumEntry<uint16_t> MemberKindNames[] static
Initial value:
= {
    ENUM_ENTRY(MethodKind, Vanilla),
    ENUM_ENTRY(MethodKind, Virtual),
    ENUM_ENTRY(MethodKind, Static),
    ENUM_ENTRY(MethodKind, Friend),
    ENUM_ENTRY(MethodKind, IntroducingVirtual),
    ENUM_ENTRY(MethodKind, PureVirtual),
    ENUM_ENTRY(MethodKind, PureIntroducingVirtual),
}
Definition at line 60 of file TypeDumpVisitor.cpp.
MethodOptionNames
const EnumEntry<uint16_t> MethodOptionNames[] static
Initial value:
= {
    ENUM_ENTRY(MethodOptions, Pseudo),
    ENUM_ENTRY(MethodOptions, NoInherit),
    ENUM_ENTRY(MethodOptions, NoConstruct),
    ENUM_ENTRY(MethodOptions, CompilerGenerated),
    ENUM_ENTRY(MethodOptions, Sealed),
}
Definition at line 52 of file TypeDumpVisitor.cpp.
PtrKindNames
const EnumEntry<uint8_t> PtrKindNames[] static
Initial value:
= {
    ENUM_ENTRY(PointerKind, Near16),
    ENUM_ENTRY(PointerKind, Far16),
    ENUM_ENTRY(PointerKind, Huge16),
    ENUM_ENTRY(PointerKind, BasedOnSegment),
    ENUM_ENTRY(PointerKind, BasedOnValue),
    ENUM_ENTRY(PointerKind, BasedOnSegmentValue),
    ENUM_ENTRY(PointerKind, BasedOnAddress),
    ENUM_ENTRY(PointerKind, BasedOnSegmentAddress),
    ENUM_ENTRY(PointerKind, BasedOnType),
    ENUM_ENTRY(PointerKind, BasedOnSelf),
    ENUM_ENTRY(PointerKind, Near32),
    ENUM_ENTRY(PointerKind, Far32),
    ENUM_ENTRY(PointerKind, Near64),
}
Definition at line 70 of file TypeDumpVisitor.cpp.
PtrMemberRepNames
const EnumEntry<uint16_t> PtrMemberRepNames[] static
Initial value:
= {
    ENUM_ENTRY(PointerToMemberRepresentation, Unknown),
    ENUM_ENTRY(PointerToMemberRepresentation, SingleInheritanceData),
    ENUM_ENTRY(PointerToMemberRepresentation, MultipleInheritanceData),
    ENUM_ENTRY(PointerToMemberRepresentation, VirtualInheritanceData),
    ENUM_ENTRY(PointerToMemberRepresentation, GeneralData),
    ENUM_ENTRY(PointerToMemberRepresentation, SingleInheritanceFunction),
    ENUM_ENTRY(PointerToMemberRepresentation, MultipleInheritanceFunction),
    ENUM_ENTRY(PointerToMemberRepresentation, VirtualInheritanceFunction),
    ENUM_ENTRY(PointerToMemberRepresentation, GeneralFunction),
}
Definition at line 94 of file TypeDumpVisitor.cpp.
PtrModeNames
const EnumEntry<uint8_t> PtrModeNames[] static
Initial value:
= {
    ENUM_ENTRY(PointerMode, Pointer),
    ENUM_ENTRY(PointerMode, LValueReference),
    ENUM_ENTRY(PointerMode, PointerToDataMember),
    ENUM_ENTRY(PointerMode, PointerToMemberFunction),
    ENUM_ENTRY(PointerMode, RValueReference),
}
Definition at line 86 of file TypeDumpVisitor.cpp.
TypeModifierNames
const EnumEntry<uint16_t> TypeModifierNames[] static
Initial value:
= {
    ENUM_ENTRY(ModifierOptions, Const), ENUM_ENTRY(ModifierOptions, Volatile),
    ENUM_ENTRY(ModifierOptions, Unaligned),
}
Definition at line 106 of file TypeDumpVisitor.cpp.