LLVM: lib/DebugInfo/CodeView/TypeRecordMapping.cpp File Reference
TypeRecordMapping.cpp File Reference
#include "llvm/DebugInfo/CodeView/TypeRecordMapping.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/DebugInfo/CodeView/CVTypeVisitor.h"
#include "llvm/DebugInfo/CodeView/CodeViewRecordIO.h"
#include "llvm/DebugInfo/CodeView/EnumTables.h"
#include "llvm/DebugInfo/CodeView/RecordSerialization.h"
#include "llvm/DebugInfo/CodeView/TypeIndex.h"
#include "llvm/DebugInfo/CodeView/TypeRecord.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MD5.h"
#include "llvm/Support/ScopedPrinter.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>
#include "llvm/DebugInfo/CodeView/CodeViewTypes.def"
Macros
#define error(X)
#define CV_TYPE(enum, val) {#enum, enum},
#define TYPE_RECORD(ename, value, name)
Functions
static void computeHashString (StringRef Name, SmallString< 32 > &StringifiedHash)
static Error mapNameAndUniqueName (CodeViewRecordIO &IO, StringRef &Name, StringRef &UniqueName, bool HasUniqueName)
Macro Definition Documentation
CV_TYPE
#define CV_TYPE (enum, val) {#enum, enum},
error
#define error (X)
Value:
  do {                                                                         \
    if (auto EC = X)                                                           \
      return EC;                                                               \
  } while (false)
Definition at line 38 of file TypeRecordMapping.cpp.
Referenced by mapNameAndUniqueName().
TYPE_RECORD
#define TYPE_RECORD (ename, value, name)
Value:
  case ename:                                                                  \
    return #name;
Function Documentation
computeHashString()
static void computeHashString (StringRef Name, SmallString< 32 > & StringifiedHash) static
Definition at line 171 of file TypeRecordMapping.cpp.
References llvm::MD5::final(), Name, llvm::MD5::stringifyResult(), and llvm::MD5::update().
Referenced by mapNameAndUniqueName().
mapNameAndUniqueName()
static Error mapNameAndUniqueName (CodeViewRecordIO & IO, StringRef & Name, StringRef & UniqueName, bool HasUniqueName) static
Definition at line 180 of file TypeRecordMapping.cpp.
References assert(), computeHashString(), error, llvm::codeview::HasUniqueName, llvm::codeview::CodeViewRecordIO::isWriting(), llvm::codeview::CodeViewRecordIO::mapStringZ(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), N, Name, llvm::StringRef::size(), llvm::Twine::str(), llvm::Error::success(), and llvm::StringRef::take_front().