LLVM: lib/Support/VersionTuple.cpp File Reference
VersionTuple.cpp File Reference
#include "llvm/Support/VersionTuple.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
Functions
static bool parseInt (StringRef &input, unsigned &value)
Function Documentation
parseInt()
static bool parseInt (StringRef & input, unsigned & value) static
Definition at line 41 of file VersionTuple.cpp.
References assert(), llvm::StringRef::empty(), llvm::StringRef::substr(), and value.
Referenced by llvm::VersionTuple::tryParse().