LLVM: lib/Target/AArch64/AArch64SelectionDAGInfo.cpp File Reference
AArch64SelectionDAGInfo.cpp File Reference
#include "AArch64TargetMachine.h"
Macros
#define DEBUG_TYPE "aarch64-selectiondag-info"
Functions
static SDValue EmitUnrolledSetTag (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Ptr, uint64_t ObjSize, const MachineMemOperand *BaseMemOperand, bool ZeroData)
Variables
static cl::opt< bool > LowerToSMERoutines ("aarch64-lower-to-sme-routines", cl::Hidden, cl::desc("Enable AArch64 SME memory operations " "to lower to librt functions"), cl::init(true))
static const int kSetTagLoopThreshold = 176
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-selectiondag-info"
Definition at line 16 of file AArch64SelectionDAGInfo.cpp.
Function Documentation
EmitUnrolledSetTag()
static SDValue EmitUnrolledSetTag (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Ptr, uint64_t ObjSize, const MachineMemOperand * BaseMemOperand, bool ZeroData) static
Definition at line 199 of file AArch64SelectionDAGInfo.cpp.
References llvm::cast(), llvm::ISD::FrameIndex, llvm::TypeSize::getFixed(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMemBasePlusOffset(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::SelectionDAG::getVTList(), Ptr, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::AArch64ISD::ST2G, llvm::AArch64ISD::STG, llvm::AArch64ISD::STZ2G, llvm::AArch64ISD::STZG, and llvm::ISD::TokenFactor.
Referenced by llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag().
Variable Documentation
kSetTagLoopThreshold
const int kSetTagLoopThreshold = 176 static
Definition at line 197 of file AArch64SelectionDAGInfo.cpp.
Referenced by llvm::AArch64SelectionDAGInfo::EmitTargetCodeForSetTag().
LowerToSMERoutines
cl::opt< bool > LowerToSMERoutines("aarch64-lower-to-sme-routines", cl::Hidden, cl::desc("Enable AArch64 SME memory operations " "to lower to librt functions"), cl::init(true)) ("aarch64-lower-to-sme-routines" , cl::Hidden , cl::desc("Enable AArch64 SME memory operations " "to lower to librt functions") , cl::init(true)) static
Referenced by llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemmove(), and llvm::AArch64SelectionDAGInfo::EmitTargetCodeForMemset().