LLVM: lib/Target/AMDGPU/MCTargetDesc/AMDGPUMCCodeEmitter.cpp File Reference
AMDGPUMCCodeEmitter.cpp File Reference
The AMDGPU code emitter produces machine code that can be executed directly on the GPU device.
#include "MCTargetDesc/AMDGPUFixupKinds.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIDefines.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/ADT/APInt.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/EndianStream.h"
#include "llvm/TargetParser/SubtargetFeature.h"
#include <optional>
#include "AMDGPUGenMCCodeEmitter.inc"
Functions
template<typename IntTy >
static uint32_t getIntInlineImmEncoding (IntTy Imm)
static uint32_t getLit16Encoding (uint16_t Val, const MCSubtargetInfo &STI)
static uint32_t getLitBF16Encoding (uint16_t Val)
static uint32_t getLit32Encoding (uint32_t Val, const MCSubtargetInfo &STI)
static uint32_t getLit16IntEncoding (uint32_t Val, const MCSubtargetInfo &STI)
static uint32_t getLit64Encoding (uint64_t Val, const MCSubtargetInfo &STI)
static bool isVCMPX64 (const MCInstrDesc &Desc)
static bool needsPCRel (const MCExpr *Expr)
Detailed Description
The AMDGPU code emitter produces machine code that can be executed directly on the GPU device.
Definition in file AMDGPUMCCodeEmitter.cpp.
Function Documentation
getIntInlineImmEncoding()
template<typename IntTy > static uint32_t getIntInlineImmEncoding (IntTy Imm) static
Definition at line 109 of file AMDGPUMCCodeEmitter.cpp.
Referenced by getLit16Encoding(), getLit32Encoding(), getLit64Encoding(), and getLitBF16Encoding().
getLit16Encoding()
static uint32_t getLit16Encoding (uint16_t Val, const MCSubtargetInfo & STI) static
Definition at line 119 of file AMDGPUMCCodeEmitter.cpp.
References getIntInlineImmEncoding(), and llvm::MCSubtargetInfo::hasFeature().
getLit16IntEncoding()
static uint32_t getLit16IntEncoding (uint32_t Val, const MCSubtargetInfo & STI) static
Definition at line 212 of file AMDGPUMCCodeEmitter.cpp.
References getLit32Encoding().
getLit32Encoding()
static uint32_t getLit32Encoding (uint32_t Val, const MCSubtargetInfo & STI) static
Definition at line 176 of file AMDGPUMCCodeEmitter.cpp.
References llvm::bit_cast(), getIntInlineImmEncoding(), and llvm::MCSubtargetInfo::hasFeature().
Referenced by getLit16IntEncoding().
getLit64Encoding()
static uint32_t getLit64Encoding (uint64_t Val, const MCSubtargetInfo & STI) static
Definition at line 216 of file AMDGPUMCCodeEmitter.cpp.
References llvm::bit_cast(), getIntInlineImmEncoding(), and llvm::MCSubtargetInfo::hasFeature().
getLitBF16Encoding()
static uint32_t getLitBF16Encoding (uint16_t Val) static
Definition at line 155 of file AMDGPUMCCodeEmitter.cpp.
References getIntInlineImmEncoding().
isVCMPX64()
static bool isVCMPX64 (const MCInstrDesc & Desc) static
Definition at line 357 of file AMDGPUMCCodeEmitter.cpp.
References llvm::SIInstrFlags::VOP3.
needsPCRel()
static bool needsPCRel (const MCExpr * Expr) static
Definition at line 561 of file AMDGPUMCCodeEmitter.cpp.
References llvm::MCExpr::Binary, llvm::cast(), llvm::MCExpr::Constant, llvm::MCExpr::getKind(), llvm_unreachable, needsPCRel(), llvm::MCBinaryExpr::Sub, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, llvm::MCExpr::Unary, llvm::MCSymbolRefExpr::VK_AMDGPU_ABS32_HI, and llvm::MCSymbolRefExpr::VK_AMDGPU_ABS32_LO.
Referenced by needsPCRel().