LLVM: lib/Target/AMDGPU/AMDGPULibCalls.cpp File Reference
AMDGPULibCalls.cpp File Reference
This file does AMD library function optimizations.
#include "AMDGPU.h"
#include "AMDGPULibFunc.h"
#include "GCNSubtarget.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/AttributeMask.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/InitializePasses.h"
#include <cmath>
Classes
class llvm::AMDGPULibCalls
struct TableEntry
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "amdgpu-simplifylib"
#define MATH_PI numbers::pi
#define MATH_E numbers::e
#define MATH_SQRT2 numbers::sqrt2
#define MATH_SQRT1_2 numbers::inv_sqrt2
Typedefs
using TableRef = ArrayRef<TableEntry>
Functions
template<typename IRB >
static CallInst * CreateCallEx (IRB &B, FunctionCallee Callee, Value *Arg, const Twine &Name="")
template<typename IRB >
static CallInst * CreateCallEx2 (IRB &B, FunctionCallee Callee, Value *Arg1, Value *Arg2, const Twine &Name="")
static FunctionType * getPownType (FunctionType *FT)
static bool HasNative (AMDGPULibFunc::EFuncId id)
static TableRef getOptTable (AMDGPULibFunc::EFuncId id)
static int getVecSize (const AMDGPULibFunc &FInfo)
static AMDGPULibFunc::EType getArgType (const AMDGPULibFunc &FInfo)
static bool isKnownIntegral (const Value *V, const DataLayout &DL, FastMathFlags FMF)
static double llvm::log2 (double V)
Variables
static cl::opt< bool > EnablePreLink ("amdgpu-prelink", cl::desc("Enable pre-link mode optimizations"), cl::init(false), cl::Hidden)
static cl::list< std::string > UseNative ("amdgpu-use-native", cl::desc("Comma separated list of functions to replace with native, or all"), cl::CommaSeparated, cl::ValueOptional, cl::Hidden)
static const TableEntry tbl_acos []
static const TableEntry tbl_acosh []
static const TableEntry tbl_acospi []
static const TableEntry tbl_asin []
static const TableEntry tbl_asinh []
static const TableEntry tbl_asinpi []
static const TableEntry tbl_atan []
static const TableEntry tbl_atanh []
static const TableEntry tbl_atanpi []
static const TableEntry tbl_cbrt []
static const TableEntry tbl_cos []
static const TableEntry tbl_cosh []
static const TableEntry tbl_cospi []
static const TableEntry tbl_erfc []
static const TableEntry tbl_erf []
static const TableEntry tbl_exp []
static const TableEntry tbl_exp2 []
static const TableEntry tbl_exp10 []
static const TableEntry tbl_expm1 []
static const TableEntry tbl_log []
static const TableEntry tbl_log2 []
static const TableEntry tbl_log10 []
static const TableEntry tbl_rsqrt []
static const TableEntry tbl_sin []
static const TableEntry tbl_sinh []
static const TableEntry tbl_sinpi []
static const TableEntry tbl_sqrt []
static const TableEntry tbl_tan []
static const TableEntry tbl_tanh []
static const TableEntry tbl_tanpi []
static const TableEntry tbl_tgamma []
Detailed Description
This file does AMD library function optimizations.
Definition in file AMDGPULibCalls.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-simplifylib"
Definition at line 30 of file AMDGPULibCalls.cpp.
MATH_E
#define MATH_E numbers::e
Definition at line 46 of file AMDGPULibCalls.cpp.
MATH_PI
#define MATH_PI numbers::pi
Definition at line 45 of file AMDGPULibCalls.cpp.
MATH_SQRT1_2
#define MATH_SQRT1_2 numbers::inv_sqrt2
Definition at line 48 of file AMDGPULibCalls.cpp.
MATH_SQRT2
#define MATH_SQRT2 numbers::sqrt2
Definition at line 47 of file AMDGPULibCalls.cpp.
Typedef Documentation
TableRef
using TableRef = ArrayRef<TableEntry>
Definition at line 355 of file AMDGPULibCalls.cpp.
Function Documentation
CreateCallEx()
template<typename IRB > static CallInst * CreateCallEx (IRB & B, FunctionCallee Callee, Value * Arg, const Twine & Name = "") static
Definition at line 153 of file AMDGPULibCalls.cpp.
References B, llvm::dyn_cast(), F, and Name.
CreateCallEx2()
template<typename IRB > static CallInst * CreateCallEx2 (IRB & B, FunctionCallee Callee, Value * Arg1, Value * Arg2, const Twine & Name = "") static
Definition at line 162 of file AMDGPULibCalls.cpp.
References B, llvm::dyn_cast(), F, and Name.
getArgType()
static AMDGPULibFunc::EType getArgType (const AMDGPULibFunc & FInfo) inline static
Definition at line 405 of file AMDGPULibCalls.cpp.
References llvm::AMDGPULibFuncBase::Param::ArgType, and llvm::AMDGPULibFunc::getLeads().
Referenced by llvm::AMDGPULibCalls::useNative().
getOptTable()
static TableRef getOptTable (AMDGPULibFunc::EFuncId id) static
Definition at line 357 of file AMDGPULibCalls.cpp.
References tbl_acos, tbl_acosh, tbl_acospi, tbl_asin, tbl_asinh, tbl_asinpi, tbl_atan, tbl_atanh, tbl_atanpi, tbl_cbrt, tbl_cos, tbl_cosh, tbl_cospi, tbl_erf, tbl_erfc, tbl_exp, tbl_exp10, tbl_exp2, tbl_expm1, tbl_log, tbl_log10, tbl_log2, tbl_rsqrt, tbl_sin, tbl_sinh, tbl_sinpi, tbl_sqrt, tbl_tan, tbl_tanh, tbl_tanpi, and tbl_tgamma.
getPownType()
static FunctionType * getPownType (FunctionType * FT) static
Definition at line 170 of file AMDGPULibCalls.cpp.
References llvm::dyn_cast().
Referenced by llvm::AMDGPULibCalls::fold().
getVecSize()
static int getVecSize (const AMDGPULibFunc & FInfo) inline static
Definition at line 401 of file AMDGPULibCalls.cpp.
References llvm::AMDGPULibFunc::getLeads(), and llvm::AMDGPULibFuncBase::Param::VectorSize.
HasNative()
static bool HasNative (AMDGPULibFunc::EFuncId id) static
Definition at line 332 of file AMDGPULibCalls.cpp.
Referenced by llvm::AMDGPULibCalls::useNative().
isKnownIntegral()
static bool isKnownIntegral (const Value * V, const DataLayout & DL, FastMathFlags FMF) static
Definition at line 579 of file AMDGPULibCalls.cpp.
References llvm::cast(), DL, llvm::dyn_cast(), llvm::Constant::getAggregateElement(), llvm::CallBase::getIntrinsicID(), llvm::ConstantFP::getValue(), I, llvm::isa(), llvm::APFloat::isInteger(), llvm::isKnownNeverInfinity(), llvm::isKnownNeverInfOrNaN(), llvm::FastMathFlags::noInfs(), and llvm::FastMathFlags::noNaNs().
Referenced by llvm::AMDGPULibCalls::fold().
Variable Documentation
EnablePreLink
cl::opt< bool > EnablePreLink("amdgpu-prelink", cl::desc("Enable pre-link mode optimizations"), cl::init(false), cl::Hidden) ("amdgpu-prelink" , cl::desc("Enable pre-link mode optimizations") , cl::init(false) , cl::Hidden) static
tbl_acos
const TableEntry tbl_acos[] static
Initial value:
= {
  {MATH_PI / 2.0, 0.0},
  {MATH_PI / 2.0, -0.0},
  {0.0, 1.0},
  {MATH_PI, -1.0}
}
Definition at line 188 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_acosh
const TableEntry tbl_acosh[] static
Initial value:
= {
  {0.0, 1.0}
}
Definition at line 194 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_acospi
const TableEntry tbl_acospi[] static
Initial value:
= {
  {0.5, 0.0},
  {0.5, -0.0},
  {0.0, 1.0},
  {1.0, -1.0}
}
Definition at line 197 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_asin
const TableEntry tbl_asin[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0},
  {MATH_PI / 2.0, 1.0},
  {-MATH_PI / 2.0, -1.0}
}
Definition at line 203 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_asinh
const TableEntry tbl_asinh[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0}
}
Definition at line 209 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_asinpi
const TableEntry tbl_asinpi[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0},
  {0.5, 1.0},
  {-0.5, -1.0}
}
Definition at line 213 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_atan
const TableEntry tbl_atan[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0},
  {MATH_PI / 4.0, 1.0},
  {-MATH_PI / 4.0, -1.0}
}
Definition at line 219 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_atanh
const TableEntry tbl_atanh[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0}
}
Definition at line 225 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_atanpi
const TableEntry tbl_atanpi[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0},
  {0.25, 1.0},
  {-0.25, -1.0}
}
Definition at line 229 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_cbrt
const TableEntry tbl_cbrt[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0},
  {1.0, 1.0},
  {-1.0, -1.0},
}
Definition at line 235 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_cos
const TableEntry tbl_cos[] static
Initial value:
= {
  {1.0, 0.0},
  {1.0, -0.0}
}
Definition at line 241 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_cosh
const TableEntry tbl_cosh[] static
Initial value:
= {
  {1.0, 0.0},
  {1.0, -0.0}
}
Definition at line 245 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_cospi
const TableEntry tbl_cospi[] static
Initial value:
= {
  {1.0, 0.0},
  {1.0, -0.0}
}
Definition at line 249 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_erf
const TableEntry tbl_erf[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0}
}
Definition at line 257 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_erfc
const TableEntry tbl_erfc[] static
Initial value:
= {
  {1.0, 0.0},
  {1.0, -0.0}
}
Definition at line 253 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_exp
const TableEntry tbl_exp[] static
Initial value:
= {
  {1.0, 0.0},
  {1.0, -0.0},
  {MATH_E, 1.0}
}
Definition at line 261 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_exp10
const TableEntry tbl_exp10[] static
Initial value:
= {
  {1.0, 0.0},
  {1.0, -0.0},
  {10.0, 1.0}
}
Definition at line 271 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_exp2
const TableEntry tbl_exp2[] static
Initial value:
= {
  {1.0, 0.0},
  {1.0, -0.0},
  {2.0, 1.0}
}
Definition at line 266 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_expm1
const TableEntry tbl_expm1[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0}
}
Definition at line 276 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_log
const TableEntry tbl_log[] static
Initial value:
= {
  {0.0, 1.0},
  {1.0, MATH_E}
}
Definition at line 280 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_log10
const TableEntry tbl_log10[] static
Initial value:
= {
  {0.0, 1.0},
  {1.0, 10.0}
}
Definition at line 288 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_log2
const TableEntry tbl_log2[] static
Initial value:
= {
  {0.0, 1.0},
  {1.0, 2.0}
}
Definition at line 284 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_rsqrt
const TableEntry tbl_rsqrt[] static
Initial value:
= {
  {1.0, 1.0},
  {MATH_SQRT1_2, 2.0}
}
Definition at line 292 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_sin
const TableEntry tbl_sin[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0}
}
Definition at line 296 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_sinh
const TableEntry tbl_sinh[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0}
}
Definition at line 300 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_sinpi
const TableEntry tbl_sinpi[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0}
}
Definition at line 304 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_sqrt
const TableEntry tbl_sqrt[] static
Initial value:
= {
  {0.0, 0.0},
  {1.0, 1.0},
  {MATH_SQRT2, 2.0}
}
Definition at line 308 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_tan
const TableEntry tbl_tan[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0}
}
Definition at line 313 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_tanh
const TableEntry tbl_tanh[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0}
}
Definition at line 317 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_tanpi
const TableEntry tbl_tanpi[] static
Initial value:
= {
  {0.0, 0.0},
  {-0.0, -0.0}
}
Definition at line 321 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
tbl_tgamma
const TableEntry tbl_tgamma[] static
Initial value:
= {
  {1.0, 1.0},
  {1.0, 2.0},
  {2.0, 3.0},
  {6.0, 4.0}
}
Definition at line 325 of file AMDGPULibCalls.cpp.
Referenced by getOptTable().
UseNative
cl::list< std::string > UseNative("amdgpu-use-native", cl::desc("Comma separated list of functions to replace with native, or all"), cl::CommaSeparated, cl::ValueOptional, cl::Hidden) ("amdgpu-use-native" , cl::desc("Comma separated list of functions to replace with native, or all") , cl::CommaSeparated , cl::ValueOptional , cl::Hidden) static
Referenced by llvm::AMDGPULibCalls::initNativeFuncs(), and llvm::AMDGPUUseNativeCallsPass::run().