LLVM: lib/Target/AMDGPU/Utils/AMDGPUDelayedMCExpr.cpp File Reference
AMDGPUDelayedMCExpr.cpp File Reference
#include "AMDGPUDelayedMCExpr.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCValue.h"
Functions
static msgpack::DocNode getNode (msgpack::DocNode DN, msgpack::Type Type, MCValue Val)
Function Documentation
getNode()
static msgpack::DocNode getNode (msgpack::DocNode DN, msgpack::Type Type, MCValue Val) static
Definition at line 15 of file AMDGPUDelayedMCExpr.cpp.
References llvm::MCValue::getConstant(), llvm::msgpack::DocNode::getDocument(), llvm::msgpack::Document::getEmptyNode(), and llvm::msgpack::Document::getNode().
Referenced by llvm::DelayedMCExprs::assignDocNode(), CheckForLiveRegDef(), CheckForLiveRegDef(), llvm::PPCTargetLowering::CollectTargetIntrinsicOperands(), combineSetCCMOVMSK(), combineX86ShufflesRecursively(), llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), llvm::msgpack::MapDocNode::find(), findConsecutiveLoad(), llvm::PPC::get_VSPLTI_elt(), llvm::BlockFrequencyInfoImpl< BlockT >::getBlockFreq(), llvm::BlockFrequencyInfoImpl< BlockT >::getBlockProfileCount(), llvm::BlockFrequencyInfoImpl< BlockT >::getFloatingBlockFreq(), llvm::LazyCallGraph::Edge::getFunction(), llvm::BlockFrequencyInfoImpl< BlockT >::isIrrLoopHeader(), isShuffleFoldableLoad(), llvm::SelectionDAG::Legalize(), llvm::TargetLowering::LowerCallTo(), GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::nodes_begin(), llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::nodes_begin(), GraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::nodes_end(), llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::nodes_end(), llvm::BlockFrequencyInfoImpl< BlockT >::print(), llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates(), llvm::SelectionDAGISel::ReplaceUses(), llvm::DelayedMCExprs::resolveDelayedExpressions(), llvm::RISCVDAGToDAGISel::Select(), llvm::HvxSelector::selectShuffle(), llvm::BlockFrequencyInfoImpl< BlockT >::setBlockFreq(), llvm::VETargetLowering::splitPackedLoadStore(), and willShiftRightEliminate().