LLVM: lib/Target/AMDGPU/AMDGPULibFunc.cpp File Reference
AMDGPULibFunc.cpp File Reference
#include "AMDGPULibFunc.h"
#include "AMDGPU.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ModRef.h"
#include "llvm/Support/raw_ostream.h"
Functions
static int parseVecSize (StringRef &mangledName)
static AMDGPULibFunc::ENamePrefix parseNamePrefix (StringRef &mangledName)
static const char * getItaniumTypeName (AMDGPULibFunc::EType T)
static Type * getIntrinsicParamType (LLVMContext &C, const AMDGPULibFunc::Param &P, bool useAddrSpace)
Variables
static cl::opt< bool > EnableOCLManglingMismatchWA ("amdgpu-enable-ocl-mangling-mismatch-workaround", cl::init(true), cl::ReallyHidden, cl::desc("Enable the workaround for OCL name mangling mismatch."))
Function Documentation
getIntrinsicParamType()
static Type * getIntrinsicParamType (LLVMContext & C, const AMDGPULibFunc::Param & P, bool useAddrSpace) static
Definition at line 932 of file AMDGPULibFunc.cpp.
References llvm::CallingConv::C, llvm::StructType::create(), llvm::FixedVectorType::get(), llvm::Type::getPointerTo(), llvm_unreachable, P, and T.
Referenced by llvm::AMDGPUMangledLibFunc::getFunctionType().
getItaniumTypeName()
static const char * getItaniumTypeName (AMDGPULibFunc::EType T) static
Definition at line 741 of file AMDGPULibFunc.cpp.
References llvm_unreachable.
parseNamePrefix()
static AMDGPULibFunc::ENamePrefix parseNamePrefix (StringRef & mangledName) static
Definition at line 554 of file AMDGPULibFunc.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), P, and llvm::StringRef::split().
Referenced by llvm::AMDGPUMangledLibFunc::parseFuncName().
parseVecSize()
static int parseVecSize (StringRef & mangledName) static
Definition at line 543 of file AMDGPULibFunc.cpp.
Variable Documentation
EnableOCLManglingMismatchWA
cl::opt< bool > EnableOCLManglingMismatchWA("amdgpu-enable-ocl-mangling-mismatch-workaround", cl::init(true), cl::ReallyHidden, cl::desc("Enable the workaround for OCL name mangling mismatch.")) ("amdgpu-enable-ocl-mangling-mismatch-workaround" , cl::init(true) , cl::ReallyHidden , cl::desc("Enable the workaround for OCL name mangling mismatch.")) static