LLVM: lib/Target/AMDGPU/AMDGPUCombinerHelper.cpp File Reference
AMDGPUCombinerHelper.cpp File Reference
#include "AMDGPUCombinerHelper.h"
#include "GCNSubtarget.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "llvm/CodeGen/GlobalISel/GenericMachineInstrs.h"
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/Target/TargetMachine.h"
Functions
static LLVM_READNONE bool fnegFoldsIntoMI (const MachineInstr &MI)
static LLVM_READONLY bool opMustUseVOP3Encoding (const MachineInstr &MI, const MachineRegisterInfo &MRI)
returns true if the operation will definitely need to use a 64-bit encoding, and thus will use a VOP3 encoding regardless of the source modifiers.
static LLVM_READONLY bool hasSourceMods (const MachineInstr &MI)
static bool allUsesHaveSourceMods (MachineInstr &MI, MachineRegisterInfo &MRI, unsigned CostThreshold=4)
static bool mayIgnoreSignedZero (MachineInstr &MI)
static bool isInv2Pi (const APFloat &APF)
static bool isConstantCostlierToNegate (MachineInstr &MI, Register Reg, MachineRegisterInfo &MRI)
static unsigned inverseMinMax (unsigned Opc)
static bool isFPExtFromF16OrConst (const MachineRegisterInfo &MRI, Register Reg)
Function Documentation
allUsesHaveSourceMods()
static bool allUsesHaveSourceMods (MachineInstr & MI, MachineRegisterInfo & MRI, unsigned CostThreshold = 4) static
Definition at line 117 of file AMDGPUCombinerHelper.cpp.
References CostThreshold, hasSourceMods(), MI, MRI, and opMustUseVOP3Encoding().
Referenced by AMDGPUCombinerHelper::matchFoldableFneg().
fnegFoldsIntoMI()
static LLVM_READNONE bool fnegFoldsIntoMI (const MachineInstr & MI) static
Definition at line 21 of file AMDGPUCombinerHelper.cpp.
References llvm::cast(), and MI.
Referenced by AMDGPUCombinerHelper::matchFoldableFneg().
hasSourceMods()
static LLVM_READONLY bool hasSourceMods (const MachineInstr & MI) static
Definition at line 78 of file AMDGPUCombinerHelper.cpp.
References llvm::cast(), and MI.
Referenced by allUsesHaveSourceMods(), and llvm::AMDGPUTargetLowering::allUsesHaveSourceMods().
inverseMinMax()
static unsigned inverseMinMax (unsigned Opc) static
Definition at line 169 of file AMDGPUCombinerHelper.cpp.
References llvm_unreachable.
Referenced by AMDGPUCombinerHelper::applyFoldableFneg(), and llvm::AMDGPUTargetLowering::performFNegCombine().
isConstantCostlierToNegate()
static bool isConstantCostlierToNegate (MachineInstr & MI, Register Reg, MachineRegisterInfo & MRI) static
Definition at line 155 of file AMDGPUCombinerHelper.cpp.
References isInv2Pi(), llvm::MIPatternMatch::m_GFCstOrSplat(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
Referenced by AMDGPUCombinerHelper::matchFoldableFneg().
isFPExtFromF16OrConst()
static bool isFPExtFromF16OrConst (const MachineRegisterInfo & MRI, Register Reg) static
Definition at line 400 of file AMDGPUCombinerHelper.cpp.
References llvm::APFloat::convert(), MRI, and llvm::LLT::scalar().
Referenced by AMDGPUCombinerHelper::matchExpandPromotedF16FMed3().
isInv2Pi()
static bool isInv2Pi (const APFloat & APF) static
Definition at line 143 of file AMDGPUCombinerHelper.cpp.
References llvm::APFloat::bitwiseIsEqual().
Referenced by llvm::AMDGPUTargetLowering::getConstantNegateCost(), and isConstantCostlierToNegate().
mayIgnoreSignedZero()
static bool mayIgnoreSignedZero (MachineInstr & MI) static
Definition at line 138 of file AMDGPUCombinerHelper.cpp.
References MI, and Options.
Referenced by AMDGPUCombinerHelper::matchFoldableFneg().
opMustUseVOP3Encoding()
static LLVM_READONLY bool opMustUseVOP3Encoding (const MachineInstr & MI, const MachineRegisterInfo & MRI) static
returns true if the operation will definitely need to use a 64-bit encoding, and thus will use a VOP3 encoding regardless of the source modifiers.
Definition at line 70 of file AMDGPUCombinerHelper.cpp.
References llvm::isa(), MI, and MRI.
Referenced by allUsesHaveSourceMods(), and llvm::AMDGPUTargetLowering::allUsesHaveSourceMods().