LLVM: lib/Analysis/GuardUtils.cpp File Reference
GuardUtils.cpp File Reference
#include "llvm/Analysis/GuardUtils.h"
#include "llvm/IR/PatternMatch.h"
Functions
template<typename CallbackType >
static void parseCondition (Value *Condition, CallbackType RecordCheckOrWidenableCond)
Function Documentation
parseCondition()
template<typename CallbackType > static void parseCondition (Value * Condition, CallbackType RecordCheckOrWidenableCond) static
Definition at line 118 of file GuardUtils.cpp.
References Check, llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallPtrSetImpl< PtrType >::insert(), LHS, llvm::PatternMatch::m_And(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and RHS.
Referenced by llvm::extractWidenableCondition(), and llvm::parseWidenableGuard().