LLVM: lib/Transforms/IPO/Annotation2Metadata.cpp File Reference
Annotation2Metadata.cpp File Reference
#include "llvm/Transforms/IPO/Annotation2Metadata.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Module.h"
#include "llvm/Transforms/IPO.h"
Macros
#define DEBUG_TYPE "annotation2metadata"
Functions
static bool convertAnnotation2Metadata (Module &M)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "annotation2metadata"
Definition at line 24 of file Annotation2Metadata.cpp.
Function Documentation
convertAnnotation2Metadata()
static bool convertAnnotation2Metadata (Module & M) static
Definition at line 26 of file Annotation2Metadata.cpp.
References llvm::OptimizationRemarkEmitter::allowExtraAnalysis(), llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), I, and instructions.
Referenced by llvm::Annotation2MetadataPass::run().