LLVM: lib/Object/ArchiveWriter.cpp File Reference
ArchiveWriter.cpp File Reference
#include "llvm/Object/ArchiveWriter.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/Magic.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/Object/Archive.h"
#include "llvm/Object/COFF.h"
#include "llvm/Object/COFFImportFile.h"
#include "llvm/Object/Error.h"
#include "llvm/Object/IRObjectFile.h"
#include "llvm/Object/MachO.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Object/SymbolicFile.h"
#include "llvm/Object/XCOFFObjectFile.h"
#include "llvm/Support/Alignment.h"
#include "llvm/Support/EndianStream.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SmallVectorMemoryBuffer.h"
#include "llvm/Support/raw_ostream.h"
#include <cerrno>
#include <map>
#include <unistd.h>
Classes
struct SymMap
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
template<typename T >
static void printWithSpacePadding (raw_ostream &OS, T Data, unsigned Size)
static bool isDarwin (object::Archive::Kind Kind)
static bool isAIXBigArchive (object::Archive::Kind Kind)
static bool isCOFFArchive (object::Archive::Kind Kind)
static bool isBSDLike (object::Archive::Kind Kind)
template<class T >
static void print (raw_ostream &Out, object::Archive::Kind Kind, T Val)
template<class T >
static void printLE (raw_ostream &Out, T Val)
static void printRestOfMemberHeader (raw_ostream &Out, const sys::TimePoint< std::chrono::seconds > &ModTime, unsigned UID, unsigned GID, unsigned Perms, uint64_t Size)
static void printGNUSmallMemberHeader (raw_ostream &Out, StringRef Name, const sys::TimePoint< std::chrono::seconds > &ModTime, unsigned UID, unsigned GID, unsigned Perms, uint64_t Size)
static void printBSDMemberHeader (raw_ostream &Out, uint64_t Pos, StringRef Name, const sys::TimePoint< std::chrono::seconds > &ModTime, unsigned UID, unsigned GID, unsigned Perms, uint64_t Size)
static void printBigArchiveMemberHeader (raw_ostream &Out, StringRef Name, const sys::TimePoint< std::chrono::seconds > &ModTime, unsigned UID, unsigned GID, unsigned Perms, uint64_t Size, uint64_t PrevOffset, uint64_t NextOffset)
static bool useStringTable (bool Thin, StringRef Name)
static bool is64BitKind (object::Archive::Kind Kind)
static void printMemberHeader (raw_ostream &Out, uint64_t Pos, raw_ostream &StringTable, StringMap< uint64_t > &MemberNames, object::Archive::Kind Kind, bool Thin, const NewArchiveMember &M, sys::TimePoint< std::chrono::seconds > ModTime, uint64_t Size)
static MemberData computeStringTable (StringRef Names)
static sys::TimePoint< std::chrono::seconds > now (bool Deterministic)
static bool isArchiveSymbol (const object::BasicSymbolRef &S)
static void printNBits (raw_ostream &Out, object::Archive::Kind Kind, uint64_t Val)
static uint64_t computeSymbolTableSize (object::Archive::Kind Kind, uint64_t NumSyms, uint64_t OffsetSize, uint64_t StringTableSize, uint32_t *Padding=nullptr)
static uint64_t computeSymbolMapSize (uint64_t NumObj, SymMap &SymMap, uint32_t *Padding=nullptr)
static uint64_t computeECSymbolsSize (SymMap &SymMap, uint32_t *Padding=nullptr)
static void writeSymbolTableHeader (raw_ostream &Out, object::Archive::Kind Kind, bool Deterministic, uint64_t Size, uint64_t PrevMemberOffset=0, uint64_t NextMemberOffset=0)
static uint64_t computeHeadersSize (object::Archive::Kind Kind, uint64_t NumMembers, uint64_t StringMemberSize, uint64_t NumSyms, uint64_t SymNamesSize, SymMap *SymMap)
static Expected< std::unique_ptr< SymbolicFile > > getSymbolicFile (MemoryBufferRef Buf, LLVMContext &Context, object::Archive::Kind Kind, function_ref< void(Error)> Warn)
static bool is64BitSymbolicFile (const SymbolicFile *SymObj)
template<typename AuxiliaryHeader >
uint16_t getAuxMaxAlignment (uint16_t AuxHeaderSize, AuxiliaryHeader *AuxHeader, uint16_t Log2OfMaxAlign)
static uint32_t getMemberAlignment (SymbolicFile *SymObj)
static void writeSymbolTable (raw_ostream &Out, object::Archive::Kind Kind, bool Deterministic, ArrayRef< MemberData > Members, StringRef StringTable, uint64_t MembersOffset, unsigned NumSyms, uint64_t PrevMemberOffset=0, uint64_t NextMemberOffset=0, bool Is64Bit=false)
static void writeSymbolMap (raw_ostream &Out, object::Archive::Kind Kind, bool Deterministic, ArrayRef< MemberData > Members, SymMap &SymMap, uint64_t MembersOffset)
static void writeECSymbols (raw_ostream &Out, object::Archive::Kind Kind, bool Deterministic, ArrayRef< MemberData > Members, SymMap &SymMap)
static bool isECObject (object::SymbolicFile &Obj)
static bool isAnyArm64COFF (object::SymbolicFile &Obj)
bool isImportDescriptor (StringRef Name)
static Expected< std::vector< unsigned > > getSymbols (SymbolicFile *Obj, uint16_t Index, raw_ostream &SymNames, SymMap *SymMap)
static Expected< std::vector< MemberData > > computeMemberData (raw_ostream &StringTable, raw_ostream &SymNames, object::Archive::Kind Kind, bool Thin, bool Deterministic, SymtabWritingMode NeedSymbols, SymMap *SymMap, LLVMContext &Context, ArrayRef< NewArchiveMember > NewMembers, std::optional< bool > IsEC, function_ref< void(Error)> Warn)
static ErrorOr< SmallString< 128 > > llvm::canonicalizePath (StringRef P)
Expected< std::string > llvm::computeArchiveRelativePath (StringRef From, StringRef To)
Error llvm::writeArchiveToStream (raw_ostream &Out, ArrayRef< NewArchiveMember > NewMembers, SymtabWritingMode WriteSymtab, object::Archive::Kind Kind, bool Deterministic, bool Thin, std::optional< bool > IsEC=std::nullopt, function_ref< void(Error)> Warn=warnToStderr)
void llvm::warnToStderr (Error Err)
Error llvm::writeArchive (StringRef ArcName, ArrayRef< NewArchiveMember > NewMembers, SymtabWritingMode WriteSymtab, object::Archive::Kind Kind, bool Deterministic, bool Thin, std::unique_ptr< MemoryBuffer > OldArchiveBuf=nullptr, std::optional< bool > IsEC=std::nullopt, function_ref< void(Error)> Warn=warnToStderr)
Expected< std::unique_ptr< MemoryBuffer > > llvm::writeArchiveToBuffer (ArrayRef< NewArchiveMember > NewMembers, SymtabWritingMode WriteSymtab, object::Archive::Kind Kind, bool Deterministic, bool Thin, function_ref< void(Error)> Warn=warnToStderr)
Variables
static const uint32_t Log2OfAIXPageSize = 12
static const uint32_t MinBigArchiveMemDataAlign = 2
Function Documentation
computeECSymbolsSize()
static uint64_t computeECSymbolsSize (SymMap & SymMap, uint32_t * Padding = nullptr) static
Definition at line 428 of file ArchiveWriter.cpp.
References Align, SymMap::ECMap, llvm::offsetToAlignment(), and Size.
Referenced by computeHeadersSize(), and writeECSymbols().
computeHeadersSize()
static uint64_t computeHeadersSize (object::Archive::Kind Kind, uint64_t NumMembers, uint64_t StringMemberSize, uint64_t NumSyms, uint64_t SymNamesSize, SymMap * SymMap) static
Definition at line 459 of file ArchiveWriter.cpp.
References computeECSymbolsSize(), computeSymbolMapSize(), computeSymbolTableSize(), SymMap::ECMap, is64BitKind(), Size, llvm::SmallVectorBase< Size_T >::size(), and writeSymbolTableHeader().
Referenced by llvm::writeArchiveToStream().
computeMemberData()
static Expected< std::vector< MemberData > > computeMemberData (raw_ostream & StringTable, raw_ostream & SymNames, object::Archive::Kind Kind, bool Thin, bool Deterministic, SymtabWritingMode NeedSymbols, SymMap * SymMap, LLVMContext & Context, ArrayRef< NewArchiveMember > NewMembers, std::optional< bool > IsEC, function_ref< void(Error)> Warn) static
Definition at line 779 of file ArchiveWriter.cpp.
References llvm::alignTo(), llvm::alignToPowerOf2(), llvm::ArrayRef< T >::begin(), llvm::createFileError(), llvm::Data, llvm::raw_ostream::flush(), llvm::get(), llvm::MemoryBufferRef::getBuffer(), llvm::MemoryBufferRef::getBufferSize(), getMemberAlignment(), getSymbolicFile(), getSymbols(), isAIXBigArchive(), isAnyArm64COFF(), isCOFFArchive(), isDarwin(), isECObject(), llvm::make_error(), llvm::object::Archive::MaxMemberSize, llvm::NoSymtab, llvm::offsetToAlignment(), llvm::object::parse_failed, printBigArchiveMemberHeader(), printMemberHeader(), Size, llvm::ArrayRef< T >::size(), llvm::Expected< T >::takeError(), llvm::raw_ostream::tell(), llvm::sys::toTimePoint(), and SymMap::UseECMap.
Referenced by llvm::writeArchiveToStream().
computeStringTable()
static MemberData computeStringTable (StringRef Names) static
Definition at line 342 of file ArchiveWriter.cpp.
References Align, llvm::raw_ostream::flush(), llvm::offsetToAlignment(), printWithSpacePadding(), Size, and llvm::StringRef::size().
Referenced by llvm::writeArchiveToStream().
computeSymbolMapSize()
static uint64_t computeSymbolMapSize (uint64_t NumObj, SymMap & SymMap, uint32_t * Padding = nullptr) static
Definition at line 413 of file ArchiveWriter.cpp.
References Align, SymMap::Map, llvm::offsetToAlignment(), and Size.
Referenced by computeHeadersSize(), and writeSymbolMap().
computeSymbolTableSize()
static uint64_t computeSymbolTableSize (object::Archive::Kind Kind, uint64_t NumSyms, uint64_t OffsetSize, uint64_t StringTableSize, uint32_t * Padding = nullptr) static
Definition at line 384 of file ArchiveWriter.cpp.
References Align, assert(), isAIXBigArchive(), isBSDLike(), llvm::offsetToAlignment(), and Size.
Referenced by computeHeadersSize(), and writeSymbolTable().
getAuxMaxAlignment()
template<typename AuxiliaryHeader > uint16_t getAuxMaxAlignment (uint16_t AuxHeaderSize, AuxiliaryHeader * AuxHeader, uint16_t Log2OfMaxAlign)
Definition at line 547 of file ArchiveWriter.cpp.
References Log2OfAIXPageSize, MinBigArchiveMemDataAlign, and offsetof.
Referenced by getMemberAlignment().
getMemberAlignment()
static uint32_t getMemberAlignment (SymbolicFile * SymObj) static
Definition at line 580 of file ArchiveWriter.cpp.
References llvm::object::XCOFFFileHeader32::AuxHeaderSize, llvm::object::XCOFFFileHeader64::AuxHeaderSize, llvm::object::XCOFFObjectFile::auxiliaryHeader32(), llvm::object::XCOFFObjectFile::auxiliaryHeader64(), llvm::dyn_cast_or_null(), llvm::object::XCOFFObjectFile::fileHeader32(), llvm::object::XCOFFObjectFile::fileHeader64(), getAuxMaxAlignment(), llvm::object::XCOFFObjectFile::is64Bit(), Log2OfAIXPageSize, and MinBigArchiveMemDataAlign.
Referenced by computeMemberData().
getSymbolicFile()
static Expected< std::unique_ptr< SymbolicFile > > getSymbolicFile (MemoryBufferRef Buf, LLVMContext & Context, object::Archive::Kind Kind, function_ref< void(Error)> Warn) static
Definition at line 485 of file ArchiveWriter.cpp.
References llvm::file_magic::bitcode, llvm::object::SymbolicFile::createSymbolicFile(), llvm::MemoryBufferRef::getBuffer(), llvm::identify_magic(), llvm::object::SymbolicFile::isSymbolicFile(), llvm::object::Archive::K_AIXBIG, llvm::object::Archive::K_BSD, llvm::object::Archive::K_COFF, llvm::object::Archive::K_DARWIN, llvm::object::Archive::K_DARWIN64, llvm::object::Archive::K_GNU, and llvm::object::Archive::K_GNU64.
Referenced by computeMemberData().
getSymbols()
static Expected< std::vector< unsigned > > getSymbols (SymbolicFile * Obj, uint16_t Index, raw_ostream & SymNames, SymMap * SymMap) static
Definition at line 736 of file ArchiveWriter.cpp.
References SymMap::ECMap, isArchiveSymbol(), isECObject(), isImportDescriptor(), SymMap::Map, Name, llvm::object::SymbolicFile::symbols(), llvm::raw_ostream::tell(), and SymMap::UseECMap.
Referenced by computeMemberData(), and llvm::writeArchiveToStream().
is64BitKind()
static bool is64BitKind (object::Archive::Kind Kind) static
Definition at line 284 of file ArchiveWriter.cpp.
References llvm::object::Archive::K_AIXBIG, llvm::object::Archive::K_BSD, llvm::object::Archive::K_COFF, llvm::object::Archive::K_DARWIN, llvm::object::Archive::K_DARWIN64, llvm::object::Archive::K_GNU, llvm::object::Archive::K_GNU64, and llvm_unreachable.
Referenced by computeHeadersSize(), printNBits(), llvm::writeArchiveToStream(), writeSymbolTable(), and writeSymbolTableHeader().
is64BitSymbolicFile()
static bool is64BitSymbolicFile (const SymbolicFile * SymObj) static
Definition at line 533 of file ArchiveWriter.cpp.
References llvm::object::SymbolicFile::is64Bit().
Referenced by llvm::writeArchiveToStream(), and writeSymbolTable().
isAIXBigArchive()
static bool isAIXBigArchive (object::Archive::Kind Kind) static
Definition at line 181 of file ArchiveWriter.cpp.
References llvm::object::Archive::K_AIXBIG.
Referenced by computeMemberData(), computeSymbolTableSize(), llvm::writeArchiveToStream(), writeSymbolTable(), and writeSymbolTableHeader().
isAnyArm64COFF()
static bool isAnyArm64COFF (object::SymbolicFile & Obj) static
Definition at line 710 of file ArchiveWriter.cpp.
References llvm::Triple::aarch64, llvm::cast(), llvm::getBitcodeTargetTriple(), llvm::object::Binary::getMemoryBufferRef(), llvm::COFF::isAnyArm64(), llvm::object::Binary::isCOFF(), llvm::object::Binary::isCOFFImportFile(), llvm::object::Binary::isIR(), and T.
Referenced by computeMemberData().
isArchiveSymbol()
static bool isArchiveSymbol (const object::BasicSymbolRef & S) static
Definition at line 362 of file ArchiveWriter.cpp.
References llvm::object::BasicSymbolRef::getFlags(), llvm::report_fatal_error(), llvm::object::BasicSymbolRef::SF_FormatSpecific, llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_Undefined, and llvm::Expected< T >::takeError().
Referenced by getSymbols().
isBSDLike()
static bool isBSDLike (object::Archive::Kind Kind) static
Definition at line 189 of file ArchiveWriter.cpp.
References llvm::object::Archive::K_AIXBIG, llvm::object::Archive::K_BSD, llvm::object::Archive::K_COFF, llvm::object::Archive::K_DARWIN, llvm::object::Archive::K_DARWIN64, llvm::object::Archive::K_GNU, llvm::object::Archive::K_GNU64, and llvm_unreachable.
Referenced by computeSymbolTableSize(), print(), printMemberHeader(), llvm::writeArchiveToStream(), writeSymbolTable(), and writeSymbolTableHeader().
isCOFFArchive()
static bool isCOFFArchive (object::Archive::Kind Kind) static
Definition at line 185 of file ArchiveWriter.cpp.
References llvm::object::Archive::K_COFF.
Referenced by computeMemberData(), printMemberHeader(), llvm::writeArchiveToStream(), and writeSymbolTable().
isDarwin()
static bool isDarwin (object::Archive::Kind Kind) static
Definition at line 176 of file ArchiveWriter.cpp.
References llvm::object::Archive::K_DARWIN, and llvm::object::Archive::K_DARWIN64.
Referenced by computeMemberData(), and writeSymbolTable().
isECObject()
static bool isECObject (object::SymbolicFile & Obj) static
Definition at line 689 of file ArchiveWriter.cpp.
References llvm::cast(), llvm::getBitcodeTargetTriple(), llvm::object::Binary::getMemoryBufferRef(), llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::object::Binary::isCOFF(), llvm::object::Binary::isCOFFImportFile(), llvm::object::Binary::isIR(), T, and llvm::Triple::x86_64.
Referenced by computeMemberData(), and getSymbols().
isImportDescriptor()
bool isImportDescriptor (StringRef Name)
Definition at line 729 of file ArchiveWriter.cpp.
References llvm::object::ImportDescriptorPrefix, Name, llvm::object::NullImportDescriptorSymbolName, llvm::object::NullThunkDataPrefix, and llvm::object::NullThunkDataSuffix.
Referenced by getSymbols().
now()
static sys::TimePoint< std::chrono::seconds > now (bool Deterministic) static
Definition at line 354 of file ArchiveWriter.cpp.
Referenced by llvm::TimeRecord::getCurrentTime(), writeECSymbols(), and writeSymbolTableHeader().
print()
template<class T > static void print (raw_ostream & Out, object::Archive::Kind Kind, T Val) static
Definition at line 205 of file ArchiveWriter.cpp.
References llvm::big, isBSDLike(), llvm::little, and llvm::support::endian::write().
Referenced by gen-inline-oz-test-model::build_mock_model(), gen-regalloc-eviction-test-model::build_mock_model(), gen-regalloc-priority-test-model::build_mock_model(), llvm::Comdat::dump(), llvm::DbgMarker::dump(), llvm::DbgRecord::dump(), llvm::Metadata::dump(), llvm::Module::dump(), llvm::ModuleSummaryIndex::dump(), llvm::NamedMDNode::dump(), llvm::Type::dump(), llvm::Value::dump(), INITIALIZE_PASS(), gen-inline-oz-test-model::main(), log_reader::main(), log_reader::pretty_print_tensor_value(), llvm::DbgLabelRecord::print(), llvm::DbgMarker::print(), llvm::DbgVariableRecord::print(), llvm::Value::print(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), and interactive_host::run_interactive().
printBigArchiveMemberHeader()
static void printBigArchiveMemberHeader (raw_ostream & Out, StringRef Name, const sys::TimePoint< std::chrono::seconds > & ModTime, unsigned UID, unsigned GID, unsigned Perms, uint64_t Size, uint64_t PrevOffset, uint64_t NextOffset) static
Definition at line 256 of file ArchiveWriter.cpp.
References llvm::format(), Name, printWithSpacePadding(), Size, llvm::sys::toTimeT(), and llvm::raw_ostream::write().
Referenced by computeMemberData(), llvm::writeArchiveToStream(), and writeSymbolTableHeader().
printBSDMemberHeader()
static void printBSDMemberHeader (raw_ostream & Out, uint64_t Pos, StringRef Name, const sys::TimePoint< std::chrono::seconds > & ModTime, unsigned UID, unsigned GID, unsigned Perms, uint64_t Size) static
Definition at line 240 of file ArchiveWriter.cpp.
References Align, Name, llvm::offsetToAlignment(), printRestOfMemberHeader(), printWithSpacePadding(), Size, and llvm::raw_ostream::write().
Referenced by printMemberHeader(), and writeSymbolTableHeader().
printGNUSmallMemberHeader()
static void printGNUSmallMemberHeader (raw_ostream & Out, StringRef Name, const sys::TimePoint< std::chrono::seconds > & ModTime, unsigned UID, unsigned GID, unsigned Perms, uint64_t Size) static
Definition at line 231 of file ArchiveWriter.cpp.
References Name, printRestOfMemberHeader(), printWithSpacePadding(), and Size.
Referenced by printMemberHeader(), writeECSymbols(), and writeSymbolTableHeader().
printLE()
template<class T > static void printLE (raw_ostream & Out, T Val) static
Definition at line 211 of file ArchiveWriter.cpp.
References llvm::little, and llvm::support::endian::write().
Referenced by writeECSymbols(), and writeSymbolMap().
printMemberHeader()
static void printMemberHeader (raw_ostream & Out, uint64_t Pos, raw_ostream & StringTable, StringMap< uint64_t > & MemberNames, object::Archive::Kind Kind, bool Thin, const NewArchiveMember & M, sys::TimePoint< std::chrono::seconds > ModTime, uint64_t Size) static
Definition at line 300 of file ArchiveWriter.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::insert(), isBSDLike(), isCOFFArchive(), printBSDMemberHeader(), printGNUSmallMemberHeader(), printRestOfMemberHeader(), printWithSpacePadding(), Size, and useStringTable().
Referenced by computeMemberData().
printNBits()
static void printNBits (raw_ostream & Out, object::Archive::Kind Kind, uint64_t Val) static
Definition at line 376 of file ArchiveWriter.cpp.
References is64BitKind(), and llvm::print().
Referenced by writeSymbolTable().
printRestOfMemberHeader()
static void printRestOfMemberHeader (raw_ostream & Out, const sys::TimePoint< std::chrono::seconds > & ModTime, unsigned UID, unsigned GID, unsigned Perms, uint64_t Size) static
Definition at line 215 of file ArchiveWriter.cpp.
References llvm::format(), printWithSpacePadding(), Size, and llvm::sys::toTimeT().
Referenced by printBSDMemberHeader(), printGNUSmallMemberHeader(), and printMemberHeader().
printWithSpacePadding()
template<typename T > static void printWithSpacePadding (raw_ostream & OS, T Data, unsigned Size) static
Definition at line 168 of file ArchiveWriter.cpp.
References assert(), llvm::Data, llvm::raw_ostream::indent(), OS, Size, and llvm::raw_ostream::tell().
Referenced by computeStringTable(), printBigArchiveMemberHeader(), printBSDMemberHeader(), printGNUSmallMemberHeader(), printMemberHeader(), printRestOfMemberHeader(), and llvm::writeArchiveToStream().
useStringTable()
static bool useStringTable (bool Thin, StringRef Name) static
Definition at line 280 of file ArchiveWriter.cpp.
References Name.
Referenced by printMemberHeader().
writeECSymbols()
static void writeECSymbols (raw_ostream & Out, object::Archive::Kind Kind, bool Deterministic, ArrayRef< MemberData > Members, SymMap & SymMap) static
Definition at line 671 of file ArchiveWriter.cpp.
References computeECSymbolsSize(), SymMap::ECMap, now(), printGNUSmallMemberHeader(), printLE(), Size, and llvm::raw_ostream::write().
Referenced by llvm::writeArchiveToStream().
writeSymbolMap()
static void writeSymbolMap (raw_ostream & Out, object::Archive::Kind Kind, bool Deterministic, ArrayRef< MemberData > Members, SymMap & SymMap, uint64_t MembersOffset) static
Definition at line 645 of file ArchiveWriter.cpp.
References computeSymbolMapSize(), SymMap::Map, printLE(), Size, llvm::ArrayRef< T >::size(), llvm::raw_ostream::write(), and writeSymbolTableHeader().
Referenced by llvm::writeArchiveToStream().
writeSymbolTable()
static void writeSymbolTable (raw_ostream & Out, object::Archive::Kind Kind, bool Deterministic, ArrayRef< MemberData > Members, StringRef StringTable, uint64_t MembersOffset, unsigned NumSyms, uint64_t PrevMemberOffset = 0, uint64_t NextMemberOffset = 0, bool Is64Bit = false) static
Definition at line 595 of file ArchiveWriter.cpp.
References computeSymbolTableSize(), is64BitKind(), is64BitSymbolicFile(), isAIXBigArchive(), isBSDLike(), isCOFFArchive(), isDarwin(), printNBits(), Size, llvm::raw_ostream::write(), and writeSymbolTableHeader().
Referenced by llvm::writeArchiveToStream().
writeSymbolTableHeader()
static void writeSymbolTableHeader (raw_ostream & Out, object::Archive::Kind Kind, bool Deterministic, uint64_t Size, uint64_t PrevMemberOffset = 0, uint64_t NextMemberOffset = 0) static
Definition at line 442 of file ArchiveWriter.cpp.
References is64BitKind(), isAIXBigArchive(), isBSDLike(), Name, now(), printBigArchiveMemberHeader(), printBSDMemberHeader(), printGNUSmallMemberHeader(), Size, and llvm::raw_ostream::tell().
Referenced by computeHeadersSize(), writeSymbolMap(), and writeSymbolTable().
Variable Documentation
Log2OfAIXPageSize
const uint32_t Log2OfAIXPageSize = 12 static
Definition at line 538 of file ArchiveWriter.cpp.
Referenced by getAuxMaxAlignment(), and getMemberAlignment().
MinBigArchiveMemDataAlign
const uint32_t MinBigArchiveMemDataAlign = 2 static
Definition at line 544 of file ArchiveWriter.cpp.
Referenced by getAuxMaxAlignment(), and getMemberAlignment().