LLVM: lib/AsmParser/Parser.cpp File Reference
Parser.cpp File Reference
#include "llvm/AsmParser/Parser.h"
#include "llvm/AsmParser/LLParser.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ModuleSummaryIndex.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SourceMgr.h"
#include <system_error>
Functions
static bool parseAssemblyInto (MemoryBufferRef F, Module *M, ModuleSummaryIndex *Index, SMDiagnostic &Err, SlotMapping *Slots, bool UpgradeDebugInfo, DataLayoutCallbackTy DataLayoutCallback)
static ParsedModuleAndIndex parseAssemblyWithIndex (MemoryBufferRef F, SMDiagnostic &Err, LLVMContext &Context, SlotMapping *Slots, bool UpgradeDebugInfo, DataLayoutCallbackTy DataLayoutCallback)
static ParsedModuleAndIndex parseAssemblyFileWithIndex (StringRef Filename, SMDiagnostic &Err, LLVMContext &Context, SlotMapping *Slots, bool UpgradeDebugInfo, DataLayoutCallbackTy DataLayoutCallback)
static bool parseSummaryIndexAssemblyInto (MemoryBufferRef F, ModuleSummaryIndex &Index, SMDiagnostic &Err)
Function Documentation
parseAssemblyFileWithIndex()
static ParsedModuleAndIndex parseAssemblyFileWithIndex (StringRef Filename, SMDiagnostic & Err, LLVMContext & Context, SlotMapping * Slots, bool UpgradeDebugInfo, DataLayoutCallbackTy DataLayoutCallback) static
Definition at line 102 of file Parser.cpp.
References llvm::SourceMgr::DK_Error, llvm::ErrorOr< T >::get(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFileOrSTDIN(), llvm::parseAssemblyWithIndex(), and llvm::UpgradeDebugInfo().
parseAssemblyInto()
static bool parseAssemblyInto (MemoryBufferRef F, Module * M, ModuleSummaryIndex * Index, SMDiagnostic & Err, SlotMapping * Slots, bool UpgradeDebugInfo, DataLayoutCallbackTy DataLayoutCallback) static
Definition at line 24 of file Parser.cpp.
References llvm::SourceMgr::AddNewSourceBuffer(), F, llvm::MemoryBuffer::getMemBuffer(), llvm::LLParser::Run(), and llvm::UpgradeDebugInfo().
parseAssemblyWithIndex()
static ParsedModuleAndIndex parseAssemblyWithIndex (MemoryBufferRef F, SMDiagnostic & Err, LLVMContext & Context, SlotMapping * Slots, bool UpgradeDebugInfo, DataLayoutCallbackTy DataLayoutCallback) static
Definition at line 75 of file Parser.cpp.
References F, llvm::parseAssemblyInto(), and llvm::UpgradeDebugInfo().
parseSummaryIndexAssemblyInto()
static bool parseSummaryIndexAssemblyInto (MemoryBufferRef F, ModuleSummaryIndex & Index, SMDiagnostic & Err) static
Definition at line 144 of file Parser.cpp.
References llvm::SourceMgr::AddNewSourceBuffer(), F, llvm::MemoryBuffer::getMemBuffer(), and llvm::LLParser::Run().
Referenced by llvm::parseSummaryIndexAssembly().