LLVM: lib/Bitcode/Reader/BitcodeReader.cpp File Reference
BitcodeReader.cpp File Reference
#include "llvm/Bitcode/BitcodeReader.h"
#include "MetadataLoader.h"
#include "ValueList.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Bitcode/BitcodeCommon.h"
#include "llvm/Bitcode/LLVMBitCodes.h"
#include "llvm/Bitstream/BitstreamReader.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/AttributeMask.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/AutoUpgrade.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/ConstantRangeList.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GVMaterializer.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalIFunc.h"
#include "llvm/IR/GlobalObject.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsAArch64.h"
#include "llvm/IR/IntrinsicsARM.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ModuleSummaryIndex.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/ProfDataUtils.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/Verifier.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/ModRef.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Triple.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <deque>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <string>
#include <system_error>
#include <tuple>
#include <utility>
#include <vector>
Functions
static Error error (const Twine &Message)
static Error hasInvalidBitcodeHeader (BitstreamCursor &Stream)
static Expected< BitstreamCursor > initStream (MemoryBufferRef Buffer)
template<typename StrTy >
static bool convertToString (ArrayRef< uint64_t > Record, unsigned Idx, StrTy &Result)
Convert a string from a record into an std::string, return true on failure.
static void stripTBAA (Module *M)
static Expected< std::string > readIdentificationBlock (BitstreamCursor &Stream)
Read the "IDENTIFICATION_BLOCK_ID" block, do some basic enforcement on the "epoch" encoded in the bitcode, and return the producer name if any.
static Expected< std::string > readIdentificationCode (BitstreamCursor &Stream)
static Expected< bool > hasObjCCategoryInModule (BitstreamCursor &Stream)
static Expected< bool > hasObjCCategory (BitstreamCursor &Stream)
static Expected< std::string > readModuleTriple (BitstreamCursor &Stream)
static Expected< std::string > readTriple (BitstreamCursor &Stream)
static bool hasImplicitComdat (size_t Val)
static GlobalValue::LinkageTypes getDecodedLinkage (unsigned Val)
static FunctionSummary::FFlags getDecodedFFlags (uint64_t RawFlags)
static GlobalValueSummary::GVFlags getDecodedGVSummaryFlags (uint64_t RawFlags, uint64_t Version)
static GlobalVarSummary::GVarFlags getDecodedGVarFlags (uint64_t RawFlags)
static std::pair< CalleeInfo::HotnessType, bool > getDecodedHotnessCallEdgeInfo (uint64_t RawFlags)
static void getDecodedRelBFCallEdgeInfo (uint64_t RawFlags, uint64_t &RelBF, bool &HasTailCall)
static GlobalValue::VisibilityTypes getDecodedVisibility (unsigned Val)
static GlobalValue::DLLStorageClassTypes getDecodedDLLStorageClass (unsigned Val)
static bool getDecodedDSOLocal (unsigned Val)
static std::optional< CodeModel::Model > getDecodedCodeModel (unsigned Val)
static GlobalVariable::ThreadLocalMode getDecodedThreadLocalMode (unsigned Val)
static GlobalVariable::UnnamedAddr getDecodedUnnamedAddrType (unsigned Val)
static int getDecodedCastOpcode (unsigned Val)
static int getDecodedUnaryOpcode (unsigned Val, Type *Ty)
static int getDecodedBinaryOpcode (unsigned Val, Type *Ty)
static AtomicRMWInst::BinOp getDecodedRMWOperation (unsigned Val)
static AtomicOrdering getDecodedOrdering (unsigned Val)
static Comdat::SelectionKind getDecodedComdatSelectionKind (unsigned Val)
static FastMathFlags getDecodedFastMathFlags (unsigned Val)
static void upgradeDLLImportExportLinkage (GlobalValue *GV, unsigned Val)
static GEPNoWrapFlags toGEPNoWrapFlags (uint64_t Flags)
static bool isConstExprSupported (const BitcodeConstant *BC)
static uint64_t getRawAttributeMask (Attribute::AttrKind Val)
static void addRawAttributeValue (AttrBuilder &B, uint64_t Val)
static void decodeLLVMAttributesForBitcode (AttrBuilder &B, uint64_t EncodedAttrs, uint64_t AttrIdx)
This fills an AttrBuilder object with the LLVM attributes that have been decoded from the given integer.
static Attribute::AttrKind getAttrFromCode (uint64_t Code)
static bool upgradeOldMemoryAttribute (MemoryEffects &ME, uint64_t EncodedKind)
static Expected< uint64_t > jumpToValueSymbolTable (uint64_t Offset, BitstreamCursor &Stream)
Helper to note and return the current location, and jump to the given offset.
static void inferDSOLocal (GlobalValue *GV)
GlobalValue::SanitizerMetadata deserializeSanitizerMetadata (unsigned V)
static void parseWholeProgramDevirtResolutionByArg (ArrayRef< uint64_t > Record, size_t &Slot, WholeProgramDevirtResolution &Wpd)
static void parseWholeProgramDevirtResolution (ArrayRef< uint64_t > Record, StringRef Strtab, size_t &Slot, TypeIdSummary &TypeId)
static void parseTypeIdSummaryRecord (ArrayRef< uint64_t > Record, StringRef Strtab, ModuleSummaryIndex &TheIndex)
static void setSpecialRefs (std::vector< ValueInfo > &Refs, unsigned ROCnt, unsigned WOCnt)
static Expected< StringRef > readBlobInRecord (BitstreamCursor &Stream, unsigned Block, unsigned RecordID)
static Expected< std::pair< bool, bool > > getEnableSplitLTOUnitAndUnifiedFlag (BitstreamCursor &Stream, unsigned ID, BitcodeLTOInfo &LTOInfo)
static Expected< BitcodeModule > getSingleModule (MemoryBufferRef Buffer)
Variables
static cl::opt< bool > PrintSummaryGUIDs ("print-summary-global-ids", cl::init(false), cl::Hidden, cl::desc("Print the global id for each value when reading the module summary"))
static cl::opt< bool > ExpandConstantExprs ("expand-constant-exprs", cl::Hidden, cl::desc("Expand constant expressions to instructions for testing purposes"))
cl::opt< cl::boolOrDefault > LoadBitcodeIntoNewDbgInfoFormat ("load-bitcode-into-experimental-debuginfo-iterators", cl::Hidden, cl::desc("Load bitcode directly into the new debug info format (regardless " "of input format)"))
Load bitcode directly into RemoveDIs format (use debug records instead of debug intrinsics).
cl::opt< bool > UseNewDbgInfoFormat
cl::opt< cl::boolOrDefault > PreserveInputDbgFormat
bool WriteNewDbgInfoFormatToBitcode
cl::opt< bool > WriteNewDbgInfoFormat
Function Documentation
addRawAttributeValue()
static void addRawAttributeValue (AttrBuilder & B, uint64_t Val) static
Definition at line 1868 of file BitcodeReader.cpp.
References A, B, getRawAttributeMask(), and I.
Referenced by decodeLLVMAttributesForBitcode().
convertToString()
template<typename StrTy > static bool convertToString (ArrayRef< uint64_t > Record, unsigned Idx, StrTy & Result) static
Convert a string from a record into an std::string, return true on failure.
Definition at line 174 of file BitcodeReader.cpp.
Referenced by hasObjCCategoryInModule(), readIdentificationBlock(), and readModuleTriple().
decodeLLVMAttributesForBitcode()
static void decodeLLVMAttributesForBitcode (AttrBuilder & B, uint64_t EncodedAttrs, uint64_t AttrIdx) static
This fills an AttrBuilder object with the LLVM attributes that have been decoded from the given integer.
This function must stay in sync with 'encodeLLVMAttributesForBitcode'.
Definition at line 1889 of file BitcodeReader.cpp.
References addRawAttributeValue(), assert(), B, llvm::AttributeList::FunctionIndex, llvm::MemoryEffectsBase< LocationEnum >::inaccessibleMemOnly(), llvm::MemoryEffectsBase< LocationEnum >::inaccessibleOrArgMemOnly(), llvm::isPowerOf2_32(), llvm::MemoryEffectsBase< LocationEnum >::none(), llvm::MemoryEffectsBase< LocationEnum >::readOnly(), llvm::MemoryEffectsBase< LocationEnum >::unknown(), and llvm::MemoryEffectsBase< LocationEnum >::writeOnly().
deserializeSanitizerMetadata()
GlobalValue::SanitizerMetadata deserializeSanitizerMetadata (unsigned V)
Definition at line 3982 of file BitcodeReader.cpp.
error()
static Error error (const Twine & Message) static
Definition at line 126 of file BitcodeReader.cpp.
References llvm::make_error(), and llvm::make_error_code().
getAttrFromCode()
static Attribute::AttrKind getAttrFromCode (uint64_t Code) static
Definition at line 2002 of file BitcodeReader.cpp.
References llvm::bitc::ATTR_KIND_ALIGNMENT, llvm::bitc::ATTR_KIND_ALLOC_ALIGN, llvm::bitc::ATTR_KIND_ALLOC_KIND, llvm::bitc::ATTR_KIND_ALLOC_SIZE, llvm::bitc::ATTR_KIND_ALLOCATED_POINTER, llvm::bitc::ATTR_KIND_ALWAYS_INLINE, llvm::bitc::ATTR_KIND_BUILTIN, llvm::bitc::ATTR_KIND_BY_VAL, llvm::bitc::ATTR_KIND_BYREF, llvm::bitc::ATTR_KIND_COLD, llvm::bitc::ATTR_KIND_CONVERGENT, llvm::bitc::ATTR_KIND_CORO_ONLY_DESTROY_WHEN_COMPLETE, llvm::bitc::ATTR_KIND_DEAD_ON_UNWIND, llvm::bitc::ATTR_KIND_DEREFERENCEABLE, llvm::bitc::ATTR_KIND_DEREFERENCEABLE_OR_NULL, llvm::bitc::ATTR_KIND_DISABLE_SANITIZER_INSTRUMENTATION, llvm::bitc::ATTR_KIND_ELEMENTTYPE, llvm::bitc::ATTR_KIND_FNRETTHUNK_EXTERN, llvm::bitc::ATTR_KIND_HOT, llvm::bitc::ATTR_KIND_IMMARG, llvm::bitc::ATTR_KIND_IN_ALLOCA, llvm::bitc::ATTR_KIND_IN_REG, llvm::bitc::ATTR_KIND_INITIALIZES, llvm::bitc::ATTR_KIND_INLINE_HINT, llvm::bitc::ATTR_KIND_JUMP_TABLE, llvm::bitc::ATTR_KIND_MEMORY, llvm::bitc::ATTR_KIND_MIN_SIZE, llvm::bitc::ATTR_KIND_MUSTPROGRESS, llvm::bitc::ATTR_KIND_NAKED, llvm::bitc::ATTR_KIND_NEST, llvm::bitc::ATTR_KIND_NO_ALIAS, llvm::bitc::ATTR_KIND_NO_BUILTIN, llvm::bitc::ATTR_KIND_NO_CALLBACK, llvm::bitc::ATTR_KIND_NO_CAPTURE, llvm::bitc::ATTR_KIND_NO_DUPLICATE, llvm::bitc::ATTR_KIND_NO_IMPLICIT_FLOAT, llvm::bitc::ATTR_KIND_NO_INLINE, llvm::bitc::ATTR_KIND_NO_MERGE, llvm::bitc::ATTR_KIND_NO_PROFILE, llvm::bitc::ATTR_KIND_NO_RECURSE, llvm::bitc::ATTR_KIND_NO_RED_ZONE, llvm::bitc::ATTR_KIND_NO_RETURN, llvm::bitc::ATTR_KIND_NO_SANITIZE_BOUNDS, llvm::bitc::ATTR_KIND_NO_SANITIZE_COVERAGE, llvm::bitc::ATTR_KIND_NO_UNWIND, llvm::bitc::ATTR_KIND_NOCF_CHECK, llvm::bitc::ATTR_KIND_NOFPCLASS, llvm::bitc::ATTR_KIND_NOFREE, llvm::bitc::ATTR_KIND_NON_LAZY_BIND, llvm::bitc::ATTR_KIND_NON_NULL, llvm::bitc::ATTR_KIND_NOSYNC, llvm::bitc::ATTR_KIND_NOUNDEF, llvm::bitc::ATTR_KIND_NULL_POINTER_IS_VALID, llvm::bitc::ATTR_KIND_OPT_FOR_FUZZING, llvm::bitc::ATTR_KIND_OPTIMIZE_FOR_DEBUGGING, llvm::bitc::ATTR_KIND_OPTIMIZE_FOR_SIZE, llvm::bitc::ATTR_KIND_OPTIMIZE_NONE, llvm::bitc::ATTR_KIND_PREALLOCATED, llvm::bitc::ATTR_KIND_PRESPLIT_COROUTINE, llvm::bitc::ATTR_KIND_RANGE, llvm::bitc::ATTR_KIND_READ_NONE, llvm::bitc::ATTR_KIND_READ_ONLY, llvm::bitc::ATTR_KIND_RETURNED, llvm::bitc::ATTR_KIND_RETURNS_TWICE, llvm::bitc::ATTR_KIND_S_EXT, llvm::bitc::ATTR_KIND_SAFESTACK, llvm::bitc::ATTR_KIND_SANITIZE_ADDRESS, llvm::bitc::ATTR_KIND_SANITIZE_HWADDRESS, llvm::bitc::ATTR_KIND_SANITIZE_MEMORY, llvm::bitc::ATTR_KIND_SANITIZE_MEMTAG, llvm::bitc::ATTR_KIND_SANITIZE_NUMERICAL_STABILITY, llvm::bitc::ATTR_KIND_SANITIZE_THREAD, llvm::bitc::ATTR_KIND_SHADOWCALLSTACK, llvm::bitc::ATTR_KIND_SKIP_PROFILE, llvm::bitc::ATTR_KIND_SPECULATABLE, llvm::bitc::ATTR_KIND_SPECULATIVE_LOAD_HARDENING, llvm::bitc::ATTR_KIND_STACK_ALIGNMENT, llvm::bitc::ATTR_KIND_STACK_PROTECT, llvm::bitc::ATTR_KIND_STACK_PROTECT_REQ, llvm::bitc::ATTR_KIND_STACK_PROTECT_STRONG, llvm::bitc::ATTR_KIND_STRICT_FP, llvm::bitc::ATTR_KIND_STRUCT_RET, llvm::bitc::ATTR_KIND_SWIFT_ASYNC, llvm::bitc::ATTR_KIND_SWIFT_ERROR, llvm::bitc::ATTR_KIND_SWIFT_SELF, llvm::bitc::ATTR_KIND_UW_TABLE, llvm::bitc::ATTR_KIND_VSCALE_RANGE, llvm::bitc::ATTR_KIND_WILLRETURN, llvm::bitc::ATTR_KIND_WRITABLE, llvm::bitc::ATTR_KIND_WRITEONLY, and llvm::bitc::ATTR_KIND_Z_EXT.
getDecodedBinaryOpcode()
static int getDecodedBinaryOpcode (unsigned Val, Type * Ty) static
Definition at line 1292 of file BitcodeReader.cpp.
References llvm::bitc::BINOP_ADD, llvm::bitc::BINOP_AND, llvm::bitc::BINOP_ASHR, llvm::bitc::BINOP_LSHR, llvm::bitc::BINOP_MUL, llvm::bitc::BINOP_OR, llvm::bitc::BINOP_SDIV, llvm::bitc::BINOP_SHL, llvm::bitc::BINOP_SREM, llvm::bitc::BINOP_SUB, llvm::bitc::BINOP_UDIV, llvm::bitc::BINOP_UREM, and llvm::bitc::BINOP_XOR.
getDecodedCastOpcode()
static int getDecodedCastOpcode (unsigned Val) static
Definition at line 1259 of file BitcodeReader.cpp.
References llvm::bitc::CAST_ADDRSPACECAST, llvm::bitc::CAST_BITCAST, llvm::bitc::CAST_FPEXT, llvm::bitc::CAST_FPTOSI, llvm::bitc::CAST_FPTOUI, llvm::bitc::CAST_FPTRUNC, llvm::bitc::CAST_INTTOPTR, llvm::bitc::CAST_PTRTOINT, llvm::bitc::CAST_SEXT, llvm::bitc::CAST_SITOFP, llvm::bitc::CAST_TRUNC, llvm::bitc::CAST_UITOFP, and llvm::bitc::CAST_ZEXT.
getDecodedCodeModel()
static std::optional< CodeModel::Model > getDecodedCodeModel (unsigned Val) static
Definition at line 1222 of file BitcodeReader.cpp.
References llvm::CodeModel::Kernel, llvm::CodeModel::Large, llvm::CodeModel::Medium, llvm::CodeModel::Small, and llvm::CodeModel::Tiny.
getDecodedComdatSelectionKind()
static Comdat::SelectionKind getDecodedComdatSelectionKind (unsigned Val) static
Definition at line 1368 of file BitcodeReader.cpp.
References llvm::Comdat::Any, llvm::bitc::COMDAT_SELECTION_KIND_ANY, llvm::bitc::COMDAT_SELECTION_KIND_EXACT_MATCH, llvm::bitc::COMDAT_SELECTION_KIND_LARGEST, llvm::bitc::COMDAT_SELECTION_KIND_NO_DUPLICATES, llvm::bitc::COMDAT_SELECTION_KIND_SAME_SIZE, llvm::Comdat::ExactMatch, llvm::Comdat::Largest, llvm::Comdat::NoDeduplicate, and llvm::Comdat::SameSize.
getDecodedDLLStorageClass()
static GlobalValue::DLLStorageClassTypes getDecodedDLLStorageClass (unsigned Val) static
Definition at line 1205 of file BitcodeReader.cpp.
References llvm::GlobalValue::DefaultStorageClass, llvm::GlobalValue::DLLExportStorageClass, and llvm::GlobalValue::DLLImportStorageClass.
getDecodedDSOLocal()
static bool getDecodedDSOLocal (unsigned Val) static
Definition at line 1214 of file BitcodeReader.cpp.
getDecodedFastMathFlags()
static FastMathFlags getDecodedFastMathFlags (unsigned Val) static
Definition at line 1384 of file BitcodeReader.cpp.
References llvm::bitc::AllowContract, llvm::bitc::AllowReassoc, llvm::bitc::AllowReciprocal, llvm::bitc::ApproxFunc, llvm::bitc::NoInfs, llvm::bitc::NoNaNs, llvm::bitc::NoSignedZeros, llvm::FastMathFlags::setAllowContract(), llvm::FastMathFlags::setAllowReassoc(), llvm::FastMathFlags::setAllowReciprocal(), llvm::FastMathFlags::setApproxFunc(), llvm::FastMathFlags::setFast(), llvm::FastMathFlags::setNoInfs(), llvm::FastMathFlags::setNoNaNs(), llvm::FastMathFlags::setNoSignedZeros(), and llvm::bitc::UnsafeAlgebra.
getDecodedFFlags()
static FunctionSummary::FFlags getDecodedFFlags (uint64_t RawFlags) static
Definition at line 1131 of file BitcodeReader.cpp.
References llvm::FunctionSummary::FFlags::ReadNone.
getDecodedGVarFlags()
static GlobalVarSummary::GVarFlags getDecodedGVarFlags (uint64_t RawFlags) static
Definition at line 1172 of file BitcodeReader.cpp.
getDecodedGVSummaryFlags()
static GlobalValueSummary::GVFlags getDecodedGVSummaryFlags (uint64_t RawFlags, uint64_t Version) static
Definition at line 1150 of file BitcodeReader.cpp.
getDecodedHotnessCallEdgeInfo()
static std::pair< CalleeInfo::HotnessType, bool > getDecodedHotnessCallEdgeInfo (uint64_t RawFlags) static
Definition at line 1180 of file BitcodeReader.cpp.
getDecodedLinkage()
static GlobalValue::LinkageTypes getDecodedLinkage (unsigned Val) static
Definition at line 1089 of file BitcodeReader.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
getDecodedOrdering()
static AtomicOrdering getDecodedOrdering (unsigned Val) static
Definition at line 1355 of file BitcodeReader.cpp.
References llvm::bitc::ORDERING_ACQREL, llvm::bitc::ORDERING_ACQUIRE, llvm::bitc::ORDERING_MONOTONIC, llvm::bitc::ORDERING_NOTATOMIC, llvm::bitc::ORDERING_RELEASE, llvm::bitc::ORDERING_SEQCST, and llvm::bitc::ORDERING_UNORDERED.
getDecodedRelBFCallEdgeInfo()
static void getDecodedRelBFCallEdgeInfo (uint64_t RawFlags, uint64_t & RelBF, bool & HasTailCall) static
Definition at line 1187 of file BitcodeReader.cpp.
References llvm::CalleeInfo::RelBlockFreqBits.
getDecodedRMWOperation()
static AtomicRMWInst::BinOp getDecodedRMWOperation (unsigned Val) static
Definition at line 1330 of file BitcodeReader.cpp.
References llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, llvm::AtomicRMWInst::BAD_BINOP, llvm::AtomicRMWInst::FAdd, llvm::AtomicRMWInst::FMax, llvm::AtomicRMWInst::FMin, llvm::AtomicRMWInst::FSub, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Or, llvm::bitc::RMW_ADD, llvm::bitc::RMW_AND, llvm::bitc::RMW_FADD, llvm::bitc::RMW_FMAX, llvm::bitc::RMW_FMIN, llvm::bitc::RMW_FSUB, llvm::bitc::RMW_MAX, llvm::bitc::RMW_MIN, llvm::bitc::RMW_NAND, llvm::bitc::RMW_OR, llvm::bitc::RMW_SUB, llvm::bitc::RMW_UDEC_WRAP, llvm::bitc::RMW_UINC_WRAP, llvm::bitc::RMW_UMAX, llvm::bitc::RMW_UMIN, llvm::bitc::RMW_XCHG, llvm::bitc::RMW_XOR, llvm::AtomicRMWInst::Sub, llvm::AtomicRMWInst::UDecWrap, llvm::AtomicRMWInst::UIncWrap, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.
getDecodedThreadLocalMode()
static GlobalVariable::ThreadLocalMode getDecodedThreadLocalMode (unsigned Val) static
Definition at line 1239 of file BitcodeReader.cpp.
getDecodedUnaryOpcode()
static int getDecodedUnaryOpcode (unsigned Val, Type * Ty) static
Definition at line 1278 of file BitcodeReader.cpp.
References llvm::bitc::UNOP_FNEG.
getDecodedUnnamedAddrType()
static GlobalVariable::UnnamedAddr getDecodedUnnamedAddrType (unsigned Val) static
Definition at line 1250 of file BitcodeReader.cpp.
getDecodedVisibility()
static GlobalValue::VisibilityTypes getDecodedVisibility (unsigned Val) static
Definition at line 1195 of file BitcodeReader.cpp.
References llvm::GlobalValue::DefaultVisibility, llvm::GlobalValue::HiddenVisibility, and llvm::GlobalValue::ProtectedVisibility.
getEnableSplitLTOUnitAndUnifiedFlag()
static Expected< std::pair< bool, bool > > getEnableSplitLTOUnitAndUnifiedFlag (BitstreamCursor & Stream, unsigned ID, BitcodeLTOInfo & LTOInfo) static
Definition at line 8419 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advanceSkippingSubblocks(), assert(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, error, llvm::bitc::FS_FLAGS, llvm::Expected< T >::get(), llvm_unreachable, llvm::BitstreamCursor::readRecord(), llvm::BitstreamEntry::Record, llvm::BitstreamEntry::SubBlock, and llvm::Expected< T >::takeError().
Referenced by llvm::BitcodeModule::getLTOInfo().
getRawAttributeMask()
static uint64_t getRawAttributeMask (Attribute::AttrKind Val) static
Definition at line 1790 of file BitcodeReader.cpp.
References llvm_unreachable.
Referenced by addRawAttributeValue().
getSingleModule()
static Expected< BitcodeModule > getSingleModule (MemoryBufferRef Buffer) static
Definition at line 8529 of file BitcodeReader.cpp.
References error, llvm::getBitcodeModuleList(), and llvm::Expected< T >::takeError().
Referenced by llvm::getBitcodeLTOInfo(), llvm::getLazyBitcodeModule(), llvm::getModuleSummaryIndex(), llvm::parseBitcodeFile(), and llvm::readModuleSummaryIndex().
hasImplicitComdat()
static bool hasImplicitComdat (size_t Val) static
Definition at line 1077 of file BitcodeReader.cpp.
hasInvalidBitcodeHeader()
static Error hasInvalidBitcodeHeader (BitstreamCursor & Stream) static
Definition at line 131 of file BitcodeReader.cpp.
References llvm::CallingConv::C, llvm::BitstreamCursor::canSkipToPos(), llvm::createStringError(), llvm::BitstreamCursor::Read(), and llvm::Error::success().
Referenced by initStream().
hasObjCCategory()
static Expected< bool > hasObjCCategory (BitstreamCursor & Stream) static
Definition at line 323 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamEntry::Error, error, hasObjCCategoryInModule(), llvm::bitc::MODULE_BLOCK_ID, llvm::BitstreamEntry::Record, llvm::BitstreamCursor::SkipBlock(), llvm::BitstreamCursor::skipRecord(), and llvm::BitstreamEntry::SubBlock.
Referenced by getObjCClassCategory(), and llvm::isBitcodeContainingObjCCategory().
hasObjCCategoryInModule()
static Expected< bool > hasObjCCategoryInModule (BitstreamCursor & Stream) static
Definition at line 275 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advanceSkippingSubblocks(), convertToString(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, error, llvm::Expected< T >::get(), llvm_unreachable, llvm::bitc::MODULE_BLOCK_ID, llvm::bitc::MODULE_CODE_SECTIONNAME, llvm::BitstreamCursor::readRecord(), llvm::BitstreamEntry::Record, llvm::BitstreamEntry::SubBlock, and llvm::Expected< T >::takeError().
Referenced by hasObjCCategory().
inferDSOLocal()
static void inferDSOLocal (GlobalValue * GV) static
Definition at line 3975 of file BitcodeReader.cpp.
References llvm::GlobalValue::hasDefaultVisibility(), llvm::GlobalValue::hasExternalWeakLinkage(), llvm::GlobalValue::hasLocalLinkage(), and llvm::GlobalValue::setDSOLocal().
initStream()
static Expected< BitstreamCursor > initStream (MemoryBufferRef Buffer) static
Definition at line 152 of file BitcodeReader.cpp.
References error, llvm::MemoryBufferRef::getBufferSize(), llvm::MemoryBufferRef::getBufferStart(), hasInvalidBitcodeHeader(), llvm::isBitcodeWrapper(), and llvm::SkipBitcodeWrapperHeader().
Referenced by llvm::getBitcodeFileContents(), llvm::getBitcodeProducerString(), llvm::getBitcodeTargetTriple(), and llvm::isBitcodeContainingObjCCategory().
isConstExprSupported()
static bool isConstExprSupported (const BitcodeConstant * BC) static
Definition at line 1485 of file BitcodeReader.cpp.
References ExpandConstantExprs, llvm::Instruction::isBinaryOp(), llvm::Instruction::isCast(), llvm::ConstantExpr::isSupportedBinOp(), llvm::ConstantExpr::isSupportedCastOp(), and llvm::ConstantExpr::isSupportedGetElementPtr().
jumpToValueSymbolTable()
static Expected< uint64_t > jumpToValueSymbolTable (uint64_t Offset, BitstreamCursor & Stream) static
Helper to note and return the current location, and jump to the given offset.
Definition at line 2829 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), error, llvm::Expected< T >::get(), llvm::BitstreamCursor::GetCurrentBitNo(), llvm::BitstreamCursor::JumpToBit(), llvm::Offset, llvm::BitstreamEntry::SubBlock, llvm::Expected< T >::takeError(), and llvm::bitc::VALUE_SYMTAB_BLOCK_ID.
parseTypeIdSummaryRecord()
static void parseTypeIdSummaryRecord (ArrayRef< uint64_t > Record, StringRef Strtab, ModuleSummaryIndex & TheIndex) static
Definition at line 7432 of file BitcodeReader.cpp.
References llvm::TypeTestResolution::AlignLog2, llvm::TypeTestResolution::BitMask, llvm::StringRef::data(), llvm::ModuleSummaryIndex::getOrInsertTypeIdSummary(), llvm::TypeTestResolution::InlineBits, parseWholeProgramDevirtResolution(), llvm::TypeTestResolution::SizeM1, llvm::TypeTestResolution::SizeM1BitWidth, llvm::TypeTestResolution::TheKind, and llvm::TypeIdSummary::TTRes.
parseWholeProgramDevirtResolution()
static void parseWholeProgramDevirtResolution (ArrayRef< uint64_t > Record, StringRef Strtab, size_t & Slot, TypeIdSummary & TypeId) static
Definition at line 7416 of file BitcodeReader.cpp.
References llvm::StringRef::data(), I, parseWholeProgramDevirtResolutionByArg(), llvm::WholeProgramDevirtResolution::SingleImplName, llvm::WholeProgramDevirtResolution::TheKind, and llvm::TypeIdSummary::WPDRes.
Referenced by parseTypeIdSummaryRecord().
parseWholeProgramDevirtResolutionByArg()
static void parseWholeProgramDevirtResolutionByArg (ArrayRef< uint64_t > Record, size_t & Slot, WholeProgramDevirtResolution & Wpd) static
Definition at line 7402 of file BitcodeReader.cpp.
References B, and llvm::WholeProgramDevirtResolution::ResByArg.
Referenced by parseWholeProgramDevirtResolution().
readBlobInRecord()
static Expected< StringRef > readBlobInRecord (BitstreamCursor & Stream, unsigned Block, unsigned RecordID) static
Definition at line 8170 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), llvm::Block, llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, error, llvm::Expected< T >::get(), llvm::BitstreamCursor::readRecord(), llvm::BitstreamEntry::Record, llvm::BitstreamCursor::SkipBlock(), llvm::BitstreamEntry::SubBlock, and llvm::Expected< T >::takeError().
Referenced by llvm::getBitcodeFileContents().
readIdentificationBlock()
static Expected< std::string > readIdentificationBlock (BitstreamCursor & Stream) static
Read the "IDENTIFICATION_BLOCK_ID" block, do some basic enforcement on the "epoch" encoded in the bitcode, and return the producer name if any.
Definition at line 195 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), llvm::bitc::BITCODE_CURRENT_EPOCH, convertToString(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, error, llvm::Expected< T >::get(), llvm::bitc::IDENTIFICATION_BLOCK_ID, llvm::bitc::IDENTIFICATION_CODE_EPOCH, llvm::bitc::IDENTIFICATION_CODE_STRING, llvm::BitstreamCursor::readRecord(), llvm::BitstreamEntry::Record, and llvm::Expected< T >::takeError().
Referenced by readIdentificationCode().
readIdentificationCode()
static Expected< std::string > readIdentificationCode (BitstreamCursor & Stream) static
Definition at line 243 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), llvm::BitstreamCursor::AtEndOfStream(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamEntry::Error, error, llvm::bitc::IDENTIFICATION_BLOCK_ID, readIdentificationBlock(), llvm::BitstreamEntry::Record, llvm::BitstreamCursor::SkipBlock(), llvm::BitstreamCursor::skipRecord(), and llvm::BitstreamEntry::SubBlock.
Referenced by llvm::getBitcodeProducerString().
readModuleTriple()
static Expected< std::string > readModuleTriple (BitstreamCursor & Stream) static
Definition at line 354 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advanceSkippingSubblocks(), convertToString(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamCursor::EnterSubBlock(), llvm::BitstreamEntry::Error, error, llvm::Expected< T >::get(), llvm_unreachable, llvm::bitc::MODULE_BLOCK_ID, llvm::bitc::MODULE_CODE_TRIPLE, llvm::BitstreamCursor::readRecord(), llvm::BitstreamEntry::Record, llvm::BitstreamEntry::SubBlock, and llvm::Expected< T >::takeError().
Referenced by readTriple().
readTriple()
static Expected< std::string > readTriple (BitstreamCursor & Stream) static
Definition at line 399 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::advance(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamEntry::Error, error, llvm::Expected< T >::get(), llvm::bitc::MODULE_BLOCK_ID, readModuleTriple(), llvm::BitstreamEntry::Record, llvm::BitstreamCursor::SkipBlock(), llvm::BitstreamCursor::skipRecord(), llvm::BitstreamEntry::SubBlock, and llvm::Expected< T >::takeError().
Referenced by llvm::getBitcodeTargetTriple().
setSpecialRefs()
static void setSpecialRefs (std::vector< ValueInfo > & Refs, unsigned ROCnt, unsigned WOCnt) static
Definition at line 7507 of file BitcodeReader.cpp.
References assert().
stripTBAA()
static void stripTBAA (Module * M) static
Definition at line 184 of file BitcodeReader.cpp.
References F, I, and instructions.
toGEPNoWrapFlags()
static GEPNoWrapFlags toGEPNoWrapFlags (uint64_t Flags) static
Definition at line 1474 of file BitcodeReader.cpp.
References llvm::bitc::GEP_INBOUNDS, llvm::bitc::GEP_NUSW, llvm::bitc::GEP_NUW, llvm::GEPNoWrapFlags::inBounds(), llvm::GEPNoWrapFlags::noUnsignedSignedWrap(), and llvm::GEPNoWrapFlags::noUnsignedWrap().
upgradeDLLImportExportLinkage()
static void upgradeDLLImportExportLinkage (GlobalValue * GV, unsigned Val) static
Definition at line 1405 of file BitcodeReader.cpp.
References llvm::GlobalValue::DLLExportStorageClass, llvm::GlobalValue::DLLImportStorageClass, llvm::GlobalValue::hasLocalLinkage(), and llvm::GlobalValue::setDLLStorageClass().
upgradeOldMemoryAttribute()
static bool upgradeOldMemoryAttribute (MemoryEffects & ME, uint64_t EncodedKind) static
Definition at line 2208 of file BitcodeReader.cpp.
References llvm::MemoryEffectsBase< LocationEnum >::argMemOnly(), llvm::bitc::ATTR_KIND_ARGMEMONLY, llvm::bitc::ATTR_KIND_INACCESSIBLEMEM_ONLY, llvm::bitc::ATTR_KIND_INACCESSIBLEMEM_OR_ARGMEMONLY, llvm::bitc::ATTR_KIND_READ_NONE, llvm::bitc::ATTR_KIND_READ_ONLY, llvm::bitc::ATTR_KIND_WRITEONLY, llvm::MemoryEffectsBase< LocationEnum >::inaccessibleMemOnly(), llvm::MemoryEffectsBase< LocationEnum >::inaccessibleOrArgMemOnly(), llvm::MemoryEffectsBase< LocationEnum >::none(), llvm::MemoryEffectsBase< LocationEnum >::readOnly(), and llvm::MemoryEffectsBase< LocationEnum >::writeOnly().
Variable Documentation
ExpandConstantExprs
cl::opt< bool > ExpandConstantExprs("expand-constant-exprs", cl::Hidden, cl::desc("Expand constant expressions to instructions for testing purposes")) ("expand-constant-exprs" , cl::Hidden , cl::desc("Expand constant expressions to instructions for testing purposes")) static
Referenced by isConstExprSupported().
LoadBitcodeIntoNewDbgInfoFormat
cl::opt< cl::boolOrDefault > LoadBitcodeIntoNewDbgInfoFormat("load-bitcode-into-experimental-debuginfo-iterators", cl::Hidden, cl::desc("Load bitcode directly into the new debug info format (regardless " "of input format)")) ("load-bitcode-into-experimental-debuginfo-iterators" , cl::Hidden , cl::desc("Load bitcode directly into the new debug info format (regardless " "of input format)"))
Load bitcode directly into RemoveDIs format (use debug records instead of debug intrinsics).
UNSET is treated as FALSE, so the default action is to do nothing. Individual tools can override this to incrementally add support for the RemoveDIs format.
PreserveInputDbgFormat
cl::opt<cl::boolOrDefault> PreserveInputDbgFormat extern
PrintSummaryGUIDs
cl::opt< bool > PrintSummaryGUIDs("print-summary-global-ids", cl::init(false), cl::Hidden, cl::desc("Print the global id for each value when reading the module summary")) ("print-summary-global-ids" , cl::init(false) , cl::Hidden , cl::desc("Print the global id for each value when reading the module summary")) static
UseNewDbgInfoFormat
cl::opt<bool> UseNewDbgInfoFormat extern
WriteNewDbgInfoFormat
cl::opt<bool> WriteNewDbgInfoFormat extern
WriteNewDbgInfoFormatToBitcode
bool WriteNewDbgInfoFormatToBitcode extern
Definition at line 47 of file BasicBlock.cpp.