LLVM: lib/Target/BPF/BPFAbstractMemberAccess.cpp File Reference
BPFAbstractMemberAccess.cpp File Reference
#include "BPF.h"
#include "BPFCORE.h"
#include "BPFTargetMachine.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/DebugInfo/BTF/BTF.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicsBPF.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueHandle.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include <stack>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "bpf-abstract-member-access"
Functions
static bool SkipDIDerivedTag (unsigned Tag, bool skipTypedef)
static DIType * stripQualifiers (DIType *Ty, bool skipTypedef=true)
static const DIType * stripQualifiers (const DIType *Ty)
static uint32_t calcArraySize (const DICompositeType *CTy, uint32_t StartDim)
static Type * getBaseElementType (const CallInst *Call)
static uint64_t getConstant (const Value *IndexValue)
static void replaceWithGEP (CallInst *Call, uint32_t DimensionIndex, uint32_t GEPIndex)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "bpf-abstract-member-access"
Definition at line 97 of file BPFAbstractMemberAccess.cpp.
Function Documentation
calcArraySize()
static uint32_t calcArraySize (const DICompositeType * CTy, uint32_t StartDim) static
Definition at line 306 of file BPFAbstractMemberAccess.cpp.
References llvm::cast(), llvm::dyn_cast_or_null(), llvm::DISubrange::getCount(), llvm::DICompositeType::getElements(), and I.
getBaseElementType()
static Type * getBaseElementType (const CallInst * Call) static
Definition at line 321 of file BPFAbstractMemberAccess.cpp.
References Call, and llvm::CallBase::getParamElementType().
Referenced by replaceWithGEP().
getConstant()
static uint64_t getConstant (const Value * IndexValue) static
Definition at line 326 of file BPFAbstractMemberAccess.cpp.
References assert(), llvm::dyn_cast(), llvm::ConstantInt::getValue(), and llvm::APInt::getZExtValue().
Referenced by replaceWithGEP().
replaceWithGEP()
static void replaceWithGEP (CallInst * Call, uint32_t DimensionIndex, uint32_t GEPIndex) static
Definition at line 416 of file BPFAbstractMemberAccess.cpp.
References Call, llvm::GetElementPtrInst::CreateInBounds(), llvm::Instruction::eraseFromParent(), GEP, llvm::CallBase::getArgOperand(), getBaseElementType(), getConstant(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), I, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Value::replaceAllUsesWith().
Referenced by llvm::BPFCoreSharedInfo::removeArrayAccessCall(), and llvm::BPFCoreSharedInfo::removeStructAccessCall().
SkipDIDerivedTag()
static bool SkipDIDerivedTag (unsigned Tag, bool skipTypedef) static
Definition at line 277 of file BPFAbstractMemberAccess.cpp.
Referenced by stripQualifiers(), and stripQualifiers().
stripQualifiers() [1/2]
static const DIType * stripQualifiers (const DIType * Ty) static
Definition at line 297 of file BPFAbstractMemberAccess.cpp.
References llvm::dyn_cast(), llvm::DINode::getTag(), and SkipDIDerivedTag().
stripQualifiers() [2/2]
static DIType * stripQualifiers (DIType * Ty, bool skipTypedef = true) static
Definition at line 288 of file BPFAbstractMemberAccess.cpp.
References llvm::dyn_cast(), llvm::DINode::getTag(), and SkipDIDerivedTag().