LLVM: lib/Target/BPF/BPFCheckAndAdjustIR.cpp File Reference
BPFCheckAndAdjustIR.cpp File Reference
#include "BPF.h"
#include "BPFCORE.h"
#include "BPFTargetMachine.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicsBPF.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Classes
struct MinMaxSinkInfo
Macros
#define DEBUG_TYPE "bpf-check-and-opt-ir"
Functions
INITIALIZE_PASS (BPFCheckAndAdjustIR, DEBUG_TYPE, "BPF Check And Adjust IR", false, false) ModulePass *llvm
static bool sinkMinMaxInBB (BasicBlock &BB, const std::function< bool(Instruction *)> &Filter)
static void unrollGEPLoad (CallInst *Call)
static void unrollGEPStore (CallInst *Call)
static bool removeGEPBuiltinsInFunc (Function &F)
static Value * aspaceWrapValue (DenseMap< Value *, Value * > &Cache, Function *F, Value *ToWrap)
static void aspaceWrapOperand (DenseMap< Value *, Value * > &Cache, Instruction *I, unsigned OpNum)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "bpf-check-and-opt-ir"
Definition at line 39 of file BPFCheckAndAdjustIR.cpp.
Function Documentation
aspaceWrapOperand()
static void aspaceWrapOperand (DenseMap< Value *, Value * > & Cache, Instruction * I, unsigned OpNum) static
Definition at line 464 of file BPFCheckAndAdjustIR.cpp.
References aspaceWrapValue(), llvm::dyn_cast(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), and I.
aspaceWrapValue()
static Value * aspaceWrapValue (DenseMap< Value *, Value * > & Cache, Function * F, Value * ToWrap) static
Definition at line 431 of file BPFCheckAndAdjustIR.cpp.
References aspaceWrapValue(), llvm::cast(), llvm::dyn_cast(), F, GEP, llvm::Value::getName(), llvm::Value::getType(), and Ptr.
Referenced by aspaceWrapOperand(), and aspaceWrapValue().
INITIALIZE_PASS()
INITIALIZE_PASS (BPFCheckAndAdjustIR , DEBUG_TYPE , "BPF Check And Adjust IR" , false , false)
Definition at line 65 of file BPFCheckAndAdjustIR.cpp.
removeGEPBuiltinsInFunc()
static bool removeGEPBuiltinsInFunc (Function & F) static
Definition at line 386 of file BPFCheckAndAdjustIR.cpp.
References Call, llvm::dyn_cast(), llvm::SmallVectorBase< Size_T >::empty(), F, llvm::for_each(), llvm::CallBase::getCalledFunction(), Insn, llvm::SmallVectorTemplateBase< T, bool >::push_back(), unrollGEPLoad(), and unrollGEPStore().
sinkMinMaxInBB()
static bool sinkMinMaxInBB (BasicBlock & BB, const std::function< bool(Instruction *)> & Filter) static
Definition at line 188 of file BPFCheckAndAdjustIR.cpp.
References A, assert(), B, Call, Changed, llvm::dyn_cast(), llvm::Filter, llvm::First, llvm::CallBase::getCalledOperand(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), I, Info, llvm::ICmpInst::isGE(), llvm::ICmpInst::isGT(), llvm::ICmpInst::isLE(), llvm::ICmpInst::isLT(), llvm::ICmpInst::isRelational(), P, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), ToRemove, and X.
unrollGEPLoad()
static void unrollGEPLoad (CallInst * Call) static
Definition at line 371 of file BPFCheckAndAdjustIR.cpp.
References Call, llvm::Instruction::eraseFromParent(), GEP, llvm::BPFPreserveStaticOffsetPass::reconstructLoad(), and llvm::Value::replaceAllUsesWith().
Referenced by removeGEPBuiltinsInFunc().
unrollGEPStore()
static void unrollGEPStore (CallInst * Call) static
Definition at line 379 of file BPFCheckAndAdjustIR.cpp.
References Call, llvm::Instruction::eraseFromParent(), GEP, and llvm::BPFPreserveStaticOffsetPass::reconstructStore().
Referenced by removeGEPBuiltinsInFunc().