LLVM: lib/DebugInfo/BTF/BTFParser.cpp File Reference
BTFParser.cpp File Reference
#include "llvm/DebugInfo/BTF/BTFParser.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Errc.h"
Classes
struct llvm::BTFParser::ParseContext
Macros
#define DEBUG_TYPE "debug-info-btf-parser"
Enumerations
enum RelocKindGroup { RKG_FIELD , RKG_TYPE , RKG_ENUMVAL , RKG_UNKNOWN }
Functions
static size_t byteSize (BTF::CommonType *Type)
template<typename T >
static const T * findInfo (const DenseMap< uint64_t, SmallVector< T, 0 > > &SecMap, SectionedAddress Address)
static RelocKindGroup relocKindGroup (const BTF::BPFFieldReloc *Reloc)
static bool isMod (const BTF::CommonType *Type)
static bool printMod (const BTFParser &BTF, const BTF::CommonType *Type, raw_ostream &Stream)
static const BTF::CommonType * skipModsAndTypedefs (const BTFParser &BTF, const BTF::CommonType *Type)
static void relocKindName (uint32_t X, raw_ostream &Out)
Variables
const char BTFSectionName [] = ".BTF"
const char BTFExtSectionName [] = ".BTF.ext"
const BTF::CommonType VoidTypeInst = {0, BTF::BTF_KIND_UNKN << 24, {0}}
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "debug-info-btf-parser"
Definition at line 19 of file BTFParser.cpp.
Enumeration Type Documentation
RelocKindGroup
enum RelocKindGroup
Enumerator
RKG_FIELD
RKG_TYPE
RKG_ENUMVAL
RKG_UNKNOWN
Definition at line 464 of file BTFParser.cpp.
Function Documentation
byteSize()
static size_t byteSize (BTF::CommonType * Type) static
Definition at line 154 of file BTFParser.cpp.
References Size.
findInfo()
template<typename T > static const T * findInfo (const DenseMap< uint64_t, SmallVector< T, 0 > > & SecMap, SectionedAddress Address) static
Definition at line 432 of file BTFParser.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::partition_point().
Referenced by llvm::BTFParser::findFieldReloc(), and llvm::BTFParser::findLineInfo().
isMod()
static bool isMod (const BTF::CommonType * Type) static
Definition at line 494 of file BTFParser.cpp.
Referenced by skipModsAndTypedefs().
printMod()
static bool printMod (const BTFParser & BTF, const BTF::CommonType * Type, raw_ostream & Stream) static
Definition at line 506 of file BTFParser.cpp.
References llvm::BTFParser::findString().
Referenced by llvm::BTFParser::symbolize().
relocKindGroup()
static RelocKindGroup relocKindGroup (const BTF::BPFFieldReloc * Reloc) static
Definition at line 471 of file BTFParser.cpp.
References llvm::BTF::BTF_TYPE_ID_LOCAL, llvm::BTF::BTF_TYPE_ID_REMOTE, llvm::BTF::ENUM_VALUE, llvm::BTF::ENUM_VALUE_EXISTENCE, llvm::BTF::FIELD_BYTE_OFFSET, llvm::BTF::FIELD_BYTE_SIZE, llvm::BTF::FIELD_EXISTENCE, llvm::BTF::FIELD_LSHIFT_U64, llvm::BTF::FIELD_RSHIFT_U64, llvm::BTF::FIELD_SIGNEDNESS, llvm::BTF::BPFFieldReloc::RelocKind, RKG_ENUMVAL, RKG_FIELD, RKG_TYPE, RKG_UNKNOWN, llvm::BTF::TYPE_EXISTENCE, llvm::BTF::TYPE_MATCH, and llvm::BTF::TYPE_SIZE.
Referenced by llvm::BTFParser::symbolize().
relocKindName()
static void relocKindName (uint32_t X, raw_ostream & Out) static
Definition at line 555 of file BTFParser.cpp.
References llvm::BTF::BTF_TYPE_ID_LOCAL, llvm::BTF::BTF_TYPE_ID_REMOTE, llvm::BTF::ENUM_VALUE, llvm::BTF::ENUM_VALUE_EXISTENCE, llvm::BTF::FIELD_BYTE_OFFSET, llvm::BTF::FIELD_BYTE_SIZE, llvm::BTF::FIELD_EXISTENCE, llvm::BTF::FIELD_LSHIFT_U64, llvm::BTF::FIELD_RSHIFT_U64, llvm::BTF::FIELD_SIGNEDNESS, llvm::BTF::TYPE_EXISTENCE, llvm::BTF::TYPE_MATCH, llvm::BTF::TYPE_SIZE, and X.
Referenced by llvm::BTFParser::symbolize().
skipModsAndTypedefs()
static const BTF::CommonType * skipModsAndTypedefs (const BTFParser & BTF, const BTF::CommonType * Type) static
Definition at line 527 of file BTFParser.cpp.
References llvm::sampleprof::Base, llvm::BTFParser::findType(), isMod(), llvm::Type::Type(), and Type.
Referenced by llvm::BTFParser::symbolize().
Variable Documentation
BTFExtSectionName
const char BTFExtSectionName[] = ".BTF.ext"
Definition at line 27 of file BTFParser.cpp.
Referenced by llvm::BTFParser::hasBTFSections(), and llvm::BTFParser::parse().
BTFSectionName
const char BTFSectionName[] = ".BTF"
Definition at line 26 of file BTFParser.cpp.
Referenced by llvm::BTFParser::hasBTFSections(), and llvm::BTFParser::parse().
VoidTypeInst
const BTF::CommonType VoidTypeInst = {0, BTF::BTF_KIND_UNKN << 24, {0}}
Definition at line 191 of file BTFParser.cpp.