LLVM: lib/Transforms/Instrumentation/CGProfile.cpp File Reference
CGProfile.cpp File Reference
#include "llvm/Transforms/Instrumentation/CGProfile.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/LazyBlockFrequencyInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/Transforms/Instrumentation.h"
#include <optional>
Functions
static bool addModuleFlags (Module &M, MapVector< std::pair< Function *, Function * >, uint64_t > &Counts)
static bool runCGProfilePass (Module &M, FunctionAnalysisManager &FAM, bool InLTO)
Function Documentation
addModuleFlags()
static bool addModuleFlags (Module & M, MapVector< std::pair< Function *, Function * >, uint64_t > & Counts) static
Definition at line 26 of file CGProfile.cpp.
References llvm::MDBuilder::createConstant(), llvm::MDNode::get(), llvm::ValueAsMetadata::get(), and llvm::MDTuple::getDistinct().
Referenced by runCGProfilePass().
runCGProfilePass()
static bool runCGProfilePass (Module & M, FunctionAnalysisManager & FAM, bool InLTO) static
Definition at line 48 of file CGProfile.cpp.
References addModuleFlags(), llvm::Count, llvm::InstrProfSymtab::create(), llvm::dyn_cast(), F, FAM, llvm::CallBase::getCalledFunction(), llvm::InstrProfSymtab::getFunction(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::getValueProfDataFromInst(), I, llvm::CallBase::isIndirectCall(), llvm::TargetTransformInfo::isLoweredToCall(), and llvm::SaturatingAdd().
Referenced by llvm::CGProfilePass::run().