LLVM: llvm::MCLOHContainer Class Reference
llvm::MCLOHContainer Class Reference
#include "llvm/MC/MCLinkerOptimizationHint.h"
Public Types
using LOHDirectives = SmallVectorImpl<MCLOHDirective>
Public Member Functions
MCLOHContainer ()=default
const LOHDirectives & getDirectives () const
Const accessor to the directives.
void addDirective (MCLOHType Kind, const MCLOHDirective::LOHArgs &Args)
Add the directive of the given kind Kind with the given arguments Args to the container.
uint64_t getEmitSize (const MCAssembler &Asm, const MachObjectWriter &ObjWriter) const
Get the size of the directives if emitted.
void emit (const MCAssembler &Asm, MachObjectWriter &ObjWriter) const
Emit all Linker Optimization Hint in one big table.
void reset ()
Detailed Description
Definition at line 136 of file MCLinkerOptimizationHint.h.
Member Typedef Documentation
LOHDirectives
using llvm::MCLOHContainer::LOHDirectives = SmallVectorImpl<MCLOHDirective>
Definition at line 144 of file MCLinkerOptimizationHint.h.
Constructor & Destructor Documentation
MCLOHContainer()
llvm::MCLOHContainer::MCLOHContainer () default
Member Function Documentation
addDirective()
void llvm::MCLOHContainer::addDirective (MCLOHType Kind, const MCLOHDirective::LOHArgs & Args) inline
Add the directive of the given kind Kind with the given arguments Args to the container.
Definition at line 155 of file MCLinkerOptimizationHint.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
emit()
void llvm::MCLOHContainer::emit (const MCAssembler & Asm, MachObjectWriter & ObjWriter) const inline
Emit all Linker Optimization Hint in one big table.
Each line of the table is emitted by LOHDirective::emit.
Definition at line 171 of file MCLinkerOptimizationHint.h.
References D.
Referenced by llvm::MachObjectWriter::writeObject().
getDirectives()
const LOHDirectives & llvm::MCLOHContainer::getDirectives () const inline
Const accessor to the directives.
Definition at line 149 of file MCLinkerOptimizationHint.h.
getEmitSize()
uint64_t llvm::MCLOHContainer::getEmitSize (const MCAssembler & Asm, const MachObjectWriter & ObjWriter) const inline
Get the size of the directives if emitted.
Definition at line 160 of file MCLinkerOptimizationHint.h.
References D.
Referenced by llvm::MachObjectWriter::writeObject().
reset()
void llvm::MCLOHContainer::reset () inline
Definition at line 176 of file MCLinkerOptimizationHint.h.
References llvm::SmallVectorImpl< T >::clear().
Referenced by llvm::MachObjectWriter::reset().
The documentation for this class was generated from the following file:
include/llvm/MC/MCLinkerOptimizationHint.h