LLVM: llvm::InlineAdvisorAnalysisPrinterPass Class Reference
llvm::InlineAdvisorAnalysisPrinterPass Class Reference
Printer pass for the InlineAdvisorAnalysis results.
#include "llvm/Analysis/InlineAdvisor.h"
Public Member Functions
InlineAdvisorAnalysisPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &MAM)
PreservedAnalyses run (LazyCallGraph::SCC &InitialC, CGSCCAnalysisManager &AM, LazyCallGraph &CG, CGSCCUpdateResult &UR)
Public Member Functions inherited from llvm::PassInfoMixin< InlineAdvisorAnalysisPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< InlineAdvisorAnalysisPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the InlineAdvisorAnalysis results.
Definition at line 345 of file InlineAdvisor.h.
Constructor & Destructor Documentation
InlineAdvisorAnalysisPrinterPass()
llvm::InlineAdvisorAnalysisPrinterPass::InlineAdvisorAnalysisPrinterPass (raw_ostream & OS) inline explicit
Definition at line 350 of file InlineAdvisor.h.
References OS.
Member Function Documentation
isRequired()
static bool llvm::InlineAdvisorAnalysisPrinterPass::isRequired () inline static
Definition at line 356 of file InlineAdvisor.h.
run() [1/2]
PreservedAnalyses InlineAdvisorAnalysisPrinterPass::run (LazyCallGraph::SCC & InitialC, CGSCCAnalysisManager & AM, LazyCallGraph & CG, CGSCCUpdateResult & UR)
Definition at line 639 of file InlineAdvisor.cpp.
References llvm::PreservedAnalyses::all(), llvm::LazyCallGraph::SCC::begin(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::LazyCallGraph::SCC::size().
run() [2/2]
PreservedAnalyses InlineAdvisorAnalysisPrinterPass::run (Module & M, ModuleAnalysisManager & MAM)
Definition at line 630 of file InlineAdvisor.cpp.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), and MAM.
The documentation for this class was generated from the following files:
include/llvm/Analysis/InlineAdvisor.h
lib/Analysis/InlineAdvisor.cpp