LLVM: llvm::SCEVParameterRewriter Class Reference
llvm::SCEVParameterRewriter Class Reference
The SCEVParameterRewriter takes a scalar evolution expression and updates the SCEVUnknown components following the Map (Value -> SCEV).
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
Public Member Functions
SCEVParameterRewriter (ScalarEvolution &SE, ValueToSCEVMapTy &M)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
Public Member Functions inherited from llvm::SCEVRewriteVisitor< SCEVParameterRewriter >
SCEVRewriteVisitor (ScalarEvolution &SE)
const SCEV * visit (const SCEV *S)
const SCEV * visitConstant (const SCEVConstant *Constant)
const SCEV * visitVScale (const SCEVVScale *VScale)
const SCEV * visitPtrToIntExpr (const SCEVPtrToIntExpr *Expr)
const SCEV * visitTruncateExpr (const SCEVTruncateExpr *Expr)
const SCEV * visitZeroExtendExpr (const SCEVZeroExtendExpr *Expr)
const SCEV * visitSignExtendExpr (const SCEVSignExtendExpr *Expr)
const SCEV * visitAddExpr (const SCEVAddExpr *Expr)
const SCEV * visitMulExpr (const SCEVMulExpr *Expr)
const SCEV * visitUDivExpr (const SCEVUDivExpr *Expr)
const SCEV * visitAddRecExpr (const SCEVAddRecExpr *Expr)
const SCEV * visitSMaxExpr (const SCEVSMaxExpr *Expr)
const SCEV * visitUMaxExpr (const SCEVUMaxExpr *Expr)
const SCEV * visitSMinExpr (const SCEVSMinExpr *Expr)
const SCEV * visitUMinExpr (const SCEVUMinExpr *Expr)
const SCEV * visitSequentialUMinExpr (const SCEVSequentialUMinExpr *Expr)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *Expr)
Public Member Functions inherited from llvm::SCEVVisitor< SCEVParameterRewriter, const SCEV * >
const SCEV * visit (const SCEV *S)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *S)
Static Public Member Functions
static const SCEV * rewrite (const SCEV *Scev, ScalarEvolution &SE, ValueToSCEVMapTy &Map)
Additional Inherited Members
Protected Attributes inherited from llvm::SCEVRewriteVisitor< SCEVParameterRewriter >
ScalarEvolution & SE
SmallDenseMap< const SCEV *, const SCEV * > RewriteResults
Detailed Description
The SCEVParameterRewriter takes a scalar evolution expression and updates the SCEVUnknown components following the Map (Value -> SCEV).
Definition at line 902 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
SCEVParameterRewriter()
llvm::SCEVParameterRewriter::SCEVParameterRewriter (ScalarEvolution & SE, ValueToSCEVMapTy & M) inline
Definition at line 910 of file ScalarEvolutionExpressions.h.
Member Function Documentation
rewrite()
static const SCEV * llvm::SCEVParameterRewriter::rewrite (const SCEV * Scev, ScalarEvolution & SE, ValueToSCEVMapTy & Map) inline static
Definition at line 904 of file ScalarEvolutionExpressions.h.
References Rewriter, and llvm::SCEVRewriteVisitor< SCEVParameterRewriter >::SE.
Referenced by llvm::SCEVDivision::visitMulExpr().
visitUnknown()
const SCEV * llvm::SCEVParameterRewriter::visitUnknown (const SCEVUnknown * Expr) inline
Definition at line 913 of file ScalarEvolutionExpressions.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::SCEVUnknown::getValue(), and I.
The documentation for this class was generated from the following file:
include/llvm/Analysis/ScalarEvolutionExpressions.h