LLVM: llvm::logicalview::LVCompare Class Reference
llvm::logicalview::LVCompare Class Reference final
#include "llvm/DebugInfo/LogicalView/Core/LVCompare.h"
Public Member Functions
LVCompare ()=delete
LVCompare (raw_ostream &OS)
LVCompare (const LVCompare &)=delete
LVCompare & operator= (const LVCompare &)=delete
~LVCompare ()=default
void push (LVScope *Scope)
void pop ()
Error execute (LVReader *ReferenceReader, LVReader *TargetReader)
void addPassEntry (LVReader *Reader, LVElement *Element, LVComparePass Pass)
const LVPassTable & getPassTable () const &
void printItem (LVElement *Element, LVComparePass Pass)
void print (raw_ostream &OS) const
void dump () const
Static Public Member Functions
static LVCompare & getInstance ()
Detailed Description
Definition at line 28 of file LVCompare.h.
Constructor & Destructor Documentation
LVCompare() [1/3]
llvm::logicalview::LVCompare::LVCompare () delete
LVCompare() [2/3]
LVCompare::LVCompare (raw_ostream & OS)
Definition at line 110 of file LVCompare.cpp.
References llvm::logicalview::options().
LVCompare() [3/3]
llvm::logicalview::LVCompare::LVCompare (const LVCompare &) delete
~LVCompare()
llvm::logicalview::LVCompare::~LVCompare () default
Member Function Documentation
addPassEntry()
void llvm::logicalview::LVCompare::addPassEntry (LVReader * Reader, LVElement * Element, LVComparePass Pass) inline
Definition at line 71 of file LVCompare.h.
Referenced by execute(), and printItem().
dump()
void llvm::logicalview::LVCompare::dump () const inline
Definition at line 80 of file LVCompare.h.
References llvm::dbgs(), and print().
execute()
Error LVCompare::execute (LVReader * ReferenceReader, LVReader * TargetReader)
Definition at line 118 of file LVCompare.cpp.
References llvm::logicalview::Added, llvm::logicalview::LVScope::addElement(), addPassEntry(), llvm::any_of(), llvm::dbgs(), llvm::logicalview::LVReader::doPrint(), llvm::logicalview::Elements, llvm::logicalview::formattedName(), llvm::logicalview::LVScope::getCompileUnitParent(), llvm::logicalview::LVObject::getOffset(), llvm::logicalview::getReader(), llvm::logicalview::LVReader::getScopesRoot(), llvm::logicalview::hexSquareString(), llvm::SmallVectorImpl< T >::insert(), LHS, LLVM_DEBUG, llvm::logicalview::Missing, llvm::logicalview::options(), Pass, llvm::logicalview::LVScope::report(), RHS, llvm::logicalview::LVReader::setCompileUnit(), llvm::logicalview::LVReader::setInstance(), and llvm::Error::success().
getInstance()
LVCompare & LVCompare::getInstance () static
Definition at line 101 of file LVCompare.cpp.
References llvm::outs().
Referenced by llvm::logicalview::getComparator().
getPassTable()
const LVPassTable & llvm::logicalview::LVCompare::getPassTable () const & inline
Definition at line 74 of file LVCompare.h.
operator=()
LVCompare & llvm::logicalview::LVCompare::operator= (const LVCompare &) delete
pop()
void llvm::logicalview::LVCompare::pop () inline
Definition at line 66 of file LVCompare.h.
References llvm::SmallVectorTemplateBase< T, bool >::pop_back().
Referenced by llvm::logicalview::LVScope::report().
print()
void LVCompare::print (raw_ostream & OS) const
Definition at line 427 of file LVCompare.cpp.
References OS.
Referenced by dump().
printItem()
void LVCompare::printItem (LVElement * Element, LVComparePass Pass)
Definition at line 361 of file LVCompare.cpp.
References addPassEntry(), llvm::logicalview::LVObject::getLineNumber(), llvm::logicalview::LVElement::getName(), llvm::logicalview::LVElement::getPathname(), llvm::logicalview::LVObject::kind(), llvm::logicalview::LVObject::lineNumberAsString(), llvm::logicalview::Missing, llvm::logicalview::Name, llvm::logicalview::options(), and llvm::logicalview::LVObject::printAttributes().
Referenced by llvm::logicalview::LVLine::report(), llvm::logicalview::LVScope::report(), llvm::logicalview::LVSymbol::report(), and llvm::logicalview::LVType::report().
push()
void llvm::logicalview::LVCompare::push (LVScope * Scope) inline
Definition at line 65 of file LVCompare.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::logicalview::LVScope::report().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVCompare.h
lib/DebugInfo/LogicalView/Core/LVCompare.cpp