LLVM: llvm::EdgeBundles Class Reference
llvm::EdgeBundles Class Reference
#include "llvm/CodeGen/EdgeBundles.h"
Public Member Functions
EdgeBundles ()
unsigned getBundle (unsigned N, bool Out) const
getBundle - Return the ingoing (Out = false) or outgoing (Out = true) bundle number for basic block N
unsigned getNumBundles () const
getNumBundles - Return the total number of bundles in the CFG.
ArrayRef< unsigned > getBlocks (unsigned Bundle) const
getBlocks - Return an array of blocks that are connected to Bundle.
const MachineFunction * getMachineFunction () const
getMachineFunction - Return the last machine function computed.
void view () const
view - Visualize the annotated bipartite CFG with Graphviz.
Public Member Functions inherited from llvm::MachineFunctionPass
bool doInitialization (Module &) override
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 24 of file EdgeBundles.h.
Constructor & Destructor Documentation
EdgeBundles()
llvm::EdgeBundles::EdgeBundles () inline
Definition at line 37 of file EdgeBundles.h.
Member Function Documentation
getBlocks()
ArrayRef< unsigned > llvm::EdgeBundles::getBlocks (unsigned Bundle) const inline
getBlocks - Return an array of blocks that are connected to Bundle.
Definition at line 47 of file EdgeBundles.h.
References Blocks.
getBundle()
unsigned llvm::EdgeBundles::getBundle (unsigned N, bool Out) const inline
getBundle - Return the ingoing (Out = false) or outgoing (Out = true) bundle number for basic block N
Definition at line 41 of file EdgeBundles.h.
References N.
Referenced by llvm::SpillPlacement::addConstraints(), llvm::SpillPlacement::addLinks(), and llvm::SpillPlacement::addPrefSpill().
getMachineFunction()
const MachineFunction * llvm::EdgeBundles::getMachineFunction () const inline
getMachineFunction - Return the last machine function computed.
Definition at line 50 of file EdgeBundles.h.
getNumBundles()
unsigned llvm::EdgeBundles::getNumBundles () const inline
getNumBundles - Return the total number of bundles in the CFG.
Definition at line 44 of file EdgeBundles.h.
Referenced by llvm::SpillPlacement::iterate(), and llvm::SpillPlacement::prepare().
view()
void EdgeBundles::view () const
view - Visualize the annotated bipartite CFG with Graphviz.
Definition at line 99 of file EdgeBundles.cpp.
References llvm::ViewGraph().
Member Data Documentation
ID
char EdgeBundles::ID = 0 static
Definition at line 36 of file EdgeBundles.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/EdgeBundles.h
lib/CodeGen/EdgeBundles.cpp