LLVM: llvm::orc::LocalIndirectStubsManager< TargetT > Class Template Reference
llvm::orc::LocalIndirectStubsManager< TargetT > Class Template Reference
IndirectStubsManager implementation for the host architecture, e.g.
#include "llvm/ExecutionEngine/Orc/IndirectionUtils.h"
Public Member Functions
Error createStub (StringRef StubName, ExecutorAddr StubAddr, JITSymbolFlags StubFlags) override
Create a single stub with the given name, target address and flags.
Error createStubs (const StubInitsMap &StubInits) override
Create StubInits.size() stubs with the given names, target addresses, and flags.
ExecutorSymbolDef findStub (StringRef Name, bool ExportedStubsOnly) override
Find the stub with the given name.
ExecutorSymbolDef findPointer (StringRef Name) override
Find the implementation-pointer for the stub.
Error updatePointer (StringRef Name, ExecutorAddr NewAddr) override
Change the value of the implementation pointer for the stub.
Public Member Functions inherited from llvm::orc::IndirectStubsManager
virtual ~IndirectStubsManager ()=default
Additional Inherited Members
Public Types inherited from llvm::orc::IndirectStubsManager
using StubInitsMap = StringMap<std::pair<ExecutorAddr, JITSymbolFlags>>
Map type for initializing the manager. See init.
Detailed Description
template<typename TargetT>
class llvm::orc::LocalIndirectStubsManager< TargetT >
IndirectStubsManager implementation for the host architecture, e.g.
OrcX86_64. (See OrcArchitectureSupport.h).
Definition at line 370 of file IndirectionUtils.h.
Member Function Documentation
createStub()
template<typename TargetT > Error llvm::orc::LocalIndirectStubsManager< TargetT >::createStub (StringRef StubName, ExecutorAddr StubAddr, JITSymbolFlags StubFlags) inline override virtual
Create a single stub with the given name, target address and flags.
Implements llvm::orc::IndirectStubsManager.
Definition at line 372 of file IndirectionUtils.h.
References llvm::Error::success().
createStubs()
template<typename TargetT > Error llvm::orc::LocalIndirectStubsManager< TargetT >::createStubs (const StubInitsMap & StubInits) inline override virtual
Create StubInits.size() stubs with the given names, target addresses, and flags.
Implements llvm::orc::IndirectStubsManager.
Definition at line 383 of file IndirectionUtils.h.
References llvm::StringMapImpl::size(), and llvm::Error::success().
findPointer()
template<typename TargetT > ExecutorSymbolDef llvm::orc::LocalIndirectStubsManager< TargetT >::findPointer (StringRef Name) inline override virtual
Find the implementation-pointer for the stub.
Implements llvm::orc::IndirectStubsManager.
Definition at line 410 of file IndirectionUtils.h.
References assert(), llvm::orc::ExecutorAddr::fromPtr(), I, and Name.
findStub()
template<typename TargetT > ExecutorSymbolDef llvm::orc::LocalIndirectStubsManager< TargetT >::findStub (StringRef Name, bool ExportedStubsOnly) inline override virtual
Find the stub with the given name.
If ExportedStubsOnly is true, this will only return a result if the stub's flags indicate that it is exported.
Implements llvm::orc::IndirectStubsManager.
Definition at line 395 of file IndirectionUtils.h.
References assert(), llvm::orc::ExecutorAddr::fromPtr(), I, and Name.
updatePointer()
template<typename TargetT > Error llvm::orc::LocalIndirectStubsManager< TargetT >::updatePointer (StringRef Name, ExecutorAddr NewAddr) inline override virtual
Change the value of the implementation pointer for the stub.
Implements llvm::orc::IndirectStubsManager.
Definition at line 422 of file IndirectionUtils.h.
References assert(), llvm::orc::ExecutorAddr::getValue(), I, Name, and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/IndirectionUtils.h