LLVM: llvm::MDNodeOpsKey Class Reference
llvm::MDNodeOpsKey Class Reference
Structure for hashing arbitrary MDNode operands.
#include "IR/LLVMContextImpl.h"
Public Member Functions
unsigned getHash () const
Protected Member Functions
MDNodeOpsKey (ArrayRef< Metadata * > Ops)
template<class NodeTy >
MDNodeOpsKey (const NodeTy *N, unsigned Offset=0)
template<class NodeTy >
bool compareOps (const NodeTy *RHS, unsigned Offset=0) const
Static Protected Member Functions
static unsigned calculateHash (MDNode *N, unsigned Offset=0)
Detailed Description
Structure for hashing arbitrary MDNode operands.
Definition at line 244 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeOpsKey() [1/2]
llvm::MDNodeOpsKey::MDNodeOpsKey (ArrayRef< Metadata * > Ops) inline protected
Definition at line 250 of file LLVMContextImpl.h.
MDNodeOpsKey() [2/2]
template<class NodeTy > llvm::MDNodeOpsKey::MDNodeOpsKey (const NodeTy * N, unsigned Offset = 0) inline protected
Definition at line 254 of file LLVMContextImpl.h.
Member Function Documentation
calculateHash()
unsigned MDNodeOpsKey::calculateHash (MDNode * N, unsigned Offset = 0) static protected
Definition at line 199 of file LLVMContextImpl.cpp.
References assert(), calculateHash(), llvm::drop_begin(), llvm::hash_combine_range(), N, and llvm::Offset.
Referenced by llvm::MDNodeKeyImpl< GenericDINode >::calculateHash(), llvm::MDNodeKeyImpl< MDTuple >::calculateHash(), and calculateHash().
compareOps()
template<class NodeTy > bool llvm::MDNodeOpsKey::compareOps (const NodeTy * RHS, unsigned Offset = 0) const inline protected
Definition at line 258 of file LLVMContextImpl.h.
References assert(), compareOps(), llvm::ArrayRef< T >::empty(), getHash(), and llvm::Offset.
Referenced by compareOps().
getHash()
unsigned llvm::MDNodeOpsKey::getHash () const inline
Definition at line 280 of file LLVMContextImpl.h.
Referenced by compareOps().
The documentation for this class was generated from the following files:
lib/IR/LLVMContextImpl.h
lib/IR/LLVMContextImpl.cpp