LLVM: llvm::AssumptionAnalysis Class Reference
llvm::AssumptionAnalysis Class Reference
A function analysis which provides an AssumptionCache.
#include "llvm/Analysis/AssumptionCache.h"
Public Types
using Result = AssumptionCache
Public Member Functions
AssumptionCache run (Function &F, FunctionAnalysisManager &)
Public Member Functions inherited from llvm::PassInfoMixin< AssumptionAnalysis >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::AnalysisInfoMixin< AssumptionAnalysis >
static AnalysisKey * ID ()
Returns an opaque, unique ID for this analysis type.
Static Public Member Functions inherited from llvm::PassInfoMixin< AssumptionAnalysis >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A function analysis which provides an AssumptionCache.
This analysis is intended for use with the new pass manager and will vend assumption caches for a given function.
Definition at line 173 of file AssumptionCache.h.
Member Typedef Documentation
Result
using llvm::AssumptionAnalysis::Result = AssumptionCache
Definition at line 179 of file AssumptionCache.h.
Member Function Documentation
run()
AssumptionCache AssumptionAnalysis::run (Function & F, FunctionAnalysisManager & FAM)
Definition at line 221 of file AssumptionCache.cpp.
References llvm::AssumptionCache::AssumptionCache(), F, FAM, and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult().
Referenced by computeHeuristicUnrollFactor(), and llvm::LoadStoreVectorizerPass::run().
The documentation for this class was generated from the following files:
include/llvm/Analysis/AssumptionCache.h
lib/Analysis/AssumptionCache.cpp