LLVM: llvm::MCELFObjectTargetWriter Class Reference
llvm::MCELFObjectTargetWriter Class Reference abstract
#include "llvm/MC/MCELFObjectWriter.h"
Public Member Functions
virtual ~MCELFObjectTargetWriter ()=default
Triple::ObjectFormatType getFormat () const override
virtual unsigned getRelocType (MCContext &Ctx, const MCValue &Target, const MCFixup &Fixup, bool IsPCRel) const =0
virtual bool needsRelocateWithSymbol (const MCValue &Val, const MCSymbol &Sym, unsigned Type) const
virtual void sortRelocs (const MCAssembler &Asm, std::vector< ELFRelocationEntry > &Relocs)
virtual void addTargetSectionFlags (MCContext &Ctx, MCSectionELF &Sec)
uint8_t getRType (uint32_t Type) const
uint8_t getRType2 (uint32_t Type) const
uint8_t getRType3 (uint32_t Type) const
uint8_t getRSsym (uint32_t Type) const
unsigned setRSsym (unsigned Value, unsigned Type) const
virtual MCSectionELF * getMemtagRelocsSection (MCContext &Ctx) const
Accessors
uint8_t getOSABI () const
uint8_t getABIVersion () const
uint16_t getEMachine () const
bool hasRelocationAddend () const
bool is64Bit () const
Public Member Functions inherited from llvm::MCObjectTargetWriter
virtual ~MCObjectTargetWriter ()=default
Static Public Member Functions
static bool classof (const MCObjectTargetWriter *W)
static uint8_t getOSABI (Triple::OSType OSType)
static unsigned setRTypes (unsigned Value1, unsigned Value2, unsigned Value3)
Protected Member Functions
MCELFObjectTargetWriter (bool Is64Bit_, uint8_t OSABI_, uint16_t EMachine_, bool HasRelocationAddend_, uint8_t ABIVersion_=0)
Detailed Description
Definition at line 58 of file MCELFObjectWriter.h.
Constructor & Destructor Documentation
MCELFObjectTargetWriter()
MCELFObjectTargetWriter::MCELFObjectTargetWriter (bool Is64Bit_, uint8_t OSABI_, uint16_t EMachine_, bool HasRelocationAddend_, uint8_t ABIVersion_ = 0) protected
Definition at line 13 of file MCELFObjectTargetWriter.cpp.
~MCELFObjectTargetWriter()
virtual llvm::MCELFObjectTargetWriter::~MCELFObjectTargetWriter () virtual default
Member Function Documentation
addTargetSectionFlags()
void MCELFObjectTargetWriter::addTargetSectionFlags (MCContext & Ctx, MCSectionELF & Sec) virtual
Definition at line 31 of file MCELFObjectTargetWriter.cpp.
classof()
static bool llvm::MCELFObjectTargetWriter::classof (const MCObjectTargetWriter * W) inline static
Definition at line 73 of file MCELFObjectWriter.h.
References llvm::Triple::ELF.
getABIVersion()
uint8_t llvm::MCELFObjectTargetWriter::getABIVersion () const inline
Definition at line 107 of file MCELFObjectWriter.h.
getEMachine()
uint16_t llvm::MCELFObjectTargetWriter::getEMachine () const inline
Definition at line 108 of file MCELFObjectWriter.h.
getFormat()
Triple::ObjectFormatType llvm::MCELFObjectTargetWriter::getFormat () const inline override virtual
Implements llvm::MCObjectTargetWriter.
Definition at line 72 of file MCELFObjectWriter.h.
References llvm::Triple::ELF.
getMemtagRelocsSection()
virtual MCSectionELF * llvm::MCELFObjectTargetWriter::getMemtagRelocsSection (MCContext & Ctx) const inline virtual
Definition at line 152 of file MCELFObjectWriter.h.
getOSABI() [1/2]
uint8_t llvm::MCELFObjectTargetWriter::getOSABI () const inline
Definition at line 106 of file MCELFObjectWriter.h.
Referenced by llvm::createAArch64beAsmBackend(), llvm::createAArch64leAsmBackend(), createARMAsmBackend(), llvm::createHexagonAsmBackend(), llvm::createLoongArchAsmBackend(), llvm::createM68kAsmBackend(), llvm::createMipsELFObjectWriter(), llvm::AVRAsmBackend::createObjectTargetWriter(), llvm::createRISCVAsmBackend(), llvm::createSystemZMCAsmBackend(), llvm::createX86_32AsmBackend(), llvm::createX86_64AsmBackend(), and llvm::createXtensaMCAsmBackend().
getOSABI() [2/2]
static uint8_t llvm::MCELFObjectTargetWriter::getOSABI (Triple::OSType OSType) inline static
Definition at line 77 of file MCELFObjectWriter.h.
References llvm::ELF::ELFOSABI_FREEBSD, llvm::ELF::ELFOSABI_NONE, llvm::ELF::ELFOSABI_OPENBSD, llvm::ELF::ELFOSABI_SOLARIS, llvm::ELF::ELFOSABI_STANDALONE, llvm::Triple::FreeBSD, llvm::Triple::HermitCore, llvm::Triple::OpenBSD, llvm::Triple::PS4, and llvm::Triple::Solaris.
getRelocType()
virtual unsigned llvm::MCELFObjectTargetWriter::getRelocType (MCContext & Ctx, const MCValue & Target, const MCFixup & Fixup, bool IsPCRel) const pure virtual
Implemented in llvm::AVRELFObjectWriter.
getRSsym()
uint8_t llvm::MCELFObjectTargetWriter::getRSsym (uint32_t Type) const inline
Definition at line 134 of file MCELFObjectWriter.h.
References R_SSYM_SHIFT.
getRType()
uint8_t llvm::MCELFObjectTargetWriter::getRType (uint32_t Type) const inline
Definition at line 125 of file MCELFObjectWriter.h.
References R_TYPE_SHIFT.
getRType2()
uint8_t llvm::MCELFObjectTargetWriter::getRType2 (uint32_t Type) const inline
Definition at line 128 of file MCELFObjectWriter.h.
References R_TYPE2_SHIFT.
getRType3()
uint8_t llvm::MCELFObjectTargetWriter::getRType3 (uint32_t Type) const inline
Definition at line 131 of file MCELFObjectWriter.h.
References R_TYPE3_SHIFT.
hasRelocationAddend()
bool llvm::MCELFObjectTargetWriter::hasRelocationAddend () const inline
Definition at line 109 of file MCELFObjectWriter.h.
is64Bit()
bool llvm::MCELFObjectTargetWriter::is64Bit () const inline
Definition at line 110 of file MCELFObjectWriter.h.
needsRelocateWithSymbol()
bool MCELFObjectTargetWriter::needsRelocateWithSymbol (const MCValue & Val, const MCSymbol & Sym, unsigned Type) const virtual
Definition at line 20 of file MCELFObjectTargetWriter.cpp.
setRSsym()
unsigned llvm::MCELFObjectTargetWriter::setRSsym (unsigned Value, unsigned Type) const inline
Definition at line 144 of file MCELFObjectWriter.h.
References R_SSYM_MASK, and R_SSYM_SHIFT.
setRTypes()
static unsigned llvm::MCELFObjectTargetWriter::setRTypes (unsigned Value1, unsigned Value2, unsigned Value3) inline static
Definition at line 139 of file MCELFObjectWriter.h.
References R_TYPE2_SHIFT, R_TYPE3_SHIFT, and R_TYPE_SHIFT.
sortRelocs()
void MCELFObjectTargetWriter::sortRelocs (const MCAssembler & Asm, std::vector< ELFRelocationEntry > & Relocs) virtual
Definition at line 27 of file MCELFObjectTargetWriter.cpp.
The documentation for this class was generated from the following files:
include/llvm/MC/MCELFObjectWriter.h
lib/MC/MCELFObjectTargetWriter.cpp