LLVM: llvm::PredicateInfoAnnotatedWriter Class Reference
llvm::PredicateInfoAnnotatedWriter Class Reference
An assembly annotator class to print PredicateInfo information in comments.
Public Member Functions
PredicateInfoAnnotatedWriter (const PredicateInfo *M)
void emitBasicBlockStartAnnot (const BasicBlock *BB, formatted_raw_ostream &OS) override
emitBasicBlockStartAnnot - This may be implemented to emit a string right after the basic block label, but before the first instruction in the block.
void emitInstructionAnnot (const Instruction *I, formatted_raw_ostream &OS) override
emitInstructionAnnot - This may be implemented to emit a string right before an instruction is emitted.
Public Member Functions inherited from llvm::AssemblyAnnotationWriter
virtual ~AssemblyAnnotationWriter ()
virtual void emitFunctionAnnot (const Function *, formatted_raw_ostream &)
emitFunctionAnnot - This may be implemented to emit a string right before the start of a function.
virtual void emitBasicBlockEndAnnot (const BasicBlock *, formatted_raw_ostream &)
emitBasicBlockEndAnnot - This may be implemented to emit a string right after the basic block.
virtual void printInfoComment (const Value &, formatted_raw_ostream &)
printInfoComment - This may be implemented to emit a comment to the right of an instruction or global value.
Friends
class PredicateInfo
Detailed Description
An assembly annotator class to print PredicateInfo information in comments.
Definition at line 856 of file PredicateInfo.cpp.
Constructor & Destructor Documentation
PredicateInfoAnnotatedWriter()
llvm::PredicateInfoAnnotatedWriter::PredicateInfoAnnotatedWriter (const PredicateInfo * M) inline
Definition at line 861 of file PredicateInfo.cpp.
Member Function Documentation
emitBasicBlockStartAnnot()
void llvm::PredicateInfoAnnotatedWriter::emitBasicBlockStartAnnot (const BasicBlock * , formatted_raw_ostream &) inline override virtual
emitBasicBlockStartAnnot - This may be implemented to emit a string right after the basic block label, but before the first instruction in the block.
Reimplemented from llvm::AssemblyAnnotationWriter.
Definition at line 863 of file PredicateInfo.cpp.
emitInstructionAnnot()
void llvm::PredicateInfoAnnotatedWriter::emitInstructionAnnot (const Instruction * , formatted_raw_ostream &) inline override virtual
emitInstructionAnnot - This may be implemented to emit a string right before an instruction is emitted.
Reimplemented from llvm::AssemblyAnnotationWriter.
Definition at line 866 of file PredicateInfo.cpp.
References llvm::dyn_cast(), llvm::PredicateInfo::getPredicateInfoFor(), I, OS, and PB().
Friends And Related Symbol Documentation
PredicateInfo
friend class PredicateInfo friend
Definition at line 857 of file PredicateInfo.cpp.
The documentation for this class was generated from the following file:
lib/Transforms/Utils/PredicateInfo.cpp