LLVM: llvm::MemoryBufferRef Class Reference
llvm::MemoryBufferRef Class Reference
#include "llvm/Support/MemoryBufferRef.h"
Public Member Functions
MemoryBufferRef ()=default
MemoryBufferRef (const MemoryBuffer &Buffer)
MemoryBufferRef (StringRef Buffer, StringRef Identifier)
StringRef getBuffer () const
StringRef getBufferIdentifier () const
const char * getBufferStart () const
const char * getBufferEnd () const
size_t getBufferSize () const
Friends
bool operator== (const MemoryBufferRef &LHS, const MemoryBufferRef &RHS)
Check pointer identity (not value) of identifier and data.
bool operator!= (const MemoryBufferRef &LHS, const MemoryBufferRef &RHS)
Detailed Description
Definition at line 22 of file MemoryBufferRef.h.
Constructor & Destructor Documentation
MemoryBufferRef() [1/3]
llvm::MemoryBufferRef::MemoryBufferRef () default
MemoryBufferRef() [2/3]
MemoryBufferRef::MemoryBufferRef (const MemoryBuffer & Buffer)
Definition at line 18 of file MemoryBufferRef.cpp.
MemoryBufferRef() [3/3]
llvm::MemoryBufferRef::MemoryBufferRef (StringRef Buffer, StringRef Identifier) inline
Definition at line 29 of file MemoryBufferRef.h.
Member Function Documentation
getBuffer()
StringRef llvm::MemoryBufferRef::getBuffer () const inline
Definition at line 32 of file MemoryBufferRef.h.
Referenced by appendFile(), llvm::object::Archive::Archive(), llvm::object::BigArchive::BigArchive(), llvm::MachO::TextAPIReader::canRead(), computeMemberData(), llvm::orc::ELFDebugObject::Create(), llvm::coverage::BinaryCoverageReader::create(), llvm::object::OffloadBinary::create(), llvm::object::createBinary(), llvm::object::ObjectFile::createELFObjectFile(), llvm::jitlink::createLinkGraphFromCOFFObject(), llvm::jitlink::createLinkGraphFromELFObject(), llvm::jitlink::createLinkGraphFromMachOObject(), llvm::jitlink::createLinkGraphFromObject(), llvm::object::ObjectFile::createMachOObjectFile(), llvm::object::extractOffloadBinaries(), llvm::MachO::TextAPIReader::get(), llvm::orc::ELFDebugObject::getBuffer(), llvm::object::Binary::getData(), llvm::object::COFFImportFile::getExportName(), getSymbolicFile(), and llvm::object::parseCOFFModuleDefinition().
getBufferEnd()
const char * llvm::MemoryBufferRef::getBufferEnd () const inline
Definition at line 36 of file MemoryBufferRef.h.
References llvm::StringRef::end().
Referenced by llvm::embedBitcodeInModule(), llvm::object::ArchiveMemberHeader::getNextChildLoc(), llvm::object::GOFFObjectFile::GOFFObjectFile(), and llvm::parseIR().
getBufferIdentifier()
StringRef llvm::MemoryBufferRef::getBufferIdentifier () const inline
Definition at line 33 of file MemoryBufferRef.h.
Referenced by appendFile(), llvm::jitlink::createLinkGraphFromCOFFObject(), llvm::jitlink::createLinkGraphFromCOFFObject_x86_64(), llvm::jitlink::createLinkGraphFromELFObject(), llvm::jitlink::createLinkGraphFromELFObject_aarch32(), llvm::jitlink::createLinkGraphFromELFObject_aarch64(), llvm::jitlink::createLinkGraphFromELFObject_i386(), llvm::jitlink::createLinkGraphFromELFObject_loongarch(), llvm::jitlink::createLinkGraphFromELFObject_ppc64(), llvm::jitlink::createLinkGraphFromELFObject_riscv(), llvm::jitlink::createLinkGraphFromELFObject_x86_64(), llvm::jitlink::createLinkGraphFromMachOObject(), llvm::orc::ELFDebugObject::finalizeWorkingMemory(), llvm::MachO::TextAPIReader::get(), llvm::getBitcodeFileContents(), llvm::object::Binary::getFileName(), llvm::parseIR(), llvm::MachO::DylibReader::readFile(), and llvm::orc::ELFDebugObject::recordSection().
getBufferSize()
size_t llvm::MemoryBufferRef::getBufferSize () const inline
Definition at line 37 of file MemoryBufferRef.h.
References llvm::StringRef::size().
Referenced by llvm::object::BigArchive::BigArchive(), computeMemberData(), llvm::object::OffloadBinary::create(), llvm::embedBitcodeInModule(), llvm::embedBufferInModule(), llvm::orc::ELFDebugObject::finalizeWorkingMemory(), getGlobalSymtabLocAndSize(), initStream(), llvm::object::Archive::isEmpty(), llvm::line_iterator::line_iterator(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), llvm::msgpack::Writer::write(), llvm::msgpack::Writer::writeExt(), and writeUniversalArchsToStream().
getBufferStart()
const char * llvm::MemoryBufferRef::getBufferStart () const inline
Definition at line 35 of file MemoryBufferRef.h.
References llvm::StringRef::begin().
Referenced by llvm::object::ObjectFile::base(), llvm::object::Archive::child_begin(), llvm::coverage::BinaryCoverageReader::create(), llvm::object::OffloadBinary::create(), llvm::object::ObjectFile::createELFObjectFile(), llvm::embedBitcodeInModule(), llvm::embedBufferInModule(), llvm::orc::ELFDebugObject::finalizeWorkingMemory(), llvm::object::COFFImportFile::getCOFFImportHeader(), getGlobalSymtabLocAndSize(), initStream(), llvm::parseIR(), llvm::object::COFFImportFile::printSymbolName(), llvm::msgpack::Writer::write(), llvm::msgpack::Writer::writeExt(), and writeUniversalArchsToStream().
Friends And Related Symbol Documentation
operator!=
bool operator!= (const MemoryBufferRef & LHS, const MemoryBufferRef & RHS) friend
Definition at line 48 of file MemoryBufferRef.h.
operator==
bool operator== (const MemoryBufferRef & LHS, const MemoryBufferRef & RHS) friend
Check pointer identity (not value) of identifier and data.
Definition at line 40 of file MemoryBufferRef.h.
The documentation for this class was generated from the following files:
include/llvm/Support/MemoryBufferRef.h
lib/Support/MemoryBufferRef.cpp