LLVM: llvm::SystemZTargetStreamer Class Reference
llvm::SystemZTargetStreamer Class Reference
#include "Target/SystemZ/SystemZTargetStreamer.h"
Classes
struct CmpMCInst
Public Types
typedef std::pair< MCInst, const MCSubtargetInfo * > MCInstSTIPair
typedef std::map< MCInstSTIPair, MCSymbol *, CmpMCInst > EXRLT2SymMap
Public Member Functions
SystemZTargetStreamer (MCStreamer &S)
void emitConstantPools () override
virtual void emitMachine (StringRef CPU)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void finish ()
Public Attributes
EXRLT2SymMap EXRLTargets2Sym
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 20 of file SystemZTargetStreamer.h.
Member Typedef Documentation
EXRLT2SymMap
std::map<MCInstSTIPair, MCSymbol *, CmpMCInst> llvm::SystemZTargetStreamer::EXRLT2SymMap
Definition at line 48 of file SystemZTargetStreamer.h.
MCInstSTIPair
std::pair<MCInst, const MCSubtargetInfo *> llvm::SystemZTargetStreamer::MCInstSTIPair
Definition at line 24 of file SystemZTargetStreamer.h.
Constructor & Destructor Documentation
SystemZTargetStreamer()
llvm::SystemZTargetStreamer::SystemZTargetStreamer (MCStreamer & S) inline
Definition at line 22 of file SystemZTargetStreamer.h.
Member Function Documentation
emitConstantPools()
void SystemZTargetStreamer::emitConstantPools () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 192 of file SystemZMCTargetDesc.cpp.
References llvm::MCStreamer::emitInstruction(), llvm::MCStreamer::emitLabel(), EXRLTargets2Sym, llvm::MCStreamer::getContext(), llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getTextSection(), I, llvm::MCTargetStreamer::Streamer, and llvm::MCStreamer::switchSection().
emitMachine()
virtual void llvm::SystemZTargetStreamer::emitMachine (StringRef CPU) inline virtual
Definition at line 53 of file SystemZTargetStreamer.h.
Member Data Documentation
EXRLTargets2Sym
EXRLT2SymMap llvm::SystemZTargetStreamer::EXRLTargets2Sym
Definition at line 49 of file SystemZTargetStreamer.h.
Referenced by emitConstantPools(), and llvm::SystemZAsmPrinter::emitInstruction().
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZTargetStreamer.h
lib/Target/SystemZ/MCTargetDesc/SystemZMCTargetDesc.cpp