LLVM: llvm::StringMap< ValueTy, AllocatorTy > Class Template Reference
llvm::StringMap< ValueTy, AllocatorTy > Class Template Reference
StringMap - This is an unconventional map that is specialized for handling keys that are "strings", which are basically ranges of bytes.
#include "llvm/ADT/StringMap.h"
Inherits llvm::StringMapImpl, and llvm::detail::AllocatorHolder< AllocatorTy >.
Public Types
using MapEntryTy = StringMapEntry<ValueTy>
using key_type = const char *
using mapped_type = ValueTy
using value_type = StringMapEntry<ValueTy>
using size_type = size_t
using const_iterator = StringMapConstIterator<ValueTy>
using iterator = StringMapIterator<ValueTy>
Public Member Functions
StringMap ()
StringMap (unsigned InitialSize)
StringMap (AllocatorTy A)
StringMap (unsigned InitialSize, AllocatorTy A)
StringMap (std::initializer_list< std::pair< StringRef, ValueTy > > List)
StringMap (StringMap &&RHS)
StringMap (const StringMap &RHS)
StringMap & operator= (StringMap RHS)
~StringMap ()
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
iterator_range< StringMapKeyIterator< ValueTy > > keys () const
iterator find (StringRef Key)
iterator find (StringRef Key, uint32_t FullHashValue)
const_iterator find (StringRef Key) const
const_iterator find (StringRef Key, uint32_t FullHashValue) const
ValueTy lookup (StringRef Key) const
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
const ValueTy & at (StringRef Val) const
at - Return the entry for the specified key, or abort if no such entry exists.
ValueTy & operator[] (StringRef Key)
Lookup the ValueTy for the Key, or create a default constructed value if the key is not in the map.
bool contains (StringRef Key) const
contains - Return true if the element is in the map, false otherwise.
size_type count (StringRef Key) const
count - Return 1 if the element is in the map, 0 otherwise.
template<typename InputTy >
size_type count (const StringMapEntry< InputTy > &MapEntry) const
bool operator== (const StringMap &RHS) const
equal - check whether both of the containers are equal.
bool operator!= (const StringMap &RHS) const
bool insert (MapEntryTy *KeyValue)
insert - Insert the specified key/value pair into the map.
std::pair< iterator, bool > insert (std::pair< StringRef, ValueTy > KV)
insert - Inserts the specified key/value pair into the map if the key isn't already in the map.
std::pair< iterator, bool > insert (std::pair< StringRef, ValueTy > KV, uint32_t FullHashValue)
template<typename InputIt >
void insert (InputIt First, InputIt Last)
Inserts elements from range [first, last).
void insert (std::initializer_list< std::pair< StringRef, ValueTy > > List)
Inserts elements from initializer list ilist.
template<typename V >
std::pair< iterator, bool > insert_or_assign (StringRef Key, V &&Val)
Inserts an element or assigns to the current element if the key already exists.
template<typename... ArgsTy>
std::pair< iterator, bool > try_emplace (StringRef Key, ArgsTy &&...Args)
Emplace a new element for the specified key into the map if the key isn't already in the map.
template<typename... ArgsTy>
std::pair< iterator, bool > try_emplace_with_hash (StringRef Key, uint32_t FullHashValue, ArgsTy &&...Args)
void clear ()
void remove (MapEntryTy *KeyValue)
remove - Remove the specified key/value pair from the map, but do not erase it.
void erase (iterator I)
bool erase (StringRef Key)
Public Member Functions inherited from llvm::StringMapImpl
unsigned getNumBuckets () const
unsigned getNumItems () const
bool empty () const
unsigned size () const
void swap (StringMapImpl &Other)
Additional Inherited Members
Static Public Member Functions inherited from llvm::StringMapImpl
static StringMapEntryBase * getTombstoneVal ()
static uint32_t hash (StringRef Key)
Returns the hash value that will be used for the given string.
Static Public Attributes inherited from llvm::StringMapImpl
static constexpr uintptr_t TombstoneIntVal
Protected Member Functions inherited from llvm::StringMapImpl
StringMapImpl (unsigned itemSize)
StringMapImpl (StringMapImpl &&RHS)
StringMapImpl (unsigned InitSize, unsigned ItemSize)
~StringMapImpl ()
unsigned RehashTable (unsigned BucketNo=0)
RehashTable - Grow the table, redistributing values into the buckets with the appropriate mod-of-hashtable-size.
unsigned LookupBucketFor (StringRef Key)
LookupBucketFor - Look up the bucket that the specified string should end up in.
unsigned LookupBucketFor (StringRef Key, uint32_t FullHashValue)
Overload that explicitly takes precomputed hash(Key).
int FindKey (StringRef Key) const
FindKey - Look up the bucket that contains the specified key.
int FindKey (StringRef Key, uint32_t FullHashValue) const
Overload that explicitly takes precomputed hash(Key).
void RemoveKey (StringMapEntryBase *V)
RemoveKey - Remove the specified StringMapEntry from the table, but do not delete it.
StringMapEntryBase * RemoveKey (StringRef Key)
RemoveKey - Remove the StringMapEntry for the specified key from the table, returning it.
void init (unsigned Size)
Allocate the table with the specified number of buckets and otherwise setup the map as empty.
Protected Attributes inherited from llvm::StringMapImpl
StringMapEntryBase ** TheTable = nullptr
unsigned NumBuckets = 0
unsigned NumItems = 0
unsigned NumTombstones = 0
unsigned ItemSize
Detailed Description
template<typename ValueTy, typename AllocatorTy>
class llvm::StringMap< ValueTy, AllocatorTy >
StringMap - This is an unconventional map that is specialized for handling keys that are "strings", which are basically ranges of bytes.
This does some funky memory allocation and hashing things to make it extremely efficient, storing the string data after the value in the map.
Definition at line 21 of file Host.h.
Member Typedef Documentation
const_iterator
template<typename ValueTy , typename AllocatorTy > using llvm::StringMap< ValueTy, AllocatorTy >::const_iterator = StringMapConstIterator<ValueTy>
Definition at line 216 of file StringMap.h.
iterator
template<typename ValueTy , typename AllocatorTy > using llvm::StringMap< ValueTy, AllocatorTy >::iterator = StringMapIterator<ValueTy>
Definition at line 217 of file StringMap.h.
key_type
template<typename ValueTy , typename AllocatorTy > using llvm::StringMap< ValueTy, AllocatorTy >::key_type = const char *
Definition at line 211 of file StringMap.h.
MapEntryTy
template<typename ValueTy , typename AllocatorTy > using llvm::StringMap< ValueTy, AllocatorTy >::MapEntryTy = StringMapEntry<ValueTy>
Definition at line 132 of file StringMap.h.
mapped_type
template<typename ValueTy , typename AllocatorTy > using llvm::StringMap< ValueTy, AllocatorTy >::mapped_type = ValueTy
Definition at line 212 of file StringMap.h.
size_type
template<typename ValueTy , typename AllocatorTy > using llvm::StringMap< ValueTy, AllocatorTy >::size_type = size_t
Definition at line 214 of file StringMap.h.
value_type
template<typename ValueTy , typename AllocatorTy > using llvm::StringMap< ValueTy, AllocatorTy >::value_type = StringMapEntry<ValueTy>
Definition at line 213 of file StringMap.h.
Constructor & Destructor Documentation
StringMap() [1/7]
template<typename ValueTy , typename AllocatorTy > llvm::StringMap< ValueTy, AllocatorTy >::StringMap () inline
Definition at line 134 of file StringMap.h.
StringMap() [2/7]
template<typename ValueTy , typename AllocatorTy > llvm::StringMap< ValueTy, AllocatorTy >::StringMap (unsigned InitialSize) inline explicit
Definition at line 136 of file StringMap.h.
StringMap() [3/7]
template<typename ValueTy , typename AllocatorTy > llvm::StringMap< ValueTy, AllocatorTy >::StringMap (AllocatorTy A) inline explicit
Definition at line 139 of file StringMap.h.
StringMap() [4/7]
template<typename ValueTy , typename AllocatorTy > llvm::StringMap< ValueTy, AllocatorTy >::StringMap (unsigned InitialSize, AllocatorTy A) inline
Definition at line 142 of file StringMap.h.
StringMap() [5/7]
template<typename ValueTy , typename AllocatorTy > llvm::StringMap< ValueTy, AllocatorTy >::StringMap (std::initializer_list< std::pair< StringRef, ValueTy > > List) inline
Definition at line 146 of file StringMap.h.
StringMap() [6/7]
template<typename ValueTy , typename AllocatorTy > llvm::StringMap< ValueTy, AllocatorTy >::StringMap (StringMap< ValueTy, AllocatorTy > && RHS) inline
Definition at line 151 of file StringMap.h.
References llvm::move().
StringMap() [7/7]
template<typename ValueTy , typename AllocatorTy > llvm::StringMap< ValueTy, AllocatorTy >::StringMap (const StringMap< ValueTy, AllocatorTy > & RHS) inline
Definition at line 154 of file StringMap.h.
References E, for(), and I.
~StringMap()
template<typename ValueTy , typename AllocatorTy > llvm::StringMap< ValueTy, AllocatorTy >::~StringMap () inline
Definition at line 195 of file StringMap.h.
References E, and I.
Member Function Documentation
at()
template<typename ValueTy , typename AllocatorTy > const ValueTy & llvm::StringMap< ValueTy, AllocatorTy >::at (StringRef Val) const inline
at - Return the entry for the specified key, or abort if no such entry exists.
Definition at line 262 of file StringMap.h.
References assert(), and llvm::find().
begin() [1/2]
template<typename ValueTy , typename AllocatorTy > iterator llvm::StringMap< ValueTy, AllocatorTy >::begin () inline
Definition at line 219 of file StringMap.h.
Referenced by llvm::codeview::DebugStringTableSubsection::begin(), llvm::DCData::begin(), llvm::RecordStreamer::begin(), llvm::ValueSymbolTable::begin(), llvm::ValueSymbolTable::begin(), llvm::orc::SymbolStringPool::clearDeadEntries(), llvm::jitlink::LinkGraph::external_symbols(), llvm::ExecutionEngine::getGlobalValueAtAddress(), llvm::LLVMContext::getMDKindNames(), LookupNearestOption(), and sortOpts().
begin() [2/2]
template<typename ValueTy , typename AllocatorTy > const_iterator llvm::StringMap< ValueTy, AllocatorTy >::begin () const inline
Definition at line 221 of file StringMap.h.
clear()
template<typename ValueTy , typename AllocatorTy > void llvm::StringMap< ValueTy, AllocatorTy >::clear () inline
Definition at line 394 of file StringMap.h.
References E, and I.
Referenced by llvm::ExecutionEngine::clearAllGlobalMappings(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::symbolize::LLVMSymbolizer::flush(), llvm::MCContext::reset(), llvm::LTOCodeGenerator::setModule(), and llvm::PerTargetMIParsingState::setTarget().
contains()
template<typename ValueTy , typename AllocatorTy > bool llvm::StringMap< ValueTy, AllocatorTy >::contains (StringRef Key) const inline
contains - Return true if the element is in the map, false otherwise.
Definition at line 273 of file StringMap.h.
References llvm::find().
Referenced by llvm::jitlink::LinkGraph::addExternalSymbol(), llvm::Logger::hasAnyObservationForContext(), llvm::jitlink::LinkGraph::makeAbsolute(), llvm::jitlink::LinkGraph::makeDefined(), and llvm::jitlink::LinkGraph::removeExternalSymbol().
count() [1/2]
template<typename ValueTy , typename AllocatorTy > template<typename InputTy > size_type llvm::StringMap< ValueTy, AllocatorTy >::count (const StringMapEntry< InputTy > & MapEntry) const inline
Definition at line 279 of file StringMap.h.
References llvm::count(), and llvm::StringMapEntry< T >::getKey().
count() [2/2]
template<typename ValueTy , typename AllocatorTy > size_type llvm::StringMap< ValueTy, AllocatorTy >::count (StringRef Key) const inline
count - Return 1 if the element is in the map, 0 otherwise.
Definition at line 276 of file StringMap.h.
References contains().
Referenced by llvm::AArch64Subtarget::AArch64Subtarget(), llvm::jitlink::MachOLinkGraphBuilder::addCustomSectionParser(), llvm::DCData::getSuccessorLabel(), HandlePrefixedOrGroupedOption(), llvm::OffloadEntriesInfoManager::hasDeviceGlobalVarEntryInfo(), llvm::ModuleSummaryIndex::hasExportedFunctions(), llvm::AMDGPU::insertWaveSizeFeature(), llvm::RuntimeDyldImpl::loadObjectImpl(), llvm::dwarf_linker::classic::CachedPathResolver::resolve(), llvm::RuntimeDyldImpl::resolveExternalSymbols(), shouldApply(), and WorkloadImportsManager::WorkloadImportsManager().
end() [1/2]
template<typename ValueTy , typename AllocatorTy > iterator llvm::StringMap< ValueTy, AllocatorTy >::end () inline
Definition at line 220 of file StringMap.h.
Referenced by llvm::RuntimeDyldImpl::addRelocationForSymbol(), llvm::RuntimeDyldImpl::applyExternalSymbolRelocations(), llvm::orc::SymbolStringPool::clearDeadEntries(), llvm::codeview::DebugStringTableSubsection::end(), llvm::DCData::end(), llvm::RecordStreamer::end(), llvm::ValueSymbolTable::end(), llvm::ValueSymbolTable::end(), llvm::jitlink::LinkGraph::external_symbols(), llvm::RecordStreamer::flushSymverDirectives(), llvm::ExecutionEngine::getAddressToGlobalIfAvailable(), llvm::ReplayInlineAdvisor::getAdviceImpl(), llvm::PerTargetMIParsingState::getBitmaskTargetFlag(), llvm::PerTargetMIParsingState::getDirectTargetFlag(), llvm::ExecutionEngine::getGlobalValueAtAddress(), llvm::codeview::DebugStringTableSubsection::getIdForString(), llvm::LLVMContext::getMDKindNames(), llvm::PerTargetMIParsingState::getMMOTargetFlag(), llvm::ModuleSummaryIndex::getModule(), llvm::ModuleSummaryIndex::getModule(), llvm::ModuleSummaryIndex::getModuleHash(), llvm::SlotTracker::getModulePathSlot(), llvm::LLVMContextImpl::getOperandBundleTagID(), getOptionPred(), llvm::PerTargetMIParsingState::getRegBank(), llvm::PerTargetMIParsingState::getRegClass(), llvm::PerTargetMIParsingState::getRegMask(), llvm::RuntimeDyldMachO::getRelocationValueRef(), llvm::pdb::DbiStreamBuilder::getSourceFileNameIndex(), llvm::PerTargetMIParsingState::getSubRegIndex(), llvm::RuntimeDyldImpl::getSymbol(), llvm::RuntimeDyldImpl::getSymbolLocalAddress(), llvm::RuntimeDyldImpl::getSymbolSectionID(), llvm::PerTargetMIParsingState::getTargetIndex(), llvm::SlotTracker::getTypeIdCompatibleVtableSlot(), llvm::SlotTracker::getTypeIdSlot(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::isClangModuleRef(), LookupNearestOption(), llvm::PerTargetMIParsingState::parseInstrName(), llvm::Annotations::pointsWithPayload(), llvm::Annotations::pointWithPayload(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), llvm::Annotations::rangesWithPayload(), llvm::Annotations::rangeWithPayload(), readSymbols(), llvm::ImportedFunctionsInliningStatistics::recordInline(), llvm::ExecutionEngineState::RemoveMapping(), sortOpts(), WorkloadImportsManager::WorkloadImportsManager(), and llvm::object::writeImportLibrary().
end() [2/2]
template<typename ValueTy , typename AllocatorTy > const_iterator llvm::StringMap< ValueTy, AllocatorTy >::end () const inline
Definition at line 224 of file StringMap.h.
erase() [1/2]
template<typename ValueTy , typename AllocatorTy > void llvm::StringMap< ValueTy, AllocatorTy >::erase (iterator I) inline
Definition at line 416 of file StringMap.h.
References I.
Referenced by llvm::orc::SymbolStringPool::clearDeadEntries(), llvm::Module::eraseNamedMetadata(), llvm::jitlink::LinkGraph::makeAbsolute(), llvm::jitlink::LinkGraph::makeDefined(), llvm::jitlink::LinkGraph::removeExternalSymbol(), and llvm::ExecutionEngineState::RemoveMapping().
erase() [2/2]
template<typename ValueTy , typename AllocatorTy > bool llvm::StringMap< ValueTy, AllocatorTy >::erase (StringRef Key) inline
Definition at line 422 of file StringMap.h.
References erase(), llvm::find(), and I.
find() [1/4]
template<typename ValueTy , typename AllocatorTy > iterator llvm::StringMap< ValueTy, AllocatorTy >::find (StringRef Key) inline
Definition at line 233 of file StringMap.h.
References llvm::StringMap< ValueTy, AllocatorTy >::find().
Referenced by llvm::RuntimeDyldImpl::addRelocationForSymbol(), llvm::RuntimeDyldImpl::applyExternalSymbolRelocations(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::RecordStreamer::flushSymverDirectives(), llvm::ExecutionEngine::getAddressToGlobalIfAvailable(), llvm::ReplayInlineAdvisor::getAdviceImpl(), llvm::PerTargetMIParsingState::getBitmaskTargetFlag(), llvm::PerTargetMIParsingState::getDirectTargetFlag(), llvm::codeview::DebugStringTableSubsection::getIdForString(), llvm::PerTargetMIParsingState::getMMOTargetFlag(), llvm::ModuleSummaryIndex::getModule(), llvm::ModuleSummaryIndex::getModule(), llvm::ModuleSummaryIndex::getModuleHash(), llvm::SlotTracker::getModulePathSlot(), llvm::LLVMContextImpl::getOperandBundleTagID(), getOptionPred(), llvm::PerTargetMIParsingState::getRegBank(), llvm::PerTargetMIParsingState::getRegClass(), llvm::PerTargetMIParsingState::getRegMask(), llvm::RuntimeDyldMachO::getRelocationValueRef(), llvm::pdb::DbiStreamBuilder::getSourceFileNameIndex(), llvm::PerTargetMIParsingState::getSubRegIndex(), llvm::DCData::getSuccessorLabel(), llvm::RuntimeDyldImpl::getSymbol(), llvm::RuntimeDyldImpl::getSymbolLocalAddress(), llvm::RuntimeDyldImpl::getSymbolSectionID(), llvm::PerTargetMIParsingState::getTargetIndex(), llvm::SlotTracker::getTypeIdCompatibleVtableSlot(), llvm::SlotTracker::getTypeIdSlot(), HandlePrefixedOrGroupedOption(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::isClangModuleRef(), llvm::PerTargetMIParsingState::parseInstrName(), llvm::Annotations::pointsWithPayload(), llvm::Annotations::pointWithPayload(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), llvm::Annotations::rangesWithPayload(), llvm::Annotations::rangeWithPayload(), readSymbols(), llvm::ImportedFunctionsInliningStatistics::recordInline(), llvm::ExecutionEngineState::RemoveMapping(), WorkloadImportsManager::WorkloadImportsManager(), and llvm::object::writeImportLibrary().
find() [2/4]
template<typename ValueTy , typename AllocatorTy > const_iterator llvm::StringMap< ValueTy, AllocatorTy >::find (StringRef Key) const inline
Definition at line 242 of file StringMap.h.
References llvm::StringMap< ValueTy, AllocatorTy >::find().
Referenced by llvm::StringMap< ValueTy, AllocatorTy >::find().
find() [3/4]
template<typename ValueTy , typename AllocatorTy > iterator llvm::StringMap< ValueTy, AllocatorTy >::find (StringRef Key, uint32_t FullHashValue) inline
Definition at line 235 of file StringMap.h.
find() [4/4]
template<typename ValueTy , typename AllocatorTy > const_iterator llvm::StringMap< ValueTy, AllocatorTy >::find (StringRef Key, uint32_t FullHashValue) const inline
Definition at line 244 of file StringMap.h.
insert() [1/5]
template<typename ValueTy , typename AllocatorTy > template<typename InputIt > void llvm::StringMap< ValueTy, AllocatorTy >::insert (InputIt First, InputIt Last) inline
Inserts elements from range [first, last).
If multiple elements in the range have keys that compare equivalent, it is unspecified which element is inserted .
Definition at line 341 of file StringMap.h.
insert() [2/5]
template<typename ValueTy , typename AllocatorTy > bool llvm::StringMap< ValueTy, AllocatorTy >::insert (MapEntryTy * KeyValue) inline
insert - Insert the specified key/value pair into the map.
If the key already exists in the map, return false and ignore the request, otherwise insert it and return true.
Definition at line 308 of file StringMap.h.
References assert(), and llvm::StringMapEntry< T >::getKey().
Referenced by llvm::jitlink::LinkGraph::addExternalSymbol(), llvm::pdb::DbiStreamBuilder::addModuleSourceFile(), llvm::DCData::addSuccessorLabel(), llvm::CodeViewContext::addToStringTable(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::cloneAndEmitDebugFrame(), llvm::MCContext::createELFRelSection(), createIndexMap(), llvm::IRComparer< T >::generateFunctionData(), llvm::NonRelocatableStringpool::getEntry(), llvm::LLVMContext::getMDKindID(), llvm::StringToOffsetTable::GetOrAddStringOffset(), llvm::LLVMContextImpl::getOrInsertBundleTag(), llvm::Module::getOrInsertComdat(), llvm::Module::getUniqueIntrinsicName(), llvm::codeview::DebugStringTableSubsection::insert(), llvm::AMDGPU::insertWaveSizeFeature(), llvm::NonRelocatableStringpool::internString(), llvm::jitlink::LinkGraph::makeExternal(), printMemberHeader(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::registerModuleReference(), llvm::dwarf_linker::classic::CachedPathResolver::resolve(), llvm::RuntimeDyldImpl::resolveExternalSymbols(), llvm::Logger::startObservation(), llvm::MCDwarfLineTableHeader::tryGetFile(), and WorkloadImportsManager::WorkloadImportsManager().
insert() [3/5]
template<typename ValueTy , typename AllocatorTy > void llvm::StringMap< ValueTy, AllocatorTy >::insert (std::initializer_list< std::pair< StringRef, ValueTy > > List) inline
Inserts elements from initializer list ilist.
If multiple elements in the range have keys that compare equivalent, it is unspecified which element is inserted
Definition at line 349 of file StringMap.h.
insert() [4/5]
template<typename ValueTy , typename AllocatorTy > std::pair< iterator, bool > llvm::StringMap< ValueTy, AllocatorTy >::insert (std::pair< StringRef, ValueTy > KV) inline
insert - Inserts the specified key/value pair into the map if the key isn't already in the map.
The bool component of the returned pair is true if and only if the insertion takes place, and the iterator component of the pair points to the element with key equivalent to the key of the pair.
Definition at line 328 of file StringMap.h.
insert() [5/5]
template<typename ValueTy , typename AllocatorTy > std::pair< iterator, bool > llvm::StringMap< ValueTy, AllocatorTy >::insert (std::pair< StringRef, ValueTy > KV, uint32_t FullHashValue) inline
Definition at line 333 of file StringMap.h.
insert_or_assign()
template<typename ValueTy , typename AllocatorTy > template<typename V > std::pair< iterator, bool > llvm::StringMap< ValueTy, AllocatorTy >::insert_or_assign (StringRef Key, V && Val) inline
Inserts an element or assigns to the current element if the key already exists.
The return type is the same as try_emplace.
Definition at line 356 of file StringMap.h.
Referenced by llvm::RuntimeDyldImpl::loadObjectImpl().
keys()
template<typename ValueTy , typename AllocatorTy > iterator_range< StringMapKeyIterator< ValueTy > > llvm::StringMap< ValueTy, AllocatorTy >::keys () const inline
Definition at line 228 of file StringMap.h.
References llvm::make_range().
Referenced by llvm::Annotations::all_points(), llvm::Annotations::all_ranges(), and llvm::InstrProfSymtab::dumpNames().
lookup()
template<typename ValueTy , typename AllocatorTy > ValueTy llvm::StringMap< ValueTy, AllocatorTy >::lookup (StringRef Key) const inline
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
Definition at line 253 of file StringMap.h.
References llvm::find().
Referenced by llvm::MCContext::getInlineAsmLabel(), llvm::Module::getNamedMetadata(), llvm::OpenMPIRBuilder::getOpenMPDefaultSimdAlign(), llvm::PassRegistry::getPassInfo(), llvm::ValueSymbolTable::lookup(), and llvm::MCContext::lookupSymbol().
operator!=()
template<typename ValueTy , typename AllocatorTy > bool llvm::StringMap< ValueTy, AllocatorTy >::operator!= (const StringMap< ValueTy, AllocatorTy > & RHS) const inline
Definition at line 303 of file StringMap.h.
References RHS.
operator=()
template<typename ValueTy , typename AllocatorTy > StringMap & llvm::StringMap< ValueTy, AllocatorTy >::operator= (StringMap< ValueTy, AllocatorTy > RHS) inline
Definition at line 189 of file StringMap.h.
References std::swap().
operator==()
template<typename ValueTy , typename AllocatorTy > bool llvm::StringMap< ValueTy, AllocatorTy >::operator== (const StringMap< ValueTy, AllocatorTy > & RHS) const inline
equal - check whether both of the containers are equal.
Definition at line 284 of file StringMap.h.
References size().
operator[]()
template<typename ValueTy , typename AllocatorTy > ValueTy & llvm::StringMap< ValueTy, AllocatorTy >::operator[] (StringRef Key) inline
Lookup the ValueTy for the Key, or create a default constructed value if the key is not in the map.
Definition at line 270 of file StringMap.h.
remove()
template<typename ValueTy , typename AllocatorTy > void llvm::StringMap< ValueTy, AllocatorTy >::remove (MapEntryTy * KeyValue) inline
remove - Remove the specified key/value pair from the map, but do not erase it.
This aborts if the key is not in the map.
Definition at line 414 of file StringMap.h.
Referenced by llvm::StructType::setName().
try_emplace()
template<typename ValueTy , typename AllocatorTy > template<typename... ArgsTy> std::pair< iterator, bool > llvm::StringMap< ValueTy, AllocatorTy >::try_emplace (StringRef Key, ArgsTy &&... Args) inline
Emplace a new element for the specified key into the map if the key isn't already in the map.
The bool component of the returned pair is true if and only if the insertion takes place, and the iterator component of the pair points to the element with key equivalent to the key of the pair.
Definition at line 368 of file StringMap.h.
Referenced by llvm::StringSet< AllocatorTy >::insert(), and llvm::orc::SymbolStringPool::intern().
try_emplace_with_hash()
template<typename ValueTy , typename AllocatorTy > template<typename... ArgsTy> std::pair< iterator, bool > llvm::StringMap< ValueTy, AllocatorTy >::try_emplace_with_hash (StringRef Key, uint32_t FullHashValue, ArgsTy &&... Args) inline
Definition at line 373 of file StringMap.h.
References assert().
The documentation for this class was generated from the following files:
include/llvm/ADT/StringMap.h
include/llvm/TargetParser/Host.h