LLVM: llvm::GISelAddressing::BaseIndexOffset Class Reference
llvm::GISelAddressing::BaseIndexOffset Class Reference
Helper struct to store a base, index and offset that forms an address.
#include "llvm/CodeGen/GlobalISel/LoadStoreOpt.h"
Public Member Functions
BaseIndexOffset ()=default
Register getBase ()
Register getBase () const
Register getIndex ()
Register getIndex () const
void setBase (Register NewBase)
void setIndex (Register NewIndex)
void setOffset (std::optional< int64_t > NewOff)
bool hasValidOffset () const
int64_t getOffset () const
Detailed Description
Helper struct to store a base, index and offset that forms an address.
Definition at line 38 of file LoadStoreOpt.h.
Constructor & Destructor Documentation
BaseIndexOffset()
llvm::GISelAddressing::BaseIndexOffset::BaseIndexOffset () default
Referenced by llvm::BaseIndexOffset::match().
Member Function Documentation
getBase() [1/2]
Register llvm::GISelAddressing::BaseIndexOffset::getBase () inline
Definition at line 46 of file LoadStoreOpt.h.
Referenced by llvm::GISelAddressing::aliasIsKnownForLoadStore(), and llvm::BaseIndexOffset::computeAliasing().
getBase() [2/2]
Register llvm::GISelAddressing::BaseIndexOffset::getBase () const inline
Definition at line 47 of file LoadStoreOpt.h.
getIndex() [1/2]
Register llvm::GISelAddressing::BaseIndexOffset::getIndex () inline
Definition at line 48 of file LoadStoreOpt.h.
getIndex() [2/2]
Register llvm::GISelAddressing::BaseIndexOffset::getIndex () const inline
Definition at line 49 of file LoadStoreOpt.h.
getOffset()
int64_t llvm::GISelAddressing::BaseIndexOffset::getOffset () const inline
Definition at line 54 of file LoadStoreOpt.h.
Referenced by llvm::GISelAddressing::aliasIsKnownForLoadStore(), and performCONCAT_VECTORSCombine().
hasValidOffset()
bool llvm::GISelAddressing::BaseIndexOffset::hasValidOffset () const inline
Definition at line 53 of file LoadStoreOpt.h.
Referenced by llvm::GISelAddressing::aliasIsKnownForLoadStore(), and llvm::BaseIndexOffset::equalBaseIndex().
setBase()
void llvm::GISelAddressing::BaseIndexOffset::setBase (Register NewBase) inline
Definition at line 50 of file LoadStoreOpt.h.
setIndex()
void llvm::GISelAddressing::BaseIndexOffset::setIndex (Register NewIndex) inline
Definition at line 51 of file LoadStoreOpt.h.
setOffset()
void llvm::GISelAddressing::BaseIndexOffset::setOffset (std::optional< int64_t > NewOff) inline
Definition at line 52 of file LoadStoreOpt.h.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/GlobalISel/LoadStoreOpt.h