LLVM: llvm::FunctionPropertiesUpdater Class Reference
llvm::FunctionPropertiesUpdater Class Reference
Correctly update FunctionPropertiesInfo post-inlining.
#include "llvm/Analysis/FunctionPropertiesAnalysis.h"
Public Member Functions
FunctionPropertiesUpdater (FunctionPropertiesInfo &FPI, CallBase &CB)
void finish (FunctionAnalysisManager &FAM) const
bool finishAndTest (FunctionAnalysisManager &FAM) const
Detailed Description
Correctly update FunctionPropertiesInfo post-inlining.
A FunctionPropertiesUpdater keeps the state necessary for tracking the changes llvm::InlineFunction makes. The idea is that inlining will at most modify a few BBs of the Caller (maybe the entry BB and definitely the callsite BB) and potentially affect exception handling BBs in the case of invoke inlining.
Definition at line 170 of file FunctionPropertiesAnalysis.h.
Constructor & Destructor Documentation
FunctionPropertiesUpdater()
FunctionPropertiesUpdater::FunctionPropertiesUpdater (FunctionPropertiesInfo & FPI, CallBase & CB)
Definition at line 309 of file FunctionPropertiesAnalysis.cpp.
References assert(), llvm::Function::begin(), llvm::dyn_cast(), II, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::succ_begin(), and llvm::succ_end().
Member Function Documentation
finish()
void FunctionPropertiesUpdater::finish (FunctionAnalysisManager & FAM) const
Definition at line 359 of file FunctionPropertiesAnalysis.cpp.
References assert(), llvm::Function::begin(), FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), I, llvm::SetVector< T, Vector, Set, N >::insert(), llvm::SetVector< T, Vector, Set, N >::size(), llvm::succ_begin(), llvm::succ_end(), and llvm::successors().
Referenced by finishAndTest().
finishAndTest()
bool llvm::FunctionPropertiesUpdater::finishAndTest (FunctionAnalysisManager & FAM) const inline
Definition at line 175 of file FunctionPropertiesAnalysis.h.
References FAM, and finish().
The documentation for this class was generated from the following files:
include/llvm/Analysis/FunctionPropertiesAnalysis.h
lib/Analysis/FunctionPropertiesAnalysis.cpp