LLVM: llvm::sandboxir::IRChangeBase Class Reference
llvm::sandboxir::IRChangeBase Class Reference abstract
The base class for IR Change classes.
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
IRChangeBase (Tracker &Parent)
virtual void revert ()=0
This runs when changes get reverted.
virtual void accept ()=0
This runs when changes get accepted.
virtual ~IRChangeBase ()=default
unsigned getIdx () const
\Returns the index of this change by iterating over all changes in the tracker.
void dumpCommon (raw_ostream &OS) const
virtual void dump (raw_ostream &OS) const =0
virtual LLVM_DUMP_METHOD void dump () const =0
Protected Attributes
Tracker & Parent
Friends
raw_ostream & operator<< (raw_ostream &OS, const IRChangeBase &C)
Detailed Description
The base class for IR Change classes.
Definition at line 60 of file Tracker.h.
Constructor & Destructor Documentation
IRChangeBase()
IRChangeBase::IRChangeBase (Tracker & Parent)
Definition at line 18 of file Tracker.cpp.
References assert(), llvm::sandboxir::Tracker::InMiddleOfCreatingChange, llvm::sandboxir::Tracker::isTracking(), and Parent.
~IRChangeBase()
virtual llvm::sandboxir::IRChangeBase::~IRChangeBase () virtual default
Member Function Documentation
accept()
virtual void llvm::sandboxir::IRChangeBase::accept () pure virtual
This runs when changes get accepted.
Implemented in llvm::sandboxir::EraseFromParent, llvm::sandboxir::MoveInstr, llvm::sandboxir::RemoveFromParent, and llvm::sandboxir::UseSet.
dump() [1/2]
virtual LLVM_DUMP_METHOD void llvm::sandboxir::IRChangeBase::dump () const pure virtual
Implemented in llvm::sandboxir::EraseFromParent, llvm::sandboxir::MoveInstr, llvm::sandboxir::RemoveFromParent, and llvm::sandboxir::UseSet.
dump() [2/2]
virtual void llvm::sandboxir::IRChangeBase::dump (raw_ostream & OS) const pure virtual
Implemented in llvm::sandboxir::EraseFromParent, llvm::sandboxir::MoveInstr, llvm::sandboxir::RemoveFromParent, and llvm::sandboxir::UseSet.
dumpCommon()
void llvm::sandboxir::IRChangeBase::dumpCommon (raw_ostream & OS) const inline
Definition at line 75 of file Tracker.h.
References getIdx(), and OS.
Referenced by llvm::sandboxir::EraseFromParent::dump(), llvm::sandboxir::MoveInstr::dump(), llvm::sandboxir::RemoveFromParent::dump(), and llvm::sandboxir::UseSet::dump().
getIdx()
unsigned IRChangeBase::getIdx () const
\Returns the index of this change by iterating over all changes in the tracker.
This is only used for debugging.
Definition at line 28 of file Tracker.cpp.
References llvm::find_if(), Parent, and Ptr.
Referenced by dumpCommon().
revert()
virtual void llvm::sandboxir::IRChangeBase::revert () pure virtual
This runs when changes get reverted.
Implemented in llvm::sandboxir::EraseFromParent, llvm::sandboxir::MoveInstr, llvm::sandboxir::RemoveFromParent, and llvm::sandboxir::UseSet.
Friends And Related Symbol Documentation
operator<<
raw_ostream & operator<< (raw_ostream & OS, const IRChangeBase & C) friend
Definition at line 78 of file Tracker.h.
Member Data Documentation
Parent
Tracker& llvm::sandboxir::IRChangeBase::Parent protected
Definition at line 62 of file Tracker.h.
Referenced by getIdx(), IRChangeBase(), and llvm::sandboxir::EraseFromParent::revert().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp