LLVM: llvm::UnclusteredHighRPStage Class Reference
llvm::UnclusteredHighRPStage Class Reference
#include "Target/AMDGPU/GCNSchedStrategy.h"
Public Member Functions
bool initGCNSchedStage () override
void finalizeGCNSchedStage () override
bool initGCNRegion () override
bool shouldRevertScheduling (unsigned WavesAfter) override
UnclusteredHighRPStage (GCNSchedStageID StageID, GCNScheduleDAGMILive &DAG)
Public Member Functions inherited from llvm::GCNSchedStage
void setupNewBlock ()
void finalizeGCNRegion ()
void checkScheduling ()
ScheduleMetrics getScheduleMetrics (const std::vector< SUnit > &InputSchedule)
ScheduleMetrics getScheduleMetrics (const GCNScheduleDAGMILive &DAG)
unsigned computeSUnitReadyCycle (const SUnit &SU, unsigned CurrCycle, DenseMap< unsigned, unsigned > &ReadyCycles, const TargetSchedModel &SM)
bool isRegionWithExcessRP () const
bool mayCauseSpilling (unsigned WavesAfter)
void revertScheduling ()
void advanceRegion ()
virtual ~GCNSchedStage ()=default
Additional Inherited Members
Protected Member Functions inherited from llvm::GCNSchedStage
GCNSchedStage (GCNSchedStageID StageID, GCNScheduleDAGMILive &DAG)
Protected Attributes inherited from llvm::GCNSchedStage
GCNScheduleDAGMILive & DAG
GCNSchedStrategy & S
MachineFunction & MF
SIMachineFunctionInfo & MFI
const GCNSubtarget & ST
const GCNSchedStageID StageID
MachineBasicBlock * CurrentMBB = nullptr
unsigned RegionIdx = 0
std::vector< MachineInstr * > Unsched
GCNRegPressure PressureBefore
GCNRegPressure PressureAfter
std::vector< std::unique_ptr< ScheduleDAGMutation > > SavedMutations
Detailed Description
Definition at line 333 of file GCNSchedStrategy.h.
Constructor & Destructor Documentation
UnclusteredHighRPStage()
llvm::UnclusteredHighRPStage::UnclusteredHighRPStage (GCNSchedStageID StageID, GCNScheduleDAGMILive & DAG) inline
Definition at line 347 of file GCNSchedStrategy.h.
Member Function Documentation
finalizeGCNSchedStage()
void UnclusteredHighRPStage::finalizeGCNSchedStage () override virtual
Reimplemented from llvm::GCNSchedStage.
Definition at line 876 of file GCNSchedStrategy.cpp.
References llvm::GCNSchedStage::DAG, llvm::dbgs(), llvm::GCNSchedStage::finalizeGCNSchedStage(), LLVM_DEBUG, llvm::ScheduleDAGMI::Mutations, llvm::GCNSchedStage::S, llvm::GCNSchedStage::SavedMutations, llvm::GCNSchedStrategy::SGPRLimitBias, llvm::GCNSchedStage::StageID, and llvm::GCNSchedStrategy::VGPRLimitBias.
initGCNRegion()
bool UnclusteredHighRPStage::initGCNRegion () override virtual
Reimplemented from llvm::GCNSchedStage.
Definition at line 954 of file GCNSchedStrategy.cpp.
References llvm::GCNSchedStage::DAG, llvm::GCNSchedStage::initGCNRegion(), and llvm::GCNSchedStage::RegionIdx.
initGCNSchedStage()
bool UnclusteredHighRPStage::initGCNSchedStage () override virtual
Reimplemented from llvm::GCNSchedStage.
Definition at line 792 of file GCNSchedStrategy.cpp.
References llvm::ScheduleDAGMI::addMutation(), llvm::createIGroupLPDAGMutation(), llvm::GCNSchedStage::DAG, llvm::dbgs(), DisableUnclusterHighRP, llvm::SIMachineFunctionInfo::getMaxWavesPerEU(), llvm::GCNSchedStrategy::HighRPSGPRBias, llvm::GCNSchedStrategy::HighRPVGPRBias, llvm::SIMachineFunctionInfo::increaseOccupancy(), llvm::GCNSchedStage::initGCNSchedStage(), LLVM_DEBUG, llvm::GCNSchedStage::MF, llvm::GCNSchedStage::MFI, llvm::ScheduleDAGMI::Mutations, llvm::BitVector::none(), llvm::AMDGPU::PreRAReentry, llvm::GCNSchedStage::S, llvm::GCNSchedStage::SavedMutations, llvm::GCNSchedStrategy::SGPRLimitBias, and llvm::GCNSchedStrategy::VGPRLimitBias.
shouldRevertScheduling()
bool UnclusteredHighRPStage::shouldRevertScheduling (unsigned WavesAfter) override virtual
Reimplemented from llvm::GCNSchedStage.
Definition at line 1225 of file GCNSchedStrategy.cpp.
References llvm::GCNSchedStage::DAG, llvm::dbgs(), llvm::ScheduleMetrics::getMetric(), llvm::GCNRegPressure::getOccupancy(), llvm::GCNSchedStage::getScheduleMetrics(), llvm::GCNSchedStrategy::getTargetOccupancy(), llvm::GCNSchedStage::isRegionWithExcessRP(), LLVM_DEBUG, llvm::GCNSchedStage::mayCauseSpilling(), llvm::GCNSchedStage::PressureBefore, llvm::GCNSchedStage::S, llvm::ScheduleMetrics::ScaleFactor, ScheduleMetricBias, llvm::GCNSchedStage::shouldRevertScheduling(), llvm::GCNSchedStage::ST, and llvm::ScheduleDAG::SUnits.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNSchedStrategy.h
lib/Target/AMDGPU/GCNSchedStrategy.cpp