LLVM: llvm::gsym::OutputAggregator Class Reference
llvm::gsym::OutputAggregator Class Reference
#include "llvm/DebugInfo/GSYM/OutputAggregator.h"
Public Member Functions
OutputAggregator (raw_ostream *out)
size_t GetNumCategories () const
void Report (StringRef s, std::function< void(raw_ostream &o)> detailCallback)
void EnumerateResults (std::function< void(StringRef, unsigned)> handleCounts) const
raw_ostream * GetOS () const
template<typename T >
OutputAggregator & operator<< (T &&value)
void Merge (const OutputAggregator &other)
Protected Attributes
std::map< std::string, unsigned > Aggregation
raw_ostream * Out
Detailed Description
Definition at line 24 of file OutputAggregator.h.
Constructor & Destructor Documentation
OutputAggregator()
llvm::gsym::OutputAggregator::OutputAggregator (raw_ostream * out) inline
Definition at line 32 of file OutputAggregator.h.
Member Function Documentation
EnumerateResults()
void llvm::gsym::OutputAggregator::EnumerateResults (std::function< void(StringRef, unsigned)> handleCounts) const inline
Definition at line 42 of file OutputAggregator.h.
References Aggregation, llvm::count(), and name.
GetNumCategories()
size_t llvm::gsym::OutputAggregator::GetNumCategories () const inline
Definition at line 34 of file OutputAggregator.h.
References Aggregation.
GetOS()
raw_ostream * llvm::gsym::OutputAggregator::GetOS () const inline
Definition at line 48 of file OutputAggregator.h.
References Out.
Referenced by llvm::gsym::DwarfTransformer::convert(), llvm::gsym::ObjectFileTransformer::convert(), Report(), and llvm::gsym::DwarfTransformer::verify().
Merge()
void llvm::gsym::OutputAggregator::Merge (const OutputAggregator & other) inline
Definition at line 62 of file OutputAggregator.h.
References Aggregation, llvm::count(), and name.
Referenced by llvm::gsym::DwarfTransformer::convert().
operator<<()
template<typename T > OutputAggregator & llvm::gsym::OutputAggregator::operator<< (T && value) inline
Definition at line 53 of file OutputAggregator.h.
References Out.
Report()
void llvm::gsym::OutputAggregator::Report (StringRef s, std::function< void(raw_ostream &o)> detailCallback) inline
Definition at line 36 of file OutputAggregator.h.
References Aggregation, GetOS(), and Out.
Referenced by llvm::gsym::DwarfTransformer::convert(), convertFunctionLineTable(), llvm::gsym::GsymCreator::finalize(), and parseInlineInfo().
Member Data Documentation
Aggregation
std::map<std::string, unsigned> llvm::gsym::OutputAggregator::Aggregation protected
Definition at line 28 of file OutputAggregator.h.
Referenced by EnumerateResults(), GetNumCategories(), Merge(), and Report().
Out
raw_ostream* llvm::gsym::OutputAggregator::Out protected
Definition at line 29 of file OutputAggregator.h.
Referenced by GetOS(), operator<<(), and Report().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/GSYM/OutputAggregator.h