LLVM: llvm::CSKYAsmBackend Class Reference
llvm::CSKYAsmBackend Class Reference
#include "Target/CSKY/MCTargetDesc/CSKYAsmBackend.h"
Public Member Functions
CSKYAsmBackend (const MCSubtargetInfo &STI, const MCTargetOptions &OP)
unsigned int getNumFixupKinds () const override
Get the number of target specific fixup kinds.
void applyFixup (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo *STI) const override
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
const MCFixupKindInfo & getFixupKindInfo (MCFixupKind Kind) const override
Get information on a fixup kind.
bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value) const override
Simple predicate for targets where !Resolved implies requiring relaxation.
void relaxInstruction (MCInst &Inst, const MCSubtargetInfo &STI) const override
Relax the instruction in the given fragment to the next wider instruction.
bool mayNeedRelaxation (const MCInst &Inst, const MCSubtargetInfo &STI) const override
Check whether the given instruction may need relaxation.
bool fixupNeedsRelaxationAdvanced (const MCAssembler &Asm, const MCFixup &Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment *DF, const bool WasForced) const override
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
bool writeNopData (raw_ostream &OS, uint64_t Count, const MCSubtargetInfo *STI) const override
Write an (optimal) nop sequence of Count bytes to the given output.
bool shouldForceRelocation (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, const MCSubtargetInfo *STI) override
Hook to check if a relocation is needed for some target specific reason.
std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const override
Public Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
virtual bool allowAutoPadding () const
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
virtual bool allowEnhancedRelaxation () const
Return true if this target allows an unrelaxable instruction to be emitted into RelaxableFragment and then we can increase its size in a tricky way for optimization.
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual unsigned getMaximumNopSize (const MCSubtargetInfo &STI) const
Returns the maximum size of a nop in bytes on this target.
virtual void finishLayout (MCAssembler const &Asm) const
Give backend an opportunity to finish layout after relaxation.
virtual void handleAssemblerFlag (MCAssemblerFlag Flag)
Handle any target-specific assembler flags. By default, do nothing.
virtual uint64_t generateCompactUnwindEncoding (const MCDwarfFrameInfo *FI, const MCContext *Ctxt) const
Generate the compact unwind encoding for the CFI instructions.
virtual bool isMicroMips (const MCSymbol *Sym) const
Check whether a given symbol has been flagged with MICROMIPS flag.
bool isDarwinCanonicalPersonality (const MCSymbol *Sym) const
virtual std::optional< MCFixupKind > getFixupKind (StringRef Name) const
Map a relocation name used in .reloc to a fixup kind.
virtual bool shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment &AF, unsigned &Size)
Hook to check if extra nop bytes must be inserted for alignment directive.
virtual bool shouldInsertFixupForCodeAlign (MCAssembler &Asm, MCAlignFragment &AF)
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
virtual bool evaluateTargetFixup (const MCAssembler &Asm, const MCFixup &Fixup, const MCFragment *DF, const MCValue &Target, const MCSubtargetInfo *STI, uint64_t &Value, bool &WasForced)
virtual bool handleAddSubRelocations (const MCAssembler &Asm, const MCFragment &F, const MCFixup &Fixup, const MCValue &Target, uint64_t &FixedValue) const
virtual bool relaxDwarfLineAddr (const MCAssembler &Asm, MCDwarfLineAddrFragment &DF, bool &WasRelaxed) const
virtual bool relaxDwarfCFA (const MCAssembler &Asm, MCDwarfCallFrameFragment &DF, bool &WasRelaxed) const
virtual std::pair< bool, bool > relaxLEB128 (const MCAssembler &Asm, MCLEBFragment &LF, int64_t &Value) const
Additional Inherited Members
Public Attributes inherited from llvm::MCAsmBackend
const llvm::endianness Endian
const unsigned RelaxFixupKind
Fixup kind used for linker relaxation. Currently only used by RISC-V.
Protected Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (llvm::endianness Endian, unsigned RelaxFixupKind=MaxFixupKind)
Detailed Description
Definition at line 19 of file CSKYAsmBackend.h.
Constructor & Destructor Documentation
CSKYAsmBackend()
llvm::CSKYAsmBackend::CSKYAsmBackend (const MCSubtargetInfo & STI, const MCTargetOptions & OP) inline
Definition at line 22 of file CSKYAsmBackend.h.
Member Function Documentation
applyFixup()
void CSKYAsmBackend::applyFixup (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo * STI) const override virtual
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
Errors (such as an out of range fixup value) should be reported via Ctx. The STI is present only for fragments of type MCRelaxableFragment and MCDataFragment with hasInstructions() == true.
Implements llvm::MCAsmBackend.
Definition at line 200 of file CSKYAsmBackend.cpp.
References adjustFixupValue(), llvm::alignTo(), assert(), llvm::Data, llvm::FirstLiteralRelocationKind, llvm::FirstTargetFixupKind, Fixup, getFixupKindInfo(), I, llvm::little, and llvm::Offset.
createObjectTargetWriter()
std::unique_ptr< MCObjectTargetWriter > CSKYAsmBackend::createObjectTargetWriter () const override virtual
Implements llvm::MCAsmBackend.
Definition at line 23 of file CSKYAsmBackend.cpp.
References llvm::createCSKYELFObjectWriter().
fixupNeedsRelaxation()
bool CSKYAsmBackend::fixupNeedsRelaxation (const MCFixup & Fixup, uint64_t Value) const override virtual
Simple predicate for targets where !Resolved implies requiring relaxation.
Reimplemented from llvm::MCAsmBackend.
Definition at line 286 of file CSKYAsmBackend.cpp.
fixupNeedsRelaxationAdvanced()
bool CSKYAsmBackend::fixupNeedsRelaxationAdvanced (const MCAssembler & Asm, const MCFixup & Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment * DF, const bool WasForced) const override virtual
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
Reimplemented from llvm::MCAsmBackend.
Definition at line 173 of file CSKYAsmBackend.cpp.
References Fixup, llvm::CSKY::fixup_csky_pcrel_imm10_scale2, llvm::CSKY::fixup_csky_pcrel_imm16_scale2, llvm::CSKY::fixup_csky_pcrel_imm26_scale2, llvm::CSKY::fixup_csky_pcrel_uimm7_scale4, llvm::isShiftedInt(), and llvm::Offset.
getFixupKindInfo()
const MCFixupKindInfo & CSKYAsmBackend::getFixupKindInfo (MCFixupKind Kind) const override virtual
Get information on a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 28 of file CSKYAsmBackend.cpp.
References assert(), llvm::FirstLiteralRelocationKind, llvm::FirstTargetFixupKind, llvm::CSKY::fixup_csky_addr32, llvm::CSKY::fixup_csky_addr_hi16, llvm::CSKY::fixup_csky_addr_lo16, llvm::CSKY::fixup_csky_doffset_imm18, llvm::CSKY::fixup_csky_doffset_imm18_scale2, llvm::CSKY::fixup_csky_doffset_imm18_scale4, llvm::CSKY::fixup_csky_got32, llvm::CSKY::fixup_csky_got_imm18_scale4, llvm::CSKY::fixup_csky_gotoff, llvm::CSKY::fixup_csky_gotpc, llvm::CSKY::fixup_csky_pcrel_imm10_scale2, llvm::CSKY::fixup_csky_pcrel_imm16_scale2, llvm::CSKY::fixup_csky_pcrel_imm18_scale2, llvm::CSKY::fixup_csky_pcrel_imm26_scale2, llvm::CSKY::fixup_csky_pcrel_uimm16_scale4, llvm::CSKY::fixup_csky_pcrel_uimm7_scale4, llvm::CSKY::fixup_csky_pcrel_uimm8_scale4, llvm::CSKY::fixup_csky_plt32, llvm::CSKY::fixup_csky_plt_imm18_scale4, llvm::FK_NONE, llvm::MCFixupKindInfo::FKF_IsAlignedDownTo32Bits, llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::MCAsmBackend::getFixupKindInfo(), getNumFixupKinds(), llvm::CSKY::NumTargetFixupKinds, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size().
Referenced by applyFixup().
getNumFixupKinds()
unsigned int llvm::CSKYAsmBackend::getNumFixupKinds () const inline override virtual
Get the number of target specific fixup kinds.
Implements llvm::MCAsmBackend.
Definition at line 25 of file CSKYAsmBackend.h.
References llvm::CSKY::NumTargetFixupKinds.
Referenced by getFixupKindInfo().
mayNeedRelaxation()
bool CSKYAsmBackend::mayNeedRelaxation (const MCInst & Inst, const MCSubtargetInfo & STI) const override virtual
Check whether the given instruction may need relaxation.
Parameters
Inst - The instruction to test.
STI - The MCSubtargetInfo in effect when the instruction was encoded.
Reimplemented from llvm::MCAsmBackend.
Definition at line 241 of file CSKYAsmBackend.cpp.
References llvm::MCInst::getOpcode(), and llvm::MCSubtargetInfo::hasFeature().
relaxInstruction()
void CSKYAsmBackend::relaxInstruction (MCInst & Inst, const MCSubtargetInfo & STI) const override virtual
Relax the instruction in the given fragment to the next wider instruction.
Parameters
[out] Inst The instruction to relax, which is also the relaxed instruction.
STI the subtarget information for the associated instruction.
Reimplemented from llvm::MCAsmBackend.
Definition at line 291 of file CSKYAsmBackend.cpp.
References llvm::MCInst::addOperand(), llvm::MCInst::dump(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCSubtargetInfo::hasFeature(), LLVM_DEBUG, llvm_unreachable, and llvm::MCInst::setOpcode().
shouldForceRelocation()
bool CSKYAsmBackend::shouldForceRelocation (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target, const MCSubtargetInfo * STI) override virtual
Hook to check if a relocation is needed for some target specific reason.
Reimplemented from llvm::MCAsmBackend.
Definition at line 262 of file CSKYAsmBackend.cpp.
References llvm::FirstLiteralRelocationKind, Fixup, llvm::CSKY::fixup_csky_doffset_imm18, llvm::CSKY::fixup_csky_doffset_imm18_scale2, llvm::CSKY::fixup_csky_doffset_imm18_scale4, llvm::CSKY::fixup_csky_got32, llvm::CSKY::fixup_csky_got_imm18_scale4, llvm::CSKY::fixup_csky_gotoff, llvm::CSKY::fixup_csky_gotpc, llvm::CSKY::fixup_csky_plt32, and llvm::CSKY::fixup_csky_plt_imm18_scale4.
writeNopData()
bool CSKYAsmBackend::writeNopData (raw_ostream & OS, uint64_t Count, const MCSubtargetInfo * STI) const override virtual
Write an (optimal) nop sequence of Count bytes to the given output.
If the target cannot generate such a sequence, it should return an error.
Returns
- True on success.
Implements llvm::MCAsmBackend.
Definition at line 346 of file CSKYAsmBackend.cpp.
References llvm::Count, OS, and llvm::raw_ostream::write_zeros().
The documentation for this class was generated from the following files:
lib/Target/CSKY/MCTargetDesc/CSKYAsmBackend.h
lib/Target/CSKY/MCTargetDesc/CSKYAsmBackend.cpp