LLVM: llvm::jitlink::aarch32::StubsManager_v7 Class Reference
llvm::jitlink::aarch32::StubsManager_v7 Class Reference
Stubs builder for v7 emits non-position-independent Arm and Thumb stubs.
#include "llvm/ExecutionEngine/JITLink/aarch32.h"
Public Member Functions
StubsManager_v7 ()=default
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Implements link-graph traversal via visitExistingEdges().
Static Public Member Functions
static StringRef getSectionName ()
Name of the object file section that will contain all our stubs.
Detailed Description
Stubs builder for v7 emits non-position-independent Arm and Thumb stubs.
Definition at line 380 of file aarch32.h.
Constructor & Destructor Documentation
StubsManager_v7()
llvm::jitlink::aarch32::StubsManager_v7::StubsManager_v7 () default
Member Function Documentation
getSectionName()
static StringRef llvm::jitlink::aarch32::StubsManager_v7::getSectionName () inline static
Name of the object file section that will contain all our stubs.
Definition at line 385 of file aarch32.h.
Referenced by visitEdge().
visitEdge()
bool llvm::jitlink::aarch32::StubsManager_v7::visitEdge (LinkGraph & G, Block * B, Edge & E)
Implements link-graph traversal via visitExistingEdges().
Definition at line 886 of file aarch32.cpp.
References assert(), B, llvm::jitlink::aarch32::createStubArmv7(), llvm::jitlink::aarch32::createStubThumbv7(), llvm::dbgs(), llvm::orc::Exec, llvm::formatv(), G, llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Section::getName(), llvm::Target::getName(), llvm::jitlink::Block::getSection(), getSectionName(), llvm::jitlink::Symbol::getTargetFlags(), llvm::jitlink::aarch32::LastArmRelocation, LLVM_DEBUG, llvm::jitlink::aarch32::needsStub(), llvm::orc::Read, llvm::jitlink::Symbol::setTargetFlags(), and llvm::jitlink::aarch32::ThumbSymbol.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/aarch32.h
lib/ExecutionEngine/JITLink/aarch32.cpp