LLVM: llvm::orc::LocalIndirectStubsInfo< ORCABI > Class Template Reference
llvm::orc::LocalIndirectStubsInfo< ORCABI > Class Template Reference
#include "llvm/ExecutionEngine/Orc/IndirectionUtils.h"
Public Member Functions
LocalIndirectStubsInfo (unsigned NumStubs, sys::OwningMemoryBlock StubsMem)
unsigned getNumStubs () const
void * getStub (unsigned Idx) const
void ** getPtr (unsigned Idx) const
Static Public Member Functions
static Expected< LocalIndirectStubsInfo > create (unsigned MinStubs, unsigned PageSize)
Detailed Description
template<typename ORCABI>
class llvm::orc::LocalIndirectStubsInfo< ORCABI >
Definition at line 312 of file IndirectionUtils.h.
Constructor & Destructor Documentation
LocalIndirectStubsInfo()
template<typename ORCABI > llvm::orc::LocalIndirectStubsInfo< ORCABI >::LocalIndirectStubsInfo (unsigned NumStubs, sys::OwningMemoryBlock StubsMem) inline
Definition at line 314 of file IndirectionUtils.h.
Referenced by llvm::orc::LocalIndirectStubsInfo< ORCABI >::create().
Member Function Documentation
create()
template<typename ORCABI > static Expected< LocalIndirectStubsInfo > llvm::orc::LocalIndirectStubsInfo< ORCABI >::create (unsigned MinStubs, unsigned PageSize) inline static
Definition at line 317 of file IndirectionUtils.h.
References llvm::alignTo(), llvm::sys::Memory::allocateMappedMemory(), assert(), llvm::errorCodeToError(), llvm::orc::ExecutorAddr::fromPtr(), llvm::orc::getIndirectStubsBlockSizes(), llvm::orc::LocalIndirectStubsInfo< ORCABI >::LocalIndirectStubsInfo(), llvm::sys::Memory::MF_EXEC, llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, PageSize, and llvm::sys::Memory::protectMappedMemory().
getNumStubs()
template<typename ORCABI > unsigned llvm::orc::LocalIndirectStubsInfo< ORCABI >::getNumStubs () const inline
Definition at line 350 of file IndirectionUtils.h.
getPtr()
template<typename ORCABI > void ** llvm::orc::LocalIndirectStubsInfo< ORCABI >::getPtr (unsigned Idx) const inline
Definition at line 356 of file IndirectionUtils.h.
References llvm::sys::OwningMemoryBlock::base().
getStub()
template<typename ORCABI > void * llvm::orc::LocalIndirectStubsInfo< ORCABI >::getStub (unsigned Idx) const inline
Definition at line 352 of file IndirectionUtils.h.
References llvm::sys::OwningMemoryBlock::base().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/IndirectionUtils.h