LLVM: llvm::VPHeaderPHIRecipe Class Reference
llvm::VPHeaderPHIRecipe Class Reference abstract
A pure virtual base class for all recipes modeling header phis, including phis for first order recurrences, pointer inductions and reductions.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
~VPHeaderPHIRecipe () override=default
void execute (VPTransformState &State) override=0
Generate the phi nodes.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override=0
Print the recipe.
VPValue * getStartValue ()
Returns the start value of the phi, if one is set.
VPValue * getStartValue () const
void setStartValue (VPValue *V)
Update the start value of the recipe.
virtual VPValue * getBackedgeValue ()
Returns the incoming value from the loop backedge.
virtual VPRecipeBase & getBackedgeRecipe ()
Returns the backedge value as a recipe.
Public Member Functions inherited from llvm::VPSingleDefRecipe
template<typename IterT >
VPSingleDefRecipe (const unsigned char SC, IterT Operands, DebugLoc DL={})
VPSingleDefRecipe (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
template<typename IterT >
VPSingleDefRecipe (const unsigned char SC, IterT Operands, Value *UV, DebugLoc DL={})
virtual VPSingleDefRecipe * clone () override=0
Clone the current recipe.
Instruction * getUnderlyingInstr ()
Returns the underlying instruction.
const Instruction * getUnderlyingInstr () const
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
template<typename IterT >
VPRecipeBase (const unsigned char SC, iterator_range< IterT > Operands, DebugLoc DL={})
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
virtual InstructionCost cost (ElementCount VF, VPCostContext &Ctx)
Return the cost of this recipe, taking into account if the cost computation should be skipped and the ForceTargetInstructionCost flag.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
DebugLoc getDebugLoc () const
Returns the debug location of the recipe.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >, ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent () const
ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent ()
void setParent (ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty *Parent)
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
VPUserID getVPUserID () const
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
virtual bool onlyFirstLaneUsed (const VPValue *Op) const
Returns true if the VPUser only uses the first lane of operand Op.
virtual bool onlyFirstPartUsed (const VPValue *Op) const
Returns true if the VPUser only uses the first part of operand Op.
Public Member Functions inherited from llvm::VPValue
Value * getUnderlyingValue () const
Return the underlying Value attached to this VPValue.
VPValue (Value *UV=nullptr)
Create a live-in VPValue.
VPValue (VPDef *Def, Value *UV=nullptr)
Create a VPValue for a Def which is a subclass of VPValue.
VPValue (Value *UV, VPDef *Def)
Create a VPValue for a Def which defines multiple values.
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser ()
Returns true if the value has more than one unique user.
void replaceAllUsesWith (VPValue *New)
void replaceUsesWithIf (VPValue *New, llvm::function_ref< bool(VPUser &U, unsigned Idx)> ShouldReplace)
Go through the uses list for this VPValue and make each use point to New if the callback ShouldReplace returns true for the given use specified by a pair of (VPUser, the use index).
VPRecipeBase * getDefiningRecipe ()
Returns the recipe defining this VPValue or nullptr if it is not defined by a recipe, i.e.
const VPRecipeBase * getDefiningRecipe () const
bool hasDefiningRecipe () const
Returns true if this VPValue is defined by a recipe.
bool isLiveIn () const
Returns true if this VPValue is a live-in, i.e. defined outside the VPlan.
Value * getLiveInIRValue ()
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
const Value * getLiveInIRValue () const
bool isDefinedOutsideVectorRegions () const
Returns true if the VPValue is defined outside any vector regions, i.e.
void setUnderlyingValue (Value *Val)
Static Public Member Functions
static bool classof (const VPRecipeBase *B)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPValue *V)
Static Public Member Functions inherited from llvm::VPSingleDefRecipe
static bool classof (const VPRecipeBase *R)
static bool classof (const VPUser *U)
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Protected Member Functions
VPHeaderPHIRecipe (unsigned char VPDefID, Instruction *UnderlyingInstr, VPValue *Start=nullptr, DebugLoc DL={})
Protected Member Functions inherited from llvm::VPRecipeBase
InstructionCost computeCost (ElementCount VF, VPCostContext &Ctx) const
Compute the cost of this recipe using the legacy cost model and the underlying instructions.
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands, VPUserID ID)
VPUser (std::initializer_list< VPValue * > Operands, VPUserID ID)
template<typename IterT >
VPUser (iterator_range< IterT > Operands, VPUserID ID)
Protected Member Functions inherited from llvm::VPValue
VPValue (const unsigned char SC, Value *UV=nullptr, VPDef *Def=nullptr)
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
enum class VPUserID { Recipe , LiveOut }
Subclass identifier (for isa/dyn_cast).
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Types inherited from llvm::VPValue
enum { VPValueSC , VPVRecipeSC }
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Attributes inherited from llvm::VPValue
Value * UnderlyingVal
VPDef * Def
Pointer to the VPDef that defines this VPValue.
Detailed Description
A pure virtual base class for all recipes modeling header phis, including phis for first order recurrences, pointer inductions and reductions.
The start value is the first operand of the recipe and the incoming value from the backedge is the second operand.
Inductions are modeled using the following sub-classes:
VPCanonicalIVPHIRecipe: Canonical scalar induction of the vector loop, starting at a specified value (zero for the main vector loop, the resume value for the epilogue vector loop) and stepping by 1. The induction controls exiting of the vector loop by comparing against the vector trip count. Produces a single scalar PHI for the induction value per iteration.
VPWidenIntOrFpInductionRecipe: Generates vector values for integer and floating point inductions with arbitrary start and step values. Produces a vector PHI per-part.
VPDerivedIVRecipe: Converts the canonical IV value to the corresponding value of an IV with different start and step values. Produces a single scalar value per iteration
VPScalarIVStepsRecipe: Generates scalar values per-lane based on a canonical or derived induction.
VPWidenPointerInductionRecipe: Generate vector and scalar values for a pointer induction. Produces either a vector PHI per-part or scalar values per-lane based on the canonical induction.
Definition at line 1711 of file VPlan.h.
Constructor & Destructor Documentation
VPHeaderPHIRecipe()
llvm::VPHeaderPHIRecipe::VPHeaderPHIRecipe (unsigned char VPDefID, Instruction * UnderlyingInstr, VPValue * Start = nullptr, DebugLoc DL = {}) inline protected
Definition at line 1713 of file VPlan.h.
~VPHeaderPHIRecipe()
llvm::VPHeaderPHIRecipe::~VPHeaderPHIRecipe () override default
Member Function Documentation
classof() [1/2]
static bool llvm::VPHeaderPHIRecipe::classof (const VPRecipeBase * B) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 1724 of file VPlan.h.
References B.
classof() [2/2]
static bool llvm::VPHeaderPHIRecipe::classof (const VPValue * V) inline static
Definition at line 1728 of file VPlan.h.
References B.
execute()
void llvm::VPHeaderPHIRecipe::execute (VPTransformState & State) override pure virtual
Generate the phi nodes.
Implements llvm::VPRecipeBase.
Implemented in llvm::VPActiveLaneMaskPHIRecipe, llvm::VPCanonicalIVPHIRecipe, llvm::VPEVLBasedIVPHIRecipe, llvm::VPFirstOrderRecurrencePHIRecipe, llvm::VPReductionPHIRecipe, llvm::VPWidenIntOrFpInductionRecipe, and llvm::VPWidenPointerInductionRecipe.
getBackedgeRecipe()
virtual VPRecipeBase & llvm::VPHeaderPHIRecipe::getBackedgeRecipe () inline virtual
Returns the backedge value as a recipe.
The backedge value is guaranteed to be a recipe.
Reimplemented in llvm::VPWidenIntOrFpInductionRecipe.
Definition at line 1761 of file VPlan.h.
References getBackedgeValue(), and llvm::VPValue::getDefiningRecipe().
getBackedgeValue()
virtual VPValue * llvm::VPHeaderPHIRecipe::getBackedgeValue () inline virtual
Returns the incoming value from the loop backedge.
Reimplemented in llvm::VPWidenIntOrFpInductionRecipe.
Definition at line 1755 of file VPlan.h.
References llvm::VPUser::getOperand().
Referenced by llvm::VPCanonicalIVPHIRecipe::clone(), llvm::VPReductionPHIRecipe::clone(), and getBackedgeRecipe().
getStartValue() [1/2]
VPValue * llvm::VPHeaderPHIRecipe::getStartValue () inline
Returns the start value of the phi, if one is set.
Definition at line 1744 of file VPlan.h.
References llvm::VPUser::getNumOperands(), and llvm::VPUser::getOperand().
Referenced by llvm::VPWidenIntOrFpInductionRecipe::clone(), llvm::VPWidenPointerInductionRecipe::execute(), llvm::VPCanonicalIVPHIRecipe::getScalarType(), and llvm::VPlanTransforms::optimizeForVFAndUF().
getStartValue() [2/2]
VPValue * llvm::VPHeaderPHIRecipe::getStartValue () const inline
Definition at line 1747 of file VPlan.h.
References llvm::VPUser::getNumOperands(), and llvm::VPUser::getOperand().
print()
void llvm::VPHeaderPHIRecipe::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override pure virtual
Print the recipe.
Implements llvm::VPDef.
Implemented in llvm::VPActiveLaneMaskPHIRecipe, llvm::VPCanonicalIVPHIRecipe, llvm::VPEVLBasedIVPHIRecipe, llvm::VPFirstOrderRecurrencePHIRecipe, llvm::VPReductionPHIRecipe, llvm::VPWidenIntOrFpInductionRecipe, and llvm::VPWidenPointerInductionRecipe.
setStartValue()
void llvm::VPHeaderPHIRecipe::setStartValue (VPValue * V) inline
Update the start value of the recipe.
Definition at line 1752 of file VPlan.h.
References llvm::VPUser::setOperand().
The documentation for this class was generated from the following file:
lib/Transforms/Vectorize/VPlan.h