LLVM: llvm::sandboxir::Use Class Reference
llvm::sandboxir::Use Class Reference
Represents a Def-use/Use-def edge in SandboxIR.
#include "llvm/SandboxIR/Use.h"
Public Member Functions
operator Value * () const
Value * get () const
void set (Value *V)
class User * getUser () const
unsigned getOperandNo () const
Context * getContext () const
bool operator== (const Use &Other) const
bool operator!= (const Use &Other) const
void dump (raw_ostream &OS) const
void dump () const
Friends
class Value
class User
class OperandUseIterator
class UserUseIterator
Detailed Description
Represents a Def-use/Use-def edge in SandboxIR.
NOTE: Unlike llvm::Use, this is not an integral part of the use-def chains. It is also not uniqued and is currently passed by value, so you can have more than one sandboxir::Use objects for the same use-def edge.
Definition at line 29 of file Use.h.
Member Function Documentation
dump() [1/2]
void Use::dump () const
Definition at line 52 of file SandboxIR.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void Use::dump (raw_ostream & OS) const
Definition at line 24 of file SandboxIR.cpp.
References getOperandNo(), and OS.
get()
Value * Use::get () const
Definition at line 17 of file SandboxIR.cpp.
Referenced by llvm::sandboxir::EraseFromParent::EraseFromParent(), llvm::sandboxir::User::getOperand(), operator Value *(), and llvm::sandboxir::User::replaceUsesOfWith().
getContext()
Context * llvm::sandboxir::Use::getContext () const inline
Definition at line 50 of file Use.h.
getOperandNo()
unsigned Use::getOperandNo () const
Definition at line 21 of file SandboxIR.cpp.
References llvm::sandboxir::User::getUseOperandNo().
Referenced by dump(), and llvm::sandboxir::OperandUseIterator::operator++().
getUser()
class User * llvm::sandboxir::Use::getUser () const inline
Definition at line 48 of file Use.h.
Referenced by llvm::sandboxir::Value::UseToUser::operator()(), llvm::sandboxir::OperandUseIterator::operator++(), and llvm::sandboxir::User::verifyUserOfLLVMUse().
operator Value *()
llvm::sandboxir::Use::operator Value * () const inline
Definition at line 45 of file Use.h.
References get().
operator!=()
bool llvm::sandboxir::Use::operator!= (const Use & Other) const inline
Definition at line 55 of file Use.h.
References llvm::Other.
operator==()
bool llvm::sandboxir::Use::operator== (const Use & Other) const inline
Definition at line 51 of file Use.h.
References assert(), and llvm::Other.
set()
void Use::set (Value * V)
Definition at line 19 of file SandboxIR.cpp.
Friends And Related Symbol Documentation
OperandUseIterator
friend class OperandUseIterator friend
Definition at line 41 of file Use.h.
User
friend class User friend
Definition at line 40 of file Use.h.
UserUseIterator
friend class UserUseIterator friend
Definition at line 42 of file Use.h.
Value
friend class Value friend
Definition at line 39 of file Use.h.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Use.h
lib/SandboxIR/SandboxIR.cpp