LLVM: llvm::XtensaConstantPoolJumpTable Class Reference
llvm::XtensaConstantPoolJumpTable Class Reference
XtensaConstantPoolJumpTable - Xtensa-specific constantpool values for Jump Table symbols.
#include "Target/Xtensa/XtensaConstantPoolValue.h"
Public Member Functions
unsigned getIndex () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
bool hasSameValue (XtensaConstantPoolValue *ACPV) override
hasSameValue - Return true if this Xtensa constpool value can share the same constantpool entry as another Xtensa constpool value.
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const XtensaConstantPoolJumpTable *A) const
Public Member Functions inherited from llvm::XtensaConstantPoolValue
~XtensaConstantPoolValue () override
XtensaCP::XtensaCPModifier getModifier () const
bool hasModifier () const
StringRef getModifierText () const
unsigned getLabelId () const
void setLabelId (unsigned ID)
bool isExtSymbol () const
bool isBlockAddress () const
bool isMachineBasicBlock () const
bool isJumpTable () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
bool equals (const XtensaConstantPoolValue *A) const
void print (raw_ostream &O) const override
print - Implement operator<<
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
virtual unsigned getSizeInBytes (const DataLayout &DL) const
Static Public Member Functions
static XtensaConstantPoolJumpTable * Create (LLVMContext &C, unsigned Idx)
static bool classof (const XtensaConstantPoolValue *ACPV)
Additional Inherited Members
Protected Member Functions inherited from llvm::XtensaConstantPoolValue
XtensaConstantPoolValue (Type *Ty, unsigned ID, XtensaCP::XtensaCPKind Kind, XtensaCP::XtensaCPModifier Modifier=XtensaCP::no_modifier)
XtensaConstantPoolValue (LLVMContext &C, unsigned id, XtensaCP::XtensaCPKind Kind, XtensaCP::XtensaCPModifier Modifier=XtensaCP::no_modifier)
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, Align Alignment)
Detailed Description
XtensaConstantPoolJumpTable - Xtensa-specific constantpool values for Jump Table symbols.
Definition at line 231 of file XtensaConstantPoolValue.h.
Member Function Documentation
addSelectionDAGCSEId()
void XtensaConstantPoolJumpTable::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 202 of file XtensaConstantPoolValue.cpp.
classof()
static bool llvm::XtensaConstantPoolJumpTable::classof (const XtensaConstantPoolValue * ACPV) inline static
Definition at line 252 of file XtensaConstantPoolValue.h.
References llvm::XtensaConstantPoolValue::isJumpTable().
Create()
XtensaConstantPoolJumpTable * XtensaConstantPoolJumpTable::Create (LLVMContext & C, unsigned Idx) static
Definition at line 184 of file XtensaConstantPoolValue.cpp.
References llvm::CallingConv::C.
equals()
bool llvm::XtensaConstantPoolJumpTable::equals (const XtensaConstantPoolJumpTable * A) const inline
Definition at line 256 of file XtensaConstantPoolValue.h.
References A, and llvm::XtensaConstantPoolValue::equals().
getExistingMachineCPValue()
int XtensaConstantPoolJumpTable::getExistingMachineCPValue (MachineConstantPool * CP, Align Alignment) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 189 of file XtensaConstantPoolValue.cpp.
References llvm::XtensaConstantPoolValue::getExistingMachineCPValueImpl().
getIndex()
unsigned llvm::XtensaConstantPoolJumpTable::getIndex () const inline
Definition at line 239 of file XtensaConstantPoolValue.h.
hasSameValue()
bool XtensaConstantPoolJumpTable::hasSameValue (XtensaConstantPoolValue * ACPV) override virtual
hasSameValue - Return true if this Xtensa constpool value can share the same constantpool entry as another Xtensa constpool value.
Reimplemented from llvm::XtensaConstantPoolValue.
Definition at line 195 of file XtensaConstantPoolValue.cpp.
References llvm::dyn_cast(), and llvm::XtensaConstantPoolValue::hasSameValue().
print()
void XtensaConstantPoolJumpTable::print (raw_ostream & O) const override virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Definition at line 204 of file XtensaConstantPoolValue.cpp.
References llvm::XtensaConstantPoolValue::print().
The documentation for this class was generated from the following files:
lib/Target/Xtensa/XtensaConstantPoolValue.h
lib/Target/Xtensa/XtensaConstantPoolValue.cpp