LLVM: llvm::codeview::MergingTypeTableBuilder Class Reference
llvm::codeview::MergingTypeTableBuilder Class Reference
#include "llvm/DebugInfo/CodeView/MergingTypeTableBuilder.h"
Public Member Functions
MergingTypeTableBuilder (BumpPtrAllocator &Storage)
~MergingTypeTableBuilder ()
std::optional< TypeIndex > getFirst () override
std::optional< TypeIndex > getNext (TypeIndex Prev) override
CVType getType (TypeIndex Index) override
StringRef getTypeName (TypeIndex Index) override
bool contains (TypeIndex Index) override
uint32_t size () override
uint32_t capacity () override
bool replaceType (TypeIndex &Index, CVType Data, bool Stabilize) override
void reset ()
TypeIndex nextTypeIndex () const
BumpPtrAllocator & getAllocator ()
ArrayRef< ArrayRef< uint8_t > > records () const
TypeIndex insertRecordAs (hash_code Hash, ArrayRef< uint8_t > &Record)
TypeIndex insertRecordBytes (ArrayRef< uint8_t > &Record)
TypeIndex insertRecord (ContinuationRecordBuilder &Builder)
template<typename T >
TypeIndex writeLeafType (T &Record)
Public Member Functions inherited from llvm::codeview::TypeCollection
virtual ~TypeCollection ()=default
bool empty ()
template<typename TFunc >
void ForEachRecord (TFunc Func)
Detailed Description
Definition at line 28 of file MergingTypeTableBuilder.h.
Constructor & Destructor Documentation
MergingTypeTableBuilder()
MergingTypeTableBuilder::MergingTypeTableBuilder (BumpPtrAllocator & Storage) explicit
Definition at line 28 of file MergingTypeTableBuilder.cpp.
~MergingTypeTableBuilder()
MergingTypeTableBuilder::~MergingTypeTableBuilder () default
Member Function Documentation
capacity()
uint32_t MergingTypeTableBuilder::capacity () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 66 of file MergingTypeTableBuilder.cpp.
contains()
bool MergingTypeTableBuilder::contains (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 57 of file MergingTypeTableBuilder.cpp.
getAllocator()
BumpPtrAllocator & llvm::codeview::MergingTypeTableBuilder::getAllocator () inline
Definition at line 61 of file MergingTypeTableBuilder.h.
getFirst()
std::optional< TypeIndex > MergingTypeTableBuilder::getFirst () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 35 of file MergingTypeTableBuilder.cpp.
References llvm::codeview::TypeCollection::empty(), and llvm::codeview::TypeIndex::FirstNonSimpleIndex.
getNext()
std::optional< TypeIndex > MergingTypeTableBuilder::getNext (TypeIndex Prev) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 42 of file MergingTypeTableBuilder.cpp.
References nextTypeIndex().
getType()
CVType MergingTypeTableBuilder::getType (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 48 of file MergingTypeTableBuilder.cpp.
References Type.
getTypeName()
StringRef MergingTypeTableBuilder::getTypeName (TypeIndex Index) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 53 of file MergingTypeTableBuilder.cpp.
References llvm_unreachable.
insertRecord()
TypeIndex MergingTypeTableBuilder::insertRecord (ContinuationRecordBuilder & Builder)
Definition at line 112 of file MergingTypeTableBuilder.cpp.
References assert(), llvm::codeview::C, insertRecordBytes(), and nextTypeIndex().
insertRecordAs()
TypeIndex MergingTypeTableBuilder::insertRecordAs (hash_code Hash, ArrayRef< uint8_t > & Record)
Definition at line 84 of file MergingTypeTableBuilder.cpp.
References assert(), nextTypeIndex(), stabilize(), and llvm::codeview::TypeIndex::toArrayIndex().
Referenced by insertRecordBytes().
insertRecordBytes()
TypeIndex MergingTypeTableBuilder::insertRecordBytes (ArrayRef< uint8_t > & Record)
Definition at line 107 of file MergingTypeTableBuilder.cpp.
References llvm::hash_value(), and insertRecordAs().
Referenced by insertRecord(), and writeLeafType().
nextTypeIndex()
TypeIndex MergingTypeTableBuilder::nextTypeIndex () const
Definition at line 24 of file MergingTypeTableBuilder.cpp.
References llvm::codeview::TypeIndex::fromArrayIndex().
Referenced by getNext(), insertRecord(), and insertRecordAs().
records()
ArrayRef< ArrayRef< uint8_t > > MergingTypeTableBuilder::records () const
Definition at line 68 of file MergingTypeTableBuilder.cpp.
replaceType()
bool MergingTypeTableBuilder::replaceType (TypeIndex & Index, CVType Data, bool Stabilize) override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 121 of file MergingTypeTableBuilder.cpp.
References assert(), llvm::Data, llvm::hash_value(), and stabilize().
reset()
void MergingTypeTableBuilder::reset ()
Definition at line 72 of file MergingTypeTableBuilder.cpp.
size()
uint32_t MergingTypeTableBuilder::size () override virtual
Implements llvm::codeview::TypeCollection.
Definition at line 64 of file MergingTypeTableBuilder.cpp.
writeLeafType()
template<typename T > TypeIndex llvm::codeview::MergingTypeTableBuilder::writeLeafType (T & Record) inline
Definition at line 69 of file MergingTypeTableBuilder.h.
References llvm::Data, insertRecordBytes(), and llvm::codeview::SimpleTypeSerializer::serialize().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/MergingTypeTableBuilder.h
lib/DebugInfo/CodeView/MergingTypeTableBuilder.cpp