LLVM: llvm::XtensaConstantPoolValue Class Reference
llvm::XtensaConstantPoolValue Class Reference
XtensaConstantPoolValue - Xtensa specific constantpool value.
#include "Target/Xtensa/XtensaConstantPoolValue.h"
Public Member Functions
~XtensaConstantPoolValue () override
XtensaCP::XtensaCPModifier getModifier () const
bool hasModifier () const
StringRef getModifierText () const
unsigned getLabelId () const
void setLabelId (unsigned ID)
bool isExtSymbol () const
bool isBlockAddress () const
bool isMachineBasicBlock () const
bool isJumpTable () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
virtual bool hasSameValue (XtensaConstantPoolValue *ACPV)
hasSameValue - Return true if this Xtensa constpool value can share the same constantpool entry as another Xtensa constpool value.
bool equals (const XtensaConstantPoolValue *A) const
void print (raw_ostream &O) const override
print - Implement operator<<
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
virtual unsigned getSizeInBytes (const DataLayout &DL) const
Protected Member Functions
XtensaConstantPoolValue (Type *Ty, unsigned ID, XtensaCP::XtensaCPKind Kind, XtensaCP::XtensaCPModifier Modifier=XtensaCP::no_modifier)
XtensaConstantPoolValue (LLVMContext &C, unsigned id, XtensaCP::XtensaCPKind Kind, XtensaCP::XtensaCPModifier Modifier=XtensaCP::no_modifier)
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, Align Alignment)
Detailed Description
XtensaConstantPoolValue - Xtensa specific constantpool value.
This is used to represent PC-relative displacement between the address of the load instruction and the constant being loaded.
Definition at line 48 of file XtensaConstantPoolValue.h.
Constructor & Destructor Documentation
XtensaConstantPoolValue() [1/2]
XtensaConstantPoolValue::XtensaConstantPoolValue (Type * Ty, unsigned ID, XtensaCP::XtensaCPKind Kind, XtensaCP::XtensaCPModifier Modifier = XtensaCP::no_modifier) protected
Definition at line 24 of file XtensaConstantPoolValue.cpp.
XtensaConstantPoolValue() [2/2]
XtensaConstantPoolValue::XtensaConstantPoolValue (LLVMContext & C, unsigned id, XtensaCP::XtensaCPKind Kind, XtensaCP::XtensaCPModifier Modifier = XtensaCP::no_modifier) protected
Definition at line 30 of file XtensaConstantPoolValue.cpp.
~XtensaConstantPoolValue()
XtensaConstantPoolValue::~XtensaConstantPoolValue () override
Definition at line 36 of file XtensaConstantPoolValue.cpp.
Member Function Documentation
addSelectionDAGCSEId()
void XtensaConstantPoolValue::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 53 of file XtensaConstantPoolValue.cpp.
Referenced by llvm::XtensaConstantPoolConstant::addSelectionDAGCSEId(), llvm::XtensaConstantPoolMBB::addSelectionDAGCSEId(), and llvm::XtensaConstantPoolSymbol::addSelectionDAGCSEId().
dump()
void XtensaConstantPoolValue::dump () const
Definition at line 66 of file XtensaConstantPoolValue.cpp.
References llvm::errs().
equals()
bool llvm::XtensaConstantPoolValue::equals (const XtensaConstantPoolValue * A) const inline
Definition at line 106 of file XtensaConstantPoolValue.h.
References A.
Referenced by llvm::XtensaConstantPoolConstant::equals(), llvm::XtensaConstantPoolJumpTable::equals(), llvm::XtensaConstantPoolMBB::equals(), llvm::XtensaConstantPoolSymbol::equals(), and getExistingMachineCPValueImpl().
getExistingMachineCPValue()
int XtensaConstantPoolValue::getExistingMachineCPValue (MachineConstantPool * CP, Align Alignment) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 48 of file XtensaConstantPoolValue.cpp.
References llvm::report_fatal_error().
getExistingMachineCPValueImpl()
template<typename Derived > int llvm::XtensaConstantPoolValue::getExistingMachineCPValueImpl (MachineConstantPool * CP, Align Alignment) inline protected
Definition at line 64 of file XtensaConstantPoolValue.h.
References llvm::cast(), llvm::dyn_cast(), equals(), and llvm::getAlign().
Referenced by llvm::XtensaConstantPoolConstant::getExistingMachineCPValue(), llvm::XtensaConstantPoolJumpTable::getExistingMachineCPValue(), llvm::XtensaConstantPoolMBB::getExistingMachineCPValue(), and llvm::XtensaConstantPoolSymbol::getExistingMachineCPValue().
getLabelId()
unsigned llvm::XtensaConstantPoolValue::getLabelId () const inline
Definition at line 87 of file XtensaConstantPoolValue.h.
Referenced by llvm::XtensaAsmPrinter::emitMachineConstantPoolValue().
getModifier()
XtensaCP::XtensaCPModifier llvm::XtensaConstantPoolValue::getModifier () const inline
Definition at line 83 of file XtensaConstantPoolValue.h.
Referenced by llvm::XtensaAsmPrinter::emitMachineConstantPoolValue().
getModifierText()
StringRef XtensaConstantPoolValue::getModifierText () const
Definition at line 38 of file XtensaConstantPoolValue.cpp.
References llvm::XtensaCP::no_modifier, llvm::report_fatal_error(), and llvm::XtensaCP::TPOFF.
Referenced by llvm::XtensaAsmPrinter::emitMachineConstantPoolValue().
hasModifier()
bool llvm::XtensaConstantPoolValue::hasModifier () const inline
Definition at line 84 of file XtensaConstantPoolValue.h.
References llvm::XtensaCP::no_modifier.
hasSameValue()
bool XtensaConstantPoolValue::hasSameValue (XtensaConstantPoolValue * ACPV) virtual
hasSameValue - Return true if this Xtensa constpool value can share the same constantpool entry as another Xtensa constpool value.
Reimplemented in llvm::XtensaConstantPoolConstant, llvm::XtensaConstantPoolJumpTable, llvm::XtensaConstantPoolMBB, and llvm::XtensaConstantPoolSymbol.
Definition at line 57 of file XtensaConstantPoolValue.cpp.
Referenced by llvm::XtensaConstantPoolConstant::hasSameValue(), llvm::XtensaConstantPoolJumpTable::hasSameValue(), llvm::XtensaConstantPoolMBB::hasSameValue(), and llvm::XtensaConstantPoolSymbol::hasSameValue().
isBlockAddress()
bool llvm::XtensaConstantPoolValue::isBlockAddress () const inline
Definition at line 91 of file XtensaConstantPoolValue.h.
References llvm::XtensaCP::CPBlockAddress.
Referenced by llvm::XtensaConstantPoolConstant::classof(), and llvm::XtensaAsmPrinter::emitMachineConstantPoolValue().
isExtSymbol()
bool llvm::XtensaConstantPoolValue::isExtSymbol () const inline
Definition at line 90 of file XtensaConstantPoolValue.h.
References llvm::XtensaCP::CPExtSymbol.
Referenced by llvm::XtensaConstantPoolSymbol::classof(), and llvm::XtensaAsmPrinter::emitMachineConstantPoolValue().
isJumpTable()
bool llvm::XtensaConstantPoolValue::isJumpTable () const inline
Definition at line 95 of file XtensaConstantPoolValue.h.
References llvm::XtensaCP::CPJumpTable.
Referenced by llvm::XtensaConstantPoolJumpTable::classof(), and llvm::XtensaAsmPrinter::emitMachineConstantPoolValue().
isMachineBasicBlock()
bool llvm::XtensaConstantPoolValue::isMachineBasicBlock () const inline
Definition at line 92 of file XtensaConstantPoolValue.h.
References llvm::XtensaCP::CPMachineBasicBlock.
Referenced by llvm::XtensaConstantPoolMBB::classof().
print()
void XtensaConstantPoolValue::print (raw_ostream & O) const override virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Definition at line 69 of file XtensaConstantPoolValue.cpp.
Referenced by llvm::XtensaConstantPoolConstant::print(), llvm::XtensaConstantPoolJumpTable::print(), llvm::XtensaConstantPoolMBB::print(), and llvm::XtensaConstantPoolSymbol::print().
setLabelId()
void llvm::XtensaConstantPoolValue::setLabelId (unsigned ID) inline
Definition at line 88 of file XtensaConstantPoolValue.h.
Referenced by llvm::XtensaAsmPrinter::emitMachineConstantPoolEntry().
The documentation for this class was generated from the following files:
lib/Target/Xtensa/XtensaConstantPoolValue.h
lib/Target/Xtensa/XtensaConstantPoolValue.cpp