LLVM: llvm::orc::SimpleRemoteEPCServer::Setup Class Reference
llvm::orc::SimpleRemoteEPCServer::Setup Class Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/SimpleRemoteEPCServer.h"
Public Member Functions
SimpleRemoteEPCServer & server ()
StringMap< std::vector< char > > & bootstrapMap ()
template<typename T , typename SPSTagT >
void setBootstrapMapValue (std::string Key, const T &Value)
StringMap< ExecutorAddr > & bootstrapSymbols ()
std::vector< std::unique_ptr< ExecutorBootstrapService > > & services ()
void setDispatcher (std::unique_ptr< Dispatcher > D)
void setErrorReporter (unique_function< void(Error)> ReportError)
Friends
class SimpleRemoteEPCServer
Detailed Description
Definition at line 62 of file SimpleRemoteEPCServer.h.
Member Function Documentation
bootstrapMap()
StringMap< std::vector< char > > & llvm::orc::SimpleRemoteEPCServer::Setup::bootstrapMap () inline
Definition at line 67 of file SimpleRemoteEPCServer.h.
bootstrapSymbols()
StringMap< ExecutorAddr > & llvm::orc::SimpleRemoteEPCServer::Setup::bootstrapSymbols () inline
Definition at line 78 of file SimpleRemoteEPCServer.h.
Referenced by llvm::orc::SimpleRemoteEPCServer::Create().
server()
SimpleRemoteEPCServer & llvm::orc::SimpleRemoteEPCServer::Setup::server () inline
Definition at line 66 of file SimpleRemoteEPCServer.h.
services()
std::vector< std::unique_ptr< ExecutorBootstrapService > > & llvm::orc::SimpleRemoteEPCServer::Setup::services () inline
Definition at line 79 of file SimpleRemoteEPCServer.h.
Referenced by llvm::orc::SimpleRemoteEPCServer::Create().
setBootstrapMapValue()
template<typename T , typename SPSTagT > void llvm::orc::SimpleRemoteEPCServer::Setup::setBootstrapMapValue (std::string Key, const T & Value) inline
Definition at line 69 of file SimpleRemoteEPCServer.h.
References assert(), and Success.
setDispatcher()
void llvm::orc::SimpleRemoteEPCServer::Setup::setDispatcher (std::unique_ptr< Dispatcher > D) inline
Definition at line 82 of file SimpleRemoteEPCServer.h.
References D.
setErrorReporter()
void llvm::orc::SimpleRemoteEPCServer::Setup::setErrorReporter (unique_function< void(Error)> ReportError) inline
Definition at line 83 of file SimpleRemoteEPCServer.h.
Friends And Related Symbol Documentation
SimpleRemoteEPCServer
friend class SimpleRemoteEPCServer friend
Definition at line 63 of file SimpleRemoteEPCServer.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/TargetProcess/SimpleRemoteEPCServer.h