LLVM: llvm::sandboxir::Tracker Class Reference
llvm::sandboxir::Tracker Class Reference
The tracker collects all the change objects and implements the main API for saving / reverting / accepting.
#include "llvm/SandboxIR/Tracker.h"
Public Types
enum class TrackerState { Disabled , Record }
Public Member Functions
Tracker (Context &Ctx)
~Tracker ()
Context & getContext () const
void track (std::unique_ptr< IRChangeBase > &&Change)
Record Change and take ownership.
bool isTracking () const
\Returns true if the tracker is recording changes.
TrackerState getState () const
\Returns the current state of the tracker.
void save ()
Turns on IR tracking.
void accept ()
Stops tracking and accept changes.
void revert ()
Stops tracking and reverts to saved state.
void dump (raw_ostream &OS) const
LLVM_DUMP_METHOD void dump () const
Public Attributes
bool InMiddleOfCreatingChange = false
Helps catch bugs where we are creating new change objects while in the middle of creating other change objects.
Friends
unsigned IRChangeBase::getIdx () const
raw_ostream & operator<< (raw_ostream &OS, const Tracker &Tracker)
Detailed Description
The tracker collects all the change objects and implements the main API for saving / reverting / accepting.
Definition at line 181 of file Tracker.h.
Member Enumeration Documentation
TrackerState
enum class llvm::sandboxir::Tracker::TrackerState strong
Enumerator
Disabled
Record
‍Tracking is disabled
Definition at line 183 of file Tracker.h.
Constructor & Destructor Documentation
Tracker()
llvm::sandboxir::Tracker::Tracker (Context & Ctx) inline explicit
Definition at line 205 of file Tracker.h.
~Tracker()
Tracker::~Tracker ()
Definition at line 40 of file Tracker.cpp.
References assert().
Member Function Documentation
accept()
void Tracker::accept ()
Stops tracking and accept changes.
Definition at line 170 of file Tracker.cpp.
References assert(), Disabled, and Record.
dump() [1/2]
void Tracker::dump () const
Definition at line 185 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void Tracker::dump (raw_ostream & OS) const
Definition at line 179 of file Tracker.cpp.
References OS.
getContext()
Context & llvm::sandboxir::Tracker::getContext () const inline
Definition at line 207 of file Tracker.h.
Referenced by llvm::sandboxir::EraseFromParent::revert().
getState()
TrackerState llvm::sandboxir::Tracker::getState () const inline
\Returns the current state of the tracker.
Definition at line 214 of file Tracker.h.
isTracking()
bool llvm::sandboxir::Tracker::isTracking () const inline
\Returns true if the tracker is recording changes.
Definition at line 212 of file Tracker.h.
References Record.
Referenced by llvm::sandboxir::IRChangeBase::IRChangeBase(), llvm::sandboxir::Value::replaceAllUsesWith(), llvm::sandboxir::User::replaceUsesOfWith(), llvm::sandboxir::Value::replaceUsesWithIf(), and llvm::sandboxir::User::setOperand().
revert()
void Tracker::revert ()
Stops tracking and reverts to saved state.
Definition at line 162 of file Tracker.cpp.
References assert(), Disabled, Record, and llvm::reverse().
save()
void Tracker::save ()
Turns on IR tracking.
Definition at line 160 of file Tracker.cpp.
References Record.
track()
void Tracker::track (std::unique_ptr< IRChangeBase > && Change)
Record Change and take ownership.
This is the main function used to track Sandbox IR changes.
Definition at line 151 of file Tracker.cpp.
References assert(), InMiddleOfCreatingChange, and Record.
Referenced by llvm::sandboxir::Value::replaceAllUsesWith(), llvm::sandboxir::User::replaceUsesOfWith(), llvm::sandboxir::Value::replaceUsesWithIf(), and llvm::sandboxir::User::setOperand().
Friends And Related Symbol Documentation
IRChangeBase::getIdx
unsigned IRChangeBase::getIdx () const friend
operator<<
raw_ostream & operator<< (raw_ostream & OS, const Tracker & Tracker) friend
Definition at line 225 of file Tracker.h.
Member Data Documentation
InMiddleOfCreatingChange
bool llvm::sandboxir::Tracker::InMiddleOfCreatingChange = false
Helps catch bugs where we are creating new change objects while in the middle of creating other change objects.
Definition at line 202 of file Tracker.h.
Referenced by llvm::sandboxir::IRChangeBase::IRChangeBase(), and track().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp