LLVM: llvm::codeview::LineInfo Class Reference
llvm::codeview::LineInfo Class Reference
#include "llvm/DebugInfo/CodeView/Line.h"
Public Types
enum : uint32_t { AlwaysStepIntoLineNumber = 0xfeefee , NeverStepIntoLineNumber = 0xf00f00 }
enum : int { EndLineDeltaShift = 24 }
enum : uint32_t { StartLineMask = 0x00ffffff , EndLineDeltaMask = 0x7f000000 , StatementFlag = 0x80000000u }
Public Member Functions
LineInfo (uint32_t StartLine, uint32_t EndLine, bool IsStatement)
LineInfo (uint32_t LineData)
uint32_t getStartLine () const
uint32_t getLineDelta () const
uint32_t getEndLine () const
bool isStatement () const
uint32_t getRawData () const
bool isAlwaysStepInto () const
bool isNeverStepInto () const
Detailed Description
Definition at line 20 of file Line.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : uint32_t
Enumerator
AlwaysStepIntoLineNumber
NeverStepIntoLineNumber
Definition at line 22 of file Line.h.
anonymous enum
anonymous enum : int
Enumerator
EndLineDeltaShift
Definition at line 27 of file Line.h.
anonymous enum
anonymous enum : uint32_t
Enumerator
StartLineMask
EndLineDeltaMask
StatementFlag
Definition at line 29 of file Line.h.
Constructor & Destructor Documentation
LineInfo() [1/2]
LineInfo::LineInfo (uint32_t StartLine, uint32_t EndLine, bool IsStatement)
Definition at line 14 of file Line.cpp.
References EndLineDeltaMask, EndLineDeltaShift, StartLineMask, and StatementFlag.
LineInfo() [2/2]
llvm::codeview::LineInfo::LineInfo (uint32_t LineData) inline
Definition at line 36 of file Line.h.
Member Function Documentation
getEndLine()
uint32_t llvm::codeview::LineInfo::getEndLine () const inline
Definition at line 44 of file Line.h.
References getLineDelta(), and getStartLine().
Referenced by llvm::codeview::Line::getEndLine(), and llvm::pdb::NativeLineNumber::getLineNumberEnd().
getLineDelta()
uint32_t llvm::codeview::LineInfo::getLineDelta () const inline
Definition at line 40 of file Line.h.
References EndLineDeltaMask, and EndLineDeltaShift.
Referenced by getEndLine(), and llvm::codeview::Line::getLineDelta().
getRawData()
uint32_t llvm::codeview::LineInfo::getRawData () const inline
Definition at line 48 of file Line.h.
getStartLine()
uint32_t llvm::codeview::LineInfo::getStartLine () const inline
Definition at line 38 of file Line.h.
References StartLineMask.
Referenced by getEndLine(), llvm::pdb::NativeLineNumber::getLineNumber(), llvm::codeview::Line::getStartLine(), isAlwaysStepInto(), and isNeverStepInto().
isAlwaysStepInto()
bool llvm::codeview::LineInfo::isAlwaysStepInto () const inline
Definition at line 50 of file Line.h.
References AlwaysStepIntoLineNumber, and getStartLine().
Referenced by llvm::codeview::Line::isAlwaysStepInto().
isNeverStepInto()
bool llvm::codeview::LineInfo::isNeverStepInto () const inline
Definition at line 54 of file Line.h.
References getStartLine(), and NeverStepIntoLineNumber.
Referenced by llvm::codeview::Line::isNeverStepInto().
isStatement()
bool llvm::codeview::LineInfo::isStatement () const inline
Definition at line 46 of file Line.h.
References StatementFlag.
Referenced by llvm::codeview::Line::isStatement(), and llvm::pdb::NativeLineNumber::isStatement().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/CodeView/Line.h
lib/DebugInfo/CodeView/Line.cpp