LLVM: llvm::memprof::CallStackRadixTreeBuilder Class Reference
llvm::memprof::CallStackRadixTreeBuilder Class Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
CallStackRadixTreeBuilder ()=default
void build (llvm::MapVector< CallStackId, llvm::SmallVector< FrameId > > &&MemProfCallStackData, const llvm::DenseMap< FrameId, LinearFrameId > &MemProfFrameIndexes, llvm::DenseMap< FrameId, FrameStat > &FrameHistogram)
const std::vector< LinearFrameId > & getRadixArray () const
llvm::DenseMap< CallStackId, LinearCallStackId > takeCallStackPos ()
Detailed Description
Definition at line 1009 of file MemProf.h.
Constructor & Destructor Documentation
CallStackRadixTreeBuilder()
llvm::memprof::CallStackRadixTreeBuilder::CallStackRadixTreeBuilder () default
Member Function Documentation
build()
void llvm::memprof::CallStackRadixTreeBuilder::build (llvm::MapVector< CallStackId, llvm::SmallVector< FrameId > > && MemProfCallStackData, const llvm::DenseMap< FrameId, LinearFrameId > & MemProfFrameIndexes, llvm::DenseMap< FrameId, FrameStat > & FrameHistogram)
Definition at line 486 of file MemProf.cpp.
References assert(), llvm::SmallVectorBase< Size_T >::empty(), I, llvm::reverse(), llvm::SmallVectorBase< Size_T >::size(), llvm::sort(), and std::swap().
Referenced by writeMemProfCallStackArray().
getRadixArray()
const std::vector< LinearFrameId > & llvm::memprof::CallStackRadixTreeBuilder::getRadixArray () const inline
Definition at line 1054 of file MemProf.h.
takeCallStackPos()
llvm::DenseMap< CallStackId, LinearCallStackId > llvm::memprof::CallStackRadixTreeBuilder::takeCallStackPos () inline
Definition at line 1056 of file MemProf.h.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/MemProf.h
lib/ProfileData/MemProf.cpp