LLVM: llvm::DWARFAbbreviationDeclarationSet Class Reference
llvm::DWARFAbbreviationDeclarationSet Class Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugAbbrev.h"
Public Member Functions
DWARFAbbreviationDeclarationSet ()
uint64_t getOffset () const
void dump (raw_ostream &OS) const
Error extract (DataExtractor Data, uint64_t *OffsetPtr)
const DWARFAbbreviationDeclaration * getAbbreviationDeclaration (uint32_t AbbrCode) const
const_iterator begin () const
const_iterator end () const
std::string getCodeRange () const
uint32_t getFirstAbbrCode () const
Detailed Description
Definition at line 22 of file DWARFDebugAbbrev.h.
Constructor & Destructor Documentation
DWARFAbbreviationDeclarationSet()
DWARFAbbreviationDeclarationSet::DWARFAbbreviationDeclarationSet ()
Definition at line 18 of file DWARFDebugAbbrev.cpp.
Member Function Documentation
begin()
const_iterator llvm::DWARFAbbreviationDeclarationSet::begin () const inline
Definition at line 42 of file DWARFDebugAbbrev.h.
dump()
void DWARFAbbreviationDeclarationSet::dump (raw_ostream & OS) const
Definition at line 56 of file DWARFDebugAbbrev.cpp.
References OS.
end()
const_iterator llvm::DWARFAbbreviationDeclarationSet::end () const inline
Definition at line 46 of file DWARFDebugAbbrev.h.
extract()
Error DWARFAbbreviationDeclarationSet::extract (DataExtractor Data, uint64_t * OffsetPtr)
Definition at line 28 of file DWARFDebugAbbrev.cpp.
References llvm::DWARFAbbreviationDeclaration::Complete, llvm::Data, llvm::DWARFAbbreviationDeclaration::extract(), llvm::DWARFAbbreviationDeclaration::getCode(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by llvm::DWARFDebugAbbrev::getAbbreviationDeclarationSet(), and llvm::DWARFDebugAbbrev::parse().
getAbbreviationDeclaration()
const DWARFAbbreviationDeclaration * DWARFAbbreviationDeclarationSet::getAbbreviationDeclaration (uint32_t AbbrCode) const
Definition at line 62 of file DWARFDebugAbbrev.cpp.
getCodeRange()
std::string DWARFAbbreviationDeclarationSet::getCodeRange () const
Definition at line 76 of file DWARFDebugAbbrev.cpp.
References End.
getFirstAbbrCode()
uint32_t llvm::DWARFAbbreviationDeclarationSet::getFirstAbbrCode () const inline
Definition at line 52 of file DWARFDebugAbbrev.h.
getOffset()
uint64_t llvm::DWARFAbbreviationDeclarationSet::getOffset () const inline
Definition at line 35 of file DWARFDebugAbbrev.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugAbbrev.h
lib/DebugInfo/DWARF/DWARFDebugAbbrev.cpp