LLVM: llvm::XtensaSubtarget Class Reference
llvm::XtensaSubtarget Class Reference
#include "Target/Xtensa/XtensaSubtarget.h"
Public Member Functions
XtensaSubtarget (const Triple &TT, StringRef CPU, StringRef FS, const TargetMachine &TM)
const Triple & getTargetTriple () const
const TargetFrameLowering * getFrameLowering () const override
const XtensaInstrInfo * getInstrInfo () const override
const XtensaRegisterInfo * getRegisterInfo () const override
const XtensaTargetLowering * getTargetLowering () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
bool hasDensity () const
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
Detailed Description
Definition at line 31 of file XtensaSubtarget.h.
Constructor & Destructor Documentation
XtensaSubtarget()
XtensaSubtarget::XtensaSubtarget (const Triple & TT, StringRef CPU, StringRef FS, const TargetMachine & TM)
Definition at line 40 of file XtensaSubtarget.cpp.
Member Function Documentation
getFrameLowering()
const TargetFrameLowering * llvm::XtensaSubtarget::getFrameLowering () const inline override
Definition at line 50 of file XtensaSubtarget.h.
Referenced by llvm::XtensaTargetLowering::LowerCall().
getInstrInfo()
const XtensaInstrInfo * llvm::XtensaSubtarget::getInstrInfo () const inline override
Definition at line 53 of file XtensaSubtarget.h.
getRegisterInfo()
const XtensaRegisterInfo * llvm::XtensaSubtarget::getRegisterInfo () const inline override
Definition at line 54 of file XtensaSubtarget.h.
Referenced by llvm::XtensaTargetLowering::LowerCall(), and llvm::XtensaTargetLowering::XtensaTargetLowering().
getSelectionDAGInfo()
const SelectionDAGTargetInfo * llvm::XtensaSubtarget::getSelectionDAGInfo () const inline override
Definition at line 61 of file XtensaSubtarget.h.
getTargetLowering()
const XtensaTargetLowering * llvm::XtensaSubtarget::getTargetLowering () const inline override
Definition at line 58 of file XtensaSubtarget.h.
getTargetTriple()
const Triple & llvm::XtensaSubtarget::getTargetTriple () const inline
Definition at line 48 of file XtensaSubtarget.h.
hasDensity()
bool llvm::XtensaSubtarget::hasDensity () const inline
Definition at line 65 of file XtensaSubtarget.h.
ParseSubtargetFeatures()
void llvm::XtensaSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
The documentation for this class was generated from the following files:
lib/Target/Xtensa/XtensaSubtarget.h
lib/Target/Xtensa/XtensaSubtarget.cpp