LLVM: llvm::orc::VTuneSupportPlugin Class Reference
llvm::orc::VTuneSupportPlugin Class Reference
#include "llvm/ExecutionEngine/Orc/Debugging/VTuneSupportPlugin.h"
Public Member Functions
VTuneSupportPlugin (ExecutorProcessControl &EPC, ExecutorAddr RegisterImplAddr, ExecutorAddr UnregisterImplAddr, bool EmitDebugInfo)
void modifyPassConfig (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::PassConfiguration &Config) override
Error notifyEmitted (MaterializationResponsibility &MR) override
Error notifyFailed (MaterializationResponsibility &MR) override
Error notifyRemovingResources (JITDylib &JD, ResourceKey K) override
void notifyTransferringResources (JITDylib &JD, ResourceKey DstKey, ResourceKey SrcKey) override
Public Member Functions inherited from llvm::orc::ObjectLinkingLayer::Plugin
virtual ~Plugin ()
virtual void notifyMaterializing (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::JITLinkContext &Ctx, MemoryBufferRef InputObject)
virtual void notifyLoaded (MaterializationResponsibility &MR)
virtual SyntheticSymbolDependenciesMap getSyntheticSymbolDependencies (MaterializationResponsibility &MR)
Return any dependencies that synthetic symbols (e.g.
Static Public Member Functions
static Expected< std::unique_ptr< VTuneSupportPlugin > > Create (ExecutorProcessControl &EPC, JITDylib &JD, bool EmitDebugInfo, bool TestMode=false)
Additional Inherited Members
Public Types inherited from llvm::orc::ObjectLinkingLayer::Plugin
using JITLinkSymbolSet = DenseSet<jitlink::Symbol *>
using SyntheticSymbolDependenciesMap
Detailed Description
Definition at line 27 of file VTuneSupportPlugin.h.
Constructor & Destructor Documentation
VTuneSupportPlugin()
llvm::orc::VTuneSupportPlugin::VTuneSupportPlugin (ExecutorProcessControl & EPC, ExecutorAddr RegisterImplAddr, ExecutorAddr UnregisterImplAddr, bool EmitDebugInfo) inline
Definition at line 29 of file VTuneSupportPlugin.h.
Member Function Documentation
Create()
Expected< std::unique_ptr< VTuneSupportPlugin > > VTuneSupportPlugin::Create (ExecutorProcessControl & EPC, JITDylib & JD, bool EmitDebugInfo, bool TestMode = false) static
Definition at line 169 of file VTuneSupportPlugin.cpp.
References RegisterTestVTuneImplName, RegisterVTuneImplName, and UnregisterVTuneImplName.
modifyPassConfig()
void VTuneSupportPlugin::modifyPassConfig (MaterializationResponsibility & MR, jitlink::LinkGraph & G, jitlink::PassConfiguration & Config) override virtual
Reimplemented from llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 84 of file VTuneSupportPlugin.cpp.
References llvm::cantFail(), Config, llvm::orc::shared::WrapperFunctionCall::Create(), G, getMethodBatch(), and llvm::Error::success().
notifyEmitted()
Error VTuneSupportPlugin::notifyEmitted (MaterializationResponsibility & MR) override virtual
Reimplemented from llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 112 of file VTuneSupportPlugin.cpp.
References llvm::Error::success().
notifyFailed()
Error VTuneSupportPlugin::notifyFailed (MaterializationResponsibility & MR) override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 127 of file VTuneSupportPlugin.cpp.
References llvm::Error::success().
notifyRemovingResources()
Error VTuneSupportPlugin::notifyRemovingResources (JITDylib & JD, ResourceKey K) override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 133 of file VTuneSupportPlugin.cpp.
References I, and llvm::Error::success().
notifyTransferringResources()
void VTuneSupportPlugin::notifyTransferringResources (JITDylib & JD, ResourceKey DstKey, ResourceKey SrcKey) override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 155 of file VTuneSupportPlugin.cpp.
References I.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Debugging/VTuneSupportPlugin.h
lib/ExecutionEngine/Orc/Debugging/VTuneSupportPlugin.cpp