LLVM: llvm::lto::ThinBackendProc Class Reference
llvm::lto::ThinBackendProc Class Reference abstract
This class defines the interface to the ThinLTO backend.
Public Member Functions
ThinBackendProc (const Config &Conf, ModuleSummaryIndex &CombinedIndex, const DenseMap< StringRef, GVSummaryMapTy > &ModuleToDefinedGVSummaries, lto::IndexWriteCallback OnWrite, bool ShouldEmitImportsFiles)
virtual ~ThinBackendProc ()=default
virtual Error start (unsigned Task, BitcodeModule BM, const FunctionImporter::ImportMapTy &ImportList, const FunctionImporter::ExportSetTy &ExportList, const std::map< GlobalValue::GUID, GlobalValue::LinkageTypes > &ResolvedODR, MapVector< StringRef, BitcodeModule > &ModuleMap)=0
virtual Error wait ()=0
virtual unsigned getThreadCount ()=0
Error emitFiles (const FunctionImporter::ImportMapTy &ImportList, llvm::StringRef ModulePath, const std::string &NewModulePath)
Protected Attributes
const Config & Conf
ModuleSummaryIndex & CombinedIndex
const DenseMap< StringRef, GVSummaryMapTy > & ModuleToDefinedGVSummaries
lto::IndexWriteCallback OnWrite
bool ShouldEmitImportsFiles
Detailed Description
This class defines the interface to the ThinLTO backend.
Definition at line 1370 of file LTO.cpp.
Constructor & Destructor Documentation
ThinBackendProc()
llvm::lto::ThinBackendProc::ThinBackendProc (const Config & Conf, ModuleSummaryIndex & CombinedIndex, const DenseMap< StringRef, GVSummaryMapTy > & ModuleToDefinedGVSummaries, lto::IndexWriteCallback OnWrite, bool ShouldEmitImportsFiles) inline
Definition at line 1379 of file LTO.cpp.
~ThinBackendProc()
virtual llvm::lto::ThinBackendProc::~ThinBackendProc () virtual default
Member Function Documentation
emitFiles()
Error llvm::lto::ThinBackendProc::emitFiles (const FunctionImporter::ImportMapTy & ImportList, llvm::StringRef ModulePath, const std::string & NewModulePath) inline
Definition at line 1398 of file LTO.cpp.
References llvm::EmitImportsFiles(), llvm::errorCodeToError(), llvm::gatherImportedSummariesForModule(), OS, llvm::Error::success(), and llvm::writeIndexToFile().
getThreadCount()
virtual unsigned llvm::lto::ThinBackendProc::getThreadCount () pure virtual
start()
virtual Error llvm::lto::ThinBackendProc::start (unsigned Task, BitcodeModule BM, const FunctionImporter::ImportMapTy & ImportList, const FunctionImporter::ExportSetTy & ExportList, const std::map< GlobalValue::GUID, GlobalValue::LinkageTypes > & ResolvedODR, MapVector< StringRef, BitcodeModule > & ModuleMap) pure virtual
wait()
virtual Error llvm::lto::ThinBackendProc::wait () pure virtual
Member Data Documentation
CombinedIndex
ModuleSummaryIndex& llvm::lto::ThinBackendProc::CombinedIndex protected
Definition at line 1373 of file LTO.cpp.
Conf
const Config& llvm::lto::ThinBackendProc::Conf protected
Definition at line 1372 of file LTO.cpp.
ModuleToDefinedGVSummaries
const DenseMap<StringRef, GVSummaryMapTy>& llvm::lto::ThinBackendProc::ModuleToDefinedGVSummaries protected
Definition at line 1374 of file LTO.cpp.
OnWrite
lto::IndexWriteCallback llvm::lto::ThinBackendProc::OnWrite protected
Definition at line 1375 of file LTO.cpp.
ShouldEmitImportsFiles
bool llvm::lto::ThinBackendProc::ShouldEmitImportsFiles protected
Definition at line 1376 of file LTO.cpp.
The documentation for this class was generated from the following file:
lib/LTO/LTO.cpp