LLVM: llvm::ilist_node_with_parent< NodeTy, ParentTy, Options > Class Template Reference
llvm::ilist_node_with_parent< NodeTy, ParentTy, Options > Class Template Reference
An ilist node that can access its parent list.
#include "llvm/ADT/ilist_node.h"
Public Member Functions
Adjacent Node Accessors
Get the previous node, or nullptr for the list head.
NodeTy * getPrevNode ()
const NodeTy * getPrevNode () const
Get the previous node, or nullptr for the list head.
NodeTy * getNextNode ()
Get the next node, or nullptr for the list tail.
const NodeTy * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< NodeTy, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< NodeTy, Options... >::type >, ilist_detail::compute_node_options< NodeTy, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< NodeTy, Options... >::type::parent_ty * getParent () const
ilist_detail::compute_node_options< NodeTy, Options... >::type::parent_ty * getParent ()
void setParent (ilist_detail::compute_node_options< NodeTy, Options... >::type::parent_ty *Parent)
Protected Member Functions
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< NodeTy, Options... >::type >
ilist_node_impl ()=default
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< NodeTy, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Detailed Description
template<typename NodeTy, typename ParentTy, class... Options>
class llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >
An ilist node that can access its parent list.
Requires NodeTy to have getParent() to find the parent node, and the ParentTy to have getSublistAccess() to get a reference to the list.
Definition at line 321 of file ilist_node.h.
Constructor & Destructor Documentation
ilist_node_with_parent()
template<typename NodeTy , typename ParentTy , class... Options> llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::ilist_node_with_parent () protected default
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-19.1.0/llvm/include/llvm/ADT/ilist_node.h.
References llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< NodeTy, Options... >::type >, ilist_detail::compute_node_options< NodeTy, Options... >::type::parent_ty >::getParent().
Member Function Documentation
getNextNode() [1/2]
template<typename NodeTy , typename ParentTy , class... Options> NodeTy * llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode () inline
Get the next node, or nullptr for the list tail.
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-19.1.0/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 353 of file ilist_node.h.
Referenced by AlignBlocks(), llvm::AArch64InstrInfo::analyzeBranchPredicate(), llvm::X86InstrInfo::analyzeBranchPredicate(), llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), llvm::OpenMPIRBuilder::collapseLoops(), collectInstructionsInBetween(), llvm::OpenMPIRBuilder::createCanonicalLoop(), llvm::OpenMPIRBuilder::createParallel(), llvm::RandomIRBuilder::createStackMemory(), emitSetAndGetSwiftErrorValueAround(), llvm::DebugHandlerBase::endInstruction(), FindDominatedInstruction(), llvm::getMachineInstrType(), llvm::MustBeExecutedContextExplorer::getMustBeExecutedNextInstruction(), getNextMachineInstr(), getNextNode(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::Instruction::getNextNonDebugInstruction(), hasCallsBetween(), hasCallsInBlockBetween(), insertRelocationStores(), llvm::SampleProfileProber::instrumentOneFunc(), llvm::ARMBlockPlacement::moveBasicBlock(), llvm::sandboxir::MoveInstr::MoveInstr(), OptimizeGlobalAddressOfAllocation(), optimizeSQRT(), processNewInstrs(), rematerializeLiveValues(), removeEmptyCleanup(), llvm::sandboxir::RemoveFromParent::RemoveFromParent(), simplifyRelocatesOffABase(), sinkSpillUsesAfterCoroBegin(), llvm::splitBB(), llvm::JumpThreadingPass::threadGuard(), validateFunCallMachineDef(), and versionCallSiteWithCond().
getNextNode() [2/2]
template<typename NodeTy , typename ParentTy , class... Options> const NodeTy * llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode () const inline
Get the next node, or nullptr for the list tail.
Definition at line 362 of file ilist_node.h.
References llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode().
getPrevNode() [1/2]
template<typename NodeTy , typename ParentTy , class... Options> NodeTy * llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode () inline
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-19.1.0/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 339 of file ilist_node.h.
Referenced by llvm::VPlan::execute(), llvm::ARMBlockPlacement::fixBackwardsWLS(), llvm::MustBeExecutedContextExplorer::getMustBeExecutedPrevInstruction(), getOrCreateDebugLoc(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode(), llvm::Instruction::getPrevNonDebugInstruction(), llvm::BasicBlock::getTerminatingMustTailCall(), LowerCallResults(), llvm::ARMBlockPlacement::moveBasicBlock(), PrevCrossBBInst(), simplifySuspendPoint(), and updateKillStatus().
getPrevNode() [2/2]
template<typename NodeTy , typename ParentTy , class... Options> const NodeTy * llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode () const inline
Get the previous node, or nullptr for the list head.
Definition at line 348 of file ilist_node.h.
References llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getPrevNode().
The documentation for this class was generated from the following file:
include/llvm/ADT/ilist_node.h