LLVM: llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay > Class Template Reference
llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay > Class Template Reference
Allocate memory in an ever growing pool, as if by bump-pointer.
#include "llvm/Support/Allocator.h"
Public Member Functions
BumpPtrAllocatorImpl ()=default
template<typename T >
BumpPtrAllocatorImpl (T &&Allocator)
BumpPtrAllocatorImpl (BumpPtrAllocatorImpl &&Old)
~BumpPtrAllocatorImpl ()
BumpPtrAllocatorImpl & operator= (BumpPtrAllocatorImpl &&RHS)
void Reset ()
Deallocate all but the current slab and reset the current pointer to the beginning of it, freeing all memory allocated so far.
LLVM_ATTRIBUTE_RETURNS_NONNULL void * Allocate (size_t Size, Align Alignment)
Allocate space at the specified alignment.
LLVM_ATTRIBUTE_RETURNS_NONNULL LLVM_ATTRIBUTE_NOINLINE void * AllocateSlow (size_t Size, size_t SizeToAllocate, Align Alignment)
LLVM_ATTRIBUTE_RETURNS_NONNULL void * Allocate (size_t Size, size_t Alignment)
void Deallocate (const void *Ptr, size_t Size, size_t)
size_t GetNumSlabs () const
std::optional< int64_t > identifyObject (const void *Ptr)
int64_t identifyKnownObject (const void *Ptr)
A wrapper around identifyObject that additionally asserts that the object is indeed within the allocator.
template<typename T >
int64_t identifyKnownAlignedObject (const void *Ptr)
A wrapper around identifyKnownObject.
size_t getTotalMemory () const
size_t getBytesAllocated () const
void setRedZoneSize (size_t NewSize)
void PrintStats () const
Public Member Functions inherited from llvm::AllocatorBase< BumpPtrAllocatorImpl< MallocAllocator, 4096, 4096, 128 > >
void * Allocate (size_t Size, size_t Alignment)
Allocate Size bytes of Alignment aligned memory.
T * Allocate (size_t Num=1)
Allocate space for a sequence of objects without constructing them.
void Deallocate (const void *Ptr, size_t Size, size_t Alignment)
Deallocate Ptr to Size bytes of memory allocated by this allocator.
std::enable_if_t<!std::is_same_v< std::remove_cv_t< T >, void >, void > Deallocate (T *Ptr, size_t Num=1)
Deallocate space for a sequence of objects without constructing them.
Friends
template<typename T >
class SpecificBumpPtrAllocator
Detailed Description
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128>
class llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >
Allocate memory in an ever growing pool, as if by bump-pointer.
This isn't strictly a bump-pointer allocator as it uses backing slabs of memory rather than relying on a boundless contiguous heap. However, it has bump-pointer semantics in that it is a monotonically growing pool of memory where every allocation is found by merely allocating the next N bytes in the slab, or the next N bytes in the next slab.
Note that this also has a threshold for forcing allocations above a certain size into their own slab.
The BumpPtrAllocatorImpl template defaults to using a MallocAllocator object, which wraps malloc, to allocate memory, but it can be changed to use a custom allocator.
The GrowthDelay specifies after how many allocated slabs the allocator increases the size of the slabs.
Definition at line 63 of file Allocator.h.
Constructor & Destructor Documentation
BumpPtrAllocatorImpl() [1/3]
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::BumpPtrAllocatorImpl () default
BumpPtrAllocatorImpl() [2/3]
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> template<typename T > llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::BumpPtrAllocatorImpl (T && Allocator) inline
Definition at line 81 of file Allocator.h.
BumpPtrAllocatorImpl() [3/3]
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::BumpPtrAllocatorImpl (BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay > && Old) inline
Definition at line 86 of file Allocator.h.
~BumpPtrAllocatorImpl()
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::~BumpPtrAllocatorImpl () inline
Definition at line 97 of file Allocator.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
Member Function Documentation
Allocate() [1/2]
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> LLVM_ATTRIBUTE_RETURNS_NONNULL void * llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate (size_t Size, Align Alignment) inline
Allocate space at the specified alignment.
Definition at line 148 of file Allocator.h.
References __asan_unpoison_memory_region, __msan_allocated_memory, llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::AllocateSlow(), assert(), LLVM_LIKELY, llvm::offsetToAlignedAddr(), and Size.
Referenced by llvm::codeview::DebugChecksumsSubsection::addChecksum(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), llvm::LoopInfoBase< BlockT, LoopT >::AllocateLoop(), llvm::MCContext::allocFragment(), llvm::MachO::RecordsSlice::copyString(), llvm::Attribute::get(), llvm::Attribute::get(), llvm::BitsInit::get(), llvm::CondOpInit::get(), llvm::DagInit::get(), llvm::ListInit::get(), llvm::RecordRecTy::get(), llvm::VarDefInit::get(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ScalarEvolution::getSequentialMinMaxExpr(), llvm::SelectionDAG::getVectorShuffle(), llvm::codeview::GlobalTypeTableBuilder::insertRecordAs(), stabilize(), and llvm::codeview::SymbolSerializer::visitSymbolEnd().
Allocate() [2/2]
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> LLVM_ATTRIBUTE_RETURNS_NONNULL void * llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate (size_t Size, size_t Alignment) inline
Definition at line 212 of file Allocator.h.
References Align, llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), assert(), and Size.
AllocateSlow()
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> LLVM_ATTRIBUTE_RETURNS_NONNULL LLVM_ATTRIBUTE_NOINLINE void * llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::AllocateSlow (size_t Size, size_t SizeToAllocate, Align Alignment) inline
Definition at line 180 of file Allocator.h.
References __asan_poison_memory_region, __asan_unpoison_memory_region, __msan_allocated_memory, llvm::alignAddr(), llvm::MallocAllocator::Allocate(), assert(), llvm::detail::AllocatorHolder< MallocAllocator >::getAllocator(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), Size, and llvm::Align::value().
Referenced by llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate().
Deallocate()
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> void llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Deallocate (const void * Ptr, size_t Size, size_t) inline
Definition at line 223 of file Allocator.h.
References __asan_poison_memory_region, Ptr, and Size.
Referenced by llvm::LoopInfoBase< BlockT, LoopT >::destroy().
getBytesAllocated()
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> size_t llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::getBytesAllocated () const inline
Definition at line 295 of file Allocator.h.
GetNumSlabs()
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> size_t llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::GetNumSlabs () const inline
Definition at line 230 of file Allocator.h.
References llvm::SmallVectorBase< Size_T >::size().
getTotalMemory()
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> size_t llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::getTotalMemory () const inline
Definition at line 286 of file Allocator.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and I.
Referenced by llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::PrintStats().
identifyKnownAlignedObject()
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> template<typename T > int64_t llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::identifyKnownAlignedObject (const void * Ptr) inline
A wrapper around identifyKnownObject.
Accepts type information about the object and produces a smaller identifier by relying on the alignment information. Note that sub-classes may have different alignment, so the most base class should be passed as template parameter in order to obtain correct results. For that reason automatic template parameter deduction is disabled.
Returns
An index uniquely and reproducibly identifying an input pointer Ptr in the given allocator. This identifier is different from the ones produced by identifyObject and identifyAlignedObject.
Definition at line 280 of file Allocator.h.
References assert(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::identifyKnownObject(), Ptr, and T.
identifyKnownObject()
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> int64_t llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::identifyKnownObject (const void * Ptr) inline
A wrapper around identifyObject that additionally asserts that the object is indeed within the allocator.
Returns
An index uniquely and reproducibly identifying an input pointer Ptr in the given allocator.
Definition at line 263 of file Allocator.h.
References assert(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::identifyObject(), and Ptr.
Referenced by llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::identifyKnownAlignedObject().
identifyObject()
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> std::optional< int64_t > llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::identifyObject (const void * Ptr) inline
Returns
An index uniquely and reproducibly identifying an input pointer Ptr in the given allocator. The returned value is negative iff the object is inside a custom-size slab. Returns an empty optional if the pointer is not found in the allocator.
Definition at line 237 of file Allocator.h.
References P, Ptr, Size, and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::MachO::RecordsSlice::copyString(), and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::identifyKnownObject().
operator=()
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> BumpPtrAllocatorImpl & llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::operator= (BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay > && RHS) inline
Definition at line 102 of file Allocator.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
PrintStats()
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> void llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::PrintStats () const inline
Definition at line 301 of file Allocator.h.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::getTotalMemory(), llvm::detail::printBumpPtrAllocatorStats(), and llvm::SmallVectorBase< Size_T >::size().
Reset()
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> void llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Reset () inline
Deallocate all but the current slab and reset the current pointer to the beginning of it, freeing all memory allocated so far.
Definition at line 123 of file Allocator.h.
References __asan_poison_memory_region, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), and llvm::SmallVectorTemplateCommon< T, typename >::front().
Referenced by llvm::rdf::NodeAllocator::clear(), llvm::SelectionDAG::clear(), llvm::GISelCSEInfo::releaseMemory(), llvm::LiveStacks::releaseMemory(), llvm::LoopInfoBase< BlockT, LoopT >::releaseMemory(), and llvm::MCContext::reset().
setRedZoneSize()
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> void llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::setRedZoneSize (size_t NewSize) inline
Definition at line 297 of file Allocator.h.
Friends And Related Symbol Documentation
SpecificBumpPtrAllocator
template<typename AllocatorT = MallocAllocator, size_t SlabSize = 4096, size_t SizeThreshold = SlabSize, size_t GrowthDelay = 128> template<typename T > friend class SpecificBumpPtrAllocator friend
Definition at line 375 of file Allocator.h.
The documentation for this class was generated from the following file:
include/llvm/Support/Allocator.h