LLVM: llvm::memprof::CallStackLookupTrait Class Reference
llvm::memprof::CallStackLookupTrait Class Reference
#include "llvm/ProfileData/MemProf.h"
Public Types
using data_type = const llvm::SmallVector<FrameId>
using internal_key_type = CallStackId
using external_key_type = CallStackId
using hash_value_type = CallStackId
using offset_type = uint64_t
Public Member Functions
hash_value_type ComputeHash (internal_key_type K)
uint64_t ReadKey (const unsigned char *D, offset_type)
data_type ReadData (uint64_t K, const unsigned char *D, offset_type Length)
Static Public Member Functions
static bool EqualKey (internal_key_type A, internal_key_type B)
static uint64_t GetInternalKey (internal_key_type K)
static uint64_t GetExternalKey (external_key_type K)
static std::pair< offset_type, offset_type > ReadKeyDataLength (const unsigned char *&D)
Detailed Description
Definition at line 752 of file MemProf.h.
Member Typedef Documentation
data_type
using llvm::memprof::CallStackLookupTrait::data_type = const llvm::SmallVector<FrameId>
Definition at line 754 of file MemProf.h.
external_key_type
using llvm::memprof::CallStackLookupTrait::external_key_type = CallStackId
Definition at line 756 of file MemProf.h.
hash_value_type
using llvm::memprof::CallStackLookupTrait::hash_value_type = CallStackId
Definition at line 757 of file MemProf.h.
internal_key_type
using llvm::memprof::CallStackLookupTrait::internal_key_type = CallStackId
Definition at line 755 of file MemProf.h.
offset_type
using llvm::memprof::CallStackLookupTrait::offset_type = uint64_t
Definition at line 758 of file MemProf.h.
Member Function Documentation
ComputeHash()
hash_value_type llvm::memprof::CallStackLookupTrait::ComputeHash (internal_key_type K) inline
Definition at line 766 of file MemProf.h.
EqualKey()
static bool llvm::memprof::CallStackLookupTrait::EqualKey (internal_key_type A, internal_key_type B) inline static
Definition at line 760 of file MemProf.h.
References A, and B.
GetExternalKey()
static uint64_t llvm::memprof::CallStackLookupTrait::GetExternalKey (external_key_type K) inline static
Definition at line 764 of file MemProf.h.
GetInternalKey()
static uint64_t llvm::memprof::CallStackLookupTrait::GetInternalKey (internal_key_type K) inline static
Definition at line 763 of file MemProf.h.
ReadData()
data_type llvm::memprof::CallStackLookupTrait::ReadData (uint64_t K, const unsigned char * D, offset_type Length) inline
Definition at line 784 of file MemProf.h.
References assert(), D, F, I, llvm::Length, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::support::endian::readNext(), and llvm::SmallVectorImpl< T >::reserve().
ReadKey()
uint64_t llvm::memprof::CallStackLookupTrait::ReadKey (const unsigned char * D, offset_type) inline
Definition at line 779 of file MemProf.h.
References D, and llvm::support::endian::readNext().
ReadKeyDataLength()
static std::pair< offset_type, offset_type > llvm::memprof::CallStackLookupTrait::ReadKeyDataLength (const unsigned char *& D) inline static
Definition at line 769 of file MemProf.h.
References D, and llvm::support::endian::readNext().
The documentation for this class was generated from the following file:
include/llvm/ProfileData/MemProf.h