LLVM: llvm::RISCVMatInt::Inst Class Reference
llvm::RISCVMatInt::Inst Class Reference
#include "Target/RISCV/MCTargetDesc/RISCVMatInt.h"
Public Member Functions
Inst (unsigned Opc, int64_t I)
unsigned getOpcode () const
int64_t getImm () const
OpndKind getOpndKind () const
Detailed Description
Definition at line 29 of file RISCVMatInt.h.
Constructor & Destructor Documentation
Inst()
llvm::RISCVMatInt::Inst::Inst (unsigned Opc, int64_t I) inline
Definition at line 34 of file RISCVMatInt.h.
References assert(), I, and llvm::RISCVMatInt::Imm.
Member Function Documentation
getImm()
int64_t llvm::RISCVMatInt::Inst::getImm () const inline
Definition at line 39 of file RISCVMatInt.h.
References llvm::RISCVMatInt::Imm.
Referenced by llvm::RISCVMatInt::generateMCInstSeq().
getOpcode()
unsigned llvm::RISCVMatInt::Inst::getOpcode () const inline
Definition at line 38 of file RISCVMatInt.h.
Referenced by llvm::RISCVMatInt::generateMCInstSeq().
getOpndKind()
OpndKind llvm::RISCVMatInt::Inst::getOpndKind () const
Definition at line 521 of file RISCVMatInt.cpp.
References llvm::RISCVMatInt::Imm, llvm_unreachable, llvm::RISCVMatInt::RegImm, llvm::RISCVMatInt::RegReg, and llvm::RISCVMatInt::RegX0.
Referenced by llvm::RISCVMatInt::generateMCInstSeq().
The documentation for this class was generated from the following files:
lib/Target/RISCV/MCTargetDesc/RISCVMatInt.h
lib/Target/RISCV/MCTargetDesc/RISCVMatInt.cpp