LLVM: llvm::object::AbstractArchiveMemberHeader Class Reference
llvm::object::AbstractArchiveMemberHeader Class Reference abstract
#include "llvm/Object/Archive.h"
Public Member Functions
virtual std::unique_ptr< AbstractArchiveMemberHeader > clone () const =0
virtual ~AbstractArchiveMemberHeader ()=default
virtual Expected< StringRef > getRawName () const =0
Get the name without looking up long names.
virtual StringRef getRawAccessMode () const =0
virtual StringRef getRawLastModified () const =0
virtual StringRef getRawUID () const =0
virtual StringRef getRawGID () const =0
virtual Expected< StringRef > getName (uint64_t Size) const =0
Get the name looking up long names.
virtual Expected< uint64_t > getSize () const =0
virtual uint64_t getOffset () const =0
virtual Expected< const char * > getNextChildLoc () const =0
Get next file member location.
virtual Expected< bool > isThin () const =0
Expected< sys::fs::perms > getAccessMode () const
Expected< sys::TimePoint< std::chrono::seconds > > getLastModified () const
Expected< unsigned > getUID () const
Expected< unsigned > getGID () const
virtual uint64_t getSizeOf () const =0
Returns the size in bytes of the format-defined member header of the concrete archive type.
Public Attributes
const Archive * Parent
Protected Member Functions
AbstractArchiveMemberHeader (const Archive *Parent)
Friends
class Archive
Detailed Description
Definition at line 39 of file Archive.h.
Constructor & Destructor Documentation
AbstractArchiveMemberHeader()
llvm::object::AbstractArchiveMemberHeader::AbstractArchiveMemberHeader (const Archive * Parent) inline protected
Definition at line 41 of file Archive.h.
~AbstractArchiveMemberHeader()
virtual llvm::object::AbstractArchiveMemberHeader::~AbstractArchiveMemberHeader () virtual default
Member Function Documentation
clone()
virtual std::unique_ptr< AbstractArchiveMemberHeader > llvm::object::AbstractArchiveMemberHeader::clone () const pure virtual
Implemented in llvm::object::ArchiveMemberHeader, and llvm::object::BigArchiveMemberHeader.
getAccessMode()
Expected< sys::fs::perms > AbstractArchiveMemberHeader::getAccessMode () const
Definition at line 385 of file Archive.cpp.
References getArchiveMemberOctField(), getRawAccessMode(), Parent, and llvm::Expected< T >::takeError().
getGID()
Expected< unsigned > AbstractArchiveMemberHeader::getGID () const
Definition at line 411 of file Archive.cpp.
References llvm::StringRef::empty(), getArchiveMemberDecField(), getRawGID(), and Parent.
getLastModified()
Expected< sys::TimePoint< std::chrono::seconds > > AbstractArchiveMemberHeader::getLastModified () const
Definition at line 394 of file Archive.cpp.
References getArchiveMemberDecField(), getRawLastModified(), Parent, llvm::Expected< T >::takeError(), and llvm::sys::toTimePoint().
getName()
virtual Expected< StringRef > llvm::object::AbstractArchiveMemberHeader::getName (uint64_t Size) const pure virtual
Get the name looking up long names.
Implemented in llvm::object::ArchiveMemberHeader, and llvm::object::BigArchiveMemberHeader.
Referenced by createMemberHeaderParseError().
getNextChildLoc()
virtual Expected< const char * > llvm::object::AbstractArchiveMemberHeader::getNextChildLoc () const pure virtual
Get next file member location.
Implemented in llvm::object::ArchiveMemberHeader, and llvm::object::BigArchiveMemberHeader.
getOffset()
virtual uint64_t llvm::object::AbstractArchiveMemberHeader::getOffset () const pure virtual
Implemented in llvm::object::CommonArchiveMemberHeader< T >, llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >, and llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >.
Referenced by getArchiveMemberDecField(), and getArchiveMemberOctField().
getRawAccessMode()
virtual StringRef llvm::object::AbstractArchiveMemberHeader::getRawAccessMode () const pure virtual
Implemented in llvm::object::CommonArchiveMemberHeader< T >, llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >, and llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >.
Referenced by getAccessMode().
getRawGID()
virtual StringRef llvm::object::AbstractArchiveMemberHeader::getRawGID () const pure virtual
Implemented in llvm::object::CommonArchiveMemberHeader< T >, llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >, and llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >.
Referenced by getGID().
getRawLastModified()
virtual StringRef llvm::object::AbstractArchiveMemberHeader::getRawLastModified () const pure virtual
Implemented in llvm::object::CommonArchiveMemberHeader< T >, llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >, and llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >.
Referenced by getLastModified().
getRawName()
virtual Expected< StringRef > llvm::object::AbstractArchiveMemberHeader::getRawName () const pure virtual
Get the name without looking up long names.
Implemented in llvm::object::ArchiveMemberHeader, and llvm::object::BigArchiveMemberHeader.
getRawUID()
virtual StringRef llvm::object::AbstractArchiveMemberHeader::getRawUID () const pure virtual
Implemented in llvm::object::CommonArchiveMemberHeader< T >, llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >, and llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >.
Referenced by getUID().
getSize()
virtual Expected< uint64_t > llvm::object::AbstractArchiveMemberHeader::getSize () const pure virtual
Implemented in llvm::object::ArchiveMemberHeader, and llvm::object::BigArchiveMemberHeader.
getSizeOf()
virtual uint64_t llvm::object::AbstractArchiveMemberHeader::getSizeOf () const pure virtual
Returns the size in bytes of the format-defined member header of the concrete archive type.
Implemented in llvm::object::CommonArchiveMemberHeader< T >, llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >, and llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >.
getUID()
Expected< unsigned > AbstractArchiveMemberHeader::getUID () const
Definition at line 404 of file Archive.cpp.
References getArchiveMemberDecField(), getRawUID(), and Parent.
isThin()
virtual Expected< bool > llvm::object::AbstractArchiveMemberHeader::isThin () const pure virtual
Implemented in llvm::object::ArchiveMemberHeader, and llvm::object::BigArchiveMemberHeader.
Friends And Related Symbol Documentation
Archive
friend class Archive friend
Definition at line 44 of file Archive.h.
Member Data Documentation
Parent
const Archive* llvm::object::AbstractArchiveMemberHeader::Parent
Definition at line 73 of file Archive.h.
Referenced by llvm::object::ArchiveMemberHeader::ArchiveMemberHeader(), llvm::object::BigArchiveMemberHeader::BigArchiveMemberHeader(), createMemberHeaderParseError(), getAccessMode(), getGID(), getLastModified(), llvm::object::ArchiveMemberHeader::getName(), llvm::object::ArchiveMemberHeader::getNextChildLoc(), llvm::object::BigArchiveMemberHeader::getNextChildLoc(), llvm::object::BigArchiveMemberHeader::getNextOffset(), llvm::object::ArchiveMemberHeader::getRawName(), llvm::object::BigArchiveMemberHeader::getRawName(), llvm::object::BigArchiveMemberHeader::getRawNameSize(), llvm::object::ArchiveMemberHeader::getSize(), llvm::object::BigArchiveMemberHeader::getSize(), getUID(), and llvm::object::ArchiveMemberHeader::isThin().
The documentation for this class was generated from the following files:
include/llvm/Object/Archive.h
lib/Object/Archive.cpp