LLVM: llvm::BlockFrequencyPrinterPass Class Reference
llvm::BlockFrequencyPrinterPass Class Reference
Printer pass for the BlockFrequencyInfo results.
#include "llvm/Analysis/BlockFrequencyInfo.h"
Public Member Functions
BlockFrequencyPrinterPass (raw_ostream &OS)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< BlockFrequencyPrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< BlockFrequencyPrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Printer pass for the BlockFrequencyInfo results.
Definition at line 129 of file BlockFrequencyInfo.h.
Constructor & Destructor Documentation
BlockFrequencyPrinterPass()
llvm::BlockFrequencyPrinterPass::BlockFrequencyPrinterPass (raw_ostream & OS) inline explicit
Definition at line 134 of file BlockFrequencyInfo.h.
References OS.
Member Function Documentation
isRequired()
static bool llvm::BlockFrequencyPrinterPass::isRequired () inline static
Definition at line 138 of file BlockFrequencyInfo.h.
run()
PreservedAnalyses BlockFrequencyPrinterPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 343 of file BlockFrequencyInfo.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), OS, and llvm::print().
The documentation for this class was generated from the following files:
include/llvm/Analysis/BlockFrequencyInfo.h
lib/Analysis/BlockFrequencyInfo.cpp