LLVM: llvm::dwarf_linker::parallel::CompileUnit::OutputUnitVariantPtr Class Reference
llvm::dwarf_linker::parallel::CompileUnit::OutputUnitVariantPtr Class Reference
Output unit selector.
#include "DWARFLinker/Parallel/DWARFLinkerCompileUnit.h"
Public Member Functions
OutputUnitVariantPtr (CompileUnit *U)
OutputUnitVariantPtr (TypeUnit *U)
DwarfUnit * operator-> ()
Accessor for common functionality.
bool isCompileUnit ()
bool isTypeUnit ()
CompileUnit * getAsCompileUnit ()
Returns CompileUnit if applicable.
TypeUnit * getAsTypeUnit ()
Returns TypeUnit if applicable.
Protected Attributes
PointerUnion< CompileUnit *, TypeUnit * > Ptr
Detailed Description
Output unit selector.
Definition at line 580 of file DWARFLinkerCompileUnit.h.
Constructor & Destructor Documentation
OutputUnitVariantPtr() [1/2]
CompileUnit::OutputUnitVariantPtr::OutputUnitVariantPtr (CompileUnit * U)
Definition at line 1800 of file DWARFLinkerCompileUnit.cpp.
References assert().
OutputUnitVariantPtr() [2/2]
CompileUnit::OutputUnitVariantPtr::OutputUnitVariantPtr (TypeUnit * U)
Definition at line 1805 of file DWARFLinkerCompileUnit.cpp.
References assert().
Member Function Documentation
getAsCompileUnit()
CompileUnit * CompileUnit::OutputUnitVariantPtr::getAsCompileUnit ()
Returns CompileUnit if applicable.
Definition at line 1824 of file DWARFLinkerCompileUnit.cpp.
References Ptr.
Referenced by llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneAddressAttr(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneDieRefAttr(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneScalarAttr(), llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::saveNameRecord(), llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::saveNamespaceRecord(), llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::saveObjCNameRecord(), and llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::saveTypeRecord().
getAsTypeUnit()
TypeUnit * CompileUnit::OutputUnitVariantPtr::getAsTypeUnit ()
Returns TypeUnit if applicable.
Definition at line 1828 of file DWARFLinkerCompileUnit.cpp.
References Ptr.
Referenced by llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::saveNamespaceRecord(), and llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::saveTypeRecord().
isCompileUnit()
bool CompileUnit::OutputUnitVariantPtr::isCompileUnit ()
Definition at line 1816 of file DWARFLinkerCompileUnit.cpp.
References Ptr.
Referenced by llvm::dwarf_linker::parallel::DIEAttributeCloner::clone(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneScalarAttr(), llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::saveNamespaceRecord(), and llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::saveTypeRecord().
isTypeUnit()
bool CompileUnit::OutputUnitVariantPtr::isTypeUnit ()
Definition at line 1820 of file DWARFLinkerCompileUnit.cpp.
References Ptr.
Referenced by llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneAddressAttr(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneBlockAttr(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneDieRefAttr(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneScalarAttr(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneStringAttr(), and llvm::dwarf_linker::parallel::DIEAttributeCloner::DIEAttributeCloner().
operator->()
DwarfUnit * CompileUnit::OutputUnitVariantPtr::operator-> ()
Accessor for common functionality.
Definition at line 1809 of file DWARFLinkerCompileUnit.cpp.
References llvm::isCompileUnit().
Member Data Documentation
Ptr
PointerUnion<CompileUnit *, TypeUnit *> llvm::dwarf_linker::parallel::CompileUnit::OutputUnitVariantPtr::Ptr protected
Definition at line 599 of file DWARFLinkerCompileUnit.h.
The documentation for this class was generated from the following files:
lib/DWARFLinker/Parallel/DWARFLinkerCompileUnit.h
lib/DWARFLinker/Parallel/DWARFLinkerCompileUnit.cpp