LLVM: StackNode Class Reference
StackNode Class Reference
Public Member Functions
StackNode (ScopedHashTable< const SCEV *, LoadValue > &AvailableLoads, unsigned cg, DomTreeNode *N, DomTreeNode::const_iterator Child, DomTreeNode::const_iterator End)
unsigned currentGeneration () const
unsigned childGeneration () const
void childGeneration (unsigned generation)
DomTreeNode * node ()
DomTreeNode::const_iterator childIter () const
DomTreeNode * nextChild ()
DomTreeNode::const_iterator end () const
bool isProcessed () const
void process ()
Detailed Description
Definition at line 223 of file LoopUnroll.cpp.
Constructor & Destructor Documentation
StackNode()
StackNode::StackNode (ScopedHashTable< const SCEV *, LoadValue > & AvailableLoads, unsigned cg, DomTreeNode * N, DomTreeNode::const_iterator Child, DomTreeNode::const_iterator End) inline
Definition at line 233 of file LoopUnroll.cpp.
Member Function Documentation
childGeneration() [1/2]
unsigned StackNode::childGeneration () const inline
Definition at line 240 of file LoopUnroll.cpp.
Referenced by loadCSE().
childGeneration() [2/2]
void StackNode::childGeneration (unsigned generation) inline
Definition at line 241 of file LoopUnroll.cpp.
References generation.
childIter()
DomTreeNode::const_iterator StackNode::childIter () const inline
Definition at line 243 of file LoopUnroll.cpp.
Referenced by loadCSE().
currentGeneration()
unsigned StackNode::currentGeneration () const inline
Definition at line 239 of file LoopUnroll.cpp.
Referenced by loadCSE().
end()
DomTreeNode::const_iterator StackNode::end () const inline
Definition at line 251 of file LoopUnroll.cpp.
Referenced by loadCSE().
isProcessed()
bool StackNode::isProcessed () const inline
Definition at line 252 of file LoopUnroll.cpp.
Referenced by loadCSE().
nextChild()
DomTreeNode * StackNode::nextChild () inline
Definition at line 245 of file LoopUnroll.cpp.
Referenced by loadCSE().
node()
DomTreeNode * StackNode::node () inline
Definition at line 242 of file LoopUnroll.cpp.
Referenced by loadCSE().
process()
void StackNode::process () inline
Definition at line 253 of file LoopUnroll.cpp.
Referenced by loadCSE().
The documentation for this class was generated from the following file:
lib/Transforms/Utils/LoopUnroll.cpp