LLVM: llvm::BufferByteStreamer Class Reference
llvm::BufferByteStreamer Class Reference final
#include "CodeGen/AsmPrinter/ByteStreamer.h"
Public Member Functions
BufferByteStreamer (SmallVectorImpl< char > &Buffer, std::vector< std::string > &Comments, bool GenerateComments)
void emitInt8 (uint8_t Byte, const Twine &Comment) override
void emitSLEB128 (uint64_t DWord, const Twine &Comment) override
void emitULEB128 (uint64_t DWord, const Twine &Comment, unsigned PadTo) override
unsigned emitDIERef (const DIE &D) override
Public Member Functions inherited from llvm::ByteStreamer
Public Attributes
const bool GenerateComments
Only verbose textual output needs comments.
Additional Inherited Members
Protected Member Functions inherited from llvm::ByteStreamer
~ByteStreamer ()=default
ByteStreamer (const ByteStreamer &)=default
ByteStreamer ()=default
Detailed Description
Definition at line 90 of file ByteStreamer.h.
Constructor & Destructor Documentation
BufferByteStreamer()
llvm::BufferByteStreamer::BufferByteStreamer (SmallVectorImpl< char > & Buffer, std::vector< std::string > & Comments, bool GenerateComments) inline
Definition at line 101 of file ByteStreamer.h.
Member Function Documentation
emitDIERef()
unsigned llvm::BufferByteStreamer::emitDIERef (const DIE & D) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 134 of file ByteStreamer.h.
References assert(), D, emitULEB128(), llvm::Offset, and ULEB128PadSize.
emitInt8()
void llvm::BufferByteStreamer::emitInt8 (uint8_t Byte, const Twine & Comment) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 105 of file ByteStreamer.h.
References GenerateComments, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
emitSLEB128()
void llvm::BufferByteStreamer::emitSLEB128 (uint64_t DWord, const Twine & Comment) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 110 of file ByteStreamer.h.
References llvm::encodeSLEB128(), GenerateComments, and llvm::Length.
emitULEB128()
void llvm::BufferByteStreamer::emitULEB128 (uint64_t DWord, const Twine & Comment, unsigned PadTo) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 122 of file ByteStreamer.h.
References llvm::encodeULEB128(), GenerateComments, and llvm::Length.
Referenced by emitDIERef().
Member Data Documentation
GenerateComments
const bool llvm::BufferByteStreamer::GenerateComments
Only verbose textual output needs comments.
This will be set to true for that case, and false otherwise. If false, comments passed in to the emit methods will be ignored.
Definition at line 99 of file ByteStreamer.h.
Referenced by emitInt8(), emitSLEB128(), and emitULEB128().
The documentation for this class was generated from the following file:
lib/CodeGen/AsmPrinter/ByteStreamer.h