LLVM: llvm::StackProtectorPass Class Reference
llvm::StackProtectorPass Class Reference
#include "llvm/CodeGen/StackProtector.h"
Public Member Functions
StackProtectorPass (const TargetMachine *TM)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &FAM)
Public Member Functions inherited from llvm::PassInfoMixin< StackProtectorPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< StackProtectorPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 85 of file StackProtector.h.
Constructor & Destructor Documentation
StackProtectorPass()
llvm::StackProtectorPass::StackProtectorPass (const TargetMachine * TM) inline explicit
Definition at line 89 of file StackProtector.h.
References TM.
Member Function Documentation
run()
PreservedAnalyses StackProtectorPass::run (Function & F, FunctionAnalysisManager & FAM)
Definition at line 118 of file StackProtector.cpp.
References llvm::PreservedAnalyses::all(), assert(), Changed, llvm::classifyEHPersonality(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), InsertStackProtectors(), llvm::isFuncletEHPersonality(), and llvm::PreservedAnalyses::preserve().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/StackProtector.h
lib/CodeGen/StackProtector.cpp