LLVM: llvm::sandboxir::RemoveFromParent Class Reference
llvm::sandboxir::RemoveFromParent Class Reference
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
RemoveFromParent (Instruction *RemovedI, Tracker &Tracker)
void revert () final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
Instruction * getInstruction () const
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
IRChangeBase (Tracker &Parent)
virtual ~IRChangeBase ()=default
unsigned getIdx () const
\Returns the index of this change by iterating over all changes in the tracker.
void dumpCommon (raw_ostream &OS) const
Additional Inherited Members
Protected Attributes inherited from llvm::sandboxir::IRChangeBase
Tracker & Parent
Detailed Description
Definition at line 139 of file Tracker.h.
Constructor & Destructor Documentation
RemoveFromParent()
RemoveFromParent::RemoveFromParent (Instruction * RemovedI, Tracker & Tracker)
Definition at line 103 of file Tracker.cpp.
References llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), and llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent().
Member Function Documentation
accept()
void llvm::sandboxir::RemoveFromParent::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 148 of file Tracker.h.
dump() [1/2]
void RemoveFromParent::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 121 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::RemoveFromParent::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 151 of file Tracker.h.
References llvm::sandboxir::IRChangeBase::dumpCommon(), and OS.
getInstruction()
Instruction * llvm::sandboxir::RemoveFromParent::getInstruction () const inline
Definition at line 149 of file Tracker.h.
revert()
void RemoveFromParent::revert () final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 111 of file Tracker.cpp.
References llvm::Instruction::insertBefore(), and llvm::Instruction::insertInto().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp