LLVM: llvm::SPIRVInlineAsmLowering Class Reference
llvm::SPIRVInlineAsmLowering Class Reference
#include "Target/SPIRV/SPIRVInlineAsmLowering.h"
Public Member Functions
SPIRVInlineAsmLowering (const SPIRVTargetLowering &TLI)
bool lowerAsmOperandForConstraint (Value *Val, StringRef Constraint, std::vector< MachineOperand > &Ops, MachineIRBuilder &MIRBuilder) const override
Lower the specified operand into the Ops vector.
Public Member Functions inherited from llvm::InlineAsmLowering
bool lowerInlineAsm (MachineIRBuilder &MIRBuilder, const CallBase &CB, std::function< ArrayRef< Register >(const Value &Val)> GetOrCreateVRegs) const
Lower the given inline asm call instruction GetOrCreateVRegs is a callback to materialize a register for the input and output operands of the inline asm.
InlineAsmLowering (const TargetLowering *TLI)
virtual ~InlineAsmLowering ()=default
Additional Inherited Members
Protected Member Functions inherited from llvm::InlineAsmLowering
const TargetLowering * getTLI () const
Getter for generic TargetLowering class.
template<class XXXTargetLowering >
const XXXTargetLowering * getTLI () const
Getter for target specific TargetLowering class.
Detailed Description
Definition at line 23 of file SPIRVInlineAsmLowering.h.
Constructor & Destructor Documentation
SPIRVInlineAsmLowering()
SPIRVInlineAsmLowering::SPIRVInlineAsmLowering (const SPIRVTargetLowering & TLI)
Definition at line 21 of file SPIRVInlineAsmLowering.cpp.
Member Function Documentation
lowerAsmOperandForConstraint()
bool SPIRVInlineAsmLowering::lowerAsmOperandForConstraint (Value * Val, StringRef Constraint, std::vector< MachineOperand > & Ops, MachineIRBuilder & MIRBuilder) const override virtual
Lower the specified operand into the Ops vector.
Val is the IR input value to be lowered Constraint is the user supplied constraint string Ops is the vector to be filled with the lowered operands
Returns
True if the lowering succeeds, false otherwise.
Reimplemented from llvm::InlineAsmLowering.
Definition at line 24 of file SPIRVInlineAsmLowering.cpp.
References llvm::MachineOperand::CreateFPImm(), llvm::dyn_cast(), II, llvm::isa(), and llvm::InlineAsmLowering::lowerAsmOperandForConstraint().
The documentation for this class was generated from the following files:
lib/Target/SPIRV/SPIRVInlineAsmLowering.h
lib/Target/SPIRV/SPIRVInlineAsmLowering.cpp