LLVM: llvm::objcopy::elf::SectionIndexSection Class Reference
llvm::objcopy::elf::SectionIndexSection Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
virtual ~SectionIndexSection ()
void addIndex (uint32_t Index)
void reserve (size_t NumSymbols)
void setSymTab (SymbolTableSection *SymTab)
Error initialize (SectionTableRef SecTable) override
void finalize () override
Error accept (SectionVisitor &Visitor) const override
Error accept (MutableSectionVisitor &Visitor) override
SectionIndexSection ()
Public Member Functions inherited from llvm::objcopy::elf::SectionBase
SectionBase ()=default
SectionBase (const SectionBase &)=default
virtual ~SectionBase ()=default
virtual Error removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove)
virtual Error removeSymbols (function_ref< bool(const Symbol &)> ToRemove)
virtual void markSymbols ()
virtual void replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > &)
virtual bool hasContents () const
virtual void onRemove ()
virtual void restoreSymTabLink (SymbolTableSection &)
Additional Inherited Members
Public Attributes inherited from llvm::objcopy::elf::SectionBase
std::string Name
Segment * ParentSegment = nullptr
uint64_t HeaderOffset = 0
uint32_t Index = 0
uint32_t OriginalIndex = 0
uint64_t OriginalFlags = 0
uint64_t OriginalType = ELF::SHT_NULL
uint64_t OriginalOffset = std::numeric_limits<uint64_t>::max()
uint64_t Addr = 0
uint64_t Align = 1
uint32_t EntrySize = 0
uint64_t Flags = 0
uint64_t Info = 0
uint64_t Link = ELF::SHN_UNDEF
uint64_t NameIndex = 0
uint64_t Offset = 0
uint64_t Size = 0
uint64_t Type = ELF::SHT_NULL
ArrayRef< uint8_t > OriginalData
bool HasSymbol = false
Detailed Description
Definition at line 775 of file ELFObject.h.
Constructor & Destructor Documentation
~SectionIndexSection()
virtual llvm::objcopy::elf::SectionIndexSection::~SectionIndexSection () inline virtual
Definition at line 783 of file ELFObject.h.
SectionIndexSection()
llvm::objcopy::elf::SectionIndexSection::SectionIndexSection () inline
Definition at line 799 of file ELFObject.h.
References llvm::objcopy::elf::SectionBase::EntrySize, llvm::objcopy::elf::SectionBase::Name, llvm::objcopy::elf::SectionBase::OriginalType, and llvm::ELF::SHT_SYMTAB_SHNDX.
Member Function Documentation
accept() [1/2]
Error SectionIndexSection::accept (MutableSectionVisitor & Visitor) override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 647 of file ELFObject.cpp.
References llvm::objcopy::elf::MutableSectionVisitor::visit().
accept() [2/2]
Error SectionIndexSection::accept (SectionVisitor & Visitor) const override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 643 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionVisitor::visit().
addIndex()
void llvm::objcopy::elf::SectionIndexSection::addIndex (uint32_t Index) inline
Definition at line 784 of file ELFObject.h.
References assert(), and llvm::objcopy::elf::SectionBase::Size.
Referenced by llvm::objcopy::elf::SymbolTableSection::fillShndxTable().
finalize()
void SectionIndexSection::finalize () override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 641 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::Index, and llvm::objcopy::elf::SectionBase::Link.
initialize()
Error SectionIndexSection::initialize (SectionTableRef SecTable) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 624 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionTableRef::getSectionOfType(), llvm::objcopy::elf::SectionBase::Link, llvm::objcopy::elf::SectionBase::Name, llvm::objcopy::elf::SymbolTableSection::setShndxTable(), setSymTab(), llvm::objcopy::elf::SectionBase::Size, llvm::Error::success(), and llvm::Expected< T >::takeError().
reserve()
void llvm::objcopy::elf::SectionIndexSection::reserve (size_t NumSymbols) inline
Definition at line 789 of file ELFObject.h.
References llvm::objcopy::elf::SectionBase::Size.
Referenced by llvm::objcopy::elf::SymbolTableSection::prepareForLayout(), and llvm::objcopy::elf::Object::removeSections().
setSymTab()
void llvm::objcopy::elf::SectionIndexSection::setSymTab (SymbolTableSection * SymTab) inline
Definition at line 793 of file ELFObject.h.
Referenced by llvm::objcopy::elf::ELFWriter< ELFT >::finalize(), and initialize().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp