LLVM: llvm::AttributeSetNode Class Reference
llvm::AttributeSetNode Class Reference final
This class represents a group of attributes that apply to one element: function, return type, or parameter.
#include "IR/AttributeImpl.h"
Public Types
using iterator = const Attribute *
Public Member Functions
AttributeSetNode (const AttributeSetNode &)=delete
AttributeSetNode & operator= (const AttributeSetNode &)=delete
void operator delete (void *p)
unsigned getNumAttributes () const
Return the number of attributes this AttributeList contains.
bool hasAttribute (Attribute::AttrKind Kind) const
bool hasAttribute (StringRef Kind) const
bool hasAttributes () const
Attribute getAttribute (Attribute::AttrKind Kind) const
Attribute getAttribute (StringRef Kind) const
MaybeAlign getAlignment () const
MaybeAlign getStackAlignment () const
uint64_t getDereferenceableBytes () const
uint64_t getDereferenceableOrNullBytes () const
std::optional< std::pair< unsigned, std::optional< unsigned > > > getAllocSizeArgs () const
unsigned getVScaleRangeMin () const
std::optional< unsigned > getVScaleRangeMax () const
UWTableKind getUWTableKind () const
AllocFnKind getAllocKind () const
MemoryEffects getMemoryEffects () const
FPClassTest getNoFPClass () const
std::string getAsString (bool InAttrGrp) const
Type * getAttributeType (Attribute::AttrKind Kind) const
iterator begin () const
iterator end () const
void Profile (FoldingSetNodeID &ID) const
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static AttributeSetNode * get (LLVMContext &C, const AttrBuilder &B)
static AttributeSetNode * get (LLVMContext &C, ArrayRef< Attribute > Attrs)
static void Profile (FoldingSetNodeID &ID, ArrayRef< Attribute > AttrList)
Detailed Description
This class represents a group of attributes that apply to one element: function, return type, or parameter.
Definition at line 296 of file AttributeImpl.h.
Member Typedef Documentation
iterator
using llvm::AttributeSetNode::iterator = const Attribute *
Definition at line 350 of file AttributeImpl.h.
Constructor & Destructor Documentation
AttributeSetNode()
llvm::AttributeSetNode::AttributeSetNode (const AttributeSetNode &) delete
Member Function Documentation
begin()
iterator llvm::AttributeSetNode::begin () const inline
Definition at line 352 of file AttributeImpl.h.
References llvm::TrailingObjects< AttributeSetNode, Attribute >::getTrailingObjects().
Referenced by llvm::AttributeSet::begin(), end(), getAsString(), and Profile().
end()
iterator llvm::AttributeSetNode::end () const inline
Definition at line 353 of file AttributeImpl.h.
References begin().
Referenced by llvm::AttributeSet::end(), getAsString(), and Profile().
get() [1/2]
AttributeSetNode * AttributeSetNode::get (LLVMContext & C, ArrayRef< Attribute > Attrs) static
Definition at line 1041 of file Attributes.cpp.
References llvm::CallingConv::C, and llvm::sort().
get() [2/2]
AttributeSetNode * AttributeSetNode::get (LLVMContext & C, const AttrBuilder & B) static
Definition at line 1078 of file Attributes.cpp.
References B, and llvm::CallingConv::C.
Referenced by llvm::AttributeSet::get(), and llvm::AttributeSet::get().
getAlignment()
MaybeAlign AttributeSetNode::getAlignment () const
Definition at line 1113 of file Attributes.cpp.
References A.
Referenced by llvm::AttributeSet::getAlignment().
getAllocKind()
AllocFnKind AttributeSetNode::getAllocKind () const
Definition at line 1168 of file Attributes.cpp.
References A, and llvm::Unknown.
Referenced by llvm::AttributeSet::getAllocKind().
getAllocSizeArgs()
std::optional< std::pair< unsigned, std::optional< unsigned > > > AttributeSetNode::getAllocSizeArgs () const
Definition at line 1144 of file Attributes.cpp.
References A.
Referenced by llvm::AttributeSet::getAllocSizeArgs().
getAsString()
std::string AttributeSetNode::getAsString (bool InAttrGrp) const
Definition at line 1186 of file Attributes.cpp.
References begin(), E, end(), and I.
Referenced by llvm::AttributeSet::getAsString().
getAttribute() [1/2]
Attribute AttributeSetNode::getAttribute (Attribute::AttrKind Kind) const
Definition at line 1103 of file Attributes.cpp.
References A.
Referenced by llvm::AttributeSet::getAttribute(), and llvm::AttributeSet::getAttribute().
getAttribute() [2/2]
Attribute AttributeSetNode::getAttribute (StringRef Kind) const
Definition at line 1109 of file Attributes.cpp.
getAttributeType()
Type * AttributeSetNode::getAttributeType (Attribute::AttrKind Kind) const
Definition at line 1125 of file Attributes.cpp.
References A.
Referenced by llvm::AttributeSet::getByRefType(), llvm::AttributeSet::getByValType(), llvm::AttributeSet::getElementType(), llvm::AttributeSet::getInAllocaType(), llvm::AttributeSet::getPreallocatedType(), and llvm::AttributeSet::getStructRetType().
getDereferenceableBytes()
uint64_t AttributeSetNode::getDereferenceableBytes () const
Definition at line 1131 of file Attributes.cpp.
References A.
Referenced by llvm::AttributeSet::getDereferenceableBytes().
getDereferenceableOrNullBytes()
uint64_t AttributeSetNode::getDereferenceableOrNullBytes () const
Definition at line 1137 of file Attributes.cpp.
References A.
Referenced by llvm::AttributeSet::getDereferenceableOrNullBytes().
getMemoryEffects()
MemoryEffects AttributeSetNode::getMemoryEffects () const
Definition at line 1174 of file Attributes.cpp.
References A, and llvm::MemoryEffectsBase< LocationEnum >::unknown().
Referenced by llvm::AttributeSet::getMemoryEffects().
getNoFPClass()
FPClassTest AttributeSetNode::getNoFPClass () const
Definition at line 1180 of file Attributes.cpp.
References A, and llvm::fcNone.
Referenced by llvm::AttributeSet::getNoFPClass().
getNumAttributes()
unsigned llvm::AttributeSetNode::getNumAttributes () const inline
Return the number of attributes this AttributeList contains.
Definition at line 324 of file AttributeImpl.h.
Referenced by llvm::AttributeSet::getNumAttributes().
getStackAlignment()
MaybeAlign AttributeSetNode::getStackAlignment () const
Definition at line 1119 of file Attributes.cpp.
References A.
Referenced by llvm::AttributeSet::getStackAlignment().
getUWTableKind()
UWTableKind AttributeSetNode::getUWTableKind () const
Definition at line 1162 of file Attributes.cpp.
References A, and llvm::None.
Referenced by llvm::AttributeSet::getUWTableKind().
getVScaleRangeMax()
std::optional< unsigned > AttributeSetNode::getVScaleRangeMax () const
Definition at line 1156 of file Attributes.cpp.
References A.
Referenced by llvm::AttributeSet::getVScaleRangeMax().
getVScaleRangeMin()
unsigned AttributeSetNode::getVScaleRangeMin () const
Definition at line 1150 of file Attributes.cpp.
References A.
Referenced by llvm::AttributeSet::getVScaleRangeMin().
hasAttribute() [1/2]
bool llvm::AttributeSetNode::hasAttribute (Attribute::AttrKind Kind) const inline
Definition at line 326 of file AttributeImpl.h.
References llvm::AttributeBitSet::hasAttribute().
Referenced by llvm::AttributeSet::hasAttribute(), and llvm::AttributeSet::hasAttribute().
hasAttribute() [2/2]
bool AttributeSetNode::hasAttribute (StringRef Kind) const
Definition at line 1082 of file Attributes.cpp.
hasAttributes()
bool llvm::AttributeSetNode::hasAttributes () const inline
Definition at line 330 of file AttributeImpl.h.
operator delete()
void llvm::AttributeSetNode::operator delete (void * p) inline
Definition at line 317 of file AttributeImpl.h.
operator=()
AttributeSetNode & llvm::AttributeSetNode::operator= (const AttributeSetNode &) delete
Profile() [1/2]
void llvm::AttributeSetNode::Profile (FoldingSetNodeID & ID) const inline
Definition at line 355 of file AttributeImpl.h.
References llvm::ArrayRef(), begin(), end(), and Profile.
Referenced by llvm::AttributeSet::hasParentContext().
Profile() [2/2]
static void llvm::AttributeSetNode::Profile (FoldingSetNodeID & ID, ArrayRef< Attribute > AttrList) inline static
Definition at line 359 of file AttributeImpl.h.
The documentation for this class was generated from the following files:
lib/IR/AttributeImpl.h
lib/IR/Attributes.cpp