LLVM: llvm::GCNUserSGPRUsageInfo Class Reference
llvm::GCNUserSGPRUsageInfo Class Reference
#include "Target/AMDGPU/GCNSubtarget.h"
Public Types
enum UserSGPRID : unsigned {
ImplicitBufferPtrID = 0 , PrivateSegmentBufferID = 1 , DispatchPtrID = 2 , QueuePtrID = 3 ,
KernargSegmentPtrID = 4 , DispatchIdID = 5 , FlatScratchInitID = 6 , PrivateSegmentSizeID = 7
}
Public Member Functions
bool hasImplicitBufferPtr () const
bool hasPrivateSegmentBuffer () const
bool hasDispatchPtr () const
bool hasQueuePtr () const
bool hasKernargSegmentPtr () const
bool hasDispatchID () const
bool hasFlatScratchInit () const
bool hasPrivateSegmentSize () const
unsigned getNumKernargPreloadSGPRs () const
unsigned getNumUsedUserSGPRs () const
unsigned getNumFreeUserSGPRs ()
void allocKernargPreloadSGPRs (unsigned NumSGPRs)
GCNUserSGPRUsageInfo (const Function &F, const GCNSubtarget &ST)
Static Public Member Functions
static unsigned getNumUserSGPRForField (UserSGPRID ID)
Detailed Description
Definition at line 1590 of file GCNSubtarget.h.
Member Enumeration Documentation
UserSGPRID
enum llvm::GCNUserSGPRUsageInfo::UserSGPRID : unsigned
Enumerator
ImplicitBufferPtrID
PrivateSegmentBufferID
DispatchPtrID
QueuePtrID
KernargSegmentPtrID
DispatchIdID
FlatScratchInitID
PrivateSegmentSizeID
Definition at line 1616 of file GCNSubtarget.h.
Constructor & Destructor Documentation
GCNUserSGPRUsageInfo()
GCNUserSGPRUsageInfo::GCNUserSGPRUsageInfo (const Function & F, const GCNSubtarget & ST)
Definition at line 1051 of file AMDGPUSubtarget.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, CC, DispatchIdID, DispatchPtrID, F, FlatScratchInitID, getNumUserSGPRForField(), HasCalls, hasDispatchID(), hasDispatchPtr(), hasFlatScratchInit(), hasImplicitBufferPtr(), hasKernargSegmentPtr(), hasPrivateSegmentBuffer(), hasPrivateSegmentSize(), hasQueuePtr(), if(), ImplicitBufferPtrID, llvm::AMDGPU::isEntryFunctionCC(), llvm::AMDGPU::isGraphics(), KernargSegmentPtrID, PrivateSegmentBufferID, PrivateSegmentSizeID, QueuePtrID, and llvm::CallingConv::SPIR_KERNEL.
Member Function Documentation
allocKernargPreloadSGPRs()
void GCNUserSGPRUsageInfo::allocKernargPreloadSGPRs (unsigned NumSGPRs)
Definition at line 1120 of file AMDGPUSubtarget.cpp.
References assert(), and llvm::AMDGPU::getMaxNumUserSGPRs().
Referenced by llvm::SIMachineFunctionInfo::addPreloadedKernArg().
getNumFreeUserSGPRs()
unsigned GCNUserSGPRUsageInfo::getNumFreeUserSGPRs ()
Definition at line 1126 of file AMDGPUSubtarget.cpp.
References llvm::AMDGPU::getMaxNumUserSGPRs().
Referenced by llvm::SITargetLowering::allocatePreloadKernArgSGPRs().
getNumKernargPreloadSGPRs()
unsigned llvm::GCNUserSGPRUsageInfo::getNumKernargPreloadSGPRs () const inline
Definition at line 1608 of file GCNSubtarget.h.
getNumUsedUserSGPRs()
unsigned llvm::GCNUserSGPRUsageInfo::getNumUsedUserSGPRs () const inline
Definition at line 1610 of file GCNSubtarget.h.
getNumUserSGPRForField()
static unsigned llvm::GCNUserSGPRUsageInfo::getNumUserSGPRForField (UserSGPRID ID) inline static
Definition at line 1628 of file GCNSubtarget.h.
References DispatchIdID, DispatchPtrID, FlatScratchInitID, ImplicitBufferPtrID, KernargSegmentPtrID, llvm_unreachable, PrivateSegmentBufferID, PrivateSegmentSizeID, and QueuePtrID.
Referenced by GCNUserSGPRUsageInfo().
hasDispatchID()
bool llvm::GCNUserSGPRUsageInfo::hasDispatchID () const inline
Definition at line 1602 of file GCNSubtarget.h.
Referenced by allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateSpecialInputSGPRs(), and GCNUserSGPRUsageInfo().
hasDispatchPtr()
bool llvm::GCNUserSGPRUsageInfo::hasDispatchPtr () const inline
Definition at line 1596 of file GCNSubtarget.h.
Referenced by allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateSpecialInputSGPRs(), GCNUserSGPRUsageInfo(), and llvm::SITargetLowering::LowerFormalArguments().
hasFlatScratchInit()
bool llvm::GCNUserSGPRUsageInfo::hasFlatScratchInit () const inline
Definition at line 1604 of file GCNSubtarget.h.
Referenced by allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateHSAUserSGPRs(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), GCNUserSGPRUsageInfo(), llvm::GCNSubtarget::getReservedNumSGPRs(), llvm::SITargetLowering::LowerFormalArguments(), and llvm::AMDGPUCallLowering::lowerFormalArguments().
hasImplicitBufferPtr()
bool llvm::GCNUserSGPRUsageInfo::hasImplicitBufferPtr () const inline
Definition at line 1592 of file GCNSubtarget.h.
Referenced by llvm::SITargetLowering::allocateHSAUserSGPRs(), GCNUserSGPRUsageInfo(), and llvm::AMDGPUCallLowering::lowerFormalArguments().
hasKernargSegmentPtr()
bool llvm::GCNUserSGPRUsageInfo::hasKernargSegmentPtr () const inline
Definition at line 1600 of file GCNSubtarget.h.
Referenced by allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateHSAUserSGPRs(), GCNUserSGPRUsageInfo(), and llvm::SITargetLowering::LowerFormalArguments().
hasPrivateSegmentBuffer()
bool llvm::GCNUserSGPRUsageInfo::hasPrivateSegmentBuffer () const inline
Definition at line 1594 of file GCNSubtarget.h.
Referenced by allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateHSAUserSGPRs(), and GCNUserSGPRUsageInfo().
hasPrivateSegmentSize()
bool llvm::GCNUserSGPRUsageInfo::hasPrivateSegmentSize () const inline
Definition at line 1606 of file GCNSubtarget.h.
Referenced by llvm::SITargetLowering::allocateHSAUserSGPRs(), and GCNUserSGPRUsageInfo().
hasQueuePtr()
bool llvm::GCNUserSGPRUsageInfo::hasQueuePtr () const inline
Definition at line 1598 of file GCNSubtarget.h.
Referenced by allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateSpecialInputSGPRs(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs(), and GCNUserSGPRUsageInfo().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNSubtarget.h
lib/Target/AMDGPU/AMDGPUSubtarget.cpp