LLVM: llvm::InstrProfReaderIndex< HashTableImpl > Class Template Reference
llvm::InstrProfReaderIndex< HashTableImpl > Class Template Reference
#include "llvm/ProfileData/InstrProfReader.h"
Public Member Functions
InstrProfReaderIndex (const unsigned char *Buckets, const unsigned char *const Payload, const unsigned char *const Base, IndexedInstrProf::HashT HashType, uint64_t Version)
~InstrProfReaderIndex () override=default
Error getRecords (ArrayRef< NamedInstrProfRecord > &Data) override
Error getRecords (StringRef FuncName, ArrayRef< NamedInstrProfRecord > &Data) override
void advanceToNextKey () override
bool atEnd () const override
void setValueProfDataEndianness (llvm::endianness Endianness) override
uint64_t getVersion () const override
bool isIRLevelProfile () const override
bool hasCSIRLevelProfile () const override
bool instrEntryBBEnabled () const override
bool hasSingleByteCoverage () const override
bool functionEntryOnly () const override
bool hasMemoryProfile () const override
bool hasTemporalProfile () const override
InstrProfKind getProfileKind () const override
Error populateSymtab (InstrProfSymtab &Symtab) override
Public Member Functions inherited from llvm::InstrProfReaderIndexBase
virtual ~InstrProfReaderIndexBase ()=default
Friends
class InstrProfReaderItaniumRemapper< HashTableImpl >
Detailed Description
template<typename HashTableImpl>
class llvm::InstrProfReaderIndex< HashTableImpl >
Definition at line 570 of file InstrProfReader.h.
Constructor & Destructor Documentation
InstrProfReaderIndex()
template<typename HashTableImpl > InstrProfReaderIndex::InstrProfReaderIndex (const unsigned char * Buckets, const unsigned char *const Payload, const unsigned char *const Base, IndexedInstrProf::HashT HashType, uint64_t Version)
Definition at line 1001 of file InstrProfReader.cpp.
References llvm::sampleprof::Base, and llvm::Version.
~InstrProfReaderIndex()
template<typename HashTableImpl > llvm::InstrProfReaderIndex< HashTableImpl >::~InstrProfReaderIndex () override default
Member Function Documentation
advanceToNextKey()
template<typename HashTableImpl > void llvm::InstrProfReaderIndex< HashTableImpl >::advanceToNextKey () inline override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 588 of file InstrProfReader.h.
atEnd()
template<typename HashTableImpl > bool llvm::InstrProfReaderIndex< HashTableImpl >::atEnd () const inline override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 590 of file InstrProfReader.h.
functionEntryOnly()
template<typename HashTableImpl > bool llvm::InstrProfReaderIndex< HashTableImpl >::functionEntryOnly () const inline override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 616 of file InstrProfReader.h.
References VARIANT_MASK_FUNCTION_ENTRY_ONLY.
getProfileKind()
template<typename HashTableImpl > InstrProfKind InstrProfReaderIndex::getProfileKind () const override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 1013 of file InstrProfReader.cpp.
References getProfileKindFromVersion().
getRecords() [1/2]
template<typename HashTableImpl > Error InstrProfReaderIndex::getRecords (ArrayRef< NamedInstrProfRecord > & Data) override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 986 of file InstrProfReader.cpp.
References llvm::Data, llvm::eof, llvm::make_error(), llvm::malformed, and llvm::Error::success().
getRecords() [2/2]
template<typename HashTableImpl > Error InstrProfReaderIndex::getRecords (StringRef FuncName, ArrayRef< NamedInstrProfRecord > & Data) override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 971 of file InstrProfReader.cpp.
References llvm::Data, llvm::make_error(), llvm::malformed, llvm::Error::success(), and llvm::unknown_function.
getVersion()
template<typename HashTableImpl > uint64_t llvm::InstrProfReaderIndex< HashTableImpl >::getVersion () const inline override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 598 of file InstrProfReader.h.
References GET_VERSION.
hasCSIRLevelProfile()
template<typename HashTableImpl > bool llvm::InstrProfReaderIndex< HashTableImpl >::hasCSIRLevelProfile () const inline override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 604 of file InstrProfReader.h.
References VARIANT_MASK_CSIR_PROF.
hasMemoryProfile()
template<typename HashTableImpl > bool llvm::InstrProfReaderIndex< HashTableImpl >::hasMemoryProfile () const inline override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 620 of file InstrProfReader.h.
References VARIANT_MASK_MEMPROF.
hasSingleByteCoverage()
template<typename HashTableImpl > bool llvm::InstrProfReaderIndex< HashTableImpl >::hasSingleByteCoverage () const inline override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 612 of file InstrProfReader.h.
References VARIANT_MASK_BYTE_COVERAGE.
hasTemporalProfile()
template<typename HashTableImpl > bool llvm::InstrProfReaderIndex< HashTableImpl >::hasTemporalProfile () const inline override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 624 of file InstrProfReader.h.
References VARIANT_MASK_TEMPORAL_PROF.
instrEntryBBEnabled()
template<typename HashTableImpl > bool llvm::InstrProfReaderIndex< HashTableImpl >::instrEntryBBEnabled () const inline override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 608 of file InstrProfReader.h.
References VARIANT_MASK_INSTR_ENTRY.
isIRLevelProfile()
template<typename HashTableImpl > bool llvm::InstrProfReaderIndex< HashTableImpl >::isIRLevelProfile () const inline override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 600 of file InstrProfReader.h.
References VARIANT_MASK_IR_PROF.
populateSymtab()
template<typename HashTableImpl > Error llvm::InstrProfReaderIndex< HashTableImpl >::populateSymtab (InstrProfSymtab & Symtab) inline override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 630 of file InstrProfReader.h.
References llvm::InstrProfSymtab::create().
setValueProfDataEndianness()
template<typename HashTableImpl > void llvm::InstrProfReaderIndex< HashTableImpl >::setValueProfDataEndianness (llvm::endianness Endianness) inline override virtual
Implements llvm::InstrProfReaderIndexBase.
Definition at line 594 of file InstrProfReader.h.
Friends And Related Symbol Documentation
InstrProfReaderItaniumRemapper< HashTableImpl >
template<typename HashTableImpl > friend class InstrProfReaderItaniumRemapper< HashTableImpl > friend
Definition at line 574 of file InstrProfReader.h.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/InstrProfReader.h
lib/ProfileData/InstrProfReader.cpp