LLVM: llvm::sampleprof::SampleProfileReaderBinary Class Reference
llvm::sampleprof::SampleProfileReaderBinary Class Reference abstract
#include "llvm/ProfileData/SampleProfReader.h"
Public Member Functions
SampleProfileReaderBinary (std::unique_ptr< MemoryBuffer > B, LLVMContext &C, SampleProfileFormat Format=SPF_None)
std::error_code readHeader () override
Read and validate the file header.
std::error_code readImpl () override
Read sample profiles from the associated file.
std::vector< FunctionId > * getNameTable () override
It includes all the names that have samples either in outline instance or inline instance.
Public Member Functions inherited from llvm::sampleprof::SampleProfileReader
SampleProfileReader (std::unique_ptr< MemoryBuffer > B, LLVMContext &C, SampleProfileFormat Format=SPF_None)
virtual ~SampleProfileReader ()=default
void setDiscriminatorMaskedBitFrom (FSDiscriminatorPass P)
Set the bits for FS discriminators.
uint32_t getDiscriminatorMask () const
Get the bitmask the discriminators: For FS profiles, return the bit mask for this pass.
std::error_code read ()
The interface to read sample profiles from the associated file.
void dumpFunctionProfile (const FunctionSamples &FS, raw_ostream &OS=dbgs())
Print the profile for FunctionSamples on stream OS.
virtual bool collectFuncsFromModule ()
Collect functions with definitions in Module M.
void dump (raw_ostream &OS=dbgs())
Print all the profiles on stream OS.
void dumpJson (raw_ostream &OS=dbgs())
Print all the profiles on stream OS in the JSON format.
FunctionSamples * getSamplesFor (const Function &F)
Return the samples collected for function F.
FunctionSamples * getSamplesFor (StringRef Fname)
Return the samples collected for function F.
SampleProfileMap & getProfiles ()
Return all the profiles.
void reportError (int64_t LineNumber, const Twine &Msg) const
Report a parse error message.
ProfileSummary & getSummary () const
Return the profile summary.
MemoryBuffer * getBuffer () const
SampleProfileFormat getFormat () const
Return the profile format.
bool profileIsProbeBased () const
Whether input profile is based on pseudo probes.
bool profileIsCS () const
Whether input profile is fully context-sensitive.
bool profileIsPreInlined () const
Whether input profile contains ShouldBeInlined contexts.
bool profileIsFS () const
Whether input profile is flow-sensitive.
virtual std::unique_ptr< ProfileSymbolList > getProfileSymbolList ()
virtual bool dumpSectionInfo (raw_ostream &OS=dbgs())
bool useMD5 () const
Return whether names in the profile are all MD5 numbers.
virtual void setProfileUseMD5 ()
Force the profile to use MD5 in Sample contexts, even if function names are present.
virtual void setSkipFlatProf (bool Skip)
Don't read profile without context if the flag is set.
virtual bool hasUniqSuffix ()
Return whether any name in the profile contains ".__uniq." suffix.
SampleProfileReaderItaniumRemapper * getRemapper ()
void setModule (const Module *Mod)
Protected Member Functions
template<typename T >
ErrorOr< T > readNumber ()
Read a numeric value of type T from the profile.
template<typename T >
ErrorOr< T > readUnencodedNumber ()
Read a numeric value of type T from the profile.
ErrorOr< StringRef > readString ()
Read a string from the profile.
template<typename T >
ErrorOr< size_t > readStringIndex (T &Table)
Read the string index and check whether it overflows the table.
std::error_code readFuncProfile (const uint8_t *Start)
Read the next function profile instance.
std::error_code readProfile (FunctionSamples &FProfile)
Read the contents of the given profile instance.
std::error_code readMagicIdent ()
Read the contents of Magic number and Version number.
std::error_code readSummary ()
Read profile summary.
std::error_code readNameTable ()
Read the whole name table.
ErrorOr< FunctionId > readStringFromTable (size_t *RetIdx=nullptr)
Read a string indirectly via the name table. Optionally return the index.
ErrorOr< SampleContextFrames > readContextFromTable (size_t *RetIdx=nullptr)
Read a context indirectly via the CSNameTable.
ErrorOr< std::pair< SampleContext, uint64_t > > readSampleContextFromTable ()
Read a context indirectly via the CSNameTable if the profile has context, otherwise same as readStringFromTable, also return its hash value.
Protected Member Functions inherited from llvm::sampleprof::SampleProfileReader
void computeSummary ()
Compute summary for this profile.
Protected Attributes
const uint8_t * Data = nullptr
Points to the current location in the buffer.
const uint8_t * End = nullptr
Points to the end of the buffer.
std::vector< FunctionId > NameTable
Function name table.
std::vector< SampleContextFrameVector > CSNameTable
CSNameTable is used to save full context vectors.
std::vector< uint64_t > MD5SampleContextTable
Table to cache MD5 values of sample contexts corresponding to readSampleContextFromTable(), used to index into Profiles or FuncOffsetTable.
const uint64_t * MD5SampleContextStart = nullptr
The starting address of the table of MD5 values of sample contexts.
Protected Attributes inherited from llvm::sampleprof::SampleProfileReader
SampleProfileMap Profiles
Map every function to its associated profile.
LLVMContext & Ctx
LLVM context used to emit diagnostics.
std::unique_ptr< MemoryBuffer > Buffer
Memory buffer holding the profile file.
std::unique_ptr< ProfileSummary > Summary
Profile summary information.
std::unique_ptr< SampleProfileReaderItaniumRemapper > Remapper
bool ProfileIsProbeBased = false
Whether samples are collected based on pseudo probes.
bool ProfileIsCS = false
Whether function profiles are context-sensitive flat profiles.
bool ProfileIsPreInlined = false
Whether function profile contains ShouldBeInlined contexts.
uint32_t CSProfileCount = 0
Number of context-sensitive profiles.
bool ProfileIsFS = false
Whether the function profiles use FS discriminators.
SampleProfileFormat Format = SPF_None
The format of sample.
const Module * M = nullptr
The current module being compiled if SampleProfileReader is used by compiler.
uint32_t MaskedBitFrom = 31
Zero out the discriminator bits higher than bit MaskedBitFrom (0 based).
bool ProfileIsMD5 = false
Whether the profile uses MD5 for Sample Contexts and function names.
Additional Inherited Members
Static Public Member Functions inherited from llvm::sampleprof::SampleProfileReader
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (StringRef Filename, LLVMContext &C, vfs::FileSystem &FS, FSDiscriminatorPass P=FSDiscriminatorPass::Base, StringRef RemapFilename="")
Create a sample profile reader appropriate to the file format.
static ErrorOr< std::unique_ptr< SampleProfileReader > > create (std::unique_ptr< MemoryBuffer > &B, LLVMContext &C, vfs::FileSystem &FS, FSDiscriminatorPass P=FSDiscriminatorPass::Base, StringRef RemapFilename="")
Create a sample profile reader from the supplied memory buffer.
Static Protected Member Functions inherited from llvm::sampleprof::SampleProfileReader
static std::unique_ptr< ProfileSummary > takeSummary (SampleProfileReader &Reader)
Take ownership of the summary of this reader.
Detailed Description
Definition at line 580 of file SampleProfReader.h.
Constructor & Destructor Documentation
SampleProfileReaderBinary()
llvm::sampleprof::SampleProfileReaderBinary::SampleProfileReaderBinary (std::unique_ptr< MemoryBuffer > B, LLVMContext & C, SampleProfileFormat Format = SPF_None) inline
Definition at line 582 of file SampleProfReader.h.
Member Function Documentation
getNameTable()
std::vector< FunctionId > * llvm::sampleprof::SampleProfileReaderBinary::getNameTable () inline override virtual
It includes all the names that have samples either in outline instance or inline instance.
Reimplemented from llvm::sampleprof::SampleProfileReader.
Definition at line 594 of file SampleProfReader.h.
References NameTable.
readContextFromTable()
ErrorOr< SampleContextFrames > SampleProfileReaderBinary::readContextFromTable (size_t * RetIdx = nullptr) protected
Read a context indirectly via the CSNameTable.
Optionally return the index.
Definition at line 532 of file SampleProfReader.cpp.
References CSNameTable, readNumber(), and llvm::truncated_name_table.
Referenced by readSampleContextFromTable().
readFuncProfile()
std::error_code SampleProfileReaderBinary::readFuncProfile (const uint8_t * Start) protected
Read the next function profile instance.
Definition at line 656 of file SampleProfReader.cpp.
References llvm::sampleprof::FunctionSamples::addHeadSamples(), llvm::sampleprof::SampleProfileReader::CSProfileCount, Data, llvm::sampleprof::SampleProfileReader::Profiles, readNumber(), readProfile(), readSampleContextFromTable(), llvm::sampleprof::FunctionSamples::setContext(), llvm::success, and llvm::sampleprof::HashKeyMap< MapT, KeyT, ValueT, MapTArgs >::try_emplace().
Referenced by llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncProfiles(), and readImpl().
readHeader()
std::error_code SampleProfileReaderBinary::readHeader () override virtual
Read and validate the file header.
Implements llvm::sampleprof::SampleProfileReader.
Reimplemented in llvm::sampleprof::SampleProfileReaderExtBinaryBase.
Definition at line 1432 of file SampleProfReader.cpp.
References llvm::sampleprof::SampleProfileReader::Buffer, Data, End, readMagicIdent(), readNameTable(), readSummary(), and llvm::success.
readImpl()
std::error_code SampleProfileReaderBinary::readImpl () override virtual
Read sample profiles from the associated file.
Implements llvm::sampleprof::SampleProfileReader.
Reimplemented in llvm::sampleprof::SampleProfileReaderExtBinaryBase.
Definition at line 681 of file SampleProfReader.cpp.
References Data, End, llvm::sampleprof::FunctionSamples::ProfileIsFS, llvm::sampleprof::SampleProfileReader::ProfileIsFS, ProfileIsFSDisciminator, readFuncProfile(), and llvm::success.
readMagicIdent()
std::error_code SampleProfileReaderBinary::readMagicIdent () protected
Read the contents of Magic number and Version number.
Definition at line 1414 of file SampleProfReader.cpp.
References readNumber(), llvm::sampleprof::SPVersion(), llvm::success, and llvm::unsupported_version.
Referenced by readHeader(), and llvm::sampleprof::SampleProfileReaderExtBinaryBase::readHeader().
readNameTable()
std::error_code SampleProfileReaderBinary::readNameTable () protected
Read the whole name table.
Definition at line 1048 of file SampleProfReader.cpp.
References llvm::sampleprof::FunctionId::getHashCode(), I, MD5SampleContextStart, MD5SampleContextTable, Name, NameTable, llvm::sampleprof::SampleProfileReader::ProfileIsCS, readNumber(), readString(), Size, llvm::success, and llvm::sampleprof::SampleProfileReader::useMD5().
Referenced by readHeader(), and llvm::sampleprof::SampleProfileReaderExtBinaryBase::readNameTableSec().
readNumber()
template<typename T > ErrorOr< T > SampleProfileReaderBinary::readNumber () protected
Read a numeric value of type T from the profile.
If an error occurs during decoding, a diagnostic message is emitted and EC is set.
Returns
the read value.
Definition at line 468 of file SampleProfReader.cpp.
References Data, llvm::decodeULEB128(), End, llvm::malformed, llvm::sampleprof::SampleProfileReader::reportError(), and llvm::truncated.
Referenced by readContextFromTable(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readCSNameTableSec(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncMetadata(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncOffsetTable(), readFuncProfile(), readMagicIdent(), readNameTable(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readNameTableSec(), readProfile(), readStringIndex(), and readSummary().
readProfile()
std::error_code SampleProfileReaderBinary::readProfile (FunctionSamples & FProfile) protected
Read the contents of the given profile instance.
Definition at line 573 of file SampleProfReader.cpp.
References llvm::sampleprof::FunctionSamples::addBodySamples(), llvm::sampleprof::FunctionSamples::addCalledTargetSamples(), llvm::sampleprof::FunctionSamples::addTotalSamples(), llvm::sampleprof::FunctionSamples::functionSamplesAt(), llvm::sampleprof::SampleProfileReader::getDiscriminatorMask(), I, isOffsetLegal(), readNumber(), readProfile(), readStringFromTable(), llvm::sampleprof::FunctionSamples::setFunction(), and llvm::success.
Referenced by readFuncProfile(), and readProfile().
readSampleContextFromTable()
ErrorOr< std::pair< SampleContext, uint64_t > > SampleProfileReaderBinary::readSampleContextFromTable () protected
Read a context indirectly via the CSNameTable if the profile has context, otherwise same as readStringFromTable, also return its hash value.
Definition at line 544 of file SampleProfReader.cpp.
References assert(), MD5SampleContextStart, MD5SampleContextTable, llvm::sampleprof::SampleProfileReader::ProfileIsCS, llvm::support::endian::read64le(), readContextFromTable(), readStringFromTable(), and llvm::support::endian::write64le().
Referenced by llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncMetadata(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncMetadata(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncOffsetTable(), and readFuncProfile().
readString()
ErrorOr< StringRef > SampleProfileReaderBinary::readString () protected
Read a string from the profile.
If an error occurs during decoding, a diagnostic message is emitted and EC is set.
Returns
the read value.
Definition at line 486 of file SampleProfReader.cpp.
References Data, End, llvm::sampleprof::SampleProfileReader::reportError(), and llvm::truncated.
Referenced by readNameTable().
readStringFromTable()
ErrorOr< FunctionId > SampleProfileReaderBinary::readStringFromTable (size_t * RetIdx = nullptr) protected
Read a string indirectly via the name table. Optionally return the index.
Definition at line 522 of file SampleProfReader.cpp.
References NameTable, and readStringIndex().
Referenced by llvm::sampleprof::SampleProfileReaderExtBinaryBase::readCSNameTableSec(), readProfile(), and readSampleContextFromTable().
readStringIndex()
template<typename T > ErrorOr< size_t > SampleProfileReaderBinary::readStringIndex (T & Table) inline protected
Read the string index and check whether it overflows the table.
Definition at line 512 of file SampleProfReader.cpp.
References readNumber(), and llvm::truncated_name_table.
Referenced by readStringFromTable().
readSummary()
std::error_code SampleProfileReaderBinary::readSummary () protected
Read profile summary.
Definition at line 1465 of file SampleProfReader.cpp.
References llvm::ProfileSummary::PSK_Sample, readNumber(), and llvm::success.
Referenced by readHeader(), and llvm::sampleprof::SampleProfileReaderExtBinaryBase::readOneSection().
readUnencodedNumber()
template<typename T > ErrorOr< T > SampleProfileReaderBinary::readUnencodedNumber () protected
Read a numeric value of type T from the profile.
The value is saved without encoded.
Definition at line 499 of file SampleProfReader.cpp.
References Data, End, llvm::support::endian::readNext(), llvm::sampleprof::SampleProfileReader::reportError(), and llvm::truncated.
Referenced by llvm::sampleprof::SampleProfileReaderExtBinaryBase::readSecHdrTable(), and llvm::sampleprof::SampleProfileReaderExtBinaryBase::readSecHdrTableEntry().
Member Data Documentation
CSNameTable
std::vector<SampleContextFrameVector> llvm::sampleprof::SampleProfileReaderBinary::CSNameTable protected
CSNameTable is used to save full context vectors.
It is the backing buffer for SampleContextFrames.
Definition at line 659 of file SampleProfReader.h.
Referenced by readContextFromTable(), and llvm::sampleprof::SampleProfileReaderExtBinaryBase::readCSNameTableSec().
Data
const uint8_t* llvm::sampleprof::SampleProfileReaderBinary::Data = nullptr protected
Points to the current location in the buffer.
Definition at line 649 of file SampleProfReader.h.
Referenced by llvm::sampleprof::SampleProfileReaderExtBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderRawBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncMetadata(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncMetadata(), readFuncProfile(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncProfiles(), readHeader(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readHeader(), readImpl(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readImpl(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readNameTableSec(), readNumber(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readOneSection(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readProfileSymbolList(), readString(), and readUnencodedNumber().
End
const uint8_t* llvm::sampleprof::SampleProfileReaderBinary::End = nullptr protected
Points to the end of the buffer.
Definition at line 652 of file SampleProfReader.h.
Referenced by llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncMetadata(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncMetadata(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncProfiles(), readHeader(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readHeader(), readImpl(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readImpl(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readNameTableSec(), readNumber(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readOneSection(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readProfileSymbolList(), readString(), and readUnencodedNumber().
MD5SampleContextStart
const uint64_t* llvm::sampleprof::SampleProfileReaderBinary::MD5SampleContextStart = nullptr protected
The starting address of the table of MD5 values of sample contexts.
For fixed length MD5 non-CS profile it is same as MD5NameMemStart because hashes of non-CS contexts are already in the profile. Otherwise it points to the start of MD5SampleContextTable.
Definition at line 670 of file SampleProfReader.h.
Referenced by llvm::sampleprof::SampleProfileReaderExtBinaryBase::readCSNameTableSec(), readNameTable(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readNameTableSec(), and readSampleContextFromTable().
MD5SampleContextTable
std::vector<uint64_t> llvm::sampleprof::SampleProfileReaderBinary::MD5SampleContextTable protected
Table to cache MD5 values of sample contexts corresponding to readSampleContextFromTable(), used to index into Profiles or FuncOffsetTable.
Definition at line 664 of file SampleProfReader.h.
Referenced by llvm::sampleprof::SampleProfileReaderExtBinaryBase::readCSNameTableSec(), readNameTable(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readNameTableSec(), and readSampleContextFromTable().
NameTable
std::vector<FunctionId> llvm::sampleprof::SampleProfileReaderBinary::NameTable protected
Function name table.
Definition at line 655 of file SampleProfReader.h.
Referenced by getNameTable(), readNameTable(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readNameTableSec(), and readStringFromTable().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/SampleProfReader.h
lib/ProfileData/SampleProfReader.cpp