LLVM: llvm::InstructionWorklist Class Reference
llvm::InstructionWorklist Class Reference
InstructionWorklist - This is the worklist management logic for InstCombine and other simplification passes.
#include "llvm/Transforms/Utils/InstructionWorklist.h"
Public Member Functions
InstructionWorklist ()=default
InstructionWorklist (InstructionWorklist &&)=default
InstructionWorklist & operator= (InstructionWorklist &&)=default
bool isEmpty () const
void add (Instruction *I)
Add instruction to the worklist.
void addValue (Value *V)
Add value to the worklist if it is an instruction.
void push (Instruction *I)
Push the instruction onto the worklist stack.
void pushValue (Value *V)
Instruction * popDeferred ()
void reserve (size_t Size)
void remove (Instruction *I)
Remove I from the worklist if it exists.
Instruction * removeOne ()
void pushUsersToWorkList (Instruction &I)
When an instruction is simplified, add all users of the instruction to the work lists because they might get more simplified now.
void handleUseCountDecrement (Value *V)
Should be called after decrementing the use-count on V.
void zap ()
Check that the worklist is empty and nuke the backing store for the map.
Detailed Description
InstructionWorklist - This is the worklist management logic for InstCombine and other simplification passes.
Definition at line 25 of file InstructionWorklist.h.
Constructor & Destructor Documentation
InstructionWorklist() [1/2]
llvm::InstructionWorklist::InstructionWorklist () default
InstructionWorklist() [2/2]
llvm::InstructionWorklist::InstructionWorklist (InstructionWorklist &&) default
Member Function Documentation
add()
void llvm::InstructionWorklist::add (Instruction * I) inline
Add instruction to the worklist.
Instructions will be visited in the order they are added. You likely want to use this method.
Definition at line 44 of file InstructionWorklist.h.
References llvm::dbgs(), I, llvm::SetVector< T, Vector, Set, N >::insert(), and LLVM_DEBUG.
Referenced by addValue(), combineInstructionsOverFunction(), handleUseCountDecrement(), llvm::InstCombiner::InsertNewInstBefore(), llvm::InstCombinerImpl::tryToSinkInstruction(), llvm::InstCombinerImpl::visitAllocSite(), and llvm::InstCombinerImpl::visitCallInst().
addValue()
void llvm::InstructionWorklist::addValue (Value * V) inline
Add value to the worklist if it is an instruction.
Instructions will be visited in the order they are added.
Definition at line 51 of file InstructionWorklist.h.
References add(), llvm::dyn_cast(), and I.
Referenced by llvm::InstCombinerImpl::visitExtractElementInst().
handleUseCountDecrement()
void llvm::InstructionWorklist::handleUseCountDecrement (Value * V) inline
Should be called after decrementing the use-count on V.
Definition at line 112 of file InstructionWorklist.h.
References add(), llvm::cast(), llvm::dyn_cast(), and I.
Referenced by llvm::InstCombiner::replaceOperand(), and llvm::InstCombiner::replaceUse().
isEmpty()
bool llvm::InstructionWorklist::isEmpty () const inline
Definition at line 39 of file InstructionWorklist.h.
References llvm::SetVector< T, Vector, Set, N >::empty(), and llvm::SmallVectorBase< Size_T >::empty().
Referenced by llvm::InstCombinerImpl::run().
operator=()
InstructionWorklist & llvm::InstructionWorklist::operator= (InstructionWorklist &&) default
popDeferred()
Instruction * llvm::InstructionWorklist::popDeferred () inline
Definition at line 73 of file InstructionWorklist.h.
References llvm::SetVector< T, Vector, Set, N >::empty(), and llvm::SetVector< T, Vector, Set, N >::pop_back_val().
Referenced by llvm::InstCombinerImpl::run().
push()
void llvm::InstructionWorklist::push (Instruction * I) inline
Push the instruction onto the worklist stack.
Instructions that have been added first will be visited last.
Definition at line 58 of file InstructionWorklist.h.
References assert(), llvm::dbgs(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), LLVM_DEBUG, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::InstCombiner::addToWorklist(), llvm::InstCombinerImpl::matchBSwapOrBitReverse(), llvm::InstCombinerImpl::prepareWorklist(), pushUsersToWorkList(), pushValue(), llvm::InstCombinerImpl::run(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), llvm::InstCombinerImpl::simplifyDivRemOfSelectWithZeroOp(), and llvm::InstCombinerImpl::visitBranchInst().
pushUsersToWorkList()
void llvm::InstructionWorklist::pushUsersToWorkList (Instruction & I) inline
When an instruction is simplified, add all users of the instruction to the work lists because they might get more simplified now.
Definition at line 106 of file InstructionWorklist.h.
References llvm::cast(), I, push(), and llvm::Value::users().
Referenced by llvm::InstCombiner::replaceInstUsesWith(), and llvm::InstCombinerImpl::run().
pushValue()
void llvm::InstructionWorklist::pushValue (Value * V) inline
Definition at line 68 of file InstructionWorklist.h.
References llvm::dyn_cast(), I, and push().
Referenced by llvm::InstCombinerImpl::visitCallInst().
remove()
void llvm::InstructionWorklist::remove (Instruction * I) inline
Remove I from the worklist if it exists.
Definition at line 85 of file InstructionWorklist.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), I, and llvm::SetVector< T, Vector, Set, N >::remove().
removeOne()
Instruction * llvm::InstructionWorklist::removeOne () inline
Definition at line 96 of file InstructionWorklist.h.
References llvm::SmallVectorBase< Size_T >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), I, and llvm::SmallVectorImpl< T >::pop_back_val().
Referenced by llvm::InstCombinerImpl::run().
reserve()
void llvm::InstructionWorklist::reserve (size_t Size) inline
Definition at line 79 of file InstructionWorklist.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::reserve(), llvm::SmallVectorImpl< T >::reserve(), and Size.
Referenced by llvm::InstCombinerImpl::prepareWorklist().
zap()
void llvm::InstructionWorklist::zap () inline
Check that the worklist is empty and nuke the backing store for the map.
Definition at line 123 of file InstructionWorklist.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), and llvm::SetVector< T, Vector, Set, N >::empty().
Referenced by llvm::InstCombinerImpl::run().
The documentation for this class was generated from the following file:
include/llvm/Transforms/Utils/InstructionWorklist.h