LLVM: llvm::RegAllocBase Class Reference
llvm::RegAllocBase Class Reference abstract
RegAllocBase provides the register allocation driver and interface that can be extended to add interesting heuristics.
#include "CodeGen/RegAllocBase.h"
Static Public Attributes
static bool VerifyEnabled = false
VerifyEnabled - True when -verify-regalloc is given.
Protected Member Functions
RegAllocBase (const RegAllocFilterFunc F=nullptr)
virtual ~RegAllocBase ()=default
void init (VirtRegMap &vrm, LiveIntervals &lis, LiveRegMatrix &mat)
bool shouldAllocateRegister (Register Reg)
Get whether a given register should be allocated.
void allocatePhysRegs ()
virtual void postOptimization ()
virtual Spiller & spiller ()=0
virtual void enqueueImpl (const LiveInterval *LI)=0
enqueue - Add VirtReg to the priority queue of unassigned registers.
void enqueue (const LiveInterval *LI)
enqueue - Add VirtReg to the priority queue of unassigned registers.
virtual const LiveInterval * dequeue ()=0
dequeue - Return the next unassigned register, or NULL.
virtual MCRegister selectOrSplit (const LiveInterval &VirtReg, SmallVectorImpl< Register > &splitLVRs)=0
virtual void aboutToRemoveInterval (const LiveInterval &LI)
Method called when the allocator is about to remove a LiveInterval.
Protected Attributes
const TargetRegisterInfo * TRI = nullptr
MachineRegisterInfo * MRI = nullptr
VirtRegMap * VRM = nullptr
LiveIntervals * LIS = nullptr
LiveRegMatrix * Matrix = nullptr
RegisterClassInfo RegClassInfo
SmallPtrSet< MachineInstr *, 32 > DeadRemats
Inst which is a def of an original reg and whose defs are already all dead after remat is saved in DeadRemats.
Static Protected Attributes
static const char TimerGroupName [] = "regalloc"
static const char TimerGroupDescription [] = "Register Allocation"
Detailed Description
RegAllocBase provides the register allocation driver and interface that can be extended to add interesting heuristics.
Register allocators must override the selectOrSplit() method to implement live range splitting. They must also override enqueue/dequeue to provide an assignment order.
Definition at line 62 of file RegAllocBase.h.
Constructor & Destructor Documentation
RegAllocBase()
llvm::RegAllocBase::RegAllocBase (const RegAllocFilterFunc F = nullptr) inline protected
Definition at line 84 of file RegAllocBase.h.
~RegAllocBase()
virtual llvm::RegAllocBase::~RegAllocBase () protected virtual default
Member Function Documentation
aboutToRemoveInterval()
virtual void llvm::RegAllocBase::aboutToRemoveInterval (const LiveInterval & LI) inline protected virtual
Method called when the allocator is about to remove a LiveInterval.
Reimplemented in llvm::RAGreedy.
Definition at line 131 of file RegAllocBase.h.
Referenced by allocatePhysRegs().
allocatePhysRegs()
void RegAllocBase::allocatePhysRegs () protected
Definition at line 85 of file RegAllocBase.cpp.
References aboutToRemoveInterval(), assert(), llvm::LiveRegMatrix::assign(), llvm::VirtRegMap::assignVirt2Phys(), llvm::dbgs(), dequeue(), llvm::ArrayRef< T >::empty(), llvm::LiveRange::empty(), enqueue(), llvm::ArrayRef< T >::front(), llvm::LiveIntervals::getInterval(), llvm::RegisterClassInfo::getOrder(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClassName(), llvm::LiveIntervals::hasInterval(), llvm::VirtRegMap::hasPhys(), llvm::LiveRegMatrix::invalidateVirtRegs(), llvm::Register::isVirtual(), LIS, LLVM_DEBUG, Matrix, MI, MRI, llvm::LiveInterval::reg(), llvm::MachineRegisterInfo::reg_instructions(), llvm::MachineRegisterInfo::reg_nodbg_empty(), RegClassInfo, llvm::LiveIntervals::removeInterval(), llvm::report_fatal_error(), selectOrSplit(), TRI, and VRM.
Referenced by llvm::RAGreedy::runOnMachineFunction().
dequeue()
virtual const LiveInterval * llvm::RegAllocBase::dequeue () protected pure virtual
dequeue - Return the next unassigned register, or NULL.
Implemented in llvm::RAGreedy.
Referenced by allocatePhysRegs().
enqueue()
void RegAllocBase::enqueue (const LiveInterval * LI) protected
enqueue - Add VirtReg to the priority queue of unassigned registers.
Definition at line 174 of file RegAllocBase.cpp.
References assert(), llvm::dbgs(), enqueueImpl(), llvm::VirtRegMap::hasPhys(), LLVM_DEBUG, llvm::printReg(), llvm::LiveInterval::reg(), shouldAllocateRegister(), TRI, and VRM.
Referenced by allocatePhysRegs().
enqueueImpl()
virtual void llvm::RegAllocBase::enqueueImpl (const LiveInterval * LI) protected pure virtual
enqueue - Add VirtReg to the priority queue of unassigned registers.
Implemented in llvm::RAGreedy.
Referenced by enqueue().
init()
void RegAllocBase::init (VirtRegMap & vrm, LiveIntervals & lis, LiveRegMatrix & mat) protected
Definition at line 58 of file RegAllocBase.cpp.
References llvm::MachineRegisterInfo::freezeReservedRegs(), llvm::VirtRegMap::getMachineFunction(), llvm::VirtRegMap::getRegInfo(), llvm::VirtRegMap::getTargetRegInfo(), LIS, Matrix, MRI, RegClassInfo, llvm::RegisterClassInfo::runOnMachineFunction(), TRI, and VRM.
Referenced by llvm::RAGreedy::runOnMachineFunction().
postOptimization()
void RegAllocBase::postOptimization () protected virtual
Definition at line 165 of file RegAllocBase.cpp.
References DeadRemats, LIS, llvm::Spiller::postOptimization(), llvm::LiveIntervals::RemoveMachineInstrFromMaps(), and spiller().
Referenced by llvm::RAGreedy::runOnMachineFunction().
selectOrSplit()
virtual MCRegister llvm::RegAllocBase::selectOrSplit (const LiveInterval & VirtReg, SmallVectorImpl< Register > & splitLVRs) protected pure virtual
Implemented in llvm::RAGreedy.
Referenced by allocatePhysRegs().
shouldAllocateRegister()
bool llvm::RegAllocBase::shouldAllocateRegister (Register Reg) inline protected
Get whether a given register should be allocated.
Definition at line 93 of file RegAllocBase.h.
References MRI, and TRI.
Referenced by enqueue().
spiller()
virtual Spiller & llvm::RegAllocBase::spiller () protected pure virtual
Implemented in llvm::RAGreedy.
Referenced by postOptimization().
Member Data Documentation
DeadRemats
SmallPtrSet<MachineInstr *, 32> llvm::RegAllocBase::DeadRemats protected
Inst which is a def of an original reg and whose defs are already all dead after remat is saved in DeadRemats.
The deletion of such inst is postponed till all the allocations are done, so its remat expr is always available for the remat of all the siblings of the original reg.
Definition at line 82 of file RegAllocBase.h.
Referenced by postOptimization().
LIS
LiveIntervals* llvm::RegAllocBase::LIS = nullptr protected
Definition at line 69 of file RegAllocBase.h.
Referenced by allocatePhysRegs(), init(), postOptimization(), and llvm::RAGreedy::runOnMachineFunction().
Matrix
LiveRegMatrix* llvm::RegAllocBase::Matrix = nullptr protected
Definition at line 70 of file RegAllocBase.h.
Referenced by allocatePhysRegs(), llvm::RegAllocEvictionAdvisor::canReassign(), init(), llvm::RegAllocEvictionAdvisor::isUnusedCalleeSavedReg(), and llvm::RAGreedy::runOnMachineFunction().
MRI
MachineRegisterInfo* llvm::RegAllocBase::MRI = nullptr protected
Definition at line 67 of file RegAllocBase.h.
Referenced by allocatePhysRegs(), getInstReadLaneMask(), llvm::RegAllocEvictionAdvisor::getOrderLimit(), hasTiedDef(), init(), readsLaneSubset(), and shouldAllocateRegister().
RegClassInfo
RegisterClassInfo llvm::RegAllocBase::RegClassInfo protected
Definition at line 71 of file RegAllocBase.h.
Referenced by allocatePhysRegs(), llvm::RegAllocEvictionAdvisor::canAllocatePhysReg(), llvm::RegAllocEvictionAdvisor::canReassign(), llvm::RegAllocEvictionAdvisor::getOrderLimit(), init(), and llvm::RegAllocEvictionAdvisor::isUnusedCalleeSavedReg().
TimerGroupDescription
const char RegAllocBase::TimerGroupDescription = "Register Allocation" static protected
Definition at line 128 of file RegAllocBase.h.
TimerGroupName
const char RegAllocBase::TimerGroupName = "regalloc" static protected
Definition at line 127 of file RegAllocBase.h.
TRI
const TargetRegisterInfo* llvm::RegAllocBase::TRI = nullptr protected
Definition at line 66 of file RegAllocBase.h.
Referenced by allocatePhysRegs(), assignedRegPartiallyOverlaps(), llvm::RegAllocEvictionAdvisor::canAllocatePhysReg(), llvm::RegAllocEvictionAdvisor::canReassign(), enqueue(), getInstReadLaneMask(), getNumAllocatableRegsForConstraints(), llvm::RegAllocEvictionAdvisor::getOrderLimit(), init(), readsLaneSubset(), llvm::RAGreedy::runOnMachineFunction(), and shouldAllocateRegister().
VerifyEnabled
bool RegAllocBase::VerifyEnabled = false static
VerifyEnabled - True when -verify-regalloc is given.
Definition at line 135 of file RegAllocBase.h.
Referenced by llvm::RAGreedy::runOnMachineFunction().
VRM
VirtRegMap* llvm::RegAllocBase::VRM = nullptr protected
Definition at line 68 of file RegAllocBase.h.
Referenced by allocatePhysRegs(), assignedRegPartiallyOverlaps(), llvm::RegAllocEvictionAdvisor::canReassign(), enqueue(), init(), and llvm::RAGreedy::runOnMachineFunction().
The documentation for this class was generated from the following files:
lib/CodeGen/RegAllocBase.h
lib/CodeGen/RegAllocBase.cpp