LLVM: llvm::SPIRVGeneralDuplicatesTracker Class Reference
llvm::SPIRVGeneralDuplicatesTracker Class Reference
#include "Target/SPIRV/SPIRVDuplicatesTracker.h"
Public Member Functions
void buildDepsGraph (std::vector< SPIRV::DTSortableEntry * > &Graph, MachineModuleInfo *MMI)
void add (const Type *Ty, const MachineFunction *MF, Register R)
void add (const Type *PointeeTy, unsigned AddressSpace, const MachineFunction *MF, Register R)
void add (const Constant *C, const MachineFunction *MF, Register R)
void add (const GlobalVariable *GV, const MachineFunction *MF, Register R)
void add (const Function *F, const MachineFunction *MF, Register R)
void add (const Argument *Arg, const MachineFunction *MF, Register R)
void add (const MachineInstr *MI, const MachineFunction *MF, Register R)
void add (const SPIRV::SpecialTypeDescriptor &TD, const MachineFunction *MF, Register R)
Register find (const Type *Ty, const MachineFunction *MF)
Register find (const Type *PointeeTy, unsigned AddressSpace, const MachineFunction *MF)
Register find (const Constant *C, const MachineFunction *MF)
Register find (const GlobalVariable *GV, const MachineFunction *MF)
Register find (const Function *F, const MachineFunction *MF)
Register find (const Argument *Arg, const MachineFunction *MF)
Register find (const MachineInstr *MI, const MachineFunction *MF)
Register find (const SPIRV::SpecialTypeDescriptor &TD, const MachineFunction *MF)
const SPIRVDuplicatesTracker< Type > * getTypes ()
Detailed Description
Definition at line 195 of file SPIRVDuplicatesTracker.h.
Member Function Documentation
add() [1/8]
void llvm::SPIRVGeneralDuplicatesTracker::add (const Argument * Arg, const MachineFunction * MF, Register R) inline
Definition at line 242 of file SPIRVDuplicatesTracker.h.
References llvm::SPIRVDuplicatesTrackerBase< KeyTy >::add().
add() [2/8]
void llvm::SPIRVGeneralDuplicatesTracker::add (const Constant * C, const MachineFunction * MF, Register R) inline
Definition at line 230 of file SPIRVDuplicatesTracker.h.
References llvm::SPIRVDuplicatesTrackerBase< KeyTy >::add(), and llvm::CallingConv::C.
add() [3/8]
void llvm::SPIRVGeneralDuplicatesTracker::add (const Function * F, const MachineFunction * MF, Register R) inline
Definition at line 238 of file SPIRVDuplicatesTracker.h.
References llvm::SPIRVDuplicatesTrackerBase< KeyTy >::add(), and F.
add() [4/8]
void llvm::SPIRVGeneralDuplicatesTracker::add (const GlobalVariable * GV, const MachineFunction * MF, Register R) inline
Definition at line 234 of file SPIRVDuplicatesTracker.h.
add() [5/8]
void llvm::SPIRVGeneralDuplicatesTracker::add (const MachineInstr * MI, const MachineFunction * MF, Register R) inline
Definition at line 246 of file SPIRVDuplicatesTracker.h.
References llvm::SPIRVDuplicatesTrackerBase< KeyTy >::add(), and MI.
add() [6/8]
void llvm::SPIRVGeneralDuplicatesTracker::add (const SPIRV::SpecialTypeDescriptor & TD, const MachineFunction * MF, Register R) inline
Definition at line 250 of file SPIRVDuplicatesTracker.h.
add() [7/8]
void llvm::SPIRVGeneralDuplicatesTracker::add (const Type * PointeeTy, unsigned AddressSpace, const MachineFunction * MF, Register R) inline
Definition at line 224 of file SPIRVDuplicatesTracker.h.
References llvm::SPIRV::make_descr_pointee(), and llvm::unifyPtrType().
add() [8/8]
void llvm::SPIRVGeneralDuplicatesTracker::add (const Type * Ty, const MachineFunction * MF, Register R) inline
Definition at line 220 of file SPIRVDuplicatesTracker.h.
References llvm::unifyPtrType().
Referenced by llvm::SPIRVGlobalRegistry::add(), llvm::SPIRVGlobalRegistry::add(), llvm::SPIRVGlobalRegistry::add(), llvm::SPIRVGlobalRegistry::add(), llvm::SPIRVGlobalRegistry::add(), llvm::SPIRVGlobalRegistry::buildConstantFP(), llvm::SPIRVGlobalRegistry::buildConstantInt(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), llvm::SPIRVGlobalRegistry::getOrCreateConstNullPtr(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeByOpcode(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeCoopMatr(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeDeviceEvent(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeFunctionWithArgs(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeImage(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypePipe(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampledImage(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeSampler(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVArrayType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVBoolType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), and llvm::SPIRVGlobalRegistry::getOrCreateUndef().
buildDepsGraph()
void SPIRVGeneralDuplicatesTracker::buildDepsGraph (std::vector< SPIRV::DTSortableEntry * > & Graph, MachineModuleInfo * MMI = nullptr)
Definition at line 33 of file SPIRVDuplicatesTracker.cpp.
References assert(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::count(), D, llvm::dbgs(), llvm::Pass::dump(), F, llvm::MachineInstr::getOperand(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::lookup(), MBB, MI, MRI, llvm::Next, and llvm::Register::virtReg2Index().
Referenced by llvm::SPIRVGlobalRegistry::buildDepsGraph().
find() [1/8]
Register llvm::SPIRVGeneralDuplicatesTracker::find (const Argument * Arg, const MachineFunction * MF) inline
Definition at line 277 of file SPIRVDuplicatesTracker.h.
References llvm::SPIRVDuplicatesTrackerBase< KeyTy >::find().
find() [2/8]
Register llvm::SPIRVGeneralDuplicatesTracker::find (const Constant * C, const MachineFunction * MF) inline
Definition at line 265 of file SPIRVDuplicatesTracker.h.
References llvm::CallingConv::C, and llvm::SPIRVDuplicatesTrackerBase< KeyTy >::find().
find() [3/8]
Register llvm::SPIRVGeneralDuplicatesTracker::find (const Function * F, const MachineFunction * MF) inline
Definition at line 273 of file SPIRVDuplicatesTracker.h.
References F, and llvm::SPIRVDuplicatesTrackerBase< KeyTy >::find().
find() [4/8]
Register llvm::SPIRVGeneralDuplicatesTracker::find (const GlobalVariable * GV, const MachineFunction * MF) inline
Definition at line 269 of file SPIRVDuplicatesTracker.h.
find() [5/8]
Register llvm::SPIRVGeneralDuplicatesTracker::find (const MachineInstr * MI, const MachineFunction * MF) inline
Definition at line 281 of file SPIRVDuplicatesTracker.h.
References llvm::SPIRVDuplicatesTrackerBase< KeyTy >::find(), and MI.
find() [6/8]
Register llvm::SPIRVGeneralDuplicatesTracker::find (const SPIRV::SpecialTypeDescriptor & TD, const MachineFunction * MF) inline
Definition at line 285 of file SPIRVDuplicatesTracker.h.
find() [7/8]
Register llvm::SPIRVGeneralDuplicatesTracker::find (const Type * PointeeTy, unsigned AddressSpace, const MachineFunction * MF) inline
Definition at line 259 of file SPIRVDuplicatesTracker.h.
References llvm::SPIRV::make_descr_pointee(), and llvm::unifyPtrType().
find() [8/8]
Register llvm::SPIRVGeneralDuplicatesTracker::find (const Type * Ty, const MachineFunction * MF) inline
Definition at line 255 of file SPIRVDuplicatesTracker.h.
References llvm::unifyPtrType().
Referenced by llvm::SPIRVGlobalRegistry::buildConstantFP(), llvm::SPIRVGlobalRegistry::buildConstantInt(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), llvm::SPIRVGlobalRegistry::find(), llvm::SPIRVGlobalRegistry::find(), llvm::SPIRVGlobalRegistry::find(), llvm::SPIRVGlobalRegistry::find(), llvm::SPIRVGlobalRegistry::getOrCreateConstNullPtr(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeByOpcode(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeCoopMatr(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeFunctionWithArgs(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVArrayType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVBoolType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), and llvm::SPIRVGlobalRegistry::getOrCreateUndef().
getTypes()
const SPIRVDuplicatesTracker< Type > * llvm::SPIRVGeneralDuplicatesTracker::getTypes () inline
Definition at line 290 of file SPIRVDuplicatesTracker.h.
The documentation for this class was generated from the following files:
lib/Target/SPIRV/SPIRVDuplicatesTracker.h
lib/Target/SPIRV/SPIRVDuplicatesTracker.cpp