LLVM: llvm::orc::CAPIDefinitionGenerator Class Reference
llvm::orc::CAPIDefinitionGenerator Class Reference final
Public Member Functions
CAPIDefinitionGenerator (LLVMOrcDisposeCAPIDefinitionGeneratorFunction Dispose, void *Ctx, LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction TryToGenerate)
~CAPIDefinitionGenerator ()
Error tryToGenerate (LookupState &LS, LookupKind K, JITDylib &JD, JITDylibLookupFlags JDLookupFlags, const SymbolLookupSet &LookupSet) override
Detailed Description
Definition at line 259 of file OrcV2CBindings.cpp.
Constructor & Destructor Documentation
CAPIDefinitionGenerator()
llvm::orc::CAPIDefinitionGenerator::CAPIDefinitionGenerator (LLVMOrcDisposeCAPIDefinitionGeneratorFunction Dispose, void * Ctx, LLVMOrcCAPIDefinitionGeneratorTryToGenerateFunction TryToGenerate) inline
Definition at line 261 of file OrcV2CBindings.cpp.
~CAPIDefinitionGenerator()
llvm::orc::CAPIDefinitionGenerator::~CAPIDefinitionGenerator () inline
Definition at line 266 of file OrcV2CBindings.cpp.
Member Function Documentation
tryToGenerate()
Error llvm::orc::CAPIDefinitionGenerator::tryToGenerate (LookupState & LS, LookupKind K, JITDylib & JD, JITDylibLookupFlags JDLookupFlags, const SymbolLookupSet & LookupSet) inline override
Definition at line 271 of file OrcV2CBindings.cpp.
References llvm::orc::OrcV2CAPIHelper::extractLookupState(), llvm::orc::SymbolStringPoolEntryUnsafe::from(), Name, llvm::orc::OrcV2CAPIHelper::resetLookupState(), llvm::unwrap(), and llvm::wrap().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/OrcV2CBindings.cpp