LLVM: llvm::XtensaTargetAsmStreamer Class Reference
llvm::XtensaTargetAsmStreamer Class Reference
#include "Target/Xtensa/MCTargetDesc/XtensaTargetStreamer.h"
Public Member Functions
XtensaTargetAsmStreamer (MCStreamer &S, formatted_raw_ostream &OS)
void emitLiteral (MCSymbol *LblSym, const MCExpr *Value, bool SwitchLiteralSection, SMLoc L) override
void emitLiteralPosition () override
void startLiteralSection (MCSection *Section) override
Public Member Functions inherited from llvm::XtensaTargetStreamer
XtensaTargetStreamer (MCStreamer &S)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 36 of file XtensaTargetStreamer.h.
Constructor & Destructor Documentation
XtensaTargetAsmStreamer()
XtensaTargetAsmStreamer::XtensaTargetAsmStreamer (MCStreamer & S, formatted_raw_ostream & OS)
Definition at line 49 of file XtensaTargetStreamer.cpp.
Member Function Documentation
emitLiteral()
void XtensaTargetAsmStreamer::emitLiteral (MCSymbol * LblSym, const MCExpr * Value, bool SwitchLiteralSection, SMLoc L) override virtual
Implements llvm::XtensaTargetStreamer.
Definition at line 53 of file XtensaTargetStreamer.cpp.
References llvm::dyn_cast(), llvm::MCSymbol::getName(), llvm_unreachable, llvm::raw_svector_ostream::str(), and Sym.
emitLiteralPosition()
void XtensaTargetAsmStreamer::emitLiteralPosition () override virtual
Implements llvm::XtensaTargetStreamer.
Definition at line 72 of file XtensaTargetStreamer.cpp.
Referenced by startLiteralSection().
startLiteralSection()
void XtensaTargetAsmStreamer::startLiteralSection (MCSection * Section) override virtual
Implements llvm::XtensaTargetStreamer.
Definition at line 76 of file XtensaTargetStreamer.cpp.
References emitLiteralPosition().
The documentation for this class was generated from the following files:
lib/Target/Xtensa/MCTargetDesc/XtensaTargetStreamer.h
lib/Target/Xtensa/MCTargetDesc/XtensaTargetStreamer.cpp