LLVM: llvm::PPCMCCodeEmitter Class Reference
llvm::PPCMCCodeEmitter Class Reference
#include "Target/PowerPC/MCTargetDesc/PPCMCCodeEmitter.h"
Public Member Functions
PPCMCCodeEmitter (const MCInstrInfo &mcii, MCContext &ctx)
PPCMCCodeEmitter (const PPCMCCodeEmitter &)=delete
void operator= (const PPCMCCodeEmitter &)=delete
~PPCMCCodeEmitter () override=default
unsigned getDirectBrEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getCondBrEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getAbsDirectBrEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getAbsCondBrEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getImm16Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
uint64_t getImm34Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI, MCFixupKind Fixup) const
uint64_t getImm34EncodingNoPCRel (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
uint64_t getImm34EncodingPCRel (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getDispRIEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getDispRIXEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getDispRIX16Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getDispRIHashEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
uint64_t getDispRI34PCRelEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
uint64_t getDispRI34Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getDispSPE8Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getDispSPE4Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getDispSPE2Encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getTLSRegEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getTLSCallEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned get_crbitm_encoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getVSRpEvenEncoding (const MCInst &MI, unsigned OpNo, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
uint64_t getMachineOpValue (const MCInst &MI, const MCOperand &MO, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
getMachineOpValue - Return binary encoding of operand.
uint64_t getBinaryCodeForInstr (const MCInst &MI, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
void encodeInstruction (const MCInst &MI, SmallVectorImpl< char > &CB, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const override
Encode the given Inst to bytes and append to CB.
unsigned getInstSizeInBytes (const MCInst &MI) const
bool isPrefixedInstruction (const MCInst &MI) const
bool isNoTOCCallInstr (const MCInst &MI) const
Check if Opcode corresponds to a call instruction that should be marked with the NOTOC relocation.
Public Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter (const MCCodeEmitter &)=delete
MCCodeEmitter & operator= (const MCCodeEmitter &)=delete
virtual ~MCCodeEmitter ()
virtual void reset ()
Lifetime management.
Additional Inherited Members
Protected Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter ()
Detailed Description
Definition at line 25 of file PPCMCCodeEmitter.h.
Constructor & Destructor Documentation
PPCMCCodeEmitter() [1/2]
llvm::PPCMCCodeEmitter::PPCMCCodeEmitter (const MCInstrInfo & mcii, MCContext & ctx) inline
Definition at line 31 of file PPCMCCodeEmitter.h.
PPCMCCodeEmitter() [2/2]
llvm::PPCMCCodeEmitter::PPCMCCodeEmitter (const PPCMCCodeEmitter &) delete
~PPCMCCodeEmitter()
llvm::PPCMCCodeEmitter::~PPCMCCodeEmitter () override default
Member Function Documentation
encodeInstruction()
void PPCMCCodeEmitter::encodeInstruction (const MCInst & Inst, SmallVectorImpl< char > & CB, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const override virtual
Encode the given Inst to bytes and append to CB.
Implements llvm::MCCodeEmitter.
Definition at line 503 of file PPCMCCodeEmitter.cpp.
References llvm::big, getBinaryCodeForInstr(), getInstSizeInBytes(), llvm::little, llvm_unreachable, MI, Size, and llvm::support::endian::write().
get_crbitm_encoding()
unsigned PPCMCCodeEmitter::get_crbitm_encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 457 of file PPCMCCodeEmitter.cpp.
References assert(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCOperand::getReg(), llvm::MCContext::getRegisterInfo(), and MI.
getAbsCondBrEncoding()
unsigned PPCMCCodeEmitter::getAbsCondBrEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 179 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_brcond14abs, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and MI.
getAbsDirectBrEncoding()
unsigned PPCMCCodeEmitter::getAbsDirectBrEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 166 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_br24abs, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and MI.
getBinaryCodeForInstr()
uint64_t llvm::PPCMCCodeEmitter::getBinaryCodeForInstr (const MCInst & MI, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Referenced by encodeInstruction().
getCondBrEncoding()
unsigned PPCMCCodeEmitter::getCondBrEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 154 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_brcond14, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and MI.
getDirectBrEncoding()
unsigned PPCMCCodeEmitter::getDirectBrEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 43 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_br24, llvm::PPC::fixup_ppc_br24_notoc, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), isNoTOCCallInstr(), llvm::MCOperand::isReg(), and MI.
Referenced by getTLSCallEncoding().
getDispRI34Encoding()
uint64_t PPCMCCodeEmitter::getDispRI34Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 387 of file PPCMCCodeEmitter.cpp.
References getMachineOpValue(), and MI.
getDispRI34PCRelEncoding()
uint64_t PPCMCCodeEmitter::getDispRI34PCRelEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 304 of file PPCMCCodeEmitter.cpp.
References llvm::MCBinaryExpr::Add, assert(), llvm::MCExpr::Binary, llvm::cast(), llvm::MCExpr::Constant, llvm::MCFixup::create(), llvm::PPC::fixup_ppc_pcrel34, llvm::MCOperand::getExpr(), llvm::MCExpr::getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCBinaryExpr::getLHS(), getMachineOpValue(), llvm::MCBinaryExpr::getOpcode(), llvm::MCBinaryExpr::getRHS(), llvm::MCOperand::isExpr(), llvm::isInt(), llvm_unreachable, MI, std::swap(), llvm::MCExpr::SymbolRef, llvm::MCSymbolRefExpr::VK_PCREL, llvm::MCSymbolRefExpr::VK_PPC_GOT_PCREL, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSGD_PCREL, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSLD_PCREL, and llvm::MCSymbolRefExpr::VK_PPC_GOT_TPREL_PCREL.
getDispRIEncoding()
unsigned PPCMCCodeEmitter::getDispRIEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 244 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_half16, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), and MI.
getDispRIHashEncoding()
unsigned PPCMCCodeEmitter::getDispRIHashEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 289 of file PPCMCCodeEmitter.cpp.
References assert(), llvm::MCOperand::getImm(), llvm::MCOperand::isImm(), and MI.
getDispRIX16Encoding()
unsigned PPCMCCodeEmitter::getDispRIX16Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 272 of file PPCMCCodeEmitter.cpp.
References assert(), llvm::MCFixup::create(), llvm::PPC::fixup_ppc_half16dq, llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), getMachineOpValue(), llvm::MCOperand::isImm(), and MI.
getDispRIXEncoding()
unsigned PPCMCCodeEmitter::getDispRIXEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 258 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_half16ds, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), and MI.
getDispSPE2Encoding()
unsigned PPCMCCodeEmitter::getDispSPE2Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 416 of file PPCMCCodeEmitter.cpp.
References assert(), getMachineOpValue(), llvm::MCOperand::isImm(), and MI.
getDispSPE4Encoding()
unsigned PPCMCCodeEmitter::getDispSPE4Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 406 of file PPCMCCodeEmitter.cpp.
References assert(), getMachineOpValue(), llvm::MCOperand::isImm(), and MI.
getDispSPE8Encoding()
unsigned PPCMCCodeEmitter::getDispSPE8Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 396 of file PPCMCCodeEmitter.cpp.
References assert(), getMachineOpValue(), llvm::MCOperand::isImm(), and MI.
getImm16Encoding()
unsigned PPCMCCodeEmitter::getImm16Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 202 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_half16, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and MI.
getImm34Encoding()
uint64_t PPCMCCodeEmitter::getImm34Encoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI, MCFixupKind Fixup) const
Definition at line 214 of file PPCMCCodeEmitter.cpp.
References assert(), llvm::MCFixup::create(), Fixup, llvm::MCOperand::getExpr(), getMachineOpValue(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and MI.
Referenced by getImm34EncodingNoPCRel(), and getImm34EncodingPCRel().
getImm34EncodingNoPCRel()
uint64_t PPCMCCodeEmitter::getImm34EncodingNoPCRel (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 229 of file PPCMCCodeEmitter.cpp.
References llvm::PPC::fixup_ppc_imm34, getImm34Encoding(), and MI.
getImm34EncodingPCRel()
uint64_t PPCMCCodeEmitter::getImm34EncodingPCRel (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 237 of file PPCMCCodeEmitter.cpp.
References llvm::PPC::fixup_ppc_pcrel34, getImm34Encoding(), and MI.
getInstSizeInBytes()
unsigned PPCMCCodeEmitter::getInstSizeInBytes (const MCInst & MI) const
Definition at line 533 of file PPCMCCodeEmitter.cpp.
References llvm::MCInstrInfo::get(), and MI.
Referenced by encodeInstruction().
getMachineOpValue()
uint64_t PPCMCCodeEmitter::getMachineOpValue (const MCInst & MI, const MCOperand & MO, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
getMachineOpValue - Return binary encoding of operand.
If the machine operand requires relocation, record the relocation and return zero.
Definition at line 482 of file PPCMCCodeEmitter.cpp.
References assert(), llvm::MCInstrInfo::get(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCOperand::getImm(), getOpIdxForMO(), llvm::MCOperand::getReg(), llvm::MCContext::getRegisterInfo(), llvm::PPC::getRegNumForOperand(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and MI.
Referenced by getAbsCondBrEncoding(), getAbsDirectBrEncoding(), getCondBrEncoding(), getDirectBrEncoding(), getDispRI34Encoding(), getDispRI34PCRelEncoding(), getDispRIEncoding(), getDispRIX16Encoding(), getDispRIXEncoding(), getDispSPE2Encoding(), getDispSPE4Encoding(), getDispSPE8Encoding(), getImm16Encoding(), getImm34Encoding(), getTLSRegEncoding(), and getVSRpEvenEncoding().
getTLSCallEncoding()
unsigned PPCMCCodeEmitter::getTLSCallEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 445 of file PPCMCCodeEmitter.cpp.
References llvm::MCFixup::create(), llvm::PPC::fixup_ppc_nofixup, getDirectBrEncoding(), llvm::MCOperand::getExpr(), and MI.
getTLSRegEncoding()
unsigned PPCMCCodeEmitter::getTLSRegEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 425 of file PPCMCCodeEmitter.cpp.
References llvm::cast(), llvm::MCFixup::create(), llvm::PPC::fixup_ppc_nofixup, llvm::MCRegisterInfo::getEncodingValue(), llvm::MCOperand::getExpr(), llvm::MCSymbolRefExpr::getKind(), getMachineOpValue(), llvm::MCContext::getRegisterInfo(), llvm::MCSubtargetInfo::getTargetTriple(), llvm::MCOperand::isReg(), MI, and llvm::MCSymbolRefExpr::VK_PPC_TLS_PCREL.
getVSRpEvenEncoding()
unsigned PPCMCCodeEmitter::getVSRpEvenEncoding (const MCInst & MI, unsigned OpNo, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 193 of file PPCMCCodeEmitter.cpp.
References assert(), getMachineOpValue(), and MI.
isNoTOCCallInstr()
bool PPCMCCodeEmitter::isNoTOCCallInstr (const MCInst & MI) const
Check if Opcode corresponds to a call instruction that should be marked with the NOTOC relocation.
Definition at line 62 of file PPCMCCodeEmitter.cpp.
References llvm::MCInstrInfo::get(), llvm::MCInstrDesc::isCall(), llvm_unreachable, and MI.
Referenced by getDirectBrEncoding().
isPrefixedInstruction()
bool PPCMCCodeEmitter::isPrefixedInstruction (const MCInst & MI) const
Definition at line 539 of file PPCMCCodeEmitter.cpp.
References llvm::MCInstrInfo::get(), MI, llvm::PPCII::Prefixed, and llvm::MCInstrDesc::TSFlags.
operator=()
void llvm::PPCMCCodeEmitter::operator= (const PPCMCCodeEmitter &) delete
The documentation for this class was generated from the following files:
lib/Target/PowerPC/MCTargetDesc/PPCMCCodeEmitter.h
lib/Target/PowerPC/MCTargetDesc/PPCMCCodeEmitter.cpp