LLVM: llvm::symbolize::LLVMSymbolizer Class Reference
llvm::symbolize::LLVMSymbolizer Class Reference
#include "llvm/DebugInfo/Symbolize/Symbolize.h"
Classes
struct Options
Public Member Functions
LLVMSymbolizer ()
LLVMSymbolizer (const Options &Opts)
~LLVMSymbolizer ()
Expected< DILineInfo > symbolizeCode (const ObjectFile &Obj, object::SectionedAddress ModuleOffset)
Expected< DILineInfo > symbolizeCode (const std::string &ModuleName, object::SectionedAddress ModuleOffset)
Expected< DILineInfo > symbolizeCode (ArrayRef< uint8_t > BuildID, object::SectionedAddress ModuleOffset)
Expected< DIInliningInfo > symbolizeInlinedCode (const ObjectFile &Obj, object::SectionedAddress ModuleOffset)
Expected< DIInliningInfo > symbolizeInlinedCode (const std::string &ModuleName, object::SectionedAddress ModuleOffset)
Expected< DIInliningInfo > symbolizeInlinedCode (ArrayRef< uint8_t > BuildID, object::SectionedAddress ModuleOffset)
Expected< DIGlobal > symbolizeData (const ObjectFile &Obj, object::SectionedAddress ModuleOffset)
Expected< DIGlobal > symbolizeData (const std::string &ModuleName, object::SectionedAddress ModuleOffset)
Expected< DIGlobal > symbolizeData (ArrayRef< uint8_t > BuildID, object::SectionedAddress ModuleOffset)
Expected< std::vector< DILocal > > symbolizeFrame (const ObjectFile &Obj, object::SectionedAddress ModuleOffset)
Expected< std::vector< DILocal > > symbolizeFrame (const std::string &ModuleName, object::SectionedAddress ModuleOffset)
Expected< std::vector< DILocal > > symbolizeFrame (ArrayRef< uint8_t > BuildID, object::SectionedAddress ModuleOffset)
Expected< std::vector< DILineInfo > > findSymbol (const ObjectFile &Obj, StringRef Symbol, uint64_t Offset)
Expected< std::vector< DILineInfo > > findSymbol (const std::string &ModuleName, StringRef Symbol, uint64_t Offset)
Expected< std::vector< DILineInfo > > findSymbol (ArrayRef< uint8_t > BuildID, StringRef Symbol, uint64_t Offset)
void flush ()
void pruneCache ()
void setBuildIDFetcher (std::unique_ptr< BuildIDFetcher > Fetcher)
Expected< SymbolizableModule * > getOrCreateModuleInfo (const std::string &ModuleName)
Returns a SymbolizableModule or an error if loading debug info failed.
Static Public Member Functions
static std::string DemangleName (const std::string &Name, const SymbolizableModule *DbiModuleDescriptor)
Detailed Description
Definition at line 50 of file Symbolize.h.
Constructor & Destructor Documentation
LLVMSymbolizer() [1/2]
llvm::symbolize::LLVMSymbolizer::LLVMSymbolizer () default
LLVMSymbolizer() [2/2]
llvm::symbolize::LLVMSymbolizer::LLVMSymbolizer (const Options & Opts)
Definition at line 46 of file Symbolize.cpp.
~LLVMSymbolizer()
llvm::symbolize::LLVMSymbolizer::~LLVMSymbolizer () default
Member Function Documentation
DemangleName()
std::string llvm::symbolize::LLVMSymbolizer::DemangleName (const std::string & Name, const SymbolizableModule * DbiModuleDescriptor) static
Definition at line 746 of file Symbolize.cpp.
References llvm::symbolize::SymbolizableModule::isWin32Module(), llvm::microsoftDemangle(), llvm::MSDF_NoAccessSpecifier, llvm::MSDF_NoCallingConvention, llvm::MSDF_NoMemberType, llvm::MSDF_NoReturnType, Name, and llvm::nonMicrosoftDemangle().
findSymbol() [1/3]
Expected< std::vector< DILineInfo > > llvm::symbolize::LLVMSymbolizer::findSymbol (ArrayRef< uint8_t > BuildID, StringRef Symbol, uint64_t Offset)
Definition at line 277 of file Symbolize.cpp.
References llvm::Offset.
findSymbol() [2/3]
Expected< std::vector< DILineInfo > > llvm::symbolize::LLVMSymbolizer::findSymbol (const ObjectFile & Obj, StringRef Symbol, uint64_t Offset)
Definition at line 265 of file Symbolize.cpp.
References llvm::Offset.
findSymbol() [3/3]
Expected< std::vector< DILineInfo > > llvm::symbolize::LLVMSymbolizer::findSymbol (const std::string & ModuleName, StringRef Symbol, uint64_t Offset)
Definition at line 271 of file Symbolize.cpp.
References llvm::Offset.
flush()
void llvm::symbolize::LLVMSymbolizer::flush ()
Definition at line 282 of file Symbolize.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::clear().
getOrCreateModuleInfo()
Expected< SymbolizableModule * > llvm::symbolize::LLVMSymbolizer::getOrCreateModuleInfo (const std::string & ModuleName)
Returns a SymbolizableModule or an error if loading debug info failed.
Only one attempt is made to load a module, and errors during loading are only reported once. Subsequent calls to get module info for a module that failed to load will return nullptr.
Definition at line 603 of file Symbolize.cpp.
References llvm::any_of(), llvm::DWARFContext::create(), llvm::createFileError(), llvm::dwarf_linker::DebugInfo, llvm::symbolize::LLVMSymbolizer::Options::DefaultArch, llvm::symbolize::LLVMSymbolizer::Options::DWPName, llvm::dyn_cast(), llvm::StringRef::empty(), I, llvm::DWARFContext::Process, llvm::Triple::UnknownArch, and llvm::symbolize::LLVMSymbolizer::Options::UseDIA.
pruneCache()
void llvm::symbolize::LLVMSymbolizer::pruneCache ()
Definition at line 782 of file Symbolize.cpp.
References llvm::Bin, and llvm::symbolize::LLVMSymbolizer::Options::MaxCacheSize.
setBuildIDFetcher()
void llvm::symbolize::LLVMSymbolizer::setBuildIDFetcher (std::unique_ptr< BuildIDFetcher > Fetcher) inline
Definition at line 126 of file Symbolize.h.
symbolizeCode() [1/3]
Expected< DILineInfo > llvm::symbolize::LLVMSymbolizer::symbolizeCode (ArrayRef< uint8_t > BuildID, object::SectionedAddress ModuleOffset)
Definition at line 94 of file Symbolize.cpp.
symbolizeCode() [2/3]
Expected< DILineInfo > llvm::symbolize::LLVMSymbolizer::symbolizeCode (const ObjectFile & Obj, object::SectionedAddress ModuleOffset)
Definition at line 82 of file Symbolize.cpp.
symbolizeCode() [3/3]
Expected< DILineInfo > llvm::symbolize::LLVMSymbolizer::symbolizeCode (const std::string & ModuleName, object::SectionedAddress ModuleOffset)
Definition at line 88 of file Symbolize.cpp.
symbolizeData() [1/3]
Expected< DIGlobal > llvm::symbolize::LLVMSymbolizer::symbolizeData (ArrayRef< uint8_t > BuildID, object::SectionedAddress ModuleOffset)
Definition at line 188 of file Symbolize.cpp.
symbolizeData() [2/3]
Expected< DIGlobal > llvm::symbolize::LLVMSymbolizer::symbolizeData (const ObjectFile & Obj, object::SectionedAddress ModuleOffset)
Definition at line 176 of file Symbolize.cpp.
symbolizeData() [3/3]
Expected< DIGlobal > llvm::symbolize::LLVMSymbolizer::symbolizeData (const std::string & ModuleName, object::SectionedAddress ModuleOffset)
Definition at line 182 of file Symbolize.cpp.
symbolizeFrame() [1/3]
Expected< std::vector< DILocal > > llvm::symbolize::LLVMSymbolizer::symbolizeFrame (ArrayRef< uint8_t > BuildID, object::SectionedAddress ModuleOffset)
Definition at line 229 of file Symbolize.cpp.
symbolizeFrame() [2/3]
Expected< std::vector< DILocal > > llvm::symbolize::LLVMSymbolizer::symbolizeFrame (const ObjectFile & Obj, object::SectionedAddress ModuleOffset)
Definition at line 217 of file Symbolize.cpp.
symbolizeFrame() [3/3]
Expected< std::vector< DILocal > > llvm::symbolize::LLVMSymbolizer::symbolizeFrame (const std::string & ModuleName, object::SectionedAddress ModuleOffset)
Definition at line 223 of file Symbolize.cpp.
symbolizeInlinedCode() [1/3]
Expected< DIInliningInfo > llvm::symbolize::LLVMSymbolizer::symbolizeInlinedCode (ArrayRef< uint8_t > BuildID, object::SectionedAddress ModuleOffset)
Definition at line 143 of file Symbolize.cpp.
symbolizeInlinedCode() [2/3]
Expected< DIInliningInfo > llvm::symbolize::LLVMSymbolizer::symbolizeInlinedCode (const ObjectFile & Obj, object::SectionedAddress ModuleOffset)
Definition at line 131 of file Symbolize.cpp.
symbolizeInlinedCode() [3/3]
Expected< DIInliningInfo > llvm::symbolize::LLVMSymbolizer::symbolizeInlinedCode (const std::string & ModuleName, object::SectionedAddress ModuleOffset)
Definition at line 137 of file Symbolize.cpp.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/Symbolize/Symbolize.h
lib/DebugInfo/Symbolize/Symbolize.cpp