LLVM: llvm::orc::PerfSupportPlugin Class Reference
llvm::orc::PerfSupportPlugin Class Reference
Log perf jitdump events for each object (see https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/perf/Documentation/jitdump-specification.txt).
#include "llvm/ExecutionEngine/Orc/Debugging/PerfSupportPlugin.h"
Public Member Functions
PerfSupportPlugin (ExecutorProcessControl &EPC, ExecutorAddr RegisterPerfStartAddr, ExecutorAddr RegisterPerfEndAddr, ExecutorAddr RegisterPerfImplAddr, bool EmitDebugInfo, bool EmitUnwindInfo)
~PerfSupportPlugin ()
void modifyPassConfig (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::PassConfiguration &Config) override
Error notifyFailed (MaterializationResponsibility &MR) override
Error notifyRemovingResources (JITDylib &JD, ResourceKey K) override
void notifyTransferringResources (JITDylib &JD, ResourceKey DstKey, ResourceKey SrcKey) override
Public Member Functions inherited from llvm::orc::ObjectLinkingLayer::Plugin
virtual ~Plugin ()
virtual void notifyMaterializing (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::JITLinkContext &Ctx, MemoryBufferRef InputObject)
virtual void notifyLoaded (MaterializationResponsibility &MR)
virtual Error notifyEmitted (MaterializationResponsibility &MR)
virtual SyntheticSymbolDependenciesMap getSyntheticSymbolDependencies (MaterializationResponsibility &MR)
Return any dependencies that synthetic symbols (e.g.
Static Public Member Functions
static Expected< std::unique_ptr< PerfSupportPlugin > > Create (ExecutorProcessControl &EPC, JITDylib &JD, bool EmitDebugInfo, bool EmitUnwindInfo)
Additional Inherited Members
Public Types inherited from llvm::orc::ObjectLinkingLayer::Plugin
using JITLinkSymbolSet = DenseSet<jitlink::Symbol *>
using SyntheticSymbolDependenciesMap
Detailed Description
Log perf jitdump events for each object (see https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/tools/perf/Documentation/jitdump-specification.txt).
Currently has support for dumping code load records and unwind info records.
Definition at line 27 of file PerfSupportPlugin.h.
Constructor & Destructor Documentation
PerfSupportPlugin()
PerfSupportPlugin::PerfSupportPlugin (ExecutorProcessControl & EPC, ExecutorAddr RegisterPerfStartAddr, ExecutorAddr RegisterPerfEndAddr, ExecutorAddr RegisterPerfImplAddr, bool EmitDebugInfo, bool EmitUnwindInfo)
Definition at line 255 of file PerfSupportPlugin.cpp.
References llvm::cantFail().
~PerfSupportPlugin()
PerfSupportPlugin::~PerfSupportPlugin ()
Definition at line 266 of file PerfSupportPlugin.cpp.
References llvm::cantFail().
Member Function Documentation
Create()
Expected< std::unique_ptr< PerfSupportPlugin > > PerfSupportPlugin::Create (ExecutorProcessControl & EPC, JITDylib & JD, bool EmitDebugInfo, bool EmitUnwindInfo) static
Definition at line 286 of file PerfSupportPlugin.cpp.
References llvm::inconvertibleErrorCode(), llvm::orc::lookupAndRecordAddrs(), and llvm::make_error().
modifyPassConfig()
void PerfSupportPlugin::modifyPassConfig (MaterializationResponsibility & MR, jitlink::LinkGraph & G, jitlink::PassConfiguration & Config) override virtual
Reimplemented from llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 270 of file PerfSupportPlugin.cpp.
References llvm::cantFail(), Config, llvm::orc::shared::WrapperFunctionCall::Create(), G, and llvm::Error::success().
notifyFailed()
Error llvm::orc::PerfSupportPlugin::notifyFailed (MaterializationResponsibility & MR) inline override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 40 of file PerfSupportPlugin.h.
References llvm::Error::success().
notifyRemovingResources()
Error llvm::orc::PerfSupportPlugin::notifyRemovingResources (JITDylib & JD, ResourceKey K) inline override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 44 of file PerfSupportPlugin.h.
References llvm::Error::success().
notifyTransferringResources()
void llvm::orc::PerfSupportPlugin::notifyTransferringResources (JITDylib & JD, ResourceKey DstKey, ResourceKey SrcKey) inline override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 48 of file PerfSupportPlugin.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Debugging/PerfSupportPlugin.h
lib/ExecutionEngine/Orc/Debugging/PerfSupportPlugin.cpp