LLVM: llvm::InsertPosition Class Reference
llvm::InsertPosition Class Reference
#include "llvm/IR/Instruction.h"
Public Member Functions
InsertPosition (std::nullptr_t)
InsertPosition (Instruction *InsertBefore)
InsertPosition (BasicBlock *InsertAtEnd)
InsertPosition (InstListType::iterator InsertAt)
operator InstListType::iterator () const
bool isValid () const
BasicBlock * getBasicBlock ()
Detailed Description
Definition at line 48 of file Instruction.h.
Constructor & Destructor Documentation
InsertPosition() [1/4]
llvm::InsertPosition::InsertPosition (std::nullptr_t) inline
Definition at line 54 of file Instruction.h.
InsertPosition() [2/4]
InsertPosition::InsertPosition (Instruction * InsertBefore)
Definition at line 29 of file Instruction.cpp.
InsertPosition() [3/4]
InsertPosition::InsertPosition (BasicBlock * InsertAtEnd)
Definition at line 32 of file Instruction.cpp.
InsertPosition() [4/4]
llvm::InsertPosition::InsertPosition (InstListType::iterator InsertAt) inline
Definition at line 59 of file Instruction.h.
Member Function Documentation
getBasicBlock()
BasicBlock * llvm::InsertPosition::getBasicBlock () inline
Definition at line 62 of file Instruction.h.
Referenced by computeAllocaDefaultAlign(), and computeLoadStoreDefaultAlign().
isValid()
bool llvm::InsertPosition::isValid () const inline
Definition at line 61 of file Instruction.h.
Referenced by computeAllocaDefaultAlign(), computeLoadStoreDefaultAlign(), llvm::CmpInst::Create(), and llvm::Instruction::Instruction().
operator InstListType::iterator()
llvm::InsertPosition::operator InstListType::iterator () const inline
Definition at line 60 of file Instruction.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Instruction.h
lib/IR/Instruction.cpp