LLVM: llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator Class Reference
llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator Class Reference
#include "Target/X86/ImmutableGraph.h"
Public Member Functions
iterator (const NodeSet &Set, size_type Begin)
iterator operator++ (int)
iterator & operator++ ()
Node * operator* () const
bool operator== (const iterator &other) const
bool operator!= (const iterator &other) const
Detailed Description
template<typename NodeValueT, typename EdgeValueT>
class llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator
Definition at line 163 of file ImmutableGraph.h.
Constructor & Destructor Documentation
iterator()
template<typename NodeValueT , typename EdgeValueT > llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator::iterator (const NodeSet & Set, size_type Begin) inline
Definition at line 173 of file ImmutableGraph.h.
Member Function Documentation
operator!=()
template<typename NodeValueT , typename EdgeValueT > bool llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator::operator!= (const iterator & other) const inline
Definition at line 192 of file ImmutableGraph.h.
operator*()
template<typename NodeValueT , typename EdgeValueT > Node * llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator::operator* () const inline
Definition at line 184 of file ImmutableGraph.h.
References assert(), and llvm::ImmutableGraph< NodeValueT, EdgeValueT >::nodes_begin().
operator++() [1/2]
template<typename NodeValueT , typename EdgeValueT > iterator & llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator::operator++ () inline
Definition at line 180 of file ImmutableGraph.h.
operator++() [2/2]
template<typename NodeValueT , typename EdgeValueT > iterator llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator::operator++ (int) inline
Definition at line 175 of file ImmutableGraph.h.
operator==()
template<typename NodeValueT , typename EdgeValueT > bool llvm::ImmutableGraph< NodeValueT, EdgeValueT >::NodeSet::iterator::operator== (const iterator & other) const inline
Definition at line 188 of file ImmutableGraph.h.
References assert().
The documentation for this class was generated from the following file:
lib/Target/X86/ImmutableGraph.h