LLVM: llvm::objcopy::xcoff::XCOFFWriter Class Reference
llvm::objcopy::xcoff::XCOFFWriter Class Reference
#include "ObjCopy/XCOFF/XCOFFWriter.h"
Public Member Functions
virtual ~XCOFFWriter ()
XCOFFWriter (Object &Obj, raw_ostream &Out)
Error write ()
Detailed Description
Definition at line 21 of file XCOFFWriter.h.
Constructor & Destructor Documentation
~XCOFFWriter()
virtual llvm::objcopy::xcoff::XCOFFWriter::~XCOFFWriter () inline virtual
Definition at line 23 of file XCOFFWriter.h.
XCOFFWriter()
llvm::objcopy::xcoff::XCOFFWriter::XCOFFWriter (Object & Obj, raw_ostream & Out) inline
Definition at line 24 of file XCOFFWriter.h.
Member Function Documentation
write()
Error llvm::objcopy::xcoff::XCOFFWriter::write ()
Definition at line 108 of file XCOFFWriter.cpp.
References llvm::createStringError(), llvm::WritableMemoryBuffer::getNewMemBuffer(), llvm::not_enough_memory, llvm::Error::success(), llvm::Twine::utohexstr(), and llvm::raw_ostream::write().
Referenced by llvm::objcopy::xcoff::executeObjcopyOnBinary().
The documentation for this class was generated from the following files:
lib/ObjCopy/XCOFF/XCOFFWriter.h
lib/ObjCopy/XCOFF/XCOFFWriter.cpp