LLVM: llvm::WasmEHPreparePass Class Reference
llvm::WasmEHPreparePass Class Reference
#include "llvm/CodeGen/WasmEHPrepare.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &FAM)
Public Member Functions inherited from llvm::PassInfoMixin< WasmEHPreparePass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< WasmEHPreparePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 16 of file WasmEHPrepare.h.
Member Function Documentation
run()
PreservedAnalyses WasmEHPreparePass::run (Function & F, FunctionAnalysisManager & FAM)
Definition at line 143 of file WasmEHPrepare.cpp.
References Changed, F, llvm::PointerType::get(), llvm::StructType::get(), llvm::Type::getInt32Ty(), llvm::PreservedAnalyses::none(), and P.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/WasmEHPrepare.h
lib/CodeGen/WasmEHPrepare.cpp