LLVM: llvm::SparseBitVector< Element > Class Template Reference
llvm::SparseBitVector< Element > Class Template Reference
#include "llvm/ADT/SparseBitVector.h"
Public Types
using iterator = SparseBitVectorIterator
Public Member Functions
SparseBitVector ()
SparseBitVector (const SparseBitVector &RHS)
SparseBitVector (SparseBitVector &&RHS)
void clear ()
SparseBitVector & operator= (const SparseBitVector &RHS)
SparseBitVector & operator= (SparseBitVector &&RHS)
bool test (unsigned Idx) const
void reset (unsigned Idx)
void set (unsigned Idx)
bool test_and_set (unsigned Idx)
bool operator!= (const SparseBitVector &RHS) const
bool operator== (const SparseBitVector &RHS) const
bool operator|= (const SparseBitVector &RHS)
bool operator&= (const SparseBitVector &RHS)
bool intersectWithComplement (const SparseBitVector &RHS)
bool intersectWithComplement (const SparseBitVector< ElementSize > *RHS) const
void intersectWithComplement (const SparseBitVector< ElementSize > &RHS1, const SparseBitVector< ElementSize > &RHS2)
void intersectWithComplement (const SparseBitVector< ElementSize > *RHS1, const SparseBitVector< ElementSize > *RHS2)
bool intersects (const SparseBitVector< ElementSize > *RHS) const
bool intersects (const SparseBitVector< ElementSize > &RHS) const
bool contains (const SparseBitVector< ElementSize > &RHS) const
int find_first () const
int find_last () const
bool empty () const
unsigned count () const
iterator begin () const
iterator end () const
Detailed Description
template<unsigned Element>
class llvm::SparseBitVector< Element >
Definition at line 33 of file LiveIntervalUnion.h.
Member Typedef Documentation
iterator
template<unsigned Element> using llvm::SparseBitVector< Element >::iterator = SparseBitVectorIterator
Definition at line 442 of file SparseBitVector.h.
Constructor & Destructor Documentation
SparseBitVector() [1/3]
template<unsigned Element> llvm::SparseBitVector< Element >::SparseBitVector () inline
Definition at line 444 of file SparseBitVector.h.
SparseBitVector() [2/3]
template<unsigned Element> llvm::SparseBitVector< Element >::SparseBitVector (const SparseBitVector< Element > & RHS) inline
Definition at line 446 of file SparseBitVector.h.
SparseBitVector() [3/3]
template<unsigned Element> llvm::SparseBitVector< Element >::SparseBitVector (SparseBitVector< Element > && RHS) inline
Definition at line 448 of file SparseBitVector.h.
Member Function Documentation
begin()
template<unsigned Element> iterator llvm::SparseBitVector< Element >::begin () const inline
Definition at line 810 of file SparseBitVector.h.
clear()
template<unsigned Element> void llvm::SparseBitVector< Element >::clear () inline
Definition at line 452 of file SparseBitVector.h.
Referenced by llvm::pdb::HashTable< ValueT >::clear(), llvm::SIInstrInfo::convertToThreeAddress(), and llvm::SparseBitVector< Element >::intersectWithComplement().
contains()
template<unsigned Element> bool llvm::SparseBitVector< Element >::contains (const SparseBitVector< ElementSize > & RHS) const inline
Definition at line 773 of file SparseBitVector.h.
References RHS.
count()
template<unsigned Element> unsigned llvm::SparseBitVector< Element >::count () const inline
Definition at line 800 of file SparseBitVector.h.
Referenced by llvm::pdb::HashTable< ValueT >::load(), and llvm::pdb::HashTable< ValueT >::size().
empty()
template<unsigned Element> bool llvm::SparseBitVector< Element >::empty () const inline
Definition at line 796 of file SparseBitVector.h.
Referenced by llvm::LiveVariables::HandleVirtRegDef(), and llvm::SparseBitVector< Element >::intersectWithComplement().
end()
template<unsigned Element> iterator llvm::SparseBitVector< Element >::end () const inline
Definition at line 814 of file SparseBitVector.h.
find_first()
template<unsigned Element> int llvm::SparseBitVector< Element >::find_first () const inline
Definition at line 780 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::find_first(), and llvm::First.
find_last()
template<unsigned Element> int llvm::SparseBitVector< Element >::find_last () const inline
Definition at line 788 of file SparseBitVector.h.
References llvm::SparseBitVectorElement< ElementSize >::find_last(), and llvm::Last.
Referenced by llvm::pdb::HashTable< ValueT >::calculateSerializedLength(), llvm::DivergencePropagator< ContextT >::computeJoinPoints(), and llvm::pdb::writeSparseBitVector().
intersects() [1/2]
template<unsigned Element> bool llvm::SparseBitVector< Element >::intersects (const SparseBitVector< ElementSize > & RHS) const inline
Definition at line 744 of file SparseBitVector.h.
intersects() [2/2]
template<unsigned Element> bool llvm::SparseBitVector< Element >::intersects (const SparseBitVector< ElementSize > * RHS) const inline
Definition at line 739 of file SparseBitVector.h.
References llvm::SparseBitVector< Element >::intersects().
Referenced by llvm::SparseBitVector< Element >::intersects(), and llvm::pdb::HashTable< ValueT >::load().
intersectWithComplement() [1/4]
template<unsigned Element> bool llvm::SparseBitVector< Element >::intersectWithComplement (const SparseBitVector< Element > & RHS) inline
Definition at line 637 of file SparseBitVector.h.
References llvm::SparseBitVector< Element >::clear(), and llvm::SparseBitVector< Element >::empty().
Referenced by llvm::SparseBitVector< Element >::intersectWithComplement(), llvm::SparseBitVector< Element >::intersectWithComplement(), and llvm::SparseBitVector< Element >::intersectWithComplement().
intersectWithComplement() [2/4]
template<unsigned Element> void llvm::SparseBitVector< Element >::intersectWithComplement (const SparseBitVector< ElementSize > & RHS1, const SparseBitVector< ElementSize > & RHS2) inline
Definition at line 688 of file SparseBitVector.h.
References llvm::SparseBitVector< Element >::intersectWithComplement().
intersectWithComplement() [3/4]
template<unsigned Element> bool llvm::SparseBitVector< Element >::intersectWithComplement (const SparseBitVector< ElementSize > * RHS) const inline
Definition at line 682 of file SparseBitVector.h.
References llvm::SparseBitVector< Element >::intersectWithComplement().
intersectWithComplement() [4/4]
template<unsigned Element> void llvm::SparseBitVector< Element >::intersectWithComplement (const SparseBitVector< ElementSize > * RHS1, const SparseBitVector< ElementSize > * RHS2) inline
Definition at line 734 of file SparseBitVector.h.
References llvm::SparseBitVector< Element >::intersectWithComplement().
operator!=()
template<unsigned Element> bool llvm::SparseBitVector< Element >::operator!= (const SparseBitVector< Element > & RHS) const inline
Definition at line 541 of file SparseBitVector.h.
References RHS.
operator&=()
template<unsigned Element> bool llvm::SparseBitVector< Element >::operator&= (const SparseBitVector< Element > & RHS) inline
Definition at line 588 of file SparseBitVector.h.
operator=() [1/2]
template<unsigned Element> SparseBitVector & llvm::SparseBitVector< Element >::operator= (const SparseBitVector< Element > & RHS) inline
Definition at line 457 of file SparseBitVector.h.
operator=() [2/2]
template<unsigned Element> SparseBitVector & llvm::SparseBitVector< Element >::operator= (SparseBitVector< Element > && RHS) inline
Definition at line 465 of file SparseBitVector.h.
operator==()
template<unsigned Element> bool llvm::SparseBitVector< Element >::operator== (const SparseBitVector< Element > & RHS) const inline
Definition at line 545 of file SparseBitVector.h.
operator|=()
template<unsigned Element> bool llvm::SparseBitVector< Element >::operator|= (const SparseBitVector< Element > & RHS) inline
Definition at line 558 of file SparseBitVector.h.
reset()
template<unsigned Element> void llvm::SparseBitVector< Element >::reset (unsigned Idx) inline
Definition at line 487 of file SparseBitVector.h.
Referenced by llvm::DivergencePropagator< ContextT >::computeJoinPoints().
set()
template<unsigned Element> void llvm::SparseBitVector< Element >::set (unsigned Idx) inline
Definition at line 508 of file SparseBitVector.h.
Referenced by llvm::LiveVariables::addNewBlock(), llvm::LiveVariables::addNewBlock(), llvm::DivergencePropagator< ContextT >::computeJoin(), locateCStrings(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), llvm::LiveVariables::recomputeForSingleDefVirtReg(), llvm::SparseBitVector< Element >::test_and_set(), and llvm::LiveIntervalUnion::verify().
test()
template<unsigned Element> bool llvm::SparseBitVector< Element >::test (unsigned Idx) const inline
Definition at line 472 of file SparseBitVector.h.
Referenced by callBufferedPrintfArgPush(), callBufferedPrintfStart(), llvm::emitAMDGPUPrintfCall(), llvm::LiveVariables::HandleVirtRegUse(), llvm::pdb::HashTable< ValueT >::isDeleted(), llvm::pdb::HashTable< ValueT >::isPresent(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), and llvm::pdb::writeSparseBitVector().
test_and_set()
template<unsigned Element> bool llvm::SparseBitVector< Element >::test_and_set (unsigned Idx) inline
Definition at line 532 of file SparseBitVector.h.
References llvm::SparseBitVector< Element >::set(), and test.
The documentation for this class was generated from the following files:
include/llvm/ADT/SparseBitVector.h
include/llvm/CodeGen/LiveIntervalUnion.h