LLVM: llvm::orc::AllocGroupSmallMap< T > Class Template Reference
llvm::orc::AllocGroupSmallMap< T > Class Template Reference
A specialized small-map for AllocGroups.
#include "llvm/ExecutionEngine/Orc/Shared/MemoryFlags.h"
Public Types
using iterator = typename VectorTy::iterator
Public Member Functions
AllocGroupSmallMap ()=default
AllocGroupSmallMap (std::initializer_list< std::pair< AllocGroup, T > > Inits)
iterator begin ()
iterator end ()
iterator find (AllocGroup G)
bool empty () const
size_t size () const
T & operator[] (AllocGroup G)
Detailed Description
template<typename T>
class llvm::orc::AllocGroupSmallMap< T >
A specialized small-map for AllocGroups.
Iteration order is guaranteed to match key ordering.
Definition at line 165 of file MemoryFlags.h.
Member Typedef Documentation
iterator
template<typename T > using llvm::orc::AllocGroupSmallMap< T >::iterator = typename VectorTy::iterator
Definition at line 175 of file MemoryFlags.h.
Constructor & Destructor Documentation
AllocGroupSmallMap() [1/2]
template<typename T > llvm::orc::AllocGroupSmallMap< T >::AllocGroupSmallMap () default
AllocGroupSmallMap() [2/2]
template<typename T > llvm::orc::AllocGroupSmallMap< T >::AllocGroupSmallMap (std::initializer_list< std::pair< AllocGroup, T > > Inits) inline
Definition at line 178 of file MemoryFlags.h.
References llvm::sort().
Member Function Documentation
begin()
template<typename T > iterator llvm::orc::AllocGroupSmallMap< T >::begin () inline
Definition at line 183 of file MemoryFlags.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by llvm::jitlink::BasicLayout::segments().
empty()
template<typename T > bool llvm::orc::AllocGroupSmallMap< T >::empty () const inline
Definition at line 190 of file MemoryFlags.h.
References llvm::SmallVectorBase< Size_T >::empty().
end()
template<typename T > iterator llvm::orc::AllocGroupSmallMap< T >::end () inline
Definition at line 184 of file MemoryFlags.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::orc::AllocGroupSmallMap< T >::find(), and llvm::jitlink::BasicLayout::segments().
find()
template<typename T > iterator llvm::orc::AllocGroupSmallMap< T >::find (AllocGroup G) inline
Definition at line 185 of file MemoryFlags.h.
References llvm::orc::AllocGroupSmallMap< T >::end(), G, I, and llvm::lower_bound().
operator[]()
template<typename T > T & llvm::orc::AllocGroupSmallMap< T >::operator[] (AllocGroup G) inline
Definition at line 193 of file MemoryFlags.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), G, I, llvm::SmallVectorImpl< T >::insert(), llvm::lower_bound(), and T.
size()
template<typename T > size_t llvm::orc::AllocGroupSmallMap< T >::size () const inline
Definition at line 191 of file MemoryFlags.h.
References llvm::SmallVectorBase< Size_T >::size().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/MemoryFlags.h