LLVM: llvm::DWARFDie Class Reference
llvm::DWARFDie Class Reference
Utility class that carries the DWARF compile/type unit and the debug info entry in an object.
#include "llvm/DebugInfo/DWARF/DWARFDie.h"
Classes
class attribute_iterator
class iterator
Public Member Functions
DWARFDie ()=default
DWARFDie (DWARFUnit *Unit, const DWARFDebugInfoEntry *D)
bool isValid () const
operator bool () const
const DWARFDebugInfoEntry * getDebugInfoEntry () const
DWARFUnit * getDwarfUnit () const
const DWARFAbbreviationDeclaration * getAbbreviationDeclarationPtr () const
Get the abbreviation declaration for this DIE.
uint64_t getOffset () const
Get the absolute offset into the debug info or types section.
dwarf::Tag getTag () const
bool hasChildren () const
bool isNULL () const
Returns true for a valid DIE that terminates a sibling chain.
bool isSubprogramDIE () const
Returns true if DIE represents a subprogram (not inlined).
bool isSubroutineDIE () const
Returns true if DIE represents a subprogram or an inlined subroutine.
DWARFDie getParent () const
Get the parent of this DIE object.
DWARFDie getSibling () const
Get the sibling of this DIE object.
DWARFDie getPreviousSibling () const
Get the previous sibling of this DIE object.
DWARFDie getFirstChild () const
Get the first child of this DIE object.
DWARFDie getLastChild () const
Get the last child of this DIE object.
void dump (raw_ostream &OS, unsigned indent=0, DIDumpOptions DumpOpts=DIDumpOptions()) const
Dump the DIE and all of its attributes to the supplied stream.
LLVM_DUMP_METHOD void dump () const
Convenience zero-argument overload for debugging.
std::optional< DWARFFormValue > find (dwarf::Attribute Attr) const
Extract the specified attribute from this DIE.
std::optional< DWARFFormValue > find (ArrayRef< dwarf::Attribute > Attrs) const
Extract the first value of any attribute in Attrs from this DIE.
std::optional< DWARFFormValue > findRecursively (ArrayRef< dwarf::Attribute > Attrs) const
Extract the first value of any attribute in Attrs from this DIE and recurse into any DW_AT_specification or DW_AT_abstract_origin referenced DIEs.
DWARFDie getAttributeValueAsReferencedDie (dwarf::Attribute Attr) const
Extract the specified attribute from this DIE as the referenced DIE.
DWARFDie getAttributeValueAsReferencedDie (const DWARFFormValue &V) const
DWARFDie resolveTypeUnitReference () const
std::optional< uint64_t > getRangesBaseAttribute () const
Extract the range base attribute from this DIE as absolute section offset.
std::optional< uint64_t > getLocBaseAttribute () const
std::optional< uint64_t > getHighPC (uint64_t LowPC) const
Get the DW_AT_high_pc attribute value as an address.
bool getLowAndHighPC (uint64_t &LowPC, uint64_t &HighPC, uint64_t &SectionIndex) const
Retrieves DW_AT_low_pc and DW_AT_high_pc from CU.
Expected< DWARFAddressRangesVector > getAddressRanges () const
Get the address ranges for this DIE.
bool addressRangeContainsAddress (const uint64_t Address) const
Expected< DWARFLocationExpressionsVector > getLocations (dwarf::Attribute Attr) const
const char * getSubroutineName (DINameKind Kind) const
If a DIE represents a subprogram (or inlined subroutine), returns its mangled name (or short name, if mangled is missing).
const char * getName (DINameKind Kind) const
Return the DIE name resolving DW_AT_specification or DW_AT_abstract_origin references if necessary.
void getFullName (raw_string_ostream &, std::string *OriginalFullName=nullptr) const
const char * getShortName () const
Return the DIE short name resolving DW_AT_specification or DW_AT_abstract_origin references if necessary.
const char * getLinkageName () const
Return the DIE linkage name resolving DW_AT_specification or DW_AT_abstract_origin references if necessary.
uint64_t getDeclLine () const
Returns the declaration line (start line) for a DIE, assuming it specifies a subprogram.
std::string getDeclFile (DILineInfoSpecifier::FileLineInfoKind Kind) const
void getCallerFrame (uint32_t &CallFile, uint32_t &CallLine, uint32_t &CallColumn, uint32_t &CallDiscriminator) const
Retrieves values of DW_AT_call_file, DW_AT_call_line and DW_AT_call_column from DIE (or zeroes if they are missing).
iterator_range< attribute_iterator > attributes () const
Get an iterator range to all attributes in the current DIE only.
std::optional< uint64_t > getTypeSize (uint64_t PointerSize)
Gets the type size (in bytes) for this DIE.
iterator begin () const
iterator end () const
std::reverse_iterator< iterator > rbegin () const
std::reverse_iterator< iterator > rend () const
iterator_range< iterator > children () const
Detailed Description
Utility class that carries the DWARF compile/type unit and the debug info entry in an object.
When accessing information from a debug info entry we always need to DWARF compile/type unit in order to extract the info correctly as some information is relative to the compile/type unit. Prior to this class the DWARFUnit and the DWARFDebugInfoEntry was passed around separately and there was the possibility for error if the wrong DWARFUnit was used to extract a unit relative offset. This class helps to ensure that this doesn't happen and also simplifies the attribute extraction calls by not having to specify the DWARFUnit for each call.
Definition at line 42 of file DWARFDie.h.
Constructor & Destructor Documentation
DWARFDie() [1/2]
llvm::DWARFDie::DWARFDie () default
Referenced by getAttributeValueAsReferencedDie(), getFirstChild(), getLastChild(), getParent(), getPreviousSibling(), and getSibling().
DWARFDie() [2/2]
llvm::DWARFDie::DWARFDie (DWARFUnit * Unit, const DWARFDebugInfoEntry * D) inline
Definition at line 48 of file DWARFDie.h.
Member Function Documentation
addressRangeContainsAddress()
bool DWARFDie::addressRangeContainsAddress (const uint64_t Address) const
Definition at line 394 of file DWARFDie.cpp.
References llvm::consumeError(), and getAddressRanges().
attributes()
iterator_range< DWARFDie::attribute_iterator > DWARFDie::attributes () const
Get an iterator range to all attributes in the current DIE only.
Returns
an iterator range for the attributes of the current DIE.
Definition at line 666 of file DWARFDie.cpp.
References llvm::make_range().
Referenced by dump().
begin()
DWARFDie::iterator llvm::DWARFDie::begin () const inline
Definition at line 387 of file DWARFDie.h.
References getFirstChild().
Referenced by children(), and rend().
children()
iterator_range< DWARFDie::iterator > llvm::DWARFDie::children () const inline
Definition at line 395 of file DWARFDie.h.
References begin(), end(), and llvm::make_range().
Referenced by llvm::analyzeContextInfo(), llvm::DWARFTypePrinter::appendArrayType(), hasInlineInfo(), parseInlineInfo(), llvm::dwarf_linker::parallel::DependencyTracker::verifyKeepChain(), and llvm::verifyKeepChain().
dump() [1/2]
LLVM_DUMP_METHOD void DWARFDie::dump () const
Convenience zero-argument overload for debugging.
Definition at line 634 of file DWARFDie.cpp.
References dump(), and llvm::errs().
Referenced by dump().
dump() [2/2]
void DWARFDie::dump (raw_ostream & OS, unsigned indent = 0, DIDumpOptions DumpOpts = DIDumpOptions()) const
Dump the DIE and all of its attributes to the supplied stream.
Parameters
OS the stream to use for output.
indent the number of characters to indent each line that is output.
Definition at line 576 of file DWARFDie.cpp.
References llvm::Address, attributes(), llvm::DIDumpOptions::ChildRecurseDepth, dump(), dumpAttribute(), dumpParentChain(), llvm::format(), llvm::formatv(), llvm::WithColor::get(), getAbbreviationDeclarationPtr(), getFirstChild(), getOffset(), getParent(), llvm::DWARFDebugInfoEntry::getParentIdx(), getSibling(), getTag(), llvm::DataExtractor::getULEB128(), llvm::raw_ostream::indent(), isValid(), llvm::DataExtractor::isValidOffset(), llvm::Offset, OS, llvm::DIDumpOptions::ShowAddresses, llvm::DIDumpOptions::ShowChildren, llvm::DIDumpOptions::ShowParents, llvm::Tag, and llvm::DIDumpOptions::Verbose.
Referenced by convertFunctionLineTable(), llvm::DWARFCompileUnit::dump(), llvm::DWARFContext::dump(), dump(), and dumpParentChain().
end()
DWARFDie::iterator llvm::DWARFDie::end () const inline
Definition at line 391 of file DWARFDie.h.
References getLastChild().
Referenced by children(), and rbegin().
find() [1/2]
std::optional< DWARFFormValue > DWARFDie::find (ArrayRef< dwarf::Attribute > Attrs) const
Extract the first value of any attribute in Attrs from this DIE.
Extract the first attribute that matches from this DIE only. This call doesn't look for the attribute value in any DW_AT_specification or DW_AT_abstract_origin referenced DIEs. The attributes will be searched linearly in the order they are specified within Attrs.
Parameters
Attrs an array of DWARF attribute to look for.
Returns
an optional that has a valid DWARFFormValue for the first matching attribute in Attrs, or std::nullopt if none of the attributes in Attrs exist in this DIE.
Definition at line 260 of file DWARFDie.cpp.
References getAbbreviationDeclarationPtr(), getOffset(), isValid(), and llvm::Value.
find() [2/2]
std::optional< DWARFFormValue > DWARFDie::find (dwarf::Attribute Attr) const
Extract the specified attribute from this DIE.
Extract an attribute value from this DIE only. This call doesn't look for the attribute value in any DW_AT_specification or DW_AT_abstract_origin referenced DIEs.
Parameters
Attr the attribute to extract.
Returns
an optional DWARFFormValue that will have the form value if the attribute was successfully extracted.
Definition at line 250 of file DWARFDie.cpp.
References getAbbreviationDeclarationPtr(), getOffset(), and isValid().
Referenced by llvm::analyzeContextInfo(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitDebugMacro(), llvm::dwarf_linker::parallel::CompileUnit::CompileUnit(), llvm::logicalview::LVDWARFReader::createScopes(), llvm::gsym::CUInfo::CUInfo(), findRecursively(), getAddressRanges(), getAttributeValueAsReferencedDie(), llvm::DWARFUnit::getBaseAddress(), getCallerFrame(), getDwoId(), llvm::getDwoId(), getHighPC(), llvm::DWARFContext::getInliningInfoForAddress(), getLocations(), getLocBaseAttribute(), getLowAndHighPC(), getPCMFile(), llvm::getPCMFile(), getRangesBaseAttribute(), getTypeSizeImpl(), hashFullyQualifiedName(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::isClangModuleRef(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::link(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::loadClangModule(), parseInlineInfo(), resolveTypeUnitReference(), llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::save(), llvm::DWARFUnit::tryExtractDIEsIfNeeded(), and llvm::updatePruning().
findRecursively()
std::optional< DWARFFormValue > DWARFDie::findRecursively (ArrayRef< dwarf::Attribute > Attrs) const
Extract the first value of any attribute in Attrs from this DIE and recurse into any DW_AT_specification or DW_AT_abstract_origin referenced DIEs.
Parameters
Attrs an array of DWARF attribute to look for.
Returns
an optional that has a valid DWARFFormValue for the first matching attribute in Attrs, or std::nullopt if none of the attributes in Attrs exist in this DIE or in any DW_AT_specification or DW_AT_abstract_origin DIEs.
Definition at line 274 of file DWARFDie.cpp.
References D, llvm::SmallVectorBase< Size_T >::empty(), find(), getAttributeValueAsReferencedDie(), llvm::SmallSet< T, N, C >::insert(), isValid(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Value.
Referenced by convertFunctionLineTable(), getDeclFile(), getDeclLine(), getLinkageName(), getShortName(), and parseInlineInfo().
getAbbreviationDeclarationPtr()
const DWARFAbbreviationDeclaration * llvm::DWARFDie::getAbbreviationDeclarationPtr () const inline
Get the abbreviation declaration for this DIE.
Returns
the abbreviation declaration or NULL for null tags.
Definition at line 58 of file DWARFDie.h.
References assert(), llvm::DWARFDebugInfoEntry::getAbbreviationDeclarationPtr(), and isValid().
Referenced by llvm::DWARFDie::attribute_iterator::attribute_iterator(), dump(), find(), find(), getTag(), and isNULL().
getAddressRanges()
Expected< DWARFAddressRangesVector > DWARFDie::getAddressRanges () const
Get the address ranges for this DIE.
Get the hi/low PC range if both attributes are available or exrtracts the non-contiguous address ranges from the DW_AT_ranges attribute.
Extracts the range information from this DIE only. This call doesn't look for the range in any DW_AT_specification or DW_AT_abstract_origin DIEs.
Returns
a address range vector that might be empty if no address range information is available.
Definition at line 377 of file DWARFDie.cpp.
References find(), getLowAndHighPC(), and isNULL().
Referenced by addressRangeContainsAddress(), llvm::DWARFUnit::collectAddressRanges(), dumpAttribute(), parseInlineInfo(), and llvm::DWARFUnit::updateAddressDieMap().
getAttributeValueAsReferencedDie() [1/2]
DWARFDie DWARFDie::getAttributeValueAsReferencedDie (const DWARFFormValue & V) const
Definition at line 314 of file DWARFDie.cpp.
References llvm::DWARFUnit::getDIEForOffset(), llvm::DWARFUnitVector::getUnitForOffset(), llvm::DWARFUnit::getUnitVector(), and llvm::Offset.
getAttributeValueAsReferencedDie() [2/2]
DWARFDie DWARFDie::getAttributeValueAsReferencedDie (dwarf::Attribute Attr) const
Extract the specified attribute from this DIE as the referenced DIE.
Regardless of the reference type, return the correct DWARFDie instance if the attribute exists. The returned DWARFDie object might be from another DWARFUnit, but that is all encapsulated in the new DWARFDie object.
Extract an attribute value from this DIE only. This call doesn't look for the attribute value in any DW_AT_specification or DW_AT_abstract_origin referenced DIEs.
Parameters
Attr the attribute to extract.
Returns
a valid DWARFDie instance if the attribute exists, or an invalid DWARFDie object if it doesn't.
Definition at line 307 of file DWARFDie.cpp.
References DWARFDie(), F, find(), and getAttributeValueAsReferencedDie().
Referenced by dumpAttribute(), findRecursively(), getAttributeValueAsReferencedDie(), GetParentDeclContextDIE(), getTypeSizeImpl(), llvm::resolveReferencedType(), llvm::resolveReferencedType(), resolveReferencedType(), and llvm::DWARFUnit::updateVariableDieMap().
getCallerFrame()
void DWARFDie::getCallerFrame (uint32_t & CallFile, uint32_t & CallLine, uint32_t & CallColumn, uint32_t & CallDiscriminator) const
Retrieves values of DW_AT_call_file, DW_AT_call_line and DW_AT_call_column from DIE (or zeroes if they are missing).
This function looks for DW_AT_call attributes in this DIE only, it will not resolve the attribute values in any DW_AT_specification or DW_AT_abstract_origin DIEs.
Parameters
CallFile filled in with non-zero if successful, zero if there is no DW_AT_call_file attribute in this DIE.
CallLine filled in with non-zero if successful, zero if there is no DW_AT_call_line attribute in this DIE.
CallColumn filled in with non-zero if successful, zero if there is no DW_AT_call_column attribute in this DIE.
CallDiscriminator filled in with non-zero if successful, zero if there is no DW_AT_GNU_discriminator attribute in this DIE.
Definition at line 483 of file DWARFDie.cpp.
References find(), and llvm::dwarf::toUnsigned().
Referenced by llvm::DWARFContext::getInliningInfoForAddress().
getDebugInfoEntry()
const DWARFDebugInfoEntry * llvm::DWARFDie::getDebugInfoEntry () const inline
Definition at line 52 of file DWARFDie.h.
Referenced by llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmit(), getTypeSizeImpl(), and llvm::dwarf_linker::parallel::DependencyTracker::verifyKeepChain().
getDeclFile()
std::string DWARFDie::getDeclFile (DILineInfoSpecifier::FileLineInfoKind Kind) const
Definition at line 476 of file DWARFDie.cpp.
References findRecursively().
Referenced by convertFunctionLineTable(), llvm::DWARFContext::getInliningInfoForAddress(), and llvm::DWARFContext::getLineInfoForDataAddress().
getDeclLine()
uint64_t DWARFDie::getDeclLine () const
Returns the declaration line (start line) for a DIE, assuming it specifies a subprogram.
This may be fetched from specification or abstract origin for this subprogram by resolving DW_AT_sepcification or DW_AT_abstract_origin references if necessary.
Definition at line 471 of file DWARFDie.cpp.
References findRecursively(), and llvm::dwarf::toUnsigned().
Referenced by llvm::DWARFContext::getInliningInfoForAddress(), and llvm::DWARFContext::getLineInfoForDataAddress().
getDwarfUnit()
DWARFUnit * llvm::DWARFDie::getDwarfUnit () const inline
Definition at line 53 of file DWARFDie.h.
Referenced by llvm::logicalview::LVDWARFReader::createScopes(), llvm::DWARFContext::dump(), dumpAttribute(), llvm::DWARFContext::getDIEsForAddress(), and isVariableIndexable().
getFirstChild()
DWARFDie DWARFDie::getFirstChild () const
Get the first child of this DIE object.
Returns
a valid DWARFDie instance if this object has children or an invalid DWARFDie instance if it doesn't.
Definition at line 654 of file DWARFDie.cpp.
References DWARFDie(), getFirstChild(), and isValid().
Referenced by begin(), dump(), getFirstChild(), and llvm::DWARFUnit::updateAddressDieMap().
getFullName()
void DWARFDie::getFullName (raw_string_ostream & OS, std::string * OriginalFullName = nullptr) const
Definition at line 233 of file DWARFDie.cpp.
References llvm::dumpTypeUnqualifiedName(), getShortName(), getTag(), and OS.
getHighPC()
std::optional< uint64_t > DWARFDie::getHighPC (uint64_t LowPC) const
Get the DW_AT_high_pc attribute value as an address.
In DWARF version 4 and later the high PC can be encoded as an offset from the DW_AT_low_pc. This function takes care of extracting the value as an address or offset and adds it to the low PC if needed and returns the value as an optional in case the DIE doesn't have a DW_AT_high_pc attribute.
Parameters
LowPC the low PC that might be needed to calculate the high PC.
Returns
an optional address value for the attribute.
Definition at line 345 of file DWARFDie.cpp.
References llvm::Address, llvm::dwarf::computeTombstoneAddress(), find(), and llvm::Offset.
Referenced by getLowAndHighPC().
getLastChild()
DWARFDie DWARFDie::getLastChild () const
Get the last child of this DIE object.
Returns
a valid null DWARFDie instance if this object has children or an invalid DWARFDie instance if it doesn't.
Definition at line 660 of file DWARFDie.cpp.
References DWARFDie(), getLastChild(), and isValid().
Referenced by end(), and getLastChild().
getLinkageName()
const char * DWARFDie::getLinkageName () const
Return the DIE linkage name resolving DW_AT_specification or DW_AT_abstract_origin references if necessary.
Returns null if no name is found.
Definition at line 462 of file DWARFDie.cpp.
References findRecursively(), isValid(), and llvm::dwarf::toString().
Referenced by getName(), getQualifiedNameIndex(), and llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::save().
getLocations()
Expected< DWARFLocationExpressionsVector > DWARFDie::getLocations (dwarf::Attribute Attr) const
Definition at line 408 of file DWARFDie.cpp.
References llvm::dwarf::AttributeString(), llvm::createStringError(), llvm::StringRef::data(), find(), llvm::dwarf::FormEncodingString(), llvm::inconvertibleErrorCode(), llvm::Offset, and llvm::to_vector().
Referenced by isVariableIndexable(), and llvm::DWARFUnit::updateVariableDieMap().
getLocBaseAttribute()
std::optional< uint64_t > DWARFDie::getLocBaseAttribute () const
Definition at line 341 of file DWARFDie.cpp.
References find(), and llvm::dwarf::toSectionOffset().
getLowAndHighPC()
bool DWARFDie::getLowAndHighPC (uint64_t & LowPC, uint64_t & HighPC, uint64_t & SectionIndex) const
Retrieves DW_AT_low_pc and DW_AT_high_pc from CU.
Returns true if both attributes are present.
Definition at line 362 of file DWARFDie.cpp.
References F, find(), getHighPC(), and llvm::dwarf::toSectionedAddress().
Referenced by dumpAttribute(), and getAddressRanges().
getName()
const char * DWARFDie::getName (DINameKind Kind) const
Return the DIE name resolving DW_AT_specification or DW_AT_abstract_origin references if necessary.
For the LinkageName case it additionaly searches for ShortName if LinkageName is not found. Returns null if no name is found.
Definition at line 444 of file DWARFDie.cpp.
References getLinkageName(), getShortName(), isValid(), llvm::LinkageName, Name, and llvm::None.
Referenced by llvm::dwarf_linker::parallel::CompileUnit::CompileUnit(), llvm::DWARFTypeUnit::dump(), dumpAttribute(), getQualifiedNameIndex(), getSubroutineName(), and hashFullyQualifiedName().
getOffset()
uint64_t llvm::DWARFDie::getOffset () const inline
Get the absolute offset into the debug info or types section.
Returns
the DIE offset or -1U if invalid.
Definition at line 66 of file DWARFDie.h.
References assert(), llvm::DWARFDebugInfoEntry::getOffset(), and isValid().
Referenced by llvm::dwarf_linker::parallel::DIEAttributeCloner::clone(), convertFunctionLineTable(), dump(), find(), find(), and parseInlineInfo().
getParent()
DWARFDie DWARFDie::getParent () const
Get the parent of this DIE object.
Returns
a valid DWARFDie instance if this object has a parent or an invalid DWARFDie instance if it doesn't.
Definition at line 636 of file DWARFDie.cpp.
References DWARFDie(), getParent(), and isValid().
Referenced by llvm::DWARFTypePrinter::appendScopes(), dump(), dumpParentChain(), llvm::DWARFUnit::getInlinedChainForAddress(), getParent(), GetParentDeclContextDIE(), and hashFullyQualifiedName().
getPreviousSibling()
DWARFDie DWARFDie::getPreviousSibling () const
Get the previous sibling of this DIE object.
Returns
a valid DWARFDie instance if this object has a sibling or an invalid DWARFDie instance if it doesn't.
Definition at line 648 of file DWARFDie.cpp.
References DWARFDie(), getPreviousSibling(), and isValid().
Referenced by getPreviousSibling(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator++(), llvm::DWARFDie::iterator::operator--(), and std::reverse_iterator< llvm::DWARFDie::iterator >::reverse_iterator().
getRangesBaseAttribute()
std::optional< uint64_t > DWARFDie::getRangesBaseAttribute () const
Extract the range base attribute from this DIE as absolute section offset.
This is a utility function that checks for either the DW_AT_rnglists_base or DW_AT_GNU_ranges_base attribute.
Returns
anm optional absolute section offset value for the attribute.
Definition at line 337 of file DWARFDie.cpp.
References find(), and llvm::dwarf::toSectionOffset().
getShortName()
const char * DWARFDie::getShortName () const
Return the DIE short name resolving DW_AT_specification or DW_AT_abstract_origin references if necessary.
Returns null if no name is found.
Definition at line 455 of file DWARFDie.cpp.
References findRecursively(), isValid(), and llvm::dwarf::toString().
Referenced by getFullName(), getName(), and llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::save().
getSibling()
DWARFDie DWARFDie::getSibling () const
Get the sibling of this DIE object.
Returns
a valid DWARFDie instance if this object has a sibling or an invalid DWARFDie instance if it doesn't.
Definition at line 642 of file DWARFDie.cpp.
References DWARFDie(), getSibling(), and isValid().
Referenced by std::reverse_iterator< llvm::DWARFDie::iterator >::base(), dump(), getSibling(), llvm::DWARFDie::iterator::operator++(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator--(), and llvm::DWARFUnit::updateAddressDieMap().
getSubroutineName()
const char * DWARFDie::getSubroutineName (DINameKind Kind) const
If a DIE represents a subprogram (or inlined subroutine), returns its mangled name (or short name, if mangled is missing).
This name may be fetched from specification or abstract origin for this subprogram. Returns null if no name is found.
Definition at line 438 of file DWARFDie.cpp.
References getName(), and isSubroutineDIE().
Referenced by llvm::DWARFContext::getInliningInfoForAddress().
getTag()
dwarf::Tag llvm::DWARFDie::getTag () const inline
Definition at line 71 of file DWARFDie.h.
References getAbbreviationDeclarationPtr().
Referenced by llvm::analyzeContextInfo(), llvm::DWARFTypePrinter::appendUnqualifiedNameAfter(), llvm::dwarf_linker::classic::CompileUnit::createOutputDIE(), dump(), getFullName(), llvm::DWARFUnit::getInlinedChainForAddress(), GetParentDeclContextDIE(), llvm::dwarf_linker::classic::CompileUnit::getTag(), getTypeSizeImpl(), hashFullyQualifiedName(), hasInlineInfo(), llvm::isODRCanonicalCandidate(), isSubprogramDIE(), isSubroutineDIE(), parseInlineInfo(), llvm::updateChildIncompleteness(), llvm::updatePruning(), llvm::updateRefIncompleteness(), and llvm::DWARFUnit::updateVariableDieMap().
getTypeSize()
std::optional< uint64_t > DWARFDie::getTypeSize (uint64_t PointerSize)
Gets the type size (in bytes) for this DIE.
Parameters
PointerSize the pointer size of the containing CU.
Returns
if this is a type DIE, or this DIE contains a DW_AT_type, returns the size of the type.
Definition at line 559 of file DWARFDie.cpp.
References getTypeSizeImpl().
Referenced by llvm::DWARFUnit::updateVariableDieMap().
hasChildren()
bool llvm::DWARFDie::hasChildren () const inline
Definition at line 78 of file DWARFDie.h.
References assert(), llvm::DWARFDebugInfoEntry::hasChildren(), and isValid().
isNULL()
bool llvm::DWARFDie::isNULL () const inline
Returns true for a valid DIE that terminates a sibling chain.
Definition at line 84 of file DWARFDie.h.
References getAbbreviationDeclarationPtr().
Referenced by getAddressRanges(), and std::reverse_iterator< llvm::DWARFDie::iterator >::operator--().
isSubprogramDIE()
bool DWARFDie::isSubprogramDIE () const
Returns true if DIE represents a subprogram (not inlined).
Definition at line 243 of file DWARFDie.cpp.
References getTag().
Referenced by llvm::DWARFUnit::getInlinedChainForAddress().
isSubroutineDIE()
bool DWARFDie::isSubroutineDIE () const
Returns true if DIE represents a subprogram or an inlined subroutine.
Definition at line 245 of file DWARFDie.cpp.
References getTag().
Referenced by getSubroutineName(), and llvm::DWARFUnit::updateAddressDieMap().
isValid()
bool llvm::DWARFDie::isValid () const inline
Definition at line 50 of file DWARFDie.h.
Referenced by llvm::DWARFTypePrinter::appendConstVolatileQualifierAfter(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmit(), llvm::logicalview::LVDWARFReader::createScopes(), dump(), dumpAttribute(), find(), find(), findRecursively(), getAbbreviationDeclarationPtr(), getFirstChild(), getLastChild(), getLinkageName(), llvm::DWARFContext::getLocalsForAddress(), getName(), getOffset(), getParent(), getPreviousSibling(), getShortName(), getSibling(), hasChildren(), hashFullyQualifiedName(), operator bool(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator*(), and llvm::dwarf_linker::parallel::DependencyTracker::verifyKeepChain().
operator bool()
llvm::DWARFDie::operator bool () const inline explicit
Definition at line 51 of file DWARFDie.h.
References isValid().
rbegin()
std::reverse_iterator< DWARFDie::iterator > llvm::DWARFDie::rbegin () const inline
Definition at line 471 of file DWARFDie.h.
References end().
rend()
std::reverse_iterator< DWARFDie::iterator > llvm::DWARFDie::rend () const inline
Definition at line 475 of file DWARFDie.h.
References begin().
resolveTypeUnitReference()
DWARFDie DWARFDie::resolveTypeUnitReference () const
Definition at line 326 of file DWARFDie.cpp.
References find(), llvm::DWARFUnit::getContext(), and llvm::DWARFContext::getTypeUnitForHash().
Referenced by llvm::resolveReferencedType(), llvm::resolveReferencedType(), and resolveReferencedType().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDie.h
lib/DebugInfo/DWARF/DWARFDie.cpp