LLVM: llvm::logicalview::LVRangeEntry Class Reference
llvm::logicalview::LVRangeEntry Class Reference final
#include "llvm/DebugInfo/LogicalView/Core/LVRange.h"
Public Types
using RangeType = LVAddress
Public Member Functions
LVRangeEntry ()=delete
LVRangeEntry (LVAddress LowerAddress, LVAddress UpperAddress, LVScope *Scope)
RangeType lower () const
RangeType upper () const
LVAddressRange addressRange () const
LVScope * scope () const
Detailed Description
Definition at line 25 of file LVRange.h.
Member Typedef Documentation
RangeType
using llvm::logicalview::LVRangeEntry::RangeType = LVAddress
Definition at line 31 of file LVRange.h.
Constructor & Destructor Documentation
LVRangeEntry() [1/2]
llvm::logicalview::LVRangeEntry::LVRangeEntry () delete
LVRangeEntry() [2/2]
llvm::logicalview::LVRangeEntry::LVRangeEntry (LVAddress LowerAddress, LVAddress UpperAddress, LVScope * Scope) inline
Definition at line 34 of file LVRange.h.
References llvm::Upper.
Member Function Documentation
addressRange()
LVAddressRange llvm::logicalview::LVRangeEntry::addressRange () const inline
Definition at line 39 of file LVRange.h.
References lower(), and upper().
lower()
RangeType llvm::logicalview::LVRangeEntry::lower () const inline
Definition at line 37 of file LVRange.h.
Referenced by addressRange(), and llvm::logicalview::LVRange::sort().
scope()
LVScope * llvm::logicalview::LVRangeEntry::scope () const inline
Definition at line 42 of file LVRange.h.
upper()
RangeType llvm::logicalview::LVRangeEntry::upper () const inline
Definition at line 38 of file LVRange.h.
References llvm::Upper.
Referenced by addressRange(), and llvm::logicalview::LVRange::sort().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/LogicalView/Core/LVRange.h