LLVM: llvm::detail::UniqueFunctionBase< ReturnT, ParamTs > Class Template Reference
llvm::detail::UniqueFunctionBase< ReturnT, ParamTs > Class Template Reference
#include "llvm/ADT/FunctionExtras.h"
Classes
struct AdjustedParamTBase
struct AdjustedParamTBase< T & >
struct AdjustedParamTBase< T && >
struct CallbacksHolder
struct CallbacksHolder< CallableT, CalledAs, EnableIfTrivial< CallableT > >
struct CalledAs
struct enable_if_t< sizeof(T)<=2 *sizeof(void *)> >
struct IsSizeLessThanThresholdT
struct NonTrivialCallbacks
A struct we use to aggregate three callbacks when we need full set of operations.
union StorageUnionT
struct TrivialCallback
A struct to hold a single trivial callback with sufficient alignment for our bitpacking.
Public Member Functions
operator bool () const
Protected Types
template<typename T >
using AdjustedParamT = typename AdjustedParamTBase<T>::type
using CallPtrT
using MovePtrT = void (*)(void *LHSCallableAddr, void *RHSCallableAddr)
using DestroyPtrT = void (*)(void *CallableAddr)
using CallbackPointerUnionT
Protected Member Functions
bool isInlineStorage () const
bool isTrivialCallback () const
CallPtrT getTrivialCallback () const
NonTrivialCallbacks * getNonTrivialCallbacks () const
CallPtrT getCallPtr () const
void * getCalleePtr () const
void * getInlineStorage () const
void * getOutOfLineStorage () const
size_t getOutOfLineStorageSize () const
size_t getOutOfLineStorageAlignment () const
void setOutOfLineStorage (void *Ptr, size_t Size, size_t Alignment)
template<typename CallableT , typename CalledAsT >
UniqueFunctionBase (CallableT Callable, CalledAs< CalledAsT >)
~UniqueFunctionBase ()
UniqueFunctionBase (UniqueFunctionBase &&RHS) noexcept
UniqueFunctionBase & operator= (UniqueFunctionBase &&RHS) noexcept
UniqueFunctionBase ()=default
Static Protected Member Functions
template<typename CalledAsT >
static ReturnT CallImpl (void *CallableAddr, AdjustedParamT< ParamTs >... Params)
template<typename CallableT >
static void MoveImpl (void *LHSCallableAddr, void *RHSCallableAddr) noexcept
template<typename CallableT >
static void DestroyImpl (void *CallableAddr) noexcept
Protected Attributes
union llvm::detail::UniqueFunctionBase::StorageUnionT StorageUnion
PointerIntPair< CallbackPointerUnionT, 1, bool > CallbackAndInlineFlag
Static Protected Attributes
static constexpr size_t InlineStorageSize = sizeof(void *) * 3
Detailed Description
template<typename ReturnT, typename... ParamTs>
class llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >
Definition at line 80 of file FunctionExtras.h.
Member Typedef Documentation
AdjustedParamT
template<typename ReturnT , typename... ParamTs> template<typename T > using llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::AdjustedParamT = typename AdjustedParamTBase<T>::type protected
Definition at line 117 of file FunctionExtras.h.
CallbackPointerUnionT
template<typename ReturnT , typename... ParamTs> using llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::CallbackPointerUnionT protected
Initial value:
      PointerUnion<TrivialCallback *, NonTrivialCallbacks *>
Definition at line 143 of file FunctionExtras.h.
CallPtrT
template<typename ReturnT , typename... ParamTs> using llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::CallPtrT protected
Initial value:
 ReturnT (*)(void *CallableAddr,
                               AdjustedParamT<ParamTs>... Params)
Definition at line 121 of file FunctionExtras.h.
DestroyPtrT
template<typename ReturnT , typename... ParamTs> using llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::DestroyPtrT = void (*)(void *CallableAddr) protected
Definition at line 124 of file FunctionExtras.h.
MovePtrT
template<typename ReturnT , typename... ParamTs> using llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::MovePtrT = void (*)(void *LHSCallableAddr, void *RHSCallableAddr) protected
Definition at line 123 of file FunctionExtras.h.
Constructor & Destructor Documentation
UniqueFunctionBase() [1/3]
template<typename ReturnT , typename... ParamTs> template<typename CallableT , typename CalledAsT > llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase (CallableT Callable, CalledAs< CalledAsT >) inline protected
Definition at line 261 of file FunctionExtras.h.
References llvm::allocate_buffer(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::CallbackAndInlineFlag, llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getInlineStorage(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnionT::InlineStorage, llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::InlineStorageSize, llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::setOutOfLineStorage(), Size, and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnion.
~UniqueFunctionBase()
template<typename ReturnT , typename... ParamTs> llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::~UniqueFunctionBase () inline protected
Definition at line 281 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::CallbackAndInlineFlag, llvm::deallocate_buffer(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::NonTrivialCallbacks::DestroyPtr, llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getInlineStorage(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getNonTrivialCallbacks(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getOutOfLineStorage(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getOutOfLineStorageAlignment(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getOutOfLineStorageSize(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::isInlineStorage(), and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::isTrivialCallback().
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::operator=().
UniqueFunctionBase() [2/3]
template<typename ReturnT , typename... ParamTs> llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase (UniqueFunctionBase< ReturnT, ParamTs > && RHS) inline protected noexcept
Definition at line 297 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::CallbackAndInlineFlag, llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getInlineStorage(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getNonTrivialCallbacks(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::InlineStorageSize, llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::isInlineStorage(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::isTrivialCallback(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::NonTrivialCallbacks::MovePtr, llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnionT::OutOfLineStorage, and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnion.
UniqueFunctionBase() [3/3]
template<typename ReturnT , typename... ParamTs> llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase () protected default
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::operator=().
Member Function Documentation
CallImpl()
template<typename ReturnT , typename... ParamTs> template<typename CalledAsT > static ReturnT llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::CallImpl (void * CallableAddr, AdjustedParamT< ParamTs >... Params) inline static protected
Definition at line 217 of file FunctionExtras.h.
DestroyImpl()
template<typename ReturnT , typename... ParamTs> template<typename CallableT > static void llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::DestroyImpl (void * CallableAddr) inline static protected noexcept
Definition at line 230 of file FunctionExtras.h.
getCalleePtr()
template<typename ReturnT , typename... ParamTs> void * llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getCalleePtr () const inline protected
Definition at line 197 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getInlineStorage(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getOutOfLineStorage(), and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::isInlineStorage().
getCallPtr()
template<typename ReturnT , typename... ParamTs> CallPtrT llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getCallPtr () const inline protected
Definition at line 186 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::NonTrivialCallbacks::CallPtr, llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getNonTrivialCallbacks(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getTrivialCallback(), and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::isTrivialCallback().
getInlineStorage()
template<typename ReturnT , typename... ParamTs> void * llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getInlineStorage () const inline protected
Definition at line 200 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnionT::InlineStorage, and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnion.
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getCalleePtr(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase(), and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::~UniqueFunctionBase().
getNonTrivialCallbacks()
template<typename ReturnT , typename... ParamTs> NonTrivialCallbacks * llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getNonTrivialCallbacks () const inline protected
Definition at line 182 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::CallbackAndInlineFlag, and llvm::cast().
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getCallPtr(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase(), and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::~UniqueFunctionBase().
getOutOfLineStorage()
template<typename ReturnT , typename... ParamTs> void * llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getOutOfLineStorage () const inline protected
Definition at line 201 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnionT::OutOfLineStorage, llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnionT::OutOfLineStorageT::StoragePtr, and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnion.
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getCalleePtr(), and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::~UniqueFunctionBase().
getOutOfLineStorageAlignment()
template<typename ReturnT , typename... ParamTs> size_t llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getOutOfLineStorageAlignment () const inline protected
Definition at line 208 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnionT::OutOfLineStorageT::Alignment, llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnionT::OutOfLineStorage, and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnion.
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::~UniqueFunctionBase().
getOutOfLineStorageSize()
template<typename ReturnT , typename... ParamTs> size_t llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getOutOfLineStorageSize () const inline protected
Definition at line 205 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnionT::OutOfLineStorage, llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnionT::OutOfLineStorageT::Size, and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnion.
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::~UniqueFunctionBase().
getTrivialCallback()
template<typename ReturnT , typename... ParamTs> CallPtrT llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getTrivialCallback () const inline protected
Definition at line 178 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::CallbackAndInlineFlag, and llvm::cast().
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getCallPtr().
isInlineStorage()
template<typename ReturnT , typename... ParamTs> bool llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::isInlineStorage () const inline protected
Definition at line 172 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::CallbackAndInlineFlag.
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getCalleePtr(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase(), and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::~UniqueFunctionBase().
isTrivialCallback()
template<typename ReturnT , typename... ParamTs> bool llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::isTrivialCallback () const inline protected
Definition at line 174 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::CallbackAndInlineFlag, and llvm::isa().
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getCallPtr(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase(), and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::~UniqueFunctionBase().
MoveImpl()
template<typename ReturnT , typename... ParamTs> template<typename CallableT > static void llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::MoveImpl (void * LHSCallableAddr, void * RHSCallableAddr) inline static protected noexcept
Definition at line 224 of file FunctionExtras.h.
operator bool()
template<typename ReturnT , typename... ParamTs> llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::operator bool () const inline explicit
Definition at line 343 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::CallbackAndInlineFlag.
operator=()
template<typename ReturnT , typename... ParamTs> UniqueFunctionBase & llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::operator= (UniqueFunctionBase< ReturnT, ParamTs > && RHS) inline protected noexcept
Definition at line 328 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase(), and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::~UniqueFunctionBase().
setOutOfLineStorage()
template<typename ReturnT , typename... ParamTs> void llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::setOutOfLineStorage (void * Ptr, size_t Size, size_t Alignment) inline protected
Definition at line 212 of file FunctionExtras.h.
References llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnionT::OutOfLineStorage, Ptr, Size, and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnion.
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase().
Member Data Documentation
CallbackAndInlineFlag
template<typename ReturnT , typename... ParamTs> PointerIntPair<CallbackPointerUnionT, 1, bool> llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::CallbackAndInlineFlag protected
Definition at line 170 of file FunctionExtras.h.
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getNonTrivialCallbacks(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getTrivialCallback(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::isInlineStorage(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::isTrivialCallback(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::operator bool(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase(), and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::~UniqueFunctionBase().
InlineStorageSize
template<typename ReturnT , typename... ParamTs> size_t llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::InlineStorageSize = sizeof(void *) * 3 static constexpr protected
Definition at line 82 of file FunctionExtras.h.
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase(), and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase().
StorageUnion
template<typename ReturnT , typename... ParamTs> union llvm::detail::UniqueFunctionBase::StorageUnionT llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::StorageUnion protected
Referenced by llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getInlineStorage(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getOutOfLineStorage(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getOutOfLineStorageAlignment(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::getOutOfLineStorageSize(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::setOutOfLineStorage(), llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase(), and llvm::detail::UniqueFunctionBase< ReturnT, ParamTs >::UniqueFunctionBase().
The documentation for this class was generated from the following file:
include/llvm/ADT/FunctionExtras.h