LLVM: llvm::object::DiceRef Class Reference
llvm::object::DiceRef Class Reference
DiceRef - This is a value type class that represents a single data in code entry in the table in a Mach-O object file.
#include "llvm/Object/MachO.h"
Public Member Functions
DiceRef ()=default
DiceRef (DataRefImpl DiceP, const ObjectFile *Owner)
DiceRef.
bool operator== (const DiceRef &Other) const
bool operator< (const DiceRef &Other) const
void moveNext ()
std::error_code getOffset (uint32_t &Result) const
std::error_code getLength (uint16_t &Result) const
std::error_code getKind (uint16_t &Result) const
DataRefImpl getRawDataRefImpl () const
const ObjectFile * getObjectFile () const
Detailed Description
DiceRef - This is a value type class that represents a single data in code entry in the table in a Mach-O object file.
Definition at line 44 of file MachO.h.
Constructor & Destructor Documentation
DiceRef() [1/2]
llvm::object::DiceRef::DiceRef () default
DiceRef() [2/2]
llvm::object::DiceRef::DiceRef (DataRefImpl DiceP, const ObjectFile * Owner) inline
DiceRef.
Definition at line 876 of file MachO.h.
Member Function Documentation
getKind()
std::error_code llvm::object::DiceRef::getKind (uint16_t & Result) const inline
Definition at line 913 of file MachO.h.
References llvm::object::MachOObjectFile::getDice(), and llvm::MachO::data_in_code_entry::kind.
getLength()
std::error_code llvm::object::DiceRef::getLength (uint16_t & Result) const inline
Definition at line 905 of file MachO.h.
References llvm::object::MachOObjectFile::getDice(), and llvm::MachO::data_in_code_entry::length.
getObjectFile()
const ObjectFile * llvm::object::DiceRef::getObjectFile () const inline
Definition at line 925 of file MachO.h.
getOffset()
std::error_code llvm::object::DiceRef::getOffset (uint32_t & Result) const inline
Definition at line 897 of file MachO.h.
References llvm::object::MachOObjectFile::getDice(), and llvm::MachO::data_in_code_entry::offset.
getRawDataRefImpl()
DataRefImpl llvm::object::DiceRef::getRawDataRefImpl () const inline
Definition at line 921 of file MachO.h.
moveNext()
void llvm::object::DiceRef::moveNext () inline
Definition at line 887 of file MachO.h.
References P, and llvm::object::DataRefImpl::p.
operator<()
bool llvm::object::DiceRef::operator< (const DiceRef & Other) const inline
Definition at line 883 of file MachO.h.
References llvm::Other.
operator==()
bool llvm::object::DiceRef::operator== (const DiceRef & Other) const inline
Definition at line 879 of file MachO.h.
References llvm::Other.
The documentation for this class was generated from the following file:
include/llvm/Object/MachO.h