LLVM: llvm::IndexedMemProfReader Class Reference
llvm::IndexedMemProfReader Class Reference
#include "llvm/ProfileData/InstrProfReader.h"
Public Member Functions
IndexedMemProfReader ()=default
Error deserialize (const unsigned char *Start, uint64_t MemProfOffset)
Expected< memprof::MemProfRecord > getMemProfRecord (const uint64_t FuncNameHash) const
Detailed Description
Definition at line 650 of file InstrProfReader.h.
Constructor & Destructor Documentation
IndexedMemProfReader()
llvm::IndexedMemProfReader::IndexedMemProfReader () default
Member Function Documentation
deserialize()
Error IndexedMemProfReader::deserialize (const unsigned char * Start, uint64_t MemProfOffset)
Definition at line 1287 of file InstrProfReader.cpp.
References E, llvm::formatv(), llvm::make_error(), llvm::memprof::MaximumSupportedVersion, llvm::memprof::MinimumSupportedVersion, Ptr, llvm::support::endian::readNext(), llvm::Error::success(), llvm::unsupported_version, llvm::memprof::Version0, llvm::memprof::Version1, llvm::memprof::Version2, and llvm::memprof::Version3.
Referenced by llvm::IndexedInstrProfReader::readHeader().
getMemProfRecord()
Expected< memprof::MemProfRecord > IndexedMemProfReader::getMemProfRecord (const uint64_t FuncNameHash) const
Definition at line 1600 of file InstrProfReader.cpp.
References assert(), llvm::formatv(), getMemProfRecordV0(), getMemProfRecordV2(), getMemProfRecordV3(), llvm::invalid_prof, llvm::make_error(), llvm::memprof::MaximumSupportedVersion, llvm::memprof::MinimumSupportedVersion, llvm::unknown_function, llvm::unsupported_version, llvm::memprof::Version0, llvm::memprof::Version1, llvm::memprof::Version2, and llvm::memprof::Version3.
Referenced by llvm::IndexedInstrProfReader::getMemProfRecord().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/InstrProfReader.h
lib/ProfileData/InstrProfReader.cpp