LLVM: llvm::pdb::PDBFile Class Reference
llvm::pdb::PDBFile Class Reference
#include "llvm/DebugInfo/PDB/Native/PDBFile.h"
Public Member Functions
PDBFile (StringRef Path, std::unique_ptr< BinaryStream > PdbFileBuffer, BumpPtrAllocator &Allocator)
~PDBFile () override
StringRef getFileDirectory () const
StringRef getFilePath () const
uint32_t getFreeBlockMapBlock () const
uint32_t getUnknown1 () const
uint32_t getBlockSize () const override
uint32_t getBlockCount () const override
uint32_t getNumDirectoryBytes () const
uint32_t getBlockMapIndex () const
uint32_t getNumDirectoryBlocks () const
uint64_t getBlockMapOffset () const
uint32_t getNumStreams () const override
uint32_t getMaxStreamSize () const
uint32_t getStreamByteSize (uint32_t StreamIndex) const override
ArrayRef< support::ulittle32_t > getStreamBlockList (uint32_t StreamIndex) const override
uint64_t getFileSize () const
Expected< ArrayRef< uint8_t > > getBlockData (uint32_t BlockIndex, uint32_t NumBytes) const override
Error setBlockData (uint32_t BlockIndex, uint32_t Offset, ArrayRef< uint8_t > Data) const override
ArrayRef< support::ulittle32_t > getStreamSizes () const
ArrayRef< ArrayRef< support::ulittle32_t > > getStreamMap () const
const msf::MSFLayout & getMsfLayout () const
BinaryStreamRef getMsfBuffer () const
ArrayRef< support::ulittle32_t > getDirectoryBlockArray () const
std::unique_ptr< msf::MappedBlockStream > createIndexedStream (uint16_t SN) const
Expected< std::unique_ptr< msf::MappedBlockStream > > safelyCreateIndexedStream (uint32_t StreamIndex) const
Wrapper around MappedBlockStream::createIndexedStream() that checks if a stream with that index actually exists.
Expected< std::unique_ptr< msf::MappedBlockStream > > safelyCreateNamedStream (StringRef Name)
msf::MSFStreamLayout getStreamLayout (uint32_t StreamIdx) const
msf::MSFStreamLayout getFpmStreamLayout () const
Error parseFileHeaders ()
Error parseStreamData ()
Expected< InfoStream & > getPDBInfoStream ()
Expected< DbiStream & > getPDBDbiStream ()
Expected< GlobalsStream & > getPDBGlobalsStream ()
Expected< TpiStream & > getPDBTpiStream ()
Expected< TpiStream & > getPDBIpiStream ()
Expected< PublicsStream & > getPDBPublicsStream ()
Expected< SymbolStream & > getPDBSymbolStream ()
Expected< PDBStringTable & > getStringTable ()
Expected< InjectedSourceStream & > getInjectedSourceStream ()
BumpPtrAllocator & getAllocator ()
bool hasPDBDbiStream () const
bool hasPDBGlobalsStream ()
bool hasPDBInfoStream () const
bool hasPDBIpiStream () const
bool hasPDBPublicsStream ()
bool hasPDBSymbolStream ()
bool hasPDBTpiStream () const
bool hasPDBStringTable ()
bool hasPDBInjectedSourceStream ()
uint32_t getPointerSize ()
Public Member Functions inherited from llvm::msf::IMSFFile
virtual ~IMSFFile ()=default
Detailed Description
Definition at line 40 of file PDBFile.h.
Constructor & Destructor Documentation
PDBFile()
PDBFile::PDBFile (StringRef Path, std::unique_ptr< BinaryStream > PdbFileBuffer, BumpPtrAllocator & Allocator)
Definition at line 41 of file PDBFile.cpp.
~PDBFile()
PDBFile::~PDBFile () override default
Member Function Documentation
createIndexedStream()
std::unique_ptr< MappedBlockStream > PDBFile::createIndexedStream (uint16_t SN) const
Definition at line 237 of file PDBFile.cpp.
References llvm::msf::MappedBlockStream::createIndexedStream(), and llvm::pdb::kInvalidStreamIndex.
Referenced by safelyCreateIndexedStream().
getAllocator()
BumpPtrAllocator & llvm::pdb::PDBFile::getAllocator () inline
Definition at line 108 of file PDBFile.h.
getBlockCount()
uint32_t PDBFile::getBlockCount () const override virtual
Implements llvm::msf::IMSFFile.
Definition at line 60 of file PDBFile.cpp.
References llvm::msf::SuperBlock::NumBlocks, and llvm::msf::MSFLayout::SB.
Referenced by parseFileHeaders().
getBlockData()
Expected< ArrayRef< uint8_t > > PDBFile::getBlockData (uint32_t BlockIndex, uint32_t NumBytes) const override virtual
Implements llvm::msf::IMSFFile.
Definition at line 103 of file PDBFile.cpp.
References llvm::msf::blockToOffset(), llvm::codeview::EC, and getBlockSize().
getBlockMapIndex()
uint32_t PDBFile::getBlockMapIndex () const
Definition at line 68 of file PDBFile.cpp.
References llvm::msf::SuperBlock::BlockMapAddr, and llvm::msf::MSFLayout::SB.
getBlockMapOffset()
uint64_t PDBFile::getBlockMapOffset () const
Definition at line 79 of file PDBFile.cpp.
References llvm::msf::SuperBlock::BlockMapAddr, llvm::msf::SuperBlock::BlockSize, and llvm::msf::MSFLayout::SB.
Referenced by parseFileHeaders().
getBlockSize()
uint32_t PDBFile::getBlockSize () const override virtual
Implements llvm::msf::IMSFFile.
Definition at line 54 of file PDBFile.cpp.
References llvm::msf::SuperBlock::BlockSize, and llvm::msf::MSFLayout::SB.
Referenced by getBlockData().
getDirectoryBlockArray()
ArrayRef< support::ulittle32_t > PDBFile::getDirectoryBlockArray () const
Definition at line 232 of file PDBFile.cpp.
References llvm::msf::MSFLayout::DirectoryBlocks.
getFileDirectory()
StringRef PDBFile::getFileDirectory () const
Definition at line 50 of file PDBFile.cpp.
References llvm::sys::path::parent_path().
getFilePath()
StringRef PDBFile::getFilePath () const
Definition at line 48 of file PDBFile.cpp.
Referenced by llvm::pdb::InputFile::getFilePath(), and llvm::pdb::NativeExeSymbol::getSymbolsFileName().
getFileSize()
uint64_t PDBFile::getFileSize () const
Definition at line 101 of file PDBFile.cpp.
Referenced by parseStreamData().
getFpmStreamLayout()
msf::MSFStreamLayout PDBFile::getFpmStreamLayout () const
Definition at line 252 of file PDBFile.cpp.
References llvm::msf::getFpmStreamLayout().
getFreeBlockMapBlock()
uint32_t PDBFile::getFreeBlockMapBlock () const
Definition at line 56 of file PDBFile.cpp.
References llvm::msf::SuperBlock::FreeBlockMapBlock, and llvm::msf::MSFLayout::SB.
getInjectedSourceStream()
Expected< InjectedSourceStream & > PDBFile::getInjectedSourceStream ()
Definition at line 383 of file PDBFile.cpp.
References llvm::codeview::EC, getStringTable(), and safelyCreateNamedStream().
getMaxStreamSize()
uint32_t PDBFile::getMaxStreamSize () const
Definition at line 88 of file PDBFile.cpp.
References llvm::max_element(), and llvm::msf::MSFLayout::StreamSizes.
getMsfBuffer()
BinaryStreamRef llvm::pdb::PDBFile::getMsfBuffer () const inline
Definition at line 81 of file PDBFile.h.
getMsfLayout()
const msf::MSFLayout & llvm::pdb::PDBFile::getMsfLayout () const inline
Definition at line 80 of file PDBFile.h.
getNumDirectoryBlocks()
uint32_t PDBFile::getNumDirectoryBlocks () const
Definition at line 74 of file PDBFile.cpp.
References llvm::msf::SuperBlock::BlockSize, llvm::msf::bytesToBlocks(), llvm::msf::SuperBlock::NumDirectoryBytes, and llvm::msf::MSFLayout::SB.
Referenced by parseFileHeaders().
getNumDirectoryBytes()
uint32_t PDBFile::getNumDirectoryBytes () const
Definition at line 64 of file PDBFile.cpp.
References llvm::msf::SuperBlock::NumDirectoryBytes, and llvm::msf::MSFLayout::SB.
getNumStreams()
uint32_t PDBFile::getNumStreams () const override virtual
Implements llvm::msf::IMSFFile.
Definition at line 84 of file PDBFile.cpp.
References llvm::msf::MSFLayout::StreamSizes.
Referenced by hasPDBDbiStream(), hasPDBGlobalsStream(), hasPDBInfoStream(), hasPDBInjectedSourceStream(), hasPDBIpiStream(), hasPDBPublicsStream(), hasPDBStringTable(), hasPDBSymbolStream(), hasPDBTpiStream(), and safelyCreateIndexedStream().
getPDBDbiStream()
Expected< DbiStream & > PDBFile::getPDBDbiStream ()
Definition at line 287 of file PDBFile.cpp.
References llvm::codeview::EC, safelyCreateIndexedStream(), and llvm::pdb::StreamDBI.
Referenced by getDbiStreamPtr(), getPDBGlobalsStream(), getPDBPublicsStream(), getPDBSymbolStream(), getPointerSize(), llvm::pdb::NativeExeSymbol::hasCTypes(), hasPDBGlobalsStream(), hasPDBPublicsStream(), hasPDBSymbolStream(), and llvm::pdb::NativeExeSymbol::hasPrivateSymbols().
getPDBGlobalsStream()
Expected< GlobalsStream & > PDBFile::getPDBGlobalsStream ()
Definition at line 256 of file PDBFile.cpp.
References llvm::codeview::EC, getPDBDbiStream(), and safelyCreateIndexedStream().
Referenced by llvm::pdb::NativeEnumGlobals::NativeEnumGlobals().
getPDBInfoStream()
Expected< InfoStream & > PDBFile::getPDBInfoStream ()
Definition at line 274 of file PDBFile.cpp.
References llvm::codeview::EC, safelyCreateIndexedStream(), and llvm::pdb::StreamPDB.
Referenced by llvm::pdb::NativeExeSymbol::getAge(), llvm::pdb::NativeExeSymbol::getGuid(), hasPDBInjectedSourceStream(), hasPDBIpiStream(), hasPDBStringTable(), and safelyCreateNamedStream().
getPDBIpiStream()
Expected< TpiStream & > PDBFile::getPDBIpiStream ()
Definition at line 313 of file PDBFile.cpp.
References llvm::codeview::EC, hasPDBIpiStream(), llvm::make_error(), llvm::pdb::no_stream, safelyCreateIndexedStream(), and llvm::pdb::StreamIPI.
Referenced by llvm::pdb::NativeInlineSiteSymbol::getName().
getPDBPublicsStream()
Expected< PublicsStream & > PDBFile::getPDBPublicsStream ()
Definition at line 329 of file PDBFile.cpp.
References llvm::codeview::EC, getPDBDbiStream(), and safelyCreateIndexedStream().
getPDBSymbolStream()
Expected< SymbolStream & > PDBFile::getPDBSymbolStream ()
Definition at line 347 of file PDBFile.cpp.
References llvm::codeview::EC, getPDBDbiStream(), and safelyCreateIndexedStream().
Referenced by llvm::pdb::SymbolCache::getOrCreateGlobalSymbolByOffset(), and llvm::pdb::NativeEnumGlobals::NativeEnumGlobals().
getPDBTpiStream()
Expected< TpiStream & > PDBFile::getPDBTpiStream ()
Definition at line 300 of file PDBFile.cpp.
References llvm::codeview::EC, safelyCreateIndexedStream(), and llvm::pdb::StreamTPI.
Referenced by llvm::pdb::SymbolCache::createTypeEnumerator(), llvm::pdb::SymbolCache::findSymbolByTypeIndex(), and llvm::pdb::NativeInlineSiteSymbol::getName().
getPointerSize()
uint32_t PDBFile::getPointerSize ()
Definition at line 401 of file PDBFile.cpp.
References llvm::pdb::Amd64, getPDBDbiStream(), and Machine.
getStreamBlockList()
ArrayRef< support::ulittle32_t > PDBFile::getStreamBlockList (uint32_t StreamIndex) const override virtual
Implements llvm::msf::IMSFFile.
Definition at line 97 of file PDBFile.cpp.
References llvm::msf::MSFLayout::StreamMap.
Referenced by getStreamLayout().
getStreamByteSize()
uint32_t PDBFile::getStreamByteSize (uint32_t StreamIndex) const override virtual
Implements llvm::msf::IMSFFile.
Definition at line 92 of file PDBFile.cpp.
References llvm::msf::MSFLayout::StreamSizes.
Referenced by getStreamLayout(), hasPDBDbiStream(), and parseStreamData().
getStreamLayout()
MSFStreamLayout PDBFile::getStreamLayout (uint32_t StreamIdx) const
Definition at line 244 of file PDBFile.cpp.
References Blocks, getStreamBlockList(), and getStreamByteSize().
getStreamMap()
ArrayRef< ArrayRef< support::ulittle32_t > > llvm::pdb::PDBFile::getStreamMap () const inline
Definition at line 76 of file PDBFile.h.
References llvm::msf::MSFLayout::StreamMap.
getStreamSizes()
ArrayRef< support::ulittle32_t > llvm::pdb::PDBFile::getStreamSizes () const inline
Definition at line 73 of file PDBFile.h.
References llvm::msf::MSFLayout::StreamSizes.
getStringTable()
Expected< PDBStringTable & > PDBFile::getStringTable ()
Definition at line 366 of file PDBFile.cpp.
References assert(), llvm::BinaryStreamReader::bytesRemaining(), llvm::codeview::EC, N, and safelyCreateNamedStream().
Referenced by llvm::pdb::NativeSourceFile::getFileName(), and getInjectedSourceStream().
getUnknown1()
uint32_t PDBFile::getUnknown1 () const
Definition at line 72 of file PDBFile.cpp.
References llvm::msf::MSFLayout::SB, and llvm::msf::SuperBlock::Unknown1.
hasPDBDbiStream()
bool PDBFile::hasPDBDbiStream () const
Definition at line 411 of file PDBFile.cpp.
References getNumStreams(), getStreamByteSize(), and llvm::pdb::StreamDBI.
hasPDBGlobalsStream()
bool PDBFile::hasPDBGlobalsStream ()
Definition at line 415 of file PDBFile.cpp.
References llvm::consumeError(), getNumStreams(), and getPDBDbiStream().
hasPDBInfoStream()
bool PDBFile::hasPDBInfoStream () const
Definition at line 425 of file PDBFile.cpp.
References getNumStreams(), and llvm::pdb::StreamPDB.
Referenced by hasPDBIpiStream().
hasPDBInjectedSourceStream()
bool PDBFile::hasPDBInjectedSourceStream ()
Definition at line 469 of file PDBFile.cpp.
References assert(), llvm::consumeError(), getNumStreams(), getPDBInfoStream(), and llvm::Expected< T >::takeError().
hasPDBIpiStream()
bool PDBFile::hasPDBIpiStream () const
Definition at line 427 of file PDBFile.cpp.
References llvm::cantFail(), llvm::pdb::InfoStream::containsIdStream(), getNumStreams(), getPDBInfoStream(), hasPDBInfoStream(), and llvm::pdb::StreamIPI.
Referenced by getPDBIpiStream(), and llvm::pdb::InputFile::hasIds().
hasPDBPublicsStream()
bool PDBFile::hasPDBPublicsStream ()
Definition at line 438 of file PDBFile.cpp.
References llvm::consumeError(), getNumStreams(), and getPDBDbiStream().
hasPDBStringTable()
bool PDBFile::hasPDBStringTable ()
Definition at line 456 of file PDBFile.cpp.
References assert(), llvm::consumeError(), getNumStreams(), getPDBInfoStream(), and llvm::Expected< T >::takeError().
hasPDBSymbolStream()
bool PDBFile::hasPDBSymbolStream ()
Definition at line 447 of file PDBFile.cpp.
References getNumStreams(), and getPDBDbiStream().
hasPDBTpiStream()
bool PDBFile::hasPDBTpiStream () const
Definition at line 454 of file PDBFile.cpp.
References getNumStreams(), and llvm::pdb::StreamTPI.
Referenced by llvm::pdb::InputFile::hasTypes().
parseFileHeaders()
Error PDBFile::parseFileHeaders ()
Definition at line 119 of file PDBFile.cpp.
References llvm::msf::SuperBlock::BlockSize, llvm::codeview::Byte, llvm::BinaryStreamReader::bytesRemaining(), llvm::consumeError(), llvm::pdb::corrupt_file, llvm::msf::MappedBlockStream::createFpmStream(), llvm::msf::MSFLayout::DirectoryBlocks, llvm::codeview::EC, llvm::msf::MSFLayout::FreePageMap, getBlockCount(), getBlockMapOffset(), getNumDirectoryBlocks(), I, llvm::make_error(), llvm::msf::SuperBlock::NumBlocks, llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readBytes(), llvm::BinaryStreamReader::readObject(), llvm::BitVector::resize(), llvm::msf::MSFLayout::SB, llvm::BinaryStreamReader::setOffset(), llvm::Error::success(), and llvm::msf::validateSuperBlock().
parseStreamData()
Error PDBFile::parseStreamData ()
Definition at line 179 of file PDBFile.cpp.
References assert(), llvm::pdb::Block, Blocks, llvm::msf::SuperBlock::BlockSize, llvm::BinaryStreamReader::bytesRemaining(), llvm::msf::bytesToBlocks(), llvm::pdb::corrupt_file, llvm::msf::MappedBlockStream::createDirectoryStream(), llvm::codeview::EC, getFileSize(), getStreamByteSize(), I, llvm::make_error(), llvm::BinaryStreamReader::readArray(), llvm::BinaryStreamReader::readInteger(), llvm::msf::MSFLayout::SB, llvm::msf::MSFLayout::StreamMap, llvm::msf::MSFLayout::StreamSizes, and llvm::Error::success().
safelyCreateIndexedStream()
Expected< std::unique_ptr< MappedBlockStream > > PDBFile::safelyCreateIndexedStream (uint32_t StreamIndex) const
Wrapper around MappedBlockStream::createIndexedStream() that checks if a stream with that index actually exists.
If it does not, the return value will have an MSFError with code msf_error_code::no_stream. Else, the return value will contain the stream returned by createIndexedStream().
Definition at line 487 of file PDBFile.cpp.
References createIndexedStream(), getNumStreams(), llvm::make_error(), and llvm::pdb::no_stream.
Referenced by getPDBDbiStream(), getPDBGlobalsStream(), getPDBInfoStream(), getPDBIpiStream(), getPDBPublicsStream(), getPDBSymbolStream(), getPDBTpiStream(), llvm::pdb::TpiStream::reload(), and safelyCreateNamedStream().
safelyCreateNamedStream()
Expected< std::unique_ptr< MappedBlockStream > > PDBFile::safelyCreateNamedStream (StringRef Name)
Definition at line 495 of file PDBFile.cpp.
References getPDBInfoStream(), Name, safelyCreateIndexedStream(), and llvm::Expected< T >::takeError().
Referenced by getInjectedSourceStream(), and getStringTable().
setBlockData()
Error PDBFile::setBlockData (uint32_t BlockIndex, uint32_t Offset, ArrayRef< uint8_t > Data) const override virtual
Implements llvm::msf::IMSFFile.
Definition at line 113 of file PDBFile.cpp.
References llvm::make_error(), and llvm::pdb::not_writable.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/PDBFile.h
lib/DebugInfo/PDB/Native/PDBFile.cpp