LLVM: llvm::XtensaConstantPoolConstant Class Reference
llvm::XtensaConstantPoolConstant Class Reference
XtensaConstantPoolConstant - Xtensa-specific constant pool values for Constants (for example BlockAddresses).
#include "Target/Xtensa/XtensaConstantPoolValue.h"
Public Member Functions
const BlockAddress * getBlockAddress () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
bool hasSameValue (XtensaConstantPoolValue *ACPV) override
hasSameValue - Return true if this Xtensa constpool value can share the same constantpool entry as another Xtensa constpool value.
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const XtensaConstantPoolConstant *A) const
Public Member Functions inherited from llvm::XtensaConstantPoolValue
~XtensaConstantPoolValue () override
XtensaCP::XtensaCPModifier getModifier () const
bool hasModifier () const
StringRef getModifierText () const
unsigned getLabelId () const
void setLabelId (unsigned ID)
bool isExtSymbol () const
bool isBlockAddress () const
bool isMachineBasicBlock () const
bool isJumpTable () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
bool equals (const XtensaConstantPoolValue *A) const
void print (raw_ostream &O) const override
print - Implement operator<<
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
virtual unsigned getSizeInBytes (const DataLayout &DL) const
Static Public Member Functions
static XtensaConstantPoolConstant * Create (const Constant *C, unsigned ID, XtensaCP::XtensaCPKind Kind)
static bool classof (const XtensaConstantPoolValue *APV)
Additional Inherited Members
Protected Member Functions inherited from llvm::XtensaConstantPoolValue
XtensaConstantPoolValue (Type *Ty, unsigned ID, XtensaCP::XtensaCPKind Kind, XtensaCP::XtensaCPModifier Modifier=XtensaCP::no_modifier)
XtensaConstantPoolValue (LLVMContext &C, unsigned id, XtensaCP::XtensaCPKind Kind, XtensaCP::XtensaCPModifier Modifier=XtensaCP::no_modifier)
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, Align Alignment)
Detailed Description
XtensaConstantPoolConstant - Xtensa-specific constant pool values for Constants (for example BlockAddresses).
Definition at line 125 of file XtensaConstantPoolValue.h.
Member Function Documentation
addSelectionDAGCSEId()
void XtensaConstantPoolConstant::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 102 of file XtensaConstantPoolValue.cpp.
References llvm::XtensaConstantPoolValue::addSelectionDAGCSEId().
classof()
static bool llvm::XtensaConstantPoolConstant::classof (const XtensaConstantPoolValue * APV) inline static
Definition at line 147 of file XtensaConstantPoolValue.h.
References llvm::XtensaConstantPoolValue::isBlockAddress().
Create()
XtensaConstantPoolConstant * XtensaConstantPoolConstant::Create (const Constant * C, unsigned ID, XtensaCP::XtensaCPKind Kind) static
Definition at line 80 of file XtensaConstantPoolValue.cpp.
References llvm::CallingConv::C.
equals()
bool llvm::XtensaConstantPoolConstant::equals (const XtensaConstantPoolConstant * A) const inline
Definition at line 151 of file XtensaConstantPoolValue.h.
References A, and llvm::XtensaConstantPoolValue::equals().
getBlockAddress()
const BlockAddress * XtensaConstantPoolConstant::getBlockAddress () const
Definition at line 85 of file XtensaConstantPoolValue.cpp.
References llvm::dyn_cast_or_null().
getExistingMachineCPValue()
int XtensaConstantPoolConstant::getExistingMachineCPValue (MachineConstantPool * CP, Align Alignment) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 89 of file XtensaConstantPoolValue.cpp.
References llvm::XtensaConstantPoolValue::getExistingMachineCPValueImpl().
hasSameValue()
bool XtensaConstantPoolConstant::hasSameValue (XtensaConstantPoolValue * ACPV) override virtual
hasSameValue - Return true if this Xtensa constpool value can share the same constantpool entry as another Xtensa constpool value.
Reimplemented from llvm::XtensaConstantPoolValue.
Definition at line 95 of file XtensaConstantPoolValue.cpp.
References llvm::dyn_cast(), and llvm::XtensaConstantPoolValue::hasSameValue().
print()
void XtensaConstantPoolConstant::print (raw_ostream & O) const override virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Definition at line 107 of file XtensaConstantPoolValue.cpp.
References llvm::Value::getName(), and llvm::XtensaConstantPoolValue::print().
The documentation for this class was generated from the following files:
lib/Target/Xtensa/XtensaConstantPoolValue.h
lib/Target/Xtensa/XtensaConstantPoolValue.cpp