LLVM: llvm::DebuginfodCollection Class Reference
llvm::DebuginfodCollection Class Reference
Tracks a collection of debuginfod artifacts on the local filesystem.
#include "llvm/Debuginfod/Debuginfod.h"
Public Member Functions
DebuginfodCollection (ArrayRef< StringRef > Paths, DebuginfodLog &Log, ThreadPoolInterface &Pool, double MinInterval)
Error update ()
Error updateForever (std::chrono::milliseconds Interval)
Expected< std::string > findDebugBinaryPath (object::BuildIDRef)
Expected< std::string > findBinaryPath (object::BuildIDRef)
Detailed Description
Tracks a collection of debuginfod artifacts on the local filesystem.
Definition at line 124 of file Debuginfod.h.
Constructor & Destructor Documentation
DebuginfodCollection()
llvm::DebuginfodCollection::DebuginfodCollection (ArrayRef< StringRef > Paths, DebuginfodLog & Log, ThreadPoolInterface & Pool, double MinInterval)
Definition at line 350 of file Debuginfod.cpp.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Member Function Documentation
findBinaryPath()
Expected< std::string > llvm::DebuginfodCollection::findBinaryPath (object::BuildIDRef ID)
Definition at line 501 of file Debuginfod.cpp.
References llvm::consumeError(), findDebugBinaryPath(), llvm::getCachedOrDownloadExecutable(), and llvm::Expected< T >::takeError().
findDebugBinaryPath()
Expected< std::string > llvm::DebuginfodCollection::findDebugBinaryPath (object::BuildIDRef ID)
Definition at line 533 of file Debuginfod.cpp.
References llvm::getCachedOrDownloadDebuginfo(), and llvm::Expected< T >::takeError().
Referenced by llvm::DebuginfodServer::DebuginfodServer(), and findBinaryPath().
update()
Error llvm::DebuginfodCollection::update ()
Definition at line 359 of file Debuginfod.cpp.
References llvm::Timer::clear(), llvm::Timer::isRunning(), llvm::DebuginfodLog::push(), llvm::Timer::startTimer(), llvm::Timer::stopTimer(), and llvm::Error::success().
Referenced by updateForever().
updateForever()
Error llvm::DebuginfodCollection::updateForever (std::chrono::milliseconds Interval)
Definition at line 387 of file Debuginfod.cpp.
References llvm_unreachable, and update().
The documentation for this class was generated from the following files:
include/llvm/Debuginfod/Debuginfod.h
lib/Debuginfod/Debuginfod.cpp