LLVM: llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator Class Reference
llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator Class Reference
#include "llvm/ADT/EquivalenceClasses.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = const ElemTy
using size_type = std::size_t
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
member_iterator ()=default
member_iterator (const ECValue *N)
reference operator* () const
pointer operator-> () const
member_iterator & operator++ ()
member_iterator operator++ (int)
bool operator== (const member_iterator &RHS) const
bool operator!= (const member_iterator &RHS) const
Friends
class EquivalenceClasses
Detailed Description
template<class ElemTy, class Compare = std::less<ElemTy>>
class llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator
Definition at line 272 of file EquivalenceClasses.h.
Member Typedef Documentation
difference_type
template<class ElemTy , class Compare = std::less<ElemTy>> using llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::difference_type = std::ptrdiff_t
Definition at line 281 of file EquivalenceClasses.h.
iterator_category
template<class ElemTy , class Compare = std::less<ElemTy>> using llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::iterator_category = std::forward_iterator_tag
Definition at line 278 of file EquivalenceClasses.h.
pointer
template<class ElemTy , class Compare = std::less<ElemTy>> using llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::pointer = value_type *
Definition at line 282 of file EquivalenceClasses.h.
reference
template<class ElemTy , class Compare = std::less<ElemTy>> using llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::reference = value_type &
Definition at line 283 of file EquivalenceClasses.h.
size_type
template<class ElemTy , class Compare = std::less<ElemTy>> using llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::size_type = std::size_t
Definition at line 280 of file EquivalenceClasses.h.
value_type
template<class ElemTy , class Compare = std::less<ElemTy>> using llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::value_type = const ElemTy
Definition at line 279 of file EquivalenceClasses.h.
Constructor & Destructor Documentation
member_iterator() [1/2]
template<class ElemTy , class Compare = std::less<ElemTy>> llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::member_iterator () explicit default
member_iterator() [2/2]
template<class ElemTy , class Compare = std::less<ElemTy>> llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::member_iterator (const ECValue * N) inline explicit
Definition at line 286 of file EquivalenceClasses.h.
Member Function Documentation
operator!=()
template<class ElemTy , class Compare = std::less<ElemTy>> bool llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::operator!= (const member_iterator & RHS) const inline
Definition at line 309 of file EquivalenceClasses.h.
References Node::Node().
operator*()
template<class ElemTy , class Compare = std::less<ElemTy>> reference llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::operator* () const inline
Definition at line 288 of file EquivalenceClasses.h.
References assert().
Referenced by llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::operator->().
operator++() [1/2]
template<class ElemTy , class Compare = std::less<ElemTy>> member_iterator & llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::operator++ () inline
Definition at line 294 of file EquivalenceClasses.h.
References assert().
operator++() [2/2]
template<class ElemTy , class Compare = std::less<ElemTy>> member_iterator llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::operator++ (int) inline
Definition at line 300 of file EquivalenceClasses.h.
operator->()
template<class ElemTy , class Compare = std::less<ElemTy>> pointer llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::operator-> () const inline
Definition at line 292 of file EquivalenceClasses.h.
References llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::operator*().
operator==()
template<class ElemTy , class Compare = std::less<ElemTy>> bool llvm::EquivalenceClasses< ElemTy, Compare >::member_iterator::operator== (const member_iterator & RHS) const inline
Definition at line 306 of file EquivalenceClasses.h.
References Node::Node().
Friends And Related Symbol Documentation
EquivalenceClasses
template<class ElemTy , class Compare = std::less<ElemTy>> friend class EquivalenceClasses friend
Definition at line 273 of file EquivalenceClasses.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/EquivalenceClasses.h