LLVM: llvm::objcopy::NameOrPattern Class Reference
llvm::objcopy::NameOrPattern Class Reference
#include "llvm/ObjCopy/CommonConfig.h"
Public Member Functions
bool isPositiveMatch () const
std::optional< StringRef > getName () const
bool operator== (StringRef S) const
bool operator!= (StringRef S) const
Static Public Member Functions
static Expected< NameOrPattern > create (StringRef Pattern, MatchStyle MS, llvm::function_ref< Error(Error)> ErrorCallback)
Detailed Description
Definition at line 92 of file CommonConfig.h.
Member Function Documentation
create()
Expected< NameOrPattern > llvm::objcopy::NameOrPattern::create (StringRef Pattern, MatchStyle MS, llvm::function_ref< Error(Error)> ErrorCallback) static
Definition at line 16 of file CommonConfig.cpp.
References llvm::GlobPattern::create(), create(), llvm::createStringError(), llvm::Data, llvm::invalid_argument, llvm::Regex::isValid(), llvm::objcopy::Literal, llvm_unreachable, llvm::objcopy::Regex, llvm::Expected< T >::takeError(), and llvm::objcopy::Wildcard.
Referenced by create().
getName()
std::optional< StringRef > llvm::objcopy::NameOrPattern::getName () const inline
Definition at line 112 of file CommonConfig.h.
References G.
isPositiveMatch()
bool llvm::objcopy::NameOrPattern::isPositiveMatch () const inline
Definition at line 111 of file CommonConfig.h.
operator!=()
bool llvm::objcopy::NameOrPattern::operator!= (StringRef S) const inline
Definition at line 120 of file CommonConfig.h.
References operator==().
operator==()
bool llvm::objcopy::NameOrPattern::operator== (StringRef S) const inline
Definition at line 117 of file CommonConfig.h.
References G.
Referenced by operator!=().
The documentation for this class was generated from the following files:
include/llvm/ObjCopy/CommonConfig.h
lib/ObjCopy/CommonConfig.cpp