LLVM: llvm::Target Class Reference
llvm::Target Class Reference
Target - Wrapper for Target specific information.
#include "llvm/MC/TargetRegistry.h"
Public Types
using ArchMatchFnTy = bool (*)(Triple::ArchType Arch)
using MCAsmInfoCtorFnTy
using MCObjectFileInfoCtorFnTy
using MCInstrInfoCtorFnTy = MCInstrInfo *(*)()
using MCInstrAnalysisCtorFnTy = MCInstrAnalysis *(*)(const MCInstrInfo *Info)
using MCRegInfoCtorFnTy = MCRegisterInfo *(*)(const Triple &TT)
using MCSubtargetInfoCtorFnTy
using TargetMachineCtorTy
using AsmPrinterCtorTy
using MCAsmBackendCtorTy
using MCAsmParserCtorTy
using MCDisassemblerCtorTy
using MCInstPrinterCtorTy
using MCCodeEmitterCtorTy
using ELFStreamerCtorTy
using MachOStreamerCtorTy
using COFFStreamerCtorTy
using XCOFFStreamerCtorTy
using NullTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S)
using AsmTargetStreamerCtorTy
using ObjectTargetStreamerCtorTy
using MCRelocationInfoCtorTy
using MCSymbolizerCtorTy
using CustomBehaviourCtorTy
using InstrPostProcessCtorTy
using InstrumentManagerCtorTy
Public Member Functions
Target ()=default
Target Information
const Target * getNext () const
const char * getName () const
getName - Get the target name.
const char * getShortDescription () const
getShortDescription - Get a short description of the target.
const char * getBackendName () const
getBackendName - Get the backend name.
Feature Predicates
bool hasJIT () const
hasJIT - Check if this targets supports the just-in-time compilation.
bool hasTargetMachine () const
hasTargetMachine - Check if this target supports code generation.
bool hasMCAsmBackend () const
hasMCAsmBackend - Check if this target supports .o generation.
bool hasMCAsmParser () const
hasMCAsmParser - Check if this target supports assembly parsing.
Feature Constructors
MCAsmInfo * createMCAsmInfo (const MCRegisterInfo &MRI, StringRef TheTriple, const MCTargetOptions &Options) const
createMCAsmInfo - Create a MCAsmInfo implementation for the specified target triple.
MCObjectFileInfo * createMCObjectFileInfo (MCContext &Ctx, bool PIC, bool LargeCodeModel=false) const
Create a MCObjectFileInfo implementation for the specified target triple.
MCInstrInfo * createMCInstrInfo () const
createMCInstrInfo - Create a MCInstrInfo implementation.
MCInstrAnalysis * createMCInstrAnalysis (const MCInstrInfo *Info) const
createMCInstrAnalysis - Create a MCInstrAnalysis implementation.
MCRegisterInfo * createMCRegInfo (StringRef TT) const
createMCRegInfo - Create a MCRegisterInfo implementation.
MCSubtargetInfo * createMCSubtargetInfo (StringRef TheTriple, StringRef CPU, StringRef Features) const
createMCSubtargetInfo - Create a MCSubtargetInfo implementation.
TargetMachine * createTargetMachine (StringRef TT, StringRef CPU, StringRef Features, const TargetOptions &Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM=std::nullopt, CodeGenOptLevel OL=CodeGenOptLevel::Default, bool JIT=false) const
createTargetMachine - Create a target specific machine implementation for the specified Triple.
MCAsmBackend * createMCAsmBackend (const MCSubtargetInfo &STI, const MCRegisterInfo &MRI, const MCTargetOptions &Options) const
createMCAsmBackend - Create a target specific assembly parser.
MCTargetAsmParser * createMCAsmParser (const MCSubtargetInfo &STI, MCAsmParser &Parser, const MCInstrInfo &MII, const MCTargetOptions &Options) const
createMCAsmParser - Create a target specific assembly parser.
AsmPrinter * createAsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > &&Streamer) const
createAsmPrinter - Create a target specific assembly printer pass.
MCDisassembler * createMCDisassembler (const MCSubtargetInfo &STI, MCContext &Ctx) const
MCInstPrinter * createMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI) const
MCCodeEmitter * createMCCodeEmitter (const MCInstrInfo &II, MCContext &Ctx) const
createMCCodeEmitter - Create a target specific code emitter.
MCStreamer * createMCObjectStreamer (const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > TAB, std::unique_ptr< MCObjectWriter > OW, std::unique_ptr< MCCodeEmitter > Emitter, const MCSubtargetInfo &STI) const
Create a target specific MCStreamer.
MCStreamer * createMCObjectStreamer (const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, const MCSubtargetInfo &STI, bool, bool, bool) const
MCStreamer * createAsmStreamer (MCContext &Ctx, std::unique_ptr< formatted_raw_ostream > OS, MCInstPrinter *IP, std::unique_ptr< MCCodeEmitter > CE, std::unique_ptr< MCAsmBackend > TAB) const
MCStreamer * createAsmStreamer (MCContext &Ctx, std::unique_ptr< formatted_raw_ostream > OS, bool IsVerboseAsm, bool UseDwarfDirectory, MCInstPrinter *IP, std::unique_ptr< MCCodeEmitter > &&CE, std::unique_ptr< MCAsmBackend > &&TAB, bool ShowInst) const
MCTargetStreamer * createAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint) const
MCStreamer * createNullStreamer (MCContext &Ctx) const
MCTargetStreamer * createNullTargetStreamer (MCStreamer &S) const
MCRelocationInfo * createMCRelocationInfo (StringRef TT, MCContext &Ctx) const
createMCRelocationInfo - Create a target specific MCRelocationInfo.
MCSymbolizer * createMCSymbolizer (StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, std::unique_ptr< MCRelocationInfo > &&RelInfo) const
createMCSymbolizer - Create a target specific MCSymbolizer.
mca::CustomBehaviour * createCustomBehaviour (const MCSubtargetInfo &STI, const mca::SourceMgr &SrcMgr, const MCInstrInfo &MCII) const
createCustomBehaviour - Create a target specific CustomBehaviour.
mca::InstrPostProcess * createInstrPostProcess (const MCSubtargetInfo &STI, const MCInstrInfo &MCII) const
createInstrPostProcess - Create a target specific InstrPostProcess.
mca::InstrumentManager * createInstrumentManager (const MCSubtargetInfo &STI, const MCInstrInfo &MCII) const
createInstrumentManager - Create a target specific InstrumentManager.
Friends
struct TargetRegistry
Detailed Description
Target - Wrapper for Target specific information.
For registration purposes, this is a POD type so that targets can be registered without the use of static constructors.
Targets should implement a single global instance of this class (which will be zero initialized), and pass that instance to the TargetRegistry as part of their initialization.
Definition at line 144 of file TargetRegistry.h.
Member Typedef Documentation
ArchMatchFnTy
using llvm::Target::ArchMatchFnTy = bool (*)(Triple::ArchType Arch)
Definition at line 148 of file TargetRegistry.h.
AsmPrinterCtorTy
using llvm::Target::AsmPrinterCtorTy
Initial value:
 AsmPrinter *(*)(
      TargetMachine &TM, std::unique_ptr<MCStreamer> &&Streamer)
Definition at line 169 of file TargetRegistry.h.
AsmTargetStreamerCtorTy
using llvm::Target::AsmTargetStreamerCtorTy
Initial value:
      MCTargetStreamer *(*)(MCStreamer &S, formatted_raw_ostream &OS,
                            MCInstPrinter *InstPrint)
Definition at line 208 of file TargetRegistry.h.
COFFStreamerCtorTy
using llvm::Target::COFFStreamerCtorTy
Initial value:
      MCStreamer *(*)(MCContext &Ctx, std::unique_ptr<MCAsmBackend> &&TAB,
                      std::unique_ptr<MCObjectWriter> &&OW,
                      std::unique_ptr<MCCodeEmitter> &&Emitter)
Definition at line 197 of file TargetRegistry.h.
CustomBehaviourCtorTy
using llvm::Target::CustomBehaviourCtorTy
Initial value:
      mca::CustomBehaviour *(*)(const MCSubtargetInfo &STI,
                                const mca::SourceMgr &SrcMgr,
                                const MCInstrInfo &MCII)
Definition at line 220 of file TargetRegistry.h.
ELFStreamerCtorTy
using llvm::Target::ELFStreamerCtorTy
Initial value:
      MCStreamer *(*)(const Triple &T, MCContext &Ctx,
                      std::unique_ptr<MCAsmBackend> &&TAB,
                      std::unique_ptr<MCObjectWriter> &&OW,
                      std::unique_ptr<MCCodeEmitter> &&Emitter)
Definition at line 188 of file TargetRegistry.h.
InstrPostProcessCtorTy
using llvm::Target::InstrPostProcessCtorTy
Initial value:
      mca::InstrPostProcess *(*)(const MCSubtargetInfo &STI,
                                 const MCInstrInfo &MCII)
Definition at line 225 of file TargetRegistry.h.
InstrumentManagerCtorTy
using llvm::Target::InstrumentManagerCtorTy
Initial value:
      mca::InstrumentManager *(*)(const MCSubtargetInfo &STI,
                                  const MCInstrInfo &MCII)
Definition at line 229 of file TargetRegistry.h.
MachOStreamerCtorTy
using llvm::Target::MachOStreamerCtorTy
Initial value:
      MCStreamer *(*)(MCContext &Ctx, std::unique_ptr<MCAsmBackend> &&TAB,
                      std::unique_ptr<MCObjectWriter> &&OW,
                      std::unique_ptr<MCCodeEmitter> &&Emitter)
Definition at line 193 of file TargetRegistry.h.
MCAsmBackendCtorTy
using llvm::Target::MCAsmBackendCtorTy
Initial value:
 MCAsmBackend *(*)(const Target &T,
                                               const MCSubtargetInfo &STI,
                                               const MCRegisterInfo &MRI,
                                               const MCTargetOptions &Options)
Definition at line 171 of file TargetRegistry.h.
MCAsmInfoCtorFnTy
using llvm::Target::MCAsmInfoCtorFnTy
Initial value:
 MCAsmInfo *(*)(const MCRegisterInfo &MRI,
                                           const Triple &TT,
                                           const MCTargetOptions &Options)
Definition at line 150 of file TargetRegistry.h.
MCAsmParserCtorTy
using llvm::Target::MCAsmParserCtorTy
Initial value:
 MCTargetAsmParser *(*)(
      const MCSubtargetInfo &STI, MCAsmParser &P, const MCInstrInfo &MII,
      const MCTargetOptions &Options)
Definition at line 175 of file TargetRegistry.h.
MCCodeEmitterCtorTy
using llvm::Target::MCCodeEmitterCtorTy
Initial value:
 MCCodeEmitter *(*)(const MCInstrInfo &II,
                                                 MCContext &Ctx)
Definition at line 186 of file TargetRegistry.h.
MCDisassemblerCtorTy
using llvm::Target::MCDisassemblerCtorTy
Initial value:
 MCDisassembler *(*)(const Target &T,
                                                   const MCSubtargetInfo &STI,
                                                   MCContext &Ctx)
Definition at line 178 of file TargetRegistry.h.
MCInstPrinterCtorTy
using llvm::Target::MCInstPrinterCtorTy
Initial value:
 MCInstPrinter *(*)(const Triple &T,
                                                 unsigned SyntaxVariant,
                                                 const MCAsmInfo &MAI,
                                                 const MCInstrInfo &MII,
                                                 const MCRegisterInfo &MRI)
Definition at line 181 of file TargetRegistry.h.
MCInstrAnalysisCtorFnTy
using llvm::Target::MCInstrAnalysisCtorFnTy = MCInstrAnalysis *(*)(const MCInstrInfo *Info)
Definition at line 157 of file TargetRegistry.h.
MCInstrInfoCtorFnTy
using llvm::Target::MCInstrInfoCtorFnTy = MCInstrInfo *(*)()
Definition at line 156 of file TargetRegistry.h.
MCObjectFileInfoCtorFnTy
using llvm::Target::MCObjectFileInfoCtorFnTy
Initial value:
 MCObjectFileInfo *(*)(MCContext &Ctx,
                                                         bool PIC,
                                                         bool LargeCodeModel)
Definition at line 153 of file TargetRegistry.h.
MCRegInfoCtorFnTy
using llvm::Target::MCRegInfoCtorFnTy = MCRegisterInfo *(*)(const Triple &TT)
Definition at line 158 of file TargetRegistry.h.
MCRelocationInfoCtorTy
using llvm::Target::MCRelocationInfoCtorTy
Initial value:
 MCRelocationInfo *(*)(const Triple &TT,
                                                       MCContext &Ctx)
Definition at line 213 of file TargetRegistry.h.
MCSubtargetInfoCtorFnTy
using llvm::Target::MCSubtargetInfoCtorFnTy
Initial value:
 MCSubtargetInfo *(*)(const Triple &TT,
                                                       StringRef CPU,
                                                       StringRef Features)
Definition at line 159 of file TargetRegistry.h.
MCSymbolizerCtorTy
using llvm::Target::MCSymbolizerCtorTy
Initial value:
 MCSymbolizer *(*)(
      const Triple &TT, LLVMOpInfoCallback GetOpInfo,
      LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx,
      std::unique_ptr<MCRelocationInfo> &&RelInfo)
Definition at line 215 of file TargetRegistry.h.
NullTargetStreamerCtorTy
using llvm::Target::NullTargetStreamerCtorTy = MCTargetStreamer *(*)(MCStreamer &S)
Definition at line 207 of file TargetRegistry.h.
ObjectTargetStreamerCtorTy
using llvm::Target::ObjectTargetStreamerCtorTy
Initial value:
 MCTargetStreamer *(*)(
      MCStreamer &S, const MCSubtargetInfo &STI)
Definition at line 211 of file TargetRegistry.h.
TargetMachineCtorTy
using llvm::Target::TargetMachineCtorTy
Initial value:
 TargetMachine
      *(*)(const Target &T, const Triple &TT, StringRef CPU, StringRef Features,
           const TargetOptions &Options, std::optional<Reloc::Model> RM,
           std::optional<CodeModel::Model> CM, CodeGenOptLevel OL, bool JIT)
Definition at line 162 of file TargetRegistry.h.
XCOFFStreamerCtorTy
using llvm::Target::XCOFFStreamerCtorTy
Initial value:
      MCStreamer *(*)(const Triple &T, MCContext &Ctx,
                      std::unique_ptr<MCAsmBackend> &&TAB,
                      std::unique_ptr<MCObjectWriter> &&OW,
                      std::unique_ptr<MCCodeEmitter> &&Emitter)
Definition at line 201 of file TargetRegistry.h.
Constructor & Destructor Documentation
Target()
llvm::Target::Target () default
Member Function Documentation
createAsmPrinter()
AsmPrinter * llvm::Target::createAsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > && Streamer) const inline
createAsmPrinter - Create a target specific assembly printer pass.
This takes ownership of the MCStreamer object.
Definition at line 490 of file TargetRegistry.h.
References TM.
Referenced by llvm::LLVMTargetMachine::addAsmPrinter(), llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::dwarf_linker::classic::DwarfStreamer::init(), and llvm::dwarf_linker::parallel::DwarfEmitterImpl::init().
createAsmStreamer() [1/2]
MCStreamer * Target::createAsmStreamer (MCContext & Ctx, std::unique_ptr< formatted_raw_ostream > OS, bool IsVerboseAsm, bool UseDwarfDirectory, MCInstPrinter * IP, std::unique_ptr< MCCodeEmitter > && CE, std::unique_ptr< MCAsmBackend > && TAB, bool ShowInst) const
Definition at line 102 of file TargetRegistry.cpp.
References createAsmStreamer(), and OS.
createAsmStreamer() [2/2]
MCStreamer * Target::createAsmStreamer (MCContext & Ctx, std::unique_ptr< formatted_raw_ostream > OS, MCInstPrinter * IP, std::unique_ptr< MCCodeEmitter > CE, std::unique_ptr< MCAsmBackend > TAB) const
Definition at line 90 of file TargetRegistry.cpp.
References llvm::createAsmStreamer(), createAsmTargetStreamer(), and OS.
Referenced by createAsmStreamer(), llvm::LLVMTargetMachine::createMCStreamer(), llvm::dwarf_linker::classic::DwarfStreamer::init(), and llvm::dwarf_linker::parallel::DwarfEmitterImpl::init().
createAsmTargetStreamer()
MCTargetStreamer * llvm::Target::createAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint) const inline
Definition at line 553 of file TargetRegistry.h.
References OS.
Referenced by createAsmStreamer().
createCustomBehaviour()
mca::CustomBehaviour * llvm::Target::createCustomBehaviour (const MCSubtargetInfo & STI, const mca::SourceMgr & SrcMgr, const MCInstrInfo & MCII) const inline
createCustomBehaviour - Create a target specific CustomBehaviour.
This class is used by llvm-mca and requires backend functionality.
Definition at line 609 of file TargetRegistry.h.
References llvm::SrcMgr.
createInstrPostProcess()
mca::InstrPostProcess * llvm::Target::createInstrPostProcess (const MCSubtargetInfo & STI, const MCInstrInfo & MCII) const inline
createInstrPostProcess - Create a target specific InstrPostProcess.
This class is used by llvm-mca and requires backend functionality.
Definition at line 619 of file TargetRegistry.h.
createInstrumentManager()
mca::InstrumentManager * llvm::Target::createInstrumentManager (const MCSubtargetInfo & STI, const MCInstrInfo & MCII) const inline
createInstrumentManager - Create a target specific InstrumentManager.
This class is used by llvm-mca and requires backend functionality.
Definition at line 630 of file TargetRegistry.h.
createMCAsmBackend()
MCAsmBackend * llvm::Target::createMCAsmBackend (const MCSubtargetInfo & STI, const MCRegisterInfo & MRI, const MCTargetOptions & Options) const inline
createMCAsmBackend - Create a target specific assembly parser.
Definition at line 467 of file TargetRegistry.h.
References MRI, and Options.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::LLVMTargetMachine::createMCStreamer(), llvm::dwarf_linker::classic::DwarfStreamer::init(), and llvm::dwarf_linker::parallel::DwarfEmitterImpl::init().
createMCAsmInfo()
MCAsmInfo * llvm::Target::createMCAsmInfo (const MCRegisterInfo & MRI, StringRef TheTriple, const MCTargetOptions & Options) const inline
createMCAsmInfo - Create a MCAsmInfo implementation for the specified target triple.
Parameters
TheTriple This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
Definition at line 388 of file TargetRegistry.h.
References MRI, and Options.
Referenced by llvm::dwarf_linker::classic::DwarfStreamer::init(), llvm::dwarf_linker::parallel::DwarfEmitterImpl::init(), llvm::LLVMTargetMachine::initAsmInfo(), LLVMCreateDisasmCPUFeatures(), and llvm::logicalview::LVBinaryReader::loadGenericTargetInfo().
createMCAsmParser()
MCTargetAsmParser * llvm::Target::createMCAsmParser (const MCSubtargetInfo & STI, MCAsmParser & Parser, const MCInstrInfo & MII, const MCTargetOptions & Options) const inline
createMCAsmParser - Create a target specific assembly parser.
Parameters
Parser The target independent parser implementation to use for parsing and lexing.
Definition at line 479 of file TargetRegistry.h.
References Options.
createMCCodeEmitter()
MCCodeEmitter * llvm::Target::createMCCodeEmitter (const MCInstrInfo & II, MCContext & Ctx) const inline
createMCCodeEmitter - Create a target specific code emitter.
Definition at line 514 of file TargetRegistry.h.
References II.
Referenced by llvm::LLVMTargetMachine::createMCStreamer(), llvm::dwarf_linker::classic::DwarfStreamer::init(), llvm::dwarf_linker::parallel::DwarfEmitterImpl::init(), and llvm::X86AsmPrinter::runOnMachineFunction().
createMCDisassembler()
MCDisassembler * llvm::Target::createMCDisassembler (const MCSubtargetInfo & STI, MCContext & Ctx) const inline
Definition at line 497 of file TargetRegistry.h.
Referenced by LLVMCreateDisasmCPUFeatures(), and llvm::logicalview::LVBinaryReader::loadGenericTargetInfo().
createMCInstPrinter()
MCInstPrinter * llvm::Target::createMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) const inline
Definition at line 504 of file TargetRegistry.h.
References MRI.
Referenced by llvm::LLVMTargetMachine::createMCStreamer(), llvm::dwarf_linker::classic::DwarfStreamer::init(), llvm::dwarf_linker::parallel::DwarfEmitterImpl::init(), LLVMCreateDisasmCPUFeatures(), LLVMSetDisasmOptions(), and llvm::logicalview::LVBinaryReader::loadGenericTargetInfo().
createMCInstrAnalysis()
MCInstrAnalysis * llvm::Target::createMCInstrAnalysis (const MCInstrInfo * Info) const inline
createMCInstrAnalysis - Create a MCInstrAnalysis implementation.
Definition at line 418 of file TargetRegistry.h.
createMCInstrInfo()
MCInstrInfo * llvm::Target::createMCInstrInfo () const inline
createMCInstrInfo - Create a MCInstrInfo implementation.
Definition at line 410 of file TargetRegistry.h.
Referenced by llvm::dwarf_linker::classic::DwarfStreamer::init(), llvm::dwarf_linker::parallel::DwarfEmitterImpl::init(), llvm::LLVMTargetMachine::initAsmInfo(), LLVMCreateDisasmCPUFeatures(), and llvm::logicalview::LVBinaryReader::loadGenericTargetInfo().
createMCObjectFileInfo()
MCObjectFileInfo * llvm::Target::createMCObjectFileInfo (MCContext & Ctx, bool PIC, bool LargeCodeModel = false) const inline
Create a MCObjectFileInfo implementation for the specified target triple.
Definition at line 398 of file TargetRegistry.h.
References llvm::MCObjectFileInfo::initMCObjectFileInfo(), and PIC.
Referenced by llvm::dwarf_linker::classic::DwarfStreamer::init(), and llvm::dwarf_linker::parallel::DwarfEmitterImpl::init().
createMCObjectStreamer() [1/2]
MCStreamer * Target::createMCObjectStreamer (const Triple & T, MCContext & Ctx, std::unique_ptr< MCAsmBackend > && TAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, const MCSubtargetInfo & STI, bool , bool , bool) const
Definition at line 81 of file TargetRegistry.cpp.
References createMCObjectStreamer(), and Emitter.
createMCObjectStreamer() [2/2]
MCStreamer * Target::createMCObjectStreamer (const Triple & T, MCContext & Ctx, std::unique_ptr< MCAsmBackend > TAB, std::unique_ptr< MCObjectWriter > OW, std::unique_ptr< MCCodeEmitter > Emitter, const MCSubtargetInfo & STI) const
Create a target specific MCStreamer.
Parameters
T The target triple.
Ctx The target context.
TAB The target assembler backend object. Takes ownership.
OW The stream object.
Emitter The target independent assembler object.Takes ownership.
Definition at line 25 of file TargetRegistry.cpp.
References assert(), llvm::Triple::COFF, llvm::createDXContainerStreamer(), llvm::createELFStreamer(), llvm::createGOFFStreamer(), llvm::createMachOStreamer(), llvm::createSPIRVStreamer(), llvm::createWasmStreamer(), llvm::Triple::DXContainer, llvm::Triple::ELF, Emitter, llvm::Triple::GOFF, llvm_unreachable, llvm::Triple::MachO, llvm::Triple::SPIRV, llvm::Triple::UnknownObjectFormat, llvm::Triple::Wasm, and llvm::Triple::XCOFF.
Referenced by createMCObjectStreamer(), llvm::dwarf_linker::classic::DwarfStreamer::init(), and llvm::dwarf_linker::parallel::DwarfEmitterImpl::init().
createMCRegInfo()
MCRegisterInfo * llvm::Target::createMCRegInfo (StringRef TT) const inline
createMCRegInfo - Create a MCRegisterInfo implementation.
Definition at line 426 of file TargetRegistry.h.
Referenced by llvm::dwarf_linker::classic::DwarfStreamer::init(), llvm::dwarf_linker::parallel::DwarfEmitterImpl::init(), llvm::LLVMTargetMachine::initAsmInfo(), LLVMCreateDisasmCPUFeatures(), and llvm::logicalview::LVBinaryReader::loadGenericTargetInfo().
createMCRelocationInfo()
MCRelocationInfo * llvm::Target::createMCRelocationInfo (StringRef TT, MCContext & Ctx) const inline
createMCRelocationInfo - Create a target specific MCRelocationInfo.
Parameters
TT The target triple.
Ctx The target context.
Definition at line 577 of file TargetRegistry.h.
References llvm::createMCRelocationInfo().
Referenced by LLVMCreateDisasmCPUFeatures().
createMCSubtargetInfo()
MCSubtargetInfo * llvm::Target::createMCSubtargetInfo (StringRef TheTriple, StringRef CPU, StringRef Features) const inline
createMCSubtargetInfo - Create a MCSubtargetInfo implementation.
Parameters
TheTriple This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
CPU This specifies the name of the target CPU.
Features This specifies the string representation of the additional target features.
Definition at line 441 of file TargetRegistry.h.
Referenced by llvm::dwarf_linker::classic::DwarfStreamer::init(), llvm::dwarf_linker::parallel::DwarfEmitterImpl::init(), llvm::LLVMTargetMachine::initAsmInfo(), LLVMCreateDisasmCPUFeatures(), and llvm::logicalview::LVBinaryReader::loadGenericTargetInfo().
createMCSymbolizer()
MCSymbolizer * llvm::Target::createMCSymbolizer (StringRef TT, LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void * DisInfo, MCContext * Ctx, std::unique_ptr< MCRelocationInfo > && RelInfo) const inline
createMCSymbolizer - Create a target specific MCSymbolizer.
Parameters
TT The target triple.
GetOpInfo The function to get the symbolic information for operands.
SymbolLookUp The function to lookup a symbol name.
DisInfo The pointer to the block of symbolic information for above call back.
Ctx The target context.
RelInfo The relocation information for this target. Takes ownership.
Definition at line 597 of file TargetRegistry.h.
References llvm::createMCSymbolizer().
Referenced by LLVMCreateDisasmCPUFeatures().
createNullStreamer()
MCStreamer * llvm::Target::createNullStreamer (MCContext & Ctx) const inline
Definition at line 561 of file TargetRegistry.h.
References llvm::createNullStreamer(), and createNullTargetStreamer().
createNullTargetStreamer()
MCTargetStreamer * llvm::Target::createNullTargetStreamer (MCStreamer & S) const inline
Definition at line 567 of file TargetRegistry.h.
Referenced by createNullStreamer().
createTargetMachine()
TargetMachine * llvm::Target::createTargetMachine (StringRef TT, StringRef CPU, StringRef Features, const TargetOptions & Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM = std::nullopt, CodeGenOptLevel OL = CodeGenOptLevel::Default, bool JIT = false) const inline
createTargetMachine - Create a target specific machine implementation for the specified Triple.
Parameters
TT This argument is used to determine the target machine feature set; it should always be provided. Generally this should be either the target triple from the module, or the target triple of the host if that does not exist.
Definition at line 455 of file TargetRegistry.h.
References Options.
Referenced by llvm::TargetMachineBuilder::create(), createTargetMachine(), createTargetMachine(), llvm::codegen::createTargetMachineForTriple(), llvm::dwarf_linker::classic::DwarfStreamer::init(), llvm::dwarf_linker::parallel::DwarfEmitterImpl::init(), and llvm::EngineBuilder::selectTarget().
getBackendName()
const char * llvm::Target::getBackendName () const inline
getBackendName - Get the backend name.
Definition at line 359 of file TargetRegistry.h.
getName()
const char * llvm::Target::getName () const inline
getName - Get the target name.
Definition at line 353 of file TargetRegistry.h.
References Name.
Referenced by llvm::jitlink::TableManager< TableManagerImplT >::getEntryForTarget(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::getGOTEntry(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::getPLTStub(), llvm::MachObjectWriter::getSymbolAddress(), llvm::logicalview::LVScope::markMissingParents(), llvm::logicalview::LVSymbol::markMissingParents(), llvm::logicalview::LVType::markMissingParents(), llvm::jitlink::TableManager< TableManagerImplT >::registerPreExistingEntry(), llvm::jitlink::aarch32::StubsManager_prev7::visitEdge(), and llvm::jitlink::aarch32::StubsManager_v7::visitEdge().
getNext()
const Target * llvm::Target::getNext () const inline
Definition at line 350 of file TargetRegistry.h.
References llvm::Next.
Referenced by llvm::TargetRegistry::iterator::operator++().
getShortDescription()
const char * llvm::Target::getShortDescription () const inline
getShortDescription - Get a short description of the target.
Definition at line 356 of file TargetRegistry.h.
Referenced by llvm::TargetRegistry::printRegisteredTargetsForVersion().
hasJIT()
bool llvm::Target::hasJIT () const inline
hasJIT - Check if this targets supports the just-in-time compilation.
Definition at line 366 of file TargetRegistry.h.
hasMCAsmBackend()
bool llvm::Target::hasMCAsmBackend () const inline
hasMCAsmBackend - Check if this target supports .o generation.
Definition at line 372 of file TargetRegistry.h.
hasMCAsmParser()
bool llvm::Target::hasMCAsmParser () const inline
hasMCAsmParser - Check if this target supports assembly parsing.
Definition at line 375 of file TargetRegistry.h.
hasTargetMachine()
bool llvm::Target::hasTargetMachine () const inline
hasTargetMachine - Check if this target supports code generation.
Definition at line 369 of file TargetRegistry.h.
Friends And Related Symbol Documentation
TargetRegistry
friend struct TargetRegistry friend
Definition at line 146 of file TargetRegistry.h.
The documentation for this class was generated from the following files:
include/llvm/MC/TargetRegistry.h
lib/MC/TargetRegistry.cpp