LLVM: llvm::dwarf_linker::parallel::TypeEntryInfo Class Reference
llvm::dwarf_linker::parallel::TypeEntryInfo Class Reference
#include "DWARFLinker/Parallel/TypePool.h"
Static Public Member Functions
static uint64_t getHashValue (const StringRef &Key)
static bool isEqual (const StringRef &LHS, const StringRef &RHS)
static StringRef getKey (const TypeEntry &KeyData)
static TypeEntry * create (const StringRef &Key, llvm::parallel::PerThreadBumpPtrAllocator &Allocator)
Detailed Description
Definition at line 81 of file TypePool.h.
Member Function Documentation
create()
static TypeEntry * llvm::dwarf_linker::parallel::TypeEntryInfo::create (const StringRef & Key, llvm::parallel::PerThreadBumpPtrAllocator & Allocator) inline static
Returns
newly created object of KeyDataTy type.
Definition at line 100 of file TypePool.h.
References llvm::StringMapEntry< T >::create().
getHashValue()
static uint64_t llvm::dwarf_linker::parallel::TypeEntryInfo::getHashValue (const StringRef & Key) inline static
Returns
Hash value for the specified Key.
Definition at line 84 of file TypePool.h.
References llvm::xxh3_64bits().
getKey()
static StringRef llvm::dwarf_linker::parallel::TypeEntryInfo::getKey (const TypeEntry & KeyData) inline static
Returns
key for the specified KeyData.
Definition at line 94 of file TypePool.h.
References llvm::StringMapEntry< T >::getKey().
isEqual()
static bool llvm::dwarf_linker::parallel::TypeEntryInfo::isEqual (const StringRef & LHS, const StringRef & RHS) inline static
Returns
true if both LHS and RHS are equal.
Definition at line 89 of file TypePool.h.
References RHS.
The documentation for this class was generated from the following file:
lib/DWARFLinker/Parallel/TypePool.h