LLVM: llvm::CombinerHelper Class Reference
llvm::CombinerHelper Class Reference
#include "llvm/CodeGen/GlobalISel/CombinerHelper.h"
Public Member Functions
CombinerHelper (GISelChangeObserver &Observer, MachineIRBuilder &B, bool IsPreLegalize, GISelKnownBits *KB=nullptr, MachineDominatorTree *MDT=nullptr, const LegalizerInfo *LI=nullptr)
GISelKnownBits * getKnownBits () const
MachineIRBuilder & getBuilder () const
const TargetLowering & getTargetLowering () const
bool isPreLegalize () const
bool isLegal (const LegalityQuery &Query) const
bool isLegalOrBeforeLegalizer (const LegalityQuery &Query) const
bool isConstantLegalOrBeforeLegalizer (const LLT Ty) const
void replaceRegWith (MachineRegisterInfo &MRI, Register FromReg, Register ToReg) const
MachineRegisterInfo::replaceRegWith() and inform the observer of the changes.
void replaceRegOpWith (MachineRegisterInfo &MRI, MachineOperand &FromRegOp, Register ToReg) const
Replace a single register operand with a new register and inform the observer of the changes.
void replaceOpcodeWith (MachineInstr &FromMI, unsigned ToOpcode) const
Replace the opcode in instruction with a new opcode and inform the observer of the changes.
const RegisterBank * getRegBank (Register Reg) const
Get the register bank of Reg.
void setRegBank (Register Reg, const RegisterBank *RegBank)
Set the register bank of Reg.
bool tryCombineCopy (MachineInstr &MI)
If MI is COPY, try to combine it.
bool matchCombineCopy (MachineInstr &MI)
void applyCombineCopy (MachineInstr &MI)
bool isPredecessor (const MachineInstr &DefMI, const MachineInstr &UseMI)
Returns true if DefMI precedes UseMI or they are the same instruction.
bool dominates (const MachineInstr &DefMI, const MachineInstr &UseMI)
Returns true if DefMI dominates UseMI.
bool tryCombineExtendingLoads (MachineInstr &MI)
If MI is extend that consumes the result of a load, try to combine it.
bool matchCombineExtendingLoads (MachineInstr &MI, PreferredTuple &MatchInfo)
void applyCombineExtendingLoads (MachineInstr &MI, PreferredTuple &MatchInfo)
bool matchCombineLoadWithAndMask (MachineInstr &MI, BuildFnTy &MatchInfo)
Match (and (load x), mask) -> zextload x.
bool matchCombineExtractedVectorLoad (MachineInstr &MI, BuildFnTy &MatchInfo)
Combine a G_EXTRACT_VECTOR_ELT of a load into a narrowed load.
bool matchCombineIndexedLoadStore (MachineInstr &MI, IndexedLoadStoreMatchInfo &MatchInfo)
void applyCombineIndexedLoadStore (MachineInstr &MI, IndexedLoadStoreMatchInfo &MatchInfo)
bool matchSextTruncSextLoad (MachineInstr &MI)
void applySextTruncSextLoad (MachineInstr &MI)
bool matchSextInRegOfLoad (MachineInstr &MI, std::tuple< Register, unsigned > &MatchInfo)
Match sext_inreg(load p), imm -> sextload p.
void applySextInRegOfLoad (MachineInstr &MI, std::tuple< Register, unsigned > &MatchInfo)
bool matchCombineDivRem (MachineInstr &MI, MachineInstr *&OtherMI)
Try to combine G_[SU]DIV and G_[SU]REM into a single G_[SU]DIVREM when their source operands are identical.
void applyCombineDivRem (MachineInstr &MI, MachineInstr *&OtherMI)
bool matchOptBrCondByInvertingCond (MachineInstr &MI, MachineInstr *&BrCond)
If a brcond's true block is not the fallthrough, make it so by inverting the condition and swapping operands.
void applyOptBrCondByInvertingCond (MachineInstr &MI, MachineInstr *&BrCond)
bool matchCombineConcatVectors (MachineInstr &MI, SmallVector< Register > &Ops)
If MI is G_CONCAT_VECTORS, try to combine it.
void applyCombineConcatVectors (MachineInstr &MI, SmallVector< Register > &Ops)
Replace MI with a flattened build_vector with Ops or an implicit_def if Ops is empty.
bool matchCombineShuffleConcat (MachineInstr &MI, SmallVector< Register > &Ops)
void applyCombineShuffleConcat (MachineInstr &MI, SmallVector< Register > &Ops)
Replace MI with a flattened build_vector with Ops or an implicit_def if Ops is empty.
bool tryCombineShuffleVector (MachineInstr &MI)
Try to combine G_SHUFFLE_VECTOR into G_CONCAT_VECTORS.
bool matchCombineShuffleVector (MachineInstr &MI, SmallVectorImpl< Register > &Ops)
Check if the G_SHUFFLE_VECTOR MI can be replaced by a concat_vectors.
void applyCombineShuffleVector (MachineInstr &MI, const ArrayRef< Register > Ops)
Replace MI with a concat_vectors with Ops.
bool matchShuffleToExtract (MachineInstr &MI)
void applyShuffleToExtract (MachineInstr &MI)
bool tryCombineMemCpyFamily (MachineInstr &MI, unsigned MaxLen=0)
Optimize memcpy intrinsics et al, e.g.
bool matchPtrAddImmedChain (MachineInstr &MI, PtrAddChain &MatchInfo)
void applyPtrAddImmedChain (MachineInstr &MI, PtrAddChain &MatchInfo)
bool matchShiftImmedChain (MachineInstr &MI, RegisterImmPair &MatchInfo)
Fold (shift (shift base, x), y) -> (shift base (x+y))
void applyShiftImmedChain (MachineInstr &MI, RegisterImmPair &MatchInfo)
bool matchShiftOfShiftedLogic (MachineInstr &MI, ShiftOfShiftedLogic &MatchInfo)
If we have a shift-by-constant of a bitwise logic op that itself has a shift-by-constant operand with identical opcode, we may be able to convert that into 2 independent shifts followed by the logic op.
void applyShiftOfShiftedLogic (MachineInstr &MI, ShiftOfShiftedLogic &MatchInfo)
bool matchCommuteShift (MachineInstr &MI, BuildFnTy &MatchInfo)
bool matchCombineMulToShl (MachineInstr &MI, unsigned &ShiftVal)
Transform a multiply by a power-of-2 value to a left shift.
void applyCombineMulToShl (MachineInstr &MI, unsigned &ShiftVal)
bool matchCombineShlOfExtend (MachineInstr &MI, RegisterImmPair &MatchData)
void applyCombineShlOfExtend (MachineInstr &MI, const RegisterImmPair &MatchData)
bool matchCombineMergeUnmerge (MachineInstr &MI, Register &MatchInfo)
Fold away a merge of an unmerge of the corresponding values.
bool matchCombineShiftToUnmerge (MachineInstr &MI, unsigned TargetShiftSize, unsigned &ShiftVal)
Reduce a shift by a constant to an unmerge and a shift on a half sized type.
void applyCombineShiftToUnmerge (MachineInstr &MI, const unsigned &ShiftVal)
bool tryCombineShiftToUnmerge (MachineInstr &MI, unsigned TargetShiftAmount)
bool matchCombineUnmergeMergeToPlainValues (MachineInstr &MI, SmallVectorImpl< Register > &Operands)
Transform <ty,...> G_UNMERGE(G_MERGE ty X, Y, Z) -> ty X, Y, Z.
void applyCombineUnmergeMergeToPlainValues (MachineInstr &MI, SmallVectorImpl< Register > &Operands)
bool matchCombineUnmergeConstant (MachineInstr &MI, SmallVectorImpl< APInt > &Csts)
Transform G_UNMERGE Constant -> Constant1, Constant2, ...
void applyCombineUnmergeConstant (MachineInstr &MI, SmallVectorImpl< APInt > &Csts)
bool matchCombineUnmergeUndef (MachineInstr &MI, std::function< void(MachineIRBuilder &)> &MatchInfo)
Transform G_UNMERGE G_IMPLICIT_DEF -> G_IMPLICIT_DEF, G_IMPLICIT_DEF, ...
bool matchCombineUnmergeWithDeadLanesToTrunc (MachineInstr &MI)
Transform X, Y<dead> = G_UNMERGE Z -> X = G_TRUNC Z.
void applyCombineUnmergeWithDeadLanesToTrunc (MachineInstr &MI)
bool matchCombineUnmergeZExtToZExt (MachineInstr &MI)
Transform X, Y = G_UNMERGE(G_ZEXT(Z)) -> X = G_ZEXT(Z); Y = G_CONSTANT 0.
void applyCombineUnmergeZExtToZExt (MachineInstr &MI)
void applyCombineConstantFoldFpUnary (MachineInstr &MI, const ConstantFP *Cst)
Transform fp_instr(cst) to constant result of the fp operation.
bool matchCombineI2PToP2I (MachineInstr &MI, Register &Reg)
Transform IntToPtr(PtrToInt(x)) to x if cast is in the same address space.
void applyCombineI2PToP2I (MachineInstr &MI, Register &Reg)
void applyCombineP2IToI2P (MachineInstr &MI, Register &Reg)
Transform PtrToInt(IntToPtr(x)) to x.
bool matchCombineAddP2IToPtrAdd (MachineInstr &MI, std::pair< Register, bool > &PtrRegAndCommute)
Transform G_ADD (G_PTRTOINT x), y -> G_PTRTOINT (G_PTR_ADD x, y) Transform G_ADD y, (G_PTRTOINT x) -> G_PTRTOINT (G_PTR_ADD x, y)
void applyCombineAddP2IToPtrAdd (MachineInstr &MI, std::pair< Register, bool > &PtrRegAndCommute)
bool matchCombineConstPtrAddToI2P (MachineInstr &MI, APInt &NewCst)
void applyCombineConstPtrAddToI2P (MachineInstr &MI, APInt &NewCst)
bool matchCombineAnyExtTrunc (MachineInstr &MI, Register &Reg)
Transform anyext(trunc(x)) to x.
bool matchCombineZextTrunc (MachineInstr &MI, Register &Reg)
Transform zext(trunc(x)) to x.
bool matchCombineExtOfExt (MachineInstr &MI, std::tuple< Register, unsigned > &MatchInfo)
Transform [asz]ext([asz]ext(x)) to [asz]ext x.
void applyCombineExtOfExt (MachineInstr &MI, std::tuple< Register, unsigned > &MatchInfo)
bool matchCombineTruncOfExt (MachineInstr &MI, std::pair< Register, unsigned > &MatchInfo)
Transform trunc ([asz]ext x) to x or ([asz]ext x) or (trunc x).
void applyCombineTruncOfExt (MachineInstr &MI, std::pair< Register, unsigned > &MatchInfo)
bool matchCombineTruncOfShift (MachineInstr &MI, std::pair< MachineInstr *, LLT > &MatchInfo)
Transform trunc (shl x, K) to shl (trunc x), K if K < VT.getScalarSizeInBits().
void applyCombineTruncOfShift (MachineInstr &MI, std::pair< MachineInstr *, LLT > &MatchInfo)
bool matchAnyExplicitUseIsUndef (MachineInstr &MI)
Return true if any explicit use operand on MI is defined by a G_IMPLICIT_DEF.
bool matchAllExplicitUsesAreUndef (MachineInstr &MI)
Return true if all register explicit use operands on MI are defined by a G_IMPLICIT_DEF.
bool matchUndefShuffleVectorMask (MachineInstr &MI)
Return true if a G_SHUFFLE_VECTOR instruction MI has an undef mask.
bool matchUndefStore (MachineInstr &MI)
Return true if a G_STORE instruction MI is storing an undef value.
bool matchUndefSelectCmp (MachineInstr &MI)
Return true if a G_SELECT instruction MI has an undef comparison.
bool matchInsertExtractVecEltOutOfBounds (MachineInstr &MI)
Return true if a G_{EXTRACT,INSERT}_VECTOR_ELT has an out of range index.
bool matchConstantSelectCmp (MachineInstr &MI, unsigned &OpIdx)
Return true if a G_SELECT instruction MI has a constant comparison.
void replaceInstWithFConstant (MachineInstr &MI, double C)
Replace an instruction with a G_FCONSTANT with value C.
void replaceInstWithFConstant (MachineInstr &MI, ConstantFP *CFP)
Replace an instruction with an G_FCONSTANT with value CFP.
void replaceInstWithConstant (MachineInstr &MI, int64_t C)
Replace an instruction with a G_CONSTANT with value C.
void replaceInstWithConstant (MachineInstr &MI, APInt C)
Replace an instruction with a G_CONSTANT with value C.
void replaceInstWithUndef (MachineInstr &MI)
Replace an instruction with a G_IMPLICIT_DEF.
void replaceSingleDefInstWithOperand (MachineInstr &MI, unsigned OpIdx)
Delete MI and replace all of its uses with its OpIdx-th operand.
void replaceSingleDefInstWithReg (MachineInstr &MI, Register Replacement)
Delete MI and replace all of its uses with Replacement.
void applyFunnelShiftConstantModulo (MachineInstr &MI)
Replaces the shift amount in MI with ShiftAmt % BW.
bool matchEqualDefs (const MachineOperand &MOP1, const MachineOperand &MOP2)
Return true if MOP1 and MOP2 are register operands are defined by equivalent instructions.
bool matchConstantOp (const MachineOperand &MOP, int64_t C)
Return true if MOP is defined by a G_CONSTANT or splat with a value equal to C.
bool matchConstantFPOp (const MachineOperand &MOP, double C)
Return true if MOP is defined by a G_FCONSTANT or splat with a value exactly equal to C.
bool matchConstantLargerBitWidth (MachineInstr &MI, unsigned ConstIdx)
Checks if constant at ConstIdx is larger than MI 's bitwidth.
bool matchSelectSameVal (MachineInstr &MI)
Optimize (cond ? x : x) -> x.
bool matchBinOpSameVal (MachineInstr &MI)
Optimize (x op x) -> x.
bool matchOperandIsZero (MachineInstr &MI, unsigned OpIdx)
Check if operand OpIdx is zero.
bool matchOperandIsUndef (MachineInstr &MI, unsigned OpIdx)
Check if operand OpIdx is undef.
bool matchOperandIsKnownToBeAPowerOfTwo (MachineInstr &MI, unsigned OpIdx)
Check if operand OpIdx is known to be a power of 2.
void eraseInst (MachineInstr &MI)
Erase MI.
bool matchSimplifyAddToSub (MachineInstr &MI, std::tuple< Register, Register > &MatchInfo)
Return true if MI is a G_ADD which can be simplified to a G_SUB.
void applySimplifyAddToSub (MachineInstr &MI, std::tuple< Register, Register > &MatchInfo)
bool matchHoistLogicOpWithSameOpcodeHands (MachineInstr &MI, InstructionStepsMatchInfo &MatchInfo)
Match (logic_op (op x...), (op y...)) -> (op (logic_op x, y))
void applyBuildInstructionSteps (MachineInstr &MI, InstructionStepsMatchInfo &MatchInfo)
Replace MI with a series of instructions described in MatchInfo.
bool matchAshrShlToSextInreg (MachineInstr &MI, std::tuple< Register, int64_t > &MatchInfo)
Match ashr (shl x, C), C -> sext_inreg (C)
void applyAshShlToSextInreg (MachineInstr &MI, std::tuple< Register, int64_t > &MatchInfo)
bool matchOverlappingAnd (MachineInstr &MI, BuildFnTy &MatchInfo)
Fold and(and(x, C1), C2) -> C1&C2 ? and(x, C1&C2) : 0.
bool matchRedundantAnd (MachineInstr &MI, Register &Replacement)
bool matchRedundantOr (MachineInstr &MI, Register &Replacement)
bool matchRedundantSExtInReg (MachineInstr &MI)
bool matchNotCmp (MachineInstr &MI, SmallVectorImpl< Register > &RegsToNegate)
Combine inverting a result of a compare into the opposite cond code.
void applyNotCmp (MachineInstr &MI, SmallVectorImpl< Register > &RegsToNegate)
bool matchXorOfAndWithSameReg (MachineInstr &MI, std::pair< Register, Register > &MatchInfo)
Fold (xor (and x, y), y) -> (and (not x), y) {.
void applyXorOfAndWithSameReg (MachineInstr &MI, std::pair< Register, Register > &MatchInfo)
bool matchPtrAddZero (MachineInstr &MI)
}
void applyPtrAddZero (MachineInstr &MI)
void applySimplifyURemByPow2 (MachineInstr &MI)
Combine G_UREM x, (known power of 2) to an add and bitmasking.
bool matchFoldBinOpIntoSelect (MachineInstr &MI, unsigned &SelectOpNo)
Push a binary operator through a select on constants.
void applyFoldBinOpIntoSelect (MachineInstr &MI, const unsigned &SelectOpNo)
SelectOperand is the operand in binary operator MI that is the select to fold.
bool matchCombineInsertVecElts (MachineInstr &MI, SmallVectorImpl< Register > &MatchInfo)
void applyCombineInsertVecElts (MachineInstr &MI, SmallVectorImpl< Register > &MatchInfo)
bool matchLoadOrCombine (MachineInstr &MI, BuildFnTy &MatchInfo)
Match expression trees of the form.
bool matchExtendThroughPhis (MachineInstr &MI, MachineInstr *&ExtMI)
void applyExtendThroughPhis (MachineInstr &MI, MachineInstr *&ExtMI)
bool matchExtractVecEltBuildVec (MachineInstr &MI, Register &Reg)
void applyExtractVecEltBuildVec (MachineInstr &MI, Register &Reg)
bool matchExtractAllEltsFromBuildVector (MachineInstr &MI, SmallVectorImpl< std::pair< Register, MachineInstr * > > &MatchInfo)
void applyExtractAllEltsFromBuildVector (MachineInstr &MI, SmallVectorImpl< std::pair< Register, MachineInstr * > > &MatchInfo)
void applyBuildFn (MachineInstr &MI, BuildFnTy &MatchInfo)
Use a function which takes in a MachineIRBuilder to perform a combine.
void applyBuildFnNoErase (MachineInstr &MI, BuildFnTy &MatchInfo)
Use a function which takes in a MachineIRBuilder to perform a combine.
bool matchOrShiftToFunnelShift (MachineInstr &MI, BuildFnTy &MatchInfo)
bool matchFunnelShiftToRotate (MachineInstr &MI)
Match an FSHL or FSHR that can be combined to a ROTR or ROTL rotate.
void applyFunnelShiftToRotate (MachineInstr &MI)
bool matchRotateOutOfRange (MachineInstr &MI)
void applyRotateOutOfRange (MachineInstr &MI)
bool matchICmpToTrueFalseKnownBits (MachineInstr &MI, int64_t &MatchInfo)
bool matchICmpToLHSKnownBits (MachineInstr &MI, BuildFnTy &MatchInfo)
bool matchAndOrDisjointMask (MachineInstr &MI, BuildFnTy &MatchInfo)
bool matchBitfieldExtractFromSExtInReg (MachineInstr &MI, BuildFnTy &MatchInfo)
Form a G_SBFX from a G_SEXT_INREG fed by a right shift.
bool matchBitfieldExtractFromAnd (MachineInstr &MI, BuildFnTy &MatchInfo)
Match: and (lshr x, cst), mask -> ubfx x, cst, width.
bool matchBitfieldExtractFromShr (MachineInstr &MI, BuildFnTy &MatchInfo)
Match: shr (shl x, n), k -> sbfx/ubfx x, pos, width.
bool matchBitfieldExtractFromShrAnd (MachineInstr &MI, BuildFnTy &MatchInfo)
Match: shr (and x, n), k -> ubfx x, pos, width.
bool matchReassocConstantInnerRHS (GPtrAdd &MI, MachineInstr *RHS, BuildFnTy &MatchInfo)
bool matchReassocFoldConstantsInSubTree (GPtrAdd &MI, MachineInstr *LHS, MachineInstr *RHS, BuildFnTy &MatchInfo)
bool matchReassocConstantInnerLHS (GPtrAdd &MI, MachineInstr *LHS, MachineInstr *RHS, BuildFnTy &MatchInfo)
bool matchReassocPtrAdd (MachineInstr &MI, BuildFnTy &MatchInfo)
Reassociate pointer calculations with G_ADD involved, to allow better addressing mode usage.
bool tryReassocBinOp (unsigned Opc, Register DstReg, Register Op0, Register Op1, BuildFnTy &MatchInfo)
Try to reassociate to reassociate operands of a commutative binop.
bool matchReassocCommBinOp (MachineInstr &MI, BuildFnTy &MatchInfo)
Reassociate commutative binary operations like G_ADD.
bool matchConstantFoldCastOp (MachineInstr &MI, APInt &MatchInfo)
Do constant folding when opportunities are exposed after MIR building.
bool matchConstantFoldBinOp (MachineInstr &MI, APInt &MatchInfo)
Do constant folding when opportunities are exposed after MIR building.
bool matchConstantFoldFPBinOp (MachineInstr &MI, ConstantFP *&MatchInfo)
Do constant FP folding when opportunities are exposed after MIR building.
bool matchConstantFoldFMA (MachineInstr &MI, ConstantFP *&MatchInfo)
Constant fold G_FMA/G_FMAD.
bool matchNarrowBinopFeedingAnd (MachineInstr &MI, BuildFnTy &MatchInfo)
MachineInstr * buildUDivUsingMul (MachineInstr &MI)
Given an G_UDIV MI expressing a divide by constant, return an expression that implements it by multiplying by a magic number.
bool matchUDivByConst (MachineInstr &MI)
Combine G_UDIV by constant into a multiply by magic constant.
void applyUDivByConst (MachineInstr &MI)
MachineInstr * buildSDivUsingMul (MachineInstr &MI)
Given an G_SDIV MI expressing a signed divide by constant, return an expression that implements it by multiplying by a magic number.
bool matchSDivByConst (MachineInstr &MI)
void applySDivByConst (MachineInstr &MI)
bool matchDivByPow2 (MachineInstr &MI, bool IsSigned)
Given an G_SDIV MI expressing a signed divided by a pow2 constant, return expressions that implements it by shifting.
void applySDivByPow2 (MachineInstr &MI)
void applyUDivByPow2 (MachineInstr &MI)
Given an G_UDIV MI expressing an unsigned divided by a pow2 constant, return expressions that implements it by shifting.
bool matchUMulHToLShr (MachineInstr &MI)
void applyUMulHToLShr (MachineInstr &MI)
bool tryCombine (MachineInstr &MI)
Try to transform MI by using all of the above combine functions.
bool tryEmitMemcpyInline (MachineInstr &MI)
Emit loads and stores that perform the given memcpy.
bool matchMulOBy2 (MachineInstr &MI, BuildFnTy &MatchInfo)
Match: (G_UMULO x, 2) -> (G_UADDO x, x) (G_SMULO x, 2) -> (G_SADDO x, x)
bool matchMulOBy0 (MachineInstr &MI, BuildFnTy &MatchInfo)
Match: (G_*MULO x, 0) -> 0 + no carry out.
bool matchAddEToAddO (MachineInstr &MI, BuildFnTy &MatchInfo)
Match: (G_*ADDE x, y, 0) -> (G_*ADDO x, y) (G_*SUBE x, y, 0) -> (G_*SUBO x, y)
bool matchRedundantNegOperands (MachineInstr &MI, BuildFnTy &MatchInfo)
Transform (fadd x, fneg(y)) -> (fsub x, y) (fadd fneg(x), y) -> (fsub y, x) (fsub x, fneg(y)) -> (fadd x, y) (fmul fneg(x), fneg(y)) -> (fmul x, y) (fdiv fneg(x), fneg(y)) -> (fdiv x, y) (fmad fneg(x), fneg(y), z) -> (fmad x, y, z) (fma fneg(x), fneg(y), z) -> (fma x, y, z)
bool matchFsubToFneg (MachineInstr &MI, Register &MatchInfo)
void applyFsubToFneg (MachineInstr &MI, Register &MatchInfo)
bool canCombineFMadOrFMA (MachineInstr &MI, bool &AllowFusionGlobally, bool &HasFMAD, bool &Aggressive, bool CanReassociate=false)
bool matchCombineFAddFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo)
Transform (fadd (fmul x, y), z) -> (fma x, y, z) (fadd (fmul x, y), z) -> (fmad x, y, z)
bool matchCombineFAddFpExtFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo)
Transform (fadd (fpext (fmul x, y)), z) -> (fma (fpext x), (fpext y), z) (fadd (fpext (fmul x, y)), z) -> (fmad (fpext x), (fpext y), z)
bool matchCombineFAddFMAFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo)
Transform (fadd (fma x, y, (fmul u, v)), z) -> (fma x, y, (fma u, v, z)) (fadd (fmad x, y, (fmul u, v)), z) -> (fmad x, y, (fmad u, v, z))
bool matchCombineFAddFpExtFMulToFMadOrFMAAggressive (MachineInstr &MI, BuildFnTy &MatchInfo)
bool matchCombineFSubFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo)
Transform (fsub (fmul x, y), z) -> (fma x, y, -z) (fsub (fmul x, y), z) -> (fmad x, y, -z)
bool matchCombineFSubFNegFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo)
Transform (fsub (fneg (fmul, x, y)), z) -> (fma (fneg x), y, (fneg z)) (fsub (fneg (fmul, x, y)), z) -> (fmad (fneg x), y, (fneg z))
bool matchCombineFSubFpExtFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo)
Transform (fsub (fpext (fmul x, y)), z) -> (fma (fpext x), (fpext y), (fneg z)) (fsub (fpext (fmul x, y)), z) -> (fmad (fpext x), (fpext y), (fneg z))
bool matchCombineFSubFpExtFNegFMulToFMadOrFMA (MachineInstr &MI, BuildFnTy &MatchInfo)
Transform (fsub (fpext (fneg (fmul x, y))), z) -> (fneg (fma (fpext x), (fpext y), z)) (fsub (fpext (fneg (fmul x, y))), z) -> (fneg (fmad (fpext x), (fpext y), z))
bool matchCombineFMinMaxNaN (MachineInstr &MI, unsigned &Info)
bool matchAddSubSameReg (MachineInstr &MI, Register &Src)
Transform G_ADD(x, G_SUB(y, x)) to y.
bool matchBuildVectorIdentityFold (MachineInstr &MI, Register &MatchInfo)
bool matchTruncBuildVectorFold (MachineInstr &MI, Register &MatchInfo)
bool matchTruncLshrBuildVectorFold (MachineInstr &MI, Register &MatchInfo)
bool matchSubAddSameReg (MachineInstr &MI, BuildFnTy &MatchInfo)
Transform: (x + y) - y -> x (x + y) - x -> y x - (y + x) -> 0 - y x - (x + z) -> 0 - z.
bool matchSimplifySelectToMinMax (MachineInstr &MI, BuildFnTy &MatchInfo)
bool matchRedundantBinOpInEquality (MachineInstr &MI, BuildFnTy &MatchInfo)
Transform: (X + Y) == X -> Y == 0 (X - Y) == X -> Y == 0 (X ^ Y) == X -> Y == 0 (X + Y) != X -> Y != 0 (X - Y) != X -> Y != 0 (X ^ Y) != X -> Y != 0.
bool matchShiftsTooBig (MachineInstr &MI)
Match shifts greater or equal to the bitwidth of the operation.
bool matchCommuteConstantToRHS (MachineInstr &MI)
Match constant LHS ops that should be commuted.
bool matchSextOfTrunc (const MachineOperand &MO, BuildFnTy &MatchInfo)
Combine sext of trunc.
bool matchZextOfTrunc (const MachineOperand &MO, BuildFnTy &MatchInfo)
Combine zext of trunc.
bool matchNonNegZext (const MachineOperand &MO, BuildFnTy &MatchInfo)
Combine zext nneg to sext.
bool matchCommuteFPConstantToRHS (MachineInstr &MI)
Match constant LHS FP ops that should be commuted.
void applyCommuteBinOpOperands (MachineInstr &MI)
bool matchSelectIMinMax (const MachineOperand &MO, BuildFnTy &MatchInfo)
Combine select to integer min/max.
bool matchSelect (MachineInstr &MI, BuildFnTy &MatchInfo)
Combine selects.
bool matchAnd (MachineInstr &MI, BuildFnTy &MatchInfo)
Combine ands.
bool matchOr (MachineInstr &MI, BuildFnTy &MatchInfo)
Combine ors.
bool matchAddOverflow (MachineInstr &MI, BuildFnTy &MatchInfo)
Combine addos.
bool matchExtractVectorElement (MachineInstr &MI, BuildFnTy &MatchInfo)
Combine extract vector element.
bool matchExtractVectorElementWithBuildVector (const MachineOperand &MO, BuildFnTy &MatchInfo)
Combine extract vector element with a build vector on the vector register.
bool matchExtractVectorElementWithBuildVectorTrunc (const MachineOperand &MO, BuildFnTy &MatchInfo)
Combine extract vector element with a build vector trunc on the vector register.
bool matchExtractVectorElementWithShuffleVector (const MachineOperand &MO, BuildFnTy &MatchInfo)
Combine extract vector element with a shuffle vector on the vector register.
bool matchExtractVectorElementWithDifferentIndices (const MachineOperand &MO, BuildFnTy &MatchInfo)
Combine extract vector element with a insert vector element on the vector register and different indices.
void applyBuildFnMO (const MachineOperand &MO, BuildFnTy &MatchInfo)
Use a function which takes in a MachineIRBuilder to perform a combine.
bool matchFPowIExpansion (MachineInstr &MI, int64_t Exponent)
Match FPOWI if it's safe to extend it into a series of multiplications.
void applyExpandFPowI (MachineInstr &MI, int64_t Exponent)
Expands FPOWI into a series of multiplications and a division if the exponent is negative.
bool matchInsertVectorElementOOB (MachineInstr &MI, BuildFnTy &MatchInfo)
Combine insert vector element OOB.
bool matchFreezeOfSingleMaybePoisonOperand (MachineInstr &MI, BuildFnTy &MatchInfo)
bool matchAddOfVScale (const MachineOperand &MO, BuildFnTy &MatchInfo)
bool matchMulOfVScale (const MachineOperand &MO, BuildFnTy &MatchInfo)
bool matchSubOfVScale (const MachineOperand &MO, BuildFnTy &MatchInfo)
bool matchShlOfVScale (const MachineOperand &MO, BuildFnTy &MatchInfo)
Protected Attributes
MachineIRBuilder & Builder
MachineRegisterInfo & MRI
GISelChangeObserver & Observer
GISelKnownBits * KB
MachineDominatorTree * MDT
bool IsPreLegalize
const LegalizerInfo * LI
const RegisterBankInfo * RBI
const TargetRegisterInfo * TRI
Detailed Description
Definition at line 103 of file CombinerHelper.h.
Constructor & Destructor Documentation
CombinerHelper()
CombinerHelper::CombinerHelper (GISelChangeObserver & Observer, MachineIRBuilder & B, bool IsPreLegalize, GISelKnownBits * KB = nullptr, MachineDominatorTree * MDT = nullptr, const LegalizerInfo * LI = nullptr)
Definition at line 56 of file CombinerHelper.cpp.
References KB.
Member Function Documentation
applyAshShlToSextInreg()
void CombinerHelper::applyAshShlToSextInreg (MachineInstr & MI, std::tuple< Register, int64_t > & MatchInfo)
Definition at line 3244 of file CombinerHelper.cpp.
References assert(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), MI, MRI, and Size.
applyBuildFn()
void CombinerHelper::applyBuildFn (MachineInstr & MI, BuildFnTy & MatchInfo)
Use a function which takes in a MachineIRBuilder to perform a combine.
By default, it erases the instruction MI from the function.
Definition at line 4225 of file CombinerHelper.cpp.
References applyBuildFnNoErase(), and MI.
applyBuildFnMO()
void CombinerHelper::applyBuildFnMO (const MachineOperand & MO, BuildFnTy & MatchInfo)
Use a function which takes in a MachineIRBuilder to perform a combine.
By default, it erases the instruction def'd on MO from the function.
Definition at line 7406 of file CombinerHelper.cpp.
References llvm::MachineInstr::eraseFromParent(), llvm::getDefIgnoringCopies(), llvm::MachineOperand::getReg(), and MRI.
applyBuildFnNoErase()
void CombinerHelper::applyBuildFnNoErase (MachineInstr & MI, BuildFnTy & MatchInfo)
Use a function which takes in a MachineIRBuilder to perform a combine.
This variant does not erase MI after calling the build function.
Definition at line 4231 of file CombinerHelper.cpp.
Referenced by applyBuildFn().
applyBuildInstructionSteps()
void CombinerHelper::applyBuildInstructionSteps (MachineInstr & MI, InstructionStepsMatchInfo & MatchInfo)
Replace MI with a series of instructions described in MatchInfo.
Definition at line 3212 of file CombinerHelper.cpp.
References assert(), llvm::InstructionStepsMatchInfo::InstrsToBuild, and MI.
applyCombineAddP2IToPtrAdd()
void CombinerHelper::applyCombineAddP2IToPtrAdd (MachineInstr & MI, std::pair< Register, bool > & PtrRegAndCommute)
Definition at line 2457 of file CombinerHelper.cpp.
References llvm::MachineRegisterInfo::getType(), MI, MRI, and std::swap().
applyCombineConcatVectors()
void CombinerHelper::applyCombineConcatVectors (MachineInstr & MI, SmallVector< Register > & Ops)
Replace MI with a flattened build_vector with Ops or an implicit_def if Ops is empty.
Definition at line 354 of file CombinerHelper.cpp.
References llvm::MachineRegisterInfo::cloneVirtualRegister(), llvm::SmallVectorBase< Size_T >::empty(), MI, MRI, and replaceRegWith().
applyCombineConstantFoldFpUnary()
void CombinerHelper::applyCombineConstantFoldFpUnary (MachineInstr & MI, const ConstantFP * Cst)
Transform fp_instr(cst) to constant result of the fp operation.
Definition at line 1693 of file CombinerHelper.cpp.
References constantFoldFpUnary(), llvm::ConstantFP::getValue(), MI, and MRI.
applyCombineConstPtrAddToI2P()
void CombinerHelper::applyCombineConstPtrAddToI2P (MachineInstr & MI, APInt & NewCst)
Definition at line 2496 of file CombinerHelper.cpp.
References llvm::cast(), and MI.
applyCombineCopy()
void CombinerHelper::applyCombineCopy (MachineInstr & MI)
Definition at line 219 of file CombinerHelper.cpp.
References MI, MRI, and replaceRegWith().
Referenced by tryCombineCopy().
applyCombineDivRem()
void CombinerHelper::applyCombineDivRem (MachineInstr & MI, MachineInstr *& OtherMI)
Definition at line 1540 of file CombinerHelper.cpp.
References assert(), dominates(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and MI.
applyCombineExtendingLoads()
void CombinerHelper::applyCombineExtendingLoads (MachineInstr & MI, PreferredTuple & MatchInfo)
rewrites to:
rewrites to:
Definition at line 780 of file CombinerHelper.cpp.
References llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineRegisterInfo::cloneVirtualRegister(), llvm::MachineInstr::eraseFromParent(), llvm::GISelChangeObserver::erasingInstr(), llvm::PreferredTuple::ExtendOpcode, getExtLoadOpcForExtend(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::PreferredTuple::MI, MI, MRI, Observer, replaceRegOpWith(), replaceRegWith(), llvm::MachineOperand::setReg(), llvm::PreferredTuple::Ty, llvm::MachineRegisterInfo::use_operands(), UseMI, and Uses.
Referenced by tryCombineExtendingLoads().
applyCombineExtOfExt()
void CombinerHelper::applyCombineExtOfExt (MachineInstr & MI, std::tuple< Register, unsigned > & MatchInfo)
Definition at line 2555 of file CombinerHelper.cpp.
References assert(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), MI, and Observer.
applyCombineI2PToP2I()
void CombinerHelper::applyCombineI2PToP2I (MachineInstr & MI, Register & Reg)
Definition at line 2418 of file CombinerHelper.cpp.
References assert(), and MI.
applyCombineIndexedLoadStore()
void CombinerHelper::applyCombineIndexedLoadStore (MachineInstr & MI, IndexedLoadStoreMatchInfo & MatchInfo)
Definition at line 1442 of file CombinerHelper.cpp.
References llvm::IndexedLoadStoreMatchInfo::Addr, llvm::IndexedLoadStoreMatchInfo::Base, llvm::dbgs(), llvm::MachineInstr::eraseFromParent(), getIndexedOpc(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::MachineRegisterInfo::getVRegDef(), llvm::IndexedLoadStoreMatchInfo::IsPre, LLVM_DEBUG, MI, MRI, llvm::IndexedLoadStoreMatchInfo::Offset, and llvm::IndexedLoadStoreMatchInfo::RematOffset.
applyCombineInsertVecElts()
void CombinerHelper::applyCombineInsertVecElts (MachineInstr & MI, SmallVectorImpl< Register > & MatchInfo)
Definition at line 3078 of file CombinerHelper.cpp.
References llvm::LLT::getScalarType(), llvm::MachineRegisterInfo::getType(), MI, and MRI.
applyCombineMulToShl()
void CombinerHelper::applyCombineMulToShl (MachineInstr & MI, unsigned & ShiftVal)
Definition at line 2020 of file CombinerHelper.cpp.
References assert(), llvm::MachineIRBuilder::buildConstant(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MCInstrInfo::get(), llvm::MachineIRBuilder::getTII(), llvm::MachineRegisterInfo::getType(), MI, MRI, and Observer.
applyCombineP2IToI2P()
void CombinerHelper::applyCombineP2IToI2P (MachineInstr & MI, Register & Reg)
Transform PtrToInt(IntToPtr(x)) to x.
Definition at line 2425 of file CombinerHelper.cpp.
References assert(), and MI.
applyCombineShiftToUnmerge()
void CombinerHelper::applyCombineShiftToUnmerge (MachineInstr & MI, const unsigned & ShiftVal)
Definition at line 2326 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::getType(), llvm::Hi, llvm::Lo, MI, MRI, llvm::LLT::scalar(), and Size.
Referenced by tryCombineShiftToUnmerge().
applyCombineShlOfExtend()
void CombinerHelper::applyCombineShlOfExtend (MachineInstr & MI, const RegisterImmPair & MatchData)
Definition at line 2073 of file CombinerHelper.cpp.
References llvm::MachineRegisterInfo::getType(), llvm::RegisterImmPair::Imm, MI, MRI, and llvm::RegisterImmPair::Reg.
applyCombineShuffleConcat()
void CombinerHelper::applyCombineShuffleConcat (MachineInstr & MI, SmallVector< Register > & Ops)
Replace MI with a flattened build_vector with Ops or an implicit_def if Ops is empty.
Definition at line 436 of file CombinerHelper.cpp.
References llvm::MachineRegisterInfo::getType(), MI, MRI, and llvm::SmallVectorBase< Size_T >::size().
applyCombineShuffleVector()
void CombinerHelper::applyCombineShuffleVector (MachineInstr & MI, const ArrayRef< Register > Ops)
Replace MI with a concat_vectors with Ops.
Definition at line 541 of file CombinerHelper.cpp.
References llvm::MachineRegisterInfo::cloneVirtualRegister(), MI, MRI, replaceRegWith(), and llvm::ArrayRef< T >::size().
Referenced by tryCombineShuffleVector().
applyCombineTruncOfExt()
void CombinerHelper::applyCombineTruncOfExt (MachineInstr & MI, std::pair< Register, unsigned > & MatchInfo)
Definition at line 2599 of file CombinerHelper.cpp.
References assert(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), MI, MRI, and replaceRegWith().
applyCombineTruncOfShift()
void CombinerHelper::applyCombineTruncOfShift (MachineInstr & MI, std::pair< MachineInstr *, LLT > & MatchInfo)
Definition at line 2697 of file CombinerHelper.cpp.
References eraseInst(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), MI, MRI, and replaceRegWith().
applyCombineUnmergeConstant()
void CombinerHelper::applyCombineUnmergeConstant (MachineInstr & MI, SmallVectorImpl< APInt > & Csts)
Definition at line 2193 of file CombinerHelper.cpp.
References assert(), MI, and llvm::SmallVectorBase< Size_T >::size().
applyCombineUnmergeMergeToPlainValues()
void CombinerHelper::applyCombineUnmergeMergeToPlainValues (MachineInstr & MI, SmallVectorImpl< Register > & Operands)
Definition at line 2137 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::getRegClassOrRegBank(), llvm::MachineRegisterInfo::getType(), MI, MRI, Operands, replaceRegWith(), and llvm::MachineRegisterInfo::setRegClassOrRegBank().
applyCombineUnmergeWithDeadLanesToTrunc()
void CombinerHelper::applyCombineUnmergeWithDeadLanesToTrunc (MachineInstr & MI)
Definition at line 2236 of file CombinerHelper.cpp.
References MI.
applyCombineUnmergeZExtToZExt()
void CombinerHelper::applyCombineUnmergeZExtToZExt (MachineInstr & MI)
Definition at line 2269 of file CombinerHelper.cpp.
References assert(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), MI, MRI, and replaceRegWith().
applyCommuteBinOpOperands()
void CombinerHelper::applyCommuteBinOpOperands (MachineInstr & MI)
Definition at line 6559 of file CombinerHelper.cpp.
References llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), MI, and Observer.
applyExpandFPowI()
void CombinerHelper::applyExpandFPowI (MachineInstr & MI, int64_t Exponent)
Expands FPOWI into a series of multiplications and a division if the exponent is negative.
Definition at line 7418 of file CombinerHelper.cpp.
References llvm::sampleprof::Base, llvm::Exponent, llvm::MachineRegisterInfo::getType(), MI, and MRI.
applyExtendThroughPhis()
void CombinerHelper::applyExtendThroughPhis (MachineInstr & MI, MachineInstr *& ExtMI)
Definition at line 4075 of file CombinerHelper.cpp.
References llvm::cast(), llvm::drop_begin(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineBasicBlock::getFirstNonPHI(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), I, llvm::SetVector< T, Vector, Set, N >::insert(), MBB, MI, MRI, and PHI.
applyExtractAllEltsFromBuildVector()
void CombinerHelper::applyExtractAllEltsFromBuildVector (MachineInstr & MI, SmallVectorImpl< std::pair< Register, MachineInstr * > > & MatchInfo)
Definition at line 4213 of file CombinerHelper.cpp.
References assert(), MI, MRI, and replaceRegWith().
applyExtractVecEltBuildVec()
void CombinerHelper::applyExtractVecEltBuildVec (MachineInstr & MI, Register & Reg)
Definition at line 4154 of file CombinerHelper.cpp.
References assert(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), MI, MRI, and replaceSingleDefInstWithReg().
applyFoldBinOpIntoSelect()
void CombinerHelper::applyFoldBinOpIntoSelect (MachineInstr & MI, const unsigned & SelectOpNo)
SelectOperand is the operand in binary operator MI that is the select to fold.
Definition at line 3640 of file CombinerHelper.cpp.
References getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), LHS, MI, MRI, and Select.
applyFsubToFneg()
void CombinerHelper::applyFsubToFneg (MachineInstr & MI, Register & MatchInfo)
Definition at line 5668 of file CombinerHelper.cpp.
References eraseInst(), llvm::MachineRegisterInfo::getType(), MI, and MRI.
applyFunnelShiftConstantModulo()
void CombinerHelper::applyFunnelShiftConstantModulo (MachineInstr & MI)
Replaces the shift amount in MI with ShiftAmt % BW.
Parameters
MI
Definition at line 2928 of file CombinerHelper.cpp.
References assert(), llvm::getIConstantVRegValWithLookThrough(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::APInt::getZExtValue(), MI, MRI, and llvm::APInt::urem().
applyFunnelShiftToRotate()
void CombinerHelper::applyFunnelShiftToRotate (MachineInstr & MI)
Definition at line 4302 of file CombinerHelper.cpp.
References assert(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), MI, and Observer.
applyNotCmp()
void CombinerHelper::applyNotCmp (MachineInstr & MI, SmallVectorImpl< Register > & RegsToNegate)
Definition at line 3471 of file CombinerHelper.cpp.
References llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::CmpInst::getInversePredicate(), llvm::MachineOperand::getPredicate(), llvm::MachineRegisterInfo::getVRegDef(), llvm_unreachable, MI, MRI, Observer, replaceRegWith(), and llvm::MachineOperand::setPredicate().
applyOptBrCondByInvertingCond()
void CombinerHelper::applyOptBrCondByInvertingCond (MachineInstr & MI, MachineInstr *& BrCond)
Definition at line 1606 of file CombinerHelper.cpp.
References llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::getICmpTrueVal(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), MI, MRI, Observer, llvm::MachineOperand::setMBB(), llvm::MachineOperand::setReg(), and llvm::Xor.
applyPtrAddImmedChain()
void CombinerHelper::applyPtrAddImmedChain (MachineInstr & MI, PtrAddChain & MatchInfo)
Definition at line 1763 of file CombinerHelper.cpp.
References assert(), llvm::PtrAddChain::Bank, llvm::PtrAddChain::Base, llvm::MachineIRBuilder::buildConstant(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineRegisterInfo::getType(), llvm::PtrAddChain::Imm, MI, MRI, Observer, and setRegBank().
applyPtrAddZero()
void CombinerHelper::applyPtrAddZero (MachineInstr & MI)
Definition at line 3566 of file CombinerHelper.cpp.
References llvm::cast(), and MI.
applyRotateOutOfRange()
void CombinerHelper::applyRotateOutOfRange (MachineInstr & MI)
Definition at line 4329 of file CombinerHelper.cpp.
References assert(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), MI, MRI, and Observer.
applySDivByConst()
void CombinerHelper::applySDivByConst (MachineInstr & MI)
Definition at line 5410 of file CombinerHelper.cpp.
References buildSDivUsingMul(), MI, and replaceSingleDefInstWithReg().
applySDivByPow2()
void CombinerHelper::applySDivByPow2 (MachineInstr & MI)
Definition at line 5493 of file CombinerHelper.cpp.
References llvm::Add, assert(), llvm::BitWidth, llvm::cast(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_SLT, llvm::LLT::isVector(), MI, MRI, llvm::LLT::scalar(), and llvm::LLT::vector().
applySextInRegOfLoad()
void CombinerHelper::applySextInRegOfLoad (MachineInstr & MI, std::tuple< Register, unsigned > & MatchInfo)
Definition at line 1081 of file CombinerHelper.cpp.
References assert(), llvm::cast(), llvm::GMemOperation::getMMO(), llvm::MachineMemOperand::getPointerInfo(), llvm::GLoadStore::getPointerReg(), llvm::MachineRegisterInfo::getVRegDef(), MI, and MRI.
applySextTruncSextLoad()
void CombinerHelper::applySextTruncSextLoad (MachineInstr & MI)
Definition at line 1023 of file CombinerHelper.cpp.
References assert(), and MI.
applyShiftImmedChain()
void CombinerHelper::applyShiftImmedChain (MachineInstr & MI, RegisterImmPair & MatchInfo)
Definition at line 1821 of file CombinerHelper.cpp.
References assert(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::RegisterImmPair::Imm, MI, MRI, Observer, and llvm::RegisterImmPair::Reg.
applyShiftOfShiftedLogic()
void CombinerHelper::applyShiftOfShiftedLogic (MachineInstr & MI, ShiftOfShiftedLogic & MatchInfo)
Definition at line 1934 of file CombinerHelper.cpp.
References assert(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getReg(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::ShiftOfShiftedLogic::Logic, llvm::ShiftOfShiftedLogic::LogicNonShiftReg, MI, MRI, llvm::ShiftOfShiftedLogic::Shift2, and llvm::ShiftOfShiftedLogic::ValSum.
applyShuffleToExtract()
void CombinerHelper::applyShuffleToExtract (MachineInstr & MI)
Definition at line 564 of file CombinerHelper.cpp.
References llvm::MachineRegisterInfo::getType(), I, llvm::LLT::isVector(), MI, and MRI.
applySimplifyAddToSub()
void CombinerHelper::applySimplifyAddToSub (MachineInstr & MI, std::tuple< Register, Register > & MatchInfo)
Definition at line 3096 of file CombinerHelper.cpp.
References MI.
applySimplifyURemByPow2()
void CombinerHelper::applySimplifyURemByPow2 (MachineInstr & MI)
Combine G_UREM x, (known power of 2) to an add and bitmasking.
The second source operand is known to be a power of 2.
Definition at line 3573 of file CombinerHelper.cpp.
References llvm::Add, llvm::MachineRegisterInfo::getType(), MI, and MRI.
applyUDivByConst()
void CombinerHelper::applyUDivByConst (MachineInstr & MI)
Definition at line 5376 of file CombinerHelper.cpp.
References buildUDivUsingMul(), MI, and replaceSingleDefInstWithReg().
applyUDivByPow2()
void CombinerHelper::applyUDivByPow2 (MachineInstr & MI)
Given an G_UDIV MI expressing an unsigned divided by a pow2 constant, return expressions that implements it by shifting.
Definition at line 5552 of file CombinerHelper.cpp.
References assert(), llvm::cast(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), MI, and MRI.
applyUMulHToLShr()
void CombinerHelper::applyUMulHToLShr (MachineInstr & MI)
Definition at line 5582 of file CombinerHelper.cpp.
References buildLogBase2(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), llvm::LLT::getScalarSizeInBits(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), MI, and MRI.
applyXorOfAndWithSameReg()
void CombinerHelper::applyXorOfAndWithSameReg (MachineInstr & MI, std::pair< Register, Register > & MatchInfo)
Definition at line 3534 of file CombinerHelper.cpp.
References llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineRegisterInfo::getType(), MI, MRI, Observer, X, and Y.
buildSDivUsingMul()
MachineInstr * CombinerHelper::buildSDivUsingMul (MachineInstr & MI)
Given an G_SDIV MI expressing a signed divide by constant, return an expression that implements it by multiplying by a magic number.
Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
Definition at line 5415 of file CombinerHelper.cpp.
References llvm::APInt::ashrInPlace(), assert(), Builder, llvm::CallingConv::C, llvm::cast(), llvm::APInt::countr_zero(), llvm::SmallVectorBase< Size_T >::empty(), llvm::getDefIgnoringCopies(), llvm::getIConstantSplatVal(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), llvm::LLT::getScalarType(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineInstr::IsExact, LHS, llvm::matchUnaryPredicate(), MI, MRI, llvm::APInt::multiplicativeInverse(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by applySDivByConst().
buildUDivUsingMul()
MachineInstr * CombinerHelper::buildUDivUsingMul (MachineInstr & MI)
Given an G_UDIV MI expressing a divide by constant, return an expression that implements it by multiplying by a magic number.
Ref: "Hacker's Delight" or "The PowerPC Compiler Writer's Guide".
Definition at line 5170 of file CombinerHelper.cpp.
References assert(), Builder, llvm::CallingConv::C, llvm::cast(), llvm::LLT::changeElementSize(), llvm::APInt::countl_zero(), llvm::KnownBits::countMinLeadingZeros(), llvm::APInt::countr_zero(), llvm::SmallVectorBase< Size_T >::empty(), llvm::UnsignedDivisionByConstantInfo::get(), llvm::APInt::getBitWidth(), llvm::getDefIgnoringCopies(), llvm::getIConstantSplatVal(), llvm::GISelKnownBits::getKnownBits(), llvm::APInt::getOneBitSet(), llvm::getOpcodeDef(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getScalarType(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::APInt::getZero(), llvm::CmpInst::ICMP_EQ, llvm::UnsignedDivisionByConstantInfo::IsAdd, llvm::MachineInstr::IsExact, llvm::APInt::isOne(), llvm::LLT::isScalar(), KB, LHS, llvm_unreachable, llvm::APInt::lshrInPlace(), llvm::UnsignedDivisionByConstantInfo::Magic, llvm::matchUnaryPredicate(), MI, MRI, llvm::APInt::multiplicativeInverse(), llvm::UnsignedDivisionByConstantInfo::PostShift, llvm::UnsignedDivisionByConstantInfo::PreShift, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::LLT::scalar().
Referenced by applyUDivByConst().
canCombineFMadOrFMA()
bool CombinerHelper::canCombineFMadOrFMA (MachineInstr & MI, bool & AllowFusionGlobally, bool & HasFMAD, bool & Aggressive, bool CanReassociate = false)
Definition at line 5691 of file CombinerHelper.cpp.
References llvm::Aggressive, llvm::FPOpFusion::Fast, llvm::MachineInstr::FmContract, llvm::MachineInstr::FmReassoc, llvm::MachineRegisterInfo::getType(), isLegalOrBeforeLegalizer(), isPreLegalize(), MI, MRI, and Options.
Referenced by matchCombineFAddFMAFMulToFMadOrFMA(), matchCombineFAddFMulToFMadOrFMA(), matchCombineFAddFpExtFMulToFMadOrFMA(), matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), matchCombineFSubFMulToFMadOrFMA(), matchCombineFSubFNegFMulToFMadOrFMA(), matchCombineFSubFpExtFMulToFMadOrFMA(), and matchCombineFSubFpExtFNegFMulToFMadOrFMA().
dominates()
bool CombinerHelper::dominates (const MachineInstr & DefMI, const MachineInstr & UseMI)
Returns true if DefMI dominates UseMI.
By definition an instruction dominates itself.
If we haven't been provided with a MachineDominatorTree during construction, this function returns a conservative result that tracks just a single basic block.
Definition at line 984 of file CombinerHelper.cpp.
References assert(), DefMI, llvm::MachineDominatorTree::dominates(), isPredecessor(), MDT, and UseMI.
Referenced by applyCombineDivRem().
eraseInst()
void CombinerHelper::eraseInst (MachineInstr & MI)
Erase MI.
Definition at line 2777 of file CombinerHelper.cpp.
References MI.
Referenced by applyCombineTruncOfShift(), and applyFsubToFneg().
getBuilder()
MachineIRBuilder & llvm::CombinerHelper::getBuilder () const inline
Definition at line 126 of file CombinerHelper.h.
References Builder.
getKnownBits()
GISelKnownBits * llvm::CombinerHelper::getKnownBits () const inline
Definition at line 122 of file CombinerHelper.h.
References KB.
getRegBank()
const RegisterBank * CombinerHelper::getRegBank (Register Reg) const
Get the register bank of Reg.
If Reg has not been assigned a register, a register class, or a register bank, then this returns nullptr.
Precondition
Reg.isValid()
Definition at line 196 of file CombinerHelper.cpp.
References llvm::RegisterBankInfo::getRegBank(), MRI, RBI, and TRI.
Referenced by matchPtrAddImmedChain().
getTargetLowering()
const TargetLowering & CombinerHelper::getTargetLowering () const
Definition at line 67 of file CombinerHelper.cpp.
Referenced by applyOptBrCondByInvertingCond(), applySDivByPow2(), applyUDivByPow2(), applyUMulHToLShr(), buildSDivUsingMul(), buildUDivUsingMul(), matchBitfieldExtractFromAnd(), matchBitfieldExtractFromSExtInReg(), matchBitfieldExtractFromShr(), matchBitfieldExtractFromShrAnd(), matchCombineExtractedVectorLoad(), matchCombineShlOfExtend(), matchCombineTruncOfShift(), matchCommuteShift(), matchExtractVecEltBuildVec(), matchExtractVectorElementWithBuildVector(), matchExtractVectorElementWithBuildVectorTrunc(), matchFPowIExpansion(), matchHoistLogicOpWithSameOpcodeHands(), matchICmpToLHSKnownBits(), matchICmpToTrueFalseKnownBits(), matchLoadOrCombine(), matchNarrowBinopFeedingAnd(), matchNonNegZext(), matchSDivByConst(), matchUDivByConst(), matchUMulHToLShr(), and tryReassocBinOp().
isConstantLegalOrBeforeLegalizer()
bool CombinerHelper::isConstantLegalOrBeforeLegalizer (const LLT Ty) const
Returns
true if the combine is running prior to legalization, or if Ty is a legal integer constant type on the target.
Definition at line 153 of file CombinerHelper.cpp.
References llvm::LLT::getElementType(), isLegal(), isLegalOrBeforeLegalizer(), and isPreLegalize().
Referenced by matchAddOverflow(), matchExtractVectorElementWithShuffleVector(), and matchMulOBy0().
isLegal()
bool CombinerHelper::isLegal (const LegalityQuery & Query) const
Returns
true if Query is legal on the target.
Definition at line 143 of file CombinerHelper.cpp.
References llvm::LegalizeActionStep::Action, assert(), llvm::LegalizerInfo::getAction(), llvm::LegalizeActions::Legal, and LI.
Referenced by isConstantLegalOrBeforeLegalizer(), and isLegalOrBeforeLegalizer().
isLegalOrBeforeLegalizer()
bool CombinerHelper::isLegalOrBeforeLegalizer (const LegalityQuery & Query) const
Returns
true if the combine is running prior to legalization, or if Query is legal on the target.
Definition at line 148 of file CombinerHelper.cpp.
References isLegal(), and isPreLegalize().
Referenced by canCombineFMadOrFMA(), isConstantLegalOrBeforeLegalizer(), matchAddOverflow(), matchAshrShlToSextInreg(), matchCombineConcatVectors(), matchCombineDivRem(), matchCombineExtractedVectorLoad(), matchCombineLoadWithAndMask(), matchCombineShlOfExtend(), matchCombineShuffleConcat(), matchCombineTruncOfShift(), matchExtractVectorElement(), matchExtractVectorElementWithBuildVectorTrunc(), matchExtractVectorElementWithShuffleVector(), matchFunnelShiftToRotate(), matchHoistLogicOpWithSameOpcodeHands(), matchICmpToLHSKnownBits(), matchInsertVectorElementOOB(), matchLoadOrCombine(), matchNarrowBinopFeedingAnd(), matchNonNegZext(), matchOrShiftToFunnelShift(), matchRedundantNegOperands(), matchSelectIMinMax(), matchSextInRegOfLoad(), matchSextOfTrunc(), matchShlOfVScale(), matchSubOfVScale(), matchUDivByConst(), matchUMulHToLShr(), and matchZextOfTrunc().
isPredecessor()
bool CombinerHelper::isPredecessor (const MachineInstr & DefMI, const MachineInstr & UseMI)
Returns true if DefMI precedes UseMI or they are the same instruction.
Both must be in the same basic block.
Definition at line 968 of file CombinerHelper.cpp.
References assert(), DefMI, llvm::MachineBasicBlock::end(), llvm::find_if(), llvm_unreachable, MBB, MI, and UseMI.
Referenced by dominates().
isPreLegalize()
bool CombinerHelper::isPreLegalize () const
Returns
true if the combiner is running pre-legalization.
Definition at line 141 of file CombinerHelper.cpp.
References IsPreLegalize.
Referenced by canCombineFMadOrFMA(), isConstantLegalOrBeforeLegalizer(), isLegalOrBeforeLegalizer(), matchCombineExtendingLoads(), and matchCommuteShift().
matchAddEToAddO()
bool CombinerHelper::matchAddEToAddO (MachineInstr & MI, BuildFnTy & MatchInfo)
Match: (G_*ADDE x, y, 0) -> (G_*ADDO x, y) (G_*SUBE x, y, 0) -> (G_*SUBO x, y)
Definition at line 5093 of file CombinerHelper.cpp.
References assert(), B, llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MIPatternMatch::m_SpecificICstOrSplat(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Observer.
matchAddOfVScale()
bool CombinerHelper::matchAddOfVScale (const MachineOperand & MO, BuildFnTy & MatchInfo)
Definition at line 405 of file CombinerHelperVectorOps.cpp.
References llvm::Add, B, llvm::cast(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GVScale::getSrc(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), and MRI.
matchAddOverflow()
bool CombinerHelper::matchAddOverflow (MachineInstr & MI, BuildFnTy & MatchInfo)
Combine addos.
Definition at line 7239 of file CombinerHelper.cpp.
References llvm::Add, llvm::ConstantRange::AlwaysOverflowsHigh, llvm::ConstantRange::AlwaysOverflowsLow, B, llvm::cast(), llvm::GISelKnownBits::computeNumSignBits(), llvm::ConstantRange::fromKnownBits(), llvm::MachineInstr::getFlag(), llvm::GISelKnownBits::getKnownBits(), llvm::GBinOp::getLHSReg(), llvm::getOpcodeDef(), llvm::GBinOp::getRHSReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isConstantLegalOrBeforeLegalizer(), isLegalOrBeforeLegalizer(), KB, llvm::ConstantRange::MayOverflow, MI, MRI, llvm::ConstantRange::NeverOverflows, llvm::MachineInstr::NoSWrap, llvm::MachineInstr::NoUWrap, llvm::ConstantRange::signedAddMayOverflow(), llvm::ConstantRange::unsignedAddMayOverflow(), and llvm::MachineRegisterInfo::use_nodbg_empty().
matchAddSubSameReg()
bool CombinerHelper::matchAddSubSameReg (MachineInstr & MI, Register & Src)
Transform G_ADD(x, G_SUB(y, x)) to y.
Transform G_ADD(G_SUB(y, x), x) to y.
Definition at line 6259 of file CombinerHelper.cpp.
References assert(), llvm::MIPatternMatch::m_GSub(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Reg.
matchAllExplicitUsesAreUndef()
bool CombinerHelper::matchAllExplicitUsesAreUndef (MachineInstr & MI)
Return true if all register explicit use operands on MI are defined by a G_IMPLICIT_DEF.
Definition at line 2729 of file CombinerHelper.cpp.
References llvm::all_of(), and MI.
matchAnd()
bool CombinerHelper::matchAnd (MachineInstr & MI, BuildFnTy & MatchInfo)
Combine ands.
Definition at line 7215 of file CombinerHelper.cpp.
References llvm::cast(), and MI.
matchAndOrDisjointMask()
bool CombinerHelper::matchAndOrDisjointMask (MachineInstr & MI, BuildFnTy & MatchInfo)
Returns
true if (and (or x, c1), c2) can be replaced with (and x, c2)
Definition at line 4463 of file CombinerHelper.cpp.
References assert(), B, llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_GAnd(), llvm::MIPatternMatch::m_GOr(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Observer.
matchAnyExplicitUseIsUndef()
bool CombinerHelper::matchAnyExplicitUseIsUndef (MachineInstr & MI)
Return true if any explicit use operand on MI is defined by a G_IMPLICIT_DEF.
Definition at line 2722 of file CombinerHelper.cpp.
References llvm::any_of(), and MI.
matchAshrShlToSextInreg()
bool CombinerHelper::matchAshrShlToSextInreg (MachineInstr & MI, std::tuple< Register, int64_t > & MatchInfo)
Match ashr (shl x, C), C -> sext_inreg (C)
Definition at line 3226 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::getType(), isLegalOrBeforeLegalizer(), llvm::MIPatternMatch::m_GAShr(), llvm::MIPatternMatch::m_GShl(), llvm::MIPatternMatch::m_ICstOrSplat(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchBinOpSameVal()
bool CombinerHelper::matchBinOpSameVal (MachineInstr & MI)
Optimize (x op x) -> x.
Definition at line 2960 of file CombinerHelper.cpp.
References llvm::canReplaceReg(), matchEqualDefs(), MI, and MRI.
matchBitfieldExtractFromAnd()
bool CombinerHelper::matchBitfieldExtractFromAnd (MachineInstr & MI, BuildFnTy & MatchInfo)
Match: and (lshr x, cst), mask -> ubfx x, cst, width.
Form a G_UBFX from "(a srl b) & mask", where b and mask are constants.
Definition at line 4527 of file CombinerHelper.cpp.
References llvm::cast(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::LegalizerInfo::isLegalOrCustom(), LI, MI, and MRI.
matchBitfieldExtractFromSExtInReg()
bool CombinerHelper::matchBitfieldExtractFromSExtInReg (MachineInstr & MI, BuildFnTy & MatchInfo)
Form a G_SBFX from a G_SEXT_INREG fed by a right shift.
Definition at line 4498 of file CombinerHelper.cpp.
References assert(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::LegalizerInfo::isLegalOrCustom(), LI, MI, and MRI.
matchBitfieldExtractFromShr()
bool CombinerHelper::matchBitfieldExtractFromShr (MachineInstr & MI, BuildFnTy & MatchInfo)
Match: shr (shl x, n), k -> sbfx/ubfx x, pos, width.
Definition at line 4564 of file CombinerHelper.cpp.
References assert(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::LegalizerInfo::isLegalOrCustom(), LI, MI, and MRI.
matchBitfieldExtractFromShrAnd()
bool CombinerHelper::matchBitfieldExtractFromShrAnd (MachineInstr & MI, BuildFnTy & MatchInfo)
Match: shr (and x, n), k -> ubfx x, pos, width.
Definition at line 4613 of file CombinerHelper.cpp.
References assert(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::LegalizerInfo::isLegalOrCustom(), LI, MI, and MRI.
matchBuildVectorIdentityFold()
bool CombinerHelper::matchBuildVectorIdentityFold (MachineInstr & MI, Register & MatchInfo)
Definition at line 6275 of file CombinerHelper.cpp.
References llvm::LLT::getElementType(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::Hi, llvm::Lo, llvm::MIPatternMatch::m_any_of(), llvm::MIPatternMatch::m_GBitcast(), llvm::MIPatternMatch::m_GBuildVector(), llvm::MIPatternMatch::m_GBuildVectorTrunc(), llvm::MIPatternMatch::m_GCst(), llvm::MIPatternMatch::m_GImplicitDef(), llvm::MIPatternMatch::m_GLShr(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineAddP2IToPtrAdd()
bool CombinerHelper::matchCombineAddP2IToPtrAdd (MachineInstr & MI, std::pair< Register, bool > & PtrRegAndCommute)
Transform G_ADD (G_PTRTOINT x), y -> G_PTRTOINT (G_PTR_ADD x, y) Transform G_ADD y, (G_PTRTOINT x) -> G_PTRTOINT (G_PTR_ADD x, y)
Definition at line 2432 of file CombinerHelper.cpp.
References assert(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), LHS, llvm::MIPatternMatch::m_GPtrToInt(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineAnyExtTrunc()
bool CombinerHelper::matchCombineAnyExtTrunc (MachineInstr & MI, Register & Reg)
Transform anyext(trunc(x)) to x.
Definition at line 2505 of file CombinerHelper.cpp.
References assert(), llvm::getSrcRegIgnoringCopies(), llvm::MachineRegisterInfo::getType(), llvm::Register::isValid(), llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_SpecificType(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineConcatVectors()
bool CombinerHelper::matchCombineConcatVectors (MachineInstr & MI, SmallVector< Register > & Ops)
If MI is G_CONCAT_VECTORS, try to combine it.
Returns true if MI changed. Right now, we support:
concat_vector(undef, undef) => undef
concat_vector(build_vector(A, B), build_vector(C, D)) =>
build_vector(A, B, C, D)
Check if the G_CONCAT_VECTORS MI is undef or if it can be flattened into a build_vector. In the first case Ops will be empty In the second case Ops will contain the operands needed to produce the flattened build_vector.
Precondition
MI.getOpcode() == G_CONCAT_VECTORS.
Definition at line 296 of file CombinerHelper.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::LLT::getScalarType(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isLegalOrBeforeLegalizer(), MI, MRI, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
matchCombineConstPtrAddToI2P()
bool CombinerHelper::matchCombineConstPtrAddToI2P (MachineInstr & MI, APInt & NewCst)
Definition at line 2475 of file CombinerHelper.cpp.
References llvm::cast(), llvm::getIConstantVRegVal(), llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_GIntToPtr(), llvm::MIPatternMatch::m_ICst(), MI, llvm::MIPatternMatch::mi_match(), MRI, llvm::APInt::sextOrTrunc(), and llvm::APInt::zextOrTrunc().
matchCombineCopy()
bool CombinerHelper::matchCombineCopy (MachineInstr & MI)
Definition at line 212 of file CombinerHelper.cpp.
References llvm::canReplaceReg(), MI, and MRI.
Referenced by tryCombineCopy().
matchCombineDivRem()
bool CombinerHelper::matchCombineDivRem (MachineInstr & MI, MachineInstr *& OtherMI)
Try to combine G_[SU]DIV and G_[SU]REM into a single G_[SU]DIVREM when their source operands are identical.
Definition at line 1477 of file CombinerHelper.cpp.
References llvm::MachineRegisterInfo::getType(), isLegalOrBeforeLegalizer(), llvm_unreachable, matchEqualDefs(), MI, MRI, llvm::MachineRegisterInfo::use_nodbg_instructions(), and UseMI.
matchCombineExtendingLoads()
bool CombinerHelper::matchCombineExtendingLoads (MachineInstr & MI, PreferredTuple & MatchInfo)
Definition at line 704 of file CombinerHelper.cpp.
References llvm::dyn_cast(), llvm::LegalizerInfo::getAction(), llvm::GAnyLoad::getDstReg(), getExtLoadOpcForExtend(), llvm::GMemOperation::getMMO(), llvm::GLoadStore::getPointerReg(), llvm::MachineInstrBuilder::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::has_single_bit(), llvm::isa(), isPreLegalize(), llvm::LLT::isScalar(), llvm::LegalizeActions::Legal, LI, MI, MRI, llvm::MachineRegisterInfo::use_nodbg_instructions(), and UseMI.
Referenced by tryCombineExtendingLoads().
matchCombineExtOfExt()
bool CombinerHelper::matchCombineExtOfExt (MachineInstr & MI, std::tuple< Register, unsigned > & MatchInfo)
Transform [asz]ext([asz]ext(x)) to [asz]ext x.
Definition at line 2531 of file CombinerHelper.cpp.
References assert(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::getSrcRegIgnoringCopies(), llvm::MachineRegisterInfo::getVRegDef(), llvm::Register::isValid(), MI, and MRI.
matchCombineExtractedVectorLoad()
bool CombinerHelper::matchCombineExtractedVectorLoad (MachineInstr & MI, BuildFnTy & MatchInfo)
Combine a G_EXTRACT_VECTOR_ELT of a load into a narrowed load.
Definition at line 1319 of file CombinerHelper.cpp.
References assert(), B, llvm::CallingConv::C, llvm::commonAlignment(), DL, llvm::MachineInstr::eraseFromParent(), llvm::CallingConv::Fast, llvm::MachinePointerInfo::getAddrSpace(), llvm::MachineMemOperand::getAlign(), llvm::Function::getContext(), llvm::MachineFunction::getDataLayout(), llvm::LLT::getElementType(), llvm::MachineFunction::getFunction(), llvm::getIConstantVRegVal(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineFunction::getMachineMemOperand(), llvm::getOpcodeDef(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineMemOperand::getPointerInfo(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::LegalizerHelper::getVectorElementPointer(), llvm::MachinePointerInfo::getWithOffset(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), II, llvm::LLT::isByteSized(), isLegalOrBeforeLegalizer(), MI, MRI, llvm::Offset, and llvm::Vector.
matchCombineFAddFMAFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFAddFMAFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo)
Transform (fadd (fma x, y, (fmul u, v)), z) -> (fma x, y, (fma u, v, z)) (fadd (fmad x, y, (fmul u, v)), z) -> (fmad x, y, (fmad u, v, z))
Definition at line 5831 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B, canCombineFMadOrFMA(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), hasMoreUses(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isContractableFMul(), MI, MRI, std::swap(), X, and Y.
matchCombineFAddFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFAddFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo)
Transform (fadd (fmul x, y), z) -> (fma x, y, z) (fadd (fmul x, y), z) -> (fmad x, y, z)
Definition at line 5724 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B, canCombineFMadOrFMA(), llvm::MachineRegisterInfo::getVRegDef(), hasMoreUses(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isContractableFMul(), MI, MRI, and std::swap().
matchCombineFAddFpExtFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo)
Transform (fadd (fpext (fmul x, y)), z) -> (fma (fpext x), (fpext y), z) (fadd (fpext (fmul x, y)), z) -> (fmad (fpext x), (fpext y), z)
Definition at line 5772 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B, canCombineFMadOrFMA(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), hasMoreUses(), isContractableFMul(), llvm::MIPatternMatch::m_GFPExt(), llvm::MIPatternMatch::m_MInstr(), MI, llvm::MIPatternMatch::mi_match(), MRI, and std::swap().
matchCombineFAddFpExtFMulToFMadOrFMAAggressive()
bool CombinerHelper::matchCombineFAddFpExtFMulToFMadOrFMAAggressive (MachineInstr & MI, BuildFnTy & MatchInfo)
Definition at line 5896 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B, canCombineFMadOrFMA(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getReg(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), hasMoreUses(), isContractableFMul(), llvm::MIPatternMatch::m_GFPExt(), llvm::MIPatternMatch::m_MInstr(), MI, llvm::MIPatternMatch::mi_match(), MRI, std::swap(), X, and Y.
matchCombineFMinMaxNaN()
bool CombinerHelper::matchCombineFMinMaxNaN (MachineInstr & MI, unsigned & Info)
Definition at line 6231 of file CombinerHelper.cpp.
References llvm::getConstantFPVRegVal(), llvm::ConstantFP::getValueAPF(), llvm::APFloat::isNaN(), MI, and MRI.
matchCombineFSubFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFSubFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo)
Transform (fsub (fmul x, y), z) -> (fma x, y, -z) (fsub (fmul x, y), z) -> (fmad x, y, -z)
Definition at line 6022 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B, canCombineFMadOrFMA(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), hasMoreUses(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isContractableFMul(), MI, and MRI.
matchCombineFSubFNegFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFSubFNegFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo)
Transform (fsub (fneg (fmul, x, y)), z) -> (fma (fneg x), y, (fneg z)) (fsub (fneg (fmul, x, y)), z) -> (fmad (fneg x), y, (fneg z))
Definition at line 6074 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B, canCombineFMadOrFMA(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isContractableFMul(), llvm::MIPatternMatch::m_GFNeg(), llvm::MIPatternMatch::m_MInstr(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineFSubFpExtFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFSubFpExtFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo)
Transform (fsub (fpext (fmul x, y)), z) -> (fma (fpext x), (fpext y), (fneg z)) (fsub (fpext (fmul x, y)), z) -> (fmad (fpext x), (fpext y), (fneg z))
Definition at line 6121 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B, canCombineFMadOrFMA(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isContractableFMul(), llvm::MIPatternMatch::m_GFPExt(), llvm::MIPatternMatch::m_MInstr(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineFSubFpExtFNegFMulToFMadOrFMA()
bool CombinerHelper::matchCombineFSubFpExtFNegFMulToFMadOrFMA (MachineInstr & MI, BuildFnTy & MatchInfo)
Transform (fsub (fpext (fneg (fmul x, y))), z) -> (fneg (fma (fpext x), (fpext y), z)) (fsub (fpext (fneg (fmul x, y))), z) -> (fneg (fmad (fpext x), (fpext y), z))
Definition at line 6172 of file CombinerHelper.cpp.
References llvm::Aggressive, assert(), B, canCombineFMadOrFMA(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), isContractableFMul(), llvm::MIPatternMatch::m_GFNeg(), llvm::MIPatternMatch::m_GFPExt(), llvm::MIPatternMatch::m_MInstr(), MI, llvm::MIPatternMatch::mi_match(), MRI, X, and Y.
matchCombineI2PToP2I()
bool CombinerHelper::matchCombineI2PToP2I (MachineInstr & MI, Register & Reg)
Transform IntToPtr(PtrToInt(x)) to x if cast is in the same address space.
Definition at line 2409 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_GPtrToInt(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_SpecificType(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineIndexedLoadStore()
bool CombinerHelper::matchCombineIndexedLoadStore (MachineInstr & MI, IndexedLoadStoreMatchInfo & MatchInfo)
Definition at line 1425 of file CombinerHelper.cpp.
References llvm::IndexedLoadStoreMatchInfo::Addr, llvm::IndexedLoadStoreMatchInfo::Base, llvm::cast(), llvm::GMemOperation::isAtomic(), llvm::IndexedLoadStoreMatchInfo::IsPre, MI, llvm::IndexedLoadStoreMatchInfo::Offset, and llvm::IndexedLoadStoreMatchInfo::RematOffset.
matchCombineInsertVecElts()
bool CombinerHelper::matchCombineInsertVecElts (MachineInstr & MI, SmallVectorImpl< Register > & MatchInfo)
Definition at line 3035 of file CombinerHelper.cpp.
References llvm::all_of(), assert(), llvm::LLT::getNumElements(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneUse(), I, isValid(), llvm::LLT::isVector(), llvm::MIPatternMatch::m_GInsertVecElt(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, Reg, llvm::SmallVectorImpl< T >::resize(), and llvm::MachineRegisterInfo::use_instr_begin().
matchCombineLoadWithAndMask()
bool CombinerHelper::matchCombineLoadWithAndMask (MachineInstr & MI, BuildFnTy & MatchInfo)
Match (and (load x), mask) -> zextload x.
Definition at line 886 of file CombinerHelper.cpp.
References assert(), B, llvm::APInt::countr_one(), llvm::dyn_cast(), llvm::MachineInstr::eraseFromParent(), llvm::GAnyLoad::getDstReg(), llvm::getIConstantVRegValWithLookThrough(), llvm::GMemOperation::getMemSizeInBits(), llvm::GMemOperation::getMMO(), llvm::MachineMemOperand::getPointerInfo(), llvm::GLoadStore::getPointerReg(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::LocationSize::getValue(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isLegalOrBeforeLegalizer(), llvm::APInt::isMask(), llvm::isPowerOf2_32(), llvm::GMemOperation::isSimple(), llvm::LLT::isVector(), llvm::LegalityQuery::MemDesc::MemoryTy, MI, MRI, RegSize, and llvm::LLT::scalar().
matchCombineMergeUnmerge()
bool CombinerHelper::matchCombineMergeUnmerge (MachineInstr & MI, Register & MatchInfo)
Fold away a merge of an unmerge of the corresponding values.
Definition at line 2086 of file CombinerHelper.cpp.
References llvm::cast(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::getOpcodeDef(), I, Merge, MI, MRI, and llvm::SmallVectorBase< Size_T >::size().
matchCombineMulToShl()
bool CombinerHelper::matchCombineMulToShl (MachineInstr & MI, unsigned & ShiftVal)
Transform a multiply by a power-of-2 value to a left shift.
Definition at line 2008 of file CombinerHelper.cpp.
References assert(), llvm::getIConstantVRegValWithLookThrough(), MI, and MRI.
matchCombineShiftToUnmerge()
bool CombinerHelper::matchCombineShiftToUnmerge (MachineInstr & MI, unsigned TargetShiftSize, unsigned & ShiftVal)
Reduce a shift by a constant to an unmerge and a shift on a half sized type.
This will not produce a shift smaller than TargetShiftSize.
Definition at line 2301 of file CombinerHelper.cpp.
References assert(), llvm::getIConstantVRegValWithLookThrough(), llvm::MachineRegisterInfo::getType(), MI, MRI, and Size.
Referenced by tryCombineShiftToUnmerge().
matchCombineShlOfExtend()
bool CombinerHelper::matchCombineShlOfExtend (MachineInstr & MI, RegisterImmPair & MatchData)
Definition at line 2033 of file CombinerHelper.cpp.
References assert(), llvm::APInt::countl_one(), llvm::GISelKnownBits::getKnownZeroes(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), llvm::LLT::getScalarSizeInBits(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::RegisterImmPair::Imm, llvm::isConstantOrConstantSplatVector(), isLegalOrBeforeLegalizer(), KB, LI, llvm::MIPatternMatch::m_GAnyExt(), llvm::MIPatternMatch::m_GSExt(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and llvm::RegisterImmPair::Reg.
matchCombineShuffleConcat()
bool CombinerHelper::matchCombineShuffleConcat (MachineInstr & MI, SmallVector< Register > & Ops)
Definition at line 376 of file CombinerHelper.cpp.
References llvm::dyn_cast(), llvm::SmallVectorBase< Size_T >::empty(), llvm::LLT::getNumElements(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), isLegalOrBeforeLegalizer(), MI, MRI, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
matchCombineShuffleVector()
bool CombinerHelper::matchCombineShuffleVector (MachineInstr & MI, SmallVectorImpl< Register > & Ops)
Check if the G_SHUFFLE_VECTOR MI can be replaced by a concat_vectors.
Ops will contain the operands needed to produce the flattened concat_vectors.
Precondition
MI.getOpcode() == G_SHUFFLE_VECTOR.
Definition at line 465 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isVector(), MI, MRI, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by tryCombineShuffleVector().
matchCombineTruncOfExt()
bool CombinerHelper::matchCombineTruncOfExt (MachineInstr & MI, std::pair< Register, unsigned > & MatchInfo)
Transform trunc ([asz]ext x) to x or ([asz]ext x) or (trunc x).
Definition at line 2585 of file CombinerHelper.cpp.
References assert(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), MI, and MRI.
matchCombineTruncOfShift()
bool CombinerHelper::matchCombineTruncOfShift (MachineInstr & MI, std::pair< MachineInstr *, LLT > & MatchInfo)
Transform trunc (shl x, K) to shl (trunc x), K if K < VT.getScalarSizeInBits().
Transforms trunc ([al]shr x, K) to (trunc ([al]shr (MidVT (trunc x)), K)) if K <= (MidVT.getScalarSizeInBits() - VT.getScalarSizeInBits()) MidVT is obtained by finding a legal type between the trunc's src and dst types.
Definition at line 2636 of file CombinerHelper.cpp.
References assert(), llvm::getDefIgnoringCopies(), llvm::GISelKnownBits::getKnownBits(), llvm::KnownBits::getMaxValue(), getMidVTForTruncRightShiftCombine(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isLegalOrBeforeLegalizer(), KB, MI, MRI, llvm::APInt::uge(), llvm::APInt::ugt(), and llvm::MachineRegisterInfo::use_instructions().
matchCombineUnmergeConstant()
bool CombinerHelper::matchCombineUnmergeConstant (MachineInstr & MI, SmallVectorImpl< APInt > & Csts)
Transform G_UNMERGE Constant -> Constant1, Constant2, ...
Definition at line 2168 of file CombinerHelper.cpp.
References llvm::APFloat::bitcastToAPInt(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::MachineOperand::getCImm(), llvm::MachineOperand::getFPImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::ConstantInt::getValue(), llvm::ConstantFP::getValueAPF(), llvm::MachineRegisterInfo::getVRegDef(), llvm::APInt::lshr(), MI, MRI, and llvm::APInt::trunc().
matchCombineUnmergeMergeToPlainValues()
bool CombinerHelper::matchCombineUnmergeMergeToPlainValues (MachineInstr & MI, SmallVectorImpl< Register > & Operands)
Transform <ty,...> G_UNMERGE(G_MERGE ty X, Y, Z) -> ty X, Y, Z.
Definition at line 2113 of file CombinerHelper.cpp.
References assert(), llvm::cast(), llvm::getOpcodeDef(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), MI, MRI, Operands, and peekThroughBitcast().
matchCombineUnmergeUndef()
bool CombinerHelper::matchCombineUnmergeUndef (MachineInstr & MI, std::function< void(MachineIRBuilder &)> & MatchInfo)
Transform G_UNMERGE G_IMPLICIT_DEF -> G_IMPLICIT_DEF, G_IMPLICIT_DEF, ...
Definition at line 2208 of file CombinerHelper.cpp.
References B, llvm::MachineRegisterInfo::getVRegDef(), llvm::isa(), MI, and MRI.
matchCombineUnmergeWithDeadLanesToTrunc()
bool CombinerHelper::matchCombineUnmergeWithDeadLanesToTrunc (MachineInstr & MI)
Transform X, Y<dead> = G_UNMERGE Z -> X = G_TRUNC Z.
Definition at line 2222 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isVector(), MI, MRI, and llvm::MachineRegisterInfo::use_nodbg_empty().
matchCombineUnmergeZExtToZExt()
bool CombinerHelper::matchCombineUnmergeZExtToZExt (MachineInstr & MI)
Transform X, Y = G_UNMERGE(G_ZEXT(Z)) -> X = G_ZEXT(Z); Y = G_CONSTANT 0.
Definition at line 2243 of file CombinerHelper.cpp.
References assert(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isVector(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCombineZextTrunc()
bool CombinerHelper::matchCombineZextTrunc (MachineInstr & MI, Register & Reg)
Transform zext(trunc(x)) to x.
Definition at line 2517 of file CombinerHelper.cpp.
References assert(), llvm::KnownBits::countMinLeadingZeros(), llvm::GISelKnownBits::getKnownBits(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), KB, llvm::MIPatternMatch::m_all_of(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_SpecificType(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCommuteConstantToRHS()
bool CombinerHelper::matchCommuteConstantToRHS (MachineInstr & MI)
Match constant LHS ops that should be commuted.
Definition at line 6520 of file CombinerHelper.cpp.
References llvm::getIConstantVRegVal(), llvm::MachineInstr::getOpcode(), llvm::MachineRegisterInfo::getVRegDef(), MI, and MRI.
matchCommuteFPConstantToRHS()
bool CombinerHelper::matchCommuteFPConstantToRHS (MachineInstr & MI)
Match constant LHS FP ops that should be commuted.
Definition at line 6550 of file CombinerHelper.cpp.
References llvm::MIPatternMatch::m_GFCstOrSplat(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchCommuteShift()
bool CombinerHelper::matchCommuteShift (MachineInstr & MI, BuildFnTy & MatchInfo)
Definition at line 1973 of file CombinerHelper.cpp.
References assert(), B, llvm::cast(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), isPreLegalize(), llvm::MIPatternMatch::m_any_of(), llvm::MIPatternMatch::m_GAdd(), llvm::MIPatternMatch::m_GOr(), llvm::MIPatternMatch::m_ICstOrSplat(), llvm::MIPatternMatch::m_OneNonDBGUse(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, S1, and X.
matchConstantFoldBinOp()
bool CombinerHelper::matchConstantFoldBinOp (MachineInstr & MI, APInt & MatchInfo)
Do constant folding when opportunities are exposed after MIR building.
Definition at line 4920 of file CombinerHelper.cpp.
References llvm::ConstantFoldBinOp(), MI, and MRI.
matchConstantFoldCastOp()
bool CombinerHelper::matchConstantFoldCastOp (MachineInstr & MI, APInt & MatchInfo)
Do constant folding when opportunities are exposed after MIR building.
Definition at line 4908 of file CombinerHelper.cpp.
References llvm::ConstantFoldCastOp(), llvm::MachineRegisterInfo::getType(), MI, and MRI.
matchConstantFoldFMA()
bool CombinerHelper::matchConstantFoldFMA (MachineInstr & MI, ConstantFP *& MatchInfo)
Constant fold G_FMA/G_FMAD.
Definition at line 4941 of file CombinerHelper.cpp.
References _, assert(), llvm::APFloat::fusedMultiplyAdd(), llvm::getConstantFPVRegVal(), llvm::ConstantFP::getValueAPF(), MI, MRI, and llvm::APFloatBase::rmNearestTiesToEven.
matchConstantFoldFPBinOp()
bool CombinerHelper::matchConstantFoldFPBinOp (MachineInstr & MI, ConstantFP *& MatchInfo)
Do constant FP folding when opportunities are exposed after MIR building.
Definition at line 4930 of file CombinerHelper.cpp.
References llvm::ConstantFoldFPBinOp(), MI, and MRI.
matchConstantFPOp()
bool CombinerHelper::matchConstantFPOp (const MachineOperand & MOP, double C)
Return true if MOP is defined by a G_FCONSTANT or splat with a value exactly equal to C.
Definition at line 2885 of file CombinerHelper.cpp.
References llvm::CallingConv::C, llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), llvm::MIPatternMatch::m_GFCstOrSplat(), llvm::MIPatternMatch::mi_match(), and MRI.
matchConstantLargerBitWidth()
bool CombinerHelper::matchConstantLargerBitWidth (MachineInstr & MI, unsigned ConstIdx)
Checks if constant at ConstIdx is larger than MI 's bitwidth.
Parameters
ConstIdx Index of the constant
Definition at line 2914 of file CombinerHelper.cpp.
References llvm::getIConstantVRegValWithLookThrough(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), MI, and MRI.
matchConstantOp()
bool CombinerHelper::matchConstantOp (const MachineOperand & MOP, int64_t C)
Return true if MOP is defined by a G_CONSTANT or splat with a value equal to C.
Definition at line 2876 of file CombinerHelper.cpp.
References llvm::CallingConv::C, llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), llvm::isConstantOrConstantSplatVector(), llvm::MachineOperand::isReg(), MI, and MRI.
Referenced by matchOperandIsZero().
matchConstantSelectCmp()
bool CombinerHelper::matchConstantSelectCmp (MachineInstr & MI, unsigned & OpIdx)
Return true if a G_SELECT instruction MI has a constant comparison.
If true, OpIdx will store the operand index of the known selected value.
Definition at line 2767 of file CombinerHelper.cpp.
References llvm::cast(), llvm::GSelect::getCondReg(), llvm::MachineRegisterInfo::getVRegDef(), llvm::isConstantOrConstantSplatVector(), MI, and MRI.
matchDivByPow2()
bool CombinerHelper::matchDivByPow2 (MachineInstr & MI, bool IsSigned)
Given an G_SDIV MI expressing a signed divided by a pow2 constant, return expressions that implements it by shifting.
Definition at line 5479 of file CombinerHelper.cpp.
References assert(), llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), llvm::matchUnaryPredicate(), MI, and MRI.
matchEqualDefs()
bool CombinerHelper::matchEqualDefs (const MachineOperand & MOP1, const MachineOperand & MOP2)
Return true if MOP1 and MOP2 are register operands are defined by equivalent instructions.
Definition at line 2779 of file CombinerHelper.cpp.
References llvm::any_of(), llvm::dyn_cast(), llvm::MachineInstr::findRegisterDefOperandIdx(), llvm::getDefSrcRegIgnoringCopies(), llvm::GMemOperation::getMemSizeInBits(), llvm::MachineOperand::getReg(), llvm::MachineInstr::isDereferenceableInvariantLoad(), llvm::MachineOperand::isReg(), llvm::MachineInstr::mayLoadOrStore(), and MRI.
Referenced by matchBinOpSameVal(), matchCombineDivRem(), matchHoistLogicOpWithSameOpcodeHands(), and matchSelectSameVal().
matchExtendThroughPhis()
bool CombinerHelper::matchExtendThroughPhis (MachineInstr & MI, MachineInstr *& ExtMI)
Definition at line 4021 of file CombinerHelper.cpp.
References llvm::cast(), DefMI, llvm::getDefIgnoringCopies(), llvm::MachineInstr::getOpcode(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::LLT::isVector(), MI, MRI, PHI, llvm::SmallPtrSetImplBase::size(), and llvm::MachineRegisterInfo::use_instr_nodbg_begin().
matchExtractAllEltsFromBuildVector()
bool CombinerHelper::matchExtractAllEltsFromBuildVector (MachineInstr & MI, SmallVectorImpl< std::pair< Register, MachineInstr * > > & MatchInfo)
Definition at line 4171 of file CombinerHelper.cpp.
References llvm::SmallBitVector::all(), assert(), llvm::getIConstantVRegVal(), llvm::LLT::getNumElements(), llvm::MachineRegisterInfo::getType(), II, MI, MRI, llvm::SmallBitVector::set(), and llvm::MachineRegisterInfo::use_nodbg_instructions().
matchExtractVecEltBuildVec()
bool CombinerHelper::matchExtractVecEltBuildVec (MachineInstr & MI, Register & Reg)
Definition at line 4120 of file CombinerHelper.cpp.
References assert(), llvm::getIConstantVRegValWithLookThrough(), llvm::getMVTForLLT(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), MI, and MRI.
matchExtractVectorElement()
bool CombinerHelper::matchExtractVectorElement (MachineInstr & MI, BuildFnTy & MatchInfo)
Combine extract vector element.
Definition at line 33 of file CombinerHelperVectorOps.cpp.
References B, llvm::cast(), llvm::getIConstantVRegValWithLookThrough(), llvm::GExtractVectorElement::getIndexReg(), llvm::LLT::getNumElements(), llvm::GenericMachineInstr::getReg(), llvm::MachineRegisterInfo::getType(), llvm::GExtractVectorElement::getVectorReg(), llvm::LLT::isFixedVector(), isLegalOrBeforeLegalizer(), MI, MRI, and llvm::Vector.
matchExtractVectorElementWithBuildVector()
bool CombinerHelper::matchExtractVectorElementWithBuildVector (const MachineOperand & MO, BuildFnTy & MatchInfo)
Combine extract vector element with a build vector on the vector register.
Definition at line 148 of file CombinerHelperVectorOps.cpp.
References B, llvm::cast(), llvm::getDefIgnoringCopies(), llvm::getIConstantVRegValWithLookThrough(), llvm::GExtractVectorElement::getIndexReg(), llvm::getMVTForLLT(), llvm::getOpcodeDef(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GMergeLikeInstr::getSourceReg(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::GExtractVectorElement::getVectorReg(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), MRI, and llvm::Vector.
matchExtractVectorElementWithBuildVectorTrunc()
bool CombinerHelper::matchExtractVectorElementWithBuildVectorTrunc (const MachineOperand & MO, BuildFnTy & MatchInfo)
Combine extract vector element with a build vector trunc on the vector register.
Definition at line 209 of file CombinerHelperVectorOps.cpp.
References B, llvm::cast(), llvm::getDefIgnoringCopies(), llvm::getIConstantVRegValWithLookThrough(), llvm::GExtractVectorElement::getIndexReg(), llvm::getMVTForLLT(), llvm::getOpcodeDef(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GMergeLikeInstr::getSourceReg(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::GExtractVectorElement::getVectorReg(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isLegalOrBeforeLegalizer(), MRI, and llvm::Vector.
matchExtractVectorElementWithDifferentIndices()
bool CombinerHelper::matchExtractVectorElementWithDifferentIndices (const MachineOperand & MO, BuildFnTy & MatchInfo)
Combine extract vector element with a insert vector element on the vector register and different indices.
Definition at line 91 of file CombinerHelperVectorOps.cpp.
References B, llvm::cast(), llvm::getDefIgnoringCopies(), llvm::getIConstantVRegValWithLookThrough(), llvm::GExtractVectorElement::getIndexReg(), llvm::getOpcodeDef(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GExtractVectorElement::getVectorReg(), MRI, and llvm::Vector.
matchExtractVectorElementWithShuffleVector()
bool CombinerHelper::matchExtractVectorElementWithShuffleVector (const MachineOperand & MO, BuildFnTy & MatchInfo)
Combine extract vector element with a shuffle vector on the vector register.
Definition at line 276 of file CombinerHelperVectorOps.cpp.
References assert(), B, llvm::cast(), llvm::getDefIgnoringCopies(), llvm::getIConstantVRegValWithLookThrough(), llvm::GExtractVectorElement::getIndexReg(), llvm::GShuffleVector::getMask(), llvm::LLT::getNumElements(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GShuffleVector::getSrc1Reg(), llvm::GShuffleVector::getSrc2Reg(), llvm::MachineRegisterInfo::getType(), llvm::GExtractVectorElement::getVectorReg(), isConstantLegalOrBeforeLegalizer(), isLegalOrBeforeLegalizer(), llvm::LLT::isVector(), MRI, and llvm::Offset.
matchFoldBinOpIntoSelect()
bool CombinerHelper::matchFoldBinOpIntoSelect (MachineInstr & MI, unsigned & SelectOpNo)
Push a binary operator through a select on constants.
binop (select cond, K0, K1), K2 -> select cond, (binop K0, K2), (binop K1, K2)
Definition at line 3586 of file CombinerHelper.cpp.
References llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::isAllOnesOrAllOnesSplat(), llvm::isConstantOrConstantVector(), llvm::isNullOrNullSplat(), LHS, MI, MRI, RHS, and Select.
matchFPowIExpansion()
bool CombinerHelper::matchFPowIExpansion (MachineInstr & MI, int64_t Exponent)
Match FPOWI if it's safe to extend it into a series of multiplications.
Definition at line 7413 of file CombinerHelper.cpp.
References llvm::Exponent, getTargetLowering(), llvm::TargetLoweringBase::isBeneficialToExpandPowI(), and MI.
matchFreezeOfSingleMaybePoisonOperand()
bool CombinerHelper::matchFreezeOfSingleMaybePoisonOperand (MachineInstr & MI, BuildFnTy & MatchInfo)
Definition at line 226 of file CombinerHelper.cpp.
References B, llvm::canCreateUndefOrPoison(), llvm::cast(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineInstr::findRegisterUseOperand(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::isa(), llvm::isGuaranteedNotToBeUndefOrPoison(), llvm::MachineInstr::isPHI(), MI, MRI, Observer, replaceRegOpWith(), replaceRegWith(), TRI, and llvm::MachineInstr::uses().
matchFsubToFneg()
bool CombinerHelper::matchFsubToFneg (MachineInstr & MI, Register & MatchInfo)
Definition at line 5644 of file CombinerHelper.cpp.
References assert(), llvm::MachineInstr::FmNsz, llvm::getFConstantSplat(), llvm::getFConstantVRegValWithLookThrough(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isVector(), MI, and MRI.
matchFunnelShiftToRotate()
bool CombinerHelper::matchFunnelShiftToRotate (MachineInstr & MI)
Match an FSHL or FSHR that can be combined to a ROTR or ROTL rotate.
Definition at line 4290 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::getType(), isLegalOrBeforeLegalizer(), MI, MRI, X, and Y.
matchHoistLogicOpWithSameOpcodeHands()
bool CombinerHelper::matchHoistLogicOpWithSameOpcodeHands (MachineInstr & MI, InstructionStepsMatchInfo & MatchInfo)
Match (logic_op (op x...), (op y...)) -> (op (logic_op x, y))
Definition at line 3104 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::createGenericVirtualRegister(), DL, llvm::Function::getContext(), llvm::MachineFunction::getDataLayout(), llvm::getDefIgnoringCopies(), llvm::MachineFunction::getFunction(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isLegalOrBeforeLegalizer(), llvm::MachineOperand::isReg(), llvm::TargetLoweringBase::isTruncateFree(), llvm::LLT::isValid(), llvm::Register::isValid(), llvm::TargetLoweringBase::isZExtFree(), matchEqualDefs(), MI, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), X, and Y.
matchICmpToLHSKnownBits()
bool CombinerHelper::matchICmpToLHSKnownBits (MachineInstr & MI, BuildFnTy & MatchInfo)
Returns
true if a G_ICMP MI can be replaced with its LHS based off of KnownBits information.
Definition at line 4420 of file CombinerHelper.cpp.
References assert(), B, llvm::getICmpTrueVal(), llvm::GISelKnownBits::getKnownBits(), llvm::LLT::getSizeInBits(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::isEquality(), isLegalOrBeforeLegalizer(), llvm::LLT::isVector(), KB, llvm::MIPatternMatch::m_SpecificICst(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchICmpToTrueFalseKnownBits()
bool CombinerHelper::matchICmpToTrueFalseKnownBits (MachineInstr & MI, int64_t & MatchInfo)
Returns
true if a G_ICMP instruction MI can be replaced with a true or false constant based off of KnownBits information.
Definition at line 4343 of file CombinerHelper.cpp.
References assert(), llvm::KnownBits::eq(), llvm::getICmpTrueVal(), llvm::GISelKnownBits::getKnownBits(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::LLT::isVector(), KB, llvm_unreachable, MI, MRI, llvm::KnownBits::ne(), llvm::KnownBits::sge(), llvm::KnownBits::sgt(), llvm::KnownBits::sle(), llvm::KnownBits::slt(), llvm::KnownBits::uge(), llvm::KnownBits::ugt(), llvm::KnownBits::ule(), and llvm::KnownBits::ult().
matchInsertExtractVecEltOutOfBounds()
bool CombinerHelper::matchInsertExtractVecEltOutOfBounds (MachineInstr & MI)
Return true if a G_{EXTRACT,INSERT}_VECTOR_ELT has an out of range index.
Definition at line 2754 of file CombinerHelper.cpp.
References assert(), llvm::getIConstantVRegVal(), llvm::LLT::getNumElements(), llvm::MachineRegisterInfo::getType(), MI, and MRI.
matchInsertVectorElementOOB()
bool CombinerHelper::matchInsertVectorElementOOB (MachineInstr & MI, BuildFnTy & MatchInfo)
Combine insert vector element OOB.
Definition at line 382 of file CombinerHelperVectorOps.cpp.
References B, llvm::cast(), llvm::getIConstantVRegValWithLookThrough(), llvm::LLT::getNumElements(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isFixedVector(), isLegalOrBeforeLegalizer(), MI, and MRI.
matchLoadOrCombine()
bool CombinerHelper::matchLoadOrCombine (MachineInstr & MI, BuildFnTy & MatchInfo)
Match expression trees of the form.
sN *a = ...
sM val = a[0] | (a[1] << N) | (a[2] << 2N) | (a[3] << 3N) ...
And check if the tree can be replaced with a M-bit load + possibly a bswap.
Definition at line 3908 of file CombinerHelper.cpp.
References assert(), bigEndianByteAt(), llvm::CallingConv::C, llvm::MachineRegisterInfo::cloneVirtualRegister(), DL, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::CallingConv::Fast, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::Function::getContext(), llvm::MachineFunction::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::GMemOperation::getMMO(), llvm::MachineMemOperand::getPointerInfo(), llvm::GLoadStore::getPointerReg(), llvm::LLT::getSizeInBits(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), isBigEndian(), llvm::DataLayout::isBigEndian(), isLegalOrBeforeLegalizer(), littleEndianByteAt(), llvm::LegalityQuery::MemDesc::MemoryTy, MI, MRI, and Ptr.
matchMulOBy0()
bool CombinerHelper::matchMulOBy0 (MachineInstr & MI, BuildFnTy & MatchInfo)
Match: (G_*MULO x, 0) -> 0 + no carry out.
Definition at line 5075 of file CombinerHelper.cpp.
References assert(), B, llvm::MachineRegisterInfo::getType(), isConstantLegalOrBeforeLegalizer(), llvm::MIPatternMatch::m_SpecificICstOrSplat(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchMulOBy2()
bool CombinerHelper::matchMulOBy2 (MachineInstr & MI, BuildFnTy & MatchInfo)
Match: (G_UMULO x, 2) -> (G_UADDO x, x) (G_SMULO x, 2) -> (G_SADDO x, x)
Definition at line 5057 of file CombinerHelper.cpp.
References assert(), B, llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MIPatternMatch::m_SpecificICstOrSplat(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Observer.
matchMulOfVScale()
bool CombinerHelper::matchMulOfVScale (const MachineOperand & MO, BuildFnTy & MatchInfo)
Definition at line 424 of file CombinerHelperVectorOps.cpp.
References B, llvm::cast(), llvm::getIConstantVRegVal(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GVScale::getSrc(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), MRI, and llvm::Mul.
matchNarrowBinopFeedingAnd()
bool CombinerHelper::matchNarrowBinopFeedingAnd (MachineInstr & MI, BuildFnTy & MatchInfo)
Returns
true if it is possible to narrow the width of a scalar binop feeding a G_AND instruction MI.
Definition at line 4966 of file CombinerHelper.cpp.
References assert(), B, llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), DL, llvm::getDefIgnoringCopies(), llvm::getIConstantVRegValWithLookThrough(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getSizeInBits(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isLegalOrBeforeLegalizer(), llvm::LLT::isScalar(), MI, MRI, Observer, and llvm::LLT::scalar().
matchNonNegZext()
bool CombinerHelper::matchNonNegZext (const MachineOperand & MO, BuildFnTy & MatchInfo)
Combine zext nneg to sext.
Definition at line 7529 of file CombinerHelper.cpp.
References B, llvm::cast(), llvm::getMVTForLLT(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GCastOp::getSrcReg(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), isLegalOrBeforeLegalizer(), and MRI.
matchNotCmp()
bool CombinerHelper::matchNotCmp (MachineInstr & MI, SmallVectorImpl< Register > & RegsToNegate)
Combine inverting a result of a compare into the opposite cond code.
Definition at line 3394 of file CombinerHelper.cpp.
References assert(), llvm::getIConstantSplatSExtVal(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), I, isConstValidTrue(), llvm::MIPatternMatch::m_GXor(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase< Size_T >::size().
matchOperandIsKnownToBeAPowerOfTwo()
bool CombinerHelper::matchOperandIsKnownToBeAPowerOfTwo (MachineInstr & MI, unsigned OpIdx)
Check if operand OpIdx is known to be a power of 2.
Definition at line 2978 of file CombinerHelper.cpp.
References llvm::MachineOperand::getReg(), llvm::isKnownToBeAPowerOfTwo(), KB, MI, and MRI.
matchOperandIsUndef()
bool CombinerHelper::matchOperandIsUndef (MachineInstr & MI, unsigned OpIdx)
Check if operand OpIdx is undef.
Definition at line 2972 of file CombinerHelper.cpp.
References llvm::getOpcodeDef(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), MI, and MRI.
matchOperandIsZero()
bool CombinerHelper::matchOperandIsZero (MachineInstr & MI, unsigned OpIdx)
Check if operand OpIdx is zero.
Definition at line 2966 of file CombinerHelper.cpp.
References llvm::canReplaceReg(), matchConstantOp(), MI, and MRI.
matchOptBrCondByInvertingCond()
bool CombinerHelper::matchOptBrCondByInvertingCond (MachineInstr & MI, MachineInstr *& BrCond)
If a brcond's true block is not the fallthrough, make it so by inverting the condition and swapping operands.
Definition at line 1572 of file CombinerHelper.cpp.
References assert(), llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::isLayoutSuccessor(), MBB, and MI.
matchOr()
bool CombinerHelper::matchOr (MachineInstr & MI, BuildFnTy & MatchInfo)
Combine ors.
Definition at line 7227 of file CombinerHelper.cpp.
References llvm::cast(), and MI.
matchOrShiftToFunnelShift()
bool CombinerHelper::matchOrShiftToFunnelShift (MachineInstr & MI, BuildFnTy & MatchInfo)
Definition at line 4236 of file CombinerHelper.cpp.
References assert(), B, llvm::BitWidth, llvm::MachineRegisterInfo::getType(), isLegalOrBeforeLegalizer(), llvm::MIPatternMatch::m_GLShr(), llvm::MIPatternMatch::m_GOr(), llvm::MIPatternMatch::m_GShl(), llvm::MIPatternMatch::m_GSub(), llvm::MIPatternMatch::m_ICstOrSplat(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_SpecificICstOrSplat(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchOverlappingAnd()
bool CombinerHelper::matchOverlappingAnd (MachineInstr & MI, BuildFnTy & MatchInfo)
Fold and(and(x, C1), C2) -> C1&C2 ? and(x, C1&C2) : 0.
and(and(x, C1), C2) -> C1&C2 ? and(x, C1&C2) : 0
Definition at line 3256 of file CombinerHelper.cpp.
References assert(), B, llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_GAnd(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and replaceRegWith().
matchPtrAddImmedChain()
bool CombinerHelper::matchPtrAddImmedChain (MachineInstr & MI, PtrAddChain & MatchInfo)
Definition at line 1701 of file CombinerHelper.cpp.
References llvm::PtrAddChain::Bank, llvm::PtrAddChain::Base, llvm::sampleprof::Base, llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::dyn_cast(), llvm::LLT::getAddressSpace(), llvm::getIConstantVRegValWithLookThrough(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), getRegBank(), llvm::APInt::getSExtValue(), llvm::MachineRegisterInfo::getType(), llvm::getTypeForLLT(), llvm::MachineRegisterInfo::getVRegDef(), llvm::TargetLoweringBase::AddrMode::HasBaseReg, llvm::PtrAddChain::Imm, MI, MRI, llvm::MachineRegisterInfo::use_nodbg_instructions(), and UseMI.
matchPtrAddZero()
bool CombinerHelper::matchPtrAddZero (MachineInstr & MI)
}
Combine G_PTR_ADD with nullptr to G_INTTOPTR
Definition at line 3547 of file CombinerHelper.cpp.
References assert(), llvm::cast(), DL, llvm::getIConstantVRegVal(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::isBuildVectorAllZeros(), MI, and MRI.
matchReassocCommBinOp()
bool CombinerHelper::matchReassocCommBinOp (MachineInstr & MI, BuildFnTy & MatchInfo)
Reassociate commutative binary operations like G_ADD.
Definition at line 4892 of file CombinerHelper.cpp.
References MI, and tryReassocBinOp().
matchReassocConstantInnerLHS()
bool CombinerHelper::matchReassocConstantInnerLHS (GPtrAdd & MI, MachineInstr * LHS, MachineInstr * RHS, BuildFnTy & MatchInfo)
Definition at line 4759 of file CombinerHelper.cpp.
References B, llvm::cast(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_GCst(), llvm::MIPatternMatch::m_GPtrAdd(), llvm::MIPatternMatch::m_OneNonDBGUse(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and Observer.
Referenced by matchReassocPtrAdd().
matchReassocConstantInnerRHS()
bool CombinerHelper::matchReassocConstantInnerRHS (GPtrAdd & MI, MachineInstr * RHS, BuildFnTy & MatchInfo)
Definition at line 4735 of file CombinerHelper.cpp.
References B, llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::getIConstantVRegVal(), llvm::MachineRegisterInfo::getType(), MI, MRI, and Observer.
Referenced by matchReassocPtrAdd().
matchReassocFoldConstantsInSubTree()
bool CombinerHelper::matchReassocFoldConstantsInSubTree (GPtrAdd & MI, MachineInstr * LHS, MachineInstr * RHS, BuildFnTy & MatchInfo)
Definition at line 4790 of file CombinerHelper.cpp.
References B, llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::dyn_cast(), llvm::getIConstantVRegVal(), llvm::MachineRegisterInfo::getType(), MI, MRI, and Observer.
Referenced by matchReassocPtrAdd().
matchReassocPtrAdd()
bool CombinerHelper::matchReassocPtrAdd (MachineInstr & MI, BuildFnTy & MatchInfo)
Reassociate pointer calculations with G_ADD involved, to allow better addressing mode usage.
Definition at line 4819 of file CombinerHelper.cpp.
References llvm::cast(), llvm::MachineRegisterInfo::getVRegDef(), matchReassocConstantInnerLHS(), matchReassocConstantInnerRHS(), matchReassocFoldConstantsInSubTree(), MI, and MRI.
matchRedundantAnd()
bool CombinerHelper::matchRedundantAnd (MachineInstr & MI, Register & Replacement)
Returns
true if MI is a G_AND instruction whose operands are x and y where x & y == x or x & y == y. (E.g., one of operands is all-ones value.)
Parameters
[in] MI - The G_AND instruction.
[out] Replacement - A register the G_AND should be replaced with on success.
Definition at line 3282 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), llvm::GISelKnownBits::getKnownBits(), llvm::KnownBits::isUnknown(), KB, LHS, MI, MRI, llvm::KnownBits::One, RHS, and llvm::KnownBits::Zero.
matchRedundantBinOpInEquality()
bool CombinerHelper::matchRedundantBinOpInEquality (MachineInstr & MI, BuildFnTy & MatchInfo)
Transform: (X + Y) == X -> Y == 0 (X - Y) == X -> Y == 0 (X ^ Y) == X -> Y == 0 (X + Y) != X -> Y != 0 (X - Y) != X -> Y != 0 (X ^ Y) != X -> Y != 0.
Definition at line 6478 of file CombinerHelper.cpp.
References assert(), B, llvm::MachineRegisterInfo::getType(), llvm::CmpInst::isEquality(), llvm::MIPatternMatch::m_any_of(), llvm::MIPatternMatch::m_c_GICmp(), llvm::MIPatternMatch::m_GAdd(), llvm::MIPatternMatch::m_GSub(), llvm::MIPatternMatch::m_GXor(), llvm::MIPatternMatch::m_Pred(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, Register, X, and Y.
matchRedundantNegOperands()
bool CombinerHelper::matchRedundantNegOperands (MachineInstr & MI, BuildFnTy & MatchInfo)
Transform (fadd x, fneg(y)) -> (fsub x, y) (fadd fneg(x), y) -> (fsub y, x) (fsub x, fneg(y)) -> (fadd x, y) (fmul fneg(x), fneg(y)) -> (fmul x, y) (fdiv fneg(x), fneg(y)) -> (fdiv x, y) (fmad fneg(x), fneg(y), z) -> (fmad x, y, z) (fma fneg(x), fneg(y), z) -> (fma x, y, z)
fold (fsub x, fneg(y)) -> (fadd x, y)
Definition at line 5598 of file CombinerHelper.cpp.
References assert(), B, llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineRegisterInfo::getType(), isLegalOrBeforeLegalizer(), llvm::MIPatternMatch::m_GFAdd(), llvm::MIPatternMatch::m_GFNeg(), llvm::MIPatternMatch::m_GFSub(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, Observer, X, and Y.
matchRedundantOr()
bool CombinerHelper::matchRedundantOr (MachineInstr & MI, Register & Replacement)
Returns
true if MI is a G_OR instruction whose operands are x and y where x | y == x or x | y == y. (E.g., one of operands is all-zeros value.)
Parameters
[in] MI - The G_OR instruction.
[out] Replacement - A register the G_OR should be replaced with on success.
Definition at line 3338 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), llvm::GISelKnownBits::getKnownBits(), KB, LHS, MI, MRI, llvm::KnownBits::One, RHS, and llvm::KnownBits::Zero.
matchRedundantSExtInReg()
bool CombinerHelper::matchRedundantSExtInReg (MachineInstr & MI)
Returns
true if MI is a G_SEXT_INREG that can be erased.
Definition at line 3379 of file CombinerHelper.cpp.
References llvm::GISelKnownBits::computeNumSignBits(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), KB, MI, and MRI.
matchRotateOutOfRange()
bool CombinerHelper::matchRotateOutOfRange (MachineInstr & MI)
Definition at line 4314 of file CombinerHelper.cpp.
References assert(), llvm::CallingConv::C, llvm::dyn_cast(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::matchUnaryPredicate(), MI, and MRI.
matchSDivByConst()
bool CombinerHelper::matchSDivByConst (MachineInstr & MI)
Definition at line 5381 of file CombinerHelper.cpp.
References assert(), llvm::CallingConv::C, DL, llvm::getApproximateEVTForLLT(), llvm::AttributeList::getAttributes(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineInstr::IsExact, llvm::matchUnaryPredicate(), MI, and MRI.
matchSelect()
bool CombinerHelper::matchSelect (MachineInstr & MI, BuildFnTy & MatchInfo)
Combine selects.
Definition at line 6965 of file CombinerHelper.cpp.
References llvm::cast(), MI, and Select.
matchSelectIMinMax()
bool CombinerHelper::matchSelectIMinMax (const MachineOperand & MO, BuildFnTy & MatchInfo)
Combine select to integer min/max.
Definition at line 6893 of file CombinerHelper.cpp.
References B, llvm::cast(), llvm::MachineOperand::getReg(), llvm::CmpInst::getSwappedPredicate(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::CmpInst::isEquality(), isLegalOrBeforeLegalizer(), llvm::LLT::isPointer(), MRI, Select, and std::swap().
matchSelectSameVal()
bool CombinerHelper::matchSelectSameVal (MachineInstr & MI)
Optimize (cond ? x : x) -> x.
Definition at line 2952 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), matchEqualDefs(), MI, and MRI.
matchSextInRegOfLoad()
bool CombinerHelper::matchSextInRegOfLoad (MachineInstr & MI, std::tuple< Register, unsigned > & MatchInfo)
Match sext_inreg(load p), imm -> sextload p.
Definition at line 1029 of file CombinerHelper.cpp.
References assert(), llvm::getOpcodeDef(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isLegalOrBeforeLegalizer(), llvm::isPowerOf2_32(), llvm::LLT::isVector(), llvm::LegalityQuery::MemDesc::MemoryTy, MI, MRI, and llvm::LLT::scalar().
matchSextOfTrunc()
bool CombinerHelper::matchSextOfTrunc (const MachineOperand & MO, BuildFnTy & MatchInfo)
Combine sext of trunc.
Definition at line 7461 of file CombinerHelper.cpp.
References B, llvm::cast(), llvm::getDefIgnoringCopies(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::GCastOp::getSrcReg(), llvm::MachineRegisterInfo::getType(), isLegalOrBeforeLegalizer(), MRI, and llvm::MachineInstr::NoSWrap.
matchSextTruncSextLoad()
bool CombinerHelper::matchSextTruncSextLoad (MachineInstr & MI)
Definition at line 996 of file CombinerHelper.cpp.
References assert(), llvm::getOpcodeDef(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::LLT::isVector(), llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchShiftImmedChain()
bool CombinerHelper::matchShiftImmedChain (MachineInstr & MI, RegisterImmPair & MatchInfo)
Fold (shift (shift base, x), y) -> (shift base (x+y))
Definition at line 1776 of file CombinerHelper.cpp.
References assert(), llvm::sampleprof::Base, llvm::getIConstantVRegValWithLookThrough(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::RegisterImmPair::Imm, MI, MRI, and llvm::RegisterImmPair::Reg.
matchShiftOfShiftedLogic()
bool CombinerHelper::matchShiftOfShiftedLogic (MachineInstr & MI, ShiftOfShiftedLogic & MatchInfo)
If we have a shift-by-constant of a bitwise logic op that itself has a shift-by-constant operand with identical opcode, we may be able to convert that into 2 independent shifts followed by the logic op.
Definition at line 1853 of file CombinerHelper.cpp.
References assert(), llvm::getIConstantVRegValWithLookThrough(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::ShiftOfShiftedLogic::Logic, llvm::ShiftOfShiftedLogic::LogicNonShiftReg, MI, MRI, llvm::ShiftOfShiftedLogic::Shift2, and llvm::ShiftOfShiftedLogic::ValSum.
matchShiftsTooBig()
bool CombinerHelper::matchShiftsTooBig (MachineInstr & MI)
Match shifts greater or equal to the bitwidth of the operation.
Definition at line 6510 of file CombinerHelper.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), llvm::LLT::getScalarSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::matchUnaryPredicate(), MI, and MRI.
matchShlOfVScale()
bool CombinerHelper::matchShlOfVScale (const MachineOperand & MO, BuildFnTy & MatchInfo)
Definition at line 465 of file CombinerHelperVectorOps.cpp.
References B, llvm::cast(), llvm::getIConstantVRegVal(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GShl::getShiftReg(), llvm::GVScale::getSrc(), llvm::GShl::getSrcReg(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isLegalOrBeforeLegalizer(), MRI, and llvm::APInt::shl().
matchShuffleToExtract()
bool CombinerHelper::matchShuffleToExtract (MachineInstr & MI)
Definition at line 556 of file CombinerHelper.cpp.
References assert(), and MI.
matchSimplifyAddToSub()
bool CombinerHelper::matchSimplifyAddToSub (MachineInstr & MI, std::tuple< Register, Register > & MatchInfo)
Return true if MI is a G_ADD which can be simplified to a G_SUB.
Definition at line 3015 of file CombinerHelper.cpp.
References llvm::PatternMatch::m_Neg(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchSimplifySelectToMinMax()
bool CombinerHelper::matchSimplifySelectToMinMax (MachineInstr & MI, BuildFnTy & MatchInfo)
Returns
true if it is possible to simplify a select instruction MI to a min/max instruction of some sort.
Definition at line 6463 of file CombinerHelper.cpp.
References assert(), Cond, llvm::MIPatternMatch::m_GTrunc(), llvm::MIPatternMatch::m_OneNonDBGUse(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchSubAddSameReg()
bool CombinerHelper::matchSubAddSameReg (MachineInstr & MI, BuildFnTy & MatchInfo)
Transform: (x + y) - y -> x (x + y) - x -> y x - (y + x) -> 0 - y x - (x + z) -> 0 - z.
Definition at line 5126 of file CombinerHelper.cpp.
References assert(), B, llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_GAdd(), llvm::MIPatternMatch::m_GSub(), llvm::MIPatternMatch::m_ICstOrSplat(), llvm::MIPatternMatch::m_Reg(), llvm::MIPatternMatch::m_SpecificICstOrSplat(), MI, llvm::MIPatternMatch::mi_match(), MRI, X, and Y.
matchSubOfVScale()
bool CombinerHelper::matchSubOfVScale (const MachineOperand & MO, BuildFnTy & MatchInfo)
Definition at line 445 of file CombinerHelperVectorOps.cpp.
References B, llvm::cast(), llvm::MachineInstr::getFlags(), llvm::GBinOp::getLHSReg(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::GBinOp::getRHSReg(), llvm::GVScale::getSrc(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isLegalOrBeforeLegalizer(), and MRI.
matchTruncBuildVectorFold()
bool CombinerHelper::matchTruncBuildVectorFold (MachineInstr & MI, Register & MatchInfo)
Definition at line 6321 of file CombinerHelper.cpp.
References llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_GBitcast(), llvm::MIPatternMatch::m_GBuildVector(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchTruncLshrBuildVectorFold()
bool CombinerHelper::matchTruncLshrBuildVectorFold (MachineInstr & MI, Register & MatchInfo)
Definition at line 6332 of file CombinerHelper.cpp.
References llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MIPatternMatch::m_GBitcast(), llvm::MIPatternMatch::m_GBuildVector(), llvm::MIPatternMatch::m_GCst(), llvm::MIPatternMatch::m_GLShr(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchUDivByConst()
bool CombinerHelper::matchUDivByConst (MachineInstr & MI)
Combine G_UDIV by constant into a multiply by magic constant.
Definition at line 5331 of file CombinerHelper.cpp.
References assert(), llvm::CallingConv::C, llvm::LLT::changeElementSize(), DL, llvm::getApproximateEVTForLLT(), llvm::AttributeList::getAttributes(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::isConstantOrConstantVector(), llvm::MachineInstr::IsExact, isLegalOrBeforeLegalizer(), llvm::LLT::isVector(), LI, llvm::matchUnaryPredicate(), MI, MRI, and llvm::LLT::scalar().
matchUMulHToLShr()
bool CombinerHelper::matchUMulHToLShr (MachineInstr & MI)
Definition at line 5566 of file CombinerHelper.cpp.
References assert(), llvm::CallingConv::C, llvm::dyn_cast(), llvm::TargetLoweringBase::getPreferredShiftAmountTy(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), isLegalOrBeforeLegalizer(), llvm::matchUnaryPredicate(), MI, and MRI.
matchUndefSelectCmp()
bool CombinerHelper::matchUndefSelectCmp (MachineInstr & MI)
Return true if a G_SELECT instruction MI has an undef comparison.
Definition at line 2748 of file CombinerHelper.cpp.
References assert(), llvm::getOpcodeDef(), MI, and MRI.
matchUndefShuffleVectorMask()
bool CombinerHelper::matchUndefShuffleVectorMask (MachineInstr & MI)
Return true if a G_SHUFFLE_VECTOR instruction MI has an undef mask.
Definition at line 2736 of file CombinerHelper.cpp.
References llvm::all_of(), assert(), and MI.
matchUndefStore()
bool CombinerHelper::matchUndefStore (MachineInstr & MI)
Return true if a G_STORE instruction MI is storing an undef value.
Definition at line 2742 of file CombinerHelper.cpp.
References assert(), llvm::getOpcodeDef(), MI, and MRI.
matchXorOfAndWithSameReg()
bool CombinerHelper::matchXorOfAndWithSameReg (MachineInstr & MI, std::pair< Register, Register > & MatchInfo)
Fold (xor (and x, y), y) -> (and (not x), y) {.
Definition at line 3503 of file CombinerHelper.cpp.
References assert(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::MIPatternMatch::m_GAnd(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, std::swap(), X, and Y.
matchZextOfTrunc()
bool CombinerHelper::matchZextOfTrunc (const MachineOperand & MO, BuildFnTy & MatchInfo)
Combine zext of trunc.
Definition at line 7494 of file CombinerHelper.cpp.
References B, llvm::cast(), llvm::getDefIgnoringCopies(), llvm::GenericMachineInstr::getReg(), llvm::MachineOperand::getReg(), llvm::LLT::getScalarSizeInBits(), llvm::GCastOp::getSrcReg(), llvm::MachineRegisterInfo::getType(), isLegalOrBeforeLegalizer(), MRI, llvm::MachineInstr::NonNeg, and llvm::MachineInstr::NoUWrap.
replaceInstWithConstant() [1/2]
void CombinerHelper::replaceInstWithConstant (MachineInstr & MI, APInt C)
Replace an instruction with a G_CONSTANT with value C.
Definition at line 2996 of file CombinerHelper.cpp.
References assert(), llvm::CallingConv::C, and MI.
replaceInstWithConstant() [2/2]
void CombinerHelper::replaceInstWithConstant (MachineInstr & MI, int64_t C)
Replace an instruction with a G_CONSTANT with value C.
Definition at line 2990 of file CombinerHelper.cpp.
References assert(), llvm::CallingConv::C, and MI.
replaceInstWithFConstant() [1/2]
void CombinerHelper::replaceInstWithFConstant (MachineInstr & MI, ConstantFP * CFP)
Replace an instruction with an G_FCONSTANT with value CFP.
Definition at line 3002 of file CombinerHelper.cpp.
References assert(), llvm::ConstantFP::getValueAPF(), and MI.
replaceInstWithFConstant() [2/2]
void CombinerHelper::replaceInstWithFConstant (MachineInstr & MI, double C)
Replace an instruction with a G_FCONSTANT with value C.
Definition at line 2984 of file CombinerHelper.cpp.
References assert(), llvm::CallingConv::C, and MI.
replaceInstWithUndef()
void CombinerHelper::replaceInstWithUndef (MachineInstr & MI)
Replace an instruction with a G_IMPLICIT_DEF.
Definition at line 3009 of file CombinerHelper.cpp.
References assert(), and MI.
replaceOpcodeWith()
void CombinerHelper::replaceOpcodeWith (MachineInstr & FromMI, unsigned ToOpcode) const
Replace the opcode in instruction with a new opcode and inform the observer of the changes.
Definition at line 187 of file CombinerHelper.cpp.
References llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), Observer, and llvm::MachineInstr::setDesc().
Referenced by AMDGPUCombinerHelper::applyFoldableFneg().
replaceRegOpWith()
void CombinerHelper::replaceRegOpWith (MachineRegisterInfo & MRI, MachineOperand & FromRegOp, Register ToReg) const
Replace a single register operand with a new register and inform the observer of the changes.
Definition at line 176 of file CombinerHelper.cpp.
References assert(), llvm::GISelChangeObserver::changedInstr(), llvm::GISelChangeObserver::changingInstr(), llvm::MachineOperand::getParent(), Observer, and llvm::MachineOperand::setReg().
Referenced by applyCombineExtendingLoads(), AMDGPUCombinerHelper::applyFoldableFneg(), and matchFreezeOfSingleMaybePoisonOperand().
replaceRegWith()
void CombinerHelper::replaceRegWith (MachineRegisterInfo & MRI, Register FromReg, Register ToReg) const
MachineRegisterInfo::replaceRegWith() and inform the observer of the changes.
Definition at line 164 of file CombinerHelper.cpp.
References llvm::GISelChangeObserver::changingAllUsesOfReg(), llvm::MachineRegisterInfo::constrainRegAttrs(), llvm::GISelChangeObserver::finishedChangingAllUsesOfReg(), MRI, Observer, and llvm::MachineRegisterInfo::replaceRegWith().
Referenced by applyCombineConcatVectors(), applyCombineCopy(), applyCombineExtendingLoads(), applyCombineShuffleVector(), applyCombineTruncOfExt(), applyCombineTruncOfShift(), applyCombineUnmergeMergeToPlainValues(), applyCombineUnmergeZExtToZExt(), applyExtractAllEltsFromBuildVector(), AMDGPUCombinerHelper::applyFoldableFneg(), applyNotCmp(), matchFreezeOfSingleMaybePoisonOperand(), matchOverlappingAnd(), replaceSingleDefInstWithOperand(), and replaceSingleDefInstWithReg().
replaceSingleDefInstWithOperand()
void CombinerHelper::replaceSingleDefInstWithOperand (MachineInstr & MI, unsigned OpIdx)
Delete MI and replace all of its uses with its OpIdx-th operand.
Definition at line 2895 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), MI, MRI, and replaceRegWith().
replaceSingleDefInstWithReg()
void CombinerHelper::replaceSingleDefInstWithReg (MachineInstr & MI, Register Replacement)
Delete MI and replace all of its uses with Replacement.
Definition at line 2905 of file CombinerHelper.cpp.
References assert(), llvm::canReplaceReg(), MI, MRI, and replaceRegWith().
Referenced by applyExtractVecEltBuildVec(), applySDivByConst(), and applyUDivByConst().
setRegBank()
void CombinerHelper::setRegBank (Register Reg, const RegisterBank * RegBank)
Set the register bank of Reg.
Does nothing if the RegBank is null. This is the counterpart to getRegBank.
Definition at line 200 of file CombinerHelper.cpp.
References MRI, and llvm::MachineRegisterInfo::setRegBank().
Referenced by applyPtrAddImmedChain().
tryCombine()
bool llvm::CombinerHelper::tryCombine (MachineInstr & MI)
Try to transform MI by using all of the above combine functions.
Returns true if changed.
tryCombineCopy()
bool CombinerHelper::tryCombineCopy (MachineInstr & MI)
If MI is COPY, try to combine it.
Returns true if MI changed.
Definition at line 205 of file CombinerHelper.cpp.
References applyCombineCopy(), matchCombineCopy(), and MI.
tryCombineExtendingLoads()
bool CombinerHelper::tryCombineExtendingLoads (MachineInstr & MI)
If MI is extend that consumes the result of a load, try to combine it.
Returns true if MI changed.
Definition at line 677 of file CombinerHelper.cpp.
References applyCombineExtendingLoads(), matchCombineExtendingLoads(), and MI.
tryCombineMemCpyFamily()
bool CombinerHelper::tryCombineMemCpyFamily (MachineInstr & MI, unsigned MaxLen = 0)
Optimize memcpy intrinsics et al, e.g.
constant len calls. /p MaxLen if non-zero specifies the max length of a mem libcall to inline.
For example (pre-indexed):
$addr = G_PTR_ADD $base, $offset
[...]
$val = G_LOAD $addr
[...]
$whatever = COPY $addr
-->
$val, $addr = G_INDEXED_LOAD $base, $offset, 1 (IsPre)
[...]
$whatever = COPY $addr
or (post-indexed):
G_STORE $val, $base
[...]
$addr = G_PTR_ADD $base, $offset
[...]
$whatever = COPY $addr
-->
$addr = G_INDEXED_STORE $val, $base, $offset
[...]
$whatever = COPY $addr
Definition at line 1640 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::getMF(), llvm::LegalizerHelper::Legalized, llvm::LegalizerHelper::lowerMemCpyFamily(), and MI.
tryCombineShiftToUnmerge()
bool CombinerHelper::tryCombineShiftToUnmerge (MachineInstr & MI, unsigned TargetShiftAmount)
Definition at line 2398 of file CombinerHelper.cpp.
References applyCombineShiftToUnmerge(), matchCombineShiftToUnmerge(), and MI.
tryCombineShuffleVector()
bool CombinerHelper::tryCombineShuffleVector (MachineInstr & MI)
Try to combine G_SHUFFLE_VECTOR into G_CONCAT_VECTORS.
Returns true if MI changed.
Precondition
MI.getOpcode() == G_SHUFFLE_VECTOR.
Definition at line 456 of file CombinerHelper.cpp.
References applyCombineShuffleVector(), matchCombineShuffleVector(), and MI.
tryEmitMemcpyInline()
bool CombinerHelper::tryEmitMemcpyInline (MachineInstr & MI)
Emit loads and stores that perform the given memcpy.
Assumes MI is a G_MEMCPY_INLINE TODO: implement dynamically sized inline memcpy, and rename: s/bool tryEmit/void emit/
Definition at line 1632 of file CombinerHelper.cpp.
References llvm::MachineIRBuilder::getMF(), llvm::LegalizerHelper::Legalized, and MI.
tryReassocBinOp()
bool CombinerHelper::tryReassocBinOp (unsigned Opc, Register DstReg, Register Op0, Register Op1, BuildFnTy & MatchInfo)
Try to reassociate to reassociate operands of a commutative binop.
Definition at line 4851 of file CombinerHelper.cpp.
References B, llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), getTargetLowering(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::isConstantOrConstantSplatVector(), and MRI.
Referenced by matchReassocCommBinOp().
Member Data Documentation
Builder
MachineIRBuilder& llvm::CombinerHelper::Builder protected
Definition at line 105 of file CombinerHelper.h.
Referenced by buildSDivUsingMul(), buildUDivUsingMul(), and getBuilder().
IsPreLegalize
bool llvm::CombinerHelper::IsPreLegalize protected
Definition at line 110 of file CombinerHelper.h.
Referenced by isPreLegalize().
KB
GISelKnownBits* llvm::CombinerHelper::KB protected
Definition at line 108 of file CombinerHelper.h.
Referenced by buildUDivUsingMul(), CombinerHelper(), getKnownBits(), matchAddOverflow(), matchCombineShlOfExtend(), matchCombineTruncOfShift(), matchCombineZextTrunc(), matchICmpToLHSKnownBits(), matchICmpToTrueFalseKnownBits(), matchOperandIsKnownToBeAPowerOfTwo(), matchRedundantAnd(), matchRedundantOr(), and matchRedundantSExtInReg().
LI
const LegalizerInfo* llvm::CombinerHelper::LI protected
Definition at line 111 of file CombinerHelper.h.
Referenced by isLegal(), matchBitfieldExtractFromAnd(), matchBitfieldExtractFromSExtInReg(), matchBitfieldExtractFromShr(), matchBitfieldExtractFromShrAnd(), matchCombineExtendingLoads(), matchCombineShlOfExtend(), and matchUDivByConst().
MDT
MachineDominatorTree* llvm::CombinerHelper::MDT protected
Definition at line 109 of file CombinerHelper.h.
Referenced by dominates().
MRI
MachineRegisterInfo& llvm::CombinerHelper::MRI protected
Definition at line 106 of file CombinerHelper.h.
Referenced by applyAshShlToSextInreg(), applyBuildFnMO(), applyCombineAddP2IToPtrAdd(), applyCombineConcatVectors(), applyCombineConstantFoldFpUnary(), applyCombineCopy(), applyCombineExtendingLoads(), applyCombineIndexedLoadStore(), applyCombineInsertVecElts(), applyCombineMulToShl(), applyCombineShiftToUnmerge(), applyCombineShlOfExtend(), applyCombineShuffleConcat(), applyCombineShuffleVector(), applyCombineTruncOfExt(), applyCombineTruncOfShift(), applyCombineUnmergeMergeToPlainValues(), applyCombineUnmergeZExtToZExt(), applyExpandFPowI(), AMDGPUCombinerHelper::applyExpandPromotedF16FMed3(), applyExtendThroughPhis(), applyExtractAllEltsFromBuildVector(), applyExtractVecEltBuildVec(), AMDGPUCombinerHelper::applyFoldableFneg(), applyFoldBinOpIntoSelect(), applyFsubToFneg(), applyFunnelShiftConstantModulo(), applyNotCmp(), applyOptBrCondByInvertingCond(), applyPtrAddImmedChain(), applyRotateOutOfRange(), applySDivByPow2(), applySextInRegOfLoad(), applyShiftImmedChain(), applyShiftOfShiftedLogic(), applyShuffleToExtract(), applySimplifyURemByPow2(), applyUDivByPow2(), applyUMulHToLShr(), applyXorOfAndWithSameReg(), buildSDivUsingMul(), buildUDivUsingMul(), canCombineFMadOrFMA(), getRegBank(), matchAddEToAddO(), matchAddOfVScale(), matchAddOverflow(), matchAddSubSameReg(), matchAndOrDisjointMask(), matchAshrShlToSextInreg(), matchBinOpSameVal(), matchBitfieldExtractFromAnd(), matchBitfieldExtractFromSExtInReg(), matchBitfieldExtractFromShr(), matchBitfieldExtractFromShrAnd(), matchBuildVectorIdentityFold(), matchCombineAddP2IToPtrAdd(), matchCombineAnyExtTrunc(), matchCombineConcatVectors(), matchCombineConstPtrAddToI2P(), matchCombineCopy(), matchCombineDivRem(), matchCombineExtendingLoads(), matchCombineExtOfExt(), matchCombineExtractedVectorLoad(), matchCombineFAddFMAFMulToFMadOrFMA(), matchCombineFAddFMulToFMadOrFMA(), matchCombineFAddFpExtFMulToFMadOrFMA(), matchCombineFAddFpExtFMulToFMadOrFMAAggressive(), matchCombineFMinMaxNaN(), matchCombineFSubFMulToFMadOrFMA(), matchCombineFSubFNegFMulToFMadOrFMA(), matchCombineFSubFpExtFMulToFMadOrFMA(), matchCombineFSubFpExtFNegFMulToFMadOrFMA(), matchCombineI2PToP2I(), matchCombineInsertVecElts(), matchCombineLoadWithAndMask(), matchCombineMergeUnmerge(), matchCombineMulToShl(), matchCombineShiftToUnmerge(), matchCombineShlOfExtend(), matchCombineShuffleConcat(), matchCombineShuffleVector(), matchCombineTruncOfExt(), matchCombineTruncOfShift(), matchCombineUnmergeConstant(), matchCombineUnmergeMergeToPlainValues(), matchCombineUnmergeUndef(), matchCombineUnmergeWithDeadLanesToTrunc(), matchCombineUnmergeZExtToZExt(), matchCombineZextTrunc(), matchCommuteConstantToRHS(), matchCommuteFPConstantToRHS(), matchCommuteShift(), matchConstantFoldBinOp(), matchConstantFoldCastOp(), matchConstantFoldFMA(), matchConstantFoldFPBinOp(), matchConstantFPOp(), matchConstantLargerBitWidth(), matchConstantOp(), matchConstantSelectCmp(), matchDivByPow2(), matchEqualDefs(), AMDGPUCombinerHelper::matchExpandPromotedF16FMed3(), matchExtendThroughPhis(), matchExtractAllEltsFromBuildVector(), matchExtractVecEltBuildVec(), matchExtractVectorElement(), matchExtractVectorElementWithBuildVector(), matchExtractVectorElementWithBuildVectorTrunc(), matchExtractVectorElementWithDifferentIndices(), matchExtractVectorElementWithShuffleVector(), AMDGPUCombinerHelper::matchFoldableFneg(), matchFoldBinOpIntoSelect(), matchFreezeOfSingleMaybePoisonOperand(), matchFsubToFneg(), matchFunnelShiftToRotate(), matchHoistLogicOpWithSameOpcodeHands(), matchICmpToLHSKnownBits(), matchICmpToTrueFalseKnownBits(), matchInsertExtractVecEltOutOfBounds(), matchInsertVectorElementOOB(), matchLoadOrCombine(), matchMulOBy0(), matchMulOBy2(), matchMulOfVScale(), matchNarrowBinopFeedingAnd(), matchNonNegZext(), matchNotCmp(), matchOperandIsKnownToBeAPowerOfTwo(), matchOperandIsUndef(), matchOperandIsZero(), matchOrShiftToFunnelShift(), matchOverlappingAnd(), matchPtrAddImmedChain(), matchPtrAddZero(), matchReassocConstantInnerLHS(), matchReassocConstantInnerRHS(), matchReassocFoldConstantsInSubTree(), matchReassocPtrAdd(), matchRedundantAnd(), matchRedundantBinOpInEquality(), matchRedundantNegOperands(), matchRedundantOr(), matchRedundantSExtInReg(), matchRotateOutOfRange(), matchSDivByConst(), matchSelectIMinMax(), matchSelectSameVal(), matchSextInRegOfLoad(), matchSextOfTrunc(), matchSextTruncSextLoad(), matchShiftImmedChain(), matchShiftOfShiftedLogic(), matchShiftsTooBig(), matchShlOfVScale(), matchSimplifyAddToSub(), matchSimplifySelectToMinMax(), matchSubAddSameReg(), matchSubOfVScale(), matchTruncBuildVectorFold(), matchTruncLshrBuildVectorFold(), matchUDivByConst(), matchUMulHToLShr(), matchUndefSelectCmp(), matchUndefStore(), matchXorOfAndWithSameReg(), matchZextOfTrunc(), replaceRegWith(), replaceSingleDefInstWithOperand(), replaceSingleDefInstWithReg(), setRegBank(), and tryReassocBinOp().
Observer
GISelChangeObserver& llvm::CombinerHelper::Observer protected
Definition at line 107 of file CombinerHelper.h.
Referenced by applyCombineExtendingLoads(), applyCombineExtOfExt(), applyCombineMulToShl(), applyCommuteBinOpOperands(), applyFunnelShiftToRotate(), applyNotCmp(), applyOptBrCondByInvertingCond(), applyPtrAddImmedChain(), applyRotateOutOfRange(), applyShiftImmedChain(), applyXorOfAndWithSameReg(), matchAddEToAddO(), matchAndOrDisjointMask(), matchFreezeOfSingleMaybePoisonOperand(), matchMulOBy2(), matchNarrowBinopFeedingAnd(), matchReassocConstantInnerLHS(), matchReassocConstantInnerRHS(), matchReassocFoldConstantsInSubTree(), matchRedundantNegOperands(), replaceOpcodeWith(), replaceRegOpWith(), and replaceRegWith().
RBI
const RegisterBankInfo* llvm::CombinerHelper::RBI protected
Definition at line 112 of file CombinerHelper.h.
Referenced by getRegBank().
TRI
const TargetRegisterInfo* llvm::CombinerHelper::TRI protected
Definition at line 113 of file CombinerHelper.h.
Referenced by getRegBank(), and matchFreezeOfSingleMaybePoisonOperand().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/CombinerHelper.h
lib/CodeGen/GlobalISel/CombinerHelper.cpp
lib/CodeGen/GlobalISel/CombinerHelperVectorOps.cpp