LLVM: llvm::cl::list_storage< DataType, StorageClass > Class Template Reference
llvm::cl::list_storage< DataType, StorageClass > Class Template Reference
#include "llvm/Support/CommandLine.h"
Public Member Functions
list_storage ()=default
void clear ()
bool setLocation (Option &O, StorageClass &L)
template<class T >
void addValue (const T &V, bool initial=false)
const std::vector< OptionValue< DataType > > & getDefault () const
void assignDefault ()
void overwriteDefault ()
bool isDefaultAssigned ()
Detailed Description
template<class DataType, class StorageClass>
class llvm::cl::list_storage< DataType, StorageClass >
Definition at line 1524 of file CommandLine.h.
Constructor & Destructor Documentation
list_storage()
template<class DataType , class StorageClass > llvm::cl::list_storage< DataType, StorageClass >::list_storage () default
Member Function Documentation
addValue()
template<class DataType , class StorageClass > template<class T > void llvm::cl::list_storage< DataType, StorageClass >::addValue (const T & V, bool initial = false) inline
Definition at line 1542 of file CommandLine.h.
References assert(), and llvm::Default.
Referenced by llvm::cl::list< DataType, StorageClass, ParserClass >::setInitialValues().
assignDefault()
template<class DataType , class StorageClass > void llvm::cl::list_storage< DataType, StorageClass >::assignDefault () inline
Definition at line 1555 of file CommandLine.h.
Referenced by llvm::cl::list< DataType, StorageClass, ParserClass >::setInitialValues().
clear()
template<class DataType , class StorageClass > void llvm::cl::list_storage< DataType, StorageClass >::clear () inline
Definition at line 1533 of file CommandLine.h.
Referenced by llvm::cl::list< DataType, StorageClass, ParserClass >::clear().
getDefault()
template<class DataType , class StorageClass > const std::vector< OptionValue< DataType > > & llvm::cl::list_storage< DataType, StorageClass >::getDefault () const inline
Definition at line 1551 of file CommandLine.h.
References llvm::Default.
isDefaultAssigned()
template<class DataType , class StorageClass > bool llvm::cl::list_storage< DataType, StorageClass >::isDefaultAssigned () inline
Definition at line 1557 of file CommandLine.h.
overwriteDefault()
template<class DataType , class StorageClass > void llvm::cl::list_storage< DataType, StorageClass >::overwriteDefault () inline
Definition at line 1556 of file CommandLine.h.
setLocation()
template<class DataType , class StorageClass > bool llvm::cl::list_storage< DataType, StorageClass >::setLocation (Option & O, StorageClass & L) inline
Definition at line 1535 of file CommandLine.h.
The documentation for this class was generated from the following file:
include/llvm/Support/CommandLine.h