LLVM: llvm::TargetMachine Class Reference
llvm::TargetMachine Class Reference
Primary interface to the complete machine description for the target machine.
#include "llvm/Target/TargetMachine.h"
Public Member Functions
TargetMachine (const TargetMachine &)=delete
void operator= (const TargetMachine &)=delete
virtual ~TargetMachine ()
const Target & getTarget () const
const Triple & getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
void setTargetFeatureString (StringRef FS)
virtual const TargetSubtargetInfo * getSubtargetImpl (const Function &) const
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
virtual TargetLoweringObjectFile * getObjFileLowering () const
virtual MachineFunctionInfo * createMachineFunctionInfo (BumpPtrAllocator &Allocator, const Function &F, const TargetSubtargetInfo *STI) const
Create the target's instance of MachineFunctionInfo.
virtual yaml::MachineFunctionInfo * createDefaultFuncInfoYAML () const
Allocate and return a default initialized instance of the YAML representation for the MachineFunctionInfo.
virtual yaml::MachineFunctionInfo * convertFuncInfoToYAML (const MachineFunction &MF) const
Allocate and initialize an instance of the YAML representation of the MachineFunctionInfo.
virtual bool parseMachineFunctionInfo (const yaml::MachineFunctionInfo &, PerFunctionMIParsingState &PFS, SMDiagnostic &Error, SMRange &SourceRange) const
Parse out the target's MachineFunctionInfo from the YAML reprsentation.
template<typename STC >
const STC & getSubtarget (const Function &F) const
This method returns a pointer to the specified type of TargetSubtargetInfo.
const DataLayout createDataLayout () const
Create a DataLayout.
bool isCompatibleDataLayout (const DataLayout &Candidate) const
Test if a DataLayout if compatible with the CodeGen for this target.
unsigned getPointerSize (unsigned AS) const
Get the pointer size for this target.
unsigned getPointerSizeInBits (unsigned AS) const
unsigned getProgramPointerSize () const
unsigned getAllocaPointerSize () const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
Return target specific asm information.
const MCRegisterInfo * getMCRegisterInfo () const
const MCInstrInfo * getMCInstrInfo () const
const MCSubtargetInfo * getMCSubtargetInfo () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
If intrinsic information is available, return it. If not, return null.
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
Returns the code generation relocation model.
CodeModel::Model getCodeModel () const
Returns the code model.
uint64_t getMaxCodeSize () const
Returns the maximum code size possible under the code model.
void setCodeModel (CodeModel::Model CM)
Set the code model.
void setLargeDataThreshold (uint64_t LDT)
bool isLargeGlobalValue (const GlobalValue *GV) const
bool isPositionIndependent () const
bool shouldAssumeDSOLocal (const GlobalValue *GV) const
bool useEmulatedTLS () const
Returns true if this target uses emulated TLS.
bool useTLSDESC () const
Returns true if this target uses TLS Descriptors.
TLSModel::Model getTLSModel (const GlobalValue *GV) const
Returns the TLS model which should be used for the given global variable.
CodeGenOptLevel getOptLevel () const
Returns the optimization level: None, Less, Default, or Aggressive.
void setOptLevel (CodeGenOptLevel Level)
Overrides the optimization level.
void setFastISel (bool Enable)
bool getO0WantsFastISel ()
void setO0WantsFastISel (bool Enable)
void setGlobalISel (bool Enable)
void setGlobalISelAbort (GlobalISelAbortMode Mode)
void setMachineOutliner (bool Enable)
void setSupportsDefaultOutlining (bool Enable)
void setSupportsDebugEntryValues (bool Enable)
void setCFIFixup (bool Enable)
bool getAIXExtendedAltivecABI () const
bool getUniqueSectionNames () const
bool getUniqueBasicBlockSectionNames () const
Return true if unique basic block section names must be generated.
bool getSeparateNamedSections () const
bool getDataSections () const
Return true if data objects should be emitted into their own section, corresponds to -fdata-sections.
bool getFunctionSections () const
Return true if functions should be emitted into their own section, corresponding to -ffunction-sections.
bool getIgnoreXCOFFVisibility () const
Return true if visibility attribute should not be emitted in XCOFF, corresponding to -mignore-xcoff-visibility.
bool getXCOFFTracebackTable () const
Return true if XCOFF traceback table should be emitted, corresponding to -xcoff-traceback-table.
llvm::BasicBlockSection getBBSectionsType () const
If basic blocks should be emitted into their own section, corresponding to -fbasic-block-sections.
const MemoryBuffer * getBBSectionsFuncListBuf () const
Get the list of functions and basic block ids that need unique sections.
virtual bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast between SrcAS and DestAS is a noop.
void setPGOOption (std::optional< PGOOptions > PGOOpt)
const std::optional< PGOOptions > & getPGOOption () const
virtual unsigned getAssumedAddrSpace (const Value *V) const
If the specified generic pointer could be assumed as a pointer to a specific address space, return that address space.
virtual std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const
If the specified predicate checks whether a generic pointer falls within a specified address space, return that generic pointer and the address space being queried.
TargetIRAnalysis getTargetIRAnalysis () const
Get a TargetIRAnalysis appropriate for the target.
virtual TargetTransformInfo getTargetTransformInfo (const Function &F) const
Return a TargetTransformInfo for a given function.
virtual void registerPassBuilderCallbacks (PassBuilder &)
Allow the target to modify the pass pipeline.
virtual void registerDefaultAliasAnalyses (AAManager &)
Allow the target to register alias analyses with the AAManager for use with the new pass manager.
virtual bool addPassesToEmitFile (PassManagerBase &, raw_pwrite_stream &, raw_pwrite_stream *, CodeGenFileType, bool=true, MachineModuleInfoWrapperPass *MMIWP=nullptr)
Add passes to the specified pass manager to get the specified file emitted.
virtual bool addPassesToEmitMC (PassManagerBase &, MCContext *&, raw_pwrite_stream &, bool=true)
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
virtual bool targetSchedulesPostRAScheduling () const
True if subtarget inserts the final scheduling pass on its own.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV) const
virtual unsigned getSjLjDataSize () const
virtual unsigned getAddressSpaceForPseudoSourceKind (unsigned Kind) const
getAddressSpaceForPseudoSourceKind - Given the kind of memory (e.g.
virtual bool splitModule (Module &M, unsigned NumParts, function_ref< void(std::unique_ptr< Module > MPart)> ModuleCallback)
Entry point for module splitting.
Static Public Member Functions
static std::pair< int, int > parseBinutilsVersion (StringRef Version)
Public Attributes
TargetOptions Options
Static Public Attributes
static constexpr unsigned DefaultSjLjDataSize = 32
The integer bit size to use for SjLj based exception handling.
Protected Member Functions
TargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes
const Target & TheTarget
The Target that this machine was created for.
const DataLayout DL
DataLayout for the target: keep ABI type size and alignment.
Triple TargetTriple
Triple string, CPU name, and target feature strings the TargetMachine instance is created with.
std::string TargetCPU
std::string TargetFS
Reloc::Model RM = Reloc::Static
CodeModel::Model CMModel = CodeModel::Small
uint64_t LargeDataThreshold = 0
CodeGenOptLevel OptLevel = CodeGenOptLevel::Default
std::unique_ptr< const MCAsmInfo > AsmInfo
Contains target specific asm information.
std::unique_ptr< const MCRegisterInfo > MRI
std::unique_ptr< const MCInstrInfo > MII
std::unique_ptr< const MCSubtargetInfo > STI
unsigned RequireStructuredCFG: 1
unsigned O0WantsFastISel: 1
std::optional< PGOOptions > PGOOption
Detailed Description
Primary interface to the complete machine description for the target machine.
All target-specific information should be accessible through this interface.
Definition at line 77 of file TargetMachine.h.
Constructor & Destructor Documentation
TargetMachine() [1/2]
TargetMachine::TargetMachine (const Target & T, StringRef DataLayoutString, const Triple & TargetTriple, StringRef CPU, StringRef FS, const TargetOptions & Options) protected
Definition at line 33 of file TargetMachine.cpp.
TargetMachine() [2/2]
llvm::TargetMachine::TargetMachine (const TargetMachine &) delete
~TargetMachine()
TargetMachine::~TargetMachine () virtual default
Member Function Documentation
addPassesToEmitFile()
virtual bool llvm::TargetMachine::addPassesToEmitFile (PassManagerBase & , raw_pwrite_stream & , raw_pwrite_stream * , CodeGenFileType , bool = true, MachineModuleInfoWrapperPass * MMIWP = nullptr) inline virtual
Add passes to the specified pass manager to get the specified file emitted.
Typically this will involve several steps of code generation. This method should return true if emission of this file type is not supported, or false on success. MMIWP is an optional parameter that, if set to non-nullptr, will be used to set the MachineModuloInfo for this PM.
Reimplemented in llvm::DirectXTargetMachine, and llvm::LLVMTargetMachine.
Definition at line 385 of file TargetMachine.h.
addPassesToEmitMC()
virtual bool llvm::TargetMachine::addPassesToEmitMC (PassManagerBase & , MCContext *& , raw_pwrite_stream & , bool = true) inline virtual
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
This method returns true if machine code is not supported. It fills the MCContext Ctx pointer which can be used to build custom MCStreamer.
Reimplemented in llvm::DirectXTargetMachine, llvm::LLVMTargetMachine, and llvm::NVPTXTargetMachine.
Definition at line 397 of file TargetMachine.h.
Referenced by llvm::orc::SimpleCompiler::operator()().
convertFuncInfoToYAML()
virtual yaml::MachineFunctionInfo * llvm::TargetMachine::convertFuncInfoToYAML (const MachineFunction & MF) const inline virtual
Allocate and initialize an instance of the YAML representation of the MachineFunctionInfo.
Reimplemented in llvm::AArch64TargetMachine, llvm::ARMBaseTargetMachine, llvm::GCNTargetMachine, llvm::RISCVTargetMachine, llvm::WebAssemblyTargetMachine, and llvm::X86TargetMachine.
Definition at line 156 of file TargetMachine.h.
createDataLayout()
const DataLayout llvm::TargetMachine::createDataLayout () const inline
Create a DataLayout.
Definition at line 176 of file TargetMachine.h.
References DL.
createDefaultFuncInfoYAML()
virtual yaml::MachineFunctionInfo * llvm::TargetMachine::createDefaultFuncInfoYAML () const inline virtual
Allocate and return a default initialized instance of the YAML representation for the MachineFunctionInfo.
Reimplemented in llvm::AArch64TargetMachine, llvm::ARMBaseTargetMachine, llvm::GCNTargetMachine, llvm::RISCVTargetMachine, llvm::WebAssemblyTargetMachine, and llvm::X86TargetMachine.
Definition at line 149 of file TargetMachine.h.
createMachineFunctionInfo()
virtual MachineFunctionInfo * llvm::TargetMachine::createMachineFunctionInfo (BumpPtrAllocator & Allocator, const Function & F, const TargetSubtargetInfo * STI) const inline virtual
Create the target's instance of MachineFunctionInfo.
Reimplemented in llvm::AArch64TargetMachine, llvm::ARCTargetMachine, llvm::ARMBaseTargetMachine, llvm::AVRTargetMachine, llvm::CSKYTargetMachine, llvm::GCNTargetMachine, llvm::HexagonTargetMachine, llvm::LanaiTargetMachine, llvm::LoongArchTargetMachine, llvm::M68kTargetMachine, llvm::MipsTargetMachine, llvm::MSP430TargetMachine, llvm::NVPTXTargetMachine, llvm::PPCTargetMachine, llvm::R600TargetMachine, llvm::RISCVTargetMachine, llvm::SparcTargetMachine, llvm::SystemZTargetMachine, llvm::VETargetMachine, llvm::WebAssemblyTargetMachine, llvm::X86TargetMachine, and llvm::XCoreTargetMachine.
Definition at line 142 of file TargetMachine.h.
getAddressSpaceForPseudoSourceKind()
virtual unsigned llvm::TargetMachine::getAddressSpaceForPseudoSourceKind (unsigned Kind) const inline virtual
getAddressSpaceForPseudoSourceKind - Given the kind of memory (e.g.
stack) the target returns the corresponding address space.
Reimplemented in llvm::AMDGPUTargetMachine.
Definition at line 422 of file TargetMachine.h.
getAIXExtendedAltivecABI()
bool llvm::TargetMachine::getAIXExtendedAltivecABI () const inline
Definition at line 281 of file TargetMachine.h.
References llvm::TargetOptions::EnableAIXExtendedAltivecABI, and Options.
Referenced by llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCallPreservedMask(), llvm::PPCRegisterInfo::getRegPressureLimit(), and llvm::PPCRegisterInfo::getReservedRegs().
getAllocaPointerSize()
unsigned llvm::TargetMachine::getAllocaPointerSize () const inline
Definition at line 202 of file TargetMachine.h.
References DL, llvm::DataLayout::getAllocaAddrSpace(), and llvm::DataLayout::getPointerSize().
getAssumedAddrSpace()
virtual unsigned llvm::TargetMachine::getAssumedAddrSpace (const Value * V) const inline virtual
If the specified generic pointer could be assumed as a pointer to a specific address space, return that address space.
Under offloading programming, the offloading target may be passed with values only prepared on the host side and could assume certain properties.
Reimplemented in llvm::AMDGPUTargetMachine.
Definition at line 343 of file TargetMachine.h.
Referenced by llvm::BasicTTIImplBase< T >::getAssumedAddrSpace().
getBBSectionsFuncListBuf()
const MemoryBuffer * llvm::TargetMachine::getBBSectionsFuncListBuf () const inline
Get the list of functions and basic block ids that need unique sections.
Definition at line 325 of file TargetMachine.h.
References llvm::TargetOptions::BBSectionsFuncListBuf, and Options.
Referenced by llvm::TargetPassConfig::addMachinePasses(), and llvm::BasicBlockSectionsProfileReaderAnalysis::run().
getBBSectionsType()
llvm::BasicBlockSection llvm::TargetMachine::getBBSectionsType () const inline
If basic blocks should be emitted into their own section, corresponding to -fbasic-block-sections.
Definition at line 320 of file TargetMachine.h.
References llvm::TargetOptions::BBSections, and Options.
Referenced by llvm::TargetPassConfig::addMachinePasses(), assignSections(), and llvm::MIRParserImpl::initializeMachineFunction().
getCodeModel()
CodeModel::Model llvm::TargetMachine::getCodeModel () const inline
Returns the code model.
The choices are small, kernel, medium, large, and target default.
Definition at line 232 of file TargetMachine.h.
References CMModel.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::X86InstrInfo::canMakeTailCallConditional(), llvm::M68kSubtarget::classifyGlobalReference(), llvm::X86Subtarget::classifyGlobalReference(), llvm::M68kSubtarget::classifyLocalReference(), llvm::X86Subtarget::classifyLocalReference(), llvm::X86AsmPrinter::emitEndOfAsmFile(), llvm::AsmPrinter::emitPCSections(), llvm::AArch64FrameLowering::emitPrologue(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::PPCSubtarget::getCodeModel(), llvm::M68kSubtarget::getJumpTableEncoding(), getMaxCodeSize(), llvm::TargetLoweringObjectFileXCOFF::getSectionForTOCEntry(), llvm::TargetLoweringObjectFile::Initialize(), llvm::TargetLoweringObjectFileELF::Initialize(), llvm::PPCTargetLowering::isAccessedAsGotIndirect(), llvm::LanaiTargetObjectFile::isGlobalInSmallSection(), llvm::PPCSubtarget::isGVIndirectSymbol(), isLargeGlobalValue(), llvm::X86TargetLowering::isLegalAddressingMode(), IsSmallObject(), llvm::PPCSubtarget::isUsingPCRelativeCalls(), llvm::LoongArchTargetLowering::LowerCall(), needsPrologueENDBR(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::PPCInstrInfo::shouldReduceRegisterPressure(), and llvm::AArch64Subtarget::useSmallAddressing().
getDataSections()
bool llvm::TargetMachine::getDataSections () const inline
Return true if data objects should be emitted into their own section, corresponds to -fdata-sections.
Definition at line 298 of file TargetMachine.h.
References llvm::TargetOptions::DataSections, and Options.
Referenced by llvm::TargetLoweringObjectFileXCOFF::getTargetSymbol(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileWasm::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal().
getFunctionSections()
bool llvm::TargetMachine::getFunctionSections () const inline
Return true if functions should be emitted into their own section, corresponding to -ffunction-sections.
Definition at line 304 of file TargetMachine.h.
References llvm::TargetOptions::FunctionSections, and Options.
Referenced by llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileXCOFF::getFunctionEntryPointSymbol(), llvm::TargetLoweringObjectFileELF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileXCOFF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileELF::getSectionForLSDA(), llvm::TargetLoweringObjectFileXCOFF::getSectionForLSDA(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileWasm::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal().
getIgnoreXCOFFVisibility()
bool llvm::TargetMachine::getIgnoreXCOFFVisibility () const inline
Return true if visibility attribute should not be emitted in XCOFF, corresponding to -mignore-xcoff-visibility.
Definition at line 310 of file TargetMachine.h.
References llvm::TargetOptions::IgnoreXCOFFVisibility, and Options.
getIntrinsicInfo()
virtual const TargetIntrinsicInfo * llvm::TargetMachine::getIntrinsicInfo () const inline virtual
If intrinsic information is available, return it. If not, return null.
Definition at line 219 of file TargetMachine.h.
getMaxCodeSize()
uint64_t TargetMachine::getMaxCodeSize () const
Returns the maximum code size possible under the code model.
Definition at line 146 of file TargetMachine.cpp.
References getCodeModel(), llvm::CodeModel::Kernel, llvm::CodeModel::Large, llvm_unreachable, llvm::maxUIntN(), llvm::CodeModel::Medium, llvm::CodeModel::Small, and llvm::CodeModel::Tiny.
getMCAsmInfo()
const MCAsmInfo * llvm::TargetMachine::getMCAsmInfo () const inline
Return target specific asm information.
Definition at line 212 of file TargetMachine.h.
References AsmInfo.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::TargetPassConfig::addPassesToHandleExceptions(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::canUseLEAForSPInEpilogue(), llvm::LLVMTargetMachine::createMCStreamer(), llvm::AsmPrinter::doInitialization(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::emitEpilogue(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::TargetFrameLowering::enableCFIFixup(), ExpandMOVImmSExti8(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::AArch64InstrInfo::getInstSizeInBytes(), llvm::ARCInstrInfo::getInstSizeInBytes(), llvm::ARMBaseInstrInfo::getInstSizeInBytes(), llvm::CSKYInstrInfo::getInstSizeInBytes(), llvm::LoongArchInstrInfo::getInstSizeInBytes(), llvm::MipsInstrInfo::getInstSizeInBytes(), llvm::MSP430InstrInfo::getInstSizeInBytes(), llvm::PPCInstrInfo::getInstSizeInBytes(), llvm::RISCVInstrInfo::getInstSizeInBytes(), llvm::SIInstrInfo::getInstSizeInBytes(), llvm::SparcInstrInfo::getInstSizeInBytes(), llvm::SystemZInstrInfo::getInstSizeInBytes(), llvm::TargetLoweringObjectFileMachO::getNameWithPrefix(), llvm::HexagonInstrInfo::getSize(), llvm::ARMElfTargetObjectFile::getTTypeGlobalReference(), llvm::X86::isExtendedSwiftAsyncFrameSupported(), llvm::AArch64FunctionInfo::needsDwarfUnwindInfo(), llvm::WebAssemblyFrameLowering::needsPrologForEH(), needsWinCFI(), needsWinCFI(), needsWinCFI(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), and llvm::ARMSubtarget::splitFramePointerPush().
getMCInstrInfo()
const MCInstrInfo * llvm::TargetMachine::getMCInstrInfo () const inline
Definition at line 215 of file TargetMachine.h.
References llvm::MCInstrInfo::get(), and MII.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitMC(), and llvm::LLVMTargetMachine::createMCStreamer().
getMCRegisterInfo()
const MCRegisterInfo * llvm::TargetMachine::getMCRegisterInfo () const inline
Definition at line 214 of file TargetMachine.h.
References llvm::MCRegisterInfo::get(), and MRI.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute(), llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::LLVMTargetMachine::createMCStreamer(), and llvm::SystemZAsmPrinter::PrintAsmOperand().
getMCSubtargetInfo()
const MCSubtargetInfo * llvm::TargetMachine::getMCSubtargetInfo () const inline
Definition at line 216 of file TargetMachine.h.
References STI.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::AMDGPUTargetMachine::AMDGPUTargetMachine(), llvm::LLVMTargetMachine::createMCStreamer(), llvm::AsmPrinter::doInitialization(), llvm::AsmPrinter::emitAlignment(), llvm::AMDGPUAsmPrinter::getGlobalSTI(), llvm::ARMElfTargetObjectFile::Initialize(), and llvm::CSKYAsmPrinter::runOnMachineFunction().
getNameWithPrefix()
void TargetMachine::getNameWithPrefix (SmallVectorImpl< char > & Name, const GlobalValue * GV, Mangler & Mang, bool MayAlwaysUsePrivate = false) const
Definition at line 275 of file TargetMachine.cpp.
References llvm::Mangler::getNameWithPrefix(), llvm::TargetLoweringObjectFile::getNameWithPrefix(), getObjFileLowering(), llvm::GlobalValue::hasPrivateLinkage(), and Name.
Referenced by llvm::AArch64MCInstLower::GetGlobalValueSymbol(), llvm::AsmPrinter::getNameWithPrefix(), getSymbol(), and llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase().
getO0WantsFastISel()
bool llvm::TargetMachine::getO0WantsFastISel () inline
Definition at line 263 of file TargetMachine.h.
References O0WantsFastISel.
Referenced by llvm::TargetPassConfig::addCoreISelPasses(), and llvm::OptLevelChanger::OptLevelChanger().
getObjFileLowering()
virtual TargetLoweringObjectFile * llvm::TargetMachine::getObjFileLowering () const inline virtual
Reimplemented in llvm::AArch64TargetMachine, llvm::AMDGPUTargetMachine, llvm::ARCTargetMachine, llvm::ARMBaseTargetMachine, llvm::AVRTargetMachine, llvm::BPFTargetMachine, llvm::CSKYTargetMachine, llvm::DirectXTargetMachine, llvm::HexagonTargetMachine, llvm::LanaiTargetMachine, llvm::LoongArchTargetMachine, llvm::M68kTargetMachine, llvm::MipsTargetMachine, llvm::MSP430TargetMachine, llvm::NVPTXTargetMachine, llvm::PPCTargetMachine, llvm::RISCVTargetMachine, llvm::SparcTargetMachine, llvm::SPIRVTargetMachine, llvm::SystemZTargetMachine, llvm::VETargetMachine, llvm::WebAssemblyTargetMachine, llvm::X86TargetMachine, llvm::XCoreTargetMachine, and llvm::XtensaTargetMachine.
Definition at line 136 of file TargetMachine.h.
Referenced by getNameWithPrefix(), llvm::AsmPrinter::getObjFileLowering(), getSymbol(), llvm::LanaiTargetLowering::LowerConstantPool(), llvm::LanaiTargetLowering::LowerGlobalAddress(), and llvm::MachineModuleInfo::MachineModuleInfo().
getOptLevel()
CodeGenOptLevel TargetMachine::getOptLevel () const
Returns the optimization level: None, Less, Default, or Aggressive.
Definition at line 266 of file TargetMachine.cpp.
References OptLevel.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::TargetPassConfig::addCoreISelPasses(), llvm::AMDGPUPassConfig::addIRPasses(), llvm::AMDGPUPassConfig::addPreISel(), AlignBlocks(), llvm::CodeViewDebug::beginFunctionImpl(), canOptimizeTLSDFormToXForm(), llvm::SwitchCG::SwitchLowering::findJumpTables(), llvm::GISelKnownBitsAnalysis::get(), llvm::AMDGPUPassConfig::getCSEConfig(), llvm::HexagonFrameLowering::getFrameIndexReference(), llvm::PPCInstrInfo::getMachineCombinerPatterns(), llvm::TargetPassConfig::getOptLevel(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::HexagonFrameLowering::hasFP(), isOptNone(), llvm::AMDGPUPassConfig::isPassEnabled(), llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::InstructionSelect::runOnMachineFunction(), and llvm::RISCVDAGToDAGISel::Select().
getPGOOption()
const std::optional< PGOOptions > & llvm::TargetMachine::getPGOOption () const inline
Definition at line 335 of file TargetMachine.h.
References PGOOption.
getPointerSize()
unsigned llvm::TargetMachine::getPointerSize (unsigned AS) const inline
Get the pointer size for this target.
This is the only time the DataLayout in the TargetMachine is used.
Definition at line 190 of file TargetMachine.h.
References DL, and llvm::DataLayout::getPointerSize().
Referenced by llvm::SystemZFrameLowering::create(), llvm::AsmPrinter::getPointerSize(), llvm::AVRTargetMachine::isNoopAddrSpaceCast(), and llvm::X86TargetMachine::isNoopAddrSpaceCast().
getPointerSizeInBits()
unsigned llvm::TargetMachine::getPointerSizeInBits (unsigned AS) const inline
Definition at line 194 of file TargetMachine.h.
References DL, and llvm::DataLayout::getPointerSizeInBits().
getPredicatedAddrSpace()
virtual std::pair< const Value *, unsigned > llvm::TargetMachine::getPredicatedAddrSpace (const Value * V) const inline virtual
If the specified predicate checks whether a generic pointer falls within a specified address space, return that generic pointer and the address space being queried.
Such predicates could be specified in @llvm.assume intrinsics for the optimizer to assume that the given generic pointer always falls within the address space based on that predicate.
Reimplemented in llvm::AMDGPUTargetMachine, and llvm::NVPTXTargetMachine.
Definition at line 353 of file TargetMachine.h.
Referenced by llvm::BasicTTIImplBase< T >::getPredicatedAddrSpace().
getProgramPointerSize()
unsigned llvm::TargetMachine::getProgramPointerSize () const inline
Definition at line 198 of file TargetMachine.h.
References DL, llvm::DataLayout::getPointerSize(), and llvm::DataLayout::getProgramAddressSpace().
Referenced by llvm::AsmPrinter::emitStackSizeSection().
getRelocationModel()
Reloc::Model TargetMachine::getRelocationModel () const
Returns the code generation relocation model.
The choices are static, PIC, and dynamic-no-pic, and target default.
The choices are static, PIC, and dynamic-no-pic.
Definition at line 144 of file TargetMachine.cpp.
References RM.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute(), llvm::X86Subtarget::classifyGlobalFunctionReference(), llvm::X86Subtarget::classifyGlobalReference(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::MipsSubtarget::getRelocationModel(), llvm::AsmPrinter::getSymbolPreferLocal(), getTLSModel(), llvm::TargetLoweringObjectFileMachO::Initialize(), llvm::TargetLoweringBase::insertSSPDeclarations(), llvm::X86Subtarget::isLegalToCallImmediateAddr(), llvm::HexagonTargetLowering::isOffsetFoldingLegal(), isPositionIndependent(), llvm::ARMSubtarget::isROPI(), llvm::ARMSubtarget::isRWPI(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), shouldAssumeDSOLocal(), and transformCallee().
getSeparateNamedSections()
bool llvm::TargetMachine::getSeparateNamedSections () const inline
Definition at line 292 of file TargetMachine.h.
References Options, and llvm::TargetOptions::SeparateNamedSections.
getSjLjDataSize()
virtual unsigned llvm::TargetMachine::getSjLjDataSize () const inline virtual
Reimplemented in llvm::VETargetMachine.
Definition at line 416 of file TargetMachine.h.
References DefaultSjLjDataSize.
getSubtarget()
template<typename STC > const STC & llvm::TargetMachine::getSubtarget (const Function & F) const inline
This method returns a pointer to the specified type of TargetSubtargetInfo.
In debug builds, it verifies that the object being returned is of the correct type.
Definition at line 171 of file TargetMachine.h.
References F, and getSubtargetImpl().
Referenced by llvm::PhysicalRegisterUsageInfo::print().
getSubtargetImpl()
virtual const TargetSubtargetInfo * llvm::TargetMachine::getSubtargetImpl (const Function &) const inline virtual
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented in llvm::AArch64TargetMachine, llvm::AMDGPUTargetMachine, llvm::ARCTargetMachine, llvm::ARMBaseTargetMachine, llvm::AVRTargetMachine, llvm::BPFTargetMachine, llvm::CSKYTargetMachine, llvm::DirectXTargetMachine, llvm::GCNTargetMachine, llvm::HexagonTargetMachine, llvm::LanaiTargetMachine, llvm::LoongArchTargetMachine, llvm::M68kTargetMachine, llvm::MipsTargetMachine, llvm::MSP430TargetMachine, llvm::NVPTXTargetMachine, llvm::PPCTargetMachine, llvm::R600TargetMachine, llvm::RISCVTargetMachine, llvm::SparcTargetMachine, llvm::SPIRVTargetMachine, llvm::SystemZTargetMachine, llvm::VETargetMachine, llvm::WebAssemblyTargetMachine, llvm::X86TargetMachine, llvm::XCoreTargetMachine, and llvm::XtensaTargetMachine.
Definition at line 133 of file TargetMachine.h.
Referenced by llvm::AVRAsmPrinter::doFinalization(), llvm::AVRAsmPrinter::emitStartOfAsmFile(), llvm::MachineModuleInfo::getOrCreateMachineFunction(), getSubtarget(), llvm::ExpandLargeDivRemPass::run(), llvm::ExpandLargeFpConvertPass::run(), llvm::ExpandMemCmpPass::run(), llvm::IndirectBrExpandPass::run(), llvm::InterleavedAccessPass::run(), and llvm::MachineFunctionAnalysis::run().
getSymbol()
MCSymbol * TargetMachine::getSymbol (const GlobalValue * GV) const
Definition at line 288 of file TargetMachine.cpp.
References llvm::MCObjectFileInfo::getContext(), llvm::TargetLoweringObjectFile::getMangler(), getNameWithPrefix(), getObjFileLowering(), llvm::MCContext::getOrCreateSymbol(), and llvm::TargetLoweringObjectFile::getTargetSymbol().
Referenced by llvm::TargetLoweringObjectFile::emitCGProfileMetadata(), llvm::AIXException::endFunction(), llvm::AArch64_MachoTargetObjectFile::getCFIPersonalitySymbol(), llvm::TargetLoweringObjectFile::getCFIPersonalitySymbol(), llvm::TargetLoweringObjectFileELF::getCFIPersonalitySymbol(), llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::X86_64MachoTargetObjectFile::getCFIPersonalitySymbol(), llvm::NVPTXTargetLowering::getParamName(), llvm::AsmPrinter::getSymbol(), llvm::AsmPrinter::getSymbolPreferLocal(), llvm::AArch64_MachoTargetObjectFile::getTTypeGlobalReference(), llvm::ARMElfTargetObjectFile::getTTypeGlobalReference(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::X86_64MachoTargetObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileELF::lowerDSOLocalEquivalent(), llvm::TargetLoweringObjectFileELF::lowerRelativeReference(), llvm::TargetLoweringObjectFileWasm::lowerRelativeReference(), and llvm::TargetLoweringObjectFileGOFF::SelectSectionForGlobal().
getTarget()
const Target & llvm::TargetMachine::getTarget () const inline
Definition at line 124 of file TargetMachine.h.
References TheTarget.
Referenced by llvm::LLVMTargetMachine::addAsmPrinter(), llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::LLVMTargetMachine::createMCStreamer(), and llvm::X86AsmPrinter::runOnMachineFunction().
getTargetCPU()
StringRef llvm::TargetMachine::getTargetCPU () const inline
Definition at line 127 of file TargetMachine.h.
References TargetCPU.
Referenced by llvm::MipsAsmPrinter::emitStartOfAsmFile(), llvm::AMDGPUTargetMachine::getGPUName(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), and llvm::LLVMTargetMachine::initAsmInfo().
getTargetFeatureString()
StringRef llvm::TargetMachine::getTargetFeatureString () const inline
Definition at line 128 of file TargetMachine.h.
References TargetFS.
Referenced by llvm::MipsAsmPrinter::emitStartOfAsmFile(), llvm::AMDGPUTargetMachine::getFeatureString(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), and llvm::LLVMTargetMachine::initAsmInfo().
getTargetIRAnalysis()
TargetIRAnalysis TargetMachine::getTargetIRAnalysis () const
Get a TargetIRAnalysis appropriate for the target.
This is used to construct the new pass manager's target IR analysis pass, set up appropriately for this target machine. Even the old pass manager uses this to answer queries about the IR.
Definition at line 299 of file TargetMachine.cpp.
References F, and getTargetTransformInfo().
Referenced by llvm::TargetPassConfig::addISelPasses().
getTargetTransformInfo()
TargetTransformInfo TargetMachine::getTargetTransformInfo (const Function & F) const virtual
Return a TargetTransformInfo for a given function.
The returned TargetTransformInfo is specialized to the subtarget corresponding to F.
Reimplemented in llvm::AArch64TargetMachine, llvm::ARCTargetMachine, llvm::ARMBaseTargetMachine, llvm::BPFTargetMachine, llvm::DirectXTargetMachine, llvm::GCNTargetMachine, llvm::HexagonTargetMachine, llvm::LanaiTargetMachine, llvm::LLVMTargetMachine, llvm::LoongArchTargetMachine, llvm::MipsTargetMachine, llvm::NVPTXTargetMachine, llvm::PPCTargetMachine, llvm::R600TargetMachine, llvm::RISCVTargetMachine, llvm::SPIRVTargetMachine, llvm::SystemZTargetMachine, llvm::VETargetMachine, llvm::WebAssemblyTargetMachine, llvm::X86TargetMachine, and llvm::XCoreTargetMachine.
Definition at line 271 of file TargetMachine.cpp.
References F.
Referenced by getTargetIRAnalysis(), and llvm::SelectionDAGBuilder::shouldKeepJumpConditionsTogether().
getTargetTriple()
const Triple & llvm::TargetMachine::getTargetTriple () const inline
Definition at line 126 of file TargetMachine.h.
References TargetTriple.
Referenced by llvm::AMDGPUPassConfig::addCodeGenPrepare(), llvm::AMDGPUPassConfig::addIRPasses(), llvm::TargetPassConfig::addIRPasses(), llvm::DwarfCompileUnit::addLocationAttribute(), llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::LLVMTargetMachine::createMCStreamer(), createPPCAsmPrinterPass(), llvm::AsmPrinter::doFinalization(), llvm::AMDGPUAsmPrinter::doInitialization(), llvm::AsmPrinter::doInitialization(), llvm::TargetInstrInfo::duplicate(), llvm::DwarfDebug::DwarfDebug(), llvm::DwarfDebug::emitDebugLocValue(), llvm::AMDGPUAsmPrinter::emitEndOfAsmFile(), llvm::ARMAsmPrinter::emitEndOfAsmFile(), llvm::CSKYAsmPrinter::emitEndOfAsmFile(), llvm::HexagonAsmPrinter::emitEndOfAsmFile(), llvm::X86AsmPrinter::emitEndOfAsmFile(), llvm::X86FrameLowering::emitEpilogue(), llvm::AsmPrinter::emitFunctionBody(), llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), llvm::SystemZAsmPrinter::emitFunctionBodyEnd(), llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel(), llvm::AsmPrinter::emitFunctionEntryLabel(), llvm::AsmPrinter::emitGlobalAlias(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), llvm::AsmPrinter::emitGlobalVariable(), llvm::AsmPrinter::emitPatchableFunctionEntries(), llvm::ARMAsmPrinter::emitStartOfAsmFile(), llvm::CSKYAsmPrinter::emitStartOfAsmFile(), llvm::HexagonAsmPrinter::emitStartOfAsmFile(), llvm::MipsAsmPrinter::emitStartOfAsmFile(), llvm::SystemZAsmPrinter::emitStartOfAsmFile(), llvm::X86AsmPrinter::emitStartOfAsmFile(), llvm::AsmPrinter::emitXRayTable(), llvm::TargetLowering::expandIndirectJTBranch(), llvm::AMDGPUSubtarget::get(), llvm::AArch64MCInstLower::GetGlobalValueSymbol(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::M68kMCInstLower::GetSymbolFromOperand(), llvm::AsmPrinter::getSymbolPreferLocal(), llvm::LLVMTargetMachine::initAsmInfo(), llvm::TargetLoweringObjectFileELF::Initialize(), llvm::TargetLoweringObjectFileXCOFF::Initialize(), llvm::TargetLoweringBase::insertSSPDeclarations(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), isLargeGlobalValue(), llvm::PPCTargetMachine::isPPC64(), llvm::AArch64MCInstLower::LowerSymbolOperand(), llvm::AsmPrinter::preprocessXXStructorList(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::FastISel::selectOperator(), llvm::AMDGPUTargetObjectFile::SelectSectionForGlobal(), llvm::FastISel::selectXRayCustomEvent(), llvm::FastISel::selectXRayTypedEvent(), llvm::AsmPrinter::SetupMachineFunction(), shouldAssumeDSOLocal(), llvm::SITargetLowering::shouldEmitFixup(), shouldLowerMemFuncForSize(), shouldLowerMemFuncForSize(), llvm::TargetLoweringObjectFileCOFF::shouldPutJumpTableInFunctionSection(), llvm::TailDuplicator::shouldTailDuplicate(), llvm::SITargetLowering::shouldUseLDSConstAddress(), llvm::SelectionDAGBuilder::visitSPDescriptorFailure(), and llvm::WinException::WinException().
getTLSModel()
TLSModel::Model TargetMachine::getTLSModel (const GlobalValue * GV) const
Returns the TLS model which should be used for the given global variable.
Definition at line 238 of file TargetMachine.cpp.
References llvm::PIELevel::Default, llvm::TLSModel::GeneralDynamic, llvm::GlobalValue::getParent(), llvm::Module::getPIELevel(), getRelocationModel(), getSelectedTLSModel(), llvm::TLSModel::InitialExec, llvm::TLSModel::LocalDynamic, llvm::TLSModel::LocalExec, llvm::Reloc::PIC_, RM, and shouldAssumeDSOLocal().
Referenced by isEligibleToFoldADDIForFasterLocalAccesses(), llvm::HexagonTargetLowering::LowerGlobalTLSAddress(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), and llvm::AArch64MCInstLower::lowerSymbolOperandELF().
getUniqueBasicBlockSectionNames()
bool llvm::TargetMachine::getUniqueBasicBlockSectionNames () const inline
Return true if unique basic block section names must be generated.
Definition at line 288 of file TargetMachine.h.
References Options, and llvm::TargetOptions::UniqueBasicBlockSectionNames.
Referenced by llvm::TargetLoweringObjectFileELF::getSectionForMachineBasicBlock().
getUniqueSectionNames()
bool llvm::TargetMachine::getUniqueSectionNames () const inline
Definition at line 285 of file TargetMachine.h.
References Options, and llvm::TargetOptions::UniqueSectionNames.
Referenced by llvm::TargetLoweringObjectFileELF::getSectionForLSDA().
getXCOFFTracebackTable()
bool llvm::TargetMachine::getXCOFFTracebackTable () const inline
Return true if XCOFF traceback table should be emitted, corresponding to -xcoff-traceback-table.
Definition at line 316 of file TargetMachine.h.
References Options, and llvm::TargetOptions::XCOFFTracebackTable.
isCompatibleDataLayout()
bool llvm::TargetMachine::isCompatibleDataLayout (const DataLayout & Candidate) const inline
Test if a DataLayout if compatible with the CodeGen for this target.
The LLVM Module owns a DataLayout that is used for the target independent optimizations and code generation. This hook provides a target specific check on the validity of this DataLayout.
Definition at line 183 of file TargetMachine.h.
References DL.
isLargeGlobalValue()
bool TargetMachine::isLargeGlobalValue (const GlobalValue * GV) const
Definition at line 43 of file TargetMachine.cpp.
References DL, llvm::dyn_cast(), llvm::GlobalValue::getAliaseeObject(), getCodeModel(), getTargetTriple(), llvm::DataLayout::getTypeAllocSize(), llvm::CodeModel::Large, LargeDataThreshold, llvm::CodeModel::Medium, Name, Size, llvm::CodeModel::Small, and llvm::Triple::x86_64.
Referenced by llvm::X86Subtarget::classifyLocalReference().
isNoopAddrSpaceCast()
virtual bool llvm::TargetMachine::isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const inline virtual
Returns true if a cast between SrcAS and DestAS is a noop.
Reimplemented in llvm::AArch64TargetMachine, llvm::AMDGPUTargetMachine, llvm::ARMBaseTargetMachine, llvm::AVRTargetMachine, llvm::LoongArchTargetMachine, llvm::MipsTargetMachine, llvm::PPCTargetMachine, llvm::RISCVTargetMachine, and llvm::X86TargetMachine.
Definition at line 330 of file TargetMachine.h.
Referenced by checkAddrSpaceIsValidForLibcall(), llvm::TargetLoweringBase::isFreeAddrSpaceCast(), llvm::BasicTTIImplBase< T >::isNoopAddrSpaceCast(), and llvm::AsmPrinter::lowerConstant().
isPositionIndependent()
bool TargetMachine::isPositionIndependent () const
Definition at line 117 of file TargetMachine.cpp.
References getRelocationModel(), and llvm::Reloc::PIC_.
Referenced by computeBasePointerSaveOffset(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::PPCRegisterInfo::getBaseRegister(), llvm::PPCRegisterInfo::getCalleeSavedRegs(), llvm::PPCRegisterInfo::getCallPreservedMask(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::MipsFunctionInfo::initGlobalBaseReg(), llvm::TargetLoweringObjectFile::Initialize(), llvm::ARMSubtarget::isGVIndirectSymbol(), llvm::ARMSubtarget::isGVInGOT(), llvm::MipsTargetLowering::isJumpTableRelative(), llvm::TargetLoweringBase::isJumpTableRelative(), llvm::AsmPrinter::isPositionIndependent(), llvm::M68kSubtarget::isPositionIndependent(), llvm::MipsSubtarget::isPositionIndependent(), llvm::TargetLowering::isPositionIndependent(), llvm::X86Subtarget::isPositionIndependent(), llvm::HexagonTargetObjectFile::isSmallDataEnabled(), and llvm::M68kCallLowering::lowerCall().
operator=()
void llvm::TargetMachine::operator= (const TargetMachine &) delete
parseBinutilsVersion()
std::pair< int, int > TargetMachine::parseBinutilsVersion (StringRef Version) static
Definition at line 306 of file TargetMachine.cpp.
parseMachineFunctionInfo()
virtual bool llvm::TargetMachine::parseMachineFunctionInfo (const yaml::MachineFunctionInfo & , PerFunctionMIParsingState & PFS, SMDiagnostic & Error, SMRange & SourceRange) const inline virtual
Parse out the target's MachineFunctionInfo from the YAML reprsentation.
Reimplemented in llvm::AArch64TargetMachine, llvm::ARMBaseTargetMachine, llvm::GCNTargetMachine, llvm::RISCVTargetMachine, llvm::WebAssemblyTargetMachine, and llvm::X86TargetMachine.
Definition at line 161 of file TargetMachine.h.
registerDefaultAliasAnalyses()
virtual void llvm::TargetMachine::registerDefaultAliasAnalyses (AAManager &) inline virtual
Allow the target to register alias analyses with the AAManager for use with the new pass manager.
Only affects the "default" AAManager.
Reimplemented in llvm::AMDGPUTargetMachine, and llvm::NVPTXTargetMachine.
Definition at line 376 of file TargetMachine.h.
Referenced by llvm::PassBuilder::buildDefaultAAPipeline().
registerPassBuilderCallbacks()
virtual void llvm::TargetMachine::registerPassBuilderCallbacks (PassBuilder &) inline virtual
Allow the target to modify the pass pipeline.
Reimplemented in llvm::AArch64TargetMachine, llvm::AMDGPUTargetMachine, llvm::BPFTargetMachine, llvm::DirectXTargetMachine, llvm::HexagonTargetMachine, llvm::NVPTXTargetMachine, llvm::RISCVTargetMachine, and llvm::X86TargetMachine.
Definition at line 372 of file TargetMachine.h.
requiresStructuredCFG()
bool llvm::TargetMachine::requiresStructuredCFG () const inline
Definition at line 223 of file TargetMachine.h.
References RequireStructuredCFG.
Referenced by llvm::TargetPassConfig::addMachineLateOptimization(), and llvm::MachineBasicBlock::canSplitCriticalEdge().
resetTargetOptions()
void TargetMachine::resetTargetOptions (const Function & F) const
Reset the target options based on the function's attributes.
setFunctionAttributes should have made the raw attribute value consistent with the command line flag if used.
Definition at line 129 of file TargetMachine.cpp.
References RESET_OPTION.
Referenced by llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::CSKYTargetMachine::getSubtargetImpl(), llvm::GCNTargetMachine::getSubtargetImpl(), llvm::HexagonTargetMachine::getSubtargetImpl(), llvm::LoongArchTargetMachine::getSubtargetImpl(), llvm::M68kTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::R600TargetMachine::getSubtargetImpl(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::SparcTargetMachine::getSubtargetImpl(), llvm::SystemZTargetMachine::getSubtargetImpl(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), and llvm::XtensaTargetMachine::getSubtargetImpl().
setCFIFixup()
void llvm::TargetMachine::setCFIFixup (bool Enable) inline
Definition at line 279 of file TargetMachine.h.
References llvm::Enable, llvm::TargetOptions::EnableCFIFixup, and Options.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine().
setCodeModel()
void llvm::TargetMachine::setCodeModel (CodeModel::Model CM) inline
Set the code model.
Definition at line 238 of file TargetMachine.h.
References CMModel.
setFastISel()
void llvm::TargetMachine::setFastISel (bool Enable) inline
Definition at line 262 of file TargetMachine.h.
References llvm::Enable, llvm::TargetOptions::EnableFastISel, and Options.
Referenced by llvm::TargetPassConfig::addCoreISelPasses(), llvm::OptLevelChanger::OptLevelChanger(), llvm::SPIRVTargetMachine::SPIRVTargetMachine(), and llvm::OptLevelChanger::~OptLevelChanger().
setGlobalISel()
void llvm::TargetMachine::setGlobalISel (bool Enable) inline
Definition at line 265 of file TargetMachine.h.
References llvm::Enable, llvm::TargetOptions::EnableGlobalISel, and Options.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::TargetPassConfig::addCoreISelPasses(), and llvm::SPIRVTargetMachine::SPIRVTargetMachine().
setGlobalISelAbort()
void llvm::TargetMachine::setGlobalISelAbort (GlobalISelAbortMode Mode) inline
Definition at line 266 of file TargetMachine.h.
References llvm::TargetOptions::GlobalISelAbort, Mode, and Options.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine().
setLargeDataThreshold()
void llvm::TargetMachine::setLargeDataThreshold (uint64_t LDT) inline
Definition at line 240 of file TargetMachine.h.
References LargeDataThreshold.
setMachineOutliner()
void llvm::TargetMachine::setMachineOutliner (bool Enable) inline
Definition at line 269 of file TargetMachine.h.
References llvm::Enable, llvm::TargetOptions::EnableMachineOutliner, and Options.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::ARMBaseTargetMachine::ARMBaseTargetMachine(), llvm::RISCVTargetMachine::RISCVTargetMachine(), and llvm::X86TargetMachine::X86TargetMachine().
setO0WantsFastISel()
void llvm::TargetMachine::setO0WantsFastISel (bool Enable) inline
Definition at line 264 of file TargetMachine.h.
References llvm::Enable, and O0WantsFastISel.
Referenced by llvm::TargetPassConfig::addCoreISelPasses(), and llvm::SPIRVTargetMachine::SPIRVTargetMachine().
setOptLevel()
void TargetMachine::setOptLevel (CodeGenOptLevel Level)
Overrides the optimization level.
Definition at line 268 of file TargetMachine.cpp.
References OptLevel.
Referenced by llvm::OptLevelChanger::OptLevelChanger(), and llvm::OptLevelChanger::~OptLevelChanger().
setPGOOption()
void llvm::TargetMachine::setPGOOption (std::optional< PGOOptions > PGOOpt) inline
Definition at line 334 of file TargetMachine.h.
References PGOOption.
setRequiresStructuredCFG()
void llvm::TargetMachine::setRequiresStructuredCFG (bool Value) inline
Definition at line 224 of file TargetMachine.h.
References RequireStructuredCFG, and llvm::Value.
Referenced by llvm::NVPTXTargetMachine::NVPTXTargetMachine(), llvm::R600TargetMachine::R600TargetMachine(), and llvm::SPIRVTargetMachine::SPIRVTargetMachine().
setSupportsDebugEntryValues()
void llvm::TargetMachine::setSupportsDebugEntryValues (bool Enable) inline
Definition at line 275 of file TargetMachine.h.
References llvm::Enable, Options, and llvm::TargetOptions::SupportsDebugEntryValues.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::ARMBaseTargetMachine::ARMBaseTargetMachine(), llvm::MipsTargetMachine::MipsTargetMachine(), and llvm::X86TargetMachine::X86TargetMachine().
setSupportsDefaultOutlining()
void llvm::TargetMachine::setSupportsDefaultOutlining (bool Enable) inline
Definition at line 272 of file TargetMachine.h.
References llvm::Enable, Options, and llvm::TargetOptions::SupportsDefaultOutlining.
Referenced by llvm::AArch64TargetMachine::AArch64TargetMachine(), llvm::ARMBaseTargetMachine::ARMBaseTargetMachine(), and llvm::RISCVTargetMachine::RISCVTargetMachine().
setTargetFeatureString()
void llvm::TargetMachine::setTargetFeatureString (StringRef FS) inline
Definition at line 129 of file TargetMachine.h.
References TargetFS.
shouldAssumeDSOLocal()
bool TargetMachine::shouldAssumeDSOLocal (const GlobalValue * GV) const
Definition at line 178 of file TargetMachine.cpp.
References assert(), getRelocationModel(), getTargetTriple(), llvm::GlobalValue::hasDLLImportStorageClass(), llvm::GlobalValue::hasExternalWeakLinkage(), llvm::isa(), llvm::GlobalValue::isDeclarationForLinker(), llvm::GlobalValue::isDSOLocal(), llvm::GlobalValue::isStrongDefinitionForLinker(), RM, and llvm::Reloc::Static.
Referenced by llvm::M68kSubtarget::classifyExternalReference(), llvm::M68kSubtarget::classifyGlobalFunctionReference(), llvm::X86Subtarget::classifyGlobalFunctionReference(), llvm::M68kSubtarget::classifyGlobalReference(), llvm::X86Subtarget::classifyGlobalReference(), getTLSModel(), llvm::ARMSubtarget::isGVIndirectSymbol(), llvm::PPCSubtarget::isGVIndirectSymbol(), llvm::SystemZSubtarget::isPC32DBLSymbol(), llvm::LoongArchTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::SITargetLowering::shouldEmitGOTReloc(), and transformCallee().
splitModule()
virtual bool llvm::TargetMachine::splitModule (Module & M, unsigned NumParts, function_ref< void(std::unique_ptr< Module > MPart)> ModuleCallback) inline virtual
Entry point for module splitting.
Targets can implement custom module splitting logic, mainly used by LTO for –lto-partitions.
Returns
true if the module was split, false otherwise. When false is returned, it is assumed that ModuleCallback has never been called and M has not been modified.
Reimplemented in llvm::AMDGPUTargetMachine.
Definition at line 432 of file TargetMachine.h.
targetSchedulesPostRAScheduling()
virtual bool llvm::TargetMachine::targetSchedulesPostRAScheduling () const inline virtual
True if subtarget inserts the final scheduling pass on its own.
Branch relaxation, which must happen after block placement, can on some targets (e.g. SystemZ) expose additional post-RA scheduling opportunities.
Reimplemented in llvm::ARMBaseTargetMachine, and llvm::SystemZTargetMachine.
Definition at line 408 of file TargetMachine.h.
Referenced by llvm::TargetPassConfig::addMachinePasses().
useEmulatedTLS()
bool TargetMachine::useEmulatedTLS () const
Returns true if this target uses emulated TLS.
Definition at line 235 of file TargetMachine.cpp.
References llvm::TargetOptions::EmulatedTLS, and Options.
Referenced by llvm::TargetPassConfig::addISelPasses(), llvm::DwarfCompileUnit::addLocationAttribute(), llvm::AsmPrinter::emitGlobalVariable(), and llvm::SparcTargetLowering::LowerGlobalTLSAddress().
useTLSDESC()
bool TargetMachine::useTLSDESC () const
Returns true if this target uses TLS Descriptors.
Definition at line 236 of file TargetMachine.cpp.
References llvm::TargetOptions::EnableTLSDESC, and Options.
Referenced by GetTLSADDR().
Member Data Documentation
AsmInfo
std::unique_ptr<const MCAsmInfo> llvm::TargetMachine::AsmInfo protected
Contains target specific asm information.
Definition at line 106 of file TargetMachine.h.
Referenced by llvm::BPFTargetMachine::BPFTargetMachine(), getMCAsmInfo(), and llvm::LLVMTargetMachine::initAsmInfo().
CMModel
CodeModel::Model llvm::TargetMachine::CMModel = CodeModel::Small protected
Definition at line 101 of file TargetMachine.h.
Referenced by getCodeModel(), llvm::LLVMTargetMachine::LLVMTargetMachine(), and setCodeModel().
DefaultSjLjDataSize
unsigned llvm::TargetMachine::DefaultSjLjDataSize = 32 static constexpr
The integer bit size to use for SjLj based exception handling.
Definition at line 415 of file TargetMachine.h.
Referenced by getSjLjDataSize().
DL
const DataLayout llvm::TargetMachine::DL protected
DataLayout for the target: keep ABI type size and alignment.
The DataLayout is created based on the string representation provided during construction. It is kept here only to avoid reparsing the string but should not really be used during compilation, because it has an internal cache that is context specific.
Definition at line 92 of file TargetMachine.h.
Referenced by createDataLayout(), getAllocaPointerSize(), getPointerSize(), getPointerSizeInBits(), getProgramPointerSize(), isCompatibleDataLayout(), and isLargeGlobalValue().
LargeDataThreshold
uint64_t llvm::TargetMachine::LargeDataThreshold = 0 protected
Definition at line 102 of file TargetMachine.h.
Referenced by isLargeGlobalValue(), and setLargeDataThreshold().
MII
std::unique_ptr<const MCInstrInfo> llvm::TargetMachine::MII protected
Definition at line 108 of file TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::createMCStreamer(), getMCInstrInfo(), and llvm::LLVMTargetMachine::initAsmInfo().
MRI
std::unique_ptr<const MCRegisterInfo> llvm::TargetMachine::MRI protected
Definition at line 107 of file TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::AMDGPUTargetMachine::AMDGPUTargetMachine(), llvm::LLVMTargetMachine::createMCStreamer(), getMCRegisterInfo(), and llvm::LLVMTargetMachine::initAsmInfo().
O0WantsFastISel
unsigned llvm::TargetMachine::O0WantsFastISel protected
Definition at line 112 of file TargetMachine.h.
Referenced by getO0WantsFastISel(), and setO0WantsFastISel().
Options
TargetOptions llvm::TargetMachine::Options mutable
Definition at line 118 of file TargetMachine.h.
Referenced by llvm::DwarfUnit::addAttribute(), llvm::TargetPassConfig::addCoreISelPasses(), llvm::DwarfDebug::addDwarfTypeUnitType(), llvm::TargetPassConfig::addMachinePasses(), llvm::LLVMTargetMachine::addPassesToEmitMC(), allowApproxFunc(), llvm::AMDGPUTargetLowering::allowApproxFunc(), llvm::NVPTXTargetLowering::allowFMA(), llvm::NVPTXTargetLowering::allowUnsafeFPMath(), llvm::ARMBaseTargetMachine::ARMBaseTargetMachine(), llvm::DwarfCFIException::beginBasicBlockSection(), llvm::SelectionDAG::canCreateUndefOrPoison(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), combineFaddCFmul(), combineFMinFMax(), combineFMinNumFMaxNum(), combineSelect(), llvm::DwarfUnit::constructTypeDIE(), llvm::LLVMTargetMachine::createMCStreamer(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::PPCFrameLowering::determineCalleeSaves(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::AsmPrinter::doFinalization(), llvm::AsmPrinter::doInitialization(), llvm::DwarfDebug::DwarfDebug(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::SelectionDAGBuilder::EmitBranchForMergedCondition(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::AsmPrinter::emitFunctionBody(), llvm::AArch64FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::AsmPrinter::emitStackSizeSection(), llvm::AsmPrinter::emitStackUsage(), llvm::AsmPrinter::emitXRayTable(), llvm::AsmPrinter::emitXXStructorList(), foldFPToIntToFP(), getAIXExtendedAltivecABI(), llvm::GCNTTIImpl::getArithmeticInstrCost(), getBBSectionsFuncListBuf(), getBBSectionsType(), getDataSections(), llvm::TargetLoweringObjectFileXCOFF::getExplicitSectionGlobal(), llvm::AsmPrinter::getFunctionCFISectionType(), getFunctionSections(), getIgnoreXCOFFVisibility(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::PPCTargetLowering::getNegatedExpression(), llvm::TargetLowering::getNegatedExpression(), llvm::TargetLoweringBase::getPrefLoopAlignment(), getSeparateNamedSections(), llvm::LoongArchTargetMachine::getSubtargetImpl(), llvm::RISCVTargetMachine::getSubtargetImpl(), getUniqueBasicBlockSectionNames(), getUniqueSectionNames(), getXCOFFTracebackTable(), llvm::AArch64FrameLowering::hasFP(), llvm::ARCFrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::CSKYFrameLowering::hasFP(), llvm::LoongArchFrameLowering::hasFP(), llvm::M68kFrameLowering::hasFP(), llvm::MipsFrameLowering::hasFP(), llvm::MSP430FrameLowering::hasFP(), llvm::RISCVFrameLowering::hasFP(), llvm::SIFrameLowering::hasFP(), llvm::SparcFrameLowering::hasFP(), llvm::SystemZELFFrameLowering::hasFP(), llvm::VEFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), llvm::XCoreFrameLowering::hasFP(), llvm::XtensaFrameLowering::hasFP(), llvm::LLVMTargetMachine::initAsmInfo(), llvm::TargetLoweringObjectFileELF::Initialize(), isCombineInstrCandidateFP(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), llvm::AMDGPUCallLowering::isEligibleForTailCallOptimization(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), isFMAddSubOrFMSubAdd(), llvm::ARMFrameLowering::isFPReserved(), llvm::TargetPassConfig::isGlobalISelAbortEnabled(), isLegalToCombineMinNumMaxNum(), llvm::AArch64TargetLowering::isProfitableToHoist(), llvm::PPCTargetLowering::isProfitableToHoist(), llvm::RISCVMachineFunctionInfo::isPushable(), llvm::BasicTTIImplBase< T >::isSingleThreaded(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFExp(), llvm::SITargetLowering::LowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::SelectionDAGBuilder::LowerDeoptimizingReturn(), llvm::AMDGPUTargetLowering::lowerFEXP(), llvm::AMDGPUTargetLowering::LowerFLOGCommon(), LowerFMINIMUM_FMAXIMUM(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::LegalizerHelper::lowerFPTRUNC_F64_TO_F16(), llvm::AMDGPUCallLowering::lowerTailCall(), llvm::PPCFrameLowering::needsFP(), llvm::MachineFunction::needsFrameMoves(), llvm::OptLevelChanger::OptLevelChanger(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), promoteToConstantPool(), llvm::TargetPassConfig::reportDiagnosticWhenGlobalISelFallback(), llvm::FastISel::selectOperator(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), setCFIFixup(), setFastISel(), setGlobalISel(), setGlobalISelAbort(), setMachineOutliner(), setSupportsDebugEntryValues(), setSupportsDefaultOutlining(), llvm::AsmPrinter::SetupMachineFunction(), llvm::ARMSubtarget::splitFramePushPop(), llvm::TargetPassConfig::TargetPassConfig(), llvm::DwarfCompileUnit::updateSubprogramScopeDIE(), useEmulatedTLS(), llvm::ARMSubtarget::useFastISel(), llvm::CSKYSubtarget::useHardFloatABI(), llvm::NVPTXTargetLowering::usePrecSqrtF32(), and useTLSDESC().
OptLevel
CodeGenOptLevel llvm::TargetMachine::OptLevel = CodeGenOptLevel::Default protected
Definition at line 103 of file TargetMachine.h.
Referenced by getOptLevel(), llvm::LLVMTargetMachine::LLVMTargetMachine(), and setOptLevel().
PGOOption
std::optional<PGOOptions> llvm::TargetMachine::PGOOption protected
Definition at line 115 of file TargetMachine.h.
Referenced by getPGOOption(), and setPGOOption().
RequireStructuredCFG
unsigned llvm::TargetMachine::RequireStructuredCFG protected
Definition at line 111 of file TargetMachine.h.
Referenced by requiresStructuredCFG(), and setRequiresStructuredCFG().
RM
Reloc::Model llvm::TargetMachine::RM = Reloc::Static protected
Definition at line 100 of file TargetMachine.h.
Referenced by getRelocationModel(), getTLSModel(), llvm::LLVMTargetMachine::LLVMTargetMachine(), and shouldAssumeDSOLocal().
STI
std::unique_ptr<const MCSubtargetInfo> llvm::TargetMachine::STI protected
Definition at line 109 of file TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::AArch64TargetMachine::createMachineFunctionInfo(), llvm::ARCTargetMachine::createMachineFunctionInfo(), llvm::ARMBaseTargetMachine::createMachineFunctionInfo(), llvm::CSKYTargetMachine::createMachineFunctionInfo(), llvm::GCNTargetMachine::createMachineFunctionInfo(), llvm::HexagonTargetMachine::createMachineFunctionInfo(), llvm::LanaiTargetMachine::createMachineFunctionInfo(), llvm::LoongArchTargetMachine::createMachineFunctionInfo(), llvm::M68kTargetMachine::createMachineFunctionInfo(), llvm::MipsTargetMachine::createMachineFunctionInfo(), llvm::MSP430TargetMachine::createMachineFunctionInfo(), llvm::NVPTXTargetMachine::createMachineFunctionInfo(), llvm::PPCTargetMachine::createMachineFunctionInfo(), llvm::R600TargetMachine::createMachineFunctionInfo(), llvm::RISCVTargetMachine::createMachineFunctionInfo(), llvm::SparcTargetMachine::createMachineFunctionInfo(), llvm::SystemZTargetMachine::createMachineFunctionInfo(), llvm::VETargetMachine::createMachineFunctionInfo(), llvm::WebAssemblyTargetMachine::createMachineFunctionInfo(), llvm::X86TargetMachine::createMachineFunctionInfo(), llvm::XCoreTargetMachine::createMachineFunctionInfo(), llvm::LLVMTargetMachine::createMCStreamer(), getMCSubtargetInfo(), and llvm::LLVMTargetMachine::initAsmInfo().
TargetCPU
std::string llvm::TargetMachine::TargetCPU protected
Definition at line 97 of file TargetMachine.h.
Referenced by llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::CSKYTargetMachine::getSubtargetImpl(), llvm::HexagonTargetMachine::getSubtargetImpl(), llvm::LoongArchTargetMachine::getSubtargetImpl(), llvm::M68kTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::SparcTargetMachine::getSubtargetImpl(), llvm::SystemZTargetMachine::getSubtargetImpl(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), llvm::XtensaTargetMachine::getSubtargetImpl(), and getTargetCPU().
TargetFS
std::string llvm::TargetMachine::TargetFS protected
Definition at line 98 of file TargetMachine.h.
Referenced by llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::CSKYTargetMachine::getSubtargetImpl(), llvm::HexagonTargetMachine::getSubtargetImpl(), llvm::LoongArchTargetMachine::getSubtargetImpl(), llvm::M68kTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::SparcTargetMachine::getSubtargetImpl(), llvm::SystemZTargetMachine::getSubtargetImpl(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), llvm::XtensaTargetMachine::getSubtargetImpl(), getTargetFeatureString(), and setTargetFeatureString().
TargetTriple
Triple llvm::TargetMachine::TargetTriple protected
Triple string, CPU name, and target feature strings the TargetMachine instance is created with.
Definition at line 96 of file TargetMachine.h.
Referenced by llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::ARMBaseTargetMachine::getSubtargetImpl(), llvm::CSKYTargetMachine::getSubtargetImpl(), llvm::GCNTargetMachine::getSubtargetImpl(), llvm::HexagonTargetMachine::getSubtargetImpl(), llvm::LoongArchTargetMachine::getSubtargetImpl(), llvm::M68kTargetMachine::getSubtargetImpl(), llvm::MipsTargetMachine::getSubtargetImpl(), llvm::PPCTargetMachine::getSubtargetImpl(), llvm::R600TargetMachine::getSubtargetImpl(), llvm::RISCVTargetMachine::getSubtargetImpl(), llvm::SystemZTargetMachine::getSubtargetImpl(), llvm::WebAssemblyTargetMachine::getSubtargetImpl(), llvm::X86TargetMachine::getSubtargetImpl(), llvm::XtensaTargetMachine::getSubtargetImpl(), getTargetTriple(), and llvm::ARMBaseTargetMachine::isTargetHardFloat().
TheTarget
const Target& llvm::TargetMachine::TheTarget protected
The Target that this machine was created for.
Definition at line 84 of file TargetMachine.h.
Referenced by getTarget(), and llvm::LLVMTargetMachine::initAsmInfo().
The documentation for this class was generated from the following files:
include/llvm/Target/TargetMachine.h
lib/Target/TargetMachine.cpp