LLVM: llvm::objcopy::elf::SRECSectionWriterBase Class Reference
llvm::objcopy::elf::SRECSectionWriterBase Class Reference abstract
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
SRECSectionWriterBase (WritableMemoryBuffer &Buf, uint64_t StartOffset)
void writeRecords (uint32_t Entry)
uint64_t getBufferOffset () const
Error visit (const Section &S) override
Error visit (const OwnedDataSection &S) override
Error visit (const StringTableSection &S) override
Error visit (const DynamicRelocationSection &S) override
uint8_t getType () const
Error visit (const SymbolTableSection &Sec) override
Error visit (const RelocationSection &Sec) override
Error visit (const GnuDebugLinkSection &Sec) override
Error visit (const GroupSection &Sec) override
Error visit (const SectionIndexSection &Sec) override
Error visit (const CompressedSection &Sec) override
Error visit (const DecompressedSection &Sec) override
Public Member Functions inherited from llvm::objcopy::elf::BinarySectionWriter
virtual ~BinarySectionWriter ()
BinarySectionWriter (WritableMemoryBuffer &Buf)
Public Member Functions inherited from llvm::objcopy::elf::SectionWriter
virtual ~SectionWriter ()=default
SectionWriter (WritableMemoryBuffer &Buf)
Public Member Functions inherited from llvm::objcopy::elf::SectionVisitor
virtual ~SectionVisitor ()=default
Protected Member Functions
void writeSection (const SectionBase &S, ArrayRef< uint8_t > Data)
virtual void writeRecord (SRecord &Record, uint64_t Off)=0
Protected Attributes
uint64_t Offset
uint64_t HeaderSize
uint8_t Type = SRecord::S1
std::vector< SRecord > Records
Protected Attributes inherited from llvm::objcopy::elf::SectionWriter
WritableMemoryBuffer & Out
Detailed Description
Definition at line 458 of file ELFObject.h.
Constructor & Destructor Documentation
SRECSectionWriterBase()
llvm::objcopy::elf::SRECSectionWriterBase::SRECSectionWriterBase (WritableMemoryBuffer & Buf, uint64_t StartOffset) inline explicit
Definition at line 460 of file ELFObject.h.
Member Function Documentation
getBufferOffset()
uint64_t llvm::objcopy::elf::SRECSectionWriterBase::getBufferOffset () const inline
Definition at line 468 of file ELFObject.h.
References Offset.
getType()
uint8_t llvm::objcopy::elf::SRECSectionWriterBase::getType () const inline
Definition at line 473 of file ELFObject.h.
References Type.
visit() [1/11]
Error BinarySectionWriter::visit (const CompressedSection & Sec) override virtual
Reimplemented from llvm::objcopy::elf::BinarySectionWriter.
Definition at line 190 of file ELFObject.cpp.
visit() [2/11]
Error BinarySectionWriter::visit (const DecompressedSection & Sec) override virtual
Reimplemented from llvm::objcopy::elf::BinarySectionWriter.
Definition at line 191 of file ELFObject.cpp.
visit() [3/11]
Error SRECSectionWriterBase::visit (const DynamicRelocationSection & S) override virtual
Reimplemented from llvm::objcopy::elf::SectionWriter.
Definition at line 2888 of file ELFObject.cpp.
References llvm::Error::success(), and writeSection().
visit() [4/11]
Error BinarySectionWriter::visit (const GnuDebugLinkSection & Sec) override virtual
Reimplemented from llvm::objcopy::elf::BinarySectionWriter.
Definition at line 187 of file ELFObject.cpp.
visit() [5/11]
Error BinarySectionWriter::visit (const GroupSection & Sec) override virtual
Reimplemented from llvm::objcopy::elf::BinarySectionWriter.
Definition at line 188 of file ELFObject.cpp.
visit() [6/11]
Error SRECSectionWriterBase::visit (const OwnedDataSection & S) override virtual
Reimplemented from llvm::objcopy::elf::SectionWriter.
Definition at line 2883 of file ELFObject.cpp.
References llvm::Error::success(), and writeSection().
visit() [7/11]
Error BinarySectionWriter::visit (const RelocationSection & Sec) override virtual
Reimplemented from llvm::objcopy::elf::BinarySectionWriter.
Definition at line 186 of file ELFObject.cpp.
visit() [8/11]
Error SRECSectionWriterBase::visit (const Section & S) override virtual
Reimplemented from llvm::objcopy::elf::SectionWriter.
Definition at line 2878 of file ELFObject.cpp.
References llvm::Error::success(), and writeSection().
visit() [9/11]
Error BinarySectionWriter::visit (const SectionIndexSection & Sec) override virtual
Reimplemented from llvm::objcopy::elf::BinarySectionWriter.
Definition at line 189 of file ELFObject.cpp.
visit() [10/11]
Error SRECSectionWriterBase::visit (const StringTableSection & S) override virtual
Reimplemented from llvm::objcopy::elf::SectionWriter.
Definition at line 2869 of file ELFObject.cpp.
References assert(), llvm::StringTableBuilder::getSize(), llvm::objcopy::elf::SectionBase::Size, and llvm::Error::success().
visit() [11/11]
Error BinarySectionWriter::visit (const SymbolTableSection & Sec) override virtual
Reimplemented from llvm::objcopy::elf::BinarySectionWriter.
Definition at line 185 of file ELFObject.cpp.
writeRecord()
virtual void llvm::objcopy::elf::SRECSectionWriterBase::writeRecord (SRecord & Record, uint64_t Off) protected pure virtual
Implemented in llvm::objcopy::elf::SRECSectionWriter, and llvm::objcopy::elf::SRECSizeCalculator.
Referenced by writeRecords().
writeRecords()
void SRECSectionWriterBase::writeRecords (uint32_t Entry)
Definition at line 2898 of file ELFObject.cpp.
References llvm::objcopy::elf::SRecord::getType(), HeaderSize, Offset, Records, Type, and writeRecord().
writeSection()
void SRECSectionWriterBase::writeSection (const SectionBase & S, ArrayRef< uint8_t > Data) protected
Definition at line 2911 of file ELFObject.cpp.
References llvm::Address, llvm::Data, llvm::DataSize, llvm::objcopy::elf::SRecord::getType(), Records, sectionPhysicalAddr(), llvm::objcopy::elf::SectionBase::Size, and Type.
Referenced by llvm::objcopy::elf::SRECSectionWriter::visit(), visit(), visit(), and visit().
Member Data Documentation
HeaderSize
uint64_t llvm::objcopy::elf::SRECSectionWriterBase::HeaderSize protected
Definition at line 479 of file ELFObject.h.
Referenced by writeRecords().
Offset
uint64_t llvm::objcopy::elf::SRECSectionWriterBase::Offset protected
Definition at line 477 of file ELFObject.h.
Referenced by getBufferOffset(), and writeRecords().
Records
std::vector<SRecord> llvm::objcopy::elf::SRECSectionWriterBase::Records protected
Definition at line 482 of file ELFObject.h.
Referenced by writeRecords(), and writeSection().
Type
uint8_t llvm::objcopy::elf::SRECSectionWriterBase::Type = SRecord::S1 protected
Definition at line 481 of file ELFObject.h.
Referenced by getType(), writeRecords(), and writeSection().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp