LLVM: llvm::DiagnosticInfoResourceLimit Class Reference
llvm::DiagnosticInfoResourceLimit Class Reference
Diagnostic information for stack size etc.
#include "llvm/IR/DiagnosticInfo.h"
Public Member Functions
DiagnosticInfoResourceLimit (const Function &Fn, const char *ResourceName, uint64_t ResourceSize, uint64_t ResourceLimit, DiagnosticSeverity Severity=DS_Warning, DiagnosticKind Kind=DK_ResourceLimit)
The function that is concerned by this stack size diagnostic.
const Function & getFunction () const
const char * getResourceName () const
uint64_t getResourceSize () const
uint64_t getResourceLimit () const
void print (DiagnosticPrinter &DP) const override
Public Member Functions inherited from llvm::DiagnosticInfoWithLocationBase
DiagnosticInfoWithLocationBase (enum DiagnosticKind Kind, enum DiagnosticSeverity Severity, const Function &Fn, const DiagnosticLocation &Loc)
Fn is the function where the diagnostic is being emitted.
bool isLocationAvailable () const
Return true if location information is available for this diagnostic.
std::string getLocationStr () const
Return a string with the location information for this diagnostic in the format "file:line:col".
void getLocation (StringRef &RelativePath, unsigned &Line, unsigned &Column) const
Return location information for this diagnostic in three parts: the relative source file path, line number and column.
std::string getAbsolutePath () const
Return the absolute path tot the file.
const Function & getFunction () const
DiagnosticLocation getLocation () const
Public Member Functions inherited from llvm::DiagnosticInfo
DiagnosticInfo (int Kind, DiagnosticSeverity Severity)
virtual ~DiagnosticInfo ()=default
int getKind () const
DiagnosticSeverity getSeverity () const
Static Public Member Functions
static bool classof (const DiagnosticInfo *DI)
Detailed Description
Diagnostic information for stack size etc.
reporting. This is basically a function and a size.
Definition at line 358 of file DiagnosticInfo.h.
Constructor & Destructor Documentation
DiagnosticInfoResourceLimit()
DiagnosticInfoResourceLimit::DiagnosticInfoResourceLimit (const Function & Fn, const char * ResourceName, uint64_t ResourceSize, uint64_t ResourceLimit, DiagnosticSeverity Severity = DS_Warning, DiagnosticKind Kind = DK_ResourceLimit)
The function that is concerned by this stack size diagnostic.
The computed stack size.
Definition at line 69 of file DiagnosticInfo.cpp.
Member Function Documentation
classof()
static bool llvm::DiagnosticInfoResourceLimit::classof (const DiagnosticInfo * DI) inline static
Definition at line 388 of file DiagnosticInfo.h.
References llvm::DK_ResourceLimit, llvm::DK_StackSize, and llvm::DiagnosticInfo::getKind().
getFunction()
const Function & llvm::DiagnosticInfoResourceLimit::getFunction () const inline
Definition at line 380 of file DiagnosticInfo.h.
Referenced by print().
getResourceLimit()
uint64_t llvm::DiagnosticInfoResourceLimit::getResourceLimit () const inline
Definition at line 383 of file DiagnosticInfo.h.
Referenced by llvm::DiagnosticInfoStackSize::getStackLimit(), and print().
getResourceName()
const char * llvm::DiagnosticInfoResourceLimit::getResourceName () const inline
Definition at line 381 of file DiagnosticInfo.h.
Referenced by print().
getResourceSize()
uint64_t llvm::DiagnosticInfoResourceLimit::getResourceSize () const inline
Definition at line 382 of file DiagnosticInfo.h.
Referenced by llvm::DiagnosticInfoStackSize::getStackSize(), and print().
print()
void DiagnosticInfoResourceLimit::print (DiagnosticPrinter & DP) const override virtual
See also
DiagnosticInfo::print.
Implements llvm::DiagnosticInfo.
Definition at line 76 of file DiagnosticInfo.cpp.
References getFunction(), llvm::DiagnosticInfoWithLocationBase::getLocationStr(), getResourceLimit(), getResourceName(), and getResourceSize().
The documentation for this class was generated from the following files:
include/llvm/IR/DiagnosticInfo.h
lib/IR/DiagnosticInfo.cpp