LLVM: llvm::MachObjectWriter Class Reference
llvm::MachObjectWriter Class Reference
#include "llvm/MC/MCMachObjectWriter.h"
Classes
struct DataRegionData
Public Types
using VersionInfoType
Public Member Functions
MachObjectWriter (std::unique_ptr< MCMachObjectTargetWriter > MOTW, raw_pwrite_stream &OS, bool IsLittleEndian)
const MCSymbol & findAliasedSymbol (const MCSymbol &Sym) const
void writeHeader (MachO::HeaderFileType Type, unsigned NumLoadCommands, unsigned LoadCommandsSize, bool SubsectionsViaSymbols)
void writeSegmentLoadCommand (StringRef Name, unsigned NumSections, uint64_t VMAddr, uint64_t VMSize, uint64_t SectionDataStartOffset, uint64_t SectionDataSize, uint32_t MaxProt, uint32_t InitProt)
Write a segment load command.
void writeSection (const MCAssembler &Asm, const MCSection &Sec, uint64_t VMAddr, uint64_t FileOffset, unsigned Flags, uint64_t RelocationsStart, unsigned NumRelocations)
void writeSymtabLoadCommand (uint32_t SymbolOffset, uint32_t NumSymbols, uint32_t StringTableOffset, uint32_t StringTableSize)
void writeDysymtabLoadCommand (uint32_t FirstLocalSymbol, uint32_t NumLocalSymbols, uint32_t FirstExternalSymbol, uint32_t NumExternalSymbols, uint32_t FirstUndefinedSymbol, uint32_t NumUndefinedSymbols, uint32_t IndirectSymbolOffset, uint32_t NumIndirectSymbols)
void writeNlist (MachSymbolData &MSD, const MCAssembler &Asm)
void writeLinkeditLoadCommand (uint32_t Type, uint32_t DataOffset, uint32_t DataSize)
void writeLinkerOptionsLoadCommand (const std::vector< std::string > &Options)
void addRelocation (const MCSymbol *RelSymbol, const MCSection *Sec, MachO::any_relocation_info &MRE)
void recordRelocation (MCAssembler &Asm, const MCFragment *Fragment, const MCFixup &Fixup, MCValue Target, uint64_t &FixedValue) override
Record a relocation entry.
void bindIndirectSymbols (MCAssembler &Asm)
void computeSymbolTable (MCAssembler &Asm, std::vector< MachSymbolData > &LocalSymbolData, std::vector< MachSymbolData > &ExternalSymbolData, std::vector< MachSymbolData > &UndefinedSymbolData)
Compute the symbol table data.
void computeSectionAddresses (const MCAssembler &Asm)
void executePostLayoutBinding (MCAssembler &Asm) override
Perform any late binding of symbols (for example, to assign symbol indices for use when generating relocations).
bool isSymbolRefDifferenceFullyResolvedImpl (const MCAssembler &Asm, const MCSymbol &SymA, const MCFragment &FB, bool InSet, bool IsPCRel) const override
void populateAddrSigSection (MCAssembler &Asm)
uint64_t writeObject (MCAssembler &Asm) override
Write the object file and returns the number of bytes written.
Lifetime management Methods
void reset () override
lifetime management
Utility Methods
bool isFixupKindPCRel (const MCAssembler &Asm, unsigned Kind)
std::vector< IndirectSymbolData > & getIndirectSymbols ()
std::vector< DataRegionData > & getDataRegions ()
const llvm::SmallVectorImpl< MCSection * > & getSectionOrder () const
SectionAddrMap & getSectionAddressMap ()
MCLOHContainer & getLOHContainer ()
uint64_t getSectionAddress (const MCSection *Sec) const
uint64_t getSymbolAddress (const MCSymbol &S, const MCAssembler &Asm) const
uint64_t getFragmentAddress (const MCAssembler &Asm, const MCFragment *Fragment) const
uint64_t getPaddingSize (const MCAssembler &Asm, const MCSection *SD) const
const MCSymbol * getAtom (const MCSymbol &S) const
bool doesSymbolRequireExternRelocation (const MCSymbol &S)
void setVersionMin (MCVersionMinType Type, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion=VersionTuple())
Mach-O deployment target version information.
void setBuildVersion (MachO::PlatformType Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion=VersionTuple())
void setTargetVariantBuildVersion (MachO::PlatformType Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
std::vector< std::vector< std::string > > & getLinkerOptions ()
Target Writer Proxy Accessors
bool is64Bit () const
bool isX86_64 () const
Public Member Functions inherited from llvm::MCObjectWriter
MCObjectWriter (const MCObjectWriter &)=delete
MCObjectWriter & operator= (const MCObjectWriter &)=delete
virtual ~MCObjectWriter ()
bool isSymbolRefDifferenceFullyResolved (const MCAssembler &Asm, const MCSymbolRefExpr *A, const MCSymbolRefExpr *B, bool InSet) const
Check whether the difference (A - B) between two symbol references is fully resolved.
MutableArrayRef< std::pair< std::string, size_t > > getFileNames ()
void addFileName (MCAssembler &Asm, StringRef FileName)
void setCompilerVersion (StringRef CompilerVers)
void emitAddrsigSection ()
Tell the object writer to emit an address-significance table during writeObject().
bool getEmitAddrsigSection ()
void addAddrsigSymbol (const MCSymbol *Sym)
Record the given symbol in the address-significance table to be written diring writeObject().
std::vector< const MCSymbol * > & getAddrsigSyms ()
SmallVector< CGProfileEntry, 0 > & getCGProfile ()
bool getSubsectionsViaSymbols () const
void setSubsectionsViaSymbols (bool Value)
Public Attributes
support::endian::Writer W
Additional Inherited Members
Protected Member Functions inherited from llvm::MCObjectWriter
MCObjectWriter ()=default
Protected Attributes inherited from llvm::MCObjectWriter
SmallVector< std::pair< std::string, size_t >, 0 > FileNames
List of declared file names.
std::string CompilerVersion
std::vector< const MCSymbol * > AddrsigSyms
bool EmitAddrsigSection = false
bool SubsectionsViaSymbols = false
SmallVector< CGProfileEntry, 0 > CGProfile
Detailed Description
Definition at line 86 of file MCMachObjectWriter.h.
Member Typedef Documentation
VersionInfoType
using llvm::MachObjectWriter::VersionInfoType
Initial value:
 struct {
    bool EmitBuildVersion;
    union {
      MCVersionMinType Type;
      MachO::PlatformType Platform;
    } TypeOrPlatform;
    unsigned Major;
    unsigned Minor;
    unsigned Update;
    VersionTuple SDKVersion;
  }
Definition at line 96 of file MCMachObjectWriter.h.
Constructor & Destructor Documentation
MachObjectWriter()
llvm::MachObjectWriter::MachObjectWriter (std::unique_ptr< MCMachObjectTargetWriter > MOTW, raw_pwrite_stream & OS, bool IsLittleEndian) inline
Definition at line 175 of file MCMachObjectWriter.h.
Member Function Documentation
addRelocation()
void llvm::MachObjectWriter::addRelocation (const MCSymbol * RelSymbol, const MCSection * Sec, MachO::any_relocation_info & MRE) inline
Definition at line 325 of file MCMachObjectWriter.h.
References P.
Referenced by populateAddrSigSection().
bindIndirectSymbols()
void MachObjectWriter::bindIndirectSymbols (MCAssembler & Asm)
Definition at line 520 of file MachObjectWriter.cpp.
References llvm::cast(), llvm::enumerate(), llvm::report_fatal_error(), llvm::MachO::S_LAZY_SYMBOL_POINTERS, llvm::MachO::S_NON_LAZY_SYMBOL_POINTERS, llvm::MachO::S_SYMBOL_STUBS, and llvm::MachO::S_THREAD_LOCAL_VARIABLE_POINTERS.
Referenced by executePostLayoutBinding().
computeSectionAddresses()
void MachObjectWriter::computeSectionAddresses (const MCAssembler & Asm)
strictly be necessary.
Definition at line 677 of file MachObjectWriter.cpp.
References llvm::alignTo(), llvm::cast(), getPaddingSize(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by executePostLayoutBinding().
computeSymbolTable()
void MachObjectWriter::computeSymbolTable (MCAssembler & Asm, std::vector< MachSymbolData > & LocalSymbolData, std::vector< MachSymbolData > & ExternalSymbolData, std::vector< MachSymbolData > & UndefinedSymbolData)
Compute the symbol table data.
computeSymbolTable - Compute the symbol table data
Definition at line 577 of file MachObjectWriter.cpp.
References llvm::StringTableBuilder::add(), assert(), llvm::cast(), llvm::support::endian::Writer::Endian, llvm::StringTableBuilder::finalize(), llvm::StringTableBuilder::getOffset(), llvm::isInt(), isSymbolLinkerVisible(), llvm::little, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::sort(), and W.
Referenced by writeObject().
doesSymbolRequireExternRelocation()
bool MachObjectWriter::doesSymbolRequireExternRelocation (const MCSymbol & S)
Definition at line 67 of file MachObjectWriter.cpp.
References llvm::cast(), and llvm::MCSymbol::isUndefined().
executePostLayoutBinding()
void MachObjectWriter::executePostLayoutBinding (MCAssembler & Asm) override virtual
Perform any late binding of symbols (for example, to assign symbol indices for use when generating relocations).
This routine is called by the assembler after layout and relaxation is complete.
Reimplemented from llvm::MCObjectWriter.
Definition at line 707 of file MachObjectWriter.cpp.
References bindIndirectSymbols(), and computeSectionAddresses().
findAliasedSymbol()
const MCSymbol & MachObjectWriter::findAliasedSymbol (const MCSymbol & Sym) const
Definition at line 371 of file MachObjectWriter.cpp.
References llvm::dyn_cast(), llvm::MCSymbol::getVariableValue(), llvm::MCSymbol::isVariable(), llvm::Ref, and Sym.
Referenced by isSymbolRefDifferenceFullyResolvedImpl(), and writeNlist().
getAtom()
const MCSymbol * MachObjectWriter::getAtom (const MCSymbol & S) const
Definition at line 157 of file MachObjectWriter.cpp.
References llvm::MCFragment::getAtom(), llvm::MCSymbol::getFragment(), llvm::MCFragment::getParent(), llvm::MCSymbol::isInSection(), llvm::MCAsmInfoDarwin::isSectionAtomizableBySymbols(), and isSymbolLinkerVisible().
getDataRegions()
std::vector< DataRegionData > & llvm::MachObjectWriter::getDataRegions () inline
Definition at line 202 of file MCMachObjectWriter.h.
getFragmentAddress()
uint64_t MachObjectWriter::getFragmentAddress (const MCAssembler & Asm, const MCFragment * Fragment) const
Definition at line 94 of file MachObjectWriter.cpp.
References getSectionAddress().
getIndirectSymbols()
std::vector< IndirectSymbolData > & llvm::MachObjectWriter::getIndirectSymbols () inline
Definition at line 199 of file MCMachObjectWriter.h.
getLinkerOptions()
std::vector< std::vector< std::string > > & llvm::MachObjectWriter::getLinkerOptions () inline
Definition at line 255 of file MCMachObjectWriter.h.
getLOHContainer()
MCLOHContainer & llvm::MachObjectWriter::getLOHContainer () inline
Definition at line 207 of file MCMachObjectWriter.h.
getPaddingSize()
uint64_t MachObjectWriter::getPaddingSize (const MCAssembler & Asm, const MCSection * SD) const
Definition at line 133 of file MachObjectWriter.cpp.
References llvm::cast(), llvm::MCSection::getAlign(), getSectionAddress(), llvm::MCSection::isVirtualSection(), llvm::Next, llvm::offsetToAlignment(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by computeSectionAddresses(), and writeObject().
getSectionAddress()
uint64_t llvm::MachObjectWriter::getSectionAddress (const MCSection * Sec) const inline
Definition at line 209 of file MCMachObjectWriter.h.
Referenced by getFragmentAddress(), getPaddingSize(), getSymbolAddress(), and writeObject().
getSectionAddressMap()
SectionAddrMap & llvm::MachObjectWriter::getSectionAddressMap () inline
Definition at line 206 of file MCMachObjectWriter.h.
getSectionOrder()
const llvm::SmallVectorImpl< MCSection * > & llvm::MachObjectWriter::getSectionOrder () const inline
Definition at line 203 of file MCMachObjectWriter.h.
getSymbolAddress()
uint64_t MachObjectWriter::getSymbolAddress (const MCSymbol & S, const MCAssembler & Asm) const
Definition at line 100 of file MachObjectWriter.cpp.
References llvm::Address, llvm::CallingConv::C, llvm::dyn_cast(), llvm::MCExpr::evaluateAsRelocatable(), llvm::MCSymbol::getFragment(), llvm::MCSymbol::getName(), llvm::Target::getName(), llvm::MCFragment::getParent(), getSectionAddress(), getSymbolAddress(), llvm::MCSymbol::getVariableValue(), llvm::MCSymbol::isVariable(), and llvm::report_fatal_error().
Referenced by getSymbolAddress(), writeNlist(), and writeObject().
is64Bit()
bool llvm::MachObjectWriter::is64Bit () const inline
Definition at line 264 of file MCMachObjectWriter.h.
Referenced by populateAddrSigSection(), writeHeader(), writeLinkerOptionsLoadCommand(), writeNlist(), writeObject(), writeSection(), and writeSegmentLoadCommand().
isFixupKindPCRel()
bool MachObjectWriter::isFixupKindPCRel (const MCAssembler & Asm, unsigned Kind)
Definition at line 86 of file MachObjectWriter.cpp.
References llvm::MCFixupKindInfo::FKF_IsPCRel, and llvm::MCFixupKindInfo::Flags.
isSymbolRefDifferenceFullyResolvedImpl()
bool MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl (const MCAssembler & Asm, const MCSymbol & SymA, const MCFragment & FB, bool InSet, bool IsPCRel) const override virtual
Reimplemented from llvm::MCObjectWriter.
Definition at line 714 of file MachObjectWriter.cpp.
References findAliasedSymbol(), llvm::MCFragment::getAtom(), llvm::MCSymbol::getFragment(), llvm::MCFragment::getParent(), llvm::MCSymbol::getSection(), llvm::MCSymbol::isInSection(), llvm::MCSymbol::isTemporary(), isX86_64(), and llvm::MCObjectWriter::SubsectionsViaSymbols.
isX86_64()
bool llvm::MachObjectWriter::isX86_64 () const inline
Definition at line 265 of file MCMachObjectWriter.h.
References llvm::MachO::CPU_TYPE_X86_64.
Referenced by isSymbolRefDifferenceFullyResolvedImpl().
populateAddrSigSection()
void MachObjectWriter::populateAddrSigSection (MCAssembler & Asm)
Definition at line 771 of file MachObjectWriter.cpp.
References addRelocation(), llvm::MachO::GENERIC_RELOC_VANILLA, llvm::MCObjectWriter::getAddrsigSyms(), is64Bit(), llvm::MachO::any_relocation_info::r_word0, and llvm::MachO::any_relocation_info::r_word1.
Referenced by writeObject().
recordRelocation()
void MachObjectWriter::recordRelocation (MCAssembler & Asm, const MCFragment * Fragment, const MCFixup & Fixup, MCValue Target, uint64_t & FixedValue) override virtual
Record a relocation entry.
This routine is called by the assembler after layout and relaxation, and post layout binding. The implementation is responsible for storing information about the relocation so that it can be emitted during writeObject().
Implements llvm::MCObjectWriter.
Definition at line 506 of file MachObjectWriter.cpp.
References Fixup, and isFixupTargetValid().
reset()
void MachObjectWriter::reset () override virtual
lifetime management
Reimplemented from llvm::MCObjectWriter.
Definition at line 47 of file MachObjectWriter.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::StringTableBuilder::clear(), llvm::MCLOHContainer::reset(), and llvm::MCObjectWriter::reset().
setBuildVersion()
void llvm::MachObjectWriter::setBuildVersion (MachO::PlatformType Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion = VersionTuple()) inline
Definition at line 234 of file MCMachObjectWriter.h.
setTargetVariantBuildVersion()
void llvm::MachObjectWriter::setTargetVariantBuildVersion (MachO::PlatformType Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion) inline
Definition at line 244 of file MCMachObjectWriter.h.
setVersionMin()
void llvm::MachObjectWriter::setVersionMin (MCVersionMinType Type, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion = VersionTuple()) inline
Mach-O deployment target version information.
Definition at line 224 of file MCMachObjectWriter.h.
References Type.
writeDysymtabLoadCommand()
void MachObjectWriter::writeDysymtabLoadCommand (uint32_t FirstLocalSymbol, uint32_t NumLocalSymbols, uint32_t FirstExternalSymbol, uint32_t NumExternalSymbols, uint32_t FirstUndefinedSymbol, uint32_t NumUndefinedSymbols, uint32_t IndirectSymbolOffset, uint32_t NumIndirectSymbols)
Definition at line 323 of file MachObjectWriter.cpp.
References assert(), llvm::support::endian::Writer::OS, llvm::raw_ostream::tell(), W, and llvm::support::endian::Writer::write().
Referenced by writeObject().
writeHeader()
void MachObjectWriter::writeHeader (MachO::HeaderFileType Type, unsigned NumLoadCommands, unsigned LoadCommandsSize, bool SubsectionsViaSymbols)
Definition at line 176 of file MachObjectWriter.cpp.
References assert(), is64Bit(), llvm::MachO::MH_MAGIC, llvm::MachO::MH_MAGIC_64, llvm::MachO::MH_SUBSECTIONS_VIA_SYMBOLS, llvm::support::endian::Writer::OS, llvm::MCObjectWriter::SubsectionsViaSymbols, llvm::raw_ostream::tell(), Type, W, and llvm::support::endian::Writer::write().
Referenced by writeObject().
writeLinkeditLoadCommand()
void MachObjectWriter::writeLinkeditLoadCommand (uint32_t Type, uint32_t DataOffset, uint32_t DataSize)
Definition at line 451 of file MachObjectWriter.cpp.
References assert(), llvm::DataSize, llvm::support::endian::Writer::OS, llvm::raw_ostream::tell(), Type, W, and llvm::support::endian::Writer::write().
Referenced by writeObject().
writeLinkerOptionsLoadCommand()
void MachObjectWriter::writeLinkerOptionsLoadCommand (const std::vector< std::string > & Options)
Definition at line 474 of file MachObjectWriter.cpp.
References Align, assert(), ComputeLinkerOptionsLoadCommandSize(), is64Bit(), llvm::offsetToAlignment(), Options, llvm::support::endian::Writer::OS, Size, llvm::raw_ostream::tell(), W, llvm::support::endian::Writer::write(), and llvm::raw_ostream::write_zeros().
Referenced by writeObject().
writeNlist()
void MachObjectWriter::writeNlist (MachSymbolData & MSD, const MCAssembler & Asm)
Definition at line 383 of file MachObjectWriter.cpp.
References llvm::Address, llvm::cast(), llvm::Data, findAliasedSymbol(), getSymbolAddress(), is64Bit(), llvm::MachO::N_ABS, llvm::MachO::N_EXT, llvm::MachO::N_INDR, llvm::MachO::N_PEXT, llvm::MachO::N_SECT, llvm::MachO::N_UNDF, llvm::support::endian::Writer::OS, W, and llvm::support::endian::Writer::write().
Referenced by writeObject().
writeObject()
uint64_t MachObjectWriter::writeObject (MCAssembler & Asm) override virtual
Write the object file and returns the number of bytes written.
This routine is called by the assembler after layout and relaxation is complete, fixups have been evaluated and applied, and relocations generated.
Implements llvm::MCObjectWriter.
Definition at line 785 of file MachObjectWriter.cpp.
References Align, llvm::alignTo(), assert(), llvm::MCSection::begin(), llvm::cast(), llvm::MCObjectWriter::CGProfile, ComputeLinkerOptionsLoadCommandSize(), computeSymbolTable(), llvm::Data, llvm::dbgs(), llvm::MCLOHContainer::emit(), End, llvm::support::endian::Writer::Endian, llvm::MCLOHContainer::getEmitSize(), getLCFromMCVM(), llvm::SectionKind::getMetadata(), getPaddingSize(), getSectionAddress(), llvm::StringTableBuilder::getSize(), getSymbolAddress(), llvm::MachO::INDIRECT_SYMBOL_ABS, llvm::MachO::INDIRECT_SYMBOL_LOCAL, is64Bit(), llvm::isUInt(), LLVM_DEBUG, llvm::MachO::MH_OBJECT, llvm::offsetToAlignment(), llvm::support::endian::Writer::OS, OS, populateAddrSigSection(), llvm::report_fatal_error(), llvm::reverse(), llvm::MachO::S_ATTR_SOME_INSTRUCTIONS, llvm::MachO::S_NON_LAZY_SYMBOL_POINTERS, Size, llvm::MCObjectWriter::SubsectionsViaSymbols, llvm::raw_ostream::tell(), llvm::MachO::VM_PROT_EXECUTE, llvm::MachO::VM_PROT_READ, llvm::MachO::VM_PROT_WRITE, W, llvm::StringTableBuilder::write(), llvm::support::endian::write(), llvm::support::endian::Writer::write(), llvm::raw_ostream::write_zeros(), writeDysymtabLoadCommand(), writeHeader(), writeLinkeditLoadCommand(), writeLinkerOptionsLoadCommand(), writeNlist(), writeSection(), writeSegmentLoadCommand(), and writeSymtabLoadCommand().
writeSection()
void MachObjectWriter::writeSection (const MCAssembler & Asm, const MCSection & Sec, uint64_t VMAddr, uint64_t FileOffset, unsigned Flags, uint64_t RelocationsStart, unsigned NumRelocations)
Definition at line 257 of file MachObjectWriter.cpp.
References assert(), llvm::cast(), is64Bit(), llvm::isUInt(), llvm::Log2(), llvm::support::endian::Writer::OS, llvm::raw_ostream::tell(), W, and llvm::support::endian::Writer::write().
Referenced by writeObject().
writeSegmentLoadCommand()
void MachObjectWriter::writeSegmentLoadCommand (StringRef Name, unsigned NumSections, uint64_t VMAddr, uint64_t VMSize, uint64_t SectionDataStartOffset, uint64_t SectionDataSize, uint32_t MaxProt, uint32_t InitProt)
Write a segment load command.
writeSegmentLoadCommand - Write a segment load command.
Parameters
NumSections The number of sections in this segment.
SectionDataSize The total size of the sections.
Definition at line 217 of file MachObjectWriter.cpp.
References assert(), is64Bit(), Name, llvm::support::endian::Writer::OS, llvm::raw_ostream::tell(), W, and llvm::support::endian::Writer::write().
Referenced by writeObject().
writeSymtabLoadCommand()
void MachObjectWriter::writeSymtabLoadCommand (uint32_t SymbolOffset, uint32_t NumSymbols, uint32_t StringTableOffset, uint32_t StringTableSize)
Definition at line 304 of file MachObjectWriter.cpp.
References assert(), llvm::support::endian::Writer::OS, llvm::raw_ostream::tell(), W, and llvm::support::endian::Writer::write().
Referenced by writeObject().
Member Data Documentation
W
support::endian::Writer llvm::MachObjectWriter::W
Definition at line 183 of file MCMachObjectWriter.h.
Referenced by computeSymbolTable(), llvm::MCLOHDirective::emit(), writeDysymtabLoadCommand(), writeHeader(), writeLinkeditLoadCommand(), writeLinkerOptionsLoadCommand(), writeNlist(), writeObject(), writeSection(), writeSegmentLoadCommand(), and writeSymtabLoadCommand().
The documentation for this class was generated from the following files:
include/llvm/MC/MCMachObjectWriter.h
lib/MC/MachObjectWriter.cpp