LLVM: llvm::jitlink::i386::GOTTableManager Class Reference
llvm::jitlink::i386::GOTTableManager Class Reference
Global Offset Table Builder.
#include "llvm/ExecutionEngine/JITLink/i386.h"
Public Member Functions
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Public Member Functions inherited from llvm::jitlink::TableManager< GOTTableManager >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Static Public Member Functions
static StringRef getSectionName ()
Detailed Description
Global Offset Table Builder.
Definition at line 339 of file i386.h.
Member Function Documentation
createEntry()
Symbol & llvm::jitlink::i386::GOTTableManager::createEntry (LinkGraph & G, Symbol & Target) inline
Definition at line 370 of file i386.h.
References llvm::jitlink::i386::createAnonymousPointer(), and G.
getSectionName()
static StringRef llvm::jitlink::i386::GOTTableManager::getSectionName () inline static
Definition at line 341 of file i386.h.
visitEdge()
bool llvm::jitlink::i386::GOTTableManager::visitEdge (LinkGraph & G, Block * B, Edge & E) inline
Definition at line 343 of file i386.h.
References assert(), B, llvm::dbgs(), DEBUG_WITH_TYPE, llvm::jitlink::i386::Delta32FromGOT, llvm::formatv(), G, llvm::jitlink::TableManager< GOTTableManager >::getEntryForTarget(), llvm::jitlink::Edge::Invalid, and llvm::jitlink::i386::RequestGOTAndTransformToDelta32FromGOT.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/i386.h