LLVM: llvm::InstrProfCorrelatorImpl< IntPtrT > Class Template Reference
llvm::InstrProfCorrelatorImpl< IntPtrT > Class Template Reference abstract
InstrProfCorrelatorImpl - A child of InstrProfCorrelator with a template pointer type so that the ProfileData vector can be materialized.
#include "llvm/ProfileData/InstrProfCorrelator.h"
Public Member Functions
InstrProfCorrelatorImpl (std::unique_ptr< InstrProfCorrelator::Context > Ctx)
const RawInstrProf::ProfileData< IntPtrT > * getDataPointer () const
Return a pointer to the underlying ProfileData vector that this class constructs.
size_t getDataSize () const
Return the number of ProfileData elements.
InstrProfCorrelatorImpl (std::unique_ptr< InstrProfCorrelator::Context > Ctx)
InstrProfCorrelatorImpl (std::unique_ptr< InstrProfCorrelator::Context > Ctx)
bool classof (const InstrProfCorrelator *C)
bool classof (const InstrProfCorrelator *C)
Public Member Functions inherited from llvm::InstrProfCorrelator
std::optional< size_t > getDataSize () const
Return the number of ProfileData elements.
const char * getNamesPointer () const
Return a pointer to the names string that this class constructs.
size_t getNamesSize () const
Return the number of bytes in the names string.
uint64_t getCountersSectionSize () const
Return the size of the counters section in bytes.
InstrProfCorrelatorKind getKind () const
virtual ~InstrProfCorrelator ()=default
Static Public Member Functions
static bool classof (const InstrProfCorrelator *C)
static llvm::Expected< std::unique_ptr< InstrProfCorrelatorImpl< IntPtrT > > > get (std::unique_ptr< InstrProfCorrelator::Context > Ctx, const object::ObjectFile &Obj, ProfCorrelatorKind FileKind)
Static Public Member Functions inherited from llvm::InstrProfCorrelator
static llvm::Expected< std::unique_ptr< InstrProfCorrelator > > get (StringRef Filename, ProfCorrelatorKind FileKind)
Protected Member Functions
Error correlateProfileData (int MaxWarnings) override
Construct a ProfileData vector used to correlate raw instrumentation data to their functions.
virtual void correlateProfileDataImpl (int MaxWarnings, InstrProfCorrelator::CorrelationData *Data=nullptr)=0
virtual Error correlateProfileNameImpl ()=0
Error dumpYaml (int MaxWarnings, raw_ostream &OS) override
Process debug info and dump the correlation data.
void addDataProbe (uint64_t FunctionName, uint64_t CFGHash, IntPtrT CounterOffset, IntPtrT FunctionPtr, uint32_t NumCounters)
template<class T >
T maybeSwap (T Value) const
Protected Member Functions inherited from llvm::InstrProfCorrelator
InstrProfCorrelator (InstrProfCorrelatorKind K, std::unique_ptr< Context > Ctx)
Protected Attributes
std::vector< RawInstrProf::ProfileData< IntPtrT > > Data
Protected Attributes inherited from llvm::InstrProfCorrelator
const std::unique_ptr< Context > Ctx
std::string Names
std::vector< std::string > NamesVec
Additional Inherited Members
Public Types inherited from llvm::InstrProfCorrelator
enum ProfCorrelatorKind { NONE , DEBUG_INFO , BINARY }
Indicate if we should use the debug info or profile metadata sections to correlate.
enum InstrProfCorrelatorKind { CK_32Bit , CK_64Bit }
Static Public Attributes inherited from llvm::InstrProfCorrelator
static const char * FunctionNameAttributeName = "Function Name"
static const char * CFGHashAttributeName = "CFG Hash"
static const char * NumCountersAttributeName = "Num Counters"
Detailed Description
template<class IntPtrT>
class llvm::InstrProfCorrelatorImpl< IntPtrT >
InstrProfCorrelatorImpl - A child of InstrProfCorrelator with a template pointer type so that the ProfileData vector can be materialized.
Definition at line 126 of file InstrProfCorrelator.h.
Constructor & Destructor Documentation
InstrProfCorrelatorImpl() [1/3]
template<class IntPtrT > llvm::InstrProfCorrelatorImpl< IntPtrT >::InstrProfCorrelatorImpl (std::unique_ptr< InstrProfCorrelator::Context > Ctx)
InstrProfCorrelatorImpl() [2/3]
llvm::InstrProfCorrelatorImpl< uint32_t >::InstrProfCorrelatorImpl (std::unique_ptr< InstrProfCorrelator::Context > Ctx)
Definition at line 163 of file InstrProfCorrelator.cpp.
InstrProfCorrelatorImpl() [3/3]
llvm::InstrProfCorrelatorImpl< uint64_t >::InstrProfCorrelatorImpl (std::unique_ptr< InstrProfCorrelator::Context > Ctx)
Definition at line 168 of file InstrProfCorrelator.cpp.
Member Function Documentation
addDataProbe()
template<class IntPtrT > void InstrProfCorrelatorImpl::addDataProbe (uint64_t FunctionName, uint64_t CFGHash, IntPtrT CounterOffset, IntPtrT FunctionPtr, uint32_t NumCounters) protected
Definition at line 257 of file InstrProfCorrelator.cpp.
References llvm::Data, and llvm::NumCounters.
classof() [1/3]
template<class IntPtrT > static bool llvm::InstrProfCorrelatorImpl< IntPtrT >::classof (const InstrProfCorrelator * C) static
classof() [2/3]
bool llvm::InstrProfCorrelatorImpl< uint32_t >::classof (const InstrProfCorrelator * C)
Definition at line 173 of file InstrProfCorrelator.cpp.
References llvm::CallingConv::C.
classof() [3/3]
bool llvm::InstrProfCorrelatorImpl< uint64_t >::classof (const InstrProfCorrelator * C)
Definition at line 177 of file InstrProfCorrelator.cpp.
References llvm::CallingConv::C.
correlateProfileData()
template<class IntPtrT > Error InstrProfCorrelatorImpl::correlateProfileData (int MaxWarnings) override protected virtual
Construct a ProfileData vector used to correlate raw instrumentation data to their functions.
Parameters
MaxWarnings the maximum number of warnings to emit (0 = no limit)
Implements llvm::InstrProfCorrelator.
Definition at line 206 of file InstrProfCorrelator.cpp.
References assert(), llvm::Data, and llvm::make_error().
correlateProfileDataImpl()
template<class IntPtrT > virtual void llvm::InstrProfCorrelatorImpl< IntPtrT >::correlateProfileDataImpl (int MaxWarnings, InstrProfCorrelator::CorrelationData * Data = nullptr) protected pure virtual
correlateProfileNameImpl()
template<class IntPtrT > virtual Error llvm::InstrProfCorrelatorImpl< IntPtrT >::correlateProfileNameImpl () protected pure virtual
dumpYaml()
template<class IntPtrT > Error InstrProfCorrelatorImpl::dumpYaml (int MaxWarnings, raw_ostream & OS) override protected virtual
Process debug info and dump the correlation data.
Parameters
MaxWarnings the maximum number of warnings to emit (0 = no limit)
Implements llvm::InstrProfCorrelator.
Definition at line 243 of file InstrProfCorrelator.cpp.
References llvm::Data, llvm::make_error(), OS, and llvm::Error::success().
get()
template<class IntPtrT > llvm::Expected< std::unique_ptr< InstrProfCorrelatorImpl< IntPtrT > > > InstrProfCorrelatorImpl::get (std::unique_ptr< InstrProfCorrelator::Context > Ctx, const object::ObjectFile & Obj, ProfCorrelatorKind FileKind) static
Definition at line 185 of file InstrProfCorrelator.cpp.
References llvm::DWARFContext::create(), llvm::object::Binary::isCOFF(), llvm::object::Binary::isELF(), llvm::object::Binary::isMachO(), and llvm::make_error().
getDataPointer()
template<class IntPtrT > const RawInstrProf::ProfileData< IntPtrT > * llvm::InstrProfCorrelatorImpl< IntPtrT >::getDataPointer () const inline
Return a pointer to the underlying ProfileData vector that this class constructs.
Definition at line 133 of file InstrProfCorrelator.h.
References llvm::InstrProfCorrelatorImpl< IntPtrT >::Data.
getDataSize()
template<class IntPtrT > size_t llvm::InstrProfCorrelatorImpl< IntPtrT >::getDataSize () const inline
Return the number of ProfileData elements.
Definition at line 138 of file InstrProfCorrelator.h.
References llvm::InstrProfCorrelatorImpl< IntPtrT >::Data.
maybeSwap()
template<class IntPtrT > template<class T > T llvm::InstrProfCorrelatorImpl< IntPtrT >::maybeSwap (T Value) const inline protected
Definition at line 161 of file InstrProfCorrelator.h.
References llvm::byteswap(), and llvm::Value.
Member Data Documentation
Data
template<class IntPtrT > std::vector<RawInstrProf::ProfileData<IntPtrT> > llvm::InstrProfCorrelatorImpl< IntPtrT >::Data protected
Definition at line 145 of file InstrProfCorrelator.h.
Referenced by llvm::InstrProfCorrelatorImpl< IntPtrT >::getDataPointer(), and llvm::InstrProfCorrelatorImpl< IntPtrT >::getDataSize().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/InstrProfCorrelator.h
lib/ProfileData/InstrProfCorrelator.cpp