LLVM: ModuleImportsManager Class Reference
ModuleImportsManager Class Reference
Determine the list of imports and exports for each module.
Public Member Functions
virtual ~ModuleImportsManager ()=default
virtual void computeImportForModule (const GVSummaryMapTy &DefinedGVSummaries, StringRef ModName, FunctionImporter::ImportMapTy &ImportList)
Given the list of globals defined in a module, compute the list of imports as well as the list of "exports", i.e.
Static Public Member Functions
static std::unique_ptr< ModuleImportsManager > create (function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, const ModuleSummaryIndex &Index, DenseMap< StringRef, FunctionImporter::ExportSetTy > *ExportLists=nullptr)
Protected Member Functions
ModuleImportsManager (function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, const ModuleSummaryIndex &Index, DenseMap< StringRef, FunctionImporter::ExportSetTy > *ExportLists=nullptr)
Protected Attributes
function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing
const ModuleSummaryIndex & Index
DenseMap< StringRef, FunctionImporter::ExportSetTy > *const ExportLists
Detailed Description
Determine the list of imports and exports for each module.
Definition at line 436 of file FunctionImport.cpp.
Constructor & Destructor Documentation
ModuleImportsManager()
ModuleImportsManager::ModuleImportsManager (function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, const ModuleSummaryIndex & Index, DenseMap< StringRef, FunctionImporter::ExportSetTy > * ExportLists = nullptr) inline protected
Definition at line 443 of file FunctionImport.cpp.
Referenced by create().
~ModuleImportsManager()
virtual ModuleImportsManager::~ModuleImportsManager () virtual default
Member Function Documentation
computeImportForModule()
void ModuleImportsManager::computeImportForModule (const GVSummaryMapTy & DefinedGVSummaries, StringRef ModName, FunctionImporter::ImportMapTy & ImportList) virtual
Given the list of globals defined in a module, compute the list of imports as well as the list of "exports", i.e.
the list of symbols referenced from another module (that may require promotion).
Definition at line 913 of file FunctionImport.cpp.
References assert(), computeImportForFunction(), llvm::dbgs(), llvm::dyn_cast(), llvm::SmallVectorBase< Size_T >::empty(), ExportLists, getFailureName(), llvm::getHotnessName(), I, ImportInstrLimit, LLVM_DEBUG, llvm::SmallVectorImpl< T >::pop_back_val(), and PrintImportFailures.
create()
std::unique_ptr< ModuleImportsManager > ModuleImportsManager::create (function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, const ModuleSummaryIndex & Index, DenseMap< StringRef, FunctionImporter::ExportSetTy > * ExportLists = nullptr) static
Definition at line 677 of file FunctionImport.cpp.
References llvm::dbgs(), ExportLists, LLVM_DEBUG, ModuleImportsManager(), and WorkloadDefinitions.
Referenced by llvm::ComputeCrossModuleImport(), and ComputeCrossModuleImportForModuleForTest().
Member Data Documentation
ExportLists
DenseMap<StringRef, FunctionImporter::ExportSetTy>* const ModuleImportsManager::ExportLists protected
Definition at line 441 of file FunctionImport.cpp.
Referenced by computeImportForModule(), and create().
Index
const ModuleSummaryIndex& ModuleImportsManager::Index protected
Definition at line 440 of file FunctionImport.cpp.
IsPrevailing
function_ref<bool(GlobalValue::GUID, const GlobalValueSummary *)> ModuleImportsManager::IsPrevailing protected
Definition at line 439 of file FunctionImport.cpp.
The documentation for this class was generated from the following file:
lib/Transforms/IPO/FunctionImport.cpp