LLVM: llvm::HexagonTargetStreamer Class Reference
llvm::HexagonTargetStreamer Class Reference
#include "Target/Hexagon/HexagonTargetStreamer.h"
Public Member Functions
HexagonTargetStreamer (MCStreamer &S)
virtual void emitCodeAlignment (Align Alignment, const MCSubtargetInfo *STI, unsigned MaxBytesToEmit=0)
virtual void emitFAlign (unsigned Size, unsigned MaxBytesToEmit)
virtual void emitCommonSymbolSorted (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment, unsigned AccessGranularity)
virtual void emitLocalCommonSymbolSorted (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlign, unsigned AccessGranularity)
void finish () override
virtual void finishAttributeSection ()
virtual void emitAttribute (unsigned Attribute, unsigned Value)
void emitTargetAttributes (const MCSubtargetInfo &STI)
virtual void reset ()
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 15 of file HexagonTargetStreamer.h.
Constructor & Destructor Documentation
HexagonTargetStreamer()
llvm::HexagonTargetStreamer::HexagonTargetStreamer (MCStreamer & S) inline
Definition at line 17 of file HexagonTargetStreamer.h.
Member Function Documentation
emitAttribute()
virtual void llvm::HexagonTargetStreamer::emitAttribute (unsigned Attribute, unsigned Value) inline virtual
Definition at line 31 of file HexagonTargetStreamer.h.
Referenced by emitTargetAttributes().
emitCodeAlignment()
virtual void llvm::HexagonTargetStreamer::emitCodeAlignment (Align Alignment, const MCSubtargetInfo * STI, unsigned MaxBytesToEmit = 0) inline virtual
Definition at line 18 of file HexagonTargetStreamer.h.
emitCommonSymbolSorted()
virtual void llvm::HexagonTargetStreamer::emitCommonSymbolSorted (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment, unsigned AccessGranularity) inline virtual
Definition at line 21 of file HexagonTargetStreamer.h.
emitFAlign()
virtual void llvm::HexagonTargetStreamer::emitFAlign (unsigned Size, unsigned MaxBytesToEmit) inline virtual
Definition at line 20 of file HexagonTargetStreamer.h.
emitLocalCommonSymbolSorted()
virtual void llvm::HexagonTargetStreamer::emitLocalCommonSymbolSorted (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlign, unsigned AccessGranularity) inline virtual
Definition at line 24 of file HexagonTargetStreamer.h.
emitTargetAttributes()
void HexagonTargetStreamer::emitTargetAttributes (const MCSubtargetInfo & STI)
Definition at line 190 of file HexagonMCELFStreamer.cpp.
References llvm::HexagonAttrs::ARCH, llvm::HexagonAttrs::AUDIO, llvm::HexagonAttrs::CABAC, emitAttribute(), featureToArchVersion(), llvm::Hexagon_MC::getArchVersion(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::Hexagon_MC::getHVXVersion(), llvm::HexagonAttrs::HVXARCH, llvm::HexagonAttrs::HVXIEEEFP, llvm::HexagonAttrs::HVXQFLOAT, and llvm::HexagonAttrs::ZREG.
finish()
void llvm::HexagonTargetStreamer::finish () inline override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 27 of file HexagonTargetStreamer.h.
finishAttributeSection()
virtual void llvm::HexagonTargetStreamer::finishAttributeSection () inline virtual
Definition at line 29 of file HexagonTargetStreamer.h.
Referenced by llvm::HexagonAsmPrinter::emitEndOfAsmFile().
reset()
virtual void llvm::HexagonTargetStreamer::reset () inline virtual
Definition at line 35 of file HexagonTargetStreamer.h.
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonTargetStreamer.h
lib/Target/Hexagon/MCTargetDesc/HexagonMCELFStreamer.cpp