LLVM: llvm::sandboxir::Value Class Reference
llvm::sandboxir::Value Class Reference abstract
A SandboxIR Value has users. This is the base class.
#include "llvm/SandboxIR/SandboxIR.h"
Classes
struct UseToUser
Helper for mapped_iterator.
Public Types
enum class ClassID : unsigned { DEF_VALUE , DEF_USER , DEF_INSTR }
using use_iterator = UserUseIterator
using const_use_iterator = UserUseIterator
using user_iterator = mapped_iterator<sandboxir::UserUseIterator, UseToUser>
using const_user_iterator = user_iterator
Public Member Functions
virtual ~Value ()=default
ClassID getSubclassID () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
user_iterator user_begin ()
user_iterator user_end ()
const_user_iterator user_begin () const
const_user_iterator user_end () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
unsigned getNumUses () const
\Returns the number of user edges (not necessarily to unique users).
bool hasNUsesOrMore (unsigned Num) const
Return true if this value has N uses or more.
bool hasNUses (unsigned Num) const
Return true if this Value has exactly N uses.
Type * getType () const
Context & getContext () const
void replaceUsesWithIf (Value *OtherV, llvm::function_ref< bool(const Use &)> ShouldReplace)
void replaceAllUsesWith (Value *Other)
StringRef getName () const
\Returns the LLVM IR name of the bottom-most LLVM value.
virtual void verify () const =0
Should crash if there is something wrong with the instruction.
std::string getUid () const
Returns the unique id in the form 'SB<number>.' like 'SB1.'.
virtual void dumpCommonHeader (raw_ostream &OS) const
void dumpCommonFooter (raw_ostream &OS) const
void dumpCommonPrefix (raw_ostream &OS) const
void dumpCommonSuffix (raw_ostream &OS) const
void printAsOperandCommon (raw_ostream &OS) const
virtual void dump (raw_ostream &OS) const =0
virtual LLVM_DUMP_METHOD void dump () const =0
Protected Member Functions
void clearValue ()
Value (ClassID SubclassID, llvm::Value *Val, Context &Ctx)
Static Protected Member Functions
static const char * getSubclassIDStr (ClassID ID)
Protected Attributes
ClassID SubclassID
For isa/dyn_cast.
unsigned UID
A unique ID used for forming the name (used for debugging).
llvm::Value * Val = nullptr
The LLVM Value that corresponds to this SandboxIR Value.
Context & Ctx
All values point to the context.
Friends
class Context
class User
class Use
class SelectInst
class LoadInst
class StoreInst
class ReturnInst
template<typename ItTy , typename SBTy >
class LLVMOpUserItToSBTy
raw_ostream & operator<< (raw_ostream &OS, const sandboxir::Value &V)
Detailed Description
A SandboxIR Value has users. This is the base class.
Definition at line 140 of file SandboxIR.h.
Member Typedef Documentation
const_use_iterator
using llvm::sandboxir::Value::const_use_iterator = UserUseIterator
Definition at line 199 of file SandboxIR.h.
const_user_iterator
using llvm::sandboxir::Value::const_user_iterator = user_iterator
Definition at line 223 of file SandboxIR.h.
use_iterator
using llvm::sandboxir::Value::use_iterator = UserUseIterator
Definition at line 198 of file SandboxIR.h.
user_iterator
using llvm::sandboxir::Value::user_iterator = mapped_iterator<sandboxir::UserUseIterator, UseToUser>
Definition at line 222 of file SandboxIR.h.
Member Enumeration Documentation
ClassID
enum class llvm::sandboxir::Value::ClassID : unsigned strong
Enumerator
DEF_VALUE
DEF_USER
DEF_INSTR
Definition at line 142 of file SandboxIR.h.
Constructor & Destructor Documentation
Value()
Value::Value (ClassID SubclassID, llvm::Value * Val, Context & Ctx) protected
Definition at line 80 of file SandboxIR.cpp.
References UID.
~Value()
virtual llvm::sandboxir::Value::~Value () virtual default
Member Function Documentation
clearValue()
void llvm::sandboxir::Value::clearValue () inline protected
Definition at line 189 of file SandboxIR.h.
References Val.
dump() [1/2]
virtual LLVM_DUMP_METHOD void llvm::sandboxir::Value::dump () const pure virtual
Implemented in llvm::Function, llvm::sandboxir::Argument, llvm::sandboxir::Constant, and llvm::sandboxir::User.
dump() [2/2]
virtual void llvm::sandboxir::Value::dump (raw_ostream & OS) const pure virtual
Implemented in llvm::Function, llvm::sandboxir::Argument, llvm::sandboxir::Constant, and llvm::sandboxir::User.
dumpCommonFooter()
void Value::dumpCommonFooter (raw_ostream & OS) const
Definition at line 153 of file SandboxIR.cpp.
References OS, and Val.
dumpCommonHeader()
void Value::dumpCommonHeader (raw_ostream & OS) const virtual
Reimplemented in llvm::sandboxir::User.
Definition at line 149 of file SandboxIR.cpp.
References getSubclassIDStr(), getUid(), OS, and SubclassID.
Referenced by llvm::sandboxir::User::dumpCommonHeader().
dumpCommonPrefix()
void Value::dumpCommonPrefix (raw_ostream & OS) const
Definition at line 162 of file SandboxIR.cpp.
References OS, and Val.
Referenced by llvm::sandboxir::Argument::dump(), and llvm::sandboxir::Constant::dump().
dumpCommonSuffix()
void Value::dumpCommonSuffix (raw_ostream & OS) const
Definition at line 169 of file SandboxIR.cpp.
References getSubclassIDStr(), getUid(), OS, and SubclassID.
Referenced by llvm::sandboxir::Argument::dump(), and llvm::sandboxir::Constant::dump().
getContext()
Context & llvm::sandboxir::Value::getContext () const inline
Definition at line 268 of file SandboxIR.h.
References Ctx.
Referenced by llvm::sandboxir::Constant::getParent().
getName()
StringRef llvm::sandboxir::Value::getName () const inline
\Returns the LLVM IR name of the bottom-most LLVM value.
Definition at line 275 of file SandboxIR.h.
References llvm::Value::getName(), and Val.
Referenced by AddAliasScopeMetadata(), addMappingsFromTLI(), llvm::WinException::beginFunction(), buildDebugInfoForNoopResumeDestroyFunc(), llvm::Attributor::checkForAllCallSites(), createCloneDeclaration(), llvm::OpenMPIRBuilder::createTargetDeinit(), llvm::OpenMPIRBuilder::createTargetInit(), llvm::SystemZAsmPrinter::emitFunctionEntryLabel(), fixupDebugInfoPostExtraction(), FlattenLoopPair(), llvm::ReplayInlineAdvisor::getAdviceImpl(), getBranchHint(), llvm::DeadArgumentEliminationPass::RetOrArg::getDescription(), getFuncAddrForProfData(), llvm::DOTGraphTraits< DOTFuncInfo * >::getGraphName(), llvm::DOTGraphTraits< DOTFuncMSSAInfo * >::getGraphName(), llvm::getInlineCost(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::MachineFunction::getName(), llvm::DOTGraphTraits< AttributorCallGraph * >::getNodeLabel(), llvm::OpenMPIRBuilder::getOrCreateRuntimeFunction(), llvm::OpenMPIRBuilder::getOrCreateSrcLocStr(), llvm::AArch64Subtarget::getPtrAuthBlockAddressDiscriminatorIfEnabled(), llvm::logicalview::LVBinaryReader::includeInlineeLines(), INITIALIZE_PASS(), llvm::SelectionDAGISel::initializeAnalysisResults(), llvm::SelectionDAGISel::initializeAnalysisResults(), llvm::InlineFunction(), isPotentiallyReachable(), llvm::isTLIScalarize(), llvm::lowerGlobalIFuncUsersAsGlobalCtor(), optimizeDoubleFP(), llvm::OptLevelChanger::OptLevelChanger(), llvm::CallGraphNode::print(), llvm::DemandedBits::print(), llvm::DiagnosticInfoUnsupported::print(), llvm::UniformityInfoWrapperPass::print(), llvm::VPWidenCallRecipe::print(), recoverFramePointer(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::CallGraphUpdater::removeFunction(), replaceWithCallToVeclib(), llvm::ArgumentPromotionPass::run(), llvm::FunctionSpecializer::run(), llvm::InlineCostAnnotationPrinterPass::run(), runAttributorLightOnFunctions(), runAttributorOnFunctions(), llvm::JumpThreadingPass::runImpl(), runImpl(), llvm::IRSimilarity::IRInstructionData::setCalleeName(), shouldCheckArgs(), SwitchToLookupTable(), trackInlinedStores(), llvm::logicalview::LVSymbolTable::update(), llvm::Function::updateAfterNameChange(), llvm::UpgradeIntrinsicCall(), llvm::Function::viewCFG(), and llvm::OptLevelChanger::~OptLevelChanger().
getNumUses()
unsigned Value::getNumUses () const
\Returns the number of user edges (not necessarily to unique users).
WARNING: This is a linear-time operation.
Definition at line 108 of file SandboxIR.cpp.
References llvm::range_size(), llvm::Value::users(), and Val.
Referenced by llvm::OpenMPIRBuilder::createTeams(), llvm::OpenMPIRBuilder::emitTargetTask(), and llvm::OpenMPIRBuilder::finalize().
getSubclassID()
ClassID llvm::sandboxir::Value::getSubclassID () const inline
Definition at line 196 of file SandboxIR.h.
References SubclassID.
getSubclassIDStr()
static const char * llvm::sandboxir::Value::getSubclassIDStr (ClassID ID) inline static protected
Definition at line 150 of file SandboxIR.h.
References llvm_unreachable.
Referenced by dumpCommonHeader(), and dumpCommonSuffix().
getType()
Type * llvm::sandboxir::Value::getType () const inline
Definition at line 266 of file SandboxIR.h.
References llvm::Value::getType(), and Val.
Referenced by llvm::Function::getContext(), getTLIFunction(), isKnownNonZeroFromAssume(), llvm::Attributor::isValidFunctionSignatureRewrite(), replaceAllUsesWith(), and replaceUsesWithIf().
getUid()
std::string Value::getUid () const
Returns the unique id in the form 'SB<number>.' like 'SB1.'.
Definition at line 143 of file SandboxIR.cpp.
References UID.
Referenced by dumpCommonHeader(), and dumpCommonSuffix().
hasNUses()
bool llvm::sandboxir::Value::hasNUses (unsigned Num) const inline
Return true if this Value has exactly N uses.
Definition at line 257 of file SandboxIR.h.
References use_begin(), and use_end().
hasNUsesOrMore()
bool llvm::sandboxir::Value::hasNUsesOrMore (unsigned Num) const inline
Return true if this value has N uses or more.
This is logically equivalent to getNumUses() >= N. WARNING: This can be expensive, as it is linear to the number of users.
Definition at line 248 of file SandboxIR.h.
References use_begin(), and use_end().
printAsOperandCommon()
void Value::printAsOperandCommon (raw_ostream & OS) const
Definition at line 173 of file SandboxIR.cpp.
References OS, llvm::Value::printAsOperand(), and Val.
Referenced by llvm::sandboxir::Argument::printAsOperand().
replaceAllUsesWith()
void Value::replaceAllUsesWith (Value * Other)
Definition at line 130 of file SandboxIR.cpp.
References assert(), getType(), llvm::sandboxir::Tracker::isTracking(), llvm::Other, llvm::Value::replaceAllUsesWith(), llvm::sandboxir::Tracker::track(), uses(), and Val.
Referenced by simplifyCommonValuePhi().
replaceUsesWithIf()
void Value::replaceUsesWithIf (Value * OtherV, llvm::function_ref< bool(const Use &)> ShouldReplace)
Definition at line 110 of file SandboxIR.cpp.
References assert(), llvm::cast_or_null(), getType(), llvm::Use::getUser(), llvm::sandboxir::Tracker::isTracking(), llvm::Value::replaceUsesWithIf(), llvm::sandboxir::Tracker::track(), and Val.
use_begin() [1/2]
Value::use_iterator Value::use_begin ()
Definition at line 87 of file SandboxIR.cpp.
References llvm::cast_or_null(), Use, llvm::Value::use_begin(), llvm::Value::use_end(), and Val.
Referenced by hasNUses(), hasNUsesOrMore(), use_begin(), uses(), and uses().
use_begin() [2/2]
const_use_iterator llvm::sandboxir::Value::use_begin () const inline
Definition at line 202 of file SandboxIR.h.
References use_begin().
use_end() [1/2]
use_iterator llvm::sandboxir::Value::use_end () inline
Definition at line 205 of file SandboxIR.h.
References Use.
Referenced by hasNUses(), hasNUsesOrMore(), use_end(), uses(), and uses().
use_end() [2/2]
const_use_iterator llvm::sandboxir::Value::use_end () const inline
Definition at line 206 of file SandboxIR.h.
References use_end().
user_begin() [1/2]
Value::user_iterator Value::user_begin ()
Definition at line 97 of file SandboxIR.cpp.
References llvm::cast_or_null(), Use, llvm::Value::use_begin(), llvm::Value::use_end(), and Val.
Referenced by user_begin(), users(), users(), and llvm::PredicateInfo::~PredicateInfo().
user_begin() [2/2]
const_user_iterator llvm::sandboxir::Value::user_begin () const inline
Definition at line 229 of file SandboxIR.h.
References user_begin().
user_end() [1/2]
user_iterator llvm::sandboxir::Value::user_end () inline
Definition at line 226 of file SandboxIR.h.
References Use.
Referenced by user_end(), users(), users(), and llvm::PredicateInfo::~PredicateInfo().
user_end() [2/2]
const_user_iterator llvm::sandboxir::Value::user_end () const inline
Definition at line 232 of file SandboxIR.h.
References user_end().
users() [1/2]
iterator_range< user_iterator > llvm::sandboxir::Value::users () inline
Definition at line 236 of file SandboxIR.h.
References llvm::make_range(), user_begin(), and user_end().
Referenced by llvm::getNumOfCalls(), llvm::Function::isDefTriviallyDead(), nullifySetjmp(), OptimizeEmptyGlobalAtExitDtors(), llvm::ArgumentPromotionPass::run(), and llvm::UpgradeARCRuntime().
users() [2/2]
iterator_range< const_user_iterator > llvm::sandboxir::Value::users () const inline
Definition at line 239 of file SandboxIR.h.
References llvm::make_range(), user_begin(), and user_end().
uses() [1/2]
iterator_range< use_iterator > llvm::sandboxir::Value::uses () inline
Definition at line 210 of file SandboxIR.h.
References llvm::make_range(), use_begin(), and use_end().
Referenced by llvm::Attributor::checkForAllCallSites(), computeVirtualCallSiteTypeInfoMap(), dropTypeTests(), llvm::Function::hasAddressTaken(), replaceAllPrepares(), replaceAllUsesWith(), runAttributorOnFunctions(), and llvm::updatePublicTypeTestCalls().
uses() [2/2]
iterator_range< const_use_iterator > llvm::sandboxir::Value::uses () const inline
Definition at line 213 of file SandboxIR.h.
References llvm::make_range(), use_begin(), and use_end().
verify()
virtual void llvm::sandboxir::Value::verify () const pure virtual
Should crash if there is something wrong with the instruction.
Implemented in llvm::Function, llvm::sandboxir::Argument, llvm::sandboxir::Constant, and llvm::sandboxir::User.
Friends And Related Symbol Documentation
Context
friend class Context friend
Definition at line 178 of file SandboxIR.h.
LLVMOpUserItToSBTy
template<typename ItTy , typename SBTy > friend class LLVMOpUserItToSBTy friend
Definition at line 190 of file SandboxIR.h.
LoadInst
friend class LoadInst friend
Definition at line 182 of file SandboxIR.h.
operator<<
raw_ostream & operator<< (raw_ostream & OS, const sandboxir::Value & V) friend
Definition at line 287 of file SandboxIR.h.
ReturnInst
friend class ReturnInst friend
Definition at line 184 of file SandboxIR.h.
SelectInst
friend class SelectInst friend
Definition at line 181 of file SandboxIR.h.
StoreInst
friend class StoreInst friend
Definition at line 183 of file SandboxIR.h.
Use
friend class Use friend
Definition at line 180 of file SandboxIR.h.
Referenced by llvm::sandboxir::User::getOperandUseDefault(), use_begin(), use_end(), user_begin(), and user_end().
User
friend class User friend
Definition at line 179 of file SandboxIR.h.
Member Data Documentation
Ctx
Context& llvm::sandboxir::Value::Ctx protected
All values point to the context.
Definition at line 187 of file SandboxIR.h.
Referenced by getContext().
SubclassID
ClassID llvm::sandboxir::Value::SubclassID protected
For isa/dyn_cast.
Definition at line 167 of file SandboxIR.h.
Referenced by dumpCommonHeader(), dumpCommonSuffix(), and getSubclassID().
UID
unsigned llvm::sandboxir::Value::UID protected
A unique ID used for forming the name (used for debugging).
Definition at line 170 of file SandboxIR.h.
Referenced by getUid(), and Value().
Val
llvm::Value* llvm::sandboxir::Value::Val = nullptr protected
The LLVM Value that corresponds to this SandboxIR Value.
NOTE: Some sandboxir Instructions, like Packs, may include more than one value and in these cases Val points to the last instruction in program order.
Definition at line 176 of file SandboxIR.h.
Referenced by llvm::Function::addFnAttr(), clearValue(), dumpCommonFooter(), dumpCommonPrefix(), llvm::Function::getDenormalModeF32Raw(), llvm::Function::getDenormalModeRaw(), getName(), llvm::sandboxir::User::getNumOperands(), getNumUses(), llvm::sandboxir::User::getOperandUseDefault(), getType(), llvm::sandboxir::User::op_begin(), llvm::sandboxir::User::op_end(), printAsOperandCommon(), replaceAllUsesWith(), llvm::sandboxir::User::replaceUsesOfWith(), replaceUsesWithIf(), llvm::sandboxir::User::setOperand(), use_begin(), user_begin(), llvm::sandboxir::Argument::verify(), llvm::sandboxir::Constant::verify(), and llvm::sandboxir::User::verify().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/SandboxIR.h
lib/SandboxIR/SandboxIR.cpp