LLVM: llvm::HashingByteStreamer Class Reference
llvm::HashingByteStreamer Class Reference final
#include "CodeGen/AsmPrinter/ByteStreamer.h"
Public Member Functions
HashingByteStreamer (DIEHash &H)
void emitInt8 (uint8_t Byte, const Twine &Comment) override
void emitSLEB128 (uint64_t DWord, const Twine &Comment) override
void emitULEB128 (uint64_t DWord, const Twine &Comment, unsigned PadTo) override
unsigned emitDIERef (const DIE &D) override
Public Member Functions inherited from llvm::ByteStreamer
Additional Inherited Members
Protected Member Functions inherited from llvm::ByteStreamer
~ByteStreamer ()=default
ByteStreamer (const ByteStreamer &)=default
ByteStreamer ()=default
Detailed Description
Definition at line 69 of file ByteStreamer.h.
Constructor & Destructor Documentation
HashingByteStreamer()
llvm::HashingByteStreamer::HashingByteStreamer (DIEHash & H) inline
Definition at line 73 of file ByteStreamer.h.
Member Function Documentation
emitDIERef()
unsigned llvm::HashingByteStreamer::emitDIERef (const DIE & D) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 84 of file ByteStreamer.h.
References D, and llvm::DIEHash::hashRawTypeReference().
emitInt8()
void llvm::HashingByteStreamer::emitInt8 (uint8_t Byte, const Twine & Comment) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 74 of file ByteStreamer.h.
References llvm::DIEHash::update().
emitSLEB128()
void llvm::HashingByteStreamer::emitSLEB128 (uint64_t DWord, const Twine & Comment) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 77 of file ByteStreamer.h.
References llvm::DIEHash::addSLEB128().
emitULEB128()
void llvm::HashingByteStreamer::emitULEB128 (uint64_t DWord, const Twine & Comment, unsigned PadTo) inline override virtual
Implements llvm::ByteStreamer.
Definition at line 80 of file ByteStreamer.h.
References llvm::DIEHash::addULEB128().
The documentation for this class was generated from the following file:
lib/CodeGen/AsmPrinter/ByteStreamer.h