LLVM: llvm::object::ArchiveMemberHeader Class Reference
llvm::object::ArchiveMemberHeader Class Reference
#include "llvm/Object/Archive.h"
Public Member Functions
ArchiveMemberHeader (const Archive *Parent, const char *RawHeaderPtr, uint64_t Size, Error *Err)
std::unique_ptr< AbstractArchiveMemberHeader > clone () const override
Expected< StringRef > getRawName () const override
Get the name without looking up long names.
Expected< StringRef > getName (uint64_t Size) const override
Get the name looking up long names.
Expected< uint64_t > getSize () const override
Expected< const char * > getNextChildLoc () const override
Get next file member location.
Expected< bool > isThin () const override
Public Member Functions inherited from llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >
CommonArchiveMemberHeader (const Archive *Parent, const UnixArMemHdrType *RawHeaderPtr)
StringRef getRawAccessMode () const override
StringRef getRawLastModified () const override
StringRef getRawUID () const override
StringRef getRawGID () const override
uint64_t getOffset () const override
uint64_t getSizeOf () const override
Returns the size in bytes of the format-defined member header of the concrete archive type.
Public Member Functions inherited from llvm::object::AbstractArchiveMemberHeader
virtual ~AbstractArchiveMemberHeader ()=default
Expected< sys::fs::perms > getAccessMode () const
Expected< sys::TimePoint< std::chrono::seconds > > getLastModified () const
Expected< unsigned > getUID () const
Expected< unsigned > getGID () const
Additional Inherited Members
Public Attributes inherited from llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >
UnixArMemHdrType const * ArMemHdr
Public Attributes inherited from llvm::object::AbstractArchiveMemberHeader
const Archive * Parent
Protected Member Functions inherited from llvm::object::AbstractArchiveMemberHeader
AbstractArchiveMemberHeader (const Archive *Parent)
Detailed Description
Definition at line 102 of file Archive.h.
Constructor & Destructor Documentation
ArchiveMemberHeader()
ArchiveMemberHeader::ArchiveMemberHeader (const Archive * Parent, const char * RawHeaderPtr, uint64_t Size, Error * Err)
Definition at line 95 of file Archive.cpp.
References llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >::ArMemHdr, llvm::consumeError(), createMemberHeaderParseError(), llvm::StringRef::data(), llvm::raw_ostream::flush(), llvm::Expected< T >::get(), llvm::object::Binary::getData(), getName(), llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >::getSizeOf(), malformedError(), llvm::Offset, OS, llvm::object::AbstractArchiveMemberHeader::Parent, Size, llvm::Expected< T >::takeError(), llvm::object::UnixArMemHdrType::Terminator, and llvm::raw_ostream::write_escaped().
Member Function Documentation
clone()
std::unique_ptr< AbstractArchiveMemberHeader > llvm::object::ArchiveMemberHeader::clone () const inline override virtual
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 107 of file Archive.h.
getName()
Expected< StringRef > ArchiveMemberHeader::getName (uint64_t Size) const override virtual
Get the name looking up long names.
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 245 of file Archive.cpp.
References llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >::ArMemHdr, llvm::StringRef::begin(), llvm::StringRef::data(), End, llvm::StringRef::find(), llvm::raw_ostream::flush(), llvm::Expected< T >::get(), llvm::object::Binary::getData(), getRawName(), llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >::getSizeOf(), llvm::object::Archive::getStringTable(), llvm::object::Archive::K_GNU, llvm::object::Archive::K_GNU64, llvm::object::Archive::kind(), malformedError(), llvm::object::UnixArMemHdrType::Name, Name, llvm::StringRef::npos, offsetof, OS, llvm::object::AbstractArchiveMemberHeader::Parent, llvm::StringRef::rtrim(), Size, llvm::StringRef::size(), llvm::StringRef::slice(), llvm::Expected< T >::takeError(), and llvm::raw_ostream::write_escaped().
Referenced by ArchiveMemberHeader().
getNextChildLoc()
Expected< const char * > ArchiveMemberHeader::getNextChildLoc () const override virtual
Get next file member location.
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 426 of file Archive.cpp.
References llvm::alignTo(), llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >::ArMemHdr, llvm::Expected< T >::get(), llvm::MemoryBufferRef::getBufferEnd(), llvm::object::Binary::getMemoryBufferRef(), getSize(), llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >::getSizeOf(), isThin(), llvm::object::AbstractArchiveMemberHeader::Parent, Size, and llvm::Expected< T >::takeError().
getRawName()
Expected< StringRef > ArchiveMemberHeader::getRawName () const override virtual
Get the name without looking up long names.
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 155 of file Archive.cpp.
References llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >::ArMemHdr, assert(), llvm::StringRef::data(), llvm::StringRef::find(), llvm::object::Binary::getData(), llvm::object::Archive::K_BSD, llvm::object::Archive::K_DARWIN64, llvm::object::Archive::kind(), malformedError(), llvm::object::UnixArMemHdrType::Name, llvm::StringRef::npos, llvm::Offset, and llvm::object::AbstractArchiveMemberHeader::Parent.
Referenced by getName(), and isThin().
getSize()
Expected< uint64_t > ArchiveMemberHeader::getSize () const override virtual
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 357 of file Archive.cpp.
References llvm::object::CommonArchiveMemberHeader< UnixArMemHdrType >::ArMemHdr, getArchiveMemberDecField(), getFieldRawString(), llvm::object::AbstractArchiveMemberHeader::Parent, and llvm::object::UnixArMemHdrType::Size.
Referenced by getNextChildLoc().
isThin()
Expected< bool > ArchiveMemberHeader::isThin () const override virtual
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 418 of file Archive.cpp.
References llvm::Expected< T >::get(), getRawName(), llvm::object::Archive::isThin(), Name, llvm::object::AbstractArchiveMemberHeader::Parent, and llvm::Expected< T >::takeError().
Referenced by getNextChildLoc().
The documentation for this class was generated from the following files:
include/llvm/Object/Archive.h
lib/Object/Archive.cpp