LLVM: llvm::coverage::BinaryCoverageReader Class Reference
llvm::coverage::BinaryCoverageReader Class Reference
Reader for the coverage mapping data that is emitted by the frontend and stored in an object file.
#include "llvm/ProfileData/Coverage/CoverageMappingReader.h"
Classes
struct ProfileMappingRecord
Public Types
using FuncRecordsStorage = std::unique_ptr<MemoryBuffer>
Public Member Functions
BinaryCoverageReader (const BinaryCoverageReader &)=delete
BinaryCoverageReader & operator= (const BinaryCoverageReader &)=delete
Error readNextRecord (CoverageMappingRecord &Record) override
Public Member Functions inherited from llvm::coverage::CoverageMappingReader
virtual ~CoverageMappingReader ()=default
CoverageMappingIterator begin ()
CoverageMappingIterator end ()
Static Public Member Functions
static Expected< std::vector< std::unique_ptr< BinaryCoverageReader > > > create (MemoryBufferRef ObjectBuffer, StringRef Arch, SmallVectorImpl< std::unique_ptr< MemoryBuffer > > &ObjectFileBuffers, StringRef CompilationDir="", SmallVectorImpl< object::BuildIDRef > *BinaryIDs=nullptr)
static Expected< std::unique_ptr< BinaryCoverageReader > > createCoverageReaderFromBuffer (StringRef Coverage, FuncRecordsStorage &&FuncRecords, std::unique_ptr< InstrProfSymtab > ProfileNamesPtr, uint8_t BytesInAddress, llvm::endianness Endian, StringRef CompilationDir="")
Detailed Description
Reader for the coverage mapping data that is emitted by the frontend and stored in an object file.
Definition at line 164 of file CoverageMappingReader.h.
Member Typedef Documentation
FuncRecordsStorage
using llvm::coverage::BinaryCoverageReader::FuncRecordsStorage = std::unique_ptr<MemoryBuffer>
Definition at line 182 of file CoverageMappingReader.h.
Constructor & Destructor Documentation
BinaryCoverageReader()
llvm::coverage::BinaryCoverageReader::BinaryCoverageReader (const BinaryCoverageReader &) delete
Member Function Documentation
create()
Expected< std::vector< std::unique_ptr< BinaryCoverageReader > > > BinaryCoverageReader::create (MemoryBufferRef ObjectBuffer, StringRef Arch, SmallVectorImpl< std::unique_ptr< MemoryBuffer > > & ObjectFileBuffers, StringRef CompilationDir = "", SmallVectorImpl< object::BuildIDRef > * BinaryIDs = nullptr) static
Definition at line 1203 of file CoverageMappingReader.cpp.
References llvm::Bin, llvm::support::endian::byte_swap(), llvm::consumeError(), create(), llvm::object::createBinary(), llvm::dyn_cast(), llvm::ArrayRef< T >::empty(), llvm::Expected< T >::get(), llvm::MemoryBufferRef::getBuffer(), llvm::MemoryBufferRef::getBufferStart(), llvm::coverage::invalid_or_missing_arch_specifier, isArchSpecifierInvalidOrMissing(), loadBinaryFormat(), loadTestingFormat(), llvm::make_error(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::StringRef::size(), llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::coverage::TestingFormatMagic.
Referenced by create().
createCoverageReaderFromBuffer()
Expected< std::unique_ptr< BinaryCoverageReader > > BinaryCoverageReader::createCoverageReaderFromBuffer (StringRef Coverage, FuncRecordsStorage && FuncRecords, std::unique_ptr< InstrProfSymtab > ProfileNamesPtr, uint8_t BytesInAddress, llvm::endianness Endian, StringRef CompilationDir = "") static
Definition at line 895 of file CoverageMappingReader.cpp.
References llvm::big, llvm::little, llvm::make_error(), llvm::coverage::malformed, and readCoverageMappingData().
Referenced by loadBinaryFormat(), and loadTestingFormat().
operator=()
BinaryCoverageReader & llvm::coverage::BinaryCoverageReader::operator= (const BinaryCoverageReader &) delete
readNextRecord()
Error BinaryCoverageReader::readNextRecord (CoverageMappingRecord & Record) override virtual
Implements llvm::coverage::CoverageMappingReader.
Definition at line 1295 of file CoverageMappingReader.cpp.
References llvm::ArrayRef(), llvm::coverage::eof, F, llvm::make_error(), llvm::coverage::RawCoverageMappingReader::read(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMappingReader.h
lib/ProfileData/Coverage/CoverageMappingReader.cpp