LLVM: llvm::MachineModuleInfoELF Class Reference
llvm::MachineModuleInfoELF Class Reference
MachineModuleInfoELF - This is a MachineModuleInfoImpl implementation for ELF targets.
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
Public Member Functions
MachineModuleInfoELF (const MachineModuleInfo &)
StubValueTy & getGVStubEntry (MCSymbol *Sym)
const MCExpr *& getAuthPtrStubEntry (MCSymbol *Sym)
SymbolListTy GetGVStubList ()
Accessor methods to return the set of stubs in sorted order.
ExprStubListTy getAuthGVStubList ()
Public Member Functions inherited from llvm::MachineModuleInfoImpl
virtual ~MachineModuleInfoImpl ()
Additional Inherited Members
Public Types inherited from llvm::MachineModuleInfoImpl
using StubValueTy = PointerIntPair<MCSymbol *, 1, bool>
using SymbolListTy = std::vector<std::pair<MCSymbol *, StubValueTy>>
using ExprStubListTy = std::vector<std::pair<MCSymbol *, const MCExpr *>>
A variant of SymbolListTy where the stub is a generalized MCExpr.
Static Protected Member Functions inherited from llvm::MachineModuleInfoImpl
static SymbolListTy getSortedStubs (DenseMap< MCSymbol *, StubValueTy > &)
Return the entries from a DenseMap in a deterministic sorted orer.
static ExprStubListTy getSortedExprStubs (DenseMap< MCSymbol *, const MCExpr * > &)
Return the entries from a DenseMap in a deterministic sorted orer.
Detailed Description
MachineModuleInfoELF - This is a MachineModuleInfoImpl implementation for ELF targets.
Definition at line 77 of file MachineModuleInfoImpls.h.
Constructor & Destructor Documentation
MachineModuleInfoELF()
llvm::MachineModuleInfoELF::MachineModuleInfoELF (const MachineModuleInfo &) inline
Definition at line 89 of file MachineModuleInfoImpls.h.
Member Function Documentation
getAuthGVStubList()
ExprStubListTy llvm::MachineModuleInfoELF::getAuthGVStubList () inline
Definition at line 105 of file MachineModuleInfoImpls.h.
References llvm::MachineModuleInfoImpl::getSortedExprStubs().
getAuthPtrStubEntry()
const MCExpr *& llvm::MachineModuleInfoELF::getAuthPtrStubEntry (MCSymbol * Sym) inline
Definition at line 96 of file MachineModuleInfoImpls.h.
References assert(), and Sym.
getGVStubEntry()
StubValueTy & llvm::MachineModuleInfoELF::getGVStubEntry (MCSymbol * Sym) inline
Definition at line 91 of file MachineModuleInfoImpls.h.
References assert(), and Sym.
Referenced by llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), and llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference().
GetGVStubList()
SymbolListTy llvm::MachineModuleInfoELF::GetGVStubList () inline
Accessor methods to return the set of stubs in sorted order.
Definition at line 103 of file MachineModuleInfoImpls.h.
References llvm::MachineModuleInfoImpl::getSortedStubs().
Referenced by llvm::AsmPrinter::doFinalization().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineModuleInfoImpls.h
lib/CodeGen/MachineModuleInfoImpls.cpp