LLVM: llvm::CleanupInstaller Class Reference
llvm::CleanupInstaller Class Reference
#include "llvm/Support/ToolOutputFile.h"
Public Member Functions
StringRef getFilename ()
CleanupInstaller (StringRef Filename)
~CleanupInstaller ()
Public Attributes
std::string Filename
The name of the file.
bool Keep
The flag which indicates whether we should not delete the file.
Detailed Description
Definition at line 21 of file ToolOutputFile.h.
Constructor & Destructor Documentation
CleanupInstaller()
CleanupInstaller::CleanupInstaller (StringRef Filename) explicit
Definition at line 20 of file ToolOutputFile.cpp.
References Filename, isStdout(), and llvm::sys::RemoveFileOnSignal().
~CleanupInstaller()
CleanupInstaller::~CleanupInstaller ()
Definition at line 27 of file ToolOutputFile.cpp.
References llvm::sys::DontRemoveFileOnSignal(), Filename, isStdout(), Keep, and llvm::sys::fs::remove().
Member Function Documentation
getFilename()
StringRef llvm::CleanupInstaller::getFilename () inline
Definition at line 29 of file ToolOutputFile.h.
References Filename.
Referenced by llvm::ToolOutputFile::getFilename().
Member Data Documentation
Filename
std::string llvm::CleanupInstaller::Filename
The name of the file.
Definition at line 24 of file ToolOutputFile.h.
Referenced by CleanupInstaller(), getFilename(), llvm::ToolOutputFile::outputFilename(), and ~CleanupInstaller().
Keep
bool llvm::CleanupInstaller::Keep
The flag which indicates whether we should not delete the file.
Definition at line 27 of file ToolOutputFile.h.
Referenced by llvm::ToolOutputFile::keep(), llvm::ToolOutputFile::ToolOutputFile(), and ~CleanupInstaller().
The documentation for this class was generated from the following files:
include/llvm/Support/ToolOutputFile.h
lib/Support/ToolOutputFile.cpp