LLVM: llvm::memprof::RecordLookupTrait Class Reference
llvm::memprof::RecordLookupTrait Class Reference
#include "llvm/ProfileData/MemProf.h"
Public Types
using data_type = const IndexedMemProfRecord &
using internal_key_type = uint64_t
using external_key_type = uint64_t
using hash_value_type = uint64_t
using offset_type = uint64_t
Public Member Functions
RecordLookupTrait ()=delete
RecordLookupTrait (IndexedVersion V, const MemProfSchema &S)
hash_value_type ComputeHash (uint64_t K)
uint64_t ReadKey (const unsigned char *D, offset_type)
data_type ReadData (uint64_t K, const unsigned char *D, offset_type)
Static Public Member Functions
static bool EqualKey (uint64_t A, uint64_t B)
static uint64_t GetInternalKey (uint64_t K)
static uint64_t GetExternalKey (uint64_t K)
static std::pair< offset_type, offset_type > ReadKeyDataLength (const unsigned char *&D)
Detailed Description
Definition at line 522 of file MemProf.h.
Member Typedef Documentation
data_type
using llvm::memprof::RecordLookupTrait::data_type = const IndexedMemProfRecord &
Definition at line 524 of file MemProf.h.
external_key_type
using llvm::memprof::RecordLookupTrait::external_key_type = uint64_t
Definition at line 526 of file MemProf.h.
hash_value_type
using llvm::memprof::RecordLookupTrait::hash_value_type = uint64_t
Definition at line 527 of file MemProf.h.
internal_key_type
using llvm::memprof::RecordLookupTrait::internal_key_type = uint64_t
Definition at line 525 of file MemProf.h.
offset_type
using llvm::memprof::RecordLookupTrait::offset_type = uint64_t
Definition at line 528 of file MemProf.h.
Constructor & Destructor Documentation
RecordLookupTrait() [1/2]
llvm::memprof::RecordLookupTrait::RecordLookupTrait () delete
RecordLookupTrait() [2/2]
llvm::memprof::RecordLookupTrait::RecordLookupTrait (IndexedVersion V, const MemProfSchema & S) inline
Definition at line 531 of file MemProf.h.
Member Function Documentation
ComputeHash()
hash_value_type llvm::memprof::RecordLookupTrait::ComputeHash (uint64_t K) inline
Definition at line 538 of file MemProf.h.
EqualKey()
static bool llvm::memprof::RecordLookupTrait::EqualKey (uint64_t A, uint64_t B) inline static
Definition at line 534 of file MemProf.h.
References A, and B.
GetExternalKey()
static uint64_t llvm::memprof::RecordLookupTrait::GetExternalKey (uint64_t K) inline static
Definition at line 536 of file MemProf.h.
GetInternalKey()
static uint64_t llvm::memprof::RecordLookupTrait::GetInternalKey (uint64_t K) inline static
Definition at line 535 of file MemProf.h.
ReadData()
data_type llvm::memprof::RecordLookupTrait::ReadData (uint64_t K, const unsigned char * D, offset_type) inline
Definition at line 556 of file MemProf.h.
References D, and llvm::memprof::IndexedMemProfRecord::deserialize().
ReadKey()
uint64_t llvm::memprof::RecordLookupTrait::ReadKey (const unsigned char * D, offset_type) inline
Definition at line 551 of file MemProf.h.
References D, and llvm::support::endian::readNext().
ReadKeyDataLength()
static std::pair< offset_type, offset_type > llvm::memprof::RecordLookupTrait::ReadKeyDataLength (const unsigned char *& D) inline static
Definition at line 541 of file MemProf.h.
References D, and llvm::support::endian::readNext().
The documentation for this class was generated from the following file:
include/llvm/ProfileData/MemProf.h