LLVM: llvm::logicalview::LVDWARFReader Class Reference
llvm::logicalview::LVDWARFReader Class Reference final
#include "llvm/DebugInfo/LogicalView/Readers/LVDWARFReader.h"
Public Member Functions
LVDWARFReader ()=delete
LVDWARFReader (StringRef Filename, StringRef FileFormatName, object::ObjectFile &Obj, ScopedPrinter &W)
LVDWARFReader (const LVDWARFReader &)=delete
LVDWARFReader & operator= (const LVDWARFReader &)=delete
~LVDWARFReader ()=default
LVAddress getCUBaseAddress () const
void setCUBaseAddress (LVAddress Address)
LVAddress getCUHighAddress () const
void setCUHighAddress (LVAddress Address)
const LVSymbols & GetSymbolsWithLocations () const
std::string getRegisterName (LVSmall Opcode, ArrayRef< uint64_t > Operands) override
void print (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::logicalview::LVBinaryReader
LVBinaryReader ()=delete
LVBinaryReader (StringRef Filename, StringRef FileFormatName, ScopedPrinter &W, LVBinaryType BinaryType)
LVBinaryReader (const LVBinaryReader &)=delete
LVBinaryReader & operator= (const LVBinaryReader &)=delete
virtual ~LVBinaryReader ()=default
void addInlineeLines (LVScope *Scope, LVLines &Lines)
LVAddress linearAddress (uint16_t Segment, uint32_t Offset, LVAddress Addendum=0)
void addToSymbolTable (StringRef Name, LVScope *Function, LVSectionIndex SectionIndex=0)
void addToSymbolTable (StringRef Name, LVAddress Address, LVSectionIndex SectionIndex, bool IsComdat)
LVSectionIndex updateSymbolTable (LVScope *Function)
const LVSymbolTableEntry & getSymbolTableEntry (StringRef Name)
LVAddress getSymbolTableAddress (StringRef Name)
LVSectionIndex getSymbolTableIndex (StringRef Name)
bool getSymbolTableIsComdat (StringRef Name)
LVSectionIndex getSectionIndex (LVScope *Scope) override
void print (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::logicalview::LVReader
LVReader ()=delete
LVReader (StringRef InputFilename, StringRef FileFormatName, ScopedPrinter &W, LVBinaryType BinaryType=LVBinaryType::NONE)
LVReader (const LVReader &)=delete
LVReader & operator= (const LVReader &)=delete
virtual ~LVReader ()=default
LVOperation * createOperation (LVSmall OpCode, ArrayRef< LVUnsigned > Operands)
StringRef getFilename (LVObject *Object, size_t Index) const
StringRef getFilename () const
void setFilename (std::string Name)
StringRef getFileFormatName () const
raw_ostream & outputStream ()
bool isBinaryTypeNone () const
bool isBinaryTypeELF () const
bool isBinaryTypeCOFF () const
LVScopeCompileUnit * getCompileUnit () const
void setCompileUnit (LVScope *Scope)
void setCompileUnitCPUType (codeview::CPUType Type)
codeview::CPUType getCompileUnitCPUType ()
LVScopeRoot * getScopesRoot () const
Error doPrint ()
Error doLoad ()
LVSectionIndex getDotTextSectionIndex () const
virtual bool isSystemEntry (LVElement *Element, StringRef Name={}) const
LVSplitContext & getSplitContext ()
void notifyAddedElement (LVLine *Line)
void notifyAddedElement (LVScope *Scope)
void notifyAddedElement (LVSymbol *Symbol)
void notifyAddedElement (LVType *Type)
const LVLines & getLines () const
const LVScopes & getScopes () const
const LVSymbols & getSymbols () const
const LVTypes & getTypes () const
bool doPrintLine (const LVLine *Line) const
bool doPrintLocation (const LVLocation *Location) const
bool doPrintScope (const LVScope *Scope) const
bool doPrintSymbol (const LVSymbol *Symbol) const
bool doPrintType (const LVType *Type) const
void print (raw_ostream &OS) const
virtual void printRecords (raw_ostream &OS) const
void dump () const
Protected Member Functions
Error createScopes () override
void sortScopes () override
Protected Member Functions inherited from llvm::logicalview::LVBinaryReader
Error loadGenericTargetInfo (StringRef TheTriple, StringRef TheFeatures)
virtual void mapRangeAddress (const object::ObjectFile &Obj, const object::SectionRef &Section, bool IsComdat)
void mapVirtualAddress (const object::ObjectFile &Obj)
void mapVirtualAddress (const object::COFFObjectFile &COFFObj)
Expected< std::pair< LVSectionIndex, object::SectionRef > > getSection (LVScope *Scope, LVAddress Address, LVSectionIndex SectionIndex)
void addSectionRange (LVSectionIndex SectionIndex, LVScope *Scope)
void addSectionRange (LVSectionIndex SectionIndex, LVScope *Scope, LVAddress LowerAddress, LVAddress UpperAddress)
LVRange * getSectionRanges (LVSectionIndex SectionIndex)
void includeInlineeLines (LVSectionIndex SectionIndex, LVScope *Function)
Error createInstructions ()
Error createInstructions (LVScope *Function, LVSectionIndex SectionIndex)
Error createInstructions (LVScope *Function, LVSectionIndex SectionIndex, const LVNameInfo &NameInfo)
void processLines (LVLines *DebugLines, LVSectionIndex SectionIndex)
void processLines (LVLines *DebugLines, LVSectionIndex SectionIndex, LVScope *Function)
Protected Member Functions inherited from llvm::logicalview::LVReader
void addCompileUnitOffset (LVOffset Offset, LVScopeCompileUnit *CompileUnit)
std::string createAlternativePath (StringRef From)
virtual Error printScopes ()
virtual Error printMatchedElements (bool UseMatchedElements)
Additional Inherited Members
Static Public Member Functions inherited from llvm::logicalview::LVReader
static LVReader & getInstance ()
static void setInstance (LVReader *Reader)
Protected Attributes inherited from llvm::logicalview::LVBinaryReader
LVLines CULines
std::unique_ptr< const MCRegisterInfo > MRI
std::unique_ptr< const MCAsmInfo > MAI
std::unique_ptr< const MCSubtargetInfo > STI
std::unique_ptr< const MCInstrInfo > MII
std::unique_ptr< const MCDisassembler > MD
std::unique_ptr< MCContext > MC
std::unique_ptr< MCInstPrinter > MIP
LVAddress WasmCodeSectionOffset = 0
Protected Attributes inherited from llvm::logicalview::LVReader
LVScopeRoot * Root = nullptr
std::string InputFilename
std::string FileFormatName
ScopedPrinter & W
raw_ostream & OS
LVScopeCompileUnit * CompileUnit = nullptr
LVSectionIndex DotTextSectionIndex = UndefinedSectionIndex
Detailed Description
Definition at line 33 of file LVDWARFReader.h.
Constructor & Destructor Documentation
LVDWARFReader() [1/3]
llvm::logicalview::LVDWARFReader::LVDWARFReader () delete
LVDWARFReader() [2/3]
llvm::logicalview::LVDWARFReader::LVDWARFReader (StringRef Filename, StringRef FileFormatName, object::ObjectFile & Obj, ScopedPrinter & W) inline
Definition at line 131 of file LVDWARFReader.h.
LVDWARFReader() [3/3]
llvm::logicalview::LVDWARFReader::LVDWARFReader (const LVDWARFReader &) delete
~LVDWARFReader()
llvm::logicalview::LVDWARFReader::~LVDWARFReader () default
Member Function Documentation
createScopes()
Error LVDWARFReader::createScopes () override protected virtual
Reimplemented from llvm::logicalview::LVReader.
Definition at line 804 of file LVDWARFReader.cpp.
References llvm::logicalview::LVBinaryReader::addSectionRange(), llvm::c_str(), llvm::logicalview::LVRange::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::DWARFContext::create(), llvm::logicalview::LVReader::createAlternativePath(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::logicalview::LVReader::createScopes(), llvm::createStringError(), llvm::logicalview::LVBinaryReader::CULines, llvm::DWARFDebugLine::FileNameEntry::DirIdx, llvm::logicalview::LVReader::FileFormatName, llvm::DWARFDie::find(), From, llvm::DWARFDie::getDwarfUnit(), llvm::object::Binary::getFileName(), llvm::logicalview::LVReader::getFilename(), llvm::logicalview::LVBinaryReader::getSectionIndex(), llvm::logicalview::LVBinaryReader::getSectionRanges(), llvm::invalid_argument, llvm::DWARFUnit::isDWOUnit(), llvm::DWARFDie::isValid(), LLVM_DEBUG, llvm::logicalview::LVBinaryReader::mapVirtualAddress(), llvm::codeview::None, llvm::ScopedPrinter::printString(), llvm::logicalview::LVBinaryReader::processLines(), llvm::DILineInfoSpecifier::RawValue, llvm::logicalview::LVReader::Root, llvm::logicalview::LVRange::sort(), llvm::ScopedPrinter::startLine(), llvm::StringRef::str(), llvm::Error::success(), llvm::dwarf::toString(), and llvm::logicalview::LVReader::W.
dump()
void llvm::logicalview::LVDWARFReader::dump () const inline
Definition at line 154 of file LVDWARFReader.h.
References llvm::dbgs(), and print().
getCUBaseAddress()
LVAddress llvm::logicalview::LVDWARFReader::getCUBaseAddress () const inline
Definition at line 139 of file LVDWARFReader.h.
getCUHighAddress()
LVAddress llvm::logicalview::LVDWARFReader::getCUHighAddress () const inline
Definition at line 141 of file LVDWARFReader.h.
getRegisterName()
std::string LVDWARFReader::getRegisterName (LVSmall Opcode, ArrayRef< uint64_t > Operands) override virtual
Reimplemented from llvm::logicalview::LVReader.
Definition at line 776 of file LVDWARFReader.cpp.
References llvm::DIDumpOptions::GetNameForDWARFReg, llvm::logicalview::LVBinaryReader::MRI, Operands, llvm::DWARFExpression::prettyPrintRegisterOp(), RegName, llvm::raw_string_ostream::str(), and string.
GetSymbolsWithLocations()
const LVSymbols & llvm::logicalview::LVDWARFReader::GetSymbolsWithLocations () const inline
Definition at line 144 of file LVDWARFReader.h.
operator=()
LVDWARFReader & llvm::logicalview::LVDWARFReader::operator= (const LVDWARFReader &) delete
print()
void LVDWARFReader::print (raw_ostream & OS) const
Definition at line 1251 of file LVDWARFReader.cpp.
References llvm::dbgs(), LLVM_DEBUG, and llvm::logicalview::LVReader::OS.
Referenced by dump().
setCUBaseAddress()
void llvm::logicalview::LVDWARFReader::setCUBaseAddress (LVAddress Address) inline
Definition at line 140 of file LVDWARFReader.h.
References llvm::Address.
setCUHighAddress()
void llvm::logicalview::LVDWARFReader::setCUHighAddress (LVAddress Address) inline
Definition at line 142 of file LVDWARFReader.h.
References llvm::Address.
sortScopes()
void LVDWARFReader::sortScopes () override protected virtual
Reimplemented from llvm::logicalview::LVReader.
Definition at line 1249 of file LVDWARFReader.cpp.
References llvm::logicalview::LVReader::Root, and llvm::logicalview::LVScope::sort().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Readers/LVDWARFReader.h
lib/DebugInfo/LogicalView/Readers/LVDWARFReader.cpp