LLVM: llvm::NVPTXTargetMachine Class Reference
llvm::NVPTXTargetMachine Class Reference
NVPTXTargetMachine.
#include "Target/NVPTX/NVPTXTargetMachine.h"
Public Member Functions
NVPTXTargetMachine (const Target &T, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM, CodeGenOptLevel OP, bool is64bit)
~NVPTXTargetMachine () override
const NVPTXSubtarget * getSubtargetImpl (const Function &) const override
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
const NVPTXSubtarget * getSubtargetImpl () const
bool is64Bit () const
NVPTX::DrvInterface getDrvInterface () const
UniqueStringSaver & getStrPool () const
TargetPassConfig * createPassConfig (PassManagerBase &PM) override
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
bool addPassesToEmitMC (PassManagerBase &, MCContext *&, raw_pwrite_stream &, bool=true) override
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
TargetLoweringObjectFile * getObjFileLowering () const override
MachineFunctionInfo * createMachineFunctionInfo (BumpPtrAllocator &Allocator, const Function &F, const TargetSubtargetInfo *STI) const override
Create the target's instance of MachineFunctionInfo.
void registerDefaultAliasAnalyses (AAManager &AAM) override
Allow the target to register alias analyses with the AAManager for use with the new pass manager.
void registerPassBuilderCallbacks (PassBuilder &PB) override
Allow the target to modify the pass pipeline.
TargetTransformInfo getTargetTransformInfo (const Function &F) const override
Get a TargetTransformInfo implementation for the target.
bool isMachineVerifierClean () const override
Returns true if the target is expected to pass all machine verifier checks.
std::pair< const Value *, unsigned > getPredicatedAddrSpace (const Value *V) const override
If the specified predicate checks whether a generic pointer falls within a specified address space, return that generic pointer and the address space being queried.
Public Member Functions inherited from llvm::LLVMTargetMachine
bool addPassesToEmitFile (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, bool DisableVerify=true, MachineModuleInfoWrapperPass *MMIWP=nullptr) override
Add passes to the specified pass manager to get the specified file emitted.
virtual Error buildCodeGenPipeline (ModulePassManager &, raw_pwrite_stream &, raw_pwrite_stream *, CodeGenFileType, const CGPassBuilderOption &, PassInstrumentationCallbacks *)
bool addAsmPrinter (PassManagerBase &PM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Context)
Adds an AsmPrinter pass to the pipeline that prints assembly or machine code from the MI representation.
Expected< std::unique_ptr< MCStreamer > > createMCStreamer (raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType, MCContext &Ctx)
virtual bool usesPhysRegsForValues () const
True if the target uses physical regs (as nearly all targets do).
virtual bool useIPRA () const
True if the target wants to use interprocedural register allocation by default.
virtual int unqualifiedInlineAsmVariant () const
The default variant to use in unqualified asm instructions.
virtual void registerMachineRegisterInfoCallback (MachineFunction &MF) const
Public Member Functions inherited from llvm::TargetMachine
TargetMachine (const TargetMachine &)=delete
void operator= (const TargetMachine &)=delete
virtual ~TargetMachine ()
const Target & getTarget () const
const Triple & getTargetTriple () const
StringRef getTargetCPU () const
StringRef getTargetFeatureString () const
void setTargetFeatureString (StringRef FS)
virtual yaml::MachineFunctionInfo * createDefaultFuncInfoYAML () const
Allocate and return a default initialized instance of the YAML representation for the MachineFunctionInfo.
virtual yaml::MachineFunctionInfo * convertFuncInfoToYAML (const MachineFunction &MF) const
Allocate and initialize an instance of the YAML representation of the MachineFunctionInfo.
virtual bool parseMachineFunctionInfo (const yaml::MachineFunctionInfo &, PerFunctionMIParsingState &PFS, SMDiagnostic &Error, SMRange &SourceRange) const
Parse out the target's MachineFunctionInfo from the YAML reprsentation.
template<typename STC >
const STC & getSubtarget (const Function &F) const
This method returns a pointer to the specified type of TargetSubtargetInfo.
const DataLayout createDataLayout () const
Create a DataLayout.
bool isCompatibleDataLayout (const DataLayout &Candidate) const
Test if a DataLayout if compatible with the CodeGen for this target.
unsigned getPointerSize (unsigned AS) const
Get the pointer size for this target.
unsigned getPointerSizeInBits (unsigned AS) const
unsigned getProgramPointerSize () const
unsigned getAllocaPointerSize () const
void resetTargetOptions (const Function &F) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
Return target specific asm information.
const MCRegisterInfo * getMCRegisterInfo () const
const MCInstrInfo * getMCInstrInfo () const
const MCSubtargetInfo * getMCSubtargetInfo () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
If intrinsic information is available, return it. If not, return null.
bool requiresStructuredCFG () const
void setRequiresStructuredCFG (bool Value)
Reloc::Model getRelocationModel () const
Returns the code generation relocation model.
CodeModel::Model getCodeModel () const
Returns the code model.
uint64_t getMaxCodeSize () const
Returns the maximum code size possible under the code model.
void setCodeModel (CodeModel::Model CM)
Set the code model.
void setLargeDataThreshold (uint64_t LDT)
bool isLargeGlobalValue (const GlobalValue *GV) const
bool isPositionIndependent () const
bool shouldAssumeDSOLocal (const GlobalValue *GV) const
bool useEmulatedTLS () const
Returns true if this target uses emulated TLS.
bool useTLSDESC () const
Returns true if this target uses TLS Descriptors.
TLSModel::Model getTLSModel (const GlobalValue *GV) const
Returns the TLS model which should be used for the given global variable.
CodeGenOptLevel getOptLevel () const
Returns the optimization level: None, Less, Default, or Aggressive.
void setOptLevel (CodeGenOptLevel Level)
Overrides the optimization level.
void setFastISel (bool Enable)
bool getO0WantsFastISel ()
void setO0WantsFastISel (bool Enable)
void setGlobalISel (bool Enable)
void setGlobalISelAbort (GlobalISelAbortMode Mode)
void setMachineOutliner (bool Enable)
void setSupportsDefaultOutlining (bool Enable)
void setSupportsDebugEntryValues (bool Enable)
void setCFIFixup (bool Enable)
bool getAIXExtendedAltivecABI () const
bool getUniqueSectionNames () const
bool getUniqueBasicBlockSectionNames () const
Return true if unique basic block section names must be generated.
bool getSeparateNamedSections () const
bool getDataSections () const
Return true if data objects should be emitted into their own section, corresponds to -fdata-sections.
bool getFunctionSections () const
Return true if functions should be emitted into their own section, corresponding to -ffunction-sections.
bool getIgnoreXCOFFVisibility () const
Return true if visibility attribute should not be emitted in XCOFF, corresponding to -mignore-xcoff-visibility.
bool getXCOFFTracebackTable () const
Return true if XCOFF traceback table should be emitted, corresponding to -xcoff-traceback-table.
llvm::BasicBlockSection getBBSectionsType () const
If basic blocks should be emitted into their own section, corresponding to -fbasic-block-sections.
const MemoryBuffer * getBBSectionsFuncListBuf () const
Get the list of functions and basic block ids that need unique sections.
virtual bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast between SrcAS and DestAS is a noop.
void setPGOOption (std::optional< PGOOptions > PGOOpt)
const std::optional< PGOOptions > & getPGOOption () const
virtual unsigned getAssumedAddrSpace (const Value *V) const
If the specified generic pointer could be assumed as a pointer to a specific address space, return that address space.
TargetIRAnalysis getTargetIRAnalysis () const
Get a TargetIRAnalysis appropriate for the target.
virtual bool targetSchedulesPostRAScheduling () const
True if subtarget inserts the final scheduling pass on its own.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV, Mangler &Mang, bool MayAlwaysUsePrivate=false) const
MCSymbol * getSymbol (const GlobalValue *GV) const
virtual unsigned getSjLjDataSize () const
virtual unsigned getAddressSpaceForPseudoSourceKind (unsigned Kind) const
getAddressSpaceForPseudoSourceKind - Given the kind of memory (e.g.
virtual bool splitModule (Module &M, unsigned NumParts, function_ref< void(std::unique_ptr< Module > MPart)> ModuleCallback)
Entry point for module splitting.
Additional Inherited Members
Static Public Member Functions inherited from llvm::TargetMachine
static std::pair< int, int > parseBinutilsVersion (StringRef Version)
Public Attributes inherited from llvm::TargetMachine
TargetOptions Options
Static Public Attributes inherited from llvm::TargetMachine
static constexpr unsigned DefaultSjLjDataSize = 32
The integer bit size to use for SjLj based exception handling.
Protected Member Functions inherited from llvm::LLVMTargetMachine
LLVMTargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOptLevel OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef DataLayoutString, const Triple &TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
The Target that this machine was created for.
const DataLayout DL
DataLayout for the target: keep ABI type size and alignment.
Triple TargetTriple
Triple string, CPU name, and target feature strings the TargetMachine instance is created with.
std::string TargetCPU
std::string TargetFS
Reloc::Model RM = Reloc::Static
CodeModel::Model CMModel = CodeModel::Small
uint64_t LargeDataThreshold = 0
CodeGenOptLevel OptLevel = CodeGenOptLevel::Default
std::unique_ptr< const MCAsmInfo > AsmInfo
Contains target specific asm information.
std::unique_ptr< const MCRegisterInfo > MRI
std::unique_ptr< const MCInstrInfo > MII
std::unique_ptr< const MCSubtargetInfo > STI
unsigned RequireStructuredCFG: 1
unsigned O0WantsFastISel: 1
std::optional< PGOOptions > PGOOption
Detailed Description
NVPTXTargetMachine.
Definition at line 25 of file NVPTXTargetMachine.h.
Constructor & Destructor Documentation
NVPTXTargetMachine()
NVPTXTargetMachine::NVPTXTargetMachine (const Target & T, const Triple & TT, StringRef CPU, StringRef FS, const TargetOptions & Options, std::optional< Reloc::Model > RM, std::optional< CodeModel::Model > CM, CodeGenOptLevel OP, bool is64bit)
Definition at line 125 of file NVPTXTargetMachine.cpp.
References llvm::NVPTX::CUDA, DisableRequireStructuredCFG, if(), llvm::LLVMTargetMachine::initAsmInfo(), llvm::NVPTX::NVCL, llvm::Triple::NVCL, and llvm::TargetMachine::setRequiresStructuredCFG().
~NVPTXTargetMachine()
NVPTXTargetMachine::~NVPTXTargetMachine () override default
Member Function Documentation
addPassesToEmitMC()
bool llvm::NVPTXTargetMachine::addPassesToEmitMC (PassManagerBase & PM, MCContext *& Ctx, raw_pwrite_stream & Out, bool DisableVerify = true) inline override virtual
Add passes to the specified pass manager to get machine code emitted with the MCJIT.
addPassesToEmitMC - Add passes to the specified pass manager to get machine code emitted with the MCJIT.
This method returns true if machine code is not supported. It fills the MCContext Ctx pointer which can be used to build custom MCStreamer.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 55 of file NVPTXTargetMachine.h.
createMachineFunctionInfo()
MachineFunctionInfo * NVPTXTargetMachine::createMachineFunctionInfo (BumpPtrAllocator & Allocator, const Function & F, const TargetSubtargetInfo * STI) const override virtual
Create the target's instance of MachineFunctionInfo.
Reimplemented from llvm::TargetMachine.
Definition at line 217 of file NVPTXTargetMachine.cpp.
References llvm::MachineFunctionInfo::create(), F, and llvm::TargetMachine::STI.
createPassConfig()
TargetPassConfig * NVPTXTargetMachine::createPassConfig (PassManagerBase & PM) override virtual
Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 213 of file NVPTXTargetMachine.cpp.
getDrvInterface()
NVPTX::DrvInterface llvm::NVPTXTargetMachine::getDrvInterface () const inline
Definition at line 47 of file NVPTXTargetMachine.h.
Referenced by llvm::NVPTXSubtarget::hasImageHandles().
getObjFileLowering()
TargetLoweringObjectFile * llvm::NVPTXTargetMachine::getObjFileLowering () const inline override virtual
Reimplemented from llvm::TargetMachine.
Definition at line 59 of file NVPTXTargetMachine.h.
getPredicatedAddrSpace()
std::pair< const Value *, unsigned > NVPTXTargetMachine::getPredicatedAddrSpace (const Value * V) const override virtual
If the specified predicate checks whether a generic pointer falls within a specified address space, return that generic pointer and the address space being queried.
Such predicates could be specified in @llvm.assume intrinsics for the optimizer to assume that the given generic pointer always falls within the address space based on that predicate.
Reimplemented from llvm::TargetMachine.
Definition at line 249 of file NVPTXTargetMachine.cpp.
References llvm::ADDRESS_SPACE_CONST, llvm::ADDRESS_SPACE_GLOBAL, llvm::ADDRESS_SPACE_LOCAL, llvm::ADDRESS_SPACE_SHARED, llvm::dyn_cast(), and II.
getStrPool()
UniqueStringSaver & llvm::NVPTXTargetMachine::getStrPool () const inline
Definition at line 48 of file NVPTXTargetMachine.h.
Referenced by llvm::NVPTXTargetLowering::LowerCall().
getSubtargetImpl() [1/2]
const NVPTXSubtarget * llvm::NVPTXTargetMachine::getSubtargetImpl () const inline
Definition at line 45 of file NVPTXTargetMachine.h.
getSubtargetImpl() [2/2]
const NVPTXSubtarget * llvm::NVPTXTargetMachine::getSubtargetImpl (const Function &) const inline override virtual
Virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 42 of file NVPTXTargetMachine.h.
Referenced by llvm::NVPTXAsmPrinter::doInitialization().
getTargetTransformInfo()
TargetTransformInfo NVPTXTargetMachine::getTargetTransformInfo (const Function & F) const override virtual
Get a TargetTransformInfo implementation for the target.
The TTI returned uses the common code generator to answer queries about the IR.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 244 of file NVPTXTargetMachine.cpp.
References F.
is64Bit()
bool llvm::NVPTXTargetMachine::is64Bit () const inline
Definition at line 46 of file NVPTXTargetMachine.h.
Referenced by llvm::NVPTXFrameLowering::emitPrologue(), and llvm::NVPTXTargetLowering::LowerDYNAMIC_STACKALLOC().
isMachineVerifierClean()
bool llvm::NVPTXTargetMachine::isMachineVerifierClean () const inline override virtual
Returns true if the target is expected to pass all machine verifier checks.
This is a stopgap measure to fix targets one by one. We will remove this at some point and always enable the verifier when EXPENSIVE_CHECKS is enabled.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 73 of file NVPTXTargetMachine.h.
registerDefaultAliasAnalyses()
void NVPTXTargetMachine::registerDefaultAliasAnalyses (AAManager &) override virtual
Allow the target to register alias analyses with the AAManager for use with the new pass manager.
Only affects the "default" AAManager.
Reimplemented from llvm::TargetMachine.
Definition at line 224 of file NVPTXTargetMachine.cpp.
References llvm::AAManager::registerFunctionAnalysis().
registerPassBuilderCallbacks()
void NVPTXTargetMachine::registerPassBuilderCallbacks (PassBuilder &) override virtual
Allow the target to modify the pass pipeline.
Reimplemented from llvm::TargetMachine.
Definition at line 228 of file NVPTXTargetMachine.cpp.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::createModuleToFunctionPassAdaptor(), llvm::NVPTXSubtarget::getSmVersion(), PB(), and llvm::PassBuilder::registerPipelineStartEPCallback().
The documentation for this class was generated from the following files:
lib/Target/NVPTX/NVPTXTargetMachine.h
lib/Target/NVPTX/NVPTXTargetMachine.cpp