LLVM: llvm::XtensaConstantPoolMBB Class Reference
llvm::XtensaConstantPoolMBB Class Reference
XtensaConstantPoolMBB - Xtensa-specific constantpool value of a machine basic block.
#include "Target/Xtensa/XtensaConstantPoolValue.h"
Public Member Functions
const MachineBasicBlock * getMBB () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
bool hasSameValue (XtensaConstantPoolValue *ACPV) override
hasSameValue - Return true if this Xtensa constpool value can share the same constantpool entry as another Xtensa constpool value.
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const XtensaConstantPoolMBB *A) const
Public Member Functions inherited from llvm::XtensaConstantPoolValue
~XtensaConstantPoolValue () override
XtensaCP::XtensaCPModifier getModifier () const
bool hasModifier () const
StringRef getModifierText () const
unsigned getLabelId () const
void setLabelId (unsigned ID)
bool isExtSymbol () const
bool isBlockAddress () const
bool isMachineBasicBlock () const
bool isJumpTable () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
bool equals (const XtensaConstantPoolValue *A) const
void print (raw_ostream &O) const override
print - Implement operator<<
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
virtual unsigned getSizeInBytes (const DataLayout &DL) const
Static Public Member Functions
static XtensaConstantPoolMBB * Create (LLVMContext &C, const MachineBasicBlock *M, unsigned ID)
static bool classof (const XtensaConstantPoolValue *ACPV)
Additional Inherited Members
Protected Member Functions inherited from llvm::XtensaConstantPoolValue
XtensaConstantPoolValue (Type *Ty, unsigned ID, XtensaCP::XtensaCPKind Kind, XtensaCP::XtensaCPModifier Modifier=XtensaCP::no_modifier)
XtensaConstantPoolValue (LLVMContext &C, unsigned id, XtensaCP::XtensaCPKind Kind, XtensaCP::XtensaCPModifier Modifier=XtensaCP::no_modifier)
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, Align Alignment)
Detailed Description
XtensaConstantPoolMBB - Xtensa-specific constantpool value of a machine basic block.
Definition at line 197 of file XtensaConstantPoolValue.h.
Member Function Documentation
addSelectionDAGCSEId()
void XtensaConstantPoolMBB::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 170 of file XtensaConstantPoolValue.cpp.
References llvm::XtensaConstantPoolValue::addSelectionDAGCSEId().
classof()
static bool llvm::XtensaConstantPoolMBB::classof (const XtensaConstantPoolValue * ACPV) inline static
Definition at line 220 of file XtensaConstantPoolValue.h.
References llvm::XtensaConstantPoolValue::isMachineBasicBlock().
Create()
XtensaConstantPoolMBB * XtensaConstantPoolMBB::Create (LLVMContext & C, const MachineBasicBlock * M, unsigned ID) static
Definition at line 153 of file XtensaConstantPoolValue.cpp.
References llvm::CallingConv::C.
equals()
bool llvm::XtensaConstantPoolMBB::equals (const XtensaConstantPoolMBB * A) const inline
Definition at line 224 of file XtensaConstantPoolValue.h.
References A, llvm::XtensaConstantPoolValue::equals(), and MBB.
getExistingMachineCPValue()
int XtensaConstantPoolMBB::getExistingMachineCPValue (MachineConstantPool * CP, Align Alignment) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 159 of file XtensaConstantPoolValue.cpp.
References llvm::XtensaConstantPoolValue::getExistingMachineCPValueImpl().
getMBB()
const MachineBasicBlock * llvm::XtensaConstantPoolMBB::getMBB () const inline
Definition at line 207 of file XtensaConstantPoolValue.h.
References MBB.
hasSameValue()
bool XtensaConstantPoolMBB::hasSameValue (XtensaConstantPoolValue * ACPV) override virtual
hasSameValue - Return true if this Xtensa constpool value can share the same constantpool entry as another Xtensa constpool value.
Reimplemented from llvm::XtensaConstantPoolValue.
Definition at line 164 of file XtensaConstantPoolValue.cpp.
References llvm::dyn_cast(), and llvm::XtensaConstantPoolValue::hasSameValue().
print()
void XtensaConstantPoolMBB::print (raw_ostream & O) const override virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Definition at line 175 of file XtensaConstantPoolValue.cpp.
References llvm::MachineBasicBlock::getNumber(), and llvm::XtensaConstantPoolValue::print().
The documentation for this class was generated from the following files:
lib/Target/Xtensa/XtensaConstantPoolValue.h
lib/Target/Xtensa/XtensaConstantPoolValue.cpp