LLVM: llvm::MachineVerifierPass Class Reference
llvm::MachineVerifierPass Class Reference
#include "llvm/CodeGen/MachineVerifier.h"
Public Member Functions
MachineVerifierPass (const std::string &Banner=std::string())
PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MFAM)
Public Member Functions inherited from llvm::PassInfoMixin< MachineVerifierPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< MachineVerifierPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 16 of file MachineVerifier.h.
Constructor & Destructor Documentation
MachineVerifierPass()
llvm::MachineVerifierPass::MachineVerifierPass (const std::string & Banner = std::string()) inline
Definition at line 20 of file MachineVerifier.h.
Member Function Documentation
run()
PreservedAnalyses MachineVerifierPass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MFAM)
Definition at line 347 of file MachineVerifier.cpp.
References llvm::PreservedAnalyses::all(), llvm::MachineFunctionProperties::FailsVerification, llvm::MachineFunction::getProperties(), llvm::MachineFunctionProperties::hasProperty(), and llvm::report_fatal_error().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineVerifier.h
lib/CodeGen/MachineVerifier.cpp