LLVM: llvm::PPCTargetLowering Class Reference
llvm::PPCTargetLowering Class Reference
#include "Target/PowerPC/PPCISelLowering.h"
Classes
struct CallFlags
Structure that collects some common arguments that get passed around between the functions for call lowering.
Public Member Functions
PPCTargetLowering (const PPCTargetMachine &TM, const PPCSubtarget &STI)
const char * getTargetNodeName (unsigned Opcode) const override
getTargetNodeName() - This method returns the name of a target specific DAG node.
bool isSelectSupported (SelectSupportKind Kind) const override
TargetLoweringBase::LegalizeTypeAction getPreferredVectorAction (MVT VT) const override
getPreferredVectorAction - The code we generate when vector types are legalized by promoting the integer element type is often much worse than code we generate if we widen the type for applicable vector types.
bool useSoftFloat () const override
bool hasSPE () const
MVT getScalarShiftAmountTy (const DataLayout &, EVT) const override
Return the type to use for a scalar shift opcode, given the shifted amount type.
bool isCheapToSpeculateCttz (Type *Ty) const override
Return true if it is cheap to speculate a call to intrinsic cttz.
bool isCheapToSpeculateCtlz (Type *Ty) const override
Return true if it is cheap to speculate a call to intrinsic ctlz.
bool shallExtractConstSplatVectorElementToStore (Type *VectorTy, unsigned ElemSizeInBits, unsigned &Index) const override
Return true if the target shall perform extract vector element and store given that the vector is known to be splat of constant.
bool isCtlzFast () const override
Return true if ctlz instruction is fast.
bool isEqualityCmpFoldedWithSignedCmp () const override
Return true if instruction generated for equality comparison is folded with instruction generated for signed comparison.
bool hasAndNotCompare (SDValue) const override
Return true if the target should transform: (X & Y) == Y ---> (~X & Y) == 0 (X & Y) != Y ---> (~X & Y) != 0.
bool preferIncOfAddToSubOfNot (EVT VT) const override
These two forms are equivalent: sub y, (xor x, -1) add (add x, 1), y The variant with two add's is IR-canonical.
bool convertSetCCLogicToBitwiseLogic (EVT VT) const override
Use bitwise logic to make pairs of compares more efficient.
SDValue getNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOps, bool OptForSize, NegatibleCost &Cost, unsigned Depth=0) const override
Return the newly negated expression if the cost is not expensive and set the cost in Cost to indicate that if it is cheaper or neutral to do the negation.
EVT getSetCCResultType (const DataLayout &DL, LLVMContext &Context, EVT VT) const override
getSetCCResultType - Return the ISD::SETCC ValueType
bool enableAggressiveFMAFusion (EVT VT) const override
Return true if target always benefits from combining into FMA for a given value type.
bool getPreIndexedAddressParts (SDNode *N, SDValue &Base, SDValue &Offset, ISD::MemIndexedMode &AM, SelectionDAG &DAG) const override
getPreIndexedAddressParts - returns true by value, base pointer and offset pointer and addressing mode by reference if the node's address can be legally represented as pre-indexed load / store address.
bool SelectAddressEVXRegReg (SDValue N, SDValue &Base, SDValue &Index, SelectionDAG &DAG) const
SelectAddressEVXRegReg - Given the specified addressed, check to see if it can be more efficiently represented as [r+imm].
bool SelectAddressRegReg (SDValue N, SDValue &Base, SDValue &Index, SelectionDAG &DAG, MaybeAlign EncodingAlignment=std::nullopt) const
SelectAddressRegReg - Given the specified addressed, check to see if it can be more efficiently represented as [r+imm].
bool SelectAddressRegImm (SDValue N, SDValue &Disp, SDValue &Base, SelectionDAG &DAG, MaybeAlign EncodingAlignment) const
SelectAddressRegImm - Returns true if the address N can be represented by a base register plus a signed 16-bit displacement [r+imm], and if it is not better represented as reg+reg.
bool SelectAddressRegImm34 (SDValue N, SDValue &Disp, SDValue &Base, SelectionDAG &DAG) const
Similar to the 16-bit case but for instructions that take a 34-bit displacement field (prefixed loads/stores).
bool SelectAddressRegRegOnly (SDValue N, SDValue &Base, SDValue &Index, SelectionDAG &DAG) const
SelectAddressRegRegOnly - Given the specified addressed, force it to be represented as an indexed [r+r] operation.
bool SelectAddressPCRel (SDValue N, SDValue &Base) const
SelectAddressPCRel - Represent the specified address as pc relative to be represented as [pc+imm].
Sched::Preference getSchedulingPreference (SDNode *N) const override
Some scheduler, e.g.
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
LowerOperation - Provide custom lowering hooks for some operations.
void ReplaceNodeResults (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const override
ReplaceNodeResults - Replace the results of node with an illegal result type with new values built out of custom code.
SDValue expandVSXLoadForLE (SDNode *N, DAGCombinerInfo &DCI) const
SDValue expandVSXStoreForLE (SDNode *N, DAGCombinerInfo &DCI) const
SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const override
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
SDValue BuildSDIVPow2 (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, SmallVectorImpl< SDNode * > &Created) const override
Targets may override this function to provide custom SDIV lowering for power-of-2 denominators.
Register getRegisterByName (const char *RegName, LLT VT, const MachineFunction &MF) const override
Return the register ID of the name passed in.
void computeKnownBitsForTargetNode (const SDValue Op, KnownBits &Known, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth=0) const override
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
Align getPrefLoopAlignment (MachineLoop *ML) const override
Return the preferred loop alignment.
bool shouldInsertFencesForAtomic (const Instruction *I) const override
Whether AtomicExpandPass should automatically insert fences and reduce ordering for this atomic.
Instruction * emitLeadingFence (IRBuilderBase &Builder, Instruction *Inst, AtomicOrdering Ord) const override
Inserts in the IR a target-specific intrinsic specifying a fence.
Instruction * emitTrailingFence (IRBuilderBase &Builder, Instruction *Inst, AtomicOrdering Ord) const override
bool shouldInlineQuadwordAtomics () const
TargetLowering::AtomicExpansionKind shouldExpandAtomicRMWInIR (AtomicRMWInst *AI) const override
Returns how the IR-level AtomicExpand pass should expand the given AtomicRMW, if at all.
TargetLowering::AtomicExpansionKind shouldExpandAtomicCmpXchgInIR (AtomicCmpXchgInst *AI) const override
Returns how the given atomic cmpxchg should be expanded by the IR-level AtomicExpand pass.
Value * emitMaskedAtomicRMWIntrinsic (IRBuilderBase &Builder, AtomicRMWInst *AI, Value *AlignedAddr, Value *Incr, Value *Mask, Value *ShiftAmt, AtomicOrdering Ord) const override
Perform a masked atomicrmw using a target-specific intrinsic.
Value * emitMaskedAtomicCmpXchgIntrinsic (IRBuilderBase &Builder, AtomicCmpXchgInst *CI, Value *AlignedAddr, Value *CmpVal, Value *NewVal, Value *Mask, AtomicOrdering Ord) const override
Perform a masked cmpxchg using a target-specific intrinsic.
MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr &MI, MachineBasicBlock *MBB) const override
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
MachineBasicBlock * EmitAtomicBinary (MachineInstr &MI, MachineBasicBlock *MBB, unsigned AtomicSize, unsigned BinOpcode, unsigned CmpOpcode=0, unsigned CmpPred=0) const
MachineBasicBlock * EmitPartwordAtomicBinary (MachineInstr &MI, MachineBasicBlock *MBB, bool is8bit, unsigned Opcode, unsigned CmpOpcode=0, unsigned CmpPred=0) const
MachineBasicBlock * emitEHSjLjSetJmp (MachineInstr &MI, MachineBasicBlock *MBB) const
MachineBasicBlock * emitEHSjLjLongJmp (MachineInstr &MI, MachineBasicBlock *MBB) const
MachineBasicBlock * emitProbedAlloca (MachineInstr &MI, MachineBasicBlock *MBB) const
bool hasInlineStackProbe (const MachineFunction &MF) const override
unsigned getStackProbeSize (const MachineFunction &MF) const
ConstraintType getConstraintType (StringRef Constraint) const override
getConstraintType - Given a constraint, return the type of constraint it is for this target.
ConstraintWeight getSingleConstraintMatchWeight (AsmOperandInfo &info, const char *constraint) const override
Examine constraint string and operand type and determine a weight value.
std::pair< unsigned, const TargetRegisterClass * > getRegForInlineAsmConstraint (const TargetRegisterInfo *TRI, StringRef Constraint, MVT VT) const override
Given a physical register constraint (e.g.
uint64_t getByValTypeAlignment (Type *Ty, const DataLayout &DL) const override
getByValTypeAlignment - Return the desired alignment for ByVal aggregate function arguments in the caller parameter area.
void LowerAsmOperandForConstraint (SDValue Op, StringRef Constraint, std::vector< SDValue > &Ops, SelectionDAG &DAG) const override
LowerAsmOperandForConstraint - Lower the specified operand into the Ops vector.
InlineAsm::ConstraintCode getInlineAsmMemConstraint (StringRef ConstraintCode) const override
void CollectTargetIntrinsicOperands (const CallInst &I, SmallVectorImpl< SDValue > &Ops, SelectionDAG &DAG) const override
bool isLegalAddressingMode (const DataLayout &DL, const AddrMode &AM, Type *Ty, unsigned AS, Instruction *I=nullptr) const override
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
bool isLegalICmpImmediate (int64_t Imm) const override
isLegalICmpImmediate - Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
bool isLegalAddImmediate (int64_t Imm) const override
isLegalAddImmediate - Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register and the immediate without having to materialize the immediate into a register.
bool isTruncateFree (Type *Ty1, Type *Ty2) const override
isTruncateFree - Return true if it's free to truncate a value of type Ty1 to type Ty2.
bool isTruncateFree (EVT VT1, EVT VT2) const override
bool isZExtFree (SDValue Val, EVT VT2) const override
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
bool isFPExtFree (EVT DestVT, EVT SrcVT) const override
Return true if an fpext operation is free (for instance, because single-precision floating-point numbers are implicitly extended to double-precision).
bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const override
Returns true if it is beneficial to convert a load of a constant to just the constant itself.
bool convertSelectOfConstantsToMath (EVT VT) const override
Return true if a select of constants (select Cond, C1, C2) should be transformed into simple math ops with the condition value.
bool decomposeMulByConstant (LLVMContext &Context, EVT VT, SDValue C) const override
Return true if it is profitable to transform an integer multiplication-by-constant into simpler operations like shifts and adds.
bool isDesirableToTransformToIntegerOp (unsigned Opc, EVT VT) const override
Return true if it is profitable for dag combiner to transform a floating point op of specified opcode to a equivalent op of an integer type.
bool isAccessedAsGotIndirect (SDValue N) const
bool isOffsetFoldingLegal (const GlobalAddressSDNode *GA) const override
Return true if folding a constant offset with the given GlobalAddress is legal.
bool getTgtMemIntrinsic (IntrinsicInfo &Info, const CallInst &I, MachineFunction &MF, unsigned Intrinsic) const override
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory).
EVT getOptimalMemOpType (const MemOp &Op, const AttributeList &FuncAttributes) const override
It returns EVT::Other if the type should be determined using generic target-independent logic.
bool allowsMisalignedMemoryAccesses (EVT VT, unsigned AddrSpace, Align Alignment=Align(1), MachineMemOperand::Flags Flags=MachineMemOperand::MONone, unsigned *Fast=nullptr) const override
Is unaligned memory access allowed for the given type, and is it fast relative to software emulation.
bool isFMAFasterThanFMulAndFAdd (const MachineFunction &MF, EVT VT) const override
isFMAFasterThanFMulAndFAdd - Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
bool isFMAFasterThanFMulAndFAdd (const Function &F, Type *Ty) const override
IR version.
bool isProfitableToHoist (Instruction *I) const override
isProfitableToHoist - Check if it is profitable to hoist instruction I to its dominator block.
const MCPhysReg * getScratchRegisters (CallingConv::ID CC) const override
Returns a 0 terminated array of registers that can be safely used as scratch registers.
bool shouldExpandBuildVectorWithShuffles (EVT VT, unsigned DefinedValues) const override
bool shouldKeepZExtForFP16Conv () const override
Does this target require the clearing of high-order bits in a register passed to the fp16 to fp conversion library function.
FastISel * createFastISel (FunctionLoweringInfo &FuncInfo, const TargetLibraryInfo *LibInfo) const override
createFastISel - This method returns a target-specific FastISel object, or null if the target does not support "fast" instruction selection.
bool functionArgumentNeedsConsecutiveRegisters (Type *Ty, CallingConv::ID CallConv, bool isVarArg, const DataLayout &DL) const override
Returns true if an argument of type Ty needs to be passed in a contiguous block of registers in calling convention CallConv.
Register getExceptionPointerRegister (const Constant *PersonalityFn) const override
If a physical register, this returns the register that receives the exception address on entry to an EH pad.
Register getExceptionSelectorRegister (const Constant *PersonalityFn) const override
If a physical register, this returns the register that receives the exception typeid on entry to a landing pad.
bool useLoadStackGuardNode () const override
Override to support customized stack guard loading.
void insertSSPDeclarations (Module &M) const override
Inserts necessary declarations for SSP (stack protection) purpose.
Value * getSDagStackGuard (const Module &M) const override
Return the variable that's previously inserted by insertSSPDeclarations, if any, otherwise return nullptr.
bool isFPImmLegal (const APFloat &Imm, EVT VT, bool ForCodeSize) const override
Returns true if the target can instruction select the specified FP immediate natively.
unsigned getJumpTableEncoding () const override
Return the entry encoding for a jump table in the current function.
bool isJumpTableRelative () const override
SDValue getPICJumpTableRelocBase (SDValue Table, SelectionDAG &DAG) const override
Returns relocation base for the given PIC jumptable.
const MCExpr * getPICJumpTableRelocBaseExpr (const MachineFunction *MF, unsigned JTI, MCContext &Ctx) const override
This returns the relocation base for the given PIC jumptable, the same as getPICJumpTableRelocBase, but as an MCExpr.
PPC::AddrMode SelectOptimalAddrMode (const SDNode *Parent, SDValue N, SDValue &Disp, SDValue &Base, SelectionDAG &DAG, MaybeAlign Align) const
SelectOptimalAddrMode - Based on a node N and it's Parent (a MemSDNode), compute the address flags of the node, get the optimal address mode based on the flags, and set the Base and Disp based on the address mode.
PPC::AddrMode SelectForceXFormMode (SDValue N, SDValue &Disp, SDValue &Base, SelectionDAG &DAG) const
SelectForceXFormMode - Given the specified address, force it to be represented as an indexed [r+r] operation (an XForm instruction).
bool splitValueIntoRegisterParts (SelectionDAG &DAG, const SDLoc &DL, SDValue Val, SDValue *Parts, unsigned NumParts, MVT PartVT, std::optional< CallingConv::ID > CC) const override
Target-specific splitting of values into parts that fit a register storing a legal type.
CCAssignFn * ccAssignFnForCall (CallingConv::ID CC, bool Return, bool IsVarArg) const
bool supportsTailCallFor (const CallBase *CB) const
Public Member Functions inherited from llvm::TargetLowering
TargetLowering (const TargetLowering &)=delete
TargetLowering & operator= (const TargetLowering &)=delete
TargetLowering (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
bool isPositionIndependent () const
virtual bool isSDNodeSourceOfDivergence (const SDNode *N, FunctionLoweringInfo *FLI, UniformityInfo *UA) const
virtual bool isReassocProfitable (SelectionDAG &DAG, SDValue N0, SDValue N1) const
virtual bool isReassocProfitable (MachineRegisterInfo &MRI, Register N0, Register N1) const
virtual bool isSDNodeAlwaysUniform (const SDNode *N) const
virtual bool getPostIndexedAddressParts (SDNode *, SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
Returns true by value, base pointer and offset pointer and addressing mode by reference if this node can be combined with a load / store to form a post-indexed load / store.
virtual bool isIndexingLegal (MachineInstr &MI, Register Base, Register Offset, bool IsPre, MachineRegisterInfo &MRI) const
Returns true if the specified base+offset is a legal indexed addressing mode for this target.
virtual const MCExpr * LowerCustomJumpTableEntry (const MachineJumpTableInfo *, const MachineBasicBlock *, unsigned, MCContext &) const
virtual bool isInlineAsmTargetBranch (const SmallVectorImpl< StringRef > &AsmStrs, unsigned OpNo) const
On x86, return true if the operand with index OpNo is a CALL or JUMP instruction, which can use either a memory constraint or an address constraint.
bool isInTailCallPosition (SelectionDAG &DAG, SDNode *Node, SDValue &Chain) const
Check whether a given call node is in tail position within its function.
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, const SDLoc &DL, const SDValue OldLHS, const SDValue OldRHS) const
Soften the operands of a comparison.
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, const SDLoc &DL, const SDValue OldLHS, const SDValue OldRHS, SDValue &Chain, bool IsSignaling=false) const
virtual SDValue visitMaskedLoad (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, MachineMemOperand *MMO, SDValue &NewLoad, SDValue Ptr, SDValue PassThru, SDValue Mask) const
virtual SDValue visitMaskedStore (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, MachineMemOperand *MMO, SDValue Ptr, SDValue Val, SDValue Mask) const
std::pair< SDValue, SDValue > makeLibCall (SelectionDAG &DAG, RTLIB::Libcall LC, EVT RetVT, ArrayRef< SDValue > Ops, MakeLibCallOptions CallOptions, const SDLoc &dl, SDValue Chain=SDValue()) const
Returns a pair of (return value, chain).
bool parametersInCSRMatch (const MachineRegisterInfo &MRI, const uint32_t *CallerPreservedMask, const SmallVectorImpl< CCValAssign > &ArgLocs, const SmallVectorImpl< SDValue > &OutVals) const
Check whether parameters to a call that are passed in callee saved registers are the same as from the calling function.
virtual bool findOptimalMemOpLowering (std::vector< EVT > &MemOps, unsigned Limit, const MemOp &Op, unsigned DstAS, unsigned SrcAS, const AttributeList &FuncAttributes) const
Determines the optimal series of memory ops to replace the memset / memcpy.
bool ShrinkDemandedConstant (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, TargetLoweringOpt &TLO) const
Check to see if the specified operand of the specified instruction is a constant integer.
bool ShrinkDemandedConstant (SDValue Op, const APInt &DemandedBits, TargetLoweringOpt &TLO) const
Helper wrapper around ShrinkDemandedConstant, demanding all elements.
virtual bool targetShrinkDemandedConstant (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, TargetLoweringOpt &TLO) const
bool ShrinkDemandedOp (SDValue Op, unsigned BitWidth, const APInt &DemandedBits, TargetLoweringOpt &TLO) const
Convert x+y to (VT)((SmallVT)x+(SmallVT)y) if the casts are free.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Look at Op.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Helper wrapper around SimplifyDemandedBits, demanding all elements.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, DAGCombinerInfo &DCI) const
Helper wrapper around SimplifyDemandedBits.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, DAGCombinerInfo &DCI) const
Helper wrapper around SimplifyDemandedBits.
SDValue SimplifyMultipleUseDemandedBits (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, SelectionDAG &DAG, unsigned Depth=0) const
More limited version of SimplifyDemandedBits that can be used to "look through" ops that don't contribute to the DemandedBits/DemandedElts - bitwise ops etc.
SDValue SimplifyMultipleUseDemandedBits (SDValue Op, const APInt &DemandedBits, SelectionDAG &DAG, unsigned Depth=0) const
Helper wrapper around SimplifyMultipleUseDemandedBits, demanding all elements.
SDValue SimplifyMultipleUseDemandedVectorElts (SDValue Op, const APInt &DemandedElts, SelectionDAG &DAG, unsigned Depth=0) const
Helper wrapper around SimplifyMultipleUseDemandedBits, demanding all bits from only some vector elements.
bool SimplifyDemandedVectorElts (SDValue Op, const APInt &DemandedEltMask, APInt &KnownUndef, APInt &KnownZero, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Look at Vector Op.
bool SimplifyDemandedVectorElts (SDValue Op, const APInt &DemandedElts, DAGCombinerInfo &DCI) const
Helper wrapper around SimplifyDemandedVectorElts.
virtual bool shouldSimplifyDemandedVectorElts (SDValue Op, const TargetLoweringOpt &TLO) const
Return true if the target supports simplifying demanded vector elements by converting them to undefs.
virtual void computeKnownBitsForTargetInstr (GISelKnownBits &Analysis, Register R, KnownBits &Known, const APInt &DemandedElts, const MachineRegisterInfo &MRI, unsigned Depth=0) const
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
virtual Align computeKnownAlignForTargetInstr (GISelKnownBits &Analysis, Register R, const MachineRegisterInfo &MRI, unsigned Depth=0) const
Determine the known alignment for the pointer value R.
virtual void computeKnownBitsForFrameIndex (int FIOp, KnownBits &Known, const MachineFunction &MF) const
Determine which of the bits of FrameIndex FIOp are known to be 0.
virtual unsigned ComputeNumSignBitsForTargetNode (SDValue Op, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth=0) const
This method can be implemented by targets that want to expose additional information about sign bits to the DAG Combiner.
virtual unsigned computeNumSignBitsForTargetInstr (GISelKnownBits &Analysis, Register R, const APInt &DemandedElts, const MachineRegisterInfo &MRI, unsigned Depth=0) const
This method can be implemented by targets that want to expose additional information about sign bits to GlobalISel combiners.
virtual bool SimplifyDemandedVectorEltsForTargetNode (SDValue Op, const APInt &DemandedElts, APInt &KnownUndef, APInt &KnownZero, TargetLoweringOpt &TLO, unsigned Depth=0) const
Attempt to simplify any target nodes based on the demanded vector elements, returning true on success.
virtual bool SimplifyDemandedBitsForTargetNode (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0) const
Attempt to simplify any target nodes based on the demanded bits/elts, returning true on success.
virtual SDValue SimplifyMultipleUseDemandedBitsForTargetNode (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, SelectionDAG &DAG, unsigned Depth) const
More limited version of SimplifyDemandedBits that can be used to "look through" ops that don't contribute to the DemandedBits/DemandedElts - bitwise ops etc.
virtual bool isGuaranteedNotToBeUndefOrPoisonForTargetNode (SDValue Op, const APInt &DemandedElts, const SelectionDAG &DAG, bool PoisonOnly, unsigned Depth) const
Return true if this function can prove that Op is never poison and, if PoisonOnly is false, does not have undef bits.
virtual bool canCreateUndefOrPoisonForTargetNode (SDValue Op, const APInt &DemandedElts, const SelectionDAG &DAG, bool PoisonOnly, bool ConsiderFlags, unsigned Depth) const
Return true if Op can create undef or poison from non-undef & non-poison operands.
SDValue buildLegalVectorShuffle (EVT VT, const SDLoc &DL, SDValue N0, SDValue N1, MutableArrayRef< int > Mask, SelectionDAG &DAG) const
Tries to build a legal vector shuffle using the provided parameters or equivalent variations.
virtual const Constant * getTargetConstantFromLoad (LoadSDNode *LD) const
This method returns the constant pool value that will be loaded by LD.
virtual bool isKnownNeverNaNForTargetNode (SDValue Op, const SelectionDAG &DAG, bool SNaN=false, unsigned Depth=0) const
If SNaN is false,.
virtual bool isSplatValueForTargetNode (SDValue Op, const APInt &DemandedElts, APInt &UndefElts, const SelectionDAG &DAG, unsigned Depth=0) const
Return true if vector Op has the same value across all DemandedElts, indicating any elements which may be undef in the output UndefElts.
virtual bool isTargetCanonicalConstantNode (SDValue Op) const
Returns true if the given Opc is considered a canonical constant for the target, which should not be transformed back into a BUILD_VECTOR.
bool isConstTrueVal (SDValue N) const
Return if the N is a constant or constant vector equal to the true value from getBooleanContents().
bool isConstFalseVal (SDValue N) const
Return if the N is a constant or constant vector equal to the false value from getBooleanContents().
bool isExtendedTrueVal (const ConstantSDNode *N, EVT VT, bool SExt) const
Return if N is a True value when extended to VT.
SDValue SimplifySetCC (EVT VT, SDValue N0, SDValue N1, ISD::CondCode Cond, bool foldBooleans, DAGCombinerInfo &DCI, const SDLoc &dl) const
Try to simplify a setcc built with the specified operands and cc.
virtual SDValue unwrapAddress (SDValue N) const
virtual bool isGAPlusOffset (SDNode *N, const GlobalValue *&GA, int64_t &Offset) const
Returns true (and the GlobalValue and the offset) if the node is a GlobalAddress + offset.
virtual bool isDesirableToCommuteWithShift (const SDNode *N, CombineLevel Level) const
Return true if it is profitable to move this shift by a constant amount through its operand, adjusting any immediate operands as necessary to preserve semantics.
virtual bool isDesirableToCommuteWithShift (const MachineInstr &MI, bool IsAfterLegal) const
GlobalISel - return true if it is profitable to move this shift by a constant amount through its operand, adjusting any immediate operands as necessary to preserve semantics.
virtual bool isDesirableToPullExtFromShl (const MachineInstr &MI) const
GlobalISel - return true if it's profitable to perform the combine: shl ([sza]ext x), y => zext (shl x, y)
virtual AndOrSETCCFoldKind isDesirableToCombineLogicOpOfSETCC (const SDNode *LogicOp, const SDNode *SETCC0, const SDNode *SETCC1) const
virtual bool isDesirableToCommuteXorWithShift (const SDNode *N) const
Return true if it is profitable to combine an XOR of a logical shift to create a logical shift of NOT.
virtual bool isTypeDesirableForOp (unsigned, EVT VT) const
Return true if the target has native support for the specified value type and it is 'desirable' to use the type for the given node type.
virtual bool IsDesirableToPromoteOp (SDValue, EVT &) const
This method query the target whether it is beneficial for dag combiner to promote the specified node.
virtual bool supportSwiftError () const
Return true if the target supports swifterror attribute.
virtual bool supportSplitCSR (MachineFunction *MF) const
Return true if the target supports that a subset of CSRs for the given machine function is handled explicitly via copies.
virtual bool supportKCFIBundles () const
Return true if the target supports kcfi operand bundles.
virtual bool supportPtrAuthBundles () const
Return true if the target supports ptrauth operand bundles.
virtual void initializeSplitCSR (MachineBasicBlock *Entry) const
Perform necessary initialization to handle a subset of CSRs explicitly via copies.
virtual void insertCopiesSplitCSR (MachineBasicBlock *Entry, const SmallVectorImpl< MachineBasicBlock * > &Exits) const
Insert explicit copies in entry and exit blocks.
SDValue getCheaperOrNeutralNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOps, bool OptForSize, const NegatibleCost CostThreshold=NegatibleCost::Neutral, unsigned Depth=0) const
SDValue getCheaperNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOps, bool OptForSize, unsigned Depth=0) const
This is the helper function to return the newly negated expression only when the cost is cheaper.
SDValue getNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOps, bool OptForSize, unsigned Depth=0) const
This is the helper function to return the newly negated expression if the cost is not expensive.
virtual bool checkForPhysRegDependency (SDNode *Def, SDNode *User, unsigned Op, const TargetRegisterInfo *TRI, const TargetInstrInfo *TII, unsigned &PhysReg, int &Cost) const
Allows the target to handle physreg-carried dependency in target-specific way.
virtual SDValue joinRegisterPartsIntoValue (SelectionDAG &DAG, const SDLoc &DL, const SDValue *Parts, unsigned NumParts, MVT PartVT, EVT ValueVT, std::optional< CallingConv::ID > CC) const
Target-specific combining of register parts into its original value.
std::pair< SDValue, SDValue > LowerCallTo (CallLoweringInfo &CLI) const
This function lowers an abstract call to a function into an actual call.
virtual void HandleByVal (CCState *, unsigned &, Align) const
Target-specific cleanup for formal ByVal parameters.
virtual bool isUsedByReturnOnly (SDNode *, SDValue &) const
Return true if result of the specified node is used by a return node only.
virtual EVT getTypeForExtReturn (LLVMContext &Context, EVT VT, ISD::NodeType) const
Return the type that should be used to zero or sign extend a zeroext/signext integer return value.
virtual bool shouldSplitFunctionArgumentsAsLittleEndian (const DataLayout &DL) const
For most targets, an LLVM type must be broken down into multiple smaller types.
virtual ArrayRef< MCPhysReg > getRoundingControlRegisters () const
Returns a 0 terminated array of rounding control registers that can be attached into strict FP call.
virtual SDValue prepareVolatileOrAtomicLoad (SDValue Chain, const SDLoc &DL, SelectionDAG &DAG) const
This callback is used to prepare for a volatile or atomic load.
virtual void LowerOperationWrapper (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const
This callback is invoked by the type legalizer to legalize nodes with an illegal operand type but legal result types.
bool verifyReturnAddressArgumentIsConstant (SDValue Op, SelectionDAG &DAG) const
virtual void verifyTargetSDNode (const SDNode *N) const
Check the given SDNode. Aborts if it is invalid.
virtual bool ExpandInlineAsm (CallInst *) const
This hook allows the target to expand an inline asm call to be explicit llvm code if it wants to.
virtual AsmOperandInfoVector ParseConstraints (const DataLayout &DL, const TargetRegisterInfo *TRI, const CallBase &Call) const
Split up the constraint string from the inline assembly value into the specific constraints and their prefixes, and also tie in the associated operand values.
virtual ConstraintWeight getMultipleConstraintMatchWeight (AsmOperandInfo &info, int maIndex) const
Examine constraint type and operand type and determine a weight value.
virtual void ComputeConstraintToUse (AsmOperandInfo &OpInfo, SDValue Op, SelectionDAG *DAG=nullptr) const
Determines the constraint code and constraint type to use for the specific AsmOperandInfo, setting OpInfo.ConstraintCode and OpInfo.ConstraintType.
ConstraintGroup getConstraintPreferences (AsmOperandInfo &OpInfo) const
Given an OpInfo with list of constraints codes as strings, return a sorted Vector of pairs of constraint codes and their types in priority of what we'd prefer to lower them as.
virtual const char * LowerXConstraint (EVT ConstraintVT) const
Try to replace an X constraint, which matches anything, with another that has more specific requirements based on the type of the corresponding operand.
virtual SDValue LowerAsmOutputForConstraint (SDValue &Chain, SDValue &Glue, const SDLoc &DL, const AsmOperandInfo &OpInfo, SelectionDAG &DAG) const
SDValue BuildSDIV (SDNode *N, SelectionDAG &DAG, bool IsAfterLegalization, SmallVectorImpl< SDNode * > &Created) const
Given an ISD::SDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number.
SDValue BuildUDIV (SDNode *N, SelectionDAG &DAG, bool IsAfterLegalization, SmallVectorImpl< SDNode * > &Created) const
Given an ISD::UDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number.
SDValue buildSDIVPow2WithCMov (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, SmallVectorImpl< SDNode * > &Created) const
Build sdiv by power-of-2 with conditional move instructions Ref: "Hacker's Delight" by Henry Warren 10-1 If conditional move/branch is preferred, we lower sdiv x, +/-2**k into: bgez x, label add x, x, 2**k-1 label: sra res, x, k neg res, res (when the divisor is negative)
virtual SDValue BuildSREMPow2 (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, SmallVectorImpl< SDNode * > &Created) const
Targets may override this function to provide custom SREM lowering for power-of-2 denominators.
SDValue createSelectForFMINNUM_FMAXNUM (SDNode *Node, SelectionDAG &DAG) const
Try to convert the fminnum/fmaxnum to a compare/select sequence.
bool expandMUL_LOHI (unsigned Opcode, EVT VT, const SDLoc &dl, SDValue LHS, SDValue RHS, SmallVectorImpl< SDValue > &Result, EVT HiLoVT, SelectionDAG &DAG, MulExpansionKind Kind, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
Expand a MUL or [US]MUL_LOHI of n-bit values into two or four nodes, respectively, each computing an n/2-bit part of the result.
bool expandMUL (SDNode *N, SDValue &Lo, SDValue &Hi, EVT HiLoVT, SelectionDAG &DAG, MulExpansionKind Kind, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
Expand a MUL into two nodes.
bool expandDIVREMByConstant (SDNode *N, SmallVectorImpl< SDValue > &Result, EVT HiLoVT, SelectionDAG &DAG, SDValue LL=SDValue(), SDValue LH=SDValue()) const
Attempt to expand an n-bit div/rem/divrem by constant using a n/2-bit urem by constant and other arithmetic ops.
SDValue expandFunnelShift (SDNode *N, SelectionDAG &DAG) const
Expand funnel shift.
SDValue expandROT (SDNode *N, bool AllowVectorOps, SelectionDAG &DAG) const
Expand rotations.
void expandShiftParts (SDNode *N, SDValue &Lo, SDValue &Hi, SelectionDAG &DAG) const
Expand shift-by-parts.
bool expandFP_TO_SINT (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand float(f32) to SINT(i64) conversion.
bool expandFP_TO_UINT (SDNode *N, SDValue &Result, SDValue &Chain, SelectionDAG &DAG) const
Expand float to UINT conversion.
bool expandUINT_TO_FP (SDNode *N, SDValue &Result, SDValue &Chain, SelectionDAG &DAG) const
Expand UINT(i64) to double(f64) conversion.
SDValue expandFMINNUM_FMAXNUM (SDNode *N, SelectionDAG &DAG) const
Expand fminnum/fmaxnum into fminnum_ieee/fmaxnum_ieee with quieted inputs.
SDValue expandFMINIMUM_FMAXIMUM (SDNode *N, SelectionDAG &DAG) const
Expand fminimum/fmaximum into multiple comparison with selects.
SDValue expandFP_TO_INT_SAT (SDNode *N, SelectionDAG &DAG) const
Expand FP_TO_[US]INT_SAT into FP_TO_[US]INT and selects or min/max.
SDValue expandRoundInexactToOdd (EVT ResultVT, SDValue Op, const SDLoc &DL, SelectionDAG &DAG) const
Truncate Op to ResultVT.
SDValue expandFP_ROUND (SDNode *Node, SelectionDAG &DAG) const
Expand round(fp) to fp conversion.
SDValue expandIS_FPCLASS (EVT ResultVT, SDValue Op, FPClassTest Test, SDNodeFlags Flags, const SDLoc &DL, SelectionDAG &DAG) const
Expand check for floating point class.
SDValue expandCTPOP (SDNode *N, SelectionDAG &DAG) const
Expand CTPOP nodes.
SDValue expandVPCTPOP (SDNode *N, SelectionDAG &DAG) const
Expand VP_CTPOP nodes.
SDValue expandCTLZ (SDNode *N, SelectionDAG &DAG) const
Expand CTLZ/CTLZ_ZERO_UNDEF nodes.
SDValue expandVPCTLZ (SDNode *N, SelectionDAG &DAG) const
Expand VP_CTLZ/VP_CTLZ_ZERO_UNDEF nodes.
SDValue CTTZTableLookup (SDNode *N, SelectionDAG &DAG, const SDLoc &DL, EVT VT, SDValue Op, unsigned NumBitsPerElt) const
Expand CTTZ via Table Lookup.
SDValue expandCTTZ (SDNode *N, SelectionDAG &DAG) const
Expand CTTZ/CTTZ_ZERO_UNDEF nodes.
SDValue expandVPCTTZ (SDNode *N, SelectionDAG &DAG) const
Expand VP_CTTZ/VP_CTTZ_ZERO_UNDEF nodes.
SDValue expandVPCTTZElements (SDNode *N, SelectionDAG &DAG) const
Expand VP_CTTZ_ELTS/VP_CTTZ_ELTS_ZERO_UNDEF nodes.
SDValue expandABS (SDNode *N, SelectionDAG &DAG, bool IsNegative=false) const
Expand ABS nodes.
SDValue expandABD (SDNode *N, SelectionDAG &DAG) const
Expand ABDS/ABDU nodes.
SDValue expandAVG (SDNode *N, SelectionDAG &DAG) const
Expand vector/scalar AVGCEILS/AVGCEILU/AVGFLOORS/AVGFLOORU nodes.
SDValue expandBSWAP (SDNode *N, SelectionDAG &DAG) const
Expand BSWAP nodes.
SDValue expandVPBSWAP (SDNode *N, SelectionDAG &DAG) const
Expand VP_BSWAP nodes.
SDValue expandBITREVERSE (SDNode *N, SelectionDAG &DAG) const
Expand BITREVERSE nodes.
SDValue expandVPBITREVERSE (SDNode *N, SelectionDAG &DAG) const
Expand VP_BITREVERSE nodes.
std::pair< SDValue, SDValue > scalarizeVectorLoad (LoadSDNode *LD, SelectionDAG &DAG) const
Turn load of vector type into a load of the individual elements.
SDValue scalarizeVectorStore (StoreSDNode *ST, SelectionDAG &DAG) const
std::pair< SDValue, SDValue > expandUnalignedLoad (LoadSDNode *LD, SelectionDAG &DAG) const
Expands an unaligned load to 2 half-size loads for an integer, and possibly more for vectors.
SDValue expandUnalignedStore (StoreSDNode *ST, SelectionDAG &DAG) const
Expands an unaligned store to 2 half-size stores for integer values, and possibly more for vectors.
SDValue IncrementMemoryAddress (SDValue Addr, SDValue Mask, const SDLoc &DL, EVT DataVT, SelectionDAG &DAG, bool IsCompressedMemory) const
Increments memory address Addr according to the type of the value DataVT that should be stored.
SDValue getVectorElementPointer (SelectionDAG &DAG, SDValue VecPtr, EVT VecVT, SDValue Index) const
Get a pointer to vector element Idx located in memory for a vector of type VecVT starting at a base address of VecPtr.
SDValue getVectorSubVecPointer (SelectionDAG &DAG, SDValue VecPtr, EVT VecVT, EVT SubVecVT, SDValue Index) const
Get a pointer to a sub-vector of type SubVecVT at index Idx located in memory for a vector of type VecVT starting at a base address of VecPtr.
SDValue expandIntMINMAX (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US][MIN|MAX].
SDValue expandAddSubSat (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US][ADD|SUB]SAT.
SDValue expandCMP (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]CMP.
SDValue expandShlSat (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]SHLSAT.
SDValue expandFixedPointMul (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[U|S]MULFIX[SAT].
SDValue expandFixedPointDiv (unsigned Opcode, const SDLoc &dl, SDValue LHS, SDValue RHS, unsigned Scale, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]DIVFIX[SAT].
void expandUADDSUBO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::U(ADD|SUB)O.
void expandSADDSUBO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::S(ADD|SUB)O.
bool expandMULO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]MULO.
void forceExpandWideMUL (SelectionDAG &DAG, const SDLoc &dl, bool Signed, EVT WideVT, const SDValue LL, const SDValue LH, const SDValue RL, const SDValue RH, SDValue &Lo, SDValue &Hi) const
forceExpandWideMUL - Unconditionally expand a MUL into either a libcall or brute force via a wide multiplication.
void forceExpandWideMUL (SelectionDAG &DAG, const SDLoc &dl, bool Signed, const SDValue LHS, const SDValue RHS, SDValue &Lo, SDValue &Hi) const
Same as above, but creates the upper halves of each operand by sign/zero-extending the operands.
SDValue expandVecReduce (SDNode *Node, SelectionDAG &DAG) const
Expand a VECREDUCE_* into an explicit calculation.
SDValue expandVecReduceSeq (SDNode *Node, SelectionDAG &DAG) const
Expand a VECREDUCE_SEQ_* into an explicit ordered calculation.
bool expandREM (SDNode *Node, SDValue &Result, SelectionDAG &DAG) const
Expand an SREM or UREM using SDIV/UDIV or SDIVREM/UDIVREM, if legal.
SDValue expandVectorSplice (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::VECTOR_SPLICE.
SDValue expandVECTOR_COMPRESS (SDNode *Node, SelectionDAG &DAG) const
Expand a vector VECTOR_COMPRESS into a sequence of extract element, store temporarily, advance store position, before re-loading the final vector.
bool LegalizeSetCCCondCode (SelectionDAG &DAG, EVT VT, SDValue &LHS, SDValue &RHS, SDValue &CC, SDValue Mask, SDValue EVL, bool &NeedInvert, const SDLoc &dl, SDValue &Chain, bool IsSignaling=false) const
Legalize a SETCC or VP_SETCC with given LHS and RHS and condition code CC on the current target.
virtual void AdjustInstrPostInstrSelection (MachineInstr &MI, SDNode *Node) const
This method should be implemented by targets that mark instructions with the 'hasPostISelHook' flag.
virtual SDValue emitStackGuardXorFP (SelectionDAG &DAG, SDValue Val, const SDLoc &DL) const
virtual SDValue LowerToTLSEmulatedModel (const GlobalAddressSDNode *GA, SelectionDAG &DAG) const
Lower TLS global address SDNode for target independent emulated TLS model.
virtual SDValue expandIndirectJTBranch (const SDLoc &dl, SDValue Value, SDValue Addr, int JTI, SelectionDAG &DAG) const
Expands target specific indirect branch for the case of JumpTable expansion.
SDValue lowerCmpEqZeroToCtlzSrl (SDValue Op, SelectionDAG &DAG) const
virtual bool isXAndYEqZeroPreferableToXAndYEqY (ISD::CondCode, EVT) const
Public Member Functions inherited from llvm::TargetLoweringBase
virtual void markLibCallAttributes (MachineFunction *MF, unsigned CC, ArgListTy &Args) const
TargetLoweringBase (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
TargetLoweringBase (const TargetLoweringBase &)=delete
TargetLoweringBase & operator= (const TargetLoweringBase &)=delete
virtual ~TargetLoweringBase ()=default
bool isStrictFPEnabled () const
Return true if the target support strict float operation.
const TargetMachine & getTargetMachine () const
virtual MVT getPointerTy (const DataLayout &DL, uint32_t AS=0) const
Return the pointer type for the given address space, defaults to the pointer type from the data layout.
virtual MVT getPointerMemTy (const DataLayout &DL, uint32_t AS=0) const
Return the in-memory pointer type for the given address space, defaults to the pointer type from the data layout.
MVT getFrameIndexTy (const DataLayout &DL) const
Return the type for frame index, which is determined by the alloca address space specified through the data layout.
MVT getProgramPointerTy (const DataLayout &DL) const
Return the type for code pointers, which is determined by the program address space specified through the data layout.
virtual MVT getFenceOperandTy (const DataLayout &DL) const
Return the type for operands of fence.
EVT getShiftAmountTy (EVT LHSTy, const DataLayout &DL) const
Returns the type for the shift amount of a shift opcode.
virtual LLVM_READONLY LLT getPreferredShiftAmountTy (LLT ShiftValueTy) const
Return the preferred type to use for a shift opcode, given the shifted amount type is ShiftValueTy.
virtual MVT getVectorIdxTy (const DataLayout &DL) const
Returns the type to be used for the index operand of: ISD::INSERT_VECTOR_ELT, ISD::EXTRACT_VECTOR_ELT, ISD::INSERT_SUBVECTOR, and ISD::EXTRACT_SUBVECTOR.
virtual MVT getVPExplicitVectorLengthTy () const
Returns the type to be used for the EVL/AVL operand of VP nodes: ISD::VP_ADD, ISD::VP_SUB, etc.
virtual MachineMemOperand::Flags getTargetMMOFlags (const Instruction &I) const
This callback is used to inspect load/store instructions and add target-specific MachineMemOperand flags to them.
virtual MachineMemOperand::Flags getTargetMMOFlags (const MemSDNode &Node) const
This callback is used to inspect load/store SDNode.
MachineMemOperand::Flags getLoadMemOperandFlags (const LoadInst &LI, const DataLayout &DL, AssumptionCache *AC=nullptr, const TargetLibraryInfo *LibInfo=nullptr) const
MachineMemOperand::Flags getStoreMemOperandFlags (const StoreInst &SI, const DataLayout &DL) const
MachineMemOperand::Flags getAtomicMemOperandFlags (const Instruction &AI, const DataLayout &DL) const
virtual bool shouldExpandGetActiveLaneMask (EVT VT, EVT OpVT) const
Return true if the @llvm.get.active.lane.mask intrinsic should be expanded using generic code in SelectionDAGBuilder.
virtual bool shouldExpandGetVectorLength (EVT CountVT, unsigned VF, bool IsScalable) const
virtual bool shouldExpandCttzElements (EVT VT) const
Return true if the @llvm.experimental.cttz.elts intrinsic should be expanded using generic code in SelectionDAGBuilder.
unsigned getBitWidthForCttzElements (Type *RetTy, ElementCount EC, bool ZeroIsPoison, const ConstantRange *VScaleRange) const
Return the minimum number of bits required to hold the maximum possible number of trailing zero vector elements.
virtual bool shouldReassociateReduction (unsigned RedOpc, EVT VT) const
virtual bool reduceSelectOfFPConstantLoads (EVT CmpOpVT) const
Return true if it is profitable to convert a select of FP constants into a constant pool load whose address depends on the select condition.
bool hasMultipleConditionRegisters () const
Return true if multiple condition registers are available.
bool hasExtractBitsInsn () const
Return true if the target has BitExtract instructions.
virtual bool softPromoteHalfType () const
virtual bool useFPRegsForHalfType () const
virtual bool isIntDivCheap (EVT VT, AttributeList Attr) const
Return true if integer divide is usually cheaper than a sequence of several shifts, adds, and multiplies for this target.
virtual bool hasStandaloneRem (EVT VT) const
Return true if the target can handle a standalone remainder operation.
virtual bool isFsqrtCheap (SDValue X, SelectionDAG &DAG) const
Return true if SQRT(X) shouldn't be replaced with X*RSQRT(X).
int getRecipEstimateSqrtEnabled (EVT VT, MachineFunction &MF) const
Return a ReciprocalEstimate enum value for a square root of the given type based on the function's attributes.
int getRecipEstimateDivEnabled (EVT VT, MachineFunction &MF) const
Return a ReciprocalEstimate enum value for a division of the given type based on the function's attributes.
int getSqrtRefinementSteps (EVT VT, MachineFunction &MF) const
Return the refinement step count for a square root of the given type based on the function's attributes.
int getDivRefinementSteps (EVT VT, MachineFunction &MF) const
Return the refinement step count for a division of the given type based on the function's attributes.
bool isSlowDivBypassed () const
Returns true if target has indicated at least one type should be bypassed.
const DenseMap< unsigned int, unsigned int > & getBypassSlowDivWidths () const
Returns map of slow types for division or remainder with corresponding fast types.
virtual bool isVScaleKnownToBeAPowerOfTwo () const
Return true only if vscale must be a power of two.
bool isJumpExpensive () const
Return true if Flow Control is an expensive operation that should be avoided.
virtual CondMergingParams getJumpConditionMergingParams (Instruction::BinaryOps, const Value *, const Value *) const
bool isPredictableSelectExpensive () const
Return true if selects are only cheaper than branches if the branch is unlikely to be predicted right.
virtual bool fallBackToDAGISel (const Instruction &Inst) const
virtual bool isLoadBitCastBeneficial (EVT LoadVT, EVT BitcastVT, const SelectionDAG &DAG, const MachineMemOperand &MMO) const
Return true if the following transform is beneficial: fold (conv (load x)) -> (load (conv*)x) On architectures that don't natively support some vector loads efficiently, casting the load to a smaller vector of larger types and loading is more efficient, however, this can be undone by optimizations in dag combiner.
virtual bool isStoreBitCastBeneficial (EVT StoreVT, EVT BitcastVT, const SelectionDAG &DAG, const MachineMemOperand &MMO) const
Return true if the following transform is beneficial: (store (y (conv x)), y*)) -> (store x, (x*))
virtual bool storeOfVectorConstantIsCheap (bool IsZero, EVT MemVT, unsigned NumElem, unsigned AddrSpace) const
Return true if it is expected to be cheaper to do a store of vector constant with the given size and type for the address space than to store the individual scalar element constants.
virtual bool mergeStoresAfterLegalization (EVT MemVT) const
Allow store merging for the specified type after legalization in addition to before legalization.
virtual bool canMergeStoresTo (unsigned AS, EVT MemVT, const MachineFunction &MF) const
Returns if it's reasonable to merge stores to MemVT size.
virtual bool isCtpopFast (EVT VT) const
Return true if ctpop instruction is fast.
virtual unsigned getCustomCtpopCost (EVT VT, ISD::CondCode Cond) const
Return the maximum number of "x & (x - 1)" operations that can be done instead of deferring to a custom CTPOP.
virtual bool preferZeroCompareBranch () const
Return true if the heuristic to prefer icmp eq zero should be used in code gen prepare.
virtual bool isMultiStoresCheaperThanBitsMerge (EVT LTy, EVT HTy) const
Return true if it is cheaper to split the store of a merged int val from a pair of smaller values into multiple stores.
virtual bool areTwoSDNodeTargetMMOFlagsMergeable (const MemSDNode &NodeX, const MemSDNode &NodeY) const
Return true if it is valid to merge the TargetMMOFlags in two SDNodes.
virtual MVT hasFastEqualityCompare (unsigned NumBits) const
Return the preferred operand type if the target has a quick way to compare integer values of the given size.
virtual bool hasAndNot (SDValue X) const
Return true if the target has a bitwise and-not operation: X = ~A & B This can be used to simplify select or other instructions.
virtual bool hasBitTest (SDValue X, SDValue Y) const
Return true if the target has a bit-test instruction: (X & (1 << Y)) ==/!= 0 This knowledge can be used to prevent breaking the pattern, or creating it if it could be recognized.
virtual bool shouldFoldMaskToVariableShiftPair (SDValue X) const
There are two ways to clear extreme bits (either low or high): Mask: x & (-1 << y) (the instcombine canonical form) Shifts: x >> y << y Return true if the variant with 2 variable shifts is preferred.
virtual bool shouldFoldConstantShiftPairToMask (const SDNode *N, CombineLevel Level) const
Return true if it is profitable to fold a pair of shifts into a mask.
virtual bool shouldTransformSignedTruncationCheck (EVT XVT, unsigned KeptBits) const
Should we tranform the IR-optimal check for whether given truncation down into KeptBits would be truncating or not: (add x, (1 << (KeptBits-1))) srccond (1 << KeptBits) Into it's more traditional form: ((x << C) a>> C) dstcond x Return true if we should transform.
virtual bool shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd (SDValue X, ConstantSDNode *XC, ConstantSDNode *CC, SDValue Y, unsigned OldShiftOpcode, unsigned NewShiftOpcode, SelectionDAG &DAG) const
Given the pattern (X & (C l>>/<< Y)) ==/!= 0 return true if it should be transformed into: ((X <</l>> Y) & C) ==/!= 0 WARNING: if 'X' is a constant, the fold may deadlock! FIXME: we could avoid passing XC, but we can't use isConstOrConstSplat() here because it can end up being not linked in.
virtual bool optimizeFMulOrFDivAsShiftAddBitcast (SDNode *N, SDValue FPConst, SDValue IntPow2) const
virtual unsigned preferedOpcodeForCmpEqPiecesOfOperand (EVT VT, unsigned ShiftOpc, bool MayTransformRotate, const APInt &ShiftOrRotateAmt, const std::optional< APInt > &AndMask) const
virtual bool preferABDSToABSWithNSW (EVT VT) const
virtual bool preferScalarizeSplat (SDNode *N) const
virtual bool preferSextInRegOfTruncate (EVT TruncVT, EVT VT, EVT ExtVT) const
bool enableExtLdPromotion () const
Return true if the target wants to use the optimization that turns ext(promotableInst1(...(promotableInstN(load)))) into promotedInst1(...(promotedInstN(ext(load)))).
virtual bool canCombineStoreAndExtract (Type *VectorTy, Value *Idx, unsigned &Cost) const
Return true if the target can combine store(extractelement VectorTy, Idx).
virtual bool shouldSplatInsEltVarIndex (EVT) const
Return true if inserting a scalar into a variable element of an undef vector is more efficiently handled by splatting the scalar instead.
virtual bool enableAggressiveFMAFusion (LLT Ty) const
Return true if target always benefits from combining into FMA for a given value type.
virtual MVT::SimpleValueType getCmpLibcallReturnType () const
Return the ValueType for comparison libcalls.
BooleanContent getBooleanContents (bool isVec, bool isFloat) const
For targets without i1 registers, this gives the nature of the high-bits of boolean values held in types wider than i1.
BooleanContent getBooleanContents (EVT Type) const
SDValue promoteTargetBoolean (SelectionDAG &DAG, SDValue Bool, EVT ValVT) const
Promote the given target boolean to a target boolean of the given type.
Sched::Preference getSchedulingPreference () const
Return target scheduling preference.
virtual const TargetRegisterClass * getRegClassFor (MVT VT, bool isDivergent=false) const
Return the register class that should be used for the specified value type.
virtual bool requiresUniformRegister (MachineFunction &MF, const Value *) const
Allows target to decide about the register class of the specific value that is live outside the defining block.
virtual const TargetRegisterClass * getRepRegClassFor (MVT VT) const
Return the 'representative' register class for the specified value type.
virtual uint8_t getRepRegClassCostFor (MVT VT) const
Return the cost of the 'representative' register class for the specified value type.
virtual ShiftLegalizationStrategy preferredShiftLegalizationStrategy (SelectionDAG &DAG, SDNode *N, unsigned ExpansionFactor) const
bool isTypeLegal (EVT VT) const
Return true if the target has native support for the specified value type.
const ValueTypeActionImpl & getValueTypeActions () const
LegalizeKind getTypeConversion (LLVMContext &Context, EVT VT) const
Return pair that represents the legalization kind (first) that needs to happen to EVT (second) in order to type-legalize it.
LegalizeTypeAction getTypeAction (LLVMContext &Context, EVT VT) const
Return how we should legalize values of this type, either it is already legal (return 'Legal') or we need to promote it to a larger type (return 'Promote'), or we need to expand it into multiple registers of smaller integer type (return 'Expand').
LegalizeTypeAction getTypeAction (MVT VT) const
virtual EVT getTypeToTransformTo (LLVMContext &Context, EVT VT) const
For types supported by the target, this is an identity function.
EVT getTypeToExpandTo (LLVMContext &Context, EVT VT) const
For types supported by the target, this is an identity function.
unsigned getVectorTypeBreakdown (LLVMContext &Context, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
Vector types are broken down into some number of legal first class types.
virtual unsigned getVectorTypeBreakdownForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
Certain targets such as MIPS require that some types such as vectors are always broken down into scalars in some contexts.
virtual bool isShuffleMaskLegal (ArrayRef< int >, EVT) const
Targets can use this to indicate that they only support some VECTOR_SHUFFLE operations, those with specific masks.
virtual bool canOpTrap (unsigned Op, EVT VT) const
Returns true if the operation can trap for the value type.
virtual bool isVectorClearMaskLegal (ArrayRef< int >, EVT) const
Similar to isShuffleMaskLegal.
virtual LegalizeAction getCustomOperationAction (SDNode &Op) const
How to legalize this custom operation?
LegalizeAction getOperationAction (unsigned Op, EVT VT) const
Return how this operation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
virtual bool isSupportedFixedPointOperation (unsigned Op, EVT VT, unsigned Scale) const
Custom method defined by each target to indicate if an operation which may require a scale is supported natively by the target.
LegalizeAction getFixedPointOperationAction (unsigned Op, EVT VT, unsigned Scale) const
Some fixed point operations may be natively supported by the target but only for specific scales.
LegalizeAction getStrictFPOperationAction (unsigned Op, EVT VT) const
bool isOperationLegalOrCustom (unsigned Op, EVT VT, bool LegalOnly=false) const
Return true if the specified operation is legal on this target or can be made legal with custom lowering.
bool isOperationLegalOrPromote (unsigned Op, EVT VT, bool LegalOnly=false) const
Return true if the specified operation is legal on this target or can be made legal using promotion.
bool isOperationLegalOrCustomOrPromote (unsigned Op, EVT VT, bool LegalOnly=false) const
Return true if the specified operation is legal on this target or can be made legal with custom lowering or using promotion.
bool isOperationCustom (unsigned Op, EVT VT) const
Return true if the operation uses custom lowering, regardless of whether the type is legal or not.
virtual bool areJTsAllowed (const Function *Fn) const
Return true if lowering to a jump table is allowed.
bool rangeFitsInWord (const APInt &Low, const APInt &High, const DataLayout &DL) const
Check whether the range [Low,High] fits in a machine word.
virtual bool isSuitableForJumpTable (const SwitchInst *SI, uint64_t NumCases, uint64_t Range, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const
Return true if lowering to a jump table is suitable for a set of case clusters which may contain NumCases cases, Range range of values.
virtual MVT getPreferredSwitchConditionType (LLVMContext &Context, EVT ConditionVT) const
Returns preferred type for switch condition.
bool isSuitableForBitTests (unsigned NumDests, unsigned NumCmps, const APInt &Low, const APInt &High, const DataLayout &DL) const
Return true if lowering to a bit test is suitable for a set of case clusters which contains NumDests unique destinations, Low and High as its lowest and highest case values, and expects NumCmps case value comparisons.
bool isOperationExpand (unsigned Op, EVT VT) const
Return true if the specified operation is illegal on this target or unlikely to be made legal with custom lowering.
bool isOperationLegal (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target.
LegalizeAction getLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return how this load with extension should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal on this target.
bool isLoadExtLegalOrCustom (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal or custom on this target.
LegalizeAction getAtomicLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const
Same as getLoadExtAction, but for atomic loads.
bool isAtomicLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified atomic load with extension is legal on this target.
LegalizeAction getTruncStoreAction (EVT ValVT, EVT MemVT) const
Return how this store with truncation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isTruncStoreLegal (EVT ValVT, EVT MemVT) const
Return true if the specified store with truncation is legal on this target.
bool isTruncStoreLegalOrCustom (EVT ValVT, EVT MemVT) const
Return true if the specified store with truncation has solution on this target.
virtual bool canCombineTruncStore (EVT ValVT, EVT MemVT, bool LegalOnly) const
LegalizeAction getIndexedLoadAction (unsigned IdxMode, MVT VT) const
Return how the indexed load should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedStoreAction (unsigned IdxMode, MVT VT) const
Return how the indexed store should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedMaskedLoadAction (unsigned IdxMode, MVT VT) const
Return how the indexed load should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedMaskedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedMaskedStoreAction (unsigned IdxMode, MVT VT) const
Return how the indexed store should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedMaskedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
virtual bool shouldExtendGSIndex (EVT VT, EVT &EltTy) const
Returns true if the index type for a masked gather/scatter requires extending.
virtual bool shouldRemoveExtendFromGSIndex (SDValue Extend, EVT DataVT) const
virtual bool isLegalScaleForGatherScatter (uint64_t Scale, uint64_t ElemSize) const
LegalizeAction getCondCodeAction (ISD::CondCode CC, MVT VT) const
Return how the condition code should be treated: either it is legal, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isCondCodeLegal (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal on this target.
bool isCondCodeLegalOrCustom (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal or custom on this target.
MVT getTypeToPromoteTo (unsigned Op, MVT VT) const
If the action for this operation is to promote, this method returns the ValueType to promote to.
virtual EVT getAsmOperandValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
EVT getValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
Return the EVT corresponding to this LLVM type.
EVT getMemValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
MVT getSimpleValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
Return the MVT corresponding to this LLVM type. See getValueType.
MVT getRegisterType (MVT VT) const
Return the type of registers that this ValueType will eventually require.
MVT getRegisterType (LLVMContext &Context, EVT VT) const
Return the type of registers that this ValueType will eventually require.
virtual unsigned getNumRegisters (LLVMContext &Context, EVT VT, std::optional< MVT > RegisterVT=std::nullopt) const
Return the number of registers that this ValueType will eventually require.
virtual MVT getRegisterTypeForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT) const
Certain combinations of ABIs, Targets and features require that types are legal for some operations and not for other operations.
virtual unsigned getNumRegistersForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT) const
Certain targets require unusual breakdowns of certain types.
virtual Align getABIAlignmentForCallingConv (Type *ArgTy, const DataLayout &DL) const
Certain targets have context sensitive alignment requirements, where one type has the alignment requirement of another type.
virtual bool ShouldShrinkFPConstant (EVT) const
If true, then instruction selection should seek to shrink the FP constant of the specified type to a smaller type in order to save space and / or reduce runtime.
virtual bool shouldReduceLoadWidth (SDNode *Load, ISD::LoadExtType ExtTy, EVT NewVT) const
Return true if it is profitable to reduce a load to a smaller type.
virtual bool shouldRemoveRedundantExtend (SDValue Op) const
Return true (the default) if it is profitable to remove a sext_inreg(x) where the sext is redundant, and use x directly.
bool isPaddedAtMostSignificantBitsWhenStored (EVT VT) const
Indicates if any padding is guaranteed to go at the most significant bits when storing the type to memory and the type size isn't equal to the store size.
bool hasBigEndianPartOrdering (EVT VT, const DataLayout &DL) const
When splitting a value of the specified type into parts, does the Lo or Hi part come first? This usually follows the endianness, except for ppcf128, where the Hi part always comes first.
bool hasTargetDAGCombine (ISD::NodeType NT) const
If true, the target has custom DAG combine transformations that it can perform for the specified node.
unsigned getGatherAllAliasesMaxDepth () const
virtual unsigned getVaListSizeInBits (const DataLayout &DL) const
Returns the size of the platform's va_list object.
unsigned getMaxStoresPerMemset (bool OptSize) const
Get maximum # of store operations permitted for llvm.memset.
unsigned getMaxStoresPerMemcpy (bool OptSize) const
Get maximum # of store operations permitted for llvm.memcpy.
virtual unsigned getMaxGluedStoresPerMemcpy () const
Get maximum # of store operations to be glued together.
unsigned getMaxExpandSizeMemcmp (bool OptSize) const
Get maximum # of load operations permitted for memcmp.
unsigned getMaxStoresPerMemmove (bool OptSize) const
Get maximum # of store operations permitted for llvm.memmove.
virtual bool allowsMisalignedMemoryAccesses (LLT, unsigned AddrSpace=0, Align Alignment=Align(1), MachineMemOperand::Flags Flags=MachineMemOperand::MONone, unsigned *=nullptr) const
LLT handling variant.
bool allowsMemoryAccessForAlignment (LLVMContext &Context, const DataLayout &DL, EVT VT, unsigned AddrSpace=0, Align Alignment=Align(1), MachineMemOperand::Flags Flags=MachineMemOperand::MONone, unsigned *Fast=nullptr) const
This function returns true if the memory access is aligned or if the target allows this specific unaligned memory access.
bool allowsMemoryAccessForAlignment (LLVMContext &Context, const DataLayout &DL, EVT VT, const MachineMemOperand &MMO, unsigned *Fast=nullptr) const
Return true if the memory access of this type is aligned or if the target allows this specific unaligned access for the given MachineMemOperand.
virtual bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, EVT VT, unsigned AddrSpace=0, Align Alignment=Align(1), MachineMemOperand::Flags Flags=MachineMemOperand::MONone, unsigned *Fast=nullptr) const
Return true if the target supports a memory access of this type for the given address space and alignment.
bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, EVT VT, const MachineMemOperand &MMO, unsigned *Fast=nullptr) const
Return true if the target supports a memory access of this type for the given MachineMemOperand.
bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, LLT Ty, const MachineMemOperand &MMO, unsigned *Fast=nullptr) const
LLT handling variant.
virtual LLT getOptimalMemOpLLT (const MemOp &Op, const AttributeList &) const
LLT returning variant.
virtual bool isSafeMemOpType (MVT) const
Returns true if it's safe to use load / store of the specified type to expand memcpy / memset inline.
virtual unsigned getMinimumJumpTableEntries () const
Return lower limit for number of blocks in a jump table.
unsigned getMinimumJumpTableDensity (bool OptForSize) const
Return lower limit of the density in a jump table.
unsigned getMaximumJumpTableSize () const
Return upper limit for number of entries in a jump table.
Register getStackPointerRegisterToSaveRestore () const
If a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
virtual bool needsFixedCatchObjects () const
Align getMinStackArgumentAlignment () const
Return the minimum stack alignment of an argument.
Align getMinFunctionAlignment () const
Return the minimum function alignment.
Align getPrefFunctionAlignment () const
Return the preferred function alignment.
virtual unsigned getMaxPermittedBytesForAlignment (MachineBasicBlock *MBB) const
Return the maximum amount of bytes allowed to be emitted when padding for alignment.
virtual bool alignLoopsWithOptSize () const
Should loops be aligned even when the function is marked OptSize (but not MinSize).
virtual Value * getIRStackGuard (IRBuilderBase &IRB) const
If the target has a standard location for the stack protector guard, returns the address of that location.
virtual bool useStackGuardXorFP () const
If this function returns true, stack protection checks should XOR the frame pointer (or whichever pointer is used to address locals) into the stack guard value before checking it.
virtual Function * getSSPStackGuardCheck (const Module &M) const
If the target has a standard stack protection check function that performs validation and error handling, returns the function.
virtual Value * getSafeStackPointerLocation (IRBuilderBase &IRB) const
Returns the target-specific address of the unsafe stack pointer.
virtual bool hasStackProbeSymbol (const MachineFunction &MF) const
Returns the name of the symbol used to emit stack probes or the empty string if not applicable.
virtual StringRef getStackProbeSymbolName (const MachineFunction &MF) const
virtual bool isFreeAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast from SrcAS to DestAS is "cheap", such that e.g.
virtual bool shouldAlignPointerArgs (CallInst *, unsigned &, Align &) const
Return true if the pointer arguments to CI should be aligned by aligning the object whose address is being passed.
virtual void emitAtomicCmpXchgNoStoreLLBalance (IRBuilderBase &Builder) const
virtual bool shouldSignExtendTypeInLibCall (EVT Type, bool IsSigned) const
Returns true if arguments should be sign-extended in lib calls.
virtual bool shouldExtendTypeInLibCall (EVT Type) const
Returns true if arguments should be extended in lib calls.
virtual AtomicExpansionKind shouldExpandAtomicLoadInIR (LoadInst *LI) const
Returns how the given (atomic) load should be expanded by the IR-level AtomicExpand pass.
virtual AtomicExpansionKind shouldCastAtomicLoadInIR (LoadInst *LI) const
Returns how the given (atomic) load should be cast by the IR-level AtomicExpand pass.
virtual AtomicExpansionKind shouldExpandAtomicStoreInIR (StoreInst *SI) const
Returns how the given (atomic) store should be expanded by the IR-level AtomicExpand pass into.
virtual AtomicExpansionKind shouldCastAtomicStoreInIR (StoreInst *SI) const
Returns how the given (atomic) store should be cast by the IR-level AtomicExpand pass into.
virtual AtomicExpansionKind shouldCastAtomicRMWIInIR (AtomicRMWInst *RMWI) const
Returns how the given atomic atomicrmw should be cast by the IR-level AtomicExpand pass.
virtual LoadInst * lowerIdempotentRMWIntoFencedLoad (AtomicRMWInst *RMWI) const
On some platforms, an AtomicRMW that never actually modifies the value (such as fetch_add of 0) can be turned into a fence followed by an atomic load.
virtual ISD::NodeType getExtendForAtomicOps () const
Returns how the platform's atomic operations are extended (ZERO_EXTEND, SIGN_EXTEND, or ANY_EXTEND).
virtual ISD::NodeType getExtendForAtomicCmpSwapArg () const
Returns how the platform's atomic compare and swap expects its comparison value to be extended (ZERO_EXTEND, SIGN_EXTEND, or ANY_EXTEND).
virtual bool shouldNormalizeToSelectSequence (LLVMContext &Context, EVT VT) const
Returns true if we should normalize select(N0&N1, X, Y) => select(N0, select(N1, X, Y), Y) and select(N0|N1, X, Y) => select(N0, select(N1, X, Y, Y)) if it is likely that it saves us from materializing N0 and N1 in an integer register.
virtual bool isProfitableToCombineMinNumMaxNum (EVT VT) const
virtual bool isMulAddWithConstProfitable (SDValue AddNode, SDValue ConstNode) const
Return true if it may be profitable to transform (mul (add x, c1), c2) -> (add (mul x, c2), c1*c2).
virtual bool shouldUseStrictFP_TO_INT (EVT FpVT, EVT IntVT, bool IsSigned) const
Return true if it is more correct/profitable to use strict FP_TO_INT conversion operations - canonicalizing the FP source value instead of converting all cases and then selecting based on value.
bool isBeneficialToExpandPowI (int64_t Exponent, bool OptForSize) const
Return true if it is beneficial to expand an @llvm.powi.
virtual bool getAddrModeArguments (IntrinsicInst *, SmallVectorImpl< Value * > &, Type *&) const
CodeGenPrepare sinks address calculations into the same BB as Load/Store instructions reading the address.
virtual bool addressingModeSupportsTLS (const GlobalValue &) const
Returns true if the targets addressing mode can target thread local storage (TLS).
virtual int64_t getPreferredLargeGEPBaseOffset (int64_t MinOffset, int64_t MaxOffset) const
Return the prefered common base offset.
virtual bool isLegalAddScalableImmediate (int64_t) const
Return true if adding the specified scalable immediate is legal, that is the target has add instructions which can add a register with the immediate (multiplied by vscale) without having to materialize the immediate into a register.
virtual bool isLegalStoreImmediate (int64_t Value) const
Return true if the specified immediate is legal for the value input of a store instruction.
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
Return true if it's significantly cheaper to shift a vector by a uniform scalar than by an amount which will vary across each lane.
virtual Type * shouldConvertSplatType (ShuffleVectorInst *SVI) const
Given a shuffle vector SVI representing a vector splat, return a new scalar type of size equal to SVI's scalar type if the new type is more profitable.
virtual bool shouldConvertPhiType (Type *From, Type *To) const
Given a set in interconnected phis of type 'From' that are loaded/stored or bitcast to type 'To', return true if the set should be converted to 'To'.
virtual bool isCommutativeBinOp (unsigned Opcode) const
Returns true if the opcode is a commutative binary operation.
virtual bool isBinOp (unsigned Opcode) const
Return true if the node is a math/logic binary operator.
virtual bool allowTruncateForTailCall (Type *FromTy, Type *ToTy) const
Return true if a truncation from FromTy to ToTy is permitted when deciding whether a call is in tail position.
virtual bool isTruncateFree (LLT FromTy, LLT ToTy, const DataLayout &DL, LLVMContext &Ctx) const
virtual bool isTruncateFree (SDValue Val, EVT VT2) const
Return true if truncating the specific node Val to type VT2 is free.
bool isExtFree (const Instruction *I) const
Return true if the extension represented by I is free.
bool isExtLoad (const LoadInst *Load, const Instruction *Ext, const DataLayout &DL) const
Return true if Load and Ext can form an ExtLoad.
virtual bool isZExtFree (Type *FromTy, Type *ToTy) const
Return true if any actual instruction that defines a value of type FromTy implicitly zero-extends the value to ToTy in the result register.
virtual bool isZExtFree (EVT FromTy, EVT ToTy) const
virtual bool isZExtFree (LLT FromTy, LLT ToTy, const DataLayout &DL, LLVMContext &Ctx) const
virtual bool isSExtCheaperThanZExt (EVT FromTy, EVT ToTy) const
Return true if sign-extension from FromTy to ToTy is cheaper than zero-extension.
virtual bool signExtendConstant (const ConstantInt *C) const
Return true if this constant should be sign extended when promoting to a larger type.
virtual bool shouldSinkOperands (Instruction *I, SmallVectorImpl< Use * > &Ops) const
Return true if sinking I's operands to the same basic block as I is profitable, e.g.
virtual bool optimizeExtendOrTruncateConversion (Instruction *I, Loop *L, const TargetTransformInfo &TTI) const
Try to optimize extending or truncating conversion instructions (like zext, trunc, fptoui, uitofp) for the target.
virtual bool hasPairedLoad (EVT, Align &) const
Return true if the target supplies and combines to a paired load two loaded values of type LoadedType next to each other in memory.
virtual bool hasVectorBlend () const
Return true if the target has a vector blend instruction.
virtual unsigned getMaxSupportedInterleaveFactor () const
Get the maximum supported factor for interleaved memory accesses.
virtual bool lowerInterleavedLoad (LoadInst *LI, ArrayRef< ShuffleVectorInst * > Shuffles, ArrayRef< unsigned > Indices, unsigned Factor) const
Lower an interleaved load to target specific intrinsics.
virtual bool lowerInterleavedStore (StoreInst *SI, ShuffleVectorInst *SVI, unsigned Factor) const
Lower an interleaved store to target specific intrinsics.
virtual bool lowerDeinterleaveIntrinsicToLoad (IntrinsicInst *DI, LoadInst *LI) const
Lower a deinterleave intrinsic to a target specific load intrinsic.
virtual bool lowerInterleaveIntrinsicToStore (IntrinsicInst *II, StoreInst *SI) const
Lower an interleave intrinsic to a target specific store intrinsic.
virtual bool isFPExtFoldable (const MachineInstr &MI, unsigned Opcode, LLT DestTy, LLT SrcTy) const
Return true if an fpext operation input to an Opcode operation is free (for instance, because half-precision floating-point numbers are implicitly extended to float-precision) for an FMA instruction.
virtual bool isFPExtFoldable (const SelectionDAG &DAG, unsigned Opcode, EVT DestVT, EVT SrcVT) const
Return true if an fpext operation input to an Opcode operation is free (for instance, because half-precision floating-point numbers are implicitly extended to float-precision) for an FMA instruction.
virtual bool isVectorLoadExtDesirable (SDValue ExtVal) const
Return true if folding a vector load into ExtVal (a sign, zero, or any extend node) is profitable.
virtual bool isFNegFree (EVT VT) const
Return true if an fneg operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
virtual bool isFAbsFree (EVT VT) const
Return true if an fabs operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
virtual bool isFMAFasterThanFMulAndFAdd (const MachineFunction &MF, LLT) const
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
virtual bool isFMADLegal (const MachineInstr &MI, LLT Ty) const
Returns true if MI can be combined with another instruction to form TargetOpcode::G_FMAD.
virtual bool isFMADLegal (const SelectionDAG &DAG, const SDNode *N) const
Returns true if be combined with to form an ISD::FMAD.
virtual bool generateFMAsInMachineCombiner (EVT VT, CodeGenOptLevel OptLevel) const
virtual bool isNarrowingProfitable (EVT SrcVT, EVT DestVT) const
Return true if it's profitable to narrow operations of type SrcVT to DestVT.
virtual bool shouldFoldSelectWithIdentityConstant (unsigned BinOpcode, EVT VT) const
Return true if pulling a binary operation into a select with an identity constant is profitable.
virtual bool isExtractSubvectorCheap (EVT ResVT, EVT SrcVT, unsigned Index) const
Return true if EXTRACT_SUBVECTOR is cheap for extracting this result type from this source type with this index.
virtual bool shouldScalarizeBinop (SDValue VecOp) const
Try to convert an extract element of a vector binary operation into an extract element followed by a scalar operation.
virtual bool isExtractVecEltCheap (EVT VT, unsigned Index) const
Return true if extraction of a scalar element from the given vector type at the given index is cheap.
virtual bool shouldFormOverflowOp (unsigned Opcode, EVT VT, bool MathUsed) const
Try to convert math with an overflow comparison into the corresponding DAG node operation.
virtual bool aggressivelyPreferBuildVectorSources (EVT VecVT) const
virtual bool shouldConsiderGEPOffsetSplit () const
virtual bool shouldAvoidTransformToShift (EVT VT, unsigned Amount) const
Return true if creating a shift of the type by the given amount is not profitable.
virtual bool shouldFoldSelectWithSingleBitTest (EVT VT, const APInt &AndMask) const
virtual bool shouldConvertFpToSat (unsigned Op, EVT FPVT, EVT VT) const
Should we generate fp_to_si_sat and fp_to_ui_sat from type FPVT to type VT from min(max(fptoi)) saturation patterns.
virtual bool shouldExpandCmpUsingSelects () const
Should we expand [US]CMP nodes using two selects and two compares, or by doing arithmetic on boolean types.
virtual bool isComplexDeinterleavingSupported () const
Does this target support complex deinterleaving.
virtual bool isComplexDeinterleavingOperationSupported (ComplexDeinterleavingOperation Operation, Type *Ty) const
Does this target support complex deinterleaving with the given operation and type.
virtual Value * createComplexDeinterleavingIR (IRBuilderBase &B, ComplexDeinterleavingOperation OperationType, ComplexDeinterleavingRotation Rotation, Value *InputA, Value *InputB, Value *Accumulator=nullptr) const
Create the IR node for the given complex deinterleaving operation.
void setLibcallName (RTLIB::Libcall Call, const char *Name)
Rename the default libcall routine name for the specified libcall.
void setLibcallName (ArrayRef< RTLIB::Libcall > Calls, const char *Name)
const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
void setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC)
Override the default CondCode to be used to test the result of the comparison libcall against zero.
ISD::CondCode getCmpLibcallCC (RTLIB::Libcall Call) const
Get the CondCode that's to be used to test the result of the comparison libcall against zero.
void setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC)
Set the CallingConv that should be used for the specified libcall.
CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
Get the CallingConv that should be used for the specified libcall.
virtual void finalizeLowering (MachineFunction &MF) const
Execute target specific actions to finalize target lowering.
virtual bool shouldLocalize (const MachineInstr &MI, const TargetTransformInfo *TTI) const
Check whether or not MI needs to be moved close to its uses.
int InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
unsigned getMaxAtomicSizeInBitsSupported () const
Returns the maximum atomic operation size (in bits) supported by the backend.
unsigned getMaxDivRemBitWidthSupported () const
Returns the size in bits of the maximum div/rem the backend supports.
unsigned getMaxLargeFPConvertBitWidthSupported () const
Returns the size in bits of the maximum larget fp convert the backend supports.
unsigned getMinCmpXchgSizeInBits () const
Returns the size of the smallest cmpxchg or ll/sc instruction the backend supports.
bool supportsUnalignedAtomics () const
Whether the target supports unaligned atomic operations.
virtual bool shouldInsertTrailingFenceForAtomicStore (const Instruction *I) const
Whether AtomicExpandPass should automatically insert a trailing fence without reducing the ordering for this atomic.
virtual Value * emitLoadLinked (IRBuilderBase &Builder, Type *ValueTy, Value *Addr, AtomicOrdering Ord) const
Perform a load-linked operation on Addr, returning a "Value *" with the corresponding pointee type.
virtual Value * emitStoreConditional (IRBuilderBase &Builder, Value *Val, Value *Addr, AtomicOrdering Ord) const
Perform a store-conditional operation to Addr.
virtual void emitExpandAtomicRMW (AtomicRMWInst *AI) const
Perform a atomicrmw expansion using a target-specific way.
virtual void emitBitTestAtomicRMWIntrinsic (AtomicRMWInst *AI) const
Perform a bit test atomicrmw using a target-specific intrinsic.
virtual void emitCmpArithAtomicRMWIntrinsic (AtomicRMWInst *AI) const
Perform a atomicrmw which the result is only used by comparison, using a target-specific intrinsic.
virtual MachineInstr * EmitKCFICheck (MachineBasicBlock &MBB, MachineBasicBlock::instr_iterator &MBBI, const TargetInstrInfo *TII) const
Additional Inherited Members
Public Types inherited from llvm::TargetLowering
enum ConstraintType {
C_Register , C_RegisterClass , C_Memory , C_Address ,
C_Immediate , C_Other , C_Unknown
}
enum ConstraintWeight {
CW_Invalid = -1 , CW_Okay = 0 , CW_Good = 1 , CW_Better = 2 ,
CW_Best = 3 , CW_SpecificReg = CW_Okay , CW_Register = CW_Good , CW_Memory = CW_Better ,
CW_Constant = CW_Best , CW_Default = CW_Okay
}
using AsmOperandInfoVector = std::vector<AsmOperandInfo>
using ConstraintPair = std::pair<StringRef, TargetLowering::ConstraintType>
using ConstraintGroup = SmallVector<ConstraintPair>
Public Types inherited from llvm::TargetLoweringBase
enum LegalizeAction : uint8_t {
Legal , Promote , Expand , LibCall ,
Custom
}
This enum indicates whether operations are valid for a target, and if not, what action should be used to make them valid.
enum LegalizeTypeAction : uint8_t {
TypeLegal , TypePromoteInteger , TypeExpandInteger , TypeSoftenFloat ,
TypeExpandFloat , TypeScalarizeVector , TypeSplitVector , TypeWidenVector ,
TypePromoteFloat , TypeSoftPromoteHalf , TypeScalarizeScalableVector
}
This enum indicates whether a types are legal for a target, and if not, what action should be used to make them valid.
enum BooleanContent { UndefinedBooleanContent , ZeroOrOneBooleanContent , ZeroOrNegativeOneBooleanContent }
Enum that describes how the target represents true/false values.
enum SelectSupportKind { ScalarValSelect , ScalarCondVectorVal , VectorMaskSelect }
Enum that describes what type of support for selects the target has.
enum class AtomicExpansionKind {
None , CastToInteger , LLSC , LLOnly ,
CmpXChg , MaskedIntrinsic , BitTestIntrinsic , CmpArithIntrinsic ,
Expand , NotAtomic
}
Enum that specifies what an atomic load/AtomicRMWInst is expanded to, if at all.
enum class MulExpansionKind { Always , OnlyLegalOrCustom }
Enum that specifies when a multiplication should be expanded.
enum class NegatibleCost { Cheaper = 0 , Neutral = 1 , Expensive = 2 }
Enum that specifies when a float negation is beneficial.
enum AndOrSETCCFoldKind : uint8_t { None = 0 , AddAnd = 1 , NotAnd = 2 , ABS = 4 }
Enum of different potentially desirable ways to fold (and/or (setcc ...), (setcc ...)).
enum ReciprocalEstimate : int { Unspecified = -1 , Disabled = 0 , Enabled = 1 }
Reciprocal estimate status values used by the functions below.
enum class ShiftLegalizationStrategy { ExpandToParts , ExpandThroughStack , LowerToLibcall }
Return the preferred strategy to legalize tihs SHIFT instruction, with ExpansionFactor being the recursion depth - how many expansion needed.
using LegalizeKind = std::pair<LegalizeTypeAction, EVT>
LegalizeKind holds the legalization kind that needs to happen to EVT in order to type-legalize it.
using ArgListTy = std::vector<ArgListEntry>
Static Public Member Functions inherited from llvm::TargetLoweringBase
static ISD::NodeType getExtendForContent (BooleanContent Content)
Protected Member Functions inherited from llvm::TargetLoweringBase
void initActions ()
Initialize all of the actions to default values.
Value * getDefaultSafeStackPointerLocation (IRBuilderBase &IRB, bool UseTLS) const
void setBooleanContents (BooleanContent Ty)
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
void setBooleanContents (BooleanContent IntTy, BooleanContent FloatTy)
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
void setBooleanVectorContents (BooleanContent Ty)
Specify how the target extends the result of a vector boolean value from a vector of i1 to a wider type.
void setSchedulingPreference (Sched::Preference Pref)
Specify the target scheduling preference.
void setMinimumJumpTableEntries (unsigned Val)
Indicate the minimum number of blocks to generate jump tables.
void setMaximumJumpTableSize (unsigned)
Indicate the maximum number of entries in jump tables.
void setStackPointerRegisterToSaveRestore (Register R)
If set to a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
void setHasMultipleConditionRegisters (bool hasManyRegs=true)
Tells the code generator that the target has multiple (allocatable) condition registers that can be used to store the results of comparisons for use by selects and conditional branches.
void setHasExtractBitsInsn (bool hasExtractInsn=true)
Tells the code generator that the target has BitExtract instructions.
void setJumpIsExpensive (bool isExpensive=true)
Tells the code generator not to expand logic operations on comparison predicates into separate sequences that increase the amount of flow control.
void addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth)
Tells the code generator which bitwidths to bypass.
void addRegisterClass (MVT VT, const TargetRegisterClass *RC)
Add the specified register class as an available regclass for the specified value type.
virtual std::pair< const TargetRegisterClass *, uint8_t > findRepresentativeClass (const TargetRegisterInfo *TRI, MVT VT) const
Return the largest legal super-reg register class of the register class for the specified type and its associated "cost".
void computeRegisterProperties (const TargetRegisterInfo *TRI)
Once all of the register classes are added, this allows us to compute derived properties we expose.
void setOperationAction (unsigned Op, MVT VT, LegalizeAction Action)
Indicate that the specified operation does not work with the specified type and indicate what to do about it.
void setOperationAction (ArrayRef< unsigned > Ops, MVT VT, LegalizeAction Action)
void setOperationAction (ArrayRef< unsigned > Ops, ArrayRef< MVT > VTs, LegalizeAction Action)
void setLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action)
Indicate that the specified load with extension does not work with the specified type and indicate what to do about it.
void setLoadExtAction (ArrayRef< unsigned > ExtTypes, MVT ValVT, MVT MemVT, LegalizeAction Action)
void setLoadExtAction (ArrayRef< unsigned > ExtTypes, MVT ValVT, ArrayRef< MVT > MemVTs, LegalizeAction Action)
void setAtomicLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action)
Let target indicate that an extending atomic load of the specified type is legal.
void setAtomicLoadExtAction (ArrayRef< unsigned > ExtTypes, MVT ValVT, MVT MemVT, LegalizeAction Action)
void setAtomicLoadExtAction (ArrayRef< unsigned > ExtTypes, MVT ValVT, ArrayRef< MVT > MemVTs, LegalizeAction Action)
void setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action)
Indicate that the specified truncating store does not work with the specified type and indicate what to do about it.
void setIndexedLoadAction (ArrayRef< unsigned > IdxModes, MVT VT, LegalizeAction Action)
Indicate that the specified indexed load does or does not work with the specified type and indicate what to do abort it.
void setIndexedLoadAction (ArrayRef< unsigned > IdxModes, ArrayRef< MVT > VTs, LegalizeAction Action)
void setIndexedStoreAction (ArrayRef< unsigned > IdxModes, MVT VT, LegalizeAction Action)
Indicate that the specified indexed store does or does not work with the specified type and indicate what to do about it.
void setIndexedStoreAction (ArrayRef< unsigned > IdxModes, ArrayRef< MVT > VTs, LegalizeAction Action)
void setIndexedMaskedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed masked load does or does not work with the specified type and indicate what to do about it.
void setIndexedMaskedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed masked store does or does not work with the specified type and indicate what to do about it.
void setCondCodeAction (ArrayRef< ISD::CondCode > CCs, MVT VT, LegalizeAction Action)
Indicate that the specified condition code is or isn't supported on the target and indicate what to do about it.
void setCondCodeAction (ArrayRef< ISD::CondCode > CCs, ArrayRef< MVT > VTs, LegalizeAction Action)
void AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
If Opc/OrigVT is specified as being promoted, the promotion code defaults to trying a larger integer/fp until it can find one that works.
void setOperationPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
Convenience method to set an operation to Promote and specify the type in a single call.
void setOperationPromotedToType (ArrayRef< unsigned > Ops, MVT OrigVT, MVT DestVT)
void setTargetDAGCombine (ArrayRef< ISD::NodeType > NTs)
Targets should invoke this method for each target independent node that they want to provide a custom DAG combiner for by implementing the PerformDAGCombine virtual method.
void setMinFunctionAlignment (Align Alignment)
Set the target's minimum function alignment.
void setPrefFunctionAlignment (Align Alignment)
Set the target's preferred function alignment.
void setPrefLoopAlignment (Align Alignment)
Set the target's preferred loop alignment.
void setMaxBytesForAlignment (unsigned MaxBytes)
void setMinStackArgumentAlignment (Align Alignment)
Set the minimum stack alignment of an argument.
void setMaxAtomicSizeInBitsSupported (unsigned SizeInBits)
Set the maximum atomic operation size supported by the backend.
void setMaxDivRemBitWidthSupported (unsigned SizeInBits)
Set the size in bits of the maximum div/rem the backend supports.
void setMaxLargeFPConvertBitWidthSupported (unsigned SizeInBits)
Set the size in bits of the maximum fp convert the backend supports.
void setMinCmpXchgSizeInBits (unsigned SizeInBits)
Sets the minimum cmpxchg or ll/sc size supported by the backend.
void setSupportsUnalignedAtomics (bool UnalignedSupported)
Sets whether unaligned atomic operations are supported.
virtual bool isExtFreeImpl (const Instruction *I) const
Return true if the extension represented by I is free.
bool isLegalRC (const TargetRegisterInfo &TRI, const TargetRegisterClass &RC) const
Return true if the value types that can be represented by the specified register class are all legal.
MachineBasicBlock * emitPatchPoint (MachineInstr &MI, MachineBasicBlock *MBB) const
Replace/modify any TargetFrameIndex operands with a targte-dependent sequence of memory operands that is recognized by PrologEpilogInserter.
Protected Attributes inherited from llvm::TargetLoweringBase
unsigned GatherAllAliasesMaxDepth
Depth that GatherAllAliases should continue looking for chain dependencies when trying to find a more preferable chain.
unsigned MaxStoresPerMemset
Specify maximum number of store instructions per memset call.
unsigned MaxStoresPerMemsetOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxStoresPerMemcpy
Specify maximum number of store instructions per memcpy call.
unsigned MaxStoresPerMemcpyOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxGluedStoresPerMemcpy = 0
Specify max number of store instructions to glue in inlined memcpy.
unsigned MaxLoadsPerMemcmp
Specify maximum number of load instructions per memcmp call.
unsigned MaxLoadsPerMemcmpOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxStoresPerMemmove
Specify maximum number of store instructions per memmove call.
unsigned MaxStoresPerMemmoveOptSize
Likewise for functions with the OptSize attribute.
bool PredictableSelectIsExpensive
Tells the code generator that select is more expensive than a branch if the branch is usually predicted right.
bool EnableExtLdPromotion
bool IsStrictFPEnabled
Detailed Description
Definition at line 746 of file PPCISelLowering.h.
Constructor & Destructor Documentation
PPCTargetLowering()
PPCTargetLowering::PPCTargetLowering (const PPCTargetMachine & TM, const PPCSubtarget & STI) explicit
Definition at line 170 of file PPCISelLowering.cpp.
References llvm::ISD::ABDS, llvm::ISD::ABDU, llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::TargetLoweringBase::AddPromotedToType(), llvm::TargetLoweringBase::addRegisterClass(), llvm::Aggressive, Align, llvm::ISD::AND, ANDIGlueBug, llvm::ISD::ANY_EXTEND, llvm::ISD::BITREVERSE, llvm::ISD::BlockAddress, llvm::ISD::BSWAP, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, llvm::TargetLoweringBase::computeRegisterProperties(), llvm::ISD::ConstantPool, llvm::ISD::CTLZ, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::TargetLoweringBase::Custom, llvm::PPC::DIR_970, llvm::PPC::DIR_A2, llvm::PPC::DIR_E500, llvm::PPC::DIR_E500mc, llvm::PPC::DIR_E5500, llvm::PPC::DIR_PWR10, llvm::PPC::DIR_PWR11, llvm::PPC::DIR_PWR4, llvm::PPC::DIR_PWR5, llvm::PPC::DIR_PWR5X, llvm::PPC::DIR_PWR6, llvm::PPC::DIR_PWR6X, llvm::PPC::DIR_PWR7, llvm::PPC::DIR_PWR8, llvm::PPC::DIR_PWR9, llvm::PPC::DIR_PWR_FUTURE, llvm::ISD::EH_DWARF_CFA, llvm::ISD::EH_SJLJ_LONGJMP, llvm::ISD::EH_SJLJ_SETJMP, llvm::PPCSubtarget::enableMachineScheduler(), llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FDIV, llvm::MVT::fixedlen_vector_valuetypes(), llvm::ISD::FMA, llvm::ISD::FMUL, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::MVT::fp_valuetypes(), llvm::ISD::FREM, llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::ISD::FSUB, llvm::TargetLoweringBase::GatherAllAliasesMaxDepth, llvm::ISD::GET_ROUNDING, llvm::PPCSubtarget::getCPUDirective(), llvm::PPCSubtarget::getRegisterInfo(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::PPCSubtarget::hasPOPCNTD(), hasSPE(), llvm::Sched::Hybrid, llvm::ISD::INSERT_VECTOR_ELT, llvm::MVT::integer_valuetypes(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::PPCSubtarget::is32BitELFABI(), llvm::PPCSubtarget::is64BitELFABI(), llvm::ISD::IS_FPCLASS, llvm::PPCSubtarget::isAIXABI(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isPredictableSelectIsExpensive(), llvm::TargetLoweringBase::IsStrictFPEnabled, llvm::ISD::JumpTable, llvm::IRSimilarity::Legal, llvm::TargetLoweringBase::LibCall, llvm::TargetLoweringBase::MaxLoadsPerMemcmp, llvm::TargetLoweringBase::MaxLoadsPerMemcmpOptSize, llvm::TargetLoweringBase::MaxStoresPerMemcpy, llvm::TargetLoweringBase::MaxStoresPerMemcpyOptSize, llvm::TargetLoweringBase::MaxStoresPerMemmove, llvm::TargetLoweringBase::MaxStoresPerMemmoveOptSize, llvm::TargetLoweringBase::MaxStoresPerMemset, llvm::TargetLoweringBase::MaxStoresPerMemsetOptSize, llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, llvm::ISD::OR, llvm::PPCSubtarget::POPCNTD_Fast, PPCGatherAllAliasesMaxDepth, PPCMinimumJumpTableEntries, llvm::ISD::PRE_INC, llvm::TargetLoweringBase::PredictableSelectIsExpensive, llvm::TargetLoweringBase::Promote, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDSAT, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::TargetLoweringBase::setBooleanContents(), llvm::TargetLoweringBase::setBooleanVectorContents(), llvm::ISD::SETCC, llvm::TargetLoweringBase::setCondCodeAction(), llvm::TargetLoweringBase::setHasMultipleConditionRegisters(), llvm::TargetLoweringBase::setIndexedLoadAction(), llvm::TargetLoweringBase::setIndexedStoreAction(), llvm::TargetLoweringBase::setJumpIsExpensive(), llvm::TargetLoweringBase::setLibcallName(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::TargetLoweringBase::setMaxAtomicSizeInBitsSupported(), llvm::TargetLoweringBase::setMinFunctionAlignment(), llvm::TargetLoweringBase::setMinimumJumpTableEntries(), llvm::TargetLoweringBase::setMinStackArgumentAlignment(), llvm::ISD::SETO, llvm::ISD::SETOGE, llvm::ISD::SETOLE, llvm::ISD::SETONE, llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setPrefFunctionAlignment(), llvm::TargetLoweringBase::setPrefLoopAlignment(), llvm::TargetLoweringBase::setSchedulingPreference(), llvm::TargetLoweringBase::setStackPointerRegisterToSaveRestore(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::ISD::SETUEQ, llvm::ISD::SETUGT, llvm::ISD::SETULT, llvm::ISD::SETUO, llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::ISD::SHL_PARTS, shouldInlineQuadwordAtomics(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SMUL_LOHI, llvm::Sched::Source, llvm::ISD::SRA, llvm::ISD::SRA_PARTS, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SRL_PARTS, llvm::ISD::SSUBSAT, llvm::ISD::STRICT_FADD, llvm::ISD::STRICT_FCEIL, llvm::ISD::STRICT_FDIV, llvm::ISD::STRICT_FFLOOR, llvm::ISD::STRICT_FMA, llvm::ISD::STRICT_FMAXNUM, llvm::ISD::STRICT_FMINNUM, llvm::ISD::STRICT_FMUL, llvm::ISD::STRICT_FNEARBYINT, llvm::ISD::STRICT_FP_EXTEND, llvm::ISD::STRICT_FP_ROUND, llvm::ISD::STRICT_FP_TO_SINT, llvm::ISD::STRICT_FP_TO_UINT, llvm::ISD::STRICT_FRINT, llvm::ISD::STRICT_FROUND, llvm::ISD::STRICT_FSETCC, llvm::ISD::STRICT_FSETCCS, llvm::ISD::STRICT_FSQRT, llvm::ISD::STRICT_FSUB, llvm::ISD::STRICT_FTRUNC, llvm::ISD::STRICT_SINT_TO_FP, llvm::ISD::STRICT_UINT_TO_FP, llvm::ISD::SUB, llvm::ISD::SUBC, llvm::ISD::SUBE, TM, llvm::ISD::TRUNCATE, llvm::ISD::UADDSAT, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UMUL_LOHI, llvm::ISD::UREM, useSoftFloat(), llvm::ISD::USUBSAT, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, llvm::TargetLoweringBase::ZeroOrOneBooleanContent, and llvm::ISD::ZEXTLOAD.
Member Function Documentation
allowsMisalignedMemoryAccesses()
bool PPCTargetLowering::allowsMisalignedMemoryAccesses (EVT VT, unsigned AddrSpace, Align Alignment = Align(1), MachineMemOperand::Flags Flags = MachineMemOperand::MONone, unsigned * Fast = nullptr) const override virtual
Is unaligned memory access allowed for the given type, and is it fast relative to software emulation.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17440 of file PPCISelLowering.cpp.
References DisablePPCUnaligned, llvm::CallingConv::Fast, llvm::EVT::getSimpleVT(), llvm::EVT::isFloatingPoint(), llvm::EVT::isSimple(), llvm::EVT::isVector(), and llvm::MVT::isVector().
Referenced by llvm::PPCTTIImpl::getMemoryOpCost().
BuildSDIVPow2()
SDValue PPCTargetLowering::BuildSDIVPow2 (SDNode * N, const APInt & Divisor, SelectionDAG & DAG, SmallVectorImpl< SDNode * > & Created) const override virtual
Targets may override this function to provide custom SDIV lowering for power-of-2 denominators.
If the target returns an empty SDValue, LLVM assumes SDIV is expensive and replaces it with a series of other integer operations.
Reimplemented from llvm::TargetLowering.
Definition at line 16572 of file PPCISelLowering.cpp.
References llvm::countr_zero(), DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::APInt::isNegatedPowerOf2(), llvm::APInt::isPowerOf2(), llvm::PPCSubtarget::isPPC64(), N, llvm::SmallVectorTemplateBase< T, bool >::push_back(), SDValue(), llvm::PPCISD::SRA_ADDZE, and llvm::ISD::SUB.
ccAssignFnForCall()
CCAssignFn * PPCTargetLowering::ccAssignFnForCall (CallingConv::ID CC, bool Return, bool IsVarArg) const
Definition at line 18751 of file PPCISelLowering.cpp.
References CC, llvm::CC_PPC64_ELF(), llvm::CallingConv::Cold, and llvm::RetCC_PPC_Cold().
CollectTargetIntrinsicOperands()
void PPCTargetLowering::CollectTargetIntrinsicOperands (const CallInst & I, SmallVectorImpl< SDValue > & Ops, SelectionDAG & DAG) const override virtual
Reimplemented from llvm::TargetLowering.
Definition at line 17010 of file PPCISelLowering.cpp.
References llvm::SelectionDAG::getMDNode(), getNode(), I, llvm::isa(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
computeKnownBitsForTargetNode()
void PPCTargetLowering::computeKnownBitsForTargetNode (const SDValue Op, KnownBits & Known, const APInt & DemandedElts, const SelectionDAG & DAG, unsigned Depth = 0) const override virtual
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
Determine which of the bits specified in Mask are known to be either zero or one and return them in the Known.
The DemandedElts argument allows us to only collect the known bits that are shared by the requested vector elements.
Reimplemented from llvm::TargetLowering.
Definition at line 16605 of file PPCISelLowering.cpp.
References llvm::cast(), llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::PPCISD::LBRX, llvm::KnownBits::resetAll(), and llvm::KnownBits::Zero.
convertSelectOfConstantsToMath()
bool llvm::PPCTargetLowering::convertSelectOfConstantsToMath (EVT VT) const inline override virtual
Return true if a select of constants (select Cond, C1, C2) should be transformed into simple math ops with the condition value.
For example: select Cond, C1, C1-1 --> add (zext Cond), C1-1
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1043 of file PPCISelLowering.h.
convertSetCCLogicToBitwiseLogic()
bool llvm::PPCTargetLowering::convertSetCCLogicToBitwiseLogic (EVT VT) const inline override virtual
Use bitwise logic to make pairs of compares more efficient.
For example: and (seteq A, B), (seteq C, D) --> seteq (or (xor A, B), (xor C, D)), 0 This should be true when it takes more than one instruction to lower setcc (cmp+set on x86 scalar), when bitwise ops are faster than logic on condition bits (crand on PowerPC), and/or when reducing cmp+br is a win.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 824 of file PPCISelLowering.h.
References llvm::EVT::isScalarInteger().
createFastISel()
FastISel * PPCTargetLowering::createFastISel (FunctionLoweringInfo & FuncInfo, const TargetLibraryInfo * LibInfo) const override virtual
createFastISel - This method returns a target-specific FastISel object, or null if the target does not support "fast" instruction selection.
Reimplemented from llvm::TargetLowering.
Definition at line 17622 of file PPCISelLowering.cpp.
References llvm::PPC::createFastISel().
decomposeMulByConstant()
bool PPCTargetLowering::decomposeMulByConstant (LLVMContext & Context, EVT VT, SDValue C) const override virtual
Return true if it is profitable to transform an integer multiplication-by-constant into simpler operations like shifts and adds.
This may be true if the target does not directly support the multiplication operation for the specified type or the sequence of simpler ops is faster than the multiply.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17478 of file PPCISelLowering.cpp.
References llvm::CallingConv::C, llvm::countr_zero(), llvm::dyn_cast(), llvm::isInt(), llvm::isPowerOf2_64(), and llvm::EVT::isScalarInteger().
EmitAtomicBinary()
MachineBasicBlock * PPCTargetLowering::EmitAtomicBinary (MachineInstr & MI, MachineBasicBlock * MBB, unsigned AtomicSize, unsigned BinOpcode, unsigned CmpOpcode = 0, unsigned CmpPred = 0) const
Definition at line 12033 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), F, llvm::MachineBasicBlock::getBasicBlock(), llvm::PPCSubtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineBasicBlock::getParent(), llvm::MachineBasicBlock::insert(), llvm_unreachable, MI, llvm::PPC::PRED_NE, llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by EmitInstrWithCustomInserter(), and EmitPartwordAtomicBinary().
emitEHSjLjLongJmp()
MachineBasicBlock * PPCTargetLowering::emitEHSjLjLongJmp (MachineInstr & MI, MachineBasicBlock * MBB) const
Definition at line 12565 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineInstrBuilder::cloneMemRefs(), DL, FP, llvm::MachineFunction::getDataLayout(), llvm::PPCSubtarget::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineFunction::getRegInfo(), llvm::MVT::getStoreSize(), llvm::TargetLowering::isPositionIndependent(), llvm::PPCSubtarget::isSVR4ABI(), MBB, MI, MRI, setUsesTOCBasePtr(), and TII.
Referenced by EmitInstrWithCustomInserter().
emitEHSjLjSetJmp()
llvm::MachineBasicBlock * PPCTargetLowering::emitEHSjLjSetJmp (MachineInstr & MI, MachineBasicBlock * MBB) const
Definition at line 12423 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addRegMask(), llvm::MachineBasicBlock::addSuccessor(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineInstrBuilder::cloneMemRefs(), llvm::MachineFunction::CreateMachineBasicBlock(), DL, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineFunction::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::PPCSubtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::BranchProbability::getOne(), llvm::MachineBasicBlock::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::PPCSubtarget::getRegisterInfo(), llvm::MVT::getStoreSize(), llvm::BranchProbability::getZero(), llvm::Function::hasFnAttribute(), I, llvm::MachineFunction::insert(), llvm::PPCSubtarget::is64BitELFABI(), llvm::PPCSubtarget::isPPC64(), MBB, MI, MRI, setUsesTOCBasePtr(), llvm::MachineBasicBlock::splice(), TII, llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs(), and TRI.
Referenced by EmitInstrWithCustomInserter().
EmitInstrWithCustomInserter()
MachineBasicBlock * PPCTargetLowering::EmitInstrWithCustomInserter (MachineInstr & MI, MachineBasicBlock * MBB) const override virtual
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
These instructions are special in various ways, which require special support to insert. The specified MachineInstr is created but not inserted into any basic blocks, and this method is called to expand it into a sequence of instructions, potentially also creating new basic blocks and control flow. As long as the returned basic block is different (i.e., we created a new one), the custom inserter is free to modify the rest of MBB.
Reimplemented from llvm::TargetLowering.
Definition at line 12896 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineInstrBuilder::addUse(), Align, assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), Cond, llvm::MachineOperand::CreateImm(), llvm::MachineOperand::CreateReg(), llvm::MachineFrameInfo::CreateStackObject(), llvm::RegState::Define, DL, EmitAtomicBinary(), emitEHSjLjLongJmp(), emitEHSjLjSetJmp(), EmitPartwordAtomicBinary(), llvm::TargetLoweringBase::emitPatchPoint(), emitProbedAlloca(), llvm::MachineBasicBlock::end(), F, llvm::MachineBasicBlock::getBasicBlock(), llvm::MachinePointerInfo::getFixedStack(), llvm::PPCSubtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm::Hi, llvm::RegState::ImplicitDefine, llvm::MachineBasicBlock::insert(), llvm::PPCSubtarget::is64BitELFABI(), llvm::PPCSubtarget::isLittleEndian(), llvm::PPCSubtarget::isPPC64(), IsSelect(), IsSelectCC(), llvm::PPCSubtarget::isUsingPCRelativeCalls(), llvm_unreachable, llvm::Lo, MI, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, MRI, llvm::MachineInstr::NoFPExcept, llvm::PPC::PRED_BIT_SET, llvm::PPC::PRED_GT, llvm::PPC::PRED_LT, llvm::PPC::PRED_NE, Ptr, llvm::SmallVectorTemplateBase< T, bool >::push_back(), RA, llvm::MachineBasicBlock::setCallFrameSize(), llvm::MachineInstrBuilder::setMIFlag(), llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
emitLeadingFence()
Instruction * PPCTargetLowering::emitLeadingFence (IRBuilderBase & Builder, Instruction * Inst, AtomicOrdering Ord) const override virtual
Inserts in the IR a target-specific intrinsic specifying a fence.
It is called by AtomicExpandPass before expanding an AtomicRMW/AtomicCmpXchg/AtomicStore/AtomicLoad if shouldInsertFencesForAtomic returns true.
Inst is the original atomic instruction, prior to other expansions that may be performed.
This function should either return a nullptr, or a pointer to an IR-level Instruction*. Even complex fence sequences can be represented by a single Instruction* through an intrinsic to be lowered later.
The default implementation emits an IR fence before any release (or stronger) operation that stores, and after any acquire (or stronger) operation. This is generally a correct implementation, but backends may override if they wish to use alternative schemes (e.g. the PowerPC standard ABI uses a fence before a seq_cst load instead of after a seq_cst store).
Reimplemented from llvm::TargetLoweringBase.
Definition at line 12003 of file PPCISelLowering.cpp.
References callIntrinsic(), llvm::isReleaseOrStronger(), and llvm::SequentiallyConsistent.
Referenced by emitMaskedAtomicCmpXchgIntrinsic().
emitMaskedAtomicCmpXchgIntrinsic()
Value * PPCTargetLowering::emitMaskedAtomicCmpXchgIntrinsic (IRBuilderBase & Builder, AtomicCmpXchgInst * CI, Value * AlignedAddr, Value * CmpVal, Value * NewVal, Value * Mask, AtomicOrdering Ord) const override virtual
Perform a masked cmpxchg using a target-specific intrinsic.
This represents the core LL/SC loop which will be lowered at a late stage by the backend. The target-specific intrinsic returns the loaded value and is not responsible for masking and shifting the result.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 18835 of file PPCISelLowering.cpp.
References assert(), emitLeadingFence(), emitTrailingFence(), llvm::Intrinsic::getDeclaration(), llvm::Type::getInt64Ty(), llvm::Value::getType(), llvm::Hi, llvm::Lo, and shouldInlineQuadwordAtomics().
emitMaskedAtomicRMWIntrinsic()
Value * PPCTargetLowering::emitMaskedAtomicRMWIntrinsic (IRBuilderBase & Builder, AtomicRMWInst * AI, Value * AlignedAddr, Value * Incr, Value * Mask, Value * ShiftAmt, AtomicOrdering Ord) const override virtual
Perform a masked atomicrmw using a target-specific intrinsic.
This represents the core LL/SC loop which will be lowered at a late stage by the backend. The target-specific intrinsic returns the loaded value and is not responsible for masking and shifting the result.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 18813 of file PPCISelLowering.cpp.
References assert(), llvm::Intrinsic::getDeclaration(), llvm::Type::getInt64Ty(), getIntrinsicForAtomicRMWBinOp128(), llvm::AtomicRMWInst::getOperation(), llvm::Value::getType(), llvm::Hi, llvm::Lo, and shouldInlineQuadwordAtomics().
EmitPartwordAtomicBinary()
MachineBasicBlock * PPCTargetLowering::EmitPartwordAtomicBinary (MachineInstr & MI, MachineBasicBlock * MBB, bool is8bit, unsigned Opcode, unsigned CmpOpcode = 0, unsigned CmpPred = 0) const
Definition at line 12208 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), EmitAtomicBinary(), llvm::MachineBasicBlock::end(), F, llvm::MachineBasicBlock::getBasicBlock(), llvm::PPCSubtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineBasicBlock::getParent(), llvm::MachineBasicBlock::insert(), llvm::PPCSubtarget::isLittleEndian(), llvm::PPCSubtarget::isPPC64(), isSignExtended(), llvm::Register::isVirtual(), MI, llvm::PPC::PRED_NE, llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by EmitInstrWithCustomInserter().
emitProbedAlloca()
MachineBasicBlock * PPCTargetLowering::emitProbedAlloca (MachineInstr & MI, MachineBasicBlock * MBB) const
Definition at line 12696 of file PPCISelLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), assert(), llvm::BuildMI(), llvm::MachineFunction::CreateMachineBasicBlock(), DL, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getBasicBlock(), llvm::PPCSubtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), getStackProbeSize(), llvm::MachineFunction::insert(), llvm::isInt(), llvm::PPCSubtarget::isPPC64(), MBB, MI, MRI, llvm::Mul, llvm::PPC::PRED_EQ, llvm::MachineBasicBlock::splice(), TII, and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by EmitInstrWithCustomInserter().
emitTrailingFence()
Instruction * PPCTargetLowering::emitTrailingFence (IRBuilderBase & Builder, Instruction * Inst, AtomicOrdering Ord) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 12013 of file PPCISelLowering.cpp.
References callIntrinsic(), llvm::Intrinsic::getDeclaration(), llvm::Instruction::hasAtomicLoad(), llvm::isa(), and llvm::isAcquireOrStronger().
Referenced by emitMaskedAtomicCmpXchgIntrinsic().
enableAggressiveFMAFusion()
bool PPCTargetLowering::enableAggressiveFMAFusion (EVT VT) const override virtual
Return true if target always benefits from combining into FMA for a given value type.
This must typically return false on targets where FMA takes more cycles to execute than FADD.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1852 of file PPCISelLowering.cpp.
References assert(), and llvm::EVT::isFloatingPoint().
expandVSXLoadForLE()
SDValue PPCTargetLowering::expandVSXLoadForLE (SDNode * N, DAGCombinerInfo & DCI) const
Definition at line 15226 of file PPCISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::sampleprof::Base, llvm::cast(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::MemSDNode::getChain(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::MachineMemOperand::getSize(), llvm::LocationSize::getValue(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::LocationSize::hasValue(), llvm::ISD::INTRINSIC_W_CHAIN, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm_unreachable, llvm::PPCISD::LXVD2X, llvm::ISD::MERGE_VALUES, N, SDValue(), and llvm::PPCISD::XXSWAPD.
Referenced by PerformDAGCombine().
expandVSXStoreForLE()
SDValue PPCTargetLowering::expandVSXStoreForLE (SDNode * N, DAGCombinerInfo & DCI) const
Definition at line 15292 of file PPCISelLowering.cpp.
References llvm::TargetLowering::DAGCombinerInfo::AddToWorklist(), llvm::sampleprof::Base, llvm::cast(), llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::MemSDNode::getChain(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::MachineMemOperand::getSize(), llvm::LocationSize::getValue(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::LocationSize::hasValue(), llvm::ISD::INTRINSIC_VOID, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), llvm_unreachable, N, SDValue(), llvm::PPCISD::STXVD2X, and llvm::PPCISD::XXSWAPD.
Referenced by PerformDAGCombine().
functionArgumentNeedsConsecutiveRegisters()
bool llvm::PPCTargetLowering::functionArgumentNeedsConsecutiveRegisters (Type * Ty, CallingConv::ID CallConv, bool isVarArg, const DataLayout & DL) const inline override virtual
Returns true if an argument of type Ty needs to be passed in a contiguous block of registers in calling convention CallConv.
Reimplemented from llvm::TargetLowering.
Definition at line 1116 of file PPCISelLowering.h.
getByValTypeAlignment()
uint64_t PPCTargetLowering::getByValTypeAlignment (Type * Ty, const DataLayout & DL) const override virtual
getByValTypeAlignment - Return the desired alignment for ByVal aggregate function arguments in the caller parameter area.
This is the actual alignment, not its logarithm.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1628 of file PPCISelLowering.cpp.
References Align, getMaxByValAlign(), llvm::PPCSubtarget::isPPC64(), and llvm::Align::value().
getConstraintType()
PPCTargetLowering::ConstraintType PPCTargetLowering::getConstraintType (StringRef Constraint) const override virtual
getConstraintType - Given a constraint, return the type of constraint it is for this target.
Reimplemented from llvm::TargetLowering.
Definition at line 16712 of file PPCISelLowering.cpp.
References llvm::TargetLowering::C_Memory, llvm::TargetLowering::C_RegisterClass, llvm::TargetLowering::getConstraintType(), and llvm::StringRef::size().
getExceptionPointerRegister()
Register PPCTargetLowering::getExceptionPointerRegister (const Constant * PersonalityFn) const override virtual
If a physical register, this returns the register that receives the exception address on entry to an EH pad.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17591 of file PPCISelLowering.cpp.
References llvm::PPCSubtarget::isPPC64().
getExceptionSelectorRegister()
Register PPCTargetLowering::getExceptionSelectorRegister (const Constant * PersonalityFn) const override virtual
If a physical register, this returns the register that receives the exception typeid on entry to a landing pad.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17596 of file PPCISelLowering.cpp.
References llvm::PPCSubtarget::isPPC64().
getInlineAsmMemConstraint()
InlineAsm::ConstraintCode llvm::PPCTargetLowering::getInlineAsmMemConstraint (StringRef ConstraintCode) const inline override virtual
Reimplemented from llvm::TargetLowering.
Definition at line 994 of file PPCISelLowering.h.
References llvm::InlineAsm::es, llvm::TargetLowering::getInlineAsmMemConstraint(), llvm::InlineAsm::Q, llvm::InlineAsm::Z, and llvm::InlineAsm::Zy.
getJumpTableEncoding()
unsigned PPCTargetLowering::getJumpTableEncoding () const override virtual
Return the entry encoding for a jump table in the current function.
The returned value is a member of the MachineJumpTableInfo::JTEntryKind enum.
Reimplemented from llvm::TargetLowering.
Definition at line 3232 of file PPCISelLowering.cpp.
References llvm::MachineJumpTableInfo::EK_LabelDifference32, llvm::TargetLowering::getJumpTableEncoding(), and isJumpTableRelative().
getNegatedExpression()
SDValue PPCTargetLowering::getNegatedExpression (SDValue Op, SelectionDAG & DAG, bool LegalOps, bool OptForSize, NegatibleCost & Cost, unsigned Depth = 0) const override virtual
Return the newly negated expression if the cost is not expensive and set the cost in Cost to indicate that if it is cheaper or neutral to do the negation.
Reimplemented from llvm::TargetLowering.
Definition at line 17640 of file PPCISelLowering.cpp.
References llvm::Depth, llvm::TargetLoweringBase::Expensive, llvm::ISD::FMA, llvm::PPCISD::FNMSUB, getNegatedExpression(), llvm::TargetLowering::getNegatedExpression(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getTargetMachine(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isTypeLegal(), llvm::SelectionDAG::MaxRecursionDepth, llvm::TargetMachine::Options, Options, and SDValue().
Referenced by getNegatedExpression().
getOptimalMemOpType()
EVT PPCTargetLowering::getOptimalMemOpType (const MemOp & Op, const AttributeList & FuncAttributes) const override virtual
It returns EVT::Other if the type should be determined using generic target-independent logic.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17349 of file PPCISelLowering.cpp.
References llvm::TargetLoweringBase::getTargetMachine(), llvm::PPCSubtarget::isPPC64(), and llvm::None.
getPICJumpTableRelocBase()
SDValue PPCTargetLowering::getPICJumpTableRelocBase (SDValue Table, SelectionDAG & DAG) const override virtual
Returns relocation base for the given PIC jumptable.
Reimplemented from llvm::TargetLowering.
Definition at line 3247 of file PPCISelLowering.cpp.
References getCodeModel(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::TargetLowering::getPICJumpTableRelocBase(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getTargetMachine(), llvm::PPCISD::GlobalBaseReg, llvm::PPCSubtarget::isAIXABI(), llvm::PPCSubtarget::isPPC64(), llvm::CodeModel::Medium, and llvm::CodeModel::Small.
getPICJumpTableRelocBaseExpr()
const MCExpr * PPCTargetLowering::getPICJumpTableRelocBaseExpr (const MachineFunction * MF, unsigned JTI, MCContext & Ctx) const override virtual
This returns the relocation base for the given PIC jumptable, the same as getPICJumpTableRelocBase, but as an MCExpr.
Reimplemented from llvm::TargetLowering.
Definition at line 3263 of file PPCISelLowering.cpp.
References llvm::MCSymbolRefExpr::create(), getCodeModel(), llvm::MachineFunction::getPICBaseSymbol(), llvm::TargetLowering::getPICJumpTableRelocBaseExpr(), llvm::TargetLoweringBase::getTargetMachine(), llvm::PPCSubtarget::isAIXABI(), llvm::PPCSubtarget::isPPC64(), llvm::CodeModel::Medium, and llvm::CodeModel::Small.
getPreferredVectorAction()
TargetLoweringBase::LegalizeTypeAction llvm::PPCTargetLowering::getPreferredVectorAction (MVT VT) const inline override virtual
getPreferredVectorAction - The code we generate when vector types are legalized by promoting the integer element type is often much worse than code we generate if we widen the type for applicable vector types.
The issue with promoting is that the vector is scalaraized, individual elements promoted and then the vector is rebuilt. So say we load a pair of v4i8's and shuffle them. This will turn into a mess of 8 extending loads, moves back into VSR's (or memory ops if we don't have moves) and then the VPERM for the shuffle. All in all a very slow sequence.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 770 of file PPCISelLowering.h.
References llvm::TargetLoweringBase::getPreferredVectorAction(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::MVT::isScalableVector(), llvm::TargetLoweringBase::TypePromoteInteger, llvm::TargetLoweringBase::TypeSplitVector, and llvm::TargetLoweringBase::TypeWidenVector.
getPrefLoopAlignment()
Align PPCTargetLowering::getPrefLoopAlignment (MachineLoop * ML) const override virtual
Return the preferred loop alignment.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 16660 of file PPCISelLowering.cpp.
References Align, llvm::PPC::DIR_970, llvm::PPC::DIR_PWR10, llvm::PPC::DIR_PWR11, llvm::PPC::DIR_PWR4, llvm::PPC::DIR_PWR5, llvm::PPC::DIR_PWR5X, llvm::PPC::DIR_PWR6, llvm::PPC::DIR_PWR6X, llvm::PPC::DIR_PWR7, llvm::PPC::DIR_PWR8, llvm::PPC::DIR_PWR9, llvm::PPC::DIR_PWR_FUTURE, DisableInnermostLoopAlign32, llvm::PPCSubtarget::getCPUDirective(), llvm::PPCSubtarget::getInstrInfo(), llvm::TargetLoweringBase::getPrefLoopAlignment(), I, ML, and TII.
getPreIndexedAddressParts()
bool PPCTargetLowering::getPreIndexedAddressParts (SDNode * N, SDValue & Base, SDValue & Offset, ISD::MemIndexedMode & AM, SelectionDAG & DAG) const override virtual
getPreIndexedAddressParts - returns true by value, base pointer and offset pointer and addressing mode by reference if the node's address can be legally represented as pre-indexed load / store address.
Reimplemented from llvm::TargetLowering.
Definition at line 3048 of file PPCISelLowering.cpp.
References Align, llvm::sampleprof::Base, llvm::cast(), DisablePPCPreinc, llvm::dyn_cast(), llvm::SDValue::getNode(), llvm::isa(), isLoad(), llvm::SDNode::isPredecessorOf(), llvm::EVT::isVector(), N, llvm::Offset, llvm::ISD::PRE_INC, Ptr, SelectAddressRegImm(), SelectAddressRegReg(), llvm::ISD::SEXTLOAD, std::swap(), and usePartialVectorLoads().
getRegForInlineAsmConstraint()
std::pair< unsigned, const TargetRegisterClass * > PPCTargetLowering::getRegForInlineAsmConstraint (const TargetRegisterInfo * TRI, StringRef Constraint, MVT VT) const override virtual
Given a physical register constraint (e.g.
{edx}), return the register number and the register class for the register.
Given a register class constraint, like 'r', if this corresponds directly to an LLVM register class, return a register of 0 and the register class pointer.
This should only be used for C_Register constraints. On error, this returns a register number of 0 and a null register class pointer.
Reimplemented from llvm::TargetLowering.
Definition at line 16802 of file PPCISelLowering.cpp.
References assert(), llvm::StringRef::data(), llvm::errs(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::TargetLoweringBase::getTargetMachine(), llvm::PPCSubtarget::isAIXABI(), llvm::PPCSubtarget::isPPC64(), llvm::MVT::isVector(), llvm::report_fatal_error(), llvm::StringRef::size(), TM, and TRI.
getRegisterByName()
Register PPCTargetLowering::getRegisterByName (const char * RegName, LLT Ty, const MachineFunction & MF) const override virtual
Return the register ID of the name passed in.
Used by named register global variables extension. There is no target-independent behaviour so the default action is to bail.
Reimplemented from llvm::TargetLowering.
Definition at line 17141 of file PPCISelLowering.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), is64Bit(), llvm::PPCSubtarget::isPPC64(), Reg, Register, RegName, llvm::report_fatal_error(), and llvm::LLT::scalar().
getScalarShiftAmountTy()
MVT llvm::PPCTargetLowering::getScalarShiftAmountTy (const DataLayout & DL, EVT) const inline override virtual
Return the type to use for a scalar shift opcode, given the shifted amount type.
Targets should return a legal type if the input type is legal. Targets can return a type that is too small if the input type is illegal.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 793 of file PPCISelLowering.h.
getSchedulingPreference()
Sched::Preference PPCTargetLowering::getSchedulingPreference (SDNode *) const override virtual
Some scheduler, e.g.
hybrid, can switch to different scheduling heuristics for different nodes. This function returns the preference (or none) for the given node.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17613 of file PPCISelLowering.cpp.
References DisableILPPref, llvm::PPCSubtarget::enableMachineScheduler(), llvm::TargetLoweringBase::getSchedulingPreference(), llvm::Sched::ILP, and N.
getScratchRegisters()
const MCPhysReg * PPCTargetLowering::getScratchRegisters (CallingConv::ID CC) const override virtual
Returns a 0 terminated array of registers that can be safely used as scratch registers.
Reimplemented from llvm::TargetLowering.
Definition at line 17579 of file PPCISelLowering.cpp.
getSDagStackGuard()
Value * PPCTargetLowering::getSDagStackGuard (const Module & M) const override virtual
Return the variable that's previously inserted by insertSSPDeclarations, if any, otherwise return nullptr.
Should be used only when getIRStackGuard returns nullptr.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17724 of file PPCISelLowering.cpp.
References AIXSSPCanaryWordName, llvm::TargetLoweringBase::getSDagStackGuard(), and llvm::PPCSubtarget::isAIXABI().
getSetCCResultType()
EVT PPCTargetLowering::getSetCCResultType (const DataLayout & DL, LLVMContext & Context, EVT VT) const override virtual
getSetCCResultType - Return the ISD::SETCC ValueType
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1844 of file PPCISelLowering.cpp.
References llvm::EVT::changeVectorElementTypeToInteger(), and llvm::EVT::isVector().
Referenced by ReplaceNodeResults().
getSingleConstraintMatchWeight()
TargetLowering::ConstraintWeight PPCTargetLowering::getSingleConstraintMatchWeight (AsmOperandInfo & info, const char * constraint) const override virtual
Examine constraint string and operand type and determine a weight value.
Examine constraint type and operand type and determine a weight value.
The operand object must already have been set up with the operand type.
This object must already have been set up with the operand type and the current alternative constraint selected.
Reimplemented from llvm::TargetLowering.
Definition at line 16746 of file PPCISelLowering.cpp.
References llvm::TargetLowering::CW_Default, llvm::TargetLowering::CW_Invalid, llvm::TargetLowering::CW_Memory, llvm::TargetLowering::CW_Register, llvm::TargetLowering::getSingleConstraintMatchWeight(), llvm::Value::getType(), and info.
getStackProbeSize()
unsigned PPCTargetLowering::getStackProbeSize (const MachineFunction & MF) const
Definition at line 12674 of file PPCISelLowering.cpp.
References assert(), llvm::Function::getFnAttributeAsParsedInteger(), llvm::PPCSubtarget::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::TargetFrameLowering::getStackAlignment(), and llvm::isPowerOf2_32().
Referenced by emitProbedAlloca(), llvm::PPCFrameLowering::emitPrologue(), and llvm::PPCFrameLowering::inlineStackProbe().
getTargetNodeName()
const char * PPCTargetLowering::getTargetNodeName (unsigned Opcode) const override virtual
getTargetNodeName() - This method returns the name of a target specific DAG node.
Reimplemented from llvm::TargetLowering.
Definition at line 1671 of file PPCISelLowering.cpp.
References llvm::PPCISD::ACC_BUILD, llvm::PPCISD::ADD_TLS, llvm::PPCISD::ADDI_DTPREL_L, llvm::PPCISD::ADDI_TLSGD_L, llvm::PPCISD::ADDI_TLSGD_L_ADDR, llvm::PPCISD::ADDI_TLSLD_L, llvm::PPCISD::ADDI_TLSLD_L_ADDR, llvm::PPCISD::ADDIS_DTPREL_HA, llvm::PPCISD::ADDIS_GOT_TPREL_HA, llvm::PPCISD::ADDIS_TLSGD_HA, llvm::PPCISD::ADDIS_TLSLD_HA, llvm::PPCISD::ANDI_rec_1_EQ_BIT, llvm::PPCISD::ANDI_rec_1_GT_BIT, llvm::PPCISD::ATOMIC_CMP_SWAP_16, llvm::PPCISD::ATOMIC_CMP_SWAP_8, llvm::PPCISD::BCTRL, llvm::PPCISD::BCTRL_LOAD_TOC, llvm::PPCISD::BCTRL_LOAD_TOC_RM, llvm::PPCISD::BCTRL_RM, llvm::PPCISD::BDNZ, llvm::PPCISD::BDZ, llvm::PPCISD::BUILD_FP128, llvm::PPCISD::BUILD_SPE64, llvm::PPCISD::CALL, llvm::PPCISD::CALL_NOP, llvm::PPCISD::CALL_NOP_RM, llvm::PPCISD::CALL_NOTOC, llvm::PPCISD::CALL_NOTOC_RM, llvm::PPCISD::CALL_RM, llvm::PPCISD::CLRBHRB, llvm::PPCISD::CMPB, llvm::PPCISD::COND_BRANCH, llvm::PPCISD::CR6SET, llvm::PPCISD::CR6UNSET, llvm::PPCISD::DYNALLOC, llvm::PPCISD::DYNAREAOFFSET, llvm::PPCISD::EH_SJLJ_LONGJMP, llvm::PPCISD::EH_SJLJ_SETJMP, llvm::PPCISD::EXTRACT_SPE, llvm::PPCISD::EXTRACT_VSX_REG, llvm::PPCISD::EXTSWSLI, llvm::PPCISD::FADDRTZ, llvm::PPCISD::FCFID, llvm::PPCISD::FCFIDS, llvm::PPCISD::FCFIDU, llvm::PPCISD::FCFIDUS, llvm::PPCISD::FCTIDUZ, llvm::PPCISD::FCTIDZ, llvm::PPCISD::FCTIWUZ, llvm::PPCISD::FCTIWZ, llvm::PPCISD::FIRST_NUMBER, llvm::PPCISD::FNMSUB, llvm::PPCISD::FP_EXTEND_HALF, llvm::PPCISD::FRE, llvm::PPCISD::FRSQRTE, llvm::PPCISD::FSEL, llvm::PPCISD::FSQRT, llvm::PPCISD::FTSQRT, llvm::PPCISD::GET_TLS_ADDR, llvm::PPCISD::GET_TLS_MOD_AIX, llvm::PPCISD::GET_TLSLD_ADDR, llvm::PPCISD::GET_TPOINTER, llvm::PPCISD::GlobalBaseReg, llvm::PPCISD::Hi, llvm::PPCISD::LBRX, llvm::PPCISD::LD_GOT_TPREL_L, llvm::PPCISD::LD_SPLAT, llvm::PPCISD::LD_VSX_LH, llvm::PPCISD::LFIWAX, llvm::PPCISD::LFIWZX, llvm::PPCISD::Lo, llvm::PPCISD::LOAD_VEC_BE, llvm::PPCISD::LXSIZX, llvm::PPCISD::LXVD2X, llvm::PPCISD::LXVRZX, llvm::PPCISD::MAT_PCREL_ADDR, llvm::PPCISD::MFBHRBE, llvm::PPCISD::MFFS, llvm::PPCISD::MFOCRF, llvm::PPCISD::MFVSR, llvm::PPCISD::MTCTR, llvm::PPCISD::MTVSRA, llvm::PPCISD::MTVSRZ, llvm::PPCISD::PADDI_DTPREL, llvm::PPCISD::PAIR_BUILD, llvm::PPCISD::PPC32_GOT, llvm::PPCISD::PPC32_PICGOT, llvm::PPCISD::PROBED_ALLOCA, llvm::PPCISD::READ_TIME_BASE, llvm::PPCISD::RET_GLUE, llvm::PPCISD::RFEBB, llvm::PPCISD::SC, llvm::PPCISD::SCALAR_TO_VECTOR_PERMUTED, llvm::PPCISD::SEXT_LD_SPLAT, llvm::PPCISD::SHL, llvm::PPCISD::SINT_VEC_TO_FP, llvm::PPCISD::SRA, llvm::PPCISD::SRA_ADDZE, llvm::PPCISD::SRL, llvm::PPCISD::ST_VSR_SCAL_INT, llvm::PPCISD::STBRX, llvm::PPCISD::STFIWX, llvm::PPCISD::STORE_COND, llvm::PPCISD::STORE_VEC_BE, llvm::PPCISD::STRICT_FADDRTZ, llvm::PPCISD::STRICT_FCFID, llvm::PPCISD::STRICT_FCFIDS, llvm::PPCISD::STRICT_FCFIDU, llvm::PPCISD::STRICT_FCFIDUS, llvm::PPCISD::STRICT_FCTIDUZ, llvm::PPCISD::STRICT_FCTIDZ, llvm::PPCISD::STRICT_FCTIWUZ, llvm::PPCISD::STRICT_FCTIWZ, llvm::PPCISD::STXSIX, llvm::PPCISD::STXVD2X, llvm::PPCISD::SWAP_NO_CHAIN, llvm::PPCISD::TC_RETURN, llvm::PPCISD::TLS_DYNAMIC_MAT_PCREL_ADDR, llvm::PPCISD::TLS_LOCAL_EXEC_MAT_ADDR, llvm::PPCISD::TLSGD_AIX, llvm::PPCISD::TLSLD_AIX, llvm::PPCISD::TOC_ENTRY, llvm::PPCISD::UINT_VEC_TO_FP, llvm::PPCISD::VADD_SPLAT, llvm::PPCISD::VCMP, llvm::PPCISD::VCMP_rec, llvm::PPCISD::VECINSERT, llvm::PPCISD::VECSHL, llvm::PPCISD::VEXTS, llvm::PPCISD::VPERM, llvm::PPCISD::XSMAXC, llvm::PPCISD::XSMINC, llvm::PPCISD::XXMFACC, llvm::PPCISD::XXPERM, llvm::PPCISD::XXPERMDI, llvm::PPCISD::XXSPLT, llvm::PPCISD::XXSPLTI32DX, llvm::PPCISD::XXSPLTI_SP_TO_DP, llvm::PPCISD::XXSWAPD, and llvm::PPCISD::ZEXT_LD_SPLAT.
getTgtMemIntrinsic()
bool PPCTargetLowering::getTgtMemIntrinsic (IntrinsicInfo & , const CallInst & , MachineFunction & , unsigned) const override virtual
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory).
If this is the case, it returns true and store the intrinsic information into the IntrinsicInfo that was passed to the function.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17192 of file PPCISelLowering.cpp.
References Align, llvm::EVT::getStoreSize(), I, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, and llvm::MachineMemOperand::MOVolatile.
hasAndNotCompare()
bool llvm::PPCTargetLowering::hasAndNotCompare (SDValue Y) const inline override virtual
Return true if the target should transform: (X & Y) == Y ---> (~X & Y) == 0 (X & Y) != Y ---> (~X & Y) != 0.
This may be profitable if the target has a bitwise and-not operation that sets comparison flags. A target may want to limit the transformation based on the type of Y or if Y is a constant.
Note that the transform will not occur if Y is known to be a power-of-2 because a mask and compare of a single bit can be handled by inverting the predicate, for example: (X & 8) == 8 ---> (X & 8) != 0
Reimplemented from llvm::TargetLoweringBase.
Definition at line 818 of file PPCISelLowering.h.
hasInlineStackProbe()
bool PPCTargetLowering::hasInlineStackProbe (const MachineFunction & MF) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 12666 of file PPCISelLowering.cpp.
References llvm::Function::getFnAttribute(), llvm::MachineFunction::getFunction(), llvm::Attribute::getValueAsString(), and llvm::Function::hasFnAttribute().
Referenced by llvm::PPCFrameLowering::emitPrologue().
hasSPE()
bool PPCTargetLowering::hasSPE () const
Definition at line 1642 of file PPCISelLowering.cpp.
Referenced by PPCTargetLowering(), and SelectAddressRegReg().
insertSSPDeclarations()
void PPCTargetLowering::insertSSPDeclarations (Module & M) const override virtual
Inserts necessary declarations for SSP (stack protection) purpose.
Should be used only when getIRStackGuard returns nullptr.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17714 of file PPCISelLowering.cpp.
References AIXSSPCanaryWordName, llvm::PointerType::getUnqual(), llvm::TargetLoweringBase::insertSSPDeclarations(), llvm::PPCSubtarget::isAIXABI(), and llvm::PPCSubtarget::isTargetLinux().
isAccessedAsGotIndirect()
bool PPCTargetLowering::isAccessedAsGotIndirect (SDValue N) const
Definition at line 17160 of file PPCISelLowering.cpp.
References llvm::dyn_cast(), G, llvm::TargetMachine::getCodeModel(), llvm::TargetLoweringBase::getTargetMachine(), llvm::PPCSubtarget::is32BitELFABI(), llvm::isa(), llvm::PPCSubtarget::isAIXABI(), llvm::PPCSubtarget::isGVIndirectSymbol(), llvm::CodeModel::Large, and llvm::CodeModel::Small.
isCheapToSpeculateCtlz()
bool llvm::PPCTargetLowering::isCheapToSpeculateCtlz (Type * Ty) const inline override virtual
Return true if it is cheap to speculate a call to intrinsic ctlz.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 801 of file PPCISelLowering.h.
isCheapToSpeculateCttz()
bool llvm::PPCTargetLowering::isCheapToSpeculateCttz (Type * Ty) const inline override virtual
Return true if it is cheap to speculate a call to intrinsic cttz.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 797 of file PPCISelLowering.h.
isCtlzFast()
bool llvm::PPCTargetLowering::isCtlzFast () const inline override virtual
Return true if ctlz instruction is fast.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 810 of file PPCISelLowering.h.
isDesirableToTransformToIntegerOp()
bool llvm::PPCTargetLowering::isDesirableToTransformToIntegerOp (unsigned , EVT) const inline override virtual
Return true if it is profitable for dag combiner to transform a floating point op of specified opcode to a equivalent op of an integer type.
e.g. f32 load -> i32 load can be profitable on ARM.
Reimplemented from llvm::TargetLowering.
Definition at line 1050 of file PPCISelLowering.h.
isEqualityCmpFoldedWithSignedCmp()
bool llvm::PPCTargetLowering::isEqualityCmpFoldedWithSignedCmp () const inline override virtual
Return true if instruction generated for equality comparison is folded with instruction generated for signed comparison.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 814 of file PPCISelLowering.h.
isFMAFasterThanFMulAndFAdd() [1/2]
bool PPCTargetLowering::isFMAFasterThanFMulAndFAdd (const Function & F, Type *) const override virtual
IR version.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17511 of file PPCISelLowering.cpp.
References llvm::Type::DoubleTyID, llvm::Type::FloatTyID, llvm::Type::FP128TyID, and llvm::PPCSubtarget::useSoftFloat().
isFMAFasterThanFMulAndFAdd() [2/2]
bool PPCTargetLowering::isFMAFasterThanFMulAndFAdd (const MachineFunction & MF, EVT VT) const override virtual
isFMAFasterThanFMulAndFAdd - Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
fmuladd intrinsics will be expanded to FMAs when this method returns true, otherwise fmuladd is expanded to fmul + fadd.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17505 of file PPCISelLowering.cpp.
References llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::EVT::getTypeForEVT(), and isFMAFasterThanFMulAndFAdd().
Referenced by isFMAFasterThanFMulAndFAdd(), and isProfitableToHoist().
isFPExtFree()
bool PPCTargetLowering::isFPExtFree (EVT DestVT, EVT SrcVT) const override virtual
Return true if an fpext operation is free (for instance, because single-precision floating-point numbers are implicitly extended to double-precision).
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17423 of file PPCISelLowering.cpp.
References assert(), and llvm::EVT::isFloatingPoint().
isFPImmLegal()
bool PPCTargetLowering::isFPImmLegal (const APFloat & , EVT , bool ForCodeSize) const override virtual
Returns true if the target can instruction select the specified FP immediate natively.
If false, the legalizer will materialize the FP immediate as a load from a constant pool.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17730 of file PPCISelLowering.cpp.
References llvm::EVT::getSimpleVT(), llvm::EVT::isSimple(), llvm::APFloatBase::rmTowardZero, and llvm::MVT::SimpleTy.
isJumpTableRelative()
bool PPCTargetLowering::isJumpTableRelative () const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3239 of file PPCISelLowering.cpp.
References llvm::PPCSubtarget::isAIXABI(), llvm::TargetLoweringBase::isJumpTableRelative(), llvm::PPCSubtarget::isPPC64(), and UseAbsoluteJumpTables.
Referenced by getJumpTableEncoding().
isLegalAddImmediate()
bool PPCTargetLowering::isLegalAddImmediate (int64_t Imm) const override virtual
isLegalAddImmediate - Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register and the immediate without having to materialize the immediate into a register.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17436 of file PPCISelLowering.cpp.
References llvm::isInt(), and llvm::isUInt().
isLegalAddressingMode()
bool PPCTargetLowering::isLegalAddressingMode (const DataLayout & DL, const AddrMode & AM, Type * Ty, unsigned AS, Instruction * I = nullptr) const override virtual
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17028 of file PPCISelLowering.cpp.
References llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, llvm::TargetLoweringBase::AddrMode::HasBaseReg, and llvm::TargetLoweringBase::AddrMode::Scale.
isLegalICmpImmediate()
bool PPCTargetLowering::isLegalICmpImmediate (int64_t Imm) const override virtual
isLegalICmpImmediate - Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17432 of file PPCISelLowering.cpp.
References llvm::isInt(), and llvm::isUInt().
isOffsetFoldingLegal()
bool PPCTargetLowering::isOffsetFoldingLegal (const GlobalAddressSDNode * GA) const override virtual
Return true if folding a constant offset with the given GlobalAddress is legal.
It is frequently not legal in PIC relocation models.
Reimplemented from llvm::TargetLowering.
Definition at line 17187 of file PPCISelLowering.cpp.
isProfitableToHoist()
bool PPCTargetLowering::isProfitableToHoist (Instruction * I) const override virtual
isProfitableToHoist - Check if it is profitable to hoist instruction I to its dominator block.
For example, it is not profitable if I and it's only user can form a FMA instruction, because Powerpc prefers FMADD.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17527 of file PPCISelLowering.cpp.
References assert(), llvm::cast(), DL, F, llvm::FPOpFusion::Fast, llvm::Type::FloatTyID, llvm::ISD::FMA, llvm::Function::getFunction(), llvm::User::getOperand(), llvm::TargetLoweringBase::getTargetMachine(), llvm::Value::getType(), llvm::TargetLoweringBase::getValueType(), I, isFMAFasterThanFMulAndFAdd(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::LoadInst::isUnordered(), llvm::TargetMachine::Options, Options, and llvm::Value::user_back().
isSelectSupported()
bool llvm::PPCTargetLowering::isSelectSupported (SelectSupportKind Kind) const inline override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 757 of file PPCISelLowering.h.
References llvm::TargetLoweringBase::ScalarCondVectorVal.
isTruncateFree() [1/2]
bool PPCTargetLowering::isTruncateFree (EVT VT1, EVT VT2) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17395 of file PPCISelLowering.cpp.
References llvm::EVT::getSizeInBits(), and llvm::EVT::isInteger().
isTruncateFree() [2/2]
bool PPCTargetLowering::isTruncateFree (Type * Ty1, Type * Ty2) const override virtual
isTruncateFree - Return true if it's free to truncate a value of type Ty1 to type Ty2.
e.g. On PPC it's free to truncate a i64 value in register X1 to i32 by referencing its sub-register R1.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17387 of file PPCISelLowering.cpp.
References llvm::Type::getPrimitiveSizeInBits(), and llvm::Type::isIntegerTy().
isZExtFree()
bool PPCTargetLowering::isZExtFree (SDValue Val, EVT VT2) const override virtual
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17403 of file PPCISelLowering.cpp.
References llvm::dyn_cast(), llvm::PPCSubtarget::isPPC64(), llvm::TargetLoweringBase::isZExtFree(), llvm::ISD::NON_EXTLOAD, and llvm::ISD::ZEXTLOAD.
LowerAsmOperandForConstraint()
void PPCTargetLowering::LowerAsmOperandForConstraint (SDValue Op, StringRef Constraint, std::vector< SDValue > & Ops, SelectionDAG & DAG) const override virtual
LowerAsmOperandForConstraint - Lower the specified operand into the Ops vector.
If it is invalid, don't add anything to Ops.
Reimplemented from llvm::TargetLowering.
Definition at line 16935 of file PPCISelLowering.cpp.
References llvm::dyn_cast(), llvm::ConstantSDNode::getSExtValue(), llvm::SelectionDAG::getTargetConstant(), llvm::isInt(), llvm::isPowerOf2_64(), llvm::isShiftedInt(), llvm::isShiftedUInt(), llvm::isUInt(), llvm_unreachable, llvm::TargetLowering::LowerAsmOperandForConstraint(), and llvm::StringRef::size().
LowerOperation()
SDValue PPCTargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const override virtual
LowerOperation - Provide custom lowering hooks for some operations.
Reimplemented from llvm::TargetLowering.
Definition at line 11793 of file PPCISelLowering.cpp.
References llvm::ISD::BlockAddress, llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, llvm::ISD::ConstantPool, llvm::ISD::EH_DWARF_CFA, llvm::ISD::EH_SJLJ_LONGJMP, llvm::ISD::EH_SJLJ_SETJMP, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FRAMEADDR, llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::ISD::GET_ROUNDING, llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::ISD::IS_FPCLASS, llvm::ISD::JumpTable, llvm_unreachable, llvm::ISD::MUL, llvm::ISD::RETURNADDR, llvm::ISD::ROTL, llvm::ISD::SCALAR_TO_VECTOR, SDValue(), llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SHL_PARTS, llvm::ISD::SINT_TO_FP, llvm::ISD::SRA_PARTS, llvm::ISD::SRL_PARTS, llvm::ISD::STRICT_FP_ROUND, llvm::ISD::STRICT_FP_TO_SINT, llvm::ISD::STRICT_FP_TO_UINT, llvm::ISD::STRICT_FSETCC, llvm::ISD::STRICT_FSETCCS, llvm::ISD::STRICT_SINT_TO_FP, llvm::ISD::STRICT_UINT_TO_FP, llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, and llvm::ISD::VECTOR_SHUFFLE.
PerformDAGCombine()
SDValue PPCTargetLowering::PerformDAGCombine (SDNode * N, DAGCombinerInfo & DCI) const override virtual
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
The semantics are as follows: Return Value: SDValue.Val == 0 - No change was made SDValue.Val == N - N was replaced, is dead, and is already handled. otherwise - N should be replaced by the returned Operand.
In addition, methods provided by DAGCombinerInfo may be used to perform more complex transformations.
Reimplemented from llvm::TargetLowering.
Definition at line 15777 of file PPCISelLowering.cpp.
References llvm::ISD::ABS, llvm::ISD::ADD, llvm::Add, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, assert(), llvm::EVT::bitsGT(), llvm::ISD::BSWAP, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, BuildIntrinsicOp(), llvm::CallingConv::C, llvm::cast(), CC, llvm::TargetLowering::DAGCombinerInfo::CombineTo(), llvm::commonAlignment(), llvm::PPCISD::COND_BRANCH, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::dyn_cast(), expandVSXLoadForLE(), expandVSXStoreForLE(), findConsecutiveLoad(), llvm::ISD::FMA, llvm::PPCISD::FNMSUB, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::DataLayout::getABITypeAlign(), llvm::APInt::getAllOnes(), llvm::SDNode::getAsZExtVal(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::MachineFunction::getDataLayout(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::User::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getOperand(), llvm::User::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::EVT::getStoreSize(), llvm::SelectionDAG::getTargetConstant(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), getVectorCompareInfo(), llvm::SelectionDAG::getVTList(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::SDNode::hasNUsesOfValue(), llvm::SDNode::hasOneUse(), llvm::Hi, Intr, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::isa(), llvm::TargetLowering::DAGCombinerInfo::isAfterLegalizeDAG(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), llvm::ISD::isBuildVectorAllZeros(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::EVT::isExtended(), llvm::PPCSubtarget::isLittleEndian(), llvm::ISD::isNON_EXTLoad(), llvm::ISD::isNormalLoad(), llvm::ISD::isNormalStore(), llvm::isNullConstant(), llvm::PPCSubtarget::isPPC64(), llvm::EVT::isSimple(), isStoreConditional(), llvm::isUInt(), llvm::EVT::isVector(), llvm::PPCISD::LBRX, llvm::Lo, llvm::SelectionDAG::MaskedValueIsZero(), llvm::PPCISD::MFOCRF, llvm::ISD::MUL, N, llvm::PPCSubtarget::needsSwapsForVSXMemOps(), llvm::ISD::NON_EXTLOAD, llvm::ISD::PRE_INC, llvm::PPC::PRED_EQ, llvm::PPC::PRED_GE, llvm::PPC::PRED_LT, llvm::PPC::PRED_NE, Ptr, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::ROTL, llvm::ISD::ROTR, SDValue(), llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::ISD::SHL, llvm::PPCISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::SignExtend64(), llvm::ISD::SINT_TO_FP, llvm::ISD::SRA, llvm::PPCISD::SRA, llvm::ISD::SRL, llvm::PPCISD::SRL, llvm::PPCISD::STBRX, llvm::PPCISD::STORE_COND, llvm::ISD::STRICT_FP_TO_SINT, llvm::ISD::STRICT_FP_TO_UINT, llvm::ISD::SUB, std::swap(), llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::SelectionDAG::UpdateNodeOperands(), llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::SDNode::uses(), llvm::PPCISD::VCMP, llvm::PPCISD::VCMP_rec, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::ZERO_EXTEND, and llvm::APInt::zext().
preferIncOfAddToSubOfNot()
bool PPCTargetLowering::preferIncOfAddToSubOfNot (EVT VT) const override virtual
These two forms are equivalent: sub y, (xor x, -1) add (add x, 1), y The variant with two add's is IR-canonical.
Some targets may prefer one to the other.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1646 of file PPCISelLowering.cpp.
References llvm::EVT::isScalarInteger().
ReplaceNodeResults()
void PPCTargetLowering::ReplaceNodeResults (SDNode * N, SmallVectorImpl< SDValue > & Results, SelectionDAG & DAG) const override virtual
ReplaceNodeResults - Replace the results of node with an illegal result type with new values built out of custom code.
Reimplemented from llvm::TargetLowering.
Definition at line 11887 of file PPCISelLowering.cpp.
References assert(), llvm::ISD::BUILD_PAIR, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), getSetCCResultType(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm_unreachable, N, llvm::PPCISD::READ_TIME_BASE, Results, SDValue(), llvm::ISD::STRICT_FP_TO_SINT, llvm::ISD::STRICT_FP_TO_UINT, and llvm::ISD::TRUNCATE.
SelectAddressEVXRegReg()
bool PPCTargetLowering::SelectAddressEVXRegReg (SDValue N, SDValue & Base, SDValue & Index, SelectionDAG & DAG) const
SelectAddressEVXRegReg - Given the specified addressed, check to see if it can be more efficiently represented as [r+imm].
SelectAddressEVXRegReg - Given the specified address, check to see if it can be represented as an indexed [r+r] operation.
Definition at line 2670 of file PPCISelLowering.cpp.
References llvm::sampleprof::Base, llvm::dyn_cast(), N, and llvm::SDNode::uses().
Referenced by SelectAddressRegReg().
SelectAddressPCRel()
bool PPCTargetLowering::SelectAddressPCRel (SDValue N, SDValue & Base) const
SelectAddressPCRel - Represent the specified address as pc relative to be represented as [pc+imm].
Returns true if this address is a PC Relative address.
PC Relative addresses are marked with the flag PPCII::MO_PCREL_FLAG or if the node opcode is PPCISD::MAT_PCREL_ADDR.
Definition at line 2988 of file PPCISelLowering.cpp.
References llvm::sampleprof::Base, isValidPCRelNode(), llvm::PPCISD::MAT_PCREL_ADDR, and N.
Referenced by SelectAddressRegImm(), and SelectAddressRegReg().
SelectAddressRegImm()
bool PPCTargetLowering::SelectAddressRegImm (SDValue N, SDValue & Disp, SDValue & Base, SelectionDAG & DAG, MaybeAlign EncodingAlignment) const
SelectAddressRegImm - Returns true if the address N can be represented by a base register plus a signed 16-bit displacement [r+imm], and if it is not better represented as reg+reg.
Returns true if the address N can be represented by a base register plus a signed 16-bit displacement [r+imm], and if it is not better represented as reg+reg.
If EncodingAlignment is non-zero, only accept displacements suitable for instruction encoding requirement, i.e. multiples of 4 for DS form.
If EncodingAlignment is non-zero, only accept displacements that are multiples of that value.
Definition at line 2796 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, Addr, assert(), llvm::sampleprof::Base, llvm::SelectionDAG::computeKnownBits(), llvm::dyn_cast(), fixupFuncForFI(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getValueType(), llvm::APInt::getZExtValue(), llvm::isAligned(), llvm::isIntS16Immediate(), llvm::PPCSubtarget::isPPC64(), llvm::PPCISD::Lo, N, llvm::ISD::OR, SDValue(), SelectAddressPCRel(), SelectAddressRegReg(), llvm::ISD::TargetConstantPool, llvm::ISD::TargetGlobalAddress, llvm::ISD::TargetGlobalTLSAddress, llvm::ISD::TargetJumpTable, and llvm::KnownBits::Zero.
Referenced by getPreIndexedAddressParts().
SelectAddressRegImm34()
bool PPCTargetLowering::SelectAddressRegImm34 (SDValue N, SDValue & Disp, SDValue & Base, SelectionDAG & DAG) const
Similar to the 16-bit case but for instructions that take a 34-bit displacement field (prefixed loads/stores).
Definition at line 2901 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::sampleprof::Base, llvm::SelectionDAG::computeKnownBits(), llvm::dyn_cast(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::APInt::getZExtValue(), llvm::isIntS34Immediate(), N, llvm::ISD::OR, and llvm::KnownBits::Zero.
SelectAddressRegReg()
bool PPCTargetLowering::SelectAddressRegReg (SDValue N, SDValue & Base, SDValue & Index, SelectionDAG & DAG, MaybeAlign EncodingAlignment = std::nullopt) const
SelectAddressRegReg - Given the specified addressed, check to see if it can be more efficiently represented as [r+imm].
SelectAddressRegReg - Given the specified addressed, check to see if it can be represented as an indexed [r+r] operation.
If EncodingAlignment is non-zero, only accept displacement which is not suitable for [r+imm]. Returns false if it can be represented by [r+imm], which are preferred.
Returns false if it can be more efficiently represented as [r+imm]. If EncodingAlignment is non-zero and N can be represented by a base register plus a signed 16-bit displacement, make a more precise judgement by checking (displacement % EncodingAlignment).
Definition at line 2705 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::sampleprof::Base, llvm::SelectionDAG::computeKnownBits(), llvm::APInt::getBoolValue(), hasSPE(), llvm::isAligned(), llvm::isIntS16Immediate(), llvm::PPCISD::Lo, N, llvm::ISD::OR, SelectAddressEVXRegReg(), SelectAddressPCRel(), and llvm::KnownBits::Zero.
Referenced by getPreIndexedAddressParts(), SelectAddressRegImm(), and SelectAddressRegRegOnly().
SelectAddressRegRegOnly()
bool PPCTargetLowering::SelectAddressRegRegOnly (SDValue N, SDValue & Base, SDValue & Index, SelectionDAG & DAG) const
SelectAddressRegRegOnly - Given the specified addressed, force it to be represented as an indexed [r+r] operation.
Definition at line 2950 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::sampleprof::Base, llvm::SelectionDAG::getRegister(), llvm::isIntS16Immediate(), llvm::PPCSubtarget::isPPC64(), N, and SelectAddressRegReg().
SelectForceXFormMode()
PPC::AddrMode PPCTargetLowering::SelectForceXFormMode (SDValue N, SDValue & Disp, SDValue & Base, SelectionDAG & DAG) const
SelectForceXFormMode - Given the specified address, force it to be represented as an indexed [r+r] operation (an XForm instruction).
Definition at line 18438 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, llvm::PPC::AM_XForm, llvm::sampleprof::Base, llvm::SDValue::getOperand(), llvm::SelectionDAG::getRegister(), llvm::isIntS16Immediate(), llvm::PPCSubtarget::isPPC64(), Mode, N, and provablyDisjointOr().
SelectOptimalAddrMode()
PPC::AddrMode PPCTargetLowering::SelectOptimalAddrMode (const SDNode * Parent, SDValue N, SDValue & Disp, SDValue & Base, SelectionDAG & DAG, MaybeAlign Align) const
SelectOptimalAddrMode - Based on a node N and it's Parent (a MemSDNode), compute the address flags of the node, get the optimal address mode based on the flags, and set the Base and Disp based on the address mode.
Definition at line 18616 of file PPCISelLowering.cpp.
References llvm::ISD::ADD, Addr, llvm::PPC::AM_DForm, llvm::PPC::AM_DQForm, llvm::PPC::AM_DSForm, llvm::PPC::AM_None, llvm::PPC::AM_PCRel, llvm::PPC::AM_PrefixDForm, llvm::PPC::AM_XForm, assert(), llvm::sampleprof::Base, llvm::cast(), DL, llvm::dyn_cast(), fixupFuncForFI(), llvm::SDNode::getAsZExtVal(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetFrameIndex(), llvm::isAligned(), llvm::isInt(), llvm::isIntS16Immediate(), llvm::isIntS34Immediate(), isPCRelNode(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isUsingPCRelativeCalls(), Mode, llvm::PPC::MOF_AddrIsSImm32, llvm::PPC::MOF_RPlusLo, llvm::PPC::MOF_RPlusSImm16, N, llvm::ISD::OR, SDValue(), setXFormForUnalignedFI(), llvm::ISD::TargetConstantPool, llvm::ISD::TargetGlobalAddress, llvm::ISD::TargetGlobalTLSAddress, and llvm::ISD::TargetJumpTable.
shallExtractConstSplatVectorElementToStore()
bool PPCTargetLowering::shallExtractConstSplatVectorElementToStore (Type * VectorTy, unsigned ElemSizeInBits, unsigned & Index) const override virtual
Return true if the target shall perform extract vector element and store given that the vector is known to be splat of constant.
Index[out] gives the index of the vector element to be extracted when this is true.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1650 of file PPCISelLowering.cpp.
References llvm::dyn_cast(), llvm::PPCSubtarget::isLittleEndian(), and llvm::PPCSubtarget::isPPC64().
shouldConvertConstantLoadToIntImm()
bool PPCTargetLowering::shouldConvertConstantLoadToIntImm (const APInt & Imm, Type * Ty) const override virtual
Returns true if it is beneficial to convert a load of a constant to just the constant itself.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17379 of file PPCISelLowering.cpp.
References assert().
shouldExpandAtomicCmpXchgInIR()
TargetLowering::AtomicExpansionKind PPCTargetLowering::shouldExpandAtomicCmpXchgInIR (AtomicCmpXchgInst * AI) const override virtual
Returns how the given atomic cmpxchg should be expanded by the IR-level AtomicExpand pass.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 18784 of file PPCISelLowering.cpp.
References llvm::AtomicCmpXchgInst::getNewValOperand(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::TargetLoweringBase::MaskedIntrinsic, llvm::TargetLoweringBase::shouldExpandAtomicCmpXchgInIR(), shouldInlineQuadwordAtomics(), and Size.
shouldExpandAtomicRMWInIR()
TargetLowering::AtomicExpansionKind PPCTargetLowering::shouldExpandAtomicRMWInIR (AtomicRMWInst * RMW) const override virtual
Returns how the IR-level AtomicExpand pass should expand the given AtomicRMW, if at all.
Default is to never expand.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 18767 of file PPCISelLowering.cpp.
References llvm::TargetLoweringBase::CmpXChg, llvm::AtomicRMWInst::getOperation(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm_unreachable, llvm::TargetLoweringBase::MaskedIntrinsic, llvm::TargetLoweringBase::shouldExpandAtomicRMWInIR(), shouldInlineQuadwordAtomics(), Size, llvm::AtomicRMWInst::UDecWrap, and llvm::AtomicRMWInst::UIncWrap.
shouldExpandBuildVectorWithShuffles()
bool PPCTargetLowering::shouldExpandBuildVectorWithShuffles (EVT VT, unsigned DefinedValues) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 17602 of file PPCISelLowering.cpp.
References llvm::TargetLoweringBase::shouldExpandBuildVectorWithShuffles().
shouldInlineQuadwordAtomics()
bool PPCTargetLowering::shouldInlineQuadwordAtomics () const
Definition at line 18762 of file PPCISelLowering.cpp.
References llvm::PPCSubtarget::isPPC64().
Referenced by emitMaskedAtomicCmpXchgIntrinsic(), emitMaskedAtomicRMWIntrinsic(), PPCTargetLowering(), shouldExpandAtomicCmpXchgInIR(), and shouldExpandAtomicRMWInIR().
shouldInsertFencesForAtomic()
bool llvm::PPCTargetLowering::shouldInsertFencesForAtomic (const Instruction * I) const inline override virtual
Whether AtomicExpandPass should automatically insert fences and reduce ordering for this atomic.
This should be true for most architectures with weak memory ordering. Defaults to false.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 913 of file PPCISelLowering.h.
shouldKeepZExtForFP16Conv()
bool llvm::PPCTargetLowering::shouldKeepZExtForFP16Conv () const inline override virtual
Does this target require the clearing of high-order bits in a register passed to the fp16 to fp conversion library function.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1107 of file PPCISelLowering.h.
splitValueIntoRegisterParts()
bool PPCTargetLowering::splitValueIntoRegisterParts (SelectionDAG & DAG, const SDLoc & DL, SDValue Val, SDValue * Parts, unsigned NumParts, MVT PartVT, std::optional< CallingConv::ID > CC) const override virtual
Target-specific splitting of values into parts that fit a register storing a legal type.
Reimplemented from llvm::TargetLowering.
Definition at line 18472 of file PPCISelLowering.cpp.
References DL, llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), and llvm::ISD::ZERO_EXTEND.
supportsTailCallFor()
bool PPCTargetLowering::supportsTailCallFor (const CallBase * CB) const
Definition at line 5853 of file PPCISelLowering.cpp.
References llvm::dyn_cast(), llvm::Function::getAttributes(), llvm::CallBase::getCalledFunction(), llvm::CallBase::getCaller(), llvm::CallBase::getCallingConv(), llvm::Function::getCallingConv(), llvm::Function::getDataLayout(), llvm::GetReturnInfo(), llvm::Function::getReturnType(), and llvm::Function::isVarArg().
Referenced by llvm::PPCTTIImpl::supportsTailCallFor().
useLoadStackGuardNode()
bool PPCTargetLowering::useLoadStackGuardNode () const override virtual
Override to support customized stack guard loading.
Reimplemented from llvm::TargetLowering.
Definition at line 17706 of file PPCISelLowering.cpp.
References llvm::PPCSubtarget::isTargetLinux(), and llvm::TargetLowering::useLoadStackGuardNode().
useSoftFloat()
bool PPCTargetLowering::useSoftFloat () const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1638 of file PPCISelLowering.cpp.
References llvm::PPCSubtarget::useSoftFloat().
Referenced by PPCTargetLowering().
The documentation for this class was generated from the following files:
lib/Target/PowerPC/PPCISelLowering.h
lib/Target/PowerPC/PPCISelLowering.cpp