LLVM: llvm::SSPLayoutInfo Class Reference
llvm::SSPLayoutInfo Class Reference
#include "llvm/CodeGen/StackProtector.h"
Public Member Functions
bool shouldEmitSDCheck (const BasicBlock &BB) const
void copyToMachineFrameInfo (MachineFrameInfo &MFI) const
Friends
class StackProtectorPass
class SSPLayoutAnalysis
class StackProtector
Detailed Description
Definition at line 34 of file StackProtector.h.
Member Function Documentation
copyToMachineFrameInfo()
void SSPLayoutInfo::copyToMachineFrameInfo (MachineFrameInfo & MFI) const
Definition at line 85 of file StackProtector.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::MachineFrameInfo::getObjectAllocation(), llvm::MachineFrameInfo::getObjectIndexEnd(), I, llvm::MachineFrameInfo::isDeadObjectIndex(), and llvm::MachineFrameInfo::setObjectSSPLayout().
Referenced by llvm::StackProtector::copyToMachineFrameInfo().
shouldEmitSDCheck()
bool SSPLayoutInfo::shouldEmitSDCheck (const BasicBlock & BB) const
Definition at line 81 of file StackProtector.cpp.
References llvm::BasicBlock::getTerminator(), and llvm::isa().
Referenced by llvm::StackProtector::shouldEmitSDCheck().
Friends And Related Symbol Documentation
SSPLayoutAnalysis
friend class SSPLayoutAnalysis friend
Definition at line 36 of file StackProtector.h.
StackProtector
friend class StackProtector friend
Definition at line 37 of file StackProtector.h.
StackProtectorPass
friend class StackProtectorPass friend
Definition at line 35 of file StackProtector.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/StackProtector.h
lib/CodeGen/StackProtector.cpp