LLVM: llvm::objcopy::elf::GroupSection Class Reference
llvm::objcopy::elf::GroupSection Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Types
template<class T >
using ConstRange
Public Member Functions
GroupSection (ArrayRef< uint8_t > Data)
void setSymTab (const SymbolTableSection *SymTabSec)
void setSymbol (Symbol *S)
void setFlagWord (ELF::Elf32_Word W)
void addMember (SectionBase *Sec)
Error accept (SectionVisitor &) const override
Error accept (MutableSectionVisitor &Visitor) override
void finalize () override
Error removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove) override
Error removeSymbols (function_ref< bool(const Symbol &)> ToRemove) override
void markSymbols () override
void replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > &FromTo) override
void onRemove () override
ConstRange< SectionBase > members () const
Public Member Functions inherited from llvm::objcopy::elf::SectionBase
SectionBase ()=default
SectionBase (const SectionBase &)=default
virtual ~SectionBase ()=default
virtual Error initialize (SectionTableRef SecTable)
virtual bool hasContents () const
virtual void restoreSymTabLink (SymbolTableSection &)
Static Public Member Functions
static bool classof (const SectionBase *S)
Public Attributes
ArrayRef< uint8_t > Contents
Public Attributes inherited from llvm::objcopy::elf::SectionBase
std::string Name
Segment * ParentSegment = nullptr
uint64_t HeaderOffset = 0
uint32_t Index = 0
uint32_t OriginalIndex = 0
uint64_t OriginalFlags = 0
uint64_t OriginalType = ELF::SHT_NULL
uint64_t OriginalOffset = std::numeric_limits<uint64_t>::max()
uint64_t Addr = 0
uint64_t Align = 1
uint32_t EntrySize = 0
uint64_t Flags = 0
uint64_t Info = 0
uint64_t Link = ELF::SHN_UNDEF
uint64_t NameIndex = 0
uint64_t Offset = 0
uint64_t Size = 0
uint64_t Type = ELF::SHT_NULL
ArrayRef< uint8_t > OriginalData
bool HasSymbol = false
Detailed Description
Definition at line 936 of file ELFObject.h.
Member Typedef Documentation
ConstRange
template<class T > using llvm::objcopy::elf::GroupSection::ConstRange
Initial value:
 iterator_range<
      pointee_iterator<typename llvm::SmallVector<T *, 3>::const_iterator>>
Definition at line 945 of file ELFObject.h.
Constructor & Destructor Documentation
GroupSection()
llvm::objcopy::elf::GroupSection::GroupSection (ArrayRef< uint8_t > Data) inline explicit
Definition at line 951 of file ELFObject.h.
Member Function Documentation
accept() [1/2]
Error GroupSection::accept (MutableSectionVisitor & Visitor) override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 1214 of file ELFObject.cpp.
References llvm::objcopy::elf::MutableSectionVisitor::visit().
accept() [2/2]
Error GroupSection::accept (SectionVisitor & Visitor) const override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 1210 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionVisitor::visit().
addMember()
void llvm::objcopy::elf::GroupSection::addMember (SectionBase * Sec) inline
Definition at line 956 of file ELFObject.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
classof()
static bool llvm::objcopy::elf::GroupSection::classof (const SectionBase * S) inline static
Definition at line 974 of file ELFObject.h.
References llvm::objcopy::elf::SectionBase::OriginalType, and llvm::ELF::SHT_GROUP.
finalize()
void GroupSection::finalize () override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 1081 of file ELFObject.cpp.
References llvm::objcopy::elf::Symbol::Binding, llvm::ELF::GRP_COMDAT, llvm::objcopy::elf::SectionBase::Index, llvm::objcopy::elf::Symbol::Index, llvm::objcopy::elf::SectionBase::Link, and llvm::ELF::STB_LOCAL.
markSymbols()
void GroupSection::markSymbols () override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 1117 of file ELFObject.cpp.
References llvm::objcopy::elf::Symbol::Referenced.
members()
ConstRange< SectionBase > llvm::objcopy::elf::GroupSection::members () const inline
Definition at line 970 of file ELFObject.h.
References llvm::make_pointee_range().
Referenced by llvm::objcopy::elf::Object::removeSections().
onRemove()
void GroupSection::onRemove () override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 1129 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::Flags.
removeSectionReferences()
Error GroupSection::removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 1092 of file ELFObject.cpp.
References llvm::createStringError(), llvm::erase_if(), llvm::invalid_argument, llvm::objcopy::elf::SectionBase::Name, llvm::Error::success(), and ToRemove.
removeSymbols()
Error GroupSection::removeSymbols (function_ref< bool(const Symbol &)> ToRemove) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 1108 of file ELFObject.cpp.
References llvm::createStringError(), llvm::invalid_argument, llvm::objcopy::elf::Symbol::Name, llvm::Error::success(), and ToRemove.
replaceSectionReferences()
void GroupSection::replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > & FromTo) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 1122 of file ELFObject.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
setFlagWord()
void llvm::objcopy::elf::GroupSection::setFlagWord (ELF::Elf32_Word W) inline
Definition at line 955 of file ELFObject.h.
setSymbol()
void llvm::objcopy::elf::GroupSection::setSymbol (Symbol * S) inline
Definition at line 954 of file ELFObject.h.
References Sym.
setSymTab()
void llvm::objcopy::elf::GroupSection::setSymTab (const SymbolTableSection * SymTabSec) inline
Definition at line 953 of file ELFObject.h.
Member Data Documentation
Contents
ArrayRef<uint8_t> llvm::objcopy::elf::GroupSection::Contents
Definition at line 949 of file ELFObject.h.
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp