LLVM: llvm::BPFPreserveStaticOffsetPass Class Reference
llvm::BPFPreserveStaticOffsetPass Class Reference
#include "Target/BPF/BPF.h"
Public Member Functions
BPFPreserveStaticOffsetPass (bool AllowPartial)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< BPFPreserveStaticOffsetPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
static std::pair< GetElementPtrInst *, LoadInst * > reconstructLoad (CallInst *Call)
static std::pair< GetElementPtrInst *, StoreInst * > reconstructStore (CallInst *Call)
Static Public Member Functions inherited from llvm::PassInfoMixin< BPFPreserveStaticOffsetPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 82 of file BPF.h.
Constructor & Destructor Documentation
BPFPreserveStaticOffsetPass()
llvm::BPFPreserveStaticOffsetPass::BPFPreserveStaticOffsetPass (bool AllowPartial) inline
Definition at line 87 of file BPF.h.
Member Function Documentation
isRequired()
static bool llvm::BPFPreserveStaticOffsetPass::isRequired () inline static
Definition at line 90 of file BPF.h.
reconstructLoad()
std::pair< GetElementPtrInst *, LoadInst * > BPFPreserveStaticOffsetPass::reconstructLoad (CallInst * Call) static
Definition at line 304 of file BPFPreserveStaticOffset.cpp.
References Align, Call, GEP, llvm::CallBase::getFunctionType(), llvm::FunctionType::getReturnType(), reconstructCommon(), and reconstructGEP().
Referenced by rewriteAccessChain(), and unrollGEPLoad().
reconstructStore()
std::pair< GetElementPtrInst *, StoreInst * > BPFPreserveStaticOffsetPass::reconstructStore (CallInst * Call) static
Definition at line 315 of file BPFPreserveStaticOffset.cpp.
References Call, GEP, llvm::User::getOperand(), reconstructCommon(), and reconstructGEP().
Referenced by rewriteAccessChain(), and unrollGEPStore().
run()
PreservedAnalyses llvm::BPFPreserveStaticOffsetPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 677 of file BPFPreserveStaticOffset.cpp.
References llvm::PreservedAnalyses::all(), F, llvm::PreservedAnalyses::none(), and rewriteFunction().
The documentation for this class was generated from the following files:
lib/Target/BPF/BPF.h
lib/Target/BPF/BPFPreserveStaticOffset.cpp