LLVM: llvm::ShuffleBlockStrategy Class Reference
llvm::ShuffleBlockStrategy Class Reference
Strategy to randomly select a block and shuffle the operations without affecting data dependency.
#include "llvm/FuzzMutate/IRMutator.h"
Public Member Functions
uint64_t getWeight (size_t CurrentSize, size_t MaxSize, uint64_t CurrentWeight) override
Provide a weight to bias towards choosing this strategy for a mutation.
void mutate (BasicBlock &BB, RandomIRBuilder &IB) override
Public Member Functions inherited from llvm::IRMutationStrategy
virtual ~IRMutationStrategy ()=default
virtual void mutate (Module &M, RandomIRBuilder &IB)
virtual void mutate (Function &F, RandomIRBuilder &IB)
virtual void mutate (Instruction &I, RandomIRBuilder &IB)
Detailed Description
Strategy to randomly select a block and shuffle the operations without affecting data dependency.
Definition at line 194 of file IRMutator.h.
Member Function Documentation
getWeight()
uint64_t llvm::ShuffleBlockStrategy::getWeight (size_t CurrentSize, size_t MaxSize, uint64_t CurrentWeight) inline override virtual
Provide a weight to bias towards choosing this strategy for a mutation.
The value of the weight is arbitrary, but a good default is "the number of distinct ways in which this strategy can mutate a unit". This can also be used to prefer strategies that shrink the overall size of the result when we start getting close to MaxSize.
Implements llvm::IRMutationStrategy.
Definition at line 196 of file IRMutator.h.
mutate()
void ShuffleBlockStrategy::mutate (BasicBlock & BB, RandomIRBuilder & IB) override virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 593 of file IRMutator.cpp.
References llvm::dyn_cast(), llvm::SmallSet< T, N, C >::empty(), llvm::BasicBlock::getFirstInsertionPt(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::BasicBlock::getTerminator(), I, llvm::SmallSet< T, N, C >::insert(), llvm::make_early_inc_range(), llvm::make_range(), llvm::makeSampler(), P, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Value::users().
The documentation for this class was generated from the following files:
include/llvm/FuzzMutate/IRMutator.h
lib/FuzzMutate/IRMutator.cpp