LLVM: llvm::orc::MachOBuilder< MachOTraits > Class Template Reference
llvm::orc::MachOBuilder< MachOTraits > Class Template Reference
#include "llvm/ExecutionEngine/Orc/MachOBuilder.h"
Classes
struct Reloc
class RelocTarget
struct Section
struct SectionContent
struct Segment
Public Types
using StringId = size_t
Public Member Functions
MachOBuilder (size_t PageSize)
template<MachO::LoadCommandType LCType, typename... ArgTs>
MachOBuilderLoadCommand< LCType > & addLoadCommand (ArgTs &&...Args)
StringId addString (StringRef Str)
Segment & addSegment (StringRef SegName)
RelocTarget addSymbol (StringRef Name, uint8_t Type, uint8_t Sect, uint16_t Desc, typename MachOTraits::UIntPtr Value)
size_t layout ()
void write (MutableArrayRef< char > Buffer)
Public Attributes
MachOTraits::Header Header
Detailed Description
template<typename MachOTraits>
class llvm::orc::MachOBuilder< MachOTraits >
Definition at line 149 of file MachOBuilder.h.
Member Typedef Documentation
StringId
template<typename MachOTraits > using llvm::orc::MachOBuilder< MachOTraits >::StringId = size_t
Definition at line 168 of file MachOBuilder.h.
Constructor & Destructor Documentation
MachOBuilder()
template<typename MachOTraits > llvm::orc::MachOBuilder< MachOTraits >::MachOBuilder (size_t PageSize) inline
Definition at line 296 of file MachOBuilder.h.
Member Function Documentation
addLoadCommand()
template<typename MachOTraits > template<MachO::LoadCommandType LCType, typename... ArgTs> MachOBuilderLoadCommand< LCType > & llvm::orc::MachOBuilder< MachOTraits >::addLoadCommand (ArgTs &&... Args) inline
Definition at line 302 of file MachOBuilder.h.
Referenced by llvm::orc::MachOBuilder< MachOTraits >::layout().
addSegment()
template<typename MachOTraits > Segment & llvm::orc::MachOBuilder< MachOTraits >::addSegment (StringRef SegName) inline
Definition at line 318 of file MachOBuilder.h.
addString()
template<typename MachOTraits > StringId llvm::orc::MachOBuilder< MachOTraits >::addString (StringRef Str) inline
Definition at line 312 of file MachOBuilder.h.
References llvm::orc::MachOBuilder< MachOTraits >::addString().
Referenced by llvm::orc::MachOBuilder< MachOTraits >::addString(), and llvm::orc::MachOBuilder< MachOTraits >::addSymbol().
addSymbol()
template<typename MachOTraits > RelocTarget llvm::orc::MachOBuilder< MachOTraits >::addSymbol (StringRef Name, uint8_t Type, uint8_t Sect, uint16_t Desc, typename MachOTraits::UIntPtr Value) inline
Definition at line 323 of file MachOBuilder.h.
References llvm::orc::MachOBuilder< MachOTraits >::addString(), Name, Sym, Type, and llvm::Value.
layout()
template<typename MachOTraits > size_t llvm::orc::MachOBuilder< MachOTraits >::layout () inline
Definition at line 340 of file MachOBuilder.h.
References llvm::orc::MachOBuilder< MachOTraits >::addLoadCommand(), llvm::alignTo(), llvm::orc::MachOBuilder< MachOTraits >::Header, llvm::MachO::MH_OBJECT, llvm::Offset, and Sym.
write()
template<typename MachOTraits > void llvm::orc::MachOBuilder< MachOTraits >::write (MutableArrayRef< char > Buffer) inline
Definition at line 444 of file MachOBuilder.h.
References llvm::Offset.
Member Data Documentation
Header
template<typename MachOTraits > MachOTraits::Header llvm::orc::MachOBuilder< MachOTraits >::Header
Definition at line 455 of file MachOBuilder.h.
Referenced by llvm::orc::MachOBuilder< MachOTraits >::layout().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/MachOBuilder.h