LLVM: llvm::IndexListEntry Class Reference
llvm::IndexListEntry Class Reference
This class represents an entry in the slot index list held in the SlotIndexes pass.
#include "llvm/CodeGen/SlotIndexes.h"
Public Member Functions
IndexListEntry (MachineInstr *mi, unsigned index)
MachineInstr * getInstr () const
void setInstr (MachineInstr *mi)
unsigned getIndex () const
void setIndex (unsigned index)
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< IndexListEntry, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< IndexListEntry, Options... >::type >, ilist_detail::compute_node_options< IndexListEntry, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< IndexListEntry, Options... >::type::parent_ty * getParent () const
ilist_detail::compute_node_options< IndexListEntry, Options... >::type::parent_ty * getParent ()
void setParent (ilist_detail::compute_node_options< IndexListEntry, Options... >::type::parent_ty *Parent)
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< IndexListEntry, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< IndexListEntry, Options... >::type >
ilist_node_impl ()=default
Detailed Description
This class represents an entry in the slot index list held in the SlotIndexes pass.
It should not be used directly. See the SlotIndex & SlotIndexes classes for the public interface to this information.
Definition at line 46 of file SlotIndexes.h.
Constructor & Destructor Documentation
IndexListEntry()
llvm::IndexListEntry::IndexListEntry (MachineInstr * mi, unsigned index) inline
Definition at line 51 of file SlotIndexes.h.
Member Function Documentation
getIndex()
unsigned llvm::IndexListEntry::getIndex () const inline
Definition at line 58 of file SlotIndexes.h.
Referenced by llvm::SlotIndex::getApproxInstrDistance(), and llvm::SlotIndex::print().
getInstr()
MachineInstr * llvm::IndexListEntry::getInstr () const inline
Definition at line 53 of file SlotIndexes.h.
Referenced by llvm::SlotIndexes::getInstructionFromIndex(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), and llvm::SlotIndexes::replaceMachineInstrInMaps().
setIndex()
void llvm::IndexListEntry::setIndex (unsigned index) inline
Definition at line 59 of file SlotIndexes.h.
setInstr()
void llvm::IndexListEntry::setInstr (MachineInstr * mi) inline
Definition at line 54 of file SlotIndexes.h.
Referenced by llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), and llvm::SlotIndexes::replaceMachineInstrInMaps().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/SlotIndexes.h