LLVM: llvm::jitlink::aarch32::GOTBuilder Class Reference
llvm::jitlink::aarch32::GOTBuilder Class Reference
Populate a Global Offset Table from edges that request it.
#include "llvm/ExecutionEngine/JITLink/aarch32.h"
Public Member Functions
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Public Member Functions inherited from llvm::jitlink::TableManager< GOTBuilder >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Static Public Member Functions
static StringRef getSectionName ()
Detailed Description
Populate a Global Offset Table from edges that request it.
Definition at line 331 of file aarch32.h.
Member Function Documentation
createEntry()
Symbol & llvm::jitlink::aarch32::GOTBuilder::createEntry (LinkGraph & G, Symbol & Target)
Definition at line 713 of file aarch32.cpp.
References llvm::jitlink::aarch32::allocPointer(), B, llvm::jitlink::aarch32::Data_Pointer32, G, getSectionName(), llvm::jitlink::aarch32::GOTEntryInit, and llvm::orc::Read.
getSectionName()
static StringRef llvm::jitlink::aarch32::GOTBuilder::getSectionName () inline static
Definition at line 333 of file aarch32.h.
Referenced by createEntry().
visitEdge()
bool llvm::jitlink::aarch32::GOTBuilder::visitEdge (LinkGraph & G, Block * B, Edge & E)
Definition at line 722 of file aarch32.cpp.
References B, llvm::jitlink::aarch32::Data_Delta32, llvm::jitlink::aarch32::Data_RequestGOTAndTransformToDelta32, llvm::dbgs(), llvm::formatv(), G, llvm::jitlink::TableManager< GOTBuilder >::getEntryForTarget(), llvm::jitlink::Edge::Invalid, and LLVM_DEBUG.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/aarch32.h
lib/ExecutionEngine/JITLink/aarch32.cpp