LLVM: llvm::ConstantPool Class Reference
llvm::ConstantPool Class Reference
#include "llvm/MC/ConstantPools.h"
Public Member Functions
ConstantPool ()=default
const MCExpr * addEntry (const MCExpr *Value, MCContext &Context, unsigned Size, SMLoc Loc)
void emitEntries (MCStreamer &Streamer)
bool empty ()
void clearCache ()
Detailed Description
Definition at line 43 of file ConstantPools.h.
Constructor & Destructor Documentation
ConstantPool()
llvm::ConstantPool::ConstantPool () default
Member Function Documentation
addEntry()
const MCExpr * ConstantPool::addEntry (const MCExpr * Value, MCContext & Context, unsigned Size, SMLoc Loc)
Definition at line 39 of file ConstantPools.cpp.
References llvm::CallingConv::C, llvm::MCSymbolRefExpr::create(), llvm::dyn_cast(), llvm::MCSymbolRefExpr::getSymbol(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and Size.
Referenced by llvm::CSKYTargetStreamer::addConstantPoolEntry(), and llvm::AssemblerConstantPools::addEntry().
clearCache()
void ConstantPool::clearCache ()
Definition at line 72 of file ConstantPools.cpp.
Referenced by llvm::CSKYTargetStreamer::emitCurrentConstantPool().
emitEntries()
void ConstantPool::emitEntries (MCStreamer & Streamer)
Definition at line 26 of file ConstantPools.cpp.
References Align, llvm::MCStreamer::emitDataRegion(), llvm::MCStreamer::emitLabel(), llvm::MCStreamer::emitValue(), llvm::MCStreamer::emitValueToAlignment(), llvm::SmallVectorBase< Size_T >::empty(), llvm::MCDR_DataRegion, and llvm::MCDR_DataRegionEnd.
empty()
bool ConstantPool::empty ()
Definition at line 70 of file ConstantPools.cpp.
References llvm::SmallVectorBase< Size_T >::empty().
The documentation for this class was generated from the following files:
include/llvm/MC/ConstantPools.h
lib/MC/ConstantPools.cpp