LLVM: llvm::GraphWriter< GraphType > Class Template Reference
llvm::GraphWriter< GraphType > Class Template Reference
#include "llvm/Support/GraphWriter.h"
Public Member Functions
GraphWriter (raw_ostream &o, const GraphType &g, bool SN)
void writeGraph (const std::string &Title="")
void writeHeader (const std::string &Title)
void writeFooter ()
void writeNodes ()
bool isNodeHidden (NodeRef Node)
void writeNode (NodeRef Node)
void writeEdge (NodeRef Node, unsigned edgeidx, child_iterator EI)
void emitSimpleNode (const void *ID, const std::string &Attr, const std::string &Label, unsigned NumEdgeSources=0, const std::vector< std::string > *EdgeSourceLabels=nullptr)
emitSimpleNode - Outputs a simple (non-record) node
void emitEdge (const void *SrcNodeID, int SrcNodePort, const void *DestNodeID, int DestNodePort, const std::string &Attrs)
emitEdge - Output an edge from a simple node into the graph...
raw_ostream & getOStream ()
getOStream - Get the raw output stream into the graph file.
Detailed Description
template<typename GraphType>
class llvm::GraphWriter< GraphType >
Definition at line 64 of file GraphWriter.h.
Constructor & Destructor Documentation
GraphWriter()
template<typename GraphType > llvm::GraphWriter< GraphType >::GraphWriter (raw_ostream & o, const GraphType & g, bool SN) inline
Definition at line 120 of file GraphWriter.h.
References G, and llvm::DefaultDOTGraphTraits::renderNodesUsingHTML().
Member Function Documentation
emitEdge()
template<typename GraphType > void llvm::GraphWriter< GraphType >::emitEdge (const void * SrcNodeID, int SrcNodePort, const void * DestNodeID, int DestNodePort, const std::string & Attrs) inline
emitEdge - Output an edge from a simple node into the graph...
Definition at line 333 of file GraphWriter.h.
References llvm::DefaultDOTGraphTraits::hasEdgeDestLabels().
Referenced by llvm::DOTGraphTraits< SelectionDAG * >::addCustomGraphFeatures(), llvm::ScheduleDAGSDNodes::getCustomGraphFeatures(), and llvm::GraphWriter< GraphType >::writeEdge().
emitSimpleNode()
template<typename GraphType > void llvm::GraphWriter< GraphType >::emitSimpleNode (const void * ID, const std::string & Attr, const std::string & Label, unsigned NumEdgeSources = 0, const std::vector< std::string > * EdgeSourceLabels = nullptr) inline
emitSimpleNode - Outputs a simple (non-record) node
Definition at line 310 of file GraphWriter.h.
References llvm::DOT::EscapeString().
Referenced by llvm::DOTGraphTraits< SelectionDAG * >::addCustomGraphFeatures(), and llvm::ScheduleDAGSDNodes::getCustomGraphFeatures().
getOStream()
template<typename GraphType > raw_ostream & llvm::GraphWriter< GraphType >::getOStream () inline
getOStream - Get the raw output stream into the graph file.
Useful to write fancy things using addCustomGraphFeatures().
Definition at line 353 of file GraphWriter.h.
Referenced by llvm::DOTGraphTraits< RegionInfo * >::addCustomGraphFeatures(), and llvm::DOTGraphTraits< RegionInfo * >::printRegionCluster().
isNodeHidden()
template<typename GraphType > bool llvm::GraphWriter< GraphType >::isNodeHidden (NodeRef Node) inline
Definition at line 172 of file GraphWriter.h.
References G, and llvm::DefaultDOTGraphTraits::isNodeHidden().
Referenced by llvm::GraphWriter< GraphType >::writeNodes().
writeEdge()
template<typename GraphType > void llvm::GraphWriter< GraphType >::writeEdge (NodeRef Node, unsigned edgeidx, child_iterator EI) inline
Definition at line 288 of file GraphWriter.h.
References llvm::DefaultDOTGraphTraits::edgeTargetsEdgeSource(), llvm::GraphWriter< GraphType >::emitEdge(), G, llvm::DefaultDOTGraphTraits::getEdgeAttributes(), llvm::DefaultDOTGraphTraits::getEdgeSourceLabel(), llvm::DefaultDOTGraphTraits::getEdgeTarget(), and llvm::Offset.
Referenced by llvm::GraphWriter< GraphType >::writeNode().
writeFooter()
template<typename GraphType > void llvm::GraphWriter< GraphType >::writeFooter () inline
Definition at line 160 of file GraphWriter.h.
Referenced by llvm::GraphWriter< GraphType >::writeGraph().
writeGraph()
template<typename GraphType > void llvm::GraphWriter< GraphType >::writeGraph (const std::string & Title = "") inline
Definition at line 125 of file GraphWriter.h.
References llvm::DefaultDOTGraphTraits::addCustomGraphFeatures(), G, llvm::GraphWriter< GraphType >::writeFooter(), llvm::GraphWriter< GraphType >::writeHeader(), and llvm::GraphWriter< GraphType >::writeNodes().
writeHeader()
template<typename GraphType > void llvm::GraphWriter< GraphType >::writeHeader (const std::string & Title) inline
Definition at line 139 of file GraphWriter.h.
References llvm::DOT::EscapeString(), G, llvm::DefaultDOTGraphTraits::getGraphName(), llvm::DefaultDOTGraphTraits::getGraphProperties(), and llvm::DefaultDOTGraphTraits::renderGraphFromBottomUp().
Referenced by llvm::GraphWriter< GraphType >::writeGraph().
writeNode()
template<typename GraphType > void llvm::GraphWriter< GraphType >::writeNode (NodeRef Node) inline
Definition at line 174 of file GraphWriter.h.
References llvm::DOT::EscapeString(), G, llvm::DefaultDOTGraphTraits::getEdgeDestLabel(), llvm::DefaultDOTGraphTraits::getNodeAttributes(), llvm::DefaultDOTGraphTraits::getNodeDescription(), llvm::DefaultDOTGraphTraits::getNodeIdentifierLabel(), llvm::DefaultDOTGraphTraits::getNodeLabel(), llvm::DefaultDOTGraphTraits::hasEdgeDestLabels(), llvm::DefaultDOTGraphTraits::isNodeHidden(), llvm::DefaultDOTGraphTraits::numEdgeDestLabels(), llvm::DefaultDOTGraphTraits::renderGraphFromBottomUp(), and llvm::GraphWriter< GraphType >::writeEdge().
Referenced by llvm::GraphWriter< GraphType >::writeNodes().
writeNodes()
template<typename GraphType > void llvm::GraphWriter< GraphType >::writeNodes () inline
Definition at line 165 of file GraphWriter.h.
References G, llvm::GraphWriter< GraphType >::isNodeHidden(), nodes, and llvm::GraphWriter< GraphType >::writeNode().
Referenced by llvm::GraphWriter< GraphType >::writeGraph().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/ScheduleDAG.h
include/llvm/Support/GraphWriter.h