LLVM: llvm::symbolize::SourceCode Class Reference
llvm::symbolize::SourceCode Class Reference
Public Member Functions
SourceCode (StringRef FileName, int64_t Line, int Lines, const std::optional< StringRef > &EmbeddedSource=std::optional< StringRef >())
void format (raw_ostream &OS)
Public Attributes
const int64_t Line
const int Lines
const int64_t FirstLine
const int64_t LastLine
const std::optional< StringRef > PrunedSource
Detailed Description
Definition at line 31 of file DIPrinter.cpp.
Constructor & Destructor Documentation
SourceCode()
llvm::symbolize::SourceCode::SourceCode (StringRef FileName, int64_t Line, int Lines, const std::optional< StringRef > & EmbeddedSource = std::optional<StringRef>()) inline
Definition at line 76 of file DIPrinter.cpp.
Member Function Documentation
format()
void llvm::symbolize::SourceCode::format (raw_ostream & OS) inline
Definition at line 84 of file DIPrinter.cpp.
References llvm::StringRef::drop_back(), FirstLine, llvm::format_decimal(), LastLine, Line, llvm::StringRef::npos, OS, PrunedSource, llvm::String, and llvm::StringRef::substr().
Referenced by llvm::symbolize::JSONPrinter::print(), and llvm::symbolize::PlainPrinterBase::printContext().
Member Data Documentation
FirstLine
const int64_t llvm::symbolize::SourceCode::FirstLine
Definition at line 72 of file DIPrinter.cpp.
Referenced by format().
LastLine
const int64_t llvm::symbolize::SourceCode::LastLine
Definition at line 73 of file DIPrinter.cpp.
Referenced by format().
Line
const int64_t llvm::symbolize::SourceCode::Line
Definition at line 70 of file DIPrinter.cpp.
Referenced by format().
Lines
const int llvm::symbolize::SourceCode::Lines
Definition at line 71 of file DIPrinter.cpp.
PrunedSource
const std::optional<StringRef> llvm::symbolize::SourceCode::PrunedSource
Definition at line 74 of file DIPrinter.cpp.
Referenced by format().
The documentation for this class was generated from the following file:
lib/DebugInfo/Symbolize/DIPrinter.cpp