LLVM: llvm::GISelKnownBits Class Reference
llvm::GISelKnownBits Class Reference
#include "llvm/CodeGen/GlobalISel/GISelKnownBits.h"
Public Member Functions
GISelKnownBits (MachineFunction &MF, unsigned MaxDepth=6)
virtual ~GISelKnownBits ()=default
const MachineFunction & getMachineFunction () const
const DataLayout & getDataLayout () const
virtual void computeKnownBitsImpl (Register R, KnownBits &Known, const APInt &DemandedElts, unsigned Depth=0)
unsigned computeNumSignBits (Register R, const APInt &DemandedElts, unsigned Depth=0)
unsigned computeNumSignBits (Register R, unsigned Depth=0)
KnownBits getKnownBits (Register R)
KnownBits getKnownBits (Register R, const APInt &DemandedElts, unsigned Depth=0)
KnownBits getKnownBits (MachineInstr &MI)
APInt getKnownZeroes (Register R)
APInt getKnownOnes (Register R)
bool maskedValueIsZero (Register Val, const APInt &Mask)
bool signBitIsZero (Register Op)
Align computeKnownAlignment (Register R, unsigned Depth=0)
void erasingInstr (MachineInstr &MI) override
An instruction is about to be erased.
void createdInstr (MachineInstr &MI) override
An instruction has been created and inserted into the function.
void changingInstr (MachineInstr &MI) override
This instruction is about to be mutated in some way.
void changedInstr (MachineInstr &MI) override
This instruction was mutated in some way.
Public Member Functions inherited from llvm::GISelChangeObserver
virtual ~GISelChangeObserver ()=default
void changingAllUsesOfReg (const MachineRegisterInfo &MRI, Register Reg)
All the instructions using the given register are being changed.
void finishedChangingAllUsesOfReg ()
All instructions reported as changing by changingAllUsesOfReg() have finished being changed.
Static Public Member Functions
static void computeKnownBitsForAlignment (KnownBits &Known, Align Alignment)
Protected Member Functions
unsigned getMaxDepth () const
Detailed Description
Definition at line 29 of file GISelKnownBits.h.
Constructor & Destructor Documentation
GISelKnownBits()
llvm::GISelKnownBits::GISelKnownBits (MachineFunction & MF, unsigned MaxDepth = 6)
~GISelKnownBits()
virtual llvm::GISelKnownBits::~GISelKnownBits () virtual default
Member Function Documentation
changedInstr()
void llvm::GISelKnownBits::changedInstr (MachineInstr & MI) inline override virtual
This instruction was mutated in some way.
Implements llvm::GISelChangeObserver.
Definition at line 99 of file GISelKnownBits.h.
changingInstr()
void llvm::GISelKnownBits::changingInstr (MachineInstr & MI) inline override virtual
This instruction is about to be mutated in some way.
Implements llvm::GISelChangeObserver.
Definition at line 98 of file GISelKnownBits.h.
computeKnownAlignment()
Align GISelKnownBits::computeKnownAlignment (Register R, unsigned Depth = 0)
Returns
The known alignment for the pointer-like value R.
Definition at line 39 of file GISelKnownBits.cpp.
References Align, llvm::TargetLowering::computeKnownAlignForTargetInstr(), computeKnownAlignment(), llvm::Depth, llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineRegisterInfo::getVRegDef(), and MI.
Referenced by computeKnownAlignment().
computeKnownBitsForAlignment()
static void llvm::GISelKnownBits::computeKnownBitsForAlignment (KnownBits & Known, Align Alignment) inline static
Definition at line 86 of file GISelKnownBits.h.
References llvm::Log2(), llvm::APInt::setLowBits(), and llvm::KnownBits::Zero.
computeKnownBitsImpl()
void GISelKnownBits::computeKnownBitsImpl (Register R, KnownBits & Known, const APInt & DemandedElts, unsigned Depth = 0) virtual
Definition at line 144 of file GISelKnownBits.cpp.
References llvm::KnownBits::anyext(), llvm::KnownBits::ashr(), assert(), llvm::bit_width(), llvm::BitWidth, llvm::KnownBits::byteSwap(), llvm::APInt::clearLowBits(), llvm::KnownBits::computeForAddSub(), llvm::TargetLowering::computeKnownBitsForFrameIndex(), llvm::TargetLowering::computeKnownBitsForTargetInstr(), llvm::computeKnownBitsFromRangeMetadata(), computeKnownBitsImpl(), llvm::KnownBits::countMaxLeadingZeros(), llvm::KnownBits::countMaxPopulation(), llvm::dbgs(), llvm::Depth, dumpResult(), extractBits(), llvm::KnownBits::extractBits(), llvm::APInt::getAllOnes(), llvm::KnownBits::getBitWidth(), llvm::TargetLoweringBase::getBooleanContents(), llvm::DataLayout::getIndexSizeInBits(), getMaxDepth(), llvm::MachineMemOperand::getMemoryType(), llvm::MachineMemOperand::getRanges(), getReg(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::MachineRegisterInfo::getVRegDef(), I, llvm::KnownBits::insertBits(), llvm::KnownBits::intersectWith(), llvm::DataLayout::isNonIntegralAddressSpace(), llvm::KnownBits::isUnknown(), llvm::LLT::isValid(), llvm::LLT::isVector(), llvm::Register::isVirtual(), LLVM_DEBUG, llvm::Log2_64(), llvm::KnownBits::lshr(), llvm::KnownBits::makeConstant(), MI, llvm::KnownBits::mul(), llvm::KnownBits::One, llvm::KnownBits::reverseBits(), llvm::APInt::setAllBits(), llvm::APInt::setBitsFrom(), llvm::APInt::setLowBits(), llvm::KnownBits::sext(), llvm::KnownBits::sextInReg(), llvm::KnownBits::shl(), llvm::KnownBits::smax(), llvm::KnownBits::smin(), llvm::KnownBits::umax(), llvm::KnownBits::umin(), llvm::KnownBits::Zero, llvm::TargetLoweringBase::ZeroOrOneBooleanContent, llvm::KnownBits::zext(), and llvm::KnownBits::zextOrTrunc().
Referenced by llvm::SITargetLowering::computeKnownBitsForTargetInstr(), computeKnownBitsImpl(), and getKnownBits().
computeNumSignBits() [1/2]
unsigned GISelKnownBits::computeNumSignBits (Register R, const APInt & DemandedElts, unsigned Depth = 0)
Definition at line 656 of file GISelKnownBits.cpp.
References llvm::cast(), computeNumSignBits(), llvm::TargetLowering::computeNumSignBitsForTargetInstr(), computeNumSignBitsFromRangeMetadata(), llvm::Depth, llvm::TargetLoweringBase::getBooleanContents(), getDataLayout(), getKnownBits(), getMaxDepth(), llvm::LLT::getScalarSizeInBits(), llvm::MachineMemOperand::getSizeInBits(), llvm::MachineRegisterInfo::getType(), llvm::LocationSize::getValue(), llvm::MachineRegisterInfo::getVRegDef(), llvm::KnownBits::isNegative(), llvm::KnownBits::isNonNegative(), llvm::LLT::isValid(), llvm::LLT::isVector(), MI, llvm::KnownBits::One, llvm::KnownBits::Zero, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, and llvm::TargetLoweringBase::ZeroOrOneBooleanContent.
Referenced by computeNumSignBits(), computeNumSignBits(), llvm::CombinerHelper::matchAddOverflow(), llvm::CombinerHelper::matchRedundantSExtInReg(), and llvm::LegalizationArtifactCombiner::tryCombineSExt().
computeNumSignBits() [2/2]
unsigned GISelKnownBits::computeNumSignBits (Register R, unsigned Depth = 0)
Definition at line 840 of file GISelKnownBits.cpp.
References computeNumSignBits(), llvm::Depth, llvm::APInt::getAllOnes(), and llvm::MachineRegisterInfo::getType().
createdInstr()
void llvm::GISelKnownBits::createdInstr (MachineInstr & MI) inline override virtual
An instruction has been created and inserted into the function.
Note that the instruction might not be a fully fledged instruction at this point and won't be if the MachineFunction::Delegate is calling it. This is because the delegate only sees the construction of the MachineInstr before operands have been added.
Implements llvm::GISelChangeObserver.
Definition at line 97 of file GISelKnownBits.h.
erasingInstr()
void llvm::GISelKnownBits::erasingInstr (MachineInstr & MI) inline override virtual
An instruction is about to be erased.
Implements llvm::GISelChangeObserver.
Definition at line 96 of file GISelKnownBits.h.
getDataLayout()
const DataLayout & llvm::GISelKnownBits::getDataLayout () const inline
Definition at line 53 of file GISelKnownBits.h.
References DL.
Referenced by computeNumSignBits().
getKnownBits() [1/3]
KnownBits GISelKnownBits::getKnownBits (MachineInstr & MI)
Definition at line 61 of file GISelKnownBits.cpp.
References assert(), getKnownBits(), and MI.
getKnownBits() [2/3]
KnownBits GISelKnownBits::getKnownBits (Register R)
Definition at line 67 of file GISelKnownBits.cpp.
References llvm::APInt::getAllOnes(), getKnownBits(), and llvm::MachineRegisterInfo::getType().
Referenced by llvm::AMDGPULegalizerInfo::buildMultiply(), llvm::CombinerHelper::buildUDivUsingMul(), computeNumSignBits(), getKnownBits(), getKnownBits(), getKnownOnes(), getKnownZeroes(), llvm::isKnownToBeAPowerOfTwo(), maskedValueIsZero(), llvm::CombinerHelper::matchAddOverflow(), llvm::CombinerHelper::matchCombineTruncOfShift(), llvm::CombinerHelper::matchCombineZextTrunc(), llvm::CombinerHelper::matchICmpToLHSKnownBits(), llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), llvm::CombinerHelper::matchRedundantAnd(), and llvm::CombinerHelper::matchRedundantOr().
getKnownBits() [3/3]
KnownBits GISelKnownBits::getKnownBits (Register R, const APInt & DemandedElts, unsigned Depth = 0)
Definition at line 77 of file GISelKnownBits.cpp.
References assert(), computeKnownBitsImpl(), and llvm::Depth.
getKnownOnes()
APInt GISelKnownBits::getKnownOnes (Register R)
Definition at line 98 of file GISelKnownBits.cpp.
References getKnownBits(), and llvm::KnownBits::One.
getKnownZeroes()
APInt GISelKnownBits::getKnownZeroes (Register R)
Definition at line 94 of file GISelKnownBits.cpp.
References getKnownBits(), and llvm::KnownBits::Zero.
Referenced by llvm::CombinerHelper::matchCombineShlOfExtend(), and llvm::LegalizationArtifactCombiner::tryCombineZExt().
getMachineFunction()
const MachineFunction & llvm::GISelKnownBits::getMachineFunction () const inline
Definition at line 49 of file GISelKnownBits.h.
Referenced by llvm::SITargetLowering::computeKnownAlignForTargetInstr(), and knownBitsForWorkitemID().
getMaxDepth()
unsigned llvm::GISelKnownBits::getMaxDepth () const inline protected
Definition at line 102 of file GISelKnownBits.h.
Referenced by computeKnownBitsImpl(), and computeNumSignBits().
maskedValueIsZero()
bool llvm::GISelKnownBits::maskedValueIsZero (Register Val, const APInt & Mask) inline
Returns
true if 'V & Mask' is known to be zero in DemandedElts. We use this predicate to simplify operations downstream. Mask is known to be zero for bits that V cannot have.
Definition at line 78 of file GISelKnownBits.h.
References getKnownBits().
Referenced by signBitIsZero().
signBitIsZero()
bool GISelKnownBits::signBitIsZero (Register Op)
Returns
true if the sign bit of Op is known to be zero. We use this predicate to simplify operations downstream.
Definition at line 88 of file GISelKnownBits.cpp.
References llvm::BitWidth, llvm::APInt::getSignMask(), llvm::MachineRegisterInfo::getType(), and maskedValueIsZero().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/GlobalISel/GISelKnownBits.h
lib/CodeGen/GlobalISel/GISelKnownBits.cpp