LLVM: llvm::ARMMCExpr Class Reference
llvm::ARMMCExpr Class Reference
#include "Target/ARM/MCTargetDesc/ARMMCExpr.h"
Public Types
enum VariantKind {
VK_ARM_None , VK_ARM_HI16 , VK_ARM_LO16 , VK_ARM_HI_8_15 ,
VK_ARM_HI_0_7 , VK_ARM_LO_8_15 , VK_ARM_LO_0_7
}
Public Types inherited from llvm::MCExpr
enum ExprKind : uint8_t {
Binary , Constant , SymbolRef , Unary ,
Target
}
Public Member Functions
void printImpl (raw_ostream &OS, const MCAsmInfo *MAI) const override
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCFixup *Fixup) const override
void visitUsedExpr (MCStreamer &Streamer) const override
MCFragment * findAssociatedFragment () const override
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const override
Accessors
VariantKind getKind () const
getOpcode - Get the kind of this expression.
const MCExpr * getSubExpr () const
getSubExpr - Get the child of this expression.
Public Member Functions inherited from llvm::MCTargetExpr
virtual bool isEqualTo (const MCExpr *x) const
virtual bool inlineAssignedExpr () const
Public Member Functions inherited from llvm::MCExpr
MCExpr (const MCExpr &)=delete
MCExpr & operator= (const MCExpr &)=delete
ExprKind getKind () const
SMLoc getLoc () const
void print (raw_ostream &OS, const MCAsmInfo *MAI, bool InParens=false) const
void dump () const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm, const SectionAddrMap &Addrs) const
Try to evaluate the expression to an absolute value.
bool evaluateAsAbsolute (int64_t &Res) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool evaluateAsAbsolute (int64_t &Res, const MCAssembler *Asm) const
bool evaluateKnownAbsolute (int64_t &Res, const MCAssembler &Asm) const
Aggressive variant of evaluateAsRelocatable when relocations are unavailable (e.g.
bool evaluateAsRelocatable (MCValue &Res, const MCAssembler *Asm, const MCFixup *Fixup) const
Try to evaluate the expression to a relocatable value, i.e.
bool evaluateAsValue (MCValue &Res, const MCAssembler &Asm) const
Try to evaluate the expression to the form (a - b + constant) where neither a nor b are variables.
MCFragment * findAssociatedFragment () const
Find the "associated section" for this expression, which is currently defined as the absolute section for constants, or otherwise the section associated with the first defined symbol in the expression.
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const ARMMCExpr * create (VariantKind Kind, const MCExpr *Expr, MCContext &Ctx)
static const ARMMCExpr * createUpper16 (const MCExpr *Expr, MCContext &Ctx)
static const ARMMCExpr * createLower16 (const MCExpr *Expr, MCContext &Ctx)
static const ARMMCExpr * createUpper8_15 (const MCExpr *Expr, MCContext &Ctx)
static const ARMMCExpr * createUpper0_7 (const MCExpr *Expr, MCContext &Ctx)
static const ARMMCExpr * createLower8_15 (const MCExpr *Expr, MCContext &Ctx)
static const ARMMCExpr * createLower0_7 (const MCExpr *Expr, MCContext &Ctx)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()=default
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind Kind, SMLoc Loc, unsigned SubclassData=0)
bool evaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCFixup *Fixup, const SectionAddrMap *Addrs, bool InSet) const
unsigned getSubclassData () const
Detailed Description
Definition at line 16 of file ARMMCExpr.h.
Member Enumeration Documentation
VariantKind
enum llvm::ARMMCExpr::VariantKind
Enumerator
VK_ARM_None
VK_ARM_HI16
VK_ARM_LO16
VK_ARM_HI_8_15
VK_ARM_HI_0_7
VK_ARM_LO_8_15
VK_ARM_LO_0_7
Definition at line 18 of file ARMMCExpr.h.
Member Function Documentation
classof()
static bool llvm::ARMMCExpr::classof (const MCExpr * E) inline static
Definition at line 96 of file ARMMCExpr.h.
References llvm::MCExpr::Target.
create()
const ARMMCExpr * ARMMCExpr::create (VariantKind Kind, const MCExpr * Expr, MCContext & Ctx) static
Definition at line 17 of file ARMMCExpr.cpp.
Referenced by createLower0_7(), createLower16(), createLower8_15(), createUpper0_7(), createUpper16(), and createUpper8_15().
createLower0_7()
static const ARMMCExpr * llvm::ARMMCExpr::createLower0_7 (const MCExpr * Expr, MCContext & Ctx) inline static
Definition at line 67 of file ARMMCExpr.h.
References create(), and VK_ARM_LO_0_7.
createLower16()
static const ARMMCExpr * llvm::ARMMCExpr::createLower16 (const MCExpr * Expr, MCContext & Ctx) inline static
Definition at line 51 of file ARMMCExpr.h.
References create(), and VK_ARM_LO16.
Referenced by llvm::ARMAsmPrinter::emitInstruction().
createLower8_15()
static const ARMMCExpr * llvm::ARMMCExpr::createLower8_15 (const MCExpr * Expr, MCContext & Ctx) inline static
Definition at line 63 of file ARMMCExpr.h.
References create(), and VK_ARM_LO_8_15.
createUpper0_7()
static const ARMMCExpr * llvm::ARMMCExpr::createUpper0_7 (const MCExpr * Expr, MCContext & Ctx) inline static
Definition at line 59 of file ARMMCExpr.h.
References create(), and VK_ARM_HI_0_7.
createUpper16()
static const ARMMCExpr * llvm::ARMMCExpr::createUpper16 (const MCExpr * Expr, MCContext & Ctx) inline static
Definition at line 47 of file ARMMCExpr.h.
References create(), and VK_ARM_HI16.
Referenced by llvm::ARMAsmPrinter::emitInstruction().
createUpper8_15()
static const ARMMCExpr * llvm::ARMMCExpr::createUpper8_15 (const MCExpr * Expr, MCContext & Ctx) inline static
Definition at line 55 of file ARMMCExpr.h.
References create(), and VK_ARM_HI_8_15.
evaluateAsRelocatableImpl()
bool llvm::ARMMCExpr::evaluateAsRelocatableImpl (MCValue & Res, const MCAssembler * Asm, const MCFixup * Fixup) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 84 of file ARMMCExpr.h.
findAssociatedFragment()
MCFragment * llvm::ARMMCExpr::findAssociatedFragment () const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 89 of file ARMMCExpr.h.
References llvm::MCExpr::findAssociatedFragment(), and getSubExpr().
fixELFSymbolsInTLSFixups()
void llvm::ARMMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const inline override virtual
Implements llvm::MCTargetExpr.
Definition at line 94 of file ARMMCExpr.h.
getKind()
VariantKind llvm::ARMMCExpr::getKind () const inline
getOpcode - Get the kind of this expression.
Definition at line 76 of file ARMMCExpr.h.
Referenced by isThumbI8Relocation().
getSubExpr()
const MCExpr * llvm::ARMMCExpr::getSubExpr () const inline
getSubExpr - Get the child of this expression.
Definition at line 79 of file ARMMCExpr.h.
Referenced by findAssociatedFragment(), printImpl(), and visitUsedExpr().
printImpl()
void ARMMCExpr::printImpl (raw_ostream & OS, const MCAsmInfo * MAI) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 22 of file ARMMCExpr.cpp.
References llvm::MCExpr::getKind(), getSubExpr(), llvm_unreachable, OS, llvm::MCExpr::print(), llvm::MCExpr::SymbolRef, VK_ARM_HI16, VK_ARM_HI_0_7, VK_ARM_HI_8_15, VK_ARM_LO16, VK_ARM_LO_0_7, and VK_ARM_LO_8_15.
visitUsedExpr()
void ARMMCExpr::visitUsedExpr (MCStreamer & Streamer) const override virtual
Implements llvm::MCTargetExpr.
Definition at line 53 of file ARMMCExpr.cpp.
References getSubExpr(), and llvm::MCStreamer::visitUsedExpr().
The documentation for this class was generated from the following files:
lib/Target/ARM/MCTargetDesc/ARMMCExpr.h
lib/Target/ARM/MCTargetDesc/ARMMCExpr.cpp