LLVM: llvm::sandboxir::Constant Class Reference
llvm::sandboxir::Constant Class Reference
#include "llvm/SandboxIR/SandboxIR.h"
Public Member Functions
sandboxir::Context & getParent () const
unsigned getUseOperandNo (const Use &Use) const final
\Returns the operand index of Use.
void verify () const final
Should crash if there is something wrong with the instruction.
void dump (raw_ostream &OS) const override
LLVM_DUMP_METHOD void dump () const override
Public Member Functions inherited from llvm::sandboxir::User
virtual op_iterator op_begin ()
virtual op_iterator op_end ()
virtual const_op_iterator op_begin () const
virtual const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
Value * getOperand (unsigned OpIdx) const
Use getOperandUse (unsigned OpIdx) const
\Returns the operand edge for OpIdx.
virtual unsigned getNumOperands () const
virtual void setOperand (unsigned OperandIdx, Value *Operand)
bool replaceUsesOfWith (Value *FromV, Value *ToV)
Replaces any operands that match FromV with ToV.
void verify () const override
Should crash if there is something wrong with the instruction.
void dumpCommonHeader (raw_ostream &OS) const final
void dump (raw_ostream &OS) const override
LLVM_DUMP_METHOD void dump () const override
Public Member Functions inherited from llvm::sandboxir::Value
virtual ~Value ()=default
ClassID getSubclassID () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
user_iterator user_begin ()
user_iterator user_end ()
const_user_iterator user_begin () const
const_user_iterator user_end () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
unsigned getNumUses () const
\Returns the number of user edges (not necessarily to unique users).
bool hasNUsesOrMore (unsigned Num) const
Return true if this value has N uses or more.
bool hasNUses (unsigned Num) const
Return true if this Value has exactly N uses.
Type * getType () const
Context & getContext () const
void replaceUsesWithIf (Value *OtherV, llvm::function_ref< bool(const Use &)> ShouldReplace)
void replaceAllUsesWith (Value *Other)
StringRef getName () const
\Returns the LLVM IR name of the bottom-most LLVM value.
std::string getUid () const
Returns the unique id in the form 'SB<number>.' like 'SB1.'.
void dumpCommonFooter (raw_ostream &OS) const
void dumpCommonPrefix (raw_ostream &OS) const
void dumpCommonSuffix (raw_ostream &OS) const
void printAsOperandCommon (raw_ostream &OS) const
Static Public Member Functions
static Constant * createInt (Type *Ty, uint64_t V, Context &Ctx, bool IsSigned=false)
static bool classof (const sandboxir::Value *From)
For isa/dyn_cast.
Static Public Member Functions inherited from llvm::sandboxir::User
static bool classof (const Value *From)
For isa/dyn_cast.
Friends
class Context
raw_ostream & operator<< (raw_ostream &OS, const sandboxir::Constant &SBC)
Additional Inherited Members
Public Types inherited from llvm::sandboxir::User
using op_iterator = OperandUseIterator
using const_op_iterator = OperandUseIterator
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::sandboxir::Value
enum class ClassID : unsigned { DEF_VALUE , DEF_USER , DEF_INSTR }
using use_iterator = UserUseIterator
using const_use_iterator = UserUseIterator
using user_iterator = mapped_iterator<sandboxir::UserUseIterator, UseToUser>
using const_user_iterator = user_iterator
Protected Member Functions inherited from llvm::sandboxir::User
User (ClassID ID, llvm::Value *V, Context &Ctx)
Use getOperandUseDefault (unsigned OpIdx, bool Verify) const
\Returns the Use edge that corresponds to OpIdx.
unsigned getUseOperandNoDefault (const Use &Use) const
The default implementation works only for single-LLVMIR-instruction Users and only if they match exactly the LLVM instruction.
void verifyUserOfLLVMUse (const llvm::Use &Use) const
Protected Member Functions inherited from llvm::sandboxir::Value
void clearValue ()
Value (ClassID SubclassID, llvm::Value *Val, Context &Ctx)
Static Protected Member Functions inherited from llvm::sandboxir::Value
static const char * getSubclassIDStr (ClassID ID)
Protected Attributes inherited from llvm::sandboxir::Value
ClassID SubclassID
For isa/dyn_cast.
unsigned UID
A unique ID used for forming the name (used for debugging).
llvm::Value * Val = nullptr
The LLVM Value that corresponds to this SandboxIR Value.
Context & Ctx
All values point to the context.
Detailed Description
Definition at line 407 of file SandboxIR.h.
Member Function Documentation
classof()
static bool llvm::sandboxir::Constant::classof (const sandboxir::Value * From) inline static
For isa/dyn_cast.
Definition at line 419 of file SandboxIR.h.
References From.
createInt()
Constant * Constant::createInt (Type * Ty, uint64_t V, Context & Ctx, bool IsSigned = false) static
Definition at line 642 of file SandboxIR.cpp.
dump() [1/2]
void Constant::dump () const override virtual
Implements llvm::sandboxir::Value.
Definition at line 654 of file SandboxIR.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void Constant::dump (raw_ostream & OS) const override virtual
Implements llvm::sandboxir::Value.
Definition at line 649 of file SandboxIR.cpp.
References llvm::sandboxir::Value::dumpCommonPrefix(), llvm::sandboxir::Value::dumpCommonSuffix(), and OS.
getParent()
sandboxir::Context & llvm::sandboxir::Constant::getParent () const inline
Definition at line 423 of file SandboxIR.h.
References llvm::sandboxir::Value::getContext().
getUseOperandNo()
unsigned llvm::sandboxir::Constant::getUseOperandNo (const Use & Use) const inline final virtual
\Returns the operand index of Use.
Implements llvm::sandboxir::User.
Definition at line 424 of file SandboxIR.h.
References llvm::sandboxir::User::getUseOperandNoDefault().
verify()
void llvm::sandboxir::Constant::verify () const inline final virtual
Should crash if there is something wrong with the instruction.
Implements llvm::sandboxir::Value.
Definition at line 428 of file SandboxIR.h.
References assert(), llvm::isa(), and llvm::sandboxir::Value::Val.
Friends And Related Symbol Documentation
Context
friend class Context friend
Definition at line 410 of file SandboxIR.h.
operator<<
raw_ostream & operator<< (raw_ostream & OS, const sandboxir::Constant & SBC) friend
Definition at line 431 of file SandboxIR.h.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/SandboxIR.h
lib/SandboxIR/SandboxIR.cpp