LLVM: llvm::orc::ExecutorNativePlatform Class Reference
llvm::orc::ExecutorNativePlatform Class Reference
Configure the LLJIT instance to use the ORC runtime and the detected native target for the executor.
#include "llvm/ExecutionEngine/Orc/LLJIT.h"
Public Member Functions
ExecutorNativePlatform (std::string OrcRuntimePath)
Set up using path to Orc runtime.
ExecutorNativePlatform (std::unique_ptr< MemoryBuffer > OrcRuntimeMB)
Set up using the given memory buffer.
ExecutorNativePlatform & addVCRuntime (std::string VCRuntimePath, bool StaticVCRuntime)
Add a path to the VC runtime.
Expected< JITDylibSP > operator() (LLJIT &J)
Detailed Description
Configure the LLJIT instance to use the ORC runtime and the detected native target for the executor.
Definition at line 574 of file LLJIT.h.
Constructor & Destructor Documentation
ExecutorNativePlatform() [1/2]
llvm::orc::ExecutorNativePlatform::ExecutorNativePlatform (std::string OrcRuntimePath) inline
Set up using path to Orc runtime.
Definition at line 577 of file LLJIT.h.
ExecutorNativePlatform() [2/2]
llvm::orc::ExecutorNativePlatform::ExecutorNativePlatform (std::unique_ptr< MemoryBuffer > OrcRuntimeMB) inline
Set up using the given memory buffer.
Definition at line 581 of file LLJIT.h.
Member Function Documentation
addVCRuntime()
ExecutorNativePlatform & llvm::orc::ExecutorNativePlatform::addVCRuntime (std::string VCRuntimePath, bool StaticVCRuntime) inline
Add a path to the VC runtime.
Definition at line 587 of file LLJIT.h.
operator()()
Expected< JITDylibSP > llvm::orc::ExecutorNativePlatform::operator() (LLJIT & J)
Definition at line 1111 of file LLJIT.cpp.
References A, llvm::Triple::COFF, llvm::orc::COFFPlatform::Create(), llvm::orc::ELFNixPlatform::Create(), llvm::orc::MachOPlatform::Create(), llvm::orc::StaticLibraryDefinitionGenerator::Create(), llvm::dyn_cast(), llvm::Triple::ELF, llvm::errorOrToExpected(), G, llvm::orc::LLJIT::getExecutionSession(), llvm::MemoryBuffer::getFile(), llvm::orc::LLJIT::getObjLinkingLayer(), llvm::orc::LLJIT::getProcessSymbolsJITDylib(), llvm::orc::LLJIT::getTargetTriple(), llvm::inconvertibleErrorCode(), llvm::Triple::MachO, llvm::make_error(), P, and llvm::orc::LLJIT::setPlatformSupport().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/LLJIT.h
lib/ExecutionEngine/Orc/LLJIT.cpp