LLVM: llvm::PGOCtxProfLoweringPass Class Reference
llvm::PGOCtxProfLoweringPass Class Reference
#include "llvm/Transforms/Instrumentation/PGOCtxProfLowering.h"
Public Member Functions
PGOCtxProfLoweringPass ()=default
PreservedAnalyses run (Module &M, ModuleAnalysisManager &MAM)
Public Member Functions inherited from llvm::PassInfoMixin< PGOCtxProfLoweringPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isContextualIRPGOEnabled ()
Static Public Member Functions inherited from llvm::PassInfoMixin< PGOCtxProfLoweringPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 19 of file PGOCtxProfLowering.h.
Constructor & Destructor Documentation
PGOCtxProfLoweringPass()
llvm::PGOCtxProfLoweringPass::PGOCtxProfLoweringPass () explicit default
Member Function Documentation
isContextualIRPGOEnabled()
bool PGOCtxProfLoweringPass::isContextualIRPGOEnabled () static
Definition at line 33 of file PGOCtxProfLowering.cpp.
References ContextRoots.
Referenced by annotateAllFunctions(), llvm::PassBuilder::buildModuleSimplificationPipeline(), InstrumentAllFunctions(), instrumentOneFunc(), isValueProfilingDisabled(), and shouldInstrumentEntryBB().
run()
PreservedAnalyses PGOCtxProfLoweringPass::run (Module & M, ModuleAnalysisManager & MAM)
Definition at line 193 of file PGOCtxProfLowering.cpp.
References llvm::PreservedAnalyses::all(), Changed, F, MAM, and llvm::PreservedAnalyses::none().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/PGOCtxProfLowering.h
lib/Transforms/Instrumentation/PGOCtxProfLowering.cpp