LLVM: llvm::AssumptionCache Class Reference
llvm::AssumptionCache Class Reference
A cache of @llvm.assume calls within a function.
#include "llvm/Analysis/AssumptionCache.h"
Classes
struct ResultElem
Public Types
enum : unsigned { ExprResultIdx = std::numeric_limits<unsigned>::max() }
Value of ResultElem::Index indicating that the argument to the call of the llvm.assume.
Public Member Functions
AssumptionCache (Function &F, TargetTransformInfo *TTI=nullptr)
Construct an AssumptionCache from a function by scanning all of its instructions.
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &)
This cache is designed to be self-updating and so it should never be invalidated.
void registerAssumption (AssumeInst *CI)
Add an @llvm.assume intrinsic to this function's cache.
void unregisterAssumption (AssumeInst *CI)
Remove an @llvm.assume intrinsic from this function's cache if it has been added to the cache earlier.
void updateAffectedValues (AssumeInst *CI)
Update the cache of values being affected by this assumption (i.e.
void clear ()
Clear the cache of @llvm.assume intrinsics for a function.
MutableArrayRef< ResultElem > assumptions ()
Access the list of assumption handles currently tracked for this function.
MutableArrayRef< ResultElem > assumptionsFor (const Value *V)
Access the list of assumptions which affect this value.
Detailed Description
A cache of @llvm.assume calls within a function.
This cache provides fast lookup of assumptions within a function by caching them and amortizing the cost of scanning for them across all queries. Passes that create new assumptions are required to call registerAssumption() to register any new @llvm.assume calls that they create. Deletions of @llvm.assume calls do not require special handling.
Definition at line 42 of file AssumptionCache.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : unsigned
Value of ResultElem::Index indicating that the argument to the call of the llvm.assume.
Enumerator
ExprResultIdx
Definition at line 46 of file AssumptionCache.h.
Constructor & Destructor Documentation
AssumptionCache()
llvm::AssumptionCache::AssumptionCache (Function & F, TargetTransformInfo * TTI = nullptr) inline
Construct an AssumptionCache from a function by scanning all of its instructions.
Definition at line 109 of file AssumptionCache.h.
References F.
Referenced by llvm::AssumptionAnalysis::run().
Member Function Documentation
assumptions()
MutableArrayRef< ResultElem > llvm::AssumptionCache::assumptions () inline
Access the list of assumption handles currently tracked for this function.
Note that these produce weak handles that may be null. The caller must handle that case. FIXME: We should replace this with pointee_iterator<filter_iterator<...>> when we can write that to filter out the null values. Then caller code will become simpler.
Definition at line 150 of file AssumptionCache.h.
Referenced by llvm::PredicateInfoBuilder::buildPredicateInfo(), llvm::ScalarEvolution::LoopGuards::collect(), llvm::CodeMetrics::collectEphemeralValues(), llvm::CodeMetrics::collectEphemeralValues(), llvm::ScalarEvolution::getZeroExtendExprImpl(), llvm::ScalarEvolution::isBasicBlockEntryGuardedByCond(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), llvm::AssumptionPrinterPass::run(), llvm::AlignmentFromAssumptionsPass::runImpl(), and llvm::CodeExtractor::verifyAssumptionCache().
assumptionsFor()
MutableArrayRef< ResultElem > llvm::AssumptionCache::assumptionsFor (const Value * V) inline
Access the list of assumptions which affect this value.
Definition at line 157 of file AssumptionCache.h.
References llvm::MutableArrayRef().
Referenced by llvm::computeConstantRange(), llvm::computeKnownBitsFromContext(), computeKnownFPClassFromContext(), llvm::getKnowledgeForValue(), isKnownNonZeroFromAssume(), simplifyICmpWithDominatingAssume(), and llvm::CodeExtractor::verifyAssumptionCache().
clear()
void llvm::AssumptionCache::clear () inline
Clear the cache of @llvm.assume intrinsics for a function.
It will be re-scanned the next time it is requested.
Definition at line 136 of file AssumptionCache.h.
References llvm::SmallVectorImpl< T >::clear().
invalidate()
bool llvm::AssumptionCache::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator &) inline
This cache is designed to be self-updating and so it should never be invalidated.
Definition at line 114 of file AssumptionCache.h.
registerAssumption()
void AssumptionCache::registerAssumption (AssumeInst * CI)
Add an @llvm.assume intrinsic to this function's cache.
The call passed in must be an instruction within this function and must not already be in the cache.
Definition at line 187 of file AssumptionCache.cpp.
References assert(), llvm::cast(), ExprResultIdx, F, getParent(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::match(), and updateAffectedValues().
Referenced by AddAlignmentAssumptions(), addAssumeNonNull(), buildClonedLoopBlocks(), combineInstructionsOverFunction(), FoldCondBranchOnValueKnownInPredecessorImpl(), removeUndefIntroducingPredecessor(), llvm::salvageKnowledge(), llvm::InnerLoopVectorizer::scalarizeInstruction(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), and llvm::InstCombinerImpl::visitCallInst().
unregisterAssumption()
void AssumptionCache::unregisterAssumption (AssumeInst * CI)
Remove an @llvm.assume intrinsic from this function's cache if it has been added to the cache earlier.
Definition at line 112 of file AssumptionCache.cpp.
References assert(), llvm::AssumptionCache::ResultElem::Assume, llvm::erase(), and findAffectedValues().
Referenced by llvm::CodeExtractor::extractCodeRegion().
updateAffectedValues()
void AssumptionCache::updateAffectedValues (AssumeInst * CI)
Update the cache of values being affected by this assumption (i.e.
the values about which this assumption provides information).
Definition at line 99 of file AssumptionCache.cpp.
References llvm::AssumptionCache::ResultElem::Assume, findAffectedValues(), llvm::AssumptionCache::ResultElem::Index, and llvm::none_of().
Referenced by registerAssumption(), and llvm::InstCombinerImpl::visitCallInst().
The documentation for this class was generated from the following files:
include/llvm/Analysis/AssumptionCache.h
lib/Analysis/AssumptionCache.cpp