LLVM: llvm::DelayedMCExprs Class Reference
llvm::DelayedMCExprs Class Reference
#include "Target/AMDGPU/Utils/AMDGPUDelayedMCExpr.h"
Public Member Functions
bool resolveDelayedExpressions ()
void assignDocNode (msgpack::DocNode &DN, msgpack::Type Type, const MCExpr *ExprValue)
void clear ()
bool empty ()
Detailed Description
Definition at line 18 of file AMDGPUDelayedMCExpr.h.
Member Function Documentation
assignDocNode()
void DelayedMCExprs::assignDocNode (msgpack::DocNode & DN, msgpack::Type Type, const MCExpr * ExprValue)
Definition at line 30 of file AMDGPUDelayedMCExpr.cpp.
References llvm::MCExpr::evaluateAsRelocatable(), getNode(), and llvm::MCValue::isAbsolute().
Referenced by llvm::AMDGPUPALMetadata::setFunctionNumUsedSgprs(), llvm::AMDGPUPALMetadata::setFunctionNumUsedVgprs(), llvm::AMDGPUPALMetadata::setHwStage(), and llvm::AMDGPUPALMetadata::setRegister().
clear()
void DelayedMCExprs::clear ()
Definition at line 59 of file AMDGPUDelayedMCExpr.cpp.
Referenced by llvm::AMDGPUPALMetadata::reset().
empty()
bool DelayedMCExprs::empty ()
Definition at line 61 of file AMDGPUDelayedMCExpr.cpp.
Referenced by llvm::AMDGPUPALMetadata::resolvedAllMCExpr().
resolveDelayedExpressions()
bool DelayedMCExprs::resolveDelayedExpressions ()
Definition at line 43 of file AMDGPUDelayedMCExpr.cpp.
References llvm::MCExpr::evaluateAsRelocatable(), getNode(), and llvm::MCValue::isAbsolute().
Referenced by llvm::AMDGPUPALMetadata::toBlob(), and llvm::AMDGPUPALMetadata::toString().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/Utils/AMDGPUDelayedMCExpr.h
lib/Target/AMDGPU/Utils/AMDGPUDelayedMCExpr.cpp