LLVM: llvm::OutputCategoryAggregator Class Reference
llvm::OutputCategoryAggregator Class Reference
#include "llvm/DebugInfo/DWARF/DWARFVerifier.h"
Public Member Functions
OutputCategoryAggregator (bool includeDetail=false)
void ShowDetail (bool showDetail)
size_t GetNumCategories () const
void Report (StringRef s, std::function< void()> detailCallback)
void EnumerateResults (std::function< void(StringRef, unsigned)> handleCounts)
Detailed Description
Definition at line 33 of file DWARFVerifier.h.
Constructor & Destructor Documentation
OutputCategoryAggregator()
llvm::OutputCategoryAggregator::OutputCategoryAggregator (bool includeDetail = false) inline
Definition at line 39 of file DWARFVerifier.h.
Member Function Documentation
EnumerateResults()
void OutputCategoryAggregator::EnumerateResults (std::function< void(StringRef, unsigned)> handleCounts)
Definition at line 2025 of file DWARFVerifier.cpp.
References llvm::count(), and name.
Referenced by llvm::DWARFVerifier::summarize().
GetNumCategories()
size_t llvm::OutputCategoryAggregator::GetNumCategories () const inline
Definition at line 42 of file DWARFVerifier.h.
Referenced by llvm::DWARFVerifier::summarize().
Report()
void OutputCategoryAggregator::Report (StringRef s, std::function< void()> detailCallback)
Definition at line 2018 of file DWARFVerifier.cpp.
Referenced by llvm::DWARFVerifier::verifyDebugStrOffsets().
ShowDetail()
void llvm::OutputCategoryAggregator::ShowDetail (bool showDetail) inline
Definition at line 41 of file DWARFVerifier.h.
Referenced by llvm::DWARFVerifier::DWARFVerifier().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFVerifier.h
lib/DebugInfo/DWARF/DWARFVerifier.cpp