LLVM: llvm::logicalview::LVSymbolVisitor Class Reference
llvm::logicalview::LVSymbolVisitor Class Reference final
#include "llvm/DebugInfo/LogicalView/Readers/LVCodeViewVisitor.h"
Public Member Functions
LVSymbolVisitor (LVCodeViewReader *Reader, ScopedPrinter &W, LVLogicalVisitor *LogicalVisitor, LazyRandomTypeCollection &Types, LazyRandomTypeCollection &Ids, LVSymbolVisitorDelegate *ObjDelegate, LVShared *Shared)
Error visitSymbolBegin (CVSymbol &Record) override
Error visitSymbolBegin (CVSymbol &Record, uint32_t Offset) override
Paired begin/end actions for all symbols.
Error visitSymbolEnd (CVSymbol &Record) override
Error visitUnknownSymbol (CVSymbol &Record) override
Action to take on unknown symbols. By default, they are ignored.
Error visitKnownRecord (CVSymbol &Record, BlockSym &Block) override
Error visitKnownRecord (CVSymbol &Record, BPRelativeSym &Local) override
Error visitKnownRecord (CVSymbol &Record, BuildInfoSym &BuildInfo) override
Error visitKnownRecord (CVSymbol &Record, Compile2Sym &Compile2) override
Error visitKnownRecord (CVSymbol &Record, Compile3Sym &Compile3) override
Error visitKnownRecord (CVSymbol &Record, ConstantSym &Constant) override
Error visitKnownRecord (CVSymbol &Record, DataSym &Data) override
Error visitKnownRecord (CVSymbol &Record, DefRangeFramePointerRelFullScopeSym &DefRangeFramePointerRelFullScope) override
Error visitKnownRecord (CVSymbol &Record, DefRangeFramePointerRelSym &DefRangeFramePointerRel) override
Error visitKnownRecord (CVSymbol &Record, DefRangeRegisterRelSym &DefRangeRegisterRel) override
Error visitKnownRecord (CVSymbol &Record, DefRangeRegisterSym &DefRangeRegister) override
Error visitKnownRecord (CVSymbol &Record, DefRangeSubfieldRegisterSym &DefRangeSubfieldRegister) override
Error visitKnownRecord (CVSymbol &Record, DefRangeSubfieldSym &DefRangeSubfield) override
Error visitKnownRecord (CVSymbol &Record, DefRangeSym &DefRange) override
Error visitKnownRecord (CVSymbol &Record, FrameProcSym &FrameProc) override
Error visitKnownRecord (CVSymbol &Record, InlineSiteSym &InlineSite) override
Error visitKnownRecord (CVSymbol &Record, LocalSym &Local) override
Error visitKnownRecord (CVSymbol &Record, ObjNameSym &ObjName) override
Error visitKnownRecord (CVSymbol &Record, ProcSym &Proc) override
Error visitKnownRecord (CVSymbol &Record, RegRelativeSym &Local) override
Error visitKnownRecord (CVSymbol &Record, ScopeEndSym &ScopeEnd) override
Error visitKnownRecord (CVSymbol &Record, Thunk32Sym &Thunk) override
Error visitKnownRecord (CVSymbol &Record, UDTSym &UDT) override
Error visitKnownRecord (CVSymbol &Record, UsingNamespaceSym &UN) override
Error visitKnownRecord (CVSymbol &Record, JumpTableSym &JumpTable) override
Error visitKnownRecord (CVSymbol &Record, CallerSym &Caller) override
Public Member Functions inherited from llvm::codeview::SymbolVisitorCallbacks
virtual ~SymbolVisitorCallbacks ()=default
Detailed Description
Definition at line 124 of file LVCodeViewVisitor.h.
Constructor & Destructor Documentation
LVSymbolVisitor()
llvm::logicalview::LVSymbolVisitor::LVSymbolVisitor (LVCodeViewReader * Reader, ScopedPrinter & W, LVLogicalVisitor * LogicalVisitor, LazyRandomTypeCollection & Types, LazyRandomTypeCollection & Ids, LVSymbolVisitorDelegate * ObjDelegate, LVShared * Shared) inline
Definition at line 179 of file LVCodeViewVisitor.h.
References llvm::logicalview::Types.
Member Function Documentation
visitKnownRecord() [1/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, BlockSym & Block) override
Definition at line 790 of file LVCodeViewVisitor.cpp.
References llvm::Block, llvm::LinkageName, LLVM_DEBUG, llvm::logicalview::options(), and llvm::Error::success().
visitKnownRecord() [2/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, BPRelativeSym & Local) override
Definition at line 818 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVElement::getFunctionParent(), llvm::logicalview::LVObject::getParentScope(), LLVM_DEBUG, llvm::logicalview::Local, llvm::codeview::printTypeIndex(), llvm::logicalview::LVElement::setType(), llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::logicalview::LVElement::updateLevel().
visitKnownRecord() [3/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, BuildInfoSym & BuildInfo) override
Definition at line 923 of file LVCodeViewVisitor.cpp.
References llvm::codeview::BuildInfoSym::BuildId, LLVM_DEBUG, llvm::codeview::printTypeIndex(), and llvm::Error::success().
visitKnownRecord() [4/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, CallerSym & Caller) override
Definition at line 1706 of file LVCodeViewVisitor.cpp.
References llvm::pdb::Caller, LLVM_DEBUG, llvm::make_error(), llvm::codeview::printTypeIndex(), and llvm::Error::success().
visitKnownRecord() [5/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, Compile2Sym & Compile2) override
Definition at line 936 of file LVCodeViewVisitor.cpp.
References llvm::codeview::getCompileSym3FlagNames(), llvm::codeview::getCPUTypeNames(), llvm::codeview::Compile2Sym::getFlags(), llvm::codeview::Compile2Sym::getLanguage(), llvm::logicalview::getReader(), llvm::codeview::getSourceLanguageNames(), llvm::logicalview::LVReader::isSystemEntry(), LLVM_DEBUG, llvm::codeview::Compile2Sym::Machine, llvm::logicalview::options(), llvm::logicalview::LVShared::StringRecords, llvm::Error::success(), and llvm::codeview::Compile2Sym::Version.
visitKnownRecord() [6/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, Compile3Sym & Compile3) override
Definition at line 981 of file LVCodeViewVisitor.cpp.
References llvm::codeview::getCompileSym3FlagNames(), llvm::codeview::getCPUTypeNames(), llvm::codeview::Compile3Sym::getFlags(), llvm::codeview::Compile3Sym::getLanguage(), llvm::logicalview::getReader(), llvm::codeview::getSourceLanguageNames(), llvm::logicalview::LVReader::isSystemEntry(), LLVM_DEBUG, llvm::codeview::Compile3Sym::Machine, llvm::logicalview::options(), llvm::logicalview::LVShared::StringRecords, llvm::Error::success(), and llvm::codeview::Compile3Sym::Version.
visitKnownRecord() [7/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, ConstantSym & Constant) override
Definition at line 1026 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, llvm::codeview::printTypeIndex(), llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::Value::Value().
visitKnownRecord() [8/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, DataSym & Data) override
Definition at line 1339 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVScope::addElement(), llvm::Data, llvm::logicalview::getReader(), llvm::LinkageName, LLVM_DEBUG, llvm::logicalview::LVShared::NamespaceDeduction, llvm::logicalview::options(), llvm::codeview::printTypeIndex(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownRecord() [9/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, DefRangeFramePointerRelFullScopeSym & DefRangeFramePointerRelFullScope) override
Definition at line 1044 of file LVCodeViewVisitor.cpp.
References llvm::formatv(), LLVM_DEBUG, llvm::codeview::DefRangeFramePointerRelFullScopeSym::Offset, and llvm::Error::success().
visitKnownRecord() [10/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, DefRangeFramePointerRelSym & DefRangeFramePointerRel) override
Definition at line 1072 of file LVCodeViewVisitor.cpp.
References llvm::formatv(), llvm::codeview::DefRangeFramePointerRelSym::Gaps, llvm::codeview::DefRangeFramePointerRelSym::getRelocationOffset(), llvm::codeview::DefRangeFramePointerRelSym::Hdr, LLVM_DEBUG, llvm::codeview::DefRangeFramePointerRelHeader::Offset, llvm::codeview::DefRangeFramePointerRelSym::Range, llvm::logicalview::Range, and llvm::Error::success().
visitKnownRecord() [11/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, DefRangeRegisterRelSym & DefRangeRegisterRel) override
Definition at line 1110 of file LVCodeViewVisitor.cpp.
References llvm::codeview::DefRangeRegisterRelHeader::BasePointerOffset, llvm::formatv(), llvm::codeview::DefRangeRegisterRelSym::Gaps, llvm::codeview::DefRangeRegisterRelSym::getRelocationOffset(), llvm::codeview::DefRangeRegisterRelSym::hasSpilledUDTMember(), llvm::codeview::DefRangeRegisterRelSym::Hdr, LLVM_DEBUG, llvm::codeview::DefRangeRegisterRelSym::offsetInParent(), llvm::codeview::DefRangeRegisterRelSym::Range, llvm::logicalview::Range, llvm::codeview::DefRangeRegisterRelHeader::Register, and llvm::Error::success().
visitKnownRecord() [12/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, DefRangeRegisterSym & DefRangeRegister) override
Definition at line 1149 of file LVCodeViewVisitor.cpp.
References llvm::formatv(), llvm::codeview::DefRangeRegisterSym::Gaps, llvm::codeview::getRegisterNames(), llvm::codeview::DefRangeRegisterSym::getRelocationOffset(), llvm::codeview::DefRangeRegisterSym::Hdr, LLVM_DEBUG, llvm::codeview::DefRangeRegisterHeader::MayHaveNoName, llvm::codeview::DefRangeRegisterSym::Range, llvm::logicalview::Range, llvm::codeview::DefRangeRegisterHeader::Register, and llvm::Error::success().
visitKnownRecord() [13/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, DefRangeSubfieldRegisterSym & DefRangeSubfieldRegister) override
Definition at line 1184 of file LVCodeViewVisitor.cpp.
References llvm::formatv(), llvm::codeview::DefRangeSubfieldRegisterSym::Gaps, llvm::codeview::getRegisterNames(), llvm::codeview::DefRangeSubfieldRegisterSym::getRelocationOffset(), llvm::codeview::DefRangeSubfieldRegisterSym::Hdr, LLVM_DEBUG, llvm::codeview::DefRangeSubfieldRegisterHeader::MayHaveNoName, llvm::codeview::DefRangeSubfieldRegisterHeader::OffsetInParent, llvm::codeview::DefRangeSubfieldRegisterSym::Range, llvm::logicalview::Range, llvm::codeview::DefRangeSubfieldRegisterHeader::Register, and llvm::Error::success().
visitKnownRecord() [14/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, DefRangeSubfieldSym & DefRangeSubfield) override
Definition at line 1222 of file LVCodeViewVisitor.cpp.
References llvm::consumeError(), llvm::formatv(), llvm::codeview::DefRangeSubfieldSym::Gaps, llvm::codeview::DefRangeSubfieldSym::getRelocationOffset(), LLVM_DEBUG, llvm::make_error(), llvm::codeview::DefRangeSubfieldSym::OffsetInParent, llvm::codeview::DefRangeSubfieldSym::Program, llvm::codeview::DefRangeSubfieldSym::Range, llvm::logicalview::Range, and llvm::Error::success().
visitKnownRecord() [15/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, DefRangeSym & DefRange) override
Definition at line 1265 of file LVCodeViewVisitor.cpp.
References llvm::consumeError(), llvm::formatv(), llvm::codeview::DefRangeSym::Gaps, llvm::codeview::DefRangeSym::getRelocationOffset(), LLVM_DEBUG, llvm::make_error(), llvm::codeview::DefRangeSym::Program, llvm::codeview::DefRangeSym::Range, llvm::logicalview::Range, and llvm::Error::success().
visitKnownRecord() [16/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, FrameProcSym & FrameProc) override
Definition at line 1306 of file LVCodeViewVisitor.cpp.
References llvm::dwarf::DW_INL_declared_inlined, llvm::dwarf::DW_INL_inlined, llvm::codeview::FrameProcSym::Flags, llvm::codeview::FrameProcSym::getLocalFramePtrReg(), llvm::codeview::FrameProcSym::getParamFramePtrReg(), and llvm::Error::success().
visitKnownRecord() [17/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, InlineSiteSym & InlineSite) override
Definition at line 1381 of file LVCodeViewVisitor.cpp.
References llvm::dwarf::DW_INL_inlined, llvm::logicalview::LVElement::getName(), LLVM_DEBUG, llvm::logicalview::Name, llvm::codeview::printTypeIndex(), llvm::logicalview::LVElement::setInlineCode(), llvm::logicalview::LVElement::setReference(), llvm::logicalview::LVObject::setTag(), and llvm::Error::success().
visitKnownRecord() [18/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, JumpTableSym & JumpTable) override
Definition at line 1689 of file LVCodeViewVisitor.cpp.
References llvm::codeview::getJumpTableEntrySizeNames(), LLVM_DEBUG, and llvm::Error::success().
visitKnownRecord() [19/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, LocalSym & Local) override
Definition at line 1417 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVElement::getFunctionParent(), llvm::codeview::getLocalFlagNames(), LLVM_DEBUG, llvm::logicalview::Local, llvm::codeview::printTypeIndex(), llvm::logicalview::LVElement::setType(), llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::logicalview::LVElement::updateLevel().
visitKnownRecord() [20/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, ObjNameSym & ObjName) override
Definition at line 1466 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, llvm::codeview::ObjNameSym::Name, llvm::codeview::ObjNameSym::Signature, and llvm::Error::success().
visitKnownRecord() [21/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, ProcSym & Proc) override
Definition at line 1477 of file LVCodeViewVisitor.cpp.
References llvm::codeview::ProcSym::CodeOffset, llvm::codeview::ProcSym::CodeSize, llvm::demangle(), llvm::codeview::ProcSym::Flags, llvm::logicalview::LVShared::ForwardReferences, llvm::codeview::ProcSym::FunctionType, llvm::logicalview::getInnerComponent(), llvm::codeview::getProcSymFlagNames(), llvm::codeview::ProcSym::getRelocationOffset(), llvm::codeview::TypeIndex::isNoneType(), llvm::codeview::TypeIndex::isSimple(), llvm::LinkageName, LLVM_DEBUG, llvm::make_error(), llvm::codeview::ProcSym::Name, llvm::logicalview::options(), llvm::codeview::printTypeIndex(), llvm::codeview::ProcSym::Segment, llvm::Value::setName(), llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::logicalview::Types.
visitKnownRecord() [22/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, RegRelativeSym & Local) override
Definition at line 873 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVScope::addElement(), llvm::logicalview::LVElement::getFunctionParent(), llvm::logicalview::LVObject::getParentScope(), LLVM_DEBUG, llvm::logicalview::Local, llvm::codeview::printTypeIndex(), llvm::logicalview::LVElement::setType(), llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::logicalview::LVElement::updateLevel().
visitKnownRecord() [23/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, ScopeEndSym & ScopeEnd) override
Definition at line 1621 of file LVCodeViewVisitor.cpp.
References llvm::Error::success().
visitKnownRecord() [24/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, Thunk32Sym & Thunk) override
Definition at line 1628 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, llvm::make_error(), llvm::Value::setName(), llvm::Error::success(), and llvm::pdb::Thunk.
visitKnownRecord() [25/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, UDTSym & UDT) override
Definition at line 1647 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVScope::addElement(), llvm::logicalview::getReader(), llvm::logicalview::getRecordName(), LLVM_DEBUG, llvm::logicalview::LVShared::NamespaceDeduction, llvm::codeview::printTypeIndex(), llvm::pdb::StreamTPI, llvm::Error::success(), llvm::logicalview::Types, and llvm::pdb::UDT.
visitKnownRecord() [26/26]
Error LVSymbolVisitor::visitKnownRecord (CVSymbol & Record, UsingNamespaceSym & UN) override
Definition at line 1682 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, llvm::codeview::UsingNamespaceSym::Name, and llvm::Error::success().
visitSymbolBegin() [1/2]
Error LVSymbolVisitor::visitSymbolBegin (CVSymbol & Record) override virtual
Reimplemented from llvm::codeview::SymbolVisitorCallbacks.
Definition at line 731 of file LVCodeViewVisitor.cpp.
visitSymbolBegin() [2/2]
Error LVSymbolVisitor::visitSymbolBegin (CVSymbol & Record, uint32_t Offset) override virtual
Paired begin/end actions for all symbols.
Receives all record data, including the fixed-length record prefix. visitSymbolBegin() should return the type of the Symbol, or an error if it cannot be determined.
Reimplemented from llvm::codeview::SymbolVisitorCallbacks.
Definition at line 735 of file LVCodeViewVisitor.cpp.
References assert(), llvm::codeview::getSymbolTypeNames(), llvm::logicalview::IsCompileUnit, LLVM_DEBUG, llvm::logicalview::Offset, llvm::logicalview::options(), llvm::Error::success(), llvm::logicalview::LVShared::SymbolKinds, and llvm::codeview::symbolOpensScope().
visitSymbolEnd()
Error LVSymbolVisitor::visitSymbolEnd (CVSymbol & Record) override virtual
Reimplemented from llvm::codeview::SymbolVisitorCallbacks.
Definition at line 772 of file LVCodeViewVisitor.cpp.
References llvm::codeview::getSymbolTypeNames(), LLVM_DEBUG, llvm::Error::success(), and llvm::codeview::symbolEndsScope().
visitUnknownSymbol()
Error LVSymbolVisitor::visitUnknownSymbol (CVSymbol & Record) override virtual
Action to take on unknown symbols. By default, they are ignored.
Reimplemented from llvm::codeview::SymbolVisitorCallbacks.
Definition at line 784 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Readers/LVCodeViewVisitor.h
lib/DebugInfo/LogicalView/Readers/LVCodeViewVisitor.cpp