LLVM: ProvenanceAnalysis Class Reference
ProvenanceAnalysis Class Reference
#include "Transforms/ObjCARC/ProvenanceAnalysis.h"
Public Member Functions
ProvenanceAnalysis ()=default
ProvenanceAnalysis (const ProvenanceAnalysis &)=delete
ProvenanceAnalysis & operator= (const ProvenanceAnalysis &)=delete
void setAA (AAResults *aa)
AAResults * getAA () const
bool related (const Value *A, const Value *B)
void clear ()
Detailed Description
Definition at line 51 of file ProvenanceAnalysis.h.
Constructor & Destructor Documentation
ProvenanceAnalysis() [1/2]
ProvenanceAnalysis::ProvenanceAnalysis () default
ProvenanceAnalysis() [2/2]
ProvenanceAnalysis::ProvenanceAnalysis (const ProvenanceAnalysis &) delete
Member Function Documentation
clear()
void ProvenanceAnalysis::clear () inline
Definition at line 77 of file ProvenanceAnalysis.h.
getAA()
AAResults * ProvenanceAnalysis::getAA () const inline
Definition at line 73 of file ProvenanceAnalysis.h.
Referenced by llvm::objcarc::CanAlterRefCount(), and llvm::objcarc::CanUse().
operator=()
ProvenanceAnalysis & ProvenanceAnalysis::operator= (const ProvenanceAnalysis &) delete
related()
bool ProvenanceAnalysis::related (const Value * A, const Value * B)
Definition at line 159 of file ProvenanceAnalysis.cpp.
References A, B, and llvm::objcarc::GetUnderlyingObjCPtrCached().
Referenced by llvm::objcarc::CanAlterRefCount(), llvm::objcarc::CanUse(), and llvm::PAEvalPass::run().
setAA()
void ProvenanceAnalysis::setAA (AAResults * aa) inline
Definition at line 71 of file ProvenanceAnalysis.h.
References aa.
Referenced by llvm::PAEvalPass::run().
The documentation for this class was generated from the following files:
lib/Transforms/ObjCARC/ProvenanceAnalysis.h
lib/Transforms/ObjCARC/ProvenanceAnalysis.cpp