LLVM: llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass Class Reference
llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass Class Reference
#include "llvm/Passes/CodeGenPassBuilder.h"
Public Member Functions
AddMachinePass (ModulePassManager &MPM, const DerivedT &PB)
~AddMachinePass ()
template<typename PassT >
void operator() (PassT &&Pass, bool Force=false, StringRef Name=PassT::name())
Detailed Description
template<typename DerivedT, typename TargetMachineT>
class llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass
Definition at line 209 of file CodeGenPassBuilder.h.
Constructor & Destructor Documentation
AddMachinePass()
template<typename DerivedT , typename TargetMachineT > llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass::AddMachinePass (ModulePassManager & MPM, const DerivedT & PB) inline
Definition at line 211 of file CodeGenPassBuilder.h.
References MPM, and PB().
~AddMachinePass()
template<typename DerivedT , typename TargetMachineT > llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass::~AddMachinePass () inline
Definition at line 213 of file CodeGenPassBuilder.h.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::createFunctionToMachineFunctionPassAdaptor(), llvm::createModuleToFunctionPassAdaptor(), and llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::isEmpty().
Member Function Documentation
operator()()
template<typename DerivedT , typename TargetMachineT > template<typename PassT > void llvm::CodeGenPassBuilder< DerivedT, TargetMachineT >::AddMachinePass::operator() (PassT && Pass, bool Force = false, StringRef Name = PassT::name()) inline
Definition at line 224 of file CodeGenPassBuilder.h.
References llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::addPass(), llvm::CallingConv::C, llvm::createFunctionToMachineFunctionPassAdaptor(), llvm::createModuleToFunctionPassAdaptor(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::isEmpty(), and Name.
The documentation for this class was generated from the following file:
include/llvm/Passes/CodeGenPassBuilder.h