LLVM: llvm::objcopy::elf::ELFBuilder< ELFT > Class Template Reference
llvm::objcopy::elf::ELFBuilder< ELFT > Class Template Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
ELFBuilder (const ELFObjectFile< ELFT > &ElfObj, Object &Obj, std::optional< StringRef > ExtractPartition)
Error build (bool EnsureSymtab)
Detailed Description
template<class ELFT>
class llvm::objcopy::elf::ELFBuilder< ELFT >
Definition at line 1084 of file ELFObject.h.
Constructor & Destructor Documentation
ELFBuilder()
template<class ELFT > ELFBuilder::ELFBuilder (const ELFObjectFile< ELFT > & ElfObj, Object & Obj, std::optional< StringRef > ExtractPartition)
Definition at line 1411 of file ELFObject.cpp.
References llvm::objcopy::elf::Object::IsMips64EL.
Member Function Documentation
build()
template<class ELFT > Error ELFBuilder::build (bool EnsureSymtab)
Definition at line 1923 of file ELFObject.cpp.
References llvm::object::ELFFile< ELFT >::create(), E, llvm::ELF::EI_ABIVERSION, llvm::ELF::EI_CLASS, llvm::ELF::EI_OSABI, llvm::ELF::ELFCLASS64, llvm::Expected< T >::takeError(), and llvm::dwarf::toStringRef().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp