LLVM: llvm::objcopy::wasm::Reader Class Reference
llvm::objcopy::wasm::Reader Class Reference
#include "ObjCopy/wasm/WasmReader.h"
Public Member Functions
Reader (const object::WasmObjectFile &O)
Expected< std::unique_ptr< Object > > create () const
Detailed Description
Definition at line 18 of file WasmReader.h.
Constructor & Destructor Documentation
Reader()
llvm::objcopy::wasm::Reader::Reader (const object::WasmObjectFile & O) inline explicit
Definition at line 20 of file WasmReader.h.
Member Function Documentation
create()
Expected< std::unique_ptr< Object > > llvm::objcopy::wasm::Reader::create () const
Definition at line 18 of file WasmReader.cpp.
References llvm::object::WasmSection::Content, llvm::object::WasmObjectFile::getHeader(), llvm::object::WasmObjectFile::getNumSections(), llvm::object::WasmObjectFile::getWasmSection(), llvm::object::WasmSection::HeaderSecSizeEncodingLen, llvm::objcopy::wasm::Section::Name, llvm::object::WasmSection::Name, llvm::object::ObjectFile::sections(), llvm::objcopy::wasm::Section::SectionType, llvm::wasm::sectionTypeToString(), llvm::object::WasmSection::Type, llvm::wasm::WASM_SEC_CUSTOM, and llvm::wasm::WASM_SEC_LAST_KNOWN.
Referenced by llvm::objcopy::wasm::executeObjcopyOnBinary().
The documentation for this class was generated from the following files:
lib/ObjCopy/wasm/WasmReader.h
lib/ObjCopy/wasm/WasmReader.cpp