LLVM: llvm::BPFASpaceCastSimplifyPass Class Reference
llvm::BPFASpaceCastSimplifyPass Class Reference
#include "Target/BPF/BPF.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< BPFASpaceCastSimplifyPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< BPFASpaceCastSimplifyPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 69 of file BPF.h.
Member Function Documentation
isRequired()
static bool llvm::BPFASpaceCastSimplifyPass::isRequired () inline static
Definition at line 74 of file BPF.h.
run()
PreservedAnalyses BPFASpaceCastSimplifyPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 73 of file BPFASpaceCastSimplifyPass.cpp.
References llvm::PreservedAnalyses::all(), Changed, llvm::SmallVectorBase< Size_T >::empty(), F, I, llvm::PreservedAnalyses::none(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Value::users().
The documentation for this class was generated from the following files:
lib/Target/BPF/BPF.h
lib/Target/BPF/BPFASpaceCastSimplifyPass.cpp