LLVM: llvm::SampleProfileProber Class Reference
llvm::SampleProfileProber Class Reference
Sample profile pseudo prober.
#include "llvm/Transforms/IPO/SampleProfileProbe.h"
Public Member Functions
SampleProfileProber (Function &F, const std::string &CurModuleUniqueId)
void instrumentOneFunc (Function &F, TargetMachine *TM)
Detailed Description
Sample profile pseudo prober.
Insert pseudo probes for block sampling and value sampling.
Definition at line 74 of file SampleProfileProbe.h.
Constructor & Destructor Documentation
SampleProfileProber()
SampleProfileProber::SampleProfileProber (Function & F, const std::string & CurModuleUniqueId)
Definition at line 171 of file SampleProfileProbe.cpp.
References llvm::Last.
Member Function Documentation
instrumentOneFunc()
void SampleProfileProber::instrumentOneFunc (Function & F, TargetMachine * TM)
Definition at line 344 of file SampleProfileProbe.cpp.
References assert(), Call, llvm::cast(), llvm::MDBuilder::createPseudoProbeDesc(), llvm::dbgs(), llvm::DirectCall, llvm::StringRef::empty(), llvm::BasicBlock::end(), F, llvm::PseudoProbeDwarfDiscriminator::FullDistributionFactor, llvm::MDNode::get(), llvm::Instruction::getDebugLoc(), llvm::Intrinsic::getDeclaration(), llvm::BasicBlock::getFirstInsertionPt(), llvm::GlobalValue::getGUID(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::BasicBlock::getTerminator(), llvm::Guid, I, llvm::IndirectCall, llvm::isa(), LLVM_DEBUG, llvm::PseudoProbeDwarfDiscriminator::packProbeData(), llvm::PseudoProbeDescMetadataName, llvm::PseudoProbeFullDistributionFactor, and llvm::Instruction::setDebugLoc().
Referenced by llvm::SampleProfileProbePass::run().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/SampleProfileProbe.h
lib/Transforms/IPO/SampleProfileProbe.cpp