LLVM: llvm::VectorBuilder Class Reference
llvm::VectorBuilder Class Reference
#include "llvm/IR/VectorBuilder.h"
Public Types
enum class Behavior { ReportAndAbort = 0 , SilentlyReturnNone = 1 }
Public Member Functions
VectorBuilder (IRBuilderBase &Builder, Behavior ErrorHandling=Behavior::ReportAndAbort)
Module & getModule () const
LLVMContext & getContext () const
Value * getAllTrueMask ()
VectorBuilder & setMask (Value *NewMask)
VectorBuilder & setEVL (Value *NewExplicitVectorLength)
VectorBuilder & setStaticVL (unsigned NewFixedVL)
Value * createVectorInstruction (unsigned Opcode, Type *ReturnTy, ArrayRef< Value * > VecOpArray, const Twine &Name=Twine())
Value * createSimpleTargetReduction (Intrinsic::ID RdxID, Type *ValTy, ArrayRef< Value * > VecOpArray, const Twine &Name=Twine())
Emit a VP reduction intrinsic call for recurrence kind.
Detailed Description
Definition at line 25 of file VectorBuilder.h.
Member Enumeration Documentation
Behavior
enum class llvm::VectorBuilder::Behavior strong
Enumerator
ReportAndAbort
SilentlyReturnNone
Definition at line 27 of file VectorBuilder.h.
Constructor & Destructor Documentation
VectorBuilder()
llvm::VectorBuilder::VectorBuilder (IRBuilderBase & Builder, Behavior ErrorHandling = Behavior::ReportAndAbort) inline
Definition at line 66 of file VectorBuilder.h.
Member Function Documentation
createSimpleTargetReduction()
Value * llvm::VectorBuilder::createSimpleTargetReduction (Intrinsic::ID RdxID, Type * ValTy, ArrayRef< Value * > VecOpArray, const Twine & Name = Twine())
Emit a VP reduction intrinsic call for recurrence kind.
Parameters
RdxID The intrinsic ID of llvm.vector.reduce.*
ValTy The type of operand which the reduction operation is performed.
VecOpArray The operand list.
Definition at line 63 of file VectorBuilder.cpp.
References assert(), llvm::VPIntrinsic::getForIntrinsic(), llvm::VPReductionIntrinsic::isVPReduction(), and Name.
Referenced by llvm::createOrderedReduction(), and llvm::createSimpleTargetReduction().
createVectorInstruction()
Value * llvm::VectorBuilder::createVectorInstruction (unsigned Opcode, Type * ReturnTy, ArrayRef< Value * > VecOpArray, const Twine & Name = Twine())
Definition at line 54 of file VectorBuilder.cpp.
References llvm::VPIntrinsic::getForOpcode(), Name, and llvm::Intrinsic::not_intrinsic.
Referenced by llvm::VPWidenLoadEVLRecipe::execute(), and llvm::VPWidenStoreEVLRecipe::execute().
getAllTrueMask()
Value * llvm::VectorBuilder::getAllTrueMask ()
Definition at line 34 of file VectorBuilder.cpp.
getContext()
LLVMContext & llvm::VectorBuilder::getContext () const inline
Definition at line 73 of file VectorBuilder.h.
getModule()
Module & llvm::VectorBuilder::getModule () const
Definition at line 30 of file VectorBuilder.cpp.
setEVL()
VectorBuilder & llvm::VectorBuilder::setEVL (Value * NewExplicitVectorLength) inline
Definition at line 82 of file VectorBuilder.h.
Referenced by llvm::VPReductionEVLRecipe::execute(), llvm::VPWidenLoadEVLRecipe::execute(), and llvm::VPWidenStoreEVLRecipe::execute().
setMask()
VectorBuilder & llvm::VectorBuilder::setMask (Value * NewMask) inline
Definition at line 78 of file VectorBuilder.h.
Referenced by llvm::VPReductionEVLRecipe::execute(), llvm::VPWidenLoadEVLRecipe::execute(), and llvm::VPWidenStoreEVLRecipe::execute().
setStaticVL()
VectorBuilder & llvm::VectorBuilder::setStaticVL (unsigned NewFixedVL) inline
Definition at line 86 of file VectorBuilder.h.
References llvm::ElementCount::getFixed().
The documentation for this class was generated from the following files:
include/llvm/IR/VectorBuilder.h
lib/IR/VectorBuilder.cpp