LLVM: llvm::PrologEpilogSGPRSpillBuilder Class Reference
llvm::PrologEpilogSGPRSpillBuilder Class Reference
Public Member Functions
PrologEpilogSGPRSpillBuilder (Register Reg, const PrologEpilogSGPRSaveRestoreInfo SI, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const DebugLoc &DL, const SIInstrInfo *TII, const SIRegisterInfo &TRI, LiveRegUnits &LiveUnits, Register FrameReg)
void save ()
void restore ()
Detailed Description
Definition at line 224 of file SIFrameLowering.cpp.
Constructor & Destructor Documentation
PrologEpilogSGPRSpillBuilder()
llvm::PrologEpilogSGPRSpillBuilder::PrologEpilogSGPRSpillBuilder (Register Reg, const PrologEpilogSGPRSaveRestoreInfo SI, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const DebugLoc & DL, const SIInstrInfo * TII, const SIRegisterInfo & TRI, LiveRegUnits & LiveUnits, Register FrameReg) inline
Definition at line 337 of file SIFrameLowering.cpp.
References assert(), DL, llvm::ArrayRef< T >::empty(), MBB, MI, llvm::ArrayRef< T >::size(), TII, and TRI.
Member Function Documentation
restore()
void llvm::PrologEpilogSGPRSpillBuilder::restore () inline
Definition at line 367 of file SIFrameLowering.cpp.
References llvm::COPY_TO_SCRATCH_SGPR, llvm::SPILL_TO_MEM, and llvm::SPILL_TO_VGPR_LANE.
Referenced by llvm::SIFrameLowering::emitCSRSpillRestores().
save()
void llvm::PrologEpilogSGPRSpillBuilder::save () inline
Definition at line 356 of file SIFrameLowering.cpp.
References llvm::COPY_TO_SCRATCH_SGPR, llvm::SPILL_TO_MEM, and llvm::SPILL_TO_VGPR_LANE.
Referenced by llvm::SIFrameLowering::emitCSRSpillStores(), and llvm::SIFrameLowering::emitPrologue().
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/SIFrameLowering.cpp