LLVM: llvm::cl::SubCommand Class Reference
llvm::cl::SubCommand Class Reference
#include "llvm/Support/CommandLine.h"
Public Member Functions
SubCommand (StringRef Name, StringRef Description="")
SubCommand ()=default
void reset ()
operator bool () const
StringRef getName () const
StringRef getDescription () const
Static Public Member Functions
static SubCommand & getTopLevel ()
static SubCommand & getAll ()
Public Attributes
SmallVector< Option *, 4 > PositionalOpts
SmallVector< Option *, 4 > SinkOpts
StringMap< Option * > OptionsMap
Option * ConsumeAfterOpt = nullptr
Protected Member Functions
void registerSubCommand ()
void unregisterSubCommand ()
Detailed Description
Definition at line 202 of file CommandLine.h.
Constructor & Destructor Documentation
SubCommand() [1/2]
llvm::cl::SubCommand::SubCommand (StringRef Name, StringRef Description = "") inline
Definition at line 212 of file CommandLine.h.
References registerSubCommand().
SubCommand() [2/2]
llvm::cl::SubCommand::SubCommand () default
Member Function Documentation
getAll()
SubCommand & SubCommand::getAll () static
Definition at line 465 of file CommandLine.cpp.
References AllSubCommands.
getDescription()
StringRef llvm::cl::SubCommand::getDescription () const inline
Definition at line 230 of file CommandLine.h.
getName()
StringRef llvm::cl::SubCommand::getName () const inline
Definition at line 229 of file CommandLine.h.
getTopLevel()
SubCommand & SubCommand::getTopLevel () static
Definition at line 463 of file CommandLine.cpp.
References TopLevelSubCommand.
operator bool()
SubCommand::operator bool () const explicit
Definition at line 483 of file CommandLine.cpp.
References GlobalParser.
registerSubCommand()
void SubCommand::registerSubCommand () protected
Definition at line 467 of file CommandLine.cpp.
References GlobalParser, and registerSubCommand().
Referenced by registerSubCommand(), and SubCommand().
reset()
void SubCommand::reset ()
Definition at line 475 of file CommandLine.cpp.
References ConsumeAfterOpt, OptionsMap, PositionalOpts, and SinkOpts.
unregisterSubCommand()
void SubCommand::unregisterSubCommand () protected
Definition at line 471 of file CommandLine.cpp.
References GlobalParser.
Member Data Documentation
ConsumeAfterOpt
Option* llvm::cl::SubCommand::ConsumeAfterOpt = nullptr
Definition at line 236 of file CommandLine.h.
Referenced by reset().
OptionsMap
StringMap<Option *> llvm::cl::SubCommand::OptionsMap
Definition at line 234 of file CommandLine.h.
Referenced by llvm::cl::getRegisteredOptions(), llvm::cl::HideUnrelatedOptions(), llvm::cl::HideUnrelatedOptions(), and reset().
PositionalOpts
SmallVector<Option *, 4> llvm::cl::SubCommand::PositionalOpts
Definition at line 232 of file CommandLine.h.
Referenced by reset().
SinkOpts
SmallVector<Option *, 4> llvm::cl::SubCommand::SinkOpts
Definition at line 233 of file CommandLine.h.
Referenced by reset().
The documentation for this class was generated from the following files:
include/llvm/Support/CommandLine.h
lib/Support/CommandLine.cpp