LLVM: llvm::TGParser Class Reference
llvm::TGParser Class Reference
#include "TableGen/TGParser.h"
Public Member Functions
TGParser (SourceMgr &SM, ArrayRef< std::string > Macros, RecordKeeper &records, const bool NoWarnOnUnusedTemplateArgs=false, const bool TrackReferenceLocs=false)
bool ParseFile ()
ParseFile - Main entrypoint for parsing a tblgen file.
bool Error (SMLoc L, const Twine &Msg) const
bool TokError (const Twine &Msg) const
const TGLexer::DependenciesSetTy & getDependencies () const
TGVarScope * PushScope ()
TGVarScope * PushScope (Record *Rec)
TGVarScope * PushScope (ForeachLoop *Loop)
TGVarScope * PushScope (MultiClass *Multiclass)
void PopScope (TGVarScope *ExpectedStackTop)
Detailed Description
Definition at line 142 of file TGParser.h.
Constructor & Destructor Documentation
TGParser()
llvm::TGParser::TGParser (SourceMgr & SM, ArrayRef< std::string > Macros, RecordKeeper & records, const bool NoWarnOnUnusedTemplateArgs = false, const bool TrackReferenceLocs = false) inline
Definition at line 179 of file TGParser.h.
Member Function Documentation
Error()
bool llvm::TGParser::Error (SMLoc L, const Twine & Msg) const inline
Definition at line 190 of file TGParser.h.
References llvm::PrintError().
getDependencies()
const TGLexer::DependenciesSetTy & llvm::TGParser::getDependencies () const inline
Definition at line 197 of file TGParser.h.
References llvm::TGLexer::getDependencies().
Referenced by createDependencyFile().
ParseFile()
bool TGParser::ParseFile ()
ParseFile - Main entrypoint for parsing a tblgen file.
These parser routines return true on error, or false on success.
Definition at line 4362 of file TGParser.cpp.
References llvm::tgtok::Eof, llvm::TGLexer::getCode(), llvm::TGLexer::Lex(), PopScope(), PushScope(), and TokError().
Referenced by llvm::TableGenMain(), and llvm::TableGenParseFile().
PopScope()
void llvm::TGParser::PopScope (TGVarScope * ExpectedStackTop) inline
Definition at line 220 of file TGParser.h.
References assert().
Referenced by ParseFile().
PushScope() [1/4]
TGVarScope * llvm::TGParser::PushScope () inline
Definition at line 201 of file TGParser.h.
Referenced by ParseFile().
PushScope() [2/4]
TGVarScope * llvm::TGParser::PushScope (ForeachLoop * Loop) inline
Definition at line 212 of file TGParser.h.
PushScope() [3/4]
TGVarScope * llvm::TGParser::PushScope (MultiClass * Multiclass) inline
Definition at line 216 of file TGParser.h.
PushScope() [4/4]
TGVarScope * llvm::TGParser::PushScope (Record * Rec) inline
Definition at line 208 of file TGParser.h.
TokError()
bool llvm::TGParser::TokError (const Twine & Msg) const inline
Definition at line 194 of file TGParser.h.
References llvm::Error, and llvm::TGLexer::getLoc().
Referenced by ParseFile().
The documentation for this class was generated from the following files:
lib/TableGen/TGParser.h
lib/TableGen/TGParser.cpp