LLVM: llvm::SCEVRewriteVisitor< SC > Class Template Reference
llvm::SCEVRewriteVisitor< SC > Class Template Reference
This visitor recursively visits a SCEV expression and re-writes it.
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
Public Member Functions
SCEVRewriteVisitor (ScalarEvolution &SE)
const SCEV * visit (const SCEV *S)
const SCEV * visitConstant (const SCEVConstant *Constant)
const SCEV * visitVScale (const SCEVVScale *VScale)
const SCEV * visitPtrToIntExpr (const SCEVPtrToIntExpr *Expr)
const SCEV * visitTruncateExpr (const SCEVTruncateExpr *Expr)
const SCEV * visitZeroExtendExpr (const SCEVZeroExtendExpr *Expr)
const SCEV * visitSignExtendExpr (const SCEVSignExtendExpr *Expr)
const SCEV * visitAddExpr (const SCEVAddExpr *Expr)
const SCEV * visitMulExpr (const SCEVMulExpr *Expr)
const SCEV * visitUDivExpr (const SCEVUDivExpr *Expr)
const SCEV * visitAddRecExpr (const SCEVAddRecExpr *Expr)
const SCEV * visitSMaxExpr (const SCEVSMaxExpr *Expr)
const SCEV * visitUMaxExpr (const SCEVUMaxExpr *Expr)
const SCEV * visitSMinExpr (const SCEVSMinExpr *Expr)
const SCEV * visitUMinExpr (const SCEVUMinExpr *Expr)
const SCEV * visitSequentialUMinExpr (const SCEVSequentialUMinExpr *Expr)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *Expr)
Public Member Functions inherited from llvm::SCEVVisitor< SC, const SCEV * >
const SCEV * visit (const SCEV *S)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *S)
Protected Attributes
ScalarEvolution & SE
SmallDenseMap< const SCEV *, const SCEV * > RewriteResults
Detailed Description
template<typename SC>
class llvm::SCEVRewriteVisitor< SC >
This visitor recursively visits a SCEV expression and re-writes it.
The result from each visit is cached, so it will return the same SCEV for the same input.
Definition at line 746 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
SCEVRewriteVisitor()
template<typename SC > llvm::SCEVRewriteVisitor< SC >::SCEVRewriteVisitor (ScalarEvolution & SE) inline
Definition at line 757 of file ScalarEvolutionExpressions.h.
Member Function Documentation
visit()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visit (const SCEV * S) inline
Definition at line 759 of file ScalarEvolutionExpressions.h.
References assert(), llvm::SCEVRewriteVisitor< SC >::RewriteResults, and llvm::SCEVVisitor< SC, RetVal >::visit().
Referenced by llvm::SCEVRewriteVisitor< SC >::visitAddExpr(), llvm::SCEVRewriteVisitor< SC >::visitAddRecExpr(), llvm::SCEVRewriteVisitor< SC >::visitMulExpr(), llvm::SCEVRewriteVisitor< SC >::visitSequentialUMinExpr(), llvm::SCEVRewriteVisitor< SC >::visitSMaxExpr(), llvm::SCEVRewriteVisitor< SC >::visitSMinExpr(), llvm::SCEVRewriteVisitor< SC >::visitUMaxExpr(), and llvm::SCEVRewriteVisitor< SC >::visitUMinExpr().
visitAddExpr()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitAddExpr (const SCEVAddExpr * Expr) inline
Definition at line 801 of file ScalarEvolutionExpressions.h.
References Changed, llvm::ScalarEvolution::getAddExpr(), Operands, llvm::SCEVNAryExpr::operands(), llvm::SCEVRewriteVisitor< SC >::SE, and llvm::SCEVRewriteVisitor< SC >::visit().
visitAddRecExpr()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitAddRecExpr (const SCEVAddRecExpr * Expr) inline
Definition at line 828 of file ScalarEvolutionExpressions.h.
References Changed, llvm::ScalarEvolution::getAddRecExpr(), llvm::SCEVAddRecExpr::getLoop(), llvm::SCEVNAryExpr::getNoWrapFlags(), Operands, llvm::SCEVNAryExpr::operands(), llvm::SCEVRewriteVisitor< SC >::SE, and llvm::SCEVRewriteVisitor< SC >::visit().
visitConstant()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitConstant (const SCEVConstant * Constant) inline
Definition at line 769 of file ScalarEvolutionExpressions.h.
visitCouldNotCompute()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitCouldNotCompute (const SCEVCouldNotCompute * Expr) inline
Definition at line 892 of file ScalarEvolutionExpressions.h.
visitMulExpr()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitMulExpr (const SCEVMulExpr * Expr) inline
Definition at line 811 of file ScalarEvolutionExpressions.h.
References Changed, llvm::ScalarEvolution::getMulExpr(), Operands, llvm::SCEVNAryExpr::operands(), llvm::SCEVRewriteVisitor< SC >::SE, and llvm::SCEVRewriteVisitor< SC >::visit().
visitPtrToIntExpr()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitPtrToIntExpr (const SCEVPtrToIntExpr * Expr) inline
Definition at line 773 of file ScalarEvolutionExpressions.h.
References llvm::SCEVCastExpr::getOperand(), llvm::ScalarEvolution::getPtrToIntExpr(), llvm::SCEVCastExpr::getType(), and llvm::SCEVRewriteVisitor< SC >::SE.
visitSequentialUMinExpr()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitSequentialUMinExpr (const SCEVSequentialUMinExpr * Expr) inline
Definition at line 880 of file ScalarEvolutionExpressions.h.
References Changed, llvm::ScalarEvolution::getUMinExpr(), Operands, llvm::SCEVNAryExpr::operands(), llvm::SCEVRewriteVisitor< SC >::SE, and llvm::SCEVRewriteVisitor< SC >::visit().
visitSignExtendExpr()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitSignExtendExpr (const SCEVSignExtendExpr * Expr) inline
Definition at line 794 of file ScalarEvolutionExpressions.h.
References llvm::SCEVCastExpr::getOperand(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::SCEVCastExpr::getType(), and llvm::SCEVRewriteVisitor< SC >::SE.
Referenced by llvm::ScalarEvolution::LoopGuards::rewrite().
visitSMaxExpr()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitSMaxExpr (const SCEVSMaxExpr * Expr) inline
Definition at line 840 of file ScalarEvolutionExpressions.h.
References Changed, llvm::ScalarEvolution::getSMaxExpr(), Operands, llvm::SCEVNAryExpr::operands(), llvm::SCEVRewriteVisitor< SC >::SE, and llvm::SCEVRewriteVisitor< SC >::visit().
visitSMinExpr()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitSMinExpr (const SCEVSMinExpr * Expr) inline
Definition at line 860 of file ScalarEvolutionExpressions.h.
References Changed, llvm::ScalarEvolution::getSMinExpr(), Operands, llvm::SCEVNAryExpr::operands(), llvm::SCEVRewriteVisitor< SC >::SE, and llvm::SCEVRewriteVisitor< SC >::visit().
Referenced by llvm::ScalarEvolution::LoopGuards::rewrite().
visitTruncateExpr()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitTruncateExpr (const SCEVTruncateExpr * Expr) inline
Definition at line 780 of file ScalarEvolutionExpressions.h.
References llvm::SCEVCastExpr::getOperand(), llvm::ScalarEvolution::getTruncateExpr(), llvm::SCEVCastExpr::getType(), and llvm::SCEVRewriteVisitor< SC >::SE.
visitUDivExpr()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitUDivExpr (const SCEVUDivExpr * Expr) inline
Definition at line 821 of file ScalarEvolutionExpressions.h.
References Changed, llvm::SCEVUDivExpr::getLHS(), llvm::SCEVUDivExpr::getRHS(), llvm::ScalarEvolution::getUDivExpr(), and llvm::SCEVRewriteVisitor< SC >::SE.
visitUMaxExpr()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitUMaxExpr (const SCEVUMaxExpr * Expr) inline
Definition at line 850 of file ScalarEvolutionExpressions.h.
References Changed, llvm::ScalarEvolution::getUMaxExpr(), Operands, llvm::SCEVNAryExpr::operands(), llvm::SCEVRewriteVisitor< SC >::SE, and llvm::SCEVRewriteVisitor< SC >::visit().
visitUMinExpr()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitUMinExpr (const SCEVUMinExpr * Expr) inline
Definition at line 870 of file ScalarEvolutionExpressions.h.
References Changed, llvm::ScalarEvolution::getUMinExpr(), Operands, llvm::SCEVNAryExpr::operands(), llvm::SCEVRewriteVisitor< SC >::SE, and llvm::SCEVRewriteVisitor< SC >::visit().
Referenced by llvm::ScalarEvolution::LoopGuards::rewrite().
visitUnknown()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitUnknown (const SCEVUnknown * Expr) inline
Definition at line 890 of file ScalarEvolutionExpressions.h.
visitVScale()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitVScale (const SCEVVScale * VScale) inline
Definition at line 771 of file ScalarEvolutionExpressions.h.
visitZeroExtendExpr()
template<typename SC > const SCEV * llvm::SCEVRewriteVisitor< SC >::visitZeroExtendExpr (const SCEVZeroExtendExpr * Expr) inline
Definition at line 787 of file ScalarEvolutionExpressions.h.
References llvm::SCEVCastExpr::getOperand(), llvm::SCEVCastExpr::getType(), llvm::ScalarEvolution::getZeroExtendExpr(), and llvm::SCEVRewriteVisitor< SC >::SE.
Referenced by llvm::ScalarEvolution::LoopGuards::rewrite().
Member Data Documentation
RewriteResults
template<typename SC > SmallDenseMap<const SCEV *, const SCEV *> llvm::SCEVRewriteVisitor< SC >::RewriteResults protected
Definition at line 754 of file ScalarEvolutionExpressions.h.
Referenced by llvm::SCEVRewriteVisitor< SC >::visit().
SE
template<typename SC > ScalarEvolution& llvm::SCEVRewriteVisitor< SC >::SE protected
Definition at line 748 of file ScalarEvolutionExpressions.h.
Referenced by llvm::SCEVRewriteVisitor< SC >::visitAddExpr(), llvm::SCEVRewriteVisitor< SC >::visitAddRecExpr(), llvm::SCEVRewriteVisitor< SC >::visitMulExpr(), llvm::SCEVRewriteVisitor< SC >::visitPtrToIntExpr(), llvm::SCEVRewriteVisitor< SC >::visitSequentialUMinExpr(), llvm::SCEVRewriteVisitor< SC >::visitSignExtendExpr(), llvm::SCEVRewriteVisitor< SC >::visitSMaxExpr(), llvm::SCEVRewriteVisitor< SC >::visitSMinExpr(), llvm::SCEVRewriteVisitor< SC >::visitTruncateExpr(), llvm::SCEVRewriteVisitor< SC >::visitUDivExpr(), llvm::SCEVRewriteVisitor< SC >::visitUMaxExpr(), llvm::SCEVRewriteVisitor< SC >::visitUMinExpr(), and llvm::SCEVRewriteVisitor< SC >::visitZeroExtendExpr().
The documentation for this class was generated from the following file:
include/llvm/Analysis/ScalarEvolutionExpressions.h