LLVM: llvm::logicalview::LVStringPool Class Reference
llvm::logicalview::LVStringPool Class Reference
#include "llvm/DebugInfo/LogicalView/Core/LVStringPool.h"
Public Member Functions
LVStringPool ()
LVStringPool (LVStringPool const &other)=delete
LVStringPool (LVStringPool &&other)=delete
~LVStringPool ()=default
bool isValidIndex (size_t Index) const
size_t getSize () const
size_t findIndex (StringRef Key) const
size_t getIndex (StringRef Key)
StringRef getString (size_t Index) const
void print (raw_ostream &OS) const
void dump () const
Detailed Description
Definition at line 28 of file LVStringPool.h.
Constructor & Destructor Documentation
LVStringPool() [1/3]
llvm::logicalview::LVStringPool::LVStringPool () inline
Definition at line 37 of file LVStringPool.h.
References getIndex().
LVStringPool() [2/3]
llvm::logicalview::LVStringPool::LVStringPool (LVStringPool const & other) delete
LVStringPool() [3/3]
llvm::logicalview::LVStringPool::LVStringPool (LVStringPool && other) delete
~LVStringPool()
llvm::logicalview::LVStringPool::~LVStringPool () default
Member Function Documentation
dump()
void llvm::logicalview::LVStringPool::dump () const inline
Definition at line 84 of file LVStringPool.h.
References llvm::dbgs(), and print().
findIndex()
size_t llvm::logicalview::LVStringPool::findIndex (StringRef Key) const inline
Definition at line 50 of file LVStringPool.h.
References llvm::codeview::StringTable.
Referenced by getIndex().
getIndex()
size_t llvm::logicalview::LVStringPool::getIndex (StringRef Key) inline
Definition at line 58 of file LVStringPool.h.
References llvm::StringMapEntry< T >::create(), findIndex(), isValidIndex(), llvm::codeview::StringTable, and llvm::Value.
Referenced by getStringIndex(), LVStringPool(), llvm::logicalview::LVScopeCompileUnit::setCompilationDirectory(), llvm::logicalview::LVScopeAggregate::setEncodedArgs(), llvm::logicalview::LVScopeFunction::setEncodedArgs(), llvm::logicalview::LVScopeRoot::setFileFormatName(), llvm::logicalview::LVScopeFunction::setLinkageName(), llvm::logicalview::LVSymbol::setLinkageName(), llvm::logicalview::LVElement::setName(), llvm::logicalview::LVScopeCompileUnit::setProducer(), llvm::logicalview::LVElement::setQualifiedName(), llvm::logicalview::LVSymbol::setValue(), llvm::logicalview::LVTypeEnumerator::setValue(), and llvm::logicalview::LVTypeParam::setValue().
getSize()
size_t llvm::logicalview::LVStringPool::getSize () const inline
Definition at line 47 of file LVStringPool.h.
getString()
StringRef llvm::logicalview::LVStringPool::getString (size_t Index) const inline
Definition at line 70 of file LVStringPool.h.
Referenced by llvm::logicalview::LVScopeCompileUnit::getCompilationDirectory(), llvm::logicalview::LVScopeAggregate::getEncodedArgs(), llvm::logicalview::LVScopeFunction::getEncodedArgs(), llvm::logicalview::LVScopeRoot::getFileFormatName(), llvm::logicalview::LVScopeCompileUnit::getFilename(), llvm::logicalview::LVScopeFunction::getLinkageName(), llvm::logicalview::LVSymbol::getLinkageName(), llvm::logicalview::LVElement::getName(), llvm::logicalview::LVElement::getPathname(), llvm::logicalview::LVScopeCompileUnit::getProducer(), llvm::logicalview::LVElement::getQualifiedName(), llvm::logicalview::LVSymbol::getValue(), llvm::logicalview::LVTypeEnumerator::getValue(), llvm::logicalview::LVTypeParam::getValue(), and llvm::logicalview::LVScopeCompileUnit::printLocalNames().
isValidIndex()
bool llvm::logicalview::LVStringPool::isValidIndex (size_t Index) const inline
Definition at line 42 of file LVStringPool.h.
Referenced by getIndex().
print()
void llvm::logicalview::LVStringPool::print (raw_ostream & OS) const inline
Definition at line 74 of file LVStringPool.h.
References OS.
Referenced by dump().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/LogicalView/Core/LVStringPool.h