LLVM: llvm::sandboxir::MoveInstr Class Reference
llvm::sandboxir::MoveInstr Class Reference
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
MoveInstr (sandboxir::Instruction *I, Tracker &Tracker)
void revert () final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
IRChangeBase (Tracker &Parent)
virtual ~IRChangeBase ()=default
unsigned getIdx () const
\Returns the index of this change by iterating over all changes in the tracker.
void dumpCommon (raw_ostream &OS) const
Additional Inherited Members
Protected Attributes inherited from llvm::sandboxir::IRChangeBase
Tracker & Parent
Detailed Description
Definition at line 159 of file Tracker.h.
Constructor & Destructor Documentation
MoveInstr()
MoveInstr::MoveInstr (sandboxir::Instruction * I, Tracker & Tracker)
Definition at line 127 of file Tracker.cpp.
References llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), and llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent().
Member Function Documentation
accept()
void llvm::sandboxir::MoveInstr::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 169 of file Tracker.h.
dump() [1/2]
void MoveInstr::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 145 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::MoveInstr::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 171 of file Tracker.h.
References llvm::sandboxir::IRChangeBase::dumpCommon(), and OS.
revert()
void MoveInstr::revert () final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 135 of file Tracker.cpp.
References llvm::Instruction::moveBefore().
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp