LLVM: llvm::sandboxir::UseSet Class Reference
llvm::sandboxir::UseSet Class Reference
Tracks the change of the source Value of a sandboxir::Use.
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
UseSet (const Use &U, Tracker &Tracker)
void revert () final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
IRChangeBase (Tracker &Parent)
virtual ~IRChangeBase ()=default
unsigned getIdx () const
\Returns the index of this change by iterating over all changes in the tracker.
void dumpCommon (raw_ostream &OS) const
Additional Inherited Members
Protected Attributes inherited from llvm::sandboxir::IRChangeBase
Tracker & Parent
Detailed Description
Tracks the change of the source Value of a sandboxir::Use.
Definition at line 86 of file Tracker.h.
Constructor & Destructor Documentation
UseSet()
llvm::sandboxir::UseSet::UseSet (const Use & U, Tracker & Tracker) inline
Definition at line 91 of file Tracker.h.
Member Function Documentation
accept()
void llvm::sandboxir::UseSet::accept () inline final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 94 of file Tracker.h.
dump() [1/2]
void UseSet::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 34 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::UseSet::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 96 of file Tracker.h.
References llvm::sandboxir::IRChangeBase::dumpCommon(), and OS.
revert()
void llvm::sandboxir::UseSet::revert () inline final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 93 of file Tracker.h.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp