LLVM: llvm::Module::debug_compile_units_iterator Class Reference
llvm::Module::debug_compile_units_iterator Class Reference
An iterator for DICompileUnits that skips those marked NoDebug.
#include "llvm/IR/Module.h"
Public Types
using iterator_category = std::input_iterator_tag
using value_type = DICompileUnit *
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
debug_compile_units_iterator (NamedMDNode *CUs, unsigned Idx)
debug_compile_units_iterator & operator++ ()
debug_compile_units_iterator operator++ (int)
bool operator== (const debug_compile_units_iterator &I) const
bool operator!= (const debug_compile_units_iterator &I) const
DICompileUnit * operator* () const
DICompileUnit * operator-> () const
Detailed Description
An iterator for DICompileUnits that skips those marked NoDebug.
Definition at line 814 of file Module.h.
Member Typedef Documentation
difference_type
using llvm::Module::debug_compile_units_iterator::difference_type = std::ptrdiff_t
Definition at line 823 of file Module.h.
iterator_category
using llvm::Module::debug_compile_units_iterator::iterator_category = std::input_iterator_tag
Definition at line 821 of file Module.h.
pointer
using llvm::Module::debug_compile_units_iterator::pointer = value_type *
Definition at line 824 of file Module.h.
reference
using llvm::Module::debug_compile_units_iterator::reference = value_type &
Definition at line 825 of file Module.h.
value_type
using llvm::Module::debug_compile_units_iterator::value_type = DICompileUnit *
Definition at line 822 of file Module.h.
Constructor & Destructor Documentation
debug_compile_units_iterator()
llvm::Module::debug_compile_units_iterator::debug_compile_units_iterator (NamedMDNode * CUs, unsigned Idx) inline explicit
Definition at line 827 of file Module.h.
Member Function Documentation
operator!=()
bool llvm::Module::debug_compile_units_iterator::operator!= (const debug_compile_units_iterator & I) const inline
Definition at line 848 of file Module.h.
References I.
operator*()
DICompileUnit * Module::debug_compile_units_iterator::operator* () const
Definition at line 417 of file Module.cpp.
References llvm::cast(), and llvm::NamedMDNode::getOperand().
operator++() [1/2]
debug_compile_units_iterator & llvm::Module::debug_compile_units_iterator::operator++ () inline
Definition at line 832 of file Module.h.
operator++() [2/2]
debug_compile_units_iterator llvm::Module::debug_compile_units_iterator::operator++ (int) inline
Definition at line 838 of file Module.h.
References T.
operator->()
DICompileUnit * Module::debug_compile_units_iterator::operator-> () const
Definition at line 420 of file Module.cpp.
References llvm::cast().
operator==()
bool llvm::Module::debug_compile_units_iterator::operator== (const debug_compile_units_iterator & I) const inline
Definition at line 844 of file Module.h.
References I.
The documentation for this class was generated from the following files:
include/llvm/IR/Module.h
lib/IR/Module.cpp