LLVM: llvm::dwarf_linker::parallel::DebugLineSectionEmitter Class Reference
llvm::dwarf_linker::parallel::DebugLineSectionEmitter Class Reference
This class emits specified line table into the .debug_line section.
#include "DWARFLinker/Parallel/DebugLineSectionEmitter.h"
Public Member Functions
DebugLineSectionEmitter (const Triple &TheTriple, DwarfUnit &U)
Error emit (const DWARFDebugLine::LineTable &LineTable)
Detailed Description
This class emits specified line table into the .debug_line section.
Definition at line 24 of file DebugLineSectionEmitter.h.
Constructor & Destructor Documentation
DebugLineSectionEmitter()
llvm::dwarf_linker::parallel::DebugLineSectionEmitter::DebugLineSectionEmitter (const Triple & TheTriple, DwarfUnit & U) inline
Definition at line 26 of file DebugLineSectionEmitter.h.
Member Function Documentation
emit()
Error llvm::dwarf_linker::parallel::DebugLineSectionEmitter::emit (const DWARFDebugLine::LineTable & LineTable) inline
Definition at line 29 of file DebugLineSectionEmitter.h.
References llvm::dwarf_linker::parallel::SectionDescriptor::apply(), assert(), llvm::dwarf_linker::DebugLine, llvm::dwarf_linker::parallel::SectionDescriptor::emitUnitLength(), llvm::dwarf::FormParams::getDwarfOffsetByteSize(), llvm::dwarf_linker::parallel::SectionDescriptorBase::getFormParams(), llvm::dwarf_linker::parallel::SectionDescriptor::OS, llvm::DWARFDebugLine::LineTable::Prologue, llvm::Error::success(), and llvm::raw_ostream::tell().
Referenced by llvm::dwarf_linker::parallel::DwarfUnit::emitDebugLine().
The documentation for this class was generated from the following file:
lib/DWARFLinker/Parallel/DebugLineSectionEmitter.h