LLVM: llvm::MachO::SymbolSet Class Reference
llvm::MachO::SymbolSet Class Reference
#include "llvm/TextAPI/SymbolSet.h"
Classes
struct const_symbol_iterator
Public Types
using const_symbol_range = iterator_range<const_symbol_iterator>
using const_filtered_symbol_iterator
using const_filtered_symbol_range
Public Member Functions
SymbolSet ()=default
Symbol * addGlobal (EncodeKind Kind, StringRef Name, SymbolFlags Flags, const Target &Targ)
size_t size () const
template<typename RangeT , typename ElT = std::remove_reference_t< decltype(*std::begin(std::declval<RangeT>()))>>
Symbol * addGlobal (EncodeKind Kind, StringRef Name, SymbolFlags Flags, RangeT &&Targets)
const Symbol * findSymbol (EncodeKind Kind, StringRef Name, ObjCIFSymbolKind ObjCIF=ObjCIFSymbolKind::None) const
const_symbol_range symbols () const
const_filtered_symbol_range exports () const
const_filtered_symbol_range reexports () const
const_filtered_symbol_range undefineds () const
bool operator== (const SymbolSet &O) const
bool operator!= (const SymbolSet &O) const
void * allocate (size_t Size, unsigned Align=8)
Detailed Description
Definition at line 76 of file SymbolSet.h.
Member Typedef Documentation
const_filtered_symbol_iterator
using llvm::MachO::SymbolSet::const_filtered_symbol_iterator
Initial value:
      filter_iterator<const_symbol_iterator,
                      std::function<bool(const Symbol *)>>
Definition at line 131 of file SymbolSet.h.
const_filtered_symbol_range
using llvm::MachO::SymbolSet::const_filtered_symbol_range
Initial value:
      iterator_range<const_filtered_symbol_iterator>
Definition at line 134 of file SymbolSet.h.
const_symbol_range
using llvm::MachO::SymbolSet::const_symbol_range = iterator_range<const_symbol_iterator>
Definition at line 129 of file SymbolSet.h.
Constructor & Destructor Documentation
SymbolSet()
llvm::MachO::SymbolSet::SymbolSet () default
Member Function Documentation
addGlobal() [1/2]
Symbol * SymbolSet::addGlobal (EncodeKind Kind, StringRef Name, SymbolFlags Flags, const Target & Targ)
Definition at line 24 of file SymbolSet.cpp.
References llvm::MachO::Symbol::addTarget(), Name, and Sym.
Referenced by addGlobal(), llvm::MachO::SymbolConverter::visitGlobal(), and llvm::MachO::SymbolConverter::visitObjCInterface().
addGlobal() [2/2]
template<typename RangeT , typename ElT = std::remove_reference_t< decltype(*std::begin(std::declval<RangeT>()))>> Symbol * llvm::MachO::SymbolSet::addGlobal (EncodeKind Kind, StringRef Name, SymbolFlags Flags, RangeT && Targets) inline
Definition at line 100 of file SymbolSet.h.
References addGlobal(), llvm::Global, Name, llvm::MachO::ObjectiveCClass, and llvm::MachO::ObjectiveCClassEHType.
allocate()
void * llvm::MachO::SymbolSet::allocate (size_t Size, unsigned Align = 8) inline
Definition at line 176 of file SymbolSet.h.
References Size.
exports()
const_filtered_symbol_range llvm::MachO::SymbolSet::exports () const inline
Definition at line 143 of file SymbolSet.h.
References llvm::MachO::Symbol::isReexported(), llvm::MachO::Symbol::isUndefined(), llvm::make_filter_range(), and llvm::make_range().
findSymbol()
const Symbol * SymbolSet::findSymbol (EncodeKind Kind, StringRef Name, ObjCIFSymbolKind ObjCIF = ObjCIFSymbolKind::None) const
Definition at line 31 of file SymbolSet.cpp.
References assert(), llvm::MachO::Class, llvm::MachO::EHType, llvm::MachO::GlobalSymbol, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), llvm::MachO::MetaClass, Name, llvm::MachO::None, llvm::MachO::ObjC2ClassNamePrefix, llvm::MachO::ObjC2EHTypePrefix, and llvm::MachO::ObjC2MetaClassNamePrefix.
operator!=()
bool llvm::MachO::SymbolSet::operator!= (const SymbolSet & O) const inline
Definition at line 174 of file SymbolSet.h.
operator==()
bool llvm::MachO::SymbolSet::operator== (const SymbolSet & O) const
reexports()
const_filtered_symbol_range llvm::MachO::SymbolSet::reexports () const inline
Definition at line 153 of file SymbolSet.h.
References llvm::MachO::Symbol::isReexported(), llvm::make_filter_range(), and llvm::make_range().
size()
size_t llvm::MachO::SymbolSet::size () const inline
Definition at line 96 of file SymbolSet.h.
symbols()
const_symbol_range llvm::MachO::SymbolSet::symbols () const inline
Definition at line 138 of file SymbolSet.h.
undefineds()
const_filtered_symbol_range llvm::MachO::SymbolSet::undefineds () const inline
Definition at line 163 of file SymbolSet.h.
References llvm::MachO::Symbol::isUndefined(), llvm::make_filter_range(), and llvm::make_range().
The documentation for this class was generated from the following files:
include/llvm/TextAPI/SymbolSet.h
lib/TextAPI/SymbolSet.cpp