LLVM: llvm::sandboxir::EraseFromParent Class Reference
llvm::sandboxir::EraseFromParent Class Reference
#include "llvm/SandboxIR/Tracker.h"
Public Member Functions
EraseFromParent (std::unique_ptr< sandboxir::Value > &&IPtr, Tracker &Tracker)
void revert () final
This runs when changes get reverted.
void accept () final
This runs when changes get accepted.
void dump (raw_ostream &OS) const final
LLVM_DUMP_METHOD void dump () const final
Public Member Functions inherited from llvm::sandboxir::IRChangeBase
IRChangeBase (Tracker &Parent)
virtual ~IRChangeBase ()=default
unsigned getIdx () const
\Returns the index of this change by iterating over all changes in the tracker.
void dumpCommon (raw_ostream &OS) const
Friends
raw_ostream & operator<< (raw_ostream &OS, const EraseFromParent &C)
Additional Inherited Members
Protected Attributes inherited from llvm::sandboxir::IRChangeBase
Tracker & Parent
Detailed Description
Definition at line 104 of file Tracker.h.
Constructor & Destructor Documentation
EraseFromParent()
EraseFromParent::EraseFromParent (std::unique_ptr< sandboxir::Value > && IPtr, Tracker & Tracker)
Definition at line 44 of file Tracker.cpp.
References assert(), llvm::cast(), llvm::enumerate(), llvm::sandboxir::Use::get(), I, llvm::is_sorted(), Operands, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::reverse().
Member Function Documentation
accept()
void EraseFromParent::accept () final virtual
This runs when changes get accepted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 69 of file Tracker.cpp.
dump() [1/2]
void EraseFromParent::dump () const final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 97 of file Tracker.cpp.
References llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void llvm::sandboxir::EraseFromParent::dump (raw_ostream & OS) const inline final virtual
Implements llvm::sandboxir::IRChangeBase.
Definition at line 127 of file Tracker.h.
References llvm::sandboxir::IRChangeBase::dumpCommon(), and OS.
revert()
void EraseFromParent::revert () final virtual
This runs when changes get reverted.
Implements llvm::sandboxir::IRChangeBase.
Definition at line 74 of file Tracker.cpp.
References llvm::drop_begin(), llvm::PointerUnion< PTs >::dyn_cast(), llvm::enumerate(), llvm::PointerUnion< PTs >::get(), llvm::sandboxir::Tracker::getContext(), llvm::BasicBlock::insertInto(), Operands, and llvm::sandboxir::IRChangeBase::Parent.
Friends And Related Symbol Documentation
operator<<
raw_ostream & operator<< (raw_ostream & OS, const EraseFromParent & C) friend
Definition at line 132 of file Tracker.h.
The documentation for this class was generated from the following files:
include/llvm/SandboxIR/Tracker.h
lib/SandboxIR/Tracker.cpp