LLVM: llvm::PassInstrumentationCallbacks Class Reference
llvm::PassInstrumentationCallbacks Class Reference
This class manages callbacks registration, as well as provides a way for PassInstrumentation to pass control to the registered callbacks.
#include "llvm/IR/PassInstrumentation.h"
Public Types
using BeforePassFunc = bool(StringRef, Any)
using BeforeSkippedPassFunc = void(StringRef, Any)
using BeforeNonSkippedPassFunc = void(StringRef, Any)
using AfterPassFunc = void(StringRef, Any, const PreservedAnalyses &)
using AfterPassInvalidatedFunc = void(StringRef, const PreservedAnalyses &)
using BeforeAnalysisFunc = void(StringRef, Any)
using AfterAnalysisFunc = void(StringRef, Any)
using AnalysisInvalidatedFunc = void(StringRef, Any)
using AnalysesClearedFunc = void(StringRef)
Public Member Functions
PassInstrumentationCallbacks ()=default
PassInstrumentationCallbacks (const PassInstrumentationCallbacks &)=delete
Copying PassInstrumentationCallbacks is not intended.
void operator= (const PassInstrumentationCallbacks &)=delete
template<typename CallableT >
void registerShouldRunOptionalPassCallback (CallableT C)
template<typename CallableT >
void registerBeforeSkippedPassCallback (CallableT C)
template<typename CallableT >
void registerBeforeNonSkippedPassCallback (CallableT C)
template<typename CallableT >
void registerAfterPassCallback (CallableT C, bool ToFront=false)
template<typename CallableT >
void registerAfterPassInvalidatedCallback (CallableT C, bool ToFront=false)
template<typename CallableT >
void registerBeforeAnalysisCallback (CallableT C)
template<typename CallableT >
void registerAfterAnalysisCallback (CallableT C, bool ToFront=false)
template<typename CallableT >
void registerAnalysisInvalidatedCallback (CallableT C)
template<typename CallableT >
void registerAnalysesClearedCallback (CallableT C)
template<typename CallableT >
void registerClassToPassNameCallback (CallableT C)
void addClassToPassName (StringRef ClassName, StringRef PassName)
Add a class name to pass name mapping for use by pass instrumentation.
StringRef getPassNameForClassName (StringRef ClassName)
Get the pass name for a given pass class name.
Friends
class PassInstrumentation
Detailed Description
This class manages callbacks registration, as well as provides a way for PassInstrumentation to pass control to the registered callbacks.
Definition at line 67 of file PassInstrumentation.h.
Member Typedef Documentation
AfterAnalysisFunc
using llvm::PassInstrumentationCallbacks::AfterAnalysisFunc = void(StringRef, Any)
Definition at line 85 of file PassInstrumentation.h.
AfterPassFunc
using llvm::PassInstrumentationCallbacks::AfterPassFunc = void(StringRef, Any, const PreservedAnalyses &)
Definition at line 82 of file PassInstrumentation.h.
AfterPassInvalidatedFunc
using llvm::PassInstrumentationCallbacks::AfterPassInvalidatedFunc = void(StringRef, const PreservedAnalyses &)
Definition at line 83 of file PassInstrumentation.h.
AnalysesClearedFunc
using llvm::PassInstrumentationCallbacks::AnalysesClearedFunc = void(StringRef)
Definition at line 87 of file PassInstrumentation.h.
AnalysisInvalidatedFunc
using llvm::PassInstrumentationCallbacks::AnalysisInvalidatedFunc = void(StringRef, Any)
Definition at line 86 of file PassInstrumentation.h.
BeforeAnalysisFunc
using llvm::PassInstrumentationCallbacks::BeforeAnalysisFunc = void(StringRef, Any)
Definition at line 84 of file PassInstrumentation.h.
BeforeNonSkippedPassFunc
using llvm::PassInstrumentationCallbacks::BeforeNonSkippedPassFunc = void(StringRef, Any)
Definition at line 81 of file PassInstrumentation.h.
BeforePassFunc
using llvm::PassInstrumentationCallbacks::BeforePassFunc = bool(StringRef, Any)
Definition at line 79 of file PassInstrumentation.h.
BeforeSkippedPassFunc
using llvm::PassInstrumentationCallbacks::BeforeSkippedPassFunc = void(StringRef, Any)
Definition at line 80 of file PassInstrumentation.h.
Constructor & Destructor Documentation
PassInstrumentationCallbacks() [1/2]
llvm::PassInstrumentationCallbacks::PassInstrumentationCallbacks () default
PassInstrumentationCallbacks() [2/2]
llvm::PassInstrumentationCallbacks::PassInstrumentationCallbacks (const PassInstrumentationCallbacks &) delete
Copying PassInstrumentationCallbacks is not intended.
Member Function Documentation
addClassToPassName()
void llvm::PassInstrumentationCallbacks::addClassToPassName (StringRef ClassName, StringRef PassName)
Add a class name to pass name mapping for use by pass instrumentation.
Definition at line 20 of file PassInstrumentation.cpp.
References PassName.
getPassNameForClassName()
StringRef llvm::PassInstrumentationCallbacks::getPassNameForClassName (StringRef ClassName)
Get the pass name for a given pass class name.
Definition at line 26 of file PassInstrumentation.cpp.
References llvm::SmallVectorBase< Size_T >::empty().
Referenced by llvm::PassInstrumentation::getPassNameForClassName(), llvm::PrintCrashIRInstrumentation::registerCallbacks(), and llvm::ChangeReporter< IRUnitT >::registerRequiredCallbacks().
operator=()
void llvm::PassInstrumentationCallbacks::operator= (const PassInstrumentationCallbacks &) delete
registerAfterAnalysisCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerAfterAnalysisCallback (CallableT C, bool ToFront = false) inline
Definition at line 134 of file PassInstrumentation.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::CallingConv::C, llvm::SmallVectorImpl< T >::emplace_back(), and llvm::SmallVectorImpl< T >::insert().
Referenced by llvm::PrintPassInstrumentation::registerCallbacks(), llvm::TimePassesHandler::registerCallbacks(), and llvm::TimeProfilingPassesHandler::registerCallbacks().
registerAfterPassCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerAfterPassCallback (CallableT C, bool ToFront = false) inline
Definition at line 112 of file PassInstrumentation.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::CallingConv::C, llvm::SmallVectorImpl< T >::emplace_back(), and llvm::SmallVectorImpl< T >::insert().
Referenced by llvm::DebugifyEachInstrumentation::registerCallbacks(), llvm::PreservedCFGCheckerInstrumentation::registerCallbacks(), llvm::PrintIRInstrumentation::registerCallbacks(), llvm::PrintPassInstrumentation::registerCallbacks(), llvm::PseudoProbeVerifier::registerCallbacks(), llvm::TimePassesHandler::registerCallbacks(), llvm::TimeProfilingPassesHandler::registerCallbacks(), llvm::VerifyInstrumentation::registerCallbacks(), and llvm::ChangeReporter< IRUnitT >::registerRequiredCallbacks().
registerAfterPassInvalidatedCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback (CallableT C, bool ToFront = false) inline
Definition at line 120 of file PassInstrumentation.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::CallingConv::C, llvm::SmallVectorImpl< T >::emplace_back(), and llvm::SmallVectorImpl< T >::insert().
Referenced by llvm::PreservedCFGCheckerInstrumentation::registerCallbacks(), llvm::PrintIRInstrumentation::registerCallbacks(), llvm::PrintPassInstrumentation::registerCallbacks(), llvm::TimePassesHandler::registerCallbacks(), llvm::TimeProfilingPassesHandler::registerCallbacks(), and llvm::ChangeReporter< IRUnitT >::registerRequiredCallbacks().
registerAnalysesClearedCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerAnalysesClearedCallback (CallableT C) inline
Definition at line 148 of file PassInstrumentation.h.
References llvm::CallingConv::C, and llvm::SmallVectorImpl< T >::emplace_back().
Referenced by llvm::PrintPassInstrumentation::registerCallbacks().
registerAnalysisInvalidatedCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerAnalysisInvalidatedCallback (CallableT C) inline
Definition at line 143 of file PassInstrumentation.h.
References llvm::CallingConv::C, and llvm::SmallVectorImpl< T >::emplace_back().
Referenced by llvm::PrintPassInstrumentation::registerCallbacks().
registerBeforeAnalysisCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerBeforeAnalysisCallback (CallableT C) inline
Definition at line 129 of file PassInstrumentation.h.
References llvm::CallingConv::C, and llvm::SmallVectorImpl< T >::emplace_back().
Referenced by llvm::PrintPassInstrumentation::registerCallbacks(), llvm::TimePassesHandler::registerCallbacks(), and llvm::TimeProfilingPassesHandler::registerCallbacks().
registerBeforeNonSkippedPassCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerBeforeNonSkippedPassCallback (CallableT C) inline
Definition at line 107 of file PassInstrumentation.h.
References llvm::CallingConv::C, and llvm::SmallVectorImpl< T >::emplace_back().
Referenced by llvm::DebugifyEachInstrumentation::registerCallbacks(), llvm::PreservedCFGCheckerInstrumentation::registerCallbacks(), llvm::PrintCrashIRInstrumentation::registerCallbacks(), llvm::PrintIRInstrumentation::registerCallbacks(), llvm::PrintPassInstrumentation::registerCallbacks(), llvm::TimePassesHandler::registerCallbacks(), llvm::TimeProfilingPassesHandler::registerCallbacks(), and llvm::ChangeReporter< IRUnitT >::registerRequiredCallbacks().
registerBeforeSkippedPassCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerBeforeSkippedPassCallback (CallableT C) inline
Definition at line 102 of file PassInstrumentation.h.
References llvm::CallingConv::C, and llvm::SmallVectorImpl< T >::emplace_back().
Referenced by llvm::PrintPassInstrumentation::registerCallbacks().
registerClassToPassNameCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerClassToPassNameCallback (CallableT C) inline
Definition at line 153 of file PassInstrumentation.h.
References llvm::CallingConv::C, and llvm::SmallVectorImpl< T >::emplace_back().
Referenced by llvm::PassBuilder::PassBuilder().
registerShouldRunOptionalPassCallback()
template<typename CallableT > void llvm::PassInstrumentationCallbacks::registerShouldRunOptionalPassCallback (CallableT C) inline
Definition at line 97 of file PassInstrumentation.h.
References llvm::CallingConv::C, and llvm::SmallVectorImpl< T >::emplace_back().
Referenced by llvm::OptNoneInstrumentation::registerCallbacks(), llvm::OptPassGateInstrumentation::registerCallbacks(), and llvm::registerCodeGenCallback().
Friends And Related Symbol Documentation
PassInstrumentation
friend class PassInstrumentation friend
Definition at line 163 of file PassInstrumentation.h.
The documentation for this class was generated from the following files:
include/llvm/IR/PassInstrumentation.h
lib/IR/PassInstrumentation.cpp