LLVM: llvm::DWARFDebugArangeSet Class Reference
llvm::DWARFDebugArangeSet Class Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugArangeSet.h"
Classes
struct Descriptor
struct Header
Public Member Functions
DWARFDebugArangeSet ()
void clear ()
Error extract (DWARFDataExtractor data, uint64_t *offset_ptr, function_ref< void(Error)> WarningHandler)
void dump (raw_ostream &OS) const
uint64_t getCompileUnitDIEOffset () const
const Header & getHeader () const
desc_iterator_range descriptors () const
Detailed Description
Definition at line 23 of file DWARFDebugArangeSet.h.
Constructor & Destructor Documentation
DWARFDebugArangeSet()
llvm::DWARFDebugArangeSet::DWARFDebugArangeSet () inline
Definition at line 61 of file DWARFDebugArangeSet.h.
References clear().
Member Function Documentation
clear()
void DWARFDebugArangeSet::clear ()
Definition at line 32 of file DWARFDebugArangeSet.cpp.
Referenced by DWARFDebugArangeSet().
descriptors()
desc_iterator_range llvm::DWARFDebugArangeSet::descriptors () const inline
Definition at line 72 of file DWARFDebugArangeSet.h.
dump()
void DWARFDebugArangeSet::dump (raw_ostream & OS) const
Definition at line 163 of file DWARFDebugArangeSet.cpp.
References llvm::DWARFDebugArangeSet::Header::AddrSize, llvm::DWARFDebugArangeSet::Header::CuOffset, llvm::DWARFDebugArangeSet::Header::Format, llvm::format(), llvm::dwarf::FormatString(), llvm::dwarf::getDwarfOffsetByteSize(), llvm::DWARFDebugArangeSet::Header::Length, OS, llvm::DWARFDebugArangeSet::Header::SegSize, and llvm::DWARFDebugArangeSet::Header::Version.
Referenced by llvm::DWARFContext::dump().
extract()
Error DWARFDebugArangeSet::extract (DWARFDataExtractor data, uint64_t * offset_ptr, function_ref< void(Error)> WarningHandler)
Definition at line 38 of file DWARFDebugArangeSet.cpp.
References llvm::DWARFDebugArangeSet::Descriptor::Address, llvm::DWARFDebugArangeSet::Header::AddrSize, assert(), llvm::c_str(), llvm::DWARFContext::checkAddressSizeSupported(), llvm::createStringError(), llvm::DWARFDebugArangeSet::Header::CuOffset, llvm::DWARFDebugArangeSet::Header::Format, llvm::dwarf::getDwarfOffsetByteSize(), llvm::DWARFDataExtractor::getInitialLength(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU8(), llvm::dwarf::getUnitLengthFieldByteSize(), llvm::DataExtractor::getUnsigned(), llvm::invalid_argument, llvm::DataExtractor::isValidOffset(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::DWARFDebugArangeSet::Descriptor::Length, llvm::DWARFDebugArangeSet::Header::Length, llvm::not_supported, llvm::DWARFDebugArangeSet::Header::SegSize, llvm::Error::success(), llvm::dwarf::toString(), and llvm::DWARFDebugArangeSet::Header::Version.
Referenced by llvm::DWARFContext::dump().
getCompileUnitDIEOffset()
uint64_t llvm::DWARFDebugArangeSet::getCompileUnitDIEOffset () const inline
Definition at line 68 of file DWARFDebugArangeSet.h.
getHeader()
const Header & llvm::DWARFDebugArangeSet::getHeader () const inline
Definition at line 70 of file DWARFDebugArangeSet.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFDebugArangeSet.h
lib/DebugInfo/DWARF/DWARFDebugArangeSet.cpp