LLVM: llvm::ilist_detail::node_parent_access< NodeTy, ParentTy > Class Template Reference
llvm::ilist_detail::node_parent_access< NodeTy, ParentTy > Class Template Reference
Mixin base class that is used to add getParent() and setParent(ParentTy*) methods to ilist_node_impl iff ilist_parent has been set in the list options.
#include "llvm/ADT/ilist_node.h"
Public Member Functions
const ParentTy * getParent () const
ParentTy * getParent ()
void setParent (ParentTy *Parent)
Detailed Description
template<class NodeTy, class ParentTy>
class llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >
Mixin base class that is used to add getParent() and setParent(ParentTy*) methods to ilist_node_impl iff ilist_parent has been set in the list options.
Definition at line 30 of file ilist_node.h.
Member Function Documentation
getParent() [1/2]
template<class NodeTy , class ParentTy > ParentTy * llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent () inline
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-19.1.0/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 35 of file ilist_node.h.
getParent() [2/2]
template<class NodeTy , class ParentTy > const ParentTy * llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent () const inline
Definition at line 32 of file ilist_node.h.
Referenced by addBoundsChecking(), Prefetch::addInstruction(), addNoRecurseAttrsTopDown(), llvm::RecurrenceDescriptor::AddReductionVar(), AddReturnAttributes(), allSameBlock(), AreEquivalentPhiNodes(), areInnerLoopLatchPHIsSupported(), areOuterLoopExitPHIsSupported(), areTwoInsertFromSameBuildVector(), BlockIsSimpleEnoughToThreadThrough(), BrPHIToSelect(), buildPartialInvariantUnswitchConditionalBranch(), llvm::calculateClrEHStateNumbers(), calculateCXXStateNumbers(), calculateSEHStateNumbers(), CalculateUnswitchCostMultiplier(), canFoldTermCondOfLoop(), canHoistIVInc(), llvm::AAResults::canInstructionRangeModRef(), CanPropagatePredecessorsForPHIs(), canSplitCallSite(), canSplitPredecessors(), llvm::changeToInvokeAndSplitBasicBlock(), checkAndReplaceCondition(), checkIfSupported(), checkPHIs(), llvm::cloneAndAdaptNoAliasScopes(), llvm::CloneAndPruneIntoFromInst(), cloneInstructionInExitBlock(), llvm::computeConstantRange(), llvm::computeKnownBitsFromContext(), computeKnownFPClassFromCond(), computeKnownFPClassFromContext(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), ConnectEpilog(), llvm::ConvertDebugDeclareToDebugValue(), llvm::ConvertDebugDeclareToDebugValue(), llvm::ConvertDebugDeclareToDebugValue(), llvm::DbgVariableRecord::createLinkedDVRAssign(), llvm::createMemCpyLoopKnownSize(), createMemMoveLoop(), createMemSetLoop(), llvm::OpenMPIRBuilder::createParallel(), createRetPHINode(), llvm::OpenMPIRBuilder::createSections(), llvm::OpenMPIRBuilder::createTask(), createTileStore(), despeculateCountZeros(), diagnoseInvalidFormatString(), DoFlattenLoopPair(), llvm::DominatorTree::dominates(), llvm::DominatorTree::dominates(), llvm::DominatorTree::dominates(), llvm::PostDominatorTree::dominates(), llvm::InstCombinerImpl::dominatesAllUses(), domTreeLevelBefore(), llvm::VPlanTransforms::dropPoisonGeneratingRecipes(), emitDbgAssign(), emitTargetTaskProxyFunction(), llvm::ScalarEvolution::evaluatePredicateAt(), llvm::VPPredInstPHIRecipe::execute(), expandAbs(), expandAnyIntrinsic(), expandClampIntrinsic(), expandExpIntrinsic(), expandIntegerDot(), expandLerpIntrinsic(), expandLogIntrinsic(), expandPowIntrinsic(), expandToSwitch(), findBestNonTrivialUnswitchCandidate(), llvm::findDevirtualizableCallsForTypeTest(), findExtractedOutputToOverallOutputMapping(), findInitTrampolineFromBB(), llvm::SCEVExpander::findInsertPointAfter(), findLiveSetAtInst(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::DominatorTree::findNearestCommonDominator(), findPotentialBlockers(), llvm::InstCombinerImpl::foldBinopWithPhiOperands(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnValueKnownInPredecessorImpl(), foldDependentIVs(), foldFCmpToFPClassTest(), llvm::InstCombinerImpl::foldFreezeIntoRecurrence(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), foldLoadsRecursive(), foldMemChr(), llvm::InstCombinerImpl::foldOpIntoPhi(), llvm::InstCombinerImpl::foldPHIArgLoadIntoPHI(), llvm::InstCombinerImpl::foldPHIArgOpIntoPHI(), FoldTwoEntryPHINode(), llvm::InstCombinerImpl::freelyInvertAllUsersOf(), llvm::funcReturnsFirstArgOfCall(), llvm::LazyValueInfo::getConstant(), llvm::LazyValueInfo::getConstantRange(), getDefaultInlineAdvice(), llvm::MemoryDependenceResults::getDependency(), getDomPredecessorCondition(), llvm::IRSimilarity::IRSimilarityCandidate::getEndBB(), getFunctionTypeFromAsyncSuspend(), getGCResultLocality(), getGVNForPHINode(), getInsertPointForUses(), llvm::LoopVectorizationCostModel::getInstructionCost(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), getInvertibleOperands(), getIVIncrement(), getJumpThreadDuplicationCost(), llvm::MustBeExecutedContextExplorer::getMustBeExecutedNextInstruction(), llvm::MustBeExecutedContextExplorer::getMustBeExecutedPrevInstruction(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::DbgMarker::getParent(), llvm::DbgMarker::getParent(), llvm::DbgRecord::getParent(), llvm::DbgRecord::getParent(), llvm::LazyValueInfo::getPredicateAt(), llvm::LazyValueInfo::getPredicateAt(), llvm::ProfileSummaryInfo::getProfileCount(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), llvm::IRSimilarity::IRSimilarityCandidate::getStartBB(), llvm::memtag::getUntagLocationIfFunctionExit(), llvm::LazyValueInfoImpl::getValueAtUse(), getVarName(), handlePhiDef(), hasCallsBetween(), hashCallInst(), hasOnlyUniformBranches(), HasSafePathToPredecessorCall(), llvm::SCEVExpander::hoistIVInc(), hoistLockstepIdenticalDbgVariableRecords(), llvm::hoistRegion(), hoistValue(), hostParallelCallback(), injectPendingInvariantConditions(), llvm::InlineFunction(), inlineRetainOrClaimRVCalls(), llvm::Instruction::insertAfter(), llvm::DIBuilder::insertDbgAssign(), llvm::DIBuilder::insertDbgValueIntrinsic(), llvm::DIBuilder::insertDeclare(), llvm::DIBuilder::insertLabel(), insertLifetimeMarkersSurroundingCall(), insertNewDbgInst(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::invertCondition(), IsAcceptableTarget(), llvm::Loop::isAuxiliaryInductionVariable(), isBlockInLCSSAForm(), isColdCallSite(), llvm::isControlFlowEquivalent(), llvm::isCriticalEdge(), isEqualImpl(), isFoldableInLoop(), isGuaranteedNotToBeUndefOrPoison(), llvm::ICFLoopSafetyInfo::isGuaranteedToExecute(), llvm::SimpleLoopSafetyInfo::isGuaranteedToExecute(), llvm::isInTailCallPosition(), isIntegerLoopHeaderPHI(), llvm::isIntrinsicReturningPointerAliasingArgumentWithoutCapturing(), isKnownNonNullFromDominatingCondition(), llvm::ScalarEvolution::isKnownPredicateAt(), isLocalAlloca(), isNonEqualPHIs(), isNotUsedOrFoldableInLoop(), isPowerOfTwoRecurrence(), isPredicatedOnPHI(), llvm::isReachedBefore(), isSafePHIToSpeculate(), llvm::SCEVExpander::isSafeToExpandAt(), llvm::isSafeToLoadUnconditionally(), isSafeToSinkLoad(), isSameUnderlyingObjectInLoop(), llvm::isValidAssumeForContext(), llvm::AA::isValidAtPosition(), isValidCandidateForColdCC(), liesBetween(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::makeGuardControlFlowExplicit(), llvm::Loop::makeLoopInvariant(), matchAddReduction(), llvm::SITargetLowering::mayBeEmittedAsTailCall(), MayContainThrowingOrExitingCallAfterCB(), memoryIsNotModifiedBetween(), mergeCleanupPad(), MergeCompatibleInvokesImpl(), mergeConditionalStores(), mergeConditionalStoreToAddress(), mergeNestedCondBranch(), llvm::Instruction::moveAfter(), llvm::Instruction::moveAfterPreserving(), moveBBContents(), llvm::Instruction::moveBefore(), llvm::Instruction::moveBeforePreserving(), llvm::sandboxir::MoveInstr::MoveInstr(), llvm::LoopInfo::movementPreservesLCSSAForm(), llvm::InstDeleterIRStrategy::mutate(), NegateValue(), nextIRInstructionDataMatchesNextInst(), optimizeBranch(), OptimizeExtractBits(), optimizeSQRT(), performBranchToCommonDestFolding(), llvm::JumpThreadingPass::processBlock(), llvm::JumpThreadingPass::processBranchOnPHI(), llvm::JumpThreadingPass::processBranchOnXOR(), processUse(), llvm::promoteLoopAccessesToScalars(), llvm::AssumptionCache::registerAssumption(), rematerializeLiveValuesAtUses(), removeEmptyCleanup(), llvm::sandboxir::RemoveFromParent::RemoveFromParent(), llvm::InstructionPrecedenceTracking::removeInstruction(), llvm::DbgMarker::removeMarker(), removeTriviallyEmptyRange(), replaceArgumentUses(), replaceAsyncResumeFunction(), ReplaceCallWith(), replaceConditionalBranchesOnConstant(), replaceExtractElements(), replaceWithGEP(), returnEdge(), reuseTableCompare(), rewriteDebugUsers(), llvm::rewriteLoopExitValues(), rewriteSingleStoreAlloca(), RewriteUsesOfClonedInstructions(), llvm::InstCombinerImpl::run(), llvm::LoopConstrainer::run(), llvm::SyntheticCountsPropagation::run(), llvm::PlaceSafepointsPass::runImpl(), runImpl(), runMoveAutoInit(), safeCxtI(), safeCxtI(), SafeToMergeTerminators(), scalarizeMaskedCompressStore(), scalarizeMaskedExpandLoad(), scalarizeMaskedGather(), scalarizeMaskedLoad(), scalarizeMaskedScatter(), scalarizeMaskedStore(), scalarizeMaskedVectorHistogram(), llvm::IRSimilarity::IRInstructionData::setBranchSuccessors(), llvm::IRSimilarity::IRInstructionData::setPHIPredecessors(), llvm::setProfMetadata(), shouldFoldCondBranchesToCommonDestination(), llvm::AArch64TargetLowering::shouldSinkOperands(), shouldSplitOnPHIPredicatedArgument(), shouldSplitOnPredicatedArgument(), SimplifyCondBranchToCondBranch(), simplifyInstructionWithPHI(), simplifyOneLoop(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), simplifyRelocatesOffABase(), simplifySuspendPoint(), llvm::simplifyUsersOfIV(), simplifyUsingControlFlow(), sink(), sinkAndCmp0Expression(), SinkCast(), SinkInstruction(), sinkInstruction(), sinkLifetimeStartMarkers(), llvm::InnerLoopVectorizer::sinkScalarOperands(), SinkShiftAndTruncate(), sinkSpillUsesAfterCoroBegin(), sinkThroughTriviallyReplaceablePHI(), splitBeforeCatchSwitch(), llvm::SplitBlockAndInsertSimpleForLoop(), splitCallSite(), llvm::OutlinableRegion::splitCandidate(), llvm::SplitKnownCriticalEdge(), splitPredecessorsOfLoopExit(), targetParallelCallback(), llvm::PHITransAddr::translateValue(), llvm::tryPromoteCall(), llvm::FastISel::tryToFoldLoad(), tryToMoveFreeBeforeNullTest(), llvm::JumpThreadingPass::tryToUnfoldSelect(), llvm::JumpThreadingPass::tryToUnfoldSelect(), tryUnmergingGEPsAcrossIndirectBr(), tryWidenCondBranchToCondBranch(), turnGuardIntoBranch(), turnToExplicitForm(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), updateIDTMetaData(), updateKillStatus(), llvm::JumpThreadingPass::updateSSA(), updateSuccessor(), llvm::UpgradeARCRuntime(), upgradeDbgIntrinsicToDbgRecord(), llvm::UpgradeIntrinsicCall(), valueEscapes(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), versionCallSiteWithCond(), llvm::InstCombinerImpl::visitAllocaInst(), llvm::InstCombinerImpl::visitBranchInst(), llvm::ObjectSizeOffsetVisitor::visitLoadInst(), llvm::InstCombinerImpl::visitPHINode(), and workshareLoopTargetCallback().
setParent()
template<class NodeTy , class ParentTy > void llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::setParent (ParentTy * Parent) inline
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-19.1.0/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 38 of file ilist_node.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/ilist_node.h