LLVM: llvm::DbgVariableRecord Class Reference
llvm::DbgVariableRecord Class Reference
Record of a variable value-assignment, aka a non instruction representation of the dbg.value intrinsic.
#include "llvm/IR/DebugProgramInstruction.h"
Classes
class location_op_iterator
Iterator for ValueAsMetadata that internally uses direct pointer iteration over either a ValueAsMetadata* or a ValueAsMetadata**, dereferencing to the ValueAsMetadata .
Public Types
enum class LocationType : uint8_t {
Declare , Value , Assign , End ,
Any
}
Public Types inherited from llvm::DbgRecord
enum Kind : uint8_t { ValueKind , LabelKind }
Subclass discriminator.
using self_iterator = simple_ilist<DbgRecord>::iterator
using const_self_iterator = simple_ilist<DbgRecord>::const_iterator
Public Member Functions
DbgVariableRecord (const DbgVariableIntrinsic *DVI)
Create a new DbgVariableRecord representing the intrinsic DVI, for example the assignment represented by a dbg.value.
DbgVariableRecord (const DbgVariableRecord &DVR)
DbgVariableRecord (Metadata *Location, DILocalVariable *DV, DIExpression *Expr, const DILocation *DI, LocationType Type=LocationType::Value)
Directly construct a new DbgVariableRecord representing a dbg.value intrinsic assigning Location to the DV / Expr / DI variable.
DbgVariableRecord (Metadata *Value, DILocalVariable *Variable, DIExpression *Expression, DIAssignID *AssignID, Metadata *Address, DIExpression *AddressExpression, const DILocation *DI)
bool isDbgDeclare ()
bool isDbgValue ()
iterator_range< location_op_iterator > location_ops () const
Get the locations corresponding to the variable referenced by the debug info intrinsic.
Value * getVariableLocationOp (unsigned OpIdx) const
void replaceVariableLocationOp (Value *OldValue, Value *NewValue, bool AllowEmpty=false)
void replaceVariableLocationOp (unsigned OpIdx, Value *NewValue)
void addVariableLocationOps (ArrayRef< Value * > NewValues, DIExpression *NewExpr)
Adding a new location operand will always result in this intrinsic using an ArgList, and must always be accompanied by a new expression that uses the new operand.
unsigned getNumVariableLocationOps () const
bool hasArgList () const
bool hasValidLocation () const
Returns true if this DbgVariableRecord has no empty MDNodes in its location list.
bool isAddressOfVariable () const
Does this describe the address of a local variable.
LocationType getType () const
void setKillLocation ()
bool isKillLocation () const
void setVariable (DILocalVariable *NewVar)
DILocalVariable * getVariable () const
MDNode * getRawVariable () const
void setExpression (DIExpression *NewExpr)
DIExpression * getExpression () const
MDNode * getRawExpression () const
Metadata * getRawLocation () const
Returns the metadata operand for the first location description.
Value * getValue (unsigned OpIdx=0) const
void setRawLocation (Metadata *NewLocation)
Use of this should generally be avoided; instead, replaceVariableLocationOp and addVariableLocationOps should be used where possible to avoid creating invalid state.
std::optional< DbgVariableFragmentInfo > getFragment () const
DbgVariableFragmentInfo getFragmentOrEntireVariable () const
Get the FragmentInfo for the variable if it exists, otherwise return a FragmentInfo that covers the entire variable if the variable size is known, otherwise return a zero-sized fragment.
std::optional< uint64_t > getFragmentSizeInBits () const
Get the size (in bits) of the variable, or fragment of the variable that is described.
bool isEquivalentTo (const DbgVariableRecord &Other) const
bool isIdenticalToWhenDefined (const DbgVariableRecord &Other) const
DbgVariableRecord * clone () const
DbgVariableIntrinsic * createDebugIntrinsic (Module *M, Instruction *InsertBefore) const
Convert this DbgVariableRecord back into a dbg.value intrinsic.
void handleChangedLocation (Metadata *NewLocation)
Handle changes to the location of the Value(s) that we refer to happening "under our feet".
void print (raw_ostream &O, bool IsForDebug=false) const
void print (raw_ostream &ROS, ModuleSlotTracker &MST, bool IsForDebug) const
DbgAssign Methods
bool isDbgAssign () const
Value * getAddress () const
Metadata * getRawAddress () const
Metadata * getRawAssignID () const
DIAssignID * getAssignID () const
DIExpression * getAddressExpression () const
MDNode * getRawAddressExpression () const
void setAddressExpression (DIExpression *NewExpr)
void setAssignId (DIAssignID *New)
void setAddress (Value *V)
void setKillAddress ()
Kill the address component.
bool isKillAddress () const
Check whether this kills the address component.
Public Member Functions inherited from llvm::DbgRecord
DbgRecord (Kind RecordKind, DebugLoc DL)
bool isEquivalentTo (const DbgRecord &R) const
Same as isIdenticalToWhenDefined but checks DebugLoc too.
Kind getRecordKind () const
void setMarker (DbgMarker *M)
DbgMarker * getMarker ()
const DbgMarker * getMarker () const
BasicBlock * getBlock ()
const BasicBlock * getBlock () const
Function * getFunction ()
const Function * getFunction () const
Module * getModule ()
const Module * getModule () const
LLVMContext & getContext ()
const LLVMContext & getContext () const
const Instruction * getInstruction () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
void removeFromParent ()
void eraseFromParent ()
DbgRecord * getNextNode ()
DbgRecord * getPrevNode ()
void insertBefore (DbgRecord *InsertBefore)
void insertAfter (DbgRecord *InsertAfter)
void moveBefore (DbgRecord *MoveBefore)
void moveAfter (DbgRecord *MoveAfter)
DebugLoc getDebugLoc () const
void setDebugLoc (DebugLoc Loc)
void dump () const
void deleteRecord ()
Methods that dispatch to subclass implementations.
DbgRecord * clone () const
void print (raw_ostream &O, bool IsForDebug=false) const
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug) const
bool isIdenticalToWhenDefined (const DbgRecord &R) const
DbgInfoIntrinsic * createDebugIntrinsic (Module *M, Instruction *InsertBefore) const
Convert this DbgRecord back into an appropriate llvm.dbg.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< DbgRecord, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< DbgRecord, Options... >::type >, ilist_detail::compute_node_options< DbgRecord, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< DbgRecord, Options... >::type::parent_ty * getParent () const
ilist_detail::compute_node_options< DbgRecord, Options... >::type::parent_ty * getParent ()
void setParent (ilist_detail::compute_node_options< DbgRecord, Options... >::type::parent_ty *Parent)
Static Public Member Functions
static DbgVariableRecord * createUnresolvedDbgVariableRecord (LocationType Type, Metadata *Val, MDNode *Variable, MDNode *Expression, MDNode *AssignID, Metadata *Address, MDNode *AddressExpression, MDNode *DI)
Used to create DbgVariableRecords during parsing, where some metadata references may still be unresolved.
static DbgVariableRecord * createDVRAssign (Value *Val, DILocalVariable *Variable, DIExpression *Expression, DIAssignID *AssignID, Value *Address, DIExpression *AddressExpression, const DILocation *DI)
static DbgVariableRecord * createLinkedDVRAssign (Instruction *LinkedInstr, Value *Val, DILocalVariable *Variable, DIExpression *Expression, Value *Address, DIExpression *AddressExpression, const DILocation *DI)
static DbgVariableRecord * createDbgVariableRecord (Value *Location, DILocalVariable *DV, DIExpression *Expr, const DILocation *DI)
static DbgVariableRecord * createDbgVariableRecord (Value *Location, DILocalVariable *DV, DIExpression *Expr, const DILocation *DI, DbgVariableRecord &InsertBefore)
static DbgVariableRecord * createDVRDeclare (Value *Address, DILocalVariable *DV, DIExpression *Expr, const DILocation *DI)
static DbgVariableRecord * createDVRDeclare (Value *Address, DILocalVariable *DV, DIExpression *Expr, const DILocation *DI, DbgVariableRecord &InsertBefore)
static bool classof (const DbgRecord *E)
Support type inquiry through isa, cast, and dyn_cast.
Public Attributes
LocationType Type
Classification of the debug-info record that this DbgVariableRecord represents.
DbgRecordParamRef< DILocalVariable > Variable
DbgRecordParamRef< DIExpression > Expression
DbgRecordParamRef< DIExpression > AddressExpression
Public Attributes inherited from llvm::DbgRecord
DbgMarker * Marker = nullptr
Marker that this DbgRecord is linked into.
Friends
class DebugValueUser
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< DbgRecord, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::DbgRecord
~DbgRecord ()=default
Similarly to Value, we avoid paying the cost of a vtable by protecting the dtor and having deleteRecord dispatch cleanup.
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< DbgRecord, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::DebugValueUser
ArrayRef< Metadata * > getDebugValues () const
DbgVariableRecord * getUser ()
const DbgVariableRecord * getUser () const
void handleChangedValue (void *Old, Metadata *NewDebugValue)
To be called by ReplaceableMetadataImpl::replaceAllUsesWith, where Old is a pointer to one of the pointers in DebugValues (so should be type Metadata**), and NewDebugValue is the new Metadata* that is replacing *Old.
DebugValueUser ()=default
DebugValueUser (std::array< Metadata *, 3 > DebugValues)
DebugValueUser (DebugValueUser &&X)
DebugValueUser (const DebugValueUser &X)
DebugValueUser & operator= (DebugValueUser &&X)
DebugValueUser & operator= (const DebugValueUser &X)
~DebugValueUser ()
void resetDebugValues ()
void resetDebugValue (size_t Idx, Metadata *DebugValue)
bool operator== (const DebugValueUser &X) const
bool operator!= (const DebugValueUser &X) const
Protected Attributes inherited from llvm::DbgRecord
DebugLoc DbgLoc
Kind RecordKind
Subclass discriminator.
Protected Attributes inherited from llvm::DebugValueUser
std::array< Metadata *, 3 > DebugValues
Detailed Description
Record of a variable value-assignment, aka a non instruction representation of the dbg.value intrinsic.
This class inherits from DebugValueUser to allow LLVM's metadata facilities to update our references to metadata beneath our feet.
Definition at line 262 of file DebugProgramInstruction.h.
Member Enumeration Documentation
LocationType
enum class llvm::DbgVariableRecord::LocationType : uint8_t strong
Enumerator
Declare
Value
Assign
End
Marks the end of the concrete types.
Any
To indicate all LocationTypes in searches.
Definition at line 266 of file DebugProgramInstruction.h.
Constructor & Destructor Documentation
DbgVariableRecord() [1/4]
llvm::DbgVariableRecord::DbgVariableRecord (const DbgVariableIntrinsic * DVI)
Create a new DbgVariableRecord representing the intrinsic DVI, for example the assignment represented by a dbg.value.
Definition at line 31 of file DebugProgramInstruction.cpp.
References llvm::DbgVariableIntrinsic::getRawLocation().
Referenced by clone(), createDbgVariableRecord(), createDVRAssign(), createDVRDeclare(), and createUnresolvedDbgVariableRecord().
DbgVariableRecord() [2/4]
llvm::DbgVariableRecord::DbgVariableRecord (const DbgVariableRecord & DVR)
Definition at line 58 of file DebugProgramInstruction.cpp.
DbgVariableRecord() [3/4]
llvm::DbgVariableRecord::DbgVariableRecord (Metadata * Location, DILocalVariable * DV, DIExpression * Expr, const DILocation * DI, LocationType Type = LocationType::Value)
Directly construct a new DbgVariableRecord representing a dbg.value intrinsic assigning Location to the DV / Expr / DI variable.
Definition at line 64 of file DebugProgramInstruction.cpp.
DbgVariableRecord() [4/4]
llvm::DbgVariableRecord::DbgVariableRecord (Metadata * Value, DILocalVariable * Variable, DIExpression * Expression, DIAssignID * AssignID, Metadata * Address, DIExpression * AddressExpression, const DILocation * DI)
Definition at line 70 of file DebugProgramInstruction.cpp.
References llvm::Address, and Value.
Member Function Documentation
addVariableLocationOps()
void llvm::DbgVariableRecord::addVariableLocationOps (ArrayRef< Value * > NewValues, DIExpression * NewExpr)
Adding a new location operand will always result in this intrinsic using an ArgList, and must always be accompanied by a new expression that uses the new operand.
Definition at line 340 of file DebugProgramInstruction.cpp.
References assert(), llvm::DIArgList::get(), llvm::getAsMetadata(), llvm::DbgRecord::getContext(), getNumVariableLocationOps(), getVariableLocationOp(), llvm::is_contained(), location_ops(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), setExpression(), setRawLocation(), and llvm::ArrayRef< T >::size().
classof()
static bool llvm::DbgVariableRecord::classof (const DbgRecord * E) inline static
Support type inquiry through isa, cast, and dyn_cast.
Definition at line 535 of file DebugProgramInstruction.h.
References llvm::DbgRecord::ValueKind.
clone()
DbgVariableRecord * llvm::DbgVariableRecord::clone () const
Definition at line 394 of file DebugProgramInstruction.cpp.
References DbgVariableRecord().
Referenced by insertDbgVariableRecordsForPHIs().
createDbgVariableRecord() [1/2]
DbgVariableRecord * llvm::DbgVariableRecord::createDbgVariableRecord (Value * Location, DILocalVariable * DV, DIExpression * Expr, const DILocation * DI) static
Definition at line 179 of file DebugProgramInstruction.cpp.
References DbgVariableRecord(), llvm::ValueAsMetadata::get(), and Value.
Referenced by createDbgVariableRecord().
createDbgVariableRecord() [2/2]
DbgVariableRecord * llvm::DbgVariableRecord::createDbgVariableRecord (Value * Location, DILocalVariable * DV, DIExpression * Expr, const DILocation * DI, DbgVariableRecord & InsertBefore) static
Definition at line 186 of file DebugProgramInstruction.cpp.
References createDbgVariableRecord().
createDebugIntrinsic()
DbgVariableIntrinsic * llvm::DbgVariableRecord::createDebugIntrinsic (Module * M, Instruction * InsertBefore) const
Convert this DbgVariableRecord back into a dbg.value intrinsic.
InsertBefore Optional position to insert this intrinsic.
Returns
A new dbg.value intrinsic representiung this DbgVariableRecord.
Definition at line 403 of file DebugProgramInstruction.cpp.
References Any, assert(), Assign, llvm::cast(), llvm::CallInst::Create(), Declare, End, llvm::MetadataAsValue::get(), getAddressExpression(), getAssignID(), llvm::MDNode::getContext(), llvm::DbgRecord::getDebugLoc(), llvm::Intrinsic::getDeclaration(), getExpression(), llvm::Function::getFunctionType(), getRawAddress(), getRawLocation(), getType(), getVariable(), llvm::Instruction::insertBefore(), isDbgAssign(), llvm_unreachable, llvm::Instruction::setDebugLoc(), llvm::CallInst::setTailCall(), and Value.
createDVRAssign()
DbgVariableRecord * llvm::DbgVariableRecord::createDVRAssign (Value * Val, DILocalVariable * Variable, DIExpression * Expression, DIAssignID * AssignID, Value * Address, DIExpression * AddressExpression, const DILocation * DI) static
Definition at line 211 of file DebugProgramInstruction.cpp.
References AddressExpression, DbgVariableRecord(), llvm::ValueAsMetadata::get(), and Variable.
Referenced by createLinkedDVRAssign(), and llvm::DIBuilder::insertDbgAssign().
createDVRDeclare() [1/2]
DbgVariableRecord * llvm::DbgVariableRecord::createDVRDeclare (Value * Address, DILocalVariable * DV, DIExpression * Expr, const DILocation * DI) static
Definition at line 194 of file DebugProgramInstruction.cpp.
References DbgVariableRecord(), Declare, and llvm::ValueAsMetadata::get().
Referenced by createDVRDeclare(), and insertNewDbgInst().
createDVRDeclare() [2/2]
DbgVariableRecord * llvm::DbgVariableRecord::createDVRDeclare (Value * Address, DILocalVariable * DV, DIExpression * Expr, const DILocation * DI, DbgVariableRecord & InsertBefore) static
Definition at line 203 of file DebugProgramInstruction.cpp.
References createDVRDeclare().
createLinkedDVRAssign()
DbgVariableRecord * llvm::DbgVariableRecord::createLinkedDVRAssign (Instruction * LinkedInstr, Value * Val, DILocalVariable * Variable, DIExpression * Expression, Value * Address, DIExpression * AddressExpression, const DILocation * DI) static
Definition at line 220 of file DebugProgramInstruction.cpp.
References AddressExpression, assert(), llvm::cast(), createDVRAssign(), llvm::Instruction::getMetadata(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), and Variable.
Referenced by emitDbgAssign(), and insertNewDbgInst().
createUnresolvedDbgVariableRecord()
DbgVariableRecord * llvm::DbgVariableRecord::createUnresolvedDbgVariableRecord (DbgVariableRecord::LocationType Type, Metadata * Val, MDNode * Variable, MDNode * Expression, MDNode * AssignID, Metadata * Address, MDNode * AddressExpression, MDNode * DI) static
Used to create DbgVariableRecords during parsing, where some metadata references may still be unresolved.
Although for some fields a generic Metadata* argument is accepted for forward type-references, the verifier and accessors will reject incorrect types later on. The function is used for all types of DbgVariableRecords for simplicity while parsing, but asserts if any necessary fields are empty or unused fields are not empty, i.e. if the #dbg_assign fields are used for a non-dbg-assign type.
Definition at line 170 of file DebugProgramInstruction.cpp.
References AddressExpression, DbgVariableRecord(), and Variable.
getAddress()
Value * llvm::DbgVariableRecord::getAddress () const
Definition at line 474 of file DebugProgramInstruction.cpp.
References assert(), llvm::cast(), llvm::dyn_cast_or_null(), and getRawAddress().
Referenced by fixupDebugInfoPostExtraction(), getAddress(), isKillAddress(), replaceVariableLocationOp(), and setKillAddress().
getAddressExpression()
DIExpression * llvm::DbgVariableRecord::getAddressExpression () const inline
Definition at line 501 of file DebugProgramInstruction.h.
References AddressExpression, and llvm::MDNode::get().
Referenced by createDebugIntrinsic(), getAddressExpression(), and llvm::ValueEnumerator::ValueEnumerator().
getAssignID()
DIAssignID * llvm::DbgVariableRecord::getAssignID () const
Definition at line 485 of file DebugProgramInstruction.cpp.
References llvm::cast(), and llvm::DebugValueUser::DebugValues.
Referenced by createDebugIntrinsic(), llvm::at::getAssignmentInsts(), getIDFromMarker(), and llvm::ValueEnumerator::ValueEnumerator().
getExpression()
DIExpression * llvm::DbgVariableRecord::getExpression () const inline
Definition at line 440 of file DebugProgramInstruction.h.
Referenced by buildOverlapMapAndRecordDeclares(), llvm::ConvertDebugDeclareToDebugValue(), llvm::ConvertDebugDeclareToDebugValue(), llvm::ConvertDebugDeclareToDebugValue(), createDebugIntrinsic(), DbgVariableRecordsRemoveRedundantDbgInstrsUsingBackwardScan(), getAddressExpression(), getFragment(), getFragmentSizeInBits(), llvm::FastISel::handleDbgInfo(), insertNewDbgInst(), isKillLocation(), llvm::coro::salvageDebugInfo(), valueCoversEntireFragment(), llvm::ValueEnumerator::ValueEnumerator(), and llvm::SelectionDAGBuilder::visitDbgInfo().
getFragment()
std::optional< DbgVariableFragmentInfo > llvm::DbgVariableRecord::getFragment () const
Definition at line 374 of file DebugProgramInstruction.cpp.
References getExpression(), and llvm::DIExpression::getFragmentInfo().
Referenced by getFragmentOrEntireVariable().
getFragmentOrEntireVariable()
DbgVariableFragmentInfo llvm::DbgVariableRecord::getFragmentOrEntireVariable () const inline
Get the FragmentInfo for the variable if it exists, otherwise return a FragmentInfo that covers the entire variable if the variable size is known, otherwise return a zero-sized fragment.
Definition at line 468 of file DebugProgramInstruction.h.
References getFragment(), and getFragmentSizeInBits().
getFragmentSizeInBits()
std::optional< uint64_t > llvm::DbgVariableRecord::getFragmentSizeInBits () const
Get the size (in bits) of the variable, or fragment of the variable that is described.
Definition at line 378 of file DebugProgramInstruction.cpp.
References getExpression(), llvm::DIVariable::getSizeInBits(), and getVariable().
Referenced by getFragmentOrEntireVariable().
getNumVariableLocationOps()
unsigned llvm::DbgVariableRecord::getNumVariableLocationOps () const
Definition at line 257 of file DebugProgramInstruction.cpp.
References llvm::cast(), getRawLocation(), and hasArgList().
Referenced by addVariableLocationOps(), isKillLocation(), replaceVariableLocationOp(), and valueCoversEntireFragment().
getRawAddress()
Metadata * llvm::DbgVariableRecord::getRawAddress () const inline
Definition at line 496 of file DebugProgramInstruction.h.
References llvm::DebugValueUser::DebugValues, and isDbgAssign().
Referenced by createDebugIntrinsic(), getAddress(), and llvm::ValueEnumerator::ValueEnumerator().
getRawAddressExpression()
MDNode * llvm::DbgVariableRecord::getRawAddressExpression () const inline
Definition at line 502 of file DebugProgramInstruction.h.
References AddressExpression.
getRawAssignID()
Metadata * llvm::DbgVariableRecord::getRawAssignID () const inline
Definition at line 499 of file DebugProgramInstruction.h.
References llvm::DebugValueUser::DebugValues.
getRawExpression()
MDNode * llvm::DbgVariableRecord::getRawExpression () const inline
Definition at line 441 of file DebugProgramInstruction.h.
getRawLocation()
Metadata * llvm::DbgVariableRecord::getRawLocation () const inline
Returns the metadata operand for the first location description.
i.e., dbg intrinsic dbg.value,declare operand and dbg.assign 1st location operand (the "value componenet"). Note the operand (singular) may be a DIArgList which is a list of values.
Definition at line 447 of file DebugProgramInstruction.h.
References llvm::DebugValueUser::DebugValues.
Referenced by buildOverlapMapAndRecordDeclares(), createDebugIntrinsic(), getNumVariableLocationOps(), getVariableLocationOp(), hasArgList(), isKillLocation(), location_ops(), and llvm::ValueEnumerator::ValueEnumerator().
getRawVariable()
MDNode * llvm::DbgVariableRecord::getRawVariable () const inline
Definition at line 437 of file DebugProgramInstruction.h.
References Variable.
getType()
LocationType llvm::DbgVariableRecord::getType () const inline
Definition at line 430 of file DebugProgramInstruction.h.
References Type.
Referenced by createDebugIntrinsic(), DbgVariableRecordsRemoveRedundantDbgInstrsUsingBackwardScan(), getAddress(), getAddressExpression(), llvm::FastISel::handleDbgInfo(), isDbgAssign(), isKillAddress(), llvm::coro::salvageDebugInfo(), setKillAddress(), and llvm::SelectionDAGBuilder::visitDbgInfo().
getValue()
Value * llvm::DbgVariableRecord::getValue (unsigned OpIdx = 0) const inline
Definition at line 449 of file DebugProgramInstruction.h.
References getVariableLocationOp().
Referenced by insertNewDbgInst().
getVariable()
DILocalVariable * llvm::DbgVariableRecord::getVariable () const inline
Definition at line 436 of file DebugProgramInstruction.h.
References llvm::MDNode::get(), and Variable.
Referenced by buildFrameDebugInfo(), llvm::ConvertDebugDeclareToDebugValue(), llvm::ConvertDebugDeclareToDebugValue(), llvm::ConvertDebugDeclareToDebugValue(), createDebugIntrinsic(), DbgVariableRecordsRemoveRedundantDbgInstrsUsingBackwardScan(), findVarsWithStackSlot(), fixupDebugInfoPostExtraction(), getAggregateVariable(), getFragmentSizeInBits(), llvm::FastISel::handleDbgInfo(), insertNewDbgInst(), valueCoversEntireFragment(), llvm::ValueEnumerator::ValueEnumerator(), and llvm::SelectionDAGBuilder::visitDbgInfo().
getVariableLocationOp()
Value * llvm::DbgVariableRecord::getVariableLocationOp (unsigned OpIdx) const
Definition at line 263 of file DebugProgramInstruction.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), getRawLocation(), and llvm::isa().
Referenced by addVariableLocationOps(), getValue(), llvm::FastISel::handleDbgInfo(), hasValidLocation(), replaceVariableLocationOp(), replaceVariableLocationOp(), llvm::coro::salvageDebugInfo(), valueCoversEntireFragment(), and llvm::SelectionDAGBuilder::visitDbgInfo().
handleChangedLocation()
void llvm::DbgVariableRecord::handleChangedLocation (Metadata * NewLocation)
Handle changes to the location of the Value(s) that we refer to happening "under our feet".
hasArgList()
bool llvm::DbgVariableRecord::hasArgList () const inline
Definition at line 422 of file DebugProgramInstruction.h.
References getRawLocation(), and llvm::isa().
Referenced by getNumVariableLocationOps(), llvm::FastISel::handleDbgInfo(), isKillLocation(), replaceVariableLocationOp(), replaceVariableLocationOp(), and llvm::SelectionDAGBuilder::visitDbgInfo().
hasValidLocation()
bool llvm::DbgVariableRecord::hasValidLocation () const inline
Returns true if this DbgVariableRecord has no empty MDNodes in its location list.
Definition at line 425 of file DebugProgramInstruction.h.
References getVariableLocationOp().
isAddressOfVariable()
bool llvm::DbgVariableRecord::isAddressOfVariable () const inline
Does this describe the address of a local variable.
True for dbg.addr and dbg.declare, but not dbg.value, which describes its value.
Definition at line 429 of file DebugProgramInstruction.h.
References Declare.
Referenced by llvm::ConvertDebugDeclareToDebugValue(), and valueCoversEntireFragment().
isDbgAssign()
bool llvm::DbgVariableRecord::isDbgAssign () const inline
Definition at line 493 of file DebugProgramInstruction.h.
References Assign, and getType().
Referenced by CastToDbgAssign(), llvm::ConvertDebugDeclareToDebugValue(), createDebugIntrinsic(), DbgVariableRecordsRemoveRedundantDbgInstrsUsingBackwardScan(), llvm::memtag::DynCastToDbgAssign(), fixupDebugInfoPostExtraction(), llvm::at::getAssignmentInsts(), getIDFromMarker(), getRawAddress(), insertNewDbgInst(), replaceVariableLocationOp(), and llvm::ValueEnumerator::ValueEnumerator().
isDbgDeclare()
bool llvm::DbgVariableRecord::isDbgDeclare () inline
Definition at line 401 of file DebugProgramInstruction.h.
References Declare.
Referenced by DynCastToDbgDeclare(), insertNewDbgInst(), and llvm::coro::salvageDebugInfo().
isDbgValue()
bool llvm::DbgVariableRecord::isDbgValue () inline
Definition at line 402 of file DebugProgramInstruction.h.
References Value.
isEquivalentTo()
bool llvm::DbgVariableRecord::isEquivalentTo (const DbgVariableRecord & Other) const inline
Definition at line 479 of file DebugProgramInstruction.h.
References llvm::DbgRecord::DbgLoc, isIdenticalToWhenDefined(), and llvm::Other.
isIdenticalToWhenDefined()
bool llvm::DbgVariableRecord::isIdenticalToWhenDefined (const DbgVariableRecord & Other) const inline
Definition at line 484 of file DebugProgramInstruction.h.
References AddressExpression, llvm::DebugValueUser::DebugValues, llvm::Other, and Variable.
Referenced by isEquivalentTo().
isKillAddress()
bool llvm::DbgVariableRecord::isKillAddress () const
Check whether this kills the address component.
This doesn't take into account the position of the intrinsic, therefore a returned value of false does not guarentee the address is a valid location for the variable at the intrinsic's position in IR.
Definition at line 498 of file DebugProgramInstruction.cpp.
References Addr, getAddress(), and llvm::isa().
Referenced by isKillAddress().
isKillLocation()
bool llvm::DbgVariableRecord::isKillLocation () const
Definition at line 368 of file DebugProgramInstruction.cpp.
References llvm::any_of(), getExpression(), getNumVariableLocationOps(), getRawLocation(), hasArgList(), llvm::isa(), llvm::DIExpression::isComplex(), and location_ops().
Referenced by isKillAddress().
location_ops()
iterator_range< DbgVariableRecord::location_op_iterator > llvm::DbgVariableRecord::location_ops () const
Get the locations corresponding to the variable referenced by the debug info intrinsic.
Depending on the intrinsic, this could be the variable's value or its address.
Definition at line 234 of file DebugProgramInstruction.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), and getRawLocation().
Referenced by addVariableLocationOps(), fixupDebugInfoPostExtraction(), insertDbgVariableRecordsForPHIs(), isKillLocation(), replaceVariableLocationOp(), setKillLocation(), and llvm::SelectionDAGBuilder::visitDbgInfo().
print() [1/2]
void DbgVariableRecord::print (raw_ostream & O, bool IsForDebug = false) const
Definition at line 4962 of file AsmWriter.cpp.
References getModuleFromDPI(), and print().
print() [2/2]
void DbgVariableRecord::print (raw_ostream & ROS, ModuleSlotTracker & MST, bool IsForDebug) const
Definition at line 4989 of file AsmWriter.cpp.
References F, llvm::ModuleSlotTracker::getMachine(), getModuleFromDPI(), llvm::BasicBlock::getParent(), llvm::DbgMarker::getParent(), llvm::ModuleSlotTracker::incorporateFunction(), and OS.
replaceVariableLocationOp() [1/2]
void llvm::DbgVariableRecord::replaceVariableLocationOp (unsigned OpIdx, Value * NewValue)
Definition at line 320 of file DebugProgramInstruction.cpp.
References assert(), llvm::cast(), llvm::DIArgList::get(), llvm::ValueAsMetadata::get(), llvm::getAsMetadata(), llvm::DbgRecord::getContext(), getNumVariableLocationOps(), getVariableLocationOp(), hasArgList(), llvm::isa(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and setRawLocation().
replaceVariableLocationOp() [2/2]
void llvm::DbgVariableRecord::replaceVariableLocationOp (Value * OldValue, Value * NewValue, bool AllowEmpty = false)
Definition at line 286 of file DebugProgramInstruction.cpp.
References assert(), llvm::cast(), llvm::find(), llvm::DIArgList::get(), llvm::ValueAsMetadata::get(), getAddress(), llvm::getAsMetadata(), llvm::DbgRecord::getContext(), getVariableLocationOp(), hasArgList(), llvm::isa(), isDbgAssign(), llvm_unreachable, location_ops(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), setAddress(), and setRawLocation().
Referenced by insertDbgVariableRecordsForPHIs(), rewriteDebugUsers(), llvm::coro::salvageDebugInfo(), setKillLocation(), and updateOneDbgValueForAlloca().
setAddress()
void llvm::DbgVariableRecord::setAddress (Value * V) inline
Definition at line 509 of file DebugProgramInstruction.h.
References llvm::ValueAsMetadata::get(), and llvm::DebugValueUser::resetDebugValue().
Referenced by replaceVariableLocationOp().
setAddressExpression()
void llvm::DbgVariableRecord::setAddressExpression (DIExpression * NewExpr) inline
Definition at line 505 of file DebugProgramInstruction.h.
References AddressExpression.
setAssignId()
void llvm::DbgVariableRecord::setAssignId (DIAssignID * New)
Definition at line 489 of file DebugProgramInstruction.cpp.
References llvm::DebugValueUser::resetDebugValue().
setExpression()
void llvm::DbgVariableRecord::setExpression (DIExpression * NewExpr) inline
Definition at line 439 of file DebugProgramInstruction.h.
Referenced by addVariableLocationOps(), rewriteDebugUsers(), llvm::coro::salvageDebugInfo(), and updateOneDbgValueForAlloca().
setKillAddress()
void llvm::DbgVariableRecord::setKillAddress ()
Kill the address component.
Definition at line 493 of file DebugProgramInstruction.cpp.
References llvm::UndefValue::get(), llvm::ValueAsMetadata::get(), getAddress(), getType(), and llvm::DebugValueUser::resetDebugValue().
setKillLocation()
void llvm::DbgVariableRecord::setKillLocation ()
Definition at line 356 of file DebugProgramInstruction.cpp.
References llvm::PoisonValue::get(), llvm::SmallPtrSetImpl< PtrType >::insert(), location_ops(), Poison, and replaceVariableLocationOp().
setRawLocation()
void llvm::DbgVariableRecord::setRawLocation (Metadata * NewLocation) inline
Use of this should generally be avoided; instead, replaceVariableLocationOp and addVariableLocationOps should be used where possible to avoid creating invalid state.
Definition at line 456 of file DebugProgramInstruction.h.
References assert(), llvm::isa(), and llvm::DebugValueUser::resetDebugValue().
Referenced by addVariableLocationOps(), replaceVariableLocationOp(), and replaceVariableLocationOp().
setVariable()
void llvm::DbgVariableRecord::setVariable (DILocalVariable * NewVar) inline
Definition at line 435 of file DebugProgramInstruction.h.
References Variable.
Referenced by fixupDebugInfoPostExtraction().
Friends And Related Symbol Documentation
DebugValueUser
friend class DebugValueUser friend
Definition at line 263 of file DebugProgramInstruction.h.
Member Data Documentation
AddressExpression
DbgRecordParamRef<DIExpression> llvm::DbgVariableRecord::AddressExpression
Definition at line 286 of file DebugProgramInstruction.h.
Referenced by createDVRAssign(), createLinkedDVRAssign(), createUnresolvedDbgVariableRecord(), getAddressExpression(), getRawAddressExpression(), isIdenticalToWhenDefined(), and setAddressExpression().
Expression
DbgRecordParamRef<DIExpression> llvm::DbgVariableRecord::Expression
Definition at line 285 of file DebugProgramInstruction.h.
Type
LocationType llvm::DbgVariableRecord::Type
Classification of the debug-info record that this DbgVariableRecord represents.
Essentially, "does this correspond to a dbg.value, dbg.declare, or dbg.assign?". FIXME: We could use spare padding bits from DbgRecord for this.
Definition at line 278 of file DebugProgramInstruction.h.
Referenced by getType().
Variable
DbgRecordParamRef<DILocalVariable> llvm::DbgVariableRecord::Variable
Definition at line 284 of file DebugProgramInstruction.h.
Referenced by createDVRAssign(), createLinkedDVRAssign(), createUnresolvedDbgVariableRecord(), getRawVariable(), getVariable(), isIdenticalToWhenDefined(), and setVariable().
The documentation for this class was generated from the following files:
include/llvm/IR/DebugProgramInstruction.h
lib/IR/AsmWriter.cpp
lib/IR/DebugProgramInstruction.cpp