LLVM: llvm::pdb::DIAFrameData Class Reference
llvm::pdb::DIAFrameData Class Reference
#include "llvm/DebugInfo/PDB/DIA/DIAFrameData.h"
Public Member Functions
DIAFrameData (CComPtr< IDiaFrameData > DiaFrameData)
uint32_t getAddressOffset () const override
uint32_t getAddressSection () const override
uint32_t getLengthBlock () const override
std::string getProgram () const override
uint32_t getRelativeVirtualAddress () const override
uint64_t getVirtualAddress () const override
Public Member Functions inherited from llvm::pdb::IPDBFrameData
virtual ~IPDBFrameData ()
Detailed Description
Definition at line 20 of file DIAFrameData.h.
Constructor & Destructor Documentation
DIAFrameData()
DIAFrameData::DIAFrameData (CComPtr< IDiaFrameData > DiaFrameData) explicit
Definition at line 15 of file DIAFrameData.cpp.
Member Function Documentation
getAddressOffset()
uint32_t DIAFrameData::getAddressOffset () const override virtual
Implements llvm::pdb::IPDBFrameData.
Definition at line 29 of file DIAFrameData.cpp.
References PrivateGetDIAValue().
getAddressSection()
uint32_t DIAFrameData::getAddressSection () const override virtual
Implements llvm::pdb::IPDBFrameData.
Definition at line 33 of file DIAFrameData.cpp.
References PrivateGetDIAValue().
getLengthBlock()
uint32_t DIAFrameData::getLengthBlock () const override virtual
Implements llvm::pdb::IPDBFrameData.
Definition at line 37 of file DIAFrameData.cpp.
References PrivateGetDIAValue().
getProgram()
std::string DIAFrameData::getProgram () const override virtual
Implements llvm::pdb::IPDBFrameData.
Definition at line 41 of file DIAFrameData.cpp.
References invokeBstrMethod().
getRelativeVirtualAddress()
uint32_t DIAFrameData::getRelativeVirtualAddress () const override virtual
Implements llvm::pdb::IPDBFrameData.
Definition at line 45 of file DIAFrameData.cpp.
References PrivateGetDIAValue().
getVirtualAddress()
uint64_t DIAFrameData::getVirtualAddress () const override virtual
Implements llvm::pdb::IPDBFrameData.
Definition at line 50 of file DIAFrameData.cpp.
References PrivateGetDIAValue().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/DIA/DIAFrameData.h
lib/DebugInfo/PDB/DIA/DIAFrameData.cpp