LLVM: SlotIndexUpdateDelegate Class Reference
SlotIndexUpdateDelegate Class Reference
Public Member Functions
SlotIndexUpdateDelegate (MachineFunction &MF, SlotIndexes *Indexes)
~SlotIndexUpdateDelegate ()
void MF_HandleInsertion (MachineInstr &MI) override
Callback after an insertion. This should not modify the MI directly.
void MF_HandleRemoval (MachineInstr &MI) override
Callback before a removal. This should not modify the MI directly.
Public Member Functions inherited from llvm::MachineFunction::Delegate
virtual ~Delegate ()=default
virtual void MF_HandleChangeDesc (MachineInstr &MI, const MCInstrDesc &TID)
Callback before changing MCInstrDesc.
Detailed Description
Definition at line 1108 of file MachineBasicBlock.cpp.
Constructor & Destructor Documentation
SlotIndexUpdateDelegate()
SlotIndexUpdateDelegate::SlotIndexUpdateDelegate (MachineFunction & MF, SlotIndexes * Indexes) inline
Definition at line 1115 of file MachineBasicBlock.cpp.
References llvm::MachineFunction::setDelegate().
~SlotIndexUpdateDelegate()
SlotIndexUpdateDelegate::~SlotIndexUpdateDelegate () inline
Definition at line 1120 of file MachineBasicBlock.cpp.
References llvm::SlotIndexes::insertMachineInstrInMaps(), MI, and llvm::MachineFunction::resetDelegate().
Member Function Documentation
MF_HandleInsertion()
void SlotIndexUpdateDelegate::MF_HandleInsertion (MachineInstr & MI) inline override virtual
Callback after an insertion. This should not modify the MI directly.
Implements llvm::MachineFunction::Delegate.
Definition at line 1126 of file MachineBasicBlock.cpp.
References llvm::SetVector< T, Vector, Set, N >::insert(), and MI.
MF_HandleRemoval()
void SlotIndexUpdateDelegate::MF_HandleRemoval (MachineInstr & MI) inline override virtual
Callback before a removal. This should not modify the MI directly.
Implements llvm::MachineFunction::Delegate.
Definition at line 1132 of file MachineBasicBlock.cpp.
References MI, llvm::SetVector< T, Vector, Set, N >::remove(), and llvm::SlotIndexes::removeMachineInstrFromMaps().
The documentation for this class was generated from the following file:
lib/CodeGen/MachineBasicBlock.cpp