LLVM: llvm::ModuloScheduleExpanderMVE Class Reference
llvm::ModuloScheduleExpanderMVE Class Reference
Expand the kernel using modulo variable expansion algorithm (MVE).
#include "llvm/CodeGen/ModuloSchedule.h"
Public Member Functions
ModuloScheduleExpanderMVE (MachineFunction &MF, ModuloSchedule &S, LiveIntervals &LIS)
void expand ()
Static Public Member Functions
static bool canApply (MachineLoop &L)
Check if ModuloScheduleExpanderMVE can be applied to L.
Detailed Description
Expand the kernel using modulo variable expansion algorithm (MVE).
It unrolls the kernel enough to avoid overlap of register lifetime.
Definition at line 375 of file ModuloSchedule.h.
Constructor & Destructor Documentation
ModuloScheduleExpanderMVE()
llvm::ModuloScheduleExpanderMVE::ModuloScheduleExpanderMVE (MachineFunction & MF, ModuloSchedule & S, LiveIntervals & LIS) inline
Definition at line 436 of file ModuloSchedule.h.
References MRI, and TII.
Member Function Documentation
canApply()
bool ModuloScheduleExpanderMVE::canApply (MachineLoop & L) static
Check if ModuloScheduleExpanderMVE can be applied to L.
Definition at line 2694 of file ModuloSchedule.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::dbgs(), llvm::MachineBasicBlock::getParent(), getPhiRegs(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::MachineOperand::isReg(), LLVM_DEBUG, MI, MRI, llvm::MachineBasicBlock::phis(), llvm::Ref, and Register.
Referenced by llvm::SwingSchedulerDAG::schedule().
expand()
void ModuloScheduleExpanderMVE::expand ()
Definition at line 2683 of file ModuloSchedule.cpp.
References LLVM_DEBUG.
Referenced by llvm::SwingSchedulerDAG::schedule().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/ModuloSchedule.h
lib/CodeGen/ModuloSchedule.cpp