LLVM: llvm::PPCLegalizerInfo Class Reference
llvm::PPCLegalizerInfo Class Reference
This class provides the information for the PowerPC target legalizer for GlobalISel.
#include "Target/PowerPC/GISel/PPCLegalizerInfo.h"
Public Member Functions
PPCLegalizerInfo (const PPCSubtarget &ST)
Public Member Functions inherited from llvm::LegalizerInfo
virtual ~LegalizerInfo ()=default
const LegacyLegalizerInfo & getLegacyLegalizerInfo () const
LegacyLegalizerInfo & getLegacyLegalizerInfo ()
unsigned getOpcodeIdxForOpcode (unsigned Opcode) const
unsigned getActionDefinitionsIdx (unsigned Opcode) const
void verify (const MCInstrInfo &MII) const
Perform simple self-diagnostic and assert if there is anything obviously wrong with the actions set up.
const LegalizeRuleSet & getActionDefinitions (unsigned Opcode) const
Get the action definitions for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (unsigned Opcode)
Get the action definition builder for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (std::initializer_list< unsigned > Opcodes)
Get the action definition builder for the given set of opcodes.
void aliasActionDefinitions (unsigned OpcodeTo, unsigned OpcodeFrom)
LegalizeActionStep getAction (const LegalityQuery &Query) const
Determine what action should be taken to legalize the described instruction.
LegalizeActionStep getAction (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
Determine what action should be taken to legalize the given generic instruction.
bool isLegal (const LegalityQuery &Query) const
bool isLegalOrCustom (const LegalityQuery &Query) const
bool isLegal (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
bool isLegalOrCustom (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
virtual bool legalizeCustom (LegalizerHelper &Helper, MachineInstr &MI, LostDebugLocObserver &LocObserver) const
Called for instructions with the Custom LegalizationAction.
virtual bool legalizeIntrinsic (LegalizerHelper &Helper, MachineInstr &MI) const
virtual unsigned getExtOpcodeForWideningConstant (LLT SmallTy) const
Return the opcode (SEXT/ZEXT/ANYEXT) that should be performed while widening a constant of type SmallTy which targets can override.
Detailed Description
This class provides the information for the PowerPC target legalizer for GlobalISel.
Definition at line 23 of file PPCLegalizerInfo.h.
Constructor & Destructor Documentation
PPCLegalizerInfo()
PPCLegalizerInfo::PPCLegalizerInfo (const PPCSubtarget & ST)
Definition at line 41 of file PPCLegalizerInfo.cpp.
References llvm::LegalityPredicates::all(), llvm::LegalizeRuleSet::bitcastIf(), llvm::LegalizeMutations::changeTo(), llvm::LegacyLegalizerInfo::computeTables(), llvm::LLT::fixed_vector(), llvm::LegalizerInfo::getActionDefinitionsBuilder(), llvm::LegalizerInfo::getLegacyLegalizerInfo(), isRegisterType(), llvm::LegalizeRuleSet::legalFor(), llvm::LegalizeRuleSet::legalForCartesianProduct(), llvm::LegalizeRuleSet::legalIf(), llvm::LegalizeRuleSet::lower(), llvm::LegalizeRuleSet::lowerFor(), llvm::LLT::pointer(), S1, S16, S32, S64, S8, llvm::LLT::scalar(), llvm::LegalityPredicates::typeIsNot(), V2S64, V4S32, and V8S16.
The documentation for this class was generated from the following files:
lib/Target/PowerPC/GISel/PPCLegalizerInfo.h
lib/Target/PowerPC/GISel/PPCLegalizerInfo.cpp