LLVM: llvm::OptLevelChanger Class Reference
llvm::OptLevelChanger Class Reference
This class is used by SelectionDAGISel to temporarily override the optimization level on a per-function basis.
Public Member Functions
OptLevelChanger (SelectionDAGISel &ISel, CodeGenOptLevel NewOptLevel)
~OptLevelChanger ()
Detailed Description
This class is used by SelectionDAGISel to temporarily override the optimization level on a per-function basis.
Definition at line 238 of file SelectionDAGISel.cpp.
Constructor & Destructor Documentation
OptLevelChanger()
llvm::OptLevelChanger::OptLevelChanger (SelectionDAGISel & ISel, CodeGenOptLevel NewOptLevel) inline
Definition at line 244 of file SelectionDAGISel.cpp.
References llvm::dbgs(), dontUseFastISelFor(), llvm::TargetOptions::EnableFastISel, llvm::MachineFunction::getFunction(), llvm::sandboxir::Value::getName(), llvm::TargetMachine::getO0WantsFastISel(), LLVM_DEBUG, llvm::SelectionDAGISel::MF, llvm::None, llvm::TargetMachine::Options, llvm::SelectionDAGISel::OptLevel, llvm::TargetMachine::setFastISel(), llvm::TargetMachine::setOptLevel(), and llvm::SelectionDAGISel::TM.
~OptLevelChanger()
llvm::OptLevelChanger::~OptLevelChanger () inline
Definition at line 267 of file SelectionDAGISel.cpp.
References llvm::dbgs(), llvm::MachineFunction::getFunction(), llvm::sandboxir::Value::getName(), LLVM_DEBUG, llvm::SelectionDAGISel::MF, llvm::SelectionDAGISel::OptLevel, llvm::TargetMachine::setFastISel(), llvm::TargetMachine::setOptLevel(), and llvm::SelectionDAGISel::TM.
The documentation for this class was generated from the following file:
lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp