LLVM: llvm::BTFTypeEnum64 Class Reference
llvm::BTFTypeEnum64 Class Reference
Handle 64-bit enumerate type.
#include "Target/BPF/BTFDebug.h"
Public Member Functions
BTFTypeEnum64 (const DICompositeType *ETy, uint32_t NumValues, bool IsSigned)
uint32_t getSize () override
Get the size of this BTF type entry.
void completeType (BTFDebug &BDebug) override
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
void emitType (MCStreamer &OS) override
Emit types for this BTF type entry.
Public Member Functions inherited from llvm::BTFTypeBase
BTFTypeBase ()
virtual ~BTFTypeBase ()=default
void setId (uint32_t Id)
uint32_t getId ()
uint32_t roundupToBytes (uint32_t NumBits)
Additional Inherited Members
Protected Attributes inherited from llvm::BTFTypeBase
uint8_t Kind
bool IsCompleted
uint32_t Id
struct BTF::CommonType BTFType
Detailed Description
Handle 64-bit enumerate type.
Definition at line 222 of file BTFDebug.h.
Constructor & Destructor Documentation
BTFTypeEnum64()
BTFTypeEnum64::BTFTypeEnum64 (const DICompositeType * ETy, uint32_t NumValues, bool IsSigned)
Definition at line 207 of file BTFDebug.cpp.
References llvm::BTFTypeBase::BTFType, llvm::DIType::getSizeInBits(), llvm::BTF::CommonType::Info, llvm::BTFTypeBase::roundupToBytes(), and llvm::BTF::CommonType::Size.
Member Function Documentation
completeType()
void BTFTypeEnum64::completeType (BTFDebug & BDebug) override virtual
Complete BTF type generation after all related DebugInfo types have been visited so their BTF type id's are available for cross referece.
Reimplemented from llvm::BTFTypeBase.
Definition at line 214 of file BTFDebug.cpp.
References llvm::BTFDebug::addString(), llvm::BTFTypeBase::BTFType, llvm::cast(), llvm::DICompositeType::getElements(), llvm::DIType::getName(), llvm::BTFTypeBase::IsCompleted, llvm::BTF::BTFEnum64::NameOff, llvm::BTF::CommonType::NameOff, llvm::BTF::BTFEnum64::Val_Hi32, llvm::BTF::BTFEnum64::Val_Lo32, and llvm::Value.
emitType()
void BTFTypeEnum64::emitType (MCStreamer & OS) override virtual
Emit types for this BTF type entry.
Emit a BTF common type.
Reimplemented from llvm::BTFTypeBase.
Definition at line 238 of file BTFDebug.cpp.
References llvm::BTFTypeBase::emitType(), OS, and llvm::Twine::utohexstr().
getSize()
uint32_t llvm::BTFTypeEnum64::getSize () inline override virtual
Get the size of this BTF type entry.
Reimplemented from llvm::BTFTypeBase.
Definition at line 228 of file BTFDebug.h.
References llvm::BTF::BTFEnum64Size, and llvm::BTFTypeBase::getSize().
The documentation for this class was generated from the following files:
lib/Target/BPF/BTFDebug.h
lib/Target/BPF/BTFDebug.cpp