LLVM: llvm::AMDGPUTargetStreamer Class Reference
llvm::AMDGPUTargetStreamer Class Reference
#include "Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.h"
Public Member Functions
AMDGPUTargetStreamer (MCStreamer &S)
AMDGPUPALMetadata * getPALMetadata ()
virtual void EmitDirectiveAMDGCNTarget ()
virtual void EmitDirectiveAMDHSACodeObjectVersion (unsigned COV)
virtual void EmitAMDKernelCodeT (AMDGPU::AMDGPUMCKernelCodeT &Header)
virtual void EmitAMDGPUSymbolType (StringRef SymbolName, unsigned Type)
virtual void emitAMDGPULDS (MCSymbol *Symbol, unsigned Size, Align Alignment)
virtual bool EmitISAVersion ()
virtual bool EmitHSAMetadataV3 (StringRef HSAMetadataString)
virtual bool EmitHSAMetadata (msgpack::Document &HSAMetadata, bool Strict)
Emit HSA Metadata.
virtual bool EmitHSAMetadata (const AMDGPU::HSAMD::Metadata &HSAMetadata)
virtual bool EmitCodeEnd (const MCSubtargetInfo &STI)
virtual bool EmitKernargPreloadHeader (const MCSubtargetInfo &STI, bool TrapEnabled)
virtual void EmitAmdhsaKernelDescriptor (const MCSubtargetInfo &STI, StringRef KernelName, const AMDGPU::MCKernelDescriptor &KernelDescriptor, const MCExpr *NextVGPR, const MCExpr *NextSGPR, const MCExpr *ReserveVCC, const MCExpr *ReserveFlatScr)
const std::optional< AMDGPU::IsaInfo::AMDGPUTargetID > & getTargetID () const
std::optional< AMDGPU::IsaInfo::AMDGPUTargetID > & getTargetID ()
void initializeTargetID (const MCSubtargetInfo &STI)
void initializeTargetID (const MCSubtargetInfo &STI, StringRef FeatureString)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Static Public Member Functions
static StringRef getArchNameFromElfMach (unsigned ElfMach)
static unsigned getElfMach (StringRef GPU)
Protected Member Functions
MCContext & getContext () const
Protected Attributes
std::optional< AMDGPU::IsaInfo::AMDGPUTargetID > TargetID
unsigned CodeObjectVersion
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 31 of file AMDGPUTargetStreamer.h.
Constructor & Destructor Documentation
AMDGPUTargetStreamer()
llvm::AMDGPUTargetStreamer::AMDGPUTargetStreamer (MCStreamer & S) inline
Definition at line 42 of file AMDGPUTargetStreamer.h.
Member Function Documentation
emitAMDGPULDS()
virtual void llvm::AMDGPUTargetStreamer::emitAMDGPULDS (MCSymbol * Symbol, unsigned Size, Align Alignment) inline virtual
Reimplemented in llvm::AMDGPUTargetAsmStreamer, and llvm::AMDGPUTargetELFStreamer.
Definition at line 60 of file AMDGPUTargetStreamer.h.
EmitAMDGPUSymbolType()
virtual void llvm::AMDGPUTargetStreamer::EmitAMDGPUSymbolType (StringRef SymbolName, unsigned Type) inline virtual
Reimplemented in llvm::AMDGPUTargetAsmStreamer, and llvm::AMDGPUTargetELFStreamer.
Definition at line 58 of file AMDGPUTargetStreamer.h.
Referenced by llvm::AMDGPUAsmPrinter::emitFunctionEntryLabel().
EmitAmdhsaKernelDescriptor()
virtual void llvm::AMDGPUTargetStreamer::EmitAmdhsaKernelDescriptor (const MCSubtargetInfo & STI, StringRef KernelName, const AMDGPU::MCKernelDescriptor & KernelDescriptor, const MCExpr * NextVGPR, const MCExpr * NextSGPR, const MCExpr * ReserveVCC, const MCExpr * ReserveFlatScr) inline virtual
Reimplemented in llvm::AMDGPUTargetAsmStreamer, and llvm::AMDGPUTargetELFStreamer.
Definition at line 95 of file AMDGPUTargetStreamer.h.
Referenced by llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd().
EmitAMDKernelCodeT()
virtual void llvm::AMDGPUTargetStreamer::EmitAMDKernelCodeT (AMDGPU::AMDGPUMCKernelCodeT & Header) inline virtual
Reimplemented in llvm::AMDGPUTargetAsmStreamer, and llvm::AMDGPUTargetELFStreamer.
Definition at line 56 of file AMDGPUTargetStreamer.h.
Referenced by llvm::AMDGPUAsmPrinter::emitFunctionBodyStart().
EmitCodeEnd()
virtual bool llvm::AMDGPUTargetStreamer::EmitCodeEnd (const MCSubtargetInfo & STI) inline virtual
Returns
True on success, false on failure.
Reimplemented in llvm::AMDGPUTargetAsmStreamer, and llvm::AMDGPUTargetELFStreamer.
Definition at line 86 of file AMDGPUTargetStreamer.h.
Referenced by llvm::AMDGPUAsmPrinter::doFinalization().
EmitDirectiveAMDGCNTarget()
virtual void llvm::AMDGPUTargetStreamer::EmitDirectiveAMDGCNTarget () inline virtual
Reimplemented in llvm::AMDGPUTargetAsmStreamer, and llvm::AMDGPUTargetELFStreamer.
Definition at line 50 of file AMDGPUTargetStreamer.h.
EmitDirectiveAMDHSACodeObjectVersion()
virtual void llvm::AMDGPUTargetStreamer::EmitDirectiveAMDHSACodeObjectVersion (unsigned COV) inline virtual
Reimplemented in llvm::AMDGPUTargetAsmStreamer.
Definition at line 52 of file AMDGPUTargetStreamer.h.
References CodeObjectVersion.
Referenced by llvm::AMDGPUTargetAsmStreamer::EmitDirectiveAMDHSACodeObjectVersion().
EmitHSAMetadata() [1/2]
virtual bool llvm::AMDGPUTargetStreamer::EmitHSAMetadata (const AMDGPU::HSAMD::Metadata & HSAMetadata) inline virtual
Returns
True on success, false on failure.
Definition at line 81 of file AMDGPUTargetStreamer.h.
EmitHSAMetadata() [2/2]
virtual bool llvm::AMDGPUTargetStreamer::EmitHSAMetadata (msgpack::Document & HSAMetadata, bool Strict) inline virtual
Emit HSA Metadata.
When Strict is true, known metadata elements must already be well-typed. When Strict is false, known types are inferred and the HSAMetadata structure is updated with the correct types.
Returns
True on success, false on failure.
Reimplemented in llvm::AMDGPUTargetAsmStreamer, and llvm::AMDGPUTargetELFStreamer.
Definition at line 76 of file AMDGPUTargetStreamer.h.
Referenced by EmitHSAMetadataV3(), and llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitTo().
EmitHSAMetadataV3()
bool AMDGPUTargetStreamer::EmitHSAMetadataV3 (StringRef HSAMetadataString) virtual
Returns
True on success, false on failure.
Definition at line 46 of file AMDGPUTargetStreamer.cpp.
References EmitHSAMetadata(), and llvm::msgpack::Document::fromYAML().
EmitISAVersion()
virtual bool llvm::AMDGPUTargetStreamer::EmitISAVersion () inline virtual
Returns
True on success, false on failure.
Reimplemented in llvm::AMDGPUTargetAsmStreamer, and llvm::AMDGPUTargetELFStreamer.
Definition at line 64 of file AMDGPUTargetStreamer.h.
Referenced by llvm::AMDGPUAsmPrinter::emitEndOfAsmFile().
EmitKernargPreloadHeader()
virtual bool llvm::AMDGPUTargetStreamer::EmitKernargPreloadHeader (const MCSubtargetInfo & STI, bool TrapEnabled) inline virtual
Returns
True on success, false on failure.
Reimplemented in llvm::AMDGPUTargetAsmStreamer, and llvm::AMDGPUTargetELFStreamer.
Definition at line 89 of file AMDGPUTargetStreamer.h.
Referenced by llvm::AMDGPUAsmPrinter::emitFunctionBodyStart().
getArchNameFromElfMach()
StringRef AMDGPUTargetStreamer::getArchNameFromElfMach (unsigned ElfMach) static
Definition at line 53 of file AMDGPUTargetStreamer.cpp.
References llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1010, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1011, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1012, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1013, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1030, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1031, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1032, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1033, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1034, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1035, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1036, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX10_1_GENERIC, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX10_3_GENERIC, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1100, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1101, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1102, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1103, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1150, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1151, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1152, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX11_GENERIC, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1200, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1201, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX12_GENERIC, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX600, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX601, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX602, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX700, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX701, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX702, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX703, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX704, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX705, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX801, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX802, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX803, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX805, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX810, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX900, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX902, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX904, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX906, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX908, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX909, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX90A, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX90C, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX940, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX941, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX942, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX9_GENERIC, llvm::ELF::EF_AMDGPU_MACH_NONE, llvm::ELF::EF_AMDGPU_MACH_R600_BARTS, llvm::ELF::EF_AMDGPU_MACH_R600_CAICOS, llvm::ELF::EF_AMDGPU_MACH_R600_CAYMAN, llvm::ELF::EF_AMDGPU_MACH_R600_CEDAR, llvm::ELF::EF_AMDGPU_MACH_R600_CYPRESS, llvm::ELF::EF_AMDGPU_MACH_R600_JUNIPER, llvm::ELF::EF_AMDGPU_MACH_R600_R600, llvm::ELF::EF_AMDGPU_MACH_R600_R630, llvm::ELF::EF_AMDGPU_MACH_R600_REDWOOD, llvm::ELF::EF_AMDGPU_MACH_R600_RS880, llvm::ELF::EF_AMDGPU_MACH_R600_RV670, llvm::ELF::EF_AMDGPU_MACH_R600_RV710, llvm::ELF::EF_AMDGPU_MACH_R600_RV730, llvm::ELF::EF_AMDGPU_MACH_R600_RV770, llvm::ELF::EF_AMDGPU_MACH_R600_SUMO, llvm::ELF::EF_AMDGPU_MACH_R600_TURKS, llvm::AMDGPU::getArchNameAMDGCN(), llvm::AMDGPU::getArchNameR600(), llvm::AMDGPU::GK_BARTS, llvm::AMDGPU::GK_CAICOS, llvm::AMDGPU::GK_CAYMAN, llvm::AMDGPU::GK_CEDAR, llvm::AMDGPU::GK_CYPRESS, llvm::AMDGPU::GK_GFX1010, llvm::AMDGPU::GK_GFX1011, llvm::AMDGPU::GK_GFX1012, llvm::AMDGPU::GK_GFX1013, llvm::AMDGPU::GK_GFX1030, llvm::AMDGPU::GK_GFX1031, llvm::AMDGPU::GK_GFX1032, llvm::AMDGPU::GK_GFX1033, llvm::AMDGPU::GK_GFX1034, llvm::AMDGPU::GK_GFX1035, llvm::AMDGPU::GK_GFX1036, llvm::AMDGPU::GK_GFX10_1_GENERIC, llvm::AMDGPU::GK_GFX10_3_GENERIC, llvm::AMDGPU::GK_GFX1100, llvm::AMDGPU::GK_GFX1101, llvm::AMDGPU::GK_GFX1102, llvm::AMDGPU::GK_GFX1103, llvm::AMDGPU::GK_GFX1150, llvm::AMDGPU::GK_GFX1151, llvm::AMDGPU::GK_GFX1152, llvm::AMDGPU::GK_GFX11_GENERIC, llvm::AMDGPU::GK_GFX1200, llvm::AMDGPU::GK_GFX1201, llvm::AMDGPU::GK_GFX12_GENERIC, llvm::AMDGPU::GK_GFX600, llvm::AMDGPU::GK_GFX601, llvm::AMDGPU::GK_GFX602, llvm::AMDGPU::GK_GFX700, llvm::AMDGPU::GK_GFX701, llvm::AMDGPU::GK_GFX702, llvm::AMDGPU::GK_GFX703, llvm::AMDGPU::GK_GFX704, llvm::AMDGPU::GK_GFX705, llvm::AMDGPU::GK_GFX801, llvm::AMDGPU::GK_GFX802, llvm::AMDGPU::GK_GFX803, llvm::AMDGPU::GK_GFX805, llvm::AMDGPU::GK_GFX810, llvm::AMDGPU::GK_GFX900, llvm::AMDGPU::GK_GFX902, llvm::AMDGPU::GK_GFX904, llvm::AMDGPU::GK_GFX906, llvm::AMDGPU::GK_GFX908, llvm::AMDGPU::GK_GFX909, llvm::AMDGPU::GK_GFX90A, llvm::AMDGPU::GK_GFX90C, llvm::AMDGPU::GK_GFX940, llvm::AMDGPU::GK_GFX941, llvm::AMDGPU::GK_GFX942, llvm::AMDGPU::GK_GFX9_GENERIC, llvm::AMDGPU::GK_JUNIPER, llvm::AMDGPU::GK_NONE, llvm::AMDGPU::GK_R600, llvm::AMDGPU::GK_R630, llvm::AMDGPU::GK_REDWOOD, llvm::AMDGPU::GK_RS880, llvm::AMDGPU::GK_RV670, llvm::AMDGPU::GK_RV710, llvm::AMDGPU::GK_RV730, llvm::AMDGPU::GK_RV770, llvm::AMDGPU::GK_SUMO, and llvm::AMDGPU::GK_TURKS.
getContext()
MCContext & llvm::AMDGPUTargetStreamer::getContext () const inline protected
Definition at line 39 of file AMDGPUTargetStreamer.h.
References llvm::MCStreamer::getContext(), and llvm::MCTargetStreamer::Streamer.
Referenced by llvm::AMDGPUTargetELFStreamer::emitAMDGPULDS(), llvm::AMDGPUTargetELFStreamer::EmitAMDGPUSymbolType(), llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), llvm::AMDGPUTargetAsmStreamer::EmitAMDKernelCodeT(), llvm::AMDGPUTargetELFStreamer::EmitAMDKernelCodeT(), llvm::AMDGPUTargetELFStreamer::EmitHSAMetadata(), llvm::AMDGPUTargetELFStreamer::EmitISAVersion(), and llvm::AMDGPUTargetELFStreamer::finish().
getElfMach()
unsigned AMDGPUTargetStreamer::getElfMach (StringRef GPU) static
Definition at line 135 of file AMDGPUTargetStreamer.cpp.
References llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1010, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1011, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1012, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1013, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1030, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1031, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1032, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1033, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1034, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1035, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1036, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX10_1_GENERIC, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX10_3_GENERIC, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1100, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1101, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1102, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1103, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1150, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1151, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1152, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX11_GENERIC, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1200, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX1201, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX12_GENERIC, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX600, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX601, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX602, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX700, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX701, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX702, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX703, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX704, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX705, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX801, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX802, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX803, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX805, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX810, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX900, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX902, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX904, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX906, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX908, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX909, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX90A, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX90C, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX940, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX941, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX942, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_GFX9_GENERIC, llvm::ELF::EF_AMDGPU_MACH_NONE, llvm::ELF::EF_AMDGPU_MACH_R600_BARTS, llvm::ELF::EF_AMDGPU_MACH_R600_CAICOS, llvm::ELF::EF_AMDGPU_MACH_R600_CAYMAN, llvm::ELF::EF_AMDGPU_MACH_R600_CEDAR, llvm::ELF::EF_AMDGPU_MACH_R600_CYPRESS, llvm::ELF::EF_AMDGPU_MACH_R600_JUNIPER, llvm::ELF::EF_AMDGPU_MACH_R600_R600, llvm::ELF::EF_AMDGPU_MACH_R600_R630, llvm::ELF::EF_AMDGPU_MACH_R600_REDWOOD, llvm::ELF::EF_AMDGPU_MACH_R600_RS880, llvm::ELF::EF_AMDGPU_MACH_R600_RV670, llvm::ELF::EF_AMDGPU_MACH_R600_RV710, llvm::ELF::EF_AMDGPU_MACH_R600_RV730, llvm::ELF::EF_AMDGPU_MACH_R600_RV770, llvm::ELF::EF_AMDGPU_MACH_R600_SUMO, llvm::ELF::EF_AMDGPU_MACH_R600_TURKS, llvm::AMDGPU::GK_BARTS, llvm::AMDGPU::GK_CAICOS, llvm::AMDGPU::GK_CAYMAN, llvm::AMDGPU::GK_CEDAR, llvm::AMDGPU::GK_CYPRESS, llvm::AMDGPU::GK_GFX1010, llvm::AMDGPU::GK_GFX1011, llvm::AMDGPU::GK_GFX1012, llvm::AMDGPU::GK_GFX1013, llvm::AMDGPU::GK_GFX1030, llvm::AMDGPU::GK_GFX1031, llvm::AMDGPU::GK_GFX1032, llvm::AMDGPU::GK_GFX1033, llvm::AMDGPU::GK_GFX1034, llvm::AMDGPU::GK_GFX1035, llvm::AMDGPU::GK_GFX1036, llvm::AMDGPU::GK_GFX10_1_GENERIC, llvm::AMDGPU::GK_GFX10_3_GENERIC, llvm::AMDGPU::GK_GFX1100, llvm::AMDGPU::GK_GFX1101, llvm::AMDGPU::GK_GFX1102, llvm::AMDGPU::GK_GFX1103, llvm::AMDGPU::GK_GFX1150, llvm::AMDGPU::GK_GFX1151, llvm::AMDGPU::GK_GFX1152, llvm::AMDGPU::GK_GFX11_GENERIC, llvm::AMDGPU::GK_GFX1200, llvm::AMDGPU::GK_GFX1201, llvm::AMDGPU::GK_GFX12_GENERIC, llvm::AMDGPU::GK_GFX600, llvm::AMDGPU::GK_GFX601, llvm::AMDGPU::GK_GFX602, llvm::AMDGPU::GK_GFX700, llvm::AMDGPU::GK_GFX701, llvm::AMDGPU::GK_GFX702, llvm::AMDGPU::GK_GFX703, llvm::AMDGPU::GK_GFX704, llvm::AMDGPU::GK_GFX705, llvm::AMDGPU::GK_GFX801, llvm::AMDGPU::GK_GFX802, llvm::AMDGPU::GK_GFX803, llvm::AMDGPU::GK_GFX805, llvm::AMDGPU::GK_GFX810, llvm::AMDGPU::GK_GFX900, llvm::AMDGPU::GK_GFX902, llvm::AMDGPU::GK_GFX904, llvm::AMDGPU::GK_GFX906, llvm::AMDGPU::GK_GFX908, llvm::AMDGPU::GK_GFX909, llvm::AMDGPU::GK_GFX90A, llvm::AMDGPU::GK_GFX90C, llvm::AMDGPU::GK_GFX940, llvm::AMDGPU::GK_GFX941, llvm::AMDGPU::GK_GFX942, llvm::AMDGPU::GK_GFX9_GENERIC, llvm::AMDGPU::GK_JUNIPER, llvm::AMDGPU::GK_NONE, llvm::AMDGPU::GK_R600, llvm::AMDGPU::GK_R630, llvm::AMDGPU::GK_REDWOOD, llvm::AMDGPU::GK_RS880, llvm::AMDGPU::GK_RV670, llvm::AMDGPU::GK_RV710, llvm::AMDGPU::GK_RV730, llvm::AMDGPU::GK_RV770, llvm::AMDGPU::GK_SUMO, llvm::AMDGPU::GK_TURKS, llvm_unreachable, llvm::AMDGPU::parseArchAMDGCN(), and llvm::AMDGPU::parseArchR600().
getPALMetadata()
AMDGPUPALMetadata * llvm::AMDGPUTargetStreamer::getPALMetadata () inline
Definition at line 48 of file AMDGPUTargetStreamer.h.
Referenced by llvm::AMDGPUTargetAsmStreamer::finish(), and llvm::AMDGPUTargetELFStreamer::finish().
getTargetID() [1/2]
std::optional< AMDGPU::IsaInfo::AMDGPUTargetID > & llvm::AMDGPUTargetStreamer::getTargetID () inline
Definition at line 107 of file AMDGPUTargetStreamer.h.
References TargetID.
getTargetID() [2/2]
const std::optional< AMDGPU::IsaInfo::AMDGPUTargetID > & llvm::AMDGPUTargetStreamer::getTargetID () const inline
Definition at line 104 of file AMDGPUTargetStreamer.h.
References TargetID.
Referenced by llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), llvm::AMDGPUTargetAsmStreamer::EmitDirectiveAMDGCNTarget(), llvm::AMDGPUTargetAsmStreamer::EmitISAVersion(), llvm::AMDGPUTargetELFStreamer::EmitISAVersion(), and initializeTargetID().
initializeTargetID() [1/2]
void llvm::AMDGPUTargetStreamer::initializeTargetID (const MCSubtargetInfo & STI) inline
Definition at line 110 of file AMDGPUTargetStreamer.h.
References assert(), and TargetID.
Referenced by initializeTargetID().
initializeTargetID() [2/2]
void llvm::AMDGPUTargetStreamer::initializeTargetID (const MCSubtargetInfo & STI, StringRef FeatureString) inline
Definition at line 114 of file AMDGPUTargetStreamer.h.
References assert(), getTargetID(), and initializeTargetID().
Member Data Documentation
CodeObjectVersion
unsigned llvm::AMDGPUTargetStreamer::CodeObjectVersion protected
Definition at line 37 of file AMDGPUTargetStreamer.h.
Referenced by llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), EmitDirectiveAMDHSACodeObjectVersion(), and llvm::AMDGPUTargetELFStreamer::finish().
TargetID
std::optional<AMDGPU::IsaInfo::AMDGPUTargetID> llvm::AMDGPUTargetStreamer::TargetID protected
Definition at line 36 of file AMDGPUTargetStreamer.h.
Referenced by getTargetID(), getTargetID(), and initializeTargetID().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.h
lib/Target/AMDGPU/MCTargetDesc/AMDGPUTargetStreamer.cpp