LLVM: llvm::PseudoProbeManager Class Reference
llvm::PseudoProbeManager Class Reference
#include "llvm/Transforms/Utils/SampleProfileLoaderBaseImpl.h"
Public Member Functions
PseudoProbeManager (const Module &M)
const PseudoProbeDescriptor * getDesc (uint64_t GUID) const
const PseudoProbeDescriptor * getDesc (StringRef FProfileName) const
const PseudoProbeDescriptor * getDesc (const Function &F) const
bool profileIsHashMismatched (const PseudoProbeDescriptor &FuncDesc, const FunctionSamples &Samples) const
bool moduleIsProbed (const Module &M) const
bool profileIsValid (const Function &F, const FunctionSamples &Samples) const
Detailed Description
Definition at line 88 of file SampleProfileLoaderBaseImpl.h.
Constructor & Destructor Documentation
PseudoProbeManager()
llvm::PseudoProbeManager::PseudoProbeManager (const Module & M) inline
Definition at line 92 of file SampleProfileLoaderBaseImpl.h.
References llvm::cast(), llvm::mdconst::dyn_extract(), llvm::PseudoProbeDescMetadataName, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Member Function Documentation
getDesc() [1/3]
const PseudoProbeDescriptor * llvm::PseudoProbeManager::getDesc (const Function & F) const inline
Definition at line 115 of file SampleProfileLoaderBaseImpl.h.
References F, llvm::sampleprof::FunctionSamples::getCanonicalFnName(), getDesc(), and llvm::GlobalValue::getGUID().
getDesc() [2/3]
const PseudoProbeDescriptor * llvm::PseudoProbeManager::getDesc (StringRef FProfileName) const inline
Definition at line 111 of file SampleProfileLoaderBaseImpl.h.
References getDesc(), and llvm::GlobalValue::getGUID().
getDesc() [3/3]
const PseudoProbeDescriptor * llvm::PseudoProbeManager::getDesc (uint64_t GUID) const inline
Definition at line 106 of file SampleProfileLoaderBaseImpl.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
Referenced by getDesc(), getDesc(), and profileIsValid().
moduleIsProbed()
bool llvm::PseudoProbeManager::moduleIsProbed (const Module & M) const inline
Definition at line 124 of file SampleProfileLoaderBaseImpl.h.
References llvm::PseudoProbeDescMetadataName.
profileIsHashMismatched()
bool llvm::PseudoProbeManager::profileIsHashMismatched (const PseudoProbeDescriptor & FuncDesc, const FunctionSamples & Samples) const inline
Definition at line 119 of file SampleProfileLoaderBaseImpl.h.
References llvm::PseudoProbeDescriptor::getFunctionHash(), and llvm::sampleprof::FunctionSamples::getFunctionHash().
Referenced by profileIsValid().
profileIsValid()
bool llvm::PseudoProbeManager::profileIsValid (const Function & F, const FunctionSamples & Samples) const inline
Definition at line 128 of file SampleProfileLoaderBaseImpl.h.
References F, getDesc(), llvm::GlobalValue::isAvailableExternallyLinkage(), and profileIsHashMismatched().
The documentation for this class was generated from the following file:
include/llvm/Transforms/Utils/SampleProfileLoaderBaseImpl.h