LLVM: llvm::VPInterleaveRecipe Class Reference
llvm::VPInterleaveRecipe Class Reference
VPInterleaveRecipe is a recipe for transforming an interleave group of load or stores into one wide load/store and shuffles.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPInterleaveRecipe (const InterleaveGroup< Instruction > *IG, VPValue *Addr, ArrayRef< VPValue * > StoredValues, VPValue *Mask, bool NeedsMaskForGaps)
~VPInterleaveRecipe () override=default
VPInterleaveRecipe * clone () override
Clone the current recipe.
VPValue * getAddr () const
Return the address accessed by this recipe.
VPValue * getMask () const
Return the mask used by this recipe.
ArrayRef< VPValue * > getStoredValues () const
Return the VPValues stored by this interleave group.
void execute (VPTransformState &State) override
Generate the wide load or store, and shuffles.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the recipe.
const InterleaveGroup< Instruction > * getInterleaveGroup ()
unsigned getNumStoreOperands () const
Returns the number of stored operands of this interleave group.
bool onlyFirstLaneUsed (const VPValue *Op) const override
The recipe only uses the first lane of the address.
Instruction * getInsertPos () const
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
template<typename IterT >
VPRecipeBase (const unsigned char SC, iterator_range< IterT > Operands, DebugLoc DL={})
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
virtual InstructionCost cost (ElementCount VF, VPCostContext &Ctx)
Return the cost of this recipe, taking into account if the cost computation should be skipped and the ForceTargetInstructionCost flag.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
DebugLoc getDebugLoc () const
Returns the debug location of the recipe.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::ilist_detail::node_parent_access< ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >, ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty >
const ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent () const
ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty * getParent ()
void setParent (ilist_detail::compute_node_options< VPRecipeBase, Options... >::type::parent_ty *Parent)
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
VPUserID getVPUserID () const
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
virtual bool onlyFirstPartUsed (const VPValue *Op) const
Returns true if the VPUser only uses the first part of operand Op.
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
enum class VPUserID { Recipe , LiveOut }
Subclass identifier (for isa/dyn_cast).
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::VPRecipeBase
InstructionCost computeCost (ElementCount VF, VPCostContext &Ctx) const
Compute the cost of this recipe using the legacy cost model and the underlying instructions.
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< VPRecipeBase, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands, VPUserID ID)
VPUser (std::initializer_list< VPValue * > Operands, VPUserID ID)
template<typename IterT >
VPUser (iterator_range< IterT > Operands, VPUserID ID)
Detailed Description
VPInterleaveRecipe is a recipe for transforming an interleave group of load or stores into one wide load/store and shuffles.
The first operand of a VPInterleave recipe is the address, followed by the stored values, followed by an optional mask.
Definition at line 2082 of file VPlan.h.
Constructor & Destructor Documentation
VPInterleaveRecipe()
llvm::VPInterleaveRecipe::VPInterleaveRecipe (const InterleaveGroup< Instruction > * IG, VPValue * Addr, ArrayRef< VPValue * > StoredValues, VPValue * Mask, bool NeedsMaskForGaps) inline
Definition at line 2094 of file VPlan.h.
References Addr.
Referenced by clone().
~VPInterleaveRecipe()
llvm::VPInterleaveRecipe::~VPInterleaveRecipe () override default
Member Function Documentation
clone()
VPInterleaveRecipe * llvm::VPInterleaveRecipe::clone () inline override virtual
Clone the current recipe.
Implements llvm::VPRecipeBase.
Definition at line 2115 of file VPlan.h.
References getAddr(), getMask(), getStoredValues(), and VPInterleaveRecipe().
execute()
void VPInterleaveRecipe::execute (VPTransformState & State) override virtual
Generate the wide load or store, and shuffles.
Implements llvm::VPRecipeBase.
Definition at line 2129 of file VPlanRecipes.cpp.
References llvm::InterleaveGroup< InstTy >::addMetadata(), Addr, assert(), llvm::createBitMaskForGaps(), createBitOrPointerCast(), llvm::createReplicatedMask(), llvm::createStrideMask(), llvm::VPDef::definedValues(), DL, llvm::dyn_cast(), gep, llvm::PoisonValue::get(), llvm::VectorType::get(), llvm::InterleaveGroup< InstTy >::getAlign(), llvm::InterleaveGroup< InstTy >::getFactor(), llvm::InterleaveGroup< InstTy >::getIndex(), llvm::InterleaveGroup< InstTy >::getInsertPos(), llvm::getLoadStoreType(), llvm::InterleaveGroup< InstTy >::getMember(), llvm::getRuntimeVF(), llvm::Value::getType(), I, interleaveVectors(), llvm::isa(), llvm::InterleaveGroup< InstTy >::isReverse(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Value::stripPointerCasts().
getAddr()
VPValue * llvm::VPInterleaveRecipe::getAddr () const inline
Return the address accessed by this recipe.
Definition at line 2123 of file VPlan.h.
References llvm::VPUser::getOperand().
Referenced by clone(), and onlyFirstLaneUsed().
getInsertPos()
Instruction * llvm::VPInterleaveRecipe::getInsertPos () const inline
Definition at line 2167 of file VPlan.h.
References llvm::InterleaveGroup< InstTy >::getInsertPos().
getInterleaveGroup()
const InterleaveGroup< Instruction > * llvm::VPInterleaveRecipe::getInterleaveGroup () inline
Definition at line 2152 of file VPlan.h.
getMask()
VPValue * llvm::VPInterleaveRecipe::getMask () const inline
Return the mask used by this recipe.
Note that a full mask is represented by a nullptr.
Definition at line 2129 of file VPlan.h.
References llvm::VPUser::getNumOperands(), and llvm::VPUser::getOperand().
Referenced by clone().
getNumStoreOperands()
unsigned llvm::VPInterleaveRecipe::getNumStoreOperands () const inline
Returns the number of stored operands of this interleave group.
Returns 0 for load interleave groups.
Definition at line 2156 of file VPlan.h.
References llvm::VPUser::getNumOperands().
Referenced by getStoredValues().
getStoredValues()
ArrayRef< VPValue * > llvm::VPInterleaveRecipe::getStoredValues () const inline
Return the VPValues stored by this interleave group.
If it is a load interleave group, return an empty ArrayRef.
Definition at line 2136 of file VPlan.h.
References llvm::ArrayRef(), llvm::VPUser::getNumOperands(), getNumStoreOperands(), and llvm::VPUser::op_begin().
Referenced by clone(), and onlyFirstLaneUsed().
onlyFirstLaneUsed()
bool llvm::VPInterleaveRecipe::onlyFirstLaneUsed (const VPValue * Op) const inline override virtual
The recipe only uses the first lane of the address.
Reimplemented from llvm::VPUser.
Definition at line 2161 of file VPlan.h.
References assert(), getAddr(), getStoredValues(), llvm::is_contained(), and llvm::VPUser::operands().
print()
void VPInterleaveRecipe::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the recipe.
Implements llvm::VPDef.
Definition at line 2377 of file VPlanRecipes.cpp.
References llvm::VPUser::getOperand(), llvm::VPDef::getVPValue(), and llvm::VPValue::printAsOperand().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlanRecipes.cpp