LLVM: llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT > Class Template Reference
llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT > Class Template Reference
#include "llvm/Analysis/GenericDomTreeUpdater.h"
Public Types
enum class UpdateStrategy : unsigned char { Eager = 0 , Lazy = 1 }
using BasicBlockT = typename DomTreeT::NodeType
Public Member Functions
GenericDomTreeUpdater (UpdateStrategy Strategy_)
GenericDomTreeUpdater (DomTreeT &DT_, UpdateStrategy Strategy_)
GenericDomTreeUpdater (DomTreeT *DT_, UpdateStrategy Strategy_)
GenericDomTreeUpdater (PostDomTreeT &PDT_, UpdateStrategy Strategy_)
GenericDomTreeUpdater (PostDomTreeT *PDT_, UpdateStrategy Strategy_)
GenericDomTreeUpdater (DomTreeT &DT_, PostDomTreeT &PDT_, UpdateStrategy Strategy_)
GenericDomTreeUpdater (DomTreeT *DT_, PostDomTreeT *PDT_, UpdateStrategy Strategy_)
~GenericDomTreeUpdater ()
bool isLazy () const
Returns true if the current strategy is Lazy.
bool isEager () const
Returns true if the current strategy is Eager.
bool hasDomTree () const
Returns true if it holds a DomTreeT.
bool hasPostDomTree () const
Returns true if it holds a PostDomTreeT.
bool hasPendingDeletedBB () const
Returns true if there is BasicBlockT awaiting deletion.
bool isBBPendingDeletion (BasicBlockT *DelBB) const
Returns true if DelBB is awaiting deletion.
bool hasPendingUpdates () const
Returns true if either of DT or PDT is valid and the tree has at least one update pending.
bool hasPendingDomTreeUpdates () const
Returns true if there are DomTreeT updates queued.
bool hasPendingPostDomTreeUpdates () const
Returns true if there are PostDomTreeT updates queued.
LLVM_DUMP_METHOD void dump () const
Debug method to help view the internal state of this class.
Mutation APIs
These methods provide APIs for submitting updates to the DomTreeT and the PostDominatorTree.
Note: There are two strategies to update the DomTreeT and the PostDominatorTree:
Eager UpdateStrategy: Updates are submitted and then flushed immediately.
Lazy UpdateStrategy: Updates are submitted but only flushed when you explicitly call Flush APIs. It is recommended to use this update strategy when you submit a bunch of updates multiple times which can then add up to a large number of updates between two queries on the DomTreeT. The incremental updater can reschedule the updates or decide to recalculate the dominator tree in order to speedup the updating process depending on the number of updates.
Although GenericDomTree provides several update primitives, it is not encouraged to use these APIs directly.
template<typename FuncT >
void recalculate (FuncT &F)
Notify DTU that the entry block was replaced.
void applyUpdates (ArrayRef< typename DomTreeT::UpdateType > Updates)
Submit updates to all available trees.
void applyUpdatesPermissive (ArrayRef< typename DomTreeT::UpdateType > Updates)
Submit updates to all available trees.
Flush APIs
CAUTION! By the moment these flush APIs are called, the current CFG needs to be the same as the CFG which DTU is in sync with + all updates submitted.
DomTreeT & getDomTree ()
Flush DomTree updates and return DomTree.
PostDomTreeT & getPostDomTree ()
Flush PostDomTree updates and return PostDomTree.
void flush ()
Apply all pending updates to available trees and flush all BasicBlocks awaiting deletion.
Protected Member Functions
bool isSelfDominance (typename DomTreeT::UpdateType Update) const
Returns true if the update is self dominance.
void applyDomTreeUpdates ()
Helper function to apply all pending DomTree updates.
void applyPostDomTreeUpdates ()
Helper function to apply all pending PostDomTree updates.
bool isUpdateValid (typename DomTreeT::UpdateType Update) const
Returns true if the update appears in the LLVM IR.
void eraseDelBBNode (BasicBlockT *DelBB)
Erase Basic Block node that has been unlinked from Function in the DomTree and PostDomTree.
void tryFlushDeletedBB ()
Helper function to flush deleted BasicBlocks if all available trees are up-to-date.
void dropOutOfDateUpdates ()
Drop all updates applied by all available trees and delete BasicBlocks if all available trees are up-to-date.
Protected Attributes
SmallVector< typename DomTreeT::UpdateType, 16 > PendUpdates
size_t PendDTUpdateIndex = 0
size_t PendPDTUpdateIndex = 0
DomTreeT * DT = nullptr
PostDomTreeT * PDT = nullptr
const UpdateStrategy Strategy
SmallPtrSet< BasicBlockT *, 8 > DeletedBBs
bool IsRecalculatingDomTree = false
bool IsRecalculatingPostDomTree = false
Detailed Description
template<typename DerivedT, typename DomTreeT, typename PostDomTreeT>
class llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >
Definition at line 24 of file GenericDomTreeUpdater.h.
Member Typedef Documentation
BasicBlockT
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > using llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::BasicBlockT = typename DomTreeT::NodeType
Definition at line 32 of file GenericDomTreeUpdater.h.
Member Enumeration Documentation
UpdateStrategy
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > enum class llvm::GenericDomTreeUpdater::UpdateStrategy : unsigned char strong
Enumerator
Eager
Lazy
Definition at line 31 of file GenericDomTreeUpdater.h.
Constructor & Destructor Documentation
GenericDomTreeUpdater() [1/7]
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::GenericDomTreeUpdater (UpdateStrategy Strategy_) inline explicit
Definition at line 34 of file GenericDomTreeUpdater.h.
GenericDomTreeUpdater() [2/7]
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::GenericDomTreeUpdater (DomTreeT & DT_, UpdateStrategy Strategy_) inline
Definition at line 36 of file GenericDomTreeUpdater.h.
GenericDomTreeUpdater() [3/7]
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::GenericDomTreeUpdater (DomTreeT * DT_, UpdateStrategy Strategy_) inline
Definition at line 38 of file GenericDomTreeUpdater.h.
GenericDomTreeUpdater() [4/7]
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::GenericDomTreeUpdater (PostDomTreeT & PDT_, UpdateStrategy Strategy_) inline
Definition at line 40 of file GenericDomTreeUpdater.h.
GenericDomTreeUpdater() [5/7]
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::GenericDomTreeUpdater (PostDomTreeT * PDT_, UpdateStrategy Strategy_) inline
Definition at line 42 of file GenericDomTreeUpdater.h.
GenericDomTreeUpdater() [6/7]
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::GenericDomTreeUpdater (DomTreeT & DT_, PostDomTreeT & PDT_, UpdateStrategy Strategy_) inline
Definition at line 44 of file GenericDomTreeUpdater.h.
GenericDomTreeUpdater() [7/7]
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::GenericDomTreeUpdater (DomTreeT * DT_, PostDomTreeT * PDT_, UpdateStrategy Strategy_) inline
Definition at line 47 of file GenericDomTreeUpdater.h.
~GenericDomTreeUpdater()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::~GenericDomTreeUpdater () inline
Definition at line 51 of file GenericDomTreeUpdater.h.
References assert(), and llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingUpdates().
Member Function Documentation
applyDomTreeUpdates()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > void llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::applyDomTreeUpdates () protected
Helper function to apply all pending DomTree updates.
Definition at line 248 of file GenericDomTreeUpdaterImpl.h.
References assert(), and I.
Referenced by llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::flush().
applyPostDomTreeUpdates()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > void llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::applyPostDomTreeUpdates () protected
Helper function to apply all pending PostDomTree updates.
Definition at line 265 of file GenericDomTreeUpdaterImpl.h.
References assert(), and I.
Referenced by llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::flush().
applyUpdates()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > void llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::applyUpdates (ArrayRef< typename DomTreeT::UpdateType > Updates)
Submit updates to all available trees.
The Eager Strategy flushes updates immediately while the Lazy Strategy queues the updates.
Note: The "existence" of an edge in a CFG refers to the CFG which DTU is in sync with + all updates before that single update.
CAUTION!
It is required for the state of the LLVM IR to be updated before submitting the updates because the internal update routine will analyze the current state of the CFG to determine whether an update is valid.
It is illegal to submit any update that has already been submitted, i.e., you are supposed not to insert an existent edge or delete a nonexistent edge.
Definition at line 58 of file GenericDomTreeUpdaterImpl.h.
References llvm::ArrayRef< T >::size().
Referenced by llvm::breakLoopBackedge(), llvm::changeToCall(), llvm::changeToInvokeAndSplitBasicBlock(), llvm::changeToUnreachable(), llvm::ConstantFoldTerminator(), createUnreachableSwitchDefault(), llvm::DeleteDeadBlocks(), llvm::deleteDeadLoop(), llvm::DuplicateInstructionsInSplitBetween(), llvm::ehAwareSplitEdge(), eliminateDeadSwitchCases(), expandToSwitch(), FoldCondBranchOnValueKnownInPredecessorImpl(), foldMemChr(), llvm::FoldReturnIntoUncondBranch(), FoldTwoEntryPHINode(), llvm::MergeBlockIntoPredecessor(), MergeCompatibleInvokesImpl(), mergeNestedCondBranch(), performBranchToCommonDestFolding(), processSwitch(), removeEmptyCleanup(), removeSwitchAfterSelectFold(), removeUndefIntroducingPredecessor(), llvm::removeUnwindEdge(), replaceConditionalBranchesOnConstant(), runImpl(), SimplifyCondBranchToCondBranch(), llvm::SplitBlockAndInsertIfThenElse(), llvm::splitBlockBefore(), SplitBlockImpl(), SwitchToLookupTable(), tailMergeBlocksWithSimilarFunctionTerminators(), TryToMergeLandingPad(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), tryWidenCondBranchToCondBranch(), llvm::UnrollLoop(), and UpdateAnalysisInformation().
applyUpdatesPermissive()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > void llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::applyUpdatesPermissive (ArrayRef< typename DomTreeT::UpdateType > Updates)
Submit updates to all available trees.
It will also
discard duplicated updates,
remove invalid updates. (Invalid updates means deletion of an edge that still exists or insertion of an edge that does not exist.) The Eager Strategy flushes updates immediately while the Lazy Strategy queues the updates.
Note: The "existence" of an edge in a CFG refers to the CFG which DTU is in sync with + all updates before that single update.
CAUTION!
It is required for the state of the LLVM IR to be updated before submitting the updates because the internal update routine will analyze the current state of the CFG to determine whether an update is valid.
It is illegal to submit any update that has already been submitted, i.e., you are supposed not to insert an existent edge or delete a nonexistent edge.
It is only legal to submit updates to an edge in the order CFG changes are made. The order you submit updates on different edges is not restricted.
Definition at line 79 of file GenericDomTreeUpdaterImpl.h.
References llvm::SmallSet< T, N, C >::count(), llvm::SmallSet< T, N, C >::insert(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::MergeBasicBlockIntoOnlyPred(), processSwitch(), llvm::SCCPSolver::removeNonFeasibleEdges(), splitCallSite(), and llvm::UnrollAndJamLoop().
dropOutOfDateUpdates()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > void llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::dropOutOfDateUpdates () protected
Drop all updates applied by all available trees and delete BasicBlocks if all available trees are up-to-date.
Definition at line 329 of file GenericDomTreeUpdaterImpl.h.
References assert(), and B.
Referenced by llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::flush().
dump()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > LLVM_DUMP_METHOD void llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::dump () const
Debug method to help view the internal state of this class.
Definition at line 153 of file GenericDomTreeUpdaterImpl.h.
References llvm::dbgs(), and OS.
eraseDelBBNode()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > void llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::eraseDelBBNode (BasicBlockT * DelBB) protected
Erase Basic Block node that has been unlinked from Function in the DomTree and PostDomTree.
Definition at line 309 of file GenericDomTreeUpdaterImpl.h.
flush()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > void llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::flush () inline
Apply all pending updates to available trees and flush all BasicBlocks awaiting deletion.
Definition at line 196 of file GenericDomTreeUpdater.h.
References llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::applyDomTreeUpdates(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::applyPostDomTreeUpdates(), and llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::dropOutOfDateUpdates().
Referenced by llvm::ehAwareSplitEdge(), and llvm::JumpThreadingPass::run().
getDomTree()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > DomTreeT & llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::getDomTree ()
Flush DomTree updates and return DomTree.
It flushes Deleted BBs if both trees are up-to-date. It must only be called when it has a DomTree.
Definition at line 135 of file GenericDomTreeUpdaterImpl.h.
References assert().
Referenced by runImpl(), llvm::RewriteStatepointsForGC::runOnFunction(), shouldSplitOnPredicatedArgument(), llvm::splitBlockBefore(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), and UpdateAnalysisInformation().
getPostDomTree()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > PostDomTreeT & llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::getPostDomTree ()
Flush PostDomTree updates and return PostDomTree.
It flushes Deleted BBs if both trees are up-to-date. It must only be called when it has a PostDomTree.
Definition at line 144 of file GenericDomTreeUpdaterImpl.h.
References assert().
hasDomTree()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > bool llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasDomTree () const inline
Returns true if it holds a DomTreeT.
Definition at line 64 of file GenericDomTreeUpdater.h.
References llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::DT.
Referenced by llvm::MergeBasicBlockIntoOnlyPred(), shouldSplitOnPredicatedArgument(), and UpdateAnalysisInformation().
hasPendingDeletedBB()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > bool llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingDeletedBB () const inline
Returns true if there is BasicBlockT awaiting deletion.
The deletion will only happen until a flush event and all available trees are up-to-date. Returns false under Eager UpdateStrategy.
Definition at line 73 of file GenericDomTreeUpdater.h.
References llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::DeletedBBs, and llvm::SmallPtrSetImplBase::empty().
hasPendingDomTreeUpdates()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > bool llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingDomTreeUpdates () const inline
Returns true if there are DomTreeT updates queued.
Returns false under Eager UpdateStrategy or DT is nullptr.
Definition at line 94 of file GenericDomTreeUpdater.h.
References llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::DT, llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::PendDTUpdateIndex, llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::PendUpdates, and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingUpdates().
hasPendingPostDomTreeUpdates()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > bool llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingPostDomTreeUpdates () const inline
Returns true if there are PostDomTreeT updates queued.
Returns false under Eager UpdateStrategy or PDT is nullptr.
Definition at line 102 of file GenericDomTreeUpdater.h.
References llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::PDT, llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::PendPDTUpdateIndex, llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::PendUpdates, and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingUpdates().
hasPendingUpdates()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > bool llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingUpdates () const inline
Returns true if either of DT or PDT is valid and the tree has at least one update pending.
If DT or PDT is nullptr it is treated as having no pending updates. This function does not check whether there is MachineBasicBlock awaiting deletion. Returns false under Eager UpdateStrategy.
Definition at line 88 of file GenericDomTreeUpdater.h.
References llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingDomTreeUpdates(), and llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingPostDomTreeUpdates().
Referenced by llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::~GenericDomTreeUpdater().
hasPostDomTree()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > bool llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPostDomTree () const inline
Returns true if it holds a PostDomTreeT.
Definition at line 67 of file GenericDomTreeUpdater.h.
References llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::PDT.
isBBPendingDeletion()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > bool llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::isBBPendingDeletion (BasicBlockT * DelBB) const inline
Returns true if DelBB is awaiting deletion.
Returns false under Eager UpdateStrategy.
Definition at line 77 of file GenericDomTreeUpdater.h.
References llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::DeletedBBs, llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::Eager, llvm::SmallPtrSetImplBase::empty(), and llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::Strategy.
Referenced by iterativelySimplifyCFG(), llvm::removeUnreachableBlocks(), and tailMergeBlocksWithSimilarFunctionTerminators().
isEager()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > bool llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::isEager () const inline
Returns true if the current strategy is Eager.
Definition at line 61 of file GenericDomTreeUpdater.h.
References llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::Eager, and llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::Strategy.
isLazy()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > bool llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::isLazy () const inline
Returns true if the current strategy is Lazy.
Definition at line 58 of file GenericDomTreeUpdater.h.
References llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::Lazy, and llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::Strategy.
isSelfDominance()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > bool llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::isSelfDominance (typename DomTreeT::UpdateType Update) const inline protected
Returns true if the update is self dominance.
Definition at line 219 of file GenericDomTreeUpdater.h.
isUpdateValid()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > bool llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::isUpdateValid (typename DomTreeT::UpdateType Update) const protected
Returns true if the update appears in the LLVM IR.
It is used to check whether an update is valid in insertEdge/deleteEdge or is unnecessary in the batch update.
Definition at line 282 of file GenericDomTreeUpdaterImpl.h.
References From, llvm::is_contained(), and llvm::successors().
recalculate()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > template<typename FuncT > template void llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::recalculate (FuncT & F)
Notify DTU that the entry block was replaced.
Recalculate all available trees and flush all BasicBlocks awaiting deletion immediately.
Definition at line 27 of file GenericDomTreeUpdaterImpl.h.
References F.
Referenced by llvm::MergeBasicBlockIntoOnlyPred(), and UpdateAnalysisInformation().
tryFlushDeletedBB()
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > void llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::tryFlushDeletedBB () protected
Helper function to flush deleted BasicBlocks if all available trees are up-to-date.
Definition at line 322 of file GenericDomTreeUpdaterImpl.h.
Member Data Documentation
DeletedBBs
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > SmallPtrSet<BasicBlockT *, 8> llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::DeletedBBs protected
Definition at line 214 of file GenericDomTreeUpdater.h.
Referenced by llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingDeletedBB(), and llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::isBBPendingDeletion().
DT
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > DomTreeT* llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::DT = nullptr protected
Definition at line 211 of file GenericDomTreeUpdater.h.
Referenced by llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasDomTree(), and llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingDomTreeUpdates().
IsRecalculatingDomTree
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > bool llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::IsRecalculatingDomTree = false protected
Definition at line 215 of file GenericDomTreeUpdater.h.
IsRecalculatingPostDomTree
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > bool llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::IsRecalculatingPostDomTree = false protected
Definition at line 216 of file GenericDomTreeUpdater.h.
PDT
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > PostDomTreeT* llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::PDT = nullptr protected
Definition at line 212 of file GenericDomTreeUpdater.h.
Referenced by llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingPostDomTreeUpdates(), and llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPostDomTree().
PendDTUpdateIndex
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > size_t llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::PendDTUpdateIndex = 0 protected
Definition at line 209 of file GenericDomTreeUpdater.h.
Referenced by llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingDomTreeUpdates().
PendPDTUpdateIndex
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > size_t llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::PendPDTUpdateIndex = 0 protected
Definition at line 210 of file GenericDomTreeUpdater.h.
Referenced by llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingPostDomTreeUpdates().
PendUpdates
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > SmallVector<typename DomTreeT::UpdateType, 16> llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::PendUpdates protected
Definition at line 208 of file GenericDomTreeUpdater.h.
Referenced by llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingDomTreeUpdates(), and llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::hasPendingPostDomTreeUpdates().
Strategy
template<typename DerivedT , typename DomTreeT , typename PostDomTreeT > const UpdateStrategy llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::Strategy protected
Definition at line 213 of file GenericDomTreeUpdater.h.
Referenced by llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::isBBPendingDeletion(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::isEager(), and llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::isLazy().
The documentation for this class was generated from the following files:
include/llvm/Analysis/GenericDomTreeUpdater.h
include/llvm/Analysis/DomTreeUpdater.h
include/llvm/Analysis/GenericDomTreeUpdaterImpl.h
include/llvm/CodeGen/MachineDomTreeUpdater.h
lib/Analysis/DomTreeUpdater.cpp
lib/CodeGen/MachineDomTreeUpdater.cpp