LLVM: llvm::mcdxbc::Signature Class Reference
llvm::mcdxbc::Signature Class Reference
#include "llvm/MC/DXContainerPSVInfo.h"
Public Member Functions
void addParam (uint32_t Stream, StringRef Name, uint32_t Index, dxbc::D3DSystemValue SystemValue, dxbc::SigComponentType CompType, uint32_t Register, uint8_t Mask, uint8_t ExclusiveMask, dxbc::SigMinPrecision MinPrecision)
void write (raw_ostream &OS)
Detailed Description
Definition at line 88 of file DXContainerPSVInfo.h.
Member Function Documentation
addParam()
void llvm::mcdxbc::Signature::addParam (uint32_t Stream, StringRef Name, uint32_t Index, dxbc::D3DSystemValue SystemValue, dxbc::SigComponentType CompType, uint32_t Register, uint8_t Mask, uint8_t ExclusiveMask, dxbc::SigMinPrecision MinPrecision) inline
Definition at line 104 of file DXContainerPSVInfo.h.
References Name, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and Register.
write()
void Signature::write (raw_ostream & OS)
Definition at line 190 of file DXContainerPSVInfo.cpp.
References llvm::StringTableBuilder::add(), llvm::dxbc::ProgramSignatureElement::CompType, llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::StringTableBuilder::DWARF, llvm::dxbc::ProgramSignatureElement::ExclusiveMask, llvm::StringTableBuilder::finalizeInOrder(), llvm::dxbc::ProgramSignatureElement::Index, llvm::sys::IsBigEndianHost, llvm::dxbc::ProgramSignatureElement::Mask, llvm::dxbc::ProgramSignatureElement::MinPrecision, llvm::dxbc::ProgramSignatureElement::NameOffset, OS, P, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::dxbc::ProgramSignatureElement::Register, llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorBase< Size_T >::size(), llvm::stable_sort(), llvm::dxbc::ProgramSignatureElement::Stream, llvm::dxbc::ProgramSignatureHeader::swapBytes(), llvm::dxbc::ProgramSignatureElement::SystemValue, llvm::raw_ostream::write(), and llvm::StringTableBuilder::write().
The documentation for this class was generated from the following files:
include/llvm/MC/DXContainerPSVInfo.h
lib/MC/DXContainerPSVInfo.cpp