LLVM: llvm::MLPriorityAdvisor Class Reference
llvm::MLPriorityAdvisor Class Reference
Public Member Functions
MLPriorityAdvisor (const MachineFunction &MF, const RAGreedy &RA, SlotIndexes *const Indexes, MLModelRunner *Runner)
Public Member Functions inherited from llvm::RegAllocPriorityAdvisor
RegAllocPriorityAdvisor (const RegAllocPriorityAdvisor &)=delete
RegAllocPriorityAdvisor (RegAllocPriorityAdvisor &&)=delete
virtual ~RegAllocPriorityAdvisor ()=default
RegAllocPriorityAdvisor (const MachineFunction &MF, const RAGreedy &RA, SlotIndexes *const Indexes)
Protected Member Functions
const RegAllocPriorityAdvisor & getDefaultAdvisor () const
const MLModelRunner & getRunner () const
float getPriorityImpl (const LiveInterval &LI) const
unsigned getPriority (const LiveInterval &LI) const override
Find the priority value for a live range.
Additional Inherited Members
Protected Attributes inherited from llvm::RegAllocPriorityAdvisor
const RAGreedy & RA
LiveIntervals *const LIS
VirtRegMap *const VRM
MachineRegisterInfo *const MRI
const TargetRegisterInfo *const TRI
const RegisterClassInfo & RegClassInfo
SlotIndexes *const Indexes
const bool RegClassPriorityTrumpsGlobalness
const bool ReverseLocalAssignment
Detailed Description
Definition at line 92 of file MLRegAllocPriorityAdvisor.cpp.
Constructor & Destructor Documentation
MLPriorityAdvisor()
MLPriorityAdvisor::MLPriorityAdvisor (const MachineFunction & MF, const RAGreedy & RA, SlotIndexes *const Indexes, MLModelRunner * Runner)
Definition at line 287 of file MLRegAllocPriorityAdvisor.cpp.
References assert(), llvm::MachineFunction::getName(), and llvm::MLModelRunner::switchContext().
Member Function Documentation
getDefaultAdvisor()
const RegAllocPriorityAdvisor & llvm::MLPriorityAdvisor::getDefaultAdvisor () const inline protected
Definition at line 98 of file MLRegAllocPriorityAdvisor.cpp.
getPriority()
unsigned MLPriorityAdvisor::getPriority (const LiveInterval & LI) const override protected virtual
Find the priority value for a live range.
A float value is used since ML prefers it.
Implements llvm::RegAllocPriorityAdvisor.
Definition at line 308 of file MLRegAllocPriorityAdvisor.cpp.
References getPriorityImpl().
getPriorityImpl()
float MLPriorityAdvisor::getPriorityImpl (const LiveInterval & LI) const protected
Definition at line 297 of file MLRegAllocPriorityAdvisor.cpp.
References llvm::MLModelRunner::evaluate(), llvm::RAGreedy::getExtraInfo(), llvm::LiveInterval::getSize(), llvm::RAGreedy::ExtraRegInfo::getStage(), llvm::MLModelRunner::getTensor(), llvm::RegAllocPriorityAdvisor::RA, Size, and llvm::LiveInterval::weight().
Referenced by getPriority().
getRunner()
const MLModelRunner & llvm::MLPriorityAdvisor::getRunner () const inline protected
Definition at line 104 of file MLRegAllocPriorityAdvisor.cpp.
The documentation for this class was generated from the following file:
lib/CodeGen/MLRegAllocPriorityAdvisor.cpp