LLVM: llvm::logicalview::LVLineAssembler Class Reference
llvm::logicalview::LVLineAssembler Class Reference final
#include "llvm/DebugInfo/LogicalView/Core/LVLine.h"
Public Member Functions
LVLineAssembler ()
LVLineAssembler (const LVLineAssembler &)=delete
LVLineAssembler & operator= (const LVLineAssembler &)=delete
~LVLineAssembler ()=default
std::string noLineAsString (bool ShowZero) const override
bool equals (const LVLine *Line) const override
void printExtra (raw_ostream &OS, bool Full=true) const override
Public Member Functions inherited from llvm::logicalview::LVLine
LVLine ()
LVLine (const LVLine &)=delete
LVLine & operator= (const LVLine &)=delete
virtual ~LVLine ()=default
KIND (LVLineKind, IsBasicBlock)
KIND (LVLineKind, IsDiscriminator)
KIND (LVLineKind, IsEndSequence)
KIND (LVLineKind, IsEpilogueBegin)
KIND (LVLineKind, IsLineDebug)
KIND (LVLineKind, IsLineAssembler)
KIND (LVLineKind, IsNewStatement)
KIND (LVLineKind, IsPrologueEnd)
KIND (LVLineKind, IsAlwaysStepInto)
KIND (LVLineKind, IsNeverStepInto)
const char * kind () const override
uint64_t getAddress () const
void setAddress (uint64_t address)
std::string lineNumberAsString (bool ShowZero=false) const override
void report (LVComparePass Pass) override
void print (raw_ostream &OS, bool Full=true) const override
void dump () const override
Public Member Functions inherited from llvm::logicalview::LVElement
LVElement (LVSubclassID ID)
LVElement (const LVElement &)=delete
LVElement & operator= (const LVElement &)=delete
virtual ~LVElement ()=default
LVSubclassID getSubclassID () const
PROPERTY (Property, IsLine)
PROPERTY (Property, IsScope)
PROPERTY (Property, IsSymbol)
PROPERTY (Property, IsType)
PROPERTY (Property, IsEnumClass)
PROPERTY (Property, IsExternal)
PROPERTY (Property, HasType)
PROPERTY (Property, HasAugmentedName)
PROPERTY (Property, IsTypedefReduced)
PROPERTY (Property, IsArrayResolved)
PROPERTY (Property, IsMemberPointerResolved)
PROPERTY (Property, IsTemplateResolved)
PROPERTY (Property, IsInlined)
PROPERTY (Property, IsInlinedAbstract)
PROPERTY (Property, InvalidFilename)
PROPERTY (Property, HasReference)
PROPERTY (Property, HasReferenceAbstract)
PROPERTY (Property, HasReferenceExtension)
PROPERTY (Property, HasReferenceSpecification)
PROPERTY (Property, QualifiedResolved)
PROPERTY (Property, IncludeInPrint)
PROPERTY (Property, IsStatic)
PROPERTY (Property, TransformName)
PROPERTY (Property, IsScoped)
PROPERTY (Property, IsNested)
PROPERTY (Property, IsScopedAlready)
PROPERTY (Property, IsArtificial)
PROPERTY (Property, IsReferencedType)
PROPERTY (Property, IsSystem)
PROPERTY (Property, OffsetFromTypeIndex)
PROPERTY (Property, IsAnonymous)
bool isNamed () const override
bool isTyped () const override
bool isFiled () const override
bool getIsKindType () const
bool getIsKindScope () const
StringRef getName () const override
void setName (StringRef ElementName) override
StringRef getPathname () const
void setFilename (StringRef Filename)
void setQualifiedName (StringRef Name)
StringRef getQualifiedName () const
size_t getNameIndex () const
size_t getQualifiedNameIndex () const
void setInnerComponent ()
void setInnerComponent (StringRef Name)
StringRef getTypeName () const
virtual StringRef getProducer () const
virtual void setProducer (StringRef ProducerName)
virtual bool isCompileUnit () const
virtual bool isRoot () const
virtual void setReference (LVElement *Element)
virtual void setReference (LVScope *Scope)
virtual void setReference (LVSymbol *Symbol)
virtual void setReference (LVType *Type)
virtual void setLinkageName (StringRef LinkageName)
virtual StringRef getLinkageName () const
virtual size_t getLinkageNameIndex () const
virtual uint32_t getCallLineNumber () const
virtual void setCallLineNumber (uint32_t Number)
virtual size_t getCallFilenameIndex () const
virtual void setCallFilenameIndex (size_t Index)
size_t getFilenameIndex () const
void setFilenameIndex (size_t Index)
void setFile (LVElement *Reference=nullptr)
virtual bool isBase () const
virtual bool isTemplateParam () const
virtual uint32_t getBitSize () const
virtual void setBitSize (uint32_t Size)
virtual int64_t getCount () const
virtual void setCount (int64_t Value)
virtual int64_t getLowerBound () const
virtual void setLowerBound (int64_t Value)
virtual int64_t getUpperBound () const
virtual void setUpperBound (int64_t Value)
virtual std::pair< unsigned, unsigned > getBounds () const
virtual void setBounds (unsigned Lower, unsigned Upper)
virtual uint32_t getDiscriminator () const
virtual void setDiscriminator (uint32_t Value)
virtual StringRef getValue () const
virtual void setValue (StringRef Value)
virtual size_t getValueIndex () const
uint32_t getAccessibilityCode () const
void setAccessibilityCode (uint32_t Access)
StringRef accessibilityString (uint32_t Access=dwarf::DW_ACCESS_private) const
std::optional< uint32_t > getAccessibilityCode (codeview::MemberAccess Access)
void setAccessibilityCode (codeview::MemberAccess Access)
uint32_t getInlineCode () const
void setInlineCode (uint32_t Code)
StringRef inlineCodeString (uint32_t Code) const
uint32_t getVirtualityCode () const
void setVirtualityCode (uint32_t Virtuality)
StringRef virtualityString (uint32_t Virtuality=dwarf::DW_VIRTUALITY_none) const
std::optional< uint32_t > getVirtualityCode (codeview::MethodKind Virtuality)
void setVirtualityCode (codeview::MethodKind Virtuality)
StringRef externalString () const
LVElement * getType () const
LVType * getTypeAsType () const
LVScope * getTypeAsScope () const
void setType (LVElement *Element=nullptr)
void setGenericType (LVElement *Element)
StringRef getTypeQualifiedName () const
StringRef typeAsString () const
std::string typeOffsetAsString () const
std::string discriminatorAsString () const
LVScope * traverseParents (LVScopeGetFunction GetFunction) const
LVScope * getFunctionParent () const
virtual LVScope * getCompileUnitParent () const
void printReference (raw_ostream &OS, bool Full, LVElement *Parent) const
void printLinkageName (raw_ostream &OS, bool Full, LVElement *Parent, LVScope *Scope) const
void printLinkageName (raw_ostream &OS, bool Full, LVElement *Parent) const
void resolveFullname (LVElement *BaseType, StringRef Name=emptyString())
void generateName (std::string &Prefix) const
void generateName ()
virtual bool removeElement (LVElement *Element)
virtual void updateLevel (LVScope *Parent, bool Moved=false)
virtual void resolve ()
virtual void resolveExtra ()
virtual void resolveName ()
virtual void resolveReferences ()
void resolveParents ()
bool referenceMatch (const LVElement *Element) const
bool equals (const LVElement *Element) const
Public Member Functions inherited from llvm::logicalview::LVObject
LVObject ()
LVObject & operator= (const LVObject &)=delete
virtual ~LVObject ()=default
PROPERTY (Property, IsLocation)
PROPERTY (Property, IsGlobalReference)
PROPERTY (Property, IsGeneratedName)
PROPERTY (Property, IsResolved)
PROPERTY (Property, IsResolvedName)
PROPERTY (Property, IsDiscarded)
PROPERTY (Property, IsOptimized)
PROPERTY (Property, IsAdded)
PROPERTY (Property, IsMatched)
PROPERTY (Property, IsMissing)
PROPERTY (Property, IsMissingLink)
PROPERTY (Property, IsInCompare)
PROPERTY (Property, IsFileFromReference)
PROPERTY (Property, IsLineFromReference)
PROPERTY (Property, HasMoved)
PROPERTY (Property, HasPattern)
PROPERTY (Property, IsFinalized)
PROPERTY (Property, IsReferenced)
PROPERTY (Property, HasCodeViewLocation)
bool isLined () const
dwarf::Tag getTag () const
void setTag (dwarf::Tag Tag)
dwarf::Attribute getAttr () const
void setAttr (dwarf::Attribute Attr)
LVSmall getOpcode () const
void setOpcode (LVSmall Opcode)
LVOffset getOffset () const
void setOffset (LVOffset DieOffset)
LVLevel getLevel () const
void setLevel (LVLevel Level)
LVElement * getParent () const
LVScope * getParentScope () const
LVSymbol * getParentSymbol () const
void setParent (LVScope *Scope)
void setParent (LVSymbol *Symbol)
void resetParent ()
virtual LVAddress getLowerAddress () const
virtual void setLowerAddress (LVAddress Address)
virtual LVAddress getUpperAddress () const
virtual void setUpperAddress (LVAddress Address)
uint32_t getLineNumber () const
void setLineNumber (uint32_t Number)
std::string indentAsString () const
std::string indentAsString (LVLevel Level) const
std::string lineNumberAsStringStripped (bool ShowZero=false) const
virtual Error doPrint (bool Split, bool Match, bool Print, raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full=true) const
void printAttributes (raw_ostream &OS, bool Full, StringRef Name, LVObject *Parent, StringRef Value, bool UseQuotes=false, bool PrintRef=false) const
void markBranchAsMissing ()
uint64_t getID () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::logicalview::LVLine
static bool classof (const LVElement *Element)
static LVLineDispatch & getDispatch ()
static void markMissingParents (const LVLines *References, const LVLines *Targets)
static bool equals (const LVLines *References, const LVLines *Targets)
Static Public Member Functions inherited from llvm::logicalview::LVElement
static LVElementDispatch & getDispatch ()
Public Attributes inherited from llvm::logicalview::LVObject
Protected Member Functions inherited from llvm::logicalview::LVElement
void printFileIndex (raw_ostream &OS, bool Full=true) const override
Protected Member Functions inherited from llvm::logicalview::LVObject
std::string lineAsString (uint32_t LineNumber, LVHalf Discriminator, bool ShowZero) const
std::string referenceAsString (uint32_t LineNumber, bool Spaces) const
Protected Attributes inherited from llvm::logicalview::LVElement
LVElement * ElementType = nullptr
Detailed Description
Definition at line 143 of file LVLine.h.
Constructor & Destructor Documentation
LVLineAssembler() [1/2]
llvm::logicalview::LVLineAssembler::LVLineAssembler () inline
Definition at line 145 of file LVLine.h.
LVLineAssembler() [2/2]
llvm::logicalview::LVLineAssembler::LVLineAssembler (const LVLineAssembler &) delete
~LVLineAssembler()
llvm::logicalview::LVLineAssembler::~LVLineAssembler () default
Member Function Documentation
equals()
bool LVLineAssembler::equals (const LVLine * Line) const override virtual
Reimplemented from llvm::logicalview::LVLine.
Definition at line 214 of file LVLine.cpp.
References llvm::logicalview::LVLine::equals().
noLineAsString()
std::string llvm::logicalview::LVLineAssembler::noLineAsString (bool ShowZero) const inline override virtual
Reimplemented from llvm::logicalview::LVLine.
Definition at line 151 of file LVLine.h.
operator=()
LVLineAssembler & llvm::logicalview::LVLineAssembler::operator= (const LVLineAssembler &) delete
printExtra()
void LVLineAssembler::printExtra (raw_ostream & OS, bool Full = true) const override virtual
Reimplemented from llvm::logicalview::LVLine.
Definition at line 218 of file LVLine.cpp.
References llvm::logicalview::formattedKind(), llvm::logicalview::formattedName(), llvm::logicalview::LVElement::getName(), llvm::logicalview::LVLine::kind(), and OS.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVLine.h
lib/DebugInfo/LogicalView/Core/LVLine.cpp