LLVM: llvm::TwoAddressInstructionPass Class Reference
llvm::TwoAddressInstructionPass Class Reference
#include "llvm/CodeGen/TwoAddressInstructionPass.h"
Public Member Functions
PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MFAM)
MachineFunctionProperties getSetProperties ()
Public Member Functions inherited from llvm::PassInfoMixin< TwoAddressInstructionPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< TwoAddressInstructionPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 16 of file TwoAddressInstructionPass.h.
Member Function Documentation
getSetProperties()
MachineFunctionProperties llvm::TwoAddressInstructionPass::getSetProperties () inline
Definition at line 21 of file TwoAddressInstructionPass.h.
References llvm::MachineFunctionProperties::set(), and llvm::MachineFunctionProperties::TiedOpsRewritten.
run()
PreservedAnalyses TwoAddressInstructionPass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MFAM)
Definition at line 234 of file TwoAddressInstructionPass.cpp.
References _, llvm::PreservedAnalyses::all(), Changed, llvm::MachineFunction::getFunction(), llvm::getMachineFunctionPassPreservedAnalyses(), llvm::Function::hasOptNone(), and llvm::None.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/TwoAddressInstructionPass.h
lib/CodeGen/TwoAddressInstructionPass.cpp