LLVM: llvm::PGOInstrumentationGenCreateVar Class Reference
llvm::PGOInstrumentationGenCreateVar Class Reference
The instrumentation (profile-instr-gen) pass for IR based PGO.
#include "llvm/Transforms/Instrumentation/PGOInstrumentation.h"
Public Member Functions
PGOInstrumentationGenCreateVar (std::string CSInstrName="", bool Sampling=false)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &MAM)
Public Member Functions inherited from llvm::PassInfoMixin< PGOInstrumentationGenCreateVar >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< PGOInstrumentationGenCreateVar >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
The instrumentation (profile-instr-gen) pass for IR based PGO.
Definition at line 43 of file PGOInstrumentation.h.
Constructor & Destructor Documentation
PGOInstrumentationGenCreateVar()
llvm::PGOInstrumentationGenCreateVar::PGOInstrumentationGenCreateVar (std::string CSInstrName = "", bool Sampling = false) inline
Definition at line 46 of file PGOInstrumentation.h.
Member Function Documentation
run()
PreservedAnalyses PGOInstrumentationGenCreateVar::run (Module & M, ModuleAnalysisManager & MAM)
Definition at line 1896 of file PGOInstrumentation.cpp.
References llvm::appendToCompilerUsed(), createIRLevelProfileFlagVar(), llvm::createProfileFileNameVar(), llvm::createProfileSamplingVar(), llvm::PreservedAnalyses::preserve(), and llvm::PreservedAnalyses::preserveSet().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/PGOInstrumentation.h
lib/Transforms/Instrumentation/PGOInstrumentation.cpp