LLVM: llvm::StringMapEntryStorage< ValueTy > Class Template Reference
llvm::StringMapEntryStorage< ValueTy > Class Template Reference
StringMapEntryStorage - Holds the value in a StringMapEntry.
#include "llvm/ADT/StringMapEntry.h"
Public Member Functions
StringMapEntryStorage (size_t keyLength)
template<typename... InitTy>
StringMapEntryStorage (size_t keyLength, InitTy &&...initVals)
StringMapEntryStorage (StringMapEntryStorage &e)=delete
const ValueTy & getValue () const
ValueTy & getValue ()
void setValue (const ValueTy &V)
Public Member Functions inherited from llvm::StringMapEntryBase
StringMapEntryBase (size_t keyLength)
size_t getKeyLength () const
Public Attributes
ValueTy second
Additional Inherited Members
Static Protected Member Functions inherited from llvm::StringMapEntryBase
template<typename AllocatorTy >
static void * allocateWithKey (size_t EntrySize, size_t EntryAlign, StringRef Key, AllocatorTy &Allocator)
Helper to tail-allocate Key.
Detailed Description
template<typename ValueTy>
class llvm::StringMapEntryStorage< ValueTy >
StringMapEntryStorage - Holds the value in a StringMapEntry.
Factored out into a separate base class to make it easier to specialize. This is primarily intended to support StringSet, which doesn't need a value stored at all.
Definition at line 48 of file Metadata.h.
Constructor & Destructor Documentation
StringMapEntryStorage() [1/3]
template<typename ValueTy > llvm::StringMapEntryStorage< ValueTy >::StringMapEntryStorage (size_t keyLength) inline explicit
Definition at line 73 of file StringMapEntry.h.
StringMapEntryStorage() [2/3]
template<typename ValueTy > template<typename... InitTy> llvm::StringMapEntryStorage< ValueTy >::StringMapEntryStorage (size_t keyLength, InitTy &&... initVals) inline
Definition at line 76 of file StringMapEntry.h.
StringMapEntryStorage() [3/3]
template<typename ValueTy > llvm::StringMapEntryStorage< ValueTy >::StringMapEntryStorage (StringMapEntryStorage< ValueTy > & e) delete
Member Function Documentation
getValue() [1/2]
template<typename ValueTy > ValueTy & llvm::StringMapEntryStorage< ValueTy >::getValue () inline
Definition at line 82 of file StringMapEntry.h.
References llvm::StringMapEntryStorage< ValueTy >::second.
getValue() [2/2]
template<typename ValueTy > const ValueTy & llvm::StringMapEntryStorage< ValueTy >::getValue () const inline
Definition at line 81 of file StringMapEntry.h.
References llvm::StringMapEntryStorage< ValueTy >::second.
Referenced by llvm::dwarf_linker::parallel::TypePool::getOrCreateTypeEntryBody(), llvm::orc::SymbolStringPtrBase::getRefCount(), llvm::orc::SymbolStringPtrBase::poolEntryIsAlive(), llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::saveNamespaceRecord(), llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::saveTypeRecord(), llvm::orc::SymbolStringPtr::SymbolStringPtr(), and llvm::dwarf_linker::parallel::TypePool::TypePool().
setValue()
template<typename ValueTy > void llvm::StringMapEntryStorage< ValueTy >::setValue (const ValueTy & V) inline
Definition at line 84 of file StringMapEntry.h.
References llvm::StringMapEntryStorage< ValueTy >::second.
Referenced by llvm::Value::takeName().
Member Data Documentation
second
template<typename ValueTy > ValueTy llvm::StringMapEntryStorage< ValueTy >::second
Definition at line 71 of file StringMapEntry.h.
Referenced by llvm::computeLTOCacheKey(), llvm::StringMapEntryStorage< ValueTy >::getValue(), llvm::StringMapEntryStorage< ValueTy >::getValue(), llvm::MCContext::getWasmSection(), and llvm::StringMapEntryStorage< ValueTy >::setValue().
The documentation for this class was generated from the following files:
include/llvm/ADT/StringMapEntry.h
include/llvm/IR/Metadata.h