LLVM: llvm::SampleProfileMatcher Class Reference
llvm::SampleProfileMatcher Class Reference
#include "llvm/Transforms/IPO/SampleProfileMatcher.h"
Public Member Functions
SampleProfileMatcher (Module &M, SampleProfileReader &Reader, LazyCallGraph &CG, const PseudoProbeManager *ProbeManager, ThinOrFullLTOPhase LTOPhase, HashKeyMap< std::unordered_map, FunctionId, Function * > &SymMap, std::shared_ptr< ProfileSymbolList > PSL, HashKeyMap< std::unordered_map, FunctionId, FunctionId > &FuncNameToProfNameMap)
void runOnModule ()
void clearMatchingData ()
Detailed Description
Definition at line 26 of file SampleProfileMatcher.h.
Constructor & Destructor Documentation
SampleProfileMatcher()
llvm::SampleProfileMatcher::SampleProfileMatcher (Module & M, SampleProfileReader & Reader, LazyCallGraph & CG, const PseudoProbeManager * ProbeManager, ThinOrFullLTOPhase LTOPhase, HashKeyMap< std::unordered_map, FunctionId, Function * > & SymMap, std::shared_ptr< ProfileSymbolList > PSL, HashKeyMap< std::unordered_map, FunctionId, FunctionId > & FuncNameToProfNameMap) inline
Definition at line 120 of file SampleProfileMatcher.h.
Member Function Documentation
clearMatchingData()
void llvm::SampleProfileMatcher::clearMatchingData () inline
Definition at line 131 of file SampleProfileMatcher.h.
runOnModule()
void SampleProfileMatcher::runOnModule ()
Definition at line 866 of file SampleProfileMatcher.cpp.
References assert(), llvm::buildTopDownFuncOrder(), F, llvm::sampleprof::ProfileConverter::flattenProfile(), llvm::sampleprof::SampleProfileReader::getProfiles(), I, llvm::sampleprof::FunctionSamples::ProfileIsCS, SalvageStaleProfile, SalvageUnusedProfile, and llvm::skipProfileForFunction().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/SampleProfileMatcher.h
lib/Transforms/IPO/SampleProfileMatcher.cpp