LLVM: llvm::PredicateInfoBuilder Class Reference
llvm::PredicateInfoBuilder Class Reference
Public Member Functions
PredicateInfoBuilder (PredicateInfo &PI, Function &F, DominatorTree &DT, AssumptionCache &AC)
void buildPredicateInfo ()
Detailed Description
Definition at line 236 of file PredicateInfo.cpp.
Constructor & Destructor Documentation
PredicateInfoBuilder()
llvm::PredicateInfoBuilder::PredicateInfoBuilder (PredicateInfo & PI, Function & F, DominatorTree & DT, AssumptionCache & AC) inline
Definition at line 281 of file PredicateInfo.cpp.
References F, and llvm::SmallVectorImpl< T >::resize().
Member Function Documentation
buildPredicateInfo()
void llvm::PredicateInfoBuilder::buildPredicateInfo ()
Definition at line 498 of file PredicateInfo.cpp.
References llvm::AssumptionCache::assumptions(), llvm::depth_first(), llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getRootNode(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), II, llvm::BranchInst::isConditional(), llvm::DominatorTree::isReachableFromEntry(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers().
The documentation for this class was generated from the following file:
lib/Transforms/Utils/PredicateInfo.cpp