LLVM: llvm::ArrayRef< T > Class Template Reference
llvm::ArrayRef< T > Class Template Reference
ArrayRef - Represent a constant reference to an array (0 or more elements consecutively in memory), i.e.
#include "llvm/ADT/ArrayRef.h"
Inherited by llvm::MutableArrayRef< T >.
Public Types
using value_type = T
using pointer = value_type *
using const_pointer = const value_type *
using reference = value_type &
using const_reference = const value_type &
using iterator = const_pointer
using const_iterator = const_pointer
using reverse_iterator = std::reverse_iterator<iterator>
using const_reverse_iterator = std::reverse_iterator<const_iterator>
using size_type = size_t
using difference_type = ptrdiff_t
Public Member Functions
Constructors
ArrayRef ()=default
Construct an empty ArrayRef.
ArrayRef (std::nullopt_t)
Construct an empty ArrayRef from std::nullopt.
ArrayRef (const T &OneElt)
Construct an ArrayRef from a single element.
constexpr ArrayRef (const T *data, size_t length)
Construct an ArrayRef from a pointer and length.
constexpr ArrayRef (const T *begin, const T *end)
Construct an ArrayRef from a range.
template<typename U >
ArrayRef (const SmallVectorTemplateCommon< T, U > &Vec)
Construct an ArrayRef from a SmallVector.
template<typename A >
ArrayRef (const std::vector< T, A > &Vec)
Construct an ArrayRef from a std::vector.
template<size_t N>
constexpr ArrayRef (const std::array< T, N > &Arr)
Construct an ArrayRef from a std::array.
template<size_t N>
constexpr ArrayRef (const T(&Arr)[N])
Construct an ArrayRef from a C array.
constexpr ArrayRef (const std::initializer_list< T > &Vec)
Construct an ArrayRef from a std::initializer_list.
template<typename U >
ArrayRef (const ArrayRef< U * > &A, std::enable_if_t< std::is_convertible< U *const *, T const * >::value > *=nullptr)
Construct an ArrayRef<const T*> from ArrayRef<T*>.
template<typename U , typename DummyT >
ArrayRef (const SmallVectorTemplateCommon< U *, DummyT > &Vec, std::enable_if_t< std::is_convertible< U *const *, T const * >::value > *=nullptr)
Construct an ArrayRef<const T*> from a SmallVector<T*>.
template<typename U , typename A >
ArrayRef (const std::vector< U *, A > &Vec, std::enable_if_t< std::is_convertible< U *const *, T const * >::value > *=nullptr)
Construct an ArrayRef<const T*> from std::vector<T*>.
Simple Operations
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
bool empty () const
empty - Check if the array is empty.
const T * data () const
size_t size () const
size - Get the array size.
const T & front () const
front - Get the first element.
const T & back () const
back - Get the last element.
template<typename Allocator >
MutableArrayRef< T > copy (Allocator &A)
bool equals (ArrayRef RHS) const
equals - Check for element-wise equality.
ArrayRef< T > slice (size_t N, size_t M) const
slice(n, m) - Chop off the first N elements of the array, and keep M elements in the array.
ArrayRef< T > slice (size_t N) const
slice(n) - Chop off the first N elements of the array.
ArrayRef< T > drop_front (size_t N=1) const
Drop the first N elements of the array.
ArrayRef< T > drop_back (size_t N=1) const
Drop the last N elements of the array.
template<class PredicateT >
ArrayRef< T > drop_while (PredicateT Pred) const
Return a copy of *this with the first N elements satisfying the given predicate removed.
template<class PredicateT >
ArrayRef< T > drop_until (PredicateT Pred) const
Return a copy of *this with the first N elements not satisfying the given predicate removed.
ArrayRef< T > take_front (size_t N=1) const
Return a copy of *this with only the first N elements.
ArrayRef< T > take_back (size_t N=1) const
Return a copy of *this with only the last N elements.
template<class PredicateT >
ArrayRef< T > take_while (PredicateT Pred) const
Return the first N elements of this Array that satisfy the given predicate.
template<class PredicateT >
ArrayRef< T > take_until (PredicateT Pred) const
Return the first N elements of this Array that don't satisfy the given predicate.
Operator Overloads
const T & operator[] (size_t Index) const
template<typename U >
std::enable_if_t< std::is_same< U, T >::value, ArrayRef< T > > & operator= (U &&Temporary)=delete
Disallow accidental assignment from a temporary.
template<typename U >
std::enable_if_t< std::is_same< U, T >::value, ArrayRef< T > > & operator= (std::initializer_list< U >)=delete
Disallow accidental assignment from a temporary.
Expensive Operations
std::vector< T > vec () const
Conversion operators
operator std::vector< T > () const
Detailed Description
template<typename T>
class llvm::ArrayRef< T >
ArrayRef - Represent a constant reference to an array (0 or more elements consecutively in memory), i.e.
a start pointer and a length. It allows various APIs to take consecutive elements easily and conveniently.
This class does not own the underlying data, it is expected to be used in situations where the data resides in some other buffer, whose lifetime extends past that of the ArrayRef. For this reason, it is not in general safe to store an ArrayRef.
This is intended to be trivially copyable, so it should be passed by value.
Definition at line 25 of file X86ShuffleDecode.h.
Member Typedef Documentation
const_iterator
template<typename T > using llvm::ArrayRef< T >::const_iterator = const_pointer
Definition at line 49 of file ArrayRef.h.
const_pointer
template<typename T > using llvm::ArrayRef< T >::const_pointer = const value_type *
Definition at line 45 of file ArrayRef.h.
const_reference
template<typename T > using llvm::ArrayRef< T >::const_reference = const value_type &
Definition at line 47 of file ArrayRef.h.
const_reverse_iterator
template<typename T > using llvm::ArrayRef< T >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 51 of file ArrayRef.h.
difference_type
template<typename T > using llvm::ArrayRef< T >::difference_type = ptrdiff_t
Definition at line 53 of file ArrayRef.h.
iterator
template<typename T > using llvm::ArrayRef< T >::iterator = const_pointer
Definition at line 48 of file ArrayRef.h.
pointer
template<typename T > using llvm::ArrayRef< T >::pointer = value_type *
Definition at line 44 of file ArrayRef.h.
reference
template<typename T > using llvm::ArrayRef< T >::reference = value_type &
Definition at line 46 of file ArrayRef.h.
reverse_iterator
template<typename T > using llvm::ArrayRef< T >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 50 of file ArrayRef.h.
size_type
template<typename T > using llvm::ArrayRef< T >::size_type = size_t
Definition at line 52 of file ArrayRef.h.
value_type
template<typename T > using llvm::ArrayRef< T >::value_type = T
Definition at line 43 of file ArrayRef.h.
Constructor & Destructor Documentation
ArrayRef() [1/13]
template<typename T > llvm::ArrayRef< T >::ArrayRef () default
Construct an empty ArrayRef.
ArrayRef() [2/13]
template<typename T > llvm::ArrayRef< T >::ArrayRef (std::nullopt_t) inline
Construct an empty ArrayRef from std::nullopt.
Definition at line 70 of file ArrayRef.h.
ArrayRef() [3/13]
template<typename T > llvm::ArrayRef< T >::ArrayRef (const T & OneElt) inline
Construct an ArrayRef from a single element.
Definition at line 73 of file ArrayRef.h.
References llvm::Data, and llvm::Length.
ArrayRef() [4/13]
template<typename T > llvm::ArrayRef< T >::ArrayRef (const T * data, size_t length) inline constexpr
Construct an ArrayRef from a pointer and length.
Definition at line 77 of file ArrayRef.h.
References llvm::Data, and llvm::Length.
ArrayRef() [5/13]
template<typename T > llvm::ArrayRef< T >::ArrayRef (const T * begin, const T * end) inline constexpr
Construct an ArrayRef from a range.
Definition at line 81 of file ArrayRef.h.
References assert(), llvm::Data, and llvm::Length.
ArrayRef() [6/13]
template<typename T > template<typename U > llvm::ArrayRef< T >::ArrayRef (const SmallVectorTemplateCommon< T, U > & Vec) inline
Construct an ArrayRef from a SmallVector.
This is templated in order to avoid instantiating SmallVectorTemplateCommon<T> whenever we copy-construct an ArrayRef.
Definition at line 90 of file ArrayRef.h.
References llvm::Data, and llvm::Length.
ArrayRef() [7/13]
template<typename T > template<typename A > llvm::ArrayRef< T >::ArrayRef (const std::vector< T, A > & Vec) inline
Construct an ArrayRef from a std::vector.
Definition at line 96 of file ArrayRef.h.
References llvm::Data, and llvm::Length.
ArrayRef() [8/13]
template<typename T > template<size_t N> llvm::ArrayRef< T >::ArrayRef (const std::array< T, N > & Arr) inline constexpr
Construct an ArrayRef from a std::array.
Definition at line 101 of file ArrayRef.h.
References llvm::Data, and llvm::Length.
ArrayRef() [9/13]
template<typename T > template<size_t N> llvm::ArrayRef< T >::ArrayRef (const T(&) Arr[N]) inline constexpr
Construct an ArrayRef from a C array.
Definition at line 106 of file ArrayRef.h.
References llvm::Data, and llvm::Length.
ArrayRef() [10/13]
template<typename T > llvm::ArrayRef< T >::ArrayRef (const std::initializer_list< T > & Vec) inline constexpr
Construct an ArrayRef from a std::initializer_list.
Definition at line 116 of file ArrayRef.h.
References llvm::Data, and llvm::Length.
ArrayRef() [11/13]
template<typename T > template<typename U > llvm::ArrayRef< T >::ArrayRef (const ArrayRef< U * > & A, std::enable_if_t< std::is_convertible< U *const *, T const * >::value > * = nullptr) inline
Construct an ArrayRef<const T*> from ArrayRef<T*>.
This uses SFINAE to ensure that only ArrayRefs of pointers can be converted.
Definition at line 126 of file ArrayRef.h.
References llvm::Data, and llvm::Length.
ArrayRef() [12/13]
template<typename T > template<typename U , typename DummyT > llvm::ArrayRef< T >::ArrayRef (const SmallVectorTemplateCommon< U *, DummyT > & Vec, std::enable_if_t< std::is_convertible< U *const *, T const * >::value > * = nullptr) inline
Construct an ArrayRef<const T*> from a SmallVector<T*>.
This is templated in order to avoid instantiating SmallVectorTemplateCommon<T> whenever we copy-construct an ArrayRef.
Definition at line 135 of file ArrayRef.h.
References llvm::Data, and llvm::Length.
ArrayRef() [13/13]
template<typename T > template<typename U , typename A > llvm::ArrayRef< T >::ArrayRef (const std::vector< U *, A > & Vec, std::enable_if_t< std::is_convertible< U *const *, T const * >::value > * = nullptr) inline
Construct an ArrayRef<const T*> from std::vector<T*>.
This uses SFINAE to ensure that only vectors of pointers can be converted.
Definition at line 144 of file ArrayRef.h.
References llvm::Data, and llvm::Length.
Member Function Documentation
back()
template<typename T > const T & llvm::ArrayRef< T >::back () const inline
back - Get the last element.
Definition at line 174 of file ArrayRef.h.
References assert(), llvm::Data, and llvm::Length.
Referenced by llvm::AttributeList::addParamAttribute(), llvm::DIExpression::appendToStack(), llvm::RandomIRBuilder::connectToSink(), llvm::object::ELFFile< ELFT >::dynamicEntries(), llvm::Record::getDirectSuperClasses(), isSwitchDense(), llvm::RandomIRBuilder::newSink(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::orc::shared::runDeallocActions(), simplifyGEPInst(), simplifyInstructionWithOperands(), and llvm::slpvectorizer::BoUpSLP::vectorizeTree().
begin()
template<typename T > iterator llvm::ArrayRef< T >::begin () const inline
Definition at line 153 of file ArrayRef.h.
References llvm::Data.
Referenced by llvm::lto::LTO::add(), llvm::SubtargetFeatures::addFeaturesVector(), addMask(), llvm::DebugLocEntry::addValues(), llvm::DIExpression::append(), llvm::DIExpression::appendOpsToArg(), llvm::DIExpression::appendToStack(), llvm::DominatorTreeBase< NodeT, IsPostDom >::applyUpdates(), llvm::DIExpressionCursor::assignNewExpr(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildBuildVectorTrunc(), llvm::MachineIRBuilder::buildConcatVectors(), buildCopyFromRegs(), buildFixItLine(), llvm::MachineIRBuilder::buildMergeLikeInstr(), llvm::MachineIRBuilder::buildMergeValues(), BuildSubAggregate(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineIRBuilder::buildUnmerge(), llvm::Interpreter::callFunction(), canonicalizeDwarfOperations(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::dwarf_linker::parallel::CompileUnit::cloneDieAttrExpression(), llvm::collectGlobalObjectNameStrings(), combineShuffleOfSplatVal(), combineShuffleToZeroExtendVectorInReg(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::ComputeLinearIndex(), computeMemberData(), llvm::concatenateVectors(), llvm::ConstantRangeListAttributeImpl::ConstantRangeListAttributeImpl(), llvm::sys::UnicodeCharSet::contains(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), llvm::Instruction::copyMetadata(), CreateGCRelocates(), llvm::DeleteDeadBlocks(), llvm::discoverAndMapSubloop(), llvm::Instruction::dropUnknownNonDebugMetadata(), llvm::objcopy::wasm::dumpSectionToFile(), llvm::DIExpression::elements_begin(), llvm::MCDwarfFrameEmitter::Emit(), llvm::BitstreamWriter::emitBlob(), llvm::AAMDNodes::extendToTBAA(), llvm::FindInsertedValue(), llvm::AttributeList::get(), llvm::CondOpInit::get(), llvm::DagInit::get(), llvm::RecordRecTy::get(), llvm::gsym::GsymReader::getAddressOffsetIndex(), getAVX512Node(), llvm::BitcodeModule::getBuffer(), llvm::omp::getCompoundConstruct(), llvm::StructLayout::getElementContainingOffset(), llvm::ConstantExprKeyType::getHash(), llvm::omp::getLeafOrCompositeConstructs(), llvm::SelectionDAG::getNode(), getNoopInput(), llvm::slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), llvm::getShuffleMaskWithWidestElts(), llvm::ConstantExpr::getWithOperands(), llvm::hash_value(), llvm::CallGraphSCC::initialize(), llvm::RegPressureTracker::initLiveThru(), llvm::AppendingBinaryByteStream::insert(), insertCandidatesWithPendingInjections(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), llvm::omp::isCompositeConstruct(), isFixedVectorShuffle(), llvm::LiveRange::isLiveAtIndexes(), isSaveReachableThroughClean(), isSubset(), llvm::libDriverMain(), llvm::coverage::LineCoverageStats::LineCoverageStats(), llvm::coverage::CoverageMapping::load(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), lowerV8I16GeneralSingleInputShuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), llvm::makePostTransformationMetadata(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), mergeVectorRegsToResultRegs(), llvm::object::ExportEntry::moveNext(), llvm::object::MachOBindEntry::moveNext(), llvm::object::MachORebaseEntry::moveNext(), llvm::object::ExportEntry::nodeOffset(), optimizeDwarfOperations(), llvm::CallBase::populateBundleOperandInfos(), ProfileCondOpInit(), ProfileDagInit(), llvm::detail::BCRecordCoding< BCArray< ElementTy > >::read(), llvm::BinaryStreamReader::readCString(), llvm::BinaryStreamReader::readFixedString(), removeUnusedBlocksFromParent(), llvm::LiveIntervals::repairIntervalsInRange(), llvm::SDDbgValue::SDDbgValue(), llvm::MachineFunction::setCallSiteLandingPad(), llvm::X86MachineFunctionInfo::setPreallocatedArgOffsets(), llvm::setProfMetadata(), llvm::gsym::GsymCreator::setUUID(), stackFrameIncludesInlinedCallStack(), llvm::SelectionDAG::UpdateNodeOperands(), UpdatePHINodes(), shuffles::vdealvdd(), llvm::misexpect::verifyMisExpect(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), shuffles::vshuffvdd(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), writeDIE(), and writeToResolutionFile().
copy()
template<typename T > template<typename Allocator > MutableArrayRef< T > llvm::ArrayRef< T >::copy (Allocator & A) inline
Definition at line 180 of file ArrayRef.h.
References A, and llvm::Length.
data()
template<typename T > const T * llvm::ArrayRef< T >::data () const inline
Definition at line 162 of file ArrayRef.h.
References llvm::Data.
Referenced by llvm::codeview::DebugChecksumsSubsection::addChecksum(), analyzeHeader(), llvm::objcopy::elf::SectionTableRef::begin(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneBlockAttr(), llvm::ConstantFoldGetElementPtr(), llvm::StackMapParser< Endianness >::constants_end(), llvm::logicalview::LVBinaryReader::createInstructions(), llvm::codeview::discoverTypeIndices(), llvm::codeview::discoverTypeIndicesInSymbol(), llvm::object::doesXCOFFTracebackTableBegin(), dumpLocationExpr(), llvm::object::ELFFile< ELFT >::dynamicEntries(), eat12Bytes(), eatBytes(), llvm::DwarfDebug::emitDebugLocEntry(), llvm::objcopy::elf::SectionTableRef::end(), llvm::SimpleBitstreamCursor::fillCurWord(), llvm::X86_MC::findX86_64PltEntries(), llvm::X86_MC::findX86PltEntries(), llvm::codeview::forEachCodeViewRecord(), llvm::codeview::detail::GuidAdapter::format(), llvm::fullyRecomputeLiveIns(), llvm::StackMapParser< Endianness >::functions_end(), llvm::ConstantDataArray::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::gsym::GsymReader::getAddrOffsets(), llvm::codeview::getBytesAsCharacters(), llvm::StackMapParser< Endianness >::getConstant(), llvm::object::ResourceSectionRef::getContents(), llvm::object::COFFObjectFile::getDebugPDBInfo(), getExpressionFrameOffset(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantDataVector::getFP(), llvm::StackMapParser< Endianness >::getFunction(), llvm::ConstantExpr::getGetElementPtr(), llvm::DenseMapInfo< ArrayRef< T >, void >::getHashValue(), M68kDisassembler::getInstruction(), getLEB128(), llvm::SimpleBitstreamCursor::getPointerToByte(), llvm::StackMapParser< Endianness >::getRecord(), llvm::object::MachOObjectFile::getSectionFinalSegmentName(), llvm::object::MachOObjectFile::getSectionName(), llvm::object::ResourceSectionRef::getTableEntry(), getUUID(), llvm::MipsTargetLowering::HandleByVal(), llvm::pdb::hashStringV2(), llvm::codeview::CVRecord< Kind >::kind(), llvm::Function::lookupIntrinsicID(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), llvm::codeview::CodeViewRecordIO::mapGuid(), llvm::object::MachOChainedFixupEntry::moveNext(), nextLEB(), llvm::object::MinidumpFile::MemoryInfoIterator::operator*(), llvm::object::MachOBindEntry::operator==(), llvm::object::MachORebaseEntry::operator==(), parseImmediate(), llvm::BinaryStreamReader::readArray(), readBinaryIdsInternal(), llvm::BinaryStreamReader::readInteger(), llvm::BinaryStreamReader::readObject(), llvm::orc::FDSimpleRemoteEPCTransport::sendMessage(), llvm::BinaryByteStream::str(), llvm::codeview::CVRecord< Kind >::str_data(), verifyNoteSection(), llvm::yaml::BinaryRef::writeAsBinary(), llvm::AppendingBinaryByteStream::writeBytes(), llvm::msf::WritableMappedBlockStream::writeBytes(), llvm::MutableBinaryByteStream::writeBytes(), writeWithCommas(), llvm::xxh3_128bits(), and llvm::xxh3_64bits().
drop_back()
template<typename T > ArrayRef< T > llvm::ArrayRef< T >::drop_back (size_t N = 1) const inline
Drop the last N elements of the array.
Definition at line 210 of file ArrayRef.h.
References assert(), N, and size().
Referenced by llvm::DIExpression::appendToStack(), EltsFromConsecutiveLoads(), llvm::Record::getDirectSuperClasses(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::sampleprof::SampleContext::isPrefixOf(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::orc::shared::runDeallocActions(), simplifyGEPInst(), and simplifyInstructionWithOperands().
drop_front()
template<typename T > ArrayRef< T > llvm::ArrayRef< T >::drop_front (size_t N = 1) const inline
Drop the first N elements of the array.
Definition at line 204 of file ArrayRef.h.
References assert(), N, and size().
Referenced by allSameType(), buildCopyFromRegs(), clusterSortPtrAccesses(), combineShuffleToZeroExtendVectorInReg(), computeCommonAlignment(), llvm::codeview::CVRecord< Kind >::content(), llvm::codeview::discoverTypeIndices(), llvm::codeview::discoverTypeIndicesInSymbol(), llvm::codeview::forEachCodeViewRecord(), llvm::CodeViewYAML::detail::UnknownSymbolRecord::fromCodeViewSymbol(), llvm::opt::GenericOptTable::GenericOptTable(), llvm::fuzzerop::gepDescriptor(), llvm::object::COFFObjectFile::getDebugPDBInfo(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::DIExpression::getSingleLocationExpressionElements(), llvm::codeview::GloballyHashedType::hashType(), llvm::orc::lookupSymbolsAsyncHelper(), llvm::object::MinidumpFile::MemoryInfoIterator::operator++(), resolveTypeIndexReferences(), llvm::pdb::typesetItemList(), and writeWithCommas().
drop_until()
template<typename T > template<class PredicateT > ArrayRef< T > llvm::ArrayRef< T >::drop_until (PredicateT Pred) const inline
Return a copy of *this with the first N elements not satisfying the given predicate removed.
Definition at line 223 of file ArrayRef.h.
References llvm::find_if().
drop_while()
template<typename T > template<class PredicateT > ArrayRef< T > llvm::ArrayRef< T >::drop_while (PredicateT Pred) const inline
Return a copy of *this with the first N elements satisfying the given predicate removed.
Definition at line 217 of file ArrayRef.h.
References llvm::find_if_not().
empty()
template<typename T > bool llvm::ArrayRef< T >::empty () const inline
empty - Check if the array is empty.
Definition at line 160 of file ArrayRef.h.
References llvm::Length.
Referenced by llvm::orc::IRSymbolMapper::add(), addBasicBlockMetadata(), llvm::codeview::DebugChecksumsSubsection::addChecksum(), addMask(), llvm::LazyCallGraph::addSplitRefRecursiveFunctions(), llvm::pdb::DbiModuleDescriptorBuilder::addSymbolsInBulk(), llvm::pdb::TpiStreamBuilder::addTypeRecords(), llvm::RegAllocBase::allocatePhysRegs(), llvm::annotateValueSite(), llvm::DIExpression::append(), llvm::DIExpression::appendToStack(), llvm::DominatorTreeBase< NodeT, IsPostDom >::applyUpdates(), llvm::AttributeListImpl::AttributeListImpl(), buildExtractionBlockSet(), buildFixItLine(), llvm::VPlanSlp::buildGraph(), llvm::MachineIRBuilder::buildInstr(), canClobberPhysRegDefs(), canClobberReachingPhysRegUse(), canonicalizeShuffleMaskWithHorizOp(), llvm::cloneAndAdaptNoAliasScopes(), llvm::cloneAndAdaptNoAliasScopes(), llvm::MachineInstr::cloneMergedMemRefs(), llvm::collectGlobalObjectNameStrings(), llvm::CombinationGenerator< choice_type, choices_storage_type, variable_smallsize >::CombinationGenerator(), combineOrders(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), llvm::MDNodeOpsKey::compareOps(), computeCalleeSaveRegisterPairs(), computeExcessPressureDelta(), llvm::ConstantFoldExtractValueInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldInsertValueInstruction(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), llvm::Instruction::copyMetadata(), llvm::coverage::BinaryCoverageReader::create(), llvm::IRBuilderBase::CreateAnd(), llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilderBase::CreateLogicalOr(), llvm::IRBuilderBase::CreateOr(), llvm::OpenMPIRBuilder::createSingle(), llvm::objcopy::deepWriteArchive(), llvm::FileCheckPatternContext::defineCmdlineVariables(), llvm::doesNotNeedToSchedule(), llvm::coverage::CounterMappingContext::dump(), llvm::object::ELFFile< ELFT >::dynamicEntries(), llvm::CodeViewContext::encodeInlineLineTable(), llvm::object::MachOObjectFile::exports(), llvm::FindInsertedValue(), foldCONCAT_VECTORS(), llvm::codeview::forEachCodeViewRecord(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::RecordRecTy::get(), getBuildDwordsVector(), llvm::omp::getCompoundConstruct(), llvm::Intrinsic::getDeclaration(), llvm::Record::getDirectSuperClasses(), getExpressionFrameOffset(), getFeatures(), getIndexedTypeInternal(), getIntrinsicNameImpl(), getMaxCalleeSavedReg(), llvm::MMRAMetadata::getMD(), llvm::DILocation::getMergedLocations(), getOpenFileImpl(), getOrSelfReference(), llvm::object::MachOObjectFile::getSegmentContents(), llvm::slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), llvm::X86TTIImpl::getShuffleCost(), llvm::codeview::VFTableShapeRecord::getSlots(), llvm::Intrinsic::getType(), llvm::DFAPacketizer::getUsedResources(), getUUID(), llvm::CallLowering::handleAssignments(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::ScheduleDAGMILive::initRegPressure(), llvm::MachineInstr::insert(), llvm::LanaiInstrInfo::insertBranch(), insertLifetimeMarkersSurroundingCall(), llvm::codeview::GlobalTypeTableBuilder::insertRecordAs(), insertUseHolderAfter(), llvm::GCNTTIImpl::isInlineAsmSourceOfDivergence(), llvm::ConstantRangeList::isOrderedRanges(), isReverseOrder(), llvm::coverage::LineCoverageStats::LineCoverageStats(), llvm::coverage::CoverageMapping::load(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), llvm::orc::lookupSymbolsAsyncHelper(), llvm::lowerGlobalIFuncUsersAsGlobalCtor(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::X86TargetLowering::lowerInterleavedLoad(), llvm::AArch64CallLowering::lowerReturn(), llvm::AMDGPUCallLowering::lowerReturn(), llvm::ARMCallLowering::lowerReturn(), llvm::BPFCallLowering::lowerReturn(), llvm::M68kCallLowering::lowerReturn(), llvm::MipsCallLowering::lowerReturn(), llvm::PPCCallLowering::lowerReturn(), llvm::RISCVCallLowering::lowerReturn(), llvm::X86CallLowering::lowerReturn(), lowerV8I16GeneralSingleInputShuffle(), llvm::fuzzerop::matchFirstLengthWAnyType(), llvm::fuzzerop::matchFirstType(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), llvm::fuzzerop::matchScalarOfFirstType(), llvm::operator<<(), llvm::raw_ostream::operator<<(), llvm::performOptimizedStructLayout(), postUnswitch(), llvm::DebugCounter::printChunks(), llvm::PrologEpilogSGPRSpillBuilder::PrologEpilogSGPRSpillBuilder(), llvm::promoteCallWithVTableCmp(), llvm::PromoteMemToReg(), llvm::propagateMetadata(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::LazyCallGraph::removeDeadFunctions(), llvm::slpvectorizer::BoUpSLP::reorderTopToBottom(), resolveTypeIndexReferences(), llvm::ARMFrameLowering::restoreCalleeSavedRegisters(), llvm::AVRFrameLowering::restoreCalleeSavedRegisters(), llvm::CSKYFrameLowering::restoreCalleeSavedRegisters(), llvm::MSP430FrameLowering::restoreCalleeSavedRegisters(), llvm::RISCVFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::SIRegisterInfo::restoreSGPR(), llvm::SanitizerBinaryMetadataPass::run(), llvm::orc::shared::runDeallocActions(), llvm::MCJIT::runFunction(), llvm::MachineInstr::setMemRefs(), llvm::SelectionDAG::setNodeMemRefs(), llvm::VFABI::setVectorVariantNames(), llvm::SGPRSpillBuilder::SGPRSpillBuilder(), llvm::RISCVInstrInfo::shouldClusterMemOps(), llvm::SIInstrInfo::shouldClusterMemOps(), simplifyGEPInst(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), llvm::AVRFrameLowering::spillCalleeSavedRegisters(), llvm::CSKYFrameLowering::spillCalleeSavedRegisters(), llvm::LoongArchFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::RISCVFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), llvm::SystemZXPLINKFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::SIRegisterInfo::spillSGPR(), SplitBlockPredecessorsImpl(), llvm::CodeViewYAML::toCodeViewSubsectionList(), toSpvOverloadedIntrinsic(), llvm::pdb::typesetItemList(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), llvm::AppendingBinaryByteStream::writeBytes(), llvm::MutableBinaryByteStream::writeBytes(), and writeWithCommas().
end()
template<typename T > iterator llvm::ArrayRef< T >::end () const inline
Definition at line 154 of file ArrayRef.h.
References llvm::Data, and llvm::Length.
Referenced by llvm::lto::LTO::add(), llvm::SubtargetFeatures::addFeaturesVector(), addMask(), llvm::DebugLocEntry::addValues(), llvm::DIExpression::append(), llvm::DIExpression::appendOpsToArg(), llvm::DIExpression::appendToStack(), llvm::DominatorTreeBase< NodeT, IsPostDom >::applyUpdates(), llvm::DIExpressionCursor::assignNewExpr(), llvm::ELFAttrs::attrTypeAsString(), llvm::ELFAttrs::attrTypeFromString(), llvm::MachineIRBuilder::buildBuildVector(), llvm::MachineIRBuilder::buildBuildVectorTrunc(), llvm::MachineIRBuilder::buildConcatVectors(), buildCopyFromRegs(), buildFixItLine(), llvm::MachineIRBuilder::buildMergeLikeInstr(), llvm::MachineIRBuilder::buildMergeValues(), BuildSubAggregate(), llvm::MachineIRBuilder::buildUnmerge(), llvm::MachineIRBuilder::buildUnmerge(), llvm::Interpreter::callFunction(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::dwarf_linker::parallel::CompileUnit::cloneDieAttrExpression(), llvm::collectGlobalObjectNameStrings(), combineShuffleOfSplatVal(), combineShuffleToZeroExtendVectorInReg(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), CompressEVEXImpl(), llvm::ComputeLinearIndex(), llvm::concatenateVectors(), llvm::ConstantRangeListAttributeImpl::ConstantRangeListAttributeImpl(), llvm::sys::UnicodeCharSet::contains(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), llvm::Instruction::copyMetadata(), CreateGCRelocates(), llvm::DeleteDeadBlocks(), llvm::discoverAndMapSubloop(), llvm::Instruction::dropUnknownNonDebugMetadata(), llvm::objcopy::wasm::dumpSectionToFile(), llvm::DIExpression::elements_end(), llvm::MCDwarfFrameEmitter::Emit(), llvm::BitstreamWriter::emitBlob(), llvm::AAMDNodes::extendToTBAA(), llvm::FindInsertedValue(), findTargetSubtable(), llvm::CondOpInit::get(), llvm::DagInit::get(), llvm::RecordRecTy::get(), llvm::gsym::GsymReader::getAddressOffsetIndex(), getAVX512Node(), llvm::omp::getCompoundConstruct(), llvm::StructLayout::getElementContainingOffset(), getExpressionFrameOffset(), llvm::getFMA3Group(), getGEPCosts(), llvm::ConstantExprKeyType::getHash(), llvm::omp::getLeafOrCompositeConstructs(), getLEB128(), getNewOpcFromTable(), llvm::SelectionDAG::getNode(), getNoopInput(), getRegLanes(), llvm::slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), llvm::getShuffleMaskWithWidestElts(), llvm::ConstantExpr::getWithOperands(), llvm::hash_value(), llvm::pdb::hashStringV1(), llvm::CallGraphSCC::initialize(), llvm::RegPressureTracker::initLiveThru(), llvm::AppendingBinaryByteStream::insert(), insertCandidatesWithPendingInjections(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), llvm::IntrinsicCostAttributes::IntrinsicCostAttributes(), llvm::omp::isCompositeConstruct(), llvm::MCSubtargetInfo::isCPUStringValid(), isFixedVectorShuffle(), llvm::LiveRange::isLiveAtIndexes(), isSaveReachableThroughClean(), isSubset(), llvm::RISCVISAInfo::isSupportedExtensionFeature(), llvm::libDriverMain(), llvm::coverage::LineCoverageStats::LineCoverageStats(), llvm::coverage::CoverageMapping::load(), Lookup(), lookupFoldTableImpl(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), lowerV8I16GeneralSingleInputShuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), llvm::makePostTransformationMetadata(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), mergeVectorRegsToResultRegs(), llvm::object::MachOBindEntry::moveNext(), llvm::object::MachORebaseEntry::moveNext(), llvm::CallBase::populateBundleOperandInfos(), ProfileCondOpInit(), ProfileDagInit(), llvm::detail::BCRecordCoding< BCArray< ElementTy > >::read(), removeUnusedBlocksFromParent(), llvm::LiveIntervals::repairIntervalsInRange(), llvm::SDDbgValue::SDDbgValue(), llvm::MachineFunction::setCallSiteLandingPad(), llvm::X86MachineFunctionInfo::setPreallocatedArgOffsets(), llvm::setProfMetadata(), llvm::gsym::GsymCreator::setUUID(), stackFrameIncludesInlinedCallStack(), llvm::DbgValueHistoryMap::trimLocationRanges(), llvm::SelectionDAG::UpdateNodeOperands(), UpdatePHINodes(), shuffles::vdealvdd(), llvm::misexpect::verifyMisExpect(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), shuffles::vshuffvdd(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), and writeToResolutionFile().
equals()
template<typename T > bool llvm::ArrayRef< T >::equals (ArrayRef< T > RHS) const inline
equals - Check for element-wise equality.
Definition at line 187 of file ArrayRef.h.
References llvm::Length.
Referenced by combineTargetShuffle(), and llvm::operator==().
front()
template<typename T > const T & llvm::ArrayRef< T >::front () const inline
front - Get the first element.
Definition at line 168 of file ArrayRef.h.
References assert(), and llvm::Data.
Referenced by llvm::RegAllocBase::allocatePhysRegs(), allSameType(), buildCopyToRegs(), llvm::CSEMIRBuilder::buildInstr(), canSinkInstructions(), llvm::slpvectorizer::BoUpSLP::canVectorizeLoads(), computeCommonAlignment(), DecodeFixedType(), llvm::objcopy::deepWriteArchive(), llvm::CodeViewContext::encodeInlineLineTable(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), generateNewInstTree(), llvm::MMRAMetadata::getMD(), llvm::DFAPacketizer::getUsedResources(), isFreeConcat(), isSwitchDense(), llvm::coverage::LineCoverageStats::LineCoverageStats(), llvm::coverage::CoverageMapping::load(), llvm::orc::lookupSymbolsAsyncHelper(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), memOpsHaveSameBasePtr(), memOpsHaveSameBasePtr(), MergeCompatibleInvokesImpl(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::detail::BCRecordCoding< ElementTy >::read(), shortBundleName(), llvm::AArch64InstrInfo::shouldClusterMemOps(), llvm::PPCInstrInfo::shouldClusterMemOps(), llvm::RISCVInstrInfo::shouldClusterMemOps(), llvm::SIInstrInfo::shouldClusterMemOps(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), and llvm::widenShuffleMaskElts().
operator std::vector< T >()
template<typename T > llvm::ArrayRef< T >::operator std::vector< T > () const inline
Definition at line 287 of file ArrayRef.h.
operator=() [1/2]
template<typename T > template<typename U > std::enable_if_t< std::is_same< U, T >::value, ArrayRef< T > > & llvm::ArrayRef< T >::operator= (std::initializer_list< U >) delete
Disallow accidental assignment from a temporary.
The declaration here is extra complicated so that "arrayRef = {}" continues to select the move assignment operator.
operator=() [2/2]
template<typename T > template<typename U > std::enable_if_t< std::is_same< U, T >::value, ArrayRef< T > > & llvm::ArrayRef< T >::operator= (U && Temporary) delete
Disallow accidental assignment from a temporary.
The declaration here is extra complicated so that "arrayRef = {}" continues to select the move assignment operator.
Referenced by llvm::OwningArrayRef< T >::operator=().
operator[]()
template<typename T > const T & llvm::ArrayRef< T >::operator[] (size_t Index) const inline
Definition at line 256 of file ArrayRef.h.
References assert(), llvm::Data, Index, and llvm::Length.
rbegin()
template<typename T > reverse_iterator llvm::ArrayRef< T >::rbegin () const inline
Definition at line 156 of file ArrayRef.h.
Referenced by getNoopInput(), llvm::ScheduleDAGMI::initQueues(), rematerializeChain(), and llvm::X86FrameLowering::spillCalleeSavedRegisters().
rend()
template<typename T > reverse_iterator llvm::ArrayRef< T >::rend () const inline
Definition at line 157 of file ArrayRef.h.
Referenced by getNoopInput(), llvm::ScheduleDAGMI::initQueues(), rematerializeChain(), and llvm::X86FrameLowering::spillCalleeSavedRegisters().
size()
template<typename T > size_t llvm::ArrayRef< T >::size () const inline
size - Get the array size.
Definition at line 165 of file ArrayRef.h.
References llvm::Length.
Referenced by llvm::dwarf_linker::parallel::DIEGenerator::addBlockAttribute(), llvm::codeview::DebugChecksumsSubsection::addChecksum(), llvm::dwarf_linker::parallel::DIEGenerator::addLocationAttribute(), llvm::DwarfCompileUnit::addLocationAttribute(), addMask(), addOperands(), llvm::gsym::GsymReader::addressForIndex(), addSaveRestoreRegs(), llvm::pdb::DbiModuleDescriptorBuilder::addSymbolsInBulk(), llvm::pdb::TpiStreamBuilder::addTypeRecords(), llvm::InstrProfRecord::addValueData(), llvm::DbgVariableIntrinsic::addVariableLocationOps(), llvm::DbgVariableRecord::addVariableLocationOps(), llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::adjustExtracts(), llvm::CCState::AllocateReg(), llvm::CCState::AllocateReg(), llvm::CCState::AllocateRegBlock(), allocateSGPR32InputImpl(), allocateVGPR32Input(), allSameBlock(), llvm::analyzeArguments(), analyzeHeader(), llvm::CombinerHelper::applyCombineShuffleVector(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::applyUpdates(), llvm::SimpleBitstreamCursor::AtEndOfStream(), llvm::MachineIRBuilder::buildBuildVectorConstant(), buildClonedLoopBlocks(), buildClonedLoops(), buildCopyFromRegs(), buildCopyToRegs(), buildFatArchList(), llvm::coro::Shape::buildFrom(), llvm::CSEMIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildInstr(), llvm::BuildMI(), llvm::AMDGPULegalizerInfo::buildMultiply(), buildNew(), buildOrChain(), llvm::codelayout::calcExtTspScore(), llvm::codelayout::calcExtTspScore(), llvm::LoopVectorizationCostModel::calculateRegisterUsage(), calculateRtStride(), llvm::Interpreter::callFunction(), canonicalizeDwarfOperations(), canonicalizeShuffleMaskWithHorizOp(), llvm::SimpleBitstreamCursor::canSkipToPos(), llvm::slpvectorizer::BoUpSLP::canVectorizeLoads(), CC_AIX(), CC_ARM_AAPCS_Custom_Aggregate(), checkARM64Instructions(), CheckForLiveRegDefMasked(), checkOperandCount(), llvm::cleanUpTempFiles(), llvm::cloneAndAdaptNoAliasScopes(), llvm::cloneAndAdaptNoAliasScopes(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneBlockAttr(), llvm::MachineInstr::cloneMergedMemRefs(), clusterSortPtrAccesses(), llvm::FunctionComparator::cmpOperations(), coerceArguments(), CollectAddOperandsWithScales(), llvm::collectGlobalObjectNameStrings(), combineConcatVectorOfShuffleAndItsOperands(), combineConcatVectorOps(), combineOrders(), combineShuffleOfSplatVal(), combineShuffleToZeroExtendVectorInReg(), llvm::TargetLowering::DAGCombinerInfo::CombineTo(), combineX86ShuffleChain(), combineX86ShuffleChainWithExtract(), combineX86ShufflesConstants(), combineX86ShufflesRecursively(), CompareSCEVComplexity(), llvm::IRSimilarity::IRSimilarityCandidate::compareStructure(), llvm::codelayout::computeCacheDirectedLayout(), computeCalleeSaveRegisterPairs(), computeExcessPressureDelta(), llvm::codelayout::computeExtTspLayout(), computeIndirectRegIndex(), llvm::SelectionDAG::computeKnownBits(), computeKnownFPClass(), llvm::ComputeMappedEditDistance(), computeMaxPressureDelta(), computeMemberData(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::mca::computeProcResourceMasks(), llvm::concatenateVectors(), llvm::ConstantFoldGetElementPtr(), llvm::ConstraintSystem::ConstraintSystem(), llvm::detail::IEEEFloat::convertToInteger(), llvm::convertUTF16ToUTF8String(), llvm::convertUTF32ToUTF8String(), llvm::AArch64InstrInfo::copyGPRRegTuple(), llvm::GlobalObject::copyMetadata(), llvm::SIInstrInfo::copyPhysReg(), llvm::AArch64InstrInfo::copyPhysRegTuple(), llvm::CallBrInst::Create(), llvm::CallBrInst::Create(), llvm::CallInst::Create(), llvm::GetElementPtrConstantExpr::Create(), llvm::GetElementPtrInst::Create(), llvm::InvokeInst::Create(), llvm::IRBuilderBase::CreateAnd(), createAndCheckVectorTypesForPromotion(), llvm::jitlink::ppc64::createAnonymousPointerJumpStub(), llvm::MDBuilder::createBranchWeights(), CreateGCRelocates(), createIndexMap(), llvm::IRBuilderBase::CreateLogicalOr(), llvm::IRBuilderBase::CreateNAryOp(), llvm::IRBuilderBase::CreateOr(), llvm::createPHIsForSplitLoopExit(), llvm::OpenMPIRBuilder::createReductions(), llvm::OpenMPIRBuilder::createReductionsGPU(), llvm::createSanitizerCtorAndInitFunctions(), llvm::OpenMPIRBuilder::createSections(), llvm::OpenMPIRBuilder::createSingle(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAATypeNode(), createTuple(), createTuple(), LiveDebugValues::DbgValue::DbgValue(), DecodeIITType(), llvm::AMDGPUDisassembler::decodeKernelDescriptor(), llvm::AMDGPUDisassembler::decodeKernelDescriptorDirective(), llvm::AMDGPUDisassembler::decodeLiteralConstant(), llvm::DecodePSHUFBMask(), DecodeRegisterClass(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPERMV3Mask(), llvm::DecodeVPERMVMask(), llvm::DecodeVPPERMMask(), llvm::DeleteDeadBlocks(), llvm::GCNIterativeScheduler::detachSchedule(), llvm::object::doesXCOFFTracebackTableBegin(), dumpLocationExpr(), llvm::dumpRegSetPressure(), llvm::objcopy::coff::dumpSection(), llvm::objcopy::wasm::dumpSectionToFile(), eat12Bytes(), eatBytes(), EltsFromConsecutiveLoads(), llvm::MCDwarfLineTableHeader::Emit(), llvm::BitstreamWriter::emitBlob(), llvm::DwarfDebug::emitDebugLocEntry(), llvm::DwarfDebug::emitDebugLocEntryLocation(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::OpenMPIRBuilder::emitTargetKernel(), llvm::objcopy::elf::SectionTableRef::end(), llvm::coverage::CounterMappingContext::evaluate(), expandSGPRCopy(), llvm::SimpleBitstreamCursor::fillCurWord(), findBestNonTrivialUnswitchCandidate(), llvm::FindInsertedValue(), findLiveReferences(), llvm::wholeprogramdevirt::findLowestOffset(), FindSequence(), llvm::lto::findThinLTOModule(), llvm::X86_MC::findX86_64PltEntries(), llvm::X86_MC::findX86PltEntries(), fixupOrderingIndices(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), FoldBUILD_VECTOR(), foldCONCAT_VECTORS(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::SelectionDAG::foldConstantFPMath(), foldInlineAsmMemOperand(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::AArch64InstrInfo::foldMemoryOperandImpl(), llvm::RISCVInstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::X86InstrInfo::foldMemoryOperandImpl(), foldSwitchToSelect(), llvm::InstCombinerImpl::foldVectorBinop(), llvm::codeview::forEachCodeViewRecord(), llvm::codeview::detail::GuidAdapter::format(), formSplatFromShuffles(), llvm::CodeViewYAML::fromDebugH(), llvm::fullyRecomputeLiveIns(), llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::gather(), generateNewInstTree(), llvm::Attribute::get(), llvm::AttributeList::get(), llvm::AttributeList::get(), llvm::CondOpInit::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::ConstantDataVector::get(), llvm::DagInit::get(), llvm::TargetExtType::get(), llvm::gsym::GsymReader::getAddressInfoOffset(), llvm::gsym::GsymReader::getAddrOffsets(), llvm::RecordKeeper::getAllDerivedDefinitions(), getAltInstrMask(), llvm::getBitcodeFileContents(), llvm::BitcodeModule::getBuffer(), getBuildDwordsVector(), llvm::codeview::getBytesAsCharacters(), llvm::irsymtab::Reader::getComdatTable(), llvm::object::ResourceSectionRef::getContents(), llvm::objcopy::elf::SRecord::getCount(), llvm::object::COFFObjectFile::getDebugPDBInfo(), llvm::irsymtab::Reader::getDependentLibraries(), llvm::getDescImpl(), llvm::object::ELFFile< ELFT >::getEntry(), llvm::codeview::VFTableShapeRecord::getEntryCount(), getExpressionFrameOffset(), llvm::MachineFunction::getFilterIDFor(), llvm::CCState::getFirstUnallocated(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataArray::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantDataVector::getFP(), llvm::ConstantDataVector::getFP(), llvm::SelectionDAG::getGatherVP(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getGetElementPtr(), getHalfShuffleMask(), llvm::AArch64Disassembler::getInstruction(), llvm::AMDGPUDisassembler::getInstruction(), llvm::BasicTTIImplBase< T >::getInterleavedMemoryOpCost(), llvm::HexagonTTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCostAVX512(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), getLEB128(), llvm::BinaryByteStream::getLength(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedHistogram(), llvm::SelectionDAG::getMaskedScatter(), getMaxCalleeSavedReg(), llvm::MMRAMetadata::getMD(), llvm::DILocation::getMergedLocations(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), getNoopInput(), llvm::irsymtab::Reader::getNumModules(), llvm::opt::OptTable::getNumOptions(), getOpenFileImpl(), llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead(), llvm::AllocationOrder::getOrderLimitEnd(), getOrSelfReference(), getOutputSegmentMap(), llvm::HvxSelector::getPerfectCompletions(), llvm::MachineTraceMetrics::Trace::getResourceDepth(), llvm::MachineTraceMetrics::Trace::getResourceLength(), getSameOpcode(), llvm::SelectionDAG::getScatterVP(), llvm::object::WasmObjectFile::getSectionSize(), llvm::getShuffleMaskWithWidestElts(), llvm::objcopy::elf::SRecord::getSize(), getStatepointArgs(), getStatepointBundles(), llvm::RegPressureTracker::getUpwardPressureDelta(), getUUID(), llvm::SelectionDAG::getVTList(), llvm::ConstantExpr::getWithOperands(), llvm::CodeViewYAML::GlobalHash::GlobalHash(), llvm::MipsTargetLowering::HandleByVal(), llvm::Record::hasDirectSuperClass(), llvm::pdb::hashStringV2(), llvm::hasUTF16ByteOrderMark(), hasUTF8ByteOrderMark(), shuffles::hi(), IncomingValuesAreCompatible(), llvm::MachineInstr::insert(), llvm::LanaiInstrInfo::insertBranch(), insertCandidatesWithPendingInjections(), llvm::insertMultibyteShift(), llvm::CallLowering::insertSRetLoads(), llvm::CallLowering::insertSRetStores(), interleaveVectors(), llvm::inversePermutation(), llvm::GCNTTIImpl::isAlwaysUniform(), llvm::sampleprof::SampleContext::isBaseContext(), isBigEndian(), llvm::omp::isCompositeConstruct(), isFixedVectorShuffle(), isFreeConcat(), llvm::GCNTTIImpl::isInlineAsmSourceOfDivergence(), llvm::slpvectorizer::BoUpSLP::isLoadCombineCandidate(), llvm::ConstantRangeList::isOrderedRanges(), isReplicationMaskWithParams(), isReverseOrder(), isShuffleEquivalent(), llvm::SimpleBitstreamCursor::isSizePlausible(), isStrictSubset(), isSubset(), isSwitchDense(), isTargetShuffleEquivalent(), llvm::SelectionDAG::isUndef(), llvm::codeview::CVRecord< Kind >::kind(), llvm::BinaryItemTraits< codeview::CVSymbol >::length(), llvm::codeview::CVRecord< Kind >::length(), llvm::codeview::limitSymbolArrayToScope(), llvm::coverage::LineCoverageStats::LineCoverageStats(), shuffles::lo(), llvm::coverage::CoverageMapping::load(), llvm::object::ResourceSectionRef::load(), lowerBitreverseShuffle(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::lowerGlobalIFuncUsersAsGlobalCtor(), llvm::InlineAsmLowering::lowerInlineAsm(), llvm::AArch64TargetLowering::lowerInterleavedLoad(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::RISCVTargetLowering::lowerInterleavedLoad(), llvm::X86TargetLowering::lowerInterleavedLoad(), llvm::AArch64CallLowering::lowerReturn(), llvm::SPIRVCallLowering::lowerReturn(), lowerV16I8Shuffle(), lowerV8I16GeneralSingleInputShuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), llvm::SystemZTargetLowering::makeExternalCall(), llvm::TargetLowering::makeLibCall(), llvm::codeview::CodeViewRecordIO::mapByteVectorTail(), llvm::Intrinsic::matchIntrinsicVarArg(), llvm::fuzzerop::matchSecondType(), llvm::SIInstrInfo::materializeImmediate(), memOpsHaveSameBaseOperands(), llvm::object::MinidumpFile::MemoryInfoIterator::MemoryInfoIterator(), MergeCompatibleInvokes(), MergeCompatibleInvokesImpl(), mergeVectorRegsToResultRegs(), llvm::object::MachOChainedFixupEntry::moveNext(), multikeySort(), nextByte(), nextLEB(), llvm::object::MinidumpFile::MemoryInfoIterator::operator*(), llvm::sampleprof::SampleContext::operator<(), llvm::ConstantExprKeyType::operator==(), llvm::object::MinidumpFile::MemoryInfoIterator::operator==(), optimizeDwarfOperations(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), packSegmentMask(), llvm::ELFAttributeParser::parse(), llvm::object::DirectX::PSVRuntimeInfo::parse(), parseImmediate(), llvm::ELFAttributeParser::parseStringAttribute(), peek(), llvm::AsmLexer::peekTokens(), performBlockTailMerging(), llvm::performOptimizedStructLayout(), llvm::prepareTempFiles(), llvm::BitcodeAnalyzer::printStats(), llvm::processShuffleMasks(), llvm::AttributeImpl::Profile(), ProfileCondOpInit(), ProfileRecordRecTy(), llvm::PrologEpilogSGPRSpillBuilder::PrologEpilogSGPRSpillBuilder(), llvm::propagateMetadata(), llvm::coverage::RawCoverageMappingReader::read(), llvm::detail::BCRecordCoding< ElementTy >::read(), llvm::detail::BCRecordCoding< ElementTy >::read(), readBinaryIdsInternal(), llvm::AppendingBinaryByteStream::readBytes(), llvm::BinaryStreamReader::readCString(), llvm::BinaryStreamReader::readFixedString(), readInstruction16(), readInstruction16(), readInstruction16(), readInstruction24(), readInstruction32(), readInstruction32(), readInstruction32(), readInstruction32(), readInstruction32(), readInstruction64(), readInstruction64(), llvm::BinaryStreamReader::readLongestContiguousChunk(), llvm::BinaryStreamRef::readLongestContiguousChunk(), llvm::readWideAPInt(), rebuildLoopAfterUnswitch(), llvm::BuildVectorSDNode::recastRawBits(), llvm::recognizeBSwapOrBitReverseIdiom(), recomputeLiveInValues(), llvm::Attributor::registerFunctionSignatureRewrite(), llvm::jitlink::relaxBlock(), relocationViaAlloca(), llvm::slpvectorizer::BoUpSLP::reorderBottomToTop(), llvm::slpvectorizer::BoUpSLP::reorderTopToBottom(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), llvm::HvxSelector::rotationDistance(), llvm::Interpreter::runFunction(), llvm::MCJIT::runFunction(), llvm::IRTranslator::runOnMachineFunction(), SelectOpcodeFromVT(), llvm::orc::FDSimpleRemoteEPCTransport::sendMessage(), LiveDebugValues::DbgValue::setDbgOpIDs(), llvm::jitlink::Block::setMutableContent(), llvm::SelectionDAG::setNodeMemRefs(), llvm::SGPRSpillBuilder::SGPRSpillBuilder(), shortBundleName(), llvm::AArch64InstrInfo::shouldClusterMemOps(), llvm::PPCInstrInfo::shouldClusterMemOps(), simplifyExtractValueInst(), simplifyGEPInst(), llvm::simplifyInstructionWithOperands(), simplifyInstructionWithOperands(), llvm::mca::SourceMgr::size(), llvm::objcopy::elf::SectionTableRef::size(), llvm::SimpleBitstreamCursor::SizeInBytes(), llvm::SimpleBitstreamCursor::skipToEnd(), llvm::sortPtrAccesses(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::XtensaFrameLowering::spillCalleeSavedRegisters(), llvm::SIRegisterInfo::spillSGPR(), splitGlobal(), splitMask(), llvm::BinaryByteStream::str(), llvm::codeview::CVRecord< Kind >::str_data(), StrengthenNoWrapFlags(), llvm::ARMBaseInstrInfo::SubsumesPredicate(), llvm::PPCInstrInfo::SubsumesPredicate(), llvm::SuffixTree::SuffixTree(), llvm::OpenMPIRBuilder::tileLoops(), llvm::objcopy::macho::MachOWriter::totalSize(), llvm::ConstantRangeListAttributeImpl::totalSizeToAlloc(), llvm::mca::RegisterFile::tryEliminateMoveOrSwap(), llvm::pdb::typesetItemList(), unswitchNontrivialInvariants(), UpdateAnalysisInformation(), llvm::SelectionDAG::UpdateNodeOperands(), UpdatePHINodes(), llvm::StackMapParser< Endianness >::validateHeader(), shuffles::vdeal(), shuffles::vdealb4w(), shuffles::vdealvdd(), llvm::misexpect::verifyMisExpect(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), llvm::logicalview::LVLogicalVisitor::visitKnownRecord(), shuffles::vpack(), shuffles::vshuff(), shuffles::vshuffvdd(), llvm::WebAssembly::wasmSymbolSetType(), llvm::widenShuffleMaskElts(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), llvm::coverage::CoverageFilenamesSectionWriter::write(), llvm::coverage::CoverageMappingWriter::write(), llvm::write(), llvm::writeArchiveToStream(), llvm::yaml::BinaryRef::writeAsBinary(), llvm::AppendingBinaryByteStream::writeBytes(), llvm::BinaryStreamWriter::writeBytes(), llvm::msf::WritableMappedBlockStream::writeBytes(), llvm::MutableBinaryByteStream::writeBytes(), writeDIE(), llvm::writeIndex(), llvm::orc::writeMachOStruct(), writeSymbolMap(), writeUniversalArchsToStream(), llvm::object::writeUniversalBinaryToStream(), writeWithCommas(), llvm::xxh3_128bits(), and llvm::xxh3_64bits().
slice() [1/2]
template<typename T > ArrayRef< T > llvm::ArrayRef< T >::slice (size_t N) const inline
slice(n) - Chop off the first N elements of the array.
Definition at line 201 of file ArrayRef.h.
References N, size(), and llvm::ArrayRef< T >::slice().
Referenced by llvm::ArrayRef< T >::slice().
slice() [2/2]
template<typename T > ArrayRef< T > llvm::ArrayRef< T >::slice (size_t N, size_t M) const inline
slice(n, m) - Chop off the first N elements of the array, and keep M elements in the array.
Definition at line 195 of file ArrayRef.h.
References assert(), N, and size().
Referenced by buildNew(), llvm::slpvectorizer::BoUpSLP::canVectorizeLoads(), llvm::MachineInstr::cloneMergedMemRefs(), llvm::ConstantFoldExtractValueInstruction(), llvm::ConstantFoldInsertValueInstruction(), llvm::ConstantExprKeyType::create(), DecodeFixedType(), llvm::dlltoolDriverMain(), eat12Bytes(), eatBytes(), llvm::SIFrameLowering::emitEntryFunctionPrologue(), llvm::FindInsertedValue(), llvm::wholeprogramdevirt::findLowestOffset(), llvm::ConstantExpr::getAsInstruction(), llvm::getBitcodeFileContents(), getIndexedTypeInternal(), llvm::AMDGPUDisassembler::getInstruction(), llvm::object::MinidumpFile::getRawStream(), llvm::jitlink::Symbol::getSymbolContent(), llvm::ConstantExpr::getWithOperands(), llvm::pdb::hashStringV2(), llvm::codeview::GloballyHashedType::hashType(), isHorizontalBinOp(), llvm::libDriverMain(), LowerAVXCONCAT_VECTORS(), LowerCONCAT_VECTORSvXi1(), llvm::MCInstPrinter::matchAliasPatterns(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), llvm::AppendingBinaryByteStream::readBytes(), llvm::BinaryByteStream::readBytes(), llvm::msf::MappedBlockStream::readBytes(), llvm::AppendingBinaryByteStream::readLongestContiguousChunk(), llvm::BinaryByteStream::readLongestContiguousChunk(), llvm::BinaryStreamRef::readLongestContiguousChunk(), llvm::jitlink::relaxBlock(), llvm::Interpreter::runFunction(), simplifyExtractValueInst(), upgradeIntrinsicFunction1(), and llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit().
take_back()
template<typename T > ArrayRef< T > llvm::ArrayRef< T >::take_back (size_t N = 1) const inline
Return a copy of *this with only the last N elements.
Definition at line 235 of file ArrayRef.h.
References N, and size().
Referenced by shuffles::hi().
take_front()
template<typename T > ArrayRef< T > llvm::ArrayRef< T >::take_front (size_t N = 1) const inline
Return a copy of *this with only the first N elements.
Definition at line 228 of file ArrayRef.h.
References N, and size().
Referenced by buildCopyFromRegs(), llvm::codeview::forEachCodeViewRecord(), llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::gather(), llvm::AttributeList::get(), llvm::codeview::GloballyHashedType::hashType(), llvm::sampleprof::SampleContext::isPrefixOf(), shuffles::lo(), llvm::BinaryItemStream< T, Traits >::readBytes(), llvm::pdb::typesetItemList(), and writeWithCommas().
take_until()
template<typename T > template<class PredicateT > ArrayRef< T > llvm::ArrayRef< T >::take_until (PredicateT Pred) const inline
Return the first N elements of this Array that don't satisfy the given predicate.
Definition at line 249 of file ArrayRef.h.
References llvm::find_if().
take_while()
template<typename T > template<class PredicateT > ArrayRef< T > llvm::ArrayRef< T >::take_while (PredicateT Pred) const inline
Return the first N elements of this Array that satisfy the given predicate.
Definition at line 243 of file ArrayRef.h.
References llvm::find_if_not().
vec()
template<typename T > std::vector< T > llvm::ArrayRef< T >::vec () const inline
Definition at line 280 of file ArrayRef.h.
References llvm::Data, and llvm::Length.
Referenced by combineDIExpressions().
The documentation for this class was generated from the following files:
include/llvm/ADT/APInt.h
include/llvm/ADT/ArrayRef.h
include/llvm/ADT/SmallVector.h
include/llvm/Analysis/ConstantFolding.h
include/llvm/Analysis/DependenceAnalysis.h
include/llvm/Analysis/InstructionSimplify.h
include/llvm/Analysis/TargetLibraryInfo.h
include/llvm/Analysis/VectorUtils.h
include/llvm/CodeGen/LiveDebugVariables.h
include/llvm/CodeGen/LivePhysRegs.h
include/llvm/CodeGen/MachineInstr.h
include/llvm/CodeGen/ScheduleDFS.h
include/llvm/DebugInfo/CodeView/CodeViewRecordIO.h
include/llvm/IR/ConstantFold.h
include/llvm/IR/LegacyPassManagers.h
include/llvm/IR/MDBuilder.h
include/llvm/IR/MemoryModelRelaxationAnnotations.h
include/llvm/IR/ReplaceConstant.h
include/llvm/IR/User.h
include/llvm/LTO/legacy/LTOCodeGenerator.h
include/llvm/MC/MCDisassembler/MCDisassembler.h
include/llvm/MC/MCDwarf.h
include/llvm/MC/MCSchedule.h
include/llvm/Object/COFF.h
include/llvm/Support/ConvertUTF.h
include/llvm/Support/CRC.h
include/llvm/Support/MD5.h
include/llvm/Support/Process.h
include/llvm/Support/SHA1.h
include/llvm/Support/SHA256.h
include/llvm/Support/SipHash.h
include/llvm/ToolDrivers/llvm-dlltool/DlltoolDriver.h
include/llvm/ToolDrivers/llvm-lib/LibDriver.h
include/llvm/Transforms/IPO/WholeProgramDevirt.h
include/llvm/Transforms/Utils/CallPromotionUtils.h
include/llvm/Transforms/Utils/LoopVersioning.h
include/llvm/Transforms/Utils/ModuleUtils.h
include/llvm/Transforms/Utils/PromoteMemToReg.h
lib/Bitcode/Reader/MetadataLoader.h
lib/TableGen/TGLexer.h
lib/Target/Mips/MCTargetDesc/MipsABIInfo.h
lib/Target/X86/GISel/X86CallLowering.h
lib/Target/X86/MCTargetDesc/X86ShuffleDecode.h