LLVM: llvm::LoopVectorizationPlanner Class Reference
llvm::LoopVectorizationPlanner Class Reference
Planner drives the vectorization process after having passed Legality checks.
#include "Transforms/Vectorize/LoopVectorizationPlanner.h"
Public Member Functions
LoopVectorizationPlanner (Loop *L, LoopInfo *LI, DominatorTree *DT, const TargetLibraryInfo *TLI, const TargetTransformInfo &TTI, LoopVectorizationLegality *Legal, LoopVectorizationCostModel &CM, InterleavedAccessInfo &IAI, PredicatedScalarEvolution &PSE, const LoopVectorizeHints &Hints, OptimizationRemarkEmitter *ORE)
std::optional< VectorizationFactor > plan (ElementCount UserVF, unsigned UserIC)
Plan how to best vectorize, return the best VF and its cost, or std::nullopt if vectorization and interleaving should be avoided up front.
VectorizationFactor planInVPlanNativePath (ElementCount UserVF)
Use the VPlan-native path to plan how to best vectorize, return the best VF and its cost.
VPlan & getBestPlanFor (ElementCount VF) const
Return the best VPlan for VF.
VPlan & getBestPlan () const
Return the most profitable plan and fix its VF to the most profitable one.
std::pair< DenseMap< const SCEV *, Value * >, DenseMap< const RecurrenceDescriptor *, Value * > > executePlan (ElementCount VF, unsigned UF, VPlan &BestPlan, InnerLoopVectorizer &LB, DominatorTree *DT, bool IsEpilogueVectorization, const DenseMap< const SCEV *, Value * > *ExpandedSCEVs=nullptr)
Generate the IR code for the vectorized loop captured in VPlan BestPlan according to the best selected VF and UF.
void printPlans (raw_ostream &O)
bool hasPlanWithVF (ElementCount VF) const
Look through the existing plans and return true if we have one with vectorization factor VF.
VectorizationFactor selectEpilogueVectorizationFactor (const ElementCount MaxVF, unsigned IC)
Static Public Member Functions
static bool getDecisionAndClampRange (const std::function< bool(ElementCount)> &Predicate, VFRange &Range)
Test a Predicate on a Range of VF's.
Protected Member Functions
void buildVPlans (ElementCount MinVF, ElementCount MaxVF)
Build VPlans for power-of-2 VF's between MinVF and MaxVF inclusive, according to the information gathered by Legal when it checked if it is legal to vectorize the loop.
Detailed Description
Planner drives the vectorization process after having passed Legality checks.
Definition at line 298 of file LoopVectorizationPlanner.h.
Constructor & Destructor Documentation
LoopVectorizationPlanner()
llvm::LoopVectorizationPlanner::LoopVectorizationPlanner (Loop * L, LoopInfo * LI, DominatorTree * DT, const TargetLibraryInfo * TLI, const TargetTransformInfo & TTI, LoopVectorizationLegality * Legal, LoopVectorizationCostModel & CM, InterleavedAccessInfo & IAI, PredicatedScalarEvolution & PSE, const LoopVectorizeHints & Hints, OptimizationRemarkEmitter * ORE) inline
Definition at line 348 of file LoopVectorizationPlanner.h.
References llvm::IRSimilarity::Legal.
Member Function Documentation
buildVPlans()
void LoopVectorizationPlanner::buildVPlans (ElementCount MinVF, ElementCount MaxVF) protected
Build VPlans for power-of-2 VF's between MinVF and MaxVF inclusive, according to the information gathered by Legal when it checked if it is legal to vectorize the loop.
Build VPlans for the full range of feasible VF's = {MinVF, 2 * MinVF, 4 * MinVF, ..., MaxVF} by repeatedly building a VPlan for a sub-range of VF's starting at a given VF and extending it as much as possible.
Each vectorization decision can potentially shorten this sub-range during buildVPlan().
Definition at line 7733 of file LoopVectorize.cpp.
References llvm::VFRange::End, and llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::isKnownLT().
Referenced by planInVPlanNativePath().
executePlan()
std::pair< DenseMap< const SCEV *, Value * >, DenseMap< const RecurrenceDescriptor *, Value * > > LoopVectorizationPlanner::executePlan (ElementCount VF, unsigned UF, VPlan & BestPlan, InnerLoopVectorizer & LB, DominatorTree * DT, bool IsEpilogueVectorization, const DenseMap< const SCEV *, Value * > * ExpandedSCEVs = nullptr)
Generate the IR code for the vectorized loop captured in VPlan BestPlan according to the best selected VF and UF.
TODO: IsEpilogueVectorization is needed to avoid issues due to epilogue vectorization re-using plans for both the main and epilogue vector loops. It should be removed once the re-use issue has been fixed. ExpandedSCEVs is passed during execution of the plan for epilogue loop to re-use expansion results generated during main plan execution.
Returns a mapping of SCEVs to their expanded IR values and a mapping for the reduction resume values. Note that this is a temporary workaround needed due to the current epilogue handling.
Definition at line 7274 of file LoopVectorize.cpp.
References AddRuntimeUnrollDisableMetaData(), assert(), llvm::InnerLoopVectorizer::Builder, llvm::cast(), createAndCollectMergePhiForReduction(), llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::dbgs(), llvm::VPlan::dump(), llvm::dyn_cast(), llvm::SmallVectorBase< Size_T >::empty(), llvm::VPBasicBlock::empty(), llvm::VPBasicBlock::execute(), llvm::VPlan::execute(), llvm::InnerLoopVectorizer::fixVectorizedLoop(), llvm::RuntimePointerChecking::getChecks(), llvm::BasicBlock::getContext(), llvm::RuntimePointerChecking::getDiffChecks(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopVectorizationLegality::getLAI(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::Loop::getLoopID(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::InnerLoopVectorizer::getOrCreateVectorTripCount(), llvm::VPlan::getPreheader(), llvm::LoopAccessInfo::getRuntimePointerChecking(), llvm::PredicatedScalarEvolution::getSE(), llvm::VPBlockBase::getSingleSuccessor(), llvm::BasicBlock::getTerminator(), llvm::InnerLoopVectorizer::getTripCount(), llvm::VPlan::getTripCount(), llvm::TargetTransformInfo::getUnrollingPreferences(), llvm::VPlan::getVectorLoopRegion(), llvm::hasBranchWeightMD(), llvm::VPlan::hasUF(), llvm::VPlan::hasVF(), llvm::InnerLoopVectorizer::Legal, LLVM_DEBUG, LLVMLoopVectorizeFollowupAll, LLVMLoopVectorizeFollowupVectorized, llvm::makeFollowupLoopID(), llvm::VPlanTransforms::optimizeForVFAndUF(), llvm::VPlan::prepareToExecute(), llvm::InnerLoopVectorizer::printDebugTracesAtEnd(), llvm::InnerLoopVectorizer::printDebugTracesAtStart(), llvm::LoopVectorizeHints::setAlreadyVectorized(), llvm::setBranchWeights(), llvm::VPlan::setName(), llvm::InnerLoopVectorizer::setTripCount(), llvm::TargetTransformInfo::UnrollingPreferences::UnrollVectorizedLoop, and llvm::DominatorTreeBase< NodeT, IsPostDom >::verify().
Referenced by llvm::LoopVectorizePass::processLoop(), and processLoopInVPlanNativePath().
getBestPlan()
VPlan & LoopVectorizationPlanner::getBestPlan () const
Return the most profitable plan and fix its VF to the most profitable one.
Definition at line 7111 of file LoopVectorize.cpp.
References assert(), llvm::VectorizationFactor::Cost, llvm::dbgs(), llvm::LoopVectorizationCostModel::expectedCost(), llvm::LoopVectorizeHints::FK_Enabled, llvm::ElementCount::getFixed(), llvm::LoopVectorizeHints::getForce(), llvm::InstructionCost::getMax(), hasPlanWithVF(), llvm::ElementCount::isScalar(), LLVM_DEBUG, P, llvm::VPlan::setVF(), llvm::VPlan::vectorFactors(), llvm::VectorizationFactor::Width, and willGenerateVectors().
Referenced by llvm::LoopVectorizePass::processLoop().
getBestPlanFor()
VPlan & LoopVectorizationPlanner::getBestPlanFor (ElementCount VF) const
Return the best VPlan for VF.
Definition at line 7158 of file LoopVectorize.cpp.
References assert(), llvm::count_if(), and llvm_unreachable.
Referenced by llvm::LoopVectorizePass::processLoop(), and processLoopInVPlanNativePath().
getDecisionAndClampRange()
bool LoopVectorizationPlanner::getDecisionAndClampRange (const std::function< bool(ElementCount)> & Predicate, VFRange & Range) static
Test a Predicate on a Range of VF's.
Return the value of applying Predicate on Range.Start, possibly decreasing Range.End such that the returned value holds for the entire Range.
Definition at line 7714 of file LoopVectorize.cpp.
References assert(), and Range.
Referenced by llvm::VPRecipeBuilder::handleReplication(), and llvm::VPRecipeBuilder::tryToCreateWidenRecipe().
hasPlanWithVF()
bool llvm::LoopVectorizationPlanner::hasPlanWithVF (ElementCount VF) const inline
Look through the existing plans and return true if we have one with vectorization factor VF.
Definition at line 396 of file LoopVectorizationPlanner.h.
References llvm::any_of().
Referenced by getBestPlan(), plan(), and selectEpilogueVectorizationFactor().
plan()
std::optional< VectorizationFactor > LoopVectorizationPlanner::plan (ElementCount UserVF, unsigned UserIC)
Plan how to best vectorize, return the best VF and its cost, or std::nullopt if vectorization and interleaving should be avoided up front.
Definition at line 6857 of file LoopVectorize.cpp.
References llvm::all_of(), assert(), llvm::LoopVectorizationCostModel::blockNeedsPredicationForAnyReason(), llvm::LoopVectorizationCostModel::collectElementTypesForWidening(), llvm::LoopVectorizationCostModel::collectInLoopReductions(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), llvm::LoopVectorizationCostModel::collectUniformsAndScalars(), llvm::LoopVectorizationCostModel::collectValuesToIgnore(), llvm::LoopVectorizationCostModel::computeMaxVF(), llvm::dbgs(), llvm::VectorizationFactor::Disabled(), llvm::FixedScalableVFPair::FixedVF, llvm::LoopVectorizationCostModel::foldTailByMasking(), llvm::ElementCount::getFixed(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::ElementCount::getScalable(), hasPlanWithVF(), llvm::LoopVectorizationCostModel::InterleaveInfo, llvm::LoopVectorizationCostModel::invalidateCostModelingDecisions(), llvm::InterleavedAccessInfo::invalidateGroups(), llvm::LoopBase< BlockT, LoopT >::isInnermost(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::isKnownLE(), llvm::isPowerOf2_32(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), llvm::ElementCount::isScalar(), llvm::ElementCount::isVector(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isZero(), LLVM_DEBUG, P, llvm::LoopVectorizationLegality::prepareToFoldTailByMasking(), printPlans(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::reportVectorizationInfo(), llvm::FixedScalableVFPair::ScalableVF, llvm::VectorizationFactor::ScalarCost, llvm::LoopVectorizationCostModel::selectUserVectorizationFactor(), useMaskedInterleavedAccesses(), and llvm::VectorizationFactor::Width.
Referenced by llvm::LoopVectorizePass::processLoop().
planInVPlanNativePath()
VectorizationFactor LoopVectorizationPlanner::planInVPlanNativePath (ElementCount UserVF)
Use the VPlan-native path to plan how to best vectorize, return the best VF and its cost.
Definition at line 6805 of file LoopVectorize.cpp.
References assert(), buildVPlans(), llvm::dbgs(), determineVPlanVF(), llvm::VectorizationFactor::Disabled(), llvm::EnableVPlanNativePath, ForceTargetSupportsScalableVectors, llvm::ElementCount::getFixed(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::LoopBase< BlockT, LoopT >::isInnermost(), llvm::isPowerOf2_32(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), llvm::ElementCount::isScalar(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isZero(), LLVM_DEBUG, llvm::reportVectorizationFailure(), llvm::TargetTransformInfo::supportsScalableVectors(), and VPlanBuildStressTest.
Referenced by processLoopInVPlanNativePath().
printPlans()
void LoopVectorizationPlanner::printPlans (raw_ostream & O)
Definition at line 7416 of file LoopVectorize.cpp.
References llvm::VPlan::print(), llvm::VPlan::printDOT(), and PrintVPlansInDotFormat.
Referenced by plan().
selectEpilogueVectorizationFactor()
VectorizationFactor LoopVectorizationPlanner::selectEpilogueVectorizationFactor (const ElementCount MaxVF, unsigned IC)
Returns
The most profitable vectorization factor and the cost of that VF for vectorizing the epilogue. Returns VectorizationFactor::Disabled if epilogue vectorization is not supported for the loop.
Definition at line 4652 of file LoopVectorize.cpp.
References llvm::createTripCountSCEV(), llvm::dbgs(), llvm::VectorizationFactor::Disabled(), EnableEpilogueVectorization, EpilogueVectorizationForceVF, llvm::ScalarEvolution::getConstant(), llvm::ElementCount::getFixed(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::BasicBlock::getParent(), llvm::PredicatedScalarEvolution::getSE(), llvm::ScalarEvolution::getURemExpr(), getVScaleForTuning(), llvm::LoopVectorizationLegality::getWidestInductionType(), llvm::Function::hasMinSize(), llvm::Function::hasOptSize(), hasPlanWithVF(), llvm::CmpInst::ICMP_UGT, llvm::LoopVectorizationCostModel::isEpilogueVectorizationProfitable(), llvm::details::FixedOrScalableQuantity< ElementCount, unsigned >::isKnownGE(), llvm::ScalarEvolution::isKnownPredicate(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), llvm::LoopVectorizationCostModel::isScalarEpilogueAllowed(), and LLVM_DEBUG.
Referenced by llvm::LoopVectorizePass::processLoop().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/LoopVectorizationPlanner.h
lib/Transforms/Vectorize/LoopVectorize.cpp