LLVM: llvm::MCSymbolMachO Class Reference
llvm::MCSymbolMachO Class Reference
#include "llvm/MC/MCSymbolMachO.h"
Public Member Functions
MCSymbolMachO (const MCSymbolTableEntry *Name, bool isTemporary)
bool isPrivateExtern () const
void setPrivateExtern (bool Value)
void clearReferenceType () const
void setReferenceTypeUndefinedLazy (bool Value) const
void setThumbFunc () const
bool isNoDeadStrip () const
void setNoDeadStrip () const
bool isWeakReference () const
void setWeakReference () const
bool isWeakDefinition () const
void setWeakDefinition () const
bool isSymbolResolver () const
void setSymbolResolver () const
void setAltEntry () const
bool isAltEntry () const
void setCold () const
bool isCold () const
void setDesc (unsigned Value) const
bool isSymbolLinkerVisible () const
uint16_t getEncodedFlags (bool EncodeAsAltEntry) const
Get the encoded value of the flags as they will be emitted in to the MachO binary.
Public Member Functions inherited from llvm::MCSymbol
MCSymbol (const MCSymbol &)=delete
MCSymbol & operator= (const MCSymbol &)=delete
StringRef getName () const
getName - Get the symbol name.
bool isRegistered () const
void setIsRegistered (bool Value) const
void setUsedInReloc () const
bool isUsedInReloc () const
uint32_t getIndex () const
Get the (implementation defined) index.
void setIndex (uint32_t Value) const
Set the (implementation defined) index.
bool isUnset () const
uint64_t getOffset () const
void setOffset (uint64_t Value)
uint64_t getCommonSize () const
Return the size of a 'common' symbol.
void setCommon (uint64_t Size, Align Alignment, bool Target=false)
Mark this symbol as being 'common'.
MaybeAlign getCommonAlignment () const
Return the alignment of a 'common' symbol.
bool declareCommon (uint64_t Size, Align Alignment, bool Target=false)
Declare this symbol as being 'common'.
bool isCommon () const
Is this a 'common' symbol.
bool isTargetCommon () const
Is this a target-specific common-like symbol.
MCFragment * getFragment (bool SetUsed=true) const
bool isExternal () const
void setExternal (bool Value) const
bool isWeakExternal () const
void print (raw_ostream &OS, const MCAsmInfo *MAI) const
print - Print the value to the stream OS.
void dump () const
dump - Print the value to stderr.
bool isTemporary () const
isTemporary - Check if this is an assembler temporary symbol.
bool isUsed () const
isUsed - Check if this is used.
bool isRedefinable () const
Check if this symbol is redefinable.
void setRedefinable (bool Value)
Mark this symbol as redefinable.
void redefineIfPossible ()
Prepare this symbol to be redefined.
bool isDefined () const
isDefined - Check if this symbol is defined (i.e., it has an address).
bool isInSection () const
isInSection - Check if this symbol is defined in some section (i.e., it is defined but not absolute).
bool isUndefined (bool SetUsed=true) const
isUndefined - Check if this symbol undefined (i.e., implicitly defined).
bool isAbsolute () const
isAbsolute - Check if this is an absolute symbol.
MCSection & getSection () const
Get the section associated with a defined, non-absolute symbol.
void setFragment (MCFragment *F) const
Mark the symbol as defined in the fragment F.
void setUndefined ()
Mark the symbol as undefined.
bool isELF () const
bool isCOFF () const
bool isGOFF () const
bool isMachO () const
bool isWasm () const
bool isXCOFF () const
bool isVariable () const
isVariable - Check if this is a variable symbol.
const MCExpr * getVariableValue (bool SetUsed=true) const
getVariableValue - Get the value for variable symbols.
void setVariableValue (const MCExpr *Value)
Static Public Member Functions
static bool classof (const MCSymbol *S)
Additional Inherited Members
Public Attributes inherited from llvm::MCSymbol
Protected Types inherited from llvm::MCSymbol
enum SymbolKind {
SymbolKindUnset , SymbolKindCOFF , SymbolKindELF , SymbolKindGOFF ,
SymbolKindMachO , SymbolKindWasm , SymbolKindXCOFF
}
The kind of the symbol.
enum Contents : uint8_t {
SymContentsUnset , SymContentsOffset , SymContentsVariable , SymContentsCommon ,
SymContentsTargetCommon
}
A symbol can contain an Offset, or Value, or be Common, but never more than one of these.
enum : unsigned { NumCommonAlignmentBits = 5 }
The alignment of the symbol if it is 'common'.
enum : unsigned { NumFlagsBits = 16 }
The Flags field is used by object file implementations to store additional per symbol information which is not easily classified.
using NameEntryStorageTy
The name for a symbol.
Protected Member Functions inherited from llvm::MCSymbol
MCSymbol (SymbolKind Kind, const MCSymbolTableEntry *Name, bool isTemporary)
void * operator new (size_t s, const MCSymbolTableEntry *Name, MCContext &Ctx)
uint32_t getFlags () const
Get the (implementation defined) symbol flags.
void setFlags (uint32_t Value) const
Set the (implementation defined) symbol flags.
void modifyFlags (uint32_t Value, uint32_t Mask) const
Modify the flags via a mask.
Protected Attributes inherited from llvm::MCSymbol
MCFragment * Fragment = nullptr
If a symbol has a Fragment, the section is implied, so we only need one pointer.
unsigned HasName: 1
True if this symbol is named.
unsigned IsTemporary: 1
IsTemporary - True if this is an assembler temporary label, which typically does not survive in the .o file's symbol table.
unsigned IsRedefinable: 1
True if this symbol can be redefined.
unsigned IsUsed: 1
IsUsed - True if this symbol has been used.
unsigned IsRegistered: 1
unsigned IsExternal: 1
True if this symbol is visible outside this translation unit.
unsigned IsPrivateExtern: 1
Mach-O specific: This symbol is private extern.
unsigned IsWeakExternal: 1
This symbol is weak external.
unsigned Kind: 3
LLVM RTTI discriminator.
unsigned IsUsedInReloc: 1
True if we have created a relocation that uses this symbol.
unsigned SymbolContents: 3
This is actually a Contents enumerator, but is unsigned to avoid sign extension and achieve better bitpacking with MSVC.
unsigned CommonAlignLog2: NumCommonAlignmentBits
uint32_t Flags: NumFlagsBits
uint32_t Index = 0
Index field, for use by the object file implementation.
union {
uint64_t Offset
The offset to apply to the fragment address to form this symbol's value.
uint64_t CommonSize
The size of the symbol, if it is 'common'.
const MCExpr * Value
If non-null, the value for a variable symbol.
};
Static Protected Attributes inherited from llvm::MCSymbol
static MCFragment * AbsolutePseudoFragment = &SentinelFragment
Detailed Description
Definition at line 16 of file MCSymbolMachO.h.
Constructor & Destructor Documentation
MCSymbolMachO()
llvm::MCSymbolMachO::MCSymbolMachO (const MCSymbolTableEntry * Name, bool isTemporary) inline
Definition at line 46 of file MCSymbolMachO.h.
Member Function Documentation
classof()
static bool llvm::MCSymbolMachO::classof (const MCSymbol * S) inline static
Definition at line 153 of file MCSymbolMachO.h.
References llvm::MCSymbol::isMachO().
clearReferenceType()
void llvm::MCSymbolMachO::clearReferenceType () const inline
Definition at line 54 of file MCSymbolMachO.h.
References llvm::MCSymbol::modifyFlags().
getEncodedFlags()
uint16_t llvm::MCSymbolMachO::getEncodedFlags (bool EncodeAsAltEntry) const inline
Get the encoded value of the flags as they will be emitted in to the MachO binary.
Definition at line 129 of file MCSymbolMachO.h.
References llvm::MCSymbol::Flags, llvm::MCSymbol::getCommonAlignment(), llvm::MCSymbol::getFlags(), llvm::MCSymbol::getName(), llvm::MCSymbol::isCommon(), llvm::Log2(), llvm::report_fatal_error(), and llvm::Align::value().
isAltEntry()
bool llvm::MCSymbolMachO::isAltEntry () const inline
Definition at line 101 of file MCSymbolMachO.h.
References llvm::MCSymbol::getFlags().
isCold()
bool llvm::MCSymbolMachO::isCold () const inline
Definition at line 107 of file MCSymbolMachO.h.
References llvm::MCSymbol::getFlags().
isNoDeadStrip()
bool llvm::MCSymbolMachO::isNoDeadStrip () const inline
Definition at line 69 of file MCSymbolMachO.h.
References llvm::MCSymbol::getFlags().
isPrivateExtern()
bool llvm::MCSymbolMachO::isPrivateExtern () const inline
Definition at line 49 of file MCSymbolMachO.h.
References llvm::MCSymbol::IsPrivateExtern.
isSymbolLinkerVisible()
bool llvm::MCSymbolMachO::isSymbolLinkerVisible () const inline
Definition at line 119 of file MCSymbolMachO.h.
References llvm::MCSymbol::isTemporary(), and llvm::MCSymbol::isUsedInReloc().
isSymbolResolver()
bool llvm::MCSymbolMachO::isSymbolResolver () const inline
Definition at line 90 of file MCSymbolMachO.h.
References llvm::MCSymbol::getFlags().
isWeakDefinition()
bool llvm::MCSymbolMachO::isWeakDefinition () const inline
Definition at line 83 of file MCSymbolMachO.h.
References llvm::MCSymbol::getFlags().
isWeakReference()
bool llvm::MCSymbolMachO::isWeakReference () const inline
Definition at line 76 of file MCSymbolMachO.h.
References llvm::MCSymbol::getFlags().
setAltEntry()
void llvm::MCSymbolMachO::setAltEntry () const inline
Definition at line 97 of file MCSymbolMachO.h.
References llvm::MCSymbol::modifyFlags().
setCold()
void llvm::MCSymbolMachO::setCold () const inline
Definition at line 105 of file MCSymbolMachO.h.
References llvm::MCSymbol::modifyFlags().
setDesc()
void llvm::MCSymbolMachO::setDesc (unsigned Value) const inline
Definition at line 109 of file MCSymbolMachO.h.
References assert(), and llvm::MCSymbol::setFlags().
setNoDeadStrip()
void llvm::MCSymbolMachO::setNoDeadStrip () const inline
Definition at line 72 of file MCSymbolMachO.h.
References llvm::MCSymbol::modifyFlags().
setPrivateExtern()
void llvm::MCSymbolMachO::setPrivateExtern (bool Value) inline
Definition at line 50 of file MCSymbolMachO.h.
References llvm::MCSymbol::IsPrivateExtern, and llvm::MCSymbol::Value.
setReferenceTypeUndefinedLazy()
void llvm::MCSymbolMachO::setReferenceTypeUndefinedLazy (bool Value) const inline
Definition at line 58 of file MCSymbolMachO.h.
References llvm::MCSymbol::modifyFlags().
setSymbolResolver()
void llvm::MCSymbolMachO::setSymbolResolver () const inline
Definition at line 93 of file MCSymbolMachO.h.
References llvm::MCSymbol::modifyFlags().
setThumbFunc()
void llvm::MCSymbolMachO::setThumbFunc () const inline
Definition at line 65 of file MCSymbolMachO.h.
References llvm::MCSymbol::modifyFlags().
setWeakDefinition()
void llvm::MCSymbolMachO::setWeakDefinition () const inline
Definition at line 86 of file MCSymbolMachO.h.
References llvm::MCSymbol::modifyFlags().
setWeakReference()
void llvm::MCSymbolMachO::setWeakReference () const inline
Definition at line 79 of file MCSymbolMachO.h.
References llvm::MCSymbol::modifyFlags().
The documentation for this class was generated from the following file:
include/llvm/MC/MCSymbolMachO.h