LLVM: llvm::BTFParser Class Reference
llvm::BTFParser Class Reference
#include "llvm/DebugInfo/BTF/BTFParser.h"
Classes
struct ParseContext
struct ParseOptions
Public Member Functions
StringRef findString (uint32_t Offset) const
const BTF::BPFLineInfo * findLineInfo (SectionedAddress Address) const
const BTF::BPFFieldReloc * findFieldReloc (SectionedAddress Address) const
void symbolize (const BTF::BPFFieldReloc *Reloc, SmallVectorImpl< char > &Result) const
const BTF::CommonType * findType (uint32_t Id) const
size_t typesCount () const
Error parse (const ObjectFile &Obj, const ParseOptions &Opts)
Error parse (const ObjectFile &Obj)
Static Public Member Functions
static bool hasBTFSections (const ObjectFile &Obj)
Detailed Description
Definition at line 35 of file BTFParser.h.
Member Function Documentation
findFieldReloc()
const BTF::BPFFieldReloc * BTFParser::findFieldReloc (SectionedAddress Address) const
Definition at line 454 of file BTFParser.cpp.
References findInfo().
findLineInfo()
const BTF::BPFLineInfo * BTFParser::findLineInfo (SectionedAddress Address) const
Definition at line 449 of file BTFParser.cpp.
References findInfo().
Referenced by llvm::BTFContext::getLineInfoForAddress().
findString()
StringRef BTFParser::findString (uint32_t Offset) const
Definition at line 427 of file BTFParser.cpp.
References llvm::StringRef::find(), llvm::Offset, and llvm::StringRef::slice().
Referenced by llvm::BTFContext::getLineInfoForAddress(), printMod(), and symbolize().
findType()
const BTF::CommonType * BTFParser::findType (uint32_t Id) const
Definition at line 458 of file BTFParser.cpp.
Referenced by skipModsAndTypedefs(), and symbolize().
hasBTFSections()
bool BTFParser::hasBTFSections (const ObjectFile & Obj) static
Definition at line 410 of file BTFParser.cpp.
References BTFExtSectionName, BTFSectionName, llvm::errs(), llvm::logAllUnhandledErrors(), Name, and llvm::object::ObjectFile::sections().
Referenced by llvm::symbolize::useBTFContext().
parse() [1/2]
Error llvm::BTFParser::parse (const ObjectFile & Obj) inline
Definition at line 124 of file BTFParser.h.
References parse().
Referenced by parse().
parse() [2/2]
Error BTFParser::parse (const ObjectFile & Obj, const ParseOptions & Opts)
Definition at line 378 of file BTFParser.cpp.
References BTFExtSectionName, BTFSectionName, E, llvm::object::ObjectFile::sections(), llvm::Error::success(), and llvm::Expected< T >::takeError().
symbolize()
void BTFParser::symbolize (const BTF::BPFFieldReloc * Reloc, SmallVectorImpl< char > & Result) const
Definition at line 657 of file BTFParser.cpp.
References llvm::consumeUnsignedInteger(), llvm::dyn_cast(), llvm::StringRef::empty(), llvm::BTF::ENUM_SIGNED_FLAG, Fail, findString(), findType(), llvm::format(), llvm::BTF::FWD_UNION_FLAG, I, llvm::BTF::BPFFieldReloc::OffsetNameOff, printMod(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::BTF::BPFFieldReloc::RelocKind, relocKindGroup(), relocKindName(), RKG_ENUMVAL, RKG_FIELD, RKG_TYPE, llvm::SmallVectorBase< Size_T >::size(), llvm::StringRef::size(), skipModsAndTypedefs(), llvm::StringRef::substr(), llvm::Type::Type(), and llvm::BTF::BPFFieldReloc::TypeID.
typesCount()
size_t llvm::BTFParser::typesCount () const inline
Definition at line 105 of file BTFParser.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/BTF/BTFParser.h
lib/DebugInfo/BTF/BTFParser.cpp