LLVM: llvm::NumberedValues< T > Class Template Reference
llvm::NumberedValues< T > Class Template Reference
Mapping from value ID to value, which also remembers what the next unused ID is.
#include "llvm/AsmParser/NumberedValues.h"
Public Member Functions
unsigned getNext () const
T get (unsigned ID) const
void add (unsigned ID, T V)
Detailed Description
template<class T>
class llvm::NumberedValues< T >
Mapping from value ID to value, which also remembers what the next unused ID is.
Definition at line 18 of file NumberedValues.h.
Member Function Documentation
add()
template<class T > void llvm::NumberedValues< T >::add (unsigned ID, T V) inline
Definition at line 25 of file NumberedValues.h.
References assert(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert().
get()
template<class T > T llvm::NumberedValues< T >::get (unsigned ID) const inline
Definition at line 24 of file NumberedValues.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
getNext()
template<class T > unsigned llvm::NumberedValues< T >::getNext () const inline
Definition at line 23 of file NumberedValues.h.
The documentation for this class was generated from the following file:
include/llvm/AsmParser/NumberedValues.h