LLVM: llvm::PrintIRInstrumentation Class Reference
llvm::PrintIRInstrumentation Class Reference
Instrumentation to print IR before/after passes.
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
~PrintIRInstrumentation ()
void registerCallbacks (PassInstrumentationCallbacks &PIC)
Detailed Description
Instrumentation to print IR before/after passes.
Needs state to be able to print module after pass that invalidates IR unit (typically Loop or SCC).
Definition at line 45 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
~PrintIRInstrumentation()
PrintIRInstrumentation::~PrintIRInstrumentation ()
Definition at line 746 of file StandardInstrumentations.cpp.
References assert(), and llvm::SmallVectorBase< Size_T >::empty().
Member Function Documentation
registerCallbacks()
void PrintIRInstrumentation::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 1012 of file StandardInstrumentations.cpp.
References IR, P, PIC, llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback(), llvm::PassInstrumentationCallbacks::registerBeforeNonSkippedPassCallback(), llvm::shouldPrintAfterSomePass(), and llvm::shouldPrintBeforeSomePass().
Referenced by llvm::StandardInstrumentations::registerCallbacks().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp