LLVM: llvm::ExistsOpInit Class Reference
llvm::ExistsOpInit Class Reference
!exists<type>(expr) - Dynamically determine if a record of type named expr exists.
#include "llvm/TableGen/Record.h"
Public Member Functions
ExistsOpInit (const ExistsOpInit &)=delete
ExistsOpInit & operator= (const ExistsOpInit &)=delete
void Profile (FoldingSetNodeID &ID) const
Init * Fold (Record *CurRec, bool IsFinal=false) const
bool isComplete () const override
Is this a complete value with no unset (uninitialized) subvalues?
Init * resolveReferences (Resolver &R) const override
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
Init * getBit (unsigned Bit) const override
Get the Init value of the specified bit.
std::string getAsString () const override
Convert this value to a literal form.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Get the type of the Init as a RecTy.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init * getCastTo (RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This function is used to implement the bit range selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print this value.
virtual std::string getAsUnquotedString () const
Convert this value to a literal form, without adding quotes around a string.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const Init *I)
static ExistsOpInit * get (RecTy *CheckType, Init *Expr)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_DagInit , IK_DefInit , IK_FieldInit , IK_IntInit ,
IK_ListInit , IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit ,
IK_UnOpInit , IK_LastOpInit , IK_CondOpInit , IK_FoldOpInit ,
IK_IsAOpInit , IK_ExistsOpInit , IK_AnonymousNameInit , IK_StringInit ,
IK_VarInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit , IK_ArgumentInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
!exists<type>(expr) - Dynamically determine if a record of type named expr exists.
Definition at line 1204 of file Record.h.
Constructor & Destructor Documentation
ExistsOpInit()
llvm::ExistsOpInit::ExistsOpInit (const ExistsOpInit &) delete
Member Function Documentation
classof()
static bool llvm::ExistsOpInit::classof (const Init * I) inline static
Definition at line 1217 of file Record.h.
References I, and llvm::Init::IK_ExistsOpInit.
Fold()
Init * ExistsOpInit::Fold (Record * CurRec, bool IsFinal = false) const
Definition at line 2050 of file Record.cpp.
References D, llvm::dyn_cast(), llvm::DefInit::get(), llvm::IntInit::get(), llvm::RecordKeeper::getDef(), llvm::Record::getNameInit(), llvm::RecTy::getRecordKeeper(), llvm::TypedInit::getRecordKeeper(), llvm::Record::getType(), llvm::TypedInit::getType(), Name, and llvm::RecordRecTy::typeIsA().
Referenced by resolveReferences().
get()
ExistsOpInit * ExistsOpInit::get (RecTy * CheckType, Init * Expr) static
Definition at line 2032 of file Record.cpp.
References llvm::detail::RecordKeeperImpl::Allocator, llvm::RecordKeeper::getImpl(), llvm::Init::getRecordKeeper(), I, ProfileExistsOpInit(), and llvm::detail::RecordKeeperImpl::TheExistsOpInitPool.
Referenced by resolveReferences().
getAsString()
std::string ExistsOpInit::getAsString () const override virtual
Convert this value to a literal form.
Implements llvm::Init.
Definition at line 2095 of file Record.cpp.
References llvm::Init::getAsString(), and llvm::RecTy::getAsString().
getBit()
Init * ExistsOpInit::getBit (unsigned Bit) const override virtual
Get the Init value of the specified bit.
Implements llvm::Init.
Definition at line 2091 of file Record.cpp.
References llvm::VarBitInit::get().
isComplete()
bool llvm::ExistsOpInit::isComplete () const inline override virtual
Is this a complete value with no unset (uninitialized) subvalues?
Reimplemented from llvm::Init.
Definition at line 1227 of file Record.h.
operator=()
ExistsOpInit & llvm::ExistsOpInit::operator= (const ExistsOpInit &) delete
Profile()
void ExistsOpInit::Profile (FoldingSetNodeID & ID) const
Definition at line 2046 of file Record.cpp.
References ProfileExistsOpInit().
resolveReferences()
Init * ExistsOpInit::resolveReferences (Resolver & R) const override virtual
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 2084 of file Record.cpp.
References Fold(), get(), and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp