LLVM: llvm::object::TXTRecord Class Reference
llvm::object::TXTRecord Class Reference
#include "llvm/Object/GOFF.h"
Static Public Member Functions
static Error getData (const uint8_t *Record, SmallString< 256 > &CompleteData)
static void getElementEsdId (const uint8_t *Record, uint32_t &EsdId)
static void getOffset (const uint8_t *Record, uint32_t &Offset)
static void getDataLength (const uint8_t *Record, uint16_t &Length)
Static Public Member Functions inherited from llvm::object::Record
static Error getContinuousData (const uint8_t *Record, uint16_t DataLength, int DataIndex, SmallString< 256 > &CompleteData)
static bool isContinued (const uint8_t *Record)
static bool isContinuation (const uint8_t *Record)
Static Public Attributes
static const uint8_t TXTMaxDataLength = 56
Maximum length of data; any more must go in continuation.
Additional Inherited Members
Static Protected Member Functions inherited from llvm::object::Record
static void getBits (const uint8_t *Bytes, uint8_t ByteIndex, uint8_t BitIndex, uint8_t Length, uint8_t &Value)
Get bit field of specified byte.
template<class T >
static void get (const uint8_t *Bytes, uint8_t ByteIndex, T &Value)
Detailed Description
Definition at line 76 of file GOFF.h.
Member Function Documentation
getData()
Error TXTRecord::getData (const uint8_t * Record, SmallString< 256 > & CompleteData) static
Definition at line 636 of file GOFFObjectFile.cpp.
References llvm::object::Record::getContinuousData(), getDataLength(), and llvm::Length.
getDataLength()
static void llvm::object::TXTRecord::getDataLength (const uint8_t * Record, uint16_t & Length) inline static
Definition at line 91 of file GOFF.h.
References llvm::object::Record::get(), and llvm::Length.
Referenced by getData().
getElementEsdId()
static void llvm::object::TXTRecord::getElementEsdId (const uint8_t * Record, uint32_t & EsdId) inline static
Definition at line 83 of file GOFF.h.
References llvm::object::Record::get().
getOffset()
static void llvm::object::TXTRecord::getOffset (const uint8_t * Record, uint32_t & Offset) inline static
Definition at line 87 of file GOFF.h.
References llvm::object::Record::get(), and llvm::Offset.
Member Data Documentation
TXTMaxDataLength
const uint8_t llvm::object::TXTRecord::TXTMaxDataLength = 56 static
Maximum length of data; any more must go in continuation.
Definition at line 79 of file GOFF.h.
The documentation for this class was generated from the following files:
include/llvm/Object/GOFF.h
lib/Object/GOFFObjectFile.cpp