LLVM: llvm::detail::DoubleAPFloat Class Reference
llvm::detail::DoubleAPFloat Class Reference final
#include "llvm/ADT/APFloat.h"
Public Member Functions
DoubleAPFloat (const fltSemantics &S)
DoubleAPFloat (const fltSemantics &S, uninitializedTag)
DoubleAPFloat (const fltSemantics &S, integerPart)
DoubleAPFloat (const fltSemantics &S, const APInt &I)
DoubleAPFloat (const fltSemantics &S, APFloat &&First, APFloat &&Second)
DoubleAPFloat (const DoubleAPFloat &RHS)
DoubleAPFloat (DoubleAPFloat &&RHS)
DoubleAPFloat & operator= (const DoubleAPFloat &RHS)
DoubleAPFloat & operator= (DoubleAPFloat &&RHS)
bool needsCleanup () const
APFloat & getFirst ()
const APFloat & getFirst () const
APFloat & getSecond ()
const APFloat & getSecond () const
opStatus add (const DoubleAPFloat &RHS, roundingMode RM)
opStatus subtract (const DoubleAPFloat &RHS, roundingMode RM)
opStatus multiply (const DoubleAPFloat &RHS, roundingMode RM)
opStatus divide (const DoubleAPFloat &RHS, roundingMode RM)
opStatus remainder (const DoubleAPFloat &RHS)
opStatus mod (const DoubleAPFloat &RHS)
opStatus fusedMultiplyAdd (const DoubleAPFloat &Multiplicand, const DoubleAPFloat &Addend, roundingMode RM)
opStatus roundToIntegral (roundingMode RM)
void changeSign ()
cmpResult compareAbsoluteValue (const DoubleAPFloat &RHS) const
fltCategory getCategory () const
bool isNegative () const
void makeInf (bool Neg)
void makeZero (bool Neg)
void makeLargest (bool Neg)
void makeSmallest (bool Neg)
void makeSmallestNormalized (bool Neg)
void makeNaN (bool SNaN, bool Neg, const APInt *fill)
cmpResult compare (const DoubleAPFloat &RHS) const
bool bitwiseIsEqual (const DoubleAPFloat &RHS) const
APInt bitcastToAPInt () const
Expected< opStatus > convertFromString (StringRef, roundingMode)
opStatus next (bool nextDown)
opStatus convertToInteger (MutableArrayRef< integerPart > Input, unsigned int Width, bool IsSigned, roundingMode RM, bool *IsExact) const
opStatus convertFromAPInt (const APInt &Input, bool IsSigned, roundingMode RM)
opStatus convertFromSignExtendedInteger (const integerPart *Input, unsigned int InputSize, bool IsSigned, roundingMode RM)
opStatus convertFromZeroExtendedInteger (const integerPart *Input, unsigned int InputSize, bool IsSigned, roundingMode RM)
unsigned int convertToHexString (char *DST, unsigned int HexDigits, bool UpperCase, roundingMode RM) const
bool isDenormal () const
bool isSmallest () const
bool isSmallestNormalized () const
bool isLargest () const
bool isInteger () const
void toString (SmallVectorImpl< char > &Str, unsigned FormatPrecision, unsigned FormatMaxPadding, bool TruncateZero=true) const
bool getExactInverse (APFloat *inv) const
LLVM_READONLY int getExactLog2 () const
LLVM_READONLY int getExactLog2Abs () const
Friends
DoubleAPFloat scalbn (const DoubleAPFloat &X, int Exp, roundingMode)
DoubleAPFloat frexp (const DoubleAPFloat &X, int &Exp, roundingMode)
hash_code hash_value (const DoubleAPFloat &Arg)
Additional Inherited Members
Public Types inherited from llvm::APFloatBase
enum cmpResult { cmpLessThan , cmpEqual , cmpGreaterThan , cmpUnordered }
IEEE-754R 5.11: Floating Point Comparison Relations.
enum opStatus {
opOK = 0x00 , opInvalidOp = 0x01 , opDivByZero = 0x02 , opOverflow = 0x04 ,
opUnderflow = 0x08 , opInexact = 0x10
}
IEEE-754R 7: Default exception handling.
enum fltCategory { fcInfinity , fcNaN , fcNormal , fcZero }
Category of internally-represented number.
enum uninitializedTag { uninitialized }
Convenience enum used to construct an uninitialized APFloat.
enum IlogbErrorKinds { IEK_Zero = INT_MIN + 1 , IEK_NaN = INT_MIN , IEK_Inf = INT_MAX }
Enumeration of ilogb error results.
typedef APInt::WordType integerPart
typedef int32_t ExponentType
A signed type to represent a floating point numbers unbiased exponent.
using roundingMode = llvm::RoundingMode
IEEE-754R 4.3: Rounding-direction attributes.
enum Semantics {
S_IEEEhalf , S_BFloat , S_IEEEsingle , S_IEEEdouble ,
S_IEEEquad , S_PPCDoubleDouble , S_Float8E5M2 , S_Float8E5M2FNUZ ,
S_Float8E4M3 , S_Float8E4M3FN , S_Float8E4M3FNUZ , S_Float8E4M3B11FNUZ ,
S_FloatTF32 , S_Float6E3M2FN , S_Float6E2M3FN , S_Float4E2M1FN ,
S_x87DoubleExtended , S_MaxSemantics = S_x87DoubleExtended
}
Static Public Member Functions inherited from llvm::APFloatBase
static unsigned int semanticsPrecision (const fltSemantics &)
static ExponentType semanticsMinExponent (const fltSemantics &)
static ExponentType semanticsMaxExponent (const fltSemantics &)
static unsigned int semanticsSizeInBits (const fltSemantics &)
static unsigned int semanticsIntSizeInBits (const fltSemantics &, bool)
static bool isRepresentableAsNormalIn (const fltSemantics &Src, const fltSemantics &Dst)
static unsigned getSizeInBits (const fltSemantics &Sem)
Returns the size of the floating point number (in bits) in the given semantics.
static const llvm::fltSemantics & EnumToSemantics (Semantics S)
static Semantics SemanticsToEnum (const llvm::fltSemantics &Sem)
static const fltSemantics & IEEEhalf () LLVM_READNONE
static const fltSemantics & BFloat () LLVM_READNONE
static const fltSemantics & IEEEsingle () LLVM_READNONE
static const fltSemantics & IEEEdouble () LLVM_READNONE
static const fltSemantics & IEEEquad () LLVM_READNONE
static const fltSemantics & PPCDoubleDouble () LLVM_READNONE
static const fltSemantics & Float8E5M2 () LLVM_READNONE
static const fltSemantics & Float8E5M2FNUZ () LLVM_READNONE
static const fltSemantics & Float8E4M3 () LLVM_READNONE
static const fltSemantics & Float8E4M3FN () LLVM_READNONE
static const fltSemantics & Float8E4M3FNUZ () LLVM_READNONE
static const fltSemantics & Float8E4M3B11FNUZ () LLVM_READNONE
static const fltSemantics & FloatTF32 () LLVM_READNONE
static const fltSemantics & Float6E3M2FN () LLVM_READNONE
static const fltSemantics & Float6E2M3FN () LLVM_READNONE
static const fltSemantics & Float4E2M1FN () LLVM_READNONE
static const fltSemantics & x87DoubleExtended () LLVM_READNONE
static const fltSemantics & Bogus () LLVM_READNONE
A Pseudo fltsemantic used to construct APFloats that cannot conflict with anything real.
Static Public Attributes inherited from llvm::APFloatBase
static constexpr unsigned integerPartWidth = APInt::APINT_BITS_PER_WORD
static constexpr roundingMode rmNearestTiesToEven
static constexpr roundingMode rmTowardPositive = RoundingMode::TowardPositive
static constexpr roundingMode rmTowardNegative = RoundingMode::TowardNegative
static constexpr roundingMode rmTowardZero = RoundingMode::TowardZero
static constexpr roundingMode rmNearestTiesToAway
Detailed Description
Definition at line 711 of file APFloat.h.
Constructor & Destructor Documentation
DoubleAPFloat() [1/7]
llvm::detail::DoubleAPFloat::DoubleAPFloat (const fltSemantics & S)
Definition at line 4683 of file APFloat.cpp.
References llvm::semIEEEdouble.
Referenced by convertFromAPInt(), convertFromSignExtendedInteger(), convertFromString(), convertFromZeroExtendedInteger(), divide(), fusedMultiplyAdd(), mod(), next(), operator=(), operator=(), remainder(), and roundToIntegral().
DoubleAPFloat() [2/7]
llvm::detail::DoubleAPFloat::DoubleAPFloat (const fltSemantics & S, uninitializedTag)
Definition at line 4689 of file APFloat.cpp.
References llvm::semIEEEdouble, and llvm::APFloatBase::uninitialized.
DoubleAPFloat() [3/7]
llvm::detail::DoubleAPFloat::DoubleAPFloat (const fltSemantics & S, integerPart I)
Definition at line 4696 of file APFloat.cpp.
References I, and llvm::semIEEEdouble.
DoubleAPFloat() [4/7]
llvm::detail::DoubleAPFloat::DoubleAPFloat (const fltSemantics & S, const APInt & I)
Definition at line 4702 of file APFloat.cpp.
References I, and llvm::semIEEEdouble.
DoubleAPFloat() [5/7]
llvm::detail::DoubleAPFloat::DoubleAPFloat (const fltSemantics & S, APFloat && First, APFloat && Second)
Definition at line 4710 of file APFloat.cpp.
References llvm::First.
DoubleAPFloat() [6/7]
llvm::detail::DoubleAPFloat::DoubleAPFloat (const DoubleAPFloat & RHS)
Definition at line 4719 of file APFloat.cpp.
DoubleAPFloat() [7/7]
llvm::detail::DoubleAPFloat::DoubleAPFloat (DoubleAPFloat && RHS)
Definition at line 4727 of file APFloat.cpp.
References assert(), llvm::semBogus, and llvm::semPPCDoubleDouble.
Member Function Documentation
add()
APFloat::opStatus llvm::detail::DoubleAPFloat::add (const DoubleAPFloat & RHS, roundingMode RM)
Definition at line 4872 of file APFloat.cpp.
Referenced by subtract().
bitcastToAPInt()
APInt llvm::detail::DoubleAPFloat::bitcastToAPInt () const
Definition at line 5107 of file APFloat.cpp.
References assert(), llvm::Data, and llvm::semPPCDoubleDouble.
Referenced by convertToHexString(), convertToInteger(), divide(), fusedMultiplyAdd(), getExactInverse(), mod(), next(), remainder(), roundToIntegral(), and toString().
bitwiseIsEqual()
bool llvm::detail::DoubleAPFloat::bitwiseIsEqual (const DoubleAPFloat & RHS) const
Definition at line 5096 of file APFloat.cpp.
changeSign()
void llvm::detail::DoubleAPFloat::changeSign ()
Definition at line 5019 of file APFloat.cpp.
Referenced by makeLargest(), and subtract().
compare()
APFloat::cmpResult llvm::detail::DoubleAPFloat::compare (const DoubleAPFloat & RHS) const
Definition at line 5088 of file APFloat.cpp.
References llvm::APFloatBase::cmpEqual.
Referenced by isLargest(), isSmallest(), and isSmallestNormalized().
compareAbsoluteValue()
APFloat::cmpResult llvm::detail::DoubleAPFloat::compareAbsoluteValue (const DoubleAPFloat & RHS) const
Definition at line 5025 of file APFloat.cpp.
References llvm::APFloatBase::cmpEqual, llvm::APFloatBase::cmpGreaterThan, and llvm::APFloatBase::cmpLessThan.
convertFromAPInt()
APFloat::opStatus llvm::detail::DoubleAPFloat::convertFromAPInt (const APInt & Input, bool IsSigned, roundingMode RM)
Definition at line 5142 of file APFloat.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), llvm::APFloat::convertFromAPInt(), DoubleAPFloat(), llvm::semPPCDoubleDouble, and llvm::semPPCDoubleDoubleLegacy.
convertFromSignExtendedInteger()
APFloat::opStatus llvm::detail::DoubleAPFloat::convertFromSignExtendedInteger (const integerPart * Input, unsigned int InputSize, bool IsSigned, roundingMode RM)
Definition at line 5153 of file APFloat.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), llvm::APFloat::convertFromSignExtendedInteger(), DoubleAPFloat(), llvm::semPPCDoubleDouble, and llvm::semPPCDoubleDoubleLegacy.
convertFromString()
Expected< APFloat::opStatus > llvm::detail::DoubleAPFloat::convertFromString (StringRef S, roundingMode RM)
Definition at line 5116 of file APFloat.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), llvm::APFloat::convertFromString(), DoubleAPFloat(), llvm::semPPCDoubleDouble, and llvm::semPPCDoubleDoubleLegacy.
convertFromZeroExtendedInteger()
APFloat::opStatus llvm::detail::DoubleAPFloat::convertFromZeroExtendedInteger (const integerPart * Input, unsigned int InputSize, bool IsSigned, roundingMode RM)
Definition at line 5164 of file APFloat.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), llvm::APFloat::convertFromZeroExtendedInteger(), DoubleAPFloat(), llvm::semPPCDoubleDouble, and llvm::semPPCDoubleDoubleLegacy.
convertToHexString()
unsigned int llvm::detail::DoubleAPFloat::convertToHexString (char * DST, unsigned int HexDigits, bool UpperCase, roundingMode RM) const
Definition at line 5174 of file APFloat.cpp.
References assert(), bitcastToAPInt(), llvm::APFloat::convertToHexString(), llvm::semPPCDoubleDouble, and llvm::semPPCDoubleDoubleLegacy.
convertToInteger()
APFloat::opStatus llvm::detail::DoubleAPFloat::convertToInteger (MutableArrayRef< integerPart > Input, unsigned int Width, bool IsSigned, roundingMode RM, bool * IsExact) const
Definition at line 5134 of file APFloat.cpp.
References assert(), bitcastToAPInt(), llvm::APFloat::convertToInteger(), llvm::semPPCDoubleDouble, and llvm::semPPCDoubleDoubleLegacy.
divide()
APFloat::opStatus llvm::detail::DoubleAPFloat::divide (const DoubleAPFloat & RHS, APFloat::roundingMode RM)
Definition at line 4971 of file APFloat.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), bitcastToAPInt(), llvm::APFloat::divide(), DoubleAPFloat(), llvm::semPPCDoubleDouble, and llvm::semPPCDoubleDoubleLegacy.
fusedMultiplyAdd()
APFloat::opStatus llvm::detail::DoubleAPFloat::fusedMultiplyAdd (const DoubleAPFloat & Multiplicand, const DoubleAPFloat & Addend, APFloat::roundingMode RM)
Definition at line 4999 of file APFloat.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), bitcastToAPInt(), DoubleAPFloat(), llvm::APFloat::fusedMultiplyAdd(), llvm::semPPCDoubleDouble, and llvm::semPPCDoubleDoubleLegacy.
getCategory()
APFloat::fltCategory llvm::detail::DoubleAPFloat::getCategory () const
Definition at line 5045 of file APFloat.cpp.
Referenced by llvm::detail::frexp(), isDenormal(), isLargest(), isSmallest(), and isSmallestNormalized().
getExactInverse()
bool llvm::detail::DoubleAPFloat::getExactInverse (APFloat * inv) const
Definition at line 5229 of file APFloat.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), bitcastToAPInt(), llvm::APFloat::getExactInverse(), llvm::semPPCDoubleDouble, and llvm::semPPCDoubleDoubleLegacy.
getExactLog2()
int llvm::detail::DoubleAPFloat::getExactLog2 () const
Definition at line 5240 of file APFloat.cpp.
getExactLog2Abs()
int llvm::detail::DoubleAPFloat::getExactLog2Abs () const
Definition at line 5245 of file APFloat.cpp.
getFirst() [1/2]
APFloat & llvm::detail::DoubleAPFloat::getFirst () inline
Definition at line 1545 of file APFloat.h.
getFirst() [2/2]
const APFloat & llvm::detail::DoubleAPFloat::getFirst () const inline
Definition at line 1546 of file APFloat.h.
getSecond() [1/2]
APFloat & llvm::detail::DoubleAPFloat::getSecond () inline
Definition at line 1547 of file APFloat.h.
getSecond() [2/2]
const APFloat & llvm::detail::DoubleAPFloat::getSecond () const inline
Definition at line 1548 of file APFloat.h.
isDenormal()
bool llvm::detail::DoubleAPFloat::isDenormal () const
Definition at line 5183 of file APFloat.cpp.
References llvm::APFloatBase::fcNormal, getCategory(), and isDenormal().
Referenced by isDenormal().
isInteger()
bool llvm::detail::DoubleAPFloat::isInteger () const
Definition at line 5215 of file APFloat.cpp.
References assert(), and llvm::semPPCDoubleDouble.
isLargest()
bool llvm::detail::DoubleAPFloat::isLargest () const
Definition at line 5207 of file APFloat.cpp.
References llvm::APFloatBase::cmpEqual, compare(), llvm::APFloatBase::fcNormal, getCategory(), isNegative(), and makeLargest().
isNegative()
bool llvm::detail::DoubleAPFloat::isNegative () const
Definition at line 5049 of file APFloat.cpp.
Referenced by isLargest(), isSmallest(), and isSmallestNormalized().
isSmallest()
bool llvm::detail::DoubleAPFloat::isSmallest () const
Definition at line 5190 of file APFloat.cpp.
References llvm::APFloatBase::cmpEqual, compare(), llvm::APFloatBase::fcNormal, getCategory(), isNegative(), and makeSmallest().
isSmallestNormalized()
bool llvm::detail::DoubleAPFloat::isSmallestNormalized () const
Definition at line 5198 of file APFloat.cpp.
References llvm::APFloatBase::cmpEqual, compare(), llvm::APFloatBase::fcNormal, getCategory(), isNegative(), and makeSmallestNormalized().
makeInf()
void llvm::detail::DoubleAPFloat::makeInf (bool Neg)
Definition at line 5051 of file APFloat.cpp.
makeLargest()
void llvm::detail::DoubleAPFloat::makeLargest (bool Neg)
Definition at line 5061 of file APFloat.cpp.
References assert(), changeSign(), llvm::semIEEEdouble, and llvm::semPPCDoubleDouble.
Referenced by isLargest().
makeNaN()
void llvm::detail::DoubleAPFloat::makeNaN (bool SNaN, bool Neg, const APInt * fill)
Definition at line 5083 of file APFloat.cpp.
makeSmallest()
void llvm::detail::DoubleAPFloat::makeSmallest (bool Neg)
Definition at line 5069 of file APFloat.cpp.
References assert(), and llvm::semPPCDoubleDouble.
Referenced by isSmallest().
makeSmallestNormalized()
void llvm::detail::DoubleAPFloat::makeSmallestNormalized (bool Neg)
Definition at line 5075 of file APFloat.cpp.
References assert(), llvm::semIEEEdouble, and llvm::semPPCDoubleDouble.
Referenced by isSmallestNormalized().
makeZero()
void llvm::detail::DoubleAPFloat::makeZero (bool Neg)
Definition at line 5056 of file APFloat.cpp.
mod()
APFloat::opStatus llvm::detail::DoubleAPFloat::mod (const DoubleAPFloat & RHS)
Definition at line 4990 of file APFloat.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), bitcastToAPInt(), DoubleAPFloat(), llvm::APFloat::mod(), llvm::semPPCDoubleDouble, and llvm::semPPCDoubleDoubleLegacy.
multiply()
APFloat::opStatus llvm::detail::DoubleAPFloat::multiply (const DoubleAPFloat & RHS, APFloat::roundingMode RM)
Definition at line 4885 of file APFloat.cpp.
References A, llvm::APFloat::add(), assert(), B, llvm::CallingConv::C, D, llvm::APFloatBase::fcInfinity, llvm::APFloatBase::fcNaN, llvm::APFloatBase::fcNormal, llvm::APFloatBase::fcZero, llvm::APFloat::fusedMultiplyAdd(), LHS, llvm::APFloatBase::opOK, RHS, and T.
needsCleanup()
bool llvm::detail::DoubleAPFloat::needsCleanup () const inline
Definition at line 734 of file APFloat.h.
next()
APFloat::opStatus llvm::detail::DoubleAPFloat::next (bool nextDown)
Definition at line 5125 of file APFloat.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), bitcastToAPInt(), DoubleAPFloat(), llvm::APFloat::next(), llvm::semPPCDoubleDouble, and llvm::semPPCDoubleDoubleLegacy.
operator=() [1/2]
DoubleAPFloat & llvm::detail::DoubleAPFloat::operator= (const DoubleAPFloat & RHS)
Definition at line 4733 of file APFloat.cpp.
References DoubleAPFloat().
operator=() [2/2]
DoubleAPFloat & llvm::detail::DoubleAPFloat::operator= (DoubleAPFloat && RHS) inline
Definition at line 1537 of file APFloat.h.
References DoubleAPFloat().
remainder()
APFloat::opStatus llvm::detail::DoubleAPFloat::remainder (const DoubleAPFloat & RHS)
Definition at line 4981 of file APFloat.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), bitcastToAPInt(), DoubleAPFloat(), llvm::APFloat::remainder(), llvm::semPPCDoubleDouble, and llvm::semPPCDoubleDoubleLegacy.
roundToIntegral()
APFloat::opStatus llvm::detail::DoubleAPFloat::roundToIntegral (APFloat::roundingMode RM)
Definition at line 5011 of file APFloat.cpp.
References assert(), llvm::APFloat::bitcastToAPInt(), bitcastToAPInt(), DoubleAPFloat(), llvm::APFloat::roundToIntegral(), llvm::semPPCDoubleDouble, and llvm::semPPCDoubleDoubleLegacy.
subtract()
APFloat::opStatus llvm::detail::DoubleAPFloat::subtract (const DoubleAPFloat & RHS, roundingMode RM)
Definition at line 4877 of file APFloat.cpp.
References add(), and changeSign().
toString()
void llvm::detail::DoubleAPFloat::toString (SmallVectorImpl< char > & Str, unsigned FormatPrecision, unsigned FormatMaxPadding, bool TruncateZero = true) const
Definition at line 5220 of file APFloat.cpp.
References assert(), bitcastToAPInt(), llvm::semPPCDoubleDouble, llvm::semPPCDoubleDoubleLegacy, and llvm::APFloat::toString().
Friends And Related Symbol Documentation
frexp
DoubleAPFloat frexp (const DoubleAPFloat & X, int & Exp, roundingMode) friend
hash_value
hash_code hash_value (const DoubleAPFloat & Arg) friend
Definition at line 5101 of file APFloat.cpp.
scalbn
DoubleAPFloat scalbn (const DoubleAPFloat & X, int Exp, roundingMode) friend
The documentation for this class was generated from the following files:
include/llvm/ADT/APFloat.h
lib/Support/APFloat.cpp