LLVM: llvm::VerifyInstrumentation Class Reference
llvm::VerifyInstrumentation Class Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
VerifyInstrumentation (bool DebugLogging)
void registerCallbacks (PassInstrumentationCallbacks &PIC, ModuleAnalysisManager *MAM)
Detailed Description
Definition at line 459 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
VerifyInstrumentation()
llvm::VerifyInstrumentation::VerifyInstrumentation (bool DebugLogging) inline
Definition at line 463 of file StandardInstrumentations.h.
Member Function Documentation
registerCallbacks()
void VerifyInstrumentation::registerCallbacks (PassInstrumentationCallbacks & PIC, ModuleAnalysisManager * MAM)
Definition at line 1454 of file StandardInstrumentations.cpp.
References llvm::CallingConv::C, llvm::dbgs(), llvm::errs(), F, llvm::formatv(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getName(), getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), IR, MAM, P, PIC, llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::report_fatal_error(), unwrapIR(), Verifier, llvm::verifyFunction(), llvm::verifyMachineFunction(), and llvm::verifyModule().
Referenced by llvm::StandardInstrumentations::registerCallbacks().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp