LLVM: llvm::AnalysisManager< IRUnitT, ExtraArgTs > Class Template Reference
llvm::AnalysisManager< IRUnitT, ExtraArgTs > Class Template Reference
A container for analyses that lazily runs them and caches their results.
#include "llvm/IR/PassManager.h"
Classes
class Invalidator
API to communicate dependencies between analyses during invalidation.
Public Member Functions
AnalysisManager ()
Construct an empty analysis manager.
AnalysisManager (AnalysisManager &&)
AnalysisManager & operator= (AnalysisManager &&)
bool empty () const
Returns true if the analysis manager has an empty results cache.
void clear (IRUnitT &IR, llvm::StringRef Name)
Clear any cached analysis results for a single unit of IR.
void clear ()
Clear all analysis results cached by this AnalysisManager.
template<typename PassT >
PassT::Result & getResult (IRUnitT &IR, ExtraArgTs... ExtraArgs)
Get the result of an analysis pass for a given IR unit.
template<typename PassT >
PassT::Result * getCachedResult (IRUnitT &IR) const
Get the cached result of an analysis pass for a given IR unit.
template<typename PassT >
void verifyNotInvalidated (IRUnitT &IR, typename PassT::Result *Result) const
Verify that the given Result cannot be invalidated, assert otherwise.
template<typename PassBuilderT >
bool registerPass (PassBuilderT &&PassBuilder)
Register an analysis pass with the manager.
void invalidate (IRUnitT &IR, const PreservedAnalyses &PA)
Invalidate cached analyses for an IR unit.
Detailed Description
template<typename IRUnitT, typename... ExtraArgTs>
class llvm::AnalysisManager< IRUnitT, ExtraArgTs >
A container for analyses that lazily runs them and caches their results.
This class can manage analyses for any IR unit where the address of the IR unit sufficies as its identity.
Definition at line 30 of file PassManagerInternal.h.
Constructor & Destructor Documentation
AnalysisManager() [1/2]
template<typename IRUnitT , typename... ExtraArgTs> llvm::AnalysisManager< IRUnitT, ExtraArgTs >::AnalysisManager () inline default
Construct an empty analysis manager.
AnalysisManager() [2/2]
template<typename IRUnitT , typename... ExtraArgTs> llvm::AnalysisManager< IRUnitT, ExtraArgTs >::AnalysisManager (AnalysisManager< IRUnitT, ExtraArgTs > &&) inline default
Member Function Documentation
clear() [1/2]
template<typename IRUnitT , typename... ExtraArgTs> void llvm::AnalysisManager< IRUnitT, ExtraArgTs >::clear () inline
Clear all analysis results cached by this AnalysisManager.
Like clear(IRUnitT&), this doesn't invalidate the results; it simply deletes them. This lets you clean up the AnalysisManager when the set of IR units itself has potentially changed, and thus we can't even look up a a result and invalidate/clear it directly.
Definition at line 396 of file PassManager.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear().
clear() [2/2]
template<typename IRUnitT , typename... ExtraArgTs> void llvm::AnalysisManager< IRUnitT, ExtraArgTs >::clear (IRUnitT & IR, llvm::StringRef Name) inline
Clear any cached analysis results for a single unit of IR.
This doesn't invalidate, but instead simply deletes, the relevant results. It is useful when the IR is being removed and we want to clear out all the memory pinned for it.
Definition at line 119 of file PassManagerImpl.h.
References IR, and Name.
Referenced by llvm::CallGraphUpdater::finalize(), llvm::AnalysisGetter::invalidateAnalyses(), llvm::LPMUpdater::markLoopAsDeleted(), llvm::CallGraphUpdater::removeFunction(), llvm::ArgumentPromotionPass::run(), llvm::GlobalOptPass::run(), llvm::InlinerPass::run(), llvm::LoopUnrollPass::run(), and llvm::ModuleInlinerPass::run().
empty()
template<typename IRUnitT , typename... ExtraArgTs> bool llvm::AnalysisManager< IRUnitT, ExtraArgTs >::empty () const inline
Returns true if the analysis manager has an empty results cache.
Definition at line 376 of file PassManager.h.
References assert(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty().
getCachedResult()
template<typename IRUnitT , typename... ExtraArgTs> template<typename PassT > PassT::Result * llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult (IRUnitT & IR) const inline
Get the cached result of an analysis pass for a given IR unit.
This method never runs the analysis.
Returns
null if there is no cached result.
Definition at line 424 of file PassManager.h.
References assert(), and IR.
Referenced by llvm::AnalysisGetter::getAnalysis(), incorporateNewSCCRange(), llvm::AMDGPULibCalls::initFunction(), llvm::SelectionDAGISel::initializeAnalysisResults(), llvm::FunctionAnalysisManagerCGSCCProxy::Result::invalidate(), llvm::MIRParserImpl::parseMachineFunction(), llvm::PreservedCFGCheckerInstrumentation::registerCallbacks(), llvm::ADCEPass::run(), llvm::AMDGPUCodeGenPreparePass::run(), llvm::AssumeBuilderPass::run(), llvm::AssumeSimplifyPass::run(), llvm::BreakCriticalEdgesPass::run(), llvm::CGSCCToFunctionPassAdaptor::run(), llvm::DwarfEHPreparePass::run(), llvm::ExpandMemCmpPass::run(), llvm::ExtraSimpleLoopUnswitchPassManager::run(), llvm::ExtraVectorPassManager::run(), llvm::GuardWideningPass::run(), llvm::GVNPass::run(), llvm::HotColdSplittingPass::run(), llvm::IndirectBrExpandPass::run(), llvm::InferAddressSpacesPass::run(), llvm::InlineAdvisorAnalysisPrinterPass::run(), llvm::InstCombinePass::run(), llvm::JumpTableToSwitchPass::run(), llvm::LCSSAPass::run(), llvm::LibCallsShrinkWrapPass::run(), llvm::LoopExtractorPass::run(), llvm::LoopSimplifyPass::run(), llvm::LoopUnrollPass::run(), llvm::LowerConstantIntrinsicsPass::run(), llvm::LowerSwitchPass::run(), llvm::MergeICmpsPass::run(), llvm::ModuleInlinerPass::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor::run(), llvm::PartialInlinerPass::run(), llvm::PartiallyInlineLibCallsPass::run(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), llvm::PGOMemOPSizeOpt::run(), llvm::RecomputeGlobalsAAPass::run(), llvm::ScalarizeMaskedMemIntrinPass::run(), llvm::SCCPPass::run(), llvm::ShadowStackGCLoweringPass::run(), llvm::SLPVectorizerPass::run(), llvm::StackProtectorPass::run(), llvm::TailCallElimPass::run(), runIPSCCP(), updateCGAndAnalysisManagerForPass(), and updateNewSCCFunctionAnalyses().
getResult()
template<typename IRUnitT , typename... ExtraArgTs> template<typename PassT > PassT::Result & llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult (IRUnitT & IR, ExtraArgTs... ExtraArgs) inline
Get the result of an analysis pass for a given IR unit.
Runs the analysis if a cached result is not available.
Definition at line 405 of file PassManager.h.
References assert(), and IR.
Referenced by computeVirtualCallSiteTypeInfoMap(), doPromotion(), llvm::FunctionPropertiesUpdater::finish(), llvm::MLInlineAdvisor::getAdviceImpl(), llvm::ReplayInlineAdvisor::getAdviceImpl(), llvm::AnalysisGetter::getAnalysis(), llvm::MLInlineAdvisor::getCachedFPI(), llvm::InlineAdvisor::getCallerORE(), getDefaultInlineAdvice(), llvm::FunctionPropertiesInfo::getFunctionPropertiesInfo(), llvm::getInlineOrder(), llvm::InlineAdvisor::getMandatoryKind(), llvm::AMDGPULibCalls::initFunction(), llvm::CallGraphUpdater::initialize(), llvm::SelectionDAGISel::initializeAnalysisResults(), llvm::orc::BlockFreqQuery::operator()(), llvm::MIRParserImpl::parseMachineFunction(), llvm::MIRParser::parseMachineFunctions(), promoteArguments(), promoteIndirectCalls(), llvm::DebugifyEachInstrumentation::registerCallbacks(), llvm::PreservedCFGCheckerInstrumentation::registerCallbacks(), llvm::VerifyInstrumentation::registerCallbacks(), AMDGPUISelDAGToDAGPass::run(), llvm::AAEvaluator::run(), llvm::AAManager::run(), llvm::ADCEPass::run(), llvm::AddressSanitizerPass::run(), llvm::AggressiveInstCombinePass::run(), llvm::AliasSetsPrinterPass::run(), llvm::AlignmentFromAssumptionsPass::run(), llvm::AlwaysInlinerPass::run(), llvm::AMDGPUAtomicOptimizerPass::run(), llvm::AMDGPUAttributorPass::run(), llvm::AMDGPUCodeGenPreparePass::run(), llvm::AMDGPUPromoteAllocaToVectorPass::run(), llvm::AMDGPUPromoteKernelArgumentsPass::run(), llvm::AMDGPURewriteUndefForPHIPass::run(), llvm::AMDGPUSplitModulePass::run(), llvm::AMDGPUUnifyDivergentExitNodesPass::run(), llvm::AnnotationRemarksPass::run(), llvm::ArgumentPromotionPass::run(), llvm::AssumeBuilderPass::run(), llvm::AssumeSimplifyPass::run(), llvm::AssumptionAnalysis::run(), llvm::AssumptionPrinterPass::run(), llvm::AttributorCGSCCPass::run(), llvm::AttributorLightCGSCCPass::run(), llvm::AttributorLightPass::run(), llvm::AttributorPass::run(), llvm::BasicAA::run(), llvm::BDCEPass::run(), llvm::BitcodeWriterPass::run(), llvm::BlockFrequencyAnalysis::run(), llvm::BlockFrequencyPrinterPass::run(), llvm::BoundsCheckingPass::run(), llvm::BranchProbabilityAnalysis::run(), llvm::BranchProbabilityPrinterPass::run(), llvm::CallBrPreparePass::run(), llvm::CallGraphDOTPrinterPass::run(), llvm::CallGraphPrinterPass::run(), llvm::CallGraphSCCsPrinterPass::run(), llvm::CallGraphViewerPass::run(), llvm::CallSiteSplittingPass::run(), llvm::CFGOnlyPrinterPass::run(), llvm::CFGOnlyViewerPass::run(), llvm::CFGPrinterPass::run(), llvm::CFGViewerPass::run(), llvm::CGProfilePass::run(), llvm::CGSCCToFunctionPassAdaptor::run(), llvm::ConstantHoistingPass::run(), llvm::ConstraintEliminationPass::run(), llvm::ControlHeightReductionPass::run(), llvm::CoroCleanupPass::run(), llvm::CoroElidePass::run(), llvm::CoroSplitPass::run(), llvm::CorrelatedValuePropagationPass::run(), llvm::CostModelPrinterPass::run(), llvm::CycleInfoPrinterPass::run(), llvm::DataFlowSanitizerPass::run(), llvm::DCEPass::run(), llvm::DDGAnalysisPrinterPass::run(), llvm::DDGDotPrinterPass::run(), llvm::DebugAssignmentTrackingPrinterPass::run(), llvm::DelinearizationPrinterPass::run(), llvm::DemandedBitsAnalysis::run(), llvm::DemandedBitsPrinterPass::run(), llvm::DependenceAnalysis::run(), llvm::DependenceAnalysisPrinterPass::run(), llvm::DevirtSCCRepeatedPass::run(), llvm::DFAJumpThreadingPass::run(), llvm::DivRemPairsPass::run(), llvm::DominanceFrontierAnalysis::run(), llvm::DominanceFrontierPrinterPass::run(), llvm::DominatorTreePrinterPass::run(), llvm::DominatorTreeVerifierPass::run(), llvm::DSEPass::run(), llvm::DwarfEHPreparePass::run(), llvm::dxil::ShaderFlagsAnalysisPrinter::run(), llvm::DXILResourcePrinterPass::run(), llvm::EarlyCSEPass::run(), llvm::ExpandMemCmpPass::run(), llvm::ExpandReductionsPass::run(), llvm::ExpandVectorPredicationPass::run(), llvm::FixIrreduciblePass::run(), llvm::FlattenCFGPass::run(), llvm::Float2IntPass::run(), llvm::FunctionAnalysisManagerCGSCCProxy::run(), llvm::FunctionPropertiesPrinterPass::run(), llvm::FunctionToLoopPassAdaptor::run(), llvm::FunctionToMachineFunctionPassAdaptor::run(), llvm::GCFunctionAnalysis::run(), llvm::GCLoweringPass::run(), llvm::GCOVProfilerPass::run(), llvm::GlobalOptPass::run(), llvm::GlobalsAA::run(), llvm::GuardWideningPass::run(), llvm::GVNHoistPass::run(), llvm::GVNPass::run(), llvm::HardwareLoopsPass::run(), llvm::HipStdParAcceleratorCodeSelectionPass::run(), llvm::HotColdSplittingPass::run(), llvm::HWAddressSanitizerPass::run(), llvm::IndVarSimplifyPass::run(), llvm::InferAddressSpacesPass::run(), llvm::InferAlignmentPass::run(), llvm::InferFunctionAttrsPass::run(), llvm::InjectTLIMappings::run(), llvm::InlineAdvisorAnalysisPrinterPass::run(), llvm::InlineCostAnnotationPrinterPass::run(), llvm::InlinerPass::run(), llvm::InlineSizeEstimatorAnalysisPrinterPass::run(), llvm::InstCombinePass::run(), llvm::InstrProfilingLoweringPass::run(), llvm::InstSimplifyPass::run(), llvm::InterleavedAccessPass::run(), llvm::InterleavedLoadCombinePass::run(), llvm::IPSCCPPass::run(), llvm::IRCEPass::run(), llvm::IROutlinerPass::run(), llvm::IRSimilarityAnalysisPrinterPass::run(), llvm::IVUsersPrinterPass::run(), llvm::JumpTableToSwitchPass::run(), llvm::JumpThreadingPass::run(), llvm::LazyCallGraphAnalysis::run(), llvm::LazyCallGraphDOTPrinterPass::run(), llvm::LazyCallGraphPrinterPass::run(), llvm::LazyValueAnalysis::run(), llvm::LazyValueInfoPrinterPass::run(), llvm::LCSSAPass::run(), llvm::LibCallsShrinkWrapPass::run(), llvm::LintPass::run(), llvm::LiveIntervalsAnalysis::run(), llvm::LiveIntervalsPrinterPass::run(), llvm::LiveVariablesPrinterPass::run(), llvm::LoadStoreVectorizerPass::run(), llvm::LoopAccessAnalysis::run(), llvm::LoopAccessInfoPrinterPass::run(), llvm::LoopAnalysis::run(), llvm::LoopDataPrefetchPass::run(), llvm::LoopDistributePass::run(), llvm::LoopExtractorPass::run(), llvm::LoopFusePass::run(), llvm::LoopLoadEliminationPass::run(), llvm::LoopPrinterPass::run(), llvm::LoopSimplifyPass::run(), llvm::LoopSinkPass::run(), llvm::LoopStrengthReducePass::run(), llvm::LoopUnrollPass::run(), llvm::LoopVectorizePass::run(), llvm::LoopVerifierPass::run(), llvm::LoopVersioningPass::run(), llvm::LowerAllowCheckPass::run(), llvm::LowerConstantIntrinsicsPass::run(), llvm::LowerMatrixIntrinsicsPass::run(), llvm::LowerSwitchPass::run(), llvm::MachineBlockFrequencyAnalysis::run(), llvm::MachineBlockFrequencyPrinterPass::run(), llvm::MachineBranchProbabilityPrinterPass::run(), llvm::MachineDominatorTreePrinterPass::run(), llvm::MachineFunctionAnalysis::run(), llvm::MachineLoopAnalysis::run(), llvm::MachineLoopPrinterPass::run(), llvm::MachineOptimizationRemarkEmitterAnalysis::run(), llvm::MachinePostDominatorTreePrinterPass::run(), llvm::MemCpyOptPass::run(), llvm::MemoryDependenceAnalysis::run(), llvm::MemorySanitizerPass::run(), llvm::MemorySSAAnalysis::run(), llvm::MemorySSAPrinterPass::run(), llvm::MemorySSAVerifierPass::run(), llvm::MemorySSAWalkerPrinterPass::run(), llvm::MemProfContextDisambiguation::run(), llvm::MemProfUsePass::run(), llvm::MergedLoadStoreMotionPass::run(), llvm::MergeICmpsPass::run(), llvm::MetaRenamerPass::run(), llvm::ModuleInlinerPass::run(), llvm::ModuleInlinerWrapperPass::run(), llvm::ModuleSummaryIndexAnalysis::run(), llvm::ModuleToFunctionPassAdaptor::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor::run(), llvm::MoveAutoInitPass::run(), llvm::MustBeExecutedContextPrinterPass::run(), llvm::MustExecutePrinterPass::run(), llvm::NaryReassociatePass::run(), llvm::NewGVNPass::run(), llvm::NumericalStabilitySanitizerPass::run(), llvm::ObjCARCContractPass::run(), llvm::ObjCARCOptPass::run(), llvm::OpenMPOptCGSCCPass::run(), llvm::OpenMPOptPass::run(), llvm::OptimizationRemarkEmitterAnalysis::run(), llvm::PAEvalPass::run(), llvm::PartialInlinerPass::run(), llvm::PartiallyInlineLibCallsPass::run(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), llvm::PGOForceFunctionAttrsPass::run(), llvm::PGOIndirectCallPromotion::run(), llvm::PGOInstrumentationGen::run(), llvm::PGOInstrumentationUse::run(), llvm::PGOMemOPSizeOpt::run(), llvm::PhiValuesPrinterPass::run(), llvm::PlaceSafepointsPass::run(), llvm::PostDominatorTreePrinterPass::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::PredicateInfoPrinterPass::run(), llvm::PredicateInfoVerifierPass::run(), llvm::PreISelIntrinsicLoweringPass::run(), llvm::PrintModulePass::run(), llvm::ProfileSummaryPrinterPass::run(), llvm::PromotePass::run(), llvm::PseudoProbeUpdatePass::run(), llvm::RecomputeGlobalsAAPass::run(), llvm::RegionInfoAnalysis::run(), llvm::RegionInfoPrinterPass::run(), llvm::RegionInfoVerifierPass::run(), llvm::RegToMemPass::run(), llvm::RelLookupTableConverterPass::run(), llvm::ReplaceWithVeclib::run(), llvm::ReversePostOrderFunctionAttrsPass::run(), llvm::RewriteStatepointsForGC::run(), llvm::SafepointIRVerifierPass::run(), llvm::SafeStackPass::run(), llvm::SampleProfileLoaderPass::run(), llvm::SanitizerCoveragePass::run(), llvm::ScalarEvolutionAnalysis::run(), llvm::ScalarEvolutionPrinterPass::run(), llvm::ScalarEvolutionVerifierPass::run(), llvm::ScalarizeMaskedMemIntrinPass::run(), llvm::ScalarizerPass::run(), llvm::SCCPPass::run(), llvm::SCEVAA::run(), llvm::SeparateConstOffsetFromGEPPass::run(), llvm::ShadowStackGCLoweringPass::run(), llvm::SimpleLoopUnswitchPass::run(), llvm::SimplifyCFGPass::run(), llvm::SinkingPass::run(), llvm::SlotIndexesPrinterPass::run(), llvm::SLPVectorizerPass::run(), llvm::SpeculativeExecutionPass::run(), llvm::SPIRVConvergenceRegionAnalysis::run(), llvm::SROAPass::run(), llvm::StackProtectorPass::run(), llvm::StackSafetyAnalysis::run(), llvm::StackSafetyGlobalAnalysis::run(), llvm::StackSafetyGlobalPrinterPass::run(), llvm::StackSafetyPrinterPass::run(), llvm::StraightLineStrengthReducePass::run(), llvm::StructurizeCFGPass::run(), llvm::SyntheticCountsPropagation::run(), llvm::TailCallElimPass::run(), llvm::ThinLTOBitcodeWriterPass::run(), llvm::ThreadSanitizerPass::run(), llvm::TLSVariableHoistPass::run(), llvm::TypePromotionPass::run(), llvm::UniformityInfoAnalysis::run(), llvm::UniformityInfoPrinterPass::run(), llvm::UnifyLoopExitsPass::run(), llvm::VectorCombinePass::run(), llvm::VerifierPass::run(), llvm::VerifierPass::run(), llvm::WarnMissedTransformationsPass::run(), llvm::WholeProgramDevirtPass::run(), runCGProfilePass(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::runWithLoopNestPasses(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::runWithoutLoopNestPasses(), shouldRunOnFunction(), llvm::InlineAdvisorAnalysis::Result::tryCreate(), updateCGAndAnalysisManagerForPass(), and updateNewSCCFunctionAnalyses().
invalidate()
template<typename IRUnitT , typename... ExtraArgTs> void llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate (IRUnitT & IR, const PreservedAnalyses & PA) inline
Invalidate cached analyses for an IR unit.
Walk through all of the analyses pertaining to this unit of IR and invalidate them, unless they are preserved by the PreservedAnalyses set.
Definition at line 172 of file PassManagerImpl.h.
References llvm::PreservedAnalyses::allAnalysesInSetPreserved(), and IR.
Referenced by incorporateNewSCCRange(), llvm::FunctionAnalysisManagerCGSCCProxy::Result::invalidate(), llvm::MLInlineAdvisor::onSuccessfulInlining(), llvm::DebugifyEachInstrumentation::registerCallbacks(), llvm::ArgumentPromotionPass::run(), llvm::CGSCCToFunctionPassAdaptor::run(), llvm::CoroCleanupPass::run(), llvm::DevirtSCCRepeatedPass::run(), llvm::FunctionToLoopPassAdaptor::run(), llvm::FunctionToMachineFunctionPassAdaptor::run(), llvm::GlobalOptPass::run(), llvm::InlinerPass::run(), llvm::IRCEPass::run(), llvm::ModuleToFunctionPassAdaptor::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor::run(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), llvm::PostOrderFunctionAttrsPass::run(), runAttributorLightOnFunctions(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::runWithLoopNestPasses(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::runWithoutLoopNestPasses(), updateCGAndAnalysisManagerForPass(), and updateNewSCCFunctionAnalyses().
operator=()
template<typename IRUnitT , typename... ExtraArgTs> AnalysisManager< IRUnitT, ExtraArgTs... > & llvm::AnalysisManager< IRUnitT, ExtraArgTs >::operator= (AnalysisManager< IRUnitT, ExtraArgTs > &&) inline default
registerPass()
template<typename IRUnitT , typename... ExtraArgTs> template<typename PassBuilderT > bool llvm::AnalysisManager< IRUnitT, ExtraArgTs >::registerPass (PassBuilderT && PassBuilder) inline
Register an analysis pass with the manager.
The parameter is a callable whose result is an analysis pass. This allows passing in a lambda to construct the analysis.
The analysis type to register is the type returned by calling the PassBuilder argument. If that type has already been registered, then the argument will not be called and this function will return false. Otherwise, we register the analysis returned by calling PassBuilder(), and this function returns true.
(Note: Although the return value of this function indicates whether or not an analysis was previously registered, there intentionally isn't a way to query this directly. Instead, you should just register all the analyses you might want and let this class run them lazily. This idiom lets us minimize the number of times we have to look up analyses in our hashtable.)
Definition at line 467 of file PassManager.h.
Referenced by llvm::OpenMPIRBuilder::applySimd(), computeHeuristicUnrollFactor(), llvm::PassBuilder::crossRegisterProxies(), eliminateDeadCode(), llvm::lintFunction(), llvm::PreservedCFGCheckerInstrumentation::registerCallbacks(), llvm::PassBuilder::registerFunctionAnalyses(), and runNewPMPasses().
verifyNotInvalidated()
template<typename IRUnitT , typename... ExtraArgTs> template<typename PassT > void llvm::AnalysisManager< IRUnitT, ExtraArgTs >::verifyNotInvalidated (IRUnitT & IR, typename PassT::Result * Result) const inline
Verify that the given Result cannot be invalidated, assert otherwise.
Definition at line 441 of file PassManager.h.
References assert(), IR, and llvm::PreservedAnalyses::none().
The documentation for this class was generated from the following files:
include/llvm/Analysis/InstructionSimplify.h
include/llvm/CodeGen/MachineBasicBlock.h
include/llvm/CodeGen/MIRParser/MIRParser.h
include/llvm/IR/PassManager.h
include/llvm/IR/PassManagerInternal.h
include/llvm/IR/PassManagerImpl.h