LLVM: llvm::VPRecipeBuilder Class Reference
llvm::VPRecipeBuilder Class Reference
Helper class to create VPRecipies from IR instructions.
#include "Transforms/Vectorize/VPRecipeBuilder.h"
Public Member Functions
VPRecipeBuilder (VPlan &Plan, Loop *OrigLoop, const TargetLibraryInfo *TLI, LoopVectorizationLegality *Legal, LoopVectorizationCostModel &CM, PredicatedScalarEvolution &PSE, VPBuilder &Builder)
VPRecipeBase * tryToCreateWidenRecipe (Instruction *Instr, ArrayRef< VPValue * > Operands, VFRange &Range, VPBasicBlock *VPBB)
Create and return a widened recipe for I if one can be created within the given VF Range.
void setRecipe (Instruction *I, VPRecipeBase *R)
Set the recipe created for given ingredient.
void createHeaderMask ()
Create the mask for the vector loop header block.
void createBlockInMask (BasicBlock *BB)
A helper function that computes the predicate of the block BB, assuming that the header block of the loop is set to True or the loop mask when tail folding.
VPValue * getBlockInMask (BasicBlock *BB) const
Returns the entry mask for the block BB.
VPValue * createEdgeMask (BasicBlock *Src, BasicBlock *Dst)
A helper function that computes the predicate of the edge between SRC and DST.
VPValue * getEdgeMask (BasicBlock *Src, BasicBlock *Dst) const
A helper that returns the previously computed predicate of the edge between SRC and DST.
VPRecipeBase * getRecipe (Instruction *I)
Return the recipe created for given ingredient.
VPReplicateRecipe * handleReplication (Instruction *I, VFRange &Range)
Build a VPReplicationRecipe for I.
void fixHeaderPhis ()
Add the incoming values from the backedge to reduction & first-order recurrence cross-iteration phis.
iterator_range< mapped_iterator< Use *, std::function< VPValue *(Value *)> > > mapToVPValues (User::op_range Operands)
Returns a range mapping the values of the range Operands to their corresponding VPValues.
VPValue * getVPValueOrAddLiveIn (Value *V, VPlan &Plan)
Detailed Description
Helper class to create VPRecipies from IR instructions.
Definition at line 25 of file VPRecipeBuilder.h.
Constructor & Destructor Documentation
VPRecipeBuilder()
llvm::VPRecipeBuilder::VPRecipeBuilder (VPlan & Plan, Loop * OrigLoop, const TargetLibraryInfo * TLI, LoopVectorizationLegality * Legal, LoopVectorizationCostModel & CM, PredicatedScalarEvolution & PSE, VPBuilder & Builder) inline
Definition at line 106 of file VPRecipeBuilder.h.
References llvm::IRSimilarity::Legal.
Member Function Documentation
createBlockInMask()
void VPRecipeBuilder::createBlockInMask (BasicBlock * BB)
A helper function that computes the predicate of the block BB, assuming that the header block of the loop is set to True or the loop mask when tail folding.
Definition at line 7841 of file LoopVectorize.cpp.
References assert(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), createEdgeMask(), llvm::LoopBase< BlockT, LoopT >::getHeader(), and llvm::predecessors().
createEdgeMask()
VPValue * VPRecipeBuilder::createEdgeMask (BasicBlock * Src, BasicBlock * Dst)
A helper function that computes the predicate of the edge between SRC and DST.
Definition at line 7755 of file LoopVectorize.cpp.
References assert(), llvm::dyn_cast(), getBlockInMask(), llvm::BranchInst::getCondition(), llvm::Instruction::getDebugLoc(), llvm::BranchInst::getSuccessor(), getVPValueOrAddLiveIn(), llvm::is_contained(), llvm::BranchInst::isConditional(), llvm::LoopBase< BlockT, LoopT >::isLoopExiting(), and llvm::predecessors().
Referenced by createBlockInMask().
createHeaderMask()
void VPRecipeBuilder::createHeaderMask ()
Create the mask for the vector loop header block.
Definition at line 7806 of file LoopVectorize.cpp.
References llvm::LoopVectorizationCostModel::foldTailByMasking(), llvm::VPlan::getCanonicalIV(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::VPBasicBlock::getFirstNonPhi(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::VPlan::getOrCreateBackedgeTakenCount(), llvm::VPlan::getVectorLoopRegion(), llvm::CmpInst::ICMP_ULE, llvm::VPBasicBlock::insert(), and IV.
fixHeaderPhis()
void VPRecipeBuilder::fixHeaderPhis ()
Add the incoming values from the backedge to reduction & first-order recurrence cross-iteration phis.
Definition at line 8176 of file LoopVectorize.cpp.
References llvm::cast(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), getRecipe(), and llvm::VPDef::getVPSingleValue().
getBlockInMask()
VPValue * VPRecipeBuilder::getBlockInMask (BasicBlock * BB) const
Returns the entry mask for the block BB.
Definition at line 7833 of file LoopVectorize.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find().
Referenced by createEdgeMask(), and handleReplication().
getEdgeMask()
VPValue * VPRecipeBuilder::getEdgeMask (BasicBlock * Src, BasicBlock * Dst) const
A helper that returns the previously computed predicate of the edge between SRC and DST.
Definition at line 7795 of file LoopVectorize.cpp.
References assert(), llvm::is_contained(), and llvm::predecessors().
getRecipe()
VPRecipeBase * llvm::VPRecipeBuilder::getRecipe (Instruction * I) inline
Return the recipe created for given ingredient.
Definition at line 146 of file VPRecipeBuilder.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), and I.
Referenced by fixHeaderPhis().
getVPValueOrAddLiveIn()
VPValue * llvm::VPRecipeBuilder::getVPValueOrAddLiveIn (Value * V, VPlan & Plan) inline
Definition at line 168 of file VPRecipeBuilder.h.
References llvm::dyn_cast(), llvm::VPlan::getOrAddLiveIn(), I, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
Referenced by createEdgeMask().
handleReplication()
VPReplicateRecipe * VPRecipeBuilder::handleReplication (Instruction * I, VFRange & Range)
Build a VPReplicationRecipe for I.
If it is predicated, add the mask as last operand. Range.End may be decreased to ensure same recipe behavior from Range.Start to Range.End.
Definition at line 8186 of file LoopVectorize.cpp.
References assert(), llvm::cast(), llvm::dbgs(), getBlockInMask(), llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), getIntrinsicID(), I, llvm::isa(), llvm::LoopVectorizationCostModel::isPredicatedInst(), llvm::LoopVectorizationCostModel::isUniformAfterVectorization(), LLVM_DEBUG, mapToVPValues(), and Range.
mapToVPValues()
iterator_range< mapped_iterator< Use *, std::function< VPValue *(Value *)> > > VPRecipeBuilder::mapToVPValues (User::op_range Operands)
Returns a range mapping the values of the range Operands to their corresponding VPValues.
Definition at line 7744 of file LoopVectorize.cpp.
References llvm::dyn_cast(), llvm::VPlan::getOrAddLiveIn(), I, llvm::map_range(), and Operands.
Referenced by handleReplication().
setRecipe()
void llvm::VPRecipeBuilder::setRecipe (Instruction * I, VPRecipeBase * R) inline
Set the recipe created for given ingredient.
Definition at line 120 of file VPRecipeBuilder.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::contains(), and I.
tryToCreateWidenRecipe()
VPRecipeBase * VPRecipeBuilder::tryToCreateWidenRecipe (Instruction * Instr, ArrayRef< VPValue * > Operands, VFRange & Range, VPBasicBlock * VPBB)
Create and return a widened recipe for I if one can be created within the given VF Range.
Definition at line 8249 of file LoopVectorize.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), GEP, llvm::LoopVectorizationPlanner::getDecisionAndClampRange(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::Instruction::getOpcode(), llvm::RecurrenceDescriptor::getRecurrenceStartValue(), llvm::LoopVectorizationLegality::getReductionVars(), llvm::Value::getType(), llvm::isa(), llvm::LoopVectorizationLegality::isFixedOrderRecurrence(), llvm::LoopVectorizationCostModel::isInLoopReduction(), llvm::LoopVectorizationLegality::isReductionVariable(), llvm::ElementCount::isScalar(), llvm::make_range(), Operands, Range, and llvm::LoopVectorizationCostModel::useOrderedReductions().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPRecipeBuilder.h
lib/Transforms/Vectorize/LoopVectorize.cpp