LLVM: llvm::logicalview::LVSplitContext Class Reference
llvm::logicalview::LVSplitContext Class Reference final
#include "llvm/DebugInfo/LogicalView/Core/LVReader.h"
Public Member Functions
LVSplitContext ()=default
LVSplitContext (const LVSplitContext &)=delete
LVSplitContext & operator= (const LVSplitContext &)=delete
~LVSplitContext ()=default
Error createSplitFolder (StringRef Where)
std::error_code open (std::string Name, std::string Extension, raw_ostream &OS)
void close ()
std::string getLocation () const
raw_fd_ostream & os ()
Detailed Description
Definition at line 33 of file LVReader.h.
Constructor & Destructor Documentation
LVSplitContext() [1/2]
llvm::logicalview::LVSplitContext::LVSplitContext () default
LVSplitContext() [2/2]
llvm::logicalview::LVSplitContext::LVSplitContext (const LVSplitContext &) delete
~LVSplitContext()
llvm::logicalview::LVSplitContext::~LVSplitContext () default
Member Function Documentation
close()
void llvm::logicalview::LVSplitContext::close () inline
Definition at line 46 of file LVReader.h.
Referenced by llvm::logicalview::LVScope::doPrint(), and llvm::logicalview::LVScopeRoot::doPrintMatches().
createSplitFolder()
Error LVSplitContext::createSplitFolder (StringRef Where)
Definition at line 113 of file LVReader.cpp.
References llvm::sys::fs::create_directories(), llvm::createStringError(), llvm::codeview::EC, and llvm::Error::success().
getLocation()
std::string llvm::logicalview::LVSplitContext::getLocation () const inline
Definition at line 53 of file LVReader.h.
open()
std::error_code LVSplitContext::open (std::string Name, std::string Extension, raw_ostream & OS)
Definition at line 132 of file LVReader.cpp.
References assert(), llvm::codeview::EC, llvm::logicalview::flattenedFilePath(), llvm::logicalview::Name, and llvm::sys::fs::OF_None.
operator=()
LVSplitContext & llvm::logicalview::LVSplitContext::operator= (const LVSplitContext &) delete
os()
raw_fd_ostream & llvm::logicalview::LVSplitContext::os () inline
Definition at line 54 of file LVReader.h.
Referenced by llvm::logicalview::LVScope::doPrint(), and llvm::logicalview::LVScopeRoot::doPrintMatches().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Core/LVReader.h
lib/DebugInfo/LogicalView/Core/LVReader.cpp