LLVM: llvm::pdb::InputFile Class Reference
llvm::pdb::InputFile Class Reference
#include "llvm/DebugInfo/PDB/Native/InputFile.h"
Public Member Functions
InputFile (PDBFile *Pdb)
InputFile (object::COFFObjectFile *Obj)
InputFile (MemoryBuffer *Buffer)
~InputFile ()
InputFile (InputFile &&Other)=default
PDBFile & pdb ()
const PDBFile & pdb () const
object::COFFObjectFile & obj ()
const object::COFFObjectFile & obj () const
MemoryBuffer & unknown ()
const MemoryBuffer & unknown () const
StringRef getFilePath () const
bool hasTypes () const
bool hasIds () const
codeview::LazyRandomTypeCollection & types ()
codeview::LazyRandomTypeCollection & ids ()
iterator_range< SymbolGroupIterator > symbol_groups ()
SymbolGroupIterator symbol_groups_begin ()
SymbolGroupIterator symbol_groups_end ()
bool isPdb () const
bool isObj () const
bool isUnknown () const
Static Public Member Functions
static Expected< InputFile > open (StringRef Path, bool AllowUnknownFile=false)
Detailed Description
Definition at line 39 of file InputFile.h.
Constructor & Destructor Documentation
InputFile() [1/4]
llvm::pdb::InputFile::InputFile (PDBFile * Pdb) inline
Definition at line 57 of file InputFile.h.
InputFile() [2/4]
llvm::pdb::InputFile::InputFile (object::COFFObjectFile * Obj) inline
Definition at line 58 of file InputFile.h.
InputFile() [3/4]
llvm::pdb::InputFile::InputFile (MemoryBuffer * Buffer) inline
Definition at line 59 of file InputFile.h.
~InputFile()
InputFile::~InputFile () default
InputFile() [4/4]
llvm::pdb::InputFile::InputFile (InputFile && Other) default
Member Function Documentation
getFilePath()
StringRef InputFile::getFilePath () const
Definition at line 379 of file InputFile.cpp.
References assert(), llvm::MemoryBuffer::getBufferIdentifier(), llvm::object::Binary::getFileName(), llvm::pdb::PDBFile::getFilePath(), isObj(), isPdb(), isUnknown(), obj(), pdb(), and unknown().
hasIds()
bool InputFile::hasIds () const
Definition at line 400 of file InputFile.cpp.
References llvm::pdb::PDBFile::hasPDBIpiStream(), isObj(), and pdb().
hasTypes()
bool InputFile::hasTypes () const
Definition at line 388 of file InputFile.cpp.
References llvm::pdb::PDBFile::hasPDBTpiStream(), isDebugTSection(), isPdb(), obj(), pdb(), and sections.
ids()
codeview::LazyRandomTypeCollection & InputFile::ids ()
Definition at line 461 of file InputFile.cpp.
References isObj(), pdb(), and types().
isObj()
bool InputFile::isObj () const
Definition at line 408 of file InputFile.cpp.
References llvm::isa().
Referenced by getFilePath(), hasIds(), ids(), isMyCode(), obj(), and obj().
isPdb()
bool InputFile::isPdb () const
Definition at line 406 of file InputFile.cpp.
References llvm::isa().
Referenced by getFilePath(), llvm::pdb::SymbolGroup::getPdbModuleStream(), hasTypes(), pdb(), and pdb().
isUnknown()
bool InputFile::isUnknown () const
Definition at line 412 of file InputFile.cpp.
References llvm::isa().
Referenced by getFilePath(), unknown(), and unknown().
obj() [1/2]
object::COFFObjectFile & InputFile::obj ()
Definition at line 359 of file InputFile.cpp.
References assert(), llvm::cast(), and isObj().
Referenced by getFilePath(), and hasTypes().
obj() [2/2]
const object::COFFObjectFile & InputFile::obj () const
Definition at line 364 of file InputFile.cpp.
References assert(), llvm::cast(), and isObj().
open()
Expected< InputFile > InputFile::open (StringRef Path, bool AllowUnknownFile = false) static
Definition at line 301 of file InputFile.cpp.
References llvm::cast(), llvm::file_magic::coff_object, llvm::object::createBinary(), llvm::codeview::EC, llvm::sys::fs::exists(), llvm::formatv(), llvm::MemoryBuffer::getFile(), llvm::identify_magic(), llvm::inconvertibleErrorCode(), llvm::pdb::loadDataForPDB(), llvm::make_error(), llvm::pdb::Native, llvm::pdb::Path, llvm::file_magic::pdb, and llvm::Expected< T >::takeError().
pdb() [1/2]
PDBFile & InputFile::pdb ()
Definition at line 349 of file InputFile.cpp.
References assert(), llvm::cast(), and isPdb().
Referenced by getFilePath(), hasIds(), hasTypes(), and ids().
pdb() [2/2]
const PDBFile & InputFile::pdb () const
Definition at line 354 of file InputFile.cpp.
References assert(), llvm::cast(), and isPdb().
symbol_groups()
iterator_range< SymbolGroupIterator > InputFile::symbol_groups ()
Definition at line 471 of file InputFile.cpp.
References llvm::make_range(), symbol_groups_begin(), and symbol_groups_end().
symbol_groups_begin()
SymbolGroupIterator InputFile::symbol_groups_begin ()
Definition at line 476 of file InputFile.cpp.
Referenced by symbol_groups().
symbol_groups_end()
SymbolGroupIterator InputFile::symbol_groups_end ()
Definition at line 480 of file InputFile.cpp.
Referenced by symbol_groups().
types()
codeview::LazyRandomTypeCollection & InputFile::types ()
Definition at line 457 of file InputFile.cpp.
Referenced by ids().
unknown() [1/2]
MemoryBuffer & InputFile::unknown ()
Definition at line 369 of file InputFile.cpp.
References assert(), llvm::cast(), and isUnknown().
Referenced by getFilePath().
unknown() [2/2]
const MemoryBuffer & InputFile::unknown () const
Definition at line 374 of file InputFile.cpp.
References assert(), llvm::cast(), and isUnknown().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/InputFile.h
lib/DebugInfo/PDB/Native/InputFile.cpp