LLVM: llvm::DIScope Class Reference
llvm::DIScope Class Reference
Base class for scope-like contexts.
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
DIFile * getFile () const
StringRef getFilename () const
StringRef getDirectory () const
std::optional< StringRef > getSource () const
StringRef getName () const
DIScope * getScope () const
Metadata * getRawFile () const
Return the raw underlying file.
Public Member Functions inherited from llvm::DINode
dwarf::Tag getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
bool isReplaceable () const
bool isAlwaysReplaceable () const
unsigned getNumTemporaryUses () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
void dumpTree () const
User-friendly dump in tree shape.
void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static DIFlags getFlag (StringRef Flag)
static StringRef getFlagString (DIFlags Flag)
static DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
static MDNode * getMergedProfMetadata (MDNode *A, MDNode *B, const Instruction *AInstr, const Instruction *BInstr)
Merge !prof metadata from two instructions.
Protected Member Functions
DIScope (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops)
~DIScope ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~DINode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~MDNode ()=default
void * operator new (size_t Size, size_t NumOps, StorageType Storage)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Additional Inherited Members
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic , FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range<op_iterator>
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range<MDOperand *>
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Base class for scope-like contexts.
Base class for lexical scopes and types (which are also declaration contexts).
TODO: Separate the concepts of declaration contexts and lexical scopes.
Definition at line 519 of file DebugInfoMetadata.h.
Constructor & Destructor Documentation
DIScope()
llvm::DIScope::DIScope (LLVMContext & C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops) inline protected
Definition at line 521 of file DebugInfoMetadata.h.
~DIScope()
llvm::DIScope::~DIScope () protected default
Member Function Documentation
classof()
static bool llvm::DIScope::classof (const Metadata * MD) inline static
Definition at line 547 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
getDirectory()
StringRef llvm::DIScope::getDirectory () const inline
Definition at line 691 of file DebugInfoMetadata.h.
References F, and getFile().
Referenced by llvm::DiagnosticLocation::getAbsolutePath(), and getFilename().
getFile()
DIFile * llvm::DIScope::getFile () const inline
Definition at line 527 of file DebugInfoMetadata.h.
References llvm::cast_or_null(), and getRawFile().
Referenced by llvm::DwarfUnit::addSourceLine(), llvm::DwarfUnit::applySubprogramDefinitionAttributes(), buildFrameDebugInfo(), llvm::DiagnosticLocation::DiagnosticLocation(), fixupDebugInfoPostExtraction(), getDirectory(), getFilename(), and getSource().
getFilename()
StringRef llvm::DIScope::getFilename () const inline
Definition at line 685 of file DebugInfoMetadata.h.
References F, and getFile().
Referenced by llvm::DiagnosticLocation::getAbsolutePath(), getFilename(), and llvm::DiagnosticLocation::getRelativePath().
getName()
StringRef DIScope::getName () const
Definition at line 368 of file DebugInfoMetadata.cpp.
References assert(), llvm::dyn_cast(), and llvm::isa().
Referenced by llvm::DwarfDebug::addSubprogramNames(), llvm::DwarfUnit::applySubprogramAttributes(), llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition(), fixupDebugInfoPostExtraction(), and getFunctionName().
getRawFile()
Metadata * llvm::DIScope::getRawFile () const inline
Return the raw underlying file.
A DIFile is a DIScope, but it doesn't point at a separate file (it is the file). If this is an DIFile, we need to return this. Otherwise, return the first operand, which is where all other subclasses store their file pointer.
Definition at line 542 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand(), and llvm::isa().
Referenced by getFile().
getScope()
DIScope * DIScope::getScope () const
Definition at line 344 of file DebugInfoMetadata.cpp.
References assert(), llvm::dyn_cast(), and llvm::isa().
Referenced by llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition(), getCommonClassOptions(), llvm::DwarfUnit::getOrCreateSubprogramDIE(), llvm::DwarfUnit::getParentContextString(), getRetainedNodeScope(), llvm::DILocalScope::getSubprogram(), llvm::DILabel::isValidLocationForIntrinsic(), llvm::DILocalVariable::isValidLocationForIntrinsic(), and llvm::DebugInfoFinder::processSubprogram().
getSource()
std::optional< StringRef > llvm::DIScope::getSource () const inline
Definition at line 697 of file DebugInfoMetadata.h.
References F, and getFile().
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp