LLVM: llvm::dwarf_linker::StringPoolEntryInfo Class Reference
llvm::dwarf_linker::StringPoolEntryInfo Class Reference
#include "llvm/DWARFLinker/StringPool.h"
Static Public Member Functions
static uint64_t getHashValue (const StringRef &Key)
static bool isEqual (const StringRef &LHS, const StringRef &RHS)
static StringRef getKey (const StringEntry &KeyData)
static StringEntry * create (const StringRef &Key, llvm::parallel::PerThreadBumpPtrAllocator &Allocator)
Detailed Description
Definition at line 25 of file StringPool.h.
Member Function Documentation
create()
static StringEntry * llvm::dwarf_linker::StringPoolEntryInfo::create (const StringRef & Key, llvm::parallel::PerThreadBumpPtrAllocator & Allocator) inline static
Returns
newly created object of KeyDataTy type.
Definition at line 44 of file StringPool.h.
References llvm::StringMapEntry< T >::create().
getHashValue()
static uint64_t llvm::dwarf_linker::StringPoolEntryInfo::getHashValue (const StringRef & Key) inline static
Returns
Hash value for the specified Key.
Definition at line 28 of file StringPool.h.
References llvm::xxh3_64bits().
getKey()
static StringRef llvm::dwarf_linker::StringPoolEntryInfo::getKey (const StringEntry & KeyData) inline static
Returns
key for the specified KeyData.
Definition at line 38 of file StringPool.h.
References llvm::StringMapEntry< T >::getKey().
isEqual()
static bool llvm::dwarf_linker::StringPoolEntryInfo::isEqual (const StringRef & LHS, const StringRef & RHS) inline static
Returns
true if both LHS and RHS are equal.
Definition at line 33 of file StringPool.h.
References RHS.
The documentation for this class was generated from the following file:
include/llvm/DWARFLinker/StringPool.h