LLVM: llvm::dxil::DXILOpBuilder Class Reference
llvm::dxil::DXILOpBuilder Class Reference
#include "Target/DirectX/DXILOpBuilder.h"
Public Member Functions
DXILOpBuilder (Module &M, IRBuilderBase &B)
CallInst * createDXILOpCall (dxil::OpCode OpCode, Type *ReturnTy, Type *OverloadTy, SmallVector< Value * > Args)
Create an instruction that calls DXIL Op with return type, specified opcode, and call arguments.
Type * getOverloadTy (dxil::OpCode OpCode, FunctionType *FT)
Static Public Member Functions
static const char * getOpCodeName (dxil::OpCode DXILOp)
Detailed Description
Definition at line 29 of file DXILOpBuilder.h.
Constructor & Destructor Documentation
DXILOpBuilder()
llvm::dxil::DXILOpBuilder::DXILOpBuilder (Module & M, IRBuilderBase & B) inline
Definition at line 31 of file DXILOpBuilder.h.
Member Function Documentation
createDXILOpCall()
CallInst * llvm::dxil::DXILOpBuilder::createDXILOpCall (dxil::OpCode OpCode, Type * ReturnTy, Type * OverloadTy, SmallVector< Value * > Args)
Create an instruction that calls DXIL Op with return type, specified opcode, and call arguments.
Parameters
OpCode Opcode of the DXIL Op call constructed
ReturnTy Return type of the DXIL Op call constructed
OverloadTy Overload type of the DXIL Op call constructed
Returns
DXIL Op call constructed
Definition at line 255 of file DXILOpBuilder.cpp.
References constructOverloadName(), llvm::IRBuilderBase::CreateCall(), getDXILOpFunctionType(), getOverloadKind(), OpCodeProperty::OverloadTys, and llvm::report_fatal_error().
Referenced by lowerIntrinsic().
getOpCodeName()
const char * llvm::dxil::DXILOpBuilder::getOpCodeName (dxil::OpCode DXILOp) static
Definition at line 329 of file DXILOpBuilder.cpp.
getOverloadTy()
Type * llvm::dxil::DXILOpBuilder::getOverloadTy (dxil::OpCode OpCode, FunctionType * FT)
Definition at line 279 of file DXILOpBuilder.cpp.
References llvm::cast(), llvm::dxil::CBufferRet, llvm::Type::getContext(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::Type::getHalfTy(), llvm::Type::getInt16Ty(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getInt8Ty(), llvm::FunctionType::getParamType(), llvm::FunctionType::getReturnType(), llvm::Type::getVoidTy(), llvm_unreachable, OpCodeProperty::OverloadParamIndex, OpCodeProperty::OverloadTys, and llvm::dxil::ResourceRet.
Referenced by lowerIntrinsic().
The documentation for this class was generated from the following files:
lib/Target/DirectX/DXILOpBuilder.h
lib/Target/DirectX/DXILOpBuilder.cpp