LLVM: LiveDebugValues::InstrRefBasedLDV Class Reference
LiveDebugValues::InstrRefBasedLDV Class Reference
#include "CodeGen/LiveDebugValues/InstrRefBasedImpl.h"
Public Types
using FragmentInfo = DIExpression::FragmentInfo
using OptFragmentInfo = std::optional<DIExpression::FragmentInfo>
using VarToFragments
using MLocTransferMap = SmallDenseMap<LocIdx, ValueIDNum>
Machine location/value transfer function, a mapping of which locations are assigned which new values.
using LiveIdxT = DenseMap<const MachineBasicBlock *, DbgValue *>
Live in/out structure for the variable values: a per-block map of variables to their values.
using VarAndLoc = std::pair<DebugVariableID, DbgValue>
using InValueT = std::pair<MachineBasicBlock *, DbgValue *>
Type for a live-in value: the predecessor block, and its value.
using LiveInsT = SmallVector<SmallVector<VarAndLoc, 8>, 8>
Vector (per block) of a collection (inner smallvector) of live-ins.
using ScopeToDILocT = DenseMap<const LexicalScope *, const DILocation *>
Mapping from lexical scopes to a DILocation in that scope.
using ScopeToVarsT
Mapping from lexical scopes to variables in that scope.
using ScopeToAssignBlocksT = DenseMap<const LexicalScope *, SmallPtrSet<MachineBasicBlock *, 4>>
Mapping from lexical scopes to blocks where variables in that scope are assigned.
Public Member Functions
InstrRefBasedLDV ()
Default construct and initialize the pass.
LLVM_DUMP_METHOD void dump_mloc_transfer (const MLocTransferMap &mloc_transfer) const
bool isCalleeSaved (LocIdx L) const
bool isCalleeSavedReg (Register R) const
bool hasFoldedStackStore (const MachineInstr &MI)
std::optional< LocIdx > findLocationForMemOperand (const MachineInstr &MI)
DebugVariableMap & getDVMap ()
Friends
class ::InstrRefLDVTest
Detailed Description
Definition at line 1123 of file InstrRefBasedImpl.h.
Member Typedef Documentation
FragmentInfo
using LiveDebugValues::InstrRefBasedLDV::FragmentInfo = DIExpression::FragmentInfo
Definition at line 1127 of file InstrRefBasedImpl.h.
InValueT
using LiveDebugValues::InstrRefBasedLDV::InValueT = std::pair<MachineBasicBlock *, DbgValue *>
Type for a live-in value: the predecessor block, and its value.
Definition at line 1146 of file InstrRefBasedImpl.h.
LiveIdxT
using LiveDebugValues::InstrRefBasedLDV::LiveIdxT = DenseMap<const MachineBasicBlock *, DbgValue *>
Live in/out structure for the variable values: a per-block map of variables to their values.
Definition at line 1141 of file InstrRefBasedImpl.h.
LiveInsT
using LiveDebugValues::InstrRefBasedLDV::LiveInsT = SmallVector<SmallVector<VarAndLoc, 8>, 8>
Vector (per block) of a collection (inner smallvector) of live-ins.
Used as the result type for the variable value dataflow problem.
Definition at line 1150 of file InstrRefBasedImpl.h.
MLocTransferMap
using LiveDebugValues::InstrRefBasedLDV::MLocTransferMap = SmallDenseMap<LocIdx, ValueIDNum>
Machine location/value transfer function, a mapping of which locations are assigned which new values.
Definition at line 1137 of file InstrRefBasedImpl.h.
OptFragmentInfo
using LiveDebugValues::InstrRefBasedLDV::OptFragmentInfo = std::optional<DIExpression::FragmentInfo>
Definition at line 1128 of file InstrRefBasedImpl.h.
ScopeToAssignBlocksT
using LiveDebugValues::InstrRefBasedLDV::ScopeToAssignBlocksT = DenseMap<const LexicalScope *, SmallPtrSet<MachineBasicBlock *, 4>>
Mapping from lexical scopes to blocks where variables in that scope are assigned.
Such blocks aren't necessarily "in" the lexical scope, it's just a block where an assignment happens.
Definition at line 1162 of file InstrRefBasedImpl.h.
ScopeToDILocT
using LiveDebugValues::InstrRefBasedLDV::ScopeToDILocT = DenseMap<const LexicalScope *, const DILocation *>
Mapping from lexical scopes to a DILocation in that scope.
Definition at line 1153 of file InstrRefBasedImpl.h.
ScopeToVarsT
using LiveDebugValues::InstrRefBasedLDV::ScopeToVarsT
Initial value:
      DenseMap<const LexicalScope *, SmallSet<DebugVariableID, 4>>
Mapping from lexical scopes to variables in that scope.
Definition at line 1156 of file InstrRefBasedImpl.h.
VarAndLoc
using LiveDebugValues::InstrRefBasedLDV::VarAndLoc = std::pair<DebugVariableID, DbgValue>
Definition at line 1143 of file InstrRefBasedImpl.h.
VarToFragments
using LiveDebugValues::InstrRefBasedLDV::VarToFragments
Initial value:
      DenseMap<const DILocalVariable *, SmallSet<FragmentInfo, 4>>
Definition at line 1132 of file InstrRefBasedImpl.h.
Constructor & Destructor Documentation
InstrRefBasedLDV()
InstrRefBasedLDV::InstrRefBasedLDV () default
Default construct and initialize the pass.
Member Function Documentation
dump_mloc_transfer()
void InstrRefBasedLDV::dump_mloc_transfer (const MLocTransferMap & mloc_transfer) const
Definition at line 3415 of file InstrRefBasedImpl.cpp.
References llvm::dbgs(), LiveDebugValues::MLocTracker::IDAsString(), LiveDebugValues::MLocTracker::LocIdxToName(), and P.
findLocationForMemOperand()
std::optional< LocIdx > InstrRefBasedLDV::findLocationForMemOperand (const MachineInstr & MI)
Definition at line 1379 of file InstrRefBasedImpl.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), LiveDebugValues::MLocTracker::getSpillIDWithIdx(), LiveDebugValues::MLocTracker::getSpillMLoc(), llvm::LocationSize::getValue(), llvm::LocationSize::hasValue(), MI, and LiveDebugValues::MLocTracker::StackSlotIdxes.
getDVMap()
DebugVariableMap & LiveDebugValues::InstrRefBasedLDV::getDVMap () inline
Definition at line 1530 of file InstrRefBasedImpl.h.
hasFoldedStackStore()
bool LiveDebugValues::InstrRefBasedLDV::hasFoldedStackStore (const MachineInstr & MI) inline
Definition at line 1514 of file InstrRefBasedImpl.h.
References llvm::PseudoSourceValue::FixedStack, and MI.
isCalleeSaved()
bool InstrRefBasedLDV::isCalleeSaved (LocIdx L) const
Definition at line 1343 of file InstrRefBasedImpl.cpp.
References isCalleeSavedReg(), and LiveDebugValues::MLocTracker::LocIdxToLocID.
isCalleeSavedReg()
bool InstrRefBasedLDV::isCalleeSavedReg (Register R) const
Definition at line 1347 of file InstrRefBasedImpl.cpp.
References llvm::MCRegAliasIterator::isValid(), and llvm::BitVector::test().
Referenced by isCalleeSaved().
Friends And Related Symbol Documentation
::InstrRefLDVTest
friend class ::InstrRefLDVTest friend
Definition at line 1125 of file InstrRefBasedImpl.h.
The documentation for this class was generated from the following files:
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.h
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.cpp