LLVM: llvm::BasicBlockSectionsProfileReader Class Reference
llvm::BasicBlockSectionsProfileReader Class Reference
#include "llvm/CodeGen/BasicBlockSectionsProfileReader.h"
Public Member Functions
BasicBlockSectionsProfileReader (const MemoryBuffer *Buf)
BasicBlockSectionsProfileReader ()
bool isFunctionHot (StringRef FuncName) const
std::pair< bool, SmallVector< BBClusterInfo > > getClusterInfoForFunction (StringRef FuncName) const
SmallVector< SmallVector< unsigned > > getClonePathsForFunction (StringRef FuncName) const
Friends
class BasicBlockSectionsProfileReaderWrapperPass
Detailed Description
Definition at line 78 of file BasicBlockSectionsProfileReader.h.
Constructor & Destructor Documentation
BasicBlockSectionsProfileReader() [1/2]
llvm::BasicBlockSectionsProfileReader::BasicBlockSectionsProfileReader (const MemoryBuffer * Buf) inline
Definition at line 81 of file BasicBlockSectionsProfileReader.h.
BasicBlockSectionsProfileReader() [2/2]
llvm::BasicBlockSectionsProfileReader::BasicBlockSectionsProfileReader () inline
Definition at line 84 of file BasicBlockSectionsProfileReader.h.
Member Function Documentation
getClonePathsForFunction()
SmallVector< SmallVector< unsigned > > llvm::BasicBlockSectionsProfileReader::getClonePathsForFunction (StringRef FuncName) const
Referenced by llvm::BasicBlockSectionsProfileReaderWrapperPass::getClonePathsForFunction().
getClusterInfoForFunction()
std::pair< bool, SmallVector< BBClusterInfo > > llvm::BasicBlockSectionsProfileReader::getClusterInfoForFunction (StringRef FuncName) const
Referenced by llvm::BasicBlockSectionsProfileReaderWrapperPass::getClusterInfoForFunction().
isFunctionHot()
bool llvm::BasicBlockSectionsProfileReader::isFunctionHot (StringRef FuncName) const
Referenced by llvm::BasicBlockSectionsProfileReaderWrapperPass::isFunctionHot().
Friends And Related Symbol Documentation
BasicBlockSectionsProfileReaderWrapperPass
friend class BasicBlockSectionsProfileReaderWrapperPass friend
Definition at line 80 of file BasicBlockSectionsProfileReader.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/BasicBlockSectionsProfileReader.h
lib/CodeGen/BasicBlockSectionsProfileReader.cpp