LLVM: llvm::MachineDominatorTreePrinterPass Class Reference
llvm::MachineDominatorTreePrinterPass Class Reference
Machine function pass which print MachineDominatorTree.
#include "llvm/CodeGen/MachineDominators.h"
Public Member Functions
MachineDominatorTreePrinterPass (raw_ostream &OS)
PreservedAnalyses run (MachineFunction &MF, MachineFunctionAnalysisManager &MFAM)
Public Member Functions inherited from llvm::PassInfoMixin< MachineDominatorTreePrinterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< MachineDominatorTreePrinterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Machine function pass which print MachineDominatorTree.
Definition at line 284 of file MachineDominators.h.
Constructor & Destructor Documentation
MachineDominatorTreePrinterPass()
llvm::MachineDominatorTreePrinterPass::MachineDominatorTreePrinterPass (raw_ostream & OS) inline explicit
Definition at line 289 of file MachineDominators.h.
Member Function Documentation
isRequired()
static bool llvm::MachineDominatorTreePrinterPass::isRequired () inline static
Definition at line 292 of file MachineDominators.h.
run()
PreservedAnalyses MachineDominatorTreePrinterPass::run (MachineFunction & MF, MachineFunctionAnalysisManager & MFAM)
Definition at line 80 of file MachineDominators.cpp.
References llvm::PreservedAnalyses::all(), llvm::MachineFunction::getName(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::print().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/MachineDominators.h
lib/CodeGen/MachineDominators.cpp