LLVM: llvm::ExtractGVPass Class Reference
llvm::ExtractGVPass Class Reference
#include "llvm/Transforms/IPO/ExtractGV.h"
Public Member Functions
ExtractGVPass (std::vector< GlobalValue * > &GVs, bool deleteS=true, bool keepConstInit=false)
If deleteS is true, this pass deletes the specified global values.
PreservedAnalyses run (Module &M, ModuleAnalysisManager &)
Public Member Functions inherited from llvm::PassInfoMixin< ExtractGVPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< ExtractGVPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 18 of file ExtractGV.h.
Constructor & Destructor Documentation
ExtractGVPass()
ExtractGVPass::ExtractGVPass (std::vector< GlobalValue * > & GVs, bool deleteS = true, bool keepConstInit = false)
If deleteS is true, this pass deletes the specified global values.
Otherwise, it deletes as much of the module as possible, except for the global values specified.
Definition at line 54 of file ExtractGV.cpp.
Member Function Documentation
run()
PreservedAnalyses ExtractGVPass::run (Module & M, ModuleAnalysisManager &)
Definition at line 59 of file ExtractGV.cpp.
References llvm::Function::Create(), llvm::dyn_cast(), llvm::GlobalValue::ExternalLinkage, F, llvm::make_early_inc_range(), makeVisible(), llvm::PreservedAnalyses::none(), and llvm::Value::replaceAllUsesWith().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/ExtractGV.h
lib/Transforms/IPO/ExtractGV.cpp