LLVM: llvm::XtensaConstantPoolSymbol Class Reference
llvm::XtensaConstantPoolSymbol Class Reference
XtensaConstantPoolSymbol - Xtensa-specific constantpool values for external symbols.
#include "Target/Xtensa/XtensaConstantPoolValue.h"
Public Member Functions
const char * getSymbol () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
bool hasSameValue (XtensaConstantPoolValue *ACPV) override
hasSameValue - Return true if this Xtensa constpool value can share the same constantpool entry as another Xtensa constpool value.
bool isPrivateLinkage ()
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const XtensaConstantPoolSymbol *A) const
Public Member Functions inherited from llvm::XtensaConstantPoolValue
~XtensaConstantPoolValue () override
XtensaCP::XtensaCPModifier getModifier () const
bool hasModifier () const
StringRef getModifierText () const
unsigned getLabelId () const
void setLabelId (unsigned ID)
bool isExtSymbol () const
bool isBlockAddress () const
bool isMachineBasicBlock () const
bool isJumpTable () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
bool equals (const XtensaConstantPoolValue *A) const
void print (raw_ostream &O) const override
print - Implement operator<<
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
virtual unsigned getSizeInBytes (const DataLayout &DL) const
Static Public Member Functions
static XtensaConstantPoolSymbol * Create (LLVMContext &C, const char *S, unsigned ID, bool PrivLinkage, XtensaCP::XtensaCPModifier Modifier=XtensaCP::no_modifier)
static bool classof (const XtensaConstantPoolValue *ACPV)
Additional Inherited Members
Protected Member Functions inherited from llvm::XtensaConstantPoolValue
XtensaConstantPoolValue (Type *Ty, unsigned ID, XtensaCP::XtensaCPKind Kind, XtensaCP::XtensaCPModifier Modifier=XtensaCP::no_modifier)
XtensaConstantPoolValue (LLVMContext &C, unsigned id, XtensaCP::XtensaCPKind Kind, XtensaCP::XtensaCPModifier Modifier=XtensaCP::no_modifier)
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, Align Alignment)
Detailed Description
XtensaConstantPoolSymbol - Xtensa-specific constantpool values for external symbols.
Definition at line 158 of file XtensaConstantPoolValue.h.
Member Function Documentation
addSelectionDAGCSEId()
void XtensaConstantPoolSymbol::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 138 of file XtensaConstantPoolValue.cpp.
References llvm::XtensaConstantPoolValue::addSelectionDAGCSEId().
classof()
static bool llvm::XtensaConstantPoolSymbol::classof (const XtensaConstantPoolValue * ACPV) inline static
Definition at line 186 of file XtensaConstantPoolValue.h.
References llvm::XtensaConstantPoolValue::isExtSymbol().
Create()
XtensaConstantPoolSymbol * XtensaConstantPoolSymbol::Create (LLVMContext & C, const char * S, unsigned ID, bool PrivLinkage, XtensaCP::XtensaCPModifier Modifier = XtensaCP::no_modifier) static
Definition at line 119 of file XtensaConstantPoolValue.cpp.
References llvm::CallingConv::C.
Referenced by llvm::XtensaTargetLowering::LowerCall().
equals()
bool llvm::XtensaConstantPoolSymbol::equals (const XtensaConstantPoolSymbol * A) const inline
Definition at line 190 of file XtensaConstantPoolValue.h.
References A, and llvm::XtensaConstantPoolValue::equals().
getExistingMachineCPValue()
int XtensaConstantPoolSymbol::getExistingMachineCPValue (MachineConstantPool * CP, Align Alignment) override virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 127 of file XtensaConstantPoolValue.cpp.
References llvm::XtensaConstantPoolValue::getExistingMachineCPValueImpl().
getSymbol()
const char * llvm::XtensaConstantPoolSymbol::getSymbol () const inline
Definition at line 171 of file XtensaConstantPoolValue.h.
Referenced by llvm::XtensaAsmPrinter::emitMachineConstantPoolValue().
hasSameValue()
bool XtensaConstantPoolSymbol::hasSameValue (XtensaConstantPoolValue * ACPV) override virtual
hasSameValue - Return true if this Xtensa constpool value can share the same constantpool entry as another Xtensa constpool value.
Reimplemented from llvm::XtensaConstantPoolValue.
Definition at line 132 of file XtensaConstantPoolValue.cpp.
References llvm::dyn_cast(), and llvm::XtensaConstantPoolValue::hasSameValue().
isPrivateLinkage()
bool llvm::XtensaConstantPoolSymbol::isPrivateLinkage () inline
Definition at line 182 of file XtensaConstantPoolValue.h.
Referenced by llvm::XtensaAsmPrinter::emitMachineConstantPoolValue().
print()
void XtensaConstantPoolSymbol::print (raw_ostream & O) const override virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Definition at line 143 of file XtensaConstantPoolValue.cpp.
References llvm::XtensaConstantPoolValue::print().
The documentation for this class was generated from the following files:
lib/Target/Xtensa/XtensaConstantPoolValue.h
lib/Target/Xtensa/XtensaConstantPoolValue.cpp