LLVM: llvm::MCEncodedFragmentWithContents< ContentsSize > Class Template Reference
llvm::MCEncodedFragmentWithContents< ContentsSize > Class Template Reference
Interface implemented by fragments that contain encoded instructions and/or data.
#include "llvm/MC/MCFragment.h"
Public Member Functions
SmallVectorImpl< char > & getContents ()
const SmallVectorImpl< char > & getContents () const
Public Member Functions inherited from llvm::MCEncodedFragment
bool alignToBundleEnd () const
Should this fragment be placed at the end of an aligned bundle?
void setAlignToBundleEnd (bool V)
uint8_t getBundlePadding () const
Get the padding size that must be inserted before this fragment.
void setBundlePadding (uint8_t N)
Set the padding size for this fragment.
const MCSubtargetInfo * getSubtargetInfo () const
Retrieve the MCSubTargetInfo in effect when the instruction was encoded.
void setHasInstructions (const MCSubtargetInfo &STI)
Record that the fragment contains instructions with the MCSubtargetInfo in effect when the instruction was encoded.
Public Member Functions inherited from llvm::MCFragment
MCFragment ()=delete
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
void destroy ()
Destroys the current fragment.
MCFragment * getNext () const
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
const MCSymbol * getAtom () const
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
void dump () const
Protected Member Functions
MCEncodedFragmentWithContents (MCFragment::FragmentType FType, bool HasInstructions)
Protected Member Functions inherited from llvm::MCEncodedFragment
MCEncodedFragment (MCFragment::FragmentType FType, bool HasInstructions)
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType Kind, bool HasInstructions)
Additional Inherited Members
Public Types inherited from llvm::MCFragment
enum FragmentType : uint8_t {
FT_Align , FT_Data , FT_CompactEncodedInst , FT_Fill ,
FT_Nops , FT_Relaxable , FT_Org , FT_Dwarf ,
FT_DwarfFrame , FT_LEB , FT_BoundaryAlign , FT_SymbolId ,
FT_CVInlineLines , FT_CVDefRange , FT_PseudoProbe , FT_Dummy
}
Static Public Member Functions inherited from llvm::MCEncodedFragment
static bool classof (const MCFragment *F)
Protected Attributes inherited from llvm::MCEncodedFragment
const MCSubtargetInfo * STI = nullptr
The MCSubtargetInfo in effect when the instruction was encoded.
Protected Attributes inherited from llvm::MCFragment
bool HasInstructions: 1
bool LinkerRelaxable: 1
Detailed Description
template<unsigned ContentsSize>
class llvm::MCEncodedFragmentWithContents< ContentsSize >
Interface implemented by fragments that contain encoded instructions and/or data.
Definition at line 179 of file MCFragment.h.
Constructor & Destructor Documentation
MCEncodedFragmentWithContents()
template<unsigned ContentsSize> llvm::MCEncodedFragmentWithContents< ContentsSize >::MCEncodedFragmentWithContents (MCFragment::FragmentType FType, bool HasInstructions) inline protected
Definition at line 183 of file MCFragment.h.
Member Function Documentation
getContents() [1/2]
template<unsigned ContentsSize> SmallVectorImpl< char > & llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents () inline
Definition at line 188 of file MCFragment.h.
Referenced by llvm::CodeViewContext::addToStringTable(), llvm::CodeViewContext::encodeDefRange(), llvm::MCAssembler::layout(), llvm::MCLEBFragment::MCLEBFragment(), and writeFragment().
getContents() [2/2]
template<unsigned ContentsSize> const SmallVectorImpl< char > & llvm::MCEncodedFragmentWithContents< ContentsSize >::getContents () const inline
Definition at line 189 of file MCFragment.h.
The documentation for this class was generated from the following file:
include/llvm/MC/MCFragment.h