LLVM: llvm::SelectionDAG::FlagInserter Class Reference
llvm::SelectionDAG::FlagInserter Class Reference
Help to insert SDNodeFlags automatically in transforming.
#include "llvm/CodeGen/SelectionDAG.h"
Public Member Functions
FlagInserter (SelectionDAG &SDAG, SDNodeFlags Flags)
FlagInserter (SelectionDAG &SDAG, SDNode *N)
FlagInserter (const FlagInserter &)=delete
FlagInserter & operator= (const FlagInserter &)=delete
~FlagInserter ()
SDNodeFlags getFlags () const
Detailed Description
Help to insert SDNodeFlags automatically in transforming.
Use RAII to save and resume flags in current scope.
Definition at line 364 of file SelectionDAG.h.
Constructor & Destructor Documentation
FlagInserter() [1/3]
llvm::SelectionDAG::FlagInserter::FlagInserter (SelectionDAG & SDAG, SDNodeFlags Flags) inline
Definition at line 370 of file SelectionDAG.h.
References llvm::SelectionDAG::setFlagInserter().
FlagInserter() [2/3]
llvm::SelectionDAG::FlagInserter::FlagInserter (SelectionDAG & SDAG, SDNode * N) inline
Definition at line 375 of file SelectionDAG.h.
FlagInserter() [3/3]
llvm::SelectionDAG::FlagInserter::FlagInserter (const FlagInserter &) delete
~FlagInserter()
llvm::SelectionDAG::FlagInserter::~FlagInserter () inline
Definition at line 380 of file SelectionDAG.h.
References llvm::SelectionDAG::setFlagInserter().
Member Function Documentation
getFlags()
SDNodeFlags llvm::SelectionDAG::FlagInserter::getFlags () const inline
Definition at line 382 of file SelectionDAG.h.
Referenced by llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), and llvm::SelectionDAG::getNodeIfExists().
operator=()
FlagInserter & llvm::SelectionDAG::FlagInserter::operator= (const FlagInserter &) delete
The documentation for this class was generated from the following file:
include/llvm/CodeGen/SelectionDAG.h