LLVM: llvm::HipStdParAcceleratorCodeSelectionPass Class Reference
llvm::HipStdParAcceleratorCodeSelectionPass Class Reference
#include "llvm/Transforms/HipStdPar/HipStdPar.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &MAM)
Public Member Functions inherited from llvm::PassInfoMixin< HipStdParAcceleratorCodeSelectionPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< HipStdParAcceleratorCodeSelectionPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 27 of file HipStdPar.h.
Member Function Documentation
isRequired()
static bool llvm::HipStdParAcceleratorCodeSelectionPass::isRequired () inline static
Definition at line 32 of file HipStdPar.h.
run()
PreservedAnalyses HipStdParAcceleratorCodeSelectionPass::run (Module & M, ModuleAnalysisManager & MAM)
Definition at line 192 of file HipStdPar.cpp.
References checkIfSupported(), clearModule(), llvm::dyn_cast(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), isAcceleratorExecutionRoot(), MAM, maybeHandleGlobals(), N, llvm::PreservedAnalyses::none(), and removeUnreachableFunctions().
The documentation for this class was generated from the following files:
include/llvm/Transforms/HipStdPar/HipStdPar.h
lib/Transforms/HipStdPar/HipStdPar.cpp