LLVM: llvm::OperandBundleDefT< InputTy > Class Template Reference
llvm::OperandBundleDefT< InputTy > Class Template Reference
A container for an operand bundle being viewed as a set of values rather than a set of uses.
#include "llvm/IR/InstrTypes.h"
Public Types
using input_iterator = typename std::vector<InputTy>::const_iterator
Public Member Functions
OperandBundleDefT (std::string Tag, std::vector< InputTy > Inputs)
OperandBundleDefT (std::string Tag, ArrayRef< InputTy > Inputs)
OperandBundleDefT (const OperandBundleUse &OBU)
ArrayRef< InputTy > inputs () const
size_t input_size () const
input_iterator input_begin () const
input_iterator input_end () const
StringRef getTag () const
Detailed Description
template<typename InputTy>
class llvm::OperandBundleDefT< InputTy >
A container for an operand bundle being viewed as a set of values rather than a set of uses.
Unlike OperandBundleUse, OperandBundleDefT owns the memory it carries, and so it is possible to create and pass around "self-contained" instances of OperandBundleDef and ConstOperandBundleDef.
Definition at line 1189 of file InstrTypes.h.
Member Typedef Documentation
input_iterator
template<typename InputTy > using llvm::OperandBundleDefT< InputTy >::input_iterator = typename std::vector<InputTy>::const_iterator
Definition at line 1206 of file InstrTypes.h.
Constructor & Destructor Documentation
OperandBundleDefT() [1/3]
template<typename InputTy > llvm::OperandBundleDefT< InputTy >::OperandBundleDefT (std::string Tag, std::vector< InputTy > Inputs) inline explicit
Definition at line 1194 of file InstrTypes.h.
OperandBundleDefT() [2/3]
template<typename InputTy > llvm::OperandBundleDefT< InputTy >::OperandBundleDefT (std::string Tag, ArrayRef< InputTy > Inputs) inline explicit
Definition at line 1196 of file InstrTypes.h.
OperandBundleDefT() [3/3]
template<typename InputTy > llvm::OperandBundleDefT< InputTy >::OperandBundleDefT (const OperandBundleUse & OBU) inline explicit
Definition at line 1199 of file InstrTypes.h.
References llvm::append_range(), llvm::OperandBundleUse::getTagName(), and llvm::OperandBundleUse::Inputs.
Member Function Documentation
getTag()
template<typename InputTy > StringRef llvm::OperandBundleDefT< InputTy >::getTag () const inline
Definition at line 1212 of file InstrTypes.h.
Referenced by llvm::CallBase::Create(), and llvm::UpgradeOperandBundles().
input_begin()
template<typename InputTy > input_iterator llvm::OperandBundleDefT< InputTy >::input_begin () const inline
Definition at line 1209 of file InstrTypes.h.
input_end()
template<typename InputTy > input_iterator llvm::OperandBundleDefT< InputTy >::input_end () const inline
Definition at line 1210 of file InstrTypes.h.
input_size()
template<typename InputTy > size_t llvm::OperandBundleDefT< InputTy >::input_size () const inline
Definition at line 1208 of file InstrTypes.h.
inputs()
template<typename InputTy > ArrayRef< InputTy > llvm::OperandBundleDefT< InputTy >::inputs () const inline
Definition at line 1204 of file InstrTypes.h.
Referenced by llvm::UpgradeOperandBundles().
The documentation for this class was generated from the following files:
include/llvm/IR/AutoUpgrade.h
include/llvm/IR/InstrTypes.h