LLVM: llvm::pdb::SymbolCache Class Reference
llvm::pdb::SymbolCache Class Reference
#include "llvm/DebugInfo/PDB/Native/SymbolCache.h"
Public Member Functions
SymbolCache (NativeSession &Session, DbiStream *Dbi)
template<typename ConcreteSymbolT , typename... Args>
SymIndexId createSymbol (Args &&...ConstructorArgs) const
std::unique_ptr< IPDBEnumSymbols > createTypeEnumerator (codeview::TypeLeafKind Kind)
std::unique_ptr< IPDBEnumSymbols > createTypeEnumerator (std::vector< codeview::TypeLeafKind > Kinds)
std::unique_ptr< IPDBEnumSymbols > createGlobalsEnumerator (codeview::SymbolKind Kind)
SymIndexId findSymbolByTypeIndex (codeview::TypeIndex TI) const
template<typename ConcreteSymbolT , typename... Args>
SymIndexId getOrCreateFieldListMember (codeview::TypeIndex FieldListTI, uint32_t Index, Args &&... ConstructorArgs)
SymIndexId getOrCreateGlobalSymbolByOffset (uint32_t Offset)
SymIndexId getOrCreateInlineSymbol (codeview::InlineSiteSym Sym, uint64_t ParentAddr, uint16_t Modi, uint32_t RecordOffset) const
std::unique_ptr< PDBSymbol > findSymbolBySectOffset (uint32_t Sect, uint32_t Offset, PDB_SymType Type)
std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersByVA (uint64_t VA, uint32_t Length) const
std::unique_ptr< PDBSymbolCompiland > getOrCreateCompiland (uint32_t Index)
uint32_t getNumCompilands () const
std::unique_ptr< PDBSymbol > getSymbolById (SymIndexId SymbolId) const
NativeRawSymbol & getNativeSymbolById (SymIndexId SymbolId) const
template<typename ConcreteT >
ConcreteT & getNativeSymbolById (SymIndexId SymbolId) const
std::unique_ptr< IPDBSourceFile > getSourceFileById (SymIndexId FileId) const
SymIndexId getOrCreateSourceFile (const codeview::FileChecksumEntry &Checksum) const
Detailed Description
Definition at line 37 of file SymbolCache.h.
Constructor & Destructor Documentation
SymbolCache()
SymbolCache::SymbolCache (NativeSession & Session, DbiStream * Dbi)
Definition at line 78 of file SymbolCache.cpp.
References llvm::pdb::DbiModuleList::getModuleCount(), and llvm::pdb::DbiStream::modules().
Member Function Documentation
createGlobalsEnumerator()
std::unique_ptr< IPDBEnumSymbols > SymbolCache::createGlobalsEnumerator (codeview::SymbolKind Kind)
Definition at line 106 of file SymbolCache.cpp.
Referenced by llvm::pdb::NativeExeSymbol::findChildren().
createSymbol()
template<typename ConcreteSymbolT , typename... Args> SymIndexId llvm::pdb::SymbolCache::createSymbol (Args &&... ConstructorArgs) const inline
Definition at line 127 of file SymbolCache.h.
Referenced by getOrCreateCompiland(), getOrCreateFieldListMember(), getOrCreateGlobalSymbolByOffset(), and getOrCreateInlineSymbol().
createTypeEnumerator() [1/2]
std::unique_ptr< IPDBEnumSymbols > SymbolCache::createTypeEnumerator (codeview::TypeLeafKind Kind)
Definition at line 89 of file SymbolCache.cpp.
References createTypeEnumerator().
Referenced by createTypeEnumerator(), and llvm::pdb::NativeExeSymbol::findChildren().
createTypeEnumerator() [2/2]
std::unique_ptr< IPDBEnumSymbols > SymbolCache::createTypeEnumerator (std::vector< codeview::TypeLeafKind > Kinds)
Definition at line 94 of file SymbolCache.cpp.
References llvm::consumeError(), llvm::pdb::NativeSession::getPDBFile(), and llvm::pdb::PDBFile::getPDBTpiStream().
findLineNumbersByVA()
std::unique_ptr< IPDBEnumLineNumbers > SymbolCache::findLineNumbersByVA (uint64_t VA, uint32_t Length) const
Definition at line 533 of file SymbolCache.cpp.
References llvm::pdb::NativeSession::addressForVA(), llvm::consumeError(), llvm::pdb::NativeSession::getModuleDebugStream(), getOrCreateSourceFile(), llvm::Length, llvm::pdb::LineNumbers, llvm::codeview::Lines, llvm::pdb::NativeSession::moduleIndexForVA(), llvm::partition_point(), and llvm::Expected< T >::takeError().
findSymbolBySectOffset()
std::unique_ptr< PDBSymbol > SymbolCache::findSymbolBySectOffset (uint32_t Sect, uint32_t Offset, PDB_SymType Type)
Definition at line 314 of file SymbolCache.cpp.
References llvm::pdb::Compiland, llvm::pdb::Function, getOrCreateCompiland(), llvm::pdb::NativeSession::moduleIndexForSectOffset(), llvm::pdb::None, llvm::pdb::Offset, llvm::pdb::PublicSymbol, and Sym.
findSymbolByTypeIndex()
SymIndexId SymbolCache::findSymbolByTypeIndex (codeview::TypeIndex TI) const
Definition at line 158 of file SymbolCache.cpp.
References assert(), llvm::consumeError(), findSymbolByTypeIndex(), llvm::pdb::NativeSession::getPDBFile(), llvm::pdb::PDBFile::getPDBTpiStream(), llvm::codeview::isUdtForwardRef(), llvm::codeview::CVRecord< Kind >::kind(), and llvm::Expected< T >::takeError().
Referenced by findSymbolByTypeIndex(), llvm::pdb::NativeTypeArray::getArrayIndexTypeId(), llvm::pdb::NativeTypeEnum::getBuiltinType(), llvm::pdb::NativeEnumTypes::getChildAtIndex(), llvm::pdb::NativeTypePointer::getClassParentId(), llvm::pdb::NativeTypeEnum::getLength(), llvm::pdb::NativeTypeArray::getTypeId(), llvm::pdb::NativeTypeEnum::getTypeId(), llvm::pdb::NativeTypeFunctionSig::getTypeId(), llvm::pdb::NativeTypePointer::getTypeId(), llvm::pdb::NativeTypeTypedef::getTypeId(), llvm::pdb::NativeTypeUDT::getVirtualTableShapeId(), and llvm::pdb::NativeTypeFunctionSig::initialize().
getNativeSymbolById() [1/2]
NativeRawSymbol & SymbolCache::getNativeSymbolById (SymIndexId SymbolId) const
Definition at line 263 of file SymbolCache.cpp.
Referenced by llvm::pdb::NativeTypeArray::getCount(), getNativeSymbolById(), and llvm::pdb::NativeTypeEnum::getUnderlyingBuiltinType().
getNativeSymbolById() [2/2]
template<typename ConcreteT > ConcreteT & llvm::pdb::SymbolCache::getNativeSymbolById (SymIndexId SymbolId) const inline
Definition at line 190 of file SymbolCache.h.
References getNativeSymbolById().
getNumCompilands()
uint32_t SymbolCache::getNumCompilands () const
Definition at line 267 of file SymbolCache.cpp.
References llvm::pdb::DbiModuleList::getModuleCount(), and llvm::pdb::DbiStream::modules().
Referenced by llvm::pdb::NativeEnumModules::getChildCount().
getOrCreateCompiland()
std::unique_ptr< PDBSymbolCompiland > SymbolCache::getOrCreateCompiland (uint32_t Index)
Definition at line 597 of file SymbolCache.cpp.
References createSymbol(), llvm::pdb::IPDBSession::getConcreteSymbolById(), llvm::pdb::DbiModuleList::getModuleDescriptor(), and llvm::pdb::DbiStream::modules().
Referenced by findSymbolBySectOffset(), and llvm::pdb::NativeEnumModules::getChildAtIndex().
getOrCreateFieldListMember()
template<typename ConcreteSymbolT , typename... Args> SymIndexId llvm::pdb::SymbolCache::getOrCreateFieldListMember (codeview::TypeIndex FieldListTI, uint32_t Index, Args &&... ConstructorArgs) inline
Definition at line 157 of file SymbolCache.h.
References createSymbol(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
getOrCreateGlobalSymbolByOffset()
SymIndexId SymbolCache::getOrCreateGlobalSymbolByOffset (uint32_t Offset)
Definition at line 274 of file SymbolCache.cpp.
References assert(), llvm::cantFail(), createSymbol(), llvm::codeview::SymbolDeserializer::deserializeAs(), llvm::pdb::NativeSession::getPDBFile(), llvm::pdb::PDBFile::getPDBSymbolStream(), llvm::codeview::CVRecord< Kind >::kind(), and llvm::pdb::Offset.
Referenced by llvm::pdb::NativeEnumGlobals::getChildAtIndex().
getOrCreateInlineSymbol()
SymIndexId SymbolCache::getOrCreateInlineSymbol (codeview::InlineSiteSym Sym, uint64_t ParentAddr, uint16_t Modi, uint32_t RecordOffset) const
Definition at line 300 of file SymbolCache.cpp.
References createSymbol(), and Sym.
Referenced by llvm::pdb::NativeFunctionSymbol::findInlineFramesByVA().
getOrCreateSourceFile()
SymIndexId SymbolCache::getOrCreateSourceFile (const codeview::FileChecksumEntry & Checksum) const
Definition at line 625 of file SymbolCache.cpp.
References llvm::codeview::FileChecksumEntry::FileNameOffset.
Referenced by llvm::pdb::NativeInlineSiteSymbol::findInlineeLinesByVA(), and findLineNumbersByVA().
getSourceFileById()
std::unique_ptr< IPDBSourceFile > SymbolCache::getSourceFileById (SymIndexId FileId) const
Definition at line 614 of file SymbolCache.cpp.
References assert(), and llvm::get().
Referenced by llvm::pdb::NativeInlineSiteSymbol::findInlineeLinesByVA().
getSymbolById()
std::unique_ptr< PDBSymbol > SymbolCache::getSymbolById (SymIndexId SymbolId) const
Definition at line 247 of file SymbolCache.cpp.
References assert(), and llvm::pdb::PDBSymbol::create().
Referenced by llvm::pdb::NativeEnumGlobals::getChildAtIndex(), llvm::pdb::NativeEnumSymbols::getChildAtIndex(), and llvm::pdb::NativeEnumTypes::getChildAtIndex().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/SymbolCache.h
lib/DebugInfo/PDB/Native/SymbolCache.cpp