LLVM: TransferTracker::LocationAndQuality Class Reference
TransferTracker::LocationAndQuality Class Reference
Public Member Functions
LocationAndQuality ()
LocationAndQuality (LocIdx L, LocationQuality Q)
LocIdx getLoc () const
LocationQuality getQuality () const
bool isIllegal () const
bool isBest () const
Detailed Description
Definition at line 305 of file InstrRefBasedImpl.cpp.
Constructor & Destructor Documentation
LocationAndQuality() [1/2]
TransferTracker::LocationAndQuality::LocationAndQuality () inline
Definition at line 310 of file InstrRefBasedImpl.cpp.
LocationAndQuality() [2/2]
TransferTracker::LocationAndQuality::LocationAndQuality (LocIdx L, LocationQuality Q) inline
Definition at line 311 of file InstrRefBasedImpl.cpp.
Member Function Documentation
getLoc()
LocIdx TransferTracker::LocationAndQuality::getLoc () const inline
Definition at line 313 of file InstrRefBasedImpl.cpp.
References LiveDebugValues::LocIdx::MakeIllegalLoc().
getQuality()
LocationQuality TransferTracker::LocationAndQuality::getQuality () const inline
Definition at line 318 of file InstrRefBasedImpl.cpp.
Referenced by isBest().
isBest()
bool TransferTracker::LocationAndQuality::isBest () const inline
Definition at line 320 of file InstrRefBasedImpl.cpp.
References TransferTracker::Best, and getQuality().
isIllegal()
bool TransferTracker::LocationAndQuality::isIllegal () const inline
Definition at line 319 of file InstrRefBasedImpl.cpp.
The documentation for this class was generated from the following file:
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.cpp