LLVM: llvm::LoopAccessInfoManager Class Reference
llvm::LoopAccessInfoManager Class Reference
#include "llvm/Analysis/LoopAccessAnalysis.h"
Public Member Functions
LoopAccessInfoManager (ScalarEvolution &SE, AAResults &AA, DominatorTree &DT, LoopInfo &LI, TargetTransformInfo *TTI, const TargetLibraryInfo *TLI)
const LoopAccessInfo & getInfo (Loop &L)
void clear ()
bool invalidate (Function &F, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &Inv)
Detailed Description
Definition at line 844 of file LoopAccessAnalysis.h.
Constructor & Destructor Documentation
LoopAccessInfoManager()
llvm::LoopAccessInfoManager::LoopAccessInfoManager (ScalarEvolution & SE, AAResults & AA, DominatorTree & DT, LoopInfo & LI, TargetTransformInfo * TTI, const TargetLibraryInfo * TLI) inline
Definition at line 857 of file LoopAccessAnalysis.h.
Member Function Documentation
clear()
void LoopAccessInfoManager::clear ()
Definition at line 3079 of file LoopAccessAnalysis.cpp.
References ToRemove.
Referenced by eliminateLoadsAcrossLoops(), and llvm::LoopVectorizePass::runImpl().
getInfo()
const LoopAccessInfo & LoopAccessInfoManager::getInfo (Loop & L)
Definition at line 3070 of file LoopAccessAnalysis.cpp.
Referenced by eliminateLoadsAcrossLoops(), and llvm::LoopFlattenPass::run().
invalidate()
bool LoopAccessInfoManager::invalidate (Function & F, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator & Inv)
Definition at line 3096 of file LoopAccessAnalysis.cpp.
References F, llvm::PreservedAnalyses::getChecker(), and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::Invalidator::invalidate().
The documentation for this class was generated from the following files:
include/llvm/Analysis/LoopAccessAnalysis.h
lib/Analysis/LoopAccessAnalysis.cpp