LLVM: llvm::XtensaTargetELFStreamer Class Reference
llvm::XtensaTargetELFStreamer Class Reference
#include "Target/Xtensa/MCTargetDesc/XtensaTargetStreamer.h"
Public Member Functions
XtensaTargetELFStreamer (MCStreamer &S)
MCELFStreamer & getStreamer ()
void emitLiteral (MCSymbol *LblSym, const MCExpr *Value, bool SwitchLiteralSection, SMLoc L) override
void emitLiteralPosition () override
void startLiteralSection (MCSection *Section) override
Public Member Functions inherited from llvm::XtensaTargetStreamer
XtensaTargetStreamer (MCStreamer &S)
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, uint32_t SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 47 of file XtensaTargetStreamer.h.
Constructor & Destructor Documentation
XtensaTargetELFStreamer()
XtensaTargetELFStreamer::XtensaTargetELFStreamer (MCStreamer & S)
Definition at line 80 of file XtensaTargetStreamer.cpp.
Member Function Documentation
emitLiteral()
void XtensaTargetELFStreamer::emitLiteral (MCSymbol * LblSym, const MCExpr * Value, bool SwitchLiteralSection, SMLoc L) override virtual
Implements llvm::XtensaTargetStreamer.
Definition at line 83 of file XtensaTargetStreamer.cpp.
References llvm::MCStreamer::emitLabel(), llvm::MCStreamer::emitValue(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getCurrentSectionOnly(), getLiteralSectionName(), getStreamer(), llvm::MCStreamer::popSection(), llvm::MCStreamer::pushSection(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_EXECINSTR, llvm::ELF::SHT_PROGBITS, and llvm::MCStreamer::switchSection().
emitLiteralPosition()
void llvm::XtensaTargetELFStreamer::emitLiteralPosition () inline override virtual
Implements llvm::XtensaTargetStreamer.
Definition at line 53 of file XtensaTargetStreamer.h.
getStreamer()
MCELFStreamer & XtensaTargetELFStreamer::getStreamer ()
Definition at line 117 of file XtensaTargetStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
Referenced by emitLiteral(), and startLiteralSection().
startLiteralSection()
void XtensaTargetELFStreamer::startLiteralSection (MCSection * Section) override virtual
Implements llvm::XtensaTargetStreamer.
Definition at line 106 of file XtensaTargetStreamer.cpp.
References Align, llvm::MCStreamer::getContext(), getLiteralSectionName(), llvm::MCSection::getName(), getStreamer(), llvm::MCSection::setAlignment(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_EXECINSTR, and llvm::ELF::SHT_PROGBITS.
The documentation for this class was generated from the following files:
lib/Target/Xtensa/MCTargetDesc/XtensaTargetStreamer.h
lib/Target/Xtensa/MCTargetDesc/XtensaTargetStreamer.cpp