LLVM: llvm::NameAnonGlobalPass Class Reference
llvm::NameAnonGlobalPass Class Reference
Simple pass that provides a name to every anonymous globals.
#include "llvm/Transforms/Utils/NameAnonGlobals.h"
Public Member Functions
NameAnonGlobalPass ()=default
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< NameAnonGlobalPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< NameAnonGlobalPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Simple pass that provides a name to every anonymous globals.
Definition at line 22 of file NameAnonGlobals.h.
Constructor & Destructor Documentation
NameAnonGlobalPass()
llvm::NameAnonGlobalPass::NameAnonGlobalPass () default
Member Function Documentation
isRequired()
static bool llvm::NameAnonGlobalPass::isRequired () inline static
Definition at line 28 of file NameAnonGlobals.h.
run()
PreservedAnalyses NameAnonGlobalPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 82 of file NameAnonGlobals.cpp.
References llvm::PreservedAnalyses::all(), llvm::nameUnamedGlobals(), and llvm::PreservedAnalyses::none().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/NameAnonGlobals.h
lib/Transforms/Utils/NameAnonGlobals.cpp