LLVM: llvm::dwarf_linker::parallel::AcceleratorRecordsSaver Class Reference
llvm::dwarf_linker::parallel::AcceleratorRecordsSaver Class Reference
This class helps to store information for accelerator entries.
#include "DWARFLinker/Parallel/AcceleratorRecordsSaver.h"
Public Member Functions
AcceleratorRecordsSaver (LinkingGlobalData &GlobalData, CompileUnit &InUnit, CompileUnit *OutUnit)
AcceleratorRecordsSaver (LinkingGlobalData &GlobalData, CompileUnit &InUnit, TypeUnit *OutUnit)
void save (const DWARFDebugInfoEntry *InputDieEntry, DIE *OutDIE, AttributesInfo &AttrInfo, TypeEntry *TypeEntry)
Save accelerator info for the specified OutDIE inside OutUnit.
Protected Member Functions
AcceleratorRecordsSaver (LinkingGlobalData &GlobalData, CompileUnit &InUnit, CompileUnit::OutputUnitVariantPtr OutUnit)
void saveObjC (const DWARFDebugInfoEntry *InputDieEntry, DIE *OutDIE, AttributesInfo &AttrInfo)
void saveNameRecord (StringEntry *Name, DIE *OutDIE, dwarf::Tag Tag, bool AvoidForPubSections)
void saveNamespaceRecord (StringEntry *Name, DIE *OutDIE, dwarf::Tag Tag, TypeEntry *TypeEntry)
void saveObjCNameRecord (StringEntry *Name, DIE *OutDIE, dwarf::Tag Tag)
void saveTypeRecord (StringEntry *Name, DIE *OutDIE, dwarf::Tag Tag, uint32_t QualifiedNameHash, bool ObjcClassImplementation, TypeEntry *TypeEntry)
Protected Attributes
LinkingGlobalData & GlobalData
Global linking data.
CompileUnit & InUnit
Comiple unit corresponding to input DWARF.
CompileUnit::OutputUnitVariantPtr OutUnit
Compile unit or Artificial type unit corresponding to the output DWARF.
Detailed Description
This class helps to store information for accelerator entries.
It prepares accelerator info for the certain DIE and store it inside OutUnit.
Definition at line 24 of file AcceleratorRecordsSaver.h.
Constructor & Destructor Documentation
AcceleratorRecordsSaver() [1/3]
llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::AcceleratorRecordsSaver (LinkingGlobalData & GlobalData, CompileUnit & InUnit, CompileUnit * OutUnit) inline
Definition at line 26 of file AcceleratorRecordsSaver.h.
AcceleratorRecordsSaver() [2/3]
llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::AcceleratorRecordsSaver (LinkingGlobalData & GlobalData, CompileUnit & InUnit, TypeUnit * OutUnit) inline
Definition at line 31 of file AcceleratorRecordsSaver.h.
AcceleratorRecordsSaver() [3/3]
llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::AcceleratorRecordsSaver (LinkingGlobalData & GlobalData, CompileUnit & InUnit, CompileUnit::OutputUnitVariantPtr OutUnit) inline protected
Definition at line 42 of file AcceleratorRecordsSaver.h.
Member Function Documentation
save()
void AcceleratorRecordsSaver::save (const DWARFDebugInfoEntry * InputDieEntry, DIE * OutDIE, AttributesInfo & AttrInfo, TypeEntry * TypeEntry)
Save accelerator info for the specified OutDIE inside OutUnit.
Side effects: set attributes in AttrInfo.
Definition at line 63 of file AcceleratorRecordsSaver.cpp.
References llvm::dwarf_linker::parallel::DWARFLinkerOptions::AccelTables, llvm::SmallVectorBase< Size_T >::empty(), llvm::StringRef::empty(), llvm::DWARFDie::find(), llvm::dwarf_linker::parallel::CompileUnit::getDIE(), llvm::StringMapEntry< T >::getKey(), llvm::DWARFDie::getLinkageName(), llvm::dwarf_linker::parallel::LinkingGlobalData::getOptions(), llvm::DWARFDie::getShortName(), llvm::dwarf_linker::parallel::LinkingGlobalData::getStringPool(), llvm::DWARFDebugInfoEntry::getTag(), GlobalData, hashFullyQualifiedName(), llvm::dwarf_linker::parallel::AttributesInfo::HasLiveAddress, llvm::dwarf_linker::parallel::AttributesInfo::HasRanges, llvm::ConcurrentHashTableByPtr< KeyTy, KeyDataTy, AllocatorTy, Info >::insert(), InUnit, llvm::dwarf_linker::parallel::AttributesInfo::IsDeclaration, llvm::LinkageName, llvm::dwarf_linker::parallel::AttributesInfo::MangledName, llvm::dwarf_linker::parallel::AttributesInfo::Name, Name, saveNameRecord(), saveNamespaceRecord(), saveObjC(), saveTypeRecord(), llvm::ShortName, llvm::StripTemplateParameters(), and llvm::dwarf::toUnsigned().
saveNameRecord()
void AcceleratorRecordsSaver::saveNameRecord (StringEntry * Name, DIE * OutDIE, dwarf::Tag Tag, bool AvoidForPubSections) protected
Definition at line 207 of file AcceleratorRecordsSaver.cpp.
References llvm::dwarf_linker::parallel::CompileUnit::OutputUnitVariantPtr::getAsCompileUnit(), llvm::DIE::getOffset(), Info, llvm::dwarf_linker::parallel::DwarfUnit::Name, Name, OutUnit, llvm::dwarf_linker::parallel::CompileUnit::saveAcceleratorInfo(), and llvm::dwarf_linker::parallel::DwarfUnit::AccelInfo::Type.
Referenced by save(), and saveObjC().
saveNamespaceRecord()
void AcceleratorRecordsSaver::saveNamespaceRecord (StringEntry * Name, DIE * OutDIE, dwarf::Tag Tag, TypeEntry * TypeEntry) protected
Definition at line 220 of file AcceleratorRecordsSaver.cpp.
References assert(), llvm::dwarf_linker::parallel::CompileUnit::OutputUnitVariantPtr::getAsCompileUnit(), llvm::dwarf_linker::parallel::CompileUnit::OutputUnitVariantPtr::getAsTypeUnit(), llvm::DIE::getOffset(), llvm::StringMapEntryStorage< ValueTy >::getValue(), Info, llvm::dwarf_linker::parallel::CompileUnit::OutputUnitVariantPtr::isCompileUnit(), Name, llvm::dwarf_linker::parallel::DwarfUnit::Namespace, OutUnit, llvm::dwarf_linker::parallel::CompileUnit::saveAcceleratorInfo(), llvm::dwarf_linker::parallel::TypeUnit::saveAcceleratorInfo(), and llvm::dwarf_linker::parallel::DwarfUnit::AccelInfo::Type.
Referenced by save().
saveObjC()
void AcceleratorRecordsSaver::saveObjC (const DWARFDebugInfoEntry * InputDieEntry, DIE * OutDIE, AttributesInfo & AttrInfo) protected
Definition at line 182 of file AcceleratorRecordsSaver.cpp.
References llvm::StringMapEntry< T >::getKey(), llvm::getObjCNamesIfSelector(), llvm::dwarf_linker::parallel::LinkingGlobalData::getStringPool(), llvm::DWARFDebugInfoEntry::getTag(), GlobalData, llvm::ConcurrentHashTableByPtr< KeyTy, KeyDataTy, AllocatorTy, Info >::insert(), llvm::dwarf_linker::parallel::AttributesInfo::Name, saveNameRecord(), and saveObjCNameRecord().
Referenced by save().
saveObjCNameRecord()
void AcceleratorRecordsSaver::saveObjCNameRecord (StringEntry * Name, DIE * OutDIE, dwarf::Tag Tag) protected
Definition at line 248 of file AcceleratorRecordsSaver.cpp.
References llvm::dwarf_linker::parallel::CompileUnit::OutputUnitVariantPtr::getAsCompileUnit(), llvm::DIE::getOffset(), Info, Name, llvm::dwarf_linker::parallel::DwarfUnit::ObjC, OutUnit, llvm::dwarf_linker::parallel::CompileUnit::saveAcceleratorInfo(), and llvm::dwarf_linker::parallel::DwarfUnit::AccelInfo::Type.
Referenced by saveObjC().
saveTypeRecord()
void AcceleratorRecordsSaver::saveTypeRecord (StringEntry * Name, DIE * OutDIE, dwarf::Tag Tag, uint32_t QualifiedNameHash, bool ObjcClassImplementation, TypeEntry * TypeEntry) protected
Definition at line 261 of file AcceleratorRecordsSaver.cpp.
References assert(), llvm::dwarf_linker::parallel::CompileUnit::OutputUnitVariantPtr::getAsCompileUnit(), llvm::dwarf_linker::parallel::CompileUnit::OutputUnitVariantPtr::getAsTypeUnit(), llvm::DIE::getOffset(), llvm::StringMapEntryStorage< ValueTy >::getValue(), Info, llvm::dwarf_linker::parallel::CompileUnit::OutputUnitVariantPtr::isCompileUnit(), Name, OutUnit, llvm::dwarf_linker::parallel::CompileUnit::saveAcceleratorInfo(), llvm::dwarf_linker::parallel::TypeUnit::saveAcceleratorInfo(), llvm::dwarf_linker::parallel::DwarfUnit::AccelInfo::Type, and llvm::dwarf_linker::parallel::DwarfUnit::Type.
Referenced by save().
Member Data Documentation
GlobalData
LinkingGlobalData& llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::GlobalData protected
Global linking data.
Definition at line 59 of file AcceleratorRecordsSaver.h.
Referenced by save(), and saveObjC().
InUnit
CompileUnit& llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::InUnit protected
Comiple unit corresponding to input DWARF.
Definition at line 62 of file AcceleratorRecordsSaver.h.
Referenced by save().
OutUnit
CompileUnit::OutputUnitVariantPtr llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::OutUnit protected
Compile unit or Artificial type unit corresponding to the output DWARF.
Definition at line 65 of file AcceleratorRecordsSaver.h.
Referenced by saveNameRecord(), saveNamespaceRecord(), saveObjCNameRecord(), and saveTypeRecord().
The documentation for this class was generated from the following files:
lib/DWARFLinker/Parallel/AcceleratorRecordsSaver.h
lib/DWARFLinker/Parallel/AcceleratorRecordsSaver.cpp