LLVM: llvm::StandardInstrumentations Class Reference
llvm::StandardInstrumentations Class Reference
This class provides an interface to register all the standard pass instrumentations and manages their state (if any).
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
StandardInstrumentations (LLVMContext &Context, bool DebugLogging, bool VerifyEach=false, PrintPassOptions PrintPassOpts=PrintPassOptions())
void registerCallbacks (PassInstrumentationCallbacks &PIC, ModuleAnalysisManager *MAM=nullptr)
TimePassesHandler & getTimePasses ()
Detailed Description
This class provides an interface to register all the standard pass instrumentations and manages their state (if any).
Definition at line 583 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
StandardInstrumentations()
llvm::StandardInstrumentations::StandardInstrumentations (LLVMContext & Context, bool DebugLogging, bool VerifyEach = false, PrintPassOptions PrintPassOpts = PrintPassOptions())
Definition at line 2444 of file StandardInstrumentations.cpp.
Member Function Documentation
getTimePasses()
TimePassesHandler & llvm::StandardInstrumentations::getTimePasses () inline
Definition at line 611 of file StandardInstrumentations.h.
registerCallbacks()
void llvm::StandardInstrumentations::registerCallbacks (PassInstrumentationCallbacks & PIC, ModuleAnalysisManager * MAM = nullptr)
Definition at line 2516 of file StandardInstrumentations.cpp.
References MAM, PIC, llvm::DotCfgChangeReporter::registerCallbacks(), llvm::InLineChangePrinter::registerCallbacks(), llvm::IRChangedPrinter::registerCallbacks(), llvm::IRChangedTester::registerCallbacks(), llvm::OptNoneInstrumentation::registerCallbacks(), llvm::PreservedCFGCheckerInstrumentation::registerCallbacks(), llvm::PrintCrashIRInstrumentation::registerCallbacks(), llvm::PrintIRInstrumentation::registerCallbacks(), llvm::PrintPassInstrumentation::registerCallbacks(), llvm::PseudoProbeVerifier::registerCallbacks(), llvm::TimePassesHandler::registerCallbacks(), llvm::TimeProfilingPassesHandler::registerCallbacks(), and llvm::VerifyInstrumentation::registerCallbacks().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp