LLVM: llvm::DebugifyEachInstrumentation Class Reference
llvm::DebugifyEachInstrumentation Class Reference
#include "llvm/Transforms/Utils/Debugify.h"
Public Member Functions
void registerCallbacks (PassInstrumentationCallbacks &PIC, ModuleAnalysisManager &MAM)
void setDIStatsMap (DebugifyStatsMap &StatMap)
const DebugifyStatsMap & getDebugifyStatsMap () const
void setDebugInfoBeforePass (DebugInfoPerPass &PerPassMap)
DebugInfoPerPass & getDebugInfoPerPass ()
void setOrigDIVerifyBugsReportFilePath (StringRef BugsReportFilePath)
StringRef getOrigDIVerifyBugsReportFilePath () const
void setDebugifyMode (enum DebugifyMode M)
bool isSyntheticDebugInfo () const
bool isOriginalDebugInfoMode () const
Detailed Description
Definition at line 190 of file Debugify.h.
Member Function Documentation
getDebugifyStatsMap()
const DebugifyStatsMap & llvm::DebugifyEachInstrumentation::getDebugifyStatsMap () const inline
Definition at line 201 of file Debugify.h.
getDebugInfoPerPass()
DebugInfoPerPass & llvm::DebugifyEachInstrumentation::getDebugInfoPerPass () inline
Definition at line 206 of file Debugify.h.
getOrigDIVerifyBugsReportFilePath()
StringRef llvm::DebugifyEachInstrumentation::getOrigDIVerifyBugsReportFilePath () const inline
Definition at line 211 of file Debugify.h.
isOriginalDebugInfoMode()
bool llvm::DebugifyEachInstrumentation::isOriginalDebugInfoMode () const inline
Definition at line 220 of file Debugify.h.
References OriginalDebugInfo.
isSyntheticDebugInfo()
bool llvm::DebugifyEachInstrumentation::isSyntheticDebugInfo () const inline
Definition at line 217 of file Debugify.h.
References SyntheticDebugInfo.
registerCallbacks()
void DebugifyEachInstrumentation::registerCallbacks (PassInstrumentationCallbacks & PIC, ModuleAnalysisManager & MAM)
Definition at line 1058 of file Debugify.cpp.
References llvm::any_cast(), applyDebugify(), llvm::checkDebugInfoMetadata(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), IR, isIgnoredPass(), llvm::make_range(), MAM, P, PIC, llvm::PreservedAnalyses::preserveSet(), llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerBeforeNonSkippedPassCallback(), and SyntheticDebugInfo.
setDebugifyMode()
void llvm::DebugifyEachInstrumentation::setDebugifyMode (enum DebugifyMode M) inline
Definition at line 215 of file Debugify.h.
setDebugInfoBeforePass()
void llvm::DebugifyEachInstrumentation::setDebugInfoBeforePass (DebugInfoPerPass & PerPassMap) inline
Definition at line 203 of file Debugify.h.
setDIStatsMap()
void llvm::DebugifyEachInstrumentation::setDIStatsMap (DebugifyStatsMap & StatMap) inline
Definition at line 200 of file Debugify.h.
setOrigDIVerifyBugsReportFilePath()
void llvm::DebugifyEachInstrumentation::setOrigDIVerifyBugsReportFilePath (StringRef BugsReportFilePath) inline
Definition at line 208 of file Debugify.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/Debugify.h
lib/Transforms/Utils/Debugify.cpp