LLVM: llvm::MCOrgFragment Class Reference
llvm::MCOrgFragment Class Reference
#include "llvm/MC/MCFragment.h"
Public Member Functions
MCOrgFragment (const MCExpr &Offset, int8_t Value, SMLoc Loc)
const MCExpr & getOffset () const
uint8_t getValue () const
SMLoc getLoc () const
Public Member Functions inherited from llvm::MCFragment
MCFragment ()=delete
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
void destroy ()
Destroys the current fragment.
MCFragment * getNext () const
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
const MCSymbol * getAtom () const
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
void dump () const
Static Public Member Functions
static bool classof (const MCFragment *F)
Additional Inherited Members
Public Types inherited from llvm::MCFragment
enum FragmentType : uint8_t {
FT_Align , FT_Data , FT_CompactEncodedInst , FT_Fill ,
FT_Nops , FT_Relaxable , FT_Org , FT_Dwarf ,
FT_DwarfFrame , FT_LEB , FT_BoundaryAlign , FT_SymbolId ,
FT_CVInlineLines , FT_CVDefRange , FT_PseudoProbe , FT_Dummy
}
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType Kind, bool HasInstructions)
Protected Attributes inherited from llvm::MCFragment
bool HasInstructions: 1
bool LinkerRelaxable: 1
Detailed Description
Definition at line 391 of file MCFragment.h.
Constructor & Destructor Documentation
MCOrgFragment()
llvm::MCOrgFragment::MCOrgFragment (const MCExpr & Offset, int8_t Value, SMLoc Loc) inline
Definition at line 402 of file MCFragment.h.
Member Function Documentation
classof()
static bool llvm::MCOrgFragment::classof (const MCFragment * F) inline static
Definition at line 411 of file MCFragment.h.
References F, and llvm::MCFragment::FT_Org.
getLoc()
SMLoc llvm::MCOrgFragment::getLoc () const inline
Definition at line 409 of file MCFragment.h.
Referenced by llvm::MCAssembler::computeFragmentSize().
getOffset()
const MCExpr & llvm::MCOrgFragment::getOffset () const inline
Definition at line 405 of file MCFragment.h.
Referenced by llvm::MCAssembler::computeFragmentSize().
getValue()
uint8_t llvm::MCOrgFragment::getValue () const inline
Definition at line 407 of file MCFragment.h.
Referenced by writeFragment().
The documentation for this class was generated from the following file:
include/llvm/MC/MCFragment.h