LLVM: lib/Analysis/CodeMetrics.cpp File Reference
CodeMetrics.cpp File Reference
#include "llvm/Analysis/CodeMetrics.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/InstructionCost.h"
Macros
#define DEBUG_TYPE "code-metrics"
Functions
static void appendSpeculatableOperands (const Value *V, SmallPtrSetImpl< const Value * > &Visited, SmallVectorImpl< const Value * > &Worklist)
static void completeEphemeralValues (SmallPtrSetImpl< const Value * > &Visited, SmallVectorImpl< const Value * > &Worklist, SmallPtrSetImpl< const Value * > &EphValues)
static bool extendsConvergenceOutsideLoop (const Instruction &I, const Loop *L)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "code-metrics"
Definition at line 23 of file CodeMetrics.cpp.
Function Documentation
appendSpeculatableOperands()
static void appendSpeculatableOperands (const Value * V, SmallPtrSetImpl< const Value * > & Visited, SmallVectorImpl< const Value * > & Worklist) static
Definition at line 28 of file CodeMetrics.cpp.
References llvm::dyn_cast(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::CodeMetrics::collectEphemeralValues(), llvm::CodeMetrics::collectEphemeralValues(), and completeEphemeralValues().
completeEphemeralValues()
static void completeEphemeralValues (SmallPtrSetImpl< const Value * > & Visited, SmallVectorImpl< const Value * > & Worklist, SmallPtrSetImpl< const Value * > & EphValues) static
Definition at line 42 of file CodeMetrics.cpp.
References llvm::all_of(), appendSpeculatableOperands(), assert(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::dbgs(), llvm::SmallPtrSetImpl< PtrType >::insert(), LLVM_DEBUG, and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::CodeMetrics::collectEphemeralValues(), and llvm::CodeMetrics::collectEphemeralValues().
extendsConvergenceOutsideLoop()
static bool extendsConvergenceOutsideLoop (const Instruction & I, const Loop * L) static
Definition at line 115 of file CodeMetrics.cpp.
References llvm::cast(), I, and llvm::isa().
Referenced by llvm::CodeMetrics::analyzeBasicBlock().