LLVM: lib/ExecutionEngine/Orc/CompileOnDemandLayer.cpp File Reference
CompileOnDemandLayer.cpp File Reference
#include "llvm/ExecutionEngine/Orc/CompileOnDemandLayer.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ExecutionEngine/Orc/ExecutionUtils.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/FormatVariadic.h"
#include <string>
Classes
class llvm::orc::PartitioningIRMaterializationUnit
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::orc
Functions
static ThreadSafeModule extractSubModule (ThreadSafeModule &TSM, StringRef Suffix, GVPredicate ShouldExtract)
Function Documentation
extractSubModule()
static ThreadSafeModule extractSubModule (ThreadSafeModule & TSM, StringRef Suffix, GVPredicate ShouldExtract) static
Definition at line 20 of file CompileOnDemandLayer.cpp.
References A, assert(), llvm::cast(), llvm::orc::cloneFunctionDecl(), llvm::orc::cloneGlobalVariableDecl(), llvm::orc::cloneToNewContext(), llvm::GlobalValue::ExternalLinkage, F, G, llvm::Value::hasName(), llvm::isa(), and llvm_unreachable.