LLVM: lib/Target/CSKY/CSKYFrameLowering.cpp File Reference
CSKYFrameLowering.cpp File Reference
#include "CSKYFrameLowering.h"
#include "CSKYMachineFunctionInfo.h"
#include "CSKYSubtarget.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/MC/MCDwarf.h"
Macros
#define DEBUG_TYPE "csky-frame-lowering"
Functions
static Register getFPReg (const CSKYSubtarget &STI)
static Register getBPReg (const CSKYSubtarget &STI)
static unsigned EstimateFunctionSizeInBytes (const MachineFunction &MF, const CSKYInstrInfo &TII)
static unsigned estimateRSStackSizeLimit (MachineFunction &MF, const CSKYSubtarget &STI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "csky-frame-lowering"
Definition at line 27 of file CSKYFrameLowering.cpp.
Function Documentation
EstimateFunctionSizeInBytes()
static unsigned EstimateFunctionSizeInBytes (const MachineFunction & MF, const CSKYInstrInfo & TII) static
Definition at line 274 of file CSKYFrameLowering.cpp.
References llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstants(), MBB, MI, and TII.
estimateRSStackSizeLimit()
static unsigned estimateRSStackSizeLimit (MachineFunction & MF, const CSKYSubtarget & STI) static
Definition at line 285 of file CSKYFrameLowering.cpp.
References llvm::CSKYII::AddrMode16B, llvm::CSKYII::AddrMode16H, llvm::CSKYII::AddrMode16W, llvm::CSKYII::AddrMode32B, llvm::CSKYII::AddrMode32H, llvm::CSKYII::AddrMode32SDF, llvm::CSKYII::AddrMode32WD, llvm::CSKYII::AddrModeMask, llvm::Pass::dump(), LLVM_DEBUG, llvm_unreachable, MBB, and MI.
getBPReg()
static Register getBPReg (const CSKYSubtarget & STI) static
Definition at line 34 of file CSKYFrameLowering.cpp.
Referenced by llvm::CSKYFrameLowering::emitPrologue(), and llvm::CSKYFrameLowering::getFrameIndexReference().
getFPReg()
static Register getFPReg (const CSKYSubtarget & STI) static
Definition at line 30 of file CSKYFrameLowering.cpp.
Referenced by llvm::CSKYFrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::CSKYFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), llvm::CSKYFrameLowering::getFrameIndexReference(), and llvm::RISCVFrameLowering::getFrameIndexReference().