LLVM: lib/Target/CSKY/MCTargetDesc/CSKYMCCodeEmitter.cpp File Reference
CSKYMCCodeEmitter.cpp File Reference
#include "CSKYMCCodeEmitter.h"
#include "CSKYMCExpr.h"
#include "MCTargetDesc/CSKYMCTargetDesc.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/EndianStream.h"
#include "CSKYGenMCCodeEmitter.inc"
Macros
#define DEBUG_TYPE "csky-mccode-emitter"
Functions
STATISTIC (MCNumEmitted, "Number of MC instructions emitted")
static void writeData (uint32_t Bin, unsigned Size, SmallVectorImpl< char > &CB)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "csky-mccode-emitter"
Definition at line 26 of file CSKYMCCodeEmitter.cpp.
Function Documentation
STATISTIC()
STATISTIC (MCNumEmitted , "Number of MC instructions emitted")
writeData()
static void writeData (uint32_t Bin, unsigned Size, SmallVectorImpl< char > & CB) static
Definition at line 60 of file CSKYMCCodeEmitter.cpp.
References llvm::Bin, llvm::little, Size, and llvm::support::endian::write().
Referenced by llvm::CSKYMCCodeEmitter::encodeInstruction(), llvm::CSKYMCCodeEmitter::expandJBTF(), llvm::CSKYMCCodeEmitter::expandNEG(), and llvm::CSKYMCCodeEmitter::expandRSUBI().