LLVM: lib/DWARFLinker/Parallel/DependencyTracker.cpp File Reference
DependencyTracker.cpp File Reference
#include "DependencyTracker.h"
#include "llvm/Support/FormatVariadic.h"
Classes
struct BrokenLink
A broken link in the keep chain.
Functions
static bool isNamespaceLikeEntry (const DWARFDebugInfoEntry *Entry)
bool isAlreadyMarked (const CompileUnit::DIEInfo &Info, CompileUnit::DieOutputPlacement NewPlacement)
bool isAlreadyMarked (const UnitEntryPairTy &Entry, CompileUnit::DieOutputPlacement NewPlacement)
static CompileUnit::DieOutputPlacement getFinalPlacementForEntry (const UnitEntryPairTy &Entry, CompileUnit::DieOutputPlacement Placement)
Function Documentation
getFinalPlacementForEntry()
static CompileUnit::DieOutputPlacement getFinalPlacementForEntry (const UnitEntryPairTy & Entry, CompileUnit::DieOutputPlacement Placement) static
Definition at line 391 of file DependencyTracker.cpp.
References assert(), llvm::dwarf_linker::parallel::CompileUnit::Both, llvm_unreachable, llvm::dwarf_linker::parallel::CompileUnit::NotSet, Placement, llvm::dwarf_linker::parallel::CompileUnit::PlainDwarf, and llvm::dwarf_linker::parallel::CompileUnit::TypeTable.
Referenced by llvm::dwarf_linker::parallel::DependencyTracker::markDIEEntryAsKeptRec().
isAlreadyMarked() [1/2]
bool isAlreadyMarked (const CompileUnit::DIEInfo & Info, CompileUnit::DieOutputPlacement NewPlacement)
Definition at line 302 of file DependencyTracker.cpp.
References llvm::dwarf_linker::parallel::CompileUnit::Both, llvm_unreachable, llvm::dwarf_linker::parallel::CompileUnit::NotSet, llvm::dwarf_linker::parallel::CompileUnit::PlainDwarf, and llvm::dwarf_linker::parallel::CompileUnit::TypeTable.
Referenced by isAlreadyMarked(), llvm::dwarf_linker::parallel::DependencyTracker::markDIEEntryAsKeptRec(), and llvm::dwarf_linker::parallel::DependencyTracker::markParentsAsKeepingChildren().
isAlreadyMarked() [2/2]
bool isAlreadyMarked (const UnitEntryPairTy & Entry, CompileUnit::DieOutputPlacement NewPlacement)
Definition at line 324 of file DependencyTracker.cpp.
References isAlreadyMarked().
isNamespaceLikeEntry()
static bool isNamespaceLikeEntry (const DWARFDebugInfoEntry * Entry) static
Definition at line 290 of file DependencyTracker.cpp.
Referenced by llvm::dwarf_linker::parallel::DependencyTracker::getRootForSpecifiedEntry(), llvm::dwarf_linker::parallel::DependencyTracker::markParentsAsKeepingChildren(), and llvm::dwarf_linker::parallel::DependencyTracker::maybeAddReferencedRoots().