LLVM: lib/Target/DirectX/DXILOpLowering.cpp File Reference
DXILOpLowering.cpp File Reference
#include "DXILConstants.h"
#include "DXILIntrinsicExpansion.h"
#include "DXILOpBuilder.h"
#include "DirectX.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsDirectX.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/Pass.h"
#include "llvm/Support/ErrorHandling.h"
#include "DXILOperation.inc"
Macros
#define DEBUG_TYPE "dxil-op-lower"
#define DXIL_OP_INTRINSIC_MAP
Functions
static bool isVectorArgExpansion (Function &F)
static SmallVector< Value * > populateOperands (Value *Arg, IRBuilder<> &Builder)
static SmallVector< Value * > argVectorFlatten (CallInst *Orig, IRBuilder<> &Builder)
static void lowerIntrinsic (dxil::OpCode DXILOp, Function &F, Module &M)
static bool lowerIntrinsics (Module &M)
INITIALIZE_PASS_BEGIN (DXILOpLoweringLegacy, DEBUG_TYPE, "DXIL Op Lowering", false, false) INITIALIZE_PASS_END(DXILOpLoweringLegacy
Variables
DEBUG_TYPE
DXIL Op Lowering
DXIL Op false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dxil-op-lower"
Definition at line 28 of file DXILOpLowering.cpp.
DXIL_OP_INTRINSIC_MAP
#define DXIL_OP_INTRINSIC_MAP
Function Documentation
argVectorFlatten()
static SmallVector< Value * > argVectorFlatten (CallInst * Orig, IRBuilder<> & Builder) static
Definition at line 54 of file DXILOpLowering.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::dyn_cast(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Value::getType(), I, and populateOperands().
Referenced by lowerIntrinsic().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (DXILOpLoweringLegacy , DEBUG_TYPE , "DXIL Op Lowering" , false , false)
isVectorArgExpansion()
static bool isVectorArgExpansion (Function & F) static
Definition at line 33 of file DXILOpLowering.cpp.
References F.
Referenced by lowerIntrinsic().
lowerIntrinsic()
static void lowerIntrinsic (dxil::OpCode DXILOp, Function & F, Module & M) static
Definition at line 75 of file DXILOpLowering.cpp.
References llvm::CallBase::arg_begin(), llvm::CallBase::arg_end(), argVectorFlatten(), B, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::dxil::DXILOpBuilder::createDXILOpCall(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::Instruction::eraseFromParent(), F, llvm::dxil::DXILOpBuilder::getOverloadTy(), isVectorArgExpansion(), llvm::make_early_inc_range(), and llvm::Value::replaceAllUsesWith().
Referenced by lowerIntrinsics().
lowerIntrinsics()
bool PreISelIntrinsicLowering::lowerIntrinsics (Module & M) static
Definition at line 104 of file DXILOpLowering.cpp.
References F, lowerIntrinsic(), llvm::make_early_inc_range(), and llvm::Intrinsic::not_intrinsic.
populateOperands()
static SmallVector< Value * > populateOperands (Value * Arg, IRBuilder<> & Builder) static
Definition at line 43 of file DXILOpLowering.cpp.
References llvm::dyn_cast(), llvm::Value::getContext(), llvm::Value::getType(), I, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by argVectorFlatten().
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 156 of file DXILOpLowering.cpp.
false
DXIL Op false
Definition at line 156 of file DXILOpLowering.cpp.
Lowering
DXIL Op Lowering
Definition at line 156 of file DXILOpLowering.cpp.