LLVM: lib/Target/DirectX/DXILIntrinsicExpansion.cpp File Reference
DXILIntrinsicExpansion.cpp File Reference
#include "DXILIntrinsicExpansion.h"
#include "DirectX.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsDirectX.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Type.h"
#include "llvm/Pass.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
Macros
#define DEBUG_TYPE "dxil-intrinsic-expansion"
Functions
static bool isIntrinsicExpansion (Function &F)
static bool expandAbs (CallInst *Orig)
static bool expandIntegerDot (CallInst *Orig, Intrinsic::ID DotIntrinsic)
static bool expandExpIntrinsic (CallInst *Orig)
static bool expandAnyIntrinsic (CallInst *Orig)
static bool expandLerpIntrinsic (CallInst *Orig)
static bool expandLogIntrinsic (CallInst *Orig, float LogConstVal=numbers::ln2f)
static bool expandLog10Intrinsic (CallInst *Orig)
static bool expandPowIntrinsic (CallInst *Orig)
static Intrinsic::ID getMaxForClamp (Type *ElemTy, Intrinsic::ID ClampIntrinsic)
static Intrinsic::ID getMinForClamp (Type *ElemTy, Intrinsic::ID ClampIntrinsic)
static bool expandClampIntrinsic (CallInst *Orig, Intrinsic::ID ClampIntrinsic)
static bool expandIntrinsic (Function &F, CallInst *Orig)
static bool expansionIntrinsics (Module &M)
INITIALIZE_PASS_BEGIN (DXILIntrinsicExpansionLegacy, DEBUG_TYPE, "DXIL Intrinsic Expansion", false, false) INITIALIZE_PASS_END(DXILIntrinsicExpansionLegacy
Variables
DEBUG_TYPE
DXIL Intrinsic Expansion
DXIL Intrinsic false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dxil-intrinsic-expansion"
Definition at line 30 of file DXILIntrinsicExpansion.cpp.
Function Documentation
expandAbs()
static bool expandAbs (CallInst * Orig) static
Definition at line 52 of file DXILIntrinsicExpansion.cpp.
References llvm::cast(), llvm::Instruction::eraseFromParent(), llvm::ElementCount::getFixed(), getNumElements(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), llvm::Value::replaceAllUsesWith(), and X.
Referenced by expandIntrinsic().
expandAnyIntrinsic()
static bool expandAnyIntrinsic (CallInst * Orig) static
Definition at line 125 of file DXILIntrinsicExpansion.cpp.
References Cond, llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::ElementCount::getFixed(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), I, llvm::Type::isFloatingPointTy(), llvm::Value::replaceAllUsesWith(), and X.
Referenced by expandIntrinsic().
expandClampIntrinsic()
static bool expandClampIntrinsic (CallInst * Orig, Intrinsic::ID ClampIntrinsic) static
Definition at line 246 of file DXILIntrinsicExpansion.cpp.
References llvm::Instruction::eraseFromParent(), getMaxForClamp(), getMinForClamp(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Value::replaceAllUsesWith(), and X.
Referenced by expandIntrinsic().
expandExpIntrinsic()
static bool expandExpIntrinsic (CallInst * Orig) static
Definition at line 103 of file DXILIntrinsicExpansion.cpp.
References llvm::cast(), llvm::Instruction::eraseFromParent(), llvm::CallBase::getAttributes(), llvm::ElementCount::getFixed(), getNumElements(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), llvm::CallInst::isTailCall(), llvm::numbers::log2ef, llvm::Value::replaceAllUsesWith(), and X.
Referenced by expandIntrinsic().
expandIntegerDot()
static bool expandIntegerDot (CallInst * Orig, Intrinsic::ID DotIntrinsic) static
Definition at line 72 of file DXILIntrinsicExpansion.cpp.
References A, assert(), B, llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), I, llvm::Type::isVectorTy(), and llvm::Value::replaceAllUsesWith().
Referenced by expandIntrinsic().
expandIntrinsic()
static bool expandIntrinsic (Function & F, CallInst * Orig) static
Definition at line 264 of file DXILIntrinsicExpansion.cpp.
References expandAbs(), expandAnyIntrinsic(), expandClampIntrinsic(), expandExpIntrinsic(), expandIntegerDot(), expandLerpIntrinsic(), expandLog10Intrinsic(), expandLogIntrinsic(), expandPowIntrinsic(), F, and llvm::CallBase::getIntrinsicID().
Referenced by expansionIntrinsics().
expandLerpIntrinsic()
static bool expandLerpIntrinsic (CallInst * Orig) static
Definition at line 160 of file DXILIntrinsicExpansion.cpp.
References llvm::Instruction::eraseFromParent(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Value::replaceAllUsesWith(), X, and Y.
Referenced by expandIntrinsic().
expandLog10Intrinsic()
static bool expandLog10Intrinsic (CallInst * Orig) static
Definition at line 196 of file DXILIntrinsicExpansion.cpp.
References expandLogIntrinsic(), llvm::numbers::ln10f, and llvm::numbers::ln2f.
Referenced by expandIntrinsic().
expandLogIntrinsic()
static bool expandLogIntrinsic (CallInst * Orig, float LogConstVal = numbers::ln2f) static
Definition at line 174 of file DXILIntrinsicExpansion.cpp.
References llvm::cast(), llvm::Instruction::eraseFromParent(), llvm::CallBase::getAttributes(), llvm::ElementCount::getFixed(), getNumElements(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), llvm::CallInst::isTailCall(), llvm::Value::replaceAllUsesWith(), and X.
Referenced by expandIntrinsic(), and expandLog10Intrinsic().
expandPowIntrinsic()
static bool expandPowIntrinsic (CallInst * Orig) static
Definition at line 200 of file DXILIntrinsicExpansion.cpp.
References llvm::Instruction::eraseFromParent(), llvm::CallBase::getAttributes(), llvm::User::getOperand(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::CallInst::isTailCall(), llvm::Mul, llvm::Value::replaceAllUsesWith(), X, and Y.
Referenced by expandIntrinsic().
expansionIntrinsics()
static bool expansionIntrinsics (Module & M) static
Definition at line 290 of file DXILIntrinsicExpansion.cpp.
References llvm::dyn_cast(), expandIntrinsic(), F, isIntrinsicExpansion(), and llvm::make_early_inc_range().
Referenced by llvm::DXILIntrinsicExpansion::run(), and llvm::DXILIntrinsicExpansionLegacy::runOnModule().
getMaxForClamp()
static Intrinsic::ID getMaxForClamp (Type * ElemTy, Intrinsic::ID ClampIntrinsic) static
Definition at line 220 of file DXILIntrinsicExpansion.cpp.
References assert().
Referenced by expandClampIntrinsic().
getMinForClamp()
static Intrinsic::ID getMinForClamp (Type * ElemTy, Intrinsic::ID ClampIntrinsic) static
Definition at line 233 of file DXILIntrinsicExpansion.cpp.
References assert().
Referenced by expandClampIntrinsic().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (DXILIntrinsicExpansionLegacy , DEBUG_TYPE , "DXIL Intrinsic Expansion" , false , false)
isIntrinsicExpansion()
static bool isIntrinsicExpansion (Function & F) static
Definition at line 34 of file DXILIntrinsicExpansion.cpp.
References F.
Referenced by expansionIntrinsics().
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 322 of file DXILIntrinsicExpansion.cpp.
Expansion
DXIL Intrinsic Expansion
Definition at line 323 of file DXILIntrinsicExpansion.cpp.
Referenced by llvm::coverage::CoverageMapping::getCoverageForExpansion().
false
DXIL Intrinsic false
Definition at line 323 of file DXILIntrinsicExpansion.cpp.