LLVM: lib/CodeGen/FinalizeISel.cpp File Reference
FinalizeISel.cpp File Reference
#include "llvm/CodeGen/FinalizeISel.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
Macros
#define DEBUG_TYPE "finalize-isel"
Functions
static std::pair< bool, bool > runImpl (MachineFunction &MF)
INITIALIZE_PASS (FinalizeISel, DEBUG_TYPE, "Finalize ISel and expand pseudo-instructions", false, false) bool FinalizeISel
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "finalize-isel"
Definition at line 27 of file FinalizeISel.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (FinalizeISel , DEBUG_TYPE , "Finalize ISel and expand pseudo-instructions" , false , false)
Definition at line 85 of file FinalizeISel.cpp.
References runImpl().
runImpl()
static std::pair< bool, bool > runImpl (MachineFunction & MF) static
Definition at line 44 of file FinalizeISel.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), Changed, llvm::TargetLowering::EmitInstrWithCustomInserter(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::TargetLoweringBase::finalizeLowering(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), I, MBB, MBBI, MI, llvm::PreserveCFG, llvm::MachineFrameInfo::setAdjustsStack(), and TII.
Referenced by INITIALIZE_PASS().