LLVM: lib/Target/AMDGPU/GCNRegPressure.cpp File Reference
GCNRegPressure.cpp File Reference
This file implements the GCNRegPressure class.
#include "GCNRegPressure.h"
#include "AMDGPU.h"
#include "llvm/CodeGen/RegisterPressure.h"
Macros
#define DEBUG_TYPE "machine-scheduler"
#define PFX " "
Functions
static LaneBitmask getDefRegMask (const MachineOperand &MO, const MachineRegisterInfo &MRI)
static void collectVirtualRegUses (SmallVectorImpl< RegisterMaskPair > &RegMaskPairs, const MachineInstr &MI, const LiveIntervals &LIS, const MachineRegisterInfo &MRI)
static LaneBitmask getRegLiveThroughMask (const MachineRegisterInfo &MRI, const LiveIntervals &LIS, Register Reg, SlotIndex Begin, SlotIndex End, LaneBitmask Mask=LaneBitmask::getAll())
Variables
static cl::opt< bool > UseDownwardTracker ("amdgpu-print-rp-downward", cl::desc("Use GCNDownwardRPTracker for GCNRegPressurePrinter pass"), cl::init(false), cl::Hidden)
Detailed Description
This file implements the GCNRegPressure class.
Definition in file GCNRegPressure.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-scheduler"
Definition at line 20 of file GCNRegPressure.cpp.
PFX
#define PFX " "
Referenced by llvm::GCNRegPressurePrinter::runOnMachineFunction(), and llvm::AMDGPULibFunc::setPrefix().
Function Documentation
collectVirtualRegUses()
static void collectVirtualRegUses (SmallVectorImpl< RegisterMaskPair > & RegMaskPairs, const MachineInstr & MI, const LiveIntervals & LIS, const MachineRegisterInfo & MRI) static
Definition at line 258 of file GCNRegPressure.cpp.
References llvm::any_of(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SlotIndex::getBaseIndex(), llvm::LiveIntervals::getInstructionIndex(), llvm::LiveIntervals::getInterval(), llvm::getLiveLaneMask(), MI, MRI, and Reg.
Referenced by llvm::GCNUpwardRPTracker::recede().
getDefRegMask()
static LaneBitmask getDefRegMask (const MachineOperand & MO, const MachineRegisterInfo & MRI) static
Definition at line 245 of file GCNRegPressure.cpp.
References assert(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), llvm::Register::isVirtual(), and MRI.
Referenced by llvm::GCNDownwardRPTracker::advanceToNext(), and llvm::GCNUpwardRPTracker::recede().
getRegLiveThroughMask()
static LaneBitmask getRegLiveThroughMask (const MachineRegisterInfo & MRI, const LiveIntervals & LIS, Register Reg, SlotIndex Begin, SlotIndex End, LaneBitmask Mask = LaneBitmask::getAll()) static
Definition at line 603 of file GCNRegPressure.cpp.
References End, and llvm::LiveInterval::hasSubRanges().
Referenced by llvm::GCNRegPressurePrinter::runOnMachineFunction().
Variable Documentation
UseDownwardTracker
cl::opt< bool > UseDownwardTracker("amdgpu-print-rp-downward", cl::desc("Use GCNDownwardRPTracker for GCNRegPressurePrinter pass"), cl::init(false), cl::Hidden) ("amdgpu-print-rp-downward" , cl::desc("Use GCNDownwardRPTracker for GCNRegPressurePrinter pass") , cl::init(false) , cl::Hidden) static
Referenced by llvm::GCNRegPressurePrinter::runOnMachineFunction().