LLVM: Other Types
Other Types
LLVM-C: C interface to LLVM » Core » Types
Functions
LLVMTypeRef LLVMVoidTypeInContext (LLVMContextRef C)
Create a void type in a context.
LLVMTypeRef LLVMLabelTypeInContext (LLVMContextRef C)
Create a label type in a context.
LLVMTypeRef LLVMX86MMXTypeInContext (LLVMContextRef C)
Create a X86 MMX type in a context.
LLVMTypeRef LLVMX86AMXTypeInContext (LLVMContextRef C)
Create a X86 AMX type in a context.
LLVMTypeRef LLVMTokenTypeInContext (LLVMContextRef C)
Create a token type in a context.
LLVMTypeRef LLVMMetadataTypeInContext (LLVMContextRef C)
Create a metadata type in a context.
LLVMTypeRef LLVMVoidType (void)
These are similar to the above functions except they operate on the global context.
LLVMTypeRef LLVMLabelType (void)
LLVMTypeRef LLVMX86MMXType (void)
LLVMTypeRef LLVMX86AMXType (void)
LLVMTypeRef LLVMTargetExtTypeInContext (LLVMContextRef C, const char *Name, LLVMTypeRef *TypeParams, unsigned TypeParamCount, unsigned *IntParams, unsigned IntParamCount)
Create a target extension type in LLVM context.
const char * LLVMGetTargetExtTypeName (LLVMTypeRef TargetExtTy)
Obtain the name for this target extension type.
unsigned LLVMGetTargetExtTypeNumTypeParams (LLVMTypeRef TargetExtTy)
Obtain the number of type parameters for this target extension type.
LLVMTypeRef LLVMGetTargetExtTypeTypeParam (LLVMTypeRef TargetExtTy, unsigned Idx)
Get the type parameter at the given index for the target extension type.
unsigned LLVMGetTargetExtTypeNumIntParams (LLVMTypeRef TargetExtTy)
Obtain the number of int parameters for this target extension type.
unsigned LLVMGetTargetExtTypeIntParam (LLVMTypeRef TargetExtTy, unsigned Idx)
Get the int parameter at the given index for the target extension type.
Detailed Description
Function Documentation
LLVMGetTargetExtTypeIntParam()
unsigned LLVMGetTargetExtTypeIntParam (LLVMTypeRef TargetExtTy, unsigned Idx)
Get the int parameter at the given index for the target extension type.
See also
llvm::TargetExtType::getIntParameter()
Definition at line 994 of file Core.cpp.
References llvm::unwrap().
LLVMGetTargetExtTypeName()
const char * LLVMGetTargetExtTypeName (LLVMTypeRef TargetExtTy)
Obtain the name for this target extension type.
See also
llvm::TargetExtType::getName()
Definition at line 973 of file Core.cpp.
References llvm::unwrap().
LLVMGetTargetExtTypeNumIntParams()
unsigned LLVMGetTargetExtTypeNumIntParams (LLVMTypeRef TargetExtTy)
Obtain the number of int parameters for this target extension type.
See also
llvm::TargetExtType::getNumIntParameters()
Definition at line 989 of file Core.cpp.
References llvm::unwrap().
LLVMGetTargetExtTypeNumTypeParams()
unsigned LLVMGetTargetExtTypeNumTypeParams (LLVMTypeRef TargetExtTy)
Obtain the number of type parameters for this target extension type.
See also
llvm::TargetExtType::getNumTypeParameters()
Definition at line 978 of file Core.cpp.
References llvm::unwrap().
LLVMGetTargetExtTypeTypeParam()
LLVMTypeRef LLVMGetTargetExtTypeTypeParam (LLVMTypeRef TargetExtTy, unsigned Idx)
Get the type parameter at the given index for the target extension type.
See also
llvm::TargetExtType::getTypeParameter()
Definition at line 983 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMLabelType()
LLVMTypeRef LLVMLabelType (void)
Definition at line 958 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMLabelTypeInContext().
LLVMLabelTypeInContext()
LLVMTypeRef LLVMLabelTypeInContext (LLVMContextRef C)
Create a label type in a context.
Definition at line 945 of file Core.cpp.
References llvm::CallingConv::C, llvm::unwrap(), and llvm::wrap().
Referenced by LLVMLabelType().
LLVMMetadataTypeInContext()
LLVMTypeRef LLVMMetadataTypeInContext (LLVMContextRef C)
Create a metadata type in a context.
Definition at line 951 of file Core.cpp.
References llvm::CallingConv::C, llvm::unwrap(), and llvm::wrap().
LLVMTargetExtTypeInContext()
LLVMTypeRef LLVMTargetExtTypeInContext (LLVMContextRef C, const char * Name, LLVMTypeRef * TypeParams, unsigned TypeParamCount, unsigned * IntParams, unsigned IntParamCount)
Create a target extension type in LLVM context.
Definition at line 962 of file Core.cpp.
References llvm::CallingConv::C, llvm::TargetExtType::get(), Name, llvm::unwrap(), and llvm::wrap().
LLVMTokenTypeInContext()
LLVMTypeRef LLVMTokenTypeInContext (LLVMContextRef C)
Create a token type in a context.
Definition at line 948 of file Core.cpp.
References llvm::CallingConv::C, llvm::unwrap(), and llvm::wrap().
LLVMVoidType()
LLVMTypeRef LLVMVoidType (void)
These are similar to the above functions except they operate on the global context.
Definition at line 955 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMVoidTypeInContext().
LLVMVoidTypeInContext()
LLVMTypeRef LLVMVoidTypeInContext (LLVMContextRef C)
Create a void type in a context.
Definition at line 942 of file Core.cpp.
References llvm::CallingConv::C, llvm::unwrap(), and llvm::wrap().
Referenced by LLVMVoidType().
LLVMX86AMXType()
LLVMTypeRef LLVMX86AMXType (void)
Definition at line 759 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMX86AMXTypeInContext().
LLVMX86AMXTypeInContext()
LLVMTypeRef LLVMX86AMXTypeInContext (LLVMContextRef C)
Create a X86 AMX type in a context.
Definition at line 731 of file Core.cpp.
References llvm::CallingConv::C, and llvm::unwrap().
Referenced by LLVMX86AMXType().
LLVMX86MMXType()
LLVMTypeRef LLVMX86MMXType (void)
Definition at line 756 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMX86MMXTypeInContext().
LLVMX86MMXTypeInContext()
LLVMTypeRef LLVMX86MMXTypeInContext (LLVMContextRef C)
Create a X86 MMX type in a context.
Definition at line 728 of file Core.cpp.
References llvm::CallingConv::C, and llvm::unwrap().
Referenced by LLVMX86MMXType().