LLVM: GEPs
GEPs
LLVM-C: C interface to LLVM » Core » Instructions
Functions
LLVMBool LLVMIsInBounds (LLVMValueRef GEP)
Check whether the given GEP operator is inbounds.
void LLVMSetIsInBounds (LLVMValueRef GEP, LLVMBool InBounds)
Set the given GEP instruction to be inbounds or not.
LLVMTypeRef LLVMGetGEPSourceElementType (LLVMValueRef GEP)
Get the source element type of the given GEP operator.
LLVMGEPNoWrapFlags LLVMGEPGetNoWrapFlags (LLVMValueRef GEP)
Get the no-wrap related flags for the given GEP instruction.
void LLVMGEPSetNoWrapFlags (LLVMValueRef GEP, LLVMGEPNoWrapFlags NoWrapFlags)
Set the no-wrap related flags for the given GEP instruction.
Detailed Description
Functions in this group only apply to instructions that map to llvm::GetElementPtrInst instances.
Function Documentation
LLVMGEPGetNoWrapFlags()
LLVMGEPNoWrapFlags LLVMGEPGetNoWrapFlags (LLVMValueRef GEP)
Get the no-wrap related flags for the given GEP instruction.
See also
llvm::GetElementPtrInst::getNoWrapFlags
Definition at line 3166 of file Core.cpp.
References GEP, llvm::GEPOperator::getNoWrapFlags(), mapToLLVMGEPNoWrapFlags(), and llvm::unwrap().
LLVMGEPSetNoWrapFlags()
void LLVMGEPSetNoWrapFlags (LLVMValueRef GEP, LLVMGEPNoWrapFlags NoWrapFlags)
Set the no-wrap related flags for the given GEP instruction.
See also
llvm::GetElementPtrInst::setNoWrapFlags
Definition at line 3171 of file Core.cpp.
References GEP, mapFromLLVMGEPNoWrapFlags(), llvm::GetElementPtrInst::setNoWrapFlags(), and llvm::unwrap().
LLVMGetGEPSourceElementType()
LLVMTypeRef LLVMGetGEPSourceElementType (LLVMValueRef GEP)
Get the source element type of the given GEP operator.
Definition at line 3162 of file Core.cpp.
References GEP, llvm::unwrap(), and llvm::wrap().
LLVMIsInBounds()
LLVMBool LLVMIsInBounds (LLVMValueRef GEP)
Check whether the given GEP operator is inbounds.
Definition at line 3154 of file Core.cpp.
References GEP, and llvm::unwrap().
LLVMSetIsInBounds()
void LLVMSetIsInBounds (LLVMValueRef GEP, LLVMBool InBounds)
Set the given GEP instruction to be inbounds or not.
Definition at line 3158 of file Core.cpp.
References GEP, and llvm::unwrap().