LLVM: Sequential Types
Sequential Types
LLVM-C: C interface to LLVM » Core » Types
Functions
LLVMTypeRef LLVMGetElementType (LLVMTypeRef Ty)
Obtain the element type of an array or vector type.
void LLVMGetSubtypes (LLVMTypeRef Tp, LLVMTypeRef *Arr)
Returns type's subtypes.
unsigned LLVMGetNumContainedTypes (LLVMTypeRef Tp)
Return the number of types in the derived type.
LLVMTypeRef LLVMArrayType (LLVMTypeRef ElementType, unsigned ElementCount)
Create a fixed size array type that refers to a specific type.
LLVMTypeRef LLVMArrayType2 (LLVMTypeRef ElementType, uint64_t ElementCount)
Create a fixed size array type that refers to a specific type.
unsigned LLVMGetArrayLength (LLVMTypeRef ArrayTy)
Obtain the length of an array type.
uint64_t LLVMGetArrayLength2 (LLVMTypeRef ArrayTy)
Obtain the length of an array type.
LLVMTypeRef LLVMPointerType (LLVMTypeRef ElementType, unsigned AddressSpace)
Create a pointer type that points to a defined type.
LLVMBool LLVMPointerTypeIsOpaque (LLVMTypeRef Ty)
Determine whether a pointer is opaque.
LLVMTypeRef LLVMPointerTypeInContext (LLVMContextRef C, unsigned AddressSpace)
Create an opaque pointer type in a context.
unsigned LLVMGetPointerAddressSpace (LLVMTypeRef PointerTy)
Obtain the address space of a pointer type.
LLVMTypeRef LLVMVectorType (LLVMTypeRef ElementType, unsigned ElementCount)
Create a vector type that contains a defined type and has a specific number of elements.
LLVMTypeRef LLVMScalableVectorType (LLVMTypeRef ElementType, unsigned ElementCount)
Create a vector type that contains a defined type and has a scalable number of elements.
unsigned LLVMGetVectorSize (LLVMTypeRef VectorTy)
Obtain the (possibly scalable) number of elements in a vector type.
LLVMValueRef LLVMGetConstantPtrAuthPointer (LLVMValueRef PtrAuth)
Get the pointer value for the associated ConstantPtrAuth constant.
LLVMValueRef LLVMGetConstantPtrAuthKey (LLVMValueRef PtrAuth)
Get the key value for the associated ConstantPtrAuth constant.
LLVMValueRef LLVMGetConstantPtrAuthDiscriminator (LLVMValueRef PtrAuth)
Get the discriminator value for the associated ConstantPtrAuth constant.
LLVMValueRef LLVMGetConstantPtrAuthAddrDiscriminator (LLVMValueRef PtrAuth)
Get the address discriminator value for the associated ConstantPtrAuth constant.
Detailed Description
Sequential types represents "arrays" of types. This is a super class for array, vector, and pointer types.
Function Documentation
LLVMArrayType()
LLVMTypeRef LLVMArrayType (LLVMTypeRef ElementType, unsigned ElementCount)
Create a fixed size array type that refers to a specific type.
The created type will exist in the context that its element type exists in.
Deprecated
LLVMArrayType is deprecated in favor of the API accurate LLVMArrayType2
See also
llvm::ArrayType::get()
Definition at line 868 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMArrayType2()
LLVMTypeRef LLVMArrayType2 (LLVMTypeRef ElementType, uint64_t ElementCount)
Create a fixed size array type that refers to a specific type.
The created type will exist in the context that its element type exists in.
See also
llvm::ArrayType::get()
Definition at line 872 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetArrayLength()
unsigned LLVMGetArrayLength (LLVMTypeRef ArrayTy)
Obtain the length of an array type.
This only works on types that represent arrays.
Deprecated
LLVMGetArrayLength is deprecated in favor of the API accurate LLVMGetArrayLength2
See also
llvm::ArrayType::getNumElements()
Definition at line 904 of file Core.cpp.
References llvm::unwrap().
LLVMGetArrayLength2()
uint64_t LLVMGetArrayLength2 (LLVMTypeRef ArrayTy)
Obtain the length of an array type.
This only works on types that represent arrays.
See also
llvm::ArrayType::getNumElements()
Definition at line 908 of file Core.cpp.
References llvm::unwrap().
LLVMGetConstantPtrAuthAddrDiscriminator()
LLVMValueRef LLVMGetConstantPtrAuthAddrDiscriminator (LLVMValueRef PtrAuth)
Get the address discriminator value for the associated ConstantPtrAuth constant.
See also
llvm::ConstantPtrAuth::getAddrDiscriminator
Definition at line 932 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetConstantPtrAuthDiscriminator()
LLVMValueRef LLVMGetConstantPtrAuthDiscriminator (LLVMValueRef PtrAuth)
Get the discriminator value for the associated ConstantPtrAuth constant.
See also
llvm::ConstantPtrAuth::getDiscriminator
Definition at line 928 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetConstantPtrAuthKey()
LLVMValueRef LLVMGetConstantPtrAuthKey (LLVMValueRef PtrAuth)
Get the key value for the associated ConstantPtrAuth constant.
See also
llvm::ConstantPtrAuth::getKey
Definition at line 924 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetConstantPtrAuthPointer()
LLVMValueRef LLVMGetConstantPtrAuthPointer (LLVMValueRef PtrAuth)
Get the pointer value for the associated ConstantPtrAuth constant.
See also
llvm::ConstantPtrAuth::getPointer
Definition at line 920 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetElementType()
LLVMTypeRef LLVMGetElementType (LLVMTypeRef Ty)
Obtain the element type of an array or vector type.
See also
llvm::SequentialType::getElementType()
Definition at line 893 of file Core.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::unwrap(), and llvm::wrap().
LLVMGetNumContainedTypes()
unsigned LLVMGetNumContainedTypes (LLVMTypeRef Tp)
Return the number of types in the derived type.
See also
llvm::Type::getNumContainedTypes()
Definition at line 900 of file Core.cpp.
References llvm::unwrap().
LLVMGetPointerAddressSpace()
unsigned LLVMGetPointerAddressSpace (LLVMTypeRef PointerTy)
Obtain the address space of a pointer type.
This only works on types that represent pointers.
See also
llvm::PointerType::getAddressSpace()
Definition at line 912 of file Core.cpp.
References llvm::unwrap().
LLVMGetSubtypes()
void LLVMGetSubtypes (LLVMTypeRef Tp, LLVMTypeRef * Arr)
Returns type's subtypes.
See also
llvm::Type::subtypes()
Definition at line 860 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetVectorSize()
unsigned LLVMGetVectorSize (LLVMTypeRef VectorTy)
Obtain the (possibly scalable) number of elements in a vector type.
This only works on types that represent vectors (fixed or scalable).
See also
llvm::VectorType::getNumElements()
Definition at line 916 of file Core.cpp.
References llvm::unwrap().
LLVMPointerType()
LLVMTypeRef LLVMPointerType (LLVMTypeRef ElementType, unsigned AddressSpace)
Create a pointer type that points to a defined type.
The created type will exist in the context that its pointee type exists in.
See also
llvm::PointerType::get()
Definition at line 876 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMPointerTypeInContext()
LLVMTypeRef LLVMPointerTypeInContext (LLVMContextRef C, unsigned AddressSpace)
Create an opaque pointer type in a context.
See also
llvm::PointerType::get()
Definition at line 938 of file Core.cpp.
References llvm::CallingConv::C, llvm::unwrap(), and llvm::wrap().
LLVMPointerTypeIsOpaque()
LLVMBool LLVMPointerTypeIsOpaque (LLVMTypeRef Ty)
Determine whether a pointer is opaque.
True if this is an instance of an opaque PointerType.
See also
llvm::Type::isOpaquePointerTy()
Definition at line 880 of file Core.cpp.
LLVMScalableVectorType()
LLVMTypeRef LLVMScalableVectorType (LLVMTypeRef ElementType, unsigned ElementCount)
Create a vector type that contains a defined type and has a scalable number of elements.
The created type will exist in the context thats its element type exists in.
See also
llvm::ScalableVectorType::get()
Definition at line 888 of file Core.cpp.
References llvm::ScalableVectorType::get(), llvm::unwrap(), and llvm::wrap().
LLVMVectorType()
LLVMTypeRef LLVMVectorType (LLVMTypeRef ElementType, unsigned ElementCount)
Create a vector type that contains a defined type and has a specific number of elements.
The created type will exist in the context thats its element type exists in.
See also
llvm::VectorType::get()
Definition at line 884 of file Core.cpp.
References llvm::FixedVectorType::get(), llvm::unwrap(), and llvm::wrap().
Referenced by llvm::buildBoolRegister().