LLVM: LLJIT Utilities
LLJIT Utilities
LLVM-C: C interface to LLVM » Execution Engine » LLJIT
Functions
LLVMErrorRef LLVMOrcLLJITEnableDebugSupport (LLVMOrcLLJITRef J)
Install the plugin that submits debug objects to the executor.
Detailed Description
Function Documentation
LLVMOrcLLJITEnableDebugSupport()
LLVMErrorRef LLVMOrcLLJITEnableDebugSupport (LLVMOrcLLJITRef J)
Install the plugin that submits debug objects to the executor.
Executors must expose the llvm_orc_registerJITLoaderGDBWrapper symbol.
Definition at line 20 of file LLJITUtilsCBindings.cpp.
References llvm::orc::enableDebuggerSupport(), llvm::unwrap(), and llvm::wrap().