LLVM: Global Values
Global Values
LLVM-C: C interface to LLVM » Core » Values » Constants
Topics
Values with alignment
Functions
LLVMModuleRef LLVMGetGlobalParent (LLVMValueRef Global)
LLVMBool LLVMIsDeclaration (LLVMValueRef Global)
LLVMLinkage LLVMGetLinkage (LLVMValueRef Global)
void LLVMSetLinkage (LLVMValueRef Global, LLVMLinkage Linkage)
const char * LLVMGetSection (LLVMValueRef Global)
void LLVMSetSection (LLVMValueRef Global, const char *Section)
LLVMVisibility LLVMGetVisibility (LLVMValueRef Global)
void LLVMSetVisibility (LLVMValueRef Global, LLVMVisibility Viz)
LLVMDLLStorageClass LLVMGetDLLStorageClass (LLVMValueRef Global)
void LLVMSetDLLStorageClass (LLVMValueRef Global, LLVMDLLStorageClass Class)
LLVMUnnamedAddr LLVMGetUnnamedAddress (LLVMValueRef Global)
void LLVMSetUnnamedAddress (LLVMValueRef Global, LLVMUnnamedAddr UnnamedAddr)
LLVMTypeRef LLVMGlobalGetValueType (LLVMValueRef Global)
Returns the "value type" of a global value.
LLVMBool LLVMHasUnnamedAddr (LLVMValueRef Global)
Deprecated: Use LLVMGetUnnamedAddress instead.
void LLVMSetUnnamedAddr (LLVMValueRef Global, LLVMBool HasUnnamedAddr)
Deprecated: Use LLVMSetUnnamedAddress instead.
unsigned LLVMGetAlignment (LLVMValueRef V)
Obtain the preferred alignment of the value.
void LLVMSetAlignment (LLVMValueRef V, unsigned Bytes)
Set the preferred alignment of the value.
void LLVMGlobalSetMetadata (LLVMValueRef Global, unsigned Kind, LLVMMetadataRef MD)
Sets a metadata attachment, erasing the existing metadata attachment if it already exists for the given kind.
void LLVMGlobalEraseMetadata (LLVMValueRef Global, unsigned Kind)
Erases a metadata attachment of the given kind if it exists.
void LLVMGlobalClearMetadata (LLVMValueRef Global)
Removes all metadata attachments from this value.
LLVMValueMetadataEntry * LLVMGlobalCopyAllMetadata (LLVMValueRef Value, size_t *NumEntries)
Retrieves an array of metadata entries representing the metadata attached to this value.
void LLVMDisposeValueMetadataEntries (LLVMValueMetadataEntry *Entries)
Destroys value metadata entries.
unsigned LLVMValueMetadataEntriesGetKind (LLVMValueMetadataEntry *Entries, unsigned Index)
Returns the kind of a value metadata entry at a specific index.
LLVMMetadataRef LLVMValueMetadataEntriesGetMetadata (LLVMValueMetadataEntry *Entries, unsigned Index)
Returns the underlying metadata node of a value metadata entry at a specific index.
Detailed Description
This group contains functions that operate on global values. Functions in this group relate to functions in the llvm::GlobalValue class tree.
See also
llvm::GlobalValue
Function Documentation
LLVMDisposeValueMetadataEntries()
void LLVMDisposeValueMetadataEntries (LLVMValueMetadataEntry * Entries)
Destroys value metadata entries.
Definition at line 2177 of file Core.cpp.
LLVMGetAlignment()
unsigned LLVMGetAlignment (LLVMValueRef V)
Obtain the preferred alignment of the value.
See also
llvm::AllocaInst::getAlignment()
llvm::LoadInst::getAlignment()
llvm::StoreInst::getAlignment()
llvm::AtomicRMWInst::setAlignment()
llvm::AtomicCmpXchgInst::setAlignment()
llvm::GlobalValue::getAlignment()
Definition at line 2110 of file Core.cpp.
References llvm::dyn_cast(), llvm_unreachable, P, and llvm::unwrap().
LLVMGetDLLStorageClass()
LLVMDLLStorageClass LLVMGetDLLStorageClass (LLVMValueRef Global)
Definition at line 2059 of file Core.cpp.
References llvm::Global, and llvm::unwrap().
LLVMGetGlobalParent()
LLVMModuleRef LLVMGetGlobalParent (LLVMValueRef Global)
Definition at line 1937 of file Core.cpp.
References getParent(), llvm::Global, llvm::unwrap(), and llvm::wrap().
LLVMGetLinkage()
LLVMLinkage LLVMGetLinkage (LLVMValueRef Global)
Definition at line 1945 of file Core.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::Global, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm_unreachable, LLVMAppendingLinkage, LLVMAvailableExternallyLinkage, LLVMCommonLinkage, LLVMExternalLinkage, LLVMExternalWeakLinkage, LLVMInternalLinkage, LLVMLinkOnceAnyLinkage, LLVMLinkOnceODRLinkage, LLVMPrivateLinkage, LLVMWeakAnyLinkage, LLVMWeakODRLinkage, llvm::GlobalValue::PrivateLinkage, llvm::unwrap(), llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
LLVMGetSection()
const char * LLVMGetSection (LLVMValueRef Global)
Definition at line 2039 of file Core.cpp.
References llvm::Global, and llvm::unwrap().
LLVMGetUnnamedAddress()
LLVMUnnamedAddr LLVMGetUnnamedAddress (LLVMValueRef Global)
Definition at line 2069 of file Core.cpp.
References llvm::Global, llvm_unreachable, LLVMGlobalUnnamedAddr, LLVMLocalUnnamedAddr, LLVMNoUnnamedAddr, and llvm::unwrap().
LLVMGetVisibility()
LLVMVisibility LLVMGetVisibility (LLVMValueRef Global)
Definition at line 2049 of file Core.cpp.
References llvm::Global, and llvm::unwrap().
LLVMGlobalClearMetadata()
void LLVMGlobalClearMetadata (LLVMValueRef Global)
Removes all metadata attachments from this value.
See also
llvm::GlobalObject::clearMetadata()
Definition at line 2190 of file Core.cpp.
References llvm::Global, and llvm::unwrap().
LLVMGlobalCopyAllMetadata()
LLVMValueMetadataEntry * LLVMGlobalCopyAllMetadata (LLVMValueRef Value, size_t * NumEntries)
Retrieves an array of metadata entries representing the metadata attached to this value.
The caller is responsible for freeing this array by calling LLVMDisposeValueMetadataEntries.
See also
llvm::GlobalObject::getAllMetadata()
Definition at line 2150 of file Core.cpp.
References llvm::dyn_cast(), llvm_getMetadata(), and llvm::unwrap().
LLVMGlobalEraseMetadata()
void LLVMGlobalEraseMetadata (LLVMValueRef Global, unsigned Kind)
Erases a metadata attachment of the given kind if it exists.
See also
llvm::GlobalObject::eraseMetadata()
Definition at line 2186 of file Core.cpp.
References llvm::Global, and llvm::unwrap().
LLVMGlobalGetValueType()
LLVMTypeRef LLVMGlobalGetValueType (LLVMValueRef Global)
Returns the "value type" of a global value.
This differs from the formal type of a global value which is always a pointer type.
See also
llvm::GlobalValue::getValueType()
Definition at line 2104 of file Core.cpp.
References llvm::Global, llvm::unwrap(), and llvm::wrap().
LLVMGlobalSetMetadata()
void LLVMGlobalSetMetadata (LLVMValueRef Global, unsigned Kind, LLVMMetadataRef MD)
Sets a metadata attachment, erasing the existing metadata attachment if it already exists for the given kind.
See also
llvm::GlobalObject::setMetadata()
Definition at line 2181 of file Core.cpp.
References llvm::Global, and llvm::unwrap().
LLVMHasUnnamedAddr()
LLVMBool LLVMHasUnnamedAddr (LLVMValueRef Global)
Deprecated: Use LLVMGetUnnamedAddress instead.
Definition at line 2094 of file Core.cpp.
References llvm::Global, and llvm::unwrap().
LLVMIsDeclaration()
LLVMBool LLVMIsDeclaration (LLVMValueRef Global)
Definition at line 1941 of file Core.cpp.
References llvm::Global, and llvm::unwrap().
LLVMSetAlignment()
void LLVMSetAlignment (LLVMValueRef V, unsigned Bytes)
Set the preferred alignment of the value.
See also
llvm::AllocaInst::setAlignment()
llvm::LoadInst::setAlignment()
llvm::StoreInst::setAlignment()
llvm::AtomicRMWInst::setAlignment()
llvm::AtomicCmpXchgInst::setAlignment()
llvm::GlobalValue::setAlignment()
Definition at line 2130 of file Core.cpp.
References Align, llvm::dyn_cast(), llvm_unreachable, P, and llvm::unwrap().
LLVMSetDLLStorageClass()
void LLVMSetDLLStorageClass (LLVMValueRef Global, LLVMDLLStorageClass Class)
Definition at line 2064 of file Core.cpp.
References llvm::Global, and llvm::unwrap().
LLVMSetLinkage()
void LLVMSetLinkage (LLVMValueRef Global, LLVMLinkage Linkage)
Definition at line 1974 of file Core.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GlobalValue::CommonLinkage, llvm::errs(), llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::Global, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, LLVM_DEBUG, LLVMAppendingLinkage, LLVMAvailableExternallyLinkage, LLVMCommonLinkage, LLVMDLLExportLinkage, LLVMDLLImportLinkage, LLVMExternalLinkage, LLVMExternalWeakLinkage, LLVMGhostLinkage, LLVMInternalLinkage, LLVMLinkerPrivateLinkage, LLVMLinkerPrivateWeakLinkage, LLVMLinkOnceAnyLinkage, LLVMLinkOnceODRAutoHideLinkage, LLVMLinkOnceODRLinkage, LLVMPrivateLinkage, LLVMWeakAnyLinkage, LLVMWeakODRLinkage, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::setLinkage(), llvm::unwrap(), llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
LLVMSetSection()
void LLVMSetSection (LLVMValueRef Global, const char * Section)
Definition at line 2045 of file Core.cpp.
References llvm::Global, and llvm::unwrap().
LLVMSetUnnamedAddr()
void LLVMSetUnnamedAddr (LLVMValueRef Global, LLVMBool HasUnnamedAddr)
Deprecated: Use LLVMSetUnnamedAddress instead.
Definition at line 2098 of file Core.cpp.
References llvm::Global, and llvm::unwrap().
LLVMSetUnnamedAddress()
void LLVMSetUnnamedAddress (LLVMValueRef Global, LLVMUnnamedAddr UnnamedAddr)
Definition at line 2081 of file Core.cpp.
References llvm::Global, LLVMGlobalUnnamedAddr, LLVMLocalUnnamedAddr, LLVMNoUnnamedAddr, llvm::GlobalValue::setUnnamedAddr(), and llvm::unwrap().
LLVMSetVisibility()
void LLVMSetVisibility (LLVMValueRef Global, LLVMVisibility Viz)
Definition at line 2054 of file Core.cpp.
References llvm::Global, and llvm::unwrap().
LLVMValueMetadataEntriesGetKind()
unsigned LLVMValueMetadataEntriesGetKind (LLVMValueMetadataEntry * Entries, unsigned Index)
Returns the kind of a value metadata entry at a specific index.
Definition at line 2162 of file Core.cpp.
References LLVMOpaqueValueMetadataEntry::Kind.
LLVMValueMetadataEntriesGetMetadata()
LLVMMetadataRef LLVMValueMetadataEntriesGetMetadata (LLVMValueMetadataEntry * Entries, unsigned Index)
Returns the underlying metadata node of a value metadata entry at a specific index.
Definition at line 2170 of file Core.cpp.
References LLVMOpaqueValueMetadataEntry::Metadata.