LLVM: Object file reading and writing
Object file reading and writing
LLVM-C: C interface to LLVM
Typedefs
typedef struct LLVMOpaqueSectionIterator * LLVMSectionIteratorRef
typedef struct LLVMOpaqueSymbolIterator * LLVMSymbolIteratorRef
typedef struct LLVMOpaqueRelocationIterator * LLVMRelocationIteratorRef
typedef struct LLVMOpaqueObjectFile * LLVMObjectFileRef
Deprecated: Use LLVMBinaryRef instead.
Enumerations
enum LLVMBinaryType {
LLVMBinaryTypeArchive , LLVMBinaryTypeMachOUniversalBinary , LLVMBinaryTypeCOFFImportFile , LLVMBinaryTypeIR ,
LLVMBinaryTypeWinRes , LLVMBinaryTypeCOFF , LLVMBinaryTypeELF32L , LLVMBinaryTypeELF32B ,
LLVMBinaryTypeELF64L , LLVMBinaryTypeELF64B , LLVMBinaryTypeMachO32L , LLVMBinaryTypeMachO32B ,
LLVMBinaryTypeMachO64L , LLVMBinaryTypeMachO64B , LLVMBinaryTypeWasm , LLVMBinaryTypeOffload
}
Functions
LLVMBinaryRef LLVMCreateBinary (LLVMMemoryBufferRef MemBuf, LLVMContextRef Context, char **ErrorMessage)
Create a binary file from the given memory buffer.
void LLVMDisposeBinary (LLVMBinaryRef BR)
Dispose of a binary file.
LLVMMemoryBufferRef LLVMBinaryCopyMemoryBuffer (LLVMBinaryRef BR)
Retrieves a copy of the memory buffer associated with this object file.
LLVMBinaryType LLVMBinaryGetType (LLVMBinaryRef BR)
Retrieve the specific type of a binary.
LLVMBinaryRef LLVMMachOUniversalBinaryCopyObjectForArch (LLVMBinaryRef BR, const char *Arch, size_t ArchLen, char **ErrorMessage)
LLVMSectionIteratorRef LLVMObjectFileCopySectionIterator (LLVMBinaryRef BR)
Retrieve a copy of the section iterator for this object file.
LLVMBool LLVMObjectFileIsSectionIteratorAtEnd (LLVMBinaryRef BR, LLVMSectionIteratorRef SI)
Returns whether the given section iterator is at the end.
LLVMSymbolIteratorRef LLVMObjectFileCopySymbolIterator (LLVMBinaryRef BR)
Retrieve a copy of the symbol iterator for this object file.
LLVMBool LLVMObjectFileIsSymbolIteratorAtEnd (LLVMBinaryRef BR, LLVMSymbolIteratorRef SI)
Returns whether the given symbol iterator is at the end.
void LLVMDisposeSectionIterator (LLVMSectionIteratorRef SI)
void LLVMMoveToNextSection (LLVMSectionIteratorRef SI)
void LLVMMoveToContainingSection (LLVMSectionIteratorRef Sect, LLVMSymbolIteratorRef Sym)
void LLVMDisposeSymbolIterator (LLVMSymbolIteratorRef SI)
void LLVMMoveToNextSymbol (LLVMSymbolIteratorRef SI)
const char * LLVMGetSectionName (LLVMSectionIteratorRef SI)
uint64_t LLVMGetSectionSize (LLVMSectionIteratorRef SI)
const char * LLVMGetSectionContents (LLVMSectionIteratorRef SI)
uint64_t LLVMGetSectionAddress (LLVMSectionIteratorRef SI)
LLVMBool LLVMGetSectionContainsSymbol (LLVMSectionIteratorRef SI, LLVMSymbolIteratorRef Sym)
LLVMRelocationIteratorRef LLVMGetRelocations (LLVMSectionIteratorRef Section)
void LLVMDisposeRelocationIterator (LLVMRelocationIteratorRef RI)
LLVMBool LLVMIsRelocationIteratorAtEnd (LLVMSectionIteratorRef Section, LLVMRelocationIteratorRef RI)
void LLVMMoveToNextRelocation (LLVMRelocationIteratorRef RI)
const char * LLVMGetSymbolName (LLVMSymbolIteratorRef SI)
uint64_t LLVMGetSymbolAddress (LLVMSymbolIteratorRef SI)
uint64_t LLVMGetSymbolSize (LLVMSymbolIteratorRef SI)
uint64_t LLVMGetRelocationOffset (LLVMRelocationIteratorRef RI)
LLVMSymbolIteratorRef LLVMGetRelocationSymbol (LLVMRelocationIteratorRef RI)
uint64_t LLVMGetRelocationType (LLVMRelocationIteratorRef RI)
const char * LLVMGetRelocationTypeName (LLVMRelocationIteratorRef RI)
const char * LLVMGetRelocationValueString (LLVMRelocationIteratorRef RI)
LLVMObjectFileRef LLVMCreateObjectFile (LLVMMemoryBufferRef MemBuf)
Deprecated: Use LLVMCreateBinary instead.
void LLVMDisposeObjectFile (LLVMObjectFileRef ObjectFile)
Deprecated: Use LLVMDisposeBinary instead.
LLVMSectionIteratorRef LLVMGetSections (LLVMObjectFileRef ObjectFile)
Deprecated: Use LLVMObjectFileCopySectionIterator instead.
LLVMBool LLVMIsSectionIteratorAtEnd (LLVMObjectFileRef ObjectFile, LLVMSectionIteratorRef SI)
Deprecated: Use LLVMObjectFileIsSectionIteratorAtEnd instead.
LLVMSymbolIteratorRef LLVMGetSymbols (LLVMObjectFileRef ObjectFile)
Deprecated: Use LLVMObjectFileCopySymbolIterator instead.
LLVMBool LLVMIsSymbolIteratorAtEnd (LLVMObjectFileRef ObjectFile, LLVMSymbolIteratorRef SI)
Deprecated: Use LLVMObjectFileIsSymbolIteratorAtEnd instead.
Detailed Description
Typedef Documentation
LLVMObjectFileRef
typedef struct LLVMOpaqueObjectFile* LLVMObjectFileRef
Deprecated: Use LLVMBinaryRef instead.
Definition at line 205 of file Object.h.
LLVMRelocationIteratorRef
typedef struct LLVMOpaqueRelocationIterator* LLVMRelocationIteratorRef
Definition at line 38 of file Object.h.
LLVMSectionIteratorRef
typedef struct LLVMOpaqueSectionIterator* LLVMSectionIteratorRef
Definition at line 36 of file Object.h.
LLVMSymbolIteratorRef
typedef struct LLVMOpaqueSymbolIterator* LLVMSymbolIteratorRef
Definition at line 37 of file Object.h.
Enumeration Type Documentation
LLVMBinaryType
enum LLVMBinaryType
Enumerator
LLVMBinaryTypeArchive
Archive file.
LLVMBinaryTypeMachOUniversalBinary
Mach-O Universal Binary file.
LLVMBinaryTypeCOFFImportFile
COFF Import file.
LLVMBinaryTypeIR
LLVM IR.
LLVMBinaryTypeWinRes
Windows resource (.res) file.
LLVMBinaryTypeCOFF
COFF Object file.
LLVMBinaryTypeELF32L
ELF 32-bit, little endian.
LLVMBinaryTypeELF32B
ELF 32-bit, big endian.
LLVMBinaryTypeELF64L
ELF 64-bit, little endian.
LLVMBinaryTypeELF64B
ELF 64-bit, big endian.
LLVMBinaryTypeMachO32L
MachO 32-bit, little endian.
LLVMBinaryTypeMachO32B
MachO 32-bit, big endian.
LLVMBinaryTypeMachO64L
MachO 64-bit, little endian.
LLVMBinaryTypeMachO64B
MachO 64-bit, big endian.
LLVMBinaryTypeWasm
Web Assembly.
LLVMBinaryTypeOffload
Offloading fatbinary.
Definition at line 40 of file Object.h.
Function Documentation
LLVMBinaryCopyMemoryBuffer()
LLVMMemoryBufferRef LLVMBinaryCopyMemoryBuffer (LLVMBinaryRef BR)
Retrieves a copy of the memory buffer associated with this object file.
The returned buffer is merely a shallow copy and does not own the actual backing buffer of the binary. Nevertheless, it is the responsibility of the caller to free it with LLVMDisposeMemoryBuffer.
See also
llvm::object::getMemoryBufferRef
Definition at line 79 of file Object.cpp.
References llvm::MemoryBuffer::getMemBuffer(), llvm::unwrap(), and llvm::wrap().
LLVMBinaryGetType()
LLVMBinaryType LLVMBinaryGetType (LLVMBinaryRef BR)
Retrieve the specific type of a binary.
See also
llvm::object::Binary::getType
Definition at line 90 of file Object.cpp.
References getType(), llvm::object::Binary::ID_Archive, llvm::object::Binary::ID_COFF, llvm::object::Binary::ID_COFFImportFile, llvm::object::Binary::ID_ELF32B, llvm::object::Binary::ID_ELF32L, llvm::object::Binary::ID_ELF64B, llvm::object::Binary::ID_ELF64L, llvm::object::Binary::ID_EndObjects, llvm::object::Binary::ID_IR, llvm::object::Binary::ID_MachO32B, llvm::object::Binary::ID_MachO32L, llvm::object::Binary::ID_MachO64B, llvm::object::Binary::ID_MachO64L, llvm::object::Binary::ID_MachOUniversalBinary, llvm::object::Binary::ID_Offload, llvm::object::Binary::ID_StartObjects, llvm::object::Binary::ID_Wasm, llvm::object::Binary::ID_WinRes, llvm_unreachable, LLVMBinaryTypeArchive, LLVMBinaryTypeCOFF, LLVMBinaryTypeCOFFImportFile, LLVMBinaryTypeELF32B, LLVMBinaryTypeELF32L, LLVMBinaryTypeELF64B, LLVMBinaryTypeELF64L, LLVMBinaryTypeIR, LLVMBinaryTypeMachO32B, LLVMBinaryTypeMachO32L, LLVMBinaryTypeMachO64B, LLVMBinaryTypeMachO64L, LLVMBinaryTypeMachOUniversalBinary, LLVMBinaryTypeOffload, LLVMBinaryTypeWasm, LLVMBinaryTypeWinRes, and llvm::unwrap().
LLVMCreateBinary()
LLVMBinaryRef LLVMCreateBinary (LLVMMemoryBufferRef MemBuf, LLVMContextRef Context, char ** ErrorMessage)
Create a binary file from the given memory buffer.
The exact type of the binary file will be inferred automatically, and the appropriate implementation selected. The context may be NULL except if the resulting file is an LLVM IR file.
The memory buffer is not consumed by this function. It is the responsibilty of the caller to free it with LLVMDisposeMemoryBuffer.
If NULL is returned, the ErrorMessage parameter is populated with the error's description. It is then the caller's responsibility to free this message by calling LLVMDisposeMessage.
See also
llvm::object::createBinary
Definition at line 65 of file Object.cpp.
References llvm::object::createBinary(), llvm::Expected< T >::get(), llvm::Expected< T >::takeError(), llvm::dwarf::toString(), llvm::unwrap(), and llvm::wrap().
LLVMCreateObjectFile()
LLVMObjectFileRef LLVMCreateObjectFile (LLVMMemoryBufferRef MemBuf)
Deprecated: Use LLVMCreateBinary instead.
Definition at line 181 of file Object.cpp.
References llvm::consumeError(), llvm::Expected< T >::get(), llvm::Expected< T >::takeError(), llvm::unwrap(), and llvm::wrap().
LLVMDisposeBinary()
void LLVMDisposeBinary (LLVMBinaryRef BR)
Dispose of a binary file.
The binary file does not own its backing buffer. It is the responsibilty of the caller to free it with LLVMDisposeMemoryBuffer.
Definition at line 86 of file Object.cpp.
References llvm::unwrap().
LLVMDisposeObjectFile()
void LLVMDisposeObjectFile (LLVMObjectFileRef ObjectFile)
Deprecated: Use LLVMDisposeBinary instead.
Definition at line 196 of file Object.cpp.
References llvm::unwrap().
LLVMDisposeRelocationIterator()
void LLVMDisposeRelocationIterator (LLVMRelocationIteratorRef RI)
Definition at line 288 of file Object.cpp.
References llvm::unwrap().
LLVMDisposeSectionIterator()
void LLVMDisposeSectionIterator (LLVMSectionIteratorRef SI)
Definition at line 207 of file Object.cpp.
References llvm::unwrap().
LLVMDisposeSymbolIterator()
void LLVMDisposeSymbolIterator (LLVMSymbolIteratorRef SI)
Definition at line 240 of file Object.cpp.
References llvm::unwrap().
LLVMGetRelocationOffset()
uint64_t LLVMGetRelocationOffset (LLVMRelocationIteratorRef RI)
Definition at line 330 of file Object.cpp.
References llvm::unwrap().
LLVMGetRelocations()
LLVMRelocationIteratorRef LLVMGetRelocations (LLVMSectionIteratorRef Section)
Definition at line 283 of file Object.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetRelocationSymbol()
LLVMSymbolIteratorRef LLVMGetRelocationSymbol (LLVMRelocationIteratorRef RI)
Definition at line 334 of file Object.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetRelocationType()
uint64_t LLVMGetRelocationType (LLVMRelocationIteratorRef RI)
Definition at line 339 of file Object.cpp.
References llvm::unwrap().
LLVMGetRelocationTypeName()
const char * LLVMGetRelocationTypeName (LLVMRelocationIteratorRef RI)
Definition at line 344 of file Object.cpp.
References llvm::copy(), llvm::getTypeName(), llvm::safe_malloc(), llvm::SmallVectorBase< Size_T >::size(), and llvm::unwrap().
LLVMGetRelocationValueString()
const char * LLVMGetRelocationValueString (LLVMRelocationIteratorRef RI)
Definition at line 353 of file Object.cpp.
LLVMGetSectionAddress()
uint64_t LLVMGetSectionAddress (LLVMSectionIteratorRef SI)
Definition at line 273 of file Object.cpp.
References llvm::unwrap().
LLVMGetSectionContainsSymbol()
LLVMBool LLVMGetSectionContainsSymbol (LLVMSectionIteratorRef SI, LLVMSymbolIteratorRef Sym)
Definition at line 277 of file Object.cpp.
References Sym, and llvm::unwrap().
LLVMGetSectionContents()
const char * LLVMGetSectionContents (LLVMSectionIteratorRef SI)
Definition at line 266 of file Object.cpp.
References llvm::report_fatal_error(), and llvm::unwrap().
LLVMGetSectionName()
const char * LLVMGetSectionName (LLVMSectionIteratorRef SI)
Definition at line 255 of file Object.cpp.
References getName(), llvm::report_fatal_error(), and llvm::unwrap().
LLVMGetSections()
LLVMSectionIteratorRef LLVMGetSections (LLVMObjectFileRef ObjectFile)
Deprecated: Use LLVMObjectFileCopySectionIterator instead.
Definition at line 201 of file Object.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetSectionSize()
uint64_t LLVMGetSectionSize (LLVMSectionIteratorRef SI)
Definition at line 262 of file Object.cpp.
References llvm::unwrap().
LLVMGetSymbolAddress()
uint64_t LLVMGetSymbolAddress (LLVMSymbolIteratorRef SI)
Definition at line 314 of file Object.cpp.
References getAddress(), llvm::logAllUnhandledErrors(), OS, llvm::report_fatal_error(), and llvm::unwrap().
LLVMGetSymbolName()
const char * LLVMGetSymbolName (LLVMSymbolIteratorRef SI)
Definition at line 303 of file Object.cpp.
References getName(), llvm::logAllUnhandledErrors(), OS, llvm::report_fatal_error(), and llvm::unwrap().
LLVMGetSymbols()
LLVMSymbolIteratorRef LLVMGetSymbols (LLVMObjectFileRef ObjectFile)
Deprecated: Use LLVMObjectFileCopySymbolIterator instead.
Definition at line 234 of file Object.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetSymbolSize()
uint64_t LLVMGetSymbolSize (LLVMSymbolIteratorRef SI)
Definition at line 325 of file Object.cpp.
References llvm::unwrap().
LLVMIsRelocationIteratorAtEnd()
LLVMBool LLVMIsRelocationIteratorAtEnd (LLVMSectionIteratorRef Section, LLVMRelocationIteratorRef RI)
Definition at line 292 of file Object.cpp.
References llvm::unwrap().
LLVMIsSectionIteratorAtEnd()
LLVMBool LLVMIsSectionIteratorAtEnd (LLVMObjectFileRef ObjectFile, LLVMSectionIteratorRef SI)
Deprecated: Use LLVMObjectFileIsSectionIteratorAtEnd instead.
Definition at line 211 of file Object.cpp.
References llvm::unwrap().
LLVMIsSymbolIteratorAtEnd()
LLVMBool LLVMIsSymbolIteratorAtEnd (LLVMObjectFileRef ObjectFile, LLVMSymbolIteratorRef SI)
Deprecated: Use LLVMObjectFileIsSymbolIteratorAtEnd instead.
Definition at line 244 of file Object.cpp.
References llvm::unwrap().
LLVMMachOUniversalBinaryCopyObjectForArch()
LLVMBinaryRef LLVMMachOUniversalBinaryCopyObjectForArch (LLVMBinaryRef BR, const char * Arch, size_t ArchLen, char ** ErrorMessage)
Definition at line 138 of file Object.cpp.
References llvm::cast(), llvm::Expected< T >::get(), llvm::Expected< T >::takeError(), llvm::dwarf::toString(), llvm::unwrap(), and llvm::wrap().
LLVMMoveToContainingSection()
void LLVMMoveToContainingSection (LLVMSectionIteratorRef Sect, LLVMSymbolIteratorRef Sym)
Definition at line 221 of file Object.cpp.
References llvm::object::getSection(), llvm::logAllUnhandledErrors(), OS, llvm::report_fatal_error(), Sym, llvm::Expected< T >::takeError(), and llvm::unwrap().
LLVMMoveToNextRelocation()
void LLVMMoveToNextRelocation (LLVMRelocationIteratorRef RI)
Definition at line 297 of file Object.cpp.
References llvm::unwrap().
LLVMMoveToNextSection()
void LLVMMoveToNextSection (LLVMSectionIteratorRef SI)
Definition at line 217 of file Object.cpp.
References llvm::unwrap().
LLVMMoveToNextSymbol()
void LLVMMoveToNextSymbol (LLVMSymbolIteratorRef SI)
Definition at line 250 of file Object.cpp.
References llvm::unwrap().
LLVMObjectFileCopySectionIterator()
LLVMSectionIteratorRef LLVMObjectFileCopySectionIterator (LLVMBinaryRef BR)
Retrieve a copy of the section iterator for this object file.
If there are no sections, the result is NULL.
The returned iterator is merely a shallow copy. Nevertheless, it is the responsibility of the caller to free it with LLVMDisposeSectionIterator.
See also
llvm::object::sections()
Definition at line 152 of file Object.cpp.
References llvm::cast(), sections, llvm::unwrap(), and llvm::wrap().
LLVMObjectFileCopySymbolIterator()
LLVMSymbolIteratorRef LLVMObjectFileCopySymbolIterator (LLVMBinaryRef BR)
Retrieve a copy of the symbol iterator for this object file.
If there are no symbols, the result is NULL.
The returned iterator is merely a shallow copy. Nevertheless, it is the responsibility of the caller to free it with LLVMDisposeSymbolIterator.
See also
llvm::object::symbols()
Definition at line 166 of file Object.cpp.
References llvm::cast(), llvm::unwrap(), and llvm::wrap().
LLVMObjectFileIsSectionIteratorAtEnd()
LLVMBool LLVMObjectFileIsSectionIteratorAtEnd (LLVMBinaryRef BR, LLVMSectionIteratorRef SI)
Returns whether the given section iterator is at the end.
See also
llvm::object::section_end
Definition at line 160 of file Object.cpp.
References llvm::cast(), and llvm::unwrap().
LLVMObjectFileIsSymbolIteratorAtEnd()
LLVMBool LLVMObjectFileIsSymbolIteratorAtEnd (LLVMBinaryRef BR, LLVMSymbolIteratorRef SI)
Returns whether the given symbol iterator is at the end.
See also
llvm::object::symbol_end
Definition at line 174 of file Object.cpp.
References llvm::cast(), and llvm::unwrap().