LLVM: lib/Analysis/IndirectCallPromotionAnalysis.cpp File Reference
IndirectCallPromotionAnalysis.cpp File Reference
#include "llvm/Analysis/IndirectCallPromotionAnalysis.h"
#include "llvm/IR/Instruction.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include <memory>
Macros
#define DEBUG_TYPE "pgo-icall-prom-analysis"
Variables
static cl::opt< unsigned > ICPRemainingPercentThreshold ("icp-remaining-percent-threshold", cl::init(30), cl::Hidden, cl::desc("The percentage threshold against remaining unpromoted indirect " "call count for the promotion"))
static cl::opt< unsigned > ICPTotalPercentThreshold ("icp-total-percent-threshold", cl::init(5), cl::Hidden, cl::desc("The percentage threshold against total " "count for the promotion"))
static cl::opt< unsigned > MaxNumPromotions ("icp-max-prom", cl::init(3), cl::Hidden, cl::desc("Max number of promotions for a single indirect " "call callsite"))
cl::opt< unsigned > MaxNumVTableAnnotations ("icp-max-num-vtables", cl::init(6), cl::Hidden, cl::desc("Max number of vtables annotated for a vtable load instruction."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "pgo-icall-prom-analysis"
Definition at line 24 of file IndirectCallPromotionAnalysis.cpp.
Variable Documentation
ICPRemainingPercentThreshold
cl::opt< unsigned > ICPRemainingPercentThreshold("icp-remaining-percent-threshold", cl::init(30), cl::Hidden, cl::desc("The percentage threshold against remaining unpromoted indirect " "call count for the promotion")) ("icp-remaining-percent-threshold" , cl::init(30) , cl::Hidden , cl::desc("The percentage threshold against remaining unpromoted indirect " "call count for the promotion")) static
ICPTotalPercentThreshold
cl::opt< unsigned > ICPTotalPercentThreshold("icp-total-percent-threshold", cl::init(5), cl::Hidden, cl::desc("The percentage threshold against total " "count for the promotion")) ("icp-total-percent-threshold" , cl::init(5) , cl::Hidden , cl::desc("The percentage threshold against total " "count for the promotion")) static
MaxNumPromotions
cl::opt< unsigned > MaxNumPromotions("icp-max-prom", cl::init(3), cl::Hidden, cl::desc("Max number of promotions for a single indirect " "call callsite")) ("icp-max-prom" , cl::init(3) , cl::Hidden , cl::desc("Max number of promotions for a single indirect " "call callsite")) static
Referenced by doesHistoryAllowICP(), llvm::ICallPromotionAnalysis::getPromotionCandidatesForInstruction(), and updateIDTMetaData().
MaxNumVTableAnnotations
cl::opt< unsigned > MaxNumVTableAnnotations("icp-max-num-vtables", cl::init(6), cl::Hidden, cl::desc("Max number of vtables annotated for a vtable load instruction.")) ("icp-max-num-vtables" , cl::init(6) , cl::Hidden , cl::desc("Max number of vtables annotated for a vtable load instruction."))
Referenced by getMaxNumAnnotations().