LLVM: lib/Transforms/Scalar/InferAlignment.cpp File Reference
InferAlignment.cpp File Reference
#include "llvm/Transforms/Scalar/InferAlignment.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Instructions.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/Local.h"
Functions
static bool tryToImproveAlign (const DataLayout &DL, Instruction *I, function_ref< Align(Value *PtrOp, Align OldAlign, Align PrefAlign)> Fn)
bool inferAlignment (Function &F, AssumptionCache &AC, DominatorTree &DT)
Function Documentation
inferAlignment()
bool inferAlignment (Function & F, AssumptionCache & AC, DominatorTree & DT)
Definition at line 50 of file InferAlignment.cpp.
References Align, Changed, llvm::computeKnownBits(), llvm::KnownBits::countMinTrailingZeros(), DL, F, llvm::KnownBits::getBitWidth(), I, llvm::tryEnforceAlignment(), and tryToImproveAlign().
Referenced by llvm::InferAlignmentPass::run().
tryToImproveAlign()
static bool tryToImproveAlign (const DataLayout & DL, Instruction * I, function_ref< Align(Value *PtrOp, Align OldAlign, Align PrefAlign)> Fn) static
Definition at line 25 of file InferAlignment.cpp.
References DL, llvm::dyn_cast(), llvm::Value::getType(), and I.
Referenced by inferAlignment().