LLVM: lib/ProfileData/InstrProfReader.cpp File Reference
InstrProfReader.cpp File Reference
#include "llvm/ProfileData/InstrProfReader.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/IR/ProfileSummary.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/ProfileData/MemProf.h"
#include "llvm/ProfileData/ProfileCommon.h"
#include "llvm/ProfileData/SymbolRemappingReader.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SwapByteOrder.h"
#include "llvm/Support/VirtualFileSystem.h"
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <memory>
#include <optional>
#include <system_error>
#include <utility>
#include <vector>
Classes
class llvm::InstrProfReaderItaniumRemapper< HashTableImpl >
A remapper that applies remappings based on a symbol remapping file.
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define CHECK_LINE_END(Line)
#define READ_NUM(Str, Dst)
#define VP_READ_ADVANCE(Val)
Typedefs
using data_type = InstrProfLookupTrait::data_type
using offset_type = InstrProfLookupTrait::offset_type
Functions
static InstrProfKind getProfileKindFromVersion (uint64_t Version)
static Expected< std::unique_ptr< MemoryBuffer > > setupMemoryBuffer (const Twine &Filename, vfs::FileSystem &FS)
static Error initializeReader (InstrProfReader &Reader)
static Error readBinaryIdsInternal (const MemoryBuffer &DataBuffer, ArrayRef< uint8_t > BinaryIdsBuffer, std::vector< llvm::object::BuildID > &BinaryIds, const llvm::endianness Endian)
Read a list of binary ids from a profile that consist of a.
static void printBinaryIdsInternal (raw_ostream &OS, ArrayRef< llvm::object::BuildID > BinaryIds)
static Expected< memprof::MemProfRecord > getMemProfRecordV0 (const memprof::IndexedMemProfRecord &IndexedRecord, MemProfFrameHashTable &MemProfFrameTable)
static Expected< memprof::MemProfRecord > getMemProfRecordV2 (const memprof::IndexedMemProfRecord &IndexedRecord, MemProfFrameHashTable &MemProfFrameTable, MemProfCallStackHashTable &MemProfCallStackTable)
static Expected< memprof::MemProfRecord > getMemProfRecordV3 (const memprof::IndexedMemProfRecord &IndexedRecord, const unsigned char *FrameBase, const unsigned char *CallStackBase)
Macro Definition Documentation
CHECK_LINE_END
#define CHECK_LINE_END (Line)
Value:
  if (Line.is_at_end())                                                        \
    return error(instrprof_error::truncated);
READ_NUM
#define READ_NUM (Str, Dst)
Value:
  if ((Str).getAsInteger(10, (Dst)))                                           \
    return error(instrprof_error::malformed);
VP_READ_ADVANCE
#define VP_READ_ADVANCE (Val)
Value:
  CHECK_LINE_END(Line);                                                        \
  uint32_t Val;                                                                \
  READ_NUM((*Line), (Val));                                                    \
  Line++;
Typedef Documentation
data_type
using data_type = InstrProfLookupTrait::data_type
Definition at line 887 of file InstrProfReader.cpp.
offset_type
using offset_type = InstrProfLookupTrait::offset_type
Definition at line 888 of file InstrProfReader.cpp.
Function Documentation
getMemProfRecordV0()
static Expected< memprof::MemProfRecord > getMemProfRecordV0 (const memprof::IndexedMemProfRecord & IndexedRecord, MemProfFrameHashTable & MemProfFrameTable) static
Definition at line 1541 of file InstrProfReader.cpp.
References llvm::hash_mismatch, llvm::memprof::FrameIdConverter< MapTy >::LastUnmappedId, and llvm::make_error().
Referenced by llvm::IndexedMemProfReader::getMemProfRecord().
getMemProfRecordV2()
static Expected< memprof::MemProfRecord > getMemProfRecordV2 (const memprof::IndexedMemProfRecord & IndexedRecord, MemProfFrameHashTable & MemProfFrameTable, MemProfCallStackHashTable & MemProfCallStackTable) static
Definition at line 1560 of file InstrProfReader.cpp.
References llvm::hash_mismatch, llvm::memprof::CallStackIdConverter< MapTy >::LastUnmappedId, llvm::memprof::FrameIdConverter< MapTy >::LastUnmappedId, llvm::make_error(), and llvm::memprof::IndexedMemProfRecord::toMemProfRecord().
Referenced by llvm::IndexedMemProfReader::getMemProfRecord().
getMemProfRecordV3()
static Expected< memprof::MemProfRecord > getMemProfRecordV3 (const memprof::IndexedMemProfRecord & IndexedRecord, const unsigned char * FrameBase, const unsigned char * CallStackBase) static
Definition at line 1590 of file InstrProfReader.cpp.
References llvm::memprof::IndexedMemProfRecord::toMemProfRecord().
Referenced by llvm::IndexedMemProfReader::getMemProfRecord().
getProfileKindFromVersion()
static InstrProfKind getProfileKindFromVersion (uint64_t Version) static
Definition at line 45 of file InstrProfReader.cpp.
References VARIANT_MASK_BYTE_COVERAGE, VARIANT_MASK_CSIR_PROF, VARIANT_MASK_FUNCTION_ENTRY_ONLY, VARIANT_MASK_INSTR_ENTRY, VARIANT_MASK_IR_PROF, VARIANT_MASK_MEMPROF, and VARIANT_MASK_TEMPORAL_PROF.
Referenced by llvm::InstrProfReaderIndex< HashTableImpl >::getProfileKind(), and llvm::RawInstrProfReader< IntPtrT >::getProfileKind().
initializeReader()
static Error initializeReader (InstrProfReader & Reader) static
Definition at line 80 of file InstrProfReader.cpp.
References llvm::InstrProfReader::readHeader().
Referenced by llvm::IndexedInstrProfReader::create(), and llvm::InstrProfReader::create().
printBinaryIdsInternal()
static void printBinaryIdsInternal (raw_ostream & OS, ArrayRef< llvm::object::BuildID > BinaryIds) static
Definition at line 143 of file InstrProfReader.cpp.
References llvm::format(), I, and OS.
Referenced by llvm::IndexedInstrProfReader::printBinaryIds(), and llvm::RawInstrProfReader< IntPtrT >::printBinaryIds().
readBinaryIdsInternal()
static Error readBinaryIdsInternal (const MemoryBuffer & DataBuffer, ArrayRef< uint8_t > BinaryIdsBuffer, std::vector< llvm::object::BuildID > & BinaryIds, const llvm::endianness Endian) static
Read a list of binary ids from a profile that consist of a.
uint64_t binary id length b. uint8_t binary id data c. uint8_t padding (if necessary) This function is shared between raw and indexed profiles. Raw profiles are in host-endian format, and indexed profiles are in little-endian format. So, this function takes an argument indicating the associated endian format to read the binary ids correctly.
Definition at line 93 of file InstrProfReader.cpp.
References llvm::alignToPowerOf2(), llvm::ArrayRef< T >::data(), End, llvm::MemoryBuffer::getBufferEnd(), llvm::make_error(), llvm::support::endian::readNext(), llvm::ArrayRef< T >::size(), and llvm::Error::success().
Referenced by llvm::IndexedInstrProfReader::readBinaryIds().
setupMemoryBuffer()
static Expected< std::unique_ptr< MemoryBuffer > > setupMemoryBuffer (const Twine & Filename, vfs::FileSystem & FS) static
Definition at line 72 of file InstrProfReader.cpp.
References llvm::errorCodeToError(), and llvm::MemoryBuffer::getSTDIN().
Referenced by llvm::IndexedInstrProfReader::create(), llvm::InstrProfReader::create(), llvm::sampleprof::SampleProfileReader::create(), and llvm::sampleprof::SampleProfileReaderItaniumRemapper::create().