LLVM: lib/ProfileData/InstrProfWriter.cpp File Reference
InstrProfWriter.cpp File Reference
#include "llvm/ProfileData/InstrProfWriter.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/IR/ProfileSummary.h"
#include "llvm/ProfileData/InstrProf.h"
#include "llvm/ProfileData/MemProf.h"
#include "llvm/ProfileData/ProfileCommon.h"
#include "llvm/Support/Compression.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/EndianStream.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/OnDiskHashTable.h"
#include "llvm/Support/raw_ostream.h"
#include <cstdint>
#include <memory>
#include <string>
#include <tuple>
#include <utility>
#include <vector>
#include "llvm/ProfileData/InstrProfData.inc"
Classes
struct PatchItem
class llvm::ProfOStream
class llvm::InstrProfRecordWriterTrait
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define VALUE_PROF_KIND(Enumerator, Value, Descr)
#define INSTR_PROF_VISIBILITY
#define INSTR_PROF_DATA(Type, LLVMType, Name, Initializer)
#define INSTR_PROF_VTABLE_DATA(Type, LLVMType, Name, Initializer)
#define INSTR_PROF_VALUE_NODE(Type, LLVMType, Name, Initializer)
#define INSTR_PROF_RAW_HEADER(Type, Name, Initializer)
#define VALUE_PROF_FUNC_PARAM(ArgType, ArgName, ArgLLVMType)
#define INSTR_PROF_COMMA
#define INSTR_PROF_DATA_DEFINED
#define COVMAP_FUNC_RECORD(Type, LLVMType, Name, Initializer)
#define COVMAP_HEADER(Type, LLVMType, Name, Initializer)
Functions
static void setSummary (IndexedInstrProf::Summary *TheSummary, ProfileSummary &PS)
static void writeMemProfSchema (ProfOStream &OS, const memprof::MemProfSchema &Schema)
static uint64_t writeMemProfRecords (ProfOStream &OS, llvm::MapVector< GlobalValue::GUID, memprof::IndexedMemProfRecord > &MemProfRecordData, memprof::MemProfSchema *Schema, memprof::IndexedVersion Version, llvm::DenseMap< memprof::CallStackId, memprof::LinearCallStackId > *MemProfCallStackIndexes=nullptr)
static uint64_t writeMemProfFrames (ProfOStream &OS, llvm::MapVector< memprof::FrameId, memprof::Frame > &MemProfFrameData)
static llvm::DenseMap< memprof::FrameId, memprof::LinearFrameId > writeMemProfFrameArray (ProfOStream &OS, llvm::MapVector< memprof::FrameId, memprof::Frame > &MemProfFrameData, llvm::DenseMap< memprof::FrameId, memprof::FrameStat > &FrameHistogram)
static uint64_t writeMemProfCallStacks (ProfOStream &OS, llvm::MapVector< memprof::CallStackId, llvm::SmallVector< memprof::FrameId > > &MemProfCallStackData)
static llvm::DenseMap< memprof::CallStackId, memprof::LinearCallStackId > writeMemProfCallStackArray (ProfOStream &OS, llvm::MapVector< memprof::CallStackId, llvm::SmallVector< memprof::FrameId > > &MemProfCallStackData, llvm::DenseMap< memprof::FrameId, memprof::LinearFrameId > &MemProfFrameIndexes, llvm::DenseMap< memprof::FrameId, memprof::FrameStat > &FrameHistogram)
static Error writeMemProfV0 (ProfOStream &OS, memprof::IndexedMemProfData &MemProfData)
static Error writeMemProfV1 (ProfOStream &OS, memprof::IndexedMemProfData &MemProfData)
static Error writeMemProfV2 (ProfOStream &OS, memprof::IndexedMemProfData &MemProfData, bool MemProfFullSchema)
static Error writeMemProfV3 (ProfOStream &OS, memprof::IndexedMemProfData &MemProfData, bool MemProfFullSchema)
static Error writeMemProf (ProfOStream &OS, memprof::IndexedMemProfData &MemProfData, memprof::IndexedVersion MemProfVersionRequested, bool MemProfFullSchema)
Variables
static const char * ValueProfKindStr []
Macro Definition Documentation
COVMAP_FUNC_RECORD
#define COVMAP_FUNC_RECORD (Type, LLVMType, Name, Initializer)
COVMAP_HEADER
#define COVMAP_HEADER (Type, LLVMType, Name, Initializer)
INSTR_PROF_COMMA
#define INSTR_PROF_COMMA
INSTR_PROF_DATA
#define INSTR_PROF_DATA (Type, LLVMType, Name, Initializer)
INSTR_PROF_DATA_DEFINED
#define INSTR_PROF_DATA_DEFINED
INSTR_PROF_RAW_HEADER
#define INSTR_PROF_RAW_HEADER (Type, Name, Initializer)
INSTR_PROF_VALUE_NODE
#define INSTR_PROF_VALUE_NODE (Type, LLVMType, Name, Initializer)
INSTR_PROF_VISIBILITY
#define INSTR_PROF_VISIBILITY
INSTR_PROF_VTABLE_DATA
#define INSTR_PROF_VTABLE_DATA (Type, LLVMType, Name, Initializer)
VALUE_PROF_FUNC_PARAM
#define VALUE_PROF_FUNC_PARAM (ArgType, ArgName, ArgLLVMType)
VALUE_PROF_KIND
#define VALUE_PROF_KIND (Enumerator, Value, Descr)
Value:
#Enumerator,
Function Documentation
setSummary()
static void setSummary (IndexedInstrProf::Summary * TheSummary, ProfileSummary & PS) static
Definition at line 425 of file InstrProfWriter.cpp.
References llvm::ProfileSummary::getDetailedSummary(), llvm::ProfileSummary::getMaxCount(), llvm::ProfileSummary::getMaxFunctionCount(), llvm::ProfileSummary::getMaxInternalCount(), llvm::ProfileSummary::getNumCounts(), llvm::ProfileSummary::getNumFunctions(), llvm::ProfileSummary::getTotalCount(), I, llvm::IndexedInstrProf::Summary::NumCutoffEntries, llvm::IndexedInstrProf::Summary::NumSummaryFields, llvm::IndexedInstrProf::Summary::set(), and llvm::IndexedInstrProf::Summary::setEntry().
writeMemProf()
static Error writeMemProf (ProfOStream & OS, memprof::IndexedMemProfData & MemProfData, memprof::IndexedVersion MemProfVersionRequested, bool MemProfFullSchema) static
Definition at line 759 of file InstrProfWriter.cpp.
References llvm::formatv(), llvm::make_error(), llvm::memprof::MaximumSupportedVersion, llvm::memprof::MinimumSupportedVersion, OS, llvm::unsupported_version, llvm::memprof::Version0, llvm::memprof::Version1, llvm::memprof::Version2, llvm::memprof::Version3, writeMemProfV0(), writeMemProfV1(), writeMemProfV2(), and writeMemProfV3().
writeMemProfCallStackArray()
static llvm::DenseMap< memprof::CallStackId, memprof::LinearCallStackId > writeMemProfCallStackArray (ProfOStream & OS, llvm::MapVector< memprof::CallStackId, llvm::SmallVector< memprof::FrameId > > & MemProfCallStackData, llvm::DenseMap< memprof::FrameId, memprof::LinearFrameId > & MemProfFrameIndexes, llvm::DenseMap< memprof::FrameId, memprof::FrameStat > & FrameHistogram) static
Definition at line 563 of file InstrProfWriter.cpp.
References llvm::memprof::CallStackRadixTreeBuilder::build(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), I, and OS.
Referenced by writeMemProfV3().
writeMemProfCallStacks()
static uint64_t writeMemProfCallStacks (ProfOStream & OS, llvm::MapVector< memprof::CallStackId, llvm::SmallVector< memprof::FrameId > > & MemProfCallStackData) static
Definition at line 548 of file InstrProfWriter.cpp.
References llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), and OS.
Referenced by writeMemProfV2().
writeMemProfFrameArray()
static llvm::DenseMap< memprof::FrameId, memprof::LinearFrameId > writeMemProfFrameArray (ProfOStream & OS, llvm::MapVector< memprof::FrameId, memprof::Frame > & MemProfFrameData, llvm::DenseMap< memprof::FrameId, memprof::FrameStat > & FrameHistogram) static
Definition at line 494 of file InstrProfWriter.cpp.
References assert(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::clear(), F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), OS, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::reserve(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::size(), and llvm::sort().
Referenced by writeMemProfV3().
writeMemProfFrames()
static uint64_t writeMemProfFrames (ProfOStream & OS, llvm::MapVector< memprof::FrameId, memprof::Frame > & MemProfFrameData) static
Definition at line 476 of file InstrProfWriter.cpp.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::clear(), llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), and OS.
Referenced by writeMemProfV0(), writeMemProfV1(), and writeMemProfV2().
writeMemProfRecords()
static uint64_t writeMemProfRecords (ProfOStream & OS, llvm::MapVector< GlobalValue::GUID, memprof::IndexedMemProfRecord > & MemProfRecordData, memprof::MemProfSchema * Schema, memprof::IndexedVersion Version, llvm::DenseMap< memprof::CallStackId, memprof::LinearCallStackId > * MemProfCallStackIndexes = nullptr) static
Definition at line 451 of file InstrProfWriter.cpp.
References llvm::MapVector< KeyT, ValueT, MapType, VectorType >::clear(), llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), and OS.
Referenced by writeMemProfV0(), writeMemProfV1(), writeMemProfV2(), and writeMemProfV3().
writeMemProfSchema()
static void writeMemProfSchema (ProfOStream & OS, const memprof::MemProfSchema & Schema) static
Definition at line 443 of file InstrProfWriter.cpp.
References OS, llvm::SmallVectorBase< Size_T >::size(), and llvm::raw_ostream::write().
Referenced by writeMemProfV0(), writeMemProfV1(), writeMemProfV2(), and writeMemProfV3().
writeMemProfV0()
static Error writeMemProfV0 (ProfOStream & OS, memprof::IndexedMemProfData & MemProfData) static
Definition at line 597 of file InstrProfWriter.cpp.
References llvm::memprof::IndexedMemProfData::Frames, llvm::memprof::getFullSchema(), OS, llvm::memprof::IndexedMemProfData::Records, llvm::Error::success(), llvm::raw_ostream::tell(), llvm::memprof::Version0, llvm::raw_ostream::write(), writeMemProfFrames(), writeMemProfRecords(), and writeMemProfSchema().
Referenced by writeMemProf().
writeMemProfV1()
static Error writeMemProfV1 (ProfOStream & OS, memprof::IndexedMemProfData & MemProfData) static
Definition at line 631 of file InstrProfWriter.cpp.
References llvm::memprof::IndexedMemProfData::Frames, llvm::memprof::getFullSchema(), OS, llvm::memprof::IndexedMemProfData::Records, llvm::Error::success(), llvm::raw_ostream::tell(), llvm::memprof::Version1, llvm::raw_ostream::write(), writeMemProfFrames(), writeMemProfRecords(), and writeMemProfSchema().
Referenced by writeMemProf().
writeMemProfV2()
static Error writeMemProfV2 (ProfOStream & OS, memprof::IndexedMemProfData & MemProfData, bool MemProfFullSchema) static
Definition at line 669 of file InstrProfWriter.cpp.
References llvm::memprof::IndexedMemProfData::CallStacks, llvm::memprof::IndexedMemProfData::Frames, llvm::memprof::getFullSchema(), llvm::memprof::getHotColdSchema(), OS, llvm::memprof::IndexedMemProfData::Records, llvm::Error::success(), llvm::raw_ostream::tell(), llvm::memprof::Version2, llvm::raw_ostream::write(), writeMemProfCallStacks(), writeMemProfFrames(), writeMemProfRecords(), and writeMemProfSchema().
Referenced by writeMemProf().
writeMemProfV3()
static Error writeMemProfV3 (ProfOStream & OS, memprof::IndexedMemProfData & MemProfData, bool MemProfFullSchema) static
Definition at line 717 of file InstrProfWriter.cpp.
References assert(), llvm::memprof::IndexedMemProfData::CallStacks, llvm::memprof::computeFrameHistogram(), llvm::memprof::IndexedMemProfData::Frames, llvm::memprof::getFullSchema(), llvm::memprof::getHotColdSchema(), OS, llvm::memprof::IndexedMemProfData::Records, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), llvm::Error::success(), llvm::raw_ostream::tell(), llvm::memprof::Version3, llvm::raw_ostream::write(), writeMemProfCallStackArray(), writeMemProfFrameArray(), writeMemProfRecords(), and writeMemProfSchema().
Referenced by writeMemProf().
Variable Documentation
ValueProfKindStr
const char* ValueProfKindStr[] static
Definition at line 1031 of file InstrProfWriter.cpp.
Referenced by llvm::InstrProfWriter::writeRecordInText().