LLVM: lib/IR/IntrinsicInst.cpp File Reference
IntrinsicInst.cpp File Reference
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/IR/Statepoint.h"
#include <optional>
#include "llvm/IR/VPIntrinsics.def"
Macros
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, MASKPOS, VLENPOS)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, MASKPOS, VLENPOS)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_MEMOP(POINTERPOS, ...)
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_MEMOP(POINTERPOS, DATAPOS)
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, MASKPOS, VLENPOS)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_FUNCTIONAL_OPC(OPC)
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_FUNCTIONAL_INTRINSIC(INTRIN)
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_NO_FUNCTIONAL return true;
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_CONSTRAINEDFP(HASRND, HASEXCEPT, CID)
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_FUNCTIONAL_OPC(OPC)
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_FUNCTIONAL_INTRINSIC(INTRIN)
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_REDUCTION(STARTPOS, ...)
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_CASTOP return true;
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_CMP(CCPOS, ...)
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_BINARYOP return true;
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_CMP(CCPOS, ISFP)
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_REDUCTION(STARTPOS, VECTORPOS)
#define END_REGISTER_VP_INTRINSIC(VPID)
#define BEGIN_REGISTER_VP_INTRINSIC(VPID, ...)
#define VP_PROPERTY_REDUCTION(STARTPOS, VECTORPOS)
#define END_REGISTER_VP_INTRINSIC(VPID)
Functions
static ValueAsMetadata * getAsMetadata (Value *V)
static FCmpInst::Predicate getFPPredicateFromMD (const Value *Op)
constexpr bool isVPIntrinsic (Intrinsic::ID ID)
static constexpr std::optional< unsigned > getFunctionalOpcodeForVP (Intrinsic::ID ID)
static constexpr std::optional< Intrinsic::ID > getFunctionalIntrinsicIDForVP (Intrinsic::ID ID)
static constexpr bool doesVPHaveNoFunctionalEquivalent (Intrinsic::ID ID)
static constexpr Intrinsic::ID getForIntrinsic (Intrinsic::ID Id)
static ICmpInst::Predicate getIntPredicateFromMD (const Value *Op)
Macro Definition Documentation
BEGIN_REGISTER_VP_INTRINSIC [1/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, MASKPOS, VLENPOS)
Value:
  case Intrinsic::VPID:                                                        \
    return MASKPOS;
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [2/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, MASKPOS, VLENPOS)
Value:
  case Intrinsic::VPID:                                                        \
    return VLENPOS;
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [3/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, MASKPOS, VLENPOS)
Value:
  case Intrinsic::VPID:                                                        \
    return true;
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [4/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
case Intrinsic::VPID:
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [5/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
case Intrinsic::VPID:
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [6/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
case Intrinsic::VPID:
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [7/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
case Intrinsic::VPID:
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [8/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
case Intrinsic::VPID:
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [9/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
  static_assert(doesVPHaveNoFunctionalEquivalent(Intrinsic::VPID) ||           \
                getFunctionalOpcodeForVP(Intrinsic::VPID) ||                   \
                getFunctionalIntrinsicIDForVP(Intrinsic::VPID));
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [10/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
case Intrinsic::VPID:
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [11/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
break;
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [12/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
break;
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [13/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
case Intrinsic::VPID:
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [14/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
case Intrinsic::VPID:
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [15/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
case Intrinsic::VPID:
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [16/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
case Intrinsic::VPID:
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [17/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
case Intrinsic::VPID:
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [18/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
case Intrinsic::VPID:
Definition at line 569 of file IntrinsicInst.cpp.
BEGIN_REGISTER_VP_INTRINSIC [19/19]
#define BEGIN_REGISTER_VP_INTRINSIC (VPID, ...)
Value:
case Intrinsic::VPID:
Definition at line 569 of file IntrinsicInst.cpp.
END_REGISTER_VP_INTRINSIC [1/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
break;
END_REGISTER_VP_INTRINSIC [2/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
break;
END_REGISTER_VP_INTRINSIC [3/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
break;
END_REGISTER_VP_INTRINSIC [4/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
break;
END_REGISTER_VP_INTRINSIC [5/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
break;
END_REGISTER_VP_INTRINSIC [6/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
break;
END_REGISTER_VP_INTRINSIC [7/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
return Intrinsic::VPID;
END_REGISTER_VP_INTRINSIC [8/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
return Intrinsic::VPID;
END_REGISTER_VP_INTRINSIC [9/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
break;
END_REGISTER_VP_INTRINSIC [10/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
break;
END_REGISTER_VP_INTRINSIC [11/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
break;
END_REGISTER_VP_INTRINSIC [12/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
break;
END_REGISTER_VP_INTRINSIC [13/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
break;
END_REGISTER_VP_INTRINSIC [14/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
break;
END_REGISTER_VP_INTRINSIC [15/15]
#define END_REGISTER_VP_INTRINSIC (VPID)
Value:
break;
VP_PROPERTY_BINARYOP
#define VP_PROPERTY_BINARYOP return true;
VP_PROPERTY_CASTOP
#define VP_PROPERTY_CASTOP return true;
VP_PROPERTY_CMP [1/2]
#define VP_PROPERTY_CMP (CCPOS, ISFP)
Value:
  CCArgIdx = CCPOS;                                                            \
  IsFP = ISFP;                                                                 \
  break;
VP_PROPERTY_CMP [2/2]
#define VP_PROPERTY_CMP (CCPOS, ...)
Value:
return true;
VP_PROPERTY_CONSTRAINEDFP
#define VP_PROPERTY_CONSTRAINEDFP (HASRND, HASEXCEPT, CID)
Value:
return Intrinsic::CID;
VP_PROPERTY_FUNCTIONAL_INTRINSIC [1/2]
#define VP_PROPERTY_FUNCTIONAL_INTRINSIC (INTRIN)
Value:
return Intrinsic::INTRIN;
VP_PROPERTY_FUNCTIONAL_INTRINSIC [2/2]
#define VP_PROPERTY_FUNCTIONAL_INTRINSIC (INTRIN)
Value:
case Intrinsic::INTRIN:
VP_PROPERTY_FUNCTIONAL_OPC [1/2]
#define VP_PROPERTY_FUNCTIONAL_OPC (OPC)
Value:
return Instruction::OPC;
VP_PROPERTY_FUNCTIONAL_OPC [2/2]
#define VP_PROPERTY_FUNCTIONAL_OPC (OPC)
Value:
case Instruction::OPC:
VP_PROPERTY_MEMOP [1/2]
#define VP_PROPERTY_MEMOP (POINTERPOS, DATAPOS)
Value:
return DATAPOS;
VP_PROPERTY_MEMOP [2/2]
#define VP_PROPERTY_MEMOP (POINTERPOS, ...)
Value:
return POINTERPOS;
VP_PROPERTY_NO_FUNCTIONAL
#define VP_PROPERTY_NO_FUNCTIONAL return true;
VP_PROPERTY_REDUCTION [1/3]
#define VP_PROPERTY_REDUCTION (STARTPOS, VECTORPOS)
Value:
return VECTORPOS;
VP_PROPERTY_REDUCTION [2/3]
#define VP_PROPERTY_REDUCTION (STARTPOS, VECTORPOS)
Value:
return STARTPOS;
VP_PROPERTY_REDUCTION [3/3]
#define VP_PROPERTY_REDUCTION (STARTPOS, ...)
Value:
return true;
Function Documentation
doesVPHaveNoFunctionalEquivalent()
static constexpr bool doesVPHaveNoFunctionalEquivalent (Intrinsic::ID ID) static constexpr
Definition at line 555 of file IntrinsicInst.cpp.
getAsMetadata()
static ValueAsMetadata * getAsMetadata (Value * V) static
Definition at line 115 of file IntrinsicInst.cpp.
References llvm::cast(), llvm::dyn_cast(), llvm::ValueAsMetadata::get(), and llvm::isa().
getForIntrinsic()
static constexpr Intrinsic::ID getForIntrinsic (Intrinsic::ID Id) static constexpr
Definition at line 602 of file IntrinsicInst.cpp.
References isVPIntrinsic(), and llvm::Intrinsic::not_intrinsic.
getFPPredicateFromMD()
static FCmpInst::Predicate getFPPredicateFromMD (const Value * Op) static
Definition at line 342 of file IntrinsicInst.cpp.
References llvm::CmpInst::BAD_FCMP_PREDICATE, llvm::StringSwitch< T, R >::Case(), llvm::cast(), llvm::StringSwitch< T, R >::Default(), llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, and llvm::isa().
Referenced by llvm::ConstrainedFPCmpIntrinsic::getPredicate(), and llvm::VPCmpIntrinsic::getPredicate().
getFunctionalIntrinsicIDForVP()
static constexpr std::optional< Intrinsic::ID > getFunctionalIntrinsicIDForVP (Intrinsic::ID ID) static constexpr
Definition at line 538 of file IntrinsicInst.cpp.
getFunctionalOpcodeForVP()
static constexpr std::optional< unsigned > getFunctionalOpcodeForVP (Intrinsic::ID ID) static constexpr
Definition at line 519 of file IntrinsicInst.cpp.
getIntPredicateFromMD()
static ICmpInst::Predicate getIntPredicateFromMD (const Value * Op) static
Definition at line 777 of file IntrinsicInst.cpp.
References llvm::CmpInst::BAD_ICMP_PREDICATE, llvm::StringSwitch< T, R >::Case(), llvm::cast(), llvm::StringSwitch< T, R >::Default(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, and llvm::isa().
Referenced by llvm::VPCmpIntrinsic::getPredicate().
isVPIntrinsic()
bool isVPIntrinsic (Intrinsic::ID ID) constexpr
Definition at line 501 of file IntrinsicInst.cpp.
Referenced by getForIntrinsic().