LLVM: lib/IR/Instruction.cpp File Reference
Instruction.cpp File Reference
#include "llvm/IR/Instruction.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/IR/AttributeMask.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/MemoryModelRelaxationAnnotations.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/ProfDataUtils.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Instruction.def"
Macros
#define HANDLE_TERM_INST(N, OPC, CLASS)
#define HANDLE_TERM_INST(N, OPC, CLASS)
#define HANDLE_TERM_INST(N, OPC, CLASS)
#define HANDLE_INST(num, opc, clas)
Functions
static bool canUnwindPastLandingPad (const LandingPadInst *LP, bool IncludePhaseOneUnwind)
Variables
cl::opt< bool > UseNewDbgInfoFormat
Macro Definition Documentation
HANDLE_INST
#define HANDLE_INST (num, opc, clas)
Value:
  case Instruction::opc:                                                       \
    New = cast<clas>(this)->cloneImpl();                                       \
    break;
HANDLE_TERM_INST [1/3]
#define HANDLE_TERM_INST (N, OPC, CLASS)
Value:
  case Instruction::OPC:                                                       \
    return static_cast<const CLASS *>(this)->getNumSuccessors();
HANDLE_TERM_INST [2/3]
#define HANDLE_TERM_INST (N, OPC, CLASS)
Value:
  case Instruction::OPC:                                                       \
    return static_cast<const CLASS *>(this)->getSuccessor(idx);
HANDLE_TERM_INST [3/3]
#define HANDLE_TERM_INST (N, OPC, CLASS)
Value:
  case Instruction::OPC:                                                       \
    return static_cast<CLASS *>(this)->setSuccessor(idx, B);
Function Documentation
canUnwindPastLandingPad()
static bool canUnwindPastLandingPad (const LandingPadInst * LP, bool IncludePhaseOneUnwind) static
Definition at line 1074 of file Instruction.cpp.
References llvm::LandingPadInst::getClause(), llvm::LandingPadInst::getNumClauses(), I, llvm::isa(), llvm::LandingPadInst::isCatch(), llvm::LandingPadInst::isCleanup(), and llvm::LandingPadInst::isFilter().
Referenced by llvm::Instruction::mayThrow().
Variable Documentation
UseNewDbgInfoFormat
cl::opt<bool> UseNewDbgInfoFormat extern