LLVM: lib/ExecutionEngine/Orc/TargetProcess/JITLoaderVTune.cpp File Reference
JITLoaderVTune.cpp File Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/JITLoaderVTune.h"
#include "llvm/ExecutionEngine/Orc/Shared/VTuneSharedStructs.h"
#include <map>
Functions
static Error unsupportedBatch (const VTuneMethodBatch &MB)
static void unsuppported (const std::vector< std::pair< uint64_t, uint64_t > > &UM)
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerVTuneImpl (const char *Data, uint64_t Size)
llvm::orc::shared::CWrapperFunctionResult llvm_orc_unregisterVTuneImpl (const char *Data, uint64_t Size)
llvm::orc::shared::CWrapperFunctionResult llvm_orc_test_registerVTuneImpl (const char *Data, uint64_t Size)
Function Documentation
llvm_orc_registerVTuneImpl()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerVTuneImpl (const char * Data, uint64_t Size)
Definition at line 201 of file JITLoaderVTune.cpp.
References llvm::Data, Size, and unsupportedBatch().
llvm_orc_test_registerVTuneImpl()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_test_registerVTuneImpl (const char * Data, uint64_t Size)
Definition at line 217 of file JITLoaderVTune.cpp.
References llvm::Data, Size, and unsupportedBatch().
llvm_orc_unregisterVTuneImpl()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_unregisterVTuneImpl (const char * Data, uint64_t Size)
Definition at line 209 of file JITLoaderVTune.cpp.
References llvm::Data, Size, and unsuppported().
unsupportedBatch()
static Error unsupportedBatch (const VTuneMethodBatch & MB) static
Definition at line 191 of file JITLoaderVTune.cpp.
References llvm::inconvertibleErrorCode(), and llvm::make_error().
Referenced by llvm_orc_registerVTuneImpl(), and llvm_orc_test_registerVTuneImpl().
unsuppported()
static void unsuppported (const std::vector< std::pair< uint64_t, uint64_t > > & UM) static
Definition at line 196 of file JITLoaderVTune.cpp.
Referenced by llvm_orc_unregisterVTuneImpl().