LLVM: lib/ExecutionEngine/Orc/TargetProcess/JITLoaderPerf.cpp File Reference
JITLoaderPerf.cpp File Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/JITLoaderPerf.h"
#include "llvm/ExecutionEngine/Orc/Shared/PerfSharedStructs.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Process.h"
#include "llvm/Support/Threading.h"
#include <mutex>
#include <optional>
Functions
static Error badOS ()
static Error badOSBatch (PerfJITRecordBatch &Batch)
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfImpl (const char *Data, uint64_t Size)
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfStart (const char *Data, uint64_t Size)
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfEnd (const char *Data, uint64_t Size)
Function Documentation
badOS()
static Error badOS () static
Definition at line 428 of file JITLoaderPerf.cpp.
References llvm::inconvertibleErrorCode(), and llvm::make_error().
Referenced by badOSBatch(), llvm_orc_registerJITLoaderPerfEnd(), and llvm_orc_registerJITLoaderPerfStart().
badOSBatch()
static Error badOSBatch (PerfJITRecordBatch & Batch) static
Definition at line 435 of file JITLoaderPerf.cpp.
References badOS().
Referenced by llvm_orc_registerJITLoaderPerfImpl().
llvm_orc_registerJITLoaderPerfEnd()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfEnd (const char * Data, uint64_t Size)
Definition at line 452 of file JITLoaderPerf.cpp.
References badOS(), llvm::Data, and Size.
llvm_orc_registerJITLoaderPerfImpl()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfImpl (const char * Data, uint64_t Size)
Definition at line 438 of file JITLoaderPerf.cpp.
References badOSBatch(), llvm::Data, and Size.
llvm_orc_registerJITLoaderPerfStart()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfStart (const char * Data, uint64_t Size)
Definition at line 446 of file JITLoaderPerf.cpp.
References badOS(), llvm::Data, and Size.