LLVM: include/llvm/ExecutionEngine/Orc/TargetProcess/JITLoaderPerf.h File Reference
JITLoaderPerf.h File Reference
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
#include <cstdint>
Functions
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfImpl (const char *Data, uint64_t Size)
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfStart (const char *Data, uint64_t Size)
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfEnd (const char *Data, uint64_t Size)
Function Documentation
llvm_orc_registerJITLoaderPerfEnd()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfEnd (const char * Data, uint64_t Size)
Definition at line 452 of file JITLoaderPerf.cpp.
References badOS(), llvm::Data, and Size.
llvm_orc_registerJITLoaderPerfImpl()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfImpl (const char * Data, uint64_t Size)
Definition at line 438 of file JITLoaderPerf.cpp.
References badOSBatch(), llvm::Data, and Size.
llvm_orc_registerJITLoaderPerfStart()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderPerfStart (const char * Data, uint64_t Size)
Definition at line 446 of file JITLoaderPerf.cpp.
References badOS(), llvm::Data, and Size.