LLVM: include/llvm/ExecutionEngine/Orc/TargetProcess/JITLoaderGDB.h File Reference
JITLoaderGDB.h File Reference
#include "llvm/ExecutionEngine/Orc/Shared/WrapperFunctionUtils.h"
#include <cstdint>
Classes
struct jit_code_entry
struct jit_descriptor
Enumerations
enum jit_actions_t { JIT_NOACTION = 0 , JIT_REGISTER_FN , JIT_UNREGISTER_FN }
Functions
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBWrapper (const char *Data, uint64_t Size)
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBAllocAction (const char *Data, size_t Size)
Enumeration Type Documentation
jit_actions_t
enum jit_actions_t
Enumerator
JIT_NOACTION
JIT_REGISTER_FN
JIT_UNREGISTER_FN
Definition at line 22 of file JITLoaderGDB.h.
Function Documentation
llvm_orc_registerJITLoaderGDBAllocAction()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBAllocAction (const char * Data, size_t Size)
Definition at line 80 of file JITLoaderGDB.cpp.
References __jit_debug_register_code(), appendJITDebugDescriptor(), llvm::Data, llvm::release, Size, and llvm::Error::success().
llvm_orc_registerJITLoaderGDBWrapper()
llvm::orc::shared::CWrapperFunctionResult llvm_orc_registerJITLoaderGDBWrapper (const char * Data, uint64_t Size)
Definition at line 96 of file JITLoaderGDB.cpp.
References __jit_debug_register_code(), appendJITDebugDescriptor(), llvm::Data, llvm::release, Size, and llvm::Error::success().