LLVM: lib/CodeGen/GlobalISel/LegalizerHelper.cpp File Reference
LegalizerHelper.cpp File Reference
#include "llvm/CodeGen/GlobalISel/LegalizerHelper.h"
#include "llvm/CodeGen/GlobalISel/CallLowering.h"
#include "llvm/CodeGen/GlobalISel/GISelChangeObserver.h"
#include "llvm/CodeGen/GlobalISel/GISelKnownBits.h"
#include "llvm/CodeGen/GlobalISel/GenericMachineInstrs.h"
#include "llvm/CodeGen/GlobalISel/LegalizerInfo.h"
#include "llvm/CodeGen/GlobalISel/LostDebugLocObserver.h"
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/GlobalISel/Utils.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RuntimeLibcallUtil.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/Instructions.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include <numeric>
#include <optional>
Macros
#define DEBUG_TYPE "legalizer"
#define RTLIBCASE_INT(LibcallPrefix)
#define RTLIBCASE(LibcallPrefix)
#define LCALLS(A, B)
#define LCALL5(A)
Functions
static std::pair< int, int > getNarrowTypeBreakDown (LLT OrigTy, LLT NarrowTy, LLT &LeftoverTy)
Try to break down OrigTy into NarrowTy sized pieces.
static Type * getFloatTypeForLLT (LLVMContext &Ctx, LLT Ty)
static void getUnmergeResults (SmallVectorImpl< Register > &Regs, const MachineInstr &MI)
Append the result registers of G_UNMERGE_VALUES MI to Regs.
static RTLIB::Libcall getRTLibDesc (unsigned Opcode, unsigned Size)
static bool isLibCallInTailPosition (const CallLowering::ArgInfo &Result, MachineInstr &MI, const TargetInstrInfo &TII, MachineRegisterInfo &MRI)
True if an instruction is in tail position in its caller.
static LegalizerHelper::LegalizeResult simpleLibcall (MachineInstr &MI, MachineIRBuilder &MIRBuilder, unsigned Size, Type *OpType, LostDebugLocObserver &LocObserver)
static RTLIB::Libcall getOutlineAtomicLibcall (MachineInstr &MI)
static LegalizerHelper::LegalizeResult createAtomicLibcall (MachineIRBuilder &MIRBuilder, MachineInstr &MI)
static RTLIB::Libcall getConvRTLibDesc (unsigned Opcode, Type *ToType, Type *FromType)
static LegalizerHelper::LegalizeResult conversionLibcall (MachineInstr &MI, MachineIRBuilder &MIRBuilder, Type *ToType, Type *FromType, LostDebugLocObserver &LocObserver)
static RTLIB::Libcall getStateLibraryFunctionFor (MachineInstr &MI, const TargetLowering &TLI)
static void getUnmergePieces (SmallVectorImpl< Register > &Pieces, MachineIRBuilder &B, Register Src, LLT Ty)
static void emitLoadFromConstantPool (Register DstReg, const Constant *ConstVal, MachineIRBuilder &MIRBuilder)
static Register getBitcastWiderVectorElementOffset (MachineIRBuilder &B, Register Idx, unsigned NewEltSize, unsigned OldEltSize)
Figure out the bit offset into a register when coercing a vector index for the wide element type.
static Register buildBitFieldInsert (MachineIRBuilder &B, Register TargetReg, Register InsertReg, Register OffsetBits)
Emit code to insert InsertReg into TargetRet at OffsetBits in TargetReg, while preserving other bits in TargetReg.
static Register clampVectorIndex (MachineIRBuilder &B, Register IdxReg, LLT VecTy)
static bool hasSameNumEltsOnAllVectorOperands (GenericMachineInstr &MI, MachineRegisterInfo &MRI, std::initializer_list< unsigned > NonVecOpIndices)
Check that all vector operands have same number of elements.
static void makeDstOps (SmallVectorImpl< DstOp > &DstOps, LLT Ty, unsigned NumElts)
Fill DstOps with DstOps that have same number of elements combined as the Ty.
static void broadcastSrcOp (SmallVectorImpl< SrcOp > &Ops, unsigned N, MachineOperand &Op)
Operand Op is used on N sub-instructions.
static bool isNonZeroModBitWidthOrUndef (const MachineRegisterInfo &MRI, Register Reg, unsigned BW)
static CmpInst::Predicate minMaxToCompare (unsigned Opc)
static MachineInstrBuilder SwapN (unsigned N, DstOp Dst, MachineIRBuilder &B, MachineInstrBuilder Src, const APInt &Mask)
static bool shouldLowerMemFuncForSize (const MachineFunction &MF)
static bool findGISelOptimalMemOpLowering (std::vector< LLT > &MemOps, unsigned Limit, const MemOp &Op, unsigned DstAS, unsigned SrcAS, const AttributeList &FuncAttributes, const TargetLowering &TLI)
static Register getMemsetValue (Register Val, LLT Ty, MachineIRBuilder &MIB)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "legalizer"
Definition at line 42 of file LegalizerHelper.cpp.
LCALL5
#define LCALL5 (A)
Value:
  LCALLS(A, 1), LCALLS(A, 2), LCALLS(A, 4), LCALLS(A, 8), LCALLS(A, 16)
Referenced by getOutlineAtomicLibcall().
LCALLS
#define LCALLS (A, B)
Value:
  { A##B##_RELAX, A##B##_ACQ, A##B##_REL, A##B##_ACQ_REL }
RTLIBCASE
#define RTLIBCASE (LibcallPrefix)
Value:
  do {                                                                         \
    switch (Size) {                                                            \
    case 32:                                                                   \
      return RTLIB::LibcallPrefix##32;                                         \
    case 64:                                                                   \
      return RTLIB::LibcallPrefix##64;                                         \
    case 80:                                                                   \
      return RTLIB::LibcallPrefix##80;                                         \
    case 128:                                                                  \
      return RTLIB::LibcallPrefix##128;                                        \
    default:                                                                   \
      llvm_unreachable("unexpected size");                                     \
    }                                                                          \
  } while (0)
Referenced by getRTLibDesc().
RTLIBCASE_INT
#define RTLIBCASE_INT (LibcallPrefix)
Value:
  do {                                                                         \
    switch (Size) {                                                            \
    case 32:                                                                   \
      return RTLIB::LibcallPrefix##32;                                         \
    case 64:                                                                   \
      return RTLIB::LibcallPrefix##64;                                         \
    case 128:                                                                  \
      return RTLIB::LibcallPrefix##128;                                        \
    default:                                                                   \
      llvm_unreachable("unexpected size");                                     \
    }                                                                          \
  } while (0)
Referenced by getRTLibDesc().
Function Documentation
broadcastSrcOp()
static void broadcastSrcOp (SmallVectorImpl< SrcOp > & Ops, unsigned N, MachineOperand & Op) static
Operand Op is used on N sub-instructions.
Fill Ops with N SrcOps made from Op depending on operand type.
Definition at line 4252 of file LegalizerHelper.cpp.
References llvm_unreachable, N, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::LegalizerHelper::fewerElementsVectorMultiEltType().
buildBitFieldInsert()
static Register buildBitFieldInsert (MachineIRBuilder & B, Register TargetReg, Register InsertReg, Register OffsetBits) static
Emit code to insert InsertReg into TargetRet at OffsetBits in TargetReg, while preserving other bits in TargetReg.
(InsertReg << Offset) | (TargetReg & ~(-1 >> InsertReg.size()) << Offset)
Definition at line 3332 of file LegalizerHelper.cpp.
References B, llvm::APInt::getLowBitsSet(), and llvm::LLT::getSizeInBits().
Referenced by llvm::LegalizerHelper::bitcastInsertVectorElt().
clampVectorIndex()
static Register clampVectorIndex (MachineIRBuilder & B, Register IdxReg, LLT VecTy) static
Definition at line 4141 of file LegalizerHelper.cpp.
References B, llvm::APInt::getLowBitsSet(), llvm::LLT::getNumElements(), llvm::LLT::getSizeInBits(), llvm::isPowerOf2_32(), llvm::Log2_32(), llvm::MIPatternMatch::m_ICst(), and llvm::MIPatternMatch::mi_match().
Referenced by llvm::LegalizerHelper::getVectorElementPointer().
conversionLibcall()
static LegalizerHelper::LegalizeResult conversionLibcall (MachineInstr & MI, MachineIRBuilder & MIRBuilder, Type * ToType, Type * FromType, LostDebugLocObserver & LocObserver) static
Definition at line 877 of file LegalizerHelper.cpp.
References llvm::createLibcall(), getConvRTLibDesc(), and MI.
Referenced by llvm::LegalizerHelper::libcall().
createAtomicLibcall()
static LegalizerHelper::LegalizeResult createAtomicLibcall (MachineIRBuilder & MIRBuilder, MachineInstr & MI) static
Definition at line 777 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildSub(), llvm::MachineIRBuilder::buildXor(), llvm::CallLowering::CallLoweringInfo::CallConv, llvm::MachineOperand::CreateES(), llvm::dbgs(), llvm::IntegerType::get(), llvm::PointerType::get(), llvm::StructType::get(), llvm::TargetSubtargetInfo::getCallLowering(), llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineIRBuilder::getMF(), llvm::MCInstrInfo::getName(), getOutlineAtomicLibcall(), llvm::MachineInstrBuilder::getReg(), llvm::LLT::getSizeInBits(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::MachineIRBuilder::getTII(), Info, llvm::LegalizerHelper::Legalized, LLVM_DEBUG, llvm_unreachable, MI, Name, llvm::SmallVectorTemplateBase< T, bool >::push_back(), Success, and llvm::LegalizerHelper::UnableToLegalize.
Referenced by llvm::LegalizerHelper::libcall().
emitLoadFromConstantPool()
static void emitLoadFromConstantPool (Register DstReg, const Constant * ConstVal, MachineIRBuilder & MIRBuilder) static
Definition at line 3089 of file LegalizerHelper.cpp.
References Addr, llvm::MachineIRBuilder::buildConstantPool(), llvm::MachineIRBuilder::buildLoadInstr(), DL, llvm::MachineFunction::getConstantPool(), llvm::MachinePointerInfo::getConstantPool(), llvm::MachineConstantPool::getConstantPoolIndex(), llvm::MachineIRBuilder::getDataLayout(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineIRBuilder::getMF(), llvm::MachineIRBuilder::getMRI(), llvm::Value::getType(), llvm::MachineMemOperand::MOLoad, MRI, and llvm::LLT::pointer().
Referenced by llvm::LegalizerHelper::lowerConstant(), and llvm::LegalizerHelper::lowerFConstant().
findGISelOptimalMemOpLowering()
static bool findGISelOptimalMemOpLowering (std::vector< LLT > & MemOps, unsigned Limit, const MemOp & Op, unsigned DstAS, unsigned SrcAS, const AttributeList & FuncAttributes, const TargetLowering & TLI) static
Definition at line 8664 of file LegalizerHelper.cpp.
References llvm::TargetLoweringBase::allowsMisalignedMemoryAccesses(), assert(), llvm::bit_floor(), llvm::CallingConv::Fast, llvm::getMVTForLLT(), llvm::TargetLoweringBase::getOptimalMemOpLLT(), llvm::LLT::getSizeInBits(), llvm::LLT::getSizeInBytes(), llvm::LLT::isVector(), llvm::MachineMemOperand::MONone, llvm::LLT::scalar(), and Size.
getBitcastWiderVectorElementOffset()
static Register getBitcastWiderVectorElementOffset (MachineIRBuilder & B, Register Idx, unsigned NewEltSize, unsigned OldEltSize) static
Figure out the bit offset into a register when coercing a vector index for the wide element type.
This is only for the case when promoting vector to one with larger elements. offset_idx = G_AND idx, ~(-1 << Log2(DstEltSize / SrcEltSize)) offset_bits = G_SHL offset_idx, Log2(SrcEltSize)
Definition at line 3204 of file LegalizerHelper.cpp.
References B, llvm::APInt::getAllOnes(), llvm::LLT::getSizeInBits(), and llvm::Log2_32().
Referenced by llvm::LegalizerHelper::bitcastExtractVectorElt(), and llvm::LegalizerHelper::bitcastInsertVectorElt().
getConvRTLibDesc()
static RTLIB::Libcall getConvRTLibDesc (unsigned Opcode, Type * ToType, Type * FromType) static
Definition at line 854 of file LegalizerHelper.cpp.
References llvm::RTLIB::getFPEXT(), llvm::RTLIB::getFPROUND(), llvm::RTLIB::getFPTOSINT(), llvm::RTLIB::getFPTOUINT(), llvm::RTLIB::getSINTTOFP(), llvm::RTLIB::getUINTTOFP(), llvm::MVT::getVT(), and llvm_unreachable.
Referenced by conversionLibcall().
getFloatTypeForLLT()
static Type * getFloatTypeForLLT (LLVMContext & Ctx, LLT Ty) static
Definition at line 83 of file LegalizerHelper.cpp.
Referenced by llvm::LegalizerHelper::libcall().
getMemsetValue()
static Register getMemsetValue (Register Val, LLT Ty, MachineIRBuilder & MIB) static
Definition at line 8730 of file LegalizerHelper.cpp.
References llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildMul(), llvm::MachineIRBuilder::buildSplatBuildVector(), llvm::MachineIRBuilder::buildZExtOrTrunc(), llvm::getIConstantVRegValWithLookThrough(), llvm::MachineIRBuilder::getMRI(), llvm::MachineInstrBuilder::getReg(), llvm::LLT::getScalarType(), llvm::APInt::getSplat(), and MRI.
Referenced by getMemsetStores().
getNarrowTypeBreakDown()
static std::pair< int, int > getNarrowTypeBreakDown (LLT OrigTy, LLT NarrowTy, LLT & LeftoverTy) static
Try to break down OrigTy into NarrowTy sized pieces.
Returns the number of NarrowTy elements needed to reconstruct OrigTy, with any leftover piece as type LeftoverTy
Returns -1 in the first element of the pair if the breakdown is not satisfiable.
Definition at line 56 of file LegalizerHelper.cpp.
References assert(), llvm::LLT::getElementType(), llvm::ElementCount::getFixed(), llvm::LLT::getScalarSizeInBits(), llvm::LLT::getSizeInBits(), llvm::LLT::isValid(), llvm::LLT::isVector(), llvm::LLT::scalar(), llvm::LLT::scalarOrVector(), and Size.
Referenced by makeDstOps(), and llvm::LegalizerHelper::reduceLoadStoreWidth().
getOutlineAtomicLibcall()
static RTLIB::Libcall getOutlineAtomicLibcall (MachineInstr & MI) static
Definition at line 728 of file LegalizerHelper.cpp.
References llvm::cast(), llvm::LLT::getSizeInBytes(), llvm::LLT::isVector(), LCALL5, and MI.
Referenced by createAtomicLibcall().
getRTLibDesc()
static RTLIB::Libcall getRTLibDesc (unsigned Opcode, unsigned Size) static
Definition at line 382 of file LegalizerHelper.cpp.
References llvm_unreachable, RTLIBCASE, and RTLIBCASE_INT.
Referenced by llvm::LegalizerHelper::libcall(), and simpleLibcall().
getStateLibraryFunctionFor()
static RTLIB::Libcall getStateLibraryFunctionFor (MachineInstr & MI, const TargetLowering & TLI) static
Definition at line 886 of file LegalizerHelper.cpp.
References llvm_unreachable, and MI.
getUnmergePieces()
static void getUnmergePieces (SmallVectorImpl< Register > & Pieces, MachineIRBuilder & B, Register Src, LLT Ty) static
Definition at line 3082 of file LegalizerHelper.cpp.
References B, I, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::LegalizerHelper::lowerBitcast().
getUnmergeResults()
static void getUnmergeResults (SmallVectorImpl< Register > & Regs, const MachineInstr & MI) static
Append the result registers of G_UNMERGE_VALUES MI to Regs.
Definition at line 225 of file LegalizerHelper.cpp.
References assert(), I, MI, llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorBase< Size_T >::size().
hasSameNumEltsOnAllVectorOperands()
static bool hasSameNumEltsOnAllVectorOperands (GenericMachineInstr & MI, MachineRegisterInfo & MRI, std::initializer_list< unsigned > NonVecOpIndices) static
Check that all vector operands have same number of elements.
Other operands should be listed in NonVecOp.
Definition at line 4191 of file LegalizerHelper.cpp.
References llvm::LLT::getNumElements(), llvm::is_contained(), llvm::LLT::isVector(), MI, and MRI.
Referenced by llvm::LegalizerHelper::fewerElementsVectorMultiEltType().
isLibCallInTailPosition()
static bool isLibCallInTailPosition (const CallLowering::ArgInfo & Result, MachineInstr & MI, const TargetInstrInfo & TII, MachineRegisterInfo & MRI) static
True if an instruction is in tail position in its caller.
Intended for legalizing libcalls as tail calls when possible.
Definition at line 500 of file LegalizerHelper.cpp.
References F, llvm::AttributeList::getAttributes(), llvm::MachineFunction::getFunction(), llvm::MachineBasicBlock::getParent(), llvm::AttributeList::getRetAttrs(), llvm::AttrBuilder::hasAttributes(), llvm::AttributeList::hasRetAttr(), llvm::MachineBasicBlock::instr_end(), llvm::Register::isPhysical(), llvm::HexagonInstrInfo::isTailCall(), llvm::Register::isVirtual(), MBB, MI, llvm::Next, llvm::next_nodbg(), llvm::AttrBuilder::removeAttribute(), and TII.
Referenced by llvm::createLibcall(), and llvm::createMemLibcall().
isNonZeroModBitWidthOrUndef()
static bool isNonZeroModBitWidthOrUndef (const MachineRegisterInfo & MRI, Register Reg, unsigned BW) static
Definition at line 6571 of file LegalizerHelper.cpp.
References llvm::CallingConv::C, llvm::dyn_cast_or_null(), llvm::ConstantInt::getValue(), llvm::matchUnaryPredicate(), MRI, and llvm::APInt::urem().
Referenced by llvm::TargetLowering::expandFunnelShift(), expandVPFunnelShift(), llvm::LegalizerHelper::lowerFunnelShiftAsShifts(), and llvm::LegalizerHelper::lowerFunnelShiftWithInverse().
makeDstOps()
static void makeDstOps (SmallVectorImpl< DstOp > & DstOps, LLT Ty, unsigned NumElts) static
Fill DstOps with DstOps that have same number of elements combined as the Ty.
These DstOps have either scalar type when NumElts = 1 or are vectors with NumElts elements. When Ty.getNumElements() is not multiple of NumElts last DstOp (leftover) has fewer then NumElts elements.
Definition at line 4229 of file LegalizerHelper.cpp.
References assert(), llvm::LLT::fixed_vector(), llvm::LLT::getElementType(), getNarrowTypeBreakDown(), llvm::LLT::isValid(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), and llvm::LegalizerHelper::fewerElementsVectorPhi().
minMaxToCompare()
static CmpInst::Predicate minMaxToCompare (unsigned Opc) static
Definition at line 7247 of file LegalizerHelper.cpp.
References llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, and llvm_unreachable.
Referenced by llvm::LegalizerHelper::lowerMinMax().
shouldLowerMemFuncForSize()
static bool shouldLowerMemFuncForSize (const MachineFunction & MF) static
Definition at line 8654 of file LegalizerHelper.cpp.
References llvm::MachineFunction::getFunction(), llvm::MachineFunction::getTarget(), llvm::TargetMachine::getTargetTriple(), llvm::Function::hasMinSize(), llvm::Function::hasOptSize(), and llvm::Triple::isOSDarwin().
Referenced by getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), and llvm::LegalizerHelper::lowerMemCpyFamily().
simpleLibcall()
static LegalizerHelper::LegalizeResult simpleLibcall (MachineInstr & MI, MachineIRBuilder & MIRBuilder, unsigned Size, Type * OpType, LostDebugLocObserver & LocObserver) static
Definition at line 626 of file LegalizerHelper.cpp.
References llvm::createLibcall(), llvm::drop_begin(), getRTLibDesc(), MI, and Size.
Referenced by llvm::LegalizerHelper::libcall().
SwapN()
static MachineInstrBuilder SwapN (unsigned N, DstOp Dst, MachineIRBuilder & B, MachineInstrBuilder Src, const APInt & Mask) static
Definition at line 8182 of file LegalizerHelper.cpp.
References B, and N.
Referenced by llvm::LegalizerHelper::lowerBitreverse().