LLVM: lib/Analysis/Lint.cpp File Reference
Lint.cpp File Reference
#include "llvm/Analysis/Lint.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/Analysis/ScopedNoAliasAA.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TypeBasedAliasAnalysis.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InstVisitor.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include <iterator>
#include <string>
Namespaces
namespace MemRef
Macros
#define Check(C, ...)
Functions
static bool isZero (Value *V, const DataLayout &DL, DominatorTree *DT, AssumptionCache *AC)
Variables
static const char LintAbortOnErrorArgName [] = "lint-abort-on-error"
static cl::opt< bool > LintAbortOnError (LintAbortOnErrorArgName, cl::init(false), cl::desc("In the Lint pass, abort on errors."))
Macro Definition Documentation
Check
#define Check (C, ...)
Value:
  do {                                                                         \
    if (!(C)) {                                                                \
      CheckFailed(__VA_ARGS__);                                                \
      return;                                                                  \
    }                                                                          \
  } while (false)
Definition at line 173 of file Lint.cpp.
Function Documentation
isZero()
static bool isZero (Value * V, const DataLayout & DL, DominatorTree * DT, AssumptionCache * AC) static
Definition at line 512 of file Lint.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::computeKnownBits(), DL, llvm::dyn_cast(), llvm::Constant::getAggregateElement(), getNumElements(), I, llvm::isa(), llvm::KnownBits::isZero(), and N.
Referenced by llvm::CanonicalLoopInfo::assertOK(), combineAnd(), combineAndnp(), createShuffleMaskFromVSELECT(), llvm::IRBuilderBase::CreateVScale(), llvm::ConstantRange::ctlz(), foldGEPChainAsStructAccess(), FoldSTEP_VECTOR(), llvm::ConstantStruct::get(), llvm::APInt::getBoolValue(), llvm::detail::IEEEFloat::getExactLog2Abs(), llvm::SelectionDAG::getNode(), impliesEquivalanceIfFalse(), impliesEquivalanceIfTrue(), llvm::APInt::isMinValue(), llvm::SelectionDAG::isSplatValue(), llvm::APInt::isStrictlyPositive(), llvm::APSInt::isStrictlyPositive(), llvm::APInt::operator!(), llvm::ScaledNumber< DigitsT >::operator*=(), llvm::ScaledNumber< DigitsT >::operator/=(), llvm::JumpThreadingPass::processThreadableEdges(), rewriteGEPAsOffset(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::LoopVectorizeHints::vectorizeAnalysisPassName(), llvm::InstCombinerImpl::visitOr(), and llvm::InstCombinerImpl::visitSub().
Variable Documentation
LintAbortOnError
cl::opt< bool > LintAbortOnError(LintAbortOnErrorArgName, cl::init(false), cl::desc("In the Lint pass, abort on errors.")) (LintAbortOnErrorArgName , cl::init(false) , cl::desc("In the Lint pass, abort on errors.")) static
Referenced by llvm::LintPass::run().
LintAbortOnErrorArgName
const char LintAbortOnErrorArgName[] = "lint-abort-on-error" static
Definition at line 80 of file Lint.cpp.
Referenced by llvm::LintPass::run().