LLVM: lib/Analysis/Loads.cpp File Reference
Loads.cpp File Reference
#include "llvm/Analysis/Loads.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumeBundleQueries.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
Functions
static bool isAligned (const Value *Base, const APInt &Offset, Align Alignment, const DataLayout &DL)
static bool isDereferenceableAndAlignedPointer (const Value *V, Align Alignment, const APInt &Size, const DataLayout &DL, const Instruction *CtxI, AssumptionCache *AC, const DominatorTree *DT, const TargetLibraryInfo *TLI, SmallPtrSetImpl< const Value * > &Visited, unsigned MaxDepth)
Test if V is always a pointer to allocated and suitably aligned memory for a simple load or store.
static bool AreEquivalentAddressValues (const Value *A, const Value *B)
Test if A and B will obviously have the same value.
static bool areNonOverlapSameBaseLoadAndStore (const Value *LoadPtr, Type *LoadTy, const Value *StorePtr, Type *StoreTy, const DataLayout &DL)
static Value * getAvailableLoadStore (Instruction *Inst, const Value *Ptr, Type *AccessTy, bool AtLeastAtomic, const DataLayout &DL, bool *IsLoadCSE)
static bool isPointerUseReplacable (const Use &U)
static bool isPointerAlwaysReplaceable (const Value *From, const Value *To, const DataLayout &DL)
Function Documentation
AreEquivalentAddressValues()
static bool AreEquivalentAddressValues (const Value * A, const Value * B) static
Test if A and B will obviously have the same value.
This includes recognizing that t0 and t1 will have the same value in code like this:
%t0 = getelementptr \@a, 0, 3
store i32 0, i32* %t0
%t1 = getelementptr \@a, 0, 3
%t2 = load i32* %t1
Definition at line 242 of file Loads.cpp.
References A, B, llvm::cast(), llvm::dyn_cast(), and llvm::isa().
Referenced by getAvailableLoadStore(), and llvm::isSafeToLoadUnconditionally().
areNonOverlapSameBaseLoadAndStore()
static bool areNonOverlapSameBaseLoadAndStore (const Value * LoadPtr, Type * LoadTy, const Value * StorePtr, Type * StoreTy, const DataLayout & DL) static
Definition at line 479 of file Loads.cpp.
References DL, llvm::Value::getType(), llvm::ConstantRange::intersectWith(), llvm::ConstantRange::isEmptySet(), llvm::LocationSize::precise(), and llvm::Value::stripAndAccumulateConstantOffsets().
Referenced by llvm::findAvailablePtrLoadStore().
getAvailableLoadStore()
static Value * getAvailableLoadStore (Instruction * Inst, const Value * Ptr, Type * AccessTy, bool AtLeastAtomic, const DataLayout & DL, bool * IsLoadCSE) static
Definition at line 501 of file Loads.cpp.
References AreEquivalentAddressValues(), llvm::CallingConv::C, llvm::ConstantFoldLoadFromConst(), DL, llvm::dyn_cast(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), llvm::APInt::getSplat(), llvm::Value::getType(), llvm::CastInst::isBitOrNoopPointerCastable(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), Ptr, llvm::Splat, and llvm::Value::stripPointerCasts().
Referenced by llvm::FindAvailableLoadedValue(), and llvm::findAvailablePtrLoadStore().
isAligned()
static bool isAligned (const Value * Base, const APInt & Offset, Align Alignment, const DataLayout & DL) static
Definition at line 29 of file Loads.cpp.
References llvm::sampleprof::Base, DL, and llvm::Offset.
isDereferenceableAndAlignedPointer()
static bool isDereferenceableAndAlignedPointer (const Value * V, Align Alignment, const APInt & Size, const DataLayout & DL, const Instruction * CtxI, AssumptionCache * AC, const DominatorTree * DT, const TargetLibraryInfo * TLI, SmallPtrSetImpl< const Value * > & Visited, unsigned MaxDepth) static
Test if V is always a pointer to allocated and suitably aligned memory for a simple load or store.
TODO refactor this function to be able to search independently for Dereferencability and Alignment requirements.
Look through assumes to see if both dereferencability and alignment can be provent by an assume
Definition at line 37 of file Loads.cpp.
References llvm::RetainedKnowledge::ArgValue, assert(), llvm::sampleprof::Base, Call, DL, llvm::dyn_cast(), GEP, llvm::getArgumentAliasingToReturnedPointer(), llvm::APInt::getBoolValue(), llvm::getKnowledgeForValue(), llvm::getObjectSize(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isAligned(), llvm::isDereferenceableAndAlignedPointer(), llvm::isKnownNonZero(), llvm::isValidAssumeForContext(), MaxDepth, llvm::ObjectSizeOpts::NullIsUnknownSize, llvm::Offset, llvm::ObjectSizeOpts::RoundToAlign, Size, llvm::APInt::uge(), and llvm::Align::value().
isPointerAlwaysReplaceable()
static bool isPointerAlwaysReplaceable (const Value * From, const Value * To, const DataLayout & DL) static
Definition at line 744 of file Loads.cpp.
References DL, From, llvm::Value::getContext(), llvm::getUnderlyingObjectAggressive(), llvm::isa(), and llvm::isDereferenceablePointer().
Referenced by llvm::canReplacePointersIfEqual(), and llvm::canReplacePointersInUseIfEqual().
isPointerUseReplacable()
static bool isPointerUseReplacable (const Use & U) static
Definition at line 722 of file Loads.cpp.
References llvm::SmallVectorImpl< T >::insert(), llvm::isa(), llvm::Value::user_begin(), and llvm::Value::user_end().
Referenced by llvm::canReplacePointersInUseIfEqual().