LLVM: lib/Target/LoongArch/LoongArchOptWInstrs.cpp File Reference
LoongArchOptWInstrs.cpp File Reference
#include "LoongArch.h"
#include "LoongArchMachineFunctionInfo.h"
#include "LoongArchSubtarget.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
Macros
#define DEBUG_TYPE "loongarch-opt-w-instrs"
#define LOONGARCH_OPT_W_INSTRS_NAME "LoongArch Optimize W Instructions"
Functions
STATISTIC (NumRemovedSExtW, "Number of removed sign-extensions")
STATISTIC (NumTransformedToWInstrs, "Number of instructions transformed to W-ops")
INITIALIZE_PASS (LoongArchOptWInstrs, DEBUG_TYPE, LOONGARCH_OPT_W_INSTRS_NAME, false, false) FunctionPass *llvm
static bool hasAllNBitUsers (const MachineInstr &OrigMI, const LoongArchSubtarget &ST, const MachineRegisterInfo &MRI, unsigned OrigBits)
static bool hasAllWUsers (const MachineInstr &OrigMI, const LoongArchSubtarget &ST, const MachineRegisterInfo &MRI)
static bool isSignExtendingOpW (const MachineInstr &MI, const MachineRegisterInfo &MRI, unsigned OpNo)
static bool isSignExtendedW (Register SrcReg, const LoongArchSubtarget &ST, const MachineRegisterInfo &MRI, SmallPtrSetImpl< MachineInstr * > &FixableDef)
static unsigned getWOp (unsigned Opcode)
Variables
static cl::opt< bool > DisableSExtWRemoval ("loongarch-disable-sextw-removal", cl::desc("Disable removal of sign-extend insn"), cl::init(false), cl::Hidden)
static cl::opt< bool > DisableCvtToDSuffix ("loongarch-disable-cvt-to-d-suffix", cl::desc("Disable convert to D suffix"), cl::init(false), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loongarch-opt-w-instrs"
Definition at line 42 of file LoongArchOptWInstrs.cpp.
LOONGARCH_OPT_W_INSTRS_NAME
#define LOONGARCH_OPT_W_INSTRS_NAME "LoongArch Optimize W Instructions"
Definition at line 43 of file LoongArchOptWInstrs.cpp.
Function Documentation
getWOp()
static unsigned getWOp (unsigned Opcode) static
Definition at line 648 of file LoongArchOptWInstrs.cpp.
References llvm_unreachable.
hasAllNBitUsers()
static bool hasAllNBitUsers (const MachineInstr & OrigMI, const LoongArchSubtarget & ST, const MachineRegisterInfo & MRI, unsigned OrigBits) static
Definition at line 98 of file LoongArchOptWInstrs.cpp.
References llvm::bit_width(), llvm::SmallVectorBase< Size_T >::empty(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::SmallSet< T, N, C >::insert(), llvm::Register::isVirtual(), llvm::Log2_32(), MI, MRI, P, llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by hasAllWUsers().
hasAllWUsers()
static bool hasAllWUsers (const MachineInstr & OrigMI, const LoongArchSubtarget & ST, const MachineRegisterInfo & MRI) static
Definition at line 315 of file LoongArchOptWInstrs.cpp.
References hasAllNBitUsers(), and MRI.
Referenced by isSignExtendedW().
INITIALIZE_PASS()
INITIALIZE_PASS (LoongArchOptWInstrs , DEBUG_TYPE , LOONGARCH_OPT_W_INSTRS_NAME , false , false)
Definition at line 88 of file LoongArchOptWInstrs.cpp.
isSignExtendedW()
static bool isSignExtendedW (Register SrcReg, const LoongArchSubtarget & ST, const MachineRegisterInfo & MRI, SmallPtrSetImpl< MachineInstr * > & FixableDef) static
Definition at line 477 of file LoongArchOptWInstrs.cpp.
References assert(), B, llvm::BitWidth, D, llvm::dyn_cast(), llvm::dyn_cast_if_present(), E, llvm::SmallVectorBase< Size_T >::empty(), llvm::MachineFunction::front(), llvm::MachineOperand::getGlobal(), llvm::MachineFunction::getInfo(), llvm::MachineInstr::getOperand(), llvm::MachineFunction::getRegInfo(), hasAllWUsers(), I, II, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallSet< T, N, C >::insert(), llvm::MachineBasicBlock::instr_begin(), llvm::MachineInstr::isCall(), llvm::MachineOperand::isGlobal(), llvm::MachineRegisterInfo::isLiveIn(), llvm::LoongArchMachineFunctionInfo::isSExt32Register(), isSignExtendingOpW(), llvm::Register::isVirtual(), MBB, MI, MRI, llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
isSignExtendingOpW()
static bool isSignExtendingOpW (const MachineInstr & MI, const MachineRegisterInfo & MRI, unsigned OpNo) static
Definition at line 323 of file LoongArchOptWInstrs.cpp.
References MI.
Referenced by isSignExtendedW().
STATISTIC() [1/2]
STATISTIC (NumRemovedSExtW , "Number of removed sign-extensions")
STATISTIC() [2/2]
STATISTIC (NumTransformedToWInstrs , "Number of instructions transformed to W-ops")
Variable Documentation
DisableCvtToDSuffix
cl::opt< bool > DisableCvtToDSuffix("loongarch-disable-cvt-to-d-suffix", cl::desc("Disable convert to D suffix"), cl::init(false), cl::Hidden) ("loongarch-disable-cvt-to-d-suffix" , cl::desc("Disable convert to D suffix") , cl::init(false) , cl::Hidden) static
DisableSExtWRemoval
cl::opt< bool > DisableSExtWRemoval("loongarch-disable-sextw-removal", cl::desc("Disable removal of sign-extend insn"), cl::init(false), cl::Hidden) ("loongarch-disable-sextw-removal" , cl::desc("Disable removal of sign-extend insn") , cl::init(false) , cl::Hidden) static