LLVM: lib/Target/LoongArch/LoongArchISelDAGToDAG.cpp File Reference
LoongArchISelDAGToDAG.cpp File Reference
#include "LoongArchISelDAGToDAG.h"
#include "LoongArchISelLowering.h"
#include "MCTargetDesc/LoongArchMCTargetDesc.h"
#include "MCTargetDesc/LoongArchMatInt.h"
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "loongarch-isel"
#define PASS_NAME "LoongArch DAG->DAG Pattern Instruction Selection"
Functions
INITIALIZE_PASS (LoongArchDAGToDAGISelLegacy, DEBUG_TYPE, PASS_NAME, false, false) void LoongArchDAGToDAGISel
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loongarch-isel"
Definition at line 22 of file LoongArchISelDAGToDAG.cpp.
PASS_NAME
#define PASS_NAME "LoongArch DAG->DAG Pattern Instruction Selection"
Definition at line 23 of file LoongArchISelDAGToDAG.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (LoongArchDAGToDAGISelLegacy , DEBUG_TYPE , PASS_NAME , false , false)
Definition at line 31 of file LoongArchISelDAGToDAG.cpp.
References llvm::ISD::BUILD_VECTOR, llvm::cast(), llvm::ISD::Constant, DL, llvm::ISD::FrameIndex, llvm::LoongArchMatInt::generateInstSeq(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::is128BitVector(), llvm::MVT::is128BitVector(), llvm::EVT::is256BitVector(), llvm::MVT::is256BitVector(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::APInt::isSignedIntN(), and SDValue().