LLVM: lib/Target/LoongArch/LoongArchInstrInfo.cpp File Reference
LoongArchInstrInfo.cpp File Reference
#include "LoongArchInstrInfo.h"
#include "LoongArch.h"
#include "LoongArchMachineFunctionInfo.h"
#include "LoongArchRegisterInfo.h"
#include "MCTargetDesc/LoongArchMCTargetDesc.h"
#include "MCTargetDesc/LoongArchMatInt.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/MC/MCInstBuilder.h"
#include "LoongArchGenInstrInfo.inc"
Macros
#define GET_INSTRINFO_CTOR_DTOR
Functions
static void parseCondBranch (MachineInstr &LastInst, MachineBasicBlock *&Target, SmallVectorImpl< MachineOperand > &Cond)
static unsigned getOppositeBranchOpc (unsigned Opc)
Macro Definition Documentation
GET_INSTRINFO_CTOR_DTOR
#define GET_INSTRINFO_CTOR_DTOR
Definition at line 24 of file LoongArchInstrInfo.cpp.
Function Documentation
getOppositeBranchOpc()
static unsigned getOppositeBranchOpc (unsigned Opc) static
Definition at line 486 of file LoongArchInstrInfo.cpp.
References llvm_unreachable.
parseCondBranch()
static void parseCondBranch (MachineInstr & LastInst, MachineBasicBlock *& Target, SmallVectorImpl< MachineOperand > & Cond) static
Definition at line 254 of file LoongArchInstrInfo.cpp.
References assert(), Cond, llvm::MachineOperand::CreateImm(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MCInstrDesc::isConditionalBranch(), and llvm::MachineBasicBlock::push_back().