LLVM: lib/Analysis/LoopNestAnalysis.cpp File Reference
LoopNestAnalysis.cpp File Reference
The implementation for the loop nest analysis.
#include "llvm/Analysis/LoopNestAnalysis.h"
#include "llvm/ADT/BreadthFirstIterator.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/Analysis/ValueTracking.h"
Macros
#define DEBUG_TYPE "loopnest"
Functions
static bool checkLoopsStructure (const Loop &OuterLoop, const Loop &InnerLoop, ScalarEvolution &SE)
Determine whether the loops structure violates basic requirements for perfect nesting:
static CmpInst * getOuterLoopLatchCmp (const Loop &OuterLoop)
static CmpInst * getInnerLoopGuardCmp (const Loop &InnerLoop)
static bool checkSafeInstruction (const Instruction &I, const CmpInst *InnerLoopGuardCmp, const CmpInst *OuterLoopLatchCmp, std::optional< Loop::LoopBounds > OuterLoopLB)
Variables
static const char * VerboseDebug = DEBUG_TYPE "-verbose"
Detailed Description
The implementation for the loop nest analysis.
Definition in file LoopNestAnalysis.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loopnest"
Definition at line 21 of file LoopNestAnalysis.cpp.
Function Documentation
checkLoopsStructure()
static bool checkLoopsStructure (const Loop & OuterLoop, const Loop & InnerLoop, ScalarEvolution & SE) static
Determine whether the loops structure violates basic requirements for perfect nesting:
the inner loop should be the outer loop's only child
the outer loop header should 'flow' into the inner loop preheader or jump around the inner loop to the outer loop latch
if the inner loop latch exits the inner loop, it should 'flow' into the outer loop latch. Returns true if the loop structure satisfies the basic requirements and false otherwise.
Definition at line 315 of file LoopNestAnalysis.cpp.
References llvm::all_of(), llvm::any_of(), llvm::LoopBase< BlockT, LoopT >::getExitBlock(), llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::LoopBase< BlockT, LoopT >::getSubLoops(), and llvm::Loop::isLoopSimplifyForm().
checkSafeInstruction()
static bool checkSafeInstruction (const Instruction & I, const CmpInst * InnerLoopGuardCmp, const CmpInst * OuterLoopLatchCmp, std::optional< Loop::LoopBounds > OuterLoopLB) static
Definition at line 84 of file LoopNestAnalysis.cpp.
References I, llvm::isa(), and llvm::isSafeToSpeculativelyExecute().
Referenced by llvm::LoopNest::getInterveningInstructions().
getInnerLoopGuardCmp()
static CmpInst * getInnerLoopGuardCmp (const Loop & InnerLoop) static
Definition at line 70 of file LoopNestAnalysis.cpp.
References llvm::dbgs(), DEBUG_WITH_TYPE, llvm::dyn_cast(), llvm::BranchInst::getCondition(), llvm::Loop::getLoopGuardBranch(), and VerboseDebug.
Referenced by llvm::LoopNest::getInterveningInstructions().
getOuterLoopLatchCmp()
static CmpInst * getOuterLoopLatchCmp (const Loop & OuterLoop) static
Definition at line 52 of file LoopNestAnalysis.cpp.
References assert(), llvm::dbgs(), DEBUG_WITH_TYPE, llvm::dyn_cast(), llvm::BranchInst::getCondition(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::BasicBlock::getTerminator(), llvm::BranchInst::isConditional(), and VerboseDebug.
Referenced by llvm::LoopNest::getInterveningInstructions().
Variable Documentation
VerboseDebug
const char* VerboseDebug = DEBUG_TYPE "-verbose" static
Definition at line 23 of file LoopNestAnalysis.cpp.
Referenced by getInnerLoopGuardCmp(), llvm::LoopNest::getInterveningInstructions(), getOuterLoopLatchCmp(), llvm::EpilogueVectorizerEpilogueLoop::printDebugTracesAtEnd(), and llvm::EpilogueVectorizerMainLoop::printDebugTracesAtEnd().