LLVM: lib/Transforms/Utils/LowerMemIntrinsics.cpp File Reference
LowerMemIntrinsics.cpp File Reference
#include "llvm/Transforms/Utils/LowerMemIntrinsics.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include <optional>
Macros
#define DEBUG_TYPE "lower-mem-intrinsics"
Functions
static Value * getRuntimeLoopCount (const DataLayout &DL, IRBuilderBase &B, Value *Len, Value *OpSize, unsigned OpSizeVal)
static Value * getRuntimeLoopRemainder (const DataLayout &DL, IRBuilderBase &B, Value *Len, Value *OpSize, unsigned OpSizeVal)
static void createMemMoveLoop (Instruction *InsertBefore, Value *SrcAddr, Value *DstAddr, Value *CopyLen, Align SrcAlign, Align DstAlign, bool SrcIsVolatile, bool DstIsVolatile, const TargetTransformInfo &TTI)
static void createMemSetLoop (Instruction *InsertBefore, Value *DstAddr, Value *CopyLen, Value *SetValue, Align DstAlign, bool IsVolatile)
template<typename T >
static bool canOverlap (MemTransferBase< T > *Memcpy, ScalarEvolution *SE)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lower-mem-intrinsics"
Definition at line 20 of file LowerMemIntrinsics.cpp.
Function Documentation
canOverlap()
template<typename T > static bool canOverlap (MemTransferBase< T > * Memcpy, ScalarEvolution * SE) static
Definition at line 502 of file LowerMemIntrinsics.cpp.
References llvm::MemTransferBase< BaseCL >::getRawSource(), llvm::ScalarEvolution::getSCEV(), llvm::CmpInst::ICMP_NE, and llvm::ScalarEvolution::isKnownPredicateAt().
Referenced by llvm::expandMemCpyAsLoop().
createMemMoveLoop()
static void createMemMoveLoop (Instruction * InsertBefore, Value * SrcAddr, Value * DstAddr, Value * CopyLen, Align SrcAlign, Align DstAlign, bool SrcIsVolatile, bool DstIsVolatile, const TargetTransformInfo & TTI) static
Definition at line 372 of file LowerMemIntrinsics.cpp.
References llvm::PHINode::addIncoming(), llvm::commonAlignment(), llvm::BasicBlock::Create(), llvm::BranchInst::Create(), llvm::IRBuilderBase::CreateAdd(), llvm::IRBuilderBase::CreateAlignedLoad(), llvm::IRBuilderBase::CreateAlignedStore(), llvm::IRBuilderBase::CreateCondBr(), llvm::IRBuilderBase::CreateICmpEQ(), llvm::IRBuilderBase::CreateInBoundsGEP(), llvm::IRBuilderBase::CreatePHI(), llvm::IRBuilderBase::CreateSub(), DL, llvm::Instruction::eraseFromParent(), F, llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::BasicBlock::getParent(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::Value::setName(), and llvm::SplitBlockAndInsertIfThenElse().
Referenced by llvm::expandMemMoveAsLoop().
createMemSetLoop()
static void createMemSetLoop (Instruction * InsertBefore, Value * DstAddr, Value * CopyLen, Value * SetValue, Align DstAlign, bool IsVolatile) static
Definition at line 462 of file LowerMemIntrinsics.cpp.
References llvm::PHINode::addIncoming(), llvm::commonAlignment(), llvm::BasicBlock::Create(), llvm::IRBuilderBase::CreateAdd(), llvm::IRBuilderBase::CreateAlignedStore(), llvm::IRBuilderBase::CreateCondBr(), llvm::IRBuilderBase::CreateICmpULT(), llvm::IRBuilderBase::CreateInBoundsGEP(), llvm::IRBuilderBase::CreatePHI(), DL, llvm::Instruction::eraseFromParent(), F, llvm::BasicBlock::getParent(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), SetValue(), and llvm::BasicBlock::splitBasicBlock().
Referenced by llvm::expandMemSetAsLoop().
getRuntimeLoopCount()
static Value * getRuntimeLoopCount (const DataLayout & DL, IRBuilderBase & B, Value * Len, Value * OpSize, unsigned OpSizeVal) static
Definition at line 160 of file LowerMemIntrinsics.cpp.
References B, llvm::isPowerOf2_32(), and llvm::Log2_32().
getRuntimeLoopRemainder()
static Value * getRuntimeLoopRemainder (const DataLayout & DL, IRBuilderBase & B, Value * Len, Value * OpSize, unsigned OpSizeVal) static
Definition at line 170 of file LowerMemIntrinsics.cpp.
References B, and llvm::isPowerOf2_32().