LLVM: lib/DebugInfo/LogicalView/Core/LVSupport.cpp File Reference
LVSupport.cpp File Reference
#include "llvm/DebugInfo/LogicalView/Core/LVSupport.h"
#include "llvm/Support/FormatAdapters.h"
#include "llvm/Support/FormatVariadic.h"
#include <iomanip>
Macros
#define DEBUG_TYPE "Support"
Typedefs
using LexicalEntry = std::pair<size_t, size_t>
using LexicalIndexes = SmallVector<LexicalEntry, 10>
Functions
static LexicalIndexes getAllLexicalIndexes (StringRef Name)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "Support"
Definition at line 21 of file LVSupport.cpp.
Typedef Documentation
LexicalEntry
using LexicalEntry = std::pair<size_t, size_t>
Definition at line 64 of file LVSupport.cpp.
LexicalIndexes
using LexicalIndexes = SmallVector<LexicalEntry, 10>
Definition at line 65 of file LVSupport.cpp.
Function Documentation
getAllLexicalIndexes()
static LexicalIndexes getAllLexicalIndexes (StringRef Name) static
Definition at line 67 of file LVSupport.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::dbgs(), llvm::formatv(), llvm::Length, LLVM_DEBUG, llvm::logicalview::Name, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::logicalview::getAllLexicalComponents(), and llvm::logicalview::getInnerComponent().