LLVM: lib/MC/MachObjectWriter.cpp File Reference
MachObjectWriter.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Twine.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfoDarwin.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCFragment.h"
#include "llvm/MC/MCMachObjectWriter.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolMachO.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/Alignment.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <string>
#include <utility>
#include <vector>
Macros
#define DEBUG_TYPE "mc"
Functions
static bool isSymbolLinkerVisible (const MCSymbol &Symbol)
static unsigned ComputeLinkerOptionsLoadCommandSize (const std::vector< std::string > &Options, bool is64Bit)
static bool isFixupTargetValid (const MCValue &Target)
static MachO::LoadCommandType getLCFromMCVM (MCVersionMinType Type)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mc"
Definition at line 45 of file MachObjectWriter.cpp.
Function Documentation
ComputeLinkerOptionsLoadCommandSize()
static unsigned ComputeLinkerOptionsLoadCommandSize (const std::vector< std::string > & Options, bool is64Bit) static
Definition at line 465 of file MachObjectWriter.cpp.
References llvm::alignTo(), is64Bit(), Options, and Size.
Referenced by llvm::MachObjectWriter::writeLinkerOptionsLoadCommand(), and llvm::MachObjectWriter::writeObject().
getLCFromMCVM()
static MachO::LoadCommandType getLCFromMCVM (MCVersionMinType Type) static
Definition at line 761 of file MachObjectWriter.cpp.
References llvm_unreachable, llvm::MCVM_IOSVersionMin, llvm::MCVM_OSXVersionMin, llvm::MCVM_TvOSVersionMin, and llvm::MCVM_WatchOSVersionMin.
Referenced by llvm::MachObjectWriter::writeObject().
isFixupTargetValid()
static bool isFixupTargetValid (const MCValue & Target) static
Definition at line 498 of file MachObjectWriter.cpp.
Referenced by llvm::MachObjectWriter::recordRelocation().
isSymbolLinkerVisible()
static bool isSymbolLinkerVisible (const MCSymbol & Symbol) static
Definition at line 146 of file MachObjectWriter.cpp.
Referenced by llvm::MachObjectWriter::computeSymbolTable(), and llvm::MachObjectWriter::getAtom().