LLVM: lib/CodeGen/MachineSSAUpdater.cpp File Reference
MachineSSAUpdater.cpp File Reference
#include "llvm/CodeGen/MachineSSAUpdater.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/SSAUpdaterImpl.h"
#include <utility>
Classes
class llvm::SSAUpdaterTraits< MachineSSAUpdater >
SSAUpdaterTraits<MachineSSAUpdater> - Traits for the SSAUpdaterImpl template, specialized for MachineSSAUpdater.
class llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator
Iterator for PHI operands.
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "machine-ssaupdater"
Typedefs
using AvailableValsTy = DenseMap<MachineBasicBlock *, Register>
Functions
static AvailableValsTy & getAvailableVals (void *AV)
static Register LookForIdenticalPHI (MachineBasicBlock *BB, SmallVectorImpl< std::pair< MachineBasicBlock *, Register > > &PredValues)
static MachineInstrBuilder InsertNewDef (unsigned Opcode, MachineBasicBlock *BB, MachineBasicBlock::iterator I, MachineRegisterInfo::VRegAttrs RegAttrs, MachineRegisterInfo *MRI, const TargetInstrInfo *TII)
InsertNewDef - Insert an empty PHI or IMPLICIT_DEF instruction which define a value of the given register class at the start of the specified basic block.
static MachineBasicBlock * findCorrespondingPred (const MachineInstr *MI, MachineOperand *U)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-ssaupdater"
Definition at line 35 of file MachineSSAUpdater.cpp.
Typedef Documentation
AvailableValsTy
using AvailableValsTy = DenseMap<MachineBasicBlock *, Register>
Definition at line 37 of file MachineSSAUpdater.cpp.
Function Documentation
findCorrespondingPred()
static MachineBasicBlock * findCorrespondingPred (const MachineInstr * MI, MachineOperand * U) static
Definition at line 217 of file MachineSSAUpdater.cpp.
References llvm_unreachable, and MI.
Referenced by llvm::MachineSSAUpdater::RewriteUse().
getAvailableVals()
static AvailableValsTy & getAvailableVals (void * AV) static
Definition at line 39 of file MachineSSAUpdater.cpp.
Referenced by llvm::MachineSSAUpdater::AddAvailableValue(), llvm::SSAUpdater::AddAvailableValue(), llvm::SSAUpdater::FindValueForBlock(), llvm::MachineSSAUpdater::HasValueForBlock(), llvm::SSAUpdater::HasValueForBlock(), llvm::MachineSSAUpdater::Initialize(), and llvm::SSAUpdater::Initialize().
InsertNewDef()
static MachineInstrBuilder InsertNewDef (unsigned Opcode, MachineBasicBlock * BB, MachineBasicBlock::iterator I, MachineRegisterInfo::VRegAttrs RegAttrs, MachineRegisterInfo * MRI, const TargetInstrInfo * TII) static
InsertNewDef - Insert an empty PHI or IMPLICIT_DEF instruction which define a value of the given register class at the start of the specified basic block.
It returns the virtual register defined by the instruction.
Definition at line 114 of file MachineSSAUpdater.cpp.
References llvm::BuildMI(), llvm::dwarf_linker::DebugLoc, I, MRI, and TII.
Referenced by llvm::SSAUpdaterTraits< MachineSSAUpdater >::CreateEmptyPHI(), llvm::SSAUpdaterTraits< MachineSSAUpdater >::GetPoisonVal(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), and llvm::MachineSSAUpdater::RewriteUse().
LookForIdenticalPHI()
static Register LookForIdenticalPHI (MachineBasicBlock * BB, SmallVectorImpl< std::pair< MachineBasicBlock *, Register > > & PredValues) static
Definition at line 82 of file MachineSSAUpdater.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), I, Register, and Same.
Referenced by llvm::MachineSSAUpdater::GetValueInMiddleOfBlock().