LLVM: lib/Object/MachOObjectFile.cpp File Reference
MachOObjectFile.cpp File Reference
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Twine.h"
#include "llvm/ADT/bit.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/BinaryFormat/Swift.h"
#include "llvm/Object/Error.h"
#include "llvm/Object/MachO.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Object/SymbolicFile.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MemoryBufferRef.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SwapByteOrder.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Host.h"
#include "llvm/TargetParser/Triple.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <limits>
#include <list>
#include <memory>
#include <system_error>
#include "llvm/BinaryFormat/Swift.def"
Classes
struct MachOElement
Macros
#define HANDLE_SWIFT_SECTION(KIND, MACHO, ELF, COFF)
Functions
static Error malformedError (const Twine &Msg)
template<typename T >
static T getStruct (const MachOObjectFile &O, const char *P)
template<typename T >
static Expected< T > getStructOrErr (const MachOObjectFile &O, const char *P)
static const char * getSectionPtr (const MachOObjectFile &O, MachOObjectFile::LoadCommandInfo L, unsigned Sec)
static const char * getPtr (const MachOObjectFile &O, size_t Offset, size_t MachOFilesetEntryOffset=0)
static MachO::nlist_base getSymbolTableEntryBase (const MachOObjectFile &O, DataRefImpl DRI)
static StringRef parseSegmentOrSectionName (const char *P)
static unsigned getCPUType (const MachOObjectFile &O)
static unsigned getCPUSubType (const MachOObjectFile &O)
static uint32_t getPlainRelocationAddress (const MachO::any_relocation_info &RE)
static unsigned getScatteredRelocationAddress (const MachO::any_relocation_info &RE)
static bool getPlainRelocationPCRel (const MachOObjectFile &O, const MachO::any_relocation_info &RE)
static bool getScatteredRelocationPCRel (const MachO::any_relocation_info &RE)
static unsigned getPlainRelocationLength (const MachOObjectFile &O, const MachO::any_relocation_info &RE)
static unsigned getScatteredRelocationLength (const MachO::any_relocation_info &RE)
static unsigned getPlainRelocationType (const MachOObjectFile &O, const MachO::any_relocation_info &RE)
static uint32_t getSectionFlags (const MachOObjectFile &O, DataRefImpl Sec)
static Expected< MachOObjectFile::LoadCommandInfo > getLoadCommandInfo (const MachOObjectFile &Obj, const char *Ptr, uint32_t LoadCommandIndex)
static Expected< MachOObjectFile::LoadCommandInfo > getFirstLoadCommandInfo (const MachOObjectFile &Obj)
static Expected< MachOObjectFile::LoadCommandInfo > getNextLoadCommandInfo (const MachOObjectFile &Obj, uint32_t LoadCommandIndex, const MachOObjectFile::LoadCommandInfo &L)
template<typename T >
static void parseHeader (const MachOObjectFile &Obj, T &Header, Error &Err)
static Error checkOverlappingElement (std::list< MachOElement > &Elements, uint64_t Offset, uint64_t Size, const char *Name)
template<typename Segment , typename Section >
static Error parseSegmentLoadCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, SmallVectorImpl< const char * > &Sections, bool &IsPageZeroSegment, uint32_t LoadCommandIndex, const char *CmdName, uint64_t SizeOfHeaders, std::list< MachOElement > &Elements)
static Error checkSymtabCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **SymtabLoadCmd, std::list< MachOElement > &Elements)
static Error checkDysymtabCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **DysymtabLoadCmd, std::list< MachOElement > &Elements)
static Error checkLinkeditDataCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **LoadCmd, const char *CmdName, std::list< MachOElement > &Elements, const char *ElementName)
static Error checkDyldInfoCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **LoadCmd, const char *CmdName, std::list< MachOElement > &Elements)
static Error checkDylibCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char *CmdName)
static Error checkDylibIdCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **LoadCmd)
static Error checkDyldCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char *CmdName)
static Error checkVersCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **LoadCmd, const char *CmdName)
static Error checkNoteCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, std::list< MachOElement > &Elements)
static Error parseBuildVersionCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, SmallVectorImpl< const char * > &BuildTools, uint32_t LoadCommandIndex)
static Error checkRpathCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex)
static Error checkEncryptCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, uint64_t cryptoff, uint64_t cryptsize, const char **LoadCmd, const char *CmdName)
static Error checkLinkerOptCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex)
static Error checkSubCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char *CmdName, size_t SizeOfCmd, const char *CmdStructName, uint32_t PathOffset, const char *PathFieldName)
static Error checkThreadCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char *CmdName)
static Error checkTwoLevelHintsCommand (const MachOObjectFile &Obj, const MachOObjectFile::LoadCommandInfo &Load, uint32_t LoadCommandIndex, const char **LoadCmd, std::list< MachOElement > &Elements)
static bool isLoadCommandObsolete (uint32_t cmd)
template<typename T >
static int getEncodedOrdinal (T Value)
template<typename T , unsigned N>
static std::array< T, N > getArray (const MachOObjectFile &O, const void *Ptr)
Macro Definition Documentation
HANDLE_SWIFT_SECTION
#define HANDLE_SWIFT_SECTION (KIND, MACHO, ELF, COFF)
Value:
  .Case(MACHO, llvm::binaryformat::Swift5ReflectionSectionKind::KIND)
Function Documentation
checkDyldCommand()
static Error checkDyldCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char * CmdName) static
Definition at line 786 of file MachOObjectFile.cpp.
References D, getStructOrErr(), malformedError(), P, and llvm::Error::success().
checkDyldInfoCommand()
static Error checkDyldInfoCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** LoadCmd, const char * CmdName, std::list< MachOElement > & Elements) static
Definition at line 638 of file MachOObjectFile.cpp.
References llvm::MachO::dyld_info_command::bind_off, llvm::MachO::dyld_info_command::bind_size, checkOverlappingElement(), llvm::MachO::dyld_info_command::cmdsize, llvm::MachO::dyld_info_command::export_off, llvm::MachO::dyld_info_command::export_size, llvm::object::Binary::getData(), getStructOrErr(), llvm::MachO::dyld_info_command::lazy_bind_off, llvm::MachO::dyld_info_command::lazy_bind_size, malformedError(), llvm::MachO::dyld_info_command::rebase_off, llvm::MachO::dyld_info_command::rebase_size, llvm::StringRef::size(), llvm::Error::success(), llvm::MachO::dyld_info_command::weak_bind_off, and llvm::MachO::dyld_info_command::weak_bind_size.
checkDylibCommand()
static Error checkDylibCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char * CmdName) static
Definition at line 737 of file MachOObjectFile.cpp.
References D, getStructOrErr(), malformedError(), P, and llvm::Error::success().
Referenced by checkDylibIdCommand().
checkDylibIdCommand()
static Error checkDylibIdCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** LoadCmd) static
Definition at line 769 of file MachOObjectFile.cpp.
References checkDylibCommand(), llvm::MachO::mach_header::filetype, llvm::object::MachOObjectFile::getHeader(), malformedError(), llvm::MachO::MH_DYLIB, llvm::MachO::MH_DYLIB_STUB, and llvm::Error::success().
checkDysymtabCommand()
static Error checkDysymtabCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** DysymtabLoadCmd, std::list< MachOElement > & Elements) static
Definition at line 467 of file MachOObjectFile.cpp.
References checkOverlappingElement(), llvm::MachO::dysymtab_command::cmdsize, llvm::MachO::dysymtab_command::extrefsymoff, llvm::MachO::dysymtab_command::extreloff, llvm::object::Binary::getData(), getStructOrErr(), llvm::MachO::dysymtab_command::indirectsymoff, llvm::object::MachOObjectFile::is64Bit(), llvm::MachO::dysymtab_command::locreloff, malformedError(), llvm::MachO::dysymtab_command::modtaboff, llvm::MachO::dysymtab_command::nextrefsyms, llvm::MachO::dysymtab_command::nextrel, llvm::MachO::dysymtab_command::nindirectsyms, llvm::MachO::dysymtab_command::nlocrel, llvm::MachO::dysymtab_command::nmodtab, llvm::MachO::dysymtab_command::ntoc, llvm::StringRef::size(), llvm::Error::success(), and llvm::MachO::dysymtab_command::tocoff.
checkEncryptCommand()
static Error checkEncryptCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, uint64_t cryptoff, uint64_t cryptsize, const char ** LoadCmd, const char * CmdName) static
Definition at line 917 of file MachOObjectFile.cpp.
References llvm::object::Binary::getData(), malformedError(), llvm::StringRef::size(), and llvm::Error::success().
checkLinkeditDataCommand()
static Error checkLinkeditDataCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** LoadCmd, const char * CmdName, std::list< MachOElement > & Elements, const char * ElementName) static
Definition at line 600 of file MachOObjectFile.cpp.
References checkOverlappingElement(), llvm::MachO::linkedit_data_command::cmdsize, llvm::MachO::linkedit_data_command::dataoff, llvm::MachO::linkedit_data_command::datasize, llvm::object::Binary::getData(), getStructOrErr(), malformedError(), llvm::StringRef::size(), and llvm::Error::success().
checkLinkerOptCommand()
static Error checkLinkerOptCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex) static
Definition at line 941 of file MachOObjectFile.cpp.
References llvm::StringRef::find(), getStructOrErr(), malformedError(), and llvm::Error::success().
checkNoteCommand()
static Error checkNoteCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, std::list< MachOElement > & Elements) static
Definition at line 833 of file MachOObjectFile.cpp.
References checkOverlappingElement(), llvm::object::Binary::getData(), getStructOrErr(), malformedError(), llvm::MachO::note_command::offset, llvm::MachO::note_command::size, llvm::StringRef::size(), and llvm::Error::success().
checkOverlappingElement()
static Error checkOverlappingElement (std::list< MachOElement > & Elements, uint64_t Offset, uint64_t Size, const char * Name) static
Definition at line 252 of file MachOObjectFile.cpp.
References malformedError(), N, Name, llvm::Offset, Size, and llvm::Error::success().
Referenced by checkDyldInfoCommand(), checkDysymtabCommand(), checkLinkeditDataCommand(), checkNoteCommand(), checkSymtabCommand(), checkTwoLevelHintsCommand(), and parseSegmentLoadCommand().
checkRpathCommand()
static Error checkRpathCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex) static
Definition at line 885 of file MachOObjectFile.cpp.
References getStructOrErr(), malformedError(), P, and llvm::Error::success().
checkSubCommand()
static Error checkSubCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char * CmdName, size_t SizeOfCmd, const char * CmdStructName, uint32_t PathOffset, const char * PathFieldName) static
Definition at line 981 of file MachOObjectFile.cpp.
References malformedError(), P, and llvm::Error::success().
checkSymtabCommand()
static Error checkSymtabCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** SymtabLoadCmd, std::list< MachOElement > & Elements) static
Definition at line 409 of file MachOObjectFile.cpp.
References checkOverlappingElement(), llvm::MachO::symtab_command::cmdsize, llvm::object::Binary::getData(), getStructOrErr(), llvm::object::MachOObjectFile::is64Bit(), malformedError(), llvm::MachO::symtab_command::nsyms, llvm::StringRef::size(), llvm::MachO::symtab_command::stroff, llvm::MachO::symtab_command::strsize, llvm::Error::success(), and llvm::MachO::symtab_command::symoff.
checkThreadCommand()
static Error checkThreadCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char * CmdName) static
Definition at line 1008 of file MachOObjectFile.cpp.
References llvm::MachO::ARM_THREAD_STATE, llvm::MachO::ARM_THREAD_STATE64, llvm::MachO::ARM_THREAD_STATE64_COUNT, llvm::MachO::ARM_THREAD_STATE_COUNT, llvm::count(), llvm::MachO::CPU_TYPE_ARM, llvm::MachO::CPU_TYPE_ARM64, llvm::MachO::CPU_TYPE_ARM64_32, llvm::MachO::CPU_TYPE_I386, llvm::MachO::CPU_TYPE_POWERPC, llvm::MachO::CPU_TYPE_X86_64, getCPUType(), getStructOrErr(), llvm::object::Binary::isLittleEndian(), llvm::sys::IsLittleEndianHost, malformedError(), llvm::MachO::PPC_THREAD_STATE, llvm::MachO::PPC_THREAD_STATE_COUNT, llvm::Error::success(), llvm::sys::swapByteOrder(), llvm::MachO::x86_EXCEPTION_STATE, llvm::MachO::x86_EXCEPTION_STATE64, llvm::MachO::x86_EXCEPTION_STATE64_COUNT, llvm::MachO::x86_EXCEPTION_STATE_COUNT, llvm::MachO::x86_FLOAT_STATE, llvm::MachO::x86_FLOAT_STATE_COUNT, llvm::MachO::x86_THREAD_STATE, llvm::MachO::x86_THREAD_STATE32, llvm::MachO::x86_THREAD_STATE32_COUNT, llvm::MachO::x86_THREAD_STATE64, llvm::MachO::x86_THREAD_STATE64_COUNT, and llvm::MachO::x86_THREAD_STATE_COUNT.
checkTwoLevelHintsCommand()
static Error checkTwoLevelHintsCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** LoadCmd, std::list< MachOElement > & Elements) static
Definition at line 1199 of file MachOObjectFile.cpp.
References checkOverlappingElement(), llvm::object::Binary::getData(), getStructOrErr(), malformedError(), llvm::MachO::twolevel_hints_command::nhints, llvm::MachO::twolevel_hints_command::offset, llvm::StringRef::size(), and llvm::Error::success().
checkVersCommand()
static Error checkVersCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, uint32_t LoadCommandIndex, const char ** LoadCmd, const char * CmdName) static
Definition at line 818 of file MachOObjectFile.cpp.
References malformedError(), and llvm::Error::success().
getArray()
template<typename T , unsigned N> static std::array< T, N > getArray (const MachOObjectFile & O, const void * Ptr) static
Definition at line 5149 of file MachOObjectFile.cpp.
References llvm::sys::IsLittleEndianHost, N, Ptr, and llvm::sys::swapByteOrder().
Referenced by llvm::object::MachOObjectFile::getDyldChainedFixupTargets().
getCPUSubType()
static unsigned getCPUSubType (const MachOObjectFile & O) static
Definition at line 136 of file MachOObjectFile.cpp.
Referenced by llvm::object::MachOObjectFile::getArch().
getCPUType()
static unsigned getCPUType (const MachOObjectFile & O) static
Definition at line 132 of file MachOObjectFile.cpp.
Referenced by checkThreadCommand(), llvm::object::MachOObjectFile::getArch(), llvm::object::MachOObjectFile::getFileFormatName(), and llvm::object::MachOObjectFile::isRelocationScattered().
getEncodedOrdinal()
template<typename T > static int getEncodedOrdinal (T Value) static
Definition at line 5140 of file MachOObjectFile.cpp.
References llvm::MachO::BIND_SPECIAL_DYLIB_FLAT_LOOKUP, llvm::MachO::BIND_SPECIAL_DYLIB_MAIN_EXECUTABLE, llvm::MachO::BIND_SPECIAL_DYLIB_WEAK_LOOKUP, llvm::SignExtend32(), and llvm::Value.
Referenced by llvm::object::MachOObjectFile::getDyldChainedFixupTargets().
getFirstLoadCommandInfo()
static Expected< MachOObjectFile::LoadCommandInfo > getFirstLoadCommandInfo (const MachOObjectFile & Obj) static
Definition at line 207 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::getHeader(), getLoadCommandInfo(), llvm::object::MachOObjectFile::getMachOFilesetEntryOffset(), getPtr(), llvm::object::MachOObjectFile::is64Bit(), malformedError(), and llvm::MachO::mach_header::sizeofcmds.
getLoadCommandInfo()
static Expected< MachOObjectFile::LoadCommandInfo > getLoadCommandInfo (const MachOObjectFile & Obj, const char * Ptr, uint32_t LoadCommandIndex) static
Definition at line 192 of file MachOObjectFile.cpp.
References llvm::StringRef::end(), llvm::object::Binary::getData(), getStructOrErr(), malformedError(), Ptr, and llvm::Expected< T >::takeError().
Referenced by getFirstLoadCommandInfo(), and getNextLoadCommandInfo().
getNextLoadCommandInfo()
static Expected< MachOObjectFile::LoadCommandInfo > getNextLoadCommandInfo (const MachOObjectFile & Obj, uint32_t LoadCommandIndex, const MachOObjectFile::LoadCommandInfo & L) static
Definition at line 218 of file MachOObjectFile.cpp.
References llvm::StringRef::data(), llvm::object::Binary::getData(), llvm::object::MachOObjectFile::getHeader(), getLoadCommandInfo(), llvm::object::MachOObjectFile::getMachOFilesetEntryOffset(), llvm::object::MachOObjectFile::is64Bit(), malformedError(), and llvm::MachO::mach_header::sizeofcmds.
getPlainRelocationAddress()
static uint32_t getPlainRelocationAddress (const MachO::any_relocation_info & RE) static
Definition at line 141 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationAddress(), and llvm::object::MachOObjectFile::isRelocationScattered().
getPlainRelocationLength()
static unsigned getPlainRelocationLength (const MachOObjectFile & O, const MachO::any_relocation_info & RE) static
Definition at line 162 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word1.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationLength().
getPlainRelocationPCRel()
static bool getPlainRelocationPCRel (const MachOObjectFile & O, const MachO::any_relocation_info & RE) static
Definition at line 150 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word1.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationPCRel().
getPlainRelocationType()
static unsigned getPlainRelocationType (const MachOObjectFile & O, const MachO::any_relocation_info & RE) static
Definition at line 174 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word1.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationType().
getPtr()
static const char * getPtr (const MachOObjectFile & O, size_t Offset, size_t MachOFilesetEntryOffset = 0) static
Definition at line 111 of file MachOObjectFile.cpp.
References assert(), and llvm::Offset.
Referenced by llvm::object::MachOObjectFile::begin_dices(), llvm::Error::dynamicClassID(), llvm::object::MachOObjectFile::end_dices(), llvm::object::MachOObjectFile::getChainedFixupsHeader(), llvm::object::MachOObjectFile::getChainedFixupsSegments(), llvm::object::MachOObjectFile::getDataInCodeTableEntry(), llvm::object::MachOObjectFile::getDyldChainedFixupTargets(), llvm::object::MachOObjectFile::getDyldExportsTrie(), llvm::object::MachOObjectFile::getDyldInfoBindOpcodes(), llvm::object::MachOObjectFile::getDyldInfoExportsTrie(), llvm::object::MachOObjectFile::getDyldInfoLazyBindOpcodes(), llvm::object::MachOObjectFile::getDyldInfoRebaseOpcodes(), llvm::object::MachOObjectFile::getDyldInfoWeakBindOpcodes(), getFirstLoadCommandInfo(), llvm::object::MachOObjectFile::getIndirectSymbolTableEntry(), llvm::object::MachOObjectFile::getRelocation(), llvm::object::MachOObjectFile::getRelocationSymbol(), llvm::object::MachOObjectFile::getSymbolByIndex(), llvm::object::MachOObjectFile::getSymbolIndex(), llvm::Error::isA(), llvm::Error::operator bool(), parseHeader(), llvm::object::MachOObjectFile::symbol_end(), and llvm::Error::~Error().
getScatteredRelocationAddress()
static unsigned getScatteredRelocationAddress (const MachO::any_relocation_info & RE) static
Definition at line 146 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationAddress().
getScatteredRelocationLength()
static unsigned getScatteredRelocationLength (const MachO::any_relocation_info & RE) static
Definition at line 170 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationLength().
getScatteredRelocationPCRel()
static bool getScatteredRelocationPCRel (const MachO::any_relocation_info & RE) static
Definition at line 158 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationPCRel().
getSectionFlags()
static uint32_t getSectionFlags (const MachOObjectFile & O, DataRefImpl Sec) static
Definition at line 181 of file MachOObjectFile.cpp.
References llvm::MachO::section::flags, and llvm::MachO::section_64::flags.
Referenced by llvm::object::MachOObjectFile::getSectionType(), llvm::object::MachOObjectFile::isSectionBSS(), llvm::object::MachOObjectFile::isSectionData(), llvm::object::MachOObjectFile::isSectionText(), and llvm::object::MachOObjectFile::isSectionVirtual().
getSectionPtr()
static const char * getSectionPtr (const MachOObjectFile & O, MachOObjectFile::LoadCommandInfo L, unsigned Sec) static
Definition at line 97 of file MachOObjectFile.cpp.
Referenced by llvm::object::MachOObjectFile::getSection(), llvm::object::MachOObjectFile::getSection64(), and parseSegmentLoadCommand().
getStruct()
template<typename T > static T getStruct (const MachOObjectFile & O, const char * P) static
Definition at line 71 of file MachOObjectFile.cpp.
References P, llvm::report_fatal_error(), and llvm::MachO::swapStruct().
Referenced by llvm::object::MachOObjectFile::getBuildToolVersion(), llvm::object::MachOObjectFile::getBuildVersionLoadCommand(), llvm::object::MachOObjectFile::getDataInCodeLoadCommand(), llvm::object::MachOObjectFile::getDataInCodeTableEntry(), llvm::object::MachOObjectFile::getDice(), llvm::object::MachOObjectFile::getDyldInfoLoadCommand(), llvm::object::MachOObjectFile::getDylibIDLoadCommand(), llvm::object::MachOObjectFile::getDylinkerCommand(), llvm::object::MachOObjectFile::getDysymtabLoadCommand(), llvm::object::MachOObjectFile::getEncryptionInfoCommand(), llvm::object::MachOObjectFile::getEncryptionInfoCommand64(), llvm::object::MachOObjectFile::getEntryPointCommand(), llvm::object::MachOObjectFile::getFilesetEntryLoadCommand(), llvm::object::MachOObjectFile::getIndirectSymbolTableEntry(), llvm::object::MachOObjectFile::getLinkeditDataLoadCommand(), llvm::object::MachOObjectFile::getLinkerOptionLoadCommand(), llvm::object::MachOObjectFile::getLinkOptHintsLoadCommand(), llvm::object::MachOObjectFile::getNoteLoadCommand(), llvm::object::MachOObjectFile::getRelocation(), llvm::object::MachOObjectFile::getRoutinesCommand(), llvm::object::MachOObjectFile::getRoutinesCommand64(), llvm::object::MachOObjectFile::getRpathCommand(), llvm::object::MachOObjectFile::getSection(), llvm::object::MachOObjectFile::getSection(), llvm::object::MachOObjectFile::getSection64(), llvm::object::MachOObjectFile::getSection64(), llvm::object::MachOObjectFile::getSegment64LoadCommand(), llvm::object::MachOObjectFile::getSegmentLoadCommand(), llvm::object::MachOObjectFile::getSourceVersionCommand(), llvm::object::MachOObjectFile::getSubClientCommand(), llvm::object::MachOObjectFile::getSubFrameworkCommand(), llvm::object::MachOObjectFile::getSubLibraryCommand(), llvm::object::MachOObjectFile::getSubUmbrellaCommand(), llvm::object::MachOObjectFile::getSymbol64TableEntry(), llvm::object::MachOObjectFile::getSymbolTableEntry(), getSymbolTableEntryBase(), llvm::object::MachOObjectFile::getSymtabLoadCommand(), llvm::object::MachOObjectFile::getThreadCommand(), llvm::object::MachOObjectFile::getUuidCommand(), and llvm::object::MachOObjectFile::getVersionMinLoadCommand().
getStructOrErr()
template<typename T > static Expected< T > getStructOrErr (const MachOObjectFile & O, const char * P) static
Definition at line 84 of file MachOObjectFile.cpp.
References malformedError(), P, and llvm::MachO::swapStruct().
Referenced by checkDyldCommand(), checkDyldInfoCommand(), checkDylibCommand(), checkDysymtabCommand(), checkLinkeditDataCommand(), checkLinkerOptCommand(), checkNoteCommand(), checkRpathCommand(), checkSymtabCommand(), checkThreadCommand(), checkTwoLevelHintsCommand(), llvm::object::MachOObjectFile::getChainedFixupsHeader(), llvm::object::MachOObjectFile::getChainedFixupsLoadCommand(), llvm::object::MachOObjectFile::getChainedFixupsSegments(), llvm::object::MachOObjectFile::getDyldExportsTrie(), llvm::object::MachOObjectFile::getDyldInfoBindOpcodes(), llvm::object::MachOObjectFile::getDyldInfoExportsTrie(), llvm::object::MachOObjectFile::getDyldInfoLazyBindOpcodes(), llvm::object::MachOObjectFile::getDyldInfoRebaseOpcodes(), llvm::object::MachOObjectFile::getDyldInfoWeakBindOpcodes(), llvm::object::MachOObjectFile::getFunctionStarts(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), getLoadCommandInfo(), parseBuildVersionCommand(), parseHeader(), and parseSegmentLoadCommand().
getSymbolTableEntryBase()
static MachO::nlist_base getSymbolTableEntryBase (const MachOObjectFile & O, DataRefImpl DRI) static
Definition at line 119 of file MachOObjectFile.cpp.
References getStruct(), P, and llvm::object::DataRefImpl::p.
Referenced by llvm::object::MachOObjectFile::getIndirectName(), llvm::object::MachOObjectFile::getSymbolAlignment(), llvm::object::MachOObjectFile::getSymbolFlags(), llvm::object::MachOObjectFile::getSymbolName(), llvm::object::MachOObjectFile::getSymbolSection(), llvm::object::MachOObjectFile::getSymbolSectionID(), and llvm::object::MachOObjectFile::getSymbolType().
isLoadCommandObsolete()
static bool isLoadCommandObsolete (uint32_t cmd) static
Definition at line 1238 of file MachOObjectFile.cpp.
References llvm::MachO::linker_option_command::cmd.
malformedError()
static Error malformedError (const Twine & Msg) static
Definition at line 63 of file MachOObjectFile.cpp.
References llvm::make_error().
Referenced by checkDyldCommand(), checkDyldInfoCommand(), checkDylibCommand(), checkDylibIdCommand(), checkDysymtabCommand(), checkEncryptCommand(), checkLinkeditDataCommand(), checkLinkerOptCommand(), checkNoteCommand(), checkOverlappingElement(), checkRpathCommand(), checkSubCommand(), checkSymtabCommand(), checkThreadCommand(), checkTwoLevelHintsCommand(), checkVersCommand(), getFirstLoadCommandInfo(), getLoadCommandInfo(), getNextLoadCommandInfo(), getStructOrErr(), parseBuildVersionCommand(), parseHeader(), and parseSegmentLoadCommand().
parseBuildVersionCommand()
static Error parseBuildVersionCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, SmallVectorImpl< const char * > & BuildTools, uint32_t LoadCommandIndex) static
Definition at line 862 of file MachOObjectFile.cpp.
References getStructOrErr(), malformedError(), llvm::MachO::build_version_command::ntools, llvm::SmallVectorImpl< T >::resize(), and llvm::Error::success().
parseHeader()
template<typename T > static void parseHeader (const MachOObjectFile & Obj, T & Header, Error & Err) static
Definition at line 231 of file MachOObjectFile.cpp.
References llvm::object::Binary::getData(), llvm::object::MachOObjectFile::getMachOFilesetEntryOffset(), getPtr(), getStructOrErr(), malformedError(), and llvm::StringRef::size().
parseSegmentLoadCommand()
template<typename Segment , typename Section > static Error parseSegmentLoadCommand (const MachOObjectFile & Obj, const MachOObjectFile::LoadCommandInfo & Load, SmallVectorImpl< const char * > & Sections, bool & IsPageZeroSegment, uint32_t LoadCommandIndex, const char * CmdName, uint64_t SizeOfHeaders, std::list< MachOElement > & Elements) static
Definition at line 285 of file MachOObjectFile.cpp.
References checkOverlappingElement(), llvm::MachO::mach_header::filetype, llvm::object::Binary::getData(), llvm::object::MachOObjectFile::getHeader(), getSectionPtr(), getStructOrErr(), malformedError(), llvm::MachO::MH_DSYM, llvm::MachO::MH_DYLIB_STUB, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachO::S_THREAD_LOCAL_ZEROFILL, llvm::MachO::S_ZEROFILL, llvm::StringRef::size(), and llvm::Error::success().
parseSegmentOrSectionName()
static StringRef parseSegmentOrSectionName (const char * P) static
Definition at line 124 of file MachOObjectFile.cpp.
References P.
Referenced by llvm::object::MachOObjectFile::getSectionFinalSegmentName(), and llvm::object::MachOObjectFile::getSectionName().