LLVM: lib/TableGen/Main.cpp File Reference
Main.cpp File Reference
#include "llvm/TableGen/Main.h"
#include "TGLexer.h"
#include "TGParser.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SMLoc.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TableGen/Error.h"
#include "llvm/TableGen/Record.h"
#include "llvm/TableGen/TableGenBackend.h"
#include <memory>
#include <string>
#include <system_error>
#include <utility>
Functions
static int reportError (const char *ProgName, Twine Msg)
static int createDependencyFile (const TGParser &Parser, const char *argv0)
Create a dependency file for -d option.
Variables
static cl::opt< std::string > OutputFilename ("o", cl::desc("Output filename"), cl::value_desc("filename"), cl::init("-"))
static cl::opt< std::string > DependFilename ("d", cl::desc("Dependency filename"), cl::value_desc("filename"), cl::init(""))
static cl::opt< std::string > InputFilename (cl::Positional, cl::desc("<input file>"), cl::init("-"))
static cl::list< std::string > IncludeDirs ("I", cl::desc("Directory of include files"), cl::value_desc("directory"), cl::Prefix)
static cl::list< std::string > MacroNames ("D", cl::desc("Name of the macro to be defined"), cl::value_desc("macro name"), cl::Prefix)
static cl::opt< bool > WriteIfChanged ("write-if-changed", cl::desc("Only write output if it changed"))
static cl::opt< bool > TimePhases ("time-phases", cl::desc("Time phases of parser and backend"))
static cl::opt< bool > NoWarnOnUnusedTemplateArgs ("no-warn-on-unused-template-args", cl::desc("Disable unused template argument warnings."))
Function Documentation
createDependencyFile()
static int createDependencyFile (const TGParser & Parser, const char * argv0) static
Create a dependency file for -d option.
This functionality is really only for the benefit of the build system. It is similar to GCC's -M* family of options.
Definition at line 80 of file Main.cpp.
References DependFilename, llvm::TGParser::getDependencies(), llvm::ToolOutputFile::keep(), llvm::sys::fs::OF_Text, llvm::ToolOutputFile::os(), OutputFilename, and reportError().
Referenced by llvm::TableGenMain().
reportError()
static int reportError (const char * ProgName, Twine Msg) static
Definition at line 70 of file Main.cpp.
References llvm::errs(), and llvm::raw_ostream::flush().
Referenced by createDependencyFile(), and llvm::TableGenMain().
Variable Documentation
DependFilename
cl::opt< std::string > DependFilename("d", cl::desc("Dependency filename"), cl::value_desc("filename"), cl::init("")) ("d" , cl::desc("Dependency filename") , cl::value_desc("filename") , cl::init("")) static
Referenced by createDependencyFile(), and llvm::TableGenMain().
IncludeDirs
cl::list< std::string > IncludeDirs("I", cl::desc("Directory of include files"), cl::value_desc("directory"), cl::Prefix) ("I" , cl::desc("Directory of include files") , cl::value_desc("directory") , cl::Prefix) static
Referenced by llvm::TableGenMain().
InputFilename
cl::opt< std::string > InputFilename(cl::Positional, cl::desc("<input file>"), cl::init("-")) (cl::Positional , cl::desc("<input file>") , cl::init("-")) static
Referenced by llvm::TableGenMain().
MacroNames
cl::list< std::string > MacroNames("D", cl::desc("Name of the macro to be defined"), cl::value_desc("macro name"), cl::Prefix) ("D" , cl::desc("Name of the macro to be defined") , cl::value_desc("macro name") , cl::Prefix) static
Referenced by llvm::TableGenMain().
NoWarnOnUnusedTemplateArgs
cl::opt< bool > NoWarnOnUnusedTemplateArgs("no-warn-on-unused-template-args", cl::desc("Disable unused template argument warnings.")) ("no-warn-on-unused-template-args" , cl::desc("Disable unused template argument warnings.")) static
Referenced by llvm::TableGenMain().
OutputFilename
cl::opt< std::string > OutputFilename("o", cl::desc("Output filename"), cl::value_desc("filename"), cl::init("-")) ("o" , cl::desc("Output filename") , cl::value_desc("filename") , cl::init("-")) static
Referenced by llvm::FilePermissionsApplier::apply(), createDependencyFile(), llvm::CreateInfoOutputFile(), llvm::DisplayGraph(), llvm::EmitImportsFiles(), llvm::AsmPrinter::emitStackUsage(), and llvm::TableGenMain().
TimePhases
cl::opt< bool > TimePhases("time-phases", cl::desc("Time phases of parser and backend")) ("time-phases" , cl::desc("Time phases of parser and backend")) static
Referenced by llvm::TableGenMain().
WriteIfChanged
cl::opt< bool > WriteIfChanged("write-if-changed", cl::desc("Only write output if it changed")) ("write-if-changed" , cl::desc("Only write output if it changed")) static
Referenced by llvm::TableGenMain(), llvm::ifs::writeBinaryStub(), and llvm::ifs::writeELFBinaryToFile().