LLVM: lib/Analysis/MemoryProfileInfo.cpp File Reference
MemoryProfileInfo.cpp File Reference
#include "llvm/Analysis/MemoryProfileInfo.h"
#include "llvm/Support/CommandLine.h"
Macros
#define DEBUG_TYPE "memory-profile-info"
Functions
static void addAllocTypeAttribute (LLVMContext &Ctx, CallBase *CI, AllocationType AllocType)
static MDNode * createMIBNode (LLVMContext &Ctx, std::vector< uint64_t > &MIBCallStack, AllocationType AllocType, uint64_t TotalSize)
Variables
cl::opt< float > MemProfLifetimeAccessDensityColdThreshold ("memprof-lifetime-access-density-cold-threshold", cl::init(0.05), cl::Hidden, cl::desc("The threshold the lifetime access density (accesses per byte per " "lifetime sec) must be under to consider an allocation cold"))
cl::opt< unsigned > MemProfAveLifetimeColdThreshold ("memprof-ave-lifetime-cold-threshold", cl::init(200), cl::Hidden, cl::desc("The average lifetime (s) for an allocation to be considered " "cold"))
cl::opt< unsigned > MemProfMinAveLifetimeAccessDensityHotThreshold ("memprof-min-ave-lifetime-access-density-hot-threshold", cl::init(1000), cl::Hidden, cl::desc("The minimum TotalLifetimeAccessDensity / AllocCount for an " "allocation to be considered hot"))
cl::opt< bool > MemProfReportHintedSizes ("memprof-report-hinted-sizes", cl::init(false), cl::Hidden, cl::desc("Report total allocation sizes of hinted allocations"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "memory-profile-info"
Definition at line 19 of file MemoryProfileInfo.cpp.
Function Documentation
addAllocTypeAttribute()
static void addAllocTypeAttribute (LLVMContext & Ctx, CallBase * CI, AllocationType AllocType) static
Definition at line 124 of file MemoryProfileInfo.cpp.
References A, llvm::CallBase::addFnAttr(), llvm::Attribute::get(), and llvm::memprof::getAllocTypeAttributeString().
Referenced by llvm::memprof::CallStackTrie::buildAndAttachMIBMetadata().
createMIBNode()
static MDNode * createMIBNode (LLVMContext & Ctx, std::vector< uint64_t > & MIBCallStack, AllocationType AllocType, uint64_t TotalSize) static
Definition at line 186 of file MemoryProfileInfo.cpp.
References llvm::memprof::buildCallstackMetadata(), llvm::MDNode::get(), llvm::MDString::get(), llvm::ValueAsMetadata::get(), llvm::memprof::getAllocTypeAttributeString(), and llvm::Type::getInt64Ty().
Variable Documentation
MemProfAveLifetimeColdThreshold
cl::opt< unsigned > MemProfAveLifetimeColdThreshold("memprof-ave-lifetime-cold-threshold", cl::init(200), cl::Hidden, cl::desc("The average lifetime (s) for an allocation to be considered " "cold")) ("memprof-ave-lifetime-cold-threshold" , cl::init(200) , cl::Hidden , cl::desc("The average lifetime (s) for an allocation to be considered " "cold"))
Referenced by llvm::memprof::getAllocType().
MemProfLifetimeAccessDensityColdThreshold
cl::opt< float > MemProfLifetimeAccessDensityColdThreshold("memprof-lifetime-access-density-cold-threshold", cl::init(0.05), cl::Hidden, cl::desc("The threshold the lifetime access density (accesses per byte per " "lifetime sec) must be under to consider an allocation cold")) ("memprof-lifetime-access-density-cold-threshold" , cl::init(0.05) , cl::Hidden , cl::desc("The threshold the lifetime access density (accesses per byte per " "lifetime sec) must be under to consider an allocation cold"))
Referenced by llvm::memprof::getAllocType().
MemProfMinAveLifetimeAccessDensityHotThreshold
cl::opt< unsigned > MemProfMinAveLifetimeAccessDensityHotThreshold("memprof-min-ave-lifetime-access-density-hot-threshold", cl::init(1000), cl::Hidden, cl::desc("The minimum TotalLifetimeAccessDensity / AllocCount for an " "allocation to be considered hot")) ("memprof-min-ave-lifetime-access-density-hot-threshold" , cl::init(1000) , cl::Hidden , cl::desc("The minimum TotalLifetimeAccessDensity / AllocCount for an " "allocation to be considered hot"))
Referenced by llvm::memprof::getAllocType().
MemProfReportHintedSizes
cl::opt< bool > MemProfReportHintedSizes("memprof-report-hinted-sizes", cl::init(false), cl::Hidden, cl::desc("Report total allocation sizes of hinted allocations")) ("memprof-report-hinted-sizes" , cl::init(false) , cl::Hidden , cl::desc("Report total allocation sizes of hinted allocations"))
Referenced by addCallStack(), and llvm::memprof::CallStackTrie::buildAndAttachMIBMetadata().