LLVM: lib/Target/Mips/MipsCallLowering.cpp File Reference
MipsCallLowering.cpp File Reference
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
#include "MipsCallLowering.h"
#include "MipsCCState.h"
#include "MipsMachineFunction.h"
#include "MipsTargetMachine.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
Functions
static bool isSupportedArgumentType (Type *T)
static bool isSupportedReturnType (Type *T)
Detailed Description
This file implements the lowering of LLVM calls to machine code calls for GlobalISel.
Definition in file MipsCallLowering.cpp.
Function Documentation
isSupportedArgumentType()
static bool isSupportedArgumentType (Type * T) static
Definition at line 293 of file MipsCallLowering.cpp.
Referenced by llvm::MipsCallLowering::lowerCall(), llvm::RISCVCallLowering::lowerCall(), llvm::MipsCallLowering::lowerFormalArguments(), and llvm::RISCVCallLowering::lowerFormalArguments().
isSupportedReturnType()
static bool isSupportedReturnType (Type * T) static
Definition at line 303 of file MipsCallLowering.cpp.
Referenced by isSupportedReturnType(), llvm::MipsCallLowering::lowerCall(), llvm::RISCVCallLowering::lowerCall(), and llvm::MipsCallLowering::lowerReturn().