LLVM: lib/IR/Module.cpp File Reference
Module.cpp File Reference
#include "llvm/IR/Module.h"
#include "SymbolTableListTraitsImpl.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Comdat.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GVMaterializer.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalIFunc.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/ModuleSummaryIndex.h"
#include "llvm/IR/SymbolTableListTraits.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/TypeFinder.h"
#include "llvm/IR/Value.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/RandomNumberGenerator.h"
#include "llvm/Support/VersionTuple.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <memory>
#include <optional>
#include <utility>
#include <vector>
Functions
static void addSDKVersionMD (const VersionTuple &V, Module &M, StringRef Name)
static VersionTuple getSDKVersionMD (Metadata *MD)
Variables
cl::opt< bool > UseNewDbgInfoFormat
Function Documentation
addSDKVersionMD()
static void addSDKVersionMD (const VersionTuple & V, Module & M, StringRef Name) static
Definition at line 806 of file Module.cpp.
References llvm::ConstantDataArray::get(), Name, and llvm::Module::Warning.
Referenced by llvm::Module::setDarwinTargetVariantSDKVersion(), and llvm::Module::setSDKVersion().
getSDKVersionMD()
static VersionTuple getSDKVersionMD (Metadata * MD) static
Definition at line 824 of file Module.cpp.
References llvm::dyn_cast_or_null().
Referenced by llvm::Module::getDarwinTargetVariantSDKVersion(), and llvm::Module::getSDKVersion().
Variable Documentation
UseNewDbgInfoFormat
cl::opt<bool> UseNewDbgInfoFormat extern