LLVM: lib/Transforms/Utils/MoveAutoInit.cpp File Reference
MoveAutoInit.cpp File Reference
#include "llvm/Transforms/Utils/MoveAutoInit.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/MemorySSA.h"
#include "llvm/Analysis/MemorySSAUpdater.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Utils.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
Macros
#define DEBUG_TYPE "move-auto-init"
Functions
STATISTIC (NumMoved, "Number of instructions moved")
static bool hasAutoInitMetadata (const Instruction &I)
static std::optional< MemoryLocation > writeToAlloca (const Instruction &I)
static BasicBlock * usersDominator (const MemoryLocation &ML, Instruction *I, DominatorTree &DT, MemorySSA &MSSA)
Finds a BasicBlock in the CFG where instruction I can be moved to while not changing the Memory SSA ordering and being guarded by at least one condition.
static bool runMoveAutoInit (Function &F, DominatorTree &DT, MemorySSA &MSSA)
Variables
static cl::opt< unsigned > MoveAutoInitThreshold ("move-auto-init-threshold", cl::Hidden, cl::init(128), cl::desc("Maximum instructions to analyze per moved initialization"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "move-auto-init"
Definition at line 31 of file MoveAutoInit.cpp.
Function Documentation
hasAutoInitMetadata()
static bool hasAutoInitMetadata (const Instruction & I) static
Definition at line 39 of file MoveAutoInit.cpp.
References llvm::any_of(), and I.
Referenced by runMoveAutoInit().
runMoveAutoInit()
static bool runMoveAutoInit (Function & F, DominatorTree & DT, MemorySSA & MSSA) static
Definition at line 106 of file MoveAutoInit.cpp.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorBase< Size_T >::empty(), F, llvm::DominatorTree::findNearestCommonDominator(), llvm::BasicBlock::getFirstNonPHI(), llvm::MemorySSA::getMemoryAccess(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::BasicBlock::getUniquePredecessor(), hasAutoInitMetadata(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::isa(), llvm::DominatorTree::isReachableFromEntry(), ML, llvm::MemorySSAUpdater::moveToPlace(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::predecessors(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::reverse(), llvm::SmallVectorBase< Size_T >::size(), llvm::Successor, llvm::successors(), usersDominator(), llvm::VerifyMemorySSA, llvm::MemorySSA::verifyMemorySSA(), and writeToAlloca().
Referenced by llvm::MoveAutoInitPass::run().
STATISTIC()
STATISTIC (NumMoved , "Number of instructions moved")
usersDominator()
static BasicBlock * usersDominator (const MemoryLocation & ML, Instruction * I, DominatorTree & DT, MemorySSA & MSSA) static
Finds a BasicBlock in the CFG where instruction I can be moved to while not changing the Memory SSA ordering and being guarded by at least one condition.
Definition at line 63 of file MoveAutoInit.cpp.
References llvm::append_range(), llvm::cast(), llvm::dyn_cast(), llvm::SmallVectorBase< Size_T >::empty(), llvm::DominatorTree::findNearestCommonDominator(), llvm::MemorySSA::getAA(), llvm::MemorySSA::getMemoryAccess(), llvm::BatchAAResults::getModRefInfo(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::map_range(), MI, ML, MoveAutoInitThreshold, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallPtrSetImplBase::size(), and llvm::Value::users().
Referenced by runMoveAutoInit().
writeToAlloca()
static std::optional< MemoryLocation > writeToAlloca (const Instruction & I) static
Definition at line 45 of file MoveAutoInit.cpp.
References llvm::dyn_cast(), llvm::MemoryLocation::get(), llvm::MemoryLocation::getForDest(), llvm::getUnderlyingObject(), I, llvm::isa(), MI, and ML.
Referenced by runMoveAutoInit().
Variable Documentation
MoveAutoInitThreshold
cl::opt< unsigned > MoveAutoInitThreshold("move-auto-init-threshold", cl::Hidden, cl::init(128), cl::desc("Maximum instructions to analyze per moved initialization")) ("move-auto-init-threshold" , cl::Hidden , cl::init(128) , cl::desc("Maximum instructions to analyze per moved initialization")) static
Referenced by usersDominator().