LLVM: llvm::LoongArchABI Namespace Reference
llvm::LoongArchABI Namespace Reference
Enumerations
enum ABI {
ABI_ILP32S , ABI_ILP32F , ABI_ILP32D , ABI_LP64S ,
ABI_LP64F , ABI_LP64D , ABI_Unknown
}
Functions
static ABI checkABIStandardized (ABI Abi)
static ABI getTripleABI (const Triple &TT)
ABI computeTargetABI (const Triple &TT, const FeatureBitset &FeatureBits, StringRef ABIName)
ABI getTargetABI (StringRef ABIName)
MCRegister getBPReg ()
Enumeration Type Documentation
ABI
enum llvm::LoongArchABI::ABI
Enumerator
ABI_ILP32S
ABI_ILP32F
ABI_ILP32D
ABI_LP64S
ABI_LP64F
ABI_LP64D
ABI_Unknown
Definition at line 62 of file LoongArchBaseInfo.h.
Function Documentation
checkABIStandardized()
static ABI llvm::LoongArchABI::checkABIStandardized (ABI Abi) static
Definition at line 28 of file LoongArchBaseInfo.cpp.
References ABI_ILP32D, ABI_ILP32F, ABI_ILP32S, ABI_LP64D, ABI_LP64F, ABI_LP64S, llvm::errs(), and llvm_unreachable.
Referenced by computeTargetABI().
computeTargetABI()
ABI llvm::LoongArchABI::computeTargetABI (const Triple & TT, const FeatureBitset & FeatureBits, StringRef ABIName)
Definition at line 72 of file LoongArchBaseInfo.cpp.
References ABI_ILP32D, ABI_ILP32F, ABI_ILP32S, ABI_LP64D, ABI_LP64F, ABI_LP64S, ABI_Unknown, checkABIStandardized(), llvm::StringRef::empty(), llvm::errs(), getTargetABI(), getTripleABI(), and llvm_unreachable.
Referenced by llvm::LoongArchTargetELFStreamer::LoongArchTargetELFStreamer().
getBPReg()
MCRegister llvm::LoongArchABI::getBPReg ()
Definition at line 191 of file LoongArchBaseInfo.cpp.
Referenced by llvm::LoongArchRegisterInfo::canRealignStack(), llvm::LoongArchFrameLowering::determineCalleeSaves(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::LoongArchFrameLowering::getFrameIndexReference(), and llvm::LoongArchRegisterInfo::getReservedRegs().
getTargetABI()
ABI llvm::LoongArchABI::getTargetABI (StringRef ABIName)
Definition at line 176 of file LoongArchBaseInfo.cpp.
References ABI_ILP32D, ABI_ILP32F, ABI_ILP32S, ABI_LP64D, ABI_LP64F, ABI_LP64S, ABI_Unknown, llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Default().
Referenced by computeTargetABI(), and llvm::LoongArchTargetMachine::getSubtargetImpl().
getTripleABI()
static ABI llvm::LoongArchABI::getTripleABI (const Triple & TT) static
Definition at line 53 of file LoongArchBaseInfo.cpp.
References ABI_ILP32D, ABI_ILP32F, ABI_ILP32S, ABI_LP64D, ABI_LP64F, ABI_LP64S, llvm::Triple::GNUF32, llvm::Triple::GNUF64, and llvm::Triple::GNUSF.
Referenced by computeTargetABI().