LLVM: llvm::dxbc Namespace Reference
llvm::dxbc Namespace Reference
Namespaces
namespace PSV
Classes
struct AmplificationPSVInfo
struct BitcodeHeader
struct ContainerVersion
struct DomainPSVInfo
struct GeometryPSVInfo
struct Hash
struct Header
struct HullPSVInfo
struct MeshPSVInfo
struct PartHeader
Use this type to describe the size and type of a DXIL container part.
union PipelinePSVInfo
struct PixelPSVInfo
struct ProgramHeader
struct ProgramSignatureElement
struct ProgramSignatureHeader
struct ShaderHash
struct VertexPSVInfo
Enumerations
enum class HashFlags : uint32_t { None = 0 , IncludesSource = 1 }
enum class PartType { Unknown = 0 }
enum class FeatureFlags : uint64_t
enum class SigMinPrecision : uint32_t
enum class D3DSystemValue : uint32_t
enum class SigComponentType : uint32_t
Functions
Triple::EnvironmentType getShaderStage (uint32_t Kind)
PartType parsePartType (StringRef S)
ArrayRef< EnumEntry< SigMinPrecision > > getSigMinPrecisions ()
ArrayRef< EnumEntry< D3DSystemValue > > getD3DSystemValues ()
ArrayRef< EnumEntry< SigComponentType > > getSigComponentTypes ()
Enumeration Type Documentation
D3DSystemValue
enum class llvm::dxbc::D3DSystemValue : uint32_t strong
Definition at line 457 of file DXContainer.h.
FeatureFlags
enum class llvm::dxbc::FeatureFlags : uint64_t strong
Definition at line 149 of file DXContainer.h.
HashFlags
enum class llvm::dxbc::HashFlags : uint32_t strong
Enumerator
None
IncludesSource
Definition at line 51 of file DXContainer.h.
PartType
enum class llvm::dxbc::PartType strong
Enumerator
Unknown
Definition at line 143 of file DXContainer.h.
SigComponentType
enum class llvm::dxbc::SigComponentType : uint32_t strong
Definition at line 464 of file DXContainer.h.
SigMinPrecision
enum class llvm::dxbc::SigMinPrecision : uint32_t strong
Definition at line 450 of file DXContainer.h.
Function Documentation
getD3DSystemValues()
ArrayRef< EnumEntry< D3DSystemValue > > llvm::dxbc::getD3DSystemValues ()
Definition at line 49 of file DXContainer.cpp.
References llvm::ArrayRef(), and D3DSystemValueNames.
getShaderStage()
Triple::EnvironmentType llvm::dxbc::getShaderStage (uint32_t Kind) inline
Definition at line 41 of file DXContainer.h.
References llvm::Triple::Amplification, assert(), and llvm::Triple::Pixel.
Referenced by llvm::DXContainerYAML::PSVInfo::mapInfoForVersion(), and llvm::object::DirectX::PSVRuntimeInfo::parse().
getSigComponentTypes()
ArrayRef< EnumEntry< SigComponentType > > llvm::dxbc::getSigComponentTypes ()
Definition at line 59 of file DXContainer.cpp.
References llvm::ArrayRef(), and SigComponentTypes.
getSigMinPrecisions()
ArrayRef< EnumEntry< SigMinPrecision > > llvm::dxbc::getSigMinPrecisions ()
Definition at line 39 of file DXContainer.cpp.
References llvm::ArrayRef(), and SigMinPrecisionNames.
parsePartType()
dxbc::PartType llvm::dxbc::parsePartType (StringRef S)
Definition at line 21 of file DXContainer.cpp.
References llvm::StringSwitch< T, R >::Default().