LLVM: llvm::DomTreeBuilder Namespace Reference
llvm::DomTreeBuilder Namespace Reference
Classes
struct SemiNCAInfo
Typedefs
using MBBDomTree = DomTreeBase<MachineBasicBlock>
using MBBUpdates = ArrayRef<llvm::cfg::Update<MachineBasicBlock *>>
using MBBDomTreeGraphDiff = GraphDiff<MachineBasicBlock *, false>
using MBBPostDomTree = PostDomTreeBase<MachineBasicBlock>
using MBBPostDomTreeGraphDiff = GraphDiff<MachineBasicBlock *, true>
using BBDomTree = DomTreeBase<BasicBlock>
using BBPostDomTree = PostDomTreeBase<BasicBlock>
using BBUpdates = ArrayRef<llvm::cfg::Update<BasicBlock *>>
using BBDomTreeGraphDiff = GraphDiff<BasicBlock *, false>
using BBPostDomTreeGraphDiff = GraphDiff<BasicBlock *, true>
Functions
template void Calculate< MBBDomTree > (MBBDomTree &DT)
template void CalculateWithUpdates< MBBDomTree > (MBBDomTree &DT, MBBUpdates U)
template void InsertEdge< MBBDomTree > (MBBDomTree &DT, MachineBasicBlock *From, MachineBasicBlock *To)
template void DeleteEdge< MBBDomTree > (MBBDomTree &DT, MachineBasicBlock *From, MachineBasicBlock *To)
template void ApplyUpdates< MBBDomTree > (MBBDomTree &DT, MBBDomTreeGraphDiff &, MBBDomTreeGraphDiff *)
template bool Verify< MBBDomTree > (const MBBDomTree &DT, MBBDomTree::VerificationLevel VL)
template void Calculate< MBBPostDomTree > (MBBPostDomTree &DT)
template void InsertEdge< MBBPostDomTree > (MBBPostDomTree &DT, MachineBasicBlock *From, MachineBasicBlock *To)
template void DeleteEdge< MBBPostDomTree > (MBBPostDomTree &DT, MachineBasicBlock *From, MachineBasicBlock *To)
template void ApplyUpdates< MBBPostDomTree > (MBBPostDomTree &DT, MBBPostDomTreeGraphDiff &, MBBPostDomTreeGraphDiff *)
template bool Verify< MBBPostDomTree > (const MBBPostDomTree &DT, MBBPostDomTree::VerificationLevel VL)
template void Calculate< BBDomTree > (BBDomTree &DT)
template void CalculateWithUpdates< BBDomTree > (BBDomTree &DT, BBUpdates U)
template void Calculate< BBPostDomTree > (BBPostDomTree &DT)
template void InsertEdge< BBDomTree > (BBDomTree &DT, BasicBlock *From, BasicBlock *To)
template void InsertEdge< BBPostDomTree > (BBPostDomTree &DT, BasicBlock *From, BasicBlock *To)
template void DeleteEdge< BBDomTree > (BBDomTree &DT, BasicBlock *From, BasicBlock *To)
template void DeleteEdge< BBPostDomTree > (BBPostDomTree &DT, BasicBlock *From, BasicBlock *To)
template void ApplyUpdates< BBDomTree > (BBDomTree &DT, BBDomTreeGraphDiff &, BBDomTreeGraphDiff *)
template void ApplyUpdates< BBPostDomTree > (BBPostDomTree &DT, BBPostDomTreeGraphDiff &, BBPostDomTreeGraphDiff *)
template bool Verify< BBDomTree > (const BBDomTree &DT, BBDomTree::VerificationLevel VL)
template bool Verify< BBPostDomTree > (const BBPostDomTree &DT, BBPostDomTree::VerificationLevel VL)
template<typename DomTreeT >
void Calculate (DomTreeT &DT)
template<typename DomTreeT >
void CalculateWithUpdates (DomTreeT &DT, ArrayRef< typename DomTreeT::UpdateType > Updates)
template<typename DomTreeT >
void InsertEdge (DomTreeT &DT, typename DomTreeT::NodePtr From, typename DomTreeT::NodePtr To)
template<typename DomTreeT >
void DeleteEdge (DomTreeT &DT, typename DomTreeT::NodePtr From, typename DomTreeT::NodePtr To)
template<typename DomTreeT >
void ApplyUpdates (DomTreeT &DT, GraphDiff< typename DomTreeT::NodePtr, DomTreeT::IsPostDominator > &PreViewCFG, GraphDiff< typename DomTreeT::NodePtr, DomTreeT::IsPostDominator > *PostViewCFG)
template<typename DomTreeT >
bool Verify (const DomTreeT &DT, typename DomTreeT::VerificationLevel VL)
Typedef Documentation
BBDomTree
using llvm::DomTreeBuilder::BBDomTree = DomTreeBase<BasicBlock>
Definition at line 53 of file Dominators.h.
BBDomTreeGraphDiff
using llvm::DomTreeBuilder::BBDomTreeGraphDiff = GraphDiff<BasicBlock *, false>
Definition at line 58 of file Dominators.h.
BBPostDomTree
using llvm::DomTreeBuilder::BBPostDomTree = PostDomTreeBase<BasicBlock>
Definition at line 54 of file Dominators.h.
BBPostDomTreeGraphDiff
using llvm::DomTreeBuilder::BBPostDomTreeGraphDiff = GraphDiff<BasicBlock *, true>
Definition at line 59 of file Dominators.h.
BBUpdates
using llvm::DomTreeBuilder::BBUpdates = ArrayRef<llvm::cfg::Update<BasicBlock *>>
Definition at line 56 of file Dominators.h.
MBBDomTree
using llvm::DomTreeBuilder::MBBDomTree = DomTreeBase<MachineBasicBlock>
Definition at line 47 of file MachineDominators.h.
MBBDomTreeGraphDiff
using llvm::DomTreeBuilder::MBBDomTreeGraphDiff = GraphDiff<MachineBasicBlock *, false>
Definition at line 49 of file MachineDominators.h.
MBBPostDomTree
using llvm::DomTreeBuilder::MBBPostDomTree = PostDomTreeBase<MachineBasicBlock>
Definition at line 24 of file MachinePostDominators.h.
MBBPostDomTreeGraphDiff
using llvm::DomTreeBuilder::MBBPostDomTreeGraphDiff = GraphDiff<MachineBasicBlock *, true>
Definition at line 25 of file MachinePostDominators.h.
MBBUpdates
using llvm::DomTreeBuilder::MBBUpdates = ArrayRef<llvm::cfg::Update<MachineBasicBlock *>>
Definition at line 48 of file MachineDominators.h.
Function Documentation
ApplyUpdates()
template<typename DomTreeT > void llvm::DomTreeBuilder::ApplyUpdates (DomTreeT & DT, GraphDiff< typename DomTreeT::NodePtr, DomTreeT::IsPostDominator > & PreViewCFG, GraphDiff< typename DomTreeT::NodePtr, DomTreeT::IsPostDominator > * PostViewCFG)
Definition at line 1573 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyUpdates().
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::applyUpdates(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::applyUpdates().
ApplyUpdates< BBDomTree >()
template void llvm::DomTreeBuilder::ApplyUpdates< BBDomTree > (BBDomTree & DT, BBDomTreeGraphDiff & , BBDomTreeGraphDiff *) extern
ApplyUpdates< BBPostDomTree >()
template void llvm::DomTreeBuilder::ApplyUpdates< BBPostDomTree > (BBPostDomTree & DT, BBPostDomTreeGraphDiff & , BBPostDomTreeGraphDiff *) extern
ApplyUpdates< MBBDomTree >()
template void llvm::DomTreeBuilder::ApplyUpdates< MBBDomTree > (MBBDomTree & DT, MBBDomTreeGraphDiff & , MBBDomTreeGraphDiff *) extern
ApplyUpdates< MBBPostDomTree >()
template void llvm::DomTreeBuilder::ApplyUpdates< MBBPostDomTree > (MBBPostDomTree & DT, MBBPostDomTreeGraphDiff & , MBBPostDomTreeGraphDiff *) extern
Calculate()
template<typename DomTreeT > void llvm::DomTreeBuilder::Calculate (DomTreeT & DT)
Definition at line 1543 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch().
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::recalculate().
Calculate< BBDomTree >()
template void llvm::DomTreeBuilder::Calculate< BBDomTree > (BBDomTree & DT) extern
Calculate< BBPostDomTree >()
template void llvm::DomTreeBuilder::Calculate< BBPostDomTree > (BBPostDomTree & DT) extern
Calculate< MBBDomTree >()
template void llvm::DomTreeBuilder::Calculate< MBBDomTree > (MBBDomTree & DT) extern
Calculate< MBBPostDomTree >()
template void llvm::DomTreeBuilder::Calculate< MBBPostDomTree > (MBBPostDomTree & DT) extern
CalculateWithUpdates()
template<typename DomTreeT > void llvm::DomTreeBuilder::CalculateWithUpdates (DomTreeT & DT, ArrayRef< typename DomTreeT::UpdateType > Updates)
Definition at line 1548 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch().
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::recalculate().
CalculateWithUpdates< BBDomTree >()
template void llvm::DomTreeBuilder::CalculateWithUpdates< BBDomTree > (BBDomTree & DT, BBUpdates U) extern
CalculateWithUpdates< MBBDomTree >()
template void llvm::DomTreeBuilder::CalculateWithUpdates< MBBDomTree > (MBBDomTree & DT, MBBUpdates U) extern
DeleteEdge()
template<typename DomTreeT > void llvm::DomTreeBuilder::DeleteEdge (DomTreeT & DT, typename DomTreeT::NodePtr From, typename DomTreeT::NodePtr To)
Definition at line 1566 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), From, and std::swap().
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::deleteEdge().
DeleteEdge< BBDomTree >()
template void llvm::DomTreeBuilder::DeleteEdge< BBDomTree > (BBDomTree & DT, BasicBlock * From, BasicBlock * To) extern
DeleteEdge< BBPostDomTree >()
template void llvm::DomTreeBuilder::DeleteEdge< BBPostDomTree > (BBPostDomTree & DT, BasicBlock * From, BasicBlock * To) extern
DeleteEdge< MBBDomTree >()
template void llvm::DomTreeBuilder::DeleteEdge< MBBDomTree > (MBBDomTree & DT, MachineBasicBlock * From, MachineBasicBlock * To) extern
DeleteEdge< MBBPostDomTree >()
template void llvm::DomTreeBuilder::DeleteEdge< MBBPostDomTree > (MBBPostDomTree & DT, MachineBasicBlock * From, MachineBasicBlock * To) extern
InsertEdge()
template<typename DomTreeT > void llvm::DomTreeBuilder::InsertEdge (DomTreeT & DT, typename DomTreeT::NodePtr From, typename DomTreeT::NodePtr To)
Definition at line 1559 of file GenericDomTreeConstruction.h.
References From, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertEdge(), and std::swap().
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::insertEdge().
InsertEdge< BBDomTree >()
template void llvm::DomTreeBuilder::InsertEdge< BBDomTree > (BBDomTree & DT, BasicBlock * From, BasicBlock * To) extern
InsertEdge< BBPostDomTree >()
template void llvm::DomTreeBuilder::InsertEdge< BBPostDomTree > (BBPostDomTree & DT, BasicBlock * From, BasicBlock * To) extern
InsertEdge< MBBDomTree >()
template void llvm::DomTreeBuilder::InsertEdge< MBBDomTree > (MBBDomTree & DT, MachineBasicBlock * From, MachineBasicBlock * To) extern
InsertEdge< MBBPostDomTree >()
template void llvm::DomTreeBuilder::InsertEdge< MBBPostDomTree > (MBBPostDomTree & DT, MachineBasicBlock * From, MachineBasicBlock * To) extern
Verify()
template<typename DomTreeT > bool llvm::DomTreeBuilder::Verify (const DomTreeT & DT, typename DomTreeT::VerificationLevel VL)
Definition at line 1582 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsSameAsFreshTree(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyLevels(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyReachability(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyRoots(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty().
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::verify().
Verify< BBDomTree >()
template bool llvm::DomTreeBuilder::Verify< BBDomTree > (const BBDomTree & DT, BBDomTree::VerificationLevel VL) extern
Verify< BBPostDomTree >()
template bool llvm::DomTreeBuilder::Verify< BBPostDomTree > (const BBPostDomTree & DT, BBPostDomTree::VerificationLevel VL) extern
Verify< MBBDomTree >()
template bool llvm::DomTreeBuilder::Verify< MBBDomTree > (const MBBDomTree & DT, MBBDomTree::VerificationLevel VL) extern
Verify< MBBPostDomTree >()
template bool llvm::DomTreeBuilder::Verify< MBBPostDomTree > (const MBBPostDomTree & DT, MBBPostDomTree::VerificationLevel VL) extern