LLVM: llvm::object Namespace Reference
llvm::object Namespace Reference
Namespaces
namespace detail
namespace DirectX
Classes
class AbstractArchiveMemberHeader
class Archive
class ArchiveMemberHeader
class BaseRelocRef
class BasicSymbolRef
This is a value type class that represents a single symbol in the list of symbols in the object file.
struct BBAddrMap
class BigArchive
class BigArchiveMemberHeader
struct BigArMemHdrType
class Binary
class BinaryError
Base class for all errors indicating malformed binary files.
class BindRebaseSegInfo
class BuildIDFetcher
BuildIDFetcher searches local cache directories for debug info.
struct CFileLanguageIdAndTypeIdType
struct ChainedFixupsSegment
struct ChainedFixupTarget
ChainedFixupTarget holds all the information about an external symbol necessary to bind this binary to that symbol.
struct chpe_code_range_entry
struct chpe_metadata
struct chpe_range_entry
struct chpe_redirection_entry
struct coff_aux_bf_and_ef_symbol
struct coff_aux_clr_token
struct coff_aux_function_definition
struct coff_aux_section_definition
struct coff_aux_weak_external
struct coff_base_reloc_block_entry
struct coff_base_reloc_block_header
struct coff_bigobj_file_header
struct coff_file_header
struct coff_import_directory_table_entry
struct coff_import_header
struct coff_load_config_code_integrity
struct coff_load_configuration32
32-bit load config (IMAGE_LOAD_CONFIG_DIRECTORY32)
struct coff_load_configuration64
64-bit load config (IMAGE_LOAD_CONFIG_DIRECTORY64)
struct coff_relocation
struct coff_resource_data_entry
struct coff_resource_dir_entry
struct coff_resource_dir_table
struct coff_runtime_function_x64
struct coff_section
struct coff_symbol
struct coff_symbol_generic
struct coff_tls_directory
class COFFImportFile
struct COFFModuleDefinition
class COFFObjectFile
struct COFFShortExport
class COFFSymbolRef
class CommonArchiveMemberHeader
class content_iterator
struct data_directory
union DataRefImpl
struct DataRegion
struct debug_directory
struct debug_h_header
class Decompressor
Decompressor helps to handle decompression of compressed sections.
struct delay_import_directory_table_entry
class DelayImportDirectoryEntryRef
class DiceRef
DiceRef - This is a value type class that represents a single data in code entry in the table in a Mach-O object file.
struct dos_header
The DOS compatible header at the front of all PE/COFF executables.
class DXContainer
struct Elf_CGProfile_Impl
struct Elf_Chdr_Impl
struct Elf_Chdr_Impl< ELFType< Endianness, false > >
struct Elf_Chdr_Impl< ELFType< Endianness, true > >
struct Elf_Crel_Impl
struct Elf_Dyn_Base
Elf_Dyn_Base: This structure matches the form of entries in the dynamic table section (.dynamic) look like.
struct Elf_Dyn_Base< ELFType< Endianness, false > >
struct Elf_Dyn_Base< ELFType< Endianness, true > >
struct Elf_Dyn_Impl
Elf_Dyn_Impl: This inherits from Elf_Dyn_Base, adding getters.
struct Elf_Ehdr_Impl
struct Elf_GnuHash_Impl
struct Elf_Hash_Impl
struct Elf_Mips_ABIFlags
struct Elf_Mips_Options
struct Elf_Mips_RegInfo
struct Elf_Mips_RegInfo< ELFType< Endianness, false > >
struct Elf_Mips_RegInfo< ELFType< Endianness, true > >
struct Elf_Nhdr_Impl
Note header.
class Elf_Note_Impl
An ELF note.
class Elf_Note_Iterator_Impl
struct Elf_Phdr_Impl
struct Elf_Phdr_Impl< ELFType< Endianness, false > >
struct Elf_Phdr_Impl< ELFType< Endianness, true > >
struct Elf_Rel_Impl
struct Elf_Rel_Impl< ELFType< Endianness, false >, false >
struct Elf_Rel_Impl< ELFType< Endianness, false >, true >
struct Elf_Rel_Impl< ELFType< Endianness, true >, false >
struct Elf_Rel_Impl< ELFType< Endianness, true >, true >
class elf_relocation_iterator
class elf_section_iterator
struct Elf_Shdr_Base
struct Elf_Shdr_Base< ELFType< Endianness, false > >
struct Elf_Shdr_Base< ELFType< Endianness, true > >
struct Elf_Shdr_Impl
struct Elf_Sym_Base
struct Elf_Sym_Base< ELFType< Endianness, false > >
struct Elf_Sym_Base< ELFType< Endianness, true > >
struct Elf_Sym_Impl
class elf_symbol_iterator
struct Elf_Verdaux_Impl
Elf_Verdaux: This is the structure of auxiliary data in the SHT_GNU_verdef section (.gnu.version_d).
struct Elf_Verdef_Impl
Elf_Verdef: This is the structure of entries in the SHT_GNU_verdef section (.gnu.version_d).
struct Elf_Vernaux_Impl
Elf_Vernaux: This is the structure of auxiliary data in SHT_GNU_verneed section (.gnu.version_r).
struct Elf_Verneed_Impl
Elf_Verneed: This is the structure of entries in the SHT_GNU_verneed section (.gnu.version_r).
struct Elf_Versym_Impl
Elf_Versym: This is the structure of entries in the SHT_GNU_versym section (.gnu.version).
class ELFFile
class ELFObjectFile
class ELFObjectFileBase
struct ELFPltEntry
class ELFRelocationRef
class ELFSectionRef
class ELFSymbolRef
struct ELFType
class EmptyResError
class ENDRecord
class ESDRecord
struct ExceptionSectionEntry
union export_address_table_entry
struct export_directory_table_entry
class ExportDirectoryEntryRef
class ExportEntry
ExportEntry encapsulates the current-state-of-the-walk used when doing a non-recursive walk of the trie data structure.
struct FpoData
class GenericBinaryError
Generic binary error.
class GOFFObjectFile
class GOFFSymbolRef
class HDRRecord
struct import_lookup_table_entry
class ImportDirectoryEntryRef
class ImportedSymbolRef
class IRObjectFile
struct IRSymtabFile
The contents of a bitcode file and its irsymtab.
class Lexer
struct LoaderSectionHeader32
struct LoaderSectionHeader64
struct LoaderSectionRelocationEntry32
struct LoaderSectionRelocationEntry64
struct LoaderSectionSymbolEntry32
struct LoaderSectionSymbolEntry64
class MachOAbstractFixupEntry
MachOAbstractFixupEntry is an abstract class representing a fixup in a MH_DYLDLINK file.
class MachOBindEntry
MachOBindEntry encapsulates the current state in the decompression of binding opcodes.
class MachOChainedFixupEntry
class MachOObjectFile
class MachORebaseEntry
MachORebaseEntry encapsulates the current state in the decompression of rebasing opcodes.
class MachOUniversalBinary
class MinidumpFile
A class providing access to the contents of a minidump file.
class ObjectFile
This class is the base class for all object file types.
class OffloadBinary
A simple binary serialization of an offloading file.
class OffloadFile
A class to contain the binary information for a single OffloadBinary that owns its memory.
class OwningBinary
class Parser
struct pe32_header
The 32-bit PE header that follows the COFF header.
struct pe32plus_header
The 64-bit PE header that follows the COFF header.
struct PGOAnalysisMap
A feature extension of BBAddrMap that holds information relevant to PGO.
class Record
Represents a GOFF physical record.
class RelocationRef
This is a value type class that represents a single relocation in the list of relocations in the object file.
class ResourceEntryRef
class ResourceSectionRef
struct SectionedAddress
class SectionFilter
Creates an iterator range of SectionFilterIterators for a given Object and predicate.
class SectionFilterIterator
A filtered iterator for SectionRefs that skips sections based on some given predicate.
class SectionRef
This is a value type class that represents a single section in the list of sections in the object file.
class SectionStrippedError
class Slice
struct StringTableOffset
class symbol_iterator
class SymbolicFile
class SymbolRef
This is a value type class that represents a single symbol in the list of symbols in the object file.
struct SymEntry
class TapiFile
class TapiUniversal
class TBVectorExt
struct Token
class TXTRecord
struct UnixArMemHdrType
struct VerdAux
struct VerDef
struct VernAux
struct VerNeed
struct VersionEntry
struct ViewArray
class WasmObjectFile
struct WasmSection
class WasmSectionOrderChecker
struct WasmSegment
class WasmSymbol
class WindowsResource
class WindowsResourceCOFFWriter
class WindowsResourceParser
struct WinResHeaderPrefix
struct WinResHeaderSuffix
struct WinResIDs
class xcoff_symbol_iterator
struct XCOFFAuxiliaryHeader
struct XCOFFAuxiliaryHeader32
struct XCOFFAuxiliaryHeader64
struct XCOFFBlockAuxEnt32
struct XCOFFBlockAuxEnt64
struct XCOFFCsectAuxEnt32
struct XCOFFCsectAuxEnt64
class XCOFFCsectAuxRef
struct XCOFFExceptionAuxEnt
struct XCOFFFileAuxEnt
struct XCOFFFileHeader32
struct XCOFFFileHeader64
struct XCOFFFunctionAuxEnt32
struct XCOFFFunctionAuxEnt64
class XCOFFObjectFile
struct XCOFFRelocation
struct XCOFFRelocation32
struct XCOFFRelocation64
struct XCOFFSectAuxEntForDWARF32
struct XCOFFSectAuxEntForDWARF64
struct XCOFFSectAuxEntForStat
struct XCOFFSectionHeader
struct XCOFFSectionHeader32
struct XCOFFSectionHeader64
struct XCOFFStringTable
struct XCOFFSymbolEntry32
struct XCOFFSymbolEntry64
class XCOFFSymbolRef
class XCOFFTracebackTable
This class provides methods to extract traceback table data from a buffer.
Typedefs
typedef SmallVector< uint8_t, 10 > BuildID
A build ID in binary form.
typedef ArrayRef< uint8_t > BuildIDRef
A reference to a BuildID in binary form.
using import_directory_iterator = content_iterator<ImportDirectoryEntryRef>
using delay_import_directory_iterator
using export_directory_iterator = content_iterator<ExportDirectoryEntryRef>
using imported_symbol_iterator = content_iterator<ImportedSymbolRef>
using base_reloc_iterator = content_iterator<BaseRelocRef>
using import_lookup_table_entry32
using import_lookup_table_entry64
using export_name_pointer_table_entry = support::ulittle32_t
using export_ordinal_table_entry = support::ulittle16_t
using coff_symbol16 = coff_symbol<support::ulittle16_t>
using coff_symbol32 = coff_symbol<support::ulittle32_t>
using coff_tls_directory32 = coff_tls_directory<support::little32_t>
using coff_tls_directory64 = coff_tls_directory<support::little64_t>
using ELF32LEFile = ELFFile<ELF32LE>
using ELF64LEFile = ELFFile<ELF64LE>
using ELF32BEFile = ELFFile<ELF32BE>
using ELF64BEFile = ELFFile<ELF64BE>
using ELF32LEObjectFile = ELFObjectFile<ELF32LE>
using ELF64LEObjectFile = ELFObjectFile<ELF64LE>
using ELF32BEObjectFile = ELFObjectFile<ELF32BE>
using ELF64BEObjectFile = ELFObjectFile<ELF64BE>
using ELF32LE = ELFType<llvm::endianness::little, false>
using ELF32BE = ELFType<llvm::endianness::big, false>
using ELF64LE = ELFType<llvm::endianness::little, true>
using ELF64BE = ELFType<llvm::endianness::big, true>
using dice_iterator = content_iterator<DiceRef>
using export_iterator = content_iterator<ExportEntry>
using rebase_iterator = content_iterator<MachORebaseEntry>
using bind_iterator = content_iterator<MachOBindEntry>
using fixup_iterator = content_iterator<MachOChainedFixupEntry>
using section_iterator = content_iterator<SectionRef>
typedef std::function< bool(const SectionRef &)> SectionFilterPredicate
using relocation_iterator = content_iterator<RelocationRef>
using SupportsRelocation = bool (*)(uint64_t)
using RelocationResolver
using basic_symbol_iterator = content_iterator<BasicSymbolRef>
typedef ExceptionSectionEntry< support::ubig32_t > ExceptionSectionEntry32
typedef ExceptionSectionEntry< support::ubig64_t > ExceptionSectionEntry64
Enumerations
enum class frame_type : uint16_t { Fpo = 0 , Trap = 1 , Tss = 2 , NonFpo = 3 }
enum chpe_range_type { Arm64 = 0 , Arm64EC = 1 , Amd64 = 2 }
enum PPCInstrMasks : uint64_t {
PADDI_R12_NO_DISP = 0x0610000039800000 , ADDIS_R12_TO_R2_NO_DISP = 0x3D820000 , ADDI_R12_TO_R2_NO_DISP = 0x39820000 , ADDI_R12_TO_R12_NO_DISP = 0x398C0000 ,
PLD_R12_NO_DISP = 0x04100000E5800000 , MTCTR_R12 = 0x7D8903A6 , BCTR = 0x4E800420
}
enum class object_error {
arch_not_found = 1 , invalid_file_type , parse_failed , unexpected_eof ,
string_table_non_null_end , invalid_section_index , bitcode_section_not_found , invalid_symbol_index ,
section_stripped
}
enum class FatHeaderType { FatHeader , Fat64Header }
enum OffloadKind : uint16_t {
OFK_None = 0 , OFK_OpenMP , OFK_Cuda , OFK_HIP ,
OFK_LAST
}
The producer of the associated offloading image.
enum ImageKind : uint16_t {
IMG_None = 0 , IMG_Object , IMG_Bitcode , IMG_Cubin ,
IMG_Fatbinary , IMG_PTX , IMG_LAST
}
The type of contents the offloading image contains.
enum Kind {
Unknown , Eof , Identifier , Comma ,
Equal , EqualEqual , KwBase , KwConstant ,
KwData , KwExports , KwExportAs , KwHeapsize ,
KwLibrary , KwName , KwNoname , KwPrivate ,
KwStacksize , KwVersion
}
Functions
Expected< std::unique_ptr< Binary > > createBinary (MemoryBufferRef Source, LLVMContext *Context=nullptr, bool InitContent=true)
Create a Binary from Source, autodetecting the file type.
Expected< OwningBinary< Binary > > createBinary (StringRef Path, LLVMContext *Context=nullptr, bool InitContent=true)
BuildID parseBuildID (StringRef Str)
Parses a build ID from a hex string.
BuildIDRef getBuildID (const ObjectFile *Obj)
Returns the build ID, if any, contained in the given object file.
Error writeImportLibrary (StringRef ImportName, StringRef Path, ArrayRef< COFFShortExport > Exports, COFF::MachineTypes Machine, bool MinGW, ArrayRef< COFFShortExport > NativeExports=std::nullopt)
Writes a COFF import library containing entries described by the Exports array.
Expected< COFFModuleDefinition > parseCOFFModuleDefinition (MemoryBufferRef MB, COFF::MachineTypes Machine, bool MingwDef=false, bool AddUnderscores=true)
StringRef getELFRelocationTypeName (uint32_t Machine, uint32_t Type)
uint32_t getELFRelativeRelocationType (uint32_t Machine)
StringRef getELFSectionTypeName (uint32_t Machine, uint32_t Type)
std::pair< unsigned char, unsigned char > getElfArchType (StringRef Object)
template<class ELFT >
std::string getSecIndexForError (const ELFFile< ELFT > &Obj, const typename ELFT::Shdr &Sec)
template<class ELFT >
static std::string describe (const ELFFile< ELFT > &Obj, const typename ELFT::Shdr &Sec)
template<class ELFT >
std::string getPhdrIndexForError (const ELFFile< ELFT > &Obj, const typename ELFT::Phdr &Phdr)
static Error defaultWarningHandler (const Twine &Msg)
template<class ELFT >
bool checkSectionOffsets (const typename ELFT::Phdr &Phdr, const typename ELFT::Shdr &Sec)
template<class ELFT >
bool checkSectionVMA (const typename ELFT::Phdr &Phdr, const typename ELFT::Shdr &Sec)
template<class ELFT >
bool isSectionInSegment (const typename ELFT::Phdr &Phdr, const typename ELFT::Shdr &Sec)
template<bool Is64>
Error decodeCrel (ArrayRef< uint8_t > Content, function_ref< void(uint64_t, bool)> HdrHandler, function_ref< void(Elf_Crel_Impl< Is64 >)> EntryHandler)
template<class ELFT >
Expected< const typename ELFT::Shdr * > getSection (typename ELFT::ShdrRange Sections, uint32_t Index)
template<class ELFT >
Expected< uint32_t > getExtendedSymbolTableIndex (const typename ELFT::Sym &Sym, unsigned SymIndex, DataRegion< typename ELFT::Word > ShndxTable)
template<class ELFT >
static Expected< uint64_t > getDynSymtabSizeFromGnuHash (const typename ELFT::GnuHash &Table, const void *BufEnd)
This function finds the number of dynamic symbols using a GNU hash table.
uint32_t hashSysV (StringRef SymbolName)
This function returns the hash value for a symbol in the .dynsym section Name of the API remains consistent as specified in the libelf REF : http://www.sco.com/developers/gabi/latest/ch5.dynamic.html#hash.
uint32_t hashGnu (StringRef Name)
This function returns the hash value for a symbol in the .dynsym section for the GNU hash table.
bool operator< (const ELFSymbolRef &A, const ELFSymbolRef &B)
const std::error_category & object_category ()
std::error_code make_error_code (object_error e)
Error isNotObjectErrorInvalidFileType (llvm::Error Err)
isNotObjectErrorInvalidFileType() is used when looping through the children of an archive after calling getAsBinary() on the child and it returns an llvm::Error.
Error createError (const Twine &Err)
Expected< IRSymtabFile > readIRSymtab (MemoryBufferRef MBRef)
Reads a bitcode file, creating its irsymtab if necessary.
Error writeUniversalBinary (ArrayRef< Slice > Slices, StringRef OutputFileName, FatHeaderType FatHeader=FatHeaderType::FatHeader)
Error writeUniversalBinaryToStream (ArrayRef< Slice > Slices, raw_ostream &Out, FatHeaderType FatHeader=FatHeaderType::FatHeader)
bool operator< (const SectionedAddress &LHS, const SectionedAddress &RHS)
bool operator== (const SectionedAddress &LHS, const SectionedAddress &RHS)
raw_ostream & operator<< (raw_ostream &OS, const SectionedAddress &Addr)
Error extractOffloadBinaries (MemoryBufferRef Buffer, SmallVectorImpl< OffloadFile > &Binaries)
Extracts embedded device offloading code from a memory Buffer to a list of Binaries.
ImageKind getImageKind (StringRef Name)
Convert a string Name to an image kind.
StringRef getImageKindName (ImageKind Name)
Convert an image kind to its string representation.
OffloadKind getOffloadKind (StringRef Name)
Convert a string Name to an offload kind.
StringRef getOffloadKindName (OffloadKind Name)
Convert an offload kind to its string representation.
bool areTargetsCompatible (const OffloadFile::TargetID &LHS, const OffloadFile::TargetID &RHS)
If the target is AMD we check the target IDs for mutual compatibility.
std::pair< SupportsRelocation, RelocationResolver > getRelocationResolver (const ObjectFile &Obj)
uint64_t resolveRelocation (RelocationResolver Resolver, const RelocationRef &R, uint64_t S, uint64_t LocData)
template<typename OStream >
OStream & operator<< (OStream &OS, const DataRefImpl &D)
bool operator== (const DataRefImpl &a, const DataRefImpl &b)
bool operator!= (const DataRefImpl &a, const DataRefImpl &b)
bool operator< (const DataRefImpl &a, const DataRefImpl &b)
int compareAddress (const SymEntry *A, const SymEntry *B)
std::vector< std::pair< SymbolRef, uint64_t > > computeSymbolSizes (const ObjectFile &O)
Expected< std::unique_ptr< MemoryBuffer > > writeWindowsResourceCOFF (llvm::COFF::MachineTypes MachineType, const WindowsResourceParser &Parser, uint32_t TimeDateStamp)
void printResourceTypeName (uint16_t TypeID, raw_ostream &OS)
bool doesXCOFFTracebackTableBegin (ArrayRef< uint8_t > Bytes)
static StringRef applyNameType (ImportNameType Type, StringRef name)
static uint16_t getImgRelRelocation (MachineTypes Machine)
template<class T >
static void append (std::vector< uint8_t > &B, const T &Data)
static void writeStringTable (std::vector< uint8_t > &B, ArrayRef< const std::string_view > Strings)
static ImportNameType getNameType (StringRef Sym, StringRef ExtName, MachineTypes Machine, bool MinGW)
static Expected< std::string > replace (StringRef S, StringRef From, StringRef To)
static bool isDecorated (StringRef Sym, bool MingwDef)
static int64_t getELFAddend (RelocationRef R)
static bool supportsX86_64 (uint64_t Type)
static uint64_t resolveX86_64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend)
static bool supportsAArch64 (uint64_t Type)
static uint64_t resolveAArch64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t, int64_t Addend)
static bool supportsBPF (uint64_t Type)
static uint64_t resolveBPF (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t)
static bool supportsMips64 (uint64_t Type)
static uint64_t resolveMips64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t, int64_t Addend)
static bool supportsMSP430 (uint64_t Type)
static uint64_t resolveMSP430 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t, int64_t Addend)
static bool supportsPPC64 (uint64_t Type)
static uint64_t resolvePPC64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t, int64_t Addend)
static bool supportsSystemZ (uint64_t Type)
static uint64_t resolveSystemZ (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t, int64_t Addend)
static bool supportsSparc64 (uint64_t Type)
static uint64_t resolveSparc64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t, int64_t Addend)
static bool isAMDGPU (const ObjectFile &Obj)
Returns true if Obj is an AMDGPU code object based solely on the value of e_machine.
static bool supportsAmdgpu (uint64_t Type)
static uint64_t resolveAmdgpu (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t, int64_t Addend)
static bool supportsX86 (uint64_t Type)
static uint64_t resolveX86 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t)
static bool supportsPPC32 (uint64_t Type)
static uint64_t resolvePPC32 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t, int64_t Addend)
static bool supportsARM (uint64_t Type)
static uint64_t resolveARM (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend)
static bool supportsAVR (uint64_t Type)
static uint64_t resolveAVR (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t, int64_t Addend)
static bool supportsLanai (uint64_t Type)
static uint64_t resolveLanai (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t, int64_t Addend)
static bool supportsMips32 (uint64_t Type)
static uint64_t resolveMips32 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t)
static bool supportsSparc32 (uint64_t Type)
static uint64_t resolveSparc32 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend)
static bool supportsHexagon (uint64_t Type)
static uint64_t resolveHexagon (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t, int64_t Addend)
static bool supportsRISCV (uint64_t Type)
static uint64_t resolveRISCV (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend)
static bool supportsCSKY (uint64_t Type)
static uint64_t resolveCSKY (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend)
static bool supportsLoongArch (uint64_t Type)
static uint64_t resolveLoongArch (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend)
static bool supportsCOFFX86 (uint64_t Type)
static uint64_t resolveCOFFX86 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t)
static bool supportsCOFFX86_64 (uint64_t Type)
static uint64_t resolveCOFFX86_64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t)
static bool supportsCOFFARM (uint64_t Type)
static uint64_t resolveCOFFARM (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t)
static bool supportsCOFFARM64 (uint64_t Type)
static uint64_t resolveCOFFARM64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t)
static bool supportsMachOX86_64 (uint64_t Type)
static uint64_t resolveMachOX86_64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t)
static bool supportsWasm32 (uint64_t Type)
static bool supportsWasm64 (uint64_t Type)
static uint64_t resolveWasm32 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t)
static uint64_t resolveWasm64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend)
static Error readStringOrId (BinaryStreamReader &Reader, uint16_t &ID, ArrayRef< UTF16 > &Str, bool &IsString)
static bool convertUTF16LEToUTF8String (ArrayRef< UTF16 > Src, std::string &Out)
static std::string makeDuplicateResourceError (const ResourceEntryRef &Entry, StringRef File1, StringRef File2)
static void printStringOrID (const WindowsResourceParser::StringOrID &S, raw_string_ostream &OS, bool IsType, bool IsID)
static std::string makeDuplicateResourceError (const std::vector< WindowsResourceParser::StringOrID > &Context, StringRef File1, StringRef File2)
static void coffnamecpy (char(&Dest)[COFF::NameSize], StringRef Src)
template<typename T >
static Expected< const T * > getObject (MemoryBufferRef M, const void *Ptr, const uint64_t Size=sizeof(T))
static uintptr_t getWithOffset (uintptr_t Base, ptrdiff_t Offset)
template<typename T >
static const T * viewAs (uintptr_t in)
static StringRef generateXCOFFFixedNameStringRef (const char *Name)
template<typename T >
Expected< StringRef > getLoaderSecSymNameInStrTbl (const T *LoaderSecHeader, uint64_t Offset)
template llvm::Expected< llvm::ArrayRef< llvm::object::XCOFFRelocation64 > > llvm::object::XCOFFObjectFile::relocations< llvm::object::XCOFFSectionHeader64, llvm::object::XCOFFRelocation64 > (llvm::object::XCOFFSectionHeader64 const &) const
template llvm::Expected< llvm::ArrayRef< llvm::object::XCOFFRelocation32 > > llvm::object::XCOFFObjectFile::relocations< llvm::object::XCOFFSectionHeader32, llvm::object::XCOFFRelocation32 > (llvm::object::XCOFFSectionHeader32 const &) const
Variables
const char ArchiveMagic [] = "!<arch>\n"
const char ThinArchiveMagic [] = "!<thin>\n"
const char BigArchiveMagic [] = "<bigaf>\n"
constexpr std::string_view ImportDescriptorPrefix = "__IMPORT_DESCRIPTOR_"
constexpr std::string_view NullImportDescriptorSymbolName
constexpr std::string_view NullThunkDataPrefix = "\x7f"
constexpr std::string_view NullThunkDataSuffix = "_NULL_THUNK_DATA"
constexpr int NumElfSymbolTypes = 16
const llvm::EnumEntry< unsigned > ElfSymbolTypes [NumElfSymbolTypes]
const size_t WIN_RES_MAGIC_SIZE = 16
const size_t WIN_RES_NULL_ENTRY_SIZE = 16
const uint32_t WIN_RES_HEADER_ALIGNMENT = 4
const uint32_t WIN_RES_DATA_ALIGNMENT = 4
const uint16_t WIN_RES_PURE_MOVEABLE = 0x0030
const uint32_t MIN_HEADER_SIZE = 7 * sizeof(uint32_t) + 2 * sizeof(uint16_t)
const uint32_t SECTION_ALIGNMENT = sizeof(uint64_t)
static const uint8_t FunctionSym = 0x20
static const uint16_t NoRelMask = 0x0001
static const size_t SymbolAuxTypeOffset = 17
Typedef Documentation
base_reloc_iterator
using llvm::object::base_reloc_iterator = content_iterator<BaseRelocRef>
Definition at line 50 of file COFF.h.
basic_symbol_iterator
using llvm::object::basic_symbol_iterator = content_iterator<BasicSymbolRef>
Definition at line 143 of file SymbolicFile.h.
bind_iterator
using llvm::object::bind_iterator = content_iterator<MachOBindEntry>
Definition at line 261 of file MachO.h.
BuildID
typedef SmallVector<uint8_t, 10> llvm::object::BuildID
A build ID in binary form.
Definition at line 25 of file BuildID.h.
BuildIDRef
typedef ArrayRef<uint8_t> llvm::object::BuildIDRef
A reference to a BuildID in binary form.
Definition at line 28 of file BuildID.h.
coff_symbol16
using llvm::object::coff_symbol16 = coff_symbol<support::ulittle16_t>
Definition at line 265 of file COFF.h.
coff_symbol32
using llvm::object::coff_symbol32 = coff_symbol<support::ulittle32_t>
Definition at line 266 of file COFF.h.
coff_tls_directory32
using llvm::object::coff_tls_directory32 = coff_tls_directory<support::little32_t>
Definition at line 597 of file COFF.h.
coff_tls_directory64
using llvm::object::coff_tls_directory64 = coff_tls_directory<support::little64_t>
Definition at line 598 of file COFF.h.
delay_import_directory_iterator
using llvm::object::delay_import_directory_iterator
Initial value:
    content_iterator<DelayImportDirectoryEntryRef>
Definition at line 46 of file COFF.h.
dice_iterator
using llvm::object::dice_iterator = content_iterator<DiceRef>
Definition at line 64 of file MachO.h.
ELF32BE
using llvm::object::ELF32BE = ELFType<llvm::endianness::big, false>
Definition at line 98 of file ELFTypes.h.
ELF32BEFile
using llvm::object::ELF32BEFile = ELFFile<ELF32BE>
Definition at line 528 of file ELF.h.
ELF32BEObjectFile
using llvm::object::ELF32BEObjectFile = ELFObjectFile<ELF32BE>
Definition at line 516 of file ELFObjectFile.h.
ELF32LE
using llvm::object::ELF32LE = ELFType<llvm::endianness::little, false>
Definition at line 97 of file ELFTypes.h.
ELF32LEFile
using llvm::object::ELF32LEFile = ELFFile<ELF32LE>
Definition at line 526 of file ELF.h.
ELF32LEObjectFile
using llvm::object::ELF32LEObjectFile = ELFObjectFile<ELF32LE>
Definition at line 514 of file ELFObjectFile.h.
ELF64BE
using llvm::object::ELF64BE = ELFType<llvm::endianness::big, true>
Definition at line 100 of file ELFTypes.h.
ELF64BEFile
using llvm::object::ELF64BEFile = ELFFile<ELF64BE>
Definition at line 529 of file ELF.h.
ELF64BEObjectFile
using llvm::object::ELF64BEObjectFile = ELFObjectFile<ELF64BE>
Definition at line 517 of file ELFObjectFile.h.
ELF64LE
using llvm::object::ELF64LE = ELFType<llvm::endianness::little, true>
Definition at line 99 of file ELFTypes.h.
ELF64LEFile
using llvm::object::ELF64LEFile = ELFFile<ELF64LE>
Definition at line 527 of file ELF.h.
ELF64LEObjectFile
using llvm::object::ELF64LEObjectFile = ELFObjectFile<ELF64LE>
Definition at line 515 of file ELFObjectFile.h.
ExceptionSectionEntry32
typedef ExceptionSectionEntry<support::ubig32_t> llvm::object::ExceptionSectionEntry32
Definition at line 316 of file XCOFFObjectFile.h.
ExceptionSectionEntry64
typedef ExceptionSectionEntry<support::ubig64_t> llvm::object::ExceptionSectionEntry64
Definition at line 317 of file XCOFFObjectFile.h.
export_directory_iterator
using llvm::object::export_directory_iterator = content_iterator<ExportDirectoryEntryRef>
Definition at line 48 of file COFF.h.
export_iterator
using llvm::object::export_iterator = content_iterator<ExportEntry>
Definition at line 126 of file MachO.h.
export_name_pointer_table_entry
using llvm::object::export_name_pointer_table_entry = support::ulittle32_t
Definition at line 241 of file COFF.h.
export_ordinal_table_entry
using llvm::object::export_ordinal_table_entry = support::ulittle16_t
Definition at line 242 of file COFF.h.
fixup_iterator
using llvm::object::fixup_iterator = content_iterator<MachOChainedFixupEntry>
Definition at line 404 of file MachO.h.
import_directory_iterator
using llvm::object::import_directory_iterator = content_iterator<ImportDirectoryEntryRef>
Definition at line 45 of file COFF.h.
import_lookup_table_entry32
using llvm::object::import_lookup_table_entry32
Initial value:
    import_lookup_table_entry<support::little32_t>
Definition at line 205 of file COFF.h.
import_lookup_table_entry64
using llvm::object::import_lookup_table_entry64
Initial value:
    import_lookup_table_entry<support::little64_t>
Definition at line 207 of file COFF.h.
imported_symbol_iterator
using llvm::object::imported_symbol_iterator = content_iterator<ImportedSymbolRef>
Definition at line 49 of file COFF.h.
rebase_iterator
using llvm::object::rebase_iterator = content_iterator<MachORebaseEntry>
Definition at line 203 of file MachO.h.
relocation_iterator
using llvm::object::relocation_iterator = content_iterator<RelocationRef>
Definition at line 77 of file ObjectFile.h.
RelocationResolver
using llvm::object::RelocationResolver
Initial value:
 uint64_t (*)(uint64_t Type, uint64_t Offset,
                                        uint64_t S, uint64_t LocData,
                                        int64_t Addend)
Definition at line 28 of file RelocationResolver.h.
section_iterator
using llvm::object::section_iterator = content_iterator<SectionRef>
Definition at line 47 of file ObjectFile.h.
SectionFilterPredicate
typedef std::function<bool(const SectionRef &)> llvm::object::SectionFilterPredicate
Definition at line 49 of file ObjectFile.h.
SupportsRelocation
using llvm::object::SupportsRelocation = bool (*)(uint64_t)
Definition at line 27 of file RelocationResolver.h.
Enumeration Type Documentation
chpe_range_type
enum llvm::object::chpe_range_type
Enumerator
Arm64
Arm64EC
Amd64
Definition at line 748 of file COFF.h.
FatHeaderType
enum class llvm::object::FatHeaderType strong
Enumerator
FatHeader
Fat64Header
Definition at line 100 of file MachOUniversalWriter.h.
frame_type
enum class llvm::object::frame_type : uint16_t strong
Enumerator
Fpo
Trap
Tss
NonFpo
Definition at line 600 of file COFF.h.
ImageKind
enum llvm::object::ImageKind : uint16_t
The type of contents the offloading image contains.
Enumerator
IMG_None
IMG_Object
IMG_Bitcode
IMG_Cubin
IMG_Fatbinary
IMG_PTX
IMG_LAST
Definition at line 42 of file OffloadBinary.h.
Kind
enum llvm::object::Kind
Enumerator
Unknown
Eof
Identifier
Comma
Equal
EqualEqual
KwBase
KwConstant
KwData
KwExports
KwExportAs
KwHeapsize
KwLibrary
KwName
KwNoname
KwPrivate
KwStacksize
KwVersion
Definition at line 31 of file COFFModuleDefinition.cpp.
object_error
enum class llvm::object::object_error strong
Enumerator
arch_not_found
invalid_file_type
parse_failed
unexpected_eof
string_table_non_null_end
invalid_section_index
bitcode_section_not_found
invalid_symbol_index
section_stripped
Definition at line 27 of file Error.h.
OffloadKind
enum llvm::object::OffloadKind : uint16_t
The producer of the associated offloading image.
Enumerator
OFK_None
OFK_OpenMP
OFK_Cuda
OFK_HIP
OFK_LAST
Definition at line 33 of file OffloadBinary.h.
PPCInstrMasks
enum llvm::object::PPCInstrMasks : uint64_t
Enumerator
PADDI_R12_NO_DISP
ADDIS_R12_TO_R2_NO_DISP
ADDI_R12_TO_R2_NO_DISP
ADDI_R12_TO_R12_NO_DISP
PLD_R12_NO_DISP
MTCTR_R12
BCTR
Definition at line 87 of file ELF.h.
Function Documentation
append()
template<class T > static void llvm::object::append (std::vector< uint8_t > & B, const T & Data) static
Definition at line 139 of file COFFImportFile.cpp.
References B, and llvm::Data.
applyNameType()
static StringRef llvm::object::applyNameType (ImportNameType Type, StringRef name) static
Definition at line 57 of file COFFImportFile.cpp.
References llvm::StringRef::empty(), llvm::COFF::IMPORT_NAME_NOPREFIX, llvm::COFF::IMPORT_NAME_UNDECORATE, name, and llvm::StringRef::substr().
Referenced by llvm::object::COFFImportFile::getExportName(), and writeImportLibrary().
areTargetsCompatible()
bool llvm::object::areTargetsCompatible (const OffloadFile::TargetID & LHS, const OffloadFile::TargetID & RHS)
If the target is AMD we check the target IDs for mutual compatibility.
A target id is a string conforming to the folowing BNF syntax:
target-id ::= '<arch> (: <feature> ('+' | '-'))*'
The features 'xnack' and 'sramecc' are currently supported. These can be in the state of on, off, and any when unspecified. A target marked as any can bind with either on or off. This is used to link mutually compatible architectures together. Returns false in the case of an exact match.
Definition at line 350 of file OffloadBinary.cpp.
References T.
checkSectionOffsets()
template<class ELFT > bool llvm::object::checkSectionOffsets (const typename ELFT::Phdr & Phdr, const typename ELFT::Shdr & Sec)
Definition at line 169 of file ELF.h.
References llvm::ELF::SHT_NOBITS.
Referenced by isSectionInSegment().
checkSectionVMA()
template<class ELFT > bool llvm::object::checkSectionVMA (const typename ELFT::Phdr & Phdr, const typename ELFT::Shdr & Sec)
Definition at line 187 of file ELF.h.
References llvm::ELF::PT_TLS, llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_TLS, and llvm::ELF::SHT_NOBITS.
Referenced by isSectionInSegment().
coffnamecpy()
static void llvm::object::coffnamecpy (char(&) Dest[COFF::NameSize], StringRef Src) static
Definition at line 721 of file WindowsResource.cpp.
References assert(), and llvm::COFF::NameSize.
compareAddress()
int llvm::object::compareAddress (const SymEntry * A, const SymEntry * B)
Definition at line 21 of file SymbolSize.cpp.
References A, and B.
Referenced by computeSymbolSizes().
computeSymbolSizes()
std::vector< std::pair< SymbolRef, uint64_t > > llvm::object::computeSymbolSizes (const ObjectFile & O)
Definition at line 50 of file SymbolSize.cpp.
References llvm::array_pod_sort(), compareAddress(), llvm::dyn_cast(), getSectionID(), getSymbolSectionID(), I, N, P, llvm::report_fatal_error(), Size, Sym, and llvm::Expected< T >::takeError().
Referenced by llvm::symbolize::SymbolizableObjectFile::create().
convertUTF16LEToUTF8String()
static bool llvm::object::convertUTF16LEToUTF8String (ArrayRef< UTF16 > Src, std::string & Out) static
Definition at line 169 of file WindowsResource.cpp.
References llvm::ArrayRef(), llvm::convertUTF16ToUTF8String(), llvm::copy(), llvm::sys::IsBigEndianHost, and UNI_UTF16_BYTE_ORDER_MARK_SWAPPED.
Referenced by makeDuplicateResourceError(), and printStringOrID().
createBinary() [1/2]
Expected< std::unique_ptr< Binary > > llvm::object::createBinary (MemoryBufferRef Source, LLVMContext * Context = nullptr, bool InitContent = true)
Create a Binary from Source, autodetecting the file type.
Parameters
Source The data to create the Binary from.
Definition at line 45 of file Binary.cpp.
References llvm::file_magic::archive, llvm::file_magic::bitcode, llvm::file_magic::clang_ast, llvm::file_magic::coff_cl_gl_object, llvm::file_magic::coff_import_library, llvm::file_magic::coff_object, llvm::object::Archive::create(), llvm::object::MachOUniversalBinary::create(), llvm::object::MinidumpFile::create(), llvm::object::OffloadBinary::create(), llvm::object::TapiUniversal::create(), llvm::object::SymbolicFile::createSymbolicFile(), llvm::object::WindowsResource::createWindowsResource(), llvm::file_magic::cuda_fatbinary, llvm::file_magic::dxcontainer_object, llvm::file_magic::elf, llvm::file_magic::elf_core, llvm::file_magic::elf_executable, llvm::file_magic::elf_relocatable, llvm::file_magic::elf_shared_object, llvm::errorCodeToError(), llvm::MemoryBufferRef::getBuffer(), llvm::file_magic::goff_object, llvm::identify_magic(), invalid_file_type, llvm_unreachable, llvm::file_magic::macho_bundle, llvm::file_magic::macho_core, llvm::file_magic::macho_dsym_companion, llvm::file_magic::macho_dynamic_linker, llvm::file_magic::macho_dynamically_linked_shared_lib, llvm::file_magic::macho_dynamically_linked_shared_lib_stub, llvm::file_magic::macho_executable, llvm::file_magic::macho_file_set, llvm::file_magic::macho_fixed_virtual_memory_shared_lib, llvm::file_magic::macho_kext_bundle, llvm::file_magic::macho_object, llvm::file_magic::macho_preload_executable, llvm::file_magic::macho_universal_binary, llvm::file_magic::minidump, llvm::file_magic::offload_binary, llvm::file_magic::offload_bundle, llvm::file_magic::offload_bundle_compressed, llvm::file_magic::pdb, llvm::file_magic::pecoff_executable, llvm::file_magic::spirv_object, llvm::file_magic::tapi_file, llvm::file_magic::unknown, llvm::file_magic::wasm_object, llvm::file_magic::windows_resource, llvm::file_magic::xcoff_object_32, and llvm::file_magic::xcoff_object_64.
Referenced by llvm::MachO::DylibReader::accumulateSourceLocFromDSYM(), llvm::orc::StaticLibraryDefinitionGenerator::Create(), llvm::coverage::BinaryCoverageReader::create(), llvm::memprof::RawMemProfReader::create(), createBinary(), llvm::objcopy::macho::executeObjcopyOnMachOUniversalBinary(), llvm::object::Archive::Child::getAsBinary(), getPdbPathFromExe(), LLVMCreateBinary(), llvm::orc::StaticLibraryDefinitionGenerator::Load(), llvm::pdb::InputFile::open(), llvm::ifs::readELFFile(), and llvm::MachO::DylibReader::readFile().
createBinary() [2/2]
Expected< OwningBinary< Binary > > llvm::object::createBinary (StringRef Path, LLVMContext * Context = nullptr, bool InitContent = true)
Definition at line 107 of file Binary.cpp.
References llvm::Bin, createBinary(), llvm::errorCodeToError(), llvm::ErrorOr< T >::get(), llvm::Expected< T >::get(), llvm::ErrorOr< T >::getError(), llvm::MemoryBuffer::getFileOrSTDIN(), and llvm::Expected< T >::takeError().
createError()
Error llvm::object::createError (const Twine & Err) inline
Definition at line 84 of file Error.h.
References llvm::make_error(), and parse_failed.
Referenced by llvm::object::ELFFile< ELFT >::android_relas(), llvm::object::ELFFile< ELFT >::create(), llvm::object::ObjectFile::createELFObjectFile(), decodeBBAddrMapImpl(), defaultWarningHandler(), llvm::object::ELFFile< ELFT >::dynamicEntries(), fixupIndexV4(), fixupIndexV5(), llvm::object::MachOObjectFile::getDyldChainedFixupTargets(), llvm::object::ELFFile< ELFT >::getEntry(), getExtendedSymbolTableIndex(), llvm::object::XCOFFObjectFile::getImportFileTable(), llvm::object::ELFFile< ELFT >::getLinkAsStrtab(), getLoaderSecSymNameInStrTbl(), llvm::object::XCOFFObjectFile::getRawData(), llvm::object::ELFObjectFile< ELFT >::getRelocationAddend(), getSection(), llvm::object::ELFFile< ELFT >::getSectionAndRelocations(), llvm::object::XCOFFObjectFile::getSectionContents(), llvm::object::ELFFile< ELFT >::getSectionContentsAsArray(), llvm::object::XCOFFObjectFile::getSectionFileOffsetToRawData(), llvm::object::ELFFile< ELFT >::getSectionName(), llvm::object::ELFFile< ELFT >::getSectionStringTable(), llvm::object::ELFFile< ELFT >::getSegmentContents(), llvm::object::ELFFile< ELFT >::getSHNDXTable(), llvm::object::ELFFile< ELFT >::getStringTable(), llvm::object::XCOFFObjectFile::getStringTableEntry(), llvm::object::ELFFile< ELFT >::getStringTableForSymtab(), llvm::object::ELFFile< ELFT >::getSymbol(), llvm::object::XCOFFObjectFile::getSymbolNameByIndex(), llvm::object::ELFFile< ELFT >::getSymbolVersionByIndex(), llvm::object::ELFFile< ELFT >::getVersionDefinitions(), llvm::object::ELFFile< ELFT >::getVersionDependencies(), llvm::object::XCOFFSymbolRef::getXCOFFCsectAuxRef(), handleCompressedSection(), llvm::object::XCOFFSymbolRef::isFunction(), llvm::object::MachOChainedFixupEntry::moveNext(), llvm::object::ELFFile< ELFT >::notes_begin(), llvm::object::ELFFile< ELFT >::notes_begin(), llvm::object::DataRegion< T >::operator[](), llvm::object::ELFFile< ELFT >::program_headers(), readBBAddrMapImpl(), readDynsymVersionsImpl(), readULEB128As(), llvm::object::XCOFFObjectFile::relocations(), llvm::object::ELFFile< ELFT >::sections(), llvm::object::ELFFile< ELFT >::toMappedAddr(), and llvm::StackMapParser< Endianness >::validateHeader().
decodeCrel()
template<bool Is64> Error llvm::object::decodeCrel (ArrayRef< uint8_t > Content, function_ref< void(uint64_t, bool)> HdrHandler, function_ref< void(Elf_Crel_Impl< Is64 >)> EntryHandler)
Definition at line 215 of file ELF.h.
References B, Content, llvm::Count, llvm::ELF::CREL_HDR_ADDEND, llvm::Data, llvm::Offset, and llvm::DataExtractor::Cursor::takeError().
Referenced by llvm::object::ELFFile< ELFT >::crels(), llvm::object::ELFFile< ELFT >::decodeCrel(), and llvm::object::ELFObjectFile< ELFT >::section_rel_begin().
defaultWarningHandler()
static Error llvm::object::defaultWarningHandler (const Twine & Msg) inline static
Definition at line 164 of file ELF.h.
References createError().
describe()
template<class ELFT > static std::string llvm::object::describe (const ELFFile< ELFT > & Obj, const typename ELFT::Shdr & Sec) static
Definition at line 144 of file ELF.h.
References llvm::cantFail(), getELFSectionTypeName(), llvm::object::ELFFile< ELFT >::getHeader(), and llvm::object::ELFFile< ELFT >::sections().
Referenced by decodeBBAddrMapImpl(), llvm::object::ELFFile< ELFT >::getLinkAsStrtab(), llvm::object::ELFFile< ELFT >::getSectionAndRelocations(), llvm::object::ELFFile< ELFT >::getVersionDefinitions(), llvm::object::ELFFile< ELFT >::getVersionDependencies(), readBBAddrMapImpl(), and readDynsymVersionsImpl().
doesXCOFFTracebackTableBegin()
bool llvm::object::doesXCOFFTracebackTableBegin (ArrayRef< uint8_t > Bytes)
Definition at line 1388 of file XCOFFObjectFile.cpp.
References llvm::ArrayRef< T >::data(), llvm::support::endian::read32be(), and llvm::ArrayRef< T >::size().
extractOffloadBinaries()
Error llvm::object::extractOffloadBinaries (MemoryBufferRef Buffer, SmallVectorImpl< OffloadFile > & Binaries)
Extracts embedded device offloading code from a memory Buffer to a list of Binaries.
Definition at line 272 of file OffloadBinary.cpp.
References llvm::file_magic::archive, llvm::file_magic::bitcode, llvm::file_magic::coff_object, llvm::object::Archive::create(), llvm::object::ObjectFile::createObjectFile(), llvm::file_magic::elf_executable, llvm::file_magic::elf_relocatable, llvm::file_magic::elf_shared_object, llvm::Expected< T >::get(), llvm::MemoryBufferRef::getBuffer(), llvm::identify_magic(), llvm::file_magic::offload_binary, llvm::Error::success(), and llvm::Expected< T >::takeError().
generateXCOFFFixedNameStringRef()
static StringRef llvm::object::generateXCOFFFixedNameStringRef (const char * Name) static
Definition at line 50 of file XCOFFObjectFile.cpp.
References Name, and llvm::XCOFF::NameSize.
Referenced by llvm::object::XCOFFObjectFile::getCFileName(), llvm::object::XCOFFSectionHeader< T >::getName(), llvm::object::XCOFFSymbolRef::getName(), llvm::object::XCOFFObjectFile::getSectionName(), llvm::object::LoaderSectionSymbolEntry32::getSymbolName(), and llvm::object::XCOFFObjectFile::getSymbolSectionName().
getBuildID()
BuildIDRef llvm::object::getBuildID (const ObjectFile * Obj)
Returns the build ID, if any, contained in the given object file.
Definition at line 56 of file BuildID.cpp.
References llvm::dyn_cast().
Referenced by loadBinaryFormat().
getDynSymtabSizeFromGnuHash()
template<class ELFT > static Expected< uint64_t > llvm::object::getDynSymtabSizeFromGnuHash (const typename ELFT::GnuHash & Table, const void * BufEnd) static
This function finds the number of dynamic symbols using a GNU hash table.
Parameters
Table The GNU hash table for .dynsym.
Definition at line 796 of file ELF.h.
References llvm::createStringError(), and parse_failed.
Referenced by llvm::object::ELFFile< ELFT >::getDynSymtabSize().
getELFAddend()
static int64_t llvm::object::getELFAddend (RelocationRef R) static
Definition at line 32 of file RelocationResolver.cpp.
References llvm::object::ELFRelocationRef::getAddend(), llvm::handleAllErrors(), and llvm::Expected< T >::takeError().
Referenced by resolveRelocation().
getElfArchType()
std::pair< unsigned char, unsigned char > llvm::object::getElfArchType (StringRef Object) inline
Definition at line 79 of file ELF.h.
References llvm::ELF::EI_CLASS, llvm::ELF::EI_DATA, llvm::ELF::EI_NIDENT, llvm::ELF::ELFCLASSNONE, and llvm::ELF::ELFDATANONE.
Referenced by llvm::orc::ELFDebugObject::Create(), and llvm::object::ObjectFile::createELFObjectFile().
getELFRelativeRelocationType()
uint32_t llvm::object::getELFRelativeRelocationType (uint32_t Machine)
Definition at line 192 of file ELF.cpp.
References llvm::ELF::EM_386, llvm::ELF::EM_AARCH64, llvm::ELF::EM_AMDGPU, llvm::ELF::EM_ARC_COMPACT, llvm::ELF::EM_ARC_COMPACT2, llvm::ELF::EM_ARM, llvm::ELF::EM_AVR, llvm::ELF::EM_BPF, llvm::ELF::EM_CSKY, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_IAMCU, llvm::ELF::EM_LANAI, llvm::ELF::EM_LOONGARCH, llvm::ELF::EM_MIPS, llvm::ELF::EM_PPC, llvm::ELF::EM_PPC64, llvm::ELF::EM_RISCV, llvm::ELF::EM_S390, llvm::ELF::EM_SPARC, llvm::ELF::EM_SPARC32PLUS, llvm::ELF::EM_SPARCV9, llvm::ELF::EM_VE, llvm::ELF::EM_X86_64, and Machine.
Referenced by llvm::object::ELFFile< ELFT >::getRelativeRelocationType().
getELFRelocationTypeName()
StringRef llvm::object::getELFRelocationTypeName (uint32_t Machine, uint32_t Type)
Definition at line 23 of file ELF.cpp.
References llvm::ELF::EM_386, llvm::ELF::EM_68K, llvm::ELF::EM_AARCH64, llvm::ELF::EM_AMDGPU, llvm::ELF::EM_ARC_COMPACT, llvm::ELF::EM_ARC_COMPACT2, llvm::ELF::EM_ARM, llvm::ELF::EM_AVR, llvm::ELF::EM_BPF, llvm::ELF::EM_CSKY, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_IAMCU, llvm::ELF::EM_LANAI, llvm::ELF::EM_LOONGARCH, llvm::ELF::EM_MIPS, llvm::ELF::EM_MSP430, llvm::ELF::EM_PPC, llvm::ELF::EM_PPC64, llvm::ELF::EM_RISCV, llvm::ELF::EM_S390, llvm::ELF::EM_SPARC, llvm::ELF::EM_SPARC32PLUS, llvm::ELF::EM_SPARCV9, llvm::ELF::EM_VE, llvm::ELF::EM_X86_64, llvm::ELF::EM_XTENSA, and Machine.
Referenced by llvm::jitlink::getJITLinkEdgeKind(), llvm::object::ELFFile< ELFT >::getRelocationTypeName(), and llvm::object::ELFObjectFile< ELFT >::getRelocationTypeName().
getELFSectionTypeName()
StringRef llvm::object::getELFSectionTypeName (uint32_t Machine, uint32_t Type)
Referenced by describe(), llvm::object::ELFFile< ELFT >::getSHNDXTable(), and llvm::object::ELFFile< ELFT >::getStringTable().
getExtendedSymbolTableIndex()
template<class ELFT > Expected< uint32_t > llvm::object::getExtendedSymbolTableIndex (const typename ELFT::Sym & Sym, unsigned SymIndex, DataRegion< typename ELFT::Word > ShndxTable) inline
Definition at line 541 of file ELF.h.
References assert(), createError(), llvm::object::DataRegion< T >::First, llvm::ELF::SHN_XINDEX, Sym, llvm::Expected< T >::takeError(), and llvm::dwarf::toString().
Referenced by llvm::object::ELFFile< ELFT >::getSectionIndex(), and llvm::jitlink::ELFLinkGraphBuilder< ELFT >::graphifySymbols().
getImageKind()
ImageKind llvm::object::getImageKind (StringRef Name)
Convert a string Name to an image kind.
Definition at line 323 of file OffloadBinary.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), IMG_Bitcode, IMG_Cubin, IMG_Fatbinary, IMG_None, IMG_Object, IMG_PTX, and Name.
getImageKindName()
StringRef llvm::object::getImageKindName (ImageKind Name)
Convert an image kind to its string representation.
Definition at line 333 of file OffloadBinary.cpp.
References IMG_Bitcode, IMG_Cubin, IMG_Fatbinary, IMG_Object, and IMG_PTX.
getImgRelRelocation()
static uint16_t llvm::object::getImgRelRelocation (MachineTypes Machine) static
Definition at line 122 of file COFFImportFile.cpp.
References llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64EC, llvm::COFF::IMAGE_FILE_MACHINE_ARM64X, llvm::COFF::IMAGE_FILE_MACHINE_ARMNT, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::COFF::IMAGE_REL_AMD64_ADDR32NB, llvm::COFF::IMAGE_REL_ARM64_ADDR32NB, llvm::COFF::IMAGE_REL_ARM_ADDR32NB, llvm::COFF::IMAGE_REL_I386_DIR32NB, llvm_unreachable, and Machine.
getLoaderSecSymNameInStrTbl()
template<typename T > Expected< StringRef > llvm::object::getLoaderSecSymNameInStrTbl (const T * LoaderSecHeader, uint64_t Offset)
Definition at line 99 of file XCOFFObjectFile.cpp.
References createError(), llvm::Offset, and llvm::Twine::utohexstr().
Referenced by llvm::object::LoaderSectionSymbolEntry32::getSymbolName(), and llvm::object::LoaderSectionSymbolEntry64::getSymbolName().
getNameType()
static ImportNameType llvm::object::getNameType (StringRef Sym, StringRef ExtName, MachineTypes Machine, bool MinGW) static
Definition at line 172 of file COFFImportFile.cpp.
References llvm::StringRef::contains(), llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::COFF::IMPORT_NAME, llvm::COFF::IMPORT_NAME_NOPREFIX, llvm::COFF::IMPORT_NAME_UNDECORATE, Machine, llvm::StringRef::starts_with(), and Sym.
Referenced by writeImportLibrary().
getObject()
template<typename T > static Expected< const T * > llvm::object::getObject (MemoryBufferRef M, const void * Ptr, const uint64_t Size = sizeof(T)) static
Definition at line 33 of file XCOFFObjectFile.cpp.
References Addr, llvm::object::Binary::checkOffset(), Ptr, and Size.
Referenced by llvm::object::XCOFFObjectFile::getImportFileTable(), llvm::object::ImportDirectoryEntryRef::getImportTableEntry(), getNumberOfRelocations(), and llvm::object::XCOFFObjectFile::relocations().
getOffloadKind()
OffloadKind llvm::object::getOffloadKind (StringRef Name)
Convert a string Name to an offload kind.
Definition at line 302 of file OffloadBinary.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), Name, OFK_Cuda, OFK_HIP, OFK_None, and OFK_OpenMP.
getOffloadKindName()
StringRef llvm::object::getOffloadKindName (OffloadKind Name)
Convert an offload kind to its string representation.
Definition at line 310 of file OffloadBinary.cpp.
References OFK_Cuda, OFK_HIP, and OFK_OpenMP.
getPhdrIndexForError()
template<class ELFT > std::string llvm::object::getPhdrIndexForError (const ELFFile< ELFT > & Obj, const typename ELFT::Phdr & Phdr)
Definition at line 154 of file ELF.h.
References llvm::consumeError(), and llvm::object::ELFFile< ELFT >::program_headers().
Referenced by llvm::object::ELFFile< ELFT >::getSegmentContents().
getRelocationResolver()
std::pair< SupportsRelocation, RelocationResolver > llvm::object::getRelocationResolver (const ObjectFile & Obj)
Definition at line 767 of file RelocationResolver.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_be, llvm::Triple::amdgcn, llvm::Triple::arm, llvm::Triple::armeb, assert(), llvm::Triple::avr, llvm::Triple::bpfeb, llvm::Triple::bpfel, llvm::Triple::csky, llvm::object::ObjectFile::getArch(), llvm::object::ObjectFile::getBytesInAddress(), llvm::Triple::hexagon, isAMDGPU(), llvm::object::Binary::isCOFF(), llvm::object::Binary::isELF(), llvm::object::Binary::isMachO(), llvm::object::Binary::isWasm(), llvm::Triple::lanai, llvm_unreachable, llvm::Triple::loongarch32, llvm::Triple::loongarch64, llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::msp430, llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::Triple::ppcle, llvm::Triple::r600, resolveAArch64(), resolveAmdgpu(), resolveARM(), resolveAVR(), resolveBPF(), resolveCOFFARM(), resolveCOFFARM64(), resolveCOFFX86(), resolveCOFFX86_64(), resolveCSKY(), resolveHexagon(), resolveLanai(), resolveLoongArch(), resolveMachOX86_64(), resolveMips32(), resolveMips64(), resolveMSP430(), resolvePPC32(), resolvePPC64(), resolveRISCV(), resolveSparc32(), resolveSparc64(), resolveSystemZ(), resolveWasm32(), resolveWasm64(), resolveX86(), resolveX86_64(), llvm::Triple::riscv32, llvm::Triple::riscv64, llvm::Triple::sparc, llvm::Triple::sparcv9, supportsAArch64(), supportsAmdgpu(), supportsARM(), supportsAVR(), supportsBPF(), supportsCOFFARM(), supportsCOFFARM64(), supportsCOFFX86(), supportsCOFFX86_64(), supportsCSKY(), supportsHexagon(), supportsLanai(), supportsLoongArch(), supportsMachOX86_64(), supportsMips32(), supportsMips64(), supportsMSP430(), supportsPPC32(), supportsPPC64(), supportsRISCV(), supportsSparc32(), supportsSparc64(), supportsSystemZ(), supportsWasm32(), supportsWasm64(), supportsX86(), supportsX86_64(), llvm::Triple::systemz, llvm::Triple::thumb, llvm::Triple::wasm32, llvm::Triple::wasm64, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by loadObj().
getSecIndexForError()
template<class ELFT > std::string llvm::object::getSecIndexForError (const ELFFile< ELFT > & Obj, const typename ELFT::Shdr & Sec)
Definition at line 130 of file ELF.h.
References llvm::consumeError(), and llvm::object::ELFFile< ELFT >::sections().
Referenced by llvm::object::ELFFile< ELFT >::getSectionContentsAsArray(), llvm::object::ELFFile< ELFT >::getSectionName(), llvm::object::ELFFile< ELFT >::getStringTable(), and llvm::object::ELFFile< ELFT >::getSymbol().
getSection()
template<class ELFT > Expected< const typename ELFT::Shdr * > llvm::object::getSection (typename ELFT::ShdrRange Sections, uint32_t Index) inline
Definition at line 533 of file ELF.h.
References createError().
Referenced by llvm::object::ELFFile< ELFT >::getEntry(), llvm::object::ELFFile< ELFT >::getLinkAsStrtab(), llvm::object::ELFObjectFile< ELFT >::getRelocatedSection(), llvm::object::ELFFile< ELFT >::getSection(), llvm::object::ELFFile< ELFT >::getSection(), llvm::object::ELFFile< ELFT >::getSection(), llvm::object::ELFObjectFile< ELFT >::getSectionAddress(), llvm::object::ELFObjectFile< ELFT >::getSectionAlignment(), llvm::object::ELFFile< ELFT >::getSectionAndRelocations(), llvm::object::ELFObjectFile< ELFT >::getSectionContents(), llvm::object::ELFObjectFile< ELFT >::getSectionFlags(), llvm::object::ELFObjectFile< ELFT >::getSectionIndex(), llvm::object::ELFObjectFile< ELFT >::getSectionName(), llvm::object::ELFObjectFile< ELFT >::getSectionOffset(), llvm::object::ELFObjectFile< ELFT >::getSectionSize(), llvm::object::ELFObjectFile< ELFT >::getSectionType(), llvm::object::ELFFile< ELFT >::getSHNDXTable(), llvm::object::ELFFile< ELFT >::getStringTableForSymtab(), llvm::object::ELFObjectFile< ELFT >::isBerkeleyData(), llvm::object::ELFObjectFile< ELFT >::isBerkeleyText(), llvm::object::ELFObjectFile< ELFT >::isSectionBSS(), llvm::object::ELFObjectFile< ELFT >::isSectionCompressed(), llvm::object::ELFObjectFile< ELFT >::isSectionData(), llvm::object::ELFObjectFile< ELFT >::isSectionText(), llvm::object::ELFObjectFile< ELFT >::isSectionVirtual(), LLVMMoveToContainingSection(), and llvm::object::ELFObjectFile< ELFT >::moveSectionNext().
getWithOffset()
static uintptr_t llvm::object::getWithOffset (uintptr_t Base, ptrdiff_t Offset) static
Definition at line 41 of file XCOFFObjectFile.cpp.
References llvm::sampleprof::Base, and llvm::Offset.
Referenced by llvm::object::XCOFFObjectFile::getAdvancedSymbolEntryAddress(), llvm::object::XCOFFObjectFile::getSectionByNum(), llvm::object::XCOFFObjectFile::getSymbolAuxType(), llvm::object::XCOFFObjectFile::relocations(), and llvm::object::XCOFFObjectFile::section_end().
hashGnu()
uint32_t llvm::object::hashGnu (StringRef Name) inline
This function returns the hash value for a symbol in the .dynsym section for the GNU hash table.
The implementation is defined in the GNU hash ABI. REF : https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=bfd/elf.c#l222
Definition at line 1363 of file ELF.h.
References llvm::CallingConv::C, H, and Name.
hashSysV()
uint32_t llvm::object::hashSysV (StringRef SymbolName) inline
This function returns the hash value for a symbol in the .dynsym section Name of the API remains consistent as specified in the libelf REF : http://www.sco.com/developers/gabi/latest/ch5.dynamic.html#hash.
Definition at line 1351 of file ELF.h.
References llvm::CallingConv::C, and H.
isAMDGPU()
static bool llvm::object::isAMDGPU (const ObjectFile & Obj) static
Returns true if Obj is an AMDGPU code object based solely on the value of e_machine.
AMDGPU code objects with an e_machine of EF_AMDGPU_MACH_NONE do not identify their arch as either r600 or amdgcn, but we can still handle their relocations. When we identify an ELF object with an UnknownArch, we use isAMDGPU to check for this case.
Definition at line 261 of file RelocationResolver.cpp.
References llvm::dyn_cast(), and llvm::ELF::EM_AMDGPU.
Referenced by getRelocationResolver().
isDecorated()
static bool llvm::object::isDecorated (StringRef Sym, bool MingwDef) static
Definition at line 58 of file COFFModuleDefinition.cpp.
References Sym.
isNotObjectErrorInvalidFileType()
llvm::Error llvm::object::isNotObjectErrorInvalidFileType (llvm::Error Err)
isNotObjectErrorInvalidFileType() is used when looping through the children of an archive after calling getAsBinary() on the child and it returns an llvm::Error.
In the cases we want to loop through the children and ignore the non-objects in the archive this is used to test the error to see if an error() function needs to called on the llvm::Error.
Definition at line 82 of file Error.cpp.
References llvm::Error, llvm::handleErrors(), invalid_file_type, and llvm::Error::success().
isSectionInSegment()
template<class ELFT > bool llvm::object::isSectionInSegment (const typename ELFT::Phdr & Phdr, const typename ELFT::Shdr & Sec)
Definition at line 206 of file ELF.h.
References checkSectionOffsets(), and checkSectionVMA().
llvm::object::XCOFFObjectFile::relocations< llvm::object::XCOFFSectionHeader32, llvm::object::XCOFFRelocation32 >()
template llvm::Expected< llvm::ArrayRef< llvm::object::XCOFFRelocation32 > > llvm::object::llvm::object::XCOFFObjectFile::relocations< llvm::object::XCOFFSectionHeader32, llvm::object::XCOFFRelocation32 > (llvm::object::XCOFFSectionHeader32 const &) const
llvm::object::XCOFFObjectFile::relocations< llvm::object::XCOFFSectionHeader64, llvm::object::XCOFFRelocation64 >()
template llvm::Expected< llvm::ArrayRef< llvm::object::XCOFFRelocation64 > > llvm::object::llvm::object::XCOFFObjectFile::relocations< llvm::object::XCOFFSectionHeader64, llvm::object::XCOFFRelocation64 > (llvm::object::XCOFFSectionHeader64 const &) const
make_error_code()
std::error_code llvm::object::make_error_code (object_error e) inline
Definition at line 40 of file Error.h.
References object_category().
Referenced by llvm::object::BinaryError::BinaryError(), and llvm::object::GenericBinaryError::GenericBinaryError().
makeDuplicateResourceError() [1/2]
static std::string llvm::object::makeDuplicateResourceError (const ResourceEntryRef & Entry, StringRef File1, StringRef File2) static
Definition at line 180 of file WindowsResource.cpp.
References convertUTF16LEToUTF8String(), OS, and printResourceTypeName().
Referenced by llvm::object::WindowsResourceParser::parse().
makeDuplicateResourceError() [2/2]
static std::string llvm::object::makeDuplicateResourceError (const std::vector< WindowsResourceParser::StringOrID > & Context, StringRef File1, StringRef File2) static
Definition at line 227 of file WindowsResource.cpp.
References OS, and printStringOrID().
object_category()
const std::error_category & llvm::object::object_category ()
Definition at line 77 of file Error.cpp.
Referenced by make_error_code().
operator!=()
bool llvm::object::operator!= (const DataRefImpl & a, const DataRefImpl & b) inline
Definition at line 59 of file SymbolicFile.h.
References operator==().
operator<() [1/3]
bool llvm::object::operator< (const DataRefImpl & a, const DataRefImpl & b) inline
Definition at line 63 of file SymbolicFile.h.
operator<() [2/3]
bool llvm::object::operator< (const ELFSymbolRef & A, const ELFSymbolRef & B) inline
Definition at line 205 of file ELFObjectFile.h.
References A, llvm::object::DataRefImpl::a, B, llvm::object::DataRefImpl::b, and llvm::object::DataRefImpl::d.
operator<() [3/3]
bool llvm::object::operator< (const SectionedAddress & LHS, const SectionedAddress & RHS) inline
Definition at line 152 of file ObjectFile.h.
operator<<() [1/2]
template<typename OStream > OStream & llvm::object::operator<< (OStream & OS, const DataRefImpl & D)
Definition at line 47 of file SymbolicFile.h.
References D, llvm::format(), and OS.
operator<<() [2/2]
raw_ostream & llvm::object::operator<< (raw_ostream & OS, const SectionedAddress & Addr)
Definition at line 34 of file ObjectFile.cpp.
References Addr, llvm::format_hex(), and OS.
operator==() [1/2]
bool llvm::object::operator== (const DataRefImpl & a, const DataRefImpl & b) inline
Definition at line 53 of file SymbolicFile.h.
operator==() [2/2]
bool llvm::object::operator== (const SectionedAddress & LHS, const SectionedAddress & RHS) inline
Definition at line 158 of file ObjectFile.h.
Referenced by operator!=().
parseBuildID()
BuildID llvm::object::parseBuildID (StringRef Str)
Parses a build ID from a hex string.
Definition at line 47 of file BuildID.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
parseCOFFModuleDefinition()
Expected< COFFModuleDefinition > llvm::object::parseCOFFModuleDefinition (MemoryBufferRef MB, COFF::MachineTypes Machine, bool MingwDef = false, bool AddUnderscores = true)
Definition at line 365 of file COFFModuleDefinition.cpp.
References llvm::MemoryBufferRef::getBuffer(), Machine, and llvm::object::Parser::parse().
Referenced by llvm::libDriverMain().
printResourceTypeName()
void llvm::object::printResourceTypeName (uint16_t TypeID, raw_ostream & OS)
Definition at line 142 of file WindowsResource.cpp.
References OS.
Referenced by makeDuplicateResourceError(), and printStringOrID().
printStringOrID()
static void llvm::object::printStringOrID (const WindowsResourceParser::StringOrID & S, raw_string_ostream & OS, bool IsType, bool IsID) static
Definition at line 212 of file WindowsResource.cpp.
References convertUTF16LEToUTF8String(), llvm::object::WindowsResourceParser::StringOrID::ID, llvm::object::WindowsResourceParser::StringOrID::IsString, OS, printResourceTypeName(), and llvm::object::WindowsResourceParser::StringOrID::String.
Referenced by makeDuplicateResourceError().
readIRSymtab()
Expected< IRSymtabFile > llvm::object::readIRSymtab (MemoryBufferRef MBRef)
Reads a bitcode file, creating its irsymtab if necessary.
Definition at line 135 of file IRObjectFile.cpp.
References F, llvm::object::IRObjectFile::findBitcodeInMemBuffer(), llvm::getBitcodeFileContents(), llvm::irsymtab::readBitcode(), and llvm::Expected< T >::takeError().
Referenced by llvm::lto::InputFile::create().
readStringOrId()
static Error llvm::object::readStringOrId (BinaryStreamReader & Reader, uint16_t & ID, ArrayRef< UTF16 > & Str, bool & IsString) static
Definition at line 98 of file WindowsResource.cpp.
References llvm::BinaryStreamReader::getOffset(), llvm::BinaryStreamReader::readInteger(), llvm::BinaryStreamReader::readWideString(), RETURN_IF_ERROR, llvm::BinaryStreamReader::setOffset(), and llvm::Error::success().
replace()
static Expected< std::string > llvm::object::replace (StringRef S, StringRef From, StringRef To) static
Definition at line 189 of file COFFImportFile.cpp.
References llvm::StringRef::find(), From, llvm::make_error(), llvm::StringRef::npos, parse_failed, llvm::StringRef::starts_with(), and llvm::StringRef::substr().
Referenced by writeImportLibrary().
resolveAArch64()
static uint64_t llvm::object::resolveAArch64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t , int64_t Addend) static
Definition at line 89 of file RelocationResolver.cpp.
References llvm_unreachable, and llvm::Offset.
Referenced by getRelocationResolver().
resolveAmdgpu()
static uint64_t llvm::object::resolveAmdgpu (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t , int64_t Addend) static
Definition at line 277 of file RelocationResolver.cpp.
References llvm_unreachable.
Referenced by getRelocationResolver().
resolveARM()
static uint64_t llvm::object::resolveARM (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend) static
Definition at line 344 of file RelocationResolver.cpp.
References assert(), llvm_unreachable, and llvm::Offset.
Referenced by getRelocationResolver().
resolveAVR()
static uint64_t llvm::object::resolveAVR (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t , int64_t Addend) static
Definition at line 370 of file RelocationResolver.cpp.
References llvm_unreachable.
Referenced by getRelocationResolver().
resolveBPF()
static uint64_t llvm::object::resolveBPF (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t) static
Definition at line 117 of file RelocationResolver.cpp.
References llvm_unreachable.
Referenced by getRelocationResolver().
resolveCOFFARM()
static uint64_t llvm::object::resolveCOFFARM (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t) static
Definition at line 646 of file RelocationResolver.cpp.
References llvm::COFF::IMAGE_REL_ARM_ADDR32, llvm::COFF::IMAGE_REL_ARM_SECREL, and llvm_unreachable.
Referenced by getRelocationResolver().
resolveCOFFARM64()
static uint64_t llvm::object::resolveCOFFARM64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t) static
Definition at line 667 of file RelocationResolver.cpp.
References llvm::COFF::IMAGE_REL_ARM64_ADDR64, llvm::COFF::IMAGE_REL_ARM64_SECREL, and llvm_unreachable.
Referenced by getRelocationResolver().
resolveCOFFX86()
static uint64_t llvm::object::resolveCOFFX86 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t) static
Definition at line 603 of file RelocationResolver.cpp.
References llvm::COFF::IMAGE_REL_I386_DIR32, llvm::COFF::IMAGE_REL_I386_SECREL, and llvm_unreachable.
Referenced by getRelocationResolver().
resolveCOFFX86_64()
static uint64_t llvm::object::resolveCOFFX86_64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t) static
Definition at line 624 of file RelocationResolver.cpp.
References llvm::COFF::IMAGE_REL_AMD64_ADDR64, llvm::COFF::IMAGE_REL_AMD64_SECREL, and llvm_unreachable.
Referenced by getRelocationResolver().
resolveCSKY()
static uint64_t llvm::object::resolveCSKY (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend) static
Definition at line 521 of file RelocationResolver.cpp.
References llvm_unreachable, and llvm::Offset.
Referenced by getRelocationResolver().
resolveHexagon()
static uint64_t llvm::object::resolveHexagon (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t , int64_t Addend) static
Definition at line 434 of file RelocationResolver.cpp.
References llvm_unreachable.
Referenced by getRelocationResolver().
resolveLanai()
static uint64_t llvm::object::resolveLanai (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t , int64_t Addend) static
Definition at line 386 of file RelocationResolver.cpp.
References llvm_unreachable.
Referenced by getRelocationResolver().
resolveLoongArch()
static uint64_t llvm::object::resolveLoongArch (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend) static
Definition at line 557 of file RelocationResolver.cpp.
References llvm_unreachable, and llvm::Offset.
Referenced by getRelocationResolver().
resolveMachOX86_64()
static uint64_t llvm::object::resolveMachOX86_64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t) static
Definition at line 683 of file RelocationResolver.cpp.
References llvm_unreachable, and llvm::MachO::X86_64_RELOC_UNSIGNED.
Referenced by getRelocationResolver().
resolveMips32()
static uint64_t llvm::object::resolveMips32 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t) static
Definition at line 403 of file RelocationResolver.cpp.
References llvm_unreachable.
Referenced by getRelocationResolver().
resolveMips64()
static uint64_t llvm::object::resolveMips64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t , int64_t Addend) static
Definition at line 141 of file RelocationResolver.cpp.
References llvm_unreachable, and llvm::Offset.
Referenced by getRelocationResolver().
resolveMSP430()
static uint64_t llvm::object::resolveMSP430 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t , int64_t Addend) static
Definition at line 167 of file RelocationResolver.cpp.
References llvm_unreachable.
Referenced by getRelocationResolver().
resolvePPC32()
static uint64_t llvm::object::resolvePPC32 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t , int64_t Addend) static
Definition at line 323 of file RelocationResolver.cpp.
References llvm_unreachable, and llvm::Offset.
Referenced by getRelocationResolver().
resolvePPC64()
static uint64_t llvm::object::resolvePPC64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t , int64_t Addend) static
Definition at line 191 of file RelocationResolver.cpp.
References llvm_unreachable, and llvm::Offset.
Referenced by getRelocationResolver().
resolveRelocation()
uint64_t llvm::object::resolveRelocation (RelocationResolver Resolver, const RelocationRef & R, uint64_t S, uint64_t LocData)
Definition at line 870 of file RelocationResolver.cpp.
References llvm::cast(), llvm::dyn_cast(), getELFAddend(), llvm::Triple::loongarch32, llvm::Triple::loongarch64, llvm::Triple::riscv32, llvm::Triple::riscv64, and llvm::ELF::SHT_RELA.
Referenced by llvm::DWARFDataExtractor::getRelocatedValue(), loadObj(), and llvm::RuntimeDyldELF::~RuntimeDyldELF().
resolveRISCV()
static uint64_t llvm::object::resolveRISCV (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend) static
Definition at line 466 of file RelocationResolver.cpp.
References A, llvm_unreachable, llvm::Offset, and RA.
Referenced by getRelocationResolver().
resolveSparc32()
static uint64_t llvm::object::resolveSparc32 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend) static
Definition at line 423 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
resolveSparc64()
static uint64_t llvm::object::resolveSparc64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t , int64_t Addend) static
Definition at line 241 of file RelocationResolver.cpp.
References llvm_unreachable.
Referenced by getRelocationResolver().
resolveSystemZ()
static uint64_t llvm::object::resolveSystemZ (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t , int64_t Addend) static
Definition at line 217 of file RelocationResolver.cpp.
References llvm_unreachable.
Referenced by getRelocationResolver().
resolveWasm32()
static uint64_t llvm::object::resolveWasm32 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t) static
Definition at line 726 of file RelocationResolver.cpp.
References llvm_unreachable.
Referenced by getRelocationResolver(), and resolveWasm64().
resolveWasm64()
static uint64_t llvm::object::resolveWasm64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend) static
Definition at line 750 of file RelocationResolver.cpp.
References llvm::Offset, and resolveWasm32().
Referenced by getRelocationResolver().
resolveX86()
static uint64_t llvm::object::resolveX86 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t) static
Definition at line 299 of file RelocationResolver.cpp.
References llvm_unreachable, and llvm::Offset.
Referenced by getRelocationResolver().
resolveX86_64()
static uint64_t llvm::object::resolveX86_64 (uint64_t Type, uint64_t Offset, uint64_t S, uint64_t LocData, int64_t Addend) static
Definition at line 56 of file RelocationResolver.cpp.
References llvm_unreachable, and llvm::Offset.
Referenced by getRelocationResolver().
supportsAArch64()
static bool llvm::object::supportsAArch64 (uint64_t Type) static
Definition at line 76 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsAmdgpu()
static bool llvm::object::supportsAmdgpu (uint64_t Type) static
Definition at line 267 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsARM()
static bool llvm::object::supportsARM (uint64_t Type) static
Definition at line 334 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsAVR()
static bool llvm::object::supportsAVR (uint64_t Type) static
Definition at line 360 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsBPF()
static bool llvm::object::supportsBPF (uint64_t Type) static
Definition at line 107 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsCOFFARM()
static bool llvm::object::supportsCOFFARM (uint64_t Type) static
Definition at line 636 of file RelocationResolver.cpp.
References llvm::COFF::IMAGE_REL_ARM_ADDR32, and llvm::COFF::IMAGE_REL_ARM_SECREL.
Referenced by getRelocationResolver().
supportsCOFFARM64()
static bool llvm::object::supportsCOFFARM64 (uint64_t Type) static
Definition at line 657 of file RelocationResolver.cpp.
References llvm::COFF::IMAGE_REL_ARM64_ADDR64, and llvm::COFF::IMAGE_REL_ARM64_SECREL.
Referenced by getRelocationResolver().
supportsCOFFX86()
static bool llvm::object::supportsCOFFX86 (uint64_t Type) static
Definition at line 593 of file RelocationResolver.cpp.
References llvm::COFF::IMAGE_REL_I386_DIR32, and llvm::COFF::IMAGE_REL_I386_SECREL.
Referenced by getRelocationResolver().
supportsCOFFX86_64()
static bool llvm::object::supportsCOFFX86_64 (uint64_t Type) static
Definition at line 614 of file RelocationResolver.cpp.
References llvm::COFF::IMAGE_REL_AMD64_ADDR64, and llvm::COFF::IMAGE_REL_AMD64_SECREL.
Referenced by getRelocationResolver().
supportsCSKY()
static bool llvm::object::supportsCSKY (uint64_t Type) static
Definition at line 510 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsHexagon()
static bool llvm::object::supportsHexagon (uint64_t Type) static
Definition at line 430 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsLanai()
static bool llvm::object::supportsLanai (uint64_t Type) static
Definition at line 382 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsLoongArch()
static bool llvm::object::supportsLoongArch (uint64_t Type) static
Definition at line 535 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsMachOX86_64()
static bool llvm::object::supportsMachOX86_64 (uint64_t Type) static
Definition at line 679 of file RelocationResolver.cpp.
References llvm::MachO::X86_64_RELOC_UNSIGNED.
Referenced by getRelocationResolver().
supportsMips32()
static bool llvm::object::supportsMips32 (uint64_t Type) static
Definition at line 393 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsMips64()
static bool llvm::object::supportsMips64 (uint64_t Type) static
Definition at line 129 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsMSP430()
static bool llvm::object::supportsMSP430 (uint64_t Type) static
Definition at line 157 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsPPC32()
static bool llvm::object::supportsPPC32 (uint64_t Type) static
Definition at line 313 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsPPC64()
static bool llvm::object::supportsPPC64 (uint64_t Type) static
Definition at line 179 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsRISCV()
static bool llvm::object::supportsRISCV (uint64_t Type) static
Definition at line 441 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsSparc32()
static bool llvm::object::supportsSparc32 (uint64_t Type) static
Definition at line 413 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsSparc64()
static bool llvm::object::supportsSparc64 (uint64_t Type) static
Definition at line 229 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsSystemZ()
static bool llvm::object::supportsSystemZ (uint64_t Type) static
Definition at line 207 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsWasm32()
static bool llvm::object::supportsWasm32 (uint64_t Type) static
Definition at line 690 of file RelocationResolver.cpp.
Referenced by getRelocationResolver(), and supportsWasm64().
supportsWasm64()
static bool llvm::object::supportsWasm64 (uint64_t Type) static
Definition at line 712 of file RelocationResolver.cpp.
References supportsWasm32().
Referenced by getRelocationResolver().
supportsX86()
static bool llvm::object::supportsX86 (uint64_t Type) static
Definition at line 288 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
supportsX86_64()
static bool llvm::object::supportsX86_64 (uint64_t Type) static
Definition at line 40 of file RelocationResolver.cpp.
Referenced by getRelocationResolver().
viewAs()
template<typename T > static const T * llvm::object::viewAs (uintptr_t in) static
Definition at line 46 of file XCOFFObjectFile.cpp.
Referenced by llvm::object::XCOFFObjectFile::getImportFileTable(), llvm::object::XCOFFObjectFile::getRelocationOffset(), llvm::object::XCOFFObjectFile::getRelocationSymbol(), llvm::object::XCOFFObjectFile::getRelocationType(), llvm::object::XCOFFObjectFile::getRelocationTypeName(), llvm::object::XCOFFObjectFile::getSymbolAuxType(), llvm::object::XCOFFSymbolRef::getXCOFFCsectAuxRef(), and llvm::object::XCOFFObjectFile::moveRelocationNext().
writeImportLibrary()
Error llvm::object::writeImportLibrary (StringRef ImportName, StringRef Path, ArrayRef< COFFShortExport > Exports, COFF::MachineTypes Machine, bool MinGW, ArrayRef< COFFShortExport > NativeExports = std::nullopt)
Writes a COFF import library containing entries described by the Exports array.
For hybrid targets such as ARM64EC, additional native entry points can be exposed using the NativeExports parameter. When NativeExports is used, the output import library will expose these native ARM64 imports alongside the entries described in the Exports array. Such a library can be used for linking both ARM64EC and pure ARM64 objects, and the linker will pick only the exports relevant to the target platform. For non-hybrid targets, the NativeExports parameter should not be used.
Definition at line 659 of file COFFImportFile.cpp.
References applyNameType(), D, E, llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::Export, llvm::sys::path::filename(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::getArm64ECDemangledFunctionName(), llvm::getArm64ECMangledFunctionName(), getNameType(), llvm::COFF::IMAGE_FILE_MACHINE_ARM64, llvm::COFF::IMAGE_FILE_MACHINE_ARM64EC, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::COFF::IMPORT_CODE, llvm::COFF::IMPORT_CONST, llvm::COFF::IMPORT_DATA, llvm::COFF::IMPORT_NAME, llvm::COFF::IMPORT_NAME_EXPORTAS, llvm::COFF::IMPORT_NAME_NOPREFIX, llvm::COFF::IMPORT_NAME_UNDECORATE, llvm::COFF::IMPORT_ORDINAL, llvm::COFF::isArm64EC(), llvm::object::Archive::K_COFF, Machine, Name, llvm::NormalSymtab, llvm::SmallVectorTemplateBase< T, bool >::push_back(), replace(), llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::writeArchive().
Referenced by llvm::dlltoolDriverMain(), and llvm::libDriverMain().
writeStringTable()
static void llvm::object::writeStringTable (std::vector< uint8_t > & B, ArrayRef< const std::string_view > Strings) static
Definition at line 145 of file COFFImportFile.cpp.
References B, llvm::Length, llvm::Offset, and llvm::support::endian::write32le().
writeUniversalBinary()
Error llvm::object::writeUniversalBinary (ArrayRef< Slice > Slices, StringRef OutputFileName, FatHeaderType FatHeader = FatHeaderType::FatHeader)
Definition at line 352 of file MachOUniversalWriter.cpp.
References llvm::sys::fs::all_exe, llvm::sys::fs::all_read, llvm::sys::fs::all_write, llvm::any_of(), llvm::sys::fs::can_execute(), llvm::sys::fs::TempFile::create(), E, llvm::object::Slice::getBinary(), llvm::object::Binary::getFileName(), llvm::joinErrors(), llvm::Expected< T >::takeError(), and writeUniversalBinaryToStream().
writeUniversalBinaryToStream()
Error llvm::object::writeUniversalBinaryToStream (ArrayRef< Slice > Slices, raw_ostream & Out, FatHeaderType FatHeader = FatHeaderType::FatHeader)
Definition at line 331 of file MachOUniversalWriter.cpp.
References Fat64Header, llvm::MachO::FAT_MAGIC, llvm::MachO::FAT_MAGIC_64, FatHeader, llvm_unreachable, llvm::MachO::fat_header::nfat_arch, llvm::ArrayRef< T >::size(), and writeUniversalArchsToStream().
Referenced by llvm::objcopy::macho::executeObjcopyOnMachOUniversalBinary(), and writeUniversalBinary().
writeWindowsResourceCOFF()
Expected< std::unique_ptr< MemoryBuffer > > llvm::object::writeWindowsResourceCOFF (llvm::COFF::MachineTypes MachineType, const WindowsResourceParser & Parser, uint32_t TimeDateStamp)
Definition at line 1003 of file WindowsResource.cpp.
References E, llvm::Error::success(), and llvm::object::WindowsResourceCOFFWriter::write().
Variable Documentation
ArchiveMagic
const char llvm::object::ArchiveMagic[] = "!<arch>\n"
Definition at line 33 of file Archive.h.
Referenced by llvm::object::Archive::Archive(), and llvm::object::Archive::getArchiveMagicLen().
BigArchiveMagic
const char llvm::object::BigArchiveMagic[] = "<bigaf>\n"
Definition at line 35 of file Archive.h.
Referenced by llvm::object::Archive::Archive(), llvm::object::Archive::create(), and llvm::object::Archive::getArchiveMagicLen().
ElfSymbolTypes
const EnumEntry< unsigned > llvm::object::ElfSymbolTypes extern
Initial value:
= {
    {"None", "NOTYPE", ELF::STT_NOTYPE},
    {"Object", "OBJECT", ELF::STT_OBJECT},
    {"Function", "FUNC", ELF::STT_FUNC},
    {"Section", "SECTION", ELF::STT_SECTION},
    {"File", "FILE", ELF::STT_FILE},
    {"Common", "COMMON", ELF::STT_COMMON},
    {"TLS", "TLS", ELF::STT_TLS},
    {"Unknown", "<unknown>: 7", 7},
    {"Unknown", "<unknown>: 8", 8},
    {"Unknown", "<unknown>: 9", 9},
    {"GNU_IFunc", "IFUNC", ELF::STT_GNU_IFUNC},
    {"OS Specific", "<OS specific>: 11", 11},
    {"OS Specific", "<OS specific>: 12", 12},
    {"Proc Specific", "<processor specific>: 13", 13},
    {"Proc Specific", "<processor specific>: 14", 14},
    {"Proc Specific", "<processor specific>: 15", 15}
}
Definition at line 41 of file ELFObjectFile.cpp.
Referenced by llvm::object::ELFSymbolRef::getELFTypeName().
FunctionSym
const uint8_t llvm::object::FunctionSym = 0x20 static
Definition at line 26 of file XCOFFObjectFile.cpp.
Referenced by llvm::object::XCOFFSymbolRef::isFunction().
ImportDescriptorPrefix
std::string_view llvm::object::ImportDescriptorPrefix = "__IMPORT_DESCRIPTOR_" constexpr
Definition at line 30 of file COFFImportFile.h.
Referenced by isImportDescriptor().
MIN_HEADER_SIZE
const uint32_t llvm::object::MIN_HEADER_SIZE = 7 * sizeof(uint32_t) + 2 * sizeof(uint16_t)
Definition at line 44 of file WindowsResource.cpp.
NoRelMask
const uint16_t llvm::object::NoRelMask = 0x0001 static
Definition at line 27 of file XCOFFObjectFile.cpp.
Referenced by llvm::object::XCOFFObjectFile::isRelocatableObject().
NullImportDescriptorSymbolName
std::string_view llvm::object::NullImportDescriptorSymbolName constexpr
Initial value:
=
    "__NULL_IMPORT_DESCRIPTOR"
Definition at line 31 of file COFFImportFile.h.
Referenced by isImportDescriptor().
NullThunkDataPrefix
std::string_view llvm::object::NullThunkDataPrefix = "\x7f" constexpr
Definition at line 33 of file COFFImportFile.h.
Referenced by isImportDescriptor().
NullThunkDataSuffix
std::string_view llvm::object::NullThunkDataSuffix = "_NULL_THUNK_DATA" constexpr
Definition at line 34 of file COFFImportFile.h.
Referenced by isImportDescriptor().
NumElfSymbolTypes
int llvm::object::NumElfSymbolTypes = 16 constexpr
Definition at line 46 of file ELFObjectFile.h.
SECTION_ALIGNMENT
const uint32_t llvm::object::SECTION_ALIGNMENT = sizeof(uint64_t)
Definition at line 48 of file WindowsResource.cpp.
SymbolAuxTypeOffset
const size_t llvm::object::SymbolAuxTypeOffset = 17 static
Definition at line 28 of file XCOFFObjectFile.cpp.
Referenced by llvm::object::XCOFFObjectFile::getSymbolAuxType().
ThinArchiveMagic
const char llvm::object::ThinArchiveMagic[] = "!<thin>\n"
Definition at line 34 of file Archive.h.
Referenced by llvm::object::Archive::Archive(), and llvm::object::Archive::getArchiveMagicLen().
WIN_RES_DATA_ALIGNMENT
const uint32_t llvm::object::WIN_RES_DATA_ALIGNMENT = 4
Definition at line 57 of file WindowsResource.h.
WIN_RES_HEADER_ALIGNMENT
const uint32_t llvm::object::WIN_RES_HEADER_ALIGNMENT = 4
Definition at line 56 of file WindowsResource.h.
WIN_RES_MAGIC_SIZE
const size_t llvm::object::WIN_RES_MAGIC_SIZE = 16
Definition at line 54 of file WindowsResource.h.
Referenced by llvm::object::WindowsResource::createWindowsResource().
WIN_RES_NULL_ENTRY_SIZE
const size_t llvm::object::WIN_RES_NULL_ENTRY_SIZE = 16
Definition at line 55 of file WindowsResource.h.
Referenced by llvm::object::WindowsResource::createWindowsResource().
WIN_RES_PURE_MOVEABLE
const uint16_t llvm::object::WIN_RES_PURE_MOVEABLE = 0x0030
Definition at line 58 of file WindowsResource.h.