LLVM: llvm::DWARFYAML Namespace Reference
llvm::DWARFYAML Namespace Reference
Classes
struct Abbrev
struct AbbrevTable
struct AddrTableEntry
struct ARange
struct ARangeDescriptor
struct AttributeAbbrev
struct Data
struct DebugNameAbbreviation
struct DebugNameEntry
struct DebugNamesSection
struct DWARFContext
Class that contains helpful context information when mapping YAML into DWARF data structures.
struct DWARFOperation
struct Entry
struct File
struct FormValue
struct IdxForm
struct LineTable
struct LineTableOpcode
struct ListEntries
struct ListTable
struct LoclistEntry
struct PubEntry
struct PubSection
struct RangeEntry
Class that describes a range list entry, or a base address selection entry within a range list in the .debug_ranges section.
struct Ranges
Class that describes a single range list inside the .debug_ranges section.
struct RnglistEntry
struct SegAddrPair
struct StringOffsetsTable
struct Unit
Functions
Error emitDebugAbbrev (raw_ostream &OS, const Data &DI)
Error emitDebugStr (raw_ostream &OS, const Data &DI)
Error emitDebugAranges (raw_ostream &OS, const Data &DI)
Error emitDebugRanges (raw_ostream &OS, const Data &DI)
Error emitDebugPubnames (raw_ostream &OS, const Data &DI)
Error emitDebugPubtypes (raw_ostream &OS, const Data &DI)
Error emitDebugGNUPubnames (raw_ostream &OS, const Data &DI)
Error emitDebugGNUPubtypes (raw_ostream &OS, const Data &DI)
Error emitDebugInfo (raw_ostream &OS, const Data &DI)
Error emitDebugLine (raw_ostream &OS, const Data &DI)
Error emitDebugAddr (raw_ostream &OS, const Data &DI)
Error emitDebugStrOffsets (raw_ostream &OS, const Data &DI)
Error emitDebugRnglists (raw_ostream &OS, const Data &DI)
Error emitDebugLoclists (raw_ostream &OS, const Data &DI)
Error emitDebugNames (raw_ostream &OS, const Data &DI)
std::function< Error(raw_ostream &, const Data &)> getDWARFEmitterByName (StringRef SecName)
Expected< StringMap< std::unique_ptr< MemoryBuffer > > > emitDebugSections (StringRef YAMLString, bool IsLittleEndian=sys::IsLittleEndianHost, bool Is64BitAddrSize=true)
Function Documentation
emitDebugAbbrev()
Error llvm::DWARFYAML::emitDebugAbbrev (raw_ostream & OS, const Data & DI)
Definition at line 132 of file DWARFEmitter.cpp.
References llvm::StringRef::data(), llvm::DWARFYAML::Data::DebugAbbrev, llvm::DWARFYAML::Data::getAbbrevTableContentByIndex(), I, OS, llvm::StringRef::size(), llvm::Error::success(), and llvm::raw_ostream::write().
Referenced by getDWARFEmitterByName().
emitDebugAddr()
Error llvm::DWARFYAML::emitDebugAddr (raw_ostream & OS, const Data & DI)
Definition at line 631 of file DWARFEmitter.cpp.
References llvm::DWARFYAML::SegAddrPair::Address, llvm::c_str(), llvm::createStringError(), llvm::DWARFYAML::Data::DebugAddr, llvm::DWARFYAML::Data::Is64BitAddrSize, llvm::DWARFYAML::Data::IsLittleEndian, llvm::Length, llvm::not_supported, OS, llvm::DWARFYAML::SegAddrPair::Segment, llvm::Error::success(), llvm::dwarf::toString(), writeInitialLength(), writeInteger(), and writeVariableSizedInteger().
Referenced by getDWARFEmitterByName().
emitDebugAranges()
Error llvm::DWARFYAML::emitDebugAranges (raw_ostream & OS, const Data & DI)
Definition at line 141 of file DWARFEmitter.cpp.
References llvm::alignTo(), assert(), llvm::c_str(), llvm::cantFail(), llvm::createStringError(), llvm::DWARFYAML::Data::DebugAranges, llvm::dwarf::DWARF64, llvm::DWARFYAML::Data::Is64BitAddrSize, llvm::DWARFYAML::Data::IsLittleEndian, llvm::Length, llvm::not_supported, OS, Range, llvm::Error::success(), llvm::dwarf::toString(), writeDWARFOffset(), writeInitialLength(), writeInteger(), writeVariableSizedInteger(), and ZeroFillBytes().
Referenced by getDWARFEmitterByName().
emitDebugGNUPubnames()
Error llvm::DWARFYAML::emitDebugGNUPubnames (raw_ostream & OS, const Data & DI)
Definition at line 253 of file DWARFEmitter.cpp.
References assert(), emitPubSection(), llvm::DWARFYAML::Data::GNUPubNames, llvm::DWARFYAML::Data::IsLittleEndian, and OS.
Referenced by getDWARFEmitterByName().
emitDebugGNUPubtypes()
Error llvm::DWARFYAML::emitDebugGNUPubtypes (raw_ostream & OS, const Data & DI)
Definition at line 259 of file DWARFEmitter.cpp.
References assert(), emitPubSection(), llvm::DWARFYAML::Data::GNUPubTypes, llvm::DWARFYAML::Data::IsLittleEndian, and OS.
Referenced by getDWARFEmitterByName().
emitDebugInfo()
Error llvm::DWARFYAML::emitDebugInfo (raw_ostream & OS, const Data & DI)
Definition at line 407 of file DWARFEmitter.cpp.
References llvm::DWARFYAML::Unit::AbbrevTableID, llvm::DWARFYAML::Unit::AbbrOffset, llvm::DWARFYAML::Unit::AddrSize, llvm::DWARFYAML::Data::CompileUnits, llvm::consumeError(), llvm::DWARFYAML::Unit::Entries, llvm::DWARFYAML::Unit::Format, llvm::DWARFYAML::Data::getAbbrevTableInfoByID(), llvm::dwarf::FormParams::getDwarfOffsetByteSize(), I, llvm::DWARFYAML::Data::Is64BitAddrSize, llvm::DWARFYAML::Data::IsLittleEndian, llvm::DWARFYAML::Unit::Length, llvm::Length, OS, llvm::Error::success(), llvm::DWARFYAML::Unit::Type, llvm::DWARFYAML::Unit::Version, llvm::raw_ostream::write(), writeDIE(), writeDWARFOffset(), writeInitialLength(), and writeInteger().
Referenced by getDWARFEmitterByName().
emitDebugLine()
Error llvm::DWARFYAML::emitDebugLine (raw_ostream & OS, const Data & DI)
Definition at line 570 of file DWARFEmitter.cpp.
References llvm::StringRef::data(), llvm::DWARFYAML::Data::DebugLines, llvm::DWARFYAML::LineTable::DefaultIsStmt, llvm::dwarf::DWARF64, emitFileEntry(), llvm::DWARFYAML::LineTable::Files, llvm::DWARFYAML::LineTable::Format, getStandardOpcodeLengths(), llvm::DWARFYAML::LineTable::IncludeDirs, llvm::DWARFYAML::Data::Is64BitAddrSize, llvm::DWARFYAML::Data::IsLittleEndian, llvm::DWARFYAML::LineTable::Length, llvm::Length, llvm::DWARFYAML::LineTable::LineBase, llvm::DWARFYAML::LineTable::LineRange, llvm::DWARFYAML::LineTable::MaxOpsPerInst, llvm::DWARFYAML::LineTable::MinInstLength, llvm::DWARFYAML::LineTable::OpcodeBase, llvm::DWARFYAML::LineTable::Opcodes, OS, llvm::DWARFYAML::LineTable::PrologueLength, llvm::StringRef::size(), llvm::DWARFYAML::LineTable::StandardOpcodeLengths, llvm::Error::success(), llvm::DWARFYAML::LineTable::Version, llvm::raw_ostream::write(), writeDWARFOffset(), writeInitialLength(), writeInteger(), and writeLineTableOpcode().
Referenced by getDWARFEmitterByName().
emitDebugLoclists()
Error llvm::DWARFYAML::emitDebugLoclists (raw_ostream & OS, const Data & DI)
Definition at line 1190 of file DWARFEmitter.cpp.
References assert(), llvm::DWARFYAML::Data::DebugLoclists, llvm::DWARFYAML::Data::Is64BitAddrSize, llvm::DWARFYAML::Data::IsLittleEndian, OS, and writeDWARFLists().
Referenced by getDWARFEmitterByName().
emitDebugNames()
Error llvm::DWARFYAML::emitDebugNames (raw_ostream & OS, const Data & DI)
Definition at line 848 of file DWARFEmitter.cpp.
References assert(), llvm::dwarf_linker::DebugNames, llvm::DWARFYAML::Data::DebugNames, llvm::DWARFYAML::Data::IsLittleEndian, OS, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::raw_ostream::write().
Referenced by getDWARFEmitterByName().
emitDebugPubnames()
Error llvm::DWARFYAML::emitDebugPubnames (raw_ostream & OS, const Data & DI)
Definition at line 243 of file DWARFEmitter.cpp.
References assert(), emitPubSection(), llvm::DWARFYAML::Data::IsLittleEndian, OS, and llvm::DWARFYAML::Data::PubNames.
Referenced by getDWARFEmitterByName().
emitDebugPubtypes()
Error llvm::DWARFYAML::emitDebugPubtypes (raw_ostream & OS, const Data & DI)
Definition at line 248 of file DWARFEmitter.cpp.
References assert(), emitPubSection(), llvm::DWARFYAML::Data::IsLittleEndian, OS, and llvm::DWARFYAML::Data::PubTypes.
Referenced by getDWARFEmitterByName().
emitDebugRanges()
Error llvm::DWARFYAML::emitDebugRanges (raw_ostream & OS, const Data & DI)
Definition at line 190 of file DWARFEmitter.cpp.
References llvm::c_str(), llvm::cantFail(), llvm::createStringError(), llvm::DWARFYAML::Data::DebugRanges, llvm::invalid_argument, llvm::DWARFYAML::Data::Is64BitAddrSize, llvm::DWARFYAML::Data::IsLittleEndian, llvm::not_supported, OS, llvm::Error::success(), llvm::raw_ostream::tell(), llvm::dwarf::toString(), llvm::Twine::utohexstr(), writeVariableSizedInteger(), and ZeroFillBytes().
Referenced by getDWARFEmitterByName().
emitDebugRnglists()
Error llvm::DWARFYAML::emitDebugRnglists (raw_ostream & OS, const Data & DI)
Definition at line 1184 of file DWARFEmitter.cpp.
References assert(), llvm::DWARFYAML::Data::DebugRnglists, llvm::DWARFYAML::Data::Is64BitAddrSize, llvm::DWARFYAML::Data::IsLittleEndian, OS, and writeDWARFLists().
Referenced by getDWARFEmitterByName().
emitDebugSections()
Expected< StringMap< std::unique_ptr< MemoryBuffer > > > llvm::DWARFYAML::emitDebugSections (StringRef YAMLString, bool IsLittleEndian = sys::IsLittleEndianHost, bool Is64BitAddrSize = true)
Definition at line 1242 of file DWARFEmitter.cpp.
References llvm::createStringError(), emitDebugSectionImpl(), llvm::SMDiagnostic::getMessage(), llvm::DWARFYAML::Data::getNonEmptySectionNames(), llvm::DWARFYAML::Data::Is64BitAddrSize, llvm::DWARFYAML::Data::IsLittleEndian, llvm::joinErrors(), and llvm::Error::success().
emitDebugStr()
Error llvm::DWARFYAML::emitDebugStr (raw_ostream & OS, const Data & DI)
Definition at line 88 of file DWARFEmitter.cpp.
References llvm::DWARFYAML::Data::DebugStrings, OS, llvm::Error::success(), and llvm::raw_ostream::write().
Referenced by getDWARFEmitterByName().
emitDebugStrOffsets()
Error llvm::DWARFYAML::emitDebugStrOffsets (raw_ostream & OS, const Data & DI)
Definition at line 672 of file DWARFEmitter.cpp.
References assert(), llvm::DWARFYAML::Data::DebugStrOffsets, llvm::dwarf::DWARF64, llvm::DWARFYAML::StringOffsetsTable::Format, llvm::DWARFYAML::Data::IsLittleEndian, llvm::DWARFYAML::StringOffsetsTable::Length, llvm::Length, llvm::Offset, llvm::DWARFYAML::StringOffsetsTable::Offsets, OS, llvm::DWARFYAML::StringOffsetsTable::Padding, llvm::Error::success(), llvm::DWARFYAML::StringOffsetsTable::Version, writeDWARFOffset(), writeInitialLength(), and writeInteger().
Referenced by getDWARFEmitterByName().
getDWARFEmitterByName()
std::function< Error(raw_ostream &, const DWARFYAML::Data &)> llvm::DWARFYAML::getDWARFEmitterByName (StringRef SecName)
Definition at line 1197 of file DWARFEmitter.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::createStringError(), llvm::StringSwitch< T, R >::Default(), emitDebugAbbrev(), emitDebugAddr(), emitDebugAranges(), emitDebugGNUPubnames(), emitDebugGNUPubtypes(), emitDebugInfo(), emitDebugLine(), emitDebugLoclists(), emitDebugNames(), emitDebugPubnames(), emitDebugPubtypes(), emitDebugRanges(), emitDebugRnglists(), emitDebugStr(), emitDebugStrOffsets(), llvm::Error, and llvm::not_supported.
Referenced by emitDebugSectionImpl(), and emitDWARF().