LLVM: llvm::MachO::DylibReader Namespace Reference
llvm::MachO::DylibReader Namespace Reference
Defines the MachO Dynamic Library Reader.
Classes
struct ParseOption
Typedefs
using SymbolToSourceLocMap = llvm::StringMap<RecordLoc>
Functions
Expected< Records > readFile (MemoryBufferRef Buffer, const ParseOption &Opt)
Parse Mach-O dynamic libraries to extract TAPI attributes.
Expected< std::unique_ptr< InterfaceFile > > get (MemoryBufferRef Buffer)
Get TAPI file representation of binary dylib.
SymbolToSourceLocMap accumulateSourceLocFromDSYM (const StringRef DSYM, const Target &T)
Get the source location for each symbol from dylib.
Detailed Description
Defines the MachO Dynamic Library Reader.
Typedef Documentation
SymbolToSourceLocMap
using llvm::MachO::DylibReader::SymbolToSourceLocMap = llvm::StringMap<RecordLoc>
Definition at line 47 of file DylibReader.h.
Function Documentation
accumulateSourceLocFromDSYM()
SymbolToSourceLocMap llvm::MachO::DylibReader::accumulateSourceLocFromDSYM (const StringRef DSYM, const Target & T)
Get the source location for each symbol from dylib.
Parameters
DSYM Path to DSYM file.
T Requested target slice for dylib.
Definition at line 494 of file DylibReader.cpp.
References accumulateLocs(), llvm::consumeError(), llvm::DWARFContext::create(), llvm::object::createBinary(), DWARFErrorHandler(), llvm::dyn_cast(), llvm::object::MachOObjectFile::findDsymObjectMembers(), llvm::MachO::getArchitectureName(), and llvm::MemoryBuffer::getFile().
get()
Expected< std::unique_ptr< InterfaceFile > > llvm::MachO::DylibReader::get (MemoryBufferRef Buffer)
Get TAPI file representation of binary dylib.
Parameters
Buffer Data that points to dylib.
Definition at line 428 of file DylibReader.cpp.
References llvm::MachO::convertToInterfaceFile(), Options, and readFile().
readFile()
Expected< Records > llvm::MachO::DylibReader::readFile (MemoryBufferRef Buffer, const ParseOption & Opt)
Parse Mach-O dynamic libraries to extract TAPI attributes.
Parameters
Buffer Data that points to dylib.
Options Determines which attributes to extract.
Returns
List of record slices.
Definition at line 353 of file DylibReader.cpp.
References llvm::MachO::AK_unknown, llvm::MachO::DylibReader::ParseOption::Archs, assert(), llvm::Function::back(), llvm::Bin, llvm::cast(), constructTriples(), llvm::consumeError(), llvm::object::createBinary(), llvm::dyn_cast(), llvm::Function::empty(), llvm::MachO::getArchitectureFromCpuType(), llvm::MemoryBufferRef::getBufferIdentifier(), llvm::MachO::ArchitectureSet::has(), llvm::isa(), load, llvm::make_error(), llvm::MachO::mapToPlatformType(), llvm::MachO::MH_BUNDLE, llvm::MachO::MH_DYLIB, llvm::MachO::MH_DYLIB_STUB, and Results.
Referenced by get().