LLVM: llvm::support::endian Namespace Reference
llvm::support::endian Namespace Reference
Classes
struct Writer
Adapter to write values to a stream in a particular byte order.
Typedefs
template<typename value_type >
using make_unsigned_t = std::make_unsigned_t<value_type>
Functions
template<typename value_type >
value_type byte_swap (value_type value, endianness endian)
template<typename value_type , endianness endian>
value_type byte_swap (value_type value)
Swap the bytes of value to match the given endianness.
template<typename value_type , std::size_t alignment = unaligned>
value_type read (const void *memory, endianness endian)
Read a value of a particular endianness from memory.
template<typename value_type , endianness endian, std::size_t alignment>
value_type read (const void *memory)
template<typename value_type , std::size_t alignment = unaligned, typename CharT >
value_type readNext (const CharT *&memory, endianness endian)
Read a value of a particular endianness from a buffer, and increment the buffer past that value.
template<typename value_type , endianness endian, std::size_t alignment = unaligned, typename CharT >
value_type readNext (const CharT *&memory)
template<typename value_type , std::size_t alignment = unaligned>
void write (void *memory, value_type value, endianness endian)
Write a value to memory with a particular endianness.
template<typename value_type , endianness endian, std::size_t alignment>
void write (void *memory, value_type value)
template<typename value_type , std::size_t alignment = unaligned, typename CharT >
void writeNext (CharT *&memory, value_type value, endianness endian)
Write a value of a particular endianness, and increment the buffer past that value.
template<typename value_type , endianness endian, std::size_t alignment = unaligned, typename CharT >
void writeNext (CharT *&memory, value_type value)
template<typename value_type , endianness endian, std::size_t alignment>
value_type readAtBitAlignment (const void *memory, uint64_t startBit)
Read a value of a particular endianness from memory, for a location that starts at the given bit offset within the first byte.
template<typename value_type , endianness endian, std::size_t alignment>
void writeAtBitAlignment (void *memory, value_type value, uint64_t startBit)
Write a value to memory with a particular endianness, for a location that starts at the given bit offset within the first byte.
template<typename T , endianness E>
T read (const void *P)
uint16_t read16 (const void *P, endianness E)
uint32_t read32 (const void *P, endianness E)
uint64_t read64 (const void *P, endianness E)
template<endianness E>
uint16_t read16 (const void *P)
template<endianness E>
uint32_t read32 (const void *P)
template<endianness E>
uint64_t read64 (const void *P)
uint16_t read16le (const void *P)
uint32_t read32le (const void *P)
uint64_t read64le (const void *P)
uint16_t read16be (const void *P)
uint32_t read32be (const void *P)
uint64_t read64be (const void *P)
template<typename T , endianness E>
void write (void *P, T V)
void write16 (void *P, uint16_t V, endianness E)
void write32 (void *P, uint32_t V, endianness E)
void write64 (void *P, uint64_t V, endianness E)
template<endianness E>
void write16 (void *P, uint16_t V)
template<endianness E>
void write32 (void *P, uint32_t V)
template<endianness E>
void write64 (void *P, uint64_t V)
void write16le (void *P, uint16_t V)
void write32le (void *P, uint32_t V)
void write64le (void *P, uint64_t V)
void write16be (void *P, uint16_t V)
void write32be (void *P, uint32_t V)
void write64be (void *P, uint64_t V)
template<typename value_type >
void write_array (raw_ostream &os, ArrayRef< value_type > values, endianness endian)
template<typename value_type >
void write (raw_ostream &os, value_type value, endianness endian)
template<>
void write< float > (raw_ostream &os, float value, endianness endian)
template<>
void write< double > (raw_ostream &os, double value, endianness endian)
template<typename value_type >
void write (raw_ostream &os, ArrayRef< value_type > vals, endianness endian)
template<typename value_type >
void write (SmallVectorImpl< char > &Out, value_type V, endianness E)
Typedef Documentation
make_unsigned_t
template<typename value_type > using llvm::support::endian::make_unsigned_t = std::make_unsigned_t<value_type>
Definition at line 122 of file Endian.h.
Function Documentation
byte_swap() [1/2]
template<typename value_type , endianness endian> value_type llvm::support::endian::byte_swap (value_type value) inline nodiscard
Swap the bytes of value to match the given endianness.
Definition at line 52 of file Endian.h.
References byte_swap().
byte_swap() [2/2]
template<typename value_type > value_type llvm::support::endian::byte_swap (value_type value, endianness endian) inline nodiscard
Definition at line 44 of file Endian.h.
References llvm::native, and llvm::sys::swapByteOrder().
Referenced by llvm::HashBuilder< HasherT, Endianness >::adjustForEndiannessAndAdd(), byte_swap(), llvm::coverage::BinaryCoverageReader::create(), llvm::MCStreamer::emitIntValue(), llvm::gsym::FileWriter::fixup32(), llvm::coverage::accessors::getDataSize(), llvm::coverage::accessors::getFuncHash(), llvm::coverage::accessors::getFuncNameRef(), loadTestingFormat(), llvm::ProfOStream::patch(), read(), readAtBitAlignment(), llvm::M68k::swapWord(), llvm::coverage::TestingFormatWriter::write(), write(), write(), write(), write_array(), writeAtBitAlignment(), llvm::gsym::FileWriter::writeU16(), llvm::gsym::FileWriter::writeU32(), and llvm::gsym::FileWriter::writeU64().
read() [1/3]
template<typename value_type , endianness endian, std::size_t alignment> value_type llvm::support::endian::read (const void * memory) inline nodiscard
Definition at line 69 of file Endian.h.
References read().
read() [2/3]
template<typename value_type , std::size_t alignment = unaligned> value_type llvm::support::endian::read (const void * memory, endianness endian) inline nodiscard
Read a value of a particular endianness from memory.
Definition at line 58 of file Endian.h.
References byte_swap(), and LLVM_ASSUME_ALIGNED.
Referenced by consume(), llvm::sys::fs::copy_file_internal(), eat12Bytes(), eatBytes(), llvm::SimpleBitstreamCursor::fillCurWord(), llvm::object::Record::get(), llvm::IndexedInstrProfReader::getFunctionBitmap(), llvm::IndexedInstrProfReader::hasFormat(), llvm::MD5::MD5Result::high(), llvm::MD5::MD5Result::low(), llvm::sys::fs::md5_contents(), llvm::support::detail::packed_endian_specific_integral< ValueType, Endian, Alignment, ALIGN >::operator value_type(), llvm::support::detail::packed_endian_specific_integral< ValueType, Endian, Alignment, ALIGN >::ref::operator value_type(), llvm::memprof::LinearCallStackIdConverter::operator()(), parseImmediate(), parseStrTabSize(), parseVersion(), llvm::msgpack::Reader::read(), read(), read16(), read16(), read32(), read32(), read64(), read64(), readAtBitAlignment(), llvm::BinaryStreamReader::readInteger(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readNameTableSec(), and readNext().
read() [3/3]
template<typename T , endianness E> T llvm::support::endian::read (const void * P) inline nodiscard
Definition at line 398 of file Endian.h.
References P.
read16() [1/2]
template<endianness E> uint16_t llvm::support::endian::read16 (const void * P) inline nodiscard
Definition at line 412 of file Endian.h.
References P, and read().
read16() [2/2]
uint16_t llvm::support::endian::read16 (const void * P, endianness E) inline nodiscard
Definition at line 402 of file Endian.h.
References P, and read().
Referenced by llvm::AMDGPUDisassembler::decodeKernelDescriptor(), llvm::dwarf_linker::parallel::SectionDescriptor::getIntVal(), read16be(), and read16le().
read16be()
uint16_t llvm::support::endian::read16be (const void * P) inline nodiscard
Definition at line 431 of file Endian.h.
References P, and read16().
Referenced by M68kDisassembler::getInstruction().
read16le()
uint16_t llvm::support::endian::read16le (const void * P) inline nodiscard
Definition at line 422 of file Endian.h.
References P, and read16().
Referenced by llvm::add16(), discoverTypeIndices(), llvm::object::Archive::ec_symbols(), getEncodedIntegerLength(), llvm::object::Archive::Symbol::getMember(), handleFieldList(), handleMethodOverloadList(), and handleOneMethod().
read32() [1/2]
template<endianness E> uint32_t llvm::support::endian::read32 (const void * P) inline nodiscard
Definition at line 415 of file Endian.h.
References P, and read().
read32() [2/2]
uint32_t llvm::support::endian::read32 (const void * P, endianness E) inline nodiscard
Definition at line 405 of file Endian.h.
References P, and read().
Referenced by llvm::jitlink::ppc64::applyFixup(), llvm::dwarf_linker::parallel::SectionDescriptor::getIntVal(), read32be(), read32le(), llvm::jitlink::aarch32::readAddendData(), and verifyNoteSection().
read32be()
uint32_t llvm::support::endian::read32be (const void * P) inline nodiscard
Definition at line 434 of file Endian.h.
References P, and read32().
Referenced by llvm::jitlink::aarch32::applyFixupData(), llvm::object::doesXCOFFTracebackTableBegin(), llvm::object::Archive::Symbol::getMember(), llvm::object::Archive::getNumberOfSymbols(), llvm::object::Archive::symbol_begin(), llvm::SHA1::update(), and llvm::SHA256::update().
read32le()
uint32_t llvm::support::endian::read32le (const void * P) inline nodiscard
Definition at line 425 of file Endian.h.
References P, and read32().
Referenced by analyzeHeader(), llvm::jitlink::aarch32::applyFixupData(), discoverTypeIndices(), llvm::object::Archive::ec_symbols(), llvm::X86_MC::findX86_64PltEntries(), llvm::X86_MC::findX86PltEntries(), llvm::object::Archive::Symbol::getMember(), llvm::object::Archive::Symbol::getNext(), llvm::object::Archive::getNumberOfECSymbols(), llvm::object::Archive::getNumberOfSymbols(), handlePointer(), llvm::identify_magic(), llvm::or32le(), or32le(), llvm::RuntimeDyldCOFFAArch64::processRelocationRef(), readUint32(), llvm::jitlink::relaxCall(), llvm::RuntimeDyldCOFFAArch64::resolveRelocation(), llvm::SkipBitcodeWrapperHeader(), llvm::object::Archive::symbol_begin(), llvm::write32AArch64Addr(), write32AArch64Addr(), llvm::write32AArch64Imm(), llvm::write32AArch64Ldr(), XXH3_len_1to3_128b(), XXH3_len_1to3_64b(), XXH3_len_4to8_128b(), XXH3_len_4to8_64b(), and llvm::xxHash64().
read64() [1/2]
template<endianness E> uint64_t llvm::support::endian::read64 (const void * P) inline nodiscard
Definition at line 418 of file Endian.h.
References P, and read().
read64() [2/2]
uint64_t llvm::support::endian::read64 (const void * P, endianness E) inline nodiscard
Definition at line 408 of file Endian.h.
References P, and read().
Referenced by llvm::dwarf_linker::parallel::SectionDescriptor::getIntVal(), llvm::CodeGenCoverage::parse(), read64be(), read64le(), and llvm::jitlink::ppc64::readPrefixedInstruction().
read64be()
uint64_t llvm::support::endian::read64be (const void * P) inline nodiscard
Definition at line 437 of file Endian.h.
References P, and read64().
Referenced by appendGlobalSymbolTableInfo(), llvm::object::Archive::Symbol::getMember(), llvm::object::Archive::getNumberOfSymbols(), and llvm::object::Archive::symbol_begin().
read64le()
uint64_t llvm::support::endian::read64le (const void * P) inline nodiscard
Definition at line 428 of file Endian.h.
References P, and read64().
Referenced by llvm::object::Archive::Symbol::getMember(), llvm::object::Archive::getNumberOfSymbols(), llvm::getPointerAuthStableSipHash(), llvm::RuntimeDyldCOFFAArch64::processRelocationRef(), llvm::sampleprof::SampleProfileReaderBinary::readSampleContextFromTable(), llvm::object::Archive::symbol_begin(), XXH128_mix32B(), XXH3_accumulate_512_scalar(), XXH3_len_0to16_128b(), XXH3_len_0to16_64b(), XXH3_len_4to8_128b(), XXH3_len_4to8_64b(), XXH3_len_9to16_128b(), XXH3_len_9to16_64b(), XXH3_mix16B(), XXH3_mix2Accs(), XXH3_scrambleAcc_scalar(), and llvm::xxHash64().
readAtBitAlignment()
template<typename value_type , endianness endian, std::size_t alignment> value_type llvm::support::endian::readAtBitAlignment (const void * memory, uint64_t startBit) inline nodiscard
Read a value of a particular endianness from memory, for a location that starts at the given bit offset within the first byte.
Definition at line 127 of file Endian.h.
References assert(), byte_swap(), LLVM_ASSUME_ALIGNED, and read().
Referenced by llvm::BitstreamWriter::BackpatchByte().
readNext() [1/2]
template<typename value_type , endianness endian, std::size_t alignment = unaligned, typename CharT > value_type llvm::support::endian::readNext (const CharT *& memory) inline nodiscard
Definition at line 86 of file Endian.h.
References readNext().
readNext() [2/2]
template<typename value_type , std::size_t alignment = unaligned, typename CharT > value_type llvm::support::endian::readNext (const CharT *& memory, endianness endian) inline nodiscard
Read a value of a particular endianness from a buffer, and increment the buffer past that value.
Definition at line 77 of file Endian.h.
References read().
Referenced by llvm::IndexedMemProfReader::deserialize(), llvm::memprof::Frame::deserialize(), llvm::OutlinedHashTreeRecord::deserialize(), llvm::memprof::deserializeV0(), llvm::memprof::deserializeV2(), llvm::memprof::deserializeV3(), llvm::OnDiskChainedHashTable< Info >::find_hashed(), llvm::memprof::LinearCallStackIdConverter::operator()(), readBinaryIdsInternal(), llvm::InstrProfLookupTrait::ReadData(), llvm::memprof::CallStackLookupTrait::ReadData(), llvm::IndexedInstrProf::Header::readFromBuffer(), llvm::IndexedInstrProfReader::readHeader(), llvm::memprof::CallStackLookupTrait::ReadKey(), llvm::memprof::FrameLookupTrait::ReadKey(), llvm::memprof::RecordLookupTrait::ReadKey(), llvm::InstrProfLookupTrait::ReadKeyDataLength(), llvm::memprof::CallStackLookupTrait::ReadKeyDataLength(), llvm::memprof::FrameLookupTrait::ReadKeyDataLength(), llvm::memprof::RecordLookupTrait::ReadKeyDataLength(), llvm::memprof::readMemProfSchema(), readNext(), llvm::OnDiskChainedHashTable< Info >::readNumBucketsAndEntries(), and llvm::sampleprof::SampleProfileReaderBinary::readUnencodedNumber().
write() [1/6]
template<typename value_type > void llvm::support::endian::write (raw_ostream & os, ArrayRef< value_type > vals, endianness endian) inline
Definition at line 54 of file EndianStream.h.
References write().
write() [2/6]
template<typename value_type > void llvm::support::endian::write (raw_ostream & os, value_type value, endianness endian) inline
Definition at line 37 of file EndianStream.h.
References byte_swap().
write() [3/6]
template<typename value_type > void llvm::support::endian::write (SmallVectorImpl< char > & Out, value_type V, endianness E) inline
Definition at line 61 of file EndianStream.h.
References llvm::SmallVectorImpl< T >::append(), and byte_swap().
write() [4/6]
template<typename value_type , endianness endian, std::size_t alignment> void llvm::support::endian::write (void * memory, value_type value) inline
Definition at line 102 of file Endian.h.
References write().
write() [5/6]
template<typename value_type , std::size_t alignment = unaligned> void llvm::support::endian::write (void * memory, value_type value, endianness endian) inline
Write a value to memory with a particular endianness.
Definition at line 92 of file Endian.h.
References byte_swap(), and LLVM_ASSUME_ALIGNED.
Referenced by llvm::dwarf_linker::parallel::SectionDescriptor::applyIntVal(), emitOperand(), llvm::MCDwarfFrameEmitter::encodeAdvanceLoc(), llvm::MipsMCCodeEmitter::encodeInstruction(), llvm::MSP430MCCodeEmitter::encodeInstruction(), llvm::PPCMCCodeEmitter::encodeInstruction(), llvm::HexagonMCCodeEmitter::encodeSingleInstruction(), llvm::MCContext::getELFSection(), operator<<(), llvm::support::detail::packed_endian_specific_integral< ValueType, Endian, Alignment, ALIGN >::operator=(), llvm::support::detail::packed_endian_specific_integral< ValueType, Endian, Alignment, ALIGN >::ref::operator=(), print(), printLE(), llvm::LoongArchAsmBackend::relaxDwarfCFA(), llvm::RISCVAsmBackend::relaxDwarfCFA(), llvm::LoongArchAsmBackend::relaxDwarfLineAddr(), llvm::RISCVAsmBackend::relaxDwarfLineAddr(), llvm::mcdxbc::PSVRuntimeInfo::write(), write(), write(), llvm::support::endian::Writer::write(), llvm::support::endian::Writer::write(), write16(), write16(), write32(), write32(), write64(), write64(), write< double >(), write< float >(), writeAtBitAlignment(), writeData(), writeFragment(), llvm::RuntimeDyldImpl::writeInt16BE(), llvm::RuntimeDyldImpl::writeInt32BE(), llvm::RuntimeDyldImpl::writeInt64BE(), llvm::BinaryStreamWriter::writeInteger(), writeNext(), llvm::ARMAsmBackend::writeNopData(), llvm::MachObjectWriter::writeObject(), and llvm::WinCOFFWriter::writeObject().
write() [6/6]
template<typename T , endianness E> void llvm::support::endian::write (void * P, T V) inline
Definition at line 441 of file Endian.h.
References P.
write16() [1/2]
template<endianness E> void llvm::support::endian::write16 (void * P, uint16_t V) inline
Definition at line 455 of file Endian.h.
References P, and write().
write16() [2/2]
void llvm::support::endian::write16 (void * P, uint16_t V, endianness E) inline
Definition at line 445 of file Endian.h.
References P, and write().
Referenced by llvm::jitlink::ppc64::relocateHalf16(), write16be(), and write16le().
write16be()
void llvm::support::endian::write16be (void * P, uint16_t V) inline
Definition at line 474 of file Endian.h.
References P, and write16().
write16le()
void llvm::support::endian::write16le (void * P, uint16_t V) inline
Definition at line 465 of file Endian.h.
References P, and write16().
Referenced by llvm::add16(), and llvm::jitlink::finalizeBlockRelax().
write32() [1/2]
template<endianness E> void llvm::support::endian::write32 (void * P, uint32_t V) inline
Definition at line 458 of file Endian.h.
References P, and write().
write32() [2/2]
void llvm::support::endian::write32 (void * P, uint32_t V, endianness E) inline
Definition at line 448 of file Endian.h.
References P, and write().
Referenced by llvm::jitlink::ppc64::applyFixup(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), write32be(), and write32le().
write32be()
void llvm::support::endian::write32be (void * P, uint32_t V) inline
Definition at line 477 of file Endian.h.
References P, and write32().
Referenced by llvm::jitlink::aarch32::applyFixupData(), and llvm::StringTableBuilder::write().
write32le()
void llvm::support::endian::write32le (void * P, uint32_t V) inline
Definition at line 468 of file Endian.h.
References P, and write32().
Referenced by llvm::jitlink::aarch32::applyFixupData(), llvm::computeLTOCacheKey(), llvm::objcopy::coff::createGnuDebugLinkSectionContents(), llvm::MD5::final(), llvm::jitlink::finalizeBlockRelax(), getSourceLineHash(), llvm::or32le(), or32le(), llvm::RuntimeDyldCOFFAArch64::resolveRelocation(), llvm::objcopy::wasm::Writer::write(), llvm::StringTableBuilder::write(), llvm::write32AArch64Addr(), write32AArch64Addr(), llvm::write32AArch64Imm(), writeInt32ToBuffer(), llvm::object::writeStringTable(), and writeUint32().
write64() [1/2]
template<endianness E> void llvm::support::endian::write64 (void * P, uint64_t V) inline
Definition at line 461 of file Endian.h.
References P, and write().
write64() [2/2]
void llvm::support::endian::write64 (void * P, uint64_t V, endianness E) inline
Definition at line 451 of file Endian.h.
References P, and write().
Referenced by llvm::jitlink::ppc64::applyFixup(), write64be(), write64le(), and llvm::jitlink::ppc64::writePrefixedInstruction().
write64be()
void llvm::support::endian::write64be (void * P, uint64_t V) inline
Definition at line 480 of file Endian.h.
References P, and write64().
write64le()
void llvm::support::endian::write64le (void * P, uint64_t V) inline
Definition at line 471 of file Endian.h.
References P, and write64().
Referenced by llvm::computeLTOCacheKey(), emitStrTab(), emitVersion(), llvm::BlockCoverageInference::getInstrumentedBlocksHash(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readNameTableSec(), llvm::sampleprof::SampleProfileReaderBinary::readSampleContextFromTable(), llvm::RuntimeDyldCOFFAArch64::resolveRelocation(), and writeUint64().
write< double >()
template<> void llvm::support::endian::write< double > (raw_ostream & os, double value, endianness endian) inline
Definition at line 48 of file EndianStream.h.
References llvm::bit_cast(), and write().
write< float >()
template<> void llvm::support::endian::write< float > (raw_ostream & os, float value, endianness endian) inline
Definition at line 43 of file EndianStream.h.
References llvm::bit_cast(), and write().
write_array()
template<typename value_type > void llvm::support::endian::write_array (raw_ostream & os, ArrayRef< value_type > values, endianness endian) inline
Definition at line 28 of file EndianStream.h.
References byte_swap().
Referenced by llvm::mcdxbc::PSVRuntimeInfo::write().
writeAtBitAlignment()
template<typename value_type , endianness endian, std::size_t alignment> void llvm::support::endian::writeAtBitAlignment (void * memory, value_type value, uint64_t startBit) inline
Write a value to memory with a particular endianness, for a location that starts at the given bit offset within the first byte.
Definition at line 162 of file Endian.h.
References assert(), byte_swap(), LLVM_ASSUME_ALIGNED, and write().
Referenced by llvm::BitstreamWriter::BackpatchByte().
writeNext() [1/2]
template<typename value_type , endianness endian, std::size_t alignment = unaligned, typename CharT > void llvm::support::endian::writeNext (CharT *& memory, value_type value) inline
Definition at line 117 of file Endian.h.
References writeNext().
writeNext() [2/2]
template<typename value_type , std::size_t alignment = unaligned, typename CharT > void llvm::support::endian::writeNext (CharT *& memory, value_type value, endianness endian) inline
Write a value of a particular endianness, and increment the buffer past that value.
Definition at line 110 of file Endian.h.
References write().
Referenced by writeNext().