LLVM: llvm::json Namespace Reference
llvm::json Namespace Reference
Classes
class Array
An Array is a JSON array, which contains heterogeneous JSON values.
class Object
An Object is a JSON object, which maps strings to heterogenous JSON values.
class ObjectKey
ObjectKey is a used to capture keys in Object.
class ObjectMapper
Helper for mapping JSON objects onto protocol structs.
class OStream
json::OStream allows writing well-formed JSON without materializing all structures as json::Value ahead of time.
class ParseError
class Path
A "cursor" marking a position within a Value.
class Value
A Value is an JSON value of unknown type.
Functions
bool isUTF8 (llvm::StringRef S, size_t *ErrOffset=nullptr)
Returns true if S is valid UTF-8, which is required for use as JSON.
std::string fixUTF8 (llvm::StringRef S)
Replaces invalid UTF-8 sequences in S with the replacement character (U+FFFD).
template<typename T >
Value toJSON (const std::optional< T > &Opt)
bool operator== (const Object &LHS, const Object &RHS)
bool operator!= (const Object &LHS, const Object &RHS)
bool operator!= (const Array &L, const Array &R)
bool operator== (const Value &L, const Value &R)
bool operator!= (const Value &L, const Value &R)
bool operator== (const Array &L, const Array &R)
bool operator== (const ObjectKey &L, const ObjectKey &R)
bool operator!= (const ObjectKey &L, const ObjectKey &R)
bool operator< (const ObjectKey &L, const ObjectKey &R)
std::vector< const Object::value_type * > sortedElements (const Object &O)
bool fromJSON (const Value &E, std::string &Out, Path P)
bool fromJSON (const Value &E, int &Out, Path P)
bool fromJSON (const Value &E, int64_t &Out, Path P)
bool fromJSON (const Value &E, double &Out, Path P)
bool fromJSON (const Value &E, bool &Out, Path P)
bool fromJSON (const Value &E, uint64_t &Out, Path P)
bool fromJSON (const Value &E, std::nullptr_t &Out, Path P)
template<typename T >
bool fromJSON (const Value &E, std::optional< T > &Out, Path P)
template<typename T >
bool fromJSON (const Value &E, std::vector< T > &Out, Path P)
template<typename T >
bool fromJSON (const Value &E, std::map< std::string, T > &Out, Path P)
llvm::Expected< Value > parse (llvm::StringRef JSON)
Parses the provided JSON source, or returns a ParseError.
template<typename T >
Expected< T > parse (const llvm::StringRef &JSON, const char *RootName="")
Version of parse() that converts the parsed value to the type T.
llvm::raw_ostream & operator<< (llvm::raw_ostream &OS, const Value &V)
Serializes this Value to JSON, writing it to the provided stream.
static void abbreviate (const Value &V, OStream &JOS)
static void abbreviateChildren (const Value &V, OStream &JOS)
static void encodeUtf8 (uint32_t Rune, std::string &Out)
static void quote (llvm::raw_ostream &OS, llvm::StringRef S)
Variables
template<typename T >
constexpr bool is_uint_64_bit_v
Function Documentation
abbreviate()
static void llvm::json::abbreviate (const Value & V, OStream & JOS) static
Definition at line 259 of file JSON.cpp.
References llvm::json::Value::Array, fixUTF8(), llvm::json::Value::Object, llvm::json::OStream::rawValue(), llvm::StringRef::size(), llvm::json::Value::String, llvm::StringRef::take_front(), and llvm::json::OStream::value().
Referenced by abbreviateChildren(), and llvm::json::Path::Root::printErrorContext().
abbreviateChildren()
static void llvm::json::abbreviateChildren (const Value & V, OStream & JOS) static
Definition at line 285 of file JSON.cpp.
References abbreviate(), llvm::json::Value::Array, llvm::json::OStream::array(), llvm::json::OStream::attributeBegin(), llvm::json::OStream::attributeEnd(), I, llvm::json::Value::Object, llvm::json::OStream::object(), sortedElements(), and llvm::json::OStream::value().
Referenced by llvm::json::Path::Root::printErrorContext().
encodeUtf8()
static void llvm::json::encodeUtf8 (uint32_t Rune, std::string & Out) static
Definition at line 580 of file JSON.cpp.
References llvm_unreachable.
fixUTF8()
std::string llvm::json::fixUTF8 (llvm::StringRef S)
Replaces invalid UTF-8 sequences in S with the replacement character (U+FFFD).
The returned string is valid UTF-8. This is much slower than isUTF8, so test that first.
Definition at line 707 of file JSON.cpp.
References llvm::ConvertUTF32toUTF8(), llvm::ConvertUTF8toUTF32(), llvm::StringRef::data(), llvm::lenientConversion, llvm::StringRef::size(), and llvm::strictConversion.
Referenced by abbreviate(), llvm::json::OStream::attributeBegin(), llvm::json::ObjectKey::ObjectKey(), llvm::json::ObjectKey::ObjectKey(), llvm::json::Value::Value(), and llvm::json::Value::Value().
fromJSON() [1/10]
bool llvm::json::fromJSON (const Value & E, bool & Out, Path P) inline
Definition at line 763 of file JSON.h.
References P.
fromJSON() [2/10]
bool llvm::json::fromJSON (const Value & E, double & Out, Path P) inline
Definition at line 755 of file JSON.h.
References P.
fromJSON() [3/10]
bool llvm::json::fromJSON (const Value & E, int & Out, Path P) inline
Definition at line 739 of file JSON.h.
References P.
fromJSON() [4/10]
bool llvm::json::fromJSON (const Value & E, int64_t & Out, Path P) inline
Definition at line 747 of file JSON.h.
References P.
fromJSON() [5/10]
template<typename T > bool llvm::json::fromJSON (const Value & E, std::map< std::string, T > & Out, Path P)
Definition at line 813 of file JSON.h.
References fromJSON(), and P.
fromJSON() [6/10]
bool llvm::json::fromJSON (const Value & E, std::nullptr_t & Out, Path P) inline
Definition at line 779 of file JSON.h.
References P.
fromJSON() [7/10]
template<typename T > bool llvm::json::fromJSON (const Value & E, std::optional< T > & Out, Path P)
Definition at line 788 of file JSON.h.
References fromJSON(), and P.
fromJSON() [8/10]
bool llvm::json::fromJSON (const Value & E, std::string & Out, Path P) inline
Definition at line 731 of file JSON.h.
References P.
Referenced by fromJSON(), fromJSON(), fromJSON(), llvm::json::ObjectMapper::map(), llvm::json::ObjectMapper::map(), llvm::json::ObjectMapper::mapOptional(), and parse().
fromJSON() [9/10]
template<typename T > bool llvm::json::fromJSON (const Value & E, std::vector< T > & Out, Path P)
Definition at line 800 of file JSON.h.
References A, fromJSON(), I, and P.
fromJSON() [10/10]
bool llvm::json::fromJSON (const Value & E, uint64_t & Out, Path P) inline
Definition at line 771 of file JSON.h.
References P.
isUTF8()
bool llvm::json::isUTF8 (llvm::StringRef S, size_t * ErrOffset = nullptr)
Returns true if S is valid UTF-8, which is required for use as JSON.
If it returns false, Offset is set to a byte offset near the first error.
Definition at line 693 of file JSON.cpp.
References llvm::Data, llvm::StringRef::data(), llvm::isLegalUTF8String(), LLVM_LIKELY, and llvm::StringRef::size().
Referenced by llvm::json::OStream::attributeBegin(), llvm::json::ObjectKey::ObjectKey(), llvm::json::ObjectKey::ObjectKey(), llvm::json::Value::Value(), and llvm::json::Value::Value().
operator!=() [1/4]
bool llvm::json::operator!= (const Array & L, const Array & R) inline
Definition at line 209 of file JSON.h.
operator!=() [2/4]
bool llvm::json::operator!= (const Object & LHS, const Object & RHS) inline
Definition at line 158 of file JSON.h.
References RHS.
operator!=() [3/4]
bool llvm::json::operator!= (const ObjectKey & L, const ObjectKey & R) inline
Definition at line 624 of file JSON.h.
operator!=() [4/4]
bool llvm::json::operator!= (const Value & L, const Value & R) inline
Definition at line 530 of file JSON.h.
operator<()
bool llvm::json::operator< (const ObjectKey & L, const ObjectKey & R) inline
Definition at line 627 of file JSON.h.
operator<<()
llvm::raw_ostream & llvm::json::operator<< (llvm::raw_ostream & OS, const Value & V) inline
Serializes this Value to JSON, writing it to the provided stream.
The formatting is compact (no extra whitespace) and deterministic. For pretty-printing, use the formatv() format_provider below.
Definition at line 1089 of file JSON.h.
References OS, and llvm::json::OStream::value().
operator==() [1/4]
bool llvm::json::operator== (const Array & L, const Array & R) inline
Definition at line 572 of file JSON.h.
operator==() [2/4]
bool llvm::json::operator== (const Object & LHS, const Object & RHS)
Definition at line 87 of file JSON.cpp.
operator==() [3/4]
bool llvm::json::operator== (const ObjectKey & L, const ObjectKey & R) inline
Definition at line 621 of file JSON.h.
operator==() [4/4]
bool llvm::json::operator== (const Value & L, const Value & R)
Definition at line 185 of file JSON.cpp.
parse() [1/2]
template<typename T > Expected< T > llvm::json::parse (const llvm::StringRef & JSON, const char * RootName = "")
Version of parse() that converts the parsed value to the type T.
RootName describes the root object and is used in error messages.
Definition at line 914 of file JSON.h.
References fromJSON(), and parse().
parse() [2/2]
Expected< Value > llvm::json::parse (llvm::StringRef JSON)
Parses the provided JSON source, or returns a ParseError.
The returned Value is self-contained and owns its strings (they do not refer to the original source).
Definition at line 682 of file JSON.cpp.
References P.
Referenced by llvm::MachO::getInterfaceFileFromJSON(), and parse().
quote()
static void llvm::json::quote (llvm::raw_ostream & OS, llvm::StringRef S) static
Definition at line 724 of file JSON.cpp.
References llvm::CallingConv::C, llvm::Lower, OS, and llvm::write_hex().
Referenced by llvm::json::OStream::attributeBegin(), and llvm::json::OStream::value().
sortedElements()
std::vector< const Object::value_type * > llvm::json::sortedElements (const Object & O)
Definition at line 245 of file JSON.cpp.
References llvm::sort().
Referenced by abbreviateChildren(), llvm::json::Path::Root::printErrorContext(), and llvm::json::OStream::value().
toJSON()
template<typename T > Value llvm::json::toJSON (const std::optional< T > & Opt)
Definition at line 827 of file JSON.h.
References llvm::Value.
Variable Documentation
is_uint_64_bit_v
template<typename T > bool llvm::json::is_uint_64_bit_v constexpr
Initial value:
=
    std::is_integral_v<T> && std::is_unsigned_v<T> &&
    sizeof(T) == sizeof(uint64_t)
Definition at line 79 of file JSON.h.