LLVM: llvm::sandboxir Namespace Reference
llvm::sandboxir Namespace Reference
Classes
class Argument
Argument of a sandboxir::Function.
class Constant
class EraseFromParent
class IRChangeBase
The base class for IR Change classes.
class MoveInstr
class OperandUseIterator
Iterator for the Use edges of a User's operands.
class RemoveFromParent
class Tracker
The tracker collects all the change objects and implements the main API for saving / reverting / accepting.
class Use
Represents a Def-use/Use-def edge in SandboxIR.
class User
A sandboxir::User has operands.
class UserUseIterator
Iterator for the Use edges of a Value's users.
class UseSet
Tracks the change of the source Value of a sandboxir::Use.
class Value
A SandboxIR Value has users. This is the base class.
Functions
void accept ()
Iterator for Instructions in a `BasicBlock.
sandboxir::Value * getValue (llvm::Value *V) const
const sandboxir::Value * getValue (const llvm::Value *V) const
Function * createFunction (llvm::Function *F)
Create a sandboxir::Function for an existing LLVM IR F, including all blocks and instructions.
size_t getNumValues () const
\Returns the number of values registered with Context.
Function Documentation
accept()
void llvm::sandboxir::accept ()
Iterator for Instructions in a `BasicBlock.
/ \Returns an sandboxir::Instruction & when derereferenced. class BBIterator { public: using difference_type = std::ptrdiff_t; using value_type = Instruction; using pointer = value_type *; using reference = value_type &; using iterator_category = std::bidirectional_iterator_tag;
private: llvm::BasicBlock *BB; llvm::BasicBlock::iterator It; Context *Ctx; pointer getInstr(llvm::BasicBlock::iterator It) const;
public: BBIterator() : BB(nullptr), Ctx(nullptr) {} BBIterator(llvm::BasicBlock <em>BB, llvm::BasicBlock::iterator It, Context *Ctx) : BB(BB), It(It), Ctx(Ctx) {} reference operator() const { return *getInstr(It); } BBIterator &operator++(); BBIterator operator++(int) { auto Copy = *this; ++*this; return Copy; } BBIterator &operator--(); BBIterator operator--(int) { auto Copy = *this; –*this; return Copy; } bool operator==(const BBIterator &Other) const { assert(Ctx == Other.Ctx && "BBIterators in different context!"); return It == Other.It; } bool operator!=(const BBIterator &Other) const { return !(*this == Other); } / \Returns the SBInstruction that corresponds to this iterator, or null if / the instruction is not found in the IR-to-SandboxIR tables. pointer get() const { return getInstr(It); } };
/ A sandboxir::User with operands, opcode and linked with previous/next / instructions in an instruction list. class Instruction : public sandboxir::User { public: enum class Opcode { #define DEF_VALUE(ID, CLASS) #define DEF_USER(ID, CLASS) #define OP(OPC)
#define DEF_INSTR(ID, OPC, CLASS)
};
protected: Instruction(ClassID ID, Opcode Opc, llvm::Instruction *I, sandboxir::Context &SBCtx) : sandboxir::User(ID, I, SBCtx), Opc(Opc) {}
Opcode Opc;
/ A SandboxIR Instruction may map to multiple LLVM IR Instruction. This / returns its topmost LLVM IR instruction. llvm::Instruction *getTopmostLLVMInstruction() const; friend class SelectInst; // For getTopmostLLVMInstruction(). friend class LoadInst; // For getTopmostLLVMInstruction(). friend class StoreInst; // For getTopmostLLVMInstruction(). friend class ReturnInst; // For getTopmostLLVMInstruction().
/ \Returns the LLVM IR Instructions that this SandboxIR maps to in program / order. virtual SmallVector<llvm::Instruction *, 1> getLLVMInstrs() const = 0; friend class EraseFromParent; // For getLLVMInstrs().
public: static const char *getOpcodeName(Opcode Opc);
friend raw_ostream &operator<<(raw_ostream &OS, Opcode Opc) { OS << getOpcodeName(Opc); return OS; }
/ This is used by BasicBlock::iterator. virtual unsigned getNumOfIRInstrs() const = 0; / \Returns a BasicBlock::iterator for this Instruction. BBIterator getIterator() const; / \Returns the next sandboxir::Instruction in the block, or nullptr if at / the end of the block. Instruction *getNextNode() const; / \Returns the previous sandboxir::Instruction in the block, or nullptr if / at the beginning of the block. Instruction *getPrevNode() const; / \Returns this Instruction's opcode. Note that SandboxIR has its own opcode / state to allow for new SandboxIR-specific instructions. Opcode getOpcode() const { return Opc; } / Detach this from its parent BasicBlock without deleting it. void removeFromParent(); / Detach this Value from its parent and delete it. void eraseFromParent(); / Insert this detached instruction before BeforeI. void insertBefore(Instruction *BeforeI); / Insert this detached instruction after AfterI. void insertAfter(Instruction *AfterI); / Insert this detached instruction into BB at WhereIt. void insertInto(BasicBlock *BB, const BBIterator &WhereIt); / Move this instruction to WhereIt. void moveBefore(BasicBlock &BB, const BBIterator &WhereIt); / Move this instruction before Before. void moveBefore(Instruction *Before) { moveBefore(*Before->getParent(), Before->getIterator()); } / Move this instruction after After. void moveAfter(Instruction *After) { moveBefore(*After->getParent(), std::next(After->getIterator())); } / \Returns the BasicBlock containing this Instruction, or null if it is / detached. BasicBlock *getParent() const; / For isa/dyn_cast. static bool classof(const sandboxir::Value *From);
friend raw_ostream &operator<<(raw_ostream &OS, const sandboxir::Instruction &SBI) { SBI.dump(OS); return OS; } void dump(raw_ostream &OS) const override; LLVM_DUMP_METHOD void dump() const override;
};
class SelectInst : public Instruction { / Use Context::createSelectInst(). Don't call the / constructor directly. SelectInst(llvm::SelectInst *CI, Context &Ctx) : Instruction(ClassID::Select, Opcode::Select, CI, Ctx) {} friend Context; // for SelectInst() Use getOperandUseInternal(unsigned OpIdx, bool Verify) const final { return getOperandUseDefault(OpIdx, Verify); } SmallVector<llvm::Instruction *, 1> getLLVMInstrs() const final { return {cast<llvm::Instruction>(Val)}; } static Value *createCommon(Value *Cond, Value *True, Value *False, const Twine &Name, IRBuilder<> &Builder, Context &Ctx);
public: unsigned getUseOperandNo(const Use &Use) const final { return getUseOperandNoDefault(Use); } unsigned getNumOfIRInstrs() const final { return 1u; } static Value *create(Value *Cond, Value *True, Value *False, Instruction *InsertBefore, Context &Ctx, const Twine &Name = ""); static Value *create(Value *Cond, Value *True, Value *False, BasicBlock *InsertAtEnd, Context &Ctx, const Twine &Name = ""); Value *getCondition() { return getOperand(0); } Value *getTrueValue() { return getOperand(1); } Value *getFalseValue() { return getOperand(2); }
void setCondition(Value *New) { setOperand(0, New); } void setTrueValue(Value *New) { setOperand(1, New); } void setFalseValue(Value *New) { setOperand(2, New); } void swapValues() { cast<llvm::SelectInst>(Val)->swapValues(); } / For isa/dyn_cast. static bool classof(const Value *From);
void verify() const final { assert(isa<llvm::SelectInst>(Val) && "Expected SelectInst!"); } void dump(raw_ostream &OS) const override; LLVM_DUMP_METHOD void dump() const override;
};
class LoadInst final : public Instruction { / Use LoadInst::create() instead of calling the constructor. LoadInst(llvm::LoadInst *LI, Context &Ctx) : Instruction(ClassID::Load, Opcode::Load, LI, Ctx) {} friend Context; // for LoadInst() Use getOperandUseInternal(unsigned OpIdx, bool Verify) const final { return getOperandUseDefault(OpIdx, Verify); } SmallVector<llvm::Instruction *, 1> getLLVMInstrs() const final { return {cast<llvm::Instruction>(Val)}; }
public: unsigned getUseOperandNo(const Use &Use) const final { return getUseOperandNoDefault(Use); }
unsigned getNumOfIRInstrs() const final { return 1u; } static LoadInst *create(Type *Ty, Value *Ptr, MaybeAlign Align, Instruction *InsertBefore, Context &Ctx, const Twine &Name = ""); static LoadInst *create(Type *Ty, Value *Ptr, MaybeAlign Align, BasicBlock *InsertAtEnd, Context &Ctx, const Twine &Name = ""); / For isa/dyn_cast. static bool classof(const Value *From); Value *getPointerOperand() const; Align getAlign() const { return cast<llvm::LoadInst>(Val)->getAlign(); } bool isUnordered() const { return cast<llvm::LoadInst>(Val)->isUnordered(); } bool isSimple() const { return cast<llvm::LoadInst>(Val)->isSimple(); }
void verify() const final { assert(isa<llvm::LoadInst>(Val) && "Expected LoadInst!"); } void dump(raw_ostream &OS) const override; LLVM_DUMP_METHOD void dump() const override;
};
class StoreInst final : public Instruction { / Use StoreInst::create(). StoreInst(llvm::StoreInst *SI, Context &Ctx) : Instruction(ClassID::Store, Opcode::Store, SI, Ctx) {} friend Context; // for StoreInst() Use getOperandUseInternal(unsigned OpIdx, bool Verify) const final { return getOperandUseDefault(OpIdx, Verify); } SmallVector<llvm::Instruction *, 1> getLLVMInstrs() const final { return {cast<llvm::Instruction>(Val)}; }
public: unsigned getUseOperandNo(const Use &Use) const final { return getUseOperandNoDefault(Use); } unsigned getNumOfIRInstrs() const final { return 1u; } static StoreInst *create(Value *V, Value *Ptr, MaybeAlign Align, Instruction *InsertBefore, Context &Ctx); static StoreInst *create(Value *V, Value *Ptr, MaybeAlign Align, BasicBlock *InsertAtEnd, Context &Ctx); / For isa/dyn_cast. static bool classof(const Value *From); Value *getValueOperand() const; Value *getPointerOperand() const; Align getAlign() const { return cast<llvm::StoreInst>(Val)->getAlign(); } bool isSimple() const { return cast<llvm::StoreInst>(Val)->isSimple(); } bool isUnordered() const { return cast<llvm::StoreInst>(Val)->isUnordered(); }
void verify() const final { assert(isa<llvm::StoreInst>(Val) && "Expected StoreInst!"); } void dump(raw_ostream &OS) const override; LLVM_DUMP_METHOD void dump() const override;
};
class ReturnInst final : public Instruction { / Use ReturnInst::create() instead of calling the constructor. ReturnInst(llvm::Instruction <em>I, Context &Ctx) : Instruction(ClassID::Ret, Opcode::Ret, I, Ctx) {} ReturnInst(ClassID SubclassID, llvm::Instruction *I, Context &Ctx) : Instruction(SubclassID, Opcode::Ret, I, Ctx) {} friend class Context; // For accessing the constructor in create() Use getOperandUseInternal(unsigned OpIdx, bool Verify) const final { return getOperandUseDefault(OpIdx, Verify); } SmallVector<llvm::Instruction *, 1> getLLVMInstrs() const final { return {cast<llvm::Instruction>(Val)}; } static ReturnInst *createCommon(Value *RetVal, IRBuilder<> &Builder, Context &Ctx);
public: static ReturnInst *create(Value *RetVal, Instruction *InsertBefore, Context &Ctx); static ReturnInst *create(Value *RetVal, BasicBlock *InsertAtEnd, Context &Ctx); static bool classof(const Value *From) { return From->getSubclassID() == ClassID::Ret; } unsigned getUseOperandNo(const Use &Use) const final { return getUseOperandNoDefault(Use); } unsigned getNumOfIRInstrs() const final { return 1u; } / \Returns null if there is no return value. Value *getReturnValue() const;
void verify() const final {} void dump(raw_ostream &OS) const override; LLVM_DUMP_METHOD void dump() const override;
};
/ An LLLVM Instruction that has no SandboxIR equivalent class gets mapped to / an OpaqueInstr. class OpaqueInst : public sandboxir::Instruction { OpaqueInst(llvm::Instruction *I, sandboxir::Context &Ctx) : sandboxir::Instruction(ClassID::Opaque, Opcode::Opaque, I, Ctx) {} OpaqueInst(ClassID SubclassID, llvm::Instruction *I, sandboxir::Context &Ctx) : sandboxir::Instruction(SubclassID, Opcode::Opaque, I, Ctx) {} friend class Context; // For constructor. Use getOperandUseInternal(unsigned OpIdx, bool Verify) const final { return getOperandUseDefault(OpIdx, Verify); } SmallVector<llvm::Instruction *, 1> getLLVMInstrs() const final { return {cast<llvm::Instruction>(Val)}; }
public: static bool classof(const sandboxir::Value *From) { return From->getSubclassID() == ClassID::Opaque; } unsigned getUseOperandNo(const Use &Use) const final { return getUseOperandNoDefault(Use); } unsigned getNumOfIRInstrs() const final { return 1u; }
void verify() const final { Nothing to do } friend raw_ostream &operator<<(raw_ostream &OS, const sandboxir::OpaqueInst &OI) { OI.dump(OS); return OS; } void dump(raw_ostream &OS) const override; LLVM_DUMP_METHOD void dump() const override;
};
/ Contains a list of sandboxir::Instruction's. class BasicBlock : public Value { / Builds a graph that contains all values in BB in their original form / i.e., no vectorization is taking place here. void buildBasicBlockFromLLVMIR(llvm::BasicBlock *LLVMBB); friend class Context; // For buildBasicBlockFromIR friend class Instruction; // For LLVM Val.
BasicBlock(llvm::BasicBlock *BB, Context &SBCtx) : Value(ClassID::Block, BB, SBCtx) { buildBasicBlockFromLLVMIR(BB); }
public: ~BasicBlock() = default; / For isa/dyn_cast. static bool classof(const Value *From) { return From->getSubclassID() == Value::ClassID::Block; } Function *getParent() const; using iterator = BBIterator; iterator begin() const; iterator end() const { auto *BB = cast<llvm::BasicBlock>(Val); return iterator(BB, BB->end(), &Ctx); } std::reverse_iterator<iterator> rbegin() const { return std::make_reverse_iterator(end()); } std::reverse_iterator<iterator> rend() const { return std::make_reverse_iterator(begin()); } Context &getContext() const { return Ctx; } Instruction *getTerminator() const; bool empty() const { return begin() == end(); } Instruction &front() const; Instruction &back() const;
void verify() const final { assert(isa<llvm::BasicBlock>(Val) && "Expected BasicBlock!"); } friend raw_ostream &operator<<(raw_ostream &OS, const BasicBlock &SBBB) { SBBB.dump(OS); return OS; } void dump(raw_ostream &OS) const final; LLVM_DUMP_METHOD void dump() const final;
};
class Context { protected: LLVMContext &LLVMCtx; Tracker IRTracker;
/ Maps LLVM Value to the corresponding sandboxir::Value. Owns all / SandboxIR objects. DenseMap<llvm::Value *, std::unique_ptr<sandboxir::Value>> LLVMValueToValueMap;
/ Remove V from the maps and returns the unique_ptr. std::unique_ptr<Value> detachLLVMValue(llvm::Value *V); / Remove SBV from all SandboxIR maps and stop owning it. This effectively / detaches V from the underlying IR. std::unique_ptr<Value> detach(Value *V); friend void Instruction::eraseFromParent(); // For detach(). / Take ownership of VPtr and store it in LLVMValueToValueMap. Value *registerValue(std::unique_ptr<Value> &&VPtr); friend class EraseFromParent; // For registerValue(). / This is the actual function that creates sandboxir values for V, / and among others handles all instruction types. Value *getOrCreateValueInternal(llvm::Value *V, llvm::User *U = nullptr); / Get or create a sandboxir::Argument for an existing LLVM IR LLVMArg. Argument *getOrCreateArgument(llvm::Argument *LLVMArg) { auto Pair = LLVMValueToValueMap.insert({LLVMArg, nullptr}); auto It = Pair.first; if (Pair.second) { It->second = std::unique_ptr<Argument>(new Argument(LLVMArg, *this)); return cast<Argument>(It->second.get()); } return cast<Argument>(It->second.get()); } / Get or create a sandboxir::Value for an existing LLVM IR LLVMV. Value *getOrCreateValue(llvm::Value *LLVMV) { return getOrCreateValueInternal(LLVMV, 0); } / Get or create a sandboxir::Constant from an existing LLVM IR LLVMC. Constant *getOrCreateConstant(llvm::Constant *LLVMC) { return cast<Constant>(getOrCreateValueInternal(LLVMC, 0)); } friend class Constant; // For getOrCreateConstant(). / Create a sandboxir::BasicBlock for an existing LLVM IR BB. This will / also create all contents of the block. BasicBlock *createBasicBlock(llvm::BasicBlock *BB);
friend class BasicBlock; // For getOrCreateValue().
IRBuilder<ConstantFolder> LLVMIRBuilder; auto &getLLVMIRBuilder() { return LLVMIRBuilder; }
SelectInst *createSelectInst(llvm::SelectInst *SI); friend SelectInst; // For createSelectInst() LoadInst *createLoadInst(llvm::LoadInst *LI); friend LoadInst; // For createLoadInst() StoreInst *createStoreInst(llvm::StoreInst *SI); friend StoreInst; // For createStoreInst() ReturnInst *createReturnInst(llvm::ReturnInst *I); friend ReturnInst; // For createReturnInst()
public: Context(LLVMContext &LLVMCtx) : LLVMCtx(LLVMCtx), IRTracker(*this), LLVMIRBuilder(LLVMCtx, ConstantFolder()) {}
Tracker &getTracker() { return IRTracker; } / Convenience function for getTracker().save() void save() { IRTracker.save(); } / Convenience function for getTracker().revert() void revert() { IRTracker.revert(); } / Convenience function for getTracker().accept()
Definition at line 891 of file SandboxIR.h.
References accept().
Referenced by accept().
createFunction()
Function * llvm::sandboxir::createFunction (llvm::Function * F)
Create a sandboxir::Function for an existing LLVM IR F, including all blocks and instructions.
This is the main API function for creating Sandbox IR.
References createFunction().
Referenced by createFunction().
getNumValues()
size_t llvm::sandboxir::getNumValues () const
\Returns the number of values registered with Context.
Definition at line 903 of file SandboxIR.h.
References getNumValues().
Referenced by getNumValues().
getValue() [1/2]
const sandboxir::Value * llvm::sandboxir::getValue (const llvm::Value * V) const
Definition at line 894 of file SandboxIR.h.
References getValue().
getValue() [2/2]
sandboxir::Value * llvm::sandboxir::getValue (llvm::Value * V) const
References getValue().
Referenced by getValue(), and getValue().