LLVM: llvm::coverage::mcdc Namespace Reference
llvm::coverage::mcdc Namespace Reference
Classes
struct BranchParameters
struct DecisionParameters
class TVIdxBuilder
Compute TestVector Indices "TVIdx" from the Conds graph.
Typedefs
using ConditionID = int16_t
The ID for MCDCBranch.
using ConditionIDs = std::array<ConditionID, 2>
using Parameters
The type of MC/DC-specific parameters.
Functions
template<class MaybeConstInnerParameters , class MaybeConstMCDCParameters >
static auto & getParams (MaybeConstMCDCParameters &MCDCParams)
Check and get underlying params in MCDCParams.
Typedef Documentation
ConditionID
using llvm::coverage::mcdc::ConditionID = int16_t
The ID for MCDCBranch.
Definition at line 24 of file MCDCTypes.h.
ConditionIDs
using llvm::coverage::mcdc::ConditionIDs = std::array<ConditionID, 2>
Definition at line 25 of file MCDCTypes.h.
Parameters
using llvm::coverage::mcdc::Parameters
Initial value:
    std::variant<std::monostate, DecisionParameters, BranchParameters>
The type of MC/DC-specific parameters.
Definition at line 55 of file MCDCTypes.h.
Function Documentation
getParams()
template<class MaybeConstInnerParameters , class MaybeConstMCDCParameters > static auto & llvm::coverage::mcdc::getParams (MaybeConstMCDCParameters & MCDCParams) static
Check and get underlying params in MCDCParams.
Template Parameters
MaybeConstInnerParameters Type to get. May be const.
MaybeConstMCDCParameters Expected inferred. May be const.
Parameters
MCDCParams May be const.
Definition at line 63 of file MCDCTypes.h.
References assert().
Referenced by llvm::coverage::CounterMappingRegion::getBranchParams(), and llvm::coverage::CounterMappingRegion::getDecisionParams().