LLVM: llvm::ConverterEBCDIC Namespace Reference
llvm::ConverterEBCDIC Namespace Reference
Functions
std::error_code convertToEBCDIC (StringRef Source, SmallVectorImpl< char > &Result)
void convertToUTF8 (StringRef Source, SmallVectorImpl< char > &Result)
Function Documentation
convertToEBCDIC()
std::error_code llvm::ConverterEBCDIC::convertToEBCDIC (StringRef Source, SmallVectorImpl< char > & Result)
Definition at line 69 of file ConvertEBCDIC.cpp.
References assert(), ISO88591ToIBM1047, llvm::Length, and Ptr.
Referenced by emitPPA1Name().
convertToUTF8()
void llvm::ConverterEBCDIC::convertToUTF8 (StringRef Source, SmallVectorImpl< char > & Result)
Definition at line 101 of file ConvertEBCDIC.cpp.
References assert(), IBM1047ToISO88591, llvm::Length, and Ptr.