LLVM: llvm::RISCVMatInt Namespace Reference
llvm::RISCVMatInt Namespace Reference
Classes
class Inst
Typedefs
using InstSeq = SmallVector<Inst, 8>
Enumerations
enum OpndKind { RegImm , Imm , RegReg , RegX0 }
Functions
InstSeq generateInstSeq (int64_t Val, const MCSubtargetInfo &STI)
void generateMCInstSeq (int64_t Val, const MCSubtargetInfo &STI, MCRegister DestReg, SmallVectorImpl< MCInst > &Insts)
InstSeq generateTwoRegInstSeq (int64_t Val, const MCSubtargetInfo &STI, unsigned &ShiftAmt, unsigned &AddOpc)
int getIntMatCost (const APInt &Val, unsigned Size, const MCSubtargetInfo &STI, bool CompressionCost, bool FreeZeroes)
Typedef Documentation
InstSeq
using llvm::RISCVMatInt::InstSeq = SmallVector<Inst, 8>
Definition at line 43 of file RISCVMatInt.h.
Enumeration Type Documentation
OpndKind
enum llvm::RISCVMatInt::OpndKind
Enumerator
RegImm
Imm
RegReg
RegX0
Definition at line 22 of file RISCVMatInt.h.
Function Documentation
generateInstSeq()
InstSeq llvm::RISCVMatInt::generateInstSeq (int64_t Val, const MCSubtargetInfo & STI)
Definition at line 227 of file RISCVMatInt.cpp.
References assert(), llvm::countr_zero(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorBase< Size_T >::empty(), extractRotateInfo(), generateInstSeqImpl(), generateInstSeqLeadingZeros(), llvm::MCSubtargetInfo::hasFeature(), llvm::Hi, llvm::isInt(), llvm::Lo, llvm::popcount(), llvm::rotl(), llvm::SignExtend64(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by generateMCInstSeq(), generateTwoRegInstSeq(), getIntMatCost(), lowerConstant(), llvm::RISCVInstrInfo::movImm(), selectConstantAddr(), selectImm(), and llvm::RISCVTargetLowering::shouldConvertConstantLoadToIntImm().
generateMCInstSeq()
void llvm::RISCVMatInt::generateMCInstSeq (int64_t Val, const MCSubtargetInfo & STI, MCRegister DestReg, SmallVectorImpl< MCInst > & Insts)
Definition at line 431 of file RISCVMatInt.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), generateInstSeq(), llvm::RISCVMatInt::Inst::getImm(), llvm::RISCVMatInt::Inst::getOpcode(), llvm::RISCVMatInt::Inst::getOpndKind(), Imm, llvm::SmallVectorTemplateBase< T, bool >::push_back(), RegImm, RegReg, and RegX0.
generateTwoRegInstSeq()
InstSeq llvm::RISCVMatInt::generateTwoRegInstSeq (int64_t Val, const MCSubtargetInfo & STI, unsigned & ShiftAmt, unsigned & AddOpc)
Definition at line 468 of file RISCVMatInt.cpp.
References assert(), llvm::countr_zero(), generateInstSeq(), llvm::MCSubtargetInfo::hasFeature(), llvm::Hi_32(), llvm::Lo_32(), and llvm::SignExtend64().
Referenced by lowerConstant(), and selectImm().
getIntMatCost()
int llvm::RISCVMatInt::getIntMatCost (const APInt & Val, unsigned Size, const MCSubtargetInfo & STI, bool CompressionCost, bool FreeZeroes)
Definition at line 501 of file RISCVMatInt.cpp.
References llvm::APInt::ashr(), generateInstSeq(), getInstSeqCost(), llvm::APInt::getSExtValue(), llvm::MCSubtargetInfo::hasFeature(), HasRVC, llvm::APInt::sextOrTrunc(), and Size.
Referenced by getIntImmCostImpl(), llvm::RISCVTargetLowering::isDesirableToCommuteWithShift(), llvm::RISCVTargetLowering::isFPImmLegal(), and llvm::RISCVTargetLowering::PerformDAGCombine().