LLVM: llvm::coro Namespace Reference
llvm::coro Namespace Reference
Classes
struct LowererBase
struct Shape
Enumerations
enum class ABI { Switch , Retcon , RetconOnce , Async }
Functions
bool declaresAnyIntrinsic (const Module &M)
bool declaresIntrinsics (const Module &M, const std::initializer_list< StringRef >)
void replaceCoroFree (CoroIdInst *CoroId, bool Elide)
void salvageDebugInfo (SmallDenseMap< Argument *, AllocaInst *, 4 > &ArgToAllocaMap, DbgVariableIntrinsic &DVI, bool OptimizeFrame, bool IsEntryPoint)
Attempts to rewrite the location operand of debug intrinsics in terms of the coroutine frame pointer, folding pointer offsets into the DIExpression of the intrinsic.
void salvageDebugInfo (SmallDenseMap< Argument *, AllocaInst *, 4 > &ArgToAllocaMap, DbgVariableRecord &DVR, bool OptimizeFrame, bool UseEntryValue)
bool defaultMaterializable (Instruction &V)
Default materializable callback.
void buildCoroutineFrame (Function &F, Shape &Shape, TargetTransformInfo &TTI, const std::function< bool(Instruction &)> &MaterializableCallback)
CallInst * createMustTailCall (DebugLoc Loc, Function *MustTailCallFn, TargetTransformInfo &TTI, ArrayRef< Value * > Arguments, IRBuilder<> &)
Enumeration Type Documentation
ABI
enum class llvm::coro::ABI strong
Enumerator
Switch
The "resume-switch" lowering, where there are separate resume and destroy functions that are shared between all suspend points.
The coroutine frame implicitly stores the resume and destroy functions, the current index, and any promise value.
Retcon
The "returned-continuation" lowering, where each suspend point creates a single continuation function that is used for both resuming and destroying.
Does not support promises.
RetconOnce
The "unique returned-continuation" lowering, where each suspend point creates a single continuation function that is used for both resuming and destroying.
Does not support promises. The function is known to suspend at most once during its execution, and the return value of the continuation is void.
Async
The "async continuation" lowering, where each suspend point creates a single continuation function.
The continuation function is available as an intrinsic.
Definition at line 53 of file CoroInternal.h.
Function Documentation
buildCoroutineFrame()
void llvm::coro::buildCoroutineFrame (Function & F, Shape & Shape, TargetTransformInfo & TTI, const std::function< bool(Instruction &)> & MaterializableCallback)
Definition at line 3098 of file CoroFrame.cpp.
References A, llvm::coro::Shape::ABI, Arguments, llvm::ArrayRef(), buildFrameDebugInfo(), buildFrameType(), Call, llvm::cast(), cleanupSinglePredPHIs(), llvm::CoroIdInst::clearPromise(), collectFrameAlloca(), llvm::coro::Shape::CoroBegin, llvm::coro::Shape::CoroEnds, llvm::coro::Shape::CoroSuspends, createMustTailCall(), doRematerializations(), dumpAllocas(), dumpSpills(), llvm::dyn_cast(), eliminateSwiftError(), F, llvm::findDbgValues(), llvm::coro::Shape::FramePtr, llvm::coro::Shape::FrameTy, llvm::coro::Shape::getSwitchCoroId(), I, insertSpills(), instructions, llvm::isa(), isCoroutineStructureIntrinsic(), isLocalAlloca(), LLVM_DEBUG, lowerLocalAllocas(), lowerNonLocalAlloca(), llvm::coro::Shape::SwitchLoweringStorage::PromiseAlloca, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::report_fatal_error(), rewritePHIs(), sinkLifetimeStartMarkers(), sinkSpillUsesAfterCoroBegin(), splitAround(), llvm::coro::Shape::SwitchLowering, and llvm::Value::users().
createMustTailCall()
CallInst * llvm::coro::createMustTailCall (DebugLoc Loc, Function * MustTailCallFn, TargetTransformInfo & TTI, ArrayRef< Value * > Arguments, IRBuilder<> & Builder)
Definition at line 1658 of file CoroSplit.cpp.
References Arguments, coerceArguments(), llvm::Function::getCallingConv(), llvm::Function::getFunctionType(), llvm::TargetTransformInfo::supportsTailCallFor(), and llvm::CallInst::TCK_MustTail.
Referenced by buildCoroutineFrame(), and splitAsyncCoroutine().
declaresAnyIntrinsic()
bool llvm::coro::declaresAnyIntrinsic (const Module & M)
Definition at line 103 of file Coroutines.cpp.
References assert(), CoroIntrinsics, isCoroutineIntrinsicName(), and Name.
Referenced by llvm::CoroConditionalWrapper::run().
declaresIntrinsics()
bool llvm::coro::declaresIntrinsics (const Module & M, const std::initializer_list< StringRef > List)
Definition at line 115 of file Coroutines.cpp.
References assert(), isCoroutineIntrinsicName(), and Name.
Referenced by declaresCoroCleanupIntrinsics(), declaresCoroEarlyIntrinsics(), and llvm::CoroElidePass::run().
defaultMaterializable()
bool llvm::coro::defaultMaterializable (Instruction & V)
Default materializable callback.
Definition at line 2296 of file CoroFrame.cpp.
References llvm::isa().
replaceCoroFree()
void llvm::coro::replaceCoroFree (CoroIdInst * CoroId, bool Elide)
Definition at line 128 of file Coroutines.cpp.
References llvm::dyn_cast(), llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::ConstantPointerNull::get(), llvm::PointerType::get(), llvm::Value::getContext(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::Value::users().
Referenced by handleNoSuspendCoroutine().
salvageDebugInfo() [1/2]
void llvm::coro::salvageDebugInfo (SmallDenseMap< Argument *, AllocaInst *, 4 > & ArgToAllocaMap, DbgVariableIntrinsic & DVI, bool OptimizeFrame, bool IsEntryPoint)
Attempts to rewrite the location operand of debug intrinsics in terms of the coroutine frame pointer, folding pointer offsets into the DIExpression of the intrinsic.
If the frame pointer is an Argument, store it into an alloca if OptimizeFrame is false.
Definition at line 2950 of file CoroFrame.cpp.
References llvm::dyn_cast(), F, llvm::Instruction::getDebugLoc(), llvm::DbgVariableIntrinsic::getExpression(), llvm::Instruction::getFunction(), llvm::DbgVariableIntrinsic::getVariableLocationOp(), I, llvm::isa(), llvm::Instruction::moveBefore(), llvm::DbgVariableIntrinsic::replaceVariableLocationOp(), llvm::salvageDebugInfoImpl(), llvm::Instruction::setDebugLoc(), and llvm::DbgVariableIntrinsic::setExpression().
Referenced by insertSpills(), and splitCoroutine().
salvageDebugInfo() [2/2]
void llvm::coro::salvageDebugInfo (SmallDenseMap< Argument *, AllocaInst *, 4 > & ArgToAllocaMap, DbgVariableRecord & DVR, bool OptimizeFrame, bool UseEntryValue)
Definition at line 2992 of file CoroFrame.cpp.
References llvm::dyn_cast(), F, llvm::DbgRecord::getDebugLoc(), llvm::DbgVariableRecord::getExpression(), llvm::DbgRecord::getFunction(), llvm::DbgVariableRecord::getType(), llvm::DbgVariableRecord::getVariableLocationOp(), I, llvm::isa(), llvm::DbgVariableRecord::isDbgDeclare(), llvm::DbgRecord::removeFromParent(), llvm::DbgVariableRecord::replaceVariableLocationOp(), llvm::salvageDebugInfoImpl(), llvm::DbgRecord::setDebugLoc(), and llvm::DbgVariableRecord::setExpression().