LLVM: llvm::RISCVRI Namespace Reference
llvm::RISCVRI Namespace Reference
Enumerations
enum {
IsVRegClassShift = 0 , IsVRegClassShiftMask = 0b1 << IsVRegClassShift , VLMulShift = IsVRegClassShift + 1 , VLMulShiftMask = 0b111 << VLMulShift ,
NFShift = VLMulShift + 3 , NFShiftMask = 0b111 << NFShift
}
Functions
static bool isVRegClass (uint64_t TSFlags)
static RISCVII::VLMUL getLMul (uint64_t TSFlags)
static unsigned getNF (uint64_t TSFlags)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IsVRegClassShift
IsVRegClassShiftMask
VLMulShift
VLMulShiftMask
NFShift
NFShiftMask
Definition at line 25 of file RISCVRegisterInfo.h.
Function Documentation
getLMul()
static RISCVII::VLMUL llvm::RISCVRI::getLMul (uint64_t TSFlags) inline static
Returns
the LMUL for the register class.
Definition at line 46 of file RISCVRegisterInfo.h.
References VLMulShift, and VLMulShiftMask.
Referenced by llvm::RISCVInstrInfo::copyPhysRegVector().
getNF()
static unsigned llvm::RISCVRI::getNF (uint64_t TSFlags) inline static
Returns
the NF for the register class.
Definition at line 51 of file RISCVRegisterInfo.h.
References NFShift, and NFShiftMask.
Referenced by llvm::RISCVInstrInfo::copyPhysRegVector(), llvm::RISCVRegisterInfo::isVRNRegClass(), and llvm::RISCVRegisterInfo::isVRRegClass().
isVRegClass()
static bool llvm::RISCVRI::isVRegClass (uint64_t TSFlags) inline static
Returns
the IsVRegClass for the register class.
Definition at line 41 of file RISCVRegisterInfo.h.
References IsVRegClassShift, and IsVRegClassShiftMask.
Referenced by llvm::RISCVRegisterInfo::isRVVRegClass(), llvm::RISCVRegisterInfo::isVRNRegClass(), and llvm::RISCVRegisterInfo::isVRRegClass().