LLVM: llvm::VPlanPatternMatch Namespace Reference
llvm::VPlanPatternMatch Namespace Reference
Namespaces
namespace detail
Classes
struct BinaryRecipe_match
struct bind_ty
struct class_match
struct match_combine_or
Matching combinators.
struct specific_intval
Match a specified integer value or vector of all elements of that value.
struct UnaryRecipe_match
struct VPCanonicalIVPHI_match
struct VPScalarIVSteps_match
Typedefs
template<typename Op0_t , unsigned Opcode>
using UnaryVPInstruction_match
template<typename Op0_t , unsigned Opcode>
using AllUnaryRecipe_match
template<typename Op0_t , typename Op1_t , unsigned Opcode>
using BinaryVPInstruction_match
template<typename Op0_t , typename Op1_t , unsigned Opcode, bool Commutative = false>
using AllBinaryRecipe_match
Functions
template<typename Val , typename Pattern >
bool match (Val *V, const Pattern &P)
class_match< VPValue > m_VPValue ()
Match an arbitrary VPValue and ignore it.
specific_intval< 0 > m_SpecificInt (uint64_t V)
specific_intval< 1 > m_False ()
template<typename LTy , typename RTy >
match_combine_or< LTy, RTy > m_CombineOr (const LTy &L, const RTy &R)
bind_ty< VPValue > m_VPValue (VPValue *&V)
Match a VPValue, capturing it if we match.
template<unsigned Opcode, typename Op0_t >
UnaryVPInstruction_match< Op0_t, Opcode > m_VPInstruction (const Op0_t &Op0)
template<unsigned Opcode, typename Op0_t , typename Op1_t >
BinaryVPInstruction_match< Op0_t, Op1_t, Opcode > m_VPInstruction (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t >
UnaryVPInstruction_match< Op0_t, VPInstruction::Not > m_Not (const Op0_t &Op0)
template<typename Op0_t >
UnaryVPInstruction_match< Op0_t, VPInstruction::BranchOnCond > m_BranchOnCond (const Op0_t &Op0)
template<typename Op0_t , typename Op1_t >
BinaryVPInstruction_match< Op0_t, Op1_t, VPInstruction::ActiveLaneMask > m_ActiveLaneMask (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t , typename Op1_t >
BinaryVPInstruction_match< Op0_t, Op1_t, VPInstruction::BranchOnCount > m_BranchOnCount (const Op0_t &Op0, const Op1_t &Op1)
template<unsigned Opcode, typename Op0_t >
AllUnaryRecipe_match< Op0_t, Opcode > m_Unary (const Op0_t &Op0)
template<typename Op0_t >
AllUnaryRecipe_match< Op0_t, Instruction::Trunc > m_Trunc (const Op0_t &Op0)
template<typename Op0_t >
AllUnaryRecipe_match< Op0_t, Instruction::ZExt > m_ZExt (const Op0_t &Op0)
template<typename Op0_t >
AllUnaryRecipe_match< Op0_t, Instruction::SExt > m_SExt (const Op0_t &Op0)
template<typename Op0_t >
match_combine_or< AllUnaryRecipe_match< Op0_t, Instruction::ZExt >, AllUnaryRecipe_match< Op0_t, Instruction::SExt > > m_ZExtOrSExt (const Op0_t &Op0)
template<unsigned Opcode, typename Op0_t , typename Op1_t , bool Commutative = false>
AllBinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative > m_Binary (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t , typename Op1_t >
AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Mul > m_Mul (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t , typename Op1_t >
AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Mul, true > m_c_Mul (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t , typename Op1_t , bool Commutative = false>
AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Or, Commutative > m_BinaryOr (const Op0_t &Op0, const Op1_t &Op1)
Match a binary OR operation.
template<typename Op0_t , typename Op1_t >
AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Or, true > m_c_BinaryOr (const Op0_t &Op0, const Op1_t &Op1)
template<typename Op0_t , typename Op1_t >
BinaryVPInstruction_match< Op0_t, Op1_t, VPInstruction::LogicalAnd > m_LogicalAnd (const Op0_t &Op0, const Op1_t &Op1)
VPCanonicalIVPHI_match m_CanonicalIV ()
template<typename Op0_t , typename Op1_t >
VPScalarIVSteps_match< Op0_t, Op1_t > m_ScalarIVSteps (const Op0_t &Op0, const Op1_t &Op1)
Typedef Documentation
AllBinaryRecipe_match
template<typename Op0_t , typename Op1_t , unsigned Opcode, bool Commutative = false> using llvm::VPlanPatternMatch::AllBinaryRecipe_match
Initial value:
    BinaryRecipe_match<Op0_t, Op1_t, Opcode, Commutative, VPWidenRecipe,
                       VPReplicateRecipe, VPWidenCastRecipe, VPInstruction>
Definition at line 196 of file VPlanPatternMatch.h.
AllUnaryRecipe_match
template<typename Op0_t , unsigned Opcode> using llvm::VPlanPatternMatch::AllUnaryRecipe_match
Initial value:
    UnaryRecipe_match<Op0_t, Opcode, VPWidenRecipe, VPReplicateRecipe,
                      VPWidenCastRecipe, VPInstruction>
Definition at line 156 of file VPlanPatternMatch.h.
BinaryVPInstruction_match
template<typename Op0_t , typename Op1_t , unsigned Opcode> using llvm::VPlanPatternMatch::BinaryVPInstruction_match
Initial value:
    BinaryRecipe_match<Op0_t, Op1_t, Opcode,  false,
                       VPInstruction>
Definition at line 190 of file VPlanPatternMatch.h.
UnaryVPInstruction_match
template<typename Op0_t , unsigned Opcode> using llvm::VPlanPatternMatch::UnaryVPInstruction_match
Initial value:
    UnaryRecipe_match<Op0_t, Opcode, VPInstruction>
Definition at line 152 of file VPlanPatternMatch.h.
Function Documentation
m_ActiveLaneMask()
template<typename Op0_t , typename Op1_t > BinaryVPInstruction_match< Op0_t, Op1_t, VPInstruction::ActiveLaneMask > llvm::VPlanPatternMatch::m_ActiveLaneMask (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 226 of file VPlanPatternMatch.h.
References m_VPInstruction().
Referenced by llvm::vputils::isHeaderMask().
m_Binary()
template<unsigned Opcode, typename Op0_t , typename Op1_t , bool Commutative = false> AllBinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative > llvm::VPlanPatternMatch::m_Binary (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 267 of file VPlanPatternMatch.h.
Referenced by llvm::vputils::isHeaderMask(), m_BinaryOr(), m_c_Mul(), and m_Mul().
m_BinaryOr()
template<typename Op0_t , typename Op1_t , bool Commutative = false> AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Or, Commutative > llvm::VPlanPatternMatch::m_BinaryOr (const Op0_t & Op0, const Op1_t & Op1) inline
Match a binary OR operation.
Note that while conceptually the operands can be matched commutatively, Commutative defaults to false in line with the IR-based pattern matching infrastructure. Use m_c_BinaryOr for a commutative version of the matcher.
Definition at line 290 of file VPlanPatternMatch.h.
References m_Binary().
Referenced by m_c_BinaryOr().
m_BranchOnCond()
template<typename Op0_t > UnaryVPInstruction_match< Op0_t, VPInstruction::BranchOnCond > llvm::VPlanPatternMatch::m_BranchOnCond (const Op0_t & Op0) inline
Definition at line 220 of file VPlanPatternMatch.h.
References m_VPInstruction().
Referenced by hasConditionalTerminator().
m_BranchOnCount()
template<typename Op0_t , typename Op1_t > BinaryVPInstruction_match< Op0_t, Op1_t, VPInstruction::BranchOnCount > llvm::VPlanPatternMatch::m_BranchOnCount (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 232 of file VPlanPatternMatch.h.
References m_VPInstruction().
Referenced by hasConditionalTerminator().
m_c_BinaryOr()
template<typename Op0_t , typename Op1_t > AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Or, true > llvm::VPlanPatternMatch::m_c_BinaryOr (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 297 of file VPlanPatternMatch.h.
References m_BinaryOr().
m_c_Mul()
template<typename Op0_t , typename Op1_t > AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Mul, true > llvm::VPlanPatternMatch::m_c_Mul (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 280 of file VPlanPatternMatch.h.
References m_Binary().
m_CanonicalIV()
VPCanonicalIVPHI_match llvm::VPlanPatternMatch::m_CanonicalIV () inline
Definition at line 316 of file VPlanPatternMatch.h.
Referenced by llvm::vputils::isHeaderMask().
m_CombineOr()
template<typename LTy , typename RTy > match_combine_or< LTy, RTy > llvm::VPlanPatternMatch::m_CombineOr (const LTy & L, const RTy & R) inline
Definition at line 102 of file VPlanPatternMatch.h.
Referenced by m_ZExtOrSExt().
m_False()
specific_intval< 1 > llvm::VPlanPatternMatch::m_False () inline
Definition at line 83 of file VPlanPatternMatch.h.
m_LogicalAnd()
template<typename Op0_t , typename Op1_t > BinaryVPInstruction_match< Op0_t, Op1_t, VPInstruction::LogicalAnd > llvm::VPlanPatternMatch::m_LogicalAnd (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 303 of file VPlanPatternMatch.h.
References m_VPInstruction().
m_Mul()
template<typename Op0_t , typename Op1_t > AllBinaryRecipe_match< Op0_t, Op1_t, Instruction::Mul > llvm::VPlanPatternMatch::m_Mul (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 273 of file VPlanPatternMatch.h.
References m_Binary().
m_Not()
template<typename Op0_t > UnaryVPInstruction_match< Op0_t, VPInstruction::Not > llvm::VPlanPatternMatch::m_Not (const Op0_t & Op0) inline
Definition at line 214 of file VPlanPatternMatch.h.
References m_VPInstruction().
m_ScalarIVSteps()
template<typename Op0_t , typename Op1_t > VPScalarIVSteps_match< Op0_t, Op1_t > llvm::VPlanPatternMatch::m_ScalarIVSteps (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 341 of file VPlanPatternMatch.h.
Referenced by llvm::vputils::isHeaderMask().
m_SExt()
template<typename Op0_t > AllUnaryRecipe_match< Op0_t, Instruction::SExt > llvm::VPlanPatternMatch::m_SExt (const Op0_t & Op0) inline
Definition at line 253 of file VPlanPatternMatch.h.
References m_Unary().
Referenced by m_ZExtOrSExt().
m_SpecificInt()
specific_intval< 0 > llvm::VPlanPatternMatch::m_SpecificInt (uint64_t V) inline
Definition at line 79 of file VPlanPatternMatch.h.
m_Trunc()
template<typename Op0_t > AllUnaryRecipe_match< Op0_t, Instruction::Trunc > llvm::VPlanPatternMatch::m_Trunc (const Op0_t & Op0) inline
Definition at line 243 of file VPlanPatternMatch.h.
References m_Unary().
m_Unary()
template<unsigned Opcode, typename Op0_t > AllUnaryRecipe_match< Op0_t, Opcode > llvm::VPlanPatternMatch::m_Unary (const Op0_t & Op0) inline
Definition at line 237 of file VPlanPatternMatch.h.
Referenced by m_SExt(), m_Trunc(), and m_ZExt().
m_VPInstruction() [1/2]
template<unsigned Opcode, typename Op0_t > UnaryVPInstruction_match< Op0_t, Opcode > llvm::VPlanPatternMatch::m_VPInstruction (const Op0_t & Op0) inline
Definition at line 202 of file VPlanPatternMatch.h.
Referenced by m_ActiveLaneMask(), m_BranchOnCond(), m_BranchOnCount(), m_LogicalAnd(), and m_Not().
m_VPInstruction() [2/2]
template<unsigned Opcode, typename Op0_t , typename Op1_t > BinaryVPInstruction_match< Op0_t, Op1_t, Opcode > llvm::VPlanPatternMatch::m_VPInstruction (const Op0_t & Op0, const Op1_t & Op1) inline
Definition at line 208 of file VPlanPatternMatch.h.
m_VPValue() [1/2]
class_match< VPValue > llvm::VPlanPatternMatch::m_VPValue () inline
Match an arbitrary VPValue and ignore it.
Definition at line 37 of file VPlanPatternMatch.h.
Referenced by hasConditionalTerminator(), and llvm::vputils::isHeaderMask().
m_VPValue() [2/2]
bind_ty< VPValue > llvm::VPlanPatternMatch::m_VPValue (VPValue *& V) inline
Match a VPValue, capturing it if we match.
Definition at line 107 of file VPlanPatternMatch.h.
m_ZExt()
template<typename Op0_t > AllUnaryRecipe_match< Op0_t, Instruction::ZExt > llvm::VPlanPatternMatch::m_ZExt (const Op0_t & Op0) inline
Definition at line 248 of file VPlanPatternMatch.h.
References m_Unary().
Referenced by m_ZExtOrSExt().
m_ZExtOrSExt()
template<typename Op0_t > match_combine_or< AllUnaryRecipe_match< Op0_t, Instruction::ZExt >, AllUnaryRecipe_match< Op0_t, Instruction::SExt > > llvm::VPlanPatternMatch::m_ZExtOrSExt (const Op0_t & Op0) inline
Definition at line 260 of file VPlanPatternMatch.h.
References m_CombineOr(), m_SExt(), and m_ZExt().
match()
template<typename Val , typename Pattern > bool llvm::VPlanPatternMatch::match (Val * V, const Pattern & P)
Definition at line 28 of file VPlanPatternMatch.h.
References match(), and P.
Referenced by match().