LLVM: lib/Support/NativeFormatting.cpp File Reference
NativeFormatting.cpp File Reference
#include "llvm/Support/NativeFormatting.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <cmath>
Functions
template<typename T , std::size_t N>
static int format_to_buffer (T Value, char(&Buffer)[N])
static void writeWithCommas (raw_ostream &S, ArrayRef< char > Buffer)
template<typename T >
static void write_unsigned_impl (raw_ostream &S, T N, size_t MinDigits, IntegerStyle Style, bool IsNegative)
template<typename T >
static void write_unsigned (raw_ostream &S, T N, size_t MinDigits, IntegerStyle Style, bool IsNegative=false)
template<typename T >
static void write_signed (raw_ostream &S, T N, size_t MinDigits, IntegerStyle Style)
Function Documentation
format_to_buffer()
template<typename T , std::size_t N> static int format_to_buffer (T Value, char(&) Buffer[N]) static
Definition at line 26 of file NativeFormatting.cpp.
Referenced by write_unsigned_impl().
write_signed()
template<typename T > static void write_signed (raw_ostream & S, T N, size_t MinDigits, IntegerStyle Style) static
Definition at line 90 of file NativeFormatting.cpp.
References N, and write_unsigned().
Referenced by llvm::write_integer(), llvm::write_integer(), and llvm::write_integer().
write_unsigned()
template<typename T > static void write_unsigned (raw_ostream & S, T N, size_t MinDigits, IntegerStyle Style, bool IsNegative = false) static
Definition at line 79 of file NativeFormatting.cpp.
References N, and write_unsigned_impl().
Referenced by llvm::write_integer(), llvm::write_integer(), llvm::write_integer(), and write_signed().
write_unsigned_impl()
template<typename T > static void write_unsigned_impl (raw_ostream & S, T N, size_t MinDigits, IntegerStyle Style, bool IsNegative) static
Definition at line 56 of file NativeFormatting.cpp.
References format_to_buffer(), I, N, llvm::raw_ostream::write(), and writeWithCommas().
Referenced by write_unsigned().
writeWithCommas()
static void writeWithCommas (raw_ostream & S, ArrayRef< char > Buffer) static
Definition at line 37 of file NativeFormatting.cpp.
References assert(), llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::drop_front(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::size(), llvm::ArrayRef< T >::take_front(), and llvm::raw_ostream::write().
Referenced by write_unsigned_impl().