LLVM: lib/Frontend/OpenMP/OMP.cpp File Reference
OMP.cpp File Reference
#include "llvm/Frontend/OpenMP/OMP.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/ErrorHandling.h"
#include <algorithm>
#include <iterator>
#include <type_traits>
#include "llvm/Frontend/OpenMP/OMP.inc"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::omp
Macros
#define GEN_DIRECTIVES_IMPL
Functions
static iterator_range< ArrayRef< Directive >::iterator > getFirstCompositeRange (iterator_range< ArrayRef< Directive >::iterator > Leafs)
ArrayRef< Directive > llvm::omp::getLeafConstructs (Directive D)
ArrayRef< Directive > llvm::omp::getLeafConstructsOrSelf (Directive D)
ArrayRef< Directive > llvm::omp::getLeafOrCompositeConstructs (Directive D, SmallVectorImpl< Directive > &Output)
Directive llvm::omp::getCompoundConstruct (ArrayRef< Directive > Parts)
bool llvm::omp::isLeafConstruct (Directive D)
bool llvm::omp::isCompositeConstruct (Directive D)
bool llvm::omp::isCombinedConstruct (Directive D)
Macro Definition Documentation
GEN_DIRECTIVES_IMPL
#define GEN_DIRECTIVES_IMPL
Definition at line 25 of file OMP.cpp.
Function Documentation
getFirstCompositeRange()
static iterator_range< ArrayRef< Directive >::iterator > getFirstCompositeRange (iterator_range< ArrayRef< Directive >::iterator > Leafs) static
Definition at line 29 of file OMP.cpp.
References llvm::Empty, End, llvm::List, and llvm::make_range().
Referenced by llvm::omp::getLeafOrCompositeConstructs(), and llvm::omp::isCompositeConstruct().