LLVM: lib/IR/OptBisect.cpp File Reference
OptBisect.cpp File Reference
This file implements support for a bisecting optimizations based on a command line option.
#include "llvm/IR/OptBisect.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
Functions
static OptBisect & getOptBisector ()
static void printPassMessage (const StringRef &Name, int PassNum, StringRef TargetDesc, bool Running)
Variables
static cl::opt< int > OptBisectLimit ("opt-bisect-limit", cl::Hidden, cl::init(OptBisect::Disabled), cl::Optional, cl::cb< void, int >([](int Limit) { getOptBisector().setLimit(Limit);}), cl::desc("Maximum optimization to perform"))
Detailed Description
This file implements support for a bisecting optimizations based on a command line option.
Definition in file OptBisect.cpp.
Function Documentation
getOptBisector()
static OptBisect & getOptBisector () static
Definition at line 23 of file OptBisect.cpp.
Referenced by llvm::getGlobalPassGate().
printPassMessage()
static void printPassMessage (const StringRef & Name, int PassNum, StringRef TargetDesc, bool Running) static
Definition at line 35 of file OptBisect.cpp.
References llvm::errs(), and Name.
Referenced by llvm::OptBisect::shouldRunPass().
Variable Documentation
OptBisectLimit
cl::opt< int > OptBisectLimit("opt-bisect-limit", cl::Hidden, cl::init(OptBisect::Disabled), cl::Optional, cl::cb< void, int >([](int Limit) { getOptBisector().setLimit(Limit); }), cl::desc("Maximum optimization to perform")) ("opt-bisect-limit" , cl::Hidden , cl::init(OptBisect::Disabled) , cl::Optional , cl::cb< void, int > [](int Limit) { getOptBisector().setLimit(Limit); }, cl::desc("Maximum optimization to perform")) static