LLVM: lib/Transforms/Instrumentation/PGOForceFunctionAttrs.cpp File Reference
PGOForceFunctionAttrs.cpp File Reference
#include "llvm/Transforms/Instrumentation/PGOForceFunctionAttrs.h"
#include "llvm/Analysis/BlockFrequencyInfo.h"
#include "llvm/Analysis/ProfileSummaryInfo.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/PassManager.h"
#include "llvm/Support/ErrorHandling.h"
Functions
static bool shouldRunOnFunction (Function &F, ProfileSummaryInfo &PSI, FunctionAnalysisManager &FAM)
Function Documentation
shouldRunOnFunction()
static bool shouldRunOnFunction (Function & F, ProfileSummaryInfo & PSI, FunctionAnalysisManager & FAM) static
Definition at line 18 of file PGOForceFunctionAttrs.cpp.
References F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::ProfileSummaryInfo::hasProfileSummary(), and llvm::ProfileSummaryInfo::isFunctionColdInCallGraph().
Referenced by llvm::PGOForceFunctionAttrsPass::run().