LLVM: lib/Target/PowerPC/PPCCallingConv.cpp File Reference
PPCCallingConv.cpp File Reference
#include "PPCRegisterInfo.h"
#include "PPCCallingConv.h"
#include "PPCSubtarget.h"
#include "PPCCCState.h"
#include "PPCGenCallingConv.inc"
Functions
bool CC_PPC_AnyReg_Error (unsigned &, MVT &, MVT &, CCValAssign::LocInfo &, ISD::ArgFlagsTy &, CCState &)
bool CC_PPC64_ELF_Shadow_GPR_Regs (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_PPC32_SVR4_Custom_Dummy (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_PPC32_SVR4_Custom_AlignArgRegs (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_PPC32_SVR4_Custom_SkipLastArgRegsPPCF128 (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_PPC32_SVR4_Custom_AlignFPArgRegs (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_PPC32_SPE_CustomSplitFP64 (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
static bool CC_PPC32_SPE_RetF64 (unsigned &ValNo, MVT &ValVT, MVT &LocVT, CCValAssign::LocInfo &LocInfo, ISD::ArgFlagsTy &ArgFlags, CCState &State)
Function Documentation
CC_PPC32_SPE_CustomSplitFP64()
static bool CC_PPC32_SPE_CustomSplitFP64 (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 145 of file PPCCallingConv.cpp.
References assert(), and llvm::CCValAssign::getCustomReg().
CC_PPC32_SPE_RetF64()
static bool CC_PPC32_SPE_RetF64 (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 174 of file PPCCallingConv.cpp.
References llvm::CCValAssign::getCustomReg().
CC_PPC32_SVR4_Custom_AlignArgRegs()
static bool CC_PPC32_SVR4_Custom_AlignArgRegs (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 67 of file PPCCallingConv.cpp.
CC_PPC32_SVR4_Custom_AlignFPArgRegs()
static bool CC_PPC32_SVR4_Custom_AlignFPArgRegs (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 117 of file PPCCallingConv.cpp.
CC_PPC32_SVR4_Custom_Dummy()
static bool CC_PPC32_SVR4_Custom_Dummy (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 60 of file PPCCallingConv.cpp.
CC_PPC32_SVR4_Custom_SkipLastArgRegsPPCF128()
static bool CC_PPC32_SVR4_Custom_SkipLastArgRegsPPCF128 (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) static
Definition at line 94 of file PPCCallingConv.cpp.
CC_PPC64_ELF_Shadow_GPR_Regs()
bool CC_PPC64_ELF_Shadow_GPR_Regs (unsigned & ValNo, MVT & ValVT, MVT & LocVT, CCValAssign::LocInfo & LocInfo, ISD::ArgFlagsTy & ArgFlags, CCState & State) inline
Definition at line 27 of file PPCCallingConv.cpp.
References llvm::MVT::is128BitVector().
CC_PPC_AnyReg_Error()
bool CC_PPC_AnyReg_Error (unsigned & , MVT & , MVT & , CCValAssign::LocInfo & , ISD::ArgFlagsTy & , CCState &) inline
Definition at line 15 of file PPCCallingConv.cpp.
References llvm_unreachable.