LLVM: lib/Target/PowerPC/PPCMCInstLower.cpp File Reference
PPCMCInstLower.cpp File Reference
#include "MCTargetDesc/PPCMCExpr.h"
#include "PPC.h"
#include "PPCMachineFunctionInfo.h"
#include "PPCSubtarget.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/Twine.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/Mangler.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
Functions
static MCSymbol * GetSymbolFromOperand (const MachineOperand &MO, AsmPrinter &AP)
static MCOperand GetSymbolRef (const MachineOperand &MO, const MCSymbol *Symbol, AsmPrinter &Printer)
Function Documentation
GetSymbolFromOperand()
static MCSymbol * GetSymbolFromOperand (const MachineOperand & MO, AsmPrinter & AP) static
Definition at line 34 of file PPCMCInstLower.cpp.
References assert(), DL, llvm::AsmPrinter::getDataLayout(), llvm::MachineOperand::getGlobal(), llvm::Mangler::getNameWithPrefix(), llvm::AsmPrinter::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isSymbol(), Name, llvm::AsmPrinter::OutContext, and Sym.
Referenced by llvm::LowerPPCMachineOperandToMCOperand().
GetSymbolRef()
static MCOperand GetSymbolRef (const MachineOperand & MO, const MCSymbol * Symbol, AsmPrinter & Printer) static
Definition at line 54 of file PPCMCInstLower.cpp.
References assert(), llvm::PICLevel::BigPIC, llvm::MCConstantExpr::create(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCOperand::createExpr(), llvm::PPCMCExpr::createHa(), llvm::PPCMCExpr::createLo(), llvm::MCBinaryExpr::createSub(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getGlobal(), llvm::MachineFunction::getInfo(), llvm::MachineOperand::getOffset(), llvm::GlobalValue::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getParent(), llvm::MachineFunction::getPICBaseSymbol(), llvm::MachineFunction::getSubtarget(), llvm::MachineOperand::getTargetFlags(), llvm::PPCFunctionInfo::isAIXFuncUseTLSIEForLD(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isJTI(), llvm::PPCSubtarget::isUsingPCRelativeCalls(), llvm::TLSModel::LocalDynamic, llvm::TLSModel::LocalExec, MI, llvm::PPCII::MO_DTPREL_LO, llvm::PPCII::MO_GOT_PCREL_FLAG, llvm::PPCII::MO_GOT_TLSGD_PCREL_FLAG, llvm::PPCII::MO_GOT_TLSLD_PCREL_FLAG, llvm::PPCII::MO_GOT_TPREL_PCREL_FLAG, llvm::PPCII::MO_HA, llvm::PPCII::MO_LO, llvm::PPCII::MO_PCREL_FLAG, llvm::PPCII::MO_PCREL_OPT_FLAG, llvm::PPCII::MO_PIC_FLAG, llvm::PPCII::MO_PIC_HA_FLAG, llvm::PPCII::MO_PIC_LO_FLAG, llvm::PPCII::MO_PLT, llvm::PPCII::MO_TLS, llvm::PPCII::MO_TLS_PCREL_FLAG, llvm::PPCII::MO_TLSLD_FLAG, llvm::PPCII::MO_TLSLD_LO, llvm::PPCII::MO_TOC_LO, llvm::PPCII::MO_TPREL_FLAG, llvm::PPCII::MO_TPREL_HA, llvm::PPCII::MO_TPREL_LO, llvm::PPCII::MO_TPREL_PCREL_FLAG, PB(), Printer, TM, llvm::MCSymbolRefExpr::VK_None, llvm::MCSymbolRefExpr::VK_PCREL, llvm::MCSymbolRefExpr::VK_PLT, llvm::MCSymbolRefExpr::VK_PPC_AIX_TLSIE, llvm::MCSymbolRefExpr::VK_PPC_AIX_TLSLD, llvm::MCSymbolRefExpr::VK_PPC_AIX_TLSLE, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_LO, llvm::MCSymbolRefExpr::VK_PPC_GOT_PCREL, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSGD_PCREL, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSLD_LO, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSLD_PCREL, llvm::MCSymbolRefExpr::VK_PPC_GOT_TPREL_PCREL, llvm::MCSymbolRefExpr::VK_PPC_NOTOC, llvm::MCSymbolRefExpr::VK_PPC_PCREL_OPT, llvm::MCSymbolRefExpr::VK_PPC_TLS, llvm::MCSymbolRefExpr::VK_PPC_TLS_PCREL, llvm::MCSymbolRefExpr::VK_PPC_TOC_LO, llvm::MCSymbolRefExpr::VK_PPC_TPREL_HA, llvm::MCSymbolRefExpr::VK_PPC_TPREL_LO, and llvm::MCSymbolRefExpr::VK_TPREL.
Referenced by llvm::LowerPPCMachineOperandToMCOperand().