LLVM: lib/Support/raw_socket_stream.cpp File Reference
raw_socket_stream.cpp File Reference
#include "llvm/Support/raw_socket_stream.h"
#include "llvm/Config/config.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/FileSystem.h"
#include <atomic>
#include <fcntl.h>
#include <functional>
#include <thread>
#include <poll.h>
#include <sys/socket.h>
#include <sys/un.h>
#include <unistd.h>
Functions
static std::error_code getLastSocketErrorCode ()
static sockaddr_un setSocketAddr (StringRef SocketPath)
static Expected< int > getSocketFD (StringRef SocketPath)
static std::error_code manageTimeout (const std::chrono::milliseconds &Timeout, const std::function< int()> &getActiveFD, const std::optional< int > &CancelFD=std::nullopt)
Function Documentation
getLastSocketErrorCode()
static std::error_code getLastSocketErrorCode () static
Definition at line 57 of file raw_socket_stream.cpp.
References llvm::errnoAsErrorCode().
Referenced by llvm::ListeningSocket::accept(), llvm::ListeningSocket::createUnix(), getSocketFD(), and manageTimeout().
getSocketFD()
static Expected< int > getSocketFD (StringRef SocketPath) static
Definition at line 73 of file raw_socket_stream.cpp.
References Addr, getLastSocketErrorCode(), llvm::make_error(), and setSocketAddr().
Referenced by llvm::raw_socket_stream::createConnectedUnix(), and llvm::ListeningSocket::createUnix().
manageTimeout()
static std::error_code manageTimeout (const std::chrono::milliseconds & Timeout, const std::function< int()> & getActiveFD, const std::optional< int > & CancelFD = std::nullopt) static
Definition at line 191 of file raw_socket_stream.cpp.
References getLastSocketErrorCode().
Referenced by llvm::ListeningSocket::accept(), and llvm::raw_socket_stream::read().
setSocketAddr()
static sockaddr_un setSocketAddr (StringRef SocketPath) static
Definition at line 65 of file raw_socket_stream.cpp.
References Addr, and llvm::StringRef::str().
Referenced by llvm::ListeningSocket::createUnix(), and getSocketFD().