LLVM: lib/Target/RISCV/RISCVInsertReadWriteCSR.cpp File Reference
RISCVInsertReadWriteCSR.cpp File Reference
#include "MCTargetDesc/RISCVBaseInfo.h"
#include "RISCV.h"
#include "RISCVSubtarget.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
Macros
#define DEBUG_TYPE "riscv-insert-read-write-csr"
#define RISCV_INSERT_READ_WRITE_CSR_NAME "RISC-V Insert Read/Write CSR Pass"
Functions
INITIALIZE_PASS (RISCVInsertReadWriteCSR, DEBUG_TYPE, RISCV_INSERT_READ_WRITE_CSR_NAME, false, false) bool RISCVInsertReadWriteCSR
Variables
static cl::opt< bool > DisableFRMInsertOpt ("riscv-disable-frm-insert-opt", cl::init(false), cl::Hidden, cl::desc("Disable optimized frm insertion."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-insert-read-write-csr"
Definition at line 23 of file RISCVInsertReadWriteCSR.cpp.
RISCV_INSERT_READ_WRITE_CSR_NAME
#define RISCV_INSERT_READ_WRITE_CSR_NAME "RISC-V Insert Read/Write CSR Pass"
Definition at line 24 of file RISCVInsertReadWriteCSR.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RISCVInsertReadWriteCSR , DEBUG_TYPE , RISCV_INSERT_READ_WRITE_CSR_NAME , false , false)
Definition at line 61 of file RISCVInsertReadWriteCSR.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), Changed, llvm::MachineOperand::CreateReg(), llvm::RISCVFPRndMode::DYN, llvm::RISCVII::getFRMOpNum(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineBasicBlock::insertAfter(), llvm::Register::isValid(), MBB, MI, MRI, Register, and TII.
Variable Documentation
DisableFRMInsertOpt
cl::opt< bool > DisableFRMInsertOpt("riscv-disable-frm-insert-opt", cl::init(false), cl::Hidden, cl::desc("Disable optimized frm insertion.")) ("riscv-disable-frm-insert-opt" , cl::init(false) , cl::Hidden , cl::desc("Disable optimized frm insertion.")) static