LLVM: lib/Support/RISCVISAUtils.cpp File Reference
RISCVISAUtils.cpp File Reference
#include "llvm/Support/RISCVISAUtils.h"
#include "llvm/ADT/StringExtras.h"
#include <cassert>
Enumerations
enum RankFlags { RF_Z_EXTENSION = 1 << 6 , RF_S_EXTENSION = 2 << 6 , RF_X_EXTENSION = 3 << 6 , RF_UNKNOWN_MULTILETTER_EXTENSION = 4 << 6 }
Functions
static unsigned singleLetterExtensionRank (char Ext)
static unsigned getExtensionRank (const std::string &ExtName)
Enumeration Type Documentation
RankFlags
enum RankFlags
Enumerator
RF_Z_EXTENSION
RF_S_EXTENSION
RF_X_EXTENSION
RF_UNKNOWN_MULTILETTER_EXTENSION
Definition at line 31 of file RISCVISAUtils.cpp.
Function Documentation
getExtensionRank()
static unsigned getExtensionRank (const std::string & ExtName) static
Definition at line 60 of file RISCVISAUtils.cpp.
References assert(), RF_S_EXTENSION, RF_UNKNOWN_MULTILETTER_EXTENSION, RF_X_EXTENSION, RF_Z_EXTENSION, and singleLetterExtensionRank().
Referenced by llvm::RISCVISAUtils::compareExtension().
singleLetterExtensionRank()
static unsigned singleLetterExtensionRank (char Ext) static
Definition at line 40 of file RISCVISAUtils.cpp.
References llvm::RISCVISAUtils::AllStdExts, assert(), llvm::StringRef::find(), isLower(), llvm::StringRef::npos, and llvm::StringRef::size().
Referenced by getExtensionRank().