LLVM: lib/Target/RISCV/MCTargetDesc/RISCVMCTargetDesc.cpp File Reference
RISCVMCTargetDesc.cpp File Reference
#include "RISCVMCTargetDesc.h"
#include "RISCVBaseInfo.h"
#include "RISCVELFStreamer.h"
#include "RISCVInstPrinter.h"
#include "RISCVMCAsmInfo.h"
#include "RISCVMCObjectFileInfo.h"
#include "RISCVTargetStreamer.h"
#include "TargetInfo/RISCVTargetInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include <bitset>
#include "RISCVGenInstrInfo.inc"
#include "RISCVGenRegisterInfo.inc"
#include "RISCVGenSubtargetInfo.inc"
#include "RISCVGenSearchableTables.inc"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::RISCVVInversePseudosTable
Macros
#define GET_INSTRINFO_MC_DESC
This file provides RISC-V specific target descriptions.
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_REGINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
#define GET_RISCVVInversePseudosTable_IMPL
Functions
static MCInstrInfo * createRISCVMCInstrInfo ()
static MCRegisterInfo * createRISCVMCRegisterInfo (const Triple &TT)
static MCAsmInfo * createRISCVMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
static MCObjectFileInfo * createRISCVMCObjectFileInfo (MCContext &Ctx, bool PIC, bool LargeCodeModel=false)
static MCSubtargetInfo * createRISCVMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCInstPrinter * createRISCVMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCTargetStreamer * createRISCVObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
static MCTargetStreamer * createRISCVAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint)
static MCTargetStreamer * createRISCVNullTargetStreamer (MCStreamer &S)
static MCInstrAnalysis * createRISCVInstrAnalysis (const MCInstrInfo *Info)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 37 of file RISCVMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
This file provides RISC-V specific target descriptions.
Definition at line 36 of file RISCVMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 40 of file RISCVMCTargetDesc.cpp.
GET_RISCVVInversePseudosTable_IMPL
#define GET_RISCVVInversePseudosTable_IMPL
Definition at line 50 of file RISCVMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 43 of file RISCVMCTargetDesc.cpp.
Function Documentation
createRISCVAsmTargetStreamer()
static MCTargetStreamer * createRISCVAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint) static
Definition at line 114 of file RISCVMCTargetDesc.cpp.
References OS.
Referenced by LLVMInitializeRISCVTargetMC().
createRISCVInstrAnalysis()
static MCInstrAnalysis * createRISCVInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 326 of file RISCVMCTargetDesc.cpp.
Referenced by LLVMInitializeRISCVTargetMC().
createRISCVMCAsmInfo()
static MCAsmInfo * createRISCVMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT, const MCTargetOptions & Options) static
Definition at line 69 of file RISCVMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::cfiDefCfa(), and MRI.
Referenced by LLVMInitializeRISCVTargetMC().
createRISCVMCInstPrinter()
static MCInstPrinter * createRISCVMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 97 of file RISCVMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeRISCVTargetMC().
createRISCVMCInstrInfo()
static MCInstrInfo * createRISCVMCInstrInfo () static
Definition at line 57 of file RISCVMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeRISCVTargetMC().
createRISCVMCObjectFileInfo()
static MCObjectFileInfo * createRISCVMCObjectFileInfo (MCContext & Ctx, bool PIC, bool LargeCodeModel = false) static
Definition at line 82 of file RISCVMCTargetDesc.cpp.
References llvm::MCObjectFileInfo::initMCObjectFileInfo(), and PIC.
Referenced by LLVMInitializeRISCVTargetMC().
createRISCVMCRegisterInfo()
static MCRegisterInfo * createRISCVMCRegisterInfo (const Triple & TT) static
Definition at line 63 of file RISCVMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeRISCVTargetMC().
createRISCVMCSubtargetInfo()
static MCSubtargetInfo * createRISCVMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 89 of file RISCVMCTargetDesc.cpp.
Referenced by LLVMInitializeRISCVTargetMC().
createRISCVNullTargetStreamer()
static MCTargetStreamer * createRISCVNullTargetStreamer (MCStreamer & S) static
Definition at line 119 of file RISCVMCTargetDesc.cpp.
Referenced by LLVMInitializeRISCVTargetMC().
createRISCVObjectTargetStreamer()
static MCTargetStreamer * createRISCVObjectTargetStreamer (MCStreamer & S, const MCSubtargetInfo & STI) static
Definition at line 106 of file RISCVMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getTargetTriple().
Referenced by LLVMInitializeRISCVTargetMC().
LLVMInitializeRISCVTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVTargetMC ()
Definition at line 340 of file RISCVMCTargetDesc.cpp.
References llvm::createRISCVAsmBackend(), createRISCVAsmTargetStreamer(), llvm::createRISCVELFStreamer(), createRISCVInstrAnalysis(), createRISCVMCAsmInfo(), llvm::createRISCVMCCodeEmitter(), createRISCVMCInstPrinter(), createRISCVMCInstrInfo(), createRISCVMCObjectFileInfo(), createRISCVMCRegisterInfo(), createRISCVMCSubtargetInfo(), createRISCVNullTargetStreamer(), createRISCVObjectTargetStreamer(), llvm::getTheRISCV32Target(), llvm::getTheRISCV64Target(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCAsmInfo(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCObjectFileInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), and llvm::TargetRegistry::RegisterObjectTargetStreamer().