LLVM: lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp File Reference
RISCVAsmParser.cpp File Reference
#include "MCTargetDesc/RISCVAsmBackend.h"
#include "MCTargetDesc/RISCVBaseInfo.h"
#include "MCTargetDesc/RISCVInstPrinter.h"
#include "MCTargetDesc/RISCVMCExpr.h"
#include "MCTargetDesc/RISCVMCTargetDesc.h"
#include "MCTargetDesc/RISCVMatInt.h"
#include "MCTargetDesc/RISCVTargetStreamer.h"
#include "TargetInfo/RISCVTargetInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCValue.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/RISCVAttributes.h"
#include "llvm/TargetParser/RISCVISAInfo.h"
#include <limits>
#include "RISCVGenAsmMatcher.inc"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "riscv-asm-parser"
#define GET_ASSEMBLER_HEADER
#define GET_OPERAND_DIAGNOSTIC_TYPES
#define GET_REGISTER_MATCHER
#define GET_SUBTARGET_FEATURE_NAME
#define GET_MATCHER_IMPLEMENTATION
#define GET_MNEMONIC_SPELL_CHECKER
Functions
STATISTIC (RISCVNumInstrsCompressed, "Number of RISC-V Compressed instructions emitted")
static MCRegister convertFPR64ToFPR16 (MCRegister Reg)
static MCRegister convertFPR64ToFPR32 (MCRegister Reg)
static MCRegister convertVRToVRMx (const MCRegisterInfo &RI, MCRegister Reg, unsigned Kind)
bool isValidInsnFormat (StringRef Format, bool AllowC)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVAsmParser ()
Variables
static cl::opt< bool > AddBuildAttributes ("riscv-add-build-attributes", cl::init(false))
const SubtargetFeatureKV llvm::RISCVFeatureKV [RISCV::NumSubtargetFeatures]
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-asm-parser"
Definition at line 47 of file RISCVAsmParser.cpp.
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 193 of file RISCVAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 1289 of file RISCVAsmParser.cpp.
GET_MNEMONIC_SPELL_CHECKER
#define GET_MNEMONIC_SPELL_CHECKER
Definition at line 1290 of file RISCVAsmParser.cpp.
GET_OPERAND_DIAGNOSTIC_TYPES
#define GET_OPERAND_DIAGNOSTIC_TYPES
Definition at line 284 of file RISCVAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 1287 of file RISCVAsmParser.cpp.
GET_SUBTARGET_FEATURE_NAME
#define GET_SUBTARGET_FEATURE_NAME
Definition at line 1288 of file RISCVAsmParser.cpp.
Function Documentation
convertFPR64ToFPR16()
static MCRegister convertFPR64ToFPR16 (MCRegister Reg) static
Definition at line 1293 of file RISCVAsmParser.cpp.
References assert().
convertFPR64ToFPR32()
static MCRegister convertFPR64ToFPR32 (MCRegister Reg) static
Definition at line 1298 of file RISCVAsmParser.cpp.
References assert().
convertVRToVRMx()
static MCRegister convertVRToVRMx (const MCRegisterInfo & RI, MCRegister Reg, unsigned Kind) static
Definition at line 1303 of file RISCVAsmParser.cpp.
References llvm::MCRegisterInfo::getMatchingSuperReg().
isValidInsnFormat()
bool isValidInsnFormat (StringRef Format, bool AllowC)
Definition at line 3086 of file RISCVAsmParser.cpp.
References llvm::StringSwitch< T, R >::Cases(), and llvm::StringSwitch< T, R >::Default().
LLVMInitializeRISCVAsmParser()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVAsmParser ()
Definition at line 3764 of file RISCVAsmParser.cpp.
References llvm::getTheRISCV32Target(), llvm::getTheRISCV64Target(), X, and Y.
STATISTIC()
STATISTIC (RISCVNumInstrsCompressed , "Number of RISC-V Compressed instructions emitted")
Variable Documentation
AddBuildAttributes
cl::opt< bool > AddBuildAttributes("riscv-add-build-attributes", cl::init(false)) ("riscv-add-build-attributes" , cl::init(false)) static