LLVM: lib/Target/RISCV/Disassembler/RISCVDisassembler.cpp File Reference
RISCVDisassembler.cpp File Reference
#include "MCTargetDesc/RISCVBaseInfo.h"
#include "MCTargetDesc/RISCVMCTargetDesc.h"
#include "TargetInfo/RISCVTargetInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDecoderOps.h"
#include "llvm/MC/MCDisassembler/MCDisassembler.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Endian.h"
#include "RISCVGenDisassemblerTables.inc"
Macros
#define DEBUG_TYPE "riscv-disassembler"
#define TRY_TO_DECODE_WITH_ADDITIONAL_OPERATION(FEATURE_CHECKS, DECODER_TABLE, DESC, ADDITIONAL_OPERATION)
#define TRY_TO_DECODE_AND_ADD_SP(FEATURE_CHECKS, DECODER_TABLE, DESC)
#define TRY_TO_DECODE(FEATURE_CHECKS, DECODER_TABLE, DESC)
#define TRY_TO_DECODE_FEATURE(FEATURE, DECODER_TABLE, DESC)
Functions
static MCDisassembler * createRISCVDisassembler (const Target &T, const MCSubtargetInfo &STI, MCContext &Ctx)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVDisassembler ()
static DecodeStatus DecodeGPRRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRX1X5RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR16RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR32RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR32CRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR64RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeFPR64CRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRNoX0RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRNoX0X2RegisterClass (MCInst &Inst, uint64_t RegNo, uint32_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRCRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeGPRPairRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeSR07RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const void *Decoder)
static DecodeStatus DecodeVRRegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVRM2RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVRM4RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus DecodeVRM8RegisterClass (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeVMaskReg (MCInst &Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeUImmOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeUImmNonZeroOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeSImmOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeSImmNonZeroOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
template<unsigned N>
static DecodeStatus decodeSImmOperandAndLsl1 (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeCLUIImmOperand (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeFRMArg (MCInst &Inst, uint32_t Imm, int64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeRVCInstrRdRs1ImmZero (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeRVCInstrRdSImm (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeRVCInstrRdRs1UImm (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeRVCInstrRdRs2 (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeRVCInstrRdRs1Rs2 (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeXTHeadMemPair (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeZcmpRlist (MCInst &Inst, uint32_t Imm, uint64_t Address, const void *Decoder)
static DecodeStatus decodeRegReg (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
static DecodeStatus decodeZcmpSpimm (MCInst &Inst, uint32_t Imm, uint64_t Address, const void *Decoder)
static DecodeStatus decodeCSSPushPopchk (MCInst &Inst, uint32_t Insn, uint64_t Address, const MCDisassembler *Decoder)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-disassembler"
Definition at line 28 of file RISCVDisassembler.cpp.
TRY_TO_DECODE
#define TRY_TO_DECODE (FEATURE_CHECKS, DECODER_TABLE, DESC)
Value:
  TRY_TO_DECODE_WITH_ADDITIONAL_OPERATION(FEATURE_CHECKS, DECODER_TABLE, DESC, \
                                          (void)nullptr)
Definition at line 528 of file RISCVDisassembler.cpp.
TRY_TO_DECODE_AND_ADD_SP
#define TRY_TO_DECODE_AND_ADD_SP (FEATURE_CHECKS, DECODER_TABLE, DESC)
Value:
  TRY_TO_DECODE_WITH_ADDITIONAL_OPERATION(FEATURE_CHECKS, DECODER_TABLE, DESC, \
                                          addSPOperands(MI))
Definition at line 525 of file RISCVDisassembler.cpp.
TRY_TO_DECODE_FEATURE
#define TRY_TO_DECODE_FEATURE (FEATURE, DECODER_TABLE, DESC)
Value:
  TRY_TO_DECODE(STI.hasFeature(FEATURE), DECODER_TABLE, DESC)
Definition at line 531 of file RISCVDisassembler.cpp.
TRY_TO_DECODE_WITH_ADDITIONAL_OPERATION
#define TRY_TO_DECODE_WITH_ADDITIONAL_OPERATION (FEATURE_CHECKS, DECODER_TABLE, DESC, ADDITIONAL_OPERATION)
Value:
  do {                                                                         \
    if (FEATURE_CHECKS) {                                                      \
      LLVM_DEBUG(dbgs() << "Trying " DESC ":\n");                              \
      DecodeStatus Result =                                                    \
          decodeInstruction(DECODER_TABLE, MI, Insn, Address, this, STI);      \
      if (Result != MCDisassembler::Fail) {                                    \
        ADDITIONAL_OPERATION;                                                  \
        return Result;                                                         \
      }                                                                        \
    }                                                                          \
  } while (false)
Definition at line 512 of file RISCVDisassembler.cpp.
Function Documentation
createRISCVDisassembler()
static MCDisassembler * createRISCVDisassembler (const Target & T, const MCSubtargetInfo & STI, MCContext & Ctx) static
Definition at line 57 of file RISCVDisassembler.cpp.
Referenced by LLVMInitializeRISCVDisassembler().
decodeCLUIImmOperand()
static DecodeStatus decodeCLUIImmOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 326 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::isUInt(), llvm::SignExtend64(), and llvm::MCDisassembler::Success.
decodeCSSPushPopchk()
static DecodeStatus decodeCSSPushPopchk (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 398 of file RISCVDisassembler.cpp.
References assert(), DecodeGPRX1X5RegisterClass(), Insn, and llvm::MCDisassembler::Success.
DecodeFPR16RegisterClass()
static DecodeStatus DecodeFPR16RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 95 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeFPR32CRegisterClass()
static DecodeStatus DecodeFPR32CRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 117 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeFPR32RegisterClass()
static DecodeStatus DecodeFPR32RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 106 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeFPR64CRegisterClass()
static DecodeStatus DecodeFPR64CRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 139 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeFPR64RegisterClass()
static DecodeStatus DecodeFPR64RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 128 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
decodeFRMArg()
static DecodeStatus decodeFRMArg (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 337 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, llvm::isUInt(), llvm::RISCVFPRndMode::isValidRoundingMode(), and llvm::MCDisassembler::Success.
DecodeGPRCRegisterClass()
static DecodeStatus DecodeGPRCRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 170 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeGPRNoX0RegisterClass()
static DecodeStatus DecodeGPRNoX0RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 150 of file RISCVDisassembler.cpp.
References DecodeGPRRegisterClass(), and llvm::MCDisassembler::Fail.
Referenced by DecodeGPRNoX0X2RegisterClass(), and decodeRVCInstrRdRs1ImmZero().
DecodeGPRNoX0X2RegisterClass()
static DecodeStatus DecodeGPRNoX0X2RegisterClass (MCInst & Inst, uint64_t RegNo, uint32_t Address, const MCDisassembler * Decoder) static
Definition at line 161 of file RISCVDisassembler.cpp.
References DecodeGPRNoX0RegisterClass(), and llvm::MCDisassembler::Fail.
DecodeGPRPairRegisterClass()
static DecodeStatus DecodeGPRPairRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 181 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeGPRRegisterClass()
static DecodeStatus DecodeGPRRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 71 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCDisassembler::getSubtargetInfo(), llvm::MCSubtargetInfo::hasFeature(), and llvm::MCDisassembler::Success.
Referenced by DecodeGPRNoX0RegisterClass(), decodeRegReg(), decodeRVCInstrRdRs1Rs2(), decodeRVCInstrRdRs2(), and decodeXTHeadMemPair().
DecodeGPRX1X5RegisterClass()
static DecodeStatus DecodeGPRX1X5RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 84 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
Referenced by decodeCSSPushPopchk().
decodeRegReg()
static DecodeStatus decodeRegReg (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 488 of file RISCVDisassembler.cpp.
References DecodeGPRRegisterClass(), Insn, and llvm::MCDisassembler::Success.
decodeRVCInstrRdRs1ImmZero()
static DecodeStatus decodeRVCInstrRdRs1ImmZero (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 386 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), DecodeGPRNoX0RegisterClass(), llvm::MCInst::getOperand(), Insn, and llvm::MCDisassembler::Success.
decodeRVCInstrRdRs1Rs2()
static DecodeStatus decodeRVCInstrRdRs1Rs2 (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 443 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), DecodeGPRRegisterClass(), llvm::MCInst::getOperand(), Insn, and llvm::MCDisassembler::Success.
decodeRVCInstrRdRs1UImm()
static DecodeStatus decodeRVCInstrRdRs1UImm (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 420 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createReg(), decodeUImmOperand(), llvm::MCInst::getOperand(), Insn, and llvm::MCDisassembler::Success.
decodeRVCInstrRdRs2()
static DecodeStatus decodeRVCInstrRdRs2 (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 433 of file RISCVDisassembler.cpp.
References DecodeGPRRegisterClass(), Insn, and llvm::MCDisassembler::Success.
decodeRVCInstrRdSImm()
static DecodeStatus decodeRVCInstrRdSImm (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 408 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createReg(), decodeSImmOperand(), Insn, and llvm::MCDisassembler::Success.
decodeSImmNonZeroOperand()
template<unsigned N> static DecodeStatus decodeSImmNonZeroOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 306 of file RISCVDisassembler.cpp.
References decodeSImmOperand(), and llvm::MCDisassembler::Fail.
decodeSImmOperand()
template<unsigned N> static DecodeStatus decodeSImmOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 296 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::isUInt(), llvm::SignExtend64(), and llvm::MCDisassembler::Success.
Referenced by decodeRVCInstrRdSImm(), and decodeSImmNonZeroOperand().
decodeSImmOperandAndLsl1()
template<unsigned N> static DecodeStatus decodeSImmOperandAndLsl1 (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 315 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::isUInt(), llvm::SignExtend64(), and llvm::MCDisassembler::Success.
DecodeSR07RegisterClass()
static DecodeStatus DecodeSR07RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const void * Decoder) static
Definition at line 192 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
decodeUImmNonZeroOperand()
template<unsigned N> static DecodeStatus decodeUImmNonZeroOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 287 of file RISCVDisassembler.cpp.
References decodeUImmOperand(), and llvm::MCDisassembler::Fail.
decodeUImmOperand()
template<unsigned N> static DecodeStatus decodeUImmOperand (MCInst & Inst, uint32_t Imm, int64_t Address, const MCDisassembler * Decoder) static
Definition at line 278 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), llvm::isUInt(), and llvm::MCDisassembler::Success.
Referenced by decodeRVCInstrRdRs1UImm(), decodeUImmNonZeroOperand(), and decodeXTHeadMemPair().
decodeVMaskReg()
static DecodeStatus decodeVMaskReg (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 265 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
DecodeVRM2RegisterClass()
static DecodeStatus DecodeVRM2RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 214 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCRegisterInfo::getMatchingSuperReg(), and llvm::MCDisassembler::Success.
DecodeVRM4RegisterClass()
static DecodeStatus DecodeVRM4RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 231 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCRegisterInfo::getMatchingSuperReg(), and llvm::MCDisassembler::Success.
DecodeVRM8RegisterClass()
static DecodeStatus DecodeVRM8RegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 248 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, llvm::MCRegisterInfo::getMatchingSuperReg(), and llvm::MCDisassembler::Success.
DecodeVRRegisterClass()
static DecodeStatus DecodeVRRegisterClass (MCInst & Inst, uint32_t RegNo, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 203 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createReg(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
decodeXTHeadMemPair()
static DecodeStatus decodeXTHeadMemPair (MCInst & Inst, uint32_t Insn, uint64_t Address, const MCDisassembler * Decoder) static
Definition at line 454 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createImm(), DecodeGPRRegisterClass(), decodeUImmOperand(), llvm::MCInst::getOpcode(), Insn, and llvm::MCDisassembler::Success.
decodeZcmpRlist()
static DecodeStatus decodeZcmpRlist (MCInst & Inst, uint32_t Imm, uint64_t Address, const void * Decoder) static
Definition at line 480 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), llvm::MCDisassembler::Fail, and llvm::MCDisassembler::Success.
decodeZcmpSpimm()
static DecodeStatus decodeZcmpSpimm (MCInst & Inst, uint32_t Imm, uint64_t Address, const void * Decoder) static
Definition at line 497 of file RISCVDisassembler.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), and llvm::MCDisassembler::Success.
LLVMInitializeRISCVDisassembler()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeRISCVDisassembler ()
Definition at line 63 of file RISCVDisassembler.cpp.
References createRISCVDisassembler(), llvm::getTheRISCV32Target(), llvm::getTheRISCV64Target(), and llvm::TargetRegistry::RegisterMCDisassembler().