LLVM: lib/Target/RISCV/RISCVISelDAGToDAG.cpp File Reference
RISCVISelDAGToDAG.cpp File Reference
#include "RISCVISelDAGToDAG.h"
#include "MCTargetDesc/RISCVBaseInfo.h"
#include "MCTargetDesc/RISCVMCTargetDesc.h"
#include "MCTargetDesc/RISCVMatInt.h"
#include "RISCVISelLowering.h"
#include "RISCVMachineFunctionInfo.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/IR/IntrinsicsRISCV.h"
#include "llvm/Support/Alignment.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "RISCVGenSearchableTables.inc"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::RISCV
Macros
#define DEBUG_TYPE "riscv-isel"
#define PASS_NAME "RISC-V DAG->DAG Pattern Instruction Selection"
#define GET_RISCVVSSEGTable_IMPL
#define GET_RISCVVLSEGTable_IMPL
#define GET_RISCVVLXSEGTable_IMPL
#define GET_RISCVVSXSEGTable_IMPL
#define GET_RISCVVLETable_IMPL
#define GET_RISCVVSETable_IMPL
#define GET_RISCVVLXTable_IMPL
#define GET_RISCVVSXTable_IMPL
#define CASE_VMSLT_VMNAND_VMSET_OPCODES(lmulenum, suffix, suffix_b)
#define CASE_VMSLT_OPCODES(lmulenum, suffix, suffix_b)
#define CASE_VMXOR_VMANDN_VMOR_OPCODES(lmulenum, suffix)
Functions
static SDValue selectImmSeq (SelectionDAG *CurDAG, const SDLoc &DL, const MVT VT, RISCVMatInt::InstSeq &Seq)
static SDValue selectImm (SelectionDAG *CurDAG, const SDLoc &DL, const MVT VT, int64_t Imm, const RISCVSubtarget &Subtarget)
static SDValue createTuple (SelectionDAG &CurDAG, ArrayRef< SDValue > Regs, unsigned NF, RISCVII::VLMUL LMUL)
static bool selectConstantAddr (SelectionDAG *CurDAG, const SDLoc &DL, const MVT VT, const RISCVSubtarget *Subtarget, SDValue Addr, SDValue &Base, SDValue &Offset, bool IsPrefetch=false)
static bool isWorthFoldingAdd (SDValue Add)
static bool vectorPseudoHasAllNBitUsers (SDNode *User, unsigned UserOpNo, unsigned Bits, const TargetInstrInfo *TII)
static SDValue findVSplat (SDValue N)
static bool selectVSplatImmHelper (SDValue N, SDValue &SplatVal, SelectionDAG &DAG, const RISCVSubtarget &Subtarget, std::function< bool(int64_t)> ValidateImm)
static SDValue getMaskSetter (SDValue MaskOp, SDValue GlueOp)
static bool usesAllOnesMask (SDValue MaskOp, SDValue GlueOp)
static bool usesAllOnesMask (SDNode *N, unsigned MaskOpIdx)
static bool isImplicitDef (SDValue V)
static bool IsVMerge (SDNode *N)
static bool IsVMv (SDNode *N)
static unsigned GetVMSetForLMul (RISCVII::VLMUL LMUL)
Variables
static cl::opt< bool > UsePseudoMovImm ("riscv-use-rematerializable-movimm", cl::Hidden, cl::desc("Use a rematerializable pseudoinstruction for 2 instruction " "constant materialization"), cl::init(false))
Macro Definition Documentation
CASE_VMSLT_OPCODES
#define CASE_VMSLT_OPCODES (lmulenum, suffix, suffix_b)
Value:
  case RISCVII::VLMUL::lmulenum:                                               \
    VMSLTOpcode = IsUnsigned ? RISCV::PseudoVMSLTU_VX_##suffix                 \
                             : RISCV::PseudoVMSLT_VX_##suffix;                 \
    VMSLTMaskOpcode = IsUnsigned ? RISCV::PseudoVMSLTU_VX_##suffix##_MASK      \
                                 : RISCV::PseudoVMSLT_VX_##suffix##_MASK;      \
    break;
Referenced by llvm::RISCVDAGToDAGISel::Select().
CASE_VMSLT_VMNAND_VMSET_OPCODES
#define CASE_VMSLT_VMNAND_VMSET_OPCODES (lmulenum, suffix, suffix_b)
Value:
  case RISCVII::VLMUL::lmulenum:                                               \
    VMSLTOpcode = IsUnsigned ? RISCV::PseudoVMSLTU_VX_##suffix                 \
                             : RISCV::PseudoVMSLT_VX_##suffix;                 \
    VMNANDOpcode = RISCV::PseudoVMNAND_MM_##suffix;                            \
    VMSetOpcode = RISCV::PseudoVMSET_M_##suffix_b;                             \
    break;
Referenced by llvm::RISCVDAGToDAGISel::Select().
CASE_VMXOR_VMANDN_VMOR_OPCODES
#define CASE_VMXOR_VMANDN_VMOR_OPCODES (lmulenum, suffix)
Value:
  case RISCVII::VLMUL::lmulenum:                                               \
    VMXOROpcode = RISCV::PseudoVMXOR_MM_##suffix;                              \
    VMANDNOpcode = RISCV::PseudoVMANDN_MM_##suffix;                            \
    VMOROpcode = RISCV::PseudoVMOR_MM_##suffix;                                \
    break;
Referenced by llvm::RISCVDAGToDAGISel::Select().
DEBUG_TYPE
#define DEBUG_TYPE "riscv-isel"
Definition at line 28 of file RISCVISelDAGToDAG.cpp.
GET_RISCVVLETable_IMPL
#define GET_RISCVVLETable_IMPL
Definition at line 42 of file RISCVISelDAGToDAG.cpp.
GET_RISCVVLSEGTable_IMPL
#define GET_RISCVVLSEGTable_IMPL
Definition at line 39 of file RISCVISelDAGToDAG.cpp.
GET_RISCVVLXSEGTable_IMPL
#define GET_RISCVVLXSEGTable_IMPL
Definition at line 40 of file RISCVISelDAGToDAG.cpp.
GET_RISCVVLXTable_IMPL
#define GET_RISCVVLXTable_IMPL
Definition at line 44 of file RISCVISelDAGToDAG.cpp.
GET_RISCVVSETable_IMPL
#define GET_RISCVVSETable_IMPL
Definition at line 43 of file RISCVISelDAGToDAG.cpp.
GET_RISCVVSSEGTable_IMPL
#define GET_RISCVVSSEGTable_IMPL
Definition at line 38 of file RISCVISelDAGToDAG.cpp.
GET_RISCVVSXSEGTable_IMPL
#define GET_RISCVVSXSEGTable_IMPL
Definition at line 41 of file RISCVISelDAGToDAG.cpp.
GET_RISCVVSXTable_IMPL
#define GET_RISCVVSXTable_IMPL
Definition at line 45 of file RISCVISelDAGToDAG.cpp.
PASS_NAME
#define PASS_NAME "RISC-V DAG->DAG Pattern Instruction Selection"
Definition at line 29 of file RISCVISelDAGToDAG.cpp.
Function Documentation
createTuple()
static SDValue createTuple (SelectionDAG & CurDAG, ArrayRef< SDValue > Regs, unsigned NF, RISCVII::VLMUL LMUL) static
Definition at line 239 of file RISCVISelDAGToDAG.cpp.
References assert(), DL, llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), I, llvm_unreachable, llvm::RISCVII::LMUL_1, llvm::RISCVII::LMUL_2, llvm::RISCVII::LMUL_4, llvm::RISCVII::LMUL_F2, llvm::RISCVII::LMUL_F4, llvm::RISCVII::LMUL_F8, N, llvm::SmallVectorTemplateBase< T, bool >::push_back(), SDValue(), and llvm::ArrayRef< T >::size().
findVSplat()
static SDValue findVSplat (SDValue N) static
Definition at line 3306 of file RISCVISelDAGToDAG.cpp.
References assert(), llvm::ISD::INSERT_SUBVECTOR, N, SDValue(), llvm::Splat, llvm::RISCVISD::VMV_S_X_VL, and llvm::RISCVISD::VMV_V_X_VL.
Referenced by llvm::RISCVDAGToDAGISel::selectVSplat(), and selectVSplatImmHelper().
getMaskSetter()
static SDValue getMaskSetter (SDValue MaskOp, SDValue GlueOp) static
Definition at line 3529 of file RISCVISelDAGToDAG.cpp.
References llvm::cast(), llvm::ISD::CopyToReg, llvm::SDNode::getMachineOpcode(), llvm::SDValue::getNode(), llvm::SDNode::getOperand(), getReg(), llvm::isa(), llvm::SDNode::isMachineOpcode(), and SDValue().
Referenced by usesAllOnesMask().
GetVMSetForLMul()
static unsigned GetVMSetForLMul (RISCVII::VLMUL LMUL) static
Definition at line 3658 of file RISCVISelDAGToDAG.cpp.
References llvm_unreachable, llvm::RISCVII::LMUL_1, llvm::RISCVII::LMUL_2, llvm::RISCVII::LMUL_4, llvm::RISCVII::LMUL_8, llvm::RISCVII::LMUL_F2, llvm::RISCVII::LMUL_F4, llvm::RISCVII::LMUL_F8, and llvm::RISCVII::LMUL_RESERVED.
isImplicitDef()
static bool isImplicitDef (SDValue V) static
Definition at line 3583 of file RISCVISelDAGToDAG.cpp.
References I, and isImplicitDef().
Referenced by isImplicitDef().
IsVMerge()
static bool IsVMerge (SDNode * N) static
Definition at line 3650 of file RISCVISelDAGToDAG.cpp.
References llvm::RISCV::getRVVMCOpcode(), and N.
IsVMv()
static bool IsVMv (SDNode * N) static
Definition at line 3654 of file RISCVISelDAGToDAG.cpp.
References llvm::RISCV::getRVVMCOpcode(), and N.
isWorthFoldingAdd()
static bool isWorthFoldingAdd (SDValue Add) static
Definition at line 2499 of file RISCVISelDAGToDAG.cpp.
References llvm::Add, llvm::cast(), llvm::EVT::isScalarInteger(), and llvm::Value::uses().
Referenced by llvm::RISCVDAGToDAGISel::SelectAddrRegImm().
selectConstantAddr()
static bool selectConstantAddr (SelectionDAG * CurDAG, const SDLoc & DL, const MVT VT, const RISCVSubtarget * Subtarget, SDValue Addr, SDValue & Base, SDValue & Offset, bool IsPrefetch = false) static
Definition at line 2446 of file RISCVISelDAGToDAG.cpp.
References Addr, assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::sampleprof::Base, llvm::cast(), DL, llvm::SmallVectorBase< Size_T >::empty(), llvm::RISCVMatInt::generateInstSeq(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetConstant(), llvm::Hi, llvm::RISCVSubtarget::is64Bit(), llvm::isa(), llvm::isInt(), llvm::Offset, llvm::SmallVectorTemplateBase< T, bool >::pop_back(), SDValue(), selectImmSeq(), and llvm::SignExtend64().
Referenced by llvm::RISCVDAGToDAGISel::SelectAddrRegImm(), and llvm::RISCVDAGToDAGISel::SelectAddrRegImmLsb00000().
selectImm()
static SDValue selectImm (SelectionDAG * CurDAG, const SDLoc & DL, const MVT VT, int64_t Imm, const RISCVSubtarget & Subtarget) static
Definition at line 204 of file RISCVISelDAGToDAG.cpp.
References DL, llvm::SmallVectorBase< Size_T >::empty(), llvm::RISCVMatInt::generateInstSeq(), llvm::RISCVMatInt::generateTwoRegInstSeq(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getTargetConstant(), llvm::Lo, SDValue(), selectImmSeq(), llvm::SmallVectorBase< Size_T >::size(), and UsePseudoMovImm.
Referenced by llvm::RISCVDAGToDAGISel::Select(), and llvm::RISCVDAGToDAGISel::selectFPImm().
selectImmSeq()
static SDValue selectImmSeq (SelectionDAG * CurDAG, const SDLoc & DL, const MVT VT, RISCVMatInt::InstSeq & Seq) static
Definition at line 175 of file RISCVISelDAGToDAG.cpp.
References DL, llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getTargetConstant(), llvm::RISCVMatInt::Imm, llvm::RISCVMatInt::RegImm, llvm::RISCVMatInt::RegReg, llvm::RISCVMatInt::RegX0, and SDValue().
Referenced by selectConstantAddr(), and selectImm().
selectVSplatImmHelper()
static bool selectVSplatImmHelper (SDValue N, SDValue & SplatVal, SelectionDAG & DAG, const RISCVSubtarget & Subtarget, std::function< bool(int64_t)> ValidateImm) static
Definition at line 3330 of file RISCVISelDAGToDAG.cpp.
References assert(), findVSplat(), llvm::APInt::getSExtValue(), llvm::SelectionDAG::getTargetConstant(), llvm::RISCVSubtarget::getXLenVT(), llvm::isa(), N, llvm::APInt::sextOrTrunc(), and llvm::Splat.
Referenced by llvm::RISCVDAGToDAGISel::selectVSplatSimm5(), llvm::RISCVDAGToDAGISel::selectVSplatSimm5Plus1(), llvm::RISCVDAGToDAGISel::selectVSplatSimm5Plus1NonZero(), and llvm::RISCVDAGToDAGISel::selectVSplatUimm().
usesAllOnesMask() [1/2]
static bool usesAllOnesMask (SDNode * N, unsigned MaskOpIdx) static
Definition at line 3578 of file RISCVISelDAGToDAG.cpp.
References N, and usesAllOnesMask().
usesAllOnesMask() [2/2]
static bool usesAllOnesMask (SDValue MaskOp, SDValue GlueOp) static
Definition at line 3557 of file RISCVISelDAGToDAG.cpp.
References llvm::SDValue::getMachineOpcode(), getMaskSetter(), and llvm::SDNode::isMachineOpcode().
Referenced by usesAllOnesMask().
vectorPseudoHasAllNBitUsers()
static bool vectorPseudoHasAllNBitUsers (SDNode * User, unsigned UserOpNo, unsigned Bits, const TargetInstrInfo * TII) static
Definition at line 3061 of file RISCVISelDAGToDAG.cpp.
References assert(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::RISCV::getRVVMCOpcode(), llvm::RISCV::getVectorLowDemandedScalarBits(), llvm::RISCVII::hasSEWOp(), llvm::RISCVII::hasVecPolicyOp(), llvm::RISCVII::hasVLOp(), TII, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::RISCVDAGToDAGISel::hasAllNBitUsers().
Variable Documentation
UsePseudoMovImm
cl::opt< bool > UsePseudoMovImm("riscv-use-rematerializable-movimm", cl::Hidden, cl::desc("Use a rematerializable pseudoinstruction for 2 instruction " "constant materialization"), cl::init(false)) ("riscv-use-rematerializable-movimm" , cl::Hidden , cl::desc("Use a rematerializable pseudoinstruction for 2 instruction " "constant materialization") , cl::init(false)) static
Referenced by selectImm().