LLVM: lib/Target/RISCV/GISel/RISCVLegalizerInfo.cpp File Reference
RISCVLegalizerInfo.cpp File Reference
This file implements the targeting of the Machinelegalizer class for RISC-V.
#include "RISCVLegalizerInfo.h"
#include "MCTargetDesc/RISCVMatInt.h"
#include "RISCVMachineFunctionInfo.h"
#include "RISCVSubtarget.h"
#include "llvm/CodeGen/GlobalISel/GIMatchTableExecutor.h"
#include "llvm/CodeGen/GlobalISel/GenericMachineInstrs.h"
#include "llvm/CodeGen/GlobalISel/LegalizerHelper.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Type.h"
Functions
static LegalityPredicate typeIsScalarFPArith (unsigned TypeIdx, const RISCVSubtarget &ST)
static LegalityPredicate typeIsLegalIntOrFPVec (unsigned TypeIdx, std::initializer_list< LLT > IntOrFPVecTys, const RISCVSubtarget &ST)
static LegalityPredicate typeIsLegalBoolVec (unsigned TypeIdx, std::initializer_list< LLT > BoolVecTys, const RISCVSubtarget &ST)
static LLT getMaskTypeFor (LLT VecTy)
Return the type of the mask type suitable for masking the provided vector type.
static MachineInstrBuilder buildAllOnesMask (LLT VecTy, const SrcOp &VL, MachineIRBuilder &MIB, MachineRegisterInfo &MRI)
Creates an all ones mask suitable for masking a vector of type VecTy with vector length VL.
static std::pair< MachineInstrBuilder, Register > buildDefaultVLOps (const DstOp &Dst, MachineIRBuilder &MIB, MachineRegisterInfo &MRI)
Gets the two common "VL" operands: an all-ones mask and the vector length.
static MachineInstrBuilder buildSplatPartsS64WithVL (const DstOp &Dst, const SrcOp &Passthru, Register Lo, Register Hi, Register VL, MachineIRBuilder &MIB, MachineRegisterInfo &MRI)
static MachineInstrBuilder buildSplatSplitS64WithVL (const DstOp &Dst, const SrcOp &Passthru, const SrcOp &Scalar, Register VL, MachineIRBuilder &MIB, MachineRegisterInfo &MRI)
Detailed Description
This file implements the targeting of the Machinelegalizer class for RISC-V.
Todo
This should be generated by TableGen.
Definition in file RISCVLegalizerInfo.cpp.
Function Documentation
buildAllOnesMask()
static MachineInstrBuilder buildAllOnesMask (LLT VecTy, const SrcOp & VL, MachineIRBuilder & MIB, MachineRegisterInfo & MRI) static
Creates an all ones mask suitable for masking a vector of type VecTy with vector length VL.
Definition at line 665 of file RISCVLegalizerInfo.cpp.
References llvm::MachineIRBuilder::buildInstr(), and getMaskTypeFor().
Referenced by buildDefaultVLOps().
buildDefaultVLOps()
static std::pair< MachineInstrBuilder, Register > buildDefaultVLOps (const DstOp & Dst, MachineIRBuilder & MIB, MachineRegisterInfo & MRI) static
Gets the two common "VL" operands: an all-ones mask and the vector length.
VecTy is a scalable vector type.
Definition at line 675 of file RISCVLegalizerInfo.cpp.
References assert(), buildAllOnesMask(), llvm::LLT::isScalableVector(), and MRI.
buildSplatPartsS64WithVL()
static MachineInstrBuilder buildSplatPartsS64WithVL (const DstOp & Dst, const SrcOp & Passthru, Register Lo, Register Hi, Register VL, MachineIRBuilder & MIB, MachineRegisterInfo & MRI) static
Definition at line 685 of file RISCVLegalizerInfo.cpp.
References llvm::MachineIRBuilder::buildInstr(), llvm::Hi, and llvm::Lo.
Referenced by buildSplatSplitS64WithVL().
buildSplatSplitS64WithVL()
static MachineInstrBuilder buildSplatSplitS64WithVL (const DstOp & Dst, const SrcOp & Passthru, const SrcOp & Scalar, Register VL, MachineIRBuilder & MIB, MachineRegisterInfo & MRI) static
Definition at line 701 of file RISCVLegalizerInfo.cpp.
References assert(), buildSplatPartsS64WithVL(), llvm::MachineIRBuilder::buildUnmerge(), llvm::SrcOp::getReg(), MRI, and llvm::LLT::scalar().
getMaskTypeFor()
static LLT getMaskTypeFor (LLT VecTy) static
Return the type of the mask type suitable for masking the provided vector type.
This is simply an i1 element type vector of the same (possibly scalable) length.
Definition at line 657 of file RISCVLegalizerInfo.cpp.
References assert(), llvm::LLT::getElementCount(), llvm::LLT::isVector(), llvm::LLT::scalar(), and llvm::LLT::vector().
Referenced by buildAllOnesMask(), getAllOnesMask(), lowerFMAXIMUM_FMINIMUM(), lowerVectorFTRUNC_FCEIL_FFLOOR_FROUND(), and llvm::RISCVTargetLowering::PerformDAGCombine().
typeIsLegalBoolVec()
static LegalityPredicate typeIsLegalBoolVec (unsigned TypeIdx, std::initializer_list< LLT > BoolVecTys, const RISCVSubtarget & ST) static
Definition at line 60 of file RISCVLegalizerInfo.cpp.
References llvm::LegalityPredicates::all(), P, and llvm::LegalityPredicates::typeInSet().
Referenced by llvm::RISCVLegalizerInfo::RISCVLegalizerInfo().
typeIsLegalIntOrFPVec()
static LegalityPredicate typeIsLegalIntOrFPVec (unsigned TypeIdx, std::initializer_list< LLT > IntOrFPVecTys, const RISCVSubtarget & ST) static
Definition at line 45 of file RISCVLegalizerInfo.cpp.
References llvm::LegalityPredicates::all(), P, and llvm::LegalityPredicates::typeInSet().
Referenced by llvm::RISCVLegalizerInfo::RISCVLegalizerInfo().
typeIsScalarFPArith()
static LegalityPredicate typeIsScalarFPArith (unsigned TypeIdx, const RISCVSubtarget & ST) static
Definition at line 34 of file RISCVLegalizerInfo.cpp.
Referenced by llvm::RISCVLegalizerInfo::RISCVLegalizerInfo().