LLVM: lib/Target/RISCV/RISCVVectorPeephole.cpp File Reference
RISCVVectorPeephole.cpp File Reference
#include "RISCV.h"
#include "RISCVISelDAGToDAG.h"
#include "RISCVSubtarget.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "riscv-vector-peephole"
#define CASE_VMERGE_TO_VMV(lmul)
Functions
INITIALIZE_PASS (RISCVVectorPeephole, DEBUG_TYPE, "RISC-V Fold Masks", false, false) bool RISCVVectorPeephole
Macro Definition Documentation
CASE_VMERGE_TO_VMV
#define CASE_VMERGE_TO_VMV (lmul)
Value:
  case RISCV::PseudoVMERGE_VVM_##lmul:                                         \
    NewOpc = RISCV::PseudoVMV_V_V_##lmul;                                      \
    break;
DEBUG_TYPE
#define DEBUG_TYPE "riscv-vector-peephole"
Definition at line 40 of file RISCVVectorPeephole.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RISCVVectorPeephole , DEBUG_TYPE , "RISC-V Fold Masks" , false , false)
Definition at line 75 of file RISCVVectorPeephole.cpp.
References assert(), llvm::RISCVVType::decodeVLMUL(), llvm::RISCVII::getLMul(), llvm::RISCVII::getSEWOpNum(), llvm::RISCVII::getVLOpNum(), llvm::RISCVII::hasSEWOp(), llvm::RISCVII::hasVLOp(), if(), llvm::RISCVVType::isValidSEW(), MI, MRI, and llvm::RISCV::VLMaxSentinel.