LLVM: lib/Target/RISCV/RISCVGatherScatterLowering.cpp File Reference
RISCVGatherScatterLowering.cpp File Reference
#include "RISCV.h"
#include "RISCVTargetMachine.h"
#include "llvm/Analysis/InstSimplifyFolder.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Analysis/VectorUtils.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/IntrinsicsRISCV.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Transforms/Utils/Local.h"
#include <optional>
Macros
#define DEBUG_TYPE "riscv-gather-scatter-lowering"
Functions
INITIALIZE_PASS (RISCVGatherScatterLowering, DEBUG_TYPE, "RISC-V gather/scatter lowering pass", false, false) FunctionPass *llvm
static std::pair< Value *, Value * > matchStridedConstant (Constant *StartC)
static std::pair< Value *, Value * > matchStridedStart (Value *Start, IRBuilderBase &Builder)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-gather-scatter-lowering"
Definition at line 32 of file RISCVGatherScatterLowering.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RISCVGatherScatterLowering , DEBUG_TYPE , "RISC-V gather/scatter lowering pass" , false , false)
Definition at line 82 of file RISCVGatherScatterLowering.cpp.
matchStridedConstant()
static std::pair< Value *, Value * > matchStridedConstant (Constant * StartC) static
Definition at line 90 of file RISCVGatherScatterLowering.cpp.
References llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast_or_null(), llvm::Constant::getAggregateElement(), llvm::Value::getType(), llvm::ConstantInt::getValue(), and llvm::isa().
Referenced by matchStridedStart().
matchStridedStart()
static std::pair< Value *, Value * > matchStridedStart (Value * Start, IRBuilderBase & Builder) static
Definition at line 122 of file RISCVGatherScatterLowering.cpp.
References llvm::cast(), llvm::dwarf_linker::DebugLoc, llvm::dyn_cast(), llvm::getSplatValue(), llvm::Instruction::isCommutative(), llvm_unreachable, llvm::PatternMatch::m_Intrinsic(), llvm::PatternMatch::match(), matchStridedConstant(), matchStridedStart(), and llvm::Splat.
Referenced by matchStridedStart().