LLVM: lib/Target/RISCV/RISCVTargetTransformInfo.cpp File Reference
RISCVTargetTransformInfo.cpp File Reference
#include "RISCVTargetTransformInfo.h"
#include "MCTargetDesc/RISCVMatInt.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/BasicTTIImpl.h"
#include "llvm/CodeGen/CostTable.h"
#include "llvm/CodeGen/TargetLowering.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/PatternMatch.h"
#include <cmath>
#include <optional>
#include "llvm/IR/VPIntrinsics.def"
Macros
#define DEBUG_TYPE "riscvtti"
#define HELPER_MAP_VPID_TO_VPSD(VPID, VPSD)
Functions
static InstructionCost getIntImmCostImpl (const DataLayout &DL, const RISCVSubtarget *ST, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind, bool FreeZeroes)
static bool canUseShiftPair (Instruction *Inst, const APInt &Imm)
static VectorType * getVRGatherIndexType (MVT DataVT, const RISCVSubtarget &ST, LLVMContext &C)
static unsigned getISDForVPIntrinsicID (Intrinsic::ID ID)
Variables
static cl::opt< unsigned > RVVRegisterWidthLMUL ("riscv-v-register-bit-width-lmul", cl::desc("The LMUL to use for getRegisterBitWidth queries. Affects LMUL used " "by autovectorized code. Fractional LMULs are not supported."), cl::init(2), cl::Hidden)
static cl::opt< unsigned > SLPMaxVF ("riscv-v-slp-max-vf", cl::desc("Overrides result used for getMaximumVF query which is used " "exclusively by SLP vectorizer."), cl::Hidden)
static const CostTblEntry VectorIntrinsicCostTable []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscvtti"
Definition at line 23 of file RISCVTargetTransformInfo.cpp.
HELPER_MAP_VPID_TO_VPSD
#define HELPER_MAP_VPID_TO_VPSD (VPID, VPSD)
Value:
  case Intrinsic::VPID:                                                        \
    return ISD::VPSD;
Function Documentation
canUseShiftPair()
static bool canUseShiftPair (Instruction * Inst, const APInt & Imm) static
Definition at line 137 of file RISCVTargetTransformInfo.cpp.
References llvm::cast(), llvm::countr_zero(), llvm::dyn_cast(), llvm::User::getOperand(), llvm::isa(), and llvm::isShiftedMask_64().
Referenced by llvm::RISCVTTIImpl::getIntImmCostInst().
getIntImmCostImpl()
static InstructionCost getIntImmCostImpl (const DataLayout & DL, const RISCVSubtarget * ST, const APInt & Imm, Type * Ty, TTI::TargetCostKind CostKind, bool FreeZeroes) static
Definition at line 112 of file RISCVTargetTransformInfo.cpp.
References assert(), DL, llvm::RISCVMatInt::getIntMatCost(), and llvm::TargetTransformInfo::TCC_Free.
Referenced by llvm::RISCVTTIImpl::getIntImmCost(), and llvm::RISCVTTIImpl::getIntImmCostInst().
getISDForVPIntrinsicID()
static unsigned getISDForVPIntrinsicID (Intrinsic::ID ID) static
Definition at line 823 of file RISCVTargetTransformInfo.cpp.
References llvm::ISD::DELETED_NODE.
Referenced by llvm::RISCVTTIImpl::getIntrinsicInstrCost().
getVRGatherIndexType()
static VectorType * getVRGatherIndexType (MVT DataVT, const RISCVSubtarget & ST, LLVMContext & C) static
Definition at line 346 of file RISCVTargetTransformInfo.cpp.
References assert(), llvm::MVT::bitsGT(), llvm::CallingConv::C, llvm::cast(), llvm::MVT::changeTypeToInteger(), llvm::MVT::changeVectorElementType(), llvm::MVT::getScalarSizeInBits(), llvm::MVT::getScalarType(), and llvm::MVT::getVectorNumElements().
Referenced by llvm::RISCVTTIImpl::getShuffleCost().
Variable Documentation
RVVRegisterWidthLMUL
cl::opt< unsigned > RVVRegisterWidthLMUL("riscv-v-register-bit-width-lmul", cl::desc("The LMUL to use for getRegisterBitWidth queries. Affects LMUL used " "by autovectorized code. Fractional LMULs are not supported."), cl::init(2), cl::Hidden) ("riscv-v-register-bit-width-lmul" , cl::desc("The LMUL to use for getRegisterBitWidth queries. Affects LMUL used " "by autovectorized code. Fractional LMULs are not supported.") , cl::init(2) , cl::Hidden) static
Referenced by llvm::RISCVTTIImpl::getRegisterBitWidth().
SLPMaxVF
cl::opt< unsigned > SLPMaxVF("riscv-v-slp-max-vf", cl::desc("Overrides result used for getMaximumVF query which is used " "exclusively by SLP vectorizer."), cl::Hidden) ("riscv-v-slp-max-vf" , cl::desc("Overrides result used for getMaximumVF query which is used " "exclusively by SLP vectorizer.") , cl::Hidden) static
Referenced by llvm::RISCVTTIImpl::getMaximumVF().
VectorIntrinsicCostTable
const CostTblEntry VectorIntrinsicCostTable[] static
Definition at line 765 of file RISCVTargetTransformInfo.cpp.
Referenced by llvm::RISCVTTIImpl::getIntrinsicInstrCost().