LLVM: lib/Target/Sparc/SparcTargetMachine.cpp File Reference
SparcTargetMachine.cpp File Reference
#include "SparcTargetMachine.h"
#include "LeonPasses.h"
#include "Sparc.h"
#include "SparcMachineFunctionInfo.h"
#include "SparcTargetObjectFile.h"
#include "TargetInfo/SparcTargetInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/MC/TargetRegistry.h"
#include <optional>
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSparcTarget ()
static std::string computeDataLayout (const Triple &T, bool is64Bit)
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM)
static CodeModel::Model getEffectiveSparcCodeModel (std::optional< CodeModel::Model > CM, Reloc::Model RM, bool Is64Bit, bool JIT)
Variables
static cl::opt< bool > BranchRelaxation ("sparc-enable-branch-relax", cl::Hidden, cl::init(true), cl::desc("Relax out of range conditional branches"))
Function Documentation
computeDataLayout()
static std::string computeDataLayout (const Triple & T, bool is64Bit) static
Definition at line 38 of file SparcTargetMachine.cpp.
References is64Bit(), and llvm::Triple::sparcel.
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM) static
Definition at line 65 of file SparcTargetMachine.cpp.
References llvm::Reloc::Static.
getEffectiveSparcCodeModel()
static CodeModel::Model getEffectiveSparcCodeModel (std::optional< CodeModel::Model > CM, Reloc::Model RM, bool Is64Bit, bool JIT) static
Definition at line 80 of file SparcTargetMachine.cpp.
References llvm::CodeModel::Kernel, llvm::CodeModel::Large, llvm::CodeModel::Medium, llvm::Reloc::PIC_, llvm::report_fatal_error(), llvm::CodeModel::Small, and llvm::CodeModel::Tiny.
LLVMInitializeSparcTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSparcTarget ()
Definition at line 24 of file SparcTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheSparcelTarget(), llvm::getTheSparcTarget(), llvm::getTheSparcV9Target(), llvm::initializeSparcDAGToDAGISelLegacyPass(), X, and Y.
Variable Documentation
BranchRelaxation
cl::opt< bool > BranchRelaxation("sparc-enable-branch-relax", cl::Hidden, cl::init(true), cl::desc("Relax out of range conditional branches")) ("sparc-enable-branch-relax" , cl::Hidden , cl::init(true) , cl::desc("Relax out of range conditional branches")) static