LLVM: lib/Target/SPIRV/MCTargetDesc/SPIRVMCCodeEmitter.cpp File Reference
SPIRVMCCodeEmitter.cpp File Reference
#include "MCTargetDesc/SPIRVMCTargetDesc.h"
#include "llvm/CodeGen/Register.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/EndianStream.h"
#include "SPIRVGenMCCodeEmitter.inc"
Macros
#define DEBUG_TYPE "spirv-mccodeemitter"
Typedefs
using EndianWriter = support::endian::Writer
Functions
static bool hasType (const MCInst &MI, const MCInstrInfo &MII)
static void emitOperand (const MCOperand &Op, SmallVectorImpl< char > &CB)
static void emitTypedInstrOperands (const MCInst &MI, SmallVectorImpl< char > &CB)
static void emitUntypedInstrOperands (const MCInst &MI, SmallVectorImpl< char > &CB)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-mccodeemitter"
Definition at line 27 of file SPIRVMCCodeEmitter.cpp.
Typedef Documentation
EndianWriter
using EndianWriter = support::endian::Writer
Definition at line 58 of file SPIRVMCCodeEmitter.cpp.
Function Documentation
emitOperand()
static void emitOperand (const MCOperand & Op, SmallVectorImpl< char > & CB) static
Definition at line 77 of file SPIRVMCCodeEmitter.cpp.
References llvm::little, llvm_unreachable, and llvm::support::endian::write().
Referenced by emitTypedInstrOperands(), and emitUntypedInstrOperands().
emitTypedInstrOperands()
static void emitTypedInstrOperands (const MCInst & MI, SmallVectorImpl< char > & CB) static
Definition at line 92 of file SPIRVMCCodeEmitter.cpp.
References emitOperand(), and MI.
emitUntypedInstrOperands()
static void emitUntypedInstrOperands (const MCInst & MI, SmallVectorImpl< char > & CB) static
Definition at line 102 of file SPIRVMCCodeEmitter.cpp.
References emitOperand(), and MI.
hasType()
static bool hasType (const MCInst & MI, const MCInstrInfo & MII) static
Definition at line 63 of file SPIRVMCCodeEmitter.cpp.
References llvm::MCInstrInfo::get(), llvm::MCInstrDesc::getNumDefs(), llvm::MCInstrDesc::getNumOperands(), MI, and llvm::MCInstrDesc::operands().