LLVM: lib/Target/SPIRV/SPIRVModuleAnalysis.cpp File Reference
SPIRVModuleAnalysis.cpp File Reference
#include "SPIRVModuleAnalysis.h"
#include "MCTargetDesc/SPIRVBaseInfo.h"
#include "MCTargetDesc/SPIRVMCTargetDesc.h"
#include "SPIRV.h"
#include "SPIRVSubtarget.h"
#include "SPIRVTargetMachine.h"
#include "SPIRVUtils.h"
#include "TargetInfo/SPIRVTargetInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/TargetPassConfig.h"
Classes
struct AvoidCapabilitiesSet
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
namespace llvm::SPIRV
Macros
#define DEBUG_TYPE "spirv-module-analysis"
#define ATOM_FLT_REQ_EXT_MSG(ExtName)
Typedefs
using InstrTraces = std::set<InstrSignature>
Functions
void llvm::initializeSPIRVModuleAnalysisPass (PassRegistry &)
INITIALIZE_PASS (SPIRVModuleAnalysis, DEBUG_TYPE, "SPIRV module analysis", true, true) static unsigned getMetadataUInt(MDNode *MdNode
static InstrSignature instrToSignature (MachineInstr &MI, SPIRV::ModuleAnalysisInfo &MAI)
static void collectOtherInstr (MachineInstr &MI, SPIRV::ModuleAnalysisInfo &MAI, SPIRV::ModuleSectionType MSType, InstrTraces &IS, bool Append=true)
static void addOpDecorateReqs (const MachineInstr &MI, unsigned DecIndex, SPIRV::RequirementHandler &Reqs, const SPIRVSubtarget &ST)
static void addOpTypeImageReqs (const MachineInstr &MI, SPIRV::RequirementHandler &Reqs, const SPIRVSubtarget &ST)
static void AddAtomicFloatRequirements (const MachineInstr &MI, SPIRV::RequirementHandler &Reqs, const SPIRVSubtarget &ST)
void addInstrRequirements (const MachineInstr &MI, SPIRV::RequirementHandler &Reqs, const SPIRVSubtarget &ST)
static void collectReqs (const Module &M, SPIRV::ModuleAnalysisInfo &MAI, MachineModuleInfo *MMI, const SPIRVSubtarget &ST)
static unsigned getFastMathFlags (const MachineInstr &I)
static void handleMIFlagDecoration (MachineInstr &I, const SPIRVSubtarget &ST, const SPIRVInstrInfo &TII, SPIRV::RequirementHandler &Reqs)
static void addDecorations (const Module &M, const SPIRVInstrInfo &TII, MachineModuleInfo *MMI, const SPIRVSubtarget &ST, SPIRV::ModuleAnalysisInfo &MAI)
Variables
static cl::opt< bool > SPVDumpDeps ("spv-dump-deps", cl::desc("Dump MIR with SPIR-V dependencies info"), cl::Optional, cl::init(false))
static cl::list< SPIRV::Capability::Capability > AvoidCapabilities ("avoid-spirv-capabilities", cl::desc("SPIR-V capabilities to avoid if there are " "other options enabling a feature"), cl::ZeroOrMore, cl::Hidden, cl::values(clEnumValN(SPIRV::Capability::Shader, "Shader", "SPIR-V Shader capability")))
unsigned OpIndex
unsigned unsigned DefaultVal
Macro Definition Documentation
ATOM_FLT_REQ_EXT_MSG
#define ATOM_FLT_REQ_EXT_MSG (ExtName)
Value:
  "The atomic float instruction requires the following SPIR-V "                \
  "extension: SPV_EXT_shader_atomic_float" ExtName
Definition at line 773 of file SPIRVModuleAnalysis.cpp.
Referenced by AddAtomicFloatRequirements().
DEBUG_TYPE
#define DEBUG_TYPE "spirv-module-analysis"
Definition at line 31 of file SPIRVModuleAnalysis.cpp.
Typedef Documentation
InstrTraces
using InstrTraces = std::set<InstrSignature>
Definition at line 373 of file SPIRVModuleAnalysis.cpp.
Function Documentation
AddAtomicFloatRequirements()
static void AddAtomicFloatRequirements (const MachineInstr & MI, SPIRV::RequirementHandler & Reqs, const SPIRVSubtarget & ST) static
Definition at line 776 of file SPIRVModuleAnalysis.cpp.
References llvm::SPIRV::RequirementHandler::addCapability(), llvm::SPIRV::RequirementHandler::addExtension(), assert(), ATOM_FLT_REQ_EXT_MSG, llvm::BitWidth, llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), MI, and llvm::report_fatal_error().
Referenced by addInstrRequirements().
addDecorations()
static void addDecorations (const Module & M, const SPIRVInstrInfo & TII, MachineModuleInfo * MMI, const SPIRVSubtarget & ST, SPIRV::ModuleAnalysisInfo & MAI) static
Definition at line 1312 of file SPIRVModuleAnalysis.cpp.
References F, llvm::MachineModuleInfo::getMachineFunction(), handleMIFlagDecoration(), MBB, MI, llvm::SPIRV::ModuleAnalysisInfo::Reqs, and TII.
Referenced by llvm::SPIRVModuleAnalysis::runOnModule().
addInstrRequirements()
void addInstrRequirements (const MachineInstr & MI, SPIRV::RequirementHandler & Reqs, const SPIRVSubtarget & ST)
Definition at line 833 of file SPIRVModuleAnalysis.cpp.
References AddAtomicFloatRequirements(), llvm::SPIRV::RequirementHandler::addCapability(), llvm::SPIRV::RequirementHandler::addExtension(), addOpDecorateReqs(), addOpTypeImageReqs(), Addr, assert(), llvm::BitWidth, llvm::SPIRV::RequirementHandler::getAndAddRequirements(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), MI, MRI, llvm::SPIRV::RequirementHandler::removeCapabilityIf(), and llvm::report_fatal_error().
Referenced by collectReqs().
addOpDecorateReqs()
static void addOpDecorateReqs (const MachineInstr & MI, unsigned DecIndex, SPIRV::RequirementHandler & Reqs, const SPIRVSubtarget & ST) static
Definition at line 687 of file SPIRVModuleAnalysis.cpp.
References llvm::SPIRV::RequirementHandler::addExtension(), llvm::SPIRV::RequirementHandler::addRequirements(), and MI.
Referenced by addInstrRequirements().
addOpTypeImageReqs()
static void addOpTypeImageReqs (const MachineInstr & MI, SPIRV::RequirementHandler & Reqs, const SPIRVSubtarget & ST) static
Definition at line 719 of file SPIRVModuleAnalysis.cpp.
References llvm::SPIRV::RequirementHandler::addRequirements(), assert(), llvm::SPIRV::RequirementHandler::getAndAddRequirements(), and MI.
Referenced by addInstrRequirements().
collectOtherInstr()
static void collectOtherInstr (MachineInstr & MI, SPIRV::ModuleAnalysisInfo & MAI, SPIRV::ModuleSectionType MSType, InstrTraces & IS, bool Append = true) static
Definition at line 401 of file SPIRVModuleAnalysis.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::insert(), instrToSignature(), MI, llvm::SPIRV::ModuleAnalysisInfo::MS, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SPIRV::ModuleAnalysisInfo::setSkipEmission().
collectReqs()
static void collectReqs (const Module & M, SPIRV::ModuleAnalysisInfo & MAI, MachineModuleInfo * MMI, const SPIRVSubtarget & ST) static
Definition at line 1191 of file SPIRVModuleAnalysis.cpp.
References llvm::SPIRV::RequirementHandler::addCapability(), llvm::SPIRV::RequirementHandler::addExtension(), addInstrRequirements(), llvm::CallingConv::C, llvm::cast(), llvm::dyn_cast(), F, llvm::SPIRV::RequirementHandler::getAndAddRequirements(), llvm::MachineModuleInfo::getMachineFunction(), llvm::MDNode::getOperand(), MBB, MI, and llvm::SPIRV::ModuleAnalysisInfo::Reqs.
Referenced by llvm::SPIRVModuleAnalysis::runOnModule().
getFastMathFlags()
static unsigned getFastMathFlags (const MachineInstr & I) static
Definition at line 1269 of file SPIRVModuleAnalysis.cpp.
References I.
Referenced by CreateAdd(), CreateMul(), handleMIFlagDecoration(), and instCombineSVEVectorFuseMulAddSub().
handleMIFlagDecoration()
static void handleMIFlagDecoration (MachineInstr & I, const SPIRVSubtarget & ST, const SPIRVInstrInfo & TII, SPIRV::RequirementHandler & Reqs) static
Definition at line 1284 of file SPIRVModuleAnalysis.cpp.
References llvm::buildOpDecorate(), getFastMathFlags(), I, and TII.
Referenced by addDecorations().
INITIALIZE_PASS()
INITIALIZE_PASS (SPIRVModuleAnalysis , DEBUG_TYPE , "SPIRV module analysis" , true , true)
instrToSignature()
static InstrSignature instrToSignature (MachineInstr & MI, SPIRV::ModuleAnalysisInfo & MAI) static
Definition at line 379 of file SPIRVModuleAnalysis.cpp.
References llvm::MachineOperand::getReg(), llvm::SPIRV::ModuleAnalysisInfo::getRegisterAlias(), llvm::MachineOperand::getSubReg(), llvm::MachineOperand::getType(), llvm::hash_combine(), llvm::hash_value(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), and MI.
Referenced by collectOtherInstr().
Variable Documentation
AvoidCapabilities
cl::list< SPIRV::Capability::Capability > AvoidCapabilities("avoid-spirv-capabilities", cl::desc("SPIR-V capabilities to avoid if there are " "other options enabling a feature"), cl::ZeroOrMore, cl::Hidden, cl::values(clEnumValN(SPIRV::Capability::Shader, "Shader", "SPIR-V Shader capability"))) ("avoid-spirv-capabilities" , cl::desc("SPIR-V capabilities to avoid if there are " "other options enabling a feature") , cl::ZeroOrMore , cl::Hidden , cl::values(clEnumValN(SPIRV::Capability::Shader, "Shader", "SPIR-V Shader capability"))) static
Referenced by AvoidCapabilitiesSet::AvoidCapabilitiesSet().
DefaultVal
unsigned unsigned DefaultVal
Definition at line 65 of file SPIRVModuleAnalysis.cpp.
OpIndex
unsigned OpIndex
Definition at line 64 of file SPIRVModuleAnalysis.cpp.
Referenced by combineX86ShuffleChain(), llvm::DWARFDebugLine::Row::dump(), llvm::MipsELFStreamer::emitInstruction(), lowerV4X128Shuffle(), llvm::AArch64FrameLowering::orderFrameObjects(), and llvm::DWARFDebugLine::Row::reset().
SPVDumpDeps
cl::opt< bool > SPVDumpDeps("spv-dump-deps", cl::desc("Dump MIR with SPIR-V dependencies info"), cl::Optional, cl::init(false)) ("spv-dump-deps" , cl::desc("Dump MIR with SPIR-V dependencies info") , cl::Optional , cl::init(false)) static