LLVM: lib/Target/SPIRV/SPIRVMetadata.cpp File Reference
SPIRVMetadata.cpp File Reference
#include "SPIRVMetadata.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
static MDString * getOCLKernelArgAttribute (const Function &F, unsigned ArgIdx, const StringRef AttributeName)
MDString * llvm::getOCLKernelArgAccessQual (const Function &F, unsigned ArgIdx)
MDString * llvm::getOCLKernelArgTypeQual (const Function &F, unsigned ArgIdx)
Function Documentation
getOCLKernelArgAttribute()
static MDString * getOCLKernelArgAttribute (const Function & F, unsigned ArgIdx, const StringRef AttributeName) static
Definition at line 18 of file SPIRVMetadata.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), F, llvm::Module::getNamedMetadata(), llvm::NamedMDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::NamedMDNode::getOperand(), llvm::NamedMDNode::getParent(), llvm::ValueAsMetadata::getValue(), and llvm::MDNode::operands().
Referenced by llvm::getOCLKernelArgAccessQual(), and llvm::getOCLKernelArgTypeQual().