LLVM: lib/Target/SPIRV/SPIRVPrepareFunctions.cpp File Reference
SPIRVPrepareFunctions.cpp File Reference
#include "SPIRV.h"
#include "SPIRVSubtarget.h"
#include "SPIRVTargetMachine.h"
#include "SPIRVUtils.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/IntrinsicLowering.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsSPIRV.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/LowerMemIntrinsics.h"
#include <charconv>
#include <regex>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Functions
void llvm::initializeSPIRVPrepareFunctionsPass (PassRegistry &)
INITIALIZE_PASS (SPIRVPrepareFunctions, "prepare-functions", "SPIRV prepare functions", false, false) std
static Function * getOrCreateFunction (Module *M, Type *RetTy, ArrayRef< Type * > ArgTypes, StringRef Name)
static bool lowerIntrinsicToFunction (IntrinsicInst *Intrinsic)
static std::string getAnnotation (Value *AnnoVal, Value *OptAnnoVal)
static SmallVector< Metadata * > parseAnnotation (Value *I, const std::string &Anno, LLVMContext &Ctx, Type *Int32Ty)
static void lowerPtrAnnotation (IntrinsicInst *II)
static void lowerFunnelShifts (IntrinsicInst *FSHIntrinsic)
static void buildUMulWithOverflowFunc (Function *UMulFunc)
static void lowerExpectAssume (IntrinsicInst *II)
static bool toSpvOverloadedIntrinsic (IntrinsicInst *II, Intrinsic::ID NewID, ArrayRef< unsigned > OpNos)
static void lowerUMulWithOverflow (IntrinsicInst *UMulIntrinsic)
Function Documentation
buildUMulWithOverflowFunc()
static void buildUMulWithOverflowFunc (Function * UMulFunc) static
Definition at line 345 of file SPIRVPrepareFunctions.cpp.
References llvm::BasicBlock::Create(), llvm::IRBuilderBase::CreateICmpNE(), llvm::IRBuilderBase::CreateInsertValue(), llvm::IRBuilderBase::CreateNUWMul(), llvm::IRBuilderBase::CreateRet(), llvm::IRBuilderBase::CreateUDiv(), llvm::Function::empty(), llvm::PoisonValue::get(), llvm::Function::getArg(), llvm::Module::getContext(), llvm::GlobalValue::getParent(), llvm::Function::getReturnType(), and llvm::Mul.
Referenced by lowerUMulWithOverflow().
getAnnotation()
static std::string getAnnotation (Value * AnnoVal, Value * OptAnnoVal) static
Definition at line 158 of file SPIRVPrepareFunctions.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::getConstantStringInfo(), I, llvm::Ref, and Struct.
Referenced by lowerPtrAnnotation().
getOrCreateFunction()
static Function * getOrCreateFunction (Module * M, Type * RetTy, ArrayRef< Type * > ArgTypes, StringRef Name) static
Definition at line 80 of file SPIRVPrepareFunctions.cpp.
References llvm::Function::Create(), llvm::GlobalValue::ExternalLinkage, F, llvm::Function::getFunction(), Name, llvm::Function::setCallingConv(), and llvm::GlobalValue::setDSOLocal().
Referenced by lowerFunnelShifts(), and lowerUMulWithOverflow().
INITIALIZE_PASS()
INITIALIZE_PASS (SPIRVPrepareFunctions , "prepare-functions" , "SPIRV prepare functions" , false , false)
Definition at line 68 of file SPIRVPrepareFunctions.cpp.
References assert(), llvm::sandboxir::Value::getName(), II, and llvm::StringRef::str().
lowerExpectAssume()
static void lowerExpectAssume (IntrinsicInst * II) static
Definition at line 369 of file SPIRVPrepareFunctions.cpp.
References F, llvm::Intrinsic::getDeclaration(), II, and llvm_unreachable.
lowerFunnelShifts()
static void lowerFunnelShifts (IntrinsicInst * FSHIntrinsic) static
Definition at line 284 of file SPIRVPrepareFunctions.cpp.
References llvm::BitWidth, llvm::BasicBlock::Create(), llvm::IRBuilderBase::CreateLShr(), llvm::IRBuilderBase::CreateOr(), llvm::IRBuilderBase::CreateRet(), llvm::IRBuilderBase::CreateShl(), llvm::IRBuilderBase::CreateSub(), llvm::IRBuilderBase::CreateURem(), llvm::IRBuilderBase::CreateVectorSplat(), llvm::dyn_cast(), llvm::Function::empty(), llvm::Function::getArg(), llvm::VectorType::getElementType(), llvm::CallBase::getFunctionType(), llvm::IRBuilderBase::getInt(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Instruction::getModule(), llvm::FixedVectorType::getNumElements(), getOrCreateFunction(), llvm::Function::getReturnType(), and llvm::CallBase::setCalledFunction().
lowerIntrinsicToFunction()
static bool lowerIntrinsicToFunction (IntrinsicInst * Intrinsic) static
Definition at line 94 of file SPIRVPrepareFunctions.cpp.
References assert(), llvm::cast(), llvm::BasicBlock::Create(), llvm::IRBuilderBase::CreateIntrinsic(), llvm::IRBuilderBase::CreateMemSet(), llvm::IRBuilderBase::CreateRet(), llvm::IRBuilderBase::CreateRetVoid(), llvm::dyn_cast(), llvm::expandMemSetAsLoop(), F, llvm::Function::getFunction(), llvm::isa(), llvm::IntrinsicLowering::LowerIntrinsicCall(), and llvm::Value::setName().
lowerPtrAnnotation()
static void lowerPtrAnnotation (IntrinsicInst * II) static
Definition at line 248 of file SPIRVPrepareFunctions.cpp.
References llvm::IRBuilderBase::CreateIntrinsic(), llvm::dyn_cast(), llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MDString::get(), llvm::MetadataAsValue::get(), getAnnotation(), llvm::Value::getType(), II, llvm::Int32Ty, parseAnnotation(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::IRBuilderBase::SetInsertPoint(), and llvm::SmallVectorBase< Size_T >::size().
lowerUMulWithOverflow()
static void lowerUMulWithOverflow (IntrinsicInst * UMulIntrinsic) static
Definition at line 410 of file SPIRVPrepareFunctions.cpp.
References buildUMulWithOverflowFunc(), llvm::CallBase::getFunctionType(), llvm::Instruction::getModule(), getOrCreateFunction(), and llvm::CallBase::setCalledFunction().
parseAnnotation()
static SmallVector< Metadata * > parseAnnotation (Value * I, const std::string & Anno, LLVMContext & Ctx, Type * Int32Ty) static
Definition at line 193 of file SPIRVPrepareFunctions.cpp.
References llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MDString::get(), llvm::Int32Ty, llvm::Match, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by lowerPtrAnnotation().
toSpvOverloadedIntrinsic()
static bool toSpvOverloadedIntrinsic (IntrinsicInst * II, Intrinsic::ID NewID, ArrayRef< unsigned > OpNos) static
Definition at line 395 of file SPIRVPrepareFunctions.cpp.
References llvm::ArrayRef< T >::empty(), F, llvm::Intrinsic::getDeclaration(), II, and llvm::SmallVectorTemplateBase< T, bool >::push_back().