LLVM: lib/Target/SPIRV/SPIRVPreLegalizer.cpp File Reference
SPIRVPreLegalizer.cpp File Reference
#include "SPIRV.h"
#include "SPIRVSubtarget.h"
#include "SPIRVUtils.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/IntrinsicsSPIRV.h"
#include "llvm/Target/TargetIntrinsicInfo.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "spirv-prelegalizer"
Functions
static void addConstantsToTrack (MachineFunction &MF, SPIRVGlobalRegistry *GR, const SPIRVSubtarget &STI, DenseMap< MachineInstr *, Type * > &TargetExtConstTypes, SmallSet< Register, 4 > &TrackedConstRegs)
static void foldConstantsIntoIntrinsics (MachineFunction &MF, const SmallSet< Register, 4 > &TrackedConstRegs)
static MachineInstr * findAssignTypeInstr (Register Reg, MachineRegisterInfo *MRI)
static void insertBitcasts (MachineFunction &MF, SPIRVGlobalRegistry *GR, MachineIRBuilder MIB)
static SPIRVType * propagateSPIRVType (MachineInstr *MI, SPIRVGlobalRegistry *GR, MachineRegisterInfo &MRI, MachineIRBuilder &MIB)
static void widenScalarLLTNextPow2 (Register Reg, MachineRegisterInfo &MRI)
static std::pair< Register, unsigned > createNewIdReg (SPIRVType *SpvType, Register SrcReg, MachineRegisterInfo &MRI, const SPIRVGlobalRegistry &GR)
Register llvm::insertAssignInstr (Register Reg, Type *Ty, SPIRVType *SpirvTy, SPIRVGlobalRegistry *GR, MachineIRBuilder &MIB, MachineRegisterInfo &MRI)
Helper external function for inserting ASSIGN_TYPE instuction between Reg and its definition, set the new register as a destination of the definition, assign SPIRVType to both registers.
void llvm::processInstr (MachineInstr &MI, MachineIRBuilder &MIB, MachineRegisterInfo &MRI, SPIRVGlobalRegistry *GR)
static void generateAssignInstrs (MachineFunction &MF, SPIRVGlobalRegistry *GR, MachineIRBuilder MIB, DenseMap< MachineInstr *, Type * > &TargetExtConstTypes)
bool isTypeFoldingSupported (unsigned Opcode)
static void processInstrsWithTypeFolding (MachineFunction &MF, SPIRVGlobalRegistry *GR, MachineIRBuilder MIB)
static void insertInlineAsmProcess (MachineFunction &MF, SPIRVGlobalRegistry *GR, const SPIRVSubtarget &ST, MachineIRBuilder MIRBuilder, const SmallVector< MachineInstr * > &ToProcess)
static void insertInlineAsm (MachineFunction &MF, SPIRVGlobalRegistry *GR, const SPIRVSubtarget &ST, MachineIRBuilder MIRBuilder)
static void insertSpirvDecorations (MachineFunction &MF, MachineIRBuilder MIB)
static void processSwitches (MachineFunction &MF, SPIRVGlobalRegistry *GR, MachineIRBuilder MIB)
static bool isImplicitFallthrough (MachineBasicBlock &MBB)
static void removeImplicitFallthroughs (MachineFunction &MF, MachineIRBuilder MIB)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-prelegalizer"
Definition at line 26 of file SPIRVPreLegalizer.cpp.
Function Documentation
addConstantsToTrack()
static void addConstantsToTrack (MachineFunction & MF, SPIRVGlobalRegistry * GR, const SPIRVSubtarget & STI, DenseMap< MachineInstr *, Type * > & TargetExtConstTypes, SmallSet< Register, 4 > & TrackedConstRegs) static
Definition at line 42 of file SPIRVPreLegalizer.cpp.
References llvm::SPIRVGlobalRegistry::add(), llvm::MachineInstr::addOperand(), assert(), llvm::cast(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::contains(), llvm::MachineOperand::CreateReg(), llvm::dyn_cast(), llvm::SPIRVGlobalRegistry::find(), llvm::SPIRVSubtarget::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::MachineFunction::getRegInfo(), llvm::SPIRVGlobalRegistry::getSPIRVTypeID(), llvm::SmallSet< T, N, C >::insert(), llvm::isSpvIntrinsic(), llvm::Register::isValid(), MBB, MI, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), Reg, and llvm::MachineInstr::setDesc().
createNewIdReg()
static std::pair< Register, unsigned > createNewIdReg (SPIRVType * SpvType, Register SrcReg, MachineRegisterInfo & MRI, const SPIRVGlobalRegistry & GR) static
Definition at line 312 of file SPIRVPreLegalizer.cpp.
References assert(), llvm::LLT::fixed_vector(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::SPIRVGlobalRegistry::getPointerSize(), llvm::MachineOperand::getReg(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), llvm::LLT::isPointer(), llvm::LLT::isVector(), MRI, llvm::LLT::pointer(), and llvm::LLT::scalar().
Referenced by llvm::processInstr().
findAssignTypeInstr()
static MachineInstr * findAssignTypeInstr (Register Reg, MachineRegisterInfo * MRI) static
Definition at line 154 of file SPIRVPreLegalizer.cpp.
References llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), I, llvm::isSpvIntrinsic(), MRI, and UseMI.
Referenced by insertBitcasts().
foldConstantsIntoIntrinsics()
static void foldConstantsIntoIntrinsics (MachineFunction & MF, const SmallSet< Register, 4 > & TrackedConstRegs) static
Definition at line 127 of file SPIRVPreLegalizer.cpp.
References assert(), llvm::SmallSet< T, N, C >::contains(), llvm::MachineOperand::CreateImm(), llvm::MachineOperand::getCImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::ConstantInt::getZExtValue(), llvm::isSpvIntrinsic(), MBB, MI, MRI, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
generateAssignInstrs()
static void generateAssignInstrs (MachineFunction & MF, SPIRVGlobalRegistry * GR, MachineIRBuilder MIB, DenseMap< MachineInstr *, Type * > & TargetExtConstTypes) static
Definition at line 426 of file SPIRVPreLegalizer.cpp.
References llvm::SPIRVGlobalRegistry::add(), llvm::addressSpaceToStorageClass(), assert(), llvm::MachineBasicBlock::begin(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::contains(), llvm::MachineBasicBlock::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::MachineBasicBlock::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::SPIRVGlobalRegistry::find(), llvm::MachineOperand::getCImm(), llvm::MachineOperand::getFPImm(), llvm::SPIRVSubtarget::getInstrInfo(), llvm::getMDOperandAsType(), llvm::MachineIRBuilder::getMF(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::Value::getType(), llvm::insertAssignInstr(), llvm::isSpvIntrinsic(), llvm::Register::isValid(), llvm_unreachable, MBB, MI, MRI, llvm::post_order(), propagateSPIRVType(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineIRBuilder::setInsertPt(), UseMI, and widenScalarLLTNextPow2().
insertBitcasts()
static void insertBitcasts (MachineFunction & MF, SPIRVGlobalRegistry * GR, MachineIRBuilder MIB) static
Definition at line 168 of file SPIRVPreLegalizer.cpp.
References llvm::addressSpaceToStorageClass(), assert(), llvm::SPIRVGlobalRegistry::assignSPIRVTypeToVReg(), llvm::MachineIRBuilder::buildBitcast(), findAssignTypeInstr(), llvm::SPIRVSubtarget::getInstrInfo(), llvm::getMDOperandAsType(), llvm::MachineIRBuilder::getMF(), llvm::MachineIRBuilder::getMRI(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVPointerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), llvm::MachineFunction::getSubtarget(), llvm::isSpvIntrinsic(), MBB, MI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineRegisterInfo::replaceRegWith(), and llvm::MachineIRBuilder::setInsertPt().
insertInlineAsm()
static void insertInlineAsm (MachineFunction & MF, SPIRVGlobalRegistry * GR, const SPIRVSubtarget & ST, MachineIRBuilder MIRBuilder) static
Definition at line 713 of file SPIRVPreLegalizer.cpp.
References insertInlineAsmProcess(), llvm::isSpvIntrinsic(), MBB, MI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::report_fatal_error(), and llvm::SmallVectorBase< Size_T >::size().
insertInlineAsmProcess()
static void insertInlineAsmProcess (MachineFunction & MF, SPIRVGlobalRegistry * GR, const SPIRVSubtarget & ST, MachineIRBuilder MIRBuilder, const SmallVector< MachineInstr * > & ToProcess) static
Definition at line 614 of file SPIRVPreLegalizer.cpp.
References llvm::SPIRVGlobalRegistry::add(), llvm::MachineInstrBuilder::addDef(), llvm::MachineInstrBuilder::addImm(), llvm::addStringImm(), llvm::MachineInstrBuilder::addUse(), assert(), llvm::SPIRVGlobalRegistry::assignSPIRVTypeToVReg(), llvm::MachineIRBuilder::buildInstr(), llvm::cast(), llvm::InlineAsm::Extra_HasSideEffects, F, llvm::Function::getContext(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::getMDOperandAsType(), llvm::SPIRVGlobalRegistry::getOrCreateOpTypeFunctionWithArgs(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::SPIRVGlobalRegistry::getSPIRVTypeID(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isMetadata(), llvm::MachineOperand::isReg(), llvm::isSpvIntrinsic(), llvm::Register::isValid(), MI, llvm::InlineAsm::MIOp_AsmString, llvm::InlineAsm::MIOp_ExtraInfo, llvm::InlineAsm::MIOp_FirstOperand, MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::LLT::scalar(), llvm::MachineIRBuilder::setInsertPt(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by insertInlineAsm().
insertSpirvDecorations()
static void insertSpirvDecorations (MachineFunction & MF, MachineIRBuilder MIB) static
Definition at line 735 of file SPIRVPreLegalizer.cpp.
References llvm::buildOpSpirvDecorations(), llvm::isSpvIntrinsic(), MBB, MI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::MachineIRBuilder::setInsertPt().
isImplicitFallthrough()
static bool isImplicitFallthrough (MachineBasicBlock & MBB) static
Definition at line 839 of file SPIRVPreLegalizer.cpp.
References llvm::MachineBasicBlock::canFallThrough(), llvm::MachineBasicBlock::empty(), llvm::isSpvIntrinsic(), MBB, llvm::MachineBasicBlock::rbegin(), and llvm::MachineBasicBlock::rend().
Referenced by removeImplicitFallthroughs().
isTypeFoldingSupported()
bool isTypeFoldingSupported (unsigned Opcode) extern
Definition at line 53 of file SPIRVLegalizerInfo.cpp.
Referenced by processInstrsWithTypeFolding().
processInstrsWithTypeFolding()
static void processInstrsWithTypeFolding (MachineFunction & MF, SPIRVGlobalRegistry * GR, MachineIRBuilder MIB) static
Definition at line 573 of file SPIRVPreLegalizer.cpp.
References llvm::SPIRVGlobalRegistry::getPointerSize(), llvm::MachineFunction::getRegInfo(), isTypeFoldingSupported(), MBB, MI, MRI, llvm::LLT::pointer(), llvm::processInstr(), llvm::LLT::scalar(), and UseMI.
processSwitches()
static void processSwitches (MachineFunction & MF, SPIRVGlobalRegistry * GR, MachineIRBuilder MIB) static
Definition at line 753 of file SPIRVPreLegalizer.cpp.
References assert(), llvm::MachineOperand::CreateCImm(), llvm::MachineOperand::CreateMBB(), llvm::Constant::destroyConstant(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineOperand::getBlockAddress(), llvm::Function::getContext(), llvm::getDefInstrMaybeConstant(), llvm::MachineFunction::getFunction(), llvm::ConstantExpr::getIntToPtr(), getOpcode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineFunction::getRegInfo(), llvm::Value::getType(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::MachineOperand::isBlockAddress(), llvm::isSpvIntrinsic(), MBB, MI, MRI, llvm::Next, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::Value::replaceAllUsesWith(), and llvm::report_fatal_error().
propagateSPIRVType()
static SPIRVType * propagateSPIRVType (MachineInstr * MI, SPIRVGlobalRegistry * GR, MachineRegisterInfo & MRI, MachineIRBuilder & MIB) static
Definition at line 225 of file SPIRVPreLegalizer.cpp.
References assert(), llvm::SPIRVGlobalRegistry::assignSPIRVTypeToVReg(), llvm::TypedPointerType::get(), llvm::SPIRVGlobalRegistry::getDeducedGlobalValueType(), llvm::MachineIRBuilder::getMF(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVIntegerType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVType(), llvm::SPIRVGlobalRegistry::getOrCreateSPIRVVectorType(), llvm::SPIRVGlobalRegistry::getScalarOrVectorBitWidth(), llvm::SPIRVGlobalRegistry::getScalarOrVectorComponentCount(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), llvm::Global, MI, MRI, propagateSPIRVType(), llvm::MachineIRBuilder::setInsertPt(), and llvm::toTypedPointer().
Referenced by generateAssignInstrs(), and propagateSPIRVType().
removeImplicitFallthroughs()
static void removeImplicitFallthroughs (MachineFunction & MF, MachineIRBuilder MIB) static
Definition at line 858 of file SPIRVPreLegalizer.cpp.
References assert(), llvm::MachineIRBuilder::buildBr(), llvm::MachineBasicBlock::end(), isImplicitFallthrough(), MBB, llvm::MachineIRBuilder::setInsertPt(), and llvm::MachineBasicBlock::successors().
widenScalarLLTNextPow2()
static void widenScalarLLTNextPow2 (Register Reg, MachineRegisterInfo & MRI) static
Definition at line 299 of file SPIRVPreLegalizer.cpp.
References llvm::LLT::getScalarSizeInBits(), llvm::LLT::isScalar(), llvm::Log2_32_Ceil(), MRI, and llvm::LLT::scalar().
Referenced by generateAssignInstrs().