LLVM: lib/Target/SPIRV/SPIRVInstructionSelector.cpp File Reference
SPIRVInstructionSelector.cpp File Reference
#include "MCTargetDesc/SPIRVBaseInfo.h"
#include "MCTargetDesc/SPIRVMCTargetDesc.h"
#include "SPIRV.h"
#include "SPIRVGlobalRegistry.h"
#include "SPIRVInstrInfo.h"
#include "SPIRVRegisterBankInfo.h"
#include "SPIRVRegisterInfo.h"
#include "SPIRVTargetMachine.h"
#include "SPIRVUtils.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/CodeGen/GlobalISel/GIMatchTableExecutorImpl.h"
#include "llvm/CodeGen/GlobalISel/GenericMachineInstrs.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelector.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetOpcodes.h"
#include "llvm/IR/IntrinsicsSPIRV.h"
#include "llvm/Support/Debug.h"
#include "SPIRVGenGlobalISel.inc"
Classes
class llvm::SPIRVMachineModuleInfo
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "spirv-isel"
#define GET_GLOBALISEL_PREDICATE_BITSET
#define GET_GLOBALISEL_PREDICATES_DECL
#define GET_GLOBALISEL_TEMPORARIES_DECL
#define GET_GLOBALISEL_IMPL
#define GET_GLOBALISEL_PREDICATES_INIT
#define GET_GLOBALISEL_TEMPORARIES_INIT
Typedefs
using ExtInstList
Functions
static bool isImm (const MachineOperand &MO, MachineRegisterInfo *MRI)
bool isTypeFoldingSupported (unsigned Opcode)
static SPIRV::Scope::Scope getScope (SyncScope::ID Ord, SPIRVMachineModuleInfo *MMI)
static void addMemoryOperands (MachineMemOperand *MemOp, MachineInstrBuilder &MIB)
static void addMemoryOperands (uint64_t Flags, MachineInstrBuilder &MIB)
static bool isGenericCastablePtr (SPIRV::StorageClass::StorageClass SC)
static bool isUSMStorageClass (SPIRV::StorageClass::StorageClass SC)
static unsigned getFCmpOpcode (unsigned PredNum)
static unsigned getICmpOpcode (unsigned PredNum)
static unsigned getPtrCmpOpcode (unsigned Pred)
static unsigned getBoolCmpOpcode (unsigned PredNum)
static unsigned getArrayComponentCount (MachineRegisterInfo *MRI, const SPIRVType *ResType)
static bool isConstReg (MachineRegisterInfo *MRI, SPIRVType *OpDef, SmallPtrSet< SPIRVType *, 4 > &Visited)
static bool isConstReg (MachineRegisterInfo *MRI, Register OpReg)
static APFloat getZeroFP (const Type *LLVMFloatTy)
static int64_t foldImm (const MachineOperand &MO, MachineRegisterInfo *MRI)
InstructionSelector * llvm::createSPIRVInstructionSelector (const SPIRVTargetMachine &TM, const SPIRVSubtarget &Subtarget, const RegisterBankInfo &RBI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-isel"
Definition at line 57 of file SPIRVInstructionSelector.cpp.
GET_GLOBALISEL_IMPL
#define GET_GLOBALISEL_IMPL
Definition at line 258 of file SPIRVInstructionSelector.cpp.
GET_GLOBALISEL_PREDICATE_BITSET
#define GET_GLOBALISEL_PREDICATE_BITSET
Definition at line 68 of file SPIRVInstructionSelector.cpp.
GET_GLOBALISEL_PREDICATES_DECL
#define GET_GLOBALISEL_PREDICATES_DECL
Definition at line 96 of file SPIRVInstructionSelector.cpp.
GET_GLOBALISEL_PREDICATES_INIT
#define GET_GLOBALISEL_PREDICATES_INIT
GET_GLOBALISEL_TEMPORARIES_DECL
#define GET_GLOBALISEL_TEMPORARIES_DECL
Definition at line 100 of file SPIRVInstructionSelector.cpp.
GET_GLOBALISEL_TEMPORARIES_INIT
#define GET_GLOBALISEL_TEMPORARIES_INIT
Typedef Documentation
ExtInstList
using ExtInstList
Initial value:
    std::vector<std::pair<SPIRV::InstructionSet::InstructionSet, uint32_t>>
Definition at line 63 of file SPIRVInstructionSelector.cpp.
Function Documentation
addMemoryOperands() [1/2]
static void addMemoryOperands (MachineMemOperand * MemOp, MachineInstrBuilder & MIB) static
Definition at line 743 of file SPIRVInstructionSelector.cpp.
References llvm::MachineInstrBuilder::addImm().
addMemoryOperands() [2/2]
static void addMemoryOperands (uint64_t Flags, MachineInstrBuilder & MIB) static
Definition at line 760 of file SPIRVInstructionSelector.cpp.
References llvm::MachineInstrBuilder::addImm().
foldImm()
static int64_t foldImm (const MachineOperand & MO, MachineRegisterInfo * MRI) static
Definition at line 1813 of file SPIRVInstructionSelector.cpp.
References assert(), llvm::MachineOperand::getCImm(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::ConstantInt::getZExtValue(), and MRI.
getArrayComponentCount()
static unsigned getArrayComponentCount (MachineRegisterInfo * MRI, const SPIRVType * ResType) static
Definition at line 1430 of file SPIRVInstructionSelector.cpp.
References llvm::MachineOperand::getCImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::ConstantInt::getValue(), llvm::APInt::getZExtValue(), llvm::MachineOperand::isReg(), MRI, and N.
getBoolCmpOpcode()
static unsigned getBoolCmpOpcode (unsigned PredNum) static
Definition at line 1228 of file SPIRVInstructionSelector.cpp.
References llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, and llvm_unreachable.
getFCmpOpcode()
static unsigned getFCmpOpcode (unsigned PredNum) static
Definition at line 1152 of file SPIRVInstructionSelector.cpp.
References llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, and llvm_unreachable.
getICmpOpcode()
static unsigned getICmpOpcode (unsigned PredNum) static
Definition at line 1188 of file SPIRVInstructionSelector.cpp.
References llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, and llvm_unreachable.
getPtrCmpOpcode()
static unsigned getPtrCmpOpcode (unsigned Pred) static
Definition at line 1216 of file SPIRVInstructionSelector.cpp.
References llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, and llvm_unreachable.
getScope()
static SPIRV::Scope::Scope getScope (SyncScope::ID Ord, SPIRVMachineModuleInfo * MMI) static
Definition at line 720 of file SPIRVInstructionSelector.cpp.
References llvm::SPIRVMachineModuleInfo::AllSVMDevicesSSID, llvm::SPIRVMachineModuleInfo::DeviceSSID, llvm::SyncScope::SingleThread, llvm::SPIRVMachineModuleInfo::SubGroupSSID, llvm::SyncScope::System, llvm::SPIRVMachineModuleInfo::Work_ItemSSID, and llvm::SPIRVMachineModuleInfo::WorkGroupSSID.
Referenced by llvm::DILocation::cloneWithDiscriminator(), LLVMDILocationGetScope(), and LLVMDIVariableGetScope().
getZeroFP()
static APFloat getZeroFP (const Type * LLVMFloatTy) static
Definition at line 1623 of file SPIRVInstructionSelector.cpp.
References llvm::Type::getScalarType(), llvm::Type::getTypeID(), and llvm::APFloat::getZero().
isConstReg() [1/2]
static bool isConstReg (MachineRegisterInfo * MRI, Register OpReg) static
Definition at line 1488 of file SPIRVInstructionSelector.cpp.
References isConstReg(), and MRI.
isConstReg() [2/2]
static bool isConstReg (MachineRegisterInfo * MRI, SPIRVType * OpDef, SmallPtrSet< SPIRVType *, 4 > & Visited) static
Definition at line 1448 of file SPIRVInstructionSelector.cpp.
References llvm::cast(), llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::MachineInstr::getNumExplicitDefs(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::SmallPtrSetImpl< PtrType >::insert(), isConstReg(), llvm::MachineOperand::isReg(), and MRI.
Referenced by isConstReg(), and isConstReg().
isGenericCastablePtr()
static bool isGenericCastablePtr (SPIRV::StorageClass::StorageClass SC) static
Definition at line 1047 of file SPIRVInstructionSelector.cpp.
isImm()
static bool isImm (const MachineOperand & MO, MachineRegisterInfo * MRI) static
Definition at line 1802 of file SPIRVInstructionSelector.cpp.
References assert(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), and MRI.
Referenced by llvm::HexagonInstrInfo::insertBranch(), llvm::RISCVInstrInfo::insertBranch(), llvm::SIInstrInfo::insertBranch(), llvm::VEInstrInfo::insertBranch(), llvm::SIInstrInfo::insertVectorSelect(), llvm::LoongArchInstrInfo::isAsCheapAsAMove(), llvm::RISCVInstrInfo::isAsCheapAsAMove(), llvm::isLeaMem(), IsMemoryAssignmentError(), isMergeableLdStUpdate(), llvm::MachineInstr::isOperandSubregIdx(), llvm::HexagonInstrInfo::reverseBranchCondition(), and llvm::SIInstrInfo::reverseBranchCondition().
isTypeFoldingSupported()
bool isTypeFoldingSupported (unsigned Opcode) extern
Definition at line 53 of file SPIRVLegalizerInfo.cpp.
References TypeFoldingSupportingOpcs.
Referenced by llvm::SPIRVLegalizerInfo::legalizeCustom().
isUSMStorageClass()
static bool isUSMStorageClass (SPIRV::StorageClass::StorageClass SC) static
Definition at line 1058 of file SPIRVInstructionSelector.cpp.