LLVM: lib/Target/SPIRV/SPIRVPostLegalizer.cpp File Reference
SPIRVPostLegalizer.cpp File Reference
#include "SPIRV.h"
#include "SPIRVSubtarget.h"
#include "SPIRVUtils.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/Analysis/OptimizationRemarkEmitter.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/IntrinsicsSPIRV.h"
#include "llvm/Target/TargetIntrinsicInfo.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "spirv-postlegalizer"
Functions
bool isTypeFoldingSupported (unsigned Opcode)
Register llvm::insertAssignInstr (Register Reg, Type *Ty, SPIRVType *SpirvTy, SPIRVGlobalRegistry *GR, MachineIRBuilder &MIB, MachineRegisterInfo &MRI)
Helper external function for inserting ASSIGN_TYPE instuction between Reg and its definition, set the new register as a destination of the definition, assign SPIRVType to both registers.
void llvm::processInstr (MachineInstr &MI, MachineIRBuilder &MIB, MachineRegisterInfo &MRI, SPIRVGlobalRegistry *GR)
static bool isMetaInstrGET (unsigned Opcode)
static bool mayBeInserted (unsigned Opcode)
static void processNewInstrs (MachineFunction &MF, SPIRVGlobalRegistry *GR, MachineIRBuilder MIB)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "spirv-postlegalizer"
Definition at line 28 of file SPIRVPostLegalizer.cpp.
Function Documentation
isMetaInstrGET()
static bool isMetaInstrGET (unsigned Opcode) static
Definition at line 56 of file SPIRVPostLegalizer.cpp.
Referenced by processNewInstrs().
isTypeFoldingSupported()
bool isTypeFoldingSupported (unsigned Opcode) extern
Definition at line 53 of file SPIRVLegalizerInfo.cpp.
Referenced by mayBeInserted(), and processNewInstrs().
mayBeInserted()
static bool mayBeInserted (unsigned Opcode) static
Definition at line 64 of file SPIRVPostLegalizer.cpp.
References isTypeFoldingSupported().
Referenced by processNewInstrs().
processNewInstrs()
static void processNewInstrs (MachineFunction & MF, SPIRVGlobalRegistry * GR, MachineIRBuilder MIB) static
Definition at line 80 of file SPIRVPostLegalizer.cpp.
References llvm::SPIRVGlobalRegistry::assignSPIRVTypeToVReg(), llvm::SPIRVGlobalRegistry::CurMF, llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::getNextNode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::SPIRVGlobalRegistry::getScalarOrVectorBitWidth(), llvm::SPIRVGlobalRegistry::getSPIRVTypeForVReg(), I, llvm::insertAssignInstr(), isMetaInstrGET(), isTypeFoldingSupported(), llvm::Register::isValid(), mayBeInserted(), MBB, MRI, llvm::processInstr(), Register, llvm::report_fatal_error(), and llvm::LLT::scalar().