LLVM: llvm::OutlinedHashTreeRecord Struct Reference
llvm::OutlinedHashTreeRecord Struct Reference
#include "llvm/CodeGenData/OutlinedHashTreeRecord.h"
Public Member Functions
OutlinedHashTreeRecord ()
OutlinedHashTreeRecord (std::unique_ptr< OutlinedHashTree > HashTree)
void serialize (raw_ostream &OS) const
Serialize the outlined hash tree to a raw_ostream.
void deserialize (const unsigned char *&Ptr)
Deserialize the outlined hash tree from a raw_ostream.
void serializeYAML (yaml::Output &YOS) const
Serialize the outlined hash tree to a YAML stream.
void deserializeYAML (yaml::Input &YIS)
Deserialize the outlined hash tree from a YAML stream.
void merge (const OutlinedHashTreeRecord &Other)
Merge the other outlined hash tree into this one.
bool empty () const
void print (raw_ostream &OS=llvm::errs()) const
Print the outlined hash tree in a YAML format.
Public Attributes
std::unique_ptr< OutlinedHashTree > HashTree
Detailed Description
Definition at line 35 of file OutlinedHashTreeRecord.h.
Constructor & Destructor Documentation
OutlinedHashTreeRecord() [1/2]
llvm::OutlinedHashTreeRecord::OutlinedHashTreeRecord () inline
Definition at line 38 of file OutlinedHashTreeRecord.h.
References HashTree.
OutlinedHashTreeRecord() [2/2]
llvm::OutlinedHashTreeRecord::OutlinedHashTreeRecord (std::unique_ptr< OutlinedHashTree > HashTree) inline
Definition at line 39 of file OutlinedHashTreeRecord.h.
Member Function Documentation
deserialize()
void OutlinedHashTreeRecord::deserialize (const unsigned char *& Ptr)
Deserialize the outlined hash tree from a raw_ostream.
Definition at line 74 of file OutlinedHashTreeRecord.cpp.
References llvm::HashNodeStable::Hash, I, Ptr, llvm::support::endian::readNext(), llvm::HashNodeStable::SuccessorIds, and llvm::HashNodeStable::Terminals.
deserializeYAML()
void OutlinedHashTreeRecord::deserializeYAML (yaml::Input & YIS)
Deserialize the outlined hash tree from a YAML stream.
Definition at line 105 of file OutlinedHashTreeRecord.cpp.
empty()
bool llvm::OutlinedHashTreeRecord::empty () const inline
Returns
true if the outlined hash tree is empty.
Definition at line 57 of file OutlinedHashTreeRecord.h.
References HashTree.
merge()
void llvm::OutlinedHashTreeRecord::merge (const OutlinedHashTreeRecord & Other) inline
Merge the other outlined hash tree into this one.
Definition at line 52 of file OutlinedHashTreeRecord.h.
References HashTree, and llvm::Other.
print()
void llvm::OutlinedHashTreeRecord::print (raw_ostream & OS = llvm::errs()) const inline
Print the outlined hash tree in a YAML format.
Definition at line 60 of file OutlinedHashTreeRecord.h.
References OS, and serializeYAML().
serialize()
void OutlinedHashTreeRecord::serialize (raw_ostream & OS) const
Serialize the outlined hash tree to a raw_ostream.
Definition at line 58 of file OutlinedHashTreeRecord.cpp.
References llvm::little, OS, and llvm::support::endian::Writer::write().
serializeYAML()
void OutlinedHashTreeRecord::serializeYAML (yaml::Output & YOS) const
Serialize the outlined hash tree to a YAML stream.
Definition at line 98 of file OutlinedHashTreeRecord.cpp.
Referenced by print().
Member Data Documentation
HashTree
std::unique_ptr<OutlinedHashTree> llvm::OutlinedHashTreeRecord::HashTree
Definition at line 36 of file OutlinedHashTreeRecord.h.
Referenced by empty(), merge(), and OutlinedHashTreeRecord().
The documentation for this struct was generated from the following files:
include/llvm/CodeGenData/OutlinedHashTreeRecord.h
lib/CodeGenData/OutlinedHashTreeRecord.cpp