LLVM: llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain > Struct Template Reference
llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain > Struct Template Reference
#include "llvm/CodeGen/SDPatternMatch.h"
Public Member Functions
UnaryOpc_match (unsigned Opc, const Opnd_P &Op)
template<typename MatchContext >
bool match (const MatchContext &Ctx, SDValue N)
Public Attributes
unsigned Opcode
Opnd_P Opnd
Detailed Description
template<typename Opnd_P, bool ExcludeChain = false>
struct llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >
Definition at line 650 of file SDPatternMatch.h.
Constructor & Destructor Documentation
UnaryOpc_match()
template<typename Opnd_P , bool ExcludeChain = false> llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::UnaryOpc_match (unsigned Opc, const Opnd_P & Op) inline
Definition at line 654 of file SDPatternMatch.h.
Member Function Documentation
match()
template<typename Opnd_P , bool ExcludeChain = false> template<typename MatchContext > bool llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::match (const MatchContext & Ctx, SDValue N) inline
Definition at line 657 of file SDPatternMatch.h.
References assert(), llvm::SDPatternMatch::EffectiveOperands< ExcludeChain >::FirstIndex, llvm::SDPatternMatch::m_Opc(), N, llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::Opcode, llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::Opnd, llvm::SDPatternMatch::sd_context_match(), and llvm::SDPatternMatch::EffectiveOperands< ExcludeChain >::Size.
Member Data Documentation
Opcode
template<typename Opnd_P , bool ExcludeChain = false> unsigned llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::Opcode
Definition at line 651 of file SDPatternMatch.h.
Referenced by llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::match().
Opnd
template<typename Opnd_P , bool ExcludeChain = false> Opnd_P llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::Opnd
Definition at line 652 of file SDPatternMatch.h.
Referenced by llvm::SDPatternMatch::UnaryOpc_match< Opnd_P, ExcludeChain >::match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/SDPatternMatch.h