LLVM: llvm::SDPatternMatch::SpecificInt_match Struct Reference
llvm::SDPatternMatch::SpecificInt_match Struct Reference
#include "llvm/CodeGen/SDPatternMatch.h"
Public Member Functions
SpecificInt_match (APInt APV)
template<typename MatchContext >
bool match (const MatchContext &Ctx, SDValue N)
Public Attributes
APInt IntVal
Detailed Description
Definition at line 753 of file SDPatternMatch.h.
Constructor & Destructor Documentation
SpecificInt_match()
llvm::SDPatternMatch::SpecificInt_match::SpecificInt_match (APInt APV) inline explicit
Definition at line 756 of file SDPatternMatch.h.
Member Function Documentation
match()
template<typename MatchContext > bool llvm::SDPatternMatch::SpecificInt_match::match (const MatchContext & Ctx, SDValue N) inline
Definition at line 759 of file SDPatternMatch.h.
References IntVal, llvm::APInt::isSameValue(), llvm::SDPatternMatch::m_ConstInt(), N, and llvm::SDPatternMatch::sd_context_match().
Member Data Documentation
IntVal
APInt llvm::SDPatternMatch::SpecificInt_match::IntVal
Definition at line 754 of file SDPatternMatch.h.
Referenced by match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/SDPatternMatch.h