LLVM: llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode > Struct Template Reference
llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode > Struct Template Reference
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
Public Member Functions
TernaryOp_match (const Src0Ty &Src0, const Src1Ty &Src1, const Src2Ty &Src2)
template<typename OpTy >
bool match (const MachineRegisterInfo &MRI, OpTy &&Op)
Public Attributes
Src0Ty Src0
Src1Ty Src1
Src2Ty Src2
Detailed Description
template<typename Src0Ty, typename Src1Ty, typename Src2Ty, unsigned Opcode>
struct llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode >
Definition at line 727 of file MIPatternMatch.h.
Constructor & Destructor Documentation
TernaryOp_match()
template<typename Src0Ty , typename Src1Ty , typename Src2Ty , unsigned Opcode> llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode >::TernaryOp_match (const Src0Ty & Src0, const Src1Ty & Src1, const Src2Ty & Src2) inline
Definition at line 732 of file MIPatternMatch.h.
Member Function Documentation
match()
template<typename Src0Ty , typename Src1Ty , typename Src2Ty , unsigned Opcode> template<typename OpTy > bool llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode >::match (const MachineRegisterInfo & MRI, OpTy && Op) inline
Definition at line 735 of file MIPatternMatch.h.
References llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::mi_match(), MRI, llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode >::Src0, llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode >::Src1, and llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode >::Src2.
Member Data Documentation
Src0
template<typename Src0Ty , typename Src1Ty , typename Src2Ty , unsigned Opcode> Src0Ty llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode >::Src0
Definition at line 728 of file MIPatternMatch.h.
Referenced by llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode >::match().
Src1
template<typename Src0Ty , typename Src1Ty , typename Src2Ty , unsigned Opcode> Src1Ty llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode >::Src1
Definition at line 729 of file MIPatternMatch.h.
Referenced by llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode >::match().
Src2
template<typename Src0Ty , typename Src1Ty , typename Src2Ty , unsigned Opcode> Src2Ty llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode >::Src2
Definition at line 730 of file MIPatternMatch.h.
Referenced by llvm::MIPatternMatch::TernaryOp_match< Src0Ty, Src1Ty, Src2Ty, Opcode >::match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/GlobalISel/MIPatternMatch.h