LLVM: llvm::ForeachLoop Struct Reference
llvm::ForeachLoop Struct Reference
ForeachLoop - Record the iteration state associated with a for loop.
#include "TableGen/TGParser.h"
Public Member Functions
void dump () const
ForeachLoop (SMLoc Loc, VarInit *IVar, Init *LValue)
Public Attributes
SMLoc Loc
VarInit * IterVar
Init * ListValue
std::vector< RecordsEntry > Entries
Detailed Description
ForeachLoop - Record the iteration state associated with a for loop.
This is used to instantiate items in the loop body.
IterVar is allowed to be null, in which case no iteration variable is defined in the loop at all. (This happens when a ForeachLoop is constructed by desugaring an if statement.)
Definition at line 63 of file TGParser.h.
Constructor & Destructor Documentation
ForeachLoop()
llvm::ForeachLoop::ForeachLoop (SMLoc Loc, VarInit * IVar, Init * LValue) inline
Definition at line 71 of file TGParser.h.
Member Function Documentation
dump()
LLVM_DUMP_METHOD void ForeachLoop::dump () const
Definition at line 4422 of file TGParser.cpp.
References Entries, llvm::errs(), llvm::Init::getAsString(), llvm::VarInit::getAsString(), IterVar, and ListValue.
Member Data Documentation
Entries
std::vector<RecordsEntry> llvm::ForeachLoop::Entries
Definition at line 67 of file TGParser.h.
Referenced by dump().
IterVar
VarInit* llvm::ForeachLoop::IterVar
Definition at line 65 of file TGParser.h.
Referenced by dump(), and llvm::TGVarScope::getVar().
ListValue
Init* llvm::ForeachLoop::ListValue
Definition at line 66 of file TGParser.h.
Referenced by dump().
Loc
SMLoc llvm::ForeachLoop::Loc
Definition at line 64 of file TGParser.h.
The documentation for this struct was generated from the following files:
lib/TableGen/TGParser.h
lib/TableGen/TGParser.cpp