LLVM: llvm::DWARFAttribute Struct Reference
llvm::DWARFAttribute Struct Reference
Encapsulates a DWARF attribute value and all of the data required to describe the attribute value.
#include "llvm/DebugInfo/DWARF/DWARFAttribute.h"
Public Member Functions
bool isValid () const
operator bool () const
Static Public Member Functions
static bool mayHaveLocationList (dwarf::Attribute Attr)
Identify DWARF attributes that may contain a pointer to a location list.
static bool mayHaveLocationExpr (dwarf::Attribute Attr)
Identifies DWARF attributes that may contain a reference to a DWARF expression.
Public Attributes
uint64_t Offset = 0
The debug info/types offset for this attribute.
uint32_t ByteSize = 0
The debug info/types section byte size of the data for this attribute.
dwarf::Attribute Attr = dwarf::Attribute(0)
The attribute enumeration of this attribute.
DWARFFormValue Value
The form and value for this attribute.
Detailed Description
Encapsulates a DWARF attribute value and all of the data required to describe the attribute value.
This class is designed to be used by clients that want to iterate across all attributes in a DWARFDie.
Definition at line 24 of file DWARFAttribute.h.
Member Function Documentation
isValid()
bool llvm::DWARFAttribute::isValid () const inline
Definition at line 34 of file DWARFAttribute.h.
References Attr, and Offset.
Referenced by operator bool(), and llvm::DWARFDie::attribute_iterator::operator bool().
mayHaveLocationExpr()
bool DWARFAttribute::mayHaveLocationExpr (dwarf::Attribute Attr) static
Identifies DWARF attributes that may contain a reference to a DWARF expression.
Definition at line 735 of file DWARFDie.cpp.
Referenced by llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneBlockAttr(), and dumpAttribute().
mayHaveLocationList()
bool DWARFAttribute::mayHaveLocationList (dwarf::Attribute Attr) static
Identify DWARF attributes that may contain a pointer to a location list.
Definition at line 718 of file DWARFDie.cpp.
Referenced by llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneScalarAttr(), and dumpAttribute().
operator bool()
llvm::DWARFAttribute::operator bool () const inline explicit
Definition at line 38 of file DWARFAttribute.h.
References isValid().
Member Data Documentation
Attr
dwarf::Attribute llvm::DWARFAttribute::Attr = dwarf::Attribute(0)
The attribute enumeration of this attribute.
Definition at line 30 of file DWARFAttribute.h.
Referenced by dumpAttribute(), and isValid().
ByteSize
uint32_t llvm::DWARFAttribute::ByteSize = 0
The debug info/types section byte size of the data for this attribute.
Definition at line 28 of file DWARFAttribute.h.
Offset
uint64_t llvm::DWARFAttribute::Offset = 0
The debug info/types offset for this attribute.
Definition at line 26 of file DWARFAttribute.h.
Referenced by llvm::DWARFDie::attribute_iterator::attribute_iterator(), and isValid().
Value
DWARFFormValue llvm::DWARFAttribute::Value
The form and value for this attribute.
Definition at line 32 of file DWARFAttribute.h.
Referenced by dumpAttribute().
The documentation for this struct was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFAttribute.h
lib/DebugInfo/DWARF/DWARFDie.cpp