LLVM: llvm::memprof::PortableMemInfoBlock Struct Reference
llvm::memprof::PortableMemInfoBlock Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
PortableMemInfoBlock ()=default
PortableMemInfoBlock (const MemInfoBlock &Block, const MemProfSchema &IncomingSchema)
PortableMemInfoBlock (const MemProfSchema &Schema, const unsigned char *Ptr)
void deserialize (const MemProfSchema &IncomingSchema, const unsigned char *Ptr)
void serialize (const MemProfSchema &Schema, raw_ostream &OS) const
void printYAML (raw_ostream &OS) const
std::bitset< llvm::to_underlying(Meta::Size)> getSchema () const
MIBEntryDef (AllocCount=1, AllocCount, uint32_t) MIBEntryDef(TotalAccessCount
uint64_t MIBEntryDef (MinAccessCount=3, MinAccessCount, uint64_t) MIBEntryDef(MaxAccessCount
uint64_t uint64_t MIBEntryDef (TotalSize=5, TotalSize, uint64_t) MIBEntryDef(MinSize
uint64_t uint64_t uint32_t MIBEntryDef (MaxSize=7, MaxSize, uint32_t) MIBEntryDef(AllocTimestamp
uint64_t uint64_t uint32_t uint32_t MIBEntryDef (DeallocTimestamp=9, DeallocTimestamp, uint32_t) MIBEntryDef(TotalLifetime
uint64_t uint64_t uint32_t uint32_t uint64_t MIBEntryDef (MinLifetime=11, MinLifetime, uint32_t) MIBEntryDef(MaxLifetime
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t MIBEntryDef (AllocCpuId=13, AllocCpuId, uint32_t) MIBEntryDef(DeallocCpuId
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t MIBEntryDef (NumMigratedCpu=15, NumMigratedCpu, uint32_t) MIBEntryDef(NumLifetimeOverlaps
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t MIBEntryDef (NumSameAllocCpu=17, NumSameAllocCpu, uint32_t) MIBEntryDef(NumSameDeallocCpu
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t MIBEntryDef (DataTypeId=19, DataTypeId, uint64_t) MIBEntryDef(TotalAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t MIBEntryDef (MinAccessDensity=21, MinAccessDensity, uint32_t) MIBEntryDef(MaxAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t MIBEntryDef (TotalLifetimeAccessDensity=23, TotalLifetimeAccessDensity, uint64_t) MIBEntryDef(MinLifetimeAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t MIBEntryDef (MaxLifetimeAccessDensity=25, MaxLifetimeAccessDensity, uint32_t) MIBEntryDef(AccessHistogramSize
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t MIBEntryDef (AccessHistogram=27, AccessHistogram, uintptr_t) void clear()
bool operator== (const PortableMemInfoBlock &Other) const
bool operator!= (const PortableMemInfoBlock &Other) const
Static Public Member Functions
static size_t serializedSize (const MemProfSchema &Schema)
Public Attributes
TotalAccessCount
uint64_t MaxAccessCount
uint64_t uint64_t MinSize
uint64_t uint64_t uint32_t AllocTimestamp
uint64_t uint64_t uint32_t uint32_t TotalLifetime
uint64_t uint64_t uint32_t uint32_t uint64_t MaxLifetime
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t DeallocCpuId
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t NumLifetimeOverlaps
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t NumSameDeallocCpu
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t TotalAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t MaxAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t MinLifetimeAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t AccessHistogramSize
Detailed Description
Definition at line 61 of file MemProf.h.
Constructor & Destructor Documentation
PortableMemInfoBlock() [1/3]
llvm::memprof::PortableMemInfoBlock::PortableMemInfoBlock () default
PortableMemInfoBlock() [2/3]
llvm::memprof::PortableMemInfoBlock::PortableMemInfoBlock (const MemInfoBlock & Block, const MemProfSchema & IncomingSchema) inline explicit
Definition at line 63 of file MemProf.h.
References llvm::to_underlying().
PortableMemInfoBlock() [3/3]
llvm::memprof::PortableMemInfoBlock::PortableMemInfoBlock (const MemProfSchema & Schema, const unsigned char * Ptr) inline
Definition at line 72 of file MemProf.h.
References deserialize(), and Ptr.
Member Function Documentation
deserialize()
void llvm::memprof::PortableMemInfoBlock::deserialize (const MemProfSchema & IncomingSchema, const unsigned char * Ptr) inline
Definition at line 78 of file MemProf.h.
References llvm_unreachable, and llvm::to_underlying().
Referenced by PortableMemInfoBlock().
getSchema()
std::bitset< llvm::to_underlying(Meta::Size)> llvm::memprof::PortableMemInfoBlock::getSchema () const inline
Definition at line 137 of file MemProf.h.
MIBEntryDef() [1/14]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (AccessHistogram = 27, AccessHistogram , uintptr_t) inline
Definition at line 56 of file MemProf.h.
MIBEntryDef() [2/14]
llvm::memprof::PortableMemInfoBlock::MIBEntryDef (AllocCount = 1, AllocCount , uint32_t)
MIBEntryDef() [3/14]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (AllocCpuId = 13, AllocCpuId , uint32_t)
MIBEntryDef() [4/14]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (DataTypeId = 19, DataTypeId , uint64_t)
MIBEntryDef() [5/14]
uint64_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (DeallocTimestamp = 9, DeallocTimestamp , uint32_t)
MIBEntryDef() [6/14]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MaxLifetimeAccessDensity = 25, MaxLifetimeAccessDensity , uint32_t)
MIBEntryDef() [7/14]
uint64_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MaxSize = 7, MaxSize , uint32_t)
MIBEntryDef() [8/14]
uint64_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MinAccessCount = 3, MinAccessCount , uint64_t)
MIBEntryDef() [9/14]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MinAccessDensity = 21, MinAccessDensity , uint32_t)
MIBEntryDef() [10/14]
uint64_t uint64_t uint32_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (MinLifetime = 11, MinLifetime , uint32_t)
MIBEntryDef() [11/14]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (NumMigratedCpu = 15, NumMigratedCpu , uint32_t)
MIBEntryDef() [12/14]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (NumSameAllocCpu = 17, NumSameAllocCpu , uint32_t)
MIBEntryDef() [13/14]
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (TotalLifetimeAccessDensity = 23, TotalLifetimeAccessDensity , uint64_t)
MIBEntryDef() [14/14]
uint64_t uint64_t llvm::memprof::PortableMemInfoBlock::MIBEntryDef (TotalSize = 5, TotalSize , uint64_t)
operator!=()
bool llvm::memprof::PortableMemInfoBlock::operator!= (const PortableMemInfoBlock & Other) const inline
Definition at line 165 of file MemProf.h.
References operator==(), and llvm::Other.
operator==()
bool llvm::memprof::PortableMemInfoBlock::operator== (const PortableMemInfoBlock & Other) const inline
Definition at line 61 of file MemProf.h.
Referenced by operator!=().
printYAML()
void llvm::memprof::PortableMemInfoBlock::printYAML (raw_ostream & OS) const inline
Definition at line 121 of file MemProf.h.
References AccessHistogramSize, I, and OS.
serialize()
void llvm::memprof::PortableMemInfoBlock::serialize (const MemProfSchema & Schema, raw_ostream & OS) const inline
Definition at line 102 of file MemProf.h.
References llvm::little, llvm_unreachable, and OS.
serializedSize()
static size_t llvm::memprof::PortableMemInfoBlock::serializedSize (const MemProfSchema & Schema) inline static
Definition at line 169 of file MemProf.h.
References llvm_unreachable.
Referenced by llvm::memprof::deserializeV0(), llvm::memprof::deserializeV2(), llvm::memprof::deserializeV3(), llvm::memprof::serializedSizeV0(), llvm::memprof::serializedSizeV2(), and llvm::memprof::serializedSizeV3().
Member Data Documentation
AccessHistogramSize
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::AccessHistogramSize
Definition at line 55 of file MemProf.h.
Referenced by printYAML().
AllocTimestamp
uint64_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::AllocTimestamp
Definition at line 37 of file MemProf.h.
DeallocCpuId
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::DeallocCpuId
Definition at line 43 of file MemProf.h.
MaxAccessCount
uint64_t llvm::memprof::PortableMemInfoBlock::MaxAccessCount
Definition at line 33 of file MemProf.h.
MaxAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::MaxAccessDensity
Definition at line 51 of file MemProf.h.
MaxLifetime
uint64_t uint64_t uint32_t uint32_t uint64_t llvm::memprof::PortableMemInfoBlock::MaxLifetime
Definition at line 41 of file MemProf.h.
MinLifetimeAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t uint64_t uint32_t llvm::memprof::PortableMemInfoBlock::MinLifetimeAccessDensity
Definition at line 53 of file MemProf.h.
MinSize
uint64_t uint64_t llvm::memprof::PortableMemInfoBlock::MinSize
Definition at line 35 of file MemProf.h.
NumLifetimeOverlaps
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::NumLifetimeOverlaps
Definition at line 45 of file MemProf.h.
NumSameDeallocCpu
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::NumSameDeallocCpu
Definition at line 47 of file MemProf.h.
TotalAccessCount
llvm::memprof::PortableMemInfoBlock::TotalAccessCount
Definition at line 31 of file MemProf.h.
TotalAccessDensity
uint64_t uint64_t uint32_t uint32_t uint64_t uint32_t uint32_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::TotalAccessDensity
Definition at line 49 of file MemProf.h.
TotalLifetime
uint64_t uint64_t uint32_t uint32_t llvm::memprof::PortableMemInfoBlock::TotalLifetime
Definition at line 39 of file MemProf.h.
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProf.h