LLVM: llvm::dwarf::FormParams Struct Reference
llvm::dwarf::FormParams Struct Reference
A helper struct providing information about the byte size of DW_FORM values that vary in size depending on the DWARF version, address byte size, or DWARF32/DWARF64.
#include "llvm/BinaryFormat/Dwarf.h"
Public Member Functions
uint8_t getRefAddrByteSize () const
The definition of the size of form DW_FORM_ref_addr depends on the version.
uint8_t getDwarfOffsetByteSize () const
The size of a reference is determined by the DWARF 32/64-bit format.
operator bool () const
Public Attributes
uint16_t Version
uint8_t AddrSize
DwarfFormat Format
bool DwarfUsesRelocationsAcrossSections = false
True if DWARF v2 output generally uses relocations for references to other .debug_* sections.
Detailed Description
A helper struct providing information about the byte size of DW_FORM values that vary in size depending on the DWARF version, address byte size, or DWARF32/DWARF64.
Definition at line 1077 of file Dwarf.h.
Member Function Documentation
getDwarfOffsetByteSize()
uint8_t llvm::dwarf::FormParams::getDwarfOffsetByteSize () const inline
The size of a reference is determined by the DWARF 32/64-bit format.
Definition at line 1095 of file Dwarf.h.
References llvm::dwarf::getDwarfOffsetByteSize().
Referenced by llvm::dwarf_linker::parallel::CompileUnit::cloneDieAttrExpression(), llvm::dwarf_linker::parallel::DebugLineSectionEmitter::emit(), llvm::DWARFYAML::emitDebugInfo(), llvm::dwarf_linker::parallel::DwarfUnit::emitDebugStringOffsetSection(), llvm::dwarf_linker::parallel::DwarfUnit::emitPubAccelerators(), llvm::DWARFUnitHeader::extract(), llvm::DWARFUnitHeader::getDwarfOffsetByteSize(), llvm::StrOffsetsContributionDescriptor::getDwarfOffsetByteSize(), llvm::dwarf::getFixedFormByteSize(), getRefAddrByteSize(), llvm::DIEDelta::sizeOf(), llvm::DIEExpr::sizeOf(), llvm::DIELabel::sizeOf(), llvm::DIELocList::sizeOf(), and writeDIE().
getRefAddrByteSize()
uint8_t llvm::dwarf::FormParams::getRefAddrByteSize () const inline
The definition of the size of form DW_FORM_ref_addr depends on the version.
In DWARF v2 it's the size of an address; after that, it's the size of a reference.
Definition at line 1088 of file Dwarf.h.
References AddrSize, and getDwarfOffsetByteSize().
Referenced by llvm::dwarf::getFixedFormByteSize(), llvm::DWARFUnitHeader::getRefAddrByteSize(), llvm::DIEEntry::sizeOf(), and writeDIE().
operator bool()
llvm::dwarf::FormParams::operator bool () const inline explicit
Definition at line 1099 of file Dwarf.h.
References AddrSize.
Member Data Documentation
AddrSize
uint8_t llvm::dwarf::FormParams::AddrSize
Definition at line 1079 of file Dwarf.h.
Referenced by llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitLineTable(), llvm::DWARFUnitHeader::extract(), llvm::DWARFUnitHeader::getAddressByteSize(), llvm::DWARFDebugLine::Prologue::getAddressSize(), llvm::dwarf::getFixedFormByteSize(), getRefAddrByteSize(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::link(), operator bool(), llvm::DWARFDebugLine::Prologue::parse(), llvm::DIELabel::sizeOf(), and writeDIE().
DwarfUsesRelocationsAcrossSections
bool llvm::dwarf::FormParams::DwarfUsesRelocationsAcrossSections = false
True if DWARF v2 output generally uses relocations for references to other .debug_* sections.
Definition at line 1083 of file Dwarf.h.
Referenced by llvm::DIEString::sizeOf().
Format
DwarfFormat llvm::dwarf::FormParams::Format
Definition at line 1080 of file Dwarf.h.
Referenced by llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneBlockAttr(), llvm::DWARFDebugLine::Prologue::dump(), llvm::dwarf_linker::classic::DwarfStreamer::emitLineTableForUnit(), llvm::DWARFUnitHeader::extract(), llvm::DWARFUnitHeader::getFormat(), llvm::StrOffsetsContributionDescriptor::getFormat(), llvm::DWARFUnitHeader::getUnitLengthFieldByteSize(), llvm::DWARFDebugLine::Prologue::isDWARF64(), llvm::DWARFDebugLine::Prologue::parse(), and llvm::DIELocList::sizeOf().
Version
uint16_t llvm::dwarf::FormParams::Version
Definition at line 1078 of file Dwarf.h.
Referenced by llvm::DWARFUnitHeader::extract(), llvm::DWARFDebugLine::Prologue::getVersion(), llvm::DWARFUnitHeader::getVersion(), llvm::StrOffsetsContributionDescriptor::getVersion(), and llvm::DWARFDebugLine::Prologue::parse().
The documentation for this struct was generated from the following file:
include/llvm/BinaryFormat/Dwarf.h