LLVM: llvm::BinarySubstreamRef Struct Reference
llvm::BinarySubstreamRef Struct Reference
#include "llvm/Support/BinaryStreamRef.h"
Public Member Functions
BinarySubstreamRef slice (uint64_t Off, uint64_t Size) const
BinarySubstreamRef drop_front (uint64_t N) const
BinarySubstreamRef keep_front (uint64_t N) const
std::pair< BinarySubstreamRef, BinarySubstreamRef > split (uint64_t Off) const
uint64_t size () const
bool empty () const
Public Attributes
uint64_t Offset = 0
BinaryStreamRef StreamData
Detailed Description
Definition at line 196 of file BinaryStreamRef.h.
Member Function Documentation
drop_front()
BinarySubstreamRef llvm::BinarySubstreamRef::drop_front (uint64_t N) const inline
Definition at line 204 of file BinaryStreamRef.h.
References N, size(), and slice().
Referenced by split().
empty()
bool llvm::BinarySubstreamRef::empty () const inline
Definition at line 214 of file BinaryStreamRef.h.
References size().
Referenced by llvm::pdb::ModuleDebugStreamRef::hasDebugSubsections(), and llvm::pdb::DbiStream::reload().
keep_front()
BinarySubstreamRef llvm::BinarySubstreamRef::keep_front (uint64_t N) const inline
Definition at line 207 of file BinaryStreamRef.h.
References N, and slice().
Referenced by split().
size()
uint64_t llvm::BinarySubstreamRef::size () const inline
Definition at line 213 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::getLength(), and StreamData.
Referenced by drop_front(), empty(), and llvm::pdb::TpiStream::reload().
slice()
BinarySubstreamRef llvm::BinarySubstreamRef::slice (uint64_t Off, uint64_t Size) const inline
Definition at line 200 of file BinaryStreamRef.h.
References Offset, Size, llvm::BinaryStreamRefBase< RefType, StreamType >::slice(), and StreamData.
Referenced by drop_front(), and keep_front().
split()
std::pair< BinarySubstreamRef, BinarySubstreamRef > llvm::BinarySubstreamRef::split (uint64_t Off) const inline
Definition at line 209 of file BinaryStreamRef.h.
References drop_front(), and keep_front().
Member Data Documentation
Offset
uint64_t llvm::BinarySubstreamRef::Offset = 0
Definition at line 197 of file BinaryStreamRef.h.
Referenced by llvm::pdb::LinePrinter::formatMsfStreamData(), llvm::pdb::LinePrinter::formatMsfStreamData(), and slice().
StreamData
BinaryStreamRef llvm::BinarySubstreamRef::StreamData
Definition at line 198 of file BinaryStreamRef.h.
Referenced by llvm::pdb::LinePrinter::formatMsfStreamData(), llvm::pdb::LinePrinter::formatMsfStreamData(), llvm::pdb::DbiStream::reload(), llvm::pdb::TpiStream::reload(), size(), and slice().
The documentation for this struct was generated from the following file:
include/llvm/Support/BinaryStreamRef.h