LLVM: llvm::InstrProfCorrelator::Context Struct Reference
llvm::InstrProfCorrelator::Context Struct Reference
#include "llvm/ProfileData/InstrProfCorrelator.h"
Static Public Member Functions
static llvm::Expected< std::unique_ptr< Context > > get (std::unique_ptr< MemoryBuffer > Buffer, const object::ObjectFile &Obj, ProfCorrelatorKind FileKind)
Public Attributes
std::unique_ptr< MemoryBuffer > Buffer
uint64_t CountersSectionStart
The address range of the __llvm_prf_cnts section.
uint64_t CountersSectionEnd
const char * DataStart
The pointer points to start/end of profile data/name sections if FileKind is Binary.
const char * DataEnd
const char * NameStart
size_t NameSize
bool ShouldSwapBytes
True if target and host have different endian orders.
Detailed Description
Definition at line 73 of file InstrProfCorrelator.h.
Member Function Documentation
get()
llvm::Expected< std::unique_ptr< InstrProfCorrelator::Context > > InstrProfCorrelator::Context::get (std::unique_ptr< MemoryBuffer > Buffer, const object::ObjectFile & Obj, ProfCorrelatorKind FileKind) static
Definition at line 56 of file InstrProfCorrelator.cpp.
References llvm::InstrProfCorrelator::BINARY, Buffer, llvm::CallingConv::C, llvm::Triple::COFF, getInstrProfSection(), llvm::object::Binary::getTripleObjectFormat(), llvm::object::Binary::isLittleEndian(), and llvm::sys::IsLittleEndianHost.
Member Data Documentation
Buffer
std::unique_ptr<MemoryBuffer> llvm::InstrProfCorrelator::Context::Buffer
Definition at line 77 of file InstrProfCorrelator.h.
Referenced by get().
CountersSectionEnd
uint64_t llvm::InstrProfCorrelator::Context::CountersSectionEnd
Definition at line 80 of file InstrProfCorrelator.h.
CountersSectionStart
uint64_t llvm::InstrProfCorrelator::Context::CountersSectionStart
The address range of the __llvm_prf_cnts section.
Definition at line 79 of file InstrProfCorrelator.h.
DataEnd
const char* llvm::InstrProfCorrelator::Context::DataEnd
Definition at line 84 of file InstrProfCorrelator.h.
DataStart
const char* llvm::InstrProfCorrelator::Context::DataStart
The pointer points to start/end of profile data/name sections if FileKind is Binary.
Definition at line 83 of file InstrProfCorrelator.h.
NameSize
size_t llvm::InstrProfCorrelator::Context::NameSize
Definition at line 86 of file InstrProfCorrelator.h.
NameStart
const char* llvm::InstrProfCorrelator::Context::NameStart
Definition at line 85 of file InstrProfCorrelator.h.
ShouldSwapBytes
bool llvm::InstrProfCorrelator::Context::ShouldSwapBytes
True if target and host have different endian orders.
Definition at line 88 of file InstrProfCorrelator.h.
The documentation for this struct was generated from the following files:
include/llvm/ProfileData/InstrProfCorrelator.h
lib/ProfileData/InstrProfCorrelator.cpp