LLVM: llvm::LoopVectorizePass Struct Reference
llvm::LoopVectorizePass Struct Reference
The LoopVectorize Pass.
#include "llvm/Transforms/Vectorize/LoopVectorize.h"
Public Member Functions
LoopVectorizePass (LoopVectorizeOptions Opts={})
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
LoopVectorizeResult runImpl (Function &F, ScalarEvolution &SE_, LoopInfo &LI_, TargetTransformInfo &TTI_, DominatorTree &DT_, BlockFrequencyInfo *BFI_, TargetLibraryInfo *TLI_, DemandedBits &DB_, AssumptionCache &AC_, LoopAccessInfoManager &LAIs_, OptimizationRemarkEmitter &ORE_, ProfileSummaryInfo *PSI_)
bool processLoop (Loop *L)
Public Member Functions inherited from llvm::PassInfoMixin< LoopVectorizePass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Public Attributes
ScalarEvolution * SE
LoopInfo * LI
TargetTransformInfo * TTI
DominatorTree * DT
BlockFrequencyInfo * BFI
TargetLibraryInfo * TLI
DemandedBits * DB
AssumptionCache * AC
LoopAccessInfoManager * LAIs
OptimizationRemarkEmitter * ORE
ProfileSummaryInfo * PSI
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< LoopVectorizePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
The LoopVectorize Pass.
Definition at line 161 of file LoopVectorize.h.
Constructor & Destructor Documentation
LoopVectorizePass()
LoopVectorizePass::LoopVectorizePass (LoopVectorizeOptions Opts = {})
Definition at line 9638 of file LoopVectorize.cpp.
Member Function Documentation
printPipeline()
void LoopVectorizePass::printPipeline (raw_ostream & OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Definition at line 10235 of file LoopVectorize.cpp.
References OS, and printPipeline().
Referenced by printPipeline().
processLoop()
bool LoopVectorizePass::processLoop (Loop * L)
Definition at line 9644 of file LoopVectorize.cpp.
References AC, AddRuntimeUnrollDisableMetaData(), llvm::OptimizationRemarkEmitter::allowExtraAnalysis(), llvm::LoopVectorizeHints::allowVectorization(), llvm::InterleavedAccessInfo::analyzeInterleaving(), areRuntimeChecksProfitable(), llvm::InnerLoopVectorizer::areSafetyChecksAdded(), assert(), BFI, llvm::LoopVectorizationLegality::canVectorize(), llvm::LoopVectorizationLegality::canVectorizeFPMath(), llvm::cast(), checkMixedPrecision(), llvm::CM_ScalarEpilogueNotAllowedLowTripLoop, llvm::CM_ScalarEpilogueNotNeededUsePredicate, llvm::VectorizationFactor::Cost, llvm::InnerLoopVectorizer::createInductionResumeValue(), DB, llvm::dbgs(), DEBUG_TYPE, llvm::VectorizationFactor::Disabled(), DT, llvm::VPlan::duplicate(), llvm::dyn_cast(), llvm::OptimizationRemarkEmitter::emit(), llvm::LoopVectorizeHints::emitRemarkWithHints(), llvm::TargetTransformInfo::enableInterleavedAccessVectorization(), EnableInterleavedMemAccesses, llvm::TargetTransformInfo::enableOrderedReductions(), llvm::EnableVPlanNativePath, llvm::EpilogueLoopVectorizationInfo::EpilogueUF, llvm::EpilogueLoopVectorizationInfo::EpilogueVF, llvm::LoopVectorizationPlanner::executePlan(), F, llvm::LoopVectorizeHints::FK_Disabled, llvm::LoopVectorizeHints::FK_Enabled, ForceOrderedReductions, llvm::LoopVectorizationPlanner::getBestPlan(), llvm::LoopVectorizationPlanner::getBestPlanFor(), llvm::VPBlockBase::getEntryBasicBlock(), llvm::LoopVectorizationRequirements::getExactFPInst(), getExpandedStep(), llvm::LoopVectorizeHints::getForce(), llvm::LoopVectorizeHints::getInterleave(), llvm::LoopVectorizationLegality::getLAI(), llvm::TargetTransformInfo::getMinTripCountTailFoldingThreshold(), llvm::VPlan::getOrAddLiveIn(), getParent(), llvm::PredicatedScalarEvolution::getPredicate(), llvm::VPlan::getPreheader(), llvm::RecurrenceDescriptor::getRecurrenceKind(), llvm::RecurrenceDescriptor::getRecurrenceStartValue(), getScalarEpilogueLowering(), llvm::PredicatedScalarEvolution::getSE(), getSmallBestKnownTC(), llvm::InnerLoopVectorizer::getTripCount(), llvm::VPlan::getTripCount(), llvm::VPlan::getVectorLoopRegion(), getVScaleForTuning(), llvm::LoopVectorizeHints::getWidth(), llvm::hasBranchWeightMD(), llvm::VPlan::hasScalarVFOnly(), llvm::isa(), llvm::RecurrenceDescriptor::isAnyOfRecurrenceKind(), llvm::TargetTransformInfo::isFPVectorizationPotentiallyUnsafe(), llvm::LoopVectorizeHints::isPotentiallyUnsafe(), llvm::ElementCount::isScalar(), llvm::ElementCount::isVector(), LAIs, LI, LLVM_DEBUG, LLVMLoopVectorizeFollowupAll, LLVMLoopVectorizeFollowupEpilogue, LV_NAME, llvm::EpilogueLoopVectorizationInfo::MainLoopIterationCountCheck, llvm::EpilogueLoopVectorizationInfo::MainLoopUF, llvm::EpilogueLoopVectorizationInfo::MainLoopVF, llvm::make_early_inc_range(), llvm::makeFollowupLoopID(), llvm::VectorizationFactor::MinProfitableTripCount, ORE, llvm::LoopVectorizationPlanner::plan(), processLoopInVPlanNativePath(), PSI, llvm::VPValue::replaceAllUsesWith(), llvm::reportVectorization(), llvm::reportVectorizationFailure(), llvm::VPlan::resetTripCount(), SE, llvm::LoopVectorizationPlanner::selectEpilogueVectorizationFactor(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::LoopVectorizeHints::setAlreadyVectorized(), llvm::VPBlockBase::setName(), llvm::InnerLoopVectorizer::setTripCount(), size(), TinyTripCountVectorThreshold, TLI, UseLegacyCostModel, useMaskedInterleavedAccesses(), llvm::VPlan::vectorFactors(), llvm::LoopVectorizeHints::vectorizeAnalysisPassName(), llvm::DominatorTreeBase< NodeT, IsPostDom >::verify(), llvm::verifyFunction(), and llvm::VectorizationFactor::Width.
Referenced by runImpl().
run()
PreservedAnalyses LoopVectorizePass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 10184 of file LoopVectorize.cpp.
References AC, llvm::PreservedAnalyses::all(), BFI, DB, DT, llvm::LoopInfoBase< BlockT, LoopT >::empty(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::ProfileSummaryInfo::hasProfileSummary(), llvm::isAssignmentTrackingEnabled(), LAIs, LI, ORE, llvm::PreservedAnalyses::preserve(), llvm::PreservedAnalyses::preserveSet(), PSI, llvm::RemoveRedundantDbgInstrs(), runImpl(), SE, and TLI.
runImpl()
LoopVectorizeResult LoopVectorizePass::runImpl (Function & F, ScalarEvolution & SE_, LoopInfo & LI_, TargetTransformInfo & TTI_, DominatorTree & DT_, BlockFrequencyInfo * BFI_, TargetLibraryInfo * TLI_, DemandedBits & DB_, AssumptionCache & AC_, LoopAccessInfoManager & LAIs_, OptimizationRemarkEmitter & ORE_, ProfileSummaryInfo * PSI_)
Definition at line 10111 of file LoopVectorize.cpp.
References AC, BFI, Changed, llvm::LoopAccessInfoManager::clear(), collectSupportedLoops(), DB, DT, llvm::SmallVectorBase< Size_T >::empty(), llvm::formLCSSARecursively(), llvm::ElementCount::getFixed(), llvm::TargetTransformInfo::getMaxInterleaveFactor(), llvm::TargetTransformInfo::getNumberOfRegisters(), llvm::TargetTransformInfo::getRegisterClassForType(), LAIs, LI, ORE, llvm::SmallVectorImpl< T >::pop_back_val(), processLoop(), PSI, SE, llvm::simplifyLoop(), llvm::SmallVectorBase< Size_T >::size(), TLI, llvm::ScalarEvolution::verify(), and llvm::VerifySCEV.
Referenced by run().
Member Data Documentation
AC
AssumptionCache* llvm::LoopVectorizePass::AC
Definition at line 181 of file LoopVectorize.h.
Referenced by processLoop(), run(), and runImpl().
BFI
BlockFrequencyInfo* llvm::LoopVectorizePass::BFI
Definition at line 178 of file LoopVectorize.h.
Referenced by processLoop(), run(), and runImpl().
DB
DemandedBits* llvm::LoopVectorizePass::DB
Definition at line 180 of file LoopVectorize.h.
Referenced by processLoop(), run(), and runImpl().
DT
DominatorTree* llvm::LoopVectorizePass::DT
Definition at line 177 of file LoopVectorize.h.
Referenced by processLoop(), run(), and runImpl().
LAIs
LoopAccessInfoManager* llvm::LoopVectorizePass::LAIs
Definition at line 182 of file LoopVectorize.h.
Referenced by processLoop(), run(), and runImpl().
LI
LoopInfo* llvm::LoopVectorizePass::LI
Definition at line 175 of file LoopVectorize.h.
Referenced by processLoop(), run(), and runImpl().
ORE
OptimizationRemarkEmitter* llvm::LoopVectorizePass::ORE
Definition at line 183 of file LoopVectorize.h.
Referenced by processLoop(), run(), and runImpl().
PSI
ProfileSummaryInfo* llvm::LoopVectorizePass::PSI
Definition at line 184 of file LoopVectorize.h.
Referenced by processLoop(), run(), and runImpl().
SE
ScalarEvolution* llvm::LoopVectorizePass::SE
Definition at line 174 of file LoopVectorize.h.
Referenced by processLoop(), run(), and runImpl().
TLI
TargetLibraryInfo* llvm::LoopVectorizePass::TLI
Definition at line 179 of file LoopVectorize.h.
Referenced by processLoop(), run(), and runImpl().
TTI
TargetTransformInfo* llvm::LoopVectorizePass::TTI
Definition at line 176 of file LoopVectorize.h.
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Vectorize/LoopVectorize.h
lib/Transforms/Vectorize/LoopVectorize.cpp