LLVM: llvm::CoroElidePass Struct Reference
llvm::CoroElidePass Struct Reference
#include "llvm/Transforms/Coroutines/CoroElide.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< CoroElidePass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< CoroElidePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 25 of file CoroElide.h.
Member Function Documentation
isRequired()
static bool llvm::CoroElidePass::isRequired () inline static
Definition at line 27 of file CoroElide.h.
run()
PreservedAnalyses CoroElidePass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 467 of file CoroElide.cpp.
References llvm::PreservedAnalyses::all(), Changed, llvm::coro::declaresIntrinsics(), F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::none().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Coroutines/CoroElide.h
lib/Transforms/Coroutines/CoroElide.cpp