LLVM: llvm::support::endian::Writer Struct Reference
llvm::support::endian::Writer Struct Reference
Adapter to write values to a stream in a particular byte order.
#include "llvm/Support/EndianStream.h"
Public Member Functions
Writer (raw_ostream &OS, endianness Endian)
template<typename value_type >
void write (ArrayRef< value_type > Val)
template<typename value_type >
void write (value_type Val)
Public Attributes
raw_ostream & OS
endianness Endian
Detailed Description
Adapter to write values to a stream in a particular byte order.
Definition at line 67 of file EndianStream.h.
Constructor & Destructor Documentation
Writer()
llvm::support::endian::Writer::Writer (raw_ostream & OS, endianness Endian) inline
Definition at line 70 of file EndianStream.h.
Member Function Documentation
write() [1/2]
template<typename value_type > void llvm::support::endian::Writer::write (ArrayRef< value_type > Val) inline
Definition at line 71 of file EndianStream.h.
References OS, and llvm::support::endian::write().
Referenced by llvm::CodeViewContext::encodeDefRange(), llvm::OutlinedHashTreeRecord::serialize(), llvm::msgpack::Writer::write(), llvm::msgpack::Writer::write(), llvm::msgpack::Writer::write(), llvm::msgpack::Writer::write(), llvm::msgpack::Writer::write(), llvm::msgpack::Writer::write(), llvm::ProfOStream::write(), llvm::ProfOStream::write32(), llvm::msgpack::Writer::writeArraySize(), llvm::ProfOStream::writeByte(), llvm::MachObjectWriter::writeDysymtabLoadCommand(), llvm::msgpack::Writer::writeExt(), llvm::MachObjectWriter::writeHeader(), llvm::MachObjectWriter::writeLinkeditLoadCommand(), llvm::MachObjectWriter::writeLinkerOptionsLoadCommand(), llvm::msgpack::Writer::writeMapSize(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeNameTable(), llvm::msgpack::Writer::writeNil(), llvm::MachObjectWriter::writeNlist(), llvm::MachObjectWriter::writeObject(), llvm::MachObjectWriter::writeSection(), llvm::MachObjectWriter::writeSegmentLoadCommand(), and llvm::MachObjectWriter::writeSymtabLoadCommand().
write() [2/2]
template<typename value_type > void llvm::support::endian::Writer::write (value_type Val) inline
Definition at line 74 of file EndianStream.h.
References OS, and llvm::support::endian::write().
Member Data Documentation
Endian
endianness llvm::support::endian::Writer::Endian
Definition at line 69 of file EndianStream.h.
Referenced by llvm::MachObjectWriter::computeSymbolTable(), llvm::MachObjectWriter::writeObject(), and llvm::WinCOFFWriter::writeObject().
OS
raw_ostream& llvm::support::endian::Writer::OS
Definition at line 68 of file EndianStream.h.
Referenced by llvm::MCLOHDirective::emit(), llvm::msgpack::Writer::write(), llvm::msgpack::Writer::write(), write(), write(), llvm::MachObjectWriter::writeDysymtabLoadCommand(), llvm::msgpack::Writer::writeExt(), llvm::MachObjectWriter::writeHeader(), llvm::MachObjectWriter::writeLinkeditLoadCommand(), llvm::MachObjectWriter::writeLinkerOptionsLoadCommand(), llvm::MachObjectWriter::writeNlist(), llvm::MachObjectWriter::writeObject(), llvm::WinCOFFWriter::writeObject(), llvm::MachObjectWriter::writeSection(), llvm::MachObjectWriter::writeSegmentLoadCommand(), and llvm::MachObjectWriter::writeSymtabLoadCommand().
The documentation for this struct was generated from the following file:
include/llvm/Support/EndianStream.h