LLVM: llvm::memprof::IndexedMemProfRecord Struct Reference
llvm::memprof::IndexedMemProfRecord Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
void clear ()
void merge (const IndexedMemProfRecord &Other)
size_t serializedSize (const MemProfSchema &Schema, IndexedVersion Version) const
bool operator== (const IndexedMemProfRecord &Other) const
void serialize (const MemProfSchema &Schema, raw_ostream &OS, IndexedVersion Version, llvm::DenseMap< CallStackId, LinearCallStackId > *MemProfCallStackIndexes=nullptr) const
MemProfRecord toMemProfRecord (llvm::function_ref< std::vector< Frame >(const CallStackId)> Callback) const
Static Public Member Functions
static IndexedMemProfRecord deserialize (const MemProfSchema &Schema, const unsigned char *Buffer, IndexedVersion Version)
static GlobalValue::GUID getGUID (const StringRef FunctionName)
Public Attributes
llvm::SmallVector< IndexedAllocationInfo > AllocSites
llvm::SmallVector< llvm::SmallVector< FrameId > > CallSites
llvm::SmallVector< CallStackId > CallSiteIds
Detailed Description
Definition at line 408 of file MemProf.h.
Member Function Documentation
clear()
void llvm::memprof::IndexedMemProfRecord::clear () inline
Definition at line 422 of file MemProf.h.
References AllocSites, and CallSites.
deserialize()
IndexedMemProfRecord llvm::memprof::IndexedMemProfRecord::deserialize (const MemProfSchema & Schema, const unsigned char * Buffer, IndexedVersion Version) static
Definition at line 326 of file MemProf.cpp.
References llvm::memprof::deserializeV0(), llvm::memprof::deserializeV2(), llvm::memprof::deserializeV3(), llvm_unreachable, Ptr, llvm::memprof::Version0, llvm::memprof::Version1, llvm::memprof::Version2, and llvm::memprof::Version3.
Referenced by llvm::memprof::RecordLookupTrait::ReadData().
getGUID()
GlobalValue::GUID llvm::memprof::IndexedMemProfRecord::getGUID (const StringRef FunctionName) static
Definition at line 360 of file MemProf.cpp.
References llvm::sampleprof::FunctionSamples::getCanonicalFnName(), and llvm::GlobalValue::getGUID().
merge()
void llvm::memprof::IndexedMemProfRecord::merge (const IndexedMemProfRecord & Other) inline
Definition at line 427 of file MemProf.h.
References AllocSites, CallSites, and llvm::Other.
Referenced by llvm::InstrProfWriter::addMemProfRecord().
operator==()
bool llvm::memprof::IndexedMemProfRecord::operator== (const IndexedMemProfRecord & Other) const inline
Definition at line 437 of file MemProf.h.
References AllocSites, CallSiteIds, and llvm::Other.
serialize()
void llvm::memprof::IndexedMemProfRecord::serialize (const MemProfSchema & Schema, raw_ostream & OS, IndexedVersion Version, llvm::DenseMap< CallStackId, LinearCallStackId > * MemProfCallStackIndexes = nullptr) const
Definition at line 195 of file MemProf.cpp.
References llvm_unreachable, OS, llvm::memprof::serializeV0(), llvm::memprof::serializeV2(), llvm::memprof::serializeV3(), llvm::memprof::Version0, llvm::memprof::Version1, llvm::memprof::Version2, and llvm::memprof::Version3.
serializedSize()
size_t llvm::memprof::IndexedMemProfRecord::serializedSize (const MemProfSchema & Schema, IndexedVersion Version) const
Definition at line 117 of file MemProf.cpp.
References llvm_unreachable, llvm::memprof::serializedSizeV0(), llvm::memprof::serializedSizeV2(), llvm::memprof::serializedSizeV3(), llvm::memprof::Version0, llvm::memprof::Version1, llvm::memprof::Version2, and llvm::memprof::Version3.
toMemProfRecord()
MemProfRecord llvm::memprof::IndexedMemProfRecord::toMemProfRecord (llvm::function_ref< std::vector< Frame >(const CallStackId)> Callback) const
Definition at line 341 of file MemProf.cpp.
References AllocSites, CallSiteIds, llvm::memprof::AllocationInfo::CallStack, and llvm::memprof::AllocationInfo::Info.
Referenced by getMemProfRecordV2(), getMemProfRecordV3(), and llvm::memprof::MemProfReader::readNextRecord().
Member Data Documentation
AllocSites
llvm::SmallVector<IndexedAllocationInfo> llvm::memprof::IndexedMemProfRecord::AllocSites
Definition at line 411 of file MemProf.h.
Referenced by clear(), merge(), operator==(), and toMemProfRecord().
CallSiteIds
llvm::SmallVector<CallStackId> llvm::memprof::IndexedMemProfRecord::CallSiteIds
Definition at line 420 of file MemProf.h.
Referenced by operator==(), and toMemProfRecord().
CallSites
llvm::SmallVector<llvm::SmallVector<FrameId> > llvm::memprof::IndexedMemProfRecord::CallSites
Definition at line 417 of file MemProf.h.
Referenced by clear(), and merge().
The documentation for this struct was generated from the following files:
include/llvm/ProfileData/MemProf.h
lib/ProfileData/MemProf.cpp