LLVM: llvm::AACallGraphNode Struct Reference
llvm::AACallGraphNode Struct Reference abstract
#include "llvm/Transforms/IPO/Attributor.h"
Public Member Functions
AACallGraphNode (Attributor &A)
virtual ~AACallGraphNode ()=default
virtual AACallEdgeIterator optimisticEdgesBegin () const =0
virtual AACallEdgeIterator optimisticEdgesEnd () const =0
iterator_range< AACallEdgeIterator > optimisticEdgesRange () const
Iterator range for exploring the call graph.
Protected Attributes
Attributor & A
Reference to Attributor needed for GraphTraits implementation.
Detailed Description
Definition at line 5456 of file Attributor.h.
Constructor & Destructor Documentation
AACallGraphNode()
llvm::AACallGraphNode::AACallGraphNode (Attributor & A) inline
Definition at line 5457 of file Attributor.h.
~AACallGraphNode()
virtual llvm::AACallGraphNode::~AACallGraphNode () virtual default
Member Function Documentation
optimisticEdgesBegin()
virtual AACallEdgeIterator llvm::AACallGraphNode::optimisticEdgesBegin () const pure virtual
Implemented in llvm::AACallEdges, and llvm::AttributorCallGraph.
Referenced by optimisticEdgesRange().
optimisticEdgesEnd()
virtual AACallEdgeIterator llvm::AACallGraphNode::optimisticEdgesEnd () const pure virtual
Implemented in llvm::AACallEdges, and llvm::AttributorCallGraph.
Referenced by optimisticEdgesRange().
optimisticEdgesRange()
iterator_range< AACallEdgeIterator > llvm::AACallGraphNode::optimisticEdgesRange () const inline
Iterator range for exploring the call graph.
Definition at line 5464 of file Attributor.h.
References llvm::iterator_range(), optimisticEdgesBegin(), and optimisticEdgesEnd().
Referenced by llvm::AttributorCallGraph::populateAll().
Member Data Documentation
A
Attributor& llvm::AACallGraphNode::A protected
Reference to Attributor needed for GraphTraits implementation.
Definition at line 5471 of file Attributor.h.
Referenced by llvm::AACallEdges::optimisticEdgesBegin(), llvm::AttributorCallGraph::optimisticEdgesBegin(), llvm::AACallEdges::optimisticEdgesEnd(), and llvm::AttributorCallGraph::optimisticEdgesEnd().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h