LLVM: llvm::VPlanPatternMatch::specific_intval< BitWidth > Struct Template Reference
llvm::VPlanPatternMatch::specific_intval< BitWidth > Struct Template Reference
Match a specified integer value or vector of all elements of that value.
#include "Transforms/Vectorize/VPlanPatternMatch.h"
Public Member Functions
specific_intval (APInt V)
bool match (VPValue *VPV)
Public Attributes
APInt Val
Detailed Description
template<unsigned BitWidth = 0>
struct llvm::VPlanPatternMatch::specific_intval< BitWidth >
Match a specified integer value or vector of all elements of that value.
BitWidth optionally specifies the bitwidth the matched constant must have. If it is 0, the matched constant can have any bitwidth.
Definition at line 56 of file VPlanPatternMatch.h.
Constructor & Destructor Documentation
specific_intval()
template<unsigned BitWidth = 0> llvm::VPlanPatternMatch::specific_intval< BitWidth >::specific_intval (APInt V) inline
Definition at line 59 of file VPlanPatternMatch.h.
Member Function Documentation
match()
template<unsigned BitWidth = 0> bool llvm::VPlanPatternMatch::specific_intval< BitWidth >::match (VPValue * VPV) inline
Definition at line 61 of file VPlanPatternMatch.h.
References assert(), llvm::BitWidth, llvm::CallingConv::C, llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::VPValue::getLiveInIRValue(), llvm::VPValue::isLiveIn(), llvm::APInt::isSameValue(), and llvm::VPlanPatternMatch::specific_intval< BitWidth >::Val.
Member Data Documentation
Val
template<unsigned BitWidth = 0> APInt llvm::VPlanPatternMatch::specific_intval< BitWidth >::Val
Definition at line 57 of file VPlanPatternMatch.h.
Referenced by llvm::VPlanPatternMatch::specific_intval< BitWidth >::match().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlanPatternMatch.h