LLVM: llvm::memprof::LinearCallStackIdConverter Struct Reference
llvm::memprof::LinearCallStackIdConverter Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
LinearCallStackIdConverter ()=delete
LinearCallStackIdConverter (const unsigned char *CallStackBase, std::function< Frame(LinearFrameId)> FrameIdToFrame)
std::vector< Frame > operator() (LinearCallStackId LinearCSId)
Public Attributes
const unsigned char * CallStackBase
std::function< Frame(LinearFrameId)> FrameIdToFrame
Detailed Description
Definition at line 890 of file MemProf.h.
Constructor & Destructor Documentation
LinearCallStackIdConverter() [1/2]
llvm::memprof::LinearCallStackIdConverter::LinearCallStackIdConverter () delete
LinearCallStackIdConverter() [2/2]
llvm::memprof::LinearCallStackIdConverter::LinearCallStackIdConverter (const unsigned char * CallStackBase, std::function< Frame(LinearFrameId)> FrameIdToFrame) inline
Definition at line 895 of file MemProf.h.
Member Function Documentation
operator()()
std::vector< Frame > llvm::memprof::LinearCallStackIdConverter::operator() (LinearCallStackId LinearCSId) inline
Definition at line 899 of file MemProf.h.
References assert(), CallStackBase, FrameIdToFrame, Ptr, llvm::support::endian::read(), and llvm::support::endian::readNext().
Member Data Documentation
CallStackBase
const unsigned char* llvm::memprof::LinearCallStackIdConverter::CallStackBase
Definition at line 891 of file MemProf.h.
Referenced by operator()().
FrameIdToFrame
std::function<Frame(LinearFrameId)> llvm::memprof::LinearCallStackIdConverter::FrameIdToFrame
Definition at line 892 of file MemProf.h.
Referenced by operator()().
The documentation for this struct was generated from the following file:
include/llvm/ProfileData/MemProf.h