LLVM: llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain > Struct Template Reference
llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain > Struct Template Reference
#include "llvm/CodeGen/SDPatternMatch.h"
Public Member Functions
BinaryOpc_match (unsigned Opc, const LHS_P &L, const RHS_P &R)
template<typename MatchContext >
bool match (const MatchContext &Ctx, SDValue N)
Public Attributes
unsigned Opcode
LHS_P LHS
RHS_P RHS
Detailed Description
template<typename LHS_P, typename RHS_P, bool Commutable = false, bool ExcludeChain = false>
struct llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain >
Definition at line 496 of file SDPatternMatch.h.
Constructor & Destructor Documentation
BinaryOpc_match()
template<typename LHS_P , typename RHS_P , bool Commutable = false, bool ExcludeChain = false> llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain >::BinaryOpc_match (unsigned Opc, const LHS_P & L, const RHS_P & R) inline
Definition at line 501 of file SDPatternMatch.h.
Member Function Documentation
match()
template<typename LHS_P , typename RHS_P , bool Commutable = false, bool ExcludeChain = false> template<typename MatchContext > bool llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain >::match (const MatchContext & Ctx, SDValue N) inline
Definition at line 505 of file SDPatternMatch.h.
References assert(), llvm::SDPatternMatch::EffectiveOperands< ExcludeChain >::FirstIndex, llvm::SDPatternMatch::m_Opc(), N, llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain >::Opcode, llvm::SDPatternMatch::sd_context_match(), and llvm::SDPatternMatch::EffectiveOperands< ExcludeChain >::Size.
Member Data Documentation
LHS
template<typename LHS_P , typename RHS_P , bool Commutable = false, bool ExcludeChain = false> LHS_P llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain >::LHS
Definition at line 498 of file SDPatternMatch.h.
Opcode
template<typename LHS_P , typename RHS_P , bool Commutable = false, bool ExcludeChain = false> unsigned llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain >::Opcode
Definition at line 497 of file SDPatternMatch.h.
Referenced by llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain >::match().
RHS
template<typename LHS_P , typename RHS_P , bool Commutable = false, bool ExcludeChain = false> RHS_P llvm::SDPatternMatch::BinaryOpc_match< LHS_P, RHS_P, Commutable, ExcludeChain >::RHS
Definition at line 499 of file SDPatternMatch.h.
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/SDPatternMatch.h