LLVM: StackAccess Struct Reference
StackAccess Struct Reference
Public Types
enum AccessType { NotAccessed = 0 , GPR = 1 << 0 , PPR = 1 << 1 , FPR = 1 << 2 }
Public Member Functions
StackAccess ()
bool operator< (const StackAccess &Rhs) const
bool isCPU () const
bool isSME () const
bool isMixed () const
int64_t start () const
int64_t end () const
std::string getTypeString () const
void print (raw_ostream &OS) const
Public Attributes
int Idx
StackOffset Offset
int64_t Size
unsigned AccessTypes
Detailed Description
Definition at line 5017 of file AArch64FrameLowering.cpp.
Member Enumeration Documentation
AccessType
enum StackAccess::AccessType
Enumerator
NotAccessed
GPR
PPR
FPR
Definition at line 5018 of file AArch64FrameLowering.cpp.
Constructor & Destructor Documentation
StackAccess()
StackAccess::StackAccess () inline
Definition at line 5030 of file AArch64FrameLowering.cpp.
Member Function Documentation
end()
int64_t StackAccess::end () const inline
Definition at line 5045 of file AArch64FrameLowering.cpp.
References Size.
getTypeString()
std::string StackAccess::getTypeString () const inline
Definition at line 5047 of file AArch64FrameLowering.cpp.
isCPU()
bool StackAccess::isCPU () const inline
Definition at line 5037 of file AArch64FrameLowering.cpp.
isMixed()
bool StackAccess::isMixed () const inline
Definition at line 5042 of file AArch64FrameLowering.cpp.
isSME()
bool StackAccess::isSME () const inline
Definition at line 5041 of file AArch64FrameLowering.cpp.
operator<()
bool StackAccess::operator< (const StackAccess & Rhs) const inline
Definition at line 5032 of file AArch64FrameLowering.cpp.
References Idx, and start().
print()
void StackAccess::print (raw_ostream & OS) const inline
Definition at line 5062 of file AArch64FrameLowering.cpp.
References getTypeString(), llvm::Offset, and OS.
Referenced by operator<<().
start()
int64_t StackAccess::start () const inline
Definition at line 5044 of file AArch64FrameLowering.cpp.
References llvm::Offset.
Referenced by operator<().
Member Data Documentation
AccessTypes
unsigned StackAccess::AccessTypes
Definition at line 5028 of file AArch64FrameLowering.cpp.
Idx
int StackAccess::Idx
Definition at line 5025 of file AArch64FrameLowering.cpp.
Referenced by operator<().
Offset
StackOffset StackAccess::Offset
Definition at line 5026 of file AArch64FrameLowering.cpp.
Size
int64_t StackAccess::Size
Definition at line 5027 of file AArch64FrameLowering.cpp.
The documentation for this struct was generated from the following file:
lib/Target/AArch64/AArch64FrameLowering.cpp