LLVM: llvm::KnownBits Struct Reference
llvm::KnownBits Struct Reference
#include "llvm/Support/KnownBits.h"
Public Member Functions
KnownBits ()=default
KnownBits (unsigned BitWidth)
Create a known bits object of BitWidth bits initialized to unknown.
unsigned getBitWidth () const
Get the bit width of this value.
bool hasConflict () const
Returns true if there is conflicting information.
bool isConstant () const
Returns true if we know the value of all bits.
const APInt & getConstant () const
Returns the value when all bits have a known value.
bool isUnknown () const
Returns true if we don't know any bits.
bool isSignUnknown () const
Returns true if we don't know the sign bit.
void resetAll ()
Resets the known state of all bits.
bool isZero () const
Returns true if value is all zero.
bool isAllOnes () const
Returns true if value is all one bits.
void setAllZero ()
Make all bits known to be zero and discard any previous information.
void setAllOnes ()
Make all bits known to be one and discard any previous information.
bool isNegative () const
Returns true if this value is known to be negative.
bool isNonNegative () const
Returns true if this value is known to be non-negative.
bool isNonZero () const
Returns true if this value is known to be non-zero.
bool isStrictlyPositive () const
Returns true if this value is known to be positive.
void makeNegative ()
Make this value negative.
void makeNonNegative ()
Make this value non-negative.
APInt getMinValue () const
Return the minimal unsigned value possible given these KnownBits.
APInt getSignedMinValue () const
Return the minimal signed value possible given these KnownBits.
APInt getMaxValue () const
Return the maximal unsigned value possible given these KnownBits.
APInt getSignedMaxValue () const
Return the maximal signed value possible given these KnownBits.
KnownBits trunc (unsigned BitWidth) const
Return known bits for a truncation of the value we're tracking.
KnownBits anyext (unsigned BitWidth) const
Return known bits for an "any" extension of the value we're tracking, where we don't know anything about the extended bits.
KnownBits zext (unsigned BitWidth) const
Return known bits for a zero extension of the value we're tracking.
KnownBits sext (unsigned BitWidth) const
Return known bits for a sign extension of the value we're tracking.
KnownBits anyextOrTrunc (unsigned BitWidth) const
Return known bits for an "any" extension or truncation of the value we're tracking.
KnownBits zextOrTrunc (unsigned BitWidth) const
Return known bits for a zero extension or truncation of the value we're tracking.
KnownBits sextOrTrunc (unsigned BitWidth) const
Return known bits for a sign extension or truncation of the value we're tracking.
KnownBits sextInReg (unsigned SrcBitWidth) const
Return known bits for a in-register sign extension of the value we're tracking.
void insertBits (const KnownBits &SubBits, unsigned BitPosition)
Insert the bits from a smaller known bits starting at bitPosition.
KnownBits extractBits (unsigned NumBits, unsigned BitPosition) const
Return a subset of the known bits from [bitPosition,bitPosition+numBits).
KnownBits concat (const KnownBits &Lo) const
Concatenate the bits from Lo onto the bottom of *this.
KnownBits makeGE (const APInt &Val) const
Return KnownBits based on this, but updated given that the underlying value is known to be greater than or equal to Val.
unsigned countMinTrailingZeros () const
Returns the minimum number of trailing zero bits.
unsigned countMinTrailingOnes () const
Returns the minimum number of trailing one bits.
unsigned countMinLeadingZeros () const
Returns the minimum number of leading zero bits.
unsigned countMinLeadingOnes () const
Returns the minimum number of leading one bits.
unsigned countMinSignBits () const
Returns the number of times the sign bit is replicated into the other bits.
unsigned countMaxSignificantBits () const
Returns the maximum number of bits needed to represent all possible signed values with these known bits.
unsigned countMaxTrailingZeros () const
Returns the maximum number of trailing zero bits possible.
unsigned countMaxTrailingOnes () const
Returns the maximum number of trailing one bits possible.
unsigned countMaxLeadingZeros () const
Returns the maximum number of leading zero bits possible.
unsigned countMaxLeadingOnes () const
Returns the maximum number of leading one bits possible.
unsigned countMinPopulation () const
Returns the number of bits known to be one.
unsigned countMaxPopulation () const
Returns the maximum number of bits that could be one.
unsigned countMaxActiveBits () const
Returns the maximum number of bits needed to represent all possible unsigned values with these known bits.
KnownBits intersectWith (const KnownBits &RHS) const
Returns KnownBits information that is known to be true for both this and RHS.
KnownBits unionWith (const KnownBits &RHS) const
Returns KnownBits information that is known to be true for either this or RHS or both.
KnownBits & operator&= (const KnownBits &RHS)
Update known bits based on ANDing with RHS.
KnownBits & operator|= (const KnownBits &RHS)
Update known bits based on ORing with RHS.
KnownBits & operator^= (const KnownBits &RHS)
Update known bits based on XORing with RHS.
KnownBits abs (bool IntMinIsPoison=false) const
Compute known bits for the absolute value.
KnownBits byteSwap () const
KnownBits reverseBits () const
KnownBits blsi () const
Compute known bits for X & -X, which has only the lowest bit set of X set.
KnownBits blsmsk () const
Compute known bits for X ^ (X - 1), which has all bits up to and including the lowest set bit of X set.
bool operator== (const KnownBits &Other) const
bool operator!= (const KnownBits &Other) const
void print (raw_ostream &OS) const
void dump () const
Static Public Member Functions
static KnownBits makeConstant (const APInt &C)
Create known bits from a known constant.
static bool haveNoCommonBitsSet (const KnownBits &LHS, const KnownBits &RHS)
Return true if LHS and RHS have no common bits set.
static KnownBits computeForAddCarry (const KnownBits &LHS, const KnownBits &RHS, const KnownBits &Carry)
Compute known bits resulting from adding LHS, RHS and a 1-bit Carry.
static KnownBits computeForAddSub (bool Add, bool NSW, bool NUW, const KnownBits &LHS, const KnownBits &RHS)
Compute known bits resulting from adding LHS and RHS.
static KnownBits computeForSubBorrow (const KnownBits &LHS, KnownBits RHS, const KnownBits &Borrow)
Compute known bits results from subtracting RHS from LHS with 1-bit Borrow.
static KnownBits sadd_sat (const KnownBits &LHS, const KnownBits &RHS)
Compute knownbits resulting from llvm.sadd.sat(LHS, RHS)
static KnownBits uadd_sat (const KnownBits &LHS, const KnownBits &RHS)
Compute knownbits resulting from llvm.uadd.sat(LHS, RHS)
static KnownBits ssub_sat (const KnownBits &LHS, const KnownBits &RHS)
Compute knownbits resulting from llvm.ssub.sat(LHS, RHS)
static KnownBits usub_sat (const KnownBits &LHS, const KnownBits &RHS)
Compute knownbits resulting from llvm.usub.sat(LHS, RHS)
static KnownBits avgFloorS (const KnownBits &LHS, const KnownBits &RHS)
Compute knownbits resulting from APIntOps::avgFloorS.
static KnownBits avgFloorU (const KnownBits &LHS, const KnownBits &RHS)
Compute knownbits resulting from APIntOps::avgFloorU.
static KnownBits avgCeilS (const KnownBits &LHS, const KnownBits &RHS)
Compute knownbits resulting from APIntOps::avgCeilS.
static KnownBits avgCeilU (const KnownBits &LHS, const KnownBits &RHS)
Compute knownbits resulting from APIntOps::avgCeilU.
static KnownBits mul (const KnownBits &LHS, const KnownBits &RHS, bool NoUndefSelfMultiply=false)
Compute known bits resulting from multiplying LHS and RHS.
static KnownBits mulhs (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits from sign-extended multiply-hi.
static KnownBits mulhu (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits from zero-extended multiply-hi.
static KnownBits sdiv (const KnownBits &LHS, const KnownBits &RHS, bool Exact=false)
Compute known bits for sdiv(LHS, RHS).
static KnownBits udiv (const KnownBits &LHS, const KnownBits &RHS, bool Exact=false)
Compute known bits for udiv(LHS, RHS).
static KnownBits urem (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for urem(LHS, RHS).
static KnownBits srem (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for srem(LHS, RHS).
static KnownBits umax (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for umax(LHS, RHS).
static KnownBits umin (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for umin(LHS, RHS).
static KnownBits smax (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for smax(LHS, RHS).
static KnownBits smin (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for smin(LHS, RHS).
static KnownBits abdu (const KnownBits &LHS, const KnownBits &RHS)
Compute known bits for abdu(LHS, RHS).
static KnownBits abds (KnownBits LHS, KnownBits RHS)
Compute known bits for abds(LHS, RHS).
static KnownBits shl (const KnownBits &LHS, const KnownBits &RHS, bool NUW=false, bool NSW=false, bool ShAmtNonZero=false)
Compute known bits for shl(LHS, RHS).
static KnownBits lshr (const KnownBits &LHS, const KnownBits &RHS, bool ShAmtNonZero=false, bool Exact=false)
Compute known bits for lshr(LHS, RHS).
static KnownBits ashr (const KnownBits &LHS, const KnownBits &RHS, bool ShAmtNonZero=false, bool Exact=false)
Compute known bits for ashr(LHS, RHS).
static std::optional< bool > eq (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_EQ result.
static std::optional< bool > ne (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_NE result.
static std::optional< bool > ugt (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_UGT result.
static std::optional< bool > uge (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_UGE result.
static std::optional< bool > ult (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_ULT result.
static std::optional< bool > ule (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_ULE result.
static std::optional< bool > sgt (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_SGT result.
static std::optional< bool > sge (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_SGE result.
static std::optional< bool > slt (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_SLT result.
static std::optional< bool > sle (const KnownBits &LHS, const KnownBits &RHS)
Determine if these known bits always give the same ICMP_SLE result.
Public Attributes
APInt Zero
APInt One
Detailed Description
Definition at line 23 of file KnownBits.h.
Constructor & Destructor Documentation
KnownBits() [1/2]
llvm::KnownBits::KnownBits () default
Referenced by anyext(), byteSwap(), concat(), extractBits(), intersectWith(), makeConstant(), makeGE(), reverseBits(), sext(), smax(), smin(), trunc(), umin(), unionWith(), and zext().
KnownBits() [2/2]
llvm::KnownBits::KnownBits (unsigned BitWidth) inline
Create a known bits object of BitWidth bits initialized to unknown.
Definition at line 37 of file KnownBits.h.
Member Function Documentation
abds()
KnownBits KnownBits::abds (KnownBits LHS, KnownBits RHS) static
Compute known bits for abds(LHS, RHS).
Definition at line 247 of file KnownBits.cpp.
References computeForAddSub(), intersectWith(), and LHS.
Referenced by llvm::SelectionDAG::computeKnownBits().
abdu()
KnownBits KnownBits::abdu (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for abdu(LHS, RHS).
Definition at line 228 of file KnownBits.cpp.
References computeForAddSub(), and intersectWith().
Referenced by llvm::SelectionDAG::computeKnownBits(), and computeKnownBitsForPSADBW().
abs()
KnownBits KnownBits::abs (bool IntMinIsPoison = false) const
Compute known bits for the absolute value.
Definition at line 550 of file KnownBits.cpp.
References llvm::APInt::clearSignBit(), computeForAddSub(), countMaxPopulation(), countMaxTrailingZeros(), countMinLeadingZeros(), countMinPopulation(), countMinTrailingZeros(), getBitWidth(), llvm::APInt::isMinSignedValue(), isNegative(), isNonNegative(), llvm::APInt::isZero(), makeConstant(), One, llvm::APInt::popcount(), llvm::APInt::setBit(), llvm::APInt::setBits(), llvm::APInt::setLowBits(), llvm::APInt::setSignBit(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), and isKnownNonZeroFromOperator().
anyext()
KnownBits llvm::KnownBits::anyext (unsigned BitWidth) const inline
Return known bits for an "any" extension of the value we're tracking, where we don't know anything about the extended bits.
Definition at line 156 of file KnownBits.h.
References llvm::BitWidth, KnownBits(), One, Zero, and llvm::APInt::zext().
Referenced by anyextOrTrunc(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromICmpCond(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::FunctionLoweringInfo::GetLiveOutRegInfo(), and llvm::TargetLowering::SimplifyDemandedBits().
anyextOrTrunc()
KnownBits llvm::KnownBits::anyextOrTrunc (unsigned BitWidth) const inline
Return known bits for an "any" extension or truncation of the value we're tracking.
Definition at line 175 of file KnownBits.h.
References anyext(), llvm::BitWidth, getBitWidth(), and trunc().
Referenced by llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
ashr()
KnownBits KnownBits::ashr (const KnownBits & LHS, const KnownBits & RHS, bool ShAmtNonZero = false, bool Exact = false) static
Compute known bits for ashr(LHS, RHS).
NOTE: RHS (shift amount) bitwidth doesn't need to be the same as LHS.
Definition at line 428 of file KnownBits.cpp.
References llvm::APInt::ashrInPlace(), llvm::BitWidth, getMaxShiftAmount(), llvm::APInt::getMaxValue(), hasConflict(), intersectWith(), isUnknown(), LHS, One, llvm::APInt::setAllBits(), setAllZero(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
avgCeilS()
KnownBits KnownBits::avgCeilS (const KnownBits & LHS, const KnownBits & RHS) static
Compute knownbits resulting from APIntOps::avgCeilS.
Definition at line 787 of file KnownBits.cpp.
References avgCompute().
Referenced by llvm::SelectionDAG::computeKnownBits().
avgCeilU()
KnownBits KnownBits::avgCeilU (const KnownBits & LHS, const KnownBits & RHS) static
Compute knownbits resulting from APIntOps::avgCeilU.
Definition at line 792 of file KnownBits.cpp.
References avgCompute().
Referenced by llvm::SelectionDAG::computeKnownBits().
avgFloorS()
KnownBits KnownBits::avgFloorS (const KnownBits & LHS, const KnownBits & RHS) static
Compute knownbits resulting from APIntOps::avgFloorS.
Definition at line 777 of file KnownBits.cpp.
References avgCompute().
Referenced by llvm::SelectionDAG::computeKnownBits().
avgFloorU()
KnownBits KnownBits::avgFloorU (const KnownBits & LHS, const KnownBits & RHS) static
Compute knownbits resulting from APIntOps::avgFloorU.
Definition at line 782 of file KnownBits.cpp.
References avgCompute().
Referenced by llvm::SelectionDAG::computeKnownBits().
blsi()
KnownBits KnownBits::blsi () const
Compute known bits for X & -X, which has only the lowest bit set of X set.
The name comes from the X86 BMI instruction
Definition at line 1109 of file KnownBits.cpp.
References llvm::BitWidth, countMaxTrailingZeros(), countMinTrailingZeros(), getBitWidth(), One, llvm::APInt::setBit(), llvm::APInt::setBitsFrom(), and Zero.
Referenced by getKnownBitsFromAndXorOr().
blsmsk()
KnownBits KnownBits::blsmsk () const
Compute known bits for X ^ (X - 1), which has all bits up to and including the lowest set bit of X set.
The name comes from the X86 BMI instruction.
Definition at line 1120 of file KnownBits.cpp.
References llvm::BitWidth, countMaxTrailingZeros(), countMinTrailingZeros(), getBitWidth(), One, llvm::APInt::setBitsFrom(), llvm::APInt::setLowBits(), and Zero.
Referenced by getKnownBitsFromAndXorOr().
byteSwap()
KnownBits llvm::KnownBits::byteSwap () const inline
Definition at line 456 of file KnownBits.h.
References llvm::APInt::byteSwap(), KnownBits(), One, and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), and llvm::GISelKnownBits::computeKnownBitsImpl().
computeForAddCarry()
KnownBits KnownBits::computeForAddCarry (const KnownBits & LHS, const KnownBits & RHS, const KnownBits & Carry) static
Compute known bits resulting from adding LHS, RHS and a 1-bit Carry.
Definition at line 44 of file KnownBits.cpp.
References assert(), getBitWidth(), llvm::APInt::getBoolValue(), One, and Zero.
Referenced by computeForAddSub(), and llvm::SelectionDAG::computeKnownBits().
computeForAddSub()
KnownBits KnownBits::computeForAddSub (bool Add, bool NSW, bool NUW, const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits resulting from adding LHS and RHS.
Definition at line 51 of file KnownBits.cpp.
References llvm::Add, llvm::BitWidth, computeForAddCarry(), llvm::APInt::countl_one(), llvm::APInt::countl_zero(), llvm::APInt::getMaxValue(), llvm::APInt::getMinValue(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), hasConflict(), llvm::APInt::isNegative(), llvm::APInt::isNonNegative(), One, RHS, llvm::APInt::sadd_sat(), setAllZero(), llvm::APInt::setBits(), llvm::APInt::setHighBits(), llvm::APInt::setSignBit(), llvm::APInt::ssub_sat(), std::swap(), llvm::APInt::trunc(), llvm::APInt::uadd_sat(), llvm::APInt::usub_sat(), and Zero.
Referenced by abds(), abdu(), abs(), computeForSatAddSub(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsAddSub(), computeKnownBitsForPMADDWD(), computeKnownBitsForPSADBW(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), isNonZeroAdd(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), and llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits().
computeForSubBorrow()
KnownBits KnownBits::computeForSubBorrow (const KnownBits & LHS, KnownBits RHS, const KnownBits & Borrow) static
Compute known bits results from subtracting RHS from LHS with 1-bit Borrow.
Definition at line 137 of file KnownBits.cpp.
References assert(), getBitWidth(), llvm::APInt::getBoolValue(), One, std::swap(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits().
concat()
KnownBits llvm::KnownBits::concat (const KnownBits & Lo) const inline
Concatenate the bits from Lo onto the bottom of *this.
This is equivalent to: (this->zext(NewWidth) << Lo.getBitWidth()) | Lo.zext(NewWidth)
Definition at line 222 of file KnownBits.h.
References llvm::APInt::concat(), KnownBits(), llvm::Lo, One, and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), and llvm::TargetLowering::SimplifyDemandedBits().
countMaxActiveBits()
unsigned llvm::KnownBits::countMaxActiveBits () const inline
Returns the maximum number of bits needed to represent all possible unsigned values with these known bits.
This is the inverse of the minimum number of leading zeros.
Definition at line 285 of file KnownBits.h.
References countMinLeadingZeros(), and getBitWidth().
Referenced by combinePMULH(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::SITargetLowering::computeKnownBitsForTargetNode(), detectExtMul(), getPack(), narrowIndex(), llvm::AMDGPUTargetLowering::numBitsUnsigned(), simplifyAndInst(), and simplifyLShrInst().
countMaxLeadingOnes()
unsigned llvm::KnownBits::countMaxLeadingOnes () const inline
Returns the maximum number of leading one bits possible.
Definition at line 272 of file KnownBits.h.
References llvm::APInt::countl_zero(), and Zero.
countMaxLeadingZeros()
unsigned llvm::KnownBits::countMaxLeadingZeros () const inline
Returns the maximum number of leading zero bits possible.
Definition at line 269 of file KnownBits.h.
References llvm::APInt::countl_zero(), and One.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), and foldCttzCtlz().
countMaxPopulation()
unsigned llvm::KnownBits::countMaxPopulation () const inline
Returns the maximum number of bits that could be one.
Definition at line 278 of file KnownBits.h.
References getBitWidth(), llvm::APInt::popcount(), and Zero.
Referenced by abs(), combineMOVMSK(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), foldCtpop(), llvm::InstCombinerImpl::foldICmpWithZero(), llvm::isKnownToBeAPowerOfTwo(), and llvm::TargetLowering::SimplifySetCC().
countMaxSignificantBits()
unsigned llvm::KnownBits::countMaxSignificantBits () const inline
Returns the maximum number of bits needed to represent all possible signed values with these known bits.
This is the inverse of the minimum number of known sign bits. Examples for bitwidth 5: 110?? --> 4 0000? --> 2
Definition at line 258 of file KnownBits.h.
References countMinSignBits(), and getBitWidth().
Referenced by llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode().
countMaxTrailingOnes()
unsigned llvm::KnownBits::countMaxTrailingOnes () const inline
Returns the maximum number of trailing one bits possible.
Definition at line 266 of file KnownBits.h.
References llvm::APInt::countr_zero(), and Zero.
countMaxTrailingZeros()
unsigned llvm::KnownBits::countMaxTrailingZeros () const inline
Returns the maximum number of trailing zero bits possible.
Definition at line 263 of file KnownBits.h.
References llvm::APInt::countr_zero(), and One.
Referenced by abs(), blsi(), blsmsk(), llvm::SelectionDAG::computeKnownBits(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpWithZero(), getKnownBitsFromAndXorOr(), isNonZeroMul(), and simplifyDiv().
countMinLeadingOnes()
unsigned llvm::KnownBits::countMinLeadingOnes () const inline
Returns the minimum number of leading one bits.
Definition at line 240 of file KnownBits.h.
References llvm::APInt::countl_one(), and One.
Referenced by computeKnownBitsFromOperator(), countMinSignBits(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), and llvm::InstCombinerImpl::visitSwitchInst().
countMinLeadingZeros()
unsigned llvm::KnownBits::countMinLeadingZeros () const inline
Returns the minimum number of leading zero bits.
Definition at line 237 of file KnownBits.h.
References llvm::APInt::countl_one(), and Zero.
Referenced by abs(), llvm::TargetLowering::BuildUDIV(), llvm::CombinerHelper::buildUDivUsingMul(), checkDot4MulSignedness(), combineMOVMSK(), combineScalarToVector(), combineShiftToAVG(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), countMaxActiveBits(), countMinSignBits(), llvm::TargetLowering::expandAVG(), llvm::TargetLowering::expandFixedPointDiv(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpAndConstConst(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::RegsForValue::getCopyFromRegs(), isKnownExactCastIntToFP(), LowerAndToBT(), LowerCTPOP(), llvm::SITargetLowering::lowerSET_ROUNDING(), lowerShuffleWithVPMOV(), matchBinaryShuffle(), llvm::CombinerHelper::matchCombineZextTrunc(), matchTruncateWithPACK(), llvm::AMDGPUTargetLowering::performShlCombine(), llvm::X86TargetLowering::ReplaceNodeResults(), setShiftFlags(), llvm::TargetLowering::SimplifyDemandedBits(), simplifyDivRem(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitSwitchInst().
countMinPopulation()
unsigned llvm::KnownBits::countMinPopulation () const inline
Returns the number of bits known to be one.
Definition at line 275 of file KnownBits.h.
References One, and llvm::APInt::popcount().
Referenced by abs(), foldCtpop(), foldCtpopPow2Test(), llvm::InstCombinerImpl::foldICmpWithZero(), llvm::isKnownToBeAPowerOfTwo(), and llvm::TargetLowering::SimplifySetCC().
countMinSignBits()
unsigned llvm::KnownBits::countMinSignBits () const inline
Returns the number of times the sign bit is replicated into the other bits.
Definition at line 244 of file KnownBits.h.
References countMinLeadingOnes(), countMinLeadingZeros(), isNegative(), and isNonNegative().
Referenced by llvm::SelectionDAG::ComputeNumSignBits(), ComputeNumSignBitsImpl(), countMaxSignificantBits(), setShiftFlags(), and llvm::TargetLowering::SimplifyDemandedBits().
countMinTrailingOnes()
unsigned llvm::KnownBits::countMinTrailingOnes () const inline
Returns the minimum number of trailing one bits.
Definition at line 234 of file KnownBits.h.
References llvm::APInt::countr_one(), and One.
Referenced by getKnownBitsFromAndXorOr().
countMinTrailingZeros()
unsigned llvm::KnownBits::countMinTrailingZeros () const inline
Returns the minimum number of trailing zero bits.
Definition at line 231 of file KnownBits.h.
References llvm::APInt::countr_one(), and Zero.
Referenced by abs(), blsi(), blsmsk(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::TargetLowering::expandFixedPointDiv(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::getOrEnforceKnownAlignment(), inferAlignment(), llvm::SelectionDAG::InferPtrAlign(), isKnownExactCastIntToFP(), isWordAligned(), LowerCTPOP(), llvm::X86TargetLowering::ReplaceNodeResults(), setShiftFlags(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), simplifyShift(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitSDiv().
dump()
void KnownBits::dump () const
Definition at line 1144 of file KnownBits.cpp.
References llvm::dbgs(), and print().
eq()
std::optional< bool > KnownBits::eq (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_EQ result.
Definition at line 488 of file KnownBits.cpp.
Referenced by llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), and ne().
extractBits()
KnownBits llvm::KnownBits::extractBits (unsigned NumBits, unsigned BitPosition) const inline
Return a subset of the known bits from [bitPosition,bitPosition+numBits).
Definition at line 214 of file KnownBits.h.
References llvm::APInt::extractBits(), KnownBits(), One, and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::GISelKnownBits::computeKnownBitsImpl(), mulhs(), mulhu(), and llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode().
getBitWidth()
unsigned llvm::KnownBits::getBitWidth () const inline
Get the bit width of this value.
Definition at line 40 of file KnownBits.h.
References assert(), llvm::APInt::getBitWidth(), One, and Zero.
Referenced by abs(), llvm::adjustKnownBitsForSelectArm(), anyextOrTrunc(), blsi(), blsmsk(), combineFMulcFCMulc(), computeForAddCarry(), computeForSatAddSub(), computeForSubBorrow(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromCmp(), computeKnownBitsFromCond(), llvm::computeKnownBitsFromContext(), computeKnownBitsFromICmpCond(), computeKnownBitsFromOperator(), llvm::computeKnownBitsFromRangeMetadata(), computeKnownBitsFromShiftOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), countMaxActiveBits(), countMaxPopulation(), countMaxSignificantBits(), eliminateDeadSwitchCases(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::ConstantRange::fromKnownBits(), getKnownBitsFromAndXorOr(), llvm::FunctionLoweringInfo::GetLiveOutRegInfo(), llvm::getOrEnforceKnownAlignment(), inferAlignment(), isConstant(), llvm::SelectionDAG::isKnownNeverZero(), isNonZeroShift(), LowerCTPOP(), makeGE(), print(), setShiftFlags(), sextInReg(), sextOrTrunc(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::InstCombinerImpl::SimplifyDemandedInstructionBits(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyDivRem(), simplifyShift(), tryBitfieldInsertOpFromOr(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitSwitchInst(), zext(), and zextOrTrunc().
getConstant()
const APInt & llvm::KnownBits::getConstant () const inline
Returns the value when all bits have a known value.
This just returns One with a protective assertion.
Definition at line 56 of file KnownBits.h.
References assert(), isConstant(), and One.
Referenced by combineFMulcFCMulc(), computeKnownBitsFromOperator(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), LowerVectorAllEqual(), and llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode().
getMaxValue()
APInt llvm::KnownBits::getMaxValue () const inline
Return the maximal unsigned value possible given these KnownBits.
Definition at line 134 of file KnownBits.h.
Referenced by llvm::SelectionDAG::canCreateUndefOrPoison(), canEvaluateTruncated(), combineArithReduction(), computeKnownBitsFromShiftOperator(), llvm::SelectionDAG::computeOverflowForUnsignedAdd(), llvm::InstCombinerImpl::convertOrOfShiftsToFunnelShift(), extractBits(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::ConstantRange::fromKnownBits(), llvm::SelectionDAG::getValidShiftAmountRange(), llvm::SelectionDAG::isKnownNeverZero(), isNonZeroShift(), llvm::CombinerHelper::matchCombineTruncOfShift(), llvm::AMDGPUTargetLowering::performTruncateCombine(), setShiftFlags(), simplifyAndInst(), simplifyX86immShift(), simplifyX86varShift(), and llvm::InstCombinerImpl::visitAnd().
getMinValue()
APInt llvm::KnownBits::getMinValue () const inline
Return the minimal unsigned value possible given these KnownBits.
Definition at line 118 of file KnownBits.h.
References One.
Referenced by extractBits(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::ConstantRange::fromKnownBits(), simplifyShift(), and simplifyX86immShift().
getSignedMaxValue()
APInt llvm::KnownBits::getSignedMaxValue () const inline
Return the maximal signed value possible given these KnownBits.
Definition at line 140 of file KnownBits.h.
References llvm::APInt::isSignBitClear(), and One.
Referenced by llvm::InstCombinerImpl::foldICmpUsingKnownBits().
getSignedMinValue()
APInt llvm::KnownBits::getSignedMinValue () const inline
Return the minimal signed value possible given these KnownBits.
Definition at line 124 of file KnownBits.h.
References llvm::APInt::isSignBitClear(), One, llvm::APInt::setSignBit(), and Zero.
Referenced by cannotBeIntMin(), and llvm::InstCombinerImpl::foldICmpUsingKnownBits().
hasConflict()
bool llvm::KnownBits::hasConflict () const inline
Returns true if there is conflicting information.
Definition at line 47 of file KnownBits.h.
References llvm::APInt::intersects(), One, and Zero.
Referenced by llvm::adjustKnownBitsForSelectArm(), ashr(), computeForAddSub(), computeKnownBits(), llvm::computeKnownBitsFromContext(), computeKnownBitsFromOperator(), divComputeLowBit(), llvm::ConstantRange::fromKnownBits(), lshr(), shl(), and simplifyShift().
haveNoCommonBitsSet()
static bool llvm::KnownBits::haveNoCommonBitsSet (const KnownBits & LHS, const KnownBits & RHS) inline static
Return true if LHS and RHS have no common bits set.
Definition at line 315 of file KnownBits.h.
Referenced by llvm::haveNoCommonBitsSet(), and llvm::SelectionDAG::haveNoCommonBitsSet().
insertBits()
void llvm::KnownBits::insertBits (const KnownBits & SubBits, unsigned BitPosition) inline
Insert the bits from a smaller known bits starting at bitPosition.
Definition at line 208 of file KnownBits.h.
References llvm::APInt::insertBits(), One, and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), and llvm::GISelKnownBits::computeKnownBitsImpl().
intersectWith()
KnownBits llvm::KnownBits::intersectWith (const KnownBits & RHS) const inline
Returns KnownBits information that is known to be true for both this and RHS.
When an operation is known to return one of its operands, this can be used to combine information about the known bits of the operands to get the information that must be true about the result.
Definition at line 300 of file KnownBits.h.
References KnownBits(), One, and Zero.
Referenced by abds(), abdu(), ashr(), combineSetCC(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsBinOp(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromCond(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), lshr(), shl(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
isAllOnes()
bool llvm::KnownBits::isAllOnes () const inline
Returns true if value is all one bits.
Definition at line 79 of file KnownBits.h.
References llvm::APInt::isAllOnes(), and One.
Referenced by isTruncateOf(), matchBinaryShuffle(), and llvm::InstCombinerImpl::visitCallInst().
isConstant()
bool llvm::KnownBits::isConstant () const inline
Returns true if we know the value of all bits.
Definition at line 50 of file KnownBits.h.
References getBitWidth(), One, llvm::APInt::popcount(), and Zero.
Referenced by llvm::adjustKnownBitsForSelectArm(), combineFMulcFCMulc(), combineScalarToVector(), computeKnownBitsFromOperator(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), getConstant(), LowerVectorAllEqual(), and llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode().
isNegative()
bool llvm::KnownBits::isNegative () const inline
Returns true if this value is known to be negative.
Definition at line 94 of file KnownBits.h.
References llvm::APInt::isSignBitSet(), and One.
Referenced by abs(), llvm::SelectionDAG::computeKnownBits(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), computeKnownBitsMul(), llvm::GISelKnownBits::computeNumSignBits(), computeOverflowForSignedAdd(), countMinSignBits(), llvm::TargetLowering::expandAddSubSat(), foldICmpAndXX(), llvm::ConstantRange::fromKnownBits(), getKnownSign(), getSign32(), llvm::SelectionDAG::isKnownNeverZero(), isKnownNonZeroFromOperator(), isNonZeroAdd(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithZero(), and llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode().
isNonNegative()
bool llvm::KnownBits::isNonNegative () const inline
Returns true if this value is known to be non-negative.
Definition at line 97 of file KnownBits.h.
References llvm::APInt::isSignBitSet(), and Zero.
Referenced by abs(), canReplaceGEPIdxWithZero(), computeForSatAddSub(), llvm::SelectionDAG::computeKnownBits(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), computeKnownBitsMul(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::GISelKnownBits::computeNumSignBits(), ComputeNumSignBitsImpl(), computeOverflowForSignedAdd(), llvm::computeOverflowForSignedMul(), llvm::SelectionDAG::computeOverflowForSignedMul(), llvm::computeOverflowForUnsignedMul(), countMinSignBits(), llvm::TargetLowering::expandAddSubSat(), foldICmpAndXX(), llvm::ConstantRange::fromKnownBits(), getKnownSign(), getSign32(), isKnownNonZeroFromOperator(), llvm::isKnownPositive(), isNonZeroAdd(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), simplifyICmpWithBinOpOnLHS(), simplifyICmpWithZero(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), llvm::InstCombinerImpl::simplifyRangeCheck(), and llvm::InstCombinerImpl::visitSDiv().
isNonZero()
bool llvm::KnownBits::isNonZero () const inline
Returns true if this value is known to be non-zero.
Definition at line 100 of file KnownBits.h.
References llvm::APInt::isZero(), and One.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromShiftOperator(), computeKnownBitsMul(), llvm::SelectionDAG::isKnownNeverZero(), isKnownNonZeroFromOperator(), llvm::isKnownPositive(), isNonZeroAdd(), isNonZeroMul(), and llvm::InstCombinerImpl::visitCallInst().
isSignUnknown()
bool llvm::KnownBits::isSignUnknown () const inline
Returns true if we don't know the sign bit.
Definition at line 65 of file KnownBits.h.
References llvm::APInt::isSignBitSet(), One, and Zero.
isStrictlyPositive()
bool llvm::KnownBits::isStrictlyPositive () const inline
Returns true if this value is known to be positive.
Definition at line 103 of file KnownBits.h.
References llvm::APInt::isSignBitSet(), llvm::APInt::isZero(), One, and Zero.
Referenced by llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), and llvm::SelectionDAG::isKnownNeverZero().
isUnknown()
bool llvm::KnownBits::isUnknown () const inline
Returns true if we don't know any bits.
Definition at line 62 of file KnownBits.h.
References llvm::APInt::isZero(), One, and Zero.
Referenced by llvm::FunctionLoweringInfo::AddLiveOutRegInfo(), llvm::adjustKnownBitsForSelectArm(), ashr(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsAddSub(), llvm::SITargetLowering::computeKnownBitsForTargetInstr(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::ConstantRange::fromKnownBits(), isKnownNonEqual(), isKnownNonZeroFromOperator(), isNonZeroShift(), lshr(), llvm::CombinerHelper::matchRedundantAnd(), shl(), and llvm::TargetLowering::SimplifyDemandedBits().
isZero()
bool llvm::KnownBits::isZero () const inline
Returns true if value is all zero.
Definition at line 76 of file KnownBits.h.
References llvm::APInt::isAllOnes(), and Zero.
Referenced by llvm::AMDGPULegalizerInfo::buildMultiply(), combineMOVMSK(), combineX86ShufflesRecursively(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), isZero(), LowerVectorAllEqual(), llvm::SelectionDAG::MaskedVectorIsZero(), matchBinaryShuffle(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), simplifyDivRem(), and simplifyX86immShift().
lshr()
KnownBits KnownBits::lshr (const KnownBits & LHS, const KnownBits & RHS, bool ShAmtNonZero = false, bool Exact = false) static
Compute known bits for lshr(LHS, RHS).
NOTE: RHS (shift amount) bitwidth doesn't need to be the same as LHS.
Definition at line 370 of file KnownBits.cpp.
References llvm::BitWidth, getMaxShiftAmount(), llvm::APInt::getMaxValue(), hasConflict(), intersectWith(), isUnknown(), LHS, llvm::APInt::lshrInPlace(), One, llvm::APInt::setAllBits(), setAllZero(), llvm::APInt::setHighBits(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), and extractBits().
makeConstant()
static KnownBits llvm::KnownBits::makeConstant (const APInt & C) inline static
Create known bits from a known constant.
Definition at line 290 of file KnownBits.h.
References llvm::CallingConv::C, and KnownBits().
Referenced by abs(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromCmp(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), and llvm::ConstantRange::toKnownBits().
makeGE()
KnownBits KnownBits::makeGE (const APInt & Val) const
Return KnownBits based on this, but updated given that the underlying value is known to be greater than or equal to Val.
Definition at line 166 of file KnownBits.cpp.
References llvm::APInt::clearLowBits(), llvm::countl_one(), getBitWidth(), KnownBits(), N, One, and Zero.
makeNegative()
void llvm::KnownBits::makeNegative () inline
Make this value negative.
Definition at line 108 of file KnownBits.h.
References One, and llvm::APInt::setSignBit().
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromCmp(), computeKnownBitsFromOperator(), computeKnownBitsMul(), and shl().
makeNonNegative()
void llvm::KnownBits::makeNonNegative () inline
Make this value non-negative.
Definition at line 113 of file KnownBits.h.
References llvm::APInt::setSignBit(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromCmp(), computeKnownBitsFromOperator(), computeKnownBitsMul(), shl(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
mul()
KnownBits KnownBits::mul (const KnownBits & LHS, const KnownBits & RHS, bool NoUndefSelfMultiply = false) static
Compute known bits resulting from multiplying LHS and RHS.
Definition at line 797 of file KnownBits.cpp.
References assert(), llvm::BitWidth, llvm::APInt::countl_zero(), llvm::countr_one(), llvm::APInt::getLoBits(), llvm::APInt::getMaxValue(), One, llvm::APInt::setBit(), llvm::APInt::setHighBits(), llvm::APInt::umul_ov(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsForPMADDUBSW(), computeKnownBitsForPMADDWD(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), computeKnownBitsMul(), mulhs(), mulhu(), and llvm::TargetLowering::SimplifyDemandedBits().
mulhs()
KnownBits KnownBits::mulhs (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits from sign-extended multiply-hi.
Definition at line 894 of file KnownBits.cpp.
References assert(), llvm::BitWidth, extractBits(), mul(), and sext().
Referenced by llvm::SelectionDAG::computeKnownBits(), and computeKnownBitsFromOperator().
mulhu()
KnownBits KnownBits::mulhu (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits from zero-extended multiply-hi.
Definition at line 902 of file KnownBits.cpp.
References assert(), llvm::BitWidth, extractBits(), mul(), and zext().
Referenced by llvm::SelectionDAG::computeKnownBits(), and computeKnownBitsFromOperator().
ne()
std::optional< bool > KnownBits::ne (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_NE result.
Definition at line 496 of file KnownBits.cpp.
References eq().
Referenced by llvm::SelectionDAG::isKnownNeverZero(), and llvm::CombinerHelper::matchICmpToTrueFalseKnownBits().
operator!=()
bool llvm::KnownBits::operator!= (const KnownBits & Other) const inline
Definition at line 476 of file KnownBits.h.
References llvm::Other.
operator&=()
KnownBits & KnownBits::operator&= (const KnownBits & RHS)
Update known bits based on ANDing with RHS.
Definition at line 1084 of file KnownBits.cpp.
References One, and Zero.
operator==()
bool llvm::KnownBits::operator== (const KnownBits & Other) const inline
Definition at line 472 of file KnownBits.h.
References One, llvm::Other, and Zero.
operator^=()
KnownBits & KnownBits::operator^= (const KnownBits & RHS)
Update known bits based on XORing with RHS.
Definition at line 1100 of file KnownBits.cpp.
References One, and Zero.
operator|=()
KnownBits & KnownBits::operator|= (const KnownBits & RHS)
Update known bits based on ORing with RHS.
Definition at line 1092 of file KnownBits.cpp.
References One, and Zero.
print()
void KnownBits::print (raw_ostream & OS) const
Definition at line 1130 of file KnownBits.cpp.
References llvm::BitWidth, getBitWidth(), I, N, One, OS, and Zero.
Referenced by dump(), and llvm::operator<<().
resetAll()
void llvm::KnownBits::resetAll () inline
Resets the known state of all bits.
Definition at line 70 of file KnownBits.h.
References llvm::APInt::clearAllBits(), One, and Zero.
Referenced by computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::TargetLowering::computeKnownBitsForTargetInstr(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::PPCTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::SITargetLowering::computeKnownBitsForTargetNode(), llvm::SparcTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::TargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::computeKnownBitsFromContext(), computeKnownBitsFromOperator(), llvm::InstCombinerImpl::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifyDemandedBits().
reverseBits()
KnownBits llvm::KnownBits::reverseBits () const inline
Definition at line 460 of file KnownBits.h.
References KnownBits(), One, llvm::APInt::reverseBits(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), and llvm::GISelKnownBits::computeKnownBitsImpl().
sadd_sat()
KnownBits KnownBits::sadd_sat (const KnownBits & LHS, const KnownBits & RHS) static
Compute knownbits resulting from llvm.sadd.sat(LHS, RHS)
Definition at line 753 of file KnownBits.cpp.
References computeForSatAddSub().
Referenced by computeKnownBitsForPMADDUBSW(), and computeKnownBitsFromOperator().
sdiv()
KnownBits KnownBits::sdiv (const KnownBits & LHS, const KnownBits & RHS, bool Exact = false) static
Compute known bits for sdiv(LHS, RHS).
Definition at line 946 of file KnownBits.cpp.
References llvm::BitWidth, divComputeLowBit(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::APInt::isAllOnes(), llvm::APInt::isMinSignedValue(), llvm::APInt::isZero(), One, llvm::APInt::sdiv(), setAllZero(), llvm::APInt::setHighBits(), udiv(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), and computeKnownBitsFromOperator().
setAllOnes()
void llvm::KnownBits::setAllOnes () inline
Make all bits known to be one and discard any previous information.
Definition at line 88 of file KnownBits.h.
References llvm::APInt::clearAllBits(), One, llvm::APInt::setAllBits(), and Zero.
Referenced by llvm::X86TargetLowering::computeKnownBitsForTargetNode(), and llvm::computeKnownBitsFromContext().
setAllZero()
void llvm::KnownBits::setAllZero () inline
Make all bits known to be zero and discard any previous information.
Definition at line 82 of file KnownBits.h.
References llvm::APInt::clearAllBits(), One, llvm::APInt::setAllBits(), and Zero.
Referenced by ashr(), computeForAddSub(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromCmp(), llvm::computeKnownBitsFromContext(), divComputeLowBit(), lshr(), sdiv(), shl(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), and udiv().
sext()
KnownBits llvm::KnownBits::sext (unsigned BitWidth) const inline
Return known bits for a sign extension of the value we're tracking.
Definition at line 169 of file KnownBits.h.
References llvm::BitWidth, KnownBits(), One, llvm::APInt::sext(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsForPMADDUBSW(), computeKnownBitsForPMADDWD(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), mulhs(), sextOrTrunc(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
sextInReg()
KnownBits KnownBits::sextInReg (unsigned SrcBitWidth) const
Return known bits for a in-register sign extension of the value we're tracking.
Definition at line 149 of file KnownBits.cpp.
References assert(), llvm::BitWidth, getBitWidth(), One, and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), and llvm::GISelKnownBits::computeKnownBitsImpl().
sextOrTrunc()
KnownBits llvm::KnownBits::sextOrTrunc (unsigned BitWidth) const inline
Return known bits for a sign extension or truncation of the value we're tracking.
Definition at line 195 of file KnownBits.h.
References llvm::BitWidth, getBitWidth(), sext(), and trunc().
Referenced by computeKnownBitsFromOperator().
sge()
std::optional< bool > KnownBits::sge (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_SGE result.
Definition at line 536 of file KnownBits.cpp.
References sgt().
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), llvm::TargetLowering::SimplifyDemandedBits(), and sle().
sgt()
std::optional< bool > KnownBits::sgt (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_SGT result.
Definition at line 526 of file KnownBits.cpp.
Referenced by llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), sge(), llvm::TargetLowering::SimplifyDemandedBits(), and slt().
shl()
KnownBits KnownBits::shl (const KnownBits & LHS, const KnownBits & RHS, bool NUW = false, bool NSW = false, bool ShAmtNonZero = false) static
Compute known bits for shl(LHS, RHS).
NOTE: RHS (shift amount) bitwidth doesn't need to be the same as LHS.
Definition at line 285 of file KnownBits.cpp.
References llvm::BitWidth, getMaxShiftAmount(), llvm::APInt::getMaxValue(), hasConflict(), intersectWith(), llvm::isPowerOf2_32(), isUnknown(), LHS, makeNegative(), makeNonNegative(), One, llvm::APInt::setAllBits(), setAllZero(), llvm::APInt::setLowBits(), llvm::APInt::setSignBit(), llvm::APInt::ushl_ov(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), and simplifyShift().
sle()
std::optional< bool > KnownBits::sle (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_SLE result.
Definition at line 546 of file KnownBits.cpp.
References sge().
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), and llvm::TargetLowering::SimplifyDemandedBits().
slt()
std::optional< bool > KnownBits::slt (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_SLT result.
Definition at line 542 of file KnownBits.cpp.
References sgt().
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), and llvm::TargetLowering::SimplifyDemandedBits().
smax()
KnownBits KnownBits::smax (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for smax(LHS, RHS).
Definition at line 202 of file KnownBits.cpp.
References KnownBits(), One, llvm::APInt::setBitVal(), umax(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), and llvm::TargetLowering::SimplifyDemandedBits().
smin()
KnownBits KnownBits::smin (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for smin(LHS, RHS).
Definition at line 215 of file KnownBits.cpp.
References KnownBits(), One, llvm::APInt::setBitVal(), umax(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), and llvm::TargetLowering::SimplifyDemandedBits().
srem()
KnownBits KnownBits::srem (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for srem(LHS, RHS).
Definition at line 1059 of file KnownBits.cpp.
References llvm::APInt::intersects(), llvm::APInt::isSubsetOf(), One, llvm::APInt::setHighBits(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), and computeKnownBitsFromOperator().
ssub_sat()
KnownBits KnownBits::ssub_sat (const KnownBits & LHS, const KnownBits & RHS) static
Compute knownbits resulting from llvm.ssub.sat(LHS, RHS)
Definition at line 756 of file KnownBits.cpp.
References computeForSatAddSub().
Referenced by computeKnownBitsFromOperator().
trunc()
KnownBits llvm::KnownBits::trunc (unsigned BitWidth) const inline
Return known bits for a truncation of the value we're tracking.
Definition at line 150 of file KnownBits.h.
References llvm::BitWidth, KnownBits(), One, llvm::APInt::trunc(), and Zero.
Referenced by anyextOrTrunc(), llvm::SelectionDAG::computeKnownBits(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), sextOrTrunc(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), and zextOrTrunc().
uadd_sat()
KnownBits KnownBits::uadd_sat (const KnownBits & LHS, const KnownBits & RHS) static
Compute knownbits resulting from llvm.uadd.sat(LHS, RHS)
Definition at line 759 of file KnownBits.cpp.
References computeForSatAddSub().
Referenced by computeKnownBitsFromOperator().
udiv()
KnownBits KnownBits::udiv (const KnownBits & LHS, const KnownBits & RHS, bool Exact = false) static
Compute known bits for udiv(LHS, RHS).
Definition at line 1002 of file KnownBits.cpp.
References llvm::BitWidth, llvm::APInt::countLeadingZeros(), divComputeLowBit(), llvm::APInt::getMaxValue(), llvm::APInt::getMinValue(), llvm::APInt::isZero(), setAllZero(), llvm::APInt::setHighBits(), llvm::APInt::udiv(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), sdiv(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
uge()
std::optional< bool > KnownBits::uge (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_UGE result.
Definition at line 512 of file KnownBits.cpp.
References ugt().
Referenced by isKnownNonZeroFromOperator(), llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), llvm::TargetLowering::SimplifyDemandedBits(), and ule().
ugt()
std::optional< bool > KnownBits::ugt (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_UGT result.
Definition at line 502 of file KnownBits.cpp.
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), llvm::TargetLowering::SimplifyDemandedBits(), uge(), and ult().
ule()
std::optional< bool > KnownBits::ule (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_ULE result.
Definition at line 522 of file KnownBits.cpp.
References uge().
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), and llvm::TargetLowering::SimplifyDemandedBits().
ult()
std::optional< bool > KnownBits::ult (const KnownBits & LHS, const KnownBits & RHS) static
Determine if these known bits always give the same ICMP_ULT result.
Definition at line 518 of file KnownBits.cpp.
References ugt().
Referenced by llvm::CombinerHelper::matchICmpToTrueFalseKnownBits(), and llvm::TargetLowering::SimplifyDemandedBits().
umax()
KnownBits KnownBits::umax (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for umax(LHS, RHS).
Definition at line 178 of file KnownBits.cpp.
References LHS, and RHS.
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::TargetLowering::SimplifyDemandedBits(), smax(), smin(), and umin().
umin()
KnownBits KnownBits::umin (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for umin(LHS, RHS).
Definition at line 196 of file KnownBits.cpp.
References KnownBits(), and umax().
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), and llvm::TargetLowering::SimplifyDemandedBits().
unionWith()
KnownBits llvm::KnownBits::unionWith (const KnownBits & RHS) const inline
Returns KnownBits information that is known to be true for either this or RHS or both.
This can be used to combine different sources of information about the known bits of a single value, e.g. information about the low bits and the high bits of the result of a multiplication.
Definition at line 310 of file KnownBits.h.
References KnownBits(), One, and Zero.
Referenced by llvm::adjustKnownBitsForSelectArm(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromCmp(), computeKnownBitsFromCond(), computeKnownBitsFromICmpCond(), computeKnownBitsFromOperator(), and llvm::TargetLowering::SimplifyDemandedBits().
urem()
KnownBits KnownBits::urem (const KnownBits & LHS, const KnownBits & RHS) static
Compute known bits for urem(LHS, RHS).
Definition at line 1042 of file KnownBits.cpp.
References llvm::APInt::setHighBits(), and Zero.
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), and computeKnownBitsFromOperator().
usub_sat()
KnownBits KnownBits::usub_sat (const KnownBits & LHS, const KnownBits & RHS) static
Compute knownbits resulting from llvm.usub.sat(LHS, RHS)
Definition at line 762 of file KnownBits.cpp.
References computeForSatAddSub().
Referenced by llvm::SelectionDAG::computeKnownBits(), and computeKnownBitsFromOperator().
zext()
KnownBits llvm::KnownBits::zext (unsigned BitWidth) const inline
Return known bits for a zero extension of the value we're tracking.
Definition at line 161 of file KnownBits.h.
References llvm::BitWidth, getBitWidth(), KnownBits(), One, llvm::APInt::setBitsFrom(), Zero, and llvm::APInt::zext().
Referenced by llvm::SelectionDAG::computeKnownBits(), computeKnownBitsForPMADDUBSW(), computeKnownBitsForPSADBW(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::GISelKnownBits::computeKnownBitsImpl(), mulhu(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), and zextOrTrunc().
zextOrTrunc()
KnownBits llvm::KnownBits::zextOrTrunc (unsigned BitWidth) const inline
Return known bits for a zero extension or truncation of the value we're tracking.
Definition at line 185 of file KnownBits.h.
References llvm::BitWidth, getBitWidth(), trunc(), and zext().
Referenced by llvm::SelectionDAG::computeKnownBits(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromOperator(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), and llvm::InstCombinerImpl::SimplifyDemandedUseBits().
Member Data Documentation
One
APInt llvm::KnownBits::One
Definition at line 25 of file KnownBits.h.
Referenced by abs(), llvm::FunctionLoweringInfo::AddLiveOutRegInfo(), anyext(), ashr(), llvm::ConstantRange::binaryXor(), blsi(), blsmsk(), byteSwap(), llvm::SelectionDAGISel::CheckOrMask(), combineSetCC(), computeForAddCarry(), computeForAddCarry(), computeForAddSub(), computeForSatAddSub(), computeForSubBorrow(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::SITargetLowering::computeKnownBitsForTargetInstr(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromCmp(), computeKnownBitsFromOperator(), llvm::computeKnownBitsFromRangeMetadata(), llvm::GISelKnownBits::computeKnownBitsImpl(), llvm::GISelKnownBits::computeNumSignBits(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), concat(), countMaxLeadingZeros(), countMaxTrailingZeros(), countMinLeadingOnes(), countMinPopulation(), countMinTrailingOnes(), llvm::DemandedBits::determineLiveOperandBitsSub(), divComputeLowBit(), dumpResult(), eliminateDeadSwitchCases(), extractBits(), foldCtpopPow2Test(), foldCttzCtlz(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::InstCombinerImpl::foldICmpWithZero(), getBitWidth(), getConstant(), getKnownBitsFromAndXorOr(), llvm::GISelKnownBits::getKnownOnes(), getMinValue(), getSignedMaxValue(), getSignedMinValue(), hasConflict(), insertBits(), intersectWith(), isAllOnes(), isConstant(), llvm::SelectionDAG::isKnownNeverZero(), isKnownNonEqual(), isKnownNonZeroFromOperator(), isKnownToBeAPowerOfTwo(), isNegative(), isNonZero(), isNonZeroAdd(), isNonZeroMul(), isNonZeroShift(), isSignUnknown(), isStrictlyPositive(), isUnknown(), lshr(), makeGE(), makeNegative(), matchBinaryShuffle(), llvm::CombinerHelper::matchRedundantAnd(), llvm::CombinerHelper::matchRedundantOr(), mul(), operator&=(), operator==(), operator^=(), operator|=(), print(), resetAll(), reverseBits(), sdiv(), setAllOnes(), setAllZero(), sext(), sextInReg(), shl(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), simplifyRightShift(), simplifyShift(), llvm::InstCombinerImpl::simplifyShrShlDemandedBits(), smax(), smin(), srem(), llvm::ConstantRange::toKnownBits(), trunc(), unionWith(), llvm::InstCombinerImpl::visitOr(), and zext().
Zero
APInt llvm::KnownBits::Zero
Definition at line 24 of file KnownBits.h.
Referenced by abs(), llvm::FunctionLoweringInfo::AddLiveOutRegInfo(), adjustForRedundantAnd(), anyext(), ashr(), llvm::ConstantRange::binaryXor(), blsi(), blsmsk(), byteSwap(), combineSetCC(), computeForAddCarry(), computeForAddCarry(), computeForAddSub(), computeForSatAddSub(), computeForSubBorrow(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::GISelKnownBits::computeKnownBitsForAlignment(), llvm::SITargetLowering::computeKnownBitsForFrameIndex(), llvm::TargetLowering::computeKnownBitsForFrameIndex(), llvm::SITargetLowering::computeKnownBitsForTargetInstr(), llvm::AArch64TargetLowering::computeKnownBitsForTargetNode(), llvm::AMDGPUTargetLowering::computeKnownBitsForTargetNode(), llvm::ARMTargetLowering::computeKnownBitsForTargetNode(), llvm::LanaiTargetLowering::computeKnownBitsForTargetNode(), llvm::PPCTargetLowering::computeKnownBitsForTargetNode(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), llvm::SITargetLowering::computeKnownBitsForTargetNode(), llvm::SystemZTargetLowering::computeKnownBitsForTargetNode(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromCmp(), llvm::computeKnownBitsFromContext(), computeKnownBitsFromOperator(), llvm::computeKnownBitsFromRangeMetadata(), llvm::GISelKnownBits::computeKnownBitsImpl(), computeKnownFPClass(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::GISelKnownBits::computeNumSignBits(), ComputeNumSignBitsImpl(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), concat(), countMaxLeadingOnes(), countMaxPopulation(), countMaxTrailingOnes(), countMinLeadingZeros(), countMinTrailingZeros(), llvm::DemandedBits::determineLiveOperandBitsSub(), divComputeLowBit(), dumpResult(), eliminateDeadSwitchCases(), extractBits(), llvm::InstCombinerImpl::foldAddWithConstant(), foldCtpop(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), getBitWidth(), getKnownBitsFromAndXorOr(), llvm::GISelKnownBits::getKnownZeroes(), getSignedMinValue(), hasConflict(), insertBits(), intersectWith(), isConstant(), isKnownNonEqual(), isKnownToBeAPowerOfTwo(), isNonNegative(), isNonZeroShift(), isSignUnknown(), isStrictlyPositive(), isTruncateOf(), isUnknown(), isZero(), knownBitsForWorkitemID(), LowerMUL(), lshr(), makeGE(), makeNonNegative(), llvm::MaskedValueIsZero(), matchBinaryShuffle(), llvm::CombinerHelper::matchRedundantAnd(), llvm::CombinerHelper::matchRedundantOr(), mul(), operator&=(), operator==(), operator^=(), operator|=(), performANDCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), llvm::ARMTargetLowering::PerformCMOVToBFICombine(), performORCombine(), print(), provablyDisjointOr(), resetAll(), reverseBits(), sdiv(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::PPCTargetLowering::SelectAddressRegImm34(), llvm::PPCTargetLowering::SelectAddressRegReg(), llvm::LoongArchDAGToDAGISel::selectShiftMask(), llvm::RISCVDAGToDAGISel::selectShiftMask(), setAllOnes(), setAllZero(), sext(), sextInReg(), shl(), llvm::simplifyBinaryIntrinsic(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::X86TargetLowering::SimplifyDemandedBitsForTargetNode(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::X86TTIImpl::simplifyDemandedUseBitsIntrinsic(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::InstCombinerImpl::SimplifyMultipleUseDemandedBits(), llvm::TargetLowering::SimplifyMultipleUseDemandedBits(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), simplifyShift(), llvm::InstCombinerImpl::simplifyShrShlDemandedBits(), simplifySubInst(), smax(), smin(), srem(), llvm::ConstantRange::toKnownBits(), trunc(), tryBitfieldInsertOpFromOr(), tryBitfieldInsertOpFromOrAndImm(), udiv(), unionWith(), urem(), llvm::InstCombinerImpl::visitSub(), and zext().
The documentation for this struct was generated from the following files:
include/llvm/Support/KnownBits.h
lib/Support/KnownBits.cpp