LLVM: llvm::TemporalProfTraceTy Struct Reference
llvm::TemporalProfTraceTy Struct Reference
An ordered list of functions identified by their NameRef found in INSTR_PROF_DATA.
#include "llvm/ProfileData/InstrProf.h"
Public Member Functions
TemporalProfTraceTy (std::initializer_list< uint64_t > Trace={}, uint64_t Weight=1)
Static Public Member Functions
static void createBPFunctionNodes (ArrayRef< TemporalProfTraceTy > Traces, std::vector< BPFunctionNode > &Nodes, bool RemoveOutlierUNs=true)
Use a set of temporal profile traces to create a list of balanced partitioning function nodes used by BalancedPartitioning to generate a function order that reduces page faults during startup.
Public Attributes
std::vector< uint64_t > FunctionNameRefs
uint64_t Weight
Detailed Description
An ordered list of functions identified by their NameRef found in INSTR_PROF_DATA.
Definition at line 375 of file InstrProf.h.
Constructor & Destructor Documentation
TemporalProfTraceTy()
llvm::TemporalProfTraceTy::TemporalProfTraceTy (std::initializer_list< uint64_t > Trace = {}, uint64_t Weight = 1) inline
Definition at line 378 of file InstrProf.h.
Member Function Documentation
createBPFunctionNodes()
void llvm::TemporalProfTraceTy::createBPFunctionNodes (ArrayRef< TemporalProfTraceTy > Traces, std::vector< BPFunctionNode > & Nodes, bool RemoveOutlierUNs = true) static
Use a set of temporal profile traces to create a list of balanced partitioning function nodes used by BalancedPartitioning to generate a function order that reduces page faults during startup.
Definition at line 1019 of file InstrProf.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::erase_if(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), llvm::Trace::size(), llvm::sort(), Timestamp, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Member Data Documentation
FunctionNameRefs
std::vector<uint64_t> llvm::TemporalProfTraceTy::FunctionNameRefs
Definition at line 376 of file InstrProf.h.
Weight
uint64_t llvm::TemporalProfTraceTy::Weight
Definition at line 377 of file InstrProf.h.
The documentation for this struct was generated from the following files:
include/llvm/ProfileData/InstrProf.h
lib/ProfileData/InstrProf.cpp