LLVM: llvm::MDNodeKeyImpl< DISubrange > Struct Reference
llvm::MDNodeKeyImpl< DISubrange > Struct Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (Metadata *CountNode, Metadata *LowerBound, Metadata *UpperBound, Metadata *Stride)
MDNodeKeyImpl (const DISubrange *N)
bool isKeyOf (const DISubrange *RHS) const
unsigned getHashValue () const
Public Attributes
Metadata * CountNode
Metadata * LowerBound
Metadata * UpperBound
Metadata * Stride
Detailed Description
Definition at line 364 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DISubrange >::MDNodeKeyImpl (Metadata * CountNode, Metadata * LowerBound, Metadata * UpperBound, Metadata * Stride) inline
Definition at line 370 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DISubrange >::MDNodeKeyImpl (const DISubrange * N) inline
Definition at line 374 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DISubrange >::getHashValue () const inline
Definition at line 400 of file LLVMContextImpl.h.
References llvm::cast(), llvm::dyn_cast(), and llvm::hash_combine().
isKeyOf()
bool llvm::MDNodeKeyImpl< DISubrange >::isKeyOf (const DISubrange * RHS) const inline
Definition at line 378 of file LLVMContextImpl.h.
References llvm::cast(), llvm::dyn_cast_or_null(), llvm::ConstantInt::getSExtValue(), and llvm::ConstantAsMetadata::getValue().
Member Data Documentation
CountNode
Metadata* llvm::MDNodeKeyImpl< DISubrange >::CountNode
Definition at line 365 of file LLVMContextImpl.h.
LowerBound
Metadata* llvm::MDNodeKeyImpl< DISubrange >::LowerBound
Definition at line 366 of file LLVMContextImpl.h.
Stride
Metadata* llvm::MDNodeKeyImpl< DISubrange >::Stride
Definition at line 368 of file LLVMContextImpl.h.
UpperBound
Metadata* llvm::MDNodeKeyImpl< DISubrange >::UpperBound
Definition at line 367 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h