LLVM: llvm::sampleprof::ProfileConverter::FrameNode Struct Reference
llvm::sampleprof::ProfileConverter::FrameNode Struct Reference
#include "llvm/ProfileData/SampleProf.h"
Public Member Functions
FrameNode (FunctionId FName=FunctionId(), FunctionSamples *FSamples=nullptr, LineLocation CallLoc={0, 0})
FrameNode * getOrCreateChildFrame (const LineLocation &CallSite, FunctionId CalleeName)
Public Attributes
std::map< uint64_t, FrameNode > AllChildFrames
FunctionId FuncName
FunctionSamples * FuncSamples
LineLocation CallSiteLoc
Detailed Description
Definition at line 1405 of file SampleProf.h.
Constructor & Destructor Documentation
FrameNode()
llvm::sampleprof::ProfileConverter::FrameNode::FrameNode (FunctionId FName = FunctionId(), FunctionSamples * FSamples = nullptr, LineLocation CallLoc = {0, 0}) inline
Definition at line 1406 of file SampleProf.h.
Referenced by getOrCreateChildFrame().
Member Function Documentation
getOrCreateChildFrame()
ProfileConverter::FrameNode * ProfileConverter::FrameNode::getOrCreateChildFrame (const LineLocation & CallSite, FunctionId CalleeName)
Definition at line 430 of file SampleProf.cpp.
References AllChildFrames, assert(), FrameNode(), and llvm::sampleprof::FunctionSamples::getCallSiteHash().
Member Data Documentation
AllChildFrames
std::map<uint64_t, FrameNode> llvm::sampleprof::ProfileConverter::FrameNode::AllChildFrames
Definition at line 1412 of file SampleProf.h.
Referenced by getOrCreateChildFrame().
CallSiteLoc
LineLocation llvm::sampleprof::ProfileConverter::FrameNode::CallSiteLoc
Definition at line 1418 of file SampleProf.h.
FuncName
FunctionId llvm::sampleprof::ProfileConverter::FrameNode::FuncName
Definition at line 1414 of file SampleProf.h.
FuncSamples
FunctionSamples* llvm::sampleprof::ProfileConverter::FrameNode::FuncSamples
Definition at line 1416 of file SampleProf.h.
The documentation for this struct was generated from the following files:
include/llvm/ProfileData/SampleProf.h
lib/ProfileData/SampleProf.cpp