LLVM: llvm::RTLIB::RuntimeLibcallsInfo Struct Reference
llvm::RTLIB::RuntimeLibcallsInfo Struct Reference
A simple container for information about the supported runtime calls.
#include "llvm/IR/RuntimeLibcalls.h"
Public Member Functions
RuntimeLibcallsInfo (const Triple &TT)
void setLibcallName (RTLIB::Libcall Call, const char *Name)
Rename the default libcall routine name for the specified libcall.
void setLibcallName (ArrayRef< RTLIB::Libcall > Calls, const char *Name)
const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
void setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC)
Set the CallingConv that should be used for the specified libcall.
CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
Get the CallingConv that should be used for the specified libcall.
iterator_range< const char ** > getLibcallNames ()
Detailed Description
A simple container for information about the supported runtime calls.
Definition at line 40 of file RuntimeLibcalls.h.
Constructor & Destructor Documentation
RuntimeLibcallsInfo()
llvm::RTLIB::RuntimeLibcallsInfo::RuntimeLibcallsInfo (const Triple & TT) inline explicit
Definition at line 41 of file RuntimeLibcalls.h.
Member Function Documentation
getLibcallCallingConv()
CallingConv::ID llvm::RTLIB::RuntimeLibcallsInfo::getLibcallCallingConv (RTLIB::Libcall Call) const inline
Get the CallingConv that should be used for the specified libcall.
Definition at line 66 of file RuntimeLibcalls.h.
References Call.
Referenced by llvm::TargetLoweringBase::getLibcallCallingConv().
getLibcallName()
const char * llvm::RTLIB::RuntimeLibcallsInfo::getLibcallName (RTLIB::Libcall Call) const inline
Get the libcall routine name for the specified libcall.
Definition at line 56 of file RuntimeLibcalls.h.
References Call.
Referenced by llvm::TargetLoweringBase::getLibcallName().
getLibcallNames()
iterator_range< const char ** > llvm::RTLIB::RuntimeLibcallsInfo::getLibcallNames () inline
Definition at line 70 of file RuntimeLibcalls.h.
References llvm::make_range().
Referenced by llvm::lto::LTO::getRuntimeLibcallSymbols().
setLibcallCallingConv()
void llvm::RTLIB::RuntimeLibcallsInfo::setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC) inline
Set the CallingConv that should be used for the specified libcall.
Definition at line 61 of file RuntimeLibcalls.h.
References Call, and CC.
Referenced by llvm::TargetLoweringBase::setLibcallCallingConv().
setLibcallName() [1/2]
void llvm::RTLIB::RuntimeLibcallsInfo::setLibcallName (ArrayRef< RTLIB::Libcall > Calls, const char * Name) inline
Definition at line 50 of file RuntimeLibcalls.h.
References Call, Name, and setLibcallName().
setLibcallName() [2/2]
void llvm::RTLIB::RuntimeLibcallsInfo::setLibcallName (RTLIB::Libcall Call, const char * Name) inline
Rename the default libcall routine name for the specified libcall.
Definition at line 46 of file RuntimeLibcalls.h.
References Call, and Name.
Referenced by setLibcallName(), llvm::TargetLoweringBase::setLibcallName(), and llvm::TargetLoweringBase::setLibcallName().
The documentation for this struct was generated from the following files:
include/llvm/IR/RuntimeLibcalls.h
lib/IR/RuntimeLibcalls.cpp