LLVM: llvm::AnalysisGetter Struct Reference
llvm::AnalysisGetter Struct Reference
Wrapper for FunctionAnalysisManager.
#include "llvm/Transforms/IPO/Attributor.h"
Public Member Functions
template<typename Analysis >
Analysis::Result * getAnalysis (const Function &F, bool RequestCachedOnly=false)
void invalidateAnalyses ()
Invalidates the analyses. Valid only when using the new pass manager.
AnalysisGetter (FunctionAnalysisManager &FAM, bool CachedOnly=false)
AnalysisGetter (Pass *P, bool CachedOnly=false)
AnalysisGetter ()=default
Static Public Member Functions
template<typename Analysis >
constexpr bool HasLegacyWrapper
Static Public Attributes
template<typename , typename = void>
static constexpr bool HasLegacyWrapper = false
Detailed Description
Wrapper for FunctionAnalysisManager.
Definition at line 1122 of file Attributor.h.
Constructor & Destructor Documentation
AnalysisGetter() [1/3]
llvm::AnalysisGetter::AnalysisGetter (FunctionAnalysisManager & FAM, bool CachedOnly = false) inline
Definition at line 1167 of file Attributor.h.
References FAM.
AnalysisGetter() [2/3]
llvm::AnalysisGetter::AnalysisGetter (Pass * P, bool CachedOnly = false) inline
Definition at line 1169 of file Attributor.h.
AnalysisGetter() [3/3]
llvm::AnalysisGetter::AnalysisGetter () default
Member Function Documentation
getAnalysis()
template<typename Analysis > Analysis::Result * llvm::AnalysisGetter::getAnalysis (const Function & F, bool RequestCachedOnly = false) inline
Definition at line 1138 of file Attributor.h.
References Analysis, F, llvm::Pass::getAnalysis(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), HasLegacyWrapper, and P.
Referenced by llvm::InformationCache::getAnalysisResultForFunction(), llvm::InformationCache::getTargetLibraryInfoForFunction(), and llvm::InformationCache::InformationCache().
HasLegacyWrapper()
template<typename Analysis > bool llvm::AnalysisGetter::HasLegacyWrapper static constexpr
Definition at line 1183 of file Attributor.h.
invalidateAnalyses()
void llvm::AnalysisGetter::invalidateAnalyses () inline
Invalidates the analyses. Valid only when using the new pass manager.
Definition at line 1162 of file Attributor.h.
References assert(), and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::clear().
Referenced by llvm::InformationCache::invalidateAnalyses().
Member Data Documentation
HasLegacyWrapper
template<typename , typename = void> bool llvm::AnalysisGetter::HasLegacyWrapper = false static constexpr
Definition at line 1135 of file Attributor.h.
Referenced by getAnalysis().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h