LLVM: llvm::PatternMatch::ElementWiseBitCast_match< Op_t > Struct Template Reference
llvm::PatternMatch::ElementWiseBitCast_match< Op_t > Struct Template Reference
#include "llvm/IR/PatternMatch.h"
Public Member Functions
ElementWiseBitCast_match (const Op_t &OpMatch)
template<typename OpTy >
bool match (OpTy *V)
Public Attributes
Op_t Op
Detailed Description
template<typename Op_t>
struct llvm::PatternMatch::ElementWiseBitCast_match< Op_t >
Definition at line 1963 of file PatternMatch.h.
Constructor & Destructor Documentation
ElementWiseBitCast_match()
template<typename Op_t > llvm::PatternMatch::ElementWiseBitCast_match< Op_t >::ElementWiseBitCast_match (const Op_t & OpMatch) inline
Definition at line 1966 of file PatternMatch.h.
Member Function Documentation
match()
template<typename Op_t > template<typename OpTy > bool llvm::PatternMatch::ElementWiseBitCast_match< Op_t >::match (OpTy * V) inline
Definition at line 1968 of file PatternMatch.h.
References llvm::cast(), llvm::dyn_cast(), llvm::VectorType::getElementCount(), and I.
Member Data Documentation
Op
template<typename Op_t > Op_t llvm::PatternMatch::ElementWiseBitCast_match< Op_t >::Op
Definition at line 1964 of file PatternMatch.h.
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h