LLVM: llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4 Struct Reference
llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4 Struct Reference
Public Member Functions
NormalizedTBD_V4 (IO &IO)
NormalizedTBD_V4 (IO &IO, const InterfaceFile *&File)
const InterfaceFile * denormalize (IO &IO)
Public Attributes
unsigned TBDVersion
std::vector< UUIDv4 > UUIDs
TargetList Targets
StringRef InstallName
PackedVersion CurrentVersion
PackedVersion CompatibilityVersion
SwiftVersion SwiftABIVersion {0}
std::vector< MetadataSection > AllowableClients
std::vector< MetadataSection > ReexportedLibraries
TBDFlags Flags {TBDFlags::None}
std::vector< UmbrellaSection > ParentUmbrellas
SectionList Exports
SectionList Reexports
SectionList Undefineds
Detailed Description
Definition at line 767 of file TextStub.cpp.
Constructor & Destructor Documentation
NormalizedTBD_V4() [1/2]
llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::NormalizedTBD_V4 (IO & IO) inline explicit
Definition at line 768 of file TextStub.cpp.
NormalizedTBD_V4() [2/2]
llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::NormalizedTBD_V4 (IO & IO, const InterfaceFile *& File) inline
Definition at line 769 of file TextStub.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), FlatNamespace, llvm::MachO::Symbol::getKind(), llvm::MachO::Symbol::getName(), llvm::SmallVectorImpl< T >::insert(), llvm::MachO::Symbol::isThreadLocalValue(), llvm::MachO::Symbol::isWeakDefined(), IT, None, NotApplicationExtensionSafe, OSLibNotForSharedCache, llvm::sort(), and llvm::MachO::Symbol::targets().
Member Function Documentation
denormalize()
const InterfaceFile * llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::denormalize (IO & IO) inline
Definition at line 862 of file TextStub.cpp.
References assert(), FlatNamespace, llvm::Lib, NotApplicationExtensionSafe, and OSLibNotForSharedCache.
Member Data Documentation
AllowableClients
std::vector<MetadataSection> llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::AllowableClients
Definition at line 949 of file TextStub.cpp.
CompatibilityVersion
PackedVersion llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::CompatibilityVersion
Definition at line 947 of file TextStub.cpp.
CurrentVersion
PackedVersion llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::CurrentVersion
Definition at line 946 of file TextStub.cpp.
Exports
SectionList llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::Exports
Definition at line 953 of file TextStub.cpp.
Flags
TBDFlags llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::Flags {TBDFlags::None}
Definition at line 951 of file TextStub.cpp.
InstallName
StringRef llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::InstallName
Definition at line 945 of file TextStub.cpp.
ParentUmbrellas
std::vector<UmbrellaSection> llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::ParentUmbrellas
Definition at line 952 of file TextStub.cpp.
ReexportedLibraries
std::vector<MetadataSection> llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::ReexportedLibraries
Definition at line 950 of file TextStub.cpp.
Reexports
SectionList llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::Reexports
Definition at line 954 of file TextStub.cpp.
SwiftABIVersion
SwiftVersion llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::SwiftABIVersion {0}
Definition at line 948 of file TextStub.cpp.
Targets
TargetList llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::Targets
Definition at line 944 of file TextStub.cpp.
TBDVersion
unsigned llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::TBDVersion
Definition at line 942 of file TextStub.cpp.
Undefineds
SectionList llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::Undefineds
Definition at line 955 of file TextStub.cpp.
UUIDs
std::vector<UUIDv4> llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::UUIDs
Definition at line 943 of file TextStub.cpp.
The documentation for this struct was generated from the following file:
lib/TextAPI/TextStub.cpp