LLVM: llvm::DefaultFoldingSetTrait< T > Struct Template Reference
llvm::DefaultFoldingSetTrait< T > Struct Template Reference
DefaultFoldingSetTrait - This class provides default implementations for FoldingSetTrait implementations.
#include "llvm/ADT/FoldingSet.h"
Static Public Member Functions
static void Profile (const T &X, FoldingSetNodeID &ID)
static void Profile (T &X, FoldingSetNodeID &ID)
static bool Equals (T &X, const FoldingSetNodeID &ID, unsigned IDHash, FoldingSetNodeID &TempID)
static unsigned ComputeHash (T &X, FoldingSetNodeID &TempID)
Detailed Description
template<typename T>
struct llvm::DefaultFoldingSetTrait< T >
DefaultFoldingSetTrait - This class provides default implementations for FoldingSetTrait implementations.
Definition at line 233 of file FoldingSet.h.
Member Function Documentation
ComputeHash()
template<typename T > unsigned llvm::DefaultFoldingSetTrait< T >::ComputeHash (T & X, FoldingSetNodeID & TempID) inline static
Definition at line 425 of file FoldingSet.h.
References llvm::FoldingSetNodeID::ComputeHash(), llvm::DefaultFoldingSetTrait< T >::Profile(), and X.
Equals()
template<typename T > bool llvm::DefaultFoldingSetTrait< T >::Equals (T & X, const FoldingSetNodeID & ID, unsigned IDHash, FoldingSetNodeID & TempID) inline static
Definition at line 417 of file FoldingSet.h.
References llvm::DefaultFoldingSetTrait< T >::Profile(), and X.
Profile() [1/2]
template<typename T > static void llvm::DefaultFoldingSetTrait< T >::Profile (const T & X, FoldingSetNodeID & ID) inline static
Definition at line 234 of file FoldingSet.h.
References X.
Referenced by llvm::FoldingSetNodeID::Add(), llvm::DefaultFoldingSetTrait< T >::ComputeHash(), llvm::DefaultFoldingSetTrait< T >::Equals(), llvm::FoldingSetNodeWrapper< T >::Profile(), and llvm::ImutProfileInfo< T >::Profile().
Profile() [2/2]
template<typename T > static void llvm::DefaultFoldingSetTrait< T >::Profile (T & X, FoldingSetNodeID & ID) inline static
Definition at line 237 of file FoldingSet.h.
References X.
The documentation for this struct was generated from the following file:
include/llvm/ADT/FoldingSet.h