LLVM: llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain > Struct Template Reference
llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain > Struct Template Reference
#include "llvm/CodeGen/SDPatternMatch.h"
Public Member Functions
TernaryOpc_match (unsigned Opc, const T0_P &Op0, const T1_P &Op1, const T2_P &Op2)
template<typename MatchContext >
bool match (const MatchContext &Ctx, SDValue N)
Public Attributes
unsigned Opcode
T0_P Op0
T1_P Op1
T2_P Op2
Detailed Description
template<typename T0_P, typename T1_P, typename T2_P, bool Commutable = false, bool ExcludeChain = false>
struct llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >
Definition at line 453 of file SDPatternMatch.h.
Constructor & Destructor Documentation
TernaryOpc_match()
template<typename T0_P , typename T1_P , typename T2_P , bool Commutable = false, bool ExcludeChain = false> llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::TernaryOpc_match (unsigned Opc, const T0_P & Op0, const T1_P & Op1, const T2_P & Op2) inline
Definition at line 459 of file SDPatternMatch.h.
Member Function Documentation
match()
template<typename T0_P , typename T1_P , typename T2_P , bool Commutable = false, bool ExcludeChain = false> template<typename MatchContext > bool llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::match (const MatchContext & Ctx, SDValue N) inline
Definition at line 464 of file SDPatternMatch.h.
References assert(), llvm::SDPatternMatch::EffectiveOperands< ExcludeChain >::FirstIndex, llvm::SDPatternMatch::m_Opc(), N, llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::Op0, llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::Op1, llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::Op2, llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::Opcode, llvm::SDPatternMatch::sd_context_match(), and llvm::SDPatternMatch::EffectiveOperands< ExcludeChain >::Size.
Member Data Documentation
Op0
template<typename T0_P , typename T1_P , typename T2_P , bool Commutable = false, bool ExcludeChain = false> T0_P llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::Op0
Definition at line 455 of file SDPatternMatch.h.
Referenced by llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::match().
Op1
template<typename T0_P , typename T1_P , typename T2_P , bool Commutable = false, bool ExcludeChain = false> T1_P llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::Op1
Definition at line 456 of file SDPatternMatch.h.
Referenced by llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::match().
Op2
template<typename T0_P , typename T1_P , typename T2_P , bool Commutable = false, bool ExcludeChain = false> T2_P llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::Op2
Definition at line 457 of file SDPatternMatch.h.
Referenced by llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::match().
Opcode
template<typename T0_P , typename T1_P , typename T2_P , bool Commutable = false, bool ExcludeChain = false> unsigned llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::Opcode
Definition at line 454 of file SDPatternMatch.h.
Referenced by llvm::SDPatternMatch::TernaryOpc_match< T0_P, T1_P, T2_P, Commutable, ExcludeChain >::match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/SDPatternMatch.h