LLVM: llvm::vfs::detail::NewInMemoryNodeInfo Struct Reference
llvm::vfs::detail::NewInMemoryNodeInfo Struct Reference
#include "llvm/Support/VirtualFileSystem.h"
Public Member Functions
Status makeStatus () const
Public Attributes
llvm::sys::fs::UniqueID DirUID
StringRef Path
StringRef Name
time_t ModificationTime
std::unique_ptr< llvm::MemoryBuffer > Buffer
uint32_t User
uint32_t Group
llvm::sys::fs::file_type Type
llvm::sys::fs::perms Perms
Detailed Description
Definition at line 489 of file VirtualFileSystem.h.
Member Function Documentation
makeStatus()
Status llvm::vfs::detail::NewInMemoryNodeInfo::makeStatus () const
Definition at line 816 of file VirtualFileSystem.cpp.
References Buffer, llvm::sys::fs::directory_file, DirUID, llvm::vfs::getDirectoryID(), llvm::vfs::getFileID(), Group, ModificationTime, Name, Path, Perms, and llvm::sys::toTimePoint().
Referenced by llvm::vfs::InMemoryFileSystem::addFile(), llvm::vfs::InMemoryFileSystem::addFileNoOwn(), and llvm::vfs::InMemoryFileSystem::addSymbolicLink().
Member Data Documentation
Buffer
std::unique_ptr<llvm::MemoryBuffer> llvm::vfs::detail::NewInMemoryNodeInfo::Buffer
Definition at line 494 of file VirtualFileSystem.h.
Referenced by llvm::vfs::InMemoryFileSystem::addFile(), llvm::vfs::InMemoryFileSystem::addFileNoOwn(), and makeStatus().
DirUID
llvm::sys::fs::UniqueID llvm::vfs::detail::NewInMemoryNodeInfo::DirUID
Definition at line 490 of file VirtualFileSystem.h.
Referenced by makeStatus().
Group
uint32_t llvm::vfs::detail::NewInMemoryNodeInfo::Group
Definition at line 496 of file VirtualFileSystem.h.
Referenced by makeStatus().
ModificationTime
time_t llvm::vfs::detail::NewInMemoryNodeInfo::ModificationTime
Definition at line 493 of file VirtualFileSystem.h.
Referenced by makeStatus().
Name
StringRef llvm::vfs::detail::NewInMemoryNodeInfo::Name
Definition at line 492 of file VirtualFileSystem.h.
Referenced by makeStatus().
Path
StringRef llvm::vfs::detail::NewInMemoryNodeInfo::Path
Definition at line 491 of file VirtualFileSystem.h.
Referenced by llvm::vfs::InMemoryFileSystem::addHardLink(), and makeStatus().
Perms
llvm::sys::fs::perms llvm::vfs::detail::NewInMemoryNodeInfo::Perms
Definition at line 498 of file VirtualFileSystem.h.
Referenced by makeStatus().
Type
llvm::sys::fs::file_type llvm::vfs::detail::NewInMemoryNodeInfo::Type
Definition at line 497 of file VirtualFileSystem.h.
User
uint32_t llvm::vfs::detail::NewInMemoryNodeInfo::User
Definition at line 495 of file VirtualFileSystem.h.
The documentation for this struct was generated from the following files:
include/llvm/Support/VirtualFileSystem.h
lib/Support/VirtualFileSystem.cpp