LLVM: llvm::BlockFrequencyInfoImplBase::Distribution Struct Reference
llvm::BlockFrequencyInfoImplBase::Distribution Struct Reference
Distribution of unscaled probability weight.
#include "llvm/Analysis/BlockFrequencyInfoImpl.h"
Public Types
using WeightList = SmallVector<Weight, 4>
Public Member Functions
Distribution ()=default
void addLocal (const BlockNode &Node, uint64_t Amount)
void addExit (const BlockNode &Node, uint64_t Amount)
void addBackedge (const BlockNode &Node, uint64_t Amount)
void normalize ()
Normalize the distribution.
Public Attributes
WeightList Weights
Individual successor weights.
uint64_t Total = 0
Sum of all weights.
bool DidOverflow = false
Whether Total did overflow.
Detailed Description
Distribution of unscaled probability weight.
Distribution of unscaled probability weight to a set of successors.
This class collates the successor edge weights for later processing.
DidOverflow indicates whether Total did overflow while adding to the distribution. It should never overflow twice.
Definition at line 385 of file BlockFrequencyInfoImpl.h.
Member Typedef Documentation
WeightList
using llvm::BlockFrequencyInfoImplBase::Distribution::WeightList = SmallVector<Weight, 4>
Definition at line 386 of file BlockFrequencyInfoImpl.h.
Constructor & Destructor Documentation
Distribution()
llvm::BlockFrequencyInfoImplBase::Distribution::Distribution () default
Member Function Documentation
addBackedge()
void llvm::BlockFrequencyInfoImplBase::Distribution::addBackedge (const BlockNode & Node, uint64_t Amount) inline
Definition at line 402 of file BlockFrequencyInfoImpl.h.
References llvm::BlockFrequencyInfoImplBase::Weight::Backedge.
Referenced by llvm::BlockFrequencyInfoImplBase::addToDist().
addExit()
void llvm::BlockFrequencyInfoImplBase::Distribution::addExit (const BlockNode & Node, uint64_t Amount) inline
Definition at line 398 of file BlockFrequencyInfoImpl.h.
References llvm::BlockFrequencyInfoImplBase::Weight::Exit.
Referenced by llvm::BlockFrequencyInfoImplBase::addToDist().
addLocal()
void llvm::BlockFrequencyInfoImplBase::Distribution::addLocal (const BlockNode & Node, uint64_t Amount) inline
Definition at line 394 of file BlockFrequencyInfoImpl.h.
References llvm::BlockFrequencyInfoImplBase::Weight::Local.
Referenced by llvm::BlockFrequencyInfoImplBase::addToDist(), and llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass().
normalize()
void Distribution::normalize ()
Normalize the distribution.
Combines multiple edges to the same Weight::TargetNode and scales down so that Total fits into 32-bits.
This is linear in the size of Weights. For the vast majority of cases, adjacent edge weights are combined by sorting WeightList and combining adjacent weights. However, for very large edge lists an auxiliary hash table is used.
Definition at line 236 of file BlockFrequencyInfoImpl.cpp.
References assert(), combineWeights(), llvm::countl_zero(), shiftRightAndRound(), and llvm::Total.
Member Data Documentation
DidOverflow
bool llvm::BlockFrequencyInfoImplBase::Distribution::DidOverflow = false
Whether Total did overflow.
Definition at line 390 of file BlockFrequencyInfoImpl.h.
Total
uint64_t llvm::BlockFrequencyInfoImplBase::Distribution::Total = 0
Sum of all weights.
Definition at line 389 of file BlockFrequencyInfoImpl.h.
Weights
WeightList llvm::BlockFrequencyInfoImplBase::Distribution::Weights
Individual successor weights.
Definition at line 388 of file BlockFrequencyInfoImpl.h.
Referenced by llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass(), llvm::BlockFrequencyInfoImplBase::distributeIrrLoopHeaderMass(), and llvm::BlockFrequencyInfoImplBase::distributeMass().
The documentation for this struct was generated from the following files:
include/llvm/Analysis/BlockFrequencyInfoImpl.h
lib/Analysis/BlockFrequencyInfoImpl.cpp