LLVM: llvm::AAPointerInfo Struct Reference
llvm::AAPointerInfo Struct Reference abstract
An abstract interface for struct information.
#include "llvm/Transforms/IPO/Attributor.h"
Classes
struct Access
An access description.
struct RangeList
A container for a list of ranges.
Public Types
enum AccessKind {
AK_MUST = 1 << 0 , AK_MAY = 1 << 1 , AK_R = 1 << 2 , AK_W = 1 << 3 ,
AK_RW = AK_R | AK_W , AK_ASSUMPTION = (1 << 4) | AK_MUST , AK_MAY_READ = AK_MAY | AK_R , AK_MAY_WRITE = AK_MAY | AK_W ,
AK_MAY_READ_WRITE = AK_MAY | AK_R | AK_W , AK_MUST_READ = AK_MUST | AK_R , AK_MUST_WRITE = AK_MUST | AK_W , AK_MUST_READ_WRITE = AK_MUST | AK_R | AK_W
}
using OffsetBinsTy = DenseMap<AA::RangeTy, SmallSet<unsigned, 4>>
using const_bin_iterator = OffsetBinsTy::const_iterator
Public Types inherited from llvm::AbstractAttribute
using StateType = AbstractState
Public Types inherited from llvm::IRPosition
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
using CallBaseContext = CallBase
Public Types inherited from llvm::AADepGraphNode
using DepTy = PointerIntPair<AADepGraphNode *, 1>
using DepSetTy = SmallSetVector<DepTy, 2>
using iterator = mapped_iterator<DepSetTy::iterator, decltype(&DepGetVal)>
using aaiterator
Public Member Functions
AAPointerInfo (const IRPosition &IRP)
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
virtual const_bin_iterator begin () const =0
virtual const_bin_iterator end () const =0
virtual int64_t numOffsetBins () const =0
virtual bool forallInterferingAccesses (AA::RangeTy Range, function_ref< bool(const Access &, bool)> CB) const =0
Call CB on all accesses that might interfere with Range and return true if all such accesses were known and the callback returned true for all of them, false otherwise.
virtual bool forallInterferingAccesses (Attributor &A, const AbstractAttribute &QueryingAA, Instruction &I, bool FindInterferingWrites, bool FindInterferingReads, function_ref< bool(const Access &, bool)> CB, bool &HasBeenWrittenTo, AA::RangeTy &Range, function_ref< bool(const Access &)> SkipCB=nullptr) const =0
Call CB on all accesses that might interfere with I and return true if all such accesses were known and the callback returned true for all of them, false otherwise.
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (const IRPosition &IRP)
virtual ~AbstractAttribute ()=default
Virtual destructor.
virtual void initialize (Attributor &A)
Initialize the state with the information in the Attributor A.
virtual bool isQueryAA () const
A query AA is always scheduled as long as we do updates because it does lazy computation that cannot be determined to be done from the outside.
virtual StateType & getState ()=0
Return the internal abstract state for inspection.
virtual const StateType & getState () const =0
const IRPosition & getIRPosition () const
Return an IR position, see struct IRPosition.
IRPosition & getIRPosition ()
void print (raw_ostream &OS) const
Helper functions, for debug purposes only.
void print (Attributor *, raw_ostream &OS) const override
virtual void printWithDeps (raw_ostream &OS) const
void dump () const
virtual const std::string getAsStr (Attributor *A) const =0
This function should return the "summarized" assumed state as string.
Public Member Functions inherited from llvm::IRPosition
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
bool isFunctionScope () const
Return true if this is a function or call site position.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getCalleeArgNo () const
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
int getCallSiteArgNo () const
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Value * getAttrListAnchor () const
Return the value attributes are attached to.
AttributeList getAttrList () const
Return the attributes associated with this function or call site scope.
void setAttrList (const AttributeList &AttrList) const
Update the attributes associated with this function or call site scope.
unsigned getNumArgs () const
Return the number of arguments associated with this function or call site scope.
Value * getArg (unsigned ArgNo) const
Return theargument ArgNo associated with this function or call site scope.
Kind getPositionKind () const
Return the associated position kind.
bool isAnyCallSitePosition () const
bool isArgumentPosition () const
Return true if the position is an argument or call site argument.
IRPosition stripCallBaseContext () const
Return the same position without the call base context.
const CallBaseContext * getCallBaseContext () const
Get the call base context from the position.
bool hasCallBaseContext () const
Check if the position has any call base context.
operator void * () const
}
Public Member Functions inherited from llvm::AADepGraphNode
virtual ~AADepGraphNode ()=default
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
void print (raw_ostream &OS) const
DepSetTy & getDeps ()
Static Public Member Functions
static bool isValidIRPositionForInit (Attributor &A, const IRPosition &IRP)
See AbstractAttribute::isValidIRPositionForInit.
static AAPointerInfo & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAPointerInfo.
Static Public Member Functions inherited from llvm::AbstractAttribute
static bool classof (const AADepGraphNode *DGN)
This function is used to identify if an DGN is of type AbstractAttribute so that the dyn_cast and cast can use such information to cast an AADepGraphNode to an AbstractAttribute.
static bool hasTrivialInitializer ()
Return false if this AA does anything non-trivial (hence not done by default) in its initializer.
static bool requiresCalleeForCallBase ()
Return true if this AA requires a "callee" (or an associted function) for a call site positon.
static bool requiresNonAsmForCallBase ()
Return true if this AA requires non-asm "callee" for a call site positon.
static bool requiresCallersForArgOrFunction ()
Return true if this AA requires all callees for an argument or function positon.
static bool isValidIRPositionForInit (Attributor &A, const IRPosition &IRP)
Return false if an AA should not be created for IRP.
static bool isValidIRPositionForUpdate (Attributor &A, const IRPosition &IRP)
Return false if an AA should not be updated for IRP.
Static Public Member Functions inherited from llvm::IRPosition
static const IRPosition value (const Value &V, const CallBaseContext *CBContext=nullptr)
Create a position describing the value of V.
static const IRPosition inst (const Instruction &I, const CallBaseContext *CBContext=nullptr)
Create a position describing the instruction I.
static const IRPosition function (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg, const CallBaseContext *CBContext=nullptr)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP, const CallBaseContext *CBContext=nullptr)
Create a position with function scope matching the "context" of IRP.
Static Public Attributes
static const char ID = 0
Unique ID (due to the unique address)
Static Public Attributes inherited from llvm::AbstractAttribute
static constexpr Attribute::AttrKind IRAttributeKind = Attribute::None
Compile time access to the IR attribute kind.
Static Public Attributes inherited from llvm::IRPosition
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Additional Inherited Members
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
virtual ChangeStatus manifest (Attributor &A)
Hook for the Attributor to trigger the manifestation of the information represented by the abstract attribute in the LLVM-IR.
virtual void trackStatistics () const =0
Hook to enable custom statistic tracking, called after manifest that resulted in a change if statistics are enabled.
virtual ChangeStatus updateImpl (Attributor &A)=0
The actual update/transfer function which has to be implemented by the derived classes.
Protected Member Functions inherited from llvm::AADepGraphNode
operator AbstractAttribute * ()
Static Protected Member Functions inherited from llvm::AADepGraphNode
static AADepGraphNode * DepGetVal (const DepTy &DT)
static AbstractAttribute * DepGetValAA (const DepTy &DT)
Protected Attributes inherited from llvm::AADepGraphNode
DepSetTy Deps
Set of dependency graph nodes which should be updated if this one is updated.
Detailed Description
An abstract interface for struct information.
Definition at line 5746 of file Attributor.h.
Member Typedef Documentation
const_bin_iterator
using llvm::AAPointerInfo::const_bin_iterator = OffsetBinsTy::const_iterator
Definition at line 6112 of file Attributor.h.
OffsetBinsTy
using llvm::AAPointerInfo::OffsetBinsTy = DenseMap<AA::RangeTy, SmallSet<unsigned, 4>>
Definition at line 6111 of file Attributor.h.
Member Enumeration Documentation
AccessKind
enum llvm::AAPointerInfo::AccessKind
Enumerator
AK_MUST
AK_MAY
AK_R
AK_W
AK_RW
AK_ASSUMPTION
AK_MAY_READ
AK_MAY_WRITE
AK_MAY_READ_WRITE
AK_MUST_READ
AK_MUST_WRITE
AK_MUST_READ_WRITE
Definition at line 5756 of file Attributor.h.
Constructor & Destructor Documentation
AAPointerInfo()
llvm::AAPointerInfo::AAPointerInfo (const IRPosition & IRP) inline
Definition at line 5747 of file Attributor.h.
Member Function Documentation
begin()
virtual const_bin_iterator llvm::AAPointerInfo::begin () const pure virtual
classof()
static bool llvm::AAPointerInfo::classof (const AbstractAttribute * AA) inline static
This function should return true if the type of the AA is AAPointerInfo.
Definition at line 6141 of file Attributor.h.
References llvm::AbstractAttribute::getIdAddr().
createForPosition()
static AAPointerInfo & llvm::AAPointerInfo::createForPosition (const IRPosition & IRP, Attributor & A) static
Create an abstract attribute view for the position IRP.
end()
virtual const_bin_iterator llvm::AAPointerInfo::end () const pure virtual
forallInterferingAccesses() [1/2]
virtual bool llvm::AAPointerInfo::forallInterferingAccesses (AA::RangeTy Range, function_ref< bool(const Access &, bool)> CB) const pure virtual
Call CB on all accesses that might interfere with Range and return true if all such accesses were known and the callback returned true for all of them, false otherwise.
An access interferes with an offset-size pair if it might read or write that memory region.
forallInterferingAccesses() [2/2]
virtual bool llvm::AAPointerInfo::forallInterferingAccesses (Attributor & A, const AbstractAttribute & QueryingAA, Instruction & I, bool FindInterferingWrites, bool FindInterferingReads, function_ref< bool(const Access &, bool)> CB, bool & HasBeenWrittenTo, AA::RangeTy & Range, function_ref< bool(const Access &)> SkipCB = nullptr) const pure virtual
Call CB on all accesses that might interfere with I and return true if all such accesses were known and the callback returned true for all of them, false otherwise.
In contrast to forallInterferingAccesses this function will perform reasoning to exclude write accesses that cannot affect the load even if they on the surface look as if they would. The flag HasBeenWrittenTo will be set to true if we know that I does not read the initial value of the underlying memory. If SkipCB is given and returns false for a potentially interfering access, that access is not checked for actual interference.
getIdAddr()
const char * llvm::AAPointerInfo::getIdAddr () const inline override virtual
See AbstractAttribute::getIdAddr()
Implements llvm::AbstractAttribute.
Definition at line 6109 of file Attributor.h.
References ID.
getName()
const std::string llvm::AAPointerInfo::getName () const inline override virtual
See AbstractAttribute::getName()
Implements llvm::AbstractAttribute.
Definition at line 6106 of file Attributor.h.
isValidIRPositionForInit()
static bool llvm::AAPointerInfo::isValidIRPositionForInit (Attributor & A, const IRPosition & IRP) inline static
See AbstractAttribute::isValidIRPositionForInit.
Definition at line 5750 of file Attributor.h.
References A, llvm::IRPosition::getAssociatedType(), llvm::Type::isPtrOrPtrVectorTy(), and llvm::AbstractAttribute::isValidIRPositionForInit().
numOffsetBins()
virtual int64_t llvm::AAPointerInfo::numOffsetBins () const pure virtual
Member Data Documentation
ID
const char AAPointerInfo::ID = 0 static
Unique ID (due to the unique address)
Definition at line 6146 of file Attributor.h.
Referenced by getIdAddr().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/AttributorAttributes.cpp