LLVM: llvm::PatternMatch::cstval_pred_ty< Predicate, ConstantVal, AllowPoison > Struct Template Reference
llvm::PatternMatch::cstval_pred_ty< Predicate, ConstantVal, AllowPoison > Struct Template Reference
This helper class is used to match constant scalars, vector splats, and fixed width vectors that satisfy a specified predicate.
#include "llvm/IR/PatternMatch.h"
Public Member Functions
template<typename ITy >
bool match_impl (ITy *V)
template<typename ITy >
bool match (ITy *V)
Public Attributes
const Constant ** Res = nullptr
Detailed Description
template<typename Predicate, typename ConstantVal, bool AllowPoison>
struct llvm::PatternMatch::cstval_pred_ty< Predicate, ConstantVal, AllowPoison >
This helper class is used to match constant scalars, vector splats, and fixed width vectors that satisfy a specified predicate.
For fixed width vector constants, poison elements are ignored if AllowPoison is true.
Definition at line 356 of file PatternMatch.h.
Member Function Documentation
match()
template<typename Predicate , typename ConstantVal , bool AllowPoison> template<typename ITy > bool llvm::PatternMatch::cstval_pred_ty< Predicate, ConstantVal, AllowPoison >::match (ITy * V) inline
Definition at line 392 of file PatternMatch.h.
References llvm::cast(), llvm::PatternMatch::cstval_pred_ty< Predicate, ConstantVal, AllowPoison >::match_impl(), and llvm::PatternMatch::cstval_pred_ty< Predicate, ConstantVal, AllowPoison >::Res.
match_impl()
template<typename Predicate , typename ConstantVal , bool AllowPoison> template<typename ITy > bool llvm::PatternMatch::cstval_pred_ty< Predicate, ConstantVal, AllowPoison >::match_impl (ITy * V) inline
Definition at line 358 of file PatternMatch.h.
References assert(), llvm::CallingConv::C, llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::Constant::getAggregateElement(), and llvm::isa().
Referenced by llvm::PatternMatch::cstval_pred_ty< Predicate, ConstantVal, AllowPoison >::match().
Member Data Documentation
Res
template<typename Predicate , typename ConstantVal , bool AllowPoison> const Constant** llvm::PatternMatch::cstval_pred_ty< Predicate, ConstantVal, AllowPoison >::Res = nullptr
Definition at line 357 of file PatternMatch.h.
Referenced by llvm::PatternMatch::cstval_pred_ty< Predicate, ConstantVal, AllowPoison >::match().
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h