LLVM: llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT > Struct Template Reference
llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT > Struct Template Reference
#include "llvm/Support/GenericDomTreeConstruction.h"
Classes
struct BatchUpdateInfo
struct BlockNamePrinter
struct InfoRec
struct InsertionInfo
Public Types
using NodePtr = typename DomTreeT::NodePtr
using NodeT = typename DomTreeT::NodeType
using TreeNodePtr = DomTreeNodeBase<NodeT> *
using RootsT = decltype(DomTreeT::Roots)
using GraphDiffT = GraphDiff<NodePtr, IsPostDom>
using UpdateT = typename DomTreeT::UpdateType
using UpdateKind = typename DomTreeT::UpdateKind
using BatchUpdatePtr = BatchUpdateInfo *
using NodeOrderMap = DenseMap<NodePtr, unsigned>
Public Member Functions
SemiNCAInfo (BatchUpdatePtr BUI)
void clear ()
NodePtr getIDom (NodePtr BB) const
TreeNodePtr getNodeForBlock (NodePtr BB, DomTreeT &DT)
template<bool IsReverse = false, typename DescendCondition >
unsigned runDFS (NodePtr V, unsigned LastNum, DescendCondition Condition, unsigned AttachToNum, const NodeOrderMap *SuccOrder=nullptr)
unsigned eval (unsigned V, unsigned LastLinked, SmallVectorImpl< InfoRec * > &Stack, ArrayRef< InfoRec * > NumToInfo)
void runSemiNCA ()
void addVirtualRoot ()
template<typename DescendCondition >
void doFullDFSWalk (const DomTreeT &DT, DescendCondition DC)
void attachNewSubtree (DomTreeT &DT, const TreeNodePtr AttachTo)
void reattachExistingSubtree (DomTreeT &DT, const TreeNodePtr AttachTo)
bool verifyRoots (const DomTreeT &DT)
bool verifyReachability (const DomTreeT &DT)
bool verifyParentProperty (const DomTreeT &DT)
bool verifySiblingProperty (const DomTreeT &DT)
Static Public Member Functions
template<bool Inversed>
static SmallVector< NodePtr, 8 > getChildren (NodePtr N, BatchUpdatePtr BUI)
template<bool Inversed>
static SmallVector< NodePtr, 8 > getChildren (NodePtr N)
static bool AlwaysDescend (NodePtr, NodePtr)
static bool HasForwardSuccessors (const NodePtr N, BatchUpdatePtr BUI)
static NodePtr GetEntryNode (const DomTreeT &DT)
static RootsT FindRoots (const DomTreeT &DT, BatchUpdatePtr BUI)
static void RemoveRedundantRoots (const DomTreeT &DT, BatchUpdatePtr BUI, RootsT &Roots)
static void CalculateFromScratch (DomTreeT &DT, BatchUpdatePtr BUI)
static void InsertEdge (DomTreeT &DT, const BatchUpdatePtr BUI, const NodePtr From, const NodePtr To)
static bool UpdateRootsBeforeInsertion (DomTreeT &DT, const BatchUpdatePtr BUI, const TreeNodePtr From, const TreeNodePtr To)
static bool isPermutation (const SmallVectorImpl< NodePtr > &A, const SmallVectorImpl< NodePtr > &B)
static void UpdateRootsAfterUpdate (DomTreeT &DT, const BatchUpdatePtr BUI)
static void InsertReachable (DomTreeT &DT, const BatchUpdatePtr BUI, const TreeNodePtr From, const TreeNodePtr To)
static void UpdateInsertion (DomTreeT &DT, const BatchUpdatePtr BUI, const TreeNodePtr NCD, InsertionInfo &II)
static void InsertUnreachable (DomTreeT &DT, const BatchUpdatePtr BUI, const TreeNodePtr From, const NodePtr To)
static void ComputeUnreachableDominators (DomTreeT &DT, const BatchUpdatePtr BUI, const NodePtr Root, const TreeNodePtr Incoming, SmallVectorImpl< std::pair< NodePtr, TreeNodePtr > > &DiscoveredConnectingEdges)
static void DeleteEdge (DomTreeT &DT, const BatchUpdatePtr BUI, const NodePtr From, const NodePtr To)
static void DeleteReachable (DomTreeT &DT, const BatchUpdatePtr BUI, const TreeNodePtr FromTN, const TreeNodePtr ToTN)
static bool HasProperSupport (DomTreeT &DT, const BatchUpdatePtr BUI, const TreeNodePtr TN)
static void DeleteUnreachable (DomTreeT &DT, const BatchUpdatePtr BUI, const TreeNodePtr ToTN)
static void EraseNode (DomTreeT &DT, const TreeNodePtr TN)
static void ApplyUpdates (DomTreeT &DT, GraphDiffT &PreViewCFG, GraphDiffT *PostViewCFG)
static void ApplyNextUpdate (DomTreeT &DT, BatchUpdateInfo &BUI)
static bool VerifyLevels (const DomTreeT &DT)
static bool VerifyDFSNumbers (const DomTreeT &DT)
static bool IsSameAsFreshTree (const DomTreeT &DT)
Public Attributes
SmallVector< NodePtr, 64 > NumToNode = {nullptr}
DenseMap< NodePtr, InfoRec > NodeToInfo
BatchUpdateInfo * BatchUpdates
Static Public Attributes
static constexpr bool IsPostDom = DomTreeT::IsPostDominator
Detailed Description
template<typename DomTreeT>
struct llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >
Definition at line 55 of file GenericDomTreeConstruction.h.
Member Typedef Documentation
BatchUpdatePtr
template<typename DomTreeT > using llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BatchUpdatePtr = BatchUpdateInfo *
Definition at line 95 of file GenericDomTreeConstruction.h.
GraphDiffT
template<typename DomTreeT > using llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::GraphDiffT = GraphDiff<NodePtr, IsPostDom>
Definition at line 61 of file GenericDomTreeConstruction.h.
NodeOrderMap
template<typename DomTreeT > using llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeOrderMap = DenseMap<NodePtr, unsigned>
Definition at line 166 of file GenericDomTreeConstruction.h.
NodePtr
template<typename DomTreeT > using llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodePtr = typename DomTreeT::NodePtr
Definition at line 56 of file GenericDomTreeConstruction.h.
NodeT
template<typename DomTreeT > using llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeT = typename DomTreeT::NodeType
Definition at line 57 of file GenericDomTreeConstruction.h.
RootsT
template<typename DomTreeT > using llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::RootsT = decltype(DomTreeT::Roots)
Definition at line 59 of file GenericDomTreeConstruction.h.
TreeNodePtr
template<typename DomTreeT > using llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::TreeNodePtr = DomTreeNodeBase<NodeT> *
Definition at line 58 of file GenericDomTreeConstruction.h.
UpdateKind
template<typename DomTreeT > using llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateKind = typename DomTreeT::UpdateKind
Definition at line 79 of file GenericDomTreeConstruction.h.
UpdateT
template<typename DomTreeT > using llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateT = typename DomTreeT::UpdateType
Definition at line 78 of file GenericDomTreeConstruction.h.
Constructor & Destructor Documentation
SemiNCAInfo()
template<typename DomTreeT > llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::SemiNCAInfo (BatchUpdatePtr BUI) inline
Definition at line 98 of file GenericDomTreeConstruction.h.
Member Function Documentation
addVirtualRoot()
template<typename DomTreeT > void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::addVirtualRoot () inline
Definition at line 310 of file GenericDomTreeConstruction.h.
References assert(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeToInfo, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NumToNode, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::doFullDFSWalk(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots().
AlwaysDescend()
template<typename DomTreeT > static bool llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::AlwaysDescend (NodePtr , NodePtr) inline static
Definition at line 148 of file GenericDomTreeConstruction.h.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::RemoveRedundantRoots(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyReachability().
ApplyNextUpdate()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyNextUpdate (DomTreeT & DT, BatchUpdateInfo & BUI) inline static
Definition at line 1181 of file GenericDomTreeConstruction.h.
References llvm::dbgs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertEdge(), LLVM_DEBUG, llvm::GraphDiff< NodePtr, InverseGraph >::popUpdateForIncrementalUpdates(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BatchUpdateInfo::PreViewCFG.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyUpdates().
ApplyUpdates()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyUpdates (DomTreeT & DT, GraphDiffT & PreViewCFG, GraphDiffT * PostViewCFG) inline static
Definition at line 1132 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyNextUpdate(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), llvm::GraphDiff< NodePtr, InverseGraph >::getNumLegalizedUpdates(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertEdge(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BatchUpdateInfo::IsRecalculated, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BatchUpdateInfo::NumLegalized, and llvm::GraphDiff< NodePtr, InverseGraph >::popUpdateForIncrementalUpdates().
Referenced by llvm::DomTreeBuilder::ApplyUpdates().
attachNewSubtree()
template<typename DomTreeT > void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::attachNewSubtree (DomTreeT & DT, const TreeNodePtr AttachTo) inline
Definition at line 583 of file GenericDomTreeConstruction.h.
References llvm::drop_begin(), llvm::DomTreeNodeBase< T >::getBlock(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getIDom(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getNodeForBlock(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeToInfo, and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NumToNode.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ComputeUnreachableDominators().
CalculateFromScratch()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch (DomTreeT & DT, BatchUpdatePtr BUI) inline static
Definition at line 544 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::AlwaysDescend(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::attachNewSubtree(), llvm::dbgs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::doFullDFSWalk(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BatchUpdateInfo::IsRecalculated, LLVM_DEBUG, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BatchUpdateInfo::PostViewCFG, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BatchUpdateInfo::PreViewCFG, and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runSemiNCA().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyUpdates(), llvm::DomTreeBuilder::Calculate(), llvm::DomTreeBuilder::CalculateWithUpdates(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsAfterUpdate(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsBeforeInsertion().
clear()
template<typename DomTreeT > void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::clear () inline
Definition at line 100 of file GenericDomTreeConstruction.h.
References llvm::SmallVectorImpl< T >::clear(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeToInfo, and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NumToNode.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::RemoveRedundantRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyReachability(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty().
ComputeUnreachableDominators()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ComputeUnreachableDominators (DomTreeT & DT, const BatchUpdatePtr BUI, const NodePtr Root, const TreeNodePtr Incoming, SmallVectorImpl< std::pair< NodePtr, TreeNodePtr > > & DiscoveredConnectingEdges) inline static
Definition at line 871 of file GenericDomTreeConstruction.h.
References assert(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::attachNewSubtree(), llvm::dbgs(), From, LLVM_DEBUG, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runSemiNCA().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertUnreachable().
DeleteEdge()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge (DomTreeT & DT, const BatchUpdatePtr BUI, const NodePtr From, const NodePtr To) inline static
Definition at line 896 of file GenericDomTreeConstruction.h.
References assert(), llvm::dbgs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), From, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getChildren(), llvm::DomTreeNodeBase< T >::getIDom(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasProperSupport(), llvm::is_contained(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, LLVM_DEBUG, and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsAfterUpdate().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyNextUpdate(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyUpdates(), and llvm::DomTreeBuilder::DeleteEdge().
DeleteReachable()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable (DomTreeT & DT, const BatchUpdatePtr BUI, const TreeNodePtr FromTN, const TreeNodePtr ToTN) inline static
Definition at line 949 of file GenericDomTreeConstruction.h.
References assert(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch(), llvm::dbgs(), llvm::DomTreeNodeBase< T >::getBlock(), llvm::DomTreeNodeBase< T >::getIDom(), llvm::DomTreeNodeBase< T >::getLevel(), LLVM_DEBUG, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::reattachExistingSubtree(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runSemiNCA().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge().
DeleteUnreachable()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable (DomTreeT & DT, const BatchUpdatePtr BUI, const TreeNodePtr ToTN) inline static
Definition at line 1014 of file GenericDomTreeConstruction.h.
References assert(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::clear(), llvm::dbgs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::EraseNode(), llvm::DomTreeNodeBase< T >::getBlock(), llvm::DomTreeNodeBase< T >::getIDom(), llvm::DomTreeNodeBase< T >::getLevel(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), llvm::is_contained(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, LLVM_DEBUG, N, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NumToNode, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::reattachExistingSubtree(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runSemiNCA().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge().
doFullDFSWalk()
template<typename DomTreeT > template<typename DescendCondition > void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::doFullDFSWalk (const DomTreeT & DT, DescendCondition DC) inline
Definition at line 532 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::addVirtualRoot(), assert(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyReachability(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty().
EraseNode()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::EraseNode (DomTreeT & DT, const TreeNodePtr TN) inline static
Definition at line 1113 of file GenericDomTreeConstruction.h.
References assert(), llvm::find(), llvm::DomTreeNodeBase< T >::getBlock(), llvm::DomTreeNodeBase< T >::getIDom(), llvm::DomTreeNodeBase< T >::getNumChildren(), and std::swap().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable().
eval()
template<typename DomTreeT > unsigned llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::eval (unsigned V, unsigned LastLinked, SmallVectorImpl< InfoRec * > & Stack, ArrayRef< InfoRec * > NumToInfo) inline
Definition at line 228 of file GenericDomTreeConstruction.h.
References assert(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InfoRec::Label, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InfoRec::Parent, and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InfoRec::Semi.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runSemiNCA().
FindRoots()
template<typename DomTreeT > static RootsT llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots (const DomTreeT & DT, BatchUpdatePtr BUI) inline static
Definition at line 336 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::addVirtualRoot(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::AlwaysDescend(), assert(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BatchUpdates, llvm::dbgs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getChildren(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::GetEntryNode(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasForwardSuccessors(), I, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, LLVM_DEBUG, N, nodes, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeToInfo, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NumToNode, llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::RemoveRedundantRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), and llvm::Total.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsAfterUpdate(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyRoots().
getChildren() [1/2]
template<typename DomTreeT > template<bool Inversed> static SmallVector< NodePtr, 8 > llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getChildren (NodePtr N) inline static
Definition at line 115 of file GenericDomTreeConstruction.h.
References llvm::children(), llvm::erase(), N, and llvm::detail::reverse_if().
getChildren() [2/2]
template<typename DomTreeT > template<bool Inversed> static SmallVector< NodePtr, 8 > llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getChildren (NodePtr N, BatchUpdatePtr BUI) inline static
Definition at line 108 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getChildren(), N, and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BatchUpdateInfo::PreViewCFG.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getChildren(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasForwardSuccessors(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasProperSupport(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS().
GetEntryNode()
template<typename DomTreeT > static NodePtr llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::GetEntryNode (const DomTreeT & DT) inline static
Definition at line 328 of file GenericDomTreeConstruction.h.
References assert().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyRoots().
getIDom()
template<typename DomTreeT > NodePtr llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getIDom (NodePtr BB) const inline
Definition at line 126 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeToInfo.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::attachNewSubtree(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getNodeForBlock().
getNodeForBlock()
template<typename DomTreeT > TreeNodePtr llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getNodeForBlock (NodePtr BB, DomTreeT & DT) inline
Definition at line 133 of file GenericDomTreeConstruction.h.
References assert(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getIDom(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getNodeForBlock().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::attachNewSubtree(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getNodeForBlock().
HasForwardSuccessors()
template<typename DomTreeT > static bool llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasForwardSuccessors (const NodePtr N, BatchUpdatePtr BUI) inline static
Definition at line 323 of file GenericDomTreeConstruction.h.
References assert(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getChildren(), and N.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::RemoveRedundantRoots().
HasProperSupport()
template<typename DomTreeT > static bool llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasProperSupport (DomTreeT & DT, const BatchUpdatePtr BUI, const TreeNodePtr TN) inline static
Definition at line 990 of file GenericDomTreeConstruction.h.
References llvm::dbgs(), llvm::DomTreeNodeBase< T >::getBlock(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getChildren(), and LLVM_DEBUG.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge().
InsertEdge()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertEdge (DomTreeT & DT, const BatchUpdatePtr BUI, const NodePtr From, const NodePtr To) inline static
Definition at line 632 of file GenericDomTreeConstruction.h.
References assert(), llvm::dbgs(), From, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertUnreachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, and LLVM_DEBUG.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyNextUpdate(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ApplyUpdates(), and llvm::DomTreeBuilder::InsertEdge().
InsertReachable()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable (DomTreeT & DT, const BatchUpdatePtr BUI, const TreeNodePtr From, const TreeNodePtr To) inline static
Definition at line 720 of file GenericDomTreeConstruction.h.
References assert(), llvm::dbgs(), llvm::SmallVectorBase< Size_T >::empty(), From, llvm::DomTreeNodeBase< T >::getBlock(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getChildren(), llvm::DomTreeNodeBase< T >::getLevel(), II, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, LLVM_DEBUG, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateInsertion(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsBeforeInsertion().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertEdge(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertUnreachable().
InsertUnreachable()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertUnreachable (DomTreeT & DT, const BatchUpdatePtr BUI, const TreeNodePtr From, const NodePtr To) inline static
Definition at line 846 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ComputeUnreachableDominators(), llvm::dbgs(), From, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), and LLVM_DEBUG.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertEdge().
isPermutation()
template<typename DomTreeT > static bool llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::isPermutation (const SmallVectorImpl< NodePtr > & A, const SmallVectorImpl< NodePtr > & B) inline static
Definition at line 680 of file GenericDomTreeConstruction.h.
References A, B, llvm::SmallPtrSetImpl< PtrType >::count(), and N.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsAfterUpdate(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyRoots().
IsSameAsFreshTree()
template<typename DomTreeT > static bool llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsSameAsFreshTree (const DomTreeT & DT) inline static
Definition at line 1523 of file GenericDomTreeConstruction.h.
References llvm::errs(), and llvm::raw_ostream::flush().
Referenced by llvm::DomTreeBuilder::Verify().
reattachExistingSubtree()
template<typename DomTreeT > void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::reattachExistingSubtree (DomTreeT & DT, const TreeNodePtr AttachTo) inline
Definition at line 602 of file GenericDomTreeConstruction.h.
References assert(), llvm::drop_begin(), llvm::DomTreeNodeBase< T >::getBlock(), N, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeToInfo, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NumToNode, and llvm::DomTreeNodeBase< T >::setIDom().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable().
RemoveRedundantRoots()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::RemoveRedundantRoots (const DomTreeT & DT, BatchUpdatePtr BUI, RootsT & Roots) inline static
Definition at line 492 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::AlwaysDescend(), assert(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::clear(), llvm::dbgs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasForwardSuccessors(), llvm::is_contained(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, LLVM_DEBUG, N, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NumToNode, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), and std::swap().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots().
runDFS()
template<typename DomTreeT > template<bool IsReverse = false, typename DescendCondition > unsigned llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS (NodePtr V, unsigned LastNum, DescendCondition Condition, unsigned AttachToNum, const NodeOrderMap * SuccOrder = nullptr) inline
Definition at line 179 of file GenericDomTreeConstruction.h.
References A, assert(), B, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BatchUpdates, llvm::SmallVectorBase< Size_T >::empty(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getChildren(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeToInfo, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NumToNode, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::sort().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ComputeUnreachableDominators(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::doFullDFSWalk(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::RemoveRedundantRoots().
runSemiNCA()
template<typename DomTreeT > void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runSemiNCA () inline
Definition at line 260 of file GenericDomTreeConstruction.h.
References assert(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::eval(), N, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeToInfo, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NumToNode, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::ComputeUnreachableDominators(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable().
UpdateInsertion()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateInsertion (DomTreeT & DT, const BatchUpdatePtr BUI, const TreeNodePtr NCD, InsertionInfo & II) inline static
Definition at line 826 of file GenericDomTreeConstruction.h.
References assert(), llvm::dbgs(), llvm::DomTreeNodeBase< T >::getIDom(), llvm::DomTreeNodeBase< T >::getLevel(), II, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, LLVM_DEBUG, llvm::DomTreeNodeBase< T >::setIDom(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsAfterUpdate().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable().
UpdateRootsAfterUpdate()
template<typename DomTreeT > static void llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsAfterUpdate (DomTreeT & DT, const BatchUpdatePtr BUI) inline static
Definition at line 694 of file GenericDomTreeConstruction.h.
References assert(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch(), llvm::dbgs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::isPermutation(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, LLVM_DEBUG, N, and llvm::none_of().
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateInsertion().
UpdateRootsBeforeInsertion()
template<typename DomTreeT > static bool llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsBeforeInsertion (DomTreeT & DT, const BatchUpdatePtr BUI, const TreeNodePtr From, const TreeNodePtr To) inline static
Definition at line 662 of file GenericDomTreeConstruction.h.
References assert(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch(), llvm::dbgs(), llvm::DomTreeNodeBase< T >::getBlock(), llvm::DomTreeNodeBase< T >::getIDom(), llvm::is_contained(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, and LLVM_DEBUG.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable().
VerifyDFSNumbers()
template<typename DomTreeT > static bool llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers (const DomTreeT & DT) inline static
Definition at line 1314 of file GenericDomTreeConstruction.h.
References assert(), llvm::errs(), llvm::raw_ostream::flush(), llvm::DomTreeNodeBase< T >::getDFSNumIn(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, and llvm::sort().
Referenced by llvm::DomTreeBuilder::Verify().
VerifyLevels()
template<typename DomTreeT > static bool llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyLevels (const DomTreeT & DT) inline static
Definition at line 1282 of file GenericDomTreeConstruction.h.
References llvm::errs(), llvm::raw_ostream::flush(), llvm::DomTreeNodeBase< T >::getBlock(), llvm::DomTreeNodeBase< T >::getIDom(), and llvm::DomTreeNodeBase< T >::getLevel().
Referenced by llvm::DomTreeBuilder::Verify().
verifyParentProperty()
template<typename DomTreeT > bool llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty (const DomTreeT & DT) inline
Definition at line 1450 of file GenericDomTreeConstruction.h.
References llvm::DomTreeNodeBase< T >::children(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::clear(), llvm::dbgs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::doFullDFSWalk(), llvm::errs(), llvm::raw_ostream::flush(), From, llvm::DomTreeNodeBase< T >::getBlock(), llvm::DomTreeNodeBase< T >::isLeaf(), LLVM_DEBUG, and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeToInfo.
Referenced by llvm::DomTreeBuilder::Verify().
verifyReachability()
template<typename DomTreeT > bool llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyReachability (const DomTreeT & DT) inline
Definition at line 1246 of file GenericDomTreeConstruction.h.
References llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::AlwaysDescend(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::clear(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::doFullDFSWalk(), llvm::errs(), llvm::raw_ostream::flush(), llvm::DomTreeNodeBase< T >::getBlock(), N, llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeToInfo, and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NumToNode.
Referenced by llvm::DomTreeBuilder::Verify().
verifyRoots()
template<typename DomTreeT > bool llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyRoots (const DomTreeT & DT) inline
Definition at line 1207 of file GenericDomTreeConstruction.h.
References llvm::errs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), llvm::raw_ostream::flush(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::GetEntryNode(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::isPermutation(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom, and N.
Referenced by llvm::DomTreeBuilder::Verify().
verifySiblingProperty()
template<typename DomTreeT > bool llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty (const DomTreeT & DT) inline
Definition at line 1484 of file GenericDomTreeConstruction.h.
References llvm::DomTreeNodeBase< T >::children(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::clear(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::doFullDFSWalk(), llvm::errs(), llvm::raw_ostream::flush(), From, llvm::DomTreeNodeBase< T >::getBlock(), llvm::DomTreeNodeBase< T >::isLeaf(), N, and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeToInfo.
Referenced by llvm::DomTreeBuilder::Verify().
Member Data Documentation
BatchUpdates
template<typename DomTreeT > BatchUpdateInfo* llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::BatchUpdates
Definition at line 94 of file GenericDomTreeConstruction.h.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS().
IsPostDom
template<typename DomTreeT > bool llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::IsPostDom = DomTreeT::IsPostDominator static constexpr
Definition at line 60 of file GenericDomTreeConstruction.h.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::addVirtualRoot(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::CalculateFromScratch(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::doFullDFSWalk(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertEdge(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::RemoveRedundantRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateInsertion(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsAfterUpdate(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsBeforeInsertion(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyRoots().
NodeToInfo
template<typename DomTreeT > DenseMap<NodePtr, InfoRec> llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NodeToInfo
Definition at line 76 of file GenericDomTreeConstruction.h.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::addVirtualRoot(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::attachNewSubtree(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::clear(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::getIDom(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::reattachExistingSubtree(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runSemiNCA(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyReachability(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty().
NumToNode
template<typename DomTreeT > SmallVector<NodePtr, 64> llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::NumToNode = {nullptr}
Definition at line 75 of file GenericDomTreeConstruction.h.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::addVirtualRoot(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::attachNewSubtree(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::clear(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::FindRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::reattachExistingSubtree(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::RemoveRedundantRoots(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runSemiNCA(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyReachability().
The documentation for this struct was generated from the following files:
include/llvm/Support/GenericDomTree.h
include/llvm/Support/GenericDomTreeConstruction.h