LLVM: llvm::LLVMRemarkSetupErrorInfo< ThisError > Struct Template Reference
llvm::LLVMRemarkSetupErrorInfo< ThisError > Struct Template Reference
#include "llvm/IR/LLVMRemarkStreamer.h"
Public Member Functions
LLVMRemarkSetupErrorInfo (Error E)
void log (raw_ostream &OS) const override
Print an error message to an output stream.
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
Public Member Functions inherited from llvm::ErrorInfo< ThisError >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual std::string message () const
Return the error message as a string.
template<typename ErrorInfoT >
bool isA () const
Public Attributes
std::string Msg
std::error_code EC
Additional Inherited Members
Static Public Member Functions inherited from llvm::ErrorInfo< ThisError >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Detailed Description
template<typename ThisError>
struct llvm::LLVMRemarkSetupErrorInfo< ThisError >
Definition at line 48 of file LLVMRemarkStreamer.h.
Constructor & Destructor Documentation
LLVMRemarkSetupErrorInfo()
template<typename ThisError > llvm::LLVMRemarkSetupErrorInfo< ThisError >::LLVMRemarkSetupErrorInfo (Error E) inline
Definition at line 52 of file LLVMRemarkStreamer.h.
References llvm::ErrorInfoBase::convertToErrorCode(), llvm::LLVMRemarkSetupErrorInfo< ThisError >::EC, llvm::handleAllErrors(), llvm::ErrorInfoBase::message(), and llvm::LLVMRemarkSetupErrorInfo< ThisError >::Msg.
Member Function Documentation
convertToErrorCode()
template<typename ThisError > std::error_code llvm::LLVMRemarkSetupErrorInfo< ThisError >::convertToErrorCode () const inline override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 60 of file LLVMRemarkStreamer.h.
References llvm::LLVMRemarkSetupErrorInfo< ThisError >::EC.
log()
template<typename ThisError > void llvm::LLVMRemarkSetupErrorInfo< ThisError >::log (raw_ostream & OS) const inline override virtual
Print an error message to an output stream.
Implements llvm::ErrorInfoBase.
Definition at line 59 of file LLVMRemarkStreamer.h.
References llvm::LLVMRemarkSetupErrorInfo< ThisError >::Msg, and OS.
Member Data Documentation
EC
template<typename ThisError > std::error_code llvm::LLVMRemarkSetupErrorInfo< ThisError >::EC
Definition at line 50 of file LLVMRemarkStreamer.h.
Referenced by llvm::LLVMRemarkSetupErrorInfo< ThisError >::convertToErrorCode(), and llvm::LLVMRemarkSetupErrorInfo< ThisError >::LLVMRemarkSetupErrorInfo().
Msg
template<typename ThisError > std::string llvm::LLVMRemarkSetupErrorInfo< ThisError >::Msg
Definition at line 49 of file LLVMRemarkStreamer.h.
Referenced by llvm::LLVMRemarkSetupErrorInfo< ThisError >::LLVMRemarkSetupErrorInfo(), and llvm::LLVMRemarkSetupErrorInfo< ThisError >::log().
The documentation for this struct was generated from the following file:
include/llvm/IR/LLVMRemarkStreamer.h