LLVM: llvm::MachinePointerInfo Struct Reference
llvm::MachinePointerInfo Struct Reference
This class contains a discriminated union of information about pointers in memory operands, relating them back to LLVM IR or to virtual locations (such as frame indices) that are exposed during codegen.
#include "llvm/CodeGen/MachineMemOperand.h"
Public Member Functions
MachinePointerInfo (const Value *v, int64_t offset=0, uint8_t ID=0)
MachinePointerInfo (const PseudoSourceValue *v, int64_t offset=0, uint8_t ID=0)
MachinePointerInfo (unsigned AddressSpace=0, int64_t offset=0)
MachinePointerInfo (PointerUnion< const Value *, const PseudoSourceValue * > v, int64_t offset=0, uint8_t ID=0)
MachinePointerInfo getWithOffset (int64_t O) const
bool isDereferenceable (unsigned Size, LLVMContext &C, const DataLayout &DL) const
Return true if memory region [V, V+Offset+Size) is known to be dereferenceable.
unsigned getAddrSpace () const
Return the LLVM IR address space number that this pointer points into.
Static Public Member Functions
static MachinePointerInfo getConstantPool (MachineFunction &MF)
Return a MachinePointerInfo record that refers to the constant pool.
static MachinePointerInfo getFixedStack (MachineFunction &MF, int FI, int64_t Offset=0)
Return a MachinePointerInfo record that refers to the specified FrameIndex.
static MachinePointerInfo getJumpTable (MachineFunction &MF)
Return a MachinePointerInfo record that refers to a jump table entry.
static MachinePointerInfo getGOT (MachineFunction &MF)
Return a MachinePointerInfo record that refers to a GOT entry.
static MachinePointerInfo getStack (MachineFunction &MF, int64_t Offset, uint8_t ID=0)
Stack pointer relative access.
static MachinePointerInfo getUnknownStack (MachineFunction &MF)
Stack memory without other information.
Public Attributes
PointerUnion< const Value *, const PseudoSourceValue * > V
This is the IR pointer value for the access, or it is null if unknown.
int64_t Offset
Offset - This is an offset from the base Value*.
unsigned AddrSpace = 0
uint8_t StackID
Detailed Description
This class contains a discriminated union of information about pointers in memory operands, relating them back to LLVM IR or to virtual locations (such as frame indices) that are exposed during codegen.
Definition at line 41 of file MachineMemOperand.h.
Constructor & Destructor Documentation
MachinePointerInfo() [1/4]
llvm::MachinePointerInfo::MachinePointerInfo (const Value * v, int64_t offset = 0, uint8_t ID = 0) inline explicit
Definition at line 52 of file MachineMemOperand.h.
References AddrSpace, and llvm::getPointerAddressSpace().
Referenced by getConstantPool(), getFixedStack(), getGOT(), getJumpTable(), getStack(), getUnknownStack(), and getWithOffset().
MachinePointerInfo() [2/4]
llvm::MachinePointerInfo::MachinePointerInfo (const PseudoSourceValue * v, int64_t offset = 0, uint8_t ID = 0) inline explicit
Definition at line 58 of file MachineMemOperand.h.
References AddrSpace.
MachinePointerInfo() [3/4]
llvm::MachinePointerInfo::MachinePointerInfo (unsigned AddressSpace = 0, int64_t offset = 0) inline explicit
Definition at line 64 of file MachineMemOperand.h.
MachinePointerInfo() [4/4]
llvm::MachinePointerInfo::MachinePointerInfo (PointerUnion< const Value *, const PseudoSourceValue * > v, int64_t offset = 0, uint8_t ID = 0) inline explicit
Definition at line 68 of file MachineMemOperand.h.
References AddrSpace, llvm::cast(), and llvm::dyn_cast_if_present().
Member Function Documentation
getAddrSpace()
unsigned MachinePointerInfo::getAddrSpace () const
Return the LLVM IR address space number that this pointer points into.
getAddrSpace - Return the LLVM IR address space number that this pointer points into.
Definition at line 1037 of file MachineOperand.cpp.
References AddrSpace.
Referenced by AddNodeIDCustom(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::MemSDNode::getAddressSpace(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getGatherVP(), llvm::SelectionDAG::getGetFPEnv(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getLoadVP(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedHistogram(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getMaskedStore(), llvm::SelectionDAG::getMemcpy(), getMemcpyLoadsAndStores(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getMemmove(), getMemmoveLoadsAndStores(), llvm::SelectionDAG::getMemset(), getMemsetStores(), llvm::SelectionDAG::getScatterVP(), llvm::SelectionDAG::getSetFPEnv(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getStoreVP(), llvm::SelectionDAG::getStridedLoadVP(), llvm::SelectionDAG::getStridedStoreVP(), llvm::SelectionDAG::getTruncStore(), llvm::SelectionDAG::getTruncStoreVP(), llvm::SelectionDAG::getTruncStridedStoreVP(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::CombinerHelper::matchCombineExtractedVectorLoad(), and narrowExtractedVectorLoad().
getConstantPool()
MachinePointerInfo MachinePointerInfo::getConstantPool (MachineFunction & MF) static
Return a MachinePointerInfo record that refers to the constant pool.
getConstantPool - Return a MachinePointerInfo record that refers to the constant pool.
Definition at line 1056 of file MachineOperand.cpp.
References llvm::PseudoSourceValueManager::getConstantPool(), llvm::MachineFunction::getPSVManager(), and MachinePointerInfo().
Referenced by combineConcatVectorOps(), combineTargetShuffle(), llvm::TargetLowering::CTTZTableLookup(), emitLoadFromConstantPool(), llvm::CSKYInstrInfo::getGlobalBaseReg(), lowerBuildVectorAsBroadcast(), LowerUINT_TO_FP_i64(), lowerUINT_TO_FP_vXi32(), and llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle().
getFixedStack()
MachinePointerInfo MachinePointerInfo::getFixedStack (MachineFunction & MF, int FI, int64_t Offset = 0) static
Return a MachinePointerInfo record that refers to the specified FrameIndex.
getFixedStack - Return a MachinePointerInfo record that refers to the the specified FrameIndex.
Definition at line 1062 of file MachineOperand.cpp.
References llvm::PseudoSourceValueManager::getFixedStack(), llvm::MachineFunction::getPSVManager(), MachinePointerInfo(), and Offset.
Referenced by addFrameReference(), llvm::addFrameReference(), llvm::addFrameReference(), llvm::M68k::addFrameReference(), llvm::M68k::addMemOperand(), buildEpilogRestore(), llvm::X86TargetLowering::BuildFILD(), buildPrologSpill(), llvm::SIRegisterInfo::buildVGPRSpillLoadStore(), llvm::LegalizerHelper::createStackTemporary(), emitBuildPairF64Pseudo(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::TargetLoweringBase::emitPatchPoint(), llvm::X86FrameLowering::emitPrologue(), emitSplitF64Pseudo(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::TargetLowering::expandVECTOR_COMPRESS(), llvm::TargetLowering::expandVectorSplice(), foldInlineAsmMemOperand(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::RISCVInstrInfo::foldMemoryOperandImpl(), getAddressForMemoryInput(), getFrameIndexMMO(), getMachineMemOperand(), llvm::MipsInstrInfo::GetMemOperand(), getStackAlignedMMO(), llvm::CallLowering::handleAssignments(), InferPointerInfo(), llvm::CallLowering::insertSRetLoads(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::ARCInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::AVRInstrInfo::loadRegFromStackSlot(), llvm::CSKYInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::LoongArchInstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::RISCVInstrInfo::loadRegFromStackSlot(), llvm::SIInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::VEInstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlotNoUpd(), LowerATOMIC_STORE(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::TargetLowering::LowerCallTo(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::XtensaTargetLowering::LowerFormalArguments(), llvm::MipsCallLowering::lowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::AArch64FrameLowering::restoreCalleeSavedRegisters(), llvm::AArch64FrameLowering::spillCalleeSavedRegisters(), spillIncomingStatepointValue(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::ARCInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::AVRInstrInfo::storeRegToStackSlot(), llvm::CSKYInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::LoongArchInstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::RISCVInstrInfo::storeRegToStackSlot(), llvm::SIInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::VEInstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::PPCInstrInfo::storeRegToStackSlotNoUpd(), StoreTailCallArgumentsToStackSlot(), unpack64(), unpackF64OnRV32DSoftABI(), unpackFromMemLoc(), unpackFromMemLoc(), unpackFromMemLoc(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getGOT()
MachinePointerInfo MachinePointerInfo::getGOT (MachineFunction & MF) static
Return a MachinePointerInfo record that refers to a GOT entry.
Definition at line 1071 of file MachineOperand.cpp.
References llvm::PseudoSourceValueManager::getGOT(), llvm::MachineFunction::getPSVManager(), and MachinePointerInfo().
Referenced by expandLoadStackGuard(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::MipsTargetLowering::getAddrLocal(), getzOSCalleeAndADA(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), LowerToTLSExecModel(), llvm::SparcTargetLowering::makeAddress(), and llvm::VETargetLowering::makeAddress().
getJumpTable()
MachinePointerInfo MachinePointerInfo::getJumpTable (MachineFunction & MF) static
Return a MachinePointerInfo record that refers to a jump table entry.
Definition at line 1067 of file MachineOperand.cpp.
References llvm::PseudoSourceValueManager::getJumpTable(), llvm::MachineFunction::getPSVManager(), and MachinePointerInfo().
getStack()
MachinePointerInfo MachinePointerInfo::getStack (MachineFunction & MF, int64_t Offset, uint8_t ID = 0) static
Stack pointer relative access.
Definition at line 1075 of file MachineOperand.cpp.
References llvm::MachineFunction::getPSVManager(), llvm::PseudoSourceValueManager::getStack(), MachinePointerInfo(), and Offset.
Referenced by M68kOutgoingArgHandler::getStackAddress(), llvm::AMDGPUTargetLowering::loadStackInputValue(), llvm::HexagonTargetLowering::LowerCall(), llvm::SITargetLowering::LowerCall(), and llvm::AMDGPUTargetLowering::storeStackInputValue().
getUnknownStack()
MachinePointerInfo MachinePointerInfo::getUnknownStack (MachineFunction & MF) static
Stack memory without other information.
Definition at line 1080 of file MachineOperand.cpp.
References llvm::DataLayout::getAllocaAddrSpace(), llvm::MachineFunction::getDataLayout(), and MachinePointerInfo().
Referenced by llvm::TargetLowering::expandVECTOR_COMPRESS(), llvm::TargetLowering::expandVectorSplice(), llvm::CallLowering::handleAssignments(), and llvm::LegalizerHelper::lowerVECTOR_COMPRESS().
getWithOffset()
MachinePointerInfo llvm::MachinePointerInfo::getWithOffset (int64_t O) const inline
Definition at line 81 of file MachineMemOperand.h.
References AddrSpace, llvm::cast(), llvm::isa(), MachinePointerInfo(), Offset, and StackID.
Referenced by llvm::SIRegisterInfo::buildSpillLoadStore(), combineExtractFromVectorLoad(), combineStore(), combineTargetShuffle(), emitBuildPairF64Pseudo(), emitConstantSizeRepmov(), emitSplitF64Pseudo(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::MachineFunction::getMachineMemOperand(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), llvm::LegalizerHelper::lowerExtractInsertVectorElt(), LowerF128Load(), LowerF128Store(), llvm::CombinerHelper::matchCombineExtractedVectorLoad(), PerformSplittingMVETruncToNarrowingStores(), PerformSplittingToNarrowingStores(), PerformSTORECombine(), prepareDescriptorIndirectCall(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), reduceMaskedStoreToScalarStore(), ShrinkLoadReplaceStoreWithStore(), splitStoreSplat(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
isDereferenceable()
bool MachinePointerInfo::isDereferenceable (unsigned Size, LLVMContext & C, const DataLayout & DL) const
Return true if memory region [V, V+Offset+Size) is known to be dereferenceable.
isDereferenceable - Return true if V is always dereferenceable for Offset + Size byte.
Definition at line 1041 of file MachineOperand.cpp.
References Align, llvm::cast(), DL, llvm::isa(), llvm::isDereferenceableAndAlignedPointer(), Offset, and Size.
Referenced by EltsFromConsecutiveLoads(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), and llvm::AMDGPUTargetLowering::WidenOrSplitVectorLoad().
Member Data Documentation
AddrSpace
unsigned llvm::MachinePointerInfo::AddrSpace = 0
Definition at line 48 of file MachineMemOperand.h.
Referenced by getAddrSpace(), getWithOffset(), MachinePointerInfo(), MachinePointerInfo(), and MachinePointerInfo().
Offset
int64_t llvm::MachinePointerInfo::Offset
Offset - This is an offset from the base Value*.
Definition at line 46 of file MachineMemOperand.h.
Referenced by getFixedStack(), getStack(), getWithOffset(), llvm::inferAlignFromPtrInfo(), and isDereferenceable().
StackID
uint8_t llvm::MachinePointerInfo::StackID
Definition at line 50 of file MachineMemOperand.h.
Referenced by getWithOffset().
V
PointerUnion<const Value *, const PseudoSourceValue *> llvm::MachinePointerInfo::V
This is the IR pointer value for the access, or it is null if unknown.
Definition at line 43 of file MachineMemOperand.h.
Referenced by llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getLoadVP(), llvm::MachineFunction::getMachineMemOperand(), getMemcpyLoadsAndStores(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), llvm::SelectionDAG::getTruncStoreVP(), llvm::inferAlignFromPtrInfo(), and llvm::MachineMemOperand::MachineMemOperand().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/MachineMemOperand.h
lib/CodeGen/MachineOperand.cpp