LLVM: llvm::AMDGPU::MCKernelDescriptor Struct Reference
llvm::AMDGPU::MCKernelDescriptor Struct Reference
#include "Target/AMDGPU/MCTargetDesc/AMDGPUMCKernelDescriptor.h"
Static Public Member Functions
static MCKernelDescriptor getDefaultAmdhsaKernelDescriptor (const MCSubtargetInfo *STI, MCContext &Ctx)
static void bits_set (const MCExpr *&Dst, const MCExpr *Value, uint32_t Shift, uint32_t Mask, MCContext &Ctx)
static const MCExpr * bits_get (const MCExpr *Src, uint32_t Shift, uint32_t Mask, MCContext &Ctx)
Public Attributes
const MCExpr * group_segment_fixed_size = nullptr
const MCExpr * private_segment_fixed_size = nullptr
const MCExpr * kernarg_size = nullptr
const MCExpr * compute_pgm_rsrc3 = nullptr
const MCExpr * compute_pgm_rsrc1 = nullptr
const MCExpr * compute_pgm_rsrc2 = nullptr
const MCExpr * kernel_code_properties = nullptr
const MCExpr * kernarg_preload = nullptr
Detailed Description
Definition at line 27 of file AMDGPUMCKernelDescriptor.h.
Member Function Documentation
bits_get()
const MCExpr * MCKernelDescriptor::bits_get (const MCExpr * Src, uint32_t Shift, uint32_t Mask, MCContext & Ctx) static
Definition at line 92 of file AMDGPUMCKernelDescriptor.cpp.
References llvm::MCConstantExpr::create(), llvm::MCBinaryExpr::createAnd(), and llvm::MCBinaryExpr::createLShr().
Referenced by llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
bits_set()
void MCKernelDescriptor::bits_set (const MCExpr *& Dst, const MCExpr * Value, uint32_t Shift, uint32_t Mask, MCContext & Ctx) static
Definition at line 82 of file AMDGPUMCKernelDescriptor.cpp.
References llvm::MCConstantExpr::create(), llvm::MCBinaryExpr::createAnd(), llvm::MCUnaryExpr::createNot(), llvm::MCBinaryExpr::createOr(), and llvm::MCBinaryExpr::createShl().
Referenced by getDefaultAmdhsaKernelDescriptor().
getDefaultAmdhsaKernelDescriptor()
MCKernelDescriptor MCKernelDescriptor::getDefaultAmdhsaKernelDescriptor (const MCSubtargetInfo * STI, MCContext & Ctx) static
Definition at line 21 of file AMDGPUMCKernelDescriptor.cpp.
References bits_set(), compute_pgm_rsrc1, compute_pgm_rsrc2, compute_pgm_rsrc3, llvm::MCConstantExpr::create(), llvm::amdhsa::FLOAT_DENORM_MODE_FLUSH_NONE, llvm::MCSubtargetInfo::getCPU(), llvm::MCSubtargetInfo::getFeatureBits(), llvm::AMDGPU::getIsaVersion(), group_segment_fixed_size, llvm::AMDGPU::isGFX90A(), kernarg_preload, kernarg_size, kernel_code_properties, private_segment_fixed_size, and llvm::FeatureBitset::test().
Member Data Documentation
compute_pgm_rsrc1
const MCExpr* llvm::AMDGPU::MCKernelDescriptor::compute_pgm_rsrc1 = nullptr
Definition at line 32 of file AMDGPUMCKernelDescriptor.h.
Referenced by llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), and getDefaultAmdhsaKernelDescriptor().
compute_pgm_rsrc2
const MCExpr* llvm::AMDGPU::MCKernelDescriptor::compute_pgm_rsrc2 = nullptr
Definition at line 33 of file AMDGPUMCKernelDescriptor.h.
Referenced by llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), and getDefaultAmdhsaKernelDescriptor().
compute_pgm_rsrc3
const MCExpr* llvm::AMDGPU::MCKernelDescriptor::compute_pgm_rsrc3 = nullptr
Definition at line 31 of file AMDGPUMCKernelDescriptor.h.
Referenced by llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), and getDefaultAmdhsaKernelDescriptor().
group_segment_fixed_size
const MCExpr* llvm::AMDGPU::MCKernelDescriptor::group_segment_fixed_size = nullptr
Definition at line 28 of file AMDGPUMCKernelDescriptor.h.
Referenced by llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), and getDefaultAmdhsaKernelDescriptor().
kernarg_preload
const MCExpr* llvm::AMDGPU::MCKernelDescriptor::kernarg_preload = nullptr
Definition at line 35 of file AMDGPUMCKernelDescriptor.h.
Referenced by llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), and getDefaultAmdhsaKernelDescriptor().
kernarg_size
const MCExpr* llvm::AMDGPU::MCKernelDescriptor::kernarg_size = nullptr
Definition at line 30 of file AMDGPUMCKernelDescriptor.h.
Referenced by llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), and getDefaultAmdhsaKernelDescriptor().
kernel_code_properties
const MCExpr* llvm::AMDGPU::MCKernelDescriptor::kernel_code_properties = nullptr
Definition at line 34 of file AMDGPUMCKernelDescriptor.h.
Referenced by llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), and getDefaultAmdhsaKernelDescriptor().
private_segment_fixed_size
const MCExpr* llvm::AMDGPU::MCKernelDescriptor::private_segment_fixed_size = nullptr
Definition at line 29 of file AMDGPUMCKernelDescriptor.h.
Referenced by llvm::AMDGPUTargetAsmStreamer::EmitAmdhsaKernelDescriptor(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), and getDefaultAmdhsaKernelDescriptor().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/MCTargetDesc/AMDGPUMCKernelDescriptor.h
lib/Target/AMDGPU/MCTargetDesc/AMDGPUMCKernelDescriptor.cpp