LLVM: llvm::ImutContainerInfo< T > Struct Template Reference
llvm::ImutContainerInfo< T > Struct Template Reference
ImutContainerInfo - Generic definition of comparison operations for elements of immutable containers that defaults to using std::equal_to<> and std::less<> to perform comparison of elements.
#include "llvm/ADT/ImmutableSet.h"
Public Types
using value_type = typename ImutProfileInfo<T>::value_type
using value_type_ref = typename ImutProfileInfo<T>::value_type_ref
using key_type = value_type
using key_type_ref = value_type_ref
using data_type = bool
using data_type_ref = bool
Public Types inherited from llvm::ImutProfileInfo< T >
using value_type = const T
using value_type_ref = const T&
Static Public Member Functions
static key_type_ref KeyOfValue (value_type_ref D)
static data_type_ref DataOfValue (value_type_ref)
static bool isEqual (key_type_ref LHS, key_type_ref RHS)
static bool isLess (key_type_ref LHS, key_type_ref RHS)
static bool isDataEqual (data_type_ref, data_type_ref)
Static Public Member Functions inherited from llvm::ImutProfileInfo< T >
static void Profile (FoldingSetNodeID &ID, value_type_ref X)
Detailed Description
template<typename T>
struct llvm::ImutContainerInfo< T >
ImutContainerInfo - Generic definition of comparison operations for elements of immutable containers that defaults to using std::equal_to<> and std::less<> to perform comparison of elements.
Definition at line 908 of file ImmutableSet.h.
Member Typedef Documentation
data_type
template<typename T > using llvm::ImutContainerInfo< T >::data_type = bool
Definition at line 913 of file ImmutableSet.h.
data_type_ref
template<typename T > using llvm::ImutContainerInfo< T >::data_type_ref = bool
Definition at line 914 of file ImmutableSet.h.
key_type
template<typename T > using llvm::ImutContainerInfo< T >::key_type = value_type
Definition at line 911 of file ImmutableSet.h.
key_type_ref
template<typename T > using llvm::ImutContainerInfo< T >::key_type_ref = value_type_ref
Definition at line 912 of file ImmutableSet.h.
value_type
template<typename T > using llvm::ImutContainerInfo< T >::value_type = typename ImutProfileInfo<T>::value_type
Definition at line 909 of file ImmutableSet.h.
value_type_ref
template<typename T > using llvm::ImutContainerInfo< T >::value_type_ref = typename ImutProfileInfo<T>::value_type_ref
Definition at line 910 of file ImmutableSet.h.
Member Function Documentation
DataOfValue()
template<typename T > static data_type_ref llvm::ImutContainerInfo< T >::DataOfValue (value_type_ref) inline static
Definition at line 917 of file ImmutableSet.h.
isDataEqual()
template<typename T > static bool llvm::ImutContainerInfo< T >::isDataEqual (data_type_ref , data_type_ref) inline static
Definition at line 927 of file ImmutableSet.h.
isEqual()
template<typename T > static bool llvm::ImutContainerInfo< T >::isEqual (key_type_ref LHS, key_type_ref RHS) inline static
Definition at line 919 of file ImmutableSet.h.
References LHS, and RHS.
Referenced by llvm::ImutKeyValueInfo< T, S >::isDataEqual(), and llvm::ImutKeyValueInfo< T, S >::isEqual().
isLess()
template<typename T > static bool llvm::ImutContainerInfo< T >::isLess (key_type_ref LHS, key_type_ref RHS) inline static
Definition at line 923 of file ImmutableSet.h.
References LHS, and RHS.
Referenced by llvm::ImutKeyValueInfo< T, S >::isLess().
KeyOfValue()
template<typename T > static key_type_ref llvm::ImutContainerInfo< T >::KeyOfValue (value_type_ref D) inline static
Definition at line 916 of file ImmutableSet.h.
References D.
The documentation for this struct was generated from the following file:
include/llvm/ADT/ImmutableSet.h