LLVM: llvm::PseudoProbeDwarfDiscriminator Struct Reference
llvm::PseudoProbeDwarfDiscriminator Struct Reference
#include "llvm/IR/PseudoProbe.h"
Static Public Member Functions
static uint32_t packProbeData (uint32_t Index, uint32_t Type, uint32_t Flags, uint32_t Factor, std::optional< uint32_t > DwarfBaseDiscriminator)
static uint32_t extractProbeIndex (uint32_t Value)
static std::optional< uint32_t > extractDwarfBaseDiscriminator (uint32_t Value)
static bool isDwarfBaseDiscriminatorEncoded (uint32_t Value)
static uint32_t extractProbeType (uint32_t Value)
static uint32_t extractProbeAttributes (uint32_t Value)
static uint32_t extractProbeFactor (uint32_t Value)
Static Public Attributes
static constexpr uint8_t FullDistributionFactor = 100
Detailed Description
Definition at line 41 of file PseudoProbe.h.
Member Function Documentation
extractDwarfBaseDiscriminator()
static std::optional< uint32_t > llvm::PseudoProbeDwarfDiscriminator::extractDwarfBaseDiscriminator (uint32_t Value) inline static
Definition at line 80 of file PseudoProbe.h.
References isDwarfBaseDiscriminatorEncoded().
Referenced by llvm::DILocation::getBaseDiscriminatorFromDiscriminator(), and llvm::setProbeDistributionFactor().
extractProbeAttributes()
static uint32_t llvm::PseudoProbeDwarfDiscriminator::extractProbeAttributes (uint32_t Value) inline static
Definition at line 94 of file PseudoProbe.h.
Referenced by llvm::extractProbeFromDiscriminator(), and llvm::setProbeDistributionFactor().
extractProbeFactor()
static uint32_t llvm::PseudoProbeDwarfDiscriminator::extractProbeFactor (uint32_t Value) inline static
Definition at line 98 of file PseudoProbe.h.
Referenced by llvm::extractProbeFromDiscriminator().
extractProbeIndex()
static uint32_t llvm::PseudoProbeDwarfDiscriminator::extractProbeIndex (uint32_t Value) inline static
Definition at line 74 of file PseudoProbe.h.
References isDwarfBaseDiscriminatorEncoded().
Referenced by llvm::PseudoProbeHandler::emitPseudoProbe(), llvm::extractProbeFromDiscriminator(), llvm::DILocation::getBaseDiscriminatorFromDiscriminator(), llvm::sampleprof::FunctionSamples::getCallSiteIdentifier(), and llvm::setProbeDistributionFactor().
extractProbeType()
static uint32_t llvm::PseudoProbeDwarfDiscriminator::extractProbeType (uint32_t Value) inline static
Definition at line 90 of file PseudoProbe.h.
Referenced by llvm::extractProbeFromDiscriminator(), and llvm::setProbeDistributionFactor().
isDwarfBaseDiscriminatorEncoded()
static bool llvm::PseudoProbeDwarfDiscriminator::isDwarfBaseDiscriminatorEncoded (uint32_t Value) inline static
Definition at line 86 of file PseudoProbe.h.
Referenced by extractDwarfBaseDiscriminator(), and extractProbeIndex().
packProbeData()
static uint32_t llvm::PseudoProbeDwarfDiscriminator::packProbeData (uint32_t Index, uint32_t Type, uint32_t Flags, uint32_t Factor, std::optional< uint32_t > DwarfBaseDiscriminator) inline static
Definition at line 56 of file PseudoProbe.h.
References assert().
Referenced by llvm::SampleProfileProber::instrumentOneFunc(), and llvm::setProbeDistributionFactor().
Member Data Documentation
FullDistributionFactor
uint8_t llvm::PseudoProbeDwarfDiscriminator::FullDistributionFactor = 100 static constexpr
Definition at line 103 of file PseudoProbe.h.
Referenced by llvm::extractProbeFromDiscriminator(), llvm::SampleProfileProber::instrumentOneFunc(), and llvm::setProbeDistributionFactor().
The documentation for this struct was generated from the following file:
include/llvm/IR/PseudoProbe.h