LLVM: llvm::memprof::IndexedAllocationInfo Struct Reference
llvm::memprof::IndexedAllocationInfo Struct Reference
#include "llvm/ProfileData/MemProf.h"
Public Member Functions
IndexedAllocationInfo ()=default
IndexedAllocationInfo (ArrayRef< FrameId > CS, CallStackId CSId, const MemInfoBlock &MB, const MemProfSchema &Schema=getFullSchema())
size_t serializedSize (const MemProfSchema &Schema, IndexedVersion Version) const
bool operator== (const IndexedAllocationInfo &Other) const
bool operator!= (const IndexedAllocationInfo &Other) const
Public Attributes
llvm::SmallVector< FrameId > CallStack
CallStackId CSId = 0
PortableMemInfoBlock Info
Detailed Description
Definition at line 340 of file MemProf.h.
Constructor & Destructor Documentation
IndexedAllocationInfo() [1/2]
llvm::memprof::IndexedAllocationInfo::IndexedAllocationInfo () default
IndexedAllocationInfo() [2/2]
llvm::memprof::IndexedAllocationInfo::IndexedAllocationInfo (ArrayRef< FrameId > CS, CallStackId CSId, const MemInfoBlock & MB, const MemProfSchema & Schema = getFullSchema()) inline
Definition at line 352 of file MemProf.h.
Member Function Documentation
operator!=()
bool llvm::memprof::IndexedAllocationInfo::operator!= (const IndexedAllocationInfo & Other) const inline
Definition at line 370 of file MemProf.h.
References operator==(), and llvm::Other.
operator==()
bool llvm::memprof::IndexedAllocationInfo::operator== (const IndexedAllocationInfo & Other) const inline
Definition at line 361 of file MemProf.h.
References CSId, and llvm::Other.
Referenced by operator!=().
serializedSize()
size_t llvm::memprof::IndexedAllocationInfo::serializedSize (const MemProfSchema & Schema, IndexedVersion Version) const
Definition at line 58 of file MemProf.cpp.
References llvm_unreachable, llvm::memprof::serializedSizeV0(), llvm::memprof::serializedSizeV2(), llvm::memprof::serializedSizeV3(), llvm::memprof::Version0, llvm::memprof::Version1, llvm::memprof::Version2, and llvm::memprof::Version3.
Member Data Documentation
CallStack
llvm::SmallVector<FrameId> llvm::memprof::IndexedAllocationInfo::CallStack
Definition at line 344 of file MemProf.h.
Referenced by llvm::memprof::AllocationInfo::AllocationInfo(), and llvm::memprof::serializedSizeV0().
CSId
CallStackId llvm::memprof::IndexedAllocationInfo::CSId = 0
Definition at line 347 of file MemProf.h.
Referenced by operator==().
Info
PortableMemInfoBlock llvm::memprof::IndexedAllocationInfo::Info
Definition at line 349 of file MemProf.h.
Referenced by llvm::memprof::AllocationInfo::AllocationInfo().
The documentation for this struct was generated from the following files:
include/llvm/ProfileData/MemProf.h
lib/ProfileData/MemProf.cpp