LLVM: llvm::PatternMatch::specific_intval< AllowPoison > Struct Template Reference
llvm::PatternMatch::specific_intval< AllowPoison > Struct Template Reference
Match a specified integer value or vector of all elements of that value.
#include "llvm/IR/PatternMatch.h"
Public Member Functions
specific_intval (const APInt &V)
template<typename ITy >
bool match (ITy *V)
Public Attributes
const APInt & Val
Detailed Description
template<bool AllowPoison>
struct llvm::PatternMatch::specific_intval< AllowPoison >
Match a specified integer value or vector of all elements of that value.
Definition at line 940 of file PatternMatch.h.
Constructor & Destructor Documentation
specific_intval()
template<bool AllowPoison> llvm::PatternMatch::specific_intval< AllowPoison >::specific_intval (const APInt & V) inline
Definition at line 943 of file PatternMatch.h.
Member Function Documentation
match()
template<bool AllowPoison> template<typename ITy > bool llvm::PatternMatch::specific_intval< AllowPoison >::match (ITy * V) inline
Definition at line 945 of file PatternMatch.h.
References llvm::CallingConv::C, llvm::dyn_cast(), llvm::dyn_cast_or_null(), llvm::APInt::isSameValue(), and llvm::PatternMatch::specific_intval< AllowPoison >::Val.
Member Data Documentation
Val
template<bool AllowPoison> const APInt& llvm::PatternMatch::specific_intval< AllowPoison >::Val
Definition at line 941 of file PatternMatch.h.
Referenced by llvm::PatternMatch::specific_intval< AllowPoison >::match().
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h