LLVM: llvm::AADereferenceable Struct Reference
llvm::AADereferenceable Struct Reference
An abstract interface for all dereferenceable attribute.
#include "llvm/Transforms/IPO/Attributor.h"
Public Member Functions
AADereferenceable (const IRPosition &IRP, Attributor &A)
bool isAssumedGlobal () const
Return true if we assume that underlying value is dereferenceable(_or_null) globally.
bool isKnownGlobal () const
Return true if we know that underlying value is dereferenceable(_or_null) globally.
uint32_t getAssumedDereferenceableBytes () const
Return assumed dereferenceable bytes.
uint32_t getKnownDereferenceableBytes () const
Return known dereferenceable bytes.
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::IRAttribute< Attribute::Dereferenceable, StateWrapper< DerefState, AbstractAttribute >, AADereferenceable >
IRAttribute (const IRPosition &IRP)
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
Attribute::AttrKind getAttrKind () const
Return the kind that identifies the abstract attribute implementation.
virtual void getDeducedAttributes (Attributor &A, LLVMContext &Ctx, SmallVectorImpl< Attribute > &Attrs) const
Return the deduced attributes in Attrs.
Public Member Functions inherited from llvm::StateWrapper< DerefState, AbstractAttribute >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (const IRPosition &IRP)
virtual ~AbstractAttribute ()=default
Virtual destructor.
virtual void initialize (Attributor &A)
Initialize the state with the information in the Attributor A.
virtual bool isQueryAA () const
A query AA is always scheduled as long as we do updates because it does lazy computation that cannot be determined to be done from the outside.
const IRPosition & getIRPosition () const
Return an IR position, see struct IRPosition.
IRPosition & getIRPosition ()
void print (raw_ostream &OS) const
Helper functions, for debug purposes only.
void print (Attributor *, raw_ostream &OS) const override
virtual void printWithDeps (raw_ostream &OS) const
void dump () const
virtual const std::string getAsStr (Attributor *A) const =0
This function should return the "summarized" assumed state as string.
Public Member Functions inherited from llvm::IRPosition
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
bool isFunctionScope () const
Return true if this is a function or call site position.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getCalleeArgNo () const
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
int getCallSiteArgNo () const
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Value * getAttrListAnchor () const
Return the value attributes are attached to.
AttributeList getAttrList () const
Return the attributes associated with this function or call site scope.
void setAttrList (const AttributeList &AttrList) const
Update the attributes associated with this function or call site scope.
unsigned getNumArgs () const
Return the number of arguments associated with this function or call site scope.
Value * getArg (unsigned ArgNo) const
Return theargument ArgNo associated with this function or call site scope.
Kind getPositionKind () const
Return the associated position kind.
bool isAnyCallSitePosition () const
bool isArgumentPosition () const
Return true if the position is an argument or call site argument.
IRPosition stripCallBaseContext () const
Return the same position without the call base context.
const CallBaseContext * getCallBaseContext () const
Get the call base context from the position.
bool hasCallBaseContext () const
Check if the position has any call base context.
operator void * () const
}
Public Member Functions inherited from llvm::AADepGraphNode
virtual ~AADepGraphNode ()=default
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
void print (raw_ostream &OS) const
DepSetTy & getDeps ()
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
virtual bool isValidState () const =0
Return if this abstract state is in a valid state.
virtual bool isAtFixpoint () const =0
Return if this abstract state is fixed, thus does not need to be updated if information changes as it cannot change itself.
virtual ChangeStatus indicateOptimisticFixpoint ()=0
Indicate that the abstract state should converge to the optimistic state.
virtual ChangeStatus indicatePessimisticFixpoint ()=0
Indicate that the abstract state should converge to the pessimistic state.
Static Public Member Functions
static bool isValidIRPositionForInit (Attributor &A, const IRPosition &IRP)
See AbstractAttribute::isValidIRPositionForInit.
static AADereferenceable & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AADereferenceable.
Static Public Member Functions inherited from llvm::IRAttribute< Attribute::Dereferenceable, StateWrapper< DerefState, AbstractAttribute >, AADereferenceable >
static bool hasTrivialInitializer ()
Most boolean IRAttribute AAs don't do anything non-trivial in their initializers while non-boolean ones often do.
static bool isImpliedByUndef ()
Return true if the IR attribute(s) associated with this AA are implied for an undef value.
static bool isImpliedByPoison ()
Return true if the IR attribute(s) associated with this AA are implied for an poison value.
static bool isImpliedByIR (Attributor &A, const IRPosition &IRP, Attribute::AttrKind ImpliedAttributeKind=AK, bool IgnoreSubsumingPositions=false)
Static Public Member Functions inherited from llvm::AbstractAttribute
static bool classof (const AADepGraphNode *DGN)
This function is used to identify if an DGN is of type AbstractAttribute so that the dyn_cast and cast can use such information to cast an AADepGraphNode to an AbstractAttribute.
static bool hasTrivialInitializer ()
Return false if this AA does anything non-trivial (hence not done by default) in its initializer.
static bool requiresCalleeForCallBase ()
Return true if this AA requires a "callee" (or an associted function) for a call site positon.
static bool requiresNonAsmForCallBase ()
Return true if this AA requires non-asm "callee" for a call site positon.
static bool requiresCallersForArgOrFunction ()
Return true if this AA requires all callees for an argument or function positon.
static bool isValidIRPositionForInit (Attributor &A, const IRPosition &IRP)
Return false if an AA should not be created for IRP.
static bool isValidIRPositionForUpdate (Attributor &A, const IRPosition &IRP)
Return false if an AA should not be updated for IRP.
Static Public Member Functions inherited from llvm::IRPosition
static const IRPosition value (const Value &V, const CallBaseContext *CBContext=nullptr)
Create a position describing the value of V.
static const IRPosition inst (const Instruction &I, const CallBaseContext *CBContext=nullptr)
Create a position describing the instruction I.
static const IRPosition function (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg, const CallBaseContext *CBContext=nullptr)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP, const CallBaseContext *CBContext=nullptr)
Create a position with function scope matching the "context" of IRP.
Static Public Member Functions inherited from llvm::DerefState
static DerefState getBestState ()
static DerefState getBestState (const DerefState &)
static DerefState getWorstState ()
Return the worst possible representable state.
static DerefState getWorstState (const DerefState &)
Static Public Attributes
static const char ID = 0
Unique ID (due to the unique address)
Static Public Attributes inherited from llvm::IRAttribute< Attribute::Dereferenceable, StateWrapper< DerefState, AbstractAttribute >, AADereferenceable >
static constexpr Attribute::AttrKind IRAttributeKind
Compile time access to the IR attribute kind.
Static Public Attributes inherited from llvm::AbstractAttribute
static constexpr Attribute::AttrKind IRAttributeKind = Attribute::None
Compile time access to the IR attribute kind.
Static Public Attributes inherited from llvm::IRPosition
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Additional Inherited Members
Public Types inherited from llvm::StateWrapper< DerefState, AbstractAttribute >
using StateType
Provide static access to the type of the state.
Public Types inherited from llvm::AbstractAttribute
using StateType = AbstractState
Public Types inherited from llvm::IRPosition
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
using CallBaseContext = CallBase
Public Types inherited from llvm::AADepGraphNode
using DepTy = PointerIntPair<AADepGraphNode *, 1>
using DepSetTy = SmallSetVector<DepTy, 2>
using iterator = mapped_iterator<DepSetTy::iterator, decltype(&DepGetVal)>
using aaiterator
Public Attributes inherited from llvm::DerefState
IncIntegerState DerefBytesState
State representing for dereferenceable bytes.
std::map< int64_t, uint64_t > AccessedBytesMap
Map representing for accessed memory offsets and sizes.
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
virtual void trackStatistics () const =0
Hook to enable custom statistic tracking, called after manifest that resulted in a change if statistics are enabled.
virtual ChangeStatus updateImpl (Attributor &A)=0
The actual update/transfer function which has to be implemented by the derived classes.
Protected Member Functions inherited from llvm::AADepGraphNode
operator AbstractAttribute * ()
Static Protected Member Functions inherited from llvm::AADepGraphNode
static AADepGraphNode * DepGetVal (const DepTy &DT)
static AbstractAttribute * DepGetValAA (const DepTy &DT)
Protected Attributes inherited from llvm::AADepGraphNode
DepSetTy Deps
Set of dependency graph nodes which should be updated if this one is updated.
Detailed Description
An abstract interface for all dereferenceable attribute.
Definition at line 4206 of file Attributor.h.
Constructor & Destructor Documentation
AADereferenceable()
llvm::AADereferenceable::AADereferenceable (const IRPosition & IRP, Attributor & A) inline
Definition at line 4210 of file Attributor.h.
Member Function Documentation
classof()
static bool llvm::AADereferenceable::classof (const AbstractAttribute * AA) inline static
This function should return true if the type of the AA is AADereferenceable.
Definition at line 4249 of file Attributor.h.
References llvm::AbstractAttribute::getIdAddr().
createForPosition()
static AADereferenceable & llvm::AADereferenceable::createForPosition (const IRPosition & IRP, Attributor & A) static
Create an abstract attribute view for the position IRP.
getAssumedDereferenceableBytes()
uint32_t llvm::AADereferenceable::getAssumedDereferenceableBytes () const inline
Return assumed dereferenceable bytes.
Definition at line 4228 of file Attributor.h.
References llvm::DerefState::DerefBytesState, and llvm::IntegerStateBase< base_ty, BestState, WorstState >::getAssumed().
getIdAddr()
const char * llvm::AADereferenceable::getIdAddr () const inline override virtual
See AbstractAttribute::getIdAddr()
Implements llvm::AbstractAttribute.
Definition at line 4245 of file Attributor.h.
References ID.
getKnownDereferenceableBytes()
uint32_t llvm::AADereferenceable::getKnownDereferenceableBytes () const inline
Return known dereferenceable bytes.
Definition at line 4233 of file Attributor.h.
References llvm::DerefState::DerefBytesState, and llvm::IntegerStateBase< base_ty, BestState, WorstState >::getKnown().
getName()
const std::string llvm::AADereferenceable::getName () const inline override virtual
See AbstractAttribute::getName()
Implements llvm::AbstractAttribute.
Definition at line 4242 of file Attributor.h.
isAssumedGlobal()
bool llvm::AADereferenceable::isAssumedGlobal () const inline
Return true if we assume that underlying value is dereferenceable(_or_null) globally.
Definition at line 4221 of file Attributor.h.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::getAssumed().
isKnownGlobal()
bool llvm::AADereferenceable::isKnownGlobal () const inline
Return true if we know that underlying value is dereferenceable(_or_null) globally.
Definition at line 4225 of file Attributor.h.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::getKnown().
isValidIRPositionForInit()
static bool llvm::AADereferenceable::isValidIRPositionForInit (Attributor & A, const IRPosition & IRP) inline static
See AbstractAttribute::isValidIRPositionForInit.
Definition at line 4213 of file Attributor.h.
References A, llvm::IRPosition::getAssociatedType(), and llvm::Type::isPtrOrPtrVectorTy().
Member Data Documentation
ID
const char AADereferenceable::ID = 0 static
Unique ID (due to the unique address)
Definition at line 4254 of file Attributor.h.
Referenced by getIdAddr().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/AttributorAttributes.cpp