LLVM: llvm::WasmEHFuncInfo Struct Reference
llvm::WasmEHFuncInfo Struct Reference
#include "llvm/CodeGen/WasmEHFuncInfo.h"
Public Member Functions
const BasicBlock * getUnwindDest (const BasicBlock *BB) const
SmallPtrSet< const BasicBlock *, 4 > getUnwindSrcs (const BasicBlock *BB) const
void setUnwindDest (const BasicBlock *BB, const BasicBlock *Dest)
bool hasUnwindDest (const BasicBlock *BB) const
bool hasUnwindSrcs (const BasicBlock *BB) const
MachineBasicBlock * getUnwindDest (MachineBasicBlock *MBB) const
SmallPtrSet< MachineBasicBlock *, 4 > getUnwindSrcs (MachineBasicBlock *MBB) const
void setUnwindDest (MachineBasicBlock *MBB, MachineBasicBlock *Dest)
bool hasUnwindDest (MachineBasicBlock *MBB) const
bool hasUnwindSrcs (MachineBasicBlock *MBB) const
Public Attributes
DenseMap< BBOrMBB, BBOrMBB > SrcToUnwindDest
DenseMap< BBOrMBB, SmallPtrSet< BBOrMBB, 4 > > UnwindDestToSrcs
Detailed Description
Definition at line 32 of file WasmEHFuncInfo.h.
Member Function Documentation
getUnwindDest() [1/2]
const BasicBlock * llvm::WasmEHFuncInfo::getUnwindDest (const BasicBlock * BB) const inline
Definition at line 39 of file WasmEHFuncInfo.h.
References assert(), llvm::cast(), hasUnwindDest(), and SrcToUnwindDest.
getUnwindDest() [2/2]
MachineBasicBlock * llvm::WasmEHFuncInfo::getUnwindDest (MachineBasicBlock * MBB) const inline
Definition at line 62 of file WasmEHFuncInfo.h.
References assert(), llvm::cast(), hasUnwindDest(), MBB, and SrcToUnwindDest.
getUnwindSrcs() [1/2]
SmallPtrSet< const BasicBlock *, 4 > llvm::WasmEHFuncInfo::getUnwindSrcs (const BasicBlock * BB) const inline
Definition at line 43 of file WasmEHFuncInfo.h.
References assert(), llvm::cast(), hasUnwindSrcs(), P, and UnwindDestToSrcs.
getUnwindSrcs() [2/2]
SmallPtrSet< MachineBasicBlock *, 4 > llvm::WasmEHFuncInfo::getUnwindSrcs (MachineBasicBlock * MBB) const inline
Definition at line 67 of file WasmEHFuncInfo.h.
References assert(), llvm::cast(), hasUnwindSrcs(), MBB, P, and UnwindDestToSrcs.
hasUnwindDest() [1/2]
bool llvm::WasmEHFuncInfo::hasUnwindDest (const BasicBlock * BB) const inline
Definition at line 55 of file WasmEHFuncInfo.h.
References SrcToUnwindDest.
Referenced by getUnwindDest(), and getUnwindDest().
hasUnwindDest() [2/2]
bool llvm::WasmEHFuncInfo::hasUnwindDest (MachineBasicBlock * MBB) const inline
Definition at line 79 of file WasmEHFuncInfo.h.
References MBB, and SrcToUnwindDest.
hasUnwindSrcs() [1/2]
bool llvm::WasmEHFuncInfo::hasUnwindSrcs (const BasicBlock * BB) const inline
Definition at line 58 of file WasmEHFuncInfo.h.
References UnwindDestToSrcs.
Referenced by getUnwindSrcs(), and getUnwindSrcs().
hasUnwindSrcs() [2/2]
bool llvm::WasmEHFuncInfo::hasUnwindSrcs (MachineBasicBlock * MBB) const inline
Definition at line 82 of file WasmEHFuncInfo.h.
References MBB, and UnwindDestToSrcs.
setUnwindDest() [1/2]
void llvm::WasmEHFuncInfo::setUnwindDest (const BasicBlock * BB, const BasicBlock * Dest) inline
Definition at line 51 of file WasmEHFuncInfo.h.
References SrcToUnwindDest, and UnwindDestToSrcs.
Referenced by llvm::calculateWasmEHInfo().
setUnwindDest() [2/2]
void llvm::WasmEHFuncInfo::setUnwindDest (MachineBasicBlock * MBB, MachineBasicBlock * Dest) inline
Definition at line 75 of file WasmEHFuncInfo.h.
References llvm::MachineBasicBlock::insert(), MBB, SrcToUnwindDest, and UnwindDestToSrcs.
Member Data Documentation
SrcToUnwindDest
DenseMap<BBOrMBB, BBOrMBB> llvm::WasmEHFuncInfo::SrcToUnwindDest
Definition at line 35 of file WasmEHFuncInfo.h.
Referenced by getUnwindDest(), getUnwindDest(), hasUnwindDest(), hasUnwindDest(), llvm::FunctionLoweringInfo::set(), setUnwindDest(), and setUnwindDest().
UnwindDestToSrcs
DenseMap<BBOrMBB, SmallPtrSet<BBOrMBB, 4> > llvm::WasmEHFuncInfo::UnwindDestToSrcs
Definition at line 36 of file WasmEHFuncInfo.h.
Referenced by getUnwindSrcs(), getUnwindSrcs(), hasUnwindSrcs(), hasUnwindSrcs(), llvm::FunctionLoweringInfo::set(), setUnwindDest(), and setUnwindDest().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/WasmEHFuncInfo.h