LLVM: llvm::objcopy::macho::SymbolTable Struct Reference
llvm::objcopy::macho::SymbolTable Struct Reference
The location of the symbol table inside the binary is described by LC_SYMTAB load command.
#include "ObjCopy/MachO/MachOObject.h"
Public Types
using iterator
Public Member Functions
iterator begin () const
iterator end () const
const SymbolEntry * getSymbolByIndex (uint32_t Index) const
SymbolEntry * getSymbolByIndex (uint32_t Index)
void removeSymbols (function_ref< bool(const std::unique_ptr< SymbolEntry > &)> ToRemove)
Public Attributes
std::vector< std::unique_ptr< SymbolEntry > > Symbols
Detailed Description
The location of the symbol table inside the binary is described by LC_SYMTAB load command.
Definition at line 134 of file MachOObject.h.
Member Typedef Documentation
iterator
using llvm::objcopy::macho::SymbolTable::iterator
Initial value:
 pointee_iterator<
      std::vector<std::unique_ptr<SymbolEntry>>::const_iterator>
Definition at line 137 of file MachOObject.h.
Member Function Documentation
begin()
iterator llvm::objcopy::macho::SymbolTable::begin () const inline
Definition at line 140 of file MachOObject.h.
References Symbols.
end()
iterator llvm::objcopy::macho::SymbolTable::end () const inline
Definition at line 141 of file MachOObject.h.
References Symbols.
getSymbolByIndex() [1/2]
SymbolEntry * SymbolTable::getSymbolByIndex (uint32_t Index)
Definition at line 31 of file MachOObject.cpp.
References getSymbolByIndex().
getSymbolByIndex() [2/2]
const SymbolEntry * SymbolTable::getSymbolByIndex (uint32_t Index) const
Definition at line 26 of file MachOObject.cpp.
References assert(), and Symbols.
Referenced by getSymbolByIndex().
removeSymbols()
void SymbolTable::removeSymbols (function_ref< bool(const std::unique_ptr< SymbolEntry > &)> ToRemove)
Definition at line 36 of file MachOObject.cpp.
References llvm::erase_if(), Symbols, and ToRemove.
Referenced by llvm::objcopy::macho::Object::removeSections(), and updateAndRemoveSymbols().
Member Data Documentation
Symbols
std::vector<std::unique_ptr<SymbolEntry> > llvm::objcopy::macho::SymbolTable::Symbols
Definition at line 135 of file MachOObject.h.
Referenced by begin(), end(), getSymbolByIndex(), llvm::objcopy::macho::Object::removeSections(), and removeSymbols().
The documentation for this struct was generated from the following files:
lib/ObjCopy/MachO/MachOObject.h
lib/ObjCopy/MachO/MachOObject.cpp