LLVM: llvm::VPlanPatternMatch::VPCanonicalIVPHI_match Struct Reference
llvm::VPlanPatternMatch::VPCanonicalIVPHI_match Struct Reference
#include "Transforms/Vectorize/VPlanPatternMatch.h"
Public Member Functions
bool match (const VPValue *V)
bool match (const VPRecipeBase *R)
Detailed Description
Definition at line 307 of file VPlanPatternMatch.h.
Member Function Documentation
match() [1/2]
bool llvm::VPlanPatternMatch::VPCanonicalIVPHI_match::match (const VPRecipeBase * R) inline
Definition at line 313 of file VPlanPatternMatch.h.
References llvm::isa().
match() [2/2]
bool llvm::VPlanPatternMatch::VPCanonicalIVPHI_match::match (const VPValue * V) inline
Definition at line 308 of file VPlanPatternMatch.h.
References match().
Referenced by match().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlanPatternMatch.h