LLVM: llvm::PAEvalPass Struct Reference
llvm::PAEvalPass Struct Reference
#include "llvm/Transforms/ObjCARC.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< PAEvalPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< PAEvalPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 45 of file ObjCARC.h.
Member Function Documentation
run()
PreservedAnalyses PAEvalPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 33 of file ProvenanceAnalysisEvaluator.cpp.
References llvm::PreservedAnalyses::all(), llvm::errs(), F, getName(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), I, insertIfNamed(), instructions, ProvenanceAnalysis::related(), and ProvenanceAnalysis::setAA().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/ObjCARC.h
lib/Transforms/ObjCARC/ProvenanceAnalysisEvaluator.cpp