LLVM: XtensaOperand Struct Reference
XtensaOperand Struct Reference
Classes
struct ImmOp
struct RegOp
Public Types
enum KindTy { Token , Register , Immediate }
Public Member Functions
XtensaOperand (KindTy K)
XtensaOperand (const XtensaOperand &o)
bool isToken () const override
isToken - Is this a token operand?
bool isReg () const override
isReg - Is this a register operand?
bool isImm () const override
isImm - Is this an immediate operand?
bool isMem () const override
isMem - Is this a memory operand?
bool isImm (int64_t MinValue, int64_t MaxValue) const
bool isImm8 () const
bool isImm8_sh8 () const
bool isImm12 () const
bool isImm12m () const
bool isOffset4m32 () const
bool isOffset8m8 () const
bool isOffset8m16 () const
bool isOffset8m32 () const
bool isUimm4 () const
bool isUimm5 () const
bool isImm8n_7 () const
bool isShimm1_31 () const
bool isImm16_31 () const
bool isImm1_16 () const
bool isB4const () const
bool isB4constu () const
SMLoc getStartLoc () const override
getStartLoc - Gets location of the first token of this operand
SMLoc getEndLoc () const override
getEndLoc - Gets location of the last token of this operand
MCRegister getReg () const override
const MCExpr * getImm () const
StringRef getToken () const
void print (raw_ostream &OS) const override
print - Print a debug representation of the operand to the given stream.
void addExpr (MCInst &Inst, const MCExpr *Expr) const
void addRegOperands (MCInst &Inst, unsigned N) const
void addImmOperands (MCInst &Inst, unsigned N) const
Public Member Functions inherited from llvm::MCParsedAsmOperand
virtual ~MCParsedAsmOperand ()=default
void setConstraint (StringRef C)
StringRef getConstraint ()
void setMCOperandNum (unsigned OpNum)
unsigned getMCOperandNum ()
virtual StringRef getSymName ()
virtual void * getOpDecl ()
virtual bool isMemUseUpRegs () const
isMemUseUpRegs - Is memory operand use up regs, for example, intel MS inline asm may use ARR[baseReg + IndexReg + ...] which may use up regs in [...] expr, so ARR[baseReg + IndexReg + ...] can not use extra reg for ARR.
virtual bool needAddressOf () const
needAddressOf - Do we need to emit code to get the address of the variable/label? Only valid when parsing MS-style inline assembly.
virtual bool isOffsetOfLocal () const
isOffsetOfLocal - Do we need to emit code to get the offset of the local variable, rather than its value? Only valid when parsing MS-style inline assembly.
virtual SMLoc getOffsetOfLoc () const
getOffsetOfLoc - Get the location of the offset operator.
virtual void dump () const
dump - Print to the debug stream.
Static Public Member Functions
static std::unique_ptr< XtensaOperand > createToken (StringRef Str, SMLoc S)
static std::unique_ptr< XtensaOperand > createReg (unsigned RegNo, SMLoc S, SMLoc E)
static std::unique_ptr< XtensaOperand > createImm (const MCExpr *Val, SMLoc S, SMLoc E)
Public Attributes
enum XtensaOperand::KindTy Kind
SMLoc StartLoc
SMLoc EndLoc
union {
StringRef Tok
RegOp Reg
ImmOp Imm
};
Additional Inherited Members
Protected Member Functions inherited from llvm::MCParsedAsmOperand
MCParsedAsmOperand ()=default
MCParsedAsmOperand (const MCParsedAsmOperand &RHS)=default
MCParsedAsmOperand & operator= (const MCParsedAsmOperand &)=default
Detailed Description
Definition at line 103 of file XtensaAsmParser.cpp.
Member Enumeration Documentation
KindTy
enum XtensaOperand::KindTy
Enumerator
Token
Register
Immediate
Definition at line 105 of file XtensaAsmParser.cpp.
Constructor & Destructor Documentation
XtensaOperand() [1/2]
XtensaOperand::XtensaOperand (KindTy K) inline
Definition at line 126 of file XtensaAsmParser.cpp.
XtensaOperand() [2/2]
XtensaOperand::XtensaOperand (const XtensaOperand & o) inline
Definition at line 129 of file XtensaAsmParser.cpp.
References EndLoc, Imm, Immediate, Register, StartLoc, Tok, and Token.
Member Function Documentation
addExpr()
void XtensaOperand::addExpr (MCInst & Inst, const MCExpr * Expr) const inline
Definition at line 317 of file XtensaAsmParser.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createExpr(), llvm::MCOperand::createImm(), llvm::dyn_cast(), and Imm.
Referenced by addImmOperands().
addImmOperands()
void XtensaOperand::addImmOperands (MCInst & Inst, unsigned N) const inline
Definition at line 339 of file XtensaAsmParser.cpp.
References addExpr(), assert(), getImm(), and N.
addRegOperands()
void XtensaOperand::addRegOperands (MCInst & Inst, unsigned N) const inline
Definition at line 334 of file XtensaAsmParser.cpp.
References llvm::MCInst::addOperand(), assert(), llvm::MCOperand::createReg(), getReg(), and N.
createImm()
static std::unique_ptr< XtensaOperand > XtensaOperand::createImm (const MCExpr * Val, SMLoc S, SMLoc E) inline static
Definition at line 308 of file XtensaAsmParser.cpp.
References E.
createReg()
static std::unique_ptr< XtensaOperand > XtensaOperand::createReg (unsigned RegNo, SMLoc S, SMLoc E) inline static
Definition at line 299 of file XtensaAsmParser.cpp.
References E.
createToken()
static std::unique_ptr< XtensaOperand > XtensaOperand::createToken (StringRef Str, SMLoc S) inline static
Definition at line 291 of file XtensaAsmParser.cpp.
References Token.
getEndLoc()
SMLoc XtensaOperand::getEndLoc () const inline override virtual
getEndLoc - Gets location of the last token of this operand
Implements llvm::MCParsedAsmOperand.
Definition at line 259 of file XtensaAsmParser.cpp.
References EndLoc.
getImm()
const MCExpr * XtensaOperand::getImm () const inline
Definition at line 266 of file XtensaAsmParser.cpp.
References assert(), Imm, and XtensaOperand::ImmOp::Val.
Referenced by addImmOperands(), isB4const(), isB4constu(), isImm(), isImm8_sh8(), isOffset4m32(), isOffset8m16(), isOffset8m32(), and print().
getReg()
MCRegister XtensaOperand::getReg () const inline override virtual
Implements llvm::MCParsedAsmOperand.
Definition at line 261 of file XtensaAsmParser.cpp.
References assert().
Referenced by addRegOperands(), and print().
getStartLoc()
SMLoc XtensaOperand::getStartLoc () const inline override virtual
getStartLoc - Gets location of the first token of this operand
Implements llvm::MCParsedAsmOperand.
Definition at line 257 of file XtensaAsmParser.cpp.
References StartLoc.
getToken()
StringRef XtensaOperand::getToken () const inline
Definition at line 271 of file XtensaAsmParser.cpp.
References assert(), Tok, and Token.
Referenced by print().
isB4const()
bool XtensaOperand::isB4const () const inline
Definition at line 196 of file XtensaAsmParser.cpp.
References llvm::dyn_cast(), and getImm().
isB4constu()
bool XtensaOperand::isB4constu () const inline
Definition at line 226 of file XtensaAsmParser.cpp.
References llvm::dyn_cast(), and getImm().
isImm() [1/2]
bool XtensaOperand::isImm () const inline override virtual
isImm - Is this an immediate operand?
Implements llvm::MCParsedAsmOperand.
Definition at line 148 of file XtensaAsmParser.cpp.
References Immediate.
Referenced by isImm12(), isImm16_31(), isImm1_16(), isImm8(), isImm8_sh8(), isImm8n_7(), isOffset4m32(), isOffset8m16(), isOffset8m32(), isOffset8m8(), isShimm1_31(), isUimm4(), and isUimm5().
isImm() [2/2]
bool XtensaOperand::isImm (int64_t MinValue, int64_t MaxValue) const inline
Definition at line 151 of file XtensaAsmParser.cpp.
References getImm(), and inRange().
isImm12()
bool XtensaOperand::isImm12 () const inline
Definition at line 162 of file XtensaAsmParser.cpp.
References isImm().
isImm12m()
bool XtensaOperand::isImm12m () const inline
Definition at line 165 of file XtensaAsmParser.cpp.
References Immediate.
isImm16_31()
bool XtensaOperand::isImm16_31 () const inline
Definition at line 192 of file XtensaAsmParser.cpp.
References isImm().
isImm1_16()
bool XtensaOperand::isImm1_16 () const inline
Definition at line 194 of file XtensaAsmParser.cpp.
References isImm().
isImm8()
bool XtensaOperand::isImm8 () const inline
Definition at line 155 of file XtensaAsmParser.cpp.
References isImm().
isImm8_sh8()
bool XtensaOperand::isImm8_sh8 () const inline
Definition at line 157 of file XtensaAsmParser.cpp.
References llvm::cast(), getImm(), and isImm().
isImm8n_7()
bool XtensaOperand::isImm8n_7 () const inline
Definition at line 188 of file XtensaAsmParser.cpp.
References isImm().
isMem()
bool XtensaOperand::isMem () const inline override virtual
isMem - Is this a memory operand?
Implements llvm::MCParsedAsmOperand.
Definition at line 149 of file XtensaAsmParser.cpp.
isOffset4m32()
bool XtensaOperand::isOffset4m32 () const inline
Definition at line 167 of file XtensaAsmParser.cpp.
References llvm::cast(), getImm(), and isImm().
isOffset8m16()
bool XtensaOperand::isOffset8m16 () const inline
Definition at line 174 of file XtensaAsmParser.cpp.
References llvm::cast(), getImm(), and isImm().
isOffset8m32()
bool XtensaOperand::isOffset8m32 () const inline
Definition at line 179 of file XtensaAsmParser.cpp.
References llvm::cast(), getImm(), and isImm().
isOffset8m8()
bool XtensaOperand::isOffset8m8 () const inline
Definition at line 172 of file XtensaAsmParser.cpp.
References isImm().
isReg()
bool XtensaOperand::isReg () const inline override virtual
isReg - Is this a register operand?
Implements llvm::MCParsedAsmOperand.
Definition at line 147 of file XtensaAsmParser.cpp.
References Register.
isShimm1_31()
bool XtensaOperand::isShimm1_31 () const inline
Definition at line 190 of file XtensaAsmParser.cpp.
References isImm().
isToken()
bool XtensaOperand::isToken () const inline override virtual
isToken - Is this a token operand?
Implements llvm::MCParsedAsmOperand.
Definition at line 146 of file XtensaAsmParser.cpp.
References Token.
isUimm4()
bool XtensaOperand::isUimm4 () const inline
Definition at line 184 of file XtensaAsmParser.cpp.
References isImm().
isUimm5()
bool XtensaOperand::isUimm5 () const inline
Definition at line 186 of file XtensaAsmParser.cpp.
References isImm().
print()
void XtensaOperand::print (raw_ostream & OS) const inline override virtual
print - Print a debug representation of the operand to the given stream.
Implements llvm::MCParsedAsmOperand.
Definition at line 276 of file XtensaAsmParser.cpp.
References getImm(), getReg(), getToken(), Immediate, OS, Register, and Token.
Member Data Documentation
[union]
union { ... } XtensaOperand
EndLoc
SMLoc XtensaOperand::EndLoc
Definition at line 119 of file XtensaAsmParser.cpp.
Referenced by getEndLoc(), and XtensaOperand().
Imm
ImmOp XtensaOperand::Imm
Definition at line 123 of file XtensaAsmParser.cpp.
Referenced by addExpr(), getImm(), and XtensaOperand().
Kind
enum XtensaOperand::KindTy XtensaOperand::Kind
Reg
RegOp XtensaOperand::Reg
Definition at line 122 of file XtensaAsmParser.cpp.
StartLoc
SMLoc XtensaOperand::StartLoc
Definition at line 119 of file XtensaAsmParser.cpp.
Referenced by getStartLoc(), and XtensaOperand().
Tok
StringRef XtensaOperand::Tok
Definition at line 121 of file XtensaAsmParser.cpp.
Referenced by getToken(), and XtensaOperand().
The documentation for this struct was generated from the following file:
lib/Target/Xtensa/AsmParser/XtensaAsmParser.cpp