LLVM: llvm::AMDGPU::EncodingFields< Fields > Struct Template Reference
llvm::AMDGPU::EncodingFields< Fields > Struct Template Reference
#include "Target/AMDGPU/Utils/AMDGPUBaseInfo.h"
Static Public Member Functions
static constexpr uint64_t encode (Fields... Values)
static std::tuple< typename Fields::ValueType... > decode (uint64_t Encoded)
Detailed Description
template<typename... Fields>
struct llvm::AMDGPU::EncodingFields< Fields >
Definition at line 368 of file AMDGPUBaseInfo.h.
Member Function Documentation
decode()
template<typename... Fields> static std::tuple< typename Fields::ValueType... > llvm::AMDGPU::EncodingFields< Fields >::decode (uint64_t Encoded) inline static
Definition at line 373 of file AMDGPUBaseInfo.h.
References llvm::maxUIntN().
Referenced by llvm::SITargetLowering::EmitInstrWithCustomInserter(), and getHWReg().
encode()
template<typename... Fields> static constexpr uint64_t llvm::AMDGPU::EncodingFields< Fields >::encode (Fields... Values) inline static constexpr
Definition at line 369 of file AMDGPUBaseInfo.h.
Referenced by llvm::SITargetLowering::emitGWSMemViolTestLoop(), llvm::SITargetLowering::lowerGET_FPENV(), llvm::SITargetLowering::lowerGET_ROUNDING(), llvm::SITargetLowering::lowerSET_FPENV(), and llvm::SITargetLowering::lowerSET_ROUNDING().
The documentation for this struct was generated from the following file:
lib/Target/AMDGPU/Utils/AMDGPUBaseInfo.h