LLVM: llvm::NumericalStabilitySanitizerPass Struct Reference
llvm::NumericalStabilitySanitizerPass Struct Reference
A function pass for nsan instrumentation.
#include "llvm/Transforms/Instrumentation/NumericalStabilitySanitizer.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< NumericalStabilitySanitizerPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< NumericalStabilitySanitizerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A function pass for nsan instrumentation.
Instruments functions to duplicate floating point computations in a higher-precision type. This pass inserts calls to runtime library functions. If the functions aren't declared yet, the pass inserts the declarations.
Definition at line 28 of file NumericalStabilitySanitizer.h.
Member Function Documentation
isRequired()
static bool llvm::NumericalStabilitySanitizerPass::isRequired () inline static
Definition at line 31 of file NumericalStabilitySanitizer.h.
run()
PreservedAnalyses NumericalStabilitySanitizerPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 576 of file NumericalStabilitySanitizer.cpp.
References llvm::appendToGlobalCtors(), F, FAM, llvm::getOrCreateSanitizerCtorAndInitFunctions(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), kNsanInitName(), kNsanModuleCtorName(), MAM, and llvm::PreservedAnalyses::none().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Instrumentation/NumericalStabilitySanitizer.h
lib/Transforms/Instrumentation/NumericalStabilitySanitizer.cpp