LLVM: llvm::VPlanPatternMatch::UnaryRecipe_match< Op0_t, Opcode, RecipeTys > Struct Template Reference
llvm::VPlanPatternMatch::UnaryRecipe_match< Op0_t, Opcode, RecipeTys > Struct Template Reference
#include "Transforms/Vectorize/VPlanPatternMatch.h"
Public Member Functions
UnaryRecipe_match (Op0_t Op0)
bool match (const VPValue *V)
bool match (const VPRecipeBase *R)
Public Attributes
Op0_t Op0
Detailed Description
template<typename Op0_t, unsigned Opcode, typename... RecipeTys>
struct llvm::VPlanPatternMatch::UnaryRecipe_match< Op0_t, Opcode, RecipeTys >
Definition at line 132 of file VPlanPatternMatch.h.
Constructor & Destructor Documentation
UnaryRecipe_match()
template<typename Op0_t , unsigned Opcode, typename... RecipeTys> llvm::VPlanPatternMatch::UnaryRecipe_match< Op0_t, Opcode, RecipeTys >::UnaryRecipe_match (Op0_t Op0) inline
Definition at line 135 of file VPlanPatternMatch.h.
Member Function Documentation
match() [1/2]
template<typename Op0_t , unsigned Opcode, typename... RecipeTys> bool llvm::VPlanPatternMatch::UnaryRecipe_match< Op0_t, Opcode, RecipeTys >::match (const VPRecipeBase * R) inline
Definition at line 142 of file VPlanPatternMatch.h.
References assert(), and llvm::VPlanPatternMatch::UnaryRecipe_match< Op0_t, Opcode, RecipeTys >::Op0.
match() [2/2]
template<typename Op0_t , unsigned Opcode, typename... RecipeTys> bool llvm::VPlanPatternMatch::UnaryRecipe_match< Op0_t, Opcode, RecipeTys >::match (const VPValue * V) inline
Definition at line 137 of file VPlanPatternMatch.h.
References llvm::VPlanPatternMatch::UnaryRecipe_match< Op0_t, Opcode, RecipeTys >::match().
Referenced by llvm::VPlanPatternMatch::UnaryRecipe_match< Op0_t, Opcode, RecipeTys >::match().
Member Data Documentation
Op0
template<typename Op0_t , unsigned Opcode, typename... RecipeTys> Op0_t llvm::VPlanPatternMatch::UnaryRecipe_match< Op0_t, Opcode, RecipeTys >::Op0
Definition at line 133 of file VPlanPatternMatch.h.
Referenced by llvm::VPlanPatternMatch::UnaryRecipe_match< Op0_t, Opcode, RecipeTys >::match().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlanPatternMatch.h