LLVM: llvm::ConstantExprKeyType Struct Reference
llvm::ConstantExprKeyType Struct Reference
#include "IR/ConstantsContext.h"
Public Types
using TypeClass = ConstantInfo<ConstantExpr>::TypeClass
Public Member Functions
ConstantExprKeyType (unsigned Opcode, ArrayRef< Constant * > Ops, unsigned short SubclassOptionalData=0, ArrayRef< int > ShuffleMask=std::nullopt, Type *ExplicitTy=nullptr, std::optional< ConstantRange > InRange=std::nullopt)
ConstantExprKeyType (ArrayRef< Constant * > Operands, const ConstantExpr *CE)
ConstantExprKeyType (const ConstantExpr *CE, SmallVectorImpl< Constant * > &Storage)
bool operator== (const ConstantExprKeyType &X) const
bool operator== (const ConstantExpr *CE) const
unsigned getHash () const
ConstantExpr * create (TypeClass *Ty) const
Static Public Member Functions
static bool rangesEqual (const std::optional< ConstantRange > &A, const std::optional< ConstantRange > &B)
Detailed Description
Definition at line 376 of file ConstantsContext.h.
Member Typedef Documentation
TypeClass
using llvm::ConstantExprKeyType::TypeClass = ConstantInfo<ConstantExpr>::TypeClass
Definition at line 474 of file ConstantsContext.h.
Constructor & Destructor Documentation
ConstantExprKeyType() [1/3]
llvm::ConstantExprKeyType::ConstantExprKeyType (unsigned Opcode, ArrayRef< Constant * > Ops, unsigned short SubclassOptionalData = 0, ArrayRef< int > ShuffleMask = std::nullopt, Type * ExplicitTy = nullptr, std::optional< ConstantRange > InRange = std::nullopt) inline
Definition at line 405 of file ConstantsContext.h.
ConstantExprKeyType() [2/3]
llvm::ConstantExprKeyType::ConstantExprKeyType (ArrayRef< Constant * > Operands, const ConstantExpr * CE) inline
Definition at line 414 of file ConstantsContext.h.
ConstantExprKeyType() [3/3]
llvm::ConstantExprKeyType::ConstantExprKeyType (const ConstantExpr * CE, SmallVectorImpl< Constant * > & Storage) inline
Definition at line 421 of file ConstantsContext.h.
References assert(), llvm::SmallVectorBase< Size_T >::empty(), I, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Member Function Documentation
create()
ConstantExpr * llvm::ConstantExprKeyType::create (TypeClass * Ty) const inline
Definition at line 476 of file ConstantsContext.h.
References llvm::GetElementPtrConstantExpr::Create(), llvm::Instruction::isCast(), llvm_unreachable, and llvm::ArrayRef< T >::slice().
getHash()
unsigned llvm::ConstantExprKeyType::getHash () const inline
Definition at line 467 of file ConstantsContext.h.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::hash_combine(), and llvm::hash_combine_range().
operator==() [1/2]
bool llvm::ConstantExprKeyType::operator== (const ConstantExpr * CE) const inline
Definition at line 448 of file ConstantsContext.h.
References I, rangesEqual(), and llvm::ArrayRef< T >::size().
operator==() [2/2]
bool llvm::ConstantExprKeyType::operator== (const ConstantExprKeyType & X) const inline
Definition at line 441 of file ConstantsContext.h.
References rangesEqual(), and X.
rangesEqual()
static bool llvm::ConstantExprKeyType::rangesEqual (const std::optional< ConstantRange > & A, const std::optional< ConstantRange > & B) inline static
Definition at line 434 of file ConstantsContext.h.
References A, and B.
Referenced by operator==(), and operator==().
The documentation for this struct was generated from the following file:
lib/IR/ConstantsContext.h