LLVM: llvm::rdf::Liveness Struct Reference
llvm::rdf::Liveness Struct Reference
#include "llvm/CodeGen/RDFLiveness.h"
Public Types
using LiveMapType = RegisterAggrMap<MachineBasicBlock *>
using NodeRef = detail::NodeRef
using NodeRefSet = std::unordered_set<NodeRef>
using RefMap = std::unordered_map<RegisterId, NodeRefSet>
Public Member Functions
Liveness (MachineRegisterInfo &mri, const DataFlowGraph &g)
NodeList getAllReachingDefs (RegisterRef RefRR, NodeAddr< RefNode * > RefA, bool TopShadows, bool FullChain, const RegisterAggr &DefRRs)
NodeList getAllReachingDefs (NodeAddr< RefNode * > RefA)
NodeList getAllReachingDefs (RegisterRef RefRR, NodeAddr< RefNode * > RefA)
NodeSet getAllReachedUses (RegisterRef RefRR, NodeAddr< DefNode * > DefA, const RegisterAggr &DefRRs)
NodeSet getAllReachedUses (RegisterRef RefRR, NodeAddr< DefNode * > DefA)
std::pair< NodeSet, bool > getAllReachingDefsRec (RegisterRef RefRR, NodeAddr< RefNode * > RefA, NodeSet &Visited, const NodeSet &Defs)
NodeAddr< RefNode * > getNearestAliasedRef (RegisterRef RefRR, NodeAddr< InstrNode * > IA)
Find the nearest ref node aliased to RefRR, going upwards in the data flow, starting from the instruction immediately preceding Inst.
LiveMapType & getLiveMap ()
const LiveMapType & getLiveMap () const
const RefMap & getRealUses (NodeId P) const
void computePhiInfo ()
void computeLiveIns ()
void resetLiveIns ()
void resetKills ()
void resetKills (MachineBasicBlock *B)
void trace (bool T)
Detailed Description
Definition at line 55 of file RDFLiveness.h.
Member Typedef Documentation
LiveMapType
using llvm::rdf::Liveness::LiveMapType = RegisterAggrMap<MachineBasicBlock *>
Definition at line 57 of file RDFLiveness.h.
NodeRef
using llvm::rdf::Liveness::NodeRef = detail::NodeRef
Definition at line 58 of file RDFLiveness.h.
NodeRefSet
using llvm::rdf::Liveness::NodeRefSet = std::unordered_set<NodeRef>
Definition at line 59 of file RDFLiveness.h.
RefMap
using llvm::rdf::Liveness::RefMap = std::unordered_map<RegisterId, NodeRefSet>
Definition at line 60 of file RDFLiveness.h.
Constructor & Destructor Documentation
Liveness()
llvm::rdf::Liveness::Liveness (MachineRegisterInfo & mri, const DataFlowGraph & g) inline
Definition at line 62 of file RDFLiveness.h.
Member Function Documentation
computeLiveIns()
void llvm::rdf::Liveness::computeLiveIns ()
Definition at line 743 of file RDFLiveness.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::DataFlowGraph::addr(), B, llvm::SetVector< T, Vector, Set, N >::begin(), Blocks, computePhiInfo(), D, llvm::dbgs(), llvm::MachineDominanceFrontier::end(), llvm::SetVector< T, Vector, Set, N >::end(), llvm::MachineDominanceFrontier::find(), llvm::MachineFunction::front(), getAllReachingDefs(), llvm::rdf::DataFlowGraph::getFunc(), llvm::rdf::DataFlowGraph::getLiveIns(), llvm::rdf::DataFlowGraph::getMF(), llvm::rdf::DataFlowGraph::getRelatedRefs(), I, llvm::SetVector< T, Vector, Set, N >::insert(), llvm::rdf::DataFlowGraph::IsCode(), llvm::rdf::DataFlowGraph::IsRef(), llvm::rdf::CodeNode::members(), P, llvm::rdf::NodeAttrs::Phi, llvm::rdf::Print(), llvm::printMBBReference(), RA, llvm::rdf::RegisterRef::Reg, llvm::SetVector< T, Vector, Set, N >::size(), llvm::sort(), TM, and llvm::rdf::NodeAttrs::Use.
computePhiInfo()
void llvm::rdf::Liveness::computePhiInfo ()
Definition at line 460 of file RDFLiveness.cpp.
References A, llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::DataFlowGraph::addr(), llvm::append_range(), assert(), Blocks, Changed, llvm::rdf::RegisterAggr::clearIn(), D, llvm::dbgs(), llvm::rdf::NodeAttrs::Dead, llvm::rdf::NodeAttrs::Def, F, getAllReachingDefs(), llvm::rdf::DataFlowGraph::getFunc(), llvm::rdf::DataFlowGraph::getRelatedRefs(), llvm::rdf::RegisterAggr::hasAliasOf(), llvm::rdf::RegisterAggr::hasCoverOf(), I, llvm::rdf::NodeAddr< T >::Id, llvm::rdf::RegisterAggr::insert(), llvm::SetVector< T, Vector, Set, N >::insert(), llvm::rdf::RegisterAggr::intersectWith(), llvm::rdf::DataFlowGraph::IsCode(), IsDead, llvm::rdf::DataFlowGraph::IsRef(), llvm::rdf::PhysicalRegisterInfo::mapTo(), llvm::rdf::RegisterRef::Mask, P, llvm::rdf::NodeAttrs::Phi, llvm::rdf::NodeAttrs::PhiRef, llvm::rdf::Print(), llvm::SetVector< T, Vector, Set, N >::size(), llvm::rdf::NodeAttrs::Undef, llvm::rdf::NodeAttrs::Use, and Uses.
Referenced by computeLiveIns().
getAllReachedUses() [1/2]
NodeSet llvm::rdf::Liveness::getAllReachedUses (RegisterRef RefRR, NodeAddr< DefNode * > DefA) inline
Definition at line 82 of file RDFLiveness.h.
References getAllReachedUses().
getAllReachedUses() [2/2]
NodeSet llvm::rdf::Liveness::getAllReachedUses (RegisterRef RefRR, NodeAddr< DefNode * > DefA, const RegisterAggr & DefRRs)
Definition at line 414 of file RDFLiveness.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::DataFlowGraph::addr(), llvm::rdf::PhysicalRegisterInfo::alias(), D, llvm::rdf::NodeAttrs::Dead, getAllReachedUses(), llvm::rdf::RefNode::getSibling(), llvm::rdf::RegisterAggr::hasCoverOf(), llvm::rdf::RegisterAggr::insert(), IsDead, llvm::rdf::DataFlowGraph::IsPreservingDef(), T, llvm::rdf::NodeAttrs::Undef, and Uses.
Referenced by getAllReachedUses(), and getAllReachedUses().
getAllReachingDefs() [1/3]
NodeList llvm::rdf::Liveness::getAllReachingDefs (NodeAddr< RefNode * > RefA) inline
Definition at line 70 of file RDFLiveness.h.
References llvm::rdf::NodeAddr< T >::Addr, and getAllReachingDefs().
getAllReachingDefs() [2/3]
NodeList llvm::rdf::Liveness::getAllReachingDefs (RegisterRef RefRR, NodeAddr< RefNode * > RefA) inline
Definition at line 75 of file RDFLiveness.h.
References getAllReachingDefs().
getAllReachingDefs() [3/3]
NodeList llvm::rdf::Liveness::getAllReachingDefs (RegisterRef RefRR, NodeAddr< RefNode * > RefA, bool TopShadows, bool FullChain, const RegisterAggr & DefRRs)
Definition at line 104 of file RDFLiveness.cpp.
References A, Addr, llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::DataFlowGraph::addr(), llvm::rdf::PhysicalRegisterInfo::alias(), llvm::append_range(), assert(), B, llvm::MachineBasicBlock::begin(), Blocks, llvm::SmallSet< T, N, C >::count(), llvm::rdf::NodeAttrs::Dead, llvm::rdf::NodeAttrs::Def, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::MachineBasicBlock::end(), llvm::erase_if(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineInstr::getParent(), llvm::rdf::DataFlowGraph::getRelatedRefs(), llvm::rdf::RegisterAggr::hasCoverOf(), llvm::rdf::NodeAddr< T >::Id, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::rdf::RegisterAggr::insert(), llvm::SetVector< T, Vector, Set, N >::insert(), llvm::SmallSet< T, N, C >::insert(), llvm::rdf::DataFlowGraph::IsCode(), llvm::rdf::RegisterAggr::isCoverOf(), llvm::rdf::DataFlowGraph::IsPreservingDef(), llvm_unreachable, MBB, N, llvm::rdf::NodeAttrs::Phi, llvm::rdf::NodeAttrs::PhiRef, llvm::rdf::NodeAttrs::Preserving, llvm::MachineDominatorTree::properlyDominates(), llvm::reverse(), llvm::SetVector< T, Vector, Set, N >::size(), llvm::sort(), llvm::rdf::NodeAttrs::Stmt, T, and llvm::rdf::NodeAttrs::Undef.
Referenced by computeLiveIns(), computePhiInfo(), getAllReachingDefs(), and getAllReachingDefs().
getAllReachingDefsRec()
std::pair< NodeSet, bool > llvm::rdf::Liveness::getAllReachingDefsRec (RegisterRef RefRR, NodeAddr< RefNode * > RefA, NodeSet & Visited, const NodeSet & Defs)
Definition at line 304 of file RDFLiveness.cpp.
References MaxRecNest.
getLiveMap() [1/2]
LiveMapType & llvm::rdf::Liveness::getLiveMap () inline
Definition at line 94 of file RDFLiveness.h.
getLiveMap() [2/2]
const LiveMapType & llvm::rdf::Liveness::getLiveMap () const inline
Definition at line 95 of file RDFLiveness.h.
getNearestAliasedRef()
NodeAddr< RefNode * > llvm::rdf::Liveness::getNearestAliasedRef (RegisterRef RefRR, NodeAddr< InstrNode * > IA)
Find the nearest ref node aliased to RefRR, going upwards in the data flow, starting from the instruction immediately preceding Inst.
Definition at line 357 of file RDFLiveness.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::PhysicalRegisterInfo::alias(), B, llvm::rdf::NodeAttrs::Clobbering, llvm::rdf::DataFlowGraph::findBlock(), llvm::MachineDominatorTree::getNode(), I, llvm::rdf::NodeAddr< T >::Id, llvm::rdf::DataFlowGraph::IsDef(), llvm::make_range(), and N.
getRealUses()
const RefMap & llvm::rdf::Liveness::getRealUses (NodeId P) const inline
Definition at line 97 of file RDFLiveness.h.
References F, and P.
resetKills() [1/2]
void llvm::rdf::Liveness::resetKills ()
Definition at line 910 of file RDFLiveness.cpp.
References B, llvm::rdf::DataFlowGraph::getMF(), and resetKills().
Referenced by resetKills().
resetKills() [2/2]
void llvm::rdf::Liveness::resetKills (MachineBasicBlock * B)
Definition at line 915 of file RDFLiveness.cpp.
References B, llvm::MCRegisterInfo::getNumRegs(), llvm::MCSubRegIndexIterator::getSubReg(), llvm::MCSubRegIndexIterator::getSubRegIndex(), llvm::TargetRegisterInfo::getSubRegIndexLaneMask(), I, llvm::MCRegAliasIterator::isValid(), llvm::MCSubRegIndexIterator::isValid(), MI, llvm::BitVector::reset(), llvm::reverse(), llvm::BitVector::set(), and llvm::MCRegisterInfo::subregs_inclusive().
resetLiveIns()
void llvm::rdf::Liveness::resetLiveIns ()
Definition at line 895 of file RDFLiveness.cpp.
References B, llvm::rdf::DataFlowGraph::getMF(), I, llvm::rdf::RegisterAggr::refs(), and T.
trace()
void llvm::rdf::Liveness::trace (bool T) inline
Definition at line 108 of file RDFLiveness.h.
References T.
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFLiveness.h
lib/CodeGen/RDFLiveness.cpp