LLVM: llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys > Struct Template Reference
llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys > Struct Template Reference
#include "Transforms/Vectorize/VPlanPatternMatch.h"
Public Member Functions
BinaryRecipe_match (Op0_t Op0, Op1_t Op1)
bool match (const VPValue *V)
bool match (const VPSingleDefRecipe *R)
bool match (const VPRecipeBase *R)
Public Attributes
Op0_t Op0
Op1_t Op1
Detailed Description
template<typename Op0_t, typename Op1_t, unsigned Opcode, bool Commutative, typename... RecipeTys>
struct llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >
Definition at line 162 of file VPlanPatternMatch.h.
Constructor & Destructor Documentation
BinaryRecipe_match()
template<typename Op0_t , typename Op1_t , unsigned Opcode, bool Commutative, typename... RecipeTys> llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::BinaryRecipe_match (Op0_t Op0, Op1_t Op1) inline
Definition at line 166 of file VPlanPatternMatch.h.
Member Function Documentation
match() [1/3]
template<typename Op0_t , typename Op1_t , unsigned Opcode, bool Commutative, typename... RecipeTys> bool llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::match (const VPRecipeBase * R) inline
Definition at line 177 of file VPlanPatternMatch.h.
References assert(), llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::Op0, and llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::Op1.
match() [2/3]
template<typename Op0_t , typename Op1_t , unsigned Opcode, bool Commutative, typename... RecipeTys> bool llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::match (const VPSingleDefRecipe * R) inline
Definition at line 173 of file VPlanPatternMatch.h.
References llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::match().
match() [3/3]
template<typename Op0_t , typename Op1_t , unsigned Opcode, bool Commutative, typename... RecipeTys> bool llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::match (const VPValue * V) inline
Definition at line 168 of file VPlanPatternMatch.h.
References llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::match().
Referenced by llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::match(), and llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::match().
Member Data Documentation
Op0
template<typename Op0_t , typename Op1_t , unsigned Opcode, bool Commutative, typename... RecipeTys> Op0_t llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::Op0
Definition at line 163 of file VPlanPatternMatch.h.
Referenced by llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::match().
Op1
template<typename Op0_t , typename Op1_t , unsigned Opcode, bool Commutative, typename... RecipeTys> Op1_t llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::Op1
Definition at line 164 of file VPlanPatternMatch.h.
Referenced by llvm::VPlanPatternMatch::BinaryRecipe_match< Op0_t, Op1_t, Opcode, Commutative, RecipeTys >::match().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlanPatternMatch.h