LLVM: tomp::ConstructCompositionT< ClauseType > Struct Template Reference
tomp::ConstructCompositionT< ClauseType > Struct Template Reference
#include "llvm/Frontend/OpenMP/ConstructCompositionT.h"
Public Types
using ClauseTy = ClauseType
using TypeTy = typename ClauseTy::TypeTy
using IdTy = typename ClauseTy::IdTy
using ExprTy = typename ClauseTy::ExprTy
Public Member Functions
ConstructCompositionT (uint32_t version, llvm::ArrayRef< DirectiveWithClauses< ClauseTy > > leafs)
Public Attributes
DirectiveWithClauses< ClauseTy > merged
Detailed Description
template<typename ClauseType>
struct tomp::ConstructCompositionT< ClauseType >
Definition at line 33 of file ConstructCompositionT.h.
Member Typedef Documentation
ClauseTy
template<typename ClauseType > using tomp::ConstructCompositionT< ClauseType >::ClauseTy = ClauseType
Definition at line 34 of file ConstructCompositionT.h.
ExprTy
template<typename ClauseType > using tomp::ConstructCompositionT< ClauseType >::ExprTy = typename ClauseTy::ExprTy
Definition at line 38 of file ConstructCompositionT.h.
IdTy
template<typename ClauseType > using tomp::ConstructCompositionT< ClauseType >::IdTy = typename ClauseTy::IdTy
Definition at line 37 of file ConstructCompositionT.h.
TypeTy
template<typename ClauseType > using tomp::ConstructCompositionT< ClauseType >::TypeTy = typename ClauseTy::TypeTy
Definition at line 36 of file ConstructCompositionT.h.
Constructor & Destructor Documentation
ConstructCompositionT()
template<typename ClauseType > tomp::ConstructCompositionT< C >::ConstructCompositionT (uint32_t version, llvm::ArrayRef< DirectiveWithClauses< ClauseTy > > leafs)
Definition at line 85 of file ConstructCompositionT.h.
References llvm::append_range(), clauses, tomp::DirectiveWithClauses< ClauseType >::clauses, llvm::enumerate(), tomp::DirectiveWithClauses< ClauseType >::id, llvm::is_contained(), and tomp::ConstructCompositionT< ClauseType >::merged.
Member Data Documentation
merged
template<typename ClauseType > DirectiveWithClauses<ClauseTy> tomp::ConstructCompositionT< ClauseType >::merged
Definition at line 43 of file ConstructCompositionT.h.
Referenced by tomp::ConstructCompositionT< ClauseType >::ConstructCompositionT().
The documentation for this struct was generated from the following file:
include/llvm/Frontend/OpenMP/ConstructCompositionT.h