LLVM: llvm::rdf::TargetOperandInfo Struct Reference
llvm::rdf::TargetOperandInfo Struct Reference
#include "llvm/CodeGen/RDFGraph.h"
Public Member Functions
TargetOperandInfo (const TargetInstrInfo &tii)
virtual ~TargetOperandInfo ()=default
virtual bool isPreserving (const MachineInstr &In, unsigned OpNum) const
virtual bool isClobbering (const MachineInstr &In, unsigned OpNum) const
virtual bool isFixedReg (const MachineInstr &In, unsigned OpNum) const
Public Attributes
const TargetInstrInfo & TII
Detailed Description
Definition at line 452 of file RDFGraph.h.
Constructor & Destructor Documentation
TargetOperandInfo()
llvm::rdf::TargetOperandInfo::TargetOperandInfo (const TargetInstrInfo & tii) inline
Definition at line 453 of file RDFGraph.h.
~TargetOperandInfo()
virtual llvm::rdf::TargetOperandInfo::~TargetOperandInfo () virtual default
Member Function Documentation
isClobbering()
bool llvm::rdf::TargetOperandInfo::isClobbering (const MachineInstr & In, unsigned OpNum) const virtual
Definition at line 595 of file RDFGraph.cpp.
References assert().
isFixedReg()
bool llvm::rdf::TargetOperandInfo::isFixedReg (const MachineInstr & In, unsigned OpNum) const virtual
Definition at line 608 of file RDFGraph.cpp.
References D, and llvm::is_contained().
isPreserving()
bool llvm::rdf::TargetOperandInfo::isPreserving (const MachineInstr & In, unsigned OpNum) const virtual
Definition at line 589 of file RDFGraph.cpp.
References llvm::TargetInstrInfo::isPredicated(), and TII.
Member Data Documentation
TII
const TargetInstrInfo& llvm::rdf::TargetOperandInfo::TII
Definition at line 460 of file RDFGraph.h.
Referenced by isPreserving().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFGraph.h
lib/CodeGen/RDFGraph.cpp