LLVM: llvm::dxbc::PSV::v1::RuntimeInfo Struct Reference
llvm::dxbc::PSV::v1::RuntimeInfo Struct Reference
#include "llvm/BinaryFormat/DXContainer.h"
Public Member Functions
void swapBytes ()
void swapBytes (Triple::EnvironmentType Stage)
Public Member Functions inherited from llvm::dxbc::PSV::v0::RuntimeInfo
void swapBytes ()
void swapBytes (Triple::EnvironmentType Stage)
Public Attributes
uint8_t ShaderStage
uint8_t UsesViewID
GeometryExtraInfo GeomData
uint8_t SigInputElements
uint8_t SigOutputElements
uint8_t SigPatchOrPrimElements
uint8_t SigInputVectors
uint8_t SigOutputVectors [4]
Public Attributes inherited from llvm::dxbc::PSV::v0::RuntimeInfo
PipelinePSVInfo StageInfo
uint32_t MinimumWaveLaneCount
uint32_t MaximumWaveLaneCount
Detailed Description
Definition at line 375 of file DXContainer.h.
Member Function Documentation
swapBytes() [1/2]
void llvm::dxbc::PSV::v1::RuntimeInfo::swapBytes () inline
Definition at line 389 of file DXContainer.h.
Referenced by llvm::dxbc::PSV::v2::RuntimeInfo::swapBytes().
swapBytes() [2/2]
void llvm::dxbc::PSV::v1::RuntimeInfo::swapBytes (Triple::EnvironmentType Stage) inline
Definition at line 393 of file DXContainer.h.
References GeomData, llvm::Triple::Geometry, llvm::dxbc::PSV::v1::GeometryExtraInfo::MaxVertexCount, llvm::sys::swapByteOrder(), and llvm::dxbc::PSV::v0::RuntimeInfo::swapBytes().
Member Data Documentation
GeomData
GeometryExtraInfo llvm::dxbc::PSV::v1::RuntimeInfo::GeomData
Definition at line 378 of file DXContainer.h.
Referenced by swapBytes().
ShaderStage
uint8_t llvm::dxbc::PSV::v1::RuntimeInfo::ShaderStage
Definition at line 376 of file DXContainer.h.
Referenced by llvm::yaml::MappingTraits< DXContainerYAML::PSVInfo >::mapping().
SigInputElements
uint8_t llvm::dxbc::PSV::v1::RuntimeInfo::SigInputElements
Definition at line 381 of file DXContainer.h.
Referenced by llvm::mcdxbc::PSVRuntimeInfo::finalize().
SigInputVectors
uint8_t llvm::dxbc::PSV::v1::RuntimeInfo::SigInputVectors
Definition at line 386 of file DXContainer.h.
SigOutputElements
uint8_t llvm::dxbc::PSV::v1::RuntimeInfo::SigOutputElements
Definition at line 382 of file DXContainer.h.
Referenced by llvm::mcdxbc::PSVRuntimeInfo::finalize().
SigOutputVectors
uint8_t llvm::dxbc::PSV::v1::RuntimeInfo::SigOutputVectors[4]
Definition at line 387 of file DXContainer.h.
SigPatchOrPrimElements
uint8_t llvm::dxbc::PSV::v1::RuntimeInfo::SigPatchOrPrimElements
Definition at line 383 of file DXContainer.h.
Referenced by llvm::mcdxbc::PSVRuntimeInfo::finalize().
UsesViewID
uint8_t llvm::dxbc::PSV::v1::RuntimeInfo::UsesViewID
Definition at line 377 of file DXContainer.h.
Referenced by llvm::yaml::MappingTraits< DXContainerYAML::PSVInfo >::mapping().
The documentation for this struct was generated from the following file:
include/llvm/BinaryFormat/DXContainer.h