LLVM: llvm::ExtraSimpleLoopUnswitchPassManager Struct Reference
llvm::ExtraSimpleLoopUnswitchPassManager Struct Reference
#include "llvm/Transforms/Scalar/SimpleLoopUnswitch.h"
Public Member Functions
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Public Member Functions inherited from llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >
PassManager ()=default
PassManager (PassManager &&Arg)
PassManager & operator= (PassManager &&RHS)
PreservedAnalyses run (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Add either a loop pass or a loop-nest pass to the pass manager.
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
template<typename PassT >
LLVM_ATTRIBUTE_MINSIZE std::enable_if_t< is_detected< HasRunOnLoopT, PassT >::value > addPass (PassT &&Pass)
template<typename PassT >
LLVM_ATTRIBUTE_MINSIZE std::enable_if_t<!is_detected< HasRunOnLoopT, PassT >::value > addPass (PassT &&Pass)
bool isEmpty () const
size_t getNumLoopPasses () const
size_t getNumLoopNestPasses () const
Public Member Functions inherited from llvm::PassInfoMixin< PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > >
static StringRef name ()
Gets the name of the pass we are mixed into.
Additional Inherited Members
Protected Types inherited from llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >
using LoopPassConceptT
using LoopNestPassConceptT
Protected Member Functions inherited from llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >
template<typename IRUnitT , typename PassT >
std::optional< PreservedAnalyses > runSinglePass (IRUnitT &IR, PassT &Pass, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U, PassInstrumentation &PI)
Run either a loop pass or a loop-nest pass.
PreservedAnalyses runWithLoopNestPasses (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
PreservedAnalyses runWithoutLoopNestPasses (Loop &L, LoopAnalysisManager &AM, LoopStandardAnalysisResults &AR, LPMUpdater &U)
Protected Attributes inherited from llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >
BitVector IsLoopNestPass
std::vector< std::unique_ptr< LoopPassConceptT > > LoopPasses
std::vector< std::unique_ptr< LoopNestPassConceptT > > LoopNestPasses
Detailed Description
Definition at line 45 of file SimpleLoopUnswitch.h.
Member Function Documentation
isRequired()
static bool llvm::ExtraSimpleLoopUnswitchPassManager::isRequired () inline static
Definition at line 55 of file SimpleLoopUnswitch.h.
run()
PreservedAnalyses llvm::ExtraSimpleLoopUnswitchPassManager::run (Loop & L, LoopAnalysisManager & AM, LoopStandardAnalysisResults & AR, LPMUpdater & U) inline
Definition at line 46 of file SimpleLoopUnswitch.h.
References llvm::PreservedAnalyses::all(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), and llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::run().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/Scalar/SimpleLoopUnswitch.h