LLVM: llvm::CorrelatedValuePropagationPass Struct Reference
llvm::CorrelatedValuePropagationPass Struct Reference
#include "llvm/Transforms/Scalar/CorrelatedValuePropagation.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< CorrelatedValuePropagationPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< CorrelatedValuePropagationPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 18 of file CorrelatedValuePropagation.h.
Member Function Documentation
run()
PreservedAnalyses CorrelatedValuePropagationPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 1296 of file CorrelatedValuePropagation.cpp.
References llvm::PreservedAnalyses::abandon(), llvm::PreservedAnalyses::all(), assert(), Changed, F, llvm::getBestSimplifyQuery(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserve(), and runImpl().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Scalar/CorrelatedValuePropagation.h
lib/Transforms/Scalar/CorrelatedValuePropagation.cpp