LLVM: llvm::DOTGraphTraits< CallGraphDOTInfo * > Struct Reference
llvm::DOTGraphTraits< CallGraphDOTInfo * > Struct Reference
Public Types
typedef mapped_iterator< CallGraphNode::const_iterator, decltype(&CGGetValuePtr)> nodes_iterator
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (const CallGraphNode *Node, CallGraphDOTInfo *CGInfo)
std::string getEdgeAttributes (const CallGraphNode *Node, nodes_iterator I, CallGraphDOTInfo *CGInfo)
std::string getNodeAttributes (const CallGraphNode *Node, CallGraphDOTInfo *CGInfo)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType >
std::string getNodeLabel (const void *, const GraphType &)
getNodeLabel - Given a node and a pointer to the top level graph, return the label to print in the node.
Static Public Member Functions
static std::string getGraphName (CallGraphDOTInfo *CGInfo)
static bool isNodeHidden (const CallGraphNode *Node, const CallGraphDOTInfo *CGInfo)
static const CallGraphNode * CGGetValuePtr (CallGraphNode::CallRecord P)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType >
static std::string getGraphName (const GraphType &)
getGraphName - Return the label for the graph as a whole.
template<typename GraphType >
static std::string getGraphProperties (const GraphType &)
getGraphProperties - Return any custom properties that should be included in the top level graph structure for dot.
static bool renderGraphFromBottomUp ()
renderGraphFromBottomUp - If this function returns true, the graph is emitted bottom-up instead of top-down.
template<typename GraphType >
static bool isNodeHidden (const void *, const GraphType &)
isNodeHidden - If the function returns true, the given node is not displayed in the graph.
static bool renderNodesUsingHTML ()
template<typename GraphType >
static std::string getNodeIdentifierLabel (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeAttributes (const void *, const GraphType &)
If you want to specify custom node attributes, this is the place to do so.
template<typename EdgeIter , typename GraphType >
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
If you want to override the dot attributes printed for a particular edge, override this method.
template<typename EdgeIter >
static std::string getEdgeSourceLabel (const void *, EdgeIter)
getEdgeSourceLabel - If you want to label the edge source itself, implement this method.
template<typename EdgeIter >
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
edgeTargetsEdgeSource - This method returns true if this outgoing edge should actually target another edge source, not a node.
template<typename EdgeIter >
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
getEdgeTarget - If edgeTargetsEdgeSource returns true, this method is called to determine which outgoing edge of Node is the target of this edge.
static bool hasEdgeDestLabels ()
hasEdgeDestLabels - If this function returns true, the graph is able to provide labels for edge destinations.
static unsigned numEdgeDestLabels (const void *)
numEdgeDestLabels - If hasEdgeDestLabels, this function returns the number of incoming edge labels the given node has.
static std::string getEdgeDestLabel (const void *, unsigned)
getEdgeDestLabel - If hasEdgeDestLabels, this function returns the incoming edge label with the given index in the given node.
template<typename GraphType , typename GraphWriter >
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
addCustomGraphFeatures - If a graph is made up of more than just straight-forward nodes and edges, this is the place to put all of the custom stuff necessary.
Additional Inherited Members
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
Definition at line 143 of file CallPrinter.cpp.
Member Typedef Documentation
nodes_iterator
mapped_iterator<CallGraphNode::const_iterator, decltype(&CGGetValuePtr)> llvm::DOTGraphTraits< CallGraphDOTInfo * >::nodes_iterator
Definition at line 177 of file CallPrinter.cpp.
Constructor & Destructor Documentation
DOTGraphTraits()
llvm::DOTGraphTraits< CallGraphDOTInfo * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 145 of file CallPrinter.cpp.
Member Function Documentation
CGGetValuePtr()
static const CallGraphNode * llvm::DOTGraphTraits< CallGraphDOTInfo * >::CGGetValuePtr (CallGraphNode::CallRecord P) inline static
Definition at line 170 of file CallPrinter.cpp.
References P.
getEdgeAttributes()
std::string llvm::DOTGraphTraits< CallGraphDOTInfo * >::getEdgeAttributes (const CallGraphNode * Node, nodes_iterator I, CallGraphDOTInfo * CGInfo) inline
Definition at line 179 of file CallPrinter.cpp.
References llvm::CallGraphDOTInfo::getMaxFreq(), llvm::getNumOfCalls(), and ShowEdgeWeight.
getGraphName()
static std::string llvm::DOTGraphTraits< CallGraphDOTInfo * >::getGraphName (CallGraphDOTInfo * CGInfo) inline static
Definition at line 147 of file CallPrinter.cpp.
References llvm::CallGraphDOTInfo::getModule(), and llvm::Module::getModuleIdentifier().
getNodeAttributes()
std::string llvm::DOTGraphTraits< CallGraphDOTInfo * >::getNodeAttributes (const CallGraphNode * Node, CallGraphDOTInfo * CGInfo) inline
Definition at line 200 of file CallPrinter.cpp.
References F, freq, llvm::CallGraphDOTInfo::getFreq(), llvm::Function::getFunction(), llvm::getHeatColor(), llvm::CallGraphDOTInfo::getMaxFreq(), and ShowHeatColors.
getNodeLabel()
std::string llvm::DOTGraphTraits< CallGraphDOTInfo * >::getNodeLabel (const CallGraphNode * Node, CallGraphDOTInfo * CGInfo) inline
Definition at line 159 of file CallPrinter.cpp.
References llvm::CallGraphDOTInfo::getCallGraph(), llvm::CallGraph::getCallsExternalNode(), and llvm::CallGraph::getExternalCallingNode().
isNodeHidden()
static bool llvm::DOTGraphTraits< CallGraphDOTInfo * >::isNodeHidden (const CallGraphNode * Node, const CallGraphDOTInfo * CGInfo) inline static
Definition at line 152 of file CallPrinter.cpp.
References CallMultiGraph.
The documentation for this struct was generated from the following file:
lib/Analysis/CallPrinter.cpp