LLVM: llvm::RewriteStatepointsForGC Struct Reference
llvm::RewriteStatepointsForGC Struct Reference
#include "llvm/Transforms/Scalar/RewriteStatepointsForGC.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
bool runOnFunction (Function &F, DominatorTree &, TargetTransformInfo &, const TargetLibraryInfo &)
Public Member Functions inherited from llvm::PassInfoMixin< RewriteStatepointsForGC >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< RewriteStatepointsForGC >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 29 of file RewriteStatepointsForGC.h.
Member Function Documentation
run()
PreservedAnalyses RewriteStatepointsForGC::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 133 of file RewriteStatepointsForGC.cpp.
References llvm::PreservedAnalyses::all(), Changed, F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::preserve(), runOnFunction(), shouldRewriteStatepointsIn(), and stripNonValidData().
runOnFunction()
bool RewriteStatepointsForGC::runOnFunction (Function & F, DominatorTree & DT, TargetTransformInfo & TTI, const TargetLibraryInfo & TLI)
Definition at line 3028 of file RewriteStatepointsForGC.cpp.
References AllowStatepointWithNoDeoptInfo, assert(), B, Call, llvm::callsGCLeafFunction(), llvm::cast(), Cond, llvm::dyn_cast(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::SmallVectorBase< Size_T >::empty(), F, llvm::FoldSingleEntryPHINodes(), llvm::GenericDomTreeUpdater< DerivedT, DomTreeT, PostDomTreeT >::getDomTree(), getNumElements(), llvm::CallBase::hasDeoptState(), I, inlineGetBaseAndOffset(), insertParsePoints(), instructions, llvm::isa(), llvm::DominatorTree::isReachableFromEntry(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::removeUnreachableBlocks(), shouldRewriteStatepointsIn(), and llvm::Splat.
Referenced by run().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Scalar/RewriteStatepointsForGC.h
lib/Transforms/Scalar/RewriteStatepointsForGC.cpp