LLVM: llvm::ilist_detail::SpecificNodeAccess< OptionsT > Struct Template Reference
llvm::ilist_detail::SpecificNodeAccess< OptionsT > Struct Template Reference
#include "llvm/ADT/ilist_node.h"
Protected Types
using pointer = typename OptionsT::pointer
using const_pointer = typename OptionsT::const_pointer
using node_type = ilist_node_impl<OptionsT>
Static Protected Member Functions
static node_type * getNodePtr (pointer N)
static const node_type * getNodePtr (const_pointer N)
static pointer getValuePtr (node_type *N)
static const_pointer getValuePtr (const node_type *N)
Static Protected Member Functions inherited from llvm::ilist_detail::NodeAccess
template<class OptionsT >
static ilist_node_impl< OptionsT > * getNodePtr (typename OptionsT::pointer N)
template<class OptionsT >
static const ilist_node_impl< OptionsT > * getNodePtr (typename OptionsT::const_pointer N)
template<class OptionsT >
static OptionsT::pointer getValuePtr (ilist_node_impl< OptionsT > *N)
template<class OptionsT >
static OptionsT::const_pointer getValuePtr (const ilist_node_impl< OptionsT > *N)
template<class OptionsT >
static ilist_node_impl< OptionsT > * getPrev (ilist_node_impl< OptionsT > &N)
template<class OptionsT >
static ilist_node_impl< OptionsT > * getNext (ilist_node_impl< OptionsT > &N)
template<class OptionsT >
static const ilist_node_impl< OptionsT > * getPrev (const ilist_node_impl< OptionsT > &N)
template<class OptionsT >
static const ilist_node_impl< OptionsT > * getNext (const ilist_node_impl< OptionsT > &N)
Detailed Description
template<class OptionsT>
struct llvm::ilist_detail::SpecificNodeAccess< OptionsT >
Definition at line 275 of file ilist_node.h.
Member Typedef Documentation
const_pointer
template<class OptionsT > using llvm::ilist_detail::SpecificNodeAccess< OptionsT >::const_pointer = typename OptionsT::const_pointer protected
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-19.1.0/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 278 of file ilist_node.h.
node_type
template<class OptionsT > using llvm::ilist_detail::SpecificNodeAccess< OptionsT >::node_type = ilist_node_impl<OptionsT> protected
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-19.1.0/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 279 of file ilist_node.h.
pointer
template<class OptionsT > using llvm::ilist_detail::SpecificNodeAccess< OptionsT >::pointer = typename OptionsT::pointer protected
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-19.1.0/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 277 of file ilist_node.h.
Member Function Documentation
getNodePtr() [1/2]
template<class OptionsT > static const node_type * llvm::ilist_detail::SpecificNodeAccess< OptionsT >::getNodePtr (const_pointer N) inline static protected
Definition at line 285 of file ilist_node.h.
References llvm::ilist_detail::NodeAccess::getNodePtr(), and N.
getNodePtr() [2/2]
template<class OptionsT > static node_type * llvm::ilist_detail::SpecificNodeAccess< OptionsT >::getNodePtr (pointer N) inline static protected
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-19.1.0/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 281 of file ilist_node.h.
References llvm::ilist_detail::NodeAccess::getNodePtr(), and N.
getValuePtr() [1/2]
template<class OptionsT > static const_pointer llvm::ilist_detail::SpecificNodeAccess< OptionsT >::getValuePtr (const node_type * N) inline static protected
Definition at line 293 of file ilist_node.h.
References llvm::ilist_detail::NodeAccess::getValuePtr(), and N.
getValuePtr() [2/2]
template<class OptionsT > static pointer llvm::ilist_detail::SpecificNodeAccess< OptionsT >::getValuePtr (node_type * N) inline static protected
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-19.1.0/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 289 of file ilist_node.h.
References llvm::ilist_detail::NodeAccess::getValuePtr(), and N.
Referenced by llvm::ilist_iterator< OptionsT, IsReverse, IsConst >::operator*(), and llvm::ilist_iterator_w_bits< OptionsT, IsReverse, IsConst >::operator*().
The documentation for this struct was generated from the following file:
include/llvm/ADT/ilist_node.h