LLVM: lib/Target/SystemZ/SystemZTargetMachine.cpp File Reference
SystemZTargetMachine.cpp File Reference
#include "SystemZTargetMachine.h"
#include "MCTargetDesc/SystemZMCTargetDesc.h"
#include "SystemZ.h"
#include "SystemZMachineFunctionInfo.h"
#include "SystemZMachineScheduler.h"
#include "SystemZTargetObjectFile.h"
#include "SystemZTargetTransformInfo.h"
#include "TargetInfo/SystemZTargetInfo.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/CodeGen.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Transforms/Scalar.h"
#include <memory>
#include <optional>
#include <string>
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSystemZTarget ()
static std::string computeDataLayout (const Triple &TT)
static std::unique_ptr< TargetLoweringObjectFile > createTLOF (const Triple &TT)
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM)
static CodeModel::Model getEffectiveSystemZCodeModel (std::optional< CodeModel::Model > CM, Reloc::Model RM, bool JIT)
Variables
static cl::opt< bool > EnableMachineCombinerPass ("systemz-machine-combiner", cl::desc("Enable the machine combiner pass"), cl::init(true), cl::Hidden)
Function Documentation
computeDataLayout()
static std::string computeDataLayout (const Triple & TT) static
Definition at line 53 of file SystemZTargetMachine.cpp.
References llvm::DataLayout::getManglingComponent().
createTLOF()
static std::unique_ptr< TargetLoweringObjectFile > createTLOF (const Triple & TT) static
Definition at line 86 of file SystemZTargetMachine.cpp.
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (std::optional< Reloc::Model > RM) static
Definition at line 95 of file SystemZTargetMachine.cpp.
References llvm::Reloc::DynamicNoPIC, and llvm::Reloc::Static.
getEffectiveSystemZCodeModel()
static CodeModel::Model getEffectiveSystemZCodeModel (std::optional< CodeModel::Model > CM, Reloc::Model RM, bool JIT) static
Definition at line 133 of file SystemZTargetMachine.cpp.
References llvm::CodeModel::Kernel, llvm::CodeModel::Medium, llvm::Reloc::PIC_, llvm::report_fatal_error(), llvm::CodeModel::Small, and llvm::CodeModel::Tiny.
LLVMInitializeSystemZTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSystemZTarget ()
Definition at line 39 of file SystemZTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheSystemZTarget(), llvm::initializeSystemZDAGToDAGISelLegacyPass(), llvm::initializeSystemZElimComparePass(), llvm::initializeSystemZLDCleanupPass(), llvm::initializeSystemZLongBranchPass(), llvm::initializeSystemZPostRewritePass(), llvm::initializeSystemZShortenInstPass(), llvm::initializeSystemZTDCPassPass(), and X.
Variable Documentation
EnableMachineCombinerPass
cl::opt< bool > EnableMachineCombinerPass("systemz-machine-combiner", cl::desc("Enable the machine combiner pass"), cl::init(true), cl::Hidden) ("systemz-machine-combiner" , cl::desc("Enable the machine combiner pass") , cl::init(true) , cl::Hidden) static