LLVM: lib/Analysis/TargetTransformInfo.cpp File Reference
TargetTransformInfo.cpp File Reference
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/LoopIterator.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfoImpl.h"
#include "llvm/IR/CFG.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/CommandLine.h"
#include <optional>
#include <utility>
Macros
#define DEBUG_TYPE "tti"
Variables
static cl::opt< bool > EnableReduxCost ("costmodel-reduxcost", cl::init(false), cl::Hidden, cl::desc("Recognize reduction patterns."))
static cl::opt< unsigned > CacheLineSize ("cache-line-size", cl::init(0), cl::Hidden, cl::desc("Use this to override the target cache line size when " "specified by the user."))
static cl::opt< unsigned > MinPageSize ("min-page-size", cl::init(0), cl::Hidden, cl::desc("Use this to override the target's minimum page size."))
static cl::opt< unsigned > PredictableBranchThreshold ("predictable-branch-threshold", cl::init(99), cl::Hidden, cl::desc("Use this to override the target's predictable branch threshold (%)."))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "tti"
Definition at line 30 of file TargetTransformInfo.cpp.
Variable Documentation
CacheLineSize
cl::opt< unsigned > CacheLineSize("cache-line-size", cl::init(0), cl::Hidden, cl::desc("Use this to override the target cache line size when " "specified by the user.")) ("cache-line-size" , cl::init(0) , cl::Hidden , cl::desc("Use this to override the target cache line size when " "specified by the user.")) static
Referenced by llvm::IndexedReference::computeRefCost(), llvm::AMDGPUTargetAsmStreamer::EmitCodeEnd(), llvm::AMDGPUTargetELFStreamer::EmitCodeEnd(), llvm::TargetTransformInfo::getCacheLineSize(), and llvm::RISCVInstrInfo::shouldClusterMemOps().
EnableReduxCost
cl::opt< bool > EnableReduxCost("costmodel-reduxcost", cl::init(false), cl::Hidden, cl::desc("Recognize reduction patterns.")) ("costmodel-reduxcost" , cl::init(false) , cl::Hidden , cl::desc("Recognize reduction patterns.")) static
MinPageSize
cl::opt< unsigned > MinPageSize("min-page-size", cl::init(0), cl::Hidden, cl::desc("Use this to override the target's minimum page size.")) ("min-page-size" , cl::init(0) , cl::Hidden , cl::desc("Use this to override the target's minimum page size.")) static
Referenced by llvm::TargetTransformInfo::getMinPageSize().
PredictableBranchThreshold
cl::opt< unsigned > PredictableBranchThreshold("predictable-branch-threshold", cl::init(99), cl::Hidden, cl::desc("Use this to override the target's predictable branch threshold (%).")) ("predictable-branch-threshold" , cl::init(99) , cl::Hidden , cl::desc("Use this to override the target's predictable branch threshold (%).")) static
Referenced by llvm::TargetTransformInfo::getPredictableBranchThreshold().