LLVM: lib/DebugInfo/CodeView/TypeRecordHelpers.cpp File Reference
TypeRecordHelpers.cpp File Reference
#include "llvm/DebugInfo/CodeView/TypeRecordHelpers.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/DebugInfo/CodeView/TypeDeserializer.h"
#include "llvm/DebugInfo/CodeView/TypeIndexDiscovery.h"
Functions
template<typename RecordT >
static ClassOptions getUdtOptions (CVType CVT)
template<typename RecordT >
static uint64_t getUdtSize (CVType CVT)
Function Documentation
getUdtOptions()
template<typename RecordT > static ClassOptions getUdtOptions (CVType CVT) static
Definition at line 18 of file TypeRecordHelpers.cpp.
References llvm::consumeError(), llvm::codeview::TypeDeserializer::deserializeAs(), and llvm::codeview::EC.
Referenced by llvm::codeview::isUdtForwardRef().
getUdtSize()
template<typename RecordT > static uint64_t getUdtSize (CVType CVT) static
Definition at line 162 of file TypeRecordHelpers.cpp.
References llvm::consumeError(), llvm::codeview::TypeDeserializer::deserializeAs(), and llvm::codeview::EC.
Referenced by llvm::codeview::getSizeInBytesForTypeRecord().