LLVM: llvm::dxbc::PipelinePSVInfo Union Reference
llvm::dxbc::PipelinePSVInfo Union Reference
#include "llvm/BinaryFormat/DXContainer.h"
Public Member Functions
void swapBytes (Triple::EnvironmentType Stage)
Public Attributes
VertexPSVInfo VS
HullPSVInfo HS
DomainPSVInfo DS
GeometryPSVInfo GS
PixelPSVInfo PS
MeshPSVInfo MS
AmplificationPSVInfo AS
Detailed Description
Definition at line 238 of file DXContainer.h.
Member Function Documentation
swapBytes()
void llvm::dxbc::PipelinePSVInfo::swapBytes (Triple::EnvironmentType Stage) inline
Definition at line 247 of file DXContainer.h.
References llvm::Triple::Amplification, AS, llvm::Triple::Domain, DS, llvm::Triple::Geometry, GS, HS, llvm::Triple::Hull, llvm::Triple::Mesh, MS, llvm::Triple::Pixel, PS, llvm::dxbc::AmplificationPSVInfo::swapBytes(), llvm::dxbc::DomainPSVInfo::swapBytes(), llvm::dxbc::GeometryPSVInfo::swapBytes(), llvm::dxbc::HullPSVInfo::swapBytes(), llvm::dxbc::MeshPSVInfo::swapBytes(), llvm::dxbc::PixelPSVInfo::swapBytes(), llvm::dxbc::VertexPSVInfo::swapBytes(), llvm::Triple::Vertex, and VS.
Referenced by llvm::dxbc::PSV::v0::RuntimeInfo::swapBytes().
Member Data Documentation
AS
AmplificationPSVInfo llvm::dxbc::PipelinePSVInfo::AS
Definition at line 245 of file DXContainer.h.
Referenced by llvm::DXContainerYAML::PSVInfo::mapInfoForVersion(), and swapBytes().
DS
DomainPSVInfo llvm::dxbc::PipelinePSVInfo::DS
Definition at line 241 of file DXContainer.h.
Referenced by llvm::DXContainerYAML::PSVInfo::mapInfoForVersion(), and swapBytes().
GS
GeometryPSVInfo llvm::dxbc::PipelinePSVInfo::GS
Definition at line 242 of file DXContainer.h.
Referenced by llvm::DXContainerYAML::PSVInfo::mapInfoForVersion(), and swapBytes().
HS
HullPSVInfo llvm::dxbc::PipelinePSVInfo::HS
Definition at line 240 of file DXContainer.h.
Referenced by llvm::DXContainerYAML::PSVInfo::mapInfoForVersion(), and swapBytes().
MS
MeshPSVInfo llvm::dxbc::PipelinePSVInfo::MS
Definition at line 244 of file DXContainer.h.
Referenced by llvm::DXContainerYAML::PSVInfo::mapInfoForVersion(), and swapBytes().
PS
PixelPSVInfo llvm::dxbc::PipelinePSVInfo::PS
Definition at line 243 of file DXContainer.h.
Referenced by llvm::DXContainerYAML::PSVInfo::mapInfoForVersion(), and swapBytes().
VS
VertexPSVInfo llvm::dxbc::PipelinePSVInfo::VS
Definition at line 239 of file DXContainer.h.
Referenced by llvm::DXContainerYAML::PSVInfo::mapInfoForVersion(), and swapBytes().
The documentation for this union was generated from the following file:
include/llvm/BinaryFormat/DXContainer.h