LLVM: lib/Target/VE/VEISelLowering.cpp File Reference
VEISelLowering.cpp File Reference
#include "VEISelLowering.h"
#include "MCTargetDesc/VEMCExpr.h"
#include "VECustomDAG.h"
#include "VEInstrBuilder.h"
#include "VEMachineFunctionInfo.h"
#include "VERegisterInfo.h"
#include "VETargetMachine.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/KnownBits.h"
#include "VEGenCallingConv.inc"
#include "VVPNodes.def"
Macros
#define DEBUG_TYPE "ve-lower"
#define HANDLE_VP_TO_VVP(VP_OPC, VVP_NAME)
#define ADD_VVP_OP(VVP_NAME, ISD_NAME)
#define ADD_UNARY_VVP_OP(VVPNAME, SDNAME)
#define ADD_BINARY_VVP_OP(VVPNAME, VPNAME, SDNAME)
#define ADD_TERNARY_VVP_OP(VVPNAME, SDNAME)
#define ADD_BINARY_VVP_OP_COMPACT(NAME)
#define REGISTER_PACKED(OPC)
#define ADD_REDUCE_VVP_OP(OPC, SDNAME)
#define HANDLE_VVP_REDUCE_TO_SCALAR(VVP_RED_ISD, REDUCE_ISD)
#define HELPER_REDUCTION(OPC, SCALAR_OPC)
#define TARGET_NODE_CASE(NAME)
#define ADD_VVP_OP(VVP_NAME, ...)
#define HANDLE_VP_TO_VVP(VPOPC, VVPOPC)
#define ADD_UNARY_VVP_OP(VVPNAME, SDNAME)
#define ADD_BINARY_VVP_OP(VVPNAME, VPNAME, SDNAME)
#define ADD_TERNARY_VVP_OP(VVPNAME, SDNAME)
#define ADD_BINARY_VVP_OP_COMPACT(NAME)
#define REGISTER_PACKED(OPC)
#define ADD_REDUCE_VVP_OP(OPC, SDNAME)
#define HANDLE_VVP_REDUCE_TO_SCALAR(VVP_RED_ISD, REDUCE_ISD)
#define HELPER_REDUCTION(OPC, SCALAR_OPC)
#define ADD_VVP_OP(VVP_NAME, ...)
#define HANDLE_VP_TO_VVP(VPOPC, VVPOPC)
#define ADD_UNARY_VVP_OP(VVPNAME, SDNAME)
#define ADD_BINARY_VVP_OP(VVPNAME, VPNAME, SDNAME)
#define ADD_TERNARY_VVP_OP(VVPNAME, SDNAME)
#define ADD_BINARY_VVP_OP_COMPACT(NAME)
#define REGISTER_PACKED(OPC)
#define ADD_REDUCE_VVP_OP(OPC, SDNAME)
#define HANDLE_VVP_REDUCE_TO_SCALAR(VVP_RED_ISD, REDUCE_ISD)
#define HELPER_REDUCTION(OPC, SCALAR_OPC)
#define ADD_VVP_OP(VVP_NAME, ISD_NAME)
#define HANDLE_VP_TO_VVP(VPOPC, VVPOPC)
#define ADD_UNARY_VVP_OP(VVPNAME, SDNAME)
#define ADD_BINARY_VVP_OP(VVPNAME, VPNAME, SDNAME)
#define ADD_TERNARY_VVP_OP(VVPNAME, SDNAME)
#define ADD_BINARY_VVP_OP_COMPACT(NAME)
#define REGISTER_PACKED(OPC)
#define ADD_REDUCE_VVP_OP(OPC, SDNAME)
#define HANDLE_VVP_REDUCE_TO_SCALAR(VVP_RED_ISD, REDUCE_ISD)
#define HELPER_REDUCTION(OPC, SCALAR_OPC)
Functions
CCAssignFn * getReturnCC (CallingConv::ID CallConv)
CCAssignFn * getParamCC (CallingConv::ID CallConv, bool IsVarArg)
static SDValue prepareTS1AM (SDValue Op, SelectionDAG &DAG, SDValue &Flag, SDValue &Bits)
static SDValue finalizeTS1AM (SDValue Op, SelectionDAG &DAG, SDValue Data, SDValue Bits)
static SDValue lowerLoadF128 (SDValue Op, SelectionDAG &DAG)
static SDValue lowerLoadI1 (SDValue Op, SelectionDAG &DAG)
static SDValue lowerStoreF128 (SDValue Op, SelectionDAG &DAG)
static SDValue lowerStoreI1 (SDValue Op, SelectionDAG &DAG)
static SDValue lowerFRAMEADDR (SDValue Op, SelectionDAG &DAG, const VETargetLowering &TLI, const VESubtarget *Subtarget)
static SDValue lowerRETURNADDR (SDValue Op, SelectionDAG &DAG, const VETargetLowering &TLI, const VESubtarget *Subtarget)
static bool getUniqueInsertion (SDNode *N, unsigned &UniqueIdx)
static SDValue getSplatValue (SDNode *N)
static bool isSimm7 (SDValue V)
static bool isMImm (SDValue V)
static unsigned decideComp (EVT SrcVT, ISD::CondCode CC)
static EVT decideCompType (EVT SrcVT)
static bool safeWithoutCompWithNull (EVT SrcVT, ISD::CondCode CC, bool WithCMov)
static SDValue generateComparison (EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode CC, bool WithCMov, const SDLoc &DL, SelectionDAG &DAG)
static bool isI32InsnAllUses (const SDNode *User, const SDNode *N)
static bool isI32Insn (const SDNode *User, const SDNode *N)
Variables
static const MVT AllVectorVTs []
static const MVT AllMaskVTs [] = {MVT::v256i1, MVT::v512i1}
static const MVT AllPackedVTs [] = {MVT::v512i32, MVT::v512f32}
Macro Definition Documentation
ADD_BINARY_VVP_OP [1/4]
#define ADD_BINARY_VVP_OP (VVPNAME, VPNAME, SDNAME)
Value:
            ADD_VVP_OP(VVPNAME,SDNAME) \
            HANDLE_VP_TO_VVP(VPNAME, VVPNAME)
ADD_BINARY_VVP_OP [2/4]
#define ADD_BINARY_VVP_OP (VVPNAME, VPNAME, SDNAME)
Value:
            ADD_VVP_OP(VVPNAME,SDNAME) \
            HANDLE_VP_TO_VVP(VPNAME, VVPNAME)
ADD_BINARY_VVP_OP [3/4]
#define ADD_BINARY_VVP_OP (VVPNAME, VPNAME, SDNAME)
Value:
            ADD_VVP_OP(VVPNAME,SDNAME) \
            HANDLE_VP_TO_VVP(VPNAME, VVPNAME)
ADD_BINARY_VVP_OP [4/4]
#define ADD_BINARY_VVP_OP (VVPNAME, VPNAME, SDNAME)
Value:
            ADD_VVP_OP(VVPNAME,SDNAME) \
            HANDLE_VP_TO_VVP(VPNAME, VVPNAME)
ADD_BINARY_VVP_OP_COMPACT [1/4]
#define ADD_BINARY_VVP_OP_COMPACT (NAME)
Value:
    ADD_BINARY_VVP_OP(VVP_##NAME,VP_##NAME,NAME)
ADD_BINARY_VVP_OP_COMPACT [2/4]
#define ADD_BINARY_VVP_OP_COMPACT (NAME)
Value:
    ADD_BINARY_VVP_OP(VVP_##NAME,VP_##NAME,NAME)
ADD_BINARY_VVP_OP_COMPACT [3/4]
#define ADD_BINARY_VVP_OP_COMPACT (NAME)
Value:
    ADD_BINARY_VVP_OP(VVP_##NAME,VP_##NAME,NAME)
ADD_BINARY_VVP_OP_COMPACT [4/4]
#define ADD_BINARY_VVP_OP_COMPACT (NAME)
Value:
    ADD_BINARY_VVP_OP(VVP_##NAME,VP_##NAME,NAME)
ADD_REDUCE_VVP_OP [1/4]
#define ADD_REDUCE_VVP_OP (OPC, SDNAME)
Value:
ADD_VVP_OP(OPC, SDNAME)
ADD_REDUCE_VVP_OP [2/4]
#define ADD_REDUCE_VVP_OP (OPC, SDNAME)
Value:
ADD_VVP_OP(OPC, SDNAME)
ADD_REDUCE_VVP_OP [3/4]
#define ADD_REDUCE_VVP_OP (OPC, SDNAME)
Value:
ADD_VVP_OP(OPC, SDNAME)
ADD_REDUCE_VVP_OP [4/4]
#define ADD_REDUCE_VVP_OP (OPC, SDNAME)
Value:
ADD_VVP_OP(OPC, SDNAME)
ADD_TERNARY_VVP_OP [1/4]
#define ADD_TERNARY_VVP_OP (VVPNAME, SDNAME)
Value:
    ADD_VVP_OP(VVPNAME,SDNAME)
ADD_TERNARY_VVP_OP [2/4]
#define ADD_TERNARY_VVP_OP (VVPNAME, SDNAME)
Value:
    ADD_VVP_OP(VVPNAME,SDNAME)
ADD_TERNARY_VVP_OP [3/4]
#define ADD_TERNARY_VVP_OP (VVPNAME, SDNAME)
Value:
    ADD_VVP_OP(VVPNAME,SDNAME)
ADD_TERNARY_VVP_OP [4/4]
#define ADD_TERNARY_VVP_OP (VVPNAME, SDNAME)
Value:
    ADD_VVP_OP(VVPNAME,SDNAME)
ADD_UNARY_VVP_OP [1/4]
#define ADD_UNARY_VVP_OP (VVPNAME, SDNAME)
Value:
            ADD_VVP_OP(VVPNAME,SDNAME)
ADD_UNARY_VVP_OP [2/4]
#define ADD_UNARY_VVP_OP (VVPNAME, SDNAME)
Value:
            ADD_VVP_OP(VVPNAME,SDNAME)
ADD_UNARY_VVP_OP [3/4]
#define ADD_UNARY_VVP_OP (VVPNAME, SDNAME)
Value:
            ADD_VVP_OP(VVPNAME,SDNAME)
ADD_UNARY_VVP_OP [4/4]
#define ADD_UNARY_VVP_OP (VVPNAME, SDNAME)
Value:
            ADD_VVP_OP(VVPNAME,SDNAME)
ADD_VVP_OP [1/4]
#define ADD_VVP_OP (VVP_NAME, ISD_NAME)
Value:
  setOperationAction(ISD::ISD_NAME, LegalVecVT, Custom);
ADD_VVP_OP [2/4]
#define ADD_VVP_OP (VVP_NAME, ISD_NAME)
Value:
case ISD::ISD_NAME:
ADD_VVP_OP [3/4]
#define ADD_VVP_OP (VVP_NAME, ...)
Value:
TARGET_NODE_CASE(VVP_NAME)
ADD_VVP_OP [4/4]
#define ADD_VVP_OP (VVP_NAME, ...)
Value:
case VEISD::VVP_NAME:
DEBUG_TYPE
#define DEBUG_TYPE "ve-lower"
Definition at line 39 of file VEISelLowering.cpp.
HANDLE_VP_TO_VVP [1/4]
#define HANDLE_VP_TO_VVP (VP_OPC, VVP_NAME)
Value:
  setOperationAction(ISD::VP_OPC, LegalVecVT, Custom);
HANDLE_VP_TO_VVP [2/4]
#define HANDLE_VP_TO_VVP (VPOPC, VVPOPC)
HANDLE_VP_TO_VVP [3/4]
#define HANDLE_VP_TO_VVP (VPOPC, VVPOPC)
HANDLE_VP_TO_VVP [4/4]
#define HANDLE_VP_TO_VVP (VPOPC, VVPOPC)
HANDLE_VVP_REDUCE_TO_SCALAR [1/4]
#define HANDLE_VVP_REDUCE_TO_SCALAR (VVP_RED_ISD, REDUCE_ISD)
HANDLE_VVP_REDUCE_TO_SCALAR [2/4]
#define HANDLE_VVP_REDUCE_TO_SCALAR (VVP_RED_ISD, REDUCE_ISD)
HANDLE_VVP_REDUCE_TO_SCALAR [3/4]
#define HANDLE_VVP_REDUCE_TO_SCALAR (VVP_RED_ISD, REDUCE_ISD)
HANDLE_VVP_REDUCE_TO_SCALAR [4/4]
#define HANDLE_VVP_REDUCE_TO_SCALAR (VVP_RED_ISD, REDUCE_ISD)
HELPER_REDUCTION [1/4]
#define HELPER_REDUCTION (OPC, SCALAR_OPC)
Value:
    ADD_REDUCE_VVP_OP(VVP_REDUCE_##OPC,VECREDUCE_##OPC) \
    HANDLE_VP_TO_VVP(VP_REDUCE_##OPC, VVP_REDUCE_##OPC) \
    HANDLE_VVP_REDUCE_TO_SCALAR(VVP_REDUCE_##OPC, SCALAR_OPC)
HELPER_REDUCTION [2/4]
#define HELPER_REDUCTION (OPC, SCALAR_OPC)
Value:
    ADD_REDUCE_VVP_OP(VVP_REDUCE_##OPC,VECREDUCE_##OPC) \
    HANDLE_VP_TO_VVP(VP_REDUCE_##OPC, VVP_REDUCE_##OPC) \
    HANDLE_VVP_REDUCE_TO_SCALAR(VVP_REDUCE_##OPC, SCALAR_OPC)
HELPER_REDUCTION [3/4]
#define HELPER_REDUCTION (OPC, SCALAR_OPC)
Value:
    ADD_REDUCE_VVP_OP(VVP_REDUCE_##OPC,VECREDUCE_##OPC) \
    HANDLE_VP_TO_VVP(VP_REDUCE_##OPC, VVP_REDUCE_##OPC) \
    HANDLE_VVP_REDUCE_TO_SCALAR(VVP_REDUCE_##OPC, SCALAR_OPC)
HELPER_REDUCTION [4/4]
#define HELPER_REDUCTION (OPC, SCALAR_OPC)
Value:
    ADD_REDUCE_VVP_OP(VVP_REDUCE_##OPC,VECREDUCE_##OPC) \
    HANDLE_VP_TO_VVP(VP_REDUCE_##OPC, VVP_REDUCE_##OPC) \
    HANDLE_VVP_REDUCE_TO_SCALAR(VVP_REDUCE_##OPC, SCALAR_OPC)
REGISTER_PACKED [1/4]
#define REGISTER_PACKED (OPC)
REGISTER_PACKED [2/4]
#define REGISTER_PACKED (OPC)
REGISTER_PACKED [3/4]
#define REGISTER_PACKED (OPC)
REGISTER_PACKED [4/4]
#define REGISTER_PACKED (OPC)
TARGET_NODE_CASE
#define TARGET_NODE_CASE (NAME)
Value:
  case VEISD::NAME:                                                            \
    return "VEISD::" #NAME;
Referenced by llvm::VETargetLowering::getTargetNodeName().
Function Documentation
decideComp()
static unsigned decideComp (EVT SrcVT, ISD::CondCode CC) static
Definition at line 2734 of file VEISelLowering.cpp.
References CC, llvm::VEISD::CMPF, llvm::VEISD::CMPI, llvm::VEISD::CMPQ, llvm::VEISD::CMPU, and llvm::EVT::isFloatingPoint().
Referenced by generateComparison().
decideCompType()
static EVT decideCompType (EVT SrcVT) static
Definition at line 2743 of file VEISelLowering.cpp.
Referenced by generateComparison().
finalizeTS1AM()
static SDValue finalizeTS1AM (SDValue Op, SelectionDAG & DAG, SDValue Data, SDValue Bits) static
Definition at line 1179 of file VEISelLowering.cpp.
References llvm::ISD::AND, llvm::cast(), llvm::Data, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), and llvm::ISD::SRL.
Referenced by llvm::VETargetLowering::lowerATOMIC_SWAP().
generateComparison()
static SDValue generateComparison (EVT VT, SDValue LHS, SDValue RHS, ISD::CondCode CC, bool WithCMov, const SDLoc & DL, SelectionDAG & DAG) static
Definition at line 2774 of file VEISelLowering.cpp.
References CC, decideComp(), decideCompType(), DL, llvm::SelectionDAG::getNode(), llvm::isNullConstant(), llvm::isNullFPConstant(), LHS, and safeWithoutCompWithNull().
Referenced by llvm::VETargetLowering::combineSelectCC().
getParamCC()
CCAssignFn * getParamCC (CallingConv::ID CallConv, bool IsVarArg)
Definition at line 56 of file VEISelLowering.cpp.
Referenced by llvm::VETargetLowering::LowerCall(), and llvm::VETargetLowering::LowerFormalArguments().
getReturnCC()
CCAssignFn * getReturnCC (CallingConv::ID CallConv)
Definition at line 47 of file VEISelLowering.cpp.
Referenced by llvm::VETargetLowering::CanLowerReturn(), llvm::VETargetLowering::LowerCall(), and llvm::VETargetLowering::LowerReturn().
getSplatValue()
static SDValue getSplatValue (SDNode * N) static
Definition at line 1821 of file VEISelLowering.cpp.
References llvm::dyn_cast(), N, and SDValue().
getUniqueInsertion()
static bool getUniqueInsertion (SDNode * N, unsigned & UniqueIdx) static
Definition at line 1795 of file VEISelLowering.cpp.
References llvm::cast(), llvm::isa(), and N.
Referenced by llvm::VETargetLowering::lowerBUILD_VECTOR().
isI32Insn()
static bool isI32Insn (const SDNode * User, const SDNode * N) static
Definition at line 2897 of file VEISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::BSWAP, llvm::VEISD::CMOV, llvm::VEISD::CMPI, llvm::VEISD::CMPU, llvm::ISD::CopyToReg, llvm::User::getOperand(), llvm::isa(), isI32InsnAllUses(), llvm::isIntVECondCode(), llvm::ISD::MUL, N, llvm::ISD::OR, llvm::ISD::SDIV, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SHL, llvm::ISD::SINT_TO_FP, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, llvm::ISD::UDIV, llvm::ISD::UINT_TO_FP, and llvm::ISD::XOR.
Referenced by llvm::VETargetLowering::combineTRUNCATE(), and isI32InsnAllUses().
isI32InsnAllUses()
static bool isI32InsnAllUses (const SDNode * User, const SDNode * N) static
Definition at line 2954 of file VEISelLowering.cpp.
References llvm::ISD::ANY_EXTEND, assert(), llvm::VEISD::CMOV, isI32Insn(), N, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SIGN_EXTEND, llvm::Value::uses(), and llvm::ISD::ZERO_EXTEND.
Referenced by isI32Insn().
isMImm()
static bool isMImm (SDValue V) static
Definition at line 2713 of file VEISelLowering.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), llvm::getFpImmVal(), llvm::getImmVal(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::isMImm32Val(), llvm::isMImmVal(), and llvm::EVT::isVector().
Referenced by llvm::VETargetLowering::combineSelect(), and llvm::VETargetLowering::combineSelectCC().
isSimm7()
static bool isSimm7 (SDValue V) static
Definition at line 2691 of file VEISelLowering.cpp.
References llvm::CallingConv::C, llvm::dyn_cast(), llvm::EVT::isFloatingPoint(), llvm::isInt(), llvm::EVT::isInteger(), and llvm::EVT::isVector().
Referenced by llvm::VETargetLowering::combineSelectCC().
lowerFRAMEADDR()
static SDValue lowerFRAMEADDR (SDValue Op, SelectionDAG & DAG, const VETargetLowering & TLI, const VESubtarget * Subtarget) static
Definition at line 1723 of file VEISelLowering.cpp.
References llvm::Depth, DL, llvm::SelectionDAG::getCopyFromReg(), llvm::MachineFunction::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::TargetLoweringBase::getPointerTy(), llvm::VESubtarget::getRegisterInfo(), and llvm::MachineFrameInfo::setFrameAddressIsTaken().
Referenced by llvm::VETargetLowering::LowerOperation(), and lowerRETURNADDR().
lowerLoadF128()
static SDValue lowerLoadF128 (SDValue Op, SelectionDAG & DAG) static
Definition at line 1322 of file VEISelLowering.cpp.
References llvm::ISD::ADD, Align, assert(), DL, llvm::dyn_cast(), llvm::MemSDNode::getAlign(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::LoadSDNode::getOffset(), llvm::MemSDNode::getPointerInfo(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::getValueType(), llvm::SDValue::isUndef(), llvm::MemSDNode::isVolatile(), llvm::MachineMemOperand::MONone, llvm::MachineMemOperand::MOVolatile, SDValue(), and llvm::ISD::TokenFactor.
Referenced by llvm::VETargetLowering::lowerLOAD().
lowerLoadI1()
static SDValue lowerLoadI1 (SDValue Op, SelectionDAG & DAG) static
Definition at line 1367 of file VEISelLowering.cpp.
References llvm::ISD::ADD, Addr, Align, assert(), DL, llvm::dyn_cast(), llvm::MemSDNode::getAlign(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineNode(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::LoadSDNode::getOffset(), llvm::MemSDNode::getPointerInfo(), llvm::SelectionDAG::getTargetConstant(), llvm::SDValue::isUndef(), llvm::MemSDNode::isVolatile(), llvm::MachineMemOperand::MONone, llvm::MachineMemOperand::MOVolatile, SDValue(), and llvm::ISD::TokenFactor.
Referenced by llvm::VETargetLowering::lowerLOAD().
lowerRETURNADDR()
static SDValue lowerRETURNADDR (SDValue Op, SelectionDAG & DAG, const VETargetLowering & TLI, const VESubtarget * Subtarget) static
Definition at line 1744 of file VEISelLowering.cpp.
References llvm::ISD::ADD, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), lowerFRAMEADDR(), llvm::Offset, SDValue(), llvm::MachineFrameInfo::setReturnAddressIsTaken(), and llvm::TargetLowering::verifyReturnAddressArgumentIsConstant().
Referenced by llvm::VETargetLowering::LowerOperation().
lowerStoreF128()
static SDValue lowerStoreF128 (SDValue Op, SelectionDAG & DAG) static
Definition at line 1451 of file VEISelLowering.cpp.
References llvm::ISD::ADD, Align, assert(), DL, llvm::dyn_cast(), llvm::MemSDNode::getAlign(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getNode(), llvm::StoreSDNode::getOffset(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetConstant(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::SDValue::isUndef(), llvm::MemSDNode::isVolatile(), llvm::MachineMemOperand::MONone, llvm::MachineMemOperand::MOVolatile, and llvm::ISD::TokenFactor.
Referenced by llvm::VETargetLowering::lowerSTORE().
lowerStoreI1()
static SDValue lowerStoreI1 (SDValue Op, SelectionDAG & DAG) static
Definition at line 1492 of file VEISelLowering.cpp.
References llvm::ISD::ADD, Addr, Align, assert(), DL, llvm::dyn_cast(), llvm::MemSDNode::getAlign(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMachineNode(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getNode(), llvm::StoreSDNode::getOffset(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetConstant(), llvm::StoreSDNode::getValue(), llvm::SDValue::isUndef(), llvm::MemSDNode::isVolatile(), llvm::MachineMemOperand::MONone, llvm::MachineMemOperand::MOVolatile, SDValue(), and llvm::ISD::TokenFactor.
Referenced by llvm::VETargetLowering::lowerSTORE().
prepareTS1AM()
static SDValue prepareTS1AM (SDValue Op, SelectionDAG & DAG, SDValue & Flag, SDValue & Bits) static
Definition at line 1157 of file VEISelLowering.cpp.
References llvm::ISD::AND, llvm::cast(), DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), N, Ptr, and llvm::ISD::SHL.
Referenced by llvm::VETargetLowering::lowerATOMIC_SWAP().
safeWithoutCompWithNull()
static bool safeWithoutCompWithNull (EVT SrcVT, ISD::CondCode CC, bool WithCMov) static
Definition at line 2749 of file VEISelLowering.cpp.
References CC, and llvm::EVT::isFloatingPoint().
Referenced by generateComparison().
Variable Documentation
AllMaskVTs
const MVT AllMaskVTs[] = {MVT::v256i1, MVT::v512i1} static
Definition at line 79 of file VEISelLowering.cpp.
AllPackedVTs
const MVT AllPackedVTs[] = {MVT::v512i32, MVT::v512f32} static
Definition at line 81 of file VEISelLowering.cpp.
AllVectorVTs
const MVT AllVectorVTs[] static
Initial value:
= {MVT::v256i32, MVT::v512i32, MVT::v256i64,
                                   MVT::v256f32, MVT::v512f32, MVT::v256f64}
Definition at line 76 of file VEISelLowering.cpp.