LLVM: lib/ExecutionEngine/Orc/Debugging/VTuneSupportPlugin.cpp File Reference
VTuneSupportPlugin.cpp File Reference
#include "llvm/ExecutionEngine/Orc/Debugging/VTuneSupportPlugin.h"
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
#include "llvm/ExecutionEngine/Orc/Debugging/DebugInfoSupport.h"
Functions
static VTuneMethodBatch getMethodBatch (LinkGraph &G, bool EmitDebugInfo)
Variables
static constexpr StringRef RegisterVTuneImplName = "llvm_orc_registerVTuneImpl"
static constexpr StringRef UnregisterVTuneImplName
static constexpr StringRef RegisterTestVTuneImplName
Function Documentation
getMethodBatch()
static VTuneMethodBatch getMethodBatch (LinkGraph & G, bool EmitDebugInfo) static
Definition at line 26 of file VTuneSupportPlugin.cpp.
References Addr, llvm::orc::createDWARFContext(), G, llvm::jitlink::Symbol::getAddress(), llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Symbol::getName(), llvm::jitlink::Symbol::getOffset(), llvm::jitlink::Section::getOrdinal(), llvm::jitlink::Block::getSection(), llvm::jitlink::Symbol::getSize(), I, llvm::jitlink::Symbol::isCallable(), llvm::orc::VTuneMethodBatch::Methods, llvm::orc::VTuneMethodBatch::Strings, and Sym.
Referenced by llvm::orc::VTuneSupportPlugin::modifyPassConfig().
Variable Documentation
RegisterTestVTuneImplName
StringRef RegisterTestVTuneImplName static constexpr
Initial value:
=
    "llvm_orc_test_registerVTuneImpl"
Definition at line 23 of file VTuneSupportPlugin.cpp.
Referenced by llvm::orc::VTuneSupportPlugin::Create().
RegisterVTuneImplName
StringRef RegisterVTuneImplName = "llvm_orc_registerVTuneImpl" static constexpr
Definition at line 20 of file VTuneSupportPlugin.cpp.
Referenced by llvm::orc::VTuneSupportPlugin::Create().
UnregisterVTuneImplName
StringRef UnregisterVTuneImplName static constexpr
Initial value:
=
    "llvm_orc_unregisterVTuneImpl"
Definition at line 21 of file VTuneSupportPlugin.cpp.
Referenced by llvm::orc::VTuneSupportPlugin::Create().