LLVM: lib/Target/WebAssembly/WebAssemblyExceptionInfo.cpp File Reference
WebAssemblyExceptionInfo.cpp File Reference
This file implements WebAssemblyException information analysis.
#include "WebAssemblyExceptionInfo.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "WebAssemblyUtilities.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/CodeGen/MachineDominanceFrontier.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/WasmEHFuncInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/IR/Function.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "wasm-exception-info"
Functions
INITIALIZE_PASS_BEGIN (WebAssemblyExceptionInfo, DEBUG_TYPE, "WebAssembly Exception Information", true, true) INITIALIZE_PASS_END(WebAssemblyExceptionInfo
static bool isReachableAmongDominated (const MachineBasicBlock *Src, const MachineBasicBlock *Dst, const MachineBasicBlock *Header, const MachineDominatorTree &MDT)
raw_ostream & operator<< (raw_ostream &OS, const WebAssemblyException &WE)
Variables
DEBUG_TYPE
WebAssembly Exception Information
WebAssembly Exception true
Detailed Description
This file implements WebAssemblyException information analysis.
Definition in file WebAssemblyExceptionInfo.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-exception-info"
Definition at line 29 of file WebAssemblyExceptionInfo.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (WebAssemblyExceptionInfo , DEBUG_TYPE , "WebAssembly Exception Information" , true , true)
isReachableAmongDominated()
static bool isReachableAmongDominated (const MachineBasicBlock * Src, const MachineBasicBlock * Dst, const MachineBasicBlock * Header, const MachineDominatorTree & MDT) static
Definition at line 58 of file WebAssemblyExceptionInfo.cpp.
References assert(), llvm::SmallPtrSetImpl< PtrType >::count(), llvm::MachineDominatorTree::dominates(), llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallPtrSetImpl< PtrType >::insert(), MBB, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::MachineBasicBlock::successors().
Referenced by llvm::WebAssemblyExceptionInfo::recalculate().
operator<<()
raw_ostream & operator<< (raw_ostream & OS, const WebAssemblyException & WE)
Definition at line 365 of file WebAssemblyExceptionInfo.cpp.
References OS, and llvm::WebAssemblyException::print().
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 37 of file WebAssemblyExceptionInfo.cpp.
Information
WebAssembly Exception Information
Definition at line 38 of file WebAssemblyExceptionInfo.cpp.
true
WebAssembly Exception true
Definition at line 38 of file WebAssemblyExceptionInfo.cpp.