LLVM: lib/CodeGen/WindowScheduler.cpp File Reference
WindowScheduler.cpp File Reference
#include "llvm/CodeGen/WindowScheduler.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachinePipeliner.h"
#include "llvm/CodeGen/ModuloSchedule.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/TimeProfiler.h"
Macros
#define DEBUG_TYPE "pipeliner"
Variables
cl::opt< unsigned > WindowIILimit ("window-ii-limit", cl::desc("The upper limit of II in the window algorithm."), cl::Hidden, cl::init(1000))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "pipeliner"
Definition at line 51 of file WindowScheduler.cpp.
Variable Documentation
WindowIILimit
cl::opt< unsigned > WindowIILimit("window-ii-limit", cl::desc("The upper limit of II in the window algorithm."), cl::Hidden, cl::init(1000)) ("window-ii-limit" , cl::desc("The upper limit of II in the window algorithm.") , cl::Hidden , cl::init(1000))
Referenced by llvm::WindowScheduler::analyseII(), llvm::WindowScheduler::calculateMaxCycle(), llvm::WindowScheduler::calculateStallCycle(), and llvm::WindowScheduler::run().