LLVM: lib/CodeGen/WinEHPrepare.cpp File Reference
WinEHPrepare.cpp File Reference
#include "llvm/CodeGen/WinEHPrepare.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/WinEHFuncInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/EHPersonalities.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Verifier.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/Triple.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/SSAUpdater.h"
Classes
struct WorkItem
Macros
#define DEBUG_TYPE "win-eh-prepare"
Functions
INITIALIZE_PASS (WinEHPrepare, DEBUG_TYPE, "Prepare Windows exceptions", false, false) FunctionPass *llvm
static int addUnwindMapEntry (WinEHFuncInfo &FuncInfo, int ToState, const BasicBlock *BB)
static void addTryBlockMapEntry (WinEHFuncInfo &FuncInfo, int TryLow, int TryHigh, int CatchHigh, ArrayRef< const CatchPadInst * > Handlers)
static BasicBlock * getCleanupRetUnwindDest (const CleanupPadInst *CleanupPad)
static void calculateStateNumbersForInvokes (const Function *Fn, WinEHFuncInfo &FuncInfo)
static const BasicBlock * getEHPadFromPredecessor (const BasicBlock *BB, Value *ParentPad)
static void calculateCXXStateNumbers (WinEHFuncInfo &FuncInfo, const Instruction *FirstNonPHI, int ParentState)
static int addSEHExcept (WinEHFuncInfo &FuncInfo, int ParentState, const Function *Filter, const BasicBlock *Handler)
static int addSEHFinally (WinEHFuncInfo &FuncInfo, int ParentState, const BasicBlock *Handler)
static void calculateSEHStateNumbers (WinEHFuncInfo &FuncInfo, const Instruction *FirstNonPHI, int ParentState)
static bool isTopLevelPadForMSVC (const Instruction *EHPad)
static int addClrEHHandler (WinEHFuncInfo &FuncInfo, int HandlerParentState, int TryParentState, ClrHandlerType HandlerType, uint32_t TypeToken, const BasicBlock *Handler)
Variables
static cl::opt< bool > DisableDemotion ("disable-demotion", cl::Hidden, cl::desc("Clone multicolor basic blocks but do not demote cross scopes"), cl::init(false))
static cl::opt< bool > DisableCleanups ("disable-cleanups", cl::Hidden, cl::desc("Do not remove implausible terminators or other similar cleanups"), cl::init(false))
static cl::opt< bool > DemoteCatchSwitchPHIOnlyOpt ("demote-catchswitch-only", cl::Hidden, cl::desc("Demote catchswitch BBs only (for wasm EH)"), cl::init(false))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "win-eh-prepare"
Definition at line 43 of file WinEHPrepare.cpp.
Function Documentation
addClrEHHandler()
static int addClrEHHandler (WinEHFuncInfo & FuncInfo, int HandlerParentState, int TryParentState, ClrHandlerType HandlerType, uint32_t TypeToken, const BasicBlock * Handler) static
Definition at line 636 of file WinEHPrepare.cpp.
References llvm::WinEHFuncInfo::ClrEHUnwindMap, and llvm::ClrEHUnwindMapEntry::HandlerParentState.
Referenced by llvm::calculateClrEHStateNumbers().
addSEHExcept()
static int addSEHExcept (WinEHFuncInfo & FuncInfo, int ParentState, const Function * Filter, const BasicBlock * Handler) static
Definition at line 472 of file WinEHPrepare.cpp.
References llvm::Filter, llvm::WinEHFuncInfo::SEHUnwindMap, and llvm::SEHUnwindMapEntry::ToState.
Referenced by calculateSEHStateNumbers().
addSEHFinally()
static int addSEHFinally (WinEHFuncInfo & FuncInfo, int ParentState, const BasicBlock * Handler) static
Definition at line 483 of file WinEHPrepare.cpp.
References llvm::WinEHFuncInfo::SEHUnwindMap, and llvm::SEHUnwindMapEntry::ToState.
Referenced by calculateSEHStateNumbers().
addTryBlockMapEntry()
static void addTryBlockMapEntry (WinEHFuncInfo & FuncInfo, int TryLow, int TryHigh, int CatchHigh, ArrayRef< const CatchPadInst * > Handlers) static
Definition at line 155 of file WinEHPrepare.cpp.
References llvm::WinEHHandlerType::Adjectives, llvm::WinEHHandlerType::Alloca, assert(), llvm::cast(), llvm::WinEHTryBlockMapEntry::CatchHigh, llvm::WinEHHandlerType::CatchObj, llvm::dyn_cast(), llvm::WinEHHandlerType::Handler, llvm::WinEHTryBlockMapEntry::HandlerArray, llvm::Constant::isNullValue(), llvm::Constant::stripPointerCasts(), llvm::WinEHFuncInfo::TryBlockMap, llvm::WinEHTryBlockMapEntry::TryHigh, llvm::WinEHTryBlockMapEntry::TryLow, and llvm::WinEHHandlerType::TypeDescriptor.
Referenced by calculateCXXStateNumbers().
addUnwindMapEntry()
static int addUnwindMapEntry (WinEHFuncInfo & FuncInfo, int ToState, const BasicBlock * BB) static
Definition at line 146 of file WinEHPrepare.cpp.
References llvm::CxxUnwindMapEntry::Cleanup, llvm::WinEHFuncInfo::CxxUnwindMap, llvm::WinEHFuncInfo::getLastStateNumber(), and llvm::CxxUnwindMapEntry::ToState.
Referenced by calculateCXXStateNumbers().
calculateCXXStateNumbers()
static void calculateCXXStateNumbers (WinEHFuncInfo & FuncInfo, const Instruction * FirstNonPHI, int ParentState) static
Definition at line 376 of file WinEHPrepare.cpp.
References addTryBlockMapEntry(), addUnwindMapEntry(), assert(), calculateCXXStateNumbers(), llvm::cast(), llvm::dbgs(), llvm::dyn_cast(), llvm::WinEHFuncInfo::EHPadStateMap, llvm::WinEHFuncInfo::FuncletBaseStateMap, getCleanupRetUnwindDest(), getEHPadFromPredecessor(), llvm::WinEHFuncInfo::getLastStateNumber(), llvm::Value::getName(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::Triple::isArch64Bit(), llvm::BasicBlock::isEHPad(), LLVM_DEBUG, llvm::Mod, llvm::predecessors(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::report_fatal_error(), llvm::WinEHFuncInfo::TryBlockMap, and llvm::Value::users().
Referenced by calculateCXXStateNumbers(), and llvm::calculateWinCXXEHStateNumbers().
calculateSEHStateNumbers()
static void calculateSEHStateNumbers (WinEHFuncInfo & FuncInfo, const Instruction * FirstNonPHI, int ParentState) static
Definition at line 497 of file WinEHPrepare.cpp.
References addSEHExcept(), addSEHFinally(), assert(), llvm::calculateSEHStateNumbers(), llvm::cast(), llvm::dbgs(), llvm::dyn_cast(), llvm::WinEHFuncInfo::EHPadStateMap, llvm::Filter, getCleanupRetUnwindDest(), getEHPadFromPredecessor(), llvm::Value::getName(), llvm::BasicBlock::getParent(), llvm::ilist_detail::node_parent_access< NodeTy, ParentTy >::getParent(), llvm::BasicBlock::isEHPad(), llvm::Constant::isNullValue(), LLVM_DEBUG, llvm::predecessors(), llvm::report_fatal_error(), and llvm::Value::users().
calculateStateNumbersForInvokes()
static void calculateStateNumbersForInvokes (const Function * Fn, WinEHFuncInfo & FuncInfo) static
Definition at line 189 of file WinEHPrepare.cpp.
References assert(), llvm::colorEHFunclets(), llvm::dyn_cast(), llvm::WinEHFuncInfo::EHPadStateMap, F, llvm::BasicBlock::front(), llvm::WinEHFuncInfo::FuncletBaseStateMap, getCleanupRetUnwindDest(), llvm::Function::getEntryBlock(), llvm::BasicBlock::getFirstNonPHI(), II, llvm::WinEHFuncInfo::InvokeStateMap, and llvm_unreachable.
Referenced by llvm::calculateClrEHStateNumbers(), llvm::calculateSEHStateNumbers(), and llvm::calculateWinCXXEHStateNumbers().
getCleanupRetUnwindDest()
static BasicBlock * getCleanupRetUnwindDest (const CleanupPadInst * CleanupPad) static
Definition at line 182 of file WinEHPrepare.cpp.
References llvm::dyn_cast(), and llvm::Value::users().
Referenced by calculateCXXStateNumbers(), calculateSEHStateNumbers(), calculateStateNumbersForInvokes(), and isTopLevelPadForMSVC().
getEHPadFromPredecessor()
static const BasicBlock * getEHPadFromPredecessor (const BasicBlock * BB, Value * ParentPad) static
Definition at line 356 of file WinEHPrepare.cpp.
References assert(), llvm::cast(), llvm::dyn_cast(), llvm::BasicBlock::getTerminator(), llvm::isa(), and llvm::Instruction::isEHPad().
Referenced by calculateCXXStateNumbers(), and calculateSEHStateNumbers().
INITIALIZE_PASS()
INITIALIZE_PASS (WinEHPrepare , DEBUG_TYPE , "Prepare Windows exceptions" , false , false)
Definition at line 124 of file WinEHPrepare.cpp.
isTopLevelPadForMSVC()
static bool isTopLevelPadForMSVC (const Instruction * EHPad) static
Definition at line 576 of file WinEHPrepare.cpp.
References llvm::dyn_cast(), getCleanupRetUnwindDest(), llvm::isa(), and llvm_unreachable.
Referenced by llvm::calculateSEHStateNumbers(), and llvm::calculateWinCXXEHStateNumbers().
Variable Documentation
DemoteCatchSwitchPHIOnlyOpt
cl::opt< bool > DemoteCatchSwitchPHIOnlyOpt("demote-catchswitch-only", cl::Hidden, cl::desc("Demote catchswitch BBs only (for wasm EH)"), cl::init(false)) ("demote-catchswitch-only" , cl::Hidden , cl::desc("Demote catchswitch BBs only (for wasm EH)") , cl::init(false)) static
DisableCleanups
cl::opt< bool > DisableCleanups("disable-cleanups", cl::Hidden, cl::desc("Do not remove implausible terminators or other similar cleanups"), cl::init(false)) ("disable-cleanups" , cl::Hidden , cl::desc("Do not remove implausible terminators or other similar cleanups") , cl::init(false)) static
DisableDemotion
cl::opt< bool > DisableDemotion("disable-demotion", cl::Hidden, cl::desc("Clone multicolor basic blocks but do not demote cross scopes"), cl::init(false)) ("disable-demotion" , cl::Hidden , cl::desc("Clone multicolor basic blocks but do not demote cross scopes") , cl::init(false)) static