LLVM: lib/Target/X86/X86ExpandPseudo.cpp File Reference
X86ExpandPseudo.cpp File Reference
#include "X86.h"
#include "X86FrameLowering.h"
#include "X86InstrBuilder.h"
#include "X86InstrInfo.h"
#include "X86MachineFunctionInfo.h"
#include "X86Subtarget.h"
#include "llvm/CodeGen/LivePhysRegs.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/EHPersonalities.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "x86-pseudo"
#define X86_EXPAND_PSEUDO_NAME "X86 pseudo instruction expansion pass"
#define GET_EGPR_IF_ENABLED(OPC)
#define MI_TO_RI(OP)
Functions
INITIALIZE_PASS (X86ExpandPseudo, DEBUG_TYPE, X86_EXPAND_PSEUDO_NAME, false, false) void X86ExpandPseudo
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "x86-pseudo"
Definition at line 30 of file X86ExpandPseudo.cpp.
GET_EGPR_IF_ENABLED
#define GET_EGPR_IF_ENABLED (OPC)
Value:
(STI->hasEGPR() ? OPC##_EVEX : OPC)
MI_TO_RI
#define MI_TO_RI (OP)
Value:
  case X86::OP##32mi_ND:                                                       \
    Opc = X86::OP##32ri;                                                       \
    LoadOpc = X86::MOV32rm;                                                    \
    break;                                                                     \
  case X86::OP##64mi32_ND:                                                     \
    Opc = X86::OP##64ri32;                                                     \
    LoadOpc = X86::MOV64rm;                                                    \
    break;
X86_EXPAND_PSEUDO_NAME
#define X86_EXPAND_PSEUDO_NAME "X86 pseudo instruction expansion pass"
Definition at line 31 of file X86ExpandPseudo.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (X86ExpandPseudo , DEBUG_TYPE , X86_EXPAND_PSEUDO_NAME , false , false)
Definition at line 87 of file X86ExpandPseudo.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addGlobalAddress(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::BuildMI(), CC, llvm::X86::COND_B, llvm::X86::COND_E, llvm::MachineFunction::CreateMachineBasicBlock(), DL, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), FirstTarget, llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::insert(), llvm::MachineBasicBlock::isLiveIn(), llvm::MachineOperand::isReg(), MBB, MBBI, P, and TII.