LLVM: lib/Target/Xtensa/MCTargetDesc/XtensaMCTargetDesc.cpp File Reference
XtensaMCTargetDesc.cpp File Reference
#include "XtensaMCTargetDesc.h"
#include "TargetInfo/XtensaTargetInfo.h"
#include "XtensaInstPrinter.h"
#include "XtensaMCAsmInfo.h"
#include "XtensaTargetStreamer.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "XtensaGenInstrInfo.inc"
#include "XtensaGenRegisterInfo.inc"
#include "XtensaGenSubtargetInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define GET_REGINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Functions
static MCAsmInfo * createXtensaMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
static MCInstrInfo * createXtensaMCInstrInfo ()
static MCInstPrinter * createXtensaMCInstPrinter (const Triple &TT, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCRegisterInfo * createXtensaMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createXtensaMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCTargetStreamer * createXtensaAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrint)
static MCTargetStreamer * createXtensaObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXtensaTargetMC ()
Macro Definition Documentation
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 24 of file XtensaMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 27 of file XtensaMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 30 of file XtensaMCTargetDesc.cpp.
Function Documentation
createXtensaAsmTargetStreamer()
static MCTargetStreamer * createXtensaAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrint) static
Definition at line 68 of file XtensaMCTargetDesc.cpp.
References OS.
Referenced by LLVMInitializeXtensaTargetMC().
createXtensaMCAsmInfo()
static MCAsmInfo * createXtensaMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT, const MCTargetOptions & Options) static
Definition at line 35 of file XtensaMCTargetDesc.cpp.
Referenced by LLVMInitializeXtensaTargetMC().
createXtensaMCInstPrinter()
static MCInstPrinter * createXtensaMCInstPrinter (const Triple & TT, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 48 of file XtensaMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeXtensaTargetMC().
createXtensaMCInstrInfo()
static MCInstrInfo * createXtensaMCInstrInfo () static
Definition at line 42 of file XtensaMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeXtensaTargetMC().
createXtensaMCRegisterInfo()
static MCRegisterInfo * createXtensaMCRegisterInfo (const Triple & TT) static
Definition at line 56 of file XtensaMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeXtensaTargetMC().
createXtensaMCSubtargetInfo()
static MCSubtargetInfo * createXtensaMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 63 of file XtensaMCTargetDesc.cpp.
Referenced by LLVMInitializeXtensaTargetMC().
createXtensaObjectTargetStreamer()
static MCTargetStreamer * createXtensaObjectTargetStreamer (MCStreamer & S, const MCSubtargetInfo & STI) static
Definition at line 74 of file XtensaMCTargetDesc.cpp.
Referenced by LLVMInitializeXtensaTargetMC().
LLVMInitializeXtensaTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeXtensaTargetMC ()
Definition at line 78 of file XtensaMCTargetDesc.cpp.
References createXtensaAsmTargetStreamer(), llvm::createXtensaMCAsmBackend(), createXtensaMCAsmInfo(), llvm::createXtensaMCCodeEmitter(), createXtensaMCInstPrinter(), createXtensaMCInstrInfo(), createXtensaMCRegisterInfo(), createXtensaMCSubtargetInfo(), createXtensaObjectTargetStreamer(), llvm::getTheXtensaTarget(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCAsmInfo(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), and llvm::TargetRegistry::RegisterObjectTargetStreamer().