LLVM: lib/Target/Xtensa/XtensaISelLowering.cpp File Reference
XtensaISelLowering.cpp File Reference
#include "XtensaISelLowering.h"
#include "XtensaConstantPoolValue.h"
#include "XtensaSubtarget.h"
#include "XtensaTargetMachine.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <deque>
#include "XtensaGenCallingConv.inc"
Macros
#define DEBUG_TYPE "xtensa-lower"
Functions
static bool isLongCall (const char *str)
static bool CC_Xtensa_Custom (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState &State)
static unsigned getBranchOpcode (ISD::CondCode Cond)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "xtensa-lower"
Definition at line 32 of file XtensaISelLowering.cpp.
Function Documentation
CC_Xtensa_Custom()
static bool CC_Xtensa_Custom (unsigned ValNo, MVT ValVT, MVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, CCState & State) static
Definition at line 123 of file XtensaISelLowering.cpp.
References llvm::CCValAssign::AExt, Align, llvm::ISD::ArgFlagsTy::getByValSize(), llvm::CCValAssign::getMem(), llvm::ISD::ArgFlagsTy::getNonZeroByValAlign(), llvm::ISD::ArgFlagsTy::getNonZeroOrigAlign(), llvm::CCValAssign::getReg(), llvm::MVT::getStoreSize(), IntRegs, llvm::ISD::ArgFlagsTy::isByVal(), llvm::ISD::ArgFlagsTy::isSExt(), llvm::ISD::ArgFlagsTy::isZExt(), llvm::Offset, Register, llvm::report_fatal_error(), llvm::CCValAssign::SExt, and llvm::CCValAssign::ZExt.
getBranchOpcode()
static unsigned getBranchOpcode (ISD::CondCode Cond) static
Definition at line 525 of file XtensaISelLowering.cpp.
References Cond, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, and llvm::ISD::SETULT.
isLongCall()
static bool isLongCall (const char * str) static
Definition at line 37 of file XtensaISelLowering.cpp.
Referenced by llvm::XtensaTargetLowering::LowerCall().