LLVM: lib/Target/Xtensa/MCTargetDesc/XtensaTargetStreamer.cpp File Reference
XtensaTargetStreamer.cpp File Reference
#include "XtensaTargetStreamer.h"
#include "XtensaInstPrinter.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/FormattedStream.h"
Functions
static std::string getLiteralSectionName (StringRef CSectionName)
Function Documentation
getLiteralSectionName()
static std::string getLiteralSectionName (StringRef CSectionName) static
Definition at line 25 of file XtensaTargetStreamer.cpp.
References llvm::StringRef::consume_front(), llvm::StringRef::drop_front(), llvm::StringRef::find(), and llvm::StringRef::substr().
Referenced by llvm::XtensaTargetELFStreamer::emitLiteral(), and llvm::XtensaTargetELFStreamer::startLiteralSection().