LLVM: lib/Target/Xtensa/XtensaInstrInfo.cpp File Reference
XtensaInstrInfo.cpp File Reference
#include "XtensaInstrInfo.h"
#include "XtensaTargetMachine.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "XtensaGenInstrInfo.inc"
Macros
#define GET_INSTRINFO_CTOR_DTOR
Functions
static const MachineInstrBuilder & addFrameReference (const MachineInstrBuilder &MIB, int FI)
Macro Definition Documentation
GET_INSTRINFO_CTOR_DTOR
#define GET_INSTRINFO_CTOR_DTOR
Definition at line 22 of file XtensaInstrInfo.cpp.
Function Documentation
addFrameReference()
static const MachineInstrBuilder & addFrameReference (const MachineInstrBuilder & MIB, int FI) static
Definition at line 28 of file XtensaInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlign(), llvm::MachineFrameInfo::getObjectSize(), llvm::MCInstrDesc::mayLoad(), llvm::MCInstrDesc::mayStore(), MI, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MONone, llvm::MachineMemOperand::MOStore, and llvm::Offset.