LLVM: lib/Remarks/YAMLRemarkParser.cpp File Reference
YAMLRemarkParser.cpp File Reference
#include "YAMLRemarkParser.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Path.h"
#include <optional>
Functions
static void handleDiagnostic (const SMDiagnostic &Diag, void *Ctx)
static SourceMgr setupSM (std::string &LastErrorMessage)
static Expected< bool > parseMagic (StringRef &Buf)
static Expected< uint64_t > parseVersion (StringRef &Buf)
static Expected< uint64_t > parseStrTabSize (StringRef &Buf)
static Expected< ParsedStringTable > parseStrTab (StringRef &Buf, uint64_t StrTabSize)
Function Documentation
handleDiagnostic()
static void handleDiagnostic (const SMDiagnostic & Diag, void * Ctx) static
Definition at line 26 of file YAMLRemarkParser.cpp.
References assert(), llvm::raw_ostream::flush(), OS, and llvm::SMDiagnostic::print().
Referenced by setupSM(), and llvm::remarks::YAMLParseError::YAMLParseError().
parseMagic()
static Expected< bool > parseMagic (StringRef & Buf) static
Definition at line 62 of file YAMLRemarkParser.cpp.
References llvm::StringRef::consume_front(), llvm::createStringError(), llvm::remarks::Magic(), and llvm::StringRef::size().
Referenced by llvm::remarks::createYAMLParserFromMeta().
parseStrTab()
static Expected< ParsedStringTable > parseStrTab (StringRef & Buf, uint64_t StrTabSize) static
Definition at line 98 of file YAMLRemarkParser.cpp.
References llvm::createStringError(), llvm::StringRef::data(), llvm::StringRef::drop_front(), and llvm::StringRef::size().
Referenced by llvm::remarks::createYAMLParserFromMeta().
parseStrTabSize()
static Expected< uint64_t > parseStrTabSize (StringRef & Buf) static
Definition at line 88 of file YAMLRemarkParser.cpp.
References llvm::createStringError(), llvm::StringRef::data(), llvm::StringRef::drop_front(), llvm::support::endian::read(), and llvm::StringRef::size().
Referenced by llvm::remarks::createYAMLParserFromMeta().
parseVersion()
static Expected< uint64_t > parseVersion (StringRef & Buf) static
Definition at line 72 of file YAMLRemarkParser.cpp.
References llvm::createStringError(), llvm::remarks::CurrentRemarkVersion, llvm::StringRef::data(), llvm::StringRef::drop_front(), llvm::support::endian::read(), llvm::StringRef::size(), and llvm::Version.
setupSM()
static SourceMgr setupSM (std::string & LastErrorMessage) static
Definition at line 54 of file YAMLRemarkParser.cpp.
References handleDiagnostic(), and llvm::SourceMgr::setDiagHandler().