LLVM: lib/Target/AArch64/MCTargetDesc/AArch64MCTargetDesc.cpp File Reference
AArch64MCTargetDesc.cpp File Reference
#include "AArch64MCTargetDesc.h"
#include "AArch64ELFStreamer.h"
#include "AArch64MCAsmInfo.h"
#include "AArch64WinCOFFStreamer.h"
#include "MCTargetDesc/AArch64AddressingModes.h"
#include "MCTargetDesc/AArch64InstPrinter.h"
#include "TargetInfo/AArch64TargetInfo.h"
#include "llvm/DebugInfo/CodeView/CodeView.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/ErrorHandling.h"
#include "AArch64GenInstrInfo.inc"
#include "AArch64GenSubtargetInfo.inc"
#include "AArch64GenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_HELPERS
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createAArch64MCInstrInfo ()
static MCSubtargetInfo * createAArch64MCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCRegisterInfo * createAArch64MCRegisterInfo (const Triple &Triple)
static MCAsmInfo * createAArch64MCAsmInfo (const MCRegisterInfo &MRI, const Triple &TheTriple, const MCTargetOptions &Options)
static MCInstPrinter * createAArch64MCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCStreamer * createELFStreamer (const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
static MCStreamer * createMachOStreamer (MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll, bool DWARFMustBeAtTheEnd)
static MCStreamer * createWinCOFFStreamer (MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&TAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll, bool IncrementalLinkerCompatible)
static MCInstrAnalysis * createAArch64InstrAnalysis (const MCInstrInfo *Info)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAArch64TargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 37 of file AArch64MCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 35 of file AArch64MCTargetDesc.cpp.
GET_INSTRINFO_MC_HELPERS
#define GET_INSTRINFO_MC_HELPERS
Definition at line 36 of file AArch64MCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 43 of file AArch64MCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 40 of file AArch64MCTargetDesc.cpp.
Function Documentation
createAArch64InstrAnalysis()
static MCInstrAnalysis * createAArch64InstrAnalysis (const MCInstrInfo * Info) static
Definition at line 470 of file AArch64MCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeAArch64TargetMC().
createAArch64MCAsmInfo()
static MCAsmInfo * createAArch64MCAsmInfo (const MCRegisterInfo & MRI, const Triple & TheTriple, const MCTargetOptions & Options) static
Definition at line 342 of file AArch64MCTargetDesc.cpp.
References llvm::Triple::aarch64_32, llvm::MCAsmInfo::addInitialFrameState(), assert(), llvm::MCCFIInstruction::cfiDefCfa(), llvm::Triple::getArch(), llvm::Triple::isOSBinFormatCOFF(), llvm::Triple::isOSBinFormatELF(), llvm::Triple::isOSBinFormatMachO(), llvm::Triple::isWindowsMSVCEnvironment(), and MRI.
Referenced by LLVMInitializeAArch64TargetMC().
createAArch64MCInstPrinter()
static MCInstPrinter * createAArch64MCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 365 of file AArch64MCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeAArch64TargetMC().
createAArch64MCInstrInfo()
static MCInstrInfo * createAArch64MCInstrInfo () static
Definition at line 46 of file AArch64MCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeAArch64TargetMC().
createAArch64MCRegisterInfo()
static MCRegisterInfo * createAArch64MCRegisterInfo (const Triple & Triple) static
Definition at line 335 of file AArch64MCTargetDesc.cpp.
References llvm::AArch64_MC::initLLVMToCVRegMapping(), and X.
Referenced by LLVMInitializeAArch64TargetMC().
createAArch64MCSubtargetInfo()
static MCSubtargetInfo * createAArch64MCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 53 of file AArch64MCTargetDesc.cpp.
References llvm::StringRef::empty().
Referenced by LLVMInitializeAArch64TargetMC().
createELFStreamer()
static MCStreamer * createELFStreamer (const Triple & T, MCContext & Ctx, std::unique_ptr< MCAsmBackend > && TAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll) static
Definition at line 378 of file AArch64MCTargetDesc.cpp.
References llvm::createAArch64ELFStreamer(), and Emitter.
Referenced by LLVMInitializeAArch64TargetMC().
createMachOStreamer()
static MCStreamer * createMachOStreamer (MCContext & Ctx, std::unique_ptr< MCAsmBackend > && TAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll, bool DWARFMustBeAtTheEnd) static
Definition at line 387 of file AArch64MCTargetDesc.cpp.
References createMachOStreamer(), and Emitter.
Referenced by createMachOStreamer(), and LLVMInitializeAArch64TargetMC().
createWinCOFFStreamer()
static MCStreamer * createWinCOFFStreamer (MCContext & Ctx, std::unique_ptr< MCAsmBackend > && TAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll, bool IncrementalLinkerCompatible) static
Definition at line 399 of file AArch64MCTargetDesc.cpp.
References llvm::createAArch64WinCOFFStreamer(), and Emitter.
Referenced by LLVMInitializeAArch64TargetMC().
LLVMInitializeAArch64TargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAArch64TargetMC ()
Definition at line 475 of file AArch64MCTargetDesc.cpp.
References llvm::createAArch64AsmTargetStreamer(), llvm::createAArch64beAsmBackend(), createAArch64InstrAnalysis(), llvm::createAArch64leAsmBackend(), createAArch64MCAsmInfo(), llvm::createAArch64MCCodeEmitter(), createAArch64MCInstPrinter(), createAArch64MCInstrInfo(), createAArch64MCRegisterInfo(), createAArch64MCSubtargetInfo(), llvm::createAArch64NullTargetStreamer(), llvm::createAArch64ObjectTargetStreamer(), createELFStreamer(), createMachOStreamer(), createWinCOFFStreamer(), llvm::getTheAArch64_32Target(), llvm::getTheAArch64beTarget(), llvm::getTheAArch64leTarget(), llvm::getTheARM64_32Target(), llvm::getTheARM64Target(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterCOFFStreamer(), llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMachOStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), llvm::TargetRegistry::RegisterObjectTargetStreamer(), and X.