LLVM: lib/CodeGen/AsmPrinter/AccelTable.cpp File Reference
AccelTable.cpp File Reference
#include "llvm/CodeGen/AccelTable.h"
#include "DwarfCompileUnit.h"
#include "DwarfUnit.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/DIE.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <vector>
Enumerations
enum IdxParentEncoding : uint8_t { NoIndexedParent = 0 , Ref4 = 1 , NoParent = 2 }
Functions
uint8_t encodeIdxParent (const std::optional< dwarf::Form > MaybeParentForm)
static uint32_t getTagFromAbbreviationTag (const uint32_t AbbrvTag)
static uint32_t constructAbbreviationTag (const unsigned Tag, const std::optional< DWARF5AccelTable::UnitIndexAndEncoding > &EntryRet, std::optional< dwarf::Form > MaybeParentForm)
Constructs a unique AbbrevTag that captures what a DIE accesses.
static std::optional< dwarf::Form > getFormForIdxParent (const DenseSet< OffsetAndUnitID > &IndexedOffsets, std::optional< OffsetAndUnitID > ParentOffset)
Variables
static uint32_t constexpr NumBitsIdxParent = 2
static uint32_t constexpr ParentBitOffset = dwarf::DW_IDX_type_hash
static uint32_t constexpr TagBitOffset = ParentBitOffset + NumBitsIdxParent
Enumeration Type Documentation
IdxParentEncoding
enum IdxParentEncoding : uint8_t
Enumerator
NoIndexedParent
Ref4
Parent information present but parent isn't indexed.
NoParent
Parent information present and parent is indexed.
Definition at line 412 of file AccelTable.cpp.
Function Documentation
constructAbbreviationTag()
static uint32_t constructAbbreviationTag (const unsigned Tag, const std::optional< DWARF5AccelTable::UnitIndexAndEncoding > & EntryRet, std::optional< dwarf::Form > MaybeParentForm) static
Constructs a unique AbbrevTag that captures what a DIE accesses.
Using this tag we can emit a unique abbreviation for each DIE.
Definition at line 443 of file AccelTable.cpp.
References encodeIdxParent(), ParentBitOffset, and TagBitOffset.
encodeIdxParent()
uint8_t encodeIdxParent (const std::optional< dwarf::Form > MaybeParentForm)
Definition at line 420 of file AccelTable.cpp.
References llvm_unreachable, NoIndexedParent, NoParent, and Ref4.
Referenced by constructAbbreviationTag().
getFormForIdxParent()
static std::optional< dwarf::Form > getFormForIdxParent (const DenseSet< OffsetAndUnitID > & IndexedOffsets, std::optional< OffsetAndUnitID > ParentOffset) static
Definition at line 458 of file AccelTable.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::contains().
getTagFromAbbreviationTag()
static uint32_t getTagFromAbbreviationTag (const uint32_t AbbrvTag) static
Definition at line 437 of file AccelTable.cpp.
References TagBitOffset.
Variable Documentation
NumBitsIdxParent
uint32_t constexpr NumBitsIdxParent = 2 static constexpr
Definition at line 418 of file AccelTable.cpp.
ParentBitOffset
uint32_t constexpr ParentBitOffset = dwarf::DW_IDX_type_hash static constexpr
Definition at line 435 of file AccelTable.cpp.
Referenced by constructAbbreviationTag().
TagBitOffset
uint32_t constexpr TagBitOffset = ParentBitOffset + NumBitsIdxParent static constexpr
Definition at line 436 of file AccelTable.cpp.
Referenced by constructAbbreviationTag(), and getTagFromAbbreviationTag().