LLVM: lib/Target/AMDGPU/AMDGPULowerKernelAttributes.cpp File Reference
AMDGPULowerKernelAttributes.cpp File Reference
#include "AMDGPU.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/Pass.h"
Macros
#define DEBUG_TYPE "amdgpu-lower-kernel-attributes"
Functions
static bool processUse (CallInst *CI, bool IsV5OrAbove)
INITIALIZE_PASS_BEGIN (AMDGPULowerKernelAttributes, DEBUG_TYPE, "AMDGPU Kernel Attributes", false, false) INITIALIZE_PASS_END(AMDGPULowerKernelAttributes
Variables
DEBUG_TYPE
AMDGPU Kernel Attributes
AMDGPU Kernel false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-lower-kernel-attributes"
Definition at line 29 of file AMDGPULowerKernelAttributes.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AMDGPULowerKernelAttributes , DEBUG_TYPE , "AMDGPU Kernel Attributes" , false , false)
processUse()
static bool processUse (CallInst * CI, bool IsV5OrAbove) static
Definition at line 87 of file AMDGPULowerKernelAttributes.cpp.
References llvm::ConstantFoldIntegerCast(), DL, F, llvm::Constant::getNullValue(), llvm::BasicBlock::getParent(), llvm::Instruction::getParent(), llvm::GetPointerBaseWithConstantOffset(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), I, llvm::PatternMatch::m_ICmp(), llvm::PatternMatch::m_Mul(), llvm::PatternMatch::m_Specific(), llvm::PatternMatch::m_Sub(), llvm::PatternMatch::m_UMin(), llvm::PatternMatch::match(), llvm::Offset, llvm::Value::replaceAllUsesWith(), llvm::UMin, and llvm::Value::users().
Referenced by llvm::rdf::DeadCodeElimination::collect(), and llvm::AMDGPULowerKernelAttributesPass::run().
Variable Documentation
Attributes
AMDGPU Kernel Attributes
Definition at line 349 of file AMDGPULowerKernelAttributes.cpp.
Referenced by llvm::DWARFDebugNames::Abbrev::dump(), llvm::ModuleSummaryIndex::exportToDot(), llvm::PseudoProbeSDNode::getAttributes(), llvm::DIObjCProperty::getAttributes(), llvm::object::ELFObjectFile< ELFT >::getBuildAttributes(), llvm::MDNodeKeyImpl< DIObjCProperty >::getHashValue(), llvm::MDNodeKeyImpl< DIObjCProperty >::isKeyOf(), llvm::MDNodeKeyImpl< DIObjCProperty >::MDNodeKeyImpl(), ParseLine(), parseMetadata(), llvm::logicalview::LVScopeFunction::printExtra(), llvm::logicalview::LVSymbol::printExtra(), llvm::logicalview::LVTypeImport::printExtra(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncMetadata(), llvm::sampleprof::SampleProfileReaderText::readImpl(), and llvm::object::ELFObjectFileBase::setARMSubArch().
DEBUG_TYPE
DEBUG_TYPE
Definition at line 348 of file AMDGPULowerKernelAttributes.cpp.
false
AMDGPU Kernel false
Definition at line 349 of file AMDGPULowerKernelAttributes.cpp.