LLVM: lib/Target/AMDGPU/AsmParser/AMDGPUAsmParser.cpp File Reference
AMDGPUAsmParser.cpp File Reference
#include "AMDKernelCodeT.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "MCTargetDesc/AMDGPUTargetStreamer.h"
#include "SIDefines.h"
#include "SIInstrInfo.h"
#include "SIRegisterInfo.h"
#include "TargetInfo/AMDGPUTargetInfo.h"
#include "Utils/AMDGPUAsmUtils.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "Utils/AMDKernelCodeTUtils.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/CodeGen/MachineValueType.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/AMDGPUMetadata.h"
#include "llvm/Support/AMDHSAKernelDescriptor.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/TargetParser/TargetParser.h"
#include <optional>
#include "AMDGPUGenAsmMatcher.inc"
Classes
struct RegInfo
Macros
#define PARSE_BITS_ENTRY(FIELD, ENTRY, VALUE, RANGE)
#define GET_REGISTER_MATCHER
#define GET_MATCHER_IMPLEMENTATION
#define GET_MNEMONIC_SPELL_CHECKER
#define GET_MNEMONIC_CHECKER
Auto-generated Match Functions
{
#define GET_ASSEMBLER_HEADER
Typedefs
using OperandIndices = SmallVector< int16_t, MAX_SRC_OPERANDS_NUM >
Functions
static const fltSemantics * getFltSemantics (unsigned Size)
static const fltSemantics * getFltSemantics (MVT VT)
static const fltSemantics * getOpFltSemantics (uint8_t OperandType)
static bool canLosslesslyConvertToFPType (APFloat &FPLiteral, MVT VT)
static bool isSafeTruncation (int64_t Val, unsigned Size)
static bool isInlineableLiteralOp16 (int64_t Val, MVT VT, bool HasInv2Pi)
static int getRegClass (RegisterKind Is, unsigned RegWidth)
static unsigned getSpecialRegForName (StringRef RegName)
static bool isRegularReg (RegisterKind Kind)
static const RegInfo * getRegularRegInfo (StringRef Str)
static bool getRegNum (StringRef Str, unsigned &Num)
static ArrayRef< unsigned > getAllVariants ()
static OperandIndices getSrcOperandIndices (unsigned Opcode, bool AddMandatoryLiterals=false)
static bool IsMovrelsSDWAOpcode (const unsigned Opcode)
static bool IsRevOpcode (const unsigned Opcode)
static int IsAGPROperand (const MCInst &Inst, uint16_t NameIdx, const MCRegisterInfo *MRI)
static std::string AMDGPUMnemonicSpellCheck (StringRef S, const FeatureBitset &FBS, unsigned VariantID=0)
static bool AMDGPUCheckMnemonic (StringRef Mnemonic, const FeatureBitset &AvailableFeatures, unsigned VariantID)
static bool isInvalidVOPDY (const OperandVector &Operands, uint64_t InvalidOprIdx)
static void applyMnemonicAliases (StringRef &Mnemonic, const FeatureBitset &Features, unsigned VariantID)
static void addOptionalImmOperand (MCInst &Inst, const OperandVector &Operands, AMDGPUAsmParser::OptionalImmIndexMap &OptionalIdx, AMDGPUOperand::ImmTy ImmT, int64_t Default=0)
static bool encodeCnt (const AMDGPU::IsaVersion ISA, int64_t &IntVal, int64_t CntVal, bool Saturate, unsigned(*encode)(const IsaVersion &Version, unsigned, unsigned), unsigned(*decode)(const IsaVersion &Version, unsigned))
static LLVM_READNONE unsigned encodeBitmaskPerm (const unsigned AndMask, const unsigned OrMask, const unsigned XorMask)
static bool ConvertOmodMul (int64_t &Mul)
static bool ConvertOmodDiv (int64_t &Div)
void cvtVOP3DstOpSelOnly (MCInst &Inst)
static bool isRegOrImmWithInputMods (const MCInstrDesc &Desc, unsigned OpNum)
static void addSrcModifiersAndSrc (MCInst &Inst, const OperandVector &Operands, unsigned i, unsigned Opc, unsigned OpName)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUAsmParser ()
Force static initialization.
Variables
static constexpr RegInfo RegularRegisters []
constexpr unsigned MAX_SRC_OPERANDS_NUM = 6
constexpr uint64_t MIMGFlags
Macro Definition Documentation
GET_ASSEMBLER_HEADER
#define GET_ASSEMBLER_HEADER
Definition at line 1298 of file AMDGPUAsmParser.cpp.
GET_MATCHER_IMPLEMENTATION
#define GET_MATCHER_IMPLEMENTATION
Definition at line 9217 of file AMDGPUAsmParser.cpp.
GET_MNEMONIC_CHECKER
#define GET_MNEMONIC_CHECKER
Definition at line 9219 of file AMDGPUAsmParser.cpp.
GET_MNEMONIC_SPELL_CHECKER
#define GET_MNEMONIC_SPELL_CHECKER
Definition at line 9218 of file AMDGPUAsmParser.cpp.
GET_REGISTER_MATCHER
#define GET_REGISTER_MATCHER
Definition at line 9216 of file AMDGPUAsmParser.cpp.
PARSE_BITS_ENTRY
#define PARSE_BITS_ENTRY (FIELD, ENTRY, VALUE, RANGE)
Value:
  if (!isUInt<ENTRY##_WIDTH>(VALUE))                                           \
    return OutOfRangeError(RANGE);                                             \
  AMDHSA_BITS_SET(FIELD, ENTRY, VALUE);
Typedef Documentation
OperandIndices
using OperandIndices = SmallVector<int16_t, MAX_SRC_OPERANDS_NUM>
Definition at line 3498 of file AMDGPUAsmParser.cpp.
Function Documentation
addOptionalImmOperand()
static void addOptionalImmOperand (MCInst & Inst, const OperandVector & Operands, AMDGPUAsmParser::OptionalImmIndexMap & OptionalIdx, AMDGPUOperand::ImmTy ImmT, int64_t Default = 0) static
Definition at line 6454 of file AMDGPUAsmParser.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), Default, Idx, and Operands.
addSrcModifiersAndSrc()
static void addSrcModifiersAndSrc (MCInst & Inst, const OperandVector & Operands, unsigned i, unsigned Opc, unsigned OpName) static
Definition at line 8468 of file AMDGPUAsmParser.cpp.
References llvm::AMDGPU::getNamedOperandIdx(), and Operands.
AMDGPUCheckMnemonic()
static bool AMDGPUCheckMnemonic (StringRef Mnemonic, const FeatureBitset & AvailableFeatures, unsigned VariantID) static
AMDGPUMnemonicSpellCheck()
static std::string AMDGPUMnemonicSpellCheck (StringRef S, const FeatureBitset & FBS, unsigned VariantID = 0) static
applyMnemonicAliases()
static void applyMnemonicAliases (StringRef & Mnemonic, const FeatureBitset & Features, unsigned VariantID) static
canLosslesslyConvertToFPType()
static bool canLosslesslyConvertToFPType (APFloat & FPLiteral, MVT VT) static
Definition at line 1927 of file AMDGPUAsmParser.cpp.
References llvm::APFloat::convert(), and getFltSemantics().
ConvertOmodDiv()
static bool ConvertOmodDiv (int64_t & Div) static
Definition at line 8108 of file AMDGPUAsmParser.cpp.
ConvertOmodMul()
static bool ConvertOmodMul (int64_t & Mul) static
Definition at line 8100 of file AMDGPUAsmParser.cpp.
References Mul.
cvtVOP3DstOpSelOnly()
void cvtVOP3DstOpSelOnly (MCInst & Inst)
Definition at line 8164 of file AMDGPUAsmParser.cpp.
References assert(), llvm::SISrcMods::DST_OP_SEL, llvm::MCOperand::getImm(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::AMDGPU::hasNamedOperand(), and llvm::MCOperand::setImm().
encodeBitmaskPerm()
static LLVM_READNONE unsigned encodeBitmaskPerm (const unsigned AndMask, const unsigned OrMask, const unsigned XorMask) static
Definition at line 7647 of file AMDGPUAsmParser.cpp.
encodeCnt()
static bool encodeCnt (const AMDGPU::IsaVersion ISA, int64_t & IntVal, int64_t CntVal, bool Saturate, unsigned(*)(const IsaVersion &Version, unsigned, unsigned) encode, unsigned(*)(const IsaVersion &Version, unsigned) decode) static
Definition at line 6844 of file AMDGPUAsmParser.cpp.
References decode(), llvm::encode(), and llvm::Failed().
getAllVariants()
static ArrayRef< unsigned > getAllVariants () static
Definition at line 3346 of file AMDGPUAsmParser.cpp.
References llvm::AMDGPUAsmVariants::DEFAULT, llvm::AMDGPUAsmVariants::DPP, llvm::AMDGPUAsmVariants::SDWA, llvm::AMDGPUAsmVariants::SDWA9, llvm::AMDGPUAsmVariants::VOP3, and llvm::AMDGPUAsmVariants::VOP3_DPP.
getFltSemantics() [1/2]
static const fltSemantics * getFltSemantics (MVT VT) static
Definition at line 1877 of file AMDGPUAsmParser.cpp.
References getFltSemantics(), and llvm::MVT::getSizeInBits().
getFltSemantics() [2/2]
static const fltSemantics * getFltSemantics (unsigned Size) static
Definition at line 1864 of file AMDGPUAsmParser.cpp.
References llvm_unreachable, and Size.
Referenced by canLosslesslyConvertToFPType(), and getFltSemantics().
getOpFltSemantics()
static const fltSemantics * getOpFltSemantics (uint8_t OperandType) static
Definition at line 1881 of file AMDGPUAsmParser.cpp.
References llvm_unreachable, llvm::AMDGPU::OPERAND_INLINE_SPLIT_BARRIER_INT32, llvm::AMDGPU::OPERAND_KIMM16, llvm::AMDGPU::OPERAND_KIMM32, llvm::AMDGPU::OPERAND_REG_IMM_FP16, llvm::AMDGPU::OPERAND_REG_IMM_FP16_DEFERRED, llvm::AMDGPU::OPERAND_REG_IMM_FP32, llvm::AMDGPU::OPERAND_REG_IMM_FP32_DEFERRED, llvm::AMDGPU::OPERAND_REG_IMM_FP64, llvm::AMDGPU::OPERAND_REG_IMM_INT16, llvm::AMDGPU::OPERAND_REG_IMM_INT32, llvm::AMDGPU::OPERAND_REG_IMM_INT64, llvm::AMDGPU::OPERAND_REG_IMM_V2FP16, llvm::AMDGPU::OPERAND_REG_IMM_V2FP32, llvm::AMDGPU::OPERAND_REG_IMM_V2INT16, llvm::AMDGPU::OPERAND_REG_IMM_V2INT32, llvm::AMDGPU::OPERAND_REG_INLINE_AC_FP16, llvm::AMDGPU::OPERAND_REG_INLINE_AC_FP32, llvm::AMDGPU::OPERAND_REG_INLINE_AC_FP64, llvm::AMDGPU::OPERAND_REG_INLINE_AC_INT16, llvm::AMDGPU::OPERAND_REG_INLINE_AC_INT32, llvm::AMDGPU::OPERAND_REG_INLINE_AC_V2FP16, llvm::AMDGPU::OPERAND_REG_INLINE_AC_V2INT16, llvm::AMDGPU::OPERAND_REG_INLINE_C_FP16, llvm::AMDGPU::OPERAND_REG_INLINE_C_FP32, llvm::AMDGPU::OPERAND_REG_INLINE_C_FP64, llvm::AMDGPU::OPERAND_REG_INLINE_C_INT16, llvm::AMDGPU::OPERAND_REG_INLINE_C_INT32, llvm::AMDGPU::OPERAND_REG_INLINE_C_INT64, llvm::AMDGPU::OPERAND_REG_INLINE_C_V2FP16, llvm::AMDGPU::OPERAND_REG_INLINE_C_V2FP32, llvm::AMDGPU::OPERAND_REG_INLINE_C_V2INT16, and llvm::AMDGPU::OPERAND_REG_INLINE_C_V2INT32.
getRegClass()
static int getRegClass (RegisterKind Is, unsigned RegWidth) static
Definition at line 2359 of file AMDGPUAsmParser.cpp.
getRegNum()
static bool getRegNum (StringRef Str, unsigned & Num) static
Definition at line 2623 of file AMDGPUAsmParser.cpp.
getRegularRegInfo()
static const RegInfo * getRegularRegInfo (StringRef Str) static
Definition at line 2616 of file AMDGPUAsmParser.cpp.
References RegularRegisters.
getSpecialRegForName()
static unsigned getSpecialRegForName (StringRef RegName) static
Definition at line 2472 of file AMDGPUAsmParser.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), and RegName.
getSrcOperandIndices()
static OperandIndices getSrcOperandIndices (unsigned Opcode, bool AddMandatoryLiterals = false) static
Definition at line 3502 of file AMDGPUAsmParser.cpp.
References llvm::AMDGPU::getNamedOperandIdx(), and llvm::AMDGPU::isVOPD().
IsAGPROperand()
static int IsAGPROperand (const MCInst & Inst, uint16_t NameIdx, const MCRegisterInfo * MRI) static
Definition at line 4541 of file AMDGPUAsmParser.cpp.
References llvm::MCRegisterClass::contains(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), and MRI.
Referenced by decodeOperand_AVLdSt_Any().
isInlineableLiteralOp16()
static bool isInlineableLiteralOp16 (int64_t Val, MVT VT, bool HasInv2Pi) static
Definition at line 1949 of file AMDGPUAsmParser.cpp.
References llvm::MVT::getScalarType(), llvm::AMDGPU::isInlinableIntLiteral(), and llvm::AMDGPU::isInlinableLiteral16().
isInvalidVOPDY()
static bool isInvalidVOPDY (const OperandVector & Operands, uint64_t InvalidOprIdx) static
Definition at line 5072 of file AMDGPUAsmParser.cpp.
References assert(), and Operands.
IsMovrelsSDWAOpcode()
static bool IsMovrelsSDWAOpcode (const unsigned Opcode) static
Definition at line 3867 of file AMDGPUAsmParser.cpp.
isRegOrImmWithInputMods()
static bool isRegOrImmWithInputMods (const MCInstrDesc & Desc, unsigned OpNum) static
Definition at line 8200 of file AMDGPUAsmParser.cpp.
References llvm::AMDGPU::OPERAND_INPUT_MODS.
isRegularReg()
static bool isRegularReg (RegisterKind Kind) static
Definition at line 2609 of file AMDGPUAsmParser.cpp.
IsRevOpcode()
static bool IsRevOpcode (const unsigned Opcode) static
Definition at line 4037 of file AMDGPUAsmParser.cpp.
isSafeTruncation()
static bool isSafeTruncation (int64_t Val, unsigned Size) static
Definition at line 1945 of file AMDGPUAsmParser.cpp.
References llvm::isIntN(), llvm::isUIntN(), and Size.
LLVMInitializeAMDGPUAsmParser()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeAMDGPUAsmParser ()
Force static initialization.
Definition at line 9211 of file AMDGPUAsmParser.cpp.
References A, B, llvm::getTheGCNTarget(), and llvm::getTheR600Target().
Variable Documentation
MAX_SRC_OPERANDS_NUM
constexpr unsigned MAX_SRC_OPERANDS_NUM = 6 constexpr
Definition at line 3497 of file AMDGPUAsmParser.cpp.
MIMGFlags
constexpr uint64_t MIMGFlags constexpr
Initial value:
=
    SIInstrFlags::MIMG | SIInstrFlags::VIMAGE | SIInstrFlags::VSAMPLE
Definition at line 3686 of file AMDGPUAsmParser.cpp.
RegularRegisters
constexpr RegInfo RegularRegisters[] static constexpr
Initial value:
= {
  {{"v"},    IS_VGPR},
  {{"s"},    IS_SGPR},
  {{"ttmp"}, IS_TTMP},
  {{"acc"},  IS_AGPR},
  {{"a"},    IS_AGPR},
}
Definition at line 2601 of file AMDGPUAsmParser.cpp.
Referenced by getRegularRegInfo().