LLVM: lib/Target/AMDGPU/AMDGPUMachineFunction.cpp File Reference
AMDGPUMachineFunction.cpp File Reference
#include "AMDGPUMachineFunction.h"
#include "AMDGPU.h"
#include "AMDGPUPerfHintAnalysis.h"
#include "AMDGPUSubtarget.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/IR/ConstantRange.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Metadata.h"
#include "llvm/Target/TargetMachine.h"
Functions
static const GlobalVariable * getKernelDynLDSGlobalFromFunction (const Function &F)
static bool hasLDSKernelArgument (const Function &F)
Function Documentation
getKernelDynLDSGlobalFromFunction()
static const GlobalVariable * getKernelDynLDSGlobalFromFunction (const Function & F) static
Definition at line 23 of file AMDGPUMachineFunction.cpp.
References F.
Referenced by llvm::AMDGPUMachineFunction::AMDGPUMachineFunction(), and llvm::AMDGPUMachineFunction::setDynLDSAlign().
hasLDSKernelArgument()
static bool hasLDSKernelArgument (const Function & F) static
Definition at line 31 of file AMDGPUMachineFunction.cpp.
References F, and llvm::AMDGPUAS::LOCAL_ADDRESS.
Referenced by llvm::AMDGPUMachineFunction::AMDGPUMachineFunction().