LLVM: lib/TargetParser/ARMTargetParser.cpp File Reference
ARMTargetParser.cpp File Reference
#include "llvm/TargetParser/ARMTargetParser.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/TargetParser/ARMTargetParserCommon.h"
#include "llvm/TargetParser/Triple.h"
#include <cctype>
#include "llvm/TargetParser/ARMTargetParser.def"
Macros
#define ARM_CPU_NAME(NAME, ID, DEFAULT_FPU, IS_DEFAULT, DEFAULT_EXT) .Case(NAME, DEFAULT_FPU)
#define ARM_CPU_NAME(NAME, ID, DEFAULT_FPU, IS_DEFAULT, DEFAULT_EXT)
Functions
static StringRef getHWDivSynonym (StringRef HWDiv)
static ARM::ProfileKind getProfileKind (ARM::ArchKind AK)
static bool stripNegationPrefix (StringRef &Name)
static ARM::FPUKind findDoublePrecisionFPU (ARM::FPUKind InputFPUKind)
static ARM::FPUKind findSinglePrecisionFPU (ARM::FPUKind InputFPUKind)
Macro Definition Documentation
ARM_CPU_NAME [1/2]
#define ARM_CPU_NAME (NAME, ID, DEFAULT_FPU, IS_DEFAULT, DEFAULT_EXT) .Case(NAME, DEFAULT_FPU)
ARM_CPU_NAME [2/2]
#define ARM_CPU_NAME (NAME, ID, DEFAULT_FPU, IS_DEFAULT, DEFAULT_EXT)
Value:
  .Case(NAME,                                                                  \
        ARMArchNames[static_cast<unsigned>(ArchKind::ID)].ArchBaseExtensions | \
            DEFAULT_EXT)
Function Documentation
findDoublePrecisionFPU()
static ARM::FPUKind findDoublePrecisionFPU (ARM::FPUKind InputFPUKind) static
Definition at line 366 of file ARMTargetParser.cpp.
References llvm::ARM::FPUNames, llvm::ARM::FPUName::FPUVer, llvm::ARM::has32Regs(), llvm::ARM::FPUName::ID, llvm::ARM::isDoublePrecision(), llvm::ARM::FPUName::NeonSupport, and llvm::ARM::FPUName::Restriction.
Referenced by llvm::ARM::appendArchExtFeatures().
findSinglePrecisionFPU()
static ARM::FPUKind findSinglePrecisionFPU (ARM::FPUKind InputFPUKind) static
Definition at line 393 of file ARMTargetParser.cpp.
References llvm::ARM::FPUNames, llvm::ARM::FPUName::FPUVer, llvm::ARM::has32Regs(), llvm::ARM::FPUName::ID, llvm::ARM::isDoublePrecision(), llvm::ARM::FPUName::NeonSupport, and llvm::ARM::FPUName::Restriction.
Referenced by llvm::ARM::appendArchExtFeatures().
getHWDivSynonym()
static StringRef getHWDivSynonym (StringRef HWDiv) static
Definition at line 24 of file ARMTargetParser.cpp.
References llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Default().
Referenced by llvm::ARM::parseHWDiv().
getProfileKind()
static ARM::ProfileKind getProfileKind (ARM::ArchKind AK) static
Definition at line 97 of file ARMTargetParser.cpp.
References llvm_unreachable.
Referenced by llvm::ARM::convertV9toV8(), and llvm::ARM::parseArchProfile().
stripNegationPrefix()
static bool stripNegationPrefix (StringRef & Name) static
Definition at line 352 of file ARMTargetParser.cpp.
References Name.
Referenced by llvm::ARM::appendArchExtFeatures(), and llvm::ARM::getArchExtFeature().