LLVM: lib/Target/BPF/MCTargetDesc/BPFInstPrinter.cpp File Reference
BPFInstPrinter.cpp File Reference
#include "BPF.h"
#include "MCTargetDesc/BPFInstPrinter.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCRegister.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "BPFGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
static void printExpr (const MCExpr *Expr, raw_ostream &O)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 26 of file BPFInstPrinter.cpp.
Function Documentation
printExpr()
static void printExpr (const MCExpr * Expr, raw_ostream & O) static
Definition at line 38 of file BPFInstPrinter.cpp.
References assert(), llvm::MCSymbolRefExpr::getKind(), llvm::report_fatal_error(), and llvm::MCSymbolRefExpr::VK_None.