LLVM: llvm::RISCVLegalizerInfo Class Reference
llvm::RISCVLegalizerInfo Class Reference
#include "Target/RISCV/GISel/RISCVLegalizerInfo.h"
Public Member Functions
RISCVLegalizerInfo (const RISCVSubtarget &ST)
bool legalizeCustom (LegalizerHelper &Helper, MachineInstr &MI, LostDebugLocObserver &LocObserver) const override
Called for instructions with the Custom LegalizationAction.
bool legalizeIntrinsic (LegalizerHelper &Helper, MachineInstr &MI) const override
Public Member Functions inherited from llvm::LegalizerInfo
virtual ~LegalizerInfo ()=default
const LegacyLegalizerInfo & getLegacyLegalizerInfo () const
LegacyLegalizerInfo & getLegacyLegalizerInfo ()
unsigned getOpcodeIdxForOpcode (unsigned Opcode) const
unsigned getActionDefinitionsIdx (unsigned Opcode) const
void verify (const MCInstrInfo &MII) const
Perform simple self-diagnostic and assert if there is anything obviously wrong with the actions set up.
const LegalizeRuleSet & getActionDefinitions (unsigned Opcode) const
Get the action definitions for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (unsigned Opcode)
Get the action definition builder for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (std::initializer_list< unsigned > Opcodes)
Get the action definition builder for the given set of opcodes.
void aliasActionDefinitions (unsigned OpcodeTo, unsigned OpcodeFrom)
LegalizeActionStep getAction (const LegalityQuery &Query) const
Determine what action should be taken to legalize the described instruction.
LegalizeActionStep getAction (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
Determine what action should be taken to legalize the given generic instruction.
bool isLegal (const LegalityQuery &Query) const
bool isLegalOrCustom (const LegalityQuery &Query) const
bool isLegal (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
bool isLegalOrCustom (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
virtual bool legalizeCustom (LegalizerHelper &Helper, MachineInstr &MI, LostDebugLocObserver &LocObserver) const
Called for instructions with the Custom LegalizationAction.
virtual bool legalizeIntrinsic (LegalizerHelper &Helper, MachineInstr &MI) const
virtual unsigned getExtOpcodeForWideningConstant (LLT SmallTy) const
Return the opcode (SEXT/ZEXT/ANYEXT) that should be performed while widening a constant of type SmallTy which targets can override.
Detailed Description
Definition at line 24 of file RISCVLegalizerInfo.h.
Constructor & Destructor Documentation
RISCVLegalizerInfo()
RISCVLegalizerInfo::RISCVLegalizerInfo (const RISCVSubtarget & ST)
Definition at line 40 of file RISCVLegalizerInfo.cpp.
References llvm::LegalityPredicates::all(), llvm::LegalizeMutations::changeTo(), llvm::LegalizeRuleSet::clampScalar(), llvm::LegacyLegalizerInfo::computeTables(), llvm::LegalizeRuleSet::customFor(), llvm::LegalizeRuleSet::customIf(), llvm::LegalizerInfo::getActionDefinitionsBuilder(), llvm::LegalizerInfo::getLegacyLegalizerInfo(), llvm::LegalizeRuleSet::legalFor(), llvm::LegalizeRuleSet::legalForTypesWithMemDesc(), llvm::LegalizeRuleSet::legalIf(), libcall, llvm::LegalizeRuleSet::libcallFor(), llvm::LegalizeRuleSet::lower(), llvm::LegalizeRuleSet::lowerFor(), llvm::LegalizeRuleSet::lowerForCartesianProduct(), llvm::LegalizeRuleSet::maxScalar(), llvm::LegalizeRuleSet::minScalarSameAs(), llvm::LLT::pointer(), llvm::LLT::scalable_vector(), llvm::LLT::scalar(), llvm::LegalizeRuleSet::scalarSameSizeAs(), llvm::LegalityPredicates::typeInSet(), llvm::LegalityPredicates::typeIs(), typeIsScalarFPArith(), llvm::LegalityQuery::Types, llvm::LegalizeRuleSet::widenScalarIf(), and llvm::LegalizeRuleSet::widenScalarToNextPow2().
Member Function Documentation
legalizeCustom()
bool RISCVLegalizerInfo::legalizeCustom (LegalizerHelper & Helper, MachineInstr & MI, LostDebugLocObserver & LocObserver) const override virtual
Called for instructions with the Custom LegalizationAction.
Reimplemented from llvm::LegalizerInfo.
Definition at line 454 of file RISCVLegalizerInfo.cpp.
References llvm::And, llvm::MachineIRBuilder::buildAnd(), llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildInstr(), llvm::MachineOperand::getImm(), llvm::CmpInst::ICMP_NE, llvm::LegalizerHelper::Legalized, llvm_unreachable, llvm::LegalizerHelper::lower(), llvm::LegalizerHelper::lowerAbsToMaxNeg(), MI, llvm::LegalizerHelper::MIRBuilder, llvm::LegalizerHelper::Observer, llvm::APInt::rotr(), and llvm::APInt::zext().
legalizeIntrinsic()
bool RISCVLegalizerInfo::legalizeIntrinsic (LegalizerHelper & Helper, MachineInstr & MI) const override virtual
Returns
true if MI is either legal or has been legalized and false if not legal. Return true if MI is either legal or has been legalized and false if not legal.
Reimplemented from llvm::LegalizerInfo.
Definition at line 378 of file RISCVLegalizerInfo.cpp.
References llvm::MachineIRBuilder::buildLoad(), llvm::MachineIRBuilder::buildStore(), DL, llvm::Function::getContext(), llvm::MachineIRBuilder::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineIRBuilder::getMRI(), getTypeForLLT(), MI, llvm::LegalizerHelper::MIRBuilder, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, and MRI.
The documentation for this class was generated from the following files:
lib/Target/RISCV/GISel/RISCVLegalizerInfo.h
lib/Target/RISCV/GISel/RISCVLegalizerInfo.cpp