LLVM: llvm::objcopy::elf::BinaryWriter Class Reference
llvm::objcopy::elf::BinaryWriter Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
~BinaryWriter ()
Error finalize () override
Error write () override
BinaryWriter (Object &Obj, raw_ostream &Out, const CommonConfig &Config)
Public Member Functions inherited from llvm::objcopy::elf::Writer
virtual ~Writer ()
virtual Error finalize ()=0
virtual Error write ()=0
Writer (Object &O, raw_ostream &Out)
Additional Inherited Members
Protected Attributes inherited from llvm::objcopy::elf::Writer
Object & Obj
std::unique_ptr< WritableMemoryBuffer > Buf
raw_ostream & Out
Detailed Description
Definition at line 358 of file ELFObject.h.
Constructor & Destructor Documentation
~BinaryWriter()
llvm::objcopy::elf::BinaryWriter::~BinaryWriter () inline
Definition at line 367 of file ELFObject.h.
BinaryWriter()
llvm::objcopy::elf::BinaryWriter::BinaryWriter (Object & Obj, raw_ostream & Out, const CommonConfig & Config) inline
Definition at line 370 of file ELFObject.h.
Member Function Documentation
finalize()
Error BinaryWriter::finalize () override virtual
Implements llvm::objcopy::elf::Writer.
Definition at line 2676 of file ELFObject.cpp.
References llvm::objcopy::elf::Object::allocSections(), llvm::objcopy::elf::Writer::Buf, llvm::createStringError(), llvm::WritableMemoryBuffer::getNewMemBuffer(), llvm::not_enough_memory, llvm::objcopy::elf::Writer::Obj, llvm::ELF::SHT_NOBITS, llvm::Error::success(), UINT64_MAX, and llvm::Twine::utohexstr().
write()
Error BinaryWriter::write () override virtual
Implements llvm::objcopy::elf::Writer.
Definition at line 2638 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::accept(), llvm::objcopy::elf::Object::allocSections(), assert(), llvm::objcopy::elf::Writer::Buf, llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::front(), LHS, llvm::objcopy::elf::Writer::Obj, llvm::Offset, llvm::objcopy::elf::SectionBase::Offset, llvm::objcopy::elf::Writer::Out, llvm::SmallVectorTemplateBase< T, bool >::push_back(), RHS, llvm::ELF::SHT_NOBITS, llvm::SmallVectorBase< Size_T >::size(), llvm::objcopy::elf::SectionBase::Size, llvm::stable_sort(), llvm::Error::success(), and llvm::raw_ostream::write().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp