LLVM: llvm::coverage::TestingFormatWriter Class Reference
llvm::coverage::TestingFormatWriter Class Reference
Writer for the coverage mapping testing format.
#include "llvm/ProfileData/Coverage/CoverageMappingWriter.h"
Public Member Functions
TestingFormatWriter (uint64_t ProfileNamesAddr, StringRef ProfileNamesData, StringRef CoverageMappingData, StringRef CoverageRecordsData)
void write (raw_ostream &OS, TestingFormatVersion Version=TestingFormatVersion::CurrentVersion)
Encode to the given output stream.
Detailed Description
Writer for the coverage mapping testing format.
Definition at line 58 of file CoverageMappingWriter.h.
Constructor & Destructor Documentation
TestingFormatWriter()
llvm::coverage::TestingFormatWriter::TestingFormatWriter (uint64_t ProfileNamesAddr, StringRef ProfileNamesData, StringRef CoverageMappingData, StringRef CoverageRecordsData) inline
Definition at line 65 of file CoverageMappingWriter.h.
Member Function Documentation
write()
void TestingFormatWriter::write (raw_ostream & OS, TestingFormatVersion Version = TestingFormatVersion::CurrentVersion)
Encode to the given output stream.
Definition at line 278 of file CoverageMappingWriter.cpp.
References llvm::encodeULEB128(), N, llvm::offsetToAlignment(), OS, llvm::StringRef::size(), llvm::raw_ostream::tell(), llvm::coverage::TestingFormatMagic, llvm::coverage::Version2, and llvm::raw_ostream::write().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMappingWriter.h
lib/ProfileData/Coverage/CoverageMappingWriter.cpp