LLVM: llvm::X86RegisterInfo Class Reference
llvm::X86RegisterInfo Class Reference final
#include "Target/X86/X86RegisterInfo.h"
Public Member Functions
X86RegisterInfo (const Triple &TT)
unsigned getNumSupportedRegs (const MachineFunction &MF) const override
Return the number of registers for the function.
int getSEHRegNum (unsigned i) const
const TargetRegisterClass * getMatchingSuperRegClass (const TargetRegisterClass *A, const TargetRegisterClass *B, unsigned Idx) const override
getMatchingSuperRegClass - Return a subclass of the specified register class A so that each register in it has a sub-register of the specified sub-register index which is in the specified register class B.
const TargetRegisterClass * getSubClassWithSubReg (const TargetRegisterClass *RC, unsigned Idx) const override
const TargetRegisterClass * getLargestLegalSuperClass (const TargetRegisterClass *RC, const MachineFunction &MF) const override
bool shouldRewriteCopySrc (const TargetRegisterClass *DefRC, unsigned DefSubReg, const TargetRegisterClass *SrcRC, unsigned SrcSubReg) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
getPointerRegClass - Returns a TargetRegisterClass used for pointer values.
const TargetRegisterClass * getCrossCopyRegClass (const TargetRegisterClass *RC) const override
getCrossCopyRegClass - Returns a legal register class to copy a register in the specified class to or from.
const TargetRegisterClass * getGPRsForTailCall (const MachineFunction &MF) const
getGPRsForTailCall - Returns a register class with registers that can be used in forming tail calls.
unsigned getRegPressureLimit (const TargetRegisterClass *RC, MachineFunction &MF) const override
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
getCalleeSavedRegs - Return a null-terminated list of all of the callee-save registers on this target.
const MCPhysReg * getCalleeSavedRegsViaCopy (const MachineFunction *MF) const
const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const override
const uint32_t * getNoPreservedMask () const override
const uint32_t * getDarwinTLSCallPreservedMask () const
BitVector getReservedRegs (const MachineFunction &MF) const override
getReservedRegs - Returns a bitset indexed by physical register number indicating if a register is a special register that has particular uses and should be considered unavailable at all times, e.g.
bool isArgumentRegister (const MachineFunction &MF, MCRegister Reg) const override
isArgumentReg - Returns true if Reg can be used as an argument to a function.
bool isTileRegisterClass (const TargetRegisterClass *RC) const
Return true if it is tile register class.
bool isFixedRegister (const MachineFunction &MF, MCRegister PhysReg) const override
Returns true if PhysReg is a fixed register.
void adjustStackMapLiveOutMask (uint32_t *Mask) const override
bool hasBasePointer (const MachineFunction &MF) const
bool canRealignStack (const MachineFunction &MF) const override
bool shouldRealignStack (const MachineFunction &MF) const override
void eliminateFrameIndex (MachineBasicBlock::iterator II, unsigned FIOperandNum, Register BaseReg, int FIOffset) const
bool eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
bool eliminateFrameIndicesBackwards () const override
Process frame indices in forwards block order because X86InstrInfo::getSPAdjust relies on it when searching for the ADJCALLSTACKUP pseudo following a call.
unsigned findDeadCallerSavedReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI) const
findDeadCallerSavedReg - Return a caller-saved register that isn't live when it reaches the "return" instruction.
Register getFrameRegister (const MachineFunction &MF) const override
unsigned getPtrSizedFrameRegister (const MachineFunction &MF) const
unsigned getPtrSizedStackRegister (const MachineFunction &MF) const
Register getStackRegister () const
Register getBaseRegister () const
Register getFramePtr () const
Returns physical register used as frame pointer.
unsigned getSlotSize () const
bool getRegAllocationHints (Register VirtReg, ArrayRef< MCPhysReg > Order, SmallVectorImpl< MCPhysReg > &Hints, const MachineFunction &MF, const VirtRegMap *VRM, const LiveRegMatrix *Matrix) const override
Detailed Description
Definition at line 24 of file X86RegisterInfo.h.
Constructor & Destructor Documentation
X86RegisterInfo()
X86RegisterInfo::X86RegisterInfo (const Triple & TT) explicit
Definition at line 48 of file X86RegisterInfo.cpp.
References llvm::X86_MC::initLLVMToSEHAndCVRegMapping().
Member Function Documentation
adjustStackMapLiveOutMask()
void X86RegisterInfo::adjustStackMapLiveOutMask (uint32_t * Mask) const override
Definition at line 725 of file X86RegisterInfo.cpp.
References assert().
canRealignStack()
bool X86RegisterInfo::canRealignStack (const MachineFunction & MF) const override
Definition at line 773 of file X86RegisterInfo.cpp.
References llvm::TargetRegisterInfo::canRealignStack(), CantUseSP(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getRegInfo(), and MRI.
Referenced by llvm::X86InstrInfo::loadRegFromStackSlot(), and llvm::X86InstrInfo::storeRegToStackSlot().
eliminateFrameIndex() [1/2]
void X86RegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, unsigned FIOperandNum, Register BaseReg, int FIOffset) const
Definition at line 839 of file X86RegisterInfo.cpp.
References assert(), llvm::MachineOperand::ChangeToImmediate(), MI, and llvm::Offset.
eliminateFrameIndex() [2/2]
bool X86RegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 879 of file X86RegisterInfo.cpp.
References assert(), llvm::MachineOperand::ChangeToImmediate(), contains(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::StackOffset::getFixed(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReferenceSP(), llvm::MachineFunction::getFrameInfo(), llvm::MachineBasicBlock::getParent(), llvm::X86FrameLowering::getWin64EHFrameIndexRef(), llvm::getX86SubSuperRegister(), llvm::X86FrameLowering::Is64Bit, llvm::MachineBasicBlock::isEHFuncletEntry(), llvm::MachineFrameInfo::isFixedObjectIndex(), isFuncletReturnInstr(), MBB, MBBI, MI, llvm::Offset, and tryOptimizeLEAtoMOV().
eliminateFrameIndicesBackwards()
bool llvm::X86RegisterInfo::eliminateFrameIndicesBackwards () const inline override
Process frame indices in forwards block order because X86InstrInfo::getSPAdjust relies on it when searching for the ADJCALLSTACKUP pseudo following a call.
TODO: Fix this and return true like all other targets.
Definition at line 153 of file X86RegisterInfo.h.
findDeadCallerSavedReg()
unsigned X86RegisterInfo::findDeadCallerSavedReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI) const
findDeadCallerSavedReg - Return a caller-saved register that isn't live when it reaches the "return" instruction.
We can then pop a stack object to this register without worry about clobbering it.
Definition at line 959 of file X86RegisterInfo.cpp.
References llvm::MachineFunction::callsEHReturn(), llvm::MachineBasicBlock::end(), getGPRsForTailCall(), llvm::MachineBasicBlock::getParent(), llvm::MCRegAliasIterator::isValid(), MBB, MBBI, and Uses.
Referenced by llvm::X86FrameLowering::emitSPUpdate().
getBaseRegister()
Register llvm::X86RegisterInfo::getBaseRegister () const inline
Definition at line 166 of file X86RegisterInfo.h.
Referenced by llvm::X86FrameLowering::determineCalleeSaves(), llvm::X86FrameLowering::emitPrologue(), llvm::X86FrameLowering::getFrameIndexReference(), getReservedRegs(), and llvm::X86FrameLowering::restoreWin32EHStackPointers().
getCalleeSavedRegs()
const MCPhysReg * X86RegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
getCalleeSavedRegs - Return a null-terminated list of all of the callee-save registers on this target.
Definition at line 282 of file X86RegisterInfo.cpp.
References llvm::CallingConv::AnyReg, assert(), llvm::MachineFunction::callsEHReturn(), CC, llvm::CallingConv::CFGuard_Check, llvm::CallingConv::Cold, llvm::CallingConv::CXX_FAST_TLS, F, llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), llvm::X86Subtarget::getTargetLowering(), llvm::CallingConv::GHC, llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::Function::hasFnAttribute(), llvm::X86Subtarget::hasSSE1(), llvm::CallingConv::HiPE, llvm::CallingConv::Intel_OCL_BI, llvm::CallingConv::PreserveAll, llvm::CallingConv::PreserveMost, llvm::X86TargetLowering::supportSwiftError(), llvm::CallingConv::SwiftTail, llvm::CallingConv::Win64, llvm::CallingConv::X86_64_SysV, llvm::CallingConv::X86_INTR, and llvm::CallingConv::X86_RegCall.
getCalleeSavedRegsViaCopy()
const MCPhysReg * X86RegisterInfo::getCalleeSavedRegsViaCopy (const MachineFunction * MF) const
Definition at line 409 of file X86RegisterInfo.cpp.
References assert(), llvm::CallingConv::CXX_FAST_TLS, llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), and llvm::X86MachineFunctionInfo::isSplitCSR().
getCallPreservedMask()
const uint32_t * X86RegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID CC) const override
Definition at line 419 of file X86RegisterInfo.cpp.
References llvm::CallingConv::AnyReg, assert(), CC, llvm::CallingConv::CFGuard_Check, llvm::CallingConv::Cold, llvm::CallingConv::CXX_FAST_TLS, F, llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::X86Subtarget::getTargetLowering(), llvm::CallingConv::GHC, llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE1(), llvm::CallingConv::HiPE, llvm::CallingConv::Intel_OCL_BI, llvm::CallingConv::PreserveAll, llvm::CallingConv::PreserveMost, llvm::X86TargetLowering::supportSwiftError(), llvm::CallingConv::SwiftTail, llvm::CallingConv::Win64, llvm::CallingConv::X86_64_SysV, llvm::CallingConv::X86_INTR, and llvm::CallingConv::X86_RegCall.
Referenced by getReservedRegs().
getCrossCopyRegClass()
const TargetRegisterClass * X86RegisterInfo::getCrossCopyRegClass (const TargetRegisterClass * RC) const override
getCrossCopyRegClass - Returns a legal register class to copy a register in the specified class to or from.
Returns NULL if it is possible to copy between a two registers of the specified class.
Definition at line 251 of file X86RegisterInfo.cpp.
getDarwinTLSCallPreservedMask()
const uint32_t * X86RegisterInfo::getDarwinTLSCallPreservedMask () const
Definition at line 528 of file X86RegisterInfo.cpp.
getFramePtr()
Register llvm::X86RegisterInfo::getFramePtr () const inline
Returns physical register used as frame pointer.
This will always returns the frame pointer register, contrary to getFrameRegister() which returns the "base pointer" in situations involving a stack, frame and base pointer.
Definition at line 171 of file X86RegisterInfo.h.
Referenced by llvm::X86FrameLowering::getFrameIndexReference().
getFrameRegister()
Register X86RegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 1007 of file X86RegisterInfo.cpp.
References llvm::X86FrameLowering::hasFP().
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitCalleeSavedFrameMovesFullCFA(), llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), llvm::X86FrameLowering::getFrameIndexReference(), getPtrSizedFrameRegister(), and llvm::X86FrameLowering::restoreWin32EHStackPointers().
getGPRsForTailCall()
const TargetRegisterClass * X86RegisterInfo::getGPRsForTailCall (const MachineFunction & MF) const
getGPRsForTailCall - Returns a register class with registers that can be used in forming tail calls.
Definition at line 237 of file X86RegisterInfo.cpp.
References F, llvm::MachineFunction::getFunction(), llvm::CallingConv::HiPE, and llvm::CallingConv::Win64.
Referenced by findDeadCallerSavedReg(), and getPointerRegClass().
getLargestLegalSuperClass()
const TargetRegisterClass * X86RegisterInfo::getLargestLegalSuperClass (const TargetRegisterClass * RC, const MachineFunction & MF) const override
Definition at line 110 of file X86RegisterInfo.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::TargetRegisterClass::getSuperClasses(), llvm::X86Subtarget::hasAVX512(), and I.
getMatchingSuperRegClass()
const TargetRegisterClass * X86RegisterInfo::getMatchingSuperRegClass (const TargetRegisterClass * A, const TargetRegisterClass * B, unsigned Idx) const override
getMatchingSuperRegClass - Return a subclass of the specified register class A so that each register in it has a sub-register of the specified sub-register index which is in the specified register class B.
Definition at line 97 of file X86RegisterInfo.cpp.
References A, and B.
getNoPreservedMask()
const uint32_t * X86RegisterInfo::getNoPreservedMask () const override
Definition at line 524 of file X86RegisterInfo.cpp.
getNumSupportedRegs()
unsigned X86RegisterInfo::getNumSupportedRegs (const MachineFunction & MF) const override
Return the number of registers for the function.
Definition at line 636 of file X86RegisterInfo.cpp.
References assert(), and llvm::MachineFunction::getSubtarget().
getPointerRegClass()
const TargetRegisterClass * X86RegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const override
getPointerRegClass - Returns a TargetRegisterClass used for pointer values.
Definition at line 181 of file X86RegisterInfo.cpp.
References getGPRsForTailCall(), llvm::MachineFunction::getSubtarget(), llvm::X86FrameLowering::hasFP(), llvm::X86Subtarget::isTarget64BitLP64(), llvm_unreachable, and llvm::X86FrameLowering::Uses64BitFramePtr.
getPtrSizedFrameRegister()
unsigned X86RegisterInfo::getPtrSizedFrameRegister (const MachineFunction & MF) const
Definition at line 1013 of file X86RegisterInfo.cpp.
References getFrameRegister(), llvm::MachineFunction::getSubtarget(), llvm::getX86SubSuperRegister(), and llvm::X86Subtarget::isTarget64BitILP32().
Referenced by llvm::X86TargetLowering::getRegisterByName().
getPtrSizedStackRegister()
unsigned X86RegisterInfo::getPtrSizedStackRegister (const MachineFunction & MF) const
Definition at line 1022 of file X86RegisterInfo.cpp.
References getStackRegister(), llvm::MachineFunction::getSubtarget(), llvm::getX86SubSuperRegister(), and llvm::X86Subtarget::isTarget64BitILP32().
getRegAllocationHints()
bool X86RegisterInfo::getRegAllocationHints (Register VirtReg, ArrayRef< MCPhysReg > Order, SmallVectorImpl< MCPhysReg > & Hints, const MachineFunction & MF, const VirtRegMap * VRM, const LiveRegMatrix * Matrix) const override
Definition at line 1068 of file X86RegisterInfo.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::TargetRegisterClass::contains(), llvm::SmallSet< T, N, C >::count(), llvm::dbgs(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::format_hex(), llvm::TargetRegisterClass::getID(), llvm::TargetRegisterInfo::getRegAllocationHints(), llvm::MachineFunction::getRegInfo(), getTileShape(), llvm::SmallSet< T, N, C >::insert(), LLVM_DEBUG, Matrix, MRI, llvm::MCRegister::NoRegister, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
getRegPressureLimit()
unsigned X86RegisterInfo::getRegPressureLimit (const TargetRegisterClass * RC, MachineFunction & MF) const override
Definition at line 262 of file X86RegisterInfo.cpp.
References llvm::TargetRegisterClass::getID(), and llvm::X86FrameLowering::hasFP().
getReservedRegs()
BitVector X86RegisterInfo::getReservedRegs (const MachineFunction & MF) const override
getReservedRegs - Returns a bitset indexed by physical register number indicating if a register is a special register that has particular uses and should be considered unavailable at all times, e.g.
SP, RA. This is used by register scavenger to determine what registers are free.
Definition at line 532 of file X86RegisterInfo.cpp.
References assert(), CC, llvm::MachineOperand::clobbersPhysReg(), getBaseRegister(), llvm::Function::getCallingConv(), getCallPreservedMask(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::getX86SubSuperRegister(), llvm::CallingConv::GRAAL, llvm::X86Subtarget::hasAVX512(), hasBasePointer(), llvm::X86FrameLowering::hasFP(), llvm::MCRegAliasIterator::isValid(), llvm::report_fatal_error(), llvm::Reserved, and SubReg.
getSEHRegNum()
int X86RegisterInfo::getSEHRegNum (unsigned i) const
Definition at line 80 of file X86RegisterInfo.cpp.
getSlotSize()
unsigned llvm::X86RegisterInfo::getSlotSize () const inline
Definition at line 173 of file X86RegisterInfo.h.
Referenced by llvm::X86AsmPrinter::emitInstruction(), llvm::X86FrameLowering::getInitialCFAOffset(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::X86MachineFunctionInfo::setRestoreBasePointer(), and llvm::X86FrameLowering::X86FrameLowering().
getStackRegister()
Register llvm::X86RegisterInfo::getStackRegister () const inline
Definition at line 165 of file X86RegisterInfo.h.
Referenced by llvm::X86FrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReferenceSP(), getPtrSizedStackRegister(), llvm::X86FrameLowering::getWin64EHFrameIndexRef(), llvm::X86FrameLowering::X86FrameLowering(), and llvm::X86TargetLowering::X86TargetLowering().
getSubClassWithSubReg()
const TargetRegisterClass * X86RegisterInfo::getSubClassWithSubReg (const TargetRegisterClass * RC, unsigned Idx) const override
Definition at line 85 of file X86RegisterInfo.cpp.
References Idx.
hasBasePointer()
bool X86RegisterInfo::hasBasePointer (const MachineFunction & MF) const
Definition at line 749 of file X86RegisterInfo.cpp.
References CantUseSP(), EnableBasePointer, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::X86MachineFunctionInfo::getStackPtrSaveMI(), and llvm::X86MachineFunctionInfo::hasPreallocatedCall().
Referenced by llvm::X86FrameLowering::canSimplifyCallFramePseudos(), llvm::X86FrameLowering::determineCalleeSaves(), llvm::X86FrameLowering::emitPrologue(), llvm::X86FrameLowering::getFrameIndexReference(), and getReservedRegs().
isArgumentRegister()
bool X86RegisterInfo::isArgumentRegister (const MachineFunction & MF, MCRegister Reg) const override
isArgumentReg - Returns true if Reg can be used as an argument to a function.
Definition at line 665 of file X86RegisterInfo.cpp.
References llvm::any_of(), CC, llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), TRI, llvm::CallingConv::Win64, and llvm::CallingConv::X86_64_SysV.
isFixedRegister()
bool X86RegisterInfo::isFixedRegister (const MachineFunction & MF, MCRegister PhysReg) const override
Returns true if PhysReg is a fixed register.
Definition at line 704 of file X86RegisterInfo.cpp.
References llvm::MachineFunction::getSubtarget(), llvm::X86FrameLowering::hasFP(), and TRI.
isTileRegisterClass()
bool X86RegisterInfo::isTileRegisterClass (const TargetRegisterClass * RC) const
Return true if it is tile register class.
Definition at line 721 of file X86RegisterInfo.cpp.
References llvm::TargetRegisterClass::getID().
shouldRealignStack()
bool X86RegisterInfo::shouldRealignStack (const MachineFunction & MF) const override
Definition at line 792 of file X86RegisterInfo.cpp.
References llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::TargetRegisterInfo::shouldRealignStack(), and llvm::CallingConv::X86_INTR.
shouldRewriteCopySrc()
bool X86RegisterInfo::shouldRewriteCopySrc (const TargetRegisterClass * DefRC, unsigned DefSubReg, const TargetRegisterClass * SrcRC, unsigned SrcSubReg) const override
Definition at line 221 of file X86RegisterInfo.cpp.
References llvm::TargetRegisterClass::hasSuperClassEq(), and llvm::TargetRegisterInfo::shouldRewriteCopySrc().
The documentation for this class was generated from the following files:
lib/Target/X86/X86RegisterInfo.h
lib/Target/X86/X86RegisterInfo.cpp