LLVM: llvm::coverage::CounterMappingContext Class Reference
llvm::coverage::CounterMappingContext Class Reference
A Counter mapping context is used to connect the counters, expressions and the obtained counter values.
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
Public Member Functions
CounterMappingContext (ArrayRef< CounterExpression > Expressions, ArrayRef< uint64_t > CounterValues=std::nullopt)
void setCounts (ArrayRef< uint64_t > Counts)
void setBitmapBytes (ArrayRef< uint8_t > Bytes)
void dump (const Counter &C, raw_ostream &OS) const
void dump (const Counter &C) const
Expected< int64_t > evaluate (const Counter &C) const
Return the number of times that a region of code associated with this counter was executed.
Expected< BitVector > evaluateBitmap (const CounterMappingRegion *MCDCDecision) const
Return the number of times that a region of code associated with this counter was executed.
Expected< MCDCRecord > evaluateMCDCRegion (const CounterMappingRegion &Region, const BitVector &Bitmap, ArrayRef< const CounterMappingRegion * > Branches)
Return an MCDC record that indicates executed test vectors and condition pairs.
unsigned getMaxCounterID (const Counter &C) const
Detailed Description
A Counter mapping context is used to connect the counters, expressions and the obtained counter values.
Definition at line 562 of file CoverageMapping.h.
Constructor & Destructor Documentation
CounterMappingContext()
llvm::coverage::CounterMappingContext::CounterMappingContext (ArrayRef< CounterExpression > Expressions, ArrayRef< uint64_t > CounterValues = std::nullopt) inline
Definition at line 568 of file CoverageMapping.h.
Member Function Documentation
dump() [1/2]
void llvm::coverage::CounterMappingContext::dump (const Counter & C) const inline
Definition at line 576 of file CoverageMapping.h.
References llvm::CallingConv::C, llvm::dbgs(), and dump().
Referenced by dump().
dump() [2/2]
void CounterMappingContext::dump (const Counter & C, raw_ostream & OS) const
Definition at line 140 of file CoverageMapping.cpp.
References llvm::CallingConv::C, llvm::consumeError(), llvm::coverage::Counter::CounterValueReference, dump(), E, llvm::ArrayRef< T >::empty(), evaluate(), llvm::coverage::Counter::Expression, OS, llvm::coverage::CounterExpression::Subtract, and llvm::coverage::Counter::Zero.
Referenced by dump().
evaluate()
Expected< int64_t > CounterMappingContext::evaluate (const Counter & C) const
Return the number of times that a region of code associated with this counter was executed.
Definition at line 170 of file CoverageMapping.cpp.
References llvm::argument_out_of_domain, llvm::CallingConv::C, llvm::coverage::Counter::CounterValueReference, E, llvm::errorCodeToError(), llvm::coverage::Counter::Expression, LHS, RHS, llvm::ArrayRef< T >::size(), llvm::coverage::CounterExpression::Subtract, and llvm::coverage::Counter::Zero.
Referenced by dump().
evaluateBitmap()
Expected< BitVector > CounterMappingContext::evaluateBitmap (const CounterMappingRegion * MCDCDecision) const
Return the number of times that a region of code associated with this counter was executed.
Definition at line 226 of file CoverageMapping.cpp.
References llvm::alignTo(), assert(), llvm::coverage::CounterMappingRegion::MCDCParameters::BitmapIdx, llvm::Data, llvm::coverage::CounterMappingRegion::MCDCParams, NC, llvm::coverage::CounterMappingRegion::MCDCParameters::NumConditions, and llvm::ArrayRef< T >::size().
evaluateMCDCRegion()
Expected< MCDCRecord > CounterMappingContext::evaluateMCDCRegion (const CounterMappingRegion & Region, const BitVector & Bitmap, ArrayRef< const CounterMappingRegion * > Branches)
Return an MCDC record that indicates executed test vectors and condition pairs.
Definition at line 478 of file CoverageMapping.cpp.
References MCDCRecordProcessor::processMCDCRecord().
getMaxCounterID()
unsigned CounterMappingContext::getMaxCounterID (const Counter & C) const
Definition at line 487 of file CoverageMapping.cpp.
References llvm::CallingConv::C, llvm::coverage::Counter::CounterValueReference, E, llvm::coverage::Counter::Expression, LHS, RHS, and llvm::coverage::Counter::Zero.
Referenced by getMaxCounterID().
setBitmapBytes()
void llvm::coverage::CounterMappingContext::setBitmapBytes (ArrayRef< uint8_t > Bytes) inline
Definition at line 573 of file CoverageMapping.h.
setCounts()
void llvm::coverage::CounterMappingContext::setCounts (ArrayRef< uint64_t > Counts) inline
Definition at line 572 of file CoverageMapping.h.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMapping.h
lib/ProfileData/Coverage/CoverageMapping.cpp