LLVM: ThreadUnsafeDWARFContextState Class Reference
ThreadUnsafeDWARFContextState Class Reference
Public Member Functions
ThreadUnsafeDWARFContextState (DWARFContext &DC, std::string &DWP)
DWARFUnitVector & getNormalUnits () override
DWARFUnitVector & getDWOUnits (bool Lazy) override
const DWARFDebugAbbrev * getDebugAbbrevDWO () override
const DWARFUnitIndex & getCUIndex () override
const DWARFUnitIndex & getTUIndex () override
DWARFGdbIndex & getGdbIndex () override
const DWARFDebugAbbrev * getDebugAbbrev () override
const DWARFDebugLoc * getDebugLoc () override
const DWARFDebugAranges * getDebugAranges () override
Expected< const DWARFDebugLine::LineTable * > getLineTableForUnit (DWARFUnit *U, function_ref< void(Error)> RecoverableErrorHandler) override
void clearLineTableForUnit (DWARFUnit *U) override
Expected< const DWARFDebugFrame * > getDebugFrame () override
Expected< const DWARFDebugFrame * > getEHFrame () override
const DWARFDebugMacro * getDebugMacinfo () override
const DWARFDebugMacro * getDebugMacinfoDWO () override
const DWARFDebugMacro * getDebugMacro () override
const DWARFDebugMacro * getDebugMacroDWO () override
const DWARFDebugNames & getDebugNames () override
const AppleAcceleratorTable & getAppleNames () override
const AppleAcceleratorTable & getAppleTypes () override
const AppleAcceleratorTable & getAppleNamespaces () override
const AppleAcceleratorTable & getAppleObjC () override
std::shared_ptr< DWARFContext > getDWOContext (StringRef AbsolutePath) override
bool isThreadSafe () const override
const DenseMap< uint64_t, DWARFTypeUnit * > & getNormalTypeUnitMap ()
const DenseMap< uint64_t, DWARFTypeUnit * > & getDWOTypeUnitMap ()
const DenseMap< uint64_t, DWARFTypeUnit * > & getTypeUnitMap (bool IsDWO) override
Public Member Functions inherited from llvm::DWARFContext::DWARFContextState
DWARFContextState (DWARFContext &DC)
virtual ~DWARFContextState ()=default
virtual DWARFUnitVector & getNormalUnits ()=0
virtual DWARFUnitVector & getDWOUnits (bool Lazy=false)=0
virtual const DWARFDebugAbbrev * getDebugAbbrevDWO ()=0
virtual const DWARFUnitIndex & getCUIndex ()=0
virtual const DWARFUnitIndex & getTUIndex ()=0
virtual DWARFGdbIndex & getGdbIndex ()=0
virtual const DWARFDebugAbbrev * getDebugAbbrev ()=0
virtual const DWARFDebugLoc * getDebugLoc ()=0
virtual const DWARFDebugAranges * getDebugAranges ()=0
virtual Expected< const DWARFDebugLine::LineTable * > getLineTableForUnit (DWARFUnit *U, function_ref< void(Error)> RecoverableErrHandler)=0
virtual void clearLineTableForUnit (DWARFUnit *U)=0
virtual Expected< const DWARFDebugFrame * > getDebugFrame ()=0
virtual Expected< const DWARFDebugFrame * > getEHFrame ()=0
virtual const DWARFDebugMacro * getDebugMacinfo ()=0
virtual const DWARFDebugMacro * getDebugMacinfoDWO ()=0
virtual const DWARFDebugMacro * getDebugMacro ()=0
virtual const DWARFDebugMacro * getDebugMacroDWO ()=0
virtual const DWARFDebugNames & getDebugNames ()=0
virtual const AppleAcceleratorTable & getAppleNames ()=0
virtual const AppleAcceleratorTable & getAppleTypes ()=0
virtual const AppleAcceleratorTable & getAppleNamespaces ()=0
virtual const AppleAcceleratorTable & getAppleObjC ()=0
virtual std::shared_ptr< DWARFContext > getDWOContext (StringRef AbsolutePath)=0
virtual const DenseMap< uint64_t, DWARFTypeUnit * > & getTypeUnitMap (bool IsDWO)=0
virtual bool isThreadSafe () const =0
std::unique_ptr< DWARFDebugMacro > parseMacroOrMacinfo (MacroSecType SectionType)
Parse a macro[.dwo] or macinfo[.dwo] section.
Additional Inherited Members
Protected Types inherited from llvm::DWARFContext::DWARFContextState
enum MacroSecType { MacinfoSection , MacinfoDwoSection , MacroSection , MacroDwoSection }
Helper enum to distinguish between macro[.dwo] and macinfo[.dwo] section.
Protected Attributes inherited from llvm::DWARFContext::DWARFContextState
DWARFContext & D
Detailed Description
Definition at line 250 of file DWARFContext.cpp.
Constructor & Destructor Documentation
ThreadUnsafeDWARFContextState()
ThreadUnsafeDWARFContextState::ThreadUnsafeDWARFContextState (DWARFContext & DC, std::string & DWP) inline
Definition at line 285 of file DWARFContext.cpp.
Member Function Documentation
clearLineTableForUnit()
void ThreadUnsafeDWARFContextState::clearLineTableForUnit (DWARFUnit * U) inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 427 of file DWARFContext.cpp.
References llvm::Offset, and llvm::dwarf::toSectionOffset().
Referenced by ThreadSafeState::clearLineTableForUnit().
getAppleNames()
const AppleAcceleratorTable & ThreadUnsafeDWARFContextState::getAppleNames () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 512 of file DWARFContext.cpp.
References llvm::dwarf_linker::AppleNames, D, getAccelTable(), llvm::DWARFObject::getAppleNamesSection(), and llvm::DWARFObject::getStrSection().
Referenced by ThreadSafeState::getAppleNames().
getAppleNamespaces()
const AppleAcceleratorTable & ThreadUnsafeDWARFContextState::getAppleNamespaces () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 524 of file DWARFContext.cpp.
References llvm::dwarf_linker::AppleNamespaces, D, getAccelTable(), llvm::DWARFObject::getAppleNamespacesSection(), and llvm::DWARFObject::getStrSection().
Referenced by ThreadSafeState::getAppleNamespaces().
getAppleObjC()
const AppleAcceleratorTable & ThreadUnsafeDWARFContextState::getAppleObjC () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 531 of file DWARFContext.cpp.
References llvm::dwarf_linker::AppleObjC, D, getAccelTable(), llvm::DWARFObject::getAppleObjCSection(), and llvm::DWARFObject::getStrSection().
Referenced by ThreadSafeState::getAppleObjC().
getAppleTypes()
const AppleAcceleratorTable & ThreadUnsafeDWARFContextState::getAppleTypes () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 518 of file DWARFContext.cpp.
References llvm::dwarf_linker::AppleTypes, D, getAccelTable(), llvm::DWARFObject::getAppleTypesSection(), and llvm::DWARFObject::getStrSection().
Referenced by ThreadSafeState::getAppleTypes().
getCUIndex()
const DWARFUnitIndex & ThreadUnsafeDWARFContextState::getCUIndex () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 327 of file DWARFContext.cpp.
References D, and fixupIndex().
Referenced by ThreadSafeState::getCUIndex().
getDebugAbbrev()
const DWARFDebugAbbrev * ThreadUnsafeDWARFContextState::getDebugAbbrev () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 363 of file DWARFContext.cpp.
References D.
Referenced by ThreadSafeState::getDebugAbbrev().
getDebugAbbrevDWO()
const DWARFDebugAbbrev * ThreadUnsafeDWARFContextState::getDebugAbbrevDWO () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 318 of file DWARFContext.cpp.
References D, and llvm::DWARFObject::getAbbrevDWOSection().
Referenced by ThreadSafeState::getDebugAbbrevDWO().
getDebugAranges()
const DWARFDebugAranges * ThreadUnsafeDWARFContextState::getDebugAranges () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 388 of file DWARFContext.cpp.
References D.
Referenced by ThreadSafeState::getDebugAranges().
getDebugFrame()
Expected< const DWARFDebugFrame * > ThreadUnsafeDWARFContextState::getDebugFrame () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 443 of file DWARFContext.cpp.
References D, llvm::dwarf_linker::DebugFrame, DF, E, llvm::DWARFObject::getAddressSize(), and llvm::DWARFObject::getFrameSection().
Referenced by ThreadSafeState::getDebugFrame().
getDebugLoc()
const DWARFDebugLoc * ThreadUnsafeDWARFContextState::getDebugLoc () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 373 of file DWARFContext.cpp.
References D, and llvm::DWARFObject::getLocSection().
Referenced by ThreadSafeState::getDebugLoc().
getDebugMacinfo()
const DWARFDebugMacro * ThreadUnsafeDWARFContextState::getDebugMacinfo () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 487 of file DWARFContext.cpp.
Referenced by ThreadSafeState::getDebugMacinfo().
getDebugMacinfoDWO()
const DWARFDebugMacro * ThreadUnsafeDWARFContextState::getDebugMacinfoDWO () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 492 of file DWARFContext.cpp.
Referenced by ThreadSafeState::getDebugMacinfoDWO().
getDebugMacro()
const DWARFDebugMacro * ThreadUnsafeDWARFContextState::getDebugMacro () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 497 of file DWARFContext.cpp.
References llvm::Macro.
Referenced by ThreadSafeState::getDebugMacro().
getDebugMacroDWO()
const DWARFDebugMacro * ThreadUnsafeDWARFContextState::getDebugMacroDWO () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 502 of file DWARFContext.cpp.
Referenced by ThreadSafeState::getDebugMacroDWO().
getDebugNames()
const DWARFDebugNames & ThreadUnsafeDWARFContextState::getDebugNames () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 507 of file DWARFContext.cpp.
References D, getAccelTable(), llvm::DWARFObject::getNamesSection(), and llvm::DWARFObject::getStrSection().
Referenced by ThreadSafeState::getDebugNames().
getDWOContext()
std::shared_ptr< DWARFContext > ThreadUnsafeDWARFContextState::getDWOContext (StringRef AbsolutePath) inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 538 of file DWARFContext.cpp.
References llvm::consumeError(), llvm::DWARFContext::create(), llvm::object::ObjectFile::createObjectFile(), D, llvm::WithColor::defaultErrorHandler(), llvm::WithColor::defaultWarningHandler(), llvm::SmallVectorBase< Size_T >::empty(), llvm::Expected< T >::get(), llvm::DWARFObject::getFileName(), and llvm::Expected< T >::takeError().
Referenced by ThreadSafeState::getDWOContext().
getDWOTypeUnitMap()
const DenseMap< uint64_t, DWARFTypeUnit * > & ThreadUnsafeDWARFContextState::getDWOTypeUnitMap () inline
Definition at line 607 of file DWARFContext.cpp.
References D.
getDWOUnits()
DWARFUnitVector & ThreadUnsafeDWARFContextState::getDWOUnits (bool Lazy) inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 303 of file DWARFContext.cpp.
References llvm::DWARFUnitVector::addUnitsForDWOSection(), D, llvm::DW_SECT_EXT_TYPES, llvm::SmallVectorBase< Size_T >::empty(), llvm::DWARFUnitVector::finishedInfoUnits(), llvm::DWARFObject::forEachInfoDWOSections(), and llvm::DWARFObject::forEachTypesDWOSections().
Referenced by ThreadSafeState::getDWOUnits().
getEHFrame()
Expected< const DWARFDebugFrame * > ThreadUnsafeDWARFContextState::getEHFrame () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 470 of file DWARFContext.cpp.
References D, DF, E, llvm::DWARFObject::getAddressSize(), and llvm::DWARFObject::getEHFrameSection().
Referenced by ThreadSafeState::getEHFrame().
getGdbIndex()
DWARFGdbIndex & ThreadUnsafeDWARFContextState::getGdbIndex () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 353 of file DWARFContext.cpp.
References D.
Referenced by ThreadSafeState::getGdbIndex().
getLineTableForUnit()
Expected< const DWARFDebugLine::LineTable * > ThreadUnsafeDWARFContextState::getLineTableForUnit (DWARFUnit * U, function_ref< void(Error)> RecoverableErrorHandler) inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 398 of file DWARFContext.cpp.
References llvm::Offset, and llvm::dwarf::toSectionOffset().
Referenced by ThreadSafeState::getLineTableForUnit().
getNormalTypeUnitMap()
const DenseMap< uint64_t, DWARFTypeUnit * > & ThreadUnsafeDWARFContextState::getNormalTypeUnitMap () inline
Definition at line 596 of file DWARFContext.cpp.
References D.
getNormalUnits()
DWARFUnitVector & ThreadUnsafeDWARFContextState::getNormalUnits () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 289 of file DWARFContext.cpp.
References llvm::DWARFUnitVector::addUnitsForSection(), D, llvm::DW_SECT_EXT_TYPES, llvm::SmallVectorBase< Size_T >::empty(), llvm::DWARFUnitVector::finishedInfoUnits(), llvm::DWARFObject::forEachInfoSections(), and llvm::DWARFObject::forEachTypesSections().
Referenced by ThreadSafeState::getNormalUnits().
getTUIndex()
const DWARFUnitIndex & ThreadUnsafeDWARFContextState::getTUIndex () inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 338 of file DWARFContext.cpp.
References D, llvm::DW_SECT_EXT_TYPES, and fixupIndex().
Referenced by ThreadSafeState::getTUIndex().
getTypeUnitMap()
const DenseMap< uint64_t, DWARFTypeUnit * > & ThreadUnsafeDWARFContextState::getTypeUnitMap (bool IsDWO) inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 619 of file DWARFContext.cpp.
Referenced by ThreadSafeState::getTypeUnitMap().
isThreadSafe()
bool ThreadUnsafeDWARFContextState::isThreadSafe () const inline override virtual
Implements llvm::DWARFContext::DWARFContextState.
Reimplemented in ThreadSafeState.
Definition at line 594 of file DWARFContext.cpp.
The documentation for this class was generated from the following file:
lib/DebugInfo/DWARF/DWARFContext.cpp