LLVM: llvm::SystemZMachineFunctionInfo Class Reference
llvm::SystemZMachineFunctionInfo Class Reference
#include "Target/SystemZ/SystemZMachineFunctionInfo.h"
Public Member Functions
SystemZMachineFunctionInfo (const Function &F, const TargetSubtargetInfo *STI)
MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const override
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
unsigned getSizeOfFnParams () const
void setSizeOfFnParams (unsigned Size)
SystemZ::GPRRegs getSpillGPRRegs () const
void setSpillGPRRegs (Register Low, Register High, unsigned Offs)
SystemZ::GPRRegs getRestoreGPRRegs () const
void setRestoreGPRRegs (Register Low, Register High, unsigned Offs)
Register getVarArgsFirstGPR () const
void setVarArgsFirstGPR (Register GPR)
Register getVarArgsFirstFPR () const
void setVarArgsFirstFPR (Register FPR)
unsigned getVarArgsFrameIndex () const
void setVarArgsFrameIndex (unsigned FI)
unsigned getRegSaveFrameIndex () const
void setRegSaveFrameIndex (unsigned FI)
int getFramePointerSaveIndex () const
void setFramePointerSaveIndex (int Idx)
unsigned getNumLocalDynamicTLSAccesses () const
void incNumLocalDynamicTLSAccesses ()
Register getADAVirtualRegister () const
void setADAVirtualRegister (Register Reg)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
virtual MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy , typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Detailed Description
Definition at line 27 of file SystemZMachineFunctionInfo.h.
Constructor & Destructor Documentation
SystemZMachineFunctionInfo()
llvm::SystemZMachineFunctionInfo::SystemZMachineFunctionInfo (const Function & F, const TargetSubtargetInfo * STI) inline
Definition at line 45 of file SystemZMachineFunctionInfo.h.
Member Function Documentation
clone()
MachineFunctionInfo * SystemZMachineFunctionInfo::clone (BumpPtrAllocator & Allocator, MachineFunction & DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) const override virtual
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
This requires remapping MachineBasicBlock references from the original parent to values in the new function. Targets may assume that virtual register and frame index values are preserved in the new function.
Reimplemented from llvm::MachineFunctionInfo.
Definition at line 17 of file SystemZMachineFunctionInfo.cpp.
References llvm::MachineFunction::cloneInfo().
getADAVirtualRegister()
Register llvm::SystemZMachineFunctionInfo::getADAVirtualRegister () const inline
Definition at line 108 of file SystemZMachineFunctionInfo.h.
Referenced by getADAEntry(), and getzOSCalleeAndADA().
getFramePointerSaveIndex()
int llvm::SystemZMachineFunctionInfo::getFramePointerSaveIndex () const inline
Definition at line 99 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZELFFrameLowering::getOrCreateFramePointerSaveIndex().
getNumLocalDynamicTLSAccesses()
unsigned llvm::SystemZMachineFunctionInfo::getNumLocalDynamicTLSAccesses () const inline
Definition at line 103 of file SystemZMachineFunctionInfo.h.
getRegSaveFrameIndex()
unsigned llvm::SystemZMachineFunctionInfo::getRegSaveFrameIndex () const inline
Definition at line 95 of file SystemZMachineFunctionInfo.h.
getRestoreGPRRegs()
SystemZ::GPRRegs llvm::SystemZMachineFunctionInfo::getRestoreGPRRegs () const inline
Definition at line 73 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZELFFrameLowering::emitEpilogue(), llvm::SystemZXPLINKFrameLowering::emitEpilogue(), llvm::SystemZELFFrameLowering::processFunctionBeforeFrameFinalized(), llvm::SystemZELFFrameLowering::restoreCalleeSavedRegisters(), and llvm::SystemZXPLINKFrameLowering::restoreCalleeSavedRegisters().
getSizeOfFnParams()
unsigned llvm::SystemZMachineFunctionInfo::getSizeOfFnParams () const inline
Definition at line 57 of file SystemZMachineFunctionInfo.h.
getSpillGPRRegs()
SystemZ::GPRRegs llvm::SystemZMachineFunctionInfo::getSpillGPRRegs () const inline
Definition at line 63 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZELFFrameLowering::emitPrologue(), llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters(), and llvm::SystemZXPLINKFrameLowering::spillCalleeSavedRegisters().
getVarArgsFirstFPR()
Register llvm::SystemZMachineFunctionInfo::getVarArgsFirstFPR () const inline
Definition at line 86 of file SystemZMachineFunctionInfo.h.
getVarArgsFirstGPR()
Register llvm::SystemZMachineFunctionInfo::getVarArgsFirstGPR () const inline
Definition at line 82 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZELFFrameLowering::assignCalleeSavedSpillSlots(), llvm::SystemZELFFrameLowering::determineCalleeSaves(), and llvm::SystemZELFFrameLowering::spillCalleeSavedRegisters().
getVarArgsFrameIndex()
unsigned llvm::SystemZMachineFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 90 of file SystemZMachineFunctionInfo.h.
incNumLocalDynamicTLSAccesses()
void llvm::SystemZMachineFunctionInfo::incNumLocalDynamicTLSAccesses () inline
Definition at line 104 of file SystemZMachineFunctionInfo.h.
setADAVirtualRegister()
void llvm::SystemZMachineFunctionInfo::setADAVirtualRegister (Register Reg) inline
Definition at line 109 of file SystemZMachineFunctionInfo.h.
References Reg.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
setFramePointerSaveIndex()
void llvm::SystemZMachineFunctionInfo::setFramePointerSaveIndex (int Idx) inline
Definition at line 100 of file SystemZMachineFunctionInfo.h.
References Idx.
Referenced by llvm::SystemZELFFrameLowering::getOrCreateFramePointerSaveIndex().
setRegSaveFrameIndex()
void llvm::SystemZMachineFunctionInfo::setRegSaveFrameIndex (unsigned FI) inline
Definition at line 96 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
setRestoreGPRRegs()
void llvm::SystemZMachineFunctionInfo::setRestoreGPRRegs (Register Low, Register High, unsigned Offs) inline
Definition at line 74 of file SystemZMachineFunctionInfo.h.
References llvm::SystemZ::GPRRegs::GPROffset, High, llvm::SystemZ::GPRRegs::HighGPR, llvm::Low, and llvm::SystemZ::GPRRegs::LowGPR.
Referenced by llvm::SystemZELFFrameLowering::assignCalleeSavedSpillSlots(), and llvm::SystemZXPLINKFrameLowering::assignCalleeSavedSpillSlots().
setSizeOfFnParams()
void llvm::SystemZMachineFunctionInfo::setSizeOfFnParams (unsigned Size) inline
Definition at line 58 of file SystemZMachineFunctionInfo.h.
References Size.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
setSpillGPRRegs()
void llvm::SystemZMachineFunctionInfo::setSpillGPRRegs (Register Low, Register High, unsigned Offs) inline
Definition at line 64 of file SystemZMachineFunctionInfo.h.
References llvm::SystemZ::GPRRegs::GPROffset, High, llvm::SystemZ::GPRRegs::HighGPR, llvm::Low, and llvm::SystemZ::GPRRegs::LowGPR.
Referenced by llvm::SystemZELFFrameLowering::assignCalleeSavedSpillSlots(), and llvm::SystemZXPLINKFrameLowering::assignCalleeSavedSpillSlots().
setVarArgsFirstFPR()
void llvm::SystemZMachineFunctionInfo::setVarArgsFirstFPR (Register FPR) inline
Definition at line 87 of file SystemZMachineFunctionInfo.h.
References FPR.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
setVarArgsFirstGPR()
void llvm::SystemZMachineFunctionInfo::setVarArgsFirstGPR (Register GPR) inline
Definition at line 83 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
setVarArgsFrameIndex()
void llvm::SystemZMachineFunctionInfo::setVarArgsFrameIndex (unsigned FI) inline
Definition at line 91 of file SystemZMachineFunctionInfo.h.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZMachineFunctionInfo.h
lib/Target/SystemZ/SystemZMachineFunctionInfo.cpp