LLVM: llvm::BPFSubtarget Class Reference
llvm::BPFSubtarget Class Reference
#include "Target/BPF/BPFSubtarget.h"
Public Member Functions
BPFSubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const TargetMachine &TM)
BPFSubtarget & initializeSubtargetDependencies (StringRef CPU, StringRef FS)
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
bool getHasJmpExt () const
bool getHasJmp32 () const
bool getHasAlu32 () const
bool getUseDwarfRIS () const
bool hasLdsx () const
bool hasMovsx () const
bool hasBswap () const
bool hasSdivSmod () const
bool hasGotol () const
bool hasStoreImm () const
bool isLittleEndian () const
const BPFInstrInfo * getInstrInfo () const override
const BPFFrameLowering * getFrameLowering () const override
const BPFTargetLowering * getTargetLowering () const override
const BPFSelectionDAGInfo * getSelectionDAGInfo () const override
const BPFRegisterInfo * getRegisterInfo () const override
const CallLowering * getCallLowering () const override
InstructionSelector * getInstructionSelector () const override
const LegalizerInfo * getLegalizerInfo () const override
const RegisterBankInfo * getRegBankInfo () const override
Protected Attributes
bool isDummyMode
bool IsLittleEndian
bool HasJmpExt
bool HasJmp32
bool HasAlu32
bool UseDwarfRIS
bool HasLdsx
bool HasMovsx
bool HasBswap
bool HasSdivSmod
bool HasGotol
bool HasStoreImm
std::unique_ptr< CallLowering > CallLoweringInfo
std::unique_ptr< InstructionSelector > InstSelector
std::unique_ptr< LegalizerInfo > Legalizer
std::unique_ptr< RegisterBankInfo > RegBankInfo
Detailed Description
Definition at line 36 of file BPFSubtarget.h.
Constructor & Destructor Documentation
BPFSubtarget()
BPFSubtarget::BPFSubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const TargetMachine & TM)
Definition at line 96 of file BPFSubtarget.cpp.
References CallLoweringInfo, llvm::createBPFInstructionSelector(), getRegisterInfo(), getTargetLowering(), InstSelector, IsLittleEndian, RegBankInfo, and TM.
Member Function Documentation
getCallLowering()
const CallLowering * BPFSubtarget::getCallLowering () const override
Definition at line 112 of file BPFSubtarget.cpp.
References CallLoweringInfo.
getFrameLowering()
const BPFFrameLowering * llvm::BPFSubtarget::getFrameLowering () const inline override
Definition at line 99 of file BPFSubtarget.h.
getHasAlu32()
bool llvm::BPFSubtarget::getHasAlu32 () const inline
Definition at line 87 of file BPFSubtarget.h.
References HasAlu32.
Referenced by llvm::BPFTargetLowering::BPFTargetLowering().
getHasJmp32()
bool llvm::BPFSubtarget::getHasJmp32 () const inline
Definition at line 86 of file BPFSubtarget.h.
References HasJmp32.
Referenced by llvm::BPFTargetLowering::BPFTargetLowering().
getHasJmpExt()
bool llvm::BPFSubtarget::getHasJmpExt () const inline
Definition at line 85 of file BPFSubtarget.h.
References HasJmpExt.
Referenced by llvm::BPFTargetLowering::BPFTargetLowering().
getInstrInfo()
const BPFInstrInfo * llvm::BPFSubtarget::getInstrInfo () const inline override
Definition at line 98 of file BPFSubtarget.h.
getInstructionSelector()
InstructionSelector * BPFSubtarget::getInstructionSelector () const override
Definition at line 116 of file BPFSubtarget.cpp.
References InstSelector.
getLegalizerInfo()
const LegalizerInfo * BPFSubtarget::getLegalizerInfo () const override
Definition at line 120 of file BPFSubtarget.cpp.
getRegBankInfo()
const RegisterBankInfo * BPFSubtarget::getRegBankInfo () const override
Definition at line 124 of file BPFSubtarget.cpp.
References RegBankInfo.
getRegisterInfo()
const BPFRegisterInfo * llvm::BPFSubtarget::getRegisterInfo () const inline override
Definition at line 108 of file BPFSubtarget.h.
References llvm::BPFInstrInfo::getRegisterInfo().
Referenced by BPFSubtarget(), and llvm::BPFTargetLowering::BPFTargetLowering().
getSelectionDAGInfo()
const BPFSelectionDAGInfo * llvm::BPFSubtarget::getSelectionDAGInfo () const inline override
Definition at line 105 of file BPFSubtarget.h.
Referenced by llvm::BPFTargetLowering::BPFTargetLowering().
getTargetLowering()
const BPFTargetLowering * llvm::BPFSubtarget::getTargetLowering () const inline override
Definition at line 102 of file BPFSubtarget.h.
Referenced by BPFSubtarget().
getUseDwarfRIS()
bool llvm::BPFSubtarget::getUseDwarfRIS () const inline
Definition at line 88 of file BPFSubtarget.h.
References UseDwarfRIS.
Referenced by llvm::BPFTargetMachine::BPFTargetMachine().
hasBswap()
bool llvm::BPFSubtarget::hasBswap () const inline
Definition at line 91 of file BPFSubtarget.h.
References HasBswap.
hasGotol()
bool llvm::BPFSubtarget::hasGotol () const inline
Definition at line 93 of file BPFSubtarget.h.
References HasGotol.
hasLdsx()
bool llvm::BPFSubtarget::hasLdsx () const inline
Definition at line 89 of file BPFSubtarget.h.
References HasLdsx.
Referenced by llvm::BPFTargetLowering::BPFTargetLowering().
hasMovsx()
bool llvm::BPFSubtarget::hasMovsx () const inline
Definition at line 90 of file BPFSubtarget.h.
References HasMovsx.
Referenced by llvm::BPFTargetLowering::BPFTargetLowering().
hasSdivSmod()
bool llvm::BPFSubtarget::hasSdivSmod () const inline
Definition at line 92 of file BPFSubtarget.h.
References HasSdivSmod.
Referenced by llvm::BPFTargetLowering::BPFTargetLowering().
hasStoreImm()
bool llvm::BPFSubtarget::hasStoreImm () const inline
Definition at line 94 of file BPFSubtarget.h.
References HasStoreImm.
initializeSubtargetDependencies()
BPFSubtarget & BPFSubtarget::initializeSubtargetDependencies (StringRef CPU, StringRef FS)
Definition at line 46 of file BPFSubtarget.cpp.
References ParseSubtargetFeatures().
isLittleEndian()
bool llvm::BPFSubtarget::isLittleEndian () const inline
Definition at line 96 of file BPFSubtarget.h.
References IsLittleEndian.
ParseSubtargetFeatures()
void llvm::BPFSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
Referenced by initializeSubtargetDependencies().
Member Data Documentation
CallLoweringInfo
std::unique_ptr<CallLowering> llvm::BPFSubtarget::CallLoweringInfo protected
Definition at line 69 of file BPFSubtarget.h.
Referenced by BPFSubtarget(), and getCallLowering().
HasAlu32
bool llvm::BPFSubtarget::HasAlu32 protected
Definition at line 61 of file BPFSubtarget.h.
Referenced by getHasAlu32().
HasBswap
bool llvm::BPFSubtarget::HasBswap protected
Definition at line 67 of file BPFSubtarget.h.
Referenced by hasBswap().
HasGotol
bool llvm::BPFSubtarget::HasGotol protected
Definition at line 67 of file BPFSubtarget.h.
Referenced by hasGotol().
HasJmp32
bool llvm::BPFSubtarget::HasJmp32 protected
Definition at line 58 of file BPFSubtarget.h.
Referenced by getHasJmp32().
HasJmpExt
bool llvm::BPFSubtarget::HasJmpExt protected
Definition at line 54 of file BPFSubtarget.h.
Referenced by getHasJmpExt().
HasLdsx
bool llvm::BPFSubtarget::HasLdsx protected
Definition at line 67 of file BPFSubtarget.h.
Referenced by hasLdsx().
HasMovsx
bool llvm::BPFSubtarget::HasMovsx protected
Definition at line 67 of file BPFSubtarget.h.
Referenced by hasMovsx().
HasSdivSmod
bool llvm::BPFSubtarget::HasSdivSmod protected
Definition at line 67 of file BPFSubtarget.h.
Referenced by hasSdivSmod().
HasStoreImm
bool llvm::BPFSubtarget::HasStoreImm protected
Definition at line 67 of file BPFSubtarget.h.
Referenced by hasStoreImm().
InstSelector
std::unique_ptr<InstructionSelector> llvm::BPFSubtarget::InstSelector protected
Definition at line 70 of file BPFSubtarget.h.
Referenced by BPFSubtarget(), and getInstructionSelector().
isDummyMode
bool llvm::BPFSubtarget::isDummyMode protected
Definition at line 49 of file BPFSubtarget.h.
IsLittleEndian
bool llvm::BPFSubtarget::IsLittleEndian protected
Definition at line 51 of file BPFSubtarget.h.
Referenced by BPFSubtarget(), and isLittleEndian().
Legalizer
std::unique_ptr<LegalizerInfo> llvm::BPFSubtarget::Legalizer protected
Definition at line 71 of file BPFSubtarget.h.
RegBankInfo
std::unique_ptr<RegisterBankInfo> llvm::BPFSubtarget::RegBankInfo protected
Definition at line 72 of file BPFSubtarget.h.
Referenced by BPFSubtarget(), and getRegBankInfo().
UseDwarfRIS
bool llvm::BPFSubtarget::UseDwarfRIS protected
Definition at line 64 of file BPFSubtarget.h.
Referenced by getUseDwarfRIS().
The documentation for this class was generated from the following files:
lib/Target/BPF/BPFSubtarget.h
lib/Target/BPF/BPFSubtarget.cpp