LLVM: llvm::orc::EPCGenericJITLinkMemoryManager::InFlightAlloc Class Reference
llvm::orc::EPCGenericJITLinkMemoryManager::InFlightAlloc Class Reference
Classes
struct SegInfo
Public Types
using SegInfoMap = AllocGroupSmallMap< SegInfo >
Public Types inherited from llvm::jitlink::JITLinkMemoryManager::InFlightAlloc
using OnFinalizedFunction = unique_function< void(Expected< FinalizedAlloc >)>
using OnAbandonedFunction = unique_function< void(Error)>
Public Member Functions
InFlightAlloc (EPCGenericJITLinkMemoryManager &Parent, LinkGraph &G, ExecutorAddr AllocAddr, SegInfoMap Segs)
void finalize (OnFinalizedFunction OnFinalize) override
Called to transfer working memory to the target and apply finalization.
void abandon (OnAbandonedFunction OnAbandoned) override
Called prior to finalization if the allocation should be abandoned.
Public Member Functions inherited from llvm::jitlink::JITLinkMemoryManager::InFlightAlloc
virtual ~InFlightAlloc ()
virtual void abandon (OnAbandonedFunction OnAbandoned)=0
Called prior to finalization if the allocation should be abandoned.
virtual void finalize (OnFinalizedFunction OnFinalized)=0
Called to transfer working memory to the target and apply finalization.
Expected< FinalizedAlloc > finalize ()
Synchronous convenience version of finalize.
Detailed Description
Definition at line 22 of file EPCGenericJITLinkMemoryManager.cpp.
Member Typedef Documentation
SegInfoMap
using llvm::orc::EPCGenericJITLinkMemoryManager::InFlightAlloc::SegInfoMap = AllocGroupSmallMap<SegInfo>
Definition at line 39 of file EPCGenericJITLinkMemoryManager.cpp.
Constructor & Destructor Documentation
InFlightAlloc()
llvm::orc::EPCGenericJITLinkMemoryManager::InFlightAlloc::InFlightAlloc (EPCGenericJITLinkMemoryManager & Parent, LinkGraph & G, ExecutorAddr AllocAddr, SegInfoMap Segs) inline
Definition at line 41 of file EPCGenericJITLinkMemoryManager.cpp.
References G.
Member Function Documentation
abandon()
void llvm::orc::EPCGenericJITLinkMemoryManager::InFlightAlloc::abandon (OnAbandonedFunction OnAbandoned) inline override virtual
Called prior to finalization if the allocation should be abandoned.
Implements llvm::jitlink::JITLinkMemoryManager::InFlightAlloc.
Definition at line 77 of file EPCGenericJITLinkMemoryManager.cpp.
References llvm::orc::EPCGenericJITLinkMemoryManager::SymbolAddrs::Allocator, llvm::orc::ExecutorProcessControl::callSPSWrapperAsync(), llvm::cantFail(), and llvm::orc::EPCGenericJITLinkMemoryManager::SymbolAddrs::Deallocate.
finalize()
void llvm::orc::EPCGenericJITLinkMemoryManager::InFlightAlloc::finalize (OnFinalizedFunction OnFinalized) inline override virtual
Called to transfer working memory to the target and apply finalization.
Implements llvm::jitlink::JITLinkMemoryManager::InFlightAlloc.
Definition at line 45 of file EPCGenericJITLinkMemoryManager.cpp.
References llvm::orc::tpctypes::FinalizeRequest::Actions, llvm::orc::tpctypes::SegFinalizeRequest::Addr, llvm::alignTo(), llvm::jitlink::LinkGraph::allocActions(), llvm::orc::EPCGenericJITLinkMemoryManager::SymbolAddrs::Allocator, assert(), llvm::orc::ExecutorProcessControl::callSPSWrapperAsync(), llvm::cantFail(), llvm::orc::EPCGenericJITLinkMemoryManager::SymbolAddrs::Finalize, llvm::orc::ExecutorProcessControl::getPageSize(), llvm::orc::tpctypes::FinalizeRequest::Segments, and std::swap().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/EPCGenericJITLinkMemoryManager.cpp