LLVM: llvm::LoongArchSubtarget Class Reference
llvm::LoongArchSubtarget Class Reference
#include "Target/LoongArch/LoongArchSubtarget.h"
Public Member Functions
LoongArchSubtarget (const Triple &TT, StringRef CPU, StringRef TuneCPU, StringRef FS, StringRef ABIName, const TargetMachine &TM)
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
const LoongArchFrameLowering * getFrameLowering () const override
const LoongArchInstrInfo * getInstrInfo () const override
const LoongArchRegisterInfo * getRegisterInfo () const override
const LoongArchTargetLowering * getTargetLowering () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
bool is64Bit () const
bool hasBasicF () const
bool hasBasicD () const
bool hasExtLSX () const
bool hasExtLASX () const
bool hasExtLVZ () const
bool hasExtLBT () const
bool hasLaGlobalWithPcrel () const
bool hasLaGlobalWithAbs () const
bool hasLaLocalWithAbs () const
bool hasUAL () const
bool hasLinkerRelax () const
bool hasExpAutoVec () const
bool hasFrecipe () const
MVT getGRLenVT () const
unsigned getGRLen () const
LoongArchABI::ABI getTargetABI () const
bool isXRaySupported () const override
Align getPrefFunctionAlignment () const
Align getPrefLoopAlignment () const
unsigned getMaxBytesForAlignment () const
Detailed Description
Definition at line 32 of file LoongArchSubtarget.h.
Constructor & Destructor Documentation
LoongArchSubtarget()
LoongArchSubtarget::LoongArchSubtarget (const Triple & TT, StringRef CPU, StringRef TuneCPU, StringRef FS, StringRef ABIName, const TargetMachine & TM)
Definition at line 84 of file LoongArchSubtarget.cpp.
Member Function Documentation
getFrameLowering()
const LoongArchFrameLowering * llvm::LoongArchSubtarget::getFrameLowering () const inline override
Definition at line 82 of file LoongArchSubtarget.h.
getGRLen()
unsigned llvm::LoongArchSubtarget::getGRLen () const inline
Definition at line 110 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchTargetLowering::decomposeMulByConstant(), llvm::LoongArchTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::LoongArchTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::LoongArchTargetLowering::LoongArchTargetLowering(), llvm::LoongArchTargetLowering::LowerFormalArguments(), and llvm::LoongArchDAGToDAGISel::selectShiftMaskGRLen().
getGRLenVT()
MVT llvm::LoongArchSubtarget::getGRLenVT () const inline
Definition at line 109 of file LoongArchSubtarget.h.
Referenced by legalizeIntrinsicImmArg(), llvm::LoongArchTargetLowering::LoongArchTargetLowering(), llvm::LoongArchTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerFormalArguments(), performANDCombine(), performINTRINSIC_WO_CHAINCombine(), performORCombine(), performSRLCombine(), llvm::LoongArchTargetLowering::ReplaceNodeResults(), replaceVecCondBranchResults(), replaceVPICKVE2GRResults(), llvm::LoongArchDAGToDAGISel::SelectBaseAddr(), llvm::LoongArchDAGToDAGISel::SelectInlineAsmMemoryOperand(), and llvm::LoongArchDAGToDAGISel::selectVSplatImm().
getInstrInfo()
const LoongArchInstrInfo * llvm::LoongArchSubtarget::getInstrInfo () const inline override
Definition at line 85 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::LoongArchFrameLowering::emitPrologue(), emitPseudoXVINSGR2VR(), emitVecCondBranchPseudo(), and llvm::LoongArchFrameLowering::processFunctionBeforeFrameFinalized().
getMaxBytesForAlignment()
unsigned llvm::LoongArchSubtarget::getMaxBytesForAlignment () const inline
Definition at line 115 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchTargetLowering::LoongArchTargetLowering().
getPrefFunctionAlignment()
Align llvm::LoongArchSubtarget::getPrefFunctionAlignment () const inline
Definition at line 113 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchTargetLowering::LoongArchTargetLowering().
getPrefLoopAlignment()
Align llvm::LoongArchSubtarget::getPrefLoopAlignment () const inline
Definition at line 114 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchTargetLowering::LoongArchTargetLowering().
getRegisterInfo()
const LoongArchRegisterInfo * llvm::LoongArchSubtarget::getRegisterInfo () const inline override
Definition at line 86 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchFrameLowering::emitEpilogue(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::LoongArchTargetLowering::getRegisterByName(), llvm::LoongArchFrameLowering::hasBP(), llvm::LoongArchTargetLowering::LoongArchTargetLowering(), llvm::LoongArchTargetLowering::LowerCall(), and llvm::LoongArchFrameLowering::processFunctionBeforeFrameFinalized().
getSelectionDAGInfo()
const SelectionDAGTargetInfo * llvm::LoongArchSubtarget::getSelectionDAGInfo () const inline override
Definition at line 92 of file LoongArchSubtarget.h.
getTargetABI()
LoongArchABI::ABI llvm::LoongArchSubtarget::getTargetABI () const inline
Definition at line 111 of file LoongArchSubtarget.h.
getTargetLowering()
const LoongArchTargetLowering * llvm::LoongArchSubtarget::getTargetLowering () const inline override
Definition at line 89 of file LoongArchSubtarget.h.
hasBasicD()
bool llvm::LoongArchSubtarget::hasBasicD () const inline
Definition at line 97 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchTargetLowering::LoongArchTargetLowering().
hasBasicF()
bool llvm::LoongArchSubtarget::hasBasicF () const inline
Definition at line 96 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchTargetLowering::LoongArchTargetLowering(), needScavSlotForCFR(), and llvm::LoongArchTargetLowering::ReplaceNodeResults().
hasExpAutoVec()
bool llvm::LoongArchSubtarget::hasExpAutoVec () const inline
Definition at line 107 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchTTIImpl::getRegisterBitWidth().
hasExtLASX()
bool llvm::LoongArchSubtarget::hasExtLASX () const inline
Definition at line 99 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchTTIImpl::getRegisterBitWidth(), and llvm::LoongArchTargetLowering::LoongArchTargetLowering().
hasExtLBT()
bool llvm::LoongArchSubtarget::hasExtLBT () const inline
Definition at line 101 of file LoongArchSubtarget.h.
hasExtLSX()
bool llvm::LoongArchSubtarget::hasExtLSX () const inline
Definition at line 98 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchTTIImpl::getRegisterBitWidth(), llvm::LoongArchTargetLowering::LoongArchTargetLowering(), and llvm::LoongArchDAGToDAGISel::selectVSplat().
hasExtLVZ()
bool llvm::LoongArchSubtarget::hasExtLVZ () const inline
Definition at line 100 of file LoongArchSubtarget.h.
hasFrecipe()
bool llvm::LoongArchSubtarget::hasFrecipe () const inline
Definition at line 108 of file LoongArchSubtarget.h.
hasLaGlobalWithAbs()
bool llvm::LoongArchSubtarget::hasLaGlobalWithAbs () const inline
Definition at line 103 of file LoongArchSubtarget.h.
hasLaGlobalWithPcrel()
bool llvm::LoongArchSubtarget::hasLaGlobalWithPcrel () const inline
Definition at line 102 of file LoongArchSubtarget.h.
hasLaLocalWithAbs()
bool llvm::LoongArchSubtarget::hasLaLocalWithAbs () const inline
Definition at line 104 of file LoongArchSubtarget.h.
hasLinkerRelax()
bool llvm::LoongArchSubtarget::hasLinkerRelax () const inline
Definition at line 106 of file LoongArchSubtarget.h.
hasUAL()
bool llvm::LoongArchSubtarget::hasUAL () const inline
Definition at line 105 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchTargetLowering::allowsMisalignedMemoryAccesses().
is64Bit()
bool llvm::LoongArchSubtarget::is64Bit () const inline
Definition at line 95 of file LoongArchSubtarget.h.
Referenced by llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::LoongArchFrameLowering::emitPrologue(), llvm::LoongArchTTIImpl::getRegisterBitWidth(), llvm::LoongArchInstrInfo::insertIndirectBranch(), llvm::LoongArchTargetLowering::isSExtCheaperThanZExt(), isXRaySupported(), llvm::LoongArchTargetLowering::LoongArchTargetLowering(), llvm::LoongArchTargetLowering::LowerCall(), llvm::LoongArchInstrInfo::movImm(), and llvm::LoongArchTargetLowering::ReplaceNodeResults().
isXRaySupported()
bool llvm::LoongArchSubtarget::isXRaySupported () const inline override
Definition at line 112 of file LoongArchSubtarget.h.
References is64Bit().
ParseSubtargetFeatures()
void llvm::LoongArchSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
The documentation for this class was generated from the following files:
lib/Target/LoongArch/LoongArchSubtarget.h
lib/Target/LoongArch/LoongArchSubtarget.cpp