LLVM: llvm::orc::LazyCallThroughManager Class Reference
llvm::orc::LazyCallThroughManager Class Reference
Manages a set of 'lazy call-through' trampolines.
#include "llvm/ExecutionEngine/Orc/LazyReexports.h"
Classes
struct ReexportsEntry
Public Types
using NotifyResolvedFunction = unique_function< Error(ExecutorAddr ResolvedAddr)>
Public Member Functions
LazyCallThroughManager (ExecutionSession &ES, ExecutorAddr ErrorHandlerAddr, TrampolinePool *TP)
Expected< ExecutorAddr > getCallThroughTrampoline (JITDylib &SourceJD, SymbolStringPtr SymbolName, NotifyResolvedFunction NotifyResolved)
void resolveTrampolineLandingAddress (ExecutorAddr TrampolineAddr, TrampolinePool::NotifyLandingResolvedFunction NotifyLandingResolved)
virtual ~LazyCallThroughManager ()=default
Protected Types
using NotifyLandingResolvedFunction = TrampolinePool::NotifyLandingResolvedFunction
Protected Member Functions
ExecutorAddr reportCallThroughError (Error Err)
Expected< ReexportsEntry > findReexport (ExecutorAddr TrampolineAddr)
Error notifyResolved (ExecutorAddr TrampolineAddr, ExecutorAddr ResolvedAddr)
void setTrampolinePool (TrampolinePool &TP)
Detailed Description
Manages a set of 'lazy call-through' trampolines.
These are compiler re-entry trampolines that are pre-bound to look up a given symbol in a given JITDylib, then jump to that address. Since compilation of symbols is triggered on first lookup, these call-through trampolines can be used to implement lazy compilation.
The easiest way to construct these call-throughs is using the lazyReexport function.
Definition at line 38 of file LazyReexports.h.
Member Typedef Documentation
NotifyLandingResolvedFunction
using llvm::orc::LazyCallThroughManager::NotifyLandingResolvedFunction = TrampolinePool::NotifyLandingResolvedFunction protected
Definition at line 59 of file LazyReexports.h.
NotifyResolvedFunction
using llvm::orc::LazyCallThroughManager::NotifyResolvedFunction = unique_function<Error(ExecutorAddr ResolvedAddr)>
Definition at line 40 of file LazyReexports.h.
Constructor & Destructor Documentation
LazyCallThroughManager()
llvm::orc::LazyCallThroughManager::LazyCallThroughManager (ExecutionSession & ES, ExecutorAddr ErrorHandlerAddr, TrampolinePool * TP)
Definition at line 19 of file LazyReexports.cpp.
~LazyCallThroughManager()
virtual llvm::orc::LazyCallThroughManager::~LazyCallThroughManager () virtual default
Member Function Documentation
findReexport()
Expected< LazyCallThroughManager::ReexportsEntry > llvm::orc::LazyCallThroughManager::findReexport (ExecutorAddr TrampolineAddr) protected
Definition at line 46 of file LazyReexports.cpp.
References llvm::createStringError(), llvm::formatv(), I, and llvm::inconvertibleErrorCode().
Referenced by resolveTrampolineLandingAddress().
getCallThroughTrampoline()
Expected< ExecutorAddr > llvm::orc::LazyCallThroughManager::getCallThroughTrampoline (JITDylib & SourceJD, SymbolStringPtr SymbolName, NotifyResolvedFunction NotifyResolved)
Definition at line 24 of file LazyReexports.cpp.
References assert(), and llvm::orc::TrampolinePool::getTrampoline().
notifyResolved()
Error llvm::orc::LazyCallThroughManager::notifyResolved (ExecutorAddr TrampolineAddr, ExecutorAddr ResolvedAddr) protected
Definition at line 56 of file LazyReexports.cpp.
References I, and llvm::Error::success().
Referenced by resolveTrampolineLandingAddress().
reportCallThroughError()
ExecutorAddr llvm::orc::LazyCallThroughManager::reportCallThroughError (Error Err) protected
Definition at line 40 of file LazyReexports.cpp.
References llvm::orc::ExecutionSession::reportError().
Referenced by resolveTrampolineLandingAddress().
resolveTrampolineLandingAddress()
void llvm::orc::LazyCallThroughManager::resolveTrampolineLandingAddress (ExecutorAddr TrampolineAddr, TrampolinePool::NotifyLandingResolvedFunction NotifyLandingResolved)
Definition at line 71 of file LazyReexports.cpp.
References assert(), findReexport(), llvm::orc::ExecutionSession::lookup(), llvm::orc::makeJITDylibSearchOrder(), llvm::orc::MatchAllSymbols, llvm::orc::NoDependenciesToRegister, notifyResolved(), llvm::orc::Ready, reportCallThroughError(), llvm::orc::Result, and llvm::orc::Static.
setTrampolinePool()
void llvm::orc::LazyCallThroughManager::setTrampolinePool (TrampolinePool & TP) inline protected
Definition at line 70 of file LazyReexports.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/LazyReexports.h
lib/ExecutionEngine/Orc/LazyReexports.cpp