LLVM: llvm::InstrProfCorrelator Class Reference
llvm::InstrProfCorrelator Class Reference abstract
InstrProfCorrelator - A base class used to create raw instrumentation data to their functions.
#include "llvm/ProfileData/InstrProfCorrelator.h"
Classes
struct Context
struct CorrelationData
struct Probe
Public Types
enum ProfCorrelatorKind { NONE , DEBUG_INFO , BINARY }
Indicate if we should use the debug info or profile metadata sections to correlate.
enum InstrProfCorrelatorKind { CK_32Bit , CK_64Bit }
Public Member Functions
virtual Error correlateProfileData (int MaxWarnings)=0
Construct a ProfileData vector used to correlate raw instrumentation data to their functions.
virtual Error dumpYaml (int MaxWarnings, raw_ostream &OS)=0
Process debug info and dump the correlation data.
std::optional< size_t > getDataSize () const
Return the number of ProfileData elements.
const char * getNamesPointer () const
Return a pointer to the names string that this class constructs.
size_t getNamesSize () const
Return the number of bytes in the names string.
uint64_t getCountersSectionSize () const
Return the size of the counters section in bytes.
InstrProfCorrelatorKind getKind () const
virtual ~InstrProfCorrelator ()=default
Static Public Member Functions
static llvm::Expected< std::unique_ptr< InstrProfCorrelator > > get (StringRef Filename, ProfCorrelatorKind FileKind)
Static Public Attributes
static const char * FunctionNameAttributeName = "Function Name"
static const char * CFGHashAttributeName = "CFG Hash"
static const char * NumCountersAttributeName = "Num Counters"
Protected Member Functions
InstrProfCorrelator (InstrProfCorrelatorKind K, std::unique_ptr< Context > Ctx)
Protected Attributes
const std::unique_ptr< Context > Ctx
std::string Names
std::vector< std::string > NamesVec
Friends
struct yaml::MappingTraits< Probe >
struct yaml::SequenceElementTraits< Probe >
struct yaml::MappingTraits< CorrelationData >
Detailed Description
InstrProfCorrelator - A base class used to create raw instrumentation data to their functions.
Definition at line 32 of file InstrProfCorrelator.h.
Member Enumeration Documentation
InstrProfCorrelatorKind
enum llvm::InstrProfCorrelator::InstrProfCorrelatorKind
Enumerator
CK_32Bit
CK_64Bit
Definition at line 68 of file InstrProfCorrelator.h.
ProfCorrelatorKind
enum llvm::InstrProfCorrelator::ProfCorrelatorKind
Indicate if we should use the debug info or profile metadata sections to correlate.
Enumerator
NONE
DEBUG_INFO
BINARY
Definition at line 36 of file InstrProfCorrelator.h.
Constructor & Destructor Documentation
~InstrProfCorrelator()
virtual llvm::InstrProfCorrelator::~InstrProfCorrelator () virtual default
InstrProfCorrelator()
llvm::InstrProfCorrelator::InstrProfCorrelator (InstrProfCorrelatorKind K, std::unique_ptr< Context > Ctx) inline protected
Definition at line 92 of file InstrProfCorrelator.h.
Member Function Documentation
correlateProfileData()
virtual Error llvm::InstrProfCorrelator::correlateProfileData (int MaxWarnings) pure virtual
Construct a ProfileData vector used to correlate raw instrumentation data to their functions.
Parameters
MaxWarnings the maximum number of warnings to emit (0 = no limit)
Implemented in llvm::InstrProfCorrelatorImpl< IntPtrT >.
dumpYaml()
virtual Error llvm::InstrProfCorrelator::dumpYaml (int MaxWarnings, raw_ostream & OS) pure virtual
Process debug info and dump the correlation data.
Parameters
MaxWarnings the maximum number of warnings to emit (0 = no limit)
Implemented in llvm::InstrProfCorrelatorImpl< IntPtrT >.
get()
llvm::Expected< std::unique_ptr< InstrProfCorrelator > > InstrProfCorrelator::get (StringRef Filename, ProfCorrelatorKind FileKind) static
Definition at line 94 of file InstrProfCorrelator.cpp.
References BINARY, DEBUG_INFO, llvm::errorOrToExpected(), llvm::object::MachOObjectFile::findDsymObjectMembers(), get(), llvm::MemoryBuffer::getFile(), and llvm::unable_to_correlate_profile.
Referenced by get().
getCountersSectionSize()
uint64_t llvm::InstrProfCorrelator::getCountersSectionSize () const inline
Return the size of the counters section in bytes.
Definition at line 60 of file InstrProfCorrelator.h.
References Ctx.
getDataSize()
std::optional< size_t > InstrProfCorrelator::getDataSize () const
Return the number of ProfileData elements.
Definition at line 151 of file InstrProfCorrelator.cpp.
References llvm::CallingConv::C, and llvm::dyn_cast().
getKind()
InstrProfCorrelatorKind llvm::InstrProfCorrelator::getKind () const inline
Definition at line 69 of file InstrProfCorrelator.h.
getNamesPointer()
const char * llvm::InstrProfCorrelator::getNamesPointer () const inline
Return a pointer to the names string that this class constructs.
Definition at line 54 of file InstrProfCorrelator.h.
References Names.
getNamesSize()
size_t llvm::InstrProfCorrelator::getNamesSize () const inline
Return the number of bytes in the names string.
Definition at line 57 of file InstrProfCorrelator.h.
References Names.
Friends And Related Function Documentation
yaml::MappingTraits< CorrelationData >
friend struct yaml::MappingTraits< CorrelationData > friend
Definition at line 96 of file InstrProfCorrelator.h.
yaml::MappingTraits< Probe >
friend struct yaml::MappingTraits< Probe > friend
Definition at line 96 of file InstrProfCorrelator.h.
yaml::SequenceElementTraits< Probe >
friend struct yaml::SequenceElementTraits< Probe > friend
Definition at line 96 of file InstrProfCorrelator.h.
Member Data Documentation
CFGHashAttributeName
const char * InstrProfCorrelator::CFGHashAttributeName = "CFG Hash" static
Definition at line 65 of file InstrProfCorrelator.h.
Ctx
const std::unique_ptr<Context> llvm::InstrProfCorrelator::Ctx protected
Definition at line 90 of file InstrProfCorrelator.h.
Referenced by getCountersSectionSize(), llvm::BinaryInstrProfCorrelator< IntPtrT >::getNamesPointer(), llvm::BinaryInstrProfCorrelator< IntPtrT >::getNamesSize(), and llvm::InstrProfCorrelatorImpl< IntPtrT >::maybeSwap().
FunctionNameAttributeName
const char * InstrProfCorrelator::FunctionNameAttributeName = "Function Name" static
Definition at line 64 of file InstrProfCorrelator.h.
Names
std::string llvm::InstrProfCorrelator::Names protected
Definition at line 95 of file InstrProfCorrelator.h.
Referenced by getNamesPointer(), and getNamesSize().
NamesVec
std::vector<std::string> llvm::InstrProfCorrelator::NamesVec protected
Definition at line 96 of file InstrProfCorrelator.h.
NumCountersAttributeName
const char * InstrProfCorrelator::NumCountersAttributeName = "Num Counters" static
Definition at line 66 of file InstrProfCorrelator.h.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/InstrProfCorrelator.h
lib/ProfileData/InstrProfCorrelator.cpp