LLVM: llvm::MSP430RegisterInfo Class Reference
llvm::MSP430RegisterInfo Class Reference
#include "Target/MSP430/MSP430RegisterInfo.h"
Public Member Functions
MSP430RegisterInfo ()
const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const override
Code Generation virtual methods...
BitVector getReservedRegs (const MachineFunction &MF) const override
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const override
bool eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const override
Register getFrameRegister (const MachineFunction &MF) const override
Detailed Description
Definition at line 23 of file MSP430RegisterInfo.h.
Constructor & Destructor Documentation
MSP430RegisterInfo()
MSP430RegisterInfo::MSP430RegisterInfo ()
Definition at line 34 of file MSP430RegisterInfo.cpp.
Member Function Documentation
eliminateFrameIndex()
bool MSP430RegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const override
Definition at line 103 of file MSP430RegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineBasicBlock::getParent(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MSP430FrameLowering::hasFP(), MBB, MI, llvm::Offset, and TII.
getCalleeSavedRegs()
const MCPhysReg * MSP430RegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const override
Code Generation virtual methods...
Definition at line 38 of file MSP430RegisterInfo.cpp.
References F, llvm::MachineFunction::getFunction(), llvm::MSP430FrameLowering::hasFP(), and llvm::CallingConv::MSP430_INTR.
getFrameRegister()
Register MSP430RegisterInfo::getFrameRegister (const MachineFunction & MF) const override
Definition at line 161 of file MSP430RegisterInfo.cpp.
References llvm::MSP430FrameLowering::hasFP().
getPointerRegClass()
const TargetRegisterClass * MSP430RegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const override
Definition at line 97 of file MSP430RegisterInfo.cpp.
getReservedRegs()
BitVector MSP430RegisterInfo::getReservedRegs (const MachineFunction & MF) const override
Definition at line 73 of file MSP430RegisterInfo.cpp.
References llvm::MSP430FrameLowering::hasFP(), and llvm::Reserved.
The documentation for this class was generated from the following files:
lib/Target/MSP430/MSP430RegisterInfo.h
lib/Target/MSP430/MSP430RegisterInfo.cpp