LLVM: llvm::BinaryStreamRefBase< RefType, StreamType > Class Template Reference
llvm::BinaryStreamRefBase< RefType, StreamType > Class Template Reference
Common stuff for mutable and immutable StreamRefs.
#include "llvm/Support/BinaryStreamRef.h"
Public Member Functions
llvm::endianness getEndian () const
uint64_t getLength () const
RefType drop_front (uint64_t N) const
Return a new BinaryStreamRef with the first N elements removed.
RefType drop_back (uint64_t N) const
Return a new BinaryStreamRef with the last N elements removed.
RefType keep_front (uint64_t N) const
Return a new BinaryStreamRef with only the first N elements remaining.
RefType keep_back (uint64_t N) const
Return a new BinaryStreamRef with only the last N elements remaining.
RefType drop_symmetric (uint64_t N) const
Return a new BinaryStreamRef with the first and last N elements removed.
RefType slice (uint64_t Offset, uint64_t Len) const
Return a new BinaryStreamRef with the first Offset elements removed, and retaining exactly Len elements.
bool valid () const
Protected Member Functions
BinaryStreamRefBase ()=default
BinaryStreamRefBase (StreamType &BorrowedImpl)
BinaryStreamRefBase (std::shared_ptr< StreamType > SharedImpl, uint64_t Offset, std::optional< uint64_t > Length)
BinaryStreamRefBase (StreamType &BorrowedImpl, uint64_t Offset, std::optional< uint64_t > Length)
BinaryStreamRefBase (const BinaryStreamRefBase &Other)=default
BinaryStreamRefBase & operator= (const BinaryStreamRefBase &Other)=default
BinaryStreamRefBase & operator= (BinaryStreamRefBase &&Other)=default
BinaryStreamRefBase (BinaryStreamRefBase &&Other)=default
Error checkOffsetForRead (uint64_t Offset, uint64_t DataSize) const
Protected Attributes
std::shared_ptr< StreamType > SharedImpl
StreamType * BorrowedImpl = nullptr
uint64_t ViewOffset = 0
std::optional< uint64_t > Length
Friends
bool operator== (const RefType &LHS, const RefType &RHS)
Detailed Description
template<class RefType, class StreamType>
class llvm::BinaryStreamRefBase< RefType, StreamType >
Common stuff for mutable and immutable StreamRefs.
Definition at line 23 of file BinaryStreamRef.h.
Constructor & Destructor Documentation
BinaryStreamRefBase() [1/6]
template<class RefType , class StreamType > llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase () protected default
BinaryStreamRefBase() [2/6]
template<class RefType , class StreamType > llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase (StreamType & BorrowedImpl) inline explicit protected
Definition at line 26 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::BorrowedImpl, llvm::BSF_Append, and llvm::BinaryStreamRefBase< RefType, StreamType >::Length.
BinaryStreamRefBase() [3/6]
template<class RefType , class StreamType > llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase (std::shared_ptr< StreamType > SharedImpl, uint64_t Offset, std::optional< uint64_t > Length) inline protected
Definition at line 32 of file BinaryStreamRef.h.
BinaryStreamRefBase() [4/6]
template<class RefType , class StreamType > llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase (StreamType & BorrowedImpl, uint64_t Offset, std::optional< uint64_t > Length) inline protected
Definition at line 36 of file BinaryStreamRef.h.
BinaryStreamRefBase() [5/6]
template<class RefType , class StreamType > llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase (const BinaryStreamRefBase< RefType, StreamType > & Other) protected default
BinaryStreamRefBase() [6/6]
template<class RefType , class StreamType > llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase (BinaryStreamRefBase< RefType, StreamType > && Other) protected default
Member Function Documentation
checkOffsetForRead()
template<class RefType , class StreamType > Error llvm::BinaryStreamRefBase< RefType, StreamType >::checkOffsetForRead (uint64_t Offset, uint64_t DataSize) const inline protected
Definition at line 132 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::getLength(), llvm::invalid_offset, llvm::Offset, llvm::stream_too_short, and llvm::Error::success().
drop_back()
template<class RefType , class StreamType > RefType llvm::BinaryStreamRefBase< RefType, StreamType >::drop_back (uint64_t N) const inline
Return a new BinaryStreamRef with the last N elements removed.
If this BinaryStreamRef is length-tracking and N is greater than 0, then this BinaryStreamRef will no longer length-track.
Definition at line 76 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::BorrowedImpl, llvm::BinaryStreamRefBase< RefType, StreamType >::getLength(), and N.
Referenced by llvm::BinaryStreamRefBase< RefType, StreamType >::keep_front().
drop_front()
template<class RefType , class StreamType > RefType llvm::BinaryStreamRefBase< RefType, StreamType >::drop_front (uint64_t N) const inline
Return a new BinaryStreamRef with the first N elements removed.
If this BinaryStreamRef is length-tracking, then the resulting one will be too.
Definition at line 58 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::BorrowedImpl, llvm::BinaryStreamRefBase< RefType, StreamType >::getLength(), and N.
Referenced by llvm::BinaryStreamRefBase< RefType, StreamType >::drop_symmetric(), llvm::pdb::LinePrinter::formatMsfStreamData(), llvm::BinaryStreamRefBase< RefType, StreamType >::keep_back(), llvm::VarStreamArrayIterator< ValueType, Extractor >::operator+=(), llvm::BinaryStreamRefBase< RefType, StreamType >::slice(), llvm::BinaryStreamWriter::split(), and llvm::BinaryStreamReader::split().
drop_symmetric()
template<class RefType , class StreamType > RefType llvm::BinaryStreamRefBase< RefType, StreamType >::drop_symmetric (uint64_t N) const inline
Return a new BinaryStreamRef with the first and last N elements removed.
Definition at line 109 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::drop_front(), and N.
getEndian()
template<class RefType , class StreamType > llvm::endianness llvm::BinaryStreamRefBase< RefType, StreamType >::getEndian () const inline
Definition at line 46 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::BorrowedImpl.
Referenced by llvm::BinaryStreamReader::readInteger(), and llvm::BinaryStreamWriter::writeInteger().
getLength()
template<class RefType , class StreamType > uint64_t llvm::BinaryStreamRefBase< RefType, StreamType >::getLength () const inline
Definition at line 48 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::BorrowedImpl, llvm::BinaryStreamRefBase< RefType, StreamType >::Length, and llvm::BinaryStreamRefBase< RefType, StreamType >::ViewOffset.
Referenced by llvm::codeview::DebugSubsectionRecordBuilder::calculateSerializedLength(), llvm::BinaryStreamRefBase< RefType, StreamType >::checkOffsetForRead(), llvm::codeview::DebugSubsectionRecordBuilder::commit(), llvm::BinaryStreamRefBase< RefType, StreamType >::drop_back(), llvm::BinaryStreamRefBase< RefType, StreamType >::drop_front(), llvm::VarStreamArray< ValueType, Extractor >::empty(), llvm::FixedStreamArray< T >::FixedStreamArray(), llvm::BinaryStreamReader::getLength(), llvm::BinaryStreamWriter::getLength(), llvm::codeview::DebugSubsectionRecord::getRecordLength(), llvm::BinaryStreamRefBase< RefType, StreamType >::keep_back(), llvm::BinaryStreamRefBase< RefType, StreamType >::keep_front(), llvm::VarStreamArrayIterator< ValueType, Extractor >::operator+=(), llvm::FixedStreamArray< T >::size(), llvm::BinarySubstreamRef::size(), and llvm::VarStreamArrayIterator< ValueType, Extractor >::VarStreamArrayIterator().
keep_back()
template<class RefType , class StreamType > RefType llvm::BinaryStreamRefBase< RefType, StreamType >::keep_back (uint64_t N) const inline
Return a new BinaryStreamRef with only the last N elements remaining.
Definition at line 102 of file BinaryStreamRef.h.
References assert(), llvm::BinaryStreamRefBase< RefType, StreamType >::drop_front(), llvm::BinaryStreamRefBase< RefType, StreamType >::getLength(), and N.
keep_front()
template<class RefType , class StreamType > RefType llvm::BinaryStreamRefBase< RefType, StreamType >::keep_front (uint64_t N) const inline
Return a new BinaryStreamRef with only the first N elements remaining.
Definition at line 96 of file BinaryStreamRef.h.
References assert(), llvm::BinaryStreamRefBase< RefType, StreamType >::drop_back(), llvm::BinaryStreamRefBase< RefType, StreamType >::getLength(), and N.
Referenced by llvm::pdb::LinePrinter::formatMsfStreamData().
operator=() [1/2]
template<class RefType , class StreamType > BinaryStreamRefBase & llvm::BinaryStreamRefBase< RefType, StreamType >::operator= (BinaryStreamRefBase< RefType, StreamType > && Other) protected default
operator=() [2/2]
template<class RefType , class StreamType > BinaryStreamRefBase & llvm::BinaryStreamRefBase< RefType, StreamType >::operator= (const BinaryStreamRefBase< RefType, StreamType > & Other) protected default
slice()
template<class RefType , class StreamType > RefType llvm::BinaryStreamRefBase< RefType, StreamType >::slice (uint64_t Offset, uint64_t Len) const inline
Return a new BinaryStreamRef with the first Offset elements removed, and retaining exactly Len elements.
Definition at line 115 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::drop_front(), and llvm::Offset.
Referenced by llvm::BinaryStreamReader::readStreamRef(), llvm::BinarySubstreamRef::slice(), and llvm::VarStreamArray< ValueType, Extractor >::substream().
valid()
template<class RefType , class StreamType > bool llvm::BinaryStreamRefBase< RefType, StreamType >::valid () const inline
Definition at line 119 of file BinaryStreamRef.h.
References llvm::BinaryStreamRefBase< RefType, StreamType >::BorrowedImpl.
Referenced by llvm::codeview::DebugStringTableSubsectionRef::valid(), and llvm::VarStreamArray< ValueType, Extractor >::valid().
Friends And Related Function Documentation
operator==
template<class RefType , class StreamType > bool operator== (const RefType & LHS, const RefType & RHS) friend
Definition at line 121 of file BinaryStreamRef.h.
Member Data Documentation
BorrowedImpl
template<class RefType , class StreamType > StreamType* llvm::BinaryStreamRefBase< RefType, StreamType >::BorrowedImpl = nullptr protected
Definition at line 141 of file BinaryStreamRef.h.
Referenced by llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase(), llvm::BinaryStreamRefBase< RefType, StreamType >::drop_back(), llvm::BinaryStreamRefBase< RefType, StreamType >::drop_front(), llvm::BinaryStreamRefBase< RefType, StreamType >::getEndian(), llvm::BinaryStreamRefBase< RefType, StreamType >::getLength(), and llvm::BinaryStreamRefBase< RefType, StreamType >::valid().
Length
template<class RefType , class StreamType > std::optional<uint64_t> llvm::BinaryStreamRefBase< RefType, StreamType >::Length protected
Definition at line 143 of file BinaryStreamRef.h.
Referenced by llvm::BinaryStreamRefBase< RefType, StreamType >::BinaryStreamRefBase(), and llvm::BinaryStreamRefBase< RefType, StreamType >::getLength().
SharedImpl
template<class RefType , class StreamType > std::shared_ptr<StreamType> llvm::BinaryStreamRefBase< RefType, StreamType >::SharedImpl protected
Definition at line 140 of file BinaryStreamRef.h.
ViewOffset
template<class RefType , class StreamType > uint64_t llvm::BinaryStreamRefBase< RefType, StreamType >::ViewOffset = 0 protected
Definition at line 142 of file BinaryStreamRef.h.
Referenced by llvm::BinaryStreamRefBase< RefType, StreamType >::getLength().
The documentation for this class was generated from the following file:
include/llvm/Support/BinaryStreamRef.h