LLVM: llvm::PrintCrashIRInstrumentation Class Reference
llvm::PrintCrashIRInstrumentation Class Reference
#include "llvm/Passes/StandardInstrumentations.h"
Public Member Functions
PrintCrashIRInstrumentation ()
~PrintCrashIRInstrumentation ()
void registerCallbacks (PassInstrumentationCallbacks &PIC)
void reportCrashIR ()
Protected Attributes
std::string SavedIR
Detailed Description
Definition at line 548 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
PrintCrashIRInstrumentation()
llvm::PrintCrashIRInstrumentation::PrintCrashIRInstrumentation () inline
Definition at line 550 of file StandardInstrumentations.h.
~PrintCrashIRInstrumentation()
llvm::PrintCrashIRInstrumentation::~PrintCrashIRInstrumentation ()
Definition at line 2387 of file StandardInstrumentations.cpp.
References assert(), PrintOnCrash, and PrintOnCrashPath.
Member Function Documentation
registerCallbacks()
void llvm::PrintCrashIRInstrumentation::registerCallbacks (PassInstrumentationCallbacks & PIC)
Definition at line 2396 of file StandardInstrumentations.cpp.
References llvm::sys::AddSignalHandler(), llvm::forcePrintModuleIR(), llvm::formatv(), llvm::PassInstrumentationCallbacks::getPassNameForClassName(), IR, isInteresting(), OS, PIC, PrintOnCrash, PrintOnCrashPath, llvm::PassInstrumentationCallbacks::registerBeforeNonSkippedPassCallback(), and SavedIR.
Referenced by llvm::StandardInstrumentations::registerCallbacks().
reportCrashIR()
void llvm::PrintCrashIRInstrumentation::reportCrashIR ()
Definition at line 2364 of file StandardInstrumentations.cpp.
References llvm::dbgs(), llvm::errorCodeToError(), PrintOnCrashPath, llvm::report_fatal_error(), and SavedIR.
Member Data Documentation
SavedIR
std::string llvm::PrintCrashIRInstrumentation::SavedIR protected
Definition at line 557 of file StandardInstrumentations.h.
Referenced by registerCallbacks(), and reportCrashIR().
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp