LLVM: llvm::hlsl::FrontendResource Class Reference
llvm::hlsl::FrontendResource Class Reference
#include "llvm/Frontend/HLSL/HLSLResource.h"
Public Member Functions
FrontendResource (MDNode *E)
FrontendResource (GlobalVariable *GV, ResourceKind RK, ElementType ElTy, bool IsROV, uint32_t ResIndex, uint32_t Space)
GlobalVariable * getGlobalVariable ()
StringRef getSourceType ()
ResourceKind getResourceKind ()
ElementType getElementType ()
bool getIsROV ()
uint32_t getResourceIndex ()
uint32_t getSpace ()
MDNode * getMetadata ()
Detailed Description
Definition at line 81 of file HLSLResource.h.
Constructor & Destructor Documentation
FrontendResource() [1/2]
llvm::hlsl::FrontendResource::FrontendResource (MDNode * E) inline
Definition at line 85 of file HLSLResource.h.
References assert().
FrontendResource() [2/2]
FrontendResource::FrontendResource (GlobalVariable * GV, ResourceKind RK, ElementType ElTy, bool IsROV, uint32_t ResIndex, uint32_t Space)
Definition at line 54 of file HLSLResource.cpp.
References B, llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::ValueAsMetadata::get(), and llvm::Value::getContext().
Member Function Documentation
getElementType()
ElementType FrontendResource::getElementType ()
Definition at line 32 of file HLSLResource.cpp.
References llvm::MDNode::getOperand().
getGlobalVariable()
GlobalVariable * FrontendResource::getGlobalVariable ()
Definition at line 21 of file HLSLResource.cpp.
References llvm::MDNode::getOperand().
getIsROV()
bool FrontendResource::getIsROV ()
Definition at line 38 of file HLSLResource.cpp.
References llvm::MDNode::getOperand().
getMetadata()
MDNode * llvm::hlsl::FrontendResource::getMetadata () inline
Definition at line 99 of file HLSLResource.h.
getResourceIndex()
uint32_t FrontendResource::getResourceIndex ()
Definition at line 43 of file HLSLResource.cpp.
References llvm::MDNode::getOperand().
getResourceKind()
ResourceKind FrontendResource::getResourceKind ()
Definition at line 26 of file HLSLResource.cpp.
References llvm::MDNode::getOperand().
getSourceType()
StringRef llvm::hlsl::FrontendResource::getSourceType ()
getSpace()
uint32_t FrontendResource::getSpace ()
Definition at line 48 of file HLSLResource.cpp.
References llvm::MDNode::getOperand().
The documentation for this class was generated from the following files:
include/llvm/Frontend/HLSL/HLSLResource.h
lib/Frontend/HLSL/HLSLResource.cpp