LLVM: llvm::symbolize::SymbolizableObjectFile Class Reference
llvm::symbolize::SymbolizableObjectFile Class Reference
#include "llvm/DebugInfo/Symbolize/SymbolizableObjectFile.h"
Public Member Functions
DILineInfo symbolizeCode (object::SectionedAddress ModuleOffset, DILineInfoSpecifier LineInfoSpecifier, bool UseSymbolTable) const override
DIInliningInfo symbolizeInlinedCode (object::SectionedAddress ModuleOffset, DILineInfoSpecifier LineInfoSpecifier, bool UseSymbolTable) const override
DIGlobal symbolizeData (object::SectionedAddress ModuleOffset) const override
std::vector< DILocal > symbolizeFrame (object::SectionedAddress ModuleOffset) const override
std::vector< object::SectionedAddress > findSymbol (StringRef Symbol, uint64_t Offset) const override
bool isWin32Module () const override
uint64_t getModulePreferredBase () const override
Public Member Functions inherited from llvm::symbolize::SymbolizableModule
virtual ~SymbolizableModule ()=default
virtual DILineInfo symbolizeCode (object::SectionedAddress ModuleOffset, DILineInfoSpecifier LineInfoSpecifier, bool UseSymbolTable) const =0
virtual DIInliningInfo symbolizeInlinedCode (object::SectionedAddress ModuleOffset, DILineInfoSpecifier LineInfoSpecifier, bool UseSymbolTable) const =0
virtual DIGlobal symbolizeData (object::SectionedAddress ModuleOffset) const =0
virtual std::vector< DILocal > symbolizeFrame (object::SectionedAddress ModuleOffset) const =0
virtual std::vector< object::SectionedAddress > findSymbol (StringRef Symbol, uint64_t Offset) const =0
virtual bool isWin32Module () const =0
virtual uint64_t getModulePreferredBase () const =0
Static Public Member Functions
static Expected< std::unique_ptr< SymbolizableObjectFile > > create (const object::ObjectFile *Obj, std::unique_ptr< DIContext > DICtx, bool UntagAddresses)
Detailed Description
Definition at line 31 of file SymbolizableObjectFile.h.
Member Function Documentation
create()
Expected< std::unique_ptr< SymbolizableObjectFile > > SymbolizableObjectFile::create (const object::ObjectFile * Obj, std::unique_ptr< DIContext > DICtx, bool UntagAddresses) static
Definition at line 31 of file SymbolizableObjectFile.cpp.
References assert(), llvm::object::computeSymbolSizes(), E, llvm::object::ObjectFile::getArch(), llvm::object::ObjectFile::getBytesInAddress(), I, llvm::object::Binary::isLittleEndian(), P, llvm::Triple::ppc64, llvm::object::ObjectFile::sections(), llvm::stable_sort(), and llvm::Expected< T >::takeError().
findSymbol()
std::vector< object::SectionedAddress > SymbolizableObjectFile::findSymbol (StringRef Symbol, uint64_t Offset) const override virtual
Implements llvm::symbolize::SymbolizableModule.
Definition at line 355 of file SymbolizableObjectFile.cpp.
References A, Addr, llvm::Offset, and Sym.
getModulePreferredBase()
uint64_t SymbolizableObjectFile::getModulePreferredBase () const override virtual
Implements llvm::symbolize::SymbolizableModule.
Definition at line 228 of file SymbolizableObjectFile.cpp.
isWin32Module()
bool SymbolizableObjectFile::isWin32Module () const override virtual
Implements llvm::symbolize::SymbolizableModule.
Definition at line 223 of file SymbolizableObjectFile.cpp.
References llvm::COFF::IMAGE_FILE_MACHINE_I386.
symbolizeCode()
DILineInfo SymbolizableObjectFile::symbolizeCode (object::SectionedAddress ModuleOffset, DILineInfoSpecifier LineInfoSpecifier, bool UseSymbolTable) const override virtual
Implements llvm::symbolize::SymbolizableModule.
Definition at line 274 of file SymbolizableObjectFile.cpp.
References llvm::object::SectionedAddress::Address, llvm::DILineInfo::BadString, llvm::DILineInfo::FileName, llvm::DILineInfoSpecifier::FNKind, llvm::DILineInfo::FunctionName, llvm::object::SectionedAddress::SectionIndex, Size, llvm::DILineInfo::StartAddress, and llvm::object::SectionedAddress::UndefSection.
symbolizeData()
DIGlobal SymbolizableObjectFile::symbolizeData (object::SectionedAddress ModuleOffset) const override virtual
Implements llvm::symbolize::SymbolizableModule.
Definition at line 329 of file SymbolizableObjectFile.cpp.
References llvm::object::SectionedAddress::Address, llvm::DIGlobal::DeclFile, llvm::DIGlobal::DeclLine, DL, llvm::DIGlobal::Name, llvm::DIGlobal::Size, and llvm::DIGlobal::Start.
symbolizeFrame()
std::vector< DILocal > SymbolizableObjectFile::symbolizeFrame (object::SectionedAddress ModuleOffset) const override virtual
Implements llvm::symbolize::SymbolizableModule.
Definition at line 346 of file SymbolizableObjectFile.cpp.
References llvm::object::SectionedAddress::Address, llvm::object::SectionedAddress::SectionIndex, and llvm::object::SectionedAddress::UndefSection.
symbolizeInlinedCode()
DIInliningInfo SymbolizableObjectFile::symbolizeInlinedCode (object::SectionedAddress ModuleOffset, DILineInfoSpecifier LineInfoSpecifier, bool UseSymbolTable) const override virtual
Implements llvm::symbolize::SymbolizableModule.
Definition at line 298 of file SymbolizableObjectFile.cpp.
References llvm::object::SectionedAddress::Address, llvm::DILineInfo::BadString, llvm::DILineInfo::FileName, llvm::DILineInfoSpecifier::FNKind, llvm::DILineInfo::FunctionName, llvm::sampleprof::InlinedContext, llvm::object::SectionedAddress::SectionIndex, Size, llvm::DILineInfo::StartAddress, and llvm::object::SectionedAddress::UndefSection.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/Symbolize/SymbolizableObjectFile.h
lib/DebugInfo/Symbolize/SymbolizableObjectFile.cpp