LLVM: llvm::DWARFContext::DWARFContextState Class Reference
llvm::DWARFContext::DWARFContextState Class Reference abstract
DWARFContextState This structure contains all member variables for DWARFContext that need to be protected in multi-threaded environments.
#include "llvm/DebugInfo/DWARF/DWARFContext.h"
Public Member Functions
DWARFContextState (DWARFContext &DC)
virtual ~DWARFContextState ()=default
virtual DWARFUnitVector & getNormalUnits ()=0
virtual DWARFUnitVector & getDWOUnits (bool Lazy=false)=0
virtual const DWARFDebugAbbrev * getDebugAbbrevDWO ()=0
virtual const DWARFUnitIndex & getCUIndex ()=0
virtual const DWARFUnitIndex & getTUIndex ()=0
virtual DWARFGdbIndex & getGdbIndex ()=0
virtual const DWARFDebugAbbrev * getDebugAbbrev ()=0
virtual const DWARFDebugLoc * getDebugLoc ()=0
virtual const DWARFDebugAranges * getDebugAranges ()=0
virtual Expected< const DWARFDebugLine::LineTable * > getLineTableForUnit (DWARFUnit *U, function_ref< void(Error)> RecoverableErrHandler)=0
virtual void clearLineTableForUnit (DWARFUnit *U)=0
virtual Expected< const DWARFDebugFrame * > getDebugFrame ()=0
virtual Expected< const DWARFDebugFrame * > getEHFrame ()=0
virtual const DWARFDebugMacro * getDebugMacinfo ()=0
virtual const DWARFDebugMacro * getDebugMacinfoDWO ()=0
virtual const DWARFDebugMacro * getDebugMacro ()=0
virtual const DWARFDebugMacro * getDebugMacroDWO ()=0
virtual const DWARFDebugNames & getDebugNames ()=0
virtual const AppleAcceleratorTable & getAppleNames ()=0
virtual const AppleAcceleratorTable & getAppleTypes ()=0
virtual const AppleAcceleratorTable & getAppleNamespaces ()=0
virtual const AppleAcceleratorTable & getAppleObjC ()=0
virtual std::shared_ptr< DWARFContext > getDWOContext (StringRef AbsolutePath)=0
virtual const DenseMap< uint64_t, DWARFTypeUnit * > & getTypeUnitMap (bool IsDWO)=0
virtual bool isThreadSafe () const =0
std::unique_ptr< DWARFDebugMacro > parseMacroOrMacinfo (MacroSecType SectionType)
Parse a macro[.dwo] or macinfo[.dwo] section.
Protected Types
enum MacroSecType { MacinfoSection , MacinfoDwoSection , MacroSection , MacroDwoSection }
Helper enum to distinguish between macro[.dwo] and macinfo[.dwo] section.
Protected Attributes
DWARFContext & D
Detailed Description
DWARFContextState This structure contains all member variables for DWARFContext that need to be protected in multi-threaded environments.
Threading support can be enabled by setting the ThreadSafe to true when constructing a DWARFContext to allow DWARRContext to be able to be used in a multi-threaded environment, or not enabled to allow for maximum performance in single threaded environments.
Definition at line 57 of file DWARFContext.h.
Member Enumeration Documentation
MacroSecType
enum llvm::DWARFContext::DWARFContextState::MacroSecType protected
Helper enum to distinguish between macro[.dwo] and macinfo[.dwo] section.
Enumerator
MacinfoSection
MacinfoDwoSection
MacroSection
MacroDwoSection
Definition at line 61 of file DWARFContext.h.
Constructor & Destructor Documentation
DWARFContextState()
llvm::DWARFContext::DWARFContextState::DWARFContextState (DWARFContext & DC) inline
Definition at line 70 of file DWARFContext.h.
~DWARFContextState()
virtual llvm::DWARFContext::DWARFContextState::~DWARFContextState () virtual default
Member Function Documentation
clearLineTableForUnit()
virtual void llvm::DWARFContext::DWARFContextState::clearLineTableForUnit (DWARFUnit * U) pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getAppleNames()
virtual const AppleAcceleratorTable & llvm::DWARFContext::DWARFContextState::getAppleNames () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getAppleNamespaces()
virtual const AppleAcceleratorTable & llvm::DWARFContext::DWARFContextState::getAppleNamespaces () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getAppleObjC()
virtual const AppleAcceleratorTable & llvm::DWARFContext::DWARFContextState::getAppleObjC () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getAppleTypes()
virtual const AppleAcceleratorTable & llvm::DWARFContext::DWARFContextState::getAppleTypes () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getCUIndex()
virtual const DWARFUnitIndex & llvm::DWARFContext::DWARFContextState::getCUIndex () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getDebugAbbrev()
virtual const DWARFDebugAbbrev * llvm::DWARFContext::DWARFContextState::getDebugAbbrev () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getDebugAbbrevDWO()
virtual const DWARFDebugAbbrev * llvm::DWARFContext::DWARFContextState::getDebugAbbrevDWO () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getDebugAranges()
virtual const DWARFDebugAranges * llvm::DWARFContext::DWARFContextState::getDebugAranges () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getDebugFrame()
virtual Expected< const DWARFDebugFrame * > llvm::DWARFContext::DWARFContextState::getDebugFrame () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getDebugLoc()
virtual const DWARFDebugLoc * llvm::DWARFContext::DWARFContextState::getDebugLoc () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getDebugMacinfo()
virtual const DWARFDebugMacro * llvm::DWARFContext::DWARFContextState::getDebugMacinfo () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getDebugMacinfoDWO()
virtual const DWARFDebugMacro * llvm::DWARFContext::DWARFContextState::getDebugMacinfoDWO () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getDebugMacro()
virtual const DWARFDebugMacro * llvm::DWARFContext::DWARFContextState::getDebugMacro () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getDebugMacroDWO()
virtual const DWARFDebugMacro * llvm::DWARFContext::DWARFContextState::getDebugMacroDWO () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getDebugNames()
virtual const DWARFDebugNames & llvm::DWARFContext::DWARFContextState::getDebugNames () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getDWOContext()
virtual std::shared_ptr< DWARFContext > llvm::DWARFContext::DWARFContextState::getDWOContext (StringRef AbsolutePath) pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getDWOUnits()
virtual DWARFUnitVector & llvm::DWARFContext::DWARFContextState::getDWOUnits (bool Lazy = false) pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getEHFrame()
virtual Expected< const DWARFDebugFrame * > llvm::DWARFContext::DWARFContextState::getEHFrame () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getGdbIndex()
virtual DWARFGdbIndex & llvm::DWARFContext::DWARFContextState::getGdbIndex () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getLineTableForUnit()
virtual Expected< const DWARFDebugLine::LineTable * > llvm::DWARFContext::DWARFContextState::getLineTableForUnit (DWARFUnit * U, function_ref< void(Error)> RecoverableErrHandler) pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getNormalUnits()
virtual DWARFUnitVector & llvm::DWARFContext::DWARFContextState::getNormalUnits () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getTUIndex()
virtual const DWARFUnitIndex & llvm::DWARFContext::DWARFContextState::getTUIndex () pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
getTypeUnitMap()
virtual const DenseMap< uint64_t, DWARFTypeUnit * > & llvm::DWARFContext::DWARFContextState::getTypeUnitMap (bool IsDWO) pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
isThreadSafe()
virtual bool llvm::DWARFContext::DWARFContextState::isThreadSafe () const pure virtual
Implemented in ThreadUnsafeDWARFContextState, and ThreadSafeState.
parseMacroOrMacinfo()
std::unique_ptr< DWARFDebugMacro > DWARFContext::DWARFContextState::parseMacroOrMacinfo (MacroSecType SectionType)
Parse a macro[.dwo] or macinfo[.dwo] section.
Definition at line 208 of file DWARFContext.cpp.
References llvm::DWARFContext::compile_units(), D, llvm::Data, llvm::DWARFContext::dwo_compile_units(), llvm::DWARFContext::getDWARFObj(), llvm::DWARFObject::getMacinfoDWOSection(), llvm::DWARFObject::getMacinfoSection(), llvm::DWARFObject::getMacroDWOSection(), llvm::DWARFObject::getMacroSection(), llvm::DWARFContext::getRecoverableErrorHandler(), llvm::DWARFContext::getStringDWOExtractor(), llvm::DWARFContext::getStringExtractor(), llvm::DWARFContext::isLittleEndian(), MacinfoDwoSection, MacinfoSection, llvm::Macro, MacroDwoSection, and MacroSection.
Member Data Documentation
D
DWARFContext& llvm::DWARFContext::DWARFContextState::D protected
Definition at line 68 of file DWARFContext.h.
Referenced by parseMacroOrMacinfo().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFContext.h
lib/DebugInfo/DWARF/DWARFContext.cpp