LLVM: llvm::ARMFrameLowering Class Reference
llvm::ARMFrameLowering Class Reference
#include "Target/ARM/ARMFrameLowering.h"
Public Member Functions
ARMFrameLowering (const ARMSubtarget &sti)
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const override
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, MutableArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const override
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
bool keepFramePointer (const MachineFunction &MF) const override
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
bool enableCalleeSaveSkip (const MachineFunction &MF) const override
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
bool isFPReserved (const MachineFunction &MF) const
isFPReserved - Return true if the frame pointer register should be considered a reserved register on the scope of the specified function.
bool hasReservedCallFrame (const MachineFunction &MF) const override
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
bool canSimplifyCallFramePseudos (const MachineFunction &MF) const override
canSimplifyCallFramePseudos - If there is a reserved call frame, the call frame pseudos can be simplified.
StackOffset getFrameIndexReference (const MachineFunction &MF, int FI, Register &FrameReg) const override
getFrameIndexReference - Provide a base+offset reference to an FI slot for debug info.
int ResolveFrameIndexReference (const MachineFunction &MF, int FI, Register &FrameReg, int SPAdj) const
void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const override
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS) const override
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const override
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &MBB) const override
Adjust the prologue to have the function use segmented stacks.
bool enableShrinkWrapping (const MachineFunction &MF) const override
Returns true if the target will correctly handle shrink wrapping.
bool isProfitableForNoCSROpt (const Function &F) const override
Check if the no-CSR optimisation is profitable for the given function.
bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const override
const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const override
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align(1), bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
Align getStackAlign () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
virtual uint64_t getStackThreshold () const
getStackThreshold - Return the maximum stack size
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
Align getTransientStackAlign () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual bool isStackIdSafeForLocalArea (unsigned StackId) const
This method returns whether or not it is safe for an object with the given stack id to be bundled into the local area.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool allocateScavengingFrameIndexesNearIncomingSP (const MachineFunction &MF) const
Control the placement of special register scavenging spill slots when allocating a stack frame.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI, unsigned &MinCSFrameIndex, unsigned &MaxCSFrameIndex) const
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
virtual bool targetHandlesStackFrameRounding () const
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
virtual bool enableShrinkWrapping (const MachineFunction &MF) const
Returns true if the target will correctly handle shrink wrapping.
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual bool enableCalleeSaveSkip (const MachineFunction &MF) const
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
virtual void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const =0
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
virtual void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const =0
virtual void emitZeroCallUsedRegs (BitVector RegsToZero, MachineBasicBlock &MBB) const
emitZeroCallUsedRegs - Zeros out call used registers.
virtual void emitCalleeSavedFrameMovesFullCFA (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI) const
With basic block sections, emit callee saved frame moves for basic blocks that are in a different section.
virtual bool enableCFIFixup (MachineFunction &MF) const
Returns true if we may need to fix the unwind information for the function.
virtual void resetCFIToInitialState (MachineBasicBlock &MBB) const
Emit CFI instructions that recreate the state of the unwind information upon fucntion entry.
virtual void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Replace a StackProbe stub (if any) with the actual probe code inline.
virtual bool stackProbeFunctionModifiesSP () const
Does the stack probe function call return with a modified stack pointer?
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
virtual bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, MutableArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
virtual bool keepFramePointer (const MachineFunction &MF) const
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
virtual bool hasFP (const MachineFunction &MF) const =0
hasFP - Return true if the specified function should have a dedicated frame pointer register.
virtual bool hasReservedCallFrame (const MachineFunction &MF) const
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual StackOffset getFrameIndexReference (const MachineFunction &MF, int FI, Register &FrameReg) const
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
virtual StackOffset getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, Register &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual StackOffset getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
virtual void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS=nullptr) const
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
virtual void processFunctionBeforeFrameIndicesReplaced (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameIndicesReplaced - This method is called immediately before MO_FrameIndex operands are eliminated, but after the frame is finalized.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual bool canUseAsPrologue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a prologue for the target.
virtual bool canUseAsEpilogue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a epilogue for the target.
virtual TargetStackID::Value getStackIDForScalableVectors () const
Returns the StackID that scalable vectors should be associated with.
virtual bool isSupportedStackID (TargetStackID::Value ID) const
virtual bool isProfitableForNoCSROpt (const Function &F) const
Check if the no-CSR optimisation is profitable for the given function.
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual Register getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
virtual DwarfFrameBase getDwarfFrameBase (const MachineFunction &MF) const
Return the frame base information to be encoded in the DWARF subprogram debug info.
Protected Attributes
const ARMSubtarget & STI
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp , StackGrowsDown }
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Detailed Description
Definition at line 21 of file ARMFrameLowering.h.
Constructor & Destructor Documentation
ARMFrameLowering()
ARMFrameLowering::ARMFrameLowering (const ARMSubtarget & sti) explicit
Definition at line 176 of file ARMFrameLowering.cpp.
Member Function Documentation
adjustForSegmentedStacks()
void ARMFrameLowering::adjustForSegmentedStacks (MachineFunction & MF, MachineBasicBlock & PrologueMBB) const override virtual
Adjust the prologue to have the function use segmented stacks.
This works by adding a check even before the "normal" function prologue.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2975 of file ARMFrameLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineInstrBuilder::addConstantPoolIndex(), llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::ARMCC::AL, alignToARMConstant(), assert(), B, llvm::BuildMI(), llvm::MCCFIInstruction::cfiDefCfaOffset(), llvm::condCodeOp(), Context, llvm::ARMConstantPoolSymbol::Create(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MCCFIInstruction::createOffset(), llvm::ARMFunctionInfo::createPICLabelUId(), llvm::MCCFIInstruction::createSameValue(), llvm::RegState::Define, DL, llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::SmallVectorBase< Size_T >::empty(), llvm::MachineBasicBlock::end(), llvm::SmallPtrSetImpl< PtrType >::erase(), llvm::ARMFunctionInfo::getArgumentStackSize(), llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstantPoolIndex(), llvm::MachineModuleInfo::getContext(), llvm::Function::getContext(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineFunction::getMMI(), llvm::ARMSubtarget::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineFunction::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::MachineBasicBlock::isSuccessor(), llvm::Function::isVarArg(), kSplitStackAvailable, llvm::MachineBasicBlock::liveins(), llvm::ARMCC::LS, MBB, MBBI, MRI, llvm::MachineFrameInfo::needsSplitStackProlog(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::MachineBasicBlock::predecessors(), llvm::predOps(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineBasicBlock::ReplaceUsesOfBlockWith(), llvm::report_fatal_error(), llvm::MachineBasicBlock::sortUniqueLiveIns(), STI, TII, llvm::MCAsmInfo::usesWindowsCFI(), and llvm::MachineFunction::verify().
assignCalleeSavedSpillSlots()
bool ARMFrameLowering::assignCalleeSavedSpillSlots (MachineFunction & MF, const TargetRegisterInfo * TRI, std::vector< CalleeSavedInfo > & CSI) const override virtual
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2823 of file ARMFrameLowering.cpp.
References llvm::find_if(), llvm::MachineFunction::getInfo(), llvm::ARMFunctionInfo::isCmseNSEntryFunction(), llvm::ARMFunctionInfo::shouldSignReturnAddress(), and STI.
canSimplifyCallFramePseudos()
bool ARMFrameLowering::canSimplifyCallFramePseudos (const MachineFunction & MF) const override virtual
canSimplifyCallFramePseudos - If there is a reserved call frame, the call frame pseudos can be simplified.
Unlike most targets, having a FP is not sufficient here since we still may reference some objects via SP even when FP is available in Thumb2 mode.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 244 of file ARMFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), hasReservedCallFrame(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by determineCalleeSaves().
determineCalleeSaves()
void ARMFrameLowering::determineCalleeSaves (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS) const override virtual
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
The default implementation checks populates the SavedRegs bitset with all registers which are modified in the function, targets may override this function to save additional registers. This method also sets up the register scavenger ensuring there is a free register or a frameindex available. This method should not be called by any passes outside of PEI, because it may change state passed in by MF and RS. The preferred interface outside PEI is getCalleeSaves.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2262 of file ARMFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), assert(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), canSimplifyCallFramePseudos(), canSpillOnFrameIndexAccess(), checkNumAlignedDPRCS2Regs(), contains(), llvm::dbgs(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::TargetOptions::DisableFramePointerElim(), llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), EstimateFunctionSizeInBytes(), estimateRSStackSizeLimit(), llvm::find(), FramePtr, llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::ARMFunctionInfo::getArgRegsSaveSize(), llvm::ARMBaseRegisterInfo::getBaseRegister(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), getMaxFPOffset(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::ARMFunctionInfo::getReturnRegsCount(), llvm::TargetFrameLowering::getStackAlign(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::ARMBaseRegisterInfo::hasBasePointer(), hasFP(), llvm::ARMFunctionInfo::hasStackFrame(), I, llvm::isARMLowRegister(), llvm::ARMFunctionInfo::isCmseNSEntryFunction(), llvm::MachineRegisterInfo::isLiveIn(), llvm::MachineFrameInfo::isReturnAddressTaken(), llvm::ARMSubtarget::isTargetWindows(), llvm::ARMFunctionInfo::isThumb1OnlyFunction(), llvm::ARMFunctionInfo::isThumb2Function(), llvm::ARMFunctionInfo::isThumbFunction(), LLVM_DEBUG, MRI, llvm::TargetMachine::Options, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::printReg(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), requiresAAPCSFrameRecord(), llvm::BitVector::set(), llvm::ARMFunctionInfo::setHasStackFrame(), llvm::ARMFunctionInfo::setLRIsSpilled(), llvm::ARMFunctionInfo::shouldSignReturnAddress(), Size, llvm::ARMSubtarget::splitFramePushPop(), STI, llvm::BitVector::test(), TII, TRI, llvm::ARMSubtarget::useMovt(), llvm::Align::value(), and WindowsRequiresStackProbe().
emitEpilogue()
void ARMFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Reimplemented in llvm::Thumb1FrameLowering.
Definition at line 1272 of file ARMFrameLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addReg(), llvm::ARMCC::AL, assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::condCodeOp(), llvm::emitARMRegPlusImmediate(), emitSPUpdate(), llvm::emitT2RegPlusImmediate(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::FrameDestroy, FramePtr, llvm::ARMFunctionInfo::getArgRegsSaveSize(), getArgumentStackToRestore(), llvm::Function::getCallingConv(), llvm::ARMFunctionInfo::getDPRCalleeSavedAreaSize(), llvm::ARMFunctionInfo::getDPRCalleeSavedGapSize(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::ARMFunctionInfo::getFPCXTSaveAreaSize(), llvm::MachineFunction::getFrameInfo(), llvm::ARMFunctionInfo::getFramePtrSpillOffset(), llvm::MachineFunction::getFunction(), llvm::ARMFunctionInfo::getGPRCalleeSavedArea1Size(), llvm::ARMFunctionInfo::getGPRCalleeSavedArea2Size(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::ARMSubtarget::getInstrInfo(), llvm::MachineFrameInfo::getPristineRegs(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::CallingConv::GHC, llvm::ARMFunctionInfo::hasStackFrame(), llvm::MachineFunction::hasWinCFI(), initMBBRange(), insertSEHRange(), llvm::ARMFunctionInfo::isCmseNSEntryFunction(), llvm::ARMFunctionInfo::isThumb1OnlyFunction(), llvm::ARMFunctionInfo::isThumbFunction(), MBB, MBBI, llvm::predOps(), llvm::MachineInstrBuilder::setMIFlag(), llvm::ARMFunctionInfo::shouldRestoreSPFromFP(), llvm::ARMFunctionInfo::shouldSignReturnAddress(), llvm::ARMSubtarget::splitFramePointerPush(), STI, llvm::BitVector::test(), TII, and llvm::tryFoldSPUpdateIntoPushPop().
emitPrologue()
void ARMFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Reimplemented in llvm::Thumb1FrameLowering.
Definition at line 731 of file ARMFrameLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::ARMCC::AL, assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MCCFIInstruction::cfiDefCfa(), llvm::condCodeOp(), Context, llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCCFIInstruction::createOffset(), emitAligningInstructions(), emitRegPlusImmediate(), emitSPUpdate(), llvm::MachineBasicBlock::end(), End, FramePtr, llvm::MachineInstr::FrameSetup, llvm::ARMFunctionInfo::getArgRegsSaveSize(), llvm::ARMBaseRegisterInfo::getBaseRegister(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFrameInfo(), llvm::ARMSubtarget::getFrameLowering(), llvm::ARMFunctionInfo::getFramePtrSpillOffset(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::ARMSubtarget::getInstrInfo(), llvm::MachineFrameInfo::getMaxAlign(), getMaxFPOffset(), llvm::MachineFunction::getMMI(), llvm::ARMFunctionInfo::getNumAlignedDPRCS2Regs(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getOffsetAdjustment(), llvm::ARMSubtarget::getRegisterInfo(), llvm::TargetFrameLowering::getStackAlign(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getTarget(), llvm::CallingConv::GHC, llvm::ARMBaseRegisterInfo::hasBasePointer(), hasFP(), llvm::ARMFunctionInfo::hasStackFrame(), llvm::MachineFrameInfo::hasVarSizedObjects(), I, llvm::RegState::Implicit, llvm::MachineBasicBlock::insertAfter(), insertSEHRange(), llvm::ARMSubtarget::isTargetELF(), llvm::ARMSubtarget::isTargetWindows(), llvm::ARMFunctionInfo::isThumb1OnlyFunction(), llvm::ARMFunctionInfo::isThumbFunction(), llvm::CodeModel::Kernel, llvm::RegState::Kill, llvm::CodeModel::Large, llvm_unreachable, MBB, MBBI, llvm::CodeModel::Medium, MRI, needsWinCFI(), llvm::Offset, llvm::predOps(), llvm::ARMFunctionInfo::setDPRCalleeSavedAreaOffset(), llvm::ARMFunctionInfo::setDPRCalleeSavedAreaSize(), llvm::ARMFunctionInfo::setDPRCalleeSavedGapSize(), llvm::ARMFunctionInfo::setFPCXTSaveAreaSize(), llvm::ARMFunctionInfo::setFramePtrSpillOffset(), llvm::ARMFunctionInfo::setGPRCalleeSavedArea1Offset(), llvm::ARMFunctionInfo::setGPRCalleeSavedArea1Size(), llvm::ARMFunctionInfo::setGPRCalleeSavedArea2Offset(), llvm::ARMFunctionInfo::setGPRCalleeSavedArea2Size(), llvm::MachineFunction::setHasWinCFI(), llvm::MachineInstrBuilder::setMIFlag(), llvm::MachineInstrBuilder::setMIFlags(), llvm::MachineFrameInfo::setOffsetAdjustment(), llvm::ARMFunctionInfo::setShouldRestoreSPFromFP(), llvm::ARMFunctionInfo::shouldSignReturnAddress(), sizeOfSPAdjustment(), skipAlignedDPRCS2Spills(), llvm::CodeModel::Small, llvm::ARMSubtarget::splitFramePointerPush(), llvm::ARMSubtarget::splitFramePushPop(), STI, TII, llvm::CodeModel::Tiny, TM, llvm::tryFoldSPUpdateIntoPushPop(), llvm::Align::value(), and WindowsRequiresStackProbe().
enableCalleeSaveSkip()
bool ARMFrameLowering::enableCalleeSaveSkip (const MachineFunction & MF) const override virtual
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 189 of file ARMFrameLowering.cpp.
References assert(), llvm::MachineFunction::getFunction(), and llvm::Function::hasFnAttribute().
enableShrinkWrapping()
bool ARMFrameLowering::enableShrinkWrapping (const MachineFunction & MF) const override virtual
Returns true if the target will correctly handle shrink wrapping.
Reimplemented from llvm::TargetFrameLowering.
Reimplemented in llvm::Thumb1FrameLowering.
Definition at line 2215 of file ARMFrameLowering.cpp.
References llvm::MachineFunction::getInfo(), llvm::ARMFunctionInfo::isCmseNSEntryFunction(), llvm::ARMFunctionInfo::shouldSignReturnAddress(), and STI.
getCalleeSavedSpillSlots()
const TargetFrameLowering::SpillSlot * ARMFrameLowering::getCalleeSavedSpillSlots (unsigned & NumEntries) const override virtual
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
Each entry in this array contains a <register,offset> pair, indicating the fixed offset from the incoming stack pointer that each register should be spilled at. If a register is not listed here, the code generator is allowed to spill it anywhere it chooses.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2858 of file ARMFrameLowering.cpp.
getCalleeSaves()
void ARMFrameLowering::getCalleeSaves (const MachineFunction & MF, BitVector & SavedRegs) const override virtual
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2811 of file ARMFrameLowering.cpp.
References llvm::TargetFrameLowering::getCalleeSaves(), llvm::MachineFunction::getInfo(), llvm::ARMFunctionInfo::getPreservesR0(), and llvm::BitVector::set().
getFrameIndexReference()
StackOffset ARMFrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, Register & FrameReg) const override virtual
getFrameIndexReference - Provide a base+offset reference to an FI slot for debug info.
It's the same as what we use for resolving the code-gen references for now. FIXME: This can go wrong when references are SP-relative and simple call frames aren't used.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1433 of file ARMFrameLowering.cpp.
References llvm::StackOffset::getFixed(), and ResolveFrameIndexReference().
hasFP()
bool ARMFrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register.
This is true if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 202 of file ARMFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::TargetRegisterInfo::hasStackRealignment(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFrameInfo::isFrameAddressTaken(), and llvm::TargetMachine::Options.
Referenced by determineCalleeSaves(), llvm::Thumb1FrameLowering::emitEpilogue(), emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), isFPReserved(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), ResolveFrameIndexReference(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), and llvm::Thumb1FrameLowering::spillCalleeSavedRegisters().
hasReservedCallFrame()
bool ARMFrameLowering::hasReservedCallFrame (const MachineFunction & MF) const override virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Reimplemented in llvm::Thumb1FrameLowering.
Definition at line 226 of file ARMFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getMaxCallFrameSize(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by llvm::ARMBaseRegisterInfo::canRealignStack(), canSimplifyCallFramePseudos(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), and ResolveFrameIndexReference().
isFPReserved()
bool ARMFrameLowering::isFPReserved (const MachineFunction & MF) const
isFPReserved - Return true if the frame pointer register should be considered a reserved register on the scope of the specified function.
Definition at line 217 of file ARMFrameLowering.cpp.
References llvm::MachineFunction::getSubtarget(), and hasFP().
isProfitableForNoCSROpt()
bool llvm::ARMFrameLowering::isProfitableForNoCSROpt (const Function & F) const inline override virtual
Check if the no-CSR optimisation is profitable for the given function.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 71 of file ARMFrameLowering.h.
keepFramePointer()
bool ARMFrameLowering::keepFramePointer (const MachineFunction & MF) const override virtual
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
Reimplemented from llvm::TargetFrameLowering.
Definition at line 180 of file ARMFrameLowering.cpp.
References llvm::MachineFunction::getSubtarget().
processFunctionBeforeFrameFinalized()
void ARMFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS = nullptr) const override virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2784 of file ARMFrameLowering.cpp.
References llvm::all_of(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), Info, llvm::MachineFrameInfo::isCalleeSavedInfoValid(), MBB, llvm::TargetFrameLowering::processFunctionBeforeFrameFinalized(), and llvm::MachineBasicBlock::terminators().
ResolveFrameIndexReference()
int ARMFrameLowering::ResolveFrameIndexReference (const MachineFunction & MF, int FI, Register & FrameReg, int SPAdj) const
Definition at line 1439 of file ARMFrameLowering.cpp.
References assert(), llvm::ARMBaseRegisterInfo::getBaseRegister(), llvm::MachineFunction::getFrameInfo(), llvm::ARMFunctionInfo::getFramePtrSpillOffset(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::ARMBaseRegisterInfo::hasBasePointer(), hasFP(), hasReservedCallFrame(), llvm::ARMFunctionInfo::hasStackFrame(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::ARMFunctionInfo::isThumb2Function(), llvm::ARMFunctionInfo::isThumbFunction(), and llvm::Offset.
Referenced by llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), llvm::ThumbRegisterInfo::eliminateFrameIndex(), and getFrameIndexReference().
restoreCalleeSavedRegisters()
bool ARMFrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, MutableArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo * TRI) const override virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
If it returns true, and any of the registers in CSI is not restored, it sets the corresponding Restored flag in CSI to false. Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Reimplemented in llvm::Thumb1FrameLowering.
Definition at line 2029 of file ARMFrameLowering.cpp.
References emitAlignedDPRCS2Restores(), llvm::ArrayRef< T >::empty(), llvm::ARMFunctionInfo::getArgRegsSaveSize(), llvm::MachineFunction::getInfo(), llvm::ARMFunctionInfo::getNumAlignedDPRCS2Regs(), llvm::MachineBasicBlock::getParent(), llvm::isARMArea1Register(), llvm::isARMArea2Register(), llvm::isARMArea3Register(), llvm::isSplitFPArea1Register(), llvm::isSplitFPArea2Register(), llvm::ARMFunctionInfo::isThumbFunction(), MBB, MI, llvm::ARMSubtarget::splitFramePointerPush(), STI, and TRI.
spillCalleeSavedRegisters()
bool ARMFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Reimplemented in llvm::Thumb1FrameLowering.
Definition at line 1975 of file ARMFrameLowering.cpp.
References llvm::MachineInstrBuilder::add(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::ARMCC::AL, llvm::any_of(), llvm::BuildMI(), llvm::CallingConv::C, emitAlignedDPRCS2Spills(), llvm::ArrayRef< T >::empty(), llvm::MachineInstr::FrameSetup, llvm::MachineFunction::getInfo(), llvm::ARMSubtarget::getInstrInfo(), llvm::ARMFunctionInfo::getNumAlignedDPRCS2Regs(), llvm::MachineBasicBlock::getParent(), llvm::isARMArea1Register(), llvm::isARMArea2Register(), llvm::isARMArea3Register(), llvm::isSplitFPArea1Register(), llvm::isSplitFPArea2Register(), llvm::ARMFunctionInfo::isThumbFunction(), MBB, MI, llvm::predOps(), llvm::MachineInstrBuilder::setMIFlags(), llvm::ARMFunctionInfo::shouldSignReturnAddress(), llvm::ARMSubtarget::splitFramePointerPush(), STI, and TRI.
Member Data Documentation
STI
const ARMSubtarget& llvm::ARMFrameLowering::STI protected
Definition at line 23 of file ARMFrameLowering.h.
Referenced by adjustForSegmentedStacks(), assignCalleeSavedSpillSlots(), determineCalleeSaves(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), enableShrinkWrapping(), restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), spillCalleeSavedRegisters(), and llvm::Thumb1FrameLowering::spillCalleeSavedRegisters().
The documentation for this class was generated from the following files:
lib/Target/ARM/ARMFrameLowering.h
lib/Target/ARM/ARMFrameLowering.cpp