LLVM: AliasScopeTracker Class Reference
AliasScopeTracker Class Reference
Public Member Functions
void analyse (Instruction *I)
bool isNoAliasScopeDeclDead (Instruction *Inst)
Detailed Description
Definition at line 4562 of file InstructionCombining.cpp.
Member Function Documentation
analyse()
void AliasScopeTracker::analyse (Instruction * I) inline
Definition at line 4567 of file InstructionCombining.cpp.
References I.
Referenced by llvm::InstCombinerImpl::prepareWorklist().
isNoAliasScopeDeclDead()
bool AliasScopeTracker::isNoAliasScopeDeclDead (Instruction * Inst) inline
Definition at line 4585 of file InstructionCombining.cpp.
References assert(), llvm::SmallPtrSetImpl< PtrType >::contains(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::NoAliasScopeDeclInst::getScopeList(), and llvm::Value::use_empty().
Referenced by llvm::InstCombinerImpl::prepareWorklist().
The documentation for this class was generated from the following file:
lib/Transforms/InstCombine/InstructionCombining.cpp