LLVM: llvm::DWARFUnitVector Class Reference
llvm::DWARFUnitVector Class Reference final
Describe a collection of units.
#include "llvm/DebugInfo/DWARF/DWARFUnit.h"
Public Types
using UnitVector = SmallVectorImpl< std::unique_ptr< DWARFUnit > >
using iterator = typename UnitVector::iterator
using iterator_range = llvm::iterator_range< typename UnitVector::iterator >
using compile_unit_range = decltype(make_filter_range(std::declval< iterator_range >(), isCompileUnit))
Public Types inherited from llvm::SmallVectorImpl< T >
using iterator = typename SuperClass::iterator
using const_iterator = typename SuperClass::const_iterator
using reference = typename SuperClass::reference
using size_type = typename SuperClass::size_type
Public Types inherited from llvm::SmallVectorTemplateCommon< T, typename >
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using reverse_iterator = std::reverse_iterator< iterator >
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Public Member Functions
DWARFUnit * getUnitForOffset (uint64_t Offset) const
DWARFUnit * getUnitForIndexEntry (const DWARFUnitIndex::Entry &E)
void addUnitsForSection (DWARFContext &C, const DWARFSection &Section, DWARFSectionKind SectionKind)
Read units from a .debug_info or .debug_types section.
void addUnitsForDWOSection (DWARFContext &C, const DWARFSection &DWOSection, DWARFSectionKind SectionKind, bool Lazy=false)
Read units from a .debug_info.dwo or .debug_types.dwo section.
DWARFUnit * addUnit (std::unique_ptr< DWARFUnit > Unit)
Add an existing DWARFUnit to this UnitVector.
unsigned getNumUnits () const
Returns number of all units held by this instance.
unsigned getNumInfoUnits () const
Returns number of units from all .debug_info[.dwo] sections.
unsigned getNumTypesUnits () const
Returns number of units from all .debug_types[.dwo] sections.
void finishedInfoUnits ()
Indicate that parsing .debug_info[.dwo] is done, and remaining units will be from .debug_types[.dwo].
Public Member Functions inherited from llvm::SmallVector< std::unique_ptr< DWARFUnit >, 1 >
SmallVector ()
SmallVector (size_t Size)
SmallVector (size_t Size, const std::unique_ptr< DWARFUnit > &Value)
SmallVector (ItTy S, ItTy E)
SmallVector (const iterator_range< RangeTy > &R)
SmallVector (std::initializer_list< std::unique_ptr< DWARFUnit > > IL)
SmallVector (ArrayRef< U > A)
SmallVector (const SmallVector &RHS)
SmallVector (SmallVector &&RHS)
SmallVector (SmallVectorImpl< std::unique_ptr< DWARFUnit > > &&RHS)
~SmallVector ()
SmallVector & operator= (const SmallVector &RHS)
SmallVector & operator= (SmallVector &&RHS)
SmallVector & operator= (SmallVectorImpl< std::unique_ptr< DWARFUnit > > &&RHS)
SmallVector & operator= (std::initializer_list< std::unique_ptr< DWARFUnit > > IL)
Public Member Functions inherited from llvm::SmallVectorImpl< T >
SmallVectorImpl (const SmallVectorImpl &)=delete
void clear ()
void resize (size_type N)
void resize_for_overwrite (size_type N)
Like resize, but T is POD, the new values won't be initialized.
void truncate (size_type N)
Like resize, but requires that N is less than size().
void resize (size_type N, ValueParamT NV)
void reserve (size_type N)
void pop_back_n (size_type NumItems)
T pop_back_val ()
void swap (SmallVectorImpl &RHS)
template<typename ItTy , typename = EnableIfConvertibleToInputIterator<ItTy>>
void append (ItTy in_start, ItTy in_end)
Add the specified range to the end of the SmallVector.
void append (size_type NumInputs, ValueParamT Elt)
Append NumInputs copies of Elt to the end.
void append (std::initializer_list< T > IL)
void append (const SmallVectorImpl &RHS)
void assign (size_type NumElts, ValueParamT Elt)
template<typename ItTy , typename = EnableIfConvertibleToInputIterator<ItTy>>
void assign (ItTy in_start, ItTy in_end)
void assign (std::initializer_list< T > IL)
void assign (const SmallVectorImpl &RHS)
iterator erase (const_iterator CI)
iterator erase (const_iterator CS, const_iterator CE)
iterator insert (iterator I, T &&Elt)
iterator insert (iterator I, const T &Elt)
iterator insert (iterator I, size_type NumToInsert, ValueParamT Elt)
template<typename ItTy , typename = EnableIfConvertibleToInputIterator<ItTy>>
iterator insert (iterator I, ItTy From, ItTy To)
void insert (iterator I, std::initializer_list< T > IL)
template<typename... ArgTypes>
reference emplace_back (ArgTypes &&... Args)
SmallVectorImpl & operator= (const SmallVectorImpl &RHS)
SmallVectorImpl & operator= (SmallVectorImpl &&RHS)
bool operator== (const SmallVectorImpl &RHS) const
bool operator!= (const SmallVectorImpl &RHS) const
bool operator< (const SmallVectorImpl &RHS) const
bool operator> (const SmallVectorImpl &RHS) const
bool operator<= (const SmallVectorImpl &RHS) const
bool operator>= (const SmallVectorImpl &RHS) const
Public Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
void push_back (const T &Elt)
void push_back (T &&Elt)
void pop_back ()
Public Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
size_t size () const
size_t capacity () const
bool empty () const
Additional Inherited Members
Protected Types inherited from llvm::SmallVectorImpl< T >
using ValueParamT = typename SuperClass::ValueParamT
Protected Types inherited from llvm::SmallVectorTemplateBase< T, bool >
using ValueParamT = const T &
Protected Member Functions inherited from llvm::SmallVectorImpl< T >
SmallVectorImpl (unsigned N)
void assignRemote (SmallVectorImpl &&RHS)
~SmallVectorImpl ()
Protected Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
T * mallocForGrow (size_t MinSize, size_t &NewCapacity)
Create a new allocation big enough for MinSize and pass back its size in NewCapacity.
void moveElementsForGrow (T *NewElts)
Move existing elements over to the new allocation NewElts, the middle section of grow().
void takeAllocationForGrow (T *NewElts, size_t NewCapacity)
Transfer ownership of the allocation, finishing up grow().
const T * reserveForParamAndGetAddress (const T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
T * reserveForParamAndGetAddress (T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
void growAndAssign (size_t NumElts, const T &Elt)
template<typename... ArgTypes>
T & growAndEmplaceBack (ArgTypes &&... Args)
Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
void * getFirstEl () const
Find the address of the first element.
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSize, size_t TSize)
bool isSmall () const
Return true if this is a smallvector which has not had dynamic memory allocated for it.
void resetToSmall ()
Put this vector in a state of being small.
bool isReferenceToRange (const void *V, const void *First, const void *Last) const
Return true if V is an internal reference to the given range.
bool isReferenceToStorage (const void *V) const
Return true if V is an internal reference to this vector.
bool isRangeInStorage (const void *First, const void *Last) const
Return true if First and Last form a valid (possibly empty) range in this vector's storage.
bool isSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Return true unless Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Check whether Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToAdd (const void *Elt, size_t N=1)
Check whether Elt will be invalidated by increasing the size of the vector by N.
void assertSafeToReferenceAfterClear (const T *From, const T *To)
Check whether any part of the range will be invalidated by clearing.
template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToReferenceAfterClear (ItTy, ItTy)
void assertSafeToAddRange (const T *From, const T *To)
Check whether any part of the range will be invalidated by growing.
template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToAddRange (ItTy, ItTy)
Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void * mallocForGrow (void *FirstEl, size_t MinSize, size_t TSize, size_t &NewCapacity)
This is a helper for grow() that's out of line to reduce code duplication.
void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
void * replaceAllocation (void *NewElts, size_t TSize, size_t NewCapacity, size_t VSize=0)
If vector was first created with capacity 0, getFirstEl() points to the memory right after, an area unallocated.
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
void set_allocation_range (void *Begin, size_t N)
Set the array data pointer to Begin and capacity to N.
Static Protected Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
static void destroy_range (T *S, T *E)
template<typename It1 , typename It2 >
static void uninitialized_move (It1 I, It1 E, It2 Dest)
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
static T && forward_value_param (T &&V)
static const T & forward_value_param (const T &V)
Static Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
template<class U >
static const T * reserveForParamAndGetAddressImpl (U *This, const T &Elt, size_t N)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Static Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
Protected Attributes inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
void * BeginX
SmallVectorSizeType< T > Size
SmallVectorSizeType< T > Capacity
Static Protected Attributes inherited from llvm::SmallVectorTemplateBase< T, bool >
static constexpr bool TakesParamByValue = false
Detailed Description
Describe a collection of units.
Intended to hold all units either from .debug_info and .debug_types, or from .debug_info.dwo and .debug_types.dwo.
Definition at line 128 of file DWARFUnit.h.
Member Typedef Documentation
compile_unit_range
using llvm::DWARFUnitVector::compile_unit_range = decltype(make_filter_range(std::declval<iterator_range>(), isCompileUnit))
Definition at line 140 of file DWARFUnit.h.
iterator
using llvm::DWARFUnitVector::iterator = typename UnitVector::iterator
Definition at line 137 of file DWARFUnit.h.
iterator_range
using llvm::DWARFUnitVector::iterator_range = llvm::iterator_range<typename UnitVector::iterator>
Definition at line 138 of file DWARFUnit.h.
UnitVector
using llvm::DWARFUnitVector::UnitVector = SmallVectorImpl<std::unique_ptr<DWARFUnit> >
Definition at line 136 of file DWARFUnit.h.
Member Function Documentation
addUnit()
DWARFUnit * DWARFUnitVector::addUnit (std::unique_ptr< DWARFUnit > Unit)
Add an existing DWARFUnit to this UnitVector.
This is used by the DWARF verifier to process unit separately.
Definition at line 139 of file DWARFUnit.cpp.
References I, llvm::SmallVectorImpl< T >::insert(), LHS, RHS, and llvm::upper_bound().
addUnitsForDWOSection()
void DWARFUnitVector::addUnitsForDWOSection (DWARFContext & C, const DWARFSection & DWOSection, DWARFSectionKind SectionKind, bool Lazy = false)
Read units from a .debug_info.dwo or .debug_types.dwo section.
Calls made before finishedInfoUnits() are assumed to be for .debug_info.dwo sections, calls after finishedInfoUnits() are for .debug_types.dwo sections. Caller must not mix calls to addUnitsForSection and addUnitsForDWOSection.
Definition at line 53 of file DWARFUnit.cpp.
References llvm::CallingConv::C, and D.
Referenced by ThreadUnsafeDWARFContextState::getDWOUnits().
addUnitsForSection()
void DWARFUnitVector::addUnitsForSection (DWARFContext & C, const DWARFSection & Section, DWARFSectionKind SectionKind)
Read units from a .debug_info or .debug_types section.
Calls made before finishedInfoUnits() are assumed to be for .debug_info sections, calls after finishedInfoUnits() are for .debug_types sections. Caller must not mix calls to addUnitsForSection and addUnitsForDWOSection.
Definition at line 42 of file DWARFUnit.cpp.
References llvm::CallingConv::C, and D.
Referenced by ThreadUnsafeDWARFContextState::getNormalUnits().
finishedInfoUnits()
void llvm::DWARFUnitVector::finishedInfoUnits () inline
Indicate that parsing .debug_info[.dwo] is done, and remaining units will be from .debug_types[.dwo].
Definition at line 174 of file DWARFUnit.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
Referenced by ThreadUnsafeDWARFContextState::getDWOUnits(), and ThreadUnsafeDWARFContextState::getNormalUnits().
getNumInfoUnits()
unsigned llvm::DWARFUnitVector::getNumInfoUnits () const inline
Returns number of units from all .debug_info[.dwo] sections.
Definition at line 167 of file DWARFUnit.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
Referenced by llvm::DWARFContext::dwo_info_section_units(), llvm::DWARFContext::dwo_types_section_units(), getUnitForIndexEntry(), getUnitForOffset(), llvm::DWARFContext::info_section_units(), and llvm::DWARFContext::types_section_units().
getNumTypesUnits()
unsigned llvm::DWARFUnitVector::getNumTypesUnits () const inline
Returns number of units from all .debug_types[.dwo] sections.
Definition at line 171 of file DWARFUnit.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
getNumUnits()
unsigned llvm::DWARFUnitVector::getNumUnits () const inline
Returns number of all units held by this instance.
Definition at line 165 of file DWARFUnit.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
getUnitForIndexEntry()
DWARFUnit * DWARFUnitVector::getUnitForIndexEntry (const DWARFUnitIndex::Entry & E)
Definition at line 161 of file DWARFUnit.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), E, llvm::SmallVectorTemplateCommon< T, typename >::end(), getNumInfoUnits(), llvm::SmallVectorImpl< T >::insert(), LHS, llvm::Offset, and RHS.
Referenced by llvm::DWARFContext::getDWOCompileUnitForHash(), and llvm::DWARFContext::getTypeUnitForHash().
getUnitForOffset()
DWARFUnit * DWARFUnitVector::getUnitForOffset (uint64_t Offset) const
Definition at line 148 of file DWARFUnit.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), getNumInfoUnits(), LHS, llvm::Offset, and RHS.
Referenced by llvm::DWARFDie::getAttributeValueAsReferencedDie().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/DWARF/DWARFUnit.h
lib/DebugInfo/DWARF/DWARFUnit.cpp