LLVM: llvm::orc::JITCompileCallbackManager Class Reference
llvm::orc::JITCompileCallbackManager Class Reference
Target-independent base class for compile callback management.
#include "llvm/ExecutionEngine/Orc/IndirectionUtils.h"
Public Types
using CompileFunction = std::function< ExecutorAddr()>
Public Member Functions
virtual ~JITCompileCallbackManager ()=default
Expected< ExecutorAddr > getCompileCallback (CompileFunction Compile)
Reserve a compile callback.
ExecutorAddr executeCompileCallback (ExecutorAddr TrampolineAddr)
Execute the callback for the given trampoline id.
Protected Member Functions
JITCompileCallbackManager (std::unique_ptr< TrampolinePool > TP, ExecutionSession &ES, ExecutorAddr ErrorHandlerAddress)
Construct a JITCompileCallbackManager.
void setTrampolinePool (std::unique_ptr< TrampolinePool > TP)
Detailed Description
Target-independent base class for compile callback management.
Definition at line 203 of file IndirectionUtils.h.
Member Typedef Documentation
CompileFunction
using llvm::orc::JITCompileCallbackManager::CompileFunction = std::function<ExecutorAddr()>
Definition at line 205 of file IndirectionUtils.h.
Constructor & Destructor Documentation
~JITCompileCallbackManager()
virtual llvm::orc::JITCompileCallbackManager::~JITCompileCallbackManager () virtual default
JITCompileCallbackManager()
llvm::orc::JITCompileCallbackManager::JITCompileCallbackManager (std::unique_ptr< TrampolinePool > TP, ExecutionSession & ES, ExecutorAddr ErrorHandlerAddress) inline protected
Construct a JITCompileCallbackManager.
Definition at line 218 of file IndirectionUtils.h.
Member Function Documentation
executeCompileCallback()
ExecutorAddr llvm::orc::JITCompileCallbackManager::executeCompileCallback (ExecutorAddr TrampolineAddr)
Execute the callback for the given trampoline id.
Called by the JIT to compile functions on demand.
Definition at line 82 of file IndirectionUtils.cpp.
References llvm::dbgs(), llvm::formatv(), I, llvm::inconvertibleErrorCode(), llvm::orc::ExecutionSession::lookup(), llvm::orc::makeJITDylibSearchOrder(), llvm::orc::MatchAllSymbols, Name, llvm::orc::ExecutionSession::reportError(), and Sym.
getCompileCallback()
Expected< ExecutorAddr > llvm::orc::JITCompileCallbackManager::getCompileCallback (CompileFunction Compile)
Reserve a compile callback.
Definition at line 66 of file IndirectionUtils.cpp.
References llvm::cantFail(), llvm::orc::JITDylib::define(), and llvm::orc::ExecutionSession::intern().
setTrampolinePool()
void llvm::orc::JITCompileCallbackManager::setTrampolinePool (std::unique_ptr< TrampolinePool > TP) inline protected
Definition at line 225 of file IndirectionUtils.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/IndirectionUtils.h
lib/ExecutionEngine/Orc/IndirectionUtils.cpp