LLVM: llvm::DwarfEHPreparePass Class Reference
llvm::DwarfEHPreparePass Class Reference
#include "llvm/CodeGen/DwarfEHPrepare.h"
Public Member Functions
DwarfEHPreparePass (const TargetMachine *TM_)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &FAM)
Public Member Functions inherited from llvm::PassInfoMixin< DwarfEHPreparePass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< DwarfEHPreparePass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 23 of file DwarfEHPrepare.h.
Constructor & Destructor Documentation
DwarfEHPreparePass()
llvm::DwarfEHPreparePass::DwarfEHPreparePass (const TargetMachine * TM_) inline explicit
Definition at line 27 of file DwarfEHPrepare.h.
References TM.
Member Function Documentation
run()
PreservedAnalyses DwarfEHPreparePass::run (Function & F, FunctionAnalysisManager & FAM)
Definition at line 369 of file DwarfEHPrepare.cpp.
References llvm::PreservedAnalyses::all(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::None, prepareDwarfEH(), llvm::PreservedAnalyses::preserve(), and TM.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/DwarfEHPrepare.h
lib/CodeGen/DwarfEHPrepare.cpp