LLVM: llvm::AttributeList Class Reference
llvm::AttributeList Class Reference
#include "llvm/IR/Attributes.h"
Classes
struct index_iterator
Public Types
enum AttrIndex : unsigned { ReturnIndex = 0U , FunctionIndex = ~0U , FirstArgIndex = 1 }
using iterator = const AttributeSet *
Public Member Functions
AttributeList ()=default
AttributeList addAttributeAtIndex (LLVMContext &C, unsigned Index, Attribute::AttrKind Kind) const
Add an attribute to the attribute set at the given index.
AttributeList addAttributeAtIndex (LLVMContext &C, unsigned Index, StringRef Kind, StringRef Value=StringRef()) const
Add an attribute to the attribute set at the given index.
AttributeList addAttributeAtIndex (LLVMContext &C, unsigned Index, Attribute A) const
Add an attribute to the attribute set at the given index.
AttributeList addAttributesAtIndex (LLVMContext &C, unsigned Index, const AttrBuilder &B) const
Add attributes to the attribute set at the given index.
AttributeList addFnAttribute (LLVMContext &C, Attribute::AttrKind Kind) const
Add a function attribute to the list.
AttributeList addFnAttribute (LLVMContext &C, Attribute Attr) const
Add a function attribute to the list.
AttributeList addFnAttribute (LLVMContext &C, StringRef Kind, StringRef Value=StringRef()) const
Add a function attribute to the list.
AttributeList addFnAttributes (LLVMContext &C, const AttrBuilder &B) const
Add function attribute to the list.
AttributeList addRetAttribute (LLVMContext &C, Attribute::AttrKind Kind) const
Add a return value attribute to the list.
AttributeList addRetAttribute (LLVMContext &C, Attribute Attr) const
Add a return value attribute to the list.
AttributeList addRetAttributes (LLVMContext &C, const AttrBuilder &B) const
Add a return value attribute to the list.
AttributeList addParamAttribute (LLVMContext &C, unsigned ArgNo, Attribute::AttrKind Kind) const
Add an argument attribute to the list.
AttributeList addParamAttribute (LLVMContext &C, unsigned ArgNo, StringRef Kind, StringRef Value=StringRef()) const
Add an argument attribute to the list.
AttributeList addParamAttribute (LLVMContext &C, ArrayRef< unsigned > ArgNos, Attribute A) const
Add an attribute to the attribute list at the given arg indices.
AttributeList addParamAttributes (LLVMContext &C, unsigned ArgNo, const AttrBuilder &B) const
Add an argument attribute to the list.
AttributeList removeAttributeAtIndex (LLVMContext &C, unsigned Index, Attribute::AttrKind Kind) const
Remove the specified attribute at the specified index from this attribute list.
AttributeList removeAttributeAtIndex (LLVMContext &C, unsigned Index, StringRef Kind) const
Remove the specified attribute at the specified index from this attribute list.
AttributeList removeAttribute (LLVMContext &C, unsigned Index, StringRef Kind) const
AttributeList removeAttributesAtIndex (LLVMContext &C, unsigned Index, const AttributeMask &AttrsToRemove) const
Remove the specified attributes at the specified index from this attribute list.
AttributeList removeAttributesAtIndex (LLVMContext &C, unsigned Index) const
Remove all attributes at the specified index from this attribute list.
AttributeList removeFnAttribute (LLVMContext &C, Attribute::AttrKind Kind) const
Remove the specified attribute at the function index from this attribute list.
AttributeList removeFnAttribute (LLVMContext &C, StringRef Kind) const
Remove the specified attribute at the function index from this attribute list.
AttributeList removeFnAttributes (LLVMContext &C, const AttributeMask &AttrsToRemove) const
Remove the specified attribute at the function index from this attribute list.
AttributeList removeFnAttributes (LLVMContext &C) const
Remove the attributes at the function index from this attribute list.
AttributeList removeRetAttribute (LLVMContext &C, Attribute::AttrKind Kind) const
Remove the specified attribute at the return value index from this attribute list.
AttributeList removeRetAttribute (LLVMContext &C, StringRef Kind) const
Remove the specified attribute at the return value index from this attribute list.
AttributeList removeRetAttributes (LLVMContext &C, const AttributeMask &AttrsToRemove) const
Remove the specified attribute at the return value index from this attribute list.
AttributeList removeParamAttribute (LLVMContext &C, unsigned ArgNo, Attribute::AttrKind Kind) const
Remove the specified attribute at the specified arg index from this attribute list.
AttributeList removeParamAttribute (LLVMContext &C, unsigned ArgNo, StringRef Kind) const
Remove the specified attribute at the specified arg index from this attribute list.
AttributeList removeParamAttributes (LLVMContext &C, unsigned ArgNo, const AttributeMask &AttrsToRemove) const
Remove the specified attribute at the specified arg index from this attribute list.
AttributeList removeParamAttributes (LLVMContext &C, unsigned ArgNo) const
Remove all attributes at the specified arg index from this attribute list.
AttributeList replaceAttributeTypeAtIndex (LLVMContext &C, unsigned ArgNo, Attribute::AttrKind Kind, Type *ReplacementTy) const
Replace the type contained by attribute AttrKind at index ArgNo wih ReplacementTy, preserving all other attributes.
AttributeList addDereferenceableRetAttr (LLVMContext &C, uint64_t Bytes) const
Add the dereferenceable attribute to the attribute set at the given index.
AttributeList addDereferenceableParamAttr (LLVMContext &C, unsigned ArgNo, uint64_t Bytes) const
Add the dereferenceable attribute to the attribute set at the given arg index.
AttributeList addDereferenceableOrNullParamAttr (LLVMContext &C, unsigned ArgNo, uint64_t Bytes) const
Add the dereferenceable_or_null attribute to the attribute set at the given arg index.
AttributeList addAllocSizeParamAttr (LLVMContext &C, unsigned ArgNo, unsigned ElemSizeArg, const std::optional< unsigned > &NumElemsArg)
Add the allocsize attribute to the attribute set at the given arg index.
AttributeSet getAttributes (unsigned Index) const
The attributes for the specified index are returned.
AttributeSet getParamAttrs (unsigned ArgNo) const
The attributes for the argument or parameter at the given index are returned.
AttributeSet getRetAttrs () const
The attributes for the ret value are returned.
AttributeSet getFnAttrs () const
The function attributes are returned.
bool hasAttributeAtIndex (unsigned Index, Attribute::AttrKind Kind) const
Return true if the attribute exists at the given index.
bool hasAttributeAtIndex (unsigned Index, StringRef Kind) const
Return true if the attribute exists at the given index.
bool hasAttributesAtIndex (unsigned Index) const
Return true if attribute exists at the given index.
bool hasParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Return true if the attribute exists for the given argument.
bool hasParamAttr (unsigned ArgNo, StringRef Kind) const
Return true if the attribute exists for the given argument.
bool hasParamAttrs (unsigned ArgNo) const
Return true if attributes exists for the given argument.
bool hasRetAttr (Attribute::AttrKind Kind) const
Return true if the attribute exists for the return value.
bool hasRetAttr (StringRef Kind) const
Return true if the attribute exists for the return value.
bool hasRetAttrs () const
Return true if attributes exist for the return value.
bool hasFnAttr (Attribute::AttrKind Kind) const
Return true if the attribute exists for the function.
bool hasFnAttr (StringRef Kind) const
Return true if the attribute exists for the function.
bool hasFnAttrs () const
Return true the attributes exist for the function.
bool hasAttrSomewhere (Attribute::AttrKind Kind, unsigned *Index=nullptr) const
Return true if the specified attribute is set for at least one parameter or for the return value.
Attribute getAttributeAtIndex (unsigned Index, Attribute::AttrKind Kind) const
Return the attribute object that exists at the given index.
Attribute getAttributeAtIndex (unsigned Index, StringRef Kind) const
Return the attribute object that exists at the given index.
Attribute getParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Return the attribute object that exists at the arg index.
Attribute getParamAttr (unsigned ArgNo, StringRef Kind) const
Return the attribute object that exists at the given index.
Attribute getFnAttr (Attribute::AttrKind Kind) const
Return the attribute object that exists for the function.
Attribute getFnAttr (StringRef Kind) const
Return the attribute object that exists for the function.
MaybeAlign getRetAlignment () const
Return the alignment of the return value.
MaybeAlign getParamAlignment (unsigned ArgNo) const
Return the alignment for the specified function parameter.
MaybeAlign getParamStackAlignment (unsigned ArgNo) const
Return the stack alignment for the specified function parameter.
Type * getParamByValType (unsigned ArgNo) const
Return the byval type for the specified function parameter.
Type * getParamStructRetType (unsigned ArgNo) const
Return the sret type for the specified function parameter.
Type * getParamByRefType (unsigned ArgNo) const
Return the byref type for the specified function parameter.
Type * getParamPreallocatedType (unsigned ArgNo) const
Return the preallocated type for the specified function parameter.
Type * getParamInAllocaType (unsigned ArgNo) const
Return the inalloca type for the specified function parameter.
Type * getParamElementType (unsigned ArgNo) const
Return the elementtype type for the specified function parameter.
MaybeAlign getFnStackAlignment () const
Get the stack alignment of the function.
MaybeAlign getRetStackAlignment () const
Get the stack alignment of the return value.
uint64_t getRetDereferenceableBytes () const
Get the number of dereferenceable bytes (or zero if unknown) of the return value.
uint64_t getParamDereferenceableBytes (unsigned Index) const
Get the number of dereferenceable bytes (or zero if unknown) of an arg.
uint64_t getRetDereferenceableOrNullBytes () const
Get the number of dereferenceable_or_null bytes (or zero if unknown) of the return value.
uint64_t getParamDereferenceableOrNullBytes (unsigned ArgNo) const
Get the number of dereferenceable_or_null bytes (or zero if unknown) of an arg.
FPClassTest getRetNoFPClass () const
Get the disallowed floating-point classes of the return value.
FPClassTest getParamNoFPClass (unsigned ArgNo) const
Get the disallowed floating-point classes of the argument value.
UWTableKind getUWTableKind () const
Get the unwind table kind requested for the function.
AllocFnKind getAllocKind () const
MemoryEffects getMemoryEffects () const
Returns memory effects of the function.
std::string getAsString (unsigned Index, bool InAttrGrp=false) const
Return the attributes at the index as a string.
bool hasParentContext (LLVMContext &C) const
Return true if this attribute list belongs to the LLVMContext.
iterator begin () const
iterator end () const
unsigned getNumAttrSets () const
index_iterator indexes () const
Use this to iterate over the valid attribute indexes.
bool operator== (const AttributeList &RHS) const
operator==/!= - Provide equality predicates.
bool operator!= (const AttributeList &RHS) const
void * getRawPointer () const
Return a raw pointer that uniquely identifies this attribute list.
bool isEmpty () const
Return true if there are no attributes.
void print (raw_ostream &O) const
void dump () const
Static Public Member Functions
static AttributeList get (LLVMContext &C, ArrayRef< std::pair< unsigned, Attribute > > Attrs)
Create an AttributeList with the specified parameters in it.
static AttributeList get (LLVMContext &C, ArrayRef< std::pair< unsigned, AttributeSet > > Attrs)
static AttributeList get (LLVMContext &C, AttributeSet FnAttrs, AttributeSet RetAttrs, ArrayRef< AttributeSet > ArgAttrs)
Create an AttributeList from attribute sets for a function, its return value, and all of its arguments.
static AttributeList get (LLVMContext &C, ArrayRef< AttributeList > Attrs)
Return an AttributeList with the specified parameters in it.
static AttributeList get (LLVMContext &C, unsigned Index, ArrayRef< Attribute::AttrKind > Kinds)
static AttributeList get (LLVMContext &C, unsigned Index, ArrayRef< Attribute::AttrKind > Kinds, ArrayRef< uint64_t > Values)
static AttributeList get (LLVMContext &C, unsigned Index, ArrayRef< StringRef > Kind)
static AttributeList get (LLVMContext &C, unsigned Index, AttributeSet Attrs)
static AttributeList get (LLVMContext &C, unsigned Index, const AttrBuilder &B)
Friends
class AttrBuilder
class AttributeListImpl
class AttributeSet
class AttributeSetNode
template<typename Ty , typename Enable >
struct DenseMapInfo
Detailed Description
Definition at line 435 of file Attributes.h.
Member Typedef Documentation
iterator
using llvm::AttributeList::iterator = const AttributeSet *
Definition at line 907 of file Attributes.h.
Member Enumeration Documentation
AttrIndex
enum llvm::AttributeList::AttrIndex : unsigned
Enumerator
ReturnIndex
FunctionIndex
FirstArgIndex
Definition at line 437 of file Attributes.h.
Constructor & Destructor Documentation
AttributeList()
llvm::AttributeList::AttributeList () default
Member Function Documentation
addAllocSizeParamAttr()
AttributeList AttributeList::addAllocSizeParamAttr (LLVMContext & C, unsigned ArgNo, unsigned ElemSizeArg, const std::optional< unsigned > & NumElemsArg)
Add the allocsize attribute to the attribute set at the given arg index.
Returns a new list because attribute lists are immutable.
Definition at line 1471 of file Attributes.cpp.
References addParamAttributes(), B, and llvm::CallingConv::C.
addAttributeAtIndex() [1/3]
AttributeList AttributeList::addAttributeAtIndex (LLVMContext & C, unsigned Index, Attribute A) const
Add an attribute to the attribute set at the given index.
Returns a new list because attribute lists are immutable.
Definition at line 1350 of file Attributes.cpp.
References A, addAttributesAtIndex(), B, and llvm::CallingConv::C.
addAttributeAtIndex() [2/3]
AttributeList AttributeList::addAttributeAtIndex (LLVMContext & C, unsigned Index, Attribute::AttrKind Kind) const
Add an attribute to the attribute set at the given index.
Returns a new list because attribute lists are immutable.
Definition at line 1331 of file Attributes.cpp.
References llvm::CallingConv::C, llvm::AttributeSet::get(), llvm::Attribute::get(), getAttributes(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::Function::addAttributeAtIndex(), llvm::CallBase::addAttributeAtIndex(), addFnAttribute(), addParamAttribute(), and addRetAttribute().
addAttributeAtIndex() [3/3]
AttributeList AttributeList::addAttributeAtIndex (LLVMContext & C, unsigned Index, StringRef Kind, StringRef Value = StringRef()) const
Add an attribute to the attribute set at the given index.
Returns a new list because attribute lists are immutable.
Definition at line 1342 of file Attributes.cpp.
References addAttributesAtIndex(), B, and llvm::CallingConv::C.
addAttributesAtIndex()
AttributeList AttributeList::addAttributesAtIndex (LLVMContext & C, unsigned Index, const AttrBuilder & B) const
Add attributes to the attribute set at the given index.
Returns a new list because attribute lists are immutable.
Definition at line 1374 of file Attributes.cpp.
References B, llvm::CallingConv::C, get(), llvm::AttributeSet::get(), and getAttributes().
Referenced by addAttributeAtIndex(), addFnAttributes(), addParamAttributes(), and addRetAttributes().
addDereferenceableOrNullParamAttr()
AttributeList AttributeList::addDereferenceableOrNullParamAttr (LLVMContext & C, unsigned ArgNo, uint64_t Bytes) const
Add the dereferenceable_or_null attribute to the attribute set at the given arg index.
Returns a new list because attribute lists are immutable.
Definition at line 1464 of file Attributes.cpp.
References addParamAttributes(), B, and llvm::CallingConv::C.
Referenced by llvm::Function::addDereferenceableOrNullParamAttr().
addDereferenceableParamAttr()
AttributeList AttributeList::addDereferenceableParamAttr (LLVMContext & C, unsigned ArgNo, uint64_t Bytes) const
Add the dereferenceable attribute to the attribute set at the given arg index.
Returns a new list because attribute lists are immutable.
Definition at line 1455 of file Attributes.cpp.
References addParamAttributes(), B, and llvm::CallingConv::C.
Referenced by llvm::Function::addDereferenceableParamAttr(), and llvm::CallBase::addDereferenceableParamAttr().
addDereferenceableRetAttr()
AttributeList AttributeList::addDereferenceableRetAttr (LLVMContext & C, uint64_t Bytes) const
Add the dereferenceable attribute to the attribute set at the given index.
Returns a new list because attribute lists are immutable.
Definition at line 1448 of file Attributes.cpp.
References addRetAttributes(), B, and llvm::CallingConv::C.
Referenced by llvm::CallBase::addDereferenceableRetAttr().
addFnAttribute() [1/3]
AttributeList llvm::AttributeList::addFnAttribute (LLVMContext & C, Attribute Attr) const inline
Add a function attribute to the list.
Returns a new list because attribute lists are immutable.
Definition at line 529 of file Attributes.h.
References addAttributeAtIndex(), llvm::CallingConv::C, and FunctionIndex.
addFnAttribute() [2/3]
AttributeList llvm::AttributeList::addFnAttribute (LLVMContext & C, Attribute::AttrKind Kind) const inline
Add a function attribute to the list.
Returns a new list because attribute lists are immutable.
Definition at line 522 of file Attributes.h.
References addAttributeAtIndex(), llvm::CallingConv::C, and FunctionIndex.
Referenced by llvm::Function::addFnAttr(), llvm::CallBase::addFnAttr(), emitTPIDR2Save(), and llvm::AMDGPULibFunc::getOrInsertFunction().
addFnAttribute() [3/3]
AttributeList llvm::AttributeList::addFnAttribute (LLVMContext & C, StringRef Kind, StringRef Value = StringRef()) const inline
Add a function attribute to the list.
Returns a new list because attribute lists are immutable.
Definition at line 537 of file Attributes.h.
References addAttributeAtIndex(), llvm::CallingConv::C, and FunctionIndex.
addFnAttributes()
AttributeList llvm::AttributeList::addFnAttributes (LLVMContext & C, const AttrBuilder & B) const inline
Add function attribute to the list.
Returns a new list because attribute lists are immutable.
Definition at line 544 of file Attributes.h.
References addAttributesAtIndex(), B, llvm::CallingConv::C, and FunctionIndex.
Referenced by llvm::Function::addFnAttrs(), and legalizeCallAttributes().
addParamAttribute() [1/3]
AttributeList AttributeList::addParamAttribute (LLVMContext & C, ArrayRef< unsigned > ArgNos, Attribute A) const
Add an attribute to the attribute list at the given arg indices.
Returns a new list because attribute lists are immutable.
Definition at line 1388 of file Attributes.cpp.
References A, assert(), attrIdxToArrayIdx(), B, llvm::ArrayRef< T >::back(), begin(), llvm::CallingConv::C, end(), FirstArgIndex, llvm::AttributeSet::get(), llvm::is_sorted(), llvm::SmallVectorImpl< T >::resize(), and llvm::SmallVectorBase< Size_T >::size().
addParamAttribute() [2/3]
AttributeList llvm::AttributeList::addParamAttribute (LLVMContext & C, unsigned ArgNo, Attribute::AttrKind Kind) const inline
Add an argument attribute to the list.
Returns a new list because attribute lists are immutable.
Definition at line 573 of file Attributes.h.
References addAttributeAtIndex(), llvm::CallingConv::C, and FirstArgIndex.
Referenced by llvm::Function::addParamAttr(), llvm::CallBase::addParamAttr(), and processCallSite().
addParamAttribute() [3/3]
AttributeList llvm::AttributeList::addParamAttribute (LLVMContext & C, unsigned ArgNo, StringRef Kind, StringRef Value = StringRef()) const inline
Add an argument attribute to the list.
Returns a new list because attribute lists are immutable.
Definition at line 581 of file Attributes.h.
References addAttributeAtIndex(), llvm::CallingConv::C, and FirstArgIndex.
addParamAttributes()
AttributeList llvm::AttributeList::addParamAttributes (LLVMContext & C, unsigned ArgNo, const AttrBuilder & B) const inline
Add an argument attribute to the list.
Returns a new list because attribute lists are immutable.
Definition at line 594 of file Attributes.h.
References addAttributesAtIndex(), B, llvm::CallingConv::C, and FirstArgIndex.
Referenced by addAllocSizeParamAttr(), addDereferenceableOrNullParamAttr(), addDereferenceableParamAttr(), llvm::Function::addParamAttrs(), and legalizeCallAttributes().
addRetAttribute() [1/2]
AttributeList llvm::AttributeList::addRetAttribute (LLVMContext & C, Attribute Attr) const inline
Add a return value attribute to the list.
Returns a new list because attribute lists are immutable.
Definition at line 558 of file Attributes.h.
References addAttributeAtIndex(), llvm::CallingConv::C, and ReturnIndex.
addRetAttribute() [2/2]
AttributeList llvm::AttributeList::addRetAttribute (LLVMContext & C, Attribute::AttrKind Kind) const inline
Add a return value attribute to the list.
Returns a new list because attribute lists are immutable.
Definition at line 551 of file Attributes.h.
References addAttributeAtIndex(), llvm::CallingConv::C, and ReturnIndex.
Referenced by llvm::Function::addRetAttr(), and llvm::CallBase::addRetAttr().
addRetAttributes()
AttributeList llvm::AttributeList::addRetAttributes (LLVMContext & C, const AttrBuilder & B) const inline
Add a return value attribute to the list.
Returns a new list because attribute lists are immutable.
Definition at line 565 of file Attributes.h.
References addAttributesAtIndex(), B, llvm::CallingConv::C, and ReturnIndex.
Referenced by addDereferenceableRetAttr(), llvm::Function::addRetAttrs(), and AddReturnAttributes().
begin()
AttributeList::iterator AttributeList::begin () const
Definition at line 1631 of file Attributes.cpp.
Referenced by addParamAttribute().
dump()
LLVM_DUMP_METHOD void AttributeList::dump () const
Definition at line 1671 of file Attributes.cpp.
References llvm::dbgs(), and print().
end()
AttributeList::iterator AttributeList::end () const
Definition at line 1635 of file Attributes.cpp.
Referenced by addParamAttribute().
get() [1/9]
AttributeList AttributeList::get (LLVMContext & C, ArrayRef< AttributeList > Attrs) static
Return an AttributeList with the specified parameters in it.
Definition at line 1304 of file Attributes.cpp.
References AttrBuilder, llvm::CallingConv::C, llvm::AttributeSet::get(), I, llvm::List, and llvm::AttrBuilder::merge().
get() [2/9]
AttributeList AttributeList::get (LLVMContext & C, ArrayRef< std::pair< unsigned, Attribute > > Attrs) static
Create an AttributeList with the specified parameters in it.
Definition at line 1161 of file Attributes.cpp.
References llvm::all_of(), assert(), llvm::CallingConv::C, E, llvm::SmallVectorImpl< T >::emplace_back(), get(), llvm::AttributeSet::get(), I, llvm::is_sorted(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by addAttributesAtIndex(), callBufferedPrintfStart(), llvm::CloneFunctionInto(), doPromotion(), llvm::emitMemCpyChk(), get(), llvm::GlobalVariable::getAttributesAsList(), getReturnAttrs(), llvm::InlineFunction(), makeStatepointExplicitImpl(), mergeAttributesAndFlags(), llvm::promoteCall(), and llvm::UpgradeIntrinsicCall().
get() [3/9]
AttributeList AttributeList::get (LLVMContext & C, ArrayRef< std::pair< unsigned, AttributeSet > > Attrs) static
Definition at line 1194 of file Attributes.cpp.
References assert(), attrIdxToArrayIdx(), llvm::CallingConv::C, FunctionIndex, llvm::is_sorted(), and llvm::none_of().
get() [4/9]
AttributeList AttributeList::get (LLVMContext & C, AttributeSet FnAttrs, AttributeSet RetAttrs, ArrayRef< AttributeSet > ArgAttrs) static
Create an AttributeList from attribute sets for a function, its return value, and all of its arguments.
Definition at line 1221 of file Attributes.cpp.
References llvm::append_range(), llvm::CallingConv::C, llvm::AttributeSet::hasAttributes(), I, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::ArrayRef< T >::size(), and llvm::ArrayRef< T >::take_front().
get() [5/9]
AttributeList AttributeList::get (LLVMContext & C, unsigned Index, ArrayRef< Attribute::AttrKind > Kinds) static
Definition at line 1277 of file Attributes.cpp.
References llvm::CallingConv::C, get(), and llvm::Attribute::get().
get() [6/9]
AttributeList AttributeList::get (LLVMContext & C, unsigned Index, ArrayRef< Attribute::AttrKind > Kinds, ArrayRef< uint64_t > Values) static
Definition at line 1285 of file Attributes.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::CallingConv::C, get(), llvm::Attribute::get(), and llvm::ArrayRef< T >::size().
get() [7/9]
AttributeList AttributeList::get (LLVMContext & C, unsigned Index, ArrayRef< StringRef > Kind) static
Definition at line 1296 of file Attributes.cpp.
References llvm::CallingConv::C, get(), and llvm::Attribute::get().
get() [8/9]
AttributeList AttributeList::get (LLVMContext & C, unsigned Index, AttributeSet Attrs) static
Definition at line 1262 of file Attributes.cpp.
References attrIdxToArrayIdx(), and llvm::CallingConv::C.
get() [9/9]
AttributeList AttributeList::get (LLVMContext & C, unsigned Index, const AttrBuilder & B) static
Definition at line 1272 of file Attributes.cpp.
References B, llvm::CallingConv::C, get(), and llvm::AttributeSet::get().
getAllocKind()
AllocFnKind AttributeList::getAllocKind () const
Definition at line 1604 of file Attributes.cpp.
References llvm::AttributeSet::getAllocKind(), and getFnAttrs().
getAsString()
std::string AttributeList::getAsString (unsigned Index, bool InAttrGrp = false) const
Return the attributes at the index as a string.
Definition at line 1612 of file Attributes.cpp.
References llvm::AttributeSet::getAsString(), and getAttributes().
Referenced by print().
getAttributeAtIndex() [1/2]
Attribute AttributeList::getAttributeAtIndex (unsigned Index, Attribute::AttrKind Kind) const
Return the attribute object that exists at the given index.
Definition at line 1521 of file Attributes.cpp.
References llvm::AttributeSet::getAttribute(), and getAttributes().
Referenced by llvm::Function::getAttributeAtIndex(), llvm::CallBase::getAttributeAtIndex(), getFnAttr(), getParamAttr(), and replaceAttributeTypeAtIndex().
getAttributeAtIndex() [2/2]
Attribute AttributeList::getAttributeAtIndex (unsigned Index, StringRef Kind) const
Return the attribute object that exists at the given index.
Definition at line 1526 of file Attributes.cpp.
References llvm::AttributeSet::getAttribute(), and getAttributes().
getAttributes()
AttributeSet AttributeList::getAttributes (unsigned Index) const
The attributes for the specified index are returned.
Definition at line 1616 of file Attributes.cpp.
References attrIdxToArrayIdx(), and getNumAttrSets().
Referenced by addAttributeAtIndex(), addAttributesAtIndex(), getAsString(), getAttributeAtIndex(), llvm::IRPosition::getAttrList(), getFnAttrs(), getParamAlignment(), getParamAttrs(), getParamByRefType(), getParamByValType(), getParamElementType(), getParamInAllocaType(), getParamPreallocatedType(), getParamStackAlignment(), getParamStructRetType(), getRetAlignment(), getRetAttrs(), hasAttributeAtIndex(), hasAttributesAtIndex(), llvm::CombinerHelper::matchSDivByConst(), llvm::CombinerHelper::matchUDivByConst(), print(), removeAttributeAtIndex(), and removeAttributesAtIndex().
getFnAttr() [1/2]
Attribute llvm::AttributeList::getFnAttr (Attribute::AttrKind Kind) const inline
Return the attribute object that exists for the function.
Definition at line 826 of file Attributes.h.
References FunctionIndex, and getAttributeAtIndex().
Referenced by getDeoptLowering(), llvm::CallBase::getFnAttr(), llvm::Function::getFnAttribute(), llvm::HexagonTargetMachine::getSubtargetImpl(), and llvm::parseStatepointDirectivesFromAttrs().
getFnAttr() [2/2]
Attribute llvm::AttributeList::getFnAttr (StringRef Kind) const inline
Return the attribute object that exists for the function.
Definition at line 831 of file Attributes.h.
References FunctionIndex, and getAttributeAtIndex().
getFnAttrs()
AttributeSet AttributeList::getFnAttrs () const
The function attributes are returned.
Definition at line 1491 of file Attributes.cpp.
References FunctionIndex, and getAttributes().
Referenced by llvm::CloneFunctionInto(), doPromotion(), fillOverallFunction(), getAllocKind(), getFnStackAlignment(), getMemoryEffects(), getUWTableKind(), legalizeCallAttributes(), llvm::promoteCall(), and llvm::UpgradeIntrinsicCall().
getFnStackAlignment()
MaybeAlign AttributeList::getFnStackAlignment () const
Get the stack alignment of the function.
Definition at line 1567 of file Attributes.cpp.
References getFnAttrs(), and llvm::AttributeSet::getStackAlignment().
Referenced by llvm::Function::getFnStackAlign().
getMemoryEffects()
MemoryEffects AttributeList::getMemoryEffects () const
Returns memory effects of the function.
Definition at line 1608 of file Attributes.cpp.
References getFnAttrs(), and llvm::AttributeSet::getMemoryEffects().
Referenced by llvm::Function::getMemoryEffects(), llvm::CallBase::getMemoryEffects(), and llvm::SITargetLowering::getTgtMemIntrinsic().
getNumAttrSets()
unsigned AttributeList::getNumAttrSets () const
Definition at line 1643 of file Attributes.cpp.
Referenced by getAttributes(), indexes(), and removeAttributesAtIndex().
getParamAlignment()
MaybeAlign AttributeList::getParamAlignment (unsigned ArgNo) const
Return the alignment for the specified function parameter.
Definition at line 1535 of file Attributes.cpp.
References FirstArgIndex, llvm::AttributeSet::getAlignment(), and getAttributes().
Referenced by llvm::Function::getParamAlign(), and llvm::CallBase::getParamAlign().
getParamAttr() [1/2]
Attribute llvm::AttributeList::getParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const inline
Return the attribute object that exists at the arg index.
Definition at line 816 of file Attributes.h.
References FirstArgIndex, and getAttributeAtIndex().
Referenced by llvm::CallBase::getParamAttr(), and llvm::Function::getParamAttribute().
getParamAttr() [2/2]
Attribute llvm::AttributeList::getParamAttr (unsigned ArgNo, StringRef Kind) const inline
Return the attribute object that exists at the given index.
Definition at line 821 of file Attributes.h.
References FirstArgIndex, and getAttributeAtIndex().
getParamAttrs()
AttributeSet AttributeList::getParamAttrs (unsigned ArgNo) const
The attributes for the argument or parameter at the given index are returned.
Definition at line 1483 of file Attributes.cpp.
References FirstArgIndex, and getAttributes().
Referenced by llvm::CloneFunctionInto(), doPromotion(), getParamDereferenceableBytes(), getParamDereferenceableOrNullBytes(), getParamNoFPClass(), llvm::Argument::getPassPointeeByValueCopySize(), llvm::Argument::getPointeeInMemoryValueType(), llvm::Attributor::identifyDefaultAbstractAttributes(), llvm::InlineFunction(), legalizeCallAttributes(), and llvm::promoteCall().
getParamByRefType()
Type * AttributeList::getParamByRefType (unsigned ArgNo) const
Return the byref type for the specified function parameter.
Definition at line 1551 of file Attributes.cpp.
References FirstArgIndex, getAttributes(), and llvm::AttributeSet::getByRefType().
Referenced by llvm::Function::getParamByRefType().
getParamByValType()
Type * AttributeList::getParamByValType (unsigned ArgNo) const
Return the byval type for the specified function parameter.
Definition at line 1543 of file Attributes.cpp.
References FirstArgIndex, getAttributes(), and llvm::AttributeSet::getByValType().
Referenced by llvm::Function::getParamByValType(), and llvm::CallBase::getParamByValType().
getParamDereferenceableBytes()
uint64_t AttributeList::getParamDereferenceableBytes (unsigned Index) const
Get the number of dereferenceable bytes (or zero if unknown) of an arg.
Definition at line 1579 of file Attributes.cpp.
References llvm::AttributeSet::getDereferenceableBytes(), and getParamAttrs().
Referenced by llvm::Function::getParamDereferenceableBytes(), and llvm::CallBase::getParamDereferenceableBytes().
getParamDereferenceableOrNullBytes()
uint64_t AttributeList::getParamDereferenceableOrNullBytes (unsigned ArgNo) const
Get the number of dereferenceable_or_null bytes (or zero if unknown) of an arg.
Definition at line 1588 of file Attributes.cpp.
References llvm::AttributeSet::getDereferenceableOrNullBytes(), and getParamAttrs().
Referenced by llvm::Function::getParamDereferenceableOrNullBytes(), and llvm::CallBase::getParamDereferenceableOrNullBytes().
getParamElementType()
Type * AttributeList::getParamElementType (unsigned ArgNo) const
Return the elementtype type for the specified function parameter.
Definition at line 1563 of file Attributes.cpp.
References FirstArgIndex, getAttributes(), and llvm::AttributeSet::getElementType().
Referenced by llvm::CallBase::getParamElementType().
getParamInAllocaType()
Type * AttributeList::getParamInAllocaType (unsigned ArgNo) const
Return the inalloca type for the specified function parameter.
Definition at line 1559 of file Attributes.cpp.
References FirstArgIndex, getAttributes(), and llvm::AttributeSet::getInAllocaType().
Referenced by llvm::Function::getParamInAllocaType(), and llvm::CallBase::getParamInAllocaType().
getParamNoFPClass()
FPClassTest AttributeList::getParamNoFPClass (unsigned ArgNo) const
Get the disallowed floating-point classes of the argument value.
Definition at line 1596 of file Attributes.cpp.
References llvm::AttributeSet::getNoFPClass(), and getParamAttrs().
Referenced by llvm::Function::getParamNoFPClass(), and llvm::CallBase::getParamNoFPClass().
getParamPreallocatedType()
Type * AttributeList::getParamPreallocatedType (unsigned ArgNo) const
Return the preallocated type for the specified function parameter.
Definition at line 1555 of file Attributes.cpp.
References FirstArgIndex, getAttributes(), and llvm::AttributeSet::getPreallocatedType().
Referenced by llvm::Function::getParamPreallocatedType(), and llvm::CallBase::getParamPreallocatedType().
getParamStackAlignment()
MaybeAlign AttributeList::getParamStackAlignment (unsigned ArgNo) const
Return the stack alignment for the specified function parameter.
Definition at line 1539 of file Attributes.cpp.
References FirstArgIndex, getAttributes(), and llvm::AttributeSet::getStackAlignment().
Referenced by llvm::Function::getParamStackAlign(), and llvm::CallBase::getParamStackAlign().
getParamStructRetType()
Type * AttributeList::getParamStructRetType (unsigned ArgNo) const
Return the sret type for the specified function parameter.
Definition at line 1547 of file Attributes.cpp.
References FirstArgIndex, getAttributes(), and llvm::AttributeSet::getStructRetType().
Referenced by llvm::Function::getParamStructRetType(), and llvm::CallBase::getParamStructRetType().
getRawPointer()
void * llvm::AttributeList::getRawPointer () const inline
Return a raw pointer that uniquely identifies this attribute list.
Definition at line 946 of file Attributes.h.
getRetAlignment()
MaybeAlign AttributeList::getRetAlignment () const
Return the alignment of the return value.
Definition at line 1531 of file Attributes.cpp.
References llvm::AttributeSet::getAlignment(), getAttributes(), and ReturnIndex.
Referenced by llvm::CallBase::getRetAlign().
getRetAttrs()
AttributeSet AttributeList::getRetAttrs () const
The attributes for the ret value are returned.
Definition at line 1487 of file Attributes.cpp.
References getAttributes(), and ReturnIndex.
Referenced by llvm::CloneFunctionInto(), doPromotion(), getRetDereferenceableBytes(), getRetDereferenceableOrNullBytes(), getRetNoFPClass(), getRetStackAlignment(), isLibCallInTailPosition(), llvm::PPCInstrInfo::isSignOrZeroExtended(), llvm::promoteCall(), and llvm::UpgradeIntrinsicCall().
getRetDereferenceableBytes()
uint64_t AttributeList::getRetDereferenceableBytes () const
Get the number of dereferenceable bytes (or zero if unknown) of the return value.
Definition at line 1575 of file Attributes.cpp.
References llvm::AttributeSet::getDereferenceableBytes(), and getRetAttrs().
Referenced by llvm::CallBase::getRetDereferenceableBytes().
getRetDereferenceableOrNullBytes()
uint64_t AttributeList::getRetDereferenceableOrNullBytes () const
Get the number of dereferenceable_or_null bytes (or zero if unknown) of the return value.
Definition at line 1583 of file Attributes.cpp.
References llvm::AttributeSet::getDereferenceableOrNullBytes(), and getRetAttrs().
Referenced by llvm::CallBase::getRetDereferenceableOrNullBytes().
getRetNoFPClass()
FPClassTest AttributeList::getRetNoFPClass () const
Get the disallowed floating-point classes of the return value.
Definition at line 1592 of file Attributes.cpp.
References llvm::AttributeSet::getNoFPClass(), and getRetAttrs().
Referenced by llvm::CallBase::getRetNoFPClass().
getRetStackAlignment()
MaybeAlign AttributeList::getRetStackAlignment () const
Get the stack alignment of the return value.
Definition at line 1571 of file Attributes.cpp.
References getRetAttrs(), and llvm::AttributeSet::getStackAlignment().
getUWTableKind()
UWTableKind AttributeList::getUWTableKind () const
Get the unwind table kind requested for the function.
Definition at line 1600 of file Attributes.cpp.
References getFnAttrs(), and llvm::AttributeSet::getUWTableKind().
Referenced by llvm::Function::getUWTableKind().
hasAttributeAtIndex() [1/2]
bool AttributeList::hasAttributeAtIndex (unsigned Index, Attribute::AttrKind Kind) const
Return true if the attribute exists at the given index.
Definition at line 1495 of file Attributes.cpp.
References getAttributes(), and llvm::AttributeSet::hasAttribute().
Referenced by hasFnAttr(), hasParamAttr(), and hasRetAttr().
hasAttributeAtIndex() [2/2]
bool AttributeList::hasAttributeAtIndex (unsigned Index, StringRef Kind) const
Return true if the attribute exists at the given index.
Definition at line 1500 of file Attributes.cpp.
References getAttributes(), and llvm::AttributeSet::hasAttribute().
hasAttributesAtIndex()
bool AttributeList::hasAttributesAtIndex (unsigned Index) const
Return true if attribute exists at the given index.
Definition at line 1504 of file Attributes.cpp.
References getAttributes(), and llvm::AttributeSet::hasAttributes().
Referenced by hasFnAttrs(), hasParamAttrs(), and hasRetAttrs().
hasAttrSomewhere()
bool AttributeList::hasAttrSomewhere (Attribute::AttrKind Kind, unsigned * Index = nullptr) const
Return true if the specified attribute is set for at least one parameter or for the return value.
If Index is not nullptr, the index of a parameter with the specified attribute is provided.
Definition at line 1516 of file Attributes.cpp.
Referenced by llvm::XCoreFrameLowering::emitPrologue(), llvm::CallBase::getArgOperandWithAttribute(), llvm::SystemZELFRegisters::getCalleeSavedRegs(), llvm::AArch64RegisterInfo::getCalleeSavedRegs(), llvm::SystemZELFRegisters::getCallPreservedMask(), llvm::AArch64RegisterInfo::getCallPreservedMask(), llvm::ARMBaseRegisterInfo::getCallPreservedMask(), llvm::AArch64RegisterInfo::getDarwinCalleeSavedRegs(), llvm::AArch64RegisterInfo::getDarwinCallPreservedMask(), llvm::CallBase::hasByValArgument(), and llvm::Attributor::isValidFunctionSignatureRewrite().
hasFnAttr() [1/2]
bool AttributeList::hasFnAttr (Attribute::AttrKind Kind) const
Return true if the attribute exists for the function.
Definition at line 1508 of file Attributes.cpp.
Referenced by getCopyFromParts(), getDeoptLowering(), llvm::AArch64TargetLowering::getOptimalMemOpLLT(), llvm::AArch64TargetLowering::getOptimalMemOpType(), llvm::ARMTargetLowering::getOptimalMemOpType(), llvm::RISCVTargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::Function::hasFnAttribute(), llvm::InlineFunction(), llvm::AArch64TargetLowering::isIntDivCheap(), llvm::RISCVTargetLowering::isIntDivCheap(), llvm::X86TargetLowering::isIntDivCheap(), maySpeculateLanes(), llvm::TLSVariableHoistPass::runImpl(), and llvm::TargetLowering::SimplifySetCC().
hasFnAttr() [2/2]
bool AttributeList::hasFnAttr (StringRef Kind) const
Return true if the attribute exists for the function.
Definition at line 1512 of file Attributes.cpp.
References FunctionIndex, and hasAttributeAtIndex().
hasFnAttrs()
bool llvm::AttributeList::hasFnAttrs () const inline
Return true the attributes exist for the function.
Definition at line 801 of file Attributes.h.
References FunctionIndex, and hasAttributesAtIndex().
hasParamAttr() [1/2]
bool llvm::AttributeList::hasParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const inline
Return true if the attribute exists for the given argument.
Definition at line 767 of file Attributes.h.
References FirstArgIndex, and hasAttributeAtIndex().
Referenced by llvm::Function::hasParamAttribute(), llvm::Function::hasStructRetAttr(), llvm::Attributor::identifyDefaultAbstractAttributes(), llvm::isLegalToPromote(), llvm::NVPTXTargetLowering::LowerFormalArguments(), and llvm::CallBase::paramHasAttr().
hasParamAttr() [2/2]
bool llvm::AttributeList::hasParamAttr (unsigned ArgNo, StringRef Kind) const inline
Return true if the attribute exists for the given argument.
Definition at line 772 of file Attributes.h.
References FirstArgIndex, and hasAttributeAtIndex().
hasParamAttrs()
bool llvm::AttributeList::hasParamAttrs (unsigned ArgNo) const inline
Return true if attributes exists for the given argument.
Definition at line 777 of file Attributes.h.
References FirstArgIndex, and hasAttributesAtIndex().
hasParentContext()
bool AttributeList::hasParentContext (LLVMContext & C) const
Return true if this attribute list belongs to the LLVMContext.
Definition at line 1623 of file Attributes.cpp.
References assert(), llvm::CallingConv::C, and isEmpty().
hasRetAttr() [1/2]
bool llvm::AttributeList::hasRetAttr (Attribute::AttrKind Kind) const inline
Return true if the attribute exists for the return value.
Definition at line 782 of file Attributes.h.
References hasAttributeAtIndex(), and ReturnIndex.
Referenced by llvm::GetReturnInfo(), llvm::Function::hasRetAttribute(), isLibCallInTailPosition(), llvm::Function::returnDoesNotAlias(), and llvm::CallBase::returnDoesNotAlias().
hasRetAttr() [2/2]
bool llvm::AttributeList::hasRetAttr (StringRef Kind) const inline
Return true if the attribute exists for the return value.
Definition at line 787 of file Attributes.h.
References hasAttributeAtIndex(), and ReturnIndex.
hasRetAttrs()
bool llvm::AttributeList::hasRetAttrs () const inline
Return true if attributes exist for the return value.
Definition at line 792 of file Attributes.h.
References hasAttributesAtIndex(), and ReturnIndex.
indexes()
index_iterator llvm::AttributeList::indexes () const inline
Use this to iterate over the valid attribute indexes.
Definition at line 939 of file Attributes.h.
References getNumAttrSets().
Referenced by print().
isEmpty()
bool llvm::AttributeList::isEmpty () const inline
Return true if there are no attributes.
Definition at line 951 of file Attributes.h.
Referenced by llvm::ValueEnumerator::getAttributeListID(), llvm::dxil::ValueEnumerator::getAttributeListID(), hasParentContext(), and legalizeCallAttributes().
operator!=()
bool llvm::AttributeList::operator!= (const AttributeList & RHS) const inline
Definition at line 943 of file Attributes.h.
References RHS.
operator==()
bool llvm::AttributeList::operator== (const AttributeList & RHS) const inline
operator==/!= - Provide equality predicates.
Definition at line 942 of file Attributes.h.
References RHS.
print()
void AttributeList::print (raw_ostream & O) const
Definition at line 1647 of file Attributes.cpp.
References FirstArgIndex, FunctionIndex, getAsString(), getAttributes(), indexes(), and ReturnIndex.
Referenced by dump().
removeAttribute()
AttributeList llvm::AttributeList::removeAttribute (LLVMContext & C, unsigned Index, StringRef Kind) const inline
Definition at line 609 of file Attributes.h.
References llvm::CallingConv::C, and removeAttributeAtIndex().
removeAttributeAtIndex() [1/2]
AttributeList AttributeList::removeAttributeAtIndex (LLVMContext & C, unsigned Index, Attribute::AttrKind Kind) const
Remove the specified attribute at the specified index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 1409 of file Attributes.cpp.
References llvm::CallingConv::C, and getAttributes().
Referenced by removeAttribute(), llvm::Function::removeAttributeAtIndex(), llvm::CallBase::removeAttributeAtIndex(), removeFnAttribute(), removeParamAttribute(), removeRetAttribute(), and replaceAttributeTypeAtIndex().
removeAttributeAtIndex() [2/2]
AttributeList AttributeList::removeAttributeAtIndex (LLVMContext & C, unsigned Index, StringRef Kind) const
Remove the specified attribute at the specified index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 1418 of file Attributes.cpp.
References llvm::CallingConv::C, and getAttributes().
removeAttributesAtIndex() [1/2]
AttributeList AttributeList::removeAttributesAtIndex (LLVMContext & C, unsigned Index) const
Remove all attributes at the specified index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 1439 of file Attributes.cpp.
References AttributeSet, attrIdxToArrayIdx(), llvm::CallingConv::C, and getNumAttrSets().
removeAttributesAtIndex() [2/2]
AttributeList AttributeList::removeAttributesAtIndex (LLVMContext & C, unsigned Index, const AttributeMask & AttrsToRemove) const
Remove the specified attributes at the specified index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 1428 of file Attributes.cpp.
References llvm::CallingConv::C, and getAttributes().
Referenced by removeFnAttributes(), removeParamAttributes(), and removeRetAttributes().
removeFnAttribute() [1/2]
AttributeList llvm::AttributeList::removeFnAttribute (LLVMContext & C, Attribute::AttrKind Kind) const inline
Remove the specified attribute at the function index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 628 of file Attributes.h.
References llvm::CallingConv::C, FunctionIndex, and removeAttributeAtIndex().
Referenced by llvm::Function::removeFnAttr(), and llvm::CallBase::removeFnAttr().
removeFnAttribute() [2/2]
AttributeList llvm::AttributeList::removeFnAttribute (LLVMContext & C, StringRef Kind) const inline
Remove the specified attribute at the function index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 634 of file Attributes.h.
References llvm::CallingConv::C, FunctionIndex, and removeAttributeAtIndex().
removeFnAttributes() [1/2]
AttributeList llvm::AttributeList::removeFnAttributes (LLVMContext & C) const inline
Remove the attributes at the function index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 648 of file Attributes.h.
References llvm::CallingConv::C, FunctionIndex, and removeAttributesAtIndex().
removeFnAttributes() [2/2]
AttributeList llvm::AttributeList::removeFnAttributes (LLVMContext & C, const AttributeMask & AttrsToRemove) const inline
Remove the specified attribute at the function index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 642 of file Attributes.h.
References llvm::CallingConv::C, FunctionIndex, and removeAttributesAtIndex().
Referenced by llvm::Function::removeFnAttrs(), and llvm::CallBase::removeFnAttrs().
removeParamAttribute() [1/2]
AttributeList llvm::AttributeList::removeParamAttribute (LLVMContext & C, unsigned ArgNo, Attribute::AttrKind Kind) const inline
Remove the specified attribute at the specified arg index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 677 of file Attributes.h.
References llvm::CallingConv::C, FirstArgIndex, and removeAttributeAtIndex().
Referenced by llvm::Function::removeParamAttr(), and llvm::CallBase::removeParamAttr().
removeParamAttribute() [2/2]
AttributeList llvm::AttributeList::removeParamAttribute (LLVMContext & C, unsigned ArgNo, StringRef Kind) const inline
Remove the specified attribute at the specified arg index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 685 of file Attributes.h.
References llvm::CallingConv::C, FirstArgIndex, and removeAttributeAtIndex().
removeParamAttributes() [1/2]
AttributeList llvm::AttributeList::removeParamAttributes (LLVMContext & C, unsigned ArgNo) const inline
Remove all attributes at the specified arg index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 699 of file Attributes.h.
References llvm::CallingConv::C, FirstArgIndex, and removeAttributesAtIndex().
removeParamAttributes() [2/2]
AttributeList llvm::AttributeList::removeParamAttributes (LLVMContext & C, unsigned ArgNo, const AttributeMask & AttrsToRemove) const inline
Remove the specified attribute at the specified arg index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 692 of file Attributes.h.
References llvm::CallingConv::C, FirstArgIndex, and removeAttributesAtIndex().
Referenced by llvm::Function::removeParamAttrs(), and llvm::CallBase::removeParamAttrs().
removeRetAttribute() [1/2]
AttributeList llvm::AttributeList::removeRetAttribute (LLVMContext & C, Attribute::AttrKind Kind) const inline
Remove the specified attribute at the return value index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 655 of file Attributes.h.
References llvm::CallingConv::C, removeAttributeAtIndex(), and ReturnIndex.
Referenced by llvm::Function::removeRetAttr(), and llvm::CallBase::removeRetAttr().
removeRetAttribute() [2/2]
AttributeList llvm::AttributeList::removeRetAttribute (LLVMContext & C, StringRef Kind) const inline
Remove the specified attribute at the return value index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 661 of file Attributes.h.
References llvm::CallingConv::C, removeAttributeAtIndex(), and ReturnIndex.
removeRetAttributes()
AttributeList llvm::AttributeList::removeRetAttributes (LLVMContext & C, const AttributeMask & AttrsToRemove) const inline
Remove the specified attribute at the return value index from this attribute list.
Returns a new list because attribute lists are immutable.
Definition at line 669 of file Attributes.h.
References llvm::CallingConv::C, removeAttributesAtIndex(), and ReturnIndex.
Referenced by llvm::Function::removeRetAttrs(), and llvm::CallBase::removeRetAttrs().
replaceAttributeTypeAtIndex()
AttributeList llvm::AttributeList::replaceAttributeTypeAtIndex (LLVMContext & C, unsigned ArgNo, Attribute::AttrKind Kind, Type * ReplacementTy) const inline
Replace the type contained by attribute AttrKind at index ArgNo wih ReplacementTy, preserving all other attributes.
Definition at line 707 of file Attributes.h.
References llvm::CallingConv::C, getAttributeAtIndex(), llvm::Attribute::getWithNewType(), and removeAttributeAtIndex().
Friends And Related Function Documentation
AttrBuilder
friend class AttrBuilder friend
Definition at line 444 of file Attributes.h.
Referenced by get().
AttributeListImpl
friend class AttributeListImpl friend
Definition at line 445 of file Attributes.h.
AttributeSet
friend class AttributeSet friend
Definition at line 446 of file Attributes.h.
Referenced by removeAttributesAtIndex().
AttributeSetNode
friend class AttributeSetNode friend
Definition at line 447 of file Attributes.h.
DenseMapInfo
template<typename Ty , typename Enable > friend struct DenseMapInfo friend
Definition at line 448 of file Attributes.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Attributes.h
lib/IR/Attributes.cpp