LLVM: llvm::AttributeListImpl Class Reference
llvm::AttributeListImpl Class Reference final
#include "IR/AttributeImpl.h"
Public Types
using iterator = const AttributeSet *
Public Member Functions
AttributeListImpl (ArrayRef< AttributeSet > Sets)
AttributeListImpl (const AttributeListImpl &)=delete
AttributeListImpl & operator= (const AttributeListImpl &)=delete
bool hasFnAttribute (Attribute::AttrKind Kind) const
Return true if the AttributeSet or the FunctionIndex has an enum attribute of the given kind.
bool hasAttrSomewhere (Attribute::AttrKind Kind, unsigned *Index=nullptr) const
Return true if the specified attribute is set for at least one parameter or for the return value.
iterator begin () const
iterator end () const
void Profile (FoldingSetNodeID &ID) const
void dump () const
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static void Profile (FoldingSetNodeID &ID, ArrayRef< AttributeSet > Nodes)
Friends
class AttributeList
Detailed Description
Definition at line 292 of file AttributeImpl.h.
Member Typedef Documentation
iterator
using llvm::AttributeListImpl::iterator = const AttributeSet *
Definition at line 327 of file AttributeImpl.h.
Constructor & Destructor Documentation
AttributeListImpl() [1/2]
AttributeListImpl::AttributeListImpl (ArrayRef< AttributeSet > Sets)
Definition at line 1076 of file Attributes.cpp.
References llvm::AttributeBitSet::addAttribute(), assert(), attrIdxToArrayIdx(), llvm::copy(), llvm::ArrayRef< T >::empty(), llvm::AttributeList::FunctionIndex, I, and llvm::size().
AttributeListImpl() [2/2]
llvm::AttributeListImpl::AttributeListImpl (const AttributeListImpl &) delete
Member Function Documentation
begin()
iterator llvm::AttributeListImpl::begin () const inline
Definition at line 329 of file AttributeImpl.h.
Referenced by end(), hasAttrSomewhere(), and Profile().
dump()
LLVM_DUMP_METHOD void AttributeListImpl::dump () const
Definition at line 1124 of file Attributes.cpp.
References AttributeList.
end()
iterator llvm::AttributeListImpl::end () const inline
Definition at line 330 of file AttributeImpl.h.
References begin().
Referenced by Profile().
hasAttrSomewhere()
bool AttributeListImpl::hasAttrSomewhere (Attribute::AttrKind Kind, unsigned * Index = nullptr) const
Return true if the specified attribute is set for at least one parameter or for the return value.
If Index is not nullptr, the index of a parameter with the specified attribute is provided.
Definition at line 1105 of file Attributes.cpp.
References begin(), E, llvm::AttributeBitSet::hasAttribute(), and I.
hasFnAttribute()
bool llvm::AttributeListImpl::hasFnAttribute (Attribute::AttrKind Kind) const inline
Return true if the AttributeSet or the FunctionIndex has an enum attribute of the given kind.
Definition at line 317 of file AttributeImpl.h.
References llvm::AttributeBitSet::hasAttribute().
operator=()
AttributeListImpl & llvm::AttributeListImpl::operator= (const AttributeListImpl &) delete
Profile() [1/2]
void AttributeListImpl::Profile (FoldingSetNodeID & ID) const
Definition at line 1095 of file Attributes.cpp.
References begin(), end(), and Profile.
Profile() [2/2]
void AttributeListImpl::Profile (FoldingSetNodeID & ID, ArrayRef< AttributeSet > Nodes) static
Definition at line 1099 of file Attributes.cpp.
Friends And Related Function Documentation
AttributeList
friend class AttributeList friend
Definition at line 295 of file AttributeImpl.h.
Referenced by dump().
The documentation for this class was generated from the following files:
lib/IR/AttributeImpl.h
lib/IR/Attributes.cpp