LLVM: llvm::jitlink::MachOLinkGraphBuilder Class Reference
llvm::jitlink::MachOLinkGraphBuilder Class Reference abstract
#include "ExecutionEngine/JITLink/MachOLinkGraphBuilder.h"
Classes
class NormalizedSection
struct NormalizedSymbol
Public Member Functions
virtual ~MachOLinkGraphBuilder ()
Expected< std::unique_ptr< LinkGraph > > buildGraph ()
Protected Types
using SectionParserFunction = std::function< Error(NormalizedSection &S)>
Protected Member Functions
MachOLinkGraphBuilder (const object::MachOObjectFile &Obj, Triple TT, SubtargetFeatures Features, LinkGraph::GetEdgeKindNameFunction GetEdgeKindName)
LinkGraph & getGraph () const
const object::MachOObjectFile & getObject () const
void addCustomSectionParser (StringRef SectionName, SectionParserFunction Parse)
virtual Error addRelocations ()=0
template<typename... ArgTs>
NormalizedSymbol & createNormalizedSymbol (ArgTs &&... Args)
Create a symbol.
NormalizedSection & getSectionByIndex (unsigned Index)
Index is zero-based (MachO section indexes are usually one-based) and assumed to be in-range.
Expected< NormalizedSection & > findSectionByIndex (unsigned Index)
Try to get the section at the given index.
Expected< NormalizedSymbol & > findSymbolByIndex (uint64_t Index)
Try to get the symbol at the given index.
Symbol * getSymbolByAddress (NormalizedSection &NSec, orc::ExecutorAddr Address)
Returns the symbol with the highest address not greater than the search address, or null if no such symbol exists.
Expected< Symbol & > findSymbolByAddress (NormalizedSection &NSec, orc::ExecutorAddr Address)
Returns the symbol with the highest address not greater than the search address, or an error if no such symbol exists.
MachO::relocation_info getRelocationInfo (const object::relocation_iterator RelItr)
Static Protected Member Functions
static Linkage getLinkage (uint16_t Desc)
static Scope getScope (StringRef Name, uint8_t Type)
static bool isAltEntry (const NormalizedSymbol &NSym)
static bool isDebugSection (const NormalizedSection &NSec)
static bool isZeroFillSection (const NormalizedSection &NSec)
Detailed Description
Definition at line 29 of file MachOLinkGraphBuilder.h.
Member Typedef Documentation
SectionParserFunction
using llvm::jitlink::MachOLinkGraphBuilder::SectionParserFunction = std::function<Error(NormalizedSection &S)> protected
Definition at line 84 of file MachOLinkGraphBuilder.h.
Constructor & Destructor Documentation
~MachOLinkGraphBuilder()
llvm::jitlink::MachOLinkGraphBuilder::~MachOLinkGraphBuilder () virtual default
MachOLinkGraphBuilder()
llvm::jitlink::MachOLinkGraphBuilder::MachOLinkGraphBuilder (const object::MachOObjectFile & Obj, Triple TT, SubtargetFeatures Features, LinkGraph::GetEdgeKindNameFunction GetEdgeKindName) protected
Definition at line 49 of file MachOLinkGraphBuilder.cpp.
References llvm::object::MachOObjectFile::getHeader64(), llvm::MachO::MH_SUBSECTIONS_VIA_SYMBOLS, and string.
Member Function Documentation
addCustomSectionParser()
void llvm::jitlink::MachOLinkGraphBuilder::addCustomSectionParser (StringRef SectionName, SectionParserFunction Parse) protected
Definition at line 61 of file MachOLinkGraphBuilder.cpp.
References assert(), and llvm::StringMap< ValueTy, AllocatorTy >::count().
addRelocations()
virtual Error llvm::jitlink::MachOLinkGraphBuilder::addRelocations () protected pure virtual
Referenced by buildGraph().
buildGraph()
Expected< std::unique_ptr< LinkGraph > > llvm::jitlink::MachOLinkGraphBuilder::buildGraph ()
Definition at line 25 of file MachOLinkGraphBuilder.cpp.
References addRelocations(), and llvm::object::MachOObjectFile::isRelocatableObject().
createNormalizedSymbol()
template<typename... ArgTs> NormalizedSymbol & llvm::jitlink::MachOLinkGraphBuilder::createNormalizedSymbol (ArgTs &&... Args) inline protected
Create a symbol.
Definition at line 101 of file MachOLinkGraphBuilder.h.
References Allocator, and Sym.
findSectionByIndex()
Expected< NormalizedSection & > llvm::jitlink::MachOLinkGraphBuilder::findSectionByIndex (unsigned Index) inline protected
Try to get the section at the given index.
Will return an error if the given index is out of range, or if no section has been added for the given index.
Definition at line 119 of file MachOLinkGraphBuilder.h.
References llvm::formatv(), and I.
findSymbolByAddress()
Expected< Symbol & > llvm::jitlink::MachOLinkGraphBuilder::findSymbolByAddress (NormalizedSection & NSec, orc::ExecutorAddr Address) inline protected
Returns the symbol with the highest address not greater than the search address, or an error if no such symbol exists.
Definition at line 151 of file MachOLinkGraphBuilder.h.
References llvm::Address, llvm::formatv(), getSymbolByAddress(), and Sym.
findSymbolByIndex()
Expected< NormalizedSymbol & > llvm::jitlink::MachOLinkGraphBuilder::findSymbolByIndex (uint64_t Index) inline protected
Try to get the symbol at the given index.
Will return an error if the given index is out of range, or if no symbol has been added for the given index.
Definition at line 130 of file MachOLinkGraphBuilder.h.
References assert(), llvm::formatv(), and I.
getGraph()
LinkGraph & llvm::jitlink::MachOLinkGraphBuilder::getGraph () const inline protected
Definition at line 90 of file MachOLinkGraphBuilder.h.
References G.
getLinkage()
Linkage llvm::jitlink::MachOLinkGraphBuilder::getLinkage (uint16_t Desc) static protected
Definition at line 68 of file MachOLinkGraphBuilder.cpp.
References llvm::MachO::N_WEAK_DEF, llvm::MachO::N_WEAK_REF, llvm::jitlink::Strong, and llvm::jitlink::Weak.
getObject()
const object::MachOObjectFile & llvm::jitlink::MachOLinkGraphBuilder::getObject () const inline protected
Definition at line 92 of file MachOLinkGraphBuilder.h.
Referenced by getRelocationInfo().
getRelocationInfo()
MachO::relocation_info llvm::jitlink::MachOLinkGraphBuilder::getRelocationInfo (const object::relocation_iterator RelItr) inline protected
Definition at line 169 of file MachOLinkGraphBuilder.h.
References getObject(), llvm::object::MachOObjectFile::getRelocation(), llvm::MachO::relocation_info::r_address, llvm::MachO::relocation_info::r_extern, llvm::MachO::relocation_info::r_length, llvm::MachO::relocation_info::r_pcrel, llvm::MachO::relocation_info::r_symbolnum, llvm::MachO::relocation_info::r_type, llvm::MachO::any_relocation_info::r_word0, and llvm::MachO::any_relocation_info::r_word1.
getScope()
Scope llvm::jitlink::MachOLinkGraphBuilder::getScope (StringRef Name, uint8_t Type) static protected
Definition at line 74 of file MachOLinkGraphBuilder.cpp.
References llvm::jitlink::Default, llvm::jitlink::Hidden, llvm::jitlink::Local, llvm::MachO::N_EXT, llvm::MachO::N_PEXT, and Name.
getSectionByIndex()
NormalizedSection & llvm::jitlink::MachOLinkGraphBuilder::getSectionByIndex (unsigned Index) inline protected
Index is zero-based (MachO section indexes are usually one-based) and assumed to be in-range.
Client is responsible for checking.
Definition at line 110 of file MachOLinkGraphBuilder.h.
References assert(), and I.
getSymbolByAddress()
Symbol * llvm::jitlink::MachOLinkGraphBuilder::getSymbolByAddress (NormalizedSection & NSec, orc::ExecutorAddr Address) inline protected
Returns the symbol with the highest address not greater than the search address, or null if no such symbol exists.
Definition at line 141 of file MachOLinkGraphBuilder.h.
References llvm::Address, llvm::jitlink::MachOLinkGraphBuilder::NormalizedSection::CanonicalSymbols, and I.
Referenced by findSymbolByAddress().
isAltEntry()
bool llvm::jitlink::MachOLinkGraphBuilder::isAltEntry (const NormalizedSymbol & NSym) static protected
Definition at line 84 of file MachOLinkGraphBuilder.cpp.
References llvm::jitlink::MachOLinkGraphBuilder::NormalizedSymbol::Desc, and llvm::MachO::N_ALT_ENTRY.
isDebugSection()
bool llvm::jitlink::MachOLinkGraphBuilder::isDebugSection (const NormalizedSection & NSec) static protected
Definition at line 88 of file MachOLinkGraphBuilder.cpp.
References llvm::jitlink::MachOLinkGraphBuilder::NormalizedSection::Flags, llvm::MachO::S_ATTR_DEBUG, and llvm::jitlink::MachOLinkGraphBuilder::NormalizedSection::SegName.
isZeroFillSection()
bool llvm::jitlink::MachOLinkGraphBuilder::isZeroFillSection (const NormalizedSection & NSec) static protected
Definition at line 93 of file MachOLinkGraphBuilder.cpp.
References llvm::jitlink::MachOLinkGraphBuilder::NormalizedSection::Flags, llvm::MachO::S_GB_ZEROFILL, llvm::MachO::S_THREAD_LOCAL_ZEROFILL, llvm::MachO::S_ZEROFILL, and llvm::MachO::SECTION_TYPE.
The documentation for this class was generated from the following files:
lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.h
lib/ExecutionEngine/JITLink/MachOLinkGraphBuilder.cpp