LLVM: llvm::HexagonPacketizerList Class Reference
llvm::HexagonPacketizerList Class Reference
#include "Target/Hexagon/HexagonVLIWPacketizer.h"
Public Member Functions
HexagonPacketizerList (MachineFunction &MF, MachineLoopInfo &MLI, AAResults *AA, const MachineBranchProbabilityInfo *MBPI, bool Minimal)
void initPacketizerState () override
bool ignorePseudoInstruction (const MachineInstr &MI, const MachineBasicBlock *MBB) override
bool isSoloInstruction (const MachineInstr &MI) override
bool isLegalToPacketizeTogether (SUnit *SUI, SUnit *SUJ) override
bool isLegalToPruneDependencies (SUnit *SUI, SUnit *SUJ) override
bool foundLSInPacket ()
MachineBasicBlock::iterator addToPacket (MachineInstr &MI) override
void endPacket (MachineBasicBlock *MBB, MachineBasicBlock::iterator MI) override
bool shouldAddToPacket (const MachineInstr &MI) override
void unpacketizeSoloInstrs (MachineFunction &MF)
Public Member Functions inherited from llvm::VLIWPacketizerList
VLIWPacketizerList (MachineFunction &MF, MachineLoopInfo &MLI, AAResults *AA)
VLIWPacketizerList & operator= (const VLIWPacketizerList &other)=delete
VLIWPacketizerList (const VLIWPacketizerList &other)=delete
virtual ~VLIWPacketizerList ()
void PacketizeMIs (MachineBasicBlock *MBB, MachineBasicBlock::iterator BeginItr, MachineBasicBlock::iterator EndItr)
DFAPacketizer * getResourceTracker ()
virtual MachineBasicBlock::iterator addToPacket (MachineInstr &MI)
virtual void endPacket (MachineBasicBlock *MBB, MachineBasicBlock::iterator MI)
virtual void initPacketizerState ()
virtual bool ignorePseudoInstruction (const MachineInstr &I, const MachineBasicBlock *MBB)
virtual bool isSoloInstruction (const MachineInstr &MI)
virtual bool shouldAddToPacket (const MachineInstr &MI)
virtual bool isLegalToPacketizeTogether (SUnit *SUI, SUnit *SUJ)
virtual bool isLegalToPruneDependencies (SUnit *SUI, SUnit *SUJ)
void addMutation (std::unique_ptr< ScheduleDAGMutation > Mutation)
bool alias (const MachineInstr &MI1, const MachineInstr &MI2, bool UseTBAA=true) const
Protected Member Functions
bool getmemShufDisabled ()
void setmemShufDisabled (bool val)
bool isCallDependent (const MachineInstr &MI, SDep::Kind DepType, unsigned DepReg)
bool promoteToDotCur (MachineInstr &MI, SDep::Kind DepType, MachineBasicBlock::iterator &MII, const TargetRegisterClass *RC)
bool canPromoteToDotCur (const MachineInstr &MI, const SUnit *PacketSU, unsigned DepReg, MachineBasicBlock::iterator &MII, const TargetRegisterClass *RC)
void cleanUpDotCur ()
bool promoteToDotNew (MachineInstr &MI, SDep::Kind DepType, MachineBasicBlock::iterator &MII, const TargetRegisterClass *RC)
bool canPromoteToDotNew (const MachineInstr &MI, const SUnit *PacketSU, unsigned DepReg, MachineBasicBlock::iterator &MII, const TargetRegisterClass *RC)
bool canPromoteToNewValue (const MachineInstr &MI, const SUnit *PacketSU, unsigned DepReg, MachineBasicBlock::iterator &MII)
bool canPromoteToNewValueStore (const MachineInstr &MI, const MachineInstr &PacketMI, unsigned DepReg)
bool demoteToDotOld (MachineInstr &MI)
bool useCallersSP (MachineInstr &MI)
void useCalleesSP (MachineInstr &MI)
bool updateOffset (SUnit *SUI, SUnit *SUJ)
Return true if we can update the offset in MI so that MI and MJ can be packetized together.
void undoChangedOffset (MachineInstr &MI)
Undo the changed offset.
bool arePredicatesComplements (MachineInstr &MI1, MachineInstr &MI2)
bool restrictingDepExistInPacket (MachineInstr &, unsigned)
bool isNewifiable (const MachineInstr &MI, const TargetRegisterClass *NewRC)
bool isCurifiable (MachineInstr &MI)
bool cannotCoexist (const MachineInstr &MI, const MachineInstr &MJ)
bool isPromotedToDotNew () const
bool tryAllocateResourcesForConstExt (bool Reserve)
bool canReserveResourcesForConstExt ()
void reserveResourcesForConstExt ()
bool hasDeadDependence (const MachineInstr &I, const MachineInstr &J)
bool hasControlDependence (const MachineInstr &I, const MachineInstr &J)
bool hasRegMaskDependence (const MachineInstr &I, const MachineInstr &J)
bool hasDualStoreDependence (const MachineInstr &I, const MachineInstr &J)
bool producesStall (const MachineInstr &MI)
unsigned int calcStall (const MachineInstr &MI)
Protected Attributes
const MachineBranchProbabilityInfo * MBPI
A handle to the branch probability pass.
const MachineLoopInfo * MLI
Protected Attributes inherited from llvm::VLIWPacketizerList
MachineFunction & MF
const TargetInstrInfo * TII
AAResults * AA
DefaultVLIWScheduler * VLIWScheduler
std::vector< MachineInstr * > CurrentPacketMIs
DFAPacketizer * ResourceTracker
std::map< MachineInstr *, SUnit * > MIToSUnit
Detailed Description
Definition at line 27 of file HexagonVLIWPacketizer.h.
Constructor & Destructor Documentation
HexagonPacketizerList()
hexagon Hexagon false HexagonPacketizerList::HexagonPacketizerList (MachineFunction & MF, MachineLoopInfo & MLI, AAResults * AA, const MachineBranchProbabilityInfo * MBPI, bool Minimal)
Definition at line 134 of file HexagonVLIWPacketizer.cpp.
Member Function Documentation
addToPacket()
MachineBasicBlock::iterator HexagonPacketizerList::addToPacket (MachineInstr & MI) override virtual
Reimplemented from llvm::VLIWPacketizerList.
Definition at line 1709 of file HexagonVLIWPacketizer.cpp.
References assert(), calcStall(), llvm::DFAPacketizer::canReserveResources(), canReserveResourcesForConstExt(), llvm::VLIWPacketizerList::CurrentPacketMIs, demoteToDotOld(), endPacket(), MBB, MI, producesStall(), llvm::DFAPacketizer::reserveResources(), reserveResourcesForConstExt(), llvm::VLIWPacketizerList::ResourceTracker, tryAllocateResourcesForConstExt(), and useCalleesSP().
arePredicatesComplements()
bool HexagonPacketizerList::arePredicatesComplements (MachineInstr & MI1, MachineInstr & MI2) protected
Definition at line 966 of file HexagonVLIWPacketizer.cpp.
References llvm::VLIWPacketizerList::CurrentPacketMIs, llvm::SDep::Data, getPredicatedRegister(), getPredicateSense(), I, llvm::SUnit::isSucc(), llvm::VLIWPacketizerList::MIToSUnit, PK_Unknown, restrictingDepExistInPacket(), and llvm::SUnit::Succs.
Referenced by isLegalToPacketizeTogether().
calcStall()
unsigned int HexagonPacketizerList::calcStall (const MachineInstr & MI) protected
Definition at line 1878 of file HexagonVLIWPacketizer.cpp.
References llvm::VLIWPacketizerList::CurrentPacketMIs, llvm::MachineLoopInfo::getLoopFor(), I, llvm::VLIWPacketizerList::MIToSUnit, MLI, and llvm::SUnit::Preds.
Referenced by addToPacket(), and producesStall().
cannotCoexist()
bool HexagonPacketizerList::cannotCoexist (const MachineInstr & MI, const MachineInstr & MJ) protected
Definition at line 1160 of file HexagonVLIWPacketizer.cpp.
References cannotCoexistAsymm(), and MI.
Referenced by isLegalToPacketizeTogether(), and isLegalToPruneDependencies().
canPromoteToDotCur()
bool HexagonPacketizerList::canPromoteToDotCur (const MachineInstr & MI, const SUnit * PacketSU, unsigned DepReg, MachineBasicBlock::iterator & MII, const TargetRegisterClass * RC) protected
Definition at line 406 of file HexagonVLIWPacketizer.cpp.
References llvm::VLIWPacketizerList::CurrentPacketMIs, llvm::dbgs(), llvm::Pass::dump(), llvm::SUnit::getInstr(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineInstr::isInlineAsm(), LLVM_DEBUG, llvm::VLIWPacketizerList::MF, and MI.
Referenced by isLegalToPacketizeTogether().
canPromoteToDotNew()
bool HexagonPacketizerList::canPromoteToDotNew (const MachineInstr & MI, const SUnit * PacketSU, unsigned DepReg, MachineBasicBlock::iterator & MII, const TargetRegisterClass * RC) protected
Definition at line 849 of file HexagonVLIWPacketizer.cpp.
References canPromoteToNewValue(), llvm::DFAPacketizer::canReserveResources(), llvm::MachineFunction::CreateMachineInstr(), D, llvm::MachineFunction::deleteMachineInstr(), DisableVecDblNVStores, llvm::MachineInstr::getDesc(), llvm::SUnit::getInstr(), llvm::MachineInstr::isImplicitDef(), isImplicitDependency(), llvm::MachineInstr::isInlineAsm(), isNewifiable(), MBPI, llvm::VLIWPacketizerList::MF, MI, and llvm::VLIWPacketizerList::ResourceTracker.
Referenced by isLegalToPacketizeTogether().
canPromoteToNewValue()
bool HexagonPacketizerList::canPromoteToNewValue (const MachineInstr & MI, const SUnit * PacketSU, unsigned DepReg, MachineBasicBlock::iterator & MII) protected
Definition at line 819 of file HexagonVLIWPacketizer.cpp.
References canPromoteToNewValueStore(), llvm::SUnit::getInstr(), and MI.
Referenced by canPromoteToDotNew().
canPromoteToNewValueStore()
bool HexagonPacketizerList::canPromoteToNewValueStore (const MachineInstr & MI, const MachineInstr & PacketMI, unsigned DepReg) protected
Definition at line 650 of file HexagonVLIWPacketizer.cpp.
References assert(), llvm::VLIWPacketizerList::CurrentPacketMIs, getAbsSetOperand(), llvm::MachineInstr::getDesc(), llvm::SUnit::getInstr(), getPostIncrementOperand(), getPredicateSense(), llvm::MachineOperand::getReg(), getReg(), getStoreValueOperand(), I, isLoadAbsSet(), llvm::MachineOperand::isReg(), llvm::MachineInstr::mayLoad(), llvm::MachineInstr::mayStore(), llvm::VLIWPacketizerList::MF, MI, llvm::VLIWPacketizerList::MIToSUnit, llvm::MachineInstr::modifiesRegister(), and llvm::MachineInstr::operands().
Referenced by canPromoteToNewValue().
canReserveResourcesForConstExt()
bool HexagonPacketizerList::canReserveResourcesForConstExt () protected
Definition at line 287 of file HexagonVLIWPacketizer.cpp.
References tryAllocateResourcesForConstExt().
Referenced by addToPacket().
cleanUpDotCur()
void HexagonPacketizerList::cleanUpDotCur () protected
Definition at line 384 of file HexagonVLIWPacketizer.cpp.
References llvm::VLIWPacketizerList::CurrentPacketMIs, llvm::dbgs(), llvm::Pass::dump(), LLVM_DEBUG, and MI.
Referenced by isLegalToPruneDependencies().
demoteToDotOld()
bool HexagonPacketizerList::demoteToDotOld (MachineInstr & MI) protected
Definition at line 470 of file HexagonVLIWPacketizer.cpp.
References MI.
Referenced by addToPacket(), and isLegalToPruneDependencies().
endPacket()
void HexagonPacketizerList::endPacket (MachineBasicBlock * MBB, MachineBasicBlock::iterator MI) override virtual
Reimplemented from llvm::VLIWPacketizerList.
Definition at line 1788 of file HexagonVLIWPacketizer.cpp.
References llvm::VLIWPacketizerList::CurrentPacketMIs, and LLVM_DEBUG.
Referenced by addToPacket().
foundLSInPacket()
bool HexagonPacketizerList::foundLSInPacket ()
Definition at line 1689 of file HexagonVLIWPacketizer.cpp.
References llvm::VLIWPacketizerList::CurrentPacketMIs.
getmemShufDisabled()
bool llvm::HexagonPacketizerList::getmemShufDisabled () inline protected
Definition at line 113 of file HexagonVLIWPacketizer.h.
hasControlDependence()
bool HexagonPacketizerList::hasControlDependence (const MachineInstr & I, const MachineInstr & J) protected
Definition at line 1233 of file HexagonVLIWPacketizer.cpp.
References doesModifyCalleeSavedReg(), I, llvm::MachineInstr::isBarrier(), llvm::MachineInstr::isBranch(), llvm::MachineInstr::isCall(), isControlFlow(), and MI.
Referenced by isLegalToPacketizeTogether().
hasDeadDependence()
bool HexagonPacketizerList::hasDeadDependence (const MachineInstr & I, const MachineInstr & J) protected
Definition at line 1206 of file HexagonVLIWPacketizer.cpp.
References I, llvm::MachineInstr::isCall(), and llvm::MachineInstr::operands().
Referenced by isLegalToPacketizeTogether().
hasDualStoreDependence()
bool HexagonPacketizerList::hasDualStoreDependence (const MachineInstr & I, const MachineInstr & J) protected
Definition at line 1299 of file HexagonVLIWPacketizer.cpp.
References I, isSystemInstr(), and llvm::MachineInstr::mayStore().
Referenced by isLegalToPacketizeTogether().
hasRegMaskDependence()
bool HexagonPacketizerList::hasRegMaskDependence (const MachineInstr & I, const MachineInstr & J) protected
Definition at line 1269 of file HexagonVLIWPacketizer.cpp.
References assert(), I, llvm::MachineInstr::isCall(), and llvm::MachineInstr::operands().
Referenced by isLegalToPacketizeTogether().
ignorePseudoInstruction()
bool HexagonPacketizerList::ignorePseudoInstruction (const MachineInstr & MI, const MachineBasicBlock * MBB) override virtual
Reimplemented from llvm::VLIWPacketizerList.
Definition at line 1043 of file HexagonVLIWPacketizer.cpp.
References llvm::InstrItineraryData::beginStage(), llvm::DFAPacketizer::getInstrItins(), llvm::MCInstrDesc::getSchedClass(), llvm::InstrStage::getUnits(), MI, and llvm::VLIWPacketizerList::ResourceTracker.
initPacketizerState()
void HexagonPacketizerList::initPacketizerState () override virtual
Reimplemented from llvm::VLIWPacketizerList.
Definition at line 1033 of file HexagonVLIWPacketizer.cpp.
References INT64_MAX.
isCallDependent()
bool HexagonPacketizerList::isCallDependent (const MachineInstr & MI, SDep::Kind DepType, unsigned DepReg) protected
Definition at line 302 of file HexagonVLIWPacketizer.cpp.
References llvm::SDep::Data, llvm::HexagonRegisterInfo::getFrameRegister(), llvm::HexagonRegisterInfo::getStackRegister(), and MI.
Referenced by isLegalToPacketizeTogether().
isCurifiable()
bool llvm::HexagonPacketizerList::isCurifiable (MachineInstr & MI) protected
isLegalToPacketizeTogether()
bool HexagonPacketizerList::isLegalToPacketizeTogether (SUnit * SUI, SUnit * SUJ) override virtual
Reimplemented from llvm::VLIWPacketizerList.
Definition at line 1324 of file HexagonVLIWPacketizer.cpp.
References llvm::VLIWPacketizerList::alias(), llvm::SDep::Anti, arePredicatesComplements(), assert(), cannotCoexist(), canPromoteToDotCur(), canPromoteToDotNew(), llvm::VLIWPacketizerList::CurrentPacketMIs, llvm::SDep::Data, llvm::find(), llvm::SUnit::getInstr(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::HexagonRegisterInfo::getStackRegister(), llvm::MachineFunction::getSubtarget(), hasControlDependence(), hasDeadDependence(), hasDualStoreDependence(), llvm::MachineInstr::hasOrderedMemoryRef(), hasRegMaskDependence(), llvm::HexagonSubtarget::hasV65Ops(), I, llvm::MachineInstr::isBranch(), llvm::MachineInstr::isCall(), isCallDependent(), isDirectJump(), llvm::MachineOperand::isReg(), isRegDependence(), isSoloInstruction(), llvm::SUnit::isSucc(), llvm::MachineInstr::mayLoad(), llvm::MachineInstr::mayStore(), llvm::VLIWPacketizerList::MF, llvm::MachineInstr::modifiesRegister(), llvm::SDep::Order, llvm::SDep::Output, PacketizeVolatiles, promoteToDotCur(), promoteToDotNew(), llvm::MachineInstr::readsRegister(), setmemShufDisabled(), Slot1Store, llvm::SUnit::Succs, and useCallersSP().
isLegalToPruneDependencies()
bool HexagonPacketizerList::isLegalToPruneDependencies (SUnit * SUI, SUnit * SUJ) override virtual
Reimplemented from llvm::VLIWPacketizerList.
Definition at line 1642 of file HexagonVLIWPacketizer.cpp.
References assert(), cannotCoexist(), cleanUpDotCur(), demoteToDotOld(), llvm::SUnit::getInstr(), I, INT64_MAX, undoChangedOffset(), updateOffset(), and useCalleesSP().
isNewifiable()
bool HexagonPacketizerList::isNewifiable (const MachineInstr & MI, const TargetRegisterClass * NewRC) protected
Definition at line 359 of file HexagonVLIWPacketizer.cpp.
References MI.
Referenced by canPromoteToDotNew().
isPromotedToDotNew()
bool llvm::HexagonPacketizerList::isPromotedToDotNew () const inline protected
Definition at line 150 of file HexagonVLIWPacketizer.h.
isSoloInstruction()
bool HexagonPacketizerList::isSoloInstruction (const MachineInstr & MI) override virtual
Reimplemented from llvm::VLIWPacketizerList.
Definition at line 1065 of file HexagonVLIWPacketizer.cpp.
References isSchedBarrier(), MI, and ScheduleInlineAsm.
Referenced by isLegalToPacketizeTogether().
producesStall()
bool HexagonPacketizerList::producesStall (const MachineInstr & MI) protected
Definition at line 1939 of file HexagonVLIWPacketizer.cpp.
References calcStall(), I, and llvm::Latency.
Referenced by addToPacket(), and shouldAddToPacket().
promoteToDotCur()
bool HexagonPacketizerList::promoteToDotCur (MachineInstr & MI, SDep::Kind DepType, MachineBasicBlock::iterator & MII, const TargetRegisterClass * RC) protected
Definition at line 375 of file HexagonVLIWPacketizer.cpp.
References assert(), llvm::SDep::Data, and MI.
Referenced by isLegalToPacketizeTogether().
promoteToDotNew()
bool HexagonPacketizerList::promoteToDotNew (MachineInstr & MI, SDep::Kind DepType, MachineBasicBlock::iterator & MII, const TargetRegisterClass * RC) protected
Definition at line 457 of file HexagonVLIWPacketizer.cpp.
References assert(), llvm::SDep::Data, MBPI, and MI.
Referenced by isLegalToPacketizeTogether().
reserveResourcesForConstExt()
void HexagonPacketizerList::reserveResourcesForConstExt () protected
Definition at line 282 of file HexagonVLIWPacketizer.cpp.
References llvm_unreachable, and tryAllocateResourcesForConstExt().
Referenced by addToPacket().
restrictingDepExistInPacket()
bool HexagonPacketizerList::restrictingDepExistInPacket (MachineInstr & MI, unsigned DepReg) protected
Definition at line 919 of file HexagonVLIWPacketizer.cpp.
References llvm::SDep::Anti, llvm::VLIWPacketizerList::CurrentPacketMIs, I, llvm::SUnit::isSucc(), MI, llvm::VLIWPacketizerList::MIToSUnit, and llvm::SUnit::Succs.
Referenced by arePredicatesComplements().
setmemShufDisabled()
void llvm::HexagonPacketizerList::setmemShufDisabled (bool val) inline protected
Definition at line 116 of file HexagonVLIWPacketizer.h.
Referenced by isLegalToPacketizeTogether().
shouldAddToPacket()
bool HexagonPacketizerList::shouldAddToPacket (const MachineInstr & MI) override virtual
Reimplemented from llvm::VLIWPacketizerList.
Definition at line 1834 of file HexagonVLIWPacketizer.cpp.
References llvm::DFAPacketizer::canReserveResources(), llvm::VLIWPacketizerList::CurrentPacketMIs, MI, producesStall(), llvm::VLIWPacketizerList::ResourceTracker, and llvm::MachineInstr::setDesc().
tryAllocateResourcesForConstExt()
bool HexagonPacketizerList::tryAllocateResourcesForConstExt (bool Reserve) protected
Definition at line 293 of file HexagonVLIWPacketizer.cpp.
References llvm::DFAPacketizer::canReserveResources(), llvm::MachineFunction::CreateMachineInstr(), llvm::MachineFunction::deleteMachineInstr(), llvm::VLIWPacketizerList::MF, llvm::DFAPacketizer::reserveResources(), and llvm::VLIWPacketizerList::ResourceTracker.
Referenced by addToPacket(), canReserveResourcesForConstExt(), and reserveResourcesForConstExt().
undoChangedOffset()
void HexagonPacketizerList::undoChangedOffset (MachineInstr & MI) protected
Undo the changed offset.
This is needed if the instruction cannot be added to the current packet due to a different instruction.
Definition at line 551 of file HexagonVLIWPacketizer.cpp.
References llvm_unreachable, MI, and OP.
Referenced by isLegalToPruneDependencies().
unpacketizeSoloInstrs()
void HexagonPacketizerList::unpacketizeSoloInstrs (MachineFunction & MF)
Definition at line 1165 of file HexagonVLIWPacketizer.cpp.
References B, hasWriteToReadDep(), llvm::make_early_inc_range(), llvm::VLIWPacketizerList::MF, MI, and moveInstrOut().
updateOffset()
bool HexagonPacketizerList::updateOffset (SUnit * SUI, SUnit * SUJ) protected
Return true if we can update the offset in MI so that MI and MJ can be packetized together.
Definition at line 515 of file HexagonVLIWPacketizer.cpp.
References llvm::SDep::Anti, assert(), llvm::SDep::Data, llvm::SUnit::getInstr(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), MI, llvm::Offset, and llvm::SUnit::Preds.
Referenced by isLegalToPruneDependencies().
useCalleesSP()
void HexagonPacketizerList::useCalleesSP (MachineInstr & MI) protected
Definition at line 497 of file HexagonVLIWPacketizer.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getStackSize(), HEXAGON_LRFP_SIZE, llvm_unreachable, llvm::VLIWPacketizerList::MF, and MI.
Referenced by addToPacket(), and isLegalToPruneDependencies().
useCallersSP()
bool HexagonPacketizerList::useCallersSP (MachineInstr & MI) protected
Definition at line 476 of file HexagonVLIWPacketizer.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getStackSize(), HEXAGON_LRFP_SIZE, llvm_unreachable, llvm::VLIWPacketizerList::MF, and MI.
Referenced by isLegalToPacketizeTogether().
Member Data Documentation
MBPI
const MachineBranchProbabilityInfo* llvm::HexagonPacketizerList::MBPI protected
A handle to the branch probability pass.
Definition at line 72 of file HexagonVLIWPacketizer.h.
Referenced by canPromoteToDotNew(), and promoteToDotNew().
MLI
const MachineLoopInfo* llvm::HexagonPacketizerList::MLI protected
Definition at line 73 of file HexagonVLIWPacketizer.h.
Referenced by calcStall().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonVLIWPacketizer.h
lib/Target/Hexagon/HexagonVLIWPacketizer.cpp