LLVM: llvm::MachO::RecordsSlice Class Reference
llvm::MachO::RecordsSlice Class Reference
#include "llvm/TextAPI/RecordsSlice.h"
Classes
struct BinaryAttrs
Public Member Functions
RecordsSlice (const llvm::Triple &T)
const llvm::Triple & getTriple () const
Get target triple.
const Target & getTarget () const
Get TAPI converted target.
Record * addRecord (StringRef Name, SymbolFlags Flags, GlobalRecord::Kind GV=GlobalRecord::Kind::Unknown, RecordLinkage Linkage=RecordLinkage::Unknown)
Add unspecified record to slice.
GlobalRecord * addGlobal (StringRef Name, RecordLinkage Linkage, GlobalRecord::Kind GV, SymbolFlags Flags=SymbolFlags::None)
Add non-ObjC global record.
ObjCInterfaceRecord * addObjCInterface (StringRef Name, RecordLinkage Linkage, bool HasEHType=false)
Add ObjC Class record.
ObjCIVarRecord * addObjCIVar (ObjCContainerRecord *Container, StringRef Name, RecordLinkage Linkage)
Add ObjC IVar record.
ObjCCategoryRecord * addObjCCategory (StringRef ClassToExtend, StringRef Category)
Add ObjC Category record.
ObjCInterfaceRecord * findObjCInterface (StringRef Name) const
Find ObjC Class.
ObjCCategoryRecord * findObjCCategory (StringRef ClassToExtend, StringRef Category) const
Find ObjC Category.
ObjCContainerRecord * findContainer (bool IsIVar, StringRef Name) const
Find ObjC Container.
ObjCIVarRecord * findObjCIVar (bool IsScopedName, StringRef Name) const
Find ObjC instance variable.
GlobalRecord * findGlobal (StringRef Name, GlobalRecord::Kind GV=GlobalRecord::Kind::Unknown) const
Find non-objc global.
bool hasBinaryAttrs () const
bool empty () const
void visit (RecordVisitor &V) const
BinaryAttrs & getBinaryAttrs ()
Return reference to BinaryAttrs.
StringRef copyString (StringRef String)
Store any strings owned by RecordSlice into allocator and return back reference to that.
Detailed Description
Definition at line 28 of file RecordsSlice.h.
Constructor & Destructor Documentation
RecordsSlice()
llvm::MachO::RecordsSlice::RecordsSlice (const llvm::Triple & T) inline
Definition at line 30 of file RecordsSlice.h.
Member Function Documentation
addGlobal()
GlobalRecord * RecordsSlice::addGlobal (StringRef Name, RecordLinkage Linkage, GlobalRecord::Kind GV, SymbolFlags Flags = SymbolFlags::None)
Add non-ObjC global record.
Parameters
Name The name of symbol.
Flags The flags that describe attributes of the symbol.
GV The kind of global.
Linkage The linkage of symbol.
Returns
The non-owning pointer to added record in slice.
Definition at line 133 of file RecordsSlice.cpp.
References copyString(), llvm::MachO::Data, llvm::MachO::GlobalRecord::Function, Name, llvm::MachO::Text, and llvm::MachO::GlobalRecord::Variable.
Referenced by addRecord().
addObjCCategory()
ObjCCategoryRecord * RecordsSlice::addObjCCategory (StringRef ClassToExtend, StringRef Category)
Add ObjC Category record.
Parameters
ClassToExtend The name of class that is being extended by the category, not symbol.
Category The name of category.
Returns
The non-owning pointer to added record in slice.
Definition at line 189 of file RecordsSlice.cpp.
References copyString(), and findObjCInterface().
Referenced by addRecord().
addObjCInterface()
ObjCInterfaceRecord * RecordsSlice::addObjCInterface (StringRef Name, RecordLinkage Linkage, bool HasEHType = false)
Add ObjC Class record.
Parameters
Name The name of class, not symbol.
Linkage The linkage of symbol.
HasEHType Whether symbol represents an eh_type.
Returns
The non-owning pointer to added record in slice.
Definition at line 153 of file RecordsSlice.cpp.
References copyString(), Name, and llvm::MachO::Rexported.
Referenced by addRecord().
addObjCIVar()
ObjCIVarRecord * RecordsSlice::addObjCIVar (ObjCContainerRecord * Container, StringRef Name, RecordLinkage Linkage)
Add ObjC IVar record.
Parameters
Name The name of ivar, not symbol.
Linkage The linkage of symbol.
Returns
The non-owning pointer to added record in slice.
Definition at line 230 of file RecordsSlice.cpp.
References llvm::MachO::ObjCContainerRecord::addObjCIVar(), copyString(), and Name.
Referenced by addRecord().
addRecord()
Record * RecordsSlice::addRecord (StringRef Name, SymbolFlags Flags, GlobalRecord::Kind GV = GlobalRecord::Kind::Unknown, RecordLinkage Linkage = RecordLinkage::Unknown)
Add unspecified record to slice.
Assign specific record type based on properties and symbol name.
Parameters
Name The name of symbol.
Flags The flags that describe attributes of the symbol.
GV The kind of global, if this represents a non obj-c global symbol.
Linkage The linkage of symbol.
Returns
The non-owning pointer to added record in slice.
Definition at line 22 of file RecordsSlice.cpp.
References addGlobal(), addObjCCategory(), addObjCInterface(), addObjCIVar(), findContainer(), llvm::MachO::GlobalSymbol, llvm_unreachable, Name, llvm::MachO::ObjectiveCClass, llvm::MachO::ObjectiveCClassEHType, llvm::MachO::ObjectiveCInstanceVariable, and llvm::MachO::parseSymbol().
copyString()
StringRef RecordsSlice::copyString (StringRef String)
Store any strings owned by RecordSlice into allocator and return back reference to that.
Definition at line 239 of file RecordsSlice.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::identifyObject(), Ptr, and llvm::String.
Referenced by addGlobal(), addObjCCategory(), addObjCInterface(), and addObjCIVar().
empty()
bool llvm::MachO::RecordsSlice::empty () const inline
Definition at line 131 of file RecordsSlice.h.
References hasBinaryAttrs().
findContainer()
ObjCContainerRecord * RecordsSlice::findContainer (bool IsIVar, StringRef Name) const
Find ObjC Container.
This is commonly used for assigning for looking up instance variables that are assigned to either a category or class.
Parameters
IsIVar If true, the name is the name of the IVar, otherwise it will be looked up as the name of the container.
Name Either the name of ivar or name of container.
Returns
The non-owning pointer to record in slice.
Definition at line 48 of file RecordsSlice.cpp.
References findObjCCategory(), findObjCInterface(), and Name.
Referenced by addRecord(), and findObjCIVar().
findGlobal()
GlobalRecord * RecordsSlice::findGlobal (StringRef Name, GlobalRecord::Kind GV = GlobalRecord::Kind::Unknown) const
Find non-objc global.
Parameters
Name The name of symbol.
GV The Kind of global to find.
Returns
The non-owning pointer to record in slice.
Definition at line 67 of file RecordsSlice.cpp.
References llvm::MachO::GlobalRecord::Function, Name, llvm::MachO::GlobalRecord::Unknown, and llvm::MachO::GlobalRecord::Variable.
findObjCCategory()
ObjCCategoryRecord * RecordsSlice::findObjCCategory (StringRef ClassToExtend, StringRef Category) const
Find ObjC Category.
Parameters
ClassToExtend The name of class, not full symbol name.
Categories The name of category.
Returns
The non-owning pointer to record in slice.
Definition at line 95 of file RecordsSlice.cpp.
Referenced by findContainer().
findObjCInterface()
ObjCInterfaceRecord * RecordsSlice::findObjCInterface (StringRef Name) const
Find ObjC Class.
Parameters
Name name of class, not full symbol name.
Returns
The non-owning pointer to record in slice.
Definition at line 91 of file RecordsSlice.cpp.
References Name.
Referenced by addObjCCategory(), and findContainer().
findObjCIVar()
ObjCIVarRecord * RecordsSlice::findObjCIVar (bool IsScopedName, StringRef Name) const
Find ObjC instance variable.
Parameters
IsScopedName This is used to determine how to parse the name.
Name Either the full name of the symbol or just the ivar.
Returns
The non-owning pointer to record in slice.
Definition at line 105 of file RecordsSlice.cpp.
References _, findContainer(), and Name.
getBinaryAttrs()
RecordsSlice::BinaryAttrs & RecordsSlice::getBinaryAttrs ()
Return reference to BinaryAttrs.
Definition at line 251 of file RecordsSlice.cpp.
References hasBinaryAttrs().
getTarget()
const Target & llvm::MachO::RecordsSlice::getTarget () const inline
Get TAPI converted target.
Definition at line 34 of file RecordsSlice.h.
getTriple()
const llvm::Triple & llvm::MachO::RecordsSlice::getTriple () const inline
Get target triple.
Definition at line 32 of file RecordsSlice.h.
hasBinaryAttrs()
bool llvm::MachO::RecordsSlice::hasBinaryAttrs () const inline
Definition at line 128 of file RecordsSlice.h.
Referenced by empty(), and getBinaryAttrs().
visit()
void RecordsSlice::visit (RecordVisitor & V) const
Definition at line 257 of file RecordsSlice.cpp.
References llvm::CallingConv::C, and G.
The documentation for this class was generated from the following files:
include/llvm/TextAPI/RecordsSlice.h
lib/TextAPI/RecordsSlice.cpp