LLVM: llvm::Substitution Class Reference
llvm::Substitution Class Reference abstract
Class representing a substitution to perform in the RegExStr string.
#include "FileCheck/FileCheckImpl.h"
Public Member Functions
Substitution (FileCheckPatternContext *Context, StringRef VarName, size_t InsertIdx)
virtual ~Substitution ()=default
StringRef getFromString () const
size_t getIndex () const
virtual Expected< std::string > getResult () const =0
Protected Attributes
FileCheckPatternContext * Context
Pointer to a class instance holding, among other things, the table with the values of live string variables at the start of any given CHECK line.
StringRef FromStr
The string that needs to be substituted for something else.
size_t InsertIdx
Detailed Description
Class representing a substitution to perform in the RegExStr string.
Definition at line 339 of file FileCheckImpl.h.
Constructor & Destructor Documentation
Substitution()
llvm::Substitution::Substitution (FileCheckPatternContext * Context, StringRef VarName, size_t InsertIdx) inline
Definition at line 357 of file FileCheckImpl.h.
~Substitution()
virtual llvm::Substitution::~Substitution () virtual default
Member Function Documentation
getFromString()
StringRef llvm::Substitution::getFromString () const inline
Returns
the string to be substituted for something else.
Definition at line 364 of file FileCheckImpl.h.
References FromStr.
Referenced by llvm::Pattern::printSubstitutions().
getIndex()
size_t llvm::Substitution::getIndex () const inline
Returns
the index where the substitution is to be performed in RegExStr.
Definition at line 367 of file FileCheckImpl.h.
References InsertIdx.
Referenced by llvm::Pattern::match().
getResult()
virtual Expected< std::string > llvm::Substitution::getResult () const pure virtual
Returns
a string containing the result of the substitution represented by this class instance or an error if substitution failed.
Implemented in llvm::StringSubstitution, and llvm::NumericSubstitution.
Referenced by llvm::Pattern::match(), and llvm::Pattern::printSubstitutions().
Member Data Documentation
Context
FileCheckPatternContext* llvm::Substitution::Context protected
Pointer to a class instance holding, among other things, the table with the values of live string variables at the start of any given CHECK line.
Used for substituting string variables with the text they were defined as. Expressions are linked to the numeric variables they use at parse time and directly access the value of the numeric variable to evaluate their value.
Definition at line 347 of file FileCheckImpl.h.
Referenced by llvm::StringSubstitution::getResult().
FromStr
StringRef llvm::Substitution::FromStr protected
The string that needs to be substituted for something else.
For a string variable this is its name, otherwise this is the whole expression.
Definition at line 351 of file FileCheckImpl.h.
Referenced by getFromString(), and llvm::StringSubstitution::getResult().
InsertIdx
size_t llvm::Substitution::InsertIdx protected
Definition at line 354 of file FileCheckImpl.h.
Referenced by getIndex().
The documentation for this class was generated from the following file:
lib/FileCheck/FileCheckImpl.h