LLVM: llvm::orc::SymbolsCouldNotBeRemoved Class Reference
llvm::orc::SymbolsCouldNotBeRemoved Class Reference
Used to notify clients that a set of symbols could not be removed.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
SymbolsCouldNotBeRemoved (std::shared_ptr< SymbolStringPool > SSP, SymbolNameSet Symbols)
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
void log (raw_ostream &OS) const override
Print an error message to an output stream.
std::shared_ptr< SymbolStringPool > getSymbolStringPool ()
const SymbolNameSet & getSymbols () const
Public Member Functions inherited from llvm::ErrorInfo< SymbolsCouldNotBeRemoved >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual void log (raw_ostream &OS) const =0
Print an error message to an output stream.
virtual std::string message () const
Return the error message as a string.
virtual std::error_code convertToErrorCode () const =0
Convert this error to a std::error_code.
virtual const void * dynamicClassID () const =0
virtual bool isA (const void *const ClassID) const
template<typename ErrorInfoT >
bool isA () const
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::ErrorInfo< SymbolsCouldNotBeRemoved >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Detailed Description
Used to notify clients that a set of symbols could not be removed.
Definition at line 458 of file Core.h.
Constructor & Destructor Documentation
SymbolsCouldNotBeRemoved()
llvm::orc::SymbolsCouldNotBeRemoved::SymbolsCouldNotBeRemoved (std::shared_ptr< SymbolStringPool > SSP, SymbolNameSet Symbols)
Definition at line 128 of file Core.cpp.
References assert(), and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty().
Member Function Documentation
convertToErrorCode()
std::error_code llvm::orc::SymbolsCouldNotBeRemoved::convertToErrorCode () const override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 134 of file Core.cpp.
References llvm::orc::orcError(), and llvm::orc::UnknownORCError.
getSymbols()
const SymbolNameSet & llvm::orc::SymbolsCouldNotBeRemoved::getSymbols () const inline
Definition at line 467 of file Core.h.
getSymbolStringPool()
std::shared_ptr< SymbolStringPool > llvm::orc::SymbolsCouldNotBeRemoved::getSymbolStringPool () inline
Definition at line 466 of file Core.h.
log()
void llvm::orc::SymbolsCouldNotBeRemoved::log (raw_ostream & OS) const override virtual
Print an error message to an output stream.
Implements llvm::ErrorInfoBase.
Definition at line 138 of file Core.cpp.
References OS.
Member Data Documentation
ID
char llvm::orc::SymbolsCouldNotBeRemoved::ID = 0 static
Definition at line 460 of file Core.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp