LLVM: GlobalsImporter Class Reference
GlobalsImporter Class Reference final
Import globals referenced by a function or other globals that are being imported, if importing such global is possible.
Public Member Functions
GlobalsImporter (const ModuleSummaryIndex &Index, const GVSummaryMapTy &DefinedGVSummaries, function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, FunctionImporter::ImportMapTy &ImportList, DenseMap< StringRef, FunctionImporter::ExportSetTy > *ExportLists)
void onImportingSummary (const GlobalValueSummary &Summary)
Detailed Description
Import globals referenced by a function or other globals that are being imported, if importing such global is possible.
Definition at line 292 of file FunctionImport.cpp.
Constructor & Destructor Documentation
GlobalsImporter()
GlobalsImporter::GlobalsImporter (const ModuleSummaryIndex & Index, const GVSummaryMapTy & DefinedGVSummaries, function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, FunctionImporter::ImportMapTy & ImportList, DenseMap< StringRef, FunctionImporter::ExportSetTy > * ExportLists) inline
Definition at line 378 of file FunctionImport.cpp.
Member Function Documentation
onImportingSummary()
void GlobalsImporter::onImportingSummary (const GlobalValueSummary & Summary) inline
Definition at line 388 of file FunctionImport.cpp.
References llvm::SmallVectorBase< Size_T >::empty(), and llvm::SmallVectorImpl< T >::pop_back_val().
Referenced by computeImportForFunction().
The documentation for this class was generated from the following file:
lib/Transforms/IPO/FunctionImport.cpp