LLVM: llvm::RawInstrProfReader< IntPtrT > Class Template Reference
llvm::RawInstrProfReader< IntPtrT > Class Template Reference
Reader for the raw instrprof binary format from runtime.
#include "llvm/ProfileData/InstrProfReader.h"
Public Member Functions
RawInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer, const InstrProfCorrelator *Correlator, std::function< void(Error)> Warn)
RawInstrProfReader (const RawInstrProfReader &)=delete
RawInstrProfReader & operator= (const RawInstrProfReader &)=delete
Error readHeader () override
Read the header. Required before reading first record.
Error readNextRecord (NamedInstrProfRecord &Record) override
Read a single record.
Error readBinaryIds (std::vector< llvm::object::BuildID > &BinaryIds) override
Read a list of binary ids.
Error printBinaryIds (raw_ostream &OS) override
Print binary ids.
uint64_t getVersion () const override
Return the profile version.
bool isIRLevelProfile () const override
bool hasCSIRLevelProfile () const override
bool instrEntryBBEnabled () const override
bool hasSingleByteCoverage () const override
Return true if the profile has single byte counters representing coverage.
bool functionEntryOnly () const override
Return true if the profile only instruments function entries.
bool hasMemoryProfile () const override
Return true if profile includes a memory profile.
bool hasTemporalProfile () const override
Return true if this has a temporal profile.
InstrProfKind getProfileKind () const override
Returns a BitsetEnum describing the attributes of the raw instr profile.
InstrProfSymtab & getSymtab () override
Return the PGO symtab.
SmallVector< TemporalProfTraceTy > & getTemporalProfTraces (std::optional< uint64_t > Weight={}) override
Public Member Functions inherited from llvm::InstrProfReader
InstrProfReader ()=default
virtual ~InstrProfReader ()=default
virtual Error readHeader ()=0
Read the header. Required before reading first record.
virtual Error readNextRecord (NamedInstrProfRecord &Record)=0
Read a single record.
virtual Error readBinaryIds (std::vector< llvm::object::BuildID > &BinaryIds)
Read a list of binary ids.
virtual Error printBinaryIds (raw_ostream &OS)
Print binary ids.
InstrProfIterator begin ()
Iterator over profile data.
InstrProfIterator end ()
virtual uint64_t getVersion () const =0
Return the profile version.
virtual bool isIRLevelProfile () const =0
virtual bool hasCSIRLevelProfile () const =0
virtual bool instrEntryBBEnabled () const =0
virtual bool hasSingleByteCoverage () const =0
Return true if the profile has single byte counters representing coverage.
virtual bool functionEntryOnly () const =0
Return true if the profile only instruments function entries.
virtual bool hasMemoryProfile () const =0
Return true if profile includes a memory profile.
virtual bool hasTemporalProfile () const =0
Return true if this has a temporal profile.
virtual InstrProfKind getProfileKind () const =0
Returns a BitsetEnum describing the attributes of the profile.
virtual InstrProfSymtab & getSymtab ()=0
Return the PGO symtab.
void accumulateCounts (CountSumOrPercent &Sum, bool IsCS)
Compute the sum of counts and return in Sum.
bool isEOF ()
Return true if the reader has finished reading the profile data.
bool hasError ()
Return true if the reader encountered an error reading profiling data.
Error getError ()
Get the current error.
virtual SmallVector< TemporalProfTraceTy > & getTemporalProfTraces (std::optional< uint64_t > Weight={})
uint64_t getTemporalProfTraceStreamSize ()
Static Public Member Functions
static bool hasFormat (const MemoryBuffer &DataBuffer)
Static Public Member Functions inherited from llvm::InstrProfReader
static Expected< std::unique_ptr< InstrProfReader > > create (const Twine &Path, vfs::FileSystem &FS, const InstrProfCorrelator *Correlator=nullptr, std::function< void(Error)> Warn=nullptr)
Factory method to create an appropriately typed reader for the given instrprof file.
static Expected< std::unique_ptr< InstrProfReader > > create (std::unique_ptr< MemoryBuffer > Buffer, const InstrProfCorrelator *Correlator=nullptr, std::function< void(Error)> Warn=nullptr)
Additional Inherited Members
Protected Member Functions inherited from llvm::InstrProfReader
Error error (instrprof_error Err, const std::string &ErrMsg="")
Set the current error and return same.
Error error (Error &&E)
Error success ()
Clear the current error and return a successful one.
Protected Attributes inherited from llvm::InstrProfReader
std::unique_ptr< InstrProfSymtab > Symtab
SmallVector< TemporalProfTraceTy > TemporalProfTraces
A list of temporal profile traces.
uint64_t TemporalProfTraceStreamSize = 0
The total number of temporal profile traces seen.
Detailed Description
template<class IntPtrT>
class llvm::RawInstrProfReader< IntPtrT >
Reader for the raw instrprof binary format from runtime.
This format is a raw memory dump of the instrumentation-based profiling data from the runtime. It has no index.
Templated on the unsigned type whose size matches pointers on the platform that wrote the profile.
Definition at line 310 of file InstrProfReader.h.
Constructor & Destructor Documentation
RawInstrProfReader() [1/2]
template<class IntPtrT > llvm::RawInstrProfReader< IntPtrT >::RawInstrProfReader (std::unique_ptr< MemoryBuffer > DataBuffer, const InstrProfCorrelator * Correlator, std::function< void(Error)> Warn) inline
Definition at line 348 of file InstrProfReader.h.
RawInstrProfReader() [2/2]
template<class IntPtrT > llvm::RawInstrProfReader< IntPtrT >::RawInstrProfReader (const RawInstrProfReader< IntPtrT > &) delete
Member Function Documentation
functionEntryOnly()
template<class IntPtrT > bool llvm::RawInstrProfReader< IntPtrT >::functionEntryOnly () const inline override virtual
Return true if the profile only instruments function entries.
Implements llvm::InstrProfReader.
Definition at line 382 of file InstrProfReader.h.
getProfileKind()
template<class IntPtrT > InstrProfKind RawInstrProfReader::getProfileKind override virtual
Returns a BitsetEnum describing the attributes of the raw instr profile.
Implements llvm::InstrProfReader.
Definition at line 461 of file InstrProfReader.cpp.
References getProfileKindFromVersion().
getSymtab()
template<class IntPtrT > InstrProfSymtab & llvm::RawInstrProfReader< IntPtrT >::getSymtab () inline override virtual
Return the PGO symtab.
There are three different readers: Raw, Text, and Indexed profile readers. The first two types of readers are used only by llvm-profdata tool, while the indexed profile reader is also used by llvm-cov tool and the compiler (backend or frontend). Since creating PGO symtab can create significant runtime and memory overhead (as it touches data for the whole program), InstrProfSymtab for the indexed profile reader should be created on demand and it is recommended to be only used for dumping purpose with llvm-proftool, not with the compiler.
Implements llvm::InstrProfReader.
Definition at line 399 of file InstrProfReader.h.
References assert(), and llvm::InstrProfReader::Symtab.
getTemporalProfTraces()
template<class IntPtrT > SmallVector< TemporalProfTraceTy > & RawInstrProfReader::getTemporalProfTraces (std::optional< uint64_t > Weight = {}) override virtual
Parameters
Weight for raw profiles use this as the temporal profile trace weight
Returns
a list of temporal profile traces.
Reimplemented from llvm::InstrProfReader.
Definition at line 467 of file InstrProfReader.cpp.
References assert().
getVersion()
template<class IntPtrT > uint64_t llvm::RawInstrProfReader< IntPtrT >::getVersion () const inline override virtual
Return the profile version.
Implements llvm::InstrProfReader.
Definition at line 364 of file InstrProfReader.h.
hasCSIRLevelProfile()
template<class IntPtrT > bool llvm::RawInstrProfReader< IntPtrT >::hasCSIRLevelProfile () const inline override virtual
Implements llvm::InstrProfReader.
Definition at line 370 of file InstrProfReader.h.
hasFormat()
template<class IntPtrT > bool RawInstrProfReader::hasFormat (const MemoryBuffer & DataBuffer) static
Definition at line 485 of file InstrProfReader.cpp.
References llvm::byteswap(), llvm::MemoryBuffer::getBufferSize(), and llvm::MemoryBuffer::getBufferStart().
Referenced by llvm::InstrProfReader::create().
hasMemoryProfile()
template<class IntPtrT > bool llvm::RawInstrProfReader< IntPtrT >::hasMemoryProfile () const inline override virtual
Return true if profile includes a memory profile.
Implements llvm::InstrProfReader.
Definition at line 386 of file InstrProfReader.h.
References assert().
hasSingleByteCoverage()
template<class IntPtrT > bool llvm::RawInstrProfReader< IntPtrT >::hasSingleByteCoverage () const inline override virtual
Return true if the profile has single byte counters representing coverage.
Implements llvm::InstrProfReader.
Definition at line 378 of file InstrProfReader.h.
hasTemporalProfile()
template<class IntPtrT > bool llvm::RawInstrProfReader< IntPtrT >::hasTemporalProfile () const inline override virtual
Return true if this has a temporal profile.
Implements llvm::InstrProfReader.
Definition at line 392 of file InstrProfReader.h.
instrEntryBBEnabled()
template<class IntPtrT > bool llvm::RawInstrProfReader< IntPtrT >::instrEntryBBEnabled () const inline override virtual
Implements llvm::InstrProfReader.
Definition at line 374 of file InstrProfReader.h.
isIRLevelProfile()
template<class IntPtrT > bool llvm::RawInstrProfReader< IntPtrT >::isIRLevelProfile () const inline override virtual
Implements llvm::InstrProfReader.
Definition at line 366 of file InstrProfReader.h.
operator=()
template<class IntPtrT > RawInstrProfReader & llvm::RawInstrProfReader< IntPtrT >::operator= (const RawInstrProfReader< IntPtrT > &) delete
printBinaryIds()
template<class IntPtrT > Error RawInstrProfReader::printBinaryIds (raw_ostream & OS) override virtual
Print binary ids.
Reimplemented from llvm::InstrProfReader.
Definition at line 830 of file InstrProfReader.cpp.
References OS, printBinaryIdsInternal(), and llvm::Error::success().
readBinaryIds()
template<class IntPtrT > Error RawInstrProfReader::readBinaryIds (std::vector< llvm::object::BuildID > & BinaryIds) override virtual
Read a list of binary ids.
Reimplemented from llvm::InstrProfReader.
Definition at line 822 of file InstrProfReader.cpp.
References llvm::Error::success().
readHeader()
template<class IntPtrT > Error RawInstrProfReader::readHeader () override virtual
Read the header. Required before reading first record.
Implements llvm::InstrProfReader.
Definition at line 495 of file InstrProfReader.cpp.
References llvm::bad_header, llvm::bad_magic, and error.
readNextRecord()
template<class IntPtrT > Error RawInstrProfReader::readNextRecord (NamedInstrProfRecord & Record) override virtual
Read a single record.
Implements llvm::InstrProfReader.
Definition at line 788 of file InstrProfReader.cpp.
References E, error, and llvm::success.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/InstrProfReader.h
lib/ProfileData/InstrProfReader.cpp