LLVM: llvm::IndirectBrExpandPass Class Reference
llvm::IndirectBrExpandPass Class Reference
#include "llvm/CodeGen/IndirectBrExpand.h"
Public Member Functions
IndirectBrExpandPass (const TargetMachine *TM)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &FAM)
Public Member Functions inherited from llvm::PassInfoMixin< IndirectBrExpandPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< IndirectBrExpandPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 18 of file IndirectBrExpand.h.
Constructor & Destructor Documentation
IndirectBrExpandPass()
llvm::IndirectBrExpandPass::IndirectBrExpandPass (const TargetMachine * TM) inline
Definition at line 22 of file IndirectBrExpand.h.
References TM.
Member Function Documentation
run()
PreservedAnalyses IndirectBrExpandPass::run (Function & F, FunctionAnalysisManager & FAM)
Definition at line 72 of file IndirectBrExpandPass.cpp.
References llvm::PreservedAnalyses::all(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::TargetMachine::getSubtargetImpl(), llvm::DomTreeUpdater::Lazy, llvm::PreservedAnalyses::preserve(), and runImpl().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/IndirectBrExpand.h
lib/CodeGen/IndirectBrExpandPass.cpp