LLVM: llvm::orc::SimpleMachOHeaderMU Class Reference
llvm::orc::SimpleMachOHeaderMU Class Reference
#include "llvm/ExecutionEngine/Orc/MachOPlatform.h"
Public Member Functions
SimpleMachOHeaderMU (MachOPlatform &MOP, SymbolStringPtr HeaderStartSymbol, MachOPlatform::HeaderOptions Opts)
StringRef getName () const override
Return the name of this materialization unit.
void materialize (std::unique_ptr< MaterializationResponsibility > R) override
Implementations of this method should materialize all symbols in the materialzation unit, except for those that have been previously discarded.
void discard (const JITDylib &JD, const SymbolStringPtr &Sym) override
Implementations of this method should discard the given symbol from the source (e.g.
Public Member Functions inherited from llvm::orc::MaterializationUnit
MaterializationUnit (Interface I)
virtual ~MaterializationUnit ()=default
virtual StringRef getName () const =0
Return the name of this materialization unit.
const SymbolFlagsMap & getSymbols () const
Return the set of symbols that this source provides.
const SymbolStringPtr & getInitializerSymbol () const
Returns the initialization symbol for this MaterializationUnit (if any).
virtual void materialize (std::unique_ptr< MaterializationResponsibility > R)=0
Implementations of this method should materialize all symbols in the materialzation unit, except for those that have been previously discarded.
void doDiscard (const JITDylib &JD, const SymbolStringPtr &Name)
Called by JITDylibs to notify MaterializationUnits that the given symbol has been overridden.
Protected Member Functions
virtual jitlink::Block & createHeaderBlock (JITDylib &JD, jitlink::LinkGraph &G, jitlink::Section &HeaderSection)
Protected Attributes
MachOPlatform & MOP
MachOPlatform::HeaderOptions Opts
Protected Attributes inherited from llvm::orc::MaterializationUnit
SymbolFlagsMap SymbolFlags
SymbolStringPtr InitSymbol
Additional Inherited Members
Static Public Attributes inherited from llvm::orc::MaterializationUnit
static char ID
Detailed Description
Definition at line 369 of file MachOPlatform.h.
Constructor & Destructor Documentation
SimpleMachOHeaderMU()
llvm::orc::SimpleMachOHeaderMU::SimpleMachOHeaderMU (MachOPlatform & MOP, SymbolStringPtr HeaderStartSymbol, MachOPlatform::HeaderOptions Opts)
Definition at line 1711 of file MachOPlatform.cpp.
Member Function Documentation
createHeaderBlock()
jitlink::Block & llvm::orc::SimpleMachOHeaderMU::createHeaderBlock (JITDylib & JD, jitlink::LinkGraph & G, jitlink::Section & HeaderSection) protected virtual
Definition at line 1745 of file MachOPlatform.cpp.
References llvm::Triple::aarch64, G, llvm::Triple::getArch(), llvm::orc::MachOPlatform::getExecutionSession(), llvm::orc::ExecutionSession::getTargetTriple(), llvm_unreachable, MOP, Opts, and llvm::Triple::x86_64.
discard()
void llvm::orc::SimpleMachOHeaderMU::discard (const JITDylib & JD, const SymbolStringPtr & Name) override virtual
Implementations of this method should discard the given symbol from the source (e.g.
if the source is an LLVM IR Module and the symbol is a function, delete the function body or mark it available externally).
Implements llvm::orc::MaterializationUnit.
Definition at line 1725 of file MachOPlatform.cpp.
getName()
StringRef llvm::orc::SimpleMachOHeaderMU::getName () const inline override virtual
Return the name of this materialization unit.
Useful for debugging output.
Implements llvm::orc::MaterializationUnit.
Definition at line 373 of file MachOPlatform.h.
materialize()
void llvm::orc::SimpleMachOHeaderMU::materialize (std::unique_ptr< MaterializationResponsibility > R) override virtual
Implementations of this method should materialize all symbols in the materialzation unit, except for those that have been previously discarded.
Implements llvm::orc::MaterializationUnit.
Definition at line 1718 of file MachOPlatform.cpp.
References llvm::orc::ObjectLinkingLayer::emit(), G, llvm::orc::MachOPlatform::getObjectLinkingLayer(), and MOP.
Member Data Documentation
MOP
MachOPlatform& llvm::orc::SimpleMachOHeaderMU::MOP protected
Definition at line 381 of file MachOPlatform.h.
Referenced by createHeaderBlock(), and materialize().
Opts
MachOPlatform::HeaderOptions llvm::orc::SimpleMachOHeaderMU::Opts protected
Definition at line 382 of file MachOPlatform.h.
Referenced by createHeaderBlock().
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/MachOPlatform.h
lib/ExecutionEngine/Orc/MachOPlatform.cpp