LLVM: llvm::MachO::Symbol Class Reference
llvm::MachO::Symbol Class Reference
#include "llvm/TextAPI/Symbol.h"
Public Types
using const_target_iterator = TargetList::const_iterator
using const_target_range = llvm::iterator_range< const_target_iterator >
using const_filtered_target_iterator = llvm::filter_iterator< const_target_iterator, std::function< bool(const Target &)> >
using const_filtered_target_range = llvm::iterator_range< const_filtered_target_iterator >
Public Member Functions
Symbol (SymbolKind Kind, StringRef Name, TargetList Targets, SymbolFlags Flags)
void addTarget (Target InputTarget)
SymbolKind getKind () const
StringRef getName () const
ArchitectureSet getArchitectures () const
SymbolFlags getFlags () const
bool isWeakDefined () const
bool isWeakReferenced () const
bool isThreadLocalValue () const
bool isUndefined () const
bool isReexported () const
bool isData () const
bool isText () const
bool hasArchitecture (Architecture Arch) const
bool hasTarget (const Target &Targ) const
const_target_range targets () const
const_filtered_target_range targets (ArchitectureSet architectures) const
void dump (raw_ostream &OS) const
void dump () const
bool operator== (const Symbol &O) const
bool operator!= (const Symbol &O) const
bool operator< (const Symbol &O) const
Detailed Description
Definition at line 82 of file Symbol.h.
Member Typedef Documentation
const_filtered_target_iterator
using llvm::MachO::Symbol::const_filtered_target_iterator = llvm::filter_iterator<const_target_iterator, std::function<bool(const Target &)> >
Definition at line 136 of file Symbol.h.
const_filtered_target_range
using llvm::MachO::Symbol::const_filtered_target_range = llvm::iterator_range<const_filtered_target_iterator>
Definition at line 139 of file Symbol.h.
const_target_iterator
using llvm::MachO::Symbol::const_target_iterator = TargetList::const_iterator
Definition at line 132 of file Symbol.h.
const_target_range
using llvm::MachO::Symbol::const_target_range = llvm::iterator_range<const_target_iterator>
Definition at line 133 of file Symbol.h.
Constructor & Destructor Documentation
Symbol()
llvm::MachO::Symbol::Symbol (SymbolKind Kind, StringRef Name, TargetList Targets, SymbolFlags Flags) inline
Definition at line 84 of file Symbol.h.
Member Function Documentation
addTarget()
void llvm::MachO::Symbol::addTarget (Target InputTarget) inline
Definition at line 87 of file Symbol.h.
References llvm::MachO::addEntry().
Referenced by llvm::MachO::SymbolSet::addGlobal().
dump() [1/2]
void llvm::MachO::Symbol::dump () const inline
Definition at line 145 of file Symbol.h.
References dump(), and llvm::errs().
Referenced by dump().
dump() [2/2]
LLVM_DUMP_METHOD void llvm::MachO::Symbol::dump (raw_ostream & OS) const
Definition at line 20 of file Symbol.cpp.
References llvm::MachO::GlobalSymbol, isThreadLocalValue(), isUndefined(), isWeakDefined(), isWeakReferenced(), llvm::MachO::ObjectiveCClass, llvm::MachO::ObjectiveCClassEHType, llvm::MachO::ObjectiveCInstanceVariable, OS, and llvm::StringRef::str().
getArchitectures()
ArchitectureSet llvm::MachO::Symbol::getArchitectures () const inline
Definition at line 90 of file Symbol.h.
References llvm::MachO::mapToArchitectureSet().
Referenced by llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::NormalizedTBD(), llvm::MachO::InterfaceFile::remove(), and llvm::object::TapiFile::TapiFile().
getFlags()
SymbolFlags llvm::MachO::Symbol::getFlags () const inline
Definition at line 93 of file Symbol.h.
Referenced by llvm::MachO::InterfaceFile::extract(), llvm::MachO::InterfaceFile::merge(), readSymbols(), and llvm::MachO::InterfaceFile::remove().
getKind()
SymbolKind llvm::MachO::Symbol::getKind () const inline
Definition at line 88 of file Symbol.h.
Referenced by llvm::MachO::InterfaceFile::extract(), llvm::MachO::InterfaceFile::merge(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::NormalizedTBD(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::NormalizedTBD_V4(), llvm::MachO::InterfaceFile::remove(), and llvm::object::TapiFile::TapiFile().
getName()
StringRef llvm::MachO::Symbol::getName () const inline
Definition at line 89 of file Symbol.h.
Referenced by llvm::MachO::InterfaceFile::extract(), llvm::MachO::InterfaceFile::merge(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::NormalizedTBD(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::NormalizedTBD_V4(), readSymbols(), llvm::MachO::InterfaceFile::remove(), and llvm::object::TapiFile::TapiFile().
hasArchitecture()
bool llvm::MachO::Symbol::hasArchitecture (Architecture Arch) const inline
Definition at line 124 of file Symbol.h.
References llvm::MachO::ArchitectureSet::contains(), and llvm::MachO::mapToArchitectureSet().
Referenced by llvm::MachO::InterfaceFile::extract().
hasTarget()
bool llvm::MachO::Symbol::hasTarget (const Target & Targ) const inline
Definition at line 128 of file Symbol.h.
References llvm::is_contained().
isData()
bool llvm::MachO::Symbol::isData () const inline
Definition at line 116 of file Symbol.h.
References llvm::MachO::Data.
Referenced by getType().
isReexported()
bool llvm::MachO::Symbol::isReexported () const inline
Definition at line 112 of file Symbol.h.
References llvm::MachO::Rexported.
Referenced by llvm::MachO::SymbolSet::exports(), and llvm::MachO::SymbolSet::reexports().
isText()
bool llvm::MachO::Symbol::isText () const inline
Definition at line 120 of file Symbol.h.
References llvm::MachO::Text.
Referenced by getType().
isThreadLocalValue()
bool llvm::MachO::Symbol::isThreadLocalValue () const inline
Definition at line 103 of file Symbol.h.
References llvm::MachO::ThreadLocalValue.
Referenced by dump(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::NormalizedTBD(), and llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::NormalizedTBD_V4().
isUndefined()
bool llvm::MachO::Symbol::isUndefined () const inline
Definition at line 108 of file Symbol.h.
References llvm::MachO::Undefined.
Referenced by dump(), llvm::MachO::SymbolSet::exports(), getFlags(), and llvm::MachO::SymbolSet::undefineds().
isWeakDefined()
bool llvm::MachO::Symbol::isWeakDefined () const inline
Definition at line 95 of file Symbol.h.
References llvm::MachO::WeakDefined.
Referenced by dump(), getFlags(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::NormalizedTBD(), and llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::NormalizedTBD_V4().
isWeakReferenced()
bool llvm::MachO::Symbol::isWeakReferenced () const inline
Definition at line 99 of file Symbol.h.
References llvm::MachO::WeakReferenced.
Referenced by dump(), getFlags(), and llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::NormalizedTBD().
operator!=()
bool llvm::MachO::Symbol::operator!= (const Symbol & O) const inline
Definition at line 150 of file Symbol.h.
operator<()
bool llvm::MachO::Symbol::operator< (const Symbol & O) const inline
Definition at line 152 of file Symbol.h.
operator==()
bool llvm::MachO::Symbol::operator== (const Symbol & O) const
Definition at line 57 of file Symbol.cpp.
References llvm::MachO::Data, Sym, and llvm::MachO::Text.
targets() [1/2]
const_target_range llvm::MachO::Symbol::targets () const inline
Definition at line 134 of file Symbol.h.
Referenced by llvm::MachO::InterfaceFile::extract(), llvm::MachO::InterfaceFile::merge(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::NormalizedTBD_V4(), and llvm::MachO::InterfaceFile::remove().
targets() [2/2]
Symbol::const_filtered_target_range llvm::MachO::Symbol::targets (ArchitectureSet architectures) const
Definition at line 49 of file Symbol.cpp.
References llvm::MachO::Target::Arch, llvm::MachO::ArchitectureSet::has(), and llvm::make_filter_range().
The documentation for this class was generated from the following files:
include/llvm/TextAPI/Symbol.h
lib/TextAPI/Symbol.cpp