LLVM: llvm::StackMapParser< Endianness >::LocationAccessor Class Reference
llvm::StackMapParser< Endianness >::LocationAccessor Class Reference
Accessor for location records.
#include "llvm/Object/StackMapParser.h"
Public Member Functions
LocationKind getKind () const
Get the Kind for this location.
unsigned getSizeInBytes () const
Get the Size for this location.
uint16_t getDwarfRegNum () const
Get the Dwarf register number for this location.
uint32_t getSmallConstant () const
Get the small-constant for this location. (Kind must be Constant).
uint32_t getConstantIndex () const
Get the constant-index for this location. (Kind must be ConstantIndex).
int32_t getOffset () const
Get the offset for this location. (Kind must be Direct or Indirect).
Friends
class StackMapParser
class RecordAccessor
Detailed Description
template<llvm::endianness Endianness>
class llvm::StackMapParser< Endianness >::LocationAccessor
Accessor for location records.
Definition at line 110 of file StackMapParser.h.
Member Function Documentation
getConstantIndex()
template<llvm::endianness Endianness> uint32_t llvm::StackMapParser< Endianness >::LocationAccessor::getConstantIndex () const inline
Get the constant-index for this location. (Kind must be ConstantIndex).
Definition at line 138 of file StackMapParser.h.
References assert(), llvm::StackMapParser< Endianness >::ConstantIndex, llvm::StackMapParser< Endianness >::LocationAccessor::getKind(), and P.
getDwarfRegNum()
template<llvm::endianness Endianness> uint16_t llvm::StackMapParser< Endianness >::LocationAccessor::getDwarfRegNum () const inline
Get the Dwarf register number for this location.
Definition at line 127 of file StackMapParser.h.
References P.
getKind()
template<llvm::endianness Endianness> LocationKind llvm::StackMapParser< Endianness >::LocationAccessor::getKind () const inline
Get the Kind for this location.
Definition at line 116 of file StackMapParser.h.
References P.
Referenced by llvm::StackMapParser< Endianness >::LocationAccessor::getConstantIndex(), llvm::StackMapParser< Endianness >::LocationAccessor::getOffset(), and llvm::StackMapParser< Endianness >::LocationAccessor::getSmallConstant().
getOffset()
template<llvm::endianness Endianness> int32_t llvm::StackMapParser< Endianness >::LocationAccessor::getOffset () const inline
Get the offset for this location. (Kind must be Direct or Indirect).
Definition at line 145 of file StackMapParser.h.
References assert(), llvm::StackMapParser< Endianness >::Direct, llvm::StackMapParser< Endianness >::LocationAccessor::getKind(), llvm::StackMapParser< Endianness >::Indirect, and P.
getSizeInBytes()
template<llvm::endianness Endianness> unsigned llvm::StackMapParser< Endianness >::LocationAccessor::getSizeInBytes () const inline
Get the Size for this location.
Definition at line 121 of file StackMapParser.h.
References P.
getSmallConstant()
template<llvm::endianness Endianness> uint32_t llvm::StackMapParser< Endianness >::LocationAccessor::getSmallConstant () const inline
Get the small-constant for this location. (Kind must be Constant).
Definition at line 132 of file StackMapParser.h.
References assert(), llvm::StackMapParser< Endianness >::Constant, llvm::StackMapParser< Endianness >::LocationAccessor::getKind(), and P.
Friends And Related Function Documentation
RecordAccessor
template<llvm::endianness Endianness> friend class RecordAccessor friend
Definition at line 112 of file StackMapParser.h.
StackMapParser
template<llvm::endianness Endianness> friend class StackMapParser friend
Definition at line 111 of file StackMapParser.h.
The documentation for this class was generated from the following file:
include/llvm/Object/StackMapParser.h