LLVM: llvm::SwitchCG::SwitchLowering Class Reference
llvm::SwitchCG::SwitchLowering Class Reference abstract
#include "llvm/CodeGen/SwitchLoweringUtils.h"
Classes
struct SplitWorkItemInfo
Public Member Functions
SwitchLowering (FunctionLoweringInfo &funcinfo)
void init (const TargetLowering &tli, const TargetMachine &tm, const DataLayout &dl)
void findJumpTables (CaseClusterVector &Clusters, const SwitchInst *SI, std::optional< SDLoc > SL, MachineBasicBlock *DefaultMBB, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI)
bool buildJumpTable (const CaseClusterVector &Clusters, unsigned First, unsigned Last, const SwitchInst *SI, const std::optional< SDLoc > &SL, MachineBasicBlock *DefaultMBB, CaseCluster &JTCluster)
void findBitTestClusters (CaseClusterVector &Clusters, const SwitchInst *SI)
bool buildBitTests (CaseClusterVector &Clusters, unsigned First, unsigned Last, const SwitchInst *SI, CaseCluster &BTCluster)
Build a bit test cluster from Clusters[First..Last].
virtual void addSuccessorWithProb (MachineBasicBlock *Src, MachineBasicBlock *Dst, BranchProbability Prob=BranchProbability::getUnknown())=0
unsigned caseClusterRank (const CaseCluster &CC, CaseClusterIt First, CaseClusterIt Last)
Determine the rank by weight of CC in [First,Last].
SplitWorkItemInfo computeSplitWorkItemInfo (const SwitchWorkListItem &W)
Compute information to balance the tree based on branch probabilities to create a near-optimal (in terms of search time given key frequency) binary search tree.
virtual ~SwitchLowering ()=default
Public Attributes
std::vector< CaseBlock > SwitchCases
Vector of CaseBlock structures used to communicate SwitchInst code generation information.
std::vector< JumpTableBlock > JTCases
Vector of JumpTable structures used to communicate SwitchInst code generation information.
std::vector< BitTestBlock > BitTestCases
Vector of BitTestBlock structures used to communicate SwitchInst code generation information.
Detailed Description
Definition at line 253 of file SwitchLoweringUtils.h.
Constructor & Destructor Documentation
SwitchLowering()
llvm::SwitchCG::SwitchLowering::SwitchLowering (FunctionLoweringInfo & funcinfo) inline
Definition at line 255 of file SwitchLoweringUtils.h.
~SwitchLowering()
virtual llvm::SwitchCG::SwitchLowering::~SwitchLowering () virtual default
References DL.
Member Function Documentation
addSuccessorWithProb()
virtual void llvm::SwitchCG::SwitchLowering::addSuccessorWithProb (MachineBasicBlock * Src, MachineBasicBlock * Dst, BranchProbability Prob = BranchProbability::getUnknown()) pure virtual
Implemented in llvm::SelectionDAGBuilder::SDAGSwitchLowering.
buildBitTests()
bool SwitchCG::SwitchLowering::buildBitTests (CaseClusterVector & Clusters, unsigned First, unsigned Last, const SwitchInst * SI, CaseCluster & BTCluster)
Build a bit test cluster from Clusters[First..Last].
Returns false if it decides it's not a good idea.
Definition at line 366 of file SwitchLoweringUtils.cpp.
References assert(), llvm::SwitchCG::CaseBits::Bits, llvm::SwitchCG::CaseCluster::bitTests(), llvm::BitWidth, llvm::SwitchCG::CC_Range, llvm::BitVector::count(), DL, llvm::SwitchCG::CaseBits::ExtraProb, llvm::First, llvm::MachineBasicBlock::getNumber(), llvm::BranchProbability::getZero(), llvm::APInt::getZero(), llvm::Hi, High, I, if(), llvm::Last, llvm::Lo, llvm::Low, llvm::SwitchCG::CaseBits::Mask, MBB, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::BitVector::set(), and llvm::sort().
buildJumpTable()
bool SwitchCG::SwitchLowering::buildJumpTable (const CaseClusterVector & Clusters, unsigned First, unsigned Last, const SwitchInst * SI, const std::optional< SDLoc > & SL, MachineBasicBlock * DefaultMBB, CaseCluster & JTCluster)
Definition at line 191 of file SwitchLoweringUtils.cpp.
References assert(), llvm::SwitchCG::CC_Range, llvm::MachineJumpTableInfo::createJumpTableIndex(), llvm::MachineFunction::CreateMachineBasicBlock(), DL, llvm::Done, llvm::First, llvm::MachineFunction::getOrCreateJumpTableInfo(), llvm::BranchProbability::getZero(), High, I, llvm::SwitchCG::CaseCluster::jumpTable(), llvm::Last, llvm::Low, MBB, llvm::MachineBasicBlock::normalizeSuccProbs(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size(), and llvm::APInt::slt().
Referenced by findJumpTables().
caseClusterRank()
unsigned SwitchCG::SwitchLowering::caseClusterRank (const CaseCluster & CC, CaseClusterIt First, CaseClusterIt Last)
Determine the rank by weight of CC in [First,Last].
If CC has more weight than each cluster in the range, its rank is 0.
Definition at line 498 of file SwitchLoweringUtils.cpp.
References CC, llvm::First, llvm::Last, and X.
computeSplitWorkItemInfo()
llvm::SwitchCG::SwitchLowering::SplitWorkItemInfo SwitchCG::SwitchLowering::computeSplitWorkItemInfo (const SwitchWorkListItem & W)
Compute information to balance the tree based on branch probabilities to create a near-optimal (in terms of search time given key frequency) binary search tree.
See e.g. Kurt Mehlhorn "Nearly Optimal Binary Search Trees" (1975).
Definition at line 511 of file SwitchLoweringUtils.cpp.
References assert(), CC, and I.
findBitTestClusters()
void SwitchCG::SwitchLowering::findBitTestClusters (CaseClusterVector & Clusters, const SwitchInst * SI)
Definition at line 267 of file SwitchLoweringUtils.cpp.
References assert(), llvm::BitWidth, llvm::CallingConv::C, llvm::SwitchCG::CC_JumpTable, llvm::SwitchCG::CC_Range, llvm::BitVector::count(), DL, llvm::First, llvm::MachineBasicBlock::getNumber(), llvm::EVT::getSizeInBits(), High, llvm::Last, MBB, N, llvm::None, llvm::BitVector::set(), llvm::ISD::SHL, and TM.
findJumpTables()
void SwitchCG::SwitchLowering::findJumpTables (CaseClusterVector & Clusters, const SwitchInst * SI, std::optional< SDLoc > SL, MachineBasicBlock * DefaultMBB, ProfileSummaryInfo * PSI, BlockFrequencyInfo * BFI)
Definition at line 46 of file SwitchLoweringUtils.cpp.
References llvm::TargetLoweringBase::areJTsAllowed(), assert(), buildJumpTable(), llvm::CallingConv::C, llvm::SwitchCG::CC_Range, llvm::First, llvm::SwitchCG::getJumpTableNumCases(), llvm::SwitchCG::getJumpTableRange(), llvm::TargetLoweringBase::getMinimumJumpTableEntries(), llvm::TargetMachine::getOptLevel(), llvm::Hi, High, I, llvm::TargetLoweringBase::isSuitableForJumpTable(), llvm::Last, llvm::Lo, N, llvm::None, and UINT64_MAX.
init()
void llvm::SwitchCG::SwitchLowering::init (const TargetLowering & tli, const TargetMachine & tm, const DataLayout & dl) inline
Definition at line 257 of file SwitchLoweringUtils.h.
References DL.
Member Data Documentation
BitTestCases
std::vector<BitTestBlock> llvm::SwitchCG::SwitchLowering::BitTestCases
Vector of BitTestBlock structures used to communicate SwitchInst code generation information.
Definition at line 274 of file SwitchLoweringUtils.h.
JTCases
std::vector<JumpTableBlock> llvm::SwitchCG::SwitchLowering::JTCases
Vector of JumpTable structures used to communicate SwitchInst code generation information.
Definition at line 270 of file SwitchLoweringUtils.h.
SwitchCases
std::vector<CaseBlock> llvm::SwitchCG::SwitchLowering::SwitchCases
Vector of CaseBlock structures used to communicate SwitchInst code generation information.
Definition at line 266 of file SwitchLoweringUtils.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/SwitchLoweringUtils.h
lib/CodeGen/SwitchLoweringUtils.cpp