LLVM: llvm::objcopy::elf::Section Class Reference
llvm::objcopy::elf::Section Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
Section (ArrayRef< uint8_t > Data)
Error accept (SectionVisitor &Visitor) const override
Error accept (MutableSectionVisitor &Visitor) override
Error removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove) override
Error initialize (SectionTableRef SecTable) override
void finalize () override
bool hasContents () const override
void restoreSymTabLink (SymbolTableSection &SymTab) override
Public Member Functions inherited from llvm::objcopy::elf::SectionBase
SectionBase ()=default
SectionBase (const SectionBase &)=default
virtual ~SectionBase ()=default
virtual Error initialize (SectionTableRef SecTable)
virtual void finalize ()
virtual Error removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove)
virtual Error removeSymbols (function_ref< bool(const Symbol &)> ToRemove)
virtual Error accept (SectionVisitor &Visitor) const =0
virtual Error accept (MutableSectionVisitor &Visitor)=0
virtual void markSymbols ()
virtual void replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > &)
virtual bool hasContents () const
virtual void onRemove ()
virtual void restoreSymTabLink (SymbolTableSection &)
Additional Inherited Members
Public Attributes inherited from llvm::objcopy::elf::SectionBase
std::string Name
Segment * ParentSegment = nullptr
uint64_t HeaderOffset = 0
uint32_t Index = 0
uint32_t OriginalIndex = 0
uint64_t OriginalFlags = 0
uint64_t OriginalType = ELF::SHT_NULL
uint64_t OriginalOffset = std::numeric_limits<uint64_t>::max()
uint64_t Addr = 0
uint64_t Align = 1
uint32_t EntrySize = 0
uint64_t Flags = 0
uint64_t Info = 0
uint64_t Link = ELF::SHN_UNDEF
uint64_t NameIndex = 0
uint64_t Offset = 0
uint64_t Size = 0
uint64_t Type = ELF::SHT_NULL
ArrayRef< uint8_t > OriginalData
bool HasSymbol = false
Detailed Description
Definition at line 486 of file ELFObject.h.
Constructor & Destructor Documentation
Section()
llvm::objcopy::elf::Section::Section (ArrayRef< uint8_t > Data) inline explicit
Definition at line 494 of file ELFObject.h.
Member Function Documentation
accept() [1/2]
Error Section::accept (MutableSectionVisitor & Visitor) override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 428 of file ELFObject.cpp.
References llvm::objcopy::elf::MutableSectionVisitor::visit().
accept() [2/2]
Error Section::accept (SectionVisitor & Visitor) const override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 424 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionVisitor::visit().
finalize()
void Section::finalize () override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 1130 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::Index, and llvm::objcopy::elf::SectionBase::Link.
hasContents()
bool llvm::objcopy::elf::Section::hasContents () const inline override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 503 of file ELFObject.h.
References llvm::ELF::SHT_NOBITS, and llvm::ELF::SHT_NULL.
initialize()
Error Section::initialize (SectionTableRef SecTable) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 1110 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionTableRef::getSection(), llvm::objcopy::elf::SectionBase::Link, llvm::objcopy::elf::SectionBase::Name, llvm::ELF::SHN_UNDEF, llvm::ELF::SHT_SYMTAB, llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::objcopy::elf::SectionBase::Type.
removeSectionReferences()
Error Section::removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 1041 of file ELFObject.cpp.
References llvm::createStringError(), llvm::invalid_argument, llvm::objcopy::elf::SectionBase::Name, llvm::Error::success(), and ToRemove.
restoreSymTabLink()
void Section::restoreSymTabLink (SymbolTableSection & SymTab) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 432 of file ELFObject.cpp.
References assert().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp