LLVM: llvm::SmallVectorImpl< T > Class Template Reference
llvm::SmallVectorImpl< T > Class Template Reference
This class consists of common code factored out of the SmallVector class to reduce code duplication based on the SmallVector 'N' template parameter.
#include "llvm/ADT/SmallVector.h"
Inherits llvm::SmallVectorTemplateBase< T, bool >.
Inherited by llvm::SmallVector< std::pair< ValueType, SUList >, 0 >, llvm::SmallVector< Function *, 0 >, llvm::SmallVector< AddressRange >, llvm::SmallVector< AddressRangeValuePair >, llvm::SmallVector< std::unique_ptr< DWARFUnit >, 1 >, llvm::SmallVector< BasicBlock *, IsPostDom ? 4 :1 >, llvm::SmallVector< llvm::DomTreeNodeBase *, 4 >, llvm::SmallVector< BlockT *, IsPostDom ? 4 :1 >, llvm::SmallVector< BoUpSLP::EdgeInfo, 1 >, llvm::SmallVector< llvm::MCFixup, FixupsSize >, llvm::SmallVector< char, ContentsSize >, llvm::SmallVector< Edge, N >, llvm::SmallVector< llvm::cl::parser::OptionInfo, 8 >, llvm::SmallVector< std::pair< const MachineFunction *, Register >, 0 >, llvm::SmallVector< std::pair< const T *, SPIRV::DTSortableEntry >, 0 >, llvm::SmallVector< std::pair< SPIRV::SpecialTypeDescriptor, SPIRV::DTSortableEntry >, 0 >, llvm::SmallVector< std::pair< KeyT, ValueT >, N >, llvm::SmallVector< T, N >, llvm::SmallVector< char, InternalLen >, llvm::SmallVector< std::tuple< NodeRef, ChildItTy, ChildItTy >, 8 >, llvm::SmallVector< llvm::AAPointerInfo::Access >, llvm::SmallVector< VariableGEPIndex, 4 >, llvm::SmallVector< int >, llvm::SmallVector< llvm::PointerUnion< llvm::Value *, const TreeEntry * >, 2 >, llvm::SmallVector< llvm::Value *, 2 >, llvm::SmallVector< llvm::Instruction *, 0 >, llvm::SmallVector< const llvm::MachineInstr *, 0 >, llvm::SmallVector< std::pair< const llvm::Function *, const llvm::DISubprogram * >, 0 >, llvm::SmallVector< std::pair< const llvm::Instruction *, bool >, 0 >, llvm::SmallVector< std::pair< const llvm::Instruction *, llvm::WeakVH >, 0 >, llvm::SmallVector< std::pair< const llvm::DILocalVariable *, unsigned >, 0 >, llvm::SmallVector< VarLocInfo >, llvm::SmallVector< llvm::SUnit *, 8 >, llvm::SmallVector< LiveDebugValues::ValueIDNum, 0 >, llvm::SmallVector< llvm::MachineOperand, 0 >, llvm::SmallVector< std::unique_ptr< llvm::SmallVector >, 0 >, llvm::SmallVector< DebugPHIRecord, 32 >, llvm::SmallVector< ValueIDNum, 0 >, llvm::SmallVector< unsigned, 0 >, llvm::SmallVector< llvm::Register, N >, llvm::SmallVector< std::pair< const llvm::MachineOperand *, unsigned >, 32 >, llvm::SmallVector< std::pair< llvm::DebugVariable, LiveDebugValues::DbgValue >, 0 >, llvm::SmallVector< std::pair< StringRef, size_t > >, llvm::SmallVector< MachineInstr *, N >, llvm::SmallVector< std::pair< BlockFrequency, unsigned >, 4 >, llvm::SmallVector< TransferTracker::Transfer, 32 >, llvm::SmallVector< ValueIDNum, 32 >, llvm::SmallVector< MachineInstr *, 4 >, llvm::SmallVector< ResolvedDbgOp >, llvm::SmallVector< DbgOp >, llvm::SmallVector< uint32_t >, llvm::SmallVector< unsigned, N >, llvm::SmallVector< DepTy, N >, llvm::SmallVector< void(*)(llvm::Function &F, llvm::AnalysisManager &AM, llvm::AAResults &llvm::AAResults), 4 >, llvm::SmallVector< RangeTy >, llvm::SmallVector< AAQueryInfo::LocPair, 4 >, llvm::SmallVector< llvm::ForwardedRegister, 1 >, llvm::SmallVector< MILOHDirective, 32 >, llvm::SmallVector< std::pair< unsigned, llvm::MCSymbol * >, 2 >, llvm::SmallVector< const llvm::MachineInstr *, 3 >, llvm::SmallVector< unsigned, 2 >, llvm::SmallVector< std::pair< unsigned, llvm::MCSymbol * >, 4 >, llvm::SmallVector< llvm::MachineInstr *, 8 >, llvm::SmallVector< llvm::BasicBlockInfo, 8 >, llvm::SmallVector< llvm::MachineInstr * >, llvm::SmallVector< FCmpLibcallsList, 0 >, llvm::SmallVector< int, 0 >, llvm::SmallVector< std::pair< StringRef, HashData >, 0 >, llvm::SmallVector< llvm::MemoryLocation, 0 >, llvm::SmallVector< uint8_t >, llvm::SmallVector< uint16_t, 16 >, llvm::SmallVector< AnalysisID, 8 >, llvm::SmallVector< AnalysisID, 2 >, llvm::SmallVector< AnalysisID, 0 >, llvm::SmallVector< std::pair< uint16_t, Form >, 3 >, llvm::SmallVector< std::pair< llvm::StringRef, llvm::ArchYAML::Archive::Child::Field >, 0 >, llvm::SmallVector< FreeList *, 8 >, llvm::SmallVector< std::pair< unsigned, llvm::AsmPrinter::MBBSectionRange >, 0 >, llvm::SmallVector< std::pair< const llvm::MCSymbol *, GOTEquivUsePair >, 0 >, llvm::SmallVector< llvm::AsmPrinter::XRayFunctionEntry, 4 >, llvm::SmallVector< std::pair< MCSection *, ConstantPool >, 0 >, llvm::SmallVector< llvm::AssumptionCache::ResultElem, 4 >, llvm::SmallVector< llvm::Attribute, 8 >, llvm::SmallVector< llvm::Function *, 0 >, llvm::SmallVector< llvm::Function *, N >, llvm::SmallVector< llvm::SmallVector *, 16 >, llvm::SmallVector< std::pair< llvm::Use *, llvm::Value * >, N >, llvm::SmallVector< std::pair< llvm::Value *, llvm::PointerIntPair< llvm::Value *, 1, bool > >, N >, llvm::SmallVector< llvm::WeakVH, N >, llvm::SmallVector< llvm::BasicBlock *, N >, llvm::SmallVector< llvm::AbstractAttribute *, N >, llvm::SmallVector< llvm::Type *, 8 >, llvm::SmallVector< uint32_t, 4 >, llvm::SmallVector< llvm::BitCodeAbbrevOp, 32 >, llvm::SmallVector< BitValue, DefaultBitN >, llvm::SmallVector< BitWord >, llvm::SmallVector< Block, 8 >, llvm::SmallVector< Weight, 4 >, llvm::SmallVector< std::pair< BlockNode, BlockMass >, 4 >, llvm::SmallVector< BlockNode, 4 >, llvm::SmallVector< BlockMass, 1 >, llvm::SmallVector< void *, 4 >, llvm::SmallVector< std::pair< void *, size_t >, 0 >, llvm::SmallVector< uint32_t, 16 >, llvm::SmallVector< llvm::CCValAssign, 4 >, llvm::SmallVector< llvm::ISD::ArgFlagsTy, 4 >, llvm::SmallVector< ByValInfo, 4 >, llvm::SmallVector< llvm::LazyCallGraph::RefSCC *, N >, llvm::SmallVector< llvm::LazyCallGraph::SCC *, N >, llvm::SmallVector< std::pair< llvm::Value *, llvm::WeakTrackingVH >, N >, llvm::SmallVector< ConstantPoolEntry, 4 >, llvm::SmallVector< AttributeItem, 64 >, llvm::SmallVector< Loop *, 8 >, llvm::SmallVector< LoopTripCountTy, 3 >, llvm::SmallVector< LoopCacheCostTy, 3 >, llvm::SmallVector< llvm::Function *, 16 >, llvm::SmallVector< llvm::Register, 4 >, llvm::SmallVector< llvm::Register, 2 >, llvm::SmallVector< llvm::CallLowering::ArgInfo, 32 >, llvm::SmallVector< unsigned >, llvm::SmallVector< std::pair< MDString *, MethodsList >, 0 >, llvm::SmallVector< llvm::BasicBlock *, 0 >, llvm::SmallVector< llvm::BasicBlock *, 4 >, llvm::SmallVector< Value *, 0 >, llvm::SmallVector< llvm::AllocaInst *, 16 >, llvm::SmallVector< llvm::unique_function< bool(llvm::StringRef)>, 4 >, llvm::SmallVector< llvm::unique_function< void(llvm::StringRef)>, 4 >, llvm::SmallVector< FileInfo, 4 >, llvm::SmallVector< CVGlobalVariable, 1 >, llvm::SmallVector< const llvm::DIDerivedType *, 4 >, llvm::SmallVector< std::pair< const llvm::Function *, std::unique_ptr< FunctionInfo > >, 0 >, llvm::SmallVector< const llvm::DISubprogram *, N >, llvm::SmallVector< const llvm::DICompositeType *, 4 >, llvm::SmallVector< const llvm::DILocation *, 1 >, llvm::SmallVector< llvm::codeview::TypeIndex, N >, llvm::SmallVector< LocalVariable, 1 >, llvm::SmallVector< LexicalBlock *, 1 >, llvm::SmallVector< std::pair< llvm::CodeViewDebug::LocalVarDef, llvm::SmallVector< std::pair< const llvm::MCSymbol *, const llvm::MCSymbol * >, 1 > >, 0 >, llvm::SmallVector< llvm::MachineInstr *, N >, llvm::SmallVector< std::pair< GlobalVariable *, ConstCandVecType >, 0 >, llvm::SmallVector< consthoist::ConstantInfo, 8 >, llvm::SmallVector< std::pair< GlobalVariable *, ConstInfoVecType >, 0 >, llvm::SmallVector< std::pair< llvm::Instruction *, llvm::Instruction * >, 0 >, llvm::SmallVector< llvm::SmallVector< Entry, 8 >, 4 >, llvm::SmallVector< bool >, llvm::SmallVector< llvm::SDNode *, 128 >, llvm::SmallVector< EdgeType *, 0 >, llvm::SmallVector< llvm::ValueAsMetadata *, 4 >, llvm::SmallVector< llvm::TypedTrackingMDRef, 4 >, llvm::SmallVector< llvm::DISubprogram *, 4 >, llvm::SmallVector< llvm::Metadata *, 4 >, llvm::SmallVector< std::pair< llvm::MDNode *, llvm::SetVector< llvm::Metadata * > >, 0 >, llvm::SmallVector< llvm::DIEAbbrevData, 12 >, llvm::SmallVector< llvm::DILineInfo, 4 >, llvm::SmallVector< TypeUnitMetaInfo, 1 >, llvm::SmallVector< AttributeSpec, 8 >, llvm::SmallVector< llvm::DWARFFormValue, 3 >, llvm::SmallVector< LocationList, 4 >, llvm::SmallVector< llvm::DWARFLocationEntry, 2 >, llvm::SmallVector< Entry, 4 >, llvm::SmallVector< llvm::DWARFDebugNames::NameIndex, 0 >, llvm::SmallVector< uint64_t >, llvm::SmallVector< Encoding >, llvm::SmallVector< CompUnitEntry, 0 >, llvm::SmallVector< TypeUnitEntry, 0 >, llvm::SmallVector< AddressEntry, 0 >, llvm::SmallVector< SymTableEntry, 0 >, llvm::SmallVector< std::pair< uint32_t, llvm::SmallVector< uint32_t, 0 > >, 0 >, llvm::SmallVector< uint8_t, 4 >, llvm::SmallVector< llvm::dxbc::PSV::v2::ResourceBindInfo >, llvm::SmallVector< llvm::DXContainerYAML::SignatureElement >, llvm::SmallVector< llvm::yaml::Hex32 >, llvm::SmallVector< llvm::DXContainerYAML::SignatureParameter >, llvm::SmallVector< unsigned char, 8 >, llvm::SmallVector< LayoutAlignElem, 4 >, llvm::SmallVector< PointerAlignElem, 8 >, llvm::SmallVector< unsigned, 8 >, llvm::SmallVector< std::pair< InlinedEntity, const MachineInstr * >, 0 >, llvm::SmallVector< std::pair< InlinedEntity, Entries >, 0 >, llvm::SmallVector< llvm::DbgValueLocEntry, 2 >, llvm::SmallVector< int64_t, 1 >, llvm::SmallVector< llvm::DICompileUnit *, 8 >, llvm::SmallVector< llvm::DISubprogram *, 8 >, llvm::SmallVector< llvm::DIGlobalVariableExpression *, 8 >, llvm::SmallVector< llvm::DIType *, 8 >, llvm::SmallVector< llvm::DIScope *, 8 >, llvm::SmallVector< llvm::DbgValueLoc, 1 >, llvm::SmallVector< llvm::DebugLocStream::List, 4 >, llvm::SmallVector< llvm::DebugLocStream::Entry, 32 >, llvm::SmallVector< std::string, 1 >, llvm::SmallVector< llvm::Init *, 16 >, llvm::SmallVector< llvm::DiagnosticInfoOptimizationBase::Argument, 4 >, llvm::SmallVector< NodeType *, 10 >, llvm::SmallVector< unsigned, 4 >, llvm::SmallVector< llvm::DomTreeNodeBase, 8 >, llvm::SmallVector< DominatorTree::UpdateType, 16 >, llvm::SmallVector< NodeT *, IsPostDom ? 4 :1 >, llvm::SmallVector< llvm::RangeSpan, 2 >, llvm::SmallVector< const MDNode *, 4 >, llvm::SmallVector< std::pair< const llvm::MDNode *, llvm::DwarfCompileUnit * >, 0 >, llvm::SmallVector< std::unique_ptr< llvm::DbgEntity >, 64 >, llvm::SmallVector< std::pair< std::unique_ptr< llvm::DwarfTypeUnit >, const llvm::DICompositeType * >, 1 >, llvm::SmallVector< llvm::DwarfExpression::Register, 2 >, llvm::SmallVector< std::unique_ptr< llvm::DwarfCompileUnit >, 1 >, llvm::SmallVector< llvm::RangeSpanList, 1 >, llvm::SmallVector< llvm::DbgVariable *, 8 >, llvm::SmallVector< llvm::SmallVector< unsigned, 8 >, 4 >, llvm::SmallVector< std::string, 4 >, llvm::SmallVector< llvm::Function *, 4 >, llvm::SmallVector< std::unique_ptr< llvm::GlobalVariable >, 32 >, llvm::SmallVector< MutableValue >, llvm::SmallVector< llvm::DomainValue *, 16 >, llvm::SmallVector< LiveRegsDVInfo, 4 >, llvm::SmallVector< std::unique_ptr< llvm::Module >, 1 >, llvm::SmallVector< llvm::GlobalValue *, 0 >, llvm::SmallVector< llvm::Value *, 16 >, llvm::SmallVector< llvm::ISD::ArgFlagsTy, 16 >, llvm::SmallVector< llvm::Register, 16 >, llvm::SmallVector< llvm::ISD::InputArg, 4 >, llvm::SmallVector< std::pair< llvm::Instruction *, llvm::ConstantRange >, 0 >, llvm::SmallVector< llvm::Instruction *, N >, llvm::SmallVector< std::pair< llvm::Instruction *, llvm::Value * >, 0 >, llvm::SmallVector< unsigned, 32 >, llvm::SmallVector< T *, 8 >, llvm::SmallVector< unsigned, 50 >, llvm::SmallVector< llvm::FunctionLoweringInfo::LiveOutInfo, 0 >, llvm::SmallVector< llvm::BBClusterInfo >, llvm::SmallVector< llvm::SmallVector< unsigned > >, llvm::SmallVector< llvm::DebugVariable >, llvm::SmallVector< llvm::VarLocInfo >, llvm::SmallVector< std::unique_ptr< llvm::GCStrategy >, 1 >, llvm::SmallVector< GCNSchedStageID, 4 >, llvm::SmallVector< std::pair< llvm::MachineInstrBundleIterator, llvm::MachineInstrBundleIterator >, 32 >, llvm::SmallVector< llvm::DenseMap, 32 >, llvm::SmallVector< llvm::GCNRegPressure, 32 >, llvm::SmallVector< llvm::GCOVArc *, 2 >, llvm::SmallVector< std::unique_ptr< llvm::GCOVFunction >, 16 >, llvm::SmallVector< std::unique_ptr< llvm::GCOVBlock >, 0 >, llvm::SmallVector< std::unique_ptr< llvm::GCOVArc >, 0 >, llvm::SmallVector< llvm::LLT, 4 >, llvm::SmallVector< llvm::GISelChangeObserver *, 4 >, llvm::SmallVector< llvm::BasicBlock *, 32 >, llvm::SmallVector< std::pair< llvm::Value *, llvm::Value * >, N >, llvm::SmallVector< llvm::Instruction *, 8 >, llvm::SmallVector< std::pair< llvm::Instruction *, unsigned >, 4 >, llvm::SmallVector< BlockT *, 1 >, llvm::SmallVector< BlockT *, 8 >, llvm::SmallVector< const CycleT * >, llvm::SmallVector< SubGlobPattern, 1 >, llvm::SmallVector< llvm::GlobPattern::SubGlobPattern::Bracket, 0 >, llvm::SmallVector< char, 0 >, llvm::SmallVector< llvm::cfg::Update< NodePtr >, 4 >, llvm::SmallVector< NodePtr, 2 >, llvm::SmallVector< std::string, 0 >, llvm::SmallVector< HexagonInstr, HEXAGON_PRESHUFFLE_PACKET_SIZE >, llvm::SmallVector< llvm::HexagonInstr *, HEXAGON_PRESHUFFLE_PACKET_SIZE >, llvm::SmallVector< NodeTy *, IsPostDom ? 4 :1 >, llvm::SmallVector< llvm::cfg::Update< llvm::BasicBlock * >, 4 >, llvm::SmallVector< std::pair< unsigned, llvm::MDNode * >, 2 >, llvm::SmallVector< llvm::Value *, 4 >, llvm::SmallVector< int, 4 >, llvm::SmallVector< std::pair< const llvm::PHINode *, llvm::SmallVector< llvm::MachineInstr *, 1 > >, 4 >, llvm::SmallVector< llvm::Instruction * >, llvm::SmallVector< InlineGraphNode *, 8 >, llvm::SmallVector< uintptr_t, 20 >, llvm::SmallVector< Meta, static_cast< int >(Meta::Size)>, llvm::SmallVector< T, 0 >, llvm::SmallVector< const llvm::SCEV *, 3 >, llvm::SmallVector< llvm::Instruction *, 2 >, llvm::SmallVector< llvm::Function * >, llvm::SmallVector< const llvm::Instruction *, 0 >, llvm::SmallVector< Instruction *, 8 >, llvm::SmallVector< const char *, 0 >, llvm::SmallVector< llvm::AllocaInst *, 4 >, llvm::SmallVector< llvm::WeakTrackingVH, 8 >, llvm::SmallVector< llvm::CallBase *, 8 >, llvm::SmallVector< llvm::Instruction *, 4 >, llvm::SmallVector< std::pair< const llvm::RecurrenceDescriptor *, llvm::PHINode * >, N >, llvm::SmallVector< std::pair< llvm::SlotIndex, llvm::SlotIndex >, 8 >, llvm::SmallVector< llvm::TemporalProfTraceTy >, llvm::SmallVector< std::pair< uint64_t, llvm::memprof::IndexedMemProfRecord >, 0 >, llvm::SmallVector< std::pair< uint64_t, llvm::memprof::Frame >, 0 >, llvm::SmallVector< std::function< void(MachineInstrBuilder &)>, 4 >, llvm::SmallVector< llvm::InstructionBuildSteps, 2 >, llvm::SmallVector< llvm::Instruction *, 256 >, llvm::SmallVector< RegUnitInfo, 4 >, llvm::SmallVector< BlockInterference, 8 >, llvm::SmallVector< DataType, 4 >, llvm::SmallVector< PointType, 4 >, llvm::SmallVector< const DataType *, 4 >, llvm::SmallVector< llvm::Type *, 4 >, llvm::SmallVector< const llvm::Value *, 4 >, llvm::SmallVector< ScopeContext, 8 >, llvm::SmallVector< llvm::MCRegister >, llvm::SmallVector< llvm::Instruction *, 64 >, llvm::SmallVector< llvm::Loop *, N >, llvm::SmallVector< llvm::MCSymbol *, 1 >, llvm::SmallVector< llvm::SEHHandler, 1 >, llvm::SmallVector< llvm::LazyCallGraph::RefSCC *, 16 >, llvm::SmallVector< Edge, 4 >, llvm::SmallVector< llvm::LazyCallGraph::SCC *, 4 >, llvm::SmallVector< llvm::LazyCallGraph::Node *, 1 >, llvm::SmallVector< std::pair< llvm::BasicBlock *, llvm::Value * >, 8 >, llvm::SmallVector< llvm::DenseMap, 1 >, llvm::SmallVector< SizeChangeStrategy, 1 >, llvm::SmallVector< SizeAndActionsVec, 1 >, llvm::SmallVector< llvm::LegalizeRule, 2 >, llvm::SmallVector< std::pair< bool, llvm::StringRef >, 4 >, llvm::SmallVector< llvm::LexicalScope *, 4 >, llvm::SmallVector< InsnRange, 4 >, llvm::SmallVector< const llvm::LiveInterval *, 4 >, llvm::SmallVector< llvm::LiveInterval *, 0 >, llvm::SmallVector< llvm::SlotIndex, 8 >, llvm::SmallVector< const uint32_t *, 8 >, llvm::SmallVector< std::pair< unsigned, unsigned >, 8 >, llvm::SmallVector< llvm::LiveRange *, 0 >, llvm::SmallVector< MCPhysReg, 8 >, llvm::SmallVector< Segment, 2 >, llvm::SmallVector< VNInfo *, 2 >, llvm::SmallVector< LiveOutPair, 0 >, llvm::SmallVector< LiveInBlock, 16 >, llvm::SmallVector< llvm::LiveRange::Segment, 16 >, llvm::SmallVector< IndexMaskPair, 8 >, llvm::SmallVector< llvm::LiveVariables::VarInfo, 0 >, llvm::SmallVector< llvm::GStore * >, llvm::SmallVector< std::pair< llvm::MachineInstr *, unsigned > >, llvm::SmallVector< llvm::StoreInst * >, llvm::SmallVector< MBBInfo, 4 >, llvm::SmallVector< std::pair< llvm::Instruction *, uint64_t >, 0 >, llvm::SmallVector< std::pair< unsigned, unsigned >, N >, llvm::SmallVector< std::pair< PHINode *, RecurrenceDescriptor >, 0 >, llvm::SmallVector< std::pair< PHINode *, InductionDescriptor >, 0 >, llvm::SmallVector< VPlanPtr, 4 >, llvm::SmallVector< llvm::VectorizationFactor, 8 >, llvm::SmallVector< RuntimePointerCheck, 4 >, llvm::SmallVector< llvm::DebugLoc, N >, llvm::SmallVector< llvm::MCSection *, 16 >, llvm::SmallVector< llvm::AsmToken, 1 >, llvm::SmallVector< llvm::MCAsmParser::MCPendingError, 0 >, llvm::SmallVector< std::pair< const llvm::MCSymbol *, const llvm::MCSymbol * >, 2 >, llvm::SmallVector< std::pair< std::string, std::string >, 0 >, llvm::SmallVector< llvm::MCSection *, 0 >, llvm::SmallVector< std::string, 3 >, llvm::SmallVector< llvm::MCDwarfFile, 3 >, llvm::SmallVector< llvm::MCELFStreamer::AttributeItem, 64 >, llvm::SmallVector< llvm::MCDataFragment *, 4 >, llvm::SmallVector< llvm::MCOperand, 10 >, llvm::SmallVector< llvm::object::OwningBinary< llvm::object::Archive >, 2 >, llvm::SmallVector< std::unique_ptr< llvm::MemoryBuffer >, 2 >, llvm::SmallVector< std::unique_ptr< llvm::object::ObjectFile >, 2 >, llvm::SmallVector< llvm::MCLOHDirective, 32 >, llvm::SmallVector< llvm::MCSymbol *, 3 >, llvm::SmallVector< std::pair< MCSection *, MCDwarfLineEntryCollection >, 0 >, llvm::SmallVector< llvm::MCSymbol *, 2 >, llvm::SmallVector< llvm::MCSection *, N >, llvm::SmallVector< PendingMCFixup, 2 >, llvm::SmallVector< std::pair< unsigned, llvm::MCFragment * >, 1 >, llvm::SmallVector< PendingLabel, 2 >, llvm::SmallVector< std::pair< size_t, llvm::MCSection * >, 1 >, llvm::SmallVector< std::pair< MCSectionSubPair, MCSectionSubPair >, 4 >, llvm::SmallVector< llvm::MDAttachments::Attachment, 1 >, llvm::SmallVector< llvm::StringRef, 8 >, llvm::SmallVector< Target, 5 >, llvm::SmallVector< std::pair< llvm::MachO::ObjCIVarRecord, ValueT >, 0 >, llvm::SmallVector< std::pair< llvm::StringRef, llvm::MachO::ObjCCategoryRecord * >, 0 >, llvm::SmallVector< std::pair< llvm::MachO::GlobalRecord, ValueT >, 0 >, llvm::SmallVector< std::pair< llvm::MachO::ObjCInterfaceRecord, ValueT >, 0 >, llvm::SmallVector< std::pair< llvm::MachO::ObjCCategoryRecord, std::pair< llvm::StringRef, llvm::StringRef > >, 0 >, llvm::SmallVector< llvm::MachineBasicBlock *, IsPostDom ? 4 :1 >, llvm::SmallVector< CriticalEdge, 32 >, llvm::SmallVector< llvm::MachineBasicBlock *, N >, llvm::SmallVector< std::pair< int, int64_t >, 32 >, llvm::SmallVector< VariableDbgInfo, 4 >, llvm::SmallVector< llvm::MachineFunction::DebugSubstitution, 8 >, llvm::SmallVector< llvm::unique_function< FuncTy >, 4 >, llvm::SmallVector< llvm::StringRef, 0 >, llvm::SmallVector< llvm::MachineOperand, 4 >, llvm::SmallVector< std::pair< llvm::PointerUnion, llvm::MachineOperand * >, 0 >, llvm::SmallVector< std::pair< unsigned, llvm::SmallVector< llvm::Register, 4 > >, 0 >, llvm::SmallVector< LLT, 0 >, llvm::SmallVector< llvm::MachineTraceMetrics::FixedBlockInfo, 4 >, llvm::SmallVector< llvm::MachineTraceMetrics::TraceBlockInfo, 4 >, llvm::SmallVector< llvm::MachineTraceMetrics::LiveInReg, 4 >, llvm::SmallVector< std::pair< KeyT, ValueT >, 0 >, llvm::SmallVector< llvm::Instruction *, 16 >, llvm::SmallVector< llvm::MemoryDepChecker::Dependence, 8 >, llvm::SmallVector< llvm::WeakVH, 16 >, llvm::SmallVector< llvm::AssertingVH< llvm::MemoryPhi >, N >, llvm::SmallVector< Inst, 7 >, llvm::SmallVector< bool, 4 >, llvm::SmallVector< std::unique_ptr< llvm::MipsOptionRecord >, 8 >, llvm::SmallVector< llvm::MCSymbol *, 4 >, llvm::SmallVector< llvm::MachineInstr *, 2 >, llvm::SmallVector< const BlockT * >, llvm::SmallVector< std::unique_ptr< llvm::ScheduleHazardRecognizer >, 4 >, llvm::SmallVector< std::string, 8 >, llvm::SmallVector< llvm::Instruction *, NegatorMaxNodesSSO >, llvm::SmallVector< llvm::SUnit *, 0 >, llvm::SmallVector< llvm::OpenMPIRBuilder::FinalizationInfo, 8 >, llvm::SmallVector< llvm::OpenMPIRBuilder::OutlineInfo, 16 >, llvm::SmallVector< Value *, 4 >, llvm::SmallVector< DeviceInfoTy, 4 >, llvm::SmallVector< omp::OpenMPOffloadMappingFlags, 4 >, llvm::SmallVector< Constant *, 4 >, llvm::SmallVector< uint64_t, 4 >, llvm::SmallVector< MapValuesArrayTy, 4 >, llvm::SmallVector< std::pair< const llvm::Value *, std::pair< llvm::Value *, llvm::Value * > >, N >, llvm::SmallVector< llvm::Pass *, 16 >, llvm::SmallVector< llvm::PMDataManager *, 8 >, llvm::SmallVector< llvm::ImmutablePass *, 16 >, llvm::SmallVector< llvm::SUnit *, 7 >, llvm::SmallVector< ParamType, 32 >, llvm::SmallVector< llvm::Register, 3 >, llvm::SmallVector< T *, 0 >, llvm::SmallVector< std::function< void(llvm::PassManager &, llvm::OptimizationLevel)>, 2 >, llvm::SmallVector< std::function< void(llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > &, llvm::OptimizationLevel)>, 2 >, llvm::SmallVector< std::function< void(PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & > &, llvm::OptimizationLevel)>, 2 >, llvm::SmallVector< std::function< void(llvm::AnalysisManager &)>, 2 >, llvm::SmallVector< std::function< bool(llvm::StringRef, llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)>, 2 >, llvm::SmallVector< std::function< bool(llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)>, 2 >, llvm::SmallVector< std::function< bool(llvm::StringRef, PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & > &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)>, 2 >, llvm::SmallVector< std::function< bool(llvm::StringRef, llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)>, 2 >, llvm::SmallVector< std::function< bool(llvm::StringRef Name, llvm::AAManager &AA)>, 2 >, llvm::SmallVector< std::function< void(llvm::MachineFunctionAnalysisManager &)>, 2 >, llvm::SmallVector< std::function< bool(llvm::StringRef, llvm::MachineFunctionPassManager &)>, 2 >, llvm::SmallVector< InsertedPass, 4 >, llvm::SmallVector< llvm::unique_function< BeforePassFunc >, 4 >, llvm::SmallVector< llvm::unique_function< BeforeSkippedPassFunc >, 4 >, llvm::SmallVector< llvm::unique_function< BeforeNonSkippedPassFunc >, 4 >, llvm::SmallVector< llvm::unique_function< AfterPassFunc >, 4 >, llvm::SmallVector< llvm::unique_function< AfterPassInvalidatedFunc >, 4 >, llvm::SmallVector< llvm::unique_function< BeforeAnalysisFunc >, 4 >, llvm::SmallVector< llvm::unique_function< AfterAnalysisFunc >, 4 >, llvm::SmallVector< llvm::unique_function< AnalysisInvalidatedFunc >, 4 >, llvm::SmallVector< llvm::unique_function< AnalysesClearedFunc >, 4 >, llvm::SmallVector< llvm::MachineBasicBlock *, 4 >, llvm::SmallVector< llvm::MachineInstr *, 4 >, llvm::SmallVector< DDGNode *, 4 >, llvm::SmallVector< MemberTy, N >, llvm::SmallVector< std::pair< unsigned, llvm::MapVector< llvm::MachineInstr *, llvm::MachineInstr * > >, 0 >, llvm::SmallVector< llvm::AssertingVH< llvm::Function >, N >, llvm::SmallVector< ValueInfo, 32 >, llvm::SmallVector< llvm::PredicateBase *, 4 >, llvm::SmallVector< char, 32 >, llvm::SmallVector< PassRunDescriptor, 2 >, llvm::SmallVector< llvm::SpillPlacement::BlockConstraint, 8 >, llvm::SmallVector< GlobalSplitCandidate, 32 >, llvm::SmallVector< const llvm::LiveInterval *, N >, llvm::SmallVector< RegInfo, 0 >, llvm::SmallVector< llvm::Register, 8 >, llvm::SmallVector< llvm::Type *, 16 >, llvm::SmallVector< TraversedMBBInfo, 4 >, llvm::SmallVector< LiveRegsDefInfo, 4 >, llvm::SmallVector< MBBDefsInfo, 4 >, llvm::SmallVector< llvm::SMLoc, 4 >, llvm::SmallVector< llvm::SMLoc, 0 >, llvm::SmallVector< llvm::SMRange, 0 >, llvm::SmallVector< llvm::Init *, 0 >, llvm::SmallVector< llvm::RecordVal, 0 >, llvm::SmallVector< llvm::Record::AssertionInfo, 0 >, llvm::SmallVector< llvm::Record::DumpInfo, 0 >, llvm::SmallVector< std::pair< llvm::Record *, llvm::SMRange >, 0 >, llvm::SmallVector< llvm::Init *, 4 >, llvm::SmallVector< llvm::SMRange >, llvm::SmallVector< std::unique_ptr< InsertPoint >, 2 >, llvm::SmallVector< ScavengedInfo, 2 >, llvm::SmallVector< int, 8 >, llvm::SmallVector< uint16_t, 4 >, llvm::SmallVector< llvm::RegisterMaskPair, 8 >, llvm::SmallVector< llvm::EVT, 4 >, llvm::SmallVector< llvm::MVT, 4 >, llvm::SmallVector< std::unique_ptr< llvm::DFAPacketizer > >, llvm::SmallVector< llvm::SmallVector< uint64_t, DefaultProcResSize > >, llvm::SmallVector< uint64_t, DefaultProcResSize >, llvm::SmallVector< NodeRef, 8 >, llvm::SmallVector< SID, 2 >, llvm::SmallVector< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry >, 8 >, llvm::SmallVector< IFuncStub, 2 >, llvm::SmallVector< llvm::RuntimeDyldMachO::EHFrameRelatedSections, 2 >, llvm::SmallVector< llvm::RuntimePointerChecking::PointerInfo, 2 >, llvm::SmallVector< llvm::RuntimeCheckingPtrGroup, 2 >, llvm::SmallVector< llvm::PointerDiffInfo >, llvm::SmallVector< std::pair< llvm::Function *, llvm::ValueLatticeElement >, 0 >, llvm::SmallVector< std::pair< std::pair< llvm::Function *, unsigned >, llvm::ValueLatticeElement >, 0 >, llvm::SmallVector< llvm::Value *, 64 >, llvm::SmallVector< llvm::BasicBlock *, 64 >, llvm::SmallVector< llvm::WeakVH, 2 >, llvm::SmallVector< SCEVInsertPointGuard *, 8 >, llvm::SmallVector< const llvm::SCEV *, 8 >, llvm::SmallVector< const llvm::SCEVPredicate *, 16 >, llvm::SmallVector< llvm::SDDbgValue *, 32 >, llvm::SmallVector< llvm::SDDbgLabel *, 4 >, llvm::SmallVector< llvm::MachineInstr *, 0 >, llvm::SmallVector< uint8_t, 0 >, llvm::SmallVector< std::pair< Register, int >, 0 >, llvm::SmallVector< Register, N >, llvm::SmallVector< uint16_t, 32 >, llvm::SmallVector< std::pair< Value *, StoreList >, 0 >, llvm::SmallVector< std::pair< Value *, GEPList >, 0 >, llvm::SmallVector< llvm::SMFixIt, 4 >, llvm::SmallVector< llvm::SPIRV::DTSortableEntry *, 2 >, llvm::SmallVector< MachineInstr * >, llvm::SmallVector< SPIRV::Capability::Capability, 8 >, llvm::SmallVector< Capability::Capability, N >, llvm::SmallVector< Extension::Extension, N >, llvm::SmallVector< std::pair< KeyTy, SPIRV::DTSortableEntry >, 0 >, llvm::SmallVector< std::pair< const llvm::Type *, SPIRV::DTSortableEntry >, 0 >, llvm::SmallVector< std::pair< const llvm::Constant *, SPIRV::DTSortableEntry >, 0 >, llvm::SmallVector< std::pair< const llvm::GlobalVariable *, SPIRV::DTSortableEntry >, 0 >, llvm::SmallVector< std::pair< const llvm::Function *, SPIRV::DTSortableEntry >, 0 >, llvm::SmallVector< std::pair< const llvm::Argument *, SPIRV::DTSortableEntry >, 0 >, llvm::SmallVector< std::pair< const llvm::SPIRV::SpecialTypeDescriptor *, SPIRV::DTSortableEntry >, 0 >, llvm::SmallVector< SPIRV::Extension::Extension, N >, llvm::SmallVector< SPIRV::InstructionSet::InstructionSet, N >, llvm::SmallVector< RewriteInfo, 4 >, llvm::SmallVector< llvm::Use *, 4 >, llvm::SmallVector< llvm::SDep, 4 >, llvm::SmallVector< ExitNotTakenInfo, 1 >, llvm::SmallVector< unsigned, 16 >, llvm::SmallVector< llvm::APInt, 16 >, llvm::SmallVector< RootData, 8 >, llvm::SmallVector< TreeData, 16 >, llvm::SmallVector< SMSNode, 8 >, llvm::SmallVector< std::pair< llvm::SUnit *, llvm::SUnit * >, 16 >, llvm::SmallVector< llvm::sys::MemoryBlock, 16 >, llvm::SmallVector< FreeMemBlock, 16 >, llvm::SmallVector< std::pair< const llvm::Value *, DanglingDebugInfoVector >, 0 >, llvm::SmallVector< llvm::SDValue, 8 >, llvm::SmallVector< const llvm::Value *, 16 >, llvm::SmallVector< const llvm::GCRelocateInst *, 16 >, llvm::SmallVector< IdxMBBPair, 8 >, llvm::SmallVector< ValueT, 8 >, llvm::SmallVector< llvm::CallBase * >, llvm::SmallVector< llvm::ArgInfo, 4 >, llvm::SmallVector< llvm::BlockFrequency, 8 >, llvm::SmallVector< llvm::SplitAnalysis::BlockInfo, 8 >, llvm::SmallVector< const llvm::IntrinsicInst *, 64 >, llvm::SmallVector< llvm::StackLifetime::LiveRange, 8 >, llvm::SmallVector< std::pair< uint64_t, uint64_t >, 0 >, llvm::SmallVector< std::pair< const MCSymbol *, FunctionInfo >, 0 >, llvm::SmallVector< Location, 8 >, llvm::SmallVector< LiveOutReg, 8 >, llvm::SmallVector< const llvm::GCRelocateInst *, 10 >, llvm::SmallVector< llvm::ArgumentInit *, 4 >, llvm::SmallVector< llvm::IRPosition, 4 >, llvm::SmallVector< llvm::SuffixTreeInternalNode * >, llvm::SmallVector< const Value *, 1 >, llvm::SmallVector< llvm::SmallPtrSet< llvm::SUnit *, 4 >, 10 >, llvm::SmallVector< llvm::SmallVector< int, 4 >, 16 >, llvm::SmallVector< BitTestCase, 3 >, llvm::SmallVector< std::pair< std::pair< const MCSymbol *, unsigned >, uint32_t >, 0 >, llvm::SmallVector< llvm::DefsetRecord *, 2 >, llvm::SmallVector< std::pair< GlobalVariable *, tlshoist::TLSCandidate >, 0 >, llvm::SmallVector< llvm::ISD::OutputArg, 32 >, llvm::SmallVector< llvm::SDValue, 32 >, llvm::SmallVector< llvm::ISD::InputArg, 32 >, llvm::SmallVector< llvm::SDValue, 4 >, llvm::SmallVector< llvm::Timer *, 8 >, llvm::SmallVector< TimeTraceProfilerEntry, 16 >, llvm::SmallVector< TimeTraceProfilerEntry, 128 >, llvm::SmallVector< llvm::TruncInst *, 4 >, llvm::SmallVector< std::pair< llvm::Instruction *, Info >, 0 >, llvm::SmallVector< uint8_t, 32 >, llvm::SmallVector< llvm::VFInfo, 8 >, llvm::SmallVector< llvm::VFParameter, 8 >, llvm::SmallVector< llvm::SUnit * >, llvm::SmallVector< llvm::VPBlockBase *, 1 >, llvm::SmallVector< llvm::VPHeaderPHIRecipe *, 4 >, llvm::SmallVector< llvm::VPValue *, 2 >, llvm::SmallVector< llvm::VPUser *, 1 >, llvm::SmallVector< llvm::VPBasicBlock *, 2 >, llvm::SmallVector< llvm::ElementCount, N >, llvm::SmallVector< llvm::VPValue *, 16 >, llvm::SmallVector< std::pair< llvm::PHINode *, llvm::VPLiveOut * >, 0 >, llvm::SmallVector< VPBlockBase *, IsPostDom ? 4 :1 >, llvm::SmallVector< MultiNodeOpTy, 4 >, llvm::SmallVector< llvm::Register, 0 >, llvm::SmallVector< wasm::ValType, 8 >, llvm::SmallVector< llvm::SmallVector< wasm::ValType, 4 >, 8 >, llvm::SmallVector< wasm::ValType, 16 >, llvm::SmallVector< wasm::ValType, 4 >, llvm::SmallVector< llvm::MachineInstr *, 1 >, llvm::SmallVector< std::pair< uint64_t, bool >, 4 >, llvm::SmallVector< EHInstKind, 4 >, llvm::SmallVector< std::pair< llvm::MCSymbol *, llvm::WinEH::FrameInfo::Epilog >, 0 >, llvm::SmallVector< std::pair< llvm::MCSymbol *, int64_t >, 0 >, llvm::SmallVector< llvm::CxxUnwindMapEntry, 4 >, llvm::SmallVector< llvm::WinEHTryBlockMapEntry, 4 >, llvm::SmallVector< llvm::SEHUnwindMapEntry, 4 >, llvm::SmallVector< llvm::ClrEHUnwindMapEntry, 4 >, llvm::SmallVector< llvm::WinEHHandlerType, 1 >, llvm::SmallVector< size_t, 0 >, llvm::SmallVector< llvm::SmallVector< size_t, 4 >, 0 >, llvm::SmallVector< llvm::cl::OptionCategory *, 1 >, llvm::SmallVector< llvm::cl::Option *, 4 >, llvm::SmallVector< llvm::cl::SubCommand *, 4 >, llvm::SmallVector< llvm::cl::OptionEnumValue, 4 >, llvm::SmallVector< llvm::ArrayRef< uint8_t >, 2 >, llvm::SmallVector< llvm::codeview::TypeIndex, MaxArgs >, llvm::SmallVector< RecordLimit, 2 >, llvm::SmallVector< llvm::codeview::GloballyHashedType, 2 >, llvm::SmallVector< ConstantUser, 8 >, llvm::SmallVector< RebasedConstantInfo, 4 >, llvm::SmallVector< llvm::AnyCoroEndInst *, 4 >, llvm::SmallVector< llvm::CoroSizeInst *, 2 >, llvm::SmallVector< llvm::CoroAlignInst *, 2 >, llvm::SmallVector< llvm::AnyCoroSuspendInst *, 4 >, llvm::SmallVector< llvm::CallInst *, 2 >, llvm::SmallVector< const llvm::coverage::CoverageSegment *, 4 >, llvm::SmallVector< TestVector >, llvm::SmallVector< llvm::detail::PtrUseVisitorBase::UseToVisit, 8 >, llvm::SmallVector< uint64_t, MaxOperands >, llvm::SmallVector< PatchLocation >, llvm::SmallVector< AccelTableKind, 1 >, llvm::SmallVector< llvm::dwarf_linker::parallel::CompileUnit::DIEInfo >, llvm::SmallVector< llvm::StringMapEntry * >, llvm::SmallVector< uint64_t * >, llvm::SmallVector< std::unique_ptr< llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext > >, llvm::SmallVector< std::unique_ptr< CompileUnit > >, llvm::SmallVector< RefModuleUnit >, llvm::SmallVector< DWARFLinkerBase::AccelTableKind, 1 >, llvm::SmallVector< LiveRootWorklistItemTy >, llvm::SmallVector< const llvm::StringMapEntry * >, llvm::SmallVector< llvm::dxil::UAVResource >, llvm::SmallVector< llvm::dxil::ConstantBuffer >, llvm::SmallVector< llvm::fuzzerop::SourcePred, 2 >, llvm::SmallVector< SmallVector< uint64_t, 4 >, 4 >, llvm::SmallVector< ElemT, 4 >, llvm::SmallVector< llvm::jitlink::ppc64::PLTCallStubReloc, 2 >, llvm::SmallVector< State, 16 >, llvm::SmallVector< LVLine *, 8 >, llvm::SmallVector< LVScope *, 8 >, llvm::SmallVector< LVSymbol *, 8 >, llvm::SmallVector< LVType *, 8 >, llvm::SmallVector< LVElement *, 8 >, llvm::SmallVector< LVTotalsEntry >, llvm::SmallVector< uint64_t, 16 >, llvm::SmallVector< std::pair< StringRef, BitcodeModule >, 0 >, llvm::SmallVector< EncodingInfo, 16 >, llvm::SmallVector< std::unique_ptr< llvm::mca::HardwareUnit >, 4 >, llvm::SmallVector< std::unique_ptr< llvm::mca::Instruction >, 16 >, llvm::SmallVector< llvm::mca::InstRef, 4 >, llvm::SmallVector< uint64_t, 8 >, llvm::SmallVector< llvm::mca::WriteDescriptor, 2 >, llvm::SmallVector< llvm::mca::ReadDescriptor, 4 >, llvm::SmallVector< std::pair< uint64_t, llvm::mca::ResourceUsage >, 4 >, llvm::SmallVector< llvm::mca::WriteState, 2 >, llvm::SmallVector< llvm::mca::ReadState, 4 >, llvm::SmallVector< ResourceUse, 4 >, llvm::SmallVector< llvm::mca::MemoryGroup *, 4 >, llvm::SmallVector< llvm::mca::InstRef, 8 >, llvm::SmallVector< std::unique_ptr< llvm::mca::Stage >, 8 >, llvm::SmallVector< RegisterMappingTracker, 4 >, llvm::SmallVector< std::pair< llvm::mca::ReadState *, int >, 4 >, llvm::SmallVector< llvm::mcdxbc::PSVSignatureElement >, llvm::SmallVector< Parameter >, llvm::SmallVector< llvm::memprof::Frame >, llvm::SmallVector< llvm::memprof::IndexedAllocationInfo >, llvm::SmallVector< llvm::SmallVector< uint64_t > >, llvm::SmallVector< llvm::memprof::AllocationInfo >, llvm::SmallVector< llvm::SmallVector< llvm::memprof::Frame > >, llvm::SmallVector< SegmentEntry, 2 >, llvm::SmallVector< std::pair< uint64_t, MemInfoBlock >, 0 >, llvm::SmallVector< llvm::IntrinsicInst *, 2 >, llvm::SmallVector< llvm::DbgVariableIntrinsic *, 2 >, llvm::SmallVector< std::pair< llvm::AllocaInst *, llvm::memtag::AllocaInfo >, 0 >, llvm::SmallVector< uint8_t, 128 >, llvm::SmallVector< llvm::objcopy::elf::SectionBase *, 3 >, llvm::SmallVector< SectionInfo, 32 >, llvm::SmallVector< NodeState, 16 >, llvm::SmallVector< const uint8_t *, 0 >, llvm::SmallVector< llvm::object::DataRefImpl, 256 >, llvm::SmallVector< const char *, 1 >, llvm::SmallVector< LoadCommandInfo, 4 >, llvm::SmallVector< StringRef, 1 >, llvm::SmallVector< std::pair< llvm::StringRef, llvm::StringRef >, 0 >, llvm::SmallVector< llvm::object::PGOAnalysisMap::PGOBBEntry::SuccessorEntry, 2 >, llvm::SmallVector< TraitProperty, 8 >, llvm::SmallVector< const char *, 2 >, llvm::SmallVector< Arg *, 16 >, llvm::SmallVector< std::unique_ptr< llvm::opt::Arg >, 16 >, llvm::SmallVector< llvm::StringLiteral >, llvm::SmallVector< const char *, 16 >, llvm::SmallVector< std::pair< std::string, llvm::orc::ExecutorAddr > >, llvm::SmallVector< std::tuple< ExecutorAddr, ExecutorAddr, MachOExecutorSymbolFlags > >, llvm::SmallVector< llvm::orc::ExecutorAddrRange >, llvm::SmallVector< char, 24 >, llvm::SmallVector< InjectedSourceDescriptor, 2 >, llvm::SmallVector< const llvm::TargetRegisterClass * >, llvm::SmallVector< uint32_t, 0 >, llvm::SmallVector< llvm::remarks::BitstreamRemarkParserHelper::Argument, 8 >, llvm::SmallVector< char, 1024 >, llvm::SmallVector< uint64_t, 64 >, llvm::SmallVector< llvm::remarks::Argument, 5 >, llvm::SmallVector< StackRegion, 16 >, llvm::SmallVector< StackObject, 8 >, llvm::SmallVector< std::pair< llvm::sampleprof::FunctionId, uint32_t >, 0 >, llvm::SmallVector< llvm::sampleprof::SecHdrTableEntry, 8 >, llvm::SmallVector< std::pair< llvm::sampleprof::SampleContext, uint64_t >, 0 >, llvm::SmallVector< std::pair< llvm::sampleprof::SampleContext, uint32_t >, 0 >, llvm::SmallVector< const SamplesWithLoc *, 20 >, llvm::SmallVector< std::unique_ptr< TreeEntry >, 8 >, llvm::SmallVector< const TreeEntry *, 0 >, llvm::SmallVector< ExternalUser, 16 >, llvm::SmallVector< std::pair< llvm::BasicBlock *, std::unique_ptr< BlockScheduling > >, 0 >, llvm::SmallVector< std::unique_ptr< ScheduleData[]> >, llvm::SmallVector< ScheduleData *, 0 >, llvm::SmallVector< ScheduleData *, 4 >, llvm::SmallVector< Value *, 8 >, llvm::SmallVector< llvm::slpvectorizer::BoUpSLP::EdgeInfo, 1 >, llvm::SmallVector< SmallVector< Value *, 8 >, 2 >, llvm::SmallVector< llvm::SmallVector, 4 >, llvm::SmallVector< const MMap * >, llvm::SmallVector< llvm::StringRef >, llvm::SmallVector< llvm::symbolize::MarkupNode >, llvm::SmallVector< llvm::tlshoist::TLSUser, 8 >, llvm::SmallVector< IntrusiveRefCntPtr< FileSystem >, 1 >, llvm::SmallVector< llvm::vfs::RedirectingFileSystem::Entry *, 32 >, llvm::SmallVector< ValType, 1 >, llvm::SmallVector< ValType, 4 >, llvm::SmallVector< TrieNode *, 4 >, llvm::SmallVector< llvm::yaml::StringValue >, llvm::SmallVector< SimpleKey, 4 >, and llvm::SmallVector< T, N >.
Public Types
using iterator = typename SuperClass::iterator
using const_iterator = typename SuperClass::const_iterator
using reference = typename SuperClass::reference
using size_type = typename SuperClass::size_type
Public Types inherited from llvm::SmallVectorTemplateCommon< T, typename >
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using reverse_iterator = std::reverse_iterator< iterator >
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Public Member Functions
SmallVectorImpl (const SmallVectorImpl &)=delete
void clear ()
void resize (size_type N)
void resize_for_overwrite (size_type N)
Like resize, but T is POD, the new values won't be initialized.
void truncate (size_type N)
Like resize, but requires that N is less than size().
void resize (size_type N, ValueParamT NV)
void reserve (size_type N)
void pop_back_n (size_type NumItems)
T pop_back_val ()
void swap (SmallVectorImpl &RHS)
template<typename ItTy , typename = EnableIfConvertibleToInputIterator<ItTy>>
void append (ItTy in_start, ItTy in_end)
Add the specified range to the end of the SmallVector.
void append (size_type NumInputs, ValueParamT Elt)
Append NumInputs copies of Elt to the end.
void append (std::initializer_list< T > IL)
void append (const SmallVectorImpl &RHS)
void assign (size_type NumElts, ValueParamT Elt)
template<typename ItTy , typename = EnableIfConvertibleToInputIterator<ItTy>>
void assign (ItTy in_start, ItTy in_end)
void assign (std::initializer_list< T > IL)
void assign (const SmallVectorImpl &RHS)
iterator erase (const_iterator CI)
iterator erase (const_iterator CS, const_iterator CE)
iterator insert (iterator I, T &&Elt)
iterator insert (iterator I, const T &Elt)
iterator insert (iterator I, size_type NumToInsert, ValueParamT Elt)
template<typename ItTy , typename = EnableIfConvertibleToInputIterator<ItTy>>
iterator insert (iterator I, ItTy From, ItTy To)
void insert (iterator I, std::initializer_list< T > IL)
template<typename... ArgTypes>
reference emplace_back (ArgTypes &&... Args)
SmallVectorImpl & operator= (const SmallVectorImpl &RHS)
SmallVectorImpl & operator= (SmallVectorImpl &&RHS)
bool operator== (const SmallVectorImpl &RHS) const
bool operator!= (const SmallVectorImpl &RHS) const
bool operator< (const SmallVectorImpl &RHS) const
bool operator> (const SmallVectorImpl &RHS) const
bool operator<= (const SmallVectorImpl &RHS) const
bool operator>= (const SmallVectorImpl &RHS) const
Public Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
void push_back (const T &Elt)
void push_back (T &&Elt)
void pop_back ()
Public Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
size_t size () const
size_t capacity () const
bool empty () const
Protected Types
using ValueParamT = typename SuperClass::ValueParamT
Protected Types inherited from llvm::SmallVectorTemplateBase< T, bool >
using ValueParamT = const T &
Protected Member Functions
SmallVectorImpl (unsigned N)
void assignRemote (SmallVectorImpl &&RHS)
~SmallVectorImpl ()
Protected Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
T * mallocForGrow (size_t MinSize, size_t &NewCapacity)
Create a new allocation big enough for MinSize and pass back its size in NewCapacity.
void moveElementsForGrow (T *NewElts)
Move existing elements over to the new allocation NewElts, the middle section of grow().
void takeAllocationForGrow (T *NewElts, size_t NewCapacity)
Transfer ownership of the allocation, finishing up grow().
const T * reserveForParamAndGetAddress (const T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
T * reserveForParamAndGetAddress (T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
void growAndAssign (size_t NumElts, const T &Elt)
template<typename... ArgTypes>
T & growAndEmplaceBack (ArgTypes &&... Args)
Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
void * getFirstEl () const
Find the address of the first element.
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSize, size_t TSize)
bool isSmall () const
Return true if this is a smallvector which has not had dynamic memory allocated for it.
void resetToSmall ()
Put this vector in a state of being small.
bool isReferenceToRange (const void *V, const void *First, const void *Last) const
Return true if V is an internal reference to the given range.
bool isReferenceToStorage (const void *V) const
Return true if V is an internal reference to this vector.
bool isRangeInStorage (const void *First, const void *Last) const
Return true if First and Last form a valid (possibly empty) range in this vector's storage.
bool isSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Return true unless Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Check whether Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToAdd (const void *Elt, size_t N=1)
Check whether Elt will be invalidated by increasing the size of the vector by N.
void assertSafeToReferenceAfterClear (const T *From, const T *To)
Check whether any part of the range will be invalidated by clearing.
template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToReferenceAfterClear (ItTy, ItTy)
void assertSafeToAddRange (const T *From, const T *To)
Check whether any part of the range will be invalidated by growing.
template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToAddRange (ItTy, ItTy)
Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void * mallocForGrow (void *FirstEl, size_t MinSize, size_t TSize, size_t &NewCapacity)
This is a helper for grow() that's out of line to reduce code duplication.
void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
void * replaceAllocation (void *NewElts, size_t TSize, size_t NewCapacity, size_t VSize=0)
If vector was first created with capacity 0, getFirstEl() points to the memory right after, an area unallocated.
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
void set_allocation_range (void *Begin, size_t N)
Set the array data pointer to Begin and capacity to N.
Additional Inherited Members
Static Protected Member Functions inherited from llvm::SmallVectorTemplateBase< T, bool >
static void destroy_range (T *S, T *E)
template<typename It1 , typename It2 >
static void uninitialized_move (It1 I, It1 E, It2 Dest)
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
static T && forward_value_param (T &&V)
static const T & forward_value_param (const T &V)
Static Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
template<class U >
static const T * reserveForParamAndGetAddressImpl (U *This, const T &Elt, size_t N)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Static Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
Protected Attributes inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
void * BeginX
SmallVectorSizeType< T > Size
SmallVectorSizeType< T > Capacity
Static Protected Attributes inherited from llvm::SmallVectorTemplateBase< T, bool >
static constexpr bool TakesParamByValue = false
Detailed Description
template<typename T>
class llvm::SmallVectorImpl< T >
This class consists of common code factored out of the SmallVector class to reduce code duplication based on the SmallVector 'N' template parameter.
Definition at line 586 of file SmallVector.h.
Member Typedef Documentation
const_iterator
template<typename T > using llvm::SmallVectorImpl< T >::const_iterator = typename SuperClass::const_iterator
Definition at line 591 of file SmallVector.h.
iterator
template<typename T > using llvm::SmallVectorImpl< T >::iterator = typename SuperClass::iterator
Definition at line 590 of file SmallVector.h.
reference
template<typename T > using llvm::SmallVectorImpl< T >::reference = typename SuperClass::reference
Definition at line 592 of file SmallVector.h.
size_type
template<typename T > using llvm::SmallVectorImpl< T >::size_type = typename SuperClass::size_type
Definition at line 593 of file SmallVector.h.
ValueParamT
template<typename T > using llvm::SmallVectorImpl< T >::ValueParamT = typename SuperClass::ValueParamT protected
Definition at line 597 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorImpl() [1/2]
template<typename T > llvm::SmallVectorImpl< T >::SmallVectorImpl (unsigned N) inline explicit protected
Definition at line 600 of file SmallVector.h.
~SmallVectorImpl()
template<typename T > llvm::SmallVectorImpl< T >::~SmallVectorImpl () inline protected
Definition at line 613 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::isSmall().
SmallVectorImpl() [2/2]
template<typename T > llvm::SmallVectorImpl< T >::SmallVectorImpl (const SmallVectorImpl< T > &) delete
Member Function Documentation
append() [1/4]
template<typename T > void llvm::SmallVectorImpl< T >::append (const SmallVectorImpl< T > & RHS) inline
Definition at line 715 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append(), and RHS.
Referenced by llvm::SmallVectorImpl< T >::append().
append() [2/4]
template<typename T > template<typename ItTy , typename = EnableIfConvertibleToInputIterator<ItTy>> void llvm::SmallVectorImpl< T >::append (ItTy in_start, ItTy in_end) inline
Add the specified range to the end of the SmallVector.
Definition at line 696 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToAddRange(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::size(), and llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy().
Referenced by llvm::opt::ArgList::AddAllArgValues(), addAllGlobalValueUsers(), llvm::MachineInstr::addMemOperand(), llvm::logicalview::LVScope::addMissingElements(), llvm::FoldingSetNodeID::AddNodeID(), llvm::RecurrenceDescriptor::AddReductionVar(), llvm::FoldingSetNodeID::AddString(), llvm::CodeViewContext::addToStringTable(), llvm::DebugLocEntry::addValues(), analyzeLoopUnrollCost(), llvm::DIExpression::append(), llvm::RegsForValue::append(), llvm::OpenMPIRBuilder::MapInfosTy::append(), llvm::sys::path::append(), llvm::SmallVectorImpl< T >::append(), llvm::SmallString< InternalLen >::append(), llvm::Record::appendAssertions(), llvm::Record::appendDumps(), llvm::appendReversedLoopsToWorklist(), llvm::DIExpression::appendToStack(), appendVGScaledOffsetExpr(), llvm::SmallVectorImpl< T >::assign(), llvm::DIExpression::canonicalizeExpressionOps(), llvm::dwarf_linker::parallel::CompileUnit::cloneDieAttrExpression(), llvm::MachineInstr::cloneMergedMemRefs(), collectConcatOps(), llvm::PMTopLevelManager::collectLastUses(), combineConcatVectorOfConcatVectors(), combineConcatVectorOps(), combineToExtendBoolVectorInReg(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::concatenateVectors(), llvm::DIExpression::convertToUndefExpression(), llvm::DIExpression::convertToVariadicExpression(), llvm::dxil::DXILOpBuilder::createDXILOpCall(), createMMXBuildVector(), llvm::VectorBuilder::createVectorInstruction(), llvm::DecodeEXTRQIMask(), llvm::DecodeINSERTQIMask(), llvm::DecodeVectorBroadcast(), llvm::DecodeZeroExtendMask(), llvm::DecodeZeroMoveLowMask(), deleteDeadBlocksFromLoop(), llvm::BitstreamWriter::emitBlob(), llvm::MCDwarfLineAddr::encode(), eraseDeadBBsAndChildren(), llvm::cl::expandResponseFiles(), llvm::FindInsertedValue(), FixIrreducibleImpl(), llvm::LiveRange::flushSegmentSet(), foldCONCAT_VECTORS(), foldGEPOfGEP(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::ScalarEvolution::forgetLoop(), llvm::formLCSSAForInstructions(), getConstVector(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getDescendants(), getFauxShuffleMask(), getHostID(), llvm::LoopBase< BlockT, LoopT >::getInnerLoopsInPreorder(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInReverseSiblingPreorder(), llvm::LoopInfoBase< BasicBlock, Loop >::getLoopsInReverseSiblingPreorder(), getNoopInput(), llvm::AArch64RegisterInfo::getOffsetOpcodes(), llvm::RISCVRegisterInfo::getOffsetOpcodes(), getSalvageOpsForBinOp(), getSalvageOpsForGEP(), getSalvageOpsForTrunc(), llvm::ConstantDataArray::getString(), getTargetConstantBitsFromNode(), handleSSAValueOperands(), llvm::hasPartialIVCondition(), llvm::SDNode::hasPredecessorHelper(), hostParallelCallback(), llvm::DebugHandlerBase::identifyScopeMarkers(), llvm::InlineFunction(), llvm::opt::InputArgList::InputArgList(), llvm::SmallVectorImpl< T >::insert(), llvm::MemorySSAUpdater::insertDef(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), isHorizontalBinOp(), isLoopDead(), llvm::isPotentiallyReachable(), llvm::isPotentiallyReachableFromMany(), isSaveReachableThroughClean(), IsValueFullyAvailableInBlock(), llvm::TargetLowering::LowerCallTo(), llvm::RISCVTargetLowering::lowerDeinterleaveIntrinsicToLoad(), LowerEXTEND_VECTOR_INREG(), llvm::SITargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::lowerInterleavedStore(), lowerShuffleOfExtractsAsVperm(), lowerStatepointMetaArgs(), llvm::makePostTransformationMetadata(), markAllReachable(), moveBelowOrigChain(), llvm::R600TargetLowering::PerformDAGCombine(), performINSERT_VECTOR_ELTCombine(), llvm::logicalview::LVBinaryReader::processLines(), llvm::BitstreamCursor::readRecord(), llvm::LiveVariables::recomputeForSingleDefVirtReg(), reconstructGEP(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::opt::Arg::render(), llvm::opt::Arg::renderAsInput(), llvm::sys::path::replace_extension(), ReplaceINTRINSIC_W_CHAIN(), llvm::SmallVectorImpl< T >::resize(), resolveTypeIndexReferences(), llvm::LoopFullUnrollPass::run(), llvm::salvageDebugInfoImpl(), searchPredecessors(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::EngineBuilder::setMAttrs(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::simplifyLoop(), llvm::LegalizationArtifactCombiner::tryCombineUnmergeValues(), llvm::LegalizationArtifactCombiner::tryFoldUnmergeCast(), tryToVectorizeSequence(), llvm::SelectionDAG::UnrollVectorOverflowOp(), llvm::ScalarEvolution::verify(), llvm::InstCombinerImpl::visitGEPOfGEP(), widenVectorToPartType(), and llvm::support::endian::write().
append() [3/4]
template<typename T > void llvm::SmallVectorImpl< T >::append (size_type NumInputs, ValueParamT Elt) inline
Append NumInputs copies of Elt to the end.
Definition at line 705 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
append() [4/4]
template<typename T > void llvm::SmallVectorImpl< T >::append (std::initializer_list< T > IL) inline
Definition at line 711 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append().
assign() [1/4]
template<typename T > void llvm::SmallVectorImpl< T >::assign (const SmallVectorImpl< T > & RHS) inline
Definition at line 748 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::assign(), and RHS.
Referenced by llvm::SmallVectorImpl< T >::assign().
assign() [2/4]
template<typename T > template<typename ItTy , typename = EnableIfConvertibleToInputIterator<ItTy>> void llvm::SmallVectorImpl< T >::assign (ItTy in_start, ItTy in_end) inline
Definition at line 737 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToReferenceAfterClear(), and llvm::SmallVectorImpl< T >::clear().
assign() [3/4]
template<typename T > void llvm::SmallVectorImpl< T >::assign (size_type NumElts, ValueParamT Elt) inline
Definition at line 717 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::capacity(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::growAndAssign(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
Referenced by llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::add(), llvm::slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::add(), llvm::SmallString< InternalLen >::assign(), canWidenShuffleElements(), CloneNodeWithValues(), combineHorizOpWithShuffle(), combineX86ShufflesRecursively(), computeInLaneShuffleMask(), LiveDebugValues::MLocTracker::emitLoc(), llvm::cl::ExpansionContext::findConfigFile(), llvm::SplitEditor::finish(), llvm::WebAssemblyAsmTypeCheck::funcDecl(), llvm::getShuffleMaskWithWidestElts(), getTargetConstantBitsFromNode(), llvm::ConvergingVLIWScheduler::initialize(), isHorizontalBinOp(), isRepeatedShuffleMask(), isRepeatedTargetShuffleMask(), lowerShuffleAsDecomposedShuffleMerge(), mergeEltWithShuffle(), llvm::narrowShuffleMaskElts(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::processShuffleMasks(), llvm::BuildVectorSDNode::recastRawBits(), reorderOrder(), SalvageDVI(), llvm::X86MachineFunctionInfo::setPreallocatedArgOffsets(), llvm::ShuffleVectorInst::setShuffleMask(), llvm::ShuffleVectorConstantExpr::ShuffleVectorConstantExpr(), simplifyShuffleVectorInst(), llvm::LoopTraversal::traverse(), llvm::DbgValueHistoryMap::trimLocationRanges(), VectorizePTXValueVTs(), and llvm::widenShuffleMaskElts().
assign() [4/4]
template<typename T > void llvm::SmallVectorImpl< T >::assign (std::initializer_list< T > IL) inline
Definition at line 743 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append(), and llvm::SmallVectorImpl< T >::clear().
assignRemote()
template<typename T > void llvm::SmallVectorImpl< T >::assignRemote (SmallVectorImpl< T > && RHS) inline protected
Definition at line 603 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::BeginX, llvm::SmallVectorBase< SmallVectorSizeType< T > >::Capacity, llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateCommon< T, typename >::isSmall(), RHS, and llvm::SmallVectorBase< SmallVectorSizeType< T > >::Size.
Referenced by llvm::SmallVectorImpl< T >::operator=().
clear()
template<typename T > void llvm::SmallVectorImpl< T >::clear () inline
Definition at line 623 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::Size.
Referenced by llvm::PMDataManager::add(), addHints(), llvm::LiveIntervals::addKillFlags(), llvm::LanaiInstrInfo::analyzeBranch(), llvm::SystemZCCState::AnalyzeCallOperands(), llvm::SystemZCCState::AnalyzeFormalArguments(), analyzeLoopUnrollCost(), llvm::appendReversedLoopsToWorklist(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::SmallVectorImpl< T >::assign(), llvm::SmallString< InternalLen >::assign(), llvm::codeview::ContinuationRecordBuilder::begin(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), llvm::gsym::FunctionInfo::cacheEncoding(), llvm::MachineDominatorTree::calculate(), canVectorizeLoads(), CC_ARM_AAPCS_Custom_Aggregate(), CC_LoongArch(), llvm::RISCV::CC_RISCV(), llvm::CC_SystemZ_I128Indirect(), CC_X86_32_MCUInReg(), checkDependencies(), llvm::mca::RegisterFile::checkRAWHazards(), llvm::MipsCCState::CheckReturn(), checkVectorTypesForPromotion(), llvm::ConstantHoistingPass::cleanup(), llvm::ModifiedPostOrder< ContextT >::clear(), llvm::IndexedMap< T, ToIndexT >::clear(), llvm::AssumptionCache::clear(), llvm::FunctionVarLocs::clear(), llvm::FunctionLoweringInfo::clear(), llvm::GISelWorkList< N >::clear(), llvm::LiveRange::clear(), llvm::SDDbgInfo::clear(), LiveDebugValues::DbgOpIDMap::clear(), llvm::ARMBasicBlockUtils::clear(), llvm::SPIRV::RequirementHandler::clear(), llvm::WebAssemblyAsmTypeCheck::Clear(), llvm::SpillPlacement::Node::clear(), llvm::ArrayRecycler< T, Align >::clear(), llvm::CCState::clearByValRegsInfo(), llvm::VPBlockBase::clearPredecessors(), llvm::VPBlockBase::clearSuccessors(), llvm::PPCCCState::clearWasPPCF128(), clusterSortPtrAccesses(), llvm::InlineAsm::collectAsmStrs(), llvm::computeAccessFunctions(), llvm::RegBankSelect::computeMapping(), llvm::convertUTF8ToUTF16String(), llvm::logicalview::LVELFReader::createScopes(), createTblForTrunc(), llvm::DecodeVPPERMMask(), llvm::slpvectorizer::BoUpSLP::deleteTree(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::AsmPrinter::doFinalization(), doPromotion(), llvm::ehAwareSplitEdge(), emitComments(), LiveDebugValues::MLocTracker::emitLoc(), llvm::remarks::BitstreamRemarkSerializerHelper::emitMetaBlock(), llvm::remarks::BitstreamRemarkSerializerHelper::emitMetaExternalFile(), llvm::remarks::BitstreamRemarkSerializerHelper::emitMetaRemarkVersion(), llvm::remarks::BitstreamRemarkSerializerHelper::emitMetaStrTab(), llvm::remarks::BitstreamRemarkSerializerHelper::emitRemarkBlock(), llvm::CodeViewContext::encodeDefRange(), llvm::CodeViewContext::encodeInlineLineTable(), llvm::mca::InstructionTables::execute(), ExpandBVWithShuffles(), llvm::ARMTargetLowering::ExpandInlineAsm(), llvm::X86TargetLowering::ExpandInlineAsm(), llvm::extractParts(), llvm::LegalizerHelper::fewerElementsVectorReductions(), llvm::LegalizerHelper::fewerElementsVectorShuffle(), llvm::finalizeBundle(), llvm::CodeExtractor::findAllocas(), llvm::RegBankSelect::findBestMapping(), llvm::SampleProfileLoaderBaseImpl< FT >::findEquivalenceClasses(), llvm::DirectedGraph< NodeType, EdgeType >::findIncomingEdgesToNode(), findOrCreatePHIInBlock(), finishStackBlock(), TransferTracker::flushDbgValues(), llvm::RecordStreamer::flushSymverDirectives(), llvm::remarks::BitstreamRemarkSerializerHelper::flushToStream(), llvm::formDedicatedExitBlocks(), llvm::formLCSSAForInstructions(), generateInstSeqLeadingZeros(), llvm::ScalarEvolution::getAddExpr(), llvm::RegsForValue::getCopyFromRegs(), llvm::TargetSubtargetInfo::getCriticalPathRCs(), llvm::pdb::DIARawSymbol::getDataBytes(), llvm::pdb::NativeRawSymbol::getDataBytes(), llvm::GenericCycle< ContextT >::getExitBlocks(), getFauxShuffleMask(), getHostID(), llvm::getIndexExpressionsFromGEP(), llvm::unittest::getInputFileDirectory(), getLiveInRegsAt(), llvm::getLiveRegMap(), getMemmoveLoadsAndStores(), llvm::internal::NfaTranscriber::getPaths(), llvm::LoopNest::getPerfectLoops(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::GetShadowBytes(), getUnderlyingObjects(), llvm::getUnderlyingObjectsForCodeGen(), getUnderlyingObjectsForInstr(), llvm::FunctionLoweringInfo::getValueFromVirtualReg(), llvm::ResourceManager::init(), llvm::InlineFunction(), llvm::MemorySSAUpdater::insertDef(), insertParsePoints(), insertSpills(), isHorizontalBinOp(), IsValueFullyAvailableInBlock(), isVectorPromotionViable(), isWideTypeMask(), llvm::SpillPlacement::iterate(), llvm::AMDGPULegalizerInfo::legalizeBVHIntrinsic(), TransferTracker::loadInlocs(), llvm::NVPTXTargetLowering::LowerCall(), llvm::ARMCallLowering::lowerCall(), llvm::MipsCallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), llvm::PhiLoweringHelper::lowerPhis(), llvm::NVPTXTargetLowering::LowerReturn(), lowerV4X128Shuffle(), makeStatepointExplicitImpl(), llvm::Regex::match(), mergeConstants(), moveBelowOrigChain(), llvm::sys::unicode::nameToCodepoint(), llvm::sys::unicode::nameToGeneratedCodePoint(), llvm::sys::unicode::nameToHangulCodePoint(), llvm::narrowShuffleMaskElts(), llvm::sys::path::native(), llvm::SmallVectorImpl< T >::operator=(), parseOperands(), parseScalarValue(), llvm::yaml::Scanner::peekNext(), llvm::PeelingModuloScheduleExpander::peelPrologAndEpilogs(), llvm::MipsCCState::PreAnalyzeCallOperands(), llvm::MipsCCState::PreAnalyzeCallResult(), llvm::MipsCCState::PreAnalyzeFormalArguments(), llvm::MipsCCState::PreAnalyzeReturn(), llvm::SpillPlacement::prepare(), llvm::processShuffleMasks(), llvm::sampleprof::SampleProfileReaderText::readImpl(), ReduceLoopStrength(), llvm::RuntimeDyldELF::registerEHFrames(), llvm::LiveIntervals::releaseMemory(), llvm::MachineDominatorTree::releaseMemory(), llvm::ReachingDefAnalysis::releaseMemory(), llvm::SlotIndexes::releaseMemory(), llvm::RAGreedy::releaseMemory(), llvm::LiveRange::RenumberValues(), reorderOrder(), reorderSubVector(), llvm::RuntimePointerChecking::reset(), llvm::SchedRemainder::reset(), llvm::SchedBoundary::reset(), llvm::MCContext::reset(), llvm::MCLOHContainer::reset(), llvm::MCStreamer::reset(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Reset(), llvm::internal::NfaTranscriber::reset(), llvm::DominatorTreeBase< NodeT, IsPostDom >::reset(), llvm::UnwindOpcodeAssembler::Reset(), llvm::HexagonShuffler::reset(), llvm::LiveRangeCalc::reset(), llvm::DataLayout::reset(), llvm::LiveIntervalUnion::Query::reset(), llvm::MCDwarfLineTableHeader::resetFileTable(), llvm::dwarf_linker::parallel::DependencyTracker::resolveDependenciesAndMarkLiveness(), resolveTypeIndexReferences(), llvm::SLPVectorizerPass::runImpl(), llvm::ARMBlockPlacement::runOnMachineFunction(), llvm::SpillPlacement::scanActiveBundles(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::SwiftErrorValueTracking::setFunction(), llvm::EngineBuilder::setMAttrs(), llvm::IntervalMapImpl::Path::setRoot(), llvm::dwarf_linker::parallel::SectionDescriptor::setSizesForSectionCreatedByAsmPrinter(), llvm::AAPointerInfo::RangeList::setUnknown(), simplifyLoopInst(), llvm::InnerLoopVectorizer::sinkScalarOperands(), llvm::sortPtrAccesses(), llvm::SplitKnownCriticalEdge(), stripDeadDebugInfoImpl(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::RegBankSelect::RepairingPlacement::switchTo(), llvm::CodeViewYAML::toDebugH(), llvm::cl::TokenizeGNUCommandLine(), tokenizeWindowsCommandLineImpl(), llvm::LoopTraversal::traverse(), llvm::tryDelinearizeFixedSizeImpl(), tryToVectorizeSequence(), unswitchNontrivialInvariants(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), llvm::JumpThreadingPass::updateSSA(), llvm::HexagonShuffler::ValidResourceUsage(), llvm::ValueEnumerator::ValueEnumerator(), llvm::dxil::ValueEnumerator::ValueEnumerator(), llvm::GenericConvergenceVerifier< ContextT >::verify(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::widenShuffleMaskElts(), llvm::MachObjectWriter::writeObject(), llvm::sampleprof::SampleProfileWriter::writeWithSizeLimitInternal(), and llvm::yaml::yaml2ObjectFile().
emplace_back()
template<typename T > template<typename... ArgTypes> reference llvm::SmallVectorImpl< T >::emplace_back (ArgTypes &&... Args) inline
Definition at line 950 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::capacity(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack(), LLVM_UNLIKELY, llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::size(), and T.
Referenced by llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::add(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::addAccelTableKind(), llvm::dwarf_linker::parallel::DependencyTracker::addActionToRootEntriesWorkList(), llvm::OpenMPIRBuilder::addAttributes(), llvm::MCContext::addDebugPrefixMapEntry(), addEdge(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::addModulesCompileUnit(), FunctionVarLocsBuilder::addSingleLocVar(), llvm::mca::MemoryGroup::addSuccessor(), llvm::ConstraintSystem::addVariableRow(), llvm::mca::Scheduler::analyzeDataDependencies(), appendFoldCandidate(), llvm::ScalarEvolution::applyLoopGuards(), llvm::TimeTraceProfiler::begin(), llvm::CSEMIRBuilder::buildInstr(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), llvm::calculateClrEHStateNumbers(), llvm::PatternMatch::undef_match::check(), checkClobberSanity(), classifyConstantWithOpaquePtr(), TransferTracker::clobberMloc(), cloneInstructionInExitBlock(), collectFrameAlloca(), collectVirtualRegUses(), combineBinOp_VLToVWBinOp_VL(), llvm::sys::commandLineFitsWithinSystemLimits(), computeImportForFunction(), llvm::RegBankSelect::computeMapping(), llvm::ConstantFoldCTLZ(), costAndCollectOperands(), llvm::CallBase::Create(), llvm::objcarc::createCallInstWithColors(), llvm::dxil::DXILOpBuilder::createDXILOpCall(), llvm::dxil::createEntryMD(), createFunctionClones(), createImportedModule(), llvm::mca::RISCVInstrumentManager::createInstruments(), createLocalVariable(), decompose(), decomposeGEP(), doPromotion(), llvm::MCPseudoProbeSections::emit(), llvm::NVPTXTargetStreamer::emitDwarfFileDirective(), llvm::AsmPrinter::emitFunctionBody(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), llvm::PseudoProbeHandler::emitPseudoProbe(), llvm::TimeTraceProfiler::end(), llvm::mca::InstructionTables::execute(), llvm::objcopy::macho::executeObjcopyOnMachOUniversalBinary(), llvm::LegalizerHelper::fewerElementsVectorReductions(), llvm::RISCV::fillValidCPUArchList(), llvm::X86::fillValidCPUArchList(), llvm::LoongArch::fillValidCPUList(), llvm::RISCV::fillValidTuneCPUArchList(), llvm::X86::fillValidTuneCPUList(), llvm::PeelingModuloScheduleExpander::filterInstructions(), llvm::RegBankSelect::findBestMapping(), llvm::sampleprof::FunctionSamples::findFunctionSamples(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), llvm::FoldBranchToCommonDest(), foldExtractSubvectorFromShuffleVector(), foldICmpOrXorSubChain(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), llvm::RISCVMatInt::generateInstSeq(), generateInstSeqImpl(), generateInstSeqLeadingZeros(), llvm::AttributeList::get(), llvm::SampleContextTracker::getContextString(), getDXILOpFunctionType(), llvm::LoopBase< BlockT, LoopT >::getExitEdges(), llvm::getHeaders(), llvm::MCDecodedPseudoProbe::getInlineContext(), llvm::MCPseudoProbeDecoder::getInlineContextForProbe(), llvm::CallBase::getOperandBundlesAsDefs(), llvm::X86MachineFunctionInfo::getPreallocatedIdForCallSite(), llvm::CallLowering::getReturnInfo(), llvm::ScalarEvolution::getSCEVAtScope(), llvm::SelectionDAG::getTokenFactor(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), getUnderlyingObjectsForInstr(), llvm::slpvectorizer::BoUpSLP::getVectorElementSize(), getWorklist(), llvm::SelectionDAGBuilder::handleDebugValue(), llvm::FunctionVarLocs::init(), llvm::MIRParserImpl::initializeCallSiteInfo(), llvm::mca::initializeUsedResources(), llvm::InlineFunction(), llvm::MachineInstr::insert(), llvm::TargetPassConfig::insertPass(), llvm::LazyCallGraph::RefSCC::insertTrivialCallEdge(), llvm::LazyCallGraph::RefSCC::insertTrivialRefEdge(), llvm::SCEVExpander::isHighCostExpansion(), isLoadCombineCandidate(), isOnlyCopiedFromConstantMemory(), IsValueFullyAvailableInBlock(), LinearizeExprTree(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::link(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::loadClangModule(), llvm::CombinerHelper::matchCombineMergeUnmerge(), llvm::CombinerHelper::matchCombineUnmergeConstant(), matchIntrinsicType(), mergeEltWithShuffle(), llvm::dwarf_linker::classic::CompileUnit::noteLocationAttribute(), llvm::dwarf_linker::parallel::SectionDescriptor::notePatchWithOffsetUpdate(), llvm::dwarf_linker::classic::CompileUnit::noteRangeAttribute(), llvm::json::OStream::OStream(), parseBraceExpansions(), populateEHOperandBundle(), llvm::ScopedPrinter::printFlags(), llvm::ScopedPrinter::printHexList(), llvm::ScopedPrinter::printList(), llvm::JumpThreadingPass::processThreadableEdges(), PropagateOperandBundles(), llvm::PassInstrumentation::pushBeforeNonSkippedPassCallback(), llvm::AAPointerInfo::RangeList::RangeList(), TransferTracker::redefVar(), llvm::PassInstrumentationCallbacks::registerAfterAnalysisCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback(), llvm::PassInstrumentationCallbacks::registerAnalysesClearedCallback(), llvm::PassInstrumentationCallbacks::registerAnalysisInvalidatedCallback(), llvm::PassInstrumentationCallbacks::registerBeforeAnalysisCallback(), llvm::PassInstrumentationCallbacks::registerBeforeNonSkippedPassCallback(), llvm::PassInstrumentationCallbacks::registerBeforeSkippedPassCallback(), llvm::PassInstrumentationCallbacks::registerShouldRunOptionalPassCallback(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::CallBase::removeOperandBundle(), llvm::slpvectorizer::BoUpSLP::reorderBottomToTop(), llvm::SCEVExpander::replaceCongruentIVs(), replaceExitCond(), replaceLoopPHINodesWithPreheaderValues(), llvm::rewriteLoopExitValues(), llvm::PeelingModuloScheduleExpander::rewriteUsesOf(), runMoveAutoInit(), llvm::RewriteStatepointsForGC::runOnFunction(), llvm::MachineFunction::setVariableDbgInfo(), llvm::simplifyLoopAfterUnroll(), llvm::AbstractDependenceGraphBuilder< DataDependenceGraph >::sortNodesTopologically(), llvm::SplitBlockAndInsertIfThenElse(), llvm::SplitIndirectBrCriticalEdges(), llvm::CallLowering::splitToValueTypes(), llvm::DbgValueHistoryMap::startClobber(), llvm::DbgValueHistoryMap::startDbgValue(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD::synthesizeTargets(), takeInexpensiveLog2(), llvm::OpenMPIRBuilder::tileLoops(), llvm::JumpThreadingPass::unfoldSelectInstr(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchNontrivialInvariants(), updateIDTMetaData(), llvm::PeelingModuloScheduleExpander::validateAgainstModuloScheduleExpander(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::dwarf_linker::parallel::DependencyTracker::verifyKeepChain(), llvm::dxil::ResourceTable< T >::write(), and llvm::slpvectorizer::BoUpSLP::~BoUpSLP().
erase() [1/2]
template<typename T > iterator llvm::SmallVectorImpl< T >::erase (const_iterator CI) inline
Definition at line 750 of file SmallVector.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, llvm::SmallVectorTemplateCommon< T, typename >::isReferenceToStorage(), N, and llvm::SmallVectorTemplateBase< T, bool >::pop_back().
Referenced by collectMultiplyFactors(), llvm::IntervalTree< PointT, ValueT, DataT >::create(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::cl::ExpansionContext::expandResponseFiles(), llvm::findArrayDimensions(), llvm::LiveRangeUpdater::flush(), llvm::MCSection::flushPendingLabels(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ScalarEvolution::getMulExpr(), getPreStartForExtend(), llvm::ScalarEvolution::getSequentialMinMaxExpr(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTokenFactor(), llvm::AddressRanges::insert(), llvm::LiveRange::join(), llvm::MCAsmLexer::Lex(), lowerV16I8Shuffle(), lowerV8I16GeneralSingleInputShuffle(), llvm::LiveRange::MergeValueNumberInto(), OptimizeAndOrXor(), llvm::performOptimizedStructLayout(), RemoveInstInputs(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::DirectedGraph< NodeType, EdgeType >::removeNode(), llvm::GISelObserverWrapper::removeObserver(), RemovePreallocated(), removeRegLanes(), llvm::LiveRange::removeSegment(), llvm::Record::removeValue(), replaceConstantExprOp(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Reset(), sortGlobalExprs(), llvm::DebugLocEntry::sortUniqueValues(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), verifySubExpr(), and llvm::InstCombinerImpl::visitLandingPadInst().
erase() [2/2]
template<typename T > iterator llvm::SmallVectorImpl< T >::erase (const_iterator CS, const_iterator CE) inline
Definition at line 764 of file SmallVector.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), E, llvm::SmallVectorTemplateCommon< T, typename >::end(), I, llvm::SmallVectorTemplateCommon< T, typename >::isRangeInStorage(), N, and llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size().
insert() [1/5]
template<typename T > iterator llvm::SmallVectorImpl< T >::insert (iterator I, const T & Elt) inline
Definition at line 822 of file SmallVector.h.
References llvm::SmallVectorTemplateBase< T, bool >::forward_value_param(), and I.
insert() [2/5]
template<typename T > template<typename ItTy , typename = EnableIfConvertibleToInputIterator<ItTy>> iterator llvm::SmallVectorImpl< T >::insert (iterator I, ItTy From, ItTy To) inline
Definition at line 888 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToAddRange(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), From, I, llvm::SmallVectorTemplateCommon< T, typename >::isReferenceToStorage(), llvm::SmallVectorImpl< T >::reserve(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::size(), llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy(), and llvm::SmallVectorTemplateBase< T, bool >::uninitialized_move().
insert() [3/5]
template<typename T > iterator llvm::SmallVectorImpl< T >::insert (iterator I, size_type NumToInsert, ValueParamT Elt) inline
Definition at line 826 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, llvm::SmallVectorTemplateCommon< T, typename >::isReferenceToStorage(), llvm::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::size(), llvm::SmallVectorTemplateBase< T, bool >::TakesParamByValue, and llvm::SmallVectorTemplateBase< T, bool >::uninitialized_move().
insert() [4/5]
template<typename T > void llvm::SmallVectorImpl< T >::insert (iterator I, std::initializer_list< T > IL) inline
Definition at line 946 of file SmallVector.h.
References I, and llvm::SmallVectorImpl< T >::insert().
insert() [5/5]
template<typename T > iterator llvm::SmallVectorImpl< T >::insert (iterator I, T && Elt) inline
Definition at line 818 of file SmallVector.h.
References llvm::SmallVectorTemplateBase< T, bool >::forward_value_param(), and I.
Referenced by llvm::GVNPass::ValueTable::add(), addData(), llvm::DWARFUnitVector::addUnit(), llvm::MipsInstrInfo::analyzeBranch(), llvm::DIExpression::appendOpsToArg(), checkIfSupported(), TransferTracker::clobberMloc(), collectOtherInstr(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::cl::ExpansionContext::expandResponseFiles(), llvm::LiveRangeUpdater::flush(), llvm::ScalarEvolution::forgetLoop(), getSalvageOpsForGEP(), llvm::ScalarEvolution::getSequentialMinMaxExpr(), llvm::DWARFUnitVector::getUnitForIndexEntry(), llvm::logicalview::LVBinaryReader::includeInlineeLines(), llvm::IRSimilarity::IRInstructionData::initializeInstruction(), llvm::AddressRanges::insert(), llvm::AddressRangesMap::insert(), llvm::SmallVectorImpl< T >::insert(), llvm::AAPointerInfo::RangeList::insert(), llvm::ARMBasicBlockUtils::insert(), llvm::CallLowering::insertSRetIncomingArgument(), instCombineConvertFromSVBool(), llvm::MCAsmLexer::Lex(), llvm::WebAssemblyAsmTypeCheck::localDecl(), llvm::BlockFrequencyInfoImplBase::LoopData::LoopData(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), LowerInterruptReturn(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), llvm::LegalizerHelper::narrowScalar(), llvm::sys::unicode::nearestMatchesForCodepointName(), llvm::yaml::MappingTraits< const InterfaceFile * >::NormalizedTBD_V4::NormalizedTBD_V4(), llvm::orc::AllocGroupSmallMap< T >::operator[](), ProcessElementList(), llvm::logicalview::LVBinaryReader::processLines(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::reconstituteName(), llvm::AArch64TargetLowering::ReconstructShuffle(), llvm::PassInstrumentationCallbacks::registerAfterAnalysisCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback(), llvm::LiveRange::removeSegment(), llvm::IntervalMapImpl::Path::replaceRoot(), stripDeadDebugInfoImpl(), llvm::WebAssemblyAsmTypeCheck::typeCheck(), llvm::MCAsmLexer::UnLex(), unswitchLoop(), llvm::WriteBitcodeToFile(), and llvm::dxil::WriteDXILToFile().
operator!=()
template<typename T > bool llvm::SmallVectorImpl< T >::operator!= (const SmallVectorImpl< T > & RHS) const inline
Definition at line 967 of file SmallVector.h.
References RHS.
operator<()
template<typename T > bool llvm::SmallVectorImpl< T >::operator< (const SmallVectorImpl< T > & RHS) const inline
Definition at line 971 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and RHS.
operator<=()
template<typename T > bool llvm::SmallVectorImpl< T >::operator<= (const SmallVectorImpl< T > & RHS) const inline
Definition at line 976 of file SmallVector.h.
References RHS.
operator=() [1/2]
template<typename T > SmallVectorImpl< T > & llvm::SmallVectorImpl< T >::operator= (const SmallVectorImpl< T > & RHS)
Definition at line 1017 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::capacity(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::grow(), RHS, llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::size(), and llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy().
operator=() [2/2]
template<typename T > SmallVectorImpl< T > & llvm::SmallVectorImpl< T >::operator= (SmallVectorImpl< T > && RHS)
Definition at line 1065 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::assignRemote(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::capacity(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::grow(), RHS, llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::size(), and llvm::SmallVectorTemplateBase< T, bool >::uninitialized_move().
operator==()
template<typename T > bool llvm::SmallVectorImpl< T >::operator== (const SmallVectorImpl< T > & RHS) const inline
Definition at line 963 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), RHS, and llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
operator>()
template<typename T > bool llvm::SmallVectorImpl< T >::operator> (const SmallVectorImpl< T > & RHS) const inline
Definition at line 975 of file SmallVector.h.
References RHS.
operator>=()
template<typename T > bool llvm::SmallVectorImpl< T >::operator>= (const SmallVectorImpl< T > & RHS) const inline
Definition at line 977 of file SmallVector.h.
References RHS.
pop_back_n()
template<typename T > void llvm::SmallVectorImpl< T >::pop_back_n (size_type NumItems) inline
Definition at line 681 of file SmallVector.h.
References assert(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::size(), and llvm::SmallVectorImpl< T >::truncate().
pop_back_val()
template<typename T > T llvm::SmallVectorImpl< T >::pop_back_val () inline
Definition at line 686 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), and llvm::SmallVectorTemplateBase< T, bool >::pop_back().
Referenced by addAllGlobalValueUsers(), addBlockAndPredsToSet(), llvm::RecurrenceDescriptor::AddReductionVar(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), allUsersAreInFunction(), allUsesOfLoadAndStores(), allUsesOfLoadedValueWillTrapIfNull(), analyzeLoopUnrollCost(), llvm::appendReversedLoopsToWorklist(), llvm::ScalarEvolution::applyLoopGuards(), llvm::RegBankSelect::assignRegisterBanks(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildClonedLoops(), buildMultiplyTree(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), llvm::calculateClrEHStateNumbers(), llvm::calculateCXXStateForAsynchEH(), llvm::calculateSEHStateForAsynchEH(), canonicalizePHIOperands(), canReturn(), llvm::ScalarEvolution::canReuseInstruction(), llvm::PatternMatch::undef_match::check(), checkClobberSanity(), llvm::Attributor::checkForAllUses(), llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches(), checkMixedPrecision(), CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), cleanupSinglePredPHIs(), clearAssumptionsOfUsers(), llvm::CloneAndPruneIntoFromInst(), cloneLoopNest(), llvm::OpenMPIRBuilder::OutlineInfo::collectBlocks(), collectCastInstrs(), collectEHScopeMembers(), collectHomogenousInstGraphLoopInvariants(), collectLeaves(), collectSRATypes(), collectTransitivePredecessors(), llvm::colorEHFunclets(), combineBinOp_VLToVWBinOp_VL(), combineOrCmpEqZeroToCtlzSrl(), combineRedundantDWordShuffle(), llvm::FunctionComparator::compare(), computeBlocksDominatingExits(), llvm::computeDeadSymbolsAndUpdateIndirectCalls(), ModuleImportsManager::computeImportForModule(), ComputeLiveInBlocks(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::computeMinimumValueSizes(), ComputePostOrders(), computeUnlikelySuccessors(), llvm::SMSchedule::computeUnpipelineableNodes(), ConstHasGlobalValuePredicate(), convertToParamAS(), deleteDeadBlocksFromLoop(), llvm::ARMFrameLowering::determineCalleeSaves(), determinePointerAccessAttrs(), doPromotion(), llvm::SMSchedule::earliestCycleInChain(), EmitAddTreeOfValues(), llvm::SelectionDAGISel::EnforceNodeIdInvariant(), eraseDeadBBsAndChildren(), llvm::GIMatchTableExecutor::executeMatchTable(), llvm::findAllocaForValue(), findArgParts(), findBasePointer(), findDependencies(), llvm::MustBeExecutedContextExplorer::findForwardJoinPoint(), llvm::FindFunctionBackedges(), llvm::DWARFDie::findRecursively(), findRefEdges(), FixIrreducibleImpl(), foldICmpOrXorSubChain(), forEachUser(), llvm::ScalarEvolution::forgetBlockAndLoopDispositions(), llvm::ScalarEvolution::forgetLoop(), llvm::formLCSSAForInstructions(), generateReproducer(), llvm::Attributor::getAssumedSimplifiedValues(), getBaseType(), llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getDescendants(), llvm::ReachingDefAnalysis::getGlobalUses(), llvm::LoopBase< BlockT, LoopT >::getInnerLoopsInPreorder(), getInvariantGroupClobberingInstruction(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInReverseSiblingPreorder(), llvm::AArch64TTIImpl::getMemoryOpCost(), llvm::BasicAAResult::getModRefInfoMask(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::getUnderlyingObjects(), llvm::getUnderlyingObjectsForCodeGen(), getUnwindDestToken(), getUnwindDestTokenHelper(), llvm::slpvectorizer::BoUpSLP::getVectorElementSize(), HandleMergeInputChains(), hasAllNBitUsers(), hasCallsInBlocksBetween(), hasHardUserWithinLoop(), llvm::hasPartialIVCondition(), llvm::SDNode::hasPredecessorHelper(), llvm::HexagonMCShuffle(), hoistFPAssociation(), llvm::DebugHandlerBase::identifyScopeMarkers(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), llvm::MachineTraceMetrics::Ensemble::invalidate(), isAllocSiteRemovable(), llvm::LazyCallGraph::RefSCC::isAncestorOf(), llvm::LazyCallGraph::SCC::isAncestorOf(), isBlockValidForExtraction(), isEphemeralValueOf(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), llvm::SCEVExpander::isHighCostExpansion(), isKnownNonNullFromDominatingCondition(), isLoadCombineCandidate(), isLoopDead(), isNonEscapingGlobalNoAliasWithLoad(), isObjectSizeLessThanOrEq(), isOnlyCopiedFromConstantMemory(), isPotentiallyReachable(), llvm::isPotentiallyReachableFromMany(), isReachableAmongDominated(), llvm::isSafeToDestroyConstant(), isSaveReachableThroughClean(), isSignExtendedW(), IsStoredObjCPointer(), isSuccOrder(), llvm::object::WasmSectionOrderChecker::isValidSectionOrder(), IsValueFullyAvailableInBlock(), llvm::SMSchedule::latestCycleInChain(), llvm::Legalizer::legalizeMachineFunction(), LinearizeExprTree(), llvm::LowerDbgDeclare(), markAliveBlocks(), markAllReachable(), llvm::dwarf_linker::parallel::DependencyTracker::markCollectedLiveRootsAsKept(), markTails(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), llvm::InstCombinerImpl::matchBSwapOrBitReverse(), memoryIsNotModifiedBetween(), mergeEltWithShuffle(), llvm::mustExecuteUBIfPoisonOnPathTo(), GlobalsImporter::onImportingSummary(), optimizeLoopExitWithUnknownExitCount(), parseCondition(), llvm::PointerMayBeCaptured(), llvm::GISelWorkList< N >::pop_back_val(), llvm::GraphDiff< NodePtr, InverseGraph >::popUpdateForIncrementalUpdates(), llvm::WebAssemblyInstPrinter::printInst(), llvm::AlignmentFromAssumptionsPass::processAssumption(), rebuildLoopAfterUnswitch(), llvm::LiveVariables::recomputeForSingleDefVirtReg(), recomputeLoopBlockSet(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::InstructionWorklist::removeOne(), removePAICalls(), replaceConstantExprOp(), llvm::DebugLoc::replaceInlinedAtSubprogram(), replaceLoopPHINodesWithPreheaderValues(), llvm::Value::replaceUsesWithIf(), rewriteNonInstructionUses(), llvm::GenericCycleInfoCompute< ContextT >::run(), llvm::TruncInstCombine::run(), llvm::LoopSinkPass::run(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), runImpl(), llvm::LoopVectorizePass::runImpl(), runMoveAutoInit(), searchPredecessors(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::SUnit::setDepthDirty(), llvm::SUnit::setHeightDirty(), shouldTransformMulToShiftsAddsSubs(), llvm::simplifyLoop(), llvm::simplifyLoopAfterUnroll(), sinkSpillUsesAfterCoroBegin(), SoleWriteToDeadLocal(), SRAGlobal(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::PHITransAddr::translateWithInsertion(), llvm::LoopTraversal::traverse(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), unswitchLoop(), llvm::SelectionDAG::updateDivergence(), updateLiveness(), llvm::JumpThreadingPass::updateSSA(), usersDominator(), valueIsOnlyUsedLocallyOrStoredToOneGlobal(), llvm::ScalarEvolution::verify(), verifyCTRBranch(), llvm::SCEVTraversal< SV >::visitAll(), visitDomSubTree(), visitPointers(), and llvm::LazyCallGraph::visitReferences().
reserve()
template<typename T > void llvm::SmallVectorImpl< T >::reserve (size_type N) inline
Definition at line 676 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::capacity(), and llvm::SmallVectorTemplateBase< T, bool >::grow().
Referenced by llvm::FoldingSetNodeID::AddString(), llvm::SmallVectorImpl< T >::append(), appendToGlobalArray(), llvm::DomTreeUpdater::applyUpdates(), llvm::MachineIRBuilder::buildBuildVectorConstant(), buildClonedLoopBlocks(), buildClonedLoops(), buildCopyFromRegs(), llvm::FileCheck::CanonicalizeFile(), llvm::changeToUnreachable(), llvm::OpenMPIRBuilder::collapseLoops(), combineBinOp_VLToVWBinOp_VL(), combineConcatVectorOfShuffleAndItsOperands(), llvm::sys::commandLineFitsWithinSystemLimits(), llvm::EHStreamer::computeActionsTable(), llvm::computeDeadSymbolsAndUpdateIndirectCalls(), llvm::ConstantFoldExtractElementInstruction(), llvm::TypedInit::convertInitializerBitRange(), llvm::MIRPrinter::convertStackObjects(), llvm::DIExpression::convertToVariadicExpression(), createFunctionClones(), llvm::IRBuilderBase::CreateIntrinsic(), llvm::MDBuilder::createPCSections(), llvm::memprof::IndexedMemProfRecord::deserialize(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::MCPseudoProbeSections::emit(), llvm::EHStreamer::emitExceptionTable(), emitIntrinsicWithCC(), emitIntrinsicWithCCAndChain(), ExpandBVWithShuffles(), llvm::FindInsertedValue(), llvm::slpvectorizer::BoUpSLP::findPartiallyOrderedLoads(), llvm::RecordStreamer::flushSymverDirectives(), foldExtractSubvectorFromShuffleVector(), foldGEPOfGEP(), llvm::AttributeList::get(), llvm::MachineInstrExpressionTrait::getHashValue(), llvm::SelectionDAG::getMergeValues(), llvm::MDNode::getMostGenericRange(), llvm::ScalarEvolution::getMulExpr(), llvm::IntEqClasses::grow(), llvm::ScheduleDAGTopologicalSort::InitDAGTopologicalSorting(), llvm::InlineFunction(), llvm::SmallVectorImpl< T >::insert(), llvm::MachineInstr::insert(), insertParsePoints(), insertVector(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::LinkContext(), TransferTracker::loadInlocs(), makeStatepointExplicit(), llvm::MergeBasicBlockIntoOnlyPred(), MergeCompatibleInvokesImpl(), llvm::LegalizerHelper::narrowScalarAddSub(), llvm::sys::unicode::nearestMatchesForCodepointName(), OptimizeAwayTrappingUsesOfValue(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), parseScalarValue(), performBlockTailMerging(), llvm::performOptimizedStructLayout(), llvm::PointerMayBeCaptured(), llvm::CallGraph::print(), llvm::AAPointerInfo::RangeList::RangeList(), llvm::BitstreamCursor::readRecord(), rebuildLoopAfterUnswitch(), llvm::WebAssemblyExceptionInfo::recalculate(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::reconstituteName(), relocationViaAlloca(), llvm::InstructionWorklist::reserve(), llvm::IndexedMap< T, ToIndexT >::reserve(), llvm::VarDefInit::resolveReferences(), llvm::DagInit::resolveReferences(), runImpl(), llvm::SlotIndexes::runOnMachineFunction(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runSemiNCA(), splitAsyncCoroutine(), llvm::SplitBlockAndInsertIfThenElse(), llvm::splitBlockBefore(), SplitBlockImpl(), llvm::SplitIndirectBrCriticalEdges(), splitRetconCoroutine(), llvm::stableHashValue(), llvm::SmallVectorImpl< T >::swap(), llvm::OpenMPIRBuilder::tileLoops(), tryConstantFoldCall(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), unswitchNontrivialInvariants(), UpdateAnalysisInformation(), llvm::upgradeInstructionLoopAttachment(), upgradeLoopArgument(), llvm::InstCombinerImpl::visitLandingPadInst(), llvm::widenShuffleMaskElts(), llvm::write(), llvm::mcdxbc::Signature::write(), llvm::WriteBitcodeToFile(), llvm::dxil::WriteDXILToFile(), llvm::writeIndexToFile(), llvm::writeThinLinkBitcodeToFile(), and llvm::LLVMContextImpl::~LLVMContextImpl().
resize() [1/2]
template<typename T > void llvm::SmallVectorImpl< T >::resize (size_type N) inline
Definition at line 651 of file SmallVector.h.
References N.
Referenced by addData(), llvm::CodeViewContext::addFile(), llvm::AttributeList::addParamAttribute(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addParentName(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::assignName(), canVectorizeLoads(), llvm::BitTracker::RegisterCell::cat(), llvm::CCState::CCState(), llvm::OpenMPIRBuilder::collapseLoops(), llvm::mca::RegisterFile::collectWrites(), CombineBaseUpdate(), combineBitcast(), llvm::ARMBasicBlockUtils::computeAllBlockSizes(), llvm::EHStreamer::computeCallSiteTable(), llvm::WasmException::computeCallSiteTable(), llvm::ConstantFoldGetElementPtr(), llvm::convertUTF8ToUTF16String(), copyBytesForDefRange(), llvm::orc::shared::WrapperFunctionCall::Create(), createMMXBuildVector(), llvm::VectorBuilder::createVectorInstruction(), llvm::IRBuilderBase::CreateVectorSplat(), llvm::DependenceInfo::depends(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::CodeViewContext::emitFileChecksumOffset(), llvm::MCStreamer::emitIntValue(), llvm::MachineTraceMetrics::Ensemble::Ensemble(), llvm::GIMatchTableExecutor::executeMatchTable(), llvm::extractConstantMask(), llvm::extractFromBranchWeightMD(), findBuildAggregate(), llvm::SplitEditor::finish(), llvm::RegsForValue::getCopyFromRegs(), llvm::pdb::DIARawSymbol::getDataBytes(), llvm::GenericCycle< ContextT >::getExitBlocks(), llvm::LLVMContext::getMDKindNames(), llvm::MDNode::getMostGenericRange(), getNoopInput(), llvm::LLVMContextImpl::getOperandBundleTags(), llvm::GetShadowBytes(), llvm::DependenceInfo::getSplitIteration(), llvm::LLVMContextImpl::getSyncScopeNames(), getTargetConstantBitsFromNode(), getUnmergeResults(), getVPermMask(), llvm::AMDGPULegalizerInfo::handleD16VData(), llvm::ReachingDefAnalysis::init(), llvm::TargetSchedModel::init(), llvm::ResourceManager::init(), llvm::SchedRemainder::init(), llvm::SchedBoundary::init(), INITIALIZE_PASS(), llvm::ResourceManager::initProcResourceVectors(), llvm::mca::InstrBuilder::InstrBuilder(), llvm::ShuffleVectorInst::isInterleaveMask(), llvm::LiveRange::join(), llvm::AMDGPULegalizerInfo::legalizeImageIntrinsic(), llvm::dwarf_linker::parallel::CompileUnit::loadInputDIEs(), llvm::object::ELFFile< ELFT >::loadVersionMap(), llvm::BlockFrequencyInfoImplBase::LoopData::LoopData(), llvm::TargetLowering::LowerCallTo(), LowerCONCAT_VECTORS_i1(), lowerV8I16GeneralSingleInputShuffle(), llvm::Regex::match(), llvm::CombinerHelper::matchCombineInsertVecElts(), llvm::MDBuilder::mergeCallbackEncodings(), llvm::IntervalMapImpl::Path::moveLeft(), llvm::object::ExportEntry::moveNext(), llvm::Triple::normalize(), llvm::RegisterBankInfo::OperandsMapper::OperandsMapper(), packSegmentMask(), parseBuildVersionCommand(), performBlockTailMerging(), llvm::PredicateInfoBuilder::PredicateInfoBuilder(), llvm::PrettyStackTraceFormat::PrettyStackTraceFormat(), llvm::JumpThreadingPass::processBranchOnPHI(), llvm::coverage::RawCoverageMappingReader::read(), llvm::Attributor::registerFunctionSignatureRewrite(), reorderOrder(), llvm::SchedBoundary::reset(), llvm::PagedVector< T, PageSize >::resize(), llvm::IndexedMap< T, ToIndexT >::resize(), llvm::DIInliningInfo::resize(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::ExecutionDomainFix::runOnMachineFunction(), llvm::RAGreedy::runOnMachineFunction(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::LegacyLegalizerInfo::setLegalizeScalarToDifferentSizeStrategy(), llvm::LegacyLegalizerInfo::setLegalizeVectorElementToDifferentSizeStrategy(), llvm::StructType::setName(), SimplifyValuePattern(), and llvm::sortPtrAccesses().
resize() [2/2]
template<typename T > void llvm::SmallVectorImpl< T >::resize (size_type N, ValueParamT NV) inline
Definition at line 663 of file SmallVector.h.
References llvm::SmallVectorImpl< T >::append(), N, llvm::SmallVectorBase< SmallVectorSizeType< T > >::size(), and llvm::SmallVectorImpl< T >::truncate().
resize_for_overwrite()
template<typename T > void llvm::SmallVectorImpl< T >::resize_for_overwrite (size_type N) inline
Like resize, but T is POD, the new values won't be initialized.
Definition at line 654 of file SmallVector.h.
References N.
Referenced by llvm::SmallString< InternalLen >::append(), and llvm::sys::fs::readNativeFileToEOF().
swap()
template<typename T > void llvm::SmallVectorImpl< T >::swap (SmallVectorImpl< T > & RHS)
Definition at line 981 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::BeginX, llvm::SmallVectorBase< Size_T >::BeginX, llvm::SmallVectorBase< SmallVectorSizeType< T > >::Capacity, llvm::SmallVectorBase< Size_T >::Capacity, llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateCommon< T, typename >::isSmall(), llvm::SmallVectorImpl< T >::reserve(), RHS, llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), llvm::SmallVectorBase< Size_T >::Size, llvm::SmallVectorBase< SmallVectorSizeType< T > >::Size, llvm::SmallVectorBase< Size_T >::size(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::size(), std::swap(), and llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy().
Referenced by llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::sys::fs::createUniquePath(), ExpandBVWithShuffles(), llvm::TargetLowering::LowerCallTo(), llvm::sys::fs::make_absolute(), llvm::sys::path::remove_dots(), reorderReuses(), llvm::reorderScalars(), llvm::LiveIntervals::shrinkToUses(), and llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef().
truncate()
template<typename T > void llvm::SmallVectorImpl< T >::truncate (size_type N) inline
Like resize, but requires that N is less than size().
Definition at line 657 of file SmallVector.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), llvm::SmallVectorTemplateCommon< T, typename >::end(), N, llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
Referenced by buildCopyFromRegs(), llvm::AMDGPULegalizerInfo::legalizeBufferLoad(), llvm::SmallVectorImpl< T >::pop_back_n(), llvm::sys::fs::readNativeFileToEOF(), llvm::sys::path::remove_filename(), llvm::sys::path::replace_extension(), and llvm::SmallVectorImpl< T >::resize().
The documentation for this class was generated from the following files:
include/llvm/ADT/APFloat.h
include/llvm/ADT/SmallVector.h