LLVM: llvm::IntrusiveBackList< T > Class Template Reference
llvm::IntrusiveBackList< T > Class Template Reference
#include "llvm/CodeGen/DIE.h"
Classes
class const_iterator
class iterator
Public Member Functions
void push_back (T &N)
void push_front (T &N)
T & back ()
const T & back () const
T & front ()
const T & front () const
void takeNodes (IntrusiveBackList< T > &Other)
bool deleteNode (T &N)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
bool empty () const
Static Public Member Functions
static iterator toIterator (T &N)
static const_iterator toIterator (const T &N)
Detailed Description
template<class T>
class llvm::IntrusiveBackList< T >
Definition at line 563 of file DIE.h.
Member Function Documentation
back() [1/2]
template<class T > T & llvm::IntrusiveBackList< T >::back () inline
Definition at line 570 of file DIE.h.
References llvm::IntrusiveBackListBase::Last.
back() [2/2]
template<class T > const T & llvm::IntrusiveBackList< T >::back () const inline
Definition at line 571 of file DIE.h.
References llvm::IntrusiveBackListBase::Last.
begin() [1/2]
template<class T > iterator llvm::IntrusiveBackList< T >::begin () inline
Definition at line 661 of file DIE.h.
References llvm::IntrusiveBackList< T >::end(), llvm::IntrusiveBackListBase::Last, and llvm::IntrusiveBackListNode::Next.
Referenced by llvm::IntrusiveBackList< T >::begin().
begin() [2/2]
template<class T > const_iterator llvm::IntrusiveBackList< T >::begin () const inline
Definition at line 664 of file DIE.h.
References llvm::IntrusiveBackList< T >::begin().
deleteNode()
template<class T > bool llvm::IntrusiveBackList< T >::deleteNode (T & N) inline
Definition at line 598 of file DIE.h.
References llvm::IntrusiveBackListBase::Last, N, and llvm::IntrusiveBackListNode::Next.
empty()
template<class T > bool llvm::IntrusiveBackListBase::empty () const inline
Definition at line 537 of file DIE.h.
end() [1/2]
template<class T > iterator llvm::IntrusiveBackList< T >::end () inline
Definition at line 667 of file DIE.h.
Referenced by llvm::IntrusiveBackList< T >::begin().
end() [2/2]
template<class T > const_iterator llvm::IntrusiveBackList< T >::end () const inline
Definition at line 668 of file DIE.h.
front() [1/2]
template<class T > T & llvm::IntrusiveBackList< T >::front () inline
Definition at line 572 of file DIE.h.
References llvm::IntrusiveBackListBase::Last, and llvm::IntrusiveBackListNode::Next.
front() [2/2]
template<class T > const T & llvm::IntrusiveBackList< T >::front () const inline
Definition at line 575 of file DIE.h.
References llvm::IntrusiveBackListBase::Last, and llvm::IntrusiveBackListNode::Next.
push_back()
template<class T > void llvm::IntrusiveBackList< T >::push_back (T & N) inline
Definition at line 567 of file DIE.h.
References N, and llvm::IntrusiveBackListBase::push_back().
Referenced by llvm::IntrusiveBackList< T >::takeNodes().
push_front()
template<class T > void llvm::IntrusiveBackList< T >::push_front (T & N) inline
Definition at line 568 of file DIE.h.
References N, and llvm::IntrusiveBackListBase::push_front().
takeNodes()
template<class T > void llvm::IntrusiveBackList< T >::takeNodes (IntrusiveBackList< T > & Other) inline
Definition at line 579 of file DIE.h.
References llvm::Other, and llvm::IntrusiveBackList< T >::push_back().
toIterator() [1/2]
template<class T > static const_iterator llvm::IntrusiveBackList< T >::toIterator (const T & N) inline static
Definition at line 671 of file DIE.h.
References N.
toIterator() [2/2]
template<class T > static iterator llvm::IntrusiveBackList< T >::toIterator (T & N) inline static
Definition at line 670 of file DIE.h.
References N.
The documentation for this class was generated from the following file:
include/llvm/CodeGen/DIE.h