LLVM: llvm::MemorySSA::ClobberWalkerBase Class Reference
llvm::MemorySSA::ClobberWalkerBase Class Reference
Public Member Functions
ClobberWalkerBase (MemorySSA *M, DominatorTree *D)
MemoryAccess * getClobberingMemoryAccessBase (MemoryAccess *, const MemoryLocation &, BatchAAResults &, unsigned &)
Walk the use-def chains starting at StartingAccess and find the MemoryAccess that actually clobbers Loc.
MemoryAccess * getClobberingMemoryAccessBase (MemoryAccess *, BatchAAResults &, unsigned &, bool, bool UseInvariantGroup=true)
Detailed Description
Definition at line 985 of file MemorySSA.cpp.
Constructor & Destructor Documentation
ClobberWalkerBase()
llvm::MemorySSA::ClobberWalkerBase::ClobberWalkerBase (MemorySSA * M, DominatorTree * D) inline
Definition at line 990 of file MemorySSA.cpp.
Member Function Documentation
getClobberingMemoryAccessBase() [1/2]
MemoryAccess * MemorySSA::ClobberWalkerBase::getClobberingMemoryAccessBase (MemoryAccess * MA, BatchAAResults & BAA, unsigned & UpwardWalkLimit, bool SkipSelf, bool UseInvariantGroup = true)
Definition at line 2489 of file MemorySSA.cpp.
References assert(), llvm::dbgs(), llvm::MemorySSA::getDomTree(), getInvariantGroupClobberingInstruction(), llvm::MemorySSA::getLiveOnEntryDef(), llvm::MemorySSA::getMemoryAccess(), I, llvm::MemorySSA::isLiveOnEntryDef(), isUseTriviallyOptimizableToLiveOnEntry(), and LLVM_DEBUG.
getClobberingMemoryAccessBase() [2/2]
MemoryAccess * MemorySSA::ClobberWalkerBase::getClobberingMemoryAccessBase (MemoryAccess * StartingAccess, const MemoryLocation & Loc, BatchAAResults & BAA, unsigned & UpwardWalkLimit)
Walk the use-def chains starting at StartingAccess and find the MemoryAccess that actually clobbers Loc.
Returns
our clobbering memory access
Definition at line 2388 of file MemorySSA.cpp.
References assert(), llvm::dbgs(), I, llvm::MemorySSA::isLiveOnEntryDef(), LLVM_DEBUG, and llvm::MemoryLocation::Ptr.
The documentation for this class was generated from the following file:
lib/Analysis/MemorySSA.cpp