LLVM: llvm::object::Record Class Reference
llvm::object::Record Class Reference
Represents a GOFF physical record.
#include "llvm/Object/GOFF.h"
Static Public Member Functions
static Error getContinuousData (const uint8_t *Record, uint16_t DataLength, int DataIndex, SmallString< 256 > &CompleteData)
static bool isContinued (const uint8_t *Record)
static bool isContinuation (const uint8_t *Record)
Static Protected Member Functions
static void getBits (const uint8_t *Bytes, uint8_t ByteIndex, uint8_t BitIndex, uint8_t Length, uint8_t &Value)
Get bit field of specified byte.
template<class T >
static void get (const uint8_t *Bytes, uint8_t ByteIndex, T &Value)
Detailed Description
Represents a GOFF physical record.
Specifies protected member functions to manipulate the record. These should be called from deriving classes to change values as that record specifies.
Definition at line 31 of file GOFF.h.
Member Function Documentation
get()
template<class T > static void llvm::object::Record::get (const uint8_t * Bytes, uint8_t ByteIndex, T & Value) inline static protected
Definition at line 69 of file GOFF.h.
References assert(), and llvm::GOFF::RecordLength.
getBits()
static void llvm::object::Record::getBits (const uint8_t * Bytes, uint8_t ByteIndex, uint8_t BitIndex, uint8_t Length, uint8_t & Value) inline static protected
Get bit field of specified byte.
Used to pack bit fields into one byte. Fields are packed left to right. Bit index zero is the most significant bit of the byte.
Parameters
ByteIndex index of byte the field is in.
BitIndex index of first bit of field.
Length length of bit field.
Value value of bit field.
Definition at line 58 of file GOFF.h.
References assert(), llvm::Length, and llvm::GOFF::RecordLength.
Referenced by llvm::object::ESDRecord::getAlignment(), llvm::object::ESDRecord::getBindingAlgorithm(), llvm::object::ESDRecord::getBindingScope(), llvm::object::ESDRecord::getBindingStrength(), llvm::object::ESDRecord::getDuplicateSeverity(), llvm::object::ESDRecord::getExecutable(), llvm::object::ESDRecord::getFillBytePresent(), llvm::object::ESDRecord::getIndirectReference(), llvm::object::ESDRecord::getLinkageType(), llvm::object::ESDRecord::getLoadingBehavior(), llvm::object::ESDRecord::getNameMangled(), llvm::object::ESDRecord::getReadOnly(), llvm::object::ESDRecord::getRemovable(), llvm::object::ESDRecord::getRenamable(), llvm::object::ESDRecord::getTaskingBehavior(), llvm::object::ESDRecord::getTextStyle(), isContinuation(), and isContinued().
getContinuousData()
Error Record::getContinuousData (const uint8_t * Record, uint16_t DataLength, int DataIndex, SmallString< 256 > & CompleteData) static
Definition at line 439 of file GOFFObjectFile.cpp.
References llvm::SmallString< InternalLen >::append(), assert(), llvm::createStringError(), isContinuation(), isContinued(), llvm::object::parse_failed, llvm::GOFF::PayloadLength, llvm::GOFF::RecordLength, llvm::GOFF::RecordPrefixLength, and llvm::Error::success().
Referenced by llvm::object::HDRRecord::getData(), llvm::object::ESDRecord::getData(), and llvm::object::ENDRecord::getData().
isContinuation()
static bool llvm::object::Record::isContinuation (const uint8_t * Record) inline static
Definition at line 42 of file GOFF.h.
References getBits().
Referenced by getContinuousData().
isContinued()
static bool llvm::object::Record::isContinued (const uint8_t * Record) inline static
Definition at line 36 of file GOFF.h.
References getBits().
Referenced by getContinuousData().
The documentation for this class was generated from the following files:
include/llvm/Object/GOFF.h
lib/Object/GOFFObjectFile.cpp