LLVM: llvm::orc::EPCGenericMemoryAccess Class Reference
llvm::orc::EPCGenericMemoryAccess Class Reference
#include "llvm/ExecutionEngine/Orc/EPCGenericMemoryAccess.h"
Classes
struct FuncAddrs
Function addresses for memory access.
Public Member Functions
EPCGenericMemoryAccess (ExecutorProcessControl &EPC, FuncAddrs FAs)
Create an EPCGenericMemoryAccess instance from a given set of function addrs.
void writeUInt8sAsync (ArrayRef< tpctypes::UInt8Write > Ws, WriteResultFn OnWriteComplete) override
void writeUInt16sAsync (ArrayRef< tpctypes::UInt16Write > Ws, WriteResultFn OnWriteComplete) override
void writeUInt32sAsync (ArrayRef< tpctypes::UInt32Write > Ws, WriteResultFn OnWriteComplete) override
void writeUInt64sAsync (ArrayRef< tpctypes::UInt64Write > Ws, WriteResultFn OnWriteComplete) override
void writeBuffersAsync (ArrayRef< tpctypes::BufferWrite > Ws, WriteResultFn OnWriteComplete) override
void writePointersAsync (ArrayRef< tpctypes::PointerWrite > Ws, WriteResultFn OnWriteComplete) override
Public Member Functions inherited from llvm::orc::ExecutorProcessControl::MemoryAccess
virtual ~MemoryAccess ()
virtual void writeUInt8sAsync (ArrayRef< tpctypes::UInt8Write > Ws, WriteResultFn OnWriteComplete)=0
virtual void writeUInt16sAsync (ArrayRef< tpctypes::UInt16Write > Ws, WriteResultFn OnWriteComplete)=0
virtual void writeUInt32sAsync (ArrayRef< tpctypes::UInt32Write > Ws, WriteResultFn OnWriteComplete)=0
virtual void writeUInt64sAsync (ArrayRef< tpctypes::UInt64Write > Ws, WriteResultFn OnWriteComplete)=0
virtual void writeBuffersAsync (ArrayRef< tpctypes::BufferWrite > Ws, WriteResultFn OnWriteComplete)=0
virtual void writePointersAsync (ArrayRef< tpctypes::PointerWrite > Ws, WriteResultFn OnWriteComplete)=0
Error writeUInt8s (ArrayRef< tpctypes::UInt8Write > Ws)
Error writeUInt16s (ArrayRef< tpctypes::UInt16Write > Ws)
Error writeUInt32s (ArrayRef< tpctypes::UInt32Write > Ws)
Error writeUInt64s (ArrayRef< tpctypes::UInt64Write > Ws)
Error writeBuffers (ArrayRef< tpctypes::BufferWrite > Ws)
Error writePointers (ArrayRef< tpctypes::PointerWrite > Ws)
Additional Inherited Members
Public Types inherited from llvm::orc::ExecutorProcessControl::MemoryAccess
using WriteResultFn = unique_function< void(Error)>
Callback function for asynchronous writes.
Detailed Description
Definition at line 26 of file EPCGenericMemoryAccess.h.
Constructor & Destructor Documentation
EPCGenericMemoryAccess()
llvm::orc::EPCGenericMemoryAccess::EPCGenericMemoryAccess (ExecutorProcessControl & EPC, FuncAddrs FAs) inline
Create an EPCGenericMemoryAccess instance from a given set of function addrs.
Definition at line 40 of file EPCGenericMemoryAccess.h.
Member Function Documentation
writeBuffersAsync()
void llvm::orc::EPCGenericMemoryAccess::writeBuffersAsync (ArrayRef< tpctypes::BufferWrite > Ws, WriteResultFn OnWriteComplete) inline override virtual
Implements llvm::orc::ExecutorProcessControl::MemoryAccess.
Definition at line 71 of file EPCGenericMemoryAccess.h.
References llvm::orc::ExecutorProcessControl::callSPSWrapperAsync(), and llvm::orc::EPCGenericMemoryAccess::FuncAddrs::WriteBuffers.
writePointersAsync()
void llvm::orc::EPCGenericMemoryAccess::writePointersAsync (ArrayRef< tpctypes::PointerWrite > Ws, WriteResultFn OnWriteComplete) inline override virtual
Implements llvm::orc::ExecutorProcessControl::MemoryAccess.
Definition at line 78 of file EPCGenericMemoryAccess.h.
References llvm::orc::ExecutorProcessControl::callSPSWrapperAsync(), and llvm::orc::EPCGenericMemoryAccess::FuncAddrs::WritePointers.
writeUInt16sAsync()
void llvm::orc::EPCGenericMemoryAccess::writeUInt16sAsync (ArrayRef< tpctypes::UInt16Write > Ws, WriteResultFn OnWriteComplete) inline override virtual
Implements llvm::orc::ExecutorProcessControl::MemoryAccess.
Definition at line 50 of file EPCGenericMemoryAccess.h.
References llvm::orc::ExecutorProcessControl::callSPSWrapperAsync(), and llvm::orc::EPCGenericMemoryAccess::FuncAddrs::WriteUInt16s.
writeUInt32sAsync()
void llvm::orc::EPCGenericMemoryAccess::writeUInt32sAsync (ArrayRef< tpctypes::UInt32Write > Ws, WriteResultFn OnWriteComplete) inline override virtual
Implements llvm::orc::ExecutorProcessControl::MemoryAccess.
Definition at line 57 of file EPCGenericMemoryAccess.h.
References llvm::orc::ExecutorProcessControl::callSPSWrapperAsync(), and llvm::orc::EPCGenericMemoryAccess::FuncAddrs::WriteUInt32s.
writeUInt64sAsync()
void llvm::orc::EPCGenericMemoryAccess::writeUInt64sAsync (ArrayRef< tpctypes::UInt64Write > Ws, WriteResultFn OnWriteComplete) inline override virtual
Implements llvm::orc::ExecutorProcessControl::MemoryAccess.
Definition at line 64 of file EPCGenericMemoryAccess.h.
References llvm::orc::ExecutorProcessControl::callSPSWrapperAsync(), and llvm::orc::EPCGenericMemoryAccess::FuncAddrs::WriteUInt64s.
writeUInt8sAsync()
void llvm::orc::EPCGenericMemoryAccess::writeUInt8sAsync (ArrayRef< tpctypes::UInt8Write > Ws, WriteResultFn OnWriteComplete) inline override virtual
Implements llvm::orc::ExecutorProcessControl::MemoryAccess.
Definition at line 43 of file EPCGenericMemoryAccess.h.
References llvm::orc::ExecutorProcessControl::callSPSWrapperAsync(), and llvm::orc::EPCGenericMemoryAccess::FuncAddrs::WriteUInt8s.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/EPCGenericMemoryAccess.h