LLVM: llvm::LoongArchAsmBackend Class Reference
llvm::LoongArchAsmBackend Class Reference
#include "Target/LoongArch/MCTargetDesc/LoongArchAsmBackend.h"
Public Member Functions
LoongArchAsmBackend (const MCSubtargetInfo &STI, uint8_t OSABI, bool Is64Bit, const MCTargetOptions &Options)
~LoongArchAsmBackend () override
bool handleAddSubRelocations (const MCAsmLayout &Layout, const MCFragment &F, const MCFixup &Fixup, const MCValue &Target, uint64_t &FixedValue) const override
void applyFixup (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo *STI) const override
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
bool shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment &AF, unsigned &Size) override
Hook to check if extra nop bytes must be inserted for alignment directive.
bool shouldInsertFixupForCodeAlign (MCAssembler &Asm, const MCAsmLayout &Layout, MCAlignFragment &AF) override
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
bool shouldForceRelocation (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, const MCSubtargetInfo *STI) override
Hook to check if a relocation is needed for some target specific reason.
bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout) const override
Simple predicate for targets where !Resolved implies requiring relaxation.
unsigned getNumFixupKinds () const override
Get the number of target specific fixup kinds.
std::optional< MCFixupKind > getFixupKind (StringRef Name) const override
Map a relocation name used in .reloc to a fixup kind.
const MCFixupKindInfo & getFixupKindInfo (MCFixupKind Kind) const override
Get information on a fixup kind.
void relaxInstruction (MCInst &Inst, const MCSubtargetInfo &STI) const override
Relax the instruction in the given fragment to the next wider instruction.
std::pair< bool, bool > relaxLEB128 (MCLEBFragment &LF, MCAsmLayout &Layout, int64_t &Value) const override
bool relaxDwarfLineAddr (MCDwarfLineAddrFragment &DF, MCAsmLayout &Layout, bool &WasRelaxed) const override
bool relaxDwarfCFA (MCDwarfCallFrameFragment &DF, MCAsmLayout &Layout, bool &WasRelaxed) const override
bool writeNopData (raw_ostream &OS, uint64_t Count, const MCSubtargetInfo *STI) const override
Write an (optimal) nop sequence of Count bytes to the given output.
std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const override
const MCTargetOptions & getTargetOptions () const
DenseMap< MCSection *, const MCSymbolRefExpr * > & getSecToAlignSym ()
Public Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
virtual bool allowAutoPadding () const
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
virtual bool allowEnhancedRelaxation () const
Return true if this target allows an unrelaxable instruction to be emitted into RelaxableFragment and then we can increase its size in a tricky way for optimization.
virtual void emitInstructionBegin (MCObjectStreamer &OS, const MCInst &Inst, const MCSubtargetInfo &STI)
Give the target a chance to manipulate state related to instruction alignment (e.g.
virtual void emitInstructionEnd (MCObjectStreamer &OS, const MCInst &Inst)
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const =0
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual unsigned getMaximumNopSize (const MCSubtargetInfo &STI) const
Returns the maximum size of a nop in bytes on this target.
virtual bool writeNopData (raw_ostream &OS, uint64_t Count, const MCSubtargetInfo *STI) const =0
Write an (optimal) nop sequence of Count bytes to the given output.
virtual void finishLayout (MCAssembler const &Asm, MCAsmLayout &Layout) const
Give backend an opportunity to finish layout after relaxation.
virtual void handleAssemblerFlag (MCAssemblerFlag Flag)
Handle any target-specific assembler flags. By default, do nothing.
virtual uint32_t generateCompactUnwindEncoding (const MCDwarfFrameInfo *FI, const MCContext *Ctxt) const
Generate the compact unwind encoding for the CFI instructions.
virtual bool isMicroMips (const MCSymbol *Sym) const
Check whether a given symbol has been flagged with MICROMIPS flag.
bool isDarwinCanonicalPersonality (const MCSymbol *Sym) const
virtual bool evaluateTargetFixup (const MCAssembler &Asm, const MCAsmLayout &Layout, const MCFixup &Fixup, const MCFragment *DF, const MCValue &Target, const MCSubtargetInfo *STI, uint64_t &Value, bool &WasForced)
virtual bool mayNeedRelaxation (const MCInst &Inst, const MCSubtargetInfo &STI) const
Check whether the given instruction may need relaxation.
virtual bool fixupNeedsRelaxationAdvanced (const MCFixup &Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout, const bool WasForced) const
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
Additional Inherited Members
Public Attributes inherited from llvm::MCAsmBackend
const llvm::endianness Endian
const unsigned RelaxFixupKind
Fixup kind used for linker relaxation. Currently only used by RISC-V.
Protected Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (llvm::endianness Endian, unsigned RelaxFixupKind=MaxFixupKind)
Detailed Description
Definition at line 27 of file LoongArchAsmBackend.h.
Constructor & Destructor Documentation
LoongArchAsmBackend()
llvm::LoongArchAsmBackend::LoongArchAsmBackend (const MCSubtargetInfo & STI, uint8_t OSABI, bool Is64Bit, const MCTargetOptions & Options) inline
Definition at line 35 of file LoongArchAsmBackend.h.
~LoongArchAsmBackend()
llvm::LoongArchAsmBackend::~LoongArchAsmBackend () inline override
Definition at line 40 of file LoongArchAsmBackend.h.
Member Function Documentation
applyFixup()
void LoongArchAsmBackend::applyFixup (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo * STI) const override virtual
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
Errors (such as an out of range fixup value) should be reported via Ctx. The STI is present only for fragments of type MCRelaxableFragment and MCDataFragment with hasInstructions() == true.
Implements llvm::MCAsmBackend.
Definition at line 146 of file LoongArchAsmBackend.cpp.
References adjustFixupValue(), llvm::alignTo(), assert(), llvm::Data, llvm::FirstLiteralRelocationKind, Fixup, fixupLeb128(), llvm::FK_Data_leb128, getFixupKindInfo(), I, Info, and llvm::Offset.
createObjectTargetWriter()
std::unique_ptr< MCObjectTargetWriter > LoongArchAsmBackend::createObjectTargetWriter () const override virtual
Implements llvm::MCAsmBackend.
Definition at line 508 of file LoongArchAsmBackend.cpp.
References llvm::createLoongArchELFObjectWriter(), and llvm::MCSubtargetInfo::hasFeature().
fixupNeedsRelaxation()
bool llvm::LoongArchAsmBackend::fixupNeedsRelaxation (const MCFixup & Fixup, uint64_t Value, const MCRelaxableFragment * DF, const MCAsmLayout & Layout) const inline override virtual
Simple predicate for targets where !Resolved implies requiring relaxation.
Implements llvm::MCAsmBackend.
Definition at line 64 of file LoongArchAsmBackend.h.
getFixupKind()
std::optional< MCFixupKind > LoongArchAsmBackend::getFixupKind (StringRef Name) const override virtual
Map a relocation name used in .reloc to a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 32 of file LoongArchAsmBackend.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::FirstLiteralRelocationKind, llvm::MCSubtargetInfo::getTargetTriple(), llvm::Triple::isOSBinFormatELF(), and Name.
getFixupKindInfo()
const MCFixupKindInfo & LoongArchAsmBackend::getFixupKindInfo (MCFixupKind Kind) const override virtual
Get information on a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 49 of file LoongArchAsmBackend.cpp.
References assert(), llvm::FirstLiteralRelocationKind, llvm::FirstTargetFixupKind, llvm::FK_NONE, llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::MCAsmBackend::getFixupKindInfo(), getNumFixupKinds(), and llvm::LoongArch::NumTargetFixupKinds.
Referenced by applyFixup().
getNumFixupKinds()
unsigned llvm::LoongArchAsmBackend::getNumFixupKinds () const inline override virtual
Get the number of target specific fixup kinds.
Implements llvm::MCAsmBackend.
Definition at line 70 of file LoongArchAsmBackend.h.
References llvm::LoongArch::NumTargetFixupKinds.
Referenced by getFixupKindInfo().
getSecToAlignSym()
DenseMap< MCSection *, const MCSymbolRefExpr * > & llvm::LoongArchAsmBackend::getSecToAlignSym () inline
Definition at line 95 of file LoongArchAsmBackend.h.
Referenced by shouldInsertFixupForCodeAlign().
getTargetOptions()
const MCTargetOptions & llvm::LoongArchAsmBackend::getTargetOptions () const inline
Definition at line 94 of file LoongArchAsmBackend.h.
handleAddSubRelocations()
bool LoongArchAsmBackend::handleAddSubRelocations (const MCAsmLayout & Layout, const MCFragment & F, const MCFixup & Fixup, const MCValue & Target, uint64_t & FixedValue) const override virtual
Reimplemented from llvm::MCAsmBackend.
Definition at line 448 of file LoongArchAsmBackend.cpp.
References A, B, llvm::MCFixup::create(), F, Fixup, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_Data_leb128, llvm::MCValue::get(), llvm::MCAsmLayout::getAssembler(), getRelocPairForSize(), llvm::MCSymbol::getSection(), llvm::MCSubtargetInfo::hasFeature(), llvm::MCSymbol::isInSection(), and llvm_unreachable.
relaxDwarfCFA()
bool LoongArchAsmBackend::relaxDwarfCFA (MCDwarfCallFrameFragment & DF, MCAsmLayout & Layout, bool & WasRelaxed) const override virtual
Reimplemented from llvm::MCAsmBackend.
Definition at line 375 of file LoongArchAsmBackend.cpp.
References assert(), llvm::MCFixup::create(), llvm::Data, DF, llvm::MCExpr::evaluateKnownAbsolute(), llvm::MCContext::getAsmInfo(), llvm::MCAsmLayout::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCBinaryExpr::getLHS(), llvm::MCAsmInfo::getMinInstAlignment(), getRelocPairForSize(), llvm::MCBinaryExpr::getRHS(), llvm::isUIntN(), llvm::little, llvm_unreachable, llvm::Offset, and OS.
relaxDwarfLineAddr()
bool LoongArchAsmBackend::relaxDwarfLineAddr (MCDwarfLineAddrFragment & DF, MCAsmLayout & Layout, bool & WasRelaxed) const override virtual
Reimplemented from llvm::MCAsmBackend.
Definition at line 307 of file LoongArchAsmBackend.cpp.
References assert(), llvm::CallingConv::C, llvm::MCFixup::create(), llvm::Data, DF, llvm::encodeSLEB128(), llvm::encodeULEB128(), llvm::MCExpr::evaluateKnownAbsolute(), llvm::MCAsmLayout::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCBinaryExpr::getLHS(), getRelocPairForSize(), llvm::MCBinaryExpr::getRHS(), INT64_MAX, llvm::little, llvm::Offset, OS, llvm::raw_ostream::tell(), and llvm::raw_ostream::write_zeros().
relaxInstruction()
void llvm::LoongArchAsmBackend::relaxInstruction (MCInst & Inst, const MCSubtargetInfo & STI) const inline override virtual
Relax the instruction in the given fragment to the next wider instruction.
Parameters
[out] Inst The instruction to relax, which is also the relaxed instruction.
STI the subtarget information for the associated instruction.
Reimplemented from llvm::MCAsmBackend.
Definition at line 78 of file LoongArchAsmBackend.h.
relaxLEB128()
std::pair< bool, bool > LoongArchAsmBackend::relaxLEB128 (MCLEBFragment & LF, MCAsmLayout & Layout, int64_t & Value) const override virtual
Reimplemented from llvm::MCAsmBackend.
Definition at line 296 of file LoongArchAsmBackend.cpp.
References llvm::MCFixup::create(), llvm::MCExpr::evaluateKnownAbsolute(), llvm::FK_Data_leb128, llvm::MCEncodedFragmentWithFixups< ContentsSize, FixupsSize >::getFixups(), llvm::MCExpr::getLoc(), llvm::MCLEBFragment::getValue(), and llvm::MCLEBFragment::isSigned().
shouldForceRelocation()
bool LoongArchAsmBackend::shouldForceRelocation (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target, const MCSubtargetInfo * STI) override virtual
Hook to check if a relocation is needed for some target specific reason.
Reimplemented from llvm::MCAsmBackend.
Definition at line 246 of file LoongArchAsmBackend.cpp.
References llvm::FirstLiteralRelocationKind, Fixup, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_Data_leb128, and llvm::MCSubtargetInfo::hasFeature().
shouldInsertExtraNopBytesForCodeAlign()
bool LoongArchAsmBackend::shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment & AF, unsigned & Size) override virtual
Hook to check if extra nop bytes must be inserted for alignment directive.
For some targets this may be necessary in order to support linker relaxation. The number of bytes to insert are returned in Size.
Reimplemented from llvm::MCAsmBackend.
Definition at line 186 of file LoongArchAsmBackend.cpp.
References llvm::MCAlignFragment::getAlignment(), llvm::MCAlignFragment::getMaxBytesToEmit(), llvm::MCAlignFragment::getSubtargetInfo(), llvm::MCSubtargetInfo::hasFeature(), Size, and llvm::Align::value().
Referenced by shouldInsertFixupForCodeAlign().
shouldInsertFixupForCodeAlign()
bool LoongArchAsmBackend::shouldInsertFixupForCodeAlign (MCAssembler & Asm, const MCAsmLayout & Layout, MCAlignFragment & AF) override virtual
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
Reimplemented from llvm::MCAsmBackend.
Definition at line 209 of file LoongArchAsmBackend.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCConstantExpr::create(), llvm::MCFixup::create(), llvm::MCContext::createNamedTempSymbol(), Fixup, llvm::LoongArch::fixup_loongarch_align, llvm::MCValue::get(), llvm::MCSection::getBeginSymbol(), llvm::MCSymbol::getFragment(), llvm::MCAlignFragment::getMaxBytesToEmit(), llvm::MCFragment::getParent(), getSecToAlignSym(), llvm::MCAlignFragment::getSubtargetInfo(), llvm::MCSubtargetInfo::hasFeature(), llvm::Hi, llvm::Lo, llvm::Log2_64(), shouldInsertExtraNopBytesForCodeAlign(), and Sym.
writeNopData()
bool LoongArchAsmBackend::writeNopData (raw_ostream & OS, uint64_t Count, const MCSubtargetInfo * STI) const override virtual
Write an (optimal) nop sequence of Count bytes to the given output.
If the target cannot generate such a sequence, it should return an error.
Returns
- True on success.
Implements llvm::MCAsmBackend.
Definition at line 434 of file LoongArchAsmBackend.cpp.
References OS, llvm::raw_ostream::write(), and llvm::raw_ostream::write_zeros().
The documentation for this class was generated from the following files:
lib/Target/LoongArch/MCTargetDesc/LoongArchAsmBackend.h
lib/Target/LoongArch/MCTargetDesc/LoongArchAsmBackend.cpp