LLVM: llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT > Class Template Reference
llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT > Class Template Reference
Base class for DenseSet and DenseSmallSet.
#include "llvm/ADT/DenseSet.h"
Inherited by llvm::DenseSet< Function * >, llvm::DenseSet< T >, llvm::DenseSet< const Value * >, llvm::DenseSet< llvm::Instruction * >, llvm::DenseSet< llvm::BasicBlock * >, llvm::DenseSet< const llvm::MachineInstr * >, llvm::DenseSet< ArrayRef< unsigned > >, llvm::DenseSet< MachineInstr * >, llvm::DenseSet< DebugVariable >, llvm::DenseSet< unsigned >, llvm::DenseSet< DepTy >, llvm::DenseSet< llvm::Function * >, llvm::DenseSet< const llvm::Function * >, llvm::DenseSet< llvm::WeakVH >, llvm::DenseSet< llvm::AbstractAttribute * >, llvm::DenseSet< const char * >, llvm::DenseSet< BasicBlockCallbackVH, llvm::DenseMapInfo< llvm::Value * > >, llvm::DenseSet< Value * >, llvm::DenseSet< llvm::MCSectionCOFF * >, llvm::DenseSet< const llvm::DISubprogram * >, llvm::DenseSet< ConstantClass *, MapInfo >, llvm::DenseSet< EdgeType * >, llvm::DenseSet< uint64_t >, llvm::DenseSet< llvm::DWARFDebugNames::Abbrev, AbbrevMapInfo >, llvm::DenseSet< llvm::GlobalValue * >, llvm::DenseSet< llvm::Register >, llvm::DenseSet< const llvm::BasicBlock * >, llvm::DenseSet< const llvm::GCOVBlock * >, llvm::DenseSet< const BlockT * >, llvm::DenseSet< llvm::StructType * >, llvm::DenseSet< llvm::StructType *, StructTypeKeyInfo >, llvm::DenseSet< const llvm::Instruction * >, llvm::DenseSet< const SmallPtrSet< Instruction *, 4 > * >, llvm::DenseSet< IntPtrT >, llvm::DenseSet< llvm::DIArgList *, llvm::DIArgListInfo >, llvm::DenseSet< ConstantArray *, MapInfo >, llvm::DenseSet< ConstantStruct *, MapInfo >, llvm::DenseSet< ConstantVector *, MapInfo >, llvm::DenseSet< llvm::ConstantExpr *, MapInfo >, llvm::DenseSet< llvm::InlineAsm *, MapInfo >, llvm::DenseSet< FunctionType *, FunctionTypeKeyInfo >, llvm::DenseSet< StructType *, AnonStructTypeKeyInfo >, llvm::DenseSet< TargetExtType *, TargetExtTypeKeyInfo >, llvm::DenseSet< std::pair< llvm::BasicBlock *, llvm::Value * > >, llvm::DenseSet< llvm::MCSection * >, llvm::DenseSet< llvm::StringRef >, llvm::DenseSet< const llvm::LazyCallGraph::Node * >, llvm::DenseSet< llvm::MachineConstantPoolValue * >, llvm::DenseSet< PointerIntPair< const Instruction *, 1, ExplorationDirection > >, llvm::DenseSet< llvm::SUnit * >, llvm::DenseSet< PoolEntry *, PoolEntryDSInfo >, llvm::DenseSet< PhiValuesCallbackVH, llvm::DenseMapInfo< llvm::Value * > >, llvm::DenseSet< MemberTy >, llvm::DenseSet< std::pair< llvm::BasicBlock *, llvm::BasicBlock * > >, llvm::DenseSet< const llvm::LiveInterval * >, llvm::DenseSet< AssertingVH< Instruction > >, llvm::DenseSet< llvm::Value * >, llvm::DenseSet< Edge >, llvm::DenseSet< llvm::AssertingVH< llvm::Value > >, llvm::DenseSet< llvm::AssertingVH< llvm::PHINode > >, llvm::DenseSet< llvm::MachineInstr * >, llvm::DenseSet< Register >, llvm::DenseSet< BaseTy >, llvm::DenseSet< llvm::Init * >, llvm::DenseSet< const llvm::Value * >, llvm::DenseSet< const llvm::MDNode * >, llvm::DenseSet< llvm::AttributeList >, llvm::DenseSet< llvm::Type * >, llvm::DenseSet< llvm::ElementCount >, llvm::DenseSet< DeclContext *, DeclMapInfo >, llvm::DenseSet< uint32_t >, llvm::DenseSet< Symbol * >, llvm::DenseSet< Block * >, llvm::DenseSet< llvm::CachedHashStringRef >, llvm::DenseSet< SymbolStringPtr >, llvm::DenseSet< void * >, llvm::DenseSet< llvm::codeview::CVRecord, llvm::pdb::SymbolDenseMapInfo >, llvm::DenseSet< const EdgeType * >, llvm::DenseSet< const TreeEntry * >, llvm::DenseSet< size_t >, llvm::DenseSet< ScheduleData * >, llvm::SmallDenseSet< llvm::Value * >, llvm::SmallDenseSet< std::pair< llvm::LazyCallGraph::Node *, llvm::LazyCallGraph::SCC * >, 4 >, llvm::SmallDenseSet< llvm::DomTreeNodeBase, 8 >, llvm::SmallDenseSet< std::pair< llvm::BasicBlock *, llvm::BasicBlock * >, 8 >, llvm::DenseSet< ValueT, ValueInfoT >, and llvm::SmallDenseSet< ValueT, InlineBuckets, ValueInfoT >.
Classes
class ConstIterator
class Iterator
Public Types
using key_type = ValueT
using value_type = ValueT
using size_type = unsigned
using iterator = Iterator
using const_iterator = ConstIterator
Public Member Functions
DenseSetImpl (unsigned InitialReserve=0)
template<typename InputIt >
DenseSetImpl (const InputIt &I, const InputIt &E)
DenseSetImpl (std::initializer_list< ValueT > Elems)
bool empty () const
size_type size () const
size_t getMemorySize () const
void resize (size_t Size)
Grow the DenseSet so that it has at least Size buckets.
void reserve (size_t Size)
Grow the DenseSet so that it can contain at least NumEntries items before resizing again.
void clear ()
size_type count (const_arg_type_t< ValueT > V) const
Return 1 if the specified key is in the set, 0 otherwise.
bool erase (const ValueT &V)
void swap (DenseSetImpl &RHS)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
iterator find (const_arg_type_t< ValueT > V)
const_iterator find (const_arg_type_t< ValueT > V) const
bool contains (const_arg_type_t< ValueT > V) const
Check if the set contains the given element.
template<class LookupKeyT >
iterator find_as (const LookupKeyT &Val)
Alternative version of find() which allows a different, and possibly less expensive, key type.
template<class LookupKeyT >
const_iterator find_as (const LookupKeyT &Val) const
void erase (Iterator I)
void erase (ConstIterator CI)
std::pair< iterator, bool > insert (const ValueT &V)
std::pair< iterator, bool > insert (ValueT &&V)
template<typename LookupKeyT >
std::pair< iterator, bool > insert_as (const ValueT &V, const LookupKeyT &LookupKey)
Alternative version of insert that uses a different (and possibly less expensive) key type.
template<typename LookupKeyT >
std::pair< iterator, bool > insert_as (ValueT &&V, const LookupKeyT &LookupKey)
template<typename InputIt >
void insert (InputIt I, InputIt E)
Detailed Description
template<typename ValueT, typename MapTy, typename ValueInfoT>
class llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >
Base class for DenseSet and DenseSmallSet.
MapTy should be either
DenseMap<ValueT, detail::DenseSetEmpty, ValueInfoT, detail::DenseSetPair<ValueT>>
or the equivalent SmallDenseMap type. ValueInfoT must implement the DenseMapInfo "concept".
Definition at line 54 of file DenseSet.h.
Member Typedef Documentation
const_iterator
template<typename ValueT , typename MapTy , typename ValueInfoT > using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::const_iterator = ConstIterator
Definition at line 171 of file DenseSet.h.
iterator
template<typename ValueT , typename MapTy , typename ValueInfoT > using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::iterator = Iterator
Definition at line 170 of file DenseSet.h.
key_type
template<typename ValueT , typename MapTy , typename ValueInfoT > using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::key_type = ValueT
Definition at line 63 of file DenseSet.h.
size_type
template<typename ValueT , typename MapTy , typename ValueInfoT > using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::size_type = unsigned
Definition at line 65 of file DenseSet.h.
value_type
template<typename ValueT , typename MapTy , typename ValueInfoT > using llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::value_type = ValueT
Definition at line 64 of file DenseSet.h.
Constructor & Destructor Documentation
DenseSetImpl() [1/3]
template<typename ValueT , typename MapTy , typename ValueInfoT > llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::DenseSetImpl (unsigned InitialReserve = 0) inline explicit
Definition at line 67 of file DenseSet.h.
DenseSetImpl() [2/3]
template<typename ValueT , typename MapTy , typename ValueInfoT > template<typename InputIt > llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::DenseSetImpl (const InputIt & I, const InputIt & E) inline
Definition at line 70 of file DenseSet.h.
References E, I, and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
DenseSetImpl() [3/3]
template<typename ValueT , typename MapTy , typename ValueInfoT > llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::DenseSetImpl (std::initializer_list< ValueT > Elems) inline
Definition at line 75 of file DenseSet.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
Member Function Documentation
begin() [1/2]
template<typename ValueT , typename MapTy , typename ValueInfoT > iterator llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::begin () inline
Definition at line 173 of file DenseSet.h.
Referenced by llvm::jitlink::LinkGraph::absolute_symbols(), checkHoistValue(), CheckLargerCands(), llvm::ComputeCrossModuleImport(), llvm::computeEHOnlyBlocks(), llvm::MDBuilder::createFunctionEntryCount(), and llvm::jitlink::Section::symbols().
begin() [2/2]
template<typename ValueT , typename MapTy , typename ValueInfoT > const_iterator llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::begin () const inline
Definition at line 176 of file DenseSet.h.
clear()
template<typename ValueT , typename MapTy , typename ValueInfoT > void llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::clear () inline
Definition at line 92 of file DenseSet.h.
Referenced by checkNumberingAndReplace(), llvm::FunctionLoweringInfo::clear(), llvm::TypeFinder::clear(), llvm::SPIRV::RequirementHandler::clear(), llvm::slpvectorizer::BoUpSLP::clearReductionData(), llvm::computeEHOnlyBlocks(), DPValuesRemoveRedundantDbgInstrsUsingBackwardScan(), EliminateDuplicatePHINodesSetBasedImpl(), TransferTracker::loadInlocs(), reduceDbgValsBackwardScan(), removeRedundantDbgInstrsUsingBackwardScan(), llvm::objcopy::coff::Object::removeSections(), llvm::ModuleToPostOrderCGSCCPassAdaptor::run(), and llvm::OutlinableRegion::splitCandidate().
contains()
template<typename ValueT , typename MapTy , typename ValueInfoT > bool llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::contains (const_arg_type_t< ValueT > V) const inline
Check if the set contains the given element.
Definition at line 185 of file DenseSet.h.
Referenced by llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), llvm::lto::Config::addSaveTemps(), analyzeExitPHIsForOutputUses(), llvm::slpvectorizer::BoUpSLP::areAnalyzedReductionVals(), buildOverlapMapAndRecordDeclares(), checkNumberingAndReplace(), checkNumberingAndReplaceCommutative(), llvm::IRSimilarity::IRSimilarityCandidate::checkRelativeLocations(), collectRegionsConstants(), llvm::SelectionDAG::copyExtraInfo(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalRelationFrom(), DPValuesRemoveUndefDbgAssignsFromEntryBlock(), findConstants(), findCostForOutputBlocks(), findExtractedOutputToOverallOutputMapping(), findOrCreatePHIInBlock(), getBranchInsertPoint(), getFormForIdxParent(), llvm::SPIRV::ModuleAnalysisInfo::getSkipEmission(), llvm::DIExpression::hasAllLocationOps(), llvm::slpvectorizer::BoUpSLP::isAnyGathered(), llvm::InstCostVisitor::isBlockExecutable(), llvm::SPIRV::RequirementHandler::isCapabilityAvailable(), llvm::objcopy::NameMatcher::matches(), processLoadCommands(), processSwitches(), propagateAttributesToRefs(), llvm::PHINode::removeIncomingValueIf(), llvm::objcopy::coff::Object::removeSections(), removeUndefDbgAssignsFromEntryBlock(), replaceTargetsFromPHINode(), llvm::InstructionSelect::runOnMachineFunction(), llvm::SetState< BaseTy >::setContains(), llvm::OutlinableRegion::splitCandidate(), and llvm::FastISel::tryToFoldLoad().
count()
template<typename ValueT , typename MapTy , typename ValueInfoT > size_type llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count (const_arg_type_t< ValueT > V) const inline
Return 1 if the specified key is in the set, 0 otherwise.
Definition at line 97 of file DenseSet.h.
Referenced by llvm::LiveVariables::addNewBlock(), llvm::MCPseudoProbeDecoder::buildAddress2ProbeMap(), canProveExitOnFirstIteration(), checkHoistValue(), TransferTracker::checkInstForNewValues(), checkVariableImport(), collectBlocksReachableByDirty(), computeFunctionSummary(), llvm::MustBeExecutedIterator::count(), llvm::ModuleSummaryIndex::exportToDot(), llvm::orc::JITDylib::getDFSLinkOrder(), getInstrBB(), getPostIncrementOperand(), handleArgs(), hasDirtyPred(), hasDuplicates(), hoistValue(), llvm::SCCPInstVisitor::isEdgeFeasible(), llvm::SIInstrInfo::isOperandLegal(), llvm::SIInstrInfo::legalizeOperandsVOP3(), llvm::jitlink::LinkGraph::makeDefined(), llvm::jitlink::LinkGraph::makeExternal(), processLoadCommands(), llvm::ModuleSummaryIndex::propagateAttributes(), llvm::jitlink::prune(), DeadCodeElimination::SetQueue< T >::push_back(), llvm::BitTracker::reached(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncProfiles(), relocationViaAlloca(), llvm::jitlink::LinkGraph::removeAbsoluteSymbol(), llvm::ShadowResolver::resolve(), llvm::Attributor::shouldInitialize(), sortLocalVars(), llvm::thinLTOFinalizeInModule(), thinLTOResolvePrevailingGUID(), llvm::updateVCallVisibilityInIndex(), llvm::updateVCallVisibilityInModule(), and VisitGlobalVariableForEmission().
empty()
template<typename ValueT , typename MapTy , typename ValueInfoT > bool llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty () const inline
Definition at line 80 of file DenseSet.h.
Referenced by llvm::lto::Config::addSaveTemps(), llvm::MCPseudoProbeDecoder::buildAddress2ProbeMap(), CheckLargerCands(), checkNumberingAndReplaceCommutative(), TransferTracker::clobberMloc(), llvm::computeDeadSymbolsAndUpdateIndirectCalls(), llvm::computeEHOnlyBlocks(), llvm::objcopy::NameMatcher::empty(), llvm::SetState< BaseTy >::SetContents::empty(), llvm::ThinLTOCodeGenerator::internalize(), llvm::orc::BlockFreqQuery::operator()(), llvm::PHINode::removeIncomingValueIf(), llvm::objcopy::coff::Object::removeSections(), shouldSplit(), llvm::orc::SymbolsCouldNotBeRemoved::SymbolsCouldNotBeRemoved(), llvm::orc::SymbolsNotFound::SymbolsNotFound(), llvm::thinLTOFinalizeInModule(), and llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::~SimpleExecutorDylibManager().
end() [1/2]
template<typename ValueT , typename MapTy , typename ValueInfoT > iterator llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end () inline
Definition at line 174 of file DenseSet.h.
Referenced by llvm::jitlink::LinkGraph::absolute_symbols(), analyzeLoopUnrollCost(), checkHoistValue(), llvm::ComputeCrossModuleImport(), llvm::MDBuilder::createFunctionEntryCount(), llvm::dwarf_linker::classic::DeclContextTree::getChildDeclContext(), handleArgs(), and llvm::jitlink::Section::symbols().
end() [2/2]
template<typename ValueT , typename MapTy , typename ValueInfoT > const_iterator llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::end () const inline
Definition at line 177 of file DenseSet.h.
erase() [1/3]
template<typename ValueT , typename MapTy , typename ValueInfoT > bool llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase (const ValueT & V) inline
Definition at line 101 of file DenseSet.h.
Referenced by analyzeExitPHIsForOutputUses(), llvm::ComputeCrossModuleImport(), llvm::computeEHOnlyBlocks(), llvm::jitlink::LinkGraph::makeDefined(), llvm::jitlink::LinkGraph::makeExternal(), DeadCodeElimination::SetQueue< T >::pop_front(), processLoadCommands(), TransferTracker::redefVar(), reduceDbgValsBackwardScan(), llvm::jitlink::LinkGraph::removeAbsoluteSymbol(), and VisitGlobalVariableForEmission().
erase() [2/3]
template<typename ValueT , typename MapTy , typename ValueInfoT > void llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase (ConstIterator CI) inline
Definition at line 204 of file DenseSet.h.
erase() [3/3]
template<typename ValueT , typename MapTy , typename ValueInfoT > void llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::erase (Iterator I) inline
Definition at line 203 of file DenseSet.h.
References I.
find() [1/2]
template<typename ValueT , typename MapTy , typename ValueInfoT > iterator llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::find (const_arg_type_t< ValueT > V) inline
Definition at line 179 of file DenseSet.h.
Referenced by analyzeLoopUnrollCost(), CheckLargerCands(), llvm::dwarf_linker::classic::DeclContextTree::getChildDeclContext(), and handleArgs().
find() [2/2]
template<typename ValueT , typename MapTy , typename ValueInfoT > const_iterator llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::find (const_arg_type_t< ValueT > V) const inline
Definition at line 180 of file DenseSet.h.
find_as() [1/2]
template<typename ValueT , typename MapTy , typename ValueInfoT > template<class LookupKeyT > iterator llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::find_as (const LookupKeyT & Val) inline
Alternative version of find() which allows a different, and possibly less expensive, key type.
The DenseMapInfo is responsible for supplying methods getHashValue(LookupKeyT) and isEqual(LookupKeyT, KeyT) for each key type used.
Definition at line 195 of file DenseSet.h.
find_as() [2/2]
template<typename ValueT , typename MapTy , typename ValueInfoT > template<class LookupKeyT > const_iterator llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::find_as (const LookupKeyT & Val) const inline
Definition at line 199 of file DenseSet.h.
getMemorySize()
template<typename ValueT , typename MapTy , typename ValueInfoT > size_t llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::getMemorySize () const inline
Definition at line 82 of file DenseSet.h.
insert() [1/3]
template<typename ValueT , typename MapTy , typename ValueInfoT > std::pair< iterator, bool > llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert (const ValueT & V) inline
Definition at line 206 of file DenseSet.h.
References llvm::Empty.
Referenced by llvm::jitlink::LinkGraph::addAbsoluteSymbol(), addDefsUsesToList(), llvm::orc::addFunctionPointerRelocationsToCurrentSymbol(), llvm::objcopy::NameMatcher::addMatcher(), llvm::LiveVariables::addNewBlock(), llvm::ShadowResolver::addShadow(), TransferTracker::addUseBeforeDef(), llvm::slpvectorizer::BoUpSLP::analyzedReductionVals(), analyzeExitPHIsForOutputUses(), analyzeLoopUnrollCost(), llvm::DwarfDebug::beginModule(), llvm::buildModuleSummaryIndex(), buildOverlapMapAndRecordDeclares(), canProveExitOnFirstIteration(), checkClobberSanity(), checkHoistValue(), CheckLargerCands(), checkNumberingAndReplace(), checkNumberingAndReplaceCommutative(), checkVariableImport(), TransferTracker::clobberMloc(), collectRegionsConstants(), llvm::IRSimilarity::IRSimilarityCandidate::compareCommutativeOperandMapping(), computeAliasSummary(), llvm::ComputeCrossModuleImport(), llvm::computeEHOnlyBlocks(), computeFunctionSummary(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), computeVariableSummary(), llvm::SelectionDAG::copyExtraInfo(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalRelationFrom(), llvm::deleteDeadLoop(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::DenseSetImpl(), DiscoverDependentGlobals(), DPValuesRemoveRedundantDbgInstrsUsingBackwardScan(), DPValuesRemoveUndefDbgAssignsFromEntryBlock(), EliminateDuplicatePHINodesSetBasedImpl(), llvm::WebAssemblyAsmPrinter::emitDecls(), llvm::DwarfDebug::endFunctionImpl(), llvm::sampleprof::FunctionSamples::findAllNames(), findBaseObject(), llvm::orc::SpeculateQuery::findCalles(), findConstants(), findCostForOutputBlocks(), findExtractedOutputToOverallOutputMapping(), llvm::sampleprof::FunctionSamples::findInlinedFunctions(), findOrCreatePHIInBlock(), llvm::DWARFDebugAranges::generate(), getBaseType(), llvm::IRSimilarity::IRSimilarityCandidate::getBasicBlocks(), getBranchInsertPoint(), llvm::dwarf_linker::classic::DeclContextTree::getChildDeclContext(), getCHRConditionValuesForRegion(), llvm::orc::JITDylib::getDFSLinkOrder(), getPostIncrementOperand(), getRegsUsedByPHIs(), getSelectsInScope(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::DWARFUnit::getVariableForAddress(), llvm::getVisibleToRegularObjVtableGUIDs(), getWaitStatesSince(), handleArgs(), llvm::DIExpression::hasAllLocationOps(), hasDuplicates(), hasHazard(), hoistValue(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), insertRelocationStores(), insertRematerializationStores(), insertTrivialPHIs(), llvm::SIInstrInfo::isOperandLegal(), isSaveReachableThroughClean(), llvm::SIInstrInfo::legalizeOperandsVOP3(), LLVMOrcMaterializationResponsibilityDelegate(), llvm::PhiLoweringHelper::lowerPhis(), llvm::jitlink::LinkGraph::makeAbsolute(), markAllReachable(), llvm::orc::rt_bootstrap::SimpleExecutorDylibManager::open(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), processLoadCommands(), processSwitches(), propagateAttributesToRefs(), llvm::jitlink::prune(), DeadCodeElimination::SetQueue< T >::push_back(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncProfiles(), reduceDbgValsBackwardScan(), removeExternalCFGEdges(), llvm::PHINode::removeIncomingValueIf(), removeRedundantDbgInstrsUsingBackwardScan(), llvm::objcopy::coff::Object::removeSections(), removeUndefDbgAssignsFromEntryBlock(), llvm::ThinLTOCodeGenerator::run(), llvm::lto::LTO::run(), llvm::InstructionSelect::runOnMachineFunction(), llvm::UniqueStringSaver::save(), scanInlinedCode(), scanOneBB(), searchPredecessors(), llvm::SPIRV::ModuleAnalysisInfo::setSkipEmission(), sortLocalVars(), stripDeadDebugInfoImpl(), llvm::thinLTOFinalizeInModule(), llvm::thinLTOResolvePrevailingInIndex(), LLVMOrcLazyCallThroughManagerRef::toSymbolDependenceMap(), llvm::orc::StaticLibraryDefinitionGenerator::tryToGenerate(), undefInvalidDbgValues(), llvm::FastISel::updateValueMap(), llvm::InstrProfWriter::validateRecord(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), and VisitGlobalVariableForEmission().
insert() [2/3]
template<typename ValueT , typename MapTy , typename ValueInfoT > template<typename InputIt > void llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert (InputIt I, InputIt E) inline
Definition at line 230 of file DenseSet.h.
References E, I, and llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert().
insert() [3/3]
template<typename ValueT , typename MapTy , typename ValueInfoT > std::pair< iterator, bool > llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert (ValueT && V) inline
Definition at line 211 of file DenseSet.h.
References llvm::Empty.
insert_as() [1/2]
template<typename ValueT , typename MapTy , typename ValueInfoT > template<typename LookupKeyT > std::pair< iterator, bool > llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert_as (const ValueT & V, const LookupKeyT & LookupKey) inline
Alternative version of insert that uses a different (and possibly less expensive) key type.
Definition at line 219 of file DenseSet.h.
Referenced by llvm::StructType::get().
insert_as() [2/2]
template<typename ValueT , typename MapTy , typename ValueInfoT > template<typename LookupKeyT > std::pair< iterator, bool > llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert_as (ValueT && V, const LookupKeyT & LookupKey) inline
Definition at line 224 of file DenseSet.h.
reserve()
template<typename ValueT , typename MapTy , typename ValueInfoT > void llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::reserve (size_t Size) inline
Grow the DenseSet so that it can contain at least NumEntries items before resizing again.
Definition at line 90 of file DenseSet.h.
References Size.
Referenced by EliminateDuplicatePHINodesSetBasedImpl().
resize()
template<typename ValueT , typename MapTy , typename ValueInfoT > void llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::resize (size_t Size) inline
Grow the DenseSet so that it has at least Size buckets.
Will not shrink the Size of the set.
Definition at line 86 of file DenseSet.h.
References Size.
size()
template<typename ValueT , typename MapTy , typename ValueInfoT > size_type llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::size () const inline
Definition at line 81 of file DenseSet.h.
Referenced by checkNumberingAndReplace(), checkNumberingAndReplaceCommutative(), llvm::SampleProfileLoaderBaseImpl< FT >::computeAndPropagateWeights(), llvm::computeDeadSymbolsAndUpdateIndirectCalls(), llvm::computeLTOCacheKey(), createSwitchStatement(), findCostForOutputBlocks(), llvm::SetState< BaseTy >::SetContents::getIntersection(), llvm::SetState< BaseTy >::getIntersection(), llvm::SetState< BaseTy >::SetContents::getUnion(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::PHINode::removeIncomingValueIf(), replaceCalledFunction(), llvm::Function::setEntryCount(), llvm::orc::SymbolLookupSet::SymbolLookupSet(), and llvm::jitlink::Section::symbols_size().
swap()
template<typename ValueT , typename MapTy , typename ValueInfoT > void llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::swap (DenseSetImpl< ValueT, MapTy, ValueInfoT > & RHS) inline
Definition at line 105 of file DenseSet.h.
References RHS.
The documentation for this class was generated from the following file:
include/llvm/ADT/DenseSet.h