LLVM: llvm::orc::LoadAndLinkDynLibrary Class Reference
llvm::orc::LoadAndLinkDynLibrary Class Reference
Public Member Functions
LoadAndLinkDynLibrary (LLJIT &J)
Error operator() (JITDylib &JD, StringRef DLLName)
Detailed Description
Definition at line 1059 of file LLJIT.cpp.
Constructor & Destructor Documentation
LoadAndLinkDynLibrary()
llvm::orc::LoadAndLinkDynLibrary::LoadAndLinkDynLibrary (LLJIT & J) inline
Definition at line 1061 of file LLJIT.cpp.
Member Function Documentation
operator()()
Error llvm::orc::LoadAndLinkDynLibrary::operator() (JITDylib & JD, StringRef DLLName) inline
Definition at line 1062 of file LLJIT.cpp.
References llvm::orc::JITDylib::addToLinkOrder(), llvm::StringRef::ends_with_insensitive(), llvm::inconvertibleErrorCode(), llvm::orc::LLJIT::loadPlatformDynamicLibrary(), llvm::StringRef::str(), and llvm::Error::success().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/LLJIT.cpp