LLVM: llvm::object::BigArchiveMemberHeader Class Reference
llvm::object::BigArchiveMemberHeader Class Reference
#include "llvm/Object/Archive.h"
Public Member Functions
BigArchiveMemberHeader (Archive const *Parent, const char *RawHeaderPtr, uint64_t Size, Error *Err)
std::unique_ptr< AbstractArchiveMemberHeader > clone () const override
Expected< StringRef > getRawName () const override
Get the name without looking up long names.
Expected< uint64_t > getRawNameSize () const
Expected< StringRef > getName (uint64_t Size) const override
Get the name looking up long names.
Expected< uint64_t > getSize () const override
Expected< const char * > getNextChildLoc () const override
Get next file member location.
Expected< uint64_t > getNextOffset () const
Expected< bool > isThin () const override
Public Member Functions inherited from llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >
CommonArchiveMemberHeader (const Archive *Parent, const BigArMemHdrType *RawHeaderPtr)
StringRef getRawAccessMode () const override
StringRef getRawLastModified () const override
StringRef getRawUID () const override
StringRef getRawGID () const override
uint64_t getOffset () const override
uint64_t getSizeOf () const override
Returns the size in bytes of the format-defined member header of the concrete archive type.
Public Member Functions inherited from llvm::object::AbstractArchiveMemberHeader
virtual std::unique_ptr< AbstractArchiveMemberHeader > clone () const =0
virtual ~AbstractArchiveMemberHeader ()=default
virtual Expected< StringRef > getRawName () const =0
Get the name without looking up long names.
virtual StringRef getRawAccessMode () const =0
virtual StringRef getRawLastModified () const =0
virtual StringRef getRawUID () const =0
virtual StringRef getRawGID () const =0
virtual Expected< StringRef > getName (uint64_t Size) const =0
Get the name looking up long names.
virtual Expected< uint64_t > getSize () const =0
virtual uint64_t getOffset () const =0
virtual Expected< const char * > getNextChildLoc () const =0
Get next file member location.
virtual Expected< bool > isThin () const =0
Expected< sys::fs::perms > getAccessMode () const
Expected< sys::TimePoint< std::chrono::seconds > > getLastModified () const
Expected< unsigned > getUID () const
Expected< unsigned > getGID () const
virtual uint64_t getSizeOf () const =0
Returns the size in bytes of the format-defined member header of the concrete archive type.
Additional Inherited Members
Public Attributes inherited from llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >
BigArMemHdrType const * ArMemHdr
Public Attributes inherited from llvm::object::AbstractArchiveMemberHeader
const Archive * Parent
Protected Member Functions inherited from llvm::object::AbstractArchiveMemberHeader
AbstractArchiveMemberHeader (const Archive *Parent)
Detailed Description
Definition at line 136 of file Archive.h.
Constructor & Destructor Documentation
BigArchiveMemberHeader()
BigArchiveMemberHeader::BigArchiveMemberHeader (Archive const * Parent, const char * RawHeaderPtr, uint64_t Size, Error * Err)
Definition at line 130 of file Archive.cpp.
References createMemberHeaderParseError(), llvm::StringRef::end(), llvm::object::Binary::getData(), llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >::getSizeOf(), malformedError(), llvm::object::AbstractArchiveMemberHeader::Parent, and Size.
Member Function Documentation
clone()
std::unique_ptr< AbstractArchiveMemberHeader > llvm::object::BigArchiveMemberHeader::clone () const inline override virtual
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 142 of file Archive.h.
getName()
Expected< StringRef > BigArchiveMemberHeader::getName (uint64_t Size) const override virtual
Get the name looking up long names.
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 353 of file Archive.cpp.
References getRawName().
getNextChildLoc()
Expected< const char * > BigArchiveMemberHeader::getNextChildLoc () const override virtual
Get next file member location.
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 451 of file Archive.cpp.
References llvm::StringRef::data(), llvm::Expected< T >::get(), llvm::object::Binary::getData(), getNextOffset(), llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >::getOffset(), llvm::object::AbstractArchiveMemberHeader::Parent, and llvm::Expected< T >::takeError().
getNextOffset()
Expected< uint64_t > BigArchiveMemberHeader::getNextOffset () const
Definition at line 380 of file Archive.cpp.
References llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >::ArMemHdr, getArchiveMemberDecField(), getFieldRawString(), llvm::object::BigArMemHdrType::NextOffset, and llvm::object::AbstractArchiveMemberHeader::Parent.
Referenced by getNextChildLoc().
getRawName()
Expected< StringRef > BigArchiveMemberHeader::getRawName () const override virtual
Get the name without looking up long names.
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 216 of file Archive.cpp.
References llvm::alignTo(), llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >::ArMemHdr, llvm::StringRef::data(), llvm::StringRef::ends_with(), llvm::Expected< T >::get(), getArchiveMemberDecField(), llvm::object::Binary::getData(), getFieldRawString(), malformedError(), llvm::object::BigArMemHdrType::Name, llvm::object::BigArMemHdrType::NameLen, llvm::Offset, llvm::object::AbstractArchiveMemberHeader::Parent, llvm::StringRef::size(), and llvm::Expected< T >::takeError().
Referenced by getName().
getRawNameSize()
Expected< uint64_t > BigArchiveMemberHeader::getRawNameSize () const
Definition at line 375 of file Archive.cpp.
References llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >::ArMemHdr, getArchiveMemberDecField(), getFieldRawString(), llvm::object::BigArMemHdrType::NameLen, and llvm::object::AbstractArchiveMemberHeader::Parent.
Referenced by getSize().
getSize()
Expected< uint64_t > BigArchiveMemberHeader::getSize () const override virtual
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 362 of file Archive.cpp.
References llvm::alignTo(), llvm::object::CommonArchiveMemberHeader< BigArMemHdrType >::ArMemHdr, getArchiveMemberDecField(), getFieldRawString(), getRawNameSize(), llvm::object::AbstractArchiveMemberHeader::Parent, llvm::object::BigArMemHdrType::Size, and llvm::Expected< T >::takeError().
isThin()
Expected< bool > llvm::object::BigArchiveMemberHeader::isThin () const inline override virtual
Implements llvm::object::AbstractArchiveMemberHeader.
Definition at line 153 of file Archive.h.
The documentation for this class was generated from the following files:
include/llvm/Object/Archive.h
lib/Object/Archive.cpp