LLVM: llvm::object::XCOFFCsectAuxRef Class Reference
llvm::object::XCOFFCsectAuxRef Class Reference
#include "llvm/Object/XCOFFObjectFile.h"
Public Member Functions
XCOFFCsectAuxRef (const XCOFFCsectAuxEnt32 *Entry32)
XCOFFCsectAuxRef (const XCOFFCsectAuxEnt64 *Entry64)
uint64_t getSectionOrLength () const
uint32_t getSectionOrLength32 () const
uint64_t getSectionOrLength64 () const
uint32_t getParameterHashIndex () const
uint16_t getTypeChkSectNum () const
XCOFF::StorageMappingClass getStorageMappingClass () const
uintptr_t getEntryAddress () const
uint16_t getAlignmentLog2 () const
uint8_t getSymbolType () const
bool isLabel () const
uint32_t getStabInfoIndex32 () const
uint16_t getStabSectNum32 () const
XCOFF::SymbolAuxType getAuxType64 () const
uint8_t getSymbolAlignmentAndType () const
Static Public Attributes
static constexpr uint8_t SymbolTypeMask = 0x07
static constexpr uint8_t SymbolAlignmentMask = 0xF8
static constexpr size_t SymbolAlignmentBitOffset = 3
Detailed Description
Definition at line 342 of file XCOFFObjectFile.h.
Constructor & Destructor Documentation
XCOFFCsectAuxRef() [1/2]
llvm::object::XCOFFCsectAuxRef::XCOFFCsectAuxRef (const XCOFFCsectAuxEnt32 * Entry32) inline
Definition at line 348 of file XCOFFObjectFile.h.
XCOFFCsectAuxRef() [2/2]
llvm::object::XCOFFCsectAuxRef::XCOFFCsectAuxRef (const XCOFFCsectAuxEnt64 * Entry64) inline
Definition at line 349 of file XCOFFObjectFile.h.
Member Function Documentation
getAlignmentLog2()
uint16_t llvm::object::XCOFFCsectAuxRef::getAlignmentLog2 () const inline
Definition at line 388 of file XCOFFObjectFile.h.
getAuxType64()
XCOFF::SymbolAuxType llvm::object::XCOFFCsectAuxRef::getAuxType64 () const inline
Definition at line 409 of file XCOFFObjectFile.h.
References assert().
getEntryAddress()
uintptr_t llvm::object::XCOFFCsectAuxRef::getEntryAddress () const inline
Definition at line 383 of file XCOFFObjectFile.h.
Referenced by llvm::object::XCOFFSymbolRef::isFunction().
getParameterHashIndex()
uint32_t llvm::object::XCOFFCsectAuxRef::getParameterHashIndex () const inline
Definition at line 373 of file XCOFFObjectFile.h.
References GETVALUE.
getSectionOrLength()
uint64_t llvm::object::XCOFFCsectAuxRef::getSectionOrLength () const inline
Definition at line 356 of file XCOFFObjectFile.h.
Referenced by llvm::object::XCOFFObjectFile::getCommonSymbolSizeImpl(), and llvm::object::XCOFFObjectFile::getSymbolSize().
getSectionOrLength32()
uint32_t llvm::object::XCOFFCsectAuxRef::getSectionOrLength32 () const inline
Definition at line 360 of file XCOFFObjectFile.h.
References assert().
getSectionOrLength64()
uint64_t llvm::object::XCOFFCsectAuxRef::getSectionOrLength64 () const inline
Definition at line 365 of file XCOFFObjectFile.h.
References assert().
getStabInfoIndex32()
uint32_t llvm::object::XCOFFCsectAuxRef::getStabInfoIndex32 () const inline
Definition at line 399 of file XCOFFObjectFile.h.
References assert().
getStabSectNum32()
uint16_t llvm::object::XCOFFCsectAuxRef::getStabSectNum32 () const inline
Definition at line 404 of file XCOFFObjectFile.h.
References assert().
getStorageMappingClass()
XCOFF::StorageMappingClass llvm::object::XCOFFCsectAuxRef::getStorageMappingClass () const inline
Definition at line 379 of file XCOFFObjectFile.h.
References GETVALUE.
Referenced by llvm::object::XCOFFSymbolRef::isFunction().
getSymbolAlignmentAndType()
uint8_t llvm::object::XCOFFCsectAuxRef::getSymbolAlignmentAndType () const inline
Definition at line 414 of file XCOFFObjectFile.h.
References GETVALUE.
getSymbolType()
uint8_t llvm::object::XCOFFCsectAuxRef::getSymbolType () const inline
Definition at line 393 of file XCOFFObjectFile.h.
Referenced by llvm::object::XCOFFObjectFile::getCommonSymbolSizeImpl(), llvm::object::XCOFFObjectFile::getSymbolSize(), and llvm::object::XCOFFSymbolRef::isFunction().
getTypeChkSectNum()
uint16_t llvm::object::XCOFFCsectAuxRef::getTypeChkSectNum () const inline
Definition at line 377 of file XCOFFObjectFile.h.
References GETVALUE.
isLabel()
bool llvm::object::XCOFFCsectAuxRef::isLabel () const inline
Definition at line 397 of file XCOFFObjectFile.h.
References getSymbolType(), and llvm::XCOFF::XTY_LD.
Member Data Documentation
SymbolAlignmentBitOffset
constexpr size_t llvm::object::XCOFFCsectAuxRef::SymbolAlignmentBitOffset = 3 static constexpr
Definition at line 346 of file XCOFFObjectFile.h.
SymbolAlignmentMask
constexpr uint8_t llvm::object::XCOFFCsectAuxRef::SymbolAlignmentMask = 0xF8 static constexpr
Definition at line 345 of file XCOFFObjectFile.h.
SymbolTypeMask
constexpr uint8_t llvm::object::XCOFFCsectAuxRef::SymbolTypeMask = 0x07 static constexpr
Definition at line 344 of file XCOFFObjectFile.h.
The documentation for this class was generated from the following file:
include/llvm/Object/XCOFFObjectFile.h