LLVM: llvm::orc::shared::SPSSerializationTraits< SPSExecutorSymbolDef, ExecutorSymbolDef > Class Reference
llvm::orc::shared::SPSSerializationTraits< SPSExecutorSymbolDef, ExecutorSymbolDef > Class Reference
SPS serializatior for ExecutorSymbolDef.
#include "llvm/ExecutionEngine/Orc/Shared/ExecutorSymbolDef.h"
Static Public Member Functions
static size_t size (const ExecutorSymbolDef &ESD)
static bool serialize (SPSOutputBuffer &BOB, const ExecutorSymbolDef &ESD)
static bool deserialize (SPSInputBuffer &BIB, ExecutorSymbolDef &ESD)
Detailed Description
SPS serializatior for ExecutorSymbolDef.
Definition at line 86 of file ExecutorSymbolDef.h.
Member Function Documentation
deserialize()
static bool llvm::orc::shared::SPSSerializationTraits< SPSExecutorSymbolDef, ExecutorSymbolDef >::deserialize (SPSInputBuffer & BIB, ExecutorSymbolDef & ESD) inline static
Definition at line 98 of file ExecutorSymbolDef.h.
References Addr.
serialize()
static bool llvm::orc::shared::SPSSerializationTraits< SPSExecutorSymbolDef, ExecutorSymbolDef >::serialize (SPSOutputBuffer & BOB, const ExecutorSymbolDef & ESD) inline static
Definition at line 94 of file ExecutorSymbolDef.h.
References llvm::orc::ExecutorSymbolDef::getAddress(), and llvm::orc::ExecutorSymbolDef::getFlags().
size()
static size_t llvm::orc::shared::SPSSerializationTraits< SPSExecutorSymbolDef, ExecutorSymbolDef >::size (const ExecutorSymbolDef & ESD) inline static
Definition at line 90 of file ExecutorSymbolDef.h.
References llvm::orc::ExecutorSymbolDef::getAddress(), and llvm::orc::ExecutorSymbolDef::getFlags().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/ExecutorSymbolDef.h