LLVM: llvm::mca::RISCVSEWInstrument Class Reference
llvm::mca::RISCVSEWInstrument Class Reference
#include "Target/RISCV/MCA/RISCVCustomBehaviour.h"
Public Member Functions
RISCVSEWInstrument (StringRef Data)
~RISCVSEWInstrument ()=default
uint8_t getSEW () const
Public Member Functions inherited from llvm::mca::Instrument
Instrument (StringRef Desc, StringRef Data)
Instrument ()
virtual ~Instrument ()=default
StringRef getDesc () const
StringRef getData () const
Static Public Member Functions
static bool isDataValid (StringRef Data)
Static Public Attributes
static const StringRef DESC_NAME = "RISCV-SEW"
Detailed Description
Definition at line 41 of file RISCVCustomBehaviour.h.
Constructor & Destructor Documentation
RISCVSEWInstrument()
llvm::mca::RISCVSEWInstrument::RISCVSEWInstrument (StringRef Data) inline explicit
Definition at line 46 of file RISCVCustomBehaviour.h.
~RISCVSEWInstrument()
llvm::mca::RISCVSEWInstrument::~RISCVSEWInstrument () default
Member Function Documentation
getSEW()
uint8_t llvm::mca::RISCVSEWInstrument::getSEW () const
Definition at line 80 of file RISCVCustomBehaviour.cpp.
References assert(), llvm::StringSwitch< T, R >::Case(), llvm::mca::Instrument::getData(), and isDataValid().
isDataValid()
bool llvm::mca::RISCVSEWInstrument::isDataValid (llvm::StringRef Data) static
Definition at line 73 of file RISCVCustomBehaviour.cpp.
References llvm::StringSwitch< T, R >::Cases(), and llvm::StringSwitch< T, R >::Default().
Referenced by llvm::mca::RISCVInstrumentManager::createInstrument(), and getSEW().
Member Data Documentation
DESC_NAME
const llvm::StringRef llvm::mca::RISCVSEWInstrument::DESC_NAME = "RISCV-SEW" static
Definition at line 43 of file RISCVCustomBehaviour.h.
Referenced by llvm::mca::RISCVInstrumentManager::createInstrument(), llvm::mca::RISCVInstrumentManager::createInstruments(), llvm::mca::RISCVInstrumentManager::getSchedClassID(), and llvm::mca::RISCVInstrumentManager::supportsInstrumentType().
The documentation for this class was generated from the following files:
lib/Target/RISCV/MCA/RISCVCustomBehaviour.h
lib/Target/RISCV/MCA/RISCVCustomBehaviour.cpp