LLVM: llvm::DefInit Class Reference
llvm::DefInit Class Reference
AL - Represent a reference to a 'def' in the description.
#include "llvm/TableGen/Record.h"
Public Member Functions
DefInit (const DefInit &)=delete
DefInit & operator= (const DefInit &)=delete
Init * convertInitializerTo (RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
Record * getDef () const
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
bool isConcrete () const override
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
std::string getAsString () const override
Convert this value to a literal form.
Init * getBit (unsigned Bit) const override
Get the Init value of the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Get the type of the Init as a RecTy.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init * getCastTo (RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This function is used to implement the bit range selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
Is this a complete value with no unset (uninitialized) subvalues?
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print this value.
virtual std::string getAsString () const =0
Convert this value to a literal form.
virtual std::string getAsUnquotedString () const
Convert this value to a literal form, without adding quotes around a string.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
virtual Init * getCastTo (RecTy *Ty) const =0
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
virtual Init * convertInitializerTo (RecTy *Ty) const =0
Convert to a value whose type is Ty, or return null if this is not possible.
virtual Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This function is used to implement the bit range selection operator.
virtual RecTy * getFieldType (StringInit *FieldName) const
This function is used to implement the FieldInit class.
virtual Init * resolveReferences (Resolver &R) const
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
virtual Init * getBit (unsigned Bit) const =0
Get the Init value of the specified bit.
Static Public Member Functions
static bool classof (const Init *I)
static DefInit * get (Record *)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Friends
class Record
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_DagInit , IK_DefInit , IK_FieldInit , IK_IntInit ,
IK_ListInit , IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit ,
IK_UnOpInit , IK_LastOpInit , IK_CondOpInit , IK_FoldOpInit ,
IK_IsAOpInit , IK_ExistsOpInit , IK_AnonymousNameInit , IK_StringInit ,
IK_VarInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit , IK_ArgumentInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
AL - Represent a reference to a 'def' in the description.
Definition at line 1311 of file Record.h.
Constructor & Destructor Documentation
DefInit()
llvm::DefInit::DefInit (const DefInit &) delete
Member Function Documentation
classof()
static bool llvm::DefInit::classof (const Init * I) inline static
Definition at line 1322 of file Record.h.
References I, and llvm::Init::IK_DefInit.
convertInitializerTo()
Init * DefInit::convertInitializerTo (RecTy * Ty) const override virtual
Convert to a value whose type is Ty, or return null if this is not possible.
This can happen if the value's type is convertible to Ty, but there are unresolved references.
Reimplemented from llvm::TypedInit.
Definition at line 2214 of file Record.cpp.
References llvm::TypedInit::getType().
get()
DefInit * DefInit::get (Record * R) static
Definition at line 2210 of file Record.cpp.
Referenced by llvm::TernOpInit::Fold(), llvm::UnOpInit::Fold(), and llvm::ExistsOpInit::Fold().
getAsString()
std::string DefInit::getAsString () const override virtual
Convert this value to a literal form.
Implements llvm::Init.
Definition at line 2227 of file Record.cpp.
References llvm::Record::getName().
Referenced by llvm::TernOpInit::Fold().
getBit()
Init * llvm::DefInit::getBit (unsigned Bit) const inline override virtual
Get the Init value of the specified bit.
Implements llvm::Init.
Definition at line 1339 of file Record.h.
References llvm_unreachable.
getDef()
Record * llvm::DefInit::getDef () const inline
Definition at line 1330 of file Record.h.
Referenced by llvm::BinOpInit::Fold(), llvm::TernOpInit::Fold(), and llvm::ListInit::getElementAsRecord().
getFieldType()
RecTy * DefInit::getFieldType (StringInit * FieldName) const override virtual
This method is used to implement the FieldInit class.
Implementors of this method should return the type of the named field if they are of type record.
Reimplemented from llvm::TypedInit.
Definition at line 2221 of file Record.cpp.
References llvm::Record::getValue().
isConcrete()
bool llvm::DefInit::isConcrete () const inline override virtual
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
Reimplemented from llvm::Init.
Definition at line 1336 of file Record.h.
operator=()
DefInit & llvm::DefInit::operator= (const DefInit &) delete
Friends And Related Function Documentation
Record
friend class Record friend
Definition at line 1312 of file Record.h.
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp