LLVM: llvm::logicalview::LVSymbolVisitorDelegate Class Reference
llvm::logicalview::LVSymbolVisitorDelegate Class Reference final
#include "llvm/DebugInfo/LogicalView/Readers/LVCodeViewVisitor.h"
Public Member Functions
LVSymbolVisitorDelegate (LVCodeViewReader *Reader, const llvm::object::SectionRef &Section, const llvm::object::COFFObjectFile *Obj, StringRef SectionContents)
uint32_t getRecordOffset (BinaryStreamReader Reader) override
void printRelocatedField (StringRef Label, uint32_t RelocOffset, uint32_t Offset, StringRef *RelocSym=nullptr)
void getLinkageName (uint32_t RelocOffset, uint32_t Offset, StringRef *RelocSym=nullptr)
StringRef getFileNameForFileOffset (uint32_t FileOffset) override
DebugStringTableSubsectionRef getStringTable () override
Public Member Functions inherited from llvm::codeview::SymbolVisitorDelegate
virtual ~SymbolVisitorDelegate ()=default
virtual uint32_t getRecordOffset (BinaryStreamReader Reader)=0
virtual StringRef getFileNameForFileOffset (uint32_t FileOffset)=0
virtual DebugStringTableSubsectionRef getStringTable ()=0
Detailed Description
Definition at line 85 of file LVCodeViewVisitor.h.
Constructor & Destructor Documentation
LVSymbolVisitorDelegate()
llvm::logicalview::LVSymbolVisitorDelegate::LVSymbolVisitorDelegate (LVCodeViewReader * Reader, const llvm::object::SectionRef & Section, const llvm::object::COFFObjectFile * Obj, StringRef SectionContents) inline
Definition at line 91 of file LVCodeViewVisitor.h.
References llvm::object::COFFObjectFile::getCOFFSection().
Member Function Documentation
getFileNameForFileOffset()
StringRef LVSymbolVisitorDelegate::getFileNameForFileOffset (uint32_t FileOffset) override virtual
Implements llvm::codeview::SymbolVisitorDelegate.
Definition at line 695 of file LVCodeViewVisitor.cpp.
References llvm::consumeError(), and llvm::logicalview::Name.
getLinkageName()
void LVSymbolVisitorDelegate::getLinkageName (uint32_t RelocOffset, uint32_t Offset, StringRef * RelocSym = nullptr)
Definition at line 688 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVCodeViewReader::getLinkageName(), and llvm::logicalview::Offset.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
getRecordOffset()
uint32_t llvm::logicalview::LVSymbolVisitorDelegate::getRecordOffset (BinaryStreamReader Reader) inline override virtual
Implements llvm::codeview::SymbolVisitorDelegate.
Definition at line 99 of file LVCodeViewVisitor.h.
References llvm::StringRef::bytes_begin(), llvm::consumeError(), llvm::Data, and llvm::BinaryStreamReader::readLongestContiguousChunk().
getStringTable()
DebugStringTableSubsectionRef LVSymbolVisitorDelegate::getStringTable () override virtual
Implements llvm::codeview::SymbolVisitorDelegate.
Definition at line 704 of file LVCodeViewVisitor.cpp.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
printRelocatedField()
void LVSymbolVisitorDelegate::printRelocatedField (StringRef Label, uint32_t RelocOffset, uint32_t Offset, StringRef * RelocSym = nullptr)
Definition at line 680 of file LVCodeViewVisitor.cpp.
References llvm::pdb::Label, and llvm::logicalview::Offset.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Readers/LVCodeViewVisitor.h
lib/DebugInfo/LogicalView/Readers/LVCodeViewVisitor.cpp