LLVM: llvm::DomConditionCache Class Reference
llvm::DomConditionCache Class Reference
#include "llvm/Analysis/DomConditionCache.h"
Public Member Functions
void registerBranch (BranchInst *BI)
Add a branch condition to the cache.
void removeValue (Value *V)
Remove a value from the cache, e.g. because it will be erased.
ArrayRef< BranchInst * > conditionsFor (const Value *V) const
Access the list of branches which affect this value.
Detailed Description
Definition at line 31 of file DomConditionCache.h.
Member Function Documentation
conditionsFor()
ArrayRef< BranchInst * > llvm::DomConditionCache::conditionsFor (const Value * V) const inline
Access the list of branches which affect this value.
Definition at line 45 of file DomConditionCache.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as().
Referenced by llvm::computeKnownBitsFromContext(), and llvm::InstCombinerImpl::foldICmpWithDominatingICmp().
registerBranch()
void DomConditionCache::registerBranch (BranchInst * BI)
Add a branch condition to the cache.
Definition at line 58 of file DomConditionCache.cpp.
References assert(), findAffectedValues(), llvm::BranchInst::getCondition(), llvm::is_contained(), and llvm::BranchInst::isConditional().
Referenced by llvm::InstCombinerImpl::visitBranchInst().
removeValue()
void llvm::DomConditionCache::removeValue (Value * V) inline
Remove a value from the cache, e.g. because it will be erased.
Definition at line 42 of file DomConditionCache.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase().
The documentation for this class was generated from the following files:
include/llvm/Analysis/DomConditionCache.h
lib/Analysis/DomConditionCache.cpp