LLVM: llvm::NVPTXMachineFunctionInfo Class Reference
llvm::NVPTXMachineFunctionInfo Class Reference
#include "Target/NVPTX/NVPTXMachineFunctionInfo.h"
Public Member Functions
NVPTXMachineFunctionInfo (const Function &F, const TargetSubtargetInfo *STI)
MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const override
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
unsigned getImageHandleSymbolIndex (const char *Symbol)
Returns the index for the symbol Symbol.
const char * getImageHandleSymbol (unsigned Idx) const
Returns the symbol name at the given index.
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
virtual MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy , typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Detailed Description
Definition at line 20 of file NVPTXMachineFunctionInfo.h.
Constructor & Destructor Documentation
NVPTXMachineFunctionInfo()
llvm::NVPTXMachineFunctionInfo::NVPTXMachineFunctionInfo (const Function & F, const TargetSubtargetInfo * STI) inline
Definition at line 27 of file NVPTXMachineFunctionInfo.h.
Member Function Documentation
clone()
MachineFunctionInfo * llvm::NVPTXMachineFunctionInfo::clone (BumpPtrAllocator & Allocator, MachineFunction & DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) const inline override virtual
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
This requires remapping MachineBasicBlock references from the original parent to values in the new function. Targets may assume that virtual register and frame index values are preserved in the new function.
Reimplemented from llvm::MachineFunctionInfo.
Definition at line 30 of file NVPTXMachineFunctionInfo.h.
References llvm::MachineFunction::cloneInfo().
getImageHandleSymbol()
const char * llvm::NVPTXMachineFunctionInfo::getImageHandleSymbol (unsigned Idx) const inline
Returns the symbol name at the given index.
Definition at line 50 of file NVPTXMachineFunctionInfo.h.
References assert(), Idx, and llvm::SmallVectorBase< Size_T >::size().
getImageHandleSymbolIndex()
unsigned llvm::NVPTXMachineFunctionInfo::getImageHandleSymbolIndex (const char * Symbol) inline
Returns the index for the symbol Symbol.
If the symbol was previously, added, the same index is returned. Otherwise, the symbol is added and the new index is returned.
Definition at line 39 of file NVPTXMachineFunctionInfo.h.
References llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase< Size_T >::size().
The documentation for this class was generated from the following file:
lib/Target/NVPTX/NVPTXMachineFunctionInfo.h