LLVM: llvm::ConstantRange Class Reference
llvm::ConstantRange Class Reference
This class represents a range of values.
#include "llvm/IR/ConstantRange.h"
Public Types
enum PreferredRangeType { Smallest , Unsigned , Signed }
If represented precisely, the result of some range operations may consist of multiple disjoint ranges.
enum class OverflowResult { AlwaysOverflowsLow , AlwaysOverflowsHigh , MayOverflow , NeverOverflows }
Represents whether an operation on the given constant range is known to always or never overflow.
Public Member Functions
ConstantRange (uint32_t BitWidth, bool isFullSet)
Initialize a full or empty set for the specified bit width.
ConstantRange (APInt Value)
Initialize a range to hold the single specified value.
ConstantRange (APInt Lower, APInt Upper)
Initialize a range of values explicitly.
bool icmp (CmpInst::Predicate Pred, const ConstantRange &Other) const
Does the predicate Pred hold between ranges this and Other? NOTE: false does not mean that inverse predicate holds!
bool getEquivalentICmp (CmpInst::Predicate &Pred, APInt &RHS) const
Set up Pred and RHS such that ConstantRange::makeExactICmpRegion(Pred, RHS) == *this.
void getEquivalentICmp (CmpInst::Predicate &Pred, APInt &RHS, APInt &Offset) const
Set up Pred, RHS and Offset such that (V + Offset) Pred RHS is true iff V is in the range.
const APInt & getLower () const
Return the lower value for this range.
const APInt & getUpper () const
Return the upper value for this range.
uint32_t getBitWidth () const
Get the bit width of this ConstantRange.
bool isFullSet () const
Return true if this set contains all of the elements possible for this data-type.
bool isEmptySet () const
Return true if this set contains no members.
bool isWrappedSet () const
Return true if this set wraps around the unsigned domain.
bool isUpperWrapped () const
Return true if the exclusive upper bound wraps around the unsigned domain.
bool isSignWrappedSet () const
Return true if this set wraps around the signed domain.
bool isUpperSignWrapped () const
Return true if the (exclusive) upper bound wraps around the signed domain.
bool contains (const APInt &Val) const
Return true if the specified value is in the set.
bool contains (const ConstantRange &CR) const
Return true if the other range is a subset of this one.
const APInt * getSingleElement () const
If this set contains a single element, return it, otherwise return null.
const APInt * getSingleMissingElement () const
If this set contains all but a single element, return it, otherwise return null.
bool isSingleElement () const
Return true if this set contains exactly one member.
bool isSizeStrictlySmallerThan (const ConstantRange &CR) const
Compare set size of this range with the range CR.
bool isSizeLargerThan (uint64_t MaxSize) const
Compare set size of this range with Value.
bool isAllNegative () const
Return true if all values in this range are negative.
bool isAllNonNegative () const
Return true if all values in this range are non-negative.
APInt getUnsignedMax () const
Return the largest unsigned value contained in the ConstantRange.
APInt getUnsignedMin () const
Return the smallest unsigned value contained in the ConstantRange.
APInt getSignedMax () const
Return the largest signed value contained in the ConstantRange.
APInt getSignedMin () const
Return the smallest signed value contained in the ConstantRange.
bool operator== (const ConstantRange &CR) const
Return true if this range is equal to another range.
bool operator!= (const ConstantRange &CR) const
unsigned getActiveBits () const
Compute the maximal number of active bits needed to represent every value in this range.
unsigned getMinSignedBits () const
Compute the maximal number of bits needed to represent every value in this signed range.
ConstantRange subtract (const APInt &CI) const
Subtract the specified constant from the endpoints of this constant range.
ConstantRange difference (const ConstantRange &CR) const
Subtract the specified range from this range (aka relative complement of the sets).
ConstantRange intersectWith (const ConstantRange &CR, PreferredRangeType Type=Smallest) const
Return the range that results from the intersection of this range with another range.
ConstantRange unionWith (const ConstantRange &CR, PreferredRangeType Type=Smallest) const
Return the range that results from the union of this range with another range.
std::optional< ConstantRange > exactIntersectWith (const ConstantRange &CR) const
Intersect the two ranges and return the result if it can be represented exactly, otherwise return std::nullopt.
std::optional< ConstantRange > exactUnionWith (const ConstantRange &CR) const
Union the two ranges and return the result if it can be represented exactly, otherwise return std::nullopt.
ConstantRange castOp (Instruction::CastOps CastOp, uint32_t BitWidth) const
Return a new range representing the possible values resulting from an application of the specified cast operator to this range.
ConstantRange zeroExtend (uint32_t BitWidth) const
Return a new range in the specified integer type, which must be strictly larger than the current type.
ConstantRange signExtend (uint32_t BitWidth) const
Return a new range in the specified integer type, which must be strictly larger than the current type.
ConstantRange truncate (uint32_t BitWidth) const
Return a new range in the specified integer type, which must be strictly smaller than the current type.
ConstantRange zextOrTrunc (uint32_t BitWidth) const
Make this range have the bit width given by BitWidth.
ConstantRange sextOrTrunc (uint32_t BitWidth) const
Make this range have the bit width given by BitWidth.
ConstantRange binaryOp (Instruction::BinaryOps BinOp, const ConstantRange &Other) const
Return a new range representing the possible values resulting from an application of the specified binary operator to an left hand side of this range and a right hand side of Other.
ConstantRange overflowingBinaryOp (Instruction::BinaryOps BinOp, const ConstantRange &Other, unsigned NoWrapKind) const
Return a new range representing the possible values resulting from an application of the specified overflowing binary operator to a left hand side of this range and a right hand side of Other given the provided knowledge about lack of wrapping NoWrapKind.
ConstantRange add (const ConstantRange &Other) const
Return a new range representing the possible values resulting from an addition of a value in this range and a value in Other.
ConstantRange addWithNoWrap (const ConstantRange &Other, unsigned NoWrapKind, PreferredRangeType RangeType=Smallest) const
Return a new range representing the possible values resulting from an addition with wrap type NoWrapKind of a value in this range and a value in Other.
ConstantRange sub (const ConstantRange &Other) const
Return a new range representing the possible values resulting from a subtraction of a value in this range and a value in Other.
ConstantRange subWithNoWrap (const ConstantRange &Other, unsigned NoWrapKind, PreferredRangeType RangeType=Smallest) const
Return a new range representing the possible values resulting from an subtraction with wrap type NoWrapKind of a value in this range and a value in Other.
ConstantRange multiply (const ConstantRange &Other) const
Return a new range representing the possible values resulting from a multiplication of a value in this range and a value in Other, treating both this and Other as unsigned ranges.
ConstantRange smul_fast (const ConstantRange &Other) const
Return range of possible values for a signed multiplication of this and Other.
ConstantRange smax (const ConstantRange &Other) const
Return a new range representing the possible values resulting from a signed maximum of a value in this range and a value in Other.
ConstantRange umax (const ConstantRange &Other) const
Return a new range representing the possible values resulting from an unsigned maximum of a value in this range and a value in Other.
ConstantRange smin (const ConstantRange &Other) const
Return a new range representing the possible values resulting from a signed minimum of a value in this range and a value in Other.
ConstantRange umin (const ConstantRange &Other) const
Return a new range representing the possible values resulting from an unsigned minimum of a value in this range and a value in Other.
ConstantRange udiv (const ConstantRange &Other) const
Return a new range representing the possible values resulting from an unsigned division of a value in this range and a value in Other.
ConstantRange sdiv (const ConstantRange &Other) const
Return a new range representing the possible values resulting from a signed division of a value in this range and a value in Other.
ConstantRange urem (const ConstantRange &Other) const
Return a new range representing the possible values resulting from an unsigned remainder operation of a value in this range and a value in Other.
ConstantRange srem (const ConstantRange &Other) const
Return a new range representing the possible values resulting from a signed remainder operation of a value in this range and a value in Other.
ConstantRange binaryNot () const
Return a new range representing the possible values resulting from a binary-xor of a value in this range by an all-one value, aka bitwise complement operation.
ConstantRange binaryAnd (const ConstantRange &Other) const
Return a new range representing the possible values resulting from a binary-and of a value in this range by a value in Other.
ConstantRange binaryOr (const ConstantRange &Other) const
Return a new range representing the possible values resulting from a binary-or of a value in this range by a value in Other.
ConstantRange binaryXor (const ConstantRange &Other) const
Return a new range representing the possible values resulting from a binary-xor of a value in this range by a value in Other.
ConstantRange shl (const ConstantRange &Other) const
Return a new range representing the possible values resulting from a left shift of a value in this range by a value in Other.
ConstantRange lshr (const ConstantRange &Other) const
Return a new range representing the possible values resulting from a logical right shift of a value in this range and a value in Other.
ConstantRange ashr (const ConstantRange &Other) const
Return a new range representing the possible values resulting from a arithmetic right shift of a value in this range and a value in Other.
ConstantRange uadd_sat (const ConstantRange &Other) const
Perform an unsigned saturating addition of two constant ranges.
ConstantRange sadd_sat (const ConstantRange &Other) const
Perform a signed saturating addition of two constant ranges.
ConstantRange usub_sat (const ConstantRange &Other) const
Perform an unsigned saturating subtraction of two constant ranges.
ConstantRange ssub_sat (const ConstantRange &Other) const
Perform a signed saturating subtraction of two constant ranges.
ConstantRange umul_sat (const ConstantRange &Other) const
Perform an unsigned saturating multiplication of two constant ranges.
ConstantRange smul_sat (const ConstantRange &Other) const
Perform a signed saturating multiplication of two constant ranges.
ConstantRange ushl_sat (const ConstantRange &Other) const
Perform an unsigned saturating left shift of this constant range by a value in Other.
ConstantRange sshl_sat (const ConstantRange &Other) const
Perform a signed saturating left shift of this constant range by a value in Other.
ConstantRange inverse () const
Return a new range that is the logical not of the current set.
ConstantRange abs (bool IntMinIsPoison=false) const
Calculate absolute value range.
ConstantRange ctlz (bool ZeroIsPoison=false) const
Calculate ctlz range.
ConstantRange cttz (bool ZeroIsPoison=false) const
Calculate cttz range.
ConstantRange ctpop () const
Calculate ctpop range.
OverflowResult unsignedAddMayOverflow (const ConstantRange &Other) const
Return whether unsigned add of the two ranges always/never overflows.
OverflowResult signedAddMayOverflow (const ConstantRange &Other) const
Return whether signed add of the two ranges always/never overflows.
OverflowResult unsignedSubMayOverflow (const ConstantRange &Other) const
Return whether unsigned sub of the two ranges always/never overflows.
OverflowResult signedSubMayOverflow (const ConstantRange &Other) const
Return whether signed sub of the two ranges always/never overflows.
OverflowResult unsignedMulMayOverflow (const ConstantRange &Other) const
Return whether unsigned mul of the two ranges always/never overflows.
KnownBits toKnownBits () const
Return known bits for values in this range.
void print (raw_ostream &OS) const
Print out the bounds to a stream.
void dump () const
Allow printing from a debugger easily.
Static Public Member Functions
static ConstantRange getEmpty (uint32_t BitWidth)
Create empty constant range with the given bit width.
static ConstantRange getFull (uint32_t BitWidth)
Create full constant range with the given bit width.
static ConstantRange getNonEmpty (APInt Lower, APInt Upper)
Create non-empty constant range with the given bounds.
static ConstantRange fromKnownBits (const KnownBits &Known, bool IsSigned)
Initialize a range based on a known bits constraint.
static ConstantRange makeAllowedICmpRegion (CmpInst::Predicate Pred, const ConstantRange &Other)
Produce the smallest range such that all values that may satisfy the given predicate with any value contained within Other is contained in the returned range.
static ConstantRange makeSatisfyingICmpRegion (CmpInst::Predicate Pred, const ConstantRange &Other)
Produce the largest range such that all values in the returned range satisfy the given predicate with all values contained within Other.
static ConstantRange makeExactICmpRegion (CmpInst::Predicate Pred, const APInt &Other)
Produce the exact range such that all values in the returned range satisfy the given predicate with any value contained within Other.
static bool areInsensitiveToSignednessOfICmpPredicate (const ConstantRange &CR1, const ConstantRange &CR2)
Return true iff CR1 ult CR2 is equivalent to CR1 slt CR2.
static bool areInsensitiveToSignednessOfInvertedICmpPredicate (const ConstantRange &CR1, const ConstantRange &CR2)
Return true iff CR1 ult CR2 is equivalent to CR1 sge CR2.
static CmpInst::Predicate getEquivalentPredWithFlippedSignedness (CmpInst::Predicate Pred, const ConstantRange &CR1, const ConstantRange &CR2)
If the comparison between constant ranges this and Other is insensitive to the signedness of the comparison predicate, return a predicate equivalent to Pred, with flipped signedness (i.e.
static ConstantRange makeGuaranteedNoWrapRegion (Instruction::BinaryOps BinOp, const ConstantRange &Other, unsigned NoWrapKind)
Produce the largest range containing all X such that "X BinOp Y" is guaranteed not to wrap (overflow) for all Y in Other.
static ConstantRange makeExactNoWrapRegion (Instruction::BinaryOps BinOp, const APInt &Other, unsigned NoWrapKind)
Produce the range that contains X if and only if "X BinOp Other" does not wrap.
static bool isIntrinsicSupported (Intrinsic::ID IntrinsicID)
Returns true if ConstantRange calculations are supported for intrinsic with IntrinsicID.
static ConstantRange intrinsic (Intrinsic::ID IntrinsicID, ArrayRef< ConstantRange > Ops)
Compute range of intrinsic result for the given operand ranges.
Detailed Description
This class represents a range of values.
Definition at line 47 of file ConstantRange.h.
Member Enumeration Documentation
OverflowResult
enum class llvm::ConstantRange::OverflowResult strong
Represents whether an operation on the given constant range is known to always or never overflow.
Enumerator
AlwaysOverflowsLow
Always overflows in the direction of signed/unsigned min value.
AlwaysOverflowsHigh
Always overflows in the direction of signed/unsigned max value.
MayOverflow
May or may not overflow.
NeverOverflows
Never overflows.
Definition at line 542 of file ConstantRange.h.
PreferredRangeType
enum llvm::ConstantRange::PreferredRangeType
If represented precisely, the result of some range operations may consist of multiple disjoint ranges.
As only a single range may be returned, any range covering these disjoint ranges constitutes a valid result, but some may be more useful than others depending on context. The preferred range type specifies whether a range that is non-wrapping in the unsigned or signed domain, or has the smallest size, is preferred. If a signedness is preferred but all ranges are non-wrapping or all wrapping, then the smallest set size is preferred. If there are multiple smallest sets, any one of them may be returned.
Enumerator
Smallest
Unsigned
Signed
Definition at line 319 of file ConstantRange.h.
Constructor & Destructor Documentation
ConstantRange() [1/3]
ConstantRange::ConstantRange (uint32_t BitWidth, bool isFullSet) explicit
Initialize a full or empty set for the specified bit width.
Definition at line 44 of file ConstantRange.cpp.
ConstantRange() [2/3]
ConstantRange::ConstantRange (APInt Value)
Initialize a range to hold the single specified value.
Definition at line 48 of file ConstantRange.cpp.
ConstantRange() [3/3]
ConstantRange::ConstantRange (APInt Lower, APInt Upper)
Initialize a range of values explicitly.
This will assert out if Lower==Upper and Lower != Min or Max value for its type. It will also assert out if the two APInt's are not the same bit width.
Definition at line 51 of file ConstantRange.cpp.
References assert(), llvm::APInt::getBitWidth(), llvm::APInt::isMaxValue(), and llvm::APInt::isMinValue().
Member Function Documentation
abs()
ConstantRange ConstantRange::abs (bool IntMinIsPoison = false) const
Calculate absolute value range.
If the original range contains signed min, then the resulting range will contain signed min if and only if IntMinIsPoison is false.
Definition at line 1669 of file ConstantRange.cpp.
References getBitWidth(), getNonEmpty(), getSignedMax(), getSignedMin(), llvm::APInt::getSignedMinValue(), llvm::APInt::getZero(), isEmptySet(), isSignWrappedSet(), llvm::APInt::isStrictlyPositive(), llvm::Lo, llvm::SMax, llvm::SMin, llvm::APIntOps::umax(), and llvm::APIntOps::umin().
Referenced by processSRem().
add()
ConstantRange ConstantRange::add (const ConstantRange & Other) const
Return a new range representing the possible values resulting from an addition of a value in this range and a value in Other.
Definition at line 1006 of file ConstantRange.cpp.
References getLower(), getUpper(), isEmptySet(), isFullSet(), llvm::Other, and X.
Referenced by addWithNoWrap(), binaryOp(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), foldICmpUSubSatOrUAddSatWithConstant(), and getEquivalentICmp().
addWithNoWrap()
ConstantRange ConstantRange::addWithNoWrap (const ConstantRange & Other, unsigned NoWrapKind, PreferredRangeType RangeType = Smallest) const
Return a new range representing the possible values resulting from an addition with wrap type NoWrapKind of a value in this range and a value in Other.
If the result range is disjoint, the preferred range is determined by the PreferredRangeType.
Definition at line 1025 of file ConstantRange.cpp.
References add(), isEmptySet(), isFullSet(), llvm::Other, sadd_sat(), and uadd_sat().
Referenced by overflowingBinaryOp().
areInsensitiveToSignednessOfICmpPredicate()
bool ConstantRange::areInsensitiveToSignednessOfICmpPredicate (const ConstantRange & CR1, const ConstantRange & CR2) static
Return true iff CR1 ult CR2 is equivalent to CR1 slt CR2.
Does not depend on strictness/direction of the predicate.
Definition at line 169 of file ConstantRange.cpp.
References isAllNegative(), isAllNonNegative(), and isEmptySet().
Referenced by getEquivalentPredWithFlippedSignedness().
areInsensitiveToSignednessOfInvertedICmpPredicate()
bool ConstantRange::areInsensitiveToSignednessOfInvertedICmpPredicate (const ConstantRange & CR1, const ConstantRange & CR2) static
Return true iff CR1 ult CR2 is equivalent to CR1 sge CR2.
Does not depend on strictness/direction of the predicate.
Definition at line 178 of file ConstantRange.cpp.
References isAllNegative(), isAllNonNegative(), and isEmptySet().
Referenced by getEquivalentPredWithFlippedSignedness().
ashr()
ConstantRange ConstantRange::ashr (const ConstantRange & Other) const
Return a new range representing the possible values resulting from a arithmetic right shift of a value in this range and a value in Other.
Definition at line 1525 of file ConstantRange.cpp.
References llvm::APInt::ashr(), getNonEmpty(), getSignedMax(), getSignedMin(), isEmptySet(), llvm::max(), and llvm::Other.
Referenced by binaryOp(), and makeGuaranteedNoWrapRegion().
binaryAnd()
ConstantRange ConstantRange::binaryAnd (const ConstantRange & Other) const
Return a new range representing the possible values resulting from a binary-and of a value in this range by a value in Other.
Definition at line 1431 of file ConstantRange.cpp.
References fromKnownBits(), getBitWidth(), getNonEmpty(), getUnsignedMax(), llvm::APInt::getZero(), intersectWith(), isEmptySet(), llvm::Other, toKnownBits(), and llvm::APIntOps::umin().
Referenced by binaryOp(), and canScalarizeAccess().
binaryNot()
ConstantRange ConstantRange::binaryNot () const
Return a new range representing the possible values resulting from a binary-xor of a value in this range by an all-one value, aka bitwise complement operation.
Definition at line 1427 of file ConstantRange.cpp.
References llvm::APInt::getAllOnes(), getBitWidth(), and sub().
Referenced by binaryXor().
binaryOp()
ConstantRange ConstantRange::binaryOp (Instruction::BinaryOps BinOp, const ConstantRange & Other) const
Return a new range representing the possible values resulting from an application of the specified binary operator to an left hand side of this range and a right hand side of Other.
Definition at line 878 of file ConstantRange.cpp.
References add(), ashr(), assert(), binaryAnd(), binaryOr(), binaryXor(), llvm::Instruction::isBinaryOp(), lshr(), multiply(), llvm::Other, sdiv(), shl(), srem(), sub(), udiv(), and urem().
Referenced by overflowingBinaryOp().
binaryOr()
ConstantRange ConstantRange::binaryOr (const ConstantRange & Other) const
Return a new range representing the possible values resulting from a binary-or of a value in this range by a value in Other.
Definition at line 1443 of file ConstantRange.cpp.
References fromKnownBits(), getBitWidth(), getNonEmpty(), getUnsignedMin(), llvm::APInt::getZero(), intersectWith(), isEmptySet(), llvm::Other, toKnownBits(), and llvm::APIntOps::umax().
Referenced by binaryOp().
binaryXor()
ConstantRange ConstantRange::binaryXor (const ConstantRange & Other) const
Return a new range representing the possible values resulting from a binary-xor of a value in this range by a value in Other.
Definition at line 1456 of file ConstantRange.cpp.
References binaryNot(), fromKnownBits(), getSingleElement(), isEmptySet(), isSingleElement(), llvm::Other, and toKnownBits().
Referenced by binaryOp().
castOp()
ConstantRange ConstantRange::castOp (Instruction::CastOps CastOp, uint32_t BitWidth) const
Return a new range representing the possible values resulting from an application of the specified cast operator to this range.
BitWidth is the target bitwidth of the cast. For casts which don't change bitwidth, it must be the same as the source bitwidth. For casts which do change bitwidth, the bitwidth must be consistent with the requested cast and source bitwidth.
Definition at line 721 of file ConstantRange.cpp.
References getBitWidth(), llvm::APInt::getMaxValue(), llvm::APInt::getMinValue(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm_unreachable, signExtend(), llvm::SMax, llvm::SMin, truncate(), zeroExtend(), and llvm::APInt::zext().
contains() [1/2]
bool ConstantRange::contains (const APInt & Val) const
Return true if the specified value is in the set.
Definition at line 450 of file ConstantRange.cpp.
References isFullSet(), isUpperWrapped(), and llvm::APInt::ule().
Referenced by canScalarizeAccess(), cmpExcludesZero(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::copyRangeMetadata(), ctlz(), cttz(), llvm::ScalarEvolution::getMulExpr(), getPredicateResult(), getRangeForAffineARHelper(), llvm::ScalarEvolution::getSignExtendExprImpl(), llvm::ScalarEvolution::getTripCountFromExitCount(), llvm::ScalarEvolution::getZeroExtendExprImpl(), icmp(), llvm::ValueLatticeElement::markConstantRange(), narrowSDivOrSRem(), processAShr(), processBinOp(), sdiv(), simplifyICmpWithConstant(), and willNotOverflow().
contains() [2/2]
bool ConstantRange::contains (const ConstantRange & CR) const
Return true if the other range is a subset of this one.
Definition at line 459 of file ConstantRange.cpp.
References isEmptySet(), isFullSet(), isUpperWrapped(), llvm::Other, and llvm::APInt::ule().
ctlz()
ConstantRange ConstantRange::ctlz (bool ZeroIsPoison = false) const
Calculate ctlz range.
If ZeroIsPoison is set, the range is computed ignoring a possible zero value contained in the input range.
Definition at line 1711 of file ConstantRange.cpp.
References contains(), llvm::countl_zero(), getBitWidth(), getLower(), getNonEmpty(), getUnsignedMax(), getUnsignedMin(), getUpper(), llvm::APInt::getZero(), isEmptySet(), and isZero().
ctpop()
ConstantRange ConstantRange::ctpop () const
Calculate ctpop range.
Definition at line 1843 of file ConstantRange.cpp.
References llvm::BitWidth, llvm::APInt::countl_one(), getBitWidth(), getNonEmpty(), getUnsignedPopCountRange(), llvm::APInt::getZero(), isEmptySet(), isFullSet(), isWrappedSet(), and unionWith().
cttz()
ConstantRange ConstantRange::cttz (bool ZeroIsPoison = false) const
Calculate cttz range.
If ZeroIsPoison is set, the range is computed ignoring a possible zero value contained in the input range.
Definition at line 1771 of file ConstantRange.cpp.
References llvm::BitWidth, contains(), getBitWidth(), getNonEmpty(), getUnsignedCountTrailingZerosRange(), llvm::APInt::getZero(), isEmptySet(), isFullSet(), isWrappedSet(), llvm::APInt::isZero(), and unionWith().
difference()
ConstantRange ConstantRange::difference (const ConstantRange & CR) const
Subtract the specified range from this range (aka relative complement of the sets).
Definition at line 500 of file ConstantRange.cpp.
References intersectWith(), and inverse().
Referenced by llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), and isImpliedCondCommonOperandWithConstants().
dump()
LLVM_DUMP_METHOD void ConstantRange::dump () const
Allow printing from a debugger easily.
Definition at line 1985 of file ConstantRange.cpp.
References llvm::dbgs(), and print().
exactIntersectWith()
std::optional< ConstantRange > ConstantRange::exactIntersectWith (const ConstantRange & CR) const
Intersect the two ranges and return the result if it can be represented exactly, otherwise return std::nullopt.
Definition at line 704 of file ConstantRange.cpp.
References intersectWith(), inverse(), and unionWith().
Referenced by foldICmpUSubSatOrUAddSatWithConstant().
exactUnionWith()
std::optional< ConstantRange > ConstantRange::exactUnionWith (const ConstantRange & CR) const
Union the two ranges and return the result if it can be represented exactly, otherwise return std::nullopt.
Definition at line 713 of file ConstantRange.cpp.
References intersectWith(), inverse(), and unionWith().
Referenced by foldICmpUSubSatOrUAddSatWithConstant().
fromKnownBits()
ConstantRange ConstantRange::fromKnownBits (const KnownBits & Known, bool IsSigned) static
Initialize a range based on a known bits constraint.
The IsSigned flag indicates whether the constant range should not wrap in the signed or unsigned domain.
Definition at line 59 of file ConstantRange.cpp.
References assert(), llvm::APInt::clearSignBit(), llvm::KnownBits::getBitWidth(), llvm::KnownBits::getMaxValue(), llvm::KnownBits::getMinValue(), llvm::KnownBits::hasConflict(), llvm::KnownBits::isNegative(), llvm::KnownBits::isNonNegative(), and llvm::KnownBits::isUnknown().
Referenced by binaryAnd(), binaryOr(), binaryXor(), llvm::computeConstantRangeIncludingKnownBits(), llvm::SelectionDAG::computeOverflowForSignedSub(), llvm::SelectionDAG::computeOverflowForUnsignedAdd(), llvm::computeOverflowForUnsignedMul(), llvm::SelectionDAG::computeOverflowForUnsignedMul(), and llvm::SelectionDAG::computeOverflowForUnsignedSub().
getActiveBits()
unsigned ConstantRange::getActiveBits () const
Compute the maximal number of active bits needed to represent every value in this range.
Definition at line 477 of file ConstantRange.cpp.
References llvm::APInt::getActiveBits(), getUnsignedMax(), and isEmptySet().
Referenced by narrowUDivOrURem().
getBitWidth()
uint32_t llvm::ConstantRange::getBitWidth () const inline
Get the bit width of this ConstantRange.
Definition at line 204 of file ConstantRange.h.
Referenced by abs(), binaryAnd(), binaryNot(), binaryOr(), castOp(), llvm::SelectionDAG::ComputeNumSignBits(), computeOverflowForSignedAdd(), ctlz(), ctpop(), cttz(), expandUDivOrURem(), getDomain(), getEquivalentICmp(), getRangeForAffineARHelper(), getSignedMax(), getSignedMin(), getUnsignedMax(), getUnsignedMin(), intersectWith(), isSizeLargerThan(), isSizeStrictlySmallerThan(), makeAllowedICmpRegion(), multiply(), sdiv(), sextOrTrunc(), shl(), signedAddMayOverflow(), signedSubMayOverflow(), signExtend(), srem(), subtract(), toKnownBits(), truncate(), unionWith(), urem(), zeroExtend(), and zextOrTrunc().
getEmpty()
static ConstantRange llvm::ConstantRange::getEmpty (uint32_t BitWidth) inline static
Create empty constant range with the given bit width.
Definition at line 73 of file ConstantRange.h.
References llvm::BitWidth.
getEquivalentICmp() [1/2]
bool ConstantRange::getEquivalentICmp (CmpInst::Predicate & Pred, APInt & RHS) const
Set up Pred and RHS such that ConstantRange::makeExactICmpRegion(Pred, RHS) == *this.
Return true if successful.
Definition at line 235 of file ConstantRange.cpp.
References getEquivalentICmp(), llvm::Offset, and RHS.
Referenced by getEquivalentICmp(), and llvm::ScalarEvolution::SimplifyICmpOperands().
getEquivalentICmp() [2/2]
void ConstantRange::getEquivalentICmp (CmpInst::Predicate & Pred, APInt & RHS, APInt & Offset) const
Set up Pred, RHS and Offset such that (V + Offset) Pred RHS is true iff V is in the range.
Prefers using Offset == 0 if possible.
Definition at line 205 of file ConstantRange.cpp.
References add(), assert(), getBitWidth(), getLower(), getSingleElement(), getSingleMissingElement(), getUpper(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_ULT, isEmptySet(), isFullSet(), llvm::APInt::isMinSignedValue(), makeExactICmpRegion(), llvm::Offset, and RHS.
getEquivalentPredWithFlippedSignedness()
CmpInst::Predicate ConstantRange::getEquivalentPredWithFlippedSignedness (CmpInst::Predicate Pred, const ConstantRange & CR1, const ConstantRange & CR2) static
If the comparison between constant ranges this and Other is insensitive to the signedness of the comparison predicate, return a predicate equivalent to Pred, with flipped signedness (i.e.
unsigned instead of signed or vice versa), and maybe inverted, otherwise returns CmpInst::Predicate::BAD_ICMP_PREDICATE.
Definition at line 187 of file ConstantRange.cpp.
References areInsensitiveToSignednessOfICmpPredicate(), areInsensitiveToSignednessOfInvertedICmpPredicate(), assert(), llvm::CmpInst::BAD_ICMP_PREDICATE, llvm::CmpInst::getFlippedSignednessPredicate(), llvm::CmpInst::getInversePredicate(), llvm::CmpInst::isIntPredicate(), and llvm::CmpInst::isRelational().
Referenced by processICmp().
getFull()
static ConstantRange llvm::ConstantRange::getFull (uint32_t BitWidth) inline static
Create full constant range with the given bit width.
Definition at line 78 of file ConstantRange.h.
References llvm::BitWidth.
getLower()
const APInt & llvm::ConstantRange::getLower () const inline
Return the lower value for this range.
Definition at line 198 of file ConstantRange.h.
Referenced by add(), ctlz(), getEquivalentICmp(), getRangeForAffineARHelper(), getSignedMin(), getUnsignedMin(), makeAllowedICmpRegion(), llvm::operator<<(), and sub().
getMinSignedBits()
unsigned ConstantRange::getMinSignedBits () const
Compute the maximal number of bits needed to represent every value in this signed range.
Definition at line 484 of file ConstantRange.cpp.
References getSignedMax(), getSignedMin(), and isEmptySet().
Referenced by narrowSDivOrSRem().
getNonEmpty()
static ConstantRange llvm::ConstantRange::getNonEmpty (APInt Lower, APInt Upper) inline static
Create non-empty constant range with the given bounds.
If Lower and Upper are the same, a full range is returned.
Definition at line 84 of file ConstantRange.h.
References llvm::Upper.
Referenced by abs(), ashr(), binaryAnd(), binaryOr(), llvm::computeConstantRange(), ctlz(), ctpop(), cttz(), getRangeForAffineARHelper(), getRangeForIntrinsic(), getRangeForSelectPattern(), lshr(), makeAllowedICmpRegion(), makeExactMulNSWRegion(), makeExactMulNUWRegion(), makeGuaranteedNoWrapRegion(), sadd_sat(), shl(), smax(), smin(), smul_fast(), smul_sat(), sshl_sat(), ssub_sat(), uadd_sat(), udiv(), umax(), umin(), umul_sat(), urem(), ushl_sat(), and usub_sat().
getSignedMax()
APInt ConstantRange::getSignedMax () const
Return the largest signed value contained in the ConstantRange.
Definition at line 438 of file ConstantRange.cpp.
References getBitWidth(), llvm::APInt::getSignedMaxValue(), getUpper(), isFullSet(), and isUpperSignWrapped().
Referenced by abs(), ashr(), llvm::SelectionDAG::ComputeNumSignBits(), getMinSignedBits(), llvm::ScalarEvolution::getSignedRangeMax(), makeAllowedICmpRegion(), multiply(), sadd_sat(), signedAddMayOverflow(), signedSubMayOverflow(), smax(), smin(), smul_fast(), smul_sat(), srem(), sshl_sat(), and ssub_sat().
getSignedMin()
APInt ConstantRange::getSignedMin () const
Return the smallest signed value contained in the ConstantRange.
Definition at line 444 of file ConstantRange.cpp.
References getBitWidth(), getLower(), llvm::APInt::getSignedMinValue(), isFullSet(), and isSignWrappedSet().
Referenced by abs(), ashr(), computeKnownFPClass(), llvm::SelectionDAG::ComputeNumSignBits(), getMinSignedBits(), llvm::ScalarEvolution::getSignedRangeMin(), makeAllowedICmpRegion(), multiply(), sadd_sat(), signedAddMayOverflow(), signedSubMayOverflow(), smax(), smin(), smul_fast(), smul_sat(), srem(), sshl_sat(), and ssub_sat().
getSingleElement()
const APInt * llvm::ConstantRange::getSingleElement () const inline
If this set contains a single element, return it, otherwise return null.
Definition at line 246 of file ConstantRange.h.
References llvm::Upper.
Referenced by llvm::ValueLatticeElement::asConstantInteger(), binaryXor(), computeKnownFPClass(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), llvm::AAValueConstantRange::getAssumedConstant(), llvm::LazyValueInfo::getConstant(), llvm::LazyValueInfo::getConstantOnEdge(), getEquivalentICmp(), llvm::SelectionDAG::getVScale(), multiply(), processSDiv(), simplifyIntrinsic(), srem(), and urem().
getSingleMissingElement()
const APInt * llvm::ConstantRange::getSingleMissingElement () const inline
If this set contains all but a single element, return it, otherwise return null.
Definition at line 254 of file ConstantRange.h.
References llvm::Upper.
Referenced by getEquivalentICmp().
getUnsignedMax()
APInt ConstantRange::getUnsignedMax () const
Return the largest unsigned value contained in the ConstantRange.
Definition at line 426 of file ConstantRange.cpp.
References getBitWidth(), llvm::APInt::getMaxValue(), getUpper(), isFullSet(), and isUpperWrapped().
Referenced by llvm::SCEVAAResult::alias(), binaryAnd(), ctlz(), getActiveBits(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::ScalarEvolution::getUnsignedRangeMax(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), lshr(), makeAllowedICmpRegion(), makeGuaranteedNoWrapRegion(), multiply(), mustBeFiniteCountedLoop(), processAnd(), shl(), srem(), subWithNoWrap(), toKnownBits(), uadd_sat(), udiv(), umax(), umin(), umul_sat(), unsignedAddMayOverflow(), unsignedMulMayOverflow(), unsignedSubMayOverflow(), urem(), ushl_sat(), and usub_sat().
getUnsignedMin()
APInt ConstantRange::getUnsignedMin () const
Return the smallest unsigned value contained in the ConstantRange.
Definition at line 432 of file ConstantRange.cpp.
References getBitWidth(), getLower(), llvm::APInt::getMinValue(), isFullSet(), and isWrappedSet().
Referenced by llvm::SCEVAAResult::alias(), binaryOr(), ctlz(), llvm::AArch64TargetMachine::getSubtargetImpl(), llvm::ScalarEvolution::getUnsignedRangeMin(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), lshr(), makeAllowedICmpRegion(), multiply(), shl(), srem(), toKnownBits(), uadd_sat(), udiv(), umax(), umin(), umul_sat(), unsignedAddMayOverflow(), unsignedMulMayOverflow(), unsignedSubMayOverflow(), ushl_sat(), and usub_sat().
getUpper()
const APInt & llvm::ConstantRange::getUpper () const inline
Return the upper value for this range.
Definition at line 201 of file ConstantRange.h.
References llvm::Upper.
Referenced by add(), ctlz(), getEquivalentICmp(), getRangeForAffineARHelper(), getSignedMax(), getUnsignedMax(), makeAllowedICmpRegion(), multiply(), llvm::operator<<(), sub(), and SwitchToLookupTable().
icmp()
bool ConstantRange::icmp (CmpInst::Predicate Pred, const ConstantRange & Other) const
Does the predicate Pred hold between ranges this and Other? NOTE: false does not mean that inverse predicate holds!
Definition at line 242 of file ConstantRange.cpp.
References contains(), makeSatisfyingICmpRegion(), and llvm::Other.
Referenced by expandUDivOrURem(), getDomain(), processSRem(), and llvm::InstCombinerImpl::visitCallInst().
intersectWith()
ConstantRange ConstantRange::intersectWith (const ConstantRange & CR, PreferredRangeType Type = Smallest) const
Return the range that results from the intersection of this range with another range.
If the intersection is disjoint, such that two results are possible, the preferred range is determined by the PreferredRangeType.
Definition at line 524 of file ConstantRange.cpp.
References assert(), getBitWidth(), getPreferredRange(), intersectWith(), isEmptySet(), isFullSet(), isUpperWrapped(), llvm::APInt::ule(), and llvm::APInt::ult().
Referenced by areNonOverlapSameBaseLoadAndStore(), binaryAnd(), binaryOr(), llvm::computeConstantRange(), llvm::computeConstantRangeIncludingKnownBits(), difference(), exactIntersectWith(), exactUnionWith(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), llvm::IntegerRangeState::intersectKnown(), intersectWith(), isImpliedCondCommonOperandWithConstants(), makeGuaranteedNoWrapRegion(), sdiv(), smax(), smin(), umax(), umin(), and llvm::IntegerRangeState::unionAssumed().
intrinsic()
ConstantRange ConstantRange::intrinsic (Intrinsic::ID IntrinsicID, ArrayRef< ConstantRange > Ops) static
Compute range of intrinsic result for the given operand ranges.
Definition at line 960 of file ConstantRange.cpp.
References assert(), llvm::APInt::getBitWidth(), llvm::APInt::getBoolValue(), isIntrinsicSupported(), and llvm_unreachable.
inverse()
ConstantRange ConstantRange::inverse () const
Return a new range that is the logical not of the current set.
Definition at line 1661 of file ConstantRange.cpp.
References isEmptySet(), and isFullSet().
Referenced by llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), difference(), exactIntersectWith(), exactUnionWith(), foldICmpUSubSatOrUAddSatWithConstant(), getPredicateResult(), getValueFromOverflowCondition(), makeSatisfyingICmpRegion(), and simplifyICmpWithConstant().
isAllNegative()
bool ConstantRange::isAllNegative () const
Return true if all values in this range are negative.
Definition at line 411 of file ConstantRange.cpp.
References isEmptySet(), isFullSet(), llvm::APInt::isStrictlyPositive(), and isUpperSignWrapped().
Referenced by areInsensitiveToSignednessOfICmpPredicate(), areInsensitiveToSignednessOfInvertedICmpPredicate(), computeKnownFPClass(), computeOverflowForSignedAdd(), expandUDivOrURem(), and shl().
isAllNonNegative()
bool ConstantRange::isAllNonNegative () const
Return true if all values in this range are non-negative.
Definition at line 421 of file ConstantRange.cpp.
References llvm::APInt::isNonNegative(), and isSignWrappedSet().
Referenced by areInsensitiveToSignednessOfICmpPredicate(), areInsensitiveToSignednessOfInvertedICmpPredicate(), computeKnownFPClass(), computeOverflowForSignedAdd(), getDomain(), processAShr(), processSExt(), and processZExt().
isEmptySet()
bool ConstantRange::isEmptySet () const
Return true if this set contains no members.
Definition at line 371 of file ConstantRange.cpp.
References llvm::APInt::isMinValue().
Referenced by abs(), add(), addWithNoWrap(), areInsensitiveToSignednessOfICmpPredicate(), areInsensitiveToSignednessOfInvertedICmpPredicate(), areNonOverlapSameBaseLoadAndStore(), ashr(), binaryAnd(), binaryOr(), binaryXor(), contains(), ctlz(), ctpop(), cttz(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), getActiveBits(), llvm::AAValueConstantRange::getAssumedConstant(), getEquivalentICmp(), getMinSignedBits(), llvm::ValueLatticeElement::getRange(), intersectWith(), inverse(), isAllNegative(), isImpliedCondCommonOperandWithConstants(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), lshr(), makeAllowedICmpRegion(), makeGuaranteedNoWrapRegion(), llvm::ValueLatticeElement::markConstantRange(), multiply(), print(), sadd_sat(), sdiv(), shl(), signedAddMayOverflow(), signedSubMayOverflow(), signExtend(), llvm::ScalarEvolution::SimplifyICmpOperands(), simplifyICmpWithConstant(), smax(), smin(), smul_fast(), smul_sat(), srem(), sshl_sat(), ssub_sat(), sub(), subWithNoWrap(), toKnownBits(), truncate(), uadd_sat(), udiv(), umax(), umin(), umul_sat(), unionWith(), unsignedAddMayOverflow(), unsignedMulMayOverflow(), unsignedSubMayOverflow(), urem(), ushl_sat(), usub_sat(), and zeroExtend().
isFullSet()
bool ConstantRange::isFullSet () const
Return true if this set contains all of the elements possible for this data-type.
Definition at line 367 of file ConstantRange.cpp.
References llvm::APInt::isMaxValue().
Referenced by add(), addWithNoWrap(), contains(), ctpop(), cttz(), getEquivalentICmp(), llvm::ValueLatticeElement::getRange(), getRangeForAffineARHelper(), getSignedMax(), getSignedMin(), getUnsignedMax(), getUnsignedMin(), intersectWith(), inverse(), isAllNegative(), isSizeLargerThan(), isSizeStrictlySmallerThan(), llvm::IntegerRangeState::isValidState(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), llvm::ValueLatticeElement::markConstantRange(), print(), signExtend(), llvm::ScalarEvolution::SimplifyICmpOperands(), simplifyICmpWithConstant(), sub(), subWithNoWrap(), truncate(), unionWith(), llvm::InstCombinerImpl::visitCallInst(), and zeroExtend().
isIntrinsicSupported()
bool ConstantRange::isIntrinsicSupported (Intrinsic::ID IntrinsicID) static
Returns true if ConstantRange calculations are supported for intrinsic with IntrinsicID.
Definition at line 940 of file ConstantRange.cpp.
Referenced by intrinsic().
isSignWrappedSet()
bool ConstantRange::isSignWrappedSet () const
Return true if this set wraps around the signed domain.
Special cases:
Empty set: Not wrapped.
Full set: Not wrapped.
[X, SignedMin) == [X, SignedMax]: Not wrapped.
Definition at line 383 of file ConstantRange.cpp.
References llvm::APInt::isMinSignedValue(), and llvm::APInt::sgt().
Referenced by abs(), getPreferredRange(), getSignedMin(), isAllNonNegative(), signExtend(), smax(), and smin().
isSingleElement()
bool llvm::ConstantRange::isSingleElement () const inline
Return true if this set contains exactly one member.
Definition at line 261 of file ConstantRange.h.
Referenced by binaryXor(), getPredicateResult(), hasSingleValue(), llvm::SCCPSolver::isConstant(), llvm::ValueLatticeElement::isConstantRange(), makeAllowedICmpRegion(), and runIPSCCP().
isSizeLargerThan()
bool ConstantRange::isSizeLargerThan (uint64_t MaxSize) const
Compare set size of this range with Value.
Definition at line 402 of file ConstantRange.cpp.
References getBitWidth(), llvm::APInt::getMaxValue(), isFullSet(), and llvm::APInt::ugt().
isSizeStrictlySmallerThan()
bool ConstantRange::isSizeStrictlySmallerThan (const ConstantRange & CR) const
Compare set size of this range with the range CR.
Definition at line 392 of file ConstantRange.cpp.
References assert(), getBitWidth(), isFullSet(), and llvm::Other.
Referenced by getPreferredRange(), and multiply().
isUpperSignWrapped()
bool ConstantRange::isUpperSignWrapped () const
Return true if the (exclusive) upper bound wraps around the signed domain.
Special cases:
Empty set: Not wrapped.
Full set: Not wrapped.
[X, SignedMin): Wrapped.
Definition at line 387 of file ConstantRange.cpp.
References llvm::APInt::sgt().
Referenced by getSignedMax(), and isAllNegative().
isUpperWrapped()
bool ConstantRange::isUpperWrapped () const
Return true if the exclusive upper bound wraps around the unsigned domain.
Special cases:
Empty set: Not wrapped.
Full set: Not wrapped.
[X, 0): Wrapped.
Definition at line 379 of file ConstantRange.cpp.
References llvm::APInt::ugt().
Referenced by contains(), getUnsignedMax(), intersectWith(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), multiply(), SwitchToLookupTable(), truncate(), unionWith(), and zeroExtend().
isWrappedSet()
bool ConstantRange::isWrappedSet () const
Return true if this set wraps around the unsigned domain.
Special cases:
Empty set: Not wrapped.
Full set: Not wrapped.
[X, 0) == [X, Max]: Not wrapped.
Definition at line 375 of file ConstantRange.cpp.
References llvm::APInt::isZero(), and llvm::APInt::ugt().
Referenced by ctpop(), cttz(), getPreferredRange(), getUnsignedMin(), umax(), and umin().
lshr()
ConstantRange ConstantRange::lshr (const ConstantRange & Other) const
Return a new range representing the possible values resulting from a logical right shift of a value in this range and a value in Other.
Definition at line 1515 of file ConstantRange.cpp.
References getNonEmpty(), getUnsignedMax(), getUnsignedMin(), isEmptySet(), llvm::APInt::lshr(), llvm::max(), and llvm::Other.
Referenced by binaryOp(), and makeGuaranteedNoWrapRegion().
makeAllowedICmpRegion()
ConstantRange ConstantRange::makeAllowedICmpRegion (CmpInst::Predicate Pred, const ConstantRange & Other) static
Produce the smallest range such that all values that may satisfy the given predicate with any value contained within Other is contained in the returned range.
Formally, this returns a superset of 'union over all y in Other . { x : icmp op x y is true }'. If the exact answer is not representable as a ConstantRange, the return value will be a proper superset of the above.
Example: Pred = ult and Other = i8 [2, 5) returns Result = [0, 4)
Definition at line 97 of file ConstantRange.cpp.
References getBitWidth(), getLower(), llvm::APInt::getMinValue(), getNonEmpty(), getSignedMax(), getSignedMin(), llvm::APInt::getSignedMinValue(), getUnsignedMax(), getUnsignedMin(), getUpper(), llvm::APInt::getZero(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, isEmptySet(), isSingleElement(), llvm_unreachable, llvm::SMax, llvm::SMin, llvm::UMax, and llvm::UMin.
Referenced by llvm::computeConstantRange(), computeKnownBitsFromCmp(), makeExactICmpRegion(), and makeSatisfyingICmpRegion().
makeExactICmpRegion()
ConstantRange ConstantRange::makeExactICmpRegion (CmpInst::Predicate Pred, const APInt & Other) static
Produce the exact range such that all values in the returned range satisfy the given predicate with any value contained within Other.
Formally, this returns the exact answer when the superset of 'union over all y in Other is exactly same as the subset of intersection over all y in Other. { x : icmp op x y is true}'.
Example: Pred = ult and Other = i8 3 returns [0, 3)
Definition at line 157 of file ConstantRange.cpp.
References assert(), llvm::CallingConv::C, makeAllowedICmpRegion(), and makeSatisfyingICmpRegion().
Referenced by llvm::ScalarEvolution::applyLoopGuards(), cmpExcludesZero(), computeKnownBitsFromOperator(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::InstCombinerImpl::foldICmpAddConstant(), foldICmpUSubSatOrUAddSatWithConstant(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), getEquivalentICmp(), getPredicateResult(), isImpliedCondCommonOperandWithConstants(), simplifyAndOrOfICmpsWithConstants(), llvm::ScalarEvolution::SimplifyICmpOperands(), and simplifyICmpWithConstant().
makeExactNoWrapRegion()
ConstantRange ConstantRange::makeExactNoWrapRegion (Instruction::BinaryOps BinOp, const APInt & Other, unsigned NoWrapKind) static
Produce the range that contains X if and only if "X BinOp Other" does not wrap.
Definition at line 359 of file ConstantRange.cpp.
References makeGuaranteedNoWrapRegion(), and llvm::Other.
Referenced by foldICmpUSubSatOrUAddSatWithConstant(), and getValueFromOverflowCondition().
makeGuaranteedNoWrapRegion()
ConstantRange ConstantRange::makeGuaranteedNoWrapRegion (Instruction::BinaryOps BinOp, const ConstantRange & Other, unsigned NoWrapKind) static
Produce the largest range containing all X such that "X BinOp Y" is guaranteed not to wrap (overflow) for all Y in Other.
However, there may be some Y in Other for which additional X not contained in the result also do not overflow.
NoWrapKind must be one of OBO::NoUnsignedWrap or OBO::NoSignedWrap.
Examples: typedef OverflowingBinaryOperator OBO; #define MGNR makeGuaranteedNoWrapRegion MGNR(Add, [i8 1, 2), OBO::NoSignedWrap) == [-128, 127) MGNR(Add, [i8 1, 2), OBO::NoUnsignedWrap) == [0, -1) MGNR(Add, [i8 0, 1), OBO::NoUnsignedWrap) == Full Set MGNR(Add, [i8 -1, 6), OBO::NoSignedWrap) == [INT_MIN+1, INT_MAX-4) MGNR(Sub, [i8 1, 2), OBO::NoSignedWrap) == [-127, 128) MGNR(Sub, [i8 1, 2), OBO::NoUnsignedWrap) == [1, 0)
Definition at line 285 of file ConstantRange.cpp.
References ashr(), assert(), llvm::BitWidth, llvm::CallingConv::C, llvm::APInt::getMaxValue(), llvm::APInt::getMinValue(), getNonEmpty(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), getUnsignedMax(), llvm::APInt::getZero(), intersectWith(), llvm::Instruction::isBinaryOp(), isEmptySet(), llvm_unreachable, lshr(), makeExactMulNSWRegion(), makeExactMulNUWRegion(), llvm::Other, llvm::SMax, llvm::SMin, and Unsigned.
Referenced by llvm::ScalarEvolution::getMulExpr(), makeExactNoWrapRegion(), processBinOp(), llvm::refineInstruction(), StrengthenNoWrapFlags(), and willNotOverflow().
makeSatisfyingICmpRegion()
ConstantRange ConstantRange::makeSatisfyingICmpRegion (CmpInst::Predicate Pred, const ConstantRange & Other) static
Produce the largest range such that all values in the returned range satisfy the given predicate with all values contained within Other.
Formally, this returns a subset of 'intersection over all y in Other . { x : icmp op x y is true }'. If the exact answer is not representable as a ConstantRange, the return value will be a proper subset of the above.
Example: Pred = ult and Other = i8 [2, 5) returns [0, 2)
Definition at line 147 of file ConstantRange.cpp.
References llvm::CmpInst::getInversePredicate(), inverse(), and makeAllowedICmpRegion().
Referenced by icmp(), and makeExactICmpRegion().
multiply()
ConstantRange ConstantRange::multiply (const ConstantRange & Other) const
Return a new range representing the possible values resulting from a multiplication of a value in this range and a value in Other, treating both this and Other as unsigned ranges.
Definition at line 1103 of file ConstantRange.cpp.
References A, B, llvm::CallingConv::C, getBitWidth(), getSignedMax(), getSignedMin(), getSingleElement(), getUnsignedMax(), getUnsignedMin(), getUpper(), llvm::APInt::getZero(), isEmptySet(), llvm::APInt::isMinSignedValue(), llvm::APInt::isNonNegative(), isSizeStrictlySmallerThan(), isUpperWrapped(), llvm::Other, llvm::APInt::sext(), sub(), truncate(), and llvm::APInt::zext().
Referenced by binaryOp(), and llvm::SelectionDAG::computeKnownBits().
operator!=()
bool llvm::ConstantRange::operator!= (const ConstantRange & CR) const inline
Definition at line 291 of file ConstantRange.h.
References operator==().
operator==()
bool llvm::ConstantRange::operator== (const ConstantRange & CR) const inline
Return true if this range is equal to another range.
Definition at line 288 of file ConstantRange.h.
References llvm::Upper.
overflowingBinaryOp()
ConstantRange ConstantRange::overflowingBinaryOp (Instruction::BinaryOps BinOp, const ConstantRange & Other, unsigned NoWrapKind) const
Return a new range representing the possible values resulting from an application of the specified overflowing binary operator to a left hand side of this range and a right hand side of Other given the provided knowledge about lack of wrapping NoWrapKind.
Definition at line 923 of file ConstantRange.cpp.
References addWithNoWrap(), assert(), binaryOp(), llvm::Instruction::isBinaryOp(), llvm::Other, and subWithNoWrap().
print()
void ConstantRange::print (raw_ostream & OS) const
Print out the bounds to a stream.
Definition at line 1975 of file ConstantRange.cpp.
References isEmptySet(), isFullSet(), and OS.
Referenced by dump(), llvm::operator<<(), and llvm::ScalarEvolution::print().
sadd_sat()
ConstantRange ConstantRange::sadd_sat (const ConstantRange & Other) const
Perform a signed saturating addition of two constant ranges.
Definition at line 1584 of file ConstantRange.cpp.
References getNonEmpty(), getSignedMax(), getSignedMin(), isEmptySet(), llvm::Other, and llvm::APInt::sadd_sat().
Referenced by addWithNoWrap().
sdiv()
ConstantRange ConstantRange::sdiv (const ConstantRange & Other) const
Return a new range representing the possible values resulting from a signed division of a value in this range and a value in Other.
Division by zero and division of SignedMin by -1 are considered undefined behavior, in line with IR, and do not contribute towards the result.
Definition at line 1266 of file ConstantRange.cpp.
References contains(), getBitWidth(), llvm::APInt::getSignedMinValue(), llvm::APInt::getZero(), intersectWith(), llvm::APInt::isAllOnes(), isEmptySet(), llvm::APInt::isMinSignedValue(), llvm::APInt::isZero(), llvm::Lo, RHS, llvm::APInt::sdiv(), sdiv(), Signed, and unionWith().
Referenced by binaryOp(), processSDiv(), and sdiv().
sextOrTrunc()
ConstantRange ConstantRange::sextOrTrunc (uint32_t BitWidth) const
Make this range have the bit width given by BitWidth.
The value is sign extended, truncated, or left alone to make it that width.
Definition at line 869 of file ConstantRange.cpp.
References getBitWidth(), signExtend(), and truncate().
Referenced by llvm::ScalarEvolution::getSignExtendExprImpl().
shl()
ConstantRange ConstantRange::shl (const ConstantRange & Other) const
Return a new range representing the possible values resulting from a left shift of a value in this range by a value in Other.
TODO: This isn't fully implemented yet.
Definition at line 1474 of file ConstantRange.cpp.
References llvm::APInt::countl_one(), llvm::countl_zero(), llvm::APInt::getBitsSetFrom(), getBitWidth(), getNonEmpty(), getUnsignedMax(), getUnsignedMin(), llvm::APInt::getZero(), isAllNegative(), isEmptySet(), llvm::Other, RHS, llvm::APInt::ugt(), and llvm::APInt::ule().
Referenced by binaryOp().
signedAddMayOverflow()
ConstantRange::OverflowResult ConstantRange::signedAddMayOverflow (const ConstantRange & Other) const
Return whether signed add of the two ranges always/never overflows.
Definition at line 1879 of file ConstantRange.cpp.
References AlwaysOverflowsHigh, AlwaysOverflowsLow, getBitWidth(), getSignedMax(), llvm::APInt::getSignedMaxValue(), getSignedMin(), llvm::APInt::getSignedMinValue(), isEmptySet(), llvm::APInt::isNegative(), llvm::APInt::isNonNegative(), MayOverflow, NeverOverflows, llvm::Other, llvm::APInt::sgt(), and llvm::APInt::slt().
Referenced by computeOverflowForSignedAdd().
signedSubMayOverflow()
ConstantRange::OverflowResult ConstantRange::signedSubMayOverflow (const ConstantRange & Other) const
Return whether signed sub of the two ranges always/never overflows.
Definition at line 1925 of file ConstantRange.cpp.
References AlwaysOverflowsHigh, AlwaysOverflowsLow, getBitWidth(), getSignedMax(), llvm::APInt::getSignedMaxValue(), getSignedMin(), llvm::APInt::getSignedMinValue(), isEmptySet(), llvm::APInt::isNegative(), llvm::APInt::isNonNegative(), MayOverflow, NeverOverflows, llvm::Other, llvm::APInt::sgt(), and llvm::APInt::slt().
Referenced by llvm::computeOverflowForSignedSub(), and llvm::SelectionDAG::computeOverflowForSignedSub().
signExtend()
ConstantRange ConstantRange::signExtend (uint32_t BitWidth) const
Return a new range in the specified integer type, which must be strictly larger than the current type.
The returned range will correspond to the possible range of values if the source range had been sign extended to BitWidth.
Definition at line 789 of file ConstantRange.cpp.
References assert(), getBitWidth(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), isEmptySet(), isFullSet(), llvm::APInt::isMinSignedValue(), isSignWrappedSet(), llvm::APInt::sext(), and llvm::APInt::zext().
Referenced by castOp(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::ScalarEvolution::getSignExtendExprImpl(), and sextOrTrunc().
smax()
ConstantRange ConstantRange::smax (const ConstantRange & Other) const
Return a new range representing the possible values resulting from a signed maximum of a value in this range and a value in Other.
Definition at line 1190 of file ConstantRange.cpp.
References getNonEmpty(), getSignedMax(), getSignedMin(), intersectWith(), isEmptySet(), isSignWrappedSet(), llvm::Other, Signed, llvm::APIntOps::smax(), and unionWith().
smin()
ConstantRange ConstantRange::smin (const ConstantRange & Other) const
Return a new range representing the possible values resulting from a signed minimum of a value in this range and a value in Other.
Definition at line 1218 of file ConstantRange.cpp.
References getNonEmpty(), getSignedMax(), getSignedMin(), intersectWith(), isEmptySet(), isSignWrappedSet(), llvm::Other, Signed, llvm::APIntOps::smin(), and unionWith().
smul_fast()
ConstantRange ConstantRange::smul_fast (const ConstantRange & Other) const
Return range of possible values for a signed multiplication of this and Other.
However, if overflow is possible always return a full range rather than trying to determine a more precise result.
Definition at line 1170 of file ConstantRange.cpp.
References A, B, getNonEmpty(), getSignedMax(), getSignedMin(), isEmptySet(), llvm::Other, and llvm::APInt::smul_ov().
smul_sat()
ConstantRange ConstantRange::smul_sat (const ConstantRange & Other) const
Perform a signed saturating multiplication of two constant ranges.
Definition at line 1620 of file ConstantRange.cpp.
References A, B, getNonEmpty(), getSignedMax(), getSignedMin(), isEmptySet(), llvm::Other, and llvm::APInt::smul_sat().
srem()
ConstantRange ConstantRange::srem (const ConstantRange & Other) const
Return a new range representing the possible values resulting from a signed remainder operation of a value in this range and a value in Other.
Definition at line 1376 of file ConstantRange.cpp.
References getBitWidth(), getSignedMax(), getSignedMin(), getSingleElement(), getUnsignedMax(), getUnsignedMin(), llvm::APInt::getZero(), isEmptySet(), llvm::APInt::isNonNegative(), llvm::APInt::isZero(), RHS, llvm::APInt::ugt(), llvm::APIntOps::umax(), llvm::APIntOps::umin(), and llvm::Upper.
Referenced by binaryOp().
sshl_sat()
ConstantRange ConstantRange::sshl_sat (const ConstantRange & Other) const
Perform a signed saturating left shift of this constant range by a value in Other.
Definition at line 1650 of file ConstantRange.cpp.
References getNonEmpty(), getSignedMax(), getSignedMin(), isEmptySet(), llvm::APInt::isNonNegative(), llvm::Other, and llvm::APInt::sshl_sat().
ssub_sat()
ConstantRange ConstantRange::ssub_sat (const ConstantRange & Other) const
Perform a signed saturating subtraction of two constant ranges.
Definition at line 1602 of file ConstantRange.cpp.
References getNonEmpty(), getSignedMax(), getSignedMin(), isEmptySet(), llvm::Other, and llvm::APInt::ssub_sat().
Referenced by subWithNoWrap().
sub()
ConstantRange ConstantRange::sub (const ConstantRange & Other) const
Return a new range representing the possible values resulting from a subtraction of a value in this range and a value in Other.
Definition at line 1053 of file ConstantRange.cpp.
References getLower(), getUpper(), isEmptySet(), isFullSet(), llvm::Other, and X.
Referenced by llvm::ScalarEvolution::applyLoopGuards(), binaryNot(), binaryOp(), computeKnownBitsFromCmp(), foldICmpUSubSatOrUAddSatWithConstant(), multiply(), and subWithNoWrap().
subtract()
ConstantRange ConstantRange::subtract (const APInt & CI) const
Subtract the specified constant from the endpoints of this constant range.
Definition at line 492 of file ConstantRange.cpp.
References assert(), llvm::APInt::getBitWidth(), and getBitWidth().
Referenced by llvm::InstCombinerImpl::foldICmpAddConstant().
subWithNoWrap()
ConstantRange ConstantRange::subWithNoWrap (const ConstantRange & Other, unsigned NoWrapKind, PreferredRangeType RangeType = Smallest) const
Return a new range representing the possible values resulting from an subtraction with wrap type NoWrapKind of a value in this range and a value in Other.
If the result range is disjoint, the preferred range is determined by the PreferredRangeType.
Definition at line 1072 of file ConstantRange.cpp.
References getUnsignedMax(), isEmptySet(), isFullSet(), llvm::Other, ssub_sat(), sub(), and usub_sat().
Referenced by overflowingBinaryOp().
toKnownBits()
KnownBits ConstantRange::toKnownBits () const
Return known bits for values in this range.
Definition at line 79 of file ConstantRange.cpp.
References llvm::APInt::clearLowBits(), getBitWidth(), llvm::APIntOps::GetMostSignificantDifferentBit(), getUnsignedMax(), getUnsignedMin(), isEmptySet(), llvm::KnownBits::makeConstant(), llvm::KnownBits::One, and llvm::KnownBits::Zero.
Referenced by binaryAnd(), binaryOr(), binaryXor(), llvm::SelectionDAG::computeKnownBits(), computeKnownBitsFromCmp(), and computeKnownBitsFromOperator().
truncate()
ConstantRange ConstantRange::truncate (uint32_t BitWidth) const
Return a new range in the specified integer type, which must be strictly smaller than the current type.
The returned range will correspond to the possible range of values if the source range had been truncated to the specified type.
Definition at line 807 of file ConstantRange.cpp.
References assert(), llvm::APInt::clearBit(), llvm::APInt::countr_one(), llvm::APInt::getActiveBits(), llvm::APInt::getBitsSetFrom(), getBitWidth(), llvm::APInt::getMaxValue(), isEmptySet(), isFullSet(), isUpperWrapped(), llvm::APInt::setAllBits(), llvm::APInt::trunc(), llvm::APInt::ult(), and unionWith().
Referenced by castOp(), llvm::ScalarEvolution::getSignExtendExprImpl(), llvm::ScalarEvolution::getZeroExtendExprImpl(), multiply(), sextOrTrunc(), and zextOrTrunc().
uadd_sat()
ConstantRange ConstantRange::uadd_sat (const ConstantRange & Other) const
Perform an unsigned saturating addition of two constant ranges.
Definition at line 1575 of file ConstantRange.cpp.
References getNonEmpty(), getUnsignedMax(), getUnsignedMin(), isEmptySet(), llvm::Other, and llvm::APInt::uadd_sat().
Referenced by addWithNoWrap().
udiv()
ConstantRange ConstantRange::udiv (const ConstantRange & Other) const
Return a new range representing the possible values resulting from an unsigned division of a value in this range and a value in Other.
Definition at line 1246 of file ConstantRange.cpp.
References getNonEmpty(), getUnsignedMax(), getUnsignedMin(), isEmptySet(), llvm::APInt::isZero(), RHS, llvm::APInt::udiv(), and llvm::Upper.
Referenced by binaryOp().
umax()
ConstantRange ConstantRange::umax (const ConstantRange & Other) const
Return a new range representing the possible values resulting from an unsigned maximum of a value in this range and a value in Other.
Definition at line 1204 of file ConstantRange.cpp.
References getNonEmpty(), getUnsignedMax(), getUnsignedMin(), intersectWith(), isEmptySet(), isWrappedSet(), llvm::Other, llvm::APIntOps::umax(), unionWith(), and Unsigned.
umin()
ConstantRange ConstantRange::umin (const ConstantRange & Other) const
Return a new range representing the possible values resulting from an unsigned minimum of a value in this range and a value in Other.
Definition at line 1232 of file ConstantRange.cpp.
References getNonEmpty(), getUnsignedMax(), getUnsignedMin(), intersectWith(), isEmptySet(), isWrappedSet(), llvm::Other, llvm::APIntOps::umin(), unionWith(), and Unsigned.
umul_sat()
ConstantRange ConstantRange::umul_sat (const ConstantRange & Other) const
Perform an unsigned saturating multiplication of two constant ranges.
Definition at line 1611 of file ConstantRange.cpp.
References getNonEmpty(), getUnsignedMax(), getUnsignedMin(), isEmptySet(), llvm::Other, and llvm::APInt::umul_sat().
Referenced by expandUDivOrURem().
unionWith()
ConstantRange ConstantRange::unionWith (const ConstantRange & CR, PreferredRangeType Type = Smallest) const
Return the range that results from the union of this range with another range.
The resultant range is guaranteed to include the elements of both sets, but may contain more. For example, [3, 9) union [12,15) is [3, 15), which includes 9, 10, and 11, which were not included in either set before.
Definition at line 630 of file ConstantRange.cpp.
References assert(), getBitWidth(), getPreferredRange(), isEmptySet(), isFullSet(), isUpperWrapped(), llvm::APInt::uge(), llvm::APInt::ugt(), llvm::APInt::ule(), llvm::APInt::ult(), and unionWith().
Referenced by llvm::computeConstantRange(), ctpop(), cttz(), exactIntersectWith(), exactUnionWith(), llvm::getConstantRangeFromMetadata(), llvm::ValueLatticeElement::mergeIn(), llvm::IntegerRangeState::operator&=(), sdiv(), smax(), smin(), truncate(), tryMergeRange(), umax(), umin(), llvm::IntegerRangeState::unionAssumed(), and unionWith().
unsignedAddMayOverflow()
ConstantRange::OverflowResult ConstantRange::unsignedAddMayOverflow (const ConstantRange & Other) const
Return whether unsigned add of the two ranges always/never overflows.
Definition at line 1863 of file ConstantRange.cpp.
References AlwaysOverflowsHigh, getUnsignedMax(), getUnsignedMin(), isEmptySet(), MayOverflow, NeverOverflows, llvm::Other, and llvm::APInt::ugt().
Referenced by llvm::computeOverflowForUnsignedAdd(), and llvm::SelectionDAG::computeOverflowForUnsignedAdd().
unsignedMulMayOverflow()
ConstantRange::OverflowResult ConstantRange::unsignedMulMayOverflow (const ConstantRange & Other) const
Return whether unsigned mul of the two ranges always/never overflows.
Definition at line 1955 of file ConstantRange.cpp.
References AlwaysOverflowsHigh, getUnsignedMax(), getUnsignedMin(), isEmptySet(), MayOverflow, NeverOverflows, llvm::Other, and llvm::APInt::umul_ov().
Referenced by llvm::computeOverflowForUnsignedMul(), and llvm::SelectionDAG::computeOverflowForUnsignedMul().
unsignedSubMayOverflow()
ConstantRange::OverflowResult ConstantRange::unsignedSubMayOverflow (const ConstantRange & Other) const
Return whether unsigned sub of the two ranges always/never overflows.
Definition at line 1909 of file ConstantRange.cpp.
References AlwaysOverflowsLow, getUnsignedMax(), getUnsignedMin(), isEmptySet(), MayOverflow, NeverOverflows, llvm::Other, and llvm::APInt::ult().
Referenced by llvm::computeOverflowForUnsignedSub(), and llvm::SelectionDAG::computeOverflowForUnsignedSub().
urem()
ConstantRange ConstantRange::urem (const ConstantRange & Other) const
Return a new range representing the possible values resulting from an unsigned remainder operation of a value in this range and a value in Other.
Definition at line 1354 of file ConstantRange.cpp.
References getBitWidth(), getNonEmpty(), getSingleElement(), getUnsignedMax(), llvm::APInt::getZero(), isEmptySet(), RHS, llvm::APIntOps::umin(), and llvm::Upper.
Referenced by binaryOp(), and canScalarizeAccess().
ushl_sat()
ConstantRange ConstantRange::ushl_sat (const ConstantRange & Other) const
Perform an unsigned saturating left shift of this constant range by a value in Other.
Definition at line 1641 of file ConstantRange.cpp.
References getNonEmpty(), getUnsignedMax(), getUnsignedMin(), isEmptySet(), llvm::Other, and llvm::APInt::ushl_sat().
usub_sat()
ConstantRange ConstantRange::usub_sat (const ConstantRange & Other) const
Perform an unsigned saturating subtraction of two constant ranges.
Definition at line 1593 of file ConstantRange.cpp.
References getNonEmpty(), getUnsignedMax(), getUnsignedMin(), isEmptySet(), llvm::Other, and llvm::APInt::usub_sat().
Referenced by subWithNoWrap().
zeroExtend()
ConstantRange ConstantRange::zeroExtend (uint32_t BitWidth) const
Return a new range in the specified integer type, which must be strictly larger than the current type.
The returned range will correspond to the possible range of values if the source range had been zero extended to BitWidth.
Definition at line 772 of file ConstantRange.cpp.
References assert(), getBitWidth(), llvm::APInt::getOneBitSet(), isEmptySet(), isFullSet(), isUpperWrapped(), and llvm::APInt::zext().
Referenced by castOp(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::ScalarEvolution::getZeroExtendExprImpl(), and zextOrTrunc().
zextOrTrunc()
ConstantRange ConstantRange::zextOrTrunc (uint32_t BitWidth) const
Make this range have the bit width given by BitWidth.
The value is zero extended, truncated, or left alone to make it that width.
Definition at line 860 of file ConstantRange.cpp.
References getBitWidth(), truncate(), and zeroExtend().
Referenced by llvm::ScalarEvolution::getZeroExtendExprImpl().
The documentation for this class was generated from the following files:
include/llvm/IR/ConstantRange.h
lib/IR/ConstantRange.cpp