LLVM: llvm::logicalview::LVTypeVisitor Class Reference
llvm::logicalview::LVTypeVisitor Class Reference final
#include "llvm/DebugInfo/LogicalView/Readers/LVCodeViewVisitor.h"
Public Member Functions
LVTypeVisitor (ScopedPrinter &W, LVLogicalVisitor *LogicalVisitor, LazyRandomTypeCollection &Types, LazyRandomTypeCollection &Ids, uint32_t StreamIdx, LVShared *Shared)
Error visitTypeBegin (CVType &Record) override
Paired begin/end actions for all types.
Error visitTypeBegin (CVType &Record, TypeIndex TI) override
Error visitMemberBegin (CVMemberRecord &Record) override
Error visitMemberEnd (CVMemberRecord &Record) override
Error visitUnknownMember (CVMemberRecord &Record) override
Error visitKnownRecord (CVType &Record, BuildInfoRecord &Args) override
Error visitKnownRecord (CVType &Record, ClassRecord &Class) override
Error visitKnownRecord (CVType &Record, EnumRecord &Enum) override
Error visitKnownRecord (CVType &Record, FuncIdRecord &Func) override
Error visitKnownRecord (CVType &Record, ProcedureRecord &Proc) override
Error visitKnownRecord (CVType &Record, StringIdRecord &String) override
Error visitKnownRecord (CVType &Record, UdtSourceLineRecord &Line) override
Error visitKnownRecord (CVType &Record, UnionRecord &Union) override
Error visitUnknownType (CVType &Record) override
Action to take on unknown types. By default, they are ignored.
Public Member Functions inherited from llvm::codeview::TypeVisitorCallbacks
virtual ~TypeVisitorCallbacks ()=default
virtual Error visitUnknownType (CVType &Record)
Action to take on unknown types. By default, they are ignored.
virtual Error visitTypeBegin (CVType &Record)
Paired begin/end actions for all types.
virtual Error visitTypeBegin (CVType &Record, TypeIndex Index)
virtual Error visitTypeEnd (CVType &Record)
virtual Error visitUnknownMember (CVMemberRecord &Record)
virtual Error visitMemberBegin (CVMemberRecord &Record)
virtual Error visitMemberEnd (CVMemberRecord &Record)
Detailed Description
Definition at line 39 of file LVCodeViewVisitor.h.
Constructor & Destructor Documentation
LVTypeVisitor()
llvm::logicalview::LVTypeVisitor::LVTypeVisitor (ScopedPrinter & W, LVLogicalVisitor * LogicalVisitor, LazyRandomTypeCollection & Types, LazyRandomTypeCollection & Ids, uint32_t StreamIdx, LVShared * Shared) inline
Definition at line 60 of file LVCodeViewVisitor.h.
References llvm::logicalview::Types.
Member Function Documentation
visitKnownRecord() [1/8]
Error LVTypeVisitor::visitKnownRecord (CVType & Record, BuildInfoRecord & Args) override
Definition at line 539 of file LVCodeViewVisitor.cpp.
References Arguments, llvm::codeview::LazyRandomTypeCollection::getTypeName(), LLVM_DEBUG, llvm::ScopedPrinter::printNumber(), llvm::logicalview::LVLogicalVisitor::setCompileUnitName(), llvm::pdb::StreamIPI, llvm::String, llvm::logicalview::LVShared::StringRecords, and llvm::Error::success().
visitKnownRecord() [2/8]
Error LVTypeVisitor::visitKnownRecord (CVType & Record, ClassRecord & Class) override
Definition at line 571 of file LVCodeViewVisitor.cpp.
References llvm::pdb::Class, llvm::logicalview::LVShared::ForwardReferences, LLVM_DEBUG, llvm::logicalview::LVShared::NamespaceDeduction, llvm::ScopedPrinter::printString(), llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::logicalview::LVShared::TypeRecords.
visitKnownRecord() [3/8]
Error LVTypeVisitor::visitKnownRecord (CVType & Record, EnumRecord & Enum) override
Definition at line 589 of file LVCodeViewVisitor.cpp.
References llvm::pdb::Enum, LLVM_DEBUG, llvm::logicalview::LVShared::NamespaceDeduction, llvm::ScopedPrinter::printString(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownRecord() [4/8]
Error LVTypeVisitor::visitKnownRecord (CVType & Record, FuncIdRecord & Func) override
Definition at line 602 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, llvm::logicalview::LVShared::NamespaceDeduction, llvm::ScopedPrinter::printString(), llvm::pdb::StreamTPI, and llvm::Error::success().
visitKnownRecord() [5/8]
Error LVTypeVisitor::visitKnownRecord (CVType & Record, ProcedureRecord & Proc) override
Definition at line 616 of file LVCodeViewVisitor.cpp.
References llvm::codeview::ProcedureRecord::getArgumentList(), llvm::codeview::ProcedureRecord::getParameterCount(), llvm::codeview::ProcedureRecord::getReturnType(), LLVM_DEBUG, llvm::ScopedPrinter::printNumber(), llvm::pdb::StreamTPI, llvm::Error::success(), and llvm::logicalview::LVShared::TypeRecords.
visitKnownRecord() [6/8]
Error LVTypeVisitor::visitKnownRecord (CVType & Record, StringIdRecord & String) override
Definition at line 630 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, llvm::ScopedPrinter::printString(), llvm::pdb::StreamIPI, llvm::String, and llvm::Error::success().
visitKnownRecord() [7/8]
Error LVTypeVisitor::visitKnownRecord (CVType & Record, UdtSourceLineRecord & Line) override
Definition at line 640 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVShared::LineRecords, LLVM_DEBUG, llvm::ScopedPrinter::printNumber(), llvm::pdb::StreamIPI, and llvm::Error::success().
visitKnownRecord() [8/8]
Error LVTypeVisitor::visitKnownRecord (CVType & Record, UnionRecord & Union) override
Definition at line 654 of file LVCodeViewVisitor.cpp.
References llvm::logicalview::LVShared::ForwardReferences, if(), LLVM_DEBUG, llvm::logicalview::LVShared::NamespaceDeduction, llvm::ScopedPrinter::printNumber(), llvm::ScopedPrinter::printString(), llvm::pdb::StreamTPI, llvm::Error::success(), llvm::logicalview::LVShared::TypeRecords, and llvm::pdb::Union.
visitMemberBegin()
Error LVTypeVisitor::visitMemberBegin (CVMemberRecord & Record) override virtual
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 516 of file LVCodeViewVisitor.cpp.
References llvm::pdb::formatTypeLeafKind(), llvm::ScopedPrinter::getOStream(), llvm::ScopedPrinter::indent(), LLVM_DEBUG, llvm::ScopedPrinter::startLine(), and llvm::Error::success().
visitMemberEnd()
Error LVTypeVisitor::visitMemberEnd (CVMemberRecord & Record) override virtual
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 525 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, llvm::ScopedPrinter::startLine(), llvm::Error::success(), and llvm::ScopedPrinter::unindent().
visitTypeBegin() [1/2]
Error LVTypeVisitor::visitTypeBegin (CVType & Record) override virtual
Paired begin/end actions for all types.
Receives all record data, including the fixed-length record prefix. visitTypeBegin() should return the type of the Record, or an error if it cannot be determined. Exactly one of the two visitTypeBegin methods will be called, depending on whether records are being visited sequentially or randomly. An implementation should be prepared to handle both (or assert if it can't handle random access visitation).
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 491 of file LVCodeViewVisitor.cpp.
References llvm::codeview::TypeIndex::fromArrayIndex(), llvm::codeview::LazyRandomTypeCollection::size(), and visitTypeBegin().
Referenced by visitTypeBegin().
visitTypeBegin() [2/2]
Error LVTypeVisitor::visitTypeBegin (CVType & Record, TypeIndex TI) override virtual
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 495 of file LVCodeViewVisitor.cpp.
References llvm::pdb::formatTypeLeafKind(), llvm::codeview::TypeIndex::getIndex(), llvm::ScopedPrinter::getOStream(), LLVM_DEBUG, llvm::logicalview::options(), llvm::Error::success(), llvm::logicalview::LVShared::TypeKinds, and llvm::logicalview::LVShared::TypeRecords.
visitUnknownMember()
Error LVTypeVisitor::visitUnknownMember (CVMemberRecord & Record) override virtual
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 533 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, llvm::ScopedPrinter::printHex(), and llvm::Error::success().
visitUnknownType()
Error LVTypeVisitor::visitUnknownType (CVType & Record) override virtual
Action to take on unknown types. By default, they are ignored.
Reimplemented from llvm::codeview::TypeVisitorCallbacks.
Definition at line 511 of file LVCodeViewVisitor.cpp.
References LLVM_DEBUG, llvm::ScopedPrinter::printNumber(), and llvm::Error::success().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Readers/LVCodeViewVisitor.h
lib/DebugInfo/LogicalView/Readers/LVCodeViewVisitor.cpp