LLVM: llvm::FixedStreamArrayIterator< T > Class Template Reference
llvm::FixedStreamArrayIterator< T > Class Template Reference
#include "llvm/Support/BinaryStreamArray.h"
Public Member Functions
FixedStreamArrayIterator (const FixedStreamArray< T > &Array, uint32_t Index)
FixedStreamArrayIterator (const FixedStreamArrayIterator< T > &Other)
FixedStreamArrayIterator< T > & operator= (const FixedStreamArrayIterator< T > &Other)
const T & operator* () const
const T & operator* ()
bool operator== (const FixedStreamArrayIterator< T > &R) const
FixedStreamArrayIterator< T > & operator+= (std::ptrdiff_t N)
FixedStreamArrayIterator< T > & operator-= (std::ptrdiff_t N)
std::ptrdiff_t operator- (const FixedStreamArrayIterator< T > &R) const
bool operator< (const FixedStreamArrayIterator< T > &RHS) const
Public Member Functions inherited from llvm::iterator_facade_base< FixedStreamArrayIterator< T >, std::random_access_iterator_tag, const T >
FixedStreamArrayIterator< T > operator+ (std::ptrdiff_t n) const
FixedStreamArrayIterator< T > operator- (std::ptrdiff_t n) const
FixedStreamArrayIterator< T > & operator++ ()
FixedStreamArrayIterator< T > operator++ (int)
FixedStreamArrayIterator< T > & operator-- ()
FixedStreamArrayIterator< T > operator-- (int)
bool operator!= (const FixedStreamArrayIterator< T > &RHS) const
bool operator> (const FixedStreamArrayIterator< T > &RHS) const
bool operator<= (const FixedStreamArrayIterator< T > &RHS) const
bool operator>= (const FixedStreamArrayIterator< T > &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< FixedStreamArrayIterator< T >, std::random_access_iterator_tag, const T >
using iterator_category = std::random_access_iterator_tag
using value_type = const T
using difference_type = std::ptrdiff_t
using pointer = const T *
using reference = const T &
Protected Types inherited from llvm::iterator_facade_base< FixedStreamArrayIterator< T >, std::random_access_iterator_tag, const T >
enum
Detailed Description
template<typename T>
class llvm::FixedStreamArrayIterator< T >
Definition at line 320 of file BinaryStreamArray.h.
Constructor & Destructor Documentation
FixedStreamArrayIterator() [1/2]
template<typename T > llvm::FixedStreamArrayIterator< T >::FixedStreamArrayIterator (const FixedStreamArray< T > & Array, uint32_t Index) inline
Definition at line 325 of file BinaryStreamArray.h.
FixedStreamArrayIterator() [2/2]
template<typename T > llvm::FixedStreamArrayIterator< T >::FixedStreamArrayIterator (const FixedStreamArrayIterator< T > & Other) inline
Definition at line 328 of file BinaryStreamArray.h.
Member Function Documentation
operator*() [1/2]
template<typename T > const T & llvm::FixedStreamArrayIterator< T >::operator* () inline
Definition at line 338 of file BinaryStreamArray.h.
operator*() [2/2]
template<typename T > const T & llvm::FixedStreamArrayIterator< T >::operator* () const inline
Definition at line 337 of file BinaryStreamArray.h.
operator+=()
template<typename T > FixedStreamArrayIterator< T > & llvm::FixedStreamArrayIterator< T >::operator+= (std::ptrdiff_t N) inline
Definition at line 345 of file BinaryStreamArray.h.
References N.
operator-()
template<typename T > std::ptrdiff_t llvm::FixedStreamArrayIterator< T >::operator- (const FixedStreamArrayIterator< T > & R) const inline
Definition at line 356 of file BinaryStreamArray.h.
References assert().
operator-=()
template<typename T > FixedStreamArrayIterator< T > & llvm::FixedStreamArrayIterator< T >::operator-= (std::ptrdiff_t N) inline
Definition at line 350 of file BinaryStreamArray.h.
References assert(), and N.
operator<()
template<typename T > bool llvm::FixedStreamArrayIterator< T >::operator< (const FixedStreamArrayIterator< T > & RHS) const inline
Definition at line 362 of file BinaryStreamArray.h.
References assert(), and RHS.
operator=()
template<typename T > FixedStreamArrayIterator< T > & llvm::FixedStreamArrayIterator< T >::operator= (const FixedStreamArrayIterator< T > & Other) inline
Definition at line 331 of file BinaryStreamArray.h.
References llvm::Other.
operator==()
template<typename T > bool llvm::FixedStreamArrayIterator< T >::operator== (const FixedStreamArrayIterator< T > & R) const inline
Definition at line 340 of file BinaryStreamArray.h.
References assert().
The documentation for this class was generated from the following file:
include/llvm/Support/BinaryStreamArray.h