LLVM: llvm::DotFuncBCIInfo Class Reference
llvm::DotFuncBCIInfo Class Reference
Public Member Functions
DotFuncBCIInfo (const BlockCoverageInference *BCI, const DenseMap< const BasicBlock *, bool > *Coverage)
const Function & getFunction ()
bool isInstrumented (const BasicBlock *BB) const
bool isCovered (const BasicBlock *BB) const
bool isDependent (const BasicBlock *Src, const BasicBlock *Dest) const
Detailed Description
Definition at line 250 of file BlockCoverageInference.cpp.
Constructor & Destructor Documentation
DotFuncBCIInfo()
llvm::DotFuncBCIInfo::DotFuncBCIInfo (const BlockCoverageInference * BCI, const DenseMap< const BasicBlock *, bool > * Coverage) inline
Definition at line 256 of file BlockCoverageInference.cpp.
Member Function Documentation
getFunction()
const Function & llvm::DotFuncBCIInfo::getFunction () inline
Definition at line 260 of file BlockCoverageInference.cpp.
isCovered()
bool llvm::DotFuncBCIInfo::isCovered (const BasicBlock * BB) const inline
Definition at line 266 of file BlockCoverageInference.cpp.
isDependent()
bool llvm::DotFuncBCIInfo::isDependent (const BasicBlock * Src, const BasicBlock * Dest) const inline
Definition at line 270 of file BlockCoverageInference.cpp.
References llvm::SetVector< T, Vector, Set, N >::count(), and llvm::BlockCoverageInference::getDependencies().
isInstrumented()
bool llvm::DotFuncBCIInfo::isInstrumented (const BasicBlock * BB) const inline
Definition at line 262 of file BlockCoverageInference.cpp.
References llvm::BlockCoverageInference::shouldInstrumentBlock().
The documentation for this class was generated from the following file:
lib/Transforms/Instrumentation/BlockCoverageInference.cpp