LLVM: llvm::SmallVectorBase< Size_T > Class Template Reference
llvm::SmallVectorBase< Size_T > Class Template Reference
This is all the stuff common to all SmallVectors.
#include "llvm/ADT/SmallVector.h"
Inherited by llvm::SmallVectorTemplateCommon< std::pair< ValueType, SUList > >, llvm::SmallVectorTemplateCommon< Function * >, llvm::SmallVectorTemplateCommon< AddressRange >, llvm::SmallVectorTemplateCommon< AddressRangeValuePair >, llvm::SmallVectorTemplateCommon< std::unique_ptr< DWARFUnit > >, llvm::SmallVectorTemplateCommon< BasicBlock * >, llvm::SmallVectorTemplateCommon< llvm::DomTreeNodeBase * >, llvm::SmallVectorTemplateCommon< BlockT * >, llvm::SmallVectorTemplateCommon< BoUpSLP::EdgeInfo >, llvm::SmallVectorTemplateCommon< llvm::MCFixup >, llvm::SmallVectorTemplateCommon< char >, llvm::SmallVectorTemplateCommon< Edge >, llvm::SmallVectorTemplateCommon< llvm::cl::parser::OptionInfo >, llvm::SmallVectorTemplateCommon< std::pair< const MachineFunction *, Register > >, llvm::SmallVectorTemplateCommon< std::pair< const T *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateCommon< std::pair< SPIRV::SpecialTypeDescriptor, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateCommon< std::pair< KeyT, ValueT > >, llvm::SmallVectorTemplateCommon< std::tuple< NodeRef, ChildItTy, ChildItTy > >, llvm::SmallVectorTemplateCommon< llvm::AAPointerInfo::Access >, llvm::SmallVectorTemplateCommon< Slice >, llvm::SmallVectorTemplateCommon< VariableGEPIndex >, llvm::SmallVectorTemplateCommon< int >, llvm::SmallVectorTemplateCommon< llvm::PointerUnion< llvm::Value *, const TreeEntry * > >, llvm::SmallVectorTemplateCommon< llvm::Value * >, llvm::SmallVectorTemplateCommon< llvm::Instruction * >, llvm::SmallVectorTemplateCommon< const llvm::MachineInstr * >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::Function *, const llvm::DISubprogram * > >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::Instruction *, bool > >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::Instruction *, llvm::WeakVH > >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::DILocalVariable *, unsigned > >, llvm::SmallVectorTemplateCommon< VarLocInfo >, llvm::SmallVectorTemplateCommon< llvm::SUnit * >, llvm::SmallVectorTemplateCommon< LiveDebugValues::ValueIDNum >, llvm::SmallVectorTemplateCommon< llvm::MachineOperand >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::SmallVector > >, llvm::SmallVectorTemplateCommon< DebugPHIRecord >, llvm::SmallVectorTemplateCommon< ValueIDNum >, llvm::SmallVectorTemplateCommon< unsigned >, llvm::SmallVectorTemplateCommon< llvm::Register >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::MachineOperand *, unsigned > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::DebugVariable, LiveDebugValues::DbgValue > >, llvm::SmallVectorTemplateCommon< std::pair< StringRef, size_t > >, llvm::SmallVectorTemplateCommon< MachineInstr * >, llvm::SmallVectorTemplateCommon< std::pair< BlockFrequency, unsigned > >, llvm::SmallVectorTemplateCommon< TransferTracker::Transfer >, llvm::SmallVectorTemplateCommon< ResolvedDbgOp >, llvm::SmallVectorTemplateCommon< DbgOp >, llvm::SmallVectorTemplateCommon< uint32_t >, llvm::SmallVectorTemplateCommon< DepTy >, llvm::SmallVectorTemplateCommon< void(*)(llvm::Function &F, llvm::AnalysisManager &AM, llvm::AAResults &llvm::AAResults) >, llvm::SmallVectorTemplateCommon< RangeTy >, llvm::SmallVectorTemplateCommon< AAQueryInfo::LocPair >, llvm::SmallVectorTemplateCommon< llvm::ForwardedRegister >, llvm::SmallVectorTemplateCommon< MILOHDirective >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, llvm::MCSymbol * > >, llvm::SmallVectorTemplateCommon< llvm::MachineInstr * >, llvm::SmallVectorTemplateCommon< llvm::BasicBlockInfo >, llvm::SmallVectorTemplateCommon< FCmpLibcallsList >, llvm::SmallVectorTemplateCommon< std::pair< StringRef, HashData > >, llvm::SmallVectorTemplateCommon< llvm::MemoryLocation >, llvm::SmallVectorTemplateCommon< uint8_t >, llvm::SmallVectorTemplateCommon< uint16_t >, llvm::SmallVectorTemplateCommon< AnalysisID >, llvm::SmallVectorTemplateCommon< std::pair< uint16_t, Form > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::StringRef, llvm::ArchYAML::Archive::Child::Field > >, llvm::SmallVectorTemplateCommon< FreeList * >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, llvm::AsmPrinter::MBBSectionRange > >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::MCSymbol *, GOTEquivUsePair > >, llvm::SmallVectorTemplateCommon< llvm::AsmPrinter::XRayFunctionEntry >, llvm::SmallVectorTemplateCommon< std::pair< MCSection *, ConstantPool > >, llvm::SmallVectorTemplateCommon< llvm::AssumptionCache::ResultElem >, llvm::SmallVectorTemplateCommon< llvm::Attribute >, llvm::SmallVectorTemplateCommon< llvm::Function * >, llvm::SmallVectorTemplateCommon< llvm::SmallVector * >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Use *, llvm::Value * > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Value *, llvm::PointerIntPair< llvm::Value *, 1, bool > > >, llvm::SmallVectorTemplateCommon< llvm::WeakVH >, llvm::SmallVectorTemplateCommon< llvm::BasicBlock * >, llvm::SmallVectorTemplateCommon< llvm::AbstractAttribute * >, llvm::SmallVectorTemplateCommon< llvm::Type * >, llvm::SmallVectorTemplateCommon< llvm::BitCodeAbbrevOp >, llvm::SmallVectorTemplateCommon< BitValue >, llvm::SmallVectorTemplateCommon< BitWord >, llvm::SmallVectorTemplateCommon< Block >, llvm::SmallVectorTemplateCommon< Weight >, llvm::SmallVectorTemplateCommon< std::pair< BlockNode, BlockMass > >, llvm::SmallVectorTemplateCommon< BlockNode >, llvm::SmallVectorTemplateCommon< BlockMass >, llvm::SmallVectorTemplateCommon< void * >, llvm::SmallVectorTemplateCommon< std::pair< void *, size_t > >, llvm::SmallVectorTemplateCommon< llvm::CCValAssign >, llvm::SmallVectorTemplateCommon< llvm::ISD::ArgFlagsTy >, llvm::SmallVectorTemplateCommon< ByValInfo >, llvm::SmallVectorTemplateCommon< llvm::LazyCallGraph::RefSCC * >, llvm::SmallVectorTemplateCommon< llvm::LazyCallGraph::SCC * >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Value *, llvm::WeakTrackingVH > >, llvm::SmallVectorTemplateCommon< ConstantPoolEntry >, llvm::SmallVectorTemplateCommon< AttributeItem >, llvm::SmallVectorTemplateCommon< Loop * >, llvm::SmallVectorTemplateCommon< LoopTripCountTy >, llvm::SmallVectorTemplateCommon< LoopCacheCostTy >, llvm::SmallVectorTemplateCommon< llvm::CallLowering::ArgInfo >, llvm::SmallVectorTemplateCommon< std::pair< MDString *, MethodsList > >, llvm::SmallVectorTemplateCommon< Value * >, llvm::SmallVectorTemplateCommon< llvm::AllocaInst * >, llvm::SmallVectorTemplateCommon< llvm::unique_function< bool(llvm::StringRef)> >, llvm::SmallVectorTemplateCommon< llvm::unique_function< void(llvm::StringRef)> >, llvm::SmallVectorTemplateCommon< FileInfo >, llvm::SmallVectorTemplateCommon< CVGlobalVariable >, llvm::SmallVectorTemplateCommon< const llvm::DIDerivedType * >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::Function *, std::unique_ptr< FunctionInfo > > >, llvm::SmallVectorTemplateCommon< const llvm::DISubprogram * >, llvm::SmallVectorTemplateCommon< const llvm::DICompositeType * >, llvm::SmallVectorTemplateCommon< const llvm::DILocation * >, llvm::SmallVectorTemplateCommon< llvm::codeview::TypeIndex >, llvm::SmallVectorTemplateCommon< LocalVariable >, llvm::SmallVectorTemplateCommon< LexicalBlock * >, llvm::SmallVectorTemplateCommon< std::pair< llvm::CodeViewDebug::LocalVarDef, llvm::SmallVector< std::pair< const llvm::MCSymbol *, const llvm::MCSymbol * >, 1 > > >, llvm::SmallVectorTemplateCommon< std::pair< GlobalVariable *, ConstCandVecType > >, llvm::SmallVectorTemplateCommon< consthoist::ConstantInfo >, llvm::SmallVectorTemplateCommon< std::pair< GlobalVariable *, ConstInfoVecType > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Instruction *, llvm::Instruction * > >, llvm::SmallVectorTemplateCommon< llvm::SmallVector< Entry, 8 > >, llvm::SmallVectorTemplateCommon< bool >, llvm::SmallVectorTemplateCommon< llvm::SDNode * >, llvm::SmallVectorTemplateCommon< EdgeType * >, llvm::SmallVectorTemplateCommon< llvm::ValueAsMetadata * >, llvm::SmallVectorTemplateCommon< llvm::TypedTrackingMDRef >, llvm::SmallVectorTemplateCommon< llvm::DISubprogram * >, llvm::SmallVectorTemplateCommon< llvm::Metadata * >, llvm::SmallVectorTemplateCommon< std::pair< llvm::MDNode *, llvm::SetVector< llvm::Metadata * > > >, llvm::SmallVectorTemplateCommon< llvm::DIEAbbrevData >, llvm::SmallVectorTemplateCommon< llvm::DILineInfo >, llvm::SmallVectorTemplateCommon< TypeUnitMetaInfo >, llvm::SmallVectorTemplateCommon< AttributeSpec >, llvm::SmallVectorTemplateCommon< llvm::DWARFFormValue >, llvm::SmallVectorTemplateCommon< LocationList >, llvm::SmallVectorTemplateCommon< llvm::DWARFLocationEntry >, llvm::SmallVectorTemplateCommon< Entry >, llvm::SmallVectorTemplateCommon< llvm::DWARFDebugNames::NameIndex >, llvm::SmallVectorTemplateCommon< uint64_t >, llvm::SmallVectorTemplateCommon< Encoding >, llvm::SmallVectorTemplateCommon< CompUnitEntry >, llvm::SmallVectorTemplateCommon< TypeUnitEntry >, llvm::SmallVectorTemplateCommon< AddressEntry >, llvm::SmallVectorTemplateCommon< SymTableEntry >, llvm::SmallVectorTemplateCommon< std::pair< uint32_t, llvm::SmallVector< uint32_t, 0 > > >, llvm::SmallVectorTemplateCommon< llvm::dxbc::PSV::v2::ResourceBindInfo >, llvm::SmallVectorTemplateCommon< llvm::DXContainerYAML::SignatureElement >, llvm::SmallVectorTemplateCommon< llvm::yaml::Hex32 >, llvm::SmallVectorTemplateCommon< llvm::DXContainerYAML::SignatureParameter >, llvm::SmallVectorTemplateCommon< unsigned char >, llvm::SmallVectorTemplateCommon< LayoutAlignElem >, llvm::SmallVectorTemplateCommon< PointerAlignElem >, llvm::SmallVectorTemplateCommon< std::pair< InlinedEntity, const MachineInstr * > >, llvm::SmallVectorTemplateCommon< std::pair< InlinedEntity, Entries > >, llvm::SmallVectorTemplateCommon< llvm::DbgValueLocEntry >, llvm::SmallVectorTemplateCommon< int64_t >, llvm::SmallVectorTemplateCommon< llvm::DICompileUnit * >, llvm::SmallVectorTemplateCommon< llvm::DIGlobalVariableExpression * >, llvm::SmallVectorTemplateCommon< llvm::DIType * >, llvm::SmallVectorTemplateCommon< llvm::DIScope * >, llvm::SmallVectorTemplateCommon< llvm::DbgValueLoc >, llvm::SmallVectorTemplateCommon< llvm::DebugLocStream::List >, llvm::SmallVectorTemplateCommon< llvm::DebugLocStream::Entry >, llvm::SmallVectorTemplateCommon< std::string >, llvm::SmallVectorTemplateCommon< llvm::Init * >, llvm::SmallVectorTemplateCommon< llvm::DiagnosticInfoOptimizationBase::Argument >, llvm::SmallVectorTemplateCommon< NodeType * >, llvm::SmallVectorTemplateCommon< llvm::DomTreeNodeBase >, llvm::SmallVectorTemplateCommon< DominatorTree::UpdateType >, llvm::SmallVectorTemplateCommon< NodeT * >, llvm::SmallVectorTemplateCommon< llvm::RangeSpan >, llvm::SmallVectorTemplateCommon< const MDNode * >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::MDNode *, llvm::DwarfCompileUnit * > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::DbgEntity > >, llvm::SmallVectorTemplateCommon< std::pair< std::unique_ptr< llvm::DwarfTypeUnit >, const llvm::DICompositeType * > >, llvm::SmallVectorTemplateCommon< llvm::DwarfExpression::Register >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::DwarfCompileUnit > >, llvm::SmallVectorTemplateCommon< llvm::RangeSpanList >, llvm::SmallVectorTemplateCommon< llvm::DbgVariable * >, llvm::SmallVectorTemplateCommon< llvm::SmallVector< unsigned, 8 > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::GlobalVariable > >, llvm::SmallVectorTemplateCommon< MutableValue >, llvm::SmallVectorTemplateCommon< llvm::DomainValue * >, llvm::SmallVectorTemplateCommon< LiveRegsDVInfo >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::Module > >, llvm::SmallVectorTemplateCommon< llvm::GlobalValue * >, llvm::SmallVectorTemplateCommon< llvm::ISD::InputArg >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Instruction *, llvm::ConstantRange > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Instruction *, llvm::Value * > >, llvm::SmallVectorTemplateCommon< T * >, llvm::SmallVectorTemplateCommon< llvm::FunctionLoweringInfo::LiveOutInfo >, llvm::SmallVectorTemplateCommon< llvm::BBClusterInfo >, llvm::SmallVectorTemplateCommon< llvm::SmallVector< unsigned > >, llvm::SmallVectorTemplateCommon< llvm::DebugVariable >, llvm::SmallVectorTemplateCommon< llvm::VarLocInfo >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::GCStrategy > >, llvm::SmallVectorTemplateCommon< GCNSchedStageID >, llvm::SmallVectorTemplateCommon< std::pair< llvm::MachineInstrBundleIterator, llvm::MachineInstrBundleIterator > >, llvm::SmallVectorTemplateCommon< llvm::DenseMap >, llvm::SmallVectorTemplateCommon< llvm::GCNRegPressure >, llvm::SmallVectorTemplateCommon< llvm::GCOVArc * >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::GCOVFunction > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::GCOVBlock > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::GCOVArc > >, llvm::SmallVectorTemplateCommon< llvm::LLT >, llvm::SmallVectorTemplateCommon< llvm::GISelChangeObserver * >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Value *, llvm::Value * > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Instruction *, unsigned > >, llvm::SmallVectorTemplateCommon< const CycleT * >, llvm::SmallVectorTemplateCommon< SubGlobPattern >, llvm::SmallVectorTemplateCommon< llvm::GlobPattern::SubGlobPattern::Bracket >, llvm::SmallVectorTemplateCommon< llvm::cfg::Update< NodePtr > >, llvm::SmallVectorTemplateCommon< NodePtr >, llvm::SmallVectorTemplateCommon< MCOperand >, llvm::SmallVectorTemplateCommon< HexagonInstr >, llvm::SmallVectorTemplateCommon< llvm::HexagonInstr * >, llvm::SmallVectorTemplateCommon< NodeTy * >, llvm::SmallVectorTemplateCommon< llvm::cfg::Update< llvm::BasicBlock * > >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, llvm::MDNode * > >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::PHINode *, llvm::SmallVector< llvm::MachineInstr *, 1 > > >, llvm::SmallVectorTemplateCommon< InlineGraphNode * >, llvm::SmallVectorTemplateCommon< uintptr_t >, llvm::SmallVectorTemplateCommon< Meta >, llvm::SmallVectorTemplateCommon< const llvm::SCEV * >, llvm::SmallVectorTemplateCommon< const llvm::Instruction * >, llvm::SmallVectorTemplateCommon< Instruction * >, llvm::SmallVectorTemplateCommon< const char * >, llvm::SmallVectorTemplateCommon< llvm::WeakTrackingVH >, llvm::SmallVectorTemplateCommon< llvm::CallBase * >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::RecurrenceDescriptor *, llvm::PHINode * > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::SlotIndex, llvm::SlotIndex > >, llvm::SmallVectorTemplateCommon< llvm::TemporalProfTraceTy >, llvm::SmallVectorTemplateCommon< std::pair< uint64_t, llvm::memprof::IndexedMemProfRecord > >, llvm::SmallVectorTemplateCommon< std::pair< uint64_t, llvm::memprof::Frame > >, llvm::SmallVectorTemplateCommon< std::function< void(MachineInstrBuilder &)> >, llvm::SmallVectorTemplateCommon< llvm::InstructionBuildSteps >, llvm::SmallVectorTemplateCommon< RegUnitInfo >, llvm::SmallVectorTemplateCommon< BlockInterference >, llvm::SmallVectorTemplateCommon< DataType >, llvm::SmallVectorTemplateCommon< PointType >, llvm::SmallVectorTemplateCommon< const DataType * >, llvm::SmallVectorTemplateCommon< const llvm::Value * >, llvm::SmallVectorTemplateCommon< ScopeContext >, llvm::SmallVectorTemplateCommon< llvm::MCRegister >, llvm::SmallVectorTemplateCommon< llvm::Loop * >, llvm::SmallVectorTemplateCommon< llvm::MCSymbol * >, llvm::SmallVectorTemplateCommon< llvm::SEHHandler >, llvm::SmallVectorTemplateCommon< llvm::LazyCallGraph::Node * >, llvm::SmallVectorTemplateCommon< std::pair< llvm::BasicBlock *, llvm::Value * > >, llvm::SmallVectorTemplateCommon< SizeChangeStrategy >, llvm::SmallVectorTemplateCommon< SizeAndActionsVec >, llvm::SmallVectorTemplateCommon< llvm::LegalizeRule >, llvm::SmallVectorTemplateCommon< std::pair< bool, llvm::StringRef > >, llvm::SmallVectorTemplateCommon< llvm::LexicalScope * >, llvm::SmallVectorTemplateCommon< InsnRange >, llvm::SmallVectorTemplateCommon< const llvm::LiveInterval * >, llvm::SmallVectorTemplateCommon< llvm::LiveInterval * >, llvm::SmallVectorTemplateCommon< llvm::SlotIndex >, llvm::SmallVectorTemplateCommon< const uint32_t * >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, unsigned > >, llvm::SmallVectorTemplateCommon< llvm::LiveRange * >, llvm::SmallVectorTemplateCommon< MCPhysReg >, llvm::SmallVectorTemplateCommon< Segment >, llvm::SmallVectorTemplateCommon< VNInfo * >, llvm::SmallVectorTemplateCommon< LiveOutPair >, llvm::SmallVectorTemplateCommon< LiveInBlock >, llvm::SmallVectorTemplateCommon< llvm::LiveRange::Segment >, llvm::SmallVectorTemplateCommon< IndexMaskPair >, llvm::SmallVectorTemplateCommon< llvm::LiveVariables::VarInfo >, llvm::SmallVectorTemplateCommon< llvm::GStore * >, llvm::SmallVectorTemplateCommon< std::pair< llvm::MachineInstr *, unsigned > >, llvm::SmallVectorTemplateCommon< llvm::StoreInst * >, llvm::SmallVectorTemplateCommon< MBBInfo >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Instruction *, uint64_t > >, llvm::SmallVectorTemplateCommon< std::pair< PHINode *, RecurrenceDescriptor > >, llvm::SmallVectorTemplateCommon< std::pair< PHINode *, InductionDescriptor > >, llvm::SmallVectorTemplateCommon< VPlanPtr >, llvm::SmallVectorTemplateCommon< llvm::VectorizationFactor >, llvm::SmallVectorTemplateCommon< RuntimePointerCheck >, llvm::SmallVectorTemplateCommon< llvm::DebugLoc >, llvm::SmallVectorTemplateCommon< llvm::MCSection * >, llvm::SmallVectorTemplateCommon< llvm::AsmToken >, llvm::SmallVectorTemplateCommon< llvm::MCAsmParser::MCPendingError >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::MCSymbol *, const llvm::MCSymbol * > >, llvm::SmallVectorTemplateCommon< std::pair< std::string, std::string > >, llvm::SmallVectorTemplateCommon< llvm::MCDwarfFile >, llvm::SmallVectorTemplateCommon< llvm::MCELFStreamer::AttributeItem >, llvm::SmallVectorTemplateCommon< llvm::MCDataFragment * >, llvm::SmallVectorTemplateCommon< llvm::MCOperand >, llvm::SmallVectorTemplateCommon< llvm::object::OwningBinary< llvm::object::Archive > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::MemoryBuffer > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::object::ObjectFile > >, llvm::SmallVectorTemplateCommon< llvm::MCLOHDirective >, llvm::SmallVectorTemplateCommon< std::pair< MCSection *, MCDwarfLineEntryCollection > >, llvm::SmallVectorTemplateCommon< PendingMCFixup >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, llvm::MCFragment * > >, llvm::SmallVectorTemplateCommon< PendingLabel >, llvm::SmallVectorTemplateCommon< std::pair< size_t, llvm::MCSection * > >, llvm::SmallVectorTemplateCommon< std::pair< MCSectionSubPair, MCSectionSubPair > >, llvm::SmallVectorTemplateCommon< llvm::MDAttachments::Attachment >, llvm::SmallVectorTemplateCommon< llvm::StringRef >, llvm::SmallVectorTemplateCommon< Target >, llvm::SmallVectorTemplateCommon< std::pair< llvm::MachO::ObjCIVarRecord, ValueT > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::StringRef, llvm::MachO::ObjCCategoryRecord * > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::MachO::GlobalRecord, ValueT > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::MachO::ObjCInterfaceRecord, ValueT > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::MachO::ObjCCategoryRecord, std::pair< llvm::StringRef, llvm::StringRef > > >, llvm::SmallVectorTemplateCommon< llvm::MachineBasicBlock * >, llvm::SmallVectorTemplateCommon< CriticalEdge >, llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >, llvm::SmallVectorTemplateCommon< VariableDbgInfo >, llvm::SmallVectorTemplateCommon< llvm::MachineFunction::DebugSubstitution >, llvm::SmallVectorTemplateCommon< llvm::unique_function< FuncTy > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::PointerUnion, llvm::MachineOperand * > >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, llvm::SmallVector< llvm::Register, 4 > > >, llvm::SmallVectorTemplateCommon< LLT >, llvm::SmallVectorTemplateCommon< llvm::MachineTraceMetrics::FixedBlockInfo >, llvm::SmallVectorTemplateCommon< llvm::MachineTraceMetrics::TraceBlockInfo >, llvm::SmallVectorTemplateCommon< llvm::MachineTraceMetrics::LiveInReg >, llvm::SmallVectorTemplateCommon< llvm::MemoryDepChecker::Dependence >, llvm::SmallVectorTemplateCommon< llvm::AssertingVH< llvm::MemoryPhi > >, llvm::SmallVectorTemplateCommon< Inst >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::MipsOptionRecord > >, llvm::SmallVectorTemplateCommon< const BlockT * >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::ScheduleHazardRecognizer > >, llvm::SmallVectorTemplateCommon< llvm::OpenMPIRBuilder::FinalizationInfo >, llvm::SmallVectorTemplateCommon< llvm::OpenMPIRBuilder::OutlineInfo >, llvm::SmallVectorTemplateCommon< DeviceInfoTy >, llvm::SmallVectorTemplateCommon< omp::OpenMPOffloadMappingFlags >, llvm::SmallVectorTemplateCommon< Constant * >, llvm::SmallVectorTemplateCommon< MapValuesArrayTy >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::Value *, std::pair< llvm::Value *, llvm::Value * > > >, llvm::SmallVectorTemplateCommon< llvm::Pass * >, llvm::SmallVectorTemplateCommon< llvm::PMDataManager * >, llvm::SmallVectorTemplateCommon< llvm::ImmutablePass * >, llvm::SmallVectorTemplateCommon< ParamType >, llvm::SmallVectorTemplateCommon< llvm::AsmRewrite >, llvm::SmallVectorTemplateCommon< std::function< void(llvm::PassManager &, llvm::OptimizationLevel)> >, llvm::SmallVectorTemplateCommon< std::function< void(llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > &, llvm::OptimizationLevel)> >, llvm::SmallVectorTemplateCommon< std::function< void(PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & > &, llvm::OptimizationLevel)> >, llvm::SmallVectorTemplateCommon< std::function< void(llvm::AnalysisManager &)> >, llvm::SmallVectorTemplateCommon< std::function< bool(llvm::StringRef, llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorTemplateCommon< std::function< bool(llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorTemplateCommon< std::function< bool(llvm::StringRef, PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & > &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorTemplateCommon< std::function< bool(llvm::StringRef, llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorTemplateCommon< std::function< bool(llvm::StringRef Name, llvm::AAManager &AA)> >, llvm::SmallVectorTemplateCommon< std::function< void(llvm::MachineFunctionAnalysisManager &)> >, llvm::SmallVectorTemplateCommon< std::function< bool(llvm::StringRef, llvm::MachineFunctionPassManager &)> >, llvm::SmallVectorTemplateCommon< InsertedPass >, llvm::SmallVectorTemplateCommon< llvm::unique_function< BeforePassFunc > >, llvm::SmallVectorTemplateCommon< llvm::unique_function< BeforeSkippedPassFunc > >, llvm::SmallVectorTemplateCommon< llvm::unique_function< BeforeNonSkippedPassFunc > >, llvm::SmallVectorTemplateCommon< llvm::unique_function< AfterPassFunc > >, llvm::SmallVectorTemplateCommon< llvm::unique_function< AfterPassInvalidatedFunc > >, llvm::SmallVectorTemplateCommon< llvm::unique_function< BeforeAnalysisFunc > >, llvm::SmallVectorTemplateCommon< llvm::unique_function< AfterAnalysisFunc > >, llvm::SmallVectorTemplateCommon< llvm::unique_function< AnalysisInvalidatedFunc > >, llvm::SmallVectorTemplateCommon< llvm::unique_function< AnalysesClearedFunc > >, llvm::SmallVectorTemplateCommon< DDGNode * >, llvm::SmallVectorTemplateCommon< MemberTy >, llvm::SmallVectorTemplateCommon< std::pair< unsigned, llvm::MapVector< llvm::MachineInstr *, llvm::MachineInstr * > > >, llvm::SmallVectorTemplateCommon< llvm::AssertingVH< llvm::Function > >, llvm::SmallVectorTemplateCommon< ValueInfo >, llvm::SmallVectorTemplateCommon< llvm::PredicateBase * >, llvm::SmallVectorTemplateCommon< PassRunDescriptor >, llvm::SmallVectorTemplateCommon< llvm::SpillPlacement::BlockConstraint >, llvm::SmallVectorTemplateCommon< GlobalSplitCandidate >, llvm::SmallVectorTemplateCommon< RegInfo >, llvm::SmallVectorTemplateCommon< TraversedMBBInfo >, llvm::SmallVectorTemplateCommon< LiveRegsDefInfo >, llvm::SmallVectorTemplateCommon< MBBDefsInfo >, llvm::SmallVectorTemplateCommon< llvm::SMLoc >, llvm::SmallVectorTemplateCommon< llvm::SMRange >, llvm::SmallVectorTemplateCommon< llvm::RecordVal >, llvm::SmallVectorTemplateCommon< llvm::Record::AssertionInfo >, llvm::SmallVectorTemplateCommon< llvm::Record::DumpInfo >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Record *, llvm::SMRange > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< InsertPoint > >, llvm::SmallVectorTemplateCommon< ScavengedInfo >, llvm::SmallVectorTemplateCommon< llvm::RegisterMaskPair >, llvm::SmallVectorTemplateCommon< llvm::EVT >, llvm::SmallVectorTemplateCommon< llvm::MVT >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::DFAPacketizer > >, llvm::SmallVectorTemplateCommon< llvm::SmallVector< uint64_t, DefaultProcResSize > >, llvm::SmallVectorTemplateCommon< NodeRef >, llvm::SmallVectorTemplateCommon< SID >, llvm::SmallVectorTemplateCommon< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >, llvm::SmallVectorTemplateCommon< IFuncStub >, llvm::SmallVectorTemplateCommon< llvm::RuntimeDyldMachO::EHFrameRelatedSections >, llvm::SmallVectorTemplateCommon< llvm::RuntimePointerChecking::PointerInfo >, llvm::SmallVectorTemplateCommon< llvm::RuntimeCheckingPtrGroup >, llvm::SmallVectorTemplateCommon< llvm::PointerDiffInfo >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Function *, llvm::ValueLatticeElement > >, llvm::SmallVectorTemplateCommon< std::pair< std::pair< llvm::Function *, unsigned >, llvm::ValueLatticeElement > >, llvm::SmallVectorTemplateCommon< SCEVInsertPointGuard * >, llvm::SmallVectorTemplateCommon< const llvm::SCEVPredicate * >, llvm::SmallVectorTemplateCommon< llvm::SDDbgValue * >, llvm::SmallVectorTemplateCommon< llvm::SDDbgLabel * >, llvm::SmallVectorTemplateCommon< std::pair< Register, int > >, llvm::SmallVectorTemplateCommon< Register >, llvm::SmallVectorTemplateCommon< std::pair< Value *, StoreList > >, llvm::SmallVectorTemplateCommon< std::pair< Value *, GEPList > >, llvm::SmallVectorTemplateCommon< llvm::SMFixIt >, llvm::SmallVectorTemplateCommon< llvm::SPIRV::DTSortableEntry * >, llvm::SmallVectorTemplateCommon< SPIRV::Capability::Capability >, llvm::SmallVectorTemplateCommon< Capability::Capability >, llvm::SmallVectorTemplateCommon< Extension::Extension >, llvm::SmallVectorTemplateCommon< std::pair< KeyTy, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::Type *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::Constant *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::GlobalVariable *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::Function *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::Argument *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::SPIRV::SpecialTypeDescriptor *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateCommon< SPIRV::Extension::Extension >, llvm::SmallVectorTemplateCommon< SPIRV::InstructionSet::InstructionSet >, llvm::SmallVectorTemplateCommon< llvm::PHINode * >, llvm::SmallVectorTemplateCommon< RewriteInfo >, llvm::SmallVectorTemplateCommon< llvm::Use * >, llvm::SmallVectorTemplateCommon< PhiT * >, llvm::SmallVectorTemplateCommon< llvm::SDep >, llvm::SmallVectorTemplateCommon< ExitNotTakenInfo >, llvm::SmallVectorTemplateCommon< llvm::APInt >, llvm::SmallVectorTemplateCommon< RootData >, llvm::SmallVectorTemplateCommon< TreeData >, llvm::SmallVectorTemplateCommon< SMSNode >, llvm::SmallVectorTemplateCommon< std::pair< llvm::SUnit *, llvm::SUnit * > >, llvm::SmallVectorTemplateCommon< llvm::sys::MemoryBlock >, llvm::SmallVectorTemplateCommon< FreeMemBlock >, llvm::SmallVectorTemplateCommon< std::pair< const llvm::Value *, DanglingDebugInfoVector > >, llvm::SmallVectorTemplateCommon< llvm::SDValue >, llvm::SmallVectorTemplateCommon< const llvm::GCRelocateInst * >, llvm::SmallVectorTemplateCommon< IdxMBBPair >, llvm::SmallVectorTemplateCommon< ValueT >, llvm::SmallVectorTemplateCommon< llvm::ArgInfo >, llvm::SmallVectorTemplateCommon< llvm::BlockFrequency >, llvm::SmallVectorTemplateCommon< llvm::SplitAnalysis::BlockInfo >, llvm::SmallVectorTemplateCommon< const llvm::IntrinsicInst * >, llvm::SmallVectorTemplateCommon< llvm::StackLifetime::LiveRange >, llvm::SmallVectorTemplateCommon< std::pair< uint64_t, uint64_t > >, llvm::SmallVectorTemplateCommon< std::pair< const MCSymbol *, FunctionInfo > >, llvm::SmallVectorTemplateCommon< Location >, llvm::SmallVectorTemplateCommon< LiveOutReg >, llvm::SmallVectorTemplateCommon< llvm::ArgumentInit * >, llvm::SmallVectorTemplateCommon< llvm::IRPosition >, llvm::SmallVectorTemplateCommon< llvm::SuffixTreeInternalNode * >, llvm::SmallVectorTemplateCommon< const Value * >, llvm::SmallVectorTemplateCommon< llvm::SmallPtrSet< llvm::SUnit *, 4 > >, llvm::SmallVectorTemplateCommon< llvm::SmallVector< int, 4 > >, llvm::SmallVectorTemplateCommon< BitTestCase >, llvm::SmallVectorTemplateCommon< std::pair< std::pair< const MCSymbol *, unsigned >, uint32_t > >, llvm::SmallVectorTemplateCommon< llvm::DefsetRecord * >, llvm::SmallVectorTemplateCommon< std::pair< GlobalVariable *, tlshoist::TLSCandidate > >, llvm::SmallVectorTemplateCommon< llvm::ISD::OutputArg >, llvm::SmallVectorTemplateCommon< llvm::Timer * >, llvm::SmallVectorTemplateCommon< TimeTraceProfilerEntry >, llvm::SmallVectorTemplateCommon< llvm::TruncInst * >, llvm::SmallVectorTemplateCommon< std::pair< llvm::Instruction *, Info > >, llvm::SmallVectorTemplateCommon< llvm::VFInfo >, llvm::SmallVectorTemplateCommon< llvm::VFParameter >, llvm::SmallVectorTemplateCommon< llvm::VPBlockBase * >, llvm::SmallVectorTemplateCommon< llvm::VPHeaderPHIRecipe * >, llvm::SmallVectorTemplateCommon< llvm::VPValue * >, llvm::SmallVectorTemplateCommon< llvm::VPUser * >, llvm::SmallVectorTemplateCommon< llvm::VPBasicBlock * >, llvm::SmallVectorTemplateCommon< llvm::ElementCount >, llvm::SmallVectorTemplateCommon< std::pair< llvm::PHINode *, llvm::VPLiveOut * > >, llvm::SmallVectorTemplateCommon< VPBlockBase * >, llvm::SmallVectorTemplateCommon< MultiNodeOpTy >, llvm::SmallVectorTemplateCommon< wasm::ValType >, llvm::SmallVectorTemplateCommon< llvm::SmallVector< wasm::ValType, 4 > >, llvm::SmallVectorTemplateCommon< std::pair< uint64_t, bool > >, llvm::SmallVectorTemplateCommon< EHInstKind >, llvm::SmallVectorTemplateCommon< std::pair< llvm::MCSymbol *, llvm::WinEH::FrameInfo::Epilog > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::MCSymbol *, int64_t > >, llvm::SmallVectorTemplateCommon< llvm::CxxUnwindMapEntry >, llvm::SmallVectorTemplateCommon< llvm::WinEHTryBlockMapEntry >, llvm::SmallVectorTemplateCommon< llvm::SEHUnwindMapEntry >, llvm::SmallVectorTemplateCommon< llvm::ClrEHUnwindMapEntry >, llvm::SmallVectorTemplateCommon< llvm::WinEHHandlerType >, llvm::SmallVectorTemplateCommon< size_t >, llvm::SmallVectorTemplateCommon< llvm::SmallVector< size_t, 4 > >, llvm::SmallVectorTemplateCommon< llvm::cl::OptionCategory * >, llvm::SmallVectorTemplateCommon< llvm::cl::Option * >, llvm::SmallVectorTemplateCommon< llvm::cl::SubCommand * >, llvm::SmallVectorTemplateCommon< llvm::cl::OptionEnumValue >, llvm::SmallVectorTemplateCommon< llvm::ArrayRef< uint8_t > >, llvm::SmallVectorTemplateCommon< RecordLimit >, llvm::SmallVectorTemplateCommon< llvm::codeview::GloballyHashedType >, llvm::SmallVectorTemplateCommon< ConstantUser >, llvm::SmallVectorTemplateCommon< RebasedConstantInfo >, llvm::SmallVectorTemplateCommon< llvm::AnyCoroEndInst * >, llvm::SmallVectorTemplateCommon< llvm::CoroSizeInst * >, llvm::SmallVectorTemplateCommon< llvm::CoroAlignInst * >, llvm::SmallVectorTemplateCommon< llvm::AnyCoroSuspendInst * >, llvm::SmallVectorTemplateCommon< llvm::CallInst * >, llvm::SmallVectorTemplateCommon< const llvm::coverage::CoverageSegment * >, llvm::SmallVectorTemplateCommon< TestVector >, llvm::SmallVectorTemplateCommon< llvm::detail::PtrUseVisitorBase::UseToVisit >, llvm::SmallVectorTemplateCommon< PatchLocation >, llvm::SmallVectorTemplateCommon< AccelTableKind >, llvm::SmallVectorTemplateCommon< llvm::dwarf_linker::parallel::CompileUnit::DIEInfo >, llvm::SmallVectorTemplateCommon< llvm::StringMapEntry * >, llvm::SmallVectorTemplateCommon< uint64_t * >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< CompileUnit > >, llvm::SmallVectorTemplateCommon< RefModuleUnit >, llvm::SmallVectorTemplateCommon< DWARFLinkerBase::AccelTableKind >, llvm::SmallVectorTemplateCommon< LiveRootWorklistItemTy >, llvm::SmallVectorTemplateCommon< const llvm::StringMapEntry * >, llvm::SmallVectorTemplateCommon< llvm::dxil::UAVResource >, llvm::SmallVectorTemplateCommon< llvm::dxil::ConstantBuffer >, llvm::SmallVectorTemplateCommon< llvm::fuzzerop::SourcePred >, llvm::SmallVectorTemplateCommon< SmallVector< uint64_t, 4 > >, llvm::SmallVectorTemplateCommon< ElemT >, llvm::SmallVectorTemplateCommon< llvm::jitlink::ppc64::PLTCallStubReloc >, llvm::SmallVectorTemplateCommon< State >, llvm::SmallVectorTemplateCommon< LVLine * >, llvm::SmallVectorTemplateCommon< LVScope * >, llvm::SmallVectorTemplateCommon< LVSymbol * >, llvm::SmallVectorTemplateCommon< LVType * >, llvm::SmallVectorTemplateCommon< LVElement * >, llvm::SmallVectorTemplateCommon< LVTotalsEntry >, llvm::SmallVectorTemplateCommon< std::pair< StringRef, BitcodeModule > >, llvm::SmallVectorTemplateCommon< EncodingInfo >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::mca::HardwareUnit > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::mca::Instruction > >, llvm::SmallVectorTemplateCommon< llvm::mca::InstRef >, llvm::SmallVectorTemplateCommon< llvm::mca::WriteDescriptor >, llvm::SmallVectorTemplateCommon< llvm::mca::ReadDescriptor >, llvm::SmallVectorTemplateCommon< std::pair< uint64_t, llvm::mca::ResourceUsage > >, llvm::SmallVectorTemplateCommon< llvm::mca::WriteState >, llvm::SmallVectorTemplateCommon< llvm::mca::ReadState >, llvm::SmallVectorTemplateCommon< ResourceUse >, llvm::SmallVectorTemplateCommon< llvm::mca::MemoryGroup * >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::mca::Stage > >, llvm::SmallVectorTemplateCommon< RegisterMappingTracker >, llvm::SmallVectorTemplateCommon< std::pair< llvm::mca::ReadState *, int > >, llvm::SmallVectorTemplateCommon< llvm::mcdxbc::PSVSignatureElement >, llvm::SmallVectorTemplateCommon< Parameter >, llvm::SmallVectorTemplateCommon< llvm::memprof::Frame >, llvm::SmallVectorTemplateCommon< llvm::memprof::IndexedAllocationInfo >, llvm::SmallVectorTemplateCommon< llvm::SmallVector< uint64_t > >, llvm::SmallVectorTemplateCommon< llvm::memprof::AllocationInfo >, llvm::SmallVectorTemplateCommon< llvm::SmallVector< llvm::memprof::Frame > >, llvm::SmallVectorTemplateCommon< SegmentEntry >, llvm::SmallVectorTemplateCommon< std::pair< uint64_t, MemInfoBlock > >, llvm::SmallVectorTemplateCommon< llvm::IntrinsicInst * >, llvm::SmallVectorTemplateCommon< llvm::DbgVariableIntrinsic * >, llvm::SmallVectorTemplateCommon< std::pair< llvm::AllocaInst *, llvm::memtag::AllocaInfo > >, llvm::SmallVectorTemplateCommon< llvm::objcopy::elf::SectionBase * >, llvm::SmallVectorTemplateCommon< SectionInfo >, llvm::SmallVectorTemplateCommon< NodeState >, llvm::SmallVectorTemplateCommon< const uint8_t * >, llvm::SmallVectorTemplateCommon< llvm::object::DataRefImpl >, llvm::SmallVectorTemplateCommon< LoadCommandInfo >, llvm::SmallVectorTemplateCommon< StringRef >, llvm::SmallVectorTemplateCommon< std::pair< llvm::StringRef, llvm::StringRef > >, llvm::SmallVectorTemplateCommon< llvm::object::PGOAnalysisMap::PGOBBEntry::SuccessorEntry >, llvm::SmallVectorTemplateCommon< TraitProperty >, llvm::SmallVectorTemplateCommon< Arg * >, llvm::SmallVectorTemplateCommon< std::unique_ptr< llvm::opt::Arg > >, llvm::SmallVectorTemplateCommon< llvm::StringLiteral >, llvm::SmallVectorTemplateCommon< std::pair< std::string, llvm::orc::ExecutorAddr > >, llvm::SmallVectorTemplateCommon< std::tuple< ExecutorAddr, ExecutorAddr, MachOExecutorSymbolFlags > >, llvm::SmallVectorTemplateCommon< llvm::orc::ExecutorAddrRange >, llvm::SmallVectorTemplateCommon< InjectedSourceDescriptor >, llvm::SmallVectorTemplateCommon< const llvm::TargetRegisterClass * >, llvm::SmallVectorTemplateCommon< llvm::remarks::BitstreamRemarkParserHelper::Argument >, llvm::SmallVectorTemplateCommon< llvm::remarks::Argument >, llvm::SmallVectorTemplateCommon< StackRegion >, llvm::SmallVectorTemplateCommon< StackObject >, llvm::SmallVectorTemplateCommon< std::pair< llvm::sampleprof::FunctionId, uint32_t > >, llvm::SmallVectorTemplateCommon< llvm::sampleprof::SecHdrTableEntry >, llvm::SmallVectorTemplateCommon< std::pair< llvm::sampleprof::SampleContext, uint64_t > >, llvm::SmallVectorTemplateCommon< std::pair< llvm::sampleprof::SampleContext, uint32_t > >, llvm::SmallVectorTemplateCommon< const SamplesWithLoc * >, llvm::SmallVectorTemplateCommon< std::unique_ptr< TreeEntry > >, llvm::SmallVectorTemplateCommon< const TreeEntry * >, llvm::SmallVectorTemplateCommon< ExternalUser >, llvm::SmallVectorTemplateCommon< std::pair< llvm::BasicBlock *, std::unique_ptr< BlockScheduling > > >, llvm::SmallVectorTemplateCommon< std::unique_ptr< ScheduleData[]> >, llvm::SmallVectorTemplateCommon< ScheduleData * >, llvm::SmallVectorTemplateCommon< llvm::slpvectorizer::BoUpSLP::EdgeInfo >, llvm::SmallVectorTemplateCommon< SmallVector< Value *, 8 > >, llvm::SmallVectorTemplateCommon< llvm::SmallVector >, llvm::SmallVectorTemplateCommon< const MMap * >, llvm::SmallVectorTemplateCommon< llvm::symbolize::MarkupNode >, llvm::SmallVectorTemplateCommon< llvm::tlshoist::TLSUser >, llvm::SmallVectorTemplateCommon< IntrusiveRefCntPtr< FileSystem > >, llvm::SmallVectorTemplateCommon< llvm::vfs::RedirectingFileSystem::Entry * >, llvm::SmallVectorTemplateCommon< ValType >, llvm::SmallVectorTemplateCommon< TrieNode * >, llvm::SmallVectorTemplateCommon< llvm::yaml::StringValue >, and llvm::SmallVectorTemplateCommon< SimpleKey >.
Public Member Functions
size_t size () const
size_t capacity () const
bool empty () const
Protected Member Functions
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void * mallocForGrow (void *FirstEl, size_t MinSize, size_t TSize, size_t &NewCapacity)
This is a helper for grow() that's out of line to reduce code duplication.
void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
void * replaceAllocation (void *NewElts, size_t TSize, size_t NewCapacity, size_t VSize=0)
If vector was first created with capacity 0, getFirstEl() points to the memory right after, an area unallocated.
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
void set_allocation_range (void *Begin, size_t N)
Set the array data pointer to Begin and capacity to N.
Static Protected Member Functions
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
Protected Attributes
void * BeginX
Size_T Size = 0
Size_T Capacity
Detailed Description
template<class Size_T>
class llvm::SmallVectorBase< Size_T >
This is all the stuff common to all SmallVectors.
The template parameter specifies the type which should be used to hold the Size and Capacity of the SmallVector, so it can be adjusted. Using 32 bit size is desirable to shrink the size of the SmallVector. Using 64 bit size is desirable for cases like SmallVector<char>, where a 32 bit size would limit the vector to ~4GB. SmallVectors are used for buffering bitcode output - which can exceed 4GB.
Definition at line 52 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorBase() [1/2]
template<class Size_T > llvm::SmallVectorBase< Size_T >::SmallVectorBase () protected delete
SmallVectorBase() [2/2]
template<class Size_T > llvm::SmallVectorBase< Size_T >::SmallVectorBase (void * FirstEl, size_t TotalCapacity) inline protected
Definition at line 63 of file SmallVector.h.
Member Function Documentation
capacity()
template<class Size_T > size_t llvm::SmallVectorBase< Size_T >::capacity () const inline
Definition at line 92 of file SmallVector.h.
References llvm::SmallVectorBase< Size_T >::Capacity.
Referenced by llvm::SmallVectorBase< Size_T >::set_size().
empty()
template<class Size_T > bool llvm::SmallVectorBase< Size_T >::empty () const inline
Definition at line 94 of file SmallVector.h.
References llvm::SmallVectorBase< Size_T >::Size.
Referenced by llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::add(), llvm::PMDataManager::add(), llvm::slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::add(), AddAliasScopeMetadata(), addAllGlobalValueUsers(), addBlockAndPredsToSet(), addBoundsChecking(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::MCPseudoProbeInlineTree::addPseudoProbe(), addRange(), llvm::RecurrenceDescriptor::AddReductionVar(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addTemplateParamNames(), llvm::ConstraintSystem::addVariableRow(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::LegalizeRuleSet::aliasTo(), allUsersAreInFunction(), allUsesOfLoadAndStores(), allUsesOfLoadedValueWillTrapIfNull(), allZeroIndices(), llvm::LoopInfoBase< BlockT, LoopT >::analyze(), llvm::LanaiInstrInfo::analyzeBranch(), llvm::dwarf_linker::parallel::CompileUnit::analyzeImportedModule(), llvm::analyzeImportedModule(), analyzeLoopUnrollCost(), llvm::Annotations::Annotations(), llvm::LiveRange::append(), llvm::sys::path::append(), llvm::appendReversedLoopsToWorklist(), llvm::A57ChainingConstraint::apply(), llvm::ScalarEvolution::applyLoopGuards(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingLoad(), llvm::AMDGPURegisterBankInfo::applyMappingSMULU64(), llvm::MemorySSAUpdater::applyUpdates(), llvm::AMDGPUCallLowering::areCalleeOutgoingArgsTailCallable(), llvm::RegBankSelect::assignInstr(), llvm::RegBankSelect::assignRegisterBanks(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::atEnd(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildClonedLoops(), llvm::CSEMIRBuilder::buildInstr(), buildMultiplyTree(), llvm::opt::OptTable::buildPrefixChars(), llvm::CombinerHelper::buildSDivUsingMul(), CalcNodeSethiUllmanNumber(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), llvm::calculateClrEHStateNumbers(), llvm::calculateCXXStateForAsynchEH(), llvm::calculateSEHStateForAsynchEH(), callIsStructReturn(), canonicalizePHIOperands(), canReturn(), llvm::ScalarEvolution::canReuseInstruction(), canRewriteGEPAsOffset(), canRotateDeoptimizingLatchExit(), llvm::TailDuplicator::canTailDuplicate(), canUseReferenceType(), canVectorizeLoads(), CC_LoongArch(), llvm::RISCV::CC_RISCV(), llvm::CC_SystemZ_I128Indirect(), CC_X86_32_MCUInReg(), llvm::PatternMatch::undef_match::check(), checkClobberSanity(), llvm::Attributor::checkForAllUses(), llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches(), checkIfSupported(), checkMixedPrecision(), checkVectorTypesForPromotion(), CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), cleanupSinglePredPHIs(), llvm::ArrayRecycler< T, Align >::clear(), clearAssumptionsOfUsers(), llvm::CloneAndPruneIntoFromInst(), cloneLoopNest(), codegen(), llvm::OpenMPIRBuilder::OutlineInfo::collectBlocks(), collectCastInstrs(), collectConcatOps(), collectEHScopeMembers(), collectHomogenousInstGraphLoopInvariants(), llvm::LoopVectorizationCostModel::collectInLoopReductions(), llvm::DDGNode::collectInstructions(), collectLeaves(), llvm::InnerLoopVectorizer::collectPoisonGeneratingRecipes(), collectSRATypes(), collectTransitivePredecessors(), collectUnswitchCandidates(), llvm::colorEHFunclets(), combineBinOp_VLToVWBinOp_VL(), combineHorizOpWithShuffle(), combineOrCmpEqZeroToCtlzSrl(), combineRedundantDWordShuffle(), combineToHorizontalAddSub(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::FunctionComparator::compare(), computeBlocksDominatingExits(), llvm::computeDeadSymbolsAndUpdateIndirectCalls(), computeFunctionSummary(), ModuleImportsManager::computeImportForModule(), ComputeLiveInBlocks(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::computeMinimumValueSizes(), ComputePostOrders(), computeUnlikelySuccessors(), llvm::SMSchedule::computeUnpipelineableNodes(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType(), llvm::ConstantExprKeyType::ConstantExprKeyType(), llvm::ConstantFoldGetElementPtr(), ConstHasGlobalValuePredicate(), llvm::LiveIntervalCalc::constructMainRangeFromSubranges(), llvm::MachO::convertToInterfaceFile(), convertToParamAS(), llvm::convertUTF8ToUTF16String(), llvm::orc::shared::WrapperFunctionCall::Create(), llvm::AllocationOrder::create(), llvm::SwiftErrorValueTracking::createEntriesInEntryBlock(), llvm::AbstractDependenceGraphBuilder< GraphType >::createMemoryDependencyEdges(), llvm::MDBuilder::createPCSections(), llvm::OpenMPIRBuilder::createTargetData(), createTblForTrunc(), defaultComponentBroadcast(), llvm::at::deleteAssignmentMarkers(), deleteDeadBlocksFromLoop(), llvm::delinearize(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::HexagonFrameLowering::determineCalleeSaves(), determinePointerAccessAttrs(), llvm::slpvectorizer::BoUpSLP::doesRootHaveInTreeUses(), doPromotion(), DPValuesRemoveRedundantDbgInstrsUsingBackwardScan(), DPValuesRemoveRedundantDbgInstrsUsingForwardScan(), DPValuesRemoveUndefDbgAssignsFromEntryBlock(), dropIntrinsicWithUnknownMetadataArgument(), llvm::ScheduleDAGSDNodes::dumpNode(), llvm::JumpThreadingPass::duplicateCondBranchOnPHIIntoPred(), llvm::SMSchedule::earliestCycleInChain(), llvm::ehAwareSplitEdge(), llvm::LiveRangeEdit::eliminateDeadDefs(), eliminateDeadSwitchCases(), eliminateSwiftError(), llvm::embedBitcodeInModule(), llvm::CSKYConstantPool::emitAll(), llvm::EmitAnyX86InstComments(), llvm::SIFrameLowering::emitCSRSpillRestores(), llvm::SIFrameLowering::emitCSRSpillStores(), llvm::ConstantPool::emitEntries(), llvm::PPCFrameLowering::emitEpilogue(), emitExternalFile(), llvm::CodeViewContext::emitFileChecksums(), EmitGenDwarfInfo(), emitInvalidCostRemarks(), LiveDebugValues::MLocTracker::emitLoc(), llvm::WebAssemblyTargetWasmStreamer::emitLocal(), llvm::OpenMPIRBuilder::emitOffloadingArrays(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), llvm::PPCFrameLowering::emitPrologue(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::dwarf_linker::classic::DwarfStreamer::emitStringOffsets(), emitTargetCall(), llvm::AsmPrinter::emitXXStructorList(), llvm::ConstantPool::empty(), llvm::CSKYConstantPool::empty(), llvm::ModifiedPostOrder< ContextT >::empty(), llvm::LiveRange::empty(), llvm::SDDbgInfo::empty(), llvm::orc::AllocGroupSmallMap< T >::empty(), llvm::MDAttachments::empty(), llvm::gsym::FunctionInfo::encode(), llvm::TimeTraceProfiler::end(), llvm::WebAssemblyAsmTypeCheck::endOfFunction(), llvm::codeview::CodeViewRecordIO::endRecord(), llvm::SelectionDAGISel::EnforceNodeIdInvariant(), eraseDeadBBsAndChildren(), llvm::GIMatchTableExecutor::executeMatchTable(), llvm::LoopVectorizationPlanner::executePlan(), ExpandBasePaths(), llvm::SCEVExpander::expandUnionPredicate(), explicifyGuards(), ExtendUsesToFormExtLoad(), llvm::DIBuilder::finalize(), llvm::DebugLocEntry::finalize(), llvm::PPCInstrInfo::finalizeInsInstrs(), llvm::findAllocaForValue(), llvm::CodeExtractor::findAllocas(), findArgParts(), llvm::findArrayDimensions(), llvm::MustBeExecutedContextExplorer::findBackwardJoinPoint(), findBasePointer(), llvm::RegBankSelect::findBestMapping(), llvm::rdf::FuncNode::findBlock(), findBuildAggregate(), findDependencies(), llvm::findDevirtualizableCallsForTypeTest(), llvm::DGNode< NodeType, EdgeType >::findEdgesTo(), llvm::MustBeExecutedContextExplorer::findForwardJoinPoint(), llvm::FindFunctionBackedges(), llvm::DirectedGraph< NodeType, EdgeType >::findIncomingEdgesToNode(), findNextInsertLocation(), llvm::DWARFDie::findRecursively(), findRefEdges(), llvm::MCELFStreamer::finishImpl(), llvm::InnerLoopVectorizer::fixFixedOrderRecurrence(), FixIrreducibleImpl(), llvm::MCSection::flushPendingLabels(), llvm::LiveRange::flushSegmentSet(), llvm::FoldBranchToCommonDest(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), foldGEPChainAsStructAccess(), foldGEPChainAsU8Access(), foldICmpOrXorSubChain(), foldInlineAsmMemOperand(), forEachUser(), llvm::ScalarEvolution::forgetBlockAndLoopDispositions(), llvm::ScalarEvolution::forgetLoop(), llvm::formDedicatedExitBlocks(), llvm::formLCSSA(), llvm::formLCSSAForInstructions(), forwardStoredOnceStore(), functionWillReturn(), llvm::RuntimePointerChecking::generateChecks(), llvm::RISCVMatInt::generateInstSeq(), generateInstSeqLeadingZeros(), generateReproducer(), llvm::ScalarEvolution::getAddExpr(), llvm::Attributor::getAssumedConstant(), llvm::Attributor::getAssumedSimplified(), llvm::Attributor::getAssumedSimplifiedValues(), getBaseType(), getCastsForInductionPHI(), llvm::MCStreamer::getCurrentSection(), llvm::DependenceGraphInfo< NodeType >::getDependencies(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getDescendants(), ThreadUnsafeDWARFContextState::getDWOContext(), ThreadUnsafeDWARFContextState::getDWOUnits(), llvm::getEHScopeMembership(), getEmscriptenInvokeSymbolName(), llvm::safestack::StackLayout::getFrameSize(), getFunctionNameAndStartLineForAddress(), llvm::ReachingDefAnalysis::getGlobalUses(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), llvm::getIndexExpressionsFromGEP(), llvm::DWARFUnit::getInlinedChainForAddress(), llvm::LoopBase< BlockT, LoopT >::getInnerLoopsInPreorder(), llvm::AArch64TTIImpl::getIntrinsicInstrCost(), getInvariantGroupClobberingInstruction(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), llvm::ConstraintSystem::getLastConstraint(), llvm::getLibcallSignature(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInReverseSiblingPreorder(), getMaskForArgs(), llvm::AArch64TTIImpl::getMemoryOpCost(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::BasicAAResult::getModRefInfoMask(), llvm::ScalarEvolution::getMulExpr(), llvm::GCOVFunction::getName(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), ThreadUnsafeDWARFContextState::getNormalUnits(), llvm::LoopNest::getPerfectLoops(), llvm::MCStreamer::getPreviousSection(), llvm::slpvectorizer::BoUpSLP::getReorderingData(), llvm::slpvectorizer::BoUpSLP::getRootNodeScalars(), getSameOpcode(), llvm::ScalarEvolution::getSequentialMinMaxExpr(), getTargetConstantBitsFromNode(), getTargetShuffleMask(), llvm::logicalview::LVScope::getTemplateParameterTypes(), llvm::Intrinsic::getType(), llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost(), llvm::ScalarEvolution::getUMinFromMismatchedTypes(), llvm::getUnderlyingObjects(), llvm::getUnderlyingObjectsForCodeGen(), getUnwindDestToken(), getUnwindDestTokenHelper(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::slpvectorizer::BoUpSLP::getVectorElementSize(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), llvm::SelectionDAGBuilder::handleDebugValue(), HandleMergeInputChains(), hasAllNBitUsers(), llvm::LiveRange::hasAtLeastOneValue(), hasCallsInBlocksBetween(), hasHardUserWithinLoop(), llvm::hasPartialIVCondition(), llvm::SDNode::hasPredecessorHelper(), hoistFPAssociation(), llvm::DebugHandlerBase::identifyScopeMarkers(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::VPBlockUtils::insertBlockAfter(), llvm::MemorySSAUpdater::insertDef(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), insertPHI(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), insertSpills(), llvm::VPBlockUtils::insertTwoBlocksAfter(), llvm::MachineTraceMetrics::Ensemble::invalidate(), isAllocSiteRemovable(), llvm::LazyCallGraph::RefSCC::isAncestorOf(), llvm::LazyCallGraph::SCC::isAncestorOf(), isBlockValidForExtraction(), llvm::AbstractCallSite::isCallbackCall(), llvm::AbstractCallSite::isCallee(), llvm::SITargetLowering::isEligibleForTailCallOptimization(), llvm::InstructionWorklist::isEmpty(), isEphemeralValueOf(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), llvm::SCEVExpander::isHighCostExpansion(), isHorizontalBinOp(), isKnownNonNullFromDominatingCondition(), isLoadCombineCandidate(), isLoopDead(), isNonEscapingGlobalNoAliasWithLoad(), isNotInCycle(), isObjectSizeLessThanOrEq(), isOnlyCopiedFromConstantMemory(), isPotentiallyReachable(), llvm::isPotentiallyReachable(), llvm::isPotentiallyReachableFromMany(), isPTruePromoted(), isReachableAmongDominated(), llvm::isSafeToDestroyConstant(), isSafeToMove(), isSaveReachableThroughClean(), isSignExtendedW(), IsStoredObjCPointer(), isSuccOrder(), llvm::object::WasmSectionOrderChecker::isValidSectionOrder(), IsValueFullyAvailableInBlock(), isVectorPromotionViable(), llvm::SMSchedule::latestCycleInChain(), llvm::Legalizer::legalizeMachineFunction(), llvm::MCAsmLexer::Lex(), LinearizeExprTree(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::link(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::AArch64CallLowering::lowerCall(), llvm::X86CallLowering::lowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), lowerConstant(), lowerConstantIntrinsics(), llvm::LowerDbgDeclare(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::X86CallLowering::lowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), lowerGuardIntrinsic(), llvm::PhiLoweringHelper::lowerPhis(), llvm::SITargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), lowerWidenableCondition(), llvm::IRAttribute< AK, BaseType, AAType >::manifest(), markAliveBlocks(), markAllReachable(), llvm::dwarf_linker::parallel::DependencyTracker::markCollectedLiveRootsAsKept(), markTails(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), llvm::Pattern::match(), llvm::GlobPattern::match(), matchFunnelShift(), matchIndexAsShuffle(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), memoryIsNotModifiedBetween(), llvm::AAPointerInfo::RangeList::merge(), llvm::Instruction::mergeDIAssignID(), mergeEltWithShuffle(), llvm::object::ExportEntry::moveNext(), llvm::RISCVInstrInfo::movImm(), llvm::mustExecuteUBIfPoisonOnPathTo(), llvm::EscapeEnumerator::Next(), llvm::nonStrictlyPostDominate(), GlobalsImporter::onImportingSummary(), llvm::orc::SequenceBBQuery::operator()(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator*(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++(), llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator++(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::X86InstrInfo::optimizeLoadInstr(), optimizeLoopExitWithUnknownExitCount(), llvm::AArch64FrameLowering::orderFrameObjects(), llvm::X86FrameLowering::orderFrameObjects(), llvm::MachO::PackedVersion::parse32(), llvm::MachO::PackedVersion::parse64(), parseCondition(), parseScalarValue(), llvm::ELFAttributeParser::parseSubsection(), llvm::performOptimizedStructLayout(), llvm::PointerMayBeCaptured(), llvm::GraphDiff< NodePtr, InverseGraph >::popUpdateForIncrementalUpdates(), llvm::SwiftErrorValueTracking::preassignVRegs(), PrepareTailCall(), llvm::DIExpression::prependOpcodes(), llvm::GCOVBlock::print(), llvm::WebAssemblyInstPrinter::printInst(), llvm::printLoop(), printSyncScope(), llvm::AlignmentFromAssumptionsPass::processAssumption(), llvm::JumpThreadingPass::processBranchOnXOR(), processCallSite(), llvm::logicalview::LVBinaryReader::processLines(), llvm::processShuffleMasks(), llvm::JumpThreadingPass::processThreadableEdges(), promoteArguments(), llvm::promoteLoopAccessesToScalars(), llvm::GCOVFunction::propagateCounts(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::AAPointerInfo::RangeList::push_back(), llvm::BitstreamCursor::ReadBlockEnd(), rebuildLoopAfterUnswitch(), llvm::LiveVariables::recomputeForSingleDefVirtReg(), recomputeLoopBlockSet(), ReconstructShuffleWithRuntimeMask(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), TransferTracker::redefVar(), reduceDbgValsBackwardScan(), reduceDbgValsForwardScan(), ReduceLoopStrength(), llvm::DotCfgChangeReporter::registerCallbacks(), llvm::Attributor::registerFunctionSignatureRewrite(), relocationViaAlloca(), llvm::MCContext::RemapDebugPaths(), rematerializeLiveValuesAtUses(), llvm::sys::path::remove_dots(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::PMDataManager::removeDeadPasses(), removeFromUsedList(), removeGEPBuiltinsInFunc(), llvm::MemoryDependenceResults::removeInstruction(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::InstructionWorklist::removeOne(), removePAICalls(), removeRedundantDbgInstrsUsingBackwardScan(), removeRedundantDbgInstrsUsingForwardScan(), removeUndefDbgAssignsFromEntryBlock(), llvm::slpvectorizer::BoUpSLP::reorderBottomToTop(), reorderOrder(), llvm::slpvectorizer::BoUpSLP::reorderTopToBottom(), replaceConstantExprOp(), llvm::coro::replaceCoroFree(), llvm::replaceDbgUsesWithUndef(), replaceLoopPHINodesWithPreheaderValues(), llvm::IntervalMapImpl::Path::replaceRoot(), llvm::Value::replaceUsesWithIf(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Reset(), rewriteDebugUsers(), rewriteNonInstructionUses(), rewritePHIs(), llvm::GenericCycleInfoCompute< ContextT >::run(), llvm::TruncInstCombine::run(), llvm::KCFIPass::run(), llvm::LoopSinkPass::run(), llvm::CallBrPreparePass::run(), llvm::CoroSplitPass::run(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), runImpl(), llvm::LoopVectorizePass::runImpl(), llvm::SLPVectorizerPass::runImpl(), llvm::ConstantHoistingPass::runImpl(), runMoveAutoInit(), llvm::RewriteStatepointsForGC::runOnFunction(), llvm::SlotIndexes::runOnMachineFunction(), llvm::SPIRVModuleAnalysis::runOnModule(), salvageDbgAssignAddress(), llvm::salvageDebugInfo(), llvm::salvageDebugInfoForDbgValues(), salvageDebugInfoImpl(), llvm::SelectionDAGBuilder::salvageUnresolvedDbgValue(), llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::save(), llvm::SpillPlacement::scanActiveBundles(), searchPredecessors(), llvm::SelectionDAGISel::SelectCodeCommon(), selectConstantAddr(), selectImm(), llvm::EngineBuilder::selectTarget(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::SUnit::setDepthDirty(), llvm::VPRegionBlock::setEntry(), llvm::VPRegionBlock::setExiting(), llvm::MCContext::setGenDwarfRootFile(), llvm::SUnit::setHeightDirty(), llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot(), llvm::VPBlockBase::setOneSuccessor(), llvm::VPBlockBase::setPredecessors(), setRequiredFeatureString(), llvm::dwarf_linker::parallel::SectionDescriptor::setSizesForSectionCreatedByAsmPrinter(), llvm::VPBlockBase::setTwoSuccessors(), llvm::SITargetLowering::shouldExpandAtomicRMWInIR(), llvm::AArch64TargetLowering::shouldSinkOperands(), llvm::AMDGPUTargetLowering::shouldSinkOperands(), llvm::X86TargetLowering::shouldSinkOperands(), shouldTransformMulToShiftsAddsSubs(), simplifyCommonValuePhi(), llvm::simplifyLoop(), llvm::simplifyLoopAfterUnroll(), simplifyLoopInst(), sinkSpillUsesAfterCoroBegin(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), SoleWriteToDeadLocal(), sortLocalVars(), llvm::DominatorTreeBase< NodeT, IsPostDom >::Split(), splitAsyncCoroutine(), llvm::SplitIndirectBrCriticalEdges(), llvm::SplitKnownCriticalEdge(), SplitLandingPadPredecessorsImpl(), splitRetconCoroutine(), splitSwitchCoroutine(), SRAGlobal(), llvm::DbgValueHistoryMap::startDbgValue(), stripDeadDebugInfoImpl(), stripGCRelocates(), llvm::MCStreamer::subSection(), substituteSimpleCopyRegs(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::cl::TokenizeGNUCommandLine(), tokenizeWindowsCommandLineImpl(), llvm::detail::IEEEFloat::toString(), llvm::objcopy::macho::MachOWriter::totalSize(), llvm::LoopTraversal::traverse(), tryBuildVectorShuffle(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), llvm::VFABI::tryDemangleForVFABI(), llvm::mca::RegisterFile::tryEliminateMoveOrSwap(), tryToVectorizeSequence(), llvm::UnrollRuntimeLoopRemainder(), unswitchBestCondition(), unswitchLoop(), unswitchTrivialSwitch(), updateCallGraphAfterCoroutineSplit(), llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers(), llvm::SelectionDAG::updateDivergence(), updateLiveness(), llvm::JumpThreadingPass::updateSSA(), usersDominator(), llvm::IntervalMapImpl::Path::valid(), llvm::GenericCycleInfo< ContextT >::validateTree(), valueIsOnlyUsedLocallyOrStoredToOneGlobal(), llvm::PHITransAddr::verify(), llvm::ScalarEvolution::verify(), verifyCTRBranch(), llvm::dwarf_linker::parallel::DependencyTracker::verifyKeepChain(), llvm::SCEVTraversal< SV >::visitAll(), llvm::SelectionDAGBuilder::visitDbgInfo(), visitDomSubTree(), llvm::InstCombinerImpl::visitGEPOfGEP(), llvm::InstCombinerImpl::visitLandingPadInst(), visitPointers(), llvm::LazyCallGraph::visitReferences(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::VPRegionBlock::VPRegionBlock(), llvm::objcopy::elf::BinaryWriter::write(), llvm::TimeTraceProfiler::write(), llvm::writeArchiveToStream(), llvm::WriteBitcodeToFile(), llvm::dxil::WriteDXILToFile(), llvm::ArrayRecycler< T, Align >::~ArrayRecycler(), llvm::PrintIRInstrumentation::~PrintIRInstrumentation(), llvm::SCEVExpander::~SCEVExpander(), llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::~ShuffleCostEstimator(), and llvm::slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::~ShuffleInstructionBuilder().
grow_pod()
template<class Size_T > void SmallVectorBase::grow_pod (void * FirstEl, size_t MinSize, size_t TSize) protected
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
This function will report a fatal error if it cannot increase capacity.
Definition at line 138 of file SmallVector.cpp.
References llvm::safe_malloc(), llvm::safe_realloc(), and llvm::size().
mallocForGrow()
template<class Size_T > void * SmallVectorBase::mallocForGrow (void * FirstEl, size_t MinSize, size_t TSize, size_t & NewCapacity) protected
This is a helper for grow() that's out of line to reduce code duplication.
This function will report a fatal error if it can't grow at least to MinSize.
Definition at line 124 of file SmallVector.cpp.
References llvm::safe_malloc().
replaceAllocation()
template<class Size_T > void * SmallVectorBase::replaceAllocation (void * NewElts, size_t TSize, size_t NewCapacity, size_t VSize = 0) protected
If vector was first created with capacity 0, getFirstEl() points to the memory right after, an area unallocated.
If a subsequent allocation, that grows the vector, happens to return the same pointer as getFirstEl(), get a new allocation, otherwise isSmall() will falsely return that no allocation was done (true) and the memory will not be freed in the destructor. If a VSize is given (vector size), also copy that many elements to the new allocation - used if realloca fails to increase space, and happens to allocate precisely at BeginX. This is unlikely to be called often, but resolves a memory leak when the situation does occur.
Definition at line 112 of file SmallVector.cpp.
References llvm::safe_malloc().
set_allocation_range()
template<class Size_T > void llvm::SmallVectorBase< Size_T >::set_allocation_range (void * Begin, size_t N) inline protected
Set the array data pointer to Begin and capacity to N.
This does not construct or destroy any elements in the vector.
Definition at line 110 of file SmallVector.h.
References assert(), llvm::SmallVectorBase< Size_T >::BeginX, llvm::SmallVectorBase< Size_T >::Capacity, N, and llvm::SmallVectorBase< Size_T >::SizeTypeMax().
set_size()
template<class Size_T > void llvm::SmallVectorBase< Size_T >::set_size (size_t N) inline protected
Set the array size to N, which the current array must have enough capacity for.
This does not construct or destroy any elements in the vector.
Definition at line 101 of file SmallVector.h.
References assert(), llvm::SmallVectorBase< Size_T >::capacity(), N, and llvm::SmallVectorBase< Size_T >::Size.
size()
template<class Size_T > size_t llvm::SmallVectorBase< Size_T >::size () const inline
Definition at line 91 of file SmallVector.h.
References llvm::SmallVectorBase< Size_T >::Size.
Referenced by llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::add(), llvm::slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::add(), AddAliasScopeMetadata(), llvm::SSAUpdaterBulk::AddAvailableValue(), llvm::SelectionDAGBuilder::addDanglingDebugInfo(), addData(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addDIETypeName(), addEdge(), llvm::CodeViewContext::addFile(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::logicalview::LVScope::addMissingElements(), llvm::bfi_detail::IrreducibleGraph::addNodesInLoop(), llvm::AttributeList::addParamAttribute(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addParentName(), llvm::mca::RegisterFile::addRegisterRead(), llvm::FoldingSetNodeID::AddString(), llvm::CodeViewContext::addToStringTable(), llvm::SSAUpdaterBulk::AddUse(), llvm::DebugLocEntry::addValues(), llvm::SSAUpdaterBulk::AddVariable(), adjustCostForPairing(), llvm::AggressiveAntiDepBreaker::AggressiveAntiDepBreaker(), llvm::SITargetLowering::allocatePreloadKernArgSGPRs(), llvm::StatepointLoweringState::allocateStackSlot(), AnalyzeArguments(), llvm::CCState::AnalyzeArgumentsSecondPass(), analyzeCallOperands(), llvm::CCState::AnalyzeCallOperands(), llvm::AIXCCState::AnalyzeCallOperands(), llvm::SystemZCCState::AnalyzeCallOperands(), analyzeCompressibleUses(), analyzeExitPHIsForOutputUses(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), llvm::CCState::AnalyzeReturn(), llvm::opt::ArgList::append(), llvm::sys::path::append(), llvm::ModifiedPostOrder< ContextT >::appendBlock(), appendToGlobalArray(), llvm::BitVector::apply(), llvm::CombinerHelper::applyCombineInsertVecElts(), llvm::CombinerHelper::applyCombineUnmergeConstant(), llvm::ScalarEvolution::applyLoopGuards(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingSMULU64(), llvm::DomTreeUpdater::applyUpdates(), areLoadedOffsetButOtherwiseSame(), ARM64FindSegmentsInFunction(), llvm::IntervalMapImpl::Path::atBegin(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::atBeginning(), llvm::IntervalMapImpl::Path::atLastEntry(), llvm::object::BigArchive::BigArchive(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildCopyFromRegs(), llvm::buildEnqueueKernel(), BuildExactSDIV(), buildFromShuffleMostly(), llvm::VPlanSlp::buildGraph(), llvm::MachineIRBuilder::buildMergeLikeInstr(), llvm::MachineIRBuilder::buildMergeValues(), buildMultiplyTree(), llvm::MachineIRBuilder::buildPadVectorWithUndefElements(), buildRegSequence(), buildRegSequence16(), buildRegSequence32(), llvm::TargetLowering::BuildSDIV(), BuildSubAggregate(), llvm::TargetLowering::BuildUDIV(), llvm::MachineIRBuilder::buildUnmerge(), llvm::gsym::FunctionInfo::cacheEncoding(), llvm::LoopVectorizationCostModel::calculateRegisterUsage(), callBufferedPrintfArgPush(), canLoopBeDeleted(), llvm::LoongArchTargetLowering::CanLowerReturn(), llvm::RISCVTargetLowering::CanLowerReturn(), llvm::X86InstrInfo::canMakeTailCallConditional(), CanMergeParamLoadStoresStartingAt(), canonicalizeBitSelect(), llvm::FileCheck::CanonicalizeFile(), canonicalizeShuffleMaskWithHorizOp(), canProfitablyUnrollMultiExitLoop(), canSplitCallSite(), canUseSiblingCall(), canWidenShuffleElements(), llvm::PagedVector< T, PageSize >::capacity(), CasesAreContiguous(), CC_AArch64_Custom_Block(), CC_ARM_AAPCS_Custom_Aggregate(), CC_LoongArch(), llvm::RISCV::CC_RISCV(), CC_X86_32_MCUInReg(), CC_X86_32_RegCall_Assign2Regs(), chainLoadsAndStoresForMemcpy(), llvm::ShuffleVectorInst::changesLength(), checkDependencies(), llvm::Attributor::checkForAllUses(), checkHVXPipes(), TransferTracker::checkInstForNewValues(), checkOrAndOpImpliedByOther(), llvm::CallLowering::checkReturn(), llvm::CCState::CheckReturn(), llvm::checkStackTop(), llvm::object::MachOObjectFile::checkSymbolTable(), llvm::checkVOPDRegConstraints(), llvm::ArrayRecycler< T, Align >::clear(), clobbersFlagRegisters(), llvm::CloneAndPruneIntoFromInst(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneBlockAttr(), llvm::dwarf_linker::parallel::CompileUnit::cloneDieAttrExpression(), llvm::orc::cloneToNewContext(), clusterSortPtrAccesses(), llvm::collectChildrenInLoop(), llvm::collectGlobalObjectNameStrings(), collectMultiplyFactors(), llvm::mca::RegisterFile::collectWrites(), combineAnd(), CombineBaseUpdate(), combineBinOp_VLToVWBinOp_VL(), combineBitcastvxi1(), combineCONCAT_VECTORS(), combineConcatVectorOps(), combineExtractVectorElt(), combineINSERT_SUBVECTOR(), combineOr(), combineSetCCMOVMSK(), combineShuffleToZeroExtendVectorInReg(), combineTargetShuffle(), combineToConsecutiveLoads(), combineVectorShiftImm(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::ShuffleVectorInst::commute(), llvm::DominatorTreeBase< NodeT, IsPostDom >::compare(), llvm::IRSimilarity::IRSimilarityCandidate::compareStructure(), completeEphemeralValues(), llvm::IntEqClasses::compress(), llvm::objcopy::elf::CompressedSection::CompressedSection(), llvm::EHStreamer::computeActionsTable(), llvm::ComputeASanStackFrameDescription(), llvm::ComputeASanStackFrameLayout(), llvm::EHStreamer::computeCallSiteTable(), llvm::WasmException::computeCallSiteTable(), computeHeadersSize(), llvm::X86TargetLowering::computeKnownBitsForTargetNode(), llvm::safestack::StackLayout::computeLayout(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::EHStreamer::computePadMap(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), ComputePTXValueVTs(), llvm::concatenateVectors(), llvm::ConstantFoldTerminator(), ConstructSSAForLoadSet(), llvm::LiveRange::containsOneValue(), convertImageAddrToPacked(), llvm::convertUTF8ToUTF16String(), llvm::orc::shared::WrapperFunctionCall::Create(), llvm::AllocationOrder::create(), llvm::createCFAOffset(), createDefCFAExpression(), llvm::dxil::createEntryMD(), llvm::object::ELFFile< ELFT >::createFakeSections(), createMMXBuildVector(), llvm::OpenMPIRBuilder::createOffloadMapnames(), llvm::MDBuilder::createPCSections(), llvm::OpenMPIRBuilder::createTask(), createTblForTrunc(), llvm::sys::fs::createUniquePath(), llvm::LiveRange::createValueCopy(), llvm::mca::ExecuteStage::cycleEnd(), llvm::DbgValueLoc::DbgValueLoc(), LiveDebugValues::VLocTracker::defVar(), llvm::DeleteDeadPHIs(), llvm::DependenceInfo::depends(), DoLowering(), doPromotion(), llvm::MCFragment::dump(), dumpBytes(), llvm::JumpThreadingPass::duplicateCondBranchOnPHIIntoPred(), llvm::embedBitcodeInModule(), EmitAddTreeOfValues(), llvm::EmitAnyX86InstComments(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::AsmPrinter::emitConstantPool(), emitDarwinBCHeaderAndTrailer(), llvm::InstrEmitter::EmitDbgInstrRef(), llvm::emitDWARF5AccelTable(), llvm::PPCFrameLowering::emitEpilogue(), llvm::EHStreamer::emitExceptionTable(), emitExternalFile(), llvm::CodeViewContext::emitFileChecksumOffset(), EmitGenDwarfInfo(), llvm::AMDGPUAsmPrinter::emitInstruction(), LiveDebugValues::MLocTracker::emitLoc(), llvm::WebAssemblyTargetWasmStreamer::emitLocal(), llvm::OpenMPIRBuilder::emitNonContiguousDescriptor(), llvm::OpenMPIRBuilder::emitOffloadingArrays(), llvm::PPCFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::MCStreamer::emitSLEB128IntValue(), emitTargetCall(), llvm::WebAssemblyAsmPrinter::EmitTargetFeatures(), llvm::MCStreamer::emitULEB128IntValue(), llvm::gsym::FunctionInfo::encode(), llvm::CodeViewContext::encodeDefRange(), llvm::CodeViewContext::encodeInlineLineTable(), llvm::COFF::encodeSectionName(), llvm::codeview::ContinuationRecordBuilder::end(), llvm::WebAssemblyAsmTypeCheck::endOfFunction(), llvm::logicalview::LVLine::equals(), llvm::logicalview::LVScope::equals(), llvm::logicalview::LVSymbol::equals(), llvm::logicalview::LVType::equals(), llvm::Evaluator::EvaluateFunction(), llvm::GIMatchTableExecutor::executeMatchTable(), ExpandBVWithShuffles(), llvm::ARMTargetLowering::ExpandInlineAsm(), llvm::X86TargetLowering::ExpandInlineAsm(), llvm::cl::ExpansionContext::expandResponseFiles(), llvm::extractBranchWeights(), extractInstructionFeatures(), llvm::extractParts(), llvm::LegalizerHelper::fewerElementsVectorReductions(), llvm::GISelWorkList< N >::finalize(), llvm::DebugLocEntry::finalize(), llvm::UnwindOpcodeAssembler::Finalize(), llvm::finalizeBundle(), llvm::CodeExtractor::findAllocas(), llvm::findArrayDimensions(), findArrayDimensionsRec(), llvm::DWARFAbbreviationDeclaration::findAttributeIndex(), llvm::MustBeExecutedContextExplorer::findBackwardJoinPoint(), findBestInsertionSet(), findBuildAggregate(), findForkedPointer(), findForkedSCEVs(), llvm::MustBeExecutedContextExplorer::findForwardJoinPoint(), llvm::sampleprof::FunctionSamples::findFunctionSamples(), FindInOperandList(), llvm::FindInsertedValue(), findOrCreatePHIInBlock(), findRematerializationCandidates(), llvm::MachineInstr::findTiedOperandIdx(), llvm::SplitEditor::finish(), fixupOrderingIndices(), fixupShuffleMaskForPermutedSToV(), fixupVariableFloatArgs(), TransferTracker::flushDbgValues(), llvm::remarks::BitstreamRemarkSerializerHelper::flushToStream(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), llvm::InstCombinerImpl::foldBinopWithPhiOperands(), llvm::FoldBranchToCommonDest(), llvm::SelectionDAG::FoldConstantArithmetic(), foldExtractSubvectorFromShuffleVector(), foldInlineAsmMemOperand(), llvm::InstCombinerImpl::foldIntegerTypedPHI(), llvm::InstCombinerImpl::foldPHIArgGEPIntoPHI(), foldSelectShuffleOfSelectShuffle(), FoldTwoEntryPHINode(), llvm::memtag::forAllReachableExits(), llvm::InformationCache::foreachUse(), llvm::FmtAlign::format(), llvm::formLCSSAForInstructions(), ForwardSwitchConditionToPHI(), llvm::jitlink::EHFrameCFIBlockInspector::FromEdgeScan(), llvm::RISCVMatInt::generateInstSeq(), generateInstSeqLeadingZeros(), llvm::RecordRecTy::get(), llvm::ScalarEvolution::getAddExpr(), llvm::Attributor::getAssumedSimplifiedValues(), llvm::DWARFAbbreviationDeclaration::getAttrByIndex(), llvm::DWARFAbbreviationDeclaration::getAttributeValueFromOffset(), llvm::DWARFAbbreviationDeclaration::getAttrImplicitConstValueByIndex(), llvm::DWARFAbbreviationDeclaration::getAttrIsImplicitConstByIndex(), llvm::omp::getBestVariantMatchForContext(), GetBranchWeights(), llvm::remarks::BitstreamRemarkSerializerHelper::getBuffer(), llvm::symbolize::getBuildIDStr(), llvm::AbstractCallSite::getCallArgOperandNoForCallee(), llvm::SCEVUnionPredicate::getComplexity(), llvm::dwarf_linker::parallel::SectionDescriptor::getContents(), llvm::RegsForValue::getCopyToRegs(), getDXILOpFunctionType(), getEmscriptenInvokeSymbolName(), llvm::GenericCycle< ContextT >::getExitBlocks(), getFauxShuffleMask(), llvm::DWARFAbbreviationDeclaration::getFormByIndex(), llvm::DIInliningInfo::getFrame(), llvm::NVPTXMachineFunctionInfo::getImageHandleSymbol(), llvm::NVPTXMachineFunctionInfo::getImageHandleSymbolIndex(), llvm::MCDecodedPseudoProbe::getInlineContext(), llvm::DWARFContext::getInliningInfoForAddress(), llvm::logicalview::getInnerComponent(), llvm::CCState::getInRegsParamInfo(), llvm::CCState::getInRegsParamsCount(), getInstSeqCost(), getIntOperandFromRegisterString(), getIntOperandsFromRegisterString(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::RegisterClassInfo::getLastCalleeSavedAlias(), llvm::object::MachOObjectFile::getLibraryCount(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), llvm::WebAssemblyFrameLowering::getLocalForStackObject(), llvm::ExpressionFormat::getMatchingString(), llvm::WebAssemblyAsmPrinter::getMCSymbolForFunction(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), llvm::TargetInstrInfo::getMemOperandWithOffset(), getMinAnalyzeableBackedgeTakenCount(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::MDNode::getMostGenericRange(), llvm::ScalarEvolution::getMulExpr(), llvm::DIInliningInfo::getMutableFrame(), llvm::LiveRange::getNextValue(), getNoopInput(), llvm::AbstractCallSite::getNumArgOperands(), llvm::DWARFAbbreviationDeclaration::getNumAttributes(), llvm::RuntimePointerChecking::getNumberOfChecks(), llvm::DIInliningInfo::getNumberOfFrames(), llvm::ExtractValueInst::getNumIndices(), llvm::InsertValueInst::getNumIndices(), llvm::RegBankSelect::RepairingPlacement::getNumInsertPoints(), llvm::GraphDiff< NodePtr, InverseGraph >::getNumLegalizedUpdates(), llvm::DebugLocStream::getNumLists(), llvm::BitCodeAbbrev::getNumOperandInfos(), llvm::VPBlockBase::getNumPredecessors(), llvm::mca::RegisterFile::getNumRegisterFiles(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::GetNumSlabs(), llvm::mca::MemoryGroup::getNumSuccessors(), llvm::VPBlockBase::getNumSuccessors(), llvm::coverage::MCDCRecord::getNumTestVectors(), llvm::LiveRange::getNumValNums(), llvm::opt::Arg::getNumValues(), getOpEnabled(), getOpRefinementSteps(), getOrCreateFrameHelper(), getOutputSegmentMap(), llvm::HvxSelector::getPerfectCompletions(), llvm::MachineTraceMetrics::Trace::getPHIDepth(), getPreStartForExtend(), llvm::MachineTraceMetrics::getProcReleaseAtCycles(), llvm::NVPTXTargetLowering::getPrototype(), llvm::ReachingDefAnalysis::getReachingDef(), llvm::FileCollectorFileSystem::getRealPath(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::GetReturnInfo(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::getRoot(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getRoot(), getSameOpcode(), llvm::object::MachOObjectFile::getSection(), llvm::ScalarEvolution::getSequentialMinMaxExpr(), llvm::GetShadowBytes(), getShuffleComment(), getShuffleInput(), llvm::VPBlockBase::getSinglePredecessor(), llvm::VPBlockBase::getSingleSuccessor(), llvm::DependenceInfo::getSplitIteration(), llvm::DWARFExpression::Operation::getSubCode(), llvm::object::MachOObjectFile::getSymbolSection(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTokenFactor(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::slpvectorizer::BoUpSLP::getTreeSize(), getTwoPredecessors(), llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost(), llvm::ScalarEvolution::getUMinFromMismatchedTypes(), getUnmergeResults(), llvm::ARMTTIImpl::getUnrollingPreferences(), llvm::RISCVTTIImpl::getUnrollingPreferences(), llvm::SSAUpdaterImpl< UpdaterT >::GetValue(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), getVariantMatchScore(), GroupByComplexity(), llvm::IndexedMap< T, ToIndexT >::grow(), llvm::IntEqClasses::grow(), llvm::CallLowering::handleAssignments(), HandleMergeInputChains(), llvm::orc::SimpleRemoteEPC::handleMessage(), llvm::orc::SimpleRemoteEPCServer::handleMessage(), llvm::TargetInstrInfo::hasLoadFromStackSlot(), llvm::DomTreeUpdater::hasPendingDomTreeUpdates(), llvm::DomTreeUpdater::hasPendingPostDomTreeUpdates(), llvm::TargetInstrInfo::hasStoreToStackSlot(), llvm::mca::MicroOpQueueStage::hasWorkToComplete(), llvm::IntervalMapImpl::Path::height(), llvm::HexagonMCShuffle(), hoistFPAssociation(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::identifyObject(), llvm::IndexedMap< T, ToIndexT >::inBounds(), llvm::logicalview::LVBinaryReader::includeInlineeLines(), llvm::ValueEnumerator::incorporateFunction(), llvm::ShuffleVectorInst::increasesLength(), llvm::FunctionVarLocs::init(), INITIALIZE_PASS(), initializeUniqueCases(), llvm::mca::initializeUsedResources(), llvm::InitLLVM::InitLLVM(), llvm::InlineFunction(), llvm::GISelWorkList< N >::insert(), llvm::insertDebugValuesForPHIs(), insertDPValuesForPHIs(), llvm::LiveIntervals::insertMBBInMaps(), llvm::SlotIndexes::insertMBBInMaps(), insertParsePoints(), llvm::CallLowering::insertSRetIncomingArgument(), llvm::CallLowering::insertSRetLoads(), llvm::CallLowering::insertSRetStores(), llvm::LazyCallGraph::RefSCC::insertTrivialCallEdge(), llvm::LazyCallGraph::RefSCC::insertTrivialRefEdge(), insertValues(), instCombineSVEDupqLane(), llvm::LiveIntervalUnion::Query::interferingVRegs(), llvm::FoldingSetNodeID::Intern(), llvm::intersectAccessGroups(), isCheapImmediate(), llvm::X86::isConstantSplat(), llvm::DbgValueLoc::isEquivalent(), isFNEG(), isHorizontalBinOp(), llvm::ShuffleVectorInst::isIdentity(), llvm::ARMBaseInstrInfo::isLoadFromStackSlotPostFE(), isPointerValueDeadOnEntryToFunction(), isPotentiallyReachable(), llvm::ShuffleVectorInst::isReplicationMask(), llvm::ShuffleVectorInst::isReverse(), llvm::SIInstrInfo::isSafeToSink(), llvm::ShuffleVectorInst::isSelect(), llvm::ShuffleVectorInst::isSingleSource(), isSlicingProfitable(), llvm::ShuffleVectorInst::isSplice(), llvm::memtag::isStandardLifetime(), llvm::ARMBaseInstrInfo::isStoreToStackSlotPostFE(), llvm::ShuffleVectorInst::isTranspose(), llvm::GlobPattern::isTrivialMatchAll(), llvm::AAPointerInfo::RangeList::isUnassigned(), llvm::AAPointerInfo::RangeList::isUnique(), llvm::AAPointerInfo::RangeList::isUnknown(), isUpperSubvectorUndef(), llvm::CodeViewContext::isValidFileNumber(), isVariantApplicableInContextHelper(), isVECTOR_SHUFFLE_SPLATI(), isWideTypeMask(), llvm::ShuffleVectorInst::isZeroEltSplat(), llvm::LiveRange::join(), llvm::AMDGPULegalizerInfo::legalizeBVHIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeImageIntrinsic(), llvm_getMetadata(), LLVMCopyModuleFlagsMetadata(), LLVMDisasmInstruction(), LLVMGetDebugLocDirectory(), LLVMGetDebugLocFilename(), LLVMGetDebugLocLine(), LLVMGetRelocationTypeName(), LLVMOrcExecutionSessionLookup(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::PPCInstrInfo::loadRegFromStackSlotNoUpd(), llvm::object::ELFFile< ELFT >::loadVersionMap(), llvm::lookupBuiltin(), llvm::BlockFrequencyInfoImplBase::LoopData::LoopData(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SITargetLowering::LowerCallResult(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), LowerCONCAT_VECTORS_i1(), lowerConstant(), llvm::LegalizerHelper::lowerExtract(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::AArch64CallLowering::lowerReturn(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerShift(), lowerShuffleAsBlend(), lowerShufflePairAsUNPCKAndPermute(), lowerShuffleWithUndefHalf(), lowerStatepointMetaArgs(), llvm::LegalizerHelper::lowerTRUNC(), lowerV16F32Shuffle(), lowerV16I32Shuffle(), lowerV16I8Shuffle(), lowerV4X128Shuffle(), lowerV8F32Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerV8I32Shuffle(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), lowerVECTOR_SHUFFLE_SHF(), lowerVECTOR_SHUFFLEAsVSlidedown(), llvm::sys::fs::make_absolute(), llvm::makeFollowupLoopID(), llvm::opt::InputArgList::MakeIndex(), makeStatepointExplicit(), makeStatepointExplicitImpl(), llvm::Pattern::match(), matchBinaryPermuteShuffle(), llvm::CombinerHelper::matchCombineMergeUnmerge(), llvm::Intrinsic::matchIntrinsicSignature(), matchIntrinsicType(), llvm::CombinerHelper::matchNotCmp(), matchPERM(), matchScalarReduction(), matchShuffleAsByteRotate(), MatchVectorAllEqualTest(), llvm::BitTracker::RegisterCell::meet(), llvm::MergeBasicBlockIntoOnlyPred(), mergeConstants(), llvm::DebugLocEntry::MergeRanges(), mergeVectorRegsToResultRegs(), llvm::LegalizerHelper::moreElementsVector(), llvm::RISCVInstrInfo::movImm(), llvm::InjectorIRStrategy::mutate(), llvm::InsertFunctionStrategy::mutate(), llvm::InsertCFGStrategy::mutate(), llvm::SinkInstructionStrategy::mutate(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarAddSub(), llvm::LegalizerHelper::narrowScalarBasic(), llvm::LegalizerHelper::narrowScalarExtract(), llvm::LegalizerHelper::narrowScalarInsert(), llvm::LegalizerHelper::narrowScalarSelect(), llvm::sys::unicode::nearestMatchesForCodepointName(), needsReferenceType(), llvm::EscapeEnumerator::Next(), llvm::CCState::nextInRegsParam(), llvm::Triple::normalize(), llvm::mca::ExecuteStage::notifyReservedOrReleasedBuffers(), llvm::orc::BlockFreqQuery::operator()(), llvm::FoldingSetNodeID::operator<(), llvm::raw_ostream::operator<<(), llvm::object::ExportEntry::operator==(), llvm::FoldingSetNodeID::operator==(), llvm::BitTracker::RegisterCell::operator==(), llvm::IndexedMap< T, ToIndexT >::operator[](), llvm::PagedVector< T, PageSize >::operator[](), OptimizeAndOrXor(), OptimizeAwayTrappingUsesOfValue(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), optimizeLoopExitWithUnknownExitCount(), llvm::SystemZELFFrameLowering::orderFrameObjects(), packSegmentMask(), llvm::CallLowering::parametersInCSRMatch(), llvm::TargetLowering::parametersInCSRMatch(), llvm::MachO::PackedVersion::parse32(), llvm::MachO::PackedVersion::parse64(), llvm::ARM::parseBranchProtection(), llvm::SPIRV::parseBuiltinTypeNameToTargetExtType(), llvm::cl::ParseCommandLineOptions(), parseScalarValue(), llvm::MCSectionMachO::ParseSectionSpecifier(), llvm::R600TargetLowering::PerformDAGCombine(), performExtBinopLoadFold(), llvm::performOptimizedStructLayout(), performOrXorChainCombine(), PerformSplittingToWideningLoad(), placeSplitBlockCarefully(), llvm::MCStreamer::popSection(), llvm::SystemZInstrInfo::prepareCompareSwapOperands(), llvm::prepareTempFiles(), llvm::InstCombinerImpl::prepareWorklist(), llvm::opt::Arg::print(), llvm::safestack::StackLayout::print(), llvm::BasicAAResult::DecomposedGEP::print(), llvm::DWARFExpression::Operation::print(), llvm::WebAssemblyInstPrinter::printInst(), PrintLoopInfo(), PrintOps(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::PrintStats(), llvm::memprof::RawMemProfReader::printYAML(), llvm::JumpThreadingPass::processBranchOnXOR(), processCallSite(), ProcessElementList(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::logicalview::LVBinaryReader::processLines(), processSwitches(), llvm::JumpThreadingPass::processThreadableEdges(), llvm::logicalview::LVScopeCompileUnit::propagatePatternMatch(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::InstructionWorklist::push(), llvm::coverage::RawCoverageMappingReader::read(), llvm::SymbolRemappingReader::read(), llvm::sampleprof::SampleProfileReaderText::readImpl(), llvm::sys::fs::readNativeFileToEOF(), llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile(), llvm::BitstreamCursor::readRecord(), llvm::DomTreeUpdater::recalculate(), llvm::WebAssemblyExceptionInfo::recalculate(), llvm::AArch64TargetLowering::ReconstructShuffle(), llvm::RecursivelyDeleteTriviallyDeadInstructionsPermissive(), redirectValuesFromPredecessorsToPhi(), llvm::LegalizerHelper::reduceLoadStoreWidth(), llvm::RuntimeDyldELF::registerEHFrames(), relocationViaAlloca(), rematerializeLiveValuesAtUses(), llvm::sys::path::remove_dots(), llvm::sys::path::remove_filename(), removeFromUsedList(), removeGlobalCtors(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), removeRedundantBlockingStores(), llvm::Record::removeValue(), llvm::LiveRange::RenumberValues(), reorderOrder(), reorderReuses(), llvm::reorderScalars(), llvm::sys::path::replace_extension(), replaceArgumentUses(), llvm::X86InstrInfo::replaceBranchWithTailCall(), llvm::CallGraphNode::replaceCallEdge(), replaceUndefValuesInPhi(), llvm::PagedVector< T, PageSize >::resize(), llvm::dwarf_linker::classic::CachedPathResolver::resolve(), llvm::RuntimeDyldImpl::resolveRelocationList(), resolveSources(), resolveTargetShuffleInputsAndMask(), RestoreSpillList(), llvm::CallLowering::resultsCompatible(), llvm::LanaiInstrInfo::reverseBranchCondition(), llvm::DominatorTreeBase< NodeT, IsPostDom >::root_size(), llvm::FunctionSpecializer::run(), runImpl(), llvm::LoopVectorizePass::runImpl(), llvm::SLPVectorizerPass::runImpl(), runIPSCCP(), runMoveAutoInit(), llvm::salvageDebugInfoForDbgValues(), SalvageDVI(), scaleShuffleElements(), llvm::object::MachOObjectFile::section_end(), llvm::SelectionDAGISel::SelectCodeCommon(), selectImm(), llvm::EngineBuilder::selectTarget(), selectWMMAModsNegAbs(), llvm::mca::ResourceManager::setCustomStrategy(), llvm::BranchProbabilityInfo::setEdgeProbability(), llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot(), llvm::IntervalMapImpl::Path::setSize(), setupBranchForGuard(), setUsedInitializer(), llvm::RISCVTargetLowering::shouldConvertConstantLoadToIntImm(), shouldTryInjectBasingOnMetadata(), shouldUseFrameHelper(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::simplifyLoop(), llvm::X86TargetLowering::SimplifyMultipleUseDemandedBitsForTargetNode(), simplifyOneLoop(), simplifySelectInst(), simplifySwitchOfPowersOfTwo(), SimplifyValuePattern(), simplifyWithOpReplaced(), SinkCommonCodeFromPredecessors(), sinkInstruction(), sinkLastInstruction(), sinkLifetimeStartMarkers(), sinkRecurrenceUsersAfterPrevious(), sinkScalarOperands(), llvm::AliasSet::size(), llvm::DirectedGraph< NodeType, EdgeType >::size(), llvm::ModifiedPostOrder< ContextT >::size(), llvm::IndexedMap< T, ToIndexT >::size(), llvm::ConstraintSystem::size(), llvm::LazyCallGraph::SCC::size(), llvm::LazyCallGraph::RefSCC::size(), llvm::LiveRange::size(), llvm::LiveRangeEdit::size(), llvm::orc::AllocGroupSmallMap< T >::size(), llvm::AAPointerInfo::RangeList::size(), llvm::MDAttachments::size(), llvm::HexagonShuffler::size(), llvm::IntervalMapImpl::Path::size(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), llvm::dwarf_linker::parallel::ArrayList< T, ItemsGroupSize >::sort(), llvm::DebugLocEntry::sortUniqueValues(), llvm::SubtargetFeatures::Split(), llvm::DominatorTreeBase< NodeT, IsPostDom >::Split(), splitAsyncCoroutine(), llvm::splitBlockBefore(), SplitBlockImpl(), splitCallSite(), splitCodeGen(), splitRetconCoroutine(), llvm::CallLowering::splitToValueTypes(), llvm::DbgValueHistoryMap::startClobber(), llvm::DbgValueHistoryMap::startDbgValue(), llvm::StatepointLoweringState::startNewStatepoint(), llvm::PPCInstrInfo::storeRegToStackSlotNoUpd(), StoreTailCallArgumentsToStackSlot(), llvm::Regex::sub(), substituteSimpleCopyRegs(), llvm::SmallVectorImpl< T >::swap(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::BTFParser::symbolize(), llvm::TailDuplicator::tailDuplicateAndUpdate(), llvm::JumpThreadingPass::threadEdge(), llvm::CodeViewYAML::toDebugH(), llvm::Twine::toNullTerminatedStringRef(), llvm::detail::IEEEFloat::toString(), llvm::Twine::toStringRef(), llvm::PHITransAddr::translateWithInsertion(), llvm::LoopTraversal::traverse(), llvm::Triple::Triple(), tryBuildVectorShuffle(), TryCombineBaseUpdate(), llvm::tryDelinearizeFixedSizeImpl(), llvm::VFABI::tryDemangleForVFABI(), llvm::mca::RegisterFile::tryEliminateMoveOrSwap(), llvm::MCDwarfLineTableHeader::tryGetFile(), tryMergeRange(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), tryToVectorizeSequence(), llvm::IntEqClasses::uncompress(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopRemainder(), unswitchBestCondition(), unswitchTrivialSwitch(), UpdateAnalysisInformation(), updateBranchWeights(), updateIDTMetaData(), updatePhysDepsUpwards(), llvm::UpgradeModuleFlags(), upgradeRetainReleaseMarker(), ValidateMVEStore(), llvm::HexagonShuffler::ValidResourceUsage(), VectorizePTXValueVTs(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::LiveRange::verify(), llvm::DWARFExpression::Operation::verify(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::SCEVDivision::visitAddExpr(), llvm::SelectionDAGBuilder::visitDbgInfo(), llvm::InstCombinerImpl::visitLandingPadInst(), llvm::SCEVDivision::visitMulExpr(), llvm::widenShuffleMaskElts(), widenVectorOpsToi8(), llvm::objcopy::elf::BinaryWriter::write(), llvm::mcdxbc::Signature::write(), llvm::coverage::CoverageFilenamesSectionWriter::write(), llvm::mcdxbc::PSVRuntimeInfo::write(), llvm::writeArchiveToStream(), llvm::WriteBitcodeToFile(), llvm::objcopy::elf::IHexSectionWriter::writeData(), llvm::dxil::WriteDXILToFile(), llvm::writeIndexToFile(), llvm::BitcodeWriter::writeSymtab(), llvm::writeThinLinkBitcodeToFile(), writeUniversalArchsToStream(), llvm::sampleprof::SampleProfileWriter::writeWithSizeLimitInternal(), llvm::opt::Arg::~Arg(), and llvm::json::OStream::~OStream().
SizeTypeMax()
template<class Size_T > static constexpr size_t llvm::SmallVectorBase< Size_T >::SizeTypeMax () inline static constexpr protected
The maximum value of the Size_T used.
Definition at line 58 of file SmallVector.h.
Referenced by llvm::SmallVectorBase< Size_T >::set_allocation_range().
Member Data Documentation
BeginX
template<class Size_T > void* llvm::SmallVectorBase< Size_T >::BeginX protected
Definition at line 54 of file SmallVector.h.
Referenced by llvm::SmallVectorBase< Size_T >::set_allocation_range(), and llvm::SmallVectorImpl< T >::swap().
Capacity
template<class Size_T > Size_T llvm::SmallVectorBase< Size_T >::Capacity protected
Definition at line 55 of file SmallVector.h.
Referenced by llvm::SmallVectorBase< Size_T >::capacity(), llvm::SmallVectorBase< Size_T >::set_allocation_range(), and llvm::SmallVectorImpl< T >::swap().
Size
template<class Size_T > Size_T llvm::SmallVectorBase< Size_T >::Size = 0 protected
Definition at line 55 of file SmallVector.h.
Referenced by llvm::ARMBasicBlockUtils::adjustBBSize(), llvm::ComputeASanStackFrameLayout(), llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallVectorBase< Size_T >::set_size(), llvm::SmallVectorBase< Size_T >::size(), and llvm::SmallVectorImpl< T >::swap().
The documentation for this class was generated from the following files:
include/llvm/ADT/SmallVector.h
lib/Support/SmallVector.cpp