LLVM: llvm::orc::EPCGenericDylibManager Class Reference
llvm::orc::EPCGenericDylibManager Class Reference
#include "llvm/ExecutionEngine/Orc/EPCGenericDylibManager.h"
Classes
struct SymbolAddrs
Function addresses for memory access.
Public Member Functions
EPCGenericDylibManager (ExecutorProcessControl &EPC, SymbolAddrs SAs)
Create an EPCGenericMemoryAccess instance from a given set of function addrs.
Expected< tpctypes::DylibHandle > open (StringRef Path, uint64_t Mode)
Loads the dylib with the given name.
Expected< std::vector< ExecutorSymbolDef > > lookup (tpctypes::DylibHandle H, const SymbolLookupSet &Lookup)
Looks up symbols within the given dylib.
Expected< std::vector< ExecutorSymbolDef > > lookup (tpctypes::DylibHandle H, const RemoteSymbolLookupSet &Lookup)
Looks up symbols within the given dylib.
Static Public Member Functions
static Expected< EPCGenericDylibManager > CreateWithDefaultBootstrapSymbols (ExecutorProcessControl &EPC)
Create an EPCGenericMemoryAccess instance from a given set of function addrs.
Detailed Description
Definition at line 30 of file EPCGenericDylibManager.h.
Constructor & Destructor Documentation
EPCGenericDylibManager()
llvm::orc::EPCGenericDylibManager::EPCGenericDylibManager (ExecutorProcessControl & EPC, SymbolAddrs SAs) inline
Create an EPCGenericMemoryAccess instance from a given set of function addrs.
Definition at line 46 of file EPCGenericDylibManager.h.
Member Function Documentation
CreateWithDefaultBootstrapSymbols()
Expected< EPCGenericDylibManager > llvm::orc::EPCGenericDylibManager::CreateWithDefaultBootstrapSymbols (ExecutorProcessControl & EPC) static
Create an EPCGenericMemoryAccess instance from a given set of function addrs.
Definition at line 63 of file EPCGenericDylibManager.cpp.
References llvm::orc::ExecutorProcessControl::getBootstrapSymbols().
lookup() [1/2]
Expected< std::vector< ExecutorSymbolDef > > llvm::orc::EPCGenericDylibManager::lookup (tpctypes::DylibHandle H, const RemoteSymbolLookupSet & Lookup)
Looks up symbols within the given dylib.
Definition at line 97 of file EPCGenericDylibManager.cpp.
References H, and Lookup().
lookup() [2/2]
Expected< std::vector< ExecutorSymbolDef > > llvm::orc::EPCGenericDylibManager::lookup (tpctypes::DylibHandle H, const SymbolLookupSet & Lookup)
Looks up symbols within the given dylib.
Definition at line 85 of file EPCGenericDylibManager.cpp.
References H, and Lookup().
open()
Expected< tpctypes::DylibHandle > llvm::orc::EPCGenericDylibManager::open (StringRef Path, uint64_t Mode)
Loads the dylib with the given name.
Definition at line 74 of file EPCGenericDylibManager.cpp.
References H, and Mode.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/EPCGenericDylibManager.h
lib/ExecutionEngine/Orc/EPCGenericDylibManager.cpp