LLVM: llvm::objcopy::elf::IHexWriter Class Reference
llvm::objcopy::elf::IHexWriter Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
~IHexWriter ()
Error finalize () override
Error write () override
IHexWriter (Object &Obj, raw_ostream &Out)
Public Member Functions inherited from llvm::objcopy::elf::Writer
virtual ~Writer ()
virtual Error finalize ()=0
virtual Error write ()=0
Writer (Object &O, raw_ostream &Out)
Additional Inherited Members
Protected Attributes inherited from llvm::objcopy::elf::Writer
Object & Obj
std::unique_ptr< WritableMemoryBuffer > Buf
raw_ostream & Out
Detailed Description
Definition at line 374 of file ELFObject.h.
Constructor & Destructor Documentation
~IHexWriter()
llvm::objcopy::elf::IHexWriter::~IHexWriter () inline
Definition at line 387 of file ELFObject.h.
IHexWriter()
llvm::objcopy::elf::IHexWriter::IHexWriter (Object & Obj, raw_ostream & Out) inline
Definition at line 390 of file ELFObject.h.
Member Function Documentation
finalize()
Error IHexWriter::finalize () override virtual
Implements llvm::objcopy::elf::Writer.
Definition at line 2775 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionBase::accept(), addressOverflows32bit(), llvm::objcopy::elf::Writer::Buf, llvm::createStringError(), E, llvm::objcopy::elf::Object::Entry, llvm::objcopy::elf::SectionBase::Flags, llvm::objcopy::elf::IHexSectionWriterBase::getBufferOffset(), llvm::objcopy::elf::IHexRecord::getLineLength(), llvm::WritableMemoryBuffer::getNewMemBuffer(), llvm::invalid_argument, llvm::not_enough_memory, llvm::objcopy::elf::Writer::Obj, llvm::objcopy::elf::Object::sections(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_NOBITS, llvm::objcopy::elf::SectionBase::Size, llvm::Error::success(), llvm::objcopy::elf::SectionBase::Type, and llvm::Twine::utohexstr().
write()
Error IHexWriter::write () override virtual
Implements llvm::objcopy::elf::Writer.
Definition at line 2743 of file ELFObject.cpp.
References assert(), llvm::objcopy::elf::Writer::Buf, llvm::Offset, llvm::objcopy::elf::Writer::Out, llvm::Error::success(), and llvm::raw_ostream::write().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp