LLVM: llvm::GenericConvergenceVerifier< ContextT > Class Template Reference
llvm::GenericConvergenceVerifier< ContextT > Class Template Reference
#include "llvm/ADT/GenericConvergenceVerifier.h"
Public Types
using BlockT = typename ContextT::BlockT
using FunctionT = typename ContextT::FunctionT
using ValueRefT = typename ContextT::ValueRefT
using InstructionT = typename ContextT::InstructionT
using DominatorTreeT = typename ContextT::DominatorTreeT
using CycleInfoT = GenericCycleInfo< ContextT >
using CycleT = typename CycleInfoT::CycleT
Public Member Functions
void initialize (raw_ostream *OS, function_ref< void(const Twine &Message)> FailureCB, const FunctionT &F)
void clear ()
void visit (const BlockT &BB)
void visit (const InstructionT &I)
void verify (const DominatorTreeT &DT)
bool sawTokens () const
Detailed Description
template<typename ContextT>
class llvm::GenericConvergenceVerifier< ContextT >
Definition at line 23 of file GenericConvergenceVerifier.h.
Member Typedef Documentation
BlockT
template<typename ContextT > using llvm::GenericConvergenceVerifier< ContextT >::BlockT = typename ContextT::BlockT
Definition at line 25 of file GenericConvergenceVerifier.h.
CycleInfoT
template<typename ContextT > using llvm::GenericConvergenceVerifier< ContextT >::CycleInfoT = GenericCycleInfo<ContextT>
Definition at line 30 of file GenericConvergenceVerifier.h.
CycleT
template<typename ContextT > using llvm::GenericConvergenceVerifier< ContextT >::CycleT = typename CycleInfoT::CycleT
Definition at line 31 of file GenericConvergenceVerifier.h.
DominatorTreeT
template<typename ContextT > using llvm::GenericConvergenceVerifier< ContextT >::DominatorTreeT = typename ContextT::DominatorTreeT
Definition at line 29 of file GenericConvergenceVerifier.h.
FunctionT
template<typename ContextT > using llvm::GenericConvergenceVerifier< ContextT >::FunctionT = typename ContextT::FunctionT
Definition at line 26 of file GenericConvergenceVerifier.h.
InstructionT
template<typename ContextT > using llvm::GenericConvergenceVerifier< ContextT >::InstructionT = typename ContextT::InstructionT
Definition at line 28 of file GenericConvergenceVerifier.h.
ValueRefT
template<typename ContextT > using llvm::GenericConvergenceVerifier< ContextT >::ValueRefT = typename ContextT::ValueRefT
Definition at line 27 of file GenericConvergenceVerifier.h.
Member Function Documentation
clear()
template<class ContextT > void llvm::GenericConvergenceVerifier< ContextT >::clear
Definition at line 51 of file GenericConvergenceVerifierImpl.h.
Referenced by llvm::GenericConvergenceVerifier< ContextT >::initialize().
initialize()
template<typename ContextT > void llvm::GenericConvergenceVerifier< ContextT >::initialize (raw_ostream * OS, function_ref< void(const Twine &Message)> FailureCB, const FunctionT & F) inline
Definition at line 33 of file GenericConvergenceVerifier.h.
References llvm::GenericConvergenceVerifier< ContextT >::clear(), F, and OS.
sawTokens()
template<typename ContextT > bool llvm::GenericConvergenceVerifier< ContextT >::sawTokens () const inline
Definition at line 47 of file GenericConvergenceVerifier.h.
verify()
template<class ContextT > void llvm::GenericConvergenceVerifier< ContextT >::verify (const DominatorTreeT & DT)
Definition at line 132 of file GenericConvergenceVerifierImpl.h.
References assert(), Check, llvm::SmallVectorImpl< T >::clear(), Context, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), F, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), I, llvm::is_contained(), llvm::isConvergenceControlIntrinsic(), llvm::partition(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::successors(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
visit() [1/2]
template<class ContextT > void llvm::GenericConvergenceVerifier< ContextT >::visit (const BlockT & BB)
Definition at line 58 of file GenericConvergenceVerifierImpl.h.
visit() [2/2]
template<class ContextT > void llvm::GenericConvergenceVerifier< ContextT >::visit (const InstructionT & I)
Definition at line 63 of file GenericConvergenceVerifierImpl.h.
References Check, Context, I, and LLVM_FALLTHROUGH.
The documentation for this class was generated from the following files:
include/llvm/ADT/GenericConvergenceVerifier.h
include/llvm/IR/GenericConvergenceVerifierImpl.h