LLVM: llvm::object::MachOObjectFile Class Reference
llvm::object::MachOObjectFile Class Reference
#include "llvm/Object/MachO.h"
Classes
struct LoadCommandInfo
Public Types
using LoadCommandList = SmallVector< LoadCommandInfo, 4 >
using load_command_iterator = LoadCommandList::const_iterator
Public Types inherited from llvm::object::ObjectFile
using symbol_iterator_range = iterator_range< symbol_iterator >
using section_iterator_range = iterator_range< section_iterator >
Public Types inherited from llvm::object::SymbolicFile
using basic_symbol_iterator_range = iterator_range< basic_symbol_iterator >
Public Member Functions
void moveSymbolNext (DataRefImpl &Symb) const override
uint64_t getNValue (DataRefImpl Sym) const
Expected< StringRef > getSymbolName (DataRefImpl Symb) const override
Error checkSymbolTable () const
std::error_code getIndirectName (DataRefImpl Symb, StringRef &Res) const
unsigned getSectionType (SectionRef Sec) const
Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const override
uint32_t getSymbolAlignment (DataRefImpl Symb) const override
uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const override
Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const override
Expected< uint32_t > getSymbolFlags (DataRefImpl Symb) const override
Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const override
unsigned getSymbolSectionID (SymbolRef Symb) const
unsigned getSectionID (SectionRef Sec) const
void moveSectionNext (DataRefImpl &Sec) const override
Expected< StringRef > getSectionName (DataRefImpl Sec) const override
uint64_t getSectionAddress (DataRefImpl Sec) const override
uint64_t getSectionIndex (DataRefImpl Sec) const override
uint64_t getSectionSize (DataRefImpl Sec) const override
ArrayRef< uint8_t > getSectionContents (uint32_t Offset, uint64_t Size) const
Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const override
uint64_t getSectionAlignment (DataRefImpl Sec) const override
Expected< SectionRef > getSection (unsigned SectionIndex) const
Expected< SectionRef > getSection (StringRef SectionName) const
bool isSectionCompressed (DataRefImpl Sec) const override
bool isSectionText (DataRefImpl Sec) const override
bool isSectionData (DataRefImpl Sec) const override
bool isSectionBSS (DataRefImpl Sec) const override
bool isSectionVirtual (DataRefImpl Sec) const override
bool isSectionBitcode (DataRefImpl Sec) const override
bool isDebugSection (DataRefImpl Sec) const override
ArrayRef< uint8_t > getSegmentContents (StringRef SegmentName) const
Return the raw contents of an entire segment.
ArrayRef< uint8_t > getSegmentContents (size_t SegmentIndex) const
bool isSectionStripped (DataRefImpl Sec) const override
When dsymutil generates the companion file, it strips all unnecessary sections (e.g.
relocation_iterator section_rel_begin (DataRefImpl Sec) const override
relocation_iterator section_rel_end (DataRefImpl Sec) const override
relocation_iterator extrel_begin () const
relocation_iterator extrel_end () const
iterator_range< relocation_iterator > external_relocations () const
relocation_iterator locrel_begin () const
relocation_iterator locrel_end () const
void moveRelocationNext (DataRefImpl &Rel) const override
uint64_t getRelocationOffset (DataRefImpl Rel) const override
symbol_iterator getRelocationSymbol (DataRefImpl Rel) const override
section_iterator getRelocationSection (DataRefImpl Rel) const
uint64_t getRelocationType (DataRefImpl Rel) const override
void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const override
uint8_t getRelocationLength (DataRefImpl Rel) const
std::error_code getLibraryShortNameByIndex (unsigned Index, StringRef &) const
uint32_t getLibraryCount () const
section_iterator getRelocationRelocatedSection (relocation_iterator Rel) const
basic_symbol_iterator symbol_begin () const override
basic_symbol_iterator symbol_end () const override
bool is64Bit () const override
symbol_iterator getSymbolByIndex (unsigned Index) const
uint64_t getSymbolIndex (DataRefImpl Symb) const
section_iterator section_begin () const override
section_iterator section_end () const override
uint8_t getBytesInAddress () const override
The number of bytes used to represent an address in this object file format.
StringRef getFileFormatName () const override
Triple::ArchType getArch () const override
Expected< SubtargetFeatures > getFeatures () const override
Triple getArchTriple (const char **McpuDefault=nullptr) const
relocation_iterator section_rel_begin (unsigned Index) const
relocation_iterator section_rel_end (unsigned Index) const
dice_iterator begin_dices () const
dice_iterator end_dices () const
load_command_iterator begin_load_commands () const
load_command_iterator end_load_commands () const
iterator_range< load_command_iterator > load_commands () const
iterator_range< export_iterator > exports (Error &Err) const
For use iterating over all exported symbols.
iterator_range< rebase_iterator > rebaseTable (Error &Err)
For use iterating over all rebase table entries.
iterator_range< bind_iterator > bindTable (Error &Err)
For use iterating over all bind table entries.
iterator_range< fixup_iterator > fixupTable (Error &Err)
For iterating over all chained fixups.
iterator_range< bind_iterator > lazyBindTable (Error &Err)
For use iterating over all lazy bind table entries.
iterator_range< bind_iterator > weakBindTable (Error &Err)
For use iterating over all weak bind table entries.
const char * BindEntryCheckSegAndOffsets (int32_t SegIndex, uint64_t SegOffset, uint8_t PointerSize, uint32_t Count=1, uint32_t Skip=0) const
const char * RebaseEntryCheckSegAndOffsets (int32_t SegIndex, uint64_t SegOffset, uint8_t PointerSize, uint32_t Count=1, uint32_t Skip=0) const
StringRef BindRebaseSegmentName (int32_t SegIndex) const
For use with the SegIndex of a checked Mach-O Bind or Rebase entry to get the segment name.
StringRef BindRebaseSectionName (uint32_t SegIndex, uint64_t SegOffset) const
For use with a SegIndex,SegOffset pair from a checked Mach-O Bind or Rebase entry to get the section name.
uint64_t BindRebaseAddress (uint32_t SegIndex, uint64_t SegOffset) const
For use with a SegIndex,SegOffset pair from a checked Mach-O Bind or Rebase entry to get the address.
StringRef getSectionFinalSegmentName (DataRefImpl Sec) const
ArrayRef< char > getSectionRawName (DataRefImpl Sec) const
ArrayRef< char > getSectionRawFinalSegmentName (DataRefImpl Sec) const
bool isRelocationScattered (const MachO::any_relocation_info &RE) const
unsigned getPlainRelocationSymbolNum (const MachO::any_relocation_info &RE) const
bool getPlainRelocationExternal (const MachO::any_relocation_info &RE) const
bool getScatteredRelocationScattered (const MachO::any_relocation_info &RE) const
uint32_t getScatteredRelocationValue (const MachO::any_relocation_info &RE) const
uint32_t getScatteredRelocationType (const MachO::any_relocation_info &RE) const
unsigned getAnyRelocationAddress (const MachO::any_relocation_info &RE) const
unsigned getAnyRelocationPCRel (const MachO::any_relocation_info &RE) const
unsigned getAnyRelocationLength (const MachO::any_relocation_info &RE) const
unsigned getAnyRelocationType (const MachO::any_relocation_info &RE) const
SectionRef getAnyRelocationSection (const MachO::any_relocation_info &RE) const
MachO::section getSection (DataRefImpl DRI) const
MachO::section_64 getSection64 (DataRefImpl DRI) const
MachO::section getSection (const LoadCommandInfo &L, unsigned Index) const
MachO::section_64 getSection64 (const LoadCommandInfo &L, unsigned Index) const
MachO::nlist getSymbolTableEntry (DataRefImpl DRI) const
MachO::nlist_64 getSymbol64TableEntry (DataRefImpl DRI) const
MachO::linkedit_data_command getLinkeditDataLoadCommand (const LoadCommandInfo &L) const
MachO::segment_command getSegmentLoadCommand (const LoadCommandInfo &L) const
MachO::segment_command_64 getSegment64LoadCommand (const LoadCommandInfo &L) const
MachO::linker_option_command getLinkerOptionLoadCommand (const LoadCommandInfo &L) const
MachO::version_min_command getVersionMinLoadCommand (const LoadCommandInfo &L) const
MachO::note_command getNoteLoadCommand (const LoadCommandInfo &L) const
MachO::build_version_command getBuildVersionLoadCommand (const LoadCommandInfo &L) const
MachO::build_tool_version getBuildToolVersion (unsigned index) const
MachO::dylib_command getDylibIDLoadCommand (const LoadCommandInfo &L) const
MachO::dyld_info_command getDyldInfoLoadCommand (const LoadCommandInfo &L) const
MachO::dylinker_command getDylinkerCommand (const LoadCommandInfo &L) const
MachO::uuid_command getUuidCommand (const LoadCommandInfo &L) const
MachO::rpath_command getRpathCommand (const LoadCommandInfo &L) const
MachO::source_version_command getSourceVersionCommand (const LoadCommandInfo &L) const
MachO::entry_point_command getEntryPointCommand (const LoadCommandInfo &L) const
MachO::encryption_info_command getEncryptionInfoCommand (const LoadCommandInfo &L) const
MachO::encryption_info_command_64 getEncryptionInfoCommand64 (const LoadCommandInfo &L) const
MachO::sub_framework_command getSubFrameworkCommand (const LoadCommandInfo &L) const
MachO::sub_umbrella_command getSubUmbrellaCommand (const LoadCommandInfo &L) const
MachO::sub_library_command getSubLibraryCommand (const LoadCommandInfo &L) const
MachO::sub_client_command getSubClientCommand (const LoadCommandInfo &L) const
MachO::routines_command getRoutinesCommand (const LoadCommandInfo &L) const
MachO::routines_command_64 getRoutinesCommand64 (const LoadCommandInfo &L) const
MachO::thread_command getThreadCommand (const LoadCommandInfo &L) const
MachO::fileset_entry_command getFilesetEntryLoadCommand (const LoadCommandInfo &L) const
MachO::any_relocation_info getRelocation (DataRefImpl Rel) const
MachO::data_in_code_entry getDice (DataRefImpl Rel) const
const MachO::mach_header & getHeader () const
const MachO::mach_header_64 & getHeader64 () const
uint32_t getIndirectSymbolTableEntry (const MachO::dysymtab_command &DLC, unsigned Index) const
MachO::data_in_code_entry getDataInCodeTableEntry (uint32_t DataOffset, unsigned Index) const
MachO::symtab_command getSymtabLoadCommand () const
MachO::dysymtab_command getDysymtabLoadCommand () const
MachO::linkedit_data_command getDataInCodeLoadCommand () const
MachO::linkedit_data_command getLinkOptHintsLoadCommand () const
ArrayRef< uint8_t > getDyldInfoRebaseOpcodes () const
ArrayRef< uint8_t > getDyldInfoBindOpcodes () const
ArrayRef< uint8_t > getDyldInfoWeakBindOpcodes () const
ArrayRef< uint8_t > getDyldInfoLazyBindOpcodes () const
ArrayRef< uint8_t > getDyldInfoExportsTrie () const
Expected< std::optional< MachO::dyld_chained_fixups_header > > getChainedFixupsHeader () const
If the optional is std::nullopt, no header was found, but the object was well-formed.
Expected< std::vector< ChainedFixupTarget > > getDyldChainedFixupTargets () const
Expected< std::optional< MachO::linkedit_data_command > > getChainedFixupsLoadCommand () const
Expected< std::pair< size_t, std::vector< ChainedFixupsSegment > > > getChainedFixupsSegments () const
ArrayRef< uint8_t > getDyldExportsTrie () const
SmallVector< uint64_t > getFunctionStarts () const
ArrayRef< uint8_t > getUuid () const
StringRef getStringTableData () const
void ReadULEB128s (uint64_t Index, SmallVectorImpl< uint64_t > &Out) const
bool isRelocatableObject () const override
True if this is a relocatable object (.o/.obj).
StringRef mapDebugSectionName (StringRef Name) const override
Maps a debug section name to a standard DWARF section name.
llvm::binaryformat::Swift5ReflectionSectionKind mapReflectionSectionNameToEnumValue (StringRef SectionName) const override
bool hasPageZeroSegment () const
size_t getMachOFilesetEntryOffset () const
Public Member Functions inherited from llvm::object::ObjectFile
ObjectFile ()=delete
ObjectFile (const ObjectFile &other)=delete
uint64_t getCommonSymbolSize (DataRefImpl Symb) const
virtual std::vector< SectionRef > dynamic_relocation_sections () const
symbol_iterator_range symbols () const
virtual section_iterator section_begin () const =0
virtual section_iterator section_end () const =0
section_iterator_range sections () const
virtual bool hasDebugInfo () const
virtual uint8_t getBytesInAddress () const =0
The number of bytes used to represent an address in this object file format.
virtual StringRef getFileFormatName () const =0
virtual Triple::ArchType getArch () const =0
virtual Triple::OSType getOS () const
virtual Expected< SubtargetFeatures > getFeatures () const =0
virtual std::optional< StringRef > tryGetCPUName () const
virtual void setARMSubArch (Triple &TheTriple) const
virtual Expected< uint64_t > getStartAddress () const
Triple makeTriple () const
Create a triple from the data in this object file.
virtual StringRef mapDebugSectionName (StringRef Name) const
Maps a debug section name to a standard DWARF section name.
virtual bool isRelocatableObject () const =0
True if this is a relocatable object (.o/.obj).
bool isReflectionSectionStrippable (llvm::binaryformat::Swift5ReflectionSectionKind ReflectionSectionKind) const
True if the reflection section can be stripped by the linker.
Public Member Functions inherited from llvm::object::SymbolicFile
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
~SymbolicFile () override
virtual void moveSymbolNext (DataRefImpl &Symb) const =0
virtual Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const =0
virtual Expected< uint32_t > getSymbolFlags (DataRefImpl Symb) const =0
virtual basic_symbol_iterator symbol_begin () const =0
virtual basic_symbol_iterator symbol_end () const =0
virtual bool is64Bit () const =0
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
virtual Error initContent ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isTapiUniversal () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isOffloadFile () const
bool isCOFFImportFile () const
bool isIR () const
bool isGOFF () const
bool isMinidump () const
bool isTapiFile () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static Expected< std::unique_ptr< MachOObjectFile > > create (MemoryBufferRef Object, bool IsLittleEndian, bool Is64Bits, uint32_t UniversalCputype=0, uint32_t UniversalIndex=0, size_t MachOFilesetEntryOffset=0)
static bool isMachOPairedReloc (uint64_t RelocType, uint64_t Arch)
static iterator_range< export_iterator > exports (Error &Err, ArrayRef< uint8_t > Trie, const MachOObjectFile *O=nullptr)
For use examining a trie not in a MachOObjectFile.
static iterator_range< rebase_iterator > rebaseTable (Error &Err, MachOObjectFile *O, ArrayRef< uint8_t > Opcodes, bool is64)
For use examining rebase opcodes in a MachOObjectFile.
static iterator_range< bind_iterator > bindTable (Error &Err, MachOObjectFile *O, ArrayRef< uint8_t > Opcodes, bool is64, MachOBindEntry::Kind)
For use examining bind opcodes in a MachOObjectFile.
static StringRef guessLibraryShortName (StringRef Name, bool &isFramework, StringRef &Suffix)
static Triple::ArchType getArch (uint32_t CPUType, uint32_t CPUSubType)
static Triple getArchTriple (uint32_t CPUType, uint32_t CPUSubType, const char **McpuDefault=nullptr, const char **ArchFlag=nullptr)
static bool isValidArch (StringRef ArchFlag)
static ArrayRef< StringRef > getValidArchs ()
static Triple getHostArch ()
static bool classof (const Binary *v)
static uint32_t getVersionMinMajor (MachO::version_min_command &C, bool SDK)
static uint32_t getVersionMinMinor (MachO::version_min_command &C, bool SDK)
static uint32_t getVersionMinUpdate (MachO::version_min_command &C, bool SDK)
static std::string getBuildPlatform (uint32_t platform)
static std::string getBuildTool (uint32_t tools)
static std::string getVersionString (uint32_t version)
static Expected< std::vector< std::string > > findDsymObjectMembers (StringRef Path)
If the input path is a .dSYM bundle (as created by the dsymutil tool), return the paths to the object files found in the bundle, otherwise return an empty vector.
Static Public Member Functions inherited from llvm::object::ObjectFile
static Expected< OwningBinary< ObjectFile > > createObjectFile (StringRef ObjectPath)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object, llvm::file_magic Type, bool InitContent=true)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static Expected< std::unique_ptr< COFFObjectFile > > createCOFFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< ObjectFile > > createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType)
static Expected< std::unique_ptr< ObjectFile > > createELFObjectFile (MemoryBufferRef Object, bool InitContent=true)
static Expected< std::unique_ptr< MachOObjectFile > > createMachOObjectFile (MemoryBufferRef Object, uint32_t UniversalCputype=0, uint32_t UniversalIndex=0, size_t MachOFilesetEntryOffset=0)
Create a MachOObjectFile instance from a given buffer.
static Expected< std::unique_ptr< ObjectFile > > createGOFFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< WasmObjectFile > > createWasmObjectFile (MemoryBufferRef Object)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, llvm::file_magic Type, LLVMContext *Context, bool InitContent=true)
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static bool isSymbolicFile (file_magic Type, const LLVMContext *Context)
Static Public Member Functions inherited from llvm::object::Binary
static Error checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_COFFImportFile , ID_IR ,
ID_TapiUniversal , ID_TapiFile , ID_Minidump , ID_WinRes ,
ID_Offload , ID_StartObjects , ID_COFF , ID_XCOFF32 ,
ID_XCOFF64 , ID_ELF32L , ID_ELF32B , ID_ELF64L ,
ID_ELF64B , ID_MachO32L , ID_MachO32B , ID_MachO64L ,
ID_MachO64B , ID_GOFF , ID_Wasm , ID_EndObjects
}
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBufferRef Source)
const uint8_t * base () const
virtual Expected< StringRef > getSymbolName (DataRefImpl Symb) const =0
Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
virtual Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const =0
virtual uint64_t getSymbolValueImpl (DataRefImpl Symb) const =0
virtual uint32_t getSymbolAlignment (DataRefImpl Symb) const
virtual uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const =0
virtual Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const =0
virtual Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const =0
virtual void moveSectionNext (DataRefImpl &Sec) const =0
virtual Expected< StringRef > getSectionName (DataRefImpl Sec) const =0
virtual uint64_t getSectionAddress (DataRefImpl Sec) const =0
virtual uint64_t getSectionIndex (DataRefImpl Sec) const =0
virtual uint64_t getSectionSize (DataRefImpl Sec) const =0
virtual Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const =0
virtual uint64_t getSectionAlignment (DataRefImpl Sec) const =0
virtual bool isSectionCompressed (DataRefImpl Sec) const =0
virtual bool isSectionText (DataRefImpl Sec) const =0
virtual bool isSectionData (DataRefImpl Sec) const =0
virtual bool isSectionBSS (DataRefImpl Sec) const =0
virtual bool isSectionVirtual (DataRefImpl Sec) const =0
virtual bool isSectionBitcode (DataRefImpl Sec) const
virtual bool isSectionStripped (DataRefImpl Sec) const
virtual bool isBerkeleyText (DataRefImpl Sec) const
virtual bool isBerkeleyData (DataRefImpl Sec) const
virtual bool isDebugSection (DataRefImpl Sec) const
virtual relocation_iterator section_rel_begin (DataRefImpl Sec) const =0
virtual relocation_iterator section_rel_end (DataRefImpl Sec) const =0
virtual Expected< section_iterator > getRelocatedSection (DataRefImpl Sec) const
virtual void moveRelocationNext (DataRefImpl &Rel) const =0
virtual uint64_t getRelocationOffset (DataRefImpl Rel) const =0
virtual symbol_iterator getRelocationSymbol (DataRefImpl Rel) const =0
virtual uint64_t getRelocationType (DataRefImpl Rel) const =0
virtual void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const =0
virtual llvm::binaryformat::Swift5ReflectionSectionKind mapReflectionSectionNameToEnumValue (StringRef SectionName) const
Expected< uint64_t > getSymbolValue (DataRefImpl Symb) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 406 of file MachO.h.
Member Typedef Documentation
load_command_iterator
using llvm::object::MachOObjectFile::load_command_iterator = LoadCommandList::const_iterator
Definition at line 413 of file MachO.h.
LoadCommandList
using llvm::object::MachOObjectFile::LoadCommandList = SmallVector<LoadCommandInfo, 4>
Definition at line 412 of file MachO.h.
Member Function Documentation
begin_dices()
dice_iterator MachOObjectFile::begin_dices () const
Definition at line 2901 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::dataoff, getDataInCodeLoadCommand(), getPtr(), and llvm::object::DataRefImpl::p.
begin_load_commands()
MachOObjectFile::load_command_iterator MachOObjectFile::begin_load_commands () const
Definition at line 4502 of file MachOObjectFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by load_commands().
BindEntryCheckSegAndOffsets()
const char * llvm::object::MachOObjectFile::BindEntryCheckSegAndOffsets (int32_t SegIndex, uint64_t SegOffset, uint8_t PointerSize, uint32_t Count = 1, uint32_t Skip = 0) const inline
Definition at line 578 of file MachO.h.
Referenced by llvm::object::MachOBindEntry::moveNext().
BindRebaseAddress()
uint64_t llvm::object::MachOObjectFile::BindRebaseAddress (uint32_t SegIndex, uint64_t SegOffset) const inline
For use with a SegIndex,SegOffset pair from a checked Mach-O Bind or Rebase entry to get the address.
Definition at line 614 of file MachO.h.
Referenced by llvm::object::MachORebaseEntry::address(), llvm::object::MachOBindEntry::address(), llvm::object::MachOAbstractFixupEntry::address(), and llvm::object::MachOAbstractFixupEntry::segmentAddress().
BindRebaseSectionName()
StringRef llvm::object::MachOObjectFile::BindRebaseSectionName (uint32_t SegIndex, uint64_t SegOffset) const inline
For use with a SegIndex,SegOffset pair from a checked Mach-O Bind or Rebase entry to get the section name.
Definition at line 608 of file MachO.h.
Referenced by llvm::object::MachORebaseEntry::sectionName(), llvm::object::MachOBindEntry::sectionName(), and llvm::object::MachOAbstractFixupEntry::sectionName().
BindRebaseSegmentName()
StringRef llvm::object::MachOObjectFile::BindRebaseSegmentName (int32_t SegIndex) const inline
For use with the SegIndex of a checked Mach-O Bind or Rebase entry to get the segment name.
Definition at line 602 of file MachO.h.
Referenced by llvm::object::MachORebaseEntry::segmentName(), llvm::object::MachOBindEntry::segmentName(), and llvm::object::MachOAbstractFixupEntry::segmentName().
bindTable() [1/2]
iterator_range< bind_iterator > MachOObjectFile::bindTable (Error & Err)
For use iterating over all bind table entries.
Definition at line 4473 of file MachOObjectFile.cpp.
References bindTable(), getDyldInfoBindOpcodes(), is64Bit(), and llvm::object::MachOBindEntry::Regular.
Referenced by bindTable(), lazyBindTable(), and weakBindTable().
bindTable() [2/2]
iterator_range< bind_iterator > MachOObjectFile::bindTable (Error & Err, MachOObjectFile * O, ArrayRef< uint8_t > Opcodes, bool is64, MachOBindEntry::Kind BKind) static
For use examining bind opcodes in a MachOObjectFile.
Definition at line 4459 of file MachOObjectFile.cpp.
References llvm::make_range().
checkSymbolTable()
Error MachOObjectFile::checkSymbolTable () const
Definition at line 1700 of file MachOObjectFile.cpp.
References llvm::MachO::DYNAMIC_LOOKUP_ORDINAL, llvm::MachO::EXECUTABLE_ORDINAL, llvm::MachO::mach_header_64::flags, llvm::MachO::GET_LIBRARY_ORDINAL(), getHeader(), getHeader64(), getSymbol64TableEntry(), getSymbolTableEntry(), getSymtabLoadCommand(), H, is64Bit(), malformedError(), llvm::MachO::MH_TWOLEVEL, llvm::MachO::nlist::n_desc, llvm::MachO::nlist_64::n_desc, llvm::MachO::N_INDR, llvm::MachO::N_PBUD, llvm::MachO::N_SECT, llvm::MachO::nlist::n_sect, llvm::MachO::nlist_64::n_sect, llvm::MachO::N_STAB, llvm::MachO::nlist::n_strx, llvm::MachO::nlist_64::n_strx, llvm::MachO::N_TYPE, llvm::MachO::nlist::n_type, llvm::MachO::nlist_64::n_type, llvm::MachO::N_UNDF, llvm::MachO::nlist::n_value, llvm::MachO::nlist_64::n_value, llvm::SmallVectorBase< Size_T >::size(), llvm::MachO::symtab_command::strsize, llvm::Error::success(), and llvm::object::ObjectFile::symbols().
classof()
static bool llvm::object::MachOObjectFile::classof (const Binary * v) inline static
Definition at line 768 of file MachO.h.
create()
Expected< std::unique_ptr< MachOObjectFile > > MachOObjectFile::create (MemoryBufferRef Object, bool IsLittleEndian, bool Is64Bits, uint32_t UniversalCputype = 0, uint32_t UniversalIndex = 0, size_t MachOFilesetEntryOffset = 0) static
Definition at line 1253 of file MachOObjectFile.cpp.
References llvm::Error::success().
Referenced by llvm::object::ObjectFile::createMachOObjectFile().
end_dices()
dice_iterator MachOObjectFile::end_dices () const
Definition at line 2911 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::dataoff, llvm::MachO::linkedit_data_command::datasize, getDataInCodeLoadCommand(), getPtr(), llvm::Offset, and llvm::object::DataRefImpl::p.
end_load_commands()
MachOObjectFile::load_command_iterator MachOObjectFile::end_load_commands () const
Definition at line 4507 of file MachOObjectFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by load_commands().
exports() [1/2]
iterator_range< export_iterator > MachOObjectFile::exports (Error & Err) const
For use iterating over all exported symbols.
Definition at line 3242 of file MachOObjectFile.cpp.
References exports(), getDyldExportsTrie(), and getDyldInfoExportsTrie().
Referenced by exports(), and readSymbols().
exports() [2/2]
iterator_range< export_iterator > MachOObjectFile::exports (Error & Err, ArrayRef< uint8_t > Trie, const MachOObjectFile * O = nullptr) static
For use examining a trie not in a MachOObjectFile.
Definition at line 3228 of file MachOObjectFile.cpp.
References E, llvm::ArrayRef< T >::empty(), and llvm::make_range().
external_relocations()
iterator_range< relocation_iterator > llvm::object::MachOObjectFile::external_relocations () const inline
Definition at line 479 of file MachO.h.
References extrel_begin(), extrel_end(), and llvm::make_range().
extrel_begin()
relocation_iterator MachOObjectFile::extrel_begin () const
Definition at line 2198 of file MachOObjectFile.cpp.
References llvm::object::ObjectFile::RelocationRef.
Referenced by external_relocations().
extrel_end()
relocation_iterator MachOObjectFile::extrel_end () const
Definition at line 2206 of file MachOObjectFile.cpp.
References getDysymtabLoadCommand(), llvm::MachO::dysymtab_command::nextrel, and llvm::object::ObjectFile::RelocationRef.
Referenced by external_relocations().
findDsymObjectMembers()
Expected< std::vector< std::string > > MachOObjectFile::findDsymObjectMembers (StringRef Path) static
If the input path is a .dSYM bundle (as created by the dsymutil tool), return the paths to the object files found in the bundle, otherwise return an empty vector.
If the path appears to be a .dSYM bundle but no objects were found or there was a filesystem error, then return an error.
Definition at line 5349 of file MachOObjectFile.cpp.
References llvm::sys::path::append(), llvm::createFileError(), llvm::createStringError(), llvm::errorCodeToError(), llvm::sys::path::extension(), llvm::sys::fs::is_directory(), llvm::no_such_file_or_directory, llvm::sys::fs::regular_file, llvm::sys::path::remove_dots(), llvm::sys::fs::status(), llvm::StringRef::str(), llvm::sys::fs::symlink_file, and llvm::sys::fs::type_unknown.
Referenced by llvm::InstrProfCorrelator::get().
fixupTable()
iterator_range< fixup_iterator > MachOObjectFile::fixupTable (Error & Err)
For iterating over all chained fixups.
Definition at line 4488 of file MachOObjectFile.cpp.
References llvm::make_range(), and llvm::object::MachOChainedFixupEntry::moveToEnd().
getAnyRelocationAddress()
unsigned MachOObjectFile::getAnyRelocationAddress (const MachO::any_relocation_info & RE) const
Definition at line 4575 of file MachOObjectFile.cpp.
References getPlainRelocationAddress(), getScatteredRelocationAddress(), and isRelocationScattered().
Referenced by getRelocationOffset().
getAnyRelocationLength()
unsigned MachOObjectFile::getAnyRelocationLength (const MachO::any_relocation_info & RE) const
Definition at line 4589 of file MachOObjectFile.cpp.
References getPlainRelocationLength(), getScatteredRelocationLength(), and isRelocationScattered().
Referenced by llvm::RuntimeDyldMachO::getRelocationEntry(), getRelocationLength(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), and llvm::RuntimeDyldMachO::processScatteredVANILLA().
getAnyRelocationPCRel()
unsigned MachOObjectFile::getAnyRelocationPCRel (const MachO::any_relocation_info & RE) const
Definition at line 4582 of file MachOObjectFile.cpp.
References getPlainRelocationPCRel(), getScatteredRelocationPCRel(), and isRelocationScattered().
Referenced by llvm::RuntimeDyldMachO::getRelocationEntry(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), and llvm::RuntimeDyldMachO::processScatteredVANILLA().
getAnyRelocationSection()
SectionRef MachOObjectFile::getAnyRelocationSection (const MachO::any_relocation_info & RE) const
Definition at line 4605 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, getPlainRelocationExternal(), getPlainRelocationSymbolNum(), isRelocationScattered(), llvm::MachO::R_ABS, section_end(), and llvm::object::ObjectFile::SectionRef.
Referenced by getRelocationSection(), and llvm::RuntimeDyldMachO::getRelocationValueRef().
getAnyRelocationType()
unsigned MachOObjectFile::getAnyRelocationType (const MachO::any_relocation_info & RE) const
Definition at line 4597 of file MachOObjectFile.cpp.
References getPlainRelocationType(), getScatteredRelocationType(), and isRelocationScattered().
Referenced by extractSections(), llvm::RuntimeDyldMachO::getRelocationEntry(), getRelocationType(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), llvm::RuntimeDyldMachOI386::processRelocationRef(), llvm::RuntimeDyldMachOX86_64::processRelocationRef(), and llvm::RuntimeDyldMachO::processScatteredVANILLA().
getArch() [1/2]
Triple::ArchType MachOObjectFile::getArch () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2881 of file MachOObjectFile.cpp.
References getArch(), getCPUSubType(), and getCPUType().
Referenced by getArch(), and getRelocationTypeName().
getArch() [2/2]
Triple::ArchType MachOObjectFile::getArch (uint32_t CPUType, uint32_t CPUSubType) static
Definition at line 2689 of file MachOObjectFile.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_32, llvm::Triple::arm, llvm::MachO::CPU_TYPE_ARM, llvm::MachO::CPU_TYPE_ARM64, llvm::MachO::CPU_TYPE_ARM64_32, llvm::MachO::CPU_TYPE_I386, llvm::MachO::CPU_TYPE_POWERPC, llvm::MachO::CPU_TYPE_POWERPC64, llvm::MachO::CPU_TYPE_X86_64, llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::UnknownArch, llvm::Triple::x86, and llvm::Triple::x86_64.
getArchTriple() [1/2]
Triple MachOObjectFile::getArchTriple (const char ** McpuDefault = nullptr) const
Definition at line 2885 of file MachOObjectFile.cpp.
References llvm::MachO::mach_header::cpusubtype, llvm::MachO::mach_header::cputype, getArchTriple(), and Header.
Referenced by llvm::object::Slice::create(), llvm::object::MachOUniversalBinary::ObjectForArch::getArchFlagName(), getArchTriple(), and llvm::object::MachOUniversalBinary::ObjectForArch::getTriple().
getArchTriple() [2/2]
Triple MachOObjectFile::getArchTriple (uint32_t CPUType, uint32_t CPUSubType, const char ** McpuDefault = nullptr, const char ** ArchFlag = nullptr) static
Definition at line 2710 of file MachOObjectFile.cpp.
References llvm::MachO::CPU_SUBTYPE_ARM64_32_V8, llvm::MachO::CPU_SUBTYPE_ARM64_ALL, llvm::MachO::CPU_SUBTYPE_ARM64E, llvm::MachO::CPU_SUBTYPE_ARM_V4T, llvm::MachO::CPU_SUBTYPE_ARM_V5TEJ, llvm::MachO::CPU_SUBTYPE_ARM_V6, llvm::MachO::CPU_SUBTYPE_ARM_V6M, llvm::MachO::CPU_SUBTYPE_ARM_V7, llvm::MachO::CPU_SUBTYPE_ARM_V7EM, llvm::MachO::CPU_SUBTYPE_ARM_V7K, llvm::MachO::CPU_SUBTYPE_ARM_V7M, llvm::MachO::CPU_SUBTYPE_ARM_V7S, llvm::MachO::CPU_SUBTYPE_ARM_XSCALE, llvm::MachO::CPU_SUBTYPE_I386_ALL, llvm::MachO::CPU_SUBTYPE_MASK, llvm::MachO::CPU_SUBTYPE_POWERPC_ALL, llvm::MachO::CPU_SUBTYPE_X86_64_ALL, llvm::MachO::CPU_SUBTYPE_X86_64_H, llvm::MachO::CPU_TYPE_ARM, llvm::MachO::CPU_TYPE_ARM64, llvm::MachO::CPU_TYPE_ARM64_32, llvm::MachO::CPU_TYPE_I386, llvm::MachO::CPU_TYPE_POWERPC, llvm::MachO::CPU_TYPE_POWERPC64, and llvm::MachO::CPU_TYPE_X86_64.
getBuildPlatform()
static std::string llvm::object::MachOObjectFile::getBuildPlatform (uint32_t platform) inline static
Definition at line 790 of file MachO.h.
References llvm::format_hex(), and llvm::raw_string_ostream::str().
getBuildTool()
static std::string llvm::object::MachOObjectFile::getBuildTool (uint32_t tools) inline static
Definition at line 805 of file MachO.h.
References llvm::format_hex(), llvm::raw_string_ostream::str(), llvm::MachO::TOOL_CLANG, llvm::MachO::TOOL_LD, llvm::MachO::TOOL_LLD, and llvm::MachO::TOOL_SWIFT.
getBuildToolVersion()
MachO::build_tool_version MachOObjectFile::getBuildToolVersion (unsigned index) const
Definition at line 4687 of file MachOObjectFile.cpp.
getBuildVersionLoadCommand()
MachO::build_version_command MachOObjectFile::getBuildVersionLoadCommand (const LoadCommandInfo & L) const
Definition at line 4682 of file MachOObjectFile.cpp.
Referenced by constructTriples().
getBytesInAddress()
uint8_t MachOObjectFile::getBytesInAddress () const override virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 2656 of file MachOObjectFile.cpp.
References is64Bit().
getChainedFixupsHeader()
Expected< std::optional< MachO::dyld_chained_fixups_header > > MachOObjectFile::getChainedFixupsHeader () const
If the optional is std::nullopt, no header was found, but the object was well-formed.
Definition at line 4995 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::dataoff, llvm::MachO::linkedit_data_command::datasize, llvm::MachO::dyld_chained_fixups_header::fixups_version, getChainedFixupsLoadCommand(), getPtr(), llvm::MachO::dyld_chained_fixups_header::imports_format, malformedError(), and llvm::MachO::dyld_chained_fixups_header::starts_offset.
Referenced by getChainedFixupsSegments(), and getDyldChainedFixupTargets().
getChainedFixupsLoadCommand()
Expected< std::optional< MachO::linkedit_data_command > > MachOObjectFile::getChainedFixupsLoadCommand () const
Definition at line 4976 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::dataoff.
Referenced by getChainedFixupsHeader(), getChainedFixupsSegments(), and getDyldChainedFixupTargets().
getChainedFixupsSegments()
Expected< std::pair< size_t, std::vector< ChainedFixupsSegment > > > MachOObjectFile::getChainedFixupsSegments () const
Definition at line 5046 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::dataoff, llvm::MachO::linkedit_data_command::datasize, Fail, getChainedFixupsHeader(), getChainedFixupsLoadCommand(), getPtr(), Header, I, llvm::object::Binary::isLittleEndian(), llvm::sys::IsLittleEndianHost, malformedError(), N, offsetof, llvm::MachO::dyld_chained_starts_in_segment::page_count, llvm::MachO::dyld_chained_starts_in_segment::pointer_format, llvm::MachO::dyld_chained_starts_in_image::seg_count, llvm::MachO::dyld_chained_starts_in_segment::size, and llvm::sys::swapByteOrder().
Referenced by llvm::object::MachOChainedFixupEntry::MachOChainedFixupEntry().
getCommonSymbolSizeImpl()
uint64_t MachOObjectFile::getCommonSymbolSizeImpl (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1837 of file MachOObjectFile.cpp.
References getNValue().
getDataInCodeLoadCommand()
MachO::linkedit_data_command MachOObjectFile::getDataInCodeLoadCommand () const
Definition at line 4877 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::cmd, llvm::MachO::linkedit_data_command::cmdsize, llvm::MachO::linkedit_data_command::dataoff, and llvm::MachO::linkedit_data_command::datasize.
Referenced by begin_dices(), and end_dices().
getDataInCodeTableEntry()
MachO::data_in_code_entry MachOObjectFile::getDataInCodeTableEntry (uint32_t DataOffset, unsigned Index) const
Definition at line 4826 of file MachOObjectFile.cpp.
References getPtr(), and llvm::Offset.
getDice()
MachO::data_in_code_entry MachOObjectFile::getDice (DataRefImpl Rel) const
Definition at line 4804 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::p, and P.
Referenced by llvm::object::DiceRef::getKind(), llvm::object::DiceRef::getLength(), and llvm::object::DiceRef::getOffset().
getDyldChainedFixupTargets()
Expected< std::vector< ChainedFixupTarget > > MachOObjectFile::getDyldChainedFixupTargets () const
Definition at line 5155 of file MachOObjectFile.cpp.
References llvm::object::createError(), llvm::MachO::linkedit_data_command::dataoff, llvm::MachO::linkedit_data_command::datasize, llvm::MachO::DYLD_CHAINED_IMPORT, llvm::MachO::DYLD_CHAINED_IMPORT_ADDEND, llvm::MachO::DYLD_CHAINED_IMPORT_ADDEND64, getChainedFixupsHeader(), getChainedFixupsLoadCommand(), getPtr(), Header, llvm::object::Binary::isLittleEndian(), llvm_unreachable, and malformedError().
Referenced by llvm::object::MachOChainedFixupEntry::MachOChainedFixupEntry().
getDyldExportsTrie()
ArrayRef< uint8_t > MachOObjectFile::getDyldExportsTrie () const
Definition at line 5252 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::dataoff, llvm::MachO::linkedit_data_command::datasize, getPtr(), and Ptr.
Referenced by exports().
getDyldInfoBindOpcodes()
ArrayRef< uint8_t > MachOObjectFile::getDyldInfoBindOpcodes () const
Definition at line 4919 of file MachOObjectFile.cpp.
References llvm::MachO::dyld_info_command::bind_off, llvm::MachO::dyld_info_command::bind_size, getPtr(), and Ptr.
Referenced by bindTable().
getDyldInfoExportsTrie()
ArrayRef< uint8_t > MachOObjectFile::getDyldInfoExportsTrie () const
Definition at line 4961 of file MachOObjectFile.cpp.
References llvm::MachO::dyld_info_command::export_off, llvm::MachO::dyld_info_command::export_size, getPtr(), and Ptr.
Referenced by exports().
getDyldInfoLazyBindOpcodes()
ArrayRef< uint8_t > MachOObjectFile::getDyldInfoLazyBindOpcodes () const
Definition at line 4947 of file MachOObjectFile.cpp.
References getPtr(), llvm::MachO::dyld_info_command::lazy_bind_off, llvm::MachO::dyld_info_command::lazy_bind_size, and Ptr.
Referenced by lazyBindTable().
getDyldInfoLoadCommand()
MachO::dyld_info_command MachOObjectFile::getDyldInfoLoadCommand (const LoadCommandInfo & L) const
Definition at line 4697 of file MachOObjectFile.cpp.
getDyldInfoRebaseOpcodes()
ArrayRef< uint8_t > MachOObjectFile::getDyldInfoRebaseOpcodes () const
Definition at line 4905 of file MachOObjectFile.cpp.
References getPtr(), Ptr, llvm::MachO::dyld_info_command::rebase_off, and llvm::MachO::dyld_info_command::rebase_size.
Referenced by rebaseTable().
getDyldInfoWeakBindOpcodes()
ArrayRef< uint8_t > MachOObjectFile::getDyldInfoWeakBindOpcodes () const
Definition at line 4933 of file MachOObjectFile.cpp.
References getPtr(), Ptr, llvm::MachO::dyld_info_command::weak_bind_off, and llvm::MachO::dyld_info_command::weak_bind_size.
Referenced by weakBindTable().
getDylibIDLoadCommand()
MachO::dylib_command MachOObjectFile::getDylibIDLoadCommand (const LoadCommandInfo & L) const
Definition at line 4692 of file MachOObjectFile.cpp.
Referenced by readMachOHeader().
getDylinkerCommand()
MachO::dylinker_command MachOObjectFile::getDylinkerCommand (const LoadCommandInfo & L) const
Definition at line 4702 of file MachOObjectFile.cpp.
getDysymtabLoadCommand()
MachO::dysymtab_command MachOObjectFile::getDysymtabLoadCommand () const
Definition at line 4847 of file MachOObjectFile.cpp.
References llvm::MachO::dysymtab_command::cmd, llvm::MachO::dysymtab_command::cmdsize, llvm::MachO::dysymtab_command::extrefsymoff, llvm::MachO::dysymtab_command::extreloff, llvm::MachO::dysymtab_command::iextdefsym, llvm::MachO::dysymtab_command::ilocalsym, llvm::MachO::dysymtab_command::indirectsymoff, llvm::MachO::dysymtab_command::iundefsym, llvm::MachO::dysymtab_command::locreloff, llvm::MachO::dysymtab_command::modtaboff, llvm::MachO::dysymtab_command::nextdefsym, llvm::MachO::dysymtab_command::nextrefsyms, llvm::MachO::dysymtab_command::nextrel, llvm::MachO::dysymtab_command::nindirectsyms, llvm::MachO::dysymtab_command::nlocalsym, llvm::MachO::dysymtab_command::nlocrel, llvm::MachO::dysymtab_command::nmodtab, llvm::MachO::dysymtab_command::ntoc, llvm::MachO::dysymtab_command::nundefsym, and llvm::MachO::dysymtab_command::tocoff.
Referenced by extrel_end(), getRelocation(), locrel_end(), and llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection().
getEncryptionInfoCommand()
MachO::encryption_info_command MachOObjectFile::getEncryptionInfoCommand (const LoadCommandInfo & L) const
Definition at line 4727 of file MachOObjectFile.cpp.
getEncryptionInfoCommand64()
MachO::encryption_info_command_64 MachOObjectFile::getEncryptionInfoCommand64 (const LoadCommandInfo & L) const
Definition at line 4732 of file MachOObjectFile.cpp.
getEntryPointCommand()
MachO::entry_point_command MachOObjectFile::getEntryPointCommand (const LoadCommandInfo & L) const
Definition at line 4722 of file MachOObjectFile.cpp.
getFeatures()
Expected< SubtargetFeatures > llvm::object::MachOObjectFile::getFeatures () const inline override virtual
Implements llvm::object::ObjectFile.
Definition at line 520 of file MachO.h.
getFileFormatName()
StringRef MachOObjectFile::getFileFormatName () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2660 of file MachOObjectFile.cpp.
References llvm::MachO::CPU_TYPE_ARM, llvm::MachO::CPU_TYPE_ARM64, llvm::MachO::CPU_TYPE_ARM64_32, llvm::MachO::CPU_TYPE_I386, llvm::MachO::CPU_TYPE_POWERPC, llvm::MachO::CPU_TYPE_POWERPC64, llvm::MachO::CPU_TYPE_X86_64, getCPUType(), and is64Bit().
getFilesetEntryLoadCommand()
MachO::fileset_entry_command MachOObjectFile::getFilesetEntryLoadCommand (const LoadCommandInfo & L) const
Definition at line 4772 of file MachOObjectFile.cpp.
getFunctionStarts()
SmallVector< uint64_t > MachOObjectFile::getFunctionStarts () const
Definition at line 5266 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::dataoff, Info, and ReadULEB128s().
getHeader()
const MachO::mach_header & MachOObjectFile::getHeader () const
Definition at line 4809 of file MachOObjectFile.cpp.
References Header.
Referenced by checkDylibIdCommand(), checkSymbolTable(), extractSections(), getFirstLoadCommandInfo(), getNextLoadCommandInfo(), getRelocation(), getRelocationOffset(), isRelocatableObject(), parseSegmentLoadCommand(), and readMachOHeader().
getHeader64()
const MachO::mach_header_64 & MachOObjectFile::getHeader64 () const
Definition at line 4813 of file MachOObjectFile.cpp.
References assert(), Header64, and is64Bit().
Referenced by checkSymbolTable(), and llvm::jitlink::MachOLinkGraphBuilder::MachOLinkGraphBuilder().
getHostArch()
Triple MachOObjectFile::getHostArch () static
Definition at line 2847 of file MachOObjectFile.cpp.
References llvm::sys::getDefaultTargetTriple().
getIndirectName()
std::error_code MachOObjectFile::getIndirectName (DataRefImpl Symb, StringRef & Res) const
Definition at line 1806 of file MachOObjectFile.cpp.
References getNValue(), getStringTableData(), getSymbolTableEntryBase(), llvm::MachO::N_INDR, llvm::MachO::N_TYPE, and llvm::object::parse_failed.
getIndirectSymbolTableEntry()
uint32_t MachOObjectFile::getIndirectSymbolTableEntry (const MachO::dysymtab_command & DLC, unsigned Index) const
Definition at line 4818 of file MachOObjectFile.cpp.
References getPtr(), and llvm::Offset.
Referenced by llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection().
getLibraryCount()
uint32_t MachOObjectFile::getLibraryCount () const
Definition at line 2586 of file MachOObjectFile.cpp.
References llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::object::MachOBindEntry::moveNext().
getLibraryShortNameByIndex()
std::error_code MachOObjectFile::getLibraryShortNameByIndex (unsigned Index, StringRef & Res) const
Definition at line 2552 of file MachOObjectFile.cpp.
References D, llvm::StringRef::empty(), guessLibraryShortName(), Name, P, llvm::object::parse_failed, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorBase< Size_T >::size().
getLinkeditDataLoadCommand()
MachO::linkedit_data_command MachOObjectFile::getLinkeditDataLoadCommand (const LoadCommandInfo & L) const
Definition at line 4652 of file MachOObjectFile.cpp.
Referenced by readMachOHeader().
getLinkerOptionLoadCommand()
MachO::linker_option_command MachOObjectFile::getLinkerOptionLoadCommand (const LoadCommandInfo & L) const
Definition at line 4667 of file MachOObjectFile.cpp.
getLinkOptHintsLoadCommand()
MachO::linkedit_data_command MachOObjectFile::getLinkOptHintsLoadCommand () const
Definition at line 4891 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::cmd, llvm::MachO::linkedit_data_command::cmdsize, llvm::MachO::linkedit_data_command::dataoff, and llvm::MachO::linkedit_data_command::datasize.
getMachOFilesetEntryOffset()
size_t llvm::object::MachOObjectFile::getMachOFilesetEntryOffset () const inline
Definition at line 766 of file MachO.h.
Referenced by getFirstLoadCommandInfo(), getNextLoadCommandInfo(), and parseHeader().
getNoteLoadCommand()
MachO::note_command MachOObjectFile::getNoteLoadCommand (const LoadCommandInfo & L) const
Definition at line 4677 of file MachOObjectFile.cpp.
getNValue()
uint64_t MachOObjectFile::getNValue (DataRefImpl Sym) const
Definition at line 1795 of file MachOObjectFile.cpp.
References getSymbol64TableEntry(), getSymbolTableEntry(), is64Bit(), and Sym.
Referenced by getCommonSymbolSizeImpl(), getIndirectName(), and getSymbolFlags().
getPlainRelocationExternal()
bool MachOObjectFile::getPlainRelocationExternal (const MachO::any_relocation_info & RE) const
Definition at line 4553 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), and llvm::MachO::any_relocation_info::r_word1.
Referenced by extractSections(), getAnyRelocationSection(), getRelocationSymbol(), llvm::RuntimeDyldMachO::getRelocationValueRef(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), and llvm::RuntimeDyldMachOX86_64::processRelocationRef().
getPlainRelocationSymbolNum()
unsigned MachOObjectFile::getPlainRelocationSymbolNum (const MachO::any_relocation_info & RE) const
Definition at line 4546 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), and llvm::MachO::any_relocation_info::r_word1.
Referenced by getAnyRelocationSection(), getRelocationSymbol(), and llvm::RuntimeDyldMachOAArch64::processRelocationRef().
getRelocation()
MachO::any_relocation_info MachOObjectFile::getRelocation (DataRefImpl Rel) const
Definition at line 4777 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, llvm::MachO::dysymtab_command::extreloff, getDysymtabLoadCommand(), getHeader(), getPtr(), getSection(), getSection64(), is64Bit(), llvm::MachO::dysymtab_command::locreloff, llvm::MachO::MH_OBJECT, llvm::Offset, P, llvm::MachO::section::reloff, and llvm::MachO::section_64::reloff.
Referenced by extractSections(), llvm::RuntimeDyldMachO::getRelocationEntry(), llvm::jitlink::MachOLinkGraphBuilder::getRelocationInfo(), getRelocationLength(), getRelocationOffset(), getRelocationSection(), getRelocationSymbol(), getRelocationType(), llvm::RuntimeDyldMachO::getRelocationValueRef(), isRelocScattered(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), llvm::RuntimeDyldMachOI386::processRelocationRef(), llvm::RuntimeDyldMachOX86_64::processRelocationRef(), and llvm::RuntimeDyldMachO::processScatteredVANILLA().
getRelocationLength()
uint8_t MachOObjectFile::getRelocationLength (DataRefImpl Rel) const
Definition at line 2385 of file MachOObjectFile.cpp.
References getAnyRelocationLength(), and getRelocation().
getRelocationOffset()
uint64_t MachOObjectFile::getRelocationOffset (DataRefImpl Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2236 of file MachOObjectFile.cpp.
References assert(), getAnyRelocationAddress(), getHeader(), getRelocation(), llvm::MachO::MH_KEXT_BUNDLE, and llvm::MachO::MH_OBJECT.
getRelocationRelocatedSection()
section_iterator MachOObjectFile::getRelocationRelocatedSection (relocation_iterator Rel) const
Definition at line 2591 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, and llvm::object::ObjectFile::SectionRef.
getRelocationSection()
section_iterator MachOObjectFile::getRelocationSection (DataRefImpl Rel) const
Definition at line 2266 of file MachOObjectFile.cpp.
References getAnyRelocationSection(), and getRelocation().
getRelocationSymbol()
symbol_iterator MachOObjectFile::getRelocationSymbol (DataRefImpl Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2245 of file MachOObjectFile.cpp.
References getPlainRelocationExternal(), getPlainRelocationSymbolNum(), getPtr(), getRelocation(), getSymtabLoadCommand(), is64Bit(), isRelocationScattered(), llvm::Offset, Sym, symbol_end(), llvm::object::ObjectFile::SymbolRef, llvm::XCOFF::SymbolTableEntrySize, and llvm::MachO::symtab_command::symoff.
getRelocationType()
uint64_t MachOObjectFile::getRelocationType (DataRefImpl Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2270 of file MachOObjectFile.cpp.
References getAnyRelocationType(), and getRelocation().
Referenced by getRelocationTypeName().
getRelocationTypeName()
void MachOObjectFile::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2275 of file MachOObjectFile.cpp.
References llvm::Triple::aarch64, llvm::Triple::aarch64_32, llvm::Triple::arm, llvm::StringRef::begin(), llvm::StringRef::end(), getArch(), getRelocationType(), llvm::Triple::ppc, llvm::Triple::UnknownArch, llvm::Triple::x86, and llvm::Triple::x86_64.
getRoutinesCommand()
MachO::routines_command MachOObjectFile::getRoutinesCommand (const LoadCommandInfo & L) const
Definition at line 4757 of file MachOObjectFile.cpp.
getRoutinesCommand64()
MachO::routines_command_64 MachOObjectFile::getRoutinesCommand64 (const LoadCommandInfo & L) const
Definition at line 4762 of file MachOObjectFile.cpp.
getRpathCommand()
MachO::rpath_command MachOObjectFile::getRpathCommand (const LoadCommandInfo & L) const
Definition at line 4712 of file MachOObjectFile.cpp.
Referenced by readMachOHeader().
getScatteredRelocationScattered()
bool MachOObjectFile::getScatteredRelocationScattered (const MachO::any_relocation_info & RE) const
Definition at line 4560 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
getScatteredRelocationType()
uint32_t MachOObjectFile::getScatteredRelocationType (const MachO::any_relocation_info & RE) const
Definition at line 4570 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by getAnyRelocationType().
getScatteredRelocationValue()
uint32_t MachOObjectFile::getScatteredRelocationValue (const MachO::any_relocation_info & RE) const
Definition at line 4565 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word1.
Referenced by llvm::RuntimeDyldMachO::processScatteredVANILLA().
getSection() [1/4]
MachO::section MachOObjectFile::getSection (const LoadCommandInfo & L, unsigned Index) const
Definition at line 4627 of file MachOObjectFile.cpp.
References getSectionPtr().
getSection() [2/4]
MachO::section MachOObjectFile::getSection (DataRefImpl DRI) const
Definition at line 4617 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, assert(), and llvm::object::DataRefImpl::d.
getSection() [3/4]
Expected< SectionRef > MachOObjectFile::getSection (StringRef SectionName) const
Definition at line 2025 of file MachOObjectFile.cpp.
References llvm::errorCodeToError(), llvm::object::parse_failed, and llvm::object::ObjectFile::sections().
getSection() [4/4]
Expected< SectionRef > MachOObjectFile::getSection (unsigned SectionIndex) const
Definition at line 2016 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, malformedError(), llvm::object::ObjectFile::SectionRef, and llvm::SmallVectorBase< Size_T >::size().
Referenced by extractSections(), getRelocation(), getSectionAddress(), getSectionAlignment(), getSectionContents(), getSectionSize(), isSectionStripped(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), and section_rel_end().
getSection64() [1/2]
MachO::section_64 MachOObjectFile::getSection64 (const LoadCommandInfo & L, unsigned Index) const
Definition at line 4633 of file MachOObjectFile.cpp.
References getSectionPtr().
getSection64() [2/2]
MachO::section_64 MachOObjectFile::getSection64 (DataRefImpl DRI) const
Definition at line 4622 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, assert(), and llvm::object::DataRefImpl::d.
Referenced by getRelocation(), getSectionAddress(), getSectionAlignment(), getSectionContents(), getSectionSize(), isSectionStripped(), and section_rel_end().
getSectionAddress()
uint64_t MachOObjectFile::getSectionAddress (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1941 of file MachOObjectFile.cpp.
References llvm::MachO::section_64::addr, getSection(), getSection64(), and is64Bit().
getSectionAlignment()
uint64_t MachOObjectFile::getSectionAlignment (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2003 of file MachOObjectFile.cpp.
References llvm::MachO::section::align, llvm::MachO::section_64::align, getSection(), getSection64(), and is64Bit().
getSectionContents() [1/2]
Expected< ArrayRef< uint8_t > > MachOObjectFile::getSectionContents (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1986 of file MachOObjectFile.cpp.
References getSection(), getSection64(), getSectionContents(), is64Bit(), llvm::MachO::section::offset, llvm::MachO::section_64::offset, llvm::Offset, llvm::MachO::section::size, llvm::MachO::section_64::size, and Size.
getSectionContents() [2/2]
ArrayRef< uint8_t > MachOObjectFile::getSectionContents (uint32_t Offset, uint64_t Size) const
Definition at line 1980 of file MachOObjectFile.cpp.
References llvm::object::Binary::getData(), llvm::Offset, Size, and substr().
Referenced by extractSections(), and getSectionContents().
getSectionFinalSegmentName()
StringRef MachOObjectFile::getSectionFinalSegmentName (DataRefImpl Sec) const
Definition at line 4517 of file MachOObjectFile.cpp.
References llvm::ArrayRef< T >::data(), getSectionRawFinalSegmentName(), and parseSegmentOrSectionName().
Referenced by llvm::object::BindRebaseSegInfo::BindRebaseSegInfo(), llvm::orc::getMachOObjectFileSymbolInfo(), and isSectionBitcode().
getSectionID()
unsigned MachOObjectFile::getSectionID (SectionRef Sec) const
Definition at line 2150 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, and llvm::object::SectionRef::getRawDataRefImpl().
getSectionIndex()
uint64_t MachOObjectFile::getSectionIndex (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1947 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, and llvm::object::DataRefImpl::d.
getSectionName()
Expected< StringRef > MachOObjectFile::getSectionName (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1936 of file MachOObjectFile.cpp.
References llvm::ArrayRef< T >::data(), getSectionRawName(), and parseSegmentOrSectionName().
Referenced by llvm::orc::getMachOObjectFileSymbolInfo(), isDebugSection(), and isSectionBitcode().
getSectionRawFinalSegmentName()
ArrayRef< char > MachOObjectFile::getSectionRawFinalSegmentName (DataRefImpl Sec) const
Definition at line 4531 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, assert(), llvm::sampleprof::Base, and llvm::object::DataRefImpl::d.
Referenced by getSectionFinalSegmentName().
getSectionRawName()
ArrayRef< char > MachOObjectFile::getSectionRawName (DataRefImpl Sec) const
Definition at line 4523 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, assert(), llvm::sampleprof::Base, and llvm::object::DataRefImpl::d.
Referenced by getSectionName().
getSectionSize()
uint64_t MachOObjectFile::getSectionSize (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1951 of file MachOObjectFile.cpp.
References llvm::MachO::section::flags, llvm::MachO::section_64::flags, llvm::object::Binary::getData(), getSection(), getSection64(), is64Bit(), llvm::MachO::section::offset, llvm::MachO::section_64::offset, llvm::MachO::S_GB_ZEROFILL, llvm::MachO::S_ZEROFILL, llvm::MachO::SECTION_TYPE, llvm::StringRef::size(), llvm::MachO::section::size, and llvm::MachO::section_64::size.
getSectionType()
unsigned MachOObjectFile::getSectionType (SectionRef Sec) const
Definition at line 1789 of file MachOObjectFile.cpp.
References llvm::object::SectionRef::getRawDataRefImpl(), getSectionFlags(), and llvm::MachO::SECTION_TYPE.
Referenced by llvm::orc::getMachOObjectFileSymbolInfo().
getSegment64LoadCommand()
MachO::segment_command_64 MachOObjectFile::getSegment64LoadCommand (const LoadCommandInfo & L) const
Definition at line 4662 of file MachOObjectFile.cpp.
Referenced by llvm::object::MachOAbstractFixupEntry::MachOAbstractFixupEntry().
getSegmentContents() [1/2]
ArrayRef< uint8_t > MachOObjectFile::getSegmentContents (size_t SegmentIndex) const
Definition at line 2129 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::C, llvm::MachO::load_command::cmd, Idx, and load_commands().
getSegmentContents() [2/2]
ArrayRef< uint8_t > MachOObjectFile::getSegmentContents (StringRef SegmentName) const
Return the raw contents of an entire segment.
Definition at line 2107 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::C, llvm::MachO::load_command::cmd, llvm::ArrayRef< T >::empty(), and load_commands().
getSegmentLoadCommand()
MachO::segment_command MachOObjectFile::getSegmentLoadCommand (const LoadCommandInfo & L) const
Definition at line 4657 of file MachOObjectFile.cpp.
Referenced by llvm::object::MachOAbstractFixupEntry::MachOAbstractFixupEntry().
getSourceVersionCommand()
MachO::source_version_command MachOObjectFile::getSourceVersionCommand (const LoadCommandInfo & L) const
Definition at line 4717 of file MachOObjectFile.cpp.
getStringTableData()
StringRef MachOObjectFile::getStringTableData () const
Definition at line 5289 of file MachOObjectFile.cpp.
References llvm::object::Binary::getData(), getSymtabLoadCommand(), llvm::MachO::symtab_command::stroff, llvm::MachO::symtab_command::strsize, and llvm::StringRef::substr().
Referenced by getIndirectName(), and getSymbolName().
getSubClientCommand()
MachO::sub_client_command MachOObjectFile::getSubClientCommand (const LoadCommandInfo & L) const
Definition at line 4752 of file MachOObjectFile.cpp.
Referenced by readMachOHeader().
getSubFrameworkCommand()
MachO::sub_framework_command MachOObjectFile::getSubFrameworkCommand (const LoadCommandInfo & L) const
Definition at line 4737 of file MachOObjectFile.cpp.
Referenced by readMachOHeader().
getSubLibraryCommand()
MachO::sub_library_command MachOObjectFile::getSubLibraryCommand (const LoadCommandInfo & L) const
Definition at line 4747 of file MachOObjectFile.cpp.
getSubUmbrellaCommand()
MachO::sub_umbrella_command MachOObjectFile::getSubUmbrellaCommand (const LoadCommandInfo & L) const
Definition at line 4742 of file MachOObjectFile.cpp.
getSymbol64TableEntry()
MachO::nlist_64 MachOObjectFile::getSymbol64TableEntry (DataRefImpl DRI) const
Definition at line 4646 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::p, and P.
Referenced by checkSymbolTable(), and getNValue().
getSymbolAddress()
Expected< uint64_t > MachOObjectFile::getSymbolAddress (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1824 of file MachOObjectFile.cpp.
References llvm::object::ObjectFile::getSymbolValue(), and Sym.
getSymbolAlignment()
uint32_t MachOObjectFile::getSymbolAlignment (DataRefImpl Symb) const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 1828 of file MachOObjectFile.cpp.
References llvm::cantFail(), llvm::MachO::GET_COMM_ALIGN(), getSymbolFlags(), getSymbolTableEntryBase(), and llvm::object::BasicSymbolRef::SF_Common.
getSymbolByIndex()
symbol_iterator MachOObjectFile::getSymbolByIndex (unsigned Index) const
Definition at line 2621 of file MachOObjectFile.cpp.
References getPtr(), getSymtabLoadCommand(), is64Bit(), llvm::MachO::symtab_command::nsyms, llvm::object::DataRefImpl::p, llvm::report_fatal_error(), llvm::object::ObjectFile::SymbolRef, llvm::XCOFF::SymbolTableEntrySize, and llvm::MachO::symtab_command::symoff.
Referenced by llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), and symbol_begin().
getSymbolFlags()
Expected< uint32_t > MachOObjectFile::getSymbolFlags (DataRefImpl Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 1867 of file MachOObjectFile.cpp.
References getNValue(), getSymbolTableEntryBase(), llvm::MachO::N_ABS, llvm::MachO::N_ARM_THUMB_DEF, llvm::MachO::N_EXT, llvm::MachO::N_INDR, llvm::MachO::N_PEXT, llvm::MachO::N_STAB, llvm::MachO::N_TYPE, llvm::MachO::N_UNDF, llvm::MachO::N_WEAK_DEF, llvm::MachO::N_WEAK_REF, llvm::object::BasicSymbolRef::SF_Absolute, llvm::object::BasicSymbolRef::SF_Common, llvm::object::BasicSymbolRef::SF_Exported, llvm::object::BasicSymbolRef::SF_FormatSpecific, llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_Hidden, llvm::object::BasicSymbolRef::SF_Indirect, llvm::object::BasicSymbolRef::SF_None, llvm::object::BasicSymbolRef::SF_Thumb, llvm::object::BasicSymbolRef::SF_Undefined, and llvm::object::BasicSymbolRef::SF_Weak.
Referenced by getSymbolAlignment().
getSymbolIndex()
uint64_t MachOObjectFile::getSymbolIndex (DataRefImpl Symb) const
Definition at line 2633 of file MachOObjectFile.cpp.
References getPtr(), getSymtabLoadCommand(), is64Bit(), llvm::object::DataRefImpl::p, llvm::report_fatal_error(), llvm::XCOFF::SymbolTableEntrySize, and llvm::MachO::symtab_command::symoff.
Referenced by getSymbolName(), and getSymbolSection().
getSymbolName()
Expected< StringRef > MachOObjectFile::getSymbolName (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1774 of file MachOObjectFile.cpp.
References llvm::object::Binary::getData(), getStringTableData(), getSymbolIndex(), getSymbolTableEntryBase(), and malformedError().
getSymbolSection()
Expected< section_iterator > MachOObjectFile::getSymbolSection (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1911 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, getSymbolIndex(), getSymbolTableEntryBase(), malformedError(), section_end(), llvm::object::ObjectFile::SectionRef, and llvm::SmallVectorBase< Size_T >::size().
Referenced by getSymbolType().
getSymbolSectionID()
unsigned MachOObjectFile::getSymbolSectionID (SymbolRef Symb) const
Definition at line 1926 of file MachOObjectFile.cpp.
References getSymbolTableEntryBase(), and Sym.
getSymbolTableEntry()
MachO::nlist MachOObjectFile::getSymbolTableEntry (DataRefImpl DRI) const
Definition at line 4640 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::p, and P.
Referenced by checkSymbolTable(), and getNValue().
getSymbolType()
Expected< SymbolRef::Type > MachOObjectFile::getSymbolType (DataRefImpl Symb) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1842 of file MachOObjectFile.cpp.
References getSymbolSection(), getSymbolTableEntryBase(), llvm::object::SectionRef::isBSS(), llvm::object::SectionRef::isData(), llvm::MachO::N_SECT, llvm::MachO::N_STAB, llvm::MachO::N_TYPE, llvm::MachO::N_UNDF, section_end(), llvm::object::SymbolRef::ST_Data, llvm::object::SymbolRef::ST_Debug, llvm::object::SymbolRef::ST_Function, llvm::object::SymbolRef::ST_Other, llvm::object::SymbolRef::ST_Unknown, and llvm::Expected< T >::takeError().
getSymtabLoadCommand()
MachO::symtab_command MachOObjectFile::getSymtabLoadCommand () const
Definition at line 4832 of file MachOObjectFile.cpp.
References llvm::MachO::symtab_command::cmd, llvm::MachO::symtab_command::cmdsize, llvm::MachO::symtab_command::nsyms, llvm::MachO::symtab_command::stroff, llvm::MachO::symtab_command::strsize, and llvm::MachO::symtab_command::symoff.
Referenced by checkSymbolTable(), getRelocationSymbol(), getStringTableData(), getSymbolByIndex(), getSymbolIndex(), symbol_begin(), and symbol_end().
getThreadCommand()
MachO::thread_command MachOObjectFile::getThreadCommand (const LoadCommandInfo & L) const
Definition at line 4767 of file MachOObjectFile.cpp.
getUuid()
ArrayRef< uint8_t > MachOObjectFile::getUuid () const
Definition at line 5281 of file MachOObjectFile.cpp.
References offsetof, and Ptr.
getUuidCommand()
MachO::uuid_command MachOObjectFile::getUuidCommand (const LoadCommandInfo & L) const
Definition at line 4707 of file MachOObjectFile.cpp.
Referenced by readMachOHeader().
getValidArchs()
ArrayRef< StringRef > MachOObjectFile::getValidArchs () static
Definition at line 2856 of file MachOObjectFile.cpp.
Referenced by isValidArch().
getVersionMinLoadCommand()
MachO::version_min_command MachOObjectFile::getVersionMinLoadCommand (const LoadCommandInfo & L) const
Definition at line 4672 of file MachOObjectFile.cpp.
Referenced by constructTriples().
getVersionMinMajor()
static uint32_t llvm::object::MachOObjectFile::getVersionMinMajor (MachO::version_min_command & C, bool SDK) inline static
Definition at line 773 of file MachO.h.
References llvm::CallingConv::C.
getVersionMinMinor()
static uint32_t llvm::object::MachOObjectFile::getVersionMinMinor (MachO::version_min_command & C, bool SDK) inline static
Definition at line 779 of file MachO.h.
References llvm::CallingConv::C.
getVersionMinUpdate()
static uint32_t llvm::object::MachOObjectFile::getVersionMinUpdate (MachO::version_min_command & C, bool SDK) inline static
Definition at line 785 of file MachO.h.
References llvm::CallingConv::C.
getVersionString()
static std::string llvm::object::MachOObjectFile::getVersionString (uint32_t version) inline static
Definition at line 820 of file MachO.h.
guessLibraryShortName()
StringRef MachOObjectFile::guessLibraryShortName (StringRef Name, bool & isFramework, StringRef & Suffix) static
Definition at line 2426 of file MachOObjectFile.cpp.
References F, Idx, llvm::Lib, Name, llvm::StringRef::npos, llvm::StringRef::rfind(), llvm::StringRef::size(), and llvm::StringRef::slice().
Referenced by getLibraryShortNameByIndex().
hasPageZeroSegment()
bool llvm::object::MachOObjectFile::hasPageZeroSegment () const inline
Definition at line 764 of file MachO.h.
Referenced by llvm::object::BindRebaseSegInfo::BindRebaseSegInfo().
is64Bit()
bool MachOObjectFile::is64Bit () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 5294 of file MachOObjectFile.cpp.
References llvm::object::Binary::getMachOType(), and llvm::object::Binary::getType().
Referenced by bindTable(), checkDysymtabCommand(), checkSymbolTable(), checkSymtabCommand(), getBytesInAddress(), getFileFormatName(), getFirstLoadCommandInfo(), getHeader64(), getNextLoadCommandInfo(), getNValue(), getRelocation(), getRelocationSymbol(), getSectionAddress(), getSectionAlignment(), getSectionContents(), getSectionSize(), getSymbolByIndex(), getSymbolIndex(), isSectionStripped(), lazyBindTable(), moveSymbolNext(), llvm::RuntimeDyldMachO::populateIndirectSymbolPointersSection(), rebaseTable(), section_rel_end(), symbol_end(), and weakBindTable().
isDebugSection()
bool MachOObjectFile::isDebugSection (DataRefImpl Sec) const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 2061 of file MachOObjectFile.cpp.
References llvm::consumeError(), llvm::Expected< T >::get(), getSectionName(), and llvm::Expected< T >::takeError().
isMachOPairedReloc()
bool MachOObjectFile::isMachOPairedReloc (uint64_t RelocType, uint64_t Arch) static
Definition at line 5403 of file MachOObjectFile.cpp.
References llvm::Triple::aarch64, llvm::Triple::arm, llvm::MachO::ARM64_RELOC_SUBTRACTOR, llvm::MachO::ARM_RELOC_HALF, llvm::MachO::ARM_RELOC_HALF_SECTDIFF, llvm::MachO::ARM_RELOC_LOCAL_SECTDIFF, llvm::MachO::ARM_RELOC_SECTDIFF, llvm::MachO::GENERIC_RELOC_LOCAL_SECTDIFF, llvm::MachO::GENERIC_RELOC_SECTDIFF, llvm::Triple::thumb, llvm::Triple::x86, llvm::Triple::x86_64, and llvm::MachO::X86_64_RELOC_SUBTRACTOR.
isRelocatableObject()
bool MachOObjectFile::isRelocatableObject () const override virtual
True if this is a relocatable object (.o/.obj).
Implements llvm::object::ObjectFile.
Definition at line 5311 of file MachOObjectFile.cpp.
References llvm::MachO::mach_header::filetype, getHeader(), and llvm::MachO::MH_OBJECT.
Referenced by llvm::jitlink::MachOLinkGraphBuilder::buildGraph().
isRelocationScattered()
bool MachOObjectFile::isRelocationScattered (const MachO::any_relocation_info & RE) const
Definition at line 4539 of file MachOObjectFile.cpp.
References llvm::MachO::CPU_TYPE_X86_64, getCPUType(), getPlainRelocationAddress(), and llvm::MachO::R_SCATTERED.
Referenced by extractSections(), getAnyRelocationAddress(), getAnyRelocationLength(), getAnyRelocationPCRel(), getAnyRelocationSection(), getAnyRelocationType(), getRelocationSymbol(), isRelocScattered(), llvm::RuntimeDyldMachOAArch64::processRelocationRef(), llvm::RuntimeDyldMachOARM::processRelocationRef(), llvm::RuntimeDyldMachOI386::processRelocationRef(), and llvm::RuntimeDyldMachOX86_64::processRelocationRef().
isSectionBitcode()
bool MachOObjectFile::isSectionBitcode (DataRefImpl Sec) const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 2161 of file MachOObjectFile.cpp.
References getSectionFinalSegmentName(), and getSectionName().
isSectionBSS()
bool MachOObjectFile::isSectionBSS (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2053 of file MachOObjectFile.cpp.
References getSectionFlags(), llvm::MachO::S_ATTR_PURE_INSTRUCTIONS, llvm::MachO::S_GB_ZEROFILL, llvm::MachO::S_ZEROFILL, and llvm::MachO::SECTION_TYPE.
isSectionCompressed()
bool MachOObjectFile::isSectionCompressed (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2036 of file MachOObjectFile.cpp.
isSectionData()
bool MachOObjectFile::isSectionData (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2045 of file MachOObjectFile.cpp.
References getSectionFlags(), llvm::MachO::S_ATTR_PURE_INSTRUCTIONS, llvm::MachO::S_GB_ZEROFILL, llvm::MachO::S_ZEROFILL, and llvm::MachO::SECTION_TYPE.
isSectionStripped()
bool MachOObjectFile::isSectionStripped (DataRefImpl Sec) const override virtual
When dsymutil generates the companion file, it strips all unnecessary sections (e.g.
everything in the _TEXT segment) by omitting their body and setting the offset in their corresponding load command to zero.
While the load command itself is valid, reading the section corresponds to reading the number of bytes specified in the load command, starting from offset 0 (i.e. the Mach-O header at the beginning of the file).
Reimplemented from llvm::object::ObjectFile.
Definition at line 2168 of file MachOObjectFile.cpp.
References getSection(), getSection64(), is64Bit(), and llvm::MachO::section_64::offset.
isSectionText()
bool MachOObjectFile::isSectionText (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2040 of file MachOObjectFile.cpp.
References getSectionFlags(), and llvm::MachO::S_ATTR_PURE_INSTRUCTIONS.
isSectionVirtual()
bool MachOObjectFile::isSectionVirtual (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2154 of file MachOObjectFile.cpp.
References getSectionFlags(), llvm::MachO::S_GB_ZEROFILL, llvm::MachO::S_ZEROFILL, and llvm::MachO::SECTION_TYPE.
isValidArch()
bool MachOObjectFile::isValidArch (StringRef ArchFlag) static
Definition at line 2851 of file MachOObjectFile.cpp.
References getValidArchs(), and llvm::is_contained().
lazyBindTable()
iterator_range< bind_iterator > MachOObjectFile::lazyBindTable (Error & Err)
For use iterating over all lazy bind table entries.
Definition at line 4478 of file MachOObjectFile.cpp.
References bindTable(), getDyldInfoLazyBindOpcodes(), is64Bit(), and llvm::object::MachOBindEntry::Lazy.
load_commands()
iterator_range< MachOObjectFile::load_command_iterator > MachOObjectFile::load_commands () const
Definition at line 4512 of file MachOObjectFile.cpp.
References begin_load_commands(), end_load_commands(), and llvm::make_range().
Referenced by constructTriples(), getSegmentContents(), llvm::object::MachOAbstractFixupEntry::MachOAbstractFixupEntry(), and readMachOHeader().
locrel_begin()
relocation_iterator MachOObjectFile::locrel_begin () const
Definition at line 2215 of file MachOObjectFile.cpp.
References llvm::object::ObjectFile::RelocationRef.
locrel_end()
relocation_iterator MachOObjectFile::locrel_end () const
Definition at line 2223 of file MachOObjectFile.cpp.
References getDysymtabLoadCommand(), llvm::MachO::dysymtab_command::nlocrel, and llvm::object::ObjectFile::RelocationRef.
mapDebugSectionName()
StringRef MachOObjectFile::mapDebugSectionName (StringRef Name) const override virtual
Maps a debug section name to a standard DWARF section name.
Reimplemented from llvm::object::ObjectFile.
Definition at line 5342 of file MachOObjectFile.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), and Name.
mapReflectionSectionNameToEnumValue()
llvm::binaryformat::Swift5ReflectionSectionKind MachOObjectFile::mapReflectionSectionNameToEnumValue (StringRef SectionName) const override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 5392 of file MachOObjectFile.cpp.
References llvm::StringSwitch< T, R >::Default(), and llvm::binaryformat::unknown.
moveRelocationNext()
void MachOObjectFile::moveRelocationNext (DataRefImpl & Rel) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2232 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::b, and llvm::object::DataRefImpl::d.
moveSectionNext()
void MachOObjectFile::moveSectionNext (DataRefImpl & Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 1932 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, and llvm::object::DataRefImpl::d.
moveSymbolNext()
void MachOObjectFile::moveSymbolNext (DataRefImpl & Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 1767 of file MachOObjectFile.cpp.
References is64Bit(), llvm::object::DataRefImpl::p, and llvm::XCOFF::SymbolTableEntrySize.
ReadULEB128s()
void MachOObjectFile::ReadULEB128s (uint64_t Index, SmallVectorImpl< uint64_t > & Out) const
Definition at line 5299 of file MachOObjectFile.cpp.
References llvm::object::Binary::getData(), llvm::DataExtractor::getULEB128(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by getFunctionStarts().
RebaseEntryCheckSegAndOffsets()
const char * llvm::object::MachOObjectFile::RebaseEntryCheckSegAndOffsets (int32_t SegIndex, uint64_t SegOffset, uint8_t PointerSize, uint32_t Count = 1, uint32_t Skip = 0) const inline
Definition at line 591 of file MachO.h.
Referenced by llvm::object::MachORebaseEntry::moveNext().
rebaseTable() [1/2]
iterator_range< rebase_iterator > MachOObjectFile::rebaseTable (Error & Err)
For use iterating over all rebase table entries.
Definition at line 3813 of file MachOObjectFile.cpp.
References getDyldInfoRebaseOpcodes(), is64Bit(), and rebaseTable().
Referenced by rebaseTable().
rebaseTable() [2/2]
iterator_range< rebase_iterator > MachOObjectFile::rebaseTable (Error & Err, MachOObjectFile * O, ArrayRef< uint8_t > Opcodes, bool is64) static
For use examining rebase opcodes in a MachOObjectFile.
Definition at line 3800 of file MachOObjectFile.cpp.
References llvm::make_range().
section_begin()
section_iterator MachOObjectFile::section_begin () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2645 of file MachOObjectFile.cpp.
References llvm::object::ObjectFile::SectionRef.
Referenced by llvm::RuntimeDyldMachO::getSectionByAddress().
section_end()
section_iterator MachOObjectFile::section_end () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2650 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, llvm::object::ObjectFile::SectionRef, and llvm::SmallVectorBase< Size_T >::size().
Referenced by getAnyRelocationSection(), llvm::RuntimeDyldMachO::getSectionByAddress(), getSymbolSection(), getSymbolType(), and llvm::RuntimeDyldMachO::processScatteredVANILLA().
section_rel_begin() [1/2]
relocation_iterator MachOObjectFile::section_rel_begin (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2174 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, and llvm::object::ObjectFile::RelocationRef.
Referenced by extractSections(), and section_rel_begin().
section_rel_begin() [2/2]
relocation_iterator MachOObjectFile::section_rel_begin (unsigned Index) const
Definition at line 2889 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, and section_rel_begin().
section_rel_end() [1/2]
relocation_iterator MachOObjectFile::section_rel_end (DataRefImpl Sec) const override virtual
Implements llvm::object::ObjectFile.
Definition at line 2182 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, getSection(), getSection64(), is64Bit(), llvm::MachO::section::nreloc, llvm::MachO::section_64::nreloc, and llvm::object::ObjectFile::RelocationRef.
Referenced by extractSections(), and section_rel_end().
section_rel_end() [2/2]
relocation_iterator MachOObjectFile::section_rel_end (unsigned Index) const
Definition at line 2895 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, and section_rel_end().
symbol_begin()
basic_symbol_iterator MachOObjectFile::symbol_begin () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 2597 of file MachOObjectFile.cpp.
References getSymbolByIndex(), getSymtabLoadCommand(), llvm::MachO::symtab_command::nsyms, and llvm::object::ObjectFile::SymbolRef.
symbol_end()
basic_symbol_iterator MachOObjectFile::symbol_end () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 2606 of file MachOObjectFile.cpp.
References getPtr(), getSymtabLoadCommand(), is64Bit(), llvm::MachO::symtab_command::nsyms, llvm::Offset, llvm::object::DataRefImpl::p, llvm::object::ObjectFile::SymbolRef, llvm::XCOFF::SymbolTableEntrySize, and llvm::MachO::symtab_command::symoff.
Referenced by getRelocationSymbol().
weakBindTable()
iterator_range< bind_iterator > MachOObjectFile::weakBindTable (Error & Err)
For use iterating over all weak bind table entries.
Definition at line 4483 of file MachOObjectFile.cpp.
References bindTable(), getDyldInfoWeakBindOpcodes(), is64Bit(), and llvm::object::MachOBindEntry::Weak.
Member Data Documentation
Header
MachO::mach_header llvm::object::MachOObjectFile::Header
Definition at line 849 of file MachO.h.
Referenced by getArchTriple(), getChainedFixupsSegments(), getDyldChainedFixupTargets(), and getHeader().
Header64
MachO::mach_header_64 llvm::object::MachOObjectFile::Header64
Definition at line 848 of file MachO.h.
Referenced by getHeader64().
The documentation for this class was generated from the following files:
include/llvm/Object/MachO.h
lib/Object/MachOObjectFile.cpp