LLVM: llvm::ModuleSlotTracker Class Reference
llvm::ModuleSlotTracker Class Reference
Manage lifetime of a slot tracker for printing IR.
#include "llvm/IR/ModuleSlotTracker.h"
Public Types
using MachineMDNodeListType = std::vector< std::pair< unsigned, const MDNode * > >
Public Member Functions
ModuleSlotTracker (SlotTracker &Machine, const Module *M, const Function *F=nullptr)
Wrap a preinitialized SlotTracker.
ModuleSlotTracker (const Module *M, bool ShouldInitializeAllMetadata=true)
Construct a slot tracker from a module.
virtual ~ModuleSlotTracker ()
Destructor to clean up storage.
SlotTracker * getMachine ()
Lazily creates a slot tracker.
const Module * getModule () const
const Function * getCurrentFunction () const
void incorporateFunction (const Function &F)
Incorporate the given function.
int getLocalSlot (const Value *V)
Return the slot number of the specified local value.
void setProcessHook (std::function< void(AbstractSlotTrackerStorage *, const Module *, bool)>)
void setProcessHook (std::function< void(AbstractSlotTrackerStorage *, const Function *, bool)>)
void collectMDNodes (MachineMDNodeListType &L, unsigned LB, unsigned UB) const
Detailed Description
Manage lifetime of a slot tracker for printing IR.
Wrapper around the SlotTracker used internally by AsmWriter. This class allows callers to share the cost of incorporating the metadata in a module or a function.
If the IR changes from underneath ModuleSlotTracker, strings like "<badref>" will be printed, or, worse, the wrong slots entirely.
Definition at line 44 of file ModuleSlotTracker.h.
Member Typedef Documentation
MachineMDNodeListType
using llvm::ModuleSlotTracker::MachineMDNodeListType = std::vector<std::pair<unsigned, const MDNode *> >
Definition at line 101 of file ModuleSlotTracker.h.
Constructor & Destructor Documentation
ModuleSlotTracker() [1/2]
ModuleSlotTracker::ModuleSlotTracker (SlotTracker & Machine, const Module * M, const Function * F = nullptr)
Wrap a preinitialized SlotTracker.
Definition at line 869 of file AsmWriter.cpp.
ModuleSlotTracker() [2/2]
ModuleSlotTracker::ModuleSlotTracker (const Module * M, bool ShouldInitializeAllMetadata = true) explicit
Construct a slot tracker from a module.
If M is nullptr, uses a null slot tracker. Otherwise, initializes a slot tracker, and initializes all metadata slots. ShouldInitializeAllMetadata defaults to true because this is expected to be shared between multiple callers, and otherwise MDNode references will not match up.
Definition at line 873 of file AsmWriter.cpp.
~ModuleSlotTracker()
ModuleSlotTracker::~ModuleSlotTracker () virtual default
Destructor to clean up storage.
Member Function Documentation
collectMDNodes()
void ModuleSlotTracker::collectMDNodes (MachineMDNodeListType & L, unsigned LB, unsigned UB) const
Definition at line 5123 of file AsmWriter.cpp.
References I, and llvm::make_range().
Referenced by llvm::MachineModuleSlotTracker::collectMachineMDNodes().
getCurrentFunction()
const Function * llvm::ModuleSlotTracker::getCurrentFunction () const inline
Definition at line 81 of file ModuleSlotTracker.h.
References F.
Referenced by printIRBlockReference(), and llvm::MIRFormatter::printIRValue().
getLocalSlot()
int ModuleSlotTracker::getLocalSlot (const Value * V)
Return the slot number of the specified local value.
A function that defines this value should be incorporated prior to calling this method. Return -1 if the value is not in the function's SlotTracker.
Definition at line 909 of file AsmWriter.cpp.
References assert(), and llvm::SlotTracker::getLocalSlot().
Referenced by initSlots2BasicBlocks(), mapValueToSlot(), printIRBlockReference(), llvm::MIRFormatter::printIRValue(), and llvm::MachineBasicBlock::printName().
getMachine()
SlotTracker * ModuleSlotTracker::getMachine ()
Lazily creates a slot tracker.
Definition at line 880 of file AsmWriter.cpp.
References llvm::SlotTracker::setProcessHook().
Referenced by incorporateFunction(), llvm::Value::print(), llvm::DPValue::print(), llvm::DPMarker::print(), llvm::NamedMDNode::print(), llvm::Value::printAsOperand(), printAsOperandImpl(), and printMetadataImpl().
getModule()
const Module * llvm::ModuleSlotTracker::getModule () const inline
Definition at line 80 of file ModuleSlotTracker.h.
Referenced by llvm::Value::printAsOperand(), and printAsOperandImpl().
incorporateFunction()
void ModuleSlotTracker::incorporateFunction (const Function & F)
Incorporate the given function.
Purge the currently incorporated function and incorporate F. If F is currently incorporated, this is a no-op.
Definition at line 895 of file AsmWriter.cpp.
References F, getMachine(), llvm::SlotTracker::incorporateFunction(), and llvm::SlotTracker::purgeFunction().
Referenced by initSlots2BasicBlocks(), initSlots2Values(), llvm::MIRPrinter::print(), llvm::Value::print(), llvm::MachineInstr::print(), llvm::MachineFunction::print(), llvm::MachineBasicBlock::print(), llvm::DPValue::print(), llvm::DPMarker::print(), printIRBlockReference(), printMemOperand(), and llvm::MachineBasicBlock::printName().
setProcessHook() [1/2]
void ModuleSlotTracker::setProcessHook (std::function< void(AbstractSlotTrackerStorage *, const Function *, bool)> Fn)
Definition at line 920 of file AsmWriter.cpp.
setProcessHook() [2/2]
void ModuleSlotTracker::setProcessHook (std::function< void(AbstractSlotTrackerStorage *, const Module *, bool)> Fn)
Definition at line 914 of file AsmWriter.cpp.
Referenced by llvm::MachineModuleSlotTracker::MachineModuleSlotTracker().
The documentation for this class was generated from the following files:
include/llvm/IR/ModuleSlotTracker.h
lib/IR/AsmWriter.cpp