LLVM: llvm::DebuginfodFetcher Class Reference
llvm::DebuginfodFetcher Class Reference
#include "llvm/Debuginfod/BuildIDFetcher.h"
Public Member Functions
DebuginfodFetcher (std::vector< std::string > DebugFileDirectories)
virtual ~DebuginfodFetcher ()=default
std::optional< std::string > fetch (object::BuildIDRef BuildID) const override
Fetches the given Build ID using debuginfod and returns a local path to the resulting file.
Public Member Functions inherited from llvm::object::BuildIDFetcher
BuildIDFetcher (std::vector< std::string > DebugFileDirectories)
virtual ~BuildIDFetcher ()=default
virtual std::optional< std::string > fetch (BuildIDRef BuildID) const
Returns the path to the debug file with the given build ID.
Detailed Description
Definition at line 23 of file BuildIDFetcher.h.
Constructor & Destructor Documentation
DebuginfodFetcher()
llvm::DebuginfodFetcher::DebuginfodFetcher (std::vector< std::string > DebugFileDirectories) inline
Definition at line 25 of file BuildIDFetcher.h.
~DebuginfodFetcher()
virtual llvm::DebuginfodFetcher::~DebuginfodFetcher () virtual default
Member Function Documentation
fetch()
std::optional< std::string > DebuginfodFetcher::fetch (object::BuildIDRef BuildID) const override virtual
Fetches the given Build ID using debuginfod and returns a local path to the resulting file.
Reimplemented from llvm::object::BuildIDFetcher.
Definition at line 22 of file BuildIDFetcher.cpp.
References llvm::consumeError(), llvm::getCachedOrDownloadDebuginfo(), and llvm::Expected< T >::takeError().
The documentation for this class was generated from the following files:
include/llvm/Debuginfod/BuildIDFetcher.h
lib/Debuginfod/BuildIDFetcher.cpp