LLVM: llvm::RISCVTargetELFStreamer Class Reference
llvm::RISCVTargetELFStreamer Class Reference
#include "Target/RISCV/MCTargetDesc/RISCVELFStreamer.h"
Public Member Functions
RISCVELFStreamer & getStreamer ()
RISCVTargetELFStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
void emitDirectiveOptionPush () override
void emitDirectiveOptionPop () override
void emitDirectiveOptionPIC () override
void emitDirectiveOptionNoPIC () override
void emitDirectiveOptionRVC () override
void emitDirectiveOptionNoRVC () override
void emitDirectiveOptionRelax () override
void emitDirectiveOptionNoRelax () override
void emitDirectiveVariantCC (MCSymbol &Symbol) override
void finish () override
Public Member Functions inherited from llvm::RISCVTargetStreamer
RISCVTargetStreamer (MCStreamer &S)
void finish () override
virtual void reset ()
virtual void emitDirectiveOptionPush ()
virtual void emitDirectiveOptionPop ()
virtual void emitDirectiveOptionPIC ()
virtual void emitDirectiveOptionNoPIC ()
virtual void emitDirectiveOptionRVC ()
virtual void emitDirectiveOptionNoRVC ()
virtual void emitDirectiveOptionRelax ()
virtual void emitDirectiveOptionNoRelax ()
virtual void emitDirectiveOptionArch (ArrayRef< RISCVOptionArchArg > Args)
virtual void emitDirectiveVariantCC (MCSymbol &Symbol)
virtual void emitAttribute (unsigned Attribute, unsigned Value)
virtual void finishAttributeSection ()
virtual void emitTextAttribute (unsigned Attribute, StringRef String)
virtual void emitIntTextAttribute (unsigned Attribute, unsigned IntValue, StringRef StringValue)
void emitTargetAttributes (const MCSubtargetInfo &STI, bool EmitStackAlign)
void setTargetABI (RISCVABI::ABI ABI)
RISCVABI::ABI getTargetABI () const
Public Member Functions inherited from llvm::MCTargetStreamer
MCTargetStreamer (MCStreamer &S)
virtual ~MCTargetStreamer ()
MCStreamer & getStreamer ()
virtual void emitLabel (MCSymbol *Symbol)
virtual void emitAssignment (MCSymbol *Symbol, const MCExpr *Value)
virtual void prettyPrintAsm (MCInstPrinter &InstPrinter, uint64_t Address, const MCInst &Inst, const MCSubtargetInfo &STI, raw_ostream &OS)
virtual void emitDwarfFileDirective (StringRef Directive)
virtual void changeSection (const MCSection *CurSection, MCSection *Section, const MCExpr *SubSection, raw_ostream &OS)
Update streamer for a new active section.
virtual void emitValue (const MCExpr *Value)
virtual void emitRawBytes (StringRef Data)
Emit the bytes in Data into the output.
virtual void emitConstantPools ()
virtual void finish ()
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer & Streamer
Detailed Description
Definition at line 44 of file RISCVELFStreamer.h.
Constructor & Destructor Documentation
RISCVTargetELFStreamer()
RISCVTargetELFStreamer::RISCVTargetELFStreamer (MCStreamer & S, const MCSubtargetInfo & STI)
Definition at line 32 of file RISCVELFStreamer.cpp.
References llvm::RISCVABI::computeTargetABI(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getBackend(), llvm::MCSubtargetInfo::getFeatureBits(), getStreamer(), llvm::MCSubtargetInfo::getTargetTriple(), llvm::MCSubtargetInfo::hasFeature(), and llvm::RISCVTargetStreamer::setTargetABI().
Member Function Documentation
emitDirectiveOptionNoPIC()
void RISCVTargetELFStreamer::emitDirectiveOptionNoPIC () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 56 of file RISCVELFStreamer.cpp.
emitDirectiveOptionNoRelax()
void RISCVTargetELFStreamer::emitDirectiveOptionNoRelax () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 60 of file RISCVELFStreamer.cpp.
emitDirectiveOptionNoRVC()
void RISCVTargetELFStreamer::emitDirectiveOptionNoRVC () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 58 of file RISCVELFStreamer.cpp.
emitDirectiveOptionPIC()
void RISCVTargetELFStreamer::emitDirectiveOptionPIC () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 55 of file RISCVELFStreamer.cpp.
emitDirectiveOptionPop()
void RISCVTargetELFStreamer::emitDirectiveOptionPop () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 54 of file RISCVELFStreamer.cpp.
emitDirectiveOptionPush()
void RISCVTargetELFStreamer::emitDirectiveOptionPush () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 53 of file RISCVELFStreamer.cpp.
emitDirectiveOptionRelax()
void RISCVTargetELFStreamer::emitDirectiveOptionRelax () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 59 of file RISCVELFStreamer.cpp.
emitDirectiveOptionRVC()
void RISCVTargetELFStreamer::emitDirectiveOptionRVC () override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 57 of file RISCVELFStreamer.cpp.
emitDirectiveVariantCC()
void RISCVTargetELFStreamer::emitDirectiveVariantCC (MCSymbol & Symbol) override virtual
Reimplemented from llvm::RISCVTargetStreamer.
Definition at line 127 of file RISCVELFStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), getStreamer(), llvm::MCAssembler::registerSymbol(), and llvm::ELF::STO_RISCV_VARIANT_CC.
finish()
void RISCVTargetELFStreamer::finish () override virtual
Reimplemented from llvm::MCTargetStreamer.
Definition at line 87 of file RISCVELFStreamer.cpp.
References llvm::RISCVABI::ABI_ILP32, llvm::RISCVABI::ABI_ILP32D, llvm::RISCVABI::ABI_ILP32E, llvm::RISCVABI::ABI_ILP32F, llvm::RISCVABI::ABI_LP64, llvm::RISCVABI::ABI_LP64D, llvm::RISCVABI::ABI_LP64E, llvm::RISCVABI::ABI_LP64F, llvm::RISCVABI::ABI_Unknown, llvm::ELF::EF_RISCV_FLOAT_ABI_DOUBLE, llvm::ELF::EF_RISCV_FLOAT_ABI_SINGLE, llvm::ELF::EF_RISCV_RVC, llvm::ELF::EF_RISCV_RVE, llvm::ELF::EF_RISCV_TSO, llvm::RISCVTargetStreamer::finish(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getELFHeaderEFlags(), llvm::MCSubtargetInfo::getFeatureBits(), getStreamer(), llvm::RISCVTargetStreamer::getTargetABI(), llvm_unreachable, and llvm::MCAssembler::setELFHeaderEFlags().
getStreamer()
RISCVELFStreamer & RISCVTargetELFStreamer::getStreamer ()
Definition at line 49 of file RISCVELFStreamer.cpp.
References llvm::MCTargetStreamer::Streamer.
Referenced by emitDirectiveVariantCC(), finish(), and RISCVTargetELFStreamer().
The documentation for this class was generated from the following files:
lib/Target/RISCV/MCTargetDesc/RISCVELFStreamer.h
lib/Target/RISCV/MCTargetDesc/RISCVELFStreamer.cpp