LLVM: llvm::InstrProfReaderItaniumRemapper< HashTableImpl > Class Template Reference
llvm::InstrProfReaderItaniumRemapper< HashTableImpl > Class Template Reference
A remapper that applies remappings based on a symbol remapping file.
Public Member Functions
InstrProfReaderItaniumRemapper (std::unique_ptr< MemoryBuffer > RemapBuffer, InstrProfReaderIndex< HashTableImpl > &Underlying)
Error populateRemappings () override
Error getRecords (StringRef FuncName, ArrayRef< NamedInstrProfRecord > &Data) override
Public Member Functions inherited from llvm::InstrProfReaderRemapper
virtual ~InstrProfReaderRemapper ()=default
virtual Error populateRemappings ()
virtual Error getRecords (StringRef FuncName, ArrayRef< NamedInstrProfRecord > &Data)=0
Static Public Member Functions
static StringRef extractName (StringRef Name)
Extract the original function name from a PGO function name.
static void reconstituteName (StringRef OrigName, StringRef ExtractedName, StringRef Replacement, SmallVectorImpl< char > &Out)
Given a mangled name extracted from a PGO function name, and a new form for that mangled name, reconstitute the name.
Detailed Description
template<typename HashTableImpl>
class llvm::InstrProfReaderItaniumRemapper< HashTableImpl >
A remapper that applies remappings based on a symbol remapping file.
Definition at line 1000 of file InstrProfReader.cpp.
Constructor & Destructor Documentation
InstrProfReaderItaniumRemapper()
template<typename HashTableImpl > llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::InstrProfReaderItaniumRemapper (std::unique_ptr< MemoryBuffer > RemapBuffer, InstrProfReaderIndex< HashTableImpl > & Underlying) inline
Definition at line 1003 of file InstrProfReader.cpp.
Member Function Documentation
extractName()
template<typename HashTableImpl > static StringRef llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::extractName (StringRef Name) inline static
Extract the original function name from a PGO function name.
Definition at line 1010 of file InstrProfReader.cpp.
References llvm::kGlobalIdentifierDelimiter, and Name.
Referenced by llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::getRecords(), and llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::populateRemappings().
getRecords()
template<typename HashTableImpl > Error llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::getRecords (StringRef FuncName, ArrayRef< NamedInstrProfRecord > & Data) inline override virtual
Implements llvm::InstrProfReaderRemapper.
Definition at line 1051 of file InstrProfReader.cpp.
References llvm::StringRef::begin(), llvm::Data, E, llvm::StringRef::empty(), llvm::StringRef::end(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::extractName(), llvm::handleErrors(), llvm::SymbolRemappingReader::lookup(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::reconstituteName(), llvm::Error::success(), and llvm::unknown_function.
populateRemappings()
template<typename HashTableImpl > Error llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::populateRemappings () inline override virtual
Reimplemented from llvm::InstrProfReaderRemapper.
Definition at line 1036 of file InstrProfReader.cpp.
References E, llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::extractName(), llvm::SymbolRemappingReader::insert(), Name, llvm::SymbolRemappingReader::read(), and llvm::Error::success().
reconstituteName()
template<typename HashTableImpl > static void llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::reconstituteName (StringRef OrigName, StringRef ExtractedName, StringRef Replacement, SmallVectorImpl< char > & Out) inline static
Given a mangled name extracted from a PGO function name, and a new form for that mangled name, reconstitute the name.
Definition at line 1027 of file InstrProfReader.cpp.
References llvm::StringRef::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::StringRef::end(), llvm::SmallVectorImpl< T >::insert(), llvm::SmallVectorImpl< T >::reserve(), and llvm::StringRef::size().
Referenced by llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::getRecords().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/InstrProfReader.h
lib/ProfileData/InstrProfReader.cpp