LLVM: llvm::MachO::ObjCContainerRecord Class Reference
llvm::MachO::ObjCContainerRecord Class Reference
#include "llvm/TextAPI/Record.h"
Public Member Functions
ObjCContainerRecord (StringRef Name, RecordLinkage Linkage)
ObjCIVarRecord * addObjCIVar (StringRef IVar, RecordLinkage Linkage)
ObjCIVarRecord * findObjCIVar (StringRef IVar) const
std::vector< ObjCIVarRecord * > getObjCIVars () const
Public Member Functions inherited from llvm::MachO::Record
Record ()=default
Record (StringRef Name, RecordLinkage Linkage, SymbolFlags Flags)
bool isWeakDefined () const
bool isWeakReferenced () const
bool isThreadLocalValue () const
bool isData () const
bool isText () const
bool isInternal () const
bool isUndefined () const
bool isExported () const
bool isRexported () const
StringRef getName () const
SymbolFlags getFlags () const
Additional Inherited Members
Protected Attributes inherited from llvm::MachO::Record
StringRef Name
RecordLinkage Linkage
SymbolFlags Flags
Detailed Description
Definition at line 138 of file Record.h.
Constructor & Destructor Documentation
ObjCContainerRecord()
llvm::MachO::ObjCContainerRecord::ObjCContainerRecord (StringRef Name, RecordLinkage Linkage) inline
Definition at line 140 of file Record.h.
References llvm::MachO::Data, llvm::MachO::Record::Linkage, and llvm::MachO::Record::Name.
Member Function Documentation
addObjCIVar()
ObjCIVarRecord * ObjCContainerRecord::addObjCIVar (StringRef IVar, RecordLinkage Linkage)
Definition at line 222 of file RecordsSlice.cpp.
References llvm::MachO::Record::Linkage.
Referenced by llvm::MachO::RecordsSlice::addObjCIVar().
findObjCIVar()
ObjCIVarRecord * ObjCContainerRecord::findObjCIVar (StringRef IVar) const
Definition at line 101 of file RecordsSlice.cpp.
getObjCIVars()
std::vector< ObjCIVarRecord * > ObjCContainerRecord::getObjCIVars () const
Definition at line 207 of file RecordsSlice.cpp.
References llvm::for_each(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::MachO::SymbolConverter::visitObjCCategory(), and llvm::MachO::SymbolConverter::visitObjCInterface().
The documentation for this class was generated from the following files:
include/llvm/TextAPI/Record.h
lib/TextAPI/RecordsSlice.cpp