LLVM: llvm::DPValue Class Reference
llvm::DPValue Class Reference
Record of a variable value-assignment, aka a non instruction representation of the dbg.value intrinsic.
#include "llvm/IR/DebugProgramInstruction.h"
Classes
class location_op_iterator
Iterator for ValueAsMetadata that internally uses direct pointer iteration over either a ValueAsMetadata* or a ValueAsMetadata**, dereferencing to the ValueAsMetadata .
Public Types
enum class LocationType {
Declare , Value , Assign , End ,
Any
}
using self_iterator = simple_ilist< DPValue >::iterator
using const_self_iterator = simple_ilist< DPValue >::const_iterator
Public Member Functions
void deleteInstr ()
const BasicBlock * getParent () const
BasicBlock * getParent ()
void dump () const
void removeFromParent ()
void eraseFromParent ()
DPValue * getNextNode ()
DPValue * getPrevNode ()
DPValue (const DbgVariableIntrinsic *DVI)
Create a new DPValue representing the intrinsic DVI, for example the assignment represented by a dbg.value.
DPValue (const DPValue &DPV)
DPValue (Metadata *Location, DILocalVariable *DV, DIExpression *Expr, const DILocation *DI, LocationType Type=LocationType::Value)
Directly construct a new DPValue representing a dbg.value intrinsic assigning Location to the DV / Expr / DI variable.
DPValue (Metadata *Value, DILocalVariable *Variable, DIExpression *Expression, DIAssignID *AssignID, Metadata *Address, DIExpression *AddressExpression, const DILocation *DI)
bool isDbgDeclare ()
bool isDbgValue ()
iterator_range< location_op_iterator > location_ops () const
Get the locations corresponding to the variable referenced by the debug info intrinsic.
Value * getVariableLocationOp (unsigned OpIdx) const
void replaceVariableLocationOp (Value *OldValue, Value *NewValue, bool AllowEmpty=false)
void replaceVariableLocationOp (unsigned OpIdx, Value *NewValue)
void addVariableLocationOps (ArrayRef< Value * > NewValues, DIExpression *NewExpr)
Adding a new location operand will always result in this intrinsic using an ArgList, and must always be accompanied by a new expression that uses the new operand.
void setVariable (DILocalVariable *NewVar)
void setExpression (DIExpression *NewExpr)
unsigned getNumVariableLocationOps () const
bool hasArgList () const
bool hasValidLocation () const
Returns true if this DPValue has no empty MDNodes in its location list.
bool isAddressOfVariable () const
Does this describe the address of a local variable.
LocationType getType () const
DebugLoc getDebugLoc () const
void setDebugLoc (DebugLoc Loc)
void setKillLocation ()
bool isKillLocation () const
DILocalVariable * getVariable () const
DIExpression * getExpression () const
Metadata * getRawLocation () const
Returns the metadata operand for the first location description.
Value * getValue (unsigned OpIdx=0) const
void setRawLocation (Metadata *NewLocation)
Use of this should generally be avoided; instead, replaceVariableLocationOp and addVariableLocationOps should be used where possible to avoid creating invalid state.
std::optional< uint64_t > getFragmentSizeInBits () const
Get the size (in bits) of the variable, or fragment of the variable that is described.
bool isEquivalentTo (const DPValue &Other)
bool isIdenticalToWhenDefined (const DPValue &Other)
DPValue * clone () const
DbgVariableIntrinsic * createDebugIntrinsic (Module *M, Instruction *InsertBefore) const
Convert this DPValue back into a dbg.value intrinsic.
void setMarker (DPMarker *M)
DPMarker * getMarker ()
const DPMarker * getMarker () const
BasicBlock * getBlock ()
const BasicBlock * getBlock () const
Function * getFunction ()
const Function * getFunction () const
Module * getModule ()
const Module * getModule () const
LLVMContext & getContext ()
const LLVMContext & getContext () const
void insertBefore (DPValue *InsertBefore)
Insert this DPValue prior to InsertBefore.
void insertAfter (DPValue *InsertAfter)
void moveBefore (DPValue *MoveBefore)
void moveAfter (DPValue *MoveAfter)
void print (raw_ostream &O, bool IsForDebug=false) const
void print (raw_ostream &ROS, ModuleSlotTracker &MST, bool IsForDebug) const
DbgAssign Methods
bool isDbgAssign () const
Value * getAddress () const
Metadata * getRawAddress () const
Metadata * getRawAssignID () const
DIAssignID * getAssignID () const
DIExpression * getAddressExpression () const
void setAddressExpression (DIExpression *NewExpr)
void setAssignId (DIAssignID *New)
void setAddress (Value *V)
void setKillAddress ()
Kill the address component.
bool isKillAddress () const
Check whether this kills the address component.
Public Member Functions inherited from llvm::ilist_node_impl< OptionsT >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static DPValue * createDPVAssign (Value *Val, DILocalVariable *Variable, DIExpression *Expression, DIAssignID *AssignID, Value *Address, DIExpression *AddressExpression, const DILocation *DI)
static DPValue * createLinkedDPVAssign (Instruction *LinkedInstr, Value *Val, DILocalVariable *Variable, DIExpression *Expression, Value *Address, DIExpression *AddressExpression, const DILocation *DI)
static DPValue * createDPValue (Value *Location, DILocalVariable *DV, DIExpression *Expr, const DILocation *DI)
static DPValue * createDPValue (Value *Location, DILocalVariable *DV, DIExpression *Expr, const DILocation *DI, DPValue &InsertBefore)
static DPValue * createDPVDeclare (Value *Address, DILocalVariable *DV, DIExpression *Expr, const DILocation *DI)
static DPValue * createDPVDeclare (Value *Address, DILocalVariable *DV, DIExpression *Expr, const DILocation *DI, DPValue &InsertBefore)
Public Attributes
LocationType Type
Classification of the debug-info record that this DPValue represents.
DPMarker * Marker = nullptr
Marker that this DPValue is linked into.
Friends
class DebugValueUser
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< OptionsT >
using self_iterator = typename ilist_select_iterator_type< OptionsT::has_iterator_bits, OptionsT, false, false >::type
using const_self_iterator = typename ilist_select_iterator_type< OptionsT::has_iterator_bits, OptionsT, false, true >::type
using reverse_self_iterator = typename ilist_select_iterator_type< OptionsT::has_iterator_bits, OptionsT, true, false >::type
using const_reverse_self_iterator = typename ilist_select_iterator_type< OptionsT::has_iterator_bits, OptionsT, true, true >::type
Protected Member Functions inherited from llvm::ilist_node_impl< OptionsT >
ilist_node_impl ()=default
Detailed Description
Record of a variable value-assignment, aka a non instruction representation of the dbg.value intrinsic.
Features various methods copied across from the Instruction class to aid ease-of-use. DPValue objects should always be linked into a DPMarker's StoredDPValues list. The marker connects a DPValue back to it's position in the BasicBlock.
This class inherits from DebugValueUser to allow LLVM's metadata facilities to update our references to metadata beneath our feet.
Definition at line 77 of file DebugProgramInstruction.h.
Member Typedef Documentation
const_self_iterator
using llvm::DPValue::const_self_iterator = simple_ilist<DPValue>::const_iterator
Definition at line 102 of file DebugProgramInstruction.h.
self_iterator
using llvm::DPValue::self_iterator = simple_ilist<DPValue>::iterator
Definition at line 101 of file DebugProgramInstruction.h.
Member Enumeration Documentation
LocationType
enum class llvm::DPValue::LocationType strong
Enumerator
Declare
Value
Assign
End
Marks the end of the concrete types.
Any
To indicate all LocationTypes in searches.
Definition at line 104 of file DebugProgramInstruction.h.
Constructor & Destructor Documentation
DPValue() [1/4]
llvm::DPValue::DPValue (const DbgVariableIntrinsic * DVI)
Create a new DPValue representing the intrinsic DVI, for example the assignment represented by a dbg.value.
Definition at line 16 of file DebugProgramInstruction.cpp.
References llvm::DbgVariableIntrinsic::getRawLocation().
DPValue() [2/4]
llvm::DPValue::DPValue (const DPValue & DPV)
Definition at line 42 of file DebugProgramInstruction.cpp.
DPValue() [3/4]
llvm::DPValue::DPValue (Metadata * Location, DILocalVariable * DV, DIExpression * Expr, const DILocation * DI, LocationType Type = LocationType::Value)
Directly construct a new DPValue representing a dbg.value intrinsic assigning Location to the DV / Expr / DI variable.
Definition at line 47 of file DebugProgramInstruction.cpp.
DPValue() [4/4]
llvm::DPValue::DPValue (Metadata * Value, DILocalVariable * Variable, DIExpression * Expression, DIAssignID * AssignID, Metadata * Address, DIExpression * AddressExpression, const DILocation * DI)
Definition at line 52 of file DebugProgramInstruction.cpp.
References llvm::Address, and Value.
Member Function Documentation
addVariableLocationOps()
void llvm::DPValue::addVariableLocationOps (ArrayRef< Value * > NewValues, DIExpression * NewExpr)
Adding a new location operand will always result in this intrinsic using an ArgList, and must always be accompanied by a new expression that uses the new operand.
Definition at line 218 of file DebugProgramInstruction.cpp.
References assert(), llvm::DIArgList::get(), llvm::getAsMetadata(), getContext(), getNumVariableLocationOps(), getVariableLocationOp(), llvm::is_contained(), location_ops(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), setExpression(), setRawLocation(), and llvm::ArrayRef< T >::size().
clone()
DPValue * llvm::DPValue::clone () const
Definition at line 258 of file DebugProgramInstruction.cpp.
Referenced by insertDPValuesForPHIs().
createDebugIntrinsic()
DbgVariableIntrinsic * llvm::DPValue::createDebugIntrinsic (Module * M, Instruction * InsertBefore) const
Convert this DPValue back into a dbg.value intrinsic.
InsertBefore Optional position to insert this intrinsic.
Returns
A new dbg.value intrinsic representiung this DPValue.
Definition at line 261 of file DebugProgramInstruction.cpp.
References Any, assert(), Assign, Context, llvm::CallInst::Create(), Declare, End, llvm::DebugLoc::get(), llvm::MetadataAsValue::get(), getAddressExpression(), getAssignID(), llvm::MDNode::getContext(), getDebugLoc(), llvm::Intrinsic::getDeclaration(), getExpression(), llvm::Function::getFunctionType(), getRawAddress(), getRawLocation(), getType(), getVariable(), llvm::Instruction::insertBefore(), isDbgAssign(), llvm_unreachable, llvm::Instruction::setDebugLoc(), llvm::CallInst::setTailCall(), and Value.
createDPValue() [1/2]
DPValue * llvm::DPValue::createDPValue (Value * Location, DILocalVariable * DV, DIExpression * Expr, const DILocation * DI) static
Definition at line 62 of file DebugProgramInstruction.cpp.
References llvm::ValueAsMetadata::get(), and Value.
Referenced by createDPValue().
createDPValue() [2/2]
DPValue * llvm::DPValue::createDPValue (Value * Location, DILocalVariable * DV, DIExpression * Expr, const DILocation * DI, DPValue & InsertBefore) static
Definition at line 68 of file DebugProgramInstruction.cpp.
References createDPValue().
createDPVAssign()
DPValue * llvm::DPValue::createDPVAssign (Value * Val, DILocalVariable * Variable, DIExpression * Expression, DIAssignID * AssignID, Value * Address, DIExpression * AddressExpression, const DILocation * DI) static
Definition at line 90 of file DebugProgramInstruction.cpp.
References llvm::Address, and llvm::ValueAsMetadata::get().
Referenced by createLinkedDPVAssign().
createDPVDeclare() [1/2]
DPValue * llvm::DPValue::createDPVDeclare (Value * Address, DILocalVariable * DV, DIExpression * Expr, const DILocation * DI) static
Definition at line 76 of file DebugProgramInstruction.cpp.
References llvm::Address, Declare, and llvm::ValueAsMetadata::get().
Referenced by createDPVDeclare(), and insertNewDbgInst().
createDPVDeclare() [2/2]
DPValue * llvm::DPValue::createDPVDeclare (Value * Address, DILocalVariable * DV, DIExpression * Expr, const DILocation * DI, DPValue & InsertBefore) static
Definition at line 82 of file DebugProgramInstruction.cpp.
References llvm::Address, and createDPVDeclare().
createLinkedDPVAssign()
DPValue * llvm::DPValue::createLinkedDPVAssign (Instruction * LinkedInstr, Value * Val, DILocalVariable * Variable, DIExpression * Expression, Value * Address, DIExpression * AddressExpression, const DILocation * DI) static
Definition at line 99 of file DebugProgramInstruction.cpp.
References llvm::Address, assert(), createDPVAssign(), llvm::Instruction::getMetadata(), llvm::Instruction::getParent(), and llvm::BasicBlock::insertDPValueAfter().
Referenced by createLinkedAssign(), emitDbgAssign(), and insertNewDbgInst().
deleteInstr()
void llvm::DPValue::deleteInstr ()
Definition at line 60 of file DebugProgramInstruction.cpp.
Referenced by llvm::DPMarker::dropDPValues(), llvm::DPMarker::dropOneDPValue(), and eraseFromParent().
dump()
LLVM_DUMP_METHOD void DPValue::dump () const
Definition at line 5145 of file AsmWriter.cpp.
References llvm::dbgs(), and print().
eraseFromParent()
void llvm::DPValue::eraseFromParent ()
Definition at line 467 of file DebugProgramInstruction.cpp.
References deleteInstr(), and removeFromParent().
getAddress()
Value * llvm::DPValue::getAddress () const
Definition at line 314 of file DebugProgramInstruction.cpp.
References assert(), and getRawAddress().
Referenced by isKillAddress(), replaceVariableLocationOp(), and setKillAddress().
getAddressExpression()
DIExpression * llvm::DPValue::getAddressExpression () const inline
Definition at line 295 of file DebugProgramInstruction.h.
Referenced by createDebugIntrinsic(), and insertNewDbgInst().
getAssignID()
DIAssignID * llvm::DPValue::getAssignID () const
Definition at line 324 of file DebugProgramInstruction.cpp.
References llvm::DebugValueUser::DebugValues.
Referenced by createDebugIntrinsic(), llvm::at::getAssignmentInsts(), and getIDFromMarker().
getBlock() [1/2]
BasicBlock * llvm::DPValue::getBlock ()
Definition at line 346 of file DebugProgramInstruction.cpp.
References llvm::DPMarker::getParent(), and Marker.
Referenced by getContext(), and getFunction().
getBlock() [2/2]
const BasicBlock * llvm::DPValue::getBlock () const
Definition at line 348 of file DebugProgramInstruction.cpp.
References llvm::DPMarker::getParent(), and Marker.
getContext() [1/2]
LLVMContext & llvm::DPValue::getContext ()
Definition at line 358 of file DebugProgramInstruction.cpp.
References getBlock(), and llvm::BasicBlock::getContext().
Referenced by addVariableLocationOps(), llvm::getDebugValueLoc(), and replaceVariableLocationOp().
getContext() [2/2]
const LLVMContext & llvm::DPValue::getContext () const
Definition at line 360 of file DebugProgramInstruction.cpp.
References getBlock(), and llvm::BasicBlock::getContext().
getDebugLoc()
DebugLoc llvm::DPValue::getDebugLoc () const inline
Definition at line 237 of file DebugProgramInstruction.h.
Referenced by buildFrameDebugInfo(), buildOverlapMapAndRecordDeclares(), createDebugIntrinsic(), findVarsWithStackSlot(), getAggregateVariable(), llvm::getDebugValueLoc(), insertNewDbgInst(), and llvm::DebugInfoFinder::processDPValue().
getExpression()
DIExpression * llvm::DPValue::getExpression () const inline
Definition at line 245 of file DebugProgramInstruction.h.
Referenced by buildOverlapMapAndRecordDeclares(), llvm::ConvertDebugDeclareToDebugValue(), createDebugIntrinsic(), getFragmentOrEntireVariable(), getFragmentSizeInBits(), isKillLocation(), and llvm::coro::salvageDebugInfo().
getFragmentSizeInBits()
std::optional< uint64_t > llvm::DPValue::getFragmentSizeInBits () const
Get the size (in bits) of the variable, or fragment of the variable that is described.
Definition at line 252 of file DebugProgramInstruction.cpp.
References getExpression(), llvm::DIVariable::getSizeInBits(), and getVariable().
Referenced by getFragmentOrEntireVariable(), and valueCoversEntireFragment().
getFunction() [1/2]
Function * llvm::DPValue::getFunction ()
Definition at line 350 of file DebugProgramInstruction.cpp.
References getBlock(), and llvm::BasicBlock::getParent().
Referenced by getModule(), and llvm::coro::salvageDebugInfo().
getFunction() [2/2]
const Function * llvm::DPValue::getFunction () const
Definition at line 352 of file DebugProgramInstruction.cpp.
References getBlock(), and llvm::BasicBlock::getParent().
getMarker() [1/2]
DPMarker * llvm::DPValue::getMarker () inline
Definition at line 319 of file DebugProgramInstruction.h.
References Marker.
Referenced by llvm::DPMarker::dropOneDPValue(), getModuleFromDPI(), getNextNode(), insertAfter(), insertBefore(), llvm::DPMarker::insertDPValue(), llvm::DPMarker::insertDPValueAfter(), moveAfter(), moveBefore(), removeFromParent(), and rewriteDebugUsers().
getMarker() [2/2]
const DPMarker * llvm::DPValue::getMarker () const inline
Definition at line 320 of file DebugProgramInstruction.h.
References Marker.
getModule() [1/2]
Module * llvm::DPValue::getModule ()
Definition at line 354 of file DebugProgramInstruction.cpp.
References getFunction(), and llvm::GlobalValue::getParent().
Referenced by valueCoversEntireFragment().
getModule() [2/2]
const Module * llvm::DPValue::getModule () const
Definition at line 356 of file DebugProgramInstruction.cpp.
References getFunction(), and llvm::GlobalValue::getParent().
getNextNode()
DPValue * llvm::DPValue::getNextNode () inline
Definition at line 98 of file DebugProgramInstruction.h.
References llvm::ilist_node_impl< OptionsT >::getIterator().
getNumVariableLocationOps()
unsigned llvm::DPValue::getNumVariableLocationOps () const
Definition at line 137 of file DebugProgramInstruction.cpp.
References getRawLocation(), and hasArgList().
Referenced by addVariableLocationOps(), isKillLocation(), replaceVariableLocationOp(), and valueCoversEntireFragment().
getParent() [1/2]
BasicBlock * llvm::DPValue::getParent ()
Definition at line 344 of file DebugProgramInstruction.cpp.
References llvm::Instruction::getParent(), llvm::DPMarker::MarkedInstr, and Marker.
getParent() [2/2]
const BasicBlock * llvm::DPValue::getParent () const
Definition at line 340 of file DebugProgramInstruction.cpp.
References llvm::Instruction::getParent(), llvm::DPMarker::MarkedInstr, and Marker.
Referenced by llvm::JumpThreadingPass::updateSSA().
getPrevNode()
DPValue * llvm::DPValue::getPrevNode () inline
Definition at line 99 of file DebugProgramInstruction.h.
References llvm::ilist_node_impl< OptionsT >::getIterator().
getRawAddress()
Metadata * llvm::DPValue::getRawAddress () const inline
Definition at line 290 of file DebugProgramInstruction.h.
References llvm::DebugValueUser::DebugValues, and isDbgAssign().
Referenced by createDebugIntrinsic(), and getAddress().
getRawAssignID()
Metadata * llvm::DPValue::getRawAssignID () const inline
Definition at line 293 of file DebugProgramInstruction.h.
References llvm::DebugValueUser::DebugValues.
getRawLocation()
Metadata * llvm::DPValue::getRawLocation () const inline
Returns the metadata operand for the first location description.
i.e., dbg intrinsic dbg.value,declare operand and dbg.assign 1st location operand (the "value componenet"). Note the operand (singular) may be a DIArgList which is a list of values.
Definition at line 251 of file DebugProgramInstruction.h.
References llvm::DebugValueUser::DebugValues.
Referenced by buildOverlapMapAndRecordDeclares(), createDebugIntrinsic(), getNumVariableLocationOps(), getVariableLocationOp(), hasArgList(), and location_ops().
getType()
LocationType llvm::DPValue::getType () const inline
Definition at line 235 of file DebugProgramInstruction.h.
References Type.
Referenced by createDebugIntrinsic(), isDbgAssign(), llvm::coro::salvageDebugInfo(), and setKillAddress().
getValue()
Value * llvm::DPValue::getValue (unsigned OpIdx = 0) const inline
Definition at line 253 of file DebugProgramInstruction.h.
References getVariableLocationOp().
Referenced by insertNewDbgInst().
getVariable()
DILocalVariable * llvm::DPValue::getVariable () const inline
Definition at line 243 of file DebugProgramInstruction.h.
Referenced by buildFrameDebugInfo(), llvm::ConvertDebugDeclareToDebugValue(), createDebugIntrinsic(), findVarsWithStackSlot(), getAggregateVariable(), getFragmentSizeInBits(), insertNewDbgInst(), and llvm::DebugInfoFinder::processDPValue().
getVariableLocationOp()
Value * llvm::DPValue::getVariableLocationOp (unsigned OpIdx) const
Definition at line 143 of file DebugProgramInstruction.cpp.
References assert(), and getRawLocation().
Referenced by addVariableLocationOps(), getValue(), hasValidLocation(), replaceVariableLocationOp(), llvm::coro::salvageDebugInfo(), and valueCoversEntireFragment().
hasArgList()
bool llvm::DPValue::hasArgList () const inline
Definition at line 228 of file DebugProgramInstruction.h.
References getRawLocation().
Referenced by getNumVariableLocationOps(), and replaceVariableLocationOp().
hasValidLocation()
bool llvm::DPValue::hasValidLocation () const inline
Returns true if this DPValue has no empty MDNodes in its location list.
Definition at line 230 of file DebugProgramInstruction.h.
References getVariableLocationOp().
insertAfter()
void llvm::DPValue::insertAfter (DPValue * InsertAfter)
Definition at line 372 of file DebugProgramInstruction.cpp.
References assert(), getMarker(), and llvm::DPMarker::insertDPValueAfter().
Referenced by moveAfter().
insertBefore()
void llvm::DPValue::insertBefore (DPValue * InsertBefore)
Insert this DPValue prior to InsertBefore.
Must not be called if this is already contained in a DPMarker.
Definition at line 364 of file DebugProgramInstruction.cpp.
References assert(), getMarker(), and llvm::DPMarker::insertDPValue().
Referenced by moveBefore().
isAddressOfVariable()
bool llvm::DPValue::isAddressOfVariable () const inline
Does this describe the address of a local variable.
True for dbg.addr and dbg.declare, but not dbg.value, which describes its value.
Definition at line 234 of file DebugProgramInstruction.h.
References Declare.
Referenced by llvm::ConvertDebugDeclareToDebugValue(), and valueCoversEntireFragment().
isDbgAssign()
bool llvm::DPValue::isDbgAssign () const inline
Definition at line 287 of file DebugProgramInstruction.h.
References Assign, and getType().
Referenced by CastToDbgAssign(), llvm::ConvertDebugDeclareToDebugValue(), createDebugIntrinsic(), llvm::at::getAssignmentInsts(), getIDFromMarker(), getRawAddress(), and replaceVariableLocationOp().
isDbgDeclare()
bool llvm::DPValue::isDbgDeclare () inline
Definition at line 203 of file DebugProgramInstruction.h.
References Declare.
Referenced by DynCastToDbgDeclare(), insertNewDbgInst(), and llvm::coro::salvageDebugInfo().
isDbgValue()
bool llvm::DPValue::isDbgValue () inline
Definition at line 204 of file DebugProgramInstruction.h.
References Value.
isEquivalentTo()
bool llvm::DPValue::isEquivalentTo (const DPValue & Other) inline
Definition at line 272 of file DebugProgramInstruction.h.
References llvm::DebugValueUser::DebugValues, and llvm::Other.
isIdenticalToWhenDefined()
bool llvm::DPValue::isIdenticalToWhenDefined (const DPValue & Other) inline
Definition at line 279 of file DebugProgramInstruction.h.
References llvm::DebugValueUser::DebugValues, and llvm::Other.
isKillAddress()
bool llvm::DPValue::isKillAddress () const
Check whether this kills the address component.
This doesn't take into account the position of the intrinsic, therefore a returned value of false does not guarentee the address is a valid location for the variable at the intrinsic's position in IR.
Definition at line 335 of file DebugProgramInstruction.cpp.
References Addr, and getAddress().
isKillLocation()
bool llvm::DPValue::isKillLocation () const
Definition at line 246 of file DebugProgramInstruction.cpp.
References llvm::any_of(), getExpression(), getNumVariableLocationOps(), and location_ops().
location_ops()
iterator_range< DPValue::location_op_iterator > llvm::DPValue::location_ops () const
Get the locations corresponding to the variable referenced by the debug info intrinsic.
Depending on the intrinsic, this could be the variable's value or its address.
Definition at line 114 of file DebugProgramInstruction.cpp.
References assert(), and getRawLocation().
Referenced by addVariableLocationOps(), insertDPValuesForPHIs(), isKillLocation(), replaceVariableLocationOp(), and setKillLocation().
moveAfter()
void llvm::DPValue::moveAfter (DPValue * MoveAfter)
Definition at line 386 of file DebugProgramInstruction.cpp.
References assert(), getMarker(), insertAfter(), and removeFromParent().
moveBefore()
void llvm::DPValue::moveBefore (DPValue * MoveBefore)
Definition at line 380 of file DebugProgramInstruction.cpp.
References assert(), getMarker(), insertBefore(), and removeFromParent().
print() [1/2]
void DPValue::print (raw_ostream & O, bool IsForDebug = false) const
Definition at line 4853 of file AsmWriter.cpp.
References getModuleFromDPI(), and print().
Referenced by dump(), and print().
print() [2/2]
void DPValue::print (raw_ostream & ROS, ModuleSlotTracker & MST, bool IsForDebug) const
Definition at line 4876 of file AsmWriter.cpp.
References F, llvm::ModuleSlotTracker::getMachine(), getModuleFromDPI(), llvm::BasicBlock::getParent(), llvm::DPMarker::getParent(), llvm::ModuleSlotTracker::incorporateFunction(), Marker, and OS.
removeFromParent()
void llvm::DPValue::removeFromParent ()
Definition at line 462 of file DebugProgramInstruction.cpp.
References llvm::ilist_node_impl< OptionsT >::getIterator(), getMarker(), Marker, and llvm::DPMarker::StoredDPValues.
Referenced by DbgInserterHelper(), eraseFromParent(), moveAfter(), moveBefore(), rewriteDebugUsers(), and llvm::coro::salvageDebugInfo().
replaceVariableLocationOp() [1/2]
void llvm::DPValue::replaceVariableLocationOp (unsigned OpIdx, Value * NewValue)
Definition at line 199 of file DebugProgramInstruction.cpp.
References assert(), llvm::DIArgList::get(), llvm::ValueAsMetadata::get(), llvm::getAsMetadata(), getContext(), getNumVariableLocationOps(), getVariableLocationOp(), hasArgList(), Idx, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and setRawLocation().
replaceVariableLocationOp() [2/2]
void llvm::DPValue::replaceVariableLocationOp (Value * OldValue, Value * NewValue, bool AllowEmpty = false)
Definition at line 166 of file DebugProgramInstruction.cpp.
References assert(), llvm::find(), llvm::DIArgList::get(), llvm::ValueAsMetadata::get(), getAddress(), llvm::getAsMetadata(), getContext(), getVariableLocationOp(), hasArgList(), isDbgAssign(), llvm_unreachable, location_ops(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), setAddress(), and setRawLocation().
Referenced by insertDPValuesForPHIs(), rewriteDebugUsers(), llvm::coro::salvageDebugInfo(), setKillLocation(), and updateOneDbgValueForAlloca().
setAddress()
void llvm::DPValue::setAddress (Value * V) inline
Definition at line 300 of file DebugProgramInstruction.h.
References llvm::ValueAsMetadata::get(), and llvm::DebugValueUser::resetDebugValue().
Referenced by replaceVariableLocationOp().
setAddressExpression()
void llvm::DPValue::setAddressExpression (DIExpression * NewExpr) inline
Definition at line 296 of file DebugProgramInstruction.h.
setAssignId()
void llvm::DPValue::setAssignId (DIAssignID * New)
Definition at line 328 of file DebugProgramInstruction.cpp.
References llvm::DebugValueUser::resetDebugValue().
setDebugLoc()
void llvm::DPValue::setDebugLoc (DebugLoc Loc) inline
Definition at line 238 of file DebugProgramInstruction.h.
Referenced by llvm::coro::salvageDebugInfo().
setExpression()
void llvm::DPValue::setExpression (DIExpression * NewExpr) inline
Definition at line 224 of file DebugProgramInstruction.h.
Referenced by addVariableLocationOps(), rewriteDebugUsers(), llvm::coro::salvageDebugInfo(), and updateOneDbgValueForAlloca().
setKillAddress()
void llvm::DPValue::setKillAddress ()
Kill the address component.
Definition at line 330 of file DebugProgramInstruction.cpp.
References llvm::UndefValue::get(), llvm::ValueAsMetadata::get(), getAddress(), getType(), and llvm::DebugValueUser::resetDebugValue().
setKillLocation()
void llvm::DPValue::setKillLocation ()
Definition at line 234 of file DebugProgramInstruction.cpp.
References llvm::PoisonValue::get(), llvm::SmallPtrSetImpl< PtrType >::insert(), location_ops(), and replaceVariableLocationOp().
setMarker()
void llvm::DPValue::setMarker (DPMarker * M) inline
Definition at line 317 of file DebugProgramInstruction.h.
References Marker.
Referenced by llvm::DPMarker::absorbDebugValues().
setRawLocation()
void llvm::DPValue::setRawLocation (Metadata * NewLocation) inline
Use of this should generally be avoided; instead, replaceVariableLocationOp and addVariableLocationOps should be used where possible to avoid creating invalid state.
Definition at line 260 of file DebugProgramInstruction.h.
References assert(), and llvm::DebugValueUser::resetDebugValue().
Referenced by addVariableLocationOps(), and replaceVariableLocationOp().
setVariable()
void llvm::DPValue::setVariable (DILocalVariable * NewVar) inline
Definition at line 222 of file DebugProgramInstruction.h.
Friends And Related Function Documentation
DebugValueUser
friend class DebugValueUser friend
Definition at line 78 of file DebugProgramInstruction.h.
Member Data Documentation
Marker
DPMarker* llvm::DPValue::Marker = nullptr
Marker that this DPValue is linked into.
Definition at line 118 of file DebugProgramInstruction.h.
Referenced by getBlock(), getMarker(), getParent(), print(), removeFromParent(), and setMarker().
Type
LocationType llvm::DPValue::Type
Classification of the debug-info record that this DPValue represents.
Essentially, "is this a dbg.value or dbg.declare?". dbg.declares are not currently supported, but it would be trivial to do so.
Definition at line 115 of file DebugProgramInstruction.h.
Referenced by getType().
The documentation for this class was generated from the following files:
include/llvm/IR/DebugProgramInstruction.h
lib/IR/AsmWriter.cpp
lib/IR/DebugProgramInstruction.cpp