LLVM: llvm::VEMachineFunctionInfo Class Reference
llvm::VEMachineFunctionInfo Class Reference
#include "Target/VE/VEMachineFunctionInfo.h"
Public Member Functions
VEMachineFunctionInfo ()
VEMachineFunctionInfo (const Function &F, const TargetSubtargetInfo *STI)
MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const override
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
Register getGlobalBaseReg () const
void setGlobalBaseReg (Register Reg)
int getVarArgsFrameOffset () const
void setVarArgsFrameOffset (int Offset)
void setLeafProc (bool rhs)
bool isLeafProc () const
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
virtual MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy , typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Detailed Description
Definition at line 19 of file VEMachineFunctionInfo.h.
Constructor & Destructor Documentation
VEMachineFunctionInfo() [1/2]
llvm::VEMachineFunctionInfo::VEMachineFunctionInfo () inline
Definition at line 32 of file VEMachineFunctionInfo.h.
VEMachineFunctionInfo() [2/2]
llvm::VEMachineFunctionInfo::VEMachineFunctionInfo (const Function & F, const TargetSubtargetInfo * STI) inline
Definition at line 33 of file VEMachineFunctionInfo.h.
Member Function Documentation
clone()
MachineFunctionInfo * VEMachineFunctionInfo::clone (BumpPtrAllocator & Allocator, MachineFunction & DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) const override virtual
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
This requires remapping MachineBasicBlock references from the original parent to values in the new function. Targets may assume that virtual register and frame index values are preserved in the new function.
Reimplemented from llvm::MachineFunctionInfo.
Definition at line 15 of file VEMachineFunctionInfo.cpp.
References llvm::MachineFunction::cloneInfo().
getGlobalBaseReg()
Register llvm::VEMachineFunctionInfo::getGlobalBaseReg () const inline
Definition at line 41 of file VEMachineFunctionInfo.h.
Referenced by llvm::VEInstrInfo::getGlobalBaseReg(), and llvm::VEFrameLowering::hasGOT().
getVarArgsFrameOffset()
int llvm::VEMachineFunctionInfo::getVarArgsFrameOffset () const inline
Definition at line 44 of file VEMachineFunctionInfo.h.
Referenced by llvm::VETargetLowering::lowerVASTART().
isLeafProc()
bool llvm::VEMachineFunctionInfo::isLeafProc () const inline
Definition at line 48 of file VEMachineFunctionInfo.h.
Referenced by llvm::VEFrameLowering::emitEpilogue(), llvm::VEFrameLowering::emitEpilogueInsns(), llvm::VEFrameLowering::emitPrologue(), and llvm::VEFrameLowering::emitPrologueInsns().
setGlobalBaseReg()
void llvm::VEMachineFunctionInfo::setGlobalBaseReg (Register Reg) inline
Definition at line 42 of file VEMachineFunctionInfo.h.
References Reg.
Referenced by llvm::VEInstrInfo::getGlobalBaseReg().
setLeafProc()
void llvm::VEMachineFunctionInfo::setLeafProc (bool rhs) inline
Definition at line 47 of file VEMachineFunctionInfo.h.
Referenced by llvm::VEFrameLowering::determineCalleeSaves().
setVarArgsFrameOffset()
void llvm::VEMachineFunctionInfo::setVarArgsFrameOffset (int Offset) inline
Definition at line 45 of file VEMachineFunctionInfo.h.
References llvm::Offset.
Referenced by llvm::VETargetLowering::LowerFormalArguments().
The documentation for this class was generated from the following files:
lib/Target/VE/VEMachineFunctionInfo.h
lib/Target/VE/VEMachineFunctionInfo.cpp