LLVM: llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType > Class Template Reference
llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType > Class Template Reference
#include "llvm/MC/MCPseudoProbe.h"
Public Member Functions
bool isRoot () const
InlinedProbeTreeMap & getChildren ()
const InlinedProbeTreeMap & getChildren () const
std::vector< ProbeType > & getProbes ()
void addProbes (ProbeType Probe)
DerivedProbeInlineTreeType * getOrAddNode (const InlineSite &Site)
Public Attributes
uint64_t Guid = 0
MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType > * Parent
Protected Types
using InlinedProbeTreeMap = std::unordered_map< InlineSite, std::unique_ptr< DerivedProbeInlineTreeType >, InlineSiteHash >
Protected Member Functions
MCPseudoProbeInlineTreeBase ()
Protected Attributes
InlinedProbeTreeMap Children
std::vector< ProbeType > Probes
Detailed Description
template<typename ProbeType, typename DerivedProbeInlineTreeType>
class llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >
Definition at line 215 of file MCPseudoProbe.h.
Member Typedef Documentation
InlinedProbeTreeMap
template<typename ProbeType , typename DerivedProbeInlineTreeType > using llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::InlinedProbeTreeMap = std::unordered_map< InlineSite, std::unique_ptr<DerivedProbeInlineTreeType>, InlineSiteHash> protected
Definition at line 224 of file MCPseudoProbe.h.
Constructor & Destructor Documentation
MCPseudoProbeInlineTreeBase()
template<typename ProbeType , typename DerivedProbeInlineTreeType > llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::MCPseudoProbeInlineTreeBase () inline protected
Definition at line 229 of file MCPseudoProbe.h.
References llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::MCPseudoProbeInlineTreeBase(), and value.
Referenced by llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::MCPseudoProbeInlineTreeBase().
Member Function Documentation
addProbes()
template<typename ProbeType , typename DerivedProbeInlineTreeType > void llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::addProbes (ProbeType Probe) inline
Definition at line 244 of file MCPseudoProbe.h.
References llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Probes.
Referenced by llvm::MCPseudoProbeDecoder::buildAddress2ProbeMap().
getChildren() [1/2]
template<typename ProbeType , typename DerivedProbeInlineTreeType > InlinedProbeTreeMap & llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::getChildren () inline
Definition at line 241 of file MCPseudoProbe.h.
References llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Children.
Referenced by llvm::MCPseudoProbeDecoder::buildAddress2ProbeMap().
getChildren() [2/2]
template<typename ProbeType , typename DerivedProbeInlineTreeType > const InlinedProbeTreeMap & llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::getChildren () const inline
Definition at line 242 of file MCPseudoProbe.h.
References llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Children.
getOrAddNode()
template<typename ProbeType , typename DerivedProbeInlineTreeType > DerivedProbeInlineTreeType * llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::getOrAddNode (const InlineSite & Site) inline
Definition at line 248 of file MCPseudoProbe.h.
References llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Children.
Referenced by llvm::MCPseudoProbeDecoder::buildAddress2ProbeMap().
getProbes()
template<typename ProbeType , typename DerivedProbeInlineTreeType > std::vector< ProbeType > & llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::getProbes () inline
Definition at line 243 of file MCPseudoProbe.h.
References llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Probes.
isRoot()
template<typename ProbeType , typename DerivedProbeInlineTreeType > bool llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::isRoot () const inline
Definition at line 240 of file MCPseudoProbe.h.
References llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Guid.
Referenced by llvm::MCPseudoProbeInlineTree::emit(), and llvm::MCDecodedPseudoProbeInlineTree::hasInlineSite().
Member Data Documentation
Children
template<typename ProbeType , typename DerivedProbeInlineTreeType > InlinedProbeTreeMap llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Children protected
Definition at line 226 of file MCPseudoProbe.h.
Referenced by llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::getChildren(), and llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::getOrAddNode().
Guid
template<typename ProbeType , typename DerivedProbeInlineTreeType > uint64_t llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Guid = 0
Definition at line 237 of file MCPseudoProbe.h.
Referenced by llvm::MCPseudoProbeDecoder::buildAddress2ProbeMap(), llvm::MCDecodedPseudoProbe::getInlineContext(), llvm::MCPseudoProbeDecoder::getInlinerDescForProbe(), and llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::isRoot().
Parent
template<typename ProbeType , typename DerivedProbeInlineTreeType > MCPseudoProbeInlineTreeBase<ProbeType, DerivedProbeInlineTreeType>* llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Parent
Initial value:
=
      nullptr
Definition at line 246 of file MCPseudoProbe.h.
Referenced by llvm::MCDecodedPseudoProbe::getInlineContext(), and llvm::MCPseudoProbeDecoder::getInlinerDescForProbe().
Probes
template<typename ProbeType , typename DerivedProbeInlineTreeType > std::vector<ProbeType> llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::Probes protected
Definition at line 228 of file MCPseudoProbe.h.
Referenced by llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::addProbes(), and llvm::MCPseudoProbeInlineTreeBase< ProbeType, DerivedProbeInlineTreeType >::getProbes().
The documentation for this class was generated from the following file:
include/llvm/MC/MCPseudoProbe.h