LLVM: llvm::SmallVectorTemplateBase< T, bool > Class Template Reference
llvm::SmallVectorTemplateBase< T, bool > Class Template Reference
SmallVectorTemplateBase<TriviallyCopyable = false> - This is where we put method implementations that are designed to work with non-trivial T's.
#include "llvm/ADT/SmallVector.h"
Inherits llvm::SmallVectorTemplateCommon< T, typename >.
Inherited by llvm::SmallVectorImpl< std::pair< ValueType, SUList > >, llvm::SmallVectorImpl< Function * >, llvm::SmallVectorImpl< AddressRange >, llvm::SmallVectorImpl< AddressRangeValuePair >, llvm::SmallVectorImpl< std::unique_ptr< DWARFUnit > >, llvm::SmallVectorImpl< BasicBlock * >, llvm::SmallVectorImpl< llvm::DomTreeNodeBase * >, llvm::SmallVectorImpl< BlockT * >, llvm::SmallVectorImpl< BoUpSLP::EdgeInfo >, llvm::SmallVectorImpl< llvm::MCFixup >, llvm::SmallVectorImpl< char >, llvm::SmallVectorImpl< Edge >, llvm::SmallVectorImpl< llvm::cl::parser::OptionInfo >, llvm::SmallVectorImpl< std::pair< const MachineFunction *, Register > >, llvm::SmallVectorImpl< std::pair< const T *, SPIRV::DTSortableEntry > >, llvm::SmallVectorImpl< std::pair< SPIRV::SpecialTypeDescriptor, SPIRV::DTSortableEntry > >, llvm::SmallVectorImpl< std::pair< KeyT, ValueT > >, llvm::SmallVectorImpl< std::tuple< NodeRef, ChildItTy, ChildItTy > >, llvm::SmallVectorImpl< llvm::AAPointerInfo::Access >, llvm::SmallVectorImpl< Slice >, llvm::SmallVectorImpl< VariableGEPIndex >, llvm::SmallVectorImpl< int >, llvm::SmallVectorImpl< llvm::PointerUnion< llvm::Value *, const TreeEntry * > >, llvm::SmallVectorImpl< llvm::Value * >, llvm::SmallVectorImpl< llvm::Instruction * >, llvm::SmallVectorImpl< const llvm::MachineInstr * >, llvm::SmallVectorImpl< std::pair< const llvm::Function *, const llvm::DISubprogram * > >, llvm::SmallVectorImpl< std::pair< const llvm::Instruction *, bool > >, llvm::SmallVectorImpl< std::pair< const llvm::Instruction *, llvm::WeakVH > >, llvm::SmallVectorImpl< std::pair< const llvm::DILocalVariable *, unsigned > >, llvm::SmallVectorImpl< VarLocInfo >, llvm::SmallVectorImpl< llvm::SUnit * >, llvm::SmallVectorImpl< LiveDebugValues::ValueIDNum >, llvm::SmallVectorImpl< llvm::MachineOperand >, llvm::SmallVectorImpl< std::unique_ptr< llvm::SmallVector > >, llvm::SmallVectorImpl< DebugPHIRecord >, llvm::SmallVectorImpl< ValueIDNum >, llvm::SmallVectorImpl< unsigned >, llvm::SmallVectorImpl< llvm::Register >, llvm::SmallVectorImpl< std::pair< const llvm::MachineOperand *, unsigned > >, llvm::SmallVectorImpl< std::pair< llvm::DebugVariable, LiveDebugValues::DbgValue > >, llvm::SmallVectorImpl< std::pair< StringRef, size_t > >, llvm::SmallVectorImpl< MachineInstr * >, llvm::SmallVectorImpl< std::pair< BlockFrequency, unsigned > >, llvm::SmallVectorImpl< TransferTracker::Transfer >, llvm::SmallVectorImpl< ResolvedDbgOp >, llvm::SmallVectorImpl< DbgOp >, llvm::SmallVectorImpl< uint32_t >, llvm::SmallVectorImpl< DepTy >, llvm::SmallVectorImpl< void(*)(llvm::Function &F, llvm::AnalysisManager &AM, llvm::AAResults &llvm::AAResults) >, llvm::SmallVectorImpl< RangeTy >, llvm::SmallVectorImpl< AAQueryInfo::LocPair >, llvm::SmallVectorImpl< llvm::ForwardedRegister >, llvm::SmallVectorImpl< MILOHDirective >, llvm::SmallVectorImpl< std::pair< unsigned, llvm::MCSymbol * > >, llvm::SmallVectorImpl< llvm::MachineInstr * >, llvm::SmallVectorImpl< llvm::BasicBlockInfo >, llvm::SmallVectorImpl< FCmpLibcallsList >, llvm::SmallVectorImpl< std::pair< StringRef, HashData > >, llvm::SmallVectorImpl< llvm::MemoryLocation >, llvm::SmallVectorImpl< uint8_t >, llvm::SmallVectorImpl< uint16_t >, llvm::SmallVectorImpl< AnalysisID >, llvm::SmallVectorImpl< std::pair< uint16_t, Form > >, llvm::SmallVectorImpl< std::pair< llvm::StringRef, llvm::ArchYAML::Archive::Child::Field > >, llvm::SmallVectorImpl< FreeList * >, llvm::SmallVectorImpl< std::pair< unsigned, llvm::AsmPrinter::MBBSectionRange > >, llvm::SmallVectorImpl< std::pair< const llvm::MCSymbol *, GOTEquivUsePair > >, llvm::SmallVectorImpl< llvm::AsmPrinter::XRayFunctionEntry >, llvm::SmallVectorImpl< std::pair< MCSection *, ConstantPool > >, llvm::SmallVectorImpl< llvm::AssumptionCache::ResultElem >, llvm::SmallVectorImpl< llvm::Attribute >, llvm::SmallVectorImpl< llvm::Function * >, llvm::SmallVectorImpl< llvm::SmallVector * >, llvm::SmallVectorImpl< std::pair< llvm::Use *, llvm::Value * > >, llvm::SmallVectorImpl< std::pair< llvm::Value *, llvm::PointerIntPair< llvm::Value *, 1, bool > > >, llvm::SmallVectorImpl< llvm::WeakVH >, llvm::SmallVectorImpl< llvm::BasicBlock * >, llvm::SmallVectorImpl< llvm::AbstractAttribute * >, llvm::SmallVectorImpl< llvm::Type * >, llvm::SmallVectorImpl< llvm::BitCodeAbbrevOp >, llvm::SmallVectorImpl< BitValue >, llvm::SmallVectorImpl< BitWord >, llvm::SmallVectorImpl< Block >, llvm::SmallVectorImpl< Weight >, llvm::SmallVectorImpl< std::pair< BlockNode, BlockMass > >, llvm::SmallVectorImpl< BlockNode >, llvm::SmallVectorImpl< BlockMass >, llvm::SmallVectorImpl< void * >, llvm::SmallVectorImpl< std::pair< void *, size_t > >, llvm::SmallVectorImpl< llvm::CCValAssign >, llvm::SmallVectorImpl< llvm::ISD::ArgFlagsTy >, llvm::SmallVectorImpl< ByValInfo >, llvm::SmallVectorImpl< llvm::LazyCallGraph::RefSCC * >, llvm::SmallVectorImpl< llvm::LazyCallGraph::SCC * >, llvm::SmallVectorImpl< std::pair< llvm::Value *, llvm::WeakTrackingVH > >, llvm::SmallVectorImpl< ConstantPoolEntry >, llvm::SmallVectorImpl< AttributeItem >, llvm::SmallVectorImpl< Loop * >, llvm::SmallVectorImpl< LoopTripCountTy >, llvm::SmallVectorImpl< LoopCacheCostTy >, llvm::SmallVectorImpl< llvm::CallLowering::ArgInfo >, llvm::SmallVectorImpl< std::pair< MDString *, MethodsList > >, llvm::SmallVectorImpl< Value * >, llvm::SmallVectorImpl< llvm::AllocaInst * >, llvm::SmallVectorImpl< llvm::unique_function< bool(llvm::StringRef)> >, llvm::SmallVectorImpl< llvm::unique_function< void(llvm::StringRef)> >, llvm::SmallVectorImpl< FileInfo >, llvm::SmallVectorImpl< CVGlobalVariable >, llvm::SmallVectorImpl< const llvm::DIDerivedType * >, llvm::SmallVectorImpl< std::pair< const llvm::Function *, std::unique_ptr< FunctionInfo > > >, llvm::SmallVectorImpl< const llvm::DISubprogram * >, llvm::SmallVectorImpl< const llvm::DICompositeType * >, llvm::SmallVectorImpl< const llvm::DILocation * >, llvm::SmallVectorImpl< llvm::codeview::TypeIndex >, llvm::SmallVectorImpl< LocalVariable >, llvm::SmallVectorImpl< LexicalBlock * >, llvm::SmallVectorImpl< std::pair< llvm::CodeViewDebug::LocalVarDef, llvm::SmallVector< std::pair< const llvm::MCSymbol *, const llvm::MCSymbol * >, 1 > > >, llvm::SmallVectorImpl< std::pair< GlobalVariable *, ConstCandVecType > >, llvm::SmallVectorImpl< consthoist::ConstantInfo >, llvm::SmallVectorImpl< std::pair< GlobalVariable *, ConstInfoVecType > >, llvm::SmallVectorImpl< std::pair< llvm::Instruction *, llvm::Instruction * > >, llvm::SmallVectorImpl< llvm::SmallVector< Entry, 8 > >, llvm::SmallVectorImpl< bool >, llvm::SmallVectorImpl< llvm::SDNode * >, llvm::SmallVectorImpl< EdgeType * >, llvm::SmallVectorImpl< llvm::ValueAsMetadata * >, llvm::SmallVectorImpl< llvm::TypedTrackingMDRef >, llvm::SmallVectorImpl< llvm::DISubprogram * >, llvm::SmallVectorImpl< llvm::Metadata * >, llvm::SmallVectorImpl< std::pair< llvm::MDNode *, llvm::SetVector< llvm::Metadata * > > >, llvm::SmallVectorImpl< llvm::DIEAbbrevData >, llvm::SmallVectorImpl< llvm::DILineInfo >, llvm::SmallVectorImpl< TypeUnitMetaInfo >, llvm::SmallVectorImpl< AttributeSpec >, llvm::SmallVectorImpl< llvm::DWARFFormValue >, llvm::SmallVectorImpl< LocationList >, llvm::SmallVectorImpl< llvm::DWARFLocationEntry >, llvm::SmallVectorImpl< Entry >, llvm::SmallVectorImpl< llvm::DWARFDebugNames::NameIndex >, llvm::SmallVectorImpl< uint64_t >, llvm::SmallVectorImpl< Encoding >, llvm::SmallVectorImpl< CompUnitEntry >, llvm::SmallVectorImpl< TypeUnitEntry >, llvm::SmallVectorImpl< AddressEntry >, llvm::SmallVectorImpl< SymTableEntry >, llvm::SmallVectorImpl< std::pair< uint32_t, llvm::SmallVector< uint32_t, 0 > > >, llvm::SmallVectorImpl< llvm::dxbc::PSV::v2::ResourceBindInfo >, llvm::SmallVectorImpl< llvm::DXContainerYAML::SignatureElement >, llvm::SmallVectorImpl< llvm::yaml::Hex32 >, llvm::SmallVectorImpl< llvm::DXContainerYAML::SignatureParameter >, llvm::SmallVectorImpl< unsigned char >, llvm::SmallVectorImpl< LayoutAlignElem >, llvm::SmallVectorImpl< PointerAlignElem >, llvm::SmallVectorImpl< std::pair< InlinedEntity, const MachineInstr * > >, llvm::SmallVectorImpl< std::pair< InlinedEntity, Entries > >, llvm::SmallVectorImpl< llvm::DbgValueLocEntry >, llvm::SmallVectorImpl< int64_t >, llvm::SmallVectorImpl< llvm::DICompileUnit * >, llvm::SmallVectorImpl< llvm::DIGlobalVariableExpression * >, llvm::SmallVectorImpl< llvm::DIType * >, llvm::SmallVectorImpl< llvm::DIScope * >, llvm::SmallVectorImpl< llvm::DbgValueLoc >, llvm::SmallVectorImpl< llvm::DebugLocStream::List >, llvm::SmallVectorImpl< llvm::DebugLocStream::Entry >, llvm::SmallVectorImpl< std::string >, llvm::SmallVectorImpl< llvm::Init * >, llvm::SmallVectorImpl< llvm::DiagnosticInfoOptimizationBase::Argument >, llvm::SmallVectorImpl< NodeType * >, llvm::SmallVectorImpl< llvm::DomTreeNodeBase >, llvm::SmallVectorImpl< DominatorTree::UpdateType >, llvm::SmallVectorImpl< NodeT * >, llvm::SmallVectorImpl< llvm::RangeSpan >, llvm::SmallVectorImpl< const MDNode * >, llvm::SmallVectorImpl< std::pair< const llvm::MDNode *, llvm::DwarfCompileUnit * > >, llvm::SmallVectorImpl< std::unique_ptr< llvm::DbgEntity > >, llvm::SmallVectorImpl< std::pair< std::unique_ptr< llvm::DwarfTypeUnit >, const llvm::DICompositeType * > >, llvm::SmallVectorImpl< llvm::DwarfExpression::Register >, llvm::SmallVectorImpl< std::unique_ptr< llvm::DwarfCompileUnit > >, llvm::SmallVectorImpl< llvm::RangeSpanList >, llvm::SmallVectorImpl< llvm::DbgVariable * >, llvm::SmallVectorImpl< llvm::SmallVector< unsigned, 8 > >, llvm::SmallVectorImpl< std::unique_ptr< llvm::GlobalVariable > >, llvm::SmallVectorImpl< MutableValue >, llvm::SmallVectorImpl< llvm::DomainValue * >, llvm::SmallVectorImpl< LiveRegsDVInfo >, llvm::SmallVectorImpl< std::unique_ptr< llvm::Module > >, llvm::SmallVectorImpl< llvm::GlobalValue * >, llvm::SmallVectorImpl< llvm::ISD::InputArg >, llvm::SmallVectorImpl< std::pair< llvm::Instruction *, llvm::ConstantRange > >, llvm::SmallVectorImpl< std::pair< llvm::Instruction *, llvm::Value * > >, llvm::SmallVectorImpl< T * >, llvm::SmallVectorImpl< llvm::FunctionLoweringInfo::LiveOutInfo >, llvm::SmallVectorImpl< llvm::BBClusterInfo >, llvm::SmallVectorImpl< llvm::SmallVector< unsigned > >, llvm::SmallVectorImpl< llvm::DebugVariable >, llvm::SmallVectorImpl< llvm::VarLocInfo >, llvm::SmallVectorImpl< std::unique_ptr< llvm::GCStrategy > >, llvm::SmallVectorImpl< GCNSchedStageID >, llvm::SmallVectorImpl< std::pair< llvm::MachineInstrBundleIterator, llvm::MachineInstrBundleIterator > >, llvm::SmallVectorImpl< llvm::DenseMap >, llvm::SmallVectorImpl< llvm::GCNRegPressure >, llvm::SmallVectorImpl< llvm::GCOVArc * >, llvm::SmallVectorImpl< std::unique_ptr< llvm::GCOVFunction > >, llvm::SmallVectorImpl< std::unique_ptr< llvm::GCOVBlock > >, llvm::SmallVectorImpl< std::unique_ptr< llvm::GCOVArc > >, llvm::SmallVectorImpl< llvm::LLT >, llvm::SmallVectorImpl< llvm::GISelChangeObserver * >, llvm::SmallVectorImpl< std::pair< llvm::Value *, llvm::Value * > >, llvm::SmallVectorImpl< std::pair< llvm::Instruction *, unsigned > >, llvm::SmallVectorImpl< const CycleT * >, llvm::SmallVectorImpl< SubGlobPattern >, llvm::SmallVectorImpl< llvm::GlobPattern::SubGlobPattern::Bracket >, llvm::SmallVectorImpl< llvm::cfg::Update< NodePtr > >, llvm::SmallVectorImpl< NodePtr >, llvm::SmallVectorImpl< MCOperand >, llvm::SmallVectorImpl< HexagonInstr >, llvm::SmallVectorImpl< llvm::HexagonInstr * >, llvm::SmallVectorImpl< NodeTy * >, llvm::SmallVectorImpl< llvm::cfg::Update< llvm::BasicBlock * > >, llvm::SmallVectorImpl< std::pair< unsigned, llvm::MDNode * > >, llvm::SmallVectorImpl< std::pair< const llvm::PHINode *, llvm::SmallVector< llvm::MachineInstr *, 1 > > >, llvm::SmallVectorImpl< InlineGraphNode * >, llvm::SmallVectorImpl< uintptr_t >, llvm::SmallVectorImpl< Meta >, llvm::SmallVectorImpl< const llvm::SCEV * >, llvm::SmallVectorImpl< const llvm::Instruction * >, llvm::SmallVectorImpl< Instruction * >, llvm::SmallVectorImpl< const char * >, llvm::SmallVectorImpl< llvm::WeakTrackingVH >, llvm::SmallVectorImpl< llvm::CallBase * >, llvm::SmallVectorImpl< std::pair< const llvm::RecurrenceDescriptor *, llvm::PHINode * > >, llvm::SmallVectorImpl< std::pair< llvm::SlotIndex, llvm::SlotIndex > >, llvm::SmallVectorImpl< llvm::TemporalProfTraceTy >, llvm::SmallVectorImpl< std::pair< uint64_t, llvm::memprof::IndexedMemProfRecord > >, llvm::SmallVectorImpl< std::pair< uint64_t, llvm::memprof::Frame > >, llvm::SmallVectorImpl< std::function< void(MachineInstrBuilder &)> >, llvm::SmallVectorImpl< llvm::InstructionBuildSteps >, llvm::SmallVectorImpl< RegUnitInfo >, llvm::SmallVectorImpl< BlockInterference >, llvm::SmallVectorImpl< DataType >, llvm::SmallVectorImpl< PointType >, llvm::SmallVectorImpl< const DataType * >, llvm::SmallVectorImpl< const llvm::Value * >, llvm::SmallVectorImpl< ScopeContext >, llvm::SmallVectorImpl< llvm::MCRegister >, llvm::SmallVectorImpl< llvm::Loop * >, llvm::SmallVectorImpl< llvm::MCSymbol * >, llvm::SmallVectorImpl< llvm::SEHHandler >, llvm::SmallVectorImpl< llvm::LazyCallGraph::Node * >, llvm::SmallVectorImpl< std::pair< llvm::BasicBlock *, llvm::Value * > >, llvm::SmallVectorImpl< SizeChangeStrategy >, llvm::SmallVectorImpl< SizeAndActionsVec >, llvm::SmallVectorImpl< llvm::LegalizeRule >, llvm::SmallVectorImpl< std::pair< bool, llvm::StringRef > >, llvm::SmallVectorImpl< llvm::LexicalScope * >, llvm::SmallVectorImpl< InsnRange >, llvm::SmallVectorImpl< const llvm::LiveInterval * >, llvm::SmallVectorImpl< llvm::LiveInterval * >, llvm::SmallVectorImpl< llvm::SlotIndex >, llvm::SmallVectorImpl< const uint32_t * >, llvm::SmallVectorImpl< std::pair< unsigned, unsigned > >, llvm::SmallVectorImpl< llvm::LiveRange * >, llvm::SmallVectorImpl< MCPhysReg >, llvm::SmallVectorImpl< Segment >, llvm::SmallVectorImpl< VNInfo * >, llvm::SmallVectorImpl< LiveOutPair >, llvm::SmallVectorImpl< LiveInBlock >, llvm::SmallVectorImpl< llvm::LiveRange::Segment >, llvm::SmallVectorImpl< IndexMaskPair >, llvm::SmallVectorImpl< llvm::LiveVariables::VarInfo >, llvm::SmallVectorImpl< llvm::GStore * >, llvm::SmallVectorImpl< std::pair< llvm::MachineInstr *, unsigned > >, llvm::SmallVectorImpl< llvm::StoreInst * >, llvm::SmallVectorImpl< MBBInfo >, llvm::SmallVectorImpl< std::pair< llvm::Instruction *, uint64_t > >, llvm::SmallVectorImpl< std::pair< PHINode *, RecurrenceDescriptor > >, llvm::SmallVectorImpl< std::pair< PHINode *, InductionDescriptor > >, llvm::SmallVectorImpl< VPlanPtr >, llvm::SmallVectorImpl< llvm::VectorizationFactor >, llvm::SmallVectorImpl< RuntimePointerCheck >, llvm::SmallVectorImpl< llvm::DebugLoc >, llvm::SmallVectorImpl< llvm::MCSection * >, llvm::SmallVectorImpl< llvm::AsmToken >, llvm::SmallVectorImpl< llvm::MCAsmParser::MCPendingError >, llvm::SmallVectorImpl< std::pair< const llvm::MCSymbol *, const llvm::MCSymbol * > >, llvm::SmallVectorImpl< std::pair< std::string, std::string > >, llvm::SmallVectorImpl< llvm::MCDwarfFile >, llvm::SmallVectorImpl< llvm::MCELFStreamer::AttributeItem >, llvm::SmallVectorImpl< llvm::MCDataFragment * >, llvm::SmallVectorImpl< llvm::MCOperand >, llvm::SmallVectorImpl< llvm::object::OwningBinary< llvm::object::Archive > >, llvm::SmallVectorImpl< std::unique_ptr< llvm::MemoryBuffer > >, llvm::SmallVectorImpl< std::unique_ptr< llvm::object::ObjectFile > >, llvm::SmallVectorImpl< llvm::MCLOHDirective >, llvm::SmallVectorImpl< std::pair< MCSection *, MCDwarfLineEntryCollection > >, llvm::SmallVectorImpl< PendingMCFixup >, llvm::SmallVectorImpl< std::pair< unsigned, llvm::MCFragment * > >, llvm::SmallVectorImpl< PendingLabel >, llvm::SmallVectorImpl< std::pair< size_t, llvm::MCSection * > >, llvm::SmallVectorImpl< std::pair< MCSectionSubPair, MCSectionSubPair > >, llvm::SmallVectorImpl< llvm::MDAttachments::Attachment >, llvm::SmallVectorImpl< llvm::StringRef >, llvm::SmallVectorImpl< Target >, llvm::SmallVectorImpl< std::pair< llvm::MachO::ObjCIVarRecord, ValueT > >, llvm::SmallVectorImpl< std::pair< llvm::StringRef, llvm::MachO::ObjCCategoryRecord * > >, llvm::SmallVectorImpl< std::pair< llvm::MachO::GlobalRecord, ValueT > >, llvm::SmallVectorImpl< std::pair< llvm::MachO::ObjCInterfaceRecord, ValueT > >, llvm::SmallVectorImpl< std::pair< llvm::MachO::ObjCCategoryRecord, std::pair< llvm::StringRef, llvm::StringRef > > >, llvm::SmallVectorImpl< llvm::MachineBasicBlock * >, llvm::SmallVectorImpl< CriticalEdge >, llvm::SmallVectorImpl< std::pair< int, int64_t > >, llvm::SmallVectorImpl< VariableDbgInfo >, llvm::SmallVectorImpl< llvm::MachineFunction::DebugSubstitution >, llvm::SmallVectorImpl< llvm::unique_function< FuncTy > >, llvm::SmallVectorImpl< std::pair< llvm::PointerUnion, llvm::MachineOperand * > >, llvm::SmallVectorImpl< std::pair< unsigned, llvm::SmallVector< llvm::Register, 4 > > >, llvm::SmallVectorImpl< LLT >, llvm::SmallVectorImpl< llvm::MachineTraceMetrics::FixedBlockInfo >, llvm::SmallVectorImpl< llvm::MachineTraceMetrics::TraceBlockInfo >, llvm::SmallVectorImpl< llvm::MachineTraceMetrics::LiveInReg >, llvm::SmallVectorImpl< llvm::MemoryDepChecker::Dependence >, llvm::SmallVectorImpl< llvm::AssertingVH< llvm::MemoryPhi > >, llvm::SmallVectorImpl< Inst >, llvm::SmallVectorImpl< std::unique_ptr< llvm::MipsOptionRecord > >, llvm::SmallVectorImpl< const BlockT * >, llvm::SmallVectorImpl< std::unique_ptr< llvm::ScheduleHazardRecognizer > >, llvm::SmallVectorImpl< llvm::OpenMPIRBuilder::FinalizationInfo >, llvm::SmallVectorImpl< llvm::OpenMPIRBuilder::OutlineInfo >, llvm::SmallVectorImpl< DeviceInfoTy >, llvm::SmallVectorImpl< omp::OpenMPOffloadMappingFlags >, llvm::SmallVectorImpl< Constant * >, llvm::SmallVectorImpl< MapValuesArrayTy >, llvm::SmallVectorImpl< std::pair< const llvm::Value *, std::pair< llvm::Value *, llvm::Value * > > >, llvm::SmallVectorImpl< llvm::Pass * >, llvm::SmallVectorImpl< llvm::PMDataManager * >, llvm::SmallVectorImpl< llvm::ImmutablePass * >, llvm::SmallVectorImpl< ParamType >, llvm::SmallVectorImpl< llvm::AsmRewrite >, llvm::SmallVectorImpl< std::function< void(llvm::PassManager &, llvm::OptimizationLevel)> >, llvm::SmallVectorImpl< std::function< void(llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > &, llvm::OptimizationLevel)> >, llvm::SmallVectorImpl< std::function< void(PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & > &, llvm::OptimizationLevel)> >, llvm::SmallVectorImpl< std::function< void(llvm::AnalysisManager &)> >, llvm::SmallVectorImpl< std::function< bool(llvm::StringRef, llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorImpl< std::function< bool(llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorImpl< std::function< bool(llvm::StringRef, PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & > &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorImpl< std::function< bool(llvm::StringRef, llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorImpl< std::function< bool(llvm::StringRef Name, llvm::AAManager &AA)> >, llvm::SmallVectorImpl< std::function< void(llvm::MachineFunctionAnalysisManager &)> >, llvm::SmallVectorImpl< std::function< bool(llvm::StringRef, llvm::MachineFunctionPassManager &)> >, llvm::SmallVectorImpl< InsertedPass >, llvm::SmallVectorImpl< llvm::unique_function< BeforePassFunc > >, llvm::SmallVectorImpl< llvm::unique_function< BeforeSkippedPassFunc > >, llvm::SmallVectorImpl< llvm::unique_function< BeforeNonSkippedPassFunc > >, llvm::SmallVectorImpl< llvm::unique_function< AfterPassFunc > >, llvm::SmallVectorImpl< llvm::unique_function< AfterPassInvalidatedFunc > >, llvm::SmallVectorImpl< llvm::unique_function< BeforeAnalysisFunc > >, llvm::SmallVectorImpl< llvm::unique_function< AfterAnalysisFunc > >, llvm::SmallVectorImpl< llvm::unique_function< AnalysisInvalidatedFunc > >, llvm::SmallVectorImpl< llvm::unique_function< AnalysesClearedFunc > >, llvm::SmallVectorImpl< DDGNode * >, llvm::SmallVectorImpl< MemberTy >, llvm::SmallVectorImpl< std::pair< unsigned, llvm::MapVector< llvm::MachineInstr *, llvm::MachineInstr * > > >, llvm::SmallVectorImpl< llvm::AssertingVH< llvm::Function > >, llvm::SmallVectorImpl< ValueInfo >, llvm::SmallVectorImpl< llvm::PredicateBase * >, llvm::SmallVectorImpl< PassRunDescriptor >, llvm::SmallVectorImpl< llvm::SpillPlacement::BlockConstraint >, llvm::SmallVectorImpl< GlobalSplitCandidate >, llvm::SmallVectorImpl< RegInfo >, llvm::SmallVectorImpl< TraversedMBBInfo >, llvm::SmallVectorImpl< LiveRegsDefInfo >, llvm::SmallVectorImpl< MBBDefsInfo >, llvm::SmallVectorImpl< llvm::SMLoc >, llvm::SmallVectorImpl< llvm::SMRange >, llvm::SmallVectorImpl< llvm::RecordVal >, llvm::SmallVectorImpl< llvm::Record::AssertionInfo >, llvm::SmallVectorImpl< llvm::Record::DumpInfo >, llvm::SmallVectorImpl< std::pair< llvm::Record *, llvm::SMRange > >, llvm::SmallVectorImpl< std::unique_ptr< InsertPoint > >, llvm::SmallVectorImpl< ScavengedInfo >, llvm::SmallVectorImpl< llvm::RegisterMaskPair >, llvm::SmallVectorImpl< llvm::EVT >, llvm::SmallVectorImpl< llvm::MVT >, llvm::SmallVectorImpl< std::unique_ptr< llvm::DFAPacketizer > >, llvm::SmallVectorImpl< llvm::SmallVector< uint64_t, DefaultProcResSize > >, llvm::SmallVectorImpl< NodeRef >, llvm::SmallVectorImpl< SID >, llvm::SmallVectorImpl< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >, llvm::SmallVectorImpl< IFuncStub >, llvm::SmallVectorImpl< llvm::RuntimeDyldMachO::EHFrameRelatedSections >, llvm::SmallVectorImpl< llvm::RuntimePointerChecking::PointerInfo >, llvm::SmallVectorImpl< llvm::RuntimeCheckingPtrGroup >, llvm::SmallVectorImpl< llvm::PointerDiffInfo >, llvm::SmallVectorImpl< std::pair< llvm::Function *, llvm::ValueLatticeElement > >, llvm::SmallVectorImpl< std::pair< std::pair< llvm::Function *, unsigned >, llvm::ValueLatticeElement > >, llvm::SmallVectorImpl< SCEVInsertPointGuard * >, llvm::SmallVectorImpl< const llvm::SCEVPredicate * >, llvm::SmallVectorImpl< llvm::SDDbgValue * >, llvm::SmallVectorImpl< llvm::SDDbgLabel * >, llvm::SmallVectorImpl< std::pair< Register, int > >, llvm::SmallVectorImpl< Register >, llvm::SmallVectorImpl< std::pair< Value *, StoreList > >, llvm::SmallVectorImpl< std::pair< Value *, GEPList > >, llvm::SmallVectorImpl< llvm::SMFixIt >, llvm::SmallVectorImpl< llvm::SPIRV::DTSortableEntry * >, llvm::SmallVectorImpl< SPIRV::Capability::Capability >, llvm::SmallVectorImpl< Capability::Capability >, llvm::SmallVectorImpl< Extension::Extension >, llvm::SmallVectorImpl< std::pair< KeyTy, SPIRV::DTSortableEntry > >, llvm::SmallVectorImpl< std::pair< const llvm::Type *, SPIRV::DTSortableEntry > >, llvm::SmallVectorImpl< std::pair< const llvm::Constant *, SPIRV::DTSortableEntry > >, llvm::SmallVectorImpl< std::pair< const llvm::GlobalVariable *, SPIRV::DTSortableEntry > >, llvm::SmallVectorImpl< std::pair< const llvm::Function *, SPIRV::DTSortableEntry > >, llvm::SmallVectorImpl< std::pair< const llvm::Argument *, SPIRV::DTSortableEntry > >, llvm::SmallVectorImpl< std::pair< const llvm::SPIRV::SpecialTypeDescriptor *, SPIRV::DTSortableEntry > >, llvm::SmallVectorImpl< SPIRV::Extension::Extension >, llvm::SmallVectorImpl< SPIRV::InstructionSet::InstructionSet >, llvm::SmallVectorImpl< llvm::PHINode * >, llvm::SmallVectorImpl< RewriteInfo >, llvm::SmallVectorImpl< llvm::Use * >, llvm::SmallVectorImpl< PhiT * >, llvm::SmallVectorImpl< llvm::SDep >, llvm::SmallVectorImpl< ExitNotTakenInfo >, llvm::SmallVectorImpl< llvm::APInt >, llvm::SmallVectorImpl< RootData >, llvm::SmallVectorImpl< TreeData >, llvm::SmallVectorImpl< SMSNode >, llvm::SmallVectorImpl< std::pair< llvm::SUnit *, llvm::SUnit * > >, llvm::SmallVectorImpl< llvm::sys::MemoryBlock >, llvm::SmallVectorImpl< FreeMemBlock >, llvm::SmallVectorImpl< std::pair< const llvm::Value *, DanglingDebugInfoVector > >, llvm::SmallVectorImpl< llvm::SDValue >, llvm::SmallVectorImpl< const llvm::GCRelocateInst * >, llvm::SmallVectorImpl< IdxMBBPair >, llvm::SmallVectorImpl< ValueT >, llvm::SmallVectorImpl< llvm::ArgInfo >, llvm::SmallVectorImpl< llvm::BlockFrequency >, llvm::SmallVectorImpl< llvm::SplitAnalysis::BlockInfo >, llvm::SmallVectorImpl< const llvm::IntrinsicInst * >, llvm::SmallVectorImpl< llvm::StackLifetime::LiveRange >, llvm::SmallVectorImpl< std::pair< uint64_t, uint64_t > >, llvm::SmallVectorImpl< std::pair< const MCSymbol *, FunctionInfo > >, llvm::SmallVectorImpl< Location >, llvm::SmallVectorImpl< LiveOutReg >, llvm::SmallVectorImpl< llvm::ArgumentInit * >, llvm::SmallVectorImpl< llvm::IRPosition >, llvm::SmallVectorImpl< llvm::SuffixTreeInternalNode * >, llvm::SmallVectorImpl< const Value * >, llvm::SmallVectorImpl< llvm::SmallPtrSet< llvm::SUnit *, 4 > >, llvm::SmallVectorImpl< llvm::SmallVector< int, 4 > >, llvm::SmallVectorImpl< BitTestCase >, llvm::SmallVectorImpl< std::pair< std::pair< const MCSymbol *, unsigned >, uint32_t > >, llvm::SmallVectorImpl< llvm::DefsetRecord * >, llvm::SmallVectorImpl< std::pair< GlobalVariable *, tlshoist::TLSCandidate > >, llvm::SmallVectorImpl< llvm::ISD::OutputArg >, llvm::SmallVectorImpl< llvm::Timer * >, llvm::SmallVectorImpl< TimeTraceProfilerEntry >, llvm::SmallVectorImpl< llvm::TruncInst * >, llvm::SmallVectorImpl< std::pair< llvm::Instruction *, Info > >, llvm::SmallVectorImpl< llvm::VFInfo >, llvm::SmallVectorImpl< llvm::VFParameter >, llvm::SmallVectorImpl< llvm::VPBlockBase * >, llvm::SmallVectorImpl< llvm::VPHeaderPHIRecipe * >, llvm::SmallVectorImpl< llvm::VPValue * >, llvm::SmallVectorImpl< llvm::VPUser * >, llvm::SmallVectorImpl< llvm::VPBasicBlock * >, llvm::SmallVectorImpl< llvm::ElementCount >, llvm::SmallVectorImpl< std::pair< llvm::PHINode *, llvm::VPLiveOut * > >, llvm::SmallVectorImpl< VPBlockBase * >, llvm::SmallVectorImpl< MultiNodeOpTy >, llvm::SmallVectorImpl< wasm::ValType >, llvm::SmallVectorImpl< llvm::SmallVector< wasm::ValType, 4 > >, llvm::SmallVectorImpl< std::pair< uint64_t, bool > >, llvm::SmallVectorImpl< EHInstKind >, llvm::SmallVectorImpl< std::pair< llvm::MCSymbol *, llvm::WinEH::FrameInfo::Epilog > >, llvm::SmallVectorImpl< std::pair< llvm::MCSymbol *, int64_t > >, llvm::SmallVectorImpl< llvm::CxxUnwindMapEntry >, llvm::SmallVectorImpl< llvm::WinEHTryBlockMapEntry >, llvm::SmallVectorImpl< llvm::SEHUnwindMapEntry >, llvm::SmallVectorImpl< llvm::ClrEHUnwindMapEntry >, llvm::SmallVectorImpl< llvm::WinEHHandlerType >, llvm::SmallVectorImpl< size_t >, llvm::SmallVectorImpl< llvm::SmallVector< size_t, 4 > >, llvm::SmallVectorImpl< llvm::cl::OptionCategory * >, llvm::SmallVectorImpl< llvm::cl::Option * >, llvm::SmallVectorImpl< llvm::cl::SubCommand * >, llvm::SmallVectorImpl< llvm::cl::OptionEnumValue >, llvm::SmallVectorImpl< llvm::ArrayRef< uint8_t > >, llvm::SmallVectorImpl< RecordLimit >, llvm::SmallVectorImpl< llvm::codeview::GloballyHashedType >, llvm::SmallVectorImpl< ConstantUser >, llvm::SmallVectorImpl< RebasedConstantInfo >, llvm::SmallVectorImpl< llvm::AnyCoroEndInst * >, llvm::SmallVectorImpl< llvm::CoroSizeInst * >, llvm::SmallVectorImpl< llvm::CoroAlignInst * >, llvm::SmallVectorImpl< llvm::AnyCoroSuspendInst * >, llvm::SmallVectorImpl< llvm::CallInst * >, llvm::SmallVectorImpl< const llvm::coverage::CoverageSegment * >, llvm::SmallVectorImpl< TestVector >, llvm::SmallVectorImpl< llvm::detail::PtrUseVisitorBase::UseToVisit >, llvm::SmallVectorImpl< PatchLocation >, llvm::SmallVectorImpl< AccelTableKind >, llvm::SmallVectorImpl< llvm::dwarf_linker::parallel::CompileUnit::DIEInfo >, llvm::SmallVectorImpl< llvm::StringMapEntry * >, llvm::SmallVectorImpl< uint64_t * >, llvm::SmallVectorImpl< std::unique_ptr< llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext > >, llvm::SmallVectorImpl< std::unique_ptr< CompileUnit > >, llvm::SmallVectorImpl< RefModuleUnit >, llvm::SmallVectorImpl< DWARFLinkerBase::AccelTableKind >, llvm::SmallVectorImpl< LiveRootWorklistItemTy >, llvm::SmallVectorImpl< const llvm::StringMapEntry * >, llvm::SmallVectorImpl< llvm::dxil::UAVResource >, llvm::SmallVectorImpl< llvm::dxil::ConstantBuffer >, llvm::SmallVectorImpl< llvm::fuzzerop::SourcePred >, llvm::SmallVectorImpl< SmallVector< uint64_t, 4 > >, llvm::SmallVectorImpl< ElemT >, llvm::SmallVectorImpl< llvm::jitlink::ppc64::PLTCallStubReloc >, llvm::SmallVectorImpl< State >, llvm::SmallVectorImpl< LVLine * >, llvm::SmallVectorImpl< LVScope * >, llvm::SmallVectorImpl< LVSymbol * >, llvm::SmallVectorImpl< LVType * >, llvm::SmallVectorImpl< LVElement * >, llvm::SmallVectorImpl< LVTotalsEntry >, llvm::SmallVectorImpl< std::pair< StringRef, BitcodeModule > >, llvm::SmallVectorImpl< EncodingInfo >, llvm::SmallVectorImpl< std::unique_ptr< llvm::mca::HardwareUnit > >, llvm::SmallVectorImpl< std::unique_ptr< llvm::mca::Instruction > >, llvm::SmallVectorImpl< llvm::mca::InstRef >, llvm::SmallVectorImpl< llvm::mca::WriteDescriptor >, llvm::SmallVectorImpl< llvm::mca::ReadDescriptor >, llvm::SmallVectorImpl< std::pair< uint64_t, llvm::mca::ResourceUsage > >, llvm::SmallVectorImpl< llvm::mca::WriteState >, llvm::SmallVectorImpl< llvm::mca::ReadState >, llvm::SmallVectorImpl< ResourceUse >, llvm::SmallVectorImpl< llvm::mca::MemoryGroup * >, llvm::SmallVectorImpl< std::unique_ptr< llvm::mca::Stage > >, llvm::SmallVectorImpl< RegisterMappingTracker >, llvm::SmallVectorImpl< std::pair< llvm::mca::ReadState *, int > >, llvm::SmallVectorImpl< llvm::mcdxbc::PSVSignatureElement >, llvm::SmallVectorImpl< Parameter >, llvm::SmallVectorImpl< llvm::memprof::Frame >, llvm::SmallVectorImpl< llvm::memprof::IndexedAllocationInfo >, llvm::SmallVectorImpl< llvm::SmallVector< uint64_t > >, llvm::SmallVectorImpl< llvm::memprof::AllocationInfo >, llvm::SmallVectorImpl< llvm::SmallVector< llvm::memprof::Frame > >, llvm::SmallVectorImpl< SegmentEntry >, llvm::SmallVectorImpl< std::pair< uint64_t, MemInfoBlock > >, llvm::SmallVectorImpl< llvm::IntrinsicInst * >, llvm::SmallVectorImpl< llvm::DbgVariableIntrinsic * >, llvm::SmallVectorImpl< std::pair< llvm::AllocaInst *, llvm::memtag::AllocaInfo > >, llvm::SmallVectorImpl< llvm::objcopy::elf::SectionBase * >, llvm::SmallVectorImpl< SectionInfo >, llvm::SmallVectorImpl< NodeState >, llvm::SmallVectorImpl< const uint8_t * >, llvm::SmallVectorImpl< llvm::object::DataRefImpl >, llvm::SmallVectorImpl< LoadCommandInfo >, llvm::SmallVectorImpl< StringRef >, llvm::SmallVectorImpl< std::pair< llvm::StringRef, llvm::StringRef > >, llvm::SmallVectorImpl< llvm::object::PGOAnalysisMap::PGOBBEntry::SuccessorEntry >, llvm::SmallVectorImpl< TraitProperty >, llvm::SmallVectorImpl< Arg * >, llvm::SmallVectorImpl< std::unique_ptr< llvm::opt::Arg > >, llvm::SmallVectorImpl< llvm::StringLiteral >, llvm::SmallVectorImpl< std::pair< std::string, llvm::orc::ExecutorAddr > >, llvm::SmallVectorImpl< std::tuple< ExecutorAddr, ExecutorAddr, MachOExecutorSymbolFlags > >, llvm::SmallVectorImpl< llvm::orc::ExecutorAddrRange >, llvm::SmallVectorImpl< InjectedSourceDescriptor >, llvm::SmallVectorImpl< const llvm::TargetRegisterClass * >, llvm::SmallVectorImpl< llvm::remarks::BitstreamRemarkParserHelper::Argument >, llvm::SmallVectorImpl< llvm::remarks::Argument >, llvm::SmallVectorImpl< StackRegion >, llvm::SmallVectorImpl< StackObject >, llvm::SmallVectorImpl< std::pair< llvm::sampleprof::FunctionId, uint32_t > >, llvm::SmallVectorImpl< llvm::sampleprof::SecHdrTableEntry >, llvm::SmallVectorImpl< std::pair< llvm::sampleprof::SampleContext, uint64_t > >, llvm::SmallVectorImpl< std::pair< llvm::sampleprof::SampleContext, uint32_t > >, llvm::SmallVectorImpl< const SamplesWithLoc * >, llvm::SmallVectorImpl< std::unique_ptr< TreeEntry > >, llvm::SmallVectorImpl< const TreeEntry * >, llvm::SmallVectorImpl< ExternalUser >, llvm::SmallVectorImpl< std::pair< llvm::BasicBlock *, std::unique_ptr< BlockScheduling > > >, llvm::SmallVectorImpl< std::unique_ptr< ScheduleData[]> >, llvm::SmallVectorImpl< ScheduleData * >, llvm::SmallVectorImpl< llvm::slpvectorizer::BoUpSLP::EdgeInfo >, llvm::SmallVectorImpl< SmallVector< Value *, 8 > >, llvm::SmallVectorImpl< llvm::SmallVector >, llvm::SmallVectorImpl< const MMap * >, llvm::SmallVectorImpl< llvm::symbolize::MarkupNode >, llvm::SmallVectorImpl< llvm::tlshoist::TLSUser >, llvm::SmallVectorImpl< IntrusiveRefCntPtr< FileSystem > >, llvm::SmallVectorImpl< llvm::vfs::RedirectingFileSystem::Entry * >, llvm::SmallVectorImpl< ValType >, llvm::SmallVectorImpl< TrieNode * >, llvm::SmallVectorImpl< llvm::yaml::StringValue >, llvm::SmallVectorImpl< SimpleKey >, and llvm::SmallVectorImpl< T >.
Public Member Functions
void push_back (const T &Elt)
void push_back (T &&Elt)
void pop_back ()
Public Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
size_t size () const
size_t capacity () const
bool empty () const
Protected Types
using ValueParamT = const T &
Protected Member Functions
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
T * mallocForGrow (size_t MinSize, size_t &NewCapacity)
Create a new allocation big enough for MinSize and pass back its size in NewCapacity.
void moveElementsForGrow (T *NewElts)
Move existing elements over to the new allocation NewElts, the middle section of grow().
void takeAllocationForGrow (T *NewElts, size_t NewCapacity)
Transfer ownership of the allocation, finishing up grow().
const T * reserveForParamAndGetAddress (const T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
T * reserveForParamAndGetAddress (T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
void growAndAssign (size_t NumElts, const T &Elt)
template<typename... ArgTypes>
T & growAndEmplaceBack (ArgTypes &&... Args)
Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
void * getFirstEl () const
Find the address of the first element.
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSize, size_t TSize)
bool isSmall () const
Return true if this is a smallvector which has not had dynamic memory allocated for it.
void resetToSmall ()
Put this vector in a state of being small.
bool isReferenceToRange (const void *V, const void *First, const void *Last) const
Return true if V is an internal reference to the given range.
bool isReferenceToStorage (const void *V) const
Return true if V is an internal reference to this vector.
bool isRangeInStorage (const void *First, const void *Last) const
Return true if First and Last form a valid (possibly empty) range in this vector's storage.
bool isSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Return true unless Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Check whether Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToAdd (const void *Elt, size_t N=1)
Check whether Elt will be invalidated by increasing the size of the vector by N.
void assertSafeToReferenceAfterClear (const T *From, const T *To)
Check whether any part of the range will be invalidated by clearing.
template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToReferenceAfterClear (ItTy, ItTy)
void assertSafeToAddRange (const T *From, const T *To)
Check whether any part of the range will be invalidated by growing.
template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToAddRange (ItTy, ItTy)
Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void * mallocForGrow (void *FirstEl, size_t MinSize, size_t TSize, size_t &NewCapacity)
This is a helper for grow() that's out of line to reduce code duplication.
void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
void * replaceAllocation (void *NewElts, size_t TSize, size_t NewCapacity, size_t VSize=0)
If vector was first created with capacity 0, getFirstEl() points to the memory right after, an area unallocated.
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
void set_allocation_range (void *Begin, size_t N)
Set the array data pointer to Begin and capacity to N.
Static Protected Member Functions
static void destroy_range (T *S, T *E)
template<typename It1 , typename It2 >
static void uninitialized_move (It1 I, It1 E, It2 Dest)
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
static T && forward_value_param (T &&V)
static const T & forward_value_param (const T &V)
Static Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
template<class U >
static const T * reserveForParamAndGetAddressImpl (U *This, const T &Elt, size_t N)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Static Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
Static Protected Attributes
static constexpr bool TakesParamByValue = false
Friends
class SmallVectorTemplateCommon< T >
Additional Inherited Members
Public Types inherited from llvm::SmallVectorTemplateCommon< T, typename >
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using reverse_iterator = std::reverse_iterator< iterator >
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Protected Attributes inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
void * BeginX
SmallVectorSizeType< T > Size
SmallVectorSizeType< T > Capacity
Detailed Description
template<typename T, bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value>
class llvm::SmallVectorTemplateBase< T, bool >
SmallVectorTemplateBase<TriviallyCopyable = false> - This is where we put method implementations that are designed to work with non-trivial T's.
We approximate is_trivially_copyable with trivial move/copy construction and trivial destruction. While the standard doesn't specify that you're allowed copy these types with memcpy, there is no way for the type to observe this. This catches the important case of std::pair<POD, POD>, which is not trivially assignable.
Definition at line 342 of file SmallVector.h.
Member Typedef Documentation
ValueParamT
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> using llvm::SmallVectorTemplateBase< T, bool >::ValueParamT = const T & protected
Definition at line 347 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorTemplateBase()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> llvm::SmallVectorTemplateBase< T, bool >::SmallVectorTemplateBase (size_t Size) inline protected
Definition at line 349 of file SmallVector.h.
Member Function Documentation
destroy_range()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> static void llvm::SmallVectorTemplateBase< T, bool >::destroy_range (T * S, T * E) inline static protected
Definition at line 351 of file SmallVector.h.
References E.
Referenced by llvm::SmallVectorImpl< T >::assign(), llvm::SmallVectorImpl< T >::assignRemote(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorImpl< T >::erase(), llvm::SmallVectorTemplateBase< T, bool >::growAndAssign(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< T >::swap(), and llvm::SmallVectorImpl< T >::truncate().
forward_value_param() [1/2]
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> static const T & llvm::SmallVectorTemplateBase< T, bool >::forward_value_param (const T & V) inline static protected
Definition at line 402 of file SmallVector.h.
forward_value_param() [2/2]
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> static T && llvm::SmallVectorTemplateBase< T, bool >::forward_value_param (T && V) inline static protected
Definition at line 401 of file SmallVector.h.
Referenced by llvm::SmallVectorImpl< T >::insert().
grow()
template<typename T , bool TriviallyCopyable> void llvm::SmallVectorTemplateBase< T, TriviallyCopyable >::grow (size_t MinSize = 0) protected
Grow the allocated memory (without initializing new elements), doubling the size of the allocated memory.
Guarantees space for at least one more element, or MinSize more elements if specified.
Definition at line 446 of file SmallVector.h.
Referenced by llvm::SmallVectorTemplateBase< T, true >::growAndAssign(), llvm::SmallVectorImpl< T >::operator=(), and llvm::SmallVectorImpl< T >::reserve().
growAndAssign()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> void llvm::SmallVectorTemplateBase< T, bool >::growAndAssign (size_t NumElts, const T & Elt) inline protected
Definition at line 404 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::mallocForGrow(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and llvm::SmallVectorTemplateBase< T, bool >::takeAllocationForGrow().
Referenced by llvm::SmallVectorImpl< T >::assign().
growAndEmplaceBack()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> template<typename... ArgTypes> T & llvm::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack (ArgTypes &&... Args) inline protected
Definition at line 414 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateBase< T, bool >::mallocForGrow(), llvm::SmallVectorTemplateBase< T, bool >::moveElementsForGrow(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::size(), T, and llvm::SmallVectorTemplateBase< T, bool >::takeAllocationForGrow().
Referenced by llvm::SmallVectorImpl< T >::emplace_back().
mallocForGrow()
template<typename T , bool TriviallyCopyable> T * llvm::SmallVectorTemplateBase< T, TriviallyCopyable >::mallocForGrow (size_t MinSize, size_t & NewCapacity) protected
Create a new allocation big enough for MinSize and pass back its size in NewCapacity.
This is the first section of grow().
Definition at line 454 of file SmallVector.h.
Referenced by llvm::SmallVectorTemplateBase< T, bool >::growAndAssign(), and llvm::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack().
moveElementsForGrow()
template<typename T , bool TriviallyCopyable> void llvm::SmallVectorTemplateBase< T, TriviallyCopyable >::moveElementsForGrow (T * NewElts) protected
Move existing elements over to the new allocation NewElts, the middle section of grow().
Definition at line 463 of file SmallVector.h.
Referenced by llvm::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack().
pop_back()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> void llvm::SmallVectorTemplateBase< T, bool >::pop_back () inline
Definition at line 438 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
Referenced by llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), advanceToNextLeafType(), llvm::MipsInstrInfo::analyzeBranch(), llvm::Annotations::Annotations(), llvm::A57ChainingConstraint::apply(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), BuildSubAggregate(), llvm::SmallString< InternalLen >::c_str(), llvm::c_str(), CalcNodeSethiUllmanNumber(), canRewriteGEPAsOffset(), checkIfSupported(), llvm::ArrayRecycler< T, Align >::clear(), ComputePostOrders(), llvm::ConstantFoldTerminator(), llvm::convertUTF8ToUTF16String(), llvm::sys::fs::createUniquePath(), llvm::ScheduleDAGSDNodes::dumpNode(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::TimeTraceProfiler::end(), llvm::codeview::CodeViewRecordIO::endRecord(), llvm::SmallVectorImpl< T >::erase(), llvm::DominatorTreeBase< NodeT, IsPostDom >::eraseNode(), expandFromPrimitiveShadowRecursive(), llvm::cl::ExpansionContext::expandResponseFiles(), llvm::ScalarEvolution::getAddExpr(), llvm::Attributor::getAssumedSimplifiedValues(), llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::XCOFF::getExtendedTBTableFlagString(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), llvm::Intrinsic::getType(), llvm::WebAssemblyMCInstLower::lower(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::object::ExportEntry::moveNext(), llvm::sys::unicode::nearestMatchesForCodepointName(), llvm::nonStrictlyPostDominate(), llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator++(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), llvm::IntervalMapImpl::Path::pop(), llvm::logicalview::LVCompare::pop(), llvm::LiveRangeEdit::pop_back(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::PassInstrumentation::popBeforeNonSkippedPassCallback(), llvm::ConstraintSystem::popLastConstraint(), llvm::MCStreamer::popSection(), llvm::WebAssemblyInstPrinter::printInst(), llvm::GCOVFunction::propagateCounts(), llvm::sampleprof::SampleProfileReaderText::readImpl(), llvm::sys::path::remove_dots(), removeEntryFromStack(), llvm::MemoryDependenceResults::removeInstruction(), removeRedundantBlockingStores(), rewriteAccessChain(), llvm::SelectionDAGISel::SelectCodeCommon(), selectConstantAddr(), setupBranchForGuard(), llvm::VFABI::setVectorVariantNames(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent(), llvm::SmallVectorMemoryBuffer::SmallVectorMemoryBuffer(), sortLocalVars(), swapMIOperands(), llvm::Twine::toNullTerminatedStringRef(), llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers(), and llvm::dwarf_linker::parallel::DependencyTracker::verifyKeepChain().
push_back() [1/2]
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> void llvm::SmallVectorTemplateBase< T, bool >::push_back (const T & Elt) inline
Definition at line 426 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::size(), and T.
Referenced by llvm::AbstractCallSite::AbstractCallSite(), llvm::adaptNoAliasScopes(), llvm::BitCodeAbbrev::Add(), llvm::LiveRangeUpdater::add(), llvm::PMDataManager::add(), llvm::SDDbgInfo::add(), llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::add(), llvm::slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::add(), AddAliasScopeMetadata(), llvm::opt::ArgList::AddAllArgsTranslated(), addAllGlobalValueUsers(), llvm::Instruction::addAnnotationMetadata(), llvm::Record::addAssertion(), llvm::AttributeList::addAttributeAtIndex(), addBasicBlockMetadata(), addBlockAndPredsToSet(), addBoundsChecking(), addCallStack(), AddCombineBUILD_VECTORToVPADDL(), AddCombineTo64bitMLAL(), AddCombineToVPADD(), AddCombineVUZPToVPADDL(), llvm::SchedDFSImpl::addConnection(), addConstantsToTrack(), llvm::SPIRV::DTSortableEntry::addDep(), llvm::MCLOHContainer::addDirective(), llvm::Record::addDump(), llvm::ConstantPool::addEntry(), llvm::CSKYConstantPool::addEntry(), llvm::SMDiagnostic::addFixIt(), llvm::DIInliningInfo::addFrame(), AddGlue(), llvm::mca::Context::addHardwareUnit(), addHints(), llvm::VPWidenPHIRecipe::addIncoming(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::CCState::addInRegsParamInfo(), llvm::LiveIntervals::addKillFlags(), llvm::MachineFunction::addLandingPad(), llvm::GCOVBlock::addLine(), llvm::SpillPlacement::Node::addLink(), llvm::LiveRangeCalc::addLiveInBlock(), llvm::CCState::addLoc(), addLocIfNotPresent(), llvm::AArch64FunctionInfo::addLOHDirective(), llvm::AMDGPURegisterBankInfo::addMappingFromTable(), addMappingsFromTLI(), llvm::logicalview::LVScopeCompileUnit::addMatched(), llvm::objcopy::elf::GroupSection::addMember(), llvm::MachineInstr::addMemOperand(), llvm::PPCFunctionInfo::addMustSaveCR(), addMustTailToCoroResumes(), llvm::DirectedGraph< NodeType, EdgeType >::addNode(), llvm::safestack::StackLayout::addObject(), llvm::GISelObserverWrapper::addObserver(), llvm::lowertypetests::BitSetBuilder::addOffset(), llvm::CallBase::addOperandBundle(), llvm::mcdxbc::Signature::addParam(), llvm::MCSection::addPendingLabel(), llvm::RuntimeCheckingPtrGroup::addPointer(), llvm::PredicatedScalarEvolution::addPredicate(), addPrepareFunction(), addRange(), llvm::RecurrenceDescriptor::AddReductionVar(), llvm::RecordVal::addReferenceLoc(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), addRegLanes(), addReplicateRegions(), llvm::DominatorTreeBase< NodeT, IsPostDom >::addRoot(), AddRuntimeUnrollDisableMetaData(), llvm::RegScavenger::addScavengingFrameIndex(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addSignature(), addStackMapLiveVars(), llvm::FoldingSetNodeID::AddString(), llvm::addStringMetadataToLoop(), llvm::Record::addSuperClass(), llvm::AMDGPUTargetLowering::addTokenForArgument(), llvm::omp::OMPContext::addTrait(), llvm::omp::VariantMatchInfo::addTrait(), llvm::DWARF5AccelTable::addTypeUnitSignature(), llvm::DWARF5AccelTable::addTypeUnitSymbol(), llvm::SSAUpdaterBulk::AddUse(), llvm::consthoist::ConstantCandidate::addUser(), llvm::Record::addValue(), llvm::SSAUpdaterBulk::AddVariable(), llvm::DPValue::addVariableLocationOps(), llvm::DbgVariableIntrinsic::addVariableLocationOps(), llvm::ConstraintSystem::addVariableRow(), adjustByValArgAlignment(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), adjustLoadValueTypeImpl(), advanceToNextLeafType(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), llvm::StatepointLoweringState::allocateStackSlot(), llvm::AllocInfo::AllocInfo(), allUsesOfLoadAndStores(), allUsesOfLoadedValueWillTrapIfNull(), llvm::LoopInfoBase< BlockT, LoopT >::analyze(), llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::MipsInstrInfo::analyzeBranch(), llvm::LanaiInstrInfo::analyzeBranch(), llvm::SystemZCCState::AnalyzeCallOperands(), analyzeCompressibleUses(), llvm::GenericUniformityAnalysisImpl< ContextT >::analyzeControlDivergence(), analyzeExitPHIsForOutputUses(), llvm::SystemZCCState::AnalyzeFormalArguments(), analyzeLoopUnrollCost(), llvm::CCState::analyzeMustTailForwardedRegisters(), annotateFunctionWithHashMismatch(), llvm::annotateValueSite(), llvm::Annotations::Annotations(), llvm::opt::ArgList::append(), llvm::LiveRange::append(), llvm::RegsForValue::append(), llvm::HexagonShuffler::append(), llvm::sys::path::append(), llvm::ModifiedPostOrder< ContextT >::appendBlock(), appendGlobalSymbolTableInfo(), llvm::DebugLoc::appendInlinedAt(), llvm::Record::appendLoc(), llvm::DIExpression::appendOffset(), llvm::DIExpression::appendOpsToArg(), llvm::PPCFunctionInfo::appendParameterType(), llvm::Record::appendReferenceLoc(), llvm::appendReversedLoopsToWorklist(), appendSpeculatableOperands(), appendToGlobalArray(), llvm::DIExpression::appendToStack(), llvm::DWARFTypePrinter::appendUnqualifiedNameAfter(), appendVGScaledOffsetExpr(), llvm::A57ChainingConstraint::apply(), llvm::HexagonSubtarget::UsrOverflowMutation::apply(), llvm::ScalarEvolution::applyLoopGuards(), llvm::AMDGPURegisterBankInfo::applyMappingImage(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingLoad(), llvm::OpenMPIRBuilder::applySimd(), llvm::MemorySSAUpdater::applyUpdates(), llvm::DomTreeUpdater::applyUpdates(), llvm::DomTreeUpdater::applyUpdatesPermissive(), llvm::opt::Arg::Arg(), llvm::CallLowering::ArgInfo::ArgInfo(), ARM64FindSegmentsInFunction(), llvm::LiveRange::assign(), AVRDAGToDAGISel::select< AVRISD::CALL >(), llvm::codeview::ContinuationRecordBuilder::begin(), llvm::codeview::CodeViewRecordIO::beginRecord(), llvm::object::BindRebaseSegInfo::BindRebaseSegInfo(), bitTrackingDCE(), llvm::CriticalAntiDepBreaker::BreakAntiDependencies(), broadcastSrcOp(), llvm::rdf::DataFlowGraph::build(), llvm::SwitchCG::SwitchLowering::buildBitTests(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), llvm::MachineIRBuilder::buildBuildVectorConstant(), buildCallOperands(), buildClonedLoopBlocks(), buildClonedLoops(), buildCopyFromRegs(), buildCopyToRegs(), llvm::coro::buildCoroutineFrame(), llvm::MachineIRBuilder::buildDeleteTrailingVectorElements(), llvm::buildEnqueueKernel(), BuildExactSDIV(), buildFatArchList(), buildFrameDebugInfo(), llvm::coro::Shape::buildFrom(), buildFromShuffleMostly(), llvm::VPlanSlp::buildGraph(), llvm::AMDGPULegalizerInfo::buildMultiply(), buildOverlapMapAndRecordDeclares(), llvm::MachineIRBuilder::buildPadVectorWithUndefElements(), buildPartialUnswitchConditionalBranch(), llvm::opt::OptTable::buildPrefixChars(), llvm::AMDGPURegisterBankInfo::buildReadFirstLane(), llvm::LazyCallGraph::buildRefSCCs(), buildRegSequence16(), buildRegSequence32(), llvm::TargetLowering::BuildSDIV(), llvm::PPCTargetLowering::BuildSDIVPow2(), llvm::TargetLowering::buildSDIVPow2WithCMov(), llvm::CombinerHelper::buildSDivUsingMul(), BuildSubAggregate(), llvm::TargetLowering::BuildUDIV(), llvm::CombinerHelper::buildUDivUsingMul(), llvm::LoopVectorizationPlanner::buildVPlans(), buildVRegToDbgValueMap(), llvm::SmallString< InternalLen >::c_str(), llvm::c_str(), llvm::CacheCost::CacheCost(), CalcNodeSethiUllmanNumber(), calcPredicateUsingBooleans(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), llvm::calculateCXXStateForAsynchEH(), calculateCXXStateNumbers(), llvm::calculateDbgEntityHistory(), llvm::LoopVectorizationCostModel::calculateRegisterUsage(), llvm::calculateSEHStateForAsynchEH(), CalculateTailCallArgDest(), callBufferedPrintfArgPush(), callBufferedPrintfStart(), llvm::DIExpression::canonicalizeExpressionOps(), llvm::FileCheck::CanonicalizeFile(), canonicalizePHIOperands(), canonicalizeShuffleMaskWithHorizOp(), canReturn(), llvm::ScalarEvolution::canReuseInstruction(), canRewriteGEPAsOffset(), castBufferRsrcToV4I32(), CC_AArch64_Custom_Block(), CC_AArch64_Custom_Stack_Block(), CC_ARM_AAPCS_Custom_Aggregate(), CC_LoongArch(), llvm::RISCV::CC_RISCV(), llvm::CC_SystemZ_I128Indirect(), CC_X86_32_MCUInReg(), CC_X86_32_RegCall_Assign2Regs(), chainLoadsAndStoresForMemcpy(), llvm::MachineInstr::changeDebugValuesDefReg(), llvm::AArch64TargetLowering::changeStreamingMode(), llvm::MemorySSAUpdater::changeToUnreachable(), llvm::changeToUnreachable(), checkDependencies(), llvm::Attributor::checkForAllUses(), CheckForLiveRegDef(), CheckForLiveRegDefMasked(), llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches(), TransferTracker::checkInstForNewValues(), checkMixedPrecision(), checkVectorTypesForPromotion(), llvm::checkVOPDRegConstraints(), CleanupConstantGlobalUsers(), cleanupSinglePredPHIs(), clearAssumptionsOfUsers(), llvm::FileCheckPatternContext::clearLocalVars(), TransferTracker::clobberMloc(), clobberRegEntries(), llvm::CloneAndPruneIntoFromInst(), cloneConstantExprWithNewAddressSpace(), llvm::dwarf_linker::parallel::CompileUnit::cloneDieAttrExpression(), llvm::CloneFunctionInto(), cloneLoopBlocks(), cloneLoopNest(), CloneNodeWithValues(), llvm::DILocalScope::cloneScopeForSubprogram(), llvm::WebAssemblyDebugValueManager::cloneSink(), llvm::LexicalScope::closeInsnRange(), clusterSortPtrAccesses(), coerceArguments(), CollectAddOperandsWithScales(), llvm::OpenMPIRBuilder::OutlineInfo::collectBlocks(), collectCastInstrs(), llvm::collectChildrenInLoop(), llvm::collectCmpOps(), collectConcatOps(), collectDbgVariableIntrinsics(), llvm::MachineInstr::collectDebugValues(), llvm::GCNTTIImpl::collectFlatAddressOperands(), collectHomogenousInstGraphLoopInvariants(), llvm::DDGNode::collectInstructions(), collectLeaves(), collectMultiplyFactors(), collectOtherInstr(), collectPHIs(), llvm::InnerLoopVectorizer::collectPoisonGeneratingRecipes(), collectPromotionCandidates(), llvm::PMDataManager::collectRequiredAndUsedAnalyses(), collectSRATypes(), CollectSubexprs(), llvm::PPCTargetLowering::CollectTargetIntrinsicOperands(), collectTransitivePredecessors(), collectUnswitchCandidates(), llvm::collectUsedGlobalVariables(), llvm::mca::RegisterFile::collectWrites(), llvm::colorEHFunclets(), combineAndnp(), CombineBaseUpdate(), combineBinOp_VLToVWBinOp_VL(), combineBVOfConsecutiveLoads(), combineConcatVectorOfCasts(), combineConcatVectorOfScalars(), combineConcatVectorOps(), combineExtractVectorElt(), combineFPFusedMultiply(), combineOrCmpEqZeroToCtlzSrl(), combineRedundantDWordShuffle(), combineSelect(), combineShuffleOfScalars(), combineShuffleOfSplatVal(), combineTargetShuffle(), combineToConsecutiveLoads(), combineX86ShuffleChain(), combineX86ShufflesRecursively(), llvm::FunctionComparator::compare(), compressAnnotation(), llvm::computeAccessFunctions(), llvm::EHStreamer::computeActionsTable(), computeBlocksDominatingExits(), computeCalleeSaveRegisterPairs(), llvm::EHStreamer::computeCallSiteTable(), llvm::computeDeadSymbolsAndUpdateIndirectCalls(), computeExprForSpill(), computeFreeStackSlots(), computeFunctionSummary(), llvm::computeLegalValueVTs(), ComputeLiveInBlocks(), computeLiveOuts(), llvm::computeMinimumValueSizes(), ComputePostOrders(), ComputePTXValueVTs(), llvm::computeSignatureVTs(), llvm::LiveInterval::computeSubRangeUndefs(), computeUnlikelySuccessors(), llvm::SMSchedule::computeUnpipelineableNodes(), llvm::computeValueLLTs(), llvm::ComputeValueVTs(), llvm::concatenateVectors(), ConnectProlog(), llvm::RandomIRBuilder::connectToSink(), llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType(), llvm::ConstantExprKeyType::ConstantExprKeyType(), ConstantFold(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldExtractElementInstruction(), llvm::ConstantFoldInstruction(), constantFoldOperationIntoSelectOperand(), llvm::ConstantFoldVectorBinop(), ConstHasGlobalValuePredicate(), convertImageAddrToPacked(), llvm::TypedInit::convertInitializerBitRange(), llvm::ShuffleVectorInst::convertShuffleMaskForBitcode(), llvm::MIRPrinter::convertStackObjects(), convertToGuardPredicates(), llvm::BasicBlock::convertToNewDbgValues(), convertToParamAS(), llvm::convertUTF8ToUTF16String(), llvm::IntervalTree< PointT, ValueT, DataT >::create(), llvm::coverage::BinaryCoverageReader::create(), llvm::GlobPattern::create(), createAtomicLibcall(), createBSWAPShuffleMask(), llvm::MDBuilder::createCallbackEncoding(), llvm::MDBuilder::createCallees(), llvm::createCFAOffset(), llvm::IRBuilderBase::CreateConstrainedFPCall(), llvm::OpenMPIRBuilder::createCritical(), createDefCFAExpression(), llvm::EpilogueVectorizerEpilogueLoop::createEpilogueVectorizedLoopSkeleton(), llvm::object::ELFFile< ELFT >::createFakeSections(), llvm::DIExpression::createFragmentExpression(), llvm::MDBuilder::createFunctionEntryCount(), llvm::VFABI::createFunctionType(), llvm::IRBuilderBase::CreateIntrinsic(), createMMXBuildVector(), createOutlinedFunction(), llvm::OpenMPIRBuilder::createParallel(), llvm::MDBuilder::createPCSections(), llvm::IRBuilderBase::CreatePreserveArrayAccessIndex(), llvm::createReplicatedMask(), llvm::MDBuilder::createRTTIPointerPrologue(), llvm::IRBuilderBase::CreateStepVector(), createTargetLoopWorkshareCall(), createTblForTrunc(), createTuple(), llvm::createUnaryMask(), llvm::sys::fs::createUniquePath(), createUnreachableSwitchDefault(), llvm::LiveRange::createValueCopy(), llvm::IRBuilderBase::CreateVectorReverse(), CreateVPTBlock(), llvm::mca::ResourceManager::cycleEvent(), llvm::DebuginfodCollection::DebuginfodCollection(), decodeBBAddrMapImpl(), llvm::DecodeBLENDMask(), llvm::DecodeEXTRQIMask(), DecodeFixedType(), DecodeIITType(), llvm::DecodeInsertElementMask(), llvm::DecodeINSERTPSMask(), llvm::DecodeINSERTQIMask(), llvm::DecodeMOVDDUPMask(), llvm::DecodeMOVHLPSMask(), llvm::DecodeMOVLHPSMask(), llvm::DecodeMOVSHDUPMask(), llvm::DecodeMOVSLDUPMask(), DecodePALIGNRMask(), llvm::DecodePALIGNRMask(), llvm::DecodePSHUFBMask(), llvm::DecodePSHUFHWMask(), llvm::DecodePSHUFLWMask(), llvm::DecodePSHUFMask(), llvm::DecodePSLLDQMask(), llvm::DecodePSRLDQMask(), llvm::DecodePSWAPMask(), llvm::DecodeScalarMoveMask(), llvm::DecodeSHUFPMask(), llvm::DecodeSubVectorBroadcast(), llvm::DecodeUNPCKHMask(), llvm::DecodeUNPCKLMask(), llvm::DecodeVALIGNMask(), llvm::DecodeVPERM2X128Mask(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPERMMask(), llvm::DecodeVPERMV3Mask(), llvm::DecodeVPERMVMask(), llvm::DecodeVPPERMMask(), llvm::decodeVSHUF64x2FamilyMask(), llvm::DecodeZeroExtendMask(), llvm::DecodeZeroMoveLowMask(), deduceFunctionAttributeInRPO(), llvm::GISelWorkList< N >::deferred_insert(), llvm::FileCheckPatternContext::defineCmdlineVariables(), llvm::at::deleteAll(), deleteDeadBlocksFromLoop(), deleteDeadClonedBlocks(), llvm::deleteDeadLoop(), llvm::DeleteDeadPHIs(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DependenceInfo::depends(), llvm::TargetInstrInfo::describeLoadedValue(), llvm::X86InstrInfo::describeLoadedValue(), llvm::memprof::IndexedMemProfRecord::deserialize(), llvm::detachDeadBlocks(), llvm::ARMFrameLowering::determineCalleeSaves(), determineGPRegsToClear(), determinePointerAccessAttrs(), determineSVEStackObjectOffsets(), llvm::vfs::RedirectingFileSystem::dir_begin(), llvm::RegPressureTracker::discoverLiveInOrOut(), discoverTypeIndices(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::BlockFrequencyInfoImplBase::distributeMass(), llvm::AsmPrinter::doFinalization(), llvm::NVPTXAsmPrinter::doFinalization(), DoInitialMatch(), DoLowering(), doPromotion(), DPValuesRemoveRedundantDbgInstrsUsingBackwardScan(), DPValuesRemoveRedundantDbgInstrsUsingForwardScan(), DPValuesRemoveUndefDbgAssignsFromEntryBlock(), llvm::Value::dropDroppableUses(), dropIntrinsicWithUnknownMetadataArgument(), llvm::ConstraintSystem::dump(), llvm::AppleAcceleratorTable::dump(), llvm::ScheduleDAGSDNodes::dumpNode(), llvm::SMSchedule::earliestCycleInChain(), llvm::ehAwareSplitEdge(), eliminateConstraints(), eliminateDeadSwitchCases(), eliminateLoadsAcrossLoops(), eliminateSwiftError(), eliminateSwiftErrorArgument(), llvm::embedBitcodeInModule(), llvm::BitstreamWriter::emitBlob(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::AsmPrinter::emitConstantPool(), emitDarwinBCHeaderAndTrailer(), llvm::InstrEmitter::EmitDbgInstrRef(), llvm::EHStreamer::emitExceptionTable(), llvm::AsmPrinter::emitGlobalGOTEquivs(), llvm::MCELFStreamer::emitGNUAttribute(), llvm::BufferByteStreamer::emitInt8(), emitIntrinsicWithCC(), emitIntrinsicWithCCAndChain(), emitLoadScalarOpsFromVGPRLoop(), LiveDebugValues::MLocTracker::emitLoc(), llvm::WebAssemblyTargetWasmStreamer::emitLocal(), llvm::remarks::BitstreamRemarkSerializerHelper::emitMetaBlock(), llvm::remarks::BitstreamRemarkSerializerHelper::emitMetaExternalFile(), llvm::remarks::BitstreamRemarkSerializerHelper::emitMetaRemarkVersion(), llvm::remarks::BitstreamRemarkSerializerHelper::emitMetaStrTab(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), emitNullTerminatedSymbolName(), llvm::OpenMPIRBuilder::emitOffloadingArrays(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::remarks::BitstreamRemarkSerializerHelper::emitRemarkBlock(), llvm::ScheduleDAGSDNodes::EmitSchedule(), emitSignedInt64(), llvm::dxil::DXILBitcodeWriter::emitSignedInt64(), llvm::VETargetLowering::emitSjLjDispatchBlock(), llvm::WebAssemblyAsmPrinter::EmitTargetFeatures(), EmitUnrolledSetTag(), llvm::MCDwarfLineAddr::encode(), llvm::MCDwarfFrameEmitter::encodeAdvanceLoc(), llvm::CodeViewContext::encodeDefRange(), llvm::SelectionDAGISel::EnforceNodeIdInvariant(), llvm::BitstreamCursor::EnterSubBlock(), llvm::LegalizerHelper::equalizeVectorShuffleLengths(), llvm::rdf::DeadCodeElimination::erase(), evaluateInDifferentElementOrder(), llvm::examineCFlagsUse(), llvm::VPWidenRecipe::execute(), llvm::VPWidenCallRecipe::execute(), llvm::VPWidenGEPRecipe::execute(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::GIMatchTableExecutor::executeMatchTable(), ExpandBVWithShuffles(), ExpandCryptoAEK(), expandFromPrimitiveShadowRecursive(), llvm::cl::ExpansionContext::expandResponseFiles(), llvm::TargetLowering::expandUnalignedLoad(), llvm::TargetLowering::expandUnalignedStore(), llvm::SCEVExpander::expandUnionPredicate(), llvm::expandUser(), explicifyGuards(), ExtendToType(), ExtendUsesToFormExtLoad(), llvm::DWARFAbbreviationDeclaration::extract(), extractLoadMMOs(), llvm::extractParts(), extractStoreMMOs(), extractValues(), llvm::extractVectorParts(), llvm::LegalizerHelper::fewerElementsVectorMerge(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorPhi(), llvm::LegalizerHelper::fewerElementsVectorReductions(), llvm::LegalizerHelper::fewerElementsVectorShuffle(), llvm::AMDGPU::fillValidArchListAMDGCN(), llvm::AMDGPU::fillValidArchListR600(), llvm::AArch64::fillValidCPUArchList(), llvm::ARM::fillValidCPUArchList(), llvm::CSKY::fillValidCPUArchList(), llvm::symbolize::MarkupFilter::filter(), FilterHelper(), llvm::DIBuilder::finalize(), llvm::OpenMPIRBuilder::finalize(), llvm::finalizeBundle(), llvm::RuntimeDyldCOFFX86_64::finalizeLoad(), llvm::RuntimeDyldELF::finalizeLoad(), llvm::MCJIT::finalizeObject(), findAffectedValues(), llvm::findAllocaForValue(), llvm::CodeExtractor::findAllocas(), findArgParts(), llvm::findArrayDimensions(), findArrayDimensionsRec(), llvm::FindAvailableLoadedValue(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), llvm::MustBeExecutedContextExplorer::findBackwardJoinPoint(), findBasePointer(), findBestInsertionSet(), FindCallBrs(), findCallsAtConstantOffset(), findDbgIntrinsics(), llvm::findDefsUsedOutsideOfLoop(), findDependencies(), llvm::findDevirtualizableCallsForTypeCheckedLoad(), llvm::findDevirtualizableCallsForTypeTest(), llvm::DGNode< NodeType, EdgeType >::findEdgesTo(), findForkedSCEVs(), llvm::MustBeExecutedContextExplorer::findForwardJoinPoint(), llvm::FindFunctionBackedges(), findIBRPredecessor(), findNextInsertLocation(), findNonImmUse(), llvm::RandomIRBuilder::findOrCreateGlobalVariable(), findOrCreatePHIBlock(), llvm::RandomIRBuilder::findOrCreateSource(), llvm::slpvectorizer::BoUpSLP::findPartiallyOrderedLoads(), findPartitions(), findPotentialBlockers(), llvm::SSAUpdaterTraits< LDVSSAUpdater >::FindPredecessorBlocks(), llvm::DWARFDie::findRecursively(), findRefEdges(), findRematerializableChainToBasePointer(), llvm::ScheduleDAGMI::findRootsAndBiasEdges(), FindSingleUseMultiplyFactors(), findStoresToUninstrumentedArgAllocas(), llvm::MachineInstr::findTiedOperandIdx(), finishCallSiteParams(), firstRealType(), llvm::ARMBlockPlacement::fixBackwardsWLS(), llvm::InnerLoopVectorizer::fixFixedOrderRecurrence(), fixupDebugInfoPostExtraction(), llvm::BinOpInit::Fold(), llvm::InstCombinerImpl::foldBinopWithPhiOperands(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), FoldCondBranchOnValueKnownInPredecessorImpl(), llvm::SelectionDAG::FoldConstantArithmetic(), foldConstantsIntoIntrinsics(), llvm::InstCombinerImpl::foldFreezeIntoRecurrence(), foldGEPOfGEP(), foldICmpOrXorSubChain(), llvm::InstCombinerImpl::foldICmpWithConstant(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::InstCombinerImpl::foldOpIntoPhi(), llvm::InstCombinerImpl::foldPHIArgZextsIntoPHI(), FoldTwoEntryPHINode(), llvm::memtag::forAllReachableExits(), ForeachDagApply(), llvm::InformationCache::foreachUse(), llvm::ScalarEvolution::forgetBlockAndLoopDispositions(), llvm::ScalarEvolution::forgetLcssaPhiWithNewPredecessor(), llvm::ScalarEvolution::forgetValue(), llvm::formDedicatedExitBlocks(), llvm::formLCSSA(), llvm::formLCSSAForInstructions(), forwardStoredOnceStore(), llvm::jitlink::EHFrameCFIBlockInspector::FromEdgeScan(), llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::gather(), llvm::GCNMaxILPSchedStrategy::GCNMaxILPSchedStrategy(), llvm::GCNMaxOccupancySchedStrategy::GCNMaxOccupancySchedStrategy(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), genAlternativeDpCodeSequence(), generateAssignInstrs(), generateCreationChecks(), generateCreationChecksForBinOp(), GenerateFixedLengthSVETBL(), llvm::LoongArchMatInt::generateInstSeq(), generateReproducer(), GenerateTBL(), genFNegatedMAD(), genFusedMultiply(), genIndexedMultiply(), genMaddR(), genNeg(), genShuffleBland(), genSubAdd2SubSub(), llvm::DagInit::get(), llvm::AttributeList::get(), llvm::LegalizerInfo::getAction(), llvm::ScalarEvolution::getAddExpr(), llvm::SITargetLowering::getAddrModeArguments(), llvm::ReplaceableMetadataImpl::getAllArgListUsers(), llvm::RecordKeeper::getAllDerivedDefinitions(), llvm::ReplaceableMetadataImpl::getAllDPValueUsers(), getAllLexicalIndexes(), llvm::SIMachineFunctionInfo::getAllScratchSGPRCopyDstRegs(), llvm::ScalarEvolution::getAnyExtendExpr(), getArrayElements(), llvm::Attribute::getAsString(), llvm::Attributor::getAssumedSimplifiedValues(), getBaseType(), llvm::IRSimilarity::IRSimilarityCandidate::getBasicBlocks(), llvm::HexagonInstrInfo::getBranchingInstrs(), GetBranchWeights(), llvm::AbstractCallSite::getCallbackUses(), llvm::SelectionDAG::getCALLSEQ_END(), llvm::getCapabilitiesEnabledByExtension(), getCastsForInductionPHI(), llvm::SelectionDAG::getConstant(), getConstantVector(), getConstVector(), llvm::IntervalTree< PointT, ValueT, DataT >::getContaining(), llvm::TargetRegisterInfo::getCoveringSubRegIndexes(), getDataDeps(), llvm::GlobalVariable::getDebugInfo(), getDebugLocValue(), llvm::DependenceGraphInfo< NodeType >::getDependencies(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getDescendants(), llvm::orc::JITDylib::getDFSLinkOrder(), llvm::Record::getDirectSuperClasses(), llvm::HexagonMCInstrInfo::getDuplexPossibilties(), getEdgeKind(), llvm::getEHScopeMembership(), GetEHSpillList(), llvm::ConstantExpr::getExactLogBase2(), getExactSDiv(), llvm::LoopBase< BlockT, LoopT >::getExitBlocks(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), llvm::RegionBase< Tr >::getExitingBlocks(), llvm::cl::generic_parser_base::getExtraOptionNames(), getFauxShuffleMask(), llvm::X86::getFeaturesForCPU(), llvm::PPCInstrInfo::getFMAPatterns(), getFMAPatterns(), getFMULPatterns(), getFNEGPatterns(), getFPFusedMultiplyPatterns(), getFPSequenceIfElementsMatch(), llvm::X86AddressMode::getFullAddress(), llvm::TargetLoweringObjectFileXCOFF::getFunctionEntryPointSymbol(), GetFunctions(), llvm::DataLayout::getGEPIndicesForOffset(), getGEPSmallConstantIntOffsetV(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), getGVNForPHINode(), llvm::MachineInstrExpressionTrait::getHashValue(), llvm::NVPTXMachineFunctionInfo::getImageHandleSymbolIndex(), llvm::getIndexExpressionsFromGEP(), llvm::CallBrInst::getIndirectDests(), llvm::DWARFUnit::getInlinedChainForAddress(), llvm::LoopBase< BlockT, LoopT >::getInnerLoopsInPreorder(), getInputSegmentList(), llvm::AArch64RegisterBankInfo::getInstrAlternativeMappings(), llvm::AMDGPURegisterBankInfo::getInstrAlternativeMappings(), llvm::X86RegisterBankInfo::getInstrAlternativeMappings(), llvm::RegisterBankInfo::getInstrPossibleMappings(), getIntOperandFromRegisterString(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), getIntSequenceIfElementsMatch(), getInvariantGroupClobberingInstruction(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), getInvertedVectorForFMA(), llvm::getLibcallSignature(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), llvm::pdb::PDBContext::getLineInfoForAddressRange(), getLoadsAndStores(), llvm::logicalview::LVSymbol::getLocations(), llvm::LoopBase< BlockT, LoopT >::getLoopLatches(), llvm::LoopBase< BlockT, LoopT >::getLoopsInPreorder(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopsInReverseSiblingPreorder(), llvm::TargetInstrInfo::getMachineCombinerPatterns(), llvm::X86InstrInfo::getMachineCombinerPatterns(), getMaddPatterns(), llvm::ProfileSummary::getMD(), getMemcpyLoadsAndStores(), llvm::TargetTransformInfoImplBase::getMemcpyLoopResidualLoweringType(), llvm::GCNTTIImpl::getMemcpyLoopResidualLoweringType(), getMemmoveLoadsAndStores(), llvm::SIInstrInfo::getMemOperandsWithOffsetWidth(), llvm::HexagonInstrInfo::getMemOperandsWithOffsetWidth(), llvm::LanaiInstrInfo::getMemOperandsWithOffsetWidth(), llvm::PPCInstrInfo::getMemOperandsWithOffsetWidth(), llvm::X86InstrInfo::getMemOperandsWithOffsetWidth(), llvm::AArch64InstrInfo::getMemOperandsWithOffsetWidth(), llvm::RISCVInstrInfo::getMemOperandsWithOffsetWidth(), llvm::AArch64TTIImpl::getMemoryOpCost(), getMemsetStores(), llvm::SelectionDAG::getMergeValues(), llvm::SourceMgr::GetMessage(), getMinAnalyzeableBackedgeTakenCount(), getMiscPatterns(), llvm::BasicAAResult::getModRefInfoMask(), llvm::MDNode::getMostGenericRange(), llvm::ScalarEvolution::getMulExpr(), llvm::TargetLowering::getNegatedExpression(), getNegatibleInsts(), getNewSource(), llvm::LiveRange::getNextValue(), llvm::SelectionDAG::getNode(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), llvm::ScalarEvolution::getNotSCEV(), llvm::MachO::ObjCInterfaceRecord::getObjCCategories(), llvm::MachO::ObjCContainerRecord::getObjCIVars(), getOffsetFromIndices(), llvm::AArch64RegisterInfo::getOffsetOpcodes(), llvm::RISCVRegisterInfo::getOffsetOpcodes(), llvm::MipsTargetLowering::getOpndList(), llvm::OpenMPIRBuilder::getOrCreateSrcLocStr(), llvm::DIBuilder::getOrCreateTypeArray(), llvm::WebAssemblyAsmPrinter::getOrCreateWasmSymbol(), getOriginalFunctionType(), getPack(), llvm::logicalview::LVSymbol::getParameters(), llvm::logicalview::LVType::getParameters(), llvm::internal::NfaTranscriber::getPaths(), llvm::LoopNest::getPerfectLoops(), getPHIDeps(), llvm::SCEVAddRecExpr::getPostIncExpr(), getPostIndexedLoadStoreOp(), getPotentialCopiesOfMemoryValue(), llvm::X86MachineFunctionInfo::getPreallocatedIdForCallSite(), llvm::logicalview::LVScope::getRanges(), llvm::RecurrenceDescriptor::getReductionOpChain(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::PPCRegisterInfo::getRegAllocationHints(), llvm::RISCVRegisterInfo::getRegAllocationHints(), llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), getRegistersForValue(), llvm::RegsForValue::getRegsAndSizes(), llvm::TargetInstrInfo::getRegSequenceInputs(), llvm::ARMBaseInstrInfo::getRegSequenceLikeInputs(), llvm::rdf::DataFlowGraph::getRelatedRefs(), getRelevantOperands(), llvm::CCState::getRemainingRegParmsForType(), llvm::GetReturnInfo(), getSalvageOpsForBinOp(), getSalvageOpsForGEP(), getSalvageOpsForIcmpOp(), llvm::BranchProbabilityInfo::SccInfo::getSccEnterBlocks(), llvm::BranchProbabilityInfo::SccInfo::getSccExitBlocks(), getSchedRegions(), llvm::SDDbgValue::getSDNodes(), llvm::GetShadowBytes(), llvm::slpvectorizer::BoUpSLP::LookAheadHeuristics::getShallowScore(), llvm::AArch64TTIImpl::getShuffleCost(), llvm::ScalarEvolution::getSignExtendExprImpl(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), GetSpillList(), llvm::SelectionDAG::getStackArgumentTokenFactor(), llvm::SelectionDAG::getStepVector(), llvm::ConstantDataArray::getString(), llvm::getSymbolicOperandCapabilities(), getTargetConstantBitsFromNode(), getTargetShuffleMask(), getTargetShuffleMaskIndices(), llvm::logicalview::LVScope::getTemplateParameterTypes(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::Intrinsic::getType(), llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost(), llvm::ScalarEvolution::getUMinFromMismatchedTypes(), getUnderlyingObjects(), llvm::getUnderlyingObjects(), llvm::getUnderlyingObjectsForCodeGen(), llvm::getUniqueExitBlocksHelper(), getUnmanagedCSI(), getUnmergePieces(), getUnwindDestToken(), getUnwindDestTokenHelper(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), getVCIXOperands(), llvm::LoopVectorizationCostModel::getVectorCallCost(), getVectorCallCosts(), llvm::VFABI::getVectorVariantNames(), llvm::VPlan::getVPValueOrAddLiveIn(), llvm::ScalarEvolution::getZeroExtendExprImpl(), group2Shuffle(), llvm::IntEqClasses::grow(), llvm::SmallVectorTemplateBase< T, true >::growAndEmplaceBack(), handleBaseClass(), llvm::AMDGPURegisterBankInfo::handleD16VData(), llvm::AMDGPULegalizerInfo::handleD16VData(), handleDanglingVariadicDebugInfo(), handleDataMember(), llvm::SelectionDAGBuilder::handleDebugValue(), HandleInlinedEHPad(), handleListContinuation(), HandleMergeInputChains(), handleMethodOverloadList(), llvm::LiveIntervals::handleMoveIntoNewBundle(), handleMustTailForwardedRegisters(), handleNestedType(), handleNewDebugValue(), handleOneMethod(), handleOverloadedMethod(), handlePhiDef(), handlePointer(), handleSSAValueOperands(), handleStaticDataMember(), handleVFPtr(), handleVirtualBaseClass(), hasAllNBitUsers(), hasCallsInBlocksBetween(), hasHardUserWithinLoop(), hashValueMapping(), llvm::TargetInstrInfo::hasLoadFromStackSlot(), llvm::hasPartialIVCondition(), llvm::SDNode::hasPredecessor(), llvm::SDNode::hasPredecessorHelper(), hasRegisterDependency(), llvm::TargetInstrInfo::hasStoreToStackSlot(), llvm::rdf::DataFlowGraph::hasUntrackedRef(), hoistAndMergeSGPRInits(), hoistFPAssociation(), llvm::SCEVExpander::hoistIVInc(), llvm::hoistRegion(), hostParallelCallback(), llvm::identifyNoAliasScopesToClone(), llvm::DebugHandlerBase::identifyScopeMarkers(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::ImutAVLTreeGenericIterator(), incDecVectorConstant(), llvm::logicalview::LVBinaryReader::includeInlineeLines(), llvm::ValueEnumerator::incorporateFunction(), initBranchWeights(), llvm::IRSimilarity::IRInstructionData::initializeInstruction(), llvm::InitLLVM::InitLLVM(), llvm::InlineFunction(), llvm::GISelWorkList< N >::insert(), insertBitcasts(), insertCandidatesWithPendingInjections(), llvm::MemorySSAUpdater::insertDef(), llvm::insertIfNotContained(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), llvm::LiveIntervals::insertMBBInMaps(), llvm::SlotIndexes::insertMBBInMaps(), insertParsePoints(), llvm::InsertPreheaderForLoop(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), llvm::codeview::GlobalTypeTableBuilder::insertRecordAs(), llvm::SIInstrInfo::insertSelect(), insertSpills(), insertUseHolderAfter(), insertVector(), llvm::xray::Profile::internPath(), llvm::intersectAccessGroups(), llvm::MachineTraceMetrics::Ensemble::invalidate(), llvm::OuterAnalysisManagerProxy< AnalysisManagerT, IRUnitT, ExtraArgTs >::Result::invalidate(), llvm::PhiValues::invalidateValue(), isAllocSiteRemovable(), llvm::LazyCallGraph::RefSCC::isAncestorOf(), llvm::LazyCallGraph::SCC::isAncestorOf(), isBlockValidForExtraction(), llvm::RecurrenceDescriptor::isFixedOrderRecurrence(), isFusableLoadOpStorePattern(), isHorizontalBinOp(), llvm::AANonNull::isImpliedByIR(), isKnownNonNullFromDominatingCondition(), isLoadOrMultipleLoads(), isLoopDead(), isNonEscapingGlobalNoAliasWithLoad(), isObjectSizeLessThanOrEq(), isOnlyCopiedFromConstantMemory(), llvm::isOverflowIntrinsicNoWrap(), isPointerValueDeadOnEntryToFunction(), isPotentiallyReachable(), llvm::isPotentiallyReachable(), isPTruePromoted(), isReachableAmongDominated(), llvm::isSafeToDestroyConstant(), isSafeToMove(), isSignExtendedW(), IsStoredObjCPointer(), isSuccOrder(), isValidBaseUpdate(), llvm::object::WasmSectionOrderChecker::isValidSectionOrder(), isVariantApplicableInContextHelper(), llvm::SystemZVectorConstantInfo::isVectorConstantLegal(), isVectorPromotionViable(), isWideTypeMask(), llvm::SpillPlacement::iterate(), llvm::LiveRange::join(), llvm::SMSchedule::latestCycleInChain(), llvm::LazyCallGraph::LazyCallGraph(), llvm::AMDGPULegalizerInfo::legalizeBufferLoad(), llvm::AMDGPULegalizerInfo::legalizeBVHIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeImageIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeInsertVectorElt(), llvm::Legalizer::legalizeMachineFunction(), llvm::AMDGPULegalizerInfo::legalizeMul(), llvm::SITargetLowering::legalizeTargetIndependentNode(), LinearizeExprTree(), LLVMBuildCallWithOperandBundles(), LLVMBuildInvokeWithOperandBundles(), LLVMMDNodeInContext(), LLVMOrcExecutionSessionLookup(), TransferTracker::loadInlocs(), TransferTracker::loadVarInloc(), llvm::object::ELFFile< ELFT >::loadVersionMap(), LookupNearestOption(), llvm::WebAssemblyMCInstLower::lower(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), LowerBITREVERSE(), LowerBITREVERSE_XOP(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), LowerBUILD_VECTORvXbf16(), LowerBUILD_VECTORvXi1(), lowerBuildVectorToBitOp(), llvm::SITargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SPIRVCallLowering::lowerCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::LoongArchTargetLowering::LowerCall(), llvm::RISCVTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), lowerCallResult(), llvm::SITargetLowering::LowerCallResult(), llvm::HexagonTargetLowering::LowerCallResult(), LowerCallResult(), llvm::TargetLowering::LowerCallTo(), llvm::HexagonTargetLowering::LowerCONCAT_VECTORS(), lowerConstantIntrinsics(), llvm::HexagonTargetLowering::LowerConstantPool(), LowerCTPOP(), llvm::LowerDbgDeclare(), lowerDSPIntr(), llvm::LegalizerHelper::lowerExtract(), llvm::AArch64CallLowering::lowerFormalArguments(), llvm::SPIRVCallLowering::lowerFormalArguments(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::LoongArchTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::RISCVTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::VETargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::lowerGlobalIFuncUsersAsGlobalCtor(), lowerGuardIntrinsic(), lowerIncomingStatepointValue(), llvm::LegalizerHelper::lowerInsert(), llvm::ARMTargetLowering::lowerInterleavedLoad(), llvm::AArch64TargetLowering::lowerInterleavedStore(), llvm::ARMTargetLowering::lowerInterleavedStore(), llvm::RISCVTargetLowering::lowerInterleavedStore(), llvm::X86TargetLowering::lowerInterleavedStore(), lowerLocalAllocas(), LowerMemOpCallTo(), LowerMUL(), lowerNonLocalAlloca(), llvm::lowerObjectSizeCall(), LowerPredicateStore(), llvm::SelectionDAGBuilder::lowerRangeToAssertZExt(), llvm::SITargetLowering::LowerReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::LoongArchTargetLowering::LowerReturn(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::RISCVTargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::VETargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerShift(), lowerShuffleAsBlend(), lowerShufflePairAsUNPCKAndPermute(), llvm::LegalizerHelper::lowerShuffleVector(), lowerStatepointMetaArgs(), LowerUINT_TO_FP_i64(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), lowerV8I16GeneralSingleInputShuffle(), llvm::HexagonTargetLowering::LowerVASTART(), llvm::HexagonTargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_VSHF(), LowerVECTOR_SHUFFLEUsingMovs(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorArith(), LowerVectorCTLZInRegLUT(), LowerVectorCTPOPInRegLUT(), LowervXi8MulWithUNPCK(), lowerWidenableCondition(), makeDstOps(), llvm::makeFollowupLoopID(), llvm::opt::InputArgList::MakeIndex(), llvm::makePostTransformationMetadata(), makeStatepointExplicit(), makeStatepointExplicitImpl(), markAliveBlocks(), llvm::dwarf_linker::parallel::DependencyTracker::markCollectedLiveRootsAsKept(), llvm::GVNPass::markInstructionForDeletion(), markTails(), llvm::Regex::match(), llvm::CombinerHelper::matchCombineConcatVectors(), llvm::CombinerHelper::matchCombineShuffleVector(), llvm::CombinerHelper::matchHoistLogicOpWithSameOpcodeHands(), matchIndexAsShuffle(), matchIntrinsicType(), llvm::CombinerHelper::matchNotCmp(), matchPERM(), matchScalarReduction(), MatchVectorAllEqualTest(), llvm::MCLEBFragment::MCLEBFragment(), llvm::MCStreamer::MCStreamer(), llvm::rdf::CodeNode::members_if(), memoryIsNotModifiedBetween(), llvm::memprof::MemProfRecord::MemProfRecord(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), MergeCompatibleInvokesImpl(), mergeConstants(), llvm::Instruction::mergeDIAssignID(), mergeReplicateRegionsIntoSuccessors(), llvm::LegalizerHelper::moreElementsVector(), llvm::LegalizerHelper::moreElementsVectorShuffle(), llvm::SelectionDAG::MorphNodeTo(), moveBelowOrigChain(), moveLCSSAPhis(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::mustExecuteUBIfPoisonOnPathTo(), llvm::InjectorIRStrategy::mutate(), llvm::InsertFunctionStrategy::mutate(), llvm::InsertCFGStrategy::mutate(), llvm::InsertPHIStrategy::mutate(), llvm::SinkInstructionStrategy::mutate(), llvm::ShuffleBlockStrategy::mutate(), llvm::InstDeleterIRStrategy::mutate(), llvm::SelectionDAG::mutateStrictFPToFP(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarAddSub(), llvm::LegalizerHelper::narrowScalarBasic(), llvm::LegalizerHelper::narrowScalarExtract(), llvm::LegalizerHelper::narrowScalarInsert(), llvm::LegalizerHelper::narrowScalarSelect(), llvm::narrowShuffleMaskElts(), llvm::EscapeEnumerator::Next(), llvm::nonStrictlyPostDominate(), llvm::Triple::normalize(), NormalizeBuildVector(), nullifySetjmp(), operandWithNewAddressSpaceOrCreatePoison(), llvm::orc::BlockFreqQuery::operator()(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++(), llvm::SmallString< InternalLen >::operator+=(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), OptimizeAwayTrappingUsesOfValue(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::X86InstrInfo::optimizeLoadInstr(), optimizeLoopExitWithUnknownExitCount(), optimizeSection(), llvm::MemorySSA::OptimizeUses::optimizeUses(), llvm::vfs::OverlayFileSystem::OverlayFileSystem(), packCmovGroup(), packImage16bitOpsToDwords(), padEltsToUndef(), llvm::jitlink::COFFDirectiveParser::parse(), llvm::RISCVISAInfo::parseArchString(), parseBackslash(), llvm::SPIRV::parseBuiltinTypeNameToTargetExtType(), llvm::cl::ParseCommandLineOptions(), parseCondition(), llvm::formatv_object_base::parseFormatString(), ParseFunctionArgs(), llvm::ELFAttributeParser::parseIndexList(), parseOperands(), llvm::MIRParserImpl::parseRegisterInfo(), parseScalarValue(), parseSegmentLoadCommand(), llvm::parseWidenableGuard(), partitionShuffleOfConcats(), llvm::SITargetLowering::passSpecialInputs(), llvm::peelLoop(), PerformADDVecReduce(), performBranchToCommonDestFolding(), performBUILD_VECTORCombine(), PerformBUILD_VECTORCombine(), performBuildShuffleExtendCombine(), performCONCAT_VECTORSCombine(), performConcatVectorsCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), performExtBinopLoadFold(), llvm::ARMTargetLowering::PerformIntrinsicCombine(), PerformLOADCombine(), performLOADCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::ARMTargetLowering::PerformMVETruncCombine(), PerformMVEVLDCombine(), performNEONPostLDSTCombine(), llvm::performOptimizedStructLayout(), performPostLD1Combine(), PerformReduceShuffleCombine(), performSignExtendInRegCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingMVETruncToNarrowingStores(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), PerformTruncatingStoreCombine(), performVecReduceAddCombine(), PerformVECTOR_SHUFFLECombine(), PerformVQDMULHCombine(), PerformXORCombine(), placeSources(), llvm::PointerMayBeCaptured(), populateDependencyMatrix(), llvm::SITargetLowering::PostISelFolding(), llvm::MipsCCState::PreAnalyzeCallOperand(), llvm::PPCCCState::PreAnalyzeCallOperands(), llvm::MipsCCState::PreAnalyzeCallResult(), llvm::MipsCCState::PreAnalyzeFormalArgument(), llvm::PPCCCState::PreAnalyzeFormalArguments(), llvm::MipsCCState::PreAnalyzeReturnValue(), PrefixMatcher::PrefixMatcher(), llvm::SystemZInstrInfo::prepareCompareSwapOperands(), llvm::InstCombinerImpl::prepareWorklist(), llvm::DIExpression::prepend(), llvm::TargetRegisterInfo::prependOffsetExpression(), llvm::DIExpression::prependOpcodes(), llvm::AsmPrinter::preprocessXXStructorList(), llvm::CallGraph::print(), llvm::PhysicalRegisterUsageInfo::print(), llvm::WebAssemblyInstPrinter::printInst(), printNoMatch(), llvm::Pattern::printVariableDefs(), llvm::AlignmentFromAssumptionsPass::processAssumption(), llvm::JumpThreadingPass::processBranchOnXOR(), processCallSite(), processConstantStringArg(), ProcessElementList(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::logicalview::LVBinaryReader::processLines(), processPhiNode(), processPSInputArgs(), processSwitches(), llvm::JumpThreadingPass::processThreadableEdges(), promoteAllocaUserToVector(), promoteArguments(), llvm::promoteCall(), llvm::promoteLoopAccessesToScalars(), promoteSingleBlockAlloca(), llvm::GCOVFunction::propagateCounts(), llvm::SwiftErrorValueTracking::propagateVRegs(), llvm::LiveIntervals::pruneValue(), llvm::InstructionWorklist::push(), llvm::logicalview::LVCompare::push(), llvm::IntervalMapImpl::Path::push(), llvm::AAPointerInfo::RangeList::push_back(), PushDefUseChildren(), PushLoopPHIs(), llvm::vfs::OverlayFileSystem::pushOverlay(), pushRegsToStack(), llvm::MCStreamer::pushSection(), pushStackMapConstant(), llvm::AAPointerInfo::RangeList::RangeList(), llvm::coverage::RawCoverageMappingReader::read(), llvm::sampleprof::SampleProfileReaderText::readImpl(), llvm::SIInstrInfo::readlaneVGPRToSGPR(), llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile(), llvm::BitstreamCursor::readRecord(), llvm::BinaryStreamReader::readSLEB128(), llvm::MachineInstr::readsWritesVirtualRegister(), llvm::BinaryStreamReader::readULEB128(), llvm::object::MachOObjectFile::ReadULEB128s(), llvm::TargetInstrInfo::reassociateOps(), rebuildConstant(), rebuildLoopAfterUnswitch(), llvm::WebAssemblyExceptionInfo::recalculate(), llvm::recognizeBSwapOrBitReverseIdiom(), llvm::LiveVariables::recomputeForSingleDefVirtReg(), recomputeLoopBlockSet(), llvm::AArch64TargetLowering::ReconstructShuffle(), ReconstructShuffleWithRuntimeMask(), recordCondition(), llvm::MachineDominatorTree::recordSplitCriticalEdge(), TransferTracker::recoverAsEntryValue(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), TransferTracker::redefVar(), reduceDbgValsBackwardScan(), reduceDbgValsForwardScan(), ReduceSwitchRange(), llvm::RuntimeDyldCOFFX86_64::registerEHFrames(), llvm::RegsForValue::RegsForValue(), relocationViaAlloca(), llvm::SIInstrInfo::reMaterialize(), rematerializeLiveValues(), rematerializeLiveValuesAtUses(), llvm::sys::path::remove_dots(), removeConstantFactors(), llvm::LazyCallGraph::removeDeadFunction(), llvm::SelectionDAG::RemoveDeadNodes(), removeFromUsedList(), removeGEPBuiltinsInFunc(), removeGlobalCtors(), llvm::MemoryDependenceResults::removeInstruction(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::SCCPSolver::removeNonFeasibleEdges(), removePAICalls(), removeRedundantBlockingStores(), removeRedundantDbgInstrsUsingBackwardScan(), removeRedundantDbgInstrsUsingForwardScan(), removeRedundantDbgLocsUsingBackwardScan(), removeRedundantDbgLocsUsingForwardScan(), removeUndefDbgAssignsFromEntryBlock(), removeUndefDbgLocsFromEntryBlock(), llvm::opt::Arg::render(), llvm::LiveRange::RenumberValues(), llvm::slpvectorizer::BoUpSLP::VLOperands::reorder(), llvm::slpvectorizer::BoUpSLP::reorderBottomToTop(), llvm::slpvectorizer::BoUpSLP::reorderTopToBottom(), llvm::SuffixTree::RepeatedSubstringIterator::RepeatedSubstringIterator(), llvm::sys::path::replace_extension(), ReplaceAddWithADDP(), llvm::DIExpression::replaceArg(), llvm::CallGraphNode::replaceCallEdge(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::coro::replaceCoroFree(), replaceDebugSections(), replaceDominatedUses(), replaceExtractElements(), replaceInChain(), llvm::DebugLoc::replaceInlinedAtSubprogram(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), replaceLoopPHINodesWithPreheaderValues(), llvm::LegalizationArtifactCombiner::replaceRegOrBuildCopy(), replaceUndefValuesInPhi(), llvm::Value::replaceUsesWithIf(), llvm::DbgVariableIntrinsic::replaceVariableLocationOp(), llvm::DPValue::replaceVariableLocationOp(), replaceWithCallToVeclib(), replaceWithGEP(), llvm::MCStreamer::reset(), llvm::UnwindOpcodeAssembler::Reset(), llvm::logicalview::LVScopeArray::resolveExtra(), resolveRecordTypes(), llvm::CondOpInit::resolveReferences(), llvm::VarDefInit::resolveReferences(), llvm::DagInit::resolveReferences(), resolveSources(), resolveTargetShuffleInputsAndMask(), restorePreTransformState(), rewrite(), rewriteAccessChain(), llvm::SSAUpdaterBulk::RewriteAllUses(), llvm::rewriteLoopExitValues(), rewriteMaterializableInstructions(), rewriteNonInstructionUses(), rewritePHIs(), llvm::PeelingModuloScheduleExpander::rewriteUsesOf(), llvm::FunctionSpecializer::run(), llvm::GenericCycleInfoCompute< ContextT >::run(), llvm::LoadAndStorePromoter::run(), llvm::TruncInstCombine::run(), llvm::MemDerefPrinterPass::run(), llvm::StackLifetimePrinterPass::run(), llvm::KCFIPass::run(), llvm::CGSCCToFunctionPassAdaptor::run(), llvm::CoroSplitPass::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::LowerEmuTLSPass::run(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), llvm::PlaceSafepointsPass::runImpl(), runImpl(), runIPSCCP(), runMoveAutoInit(), llvm::RewriteStatepointsForGC::runOnFunction(), llvm::SlotIndexes::runOnMachineFunction(), llvm::IRTranslator::runOnMachineFunction(), llvm::Legalizer::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), runSCCP(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runSemiNCA(), llvm::RuntimeCheckingPtrGroup::RuntimeCheckingPtrGroup(), llvm::MachineFunction::salvageCopySSAImpl(), llvm::salvageDebugInfo(), llvm::SelectionDAG::salvageDebugInfo(), SalvageDVI(), llvm::sampleprof::SampleSorter< LocationT, SampleT >::SampleSorter(), scalarizeExtEltFP(), llvm::TargetLowering::scalarizeVectorLoad(), llvm::TargetLowering::scalarizeVectorStore(), scalarizeVectorStore(), llvm::SpillPlacement::scanActiveBundles(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::FastISel::selectPatchpoint(), llvm::FastISel::selectStackmap(), selectWMMAModsNegAbs(), llvm::FastISel::selectXRayCustomEvent(), llvm::FastISel::selectXRayTypedEvent(), separateNestedLoop(), llvm::MCELFStreamer::setAttributeItem(), llvm::MCELFStreamer::setAttributeItems(), llvm::IRSimilarity::IRInstructionData::setBranchSuccessors(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), llvm::SUnit::setDepthDirty(), llvm::SwiftErrorValueTracking::setFunction(), llvm::codegen::setFunctionAttributes(), setGroupSize(), llvm::SUnit::setHeightDirty(), llvm::PMTopLevelManager::setLastUser(), llvm::StructType::setName(), llvm::IRSimilarity::IRInstructionData::setPHIPredecessors(), llvm::setProfMetadata(), setRegZero(), setRequiredFeatureString(), llvm::IntervalMapImpl::Path::setRoot(), llvm::AAPointerInfo::RangeList::setUnknown(), setupBranchForGuard(), setUsedInitializer(), llvm::LoopVectorizationCostModel::setVectorizedCallDecision(), shiftAmountKnownInRange(), llvm::AAMDNodes::shiftTBAAStruct(), shouldCombineToPostInc(), llvm::AArch64TargetLowering::shouldSinkOperands(), llvm::AMDGPUTargetLowering::shouldSinkOperands(), llvm::ARMTargetLowering::shouldSinkOperands(), llvm::RISCVTargetLowering::shouldSinkOperands(), llvm::X86TargetLowering::shouldSinkOperands(), shouldSinkVectorOfPtrs(), shouldSinkVScale(), shouldSplitOnPredicatedArgument(), shouldTransformMulToShiftsAddsSubs(), llvm::LiveIntervals::shrinkToUses(), simplifyAMDGCNMemoryIntrinsicDemanded(), simplifyCommonValuePhi(), SimplifyCondBranchToCondBranch(), llvm::TargetLowering::SimplifyDemandedVectorElts(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetNode(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), simplifyInstructionWithPHI(), llvm::simplifyLoop(), simplifyLoopInst(), simplifyOneLoop(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), simplifySelectInst(), simplifySwitchOfPowersOfTwo(), simplifyWithOpReplaced(), simplifyX86extrq(), simplifyX86insertq(), simplifyX86pack(), simplifyX86varShift(), llvm::WebAssemblyDebugValueManager::sink(), SinkCommonCodeFromPredecessors(), sinkLastInstruction(), sinkLifetimeStartMarkers(), sinkLoopInvariantInstructions(), sinkMinMaxInBB(), sinkRecurrenceUsersAfterPrevious(), llvm::InnerLoopVectorizer::sinkScalarOperands(), sinkSpillUsesAfterCoroBegin(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), SlotMaskToText(), llvm::SmallVectorMemoryBuffer::SmallVectorMemoryBuffer(), SoleWriteToDeadLocal(), llvm::dwarf_linker::parallel::ArrayList< T, ItemsGroupSize >::sort(), sortLocalVars(), llvm::AbstractDependenceGraphBuilder< GraphType >::sortNodesTopologically(), llvm::AMDGPURegisterBankInfo::split64BitValueForMapping(), splitAsyncCoroutine(), llvm::BasicBlock::splitBasicBlockBefore(), splitBlock(), llvm::splitBlockBefore(), SplitBlockImpl(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::DINode::splitFlags(), splitGlobal(), llvm::SplitKnownCriticalEdge(), SplitLandingPadPredecessorsImpl(), SplitOpsAndApply(), llvm::VETargetLowering::splitPackedLoadStore(), splitRetconCoroutine(), llvm::LiveIntervals::splitSeparateComponents(), splitSwitchCoroutine(), llvm::VETargetLowering::splitVectorOp(), SRAGlobal(), llvm::stableHashValue(), stashEntryDbgValues(), StoreTailCallArgumentsToStackSlot(), stripDeadDebugInfoImpl(), stripGCRelocates(), llvm::stripNonLineTableDebugInfo(), stripNonValidDataFromBody(), stripValuesNotDefiningMask(), swapAntiDependences(), swapMIOperands(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), SwitchToLookupTable(), llvm::BTFParser::symbolize(), llvm::TailDuplicator::tailDuplicateAndUpdate(), llvm::JumpThreadingPass::threadThroughTwoBasicBlocks(), llvm::OpenMPIRBuilder::tileLoops(), llvm::cl::TokenizeGNUCommandLine(), llvm::cl::TokenizeWindowsCommandLine(), llvm::cl::TokenizeWindowsCommandLineFull(), tokenizeWindowsCommandLineImpl(), llvm::cl::TokenizeWindowsCommandLineNoCopy(), llvm::object::ELFFile< ELFT >::toMappedAddr(), llvm::Twine::toNullTerminatedStringRef(), llvm::detail::IEEEFloat::toString(), llvm::objcopy::macho::MachOWriter::totalSize(), llvm::jitlink::LinkGraph::transferBlock(), llvm::SelectionDAG::transferDbgValues(), TransferTracker::transferMlocs(), llvm::LoopTraversal::traverse(), tryBuildVectorShuffle(), llvm::LegalizationArtifactCombiner::tryCombineAnyExt(), TryCombineBaseUpdate(), llvm::LegalizationArtifactCombiner::tryCombineExtract(), tryCombineFromSVBoolBinOp(), llvm::LegalizationArtifactCombiner::tryCombineInstruction(), llvm::LegalizationArtifactCombiner::ArtifactValueFinder::tryCombineMergeLike(), llvm::LegalizationArtifactCombiner::tryCombineSExt(), llvm::LegalizationArtifactCombiner::tryCombineTrunc(), llvm::LegalizationArtifactCombiner::tryCombineUnmergeValues(), llvm::LegalizationArtifactCombiner::tryCombineZExt(), tryConstantFoldCall(), llvm::VFABI::tryDemangleForVFABI(), llvm::LegalizationArtifactCombiner::tryFoldImplicitDef(), llvm::tryFoldSPUpdateIntoPushPop(), llvm::LegalizationArtifactCombiner::tryFoldUnmergeCast(), llvm::MCDwarfLineTableHeader::tryGetFile(), tryInterleave(), tryToElideArgumentCopy(), tryToFoldExtendOfConstant(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), llvm::InstCombinerImpl::tryToSinkInstruction(), llvm::WebAssemblyAsmTypeCheck::typeCheck(), llvm::IntEqClasses::uncompress(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::OpenMPIRBuilder::unrollLoopPartial(), llvm::UnrollRuntimeLoopRemainder(), llvm::SelectionDAG::UnrollVectorOp(), llvm::SelectionDAG::UnrollVectorOverflowOp(), unrollVectorShift(), unswitchNontrivialInvariants(), unswitchTrivialBranch(), unswitchTrivialSwitch(), llvm::UnwindOpcodeAssembler::UnwindOpcodeAssembler(), UpdateAnalysisInformation(), updateCGAndAnalysisManagerForPass(), llvm::AArch64RegisterInfo::UpdateCustomCalleeSavedRegs(), llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers(), updateDVIWithLocations(), updateLiveness(), updateLoopMetadataDebugLocationsImpl(), updatePhysDepsDownwards(), updatePhysDepsUpwards(), llvm::CallInst::updateProfWeight(), llvm::JumpThreadingPass::updateSSA(), llvm::DwarfCompileUnit::updateSubprogramScopeDIE(), llvm::upgradeInstructionLoopAttachment(), llvm::UpgradeIntrinsicCall(), upgradeIntrinsicFunction1(), upgradeLoopArgument(), ValidateMVEStore(), llvm::HexagonShuffler::ValidResourceUsage(), llvm::valTypesFromMVTs(), valueIsOnlyUsedLocallyOrStoredToOneGlobal(), llvm::InnerLoopVectorizer::vectorizeInterleaveGroup(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), vectorToScalarBitmask(), llvm::GenericConvergenceVerifier< ContextT >::verify(), llvm::SIInstrInfo::verifyInstruction(), llvm::dwarf_linker::parallel::DependencyTracker::verifyKeepChain(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::memtag::StackInfoBuilder::visit(), llvm::SCEVDivision::visitAddExpr(), llvm::InstCombinerImpl::visitCallInst(), llvm::SelectionDAGBuilder::visitDbgInfo(), visitDomSubTree(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitExtractValueInst(), llvm::InstCombinerImpl::visitGEPOfGEP(), VisitGlobalVariableForEmission(), llvm::InstCombinerImpl::visitLandingPadInst(), llvm::SCEVDivision::visitMulExpr(), visitPointers(), llvm::LazyCallGraph::visitReferences(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::widenShuffleMaskElts(), widenVectorOpsToi8(), llvm::objcopy::elf::BinaryWriter::write(), llvm::write(), llvm::mcdxbc::Signature::write(), writeStringRecord(), llvm::dxil::DXILBitcodeWriter::writeStringRecord(), llvm::InstrProfWriter::writeText(), writeTypeIdCompatibleVtableSummaryRecord(), writeTypeIdSummaryRecord(), writeWholeProgramDevirtResolution(), writeWholeProgramDevirtResolutionByArg(), and llvm::LLVMContextImpl::~LLVMContextImpl().
push_back() [2/2]
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> void llvm::SmallVectorTemplateBase< T, bool >::push_back (T && Elt) inline
Definition at line 432 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::size(), and T.
reserveForParamAndGetAddress() [1/2]
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> const T * llvm::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress (const T & Elt, size_t N = 1) inline protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 390 of file SmallVector.h.
References N, and llvm::SmallVectorTemplateCommon< T, typename >::reserveForParamAndGetAddressImpl().
Referenced by llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorImpl< T >::insert(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorTemplateBase< T, true >::push_back().
reserveForParamAndGetAddress() [2/2]
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> T * llvm::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress (T & Elt, size_t N = 1) inline protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 396 of file SmallVector.h.
References N, and llvm::SmallVectorTemplateCommon< T, typename >::reserveForParamAndGetAddressImpl().
takeAllocationForGrow()
template<typename T , bool TriviallyCopyable> void llvm::SmallVectorTemplateBase< T, TriviallyCopyable >::takeAllocationForGrow (T * NewElts, size_t NewCapacity) protected
Transfer ownership of the allocation, finishing up grow().
Definition at line 474 of file SmallVector.h.
Referenced by llvm::SmallVectorTemplateBase< T, bool >::growAndAssign(), and llvm::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack().
uninitialized_copy()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> template<typename It1 , typename It2 > static void llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy (It1 I, It1 E, It2 Dest) inline static protected
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements as needed.
Definition at line 368 of file SmallVector.h.
References E, and I.
Referenced by llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorImpl< T >::insert(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< T >::swap(), and llvm::SmallVectorTemplateBase< T, true >::uninitialized_move().
uninitialized_move()
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> template<typename It1 , typename It2 > static void llvm::SmallVectorTemplateBase< T, bool >::uninitialized_move (It1 I, It1 E, It2 Dest) inline static protected
Move the range [I, E) into the uninitialized memory starting with "Dest", constructing elements as needed.
Definition at line 361 of file SmallVector.h.
References E, and I.
Referenced by llvm::SmallVectorImpl< T >::insert(), and llvm::SmallVectorImpl< T >::operator=().
Friends And Related Function Documentation
SmallVectorTemplateCommon< T >
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> friend class SmallVectorTemplateCommon< T > friend
Definition at line 325 of file SmallVector.h.
Member Data Documentation
TakesParamByValue
template<typename T , bool = (std::is_trivially_copy_constructible<T>::value) && (std::is_trivially_move_constructible<T>::value) && std::is_trivially_destructible<T>::value> constexpr bool llvm::SmallVectorTemplateBase< T, bool >::TakesParamByValue = false static constexpr protected
Definition at line 346 of file SmallVector.h.
Referenced by llvm::SmallVectorImpl< T >::insert().
The documentation for this class was generated from the following file:
include/llvm/ADT/SmallVector.h