LLVM: llvm::pdb::GSIStreamBuilder Class Reference
llvm::pdb::GSIStreamBuilder Class Reference
#include "llvm/DebugInfo/PDB/Native/GSIStreamBuilder.h"
Public Member Functions
GSIStreamBuilder (msf::MSFBuilder &Msf)
~GSIStreamBuilder ()
GSIStreamBuilder (const GSIStreamBuilder &)=delete
GSIStreamBuilder & operator= (const GSIStreamBuilder &)=delete
Error finalizeMsfLayout ()
Error commit (const msf::MSFLayout &Layout, WritableBinaryStreamRef Buffer)
uint32_t getPublicsStreamIndex () const
uint32_t getGlobalsStreamIndex () const
uint32_t getRecordStreamIndex () const
void addPublicSymbols (std::vector< BulkPublic > &&PublicsIn)
void addGlobalSymbol (const codeview::ProcRefSym &Sym)
void addGlobalSymbol (const codeview::DataSym &Sym)
void addGlobalSymbol (const codeview::ConstantSym &Sym)
void addGlobalSymbol (const codeview::CVSymbol &Sym)
Detailed Description
Definition at line 46 of file GSIStreamBuilder.h.
Constructor & Destructor Documentation
GSIStreamBuilder() [1/2]
GSIStreamBuilder::GSIStreamBuilder (msf::MSFBuilder & Msf) explicit
Definition at line 287 of file GSIStreamBuilder.cpp.
~GSIStreamBuilder()
GSIStreamBuilder::~GSIStreamBuilder () default
GSIStreamBuilder() [2/2]
llvm::pdb::GSIStreamBuilder::GSIStreamBuilder (const GSIStreamBuilder &) delete
Member Function Documentation
addGlobalSymbol() [1/4]
void GSIStreamBuilder::addGlobalSymbol (const codeview::ConstantSym & Sym)
Definition at line 360 of file GSIStreamBuilder.cpp.
References Sym.
addGlobalSymbol() [2/4]
void GSIStreamBuilder::addGlobalSymbol (const codeview::CVSymbol & Sym)
Definition at line 371 of file GSIStreamBuilder.cpp.
addGlobalSymbol() [3/4]
void GSIStreamBuilder::addGlobalSymbol (const codeview::DataSym & Sym)
Definition at line 356 of file GSIStreamBuilder.cpp.
References Sym.
addGlobalSymbol() [4/4]
void GSIStreamBuilder::addGlobalSymbol (const codeview::ProcRefSym & Sym)
Definition at line 352 of file GSIStreamBuilder.cpp.
References Sym.
addPublicSymbols()
void GSIStreamBuilder::addPublicSymbols (std::vector< BulkPublic > && PublicsIn)
Definition at line 331 of file GSIStreamBuilder.cpp.
References assert(), llvm::parallelSort(), and sizeOfPublic().
commit()
Error GSIStreamBuilder::commit (const msf::MSFLayout & Layout, WritableBinaryStreamRef Buffer)
Definition at line 480 of file GSIStreamBuilder.cpp.
References llvm::msf::WritableMappedBlockStream::createIndexedStream(), llvm::codeview::EC, llvm::msf::MSFBuilder::getAllocator(), getGlobalsStreamIndex(), getPublicsStreamIndex(), getRecordStreamIndex(), and llvm::Error::success().
finalizeMsfLayout()
Error GSIStreamBuilder::finalizeMsfLayout ()
Definition at line 307 of file GSIStreamBuilder.cpp.
References llvm::msf::MSFBuilder::addStream(), Idx, and llvm::Error::success().
getGlobalsStreamIndex()
uint32_t llvm::pdb::GSIStreamBuilder::getGlobalsStreamIndex () const inline
Definition at line 60 of file GSIStreamBuilder.h.
Referenced by commit().
getPublicsStreamIndex()
uint32_t llvm::pdb::GSIStreamBuilder::getPublicsStreamIndex () const inline
Definition at line 59 of file GSIStreamBuilder.h.
Referenced by commit().
getRecordStreamIndex()
uint32_t llvm::pdb::GSIStreamBuilder::getRecordStreamIndex () const inline
Definition at line 61 of file GSIStreamBuilder.h.
Referenced by commit().
operator=()
GSIStreamBuilder & llvm::pdb::GSIStreamBuilder::operator= (const GSIStreamBuilder &) delete
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/GSIStreamBuilder.h
lib/DebugInfo/PDB/Native/GSIStreamBuilder.cpp