LLVM: llvm::AArch64FrameLowering Class Reference
llvm::AArch64FrameLowering Class Reference
#include "Target/AArch64/AArch64FrameLowering.h"
Public Member Functions
AArch64FrameLowering ()
void resetCFIToInitialState (MachineBasicBlock &MBB) const override
Emit CFI instructions that recreate the state of the unwind information upon fucntion entry.
MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const override
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
bool enableCFIFixup (MachineFunction &MF) const override
Returns true if we may need to fix the unwind information for the function.
bool canUseAsPrologue (const MachineBasicBlock &MBB) const override
Check whether or not the given MBB can be used as a prologue for the target.
StackOffset getFrameIndexReference (const MachineFunction &MF, int FI, Register &FrameReg) const override
getFrameIndexReference - Provide a base+offset reference to an FI slot for debug info.
StackOffset resolveFrameIndexReference (const MachineFunction &MF, int FI, Register &FrameReg, bool PreferFP, bool ForSimm) const
StackOffset resolveFrameOffsetReference (const MachineFunction &MF, int64_t ObjectOffset, bool isFixed, bool isSVE, Register &FrameReg, bool PreferFP, bool ForSimm) const
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const override
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, MutableArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const override
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
bool canUseRedZone (const MachineFunction &MF) const
Can this function use the red zone for local allocations.
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
bool hasReservedCallFrame (const MachineFunction &MF) const override
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI, unsigned &MinCSFrameIndex, unsigned &MaxCSFrameIndex) const override
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS) const override
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
bool enableShrinkWrapping (const MachineFunction &MF) const override
Returns true if the target will correctly handle shrink wrapping.
bool enableStackSlotScavenging (const MachineFunction &MF) const override
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
TargetStackID::Value getStackIDForScalableVectors () const override
Returns the StackID that scalable vectors should be associated with.
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS) const override
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
void processFunctionBeforeFrameIndicesReplaced (MachineFunction &MF, RegScavenger *RS) const override
processFunctionBeforeFrameIndicesReplaced - This method is called immediately before MO_FrameIndex operands are eliminated, but after the frame is finalized.
unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const override
The parent frame offset (aka dispFrame) is only used on X86_64 to retrieve the parent's frame pointer.
unsigned getWinEHFuncletFrameSize (const MachineFunction &MF) const
Funclets only need to account for space for the callee saved registers, as the locals are accounted for in the parent's stack frame.
StackOffset getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, Register &FrameReg, bool IgnoreSPUpdates) const override
For Win64 AArch64 EH, the offset to the Unwind object is from the SP before the update.
StackOffset getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const override
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
int getSEHFrameIndexOffset (const MachineFunction &MF, int FI) const
bool isSupportedStackID (TargetStackID::Value ID) const override
bool isStackIdSafeForLocalArea (unsigned StackId) const override
This method returns whether or not it is safe for an object with the given stack id to be bundled into the local area.
void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &ObjectsToAllocate) const override
Order the symbols in the local stack frame.
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align(1), bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
Align getStackAlign () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
virtual uint64_t getStackThreshold () const
getStackThreshold - Return the maximum stack size
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
Align getTransientStackAlign () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual bool isStackIdSafeForLocalArea (unsigned StackId) const
This method returns whether or not it is safe for an object with the given stack id to be bundled into the local area.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool allocateScavengingFrameIndexesNearIncomingSP (const MachineFunction &MF) const
Control the placement of special register scavenging spill slots when allocating a stack frame.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI, unsigned &MinCSFrameIndex, unsigned &MaxCSFrameIndex) const
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
virtual bool targetHandlesStackFrameRounding () const
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
virtual bool enableShrinkWrapping (const MachineFunction &MF) const
Returns true if the target will correctly handle shrink wrapping.
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual bool enableCalleeSaveSkip (const MachineFunction &MF) const
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
virtual void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const =0
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
virtual void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const =0
virtual void emitZeroCallUsedRegs (BitVector RegsToZero, MachineBasicBlock &MBB) const
emitZeroCallUsedRegs - Zeros out call used registers.
virtual void emitCalleeSavedFrameMovesFullCFA (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI) const
With basic block sections, emit callee saved frame moves for basic blocks that are in a different section.
virtual bool enableCFIFixup (MachineFunction &MF) const
Returns true if we may need to fix the unwind information for the function.
virtual void resetCFIToInitialState (MachineBasicBlock &MBB) const
Emit CFI instructions that recreate the state of the unwind information upon fucntion entry.
virtual void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Replace a StackProbe stub (if any) with the actual probe code inline.
virtual bool stackProbeFunctionModifiesSP () const
Does the stack probe function call return with a modified stack pointer?
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
virtual bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, MutableArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
virtual bool keepFramePointer (const MachineFunction &MF) const
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
virtual bool hasFP (const MachineFunction &MF) const =0
hasFP - Return true if the specified function should have a dedicated frame pointer register.
virtual bool hasReservedCallFrame (const MachineFunction &MF) const
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual StackOffset getFrameIndexReference (const MachineFunction &MF, int FI, Register &FrameReg) const
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
virtual StackOffset getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, Register &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual StackOffset getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
virtual void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS=nullptr) const
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
virtual void processFunctionBeforeFrameIndicesReplaced (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameIndicesReplaced - This method is called immediately before MO_FrameIndex operands are eliminated, but after the frame is finalized.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual bool canUseAsPrologue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a prologue for the target.
virtual bool canUseAsEpilogue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a epilogue for the target.
virtual TargetStackID::Value getStackIDForScalableVectors () const
Returns the StackID that scalable vectors should be associated with.
virtual bool isSupportedStackID (TargetStackID::Value ID) const
virtual bool isProfitableForNoCSROpt (const Function &F) const
Check if the no-CSR optimisation is profitable for the given function.
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual Register getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
virtual DwarfFrameBase getDwarfFrameBase (const MachineFunction &MF) const
Return the frame base information to be encoded in the DWARF subprogram debug info.
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp , StackGrowsDown }
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Detailed Description
Definition at line 21 of file AArch64FrameLowering.h.
Constructor & Destructor Documentation
AArch64FrameLowering()
llvm::AArch64FrameLowering::AArch64FrameLowering () inline explicit
Definition at line 23 of file AArch64FrameLowering.h.
Member Function Documentation
assignCalleeSavedSpillSlots()
bool AArch64FrameLowering::assignCalleeSavedSpillSlots (MachineFunction & MF, const TargetRegisterInfo * TRI, std::vector< CalleeSavedInfo > & CSI, unsigned & MinCSFrameIndex, unsigned & MaxCSFrameIndex) const override virtual
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
If implemented, assignCalleeSavedSpillSlots() should assign frame slots to all CSI entries and return true. If this method returns false, spill slots will be assigned using generic implementation. assignCalleeSavedSpillSlots() may add, delete or rearrange elements of CSI.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 3437 of file AArch64FrameLowering.cpp.
References llvm::MachineFrameInfo::CreateStackObject(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::TargetRegisterInfo::getSpillAlign(), llvm::TargetRegisterInfo::getSpillSize(), hasFP(), llvm::AArch64FunctionInfo::hasSwiftAsyncContext(), isTargetWindows(), needsWinCFI(), llvm::AArch64FunctionInfo::setSwiftAsyncContextFrameIdx(), and Size.
canUseAsPrologue()
bool AArch64FrameLowering::canUseAsPrologue (const MachineBasicBlock & MBB) const override virtual
Check whether or not the given MBB can be used as a prologue for the target.
The prologue will be inserted first in this basic block. This method is used by the shrink-wrapping pass to decide if MBB will be correctly handled by the target. As soon as the target enable shrink-wrapping without overriding this method, we assume that each basic block is a valid prologue.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1040 of file AArch64FrameLowering.cpp.
References llvm::LivePhysRegs::available(), findScratchNonCalleeSaveRegister(), llvm::MachineFunction::getInfo(), getLiveRegsForEntryMBB(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::AArch64Subtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::AArch64Subtarget::getTargetLowering(), llvm::AArch64TargetLowering::hasInlineStackProbe(), llvm::AArch64FunctionInfo::hasSwiftAsyncContext(), MBB, MRI, and TRI.
canUseRedZone()
bool AArch64FrameLowering::canUseRedZone (const MachineFunction & MF) const
Can this function use the red zone for local allocations.
Definition at line 422 of file AArch64FrameLowering.cpp.
References EnableRedZone, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::AArch64FunctionInfo::getLocalStackSize(), llvm::AArch64TargetLowering::getRedZoneSize(), llvm::MachineFunction::getSubtarget(), getSVEStackSize(), llvm::AArch64Subtarget::getTargetLowering(), llvm::MachineFrameInfo::hasCalls(), and hasFP().
Referenced by emitEpilogue(), emitPrologue(), and resolveFrameOffsetReference().
determineCalleeSaves()
void AArch64FrameLowering::determineCalleeSaves (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS) const override virtual
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
The default implementation checks populates the SavedRegs bitset with all registers which are modified in the function, targets may override this function to save additional registers. This method also sets up the register scavenger ensuring there is a free register or a frameindex available. This method should not be called by any passes outside of PEI, because it may change state passed in by MF and RS. The preferred interface outside PEI is getCalleeSaves.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 3226 of file AArch64FrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::alignTo(), assert(), llvm::AArch64RegisterInfo::cannotEliminateFrame(), contains(), llvm::BitVector::count(), llvm::MachineFrameInfo::CreateStackObject(), llvm::dbgs(), llvm::TargetFrameLowering::determineCalleeSaves(), estimateRSStackSizeLimit(), llvm::MachineFrameInfo::estimateStackSize(), llvm::AArch64RegisterInfo::getBaseRegister(), llvm::MachineRegisterInfo::getCalleeSavedRegs(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFunction::getRegInfo(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::CallingConv::GHC, llvm::AArch64RegisterInfo::hasBasePointer(), hasFP(), I, llvm::MachineFrameInfo::isCalleeSavedInfoValid(), llvm::MachineRegisterInfo::isPhysRegUsed(), llvm::AArch64RegisterInfo::isReservedReg(), llvm::AArch64Subtarget::isTargetWindows(), LLVM_DEBUG, MRI, llvm::printReg(), produceCompactUnwindFrame(), RegSize, llvm::BitVector::reset(), llvm::BitVector::set(), llvm::BitVector::set_bits(), Size, llvm::BitVector::test(), TRI, llvm::CallingConv::Win64, and windowsRequiresStackProbe().
eliminateCallFramePseudoInstr()
MachineBasicBlock::iterator AArch64FrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions. Returns an iterator pointing to the instruction after the replaced one.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 490 of file AArch64FrameLowering.cpp.
References llvm::alignTo(), assert(), llvm::MachineRegisterInfo::createVirtualRegister(), DL, llvm::emitFrameOffset(), llvm::MachineBasicBlock::erase(), llvm::StackOffset::get(), llvm::StackOffset::getFixed(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getRegInfo(), llvm::TargetFrameLowering::getStackAlign(), llvm::MachineFunction::getSubtarget(), llvm::AArch64TargetLowering::hasInlineStackProbe(), hasReservedCallFrame(), llvm::MachineFrameInfo::hasVarSizedObjects(), I, MBB, llvm::AArch64::StackProbeMaxUnprobedStack, and TII.
emitEpilogue()
void AArch64FrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 2149 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addUse(), llvm::Always, assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), canUseRedZone(), llvm::MCCFIInstruction::cfiDefCfa(), convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::DeploymentBased, DL, llvm::emitFrameOffset(), emitShadowCallStackEpilogue(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), fixupCalleeSaveRestoreStackOffset(), llvm::MachineInstr::FrameDestroy, getArgumentStackToRestore(), llvm::AArch64FunctionInfo::getCalleeSaveBaseToFrameRecordOffset(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::Function::getCallingConv(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::StackOffset::getFixed(), getFixedObjectSize(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::AArch64FunctionInfo::getLocalStackSize(), llvm::StackOffset::getScalable(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::AArch64FunctionInfo::getSVECalleeSavedStackSize(), getSVEStackSize(), llvm::MachineFunction::getTarget(), getWinEHFuncletFrameSize(), llvm::CallingConv::GHC, llvm::MachineFunction::hasEHFunclets(), hasFP(), llvm::AArch64FunctionInfo::hasSwiftAsyncContext(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFunction::hasWinCFI(), if(), isFuncletReturnInstr(), llvm::AArch64InstrInfo::isSEHInstruction(), llvm::AArch64FunctionInfo::isStackRealigned(), IsSVECalleeSave(), llvm::make_scope_exit(), MBB, MBBI, llvm::AArch64FunctionInfo::needsAsyncDwarfUnwindInfo(), llvm::AArch64FunctionInfo::needsShadowCallStackPrologueEpilogue(), needsWinCFI(), llvm::Never, llvm::TargetMachine::Options, llvm::MachineFunction::setHasWinCFI(), llvm::AArch64FunctionInfo::setLocalStackSize(), llvm::MachineInstrBuilder::setMIFlag(), llvm::MachineInstrBuilder::setMIFlags(), llvm::AArch64FunctionInfo::shouldSignReturnAddress(), llvm::TargetOptions::SwiftAsyncFramePointer, and TII.
emitPrologue()
void AArch64FrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 1614 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addUse(), llvm::Always, assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), canUseRedZone(), llvm::MCCFIInstruction::cfiDefCfaOffset(), llvm::classifyEHPersonality(), Cleanup, convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::HexagonInstrInfo::copyPhysReg(), llvm::createDefCFA(), llvm::MachineOperand::CreateImm(), llvm::MCContext::createTempSymbol(), llvm::dbgs(), llvm::RegState::Dead, llvm::RegState::Define, llvm::DeploymentBased, DL, emitDefineCFAWithFP(), llvm::emitFrameOffset(), emitShadowCallStackPrologue(), llvm::AArch64_AM::encodeLogicalImmediate(), llvm::MachineBasicBlock::end(), End, F, fixupCalleeSaveRestoreStackOffset(), for(), llvm::MachineInstr::FrameSetup, llvm::Triple::getArchName(), llvm::AArch64_AM::getArithExtendImm(), llvm::Function::getAttributes(), llvm::getBLRCallOpcode(), llvm::AArch64FunctionInfo::getCalleeSaveBaseToFrameRecordOffset(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::Function::getCallingConv(), llvm::AArch64Subtarget::getChkStkName(), llvm::TargetMachine::getCodeModel(), llvm::MachineModuleInfo::getContext(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::StackOffset::getFixed(), getFixedObjectSize(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::AArch64Subtarget::getInstrInfo(), getLivePhysRegsUpTo(), llvm::AArch64FunctionInfo::getLocalStackSize(), llvm::MachineFrameInfo::getMaxAlign(), llvm::MachineFunction::getMMI(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::AArch64Subtarget::getRegisterInfo(), llvm::StackOffset::getScalable(), llvm::AArch64_AM::getShifterImm(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::AArch64FunctionInfo::getSVECalleeSavedStackSize(), getSVEStackSize(), llvm::AArch64FunctionInfo::getTaggedBasePointerIndex(), llvm::MachineFunction::getTarget(), llvm::AArch64Subtarget::getTargetTriple(), getWinEHFuncletFrameSize(), llvm::CallingConv::GHC, hasFP(), llvm::AArch64FunctionInfo::hasStackFrame(), llvm::AArch64FunctionInfo::hasSwiftAsyncContext(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::RegState::Implicit, llvm::MachineBasicBlock::instr_begin(), llvm::isAsynchronousEHPersonality(), llvm::AArch64Subtarget::isCallingConvWin64(), llvm::MachineBasicBlock::isEHFuncletEntry(), IsSVECalleeSave(), llvm::AArch64Subtarget::isTargetILP32(), llvm::CodeModel::Kernel, llvm::RegState::Kill, llvm::CodeModel::Large, LLVM_DEBUG, llvm::AArch64_AM::LSL, llvm::make_range(), llvm::make_scope_exit(), MBB, MBBI, llvm::CodeModel::Medium, MI, llvm::AArch64II::MO_GOT, llvm::AArch64FunctionInfo::needsAsyncDwarfUnwindInfo(), llvm::AArch64FunctionInfo::needsDwarfUnwindInfo(), needsWinCFI(), llvm::Never, llvm::TargetMachine::Options, Prolog, llvm::LivePhysRegs::removeReg(), llvm::report_fatal_error(), llvm::AArch64FunctionInfo::setHasRedZone(), llvm::MachineFunction::setHasWinCFI(), llvm::AArch64FunctionInfo::setLocalStackSize(), llvm::MachineInstrBuilder::setMIFlag(), llvm::MachineInstrBuilder::setMIFlags(), llvm::AArch64FunctionInfo::setStackRealigned(), llvm::AArch64FunctionInfo::setTaggedBasePointerOffset(), llvm::CodeModel::Small, llvm::AArch64Subtarget::swiftAsyncContextIsDynamicallySet(), llvm::TargetOptions::SwiftAsyncFramePointer, TII, llvm::CodeModel::Tiny, TRI, llvm::AArch64_AM::UXTX, llvm::Align::value(), and windowsRequiresStackProbe().
enableCFIFixup()
bool AArch64FrameLowering::enableCFIFixup (MachineFunction & MF) const override virtual
Returns true if we may need to fix the unwind information for the function.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2483 of file AArch64FrameLowering.cpp.
References llvm::TargetFrameLowering::enableCFIFixup(), and llvm::MachineFunction::getInfo().
enableShrinkWrapping()
bool llvm::AArch64FrameLowering::enableShrinkWrapping (const MachineFunction & MF) const inline override virtual
Returns true if the target will correctly handle shrink wrapping.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 78 of file AArch64FrameLowering.h.
enableStackSlotScavenging()
bool AArch64FrameLowering::enableStackSlotScavenging (const MachineFunction & MF) const override virtual
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 3490 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getInfo(), llvm::AArch64FunctionInfo::hasCalleeSaveStackFreeSpace(), hasFP(), and llvm::AArch64FunctionInfo::hasStreamingModeChanges().
getFrameIndexReference()
StackOffset AArch64FrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, Register & FrameReg) const override virtual
getFrameIndexReference - Provide a base+offset reference to an FI slot for debug info.
It's the same as what we use for resolving the code-gen references for now. FIXME: This can go wrong when references are SP-relative and simple call frames aren't used.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2493 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getFunction(), llvm::Function::hasFnAttribute(), and resolveFrameIndexReference().
Referenced by getFrameIndexReferencePreferSP().
getFrameIndexReferencePreferSP()
StackOffset AArch64FrameLowering::getFrameIndexReferencePreferSP (const MachineFunction & MF, int FI, Register & FrameReg, bool IgnoreSPUpdates) const override virtual
For Win64 AArch64 EH, the offset to the Unwind object is from the SP before the update.
This is easily retrieved as it is exactly the offset that is set in processFunctionBeforeFrameFinalized.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 4092 of file AArch64FrameLowering.cpp.
References llvm::dbgs(), llvm::StackOffset::getFixed(), getFrameIndexReference(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetSubtargetInfo::getRegisterInfo(), getStackOffset(), llvm::AArch64FunctionInfo::getStackSizeSVE(), llvm::MachineFunction::getSubtarget(), llvm::TargetRegisterInfo::hasStackRealignment(), llvm::MachineFrameInfo::hasVarSizedObjects(), and LLVM_DEBUG.
getNonLocalFrameIndexReference()
StackOffset AArch64FrameLowering::getNonLocalFrameIndexReference (const MachineFunction & MF, int FI) const override virtual
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
The offset can be from either FP/BP/SP based on which base register is returned by llvm.localaddress.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2503 of file AArch64FrameLowering.cpp.
References llvm::StackOffset::getFixed(), and getSEHFrameIndexOffset().
Referenced by llvm::AArch64RegisterInfo::eliminateFrameIndex().
getSEHFrameIndexOffset()
int AArch64FrameLowering::getSEHFrameIndexOffset (const MachineFunction & MF, int FI) const
Definition at line 2529 of file AArch64FrameLowering.cpp.
References llvm::StackOffset::getFixed(), getFPOffset(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetSubtargetInfo::getRegisterInfo(), getStackOffset(), and llvm::MachineFunction::getSubtarget().
Referenced by getNonLocalFrameIndexReference().
getStackIDForScalableVectors()
TargetStackID::Value AArch64FrameLowering::getStackIDForScalableVectors () const override virtual
Returns the StackID that scalable vectors should be associated with.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 394 of file AArch64FrameLowering.cpp.
References llvm::TargetStackID::ScalableVector.
getWinEHFuncletFrameSize()
unsigned AArch64FrameLowering::getWinEHFuncletFrameSize (const MachineFunction & MF) const
Funclets only need to account for space for the callee saved registers, as the locals are accounted for in the parent's stack frame.
Definition at line 4122 of file AArch64FrameLowering.cpp.
References llvm::alignTo(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getMaxCallFrameSize(), and llvm::TargetFrameLowering::getStackAlign().
Referenced by emitEpilogue(), and emitPrologue().
getWinEHParentFrameOffset()
unsigned AArch64FrameLowering::getWinEHParentFrameOffset (const MachineFunction & MF) const override virtual
The parent frame offset (aka dispFrame) is only used on X86_64 to retrieve the parent's frame pointer.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 4115 of file AArch64FrameLowering.cpp.
hasFP()
bool AArch64FrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register.
Implements llvm::TargetFrameLowering.
Definition at line 444 of file AArch64FrameLowering.cpp.
References DefaultSafeSPDisplacement, llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineFunction::hasEHFunclets(), llvm::MachineFrameInfo::hasPatchPoint(), llvm::MachineFrameInfo::hasStackMap(), llvm::TargetRegisterInfo::hasStackRealignment(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFrameInfo::isFrameAddressTaken(), llvm::MachineFrameInfo::isMaxCallFrameSizeComputed(), and llvm::TargetMachine::Options.
Referenced by assignCalleeSavedSpillSlots(), canUseRedZone(), determineCalleeSaves(), emitEpilogue(), emitPrologue(), enableStackSlotScavenging(), llvm::AArch64RegisterInfo::getFrameRegister(), llvm::AArch64RegisterInfo::getRegPressureLimit(), llvm::AArch64RegisterInfo::getStrictlyReservedRegs(), llvm::AArch64RegisterInfo::needsFrameBaseReg(), resolveFrameOffsetReference(), restoreCalleeSavedRegisters(), spillCalleeSavedRegisters(), and llvm::AArch64RegisterInfo::useFPForScavengingIndex().
hasReservedCallFrame()
bool AArch64FrameLowering::hasReservedCallFrame (const MachineFunction & MF) const override virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 481 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by eliminateCallFramePseudoInstr().
isStackIdSafeForLocalArea()
bool llvm::AArch64FrameLowering::isStackIdSafeForLocalArea (unsigned StackId) const inline override virtual
This method returns whether or not it is safe for an object with the given stack id to be bundled into the local area.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 115 of file AArch64FrameLowering.h.
References llvm::TargetStackID::ScalableVector.
isSupportedStackID()
bool llvm::AArch64FrameLowering::isSupportedStackID (TargetStackID::Value ID) const inline override virtual
Reimplemented from llvm::TargetFrameLowering.
Definition at line 104 of file AArch64FrameLowering.h.
References llvm::TargetStackID::Default, llvm::TargetStackID::NoAlloc, and llvm::TargetStackID::ScalableVector.
orderFrameObjects()
void AArch64FrameLowering::orderFrameObjects (const MachineFunction & MF, SmallVectorImpl< int > & objectsToAllocate) const override virtual
Order the symbols in the local stack frame.
The list of objects that we want to order is in objectsToAllocate as indices into the MachineFrameInfo. The array can be reordered in any way upon return. The contents of the array, however, may not be modified (i.e. only their order may be changed). By default, just maintain the original order.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 4196 of file AArch64FrameLowering.cpp.
References llvm::dbgs(), llvm::SmallVectorBase< Size_T >::empty(), llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::AArch64FunctionInfo::getTaggedBasePointerIndex(), if(), llvm::MachineOperand::isFI(), LLVM_DEBUG, MBB, MI, OpIndex, OrderFrameObjects, and llvm::stable_sort().
processFunctionBeforeFrameFinalized()
void AArch64FrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS) const override virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 3619 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::alignTo(), assert(), llvm::RegScavenger::backward(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineFrameInfo::CreateFixedObject(), DL, llvm::MachineBasicBlock::end(), llvm::RegScavenger::enterBasicBlockEnd(), llvm::RegScavenger::FindUnusedReg(), llvm::MachineInstr::FrameSetup, llvm::MachineFunction::front(), getFixedObjectSize(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::getKillRegState(), llvm::TargetFrameLowering::getStackGrowthDirection(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getWinEHFuncInfo(), llvm::MachineFunction::hasEHFunclets(), MBB, MBBI, llvm::AArch64FunctionInfo::setMinMaxSVECSFrameIndex(), llvm::AArch64FunctionInfo::setStackSizeSVE(), llvm::TargetFrameLowering::StackGrowsDown, TII, and llvm::WinEHFuncInfo::UnwindHelpFrameIdx.
processFunctionBeforeFrameIndicesReplaced()
void AArch64FrameLowering::processFunctionBeforeFrameIndicesReplaced (MachineFunction & MF, RegScavenger * RS = nullptr) const override virtual
processFunctionBeforeFrameIndicesReplaced - This method is called immediately before MO_FrameIndex operands are eliminated, but after the frame is finalized.
This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 4081 of file AArch64FrameLowering.cpp.
References StackTaggingMergeSetTag.
resetCFIToInitialState()
void AArch64FrameLowering::resetCFIToInitialState (MachineBasicBlock & MBB) const override virtual
Emit CFI instructions that recreate the state of the unwind information upon fucntion entry.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 631 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MCCFIInstruction::cfiDefCfa(), llvm::MCCFIInstruction::createNegateRAState(), DL, llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), Info, insertCFISameValue(), MBB, TII, and TRI.
resolveFrameIndexReference()
StackOffset AArch64FrameLowering::resolveFrameIndexReference (const MachineFunction & MF, int FI, Register & FrameReg, bool PreferFP, bool ForSimm) const
Definition at line 2539 of file AArch64FrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectOffset(), resolveFrameOffsetReference(), and llvm::TargetStackID::ScalableVector.
Referenced by llvm::AArch64RegisterInfo::eliminateFrameIndex(), and getFrameIndexReference().
resolveFrameOffsetReference()
StackOffset AArch64FrameLowering::resolveFrameOffsetReference (const MachineFunction & MF, int64_t ObjectOffset, bool isFixed, bool isSVE, Register & FrameReg, bool PreferFP, bool ForSimm) const
Definition at line 2550 of file AArch64FrameLowering.cpp.
References assert(), canUseRedZone(), llvm::StackOffset::get(), llvm::AArch64FunctionInfo::getCalleeSaveBaseToFrameRecordOffset(), llvm::AArch64FunctionInfo::getCalleeSavedStackSize(), llvm::Function::getCallingConv(), llvm::StackOffset::getFixed(), getFPOffset(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::AArch64FunctionInfo::getLocalStackSize(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::StackOffset::getScalable(), getStackOffset(), llvm::MachineFunction::getSubtarget(), getSVEStackSize(), llvm::MachineFunction::hasEHFunclets(), hasFP(), llvm::AArch64FunctionInfo::hasStackFrame(), and llvm::Offset.
Referenced by resolveFrameIndexReference().
restoreCalleeSavedRegisters()
bool AArch64FrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, MutableArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo * TRI) const override virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
If it returns true, and any of the registers in CSI is not restored, it sets the corresponding Restored flag in CSI to false. Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 3097 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), computeCalleeSaveRegisterPairs(), llvm::dbgs(), llvm::RegState::Define, DL, llvm::MachineBasicBlock::end(), llvm::First, llvm::MachineInstr::FrameDestroy, llvm::getDefRegState(), llvm::MachinePointerInfo::getFixedStack(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), hasFP(), InsertSEH(), LLVM_DEBUG, MBB, MBBI, llvm::MachineMemOperand::MOLoad, needsWinCFI(), llvm::printReg(), llvm::reverse(), ReverseCSRRestoreSeq, llvm::MachineInstrBuilder::setMIFlag(), Size, llvm::MachineBasicBlock::splice(), std::swap(), TII, and TRI.
spillCalleeSavedRegisters()
bool AArch64FrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 2977 of file AArch64FrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), computeCalleeSaveRegisterPairs(), llvm::dbgs(), DL, llvm::MachineInstr::FrameSetup, llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineBasicBlock::getParent(), getPrologueDeath(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), hasFP(), InsertSEH(), LLVM_DEBUG, MBB, MI, llvm::MachineMemOperand::MOStore, MRI, needsWinCFI(), llvm::printReg(), llvm::reverse(), llvm::TargetStackID::ScalableVector, llvm::MachineInstrBuilder::setMIFlag(), llvm::MachineFrameInfo::setStackID(), Size, std::swap(), TII, and TRI.
The documentation for this class was generated from the following files:
lib/Target/AArch64/AArch64FrameLowering.h
lib/Target/AArch64/AArch64FrameLowering.cpp