LLVM: llvm::VarDefInit Class Reference
llvm::VarDefInit Class Reference final
classname<targs...> - Represent an uninstantiated anonymous class instantiation.
#include "llvm/TableGen/Record.h"
Public Types
using const_iterator = ArgumentInit *const *
Public Member Functions
VarDefInit (const VarDefInit &)=delete
VarDefInit & operator= (const VarDefInit &)=delete
void operator delete (void *p)
void Profile (FoldingSetNodeID &ID) const
Init * resolveReferences (Resolver &R) const override
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
Init * Fold () const
std::string getAsString () const override
Convert this value to a literal form.
ArgumentInit * getArg (unsigned i) const
const_iterator args_begin () const
const_iterator args_end () const
size_t args_size () const
bool args_empty () const
ArrayRef< ArgumentInit * > args () const
Init * getBit (unsigned Bit) const override
Get the Init value of the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Get the type of the Init as a RecTy.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init * getCastTo (RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This function is used to implement the bit range selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
Is this a complete value with no unset (uninitialized) subvalues?
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print this value.
virtual std::string getAsString () const =0
Convert this value to a literal form.
virtual std::string getAsUnquotedString () const
Convert this value to a literal form, without adding quotes around a string.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
virtual Init * getCastTo (RecTy *Ty) const =0
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
virtual Init * convertInitializerTo (RecTy *Ty) const =0
Convert to a value whose type is Ty, or return null if this is not possible.
virtual Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This function is used to implement the bit range selection operator.
virtual RecTy * getFieldType (StringInit *FieldName) const
This function is used to implement the FieldInit class.
virtual Init * resolveReferences (Resolver &R) const
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
virtual Init * getBit (unsigned Bit) const =0
Get the Init value of the specified bit.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::TrailingObjects< VarDefInit, ArgumentInit * >
const T * getTrailingObjects () const
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
T * getTrailingObjects ()
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
TrailingObjects ()=default
TrailingObjects (const TrailingObjects &)=delete
TrailingObjects (TrailingObjects &&)=delete
TrailingObjects & operator= (const TrailingObjects &)=delete
TrailingObjects & operator= (TrailingObjects &&)=delete
Static Public Member Functions
static bool classof (const Init *I)
static VarDefInit * get (Record *Class, ArrayRef< ArgumentInit * > Args)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TrailingObjects< VarDefInit, ArgumentInit * >
static constexpr std::enable_if_t< std::is_same_v< Foo< TrailingTys... >, Foo< Tys... > >, size_t > additionalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the size of the trailing data, if an object were allocated with the given counts (The counts are in the same order as the template arguments).
static constexpr std::enable_if_t< std::is_same_v< Foo< TrailingTys... >, Foo< Tys... > >, size_t > totalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the total size of an object if it were allocated with the given trailing object counts.
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_DagInit , IK_DefInit , IK_FieldInit , IK_IntInit ,
IK_ListInit , IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit ,
IK_UnOpInit , IK_LastOpInit , IK_CondOpInit , IK_FoldOpInit ,
IK_IsAOpInit , IK_ExistsOpInit , IK_AnonymousNameInit , IK_StringInit ,
IK_VarInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit , IK_ArgumentInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
classname<targs...> - Represent an uninstantiated anonymous class instantiation.
Definition at line 1346 of file Record.h.
Member Typedef Documentation
const_iterator
using llvm::VarDefInit::const_iterator = ArgumentInit *const *
Definition at line 1381 of file Record.h.
Constructor & Destructor Documentation
VarDefInit()
llvm::VarDefInit::VarDefInit (const VarDefInit &) delete
Member Function Documentation
args()
ArrayRef< ArgumentInit * > llvm::VarDefInit::args () const inline
Definition at line 1391 of file Record.h.
References args_begin().
Referenced by Fold(), getAsString(), Profile(), and resolveReferences().
args_begin()
const_iterator llvm::VarDefInit::args_begin () const inline
Definition at line 1383 of file Record.h.
Referenced by args(), and args_end().
args_empty()
bool llvm::VarDefInit::args_empty () const inline
Definition at line 1389 of file Record.h.
args_end()
const_iterator llvm::VarDefInit::args_end () const inline
Definition at line 1386 of file Record.h.
References args_begin().
args_size()
size_t llvm::VarDefInit::args_size () const inline
Definition at line 1388 of file Record.h.
Referenced by resolveReferences().
classof()
static bool llvm::VarDefInit::classof (const Init * I) inline static
Definition at line 1364 of file Record.h.
References I, and llvm::Init::IK_VarDefInit.
Fold()
Init * VarDefInit::Fold () const
Definition at line 2346 of file Record.cpp.
References args().
get()
VarDefInit * VarDefInit::get (Record * Class, ArrayRef< ArgumentInit * > Args) static
Definition at line 2242 of file Record.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), llvm::detail::RecordKeeperImpl::Allocator, I, ProfileVarDefInit(), and llvm::detail::RecordKeeperImpl::TheVarDefInitPool.
Referenced by resolveReferences().
getArg()
ArgumentInit * llvm::VarDefInit::getArg (unsigned i) const inline
Definition at line 1376 of file Record.h.
References assert().
getAsString()
std::string VarDefInit::getAsString () const override virtual
Convert this value to a literal form.
Implements llvm::Init.
Definition at line 2359 of file Record.cpp.
References args(), and llvm::Record::getNameInitAsString().
getBit()
Init * llvm::VarDefInit::getBit (unsigned Bit) const inline override virtual
Get the Init value of the specified bit.
Implements llvm::Init.
Definition at line 1395 of file Record.h.
References llvm_unreachable.
operator delete()
void llvm::VarDefInit::operator delete (void * p) inline
Definition at line 1362 of file Record.h.
operator=()
VarDefInit & llvm::VarDefInit::operator= (const VarDefInit &) delete
Profile()
void VarDefInit::Profile (FoldingSetNodeID & ID) const
Definition at line 2260 of file Record.cpp.
References args(), and ProfileVarDefInit().
resolveReferences()
Init * VarDefInit::resolveReferences (Resolver & R) const override virtual
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 2325 of file Record.cpp.
References args(), args_size(), llvm::TrackUnresolvedResolver::foundUnresolved(), get(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::SmallVectorImpl< T >::reserve().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp