LLVM: llvm::ImmutableListFactory< T > Class Template Reference
llvm::ImmutableListFactory< T > Class Template Reference
#include "llvm/ADT/ImmutableList.h"
Public Member Functions
ImmutableListFactory ()
ImmutableListFactory (BumpPtrAllocator &Alloc)
~ImmutableListFactory ()
template<typename ElemT >
ImmutableList< T > concat (ElemT &&Head, ImmutableList< T > Tail)
template<typename ElemT >
ImmutableList< T > add (ElemT &&Data, ImmutableList< T > L)
template<typename... CtorArgs>
ImmutableList< T > emplace (ImmutableList< T > Tail, CtorArgs &&...Args)
ImmutableList< T > getEmptyList () const
template<typename ElemT >
ImmutableList< T > create (ElemT &&Data)
Detailed Description
template<typename T>
class llvm::ImmutableListFactory< T >
Definition at line 150 of file ImmutableList.h.
Constructor & Destructor Documentation
ImmutableListFactory() [1/2]
template<typename T > llvm::ImmutableListFactory< T >::ImmutableListFactory () inline
Definition at line 166 of file ImmutableList.h.
References Allocator.
ImmutableListFactory() [2/2]
template<typename T > llvm::ImmutableListFactory< T >::ImmutableListFactory (BumpPtrAllocator & Alloc) inline
Definition at line 169 of file ImmutableList.h.
References Allocator.
~ImmutableListFactory()
template<typename T > llvm::ImmutableListFactory< T >::~ImmutableListFactory () inline
Definition at line 172 of file ImmutableList.h.
Member Function Documentation
add()
template<typename T > template<typename ElemT > ImmutableList< T > llvm::ImmutableListFactory< T >::add (ElemT && Data, ImmutableList< T > L) inline
Definition at line 200 of file ImmutableList.h.
References llvm::ImmutableListFactory< T >::concat(), and llvm::Data.
concat()
template<typename T > template<typename ElemT > ImmutableList< T > llvm::ImmutableListFactory< T >::concat (ElemT && Head, ImmutableList< T > Tail) inline
Definition at line 177 of file ImmutableList.h.
References A, llvm::FoldingSetImpl< Derived, T >::FindNodeOrInsertPos(), llvm::FoldingSetImpl< Derived, T >::InsertNode(), llvm::ImmutableListImpl< T >::Profile(), and llvm::CallingConv::Tail.
Referenced by llvm::ImmutableListFactory< T >::add(), llvm::ImmutableListFactory< T >::create(), and llvm::ImmutableListFactory< T >::emplace().
create()
template<typename T > template<typename ElemT > ImmutableList< T > llvm::ImmutableListFactory< T >::create (ElemT && Data) inline
Definition at line 215 of file ImmutableList.h.
References llvm::ImmutableListFactory< T >::concat(), llvm::Data, and llvm::ImmutableListFactory< T >::getEmptyList().
emplace()
template<typename T > template<typename... CtorArgs> ImmutableList< T > llvm::ImmutableListFactory< T >::emplace (ImmutableList< T > Tail, CtorArgs &&... Args) inline
Definition at line 205 of file ImmutableList.h.
References llvm::ImmutableListFactory< T >::concat(), T, and llvm::CallingConv::Tail.
getEmptyList()
template<typename T > ImmutableList< T > llvm::ImmutableListFactory< T >::getEmptyList () const inline
Definition at line 210 of file ImmutableList.h.
Referenced by llvm::ImmutableListFactory< T >::create().
The documentation for this class was generated from the following file:
include/llvm/ADT/ImmutableList.h