LLVM: llvm::WebAssemblyAsmTypeCheck Class Reference
llvm::WebAssemblyAsmTypeCheck Class Reference final
#include "Target/WebAssembly/AsmParser/WebAssemblyAsmTypeCheck.h"
Public Member Functions
WebAssemblyAsmTypeCheck (MCAsmParser &Parser, const MCInstrInfo &MII, bool is64)
void funcDecl (const wasm::WasmSignature &Sig)
void localDecl (const SmallVectorImpl< wasm::ValType > &Locals)
void setLastSig (const wasm::WasmSignature &Sig)
bool endOfFunction (SMLoc ErrorLoc)
bool typeCheck (SMLoc ErrorLoc, const MCInst &Inst, OperandVector &Operands)
void Clear ()
Detailed Description
Definition at line 27 of file WebAssemblyAsmTypeCheck.h.
Constructor & Destructor Documentation
WebAssemblyAsmTypeCheck()
llvm::WebAssemblyAsmTypeCheck::WebAssemblyAsmTypeCheck (MCAsmParser & Parser, const MCInstrInfo & MII, bool is64)
Definition at line 45 of file WebAssemblyAsmTypeCheck.cpp.
Member Function Documentation
Clear()
void llvm::WebAssemblyAsmTypeCheck::Clear () inline
Definition at line 63 of file WebAssemblyAsmTypeCheck.h.
References llvm::SmallVectorImpl< T >::clear().
endOfFunction()
bool llvm::WebAssemblyAsmTypeCheck::endOfFunction (SMLoc ErrorLoc)
Definition at line 234 of file WebAssemblyAsmTypeCheck.cpp.
References llvm::SmallVectorBase< Size_T >::empty(), llvm::reverse(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by typeCheck().
funcDecl()
void llvm::WebAssemblyAsmTypeCheck::funcDecl (const wasm::WasmSignature & Sig)
Definition at line 50 of file WebAssemblyAsmTypeCheck.cpp.
References llvm::SmallVectorImpl< T >::assign(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::wasm::WasmSignature::Params, and llvm::wasm::WasmSignature::Returns.
localDecl()
void llvm::WebAssemblyAsmTypeCheck::localDecl (const SmallVectorImpl< wasm::ValType > & Locals)
Definition at line 56 of file WebAssemblyAsmTypeCheck.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::SmallVectorImpl< T >::insert().
setLastSig()
void llvm::WebAssemblyAsmTypeCheck::setLastSig (const wasm::WasmSignature & Sig) inline
Definition at line 59 of file WebAssemblyAsmTypeCheck.h.
typeCheck()
bool llvm::WebAssemblyAsmTypeCheck::typeCheck (SMLoc ErrorLoc, const MCInst & Inst, OperandVector & Operands)
Definition at line 248 of file WebAssemblyAsmTypeCheck.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), endOfFunction(), llvm::MCInstrInfo::get(), llvm::MCOperand::getImm(), GetMnemonic(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::WebAssembly::getRegisterOpcode(), llvm::MCSymbolRefExpr::getSymbol(), I, llvm::wasm::I32, llvm::wasm::I64, llvm::SmallVectorImpl< T >::insert(), llvm::MCOperand::isImm(), Name, llvm::MCOI::OPERAND_REGISTER, Operands, llvm::wasm::WasmSignature::Params, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::WebAssembly::regClassToValType(), llvm::wasm::WasmSignature::Returns, llvm::wasm::WASM_SYMBOL_TYPE_FUNCTION, and llvm::wasm::WASM_SYMBOL_TYPE_TAG.
The documentation for this class was generated from the following files:
lib/Target/WebAssembly/AsmParser/WebAssemblyAsmTypeCheck.h
lib/Target/WebAssembly/AsmParser/WebAssemblyAsmTypeCheck.cpp