LLVM: llvm::TextChangeReporter< IRUnitT > Class Template Reference
llvm::TextChangeReporter< IRUnitT > Class Template Reference
#include "llvm/Passes/StandardInstrumentations.h"
Protected Member Functions
TextChangeReporter (bool Verbose)
void handleInitialIR (Any IR) override
void omitAfter (StringRef PassID, std::string &Name) override
void handleInvalidated (StringRef PassID) override
void handleFiltered (StringRef PassID, std::string &Name) override
void handleIgnored (StringRef PassID, std::string &Name) override
Protected Member Functions inherited from llvm::ChangeReporter< IRUnitT >
ChangeReporter (bool RunInVerboseMode)
void registerRequiredCallbacks (PassInstrumentationCallbacks &PIC)
virtual void handleInitialIR (Any IR)=0
virtual void generateIRRepresentation (Any IR, StringRef PassID, IRUnitT &Output)=0
virtual void omitAfter (StringRef PassID, std::string &Name)=0
virtual void handleAfter (StringRef PassID, std::string &Name, const IRUnitT &Before, const IRUnitT &After, Any)=0
virtual void handleInvalidated (StringRef PassID)=0
virtual void handleFiltered (StringRef PassID, std::string &Name)=0
virtual void handleIgnored (StringRef PassID, std::string &Name)=0
Protected Attributes
raw_ostream & Out
Protected Attributes inherited from llvm::ChangeReporter< IRUnitT >
std::vector< IRUnitT > BeforeStack
bool InitialIR = true
const bool VerboseMode
Additional Inherited Members
Public Member Functions inherited from llvm::ChangeReporter< IRUnitT >
virtual ~ChangeReporter ()
void saveIRBeforePass (Any IR, StringRef PassID, StringRef PassName)
void handleIRAfterPass (Any IR, StringRef PassID, StringRef PassName)
void handleInvalidatedPass (StringRef PassID)
Detailed Description
template<typename IRUnitT>
class llvm::TextChangeReporter< IRUnitT >
Definition at line 240 of file StandardInstrumentations.h.
Constructor & Destructor Documentation
TextChangeReporter()
template<typename T > TextChangeReporter::TextChangeReporter (bool Verbose) protected
Definition at line 439 of file StandardInstrumentations.cpp.
Member Function Documentation
handleFiltered()
template<typename T > void TextChangeReporter::handleFiltered (StringRef PassID, std::string & Name) override protected virtual
Implements llvm::ChangeReporter< IRUnitT >.
Definition at line 463 of file StandardInstrumentations.cpp.
References llvm::formatv(), and Name.
handleIgnored()
template<typename T > void TextChangeReporter::handleIgnored (StringRef PassID, std::string & Name) override protected virtual
Implements llvm::ChangeReporter< IRUnitT >.
Definition at line 471 of file StandardInstrumentations.cpp.
References llvm::formatv(), and Name.
handleInitialIR()
template<typename T > void TextChangeReporter::handleInitialIR (Any IR) override protected virtual
Implements llvm::ChangeReporter< IRUnitT >.
Definition at line 442 of file StandardInstrumentations.cpp.
References assert(), and IR.
handleInvalidated()
template<typename T > void TextChangeReporter::handleInvalidated (StringRef PassID) override protected virtual
Implements llvm::ChangeReporter< IRUnitT >.
Definition at line 458 of file StandardInstrumentations.cpp.
References llvm::formatv().
omitAfter()
template<typename T > void TextChangeReporter::omitAfter (StringRef PassID, std::string & Name) override protected virtual
Implements llvm::ChangeReporter< IRUnitT >.
Definition at line 452 of file StandardInstrumentations.cpp.
References llvm::formatv(), and Name.
Member Data Documentation
Out
template<typename IRUnitT > raw_ostream& llvm::TextChangeReporter< IRUnitT >::Out protected
Definition at line 257 of file StandardInstrumentations.h.
The documentation for this class was generated from the following files:
include/llvm/Passes/StandardInstrumentations.h
lib/Passes/StandardInstrumentations.cpp