LLVM: llvm::object::Elf_Note_Iterator_Impl< ELFT > Class Template Reference
llvm::object::Elf_Note_Iterator_Impl< ELFT > Class Template Reference
#include "llvm/Object/ELFTypes.h"
Public Types
using iterator_category = std::forward_iterator_tag
using value_type = Elf_Note_Impl< ELFT >
using difference_type = std::ptrdiff_t
using pointer = value_type *
using reference = value_type &
Public Member Functions
Elf_Note_Iterator_Impl & operator++ ()
bool operator== (Elf_Note_Iterator_Impl Other) const
bool operator!= (Elf_Note_Iterator_Impl Other) const
Elf_Note_Impl< ELFT > operator* () const
Friends
template<class ELFFileELFT >
class ELFFile
Detailed Description
template<class ELFT>
class llvm::object::Elf_Note_Iterator_Impl< ELFT >
Definition at line 655 of file ELFTypes.h.
Member Typedef Documentation
difference_type
template<class ELFT > using llvm::object::Elf_Note_Iterator_Impl< ELFT >::difference_type = std::ptrdiff_t
Definition at line 659 of file ELFTypes.h.
iterator_category
template<class ELFT > using llvm::object::Elf_Note_Iterator_Impl< ELFT >::iterator_category = std::forward_iterator_tag
Definition at line 657 of file ELFTypes.h.
pointer
template<class ELFT > using llvm::object::Elf_Note_Iterator_Impl< ELFT >::pointer = value_type *
Definition at line 660 of file ELFTypes.h.
reference
template<class ELFT > using llvm::object::Elf_Note_Iterator_Impl< ELFT >::reference = value_type &
Definition at line 661 of file ELFTypes.h.
value_type
template<class ELFT > using llvm::object::Elf_Note_Iterator_Impl< ELFT >::value_type = Elf_Note_Impl<ELFT>
Definition at line 658 of file ELFTypes.h.
Member Function Documentation
operator!=()
template<class ELFT > bool llvm::object::Elf_Note_Iterator_Impl< ELFT >::operator!= (Elf_Note_Iterator_Impl< ELFT > Other) const inline
Definition at line 727 of file ELFTypes.h.
References Other.
operator*()
template<class ELFT > Elf_Note_Impl< ELFT > llvm::object::Elf_Note_Iterator_Impl< ELFT >::operator* () const inline
Definition at line 730 of file ELFTypes.h.
References assert().
operator++()
template<class ELFT > Elf_Note_Iterator_Impl & llvm::object::Elf_Note_Iterator_Impl< ELFT >::operator++ () inline
Definition at line 713 of file ELFTypes.h.
References assert(), and llvm::object::Elf_Nhdr_Impl< ELFT >::getSize().
operator==()
template<class ELFT > bool llvm::object::Elf_Note_Iterator_Impl< ELFT >::operator== (Elf_Note_Iterator_Impl< ELFT > Other) const inline
Definition at line 720 of file ELFTypes.h.
References Other.
Friends And Related Function Documentation
ELFFile
template<class ELFT > template<class ELFFileELFT > friend class ELFFile friend
Definition at line 670 of file ELFTypes.h.
The documentation for this class was generated from the following file:
include/llvm/Object/ELFTypes.h