LLVM: llvm::SystemZSelectionDAGInfo Class Reference
llvm::SystemZSelectionDAGInfo Class Reference
#include "Target/SystemZ/SystemZSelectionDAGInfo.h"
Public Member Functions
SystemZSelectionDAGInfo ()=default
SDValue EmitTargetCodeForMemcpy (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, Align Alignment, bool IsVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override
Emit target-specific code that performs a memcpy.
SDValue EmitTargetCodeForMemset (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Dst, SDValue Byte, SDValue Size, Align Alignment, bool IsVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo) const override
Emit target-specific code that performs a memset.
std::pair< SDValue, SDValue > EmitTargetCodeForMemcmp (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src1, SDValue Src2, SDValue Size, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const override
Emit target-specific code that performs a memcmp/bcmp, in cases where that is faster than a libcall.
std::pair< SDValue, SDValue > EmitTargetCodeForMemchr (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const override
Emit target-specific code that performs a memchr, in cases where that is faster than a libcall.
std::pair< SDValue, SDValue > EmitTargetCodeForStrcpy (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const override
Emit target-specific code that performs a strcpy or stpcpy, in cases where that is faster than a libcall.
std::pair< SDValue, SDValue > EmitTargetCodeForStrcmp (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src1, SDValue Src2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const override
Emit target-specific code that performs a strcmp, in cases where that is faster than a libcall.
std::pair< SDValue, SDValue > EmitTargetCodeForStrlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const override
std::pair< SDValue, SDValue > EmitTargetCodeForStrnlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const override
Public Member Functions inherited from llvm::SelectionDAGTargetInfo
SelectionDAGTargetInfo ()=default
SelectionDAGTargetInfo (const SelectionDAGTargetInfo &)=delete
SelectionDAGTargetInfo & operator= (const SelectionDAGTargetInfo &)=delete
virtual ~SelectionDAGTargetInfo ()
virtual SDValue EmitTargetCodeForMemcpy (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
Emit target-specific code that performs a memcpy.
virtual SDValue EmitTargetCodeForMemmove (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
Emit target-specific code that performs a memmove.
virtual SDValue EmitTargetCodeForMemset (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo) const
Emit target-specific code that performs a memset.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemcmp (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
Emit target-specific code that performs a memcmp/bcmp, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemchr (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const
Emit target-specific code that performs a memchr, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcpy (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const
Emit target-specific code that performs a strcpy or stpcpy, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcmp (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
Emit target-specific code that performs a strcmp, in cases where that is faster than a libcall.
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrnlen (SelectionDAG &DAG, const SDLoc &DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const
virtual SDValue EmitTargetCodeForSetTag (SelectionDAG &DAG, const SDLoc &dl, SDValue Chain, SDValue Addr, SDValue Size, MachinePointerInfo DstPtrInfo, bool ZeroData) const
virtual bool disableGenericCombines (CodeGenOptLevel OptLevel) const
Detailed Description
Definition at line 20 of file SystemZSelectionDAGInfo.h.
Constructor & Destructor Documentation
SystemZSelectionDAGInfo()
llvm::SystemZSelectionDAGInfo::SystemZSelectionDAGInfo () explicit default
Member Function Documentation
EmitTargetCodeForMemchr()
std::pair< SDValue, SDValue > SystemZSelectionDAGInfo::EmitTargetCodeForMemchr (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const override virtual
Emit target-specific code that performs a memchr, in cases where that is faster than a libcall.
The first returned SDValue is the result of the memchr and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 188 of file SystemZSelectionDAGInfo.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::SystemZ::CCMASK_SRST, llvm::SystemZ::CCMASK_SRST_FOUND, DL, End, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getVTList(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::Length, llvm::SystemZISD::SEARCH_STRING, and llvm::SystemZISD::SELECT_CCMASK.
EmitTargetCodeForMemcmp()
std::pair< SDValue, SDValue > SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const override virtual
Emit target-specific code that performs a memcmp/bcmp, in cases where that is faster than a libcall.
The first returned SDValue is the result of the memcmp and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 172 of file SystemZSelectionDAGInfo.cpp.
References addIPMSequence(), assert(), llvm::SystemZISD::CLC, DL, emitMemMemImm(), emitMemMemReg(), llvm::SDValue::getValue(), and Size.
EmitTargetCodeForMemcpy()
SDValue SystemZSelectionDAGInfo::EmitTargetCodeForMemcpy (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const override virtual
Emit target-specific code that performs a memcpy.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
If AlwaysInline is true, the size is constant and the target should not emit any calls and is strongly encouraged to attempt to emit inline code even if it is beyond the usual threshold because this intrinsic is being expanded in a place where calls are not feasible (e.g. within the prologue for another call). If the target chooses to decline an AlwaysInline request here, legalize will resort to using simple loads and stores.
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 60 of file SystemZSelectionDAGInfo.cpp.
References DL, emitMemMemImm(), emitMemMemReg(), llvm::SystemZISD::MVC, and Size.
EmitTargetCodeForMemset()
SDValue SystemZSelectionDAGInfo::EmitTargetCodeForMemset (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, Align Alignment, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo) const override virtual
Emit target-specific code that performs a memset.
This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used. Note that if AlwaysInline is true the function has to return a valid SDValue.
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 88 of file SystemZSelectionDAGInfo.cpp.
References llvm::ISD::ADD, assert(), llvm::bit_floor(), DL, emitMemMemImm(), emitMemMemReg(), llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getStore(), llvm::MachinePointerInfo::getWithOffset(), llvm::SystemZISD::MEMSET_MVC, memsetStore(), llvm::popcount(), Size, llvm::ISD::TokenFactor, and llvm::SystemZISD::XC.
EmitTargetCodeForStrcmp()
std::pair< SDValue, SDValue > SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp (SelectionDAG & DAG, const SDLoc & dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const override virtual
Emit target-specific code that performs a strcmp, in cases where that is faster than a libcall.
The first returned SDValue is the result of the strcmp and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 224 of file SystemZSelectionDAGInfo.cpp.
References addIPMSequence(), DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), and llvm::SystemZISD::STRCMP.
EmitTargetCodeForStrcpy()
std::pair< SDValue, SDValue > SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const override virtual
Emit target-specific code that performs a strcpy or stpcpy, in cases where that is faster than a libcall.
The first returned SDValue is the result of the copy (the start of the destination string for strcpy, a pointer to the null terminator for stpcpy) and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 214 of file SystemZSelectionDAGInfo.cpp.
References DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), and llvm::SystemZISD::STPCPY.
EmitTargetCodeForStrlen()
std::pair< SDValue, SDValue > SystemZSelectionDAGInfo::EmitTargetCodeForStrlen (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const override virtual
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 255 of file SystemZSelectionDAGInfo.cpp.
References DL, getBoundedStrlen(), and llvm::SelectionDAG::getConstant().
EmitTargetCodeForStrnlen()
std::pair< SDValue, SDValue > SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen (SelectionDAG & DAG, const SDLoc & DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const override virtual
Reimplemented from llvm::SelectionDAGTargetInfo.
Definition at line 262 of file SystemZSelectionDAGInfo.cpp.
References llvm::ISD::ADD, DL, getBoundedStrlen(), llvm::SelectionDAG::getNode(), and llvm::SelectionDAG::getZExtOrTrunc().
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZSelectionDAGInfo.h
lib/Target/SystemZ/SystemZSelectionDAGInfo.cpp