LLVM: llvm::NumericVariableUse Class Reference
llvm::NumericVariableUse Class Reference
Class representing the use of a numeric variable in the AST of an expression.
#include "FileCheck/FileCheckImpl.h"
Public Member Functions
NumericVariableUse (StringRef Name, NumericVariable *Variable)
Expected< APInt > eval () const override
Expected< ExpressionFormat > getImplicitFormat (const SourceMgr &SM) const override
Public Member Functions inherited from llvm::ExpressionAST
ExpressionAST (StringRef ExpressionStr)
virtual ~ExpressionAST ()=default
StringRef getExpressionStr () const
virtual Expected< APInt > eval () const =0
Evaluates and.
virtual Expected< ExpressionFormat > getImplicitFormat (const SourceMgr &SM) const
Detailed Description
Class representing the use of a numeric variable in the AST of an expression.
Definition at line 280 of file FileCheckImpl.h.
Constructor & Destructor Documentation
NumericVariableUse()
llvm::NumericVariableUse::NumericVariableUse (StringRef Name, NumericVariable * Variable) inline
Definition at line 286 of file FileCheckImpl.h.
Member Function Documentation
eval()
Expected< APInt > NumericVariableUse::eval () const override virtual
Returns
the value of the variable referenced by this instance.
Implements llvm::ExpressionAST.
Definition at line 195 of file FileCheck.cpp.
References llvm::ExpressionAST::getExpressionStr(), and llvm::NumericVariable::getValue().
getImplicitFormat()
Expected< ExpressionFormat > llvm::NumericVariableUse::getImplicitFormat (const SourceMgr & SM) const inline override virtual
Returns
implicit format of this numeric variable.
Reimplemented from llvm::ExpressionAST.
Definition at line 293 of file FileCheckImpl.h.
References llvm::NumericVariable::getImplicitFormat().
The documentation for this class was generated from the following files:
lib/FileCheck/FileCheckImpl.h
lib/FileCheck/FileCheck.cpp