LLVM: llvm::WithCache< Arg > Class Template Reference
llvm::WithCache< Arg > Class Template Reference
#include "llvm/Analysis/WithCache.h"
Public Member Functions
WithCache (PointerType Pointer)
WithCache (PointerType Pointer, const KnownBits &Known)
PointerType getValue () const
const KnownBits & getKnownBits (const SimplifyQuery &Q) const
bool hasKnownBits () const
operator PointerType () const
PointerType operator-> () const
ReferenceType operator* () const
Detailed Description
template<typename Arg>
class llvm::WithCache< Arg >
Definition at line 27 of file WithCache.h.
Constructor & Destructor Documentation
WithCache() [1/2]
template<typename Arg > llvm::WithCache< Arg >::WithCache (PointerType Pointer) inline
Definition at line 52 of file WithCache.h.
WithCache() [2/2]
template<typename Arg > llvm::WithCache< Arg >::WithCache (PointerType Pointer, const KnownBits & Known) inline
Definition at line 53 of file WithCache.h.
Member Function Documentation
getKnownBits()
template<typename Arg > const KnownBits & llvm::WithCache< Arg >::getKnownBits (const SimplifyQuery & Q) const inline
Definition at line 58 of file WithCache.h.
References llvm::WithCache< Arg >::hasKnownBits().
Referenced by llvm::haveNoCommonBitsSet().
getValue()
template<typename Arg > PointerType llvm::WithCache< Arg >::getValue () const inline
Definition at line 56 of file WithCache.h.
Referenced by llvm::haveNoCommonBitsSet().
hasKnownBits()
template<typename Arg > bool llvm::WithCache< Arg >::hasKnownBits () const inline
Definition at line 64 of file WithCache.h.
Referenced by llvm::WithCache< Arg >::getKnownBits().
operator PointerType()
template<typename Arg > llvm::WithCache< Arg >::operator PointerType () const inline
Definition at line 66 of file WithCache.h.
operator*()
template<typename Arg > ReferenceType llvm::WithCache< Arg >::operator* () const inline
Definition at line 68 of file WithCache.h.
operator->()
template<typename Arg > PointerType llvm::WithCache< Arg >::operator-> () const inline
Definition at line 67 of file WithCache.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/WithCache.h