LLVM: llvm::PhiLoweringHelper Class Reference
llvm::PhiLoweringHelper Class Reference abstract
#include "Target/AMDGPU/SILowerI1Copies.h"
Public Member Functions
PhiLoweringHelper (MachineFunction *MF, MachineDominatorTree *DT, MachinePostDominatorTree *PDT)
virtual ~PhiLoweringHelper ()=default
bool lowerPhis ()
bool isConstantLaneMask (Register Reg, bool &Val) const
MachineBasicBlock::iterator getSaluInsertionAtEnd (MachineBasicBlock &MBB) const
Return a point at the end of the given MBB to insert SALU instructions for lane mask calculation.
void initializeLaneMaskRegisterAttributes (Register LaneMask)
bool isLaneMaskReg (Register Reg) const
virtual void markAsLaneMask (Register DstReg) const =0
virtual void getCandidatesForLowering (SmallVectorImpl< MachineInstr * > &Vreg1Phis) const =0
virtual void collectIncomingValuesFromPhi (const MachineInstr *MI, SmallVectorImpl< Incoming > &Incomings) const =0
virtual void replaceDstReg (Register NewReg, Register OldReg, MachineBasicBlock *MBB)=0
virtual void buildMergeLaneMasks (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, const DebugLoc &DL, Register DstReg, Register PrevReg, Register CurReg)=0
virtual void constrainIncomingRegisterTakenAsIs (Incoming &In)=0
Protected Attributes
bool IsWave32 = false
MachineFunction * MF = nullptr
MachineDominatorTree * DT = nullptr
MachinePostDominatorTree * PDT = nullptr
MachineRegisterInfo * MRI = nullptr
const GCNSubtarget * ST = nullptr
const SIInstrInfo * TII = nullptr
Register LaneMaskRegAttrs
DenseSet< Register > PhiRegisters
Register ExecReg
unsigned MovOp
unsigned AndOp
unsigned OrOp
unsigned XorOp
unsigned AndN2Op
unsigned OrN2Op
Detailed Description
Definition at line 36 of file SILowerI1Copies.h.
Constructor & Destructor Documentation
PhiLoweringHelper()
PhiLoweringHelper::PhiLoweringHelper (MachineFunction * MF, MachineDominatorTree * DT, MachinePostDominatorTree * PDT)
Definition at line 508 of file SILowerI1Copies.cpp.
References AndN2Op, AndOp, ExecReg, llvm::GCNSubtarget::getInstrInfo(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::GCNSubtarget::isWave32(), IsWave32, MF, MovOp, MRI, OrN2Op, OrOp, ST, TII, and XorOp.
~PhiLoweringHelper()
virtual llvm::PhiLoweringHelper::~PhiLoweringHelper () virtual default
Member Function Documentation
buildMergeLaneMasks()
virtual void llvm::PhiLoweringHelper::buildMergeLaneMasks (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, const DebugLoc & DL, Register DstReg, Register PrevReg, Register CurReg) pure virtual
Referenced by lowerPhis().
collectIncomingValuesFromPhi()
virtual void llvm::PhiLoweringHelper::collectIncomingValuesFromPhi (const MachineInstr * MI, SmallVectorImpl< Incoming > & Incomings) const pure virtual
Referenced by lowerPhis().
constrainIncomingRegisterTakenAsIs()
virtual void llvm::PhiLoweringHelper::constrainIncomingRegisterTakenAsIs (Incoming & In) pure virtual
Referenced by lowerPhis().
getCandidatesForLowering()
virtual void llvm::PhiLoweringHelper::getCandidatesForLowering (SmallVectorImpl< MachineInstr * > & Vreg1Phis) const pure virtual
Referenced by lowerPhis().
getSaluInsertionAtEnd()
MachineBasicBlock::iterator PhiLoweringHelper::getSaluInsertionAtEnd (MachineBasicBlock & MBB) const
Return a point at the end of the given MBB to insert SALU instructions for lane mask calculation.
Take terminators and SCC into account.
Definition at line 782 of file SILowerI1Copies.cpp.
References llvm::MachineBasicBlock::begin(), E, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getFirstTerminator(), I, instrDefsUsesSCC(), llvm_unreachable, and MBB.
Referenced by lowerPhis().
initializeLaneMaskRegisterAttributes()
void llvm::PhiLoweringHelper::initializeLaneMaskRegisterAttributes (Register LaneMask) inline
Definition at line 70 of file SILowerI1Copies.h.
References LaneMaskRegAttrs.
Referenced by lowerPhis().
isConstantLaneMask()
bool PhiLoweringHelper::isConstantLaneMask (Register Reg, bool & Val) const
Definition at line 729 of file SILowerI1Copies.cpp.
References llvm::MachineRegisterInfo::getUniqueVRegDef(), isLaneMaskReg(), MI, MovOp, and MRI.
isLaneMaskReg()
bool llvm::PhiLoweringHelper::isLaneMaskReg (Register Reg) const inline
Definition at line 74 of file SILowerI1Copies.h.
References llvm::SIInstrInfo::getRegisterInfo(), llvm::AMDGPUSubtarget::getWavefrontSize(), llvm::SIRegisterInfo::isSGPRReg(), MRI, Reg, ST, and TII.
Referenced by isConstantLaneMask().
lowerPhis()
bool PhiLoweringHelper::lowerPhis ()
Definition at line 537 of file SILowerI1Copies.cpp.
References llvm::SSAUpdater::AddAvailableValue(), llvm::Incoming::Block, buildMergeLaneMasks(), llvm::SmallVectorImpl< T >::clear(), collectIncomingValuesFromPhi(), constrainIncomingRegisterTakenAsIs(), llvm::createLaneMaskReg(), llvm::dbgs(), DT, llvm::SmallVectorBase< Size_T >::empty(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), llvm::MachineDominatorTree::getBase(), getCandidatesForLowering(), llvm::DomTreeNodeBase< NodeT >::getDFSNumIn(), llvm::MachineDominatorTree::getNode(), getSaluInsertionAtEnd(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::SSAUpdater::Initialize(), initializeLaneMaskRegisterAttributes(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), insertUndefLaneMask(), llvm::Register::isValid(), LaneMaskRegAttrs, LHS, LLVM_DEBUG, markAsLaneMask(), MBB, MF, MI, MRI, PDT, PhiRegisters, llvm::MachineBasicBlock::push_back(), llvm::Incoming::Reg, replaceDstReg(), RHS, llvm::sort(), TII, llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers(), llvm::Incoming::UpdatedReg, and llvm::MachineRegisterInfo::use_instructions().
markAsLaneMask()
virtual void llvm::PhiLoweringHelper::markAsLaneMask (Register DstReg) const pure virtual
Referenced by lowerPhis().
replaceDstReg()
virtual void llvm::PhiLoweringHelper::replaceDstReg (Register NewReg, Register OldReg, MachineBasicBlock * MBB) pure virtual
Referenced by lowerPhis().
Member Data Documentation
AndN2Op
unsigned llvm::PhiLoweringHelper::AndN2Op protected
Definition at line 61 of file SILowerI1Copies.h.
Referenced by PhiLoweringHelper().
AndOp
unsigned llvm::PhiLoweringHelper::AndOp protected
Definition at line 58 of file SILowerI1Copies.h.
Referenced by PhiLoweringHelper().
DT
MachineDominatorTree* llvm::PhiLoweringHelper::DT = nullptr protected
Definition at line 45 of file SILowerI1Copies.h.
Referenced by lowerPhis().
ExecReg
Register llvm::PhiLoweringHelper::ExecReg protected
Definition at line 56 of file SILowerI1Copies.h.
Referenced by PhiLoweringHelper().
IsWave32
bool llvm::PhiLoweringHelper::IsWave32 = false protected
Definition at line 43 of file SILowerI1Copies.h.
Referenced by PhiLoweringHelper().
LaneMaskRegAttrs
Register llvm::PhiLoweringHelper::LaneMaskRegAttrs protected
Definition at line 50 of file SILowerI1Copies.h.
Referenced by initializeLaneMaskRegisterAttributes(), and lowerPhis().
MF
MachineFunction* llvm::PhiLoweringHelper::MF = nullptr protected
Definition at line 44 of file SILowerI1Copies.h.
Referenced by lowerPhis(), and PhiLoweringHelper().
MovOp
unsigned llvm::PhiLoweringHelper::MovOp protected
Definition at line 57 of file SILowerI1Copies.h.
Referenced by isConstantLaneMask(), and PhiLoweringHelper().
MRI
MachineRegisterInfo* llvm::PhiLoweringHelper::MRI = nullptr protected
Definition at line 47 of file SILowerI1Copies.h.
Referenced by isConstantLaneMask(), isLaneMaskReg(), lowerPhis(), and PhiLoweringHelper().
OrN2Op
unsigned llvm::PhiLoweringHelper::OrN2Op protected
Definition at line 62 of file SILowerI1Copies.h.
Referenced by PhiLoweringHelper().
OrOp
unsigned llvm::PhiLoweringHelper::OrOp protected
Definition at line 59 of file SILowerI1Copies.h.
Referenced by PhiLoweringHelper().
PDT
MachinePostDominatorTree* llvm::PhiLoweringHelper::PDT = nullptr protected
Definition at line 46 of file SILowerI1Copies.h.
Referenced by lowerPhis().
PhiRegisters
DenseSet<Register> llvm::PhiLoweringHelper::PhiRegisters protected
Definition at line 53 of file SILowerI1Copies.h.
Referenced by lowerPhis().
ST
const GCNSubtarget* llvm::PhiLoweringHelper::ST = nullptr protected
Definition at line 48 of file SILowerI1Copies.h.
Referenced by isLaneMaskReg(), and PhiLoweringHelper().
TII
const SIInstrInfo* llvm::PhiLoweringHelper::TII = nullptr protected
Definition at line 49 of file SILowerI1Copies.h.
Referenced by isLaneMaskReg(), lowerPhis(), and PhiLoweringHelper().
XorOp
unsigned llvm::PhiLoweringHelper::XorOp protected
Definition at line 60 of file SILowerI1Copies.h.
Referenced by PhiLoweringHelper().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/SILowerI1Copies.h
lib/Target/AMDGPU/SILowerI1Copies.cpp