LLVM: llvm::TargetExtType Class Reference
llvm::TargetExtType Class Reference
Class to represent target extensions types, which are generally unintrospectable from target-independent optimizations.
#include "llvm/IR/DerivedTypes.h"
Public Types
enum Property { HasZeroInit = 1U << 0 , CanBeGlobal = 1U << 1 }
using type_param_iterator = Type::subtype_iterator
Public Types inherited from llvm::Type
enum TypeID {
HalfTyID = 0 , BFloatTyID , FloatTyID , DoubleTyID ,
X86_FP80TyID , FP128TyID , PPC_FP128TyID , VoidTyID ,
LabelTyID , MetadataTyID , X86_MMXTyID , X86_AMXTyID ,
TokenTyID , IntegerTyID , FunctionTyID , PointerTyID ,
StructTyID , ArrayTyID , FixedVectorTyID , ScalableVectorTyID ,
TypedPointerTyID , TargetExtTyID
}
Definitions of all of the base types for the Type system.
using subtype_iterator = Type *const *
using subtype_reverse_iterator = std::reverse_iterator< subtype_iterator >
Public Member Functions
TargetExtType (const TargetExtType &)=delete
TargetExtType & operator= (const TargetExtType &)=delete
StringRef getName () const
Return the name for this target extension type.
ArrayRef< Type * > type_params () const
Return the type parameters for this particular target extension type.
type_param_iterator type_param_begin () const
type_param_iterator type_param_end () const
Type * getTypeParameter (unsigned i) const
unsigned getNumTypeParameters () const
ArrayRef< unsigned > int_params () const
Return the integer parameters for this particular target extension type.
unsigned getIntParameter (unsigned i) const
unsigned getNumIntParameters () const
bool hasProperty (Property Prop) const
Returns true if the target extension type contains the given property.
Type * getLayoutType () const
Returns an underlying layout type for the target extension type.
Public Member Functions inherited from llvm::Type
void print (raw_ostream &O, bool IsForDebug=false, bool NoDetails=false) const
Print the current type.
void dump () const
LLVMContext & getContext () const
Return the LLVMContext in which this type was uniqued.
TypeID getTypeID () const
Return the type id for the type.
bool isVoidTy () const
Return true if this is 'void'.
bool isHalfTy () const
Return true if this is 'half', a 16-bit IEEE fp type.
bool isBFloatTy () const
Return true if this is 'bfloat', a 16-bit bfloat type.
bool is16bitFPTy () const
Return true if this is a 16-bit float type.
bool isFloatTy () const
Return true if this is 'float', a 32-bit IEEE fp type.
bool isDoubleTy () const
Return true if this is 'double', a 64-bit IEEE fp type.
bool isX86_FP80Ty () const
Return true if this is x86 long double.
bool isFP128Ty () const
Return true if this is 'fp128'.
bool isPPC_FP128Ty () const
Return true if this is powerpc long double.
bool isIEEELikeFPTy () const
Return true if this is a well-behaved IEEE-like type, which has a IEEE compatible layout as defined by APFloat::isIEEE(), and does not have non-IEEE values, such as x86_fp80's unnormal values.
bool isFloatingPointTy () const
Return true if this is one of the floating-point types.
bool isMultiUnitFPType () const
Returns true if this is a floating-point type that is an unevaluated sum of multiple floating-point units.
const fltSemantics & getFltSemantics () const
bool isX86_MMXTy () const
Return true if this is X86 MMX.
bool isX86_AMXTy () const
Return true if this is X86 AMX.
bool isTargetExtTy () const
Return true if this is a target extension type.
bool isScalableTargetExtTy () const
Return true if this is a target extension type with a scalable layout.
bool isScalableTy () const
Return true if this is a type whose size is a known multiple of vscale.
bool isFPOrFPVectorTy () const
Return true if this is a FP type or a vector of FP.
bool isLabelTy () const
Return true if this is 'label'.
bool isMetadataTy () const
Return true if this is 'metadata'.
bool isTokenTy () const
Return true if this is 'token'.
bool isIntegerTy () const
True if this is an instance of IntegerType.
bool isIntegerTy (unsigned Bitwidth) const
Return true if this is an IntegerType of the given width.
bool isIntOrIntVectorTy () const
Return true if this is an integer type or a vector of integer types.
bool isIntOrIntVectorTy (unsigned BitWidth) const
Return true if this is an integer type or a vector of integer types of the given width.
bool isIntOrPtrTy () const
Return true if this is an integer type or a pointer type.
bool isFunctionTy () const
True if this is an instance of FunctionType.
bool isStructTy () const
True if this is an instance of StructType.
bool isArrayTy () const
True if this is an instance of ArrayType.
bool isPointerTy () const
True if this is an instance of PointerType.
bool isOpaquePointerTy () const
True if this is an instance of an opaque PointerType.
bool isPtrOrPtrVectorTy () const
Return true if this is a pointer type or a vector of pointer types.
bool isVectorTy () const
True if this is an instance of VectorType.
bool canLosslesslyBitCastTo (Type *Ty) const
Return true if this type could be converted with a lossless BitCast to type 'Ty'.
bool isEmptyTy () const
Return true if this type is empty, that is, it has no elements or all of its elements are empty.
bool isFirstClassType () const
Return true if the type is "first class", meaning it is a valid type for a Value.
bool isSingleValueType () const
Return true if the type is a valid type for a register in codegen.
bool isAggregateType () const
Return true if the type is an aggregate type.
bool isSized (SmallPtrSetImpl< Type * > *Visited=nullptr) const
Return true if it makes sense to take the size of this type.
TypeSize getPrimitiveSizeInBits () const LLVM_READONLY
Return the basic size of this type if it is a primitive type.
unsigned getScalarSizeInBits () const LLVM_READONLY
If this is a vector type, return the getPrimitiveSizeInBits value for the element type.
int getFPMantissaWidth () const
Return the width of the mantissa of this type.
bool isIEEE () const
Return whether the type is IEEE compatible, as defined by the eponymous method in APFloat.
Type * getScalarType () const
If this is a vector type, return the element type, otherwise return 'this'.
subtype_iterator subtype_begin () const
subtype_iterator subtype_end () const
ArrayRef< Type * > subtypes () const
subtype_reverse_iterator subtype_rbegin () const
subtype_reverse_iterator subtype_rend () const
Type * getContainedType (unsigned i) const
This method is used to implement the type iterator (defined at the end of the file).
unsigned getNumContainedTypes () const
Return the number of types in the derived type.
unsigned getIntegerBitWidth () const
Type * getFunctionParamType (unsigned i) const
unsigned getFunctionNumParams () const
bool isFunctionVarArg () const
StringRef getStructName () const
unsigned getStructNumElements () const
Type * getStructElementType (unsigned N) const
uint64_t getArrayNumElements () const
Type * getArrayElementType () const
StringRef getTargetExtName () const
Type * getNonOpaquePointerElementType () const
Only use this method in code that is not reachable with opaque pointers, or part of deprecated methods that will be removed as part of the opaque pointers transition.
Type * getWithNewType (Type *EltTy) const
Given vector type, change the element type, whilst keeping the old number of elements.
Type * getWithNewBitWidth (unsigned NewBitWidth) const
Given an integer or vector type, change the lane bitwidth to NewBitwidth, whilst keeping the old number of lanes.
Type * getExtendedType () const
Given scalar/vector integer type, returns a type with elements twice as wide as in the original type.
unsigned getPointerAddressSpace () const
Get the address space of this pointer or pointer vector type.
PointerType * getPointerTo (unsigned AddrSpace=0) const
Return a pointer to the current type.
Static Public Member Functions
static TargetExtType * get (LLVMContext &Context, StringRef Name, ArrayRef< Type * > Types=std::nullopt, ArrayRef< unsigned > Ints=std::nullopt)
Return a target extension type having the specified name and optional type and integer parameters.
static bool classof (const Type *T)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Type
static Type * getPrimitiveType (LLVMContext &C, TypeID IDNumber)
Return a type based on an identifier.
static Type * getVoidTy (LLVMContext &C)
static Type * getLabelTy (LLVMContext &C)
static Type * getHalfTy (LLVMContext &C)
static Type * getBFloatTy (LLVMContext &C)
static Type * getFloatTy (LLVMContext &C)
static Type * getDoubleTy (LLVMContext &C)
static Type * getMetadataTy (LLVMContext &C)
static Type * getX86_FP80Ty (LLVMContext &C)
static Type * getFP128Ty (LLVMContext &C)
static Type * getPPC_FP128Ty (LLVMContext &C)
static Type * getX86_MMXTy (LLVMContext &C)
static Type * getX86_AMXTy (LLVMContext &C)
static Type * getTokenTy (LLVMContext &C)
static IntegerType * getIntNTy (LLVMContext &C, unsigned N)
static IntegerType * getInt1Ty (LLVMContext &C)
static IntegerType * getInt8Ty (LLVMContext &C)
static IntegerType * getInt16Ty (LLVMContext &C)
static IntegerType * getInt32Ty (LLVMContext &C)
static IntegerType * getInt64Ty (LLVMContext &C)
static IntegerType * getInt128Ty (LLVMContext &C)
template<typename ScalarTy >
static Type * getScalarTy (LLVMContext &C)
static Type * getFloatingPointTy (LLVMContext &C, const fltSemantics &S)
static Type * getWasm_ExternrefTy (LLVMContext &C)
static Type * getWasm_FuncrefTy (LLVMContext &C)
Additional Inherited Members
Protected Member Functions inherited from llvm::Type
Type (LLVMContext &C, TypeID tid)
~Type ()=default
unsigned getSubclassData () const
void setSubclassData (unsigned val)
Protected Attributes inherited from llvm::Type
unsigned NumContainedTys = 0
Keeps track of how many Type*'s there are in the ContainedTys list.
Type *const * ContainedTys = nullptr
A pointer to the array of Types contained by this Type.
Detailed Description
Class to represent target extensions types, which are generally unintrospectable from target-independent optimizations.
Target extension types have a string name, and optionally have type and/or integer parameters. The exact meaning of any parameters is dependent on the target.
Definition at line 720 of file DerivedTypes.h.
Member Typedef Documentation
type_param_iterator
using llvm::TargetExtType::type_param_iterator = Type::subtype_iterator
Definition at line 749 of file DerivedTypes.h.
Member Enumeration Documentation
Property
enum llvm::TargetExtType::Property
Enumerator
HasZeroInit
zeroinitializer is valid for this target extension type.
CanBeGlobal
This type may be used as the value type of a global variable.
Definition at line 767 of file DerivedTypes.h.
Constructor & Destructor Documentation
TargetExtType()
llvm::TargetExtType::TargetExtType (const TargetExtType &) delete
Member Function Documentation
classof()
static bool llvm::TargetExtType::classof (const Type * T) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 784 of file DerivedTypes.h.
References llvm::Type::TargetExtTyID.
get()
TargetExtType * TargetExtType::get (LLVMContext & Context, StringRef Name, ArrayRef< Type * > Types = std::nullopt, ArrayRef< unsigned > Ints = std::nullopt) static
Return a target extension type having the specified name and optional type and integer parameters.
Definition at line 796 of file Type.cpp.
References llvm::CallingConv::C, and llvm::ArrayRef< T >::size().
Referenced by DecodeFixedType(), llvm::EVT::getTypeForEVT(), LLVMTargetExtTypeInContext(), and llvm::SPIRV::parseBuiltinTypeNameToTargetExtType().
getIntParameter()
unsigned llvm::TargetExtType::getIntParameter (unsigned i) const inline
Definition at line 764 of file DerivedTypes.h.
Referenced by llvm::getImageType(), and llvm::getPipeType().
getLayoutType()
Type * TargetExtType::getLayoutType () const
Returns an underlying layout type for the target extension type.
This type can be used to query size and alignment information, if it is appropriate (although note that the layout type may also be void). It is not legal to bitcast between this type and the layout type, however.
Definition at line 851 of file Type.cpp.
References getTargetTypeInfo().
getName()
StringRef llvm::TargetExtType::getName () const inline
Return the name for this target extension type.
Two distinct target extension types may have the same name if their type or integer parameters differ.
Definition at line 741 of file DerivedTypes.h.
Referenced by getTargetTypeInfo(), and llvm::MVT::getVT().
getNumIntParameters()
unsigned llvm::TargetExtType::getNumIntParameters () const inline
Definition at line 765 of file DerivedTypes.h.
References llvm::Type::getSubclassData().
Referenced by llvm::getImageType(), llvm::getPipeType(), and int_params().
getNumTypeParameters()
unsigned llvm::TargetExtType::getNumTypeParameters () const inline
Definition at line 756 of file DerivedTypes.h.
References llvm::Type::getNumContainedTypes().
Referenced by llvm::getImageType().
getTypeParameter()
Type * llvm::TargetExtType::getTypeParameter (unsigned i) const inline
Definition at line 755 of file DerivedTypes.h.
References llvm::Type::getContainedType().
Referenced by llvm::getImageType().
hasProperty()
bool TargetExtType::hasProperty (Property Prop) const
Returns true if the target extension type contains the given property.
Definition at line 855 of file Type.cpp.
References getTargetTypeInfo().
Referenced by llvm::ConstantTargetNone::get().
int_params()
ArrayRef< unsigned > llvm::TargetExtType::int_params () const inline
Return the integer parameters for this particular target extension type.
If there are no parameters, an empty array is returned.
Definition at line 760 of file DerivedTypes.h.
References getNumIntParameters().
operator=()
TargetExtType & llvm::TargetExtType::operator= (const TargetExtType &) delete
type_param_begin()
type_param_iterator llvm::TargetExtType::type_param_begin () const inline
Definition at line 750 of file DerivedTypes.h.
References llvm::Type::ContainedTys.
Referenced by type_params().
type_param_end()
type_param_iterator llvm::TargetExtType::type_param_end () const inline
Definition at line 751 of file DerivedTypes.h.
References llvm::Type::ContainedTys, and llvm::Type::NumContainedTys.
Referenced by type_params().
type_params()
ArrayRef< Type * > llvm::TargetExtType::type_params () const inline
Return the type parameters for this particular target extension type.
If there are no parameters, an empty array is returned.
Definition at line 745 of file DerivedTypes.h.
References type_param_begin(), and type_param_end().
The documentation for this class was generated from the following files:
include/llvm/IR/DerivedTypes.h
lib/IR/Type.cpp