LLVM: LiveDebugValues::DbgValue Class Reference
LiveDebugValues::DbgValue Class Reference
Class recording the (high level) value of a variable.
#include "CodeGen/LiveDebugValues/InstrRefBasedImpl.h"
Public Types
enum KindT { Undef , Def , VPHI , NoVal }
Public Member Functions
DbgValue (ArrayRef< DbgOpID > DbgOps, const DbgValueProperties &Prop)
DbgValue (unsigned BlockNo, const DbgValueProperties &Prop, KindT Kind)
DbgValue (const DbgValueProperties &Prop, KindT Kind)
void dump (const MLocTracker *MTrack=nullptr, const DbgOpIDMap *OpStore=nullptr) const
bool operator== (const DbgValue &Other) const
bool operator!= (const DbgValue &Other) const
ArrayRef< DbgOpID > getDbgOpIDs () const
DbgOpID getDbgOpID (unsigned Index) const
void setDbgOpIDs (ArrayRef< DbgOpID > NewIDs)
unsigned getLocationOpCount () const
bool hasJoinableLocOps (const DbgValue &Other) const
bool isUnjoinedPHI () const
bool hasIdenticalValidLocOps (const DbgValue &Other) const
Public Attributes
int BlockNo
For a NoVal or VPHI DbgValue, which block it was generated in.
DbgValueProperties Properties
Qualifiers for the ValueIDNum above.
KindT Kind
Discriminator for whether this is a constant or an in-program value.
Detailed Description
Class recording the (high level) value of a variable.
Identifies the value of the variable as a list of ValueIDNums and constant MachineOperands, or as an empty list for undef debug values or VPHI values which we have not found valid locations for. This class also stores meta-information about how the value is qualified. Used to reason about variable values when performing the second (DebugVariable specific) dataflow analysis.
Definition at line 480 of file InstrRefBasedImpl.h.
Member Enumeration Documentation
KindT
enum LiveDebugValues::DbgValue::KindT
Enumerator
Undef
Def
VPHI
NoVal
Definition at line 496 of file InstrRefBasedImpl.h.
Constructor & Destructor Documentation
DbgValue() [1/3]
LiveDebugValues::DbgValue::DbgValue (ArrayRef< DbgOpID > DbgOps, const DbgValueProperties & Prop) inline
Definition at line 508 of file InstrRefBasedImpl.h.
References llvm::any_of(), assert(), llvm::dbgs(), LiveDebugValues::DbgValueProperties::getLocationOpCount(), Idx, Kind, LLVM_DEBUG, MAX_DBG_OPS, llvm::ArrayRef< T >::size(), llvm::size(), and Undef.
DbgValue() [2/3]
LiveDebugValues::DbgValue::DbgValue (unsigned BlockNo, const DbgValueProperties & Prop, KindT Kind) inline
Definition at line 529 of file InstrRefBasedImpl.h.
References assert(), Kind, NoVal, and VPHI.
DbgValue() [3/3]
LiveDebugValues::DbgValue::DbgValue (const DbgValueProperties & Prop, KindT Kind) inline
Definition at line 534 of file InstrRefBasedImpl.h.
References assert(), Kind, and Undef.
Member Function Documentation
dump()
void DbgValue::dump (const MLocTracker * MTrack = nullptr, const DbgOpIDMap * OpStore = nullptr) const
Definition at line 966 of file InstrRefBasedImpl.cpp.
References BlockNo, llvm::dbgs(), Def, LiveDebugValues::DbgValueProperties::DIExpr, LiveDebugValues::DbgOpID::dump(), getDbgOpID(), getDbgOpIDs(), Idx, LiveDebugValues::DbgValueProperties::Indirect, Kind, NoVal, Properties, and VPHI.
getDbgOpID()
DbgOpID LiveDebugValues::DbgValue::getDbgOpID (unsigned Index) const inline
Definition at line 569 of file InstrRefBasedImpl.h.
References assert(), and LiveDebugValues::DbgOpID::UndefID.
Referenced by dump(), and hasJoinableLocOps().
getDbgOpIDs()
ArrayRef< DbgOpID > LiveDebugValues::DbgValue::getDbgOpIDs () const inline
Definition at line 564 of file InstrRefBasedImpl.h.
Referenced by dump(), hasIdenticalValidLocOps(), and operator==().
getLocationOpCount()
unsigned LiveDebugValues::DbgValue::getLocationOpCount () const inline
Definition at line 591 of file InstrRefBasedImpl.h.
References LiveDebugValues::DbgValueProperties::getLocationOpCount(), and Properties.
Referenced by hasJoinableLocOps(), and setDbgOpIDs().
hasIdenticalValidLocOps()
bool LiveDebugValues::DbgValue::hasIdenticalValidLocOps (const DbgValue & Other) const inline
Definition at line 610 of file InstrRefBasedImpl.h.
References llvm::equal(), getDbgOpIDs(), and llvm::Other.
hasJoinableLocOps()
bool LiveDebugValues::DbgValue::hasJoinableLocOps (const DbgValue & Other) const inline
Definition at line 598 of file InstrRefBasedImpl.h.
References getDbgOpID(), getLocationOpCount(), Idx, LiveDebugValues::DbgOpID::isConst(), isUnjoinedPHI(), and llvm::Other.
isUnjoinedPHI()
bool LiveDebugValues::DbgValue::isUnjoinedPHI () const inline
Definition at line 608 of file InstrRefBasedImpl.h.
References Kind, and VPHI.
Referenced by hasJoinableLocOps().
operator!=()
bool LiveDebugValues::DbgValue::operator!= (const DbgValue & Other) const inline
Definition at line 560 of file InstrRefBasedImpl.h.
References llvm::Other.
operator==()
bool LiveDebugValues::DbgValue::operator== (const DbgValue & Other) const inline
Definition at line 545 of file InstrRefBasedImpl.h.
References BlockNo, Def, llvm::equal(), getDbgOpIDs(), Kind, NoVal, llvm::Other, Properties, and VPHI.
setDbgOpIDs()
void LiveDebugValues::DbgValue::setDbgOpIDs (ArrayRef< DbgOpID > NewIDs) inline
Definition at line 579 of file InstrRefBasedImpl.h.
References assert(), getLocationOpCount(), Idx, and llvm::ArrayRef< T >::size().
Member Data Documentation
BlockNo
int LiveDebugValues::DbgValue::BlockNo
For a NoVal or VPHI DbgValue, which block it was generated in.
Definition at line 491 of file InstrRefBasedImpl.h.
Referenced by dump(), and operator==().
Kind
KindT LiveDebugValues::DbgValue::Kind
Discriminator for whether this is a constant or an in-program value.
Definition at line 506 of file InstrRefBasedImpl.h.
Referenced by DbgValue(), dump(), isUnjoinedPHI(), and operator==().
Properties
DbgValueProperties LiveDebugValues::DbgValue::Properties
Qualifiers for the ValueIDNum above.
Definition at line 494 of file InstrRefBasedImpl.h.
Referenced by dump(), getLocationOpCount(), and operator==().
The documentation for this class was generated from the following files:
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.h
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.cpp