LLVM: llvm::symbolize::JSONPrinter Class Reference
llvm::symbolize::JSONPrinter Class Reference
#include "llvm/DebugInfo/Symbolize/DIPrinter.h"
Public Member Functions
JSONPrinter (raw_ostream &OS, PrinterConfig &Config)
void print (const Request &Request, const DILineInfo &Info) override
void print (const Request &Request, const DIInliningInfo &Info) override
void print (const Request &Request, const DIGlobal &Global) override
void print (const Request &Request, const std::vector< DILocal > &Locals) override
void print (const Request &Request, const std::vector< DILineInfo > &Locations) override
bool printError (const Request &Request, const ErrorInfoBase &ErrorInfo) override
void listBegin () override
void listEnd () override
Public Member Functions inherited from llvm::symbolize::DIPrinter
DIPrinter ()=default
virtual ~DIPrinter ()=default
virtual void print (const Request &Request, const DILineInfo &Info)=0
virtual void print (const Request &Request, const DIInliningInfo &Info)=0
virtual void print (const Request &Request, const DIGlobal &Global)=0
virtual void print (const Request &Request, const std::vector< DILocal > &Locals)=0
virtual void print (const Request &Request, const std::vector< DILineInfo > &Locations)=0
virtual bool printError (const Request &Request, const ErrorInfoBase &ErrorInfo)=0
virtual void listBegin ()=0
virtual void listEnd ()=0
Detailed Description
Definition at line 128 of file DIPrinter.h.
Constructor & Destructor Documentation
JSONPrinter()
llvm::symbolize::JSONPrinter::JSONPrinter (raw_ostream & OS, PrinterConfig & Config) inline
Definition at line 141 of file DIPrinter.h.
References Config, and OS.
Member Function Documentation
listBegin()
void llvm::symbolize::JSONPrinter::listBegin () override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 401 of file DIPrinter.cpp.
References assert().
listEnd()
void llvm::symbolize::JSONPrinter::listEnd () override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 406 of file DIPrinter.cpp.
References assert().
print() [1/5]
void llvm::symbolize::JSONPrinter::print (const Request & Request, const DIGlobal & Global) override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 342 of file DIPrinter.cpp.
References llvm::DILineInfo::BadString, llvm::Data, llvm::Global, llvm::symbolize::toHex(), and llvm::symbolize::toJSON().
print() [2/5]
void llvm::symbolize::JSONPrinter::print (const Request & Request, const DIInliningInfo & Info) override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 320 of file DIPrinter.cpp.
References llvm::DILineInfo::FileName, llvm::symbolize::SourceCode::format(), I, Info, llvm::DILineInfo::Line, N, llvm::DILineInfo::Source, llvm::symbolize::PrinterConfig::SourceContextLines, and llvm::symbolize::toJSON().
print() [3/5]
void llvm::symbolize::JSONPrinter::print (const Request & Request, const DILineInfo & Info) override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 314 of file DIPrinter.cpp.
References llvm::DIInliningInfo::addFrame(), Info, and print().
Referenced by print().
print() [4/5]
void llvm::symbolize::JSONPrinter::print (const Request & Request, const std::vector< DILineInfo > & Locations) override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 378 of file DIPrinter.cpp.
References llvm::json::Array::push_back(), and llvm::symbolize::toJSON().
print() [5/5]
void llvm::symbolize::JSONPrinter::print (const Request & Request, const std::vector< DILocal > & Locals) override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 355 of file DIPrinter.cpp.
References llvm::json::Array::push_back(), llvm::symbolize::toHex(), and llvm::symbolize::toJSON().
printError()
bool llvm::symbolize::JSONPrinter::printError (const Request & Request, const ErrorInfoBase & ErrorInfo) override virtual
Implements llvm::symbolize::DIPrinter.
Definition at line 391 of file DIPrinter.cpp.
References llvm::ErrorInfoBase::message(), and llvm::symbolize::toJSON().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/Symbolize/DIPrinter.h
lib/DebugInfo/Symbolize/DIPrinter.cpp