LLVM: llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap Class Reference
llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap Class Reference
This class creates a DwarfStringPoolEntry for the corresponding StringEntry.
#include "DWARFLinker/Parallel/StringEntryToDwarfStringPoolEntryMap.h"
Public Member Functions
StringEntryToDwarfStringPoolEntryMap (LinkingGlobalData &GlobalData)
~StringEntryToDwarfStringPoolEntryMap ()
DwarfStringPoolEntryWithExtString * add (const StringEntry *String)
Create DwarfStringPoolEntry for specified StringEntry if necessary.
DwarfStringPoolEntryWithExtString * getExistingEntry (const StringEntry *String) const
Returns already existed DwarfStringPoolEntry for the specified StringEntry.
void clear ()
Erase contents of StringsForEmission.
Protected Types
using DwarfStringPoolEntriesTy = DenseMap< const StringEntry *, DwarfStringPoolEntryWithExtString * >
Protected Attributes
DwarfStringPoolEntriesTy DwarfStringPoolEntries
LinkingGlobalData & GlobalData
Detailed Description
This class creates a DwarfStringPoolEntry for the corresponding StringEntry.
Definition at line 21 of file StringEntryToDwarfStringPoolEntryMap.h.
Member Typedef Documentation
DwarfStringPoolEntriesTy
using llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::DwarfStringPoolEntriesTy = DenseMap<const StringEntry *, DwarfStringPoolEntryWithExtString *> protected
Definition at line 63 of file StringEntryToDwarfStringPoolEntryMap.h.
Constructor & Destructor Documentation
StringEntryToDwarfStringPoolEntryMap()
llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::StringEntryToDwarfStringPoolEntryMap (LinkingGlobalData & GlobalData) inline
Definition at line 23 of file StringEntryToDwarfStringPoolEntryMap.h.
~StringEntryToDwarfStringPoolEntryMap()
llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::~StringEntryToDwarfStringPoolEntryMap () inline
Definition at line 25 of file StringEntryToDwarfStringPoolEntryMap.h.
Member Function Documentation
add()
DwarfStringPoolEntryWithExtString * llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::add (const StringEntry * String) inline
Create DwarfStringPoolEntry for specified StringEntry if necessary.
Initialize DwarfStringPoolEntry with initial values.
Definition at line 29 of file StringEntryToDwarfStringPoolEntryMap.h.
References assert(), DwarfStringPoolEntries, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::dwarf_linker::parallel::LinkingGlobalData::getAllocator(), GlobalData, llvm::DwarfStringPoolEntry::Index, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::DwarfStringPoolEntry::NotIndexed, llvm::DwarfStringPoolEntry::Offset, llvm::DwarfStringPoolEntryWithExtString::String, llvm::String, llvm::DwarfStringPoolEntry::Symbol, and llvm::dwarf_linker::parallel::LinkingGlobalData::translateString().
Referenced by llvm::dwarf_linker::parallel::DWARFLinkerImpl::assignOffsetsToStrings().
clear()
void llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::clear () inline
Erase contents of StringsForEmission.
Definition at line 60 of file StringEntryToDwarfStringPoolEntryMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), and DwarfStringPoolEntries.
Referenced by llvm::dwarf_linker::parallel::DWARFLinkerImpl::cleanupDataAfterDWARFOutputIsWritten().
getExistingEntry()
DwarfStringPoolEntryWithExtString * llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::getExistingEntry (const StringEntry * String) const inline
Returns already existed DwarfStringPoolEntry for the specified StringEntry.
Definition at line 50 of file StringEntryToDwarfStringPoolEntryMap.h.
References assert(), DwarfStringPoolEntries, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and llvm::String.
Referenced by llvm::dwarf_linker::parallel::OutputSections::applyPatches(), and llvm::dwarf_linker::parallel::DWARFLinkerImpl::emitStringSections().
Member Data Documentation
DwarfStringPoolEntries
DwarfStringPoolEntriesTy llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::DwarfStringPoolEntries protected
Definition at line 65 of file StringEntryToDwarfStringPoolEntryMap.h.
Referenced by add(), clear(), and getExistingEntry().
GlobalData
LinkingGlobalData& llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::GlobalData protected
Definition at line 67 of file StringEntryToDwarfStringPoolEntryMap.h.
Referenced by add().
The documentation for this class was generated from the following file:
lib/DWARFLinker/Parallel/StringEntryToDwarfStringPoolEntryMap.h