LLVM: llvm::object::GOFFObjectFile Class Reference
llvm::object::GOFFObjectFile Class Reference
#include "llvm/Object/GOFFObjectFile.h"
Public Member Functions
Expected< StringRef > getSymbolName (SymbolRef Symbol) const
GOFFObjectFile (MemoryBufferRef Object, Error &Err)
section_iterator section_begin () const override
section_iterator section_end () const override
uint8_t getBytesInAddress () const override
The number of bytes used to represent an address in this object file format.
StringRef getFileFormatName () const override
Triple::ArchType getArch () const override
Expected< SubtargetFeatures > getFeatures () const override
bool isRelocatableObject () const override
True if this is a relocatable object (.o/.obj).
void moveSymbolNext (DataRefImpl &Symb) const override
basic_symbol_iterator symbol_begin () const override
basic_symbol_iterator symbol_end () const override
bool is64Bit () const override
Public Member Functions inherited from llvm::object::ObjectFile
ObjectFile ()=delete
ObjectFile (const ObjectFile &other)=delete
uint64_t getCommonSymbolSize (DataRefImpl Symb) const
virtual std::vector< SectionRef > dynamic_relocation_sections () const
symbol_iterator_range symbols () const
virtual section_iterator section_begin () const =0
virtual section_iterator section_end () const =0
section_iterator_range sections () const
virtual bool hasDebugInfo () const
virtual uint8_t getBytesInAddress () const =0
The number of bytes used to represent an address in this object file format.
virtual StringRef getFileFormatName () const =0
virtual Triple::ArchType getArch () const =0
virtual Triple::OSType getOS () const
virtual Expected< SubtargetFeatures > getFeatures () const =0
virtual std::optional< StringRef > tryGetCPUName () const
virtual void setARMSubArch (Triple &TheTriple) const
virtual Expected< uint64_t > getStartAddress () const
Triple makeTriple () const
Create a triple from the data in this object file.
virtual StringRef mapDebugSectionName (StringRef Name) const
Maps a debug section name to a standard DWARF section name.
virtual bool isRelocatableObject () const =0
True if this is a relocatable object (.o/.obj).
bool isReflectionSectionStrippable (llvm::binaryformat::Swift5ReflectionSectionKind ReflectionSectionKind) const
True if the reflection section can be stripped by the linker.
Public Member Functions inherited from llvm::object::SymbolicFile
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
~SymbolicFile () override
virtual void moveSymbolNext (DataRefImpl &Symb) const =0
virtual Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const =0
virtual Expected< uint32_t > getSymbolFlags (DataRefImpl Symb) const =0
virtual basic_symbol_iterator symbol_begin () const =0
virtual basic_symbol_iterator symbol_end () const =0
virtual bool is64Bit () const =0
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
virtual Error initContent ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isTapiUniversal () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isOffloadFile () const
bool isCOFFImportFile () const
bool isIR () const
bool isGOFF () const
bool isMinidump () const
bool isTapiFile () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static bool classof (const Binary *V)
Static Public Member Functions inherited from llvm::object::ObjectFile
static Expected< OwningBinary< ObjectFile > > createObjectFile (StringRef ObjectPath)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object, llvm::file_magic Type, bool InitContent=true)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static Expected< std::unique_ptr< COFFObjectFile > > createCOFFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< ObjectFile > > createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType)
static Expected< std::unique_ptr< ObjectFile > > createELFObjectFile (MemoryBufferRef Object, bool InitContent=true)
static Expected< std::unique_ptr< MachOObjectFile > > createMachOObjectFile (MemoryBufferRef Object, uint32_t UniversalCputype=0, uint32_t UniversalIndex=0, size_t MachOFilesetEntryOffset=0)
Create a MachOObjectFile instance from a given buffer.
static Expected< std::unique_ptr< ObjectFile > > createGOFFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< WasmObjectFile > > createWasmObjectFile (MemoryBufferRef Object)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, llvm::file_magic Type, LLVMContext *Context, bool InitContent=true)
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static bool isSymbolicFile (file_magic Type, const LLVMContext *Context)
Static Public Member Functions inherited from llvm::object::Binary
static Error checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Additional Inherited Members
Public Types inherited from llvm::object::ObjectFile
using symbol_iterator_range = iterator_range< symbol_iterator >
using section_iterator_range = iterator_range< section_iterator >
Public Types inherited from llvm::object::SymbolicFile
using basic_symbol_iterator_range = iterator_range< basic_symbol_iterator >
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_COFFImportFile , ID_IR ,
ID_TapiUniversal , ID_TapiFile , ID_Minidump , ID_WinRes ,
ID_Offload , ID_StartObjects , ID_COFF , ID_XCOFF32 ,
ID_XCOFF64 , ID_ELF32L , ID_ELF32B , ID_ELF64L ,
ID_ELF64B , ID_MachO32L , ID_MachO32B , ID_MachO64L ,
ID_MachO64B , ID_GOFF , ID_Wasm , ID_EndObjects
}
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBufferRef Source)
const uint8_t * base () const
virtual Expected< StringRef > getSymbolName (DataRefImpl Symb) const =0
Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
virtual Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const =0
virtual uint64_t getSymbolValueImpl (DataRefImpl Symb) const =0
virtual uint32_t getSymbolAlignment (DataRefImpl Symb) const
virtual uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const =0
virtual Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const =0
virtual Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const =0
virtual void moveSectionNext (DataRefImpl &Sec) const =0
virtual Expected< StringRef > getSectionName (DataRefImpl Sec) const =0
virtual uint64_t getSectionAddress (DataRefImpl Sec) const =0
virtual uint64_t getSectionIndex (DataRefImpl Sec) const =0
virtual uint64_t getSectionSize (DataRefImpl Sec) const =0
virtual Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const =0
virtual uint64_t getSectionAlignment (DataRefImpl Sec) const =0
virtual bool isSectionCompressed (DataRefImpl Sec) const =0
virtual bool isSectionText (DataRefImpl Sec) const =0
virtual bool isSectionData (DataRefImpl Sec) const =0
virtual bool isSectionBSS (DataRefImpl Sec) const =0
virtual bool isSectionVirtual (DataRefImpl Sec) const =0
virtual bool isSectionBitcode (DataRefImpl Sec) const
virtual bool isSectionStripped (DataRefImpl Sec) const
virtual bool isBerkeleyText (DataRefImpl Sec) const
virtual bool isBerkeleyData (DataRefImpl Sec) const
virtual bool isDebugSection (DataRefImpl Sec) const
virtual relocation_iterator section_rel_begin (DataRefImpl Sec) const =0
virtual relocation_iterator section_rel_end (DataRefImpl Sec) const =0
virtual Expected< section_iterator > getRelocatedSection (DataRefImpl Sec) const
virtual void moveRelocationNext (DataRefImpl &Rel) const =0
virtual uint64_t getRelocationOffset (DataRefImpl Rel) const =0
virtual symbol_iterator getRelocationSymbol (DataRefImpl Rel) const =0
virtual uint64_t getRelocationType (DataRefImpl Rel) const =0
virtual void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const =0
virtual llvm::binaryformat::Swift5ReflectionSectionKind mapReflectionSectionNameToEnumValue (StringRef SectionName) const
Expected< uint64_t > getSymbolValue (DataRefImpl Symb) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Detailed Description
Definition at line 31 of file GOFFObjectFile.h.
Constructor & Destructor Documentation
GOFFObjectFile()
GOFFObjectFile::GOFFObjectFile (MemoryBufferRef Object, Error & Err)
Definition at line 36 of file GOFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::createStringError(), llvm::object::Binary::Data, llvm::dbgs(), End, llvm::GOFF::ESD_ST_ElementDefinition, llvm::GOFF::ESD_ST_LabelDefinition, llvm::GOFF::ESD_ST_PartReference, llvm::format(), llvm::MemoryBufferRef::getBufferEnd(), llvm::object::ESDRecord::getEsdId(), llvm::object::ESDRecord::getLength(), llvm::object::ESDRecord::getParentEsdId(), llvm::object::ESDRecord::getSymbolType(), llvm::IndexedMap< T, ToIndexT >::grow(), I, llvm::Length, LLVM_DEBUG, llvm_unreachable, P, llvm::object::parse_failed, llvm::GOFF::RecordLength, llvm::GOFF::RT_END, llvm::GOFF::RT_ESD, llvm::GOFF::RT_HDR, and llvm::object::unexpected_eof.
Member Function Documentation
classof()
static bool llvm::object::GOFFObjectFile::classof (const Binary * V) inline static
Definition at line 47 of file GOFFObjectFile.h.
getArch()
Triple::ArchType llvm::object::GOFFObjectFile::getArch () const inline override virtual
Implements llvm::object::ObjectFile.
Definition at line 55 of file GOFFObjectFile.h.
References llvm::Triple::systemz.
getBytesInAddress()
uint8_t llvm::object::GOFFObjectFile::getBytesInAddress () const inline override virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 51 of file GOFFObjectFile.h.
getFeatures()
Expected< SubtargetFeatures > llvm::object::GOFFObjectFile::getFeatures () const inline override virtual
Implements llvm::object::ObjectFile.
Definition at line 57 of file GOFFObjectFile.h.
getFileFormatName()
StringRef llvm::object::GOFFObjectFile::getFileFormatName () const inline override virtual
Implements llvm::object::ObjectFile.
Definition at line 53 of file GOFFObjectFile.h.
getSymbolName()
Expected< StringRef > GOFFObjectFile::getSymbolName (SymbolRef Symbol) const
Definition at line 211 of file GOFFObjectFile.cpp.
References getSymbolName().
Referenced by getSymbolName().
is64Bit()
bool llvm::object::GOFFObjectFile::is64Bit () const inline override virtual
Implements llvm::object::SymbolicFile.
Definition at line 65 of file GOFFObjectFile.h.
isRelocatableObject()
bool llvm::object::GOFFObjectFile::isRelocatableObject () const inline override virtual
True if this is a relocatable object (.o/.obj).
Implements llvm::object::ObjectFile.
Definition at line 59 of file GOFFObjectFile.h.
moveSymbolNext()
void GOFFObjectFile::moveSymbolNext (DataRefImpl & Symb) const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 408 of file GOFFObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, E, llvm::GOFF::ESD_ST_ElementDefinition, llvm::GOFF::ESD_ST_SectionDefinition, llvm::object::ESDRecord::getSymbolType(), I, and llvm::IndexedMap< T, ToIndexT >::size().
Referenced by symbol_begin().
section_begin()
section_iterator GOFFObjectFile::section_begin () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 397 of file GOFFObjectFile.cpp.
References llvm::object::ObjectFile::SectionRef.
section_end()
section_iterator GOFFObjectFile::section_end () const override virtual
Implements llvm::object::ObjectFile.
Definition at line 403 of file GOFFObjectFile.cpp.
References llvm::object::ObjectFile::SectionRef.
symbol_begin()
basic_symbol_iterator GOFFObjectFile::symbol_begin () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 428 of file GOFFObjectFile.cpp.
References moveSymbolNext(), and llvm::object::ObjectFile::SymbolRef.
symbol_end()
basic_symbol_iterator GOFFObjectFile::symbol_end () const override virtual
Implements llvm::object::SymbolicFile.
Definition at line 434 of file GOFFObjectFile.cpp.
References llvm::object::ObjectFile::SymbolRef.
The documentation for this class was generated from the following files:
include/llvm/Object/GOFFObjectFile.h
lib/Object/GOFFObjectFile.cpp