LLVM: llvm::JMCInstrumenterPass Class Reference
llvm::JMCInstrumenterPass Class Reference
#include "llvm/CodeGen/JMCInstrumenter.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &MAM)
Public Member Functions inherited from llvm::PassInfoMixin< JMCInstrumenterPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< JMCInstrumenterPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 16 of file JMCInstrumenter.h.
Member Function Documentation
run()
PreservedAnalyses JMCInstrumenterPass::run (Module & M, ModuleAnalysisManager & MAM)
Definition at line 57 of file JMCInstrumenter.cpp.
References llvm::PreservedAnalyses::all(), llvm::PreservedAnalyses::none(), and runImpl().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/JMCInstrumenter.h
lib/CodeGen/JMCInstrumenter.cpp