LLVM: llvm::SpecialCaseList::Matcher Class Reference
llvm::SpecialCaseList::Matcher Class Reference
Represents a set of globs and their line numbers.
#include "llvm/Support/SpecialCaseList.h"
Public Member Functions
Error insert (StringRef Pattern, unsigned LineNumber, bool UseRegex)
unsigned match (StringRef Query) const
Detailed Description
Represents a set of globs and their line numbers.
Definition at line 118 of file SpecialCaseList.h.
Member Function Documentation
insert()
Error llvm::SpecialCaseList::Matcher::insert (StringRef Pattern, unsigned LineNumber, bool UseRegex)
Definition at line 27 of file SpecialCaseList.cpp.
References llvm::GlobPattern::create(), llvm::createStringError(), llvm::invalid_argument, llvm::Regex::isValid(), and llvm::Error::success().
match()
unsigned llvm::SpecialCaseList::Matcher::match (StringRef Query) const
Definition at line 70 of file SpecialCaseList.cpp.
References llvm::Regex::match().
The documentation for this class was generated from the following files:
include/llvm/Support/SpecialCaseList.h
lib/Support/SpecialCaseList.cpp