LLVM: llvm::jitlink::ppc64::TOCTableManager< Endianness > Class Template Reference
llvm::jitlink::ppc64::TOCTableManager< Endianness > Class Template Reference
#include "llvm/ExecutionEngine/JITLink/ppc64.h"
Public Member Functions
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Symbol & createEntry (LinkGraph &G, Symbol &Target)
Public Member Functions inherited from llvm::jitlink::TableManager< TOCTableManager< Endianness > >
Symbol & getEntryForTarget (LinkGraph &G, Symbol &Target)
Return the constructed entry.
bool registerPreExistingEntry (Symbol &Target, Symbol &Entry)
Register a pre-existing entry.
Static Public Member Functions
static StringRef getSectionName ()
Detailed Description
template<llvm::endianness Endianness>
class llvm::jitlink::ppc64::TOCTableManager< Endianness >
Definition at line 158 of file ppc64.h.
Member Function Documentation
createEntry()
template<llvm::endianness Endianness> Symbol & llvm::jitlink::ppc64::TOCTableManager< Endianness >::createEntry (LinkGraph & G, Symbol & Target) inline
Definition at line 184 of file ppc64.h.
References llvm::jitlink::ppc64::createAnonymousPointer(), and G.
Referenced by llvm::jitlink::ppc64::TOCTableManager< Endianness >::visitEdge().
getSectionName()
template<llvm::endianness Endianness> static StringRef llvm::jitlink::ppc64::TOCTableManager< Endianness >::getSectionName () inline static
Definition at line 161 of file ppc64.h.
visitEdge()
template<llvm::endianness Endianness> bool llvm::jitlink::ppc64::TOCTableManager< Endianness >::visitEdge (LinkGraph & G, Block * B, Edge & E) inline
Definition at line 163 of file ppc64.h.
References llvm::jitlink::ppc64::CallBranchDeltaRestoreTOC, llvm::jitlink::ppc64::TOCTableManager< Endianness >::createEntry(), llvm::jitlink::ppc64::Delta34, E, G, llvm::jitlink::ppc64::RequestCall, llvm::jitlink::ppc64::RequestGOTAndTransformToDelta34, llvm::jitlink::ppc64::TOCDelta16DS, llvm::jitlink::ppc64::TOCDelta16HA, llvm::jitlink::ppc64::TOCDelta16LO, and llvm::jitlink::ppc64::TOCDelta16LODS.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/JITLink/ppc64.h