LLVM: llvm::CallGraphDOTInfo Class Reference
llvm::CallGraphDOTInfo Class Reference
Public Member Functions
CallGraphDOTInfo (Module *M, CallGraph *CG, function_ref< BlockFrequencyInfo *(Function &)> LookupBFI)
Module * getModule () const
CallGraph * getCallGraph () const
uint64_t getFreq (const Function *F)
uint64_t getMaxFreq ()
Public Attributes
std::function< BlockFrequencyInfo *(Function &)> LookupBFI
Detailed Description
Definition at line 55 of file CallPrinter.cpp.
Constructor & Destructor Documentation
CallGraphDOTInfo()
llvm::CallGraphDOTInfo::CallGraphDOTInfo (Module * M, CallGraph * CG, function_ref< BlockFrequencyInfo *(Function &)> LookupBFI) inline
Definition at line 65 of file CallPrinter.cpp.
References CallMultiGraph, F, getFunction(), llvm::getNumOfCalls(), and llvm::SmallSet< T, N, C >::insert().
Member Function Documentation
getCallGraph()
CallGraph * llvm::CallGraphDOTInfo::getCallGraph () const inline
Definition at line 88 of file CallPrinter.cpp.
Referenced by llvm::GraphTraits< CallGraphDOTInfo * >::getEntryNode(), llvm::DOTGraphTraits< CallGraphDOTInfo * >::getNodeLabel(), llvm::GraphTraits< CallGraphDOTInfo * >::nodes_begin(), and llvm::GraphTraits< CallGraphDOTInfo * >::nodes_end().
getFreq()
uint64_t llvm::CallGraphDOTInfo::getFreq (const Function * F) inline
Definition at line 90 of file CallPrinter.cpp.
References F.
Referenced by llvm::DOTGraphTraits< CallGraphDOTInfo * >::getNodeAttributes().
getMaxFreq()
uint64_t llvm::CallGraphDOTInfo::getMaxFreq () inline
Definition at line 92 of file CallPrinter.cpp.
Referenced by llvm::DOTGraphTraits< CallGraphDOTInfo * >::getEdgeAttributes(), and llvm::DOTGraphTraits< CallGraphDOTInfo * >::getNodeAttributes().
getModule()
Module * llvm::CallGraphDOTInfo::getModule () const inline
Definition at line 86 of file CallPrinter.cpp.
Referenced by llvm::DOTGraphTraits< CallGraphDOTInfo * >::getGraphName().
Member Data Documentation
LookupBFI
std::function<BlockFrequencyInfo *(Function &)> llvm::CallGraphDOTInfo::LookupBFI
Definition at line 63 of file CallPrinter.cpp.
The documentation for this class was generated from the following file:
lib/Analysis/CallPrinter.cpp