LLVM: llvm::object::Slice Class Reference
llvm::object::Slice Class Reference
#include "llvm/Object/MachOUniversalWriter.h"
Public Member Functions
Slice (const MachOObjectFile &O)
Slice (const MachOObjectFile &O, uint32_t Align)
Slice (const Archive &A, uint32_t CPUType, uint32_t CPUSubType, std::string ArchName, uint32_t Align)
This constructor takes pre-specified.
void setP2Alignment (uint32_t Align)
const Binary * getBinary () const
uint32_t getCPUType () const
uint32_t getCPUSubType () const
uint32_t getP2Alignment () const
uint64_t getCPUID () const
std::string getArchString () const
Static Public Member Functions
static Expected< Slice > create (const Archive &A, LLVMContext *LLVMCtx=nullptr)
static Expected< Slice > create (const IRObjectFile &IRO, uint32_t Align)
Friends
bool operator< (const Slice &Lhs, const Slice &Rhs)
Detailed Description
Definition at line 34 of file MachOUniversalWriter.h.
Constructor & Destructor Documentation
Slice() [1/3]
Slice::Slice (const MachOObjectFile & O) explicit
Definition at line 101 of file MachOUniversalWriter.cpp.
Slice() [2/3]
Slice::Slice (const MachOObjectFile & O, uint32_t Align)
Definition at line 90 of file MachOUniversalWriter.cpp.
References string.
Slice() [3/3]
Slice::Slice (const Archive & A, uint32_t CPUType, uint32_t CPUSubType, std::string ArchName, uint32_t Align)
This constructor takes pre-specified.
Parameters
CPUType
param CPUSubType ,
Parameters
ArchName
param Align instead of inferring them from the archive members.
Definition at line 85 of file MachOUniversalWriter.cpp.
Member Function Documentation
create() [1/2]
Expected< Slice > Slice::create (const Archive & A, LLVMContext * LLVMCtx = nullptr) static
Definition at line 124 of file MachOUniversalWriter.cpp.
References A, llvm::Bin, create(), llvm::createFileError(), llvm::createStringError(), llvm::Expected< T >::get(), getMachoCPUFromObjectFile(), getMachoCPUFromTriple(), llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by create().
create() [2/2]
Expected< Slice > Slice::create (const IRObjectFile & IRO, uint32_t Align) static
Definition at line 226 of file MachOUniversalWriter.cpp.
References llvm::Expected< T >::get(), llvm::object::MachOObjectFile::getArchTriple(), getMachoCPUFromTriple(), llvm::object::IRObjectFile::getTargetTriple(), and llvm::Expected< T >::takeError().
getArchString()
std::string llvm::object::Slice::getArchString () const inline
Definition at line 78 of file MachOUniversalWriter.h.
References llvm::MachO::CPU_SUBTYPE_MASK.
getBinary()
const Binary * llvm::object::Slice::getBinary () const inline
Definition at line 66 of file MachOUniversalWriter.h.
Referenced by llvm::object::writeUniversalBinary().
getCPUID()
uint64_t llvm::object::Slice::getCPUID () const inline
Definition at line 74 of file MachOUniversalWriter.h.
getCPUSubType()
uint32_t llvm::object::Slice::getCPUSubType () const inline
Definition at line 70 of file MachOUniversalWriter.h.
getCPUType()
uint32_t llvm::object::Slice::getCPUType () const inline
Definition at line 68 of file MachOUniversalWriter.h.
getP2Alignment()
uint32_t llvm::object::Slice::getP2Alignment () const inline
Definition at line 72 of file MachOUniversalWriter.h.
setP2Alignment()
void llvm::object::Slice::setP2Alignment (uint32_t Align) inline
Definition at line 64 of file MachOUniversalWriter.h.
Friends And Related Function Documentation
operator<
bool operator< (const Slice & Lhs, const Slice & Rhs) friend
Definition at line 86 of file MachOUniversalWriter.h.
The documentation for this class was generated from the following files:
include/llvm/Object/MachOUniversalWriter.h
lib/Object/MachOUniversalWriter.cpp