LLVM: llvm::orc::JITDylib Class Reference
llvm::orc::JITDylib Class Reference
Represents a JIT'd dynamic library.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
JITDylib (const JITDylib &)=delete
JITDylib & operator= (const JITDylib &)=delete
JITDylib (JITDylib &&)=delete
JITDylib & operator= (JITDylib &&)=delete
~JITDylib ()
ExecutionSession & getExecutionSession () const
Get a reference to the ExecutionSession for this JITDylib.
void dump (raw_ostream &OS)
Dump current JITDylib state to OS.
Error clear ()
Calls remove on all trackers currently associated with this JITDylib.
ResourceTrackerSP getDefaultResourceTracker ()
Get the default resource tracker for this JITDylib.
ResourceTrackerSP createResourceTracker ()
Create a resource tracker for this JITDylib.
template<typename GeneratorT >
GeneratorT & addGenerator (std::unique_ptr< GeneratorT > DefGenerator)
Adds a definition generator to this JITDylib and returns a referenece to it.
void removeGenerator (DefinitionGenerator &G)
Remove a definition generator from this JITDylib.
void setLinkOrder (JITDylibSearchOrder NewSearchOrder, bool LinkAgainstThisJITDylibFirst=true)
Set the link order to be used when fixing up definitions in JITDylib.
void addToLinkOrder (const JITDylibSearchOrder &NewLinks)
Append the given JITDylibSearchOrder to the link order for this JITDylib (discarding any elements already present in this JITDylib's link order).
void addToLinkOrder (JITDylib &JD, JITDylibLookupFlags JDLookupFlags=JITDylibLookupFlags::MatchExportedSymbolsOnly)
Add the given JITDylib to the link order for definitions in this JITDylib.
void replaceInLinkOrder (JITDylib &OldJD, JITDylib &NewJD, JITDylibLookupFlags JDLookupFlags=JITDylibLookupFlags::MatchExportedSymbolsOnly)
Replace OldJD with NewJD in the link order if OldJD is present.
void removeFromLinkOrder (JITDylib &JD)
Remove the given JITDylib from the link order for this JITDylib if it is present.
template<typename Func >
auto withLinkOrderDo (Func &&F) -> decltype(F(std::declval< const JITDylibSearchOrder & >()))
Do something with the link order (run under the session lock).
template<typename MaterializationUnitType >
Error define (std::unique_ptr< MaterializationUnitType > &&MU, ResourceTrackerSP RT=nullptr)
Define all symbols provided by the materialization unit to be part of this JITDylib.
template<typename MaterializationUnitType >
Error define (std::unique_ptr< MaterializationUnitType > &MU, ResourceTrackerSP RT=nullptr)
Define all symbols provided by the materialization unit to be part of this JITDylib.
Error remove (const SymbolNameSet &Names)
Tries to remove the given symbols.
Expected< std::vector< JITDylibSP > > getDFSLinkOrder ()
Return this JITDylib and its transitive dependencies in DFS order based on linkage relationships.
Expected< std::vector< JITDylibSP > > getReverseDFSLinkOrder ()
Rteurn this JITDylib and its transitive dependencies in reverse DFS order based on linkage relationships.
Public Member Functions inherited from llvm::ThreadSafeRefCountedBase< JITDylib >
unsigned UseCount () const
void Retain () const
void Release () const
Public Member Functions inherited from llvm::jitlink::JITLinkDylib
JITLinkDylib (std::string Name)
const std::string & getName () const
Get the name for this JITLinkDylib.
Static Public Member Functions
static Expected< std::vector< JITDylibSP > > getDFSLinkOrder (ArrayRef< JITDylibSP > JDs)
Returns the given JITDylibs and all of their transitive dependencies in DFS order (based on linkage relationships).
static Expected< std::vector< JITDylibSP > > getReverseDFSLinkOrder (ArrayRef< JITDylibSP > JDs)
Returns the given JITDylibs and all of their transitive dependencies in reverse DFS order (based on linkage relationships).
Friends
class AsynchronousSymbolQuery
class ExecutionSession
class Platform
class MaterializationResponsibility
Additional Inherited Members
Protected Member Functions inherited from llvm::ThreadSafeRefCountedBase< JITDylib >
ThreadSafeRefCountedBase ()=default
ThreadSafeRefCountedBase (const ThreadSafeRefCountedBase &)
ThreadSafeRefCountedBase & operator= (const ThreadSafeRefCountedBase &)=delete
~ThreadSafeRefCountedBase ()
Detailed Description
Represents a JIT'd dynamic library.
This class aims to mimic the behavior of a regular dylib or shared object, but without requiring the contained program representations to be compiled up-front. The JITDylib's content is defined by adding MaterializationUnits, and contained MaterializationUnits will typically rely on the JITDylib's links-against order to resolve external references (similar to a regular dylib).
The JITDylib object is a thin wrapper that references state held by the ExecutionSession. JITDylibs can be removed, clearing this underlying state and leaving the JITDylib object in a defunct state. In this state the JITDylib's name is guaranteed to remain accessible. If the ExecutionSession is still alive then other operations are callable but will return an Error or null result (depending on the API). It is illegal to call any operation other than getName on a JITDylib after the ExecutionSession has been torn down.
JITDylibs cannot be moved or copied. Their address is stable, and useful as a key in some JIT data structures.
Definition at line 957 of file Core.h.
Constructor & Destructor Documentation
JITDylib() [1/2]
llvm::orc::JITDylib::JITDylib (const JITDylib &) delete
JITDylib() [2/2]
llvm::orc::JITDylib::JITDylib (JITDylib &&) delete
~JITDylib()
llvm::orc::JITDylib::~JITDylib ()
Definition at line 655 of file Core.cpp.
References llvm::dbgs(), llvm::jitlink::JITLinkDylib::getName(), and LLVM_DEBUG.
Member Function Documentation
addGenerator()
template<typename GeneratorT > GeneratorT & llvm::orc::JITDylib::addGenerator (std::unique_ptr< GeneratorT > DefGenerator)
Adds a definition generator to this JITDylib and returns a referenece to it.
When JITDylibs are searched during lookup, if no existing definition of a symbol is found, then any generators that have been added are run (in the order that they were added) to potentially generate a definition.
It is illegal to call this method on a defunct JITDylib and the client is responsible for ensuring that they do not do so.
Definition at line 1826 of file Core.h.
References assert(), G, and llvm::orc::ExecutionSession::runSessionLocked().
Referenced by llvm::orc::LLJIT::linkStaticLibraryInto(), llvm::orc::LLJIT::loadPlatformDynamicLibrary(), llvm::orc::LLJITBuilderState::prepareForConstruction(), and llvm::orc::COFFPlatform::setupJITDylib().
addToLinkOrder() [1/2]
void llvm::orc::JITDylib::addToLinkOrder (const JITDylibSearchOrder & NewLinks)
Append the given JITDylibSearchOrder to the link order for this JITDylib (discarding any elements already present in this JITDylib's link order).
Definition at line 1352 of file Core.cpp.
References llvm::is_contained(), and llvm::orc::ExecutionSession::runSessionLocked().
Referenced by llvm::orc::COFFPlatform::Create(), llvm::orc::LLJIT::createJITDylib(), llvm::orc::LoadAndLinkDynLibrary::operator()(), and llvm::orc::ExecutorNativePlatform::operator()().
addToLinkOrder() [2/2]
void llvm::orc::JITDylib::addToLinkOrder (JITDylib & JD, JITDylibLookupFlags JDLookupFlags = JITDylibLookupFlags::MatchExportedSymbolsOnly)
Add the given JITDylib to the link order for definitions in this JITDylib.
It is illegal to call this method on a defunct JITDylib and the client is responsible for ensuring that they do not do so.
Definition at line 1364 of file Core.cpp.
References llvm::orc::ExecutionSession::runSessionLocked().
clear()
Error llvm::orc::JITDylib::clear ()
Calls remove on all trackers currently associated with this JITDylib.
Does not run static deinits.
Note that removal happens outside the session lock, so new code may be added concurrently while the clear is underway, and the newly added code will not be cleared. Adding new code concurrently with a clear is usually a bug and should be avoided.
It is illegal to call this method on a defunct JITDylib and the client is responsible for ensuring that they do not do so.
Definition at line 659 of file Core.cpp.
References assert(), getDefaultResourceTracker(), llvm::joinErrors(), llvm::orc::ExecutionSession::runSessionLocked(), and llvm::Error::success().
createResourceTracker()
ResourceTrackerSP llvm::orc::JITDylib::createResourceTracker ()
Create a resource tracker for this JITDylib.
It is illegal to call this method on a defunct JITDylib and the client is responsible for ensuring that they do not do so.
Definition at line 683 of file Core.cpp.
References assert(), and llvm::orc::ExecutionSession::runSessionLocked().
define() [1/2]
template<typename MaterializationUnitType > Error llvm::orc::JITDylib::define (std::unique_ptr< MaterializationUnitType > && MU, ResourceTrackerSP RT = nullptr)
Define all symbols provided by the materialization unit to be part of this JITDylib.
If RT is not specified then the default resource tracker will be used.
This overload always takes ownership of the MaterializationUnit. If any errors occur, the MaterializationUnit consumed.
It is illegal to call this method on a defunct JITDylib and the client is responsible for ensuring that they do not do so.
Definition at line 1843 of file Core.h.
References assert(), llvm::dbgs(), DEBUG_WITH_TYPE, llvm::IntrusiveRefCntPtr< T >::get(), getDefaultResourceTracker(), llvm::jitlink::JITLinkDylib::getName(), llvm::orc::ExecutionSession::getPlatform(), P, llvm::orc::ExecutionSession::runSessionLocked(), and llvm::Error::success().
Referenced by llvm::orc::ObjectLayer::add(), llvm::orc::Speculator::addSpeculationRuntime(), llvm::orc::MachOPlatform::Create(), llvm::orc::ELFNixPlatform::Create(), llvm::orc::COFFPlatform::Create(), llvm::orc::LocalCXXRuntimeOverrides::enable(), llvm::orc::JITCompileCallbackManager::getCompileCallback(), llvm::orc::COFFVCRuntimeBootstrapper::initializeStaticVCRuntime(), llvm::orc::COFFPlatform::setupJITDylib(), llvm::orc::ELFNixPlatform::setupJITDylib(), llvm::orc::MachOPlatform::setupJITDylib(), llvm::orc::ReexportsGenerator::tryToGenerate(), llvm::orc::EPCDynamicLibrarySearchGenerator::tryToGenerate(), and llvm::orc::DynamicLibrarySearchGenerator::tryToGenerate().
define() [2/2]
template<typename MaterializationUnitType > Error llvm::orc::JITDylib::define (std::unique_ptr< MaterializationUnitType > & MU, ResourceTrackerSP RT = nullptr)
Define all symbols provided by the materialization unit to be part of this JITDylib.
This overload only takes ownership of the MaterializationUnit no error is generated. If an error occurs, ownership remains with the caller. This may allow the caller to modify the MaterializationUnit to correct the issue, then re-call define.
It is illegal to call this method on a defunct JITDylib and the client is responsible for ensuring that they do not do so.
Definition at line 1886 of file Core.h.
References assert(), llvm::dbgs(), DEBUG_WITH_TYPE, llvm::IntrusiveRefCntPtr< T >::get(), getDefaultResourceTracker(), llvm::jitlink::JITLinkDylib::getName(), llvm::orc::ExecutionSession::getPlatform(), P, llvm::orc::ExecutionSession::runSessionLocked(), and llvm::Error::success().
dump()
void llvm::orc::JITDylib::dump (raw_ostream & OS)
Dump current JITDylib state to OS.
It is legal to call this method on a defunct JITDylib.
Definition at line 1451 of file Core.cpp.
References Addr, assert(), llvm::format(), getName(), I, OS, and llvm::orc::ExecutionSession::runSessionLocked().
getDefaultResourceTracker()
ResourceTrackerSP llvm::orc::JITDylib::getDefaultResourceTracker ()
Get the default resource tracker for this JITDylib.
It is illegal to call this method on a defunct JITDylib and the client is responsible for ensuring that they do not do so.
Definition at line 674 of file Core.cpp.
References assert(), and llvm::orc::ExecutionSession::runSessionLocked().
Referenced by llvm::orc::ObjectLinkingLayer::add(), llvm::orc::ObjectLayer::add(), llvm::orc::IRLayer::add(), llvm::orc::LLJIT::addIRModule(), llvm::orc::LLJIT::addObjectFile(), clear(), and define().
getDFSLinkOrder() [1/2]
Expected< std::vector< JITDylibSP > > llvm::orc::JITDylib::getDFSLinkOrder ()
Return this JITDylib and its transitive dependencies in DFS order based on linkage relationships.
If any JITDylib in the order is defunct then this method will return an error, otherwise returns the order.
Definition at line 2087 of file Core.cpp.
References getDFSLinkOrder().
Referenced by getDFSLinkOrder(), and getReverseDFSLinkOrder().
getDFSLinkOrder() [2/2]
Expected< std::vector< JITDylibSP > > llvm::orc::JITDylib::getDFSLinkOrder (ArrayRef< JITDylibSP > JDs) static
Returns the given JITDylibs and all of their transitive dependencies in DFS order (based on linkage relationships).
Each JITDylib will appear only once.
If any JITDylib in the order is defunct then this method will return an error, otherwise returns the order.
Definition at line 2041 of file Core.cpp.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::count(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::front(), llvm::inconvertibleErrorCode(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::orc::Result.
getExecutionSession()
ExecutionSession & llvm::orc::JITDylib::getExecutionSession () const inline
Get a reference to the ExecutionSession for this JITDylib.
It is legal to call this method on a defunct JITDylib, however the result will only usable if the ExecutionSession is still alive. If this JITDylib is held by an error that may have torn down the JIT then the result should not be used.
Definition at line 977 of file Core.h.
Referenced by llvm::orc::CtorDtorRunner::add(), llvm::orc::buildSimpleReexportsAliasMap(), llvm::orc::MaterializationResponsibility::getExecutionSession(), llvm::orc::LLJITBuilderState::prepareForConstruction(), llvm::orc::ResourceTracker::remove(), llvm::orc::CtorDtorRunner::run(), llvm::orc::ResourceTracker::transferTo(), llvm::orc::ReexportsGenerator::tryToGenerate(), llvm::orc::ResourceTracker::withResourceKeyDo(), and llvm::orc::ResourceTracker::~ResourceTracker().
getReverseDFSLinkOrder() [1/2]
Expected< std::vector< JITDylibSP > > llvm::orc::JITDylib::getReverseDFSLinkOrder ()
Rteurn this JITDylib and its transitive dependencies in reverse DFS order based on linkage relationships.
If any JITDylib in the order is defunct then this method will return an error, otherwise returns the order.
Definition at line 2091 of file Core.cpp.
References getReverseDFSLinkOrder().
Referenced by getReverseDFSLinkOrder().
getReverseDFSLinkOrder() [2/2]
Expected< std::vector< JITDylibSP > > llvm::orc::JITDylib::getReverseDFSLinkOrder (ArrayRef< JITDylibSP > JDs) static
Returns the given JITDylibs and all of their transitive dependencies in reverse DFS order (based on linkage relationships).
Each JITDylib will appear only once.
If any JITDylib in the order is defunct then this method will return an error, otherwise returns the order.
Definition at line 2080 of file Core.cpp.
References getDFSLinkOrder(), and llvm::orc::Result.
operator=() [1/2]
JITDylib & llvm::orc::JITDylib::operator= (const JITDylib &) delete
operator=() [2/2]
JITDylib & llvm::orc::JITDylib::operator= (JITDylib &&) delete
remove()
Error llvm::orc::JITDylib::remove (const SymbolNameSet & Names)
Tries to remove the given symbols.
If any symbols are not defined in this JITDylib this method will return a SymbolsNotFound error covering the missing symbols.
If all symbols are found but some symbols are in the process of being materialized this method will return a SymbolsCouldNotBeRemoved error.
On success, all symbols are removed. On failure, the JITDylib state is left unmodified (no symbols are removed).
It is illegal to call this method on a defunct JITDylib and the client is responsible for ensuring that they do not do so.
Definition at line 1392 of file Core.cpp.
References assert(), llvm::orc::ExecutionSession::getSymbolStringPool(), I, llvm::orc::Materializing, Name, and llvm::orc::ExecutionSession::runSessionLocked().
removeFromLinkOrder()
void llvm::orc::JITDylib::removeFromLinkOrder (JITDylib & JD)
Remove the given JITDylib from the link order for this JITDylib if it is present.
Otherwise this operation is a no-op.
It is illegal to call this method on a defunct JITDylib and the client is responsible for ensuring that they do not do so.
Definition at line 1380 of file Core.cpp.
References assert(), llvm::find_if(), I, and llvm::orc::ExecutionSession::runSessionLocked().
removeGenerator()
void llvm::orc::JITDylib::removeGenerator (DefinitionGenerator & G)
Remove a definition generator from this JITDylib.
The given generator must exist in this JITDylib's generators list (i.e. have been added and not yet removed).
It is illegal to call this method on a defunct JITDylib and the client is responsible for ensuring that they do not do so.
Definition at line 691 of file Core.cpp.
References assert(), llvm::find_if(), G, H, I, and llvm::orc::ExecutionSession::runSessionLocked().
replaceInLinkOrder()
void llvm::orc::JITDylib::replaceInLinkOrder (JITDylib & OldJD, JITDylib & NewJD, JITDylibLookupFlags JDLookupFlags = JITDylibLookupFlags::MatchExportedSymbolsOnly)
Replace OldJD with NewJD in the link order if OldJD is present.
Otherwise this operation is a no-op.
It is illegal to call this method on a defunct JITDylib and the client is responsible for ensuring that they do not do so.
Definition at line 1368 of file Core.cpp.
References assert(), and llvm::orc::ExecutionSession::runSessionLocked().
setLinkOrder()
void llvm::orc::JITDylib::setLinkOrder (JITDylibSearchOrder NewSearchOrder, bool LinkAgainstThisJITDylibFirst = true)
Set the link order to be used when fixing up definitions in JITDylib.
This will replace the previous link order, and apply to any symbol resolutions made for definitions in this JITDylib after the call to setLinkOrder (even if the definition itself was added before the call).
If LinkAgainstThisJITDylibFirst is true (the default) then this JITDylib will add itself to the beginning of the LinkOrder (Clients should not put this JITDylib in the list in this case, to avoid redundant lookups).
If LinkAgainstThisJITDylibFirst is false then the link order will be used as-is. The primary motivation for this feature is to support deliberate shadowing of symbols in this JITDylib by a facade JITDylib. For example, the facade may resolve function names to stubs, and the stubs may compile lazily by looking up symbols in this dylib. Adding the facade dylib as the first in the link order (instead of this dylib) ensures that definitions within this dylib resolve to the lazy-compiling stubs, rather than immediately materializing the definitions in this dylib.
It is illegal to call this method on a defunct JITDylib and the client is responsible for ensuring that they do not do so.
Definition at line 1337 of file Core.cpp.
References llvm::append_range(), assert(), and llvm::orc::ExecutionSession::runSessionLocked().
withLinkOrderDo()
template<typename Func > auto llvm::orc::JITDylib::withLinkOrderDo (Func && F) -> decltype(F(std::declval<const JITDylibSearchOrder &>()))
Do something with the link order (run under the session lock).
It is illegal to call this method on a defunct JITDylib and the client is responsible for ensuring that they do not do so.
Definition at line 1836 of file Core.h.
References assert(), and F.
Referenced by llvm::orc::ORCPlatformSupport::deinitialize(), llvm::orc::ORCPlatformSupport::initialize(), and llvm::orc::DLLImportDefinitionGenerator::tryToGenerate().
Friends And Related Function Documentation
AsynchronousSymbolQuery
friend class AsynchronousSymbolQuery friend
Definition at line 959 of file Core.h.
ExecutionSession
friend class ExecutionSession friend
Definition at line 960 of file Core.h.
MaterializationResponsibility
friend class MaterializationResponsibility friend
Definition at line 962 of file Core.h.
Platform
friend class Platform friend
Definition at line 961 of file Core.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp