LLVM: SCEVLoopGuardRewriter Class Reference
SCEVLoopGuardRewriter Class Reference
A rewriter to replace SCEV expressions in Map with the corresponding entry in the map.
Public Member Functions
SCEVLoopGuardRewriter (ScalarEvolution &SE, DenseMap< const SCEV *, const SCEV * > &M)
const SCEV * visitAddRecExpr (const SCEVAddRecExpr *Expr)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
const SCEV * visitZeroExtendExpr (const SCEVZeroExtendExpr *Expr)
const SCEV * visitSignExtendExpr (const SCEVSignExtendExpr *Expr)
const SCEV * visitUMinExpr (const SCEVUMinExpr *Expr)
const SCEV * visitSMinExpr (const SCEVSMinExpr *Expr)
Public Member Functions inherited from llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >
SCEVRewriteVisitor (ScalarEvolution &SE)
const SCEV * visit (const SCEV *S)
const SCEV * visitConstant (const SCEVConstant *Constant)
const SCEV * visitVScale (const SCEVVScale *VScale)
const SCEV * visitPtrToIntExpr (const SCEVPtrToIntExpr *Expr)
const SCEV * visitTruncateExpr (const SCEVTruncateExpr *Expr)
const SCEV * visitZeroExtendExpr (const SCEVZeroExtendExpr *Expr)
const SCEV * visitSignExtendExpr (const SCEVSignExtendExpr *Expr)
const SCEV * visitAddExpr (const SCEVAddExpr *Expr)
const SCEV * visitMulExpr (const SCEVMulExpr *Expr)
const SCEV * visitUDivExpr (const SCEVUDivExpr *Expr)
const SCEV * visitAddRecExpr (const SCEVAddRecExpr *Expr)
const SCEV * visitSMaxExpr (const SCEVSMaxExpr *Expr)
const SCEV * visitUMaxExpr (const SCEVUMaxExpr *Expr)
const SCEV * visitSMinExpr (const SCEVSMinExpr *Expr)
const SCEV * visitUMinExpr (const SCEVUMinExpr *Expr)
const SCEV * visitSequentialUMinExpr (const SCEVSequentialUMinExpr *Expr)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *Expr)
Public Member Functions inherited from llvm::SCEVVisitor< SC, RetVal >
RetVal visit (const SCEV *S)
RetVal visitCouldNotCompute (const SCEVCouldNotCompute *S)
Additional Inherited Members
Protected Attributes inherited from llvm::SCEVRewriteVisitor< SCEVLoopGuardRewriter >
ScalarEvolution & SE
SmallDenseMap< const SCEV *, const SCEV * > RewriteResults
Detailed Description
A rewriter to replace SCEV expressions in Map with the corresponding entry in the map.
It skips AddRecExpr because we cannot guarantee that the replacement is loop invariant in the loop of the AddRec.
Definition at line 14941 of file ScalarEvolution.cpp.
Constructor & Destructor Documentation
SCEVLoopGuardRewriter()
SCEVLoopGuardRewriter::SCEVLoopGuardRewriter (ScalarEvolution & SE, DenseMap< const SCEV *, const SCEV * > & M) inline
Definition at line 14945 of file ScalarEvolution.cpp.
Member Function Documentation
visitAddRecExpr()
const SCEV * SCEVLoopGuardRewriter::visitAddRecExpr (const SCEVAddRecExpr * Expr) inline
Definition at line 14949 of file ScalarEvolution.cpp.
visitSignExtendExpr()
const SCEV * SCEVLoopGuardRewriter::visitSignExtendExpr (const SCEVSignExtendExpr * Expr) inline
Definition at line 14982 of file ScalarEvolution.cpp.
References I, and llvm::SCEVRewriteVisitor< SC >::visitSignExtendExpr().
visitSMinExpr()
const SCEV * SCEVLoopGuardRewriter::visitSMinExpr (const SCEVSMinExpr * Expr) inline
Definition at line 14997 of file ScalarEvolution.cpp.
References I, and llvm::SCEVRewriteVisitor< SC >::visitSMinExpr().
visitUMinExpr()
const SCEV * SCEVLoopGuardRewriter::visitUMinExpr (const SCEVUMinExpr * Expr) inline
Definition at line 14990 of file ScalarEvolution.cpp.
References I, and llvm::SCEVRewriteVisitor< SC >::visitUMinExpr().
visitUnknown()
const SCEV * SCEVLoopGuardRewriter::visitUnknown (const SCEVUnknown * Expr) inline
Definition at line 14951 of file ScalarEvolution.cpp.
References I.
visitZeroExtendExpr()
const SCEV * SCEVLoopGuardRewriter::visitZeroExtendExpr (const SCEVZeroExtendExpr * Expr) inline
Definition at line 14958 of file ScalarEvolution.cpp.
References llvm::IntegerType::get(), llvm::ScalarEvolution::getContext(), llvm::SCEVCastExpr::getOperand(), llvm::Type::getScalarSizeInBits(), llvm::SCEVCastExpr::getType(), llvm::ScalarEvolution::getZeroExtendExpr(), I, and llvm::SCEVRewriteVisitor< SC >::visitZeroExtendExpr().
The documentation for this class was generated from the following file:
lib/Analysis/ScalarEvolution.cpp