LLVM: llvm::dwarf_linker::classic::DwarfStreamer Class Reference
llvm::dwarf_linker::classic::DwarfStreamer Class Reference
User of DwarfStreamer should call initialization code for AsmPrinter:
#include "llvm/DWARFLinker/Classic/DWARFStreamer.h"
Public Member Functions
DwarfStreamer (DWARFLinkerBase::OutputFileType OutFileType, raw_pwrite_stream &OutFile, DWARFLinkerBase::TranslatorFuncTy Translator, DWARFLinkerBase::MessageHandlerTy Warning)
virtual ~DwarfStreamer ()=default
Error init (Triple TheTriple, StringRef Swift5ReflectionSegmentName)
void finish () override
Dump the file to the disk.
AsmPrinter & getAsmPrinter () const
void switchToDebugInfoSection (unsigned DwarfVersion)
Set the current output section to debug_info and change the MC Dwarf version to DwarfVersion.
void emitCompileUnitHeader (CompileUnit &Unit, unsigned DwarfVersion) override
Emit the compilation unit header for Unit in the debug_info section.
void emitDIE (DIE &Die) override
Recursively emit the DIE tree rooted at Die.
void emitAbbrevs (const std::vector< std::unique_ptr< DIEAbbrev > > &Abbrevs, unsigned DwarfVersion) override
Emit the abbreviation table Abbrevs to the debug_abbrev section.
void emitSectionContents (StringRef SecData, DebugSectionKind SecKind) override
Emit contents of section SecName From Obj.
void emitStrings (const NonRelocatableStringpool &Pool) override
Emit the string table described by Pool into .debug_str table.
void emitStringOffsets (const SmallVector< uint64_t > &StringOffset, uint16_t TargetDWARFVersion) override
Emit the debug string offset table described by StringOffsets into the .debug_str_offsets table.
void emitLineStrings (const NonRelocatableStringpool &Pool) override
Emit the string table described by Pool into .debug_line_str table.
void emitSwiftAST (StringRef Buffer)
Emit the swift_ast section stored in Buffer.
void emitSwiftReflectionSection (llvm::binaryformat::Swift5ReflectionSectionKind ReflSectionKind, StringRef Buffer, uint32_t Alignment, uint32_t Size)
Emit the swift reflection section stored in Buffer.
MCSymbol * emitDwarfDebugRangeListHeader (const CompileUnit &Unit) override
Emit debug ranges(.debug_ranges, .debug_rnglists) header.
void emitDwarfDebugRangeListFragment (const CompileUnit &Unit, const AddressRanges &LinkedRanges, PatchLocation Patch, DebugDieValuePool &AddrPool) override
Emit debug ranges(.debug_ranges, .debug_rnglists) fragment.
void emitDwarfDebugRangeListFooter (const CompileUnit &Unit, MCSymbol *EndLabel) override
Emit debug ranges(.debug_ranges, .debug_rnglists) footer.
MCSymbol * emitDwarfDebugLocListHeader (const CompileUnit &Unit) override
Emit debug locations(.debug_loc, .debug_loclists) header.
MCSymbol * emitDwarfDebugAddrsHeader (const CompileUnit &Unit) override
Emit .debug_addr header.
void emitDwarfDebugAddrs (const SmallVector< uint64_t > &Addrs, uint8_t AddrSize) override
Emit the addresses described by Addrs into .debug_addr table.
void emitDwarfDebugAddrsFooter (const CompileUnit &Unit, MCSymbol *EndLabel) override
Emit .debug_addr footer.
void emitDwarfDebugLocListFragment (const CompileUnit &Unit, const DWARFLocationExpressionsVector &LinkedLocationExpression, PatchLocation Patch, DebugDieValuePool &AddrPool) override
Emit debug ranges(.debug_loc, .debug_loclists) fragment.
void emitDwarfDebugLocListFooter (const CompileUnit &Unit, MCSymbol *EndLabel) override
Emit debug ranges(.debug_loc, .debug_loclists) footer.
void emitDwarfDebugArangesTable (const CompileUnit &Unit, const AddressRanges &LinkedRanges) override
Emit .debug_aranges entries for Unit.
uint64_t getRangesSectionSize () const override
Returns size of generated .debug_ranges section.
uint64_t getRngListsSectionSize () const override
Returns size of generated .debug_rnglists section.
void emitLineTableForUnit (const DWARFDebugLine::LineTable &LineTable, const CompileUnit &Unit, OffsetsStringPool &DebugStrPool, OffsetsStringPool &DebugLineStrPool) override
Emit .debug_line table entry for specified LineTable.
uint64_t getLineSectionSize () const override
Returns size of generated .debug_line section.
void emitPubNamesForUnit (const CompileUnit &Unit) override
Emit the .debug_pubnames contribution for Unit.
void emitPubTypesForUnit (const CompileUnit &Unit) override
Emit the .debug_pubtypes contribution for Unit.
void emitCIE (StringRef CIEBytes) override
Emit a CIE.
void emitFDE (uint32_t CIEOffset, uint32_t AddreSize, uint64_t Address, StringRef Bytes) override
Emit an FDE with data Bytes.
void emitDebugNames (DWARF5AccelTable &Table) override
Emit DWARF debug names.
void emitAppleNamespaces (AccelTable< AppleAccelTableStaticOffsetData > &Table) override
Emit Apple namespaces accelerator table.
void emitAppleNames (AccelTable< AppleAccelTableStaticOffsetData > &Table) override
Emit Apple names accelerator table.
void emitAppleObjc (AccelTable< AppleAccelTableStaticOffsetData > &Table) override
Emit Apple Objective-C accelerator table.
void emitAppleTypes (AccelTable< AppleAccelTableStaticTypeData > &Table) override
Emit Apple type accelerator table.
uint64_t getFrameSectionSize () const override
Returns size of generated .debug_frame section.
uint64_t getDebugInfoSectionSize () const override
Returns size of generated .debug_info section.
uint64_t getDebugMacInfoSectionSize () const override
Returns size of generated .debug_macinfo section.
uint64_t getDebugMacroSectionSize () const override
Returns size of generated .debug_macro section.
uint64_t getLocListsSectionSize () const override
Returns size of generated .debug_loclists section.
uint64_t getDebugAddrSectionSize () const override
Returns size of generated .debug_addr section.
void emitMacroTables (DWARFContext *Context, const Offset2UnitMap &UnitMacroMap, OffsetsStringPool &StringPool) override
Emit all available macro tables(DWARFv4 and DWARFv5).
Public Member Functions inherited from llvm::dwarf_linker::classic::DwarfEmitter
virtual ~DwarfEmitter ()=default
virtual void emitSectionContents (StringRef SecData, DebugSectionKind SecKind)=0
Emit section named SecName with data SecData.
virtual void emitAbbrevs (const std::vector< std::unique_ptr< DIEAbbrev > > &Abbrevs, unsigned DwarfVersion)=0
Emit the abbreviation table Abbrevs to the .debug_abbrev section.
virtual void emitStrings (const NonRelocatableStringpool &Pool)=0
Emit the string table described by Pool into .debug_str table.
virtual void emitStringOffsets (const SmallVector< uint64_t > &StringOffsets, uint16_t TargetDWARFVersion)=0
Emit the debug string offset table described by StringOffsets into the .debug_str_offsets table.
virtual void emitLineStrings (const NonRelocatableStringpool &Pool)=0
Emit the string table described by Pool into .debug_line_str table.
virtual void emitDebugNames (DWARF5AccelTable &Table)=0
Emit DWARF debug names.
virtual void emitAppleNamespaces (AccelTable< AppleAccelTableStaticOffsetData > &Table)=0
Emit Apple namespaces accelerator table.
virtual void emitAppleNames (AccelTable< AppleAccelTableStaticOffsetData > &Table)=0
Emit Apple names accelerator table.
virtual void emitAppleObjc (AccelTable< AppleAccelTableStaticOffsetData > &Table)=0
Emit Apple Objective-C accelerator table.
virtual void emitAppleTypes (AccelTable< AppleAccelTableStaticTypeData > &Table)=0
Emit Apple type accelerator table.
virtual MCSymbol * emitDwarfDebugRangeListHeader (const CompileUnit &Unit)=0
Emit debug ranges (.debug_ranges, .debug_rnglists) header.
virtual void emitDwarfDebugRangeListFragment (const CompileUnit &Unit, const AddressRanges &LinkedRanges, PatchLocation Patch, DebugDieValuePool &AddrPool)=0
Emit debug ranges (.debug_ranges, .debug_rnglists) fragment.
virtual void emitDwarfDebugRangeListFooter (const CompileUnit &Unit, MCSymbol *EndLabel)=0
Emit debug ranges (.debug_ranges, .debug_rnglists) footer.
virtual MCSymbol * emitDwarfDebugLocListHeader (const CompileUnit &Unit)=0
Emit debug locations (.debug_loc, .debug_loclists) header.
virtual void emitDwarfDebugLocListFragment (const CompileUnit &Unit, const DWARFLocationExpressionsVector &LinkedLocationExpression, PatchLocation Patch, DebugDieValuePool &AddrPool)=0
Emit debug locations (.debug_loc, .debug_loclists) fragment.
virtual void emitDwarfDebugLocListFooter (const CompileUnit &Unit, MCSymbol *EndLabel)=0
Emit debug locations (.debug_loc, .debug_loclists) footer.
virtual MCSymbol * emitDwarfDebugAddrsHeader (const CompileUnit &Unit)=0
Emit .debug_addr header.
virtual void emitDwarfDebugAddrs (const SmallVector< uint64_t > &Addrs, uint8_t AddrSize)=0
Emit the addresses described by Addrs into the .debug_addr section.
virtual void emitDwarfDebugAddrsFooter (const CompileUnit &Unit, MCSymbol *EndLabel)=0
Emit .debug_addr footer.
virtual void emitDwarfDebugArangesTable (const CompileUnit &Unit, const AddressRanges &LinkedRanges)=0
Emit .debug_aranges entries for Unit.
virtual void emitLineTableForUnit (const DWARFDebugLine::LineTable &LineTable, const CompileUnit &Unit, OffsetsStringPool &DebugStrPool, OffsetsStringPool &DebugLineStrPool)=0
Emit specified LineTable into .debug_line table.
virtual void emitPubNamesForUnit (const CompileUnit &Unit)=0
Emit the .debug_pubnames contribution for Unit.
virtual void emitPubTypesForUnit (const CompileUnit &Unit)=0
Emit the .debug_pubtypes contribution for Unit.
virtual void emitCIE (StringRef CIEBytes)=0
Emit a CIE.
virtual void emitFDE (uint32_t CIEOffset, uint32_t AddreSize, uint64_t Address, StringRef Bytes)=0
Emit an FDE with data Bytes.
virtual void emitCompileUnitHeader (CompileUnit &Unit, unsigned DwarfVersion)=0
Emit the compilation unit header for Unit in the .debug_info section.
virtual void emitDIE (DIE &Die)=0
Recursively emit the DIE tree rooted at Die.
virtual void emitMacroTables (DWARFContext *Context, const Offset2UnitMap &UnitMacroMap, OffsetsStringPool &StringPool)=0
Emit all available macro tables(DWARFv4 and DWARFv5).
virtual uint64_t getLineSectionSize () const =0
Returns size of generated .debug_line section.
virtual uint64_t getFrameSectionSize () const =0
Returns size of generated .debug_frame section.
virtual uint64_t getRangesSectionSize () const =0
Returns size of generated .debug_ranges section.
virtual uint64_t getRngListsSectionSize () const =0
Returns size of generated .debug_rnglists section.
virtual uint64_t getDebugInfoSectionSize () const =0
Returns size of generated .debug_info section.
virtual uint64_t getDebugMacInfoSectionSize () const =0
Returns size of generated .debug_macinfo section.
virtual uint64_t getDebugMacroSectionSize () const =0
Returns size of generated .debug_macro section.
virtual uint64_t getLocListsSectionSize () const =0
Returns size of generated .debug_loclists section.
virtual uint64_t getDebugAddrSectionSize () const =0
Returns size of generated .debug_addr section.
virtual void finish ()=0
Dump the file to the disk.
Static Public Member Functions
static Expected< std::unique_ptr< DwarfStreamer > > createStreamer (const Triple &TheTriple, DWARFLinkerBase::OutputFileType FileType, raw_pwrite_stream &OutFile, DWARFLinkerBase::TranslatorFuncTy Translator, DWARFLinkerBase::MessageHandlerTy Warning)
Detailed Description
User of DwarfStreamer should call initialization code for AsmPrinter:
InitializeAllTargetInfos(); InitializeAllTargetMCs(); InitializeAllTargets(); InitializeAllAsmPrinters(); The Dwarf streaming logic.
All interactions with the MC layer that is used to build the debug information binary representation are handled in this class.
Definition at line 44 of file DWARFStreamer.h.
Constructor & Destructor Documentation
DwarfStreamer()
llvm::dwarf_linker::classic::DwarfStreamer::DwarfStreamer (DWARFLinkerBase::OutputFileType OutFileType, raw_pwrite_stream & OutFile, DWARFLinkerBase::TranslatorFuncTy Translator, DWARFLinkerBase::MessageHandlerTy Warning) inline
Definition at line 46 of file DWARFStreamer.h.
~DwarfStreamer()
virtual llvm::dwarf_linker::classic::DwarfStreamer::~DwarfStreamer () virtual default
Member Function Documentation
createStreamer()
Expected< std::unique_ptr< DwarfStreamer > > DwarfStreamer::createStreamer (const Triple & TheTriple, DWARFLinkerBase::OutputFileType FileType, raw_pwrite_stream & OutFile, DWARFLinkerBase::TranslatorFuncTy Translator, DWARFLinkerBase::MessageHandlerTy Warning) static
Definition at line 33 of file DWARFStreamer.cpp.
References llvm::Warning.
emitAbbrevs()
void DwarfStreamer::emitAbbrevs (const std::vector< std::unique_ptr< DIEAbbrev > > & Abbrevs, unsigned DwarfVersion) override virtual
Emit the abbreviation table Abbrevs to the debug_abbrev section.
Emit the Abbrevs array as the shared abbreviation table for the linked Dwarf file.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 211 of file DWARFStreamer.cpp.
References llvm::MCStreamer::switchSection().
emitAppleNames()
void DwarfStreamer::emitAppleNames (AccelTable< AppleAccelTableStaticOffsetData > & Table) override virtual
Emit Apple names accelerator table.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 389 of file DWARFStreamer.cpp.
References llvm::emitAppleAccelTable().
emitAppleNamespaces()
void DwarfStreamer::emitAppleNamespaces (AccelTable< AppleAccelTableStaticOffsetData > & Table) override virtual
Emit Apple namespaces accelerator table.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 381 of file DWARFStreamer.cpp.
References llvm::emitAppleAccelTable().
emitAppleObjc()
void DwarfStreamer::emitAppleObjc (AccelTable< AppleAccelTableStaticOffsetData > & Table) override virtual
Emit Apple Objective-C accelerator table.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 397 of file DWARFStreamer.cpp.
References llvm::emitAppleAccelTable().
emitAppleTypes()
void DwarfStreamer::emitAppleTypes (AccelTable< AppleAccelTableStaticTypeData > & Table) override virtual
Emit Apple type accelerator table.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 405 of file DWARFStreamer.cpp.
References llvm::emitAppleAccelTable().
emitCIE()
void DwarfStreamer::emitCIE (StringRef CIEBytes) override virtual
Emit a CIE.
Emit a CIE into the debug_frame section.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 1246 of file DWARFStreamer.cpp.
References llvm::MCStreamer::emitBytes(), llvm::StringRef::size(), and llvm::MCStreamer::switchSection().
emitCompileUnitHeader()
void DwarfStreamer::emitCompileUnitHeader (CompileUnit & Unit, unsigned DwarfVersion) override virtual
Emit the compilation unit header for Unit in the debug_info section.
As a side effect, this also switches the current Dwarf version of the MC layer to the one of U.getOrigUnit().
A Dwarf 4 section header is encoded as: uint32_t Unit length (omitting this field) uint16_t Version uint32_t Abbreviation table offset uint8_t Address size Leading to a total of 11 bytes.
A Dwarf 5 section header is encoded as: uint32_t Unit length (omitting this field) uint16_t Version uint8_t Unit type uint8_t Address size uint32_t Abbreviation table offset Leading to a total of 12 bytes.
The start of the unit within its section.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 176 of file DWARFStreamer.cpp.
References switchToDebugInfoSection().
emitDebugNames()
void DwarfStreamer::emitDebugNames (DWARF5AccelTable & Table) override virtual
Emit DWARF debug names.
llvm-dwarfutil doesn't support type units + .debug_names right now.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 350 of file DWARFStreamer.cpp.
References llvm::DIEInteger::BestForm(), llvm::emitDWARF5AccelTable(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size().
emitDIE()
void DwarfStreamer::emitDIE (DIE & Die) override virtual
Recursively emit the DIE tree rooted at Die.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 220 of file DWARFStreamer.cpp.
References llvm::DIE::getSize(), and llvm::MCStreamer::switchSection().
emitDwarfDebugAddrs()
void DwarfStreamer::emitDwarfDebugAddrs (const SmallVector< uint64_t > & Addrs, uint8_t AddrSize) override virtual
Emit the addresses described by Addrs into .debug_addr table.
Emit the .debug_addr addresses stored in Addrs.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 736 of file DWARFStreamer.cpp.
References Addr.
emitDwarfDebugAddrsFooter()
void DwarfStreamer::emitDwarfDebugAddrsFooter (const CompileUnit & Unit, MCSymbol * EndLabel) override virtual
Emit .debug_addr footer.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 746 of file DWARFStreamer.cpp.
References llvm::MCStreamer::switchSection().
emitDwarfDebugAddrsHeader()
MCSymbol * DwarfStreamer::emitDwarfDebugAddrsHeader (const CompileUnit & Unit) override virtual
Emit .debug_addr header.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 706 of file DWARFStreamer.cpp.
References llvm::MCStreamer::switchSection().
emitDwarfDebugArangesTable()
void DwarfStreamer::emitDwarfDebugArangesTable (const CompileUnit & Unit, const AddressRanges & LinkedRanges) override virtual
Emit .debug_aranges entries for Unit.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 433 of file DWARFStreamer.cpp.
References llvm::dwarf::DW_ARANGES_VERSION, llvm::MCStreamer::emitIntValue(), llvm::offsetToAlignment(), and llvm::MCStreamer::switchSection().
emitDwarfDebugLocListFooter()
void DwarfStreamer::emitDwarfDebugLocListFooter (const CompileUnit & Unit, MCSymbol * EndLabel) override virtual
Emit debug ranges(.debug_loc, .debug_loclists) footer.
Emit debug locations(.debug_loc, .debug_loclists) footer.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 653 of file DWARFStreamer.cpp.
References llvm::MCStreamer::switchSection().
emitDwarfDebugLocListFragment()
void DwarfStreamer::emitDwarfDebugLocListFragment (const CompileUnit & Unit, const DWARFLocationExpressionsVector & LinkedLocationExpression, PatchLocation Patch, DebugDieValuePool & AddrPool) override virtual
Emit debug ranges(.debug_loc, .debug_loclists) fragment.
Emit debug locations(.debug_loc, .debug_loclists) fragment.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 639 of file DWARFStreamer.cpp.
emitDwarfDebugLocListHeader()
MCSymbol * DwarfStreamer::emitDwarfDebugLocListHeader (const CompileUnit & Unit) override virtual
Emit debug locations(.debug_loc, .debug_loclists) header.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 603 of file DWARFStreamer.cpp.
References llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), and llvm::MCStreamer::switchSection().
emitDwarfDebugRangeListFooter()
void DwarfStreamer::emitDwarfDebugRangeListFooter (const CompileUnit & Unit, MCSymbol * EndLabel) override virtual
Emit debug ranges(.debug_ranges, .debug_rnglists) footer.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 552 of file DWARFStreamer.cpp.
References llvm::MCStreamer::switchSection().
emitDwarfDebugRangeListFragment()
void DwarfStreamer::emitDwarfDebugRangeListFragment (const CompileUnit & Unit, const AddressRanges & LinkedRanges, PatchLocation Patch, DebugDieValuePool & AddrPool) override virtual
Emit debug ranges(.debug_ranges, .debug_rnglists) fragment.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 541 of file DWARFStreamer.cpp.
emitDwarfDebugRangeListHeader()
MCSymbol * DwarfStreamer::emitDwarfDebugRangeListHeader (const CompileUnit & Unit) override virtual
Emit debug ranges(.debug_ranges, .debug_rnglists) header.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 506 of file DWARFStreamer.cpp.
References llvm::MCStreamer::emitInt16(), llvm::MCStreamer::emitInt32(), llvm::MCStreamer::emitInt8(), and llvm::MCStreamer::switchSection().
emitFDE()
void DwarfStreamer::emitFDE (uint32_t CIEOffset, uint32_t AddrSize, uint64_t Address, StringRef FDEBytes) override virtual
Emit an FDE with data Bytes.
Emit a FDE into the debug_frame section.
FDEBytes contains the FDE data without the length, CIE offset and address which will be replaced with the parameter values.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 1256 of file DWARFStreamer.cpp.
References llvm::Address, llvm::MCStreamer::emitBytes(), llvm::MCStreamer::emitIntValue(), llvm::StringRef::size(), and llvm::MCStreamer::switchSection().
emitLineStrings()
void DwarfStreamer::emitLineStrings (const NonRelocatableStringpool & Pool) override virtual
Emit the string table described by Pool into .debug_line_str table.
Emit the debug_line_str section stored in Pool.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 339 of file DWARFStreamer.cpp.
References llvm::NonRelocatableStringpool::getEntriesForEmission().
emitLineTableForUnit()
void DwarfStreamer::emitLineTableForUnit (const DWARFDebugLine::LineTable & LineTable, const CompileUnit & Unit, OffsetsStringPool & DebugStrPool, OffsetsStringPool & DebugLineStrPool) override virtual
Emit .debug_line table entry for specified LineTable.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 810 of file DWARFStreamer.cpp.
References llvm::dwarf::DW_LENGTH_DWARF64, llvm::dwarf::DWARF64, llvm::MCStreamer::emitInt32(), llvm::dwarf::FormParams::Format, llvm::DWARFDebugLine::Prologue::FormParams, llvm::DWARFDebugLine::LineTable::Prologue, and llvm::MCStreamer::switchSection().
emitMacroTables()
void DwarfStreamer::emitMacroTables (DWARFContext * Context, const Offset2UnitMap & UnitMacroMap, OffsetsStringPool & StringPool) override virtual
Emit all available macro tables(DWARFv4 and DWARFv5).
Use UnitMacroMap to get compilation unit by macro table offset. Side effects: Fill StringPool with macro strings, update DW_AT_macro_info, DW_AT_macros attributes for corresponding compile units.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 1267 of file DWARFStreamer.cpp.
References assert(), Context, and llvm::MCStreamer::switchSection().
emitPubNamesForUnit()
void DwarfStreamer::emitPubNamesForUnit (const CompileUnit & Unit) override virtual
Emit the .debug_pubnames contribution for Unit.
Emit .debug_pubnames for Unit.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 1234 of file DWARFStreamer.cpp.
emitPubTypesForUnit()
void DwarfStreamer::emitPubTypesForUnit (const CompileUnit & Unit) override virtual
Emit the .debug_pubtypes contribution for Unit.
Emit .debug_pubtypes for Unit.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 1240 of file DWARFStreamer.cpp.
emitSectionContents()
void DwarfStreamer::emitSectionContents (StringRef SecData, DebugSectionKind SecKind) override virtual
Emit contents of section SecName From Obj.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 227 of file DWARFStreamer.cpp.
References llvm::MCStreamer::emitBytes(), and llvm::MCStreamer::switchSection().
emitStringOffsets()
void DwarfStreamer::emitStringOffsets (const SmallVector< uint64_t > & StringOffset, uint16_t TargetDWARFVersion) override virtual
Emit the debug string offset table described by StringOffsets into the .debug_str_offsets table.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 307 of file DWARFStreamer.cpp.
References llvm::MCStreamer::emitInt16(), and llvm::SmallVectorBase< Size_T >::empty().
emitStrings()
void DwarfStreamer::emitStrings (const NonRelocatableStringpool & Pool) override virtual
Emit the string table described by Pool into .debug_str table.
Emit the debug_str section stored in Pool.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 294 of file DWARFStreamer.cpp.
References llvm::NonRelocatableStringpool::getEntriesForEmission().
emitSwiftAST()
void DwarfStreamer::emitSwiftAST (StringRef Buffer)
Emit the swift_ast section stored in Buffer.
Emit the swift_ast section stored in Buffers.
Definition at line 414 of file DWARFStreamer.cpp.
References llvm::MCStreamer::emitBytes(), llvm::MCSection::setAlignment(), and llvm::MCStreamer::switchSection().
emitSwiftReflectionSection()
void DwarfStreamer::emitSwiftReflectionSection (llvm::binaryformat::Swift5ReflectionSectionKind ReflSectionKind, StringRef Buffer, uint32_t Alignment, uint32_t Size)
Emit the swift reflection section stored in Buffer.
Definition at line 421 of file DWARFStreamer.cpp.
References llvm::MCStreamer::emitBytes(), llvm::MCSection::setAlignment(), and llvm::MCStreamer::switchSection().
finish()
void DwarfStreamer::finish () override virtual
Dump the file to the disk.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 153 of file DWARFStreamer.cpp.
References llvm::MCStreamer::finish().
getAsmPrinter()
AsmPrinter & llvm::dwarf_linker::classic::DwarfStreamer::getAsmPrinter () const inline
Definition at line 64 of file DWARFStreamer.h.
getDebugAddrSectionSize()
uint64_t llvm::dwarf_linker::classic::DwarfStreamer::getDebugAddrSectionSize () const inline override virtual
Returns size of generated .debug_addr section.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 212 of file DWARFStreamer.h.
getDebugInfoSectionSize()
uint64_t llvm::dwarf_linker::classic::DwarfStreamer::getDebugInfoSectionSize () const inline override virtual
Returns size of generated .debug_info section.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 196 of file DWARFStreamer.h.
getDebugMacInfoSectionSize()
uint64_t llvm::dwarf_linker::classic::DwarfStreamer::getDebugMacInfoSectionSize () const inline override virtual
Returns size of generated .debug_macinfo section.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 200 of file DWARFStreamer.h.
getDebugMacroSectionSize()
uint64_t llvm::dwarf_linker::classic::DwarfStreamer::getDebugMacroSectionSize () const inline override virtual
Returns size of generated .debug_macro section.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 204 of file DWARFStreamer.h.
getFrameSectionSize()
uint64_t llvm::dwarf_linker::classic::DwarfStreamer::getFrameSectionSize () const inline override virtual
Returns size of generated .debug_frame section.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 194 of file DWARFStreamer.h.
getLineSectionSize()
uint64_t llvm::dwarf_linker::classic::DwarfStreamer::getLineSectionSize () const inline override virtual
Returns size of generated .debug_line section.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 160 of file DWARFStreamer.h.
getLocListsSectionSize()
uint64_t llvm::dwarf_linker::classic::DwarfStreamer::getLocListsSectionSize () const inline override virtual
Returns size of generated .debug_loclists section.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 208 of file DWARFStreamer.h.
getRangesSectionSize()
uint64_t llvm::dwarf_linker::classic::DwarfStreamer::getRangesSectionSize () const inline override virtual
Returns size of generated .debug_ranges section.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 148 of file DWARFStreamer.h.
getRngListsSectionSize()
uint64_t llvm::dwarf_linker::classic::DwarfStreamer::getRngListsSectionSize () const inline override virtual
Returns size of generated .debug_rnglists section.
Implements llvm::dwarf_linker::classic::DwarfEmitter.
Definition at line 150 of file DWARFStreamer.h.
init()
Error DwarfStreamer::init (Triple TheTriple, StringRef Swift5ReflectionSegmentName)
Definition at line 45 of file DWARFStreamer.cpp.
References llvm::dwarf_linker::DWARFLinkerBase::Assembly, llvm::Target::createAsmPrinter(), llvm::Target::createAsmStreamer(), llvm::Target::createMCAsmBackend(), llvm::Target::createMCAsmInfo(), llvm::Target::createMCCodeEmitter(), llvm::Target::createMCInstPrinter(), llvm::Target::createMCInstrInfo(), llvm::Target::createMCObjectFileInfo(), llvm::Target::createMCObjectStreamer(), llvm::Target::createMCRegInfo(), llvm::Target::createMCSubtargetInfo(), llvm::MCAsmBackend::createObjectWriter(), llvm::createStringError(), llvm::Target::createTargetMachine(), llvm::Triple::getTriple(), llvm::mc::InitMCTargetOptionsFromFlags(), llvm::TargetRegistry::lookupTarget(), llvm::MCTargetOptions::MCIncrementalLinkerCompatible, llvm::MCTargetOptions::MCRelaxAll, llvm::dwarf_linker::DWARFLinkerBase::Object, and llvm::Error::success().
switchToDebugInfoSection()
void DwarfStreamer::switchToDebugInfoSection (unsigned DwarfVersion)
Set the current output section to debug_info and change the MC Dwarf version to DwarfVersion.
Definition at line 155 of file DWARFStreamer.cpp.
References llvm::MCStreamer::switchSection().
Referenced by emitCompileUnitHeader().
The documentation for this class was generated from the following files:
include/llvm/DWARFLinker/Classic/DWARFStreamer.h
lib/DWARFLinker/Classic/DWARFStreamer.cpp