LLVM: llvm::KCFIPass Class Reference
llvm::KCFIPass Class Reference
#include "llvm/Transforms/Instrumentation/KCFI.h"
Public Member Functions
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< KCFIPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< KCFIPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 20 of file KCFI.h.
Member Function Documentation
isRequired()
static bool llvm::KCFIPass::isRequired () inline static
Definition at line 22 of file KCFI.h.
run()
PreservedAnalyses KCFIPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 48 of file KCFI.cpp.
References llvm::PreservedAnalyses::all(), assert(), llvm::IRBuilderBase::CreateAnd(), llvm::MDBuilder::createBranchWeights(), llvm::IRBuilderBase::CreateCall(), llvm::IRBuilderBase::CreateConstInBoundsGEP1_32(), llvm::IRBuilderBase::CreateICmpNE(), llvm::IRBuilderBase::CreateIntToPtr(), llvm::IRBuilderBase::CreateLoad(), llvm::IRBuilderBase::CreatePtrToInt(), llvm::LLVMContext::diagnose(), llvm::SmallVectorBase< Size_T >::empty(), F, llvm::ConstantInt::get(), llvm::Intrinsic::getDeclaration(), llvm::Type::getInt32Ty(), llvm::Value::getType(), I, instructions, Int32Ty, llvm::PreservedAnalyses::none(), llvm::LLVMContext::OB_kcfi, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::CallBase::removeOperandBundle(), llvm::IRBuilderBase::SetInsertPoint(), llvm::SplitBlockAndInsertIfThen(), and llvm::Test.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/KCFI.h
lib/Transforms/Instrumentation/KCFI.cpp