LLVM: llvm::dwarf_linker::parallel::LinkingGlobalData Class Reference
llvm::dwarf_linker::parallel::LinkingGlobalData Class Reference
This class keeps data and services common for the whole linking process.
#include "DWARFLinker/Parallel/DWARFLinkerGlobalData.h"
Public Member Functions
llvm::parallel::PerThreadBumpPtrAllocator & getAllocator ()
Returns global per-thread allocator.
StringPool & getStringPool ()
Returns global string pool.
void setTranslator (TranslatorFuncTy Translator)
Set translation function.
StringRef translateString (StringRef String)
Translate specified string.
const DWARFLinkerOptions & getOptions () const
Returns linking options.
void setWarningHandler (MessageHandlerTy Handler)
Set warning handler.
void setErrorHandler (MessageHandlerTy Handler)
Set error handler.
void warn (const Twine &Warning, StringRef Context, const DWARFDie *DIE=nullptr)
Report warning.
void warn (Error Warning, StringRef Context, const DWARFDie *DIE=nullptr)
Report warning.
void error (const Twine &Err, StringRef Context, const DWARFDie *DIE=nullptr)
Report error.
void error (Error Err, StringRef Context, const DWARFDie *DIE=nullptr)
Report error.
void setTargetTriple (const Triple &TargetTriple)
Set target triple.
std::optional< std::reference_wrapper< const Triple > > getTargetTriple ()
Optionally return target triple.
Protected Attributes
llvm::parallel::PerThreadBumpPtrAllocator Allocator
StringPool Strings
TranslatorFuncTy Translator
DWARFLinkerOptions Options
MessageHandlerTy WarningHandler
MessageHandlerTy ErrorHandler
std::optional< Triple > TargetTriple
Triple for output data.
Detailed Description
This class keeps data and services common for the whole linking process.
Definition at line 86 of file DWARFLinkerGlobalData.h.
Member Function Documentation
error() [1/2]
void llvm::dwarf_linker::parallel::LinkingGlobalData::error (const Twine & Err, StringRef Context, const DWARFDie * DIE = nullptr) inline
Report error.
Definition at line 135 of file DWARFLinkerGlobalData.h.
References Context, and ErrorHandler.
Referenced by llvm::dwarf_linker::parallel::CompileUnit::error(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::link(), and llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::loadClangModule().
error() [2/2]
void llvm::dwarf_linker::parallel::LinkingGlobalData::error (Error Err, StringRef Context, const DWARFDie * DIE = nullptr) inline
Report error.
Definition at line 142 of file DWARFLinkerGlobalData.h.
References Context, error, llvm::handleAllErrors(), and Info.
getAllocator()
llvm::parallel::PerThreadBumpPtrAllocator & llvm::dwarf_linker::parallel::LinkingGlobalData::getAllocator () inline
Returns global per-thread allocator.
Definition at line 91 of file DWARFLinkerGlobalData.h.
References Allocator.
Referenced by llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::add().
getOptions()
const DWARFLinkerOptions & llvm::dwarf_linker::parallel::LinkingGlobalData::getOptions () const inline
Returns linking options.
Definition at line 112 of file DWARFLinkerGlobalData.h.
References Options.
Referenced by llvm::dwarf_linker::parallel::DWARFLinkerImpl::addAccelTableKind(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::addObjectFile(), llvm::dwarf_linker::parallel::CompileUnit::analyzeImportedModule(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneAddressAttr(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmit(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneBlockAttr(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneScalarAttr(), llvm::dwarf_linker::parallel::CompileUnit::CompileUnit(), llvm::dwarf_linker::parallel::DIEAttributeCloner::DIEAttributeCloner(), llvm::dwarf_linker::parallel::TypeUnit::finishCloningAndEmit(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::glueCompileUnitsAndWriteToTheOutput(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::isClangModuleRef(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::link(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::link(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::linkSingleCompileUnit(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::loadClangModule(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::registerModuleReference(), llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::save(), llvm::dwarf_linker::parallel::DIEAttributeCloner::shouldSkipAttribute(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::validateAndUpdateOptions(), and llvm::dwarf_linker::parallel::DWARFLinkerImpl::verifyInput().
getStringPool()
StringPool & llvm::dwarf_linker::parallel::LinkingGlobalData::getStringPool () inline
Returns global string pool.
Definition at line 96 of file DWARFLinkerGlobalData.h.
References Strings.
Referenced by llvm::dwarf_linker::parallel::DWARFLinkerImpl::cleanupDataAfterDWARFOutputIsWritten(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneScalarAttr(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneStringAttr(), llvm::dwarf_linker::parallel::TypeUnit::createDIETree(), llvm::dwarf_linker::parallel::SectionDescriptor::emitString(), llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::save(), and llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::saveObjC().
getTargetTriple()
std::optional< std::reference_wrapper< const Triple > > llvm::dwarf_linker::parallel::LinkingGlobalData::getTargetTriple () inline
Optionally return target triple.
Definition at line 154 of file DWARFLinkerGlobalData.h.
References TargetTriple.
Referenced by llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::cloneAndEmitDebugFrame(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::emitCommonSectionsAndWriteCompileUnitsToTheOutput(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::emitInvariantSections(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::glueCompileUnitsAndWriteToTheOutput(), and llvm::dwarf_linker::parallel::DWARFLinkerImpl::link().
setErrorHandler()
void llvm::dwarf_linker::parallel::LinkingGlobalData::setErrorHandler (MessageHandlerTy Handler) inline
Set error handler.
Definition at line 118 of file DWARFLinkerGlobalData.h.
References ErrorHandler.
Referenced by llvm::dwarf_linker::parallel::DWARFLinkerImpl::DWARFLinkerImpl().
setTargetTriple()
void llvm::dwarf_linker::parallel::LinkingGlobalData::setTargetTriple (const Triple & TargetTriple) inline
Set target triple.
Definition at line 149 of file DWARFLinkerGlobalData.h.
References TargetTriple.
Referenced by llvm::dwarf_linker::parallel::DWARFLinkerImpl::setOutputDWARFHandler().
setTranslator()
void llvm::dwarf_linker::parallel::LinkingGlobalData::setTranslator (TranslatorFuncTy Translator) inline
Set translation function.
Definition at line 99 of file DWARFLinkerGlobalData.h.
References Translator.
Referenced by llvm::dwarf_linker::parallel::DWARFLinkerImpl::DWARFLinkerImpl().
setWarningHandler()
void llvm::dwarf_linker::parallel::LinkingGlobalData::setWarningHandler (MessageHandlerTy Handler) inline
Set warning handler.
Definition at line 115 of file DWARFLinkerGlobalData.h.
References WarningHandler.
Referenced by llvm::dwarf_linker::parallel::DWARFLinkerImpl::DWARFLinkerImpl().
translateString()
StringRef llvm::dwarf_linker::parallel::LinkingGlobalData::translateString (StringRef String) inline
Translate specified string.
Definition at line 104 of file DWARFLinkerGlobalData.h.
References llvm::String, and Translator.
Referenced by llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::add(), and llvm::dwarf_linker::parallel::SectionDescriptor::emitInplaceString().
warn() [1/2]
void llvm::dwarf_linker::parallel::LinkingGlobalData::warn (const Twine & Warning, StringRef Context, const DWARFDie * DIE = nullptr) inline
Report warning.
Definition at line 121 of file DWARFLinkerGlobalData.h.
References Context, llvm::Warning, and WarningHandler.
Referenced by llvm::dwarf_linker::parallel::DwarfUnit::error(), llvm::dwarf_linker::parallel::CompileUnit::error(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::isClangModuleRef(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::loadClangModule(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::validateAndUpdateOptions(), llvm::dwarf_linker::parallel::DwarfUnit::warn(), llvm::dwarf_linker::parallel::CompileUnit::warn(), and warn().
warn() [2/2]
void llvm::dwarf_linker::parallel::LinkingGlobalData::warn (Error Warning, StringRef Context, const DWARFDie * DIE = nullptr) inline
Report warning.
Definition at line 128 of file DWARFLinkerGlobalData.h.
References Context, llvm::handleAllErrors(), Info, warn(), and llvm::Warning.
Member Data Documentation
Allocator
llvm::parallel::PerThreadBumpPtrAllocator llvm::dwarf_linker::parallel::LinkingGlobalData::Allocator protected
Definition at line 162 of file DWARFLinkerGlobalData.h.
Referenced by getAllocator().
ErrorHandler
MessageHandlerTy llvm::dwarf_linker::parallel::LinkingGlobalData::ErrorHandler protected
Definition at line 167 of file DWARFLinkerGlobalData.h.
Referenced by error(), and setErrorHandler().
Options
DWARFLinkerOptions llvm::dwarf_linker::parallel::LinkingGlobalData::Options protected
Definition at line 165 of file DWARFLinkerGlobalData.h.
Referenced by llvm::dwarf_linker::parallel::DWARFLinkerImpl::addAccelTableKind(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::emitCommonSectionsAndWriteCompileUnitsToTheOutput(), getOptions(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::link(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setAllowNonDeterministicOutput(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setInputVerificationHandler(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setKeepFunctionForStatic(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setNoODR(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setNumThreads(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setObjectPrefixMap(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setPrependPath(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setStatistics(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setSwiftInterfacesMap(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setTargetDWARFVersion(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setUpdateIndexTablesOnly(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setVerbosity(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::setVerifyInputDWARF(), and llvm::dwarf_linker::parallel::DWARFLinkerImpl::validateAndUpdateOptions().
Strings
StringPool llvm::dwarf_linker::parallel::LinkingGlobalData::Strings protected
Definition at line 163 of file DWARFLinkerGlobalData.h.
Referenced by getStringPool().
TargetTriple
std::optional<Triple> llvm::dwarf_linker::parallel::LinkingGlobalData::TargetTriple protected
Triple for output data.
May be not set if generation of output data is not requested.
Definition at line 171 of file DWARFLinkerGlobalData.h.
Referenced by getTargetTriple(), and setTargetTriple().
Translator
TranslatorFuncTy llvm::dwarf_linker::parallel::LinkingGlobalData::Translator protected
Definition at line 164 of file DWARFLinkerGlobalData.h.
Referenced by setTranslator(), and translateString().
WarningHandler
MessageHandlerTy llvm::dwarf_linker::parallel::LinkingGlobalData::WarningHandler protected
Definition at line 166 of file DWARFLinkerGlobalData.h.
Referenced by setWarningHandler(), and warn().
The documentation for this class was generated from the following file:
lib/DWARFLinker/Parallel/DWARFLinkerGlobalData.h