LLVM: llvm::R600InstPrinter Class Reference
llvm::R600InstPrinter Class Reference
#include "Target/AMDGPU/MCTargetDesc/R600InstPrinter.h"
Public Member Functions
R600InstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
std::pair< const char *, uint64_t > getMnemonic (const MCInst *MI) override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
void printAbs (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printBankSwizzle (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printClamp (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printCT (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printKCache (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printLast (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printLiteral (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printMemOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printNeg (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printOMOD (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printRel (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printRSel (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printUpdateExecMask (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printUpdatePred (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printWrite (const MCInst *MI, unsigned OpNo, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
virtual std::pair< const char *, uint64_t > getMnemonic (const MCInst *MI)=0
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
virtual void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &OS)=0
Print the specified MCInst to the specified raw_ostream.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
virtual void printRegName (raw_ostream &OS, MCRegister Reg) const
Print the assembler register name.
bool getUseMarkup () const
void setUseMarkup (bool Value)
bool getUseColor () const
void setUseColor (bool Value)
WithMarkup markup (raw_ostream &OS, Markup M) const
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (MCRegister Reg)
Additional Inherited Members
Public Types inherited from llvm::MCInstPrinter
enum class Markup { Immediate , Register , Target , Memory }
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool UseColor = false
True if we are printing colored assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
Detailed Description
Definition at line 16 of file R600InstPrinter.h.
Constructor & Destructor Documentation
R600InstPrinter()
llvm::R600InstPrinter::R600InstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 18 of file R600InstPrinter.h.
Member Function Documentation
getMnemonic()
std::pair< const char *, uint64_t > llvm::R600InstPrinter::getMnemonic (const MCInst * MI) override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
getRegisterName()
static const char * llvm::R600InstPrinter::getRegisterName (MCRegister Reg) static
Referenced by printOperand().
printAbs()
void R600InstPrinter::printAbs (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 29 of file R600InstPrinter.cpp.
References MI, and llvm::AMDGPUInstPrinter::printIfSet().
printBankSwizzle()
void R600InstPrinter::printBankSwizzle (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 34 of file R600InstPrinter.cpp.
References MI.
printClamp()
void R600InstPrinter::printClamp (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 58 of file R600InstPrinter.cpp.
References MI, and llvm::AMDGPUInstPrinter::printIfSet().
printCT()
void R600InstPrinter::printCT (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 63 of file R600InstPrinter.cpp.
References MI.
printInst()
void R600InstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 21 of file R600InstPrinter.cpp.
References llvm::Address, MI, llvm::MCInstPrinter::printAnnotation(), and printInstruction().
printInstruction()
void llvm::R600InstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
Referenced by printInst().
printKCache()
void R600InstPrinter::printKCache (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 77 of file R600InstPrinter.cpp.
References MI.
printLast()
void R600InstPrinter::printLast (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 89 of file R600InstPrinter.cpp.
References MI, and llvm::AMDGPUInstPrinter::printIfSet().
printLiteral()
void R600InstPrinter::printLiteral (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 94 of file R600InstPrinter.cpp.
References assert(), llvm::MCInstPrinter::MAI, MI, and llvm::DWARFExpression::Operation::print().
printMemOperand()
void R600InstPrinter::printMemOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 129 of file R600InstPrinter.cpp.
References MI, and printOperand().
printNeg()
void R600InstPrinter::printNeg (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 107 of file R600InstPrinter.cpp.
References MI, and llvm::AMDGPUInstPrinter::printIfSet().
printOMOD()
void R600InstPrinter::printOMOD (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 112 of file R600InstPrinter.cpp.
References MI.
printOperand()
void R600InstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 136 of file R600InstPrinter.cpp.
References getRegisterName(), llvm::MCInstPrinter::MAI, and MI.
Referenced by printMemOperand().
printRel()
void R600InstPrinter::printRel (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 171 of file R600InstPrinter.cpp.
References MI, and llvm::AMDGPUInstPrinter::printIfSet().
printRSel()
void R600InstPrinter::printRSel (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 176 of file R600InstPrinter.cpp.
References MI.
printUpdateExecMask()
void R600InstPrinter::printUpdateExecMask (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 206 of file R600InstPrinter.cpp.
References MI, and llvm::AMDGPUInstPrinter::printIfSet().
printUpdatePred()
void R600InstPrinter::printUpdatePred (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 211 of file R600InstPrinter.cpp.
References MI, and llvm::AMDGPUInstPrinter::printIfSet().
printWrite()
void R600InstPrinter::printWrite (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 216 of file R600InstPrinter.cpp.
References MI.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/MCTargetDesc/R600InstPrinter.h
lib/Target/AMDGPU/MCTargetDesc/R600InstPrinter.cpp