LLVM: llvm::object::ELFObjectFile< ELFT > Class Template Reference
llvm::object::ELFObjectFile< ELFT > Class Template Reference
#include "llvm/Object/ELFObjectFile.h"
Public Member Functions
SectionRef toSectionRef (const Elf_Shdr *Sec) const
ELFSymbolRef toSymbolRef (const Elf_Shdr *SymTable, unsigned SymbolNum) const
bool IsContentValid () const
ELFObjectFile (ELFObjectFile< ELFT > &&Other)
const Elf_Rel * getRel (DataRefImpl Rel) const
const Elf_Rela * getRela (DataRefImpl Rela) const
Expected< const Elf_Sym * > getSymbol (DataRefImpl Sym) const
const Elf_Shdr * getRelSection (DataRefImpl Rel) const
Get the relocation section that contains Rel.
const Elf_Shdr * getSection (DataRefImpl Sec) const
basic_symbol_iterator symbol_begin () const override
basic_symbol_iterator symbol_end () const override
bool is64Bit () const override
elf_symbol_iterator dynamic_symbol_begin () const
elf_symbol_iterator dynamic_symbol_end () const
section_iterator section_begin () const override
section_iterator section_end () const override
Expected< int64_t > getRelocationAddend (DataRefImpl Rel) const override
uint8_t getBytesInAddress () const override
The number of bytes used to represent an address in this object file format.
StringRef getFileFormatName () const override
Triple::ArchType getArch () const override
Triple::OSType getOS () const override
Expected< uint64_t > getStartAddress () const override
unsigned getPlatformFlags () const override
Returns platform-specific object flags, if any.
const ELFFile< ELFT > & getELFFile () const
bool isDyldType () const
elf_symbol_iterator_range getDynamicSymbolIterators () const override
bool isRelocatableObject () const override
True if this is a relocatable object (.o/.obj).
void createFakeSections ()
Public Member Functions inherited from llvm::object::ELFObjectFileBase
virtual elf_symbol_iterator_range getDynamicSymbolIterators () const =0
virtual unsigned getPlatformFlags () const =0
Returns platform-specific object flags, if any.
elf_symbol_iterator_range symbols () const
Expected< SubtargetFeatures > getFeatures () const override
std::optional< StringRef > tryGetCPUName () const override
void setARMSubArch (Triple &TheTriple) const override
virtual uint16_t getEType () const =0
virtual uint16_t getEMachine () const =0
std::vector< ELFPltEntry > getPltEntries () const
Expected< std::vector< VersionEntry > > readDynsymVersions () const
Returns a vector containing a symbol version for each dynamic symbol.
Expected< std::vector< BBAddrMap > > readBBAddrMap (std::optional< unsigned > TextSectionIndex=std::nullopt, std::vector< PGOAnalysisMap > *PGOAnalyses=nullptr) const
Returns a vector of all BB address maps in the object file.
Public Member Functions inherited from llvm::object::ObjectFile
ObjectFile ()=delete
ObjectFile (const ObjectFile &other)=delete
uint64_t getCommonSymbolSize (DataRefImpl Symb) const
virtual std::vector< SectionRef > dynamic_relocation_sections () const
symbol_iterator_range symbols () const
virtual section_iterator section_begin () const =0
virtual section_iterator section_end () const =0
section_iterator_range sections () const
virtual bool hasDebugInfo () const
virtual uint8_t getBytesInAddress () const =0
The number of bytes used to represent an address in this object file format.
virtual StringRef getFileFormatName () const =0
virtual Triple::ArchType getArch () const =0
virtual Triple::OSType getOS () const
virtual Expected< SubtargetFeatures > getFeatures () const =0
virtual std::optional< StringRef > tryGetCPUName () const
virtual void setARMSubArch (Triple &TheTriple) const
virtual Expected< uint64_t > getStartAddress () const
Triple makeTriple () const
Create a triple from the data in this object file.
virtual StringRef mapDebugSectionName (StringRef Name) const
Maps a debug section name to a standard DWARF section name.
virtual bool isRelocatableObject () const =0
True if this is a relocatable object (.o/.obj).
bool isReflectionSectionStrippable (llvm::binaryformat::Swift5ReflectionSectionKind ReflectionSectionKind) const
True if the reflection section can be stripped by the linker.
Public Member Functions inherited from llvm::object::SymbolicFile
SymbolicFile (unsigned int Type, MemoryBufferRef Source)
~SymbolicFile () override
virtual void moveSymbolNext (DataRefImpl &Symb) const =0
virtual Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const =0
virtual Expected< uint32_t > getSymbolFlags (DataRefImpl Symb) const =0
virtual basic_symbol_iterator symbol_begin () const =0
virtual basic_symbol_iterator symbol_end () const =0
virtual bool is64Bit () const =0
basic_symbol_iterator_range symbols () const
Public Member Functions inherited from llvm::object::Binary
Binary ()=delete
Binary (const Binary &other)=delete
virtual ~Binary ()
virtual Error initContent ()
StringRef getData () const
StringRef getFileName () const
MemoryBufferRef getMemoryBufferRef () const
unsigned int getType () const
bool isObject () const
bool isSymbolic () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isTapiUniversal () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isXCOFF () const
bool isWasm () const
bool isOffloadFile () const
bool isCOFFImportFile () const
bool isIR () const
bool isGOFF () const
bool isMinidump () const
bool isTapiFile () const
bool isLittleEndian () const
bool isWinRes () const
Triple::ObjectFormatType getTripleObjectFormat () const
Static Public Member Functions
static Expected< ELFObjectFile< ELFT > > create (MemoryBufferRef Object, bool InitContent=true)
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::ELFObjectFileBase
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::ObjectFile
static Expected< OwningBinary< ObjectFile > > createObjectFile (StringRef ObjectPath)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object, llvm::file_magic Type, bool InitContent=true)
static Expected< std::unique_ptr< ObjectFile > > createObjectFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static Expected< std::unique_ptr< COFFObjectFile > > createCOFFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< ObjectFile > > createXCOFFObjectFile (MemoryBufferRef Object, unsigned FileType)
static Expected< std::unique_ptr< ObjectFile > > createELFObjectFile (MemoryBufferRef Object, bool InitContent=true)
static Expected< std::unique_ptr< MachOObjectFile > > createMachOObjectFile (MemoryBufferRef Object, uint32_t UniversalCputype=0, uint32_t UniversalIndex=0, size_t MachOFilesetEntryOffset=0)
Create a MachOObjectFile instance from a given buffer.
static Expected< std::unique_ptr< ObjectFile > > createGOFFObjectFile (MemoryBufferRef Object)
static Expected< std::unique_ptr< WasmObjectFile > > createWasmObjectFile (MemoryBufferRef Object)
Static Public Member Functions inherited from llvm::object::SymbolicFile
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object, llvm::file_magic Type, LLVMContext *Context, bool InitContent=true)
static Expected< std::unique_ptr< SymbolicFile > > createSymbolicFile (MemoryBufferRef Object)
static bool classof (const Binary *v)
static bool isSymbolicFile (file_magic Type, const LLVMContext *Context)
Static Public Member Functions inherited from llvm::object::Binary
static Error checkOffset (MemoryBufferRef M, uintptr_t Addr, const uint64_t Size)
Protected Member Functions
Error initContent () override
void moveSymbolNext (DataRefImpl &Symb) const override
Expected< StringRef > getSymbolName (DataRefImpl Symb) const override
Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const override
uint64_t getSymbolValueImpl (DataRefImpl Symb) const override
uint32_t getSymbolAlignment (DataRefImpl Symb) const override
uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const override
Expected< uint32_t > getSymbolFlags (DataRefImpl Symb) const override
uint8_t getSymbolBinding (DataRefImpl Symb) const override
uint8_t getSymbolOther (DataRefImpl Symb) const override
uint8_t getSymbolELFType (DataRefImpl Symb) const override
Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const override
Expected< section_iterator > getSymbolSection (const Elf_Sym *Symb, const Elf_Shdr *SymTab) const
Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const override
void moveSectionNext (DataRefImpl &Sec) const override
Expected< StringRef > getSectionName (DataRefImpl Sec) const override
uint64_t getSectionAddress (DataRefImpl Sec) const override
uint64_t getSectionIndex (DataRefImpl Sec) const override
uint64_t getSectionSize (DataRefImpl Sec) const override
Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const override
uint64_t getSectionAlignment (DataRefImpl Sec) const override
bool isSectionCompressed (DataRefImpl Sec) const override
bool isSectionText (DataRefImpl Sec) const override
bool isSectionData (DataRefImpl Sec) const override
bool isSectionBSS (DataRefImpl Sec) const override
bool isSectionVirtual (DataRefImpl Sec) const override
bool isBerkeleyText (DataRefImpl Sec) const override
bool isBerkeleyData (DataRefImpl Sec) const override
bool isDebugSection (DataRefImpl Sec) const override
relocation_iterator section_rel_begin (DataRefImpl Sec) const override
relocation_iterator section_rel_end (DataRefImpl Sec) const override
std::vector< SectionRef > dynamic_relocation_sections () const override
Expected< section_iterator > getRelocatedSection (DataRefImpl Sec) const override
void moveRelocationNext (DataRefImpl &Rel) const override
uint64_t getRelocationOffset (DataRefImpl Rel) const override
symbol_iterator getRelocationSymbol (DataRefImpl Rel) const override
uint64_t getRelocationType (DataRefImpl Rel) const override
void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const override
uint32_t getSectionType (DataRefImpl Sec) const override
uint64_t getSectionFlags (DataRefImpl Sec) const override
uint64_t getSectionOffset (DataRefImpl Sec) const override
StringRef getRelocationTypeName (uint32_t Type) const
DataRefImpl toDRI (const Elf_Shdr *SymTable, unsigned SymbolNum) const
const Elf_Shdr * toELFShdrIter (DataRefImpl Sec) const
DataRefImpl toDRI (const Elf_Shdr *Sec) const
DataRefImpl toDRI (const Elf_Dyn *Dyn) const
bool isExportedToOtherDSO (const Elf_Sym *ESym) const
Error getBuildAttributes (ELFAttributeParser &Attributes) const override
Protected Member Functions inherited from llvm::object::ELFObjectFileBase
ELFObjectFileBase (unsigned int Type, MemoryBufferRef Source)
virtual uint64_t getSymbolSize (DataRefImpl Symb) const =0
virtual uint8_t getSymbolBinding (DataRefImpl Symb) const =0
virtual uint8_t getSymbolOther (DataRefImpl Symb) const =0
virtual uint8_t getSymbolELFType (DataRefImpl Symb) const =0
virtual uint32_t getSectionType (DataRefImpl Sec) const =0
virtual uint64_t getSectionFlags (DataRefImpl Sec) const =0
virtual uint64_t getSectionOffset (DataRefImpl Sec) const =0
virtual Expected< int64_t > getRelocationAddend (DataRefImpl Rel) const =0
virtual Error getBuildAttributes (ELFAttributeParser &Attributes) const =0
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBufferRef Source)
const uint8_t * base () const
virtual Expected< StringRef > getSymbolName (DataRefImpl Symb) const =0
Error printSymbolName (raw_ostream &OS, DataRefImpl Symb) const override
virtual Expected< uint64_t > getSymbolAddress (DataRefImpl Symb) const =0
virtual uint64_t getSymbolValueImpl (DataRefImpl Symb) const =0
virtual uint32_t getSymbolAlignment (DataRefImpl Symb) const
virtual uint64_t getCommonSymbolSizeImpl (DataRefImpl Symb) const =0
virtual Expected< SymbolRef::Type > getSymbolType (DataRefImpl Symb) const =0
virtual Expected< section_iterator > getSymbolSection (DataRefImpl Symb) const =0
virtual void moveSectionNext (DataRefImpl &Sec) const =0
virtual Expected< StringRef > getSectionName (DataRefImpl Sec) const =0
virtual uint64_t getSectionAddress (DataRefImpl Sec) const =0
virtual uint64_t getSectionIndex (DataRefImpl Sec) const =0
virtual uint64_t getSectionSize (DataRefImpl Sec) const =0
virtual Expected< ArrayRef< uint8_t > > getSectionContents (DataRefImpl Sec) const =0
virtual uint64_t getSectionAlignment (DataRefImpl Sec) const =0
virtual bool isSectionCompressed (DataRefImpl Sec) const =0
virtual bool isSectionText (DataRefImpl Sec) const =0
virtual bool isSectionData (DataRefImpl Sec) const =0
virtual bool isSectionBSS (DataRefImpl Sec) const =0
virtual bool isSectionVirtual (DataRefImpl Sec) const =0
virtual bool isSectionBitcode (DataRefImpl Sec) const
virtual bool isSectionStripped (DataRefImpl Sec) const
virtual bool isBerkeleyText (DataRefImpl Sec) const
virtual bool isBerkeleyData (DataRefImpl Sec) const
virtual bool isDebugSection (DataRefImpl Sec) const
virtual relocation_iterator section_rel_begin (DataRefImpl Sec) const =0
virtual relocation_iterator section_rel_end (DataRefImpl Sec) const =0
virtual Expected< section_iterator > getRelocatedSection (DataRefImpl Sec) const
virtual void moveRelocationNext (DataRefImpl &Rel) const =0
virtual uint64_t getRelocationOffset (DataRefImpl Rel) const =0
virtual symbol_iterator getRelocationSymbol (DataRefImpl Rel) const =0
virtual uint64_t getRelocationType (DataRefImpl Rel) const =0
virtual void getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const =0
virtual llvm::binaryformat::Swift5ReflectionSectionKind mapReflectionSectionNameToEnumValue (StringRef SectionName) const
Expected< uint64_t > getSymbolValue (DataRefImpl Symb) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBufferRef Source)
Protected Attributes
ELFFile< ELFT > EF
const Elf_Shdr * DotDynSymSec = nullptr
const Elf_Shdr * DotSymtabSec = nullptr
const Elf_Shdr * DotSymtabShndxSec = nullptr
bool isDyldELFObject = false
Protected Attributes inherited from llvm::object::Binary
MemoryBufferRef Data
Additional Inherited Members
Public Types inherited from llvm::object::ELFObjectFileBase
using elf_symbol_iterator_range = iterator_range< elf_symbol_iterator >
Public Types inherited from llvm::object::ObjectFile
using symbol_iterator_range = iterator_range< symbol_iterator >
using section_iterator_range = iterator_range< section_iterator >
Public Types inherited from llvm::object::SymbolicFile
using basic_symbol_iterator_range = iterator_range< basic_symbol_iterator >
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive , ID_MachOUniversalBinary , ID_COFFImportFile , ID_IR ,
ID_TapiUniversal , ID_TapiFile , ID_Minidump , ID_WinRes ,
ID_Offload , ID_StartObjects , ID_COFF , ID_XCOFF32 ,
ID_XCOFF64 , ID_ELF32L , ID_ELF32B , ID_ELF64L ,
ID_ELF64B , ID_MachO32L , ID_MachO32B , ID_MachO64L ,
ID_MachO64B , ID_GOFF , ID_Wasm , ID_EndObjects
}
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Detailed Description
template<class ELFT>
class llvm::object::ELFObjectFile< ELFT >
Definition at line 251 of file ELFObjectFile.h.
Constructor & Destructor Documentation
ELFObjectFile()
template<class ELFT > llvm::object::ELFObjectFile< ELFT >::ELFObjectFile (ELFObjectFile< ELFT > && Other)
Definition at line 1145 of file ELFObjectFile.h.
Member Function Documentation
classof()
template<class ELFT > static bool llvm::object::ELFObjectFile< ELFT >::classof (const Binary * v) inline static
Definition at line 466 of file ELFObjectFile.h.
References llvm::object::Binary::getELFType(), and llvm::little.
create()
template<class ELFT > Expected< ELFObjectFile< ELFT > > llvm::object::ELFObjectFile< ELFT >::create (MemoryBufferRef Object, bool InitContent = true) static
Definition at line 1119 of file ELFObjectFile.h.
References llvm::object::ELFFile< ELFT >::create(), E, and llvm::object::ELFObjectFile< ELFT >::initContent().
Referenced by createPtr().
createFakeSections()
template<class ELFT > void llvm::object::ELFObjectFile< ELFT >::createFakeSections () inline
Definition at line 476 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF.
dynamic_relocation_sections()
template<class ELFT > std::vector< SectionRef > llvm::object::ELFObjectFile< ELFT >::dynamic_relocation_sections override protected virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 928 of file ELFObjectFile.h.
References llvm::Dynamic, llvm::is_contained(), and llvm::ELF::SHT_DYNAMIC.
dynamic_symbol_begin()
template<class ELFT > elf_symbol_iterator llvm::object::ELFObjectFile< ELFT >::dynamic_symbol_begin
Definition at line 1167 of file ELFObjectFile.h.
dynamic_symbol_end()
template<class ELFT > elf_symbol_iterator llvm::object::ELFObjectFile< ELFT >::dynamic_symbol_end
Definition at line 1177 of file ELFObjectFile.h.
References Sym.
getArch()
template<class ELFT > Triple::ArchType llvm::object::ELFObjectFile< ELFT >::getArch override virtual
Implements llvm::object::ObjectFile.
Definition at line 1286 of file ELFObjectFile.h.
References llvm::Triple::aarch64, llvm::Triple::aarch64_be, llvm::Triple::amdgcn, llvm::Triple::arm, llvm::Triple::avr, llvm::Triple::bpfeb, llvm::Triple::bpfel, llvm::Triple::csky, llvm::ELF::EF_AMDGPU_MACH, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_FIRST, llvm::ELF::EF_AMDGPU_MACH_AMDGCN_LAST, llvm::ELF::EF_AMDGPU_MACH_R600_FIRST, llvm::ELF::EF_AMDGPU_MACH_R600_LAST, llvm::ELF::EI_CLASS, llvm::ELF::ELFCLASS32, llvm::ELF::ELFCLASS64, llvm::ELF::EM_386, llvm::ELF::EM_68K, llvm::ELF::EM_AARCH64, llvm::ELF::EM_AMDGPU, llvm::ELF::EM_ARM, llvm::ELF::EM_AVR, llvm::ELF::EM_BPF, llvm::ELF::EM_CSKY, llvm::ELF::EM_CUDA, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_IAMCU, llvm::ELF::EM_LANAI, llvm::ELF::EM_LOONGARCH, llvm::ELF::EM_MIPS, llvm::ELF::EM_MSP430, llvm::ELF::EM_PPC, llvm::ELF::EM_PPC64, llvm::ELF::EM_RISCV, llvm::ELF::EM_S390, llvm::ELF::EM_SPARC, llvm::ELF::EM_SPARC32PLUS, llvm::ELF::EM_SPARCV9, llvm::ELF::EM_VE, llvm::ELF::EM_X86_64, llvm::ELF::EM_XTENSA, llvm::Triple::hexagon, llvm::Triple::lanai, llvm::little, llvm::Triple::loongarch32, llvm::Triple::loongarch64, llvm::Triple::m68k, llvm::Triple::mips, llvm::Triple::mips64, llvm::Triple::mips64el, llvm::Triple::mipsel, llvm::Triple::msp430, llvm::Triple::nvptx, llvm::Triple::nvptx64, llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::Triple::ppcle, llvm::Triple::r600, llvm::report_fatal_error(), llvm::Triple::riscv32, llvm::Triple::riscv64, llvm::Triple::sparc, llvm::Triple::sparcel, llvm::Triple::sparcv9, llvm::Triple::systemz, llvm::Triple::UnknownArch, llvm::Triple::ve, llvm::Triple::x86, llvm::Triple::x86_64, and llvm::Triple::xtensa.
getBuildAttributes()
template<class ELFT > Error llvm::object::ELFObjectFile< ELFT >::getBuildAttributes (ELFAttributeParser & Attributes) const inline override protected virtual
Implements llvm::object::ELFObjectFileBase.
Definition at line 388 of file ELFObjectFile.h.
References Attributes, E, llvm::object::ELFObjectFile< ELFT >::EF, llvm::ELFAttrs::Format_Version, llvm::ELF::SHT_ARM_ATTRIBUTES, llvm::ELF::SHT_RISCV_ATTRIBUTES, and llvm::Error::success().
getBytesInAddress()
template<class ELFT > uint8_t llvm::object::ELFObjectFile< ELFT >::getBytesInAddress () const override virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 1202 of file ELFObjectFile.h.
Referenced by llvm::object::ELFObjectFile< ELFT >::is64Bit().
getCommonSymbolSizeImpl()
template<class ELFT > uint64_t llvm::object::ELFObjectFile< ELFT >::getCommonSymbolSizeImpl (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 657 of file ELFObjectFile.h.
getDynamicSymbolIterators()
template<class ELFT > ELFObjectFileBase::elf_symbol_iterator_range llvm::object::ELFObjectFile< ELFT >::getDynamicSymbolIterators override virtual
Implements llvm::object::ELFObjectFileBase.
Definition at line 1422 of file ELFObjectFile.h.
References llvm::make_range().
getELFFile()
template<class ELFT > const ELFFile< ELFT > & llvm::object::ELFObjectFile< ELFT >::getELFFile () const inline
Definition at line 463 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF.
Referenced by llvm::ifs::buildStub().
getFileFormatName()
template<class ELFT > StringRef llvm::object::ELFObjectFile< ELFT >::getFileFormatName override virtual
Implements llvm::object::ObjectFile.
Definition at line 1207 of file ELFObjectFile.h.
References llvm::ELF::EI_CLASS, llvm::ELF::ELFCLASS32, llvm::ELF::ELFCLASS64, llvm::ELF::EM_386, llvm::ELF::EM_68K, llvm::ELF::EM_AARCH64, llvm::ELF::EM_AMDGPU, llvm::ELF::EM_ARM, llvm::ELF::EM_AVR, llvm::ELF::EM_BPF, llvm::ELF::EM_CSKY, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_IAMCU, llvm::ELF::EM_LANAI, llvm::ELF::EM_LOONGARCH, llvm::ELF::EM_MIPS, llvm::ELF::EM_MSP430, llvm::ELF::EM_PPC, llvm::ELF::EM_PPC64, llvm::ELF::EM_RISCV, llvm::ELF::EM_S390, llvm::ELF::EM_SPARC, llvm::ELF::EM_SPARC32PLUS, llvm::ELF::EM_SPARCV9, llvm::ELF::EM_VE, llvm::ELF::EM_X86_64, llvm::ELF::EM_XTENSA, llvm::little, and llvm::report_fatal_error().
getOS()
template<class ELFT > Triple::OSType llvm::object::ELFObjectFile< ELFT >::getOS override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 1386 of file ELFObjectFile.h.
References llvm::Triple::AIX, llvm::Triple::AMDHSA, llvm::Triple::AMDPAL, llvm::Triple::CUDA, llvm::ELF::EI_OSABI, llvm::ELF::ELFOSABI_AIX, llvm::ELF::ELFOSABI_AMDGPU_HSA, llvm::ELF::ELFOSABI_AMDGPU_MESA3D, llvm::ELF::ELFOSABI_AMDGPU_PAL, llvm::ELF::ELFOSABI_CUDA, llvm::ELF::ELFOSABI_FREEBSD, llvm::ELF::ELFOSABI_HURD, llvm::ELF::ELFOSABI_LINUX, llvm::ELF::ELFOSABI_NETBSD, llvm::ELF::ELFOSABI_OPENBSD, llvm::ELF::ELFOSABI_SOLARIS, llvm::Triple::FreeBSD, llvm::Triple::Hurd, llvm::Triple::Linux, llvm::Triple::Mesa3D, llvm::Triple::NetBSD, llvm::Triple::OpenBSD, llvm::Triple::Solaris, and llvm::Triple::UnknownOS.
getPlatformFlags()
template<class ELFT > unsigned llvm::object::ELFObjectFile< ELFT >::getPlatformFlags () const inline override virtual
Returns platform-specific object flags, if any.
Implements llvm::object::ELFObjectFileBase.
Definition at line 461 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF.
getRel()
template<class ELFT > const ELFObjectFile< ELFT >::Elf_Rel * llvm::object::ELFObjectFile< ELFT >::getRel (DataRefImpl Rel) const
Definition at line 1099 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::a, assert(), llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, llvm::errorToErrorCode(), llvm::report_fatal_error(), and llvm::ELF::SHT_REL.
getRela()
template<class ELFT > const ELFObjectFile< ELFT >::Elf_Rela * llvm::object::ELFObjectFile< ELFT >::getRela (DataRefImpl Rela) const
Definition at line 1109 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::a, assert(), llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, llvm::errorToErrorCode(), llvm::report_fatal_error(), and llvm::ELF::SHT_RELA.
getRelocatedSection()
template<class ELFT > Expected< section_iterator > llvm::object::ELFObjectFile< ELFT >::getRelocatedSection (DataRefImpl Sec) const override protected virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 1022 of file ELFObjectFile.h.
References llvm::object::getSection(), llvm::ELF::SHT_REL, llvm::ELF::SHT_RELA, and llvm::Expected< T >::takeError().
getRelocationAddend()
template<class ELFT > Expected< int64_t > llvm::object::ELFObjectFile< ELFT >::getRelocationAddend (DataRefImpl Rel) const override virtual
Implements llvm::object::ELFObjectFileBase.
Definition at line 1091 of file ELFObjectFile.h.
References llvm::object::createError(), and llvm::ELF::SHT_RELA.
getRelocationOffset()
template<class ELFT > uint64_t llvm::object::ELFObjectFile< ELFT >::getRelocationOffset (DataRefImpl Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1060 of file ELFObjectFile.h.
References llvm::ELF::SHT_REL.
getRelocationSymbol()
template<class ELFT > symbol_iterator llvm::object::ELFObjectFile< ELFT >::getRelocationSymbol (DataRefImpl Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1042 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, and llvm::ELF::SHT_REL.
getRelocationType()
template<class ELFT > uint64_t llvm::object::ELFObjectFile< ELFT >::getRelocationType (DataRefImpl Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1069 of file ELFObjectFile.h.
References llvm::ELF::SHT_REL.
getRelocationTypeName() [1/2]
template<class ELFT > void llvm::object::ELFObjectFile< ELFT >::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1083 of file ELFObjectFile.h.
getRelocationTypeName() [2/2]
template<class ELFT > StringRef llvm::object::ELFObjectFile< ELFT >::getRelocationTypeName (uint32_t Type) const protected
Definition at line 1078 of file ELFObjectFile.h.
References llvm::object::getELFRelocationTypeName().
getRelSection()
template<class ELFT > const Elf_Shdr * llvm::object::ELFObjectFile< ELFT >::getRelSection (DataRefImpl Rel) const inline
Get the relocation section that contains Rel.
Definition at line 430 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, llvm::object::ELFObjectFile< ELFT >::EF, llvm::errorToErrorCode(), and llvm::report_fatal_error().
getSection()
template<class ELFT > const Elf_Shdr * llvm::object::ELFObjectFile< ELFT >::getSection (DataRefImpl Sec) const inline
Definition at line 438 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::p.
getSectionAddress()
template<class ELFT > uint64_t llvm::object::ELFObjectFile< ELFT >::getSectionAddress (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 863 of file ELFObjectFile.h.
References llvm::object::getSection().
getSectionAlignment()
template<class ELFT > uint64_t llvm::object::ELFObjectFile< ELFT >::getSectionAlignment (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 897 of file ELFObjectFile.h.
References llvm::object::getSection().
getSectionContents()
template<class ELFT > Expected< ArrayRef< uint8_t > > llvm::object::ELFObjectFile< ELFT >::getSectionContents (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 885 of file ELFObjectFile.h.
References E, llvm::object::getSection(), and llvm::ELF::SHT_NOBITS.
getSectionFlags()
template<class ELFT > uint64_t llvm::object::ELFObjectFile< ELFT >::getSectionFlags (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ELFObjectFileBase.
Definition at line 549 of file ELFObjectFile.h.
References llvm::object::getSection().
getSectionIndex()
template<class ELFT > uint64_t llvm::object::ELFObjectFile< ELFT >::getSectionIndex (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 868 of file ELFObjectFile.h.
References llvm::First, llvm::object::getSection(), and llvm::handleAllErrors().
getSectionName()
template<class ELFT > Expected< StringRef > llvm::object::ELFObjectFile< ELFT >::getSectionName (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 858 of file ELFObjectFile.h.
References llvm::object::getSection().
getSectionOffset()
template<class ELFT > uint64_t llvm::object::ELFObjectFile< ELFT >::getSectionOffset (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ELFObjectFileBase.
Definition at line 559 of file ELFObjectFile.h.
References llvm::object::getSection().
getSectionSize()
template<class ELFT > uint64_t llvm::object::ELFObjectFile< ELFT >::getSectionSize (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 879 of file ELFObjectFile.h.
References llvm::object::getSection().
getSectionType()
template<class ELFT > uint32_t llvm::object::ELFObjectFile< ELFT >::getSectionType (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ELFObjectFileBase.
Definition at line 554 of file ELFObjectFile.h.
References llvm::object::getSection().
getStartAddress()
template<class ELFT > Expected< uint64_t > llvm::object::ELFObjectFile< ELFT >::getStartAddress override virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 1416 of file ELFObjectFile.h.
getSymbol()
template<class ELFT > Expected< const Elf_Sym * > llvm::object::ELFObjectFile< ELFT >::getSymbol (DataRefImpl Sym) const inline
Definition at line 425 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, and Sym.
getSymbolAddress()
template<class ELFT > Expected< uint64_t > llvm::object::ELFObjectFile< ELFT >::getSymbolAddress (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 584 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, llvm::ELF::ET_REL, getSymbolValue(), llvm::ELF::SHN_ABS, llvm::ELF::SHN_COMMON, llvm::ELF::SHN_UNDEF, and llvm::Expected< T >::takeError().
getSymbolAlignment()
template<class ELFT > uint32_t llvm::object::ELFObjectFile< ELFT >::getSymbolAlignment (DataRefImpl Symb) const override protected virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 630 of file ELFObjectFile.h.
References llvm::report_fatal_error(), llvm::ELF::SHN_COMMON, and llvm::Expected< T >::takeError().
getSymbolBinding()
template<class ELFT > uint8_t llvm::object::ELFObjectFile< ELFT >::getSymbolBinding (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ELFObjectFileBase.
Definition at line 662 of file ELFObjectFile.h.
References llvm::report_fatal_error(), and llvm::Expected< T >::takeError().
getSymbolELFType()
template<class ELFT > uint8_t llvm::object::ELFObjectFile< ELFT >::getSymbolELFType (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ELFObjectFileBase.
Definition at line 678 of file ELFObjectFile.h.
References llvm::report_fatal_error(), and llvm::Expected< T >::takeError().
getSymbolFlags()
template<class ELFT > Expected< uint32_t > llvm::object::ELFObjectFile< ELFT >::getSymbolFlags (DataRefImpl Symb) const override protected virtual
Implements llvm::object::SymbolicFile.
Definition at line 711 of file ELFObjectFile.h.
References llvm::consumeError(), llvm::ELF::EM_AARCH64, llvm::ELF::EM_ARM, llvm::ELF::EM_CSKY, llvm::ELF::EM_RISCV, getSymbolName(), Name, llvm::object::BasicSymbolRef::SF_Absolute, llvm::object::BasicSymbolRef::SF_Common, llvm::object::BasicSymbolRef::SF_Exported, llvm::object::BasicSymbolRef::SF_FormatSpecific, llvm::object::BasicSymbolRef::SF_Global, llvm::object::BasicSymbolRef::SF_Hidden, llvm::object::BasicSymbolRef::SF_Indirect, llvm::object::BasicSymbolRef::SF_None, llvm::object::BasicSymbolRef::SF_Thumb, llvm::object::BasicSymbolRef::SF_Undefined, llvm::object::BasicSymbolRef::SF_Weak, llvm::ELF::SHN_ABS, llvm::ELF::SHN_COMMON, llvm::ELF::SHN_UNDEF, llvm::ELF::STB_LOCAL, llvm::ELF::STB_WEAK, llvm::ELF::STT_COMMON, llvm::ELF::STT_FILE, llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_SECTION, llvm::ELF::STV_HIDDEN, Sym, and llvm::Expected< T >::takeError().
getSymbolName()
template<class ELFT > Expected< StringRef > llvm::object::ELFObjectFile< ELFT >::getSymbolName (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 519 of file ELFObjectFile.h.
References Name, llvm::ELF::STT_SECTION, Sym, and llvm::Expected< T >::takeError().
getSymbolOther()
template<class ELFT > uint8_t llvm::object::ELFObjectFile< ELFT >::getSymbolOther (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ELFObjectFileBase.
Definition at line 670 of file ELFObjectFile.h.
References llvm::report_fatal_error(), and llvm::Expected< T >::takeError().
getSymbolSection() [1/2]
template<class ELFT > Expected< section_iterator > llvm::object::ELFObjectFile< ELFT >::getSymbolSection (const Elf_Sym * Symb, const Elf_Shdr * SymTab) const protected
Definition at line 813 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::p, and llvm::Expected< T >::takeError().
getSymbolSection() [2/2]
template<class ELFT > Expected< section_iterator > llvm::object::ELFObjectFile< ELFT >::getSymbolSection (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 840 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, and llvm::Expected< T >::takeError().
getSymbolType()
template<class ELFT > Expected< SymbolRef::Type > llvm::object::ELFObjectFile< ELFT >::getSymbolType (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 687 of file ELFObjectFile.h.
References llvm::object::SymbolRef::ST_Data, llvm::object::SymbolRef::ST_Debug, llvm::object::SymbolRef::ST_File, llvm::object::SymbolRef::ST_Function, llvm::object::SymbolRef::ST_Other, llvm::object::SymbolRef::ST_Unknown, llvm::ELF::STT_COMMON, llvm::ELF::STT_FILE, llvm::ELF::STT_FUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_SECTION, llvm::ELF::STT_TLS, and llvm::Expected< T >::takeError().
getSymbolValueImpl()
template<class ELFT > uint64_t llvm::object::ELFObjectFile< ELFT >::getSymbolValueImpl (DataRefImpl Symb) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 564 of file ELFObjectFile.h.
References llvm::ELF::EM_ARM, llvm::ELF::EM_MIPS, llvm::report_fatal_error(), llvm::ELF::SHN_ABS, llvm::ELF::STT_FUNC, and llvm::Expected< T >::takeError().
initContent()
template<class ELFT > Error llvm::object::ELFObjectFile< ELFT >::initContent override protected virtual
Reimplemented from llvm::object::Binary.
Definition at line 489 of file ELFObjectFile.h.
References llvm::ELF::SHT_DYNSYM, llvm::ELF::SHT_SYMTAB, llvm::ELF::SHT_SYMTAB_SHNDX, and llvm::Error::success().
Referenced by llvm::object::ELFObjectFile< ELFT >::create().
is64Bit()
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::is64Bit () const inline override virtual
Implements llvm::object::SymbolicFile.
Definition at line 445 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::getBytesInAddress().
isBerkeleyData()
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::isBerkeleyData (DataRefImpl Sec) const override protected virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 968 of file ELFObjectFile.h.
References llvm::object::getSection(), llvm::ELF::SHF_ALLOC, and llvm::ELF::SHT_NOBITS.
isBerkeleyText()
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::isBerkeleyText (DataRefImpl Sec) const override protected virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 961 of file ELFObjectFile.h.
References llvm::object::getSection(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_EXECINSTR, and llvm::ELF::SHF_WRITE.
IsContentValid()
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::IsContentValid () const inline
Definition at line 267 of file ELFObjectFile.h.
isDebugSection()
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::isDebugSection (DataRefImpl Sec) const override protected virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 975 of file ELFObjectFile.h.
References llvm::consumeError(), llvm::Expected< T >::get(), llvm::dwarf_linker::getSectionName(), and llvm::Expected< T >::takeError().
isDyldType()
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::isDyldType () const inline
Definition at line 465 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::isDyldELFObject.
isExportedToOtherDSO()
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::isExportedToOtherDSO (const Elf_Sym * ESym) const inline protected
Definition at line 375 of file ELFObjectFile.h.
References llvm::ELF::STB_GLOBAL, llvm::ELF::STB_GNU_UNIQUE, llvm::ELF::STB_WEAK, llvm::ELF::STV_DEFAULT, and llvm::ELF::STV_PROTECTED.
isRelocatableObject()
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::isRelocatableObject () const override virtual
True if this is a relocatable object (.o/.obj).
Implements llvm::object::ObjectFile.
Definition at line 1426 of file ELFObjectFile.h.
References llvm::ELF::ET_REL.
isSectionBSS()
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::isSectionBSS (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 920 of file ELFObjectFile.h.
References llvm::object::getSection(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_WRITE, and llvm::ELF::SHT_NOBITS.
isSectionCompressed()
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::isSectionCompressed (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 902 of file ELFObjectFile.h.
References llvm::object::getSection(), and llvm::ELF::SHF_COMPRESSED.
isSectionData()
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::isSectionData (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 912 of file ELFObjectFile.h.
References llvm::object::getSection(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_EXECINSTR, and llvm::ELF::SHT_PROGBITS.
isSectionText()
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::isSectionText (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 907 of file ELFObjectFile.h.
References llvm::object::getSection(), and llvm::ELF::SHF_EXECINSTR.
isSectionVirtual()
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::isSectionVirtual (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 956 of file ELFObjectFile.h.
References llvm::object::getSection(), and llvm::ELF::SHT_NOBITS.
moveRelocationNext()
template<class ELFT > void llvm::object::ELFObjectFile< ELFT >::moveRelocationNext (DataRefImpl & Rel) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1036 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::b, and llvm::object::DataRefImpl::d.
moveSectionNext()
template<class ELFT > void llvm::object::ELFObjectFile< ELFT >::moveSectionNext (DataRefImpl & Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 852 of file ELFObjectFile.h.
References llvm::object::getSection().
moveSymbolNext()
template<class ELFT > void llvm::object::ELFObjectFile< ELFT >::moveSymbolNext (DataRefImpl & Symb) const override protected virtual
Implements llvm::object::SymbolicFile.
Definition at line 485 of file ELFObjectFile.h.
References Sym.
section_begin()
template<class ELFT > section_iterator llvm::object::ELFObjectFile< ELFT >::section_begin override virtual
Implements llvm::object::ObjectFile.
Definition at line 1186 of file ELFObjectFile.h.
section_end()
template<class ELFT > section_iterator llvm::object::ELFObjectFile< ELFT >::section_end override virtual
Implements llvm::object::ObjectFile.
Definition at line 1194 of file ELFObjectFile.h.
section_rel_begin()
template<class ELFT > relocation_iterator llvm::object::ELFObjectFile< ELFT >::section_rel_begin (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 989 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, and llvm::object::DataRefImpl::p.
section_rel_end()
template<class ELFT > relocation_iterator llvm::object::ELFObjectFile< ELFT >::section_rel_end (DataRefImpl Sec) const override protected virtual
Implements llvm::object::ObjectFile.
Definition at line 1002 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, llvm::errorToErrorCode(), llvm::object::DataRefImpl::p, llvm::report_fatal_error(), llvm::ELF::SHT_REL, and llvm::ELF::SHT_RELA.
symbol_begin()
template<class ELFT > basic_symbol_iterator llvm::object::ELFObjectFile< ELFT >::symbol_begin override virtual
Implements llvm::object::SymbolicFile.
Definition at line 1150 of file ELFObjectFile.h.
References Sym.
symbol_end()
template<class ELFT > basic_symbol_iterator llvm::object::ELFObjectFile< ELFT >::symbol_end override virtual
Implements llvm::object::SymbolicFile.
Definition at line 1158 of file ELFObjectFile.h.
References Sym.
toDRI() [1/3]
template<class ELFT > DataRefImpl llvm::object::ELFObjectFile< ELFT >::toDRI (const Elf_Dyn * Dyn) const inline protected
Definition at line 369 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::p.
toDRI() [2/3]
template<class ELFT > DataRefImpl llvm::object::ELFObjectFile< ELFT >::toDRI (const Elf_Shdr * Sec) const inline protected
Definition at line 363 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::p.
toDRI() [3/3]
template<class ELFT > DataRefImpl llvm::object::ELFObjectFile< ELFT >::toDRI (const Elf_Shdr * SymTable, unsigned SymbolNum) const inline protected
Definition at line 334 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::a, assert(), llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, llvm::object::ELFObjectFile< ELFT >::EF, llvm::ELF::SHT_DYNSYM, and llvm::ELF::SHT_SYMTAB.
Referenced by llvm::object::ELFObjectFile< ELFT >::toSectionRef(), and llvm::object::ELFObjectFile< ELFT >::toSymbolRef().
toELFShdrIter()
template<class ELFT > const Elf_Shdr * llvm::object::ELFObjectFile< ELFT >::toELFShdrIter (DataRefImpl Sec) const inline protected
Definition at line 359 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::p.
toSectionRef()
template<class ELFT > SectionRef llvm::object::ELFObjectFile< ELFT >::toSectionRef (const Elf_Shdr * Sec) const inline
Definition at line 259 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::toDRI().
toSymbolRef()
template<class ELFT > ELFSymbolRef llvm::object::ELFObjectFile< ELFT >::toSymbolRef (const Elf_Shdr * SymTable, unsigned SymbolNum) const inline
Definition at line 263 of file ELFObjectFile.h.
References llvm::object::ELFObjectFileBase::ELFSymbolRef, and llvm::object::ELFObjectFile< ELFT >::toDRI().
Member Data Documentation
DotDynSymSec
template<class ELFT > const Elf_Shdr* llvm::object::ELFObjectFile< ELFT >::DotDynSymSec = nullptr protected
Definition at line 279 of file ELFObjectFile.h.
DotSymtabSec
template<class ELFT > const Elf_Shdr* llvm::object::ELFObjectFile< ELFT >::DotSymtabSec = nullptr protected
Definition at line 280 of file ELFObjectFile.h.
DotSymtabShndxSec
template<class ELFT > const Elf_Shdr* llvm::object::ELFObjectFile< ELFT >::DotSymtabShndxSec = nullptr protected
Definition at line 281 of file ELFObjectFile.h.
EF
template<class ELFT > ELFFile<ELFT> llvm::object::ELFObjectFile< ELFT >::EF protected
Definition at line 277 of file ELFObjectFile.h.
Referenced by llvm::object::ELFObjectFile< ELFT >::createFakeSections(), llvm::object::ELFObjectFile< ELFT >::getBuildAttributes(), llvm::object::ELFObjectFile< ELFT >::getELFFile(), llvm::object::ELFObjectFile< ELFT >::getPlatformFlags(), llvm::object::ELFObjectFile< ELFT >::getRelSection(), llvm::object::ELFObjectFile< ELFT >::getSymbol(), and llvm::object::ELFObjectFile< ELFT >::toDRI().
isDyldELFObject
template<class ELFT > bool llvm::object::ELFObjectFile< ELFT >::isDyldELFObject = false protected
Definition at line 415 of file ELFObjectFile.h.
Referenced by llvm::object::ELFObjectFile< ELFT >::isDyldType().
The documentation for this class was generated from the following file:
include/llvm/Object/ELFObjectFile.h