LLVM: llvm::ContextTrieNode Class Reference
llvm::ContextTrieNode Class Reference
#include "llvm/Transforms/IPO/SampleContextTracker.h"
Public Member Functions
ContextTrieNode (ContextTrieNode *Parent=nullptr, FunctionId FName=FunctionId(), FunctionSamples *FSamples=nullptr, LineLocation CallLoc={0, 0})
ContextTrieNode * getChildContext (const LineLocation &CallSite, FunctionId ChildName)
ContextTrieNode * getHottestChildContext (const LineLocation &CallSite)
ContextTrieNode * getOrCreateChildContext (const LineLocation &CallSite, FunctionId ChildName, bool AllowCreate=true)
void removeChildContext (const LineLocation &CallSite, FunctionId ChildName)
std::map< uint64_t, ContextTrieNode > & getAllChildContext ()
FunctionId getFuncName () const
FunctionSamples * getFunctionSamples () const
void setFunctionSamples (FunctionSamples *FSamples)
std::optional< uint32_t > getFunctionSize () const
void addFunctionSize (uint32_t FSize)
LineLocation getCallSiteLoc () const
ContextTrieNode * getParentContext () const
void setParentContext (ContextTrieNode *Parent)
void setCallSiteLoc (const LineLocation &Loc)
void dumpNode ()
void dumpTree ()
Detailed Description
Definition at line 34 of file SampleContextTracker.h.
Constructor & Destructor Documentation
ContextTrieNode()
llvm::ContextTrieNode::ContextTrieNode (ContextTrieNode * Parent = nullptr, FunctionId FName = FunctionId(), FunctionSamples * FSamples = nullptr, LineLocation CallLoc = {0, 0}) inline
Definition at line 36 of file SampleContextTracker.h.
Member Function Documentation
addFunctionSize()
void llvm::ContextTrieNode::addFunctionSize (uint32_t FSize)
Definition at line 130 of file SampleContextTracker.cpp.
dumpNode()
void llvm::ContextTrieNode::dumpNode ()
Definition at line 151 of file SampleContextTracker.cpp.
References llvm::dbgs().
dumpTree()
void llvm::ContextTrieNode::dumpTree ()
Definition at line 162 of file SampleContextTracker.cpp.
References llvm::dbgs().
Referenced by llvm::SampleContextTracker::dump().
getAllChildContext()
std::map< uint64_t, ContextTrieNode > & llvm::ContextTrieNode::getAllChildContext ()
Definition at line 112 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::getIndirectCalleeContextSamplesFor(), llvm::sampleprof::ProfiledCallGraph::ProfiledCallGraph(), and llvm::SampleContextTracker::promoteMergeContextSamplesTree().
getCallSiteLoc()
LineLocation llvm::ContextTrieNode::getCallSiteLoc () const
Definition at line 137 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::getContextString(), llvm::SampleContextTracker::getIndirectCalleeContextSamplesFor(), and llvm::SampleContextTracker::promoteMergeContextSamplesTree().
getChildContext()
ContextTrieNode * llvm::ContextTrieNode::getChildContext (const LineLocation & CallSite, FunctionId ChildName)
Definition at line 30 of file SampleContextTracker.cpp.
References llvm::sampleprof::FunctionId::empty(), llvm::sampleprof::FunctionSamples::getCallSiteHash(), and getHottestChildContext().
Referenced by llvm::SampleContextTracker::getOrCreateContextPath(), and llvm::SampleContextTracker::promoteMergeContextSamplesTree().
getFuncName()
FunctionId llvm::ContextTrieNode::getFuncName () const
Definition at line 116 of file SampleContextTracker.cpp.
getFunctionSamples()
FunctionSamples * llvm::ContextTrieNode::getFunctionSamples () const
Definition at line 118 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::getCalleeContextSamplesFor(), llvm::SampleContextTracker::getContextSamplesFor(), getHottestChildContext(), llvm::SampleContextTracker::getIndirectCalleeContextSamplesFor(), llvm::SampleContextTracker::promoteMergeContextSamplesTree(), and llvm::SampleContextTracker::SampleContextTracker().
getFunctionSize()
std::optional< uint32_t > llvm::ContextTrieNode::getFunctionSize () const
Definition at line 126 of file SampleContextTracker.cpp.
getHottestChildContext()
ContextTrieNode * llvm::ContextTrieNode::getHottestChildContext (const LineLocation & CallSite)
Definition at line 43 of file SampleContextTracker.cpp.
References getFunctionSamples(), and llvm::sampleprof::FunctionSamples::getTotalSamples().
Referenced by getChildContext().
getOrCreateChildContext()
ContextTrieNode * llvm::ContextTrieNode::getOrCreateChildContext (const LineLocation & CallSite, FunctionId ChildName, bool AllowCreate = true)
Definition at line 179 of file SampleContextTracker.cpp.
References assert(), and llvm::sampleprof::FunctionSamples::getCallSiteHash().
Referenced by llvm::SampleContextTracker::getOrCreateContextPath().
getParentContext()
ContextTrieNode * llvm::ContextTrieNode::getParentContext () const
Definition at line 139 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::getContextSamplesFor().
removeChildContext()
void llvm::ContextTrieNode::removeChildContext (const LineLocation & CallSite, FunctionId ChildName)
Definition at line 105 of file SampleContextTracker.cpp.
References llvm::sampleprof::FunctionSamples::getCallSiteHash().
setCallSiteLoc()
void llvm::ContextTrieNode::setCallSiteLoc (const LineLocation & Loc)
Definition at line 147 of file SampleContextTracker.cpp.
setFunctionSamples()
void llvm::ContextTrieNode::setFunctionSamples (FunctionSamples * FSamples)
Definition at line 122 of file SampleContextTracker.cpp.
Referenced by llvm::SampleContextTracker::SampleContextTracker().
setParentContext()
void llvm::ContextTrieNode::setParentContext (ContextTrieNode * Parent)
Definition at line 143 of file SampleContextTracker.cpp.
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/SampleContextTracker.h
lib/Transforms/IPO/SampleContextTracker.cpp