LLVM: llvm::InstrProfilingLoweringPass Class Reference
llvm::InstrProfilingLoweringPass Class Reference
Instrumentation based profiling lowering pass.
#include "llvm/Transforms/Instrumentation/InstrProfiling.h"
Public Member Functions
InstrProfilingLoweringPass ()=default
InstrProfilingLoweringPass (const InstrProfOptions &Options, bool IsCS=false)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< InstrProfilingLoweringPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< InstrProfilingLoweringPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Instrumentation based profiling lowering pass.
This pass lowers the profile instrumented code generated by FE or the IR based instrumentation pass.
Definition at line 25 of file InstrProfiling.h.
Constructor & Destructor Documentation
InstrProfilingLoweringPass() [1/2]
llvm::InstrProfilingLoweringPass::InstrProfilingLoweringPass () default
InstrProfilingLoweringPass() [2/2]
llvm::InstrProfilingLoweringPass::InstrProfilingLoweringPass (const InstrProfOptions & Options, bool IsCS = false) inline
Definition at line 33 of file InstrProfiling.h.
References Options.
Member Function Documentation
run()
PreservedAnalyses InstrProfilingLoweringPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 573 of file InstrProfiling.cpp.
References llvm::PreservedAnalyses::all(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::none().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Instrumentation/InstrProfiling.h
lib/Transforms/Instrumentation/InstrProfiling.cpp