LLVM: llvm::MachO::TextAPIWriter Class Reference
llvm::MachO::TextAPIWriter Class Reference
#include "llvm/TextAPI/TextAPIWriter.h"
Public Member Functions
TextAPIWriter ()=delete
Static Public Member Functions
static Error writeToStream (raw_ostream &OS, const InterfaceFile &File, const FileType FileKind=FileType::Invalid, bool Compact=false)
Write TAPI text file contents into stream.
static FileType parseFileType (const StringRef FT)
Get TAPI FileType from the input string.
Detailed Description
Definition at line 22 of file TextAPIWriter.h.
Constructor & Destructor Documentation
TextAPIWriter()
llvm::MachO::TextAPIWriter::TextAPIWriter () delete
Member Function Documentation
parseFileType()
static FileType llvm::MachO::TextAPIWriter::parseFileType (const StringRef FT) inline static
Get TAPI FileType from the input string.
Parameters
FT String of input to map to FileType.
Definition at line 40 of file TextAPIWriter.h.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::MachO::Invalid, llvm::MachO::TBD_V1, llvm::MachO::TBD_V2, llvm::MachO::TBD_V3, llvm::MachO::TBD_V4, and llvm::MachO::TBD_V5.
writeToStream()
Error TextAPIWriter::writeToStream (raw_ostream & OS, const InterfaceFile & File, const FileType FileKind = FileType::Invalid, bool Compact = false) static
Write TAPI text file contents into stream.
Parameters
OS Stream to write to.
File Library attributes to write as text file.
FileKind File format to write text file as. If not specified, it will read from File.
Compact Whether to limit whitespace in text file.
Definition at line 1137 of file TextStub.cpp.
References llvm::MachO::TextAPIContext::FileKind, llvm::MachO::Invalid, OS, llvm::MachO::TextAPIContext::Path, llvm::MachO::serializeInterfaceFileToJSON(), llvm::Error::success(), and llvm::MachO::TBD_V5.
The documentation for this class was generated from the following files:
include/llvm/TextAPI/TextAPIWriter.h
lib/TextAPI/TextStub.cpp