LLVM: llvm::CSKYConstantPoolConstant Class Reference
llvm::CSKYConstantPoolConstant Class Reference
CSKY-specific constant pool values for Constants, Functions, and BlockAddresses.
#include "Target/CSKY/CSKYConstantPoolValue.h"
Public Member Functions
const GlobalValue * getGV () const
const BlockAddress * getBlockAddress () const
const Constant * getConstantPool () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const CSKYConstantPoolConstant *A) const
Public Member Functions inherited from llvm::CSKYConstantPoolValue
const char * getModifierText () const
unsigned getPCAdjustment () const
bool mustAddCurrentAddress () const
CSKYCP::CSKYCPModifier getModifier () const
unsigned getLabelID () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isMachineBasicBlock () const
bool isJT () const
bool isConstPool () const
int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment) override
void addSelectionDAGCSEId (FoldingSetNodeID &ID) override
void print (raw_ostream &O) const override
print - Implement operator<<
bool equals (const CSKYConstantPoolValue *A) const
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, Align Alignment)
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()=default
Type * getType () const
virtual unsigned getSizeInBytes (const DataLayout &DL) const
virtual int getExistingMachineCPValue (MachineConstantPool *CP, Align Alignment)=0
virtual void addSelectionDAGCSEId (FoldingSetNodeID &ID)=0
virtual void print (raw_ostream &O) const =0
print - Implement operator<<
Static Public Member Functions
static CSKYConstantPoolConstant * Create (const Constant *C, CSKYCP::CSKYCPKind Kind, unsigned PCAdjust, CSKYCP::CSKYCPModifier Modifier, bool AddCurrentAddress, unsigned ID=0)
static CSKYConstantPoolConstant * Create (const Constant *C, Type *Ty, CSKYCP::CSKYCPKind Kind, unsigned PCAdjust, CSKYCP::CSKYCPModifier Modifier, bool AddCurrentAddress, unsigned ID=0)
static bool classof (const CSKYConstantPoolValue *APV)
Additional Inherited Members
Protected Member Functions inherited from llvm::CSKYConstantPoolValue
CSKYConstantPoolValue (Type *Ty, CSKYCP::CSKYCPKind Kind, unsigned PCAdjust, CSKYCP::CSKYCPModifier Modifier, bool AddCurrentAddress, unsigned ID=0)
Protected Attributes inherited from llvm::CSKYConstantPoolValue
CSKYCP::CSKYCPKind Kind
unsigned PCAdjust
CSKYCP::CSKYCPModifier Modifier
bool AddCurrentAddress
unsigned LabelId = 0
Detailed Description
CSKY-specific constant pool values for Constants, Functions, and BlockAddresses.
Definition at line 107 of file CSKYConstantPoolValue.h.
Member Function Documentation
addSelectionDAGCSEId()
void CSKYConstantPoolConstant::addSelectionDAGCSEId (FoldingSetNodeID & ID) override virtual
Reimplemented from llvm::CSKYConstantPoolValue.
Definition at line 119 of file CSKYConstantPoolValue.cpp.
References llvm::CSKYConstantPoolValue::addSelectionDAGCSEId().
classof()
static bool llvm::CSKYConstantPoolConstant::classof (const CSKYConstantPoolValue * APV) inline static
Definition at line 136 of file CSKYConstantPoolValue.h.
References llvm::CSKYConstantPoolValue::isBlockAddress(), llvm::CSKYConstantPoolValue::isConstPool(), and llvm::CSKYConstantPoolValue::isGlobalValue().
Create() [1/2]
CSKYConstantPoolConstant * CSKYConstantPoolConstant::Create (const Constant * C, CSKYCP::CSKYCPKind Kind, unsigned PCAdjust, CSKYCP::CSKYCPModifier Modifier, bool AddCurrentAddress, unsigned ID = 0) static
Definition at line 86 of file CSKYConstantPoolValue.cpp.
References llvm::CSKYConstantPoolValue::AddCurrentAddress, llvm::CallingConv::C, llvm::CSKYConstantPoolValue::Kind, llvm::CSKYConstantPoolValue::Modifier, and llvm::CSKYConstantPoolValue::PCAdjust.
Create() [2/2]
CSKYConstantPoolConstant * CSKYConstantPoolConstant::Create (const Constant * C, Type * Ty, CSKYCP::CSKYCPKind Kind, unsigned PCAdjust, CSKYCP::CSKYCPModifier Modifier, bool AddCurrentAddress, unsigned ID = 0) static
Definition at line 93 of file CSKYConstantPoolValue.cpp.
References llvm::CSKYConstantPoolValue::AddCurrentAddress, llvm::CallingConv::C, llvm::CSKYConstantPoolValue::Kind, llvm::CSKYConstantPoolValue::Modifier, and llvm::CSKYConstantPoolValue::PCAdjust.
equals()
bool llvm::CSKYConstantPoolConstant::equals (const CSKYConstantPoolConstant * A) const inline
Definition at line 132 of file CSKYConstantPoolValue.h.
References A, and llvm::CSKYConstantPoolValue::equals().
getBlockAddress()
const BlockAddress * CSKYConstantPoolConstant::getBlockAddress () const
Definition at line 105 of file CSKYConstantPoolValue.cpp.
References assert().
getConstantPool()
const Constant * CSKYConstantPoolConstant::getConstantPool () const
Definition at line 110 of file CSKYConstantPoolValue.cpp.
getExistingMachineCPValue()
int CSKYConstantPoolConstant::getExistingMachineCPValue (MachineConstantPool * CP, Align Alignment) override virtual
Reimplemented from llvm::CSKYConstantPoolValue.
Definition at line 114 of file CSKYConstantPoolValue.cpp.
getGV()
const GlobalValue * CSKYConstantPoolConstant::getGV () const
Definition at line 100 of file CSKYConstantPoolValue.cpp.
References assert().
print()
void CSKYConstantPoolConstant::print (raw_ostream & O) const override virtual
print - Implement operator<<
Reimplemented from llvm::CSKYConstantPoolValue.
Definition at line 125 of file CSKYConstantPoolValue.cpp.
References llvm::Value::getName(), and llvm::CSKYConstantPoolValue::print().
The documentation for this class was generated from the following files:
lib/Target/CSKY/CSKYConstantPoolValue.h
lib/Target/CSKY/CSKYConstantPoolValue.cpp