LLVM: llvm::CodeGenPassBuilder< DerivedT > Class Template Reference
llvm::CodeGenPassBuilder< DerivedT > Class Template Reference
This class provides access to building LLVM's passes.
#include "llvm/CodeGen/CodeGenPassBuilder.h"
Classes
class AddIRPass
class AddMachinePass
Public Member Functions
CodeGenPassBuilder (LLVMTargetMachine &TM, CGPassBuilderOption Opts, PassInstrumentationCallbacks *PIC)
Error buildPipeline (ModulePassManager &MPM, MachineFunctionPassManager &MFPM, raw_pwrite_stream &Out, raw_pwrite_stream *DwoOut, CodeGenFileType FileType) const
void registerModuleAnalyses (ModuleAnalysisManager &) const
void registerFunctionAnalyses (FunctionAnalysisManager &) const
void registerMachineFunctionAnalyses (MachineFunctionAnalysisManager &) const
std::pair< StringRef, bool > getPassNameFromLegacyName (StringRef) const
void registerAnalyses (MachineFunctionAnalysisManager &MFAM) const
PassInstrumentationCallbacks * getPassInstrumentationCallbacks () const
Protected Types
template<typename PassT >
using has_key_t = decltype(PassT::Key)
template<typename PassT >
using is_module_pass_t = decltype(std::declval< PassT & >().run(std::declval< Module & >(), std::declval< ModuleAnalysisManager & >()))
template<typename PassT >
using is_function_pass_t = decltype(std::declval< PassT & >().run(std::declval< Function & >(), std::declval< FunctionAnalysisManager & >()))
using CreateMCStreamer = std::function< Expected< std::unique_ptr< MCStreamer > >(MCContext &)>
Protected Member Functions
void registerTargetAnalysis (ModuleAnalysisManager &) const
Target override these hooks to parse target-specific analyses.
void registerTargetAnalysis (FunctionAnalysisManager &) const
void registerTargetAnalysis (MachineFunctionAnalysisManager &) const
std::pair< StringRef, bool > getTargetPassNameFromLegacyName (StringRef) const
template<typename TMC >
TMC & getTM () const
CodeGenOptLevel getOptLevel () const
bool isGlobalISelAbortEnabled () const
Check whether or not GlobalISel should abort on error.
bool reportDiagnosticWhenGlobalISelFallback () const
Check whether or not a diagnostic should be emitted when GlobalISel uses the fallback path.
Error addInstSelector (AddMachinePass &) const
addInstSelector - This method should install an instruction selector pass, which converts from LLVM code to machine instructions.
void addGlobalMergePass (AddIRPass &) const
Target can override this to add GlobalMergePass before all IR passes.
void addILPOpts (AddMachinePass &) const
Add passes that optimize instruction level parallelism for out-of-order targets.
void addPreRegAlloc (AddMachinePass &) const
This method may be implemented by targets that want to run passes immediately before register allocation.
void addPreRewrite (AddMachinePass &) const
addPreRewrite - Add passes to the optimized register allocation pipeline after register allocation is complete, but before virtual registers are rewritten to physical registers.
void addPostRewrite (AddMachinePass &) const
Add passes to be run immediately after virtual registers are rewritten to physical registers.
void addPostRegAlloc (AddMachinePass &) const
This method may be implemented by targets that want to run passes after register allocation pass pipeline but before prolog-epilog insertion.
void addPreSched2 (AddMachinePass &) const
This method may be implemented by targets that want to run passes after prolog-epilog insertion and before the second instruction scheduling pass.
void addPreEmitPass (AddMachinePass &) const
This pass may be implemented by targets that want to run passes immediately before machine code is emitted.
void addPreEmitPass2 (AddMachinePass &) const
Targets may add passes immediately before machine code is emitted in this callback.
void addPreISel (AddIRPass &) const
{{@ For GlobalISel
Error addIRTranslator (AddMachinePass &) const
This method should install an IR translator pass, which converts from LLVM code to machine instructions with possibly generic opcodes.
void addPreLegalizeMachineIR (AddMachinePass &) const
This method may be implemented by targets that want to run passes immediately before legalization.
Error addLegalizeMachineIR (AddMachinePass &) const
This method should install a legalize pass, which converts the instruction sequence into one that can be selected by the target.
void addPreRegBankSelect (AddMachinePass &) const
This method may be implemented by targets that want to run passes immediately before the register bank selection.
Error addRegBankSelect (AddMachinePass &) const
This method should install a register bank selector pass, which assigns register banks to virtual registers without a register class or register banks.
void addPreGlobalInstructionSelect (AddMachinePass &) const
This method may be implemented by targets that want to run passes immediately before the (global) instruction selection.
Error addGlobalInstructionSelect (AddMachinePass &) const
This method should install a (global) instruction selector pass, which converts possibly generic instructions to fully target-specific instructions, thereby constraining all generic virtual registers to register classes.
void addISelPasses (AddIRPass &) const
High level function that adds all passes necessary to go from llvm IR representation to the MI representation.
Error addCoreISelPasses (AddMachinePass &) const
Add the actual instruction selection passes.
Error addMachinePasses (AddMachinePass &) const
Add the complete, standard set of LLVM CodeGen passes.
void addPassesToHandleExceptions (AddIRPass &) const
Add passes to lower exception handling for the code generator.
void addIRPasses (AddIRPass &) const
Add common target configurable passes that perform LLVM IR to IR transforms following machine independent optimization.
void addCodeGenPrepare (AddIRPass &) const
Add pass to prepare the LLVM IR for code generation.
void addISelPrepare (AddIRPass &) const
Add common passes that perform LLVM IR to IR transforms in preparation for instruction selection.
void addMachineSSAOptimization (AddMachinePass &) const
Methods with trivial inline returns are convenient points in the common codegen pass pipeline where targets may insert passes.
Error addFastRegAlloc (AddMachinePass &) const
addFastRegAlloc - Add the minimum set of target-independent passes that are required for fast register allocation.
void addOptimizedRegAlloc (AddMachinePass &) const
addOptimizedRegAlloc - Add passes related to register allocation.
void addMachineLateOptimization (AddMachinePass &) const
Add passes that optimize machine instructions after register allocation.
void addGCPasses (AddMachinePass &) const
addGCPasses - Add late codegen passes that analyze code for garbage collection.
void addBlockPlacement (AddMachinePass &) const
Add standard basic block placement passes.
void addAsmPrinter (AddMachinePass &, CreateMCStreamer) const
void addTargetRegisterAllocator (AddMachinePass &, bool Optimized) const
Utilities for targets to add passes to the pass manager.
void addRegAllocPass (AddMachinePass &, bool Optimized) const
addMachinePasses helper to create the target-selected or overriden regalloc pass.
Error addRegAssignmentFast (AddMachinePass &) const
Add core register alloator passes which do the actual register assignment and rewriting.
Error addRegAssignmentOptimized (AddMachinePass &) const
Protected Attributes
LLVMTargetMachine & TM
CGPassBuilderOption Opt
PassInstrumentationCallbacks * PIC
Detailed Description
template<typename DerivedT>
class llvm::CodeGenPassBuilder< DerivedT >
This class provides access to building LLVM's passes.
Its members provide the baseline state available to passes during their construction. The MachinePassRegistry.def file specifies how to construct all of the built-in passes, and those may reference these members during construction.
Definition at line 127 of file CodeGenPassBuilder.h.
Member Typedef Documentation
CreateMCStreamer
template<typename DerivedT > using llvm::CodeGenPassBuilder< DerivedT >::CreateMCStreamer = std::function<Expected<std::unique_ptr<MCStreamer> >(MCContext &)> protected
Definition at line 457 of file CodeGenPassBuilder.h.
has_key_t
template<typename DerivedT > template<typename PassT > using llvm::CodeGenPassBuilder< DerivedT >::has_key_t = decltype(PassT::Key) protected
Definition at line 167 of file CodeGenPassBuilder.h.
is_function_pass_t
template<typename DerivedT > template<typename PassT > using llvm::CodeGenPassBuilder< DerivedT >::is_function_pass_t = decltype(std::declval<PassT &>().run(std::declval<Function &>(), std::declval<FunctionAnalysisManager &>())) protected
Definition at line 174 of file CodeGenPassBuilder.h.
is_module_pass_t
template<typename DerivedT > template<typename PassT > using llvm::CodeGenPassBuilder< DerivedT >::is_module_pass_t = decltype(std::declval<PassT &>().run(std::declval<Module &>(), std::declval<ModuleAnalysisManager &>())) protected
Definition at line 170 of file CodeGenPassBuilder.h.
Constructor & Destructor Documentation
CodeGenPassBuilder()
template<typename DerivedT > llvm::CodeGenPassBuilder< DerivedT >::CodeGenPassBuilder (LLVMTargetMachine & TM, CGPassBuilderOption Opts, PassInstrumentationCallbacks * PIC) inline explicit
Definition at line 129 of file CodeGenPassBuilder.h.
References llvm::CGPassBuilderOption::EnableGlobalISelAbort, llvm::CGPassBuilderOption::EnableIPRA, llvm::TargetOptions::EnableIPRA, llvm::CodeGenPassBuilder< DerivedT >::getOptLevel(), llvm::TargetOptions::GlobalISelAbort, llvm::None, llvm::CodeGenPassBuilder< DerivedT >::Opt, llvm::CGPassBuilderOption::OptimizeRegAlloc, llvm::TargetMachine::Options, and llvm::CodeGenPassBuilder< DerivedT >::TM.
Member Function Documentation
addAsmPrinter()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addAsmPrinter (AddMachinePass & , CreateMCStreamer) const inline protected
Definition at line 459 of file CodeGenPassBuilder.h.
References llvm_unreachable.
addBlockPlacement()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::addBlockPlacement (AddMachinePass & addPass) const protected
Add standard basic block placement passes.
Definition at line 1228 of file CodeGenPassBuilder.h.
References llvm::CGPassBuilderOption::EnableBlockPlacementStats.
addCodeGenPrepare()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::addCodeGenPrepare (AddIRPass & addPass) const protected
Add pass to prepare the LLVM IR for code generation.
This should be done before exception handling preparation passes.
Definition at line 821 of file CodeGenPassBuilder.h.
References llvm::CGPassBuilderOption::DisableCGP, and TM.
addCoreISelPasses()
template<typename Derived > Error llvm::CodeGenPassBuilder< Derived >::addCoreISelPasses (AddMachinePass & addPass) const protected
Add the actual instruction selection passes.
This does not include preparation passes on IR.
Definition at line 851 of file CodeGenPassBuilder.h.
References llvm::CGPassBuilderOption::EnableFastISelOption, llvm::CGPassBuilderOption::EnableGlobalISelOption, and TM.
addFastRegAlloc()
template<typename Derived > Error llvm::CodeGenPassBuilder< Derived >::addFastRegAlloc (AddMachinePass & addPass) const protected
addFastRegAlloc - Add the minimum set of target-independent passes that are required for fast register allocation.
Add the minimum set of target-independent passes that are required for register allocation.
No coalescing or scheduling.
Definition at line 1150 of file CodeGenPassBuilder.h.
addGCPasses()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addGCPasses (AddMachinePass &) const inline protected
addGCPasses - Add late codegen passes that analyze code for garbage collection.
This should return true if GC info should be printed after these passes.
Definition at line 452 of file CodeGenPassBuilder.h.
addGlobalInstructionSelect()
template<typename DerivedT > Error llvm::CodeGenPassBuilder< DerivedT >::addGlobalInstructionSelect (AddMachinePass &) const inline protected
This method should install a (global) instruction selector pass, which converts possibly generic instructions to fully target-specific instructions, thereby constraining all generic virtual registers to register classes.
Definition at line 391 of file CodeGenPassBuilder.h.
References llvm::inconvertibleErrorCode().
addGlobalMergePass()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addGlobalMergePass (AddIRPass &) const inline protected
Target can override this to add GlobalMergePass before all IR passes.
Definition at line 293 of file CodeGenPassBuilder.h.
Referenced by llvm::CodeGenPassBuilder< DerivedT >::addISelPasses().
addILPOpts()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addILPOpts (AddMachinePass &) const inline protected
Add passes that optimize instruction level parallelism for out-of-order targets.
These passes are run while the machine code is still in SSA form, so they can use MachineTraceMetrics to control their heuristics.
All passes added here should preserve the MachineDominatorTree, MachineLoopInfo, and MachineTraceMetrics analyses.
Definition at line 301 of file CodeGenPassBuilder.h.
addInstSelector()
template<typename DerivedT > Error llvm::CodeGenPassBuilder< DerivedT >::addInstSelector (AddMachinePass &) const inline protected
addInstSelector - This method should install an instruction selector pass, which converts from LLVM code to machine instructions.
Definition at line 287 of file CodeGenPassBuilder.h.
References llvm::inconvertibleErrorCode().
addIRPasses()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::addIRPasses (AddIRPass & addPass) const protected
Add common target configurable passes that perform LLVM IR to IR transforms following machine independent optimization.
Definition at line 708 of file CodeGenPassBuilder.h.
References llvm::createFunctionToLoopPassAdaptor(), llvm::dbgs(), llvm::CGPassBuilderOption::DisableConstantHoisting, llvm::CGPassBuilderOption::DisableLSR, llvm::CGPassBuilderOption::DisableMergeICmps, llvm::CGPassBuilderOption::DisablePartialLibcallInlining, llvm::CGPassBuilderOption::DisableSelectOptimize, llvm::CGPassBuilderOption::DisableVerify, llvm::CGPassBuilderOption::PrintLSR, and TM.
addIRTranslator()
template<typename DerivedT > Error llvm::CodeGenPassBuilder< DerivedT >::addIRTranslator (AddMachinePass &) const inline protected
This method should install an IR translator pass, which converts from LLVM code to machine instructions with possibly generic opcodes.
Definition at line 355 of file CodeGenPassBuilder.h.
References llvm::inconvertibleErrorCode().
addISelPasses()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::addISelPasses (AddIRPass & addPass) const protected
High level function that adds all passes necessary to go from llvm IR representation to the MI representation.
Adds IR based lowering and target specific optimization passes and finally the core instruction selection passes.
Definition at line 692 of file CodeGenPassBuilder.h.
References llvm::CodeGenPassBuilder< DerivedT >::addGlobalMergePass(), and TM.
addISelPrepare()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::addISelPrepare (AddIRPass & addPass) const protected
Add common passes that perform LLVM IR to IR transforms in preparation for instruction selection.
Definition at line 831 of file CodeGenPassBuilder.h.
References llvm::CodeGenPassBuilder< DerivedT >::addPreISel(), llvm::dbgs(), llvm::CGPassBuilderOption::DisableVerify, llvm::CGPassBuilderOption::PrintISelInput, and TM.
addLegalizeMachineIR()
template<typename DerivedT > Error llvm::CodeGenPassBuilder< DerivedT >::addLegalizeMachineIR (AddMachinePass &) const inline protected
This method should install a legalize pass, which converts the instruction sequence into one that can be selected by the target.
Definition at line 366 of file CodeGenPassBuilder.h.
References llvm::inconvertibleErrorCode().
addMachineLateOptimization()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::addMachineLateOptimization (AddMachinePass & addPass) const protected
Add passes that optimize machine instructions after register allocation.
Post RegAlloc Pass Configuration.
Add passes that optimize machine instructions after register allocation.
Definition at line 1207 of file CodeGenPassBuilder.h.
References TM.
addMachinePasses()
template<typename Derived > Error llvm::CodeGenPassBuilder< Derived >::addMachinePasses (AddMachinePass & addPass) const protected
Add the complete, standard set of LLVM CodeGen passes.
Add the complete set of target-independent postISel code generator passes.
Fully developed targets will not generally override this.
This can be read as the standard order of major LLVM CodeGen stages. Stages with nontrivial configuration or multiple passes are broken out below in addStage routines.
Any CodeGenPassBuilder<Derived>::addXX routine may be overriden by the Target. The addPre/Post methods with empty header implementations allow injecting target-specific fixups just before or after major stages. Additionally, targets have the flexibility to change pass order within a stage by overriding default implementation of addStage routines below. Each technique has maintainability tradeoffs because alternate pass orders are not well supported. addPre/Post works better if the target pass is easily tied to a common pass. But if it has subtle dependencies on multiple passes, the target should override the stage instead.
Add passes that optimize machine instructions after register allocation.
Definition at line 943 of file CodeGenPassBuilder.h.
References llvm::CodeGenPassBuilder< DerivedT >::addMachineSSAOptimization(), llvm::CGPassBuilderOption::EnableImplicitNullChecks, llvm::CGPassBuilderOption::EnableMachineOutliner, llvm::CGPassBuilderOption::MISchedPostRA, llvm::CGPassBuilderOption::OptimizeRegAlloc, and TM.
addMachineSSAOptimization()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::addMachineSSAOptimization (AddMachinePass & addPass) const protected
Methods with trivial inline returns are convenient points in the common codegen pass pipeline where targets may insert passes.
Add passes that optimize machine instructions in SSA form.
Methods with out-of-line standard implementations are major CodeGen stages called by addMachinePasses. Some targets may override major stages when inserting passes is insufficient, but maintaining overriden stages is more work. addMachineSSAOptimization - Add standard passes that optimize machine instructions in SSA form.
Definition at line 1050 of file CodeGenPassBuilder.h.
Referenced by llvm::CodeGenPassBuilder< DerivedT >::addMachinePasses().
addOptimizedRegAlloc()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::addOptimizedRegAlloc (AddMachinePass & addPass) const protected
addOptimizedRegAlloc - Add passes related to register allocation.
Add standard target-independent passes that are tightly coupled with optimized register allocation, including coalescing, machine instruction scheduling, and register allocation itself.
LLVMTargetMachine provides standard regalloc passes for most targets.
Definition at line 1161 of file CodeGenPassBuilder.h.
References llvm::CGPassBuilderOption::EarlyLiveIntervals.
addPassesToHandleExceptions()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::addPassesToHandleExceptions (AddIRPass & addPass) const protected
Add passes to lower exception handling for the code generator.
Turn exception handling constructs into something the code generators can handle.
Definition at line 774 of file CodeGenPassBuilder.h.
References assert(), llvm::MCAsmInfo::getExceptionHandlingType(), and TM.
addPostRegAlloc()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addPostRegAlloc (AddMachinePass &) const inline protected
This method may be implemented by targets that want to run passes after register allocation pass pipeline but before prolog-epilog insertion.
Definition at line 327 of file CodeGenPassBuilder.h.
addPostRewrite()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addPostRewrite (AddMachinePass &) const inline protected
Add passes to be run immediately after virtual registers are rewritten to physical registers.
Definition at line 323 of file CodeGenPassBuilder.h.
addPreEmitPass()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addPreEmitPass (AddMachinePass &) const inline protected
This pass may be implemented by targets that want to run passes immediately before machine code is emitted.
Definition at line 335 of file CodeGenPassBuilder.h.
addPreEmitPass2()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addPreEmitPass2 (AddMachinePass &) const inline protected
Targets may add passes immediately before machine code is emitted in this callback.
This is called even later than addPreEmitPass.
Definition at line 342 of file CodeGenPassBuilder.h.
addPreGlobalInstructionSelect()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addPreGlobalInstructionSelect (AddMachinePass &) const inline protected
This method may be implemented by targets that want to run passes immediately before the (global) instruction selection.
Definition at line 385 of file CodeGenPassBuilder.h.
addPreISel()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addPreISel (AddIRPass &) const inline protected
{{@ For GlobalISel
addPreISel - This method should add any "last minute" LLVM->LLVM passes (which are run just before instruction selector).
Definition at line 349 of file CodeGenPassBuilder.h.
References llvm_unreachable.
Referenced by llvm::CodeGenPassBuilder< DerivedT >::addISelPrepare().
addPreLegalizeMachineIR()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addPreLegalizeMachineIR (AddMachinePass &) const inline protected
This method may be implemented by targets that want to run passes immediately before legalization.
Definition at line 362 of file CodeGenPassBuilder.h.
addPreRegAlloc()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addPreRegAlloc (AddMachinePass &) const inline protected
This method may be implemented by targets that want to run passes immediately before register allocation.
Definition at line 305 of file CodeGenPassBuilder.h.
addPreRegBankSelect()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addPreRegBankSelect (AddMachinePass &) const inline protected
This method may be implemented by targets that want to run passes immediately before the register bank selection.
Definition at line 373 of file CodeGenPassBuilder.h.
addPreRewrite()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addPreRewrite (AddMachinePass &) const inline protected
addPreRewrite - Add passes to the optimized register allocation pipeline after register allocation is complete, but before virtual registers are rewritten to physical registers.
These passes must preserve VirtRegMap and LiveIntervals, and when running after RABasic or RAGreedy, they should take advantage of LiveRegMatrix. When these passes run, VirtRegMap contains legal physreg assignments for all virtual registers.
Note if the target overloads addRegAssignAndRewriteOptimized, this may not be honored. This is also not generally used for the fast variant, where the allocation and rewriting are done in one pass.
Definition at line 319 of file CodeGenPassBuilder.h.
addPreSched2()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::addPreSched2 (AddMachinePass &) const inline protected
This method may be implemented by targets that want to run passes after prolog-epilog insertion and before the second instruction scheduling pass.
Definition at line 331 of file CodeGenPassBuilder.h.
addRegAllocPass()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::addRegAllocPass (AddMachinePass & addPass, bool Optimized) const protected
addMachinePasses helper to create the target-selected or overriden regalloc pass.
Find and instantiate the register allocation pass requested by this target at the current optimization level.
Different register allocators are defined as separate passes because they may require different analysis.
Definition at line 1114 of file CodeGenPassBuilder.h.
addRegAssignmentFast()
template<typename Derived > Error llvm::CodeGenPassBuilder< Derived >::addRegAssignmentFast (AddMachinePass & addPass) const protected
Add core register alloator passes which do the actual register assignment and rewriting.
Returns
true if any passes were added.
Definition at line 1120 of file CodeGenPassBuilder.h.
addRegAssignmentOptimized()
template<typename Derived > Error llvm::CodeGenPassBuilder< Derived >::addRegAssignmentOptimized (AddMachinePass & addPass) const protected
Definition at line 1128 of file CodeGenPassBuilder.h.
addRegBankSelect()
template<typename DerivedT > Error llvm::CodeGenPassBuilder< DerivedT >::addRegBankSelect (AddMachinePass &) const inline protected
This method should install a register bank selector pass, which assigns register banks to virtual registers without a register class or register banks.
Definition at line 378 of file CodeGenPassBuilder.h.
References llvm::inconvertibleErrorCode().
addTargetRegisterAllocator()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::addTargetRegisterAllocator (AddMachinePass & addPass, bool Optimized) const protected
Utilities for targets to add passes to the pass manager.
Register Allocation Pass Configuration.
createTargetRegisterAllocator - Create the register allocator pass for this target at the current optimization level.
Instantiate the default register allocator pass for this target for either the optimized or unoptimized allocation path. This will be added to the pass manager by addFastRegAlloc in the unoptimized case or addOptimizedRegAlloc in the optimized case.
A target that uses the standard regalloc pass order for fast or optimized allocation may still override this for per-target regalloc selection. But -regalloc=... always takes precedence.
Definition at line 1102 of file CodeGenPassBuilder.h.
buildPipeline()
template<typename Derived > Error llvm::CodeGenPassBuilder< Derived >::buildPipeline (ModulePassManager & MPM, MachineFunctionPassManager & MFPM, raw_pwrite_stream & Out, raw_pwrite_stream * DwoOut, CodeGenFileType FileType) const
Definition at line 506 of file CodeGenPassBuilder.h.
References llvm::LLVMTargetMachine::createMCStreamer(), llvm::TargetPassConfig::getStartStopInfo(), MPM, and PIC.
getOptLevel()
template<typename DerivedT > CodeGenOptLevel llvm::CodeGenPassBuilder< DerivedT >::getOptLevel () const inline protected
Definition at line 269 of file CodeGenPassBuilder.h.
References llvm::TargetMachine::getOptLevel(), and llvm::CodeGenPassBuilder< DerivedT >::TM.
Referenced by llvm::CodeGenPassBuilder< DerivedT >::CodeGenPassBuilder().
getPassInstrumentationCallbacks()
template<typename DerivedT > PassInstrumentationCallbacks * llvm::CodeGenPassBuilder< DerivedT >::getPassInstrumentationCallbacks () const inline
Definition at line 162 of file CodeGenPassBuilder.h.
References llvm::CodeGenPassBuilder< DerivedT >::PIC.
getPassNameFromLegacyName()
template<typename Derived > std::pair< StringRef, bool > llvm::CodeGenPassBuilder< Derived >::getPassNameFromLegacyName (StringRef Name) const
Definition at line 650 of file CodeGenPassBuilder.h.
References Name, and llvm::report_fatal_error().
getTargetPassNameFromLegacyName()
template<typename DerivedT > std::pair< StringRef, bool > llvm::CodeGenPassBuilder< DerivedT >::getTargetPassNameFromLegacyName (StringRef) const inline protected
Definition at line 264 of file CodeGenPassBuilder.h.
getTM()
template<typename DerivedT > template<typename TMC > TMC & llvm::CodeGenPassBuilder< DerivedT >::getTM () const inline protected
Definition at line 268 of file CodeGenPassBuilder.h.
References llvm::CodeGenPassBuilder< DerivedT >::TM.
isGlobalISelAbortEnabled()
template<typename DerivedT > bool llvm::CodeGenPassBuilder< DerivedT >::isGlobalISelAbortEnabled () const inline protected
Check whether or not GlobalISel should abort on error.
When this is disabled, GlobalISel will fall back on SDISel instead of erroring out.
Definition at line 274 of file CodeGenPassBuilder.h.
References llvm::Enable, llvm::TargetOptions::GlobalISelAbort, llvm::TargetMachine::Options, and llvm::CodeGenPassBuilder< DerivedT >::TM.
registerAnalyses()
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::registerAnalyses (MachineFunctionAnalysisManager & MFAM) const inline
Definition at line 156 of file CodeGenPassBuilder.h.
References llvm::MachineFunctionAnalysisManager::FAM, llvm::MachineFunctionAnalysisManager::MAM, llvm::CodeGenPassBuilder< DerivedT >::registerFunctionAnalyses(), llvm::CodeGenPassBuilder< DerivedT >::registerMachineFunctionAnalyses(), and llvm::CodeGenPassBuilder< DerivedT >::registerModuleAnalyses().
registerFunctionAnalyses()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::registerFunctionAnalyses (FunctionAnalysisManager & FAM) const
Definition at line 625 of file CodeGenPassBuilder.h.
References FAM, and llvm::registerAAAnalyses().
Referenced by llvm::CodeGenPassBuilder< DerivedT >::registerAnalyses().
registerMachineFunctionAnalyses()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::registerMachineFunctionAnalyses (MachineFunctionAnalysisManager & MFAM) const
Definition at line 636 of file CodeGenPassBuilder.h.
References llvm::CodeGenPassBuilder< DerivedT >::registerTargetAnalysis().
Referenced by llvm::CodeGenPassBuilder< DerivedT >::registerAnalyses().
registerModuleAnalyses()
template<typename Derived > void llvm::CodeGenPassBuilder< Derived >::registerModuleAnalyses (ModuleAnalysisManager & MAM) const
Definition at line 616 of file CodeGenPassBuilder.h.
References MAM, and llvm::CodeGenPassBuilder< DerivedT >::registerTargetAnalysis().
Referenced by llvm::CodeGenPassBuilder< DerivedT >::registerAnalyses().
registerTargetAnalysis() [1/3]
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::registerTargetAnalysis (FunctionAnalysisManager &) const inline protected
Definition at line 262 of file CodeGenPassBuilder.h.
registerTargetAnalysis() [2/3]
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::registerTargetAnalysis (MachineFunctionAnalysisManager &) const inline protected
Definition at line 263 of file CodeGenPassBuilder.h.
registerTargetAnalysis() [3/3]
template<typename DerivedT > void llvm::CodeGenPassBuilder< DerivedT >::registerTargetAnalysis (ModuleAnalysisManager &) const inline protected
Target override these hooks to parse target-specific analyses.
Definition at line 261 of file CodeGenPassBuilder.h.
Referenced by llvm::CodeGenPassBuilder< DerivedT >::registerMachineFunctionAnalyses(), and llvm::CodeGenPassBuilder< DerivedT >::registerModuleAnalyses().
reportDiagnosticWhenGlobalISelFallback()
template<typename DerivedT > bool llvm::CodeGenPassBuilder< DerivedT >::reportDiagnosticWhenGlobalISelFallback () const inline protected
Check whether or not a diagnostic should be emitted when GlobalISel uses the fallback path.
In other words, it will emit a diagnostic when GlobalISel failed and isGlobalISelAbortEnabled is false.
Definition at line 281 of file CodeGenPassBuilder.h.
References llvm::DisableWithDiag, llvm::TargetOptions::GlobalISelAbort, llvm::TargetMachine::Options, and llvm::CodeGenPassBuilder< DerivedT >::TM.
Member Data Documentation
Opt
template<typename DerivedT > CGPassBuilderOption llvm::CodeGenPassBuilder< DerivedT >::Opt protected
Definition at line 257 of file CodeGenPassBuilder.h.
Referenced by llvm::CodeGenPassBuilder< DerivedT >::CodeGenPassBuilder().
PIC
template<typename DerivedT > PassInstrumentationCallbacks* llvm::CodeGenPassBuilder< DerivedT >::PIC protected
Definition at line 258 of file CodeGenPassBuilder.h.
Referenced by llvm::CodeGenPassBuilder< DerivedT >::getPassInstrumentationCallbacks().
TM
template<typename DerivedT > LLVMTargetMachine& llvm::CodeGenPassBuilder< DerivedT >::TM protected
Definition at line 256 of file CodeGenPassBuilder.h.
Referenced by llvm::CodeGenPassBuilder< DerivedT >::CodeGenPassBuilder(), llvm::CodeGenPassBuilder< DerivedT >::getOptLevel(), llvm::CodeGenPassBuilder< DerivedT >::getTM(), llvm::CodeGenPassBuilder< DerivedT >::isGlobalISelAbortEnabled(), and llvm::CodeGenPassBuilder< DerivedT >::reportDiagnosticWhenGlobalISelFallback().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/CodeGenPassBuilder.h