LLVM: llvm::ParseStatus Class Reference
llvm::ParseStatus Class Reference
Ternary parse status returned by various parse* methods.
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
Public Member Functions
constexpr ParseStatus ()
constexpr ParseStatus (StatusTy Status)
constexpr ParseStatus (bool Error)
template<typename T >
constexpr ParseStatus (T)=delete
constexpr bool isSuccess () const
constexpr bool isFailure () const
constexpr bool isNoMatch () const
constexpr ParseStatus (OperandMatchResultTy R)
constexpr operator OperandMatchResultTy () const
Static Public Attributes
static constexpr StatusTy Success = StatusTy::Success
static constexpr StatusTy Failure = StatusTy::Failure
static constexpr StatusTy NoMatch = StatusTy::NoMatch
Detailed Description
Ternary parse status returned by various parse* methods.
Definition at line 132 of file MCTargetAsmParser.h.
Constructor & Destructor Documentation
ParseStatus() [1/5]
constexpr llvm::ParseStatus::ParseStatus () inline constexpr
Definition at line 144 of file MCTargetAsmParser.h.
ParseStatus() [2/5]
constexpr llvm::ParseStatus::ParseStatus (StatusTy Status) inline constexpr
Definition at line 146 of file MCTargetAsmParser.h.
ParseStatus() [3/5]
constexpr llvm::ParseStatus::ParseStatus (bool Error) inline constexpr
Definition at line 148 of file MCTargetAsmParser.h.
ParseStatus() [4/5]
template<typename T > constexpr llvm::ParseStatus::ParseStatus (T) constexpr delete
ParseStatus() [5/5]
constexpr llvm::ParseStatus::ParseStatus (OperandMatchResultTy R) inline constexpr
Definition at line 158 of file MCTargetAsmParser.h.
Member Function Documentation
isFailure()
constexpr bool llvm::ParseStatus::isFailure () const inline constexpr
Definition at line 153 of file MCTargetAsmParser.h.
Referenced by operator OperandMatchResultTy().
isNoMatch()
constexpr bool llvm::ParseStatus::isNoMatch () const inline constexpr
Definition at line 154 of file MCTargetAsmParser.h.
isSuccess()
constexpr bool llvm::ParseStatus::isSuccess () const inline constexpr
Definition at line 152 of file MCTargetAsmParser.h.
Referenced by operator OperandMatchResultTy().
operator OperandMatchResultTy()
constexpr llvm::ParseStatus::operator OperandMatchResultTy () const inline constexpr
Definition at line 163 of file MCTargetAsmParser.h.
References isFailure(), isSuccess(), llvm::MatchOperand_NoMatch, llvm::MatchOperand_ParseFail, and llvm::MatchOperand_Success.
Member Data Documentation
Failure
constexpr StatusTy llvm::ParseStatus::Failure = StatusTy::Failure static constexpr
Definition at line 140 of file MCTargetAsmParser.h.
Referenced by llvm::MCTargetAsmParser::parseDirective().
NoMatch
constexpr StatusTy llvm::ParseStatus::NoMatch = StatusTy::NoMatch static constexpr
Definition at line 141 of file MCTargetAsmParser.h.
Referenced by llvm::MCTargetAsmParser::parseDirective().
Success
constexpr StatusTy llvm::ParseStatus::Success = StatusTy::Success static constexpr
Definition at line 139 of file MCTargetAsmParser.h.
Referenced by llvm::MCTargetAsmParser::parseDirective().
The documentation for this class was generated from the following file:
include/llvm/MC/MCParser/MCTargetAsmParser.h