LLVM: llvm::DwarfDebug Class Reference
llvm::DwarfDebug Class Reference
Collects and handles dwarf debug information.
#include "CodeGen/AsmPrinter/DwarfDebug.h"
Public Types
enum class MinimizeAddrInV5 {
Default , Disabled , Ranges , Expressions ,
Form
}
enum class DWARF5AccelTableKind { CU = 0 , TU = 1 }
Public Member Functions
DwarfDebug (AsmPrinter *A)
~DwarfDebug () override
void beginModule (Module *M) override
Emit all Dwarf sections that should come prior to the content.
void endModule () override
Emit all Dwarf sections that should come after the content.
DebugLoc emitInitialLocDirective (const MachineFunction &MF, unsigned CUID)
Emits inital debug location directive.
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void addDwarfTypeUnitType (DwarfCompileUnit &CU, StringRef Identifier, DIE &Die, const DICompositeType *CTy)
Add a DIE to the set of types that we're going to pull into type units.
void addArangeLabel (SymbolCU SCU)
Add a label so that arange data can be generated for it.
void setSymbolSize (const MCSymbol *Sym, uint64_t Size) override
For symbols that have a size designated (e.g.
bool useAllLinkageNames () const
Returns whether we should emit all DW_AT_[MIPS_]linkage_name.
bool useGNUTLSOpcode () const
Returns whether to use DW_OP_GNU_push_tls_address, instead of the standard DW_OP_form_tls_address opcode.
bool useDWARF2Bitfields () const
Returns whether to use the DWARF2 format for bitfields instyead of the DWARF4 format.
bool useInlineStrings () const
Returns whether to use inline strings.
bool useRangesSection () const
Returns whether ranges section should be emitted.
bool alwaysUseRanges (const DwarfCompileUnit &) const
Returns whether range encodings should be used for single entry range lists.
bool useAddrOffsetExpressions () const
bool useAddrOffsetForm () const
bool useSectionsAsReferences () const
Returns whether to use sections as labels rather than temp symbols.
bool useLocSection () const
Returns whether .debug_loc section should be emitted.
bool generateTypeUnits () const
Returns whether to generate DWARF v4 type units.
AccelTableKind getAccelTableKind () const
Returns what kind (if any) of accelerator tables to emit.
void setTheAccelTableKind (AccelTableKind K)
Seet TheAccelTableKind.
bool useAppleExtensionAttributes () const
bool useSplitDwarf () const
Returns whether or not to change the current debug info for the split dwarf proposal support.
bool useSegmentedStringOffsetsTable () const
Returns whether to generate a string offsets table with (possibly shared) contributions from each CU and type unit.
bool emitDebugEntryValues () const
bool useOpConvert () const
bool shareAcrossDWOCUs () const
uint16_t getDwarfVersion () const
Returns the Dwarf Version.
dwarf::Form getDwarfSectionOffsetForm () const
Returns a suitable DWARF form to represent a section offset, i.e.
const DwarfCompileUnit * getPrevCU () const
Returns the previous CU that was being updated.
void setPrevCU (const DwarfCompileUnit *PrevCU)
void terminateLineTable (const DwarfCompileUnit *CU)
Terminate the line table by adding the last range label.
const DebugLocStream & getDebugLocs () const
Returns the entries for the .debug_loc section.
void emitDebugLocEntry (ByteStreamer &Streamer, const DebugLocStream::Entry &Entry, const DwarfCompileUnit *CU)
Emit an entry for the debug loc section.
void emitDebugLocEntryLocation (const DebugLocStream::Entry &Entry, const DwarfCompileUnit *CU)
Emit the location for a debug loc entry, including the size header.
void addSubprogramNames (const DwarfUnit &Unit, const DICompileUnit::DebugNameTableKind NameTableKind, const DISubprogram *SP, DIE &Die)
AddressPool & getAddressPool ()
void addAccelName (const DwarfUnit &Unit, const DICompileUnit::DebugNameTableKind NameTableKind, StringRef Name, const DIE &Die)
void addAccelObjC (const DwarfUnit &Unit, const DICompileUnit::DebugNameTableKind NameTableKind, StringRef Name, const DIE &Die)
void addAccelNamespace (const DwarfUnit &Unit, const DICompileUnit::DebugNameTableKind NameTableKind, StringRef Name, const DIE &Die)
void addAccelType (const DwarfUnit &Unit, const DICompileUnit::DebugNameTableKind NameTableKind, StringRef Name, const DIE &Die, char Flags)
const MachineFunction * getCurrentFunction () const
bool isLexicalScopeDIENull (LexicalScope *Scope)
A helper function to check whether the DIE for a given Scope is going to be null.
DwarfCompileUnit * lookupCU (const DIE *Die)
Find the matching DwarfCompileUnit for the given CU DIE.
const DwarfCompileUnit * lookupCU (const DIE *Die) const
unsigned getStringTypeLoc (const DIStringType *ST) const
void addStringTypeLoc (const DIStringType *ST, unsigned Loc)
bool tuneForGDB () const
bool tuneForLLDB () const
bool tuneForSCE () const
bool tuneForDBX () const
const MCSymbol * getSectionLabel (const MCSection *S)
void insertSectionLabel (const MCSymbol *S)
std::optional< MD5::MD5Result > getMD5AsBytes (const DIFile *File) const
If the File has an MD5 checksum, return it as an MD5Result allocated in the MCContext.
MDNodeSet & getLocalDeclsForScope (const DILocalScope *S)
void setCurrentDWARF5AccelTable (const DWARF5AccelTableKind Kind)
Sets the current DWARF5AccelTable to use.
DWARF5AccelTable & getCurrentDWARF5AccelTable ()
Returns either CU or TU DWARF5AccelTable.
Public Member Functions inherited from llvm::DebugHandlerBase
void beginModule (Module *M) override
void beginInstruction (const MachineInstr *MI) override
Process beginning of an instruction.
void endInstruction () override
Process end of an instruction.
void beginFunction (const MachineFunction *MF) override
Gather pre-function debug information.
void endFunction (const MachineFunction *MF) override
Gather post-function debug information.
void beginBasicBlockSection (const MachineBasicBlock &MBB) override
Process the beginning of a new basic-block-section within a function.
void endBasicBlockSection (const MachineBasicBlock &MBB) override
Process the end of a basic-block-section within a function.
MCSymbol * getLabelBeforeInsn (const MachineInstr *MI)
Return Label preceding the instruction.
MCSymbol * getLabelAfterInsn (const MachineInstr *MI)
Return Label immediately following the instruction.
const InstructionOrdering & getInstOrdering () const
Public Member Functions inherited from llvm::AsmPrinterHandler
virtual ~AsmPrinterHandler ()
Pin vtable to this file.
virtual void setSymbolSize (const MCSymbol *Sym, uint64_t Size)=0
For symbols that have a size designated (e.g.
virtual void beginModule (Module *M)
virtual void endModule ()=0
Emit all sections that should come after the content.
virtual void beginFunction (const MachineFunction *MF)=0
Gather pre-function debug information.
virtual void markFunctionEnd ()
virtual void endFunction (const MachineFunction *MF)=0
Gather post-function debug information.
virtual void beginBasicBlockSection (const MachineBasicBlock &MBB)
Process the beginning of a new basic-block-section within a function.
virtual void endBasicBlockSection (const MachineBasicBlock &MBB)
Process the end of a basic-block-section within a function.
virtual void beginFunclet (const MachineBasicBlock &MBB, MCSymbol *Sym=nullptr)
Emit target-specific EH funclet machinery.
virtual void endFunclet ()
virtual void beginInstruction (const MachineInstr *MI)=0
Process beginning of an instruction.
virtual void endInstruction ()=0
Process end of an instruction.
Static Public Member Functions
static uint64_t makeTypeSignature (StringRef Identifier)
Perform an MD5 checksum of Identifier and return the lower 64 bits.
static void emitDebugLocValue (const AsmPrinter &AP, const DIBasicType *BT, const DbgValueLoc &Value, DwarfExpression &DwarfExpr)
Static Public Member Functions inherited from llvm::DebugHandlerBase
static uint64_t getBaseTypeSize (const DIType *Ty)
If this type is derived from a base type then return base type size.
static bool isUnsignedDIType (const DIType *Ty)
Return true if type encoding is unsigned.
Protected Member Functions
void beginFunctionImpl (const MachineFunction *MF) override
Gather pre-function debug information.
void endFunctionImpl (const MachineFunction *MF) override
Gather and emit post-function debug information.
unsigned getDwarfCompileUnitIDForLineTable (const DwarfCompileUnit &CU)
Get Dwarf compile unit ID for line table.
void skippedNonDebugFunction () override
Protected Member Functions inherited from llvm::DebugHandlerBase
DebugHandlerBase (AsmPrinter *A)
void identifyScopeMarkers ()
Indentify instructions that are marking the beginning of or ending of a scope.
void requestLabelBeforeInsn (const MachineInstr *MI)
Ensure that a label will be emitted before MI.
void requestLabelAfterInsn (const MachineInstr *MI)
Ensure that a label will be emitted after MI.
virtual void beginFunctionImpl (const MachineFunction *MF)=0
virtual void endFunctionImpl (const MachineFunction *MF)=0
virtual void skippedNonDebugFunction ()
Additional Inherited Members
Protected Attributes inherited from llvm::DebugHandlerBase
AsmPrinter * Asm = nullptr
Target of debug info emission.
MachineModuleInfo * MMI = nullptr
Collected machine module information.
DebugLoc PrevInstLoc
Previous instruction's location information.
MCSymbol * PrevLabel = nullptr
const MachineBasicBlock * PrevInstBB = nullptr
DebugLoc PrologEndLoc
This location indicates end of function prologue and beginning of function body.
const MachineBasicBlock * EpilogBeginBlock = nullptr
This block includes epilogue instructions.
const MachineInstr * CurMI = nullptr
If nonnull, stores the current machine instruction we're processing.
LexicalScopes LScopes
DbgValueHistoryMap DbgValues
History of DBG_VALUE and clobber instructions for each user variable.
DbgLabelInstrMap DbgLabels
Mapping of inlined labels and DBG_LABEL machine instruction.
DenseMap< const MachineInstr *, MCSymbol * > LabelsBeforeInsn
Maps instruction with label emitted before instruction.
DenseMap< const MachineInstr *, MCSymbol * > LabelsAfterInsn
Maps instruction with label emitted after instruction.
Detailed Description
Collects and handles dwarf debug information.
Definition at line 351 of file DwarfDebug.h.
Member Enumeration Documentation
DWARF5AccelTableKind
enum class llvm::DwarfDebug::DWARF5AccelTableKind strong
Enumerator
CU
TU
Definition at line 456 of file DwarfDebug.h.
MinimizeAddrInV5
enum class llvm::DwarfDebug::MinimizeAddrInV5 strong
Enumerator
Default
Disabled
Ranges
Expressions
Form
Definition at line 448 of file DwarfDebug.h.
Constructor & Destructor Documentation
DwarfDebug()
DwarfDebug::DwarfDebug (AsmPrinter * A)
Definition at line 330 of file DwarfDebug.cpp.
References A, AllLinkageNames, llvm::DebugHandlerBase::Asm, computeAccelTableKind(), llvm::DBX, llvm::TargetOptions::DebuggerTuning, llvm::Default, Default, DefaultLinkageNames, llvm::dwarf::DWARF32, llvm::dwarf::DWARF64, llvm::MCTargetOptions::Dwarf64, llvm::dwarf::DWARF_VERSION, DwarfInlinedStrings, DwarfLinkageNames, DwarfOpConvert, DwarfSectionsAsReferences, llvm::MCTargetOptions::DwarfVersion, llvm::Enable, llvm::GDB, GenerateDwarfTypeUnits, llvm::Module::getDwarfVersion(), llvm::MachineModuleInfo::getModule(), llvm::TargetMachine::getTargetTriple(), llvm::Module::isDwarf64(), llvm::LLDB, llvm::TargetOptions::MCOptions, MinimizeAddrInV5Option, llvm::DebugHandlerBase::MMI, NoDwarfRangesSection, llvm::TargetMachine::Options, llvm::AsmPrinter::OutStreamer, llvm::report_fatal_error(), llvm::SCE, llvm::TargetOptions::ShouldEmitDebugEntryValues(), llvm::MCTargetOptions::SplitDwarfFile, llvm::AsmPrinter::TM, tuneForDBX(), tuneForGDB(), tuneForLLDB(), tuneForSCE(), UseGNUDebugMacro, and useSplitDwarf().
~DwarfDebug()
DwarfDebug::~DwarfDebug () override default
Member Function Documentation
addAccelName()
void DwarfDebug::addAccelName (const DwarfUnit & Unit, const DICompileUnit::DebugNameTableKind NameTableKind, StringRef Name, const DIE & Die)
Definition at line 3603 of file DwarfDebug.cpp.
References Name.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute(), addSubprogramNames(), and llvm::DwarfCompileUnit::finishEntityDefinition().
addAccelNamespace()
void DwarfDebug::addAccelNamespace (const DwarfUnit & Unit, const DICompileUnit::DebugNameTableKind NameTableKind, StringRef Name, const DIE & Die)
Definition at line 3619 of file DwarfDebug.cpp.
References Name.
Referenced by llvm::DwarfCompileUnit::constructImportedEntityDIE(), and llvm::DwarfUnit::getOrCreateNameSpace().
addAccelObjC()
void DwarfDebug::addAccelObjC (const DwarfUnit & Unit, const DICompileUnit::DebugNameTableKind NameTableKind, StringRef Name, const DIE & Die)
Definition at line 3610 of file DwarfDebug.cpp.
References llvm::Apple, getAccelTableKind(), and Name.
Referenced by addSubprogramNames().
addAccelType()
void DwarfDebug::addAccelType (const DwarfUnit & Unit, const DICompileUnit::DebugNameTableKind NameTableKind, StringRef Name, const DIE & Die, char Flags)
Definition at line 3626 of file DwarfDebug.cpp.
References Name.
addArangeLabel()
void llvm::DwarfDebug::addArangeLabel (SymbolCU SCU) inline
Add a label so that arange data can be generated for it.
Definition at line 739 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfCompileUnit::addLocationAttribute(), and endFunctionImpl().
addDwarfTypeUnitType()
void DwarfDebug::addDwarfTypeUnitType (DwarfCompileUnit & CU, StringRef Identifier, DIE & Die, const DICompositeType * CTy)
Add a DIE to the set of types that we're going to pull into type units.
Definition at line 3448 of file DwarfDebug.cpp.
References llvm::DwarfUnit::addString(), llvm::DwarfUnit::addStringOffsetsStart(), llvm::DWARF5AccelTable::addTypeEntries(), llvm::DWARF5AccelTable::addTypeUnitSignature(), llvm::DWARF5AccelTable::addTypeUnitSymbol(), llvm::DwarfUnit::addUInt(), llvm::DebugHandlerBase::Asm, llvm::AccelTable< DataT >::clear(), llvm::DwarfFile::computeSizeAndOffsetsForUnit(), llvm::DWARF5AccelTable::convertDieToOffset(), llvm::DwarfUnit::createTypeDIE(), CU, llvm::Dwarf, llvm::DwarfFile::emitUnit(), llvm::StringRef::empty(), getAccelTableKind(), llvm::MCObjectFileInfo::getDwarfInfoDWOSection(), llvm::MCObjectFileInfo::getDwarfInfoSection(), llvm::MCObjectFileInfo::getDwarfTypesDWOSection(), llvm::MCObjectFileInfo::getDwarfTypesSection(), getDwarfVersion(), llvm::AsmPrinter::getObjFileLowering(), llvm::DIEUnit::getUnitDie(), llvm::AddressPool::hasBeenUsed(), makeTypeSignature(), llvm::TargetOptions::MCOptions, llvm::TargetMachine::Options, llvm::AddressPool::resetUsedFlag(), setCurrentDWARF5AccelTable(), llvm::DIEUnit::setSection(), llvm::DwarfTypeUnit::setType(), llvm::DwarfTypeUnit::setTypeSignature(), llvm::MCTargetOptions::SplitDwarfFile, llvm::AsmPrinter::TM, TU, useSegmentedStringOffsetsTable(), and useSplitDwarf().
Referenced by llvm::DwarfUnit::createTypeDIE().
addStringTypeLoc()
void llvm::DwarfDebug::addStringTypeLoc (const DIStringType * ST, unsigned Loc) inline
Definition at line 895 of file DwarfDebug.h.
References assert().
addSubprogramNames()
void DwarfDebug::addSubprogramNames (const DwarfUnit & Unit, const DICompileUnit::DebugNameTableKind NameTableKind, const DISubprogram * SP, DIE & Die)
Definition at line 476 of file DwarfDebug.cpp.
References addAccelName(), addAccelObjC(), llvm::DICompileUnit::Apple, llvm::Apple, llvm::DwarfFile::getAbstractScopeDIEs(), getAccelTableKind(), llvm::DIScope::getName(), getObjCClassCategory(), getObjCMethodName(), isObjCClass(), llvm::DICompileUnit::None, and useAllLinkageNames().
Referenced by llvm::DwarfCompileUnit::constructInlinedScopeDIE(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
alwaysUseRanges()
bool DwarfDebug::alwaysUseRanges (const DwarfCompileUnit & CU) const
Returns whether range encodings should be used for single entry range lists.
Definition at line 3674 of file DwarfDebug.cpp.
References Default, Ranges, and useSplitDwarf().
Referenced by llvm::DwarfCompileUnit::attachRangesOrLowHighPC().
beginFunctionImpl()
void DwarfDebug::beginFunctionImpl (const MachineFunction * MF) override protected virtual
Gather pre-function debug information.
Implements llvm::DebugHandlerBase.
Definition at line 2217 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, assert(), emitInitialLocDirective(), llvm::LexicalScopes::empty(), llvm::LexicalScopes::getCurrentFunctionScope(), getDwarfCompileUnitIDForLineTable(), llvm::MachineFunction::getFunction(), llvm::LexicalScope::getScopeNode(), llvm::Function::getSubprogram(), llvm::DebugHandlerBase::LScopes, llvm::DICompileUnit::NoDebug, llvm::AsmPrinter::OutStreamer, and llvm::DebugHandlerBase::PrologEndLoc.
beginInstruction()
void DwarfDebug::beginInstruction (const MachineInstr * MI) override virtual
Process beginning of an instruction.
Reimplemented from llvm::DebugHandlerBase.
Definition at line 2000 of file DwarfDebug.cpp.
References llvm::MachineInstr::AnyInBundle, llvm::DebugHandlerBase::Asm, assert(), llvm::DebugHandlerBase::beginInstruction(), llvm::DebugHandlerBase::CurMI, llvm::Disable, DL, DWARF2_FLAG_EPILOGUE_BEGIN, DWARF2_FLAG_IS_STMT, DWARF2_FLAG_PROLOGUE_END, llvm::Enable, llvm::DebugHandlerBase::EpilogBeginBlock, llvm::MachineInstr::FrameDestroy, llvm::MachineInstr::FrameSetup, llvm::DebugLoc::getCol(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::DebugLoc::getLine(), llvm::DebugLoc::getScope(), llvm::MachineBasicBlock::getSectionIDNum(), llvm::Function::getSubprogram(), llvm::MachineFunction::getSubtarget(), llvm::HexagonInstrInfo::isTailCall(), MBB, MI, llvm::DICompileUnit::NoDebug, llvm::AsmPrinter::OutStreamer, llvm::DebugHandlerBase::PrevInstBB, llvm::DebugHandlerBase::PrevInstLoc, llvm::DebugHandlerBase::PrevLabel, llvm::DebugHandlerBase::PrologEndLoc, llvm::DebugHandlerBase::requestLabelAfterInsn(), llvm::DebugHandlerBase::requestLabelBeforeInsn(), TII, and UnknownLocations.
beginModule()
void DwarfDebug::beginModule (Module * M) override virtual
Emit all Dwarf sections that should come prior to the content.
Reimplemented from llvm::DebugHandlerBase.
Definition at line 1145 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, assert(), llvm::DebugHandlerBase::beginModule(), llvm::AsmPrinter::createTempSymbol(), getDwarfVersion(), llvm::Global, llvm::MachineModuleInfo::hasDebugInfo(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::DebugHandlerBase::MMI, llvm::AddressPool::setLabel(), llvm::DwarfFile::setRnglistsTableBaseSym(), llvm::DebugLocStream::setSym(), sortGlobalExprs(), useSegmentedStringOffsetsTable(), and useSplitDwarf().
emitDebugEntryValues()
bool llvm::DwarfDebug::emitDebugEntryValues () const inline
Definition at line 818 of file DwarfDebug.h.
emitDebugLocEntry()
void DwarfDebug::emitDebugLocEntry (ByteStreamer & Streamer, const DebugLocStream::Entry & Entry, const DwarfCompileUnit * CU)
Emit an entry for the debug loc section.
This can be used to handle an entry that's going to be emitted into the debug loc section.
Definition at line 2591 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, assert(), llvm::ArrayRef< T >::data(), llvm::Data, llvm::ByteStreamer::emitDIERef(), llvm::ByteStreamer::emitInt8(), End, llvm::DebugLocStream::getBytes(), llvm::DWARFExpression::Operation::getCode(), llvm::MCAsmInfo::getCodePointerSize(), llvm::DebugLocStream::getComments(), llvm::AsmPrinter::getDataLayout(), llvm::DWARFExpression::Operation::getDescription(), llvm::MCContext::getDwarfFormat(), llvm::DWARFExpression::Operation::getEndOffset(), llvm::DWARFExpression::Operation::getOperandEndOffset(), llvm::DWARFExpression::Operation::getRawOperand(), llvm::DWARFExpression::Operation::getSubCode(), I, llvm::DataLayout::isLittleEndian(), llvm::Length, llvm::AsmPrinter::MAI, llvm::Offset, llvm::DWARFExpression::Operation::Description::Op, llvm::AsmPrinter::OutContext, and llvm::ArrayRef< T >::size().
Referenced by emitDebugLocEntryLocation().
emitDebugLocEntryLocation()
void DwarfDebug::emitDebugLocEntryLocation (const DebugLocStream::Entry & Entry, const DwarfCompileUnit * CU)
Emit the location for a debug loc entry, including the size header.
Definition at line 2760 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, emitDebugLocEntry(), llvm::AsmPrinter::emitInt16(), llvm::AsmPrinter::emitULEB128(), llvm::DebugLocStream::getBytes(), getDwarfVersion(), llvm::AsmPrinter::OutStreamer, and llvm::ArrayRef< T >::size().
emitDebugLocValue()
void DwarfDebug::emitDebugLocValue (const AsmPrinter & AP, const DIBasicType * BT, const DbgValueLoc & Value, DwarfExpression & DwarfExpr) static
Definition at line 2635 of file DwarfDebug.cpp.
References llvm::DwarfExpression::addConstantFP(), llvm::DwarfExpression::addExpression(), llvm::DwarfExpression::addFragmentOffset(), llvm::DwarfExpression::addMachineRegExpression(), llvm::DwarfExpression::addSignedConstant(), llvm::DwarfExpression::addUnsignedConstant(), llvm::DwarfExpression::addWasmLocation(), llvm::any_of(), assert(), llvm::DwarfExpression::beginEntryValueExpression(), llvm::dbgs(), llvm::AsmPrinter::getDwarfDebug(), llvm::AsmPrinter::getDwarfVersion(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getTargetTriple(), Idx, llvm::TargetIndexLocation::Index, llvm::Triple::isWasm(), LLVM_DEBUG, llvm::AsmPrinter::MF, llvm::TargetIndexLocation::Offset, llvm::DwarfExpression::setLocation(), llvm::DwarfExpression::setMemoryLocationKind(), llvm::AsmPrinter::TM, TRI, and tuneForSCE().
Referenced by llvm::DwarfCompileUnit::constructCallSiteParmEntryDIEs(), and llvm::DebugLocEntry::finalize().
emitInitialLocDirective()
DebugLoc DwarfDebug::emitInitialLocDirective (const MachineFunction & MF, unsigned CUID)
Emits inital debug location directive.
Definition at line 2189 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, DWARF2_FLAG_IS_STMT, findPrologueEndLoc(), getDwarfVersion(), llvm::MachineFunction::getFunction(), llvm::Function::getSubprogram(), and llvm::DebugHandlerBase::PrologEndLoc.
Referenced by beginFunctionImpl(), and llvm::AsmPrinter::emitInitialRawDwarfLocDirective().
endFunctionImpl()
void DwarfDebug::endFunctionImpl (const MachineFunction * MF) override protected virtual
Gather and emit post-function debug information.
Implements llvm::DebugHandlerBase.
Definition at line 2268 of file DwarfDebug.cpp.
References addArangeLabel(), llvm::DwarfCompileUnit::addRange(), llvm::DebugHandlerBase::Asm, assert(), llvm::DwarfCompileUnit::constructSubprogramScopeDIE(), llvm::DwarfCompileUnit::createAbstractEntity(), llvm::LexicalScopes::getAbstractScopesList(), llvm::DwarfUnit::getCUNode(), llvm::LexicalScopes::getCurrentFunctionScope(), llvm::DICompileUnit::getDebugInfoForProfiling(), llvm::DICompileUnit::getEmissionKind(), llvm::DwarfCompileUnit::getExistingAbstractEntity(), llvm::MachineFunction::getFunction(), llvm::LexicalScopes::getOrCreateAbstractScope(), getRetainedNodeScope(), llvm::DwarfFile::getScopeLabels(), llvm::LexicalScope::getScopeNode(), llvm::DwarfFile::getScopeVariables(), llvm::DwarfCompileUnit::getSkeleton(), llvm::DICompileUnit::getSplitDebugInlining(), llvm::Function::getSubprogram(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::DICompileUnit::isDebugDirectivesOnly(), llvm::DICompileUnit::LineTablesOnly, llvm::DebugHandlerBase::LScopes, llvm::AsmPrinter::MBBSectionRanges, llvm::AsmPrinter::OutStreamer, and llvm::DebugHandlerBase::PrevLabel.
endModule()
void DwarfDebug::endModule () override virtual
Emit all Dwarf sections that should come after the content.
Implements llvm::AsmPrinterHandler.
Definition at line 1402 of file DwarfDebug.cpp.
References llvm::Apple, llvm::DebugHandlerBase::Asm, assert(), llvm::DebugHandlerBase::CurMI, D, llvm::Default, llvm::Dwarf, GenerateARangeSection, getAccelTableKind(), llvm::MachineModuleInfo::hasDebugInfo(), llvm_unreachable, llvm::DebugHandlerBase::MMI, llvm::None, P, terminateLineTable(), and useSplitDwarf().
generateTypeUnits()
bool llvm::DwarfDebug::generateTypeUnits () const inline
Returns whether to generate DWARF v4 type units.
Definition at line 790 of file DwarfDebug.h.
Referenced by llvm::DwarfUnit::createTypeDIE(), and llvm::DwarfUnit::isShareableAcrossCUs().
getAccelTableKind()
AccelTableKind llvm::DwarfDebug::getAccelTableKind () const inline
Returns what kind (if any) of accelerator tables to emit.
Definition at line 795 of file DwarfDebug.h.
Referenced by addAccelObjC(), addDwarfTypeUnitType(), addSubprogramNames(), endModule(), and llvm::DwarfCompileUnit::hasDwarfPubSections().
getAddressPool()
AddressPool & llvm::DwarfDebug::getAddressPool () inline
Definition at line 861 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addAddrTableBase(), llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfUnit::addPoolOpAddress(), and emitRangeList().
getCurrentDWARF5AccelTable()
DWARF5AccelTable & llvm::DwarfDebug::getCurrentDWARF5AccelTable () inline
Returns either CU or TU DWARF5AccelTable.
Definition at line 937 of file DwarfDebug.h.
getCurrentFunction()
const MachineFunction * llvm::DwarfDebug::getCurrentFunction () const inline
Definition at line 879 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
getDebugLocs()
const DebugLocStream & llvm::DwarfDebug::getDebugLocs () const inline
Returns the entries for the .debug_loc section.
Definition at line 845 of file DwarfDebug.h.
Referenced by emitLocList(), emitLoclistsTableHeader(), and llvm::DIELocList::emitValue().
getDwarfCompileUnitIDForLineTable()
unsigned DwarfDebug::getDwarfCompileUnitIDForLineTable (const DwarfCompileUnit & CU) protected
Get Dwarf compile unit ID for line table.
Definition at line 2236 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, and llvm::AsmPrinter::OutStreamer.
Referenced by beginFunctionImpl(), and terminateLineTable().
getDwarfSectionOffsetForm()
dwarf::Form DwarfDebug::getDwarfSectionOffsetForm () const
Returns a suitable DWARF form to represent a section offset, i.e.
DW_FORM_sec_offset for DWARF version >= 4;
DW_FORM_data8 for 64-bit DWARFv3;
DW_FORM_data4 for 32-bit DWARFv3 and DWARFv2.
Definition at line 3637 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, assert(), llvm::AsmPrinter::getDwarfVersion(), and llvm::AsmPrinter::isDwarf64().
Referenced by llvm::DwarfCompileUnit::addLocationList(), llvm::DwarfUnit::addSectionDelta(), llvm::DwarfUnit::addSectionLabel(), and llvm::DwarfUnit::addSectionOffset().
getDwarfVersion()
uint16_t DwarfDebug::getDwarfVersion () const
Returns the Dwarf Version.
Definition at line 3633 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, and llvm::AsmPrinter::OutStreamer.
Referenced by llvm::DwarfCompileUnit::addAddrTableBase(), llvm::DwarfUnit::addAttribute(), llvm::DwarfUnit::addBlock(), addDwarfTypeUnitType(), llvm::DwarfUnit::addFlag(), llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfUnit::addLinkageName(), llvm::DwarfCompileUnit::addLocationList(), llvm::DwarfUnit::addOpAddress(), llvm::DwarfUnit::addPoolOpAddress(), llvm::DwarfUnit::addRnglistsBase(), llvm::DwarfCompileUnit::addScopeRangeList(), llvm::DwarfUnit::applySubprogramAttributes(), llvm::DwarfCompileUnit::attachLowHighPC(), beginModule(), llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE(), llvm::DwarfCompileUnit::constructInlinedScopeDIE(), llvm::DwarfUnit::constructTypeDIE(), llvm::DwarfUnit::emitCommonHeader(), emitDebugLocEntryLocation(), llvm::DwarfCompileUnit::emitHeader(), emitInitialLocDirective(), emitRangeList(), GetCompileUnitType(), llvm::DwarfUnit::getHeaderSize(), llvm::DwarfCompileUnit::getHeaderSize(), getMD5AsBytes(), llvm::DwarfUnit::getOrCreateTypeDIE(), llvm::DwarfCompileUnit::hasDwarfPubSections(), insertSectionLabel(), and llvm::DwarfCompileUnit::useGNUAnalogForDwarf5Feature().
getLocalDeclsForScope()
MDNodeSet & llvm::DwarfDebug::getLocalDeclsForScope (const DILocalScope * S) inline
Definition at line 922 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::createAndAddScopeChildren().
getMD5AsBytes()
std::optional< MD5::MD5Result > DwarfDebug::getMD5AsBytes (const DIFile * File) const
If the File has an MD5 checksum, return it as an MD5Result allocated in the MCContext.
Definition at line 3657 of file DwarfDebug.cpp.
References assert(), llvm::DIFile::CSK_MD5, and getDwarfVersion().
Referenced by llvm::DwarfCompileUnit::getOrCreateSourceID().
getPrevCU()
const DwarfCompileUnit * llvm::DwarfDebug::getPrevCU () const inline
Returns the previous CU that was being updated.
Definition at line 838 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addRange().
getSectionLabel()
const MCSymbol * DwarfDebug::getSectionLabel (const MCSection * S)
Definition at line 3646 of file DwarfDebug.cpp.
Referenced by llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfUnit::addPoolOpAddress(), llvm::DwarfCompileUnit::attachRangesOrLowHighPC(), and emitRangeList().
getStringTypeLoc()
unsigned llvm::DwarfDebug::getStringTypeLoc (const DIStringType * ST) const inline
Definition at line 891 of file DwarfDebug.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
insertSectionLabel()
void DwarfDebug::insertSectionLabel (const MCSymbol * S)
Definition at line 3650 of file DwarfDebug.cpp.
References getDwarfVersion(), llvm::AddressPool::getIndex(), llvm::MCSymbol::getSection(), and useSplitDwarf().
Referenced by llvm::DwarfCompileUnit::addRange().
isLexicalScopeDIENull()
bool DwarfDebug::isLexicalScopeDIENull (LexicalScope * Scope)
A helper function to check whether the DIE for a given Scope is going to be null.
Check whether we should create a DIE for the given Scope, return true if we don't create a DIE (the corresponding DIE is null).
Definition at line 513 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::getLabelAfterInsn(), and Ranges.
Referenced by llvm::DwarfCompileUnit::constructLexicalScopeDIE(), and llvm::DwarfCompileUnit::constructScopeDIE().
lookupCU() [1/2]
DwarfCompileUnit * llvm::DwarfDebug::lookupCU (const DIE * Die) inline
Find the matching DwarfCompileUnit for the given CU DIE.
Definition at line 886 of file DwarfDebug.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
Referenced by llvm::DwarfCompileUnit::constructAbstractSubprogramScopeDIE().
lookupCU() [2/2]
const DwarfCompileUnit * llvm::DwarfDebug::lookupCU (const DIE * Die) const inline
Definition at line 887 of file DwarfDebug.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup().
makeTypeSignature()
uint64_t DwarfDebug::makeTypeSignature (StringRef Identifier) static
Perform an MD5 checksum of Identifier and return the lower 64 bits.
Definition at line 3437 of file DwarfDebug.cpp.
References llvm::MD5::final(), and llvm::MD5::update().
Referenced by addDwarfTypeUnitType().
setCurrentDWARF5AccelTable()
void llvm::DwarfDebug::setCurrentDWARF5AccelTable (const DWARF5AccelTableKind Kind) inline
Sets the current DWARF5AccelTable to use.
Definition at line 927 of file DwarfDebug.h.
References CU, and TU.
Referenced by addDwarfTypeUnitType().
setPrevCU()
void llvm::DwarfDebug::setPrevCU (const DwarfCompileUnit * PrevCU) inline
Definition at line 839 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addRange().
setSymbolSize()
void llvm::DwarfDebug::setSymbolSize (const MCSymbol * Sym, uint64_t Size) inline override virtual
For symbols that have a size designated (e.g.
common symbols), this tracks that size.
Implements llvm::AsmPrinterHandler.
Definition at line 743 of file DwarfDebug.h.
References Size, and Sym.
setTheAccelTableKind()
void llvm::DwarfDebug::setTheAccelTableKind (AccelTableKind K) inline
Seet TheAccelTableKind.
Definition at line 798 of file DwarfDebug.h.
shareAcrossDWOCUs()
bool DwarfDebug::shareAcrossDWOCUs () const
Definition at line 537 of file DwarfDebug.cpp.
References SplitDwarfCrossCuReferences.
Referenced by llvm::DwarfUnit::addDIEEntry(), and llvm::DwarfUnit::isShareableAcrossCUs().
skippedNonDebugFunction()
void DwarfDebug::skippedNonDebugFunction () override protected virtual
Reimplemented from llvm::DebugHandlerBase.
Definition at line 2256 of file DwarfDebug.cpp.
References terminateLineTable().
terminateLineTable()
void DwarfDebug::terminateLineTable (const DwarfCompileUnit * CU)
Terminate the line table by adding the last range label.
Definition at line 2247 of file DwarfDebug.cpp.
References llvm::DebugHandlerBase::Asm, getDwarfCompileUnitIDForLineTable(), and llvm::AsmPrinter::OutStreamer.
Referenced by llvm::DwarfCompileUnit::addRange(), endModule(), and skippedNonDebugFunction().
useAddrOffsetExpressions()
bool llvm::DwarfDebug::useAddrOffsetExpressions () const inline
Definition at line 771 of file DwarfDebug.h.
References Expressions.
Referenced by llvm::DwarfCompileUnit::addLabelAddress(), and llvm::DwarfUnit::addPoolOpAddress().
useAddrOffsetForm()
bool llvm::DwarfDebug::useAddrOffsetForm () const inline
Definition at line 777 of file DwarfDebug.h.
References Form.
Referenced by llvm::DwarfCompileUnit::addLabelAddress(), and llvm::DwarfUnit::addPoolOpAddress().
useAllLinkageNames()
bool llvm::DwarfDebug::useAllLinkageNames () const inline
Returns whether we should emit all DW_AT_[MIPS_]linkage_name.
If not, we still might emit certain cases.
Definition at line 749 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute(), addSubprogramNames(), and llvm::DwarfUnit::applySubprogramDefinitionAttributes().
useAppleExtensionAttributes()
bool llvm::DwarfDebug::useAppleExtensionAttributes () const inline
Definition at line 800 of file DwarfDebug.h.
Referenced by llvm::DwarfUnit::applySubprogramAttributes(), and llvm::DwarfCompileUnit::updateSubprogramScopeDIE().
useDWARF2Bitfields()
bool llvm::DwarfDebug::useDWARF2Bitfields () const inline
Returns whether to use the DWARF2 format for bitfields instyead of the DWARF4 format.
Definition at line 757 of file DwarfDebug.h.
useGNUTLSOpcode()
bool llvm::DwarfDebug::useGNUTLSOpcode () const inline
Returns whether to use DW_OP_GNU_push_tls_address, instead of the standard DW_OP_form_tls_address opcode.
Definition at line 753 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::addLocationAttribute().
useInlineStrings()
bool llvm::DwarfDebug::useInlineStrings () const inline
Returns whether to use inline strings.
Definition at line 760 of file DwarfDebug.h.
Referenced by llvm::DwarfUnit::addString().
useLocSection()
bool llvm::DwarfDebug::useLocSection () const inline
Returns whether .debug_loc section should be emitted.
Definition at line 787 of file DwarfDebug.h.
useOpConvert()
bool llvm::DwarfDebug::useOpConvert () const inline
Definition at line 822 of file DwarfDebug.h.
useRangesSection()
bool llvm::DwarfDebug::useRangesSection () const inline
Returns whether ranges section should be emitted.
Definition at line 763 of file DwarfDebug.h.
Referenced by llvm::DwarfCompileUnit::attachRangesOrLowHighPC().
useSectionsAsReferences()
bool llvm::DwarfDebug::useSectionsAsReferences () const inline
Returns whether to use sections as labels rather than temp symbols.
Definition at line 782 of file DwarfDebug.h.
Referenced by llvm::DwarfUnit::emitCommonHeader(), llvm::DwarfCompileUnit::emitHeader(), and llvm::DwarfCompileUnit::initStmtList().
useSegmentedStringOffsetsTable()
bool llvm::DwarfDebug::useSegmentedStringOffsetsTable () const inline
Returns whether to generate a string offsets table with (possibly shared) contributions from each CU and type unit.
This implies the use of DW_FORM_strx* indirect references with DWARF v5 and beyond. Note that DW_FORM_GNU_str_index is also an indirect reference, but it is used with a pre-DWARF v5 implementation of split DWARF sections, which uses a monolithic string offsets table.
Definition at line 814 of file DwarfDebug.h.
Referenced by addDwarfTypeUnitType(), beginModule(), and llvm::DwarfUnit::useSegmentedStringOffsetsTable().
useSplitDwarf()
bool llvm::DwarfDebug::useSplitDwarf () const inline
Returns whether or not to change the current debug info for the split dwarf proposal support.
Definition at line 806 of file DwarfDebug.h.
Referenced by llvm::DwarfUnit::addDIEEntry(), addDwarfTypeUnitType(), llvm::DwarfCompileUnit::addLabelAddress(), llvm::DwarfCompileUnit::addLocationAttribute(), llvm::DwarfUnit::addOpAddress(), alwaysUseRanges(), beginModule(), DwarfDebug(), llvm::emitDWARF5AccelTable(), llvm::DwarfCompileUnit::emitHeader(), llvm::DwarfTypeUnit::emitHeader(), emitMacroHeader(), llvm::DIELocList::emitValue(), endModule(), llvm::DwarfCompileUnit::getHeaderSize(), llvm::DwarfCompileUnit::includeMinimalInlineScopes(), and insertSectionLabel().
The documentation for this class was generated from the following files:
lib/CodeGen/AsmPrinter/DwarfDebug.h
lib/CodeGen/AsmPrinter/DwarfDebug.cpp