LLVM: llvm::GCNSchedStrategy Class Reference
llvm::GCNSchedStrategy Class Reference
This is a minimal scheduler strategy.
#include "Target/AMDGPU/GCNSchedStrategy.h"
Public Member Functions
GCNSchedStrategy (const MachineSchedContext *C)
SUnit * pickNode (bool &IsTopNode) override
Pick the best node to balance the schedule. Implements MachineSchedStrategy.
void initialize (ScheduleDAGMI *DAG) override
Initialize the strategy after building the DAG for a new region.
unsigned getTargetOccupancy ()
void setTargetOccupancy (unsigned Occ)
GCNSchedStageID getCurrentStage ()
bool advanceStage ()
bool hasNextStage () const
GCNSchedStageID getNextStage () const
Public Member Functions inherited from llvm::GenericScheduler
GenericScheduler (const MachineSchedContext *C)
void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs) override
Initialize the per-region scheduling policy.
void dumpPolicy () const override
bool shouldTrackPressure () const override
Check if pressure tracking is needed before building the DAG and initializing this strategy.
bool shouldTrackLaneMasks () const override
Returns true if lanemasks should be tracked.
void initialize (ScheduleDAGMI *dag) override
Initialize the strategy after building the DAG for a new region.
SUnit * pickNode (bool &IsTopNode) override
Pick the best node to balance the schedule. Implements MachineSchedStrategy.
void schedNode (SUnit *SU, bool IsTopNode) override
Update the scheduler's state after scheduling a node.
void releaseTopNode (SUnit *SU) override
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
void releaseBottomNode (SUnit *SU) override
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
void registerRoots () override
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()=default
virtual void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs)
Optionally override the per-region scheduling policy.
virtual void dumpPolicy () const
virtual bool shouldTrackPressure () const
Check if pressure tracking is needed before building the DAG and initializing this strategy.
virtual bool shouldTrackLaneMasks () const
Returns true if lanemasks should be tracked.
virtual bool doMBBSchedRegionsTopDown () const
virtual void initialize (ScheduleDAGMI *DAG)=0
Initialize the strategy after building the DAG for a new region.
virtual void enterMBB (MachineBasicBlock *MBB)
Tell the strategy that MBB is about to be processed.
virtual void leaveMBB ()
Tell the strategy that current MBB is done.
virtual void registerRoots ()
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
virtual SUnit * pickNode (bool &IsTopNode)=0
Pick the next node to schedule, or return NULL.
virtual void scheduleTree (unsigned SubtreeID)
Scheduler callback to notify that a new subtree is scheduled.
virtual void schedNode (SUnit *SU, bool IsTopNode)=0
Notify MachineSchedStrategy that ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
virtual void releaseTopNode (SUnit *SU)=0
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
virtual void releaseBottomNode (SUnit *SU)=0
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Public Attributes
bool HasHighPressure
bool KnownExcessRP = false
unsigned ErrorMargin = 3
const unsigned HighRPSGPRBias = 7
const unsigned HighRPVGPRBias = 7
unsigned SGPRCriticalLimit
unsigned VGPRCriticalLimit
unsigned SGPRLimitBias = 0
unsigned VGPRLimitBias = 0
Protected Member Functions
SUnit * pickNodeBidirectional (bool &IsTopNode)
void pickNodeFromQueue (SchedBoundary &Zone, const CandPolicy &ZonePolicy, const RegPressureTracker &RPTracker, SchedCandidate &Cand)
void initCandidate (SchedCandidate &Cand, SUnit *SU, bool AtTop, const RegPressureTracker &RPTracker, const SIRegisterInfo *SRI, unsigned SGPRPressure, unsigned VGPRPressure)
Protected Member Functions inherited from llvm::GenericScheduler
void checkAcyclicLatency ()
Set IsAcyclicLatencyLimited if the acyclic path is longer than the cyclic critical path by more cycles than it takes to drain the instruction buffer.
void initCandidate (SchedCandidate &Cand, SUnit *SU, bool AtTop, const RegPressureTracker &RPTracker, RegPressureTracker &TempTracker)
virtual bool tryCandidate (SchedCandidate &Cand, SchedCandidate &TryCand, SchedBoundary *Zone) const
Apply a set of heuristics to a new candidate.
SUnit * pickNodeBidirectional (bool &IsTopNode)
Pick the best candidate node from either the top or bottom queue.
void pickNodeFromQueue (SchedBoundary &Zone, const CandPolicy &ZonePolicy, const RegPressureTracker &RPTracker, SchedCandidate &Candidate)
Pick the best candidate from the queue.
void reschedulePhysReg (SUnit *SU, bool isTop)
Protected Member Functions inherited from llvm::GenericSchedulerBase
GenericSchedulerBase (const MachineSchedContext *C)
void setPolicy (CandPolicy &Policy, bool IsPostRA, SchedBoundary &CurrZone, SchedBoundary *OtherZone)
Set the CandPolicy given a scheduling zone given the current resources and latencies inside and outside the zone.
void traceCandidate (const SchedCandidate &Cand)
Protected Attributes
std::vector< unsigned > Pressure
std::vector< unsigned > MaxPressure
unsigned SGPRExcessLimit
unsigned VGPRExcessLimit
unsigned TargetOccupancy
MachineFunction * MF
SmallVector< GCNSchedStageID, 4 > SchedStages
SmallVectorImpl< GCNSchedStageID >::iterator CurrentStage = nullptr
Protected Attributes inherited from llvm::GenericScheduler
ScheduleDAGMILive * DAG = nullptr
MachineSchedPolicy RegionPolicy
SchedBoundary Top
SchedBoundary Bot
SchedCandidate TopCand
Candidate last picked from Top boundary.
SchedCandidate BotCand
Candidate last picked from Bot boundary.
Protected Attributes inherited from llvm::GenericSchedulerBase
const MachineSchedContext * Context
const TargetSchedModel * SchedModel = nullptr
const TargetRegisterInfo * TRI = nullptr
SchedRemainder Rem
Additional Inherited Members
Public Types inherited from llvm::GenericSchedulerBase
enum CandReason : uint8_t {
NoCand , Only1 , PhysReg , RegExcess ,
RegCritical , Stall , Cluster , Weak ,
RegMax , ResourceReduce , ResourceDemand , BotHeightReduce ,
BotPathReduce , TopDepthReduce , TopPathReduce , NextDefUse ,
NodeOrder
}
Represent the type of SchedCandidate found within a single queue.
Static Public Member Functions inherited from llvm::GenericSchedulerBase
static const char * getReasonStr (GenericSchedulerBase::CandReason Reason)
Detailed Description
This is a minimal scheduler strategy.
The main difference between this and the GenericScheduler is that GCNSchedStrategy uses different heuristics to determine excess/critical pressure sets.
Definition at line 42 of file GCNSchedStrategy.h.
Constructor & Destructor Documentation
GCNSchedStrategy()
GCNSchedStrategy::GCNSchedStrategy (const MachineSchedContext * C)
Definition at line 63 of file GCNSchedStrategy.cpp.
Member Function Documentation
advanceStage()
bool GCNSchedStrategy::advanceStage ()
Definition at line 365 of file GCNSchedStrategy.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), CurrentStage, llvm::SmallVectorTemplateCommon< T, typename >::end(), and SchedStages.
getCurrentStage()
GCNSchedStageID GCNSchedStrategy::getCurrentStage ()
Definition at line 360 of file GCNSchedStrategy.cpp.
References assert(), CurrentStage, llvm::SmallVectorTemplateCommon< T, typename >::end(), and SchedStages.
getNextStage()
GCNSchedStageID GCNSchedStrategy::getNextStage () const
Definition at line 380 of file GCNSchedStrategy.cpp.
References assert(), CurrentStage, llvm::SmallVectorTemplateCommon< T, typename >::end(), and SchedStages.
Referenced by llvm::GCNSchedStage::revertScheduling().
getTargetOccupancy()
unsigned llvm::GCNSchedStrategy::getTargetOccupancy () inline
Definition at line 107 of file GCNSchedStrategy.h.
References TargetOccupancy.
Referenced by llvm::GCNSchedStage::checkScheduling(), and llvm::UnclusteredHighRPStage::shouldRevertScheduling().
hasNextStage()
bool GCNSchedStrategy::hasNextStage () const
Definition at line 375 of file GCNSchedStrategy.cpp.
References assert(), CurrentStage, llvm::SmallVectorTemplateCommon< T, typename >::end(), and SchedStages.
Referenced by llvm::PreRARematStage::initGCNSchedStage(), and llvm::GCNSchedStage::revertScheduling().
initCandidate()
void GCNSchedStrategy::initCandidate (SchedCandidate & Cand, SUnit * SU, bool AtTop, const RegPressureTracker & RPTracker, const SIRegisterInfo * SRI, unsigned SGPRPressure, unsigned VGPRPressure) protected
Definition at line 119 of file GCNSchedStrategy.cpp.
References llvm::GenericSchedulerBase::SchedCandidate::AtTop, llvm::RegPressureDelta::CriticalMax, llvm::GenericScheduler::DAG, llvm::RegPressureDelta::Excess, llvm::RegPressureTracker::getDownwardPressure(), llvm::SUnit::getInstr(), llvm::RegPressureTracker::getUpwardPressure(), HasHighPressure, llvm::ScheduleDAGMILive::isTrackingPressure(), MaxPressure, Pressure, llvm::GenericSchedulerBase::SchedCandidate::RPDelta, llvm::PressureChange::setUnitInc(), SGPRCriticalLimit, SGPRExcessLimit, llvm::GenericSchedulerBase::SchedCandidate::SU, VGPRCriticalLimit, and VGPRExcessLimit.
Referenced by pickNodeFromQueue().
initialize()
void GCNSchedStrategy::initialize (ScheduleDAGMI * DAG) override virtual
Initialize the strategy after building the DAG for a new region.
Reimplemented from llvm::GenericScheduler.
Definition at line 67 of file GCNSchedStrategy.cpp.
References llvm::alignDown(), llvm::GenericSchedulerBase::Context, llvm::GenericScheduler::DAG, llvm::dbgs(), ErrorMargin, llvm::AMDGPU::IsaInfo::getAddressableNumVGPRs(), llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getMinAllowedOccupancy(), llvm::RegisterClassInfo::getNumAllocatableRegs(), llvm::SIMachineFunctionInfo::getOccupancy(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPU::IsaInfo::getVGPRAllocGranule(), llvm::GenericScheduler::initialize(), KnownExcessRP, LLVM_DEBUG, llvm::ScheduleDAG::MF, MF, llvm::MachineSchedContext::RegClassInfo, RelaxedOcc, SGPRCriticalLimit, SGPRExcessLimit, SGPRLimitBias, TargetOccupancy, VGPRCriticalLimit, VGPRExcessLimit, and VGPRLimitBias.
pickNode()
SUnit * GCNSchedStrategy::pickNode (bool & IsTopNode) override virtual
Pick the best node to balance the schedule. Implements MachineSchedStrategy.
Reimplemented from llvm::GenericScheduler.
Definition at line 317 of file GCNSchedStrategy.cpp.
References assert(), llvm::SchedBoundary::Available, llvm::GenericScheduler::Bot, llvm::GenericScheduler::BotCand, llvm::ScheduleDAGMI::bottom(), llvm::GenericScheduler::DAG, llvm::dbgs(), llvm::ReadyQueue::empty(), llvm::ScheduleDAGMILive::getBotRPTracker(), llvm::SUnit::getInstr(), llvm::ScheduleDAGMILive::getTopRPTracker(), llvm::SUnit::isBottomReady(), llvm::SUnit::isScheduled, llvm::SUnit::isTopReady(), LLVM_DEBUG, llvm::GenericSchedulerBase::NoCand, llvm::SUnit::NodeNum, llvm::MachineSchedPolicy::OnlyBottomUp, llvm::MachineSchedPolicy::OnlyTopDown, llvm::SchedBoundary::Pending, pickNodeBidirectional(), pickNodeFromQueue(), llvm::SchedBoundary::pickOnlyChoice(), llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericScheduler::RegionPolicy, llvm::SchedBoundary::removeReady(), llvm::GenericSchedulerBase::SchedCandidate::reset(), llvm::GenericSchedulerBase::SchedCandidate::SU, llvm::ScheduleDAGMI::top(), llvm::GenericScheduler::Top, and llvm::GenericScheduler::TopCand.
pickNodeBidirectional()
SUnit * GCNSchedStrategy::pickNodeBidirectional (bool & IsTopNode) protected
Definition at line 240 of file GCNSchedStrategy.cpp.
References assert(), llvm::GenericScheduler::Bot, llvm::GenericScheduler::BotCand, llvm::GenericScheduler::DAG, llvm::dbgs(), llvm::ScheduleDAGMILive::getBotRPTracker(), llvm::ScheduleDAGMILive::getTopRPTracker(), llvm::SUnit::isScheduled, llvm::GenericSchedulerBase::SchedCandidate::isValid(), LLVM_DEBUG, llvm::GenericSchedulerBase::NoCand, pickNodeFromQueue(), llvm::SchedBoundary::pickOnlyChoice(), llvm::GenericSchedulerBase::SchedCandidate::Policy, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericSchedulerBase::SchedCandidate::reset(), llvm::GenericSchedulerBase::setPolicy(), llvm::GenericSchedulerBase::SchedCandidate::SU, llvm::GenericScheduler::Top, llvm::GenericScheduler::TopCand, llvm::GenericSchedulerBase::traceCandidate(), llvm::GenericScheduler::tryCandidate(), and llvm::VerifyScheduling.
Referenced by pickNode().
pickNodeFromQueue()
void GCNSchedStrategy::pickNodeFromQueue (SchedBoundary & Zone, const CandPolicy & ZonePolicy, const RegPressureTracker & RPTracker, SchedCandidate & Cand) protected
Definition at line 207 of file GCNSchedStrategy.cpp.
References llvm::GenericSchedulerBase::SchedCandidate::AtTop, llvm::SchedBoundary::Available, llvm::SchedBoundary::DAG, llvm::GenericScheduler::DAG, llvm::RegPressureTracker::getRegSetPressureAtPos(), initCandidate(), llvm::GenericSchedulerBase::SchedCandidate::initResourceDelta(), llvm::SchedBoundary::isTop(), llvm::ScheduleDAGMILive::isTrackingPressure(), LLVM_DEBUG, llvm::GenericSchedulerBase::NoCand, Pressure, llvm::GenericSchedulerBase::SchedCandidate::Reason, llvm::GenericSchedulerBase::SchedCandidate::ResDelta, llvm::GenericSchedulerBase::SchedModel, llvm::GenericSchedulerBase::SchedCandidate::setBest(), llvm::GenericSchedulerBase::traceCandidate(), llvm::GenericSchedulerBase::TRI, and llvm::GenericScheduler::tryCandidate().
Referenced by pickNode(), and pickNodeBidirectional().
setTargetOccupancy()
void llvm::GCNSchedStrategy::setTargetOccupancy (unsigned Occ) inline
Definition at line 109 of file GCNSchedStrategy.h.
References TargetOccupancy.
Referenced by llvm::GCNIterativeScheduler::scheduleLegacyMaxOccupancy().
Member Data Documentation
CurrentStage
SmallVectorImpl<GCNSchedStageID>::iterator llvm::GCNSchedStrategy::CurrentStage = nullptr protected
Definition at line 71 of file GCNSchedStrategy.h.
Referenced by advanceStage(), getCurrentStage(), getNextStage(), and hasNextStage().
ErrorMargin
unsigned llvm::GCNSchedStrategy::ErrorMargin = 3
Definition at line 85 of file GCNSchedStrategy.h.
Referenced by initialize().
HasHighPressure
bool llvm::GCNSchedStrategy::HasHighPressure
Definition at line 76 of file GCNSchedStrategy.h.
Referenced by llvm::GCNSchedStage::finalizeGCNRegion(), initCandidate(), and llvm::GCNSchedStage::initGCNRegion().
HighRPSGPRBias
const unsigned llvm::GCNSchedStrategy::HighRPSGPRBias = 7
Definition at line 88 of file GCNSchedStrategy.h.
Referenced by llvm::UnclusteredHighRPStage::initGCNSchedStage().
HighRPVGPRBias
const unsigned llvm::GCNSchedStrategy::HighRPVGPRBias = 7
Definition at line 91 of file GCNSchedStrategy.h.
Referenced by llvm::UnclusteredHighRPStage::initGCNSchedStage().
KnownExcessRP
bool llvm::GCNSchedStrategy::KnownExcessRP = false
Definition at line 80 of file GCNSchedStrategy.h.
Referenced by llvm::GCNSchedStage::initGCNRegion(), and initialize().
MaxPressure
std::vector<unsigned> llvm::GCNSchedStrategy::MaxPressure protected
Definition at line 57 of file GCNSchedStrategy.h.
Referenced by initCandidate().
MF
MachineFunction* llvm::GCNSchedStrategy::MF protected
Definition at line 65 of file GCNSchedStrategy.h.
Referenced by initialize().
Pressure
std::vector<unsigned> llvm::GCNSchedStrategy::Pressure protected
Definition at line 55 of file GCNSchedStrategy.h.
Referenced by initCandidate(), and pickNodeFromQueue().
SchedStages
SmallVector<GCNSchedStageID, 4> llvm::GCNSchedStrategy::SchedStages protected
Definition at line 68 of file GCNSchedStrategy.h.
Referenced by advanceStage(), llvm::GCNMaxILPSchedStrategy::GCNMaxILPSchedStrategy(), llvm::GCNMaxOccupancySchedStrategy::GCNMaxOccupancySchedStrategy(), getCurrentStage(), getNextStage(), and hasNextStage().
SGPRCriticalLimit
unsigned llvm::GCNSchedStrategy::SGPRCriticalLimit
Definition at line 93 of file GCNSchedStrategy.h.
Referenced by llvm::GCNSchedStage::checkScheduling(), initCandidate(), and initialize().
SGPRExcessLimit
unsigned llvm::GCNSchedStrategy::SGPRExcessLimit protected
Definition at line 59 of file GCNSchedStrategy.h.
Referenced by initCandidate(), and initialize().
SGPRLimitBias
unsigned llvm::GCNSchedStrategy::SGPRLimitBias = 0
Definition at line 97 of file GCNSchedStrategy.h.
Referenced by llvm::UnclusteredHighRPStage::finalizeGCNSchedStage(), llvm::UnclusteredHighRPStage::initGCNSchedStage(), and initialize().
TargetOccupancy
unsigned llvm::GCNSchedStrategy::TargetOccupancy protected
Definition at line 63 of file GCNSchedStrategy.h.
Referenced by getTargetOccupancy(), initialize(), and setTargetOccupancy().
VGPRCriticalLimit
unsigned llvm::GCNSchedStrategy::VGPRCriticalLimit
Definition at line 95 of file GCNSchedStrategy.h.
Referenced by llvm::GCNSchedStage::checkScheduling(), initCandidate(), and initialize().
VGPRExcessLimit
unsigned llvm::GCNSchedStrategy::VGPRExcessLimit protected
Definition at line 61 of file GCNSchedStrategy.h.
Referenced by initCandidate(), and initialize().
VGPRLimitBias
unsigned llvm::GCNSchedStrategy::VGPRLimitBias = 0
Definition at line 99 of file GCNSchedStrategy.h.
Referenced by llvm::UnclusteredHighRPStage::finalizeGCNSchedStage(), llvm::UnclusteredHighRPStage::initGCNSchedStage(), and initialize().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNSchedStrategy.h
lib/Target/AMDGPU/GCNSchedStrategy.cpp