LLVM: PODSmallVector< T, N > Class Template Reference
PODSmallVector< T, N > Class Template Reference
#include "llvm/Demangle/ItaniumDemangle.h"
Public Member Functions
PODSmallVector ()
PODSmallVector (const PODSmallVector &)=delete
PODSmallVector & operator= (const PODSmallVector &)=delete
PODSmallVector (PODSmallVector &&Other)
PODSmallVector & operator= (PODSmallVector &&Other)
void push_back (const T &Elem)
void pop_back ()
void shrinkToSize (size_t Index)
T * begin ()
T * end ()
bool empty () const
size_t size () const
T & back ()
T & operator[] (size_t Index)
void clear ()
~PODSmallVector ()
Detailed Description
template<class T, size_t N>
class PODSmallVector< T, N >
Definition at line 40 of file ItaniumDemangle.h.
Constructor & Destructor Documentation
PODSmallVector() [1/3]
template<class T , size_t N> PODSmallVector< T, N >::PODSmallVector () inline
Definition at line 75 of file ItaniumDemangle.h.
PODSmallVector() [2/3]
template<class T , size_t N> PODSmallVector< T, N >::PODSmallVector (const PODSmallVector< T, N > &) delete
PODSmallVector() [3/3]
template<class T , size_t N> PODSmallVector< T, N >::PODSmallVector (PODSmallVector< T, N > && Other) inline
Definition at line 80 of file ItaniumDemangle.h.
References Other.
~PODSmallVector()
template<class T , size_t N> PODSmallVector< T, N >::~PODSmallVector () inline
Definition at line 154 of file ItaniumDemangle.h.
Member Function Documentation
back()
template<class T , size_t N> T & PODSmallVector< T, N >::back () inline
Definition at line 144 of file ItaniumDemangle.h.
References DEMANGLE_ASSERT.
begin()
template<class T , size_t N> T * PODSmallVector< T, N >::begin () inline
Definition at line 139 of file ItaniumDemangle.h.
Referenced by PODSmallVector< T, N >::operator[](), and AbstractManglingParser< Derived, Alloc >::popTrailingNodeArray().
clear()
template<class T , size_t N> void PODSmallVector< T, N >::clear () inline
Definition at line 152 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::parseTemplateArgs(), AbstractManglingParser< Derived, Alloc >::parseUnnamedTypeName(), AbstractManglingParser< Derived, Alloc >::reset(), and AbstractManglingParser< Derived, Alloc >::SaveTemplateParams::SaveTemplateParams().
empty()
template<class T , size_t N> bool PODSmallVector< T, N >::empty () const inline
Definition at line 142 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::parseNestedName(), and AbstractManglingParser< Derived, Alloc >::parseSubstitution().
end()
template<class T , size_t N> T * PODSmallVector< T, N >::end () inline
Definition at line 140 of file ItaniumDemangle.h.
Referenced by AbstractManglingParser< Derived, Alloc >::popTrailingNodeArray().
operator=() [1/2]
template<class T , size_t N> PODSmallVector & PODSmallVector< T, N >::operator= (const PODSmallVector< T, N > &) delete
operator=() [2/2]
template<class T , size_t N> PODSmallVector & PODSmallVector< T, N >::operator= (PODSmallVector< T, N > && Other) inline
Definition at line 94 of file ItaniumDemangle.h.
References Other, and std::swap().
operator[]()
template<class T , size_t N> T & PODSmallVector< T, N >::operator[] (size_t Index) inline
Definition at line 148 of file ItaniumDemangle.h.
References PODSmallVector< T, N >::begin(), DEMANGLE_ASSERT, Index, and PODSmallVector< T, N >::size().
pop_back()
template<class T , size_t N> void PODSmallVector< T, N >::pop_back () inline
Definition at line 129 of file ItaniumDemangle.h.
References DEMANGLE_ASSERT.
Referenced by AbstractManglingParser< Derived, Alloc >::parseNestedName(), and AbstractManglingParser< Derived, Alloc >::parseUnnamedTypeName().
push_back()
template<class T , size_t N> void PODSmallVector< T, N >::push_back (const T & Elem) inline
Definition at line 122 of file ItaniumDemangle.h.
References PODSmallVector< T, N >::size().
Referenced by AbstractManglingParser< Derived, Alloc >::parseConversionExpr(), AbstractManglingParser< Derived, Alloc >::parseEncoding(), AbstractManglingParser< Derived, Alloc >::parseExpr(), AbstractManglingParser< Derived, Alloc >::parseFunctionType(), AbstractManglingParser< Derived, Alloc >::parseModuleNameOpt(), AbstractManglingParser< Derived, Alloc >::parseName(), AbstractManglingParser< Derived, Alloc >::parseNestedName(), AbstractManglingParser< Derived, Alloc >::parseRequiresExpr(), AbstractManglingParser< Derived, Alloc >::parseSubobjectExpr(), AbstractManglingParser< Derived, Alloc >::parseSubstitution(), AbstractManglingParser< Derived, Alloc >::parseTemplateArg(), AbstractManglingParser< Derived, Alloc >::parseTemplateArgs(), AbstractManglingParser< Derived, Alloc >::parseTemplateParam(), AbstractManglingParser< Derived, Alloc >::parseTemplateParamDecl(), AbstractManglingParser< Derived, Alloc >::parseType(), AbstractManglingParser< Derived, Alloc >::parseUnnamedTypeName(), AbstractManglingParser< Derived, Alloc >::parseUnqualifiedName(), and AbstractManglingParser< Derived, Alloc >::parseUnresolvedType().
shrinkToSize()
template<class T , size_t N> void PODSmallVector< T, N >::shrinkToSize (size_t Index) inline
Definition at line 134 of file ItaniumDemangle.h.
References DEMANGLE_ASSERT, Index, and PODSmallVector< T, N >::size().
Referenced by AbstractManglingParser< Derived, Alloc >::popTrailingNodeArray(), and AbstractManglingParser< Derived, Alloc >::resolveForwardTemplateRefs().
size()
template<class T , size_t N> size_t PODSmallVector< T, N >::size () const inline
Definition at line 143 of file ItaniumDemangle.h.
Referenced by PODSmallVector< T, N >::operator[](), AbstractManglingParser< Derived, Alloc >::parseConversionExpr(), AbstractManglingParser< Derived, Alloc >::parseEncoding(), AbstractManglingParser< Derived, Alloc >::parseExpr(), AbstractManglingParser< Derived, Alloc >::parseFunctionType(), AbstractManglingParser< Derived, Alloc >::parseRequiresExpr(), AbstractManglingParser< Derived, Alloc >::parseSubobjectExpr(), AbstractManglingParser< Derived, Alloc >::parseSubstitution(), AbstractManglingParser< Derived, Alloc >::parseTemplateArg(), AbstractManglingParser< Derived, Alloc >::parseTemplateArgs(), AbstractManglingParser< Derived, Alloc >::parseTemplateParam(), AbstractManglingParser< Derived, Alloc >::parseTemplateParamDecl(), AbstractManglingParser< Derived, Alloc >::parseUnnamedTypeName(), AbstractManglingParser< Derived, Alloc >::parseUnqualifiedName(), AbstractManglingParser< Derived, Alloc >::popTrailingNodeArray(), PODSmallVector< T, N >::push_back(), AbstractManglingParser< Derived, Alloc >::resolveForwardTemplateRefs(), and PODSmallVector< T, N >::shrinkToSize().
The documentation for this class was generated from the following file:
include/llvm/Demangle/ItaniumDemangle.h