LLVM: llvm::orc::MachOBuilder< MachOTraits >::RelocTarget Class Reference
llvm::orc::MachOBuilder< MachOTraits >::RelocTarget Class Reference
#include "llvm/ExecutionEngine/Orc/MachOBuilder.h"
Public Member Functions
RelocTarget (const Section &S)
RelocTarget (SymbolContainer &SC, size_t Idx)
bool isSymbol ()
uint32_t getSymbolNum ()
uint32_t getSectionId ()
MachOTraits::NList & nlist ()
Detailed Description
template<typename MachOTraits>
class llvm::orc::MachOBuilder< MachOTraits >::RelocTarget
Definition at line 174 of file MachOBuilder.h.
Constructor & Destructor Documentation
RelocTarget() [1/2]
template<typename MachOTraits > llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::RelocTarget (const Section & S) inline
Definition at line 176 of file MachOBuilder.h.
RelocTarget() [2/2]
template<typename MachOTraits > llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::RelocTarget (SymbolContainer & SC, size_t Idx) inline
Definition at line 177 of file MachOBuilder.h.
References Idx.
Member Function Documentation
getSectionId()
template<typename MachOTraits > uint32_t llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::getSectionId () inline
Definition at line 186 of file MachOBuilder.h.
References assert(), llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::isSymbol(), llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::S, and llvm::orc::MachOBuilder< MachOTraits >::Section::SectionNumber.
getSymbolNum()
template<typename MachOTraits > uint32_t llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::getSymbolNum () inline
Definition at line 181 of file MachOBuilder.h.
References assert(), llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::isSymbol(), and llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::SC.
isSymbol()
template<typename MachOTraits > bool llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::isSymbol () inline
Definition at line 179 of file MachOBuilder.h.
Referenced by llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::getSectionId(), llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::getSymbolNum(), and llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::nlist().
nlist()
template<typename MachOTraits > MachOTraits::NList & llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::nlist () inline
Definition at line 191 of file MachOBuilder.h.
References assert(), llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::isSymbol(), and llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::SC.
Member Data Documentation
S
template<typename MachOTraits > const Section* llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::S
Definition at line 198 of file MachOBuilder.h.
Referenced by llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::getSectionId().
SC
template<typename MachOTraits > SymbolContainer* llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::SC
Definition at line 199 of file MachOBuilder.h.
Referenced by llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::getSymbolNum(), and llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::nlist().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/MachOBuilder.h