LLVM: llvm::X86LegalizerInfo Class Reference
llvm::X86LegalizerInfo Class Reference
#include "Target/X86/GISel/X86LegalizerInfo.h"
Public Member Functions
X86LegalizerInfo (const X86Subtarget &STI, const X86TargetMachine &TM)
bool legalizeIntrinsic (LegalizerHelper &Helper, MachineInstr &MI) const override
Public Member Functions inherited from llvm::LegalizerInfo
virtual ~LegalizerInfo ()=default
const LegacyLegalizerInfo & getLegacyLegalizerInfo () const
LegacyLegalizerInfo & getLegacyLegalizerInfo ()
unsigned getOpcodeIdxForOpcode (unsigned Opcode) const
unsigned getActionDefinitionsIdx (unsigned Opcode) const
void verify (const MCInstrInfo &MII) const
Perform simple self-diagnostic and assert if there is anything obviously wrong with the actions set up.
const LegalizeRuleSet & getActionDefinitions (unsigned Opcode) const
Get the action definitions for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (unsigned Opcode)
Get the action definition builder for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (std::initializer_list< unsigned > Opcodes)
Get the action definition builder for the given set of opcodes.
void aliasActionDefinitions (unsigned OpcodeTo, unsigned OpcodeFrom)
LegalizeActionStep getAction (const LegalityQuery &Query) const
Determine what action should be taken to legalize the described instruction.
LegalizeActionStep getAction (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
Determine what action should be taken to legalize the given generic instruction.
bool isLegal (const LegalityQuery &Query) const
bool isLegalOrCustom (const LegalityQuery &Query) const
bool isLegal (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
bool isLegalOrCustom (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
virtual bool legalizeCustom (LegalizerHelper &Helper, MachineInstr &MI, LostDebugLocObserver &LocObserver) const
Called for instructions with the Custom LegalizationAction.
virtual bool legalizeIntrinsic (LegalizerHelper &Helper, MachineInstr &MI) const
virtual unsigned getExtOpcodeForWideningConstant (LLT SmallTy) const
Return the opcode (SEXT/ZEXT/ANYEXT) that should be performed while widening a constant of type SmallTy which targets can override.
Detailed Description
Definition at line 24 of file X86LegalizerInfo.h.
Constructor & Destructor Documentation
X86LegalizerInfo()
X86LegalizerInfo::X86LegalizerInfo (const X86Subtarget & STI, const X86TargetMachine & TM)
Definition at line 27 of file X86LegalizerInfo.cpp.
References llvm::X86Subtarget::canUseCMOV(), llvm::LegalizeRuleSet::clampMaxNumElements(), llvm::LegalizeRuleSet::clampMinNumElements(), llvm::LegalizeRuleSet::clampScalar(), llvm::LegacyLegalizerInfo::computeTables(), llvm::LLT::fixed_vector(), llvm::LegalizerInfo::getActionDefinitionsBuilder(), llvm::X86Subtarget::getInstrInfo(), llvm::LegalizerInfo::getLegacyLegalizerInfo(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasAVX512(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::X86Subtarget::hasSSE41(), llvm::LegalizeRuleSet::legalFor(), llvm::LegalizeRuleSet::legalForCartesianProduct(), llvm::LegalizeRuleSet::legalIf(), llvm::LegalizeRuleSet::libcall(), libcall, llvm::LegalizeRuleSet::lower(), llvm::LegalizeRuleSet::minScalar(), llvm::LegalityQuery::Opcode, llvm::LLT::pointer(), llvm::LLT::scalar(), llvm::LegalizeRuleSet::scalarize(), llvm::LegalizeRuleSet::scalarSameSizeAs(), TM, llvm::LegalityPredicates::typeInSet(), llvm::LegalityPredicates::typePairInSet(), llvm::LegalityQuery::Types, verify, and llvm::LegalizeRuleSet::widenScalarToNextPow2().
Member Function Documentation
legalizeIntrinsic()
bool X86LegalizerInfo::legalizeIntrinsic (LegalizerHelper & Helper, MachineInstr & MI) const override virtual
Returns
true if MI is either legal or has been legalized and false if not legal. Return true if MI is either legal or has been legalized and false if not legal.
Reimplemented from llvm::LegalizerInfo.
Definition at line 552 of file X86LegalizerInfo.cpp.
The documentation for this class was generated from the following files:
lib/Target/X86/GISel/X86LegalizerInfo.h
lib/Target/X86/GISel/X86LegalizerInfo.cpp