LLVM: llvm::GISelWorkList< N > Class Template Reference
llvm::GISelWorkList< N > Class Template Reference
#include "llvm/CodeGen/GlobalISel/GISelWorkList.h"
Public Member Functions
GISelWorkList ()
bool empty () const
unsigned size () const
void deferred_insert (MachineInstr *I)
void finalize ()
void insert (MachineInstr *I)
Add the specified instruction to the worklist if it isn't already in it.
void remove (const MachineInstr *I)
Remove I from the worklist if it exists.
void clear ()
MachineInstr * pop_back_val ()
Detailed Description
template<unsigned N>
class llvm::GISelWorkList< N >
Definition at line 27 of file GISelWorkList.h.
Constructor & Destructor Documentation
GISelWorkList()
template<unsigned N> llvm::GISelWorkList< N >::GISelWorkList () inline
Definition at line 36 of file GISelWorkList.h.
Member Function Documentation
clear()
template<unsigned N> void llvm::GISelWorkList< N >::clear () inline
Definition at line 97 of file GISelWorkList.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), and llvm::SmallVectorImpl< T >::clear().
Referenced by llvm::Combiner::combineMachineInstrs(), and llvm::GISelCSEInfo::releaseMemory().
deferred_insert()
template<unsigned N> void llvm::GISelWorkList< N >::deferred_insert (MachineInstr * I) inline
Definition at line 50 of file GISelWorkList.h.
References I, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::Combiner::combineMachineInstrs(), and llvm::Legalizer::legalizeMachineFunction().
empty()
template<unsigned N> bool llvm::GISelWorkList< N >::empty () const inline
Definition at line 38 of file GISelWorkList.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty().
Referenced by llvm::MipsRegisterBankInfo::applyMappingImpl(), llvm::Combiner::combineMachineInstrs(), llvm::eraseInstrs(), llvm::GISelCSEInfo::handleRecordedInsts(), and llvm::Legalizer::legalizeMachineFunction().
finalize()
template<unsigned N> void llvm::GISelWorkList< N >::finalize () inline
Definition at line 61 of file GISelWorkList.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm_unreachable, N, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::reserve(), llvm::SmallVectorBase< Size_T >::size(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Referenced by llvm::Combiner::combineMachineInstrs(), and llvm::Legalizer::legalizeMachineFunction().
insert()
template<unsigned N> void llvm::GISelWorkList< N >::insert (MachineInstr * I) inline
Add the specified instruction to the worklist if it isn't already in it.
Definition at line 74 of file GISelWorkList.h.
References assert(), I, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase< Size_T >::size(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Referenced by llvm::Combiner::WorkListMaintainer::changedInstr(), llvm::Combiner::WorkListMaintainer::changingInstr(), llvm::Combiner::WorkListMaintainer::createdInstr(), llvm::Legalizer::legalizeMachineFunction(), llvm::GISelCSEInfo::recordNewInstruction(), and llvm::saveUsesAndErase().
pop_back_val()
template<unsigned N> MachineInstr * llvm::GISelWorkList< N >::pop_back_val () inline
Definition at line 102 of file GISelWorkList.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), I, and llvm::SmallVectorImpl< T >::pop_back_val().
Referenced by llvm::MipsRegisterBankInfo::applyMappingImpl(), llvm::Combiner::combineMachineInstrs(), llvm::eraseInstrs(), llvm::GISelCSEInfo::handleRecordedInsts(), and llvm::Legalizer::legalizeMachineFunction().
remove()
template<unsigned N> void llvm::GISelWorkList< N >::remove (const MachineInstr * I) inline
Remove I from the worklist if it exists.
Definition at line 83 of file GISelWorkList.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
Referenced by llvm::Combiner::WorkListMaintainer::erasingInstr(), llvm::GISelCSEInfo::handleRemoveInst(), and llvm::saveUsesAndErase().
size()
template<unsigned N> unsigned llvm::GISelWorkList< N >::size () const inline
Definition at line 40 of file GISelWorkList.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size().
Referenced by llvm::Legalizer::legalizeMachineFunction().
The documentation for this class was generated from the following file:
include/llvm/CodeGen/GlobalISel/GISelWorkList.h