LLVM: llvm::objcopy::elf::Object Class Reference
llvm::objcopy::elf::Object Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Types
template<class T >
using ConstRange = iterator_range< pointee_iterator< typename std::vector< std::unique_ptr< T > >::const_iterator > >
Public Member Functions
SectionTableRef sections () const
iterator_range< filter_iterator< pointee_iterator< std::vector< SecPtr >::const_iterator >, decltype(&sectionIsAlloc)> > allocSections () const
const auto & getUpdatedSections () const
Error updateSection (StringRef Name, ArrayRef< uint8_t > Data)
SectionBase * findSection (StringRef Name)
SectionTableRef removedSections ()
ConstRange< Segment > segments () const
Error removeSections (bool AllowBrokenLinks, std::function< bool(const SectionBase &)> ToRemove)
Error replaceSections (const DenseMap< SectionBase *, SectionBase * > &FromTo)
Error removeSymbols (function_ref< bool(const Symbol &)> ToRemove)
template<class T , class... Ts>
T & addSection (Ts &&...Args)
Error addNewSymbolTable ()
Segment & addSegment (ArrayRef< uint8_t > Data)
bool isRelocatable () const
Public Attributes
Segment ElfHdrSegment
Segment ProgramHdrSegment
bool Is64Bits
uint8_t OSABI
uint8_t ABIVersion
uint64_t Entry
uint64_t SHOff
uint32_t Type
uint32_t Machine
uint32_t Version
uint32_t Flags
bool HadShdrs = true
bool MustBeRelocatable = false
StringTableSection * SectionNames = nullptr
SymbolTableSection * SymbolTable = nullptr
SectionIndexSection * SectionIndexTable = nullptr
bool IsMips64EL = false
Detailed Description
Definition at line 1029 of file ELFObject.h.
Member Typedef Documentation
ConstRange
template<class T > using llvm::objcopy::elf::Object::ConstRange = iterator_range<pointee_iterator< typename std::vector<std::unique_ptr<T> >::const_iterator> >
Definition at line 1045 of file ELFObject.h.
Member Function Documentation
addNewSymbolTable()
Error Object::addNewSymbolTable ()
Definition at line 2236 of file ELFObject.cpp.
References llvm::objcopy::elf::SymbolTableSection::addSymbol(), assert(), llvm::objcopy::elf::SectionBase::Index, llvm::objcopy::elf::SymbolTableSection::initialize(), llvm::objcopy::elf::SectionBase::Link, llvm::objcopy::elf::SectionBase::Name, SectionNames, sections(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_STRTAB, llvm::Error::success(), and SymbolTable.
Referenced by handleArgs().
addSection()
template<class T , class... Ts> T & llvm::objcopy::elf::Object::addSection (Ts &&... Args) inline
Definition at line 1099 of file ELFObject.h.
References MustBeRelocatable, and Ptr.
Referenced by handleArgs(), and replaceAndRemoveSections().
addSegment()
Segment & llvm::objcopy::elf::Object::addSegment (ArrayRef< uint8_t > Data) inline
Definition at line 1108 of file ELFObject.h.
References llvm::Data.
allocSections()
iterator_range< filter_iterator< pointee_iterator< std::vector< SecPtr >::const_iterator >, decltype(&sectionIsAlloc)> > llvm::objcopy::elf::Object::allocSections () const inline
Definition at line 1079 of file ELFObject.h.
References llvm::make_filter_range(), and llvm::make_pointee_range().
Referenced by llvm::objcopy::elf::BinaryWriter::finalize(), and llvm::objcopy::elf::BinaryWriter::write().
findSection()
SectionBase * llvm::objcopy::elf::Object::findSection (StringRef Name) inline
Definition at line 1086 of file ELFObject.h.
References llvm::find_if(), and Name.
Referenced by addSymbol().
getUpdatedSections()
const auto & llvm::objcopy::elf::Object::getUpdatedSections () const inline
Definition at line 1083 of file ELFObject.h.
isRelocatable()
bool llvm::objcopy::elf::Object::isRelocatable () const inline
Definition at line 1112 of file ELFObject.h.
References llvm::ELF::ET_DYN, llvm::ELF::ET_EXEC, and MustBeRelocatable.
Referenced by isRequiredByABISymbol(), removeUnneededSections(), and updateAndRemoveSymbols().
removedSections()
SectionTableRef llvm::objcopy::elf::Object::removedSections () inline
Definition at line 1091 of file ELFObject.h.
removeSections()
Error Object::removeSections (bool AllowBrokenLinks, std::function< bool(const SectionBase &)> ToRemove)
Definition at line 2152 of file ELFObject.cpp.
References E, llvm::make_range(), llvm::objcopy::elf::Segment::removeSection(), llvm::objcopy::elf::SectionIndexSection::reserve(), SectionIndexTable, SectionNames, llvm::Error::success(), SymbolTable, and ToRemove.
Referenced by handleArgs(), removeUnneededSections(), replaceAndRemoveSections(), and replaceSections().
removeSymbols()
Error Object::removeSymbols (function_ref< bool(const Symbol &)> ToRemove)
Definition at line 2228 of file ELFObject.cpp.
References E, llvm::Error::success(), SymbolTable, and ToRemove.
Referenced by updateAndRemoveSymbols().
replaceSections()
Error Object::replaceSections (const DenseMap< SectionBase *, SectionBase * > & FromTo)
Definition at line 2204 of file ELFObject.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), E, I, llvm::is_sorted(), removeSections(), llvm::sort(), and llvm::Error::success().
Referenced by replaceDebugSections().
sections()
SectionTableRef llvm::objcopy::elf::Object::sections () const inline
Definition at line 1075 of file ELFObject.h.
Referenced by addNewSymbolTable(), dumpSectionToFile(), llvm::objcopy::elf::IHexWriter::finalize(), handleArgs(), layoutSectionsForOnlyKeepDebug(), replaceDebugSections(), and updateAndRemoveSymbols().
segments()
ConstRange< Segment > llvm::objcopy::elf::Object::segments () const inline
Definition at line 1093 of file ELFObject.h.
References llvm::make_pointee_range().
updateSection()
Error Object::updateSection (StringRef Name, ArrayRef< uint8_t > Data)
Definition at line 2121 of file ELFObject.cpp.
References llvm::createStringError(), llvm::Data, llvm::find_if(), llvm::invalid_argument, Name, and llvm::Error::success().
Referenced by handleArgs().
Member Data Documentation
ABIVersion
uint8_t llvm::objcopy::elf::Object::ABIVersion
Definition at line 1059 of file ELFObject.h.
ElfHdrSegment
Segment llvm::objcopy::elf::Object::ElfHdrSegment
Definition at line 1054 of file ELFObject.h.
Entry
uint64_t llvm::objcopy::elf::Object::Entry
Definition at line 1060 of file ELFObject.h.
Referenced by llvm::objcopy::elf::IHexWriter::finalize(), and handleArgs().
Flags
uint32_t llvm::objcopy::elf::Object::Flags
Definition at line 1065 of file ELFObject.h.
HadShdrs
bool llvm::objcopy::elf::Object::HadShdrs = true
Definition at line 1067 of file ELFObject.h.
Is64Bits
bool llvm::objcopy::elf::Object::Is64Bits
Definition at line 1057 of file ELFObject.h.
Referenced by replaceAndRemoveSections().
IsMips64EL
bool llvm::objcopy::elf::Object::IsMips64EL = false
Definition at line 1073 of file ELFObject.h.
Referenced by llvm::objcopy::elf::ELFBuilder< ELFT >::ELFBuilder(), initRelocations(), and llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit().
Machine
uint32_t llvm::objcopy::elf::Object::Machine
Definition at line 1063 of file ELFObject.h.
Referenced by handleArgs(), and isRequiredByABISymbol().
MustBeRelocatable
bool llvm::objcopy::elf::Object::MustBeRelocatable = false
Definition at line 1068 of file ELFObject.h.
Referenced by addSection(), and isRelocatable().
OSABI
uint8_t llvm::objcopy::elf::Object::OSABI
Definition at line 1058 of file ELFObject.h.
Referenced by handleArgs().
ProgramHdrSegment
Segment llvm::objcopy::elf::Object::ProgramHdrSegment
Definition at line 1055 of file ELFObject.h.
SectionIndexTable
SectionIndexSection* llvm::objcopy::elf::Object::SectionIndexTable = nullptr
Definition at line 1071 of file ELFObject.h.
Referenced by removeSections().
SectionNames
StringTableSection* llvm::objcopy::elf::Object::SectionNames = nullptr
Definition at line 1069 of file ELFObject.h.
Referenced by addNewSymbolTable(), onlyKeepDWOPred(), removeSections(), removeUnneededSections(), and replaceAndRemoveSections().
SHOff
uint64_t llvm::objcopy::elf::Object::SHOff
Definition at line 1061 of file ELFObject.h.
SymbolTable
SymbolTableSection* llvm::objcopy::elf::Object::SymbolTable = nullptr
Definition at line 1070 of file ELFObject.h.
Referenced by addNewSymbolTable(), addSymbol(), handleArgs(), initRelocations(), removeSections(), removeSymbols(), removeUnneededSections(), replaceAndRemoveSections(), and updateAndRemoveSymbols().
Type
uint32_t llvm::objcopy::elf::Object::Type
Definition at line 1062 of file ELFObject.h.
Version
uint32_t llvm::objcopy::elf::Object::Version
Definition at line 1064 of file ELFObject.h.
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp