LLVM: llvm::logicalview::LVBinaryReader Class Reference
llvm::logicalview::LVBinaryReader Class Reference
#include "llvm/DebugInfo/LogicalView/Readers/LVBinaryReader.h"
Public Member Functions
LVBinaryReader ()=delete
LVBinaryReader (StringRef Filename, StringRef FileFormatName, ScopedPrinter &W, LVBinaryType BinaryType)
LVBinaryReader (const LVBinaryReader &)=delete
LVBinaryReader & operator= (const LVBinaryReader &)=delete
virtual ~LVBinaryReader ()=default
void addInlineeLines (LVScope *Scope, LVLines &Lines)
LVAddress linearAddress (uint16_t Segment, uint32_t Offset, LVAddress Addendum=0)
void addToSymbolTable (StringRef Name, LVScope *Function, LVSectionIndex SectionIndex=0)
void addToSymbolTable (StringRef Name, LVAddress Address, LVSectionIndex SectionIndex, bool IsComdat)
LVSectionIndex updateSymbolTable (LVScope *Function)
const LVSymbolTableEntry & getSymbolTableEntry (StringRef Name)
LVAddress getSymbolTableAddress (StringRef Name)
LVSectionIndex getSymbolTableIndex (StringRef Name)
bool getSymbolTableIsComdat (StringRef Name)
LVSectionIndex getSectionIndex (LVScope *Scope) override
void print (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::logicalview::LVReader
LVReader ()=delete
LVReader (StringRef InputFilename, StringRef FileFormatName, ScopedPrinter &W, LVBinaryType BinaryType=LVBinaryType::NONE)
LVReader (const LVReader &)=delete
LVReader & operator= (const LVReader &)=delete
virtual ~LVReader ()=default
LVOperation * createOperation (LVSmall OpCode, ArrayRef< LVUnsigned > Operands)
StringRef getFilename (LVObject *Object, size_t Index) const
StringRef getFilename () const
void setFilename (std::string Name)
StringRef getFileFormatName () const
raw_ostream & outputStream ()
bool isBinaryTypeNone () const
bool isBinaryTypeELF () const
bool isBinaryTypeCOFF () const
LVScopeCompileUnit * getCompileUnit () const
void setCompileUnit (LVScope *Scope)
void setCompileUnitCPUType (codeview::CPUType Type)
codeview::CPUType getCompileUnitCPUType ()
LVScopeRoot * getScopesRoot () const
Error doPrint ()
Error doLoad ()
virtual std::string getRegisterName (LVSmall Opcode, ArrayRef< uint64_t > Operands)
LVSectionIndex getDotTextSectionIndex () const
virtual LVSectionIndex getSectionIndex (LVScope *Scope)
virtual bool isSystemEntry (LVElement *Element, StringRef Name={}) const
LVSplitContext & getSplitContext ()
void notifyAddedElement (LVLine *Line)
void notifyAddedElement (LVScope *Scope)
void notifyAddedElement (LVSymbol *Symbol)
void notifyAddedElement (LVType *Type)
const LVLines & getLines () const
const LVScopes & getScopes () const
const LVSymbols & getSymbols () const
const LVTypes & getTypes () const
bool doPrintLine (const LVLine *Line) const
bool doPrintLocation (const LVLocation *Location) const
bool doPrintScope (const LVScope *Scope) const
bool doPrintSymbol (const LVSymbol *Symbol) const
bool doPrintType (const LVType *Type) const
void print (raw_ostream &OS) const
virtual void printRecords (raw_ostream &OS) const
void dump () const
Protected Member Functions
Error loadGenericTargetInfo (StringRef TheTriple, StringRef TheFeatures)
virtual void mapRangeAddress (const object::ObjectFile &Obj)
virtual void mapRangeAddress (const object::ObjectFile &Obj, const object::SectionRef &Section, bool IsComdat)
void mapVirtualAddress (const object::ObjectFile &Obj)
void mapVirtualAddress (const object::COFFObjectFile &COFFObj)
Expected< std::pair< LVSectionIndex, object::SectionRef > > getSection (LVScope *Scope, LVAddress Address, LVSectionIndex SectionIndex)
void addSectionRange (LVSectionIndex SectionIndex, LVScope *Scope)
void addSectionRange (LVSectionIndex SectionIndex, LVScope *Scope, LVAddress LowerAddress, LVAddress UpperAddress)
LVRange * getSectionRanges (LVSectionIndex SectionIndex)
void includeInlineeLines (LVSectionIndex SectionIndex, LVScope *Function)
Error createInstructions ()
Error createInstructions (LVScope *Function, LVSectionIndex SectionIndex)
Error createInstructions (LVScope *Function, LVSectionIndex SectionIndex, const LVNameInfo &NameInfo)
void processLines (LVLines *DebugLines, LVSectionIndex SectionIndex)
void processLines (LVLines *DebugLines, LVSectionIndex SectionIndex, LVScope *Function)
Protected Member Functions inherited from llvm::logicalview::LVReader
void addCompileUnitOffset (LVOffset Offset, LVScopeCompileUnit *CompileUnit)
virtual Error createScopes ()
std::string createAlternativePath (StringRef From)
virtual Error printScopes ()
virtual Error printMatchedElements (bool UseMatchedElements)
virtual void sortScopes ()
Protected Attributes
LVLines CULines
std::unique_ptr< const MCRegisterInfo > MRI
std::unique_ptr< const MCAsmInfo > MAI
std::unique_ptr< const MCSubtargetInfo > STI
std::unique_ptr< const MCInstrInfo > MII
std::unique_ptr< const MCDisassembler > MD
std::unique_ptr< MCContext > MC
std::unique_ptr< MCInstPrinter > MIP
Protected Attributes inherited from llvm::logicalview::LVReader
LVScopeRoot * Root = nullptr
std::string InputFilename
std::string FileFormatName
ScopedPrinter & W
raw_ostream & OS
LVScopeCompileUnit * CompileUnit = nullptr
LVSectionIndex DotTextSectionIndex = UndefinedSectionIndex
Additional Inherited Members
Static Public Member Functions inherited from llvm::logicalview::LVReader
static LVReader & getInstance ()
static void setInstance (LVReader *Reader)
Detailed Description
Definition at line 69 of file LVBinaryReader.h.
Constructor & Destructor Documentation
LVBinaryReader() [1/3]
llvm::logicalview::LVBinaryReader::LVBinaryReader () delete
LVBinaryReader() [2/3]
llvm::logicalview::LVBinaryReader::LVBinaryReader (StringRef Filename, StringRef FileFormatName, ScopedPrinter & W, LVBinaryType BinaryType) inline
Definition at line 158 of file LVBinaryReader.h.
LVBinaryReader() [3/3]
llvm::logicalview::LVBinaryReader::LVBinaryReader (const LVBinaryReader &) delete
~LVBinaryReader()
virtual llvm::logicalview::LVBinaryReader::~LVBinaryReader () virtual default
Member Function Documentation
addInlineeLines()
void llvm::logicalview::LVBinaryReader::addInlineeLines (LVScope * Scope, LVLines & Lines) inline
Definition at line 165 of file LVBinaryReader.h.
References llvm::codeview::Lines.
Referenced by llvm::logicalview::LVLogicalVisitor::inlineSiteAnnotation().
addSectionRange() [1/2]
void LVBinaryReader::addSectionRange (LVSectionIndex SectionIndex, LVScope * Scope) protected
Definition at line 341 of file LVBinaryReader.cpp.
References llvm::logicalview::LVRange::addEntry(), and getSectionRanges().
Referenced by llvm::logicalview::LVELFReader::createScopes().
addSectionRange() [2/2]
void LVBinaryReader::addSectionRange (LVSectionIndex SectionIndex, LVScope * Scope, LVAddress LowerAddress, LVAddress UpperAddress) protected
Definition at line 347 of file LVBinaryReader.cpp.
References llvm::logicalview::LVRange::addEntry(), and getSectionRanges().
addToSymbolTable() [1/2]
void LVBinaryReader::addToSymbolTable (StringRef Name, LVAddress Address, LVSectionIndex SectionIndex, bool IsComdat)
Definition at line 125 of file LVBinaryReader.cpp.
References llvm::logicalview::LVSymbolTable::add(), llvm::Address, and llvm::logicalview::Name.
addToSymbolTable() [2/2]
void LVBinaryReader::addToSymbolTable (StringRef Name, LVScope * Function, LVSectionIndex SectionIndex = 0)
Definition at line 121 of file LVBinaryReader.cpp.
References llvm::logicalview::LVSymbolTable::add(), and llvm::logicalview::Name.
Referenced by includeInlineeLines(), and llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
createInstructions() [1/3]
Error LVBinaryReader::createInstructions () protected
Definition at line 512 of file LVBinaryReader.cpp.
References llvm::Address, createInstructions(), llvm::dbgs(), llvm::format_decimal(), getSymbolTableIndex(), llvm::logicalview::hexValue(), LLVM_DEBUG, llvm::logicalview::Name, llvm::logicalview::options(), Size, and llvm::Error::success().
Referenced by createInstructions(), and llvm::logicalview::LVELFReader::createScopes().
createInstructions() [2/3]
Error LVBinaryReader::createInstructions (LVScope * Function, LVSectionIndex SectionIndex) protected
Definition at line 500 of file LVBinaryReader.cpp.
References createInstructions(), llvm::logicalview::Name, llvm::logicalview::options(), llvm::Error::success(), and UINT64_MAX.
createInstructions() [3/3]
Error LVBinaryReader::createInstructions (LVScope * Function, LVSectionIndex SectionIndex, const LVNameInfo & NameInfo) protected
Definition at line 365 of file LVBinaryReader.cpp.
References llvm::Address, assert(), llvm::consumeError(), llvm::ArrayRef< T >::data(), llvm::dbgs(), End, llvm::MCDisassembler::Fail, llvm::fmt_align(), llvm::format(), llvm::format_bytes(), llvm::format_decimal(), llvm::formatv(), getSection(), llvm::logicalview::hexValue(), llvm::logicalview::Instructions, llvm::Left, LLVM_DEBUG, MD, MIP, llvm::logicalview::Offset, llvm::outs(), Size, llvm::MCDisassembler::SoftFail, STI, llvm::raw_string_ostream::str(), llvm::MCDisassembler::Success, llvm::Error::success(), llvm::Expected< T >::takeError(), and llvm::StringRef::trim().
dump()
void llvm::logicalview::LVBinaryReader::dump () const inline
Definition at line 194 of file LVBinaryReader.h.
References llvm::dbgs(), and print().
getSection()
Expected< std::pair< uint64_t, object::SectionRef > > LVBinaryReader::getSection (LVScope * Scope, LVAddress Address, LVSectionIndex SectionIndex) protected
Definition at line 310 of file LVBinaryReader.cpp.
References llvm::Address, llvm::createStringError(), and llvm::invalid_argument.
Referenced by createInstructions().
getSectionIndex()
LVSectionIndex llvm::logicalview::LVBinaryReader::getSectionIndex (LVScope * Scope) inline override virtual
Reimplemented from llvm::logicalview::LVReader.
Definition at line 186 of file LVBinaryReader.h.
References llvm::logicalview::LVReader::DotTextSectionIndex, and getSymbolTableIndex().
Referenced by llvm::logicalview::LVELFReader::createScopes().
getSectionRanges()
LVRange * LVBinaryReader::getSectionRanges (LVSectionIndex SectionIndex) protected
Definition at line 354 of file LVBinaryReader.cpp.
References assert(), and llvm::logicalview::Range.
Referenced by addSectionRange(), llvm::logicalview::LVELFReader::createScopes(), and processLines().
getSymbolTableAddress()
LVAddress LVBinaryReader::getSymbolTableAddress (StringRef Name)
Definition at line 137 of file LVBinaryReader.cpp.
References llvm::logicalview::LVSymbolTable::getAddress(), and llvm::logicalview::Name.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
getSymbolTableEntry()
const LVSymbolTableEntry & LVBinaryReader::getSymbolTableEntry (StringRef Name)
Definition at line 134 of file LVBinaryReader.cpp.
References llvm::logicalview::LVSymbolTable::getEntry(), and llvm::logicalview::Name.
getSymbolTableIndex()
LVSectionIndex LVBinaryReader::getSymbolTableIndex (StringRef Name)
Definition at line 140 of file LVBinaryReader.cpp.
References llvm::logicalview::LVSymbolTable::getIndex(), and llvm::logicalview::Name.
Referenced by createInstructions(), and getSectionIndex().
getSymbolTableIsComdat()
bool LVBinaryReader::getSymbolTableIsComdat (StringRef Name)
Definition at line 143 of file LVBinaryReader.cpp.
References llvm::logicalview::LVSymbolTable::getIsComdat(), and llvm::logicalview::Name.
includeInlineeLines()
void LVBinaryReader::includeInlineeLines (LVSectionIndex SectionIndex, LVScope * Function) protected
Definition at line 864 of file LVBinaryReader.cpp.
References addToSymbolTable(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), CULines, llvm::dbgs(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::format(), llvm::Value::getName(), llvm::logicalview::LVScope::getScopes(), llvm::logicalview::hexValue(), llvm::codeview::InlineeLines, llvm::SmallVectorImpl< T >::insert(), LLVM_DEBUG, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::logicalview::Scopes, and llvm::SmallVectorBase< Size_T >::size().
linearAddress()
LVAddress llvm::logicalview::LVBinaryReader::linearAddress (uint16_t Segment, uint32_t Offset, LVAddress Addendum = 0) inline
Definition at line 170 of file LVBinaryReader.h.
References llvm::logicalview::Offset.
Referenced by llvm::logicalview::LVSymbolVisitor::visitKnownRecord().
loadGenericTargetInfo()
Error LVBinaryReader::loadGenericTargetInfo (StringRef TheTriple, StringRef TheFeatures) protected
Definition at line 248 of file LVBinaryReader.cpp.
References llvm::Target::createMCAsmInfo(), llvm::Target::createMCDisassembler(), llvm::Target::createMCInstPrinter(), llvm::Target::createMCInstrInfo(), llvm::Target::createMCRegInfo(), llvm::Target::createMCSubtargetInfo(), llvm::createStringError(), llvm::MCAsmInfo::getAssemblerDialect(), llvm::invalid_argument, llvm::TargetRegistry::lookupTarget(), MAI, MC, MD, MII, MIP, MRI, llvm::MCInstPrinter::setPrintImmHex(), STI, and llvm::Error::success().
mapRangeAddress() [1/2]
virtual void llvm::logicalview::LVBinaryReader::mapRangeAddress (const object::ObjectFile & Obj) inline protected virtual
Definition at line 128 of file LVBinaryReader.h.
Referenced by mapVirtualAddress().
mapRangeAddress() [2/2]
virtual void llvm::logicalview::LVBinaryReader::mapRangeAddress (const object::ObjectFile & Obj, const object::SectionRef & Section, bool IsComdat) inline protected virtual
Definition at line 129 of file LVBinaryReader.h.
mapVirtualAddress() [1/2]
void LVBinaryReader::mapVirtualAddress (const object::COFFObjectFile & COFFObj) protected
Definition at line 193 of file LVBinaryReader.cpp.
References llvm::object::coff_section::Characteristics, llvm::consumeError(), llvm::dbgs(), llvm::format_decimal(), llvm::ErrorOr< T >::get(), llvm::object::COFFObjectFile::getCOFFSection(), llvm::object::COFFObjectFile::getImageBase(), llvm::logicalview::hexValue(), llvm::COFF::IMAGE_SCN_CNT_CODE, llvm::COFF::IMAGE_SCN_LNK_COMDAT, LLVM_DEBUG, mapRangeAddress(), llvm::object::coff_section::PointerToRawData, llvm::object::ObjectFile::sections(), llvm::object::coff_section::SizeOfRawData, llvm::Expected< T >::takeError(), and llvm::object::coff_section::VirtualAddress.
mapVirtualAddress() [2/2]
void LVBinaryReader::mapVirtualAddress (const object::ObjectFile & Obj) protected
Definition at line 147 of file LVBinaryReader.cpp.
References llvm::consumeError(), llvm::dbgs(), llvm::logicalview::LVReader::DotTextSectionIndex, llvm::format_decimal(), llvm::logicalview::hexValue(), LLVM_DEBUG, mapRangeAddress(), llvm::object::ObjectFile::sections(), and llvm::Expected< T >::takeError().
Referenced by llvm::logicalview::LVELFReader::createScopes().
operator=()
LVBinaryReader & llvm::logicalview::LVBinaryReader::operator= (const LVBinaryReader &) delete
print()
void LVBinaryReader::print (raw_ostream & OS) const
Definition at line 936 of file LVBinaryReader.cpp.
References llvm::dbgs(), LLVM_DEBUG, and llvm::logicalview::LVReader::OS.
Referenced by dump().
processLines() [1/2]
void LVBinaryReader::processLines (LVLines * DebugLines, LVSectionIndex SectionIndex) protected
Definition at line 760 of file LVBinaryReader.cpp.
References llvm::Address, assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::dbgs(), llvm::SmallVectorBase< Size_T >::empty(), End, llvm::format_decimal(), llvm::logicalview::hexValue(), LLVM_DEBUG, processLines(), llvm::SmallVectorBase< Size_T >::size(), and Size.
Referenced by llvm::logicalview::LVELFReader::createScopes(), and processLines().
processLines() [2/2]
void LVBinaryReader::processLines (LVLines * DebugLines, LVSectionIndex SectionIndex, LVScope * Function) protected
Definition at line 555 of file LVBinaryReader.cpp.
References llvm::SmallVectorImpl< T >::append(), assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::logicalview::LVReader::CompileUnit, llvm::dbgs(), llvm::SmallVectorBase< Size_T >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::logicalview::LVRange::endSearch(), llvm::format(), llvm::format_decimal(), llvm::codeview::Function, llvm::logicalview::LVRange::getEntry(), getSectionRanges(), llvm::logicalview::hexValue(), llvm::SmallVectorImpl< T >::insert(), llvm::codeview::Lines, LLVM_DEBUG, llvm::logicalview::options(), llvm::logicalview::patterns(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::logicalview::LVPatterns::resolvePatternMatch(), llvm::logicalview::Scopes, llvm::SmallVectorBase< Size_T >::size(), and llvm::logicalview::LVRange::startSearch().
updateSymbolTable()
LVSectionIndex LVBinaryReader::updateSymbolTable (LVScope * Function)
Definition at line 130 of file LVBinaryReader.cpp.
References llvm::logicalview::LVSymbolTable::update().
Member Data Documentation
CULines
LVLines llvm::logicalview::LVBinaryReader::CULines protected
Definition at line 115 of file LVBinaryReader.h.
Referenced by llvm::logicalview::LVELFReader::createScopes(), and includeInlineeLines().
MAI
std::unique_ptr<const MCAsmInfo> llvm::logicalview::LVBinaryReader::MAI protected
Definition at line 118 of file LVBinaryReader.h.
Referenced by loadGenericTargetInfo().
MC
std::unique_ptr<MCContext> llvm::logicalview::LVBinaryReader::MC protected
Definition at line 122 of file LVBinaryReader.h.
Referenced by loadGenericTargetInfo().
MD
std::unique_ptr<const MCDisassembler> llvm::logicalview::LVBinaryReader::MD protected
Definition at line 121 of file LVBinaryReader.h.
Referenced by createInstructions(), and loadGenericTargetInfo().
MII
std::unique_ptr<const MCInstrInfo> llvm::logicalview::LVBinaryReader::MII protected
Definition at line 120 of file LVBinaryReader.h.
Referenced by loadGenericTargetInfo().
MIP
std::unique_ptr<MCInstPrinter> llvm::logicalview::LVBinaryReader::MIP protected
Definition at line 123 of file LVBinaryReader.h.
Referenced by createInstructions(), and loadGenericTargetInfo().
MRI
std::unique_ptr<const MCRegisterInfo> llvm::logicalview::LVBinaryReader::MRI protected
Definition at line 117 of file LVBinaryReader.h.
Referenced by llvm::logicalview::LVELFReader::getRegisterName(), and loadGenericTargetInfo().
STI
std::unique_ptr<const MCSubtargetInfo> llvm::logicalview::LVBinaryReader::STI protected
Definition at line 119 of file LVBinaryReader.h.
Referenced by createInstructions(), and loadGenericTargetInfo().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/LogicalView/Readers/LVBinaryReader.h
lib/DebugInfo/LogicalView/Readers/LVBinaryReader.cpp