LLVM: llvm::DecoderUInt128 Class Reference
llvm::DecoderUInt128 Class Reference
#include "Target/AMDGPU/Disassembler/AMDGPUDisassembler.h"
Public Member Functions
DecoderUInt128 ()=default
DecoderUInt128 (uint64_t Lo, uint64_t Hi=0)
operator bool () const
void insertBits (uint64_t SubBits, unsigned BitPosition, unsigned NumBits)
uint64_t extractBitsAsZExtValue (unsigned NumBits, unsigned BitPosition) const
DecoderUInt128 operator& (const DecoderUInt128 &RHS) const
DecoderUInt128 operator& (const uint64_t &RHS) const
DecoderUInt128 operator~ () const
bool operator== (const DecoderUInt128 &RHS)
bool operator!= (const DecoderUInt128 &RHS)
bool operator!= (const int &RHS)
Friends
raw_ostream & operator<< (raw_ostream &OS, const DecoderUInt128 &RHS)
Detailed Description
Definition at line 36 of file AMDGPUDisassembler.h.
Constructor & Destructor Documentation
DecoderUInt128() [1/2]
llvm::DecoderUInt128::DecoderUInt128 () default
Referenced by operator!=(), operator&(), and operator~().
DecoderUInt128() [2/2]
llvm::DecoderUInt128::DecoderUInt128 (uint64_t Lo, uint64_t Hi = 0) inline
Definition at line 43 of file AMDGPUDisassembler.h.
References Hi, and Lo.
Member Function Documentation
extractBitsAsZExtValue()
uint64_t llvm::DecoderUInt128::extractBitsAsZExtValue (unsigned NumBits, unsigned BitPosition) const inline
Definition at line 56 of file AMDGPUDisassembler.h.
References assert(), Hi, and Lo.
insertBits()
void llvm::DecoderUInt128::insertBits (uint64_t SubBits, unsigned BitPosition, unsigned NumBits) inline
Definition at line 45 of file AMDGPUDisassembler.h.
References assert(), Hi, and Lo.
operator bool()
llvm::DecoderUInt128::operator bool () const inline
Definition at line 44 of file AMDGPUDisassembler.h.
References Hi, and Lo.
operator!=() [1/2]
bool llvm::DecoderUInt128::operator!= (const DecoderUInt128 & RHS) inline
Definition at line 77 of file AMDGPUDisassembler.h.
References Hi, Lo, and RHS.
operator!=() [2/2]
bool llvm::DecoderUInt128::operator!= (const int & RHS) inline
Definition at line 80 of file AMDGPUDisassembler.h.
References DecoderUInt128(), and RHS.
operator&() [1/2]
DecoderUInt128 llvm::DecoderUInt128::operator& (const DecoderUInt128 & RHS) const inline
Definition at line 67 of file AMDGPUDisassembler.h.
References DecoderUInt128(), Hi, Lo, and RHS.
operator&() [2/2]
DecoderUInt128 llvm::DecoderUInt128::operator& (const uint64_t & RHS) const inline
Definition at line 70 of file AMDGPUDisassembler.h.
References DecoderUInt128(), and RHS.
operator==()
bool llvm::DecoderUInt128::operator== (const DecoderUInt128 & RHS) inline
Definition at line 74 of file AMDGPUDisassembler.h.
References Hi, Lo, and RHS.
operator~()
DecoderUInt128 llvm::DecoderUInt128::operator~ () const inline
Definition at line 73 of file AMDGPUDisassembler.h.
References DecoderUInt128(), Hi, and Lo.
Friends And Related Function Documentation
operator<<
raw_ostream & operator<< (raw_ostream & OS, const DecoderUInt128 & RHS) friend
Definition at line 83 of file AMDGPUDisassembler.h.
The documentation for this class was generated from the following file:
lib/Target/AMDGPU/Disassembler/AMDGPUDisassembler.h