LLVM: llvm::SmallVectorTemplateBase< T, true > Class Template Reference
llvm::SmallVectorTemplateBase< T, true > Class Template Reference
SmallVectorTemplateBase<TriviallyCopyable = true> - This is where we put method implementations that are designed to work with trivially copyable T's.
#include "llvm/ADT/SmallVector.h"
Public Member Functions
void push_back (ValueParamT Elt)
void pop_back ()
Public Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
size_t size () const
size_t capacity () const
bool empty () const
Protected Types
using ValueParamT = std::conditional_t< TakesParamByValue, T, const T & >
Either const T& or T, depending on whether it's cheap enough to take parameters by value.
Protected Member Functions
SmallVectorTemplateBase (size_t Size)
void grow (size_t MinSize=0)
Double the size of the allocated memory, guaranteeing space for at least one more element or MinSize if specified.
const T * reserveForParamAndGetAddress (const T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
T * reserveForParamAndGetAddress (T &Elt, size_t N=1)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
void growAndAssign (size_t NumElts, T Elt)
template<typename... ArgTypes>
T & growAndEmplaceBack (ArgTypes &&... Args)
Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
void * getFirstEl () const
Find the address of the first element.
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSize, size_t TSize)
bool isSmall () const
Return true if this is a smallvector which has not had dynamic memory allocated for it.
void resetToSmall ()
Put this vector in a state of being small.
bool isReferenceToRange (const void *V, const void *First, const void *Last) const
Return true if V is an internal reference to the given range.
bool isReferenceToStorage (const void *V) const
Return true if V is an internal reference to this vector.
bool isRangeInStorage (const void *First, const void *Last) const
Return true if First and Last form a valid (possibly empty) range in this vector's storage.
bool isSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Return true unless Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Check whether Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToAdd (const void *Elt, size_t N=1)
Check whether Elt will be invalidated by increasing the size of the vector by N.
void assertSafeToReferenceAfterClear (const T *From, const T *To)
Check whether any part of the range will be invalidated by clearing.
template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToReferenceAfterClear (ItTy, ItTy)
void assertSafeToAddRange (const T *From, const T *To)
Check whether any part of the range will be invalidated by growing.
template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToAddRange (ItTy, ItTy)
Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void * mallocForGrow (void *FirstEl, size_t MinSize, size_t TSize, size_t &NewCapacity)
This is a helper for grow() that's out of line to reduce code duplication.
void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
void * replaceAllocation (void *NewElts, size_t TSize, size_t NewCapacity, size_t VSize=0)
If vector was first created with capacity 0, getFirstEl() points to the memory right after, an area unallocated.
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
void set_allocation_range (void *Begin, size_t N)
Set the array data pointer to Begin and capacity to N.
Static Protected Member Functions
static void destroy_range (T *, T *)
template<typename It1 , typename It2 >
static void uninitialized_move (It1 I, It1 E, It2 Dest)
Move the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
template<typename It1 , typename It2 >
static void uninitialized_copy (It1 I, It1 E, It2 Dest)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
template<typename T1 , typename T2 >
static void uninitialized_copy (T1 *I, T1 *E, T2 *Dest, std::enable_if_t< std::is_same< std::remove_const_t< T1 >, T2 >::value > *=nullptr)
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
static ValueParamT forward_value_param (ValueParamT V)
Copy V or return a reference, depending on ValueParamT.
Static Protected Member Functions inherited from llvm::SmallVectorTemplateCommon< T, typename >
template<class U >
static const T * reserveForParamAndGetAddressImpl (U *This, const T &Elt, size_t N)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Static Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
Static Protected Attributes
static constexpr bool TakesParamByValue = sizeof(T) <= 2 * sizeof(void *)
True if it's cheap enough to take parameters by value.
Friends
class SmallVectorTemplateCommon< T >
Additional Inherited Members
Public Types inherited from llvm::SmallVectorTemplateCommon< T, typename >
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using reverse_iterator = std::reverse_iterator< iterator >
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Protected Attributes inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
void * BeginX
SmallVectorSizeType< T > Size
SmallVectorSizeType< T > Capacity
Detailed Description
template<typename T>
class llvm::SmallVectorTemplateBase< T, true >
SmallVectorTemplateBase<TriviallyCopyable = true> - This is where we put method implementations that are designed to work with trivially copyable T's.
This allows using memcpy in place of copy/move construction and skipping destruction.
Definition at line 488 of file SmallVector.h.
Member Typedef Documentation
ValueParamT
template<typename T > using llvm::SmallVectorTemplateBase< T, true >::ValueParamT = std::conditional_t<TakesParamByValue, T, const T &> protected
Either const T& or T, depending on whether it's cheap enough to take parameters by value.
Definition at line 498 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorTemplateBase()
template<typename T > llvm::SmallVectorTemplateBase< T, true >::SmallVectorTemplateBase (size_t Size) inline protected
Definition at line 500 of file SmallVector.h.
Member Function Documentation
destroy_range()
template<typename T > static void llvm::SmallVectorTemplateBase< T, true >::destroy_range (T * , T *) inline static protected
Definition at line 503 of file SmallVector.h.
forward_value_param()
template<typename T > static ValueParamT llvm::SmallVectorTemplateBase< T, true >::forward_value_param (ValueParamT V) inline static protected
Copy V or return a reference, depending on ValueParamT.
Definition at line 554 of file SmallVector.h.
grow()
template<typename T > void llvm::SmallVectorTemplateBase< T, true >::grow (size_t MinSize = 0) inline protected
Double the size of the allocated memory, guaranteeing space for at least one more element or MinSize if specified.
Definition at line 538 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::grow_pod().
growAndAssign()
template<typename T > void llvm::SmallVectorTemplateBase< T, true >::growAndAssign (size_t NumElts, T Elt) inline protected
Definition at line 556 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateBase< T, bool >::grow(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size().
growAndEmplaceBack()
template<typename T > template<typename... ArgTypes> T & llvm::SmallVectorTemplateBase< T, true >::growAndEmplaceBack (ArgTypes &&... Args) inline protected
Definition at line 565 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and T.
pop_back()
template<typename T > void llvm::SmallVectorTemplateBase< T, true >::pop_back () inline
Definition at line 580 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
push_back()
template<typename T > void llvm::SmallVectorTemplateBase< T, true >::push_back (ValueParamT Elt) inline
Definition at line 574 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::set_size(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
reserveForParamAndGetAddress() [1/2]
template<typename T > const T * llvm::SmallVectorTemplateBase< T, true >::reserveForParamAndGetAddress (const T & Elt, size_t N = 1) inline protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 542 of file SmallVector.h.
References N, and llvm::SmallVectorTemplateCommon< T, typename >::reserveForParamAndGetAddressImpl().
reserveForParamAndGetAddress() [2/2]
template<typename T > T * llvm::SmallVectorTemplateBase< T, true >::reserveForParamAndGetAddress (T & Elt, size_t N = 1) inline protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 548 of file SmallVector.h.
References N, and llvm::SmallVectorTemplateCommon< T, typename >::reserveForParamAndGetAddressImpl().
uninitialized_copy() [1/2]
template<typename T > template<typename It1 , typename It2 > static void llvm::SmallVectorTemplateBase< T, true >::uninitialized_copy (It1 I, It1 E, It2 Dest) inline static protected
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
Definition at line 516 of file SmallVector.h.
References E, and I.
uninitialized_copy() [2/2]
template<typename T > template<typename T1 , typename T2 > static void llvm::SmallVectorTemplateBase< T, true >::uninitialized_copy (T1 * I, T1 * E, T2 * Dest, std::enable_if_t< std::is_same< std::remove_const_t< T1 >, T2 >::value > * = nullptr) inline static protected
Copy the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
Definition at line 524 of file SmallVector.h.
References E, and I.
uninitialized_move()
template<typename T > template<typename It1 , typename It2 > static void llvm::SmallVectorTemplateBase< T, true >::uninitialized_move (It1 I, It1 E, It2 Dest) inline static protected
Move the range [I, E) onto the uninitialized memory starting with "Dest", constructing elements into it as needed.
Definition at line 508 of file SmallVector.h.
References E, I, and llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy().
Friends And Related Function Documentation
SmallVectorTemplateCommon< T >
template<typename T > friend class SmallVectorTemplateCommon< T > friend
Definition at line 438 of file SmallVector.h.
Member Data Documentation
TakesParamByValue
template<typename T > constexpr bool llvm::SmallVectorTemplateBase< T, true >::TakesParamByValue = sizeof(T) <= 2 * sizeof(void *) static constexpr protected
True if it's cheap enough to take parameters by value.
Doing so avoids overhead related to mitigations for reference invalidation.
Definition at line 494 of file SmallVector.h.
The documentation for this class was generated from the following file:
include/llvm/ADT/SmallVector.h