LLVM: llvm::dwarf_linker::parallel::DwarfEmitterImpl Class Reference
llvm::dwarf_linker::parallel::DwarfEmitterImpl Class Reference
This class emits DWARF data to the output stream.
#include "DWARFLinker/Parallel/DWARFEmitterImpl.h"
Public Member Functions
DwarfEmitterImpl (DWARFLinker::OutputFileType OutFileType, raw_pwrite_stream &OutFile)
Error init (Triple TheTriple, StringRef Swift5ReflectionSegmentName)
Initialize AsmPrinter data.
const Triple & getTargetTriple ()
Returns triple of output stream.
void finish ()
Dump the file to the disk.
void emitAbbrevs (const SmallVector< std::unique_ptr< DIEAbbrev > > &Abbrevs, unsigned DwarfVersion)
Emit abbreviations.
void emitCompileUnitHeader (DwarfUnit &Unit)
Emit compile unit header.
void emitDIE (DIE &Die)
Emit DIE recursively.
uint64_t getDebugInfoSectionSize () const
Returns size of generated .debug_info section.
void emitDebugNames (DWARF5AccelTable &Table, DebugNamesUnitsOffsets &CUOffsets, CompUnitIDToIdx &UnitIDToIdxMap)
Emits .debug_names section according to the specified Table.
void emitAppleNames (AccelTable< AppleAccelTableStaticOffsetData > &Table)
Emits .apple_names section according to the specified Table.
void emitAppleNamespaces (AccelTable< AppleAccelTableStaticOffsetData > &Table)
Emits .apple_namespaces section according to the specified Table.
void emitAppleObjc (AccelTable< AppleAccelTableStaticOffsetData > &Table)
Emits .apple_objc section according to the specified Table.
void emitAppleTypes (AccelTable< AppleAccelTableStaticTypeData > &Table)
Emits .apple_types section according to the specified Table.
Detailed Description
This class emits DWARF data to the output stream.
It emits already generated section data and specific data, which could not be generated by CompileUnit.
Definition at line 48 of file DWARFEmitterImpl.h.
Constructor & Destructor Documentation
DwarfEmitterImpl()
llvm::dwarf_linker::parallel::DwarfEmitterImpl::DwarfEmitterImpl (DWARFLinker::OutputFileType OutFileType, raw_pwrite_stream & OutFile) inline
Definition at line 50 of file DWARFEmitterImpl.h.
Member Function Documentation
emitAbbrevs()
void DwarfEmitterImpl::emitAbbrevs (const SmallVector< std::unique_ptr< DIEAbbrev > > & Abbrevs, unsigned DwarfVersion)
Emit abbreviations.
Definition at line 123 of file DWARFEmitterImpl.cpp.
References llvm::MCStreamer::switchSection().
emitAppleNames()
void DwarfEmitterImpl::emitAppleNames (AccelTable< AppleAccelTableStaticOffsetData > & Table)
Emits .apple_names section according to the specified Table.
Definition at line 191 of file DWARFEmitterImpl.cpp.
References llvm::emitAppleAccelTable().
emitAppleNamespaces()
void DwarfEmitterImpl::emitAppleNamespaces (AccelTable< AppleAccelTableStaticOffsetData > & Table)
Emits .apple_namespaces section according to the specified Table.
Definition at line 183 of file DWARFEmitterImpl.cpp.
References llvm::emitAppleAccelTable().
emitAppleObjc()
void DwarfEmitterImpl::emitAppleObjc (AccelTable< AppleAccelTableStaticOffsetData > & Table)
Emits .apple_objc section according to the specified Table.
Definition at line 199 of file DWARFEmitterImpl.cpp.
References llvm::emitAppleAccelTable().
emitAppleTypes()
void DwarfEmitterImpl::emitAppleTypes (AccelTable< AppleAccelTableStaticTypeData > & Table)
Emits .apple_types section according to the specified Table.
Definition at line 207 of file DWARFEmitterImpl.cpp.
References llvm::emitAppleAccelTable().
emitCompileUnitHeader()
void DwarfEmitterImpl::emitCompileUnitHeader (DwarfUnit & Unit)
Emit compile unit header.
Definition at line 131 of file DWARFEmitterImpl.cpp.
References llvm::MCStreamer::switchSection().
emitDebugNames()
void DwarfEmitterImpl::emitDebugNames (DWARF5AccelTable & Table, DebugNamesUnitsOffsets & CUOffsets, CompUnitIDToIdx & UnitIDToIdxMap)
Emits .debug_names section according to the specified Table.
Definition at line 161 of file DWARFEmitterImpl.cpp.
References llvm::DIEInteger::BestForm(), llvm::emitDWARF5AccelTable(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size().
emitDIE()
void DwarfEmitterImpl::emitDIE (DIE & Die)
Emit DIE recursively.
Definition at line 155 of file DWARFEmitterImpl.cpp.
References llvm::DIE::getSize(), and llvm::MCStreamer::switchSection().
finish()
void llvm::dwarf_linker::parallel::DwarfEmitterImpl::finish () inline
Dump the file to the disk.
Definition at line 61 of file DWARFEmitterImpl.h.
References llvm::MCStreamer::finish().
getDebugInfoSectionSize()
uint64_t llvm::dwarf_linker::parallel::DwarfEmitterImpl::getDebugInfoSectionSize () const inline
Returns size of generated .debug_info section.
Definition at line 74 of file DWARFEmitterImpl.h.
getTargetTriple()
const Triple & llvm::dwarf_linker::parallel::DwarfEmitterImpl::getTargetTriple () inline
Returns triple of output stream.
Definition at line 58 of file DWARFEmitterImpl.h.
init()
Error DwarfEmitterImpl::init (Triple TheTriple, StringRef Swift5ReflectionSegmentName)
Initialize AsmPrinter data.
Definition at line 24 of file DWARFEmitterImpl.cpp.
References llvm::dwarf_linker::DWARFLinkerBase::Assembly, llvm::Target::createAsmPrinter(), llvm::Target::createAsmStreamer(), llvm::Target::createMCAsmBackend(), llvm::Target::createMCAsmInfo(), llvm::Target::createMCCodeEmitter(), llvm::Target::createMCInstPrinter(), llvm::Target::createMCInstrInfo(), llvm::Target::createMCObjectFileInfo(), llvm::Target::createMCObjectStreamer(), llvm::Target::createMCRegInfo(), llvm::Target::createMCSubtargetInfo(), llvm::MCAsmBackend::createObjectWriter(), llvm::createStringError(), llvm::Target::createTargetMachine(), llvm::Triple::getTriple(), llvm::mc::InitMCTargetOptionsFromFlags(), llvm::TargetRegistry::lookupTarget(), llvm::MCTargetOptions::MCIncrementalLinkerCompatible, llvm::MCTargetOptions::MCRelaxAll, llvm::dwarf_linker::DWARFLinkerBase::Object, and llvm::Error::success().
The documentation for this class was generated from the following files:
lib/DWARFLinker/Parallel/DWARFEmitterImpl.h
lib/DWARFLinker/Parallel/DWARFEmitterImpl.cpp