LLVM: llvm::GCNDownwardRPTracker Class Reference
llvm::GCNDownwardRPTracker Class Reference
#include "Target/AMDGPU/GCNRegPressure.h"
Public Member Functions
GCNDownwardRPTracker (const LiveIntervals &LIS_)
MachineBasicBlock::const_iterator getNext () const
GCNRegPressure moveMaxPressure ()
bool reset (const MachineInstr &MI, const LiveRegSet *LiveRegs=nullptr)
bool advanceBeforeNext ()
void advanceToNext ()
bool advance ()
bool advance (MachineBasicBlock::const_iterator End)
bool advance (MachineBasicBlock::const_iterator Begin, MachineBasicBlock::const_iterator End, const LiveRegSet *LiveRegsCopy=nullptr)
Public Member Functions inherited from llvm::GCNRPTracker
const decltype(LiveRegs) & getLiveRegs () const
const MachineInstr * getLastTrackedMI () const
void clearMaxPressure ()
GCNRegPressure getPressure () const
decltype(LiveRegs) moveLiveRegs ()
Additional Inherited Members
Public Types inherited from llvm::GCNRPTracker
using LiveRegSet = DenseMap< unsigned, LaneBitmask >
Protected Member Functions inherited from llvm::GCNRPTracker
GCNRPTracker (const LiveIntervals &LIS_)
void reset (const MachineInstr &MI, const LiveRegSet *LiveRegsCopy, bool After)
Protected Attributes inherited from llvm::GCNRPTracker
const LiveIntervals & LIS
LiveRegSet LiveRegs
GCNRegPressure CurPressure
GCNRegPressure MaxPressure
const MachineInstr * LastTrackedMI = nullptr
const MachineRegisterInfo * MRI = nullptr
Detailed Description
Definition at line 208 of file GCNRegPressure.h.
Constructor & Destructor Documentation
GCNDownwardRPTracker()
llvm::GCNDownwardRPTracker::GCNDownwardRPTracker (const LiveIntervals & LIS_) inline
Definition at line 215 of file GCNRegPressure.h.
Member Function Documentation
advance() [1/3]
bool GCNDownwardRPTracker::advance ()
Definition at line 417 of file GCNRegPressure.cpp.
References advanceBeforeNext(), and advanceToNext().
Referenced by advance().
advance() [2/3]
bool GCNDownwardRPTracker::advance (MachineBasicBlock::const_iterator Begin, MachineBasicBlock::const_iterator End, const LiveRegSet * LiveRegsCopy = nullptr)
Definition at line 431 of file GCNRegPressure.cpp.
References advance(), End, and reset().
advance() [3/3]
bool GCNDownwardRPTracker::advance (MachineBasicBlock::const_iterator End)
Definition at line 425 of file GCNRegPressure.cpp.
References advance(), and End.
advanceBeforeNext()
bool GCNDownwardRPTracker::advanceBeforeNext ()
Definition at line 345 of file GCNRegPressure.cpp.
References assert(), llvm::GCNRPTracker::CurPressure, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::SlotIndex::getBaseIndex(), llvm::SlotIndex::getDeadSlot(), llvm::LiveIntervals::getInstructionIndex(), llvm::LiveIntervals::getInterval(), llvm::LaneBitmask::getNone(), llvm::LiveInterval::hasSubRanges(), llvm::GCNRegPressure::inc(), llvm::SmallSet< T, N, C >::insert(), llvm::GCNRPTracker::LastTrackedMI, llvm::GCNRPTracker::LIS, llvm::LiveRange::liveAt(), llvm::GCNRPTracker::LiveRegs, llvm_unreachable, llvm::max(), llvm::GCNRPTracker::MaxPressure, llvm::GCNRPTracker::MRI, llvm::MachineInstr::operands(), and llvm::LiveInterval::subranges().
Referenced by advance(), and llvm::GCNRegPressurePrinter::runOnMachineFunction().
advanceToNext()
void GCNDownwardRPTracker::advanceToNext ()
Definition at line 399 of file GCNRegPressure.cpp.
References llvm::MachineInstr::all_defs(), llvm::GCNRPTracker::CurPressure, getDefRegMask(), llvm::GCNRegPressure::inc(), llvm::GCNRPTracker::LastTrackedMI, llvm::GCNRPTracker::LiveRegs, llvm::max(), llvm::GCNRPTracker::MaxPressure, llvm::GCNRPTracker::MRI, and llvm::skipDebugInstructionsForward().
Referenced by advance(), and llvm::GCNRegPressurePrinter::runOnMachineFunction().
getNext()
MachineBasicBlock::const_iterator llvm::GCNDownwardRPTracker::getNext () const inline
Definition at line 217 of file GCNRegPressure.h.
moveMaxPressure()
GCNRegPressure llvm::GCNDownwardRPTracker::moveMaxPressure () inline
Definition at line 220 of file GCNRegPressure.h.
References llvm::GCNRegPressure::clear(), and llvm::GCNRPTracker::MaxPressure.
reset()
bool GCNDownwardRPTracker::reset (const MachineInstr & MI, const LiveRegSet * LiveRegs = nullptr)
Definition at line 332 of file GCNRegPressure.cpp.
References llvm::GCNRPTracker::LastTrackedMI, MI, llvm::GCNRPTracker::MRI, llvm::GCNRPTracker::reset(), and llvm::skipDebugInstructionsForward().
Referenced by advance(), and llvm::GCNRegPressurePrinter::runOnMachineFunction().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNRegPressure.h
lib/Target/AMDGPU/GCNRegPressure.cpp