LLVM: llvm::CSKYMachineFunctionInfo Class Reference
llvm::CSKYMachineFunctionInfo Class Reference
#include "Target/CSKY/CSKYMachineFunctionInfo.h"
Public Member Functions
CSKYMachineFunctionInfo (const Function &F, const TargetSubtargetInfo *STI)
MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const override
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
Register getGlobalBaseReg () const
void setGlobalBaseReg (Register Reg)
void setSpillsCR ()
bool isCRSpilled () const
void setVarArgsFrameIndex (int v)
int getVarArgsFrameIndex ()
unsigned getVarArgsSaveSize () const
void setVarArgsSaveSize (int Size)
bool isLRSpilled () const
void setLRIsSpilled (bool s)
void setCalleeSaveAreaSize (int v)
int getCalleeSaveAreaSize () const
unsigned createPICLabelUId ()
void initPICLabelUId (unsigned UId)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
virtual MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy , typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Detailed Description
Definition at line 20 of file CSKYMachineFunctionInfo.h.
Constructor & Destructor Documentation
CSKYMachineFunctionInfo()
llvm::CSKYMachineFunctionInfo::CSKYMachineFunctionInfo (const Function & F, const TargetSubtargetInfo * STI) inline
Definition at line 34 of file CSKYMachineFunctionInfo.h.
Member Function Documentation
clone()
MachineFunctionInfo * llvm::CSKYMachineFunctionInfo::clone (BumpPtrAllocator & Allocator, MachineFunction & DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) const inline override virtual
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
This requires remapping MachineBasicBlock references from the original parent to values in the new function. Targets may assume that virtual register and frame index values are preserved in the new function.
Reimplemented from llvm::MachineFunctionInfo.
Definition at line 37 of file CSKYMachineFunctionInfo.h.
References llvm::MachineFunction::cloneInfo().
createPICLabelUId()
unsigned llvm::CSKYMachineFunctionInfo::createPICLabelUId () inline
Definition at line 61 of file CSKYMachineFunctionInfo.h.
getCalleeSaveAreaSize()
int llvm::CSKYMachineFunctionInfo::getCalleeSaveAreaSize () const inline
Definition at line 59 of file CSKYMachineFunctionInfo.h.
Referenced by llvm::CSKYFrameLowering::emitEpilogue(), llvm::CSKYFrameLowering::emitPrologue(), and llvm::CSKYFrameLowering::getFrameIndexReference().
getGlobalBaseReg()
Register llvm::CSKYMachineFunctionInfo::getGlobalBaseReg () const inline
Definition at line 43 of file CSKYMachineFunctionInfo.h.
Referenced by llvm::CSKYInstrInfo::getGlobalBaseReg().
getVarArgsFrameIndex()
int llvm::CSKYMachineFunctionInfo::getVarArgsFrameIndex () inline
Definition at line 50 of file CSKYMachineFunctionInfo.h.
getVarArgsSaveSize()
unsigned llvm::CSKYMachineFunctionInfo::getVarArgsSaveSize () const inline
Definition at line 52 of file CSKYMachineFunctionInfo.h.
Referenced by llvm::CSKYFrameLowering::emitEpilogue(), llvm::CSKYFrameLowering::emitPrologue(), and llvm::CSKYFrameLowering::getFrameIndexReference().
initPICLabelUId()
void llvm::CSKYMachineFunctionInfo::initPICLabelUId (unsigned UId) inline
Definition at line 62 of file CSKYMachineFunctionInfo.h.
isCRSpilled()
bool llvm::CSKYMachineFunctionInfo::isCRSpilled () const inline
Definition at line 47 of file CSKYMachineFunctionInfo.h.
Referenced by llvm::CSKYFrameLowering::determineCalleeSaves().
isLRSpilled()
bool llvm::CSKYMachineFunctionInfo::isLRSpilled () const inline
Definition at line 55 of file CSKYMachineFunctionInfo.h.
setCalleeSaveAreaSize()
void llvm::CSKYMachineFunctionInfo::setCalleeSaveAreaSize (int v) inline
Definition at line 58 of file CSKYMachineFunctionInfo.h.
Referenced by llvm::CSKYFrameLowering::determineCalleeSaves().
setGlobalBaseReg()
void llvm::CSKYMachineFunctionInfo::setGlobalBaseReg (Register Reg) inline
Definition at line 44 of file CSKYMachineFunctionInfo.h.
References Reg.
Referenced by llvm::CSKYInstrInfo::getGlobalBaseReg().
setLRIsSpilled()
void llvm::CSKYMachineFunctionInfo::setLRIsSpilled (bool s) inline
Definition at line 56 of file CSKYMachineFunctionInfo.h.
Referenced by llvm::CSKYFrameLowering::determineCalleeSaves().
setSpillsCR()
void llvm::CSKYMachineFunctionInfo::setSpillsCR () inline
Definition at line 46 of file CSKYMachineFunctionInfo.h.
Referenced by llvm::CSKYInstrInfo::loadRegFromStackSlot(), and llvm::CSKYInstrInfo::storeRegToStackSlot().
setVarArgsFrameIndex()
void llvm::CSKYMachineFunctionInfo::setVarArgsFrameIndex (int v) inline
Definition at line 49 of file CSKYMachineFunctionInfo.h.
setVarArgsSaveSize()
void llvm::CSKYMachineFunctionInfo::setVarArgsSaveSize (int Size) inline
Definition at line 53 of file CSKYMachineFunctionInfo.h.
References Size.
The documentation for this class was generated from the following file:
lib/Target/CSKY/CSKYMachineFunctionInfo.h