LLVM: llvm::DomTreeNodeBase< NodeT > Class Template Reference
llvm::DomTreeNodeBase< NodeT > Class Template Reference
Base class for the actual dominator tree node.
#include "llvm/Support/GenericDomTree.h"
Public Types
using iterator = typename SmallVector< DomTreeNodeBase *, 4 >::iterator
using const_iterator = typename SmallVector< DomTreeNodeBase *, 4 >::const_iterator
Public Member Functions
DomTreeNodeBase (NodeT *BB, DomTreeNodeBase *iDom)
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
DomTreeNodeBase *const & back () const
DomTreeNodeBase *& back ()
iterator_range< iterator > children ()
iterator_range< const_iterator > children () const
NodeT * getBlock () const
DomTreeNodeBase * getIDom () const
unsigned getLevel () const
std::unique_ptr< DomTreeNodeBase > addChild (std::unique_ptr< DomTreeNodeBase > C)
bool isLeaf () const
size_t getNumChildren () const
void clearAllChildren ()
bool compare (const DomTreeNodeBase *Other) const
void setIDom (DomTreeNodeBase *NewIDom)
unsigned getDFSNumIn () const
getDFSNumIn/getDFSNumOut - These return the DFS visitation order for nodes in the dominator tree.
unsigned getDFSNumOut () const
Friends
class PostDominatorTree
class DominatorTreeBase< NodeT, false >
class DominatorTreeBase< NodeT, true >
struct DomTreeBuilder::SemiNCAInfo< DominatorTreeBase< NodeT, false > >
struct DomTreeBuilder::SemiNCAInfo< DominatorTreeBase< NodeT, true > >
Detailed Description
template<class NodeT>
class llvm::DomTreeNodeBase< NodeT >
Base class for the actual dominator tree node.
Definition at line 54 of file GenericDomTree.h.
Member Typedef Documentation
const_iterator
template<class NodeT > using llvm::DomTreeNodeBase< NodeT >::const_iterator = typename SmallVector<DomTreeNodeBase *, 4>::const_iterator
Definition at line 73 of file GenericDomTree.h.
iterator
template<class NodeT > using llvm::DomTreeNodeBase< NodeT >::iterator = typename SmallVector<DomTreeNodeBase *, 4>::iterator
Definition at line 72 of file GenericDomTree.h.
Constructor & Destructor Documentation
DomTreeNodeBase()
template<class NodeT > llvm::DomTreeNodeBase< NodeT >::DomTreeNodeBase (NodeT * BB, DomTreeNodeBase< NodeT > * iDom) inline
Definition at line 69 of file GenericDomTree.h.
Member Function Documentation
addChild()
template<class NodeT > std::unique_ptr< DomTreeNodeBase > llvm::DomTreeNodeBase< NodeT >::addChild (std::unique_ptr< DomTreeNodeBase< NodeT > > C) inline
Definition at line 93 of file GenericDomTree.h.
References llvm::CallingConv::C.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::createChild(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot().
back() [1/2]
template<class NodeT > DomTreeNodeBase *& llvm::DomTreeNodeBase< NodeT >::back () inline
Definition at line 82 of file GenericDomTree.h.
back() [2/2]
template<class NodeT > DomTreeNodeBase *const & llvm::DomTreeNodeBase< NodeT >::back () const inline
Definition at line 81 of file GenericDomTree.h.
begin() [1/2]
template<class NodeT > iterator llvm::DomTreeNodeBase< NodeT >::begin () inline
Definition at line 76 of file GenericDomTree.h.
Referenced by llvm::ForwardDominanceFrontierBase< BlockT >::calculate(), llvm::DomTreeNodeBase< NodeT >::children(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers().
begin() [2/2]
template<class NodeT > const_iterator llvm::DomTreeNodeBase< NodeT >::begin () const inline
Definition at line 78 of file GenericDomTree.h.
children() [1/2]
template<class NodeT > iterator_range< iterator > llvm::DomTreeNodeBase< NodeT >::children () inline
Definition at line 84 of file GenericDomTree.h.
References llvm::DomTreeNodeBase< NodeT >::begin(), llvm::DomTreeNodeBase< NodeT >::end(), and llvm::make_range().
Referenced by findBestInsertionSet(), getDominatees(), llvm::MergeBlockIntoPredecessor(), llvm::UnrollLoop(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty().
children() [2/2]
template<class NodeT > iterator_range< const_iterator > llvm::DomTreeNodeBase< NodeT >::children () const inline
Definition at line 85 of file GenericDomTree.h.
References llvm::DomTreeNodeBase< NodeT >::begin(), llvm::DomTreeNodeBase< NodeT >::end(), and llvm::make_range().
clearAllChildren()
template<class NodeT > void llvm::DomTreeNodeBase< NodeT >::clearAllChildren () inline
Definition at line 102 of file GenericDomTree.h.
compare()
template<class NodeT > bool llvm::DomTreeNodeBase< NodeT >::compare (const DomTreeNodeBase< NodeT > * Other) const inline
Definition at line 104 of file GenericDomTree.h.
References llvm::SmallPtrSetImpl< PtrType >::count(), llvm::DomTreeNodeBase< NodeT >::getNumChildren(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), N, and llvm::Other.
Referenced by llvm::DominatorTreeBase< NodeT, IsPostDom >::compare().
end() [1/2]
template<class NodeT > iterator llvm::DomTreeNodeBase< NodeT >::end () inline
Definition at line 77 of file GenericDomTree.h.
Referenced by llvm::ForwardDominanceFrontierBase< BlockT >::calculate(), and llvm::DomTreeNodeBase< NodeT >::children().
end() [2/2]
template<class NodeT > const_iterator llvm::DomTreeNodeBase< NodeT >::end () const inline
Definition at line 79 of file GenericDomTree.h.
getBlock()
template<class NodeT > NodeT * llvm::DomTreeNodeBase< NodeT >::getBlock () const inline
Definition at line 89 of file GenericDomTree.h.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::attachNewSubtree(), llvm::ForwardDominanceFrontierBase< BlockT >::calculate(), llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), cloneLoopBlocks(), CloneLoopBlocks(), llvm::cloneLoopWithPreheader(), computeBlocksDominatingExits(), containsUnconditionalCallSafepoint(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::EraseNode(), findBestInsertionSet(), llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::HasProperSupport(), llvm::hoistRegion(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), isGuaranteedNotToBeUndefOrPoison(), preheader(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::reattachExistingSubtree(), simplifyUsingControlFlow(), SinkInstruction(), llvm::UnrollRuntimeLoopRemainder(), UpdateAnalysisInformation(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsBeforeInsertion(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyLevels(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyReachability(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty().
getDFSNumIn()
template<class NodeT > unsigned llvm::DomTreeNodeBase< NodeT >::getDFSNumIn () const inline
getDFSNumIn/getDFSNumOut - These return the DFS visitation order for nodes in the dominator tree.
They are only guaranteed valid if updateDFSNumbers() has been called.
Definition at line 144 of file GenericDomTree.h.
Referenced by llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), checkAndReplaceCondition(), compareCmp(), llvm::ValueDFS_Compare::comparePHIRelated(), llvm::PhiLoweringHelper::lowerPhis(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyDFSNumbers().
getDFSNumOut()
template<class NodeT > unsigned llvm::DomTreeNodeBase< NodeT >::getDFSNumOut () const inline
Definition at line 145 of file GenericDomTree.h.
Referenced by checkAndReplaceCondition().
getIDom()
template<class NodeT > DomTreeNodeBase * llvm::DomTreeNodeBase< NodeT >::getIDom () const inline
Definition at line 90 of file GenericDomTree.h.
Referenced by cloneLoopBlocks(), CloneLoopBlocks(), llvm::cloneLoopWithPreheader(), computeBlocksDominatingExits(), containsUnconditionalCallSafepoint(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteEdge(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::InnerLoopVectorizer::emitIterationCountCheck(), llvm::EpilogueVectorizerMainLoop::emitIterationCountCheck(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::EraseNode(), findBestInsertionSet(), llvm::hoistRegion(), isGuaranteedNotToBeUndefOrPoison(), preheader(), simplifyUsingControlFlow(), SinkInstruction(), llvm::UnrollAndJamLoop(), llvm::UnrollLoop(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateInsertion(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateRootsBeforeInsertion(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyLevels().
getLevel()
template<class NodeT > unsigned llvm::DomTreeNodeBase< NodeT >::getLevel () const inline
Definition at line 91 of file GenericDomTree.h.
Referenced by llvm::IDFCalculatorBase< NodeTy, IsPostDom >::calculate(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteReachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::DeleteUnreachable(), llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::InsertReachable(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateInsertion(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::VerifyLevels().
getNumChildren()
template<class NodeT > size_t llvm::DomTreeNodeBase< NodeT >::getNumChildren () const inline
Definition at line 100 of file GenericDomTree.h.
Referenced by llvm::DomTreeNodeBase< NodeT >::compare(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::EraseNode().
isLeaf()
template<class NodeT > bool llvm::DomTreeNodeBase< NodeT >::isLeaf () const inline
Definition at line 99 of file GenericDomTree.h.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifyParentProperty(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::verifySiblingProperty().
setIDom()
template<class NodeT > void llvm::DomTreeNodeBase< NodeT >::setIDom (DomTreeNodeBase< NodeT > * NewIDom) inline
Definition at line 124 of file GenericDomTree.h.
References assert(), llvm::find(), and I.
Referenced by llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::reattachExistingSubtree(), and llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::UpdateInsertion().
Friends And Related Function Documentation
DominatorTreeBase< NodeT, false >
template<class NodeT > friend class DominatorTreeBase< NodeT, false > friend
Definition at line 55 of file GenericDomTree.h.
DominatorTreeBase< NodeT, true >
template<class NodeT > friend class DominatorTreeBase< NodeT, true > friend
Definition at line 55 of file GenericDomTree.h.
DomTreeBuilder::SemiNCAInfo< DominatorTreeBase< NodeT, false > >
template<class NodeT > friend struct DomTreeBuilder::SemiNCAInfo< DominatorTreeBase< NodeT, false > > friend
Definition at line 55 of file GenericDomTree.h.
DomTreeBuilder::SemiNCAInfo< DominatorTreeBase< NodeT, true > >
template<class NodeT > friend struct DomTreeBuilder::SemiNCAInfo< DominatorTreeBase< NodeT, true > > friend
Definition at line 55 of file GenericDomTree.h.
PostDominatorTree
template<class NodeT > friend class PostDominatorTree friend
Definition at line 55 of file GenericDomTree.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/LiveIntervalCalc.h
include/llvm/Support/GenericDomTree.h