LLVM: llvm::MCFragment Class Reference
llvm::MCFragment Class Reference
#include "llvm/MC/MCFragment.h"
Public Types
enum FragmentType : uint8_t {
FT_Align , FT_Data , FT_CompactEncodedInst , FT_Fill ,
FT_Nops , FT_Relaxable , FT_Org , FT_Dwarf ,
FT_DwarfFrame , FT_LEB , FT_BoundaryAlign , FT_SymbolId ,
FT_CVInlineLines , FT_CVDefRange , FT_PseudoProbe , FT_Dummy
}
Public Member Functions
MCFragment ()=delete
MCFragment (const MCFragment &)=delete
MCFragment & operator= (const MCFragment &)=delete
void destroy ()
Destroys the current fragment.
FragmentType getKind () const
MCSection * getParent () const
void setParent (MCSection *Value)
const MCSymbol * getAtom () const
void setAtom (const MCSymbol *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
void dump () const
void setSubsectionNumber (unsigned Value)
unsigned getSubsectionNumber () const
Public Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
MCFragment * getPrevNode ()
const MCFragment * getPrevNode () const
Get the previous node, or nullptr for the list head.
MCFragment * getNextNode ()
Get the next node, or nullptr for the list tail.
const MCFragment * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Protected Member Functions
MCFragment (FragmentType Kind, bool HasInstructions, MCSection *Parent=nullptr)
Protected Member Functions inherited from llvm::ilist_node_with_parent< MCFragment, MCSection >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Protected Attributes
bool HasInstructions
bool LinkerRelaxable = false
Friends
class MCAsmLayout
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator = typename ilist_select_iterator_type< OptionsT::has_iterator_bits, ilist_detail::compute_node_options< T, Options... >::type, false, false >::type
using const_self_iterator = typename ilist_select_iterator_type< OptionsT::has_iterator_bits, ilist_detail::compute_node_options< T, Options... >::type, false, true >::type
using reverse_self_iterator = typename ilist_select_iterator_type< OptionsT::has_iterator_bits, ilist_detail::compute_node_options< T, Options... >::type, true, false >::type
using const_reverse_self_iterator = typename ilist_select_iterator_type< OptionsT::has_iterator_bits, ilist_detail::compute_node_options< T, Options... >::type, true, true >::type
Detailed Description
Definition at line 30 of file MCFragment.h.
Member Enumeration Documentation
FragmentType
enum llvm::MCFragment::FragmentType : uint8_t
Enumerator
FT_Align
FT_Data
FT_CompactEncodedInst
FT_Fill
FT_Nops
FT_Relaxable
FT_Org
FT_Dwarf
FT_DwarfFrame
FT_LEB
FT_BoundaryAlign
FT_SymbolId
FT_CVInlineLines
FT_CVDefRange
FT_PseudoProbe
FT_Dummy
Definition at line 34 of file MCFragment.h.
Constructor & Destructor Documentation
MCFragment() [1/3]
MCFragment::MCFragment (FragmentType Kind, bool HasInstructions, MCSection * Parent = nullptr) protected
Definition at line 258 of file MCFragment.cpp.
References llvm::MCSection::getFragmentList(), and llvm::iplist_impl< IntrusiveListT, TraitsT >::push_back().
MCFragment() [2/3]
llvm::MCFragment::MCFragment () delete
MCFragment() [3/3]
llvm::MCFragment::MCFragment (const MCFragment &) delete
Member Function Documentation
destroy()
void MCFragment::destroy ()
Destroys the current fragment.
This must be used instead of delete as MCFragment is non-virtual. This method will dispatch to the appropriate subclass.
Definition at line 266 of file MCFragment.cpp.
References FT_Align, FT_BoundaryAlign, FT_CompactEncodedInst, FT_CVDefRange, FT_CVInlineLines, FT_Data, FT_Dummy, FT_Dwarf, FT_DwarfFrame, FT_Fill, FT_LEB, FT_Nops, FT_Org, FT_PseudoProbe, FT_Relaxable, and FT_SymbolId.
dump()
LLVM_DUMP_METHOD void MCFragment::dump () const
Definition at line 339 of file MCFragment.cpp.
References DF, llvm::errs(), F, FT_Align, FT_BoundaryAlign, FT_CompactEncodedInst, FT_CVDefRange, FT_CVInlineLines, FT_Data, FT_Dummy, FT_Dwarf, FT_DwarfFrame, FT_Fill, FT_LEB, FT_Nops, FT_Org, FT_PseudoProbe, FT_Relaxable, FT_SymbolId, getKind(), hasInstructions(), OS, and llvm::SmallVectorBase< Size_T >::size().
getAtom()
const MCSymbol * llvm::MCFragment::getAtom () const inline
Definition at line 99 of file MCFragment.h.
Referenced by llvm::MCAssembler::getAtom(), and llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl().
getKind()
FragmentType llvm::MCFragment::getKind () const inline
Definition at line 94 of file MCFragment.h.
Referenced by dump(), and getOffsetAndDataFragment().
getLayoutOrder()
unsigned llvm::MCFragment::getLayoutOrder () const inline
Definition at line 102 of file MCFragment.h.
Referenced by llvm::MCAsmLayout::canGetFragmentOffset().
getParent()
MCSection * llvm::MCFragment::getParent () const inline
Definition at line 96 of file MCFragment.h.
Referenced by AttemptToFoldSymbolOffsetDifference(), llvm::MCAssembler::computeFragmentSize(), llvm::MCAssembler::getAtom(), llvm::MachObjectWriter::getFragmentAddress(), llvm::MCSymbol::getSection(), llvm::MachObjectWriter::getSymbolAddress(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::MCBoundaryAlignFragment::setLastFragment(), and llvm::LoongArchAsmBackend::shouldInsertFixupForCodeAlign().
getSubsectionNumber()
unsigned llvm::MCFragment::getSubsectionNumber () const inline
Definition at line 112 of file MCFragment.h.
Referenced by AttemptToFoldSymbolOffsetDifference().
hasInstructions()
bool llvm::MCFragment::hasInstructions () const inline
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
Definition at line 107 of file MCFragment.h.
References HasInstructions.
Referenced by dump(), llvm::MCAssembler::layout(), and llvm::MCAssembler::writeFragmentPadding().
operator=()
MCFragment & llvm::MCFragment::operator= (const MCFragment &) delete
setAtom()
void llvm::MCFragment::setAtom (const MCSymbol * Value) inline
Definition at line 100 of file MCFragment.h.
setLayoutOrder()
void llvm::MCFragment::setLayoutOrder (unsigned Value) inline
Definition at line 103 of file MCFragment.h.
setParent()
void llvm::MCFragment::setParent (MCSection * Value) inline
Definition at line 97 of file MCFragment.h.
setSubsectionNumber()
void llvm::MCFragment::setSubsectionNumber (unsigned Value) inline
Definition at line 111 of file MCFragment.h.
Friends And Related Function Documentation
MCAsmLayout
friend class MCAsmLayout friend
Definition at line 31 of file MCFragment.h.
Member Data Documentation
HasInstructions
bool llvm::MCFragment::HasInstructions protected
Definition at line 77 of file MCFragment.h.
Referenced by hasInstructions(), and llvm::MCEncodedFragment::setHasInstructions().
LinkerRelaxable
bool llvm::MCFragment::LinkerRelaxable = false protected
Definition at line 78 of file MCFragment.h.
Referenced by llvm::MCDataFragment::isLinkerRelaxable(), and llvm::MCDataFragment::setLinkerRelaxable().
The documentation for this class was generated from the following files:
include/llvm/MC/MCFragment.h
lib/MC/MCFragment.cpp