LLVM: llvm::VPBlockBase Class Reference
llvm::VPBlockBase Class Reference abstract
VPBlockBase is the building block of the Hierarchical Control-Flow Graph.
#include "Transforms/Vectorize/VPlan.h"
Public Types
using VPBlockTy = enum { VPBasicBlockSC, VPRegionBlockSC }
An enumeration for keeping track of the concrete subclass of VPBlockBase that are actually instantiated.
using VPBlocksTy = SmallVectorImpl< VPBlockBase * >
Public Member Functions
virtual ~VPBlockBase ()=default
const std::string & getName () const
void setName (const Twine &newName)
unsigned getVPBlockID () const
VPRegionBlock * getParent ()
const VPRegionBlock * getParent () const
VPlan * getPlan ()
const VPlan * getPlan () const
void setPlan (VPlan *ParentPlan)
Sets the pointer of the plan containing the block.
void setParent (VPRegionBlock *P)
const VPBasicBlock * getEntryBasicBlock () const
VPBasicBlock * getEntryBasicBlock ()
const VPBasicBlock * getExitingBasicBlock () const
VPBasicBlock * getExitingBasicBlock ()
const VPBlocksTy & getSuccessors () const
VPBlocksTy & getSuccessors ()
iterator_range< VPBlockBase ** > successors ()
const VPBlocksTy & getPredecessors () const
VPBlocksTy & getPredecessors ()
VPBlockBase * getSingleSuccessor () const
VPBlockBase * getSinglePredecessor () const
size_t getNumSuccessors () const
size_t getNumPredecessors () const
VPBlockBase * getEnclosingBlockWithSuccessors ()
An Enclosing Block of a block B is any block containing B, including B itself.
VPBlockBase * getEnclosingBlockWithPredecessors ()
const VPBlocksTy & getHierarchicalSuccessors ()
VPBlockBase * getSingleHierarchicalSuccessor ()
const VPBlocksTy & getHierarchicalPredecessors ()
VPBlockBase * getSingleHierarchicalPredecessor ()
void setOneSuccessor (VPBlockBase *Successor)
Set a given VPBlockBase Successor as the single successor of this VPBlockBase.
void setTwoSuccessors (VPBlockBase *IfTrue, VPBlockBase *IfFalse)
Set two given VPBlockBases IfTrue and IfFalse to be the two successors of this VPBlockBase.
void setPredecessors (ArrayRef< VPBlockBase * > NewPreds)
Set each VPBasicBlock in NewPreds as predecessor of this VPBlockBase.
void clearPredecessors ()
Remove all the predecessor of this block.
void clearSuccessors ()
Remove all the successors of this block.
virtual void execute (VPTransformState *State)=0
The method which generates the output IR that correspond to this VPBlockBase, thereby "executing" the VPlan.
bool isLegalToHoistInto ()
Return true if it is legal to hoist instructions into this block.
virtual void dropAllReferences (VPValue *NewValue)=0
Replace all operands of VPUsers in the block with NewValue and also replaces all uses of VPValues defined in the block with NewValue.
void printAsOperand (raw_ostream &OS, bool PrintType) const
virtual void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const =0
Print plain-text dump of this VPBlockBase to O, prefixing all lines with Indent.
void print (raw_ostream &O) const
Print plain-text dump of this VPlan to O.
void printSuccessors (raw_ostream &O, const Twine &Indent) const
Print the successors of this block to O, prefixing all lines with Indent.
LLVM_DUMP_METHOD void dump () const
Dump this VPBlockBase to dbgs().
Static Public Member Functions
static void deleteCFG (VPBlockBase *Entry)
Delete all blocks reachable from a given VPBlockBase, inclusive.
Protected Member Functions
VPBlockBase (const unsigned char SC, const std::string &N)
Friends
class VPBlockUtils
Detailed Description
VPBlockBase is the building block of the Hierarchical Control-Flow Graph.
A VPBlockBase can be either a VPBasicBlock or a VPRegionBlock.
Definition at line 422 of file VPlan.h.
Member Typedef Documentation
VPBlocksTy
using llvm::VPBlockBase::VPBlocksTy = SmallVectorImpl<VPBlockBase *>
Definition at line 481 of file VPlan.h.
VPBlockTy
using llvm::VPBlockBase::VPBlockTy = enum { VPBasicBlockSC, VPRegionBlockSC }
An enumeration for keeping track of the concrete subclass of VPBlockBase that are actually instantiated.
Values of this enumeration are kept in the SubclassID field of the VPBlockBase objects. They are used for concrete type identification.
Definition at line 479 of file VPlan.h.
Constructor & Destructor Documentation
VPBlockBase()
llvm::VPBlockBase::VPBlockBase (const unsigned char SC, const std::string & N) inline protected
Definition at line 471 of file VPlan.h.
~VPBlockBase()
virtual llvm::VPBlockBase::~VPBlockBase () virtual default
Member Function Documentation
clearPredecessors()
void llvm::VPBlockBase::clearPredecessors () inline
Remove all the predecessor of this block.
Definition at line 615 of file VPlan.h.
References llvm::SmallVectorImpl< T >::clear().
clearSuccessors()
void llvm::VPBlockBase::clearSuccessors () inline
Remove all the successors of this block.
Definition at line 618 of file VPlan.h.
References llvm::SmallVectorImpl< T >::clear().
deleteCFG()
void VPBlockBase::deleteCFG (VPBlockBase * Entry) static
Delete all blocks reachable from a given VPBlockBase, inclusive.
Definition at line 203 of file VPlan.cpp.
References llvm::Block, llvm::to_vector(), and llvm::vp_depth_first_shallow().
Referenced by llvm::VPlan::~VPlan(), and llvm::VPRegionBlock::~VPRegionBlock().
dropAllReferences()
virtual void llvm::VPBlockBase::dropAllReferences (VPValue * NewValue) pure virtual
Replace all operands of VPUsers in the block with NewValue and also replaces all uses of VPValues defined in the block with NewValue.
Implemented in llvm::VPBasicBlock, and llvm::VPRegionBlock.
dump()
LLVM_DUMP_METHOD void llvm::VPBlockBase::dump () const inline
Dump this VPBlockBase to dbgs().
Definition at line 663 of file VPlan.h.
References llvm::dbgs(), and print().
execute()
virtual void llvm::VPBlockBase::execute (VPTransformState * State) pure virtual
The method which generates the output IR that correspond to this VPBlockBase, thereby "executing" the VPlan.
Implemented in llvm::VPBasicBlock, and llvm::VPRegionBlock.
getEnclosingBlockWithPredecessors()
VPBlockBase * VPBlockBase::getEnclosingBlockWithPredecessors ()
Returns
the closest enclosing block starting from "this", which has predecessors.
the root enclosing block if all enclosing blocks have no predecessors.
Definition at line 195 of file VPlan.cpp.
References assert(), getEnclosingBlockWithPredecessors(), and llvm::VPRegionBlock::getEntry().
Referenced by getEnclosingBlockWithPredecessors(), getHierarchicalPredecessors(), and getSingleHierarchicalPredecessor().
getEnclosingBlockWithSuccessors()
VPBlockBase * VPBlockBase::getEnclosingBlockWithSuccessors ()
An Enclosing Block of a block B is any block containing B, including B itself.
Returns
the closest enclosing block starting from "this", which has successors.
the root enclosing block if all enclosing blocks have no successors.
Definition at line 187 of file VPlan.cpp.
References assert(), getEnclosingBlockWithSuccessors(), and llvm::VPRegionBlock::getExiting().
Referenced by getEnclosingBlockWithSuccessors(), getHierarchicalSuccessors(), and getSingleHierarchicalSuccessor().
getEntryBasicBlock() [1/2]
VPBasicBlock * VPBlockBase::getEntryBasicBlock ()
Definition at line 158 of file VPlan.cpp.
References llvm::Block, and llvm::RegionBase< Tr >::getEntry().
getEntryBasicBlock() [2/2]
const VPBasicBlock * VPBlockBase::getEntryBasicBlock () const
Returns
the VPBasicBlock that is the entry of this VPBlockBase, recursively, if the latter is a VPRegionBlock. Otherwise, if this VPBlockBase is a VPBasicBlock, it is returned.
the VPBasicBlock that is the entry of Block, possibly indirectly.
Definition at line 151 of file VPlan.cpp.
References llvm::Block, and llvm::RegionBase< Tr >::getEntry().
Referenced by addCanonicalIVRecipes(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::VPlanTransforms::clearReductionWrapFlags(), llvm::VPRecipeBuilder::createHeaderMask(), createScalarIVSteps(), llvm::LoopVectorizationPlanner::executePlan(), llvm::InnerLoopVectorizer::fixVectorizedLoop(), llvm::VPlan::getCanonicalIV(), llvm::LoopVectorizePass::processLoop(), sinkScalarOperands(), and verifyPhiRecipes().
getExitingBasicBlock() [1/2]
VPBasicBlock * VPBlockBase::getExitingBasicBlock ()
Definition at line 180 of file VPlan.cpp.
References llvm::Block.
getExitingBasicBlock() [2/2]
const VPBasicBlock * VPBlockBase::getExitingBasicBlock () const
Returns
the VPBasicBlock that is the exiting this VPBlockBase, recursively, if the latter is a VPRegionBlock. Otherwise, if this VPBlockBase is a VPBasicBlock, it is returned.
the VPBasicBlock that is the exit of Block, possibly indirectly.
Definition at line 173 of file VPlan.cpp.
References llvm::Block.
Referenced by addCanonicalIVRecipes(), addVPLaneMaskPhiAndUpdateExitBranch(), llvm::VPlan::execute(), llvm::VPBasicBlock::execute(), llvm::InnerLoopVectorizer::fixVectorizedLoop(), llvm::VPRegionBlock::getPreheaderVPBB(), llvm::VPlanTransforms::optimizeForVFAndUF(), and sinkScalarOperands().
getHierarchicalPredecessors()
const VPBlocksTy & llvm::VPBlockBase::getHierarchicalPredecessors () inline
Returns
the predecessors either attached directly to this VPBlockBase or, if this VPBlockBase is the entry block of a VPRegionBlock and has no predecessors of its own, search recursively for the first enclosing VPRegionBlock that has predecessors and return them. If no such VPRegionBlock exists, return the (empty) predecessors of the topmost VPBlockBase reached.
Definition at line 575 of file VPlan.h.
References getEnclosingBlockWithPredecessors(), and getPredecessors().
getHierarchicalSuccessors()
const VPBlocksTy & llvm::VPBlockBase::getHierarchicalSuccessors () inline
Returns
the successors either attached directly to this VPBlockBase or, if this VPBlockBase is the exit block of a VPRegionBlock and has no successors of its own, search recursively for the first enclosing VPRegionBlock that has successors and return them. If no such VPRegionBlock exists, return the (empty) successors of the topmost VPBlockBase reached.
Definition at line 559 of file VPlan.h.
References getEnclosingBlockWithSuccessors(), and getSuccessors().
getName()
const std::string & llvm::VPBlockBase::getName () const inline
Definition at line 485 of file VPlan.h.
References Name.
Referenced by printAsOperand().
getNumPredecessors()
size_t llvm::VPBlockBase::getNumPredecessors () const inline
Definition at line 540 of file VPlan.h.
References llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::VPlan::VPlan().
getNumSuccessors()
size_t llvm::VPBlockBase::getNumSuccessors () const inline
Definition at line 539 of file VPlan.h.
References llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::VPLiveOut::fixPhi(), hasConditionalTerminator(), verifyRegion(), and llvm::VPlan::VPlan().
getParent() [1/2]
VPRegionBlock * llvm::VPBlockBase::getParent () inline
Definition at line 494 of file VPlan.h.
Referenced by addReplicateRegions(), llvm::VPBlockUtils::connectBlocks(), llvm::VPBasicBlock::execute(), llvm::VPBlockUtils::insertBlockAfter(), llvm::VPBlockUtils::insertTwoBlocksAfter(), isHeaderVPBB(), llvm::InnerLoopVectorizer::scalarizeInstruction(), setOneSuccessor(), llvm::VPlanVerifier::verifyHierarchicalCFG(), verifyPhiRecipes(), and verifyVPBasicBlock().
getParent() [2/2]
const VPRegionBlock * llvm::VPBlockBase::getParent () const inline
Definition at line 495 of file VPlan.h.
getPlan() [1/2]
VPlan * VPBlockBase::getPlan ()
Returns
A pointer to the plan containing the current block.
Definition at line 146 of file VPlan.cpp.
References getPlanEntry().
Referenced by llvm::VPWidenPointerInductionRecipe::execute(), and print().
getPlan() [2/2]
const VPlan * VPBlockBase::getPlan () const
Definition at line 148 of file VPlan.cpp.
References getPlanEntry().
getPredecessors() [1/2]
VPBlocksTy & llvm::VPBlockBase::getPredecessors () inline
Definition at line 525 of file VPlan.h.
getPredecessors() [2/2]
const VPBlocksTy & llvm::VPBlockBase::getPredecessors () const inline
Definition at line 524 of file VPlan.h.
Referenced by getHierarchicalPredecessors(), llvm::VPBlockUtils::insertBlockAfter(), and llvm::VPRegionBlock::setEntry().
getSingleHierarchicalPredecessor()
VPBlockBase * llvm::VPBlockBase::getSingleHierarchicalPredecessor () inline
Returns
the hierarchical predecessor of this VPBlockBase if it has a single hierarchical predecessor. Otherwise return a null pointer.
Definition at line 581 of file VPlan.h.
References getEnclosingBlockWithPredecessors(), and getSinglePredecessor().
getSingleHierarchicalSuccessor()
VPBlockBase * llvm::VPBlockBase::getSingleHierarchicalSuccessor () inline
Returns
the hierarchical successor of this VPBlockBase if it has a single hierarchical successor. Otherwise return a null pointer.
Definition at line 565 of file VPlan.h.
References getEnclosingBlockWithSuccessors(), and getSingleSuccessor().
Referenced by llvm::VPBasicBlock::execute().
getSinglePredecessor()
VPBlockBase * llvm::VPBlockBase::getSinglePredecessor () const inline
Returns
the predecessor of this VPBlockBase if it has a single predecessor. Otherwise return a null pointer.
Definition at line 535 of file VPlan.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by addVPLaneMaskPhiAndUpdateExitBranch(), llvm::VPTransformState::get(), llvm::VPRegionBlock::getPreheaderVPBB(), and getSingleHierarchicalPredecessor().
getSingleSuccessor()
VPBlockBase * llvm::VPBlockBase::getSingleSuccessor () const inline
Returns
the successor of this VPBlockBase if it has a single successor. Otherwise return a null pointer.
Definition at line 529 of file VPlan.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::VPBasicBlock::execute(), llvm::LoopVectorizationPlanner::executePlan(), llvm::VPLiveOut::fixPhi(), llvm::VPlan::getCanonicalIV(), getSingleHierarchicalSuccessor(), mergeReplicateRegionsIntoSuccessors(), and sinkScalarOperands().
getSuccessors() [1/2]
VPBlocksTy & llvm::VPBlockBase::getSuccessors () inline
Definition at line 520 of file VPlan.h.
getSuccessors() [2/2]
const VPBlocksTy & llvm::VPBlockBase::getSuccessors () const inline
Definition at line 519 of file VPlan.h.
Referenced by getHierarchicalSuccessors(), llvm::VPBlockUtils::insertBlockAfter(), llvm::VPBlockUtils::insertTwoBlocksAfter(), llvm::VPRegionBlock::setExiting(), sinkScalarOperands(), and llvm::VPRegionBlock::VPRegionBlock().
getVPBlockID()
unsigned llvm::VPBlockBase::getVPBlockID () const inline
Returns
an ID for the concrete type of this object. This is used to implement the classof checks. This should not be used for any other purpose, as the values may change as LLVM evolves.
Definition at line 492 of file VPlan.h.
isLegalToHoistInto()
bool llvm::VPBlockBase::isLegalToHoistInto () inline
Return true if it is legal to hoist instructions into this block.
Definition at line 628 of file VPlan.h.
print() [1/2]
void llvm::VPBlockBase::print (raw_ostream & O) const inline
Print plain-text dump of this VPlan to O.
Definition at line 653 of file VPlan.h.
References getPlan(), and print().
print() [2/2]
virtual void llvm::VPBlockBase::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const pure virtual
Print plain-text dump of this VPBlockBase to O, prefixing all lines with Indent.
SlotTracker is used to print unnamed VPValue's using consequtive numbers.
Note that the numbering is applied to the whole VPlan, so printing individual blocks is consistent with the whole VPlan printing.
Implemented in llvm::VPBasicBlock, llvm::VPRegionBlock, llvm::VPBasicBlock, and llvm::VPRegionBlock.
Referenced by dump(), and print().
printAsOperand()
void llvm::VPBlockBase::printAsOperand (raw_ostream & OS, bool PrintType) const inline
Definition at line 639 of file VPlan.h.
References getName(), and OS.
printSuccessors()
void VPBlockBase::printSuccessors (raw_ostream & O, const Twine & Indent) const
Print the successors of this block to O, prefixing all lines with Indent.
Definition at line 592 of file VPlan.cpp.
setName()
void llvm::VPBlockBase::setName (const Twine & newName) inline
Definition at line 487 of file VPlan.h.
References Name, and llvm::Twine::str().
setOneSuccessor()
void llvm::VPBlockBase::setOneSuccessor (VPBlockBase * Successor) inline
Set a given VPBlockBase Successor as the single successor of this VPBlockBase.
This VPBlockBase is not added as predecessor of Successor. This VPBlockBase must have no successors.
Definition at line 588 of file VPlan.h.
References assert(), llvm::SmallVectorBase< Size_T >::empty(), getParent(), and llvm::Successor.
setParent()
void llvm::VPBlockBase::setParent (VPRegionBlock * P) inline
Definition at line 505 of file VPlan.h.
References P.
Referenced by llvm::VPBlockUtils::insertBlockAfter(), llvm::VPBlockUtils::insertTwoBlocksAfter(), llvm::VPRegionBlock::setEntry(), llvm::VPRegionBlock::setExiting(), and llvm::VPRegionBlock::VPRegionBlock().
setPlan()
void VPBlockBase::setPlan (VPlan * ParentPlan)
Sets the pointer of the plan containing the block.
The block must be the entry block into the VPlan.
Definition at line 165 of file VPlan.cpp.
References assert(), llvm::VPlan::getEntry(), and llvm::VPlan::getPreheader().
Referenced by llvm::VPlan::VPlan().
setPredecessors()
void llvm::VPBlockBase::setPredecessors (ArrayRef< VPBlockBase * > NewPreds) inline
Set each VPBasicBlock in NewPreds as predecessor of this VPBlockBase.
This VPBlockBase must have no predecessors. This VPBlockBase is not added as successor of any VPBasicBlock in NewPreds.
Definition at line 608 of file VPlan.h.
References assert(), and llvm::SmallVectorBase< Size_T >::empty().
Referenced by llvm::VPBlockUtils::insertTwoBlocksAfter().
setTwoSuccessors()
void llvm::VPBlockBase::setTwoSuccessors (VPBlockBase * IfTrue, VPBlockBase * IfFalse) inline
Set two given VPBlockBases IfTrue and IfFalse to be the two successors of this VPBlockBase.
This VPBlockBase is not added as predecessor of IfTrue or IfFalse. This VPBlockBase must have no successors.
Definition at line 599 of file VPlan.h.
References assert(), and llvm::SmallVectorBase< Size_T >::empty().
Referenced by llvm::VPBlockUtils::insertTwoBlocksAfter().
successors()
iterator_range< VPBlockBase ** > llvm::VPBlockBase::successors () inline
Definition at line 522 of file VPlan.h.
Referenced by llvm::VPBlockUtils::insertBlockAfter().
Friends And Related Function Documentation
VPBlockUtils
friend class VPBlockUtils friend
Definition at line 423 of file VPlan.h.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp