LLVM: llvm::SmallVectorTemplateCommon< T, typename > Class Template Reference
llvm::SmallVectorTemplateCommon< T, typename > Class Template Reference
This is the part of SmallVectorTemplateBase which does not depend on whether the type T is a POD.
#include "llvm/ADT/SmallVector.h"
Inherits llvm::SmallVectorBase< SmallVectorSizeType< T > >.
Inherited by llvm::SmallVectorTemplateBase< std::pair< ValueType, SUList > >, llvm::SmallVectorTemplateBase< Function * >, llvm::SmallVectorTemplateBase< AddressRange >, llvm::SmallVectorTemplateBase< AddressRangeValuePair >, llvm::SmallVectorTemplateBase< std::unique_ptr< DWARFUnit > >, llvm::SmallVectorTemplateBase< BasicBlock * >, llvm::SmallVectorTemplateBase< llvm::DomTreeNodeBase * >, llvm::SmallVectorTemplateBase< BlockT * >, llvm::SmallVectorTemplateBase< BoUpSLP::EdgeInfo >, llvm::SmallVectorTemplateBase< llvm::MCFixup >, llvm::SmallVectorTemplateBase< char >, llvm::SmallVectorTemplateBase< Edge >, llvm::SmallVectorTemplateBase< llvm::cl::parser::OptionInfo >, llvm::SmallVectorTemplateBase< std::pair< const MachineFunction *, Register > >, llvm::SmallVectorTemplateBase< std::pair< const T *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateBase< std::pair< SPIRV::SpecialTypeDescriptor, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateBase< std::pair< KeyT, ValueT > >, llvm::SmallVectorTemplateBase< std::tuple< NodeRef, ChildItTy, ChildItTy > >, llvm::SmallVectorTemplateBase< llvm::AAPointerInfo::Access >, llvm::SmallVectorTemplateBase< Slice >, llvm::SmallVectorTemplateBase< VariableGEPIndex >, llvm::SmallVectorTemplateBase< int >, llvm::SmallVectorTemplateBase< llvm::PointerUnion< llvm::Value *, const TreeEntry * > >, llvm::SmallVectorTemplateBase< llvm::Value * >, llvm::SmallVectorTemplateBase< llvm::Instruction * >, llvm::SmallVectorTemplateBase< const llvm::MachineInstr * >, llvm::SmallVectorTemplateBase< std::pair< const llvm::Function *, const llvm::DISubprogram * > >, llvm::SmallVectorTemplateBase< std::pair< const llvm::Instruction *, bool > >, llvm::SmallVectorTemplateBase< std::pair< const llvm::Instruction *, llvm::WeakVH > >, llvm::SmallVectorTemplateBase< std::pair< const llvm::DILocalVariable *, unsigned > >, llvm::SmallVectorTemplateBase< VarLocInfo >, llvm::SmallVectorTemplateBase< llvm::SUnit * >, llvm::SmallVectorTemplateBase< LiveDebugValues::ValueIDNum >, llvm::SmallVectorTemplateBase< llvm::MachineOperand >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::SmallVector > >, llvm::SmallVectorTemplateBase< DebugPHIRecord >, llvm::SmallVectorTemplateBase< ValueIDNum >, llvm::SmallVectorTemplateBase< unsigned >, llvm::SmallVectorTemplateBase< llvm::Register >, llvm::SmallVectorTemplateBase< std::pair< const llvm::MachineOperand *, unsigned > >, llvm::SmallVectorTemplateBase< std::pair< llvm::DebugVariable, LiveDebugValues::DbgValue > >, llvm::SmallVectorTemplateBase< std::pair< StringRef, size_t > >, llvm::SmallVectorTemplateBase< MachineInstr * >, llvm::SmallVectorTemplateBase< std::pair< BlockFrequency, unsigned > >, llvm::SmallVectorTemplateBase< TransferTracker::Transfer >, llvm::SmallVectorTemplateBase< ResolvedDbgOp >, llvm::SmallVectorTemplateBase< DbgOp >, llvm::SmallVectorTemplateBase< uint32_t >, llvm::SmallVectorTemplateBase< DepTy >, llvm::SmallVectorTemplateBase< void(*)(llvm::Function &F, llvm::AnalysisManager &AM, llvm::AAResults &llvm::AAResults) >, llvm::SmallVectorTemplateBase< RangeTy >, llvm::SmallVectorTemplateBase< AAQueryInfo::LocPair >, llvm::SmallVectorTemplateBase< llvm::ForwardedRegister >, llvm::SmallVectorTemplateBase< MILOHDirective >, llvm::SmallVectorTemplateBase< std::pair< unsigned, llvm::MCSymbol * > >, llvm::SmallVectorTemplateBase< llvm::MachineInstr * >, llvm::SmallVectorTemplateBase< llvm::BasicBlockInfo >, llvm::SmallVectorTemplateBase< FCmpLibcallsList >, llvm::SmallVectorTemplateBase< std::pair< StringRef, HashData > >, llvm::SmallVectorTemplateBase< llvm::MemoryLocation >, llvm::SmallVectorTemplateBase< uint8_t >, llvm::SmallVectorTemplateBase< uint16_t >, llvm::SmallVectorTemplateBase< AnalysisID >, llvm::SmallVectorTemplateBase< std::pair< uint16_t, Form > >, llvm::SmallVectorTemplateBase< std::pair< llvm::StringRef, llvm::ArchYAML::Archive::Child::Field > >, llvm::SmallVectorTemplateBase< FreeList * >, llvm::SmallVectorTemplateBase< std::pair< unsigned, llvm::AsmPrinter::MBBSectionRange > >, llvm::SmallVectorTemplateBase< std::pair< const llvm::MCSymbol *, GOTEquivUsePair > >, llvm::SmallVectorTemplateBase< llvm::AsmPrinter::XRayFunctionEntry >, llvm::SmallVectorTemplateBase< std::pair< MCSection *, ConstantPool > >, llvm::SmallVectorTemplateBase< llvm::AssumptionCache::ResultElem >, llvm::SmallVectorTemplateBase< llvm::Attribute >, llvm::SmallVectorTemplateBase< llvm::Function * >, llvm::SmallVectorTemplateBase< llvm::SmallVector * >, llvm::SmallVectorTemplateBase< std::pair< llvm::Use *, llvm::Value * > >, llvm::SmallVectorTemplateBase< std::pair< llvm::Value *, llvm::PointerIntPair< llvm::Value *, 1, bool > > >, llvm::SmallVectorTemplateBase< llvm::WeakVH >, llvm::SmallVectorTemplateBase< llvm::BasicBlock * >, llvm::SmallVectorTemplateBase< llvm::AbstractAttribute * >, llvm::SmallVectorTemplateBase< llvm::Type * >, llvm::SmallVectorTemplateBase< llvm::BitCodeAbbrevOp >, llvm::SmallVectorTemplateBase< BitValue >, llvm::SmallVectorTemplateBase< BitWord >, llvm::SmallVectorTemplateBase< Block >, llvm::SmallVectorTemplateBase< Weight >, llvm::SmallVectorTemplateBase< std::pair< BlockNode, BlockMass > >, llvm::SmallVectorTemplateBase< BlockNode >, llvm::SmallVectorTemplateBase< BlockMass >, llvm::SmallVectorTemplateBase< void * >, llvm::SmallVectorTemplateBase< std::pair< void *, size_t > >, llvm::SmallVectorTemplateBase< llvm::CCValAssign >, llvm::SmallVectorTemplateBase< llvm::ISD::ArgFlagsTy >, llvm::SmallVectorTemplateBase< ByValInfo >, llvm::SmallVectorTemplateBase< llvm::LazyCallGraph::RefSCC * >, llvm::SmallVectorTemplateBase< llvm::LazyCallGraph::SCC * >, llvm::SmallVectorTemplateBase< std::pair< llvm::Value *, llvm::WeakTrackingVH > >, llvm::SmallVectorTemplateBase< ConstantPoolEntry >, llvm::SmallVectorTemplateBase< AttributeItem >, llvm::SmallVectorTemplateBase< Loop * >, llvm::SmallVectorTemplateBase< LoopTripCountTy >, llvm::SmallVectorTemplateBase< LoopCacheCostTy >, llvm::SmallVectorTemplateBase< llvm::CallLowering::ArgInfo >, llvm::SmallVectorTemplateBase< std::pair< MDString *, MethodsList > >, llvm::SmallVectorTemplateBase< Value * >, llvm::SmallVectorTemplateBase< llvm::AllocaInst * >, llvm::SmallVectorTemplateBase< llvm::unique_function< bool(llvm::StringRef)> >, llvm::SmallVectorTemplateBase< llvm::unique_function< void(llvm::StringRef)> >, llvm::SmallVectorTemplateBase< FileInfo >, llvm::SmallVectorTemplateBase< CVGlobalVariable >, llvm::SmallVectorTemplateBase< const llvm::DIDerivedType * >, llvm::SmallVectorTemplateBase< std::pair< const llvm::Function *, std::unique_ptr< FunctionInfo > > >, llvm::SmallVectorTemplateBase< const llvm::DISubprogram * >, llvm::SmallVectorTemplateBase< const llvm::DICompositeType * >, llvm::SmallVectorTemplateBase< const llvm::DILocation * >, llvm::SmallVectorTemplateBase< llvm::codeview::TypeIndex >, llvm::SmallVectorTemplateBase< LocalVariable >, llvm::SmallVectorTemplateBase< LexicalBlock * >, llvm::SmallVectorTemplateBase< std::pair< llvm::CodeViewDebug::LocalVarDef, llvm::SmallVector< std::pair< const llvm::MCSymbol *, const llvm::MCSymbol * >, 1 > > >, llvm::SmallVectorTemplateBase< std::pair< GlobalVariable *, ConstCandVecType > >, llvm::SmallVectorTemplateBase< consthoist::ConstantInfo >, llvm::SmallVectorTemplateBase< std::pair< GlobalVariable *, ConstInfoVecType > >, llvm::SmallVectorTemplateBase< std::pair< llvm::Instruction *, llvm::Instruction * > >, llvm::SmallVectorTemplateBase< llvm::SmallVector< Entry, 8 > >, llvm::SmallVectorTemplateBase< bool >, llvm::SmallVectorTemplateBase< llvm::SDNode * >, llvm::SmallVectorTemplateBase< EdgeType * >, llvm::SmallVectorTemplateBase< llvm::ValueAsMetadata * >, llvm::SmallVectorTemplateBase< llvm::TypedTrackingMDRef >, llvm::SmallVectorTemplateBase< llvm::DISubprogram * >, llvm::SmallVectorTemplateBase< llvm::Metadata * >, llvm::SmallVectorTemplateBase< std::pair< llvm::MDNode *, llvm::SetVector< llvm::Metadata * > > >, llvm::SmallVectorTemplateBase< llvm::DIEAbbrevData >, llvm::SmallVectorTemplateBase< llvm::DILineInfo >, llvm::SmallVectorTemplateBase< TypeUnitMetaInfo >, llvm::SmallVectorTemplateBase< AttributeSpec >, llvm::SmallVectorTemplateBase< llvm::DWARFFormValue >, llvm::SmallVectorTemplateBase< LocationList >, llvm::SmallVectorTemplateBase< llvm::DWARFLocationEntry >, llvm::SmallVectorTemplateBase< Entry >, llvm::SmallVectorTemplateBase< llvm::DWARFDebugNames::NameIndex >, llvm::SmallVectorTemplateBase< uint64_t >, llvm::SmallVectorTemplateBase< Encoding >, llvm::SmallVectorTemplateBase< CompUnitEntry >, llvm::SmallVectorTemplateBase< TypeUnitEntry >, llvm::SmallVectorTemplateBase< AddressEntry >, llvm::SmallVectorTemplateBase< SymTableEntry >, llvm::SmallVectorTemplateBase< std::pair< uint32_t, llvm::SmallVector< uint32_t, 0 > > >, llvm::SmallVectorTemplateBase< llvm::dxbc::PSV::v2::ResourceBindInfo >, llvm::SmallVectorTemplateBase< llvm::DXContainerYAML::SignatureElement >, llvm::SmallVectorTemplateBase< llvm::yaml::Hex32 >, llvm::SmallVectorTemplateBase< llvm::DXContainerYAML::SignatureParameter >, llvm::SmallVectorTemplateBase< unsigned char >, llvm::SmallVectorTemplateBase< LayoutAlignElem >, llvm::SmallVectorTemplateBase< PointerAlignElem >, llvm::SmallVectorTemplateBase< std::pair< InlinedEntity, const MachineInstr * > >, llvm::SmallVectorTemplateBase< std::pair< InlinedEntity, Entries > >, llvm::SmallVectorTemplateBase< llvm::DbgValueLocEntry >, llvm::SmallVectorTemplateBase< int64_t >, llvm::SmallVectorTemplateBase< llvm::DICompileUnit * >, llvm::SmallVectorTemplateBase< llvm::DIGlobalVariableExpression * >, llvm::SmallVectorTemplateBase< llvm::DIType * >, llvm::SmallVectorTemplateBase< llvm::DIScope * >, llvm::SmallVectorTemplateBase< llvm::DbgValueLoc >, llvm::SmallVectorTemplateBase< llvm::DebugLocStream::List >, llvm::SmallVectorTemplateBase< llvm::DebugLocStream::Entry >, llvm::SmallVectorTemplateBase< std::string >, llvm::SmallVectorTemplateBase< llvm::Init * >, llvm::SmallVectorTemplateBase< llvm::DiagnosticInfoOptimizationBase::Argument >, llvm::SmallVectorTemplateBase< NodeType * >, llvm::SmallVectorTemplateBase< llvm::DomTreeNodeBase >, llvm::SmallVectorTemplateBase< DominatorTree::UpdateType >, llvm::SmallVectorTemplateBase< NodeT * >, llvm::SmallVectorTemplateBase< llvm::RangeSpan >, llvm::SmallVectorTemplateBase< const MDNode * >, llvm::SmallVectorTemplateBase< std::pair< const llvm::MDNode *, llvm::DwarfCompileUnit * > >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::DbgEntity > >, llvm::SmallVectorTemplateBase< std::pair< std::unique_ptr< llvm::DwarfTypeUnit >, const llvm::DICompositeType * > >, llvm::SmallVectorTemplateBase< llvm::DwarfExpression::Register >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::DwarfCompileUnit > >, llvm::SmallVectorTemplateBase< llvm::RangeSpanList >, llvm::SmallVectorTemplateBase< llvm::DbgVariable * >, llvm::SmallVectorTemplateBase< llvm::SmallVector< unsigned, 8 > >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::GlobalVariable > >, llvm::SmallVectorTemplateBase< MutableValue >, llvm::SmallVectorTemplateBase< llvm::DomainValue * >, llvm::SmallVectorTemplateBase< LiveRegsDVInfo >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::Module > >, llvm::SmallVectorTemplateBase< llvm::GlobalValue * >, llvm::SmallVectorTemplateBase< llvm::ISD::InputArg >, llvm::SmallVectorTemplateBase< std::pair< llvm::Instruction *, llvm::ConstantRange > >, llvm::SmallVectorTemplateBase< std::pair< llvm::Instruction *, llvm::Value * > >, llvm::SmallVectorTemplateBase< T * >, llvm::SmallVectorTemplateBase< llvm::FunctionLoweringInfo::LiveOutInfo >, llvm::SmallVectorTemplateBase< llvm::BBClusterInfo >, llvm::SmallVectorTemplateBase< llvm::SmallVector< unsigned > >, llvm::SmallVectorTemplateBase< llvm::DebugVariable >, llvm::SmallVectorTemplateBase< llvm::VarLocInfo >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::GCStrategy > >, llvm::SmallVectorTemplateBase< GCNSchedStageID >, llvm::SmallVectorTemplateBase< std::pair< llvm::MachineInstrBundleIterator, llvm::MachineInstrBundleIterator > >, llvm::SmallVectorTemplateBase< llvm::DenseMap >, llvm::SmallVectorTemplateBase< llvm::GCNRegPressure >, llvm::SmallVectorTemplateBase< llvm::GCOVArc * >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::GCOVFunction > >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::GCOVBlock > >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::GCOVArc > >, llvm::SmallVectorTemplateBase< llvm::LLT >, llvm::SmallVectorTemplateBase< llvm::GISelChangeObserver * >, llvm::SmallVectorTemplateBase< std::pair< llvm::Value *, llvm::Value * > >, llvm::SmallVectorTemplateBase< std::pair< llvm::Instruction *, unsigned > >, llvm::SmallVectorTemplateBase< const CycleT * >, llvm::SmallVectorTemplateBase< SubGlobPattern >, llvm::SmallVectorTemplateBase< llvm::GlobPattern::SubGlobPattern::Bracket >, llvm::SmallVectorTemplateBase< llvm::cfg::Update< NodePtr > >, llvm::SmallVectorTemplateBase< NodePtr >, llvm::SmallVectorTemplateBase< MCOperand >, llvm::SmallVectorTemplateBase< HexagonInstr >, llvm::SmallVectorTemplateBase< llvm::HexagonInstr * >, llvm::SmallVectorTemplateBase< NodeTy * >, llvm::SmallVectorTemplateBase< llvm::cfg::Update< llvm::BasicBlock * > >, llvm::SmallVectorTemplateBase< std::pair< unsigned, llvm::MDNode * > >, llvm::SmallVectorTemplateBase< std::pair< const llvm::PHINode *, llvm::SmallVector< llvm::MachineInstr *, 1 > > >, llvm::SmallVectorTemplateBase< InlineGraphNode * >, llvm::SmallVectorTemplateBase< uintptr_t >, llvm::SmallVectorTemplateBase< Meta >, llvm::SmallVectorTemplateBase< const llvm::SCEV * >, llvm::SmallVectorTemplateBase< const llvm::Instruction * >, llvm::SmallVectorTemplateBase< Instruction * >, llvm::SmallVectorTemplateBase< const char * >, llvm::SmallVectorTemplateBase< llvm::WeakTrackingVH >, llvm::SmallVectorTemplateBase< llvm::CallBase * >, llvm::SmallVectorTemplateBase< std::pair< const llvm::RecurrenceDescriptor *, llvm::PHINode * > >, llvm::SmallVectorTemplateBase< std::pair< llvm::SlotIndex, llvm::SlotIndex > >, llvm::SmallVectorTemplateBase< llvm::TemporalProfTraceTy >, llvm::SmallVectorTemplateBase< std::pair< uint64_t, llvm::memprof::IndexedMemProfRecord > >, llvm::SmallVectorTemplateBase< std::pair< uint64_t, llvm::memprof::Frame > >, llvm::SmallVectorTemplateBase< std::function< void(MachineInstrBuilder &)> >, llvm::SmallVectorTemplateBase< llvm::InstructionBuildSteps >, llvm::SmallVectorTemplateBase< RegUnitInfo >, llvm::SmallVectorTemplateBase< BlockInterference >, llvm::SmallVectorTemplateBase< DataType >, llvm::SmallVectorTemplateBase< PointType >, llvm::SmallVectorTemplateBase< const DataType * >, llvm::SmallVectorTemplateBase< const llvm::Value * >, llvm::SmallVectorTemplateBase< ScopeContext >, llvm::SmallVectorTemplateBase< llvm::MCRegister >, llvm::SmallVectorTemplateBase< llvm::Loop * >, llvm::SmallVectorTemplateBase< llvm::MCSymbol * >, llvm::SmallVectorTemplateBase< llvm::SEHHandler >, llvm::SmallVectorTemplateBase< llvm::LazyCallGraph::Node * >, llvm::SmallVectorTemplateBase< std::pair< llvm::BasicBlock *, llvm::Value * > >, llvm::SmallVectorTemplateBase< SizeChangeStrategy >, llvm::SmallVectorTemplateBase< SizeAndActionsVec >, llvm::SmallVectorTemplateBase< llvm::LegalizeRule >, llvm::SmallVectorTemplateBase< std::pair< bool, llvm::StringRef > >, llvm::SmallVectorTemplateBase< llvm::LexicalScope * >, llvm::SmallVectorTemplateBase< InsnRange >, llvm::SmallVectorTemplateBase< const llvm::LiveInterval * >, llvm::SmallVectorTemplateBase< llvm::LiveInterval * >, llvm::SmallVectorTemplateBase< llvm::SlotIndex >, llvm::SmallVectorTemplateBase< const uint32_t * >, llvm::SmallVectorTemplateBase< std::pair< unsigned, unsigned > >, llvm::SmallVectorTemplateBase< llvm::LiveRange * >, llvm::SmallVectorTemplateBase< MCPhysReg >, llvm::SmallVectorTemplateBase< Segment >, llvm::SmallVectorTemplateBase< VNInfo * >, llvm::SmallVectorTemplateBase< LiveOutPair >, llvm::SmallVectorTemplateBase< LiveInBlock >, llvm::SmallVectorTemplateBase< llvm::LiveRange::Segment >, llvm::SmallVectorTemplateBase< IndexMaskPair >, llvm::SmallVectorTemplateBase< llvm::LiveVariables::VarInfo >, llvm::SmallVectorTemplateBase< llvm::GStore * >, llvm::SmallVectorTemplateBase< std::pair< llvm::MachineInstr *, unsigned > >, llvm::SmallVectorTemplateBase< llvm::StoreInst * >, llvm::SmallVectorTemplateBase< MBBInfo >, llvm::SmallVectorTemplateBase< std::pair< llvm::Instruction *, uint64_t > >, llvm::SmallVectorTemplateBase< std::pair< PHINode *, RecurrenceDescriptor > >, llvm::SmallVectorTemplateBase< std::pair< PHINode *, InductionDescriptor > >, llvm::SmallVectorTemplateBase< VPlanPtr >, llvm::SmallVectorTemplateBase< llvm::VectorizationFactor >, llvm::SmallVectorTemplateBase< RuntimePointerCheck >, llvm::SmallVectorTemplateBase< llvm::DebugLoc >, llvm::SmallVectorTemplateBase< llvm::MCSection * >, llvm::SmallVectorTemplateBase< llvm::AsmToken >, llvm::SmallVectorTemplateBase< llvm::MCAsmParser::MCPendingError >, llvm::SmallVectorTemplateBase< std::pair< const llvm::MCSymbol *, const llvm::MCSymbol * > >, llvm::SmallVectorTemplateBase< std::pair< std::string, std::string > >, llvm::SmallVectorTemplateBase< llvm::MCDwarfFile >, llvm::SmallVectorTemplateBase< llvm::MCELFStreamer::AttributeItem >, llvm::SmallVectorTemplateBase< llvm::MCDataFragment * >, llvm::SmallVectorTemplateBase< llvm::MCOperand >, llvm::SmallVectorTemplateBase< llvm::object::OwningBinary< llvm::object::Archive > >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::MemoryBuffer > >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::object::ObjectFile > >, llvm::SmallVectorTemplateBase< llvm::MCLOHDirective >, llvm::SmallVectorTemplateBase< std::pair< MCSection *, MCDwarfLineEntryCollection > >, llvm::SmallVectorTemplateBase< PendingMCFixup >, llvm::SmallVectorTemplateBase< std::pair< unsigned, llvm::MCFragment * > >, llvm::SmallVectorTemplateBase< PendingLabel >, llvm::SmallVectorTemplateBase< std::pair< size_t, llvm::MCSection * > >, llvm::SmallVectorTemplateBase< std::pair< MCSectionSubPair, MCSectionSubPair > >, llvm::SmallVectorTemplateBase< llvm::MDAttachments::Attachment >, llvm::SmallVectorTemplateBase< llvm::StringRef >, llvm::SmallVectorTemplateBase< Target >, llvm::SmallVectorTemplateBase< std::pair< llvm::MachO::ObjCIVarRecord, ValueT > >, llvm::SmallVectorTemplateBase< std::pair< llvm::StringRef, llvm::MachO::ObjCCategoryRecord * > >, llvm::SmallVectorTemplateBase< std::pair< llvm::MachO::GlobalRecord, ValueT > >, llvm::SmallVectorTemplateBase< std::pair< llvm::MachO::ObjCInterfaceRecord, ValueT > >, llvm::SmallVectorTemplateBase< std::pair< llvm::MachO::ObjCCategoryRecord, std::pair< llvm::StringRef, llvm::StringRef > > >, llvm::SmallVectorTemplateBase< llvm::MachineBasicBlock * >, llvm::SmallVectorTemplateBase< CriticalEdge >, llvm::SmallVectorTemplateBase< std::pair< int, int64_t > >, llvm::SmallVectorTemplateBase< VariableDbgInfo >, llvm::SmallVectorTemplateBase< llvm::MachineFunction::DebugSubstitution >, llvm::SmallVectorTemplateBase< llvm::unique_function< FuncTy > >, llvm::SmallVectorTemplateBase< std::pair< llvm::PointerUnion, llvm::MachineOperand * > >, llvm::SmallVectorTemplateBase< std::pair< unsigned, llvm::SmallVector< llvm::Register, 4 > > >, llvm::SmallVectorTemplateBase< LLT >, llvm::SmallVectorTemplateBase< llvm::MachineTraceMetrics::FixedBlockInfo >, llvm::SmallVectorTemplateBase< llvm::MachineTraceMetrics::TraceBlockInfo >, llvm::SmallVectorTemplateBase< llvm::MachineTraceMetrics::LiveInReg >, llvm::SmallVectorTemplateBase< llvm::MemoryDepChecker::Dependence >, llvm::SmallVectorTemplateBase< llvm::AssertingVH< llvm::MemoryPhi > >, llvm::SmallVectorTemplateBase< Inst >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::MipsOptionRecord > >, llvm::SmallVectorTemplateBase< const BlockT * >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::ScheduleHazardRecognizer > >, llvm::SmallVectorTemplateBase< llvm::OpenMPIRBuilder::FinalizationInfo >, llvm::SmallVectorTemplateBase< llvm::OpenMPIRBuilder::OutlineInfo >, llvm::SmallVectorTemplateBase< DeviceInfoTy >, llvm::SmallVectorTemplateBase< omp::OpenMPOffloadMappingFlags >, llvm::SmallVectorTemplateBase< Constant * >, llvm::SmallVectorTemplateBase< MapValuesArrayTy >, llvm::SmallVectorTemplateBase< std::pair< const llvm::Value *, std::pair< llvm::Value *, llvm::Value * > > >, llvm::SmallVectorTemplateBase< llvm::Pass * >, llvm::SmallVectorTemplateBase< llvm::PMDataManager * >, llvm::SmallVectorTemplateBase< llvm::ImmutablePass * >, llvm::SmallVectorTemplateBase< ParamType >, llvm::SmallVectorTemplateBase< llvm::AsmRewrite >, llvm::SmallVectorTemplateBase< std::function< void(llvm::PassManager &, llvm::OptimizationLevel)> >, llvm::SmallVectorTemplateBase< std::function< void(llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > &, llvm::OptimizationLevel)> >, llvm::SmallVectorTemplateBase< std::function< void(PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & > &, llvm::OptimizationLevel)> >, llvm::SmallVectorTemplateBase< std::function< void(llvm::AnalysisManager &)> >, llvm::SmallVectorTemplateBase< std::function< bool(llvm::StringRef, llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorTemplateBase< std::function< bool(llvm::PassManager &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorTemplateBase< std::function< bool(llvm::StringRef, PassManager< LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & > &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorTemplateBase< std::function< bool(llvm::StringRef, llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & > &, llvm::ArrayRef< llvm::PassBuilder::PipelineElement >)> >, llvm::SmallVectorTemplateBase< std::function< bool(llvm::StringRef Name, llvm::AAManager &AA)> >, llvm::SmallVectorTemplateBase< std::function< void(llvm::MachineFunctionAnalysisManager &)> >, llvm::SmallVectorTemplateBase< std::function< bool(llvm::StringRef, llvm::MachineFunctionPassManager &)> >, llvm::SmallVectorTemplateBase< InsertedPass >, llvm::SmallVectorTemplateBase< llvm::unique_function< BeforePassFunc > >, llvm::SmallVectorTemplateBase< llvm::unique_function< BeforeSkippedPassFunc > >, llvm::SmallVectorTemplateBase< llvm::unique_function< BeforeNonSkippedPassFunc > >, llvm::SmallVectorTemplateBase< llvm::unique_function< AfterPassFunc > >, llvm::SmallVectorTemplateBase< llvm::unique_function< AfterPassInvalidatedFunc > >, llvm::SmallVectorTemplateBase< llvm::unique_function< BeforeAnalysisFunc > >, llvm::SmallVectorTemplateBase< llvm::unique_function< AfterAnalysisFunc > >, llvm::SmallVectorTemplateBase< llvm::unique_function< AnalysisInvalidatedFunc > >, llvm::SmallVectorTemplateBase< llvm::unique_function< AnalysesClearedFunc > >, llvm::SmallVectorTemplateBase< DDGNode * >, llvm::SmallVectorTemplateBase< MemberTy >, llvm::SmallVectorTemplateBase< std::pair< unsigned, llvm::MapVector< llvm::MachineInstr *, llvm::MachineInstr * > > >, llvm::SmallVectorTemplateBase< llvm::AssertingVH< llvm::Function > >, llvm::SmallVectorTemplateBase< ValueInfo >, llvm::SmallVectorTemplateBase< llvm::PredicateBase * >, llvm::SmallVectorTemplateBase< PassRunDescriptor >, llvm::SmallVectorTemplateBase< llvm::SpillPlacement::BlockConstraint >, llvm::SmallVectorTemplateBase< GlobalSplitCandidate >, llvm::SmallVectorTemplateBase< RegInfo >, llvm::SmallVectorTemplateBase< TraversedMBBInfo >, llvm::SmallVectorTemplateBase< LiveRegsDefInfo >, llvm::SmallVectorTemplateBase< MBBDefsInfo >, llvm::SmallVectorTemplateBase< llvm::SMLoc >, llvm::SmallVectorTemplateBase< llvm::SMRange >, llvm::SmallVectorTemplateBase< llvm::RecordVal >, llvm::SmallVectorTemplateBase< llvm::Record::AssertionInfo >, llvm::SmallVectorTemplateBase< llvm::Record::DumpInfo >, llvm::SmallVectorTemplateBase< std::pair< llvm::Record *, llvm::SMRange > >, llvm::SmallVectorTemplateBase< std::unique_ptr< InsertPoint > >, llvm::SmallVectorTemplateBase< ScavengedInfo >, llvm::SmallVectorTemplateBase< llvm::RegisterMaskPair >, llvm::SmallVectorTemplateBase< llvm::EVT >, llvm::SmallVectorTemplateBase< llvm::MVT >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::DFAPacketizer > >, llvm::SmallVectorTemplateBase< llvm::SmallVector< uint64_t, DefaultProcResSize > >, llvm::SmallVectorTemplateBase< NodeRef >, llvm::SmallVectorTemplateBase< SID >, llvm::SmallVectorTemplateBase< std::pair< llvm::RelocationValueRef, llvm::RelocationEntry > >, llvm::SmallVectorTemplateBase< IFuncStub >, llvm::SmallVectorTemplateBase< llvm::RuntimeDyldMachO::EHFrameRelatedSections >, llvm::SmallVectorTemplateBase< llvm::RuntimePointerChecking::PointerInfo >, llvm::SmallVectorTemplateBase< llvm::RuntimeCheckingPtrGroup >, llvm::SmallVectorTemplateBase< llvm::PointerDiffInfo >, llvm::SmallVectorTemplateBase< std::pair< llvm::Function *, llvm::ValueLatticeElement > >, llvm::SmallVectorTemplateBase< std::pair< std::pair< llvm::Function *, unsigned >, llvm::ValueLatticeElement > >, llvm::SmallVectorTemplateBase< SCEVInsertPointGuard * >, llvm::SmallVectorTemplateBase< const llvm::SCEVPredicate * >, llvm::SmallVectorTemplateBase< llvm::SDDbgValue * >, llvm::SmallVectorTemplateBase< llvm::SDDbgLabel * >, llvm::SmallVectorTemplateBase< std::pair< Register, int > >, llvm::SmallVectorTemplateBase< Register >, llvm::SmallVectorTemplateBase< std::pair< Value *, StoreList > >, llvm::SmallVectorTemplateBase< std::pair< Value *, GEPList > >, llvm::SmallVectorTemplateBase< llvm::SMFixIt >, llvm::SmallVectorTemplateBase< llvm::SPIRV::DTSortableEntry * >, llvm::SmallVectorTemplateBase< SPIRV::Capability::Capability >, llvm::SmallVectorTemplateBase< Capability::Capability >, llvm::SmallVectorTemplateBase< Extension::Extension >, llvm::SmallVectorTemplateBase< std::pair< KeyTy, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateBase< std::pair< const llvm::Type *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateBase< std::pair< const llvm::Constant *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateBase< std::pair< const llvm::GlobalVariable *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateBase< std::pair< const llvm::Function *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateBase< std::pair< const llvm::Argument *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateBase< std::pair< const llvm::SPIRV::SpecialTypeDescriptor *, SPIRV::DTSortableEntry > >, llvm::SmallVectorTemplateBase< SPIRV::Extension::Extension >, llvm::SmallVectorTemplateBase< SPIRV::InstructionSet::InstructionSet >, llvm::SmallVectorTemplateBase< llvm::PHINode * >, llvm::SmallVectorTemplateBase< RewriteInfo >, llvm::SmallVectorTemplateBase< llvm::Use * >, llvm::SmallVectorTemplateBase< PhiT * >, llvm::SmallVectorTemplateBase< llvm::SDep >, llvm::SmallVectorTemplateBase< ExitNotTakenInfo >, llvm::SmallVectorTemplateBase< llvm::APInt >, llvm::SmallVectorTemplateBase< RootData >, llvm::SmallVectorTemplateBase< TreeData >, llvm::SmallVectorTemplateBase< SMSNode >, llvm::SmallVectorTemplateBase< std::pair< llvm::SUnit *, llvm::SUnit * > >, llvm::SmallVectorTemplateBase< llvm::sys::MemoryBlock >, llvm::SmallVectorTemplateBase< FreeMemBlock >, llvm::SmallVectorTemplateBase< std::pair< const llvm::Value *, DanglingDebugInfoVector > >, llvm::SmallVectorTemplateBase< llvm::SDValue >, llvm::SmallVectorTemplateBase< const llvm::GCRelocateInst * >, llvm::SmallVectorTemplateBase< IdxMBBPair >, llvm::SmallVectorTemplateBase< ValueT >, llvm::SmallVectorTemplateBase< llvm::ArgInfo >, llvm::SmallVectorTemplateBase< llvm::BlockFrequency >, llvm::SmallVectorTemplateBase< llvm::SplitAnalysis::BlockInfo >, llvm::SmallVectorTemplateBase< const llvm::IntrinsicInst * >, llvm::SmallVectorTemplateBase< llvm::StackLifetime::LiveRange >, llvm::SmallVectorTemplateBase< std::pair< uint64_t, uint64_t > >, llvm::SmallVectorTemplateBase< std::pair< const MCSymbol *, FunctionInfo > >, llvm::SmallVectorTemplateBase< Location >, llvm::SmallVectorTemplateBase< LiveOutReg >, llvm::SmallVectorTemplateBase< llvm::ArgumentInit * >, llvm::SmallVectorTemplateBase< llvm::IRPosition >, llvm::SmallVectorTemplateBase< llvm::SuffixTreeInternalNode * >, llvm::SmallVectorTemplateBase< const Value * >, llvm::SmallVectorTemplateBase< llvm::SmallPtrSet< llvm::SUnit *, 4 > >, llvm::SmallVectorTemplateBase< llvm::SmallVector< int, 4 > >, llvm::SmallVectorTemplateBase< BitTestCase >, llvm::SmallVectorTemplateBase< std::pair< std::pair< const MCSymbol *, unsigned >, uint32_t > >, llvm::SmallVectorTemplateBase< llvm::DefsetRecord * >, llvm::SmallVectorTemplateBase< std::pair< GlobalVariable *, tlshoist::TLSCandidate > >, llvm::SmallVectorTemplateBase< llvm::ISD::OutputArg >, llvm::SmallVectorTemplateBase< llvm::Timer * >, llvm::SmallVectorTemplateBase< TimeTraceProfilerEntry >, llvm::SmallVectorTemplateBase< llvm::TruncInst * >, llvm::SmallVectorTemplateBase< std::pair< llvm::Instruction *, Info > >, llvm::SmallVectorTemplateBase< llvm::VFInfo >, llvm::SmallVectorTemplateBase< llvm::VFParameter >, llvm::SmallVectorTemplateBase< llvm::VPBlockBase * >, llvm::SmallVectorTemplateBase< llvm::VPHeaderPHIRecipe * >, llvm::SmallVectorTemplateBase< llvm::VPValue * >, llvm::SmallVectorTemplateBase< llvm::VPUser * >, llvm::SmallVectorTemplateBase< llvm::VPBasicBlock * >, llvm::SmallVectorTemplateBase< llvm::ElementCount >, llvm::SmallVectorTemplateBase< std::pair< llvm::PHINode *, llvm::VPLiveOut * > >, llvm::SmallVectorTemplateBase< VPBlockBase * >, llvm::SmallVectorTemplateBase< MultiNodeOpTy >, llvm::SmallVectorTemplateBase< wasm::ValType >, llvm::SmallVectorTemplateBase< llvm::SmallVector< wasm::ValType, 4 > >, llvm::SmallVectorTemplateBase< std::pair< uint64_t, bool > >, llvm::SmallVectorTemplateBase< EHInstKind >, llvm::SmallVectorTemplateBase< std::pair< llvm::MCSymbol *, llvm::WinEH::FrameInfo::Epilog > >, llvm::SmallVectorTemplateBase< std::pair< llvm::MCSymbol *, int64_t > >, llvm::SmallVectorTemplateBase< llvm::CxxUnwindMapEntry >, llvm::SmallVectorTemplateBase< llvm::WinEHTryBlockMapEntry >, llvm::SmallVectorTemplateBase< llvm::SEHUnwindMapEntry >, llvm::SmallVectorTemplateBase< llvm::ClrEHUnwindMapEntry >, llvm::SmallVectorTemplateBase< llvm::WinEHHandlerType >, llvm::SmallVectorTemplateBase< size_t >, llvm::SmallVectorTemplateBase< llvm::SmallVector< size_t, 4 > >, llvm::SmallVectorTemplateBase< llvm::cl::OptionCategory * >, llvm::SmallVectorTemplateBase< llvm::cl::Option * >, llvm::SmallVectorTemplateBase< llvm::cl::SubCommand * >, llvm::SmallVectorTemplateBase< llvm::cl::OptionEnumValue >, llvm::SmallVectorTemplateBase< llvm::ArrayRef< uint8_t > >, llvm::SmallVectorTemplateBase< RecordLimit >, llvm::SmallVectorTemplateBase< llvm::codeview::GloballyHashedType >, llvm::SmallVectorTemplateBase< ConstantUser >, llvm::SmallVectorTemplateBase< RebasedConstantInfo >, llvm::SmallVectorTemplateBase< llvm::AnyCoroEndInst * >, llvm::SmallVectorTemplateBase< llvm::CoroSizeInst * >, llvm::SmallVectorTemplateBase< llvm::CoroAlignInst * >, llvm::SmallVectorTemplateBase< llvm::AnyCoroSuspendInst * >, llvm::SmallVectorTemplateBase< llvm::CallInst * >, llvm::SmallVectorTemplateBase< const llvm::coverage::CoverageSegment * >, llvm::SmallVectorTemplateBase< TestVector >, llvm::SmallVectorTemplateBase< llvm::detail::PtrUseVisitorBase::UseToVisit >, llvm::SmallVectorTemplateBase< PatchLocation >, llvm::SmallVectorTemplateBase< AccelTableKind >, llvm::SmallVectorTemplateBase< llvm::dwarf_linker::parallel::CompileUnit::DIEInfo >, llvm::SmallVectorTemplateBase< llvm::StringMapEntry * >, llvm::SmallVectorTemplateBase< uint64_t * >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext > >, llvm::SmallVectorTemplateBase< std::unique_ptr< CompileUnit > >, llvm::SmallVectorTemplateBase< RefModuleUnit >, llvm::SmallVectorTemplateBase< DWARFLinkerBase::AccelTableKind >, llvm::SmallVectorTemplateBase< LiveRootWorklistItemTy >, llvm::SmallVectorTemplateBase< const llvm::StringMapEntry * >, llvm::SmallVectorTemplateBase< llvm::dxil::UAVResource >, llvm::SmallVectorTemplateBase< llvm::dxil::ConstantBuffer >, llvm::SmallVectorTemplateBase< llvm::fuzzerop::SourcePred >, llvm::SmallVectorTemplateBase< SmallVector< uint64_t, 4 > >, llvm::SmallVectorTemplateBase< ElemT >, llvm::SmallVectorTemplateBase< llvm::jitlink::ppc64::PLTCallStubReloc >, llvm::SmallVectorTemplateBase< State >, llvm::SmallVectorTemplateBase< LVLine * >, llvm::SmallVectorTemplateBase< LVScope * >, llvm::SmallVectorTemplateBase< LVSymbol * >, llvm::SmallVectorTemplateBase< LVType * >, llvm::SmallVectorTemplateBase< LVElement * >, llvm::SmallVectorTemplateBase< LVTotalsEntry >, llvm::SmallVectorTemplateBase< std::pair< StringRef, BitcodeModule > >, llvm::SmallVectorTemplateBase< EncodingInfo >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::mca::HardwareUnit > >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::mca::Instruction > >, llvm::SmallVectorTemplateBase< llvm::mca::InstRef >, llvm::SmallVectorTemplateBase< llvm::mca::WriteDescriptor >, llvm::SmallVectorTemplateBase< llvm::mca::ReadDescriptor >, llvm::SmallVectorTemplateBase< std::pair< uint64_t, llvm::mca::ResourceUsage > >, llvm::SmallVectorTemplateBase< llvm::mca::WriteState >, llvm::SmallVectorTemplateBase< llvm::mca::ReadState >, llvm::SmallVectorTemplateBase< ResourceUse >, llvm::SmallVectorTemplateBase< llvm::mca::MemoryGroup * >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::mca::Stage > >, llvm::SmallVectorTemplateBase< RegisterMappingTracker >, llvm::SmallVectorTemplateBase< std::pair< llvm::mca::ReadState *, int > >, llvm::SmallVectorTemplateBase< llvm::mcdxbc::PSVSignatureElement >, llvm::SmallVectorTemplateBase< Parameter >, llvm::SmallVectorTemplateBase< llvm::memprof::Frame >, llvm::SmallVectorTemplateBase< llvm::memprof::IndexedAllocationInfo >, llvm::SmallVectorTemplateBase< llvm::SmallVector< uint64_t > >, llvm::SmallVectorTemplateBase< llvm::memprof::AllocationInfo >, llvm::SmallVectorTemplateBase< llvm::SmallVector< llvm::memprof::Frame > >, llvm::SmallVectorTemplateBase< SegmentEntry >, llvm::SmallVectorTemplateBase< std::pair< uint64_t, MemInfoBlock > >, llvm::SmallVectorTemplateBase< llvm::IntrinsicInst * >, llvm::SmallVectorTemplateBase< llvm::DbgVariableIntrinsic * >, llvm::SmallVectorTemplateBase< std::pair< llvm::AllocaInst *, llvm::memtag::AllocaInfo > >, llvm::SmallVectorTemplateBase< llvm::objcopy::elf::SectionBase * >, llvm::SmallVectorTemplateBase< SectionInfo >, llvm::SmallVectorTemplateBase< NodeState >, llvm::SmallVectorTemplateBase< const uint8_t * >, llvm::SmallVectorTemplateBase< llvm::object::DataRefImpl >, llvm::SmallVectorTemplateBase< LoadCommandInfo >, llvm::SmallVectorTemplateBase< StringRef >, llvm::SmallVectorTemplateBase< std::pair< llvm::StringRef, llvm::StringRef > >, llvm::SmallVectorTemplateBase< llvm::object::PGOAnalysisMap::PGOBBEntry::SuccessorEntry >, llvm::SmallVectorTemplateBase< TraitProperty >, llvm::SmallVectorTemplateBase< Arg * >, llvm::SmallVectorTemplateBase< std::unique_ptr< llvm::opt::Arg > >, llvm::SmallVectorTemplateBase< llvm::StringLiteral >, llvm::SmallVectorTemplateBase< std::pair< std::string, llvm::orc::ExecutorAddr > >, llvm::SmallVectorTemplateBase< std::tuple< ExecutorAddr, ExecutorAddr, MachOExecutorSymbolFlags > >, llvm::SmallVectorTemplateBase< llvm::orc::ExecutorAddrRange >, llvm::SmallVectorTemplateBase< InjectedSourceDescriptor >, llvm::SmallVectorTemplateBase< const llvm::TargetRegisterClass * >, llvm::SmallVectorTemplateBase< llvm::remarks::BitstreamRemarkParserHelper::Argument >, llvm::SmallVectorTemplateBase< llvm::remarks::Argument >, llvm::SmallVectorTemplateBase< StackRegion >, llvm::SmallVectorTemplateBase< StackObject >, llvm::SmallVectorTemplateBase< std::pair< llvm::sampleprof::FunctionId, uint32_t > >, llvm::SmallVectorTemplateBase< llvm::sampleprof::SecHdrTableEntry >, llvm::SmallVectorTemplateBase< std::pair< llvm::sampleprof::SampleContext, uint64_t > >, llvm::SmallVectorTemplateBase< std::pair< llvm::sampleprof::SampleContext, uint32_t > >, llvm::SmallVectorTemplateBase< const SamplesWithLoc * >, llvm::SmallVectorTemplateBase< std::unique_ptr< TreeEntry > >, llvm::SmallVectorTemplateBase< const TreeEntry * >, llvm::SmallVectorTemplateBase< ExternalUser >, llvm::SmallVectorTemplateBase< std::pair< llvm::BasicBlock *, std::unique_ptr< BlockScheduling > > >, llvm::SmallVectorTemplateBase< std::unique_ptr< ScheduleData[]> >, llvm::SmallVectorTemplateBase< ScheduleData * >, llvm::SmallVectorTemplateBase< llvm::slpvectorizer::BoUpSLP::EdgeInfo >, llvm::SmallVectorTemplateBase< SmallVector< Value *, 8 > >, llvm::SmallVectorTemplateBase< llvm::SmallVector >, llvm::SmallVectorTemplateBase< const MMap * >, llvm::SmallVectorTemplateBase< llvm::symbolize::MarkupNode >, llvm::SmallVectorTemplateBase< llvm::tlshoist::TLSUser >, llvm::SmallVectorTemplateBase< IntrusiveRefCntPtr< FileSystem > >, llvm::SmallVectorTemplateBase< llvm::vfs::RedirectingFileSystem::Entry * >, llvm::SmallVectorTemplateBase< ValType >, llvm::SmallVectorTemplateBase< TrieNode * >, llvm::SmallVectorTemplateBase< llvm::yaml::StringValue >, llvm::SmallVectorTemplateBase< SimpleKey >, llvm::SmallVectorTemplateBase< T, bool >, and llvm::SmallVectorTemplateBase< T, true >.
Public Types
using size_type = size_t
using difference_type = ptrdiff_t
using value_type = T
using iterator = T *
using const_iterator = const T *
using const_reverse_iterator = std::reverse_iterator< const_iterator >
using reverse_iterator = std::reverse_iterator< iterator >
using reference = T &
using const_reference = const T &
using pointer = T *
using const_pointer = const T *
Public Member Functions
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size_in_bytes () const
size_type max_size () const
size_t capacity_in_bytes () const
pointer data ()
Return a pointer to the vector's buffer, even if empty().
const_pointer data () const
Return a pointer to the vector's buffer, even if empty().
reference operator[] (size_type idx)
const_reference operator[] (size_type idx) const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
Public Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
size_t size () const
size_t capacity () const
bool empty () const
Protected Member Functions
void * getFirstEl () const
Find the address of the first element.
SmallVectorTemplateCommon (size_t Size)
void grow_pod (size_t MinSize, size_t TSize)
bool isSmall () const
Return true if this is a smallvector which has not had dynamic memory allocated for it.
void resetToSmall ()
Put this vector in a state of being small.
bool isReferenceToRange (const void *V, const void *First, const void *Last) const
Return true if V is an internal reference to the given range.
bool isReferenceToStorage (const void *V) const
Return true if V is an internal reference to this vector.
bool isRangeInStorage (const void *First, const void *Last) const
Return true if First and Last form a valid (possibly empty) range in this vector's storage.
bool isSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Return true unless Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToReferenceAfterResize (const void *Elt, size_t NewSize)
Check whether Elt will be invalidated by resizing the vector to NewSize.
void assertSafeToAdd (const void *Elt, size_t N=1)
Check whether Elt will be invalidated by increasing the size of the vector by N.
void assertSafeToReferenceAfterClear (const T *From, const T *To)
Check whether any part of the range will be invalidated by clearing.
template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToReferenceAfterClear (ItTy, ItTy)
void assertSafeToAddRange (const T *From, const T *To)
Check whether any part of the range will be invalidated by growing.
template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false>
void assertSafeToAddRange (ItTy, ItTy)
Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
SmallVectorBase ()=delete
SmallVectorBase (void *FirstEl, size_t TotalCapacity)
void * mallocForGrow (void *FirstEl, size_t MinSize, size_t TSize, size_t &NewCapacity)
This is a helper for grow() that's out of line to reduce code duplication.
void grow_pod (void *FirstEl, size_t MinSize, size_t TSize)
This is an implementation of the grow() method which only works on POD-like data types and is out of line to reduce code duplication.
void * replaceAllocation (void *NewElts, size_t TSize, size_t NewCapacity, size_t VSize=0)
If vector was first created with capacity 0, getFirstEl() points to the memory right after, an area unallocated.
void set_size (size_t N)
Set the array size to N, which the current array must have enough capacity for.
void set_allocation_range (void *Begin, size_t N)
Set the array data pointer to Begin and capacity to N.
Static Protected Member Functions
template<class U >
static const T * reserveForParamAndGetAddressImpl (U *This, const T &Elt, size_t N)
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Static Protected Member Functions inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
static constexpr size_t SizeTypeMax ()
The maximum value of the Size_T used.
Additional Inherited Members
Protected Attributes inherited from llvm::SmallVectorBase< SmallVectorSizeType< T > >
void * BeginX
SmallVectorSizeType< T > Size
SmallVectorSizeType< T > Capacity
Detailed Description
template<typename T, typename = void>
class llvm::SmallVectorTemplateCommon< T, typename >
This is the part of SmallVectorTemplateBase which does not depend on whether the type T is a POD.
The extra dummy template argument is used by ArrayRef to avoid unnecessarily requiring T to be complete.
Definition at line 133 of file SmallVector.h.
Member Typedef Documentation
const_iterator
template<typename T , typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::const_iterator = const T *
Definition at line 265 of file SmallVector.h.
const_pointer
template<typename T , typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::const_pointer = const T *
Definition at line 273 of file SmallVector.h.
const_reference
template<typename T , typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::const_reference = const T &
Definition at line 271 of file SmallVector.h.
const_reverse_iterator
template<typename T , typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::const_reverse_iterator = std::reverse_iterator<const_iterator>
Definition at line 267 of file SmallVector.h.
difference_type
template<typename T , typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::difference_type = ptrdiff_t
Definition at line 262 of file SmallVector.h.
iterator
template<typename T , typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::iterator = T *
Definition at line 264 of file SmallVector.h.
pointer
template<typename T , typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::pointer = T *
Definition at line 272 of file SmallVector.h.
reference
template<typename T , typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::reference = T &
Definition at line 270 of file SmallVector.h.
reverse_iterator
template<typename T , typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::reverse_iterator = std::reverse_iterator<iterator>
Definition at line 268 of file SmallVector.h.
size_type
template<typename T , typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::size_type = size_t
Definition at line 261 of file SmallVector.h.
value_type
template<typename T , typename = void> using llvm::SmallVectorTemplateCommon< T, typename >::value_type = T
Definition at line 263 of file SmallVector.h.
Constructor & Destructor Documentation
SmallVectorTemplateCommon()
template<typename T , typename = void> llvm::SmallVectorTemplateCommon< T, typename >::SmallVectorTemplateCommon (size_t Size) inline protected
Definition at line 148 of file SmallVector.h.
Member Function Documentation
assertSafeToAdd()
template<typename T , typename = void> void llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToAdd (const void * Elt, size_t N = 1) inline protected
Check whether Elt will be invalidated by increasing the size of the vector by N.
Definition at line 209 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToReferenceAfterResize(), N, and llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
Referenced by llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToAddRange().
assertSafeToAddRange() [1/2]
template<typename T , typename = void> void llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToAddRange (const T * From, const T * To) inline protected
Check whether any part of the range will be invalidated by growing.
Definition at line 227 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToAdd(), and From.
Referenced by llvm::SmallVectorImpl< T >::append(), and llvm::SmallVectorImpl< T >::insert().
assertSafeToAddRange() [2/2]
template<typename T , typename = void> template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false> void llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToAddRange (ItTy , ItTy) inline protected
Definition at line 237 of file SmallVector.h.
assertSafeToReferenceAfterClear() [1/2]
template<typename T , typename = void> void llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToReferenceAfterClear (const T * From, const T * To) inline protected
Check whether any part of the range will be invalidated by clearing.
Definition at line 214 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToReferenceAfterResize(), and From.
Referenced by llvm::SmallVectorImpl< T >::assign().
assertSafeToReferenceAfterClear() [2/2]
template<typename T , typename = void> template<class ItTy , std::enable_if_t<!std::is_same< std::remove_const_t< ItTy >, T * >::value, bool > = false> void llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToReferenceAfterClear (ItTy , ItTy) inline protected
Definition at line 224 of file SmallVector.h.
assertSafeToReferenceAfterResize()
template<typename T , typename = void> void llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToReferenceAfterResize (const void * Elt, size_t NewSize) inline protected
Check whether Elt will be invalidated by resizing the vector to NewSize.
Definition at line 201 of file SmallVector.h.
References assert(), and llvm::SmallVectorTemplateCommon< T, typename >::isSafeToReferenceAfterResize().
Referenced by llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToAdd(), and llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToReferenceAfterClear().
back() [1/2]
template<typename T , typename = void> reference llvm::SmallVectorTemplateCommon< T, typename >::back () inline
Definition at line 321 of file SmallVector.h.
References assert(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::empty(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::add(), llvm::slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::add(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addParamNames(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), llvm::object::ExportEntry::address(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addTemplateParamNames(), advanceToNextLeafType(), analyzeCompressibleUses(), llvm::Annotations::Annotations(), llvm::LiveRange::append(), llvm::A57ChainingConstraint::apply(), ARM64FindSegmentsInFunction(), llvm::DirectedGraph< NodeType, EdgeType >::back(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildMultiplyTree(), CalcNodeSethiUllmanNumber(), canRewriteGEPAsOffset(), canUseReferenceType(), canVectorizeLoads(), checkIfSupported(), checkOrAndOpImpliedByOther(), combineBVOfConsecutiveLoads(), combineConcatVectorOfScalars(), combineHorizOpWithShuffle(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::EHStreamer::computeCallSiteTable(), computeFunctionSummary(), llvm::RegBankSelect::computeMapping(), ComputePostOrders(), llvm::ConstantFoldTerminator(), createFunctionClones(), createTblForTrunc(), llvm::ScheduleDAGSDNodes::dumpNode(), EltsFromConsecutiveLoads(), EmitAddTreeOfValues(), llvm::EHStreamer::emitExceptionTable(), llvm::WebAssemblyTargetWasmStreamer::emitLocal(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::TimeTraceProfiler::end(), llvm::LiveRange::endIndex(), llvm::BitstreamCursor::EnterSubBlock(), llvm::DominatorTreeBase< NodeT, IsPostDom >::eraseNode(), llvm::objcopy::macho::executeObjcopyOnMachOUniversalBinary(), ExpandBVWithShuffles(), llvm::cl::ExpansionContext::expandResponseFiles(), ExtractSymbol(), llvm::FindFunctionBackedges(), firstRealType(), llvm::object::ExportEntry::flags(), getAllLexicalIndexes(), GetBranchWeights(), llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::MCStreamer::getCurrentSection(), llvm::safestack::StackLayout::getFrameSize(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), llvm::logicalview::getInnerComponent(), llvm::ConstraintSystem::getLastConstraint(), llvm::SimpleDDGNode::getLastInstruction(), llvm::GCOVBlock::getLastLine(), llvm::MCStreamer::getPreviousSection(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::Intrinsic::getType(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::getVisitState(), llvm::SmallVectorTemplateBase< T, bool >::growAndEmplaceBack(), llvm::SmallVectorTemplateBase< T, true >::growAndEmplaceBack(), hostParallelCallback(), llvm::IntervalMapImpl::Path::leaf(), llvm::IntervalMapImpl::Path::leafOffset(), llvm::IntervalMapImpl::Path::leafSize(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::link(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::LinkContext::loadClangModule(), llvm::PPCInstrInfo::loadRegFromStackSlotNoUpd(), llvm::AArch64CallLowering::lowerCall(), llvm::SPIRVCallLowering::lowerCall(), MatchVectorAllEqualTest(), llvm::object::ExportEntry::moveNext(), llvm::LegalizerHelper::narrowScalar(), needsReferenceType(), nextRealType(), llvm::object::ExportEntry::nodeOffset(), llvm::nonStrictlyPostDominate(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator*(), llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator*(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator++(), llvm::po_iterator< GraphT, SetType, ExtStorage, GT >::operator++(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::operator--(), llvm::object::ExportEntry::other(), llvm::object::ExportEntry::otherName(), ParseFunctionArgs(), parseScalarValue(), llvm::AMDGPUTargetLowering::performFNegCombine(), llvm::performOptimizedStructLayout(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::AsmPrinter::preprocessXXStructorList(), llvm::WebAssemblyInstPrinter::printInst(), llvm::GCOVFunction::propagateCounts(), llvm::AAPointerInfo::RangeList::push_back(), llvm::sampleprof::SampleProfileReaderText::readImpl(), llvm::sys::path::remove_dots(), llvm::MemoryDependenceResults::removeInstruction(), removeRedundantBlockingStores(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::returnTypeIsEligibleForTailCall(), llvm::SelectionDAGISel::SelectCodeCommon(), selectConstantAddr(), simplifySwitchOfPowersOfTwo(), llvm::ImutAVLTreeGenericIterator< ImutInfo >::skipToParent(), sortLocalVars(), llvm::CallLowering::splitToValueTypes(), llvm::DbgValueHistoryMap::startClobber(), llvm::DbgValueHistoryMap::startDbgValue(), llvm::PPCInstrInfo::storeRegToStackSlotNoUpd(), llvm::MCStreamer::subSection(), swapMIOperands(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::MCStreamer::switchSection(), llvm::MCStreamer::switchSectionNoChange(), takeInexpensiveLog2(), llvm::VFABI::tryDemangleForVFABI(), unswitchNontrivialInvariants(), llvm::DominatorTreeBase< NodeT, IsPostDom >::updateDFSNumbers(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::dwarf_linker::parallel::DependencyTracker::verifyKeepChain(), and llvm::json::OStream::~OStream().
back() [2/2]
template<typename T , typename = void> const_reference llvm::SmallVectorTemplateCommon< T, typename >::back () const inline
Definition at line 325 of file SmallVector.h.
References assert(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::empty(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
begin() [1/2]
template<typename T , typename = void> iterator llvm::SmallVectorTemplateCommon< T, typename >::begin () inline
Definition at line 280 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::BeginX.
Referenced by llvm::slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::add(), llvm::SPIRV::RequirementHandler::addExtensions(), addHints(), addMappingsFromTLI(), llvm::logicalview::LVScope::addMissingElements(), llvm::MCPseudoProbeInlineTree::addPseudoProbe(), llvm::RecurrenceDescriptor::AddReductionVar(), llvm::InstrProfWriter::addTemporalProfileTraces(), llvm::GCNSchedStrategy::advanceStage(), llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::MipsInstrInfo::analyzeBranch(), analyzeExitPHIsForOutputUses(), analyzeLoopUnrollCost(), llvm::OpenMPIRBuilder::MapInfosTy::append(), llvm::SmallVectorImpl< T >::assign(), llvm::SmallVectorImpl< T >::assignRemote(), llvm::DWARFAbbreviationDeclaration::attributes(), llvm::LazyCallGraph::EdgeSequence::begin(), llvm::RegBankSelect::RepairingPlacement::begin(), llvm::LiveRange::begin(), llvm::orc::AllocGroupSmallMap< T >::begin(), llvm::SubsumingPositionIterator::begin(), llvm::AAPointerInfo::RangeList::begin(), llvm::HexagonShuffler::begin(), llvm::DirectedGraph< NodeType, EdgeType >::begin(), llvm::AliasSet::begin(), llvm::LazyCallGraph::SCC::begin(), llvm::LazyCallGraph::RefSCC::begin(), llvm::GCModuleInfo::begin(), llvm::LiveRangeEdit::begin(), llvm::DWARFDebugNames::begin(), llvm::object::DXContainer::begin(), llvm::object::MachOObjectFile::begin_load_commands(), buildOverlapMapAndRecordDeclares(), llvm::SDDbgInfo::ByvalParmDbgBegin(), llvm::LazyCallGraph::EdgeSequence::call_begin(), callBufferedPrintfArgPush(), canVectorizeLoads(), CasesAreContiguous(), llvm::HexagonShuffler::cbegin(), checkDependencies(), llvm::SmallVectorImpl< T >::clear(), TransferTracker::clobberMloc(), collectMultiplyFactors(), collectOtherInstr(), llvm::LoopVectorizationCostModel::collectValuesToIgnore(), llvm::mca::RegisterFile::collectWrites(), CombineBaseUpdate(), combineBitcastvxi1(), combineX86ShufflesRecursively(), llvm::DominatorTreeBase< NodeT, IsPostDom >::compare(), llvm::computeAccessFunctions(), computeCalleeSaveRegisterPairs(), llvm::RandomIRBuilder::connectToSink(), llvm::IntervalTree< PointT, ValueT, DataT >::create(), createCandidatesFromSuffixTree(), createTblForTrunc(), createUniqueEntity(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::DataDependenceGraph::DataDependenceGraph(), llvm::SDDbgInfo::DbgBegin(), llvm::SDDbgInfo::DbgLabelBegin(), deleteDeadBlocksFromLoop(), deleteDeadClonedBlocks(), determineGPRegsToClear(), llvm::DomTreeUpdater::dump(), llvm::DWARFContext::dwo_info_section_units(), llvm::DWARFContext::dwo_types_section_units(), llvm::DWARFContext::dwo_units(), llvm::EHStreamer::emitExceptionTable(), llvm::XCoreFrameLowering::emitPrologue(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::AsmPrinter::emitXXStructorList(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::mca::InstructionTables::execute(), llvm::X86TargetLowering::ExpandInlineAsm(), llvm::cl::ExpansionContext::expandResponseFiles(), extractInstructionFeatures(), llvm::LazyCallGraph::RefSCC::find(), llvm::findArrayDimensions(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), llvm::RegBankSelect::findBestMapping(), llvm::cl::ExpansionContext::findConfigFile(), llvm::SSAUpdaterImpl< UpdaterT >::FindExistingPHI(), llvm::LiveRange::findIndexesLiveAt(), llvm::RandomIRBuilder::findOrCreateSource(), llvm::slpvectorizer::BoUpSLP::findReusedOrderedScalars(), llvm::MCSection::flushPendingLabels(), foldGEPChainAsStructAccess(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::WebAssemblyAsmTypeCheck::funcDecl(), llvm::FunctionImportGlobalProcessing::FunctionImportGlobalProcessing(), llvm::RecordRecTy::get(), llvm::ScalarEvolution::getAddExpr(), llvm::opt::ArgList::getAllArgValues(), llvm::Attribute::getAsString(), llvm::opt::Arg::getAsString(), llvm::IRSimilarity::IRInstructionData::getBlockOperVals(), llvm::DebugLocStream::getBytes(), llvm::SelectionDAG::getConstant(), llvm::SampleContextTracker::getContextString(), llvm::RegsForValue::getCopyFromRegs(), llvm::GenericCycle< ContextT >::getExitBlocks(), getFauxShuffleMask(), llvm::MachineInstrExpressionTrait::getHashValue(), llvm::BlockFrequencyInfoImplBase::LoopData::getHeaderIndex(), llvm::MCDecodedPseudoProbe::getInlineContext(), llvm::DataLayout::getLargestLegalIntTypeSizeInBits(), llvm::GraphDiff< NodePtr, InverseGraph >::getLegalizedUpdates(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::ScalarEvolution::getMulExpr(), llvm::RegisterBankInfo::getOperandsMapping(), getOrCreateFrameHelper(), llvm::HvxSelector::getPerfectCompletions(), getPreStartForExtend(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::slpvectorizer::BoUpSLP::getReorderingData(), getSalvageOpsForGEP(), getSchedRegions(), llvm::ScalarEvolution::getSequentialMinMaxExpr(), llvm::GetShadowBytesAfterScope(), llvm::RISCVTTIImpl::getShuffleCost(), llvm::X86TTIImpl::getShuffleCost(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::VPBlockBase::getSinglePredecessor(), llvm::VPBlockBase::getSingleSuccessor(), llvm::gsym::LookupResult::getSourceFile(), llvm::object::MinidumpFile::getString(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTokenFactor(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::getTotalMemory(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::DWARFUnitVector::getUnitForIndexEntry(), llvm::DWARFUnitVector::getUnitForOffset(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::VFABI::getVectorVariantNames(), llvm::SmallVectorTemplateBase< T, bool >::growAndAssign(), llvm::SmallVectorTemplateBase< T, true >::growAndAssign(), hashValueMapping(), llvm::SDNode::hasPredecessorHelper(), llvm::ExtractValueInst::idx_begin(), llvm::InsertValueInst::idx_begin(), llvm::logicalview::LVBinaryReader::includeInlineeLines(), llvm::DWARFContext::info_section_units(), llvm::IRSimilarity::IRInstructionData::initializeInstruction(), initializeUniqueCases(), llvm::InlineFunction(), llvm::AddressRanges::insert(), llvm::AddressRangesMap::insert(), llvm::SmallVectorImpl< T >::insert(), llvm::AAPointerInfo::RangeList::insert(), llvm::ARMBasicBlockUtils::insert(), insertParsePoints(), llvm::CallLowering::insertSRetIncomingArgument(), instCombineConvertFromSVBool(), llvm::FoldingSetNodeID::Intern(), llvm::BlockFrequencyInfoImplBase::LoopData::isHeader(), isHorizontalBinOp(), llvm::SmallVectorTemplateCommon< T, typename >::isRangeInStorage(), llvm::SmallVectorTemplateCommon< T, typename >::isReferenceToStorage(), llvm::SmallVectorTemplateCommon< T, typename >::isSafeToReferenceAfterResize(), isUpperSubvectorUndef(), isVECTOR_SHUFFLE_SPLATI(), isWideDUPMask(), llvm::MCAsmLexer::Lex(), llvm::coverage::CoverageMapping::load(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::FunctionVarLocs::locs_begin(), llvm::FunctionVarLocs::locs_end(), LowerInterruptReturn(), lowerStatepointMetaArgs(), lowerV16I8Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), shuffles::mask(), matchScalarReduction(), llvm::SlotIndexes::MBBIndexBegin(), llvm::BlockFrequencyInfoImplBase::LoopData::members_begin(), llvm::AAPointerInfo::RangeList::merge(), llvm::Instruction::mergeDIAssignID(), mergeDILocations(), mergeVectorRegsToResultRegs(), llvm::sys::unicode::nameToCodepoint(), llvm::LegalizerHelper::narrowScalar(), llvm::DWARFContext::normal_units(), llvm::RegsForValue::occupiesMultipleRegs(), llvm::sampleprof::SampleContextFrameHash::operator()(), llvm::SmallVectorImpl< T >::operator<(), llvm::operator<<(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::operator=(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< T >::operator==(), llvm::SmallVectorTemplateCommon< T, typename >::operator[](), OptimizeAndOrXor(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::X86FrameLowering::orderFrameObjects(), llvm::vfs::OverlayFileSystem::overlays_rbegin(), llvm::object::parseBuildID(), parseScalarValue(), performBranchToCommonDestFolding(), performCONCAT_VECTORSCombine(), llvm::performOptimizedStructLayout(), llvm::logicalview::LVScopeCompileUnit::printMatchedElements(), llvm::logicalview::LVBinaryReader::processLines(), llvm::sys::fs::readNativeFileToEOF(), llvm::BinaryStreamReader::readSLEB128(), llvm::BinaryStreamReader::readULEB128(), llvm::readWideAPInt(), llvm::AArch64TargetLowering::ReconstructShuffle(), llvm::SSAUpdaterImpl< UpdaterT >::RecordMatchingPHIs(), llvm::PassInstrumentationCallbacks::registerAfterAnalysisCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback(), llvm::sys::path::remove_filename(), RemovePreallocated(), removeRedundantDbgLocsUsingBackwardScan(), llvm::Record::removeValue(), llvm::SmallVectorTemplateCommon< T, typename >::rend(), llvm::opt::Arg::render(), llvm::opt::Arg::renderAsInput(), llvm::slpvectorizer::BoUpSLP::reorderBottomToTop(), reorderOrder(), reorderReuses(), reorderSubVector(), llvm::slpvectorizer::BoUpSLP::reorderTopToBottom(), llvm::sys::path::replace_extension(), replaceConstantExprOp(), llvm::IntervalMapImpl::Path::replaceRoot(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Reset(), llvm::CCState::resultsCompatible(), llvm::DominatorTreeBase< NodeT, IsPostDom >::root_begin(), llvm::FunctionSpecializer::run(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::setProfMetadata(), llvm::AAPointerInfo::RangeList::setUnknown(), setUsedInitializer(), llvm::HexagonShuffler::shuffle(), simplifyInstructionWithOperands(), SimplifyValuePattern(), llvm::FunctionVarLocs::single_locs_begin(), llvm::FunctionVarLocs::single_locs_end(), sink(), sinkInstruction(), llvm::InnerLoopVectorizer::sinkScalarOperands(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), llvm::SmallString< InternalLen >::SmallString(), llvm::SmallVectorMemoryBuffer::SmallVectorMemoryBuffer(), llvm::dwarf_linker::parallel::ArrayList< T, ItemsGroupSize >::sort(), sortGlobalExprs(), llvm::IntervalTree< PointT, ValueT, DataT >::sortIntervals(), llvm::DebugLocEntry::sortUniqueValues(), splitPredecessorsOfLoopExit(), llvm::stableHashValue(), llvm::Regex::sub(), llvm::SmallVectorImpl< T >::swap(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), llvm::object::ELFFile< ELFT >::toMappedAddr(), toStringAPFloat(), llvm::objcopy::macho::MachOWriter::totalSize(), llvm::SmallVectorImpl< T >::truncate(), llvm::LegalizationArtifactCombiner::tryCombineUnmergeValues(), llvm::LegalizationArtifactCombiner::tryFoldUnmergeCast(), llvm::MCDwarfLineTableHeader::tryGetFile(), tryToVectorizeSequence(), llvm::WebAssemblyAsmTypeCheck::typeCheck(), llvm::DWARFContext::types_section_units(), llvm::MCAsmLexer::UnLex(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), shuffles::vdealvdd(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::InstCombinerImpl::visitLandingPadInst(), llvm::LiveRange::vni_begin(), shuffles::vshuffvdd(), llvm::WriteBitcodeToFile(), llvm::dxil::WriteDXILToFile(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::~BumpPtrAllocatorImpl(), and llvm::SmallVectorImpl< T >::~SmallVectorImpl().
begin() [2/2]
template<typename T , typename = void> const_iterator llvm::SmallVectorTemplateCommon< T, typename >::begin () const inline
Definition at line 281 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::BeginX.
capacity_in_bytes()
template<typename T , typename = void> size_t llvm::SmallVectorTemplateCommon< T, typename >::capacity_in_bytes () const inline
Definition at line 296 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::capacity(), and T.
data() [1/2]
template<typename T , typename = void> pointer llvm::SmallVectorTemplateCommon< T, typename >::data () inline
Return a pointer to the vector's buffer, even if empty().
Definition at line 299 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by llvm::SmallString< InternalLen >::c_str(), llvm::c_str(), llvm::FileCheck::CanonicalizeFile(), llvm::orc::cloneToNewContext(), CollectOpsToWiden(), llvm::orc::shared::WrapperFunctionCall::Create(), llvm::pdb::DIASession::createFromExe(), llvm::pdb::DIASession::createFromPdb(), llvm::ConnectedVNInfoEqClasses::Distribute(), emitExternalFile(), llvm::MCStreamer::emitIntValue(), llvm::gsym::FunctionInfo::encode(), llvm::COFF::encodeSectionName(), llvm::opt::ArgList::eraseArg(), llvm::pdb::DIARawSymbol::findChildren(), llvm::pdb::DIARawSymbol::findChildrenByAddr(), llvm::pdb::DIARawSymbol::findChildrenByRVA(), llvm::pdb::DIARawSymbol::findChildrenByVA(), llvm::remarks::BitstreamRemarkSerializerHelper::flushToStream(), GenerateFixedLengthSVETBL(), GenerateTBL(), llvm::remarks::BitstreamRemarkSerializerHelper::getBuffer(), llvm::symbolize::getBuildIDStr(), llvm::dwarf_linker::parallel::SectionDescriptor::getContents(), llvm::pdb::DIARawSymbol::getDataBytes(), llvm::MachineTraceMetrics::getProcReleaseAtCycles(), llvm::InitLLVM::InitLLVM(), LLVMDisasmInstruction(), LLVMOrcExecutionSessionLookup(), lowerV8I16GeneralSingleInputShuffle(), llvm::sys::fs::make_absolute(), llvm::Regex::match(), matchUnaryPermuteShuffle(), llvm::sys::path::native(), llvm::SmallString< InternalLen >::operator std::string(), llvm::FoldingSetNodeID::operator<(), llvm::FoldingSetNodeID::operator==(), llvm::performOptimizedStructLayout(), llvm::PrettyStackTraceFormat::PrettyStackTraceFormat(), llvm::ReadByteArrayFromGlobal(), llvm::sys::path::remove_dots(), llvm::dwarf_linker::parallel::SectionDescriptor::setSizesForSectionCreatedByAsmPrinter(), splitCodeGen(), llvm::LiveIntervals::splitSeparateComponents(), llvm::SmallString< InternalLen >::str(), llvm::Twine::toNullTerminatedStringRef(), llvm::Twine::toStringRef(), llvm::mcdxbc::Signature::write(), llvm::objcopy::elf::IHexSectionWriter::writeData(), llvm::BitcodeWriter::writeSymtab(), writeUniversalArchsToStream(), and llvm::sampleprof::SampleProfileWriter::writeWithSizeLimitInternal().
data() [2/2]
template<typename T , typename = void> const_pointer llvm::SmallVectorTemplateCommon< T, typename >::data () const inline
Return a pointer to the vector's buffer, even if empty().
Definition at line 301 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
end() [1/2]
template<typename T , typename = void> iterator llvm::SmallVectorTemplateCommon< T, typename >::end () inline
Definition at line 282 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
Referenced by llvm::slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::add(), addData(), llvm::SPIRV::RequirementHandler::addExtensions(), addHints(), addMappingsFromTLI(), llvm::logicalview::LVScope::addMissingElements(), llvm::DirectedGraph< NodeType, EdgeType >::addNode(), llvm::MCPseudoProbeInlineTree::addPseudoProbe(), llvm::RecurrenceDescriptor::AddReductionVar(), addRegLanes(), llvm::InstrProfWriter::addTemporalProfileTraces(), llvm::GCNSchedStrategy::advanceStage(), llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR(), llvm::CCState::AnalyzeArgumentsSecondPass(), analyzeLoopUnrollCost(), llvm::SmallVectorImpl< T >::append(), llvm::OpenMPIRBuilder::MapInfosTy::append(), llvm::DIExpression::appendOpsToArg(), llvm::SmallVectorImpl< T >::assign(), llvm::SmallVectorImpl< T >::assignRemote(), llvm::DWARFAbbreviationDeclaration::attributes(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::LazyCallGraph::EdgeSequence::begin(), buildOverlapMapAndRecordDeclares(), llvm::SDDbgInfo::ByvalParmDbgEnd(), llvm::LazyCallGraph::EdgeSequence::call_begin(), llvm::LazyCallGraph::EdgeSequence::call_end(), CasesAreContiguous(), llvm::HexagonShuffler::cend(), checkDependencies(), checkIfSupported(), llvm::SmallVectorImpl< T >::clear(), llvm::LoopVectorizationCostModel::collectValuesToIgnore(), llvm::mca::RegisterFile::collectWrites(), CombineBaseUpdate(), combineBitcastvxi1(), combineX86ShufflesRecursively(), llvm::DominatorTreeBase< NodeT, IsPostDom >::compare(), llvm::computeAccessFunctions(), computeCalleeSaveRegisterPairs(), llvm::DirectedGraph< NodeType, EdgeType >::connect(), llvm::RandomIRBuilder::connectToSink(), llvm::IntervalTree< PointT, ValueT, DataT >::create(), createTblForTrunc(), llvm::DataDependenceGraph::DataDependenceGraph(), llvm::SDDbgInfo::DbgEnd(), llvm::SDDbgInfo::DbgLabelEnd(), deleteDeadBlocksFromLoop(), deleteDeadClonedBlocks(), llvm::ARMFrameLowering::determineCalleeSaves(), determineGPRegsToClear(), llvm::RegPressureTracker::discoverLiveInOrOut(), llvm::DomTreeUpdater::dump(), llvm::DWARFContext::dwo_types_section_units(), llvm::DWARFContext::dwo_units(), llvm::EHStreamer::emitExceptionTable(), llvm::XCoreFrameLowering::emitPrologue(), llvm::UnwindOpcodeAssembler::EmitRaw(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::AsmPrinter::emitXXStructorList(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::LazyCallGraph::EdgeSequence::end(), llvm::RegBankSelect::RepairingPlacement::end(), llvm::LiveRange::end(), llvm::orc::AllocGroupSmallMap< T >::end(), llvm::SubsumingPositionIterator::end(), llvm::AAPointerInfo::RangeList::end(), llvm::HexagonShuffler::end(), llvm::DirectedGraph< NodeType, EdgeType >::end(), llvm::AliasSet::end(), llvm::LazyCallGraph::SCC::end(), llvm::LazyCallGraph::RefSCC::end(), llvm::GCModuleInfo::end(), llvm::LiveRangeEdit::end(), llvm::DWARFDebugNames::end(), llvm::object::DXContainer::end(), llvm::object::MachOObjectFile::end_load_commands(), llvm::SmallVectorImpl< T >::erase(), llvm::DominatorTreeBase< NodeT, IsPostDom >::eraseNode(), llvm::X86TargetLowering::ExpandInlineAsm(), llvm::cl::ExpansionContext::expandResponseFiles(), extractInstructionFeatures(), llvm::findArrayDimensions(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), llvm::cl::ExpansionContext::findConfigFile(), llvm::SSAUpdaterImpl< UpdaterT >::FindExistingPHI(), llvm::LiveRange::findIndexesLiveAt(), findInfo(), llvm::RandomIRBuilder::findOrCreateSource(), llvm::MCSection::flushPendingLabels(), foldGEPChainAsStructAccess(), llvm::ScalarEvolution::forgetLoop(), llvm::WebAssemblyAsmTypeCheck::funcDecl(), llvm::FunctionImportGlobalProcessing::FunctionImportGlobalProcessing(), llvm::RecordRecTy::get(), llvm::opt::ArgList::getAllArgValues(), llvm::Attribute::getAsString(), llvm::opt::Arg::getAsString(), llvm::IRSimilarity::IRInstructionData::getBlockOperVals(), llvm::DebugLocStream::getBytes(), llvm::SelectionDAG::getConstant(), llvm::SampleContextTracker::getContextString(), llvm::GCNSchedStrategy::getCurrentStage(), getFauxShuffleMask(), llvm::MachineInstrExpressionTrait::getHashValue(), llvm::MCDecodedPseudoProbe::getInlineContext(), llvm::DataLayout::getLargestLegalIntTypeSizeInBits(), llvm::GraphDiff< NodePtr, InverseGraph >::getLegalizedUpdates(), llvm::CacheCost::getLoopCost(), llvm::ScalarEvolution::getMinMaxExpr(), llvm::GCNSchedStrategy::getNextStage(), llvm::RegisterBankInfo::getOperandsMapping(), llvm::HvxSelector::getPerfectCompletions(), getPreStartForExtend(), llvm::X86RegisterInfo::getRegAllocationHints(), llvm::slpvectorizer::BoUpSLP::getReorderingData(), getSchedRegions(), llvm::ScalarEvolution::getSequentialMinMaxExpr(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::getShuffleReduction(), llvm::gsym::LookupResult::getSourceFile(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTokenFactor(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::getTotalMemory(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::DWARFUnitVector::getUnitForIndexEntry(), llvm::DWARFUnitVector::getUnitForOffset(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::VFABI::getVectorVariantNames(), llvm::SmallVectorTemplateBase< T, bool >::growAndAssign(), hashValueMapping(), llvm::GCNSchedStrategy::hasNextStage(), llvm::SDNode::hasPredecessorHelper(), llvm::ExtractValueInst::idx_end(), llvm::InsertValueInst::idx_end(), llvm::logicalview::LVBinaryReader::includeInlineeLines(), llvm::InlineFunction(), llvm::AddressRanges::insert(), llvm::AddressRangesMap::insert(), llvm::SmallVectorImpl< T >::insert(), llvm::AAPointerInfo::RangeList::insert(), insertParsePoints(), llvm::FoldingSetNodeID::Intern(), llvm::xray::Profile::internPath(), isHorizontalBinOp(), llvm::SmallVectorTemplateCommon< T, typename >::isRangeInStorage(), llvm::SmallVectorTemplateCommon< T, typename >::isReferenceToStorage(), isUpperSubvectorUndef(), isVECTOR_SHUFFLE_SPLATI(), isWideDUPMask(), llvm::coverage::CoverageMapping::load(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::WebAssemblyAsmTypeCheck::localDecl(), llvm::BlockFrequencyInfoImplBase::LoopData::LoopData(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerStatepointMetaArgs(), lowerV16I8Shuffle(), lowerV8I16GeneralSingleInputShuffle(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), llvm::LiveVariables::MarkVirtRegAliveInBlock(), shuffles::mask(), llvm::SlotIndexes::MBBIndexEnd(), llvm::BlockFrequencyInfoImplBase::LoopData::members_end(), llvm::Instruction::mergeDIAssignID(), llvm::sys::unicode::nameToCodepoint(), llvm::LegalizerHelper::narrowScalar(), llvm::sys::unicode::nearestMatchesForCodepointName(), llvm::DWARFContext::normal_units(), llvm::RegsForValue::occupiesMultipleRegs(), llvm::sampleprof::SampleContextFrameHash::operator()(), llvm::object::DXContainer::PartIterator::operator++(), llvm::SmallVectorImpl< T >::operator<(), llvm::operator<<(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::operator=(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< T >::operator==(), llvm::orc::AllocGroupSmallMap< T >::operator[](), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), llvm::X86FrameLowering::orderFrameObjects(), llvm::vfs::OverlayFileSystem::overlays_rend(), llvm::object::parseBuildID(), performBranchToCommonDestFolding(), performCONCAT_VECTORSCombine(), llvm::performOptimizedStructLayout(), placeSources(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::MCStreamer::popSection(), llvm::logicalview::LVScopeCompileUnit::printMatchedElements(), ProcessElementList(), llvm::logicalview::LVBinaryReader::processLines(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::rbegin(), llvm::BinaryStreamReader::readSLEB128(), llvm::BinaryStreamReader::readULEB128(), llvm::RegPressureTracker::recede(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::reconstituteName(), llvm::AArch64TargetLowering::ReconstructShuffle(), llvm::SSAUpdaterImpl< UpdaterT >::RecordMatchingPHIs(), RemoveInstInputs(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::DirectedGraph< NodeType, EdgeType >::removeNode(), llvm::GISelObserverWrapper::removeObserver(), RemovePreallocated(), removeRedundantDbgLocsUsingBackwardScan(), removeRegLanes(), llvm::opt::Arg::render(), llvm::opt::Arg::renderAsInput(), reorderOrder(), reorderReuses(), replaceConstantExprOp(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Reset(), llvm::CCState::resultsCompatible(), llvm::DominatorTreeBase< NodeT, IsPostDom >::root_end(), llvm::FunctionSpecializer::run(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::setProfMetadata(), setRegZero(), setUsedInitializer(), llvm::HexagonShuffler::shuffle(), llvm::JumpThreadingPass::simplifyPartiallyRedundantLoad(), SimplifyValuePattern(), sink(), llvm::InnerLoopVectorizer::sinkScalarOperands(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), llvm::SmallString< InternalLen >::SmallString(), llvm::dwarf_linker::parallel::ArrayList< T, ItemsGroupSize >::sort(), sortGlobalExprs(), llvm::IntervalTree< PointT, ValueT, DataT >::sortIntervals(), llvm::DebugLocEntry::sortUniqueValues(), splitPredecessorsOfLoopExit(), llvm::stableHashValue(), llvm::Regex::sub(), llvm::SmallVectorImpl< T >::swap(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), toStringAPFloat(), llvm::objcopy::macho::MachOWriter::totalSize(), llvm::SmallVectorImpl< T >::truncate(), llvm::LegalizationArtifactCombiner::tryCombineUnmergeValues(), tryToVectorizeSequence(), llvm::WebAssemblyAsmTypeCheck::typeCheck(), llvm::DWARFContext::types_section_units(), unswitchLoop(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), verifySubExpr(), llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit(), llvm::LiveRange::vni_end(), and llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::~BumpPtrAllocatorImpl().
end() [2/2]
template<typename T , typename = void> const_iterator llvm::SmallVectorTemplateCommon< T, typename >::end () const inline
Definition at line 283 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
front() [1/2]
template<typename T , typename = void> reference llvm::SmallVectorTemplateCommon< T, typename >::front () inline
Definition at line 312 of file SmallVector.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::empty().
Referenced by llvm::slpvectorizer::BoUpSLP::ShuffleCostEstimator::add(), llvm::slpvectorizer::BoUpSLP::ShuffleInstructionBuilder::add(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::MCPseudoProbeInlineTree::addPseudoProbe(), adjustByValArgAlignment(), llvm::LiveRange::beginIndex(), calcPredicateUsingBooleans(), calcPredicateUsingInteger(), canVectorizeLoads(), combineHorizOpWithShuffle(), combineX86ShuffleChainWithExtract(), combineX86ShufflesRecursively(), llvm::dxil::createEntryMD(), createPHIsForSelects(), llvm::ARMFrameLowering::determineCalleeSaves(), llvm::slpvectorizer::BoUpSLP::doesRootHaveInTreeUses(), EltsFromConsecutiveLoads(), ExtractImmediate(), ExtractSymbol(), llvm::DirectedGraph< NodeType, EdgeType >::front(), GetBranchWeights(), llvm::vfs::OverlayFileSystem::getCurrentWorkingDirectory(), llvm::SimpleDDGNode::getFirstInstruction(), llvm::logicalview::getInnerComponent(), llvm::TargetInstrInfo::getMemOperandWithOffset(), llvm::codeview::getModifiedType(), llvm::LoopNest::getPerfectLoops(), llvm::MachineTraceMetrics::Trace::getPHIDepth(), llvm::slpvectorizer::BoUpSLP::getRootNodeScalars(), getSameOpcode(), llvm::AAPointerInfo::RangeList::getUnique(), llvm::intersectAccessGroups(), llvm::ARMBaseInstrInfo::isLoadFromStackSlotPostFE(), llvm::LanaiInstrInfo::isLoadFromStackSlotPostFE(), llvm::X86InstrInfo::isLoadFromStackSlotPostFE(), llvm::ARMBaseInstrInfo::isStoreToStackSlotPostFE(), llvm::X86InstrInfo::isStoreToStackSlotPostFE(), llvm::AAPointerInfo::RangeList::isUnique(), llvm::AAPointerInfo::RangeList::isUnknown(), llvm::Legalizer::legalizeMachineFunction(), llvm::MCAsmLexer::Lex(), llvm::codeview::CodeViewRecordIO::maxFieldLength(), llvm::sampleprof::SampleProfileReaderGCC::readOneFunctionProfile(), llvm::slpvectorizer::BoUpSLP::VLOperands::reorder(), llvm::reorderScalars(), llvm::coro::replaceCoroFree(), llvm::IntervalMapImpl::Path::replaceRoot(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Reset(), llvm::DominatorTreeBase< NodeT, IsPostDom >::setNewRoot(), simplifySwitchOfPowersOfTwo(), sinkLastInstruction(), tryToVectorizeSequence(), llvm::IntervalMapImpl::Path::valid(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), widenVectorOpsToi8(), llvm::objcopy::elf::BinaryWriter::write(), llvm::WriteBitcodeToFile(), llvm::dxil::WriteDXILToFile(), llvm::writeIndexToFile(), and llvm::writeThinLinkBitcodeToFile().
front() [2/2]
template<typename T , typename = void> const_reference llvm::SmallVectorTemplateCommon< T, typename >::front () const inline
Definition at line 316 of file SmallVector.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::empty().
getFirstEl()
template<typename T , typename = void> void * llvm::SmallVectorTemplateCommon< T, typename >::getFirstEl () const inline protected
Find the address of the first element.
For this pointer math to be valid with small-size of 0 for T with lots of alignment, it's important that SmallVectorStorage is properly-aligned even for small-size of 0.
Definition at line 141 of file SmallVector.h.
References offsetof.
Referenced by llvm::SmallVectorTemplateCommon< T, typename >::grow_pod(), llvm::SmallVectorTemplateCommon< T, typename >::isSmall(), and llvm::SmallVectorTemplateCommon< T, typename >::resetToSmall().
grow_pod()
template<typename T , typename = void> void llvm::SmallVectorTemplateCommon< T, typename >::grow_pod (size_t MinSize, size_t TSize) inline protected
Definition at line 150 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::getFirstEl(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::grow_pod().
Referenced by llvm::SmallVectorTemplateBase< T, true >::grow().
isRangeInStorage()
template<typename T , typename = void> bool llvm::SmallVectorTemplateCommon< T, typename >::isRangeInStorage (const void * First, const void * Last) const inline protected
Return true if First and Last form a valid (possibly empty) range in this vector's storage.
Definition at line 178 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::First, and llvm::Last.
Referenced by llvm::SmallVectorImpl< T >::erase().
isReferenceToRange()
template<typename T , typename = void> bool llvm::SmallVectorTemplateCommon< T, typename >::isReferenceToRange (const void * V, const void * First, const void * Last) const inline protected
Return true if V is an internal reference to the given range.
Definition at line 165 of file SmallVector.h.
References llvm::First, and llvm::Last.
Referenced by llvm::SmallVectorTemplateCommon< T, typename >::isReferenceToStorage().
isReferenceToStorage()
template<typename T , typename = void> bool llvm::SmallVectorTemplateCommon< T, typename >::isReferenceToStorage (const void * V) const inline protected
Return true if V is an internal reference to this vector.
Definition at line 172 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::SmallVectorTemplateCommon< T, typename >::isReferenceToRange().
Referenced by llvm::SmallVectorImpl< T >::erase(), llvm::SmallVectorImpl< T >::insert(), and llvm::SmallVectorTemplateCommon< T, typename >::isSafeToReferenceAfterResize().
isSafeToReferenceAfterResize()
template<typename T , typename = void> bool llvm::SmallVectorTemplateCommon< T, typename >::isSafeToReferenceAfterResize (const void * Elt, size_t NewSize) inline protected
Return true unless Elt will be invalidated by resizing the vector to NewSize.
Definition at line 187 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase< SmallVectorSizeType< T > >::capacity(), llvm::SmallVectorTemplateCommon< T, typename >::isReferenceToStorage(), LLVM_LIKELY, and llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
Referenced by llvm::SmallVectorTemplateCommon< T, typename >::assertSafeToReferenceAfterResize().
isSmall()
template<typename T , typename = void> bool llvm::SmallVectorTemplateCommon< T, typename >::isSmall () const inline protected
Return true if this is a smallvector which has not had dynamic memory allocated for it.
Definition at line 156 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::BeginX, and llvm::SmallVectorTemplateCommon< T, typename >::getFirstEl().
Referenced by llvm::SmallVectorImpl< T >::assignRemote(), llvm::SmallVectorImpl< T >::swap(), and llvm::SmallVectorImpl< T >::~SmallVectorImpl().
max_size()
template<typename T , typename = void> size_type llvm::SmallVectorTemplateCommon< T, typename >::max_size () const inline
Definition at line 292 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::SizeTypeMax().
operator[]() [1/2]
template<typename T , typename = void> reference llvm::SmallVectorTemplateCommon< T, typename >::operator[] (size_type idx) inline
Definition at line 303 of file SmallVector.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
operator[]() [2/2]
template<typename T , typename = void> const_reference llvm::SmallVectorTemplateCommon< T, typename >::operator[] (size_type idx) const inline
Definition at line 307 of file SmallVector.h.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::size().
rbegin() [1/2]
template<typename T , typename = void> reverse_iterator llvm::SmallVectorTemplateCommon< T, typename >::rbegin () inline
Definition at line 286 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), llvm::SSAUpdaterImpl< UpdaterT >::FindDominators(), llvm::SSAUpdaterImpl< UpdaterT >::FindPHIPlacement(), foldICmpOrXorSubChain(), getNoopInput(), llvm::vfs::OverlayFileSystem::overlays_begin(), llvm::WebAssemblyInstPrinter::printInst(), rewriteAccessChain(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), and llvm::slpvectorizer::BoUpSLP::vectorizeTree().
rbegin() [2/2]
template<typename T , typename = void> const_reverse_iterator llvm::SmallVectorTemplateCommon< T, typename >::rbegin () const inline
Definition at line 287 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
rend() [1/2]
template<typename T , typename = void> reverse_iterator llvm::SmallVectorTemplateCommon< T, typename >::rend () inline
Definition at line 288 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), llvm::SSAUpdaterImpl< UpdaterT >::FindDominators(), llvm::SSAUpdaterImpl< UpdaterT >::FindPHIPlacement(), foldICmpOrXorSubChain(), llvm::vfs::OverlayFileSystem::overlays_end(), rewriteAccessChain(), and llvm::slpvectorizer::BoUpSLP::vectorizeTree().
rend() [2/2]
template<typename T , typename = void> const_reverse_iterator llvm::SmallVectorTemplateCommon< T, typename >::rend () const inline
Definition at line 289 of file SmallVector.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
reserveForParamAndGetAddressImpl()
template<typename T , typename = void> template<class U > static const T * llvm::SmallVectorTemplateCommon< T, typename >::reserveForParamAndGetAddressImpl (U * This, const T & Elt, size_t N) inline static protected
Reserve enough space to add one element, and return the updated element pointer in case it was a reference to the storage.
Definition at line 242 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::capacity(), LLVM_LIKELY, LLVM_UNLIKELY, and N.
Referenced by llvm::SmallVectorTemplateBase< T, bool >::reserveForParamAndGetAddress(), and llvm::SmallVectorTemplateBase< T, true >::reserveForParamAndGetAddress().
resetToSmall()
template<typename T , typename = void> void llvm::SmallVectorTemplateCommon< T, typename >::resetToSmall () inline protected
Put this vector in a state of being small.
Definition at line 159 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::BeginX, llvm::SmallVectorBase< SmallVectorSizeType< T > >::Capacity, llvm::SmallVectorTemplateCommon< T, typename >::getFirstEl(), and llvm::SmallVectorBase< SmallVectorSizeType< T > >::Size.
size_in_bytes()
template<typename T , typename = void> size_type llvm::SmallVectorTemplateCommon< T, typename >::size_in_bytes () const inline
Definition at line 291 of file SmallVector.h.
References llvm::SmallVectorBase< SmallVectorSizeType< T > >::size(), and T.
The documentation for this class was generated from the following file:
include/llvm/ADT/SmallVector.h