LLVM: llvm::objcopy::elf::IHexSectionWriter Class Reference
llvm::objcopy::elf::IHexSectionWriter Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
IHexSectionWriter (WritableMemoryBuffer &Buf)
void writeData (uint8_t Type, uint16_t Addr, ArrayRef< uint8_t > Data) override
Error visit (const StringTableSection &Sec) override
Public Member Functions inherited from llvm::objcopy::elf::IHexSectionWriterBase
IHexSectionWriterBase (WritableMemoryBuffer &Buf)
uint64_t getBufferOffset () const
Error visit (const Section &Sec) final
Error visit (const OwnedDataSection &Sec) final
Error visit (const StringTableSection &Sec) override
Error visit (const DynamicRelocationSection &Sec) final
Error visit (const SymbolTableSection &Sec) override
Error visit (const RelocationSection &Sec) override
Error visit (const GnuDebugLinkSection &Sec) override
Error visit (const GroupSection &Sec) override
Error visit (const SectionIndexSection &Sec) override
Error visit (const CompressedSection &Sec) override
Error visit (const DecompressedSection &Sec) override
Public Member Functions inherited from llvm::objcopy::elf::BinarySectionWriter
virtual ~BinarySectionWriter ()
Error visit (const SymbolTableSection &Sec) override
Error visit (const RelocationSection &Sec) override
Error visit (const GnuDebugLinkSection &Sec) override
Error visit (const GroupSection &Sec) override
Error visit (const SectionIndexSection &Sec) override
Error visit (const CompressedSection &Sec) override
Error visit (const DecompressedSection &Sec) override
BinarySectionWriter (WritableMemoryBuffer &Buf)
Public Member Functions inherited from llvm::objcopy::elf::SectionWriter
virtual ~SectionWriter ()=default
Error visit (const Section &Sec) override
Error visit (const OwnedDataSection &Sec) override
Error visit (const StringTableSection &Sec) override
Error visit (const DynamicRelocationSection &Sec) override
Error visit (const SymbolTableSection &Sec) override=0
Error visit (const RelocationSection &Sec) override=0
Error visit (const GnuDebugLinkSection &Sec) override=0
Error visit (const GroupSection &Sec) override=0
Error visit (const SectionIndexSection &Sec) override=0
Error visit (const CompressedSection &Sec) override=0
Error visit (const DecompressedSection &Sec) override=0
SectionWriter (WritableMemoryBuffer &Buf)
Public Member Functions inherited from llvm::objcopy::elf::SectionVisitor
virtual ~SectionVisitor ()=default
virtual Error visit (const Section &Sec)=0
virtual Error visit (const OwnedDataSection &Sec)=0
virtual Error visit (const StringTableSection &Sec)=0
virtual Error visit (const SymbolTableSection &Sec)=0
virtual Error visit (const RelocationSection &Sec)=0
virtual Error visit (const DynamicRelocationSection &Sec)=0
virtual Error visit (const GnuDebugLinkSection &Sec)=0
virtual Error visit (const GroupSection &Sec)=0
virtual Error visit (const SectionIndexSection &Sec)=0
virtual Error visit (const CompressedSection &Sec)=0
virtual Error visit (const DecompressedSection &Sec)=0
Additional Inherited Members
Protected Member Functions inherited from llvm::objcopy::elf::IHexSectionWriterBase
void writeSection (const SectionBase *Sec, ArrayRef< uint8_t > Data)
virtual void writeData (uint8_t Type, uint16_t Addr, ArrayRef< uint8_t > Data)
Protected Attributes inherited from llvm::objcopy::elf::IHexSectionWriterBase
uint64_t Offset = 0
Protected Attributes inherited from llvm::objcopy::elf::SectionWriter
WritableMemoryBuffer & Out
Detailed Description
Definition at line 299 of file ELFObject.h.
Constructor & Destructor Documentation
IHexSectionWriter()
llvm::objcopy::elf::IHexSectionWriter::IHexSectionWriter (WritableMemoryBuffer & Buf) inline
Definition at line 301 of file ELFObject.h.
Member Function Documentation
visit()
Error IHexSectionWriter::visit (const StringTableSection & Sec) override virtual
Reimplemented from llvm::objcopy::elf::IHexSectionWriterBase.
Definition at line 416 of file ELFObject.cpp.
References assert(), llvm::Data, llvm::StringTableBuilder::getSize(), llvm::objcopy::elf::SectionBase::Size, llvm::Error::success(), llvm::StringTableBuilder::write(), and llvm::objcopy::elf::IHexSectionWriterBase::writeSection().
writeData()
void IHexSectionWriter::writeData (uint8_t Type, uint16_t Addr, ArrayRef< uint8_t > Data) override virtual
Reimplemented from llvm::objcopy::elf::IHexSectionWriterBase.
Definition at line 409 of file ELFObject.cpp.
References Addr, llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::Data, llvm::WritableMemoryBuffer::getBufferStart(), llvm::objcopy::elf::IHexRecord::getLine(), llvm::objcopy::elf::IHexSectionWriterBase::Offset, llvm::objcopy::elf::SectionWriter::Out, and llvm::SmallVectorBase< Size_T >::size().
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp