LLVM: llvm::SparcMachineFunctionInfo Class Reference
llvm::SparcMachineFunctionInfo Class Reference
#include "Target/Sparc/SparcMachineFunctionInfo.h"
Public Member Functions
SparcMachineFunctionInfo ()
SparcMachineFunctionInfo (const Function &F, const TargetSubtargetInfo *STI)
MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const override
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
Register getGlobalBaseReg () const
void setGlobalBaseReg (Register Reg)
int getVarArgsFrameOffset () const
void setVarArgsFrameOffset (int Offset)
Register getSRetReturnReg () const
void setSRetReturnReg (Register Reg)
void setLeafProc (bool rhs)
bool isLeafProc () const
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
virtual MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy , typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Detailed Description
Definition at line 19 of file SparcMachineFunctionInfo.h.
Constructor & Destructor Documentation
SparcMachineFunctionInfo() [1/2]
llvm::SparcMachineFunctionInfo::SparcMachineFunctionInfo () inline
Definition at line 34 of file SparcMachineFunctionInfo.h.
SparcMachineFunctionInfo() [2/2]
llvm::SparcMachineFunctionInfo::SparcMachineFunctionInfo (const Function & F, const TargetSubtargetInfo * STI) inline
Definition at line 37 of file SparcMachineFunctionInfo.h.
Member Function Documentation
clone()
MachineFunctionInfo * SparcMachineFunctionInfo::clone (BumpPtrAllocator & Allocator, MachineFunction & DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) const override virtual
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
This requires remapping MachineBasicBlock references from the original parent to values in the new function. Targets may assume that virtual register and frame index values are preserved in the new function.
Reimplemented from llvm::MachineFunctionInfo.
Definition at line 15 of file SparcMachineFunctionInfo.cpp.
References llvm::MachineFunction::cloneInfo().
getGlobalBaseReg()
Register llvm::SparcMachineFunctionInfo::getGlobalBaseReg () const inline
Definition at line 46 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcInstrInfo::getGlobalBaseReg().
getSRetReturnReg()
Register llvm::SparcMachineFunctionInfo::getSRetReturnReg () const inline
Definition at line 52 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcTargetLowering::LowerFormalArguments_32(), and llvm::SparcTargetLowering::LowerReturn_32().
getVarArgsFrameOffset()
int llvm::SparcMachineFunctionInfo::getVarArgsFrameOffset () const inline
Definition at line 49 of file SparcMachineFunctionInfo.h.
Referenced by LowerVASTART().
isLeafProc()
bool llvm::SparcMachineFunctionInfo::isLeafProc () const inline
Definition at line 56 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitPrologue(), and llvm::SparcFrameLowering::getFrameIndexReference().
setGlobalBaseReg()
void llvm::SparcMachineFunctionInfo::setGlobalBaseReg (Register Reg) inline
Definition at line 47 of file SparcMachineFunctionInfo.h.
References Reg.
Referenced by llvm::SparcInstrInfo::getGlobalBaseReg().
setLeafProc()
void llvm::SparcMachineFunctionInfo::setLeafProc (bool rhs) inline
Definition at line 55 of file SparcMachineFunctionInfo.h.
Referenced by llvm::SparcFrameLowering::determineCalleeSaves().
setSRetReturnReg()
void llvm::SparcMachineFunctionInfo::setSRetReturnReg (Register Reg) inline
Definition at line 53 of file SparcMachineFunctionInfo.h.
References Reg.
Referenced by llvm::SparcTargetLowering::LowerFormalArguments_32().
setVarArgsFrameOffset()
void llvm::SparcMachineFunctionInfo::setVarArgsFrameOffset (int Offset) inline
Definition at line 50 of file SparcMachineFunctionInfo.h.
References llvm::Offset.
Referenced by llvm::SparcTargetLowering::LowerFormalArguments_32(), and llvm::SparcTargetLowering::LowerFormalArguments_64().
The documentation for this class was generated from the following files:
lib/Target/Sparc/SparcMachineFunctionInfo.h
lib/Target/Sparc/SparcMachineFunctionInfo.cpp