LLVM: llvm::DPMarker Class Reference
llvm::DPMarker Class Reference
Per-instruction record of debug-info.
#include "llvm/IR/DebugProgramInstruction.h"
Public Member Functions
DPMarker ()
bool empty () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
void removeMarker ()
Handle the removal of a marker: the position of debug-info has gone away, but the stored debug records should not.
void dump () const
void removeFromParent ()
void eraseFromParent ()
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on DPMarker.
void print (raw_ostream &ROS, ModuleSlotTracker &MST, bool IsForDebug) const
iterator_range< simple_ilist< DPValue >::iterator > getDbgValueRange ()
Produce a range over all the DPValues in this Marker.
iterator_range< simple_ilist< DPValue >::const_iterator > getDbgValueRange () const
void absorbDebugValues (DPMarker &Src, bool InsertAtHead)
Transfer any DPValues from Src into this DPMarker.
void absorbDebugValues (iterator_range< DPValue::self_iterator > Range, DPMarker &Src, bool InsertAtHead)
Transfer the DPValues in Range from Src into this DPMarker.
void insertDPValue (DPValue *New, bool InsertAtHead)
Insert a DPValue into this DPMarker, at the end of the list.
void insertDPValue (DPValue *New, DPValue *InsertBefore)
Insert a DPValue prior to a DPValue contained within this marker.
void insertDPValueAfter (DPValue *New, DPValue *InsertAfter)
Insert a DPValue after a DPValue contained within this marker.
iterator_range< simple_ilist< DPValue >::iterator > cloneDebugInfoFrom (DPMarker *From, std::optional< simple_ilist< DPValue >::iterator > FromHere, bool InsertAtHead=false)
Clone all DPMarkers from From into this marker.
void dropDPValues ()
Erase all DPValues in this DPMarker.
void dropOneDPValue (DPValue *DPV)
Erase a single DPValue from this marker.
Static Public Member Functions
static iterator_range< simple_ilist< DPValue >::iterator > getEmptyDPValueRange ()
Public Attributes
Instruction * MarkedInstr = nullptr
Link back to the Instruction that owns this marker.
simple_ilist< DPValue > StoredDPValues
List of DPValues, each recording a single variable assignment, the equivalent of a dbg.value intrinsic.
Static Public Attributes
static DPMarker EmptyDPMarker
We generally act like all llvm Instructions have a range of DPValues attached to them, but in reality sometimes we don't allocate the DPMarker to save time and memory, but still have to return ranges of DPValues.
Detailed Description
Per-instruction record of debug-info.
If an Instruction is the position of some debugging information, it points at a DPMarker storing that info. Each marker points back at the instruction that owns it. Various utilities are provided for manipulating the DPValues contained within this marker.
This class has a rough surface area, because it's needed to preserve the one arefact that we can't yet eliminate from the intrinsic / dbg.value debug-info design: the order of DPValues/records is significant, and duplicates can exist. Thus, if one has a run of debug-info records such as: dbg.value(... foo = barinst dbg.value(... and remove barinst, then the dbg.values must be preserved in the correct order. Hence, the use of iterators to select positions to insert things into, or the occasional InsertAtHead parameter indicating that new records should go at the start of the list.
There are only five or six places in LLVM that truly rely on this ordering, which we can improve in the future. Additionally, many improvements in the way that debug-info is stored can be achieved in this class, at a future date.
Definition at line 366 of file DebugProgramInstruction.h.
Constructor & Destructor Documentation
DPMarker()
llvm::DPMarker::DPMarker () inline
Definition at line 368 of file DebugProgramInstruction.h.
Referenced by removeMarker().
Member Function Documentation
absorbDebugValues() [1/2]
void llvm::DPMarker::absorbDebugValues (DPMarker & Src, bool InsertAtHead)
Transfer any DPValues from Src into this DPMarker.
If InsertAtHead is true, place them before existing DPValues, otherwise afterwards.
Definition at line 490 of file DebugProgramInstruction.cpp.
References llvm::DPValue::setMarker(), and StoredDPValues.
Referenced by llvm::Instruction::insertBefore(), llvm::BasicBlock::reinsertInstInDPValues(), and removeMarker().
absorbDebugValues() [2/2]
void llvm::DPMarker::absorbDebugValues (iterator_range< DPValue::self_iterator > Range, DPMarker & Src, bool InsertAtHead)
Transfer the DPValues in Range from Src into this DPMarker.
If InsertAtHead is true, place them before existing DPValues, otherwise
Definition at line 498 of file DebugProgramInstruction.cpp.
References StoredDPValues.
cloneDebugInfoFrom()
iterator_range< simple_ilist< DPValue >::iterator > llvm::DPMarker::cloneDebugInfoFrom (DPMarker * From, std::optional< simple_ilist< DPValue >::iterator > FromHere, bool InsertAtHead = false)
Clone all DPMarkers from From into this marker.
There are numerous options to customise the source/destination, due to gnarliness, see class comment. FromHere If non-null, copy from FromHere to the end of From's DPValues InsertAtHead Place the cloned DPValues at the start of StoredDPValues
Returns
Range over all the newly cloned DPValues
Definition at line 510 of file DebugProgramInstruction.cpp.
References llvm::First, From, llvm::make_range(), and StoredDPValues.
Referenced by llvm::Instruction::cloneDebugInfoFrom(), and llvm::JumpThreadingPass::cloneInstructions().
dropDPValues()
void llvm::DPMarker::dropDPValues ()
Erase all DPValues in this DPMarker.
Definition at line 399 of file DebugProgramInstruction.cpp.
References llvm::DPValue::deleteInstr(), and StoredDPValues.
Referenced by llvm::Instruction::dropDbgValues(), and eraseFromParent().
dropOneDPValue()
void llvm::DPMarker::dropOneDPValue (DPValue * DPV)
Erase a single DPValue from this marker.
In an ideal future, we would never erase an assignment in this way, but it's the equivalent to erasing a dbg.value from a block.
Definition at line 408 of file DebugProgramInstruction.cpp.
References assert(), llvm::DPValue::deleteInstr(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::DPValue::getMarker(), and StoredDPValues.
Referenced by llvm::Instruction::dropOneDbgValue().
dump()
LLVM_DUMP_METHOD void DPMarker::dump () const
Definition at line 5141 of file AsmWriter.cpp.
References llvm::dbgs(), and print().
empty()
bool llvm::DPMarker::empty () const inline
Definition at line 379 of file DebugProgramInstruction.h.
References StoredDPValues.
eraseFromParent()
void llvm::DPMarker::eraseFromParent ()
Definition at line 447 of file DebugProgramInstruction.cpp.
References dropDPValues(), MarkedInstr, and removeFromParent().
Referenced by llvm::BasicBlock::convertFromNewDbgValues(), llvm::BasicBlock::flushTerminatorDbgValues(), and removeMarker().
getDbgValueRange() [1/2]
iterator_range< DPValue::self_iterator > llvm::DPMarker::getDbgValueRange ()
Produce a range over all the DPValues in this Marker.
Definition at line 454 of file DebugProgramInstruction.cpp.
References llvm::make_range(), and StoredDPValues.
Referenced by llvm::BasicBlock::convertFromNewDbgValues(), llvm::Instruction::getDbgValueRange(), getNextNode(), and llvm::BasicBlock::validateDbgValues().
getDbgValueRange() [2/2]
iterator_range< DPValue::const_self_iterator > llvm::DPMarker::getDbgValueRange () const
Definition at line 458 of file DebugProgramInstruction.cpp.
References llvm::make_range(), and StoredDPValues.
getEmptyDPValueRange()
static iterator_range< simple_ilist< DPValue >::iterator > llvm::DPMarker::getEmptyDPValueRange () inline static
Definition at line 441 of file DebugProgramInstruction.h.
References EmptyDPMarker, llvm::make_range(), and StoredDPValues.
Referenced by llvm::Instruction::cloneDebugInfoFrom(), and llvm::Instruction::getDbgValueRange().
getParent() [1/2]
BasicBlock * llvm::DPMarker::getParent ()
Definition at line 418 of file DebugProgramInstruction.cpp.
References llvm::Instruction::getParent(), and MarkedInstr.
getParent() [2/2]
const BasicBlock * llvm::DPMarker::getParent () const
Definition at line 414 of file DebugProgramInstruction.cpp.
References llvm::Instruction::getParent(), and MarkedInstr.
Referenced by llvm::formLCSSAForInstructions(), llvm::DPValue::getBlock(), getModuleFromDPI(), llvm::DPValue::print(), print(), replaceDbgUsesOutsideBlock(), and RewriteUsesOfClonedInstructions().
insertDPValue() [1/2]
void llvm::DPMarker::insertDPValue (DPValue * New, bool InsertAtHead)
Insert a DPValue into this DPMarker, at the end of the list.
If InsertAtHead is true, at the start.
Definition at line 472 of file DebugProgramInstruction.cpp.
References StoredDPValues.
Referenced by llvm::BasicBlock::convertToNewDbgValues(), llvm::DPValue::insertBefore(), and llvm::BasicBlock::insertDPValueAfter().
insertDPValue() [2/2]
void llvm::DPMarker::insertDPValue (DPValue * New, DPValue * InsertBefore)
Insert a DPValue prior to a DPValue contained within this marker.
Definition at line 477 of file DebugProgramInstruction.cpp.
References assert(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::DPValue::getMarker(), and StoredDPValues.
insertDPValueAfter()
void llvm::DPMarker::insertDPValueAfter (DPValue * New, DPValue * InsertAfter)
Insert a DPValue after a DPValue contained within this marker.
Definition at line 483 of file DebugProgramInstruction.cpp.
References assert(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::DPValue::getMarker(), and StoredDPValues.
Referenced by llvm::DPValue::insertAfter().
print() [1/2]
void DPMarker::print (raw_ostream & O, bool IsForDebug = false) const
Implement operator<< on DPMarker.
Definition at line 4847 of file AsmWriter.cpp.
References getModuleFromDPI(), and print().
Referenced by dump(), llvm::operator<<(), and print().
print() [2/2]
void DPMarker::print (raw_ostream & ROS, ModuleSlotTracker & MST, bool IsForDebug) const
Definition at line 4859 of file AsmWriter.cpp.
References F, llvm::ModuleSlotTracker::getMachine(), getModuleFromDPI(), getParent(), llvm::ModuleSlotTracker::incorporateFunction(), and OS.
removeFromParent()
void llvm::DPMarker::removeFromParent ()
Definition at line 442 of file DebugProgramInstruction.cpp.
References llvm::Instruction::DbgMarker, and MarkedInstr.
Referenced by eraseFromParent().
removeMarker()
void llvm::DPMarker::removeMarker ()
Handle the removal of a marker: the position of debug-info has gone away, but the stored debug records should not.
Drop them onto the next instruction, or otherwise work out what to do with them.
Definition at line 420 of file DebugProgramInstruction.cpp.
References absorbDebugValues(), llvm::Instruction::DbgMarker, DPMarker(), eraseFromParent(), llvm::BasicBlock::getNextMarker(), llvm::Instruction::getParent(), MarkedInstr, llvm::BasicBlock::setTrailingDPValues(), and StoredDPValues.
Referenced by llvm::Instruction::handleMarkerRemoval().
Member Data Documentation
EmptyDPMarker
DPMarker llvm::DPMarker::EmptyDPMarker static
We generally act like all llvm Instructions have a range of DPValues attached to them, but in reality sometimes we don't allocate the DPMarker to save time and memory, but still have to return ranges of DPValues.
When we need to describe such an unallocated DPValue range, use this static markers range instead. This will bite us if someone tries to insert a DPValue in that range, but they should be using the Official (TM) API for that.
Definition at line 440 of file DebugProgramInstruction.h.
Referenced by getEmptyDPValueRange().
MarkedInstr
Instruction* llvm::DPMarker::MarkedInstr = nullptr
Link back to the Instruction that owns this marker.
Can be null during operations that move a marker from one instruction to another.
Definition at line 371 of file DebugProgramInstruction.h.
Referenced by llvm::BasicBlock::createMarker(), eraseFromParent(), getNextNode(), llvm::DPValue::getParent(), getParent(), removeFromParent(), removeMarker(), rewriteDebugUsers(), and llvm::BasicBlock::validateDbgValues().
StoredDPValues
simple_ilist<DPValue> llvm::DPMarker::StoredDPValues
List of DPValues, each recording a single variable assignment, the equivalent of a dbg.value intrinsic.
There is a one-to-one relationship between each dbg.value in a block and each DPValue once the representation has been converted, and the ordering of DPValues is meaningful in the same was a dbg.values.
Definition at line 378 of file DebugProgramInstruction.h.
Referenced by absorbDebugValues(), cloneDebugInfoFrom(), dropDPValues(), dropOneDPValue(), empty(), llvm::Instruction::getDbgReinsertionPosition(), getDbgValueRange(), getEmptyDPValueRange(), insertDPValue(), insertDPValueAfter(), llvm::BasicBlock::reinsertInstInDPValues(), llvm::DPValue::removeFromParent(), and removeMarker().
The documentation for this class was generated from the following files:
include/llvm/IR/DebugProgramInstruction.h
lib/IR/AsmWriter.cpp
lib/IR/DebugProgramInstruction.cpp