LLVM: llvm::orc::OrcMips32_Base Class Reference
llvm::orc::OrcMips32_Base Class Reference
#include "llvm/ExecutionEngine/Orc/OrcABISupport.h"
Static Public Member Functions
static void writeTrampolines (char *TrampolineBlockWorkingMem, ExecutorAddr TrampolineBlockTargetAddress, ExecutorAddr ResolverAddr, unsigned NumTrampolines)
Write the requested number of trampolines into the given memory, which must be big enough to hold 1 pointer, plus NumTrampolines trampolines.
static void writeResolverCode (char *ResolverBlockWorkingMem, ExecutorAddr ResolverBlockTargetAddress, ExecutorAddr ReentryFnAddr, ExecutorAddr ReentryCtxAddr, bool isBigEndian)
Write the resolver code into the given memory.
static void writeIndirectStubsBlock (char *StubsBlockWorkingMem, ExecutorAddr StubsBlockTargetAddress, ExecutorAddr PointersBlockTargetAddress, unsigned NumStubs)
Write NumStubs indirect stubs to working memory at StubsBlockWorkingMem.
Static Public Attributes
static constexpr unsigned PointerSize = 4
static constexpr unsigned TrampolineSize = 20
static constexpr unsigned StubSize = 8
static constexpr unsigned StubToPointerMaxDisplacement = 1 << 31
static constexpr unsigned ResolverCodeSize = 0xfc
Detailed Description
Definition at line 239 of file OrcABISupport.h.
Member Function Documentation
writeIndirectStubsBlock()
void llvm::orc::OrcMips32_Base::writeIndirectStubsBlock (char * StubsBlockWorkingMem, ExecutorAddr StubsBlockTargetAddress, ExecutorAddr PointersBlockTargetAddress, unsigned NumStubs) static
Write NumStubs indirect stubs to working memory at StubsBlockWorkingMem.
Stubs will be written as if linked at StubsBlockTargetAddress, with the Nth stub using the Nth pointer in memory starting at PointersBlockTargetAddress.
Definition at line 644 of file OrcABISupport.cpp.
References assert(), llvm::orc::ExecutorAddr::getValue(), and I.
writeResolverCode()
void llvm::orc::OrcMips32_Base::writeResolverCode (char * ResolverBlockWorkingMem, ExecutorAddr ResolverBlockTargetAddress, ExecutorAddr ReentryFnAddr, ExecutorAddr ReentryCtxAddr, bool isBigEndian) static
Write the resolver code into the given memory.
The user is responsible for allocating the memory and setting permissions.
ReentryFnAddr should be the address of a function whose signature matches void* (*)(void *TrampolineAddr, void *ReentryCtxAddr). The ReentryCtxAddr argument of writeResolverCode will be passed as the second argument to the function at ReentryFnAddr.
Definition at line 513 of file OrcABISupport.cpp.
References llvm::orc::ExecutorAddr::getValue(), and isBigEndian().
Referenced by llvm::orc::OrcMips32Le::writeResolverCode(), and llvm::orc::OrcMips32Be::writeResolverCode().
writeTrampolines()
void llvm::orc::OrcMips32_Base::writeTrampolines (char * TrampolineBlockWorkingMem, ExecutorAddr TrampolineBlockTargetAddress, ExecutorAddr ResolverAddr, unsigned NumTrampolines) static
Write the requested number of trampolines into the given memory, which must be big enough to hold 1 pointer, plus NumTrampolines trampolines.
Definition at line 619 of file OrcABISupport.cpp.
References assert(), llvm::orc::ExecutorAddr::getValue(), and I.
Member Data Documentation
PointerSize
constexpr unsigned llvm::orc::OrcMips32_Base::PointerSize = 4 static constexpr
Definition at line 241 of file OrcABISupport.h.
ResolverCodeSize
constexpr unsigned llvm::orc::OrcMips32_Base::ResolverCodeSize = 0xfc static constexpr
Definition at line 245 of file OrcABISupport.h.
StubSize
constexpr unsigned llvm::orc::OrcMips32_Base::StubSize = 8 static constexpr
Definition at line 243 of file OrcABISupport.h.
StubToPointerMaxDisplacement
constexpr unsigned llvm::orc::OrcMips32_Base::StubToPointerMaxDisplacement = 1 << 31 static constexpr
Definition at line 244 of file OrcABISupport.h.
TrampolineSize
constexpr unsigned llvm::orc::OrcMips32_Base::TrampolineSize = 20 static constexpr
Definition at line 242 of file OrcABISupport.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/OrcABISupport.h
lib/ExecutionEngine/Orc/OrcABISupport.cpp