LLVM: llvm::LoongArchMachineFunctionInfo Class Reference
llvm::LoongArchMachineFunctionInfo Class Reference
LoongArchMachineFunctionInfo - This class is derived from MachineFunctionInfo and contains private LoongArch-specific information for each MachineFunction.
#include "Target/LoongArch/LoongArchMachineFunctionInfo.h"
Public Member Functions
LoongArchMachineFunctionInfo (const Function &F, const TargetSubtargetInfo *STI)
MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const override
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
int getVarArgsFrameIndex () const
void setVarArgsFrameIndex (int Index)
unsigned getVarArgsSaveSize () const
void setVarArgsSaveSize (int Size)
unsigned getCalleeSavedStackSize () const
void setCalleeSavedStackSize (unsigned Size)
int getBranchRelaxationSpillFrameIndex ()
void setBranchRelaxationSpillFrameIndex (int Index)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
virtual MachineFunctionInfo * clone (BumpPtrAllocator &Allocator, MachineFunction &DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > &Src2DstMBB) const
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
Additional Inherited Members
Static Public Member Functions inherited from llvm::MachineFunctionInfo
template<typename FuncInfoTy , typename SubtargetTy = TargetSubtargetInfo>
static FuncInfoTy * create (BumpPtrAllocator &Allocator, const Function &F, const SubtargetTy *STI)
Factory function: default behavior is to call new using the supplied allocator.
template<typename Ty >
static Ty * create (BumpPtrAllocator &Allocator, const Ty &MFI)
Detailed Description
LoongArchMachineFunctionInfo - This class is derived from MachineFunctionInfo and contains private LoongArch-specific information for each MachineFunction.
Definition at line 25 of file LoongArchMachineFunctionInfo.h.
Constructor & Destructor Documentation
LoongArchMachineFunctionInfo()
llvm::LoongArchMachineFunctionInfo::LoongArchMachineFunctionInfo (const Function & F, const TargetSubtargetInfo * STI) inline
Definition at line 40 of file LoongArchMachineFunctionInfo.h.
Member Function Documentation
clone()
MachineFunctionInfo * llvm::LoongArchMachineFunctionInfo::clone (BumpPtrAllocator & Allocator, MachineFunction & DestMF, const DenseMap< MachineBasicBlock *, MachineBasicBlock * > & Src2DstMBB) const inline override virtual
Make a functionally equivalent copy of this MachineFunctionInfo in MF.
This requires remapping MachineBasicBlock references from the original parent to values in the new function. Targets may assume that virtual register and frame index values are preserved in the new function.
Reimplemented from llvm::MachineFunctionInfo.
Definition at line 44 of file LoongArchMachineFunctionInfo.h.
References llvm::MachineFunction::cloneInfo().
getBranchRelaxationSpillFrameIndex()
int llvm::LoongArchMachineFunctionInfo::getBranchRelaxationSpillFrameIndex () inline
Definition at line 59 of file LoongArchMachineFunctionInfo.h.
Referenced by llvm::LoongArchInstrInfo::insertIndirectBranch(), and llvm::LoongArchFrameLowering::processFunctionBeforeFrameFinalized().
getCalleeSavedStackSize()
unsigned llvm::LoongArchMachineFunctionInfo::getCalleeSavedStackSize () const inline
Definition at line 56 of file LoongArchMachineFunctionInfo.h.
getVarArgsFrameIndex()
int llvm::LoongArchMachineFunctionInfo::getVarArgsFrameIndex () const inline
Definition at line 50 of file LoongArchMachineFunctionInfo.h.
getVarArgsSaveSize()
unsigned llvm::LoongArchMachineFunctionInfo::getVarArgsSaveSize () const inline
Definition at line 53 of file LoongArchMachineFunctionInfo.h.
setBranchRelaxationSpillFrameIndex()
void llvm::LoongArchMachineFunctionInfo::setBranchRelaxationSpillFrameIndex (int Index) inline
Definition at line 62 of file LoongArchMachineFunctionInfo.h.
Referenced by llvm::LoongArchFrameLowering::processFunctionBeforeFrameFinalized().
setCalleeSavedStackSize()
void llvm::LoongArchMachineFunctionInfo::setCalleeSavedStackSize (unsigned Size) inline
Definition at line 57 of file LoongArchMachineFunctionInfo.h.
References Size.
setVarArgsFrameIndex()
void llvm::LoongArchMachineFunctionInfo::setVarArgsFrameIndex (int Index) inline
Definition at line 51 of file LoongArchMachineFunctionInfo.h.
setVarArgsSaveSize()
void llvm::LoongArchMachineFunctionInfo::setVarArgsSaveSize (int Size) inline
Definition at line 54 of file LoongArchMachineFunctionInfo.h.
References Size.
The documentation for this class was generated from the following file:
lib/Target/LoongArch/LoongArchMachineFunctionInfo.h