LLVM: llvm::dwarf_linker::IndexedValuesMap< T > Class Template Reference
llvm::dwarf_linker::IndexedValuesMap< T > Class Template Reference
This class stores values sequentually and assigns index to the each value.
#include "llvm/DWARFLinker/IndexedValuesMap.h"
Public Member Functions
uint64_t getValueIndex (T Value)
const SmallVector< T > & getValues () const
void clear ()
bool empty ()
Protected Types
using ValueToIndexMapTy = DenseMap< T, uint64_t >
Protected Attributes
ValueToIndexMapTy ValueToIndexMap
SmallVector< T > Values
Detailed Description
template<typename T>
class llvm::dwarf_linker::IndexedValuesMap< T >
This class stores values sequentually and assigns index to the each value.
Definition at line 21 of file IndexedValuesMap.h.
Member Typedef Documentation
ValueToIndexMapTy
template<typename T > using llvm::dwarf_linker::IndexedValuesMap< T >::ValueToIndexMapTy = DenseMap<T, uint64_t> protected
Definition at line 42 of file IndexedValuesMap.h.
Member Function Documentation
clear()
template<typename T > void llvm::dwarf_linker::IndexedValuesMap< T >::clear () inline
Definition at line 34 of file IndexedValuesMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::dwarf_linker::IndexedValuesMap< T >::Values, and llvm::dwarf_linker::IndexedValuesMap< T >::ValueToIndexMap.
Referenced by llvm::dwarf_linker::parallel::CompileUnit::maybeResetToLoadedStage().
empty()
template<typename T > bool llvm::dwarf_linker::IndexedValuesMap< T >::empty () inline
Definition at line 39 of file IndexedValuesMap.h.
References llvm::dwarf_linker::IndexedValuesMap< T >::Values.
getValueIndex()
template<typename T > uint64_t llvm::dwarf_linker::IndexedValuesMap< T >::getValueIndex (T Value) inline
Definition at line 23 of file IndexedValuesMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::dwarf_linker::IndexedValuesMap< T >::Values, and llvm::dwarf_linker::IndexedValuesMap< T >::ValueToIndexMap.
Referenced by llvm::dwarf_linker::parallel::CompileUnit::getDebugAddrIndex().
getValues()
template<typename T > const SmallVector< T > & llvm::dwarf_linker::IndexedValuesMap< T >::getValues () const inline
Definition at line 32 of file IndexedValuesMap.h.
References llvm::dwarf_linker::IndexedValuesMap< T >::Values.
Referenced by llvm::dwarf_linker::classic::DWARFLinker::link().
Member Data Documentation
Values
template<typename T > SmallVector<T> llvm::dwarf_linker::IndexedValuesMap< T >::Values protected
Definition at line 44 of file IndexedValuesMap.h.
Referenced by llvm::dwarf_linker::IndexedValuesMap< T >::clear(), llvm::dwarf_linker::IndexedValuesMap< T >::empty(), llvm::dwarf_linker::IndexedValuesMap< T >::getValueIndex(), and llvm::dwarf_linker::IndexedValuesMap< T >::getValues().
ValueToIndexMap
template<typename T > ValueToIndexMapTy llvm::dwarf_linker::IndexedValuesMap< T >::ValueToIndexMap protected
Definition at line 43 of file IndexedValuesMap.h.
Referenced by llvm::dwarf_linker::IndexedValuesMap< T >::clear(), and llvm::dwarf_linker::IndexedValuesMap< T >::getValueIndex().
The documentation for this class was generated from the following file:
include/llvm/DWARFLinker/IndexedValuesMap.h