LLVM: llvm::Hexagon::PacketIterator Class Reference
llvm::Hexagon::PacketIterator Class Reference
#include "Target/Hexagon/MCTargetDesc/HexagonMCInstrInfo.h"
Public Member Functions
PacketIterator (MCInstrInfo const &MCII, MCInst const &Inst)
PacketIterator (MCInstrInfo const &MCII, MCInst const &Inst, std::nullptr_t)
PacketIterator & operator++ ()
MCInst const & operator* () const
bool operator== (PacketIterator const &Other) const
Public Member Functions inherited from llvm::iterator_facade_base< PacketIterator, std::forward_iterator_tag, const MCInst >
PacketIterator operator+ (std::ptrdiff_t n) const
PacketIterator operator- (std::ptrdiff_t n) const
PacketIterator & operator++ ()
PacketIterator operator++ (int)
PacketIterator & operator-- ()
PacketIterator operator-- (int)
bool operator!= (const PacketIterator &RHS) const
bool operator> (const PacketIterator &RHS) const
bool operator<= (const PacketIterator &RHS) const
bool operator>= (const PacketIterator &RHS) const
PointerProxy operator-> () const
ReferenceProxy operator[] (std::ptrdiff_t n) const
Additional Inherited Members
Public Types inherited from llvm::iterator_facade_base< PacketIterator, std::forward_iterator_tag, const MCInst >
using iterator_category = std::forward_iterator_tag
using value_type = const MCInst
using difference_type = std::ptrdiff_t
using pointer = const MCInst *
using reference = const MCInst &
Protected Types inherited from llvm::iterator_facade_base< PacketIterator, std::forward_iterator_tag, const MCInst >
enum
Detailed Description
Definition at line 45 of file HexagonMCInstrInfo.h.
Constructor & Destructor Documentation
PacketIterator() [1/2]
Hexagon::PacketIterator::PacketIterator (MCInstrInfo const & MCII, MCInst const & Inst)
Definition at line 39 of file HexagonMCInstrInfo.cpp.
PacketIterator() [2/2]
Hexagon::PacketIterator::PacketIterator (MCInstrInfo const & MCII, MCInst const & Inst, std::nullptr_t)
Definition at line 45 of file HexagonMCInstrInfo.cpp.
Member Function Documentation
operator*()
MCInst const & Hexagon::PacketIterator::operator* () const
Definition at line 71 of file HexagonMCInstrInfo.cpp.
operator++()
Hexagon::PacketIterator & Hexagon::PacketIterator::operator++ ()
Definition at line 50 of file HexagonMCInstrInfo.cpp.
References llvm::MCInst::begin(), llvm::MCInst::end(), and llvm::HexagonMCInstrInfo::isDuplex().
operator==()
bool Hexagon::PacketIterator::operator== (PacketIterator const & Other) const
Definition at line 77 of file HexagonMCInstrInfo.cpp.
References llvm::Other.
The documentation for this class was generated from the following files:
lib/Target/Hexagon/MCTargetDesc/HexagonMCInstrInfo.h
lib/Target/Hexagon/MCTargetDesc/HexagonMCInstrInfo.cpp