LLVM: llvm::orc::SymbolsNotFound Class Reference
llvm::orc::SymbolsNotFound Class Reference
Used to notify clients when symbols can not be found during a lookup.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
SymbolsNotFound (std::shared_ptr< SymbolStringPool > SSP, SymbolNameSet Symbols)
SymbolsNotFound (std::shared_ptr< SymbolStringPool > SSP, SymbolNameVector Symbols)
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
void log (raw_ostream &OS) const override
Print an error message to an output stream.
std::shared_ptr< SymbolStringPool > getSymbolStringPool ()
const SymbolNameVector & getSymbols () const
Public Member Functions inherited from llvm::ErrorInfo< SymbolsNotFound >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual void log (raw_ostream &OS) const =0
Print an error message to an output stream.
virtual std::string message () const
Return the error message as a string.
virtual std::error_code convertToErrorCode () const =0
Convert this error to a std::error_code.
virtual const void * dynamicClassID () const =0
virtual bool isA (const void *const ClassID) const
template<typename ErrorInfoT >
bool isA () const
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::ErrorInfo< SymbolsNotFound >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Detailed Description
Used to notify clients when symbols can not be found during a lookup.
Definition at line 440 of file Core.h.
Constructor & Destructor Documentation
SymbolsNotFound() [1/2]
llvm::orc::SymbolsNotFound::SymbolsNotFound (std::shared_ptr< SymbolStringPool > SSP, SymbolNameSet Symbols)
Definition at line 106 of file Core.cpp.
References assert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::empty(), and Sym.
SymbolsNotFound() [2/2]
llvm::orc::SymbolsNotFound::SymbolsNotFound (std::shared_ptr< SymbolStringPool > SSP, SymbolNameVector Symbols)
Definition at line 114 of file Core.cpp.
References assert().
Member Function Documentation
convertToErrorCode()
std::error_code llvm::orc::SymbolsNotFound::convertToErrorCode () const override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 120 of file Core.cpp.
References llvm::orc::orcError(), and llvm::orc::UnknownORCError.
getSymbols()
const SymbolNameVector & llvm::orc::SymbolsNotFound::getSymbols () const inline
Definition at line 450 of file Core.h.
getSymbolStringPool()
std::shared_ptr< SymbolStringPool > llvm::orc::SymbolsNotFound::getSymbolStringPool () inline
Definition at line 449 of file Core.h.
log()
void llvm::orc::SymbolsNotFound::log (raw_ostream & OS) const override virtual
Print an error message to an output stream.
Implements llvm::ErrorInfoBase.
Definition at line 124 of file Core.cpp.
References OS.
Member Data Documentation
ID
char llvm::orc::SymbolsNotFound::ID = 0 static
Definition at line 442 of file Core.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp