LLVM: llvm::BitcodeAnalyzer Class Reference
llvm::BitcodeAnalyzer Class Reference
#include "llvm/Bitcode/BitcodeAnalyzer.h"
Public Member Functions
BitcodeAnalyzer (StringRef Buffer, std::optional< StringRef > BlockInfoBuffer=std::nullopt)
Error analyze (std::optional< BCDumpOptions > O=std::nullopt, std::optional< StringRef > CheckHash=std::nullopt)
Analyze the bitcode file.
void printStats (BCDumpOptions O, std::optional< StringRef > Filename=std::nullopt)
Print stats about the bitcode file.
Detailed Description
Definition at line 52 of file BitcodeAnalyzer.h.
Constructor & Destructor Documentation
BitcodeAnalyzer()
BitcodeAnalyzer::BitcodeAnalyzer (StringRef Buffer, std::optional< StringRef > BlockInfoBuffer = std::nullopt)
Definition at line 557 of file BitcodeAnalyzer.cpp.
Member Function Documentation
analyze()
Error BitcodeAnalyzer::analyze (std::optional< BCDumpOptions > O = std::nullopt, std::optional< StringRef > CheckHash = std::nullopt)
Analyze the bitcode file.
Definition at line 564 of file BitcodeAnalyzer.cpp.
References analyzeHeader(), llvm::BitstreamCursor::AtEndOfStream(), llvm::bitc::BLOCKINFO_BLOCK_ID, E, llvm::bitc::ENTER_SUBBLOCK, llvm::Expected< T >::get(), llvm::BitstreamCursor::ReadBlockInfoBlock(), llvm::BitstreamCursor::ReadCode(), llvm::BitstreamCursor::ReadSubBlockID(), reportError(), llvm::BitstreamCursor::setBlockInfo(), llvm::BitstreamCursor::SkipBlock(), llvm::Error::success(), and llvm::Expected< T >::takeError().
printStats()
void BitcodeAnalyzer::printStats (BCDumpOptions O, std::optional< StringRef > Filename = std::nullopt)
Print stats about the bitcode file.
Definition at line 625 of file BitcodeAnalyzer.cpp.
References llvm::ClangSerializedASTBitstream, llvm::ClangSerializedDiagnosticsBitstream, llvm::format(), llvm::BitstreamCursor::getBitcodeBytes(), GetBlockName(), GetCodeName(), llvm::LLVMBitstreamRemarks, llvm::LLVMIRBitstream, printSize(), llvm::ArrayRef< T >::size(), llvm::stable_sort(), Stats, and llvm::UnknownBitstream.
The documentation for this class was generated from the following files:
include/llvm/Bitcode/BitcodeAnalyzer.h
lib/Bitcode/Reader/BitcodeAnalyzer.cpp