LLVM: llvm::InterleavedAccessPass Class Reference
llvm::InterleavedAccessPass Class Reference
#include "llvm/CodeGen/InterleavedAccess.h"
Public Member Functions
InterleavedAccessPass (const TargetMachine *TM)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &FAM)
Public Member Functions inherited from llvm::PassInfoMixin< InterleavedAccessPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< InterleavedAccessPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 24 of file InterleavedAccess.h.
Constructor & Destructor Documentation
InterleavedAccessPass()
llvm::InterleavedAccessPass::InterleavedAccessPass (const TargetMachine * TM) inline explicit
Definition at line 28 of file InterleavedAccess.h.
References TM.
Member Function Documentation
run()
PreservedAnalyses InterleavedAccessPass::run (Function & F, FunctionAnalysisManager & FAM)
Definition at line 159 of file InterleavedAccessPass.cpp.
References llvm::PreservedAnalyses::all(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::TargetMachine::getSubtargetImpl(), llvm::TargetSubtargetInfo::getTargetLowering(), and llvm::PreservedAnalyses::preserveSet().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/InterleavedAccess.h
lib/CodeGen/InterleavedAccessPass.cpp