LLVM: llvm::orc::DebugInfoPreservationPlugin Class Reference
llvm::orc::DebugInfoPreservationPlugin Class Reference
#include "llvm/ExecutionEngine/Orc/Debugging/DebugInfoSupport.h"
Public Member Functions
void modifyPassConfig (MaterializationResponsibility &MR, jitlink::LinkGraph &LG, jitlink::PassConfiguration &PassConfig) override
Error notifyRemovingResources (JITDylib &JD, ResourceKey K) override
Error notifyFailed (MaterializationResponsibility &MR) override
void notifyTransferringResources (JITDylib &JD, ResourceKey DstKey, ResourceKey SrcKey) override
Public Member Functions inherited from llvm::orc::ObjectLinkingLayer::Plugin
virtual ~Plugin ()
virtual void modifyPassConfig (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::PassConfiguration &Config)
virtual void notifyMaterializing (MaterializationResponsibility &MR, jitlink::LinkGraph &G, jitlink::JITLinkContext &Ctx, MemoryBufferRef InputObject)
virtual void notifyLoaded (MaterializationResponsibility &MR)
virtual Error notifyEmitted (MaterializationResponsibility &MR)
virtual Error notifyFailed (MaterializationResponsibility &MR)=0
virtual Error notifyRemovingResources (JITDylib &JD, ResourceKey K)=0
virtual void notifyTransferringResources (JITDylib &JD, ResourceKey DstKey, ResourceKey SrcKey)=0
virtual SyntheticSymbolDependenciesMap getSyntheticSymbolDependencies (MaterializationResponsibility &MR)
Return any dependencies that synthetic symbols (e.g.
Static Public Member Functions
static Expected< std::unique_ptr< DebugInfoPreservationPlugin > > Create ()
Additional Inherited Members
Public Types inherited from llvm::orc::ObjectLinkingLayer::Plugin
using JITLinkSymbolSet = DenseSet< jitlink::Symbol * >
using SyntheticSymbolDependenciesMap = DenseMap< SymbolStringPtr, JITLinkSymbolSet >
Detailed Description
Definition at line 32 of file DebugInfoSupport.h.
Member Function Documentation
Create()
static Expected< std::unique_ptr< DebugInfoPreservationPlugin > > llvm::orc::DebugInfoPreservationPlugin::Create () inline static
Definition at line 53 of file DebugInfoSupport.h.
modifyPassConfig()
void llvm::orc::DebugInfoPreservationPlugin::modifyPassConfig (MaterializationResponsibility & MR, jitlink::LinkGraph & LG, jitlink::PassConfiguration & PassConfig) inline override virtual
Reimplemented from llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 34 of file DebugInfoSupport.h.
References llvm::jitlink::PassConfiguration::PrePrunePasses, and llvm::orc::preserveDebugSections().
notifyFailed()
Error llvm::orc::DebugInfoPreservationPlugin::notifyFailed (MaterializationResponsibility & MR) inline override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 44 of file DebugInfoSupport.h.
References llvm::Error::success().
notifyRemovingResources()
Error llvm::orc::DebugInfoPreservationPlugin::notifyRemovingResources (JITDylib & JD, ResourceKey K) inline override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 40 of file DebugInfoSupport.h.
References llvm::Error::success().
notifyTransferringResources()
void llvm::orc::DebugInfoPreservationPlugin::notifyTransferringResources (JITDylib & JD, ResourceKey DstKey, ResourceKey SrcKey) inline override virtual
Implements llvm::orc::ObjectLinkingLayer::Plugin.
Definition at line 48 of file DebugInfoSupport.h.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Debugging/DebugInfoSupport.h