LLVM: llvm::pdb::NativeSession Class Reference
llvm::pdb::NativeSession Class Reference
#include "llvm/DebugInfo/PDB/Native/NativeSession.h"
Public Member Functions
NativeSession (std::unique_ptr< PDBFile > PdbFile, std::unique_ptr< BumpPtrAllocator > Allocator)
~NativeSession () override
uint64_t getLoadAddress () const override
bool setLoadAddress (uint64_t Address) override
std::unique_ptr< PDBSymbolExe > getGlobalScope () override
std::unique_ptr< PDBSymbol > getSymbolById (SymIndexId SymbolId) const override
bool addressForVA (uint64_t VA, uint32_t &Section, uint32_t &Offset) const override
bool addressForRVA (uint32_t RVA, uint32_t &Section, uint32_t &Offset) const override
std::unique_ptr< PDBSymbol > findSymbolByAddress (uint64_t Address, PDB_SymType Type) override
std::unique_ptr< PDBSymbol > findSymbolByRVA (uint32_t RVA, PDB_SymType Type) override
std::unique_ptr< PDBSymbol > findSymbolBySectOffset (uint32_t Sect, uint32_t Offset, PDB_SymType Type) override
std::unique_ptr< IPDBEnumLineNumbers > findLineNumbers (const PDBSymbolCompiland &Compiland, const IPDBSourceFile &File) const override
std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersByAddress (uint64_t Address, uint32_t Length) const override
std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersByRVA (uint32_t RVA, uint32_t Length) const override
std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersBySectOffset (uint32_t Section, uint32_t Offset, uint32_t Length) const override
std::unique_ptr< IPDBEnumSourceFiles > findSourceFiles (const PDBSymbolCompiland *Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override
std::unique_ptr< IPDBSourceFile > findOneSourceFile (const PDBSymbolCompiland *Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override
std::unique_ptr< IPDBEnumChildren< PDBSymbolCompiland > > findCompilandsForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override
std::unique_ptr< PDBSymbolCompiland > findOneCompilandForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override
std::unique_ptr< IPDBEnumSourceFiles > getAllSourceFiles () const override
std::unique_ptr< IPDBEnumSourceFiles > getSourceFilesForCompiland (const PDBSymbolCompiland &Compiland) const override
std::unique_ptr< IPDBSourceFile > getSourceFileById (uint32_t FileId) const override
std::unique_ptr< IPDBEnumDataStreams > getDebugStreams () const override
std::unique_ptr< IPDBEnumTables > getEnumTables () const override
std::unique_ptr< IPDBEnumInjectedSources > getInjectedSources () const override
std::unique_ptr< IPDBEnumSectionContribs > getSectionContribs () const override
std::unique_ptr< IPDBEnumFrameData > getFrameData () const override
PDBFile & getPDBFile ()
const PDBFile & getPDBFile () const
NativeExeSymbol & getNativeGlobalScope () const
SymbolCache & getSymbolCache ()
const SymbolCache & getSymbolCache () const
uint32_t getRVAFromSectOffset (uint32_t Section, uint32_t Offset) const
uint64_t getVAFromSectOffset (uint32_t Section, uint32_t Offset) const
bool moduleIndexForVA (uint64_t VA, uint16_t &ModuleIndex) const
bool moduleIndexForSectOffset (uint32_t Sect, uint32_t Offset, uint16_t &ModuleIndex) const
Expected< ModuleDebugStreamRef > getModuleDebugStream (uint32_t Index) const
Public Member Functions inherited from llvm::pdb::IPDBSession
virtual ~IPDBSession ()
virtual uint64_t getLoadAddress () const =0
virtual bool setLoadAddress (uint64_t Address)=0
virtual std::unique_ptr< PDBSymbolExe > getGlobalScope ()=0
virtual std::unique_ptr< PDBSymbol > getSymbolById (SymIndexId SymbolId) const =0
virtual bool addressForVA (uint64_t VA, uint32_t &Section, uint32_t &Offset) const =0
virtual bool addressForRVA (uint32_t RVA, uint32_t &Section, uint32_t &Offset) const =0
template<typename T >
std::unique_ptr< T > getConcreteSymbolById (SymIndexId SymbolId) const
virtual std::unique_ptr< PDBSymbol > findSymbolByAddress (uint64_t Address, PDB_SymType Type)=0
virtual std::unique_ptr< PDBSymbol > findSymbolByRVA (uint32_t RVA, PDB_SymType Type)=0
virtual std::unique_ptr< PDBSymbol > findSymbolBySectOffset (uint32_t Sect, uint32_t Offset, PDB_SymType Type)=0
virtual std::unique_ptr< IPDBEnumLineNumbers > findLineNumbers (const PDBSymbolCompiland &Compiland, const IPDBSourceFile &File) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersByAddress (uint64_t Address, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersByRVA (uint32_t RVA, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumLineNumbers > findLineNumbersBySectOffset (uint32_t Section, uint32_t Offset, uint32_t Length) const =0
virtual std::unique_ptr< IPDBEnumSourceFiles > findSourceFiles (const PDBSymbolCompiland *Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< IPDBSourceFile > findOneSourceFile (const PDBSymbolCompiland *Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< IPDBEnumChildren< PDBSymbolCompiland > > findCompilandsForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< PDBSymbolCompiland > findOneCompilandForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const =0
virtual std::unique_ptr< IPDBEnumSourceFiles > getAllSourceFiles () const =0
virtual std::unique_ptr< IPDBEnumSourceFiles > getSourceFilesForCompiland (const PDBSymbolCompiland &Compiland) const =0
virtual std::unique_ptr< IPDBSourceFile > getSourceFileById (uint32_t FileId) const =0
virtual std::unique_ptr< IPDBEnumDataStreams > getDebugStreams () const =0
virtual std::unique_ptr< IPDBEnumTables > getEnumTables () const =0
virtual std::unique_ptr< IPDBEnumInjectedSources > getInjectedSources () const =0
virtual std::unique_ptr< IPDBEnumSectionContribs > getSectionContribs () const =0
virtual std::unique_ptr< IPDBEnumFrameData > getFrameData () const =0
Static Public Member Functions
static Error createFromPdb (std::unique_ptr< MemoryBuffer > MB, std::unique_ptr< IPDBSession > &Session)
static Error createFromPdbPath (StringRef PdbPath, std::unique_ptr< IPDBSession > &Session)
static Error createFromExe (StringRef Path, std::unique_ptr< IPDBSession > &Session)
static Expected< std::string > searchForPdb (const PdbSearchOptions &Opts)
Detailed Description
Definition at line 32 of file NativeSession.h.
Constructor & Destructor Documentation
NativeSession()
NativeSession::NativeSession (std::unique_ptr< PDBFile > PdbFile, std::unique_ptr< BumpPtrAllocator > Allocator)
Definition at line 66 of file NativeSession.cpp.
References Allocator.
~NativeSession()
NativeSession::~NativeSession () override default
Member Function Documentation
addressForRVA()
bool NativeSession::addressForRVA (uint32_t RVA, uint32_t & Section, uint32_t & Offset) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 227 of file NativeSession.cpp.
References llvm::pdb::Offset, and llvm::size().
Referenced by addressForVA(), and findSymbolByRVA().
addressForVA()
bool NativeSession::addressForVA (uint64_t VA, uint32_t & Section, uint32_t & Offset) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 221 of file NativeSession.cpp.
References addressForRVA(), getLoadAddress(), and llvm::pdb::Offset.
Referenced by llvm::pdb::NativeInlineSiteSymbol::findInlineeLinesByVA(), llvm::pdb::SymbolCache::findLineNumbersByVA(), and findSymbolByAddress().
createFromExe()
Error NativeSession::createFromExe (StringRef Path, std::unique_ptr< IPDBSession > & Session) static
Definition at line 151 of file NativeSession.cpp.
References Allocator, llvm::Expected< T >::get(), getPdbPathFromExe(), llvm::identify_magic(), loadPdbFile(), llvm::msf::Magic, llvm::file_magic::pdb, llvm::Error::success(), and llvm::Expected< T >::takeError().
createFromPdb()
Error NativeSession::createFromPdb (std::unique_ptr< MemoryBuffer > MB, std::unique_ptr< IPDBSession > & Session) static
Definition at line 73 of file NativeSession.cpp.
References Allocator, llvm::little, llvm::pdb::Path, and llvm::Error::success().
createFromPdbPath()
Error NativeSession::createFromPdbPath (StringRef PdbPath, std::unique_ptr< IPDBSession > & Session) static
Definition at line 120 of file NativeSession.cpp.
References Allocator, loadPdbFile(), and llvm::Error::success().
Referenced by llvm::pdb::loadDataForEXE(), and llvm::pdb::loadDataForPDB().
findCompilandsForSourceFile()
std::unique_ptr< IPDBEnumChildren< PDBSymbolCompiland > > NativeSession::findCompilandsForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 313 of file NativeSession.cpp.
findLineNumbers()
std::unique_ptr< IPDBEnumLineNumbers > NativeSession::findLineNumbers (const PDBSymbolCompiland & Compiland, const IPDBSourceFile & File) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 275 of file NativeSession.cpp.
findLineNumbersByAddress()
std::unique_ptr< IPDBEnumLineNumbers > NativeSession::findLineNumbersByAddress (uint64_t Address, uint32_t Length) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 281 of file NativeSession.cpp.
References llvm::pdb::Address, llvm::pdb::SymbolCache::findLineNumbersByVA(), and llvm::Length.
findLineNumbersByRVA()
std::unique_ptr< IPDBEnumLineNumbers > NativeSession::findLineNumbersByRVA (uint32_t RVA, uint32_t Length) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 287 of file NativeSession.cpp.
References llvm::pdb::SymbolCache::findLineNumbersByVA(), getLoadAddress(), and llvm::Length.
findLineNumbersBySectOffset()
std::unique_ptr< IPDBEnumLineNumbers > NativeSession::findLineNumbersBySectOffset (uint32_t Section, uint32_t Offset, uint32_t Length) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 292 of file NativeSession.cpp.
References llvm::pdb::SymbolCache::findLineNumbersByVA(), getVAFromSectOffset(), llvm::Length, and llvm::pdb::Offset.
findOneCompilandForSourceFile()
std::unique_ptr< PDBSymbolCompiland > NativeSession::findOneCompilandForSourceFile (llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 319 of file NativeSession.cpp.
findOneSourceFile()
std::unique_ptr< IPDBSourceFile > NativeSession::findOneSourceFile (const PDBSymbolCompiland * Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 306 of file NativeSession.cpp.
findSourceFiles()
std::unique_ptr< IPDBEnumSourceFiles > NativeSession::findSourceFiles (const PDBSymbolCompiland * Compiland, llvm::StringRef Pattern, PDB_NameSearchFlags Flags) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 299 of file NativeSession.cpp.
findSymbolByAddress()
std::unique_ptr< PDBSymbol > NativeSession::findSymbolByAddress (uint64_t Address, PDB_SymType Type) override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 250 of file NativeSession.cpp.
References llvm::pdb::Address, addressForVA(), findSymbolBySectOffset(), and llvm::pdb::Offset.
findSymbolByRVA()
std::unique_ptr< PDBSymbol > NativeSession::findSymbolByRVA (uint32_t RVA, PDB_SymType Type) override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 257 of file NativeSession.cpp.
References addressForRVA(), findSymbolBySectOffset(), and llvm::pdb::Offset.
findSymbolBySectOffset()
std::unique_ptr< PDBSymbol > NativeSession::findSymbolBySectOffset (uint32_t Sect, uint32_t Offset, PDB_SymType Type) override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 266 of file NativeSession.cpp.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::empty(), llvm::pdb::SymbolCache::findSymbolBySectOffset(), and llvm::pdb::Offset.
Referenced by findSymbolByAddress(), and findSymbolByRVA().
getAllSourceFiles()
std::unique_ptr< IPDBEnumSourceFiles > NativeSession::getAllSourceFiles () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 324 of file NativeSession.cpp.
getDebugStreams()
std::unique_ptr< IPDBEnumDataStreams > NativeSession::getDebugStreams () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 338 of file NativeSession.cpp.
getEnumTables()
std::unique_ptr< IPDBEnumTables > NativeSession::getEnumTables () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 342 of file NativeSession.cpp.
getFrameData()
std::unique_ptr< IPDBEnumFrameData > NativeSession::getFrameData () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 367 of file NativeSession.cpp.
getGlobalScope()
std::unique_ptr< PDBSymbolExe > NativeSession::getGlobalScope () override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 212 of file NativeSession.cpp.
References getNativeGlobalScope().
getInjectedSources()
std::unique_ptr< IPDBEnumInjectedSources > NativeSession::getInjectedSources () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 347 of file NativeSession.cpp.
References llvm::consumeError().
getLoadAddress()
uint64_t NativeSession::getLoadAddress () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 205 of file NativeSession.cpp.
Referenced by addressForVA(), and findLineNumbersByRVA().
getModuleDebugStream()
Expected< ModuleDebugStreamRef > NativeSession::getModuleDebugStream (uint32_t Index) const
Definition at line 454 of file NativeSession.cpp.
References assert(), getDbiStreamPtr(), llvm::pdb::DbiModuleDescriptor::getModuleStreamIndex(), llvm::pdb::kInvalidStreamIndex, and llvm::pdb::ModuleDebugStreamRef::reload().
Referenced by llvm::pdb::NativeInlineSiteSymbol::findInlineeLinesByVA(), llvm::pdb::NativeFunctionSymbol::findInlineFramesByVA(), and llvm::pdb::SymbolCache::findLineNumbersByVA().
getNativeGlobalScope()
NativeExeSymbol & NativeSession::getNativeGlobalScope () const
Definition at line 376 of file NativeSession.cpp.
References llvm::pdb::SymbolCache::getNativeSymbolById().
Referenced by getGlobalScope().
getPDBFile() [1/2]
PDBFile & llvm::pdb::NativeSession::getPDBFile () inline
Definition at line 109 of file NativeSession.h.
Referenced by llvm::pdb::SymbolCache::createTypeEnumerator(), llvm::pdb::SymbolCache::findSymbolByTypeIndex(), llvm::pdb::NativeExeSymbol::getAge(), getDbiStreamPtr(), llvm::pdb::NativeSourceFile::getFileName(), llvm::pdb::NativeExeSymbol::getGuid(), llvm::pdb::NativeInlineSiteSymbol::getName(), llvm::pdb::SymbolCache::getOrCreateGlobalSymbolByOffset(), llvm::pdb::NativeExeSymbol::getSymbolsFileName(), llvm::pdb::NativeExeSymbol::hasCTypes(), llvm::pdb::NativeExeSymbol::hasPrivateSymbols(), and llvm::pdb::NativeEnumGlobals::NativeEnumGlobals().
getPDBFile() [2/2]
const PDBFile & llvm::pdb::NativeSession::getPDBFile () const inline
Definition at line 110 of file NativeSession.h.
getRVAFromSectOffset()
uint32_t NativeSession::getRVAFromSectOffset (uint32_t Section, uint32_t Offset) const
Definition at line 382 of file NativeSession.cpp.
References getDbiStreamPtr(), and llvm::pdb::Offset.
Referenced by llvm::pdb::NativeFunctionSymbol::getRelativeVirtualAddress(), llvm::pdb::NativeLineNumber::getRelativeVirtualAddress(), llvm::pdb::NativePublicSymbol::getRelativeVirtualAddress(), and getVAFromSectOffset().
getSectionContribs()
std::unique_ptr< IPDBEnumSectionContribs > NativeSession::getSectionContribs () const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 362 of file NativeSession.cpp.
getSourceFileById()
std::unique_ptr< IPDBSourceFile > NativeSession::getSourceFileById (uint32_t FileId) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 334 of file NativeSession.cpp.
References llvm::pdb::SymbolCache::getSourceFileById().
getSourceFilesForCompiland()
std::unique_ptr< IPDBEnumSourceFiles > NativeSession::getSourceFilesForCompiland (const PDBSymbolCompiland & Compiland) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 328 of file NativeSession.cpp.
getSymbolById()
std::unique_ptr< PDBSymbol > NativeSession::getSymbolById (SymIndexId SymbolId) const override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 217 of file NativeSession.cpp.
References llvm::pdb::SymbolCache::getSymbolById().
getSymbolCache() [1/2]
SymbolCache & llvm::pdb::NativeSession::getSymbolCache () inline
Definition at line 113 of file NativeSession.h.
Referenced by llvm::pdb::NativeExeSymbol::findChildren(), llvm::pdb::NativeInlineSiteSymbol::findInlineeLinesByVA(), llvm::pdb::NativeFunctionSymbol::findInlineFramesByVA(), llvm::pdb::NativeTypeArray::getArrayIndexTypeId(), llvm::pdb::NativeTypeEnum::getBuiltinType(), llvm::pdb::NativeEnumGlobals::getChildAtIndex(), llvm::pdb::NativeEnumModules::getChildAtIndex(), llvm::pdb::NativeEnumSymbols::getChildAtIndex(), llvm::pdb::NativeEnumTypes::getChildAtIndex(), llvm::pdb::NativeEnumModules::getChildCount(), llvm::pdb::NativeTypePointer::getClassParentId(), llvm::pdb::NativeTypeArray::getCount(), llvm::pdb::NativeTypeEnum::getLength(), llvm::pdb::NativeTypeArray::getTypeId(), llvm::pdb::NativeTypeEnum::getTypeId(), llvm::pdb::NativeTypeFunctionSig::getTypeId(), llvm::pdb::NativeTypePointer::getTypeId(), llvm::pdb::NativeTypeTypedef::getTypeId(), llvm::pdb::NativeTypeEnum::getUnderlyingBuiltinType(), llvm::pdb::NativeTypeUDT::getVirtualTableShapeId(), and llvm::pdb::NativeTypeFunctionSig::initialize().
getSymbolCache() [2/2]
const SymbolCache & llvm::pdb::NativeSession::getSymbolCache () const inline
Definition at line 114 of file NativeSession.h.
getVAFromSectOffset()
uint64_t NativeSession::getVAFromSectOffset (uint32_t Section, uint32_t Offset) const
Definition at line 398 of file NativeSession.cpp.
References getRVAFromSectOffset(), and llvm::pdb::Offset.
Referenced by findLineNumbersBySectOffset(), llvm::pdb::NativeFunctionSymbol::getVirtualAddress(), llvm::pdb::NativeLineNumber::getVirtualAddress(), llvm::pdb::NativePublicSymbol::getVirtualAddress(), and moduleIndexForSectOffset().
moduleIndexForSectOffset()
bool NativeSession::moduleIndexForSectOffset (uint32_t Sect, uint32_t Offset, uint16_t & ModuleIndex) const
Definition at line 412 of file NativeSession.cpp.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::end(), llvm::IntervalMap< KeyT, ValT, N, Traits >::find(), getVAFromSectOffset(), and llvm::pdb::Offset.
Referenced by llvm::pdb::SymbolCache::findSymbolBySectOffset().
moduleIndexForVA()
bool NativeSession::moduleIndexForVA (uint64_t VA, uint16_t & ModuleIndex) const
Definition at line 403 of file NativeSession.cpp.
References llvm::IntervalMap< KeyT, ValT, N, Traits >::end(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::find().
Referenced by llvm::pdb::NativeInlineSiteSymbol::findInlineeLinesByVA(), llvm::pdb::NativeFunctionSymbol::findInlineFramesByVA(), and llvm::pdb::SymbolCache::findLineNumbersByVA().
searchForPdb()
Expected< std::string > NativeSession::searchForPdb (const PdbSearchOptions & Opts) static
Definition at line 174 of file NativeSession.cpp.
References Allocator, llvm::sys::path::append(), llvm::consumeError(), llvm::sys::path::filename(), llvm::Expected< T >::get(), getPdbPathFromExe(), loadPdbFile(), llvm::sys::path::posix, llvm::sys::path::remove_filename(), llvm::StringRef::starts_with(), llvm::Expected< T >::takeError(), and llvm::sys::path::windows.
Referenced by llvm::pdb::loadDataForEXE(), and searchForExe().
setLoadAddress()
bool NativeSession::setLoadAddress (uint64_t Address) override virtual
Implements llvm::pdb::IPDBSession.
Definition at line 207 of file NativeSession.cpp.
References llvm::pdb::Address.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/NativeSession.h
lib/DebugInfo/PDB/Native/NativeSession.cpp