LLVM: llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT > Class Template Reference
llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT > Class Template Reference
#include "llvm/ADT/DenseMap.h"
Inherits llvm::DebugEpochBase.
Inherited by llvm::DenseMap< ValueType, unsigned >, llvm::DenseMap< Function *, detail::DenseSetEmpty, DenseMapInfo< Function * >, detail::DenseSetPair< Function * > >, llvm::DenseMap< Instruction *, NodeType * >, llvm::DenseMap< Instruction *, size_t >, llvm::DenseMap< NodeType *, size_t >, llvm::DenseMap< ValueT, detail::DenseSetEmpty, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, llvm::DenseMap< BasicBlock *, DomSetType >, llvm::DenseMap< BasicBlock *, std::unique_ptr< DomTreeNodeBase< BasicBlock > > >, llvm::DenseMap< BlockT *, DomSetType >, llvm::DenseMap< const BasicBlock *, Loop * >, llvm::DenseMap< const llvm::DILocation *, const llvm::sampleprof::FunctionSamples * >, llvm::DenseMap< const BasicBlockT *, uint64_t >, llvm::DenseMap< Edge, uint64_t >, llvm::DenseMap< const BasicBlockT *, const BasicBlockT * >, llvm::DenseMap< const BasicBlockT *, SmallVector< const BasicBlockT *, 8 > >, llvm::DenseMap< AnalysisKey *, std::unique_ptr< PassConceptT > >, llvm::DenseMap< MachineFunction *, AnalysisResultListT >, llvm::DenseMap< std::pair< AnalysisKey *, MachineFunction * >, typename AnalysisResultListT::iterator >, llvm::DenseMap< BlockT *, RegionT * >, llvm::DenseMap< const MachineFunction *, unsigned >, llvm::DenseMap< const T *, unsigned >, llvm::DenseMap< SPIRV::SpecialTypeDescriptor, unsigned >, llvm::DenseMap< T, detail::DenseSetEmpty, DenseMapInfo< T >, detail::DenseSetPair< T > >, llvm::DenseMap< unsigned, llvm::jitlink::Block * >, llvm::DenseMap< unsigned, llvm::jitlink::Symbol * >, llvm::DenseMap< const typename ELFFile::Elf_Shdr *, llvm::ArrayRef< typename ELFFile::Elf_Word > >, llvm::DenseMap< llvm::StringRef, llvm::jitlink::Symbol * >, llvm::DenseMap< AA::RangeTy, SmallSet< unsigned, 4 > >, llvm::DenseMap< const llvm::Instruction *, llvm::SmallVector< unsigned > >, llvm::DenseMap< llvm::StringRef, llvm::object::SectionRef >, llvm::DenseMap< const Value *, detail::DenseSetEmpty, DenseMapInfo< const Value * >, detail::DenseSetPair< const Value * > >, llvm::DenseMap< llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< llvm::Instruction * >, detail::DenseSetPair< llvm::Instruction * > >, llvm::DenseMap< llvm::BasicBlock *, detail::DenseSetEmpty, DenseMapInfo< llvm::BasicBlock * >, detail::DenseSetPair< llvm::BasicBlock * > >, llvm::DenseMap< const llvm::MachineInstr *, detail::DenseSetEmpty, DenseMapInfo< const llvm::MachineInstr * >, detail::DenseSetPair< const llvm::MachineInstr * > >, llvm::DenseMap< const llvm::Function *, unsigned >, llvm::DenseMap< const llvm::Instruction *, unsigned >, llvm::DenseMap< const llvm::DILocalVariable *, unsigned >, llvm::DenseMap< StringRef, FunctionImporter::ExportSetTy >, llvm::DenseMap< LiveDebugValues::ValueIDNum, LiveDebugValues::DbgOpID >, llvm::DenseMap< llvm::MachineOperand, LiveDebugValues::DbgOpID >, llvm::DenseMap< unsigned int, llvm::MachineBasicBlock * >, llvm::DenseMap< const llvm::MachineBasicBlock *, unsigned int >, llvm::DenseMap< unsigned, unsigned >, llvm::DenseMap< FragmentOfVar, SmallVector< DIExpression::FragmentInfo, 1 > >, llvm::DenseMap< const DILocalVariable *, SmallSet< FragmentInfo, 4 > >, llvm::DenseMap< std::pair< llvm::MachineInstr *, unsigned >, std::optional< LiveDebugValues::ValueIDNum > >, llvm::DenseMap< StackSlotPos, unsigned >, llvm::DenseMap< unsigned, StackSlotPos >, llvm::DenseMap< llvm::DebugVariable, unsigned >, llvm::DenseMap< unsigned, const CounterMappingRegion * >, llvm::DenseMap< llvm::DILocalScope *, llvm::DISubprogram * >, llvm::DenseMap< Value *, BasicBlock * >, llvm::DenseMap< ArrayRef< unsigned >, detail::DenseSetEmpty, DenseMapInfo< ArrayRef< unsigned > >, detail::DenseSetPair< ArrayRef< unsigned > > >, llvm::DenseMap< unsigned, std::pair< std::pair< unsigned, unsigned >, SmallVector< unsigned, 2 > > >, llvm::DenseMap< hash_code, unsigned >, llvm::DenseMap< const MCSection *, ElfMappingSymbol >, llvm::DenseMap< const SCEV *, const SCEV * >, llvm::DenseMap< MachineInstr *, detail::DenseSetEmpty, DenseMapInfo< MachineInstr * >, detail::DenseSetPair< MachineInstr * > >, llvm::DenseMap< LocIdx, SmallSet< DebugVariable, 4 > >, llvm::DenseMap< DebugVariable, TransferTracker::ResolvedDbgValue >, llvm::DenseMap< unsigned, SmallVector< TransferTracker::UseBeforeDef, 1 > >, llvm::DenseMap< DebugVariable, detail::DenseSetEmpty, DenseMapInfo< DebugVariable >, detail::DenseSetPair< DebugVariable > >, llvm::DenseMap< unsigned, detail::DenseSetEmpty, DenseMapInfo< unsigned >, detail::DenseSetPair< unsigned > >, llvm::DenseMap< DepTy, detail::DenseSetEmpty, DenseMapInfo< DepTy >, detail::DenseSetPair< DepTy > >, llvm::DenseMap< const llvm::Function *, llvm::AMDGPUFunctionArgInfo >, llvm::DenseMap< ValueMapCVH, FuncInfo, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< const llvm::Function *, llvm::AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo >, llvm::DenseMap< const llvm::MachineBasicBlock *, unsigned >, llvm::DenseMap< StringRef, unsigned >, llvm::DenseMap< llvm::AssertingVH< llvm::BasicBlock >, AddrLabelSymEntry >, llvm::DenseMap< llvm::AssertingVH< llvm::Function >, std::vector< llvm::MCSymbol * > >, llvm::DenseMap< const llvm::MCSymbol *, AddressPoolEntry >, llvm::DenseMap< AssertingVH< const Value >, AliasSet * >, llvm::DenseMap< IRUnitT *, AnalysisResultListT >, llvm::DenseMap< std::pair< AnalysisKey *, IRUnitT * >, typename AnalysisResultListT::iterator >, llvm::DenseMap< llvm::StringRef, unsigned >, llvm::DenseMap< const llvm::MCSymbol *, unsigned >, llvm::DenseMap< unsigned, llvm::MCSymbol * >, llvm::DenseMap< llvm::GCStrategy *, std::unique_ptr< llvm::GCMetadataPrinter > >, llvm::DenseMap< const llvm::MDNode *, llvm::SmallVector< const llvm::MCSymbol * > >, llvm::DenseMap< MCSection *, unsigned >, llvm::DenseMap< AffectedValueCallbackVH, SmallVector< ResultElem, 1 >, AffectedValueCallbackVH::DMI >, llvm::DenseMap< FunctionCallbackVH, std::unique_ptr< AssumptionCache >, FunctionCallbackVH::DMI >, llvm::DenseMap< llvm::StringRef, llvm::Attribute >, llvm::DenseMap< llvm::Value *, llvm::AttributeList >, llvm::DenseMap< llvm::IRPosition, llvm::SmallVector< SimplifictionCallbackTy, 1 > >, llvm::DenseMap< const llvm::GlobalVariable *, llvm::SmallVector< GlobalVariableSimplifictionCallbackTy, 1 > >, llvm::DenseMap< const llvm::Value *, llvm::SmallVector< VirtualUseCallbackTy, 1 > >, llvm::DenseMap< AAMapKeyTy, llvm::AbstractAttribute * >, llvm::DenseMap< llvm::Function *, llvm::SmallVector< std::unique_ptr< llvm::Attributor::ArgumentReplacementInfo >, 8 > >, llvm::DenseMap< llvm::Function *, detail::DenseSetEmpty, DenseMapInfo< llvm::Function * >, detail::DenseSetPair< llvm::Function * > >, llvm::DenseMap< const llvm::Function *, detail::DenseSetEmpty, DenseMapInfo< const llvm::Function * >, detail::DenseSetPair< const llvm::Function * > >, llvm::DenseMap< llvm::WeakVH, detail::DenseSetEmpty, DenseMapInfo< llvm::WeakVH >, detail::DenseSetPair< llvm::WeakVH > >, llvm::DenseMap< llvm::AbstractAttribute *, detail::DenseSetEmpty, DenseMapInfo< llvm::AbstractAttribute * >, detail::DenseSetPair< llvm::AbstractAttribute * > >, llvm::DenseMap< const char *, detail::DenseSetEmpty, DenseMapInfo< const char * >, detail::DenseSetPair< const char * > >, llvm::DenseMap< uint64_t, llvm::SmallVector >, llvm::DenseMap< const llvm::MachineInstr *, unsigned >, llvm::DenseMap< const llvm::BasicBlock *, llvm::SmallSetVector >, llvm::DenseMap< BlockKeyT, std::pair< BlockNode, llvm::bfi_detail::BFICallbackVH > >, llvm::DenseMap< KeyT, size_t >, llvm::DenseMap< const llvm::MachineBasicBlock *, int >, llvm::DenseMap< BasicBlockCallbackVH, detail::DenseSetEmpty, llvm::DenseMapInfo< llvm::Value * >, detail::DenseSetPair< BasicBlockCallbackVH > >, llvm::DenseMap< Edge, llvm::BranchProbability >, llvm::DenseMap< const BasicBlock *, int >, llvm::DenseMap< const llvm::BasicBlock *, std::unique_ptr< BBInfo > >, llvm::DenseMap< llvm::CSKYTargetStreamer::SymbolIndex, const llvm::MCExpr * >, llvm::DenseMap< const llvm::Function *, uint64_t >, llvm::DenseMap< VNType, SmallVector< Instruction *, 4 > >, llvm::DenseMap< MDString *, unsigned >, llvm::DenseMap< const llvm::Value *, const llvm::Value * >, llvm::DenseMap< Value *, detail::DenseSetEmpty, DenseMapInfo< Value * >, detail::DenseSetPair< Value * > >, llvm::DenseMap< llvm::BasicBlock *, llvm::DenseSet< llvm::Value * > >, llvm::DenseMap< const llvm::BasicBlock *, llvm::InstructionCost >, llvm::DenseMap< const llvm::DIGlobalVariable *, uint64_t >, llvm::DenseMap< const llvm::LexicalScope *, llvm::SmallVector< LocalVariable, 1 > >, llvm::DenseMap< const llvm::DIScope *, std::unique_ptr< llvm::SmallVector > >, llvm::DenseMap< llvm::MCSectionCOFF *, detail::DenseSetEmpty, DenseMapInfo< llvm::MCSectionCOFF * >, detail::DenseSetPair< llvm::MCSectionCOFF * > >, llvm::DenseMap< const llvm::DISubprogram *, detail::DenseSetEmpty, DenseMapInfo< const llvm::DISubprogram * >, detail::DenseSetPair< const llvm::DISubprogram * > >, llvm::DenseMap< std::pair< const llvm::DINode *, const llvm::DIType * >, llvm::codeview::TypeIndex >, llvm::DenseMap< const llvm::DICompositeType *, llvm::codeview::TypeIndex >, llvm::DenseMap< llvm::CodeViewDebug::LocalVarDef, unsigned >, llvm::DenseMap< llvm::MachineInstr *, unsigned >, llvm::DenseMap< GlobalVariable *, unsigned >, llvm::DenseMap< llvm::Instruction *, unsigned >, llvm::DenseMap< const llvm::MCSymbol *, const llvm::MCSymbolRefExpr * >, llvm::DenseMap< ConstantClass *, detail::DenseSetEmpty, MapInfo, detail::DenseSetPair< ConstantClass * > >, llvm::DenseMap< llvm::Value *, unsigned >, llvm::DenseMap< BlockT *, llvm::GenericCycle * >, llvm::DenseMap< EdgeType *, detail::DenseSetEmpty, DenseMapInfo< EdgeType * >, detail::DenseSetPair< EdgeType * > >, llvm::DenseMap< llvm::MDNode *, unsigned >, llvm::DenseMap< llvm::DISubprogram *, llvm::SmallVector< llvm::TypedTrackingMDRef, 4 > >, llvm::DenseMap< const llvm::DIE *, unsigned >, llvm::DenseMap< const llvm::BasicBlock *, bool >, llvm::DenseMap< uint64_t, detail::DenseSetEmpty, DenseMapInfo< uint64_t >, detail::DenseSetPair< uint64_t > >, llvm::DenseMap< uint64_t, const llvm::DWARFDebugNames::NameIndex * >, llvm::DenseMap< llvm::DWARFDebugNames::Abbrev, detail::DenseSetEmpty, AbbrevMapInfo, detail::DenseSetPair< llvm::DWARFDebugNames::Abbrev > >, llvm::DenseMap< const char *, uint32_t, CStrDenseMapInfo >, llvm::DenseMap< const NodeType *, const PiBlockDDGNode * >, llvm::DenseMap< InlinedEntity, unsigned >, llvm::DenseMap< unsigned, CounterInfo >, llvm::DenseMap< const llvm::MachineInstr *, llvm::MCSymbol * >, llvm::DenseMap< llvm::Instruction *, llvm::APInt >, llvm::DenseMap< Value *, SmallVector< BranchInst *, 1 > >, llvm::DenseMap< NodePtr, llvm::DomTreeBuilder::SemiNCAInfo::InfoRec >, llvm::DenseMap< NodeT *, std::unique_ptr< DomTreeNodeBase< NodeT > > >, llvm::DenseMap< const llvm::DILocalScope *, llvm::DIE * >, llvm::DenseMap< const llvm::DINode *, std::unique_ptr< llvm::DbgEntity > >, llvm::DenseMap< const llvm::MDNode *, unsigned >, llvm::DenseMap< const llvm::DIE *, llvm::DwarfCompileUnit * >, llvm::DenseMap< const llvm::MCSymbol *, uint64_t >, llvm::DenseMap< const llvm::DILocalScope *, llvm::SetVector >, llvm::DenseMap< const llvm::MDNode *, uint64_t >, llvm::DenseMap< const llvm::MCSection *, const llvm::MCSymbol * >, llvm::DenseMap< const llvm::DIStringType *, unsigned >, llvm::DenseMap< llvm::LexicalScope *, ScopeVars >, llvm::DenseMap< llvm::LexicalScope *, llvm::SmallVector >, llvm::DenseMap< const llvm::MDNode *, llvm::DIE * >, llvm::DenseMap< llvm::DIE *, const llvm::DINode * >, llvm::DenseMap< const llvm::Value *, llvm::Instruction * >, llvm::DenseMap< llvm::Instruction *, llvm::TinyPtrVector< const llvm::Value * > >, llvm::DenseMap< llvm::GlobalVariable *, MutableValue >, llvm::DenseMap< llvm::GlobalValue *, detail::DenseSetEmpty, DenseMapInfo< llvm::GlobalValue * >, detail::DenseSetPair< llvm::GlobalValue * > >, llvm::DenseMap< const llvm::Value *, llvm::Register >, llvm::DenseMap< const llvm::Value *, int >, llvm::DenseMap< const llvm::Comdat *, llvm::Comdat * >, llvm::DenseMap< const llvm::BasicBlock *, llvm::MachineBasicBlock * >, llvm::DenseMap< llvm::Register, const llvm::Value * >, llvm::DenseMap< const llvm::Instruction *, llvm::DenseMap >, llvm::DenseMap< const llvm::AllocaInst *, int >, llvm::DenseMap< const llvm::Argument *, int >, llvm::DenseMap< llvm::Register, llvm::Register >, llvm::DenseMap< llvm::Register, detail::DenseSetEmpty, DenseMapInfo< llvm::Register >, detail::DenseSetPair< llvm::Register > >, llvm::DenseMap< const llvm::Value *, ISD::NodeType >, llvm::DenseMap< const llvm::BasicBlock *, detail::DenseSetEmpty, DenseMapInfo< const llvm::BasicBlock * >, detail::DenseSetPair< const llvm::BasicBlock * > >, llvm::DenseMap< llvm::Function *, llvm::CodeMetrics >, llvm::DenseMap< llvm::Function *, unsigned >, llvm::DenseMap< const llvm::Instruction *, std::pair< unsigned, unsigned > >, llvm::DenseMap< const Function *, GCFunctionInfo * >, llvm::DenseMap< unsigned, LaneBitmask >, llvm::DenseMap< const llvm::MachineBasicBlock *, llvm::DenseMap >, llvm::DenseMap< llvm::MachineInstr *, llvm::DenseMap >, llvm::DenseMap< const llvm::GCOVBlock *, detail::DenseSetEmpty, DenseMapInfo< const llvm::GCOVBlock * >, detail::DenseSetPair< const llvm::GCOVBlock * > >, llvm::DenseMap< const llvm::MachineInstr *, llvm::UniqueMachineInstr * >, llvm::DenseMap< const llvm::Value *, unsigned >, llvm::DenseMap< const BasicBlock *, bool >, llvm::DenseMap< uint32_t, LeaderTableEntry >, llvm::DenseMap< llvm::AssertingVH< llvm::BasicBlock >, uint32_t >, llvm::DenseMap< llvm::Value *, uint32_t >, llvm::DenseMap< llvm::GVNPass::Expression, uint32_t >, llvm::DenseMap< uint32_t, llvm::PHINode * >, llvm::DenseMap< std::pair< uint32_t, const BasicBlock * >, uint32_t >, llvm::DenseMap< const InstructionT *, const InstructionT * >, llvm::DenseMap< const BlockT *, detail::DenseSetEmpty, DenseMapInfo< const BlockT * >, detail::DenseSetPair< const BlockT * > >, llvm::DenseMap< BlockT *, DFSInfo >, llvm::DenseMap< const BlockT *, std::unique_ptr< llvm::GenericSyncDependenceAnalysis::DivergenceDescriptor > >, llvm::DenseMap< const BlockT *, const BlockT * >, llvm::DenseMap< llvm::GlobalValue *, llvm::SmallPtrSet< llvm::GlobalValue *, 4 > >, llvm::DenseMap< llvm::Metadata *, llvm::SmallSet< std::pair< llvm::GlobalVariable *, uint64_t >, 4 > >, llvm::DenseMap< ValueMapCVH, uint64_t, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< const llvm::Value *, const llvm::GlobalValue * >, llvm::DenseMap< const llvm::Function *, GlobalsAAResult::FunctionInfo >, llvm::DenseMap< unsigned, ExtType >, llvm::DenseMap< unsigned, PredSet >, llvm::DenseMap< NodeTy *, std::unique_ptr< DomTreeNodeBase< NodeTy > > >, llvm::DenseMap< const Metadata *, TrackingMDRef >, llvm::DenseMap< llvm::StructType *, detail::DenseSetEmpty, DenseMapInfo< llvm::StructType * >, detail::DenseSetPair< llvm::StructType * > >, llvm::DenseMap< llvm::StructType *, detail::DenseSetEmpty, StructTypeKeyInfo, detail::DenseSetPair< llvm::StructType * > >, llvm::DenseMap< llvm::Value *, llvm::Value * >, llvm::DenseMap< llvm::IRSimilarity::IRInstructionData *, unsigned, llvm::IRSimilarity::IRInstructionDataTraits >, llvm::DenseMap< llvm::BasicBlock *, unsigned >, llvm::DenseMap< unsigned, llvm::Value * >, llvm::DenseMap< unsigned, llvm::DenseSet< unsigned > >, llvm::DenseMap< CFGEdge, llvm::SmallVector< llvm::MachineBasicBlock *, 1 > >, llvm::DenseMap< const llvm::Value *, llvm::SmallVector * >, llvm::DenseMap< const llvm::Type *, llvm::SmallVector * >, llvm::DenseMap< unsigned, TreeTy * >, llvm::DenseMap< const llvm::Function *, FunctionInfo * >, llvm::DenseMap< RetainedKnowledgeKey, Assume2KnowledgeMap >, llvm::DenseMap< const llvm::Instruction *, detail::DenseSetEmpty, DenseMapInfo< const llvm::Instruction * >, detail::DenseSetPair< const llvm::Instruction * > >, llvm::DenseMap< const SmallPtrSet< Instruction *, 4 > *, detail::DenseSetEmpty, DenseMapInfo< const SmallPtrSet< Instruction *, 4 > * >, detail::DenseSetPair< const SmallPtrSet< Instruction *, 4 > * > >, llvm::DenseMap< unsigned, InstructionVectorTy * >, llvm::DenseMap< llvm::PHINode *, llvm::Value * >, llvm::DenseMap< Value *, Constant * >, llvm::DenseMap< IntPtrT, detail::DenseSetEmpty, DenseMapInfo< IntPtrT >, detail::DenseSetPair< IntPtrT > >, llvm::DenseMap< SymbolRemappingReader::Key, llvm::StringRef >, llvm::DenseMap< uint64_t, unsigned >, llvm::DenseMap< const llvm::BasicBlock *, const llvm::Instruction * >, llvm::DenseMap< int32_t, InstTy * >, llvm::DenseMap< llvm::Instruction *, llvm::InterleaveGroup< llvm::Instruction > * >, llvm::DenseMap< llvm::Instruction *, llvm::SmallPtrSet< llvm::Instruction *, 2 > >, llvm::DenseMap< llvm::MDNode *, llvm::SmallVector< llvm::Instruction *, 2 > >, llvm::DenseMap< const llvm::Value *, llvm::StringMapEntry * >, llvm::DenseMap< unsigned, std::unique_ptr< llvm::ConstantInt > >, llvm::DenseMap< llvm::APInt, std::unique_ptr< llvm::ConstantInt > >, llvm::DenseMap< llvm::APFloat, std::unique_ptr< llvm::ConstantFP > >, llvm::DenseMap< llvm::Value *, llvm::ValueAsMetadata * >, llvm::DenseMap< llvm::Metadata *, llvm::MetadataAsValue * >, llvm::DenseMap< llvm::DIArgList *, detail::DenseSetEmpty, llvm::DIArgListInfo, detail::DenseSetPair< llvm::DIArgList * > >, llvm::DenseMap< llvm::Type *, std::unique_ptr< llvm::ConstantAggregateZero > >, llvm::DenseMap< ConstantArray *, detail::DenseSetEmpty, MapInfo, detail::DenseSetPair< ConstantArray * > >, llvm::DenseMap< ConstantStruct *, detail::DenseSetEmpty, MapInfo, detail::DenseSetPair< ConstantStruct * > >, llvm::DenseMap< ConstantVector *, detail::DenseSetEmpty, MapInfo, detail::DenseSetPair< ConstantVector * > >, llvm::DenseMap< llvm::PointerType *, std::unique_ptr< llvm::ConstantPointerNull > >, llvm::DenseMap< llvm::TargetExtType *, std::unique_ptr< llvm::ConstantTargetNone > >, llvm::DenseMap< llvm::Type *, std::unique_ptr< llvm::UndefValue > >, llvm::DenseMap< llvm::Type *, std::unique_ptr< llvm::PoisonValue > >, llvm::DenseMap< std::pair< const llvm::Function *, const llvm::BasicBlock * >, llvm::BlockAddress * >, llvm::DenseMap< const llvm::GlobalValue *, llvm::DSOLocalEquivalent * >, llvm::DenseMap< const llvm::GlobalValue *, llvm::NoCFIValue * >, llvm::DenseMap< llvm::ConstantExpr *, detail::DenseSetEmpty, MapInfo, detail::DenseSetPair< llvm::ConstantExpr * > >, llvm::DenseMap< llvm::InlineAsm *, detail::DenseSetEmpty, MapInfo, detail::DenseSetPair< llvm::InlineAsm * > >, llvm::DenseMap< unsigned, llvm::IntegerType * >, llvm::DenseMap< FunctionType *, detail::DenseSetEmpty, FunctionTypeKeyInfo, detail::DenseSetPair< FunctionType * > >, llvm::DenseMap< StructType *, detail::DenseSetEmpty, AnonStructTypeKeyInfo, detail::DenseSetPair< StructType * > >, llvm::DenseMap< TargetExtType *, detail::DenseSetEmpty, TargetExtTypeKeyInfo, detail::DenseSetPair< TargetExtType * > >, llvm::DenseMap< std::pair< llvm::Type *, uint64_t >, llvm::ArrayType * >, llvm::DenseMap< std::pair< llvm::Type *, llvm::ElementCount >, llvm::VectorType * >, llvm::DenseMap< unsigned, llvm::PointerType * >, llvm::DenseMap< std::pair< llvm::Type *, unsigned >, llvm::PointerType * >, llvm::DenseMap< std::pair< llvm::Type *, unsigned >, llvm::TypedPointerType * >, llvm::DenseMap< Value *, ValueHandleBase * >, llvm::DenseMap< const llvm::Value *, llvm::MDAttachments >, llvm::DenseMap< llvm::DIAssignID *, llvm::SmallVector< llvm::Instruction *, 1 > >, llvm::DenseMap< const llvm::GlobalObject *, llvm::StringRef >, llvm::DenseMap< const llvm::GlobalValue *, llvm::StringRef >, llvm::DenseMap< const llvm::GlobalValue *, llvm::GlobalValue::SanitizerMetadata >, llvm::DenseMap< std::pair< const char *, unsigned >, unsigned >, llvm::DenseMap< const llvm::Function *, std::string >, llvm::DenseMap< const llvm::Function *, llvm::LazyCallGraph::Node * >, llvm::DenseMap< llvm::LazyCallGraph::Node *, llvm::LazyCallGraph::SCC * >, llvm::DenseMap< llvm::LazyCallGraph::RefSCC *, int >, llvm::DenseMap< llvm::LazyCallGraph::Node *, int >, llvm::DenseMap< std::pair< llvm::BasicBlock *, llvm::Value * >, detail::DenseSetEmpty, DenseMapInfo< std::pair< llvm::BasicBlock *, llvm::Value * > >, detail::DenseSetPair< std::pair< llvm::BasicBlock *, llvm::Value * > > >, llvm::DenseMap< const llvm::DILocation *, std::unique_ptr< llvm::SmallPtrSet > >, llvm::DenseMap< LiveRange *, std::pair< BitVector, BitVector > >, llvm::DenseMap< unsigned, llvm::BitVector >, llvm::DenseMap< llvm::MCSection *, const llvm::MCSymbolRefExpr * >, llvm::DenseMap< llvm::Value *, const llvm::SCEV * >, llvm::DenseMap< llvm::Loop *, std::unique_ptr< llvm::LoopAccessInfo > >, llvm::DenseMap< ValueMapCVH, WeakTrackingVH, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< const BlockT *, LoopT * >, llvm::DenseMap< llvm::BasicBlock *, llvm::TinyPtrVector >, llvm::DenseMap< llvm::ElementCount, llvm::SmallPtrSet< llvm::BasicBlock *, 4 > >, llvm::DenseMap< llvm::ElementCount, llvm::DenseMap >, llvm::DenseMap< llvm::ElementCount, llvm::SmallPtrSet< llvm::Instruction *, 4 > >, llvm::DenseMap< llvm::Instruction *, llvm::Instruction * >, llvm::DenseMap< std::pair< Instruction *, ElementCount >, std::pair< InstWidening, InstructionCost > >, llvm::DenseMap< std::pair< CallInst *, ElementCount >, CallWideningDecision >, llvm::DenseMap< PHINode *, unsigned >, llvm::DenseMap< const llvm::Value *, const llvm::RuntimeCheckingPtrGroup * >, llvm::DenseMap< const llvm::RuntimeCheckingPtrGroup *, llvm::MDNode * >, llvm::DenseMap< const llvm::MachineBasicBlock *, llvm::BlockFrequency >, llvm::DenseMap< const llvm::MCSection *, llvm::MCFragment * >, llvm::DenseMap< unsigned, llvm::MCCVFunctionInfo::LineInfo >, llvm::DenseMap< std::pair< unsigned, unsigned >, llvm::MCSymbol * >, llvm::DenseMap< unsigned, llvm::MCLabel * >, llvm::DenseMap< llvm::MCSection *, detail::DenseSetEmpty, DenseMapInfo< llvm::MCSection * >, detail::DenseSetPair< llvm::MCSection * > >, llvm::DenseMap< llvm::StringRef, detail::DenseSetEmpty, DenseMapInfo< llvm::StringRef >, detail::DenseSetPair< llvm::StringRef > >, llvm::DenseMap< const llvm::MCSymbol *, llvm::SmallVector< PendingAssignment, 1 > >, llvm::DenseMap< llvm::MCRegister, int >, llvm::DenseMap< const uint32_t *, unsigned >, llvm::DenseMap< int, FrameIndexOperand >, llvm::DenseMap< const llvm::LazyCallGraph::Node *, detail::DenseSetEmpty, DenseMapInfo< const llvm::LazyCallGraph::Node * >, detail::DenseSetPair< const llvm::LazyCallGraph::Node * > >, llvm::DenseMap< llvm::MachO::ObjCIVarRecord, unsigned >, llvm::DenseMap< llvm::MachO::GlobalRecord, unsigned >, llvm::DenseMap< llvm::MachO::ObjCInterfaceRecord, unsigned >, llvm::DenseMap< llvm::MachO::ObjCCategoryRecord, unsigned >, llvm::DenseMap< SymbolsMapKey, Symbol * >, llvm::DenseMap< const llvm::MCSection *, std::vector< RelAndSymbol > >, llvm::DenseMap< const llvm::MCSection *, unsigned >, llvm::DenseMap< const MCSection *, uint64_t >, llvm::DenseMap< llvm::MachineConstantPoolValue *, detail::DenseSetEmpty, DenseMapInfo< llvm::MachineConstantPoolValue * >, detail::DenseSetPair< llvm::MachineConstantPoolValue * > >, llvm::DenseMap< llvm::MachineBasicBlock *, DomSetType >, llvm::DenseMap< llvm::MCSymbol *, llvm::SmallVector< unsigned, 4 > >, llvm::DenseMap< llvm::MCSymbol *, unsigned >, llvm::DenseMap< const MachineInstr *, CallSiteInfo >, llvm::DenseMap< unsigned, llvm::MachineFunction::DebugPHIRegallocPos >, llvm::DenseMap< const llvm::MachineBasicBlock *, llvm::MachineLoop * >, llvm::DenseMap< const llvm::Function *, std::unique_ptr< llvm::MachineFunction > >, llvm::DenseMap< llvm::MCSymbol *, StubValueTy >, llvm::DenseMap< const llvm::MachineInstr *, llvm::MachineTraceMetrics::InstrCycles >, llvm::DenseMap< const llvm::GlobalValue *, unsigned >, llvm::DenseMap< llvm::Init *, MappedValue >, llvm::DenseMap< KeyT, unsigned >, llvm::DenseMap< PointerIntPair< Value *, 1, bool >, std::vector< unsigned > >, llvm::DenseMap< Instruction *, MemDepResult >, llvm::DenseMap< llvm::AssertingVH< const llvm::Value >, llvm::NonLocalDepResult >, llvm::DenseMap< Instruction *, SmallPtrSet< const Value *, 4 > >, llvm::DenseMap< ValueIsLoadPair, NonLocalPointerInfo >, llvm::DenseMap< Instruction *, SmallPtrSet< ValueIsLoadPair, 4 > >, llvm::DenseMap< Instruction *, PerInstNLInfo >, llvm::DenseMap< Instruction *, SmallPtrSet< Instruction *, 4 > >, llvm::DenseMap< LoadInst *, int32_t >, llvm::DenseMap< const llvm::Value *, llvm::MemoryAccess * >, llvm::DenseMap< const BasicBlock *, std::unique_ptr< AccessList > >, llvm::DenseMap< const BasicBlock *, std::unique_ptr< DefsList > >, llvm::DenseMap< const llvm::MemoryAccess *, unsigned long >, llvm::DenseMap< const llvm::MachineInstr *, llvm::SmallVector< const llvm::MachineInstr *, 2 > >, llvm::DenseMap< const llvm::MachineInstr *, InstType >, llvm::DenseMap< const BlockT *, unsigned >, llvm::DenseMap< std::pair< unsigned, const llvm::FunctionType * >, unsigned >, llvm::DenseMap< llvm::MachineInstr *, int >, llvm::DenseMap< MachineInstr *, std::pair< unsigned, int64_t > >, llvm::DenseMap< const llvm::BasicBlock *, std::optional< bool > >, llvm::DenseMap< const llvm::Function *, std::optional< bool > >, llvm::DenseMap< const llvm::Instruction *, std::unique_ptr< llvm::MustBeExecutedIterator > >, llvm::DenseMap< PointerIntPair< const Instruction *, 1, ExplorationDirection >, detail::DenseSetEmpty, DenseMapInfo< PointerIntPair< const Instruction *, 1, ExplorationDirection > >, detail::DenseSetPair< PointerIntPair< const Instruction *, 1, ExplorationDirection > > >, llvm::DenseMap< const TargetRegisterClass *, VRegMap >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallVector< llvm::WeakTrackingVH, 2 > >, llvm::DenseMap< llvm::SUnit *, detail::DenseSetEmpty, DenseMapInfo< llvm::SUnit * >, detail::DenseSetPair< llvm::SUnit * > >, llvm::DenseMap< const Value *, WeakEvalType >, llvm::DenseMap< std::pair< llvm::Constant *, uint64_t >, llvm::Constant * >, llvm::DenseMap< llvm::Value *, llvm::BasicBlock * >, llvm::DenseMap< unsigned, llvm::Constant * >, llvm::DenseMap< PoolEntry *, detail::DenseSetEmpty, PoolEntryDSInfo, detail::DenseSetPair< PoolEntry * > >, llvm::DenseMap< llvm::Register, unsigned >, llvm::DenseMap< AnalysisID, llvm::Pass * >, llvm::DenseMap< llvm::Pass *, llvm::Pass * >, llvm::DenseMap< llvm::Pass *, llvm::SmallPtrSet< llvm::Pass *, 8 > >, llvm::DenseMap< llvm::Pass *, llvm::AnalysisUsage * >, llvm::DenseMap< AnalysisID, const llvm::PassInfo * >, llvm::DenseMap< unsigned, std::pair< llvm::Register, llvm::Register > >, llvm::DenseMap< AnalysisID, llvm::IdentifyingPassPtr >, llvm::DenseMap< const void *, const PassInfo * >, llvm::DenseMap< llvm::MachineBasicBlock *, llvm::BitVector >, llvm::DenseMap< llvm::MachineInstr *, llvm::MachineInstr * >, llvm::DenseMap< std::pair< llvm::MachineBasicBlock *, llvm::MachineInstr * >, llvm::MachineInstr * >, llvm::DenseMap< unsigned, llvm::MachineBasicBlock * >, llvm::DenseMap< llvm::Register, llvm::VRegInfo * >, llvm::DenseMap< unsigned, int >, llvm::DenseMap< unsigned, const llvm::Value * >, llvm::DenseMap< const llvm::PHINode *, unsigned int >, llvm::DenseMap< unsigned int, llvm::SmallSetVector >, llvm::DenseMap< PhiValuesCallbackVH, detail::DenseSetEmpty, llvm::DenseMapInfo< llvm::Value * >, detail::DenseSetPair< PhiValuesCallbackVH > >, llvm::DenseMap< const llvm::Function *, std::vector< uint32_t > >, llvm::DenseMap< MemberTy, detail::DenseSetEmpty, DenseMapInfo< MemberTy >, detail::DenseSetPair< MemberTy > >, llvm::DenseMap< llvm::MachineInstr *, llvm::SmallVector< unsigned, 4 > >, llvm::DenseMap< llvm::BasicBlock *, llvm::BasicBlock ** >, llvm::DenseMap< const llvm::Value *, const llvm::PredicateBase * >, llvm::DenseMap< llvm::Value *, unsigned int >, llvm::DenseMap< std::pair< llvm::BasicBlock *, llvm::BasicBlock * >, detail::DenseSetEmpty, DenseMapInfo< std::pair< llvm::BasicBlock *, llvm::BasicBlock * > >, detail::DenseSetPair< std::pair< llvm::BasicBlock *, llvm::BasicBlock * > > >, llvm::DenseMap< const llvm::SCEV *, RewriteEntry >, llvm::DenseMap< ValueMapCVH, SCEVWrapPredicate::IncrementWrapFlags, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< const llvm::BasicBlock *, llvm::DenseMap< const llvm::BasicBlock *, unsigned > >, llvm::DenseMap< T, ptrdiff_t >, llvm::DenseMap< int, uint64_t >, llvm::DenseMap< llvm::StringRef, uint64_t >, llvm::DenseMap< uint64_t, llvm::PseudoProbeDescriptor >, llvm::DenseMap< ValueMapCVH, std::unique_ptr< const llvm::GlobalValuePseudoSourceValue >, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< const llvm::LiveInterval *, detail::DenseSetEmpty, DenseMapInfo< const llvm::LiveInterval * >, detail::DenseSetPair< const llvm::LiveInterval * > >, llvm::DenseMap< llvm::AssertingVH< llvm::Value >, unsigned >, llvm::DenseMap< AssertingVH< Instruction >, detail::DenseSetEmpty, DenseMapInfo< AssertingVH< Instruction > >, detail::DenseSetPair< AssertingVH< Instruction > > >, llvm::DenseMap< std::pair< llvm::Value *, llvm::Value * >, llvm::ReassociatePass::PairMapValue >, llvm::DenseMap< llvm::Init *, llvm::Init * >, llvm::DenseMap< const llvm::MCSymbol *, std::vector< llvm::StringRef > >, llvm::DenseMap< unsigned, std::unique_ptr< const llvm::RegisterBankInfo::PartialMapping > >, llvm::DenseMap< unsigned, std::unique_ptr< const llvm::RegisterBankInfo::ValueMapping > >, llvm::DenseMap< unsigned, std::unique_ptr< llvm::RegisterBankInfo::ValueMapping[]> >, llvm::DenseMap< unsigned, std::unique_ptr< const llvm::RegisterBankInfo::InstructionMapping > >, llvm::DenseMap< unsigned, const llvm::TargetRegisterClass * >, llvm::DenseMap< SID, SID >, llvm::DenseMap< llvm::Value *, llvm::ValueLatticeElement >, llvm::DenseMap< std::pair< llvm::Value *, unsigned >, llvm::ValueLatticeElement >, llvm::DenseMap< llvm::GlobalVariable *, llvm::ValueLatticeElement >, llvm::DenseMap< std::pair< llvm::Function *, unsigned >, unsigned >, llvm::DenseMap< llvm::Value *, detail::DenseSetEmpty, DenseMapInfo< llvm::Value * >, detail::DenseSetPair< llvm::Value * > >, llvm::DenseMap< Edge, detail::DenseSetEmpty, DenseMapInfo< Edge >, detail::DenseSetPair< Edge > >, llvm::DenseMap< llvm::Function *, std::unique_ptr< llvm::PredicateInfo > >, llvm::DenseMap< llvm::Value *, llvm::SmallPtrSet< llvm::User *, 2 > >, llvm::DenseMap< std::pair< const llvm::SCEV *, llvm::Instruction * >, llvm::TrackingVH< llvm::Value > >, llvm::DenseMap< llvm::AssertingVH< llvm::Value >, detail::DenseSetEmpty, DenseMapInfo< llvm::AssertingVH< llvm::Value > >, detail::DenseSetPair< llvm::AssertingVH< llvm::Value > > >, llvm::DenseMap< const llvm::SCEV *, const llvm::Loop * >, llvm::DenseMap< llvm::AssertingVH< llvm::PHINode >, detail::DenseSetEmpty, DenseMapInfo< llvm::AssertingVH< llvm::PHINode > >, detail::DenseSetPair< llvm::AssertingVH< llvm::PHINode > > >, llvm::DenseMap< const SDNode *, SmallVector< SDDbgValue *, 2 > >, llvm::DenseMap< llvm::MachineInstr *, detail::DenseSetEmpty, DenseMapInfo< llvm::MachineInstr * >, detail::DenseSetPair< llvm::MachineInstr * > >, llvm::DenseMap< int, std::vector< llvm::SIRegisterInfo::SpilledReg > >, llvm::DenseMap< Register, unsigned >, llvm::DenseMap< Register, detail::DenseSetEmpty, DenseMapInfo< Register >, detail::DenseSetPair< Register > >, llvm::DenseMap< Register, PrologEpilogSGPRSaveRestoreInfo >, llvm::DenseMap< int, llvm::SIMachineFunctionInfo::VGPRSpillToAGPR >, llvm::DenseMap< Value *, unsigned >, llvm::DenseMap< int, std::deque< llvm::SUnit * > >, llvm::DenseMap< unsigned, llvm::Register >, llvm::DenseMap< const llvm::Function *, llvm::Register >, llvm::DenseMap< int, llvm::Register >, llvm::DenseMap< KeyTy, unsigned >, llvm::DenseMap< const llvm::Type *, unsigned >, llvm::DenseMap< const llvm::Constant *, unsigned >, llvm::DenseMap< const llvm::GlobalVariable *, unsigned >, llvm::DenseMap< const llvm::Argument *, unsigned >, llvm::DenseMap< const llvm::SPIRV::SpecialTypeDescriptor *, unsigned >, llvm::DenseMap< const llvm::MachineFunction *, llvm::DenseMap< llvm::Register, llvm::MachineInstr * > >, llvm::DenseMap< llvm::MachineInstr *, const llvm::Type * >, llvm::DenseMap< const llvm::Type *, llvm::MachineInstr * >, llvm::DenseMap< llvm::BasicBlock *, llvm::Value * >, llvm::DenseMap< BlkT *, BBInfo * >, llvm::DenseMap< const AllocaInst *, MachineFrameInfo::SSPLayoutKind >, llvm::DenseMap< uint64_t, llvm::StringRef >, llvm::DenseMap< const SCEV *, bool >, llvm::DenseMap< const SCEV *, ValueSetVector >, llvm::DenseMap< SCEVCallbackVH, const SCEV *, DenseMapInfo< Value * > >, llvm::DenseMap< llvm::ScalarEvolution::FoldID, const llvm::SCEV * >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallVector< llvm::ScalarEvolution::FoldID, 2 > >, llvm::DenseMap< const llvm::SCEV *, llvm::APInt >, llvm::DenseMap< const llvm::Loop *, BackedgeTakenInfo >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallPtrSet< llvm::PointerIntPair< const llvm::Loop *, 1, bool >, 4 > >, llvm::DenseMap< llvm::PHINode *, llvm::Constant * >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallVector< std::pair< const llvm::Loop *, const llvm::SCEV * >, 2 > >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallVector< llvm::PointerIntPair< const llvm::Loop *, 2, LoopDisposition >, 2 > >, llvm::DenseMap< const llvm::Loop *, LoopProperties >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallVector< llvm::PointerIntPair< const llvm::BasicBlock *, 2, BlockDisposition >, 2 > >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallPtrSet< const llvm::SCEV *, 8 > >, llvm::DenseMap< const llvm::SCEV *, llvm::ConstantRange >, llvm::DenseMap< const llvm::Loop *, llvm::SmallVector< const llvm::SCEVAddRecExpr *, 4 > >, llvm::DenseMap< std::pair< const llvm::SCEVUnknown *, const llvm::Loop * >, std::pair< const llvm::SCEV *, llvm::SmallVector< const llvm::SCEVPredicate *, 3 > > >, llvm::DenseMap< llvm::MachineInstr *, llvm::SUnit * >, llvm::DenseMap< K, llvm::ScopedHashTableVal *, KInfo >, llvm::DenseMap< K, llvm::ScopedHashTableVal *, DenseMapInfo< K > >, llvm::DenseMap< const llvm::SDNode *, NodeExtraInfo >, llvm::DenseMap< llvm::MCSymbol *, llvm::SDNode * >, llvm::DenseMap< const llvm::Value *, llvm::SDValue >, llvm::DenseMap< llvm::MachineBasicBlock *, llvm::SmallVector< unsigned, 4 > >, llvm::DenseMap< BaseTy, detail::DenseSetEmpty, DenseMapInfo< BaseTy >, detail::DenseSetPair< BaseTy > >, llvm::DenseMap< llvm::Init *, detail::DenseSetEmpty, DenseMapInfo< llvm::Init * >, detail::DenseSetPair< llvm::Init * > >, llvm::DenseMap< const MachineInstr *, SlotIndex >, llvm::DenseMap< const Value *, unsigned >, llvm::DenseMap< llvm::AttributeSet, unsigned >, llvm::DenseMap< LatticeKey, LatticeVal >, llvm::DenseMap< std::pair< unsigned, unsigned >, ValueForcePair >, llvm::DenseMap< const BasicBlock *, BlockLifetimeInfo >, llvm::DenseMap< const llvm::BasicBlock *, std::pair< unsigned, unsigned > >, llvm::DenseMap< const llvm::AllocaInst *, unsigned >, llvm::DenseMap< const llvm::BasicBlock *, llvm::SmallVector< std::pair< unsigned, Marker >, 4 > >, llvm::DenseMap< const MCSymbol *, unsigned >, llvm::DenseMap< llvm::SDValue, llvm::SDValue >, llvm::DenseMap< llvm::CachedHashStringRef, size_t >, llvm::DenseMap< unsigned, llvm::SuffixTreeNode * >, llvm::DenseMap< std::pair< const llvm::MachineBasicBlock *, const llvm::Value * >, llvm::Register >, llvm::DenseMap< llvm::PointerIntPair< const llvm::Instruction *, 1, bool >, llvm::Register >, llvm::DenseMap< llvm::SUnit *, std::pair< unsigned, int64_t > >, llvm::DenseMap< std::pair< const MCSymbol *, unsigned >, unsigned >, llvm::DenseMap< const llvm::MDNode *, TBAABaseNodeSummary >, llvm::DenseMap< const llvm::MDNode *, bool >, llvm::DenseMap< llvm::Register, AvailableValsTy >, llvm::DenseMap< unsigned, std::string >, llvm::DenseMap< unsigned int, unsigned int >, llvm::DenseMap< llvm::ThreadPoolTaskGroup *, unsigned >, llvm::DenseMap< const llvm::Value *, detail::DenseSetEmpty, DenseMapInfo< const llvm::Value * >, detail::DenseSetPair< const llvm::Value * > >, llvm::DenseMap< const llvm::MDNode *, detail::DenseSetEmpty, DenseMapInfo< const llvm::MDNode * >, detail::DenseSetPair< const llvm::MDNode * > >, llvm::DenseMap< llvm::AttributeList, detail::DenseSetEmpty, DenseMapInfo< llvm::AttributeList >, detail::DenseSetPair< llvm::AttributeList > >, llvm::DenseMap< llvm::Type *, detail::DenseSetEmpty, DenseMapInfo< llvm::Type * >, detail::DenseSetPair< llvm::Type * > >, llvm::DenseMap< llvm::Value *, SimplifiedAddress >, llvm::DenseMap< int32_t, llvm::Instruction * >, llvm::DenseMap< llvm::VPInstruction *, llvm::InterleaveGroup< llvm::VPInstruction > * >, llvm::DenseMap< std::pair< BasicBlock *, BasicBlock * >, VPValue * >, llvm::DenseMap< BasicBlock *, VPValue * >, llvm::DenseMap< llvm::Instruction *, llvm::VPRecipeBase * >, llvm::DenseMap< const llvm::VPValue *, unsigned >, llvm::DenseMap< VPValue *, Value * >, llvm::DenseMap< const llvm::SCEV *, llvm::Value * >, llvm::DenseMap< llvm::VPValue *, llvm::SmallVector >, llvm::DenseMap< const llvm::VPValue *, llvm::Type * >, llvm::DenseMap< llvm::ElementCount, detail::DenseSetEmpty, DenseMapInfo< llvm::ElementCount >, detail::DenseSetPair< llvm::ElementCount > >, llvm::DenseMap< Value *, VPValue * >, llvm::DenseMap< llvm::PHINode *, unsigned >, llvm::DenseMap< const llvm::SCEV *, llvm::VPValue * >, llvm::DenseMap< VPBlockBase *, std::unique_ptr< DomTreeNodeBase< VPBlockBase > > >, llvm::DenseMap< llvm::SmallVector< llvm::VPValue *, 4 >, llvm::VPInstruction *, BundleDenseMapInfo >, llvm::DenseMap< Type *, unsigned >, llvm::DenseMap< const Metadata *, MDIndex >, llvm::DenseMap< IndexAndAttrSet, unsigned >, llvm::DenseMap< AttributeList, unsigned >, llvm::DenseMap< const llvm::BasicBlock *, unsigned >, llvm::DenseMap< const Instruction *, unsigned >, llvm::DenseMap< ValueMapCVH, ValueT, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< unsigned, llvm::ShapeT >, llvm::DenseMap< PointerUnion< const BasicBlock *, MachineBasicBlock * >, PointerUnion< const BasicBlock *, MachineBasicBlock * > >, llvm::DenseMap< PointerUnion< const BasicBlock *, MachineBasicBlock * >, llvm::SmallPtrSet< PointerUnion< const BasicBlock *, MachineBasicBlock * >, 4 > >, llvm::DenseMap< const llvm::MachineLoop *, std::unique_ptr< llvm::WebAssembly::SortRegion > >, llvm::DenseMap< const llvm::WebAssemblyException *, std::unique_ptr< llvm::WebAssembly::SortRegion > >, llvm::DenseMap< const llvm::MachineBasicBlock *, llvm::WebAssemblyException * >, llvm::DenseMap< const llvm::Instruction *, int >, llvm::DenseMap< const llvm::FuncletPadInst *, int >, llvm::DenseMap< const llvm::InvokeInst *, int >, llvm::DenseMap< llvm::MCSymbol *, std::pair< int, llvm::MCSymbol * > >, llvm::DenseMap< const llvm::BasicBlock *, int >, llvm::DenseMap< int, unsigned >, llvm::DenseMap< const llvm::Value *, size_t >, llvm::DenseMap< uint32_t, uint32_t >, llvm::DenseMap< uint32_t, llvm::StringRef >, llvm::DenseMap< llvm::codeview::GloballyHashedType, llvm::codeview::TypeIndex >, llvm::DenseMap< llvm::codeview::LocallyHashedType, llvm::codeview::TypeIndex >, llvm::DenseMap< llvm::coverage::CounterExpression, unsigned >, llvm::DenseMap< size_t, llvm::DenseSet< size_t > >, llvm::DenseMap< size_t, llvm::SmallVector< unsigned, 0 > >, llvm::DenseMap< unsigned, TVRowPair >, llvm::DenseMap< unsigned, LineColPair >, llvm::DenseMap< std::pair< llvm::RecTy *, llvm::Init * >, llvm::VarInit * >, llvm::DenseMap< std::pair< llvm::TypedInit *, unsigned >, llvm::VarBitInit * >, llvm::DenseMap< std::pair< llvm::Init *, llvm::StringInit * >, llvm::FieldInit * >, llvm::DenseMap< T, uint64_t >, llvm::DenseMap< uint64_t, uint64_t >, llvm::DenseMap< uint64_t, CompileUnit * >, llvm::DenseMap< DeclContext *, detail::DenseSetEmpty, DeclMapInfo, detail::DenseSetPair< DeclContext * > >, llvm::DenseMap< std::pair< unsigned, unsigned >, StringRef >, llvm::DenseMap< unsigned, StringEntry * >, llvm::DenseMap< uint64_t, std::pair< std::string, std::string > >, llvm::DenseMap< const llvm::StringMapEntry *, uint64_t >, llvm::DenseMap< const StringEntry *, DwarfStringPoolEntryWithExtString * >, llvm::DenseMap< const Value *, Type * >, llvm::DenseMap< llvm::gsym::FileEntry, uint32_t >, llvm::DenseMap< uint64_t, llvm::CachedHashStringRef >, llvm::DenseMap< llvm::StringRef, llvm::StringRef >, llvm::DenseMap< llvm::jitlink::Section *, llvm::jitlink::SectionRange >, llvm::DenseMap< uint32_t, EdgeTarget >, llvm::DenseMap< uint32_t, detail::DenseSetEmpty, DenseMapInfo< uint32_t >, detail::DenseSetPair< uint32_t > >, llvm::DenseMap< orc::ExecutorAddr, CIEInformation >, llvm::DenseMap< llvm::orc::ExecutorAddr, llvm::jitlink::Symbol * >, llvm::DenseMap< llvm::StringRef, std::unique_ptr< llvm::jitlink::Section > >, llvm::DenseMap< Symbol *, detail::DenseSetEmpty, DenseMapInfo< Symbol * >, detail::DenseSetPair< Symbol * > >, llvm::DenseMap< unsigned, llvm::jitlink::MachOLinkGraphBuilder::NormalizedSection >, llvm::DenseMap< uint32_t, llvm::jitlink::MachOLinkGraphBuilder::NormalizedSymbol * >, llvm::DenseMap< Block *, detail::DenseSetEmpty, DenseMapInfo< Block * >, detail::DenseSetPair< Block * > >, llvm::DenseMap< llvm::StringRef, StubMapEntry >, llvm::DenseMap< ObjectKey, Value, llvm::DenseMapInfo< StringRef > >, llvm::DenseMap< const llvm::object::coff_section *, std::vector< llvm::object::RelocationRef > >, llvm::DenseMap< std::pair< unsigned short, unsigned >, std::unique_ptr< const llvm::mca::InstrDesc > >, llvm::DenseMap< std::pair< const llvm::MCInst *, unsigned >, std::unique_ptr< const llvm::mca::InstrDesc > >, llvm::DenseMap< unsigned, std::unique_ptr< llvm::mca::MemoryGroup > >, llvm::DenseMap< uint64_t, llvm::memprof::Frame >, llvm::DenseMap< uint64_t, llvm::SmallVector< uint64_t > >, llvm::DenseMap< uint64_t, std::string >, llvm::DenseMap< llvm::AllocaInst *, unsigned >, llvm::DenseMap< uint32_t, std::vector< MutableArrayRef< uint8_t > > >, llvm::DenseMap< llvm::CallInst *, llvm::CallBase * >, llvm::DenseMap< ValuePairTy, bool >, llvm::DenseMap< const llvm::Value *, std::pair< llvm::WeakVH, llvm::WeakTrackingVH > >, llvm::DenseMap< llvm::CachedHashStringRef, detail::DenseSetEmpty, DenseMapInfo< llvm::CachedHashStringRef >, detail::DenseSetPair< llvm::CachedHashStringRef > >, llvm::DenseMap< size_t, llvm::objcopy::coff::Symbol * >, llvm::DenseMap< ssize_t, llvm::objcopy::coff::Section * >, llvm::DenseMap< llvm::objcopy::elf::SectionBase *, std::vector< uint8_t > >, llvm::DenseMap< uint32_t, std::pair< size_t, std::unique_ptr< char[]> > >, llvm::DenseMap< uint32_t, std::string >, llvm::DenseMap< minidump::StreamType, std::size_t >, llvm::DenseMap< unsigned, OptRange >, llvm::DenseMap< SymbolStringPtr, ExecutorSymbolDef >, llvm::DenseMap< JITDylib *, SymbolNameSet >, llvm::DenseMap< llvm::orc::JITDylib *, llvm::orc::ExecutorAddr >, llvm::DenseMap< llvm::orc::ExecutorAddr, llvm::orc::JITDylib * >, llvm::DenseMap< llvm::orc::JITDylib *, llvm::orc::SymbolLookupSet >, llvm::DenseMap< MaterializationResponsibility *, JITLinkSymbolSet >, llvm::DenseMap< llvm::orc::MaterializationResponsibility *, llvm::orc::ExecutorAddrRange >, llvm::DenseMap< ResourceKey, std::vector< llvm::orc::ExecutorAddrRange > >, llvm::DenseMap< llvm::orc::JITDylib *, llvm::orc::ELFNixJITDylibInitializers >, llvm::DenseMap< llvm::orc::JITDylib *, uint64_t >, llvm::DenseMap< llvm::orc::ExecutorAddr, std::shared_ptr< llvm::unique_function > >, llvm::DenseMap< Alias, AliaseeDetails >, llvm::DenseMap< void *, Reservation >, llvm::DenseMap< ExecutorAddr, Allocation >, llvm::DenseMap< void *, std::vector< llvm::orc::ItaniumCXAAtExitSupport::AtExitRecord > >, llvm::DenseMap< SymbolStringPtr, SymbolTableEntry >, llvm::DenseMap< SymbolStringPtr, std::shared_ptr< UnmaterializedInfo > >, llvm::DenseMap< SymbolStringPtr, MaterializingInfo >, llvm::DenseMap< llvm::orc::ResourceTracker *, SymbolNameVector >, llvm::DenseMap< llvm::orc::ResourceTracker *, llvm::DenseSet< llvm::orc::MaterializationResponsibility * > >, llvm::DenseMap< SymbolStringPtr, SymbolAliasMapEntry >, llvm::DenseMap< llvm::orc::JITDylib *, ObjCImageInfo >, llvm::DenseMap< llvm::orc::ExecutorAddr, uint64_t >, llvm::DenseMap< SymbolStringPtr, JITSymbolFlags >, llvm::DenseMap< ResourceKey, std::vector< llvm::jitlink::JITLinkMemoryManager::FinalizedAlloc > >, llvm::DenseMap< llvm::orc::SymbolStringPtr, llvm::DenseSet >, llvm::DenseMap< const Block *, llvm::DenseSet< Block * > >, llvm::DenseMap< const Symbol *, llvm::orc::SymbolStringPtr >, llvm::DenseMap< const Block *, BlockSymbolDependencies >, llvm::DenseMap< SymbolStringPtr, detail::DenseSetEmpty, DenseMapInfo< SymbolStringPtr >, detail::DenseSetPair< SymbolStringPtr > >, llvm::DenseMap< ResourceKey, std::vector< MemoryManagerUP > >, llvm::DenseMap< uint64_t, IncomingWFRHandler >, llvm::DenseMap< uint64_t, std::promise< shared::WrapperFunctionResult > * >, llvm::DenseMap< TargetFAddr, SymbolNameSet >, llvm::DenseMap< llvm::orc::SymbolStringPtr, llvm::MemoryBufferRef >, llvm::DenseMap< void *, detail::DenseSetEmpty, DenseMapInfo< void * >, detail::DenseSetPair< void * > >, llvm::DenseMap< void *, Allocation >, llvm::DenseMap< llvm::codeview::CVRecord, detail::DenseSetEmpty, llvm::pdb::SymbolDenseMapInfo, detail::DenseSetPair< llvm::codeview::CVRecord > >, llvm::DenseMap< llvm::codeview::TypeIndex, uint32_t >, llvm::DenseMap< std::pair< llvm::codeview::TypeIndex, uint32_t >, uint32_t >, llvm::DenseMap< std::pair< uint32_t, uint32_t >, uint32_t >, llvm::DenseMap< std::pair< uint16_t, uint32_t >, uint32_t >, llvm::DenseMap< uint16_t, std::vector< LineTableEntry > >, llvm::DenseMap< uint32_t, llvm::MachineBasicBlock * >, llvm::DenseMap< uint32_t, RefMap >, llvm::DenseMap< const llvm::Value *, llvm::Align >, llvm::DenseMap< llvm::hash_code, uint64_t >, llvm::DenseMap< llvm::sampleprof::FunctionId, unsigned >, llvm::DenseMap< llvm::sampleprof::SampleContext, unsigned >, llvm::DenseMap< const FunctionSamples *, BodySampleCoverageMap >, llvm::DenseMap< NodeRef, unsigned >, llvm::DenseMap< const EdgeType *, detail::DenseSetEmpty, DenseMapInfo< const EdgeType * >, detail::DenseSetPair< const EdgeType * > >, llvm::DenseMap< const TreeEntry *, llvm::Instruction * >, llvm::DenseMap< const TreeEntry *, detail::DenseSetEmpty, DenseMapInfo< const TreeEntry * >, detail::DenseSetPair< const TreeEntry * > >, llvm::DenseMap< Value *, SmallPtrSet< const TreeEntry *, 4 > >, llvm::DenseMap< AliasCacheKey, bool >, llvm::DenseMap< size_t, detail::DenseSetEmpty, DenseMapInfo< size_t >, detail::DenseSetPair< size_t > >, llvm::DenseMap< const TreeEntry *, std::pair< uint64_t, bool > >, llvm::DenseMap< llvm::Instruction *, ScheduleData * >, llvm::DenseMap< llvm::Value *, llvm::SmallDenseMap< llvm::Value *, ScheduleData * > >, llvm::DenseMap< ScheduleData *, detail::DenseSetEmpty, DenseMapInfo< ScheduleData * >, detail::DenseSetPair< ScheduleData * > >, llvm::DenseMap< uint64_t, std::unique_ptr< Module > >, llvm::DenseMap< EdgeIdentifier, EdgeAttribute >, llvm::DenseMap< VertexIdentifier, VertexAttribute >, llvm::DenseMap< VertexIdentifier, NeighborSetT >, llvm::DenseMap< unsigned, TrieNode * >, llvm::DenseMap< int, int >, llvm::DenseMap< llvm::StringRef, llvm::DenseMap >, llvm::SmallDenseMap< const llvm::SCEV *, const llvm::SCEV * >, llvm::SmallDenseMap< ValueT, detail::DenseSetEmpty, 4, DenseMapInfo< ValueT >, detail::DenseSetPair< ValueT > >, llvm::SmallDenseMap< KeyT, unsigned, N >, llvm::SmallDenseMap< T, ptrdiff_t >, llvm::SmallDenseMap< Instruction *, unsigned >, llvm::SmallDenseMap< Instruction *, uint64_t >, llvm::SmallDenseMap< llvm::Value *, detail::DenseSetEmpty, 4, DenseMapInfo< llvm::Value * >, detail::DenseSetPair< llvm::Value * > >, llvm::SmallDenseMap< const GlobalValue *, ModRefInfo, 16 >, llvm::SmallDenseMap< llvm::DebugVariable, const llvm::DILocation *, 8 >, llvm::SmallDenseMap< llvm::Function *, llvm::DISubprogram *, 16 >, llvm::SmallDenseMap< std::pair< BasicBlock *, Value * >, Value * >, llvm::SmallDenseMap< LocPair, CacheEntry, 8 >, llvm::SmallDenseMap< int, llvm::KernArgPreloadDescriptor >, llvm::SmallDenseMap< const llvm::GlobalValue *, unsigned, 4 >, llvm::SmallDenseMap< llvm::AnalysisKey *, bool, 8 >, llvm::SmallDenseMap< llvm::Use *, unsigned, N >, llvm::SmallDenseMap< llvm::Value *, unsigned, N >, llvm::SmallDenseMap< const llvm::BasicBlock *, uint32_t >, llvm::SmallDenseMap< LoopData, uint32_t >, llvm::SmallDenseMap< llvm::LazyCallGraph::RefSCC *, ptrdiff_t >, llvm::SmallDenseMap< llvm::LazyCallGraph::SCC *, ptrdiff_t >, llvm::SmallDenseMap< std::pair< llvm::LazyCallGraph::Node *, llvm::LazyCallGraph::SCC * >, detail::DenseSetEmpty, InlineBuckets, DenseMapInfo< std::pair< llvm::LazyCallGraph::Node *, llvm::LazyCallGraph::SCC * > >, detail::DenseSetPair< std::pair< llvm::LazyCallGraph::Node *, llvm::LazyCallGraph::SCC * > > >, llvm::SmallDenseMap< llvm::SDValue, unsigned, 8 >, llvm::SmallDenseMap< unsigned, llvm::SDValue, 8 >, llvm::SmallDenseMap< unsigned, unsigned, 8 >, llvm::SmallDenseMap< unsigned, std::pair< unsigned, unsigned >, 8 >, llvm::SmallDenseMap< llvm::DomTreeNodeBase, detail::DenseSetEmpty, InlineBuckets, DenseMapInfo< llvm::DomTreeNodeBase >, detail::DenseSetPair< llvm::DomTreeNodeBase > >, llvm::SmallDenseMap< llvm::LLT, unsigned, 64 >, llvm::SmallDenseMap< llvm::Register, llvm::KnownBits, 16 >, llvm::SmallDenseMap< NodePtr, DeletesInserts >, llvm::SmallDenseMap< llvm::SDNode *, int >, llvm::SmallDenseMap< const llvm::Value *, int >, llvm::SmallDenseMap< llvm::BasicBlock *, DeletesInserts >, llvm::SmallDenseMap< const llvm::RecurrenceDescriptor *, unsigned, N >, llvm::SmallDenseMap< std::pair< llvm::BasicBlock *, llvm::BasicBlock * >, detail::DenseSetEmpty, InlineBuckets, DenseMapInfo< std::pair< llvm::BasicBlock *, llvm::BasicBlock * > >, detail::DenseSetPair< std::pair< llvm::BasicBlock *, llvm::BasicBlock * > > >, llvm::SmallDenseMap< llvm::BasicBlock *, llvm::SmallVector< llvm::BasicBlock * >, 8 >, llvm::SmallDenseMap< llvm::BasicBlock *, llvm::DPMarker * >, llvm::SmallDenseMap< llvm::Loop *, ptrdiff_t >, llvm::SmallDenseMap< llvm::LazyCallGraph::SCC *, int, 4 >, llvm::SmallDenseMap< unsigned, unsigned, N >, llvm::SmallDenseMap< llvm::Value *, llvm::Value * >, llvm::SmallDenseMap< llvm::Instruction *, llvm::SizeOffsetAPInt, 8 >, llvm::SmallDenseMap< const llvm::Value *, unsigned, N >, llvm::SmallDenseMap< llvm::AnalysisKey *, llvm::TinyPtrVector< llvm::AnalysisKey * >, 2 >, llvm::SmallDenseMap< AnalysisID, llvm::ImmutablePass *, 8 >, llvm::SmallDenseMap< void *, std::pair< llvm::PointerUnion, uint64_t >, 4 >, llvm::SmallDenseMap< unsigned, SPIRV::InstructionSet::InstructionSet >, llvm::SmallDenseMap< llvm::PointerIntPair< llvm::Value *, 1 >, llvm::ScalarEvolution::ExitLimit >, llvm::SmallDenseMap< const llvm::Value *, bool, 8 >, llvm::SmallDenseMap< llvm::VPBasicBlock *, llvm::BasicBlock * >, llvm::SmallDenseMap< const llvm::VPBlockBase *, unsigned >, llvm::SmallDenseMap< unsigned, MDRange, 1 >, llvm::SmallDenseMap< uint32_t, llvm::bfi_detail::IrreducibleGraph::IrrNode *, 4 >, llvm::SmallDenseMap< uint64_t, uint64_t, 1 >, llvm::SmallDenseMap< llvm::StructType *, LegacyStructLayout >, llvm::SmallDenseMap< ResourceRef, unsigned >, llvm::SmallDenseMap< TraitProperty, llvm::APInt >, llvm::SmallDenseMap< llvm::Value *, TreeEntry * >, llvm::SmallDenseMap< llvm::Value *, llvm::SmallVector< TreeEntry * > >, llvm::SmallDenseMap< llvm::Value *, unsigned >, llvm::SmallDenseMap< std::pair< unsigned, unsigned >, unsigned, 8 >, llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >, and llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >.
Public Types
using size_type = unsigned
using key_type = KeyT
using mapped_type = ValueT
using value_type = BucketT
using iterator = DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT >
using const_iterator = DenseMapIterator< KeyT, ValueT, KeyInfoT, BucketT, true >
Public Member Functions
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
unsigned size () const
void reserve (size_type NumEntries)
Grow the densemap so that it can contain at least NumEntries items before resizing again.
void clear ()
bool contains (const_arg_type_t< KeyT > Val) const
Return true if the specified key is in the map, false otherwise.
size_type count (const_arg_type_t< KeyT > Val) const
Return 1 if the specified key is in the map, 0 otherwise.
iterator find (const_arg_type_t< KeyT > Val)
const_iterator find (const_arg_type_t< KeyT > Val) const
template<class LookupKeyT >
iterator find_as (const LookupKeyT &Val)
Alternate version of find() which allows a different, and possibly less expensive, key type.
template<class LookupKeyT >
const_iterator find_as (const LookupKeyT &Val) const
ValueT lookup (const_arg_type_t< KeyT > Val) const
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
const ValueT & at (const_arg_type_t< KeyT > Val) const
at - Return the entry for the specified key, or abort if no such entry exists.
std::pair< iterator, bool > insert (const std::pair< KeyT, ValueT > &KV)
std::pair< iterator, bool > insert (std::pair< KeyT, ValueT > &&KV)
template<typename... Ts>
std::pair< iterator, bool > try_emplace (KeyT &&Key, Ts &&... Args)
template<typename... Ts>
std::pair< iterator, bool > try_emplace (const KeyT &Key, Ts &&... Args)
template<typename LookupKeyT >
std::pair< iterator, bool > insert_as (std::pair< KeyT, ValueT > &&KV, const LookupKeyT &Val)
Alternate version of insert() which allows a different, and possibly less expensive, key type.
template<typename InputIt >
void insert (InputIt I, InputIt E)
insert - Range insertion of pairs.
ValueT & getOrInsertDefault (KeyT &&Key)
Returns the value associated to the key in the map if it exists.
ValueT & getOrInsertDefault (const KeyT &Key)
Returns the value associated to the key in the map if it exists.
bool erase (const KeyT &Val)
void erase (iterator I)
value_type & FindAndConstruct (const KeyT &Key)
ValueT & operator[] (const KeyT &Key)
value_type & FindAndConstruct (KeyT &&Key)
ValueT & operator[] (KeyT &&Key)
bool isPointerIntoBucketsArray (const void *Ptr) const
isPointerIntoBucketsArray - Return true if the specified pointer points somewhere into the DenseMap's array of buckets (i.e.
const void * getPointerIntoBucketsArray () const
getPointerIntoBucketsArray() - Return an opaque pointer into the buckets array.
size_t getMemorySize () const
Return the approximate size (in bytes) of the actual map.
Public Member Functions inherited from llvm::DebugEpochBase
void incrementEpoch ()
Protected Member Functions
DenseMapBase ()=default
void destroyAll ()
void initEmpty ()
unsigned getMinBucketToReserveForEntries (unsigned NumEntries)
Returns the number of buckets to allocate to ensure that the DenseMap can accommodate NumEntries without need to grow().
void moveFromOldBuckets (BucketT *OldBucketsBegin, BucketT *OldBucketsEnd)
template<typename OtherBaseT >
void copyFrom (const DenseMapBase< OtherBaseT, KeyT, ValueT, KeyInfoT, BucketT > &other)
Static Protected Member Functions
static unsigned getHashValue (const KeyT &Val)
template<typename LookupKeyT >
static unsigned getHashValue (const LookupKeyT &Val)
static const KeyT getEmptyKey ()
static const KeyT getTombstoneKey ()
Detailed Description
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT, typename BucketT>
class llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >
Definition at line 61 of file DenseMap.h.
Member Typedef Documentation
const_iterator
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::const_iterator = DenseMapIterator<KeyT, ValueT, KeyInfoT, BucketT, true>
Definition at line 72 of file DenseMap.h.
iterator
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::iterator = DenseMapIterator<KeyT, ValueT, KeyInfoT, BucketT>
Definition at line 71 of file DenseMap.h.
key_type
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::key_type = KeyT
Definition at line 67 of file DenseMap.h.
mapped_type
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::mapped_type = ValueT
Definition at line 68 of file DenseMap.h.
size_type
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size_type = unsigned
Definition at line 66 of file DenseMap.h.
value_type
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > using llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::value_type = BucketT
Definition at line 69 of file DenseMap.h.
Constructor & Destructor Documentation
DenseMapBase()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::DenseMapBase () protected default
Member Function Documentation
at()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > const ValueT & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::at (const_arg_type_t< KeyT > Val) const inline
at - Return the entry for the specified key, or abort if no such entry exists.
Definition at line 211 of file DenseMap.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find().
Referenced by llvm::LoopVectorizationCostModel::getCallWideningDecision().
begin() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin () inline
Definition at line 75 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
Referenced by llvm::SlotTracker::as_begin(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::begin(), llvm::AA::PointerInfo::State::begin(), checkNumberingAndReplaceCommutative(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), llvm::computeLTOCacheKey(), findIrreducibleHeaders(), lowerVECTOR_SHUFFLE(), matchScalarReduction(), llvm::SlotTracker::mdn_begin(), SRAGlobal(), llvm::UnrollLoop(), and unswitchNontrivialInvariants().
begin() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin () const inline
Definition at line 87 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
clear()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear () inline
Definition at line 110 of file DenseMap.h.
References assert(), E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getEmptyKey(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey(), llvm::DebugEpochBase::incrementEpoch(), and P.
Referenced by analyzeLoopUnrollCost(), llvm::SampleProfileInference< FT >::apply(), buildVRegToDbgValueMap(), llvm::BranchProbabilityInfo::calculate(), llvm::AliasSetTracker::clear(), llvm::LoopAccessInfoManager::clear(), llvm::LoopBlocksDFS::clear(), llvm::GCModuleInfo::clear(), llvm::GISelWorkList< N >::clear(), llvm::SDDbgInfo::clear(), llvm::dwarf_linker::IndexedValuesMap< T >::clear(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::clear(), llvm::PredIteratorCache::clear(), llvm::mca::InstrBuilder::clear(), llvm::sampleprofutil::SampleCoverageTracker::clear(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::clear(), LiveDebugValues::DbgOpIDMap::clear(), LiveDebugValues::MLocTracker::clear(), llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::clear(), llvm::objcarc::ProvenanceAnalysis::clear(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), llvm::slpvectorizer::BoUpSLP::deleteTree(), findCandidateStructures(), llvm::symbolize::MarkupFilter::finish(), llvm::ScalarEvolution::forgetAllLoops(), llvm::MemoryDependenceResults::getDependency(), llvm::DOTGraphTraits< MachineBlockFrequencyInfo * >::getNodeLabel(), llvm::MachineSSAUpdater::Initialize(), llvm::SSAUpdater::Initialize(), INITIALIZE_PASS(), llvm::Attributor::internalizeFunctions(), llvm::LoopVectorizationCostModel::invalidateCostModelingDecisions(), TransferTracker::loadInlocs(), llvm::dwarf_linker::parallel::CompileUnit::maybeResetToLoadedStage(), mergeConstants(), llvm::SlotTracker::purgeFunction(), TransferTracker::redefVar(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::releaseMemory(), llvm::GISelCSEInfo::releaseMemory(), llvm::LoopInfoBase< BlockT, LoopT >::releaseMemory(), llvm::SlotIndexes::releaseMemory(), removeRedundantDbgLocsUsingBackwardScan(), llvm::SMSchedule::reset(), llvm::MCStreamer::reset(), llvm::DominatorTreeBase< NodeT, IsPostDom >::reset(), llvm::SplitEditor::reset(), llvm::LiveRangeCalc::resetLiveOutMap(), llvm::InstCombinerImpl::SliceUpIllegalIntegerPHI(), TransferTracker::transferMlocs(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::InstructionWorklist::zap(), and llvm::ScalarEvolution::~ScalarEvolution().
contains()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::contains (const_arg_type_t< KeyT > Val) const inline
Return true if the specified key is in the map, false otherwise.
Definition at line 145 of file DenseMap.h.
Referenced by addConstantsToTrack(), llvm::VPlan::addSCEVExpansion(), buildFrameDebugInfo(), cacheDIVar(), checkDependencies(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), collectRegionsConstants(), llvm::IRSimilarity::IRSimilarityCandidate::compareAssignmentMapping(), llvm::computeEHOnlyBlocks(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalRelationFrom(), createPHIsForCMOVsInSinkBB(), createPHIsForSelects(), llvm::MachineFunction::deleteMachineInstr(), LiveDebugValues::MLocTracker::getLocID(), llvm::AbstractDependenceGraphBuilder< GraphType >::getOrdinal(), llvm::DataDependenceGraph::getPiBlock(), llvm::Triple::getVulkanVersion(), llvm::LoopVectorizationCostModel::getWideningCost(), llvm::SIMachineFunctionInfo::hasPrologEpilogSGPRSpillEntry(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::InterleaveGroup< InstTy >::insertMember(), llvm::IRSimilarity::IRSimilarityCandidate::IRSimilarityCandidate(), llvm::coverage::MCDCRecord::isConditionIndependencePairCovered(), llvm::mca::LSUnitBase::isValidGroupID(), mapInputsToGVNs(), relocationViaAlloca(), remapExtractedInputs(), llvm::SlotIndexes::repairIndexesInRange(), rewriteGEPAsOffset(), llvm::HipStdParAllocationInterpositionPass::run(), runAttributorOnFunctions(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), useFuncSeen(), and llvm::InstCombinerImpl::visitShuffleVectorInst().
copyFrom()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<typename OtherBaseT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::copyFrom (const DenseMapBase< OtherBaseT, KeyT, ValueT, KeyInfoT, BucketT > & other) inline protected
Definition at line 448 of file DenseMap.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getEmptyKey(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey().
count()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > size_type llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count (const_arg_type_t< KeyT > Val) const inline
Return 1 if the specified key is in the map, 0 otherwise.
Definition at line 151 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::contains().
Referenced by llvm::AA::PointerInfo::State::addAccess(), llvm::orc::addAliases(), llvm::InstrEmitter::AddDbgValueLocationOps(), llvm::pdb::PDBFileBuilder::addNamedStream(), llvm::VPlan::addVPValue(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::allocate(), analyzeLoopUnrollCost(), llvm::HexagonSubtarget::CallMutation::apply(), buildClonedLoops(), llvm::calculateCXXStateForAsynchEH(), calculatePrevailingSummary(), llvm::calculateSEHStateForAsynchEH(), llvm::orc::SimpleRemoteEPC::callWrapperAsync(), llvm::ComputeCrossModuleImport(), computeImportForFunction(), llvm::computeMinimumValueSizes(), llvm::EHStreamer::computePadMap(), llvm::StringTableBuilder::contains(), llvm::ModifiedPostOrder< ContextT >::count(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::count(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::count(), llvm::GISelCSEInfo::countOpcodeHit(), llvm::VPRecipeBuilder::createBlockInMask(), CreateGCRelocates(), eliminateDeadSwitchCases(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::ModuleSummaryIndex::exportToDot(), findArgumentCopyElisionCandidates(), findBasePointer(), findIrreducibleHeaders(), llvm::formLCSSAForInstructions(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getCachedResult(), llvm::ModifiedPostOrder< ContextT >::getIndex(), llvm::PPCRegisterInfo::getMappedIdxOpcForImmOpc(), llvm::VPRecipeBuilder::getRecipe(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), getUnwindDestToken(), getUnwindDestTokenHelper(), llvm::VPlan::getVPValue(), llvm::VPlan::getVPValueOrAddLiveIn(), HandleInlinedEHPad(), handleNewDebugValue(), llvm::MachineFunction::hasCallSiteBeginLabel(), llvm::SlotIndexes::hasIndex(), llvm::dwarf_linker::classic::CompileUnit::hasLabelAt(), llvm::dwarf_linker::parallel::CompileUnit::hasLabelAt(), llvm::LoopBlocksDFS::hasPreorder(), llvm::SSAUpdater::HasValueForBlock(), llvm::MachineSSAUpdater::HasValueForBlock(), llvm::MachineFunction::hasWasmLandingPadIndex(), insertRelocationStores(), insertRematerializationStores(), llvm::orc::MaterializationUnit::Interface::Interface(), llvm::orc::IRMaterializationUnit::IRMaterializationUnit(), llvm::ARMBaseInstrInfo::isFpMLxInstruction(), llvm::orc::Platform::lookupInitSymbols(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerStatepointMetaArgs(), llvm::PeelingModuloScheduleExpander::moveStageBetweenBlocks(), llvm::PPCRegisterInfo::needsFrameBaseReg(), llvm::NodeSet::NodeSet(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved(), llvm::PeelSingleBlockLoop(), ProcessSDDbgValues(), llvm::VPRecipeBuilder::recordRecipeOf(), llvm::MemoryDependenceResults::removeInstruction(), llvm::objcopy::macho::Object::removeSections(), llvm::slpvectorizer::BoUpSLP::reorderBottomToTop(), llvm::slpvectorizer::BoUpSLP::reorderTopToBottom(), llvm::scc_iterator< GraphT, GT >::ReplaceNode(), llvm::objcopy::elf::Object::replaceSections(), rewrite(), selectIncomingValueForBlock(), llvm::VPRecipeBuilder::setRecipe(), llvm::ModuloSchedule::setStage(), setupBranchForGuard(), stashEntryDbgValues(), SwitchToLookupTable(), llvm::orc::DLLImportDefinitionGenerator::tryToGenerate(), llvm::GenericConvergenceVerifier< ContextT >::verify(), llvm::BlockFrequencyInfoImpl< BT >::verifyMatch(), and llvm::SCEVLoopAddRecRewriter::visitAddRecExpr().
destroyAll()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll () inline protected
Definition at line 387 of file DenseMap.h.
References E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getEmptyKey(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey(), and P.
empty()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty () const inline
Definition at line 98 of file DenseMap.h.
Referenced by llvm::ScalarEvolution::applyLoopGuards(), llvm::SlotTracker::as_empty(), assignSections(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::BranchProbabilityInfo::calculate(), TransferTracker::checkInstForNewValues(), checkNumberingAndReplaceCommutative(), CompactSwizzlableVector(), llvm::LoopVectorizationCostModel::computeMaxVF(), llvm::SSPLayoutInfo::copyToMachineFrameInfo(), llvm::objcarc::createCallInstWithColors(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalRelationFrom(), llvm::orc::RTDyldObjectLinkingLayer::emit(), llvm::orc::CompileOnDemandLayer::emit(), llvm::GISelWorkList< N >::empty(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::empty(), llvm::ModuleSummaryIndex::exportToDot(), llvm::GISelWorkList< N >::finalize(), findArgParts(), genNeg(), llvm::Attributor::getAttrsFromAssumes(), llvm::MachineFunction::hasAnyCallSiteLabel(), llvm::MachineFunction::hasAnyCallSiteLandingPad(), llvm::MachineFunction::hasAnyWasmLandingPadIndex(), llvm::MachineFunction::hasCallSiteLandingPad(), INITIALIZE_PASS(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::AddressPool::isEmpty(), llvm::VirtRegMap::isShapeMapEmpty(), llvm::TargetLoweringBase::isSlowDivBypassed(), matchScalarReduction(), llvm::SlotTracker::mdn_empty(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved(), populateEHOperandBundle(), ProfitableToMerge(), promoteArguments(), llvm::GISelWorkList< N >::remove(), RemoveFromReverseMap(), ReorganizeVector(), llvm::SlotIndexes::runOnMachineFunction(), llvm::SwingSchedulerDAG::schedule(), llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::shutdown(), SRAGlobal(), llvm::lto::thinBackend(), llvm::at::trackAssignments(), llvm::orc::ReexportsGenerator::tryToGenerate(), llvm::orc::EPCDynamicLibrarySearchGenerator::tryToGenerate(), llvm::orc::DynamicLibrarySearchGenerator::tryToGenerate(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), llvm::InstructionWorklist::zap(), llvm::AddrLabelMap::~AddrLabelMap(), llvm::ReplaceableMetadataImpl::~ReplaceableMetadataImpl(), llvm::orc::RTDyldObjectLinkingLayer::~RTDyldObjectLinkingLayer(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::~ScopedHashTable(), and llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::~SimpleExecutorMemoryManager().
end() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end () inline
Definition at line 84 of file DenseMap.h.
Referenced by llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::add(), llvm::CFGMST< Edge, BBInfo >::addEdge(), llvm::GCNDownwardRPTracker::advanceBeforeNext(), AreEquivalentPhiNodes(), llvm::SlotTracker::as_end(), assignSections(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::at(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::at(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::begin(), buildClonedLoopBlocks(), llvm::orc::SimpleRemoteEPC::callWrapperAsync(), llvm::mca::ResourceManager::checkAvailability(), checkHoistValue(), llvm::SIMachineFunctionInfo::checkIndexInPrologEpilogSGPRSpills(), TransferTracker::checkInstForNewValues(), checkNumberingAndReplaceCommutative(), TransferTracker::clobberMloc(), llvm::JumpThreadingPass::cloneInstructions(), llvm::DILocalScope::cloneScopeForSubprogram(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), llvm::DominatorTreeBase< NodeT, IsPostDom >::compare(), llvm::ObjectSizeOffsetEvaluator::compute(), computeBaseDerivedRelocateMap(), llvm::EHStreamer::computeCallSiteTable(), llvm::ComputeCrossModuleImport(), computeDomSubtreeCost(), llvm::computeLTOCacheKey(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::DomConditionCache::conditionsFor(), LiveDebugValues::VLocTracker::considerOverlaps(), llvm::ScalarEvolution::containsAddRecurrence(), llvm::MachineFunction::copyCallSiteInfo(), llvm::SSPLayoutInfo::copyToMachineFrameInfo(), llvm::sampleprofutil::SampleCoverageTracker::countUsedRecords(), llvm::VPRecipeBuilder::createEdgeMask(), createSwitchStatement(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::deallocate(), decodeBBAddrMapImpl(), decodeCondBranch(), DPValuesRemoveRedundantDbgInstrsUsingForwardScan(), llvm::JumpThreadingPass::duplicateCondBranchOnPHIIntoPred(), llvm::InstrEmitter::EmitDbgInstrRef(), emitGlobalAliasInline(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::end(), llvm::AA::PointerInfo::State::end(), llvm::MachineFunction::eraseCallSiteInfo(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::finalize(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as(), llvm::CFGMST< Edge, BBInfo >::findBBInfo(), findCandidateStructures(), findDuplicateOutputBlock(), findExtractedInputToOverallInputMapping(), findInsertLocation(), findIrreducibleHeaders(), LiveDebugValues::InstrRefBasedLDV::findLocationForMemOperand(), findOrCreatePHIBlock(), findOutputMapping(), findOutputValueInRegion(), FoldCondBranchOnValueKnownInPredecessorImpl(), llvm::IRSimilarity::IRSimilarityCandidate::fromCanonicalNum(), llvm::IRSimilarity::IRSimilarityCandidate::fromGVN(), llvm::gatherImportedSummariesForModule(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::AssumptionCacheTracker::getAssumptionCache(), llvm::SlotTracker::getAttributeGroupSlot(), llvm::VPRecipeBuilder::getBlockInMask(), llvm::SelectionDAG::getCallSiteInfo(), llvm::IRSimilarity::IRSimilarityCandidate::getCanonicalNum(), llvm::ARMFunctionInfo::getCoalescedWeight(), llvm::PseudoProbeManager::getDesc(), llvm::dwarf_linker::parallel::CompileUnit::getDirAndFilenameFromLineTable(), llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::getExistingEntry(), llvm::ScalarEvolution::getExistingSCEV(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::getExistingValueState(), llvm::dwarf_linker::parallel::CompileUnit::getFileName(), llvm::GCModuleInfo::getFunctionInfo(), llvm::SlotTracker::getGlobalSlot(), llvm::SlotTracker::getGUIDSlot(), llvm::IRSimilarity::IRSimilarityCandidate::getGVN(), getGVNForPHINode(), llvm::SelectionDAG::getHeapAllocSite(), llvm::SlotIndexes::getIndexAfter(), llvm::SlotIndexes::getIndexBefore(), llvm::SwingSchedulerDAG::getInstrBaseReg(), llvm::ValueEnumerator::getInstructionID(), llvm::SlotIndexes::getInstructionIndex(), llvm::SCCPInstVisitor::getLatticeValueFor(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::SlotTracker::getLocalSlot(), getMappedReg(), llvm::DILocation::getMergedLocation(), llvm::SlotTracker::getMetadataSlot(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::SelectionDAG::getNoMergeSiteInfo(), llvm::ARMFunctionInfo::getOriginalCPIdx(), llvm::SelectionDAG::getPCSections(), llvm::object::ELFObjectFileBase::getPltEntries(), getPoisonFor(), llvm::LoopBlocksDFS::getPostorder(), llvm::SCCPInstVisitor::getPredicateInfoFor(), getPredState(), llvm::SIMachineFunctionInfo::getPrologEpilogSGPRSaveRestoreInfo(), llvm::object::MinidumpFile::getRawStream(), llvm::SIMachineFunctionInfo::getScratchSGPRCopyDstReg(), llvm::SDDbgInfo::getSDDbgValues(), llvm::SIMachineFunctionInfo::getSGPRSpillToPhysicalVGPRLanes(), llvm::SIMachineFunctionInfo::getSGPRSpillToVirtualVGPRLanes(), llvm::VPSlotTracker::getSlot(), llvm::ModuloSchedule::getStage(), llvm::SCCPInstVisitor::getStructLatticeValueFor(), getSuccState(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::SPIRVGlobalRegistry::getTypeForSPIRVType(), llvm::ValueEnumerator::getTypeID(), llvm::dxil::ValueEnumerator::getTypeID(), getUnwindDestToken(), getUnwindDestTokenHelper(), llvm::dwarf_linker::IndexedValuesMap< T >::getValueIndex(), getValueOnFirstIteration(), llvm::slpvectorizer::BoUpSLP::getVectorElementSize(), llvm::SIMachineFunctionInfo::getVGPRToAGPRSpill(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), llvm::LoopVectorizationCostModel::getWideningDecision(), getWorklist(), llvm::LoopBlocksDFS::hasPostorder(), llvm::FunctionImporter::importFunctions(), INITIALIZE_PASS(), insertDPValuesForPHIs(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), isBigEndian(), llvm::coverage::MCDCRecord::isConditionIndependencePairCovered(), llvm::isEqual(), llvm::ARMBaseInstrInfo::isFpMLxInstruction(), IsValueFullyAvailableInBlock(), TransferTracker::loadInlocs(), loadObj(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::lookup(), llvm::AssumptionCacheTracker::lookupAssumptionCache(), llvm::codeview::DebugChecksumsSubsection::mapChecksumOffset(), llvm::CombinerHelper::matchLoadOrCombine(), matchScalarReduction(), llvm::SlotTracker::mdn_end(), mergeConstants(), migrateDebugInfo(), llvm::MachineFunction::moveCallSiteInfo(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved(), llvm::orc::AsynchronousSymbolQuery::notifySymbolMetRequiredState(), llvm::MIPrinter::print(), llvm::MIPrinter::printStackObjectReference(), ProfitableToMerge(), llvm::memprof::RawMemProfReader::readNextRecord(), llvm::GCNUpwardRPTracker::recede(), reduceDbgValsForwardScan(), llvm::orc::ExecutionSession::registerJITDispatchHandlers(), llvm::GISelWorkList< N >::remove(), llvm::InstructionWorklist::remove(), llvm::LoopInfoBase< BlockT, LoopT >::removeBlock(), RemoveFromReverseMap(), llvm::MemoryDependenceResults::removeInstruction(), llvm::SlotIndexes::removeMachineInstrFromMaps(), removeRedundantDbgInstrsUsingForwardScan(), removeRedundantDbgLocsUsingForwardScan(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), removeUndefDbgLocsFromEntryBlock(), llvm::slpvectorizer::BoUpSLP::reorderBottomToTop(), llvm::slpvectorizer::BoUpSLP::reorderTopToBottom(), replaceArgumentUses(), llvm::DebugLoc::replaceInlinedAtSubprogram(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::replaceSymbolicStrideSCEV(), replaceUndefValuesInPhi(), llvm::reportMismatch(), llvm::lto::LTO::run(), llvm::LoadAndStorePromoter::run(), llvm::SelectionDAGISel::runOnMachineFunction(), scanPHIsAndUpdateValueMap(), selectIncomingValueForBlock(), llvm::FunctionLoweringInfo::set(), llvm::IRSimilarity::IRInstructionData::setBranchSuccessors(), llvm::IRSimilarity::IRInstructionData::setPHIPredecessors(), llvm::SIMachineFunctionInfo::setVGPRToAGPRSpillDead(), llvm::AbstractDependenceGraphBuilder< GraphType >::simplify(), simplifyTerminatorLeadingToRet(), simplifyUsingControlFlow(), sinkThroughTriviallyReplaceablePHI(), llvm::thinLTOFinalizeInModule(), llvm::thinLTOInternalizeModule(), llvm::at::trackAssignments(), tryToElideArgumentCopy(), llvm::AssumptionCache::unregisterAssumption(), llvm::UnrollLoop(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::ScalarEvolution::verify(), llvm::GenericConvergenceVerifier< ContextT >::verify(), and llvm::SCEVParameterRewriter::visitUnknown().
end() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end () const inline
Definition at line 94 of file DenseMap.h.
erase() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase (const KeyT & Val) inline
Definition at line 329 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey().
Referenced by llvm::GCNDownwardRPTracker::advanceBeforeNext(), analyzeAndPruneOutputBlocks(), llvm::HexagonSubtarget::CallMutation::apply(), llvm::ScalarEvolution::applyLoopGuards(), llvm::orc::SimpleRemoteEPC::callWrapperAsync(), llvm::LoopInfoBase< BlockT, LoopT >::changeLoopFor(), checkNumberingAndReplaceCommutative(), llvm::compareLoops(), llvm::ObjectSizeOffsetEvaluator::compute(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::deallocate(), llvm::orc::InProcessMemoryMapper::deinitialize(), llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::deinitialize(), llvm::orc::MaterializationUnit::doDiscard(), emitGlobalAliasInline(), llvm::json::Object::erase(), llvm::opt::ArgList::eraseArg(), llvm::MachineFunction::eraseCallSiteInfo(), llvm::DominatorTreeBase< NodeT, IsPostDom >::eraseNode(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::finalize(), llvm::BlockFrequencyInfoImpl< BT >::forgetBlock(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::MachineFunction::moveCallSiteInfo(), llvm::orc::AsynchronousSymbolQuery::notifySymbolMetRequiredState(), OptimizeFunctions(), llvm::GISelWorkList< N >::pop_back_val(), llvm::GraphDiff< NodePtr, InverseGraph >::popUpdateForIncrementalUpdates(), llvm::ValueEnumerator::purgeFunction(), llvm::GCNUpwardRPTracker::recede(), TransferTracker::redefVar(), reduceDbgValsForwardScan(), llvm::orc::InProcessMemoryMapper::release(), llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::release(), llvm::GISelWorkList< N >::remove(), llvm::InstructionWorklist::remove(), llvm::LoopInfoBase< BlockT, LoopT >::removeBlock(), llvm::MemorySSA::removeFromLists(), RemoveFromReverseMap(), llvm::ValueHandleBase::RemoveFromUseList(), llvm::MemoryDependenceResults::removeInstruction(), llvm::SCCPInstVisitor::removeLatticeValueFor(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::InstructionWorklist::removeOne(), llvm::GlobalValue::removeSanitizerMetadata(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), llvm::DomConditionCache::removeValue(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::scc_iterator< GraphT, GT >::ReplaceNode(), llvm::AssumptionCache::unregisterAssumption(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), and llvm::GenericConvergenceVerifier< ContextT >::verify().
erase() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase (iterator I) inline
Definition at line 340 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey(), and I.
find() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find (const_arg_type_t< KeyT > Val) inline
Definition at line 155 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
Referenced by llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::add(), llvm::GCNDownwardRPTracker::advanceBeforeNext(), alignOutputBlockWithAggFunc(), AreEquivalentPhiNodes(), assignSections(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::at(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::at(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::begin(), buildClonedLoopBlocks(), llvm::orc::SimpleRemoteEPC::callWrapperAsync(), llvm::mca::ResourceManager::checkAvailability(), checkHoistValue(), TransferTracker::checkInstForNewValues(), CheckLargerCands(), checkNumberingAndReplaceCommutative(), TransferTracker::clobberMloc(), llvm::JumpThreadingPass::cloneInstructions(), llvm::DILocalScope::cloneScopeForSubprogram(), collectCallSiteParameters(), llvm::DominatorTreeBase< NodeT, IsPostDom >::compare(), llvm::ObjectSizeOffsetEvaluator::compute(), computeBaseDerivedRelocateMap(), llvm::EHStreamer::computeCallSiteTable(), llvm::ComputeCrossModuleImport(), computeDomSubtreeCost(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), LiveDebugValues::VLocTracker::considerOverlaps(), llvm::ScalarEvolution::containsAddRecurrence(), llvm::SSPLayoutInfo::copyToMachineFrameInfo(), llvm::sampleprofutil::SampleCoverageTracker::countUsedRecords(), llvm::objcarc::createCallInstWithColors(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalRelationFrom(), llvm::VPRecipeBuilder::createEdgeMask(), createSwitchStatement(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::deallocate(), decodeBBAddrMapImpl(), DPValuesRemoveRedundantDbgInstrsUsingForwardScan(), llvm::JumpThreadingPass::duplicateCondBranchOnPHIIntoPred(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::InstrEmitter::EmitDbgInstrRef(), emitGlobalAliasInline(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), fillOverallFunction(), llvm::orc::rt_bootstrap::SimpleExecutorMemoryManager::finalize(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::find(), llvm::LazyCallGraph::RefSCC::find(), llvm::CFGMST< Edge, BBInfo >::findBBInfo(), findCandidateStructures(), findDuplicateOutputBlock(), findExtractedInputToOverallInputMapping(), findInsertLocation(), LiveDebugValues::InstrRefBasedLDV::findLocationForMemOperand(), findOrCreatePHIBlock(), findOutputMapping(), findOutputValueInRegion(), FoldCondBranchOnValueKnownInPredecessorImpl(), llvm::IRSimilarity::IRSimilarityCandidate::fromCanonicalNum(), llvm::IRSimilarity::IRSimilarityCandidate::fromGVN(), llvm::gatherImportedSummariesForModule(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::SlotTracker::getAttributeGroupSlot(), llvm::CFGMST< Edge, BBInfo >::getBBInfo(), llvm::VPRecipeBuilder::getBlockInMask(), llvm::SelectionDAG::getCallSiteInfo(), llvm::IRSimilarity::IRSimilarityCandidate::getCanonicalNum(), llvm::ARMFunctionInfo::getCoalescedWeight(), llvm::PseudoProbeManager::getDesc(), llvm::dwarf_linker::parallel::CompileUnit::getDirAndFilenameFromLineTable(), llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::getExistingEntry(), llvm::SparseSolver< LatticeKey, LatticeVal, KeyInfo >::getExistingValueState(), llvm::dwarf_linker::parallel::CompileUnit::getFileName(), llvm::GCModuleInfo::getFunctionInfo(), llvm::SlotTracker::getGlobalSlot(), llvm::mca::LSUnitBase::getGroup(), llvm::SlotTracker::getGUIDSlot(), llvm::IRSimilarity::IRSimilarityCandidate::getGVN(), getGVNForPHINode(), llvm::SelectionDAG::getHeapAllocSite(), llvm::SlotIndexes::getIndexAfter(), llvm::SlotIndexes::getIndexBefore(), llvm::SwingSchedulerDAG::getInstrBaseReg(), llvm::ValueEnumerator::getInstructionID(), llvm::SlotIndexes::getInstructionIndex(), llvm::SCCPInstVisitor::getLatticeValueFor(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::SlotTracker::getLocalSlot(), llvm::PPCRegisterInfo::getMappedIdxOpcForImmOpc(), getMappedReg(), llvm::DILocation::getMergedLocation(), llvm::SlotTracker::getMetadataSlot(), llvm::TargetLibraryInfo::getName(), llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode(), llvm::SelectionDAG::getNoMergeSiteInfo(), llvm::ARMFunctionInfo::getOriginalCPIdx(), llvm::SelectionDAG::getPCSections(), llvm::DataDependenceGraph::getPiBlock(), llvm::object::ELFObjectFileBase::getPltEntries(), getPoisonFor(), llvm::LoopBlocksDFS::getPostorder(), llvm::SCCPInstVisitor::getPredicateInfoFor(), getPredState(), llvm::SIMachineFunctionInfo::getPrologEpilogSGPRSaveRestoreInfo(), llvm::object::MinidumpFile::getRawStream(), llvm::SIMachineFunctionInfo::getScratchSGPRCopyDstReg(), llvm::SDDbgInfo::getSDDbgValues(), llvm::SIMachineFunctionInfo::getSGPRSpillToPhysicalVGPRLanes(), llvm::SIMachineFunctionInfo::getSGPRSpillToVirtualVGPRLanes(), llvm::VPSlotTracker::getSlot(), llvm::ModuloSchedule::getStage(), llvm::SCCPInstVisitor::getStructLatticeValueFor(), getSuccState(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::SPIRVGlobalRegistry::getTypeForSPIRVType(), llvm::ValueEnumerator::getTypeID(), llvm::dxil::ValueEnumerator::getTypeID(), getUnwindDestToken(), getUnwindDestTokenHelper(), llvm::dwarf_linker::IndexedValuesMap< T >::getValueIndex(), getValueOnFirstIteration(), llvm::slpvectorizer::BoUpSLP::getVectorElementSize(), llvm::SIMachineFunctionInfo::getVGPRToAGPRSpill(), llvm::NVPTXAsmPrinter::getVirtualRegisterName(), llvm::LoopVectorizationCostModel::getWideningDecision(), getWorklist(), llvm::LoopBlocksDFS::hasPostorder(), llvm::FunctionImporter::importFunctions(), INITIALIZE_PASS(), insertDPValuesForPHIs(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), isBigEndian(), llvm::coverage::MCDCRecord::isConditionIndependencePairCovered(), llvm::isEqual(), llvm::ARMBaseInstrInfo::isFpMLxInstruction(), IsValueFullyAvailableInBlock(), TransferTracker::loadInlocs(), loadObj(), TransferTracker::loadVarInloc(), LiveDebugValues::MLocTracker::locIDToSpillIdx(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::lookup(), llvm::codeview::DebugChecksumsSubsection::mapChecksumOffset(), mapInputsToGVNs(), llvm::CombinerHelper::matchLoadOrCombine(), matchScalarReduction(), mergeConstants(), migrateDebugInfo(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved(), llvm::orc::AsynchronousSymbolQuery::notifySymbolMetRequiredState(), populateEHOperandBundle(), llvm::MIPrinter::print(), llvm::MIPrinter::printStackObjectReference(), ProfitableToMerge(), llvm::memprof::RawMemProfReader::readNextRecord(), llvm::GCNUpwardRPTracker::recede(), reduceDbgValsForwardScan(), llvm::orc::ExecutionSession::registerJITDispatchHandlers(), remapExtractedInputs(), llvm::GISelWorkList< N >::remove(), llvm::InstructionWorklist::remove(), llvm::LoopInfoBase< BlockT, LoopT >::removeBlock(), llvm::MemorySSA::removeFromLists(), RemoveFromReverseMap(), llvm::MemoryDependenceResults::removeInstruction(), llvm::SlotIndexes::removeMachineInstrFromMaps(), removeRedundantDbgInstrsUsingForwardScan(), removeRedundantDbgLocsUsingForwardScan(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), removeUndefDbgLocsFromEntryBlock(), llvm::slpvectorizer::BoUpSLP::reorderBottomToTop(), llvm::slpvectorizer::BoUpSLP::reorderTopToBottom(), replaceArgumentUses(), llvm::DebugLoc::replaceInlinedAtSubprogram(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::replaceSymbolicStrideSCEV(), replaceUndefValuesInPhi(), llvm::reportMismatch(), llvm::lto::LTO::run(), llvm::LoadAndStorePromoter::run(), llvm::SelectionDAGISel::runOnMachineFunction(), scanPHIsAndUpdateValueMap(), selectIncomingValueForBlock(), llvm::FunctionLoweringInfo::set(), llvm::IRSimilarity::IRInstructionData::setBranchSuccessors(), llvm::IRSimilarity::IRInstructionData::setPHIPredecessors(), llvm::SIMachineFunctionInfo::setVGPRToAGPRSpillDead(), llvm::AbstractDependenceGraphBuilder< GraphType >::simplify(), simplifyTerminatorLeadingToRet(), simplifyUsingControlFlow(), sinkInstruction(), sinkThroughTriviallyReplaceablePHI(), llvm::thinLTOFinalizeInModule(), llvm::thinLTOInternalizeModule(), llvm::at::trackAssignments(), tryToElideArgumentCopy(), llvm::UnrollLoop(), unswitchNontrivialInvariants(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::ScalarEvolution::verify(), llvm::GenericConvergenceVerifier< ContextT >::verify(), and llvm::SCEVParameterRewriter::visitUnknown().
find() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find (const_arg_type_t< KeyT > Val) const inline
Definition at line 164 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
find_as() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<class LookupKeyT > iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as (const LookupKeyT & Val) inline
Alternate version of find() which allows a different, and possibly less expensive, key type.
The DenseMapInfo is responsible for supplying methods getHashValue(LookupKeyT) and isEqual(LookupKeyT, KeyT) for each key type used.
Definition at line 180 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
Referenced by llvm::DomConditionCache::conditionsFor(), llvm::AssumptionCacheTracker::getAssumptionCache(), llvm::ScalarEvolution::getExistingSCEV(), llvm::AssumptionCacheTracker::lookupAssumptionCache(), and llvm::AssumptionCache::unregisterAssumption().
find_as() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<class LookupKeyT > const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find_as (const LookupKeyT & Val) const inline
Definition at line 190 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end().
FindAndConstruct() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > value_type & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::FindAndConstruct (const KeyT & Key) inline
Definition at line 348 of file DenseMap.h.
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::insert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::operator[](), and llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::operator[]().
FindAndConstruct() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > value_type & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::FindAndConstruct (KeyT && Key) inline
Definition at line 360 of file DenseMap.h.
getEmptyKey()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > static const KeyT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getEmptyKey () inline static protected
Definition at line 480 of file DenseMap.h.
Referenced by llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::copyFrom(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::moveFromOldBuckets().
getHashValue() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > static unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getHashValue (const KeyT & Val) inline static protected
Definition at line 471 of file DenseMap.h.
getHashValue() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<typename LookupKeyT > static unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getHashValue (const LookupKeyT & Val) inline static protected
Definition at line 476 of file DenseMap.h.
getMemorySize()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > size_t llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getMemorySize () const inline
Return the approximate size (in bytes) of the actual map.
This is just the raw memory used by DenseMap. If entries are pointers to objects, the size of the referenced objects are not included.
Definition at line 699 of file DenseMap.h.
getMinBucketToReserveForEntries()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getMinBucketToReserveForEntries (unsigned NumEntries) inline protected
Returns the number of buckets to allocate to ensure that the DenseMap can accommodate NumEntries without need to grow().
Definition at line 413 of file DenseMap.h.
References llvm::NextPowerOf2().
Referenced by llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::reserve().
getOrInsertDefault() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > ValueT & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getOrInsertDefault (const KeyT & Key) inline
Returns the value associated to the key in the map if it exists.
If it does not exist, emplace a default value for the key and returns a reference to the newly created value.
Definition at line 325 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
getOrInsertDefault() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > ValueT & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getOrInsertDefault (KeyT && Key) inline
Returns the value associated to the key in the map if it exists.
If it does not exist, emplace a default value for the key and returns a reference to the newly created value.
Definition at line 318 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
getPointerIntoBucketsArray()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > const void * llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getPointerIntoBucketsArray () const inline
getPointerIntoBucketsArray() - Return an opaque pointer into the buckets array.
In conjunction with the previous method, this can be used to determine whether an insertion caused the DenseMap to reallocate.
Definition at line 382 of file DenseMap.h.
getTombstoneKey()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > static const KeyT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey () inline static protected
Definition at line 486 of file DenseMap.h.
Referenced by llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::copyFrom(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::moveFromOldBuckets().
initEmpty()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty () inline protected
Definition at line 400 of file DenseMap.h.
References assert(), B, E, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getEmptyKey().
Referenced by llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::moveFromOldBuckets().
insert() [1/3]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert (const std::pair< KeyT, ValueT > & KV) inline
Definition at line 220 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
Referenced by llvm::dwarf_linker::parallel::StringEntryToDwarfStringPoolEntryMap::add(), llvm::AA::PointerInfo::State::addAccess(), AddAliasScopeMetadata(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::addBasicBlock(), llvm::addDiffRuntimeChecks(), llvm::CFGMST< Edge, BBInfo >::addEdge(), llvm::dwarf_linker::classic::CompileUnit::addLabelLowPc(), llvm::DataDependenceGraph::addNode(), llvm::SCCPInstVisitor::addPredicateInfo(), llvm::SIMachineFunctionInfo::addToPrologEpilogSGPRSpills(), analyzeLoopUnrollCost(), llvm::opt::ArgList::append(), llvm::ScalarEvolution::applyLoopGuards(), llvm::ARMBaseInstrInfo::ARMBaseInstrInfo(), buildClonedLoops(), buildFrameDebugInfo(), cacheDIVar(), llvm::mca::ResourceManager::checkAvailability(), TransferTracker::checkInstForNewValues(), CheckLargerCands(), checkNumberingAndReplace(), TransferTracker::clobberMloc(), llvm::cloneNoAliasScopes(), collectEHScopeMembers(), collectEscapedLocals(), llvm::LoopVectorizationCostModel::collectInstsToScalarize(), computeBaseDerivedRelocateMap(), ComputeCrossModuleImportForModuleFromIndexForTest(), computeDomSubtreeCost(), computeImportForFunction(), constantMatches(), llvm::ConstraintSystem::ConstraintSystem(), llvm::ScalarEvolution::containsAddRecurrence(), llvm::MIRPrinter::convertStackObjects(), createAndInsertBasicBlocks(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalMappingFor(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalRelationFrom(), llvm::mca::LSUnitBase::createMemoryGroup(), doPromotion(), llvm::orc::RTDyldObjectLinkingLayer::emit(), llvm::AsmPrinter::emitFunctionBody(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), findArgumentCopyElisionCandidates(), findBestInsertionSet(), findCandidateStructures(), findExtractedInputToOverallInputMapping(), findOrCreatePHIBlock(), llvm::xray::BlockIndexer::flush(), llvm::InstCombinerImpl::foldAggregateConstructionIntoAggregateReuse(), forEachWorkListItem(), gatherIncomingValuesToPhi(), llvm::AArch64InstrInfo::genAlternativeCodeSequence(), genAlternativeDpCodeSequence(), genNeg(), genSubAdd2SubSub(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::AssumptionCacheTracker::getAssumptionCache(), llvm::ARMFunctionInfo::getCoalescedWeight(), llvm::MemoryDependenceResults::getDependency(), llvm::dwarf_linker::parallel::CompileUnit::getDirAndFilenameFromLineTable(), llvm::dwarf_linker::parallel::CompileUnit::getFileName(), getGVNForPHINode(), llvm::MemoryDependenceResults::getInvariantGroupPointerDependency(), getLocalId(), llvm::MemoryDependenceResults::getNonLocalCallDependency(), llvm::DWPStringPool::getOffset(), llvm::object::ELFObjectFileBase::getPltEntries(), llvm::X86MachineFunctionInfo::getPreallocatedIdForCallSite(), llvm::dwarf_linker::IndexedValuesMap< T >::getValueIndex(), llvm::HexagonEvaluator::HexagonEvaluator(), initBranchWeights(), llvm::MIRParserImpl::initializeConstantPool(), llvm::MIRParserImpl::initializeFrameInfo(), llvm::MIRParserImpl::initializeJumpTableInfo(), llvm::lto::initImportList(), initSlots2BasicBlocks(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::insert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::DwarfFile::insertDIE(), insertDPValuesForPHIs(), insertFoldCacheEntry(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::isNonEscapingLocalObject(), TransferTracker::loadInlocs(), loadObj(), TransferTracker::loadVarInloc(), lowerBuildVectorViaDominantValues(), mapValueToSlot(), matchScalarReduction(), memoryIsNotModifiedBetween(), llvm::xray::mergeProfilesByThread(), LiveDebugValues::MLocTracker::MLocTracker(), moveFunctionData(), llvm::orc::BlockFreqQuery::operator()(), llvm::orc::SequenceBBQuery::operator()(), llvm::xray::Graph< VertexAttribute, EdgeAttribute, VI >::operator[](), promoteArguments(), llvm::InstructionWorklist::push(), pushDepHeight(), llvm::TargetInstrInfo::reassociateOps(), llvm::ARMFunctionInfo::recordCPEClone(), TransferTracker::redefVar(), llvm::PassRegistry::registerPass(), llvm::objcarc::ProvenanceAnalysis::related(), llvm::MemoryDependenceResults::removeInstruction(), llvm::SlotIndexes::removeSingleMachineInstrFromMaps(), removeUndefDbgLocsFromEntryBlock(), llvm::slpvectorizer::BoUpSLP::reorderTopToBottom(), replaceArgumentUses(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::SSPLayoutAnalysis::requiresStackProtector(), llvm::DevirtSCCRepeatedPass::run(), runImpl(), llvm::SlotIndexes::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), selectIncomingValueForBlock(), llvm::FunctionLoweringInfo::set(), llvm::LoopVectorizationCostModel::setCostBasedWideningDecision(), shouldConvert(), llvm::AbstractDependenceGraphBuilder< GraphType >::simplify(), solveDIType(), sortLocalVars(), SRAGlobal(), llvm::orc::ImplSymbolMap::trackImpls(), TransferTracker::transferMlocs(), llvm::VPlanTransforms::truncateToMinimalBitwidths(), tryToElideArgumentCopy(), and llvm::VirtRegAuxInfo::weightCalcHelper().
insert() [2/3]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<typename InputIt > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert (InputIt I, InputIt E) inline
insert - Range insertion of pairs.
Definition at line 310 of file DenseMap.h.
References E, I, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert().
insert() [3/3]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert (std::pair< KeyT, ValueT > && KV) inline
Definition at line 227 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace().
insert_as()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<typename LookupKeyT > std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert_as (std::pair< KeyT, ValueT > && KV, const LookupKeyT & Val) inline
Alternate version of insert() which allows a different, and possibly less expensive, key type.
The DenseMapInfo is responsible for supplying methods getHashValue(LookupKeyT) and isEqual(LookupKeyT, KeyT) for each key type used.
Definition at line 286 of file DenseMap.h.
isPointerIntoBucketsArray()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::isPointerIntoBucketsArray (const void * Ptr) const inline
isPointerIntoBucketsArray - Return true if the specified pointer points somewhere into the DenseMap's array of buckets (i.e.
either to a key or value in the DenseMap).
Definition at line 375 of file DenseMap.h.
References Ptr.
Referenced by llvm::ValueHandleBase::RemoveFromUseList().
lookup()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > ValueT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup (const_arg_type_t< KeyT > Val) const inline
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
Definition at line 202 of file DenseMap.h.
Referenced by llvm::adaptNoAliasScopes(), llvm::addClonedBlockToLoopInfo(), llvm::addDiffRuntimeChecks(), analyzeLoopUnrollCost(), llvm::CombinerHelper::applyCombineExtendingLoads(), AttemptToFoldSymbolOffsetDifference(), llvm::MCPseudoProbeDecoder::buildAddress2ProbeMap(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), buildClonedLoops(), checkDependencies(), checkForAllInstructionsImpl(), llvm::compareLoops(), llvm::ComputeCrossModuleImport(), llvm::MachObjectWriter::computeSymbolTable(), cse(), doPromotion(), dropDeadSymbols(), EvaluateExpression(), findConstantFor(), llvm::sampleprof::FunctionSamples::findInlinedFunctions(), findIrreducibleHeaders(), llvm::MachO::SymbolSet::findSymbol(), llvm::SSAUpdater::FindValueForBlock(), llvm::gatherImportedSummariesForModule(), llvm::ARMAsmBackendDarwin::generateCompactUnwindEncoding(), llvm::Attributor::getAttrsFromAssumes(), llvm::MachineFunction::getCallSiteBeginLabel(), getConstantEvolvingPHIOperands(), llvm::DebugCounter::getCounterInfo(), llvm::DwarfFile::getDIE(), llvm::ModifiedPostOrder< ContextT >::getIndex(), llvm::VPInterleavedAccessInfo::getInterleaveGroup(), getIRBlockFromSlot(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::InterleaveGroup< InstTy >::getMember(), getNewDefiningAccessForClone(), getNewSource(), llvm::PassRegistry::getPassInfo(), llvm::VPlan::getSCEVExpansion(), llvm::MachObjectWriter::getSectionAddress(), llvm::VirtRegMap::getShape(), llvm::DwarfDebug::getStringTypeLoc(), llvm::MCStreamer::getSymbolOrder(), llvm::Triple::getVulkanVersion(), llvm::MachineFunction::getWasmLandingPadIndex(), INITIALIZE_PASS(), llvm::Attributor::internalizeFunctions(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::FunctionVarLocs::locs_begin(), llvm::FunctionVarLocs::locs_end(), llvm::DwarfDebug::lookupCU(), llvm::MetadataLoader::MetadataLoaderImpl::lookupSubprogramForFunction(), llvm::GVNHoist::rank(), llvm::objcopy::elf::SymbolTableSection::replaceSectionReferences(), llvm::objcopy::elf::RelocationSection::replaceSectionReferences(), llvm::objcopy::elf::GroupSection::replaceSectionReferences(), llvm::OpenMPOptPass::run(), llvm::GCNRegPressurePrinter::runOnMachineFunction(), solveDIType(), sortLocalVars(), speculatePHINodeLoads(), llvm::stripDebugInfo(), llvm::MemorySSAUpdater::updateForClonedLoop(), and llvm::LoopInfoBase< BlockT, LoopT >::verify().
moveFromOldBuckets()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::moveFromOldBuckets (BucketT * OldBucketsBegin, BucketT * OldBucketsEnd) inline protected
Definition at line 422 of file DenseMap.h.
References assert(), B, E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getEmptyKey(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getTombstoneKey(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty().
operator[]() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > ValueT & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::operator[] (const KeyT & Key) inline
Definition at line 356 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::FindAndConstruct().
operator[]() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > ValueT & llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::operator[] (KeyT && Key) inline
Definition at line 368 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::FindAndConstruct().
reserve()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::reserve (size_type NumEntries) inline
Grow the densemap so that it can contain at least NumEntries items before resizing again.
Definition at line 103 of file DenseMap.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getMinBucketToReserveForEntries(), and llvm::DebugEpochBase::incrementEpoch().
Referenced by llvm::SampleProfileInference< FT >::apply(), buildIndexMap(), llvm::GISelWorkList< N >::finalize(), findArgumentCopyElisionCandidates(), findBestInsertionSet(), llvm::cfg::LegalizeUpdates(), TransferTracker::loadInlocs(), llvm::LoopBlocksDFS::LoopBlocksDFS(), llvm::InstructionWorklist::reserve(), and llvm::ThinLTOCodeGenerator::run().
size()
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size () const inline
Definition at line 99 of file DenseMap.h.
Referenced by llvm::CFGMST< Edge, BBInfo >::addEdge(), llvm::SampleProfileInference< FT >::apply(), llvm::SlotTracker::as_size(), llvm::MCStreamer::assignFragment(), llvm::CFGMST< Edge, BBInfo >::bbInfoSize(), llvm::SwitchCG::SwitchLowering::buildJumpTable(), checkNumberingAndReplaceCommutative(), llvm::DominatorTreeBase< NodeT, IsPostDom >::compare(), llvm::IRSimilarity::IRSimilarityCandidate::compareAssignmentMapping(), llvm::ComputeCrossModuleImport(), llvm::computeLTOCacheKey(), llvm::ConstraintSystem::ConstraintSystem(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalMappingFor(), llvm::IRSimilarity::IRSimilarityCandidate::createCanonicalRelationFrom(), llvm::CFGMST< Edge, BBInfo >::dumpEdges(), dumpImportListForModule(), llvm::dwarf_linker::classic::DwarfStreamer::emitDebugNames(), llvm::dwarf_linker::parallel::DwarfEmitterImpl::emitDebugNames(), llvm::VETargetLowering::emitSjLjDispatchBlock(), llvm::ModuleSummaryIndex::exportToDot(), findArgParts(), findArgumentCopyElisionCandidates(), findIrreducibleHeaders(), llvm::CSKYAsmBackend::getFixupKindInfo(), llvm::InterleaveGroup< InstTy >::getNumMembers(), llvm::ReplaceableMetadataImpl::getNumUses(), llvm::X86MachineFunctionInfo::getPreallocatedIdForCallSite(), insertDPValuesForPHIs(), isBigEndian(), llvm::isEqual(), IsEquivalentPHI(), llvm::cfg::LegalizeUpdates(), llvm::orc::Platform::lookupInitSymbols(), llvm::SelectionDAGBuilder::LowerAsSTATEPOINT(), lowerBuildVectorViaDominantValues(), llvm::ARMTargetLowering::lowerInterleavedLoad(), lowerStatepointMetaArgs(), lowerVECTOR_SHUFFLE(), llvm::SlotTracker::mdn_size(), LiveDebugValues::MLocTracker::MLocTracker(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved(), llvm::AA::PointerInfo::State::numOffsetBins(), llvm::AliasSetTracker::print(), llvm::memprof::RawMemProfReader::printYAML(), llvm::orc::rt_bootstrap::ExecutorSharedMemoryMapperService::shutdown(), llvm::AbstractDependenceGraphBuilder< GraphType >::simplify(), llvm::GISelWorkList< N >::size(), SRAGlobal(), SwitchToLookupTable(), llvm::UnrollLoop(), llvm::BlockFrequencyInfoImpl< BT >::verifyMatch(), and llvm::orc::InProcessMemoryMapper::~InProcessMemoryMapper().
try_emplace() [1/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<typename... Ts> std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace (const KeyT & Key, Ts &&... Args) inline
Definition at line 260 of file DenseMap.h.
try_emplace() [2/2]
template<typename DerivedT , typename KeyT , typename ValueT , typename KeyInfoT , typename BucketT > template<typename... Ts> std::pair< iterator, bool > llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::try_emplace (KeyT && Key, Ts &&... Args) inline
Definition at line 235 of file DenseMap.h.
Referenced by llvm::MachineFunction::addCallArgsForwardingRegs(), addEdge(), llvm::CloneFunctionInto(), collectSRATypes(), llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes(), llvm::object::MinidumpFile::create(), llvm::ModuleSummaryIndex::exportToDot(), llvm::GISelWorkList< N >::finalize(), findArgParts(), llvm::DILocation::getMergedLocation(), llvm::pdb::SymbolCache::getOrCreateFieldListMember(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::getOrInsertDefault(), hasChangeableCC(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::GISelWorkList< N >::insert(), llvm::codeview::GlobalTypeTableBuilder::insertRecordAs(), llvm::IRSimilarity::IRSimilarityCandidate::IRSimilarityCandidate(), IsValueFullyAvailableInBlock(), llvm::PseudoProbeManager::PseudoProbeManager(), removeRedundantDbgLocsUsingBackwardScan(), llvm::slpvectorizer::BoUpSLP::reorderBottomToTop(), llvm::slpvectorizer::BoUpSLP::reorderTopToBottom(), llvm::UnrollLoop(), updateIDTMetaData(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), and llvm::GenericConvergenceVerifier< ContextT >::verify().
The documentation for this class was generated from the following file:
include/llvm/ADT/DenseMap.h