LLVM: llvm::RuntimePointerChecking Class Reference
llvm::RuntimePointerChecking Class Reference
Holds information about the memory runtime legality checks to verify that a group of pointers do not overlap.
#include "llvm/Analysis/LoopAccessAnalysis.h"
Classes
struct PointerInfo
Public Member Functions
RuntimePointerChecking (MemoryDepChecker &DC, ScalarEvolution *SE)
void reset ()
Reset the state of the pointer runtime information.
void insert (Loop *Lp, Value *Ptr, const SCEV *PtrExpr, Type *AccessTy, bool WritePtr, unsigned DepSetId, unsigned ASId, PredicatedScalarEvolution &PSE, bool NeedsFreeze)
Insert a pointer and calculate the start and end SCEVs.
bool empty () const
No run-time memory checking is necessary.
void generateChecks (MemoryDepChecker::DepCandidates &DepCands, bool UseDependencies)
Generate the checks and store it.
const SmallVectorImpl< RuntimePointerCheck > & getChecks () const
Returns the checks that generateChecks created.
std::optional< ArrayRef< PointerDiffInfo > > getDiffChecks () const
bool needsChecking (const RuntimeCheckingPtrGroup &M, const RuntimeCheckingPtrGroup &N) const
Decide if we need to add a check between two groups of pointers, according to needsChecking.
unsigned getNumberOfChecks () const
Returns the number of run-time checks required according to needsChecking.
void print (raw_ostream &OS, unsigned Depth=0) const
Print the list run-time memory checks necessary.
void printChecks (raw_ostream &OS, const SmallVectorImpl< RuntimePointerCheck > &Checks, unsigned Depth=0) const
Print Checks.
bool needsChecking (unsigned I, unsigned J) const
Decide whether we need to issue a run-time check for pointer at index I and J to prove their independence.
const PointerInfo & getPointerInfo (unsigned PtrIdx) const
Return PointerInfo for pointer at index PtrIdx.
ScalarEvolution * getSE () const
Static Public Member Functions
static bool arePointersInSamePartition (const SmallVectorImpl< int > &PtrToPartition, unsigned PtrIdx1, unsigned PtrIdx2)
Check if pointers are in the same partition.
Public Attributes
bool Need = false
This flag indicates if we need to add the runtime check.
SmallVector< PointerInfo, 2 > Pointers
Information about the pointers that may require checking.
SmallVector< RuntimeCheckingPtrGroup, 2 > CheckingGroups
Holds a partitioning of pointers into "check groups".
Friends
struct RuntimeCheckingPtrGroup
Detailed Description
Holds information about the memory runtime legality checks to verify that a group of pointers do not overlap.
Definition at line 399 of file LoopAccessAnalysis.h.
Constructor & Destructor Documentation
RuntimePointerChecking()
llvm::RuntimePointerChecking::RuntimePointerChecking (MemoryDepChecker & DC, ScalarEvolution * SE) inline
Definition at line 432 of file LoopAccessAnalysis.h.
Member Function Documentation
arePointersInSamePartition()
bool RuntimePointerChecking::arePointersInSamePartition (const SmallVectorImpl< int > & PtrToPartition, unsigned PtrIdx1, unsigned PtrIdx2) static
Check if pointers are in the same partition.
PtrToPartition contains the partition number for pointers (-1 if the pointer belongs to multiple partitions).
Definition at line 582 of file LoopAccessAnalysis.cpp.
empty()
bool llvm::RuntimePointerChecking::empty () const inline
No run-time memory checking is necessary.
Definition at line 452 of file LoopAccessAnalysis.h.
References Pointers.
generateChecks()
void RuntimePointerChecking::generateChecks (MemoryDepChecker::DepCandidates & DepCands, bool UseDependencies)
Generate the checks and store it.
This also performs the grouping of pointers to reduce the number of memchecks necessary.
Definition at line 387 of file LoopAccessAnalysis.cpp.
References assert(), llvm::SmallVectorBase< Size_T >::empty(), and generateChecks().
Referenced by generateChecks().
getChecks()
const SmallVectorImpl< RuntimePointerCheck > & llvm::RuntimePointerChecking::getChecks () const inline
Returns the checks that generateChecks created.
They can be used to ensure no read/write accesses overlap across all loop iterations.
Definition at line 461 of file LoopAccessAnalysis.h.
Referenced by llvm::LoopVectorizationPlanner::executePlan().
getDiffChecks()
std::optional< ArrayRef< PointerDiffInfo > > llvm::RuntimePointerChecking::getDiffChecks () const inline
Definition at line 470 of file LoopAccessAnalysis.h.
Referenced by llvm::LoopVectorizationPlanner::executePlan().
getNumberOfChecks()
unsigned llvm::RuntimePointerChecking::getNumberOfChecks () const inline
Returns the number of run-time checks required according to needsChecking.
Definition at line 483 of file LoopAccessAnalysis.h.
References llvm::SmallVectorBase< Size_T >::size().
getPointerInfo()
const PointerInfo & llvm::RuntimePointerChecking::getPointerInfo (unsigned PtrIdx) const inline
Return PointerInfo for pointer at index PtrIdx.
Definition at line 515 of file LoopAccessAnalysis.h.
References Pointers.
Referenced by llvm::LoopVersioning::prepareNoAliasMetadata().
getSE()
ScalarEvolution * llvm::RuntimePointerChecking::getSE () const inline
Definition at line 519 of file LoopAccessAnalysis.h.
insert()
void RuntimePointerChecking::insert (Loop * Lp, Value * Ptr, const SCEV * PtrExpr, Type * AccessTy, bool WritePtr, unsigned DepSetId, unsigned ASId, PredicatedScalarEvolution & PSE, bool NeedsFreeze)
Insert a pointer and calculate the start and end SCEVs.
Calculate Start and End points of memory access.
We need PSE in order to compute the SCEV expression of the pointer according to the assumptions that we've made during the analysis. The method might also version the pointer stride according to Strides, and add new predicates to PSE.
Let's assume A is the first access and B is a memory access on N-th loop iteration. Then B is calculated as: B = A + Step*N . Step value may be positive or negative. N is a calculated back-edge taken count: N = (TripCount > 0) ? RoundDown(TripCount -1 , VF) : 0 Start and End points are calculated in the following way: Start = UMIN(A, B) ; End = UMAX(A, B) + SizeOfElt, where SizeOfElt is the size of single memory access in bytes.
There is no conflict when the intervals are disjoint: NoConflict = (P2.Start >= P1.End) || (P1.Start >= P2.End)
Definition at line 205 of file LoopAccessAnalysis.cpp.
References assert(), DL, llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::ScalarEvolution::getAddExpr(), llvm::PredicatedScalarEvolution::getBackedgeTakenCount(), llvm::Module::getDataLayout(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BasicBlock::getModule(), llvm::PredicatedScalarEvolution::getSE(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::ScalarEvolution::getStoreSizeOfExpr(), llvm::ScalarEvolution::getUMaxExpr(), llvm::ScalarEvolution::getUMinExpr(), llvm::ScalarEvolution::isLoopInvariant(), Pointers, Ptr, and std::swap().
needsChecking() [1/2]
bool RuntimePointerChecking::needsChecking (const RuntimeCheckingPtrGroup & M, const RuntimeCheckingPtrGroup & N) const
Decide if we need to add a check between two groups of pointers, according to needsChecking.
Definition at line 394 of file LoopAccessAnalysis.cpp.
References I, N, and needsChecking().
Referenced by needsChecking().
needsChecking() [2/2]
bool RuntimePointerChecking::needsChecking (unsigned I, unsigned J) const
Decide whether we need to issue a run-time check for pointer at index I and J to prove their independence.
Definition at line 589 of file LoopAccessAnalysis.cpp.
References llvm::RuntimePointerChecking::PointerInfo::AliasSetId, llvm::RuntimePointerChecking::PointerInfo::DependencySetId, I, llvm::RuntimePointerChecking::PointerInfo::IsWritePtr, and Pointers.
print()
void RuntimePointerChecking::print (raw_ostream & OS, unsigned Depth = 0) const
Print the list run-time memory checks necessary.
Definition at line 627 of file LoopAccessAnalysis.cpp.
References CheckingGroups, llvm::Depth, I, llvm::raw_ostream::indent(), OS, Pointers, and printChecks().
printChecks()
void RuntimePointerChecking::printChecks (raw_ostream & OS, const SmallVectorImpl< RuntimePointerCheck > & Checks, unsigned Depth = 0) const
Print Checks.
Definition at line 608 of file LoopAccessAnalysis.cpp.
References Check, llvm::Depth, llvm::First, llvm::raw_ostream::indent(), N, OS, and Pointers.
Referenced by print().
reset()
void llvm::RuntimePointerChecking::reset () inline
Reset the state of the pointer runtime information.
Definition at line 436 of file LoopAccessAnalysis.h.
References llvm::SmallVectorImpl< T >::clear(), Need, and Pointers.
Friends And Related Function Documentation
RuntimeCheckingPtrGroup
friend struct RuntimeCheckingPtrGroup friend
Definition at line 400 of file LoopAccessAnalysis.h.
Member Data Documentation
CheckingGroups
SmallVector<RuntimeCheckingPtrGroup, 2> llvm::RuntimePointerChecking::CheckingGroups
Holds a partitioning of pointers into "check groups".
Definition at line 500 of file LoopAccessAnalysis.h.
Referenced by llvm::LoopVersioning::prepareNoAliasMetadata(), and print().
Need
bool llvm::RuntimePointerChecking::Need = false
This flag indicates if we need to add the runtime check.
Definition at line 494 of file LoopAccessAnalysis.h.
Referenced by llvm::LoopVectorizationLegality::canVectorize(), llvm::LoopVectorizationCostModel::computeMaxVF(), reset(), llvm::LoopVectorizationCostModel::runtimeChecksRequired(), and llvm::LoopVectorizationCostModel::selectInterleaveCount().
Pointers
SmallVector<PointerInfo, 2> llvm::RuntimePointerChecking::Pointers
Information about the pointers that may require checking.
Definition at line 497 of file LoopAccessAnalysis.h.
Referenced by llvm::RuntimeCheckingPtrGroup::addPointer(), empty(), getPointerInfo(), insert(), needsChecking(), print(), printChecks(), and reset().
The documentation for this class was generated from the following files:
include/llvm/Analysis/LoopAccessAnalysis.h
lib/Analysis/LoopAccessAnalysis.cpp