LLVM: llvm::DILocalVariable Class Reference
llvm::DILocalVariable Class Reference
Local variable.
#include "llvm/IR/DebugInfoMetadata.h"
Public Member Functions
DEFINE_MDNODE_GET (DILocalVariable,(DILocalScope *Scope, StringRef Name, DIFile *File, unsigned Line, DIType *Type, unsigned Arg, DIFlags Flags, uint32_t AlignInBits, DINodeArray Annotations),(Scope, Name, File, Line, Type, Arg, Flags, AlignInBits, Annotations)) DEFINE_MDNODE_GET(DILocalVariable
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata Annotations TempDILocalVariable clone () const
DILocalScope * getScope () const
Get the local scope for this variable.
bool isParameter () const
unsigned getArg () const
DIFlags getFlags () const
DINodeArray getAnnotations () const
Metadata * getRawAnnotations () const
bool isArtificial () const
bool isObjectPointer () const
bool isValidLocationForIntrinsic (const DILocation *DL) const
Check that a location is valid for this variable.
Public Member Functions inherited from llvm::DIVariable
unsigned getLine () const
DIScope * getScope () const
StringRef getName () const
DIFile * getFile () const
DIType * getType () const
uint32_t getAlignInBits () const
uint32_t getAlignInBytes () const
std::optional< uint64_t > getSizeInBits () const
Determines the size of the variable's type.
std::optional< DIBasicType::Signedness > getSignedness () const
Return the signedness of this variable's type, or std::nullopt if this type is neither signed nor unsigned.
StringRef getFilename () const
StringRef getDirectory () const
std::optional< StringRef > getSource () const
Metadata * getRawScope () const
MDString * getRawName () const
Metadata * getRawFile () const
Metadata * getRawType () const
Public Member Functions inherited from llvm::DINode
dwarf::Tag getTag () const
Public Member Functions inherited from llvm::MDNode
MDNode (const MDNode &)=delete
void operator= (const MDNode &)=delete
void * operator new (size_t)=delete
TempMDNode clone () const
Create a (temporary) clone of this.
LLVMContext & getContext () const
void replaceOperandWith (unsigned I, Metadata *New)
Replace a specific operand.
bool isResolved () const
Check if node is fully resolved.
bool isUniqued () const
bool isDistinct () const
bool isTemporary () const
bool isReplaceable () const
bool isAlwaysReplaceable () const
unsigned getNumTemporaryUses () const
void replaceAllUsesWith (Metadata *MD)
RAUW a temporary.
void resolveCycles ()
Resolve cycles.
void resolve ()
Resolve a unique, unresolved node.
op_iterator op_begin () const
op_iterator op_end () const
ArrayRef< MDOperand > operands () const
const MDOperand & getOperand (unsigned I) const
unsigned getNumOperands () const
Return number of MDNode operands.
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
void printTree (raw_ostream &OS, const Module *M=nullptr) const
Print in tree shape.
void printTree (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
void dumpTree () const
User-friendly dump in tree shape.
void dumpTree (const Module *M) const
Public Member Functions inherited from llvm::Metadata
unsigned getMetadataID () const
void dump () const
User-friendly dump.
void dump (const Module *M) const
void print (raw_ostream &OS, const Module *M=nullptr, bool IsForDebug=false) const
Print.
void print (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr, bool IsForDebug=false) const
void printAsOperand (raw_ostream &OS, const Module *M=nullptr) const
Print as operand.
void printAsOperand (raw_ostream &OS, ModuleSlotTracker &MST, const Module *M=nullptr) const
Static Public Member Functions
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DIVariable
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::DINode
static DIFlags getFlag (StringRef Flag)
static StringRef getFlagString (DIFlags Flag)
static DIFlags splitFlags (DIFlags Flags, SmallVectorImpl< DIFlags > &SplitFlags)
Split up a flags bitfield.
static bool classof (const Metadata *MD)
Static Public Member Functions inherited from llvm::MDNode
static MDTuple * get (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getIfExists (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static MDTuple * getDistinct (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static TempMDTuple getTemporary (LLVMContext &Context, ArrayRef< Metadata * > MDs)
static void deleteTemporary (MDNode *N)
Deallocate a node created by getTemporary.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithPermanent (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a permanent one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithUniqued (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a uniqued one.
template<class T >
static std::enable_if_t< std::is_base_of< MDNode, T >::value, T * > replaceWithDistinct (std::unique_ptr< T, TempMDNodeDeleter > N)
Replace a temporary node with a distinct one.
static bool classof (const Metadata *MD)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * concatenate (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * intersect (MDNode *A, MDNode *B)
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
static MDNode * getMostGenericAliasScope (MDNode *A, MDNode *B)
static MDNode * getMostGenericAlignmentOrDereferenceable (MDNode *A, MDNode *B)
static MDNode * getMergedProfMetadata (MDNode *A, MDNode *B, const Instruction *AInstr, const Instruction *BInstr)
Merge !prof metadata from two instructions.
Public Attributes
Metadata * Scope
Metadata MDString * Name
Metadata MDString Metadata * File
Metadata MDString Metadata unsigned Line
Metadata MDString Metadata unsigned Metadata * Type
Metadata MDString Metadata unsigned Metadata unsigned Arg
Metadata MDString Metadata unsigned Metadata unsigned DIFlags Flags
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t AlignInBits
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata * Annotations
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata Scope
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata Name
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata File
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata Line
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata Type
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata Arg
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata Flags
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata AlignInBits
Friends
class LLVMContextImpl
class MDNode
Additional Inherited Members
Public Types inherited from llvm::DINode
enum DIFlags : uint32_t { FlagAccessibility = FlagPrivate | FlagProtected | FlagPublic , FlagPtrToMemberRep }
Debug info flags.
Public Types inherited from llvm::MDNode
using op_iterator = const MDOperand *
using op_range = iterator_range< op_iterator >
Public Types inherited from llvm::Metadata
enum MetadataKind
Protected Types inherited from llvm::MDNode
using mutable_op_range = iterator_range< MDOperand * >
Protected Types inherited from llvm::Metadata
enum StorageType { Uniqued , Distinct , Temporary }
Active type of storage.
Protected Member Functions inherited from llvm::DIVariable
DIVariable (LLVMContext &C, unsigned ID, StorageType Storage, signed Line, ArrayRef< Metadata * > Ops, uint32_t AlignInBits=0)
~DIVariable ()=default
Protected Member Functions inherited from llvm::DINode
DINode (LLVMContext &C, unsigned ID, StorageType Storage, unsigned Tag, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~DINode ()=default
template<class Ty >
Ty * getOperandAs (unsigned I) const
StringRef getStringOperand (unsigned I) const
void setTag (unsigned Tag)
Allow subclasses to mutate the tag.
Protected Member Functions inherited from llvm::MDNode
MDNode (LLVMContext &Context, unsigned ID, StorageType Storage, ArrayRef< Metadata * > Ops1, ArrayRef< Metadata * > Ops2=std::nullopt)
~MDNode ()=default
void * operator new (size_t Size, size_t NumOps, StorageType Storage)
void operator delete (void *Mem)
void operator delete (void *, unsigned)
Required by std, but never called.
void operator delete (void *, unsigned, bool)
Required by std, but never called.
void dropAllReferences ()
MDOperand * mutable_begin ()
MDOperand * mutable_end ()
mutable_op_range mutable_operands ()
void setOperand (unsigned I, Metadata *New)
Set an operand.
unsigned getNumUnresolved () const
void setNumUnresolved (unsigned N)
void storeDistinctInContext ()
void resize (size_t NumOps)
Resize the node to hold NumOps operands.
Protected Member Functions inherited from llvm::Metadata
Metadata (unsigned ID, StorageType Storage)
~Metadata ()=default
void handleChangedOperand (void *, Metadata *)
Default handling of a changed operand, which asserts.
Static Protected Member Functions inherited from llvm::DINode
static MDString * getCanonicalMDString (LLVMContext &Context, StringRef S)
Static Protected Member Functions inherited from llvm::MDNode
template<class T , class StoreT >
static T * storeImpl (T *N, StorageType Storage, StoreT &Store)
template<class T >
static T * storeImpl (T *N, StorageType Storage)
Protected Attributes inherited from llvm::Metadata
unsigned char Storage: 7
Storage flag for non-uniqued, otherwise unowned, metadata.
unsigned char SubclassData1: 1
unsigned short SubclassData16 = 0
unsigned SubclassData32 = 0
Detailed Description
Local variable.
TODO: Split up flags.
Definition at line 3244 of file DebugInfoMetadata.h.
Member Function Documentation
classof()
static bool llvm::DILocalVariable::classof (const Metadata * MD) inline static
Definition at line 3327 of file DebugInfoMetadata.h.
References llvm::Metadata::getMetadataID().
clone()
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata Annotations TempDILocalVariable llvm::DILocalVariable::clone () const inline
Definition at line 3297 of file DebugInfoMetadata.h.
DEFINE_MDNODE_GET()
llvm::DILocalVariable::DEFINE_MDNODE_GET (DILocalVariable , (DILocalScope *Scope, StringRef Name, DIFile *File, unsigned Line, DIType *Type, unsigned Arg, DIFlags Flags, uint32_t AlignInBits, DINodeArray Annotations) , (Scope, Name, File, Line, Type, Arg, Flags, AlignInBits, Annotations))
getAnnotations()
DINodeArray llvm::DILocalVariable::getAnnotations () const inline
Definition at line 3310 of file DebugInfoMetadata.h.
References getRawAnnotations().
getArg()
unsigned llvm::DILocalVariable::getArg () const inline
Definition at line 3307 of file DebugInfoMetadata.h.
Referenced by llvm::DwarfFile::addScopeVariable().
getFlags()
DIFlags llvm::DILocalVariable::getFlags () const inline
Definition at line 3308 of file DebugInfoMetadata.h.
Referenced by isArtificial(), and isObjectPointer().
getRawAnnotations()
Metadata * llvm::DILocalVariable::getRawAnnotations () const inline
Definition at line 3313 of file DebugInfoMetadata.h.
References llvm::MDNode::getOperand().
Referenced by getAnnotations().
getScope()
DILocalScope * llvm::DILocalVariable::getScope () const inline
Get the local scope for this variable.
Variables must be defined in a local scope.
Definition at line 3302 of file DebugInfoMetadata.h.
References llvm::DIVariable::getScope().
Referenced by llvm::DebugHandlerBase::beginFunction(), buildFrameDebugInfo(), LiveDebugValues::MLocTracker::emitLoc(), TransferTracker::emitMOLoc(), isValidLocationForIntrinsic(), and llvm::DebugInfoFinder::processVariable().
isArtificial()
bool llvm::DILocalVariable::isArtificial () const inline
Definition at line 3315 of file DebugInfoMetadata.h.
References getFlags().
isObjectPointer()
bool llvm::DILocalVariable::isObjectPointer () const inline
Definition at line 3316 of file DebugInfoMetadata.h.
References getFlags().
isParameter()
bool llvm::DILocalVariable::isParameter () const inline
Definition at line 3306 of file DebugInfoMetadata.h.
Referenced by llvm::DebugHandlerBase::beginFunction(), llvm::SelectionDAGBuilder::handleDebugDeclare(), llvm::SelectionDAGBuilder::handleDebugValue(), and TransferTracker::isEntryValueVariable().
isValidLocationForIntrinsic()
bool llvm::DILocalVariable::isValidLocationForIntrinsic (const DILocation * DL) const inline
Check that a location is valid for this variable.
Check that DL exists, is in the same subprogram, and has the same inlined-at location as this. (Otherwise, it's not a valid attachment to a DbgInfoIntrinsic.)
Definition at line 3323 of file DebugInfoMetadata.h.
References DL, getScope(), and llvm::DILocalScope::getSubprogram().
Referenced by llvm::calculateDbgEntityHistory(), llvm::FastISel::lowerDbgDeclare(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), and llvm::FastISel::selectIntrinsicCall().
Friends And Related Function Documentation
LLVMContextImpl
friend class LLVMContextImpl friend
Definition at line 3245 of file DebugInfoMetadata.h.
MDNode
friend class MDNode friend
Definition at line 3246 of file DebugInfoMetadata.h.
Member Data Documentation
AlignInBits [1/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t llvm::DILocalVariable::AlignInBits
Definition at line 3293 of file DebugInfoMetadata.h.
AlignInBits [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata llvm::DILocalVariable::AlignInBits
Definition at line 3294 of file DebugInfoMetadata.h.
Annotations
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata* llvm::DILocalVariable::Annotations
Definition at line 3293 of file DebugInfoMetadata.h.
Arg [1/2]
Metadata MDString Metadata unsigned Metadata unsigned llvm::DILocalVariable::Arg
Definition at line 3292 of file DebugInfoMetadata.h.
Arg [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata llvm::DILocalVariable::Arg
Definition at line 3294 of file DebugInfoMetadata.h.
File [1/2]
Metadata MDString Metadata* llvm::DILocalVariable::File
Definition at line 3291 of file DebugInfoMetadata.h.
File [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata llvm::DILocalVariable::File
Definition at line 3294 of file DebugInfoMetadata.h.
Flags [1/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags llvm::DILocalVariable::Flags
Definition at line 3292 of file DebugInfoMetadata.h.
Flags [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata llvm::DILocalVariable::Flags
Definition at line 3294 of file DebugInfoMetadata.h.
Line [1/2]
Metadata MDString Metadata unsigned llvm::DILocalVariable::Line
Definition at line 3292 of file DebugInfoMetadata.h.
Line [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata llvm::DILocalVariable::Line
Definition at line 3294 of file DebugInfoMetadata.h.
Name [1/2]
Metadata MDString* llvm::DILocalVariable::Name
Definition at line 3291 of file DebugInfoMetadata.h.
Name [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata llvm::DILocalVariable::Name
Definition at line 3294 of file DebugInfoMetadata.h.
Scope [1/2]
Metadata* llvm::DILocalVariable::Scope
Definition at line 3291 of file DebugInfoMetadata.h.
Scope [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata llvm::DILocalVariable::Scope
Definition at line 3294 of file DebugInfoMetadata.h.
Type [1/2]
Metadata MDString Metadata unsigned Metadata* llvm::DILocalVariable::Type
Definition at line 3292 of file DebugInfoMetadata.h.
Type [2/2]
Metadata MDString Metadata unsigned Metadata unsigned DIFlags uint32_t Metadata llvm::DILocalVariable::Type
Definition at line 3294 of file DebugInfoMetadata.h.
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfoMetadata.h
lib/IR/DebugInfoMetadata.cpp