LLVM: llvm::orc::ELFDebugObjectSection< ELFT > Class Template Reference
llvm::orc::ELFDebugObjectSection< ELFT > Class Template Reference
Public Member Functions
ELFDebugObjectSection (const typename ELFT::Shdr *Header)
void setTargetMemoryRange (SectionRange Range) override
void dump (raw_ostream &OS, StringRef Name) override
Error validateInBounds (StringRef Buffer, const char *Name) const
Public Member Functions inherited from llvm::orc::DebugObjectSection
virtual void setTargetMemoryRange (SectionRange Range)=0
virtual void dump (raw_ostream &OS, StringRef Name)
virtual ~DebugObjectSection ()=default
Detailed Description
template<typename ELFT>
class llvm::orc::ELFDebugObjectSection< ELFT >
Definition at line 49 of file DebugObjectManagerPlugin.cpp.
Constructor & Destructor Documentation
ELFDebugObjectSection()
template<typename ELFT > llvm::orc::ELFDebugObjectSection< ELFT >::ELFDebugObjectSection (const typename ELFT::Shdr * Header) inline
Definition at line 53 of file DebugObjectManagerPlugin.cpp.
Member Function Documentation
dump()
template<typename ELFT > void llvm::orc::ELFDebugObjectSection< ELFT >::dump (raw_ostream & OS, StringRef Name) override virtual
Reimplemented from llvm::orc::DebugObjectSection.
Definition at line 95 of file DebugObjectManagerPlugin.cpp.
References Addr, llvm::formatv(), Name, and OS.
setTargetMemoryRange()
template<typename ELFT > void llvm::orc::ELFDebugObjectSection< ELFT >::setTargetMemoryRange (SectionRange Range) override virtual
Implements llvm::orc::DebugObjectSection.
Definition at line 66 of file DebugObjectManagerPlugin.cpp.
validateInBounds()
template<typename ELFT > Error llvm::orc::ELFDebugObjectSection< ELFT >::validateInBounds (StringRef Buffer, const char * Name) const
Definition at line 73 of file DebugObjectManagerPlugin.cpp.
References llvm::StringRef::bytes_begin(), llvm::StringRef::bytes_end(), End, llvm::formatv(), llvm::inconvertibleErrorCode(), Name, llvm::StringRef::size(), and llvm::Error::success().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/DebugObjectManagerPlugin.cpp