LLVM: llvm::object::MachOChainedFixupEntry Class Reference
llvm::object::MachOChainedFixupEntry Class Reference
#include "llvm/Object/MachO.h"
Public Types
enum class FixupKind { Bind , Rebase }
Public Member Functions
MachOChainedFixupEntry (Error *Err, const MachOObjectFile *O, bool Parse)
bool operator== (const MachOChainedFixupEntry &) const
bool isBind () const
bool isRebase () const
void moveNext ()
void moveToFirst ()
void moveToEnd ()
Public Member Functions inherited from llvm::object::MachOAbstractFixupEntry
MachOAbstractFixupEntry (Error *Err, const MachOObjectFile *O)
int32_t segmentIndex () const
uint64_t segmentOffset () const
uint64_t segmentAddress () const
StringRef segmentName () const
StringRef sectionName () const
StringRef typeName () const
StringRef symbolName () const
uint32_t flags () const
int64_t addend () const
int ordinal () const
uint64_t address () const
uint64_t pointerValue () const
uint64_t rawValue () const
void moveNext ()
Additional Inherited Members
Protected Member Functions inherited from llvm::object::MachOAbstractFixupEntry
void moveToFirst ()
void moveToEnd ()
uint64_t textAddress () const
Protected Attributes inherited from llvm::object::MachOAbstractFixupEntry
Error * E
const MachOObjectFile * O
uint64_t SegmentOffset = 0
int32_t SegmentIndex = -1
StringRef SymbolName
int32_t Ordinal = 0
uint32_t Flags = 0
int64_t Addend = 0
uint64_t PointerValue = 0
uint64_t RawValue = 0
bool Done = false
Detailed Description
Definition at line 378 of file MachO.h.
Member Enumeration Documentation
FixupKind
enum class llvm::object::MachOChainedFixupEntry::FixupKind strong
Enumerator
Bind
Rebase
Definition at line 380 of file MachO.h.
Constructor & Destructor Documentation
MachOChainedFixupEntry()
MachOChainedFixupEntry::MachOChainedFixupEntry (Error * Err, const MachOObjectFile * O, bool Parse)
Definition at line 3318 of file MachOObjectFile.cpp.
References llvm::object::MachOAbstractFixupEntry::E, llvm::object::MachOObjectFile::getChainedFixupsSegments(), llvm::object::MachOObjectFile::getDyldChainedFixupTargets(), and llvm::object::MachOAbstractFixupEntry::O.
Member Function Documentation
isBind()
bool llvm::object::MachOChainedFixupEntry::isBind () const inline
Definition at line 386 of file MachO.h.
References Bind.
isRebase()
bool llvm::object::MachOChainedFixupEntry::isRebase () const inline
Definition at line 387 of file MachO.h.
References Rebase.
moveNext()
void MachOChainedFixupEntry::moveNext ()
Definition at line 3380 of file MachOObjectFile.cpp.
References llvm::object::MachOAbstractFixupEntry::Addend, assert(), Bind, llvm::MachO::BIND_SYMBOL_FLAGS_WEAK_IMPORT, llvm::object::createError(), llvm::ArrayRef< T >::data(), llvm::object::MachOAbstractFixupEntry::Done, llvm::MachO::DYLD_CHAINED_PTR_64, llvm::MachO::DYLD_CHAINED_PTR_64_OFFSET, llvm::object::MachOAbstractFixupEntry::E, llvm::object::MachOAbstractFixupEntry::Flags, llvm::object::ChainedFixupsSegment::Header, llvm::object::Binary::isLittleEndian(), llvm::sys::IsLittleEndianHost, malformedError(), moveToEnd(), llvm::object::MachOAbstractFixupEntry::O, llvm::object::MachOAbstractFixupEntry::Ordinal, llvm::MachO::dyld_chained_starts_in_segment::page_size, llvm::MachO::dyld_chained_starts_in_segment::pointer_format, llvm::object::MachOAbstractFixupEntry::PointerValue, llvm::object::MachOAbstractFixupEntry::RawValue, Rebase, llvm::Right, llvm::object::ChainedFixupsSegment::SegIdx, llvm::object::MachOAbstractFixupEntry::SegmentIndex, llvm::object::MachOAbstractFixupEntry::SegmentOffset, llvm::ArrayRef< T >::size(), llvm::sys::swapByteOrder(), llvm::object::MachOAbstractFixupEntry::SymbolName, and llvm::object::MachOAbstractFixupEntry::textAddress().
Referenced by moveToFirst().
moveToEnd()
void MachOChainedFixupEntry::moveToEnd ()
Definition at line 3376 of file MachOObjectFile.cpp.
References llvm::object::MachOAbstractFixupEntry::moveToEnd().
Referenced by llvm::object::MachOObjectFile::fixupTable(), and moveNext().
moveToFirst()
void MachOChainedFixupEntry::moveToFirst ()
Definition at line 3362 of file MachOObjectFile.cpp.
References llvm::object::MachOAbstractFixupEntry::Done, moveNext(), and llvm::object::MachOAbstractFixupEntry::moveToFirst().
operator==()
bool MachOChainedFixupEntry::operator== (const MachOChainedFixupEntry & Other) const
Definition at line 3470 of file MachOObjectFile.cpp.
References llvm::object::MachOAbstractFixupEntry::Done, and llvm::Other.
The documentation for this class was generated from the following files:
include/llvm/Object/MachO.h
lib/Object/MachOObjectFile.cpp