LLVM: llvm::orc::SymbolStringPoolEntryUnsafe Class Reference
llvm::orc::SymbolStringPoolEntryUnsafe Class Reference
Provides unsafe access to ownership operations on SymbolStringPtr.
#include "llvm/ExecutionEngine/Orc/SymbolStringPool.h"
Public Types
using PoolEntry = SymbolStringPool::PoolMapEntry
Public Member Functions
SymbolStringPoolEntryUnsafe (PoolEntry *E)
PoolEntry * rawPtr ()
SymbolStringPtr copyToSymbolStringPtr ()
Creates a SymbolStringPtr for this entry, with the SymbolStringPtr retaining the entry as usual.
SymbolStringPtr moveToSymbolStringPtr ()
Creates a SymbolStringPtr for this entry without performing a retain operation during construction.
void retain ()
void release ()
Static Public Member Functions
static SymbolStringPoolEntryUnsafe from (const SymbolStringPtr &S)
Create an unsafe pool entry ref without changing the ref-count.
static SymbolStringPoolEntryUnsafe take (SymbolStringPtr &&S)
Consumes the given SymbolStringPtr without releasing the pool entry.
Detailed Description
Provides unsafe access to ownership operations on SymbolStringPtr.
This class can be used to manage SymbolStringPtr instances from C.
Definition at line 195 of file SymbolStringPool.h.
Member Typedef Documentation
PoolEntry
using llvm::orc::SymbolStringPoolEntryUnsafe::PoolEntry = SymbolStringPool::PoolMapEntry
Definition at line 197 of file SymbolStringPool.h.
Constructor & Destructor Documentation
SymbolStringPoolEntryUnsafe()
llvm::orc::SymbolStringPoolEntryUnsafe::SymbolStringPoolEntryUnsafe (PoolEntry * E) inline
Definition at line 199 of file SymbolStringPool.h.
Member Function Documentation
copyToSymbolStringPtr()
SymbolStringPtr llvm::orc::SymbolStringPoolEntryUnsafe::copyToSymbolStringPtr () inline
Creates a SymbolStringPtr for this entry, with the SymbolStringPtr retaining the entry as usual.
Definition at line 217 of file SymbolStringPool.h.
from()
static SymbolStringPoolEntryUnsafe llvm::orc::SymbolStringPoolEntryUnsafe::from (const SymbolStringPtr & S) inline static
Create an unsafe pool entry ref without changing the ref-count.
Definition at line 202 of file SymbolStringPool.h.
References llvm::orc::SymbolStringPtrBase::S.
Referenced by LLVMOrcCreateDynamicLibrarySearchGeneratorForPath(), LLVMOrcCreateDynamicLibrarySearchGeneratorForProcess(), LLVMOrcMaterializationResponsibilityGetInitializerSymbol(), LLVMOrcMaterializationResponsibilityGetRequestedSymbols(), LLVMOrcMaterializationResponsibilityGetSymbols(), and llvm::orc::CAPIDefinitionGenerator::tryToGenerate().
moveToSymbolStringPtr()
SymbolStringPtr llvm::orc::SymbolStringPoolEntryUnsafe::moveToSymbolStringPtr () inline
Creates a SymbolStringPtr for this entry without performing a retain operation during construction.
Definition at line 221 of file SymbolStringPool.h.
References llvm::orc::SymbolStringPtrBase::S, and std::swap().
Referenced by LLVMOrcCreateCustomMaterializationUnit(), LLVMOrcLazyReexports(), LLVMOrcMaterializationResponsibilityAddDependencies(), LLVMOrcMaterializationResponsibilityDefineMaterializing(), and LLVMOrcLazyCallThroughManagerRef::toSymbolMap().
rawPtr()
PoolEntry * llvm::orc::SymbolStringPoolEntryUnsafe::rawPtr () inline
Definition at line 213 of file SymbolStringPool.h.
Referenced by LLVMOrcSymbolStringPoolEntryStr().
release()
void llvm::orc::SymbolStringPoolEntryUnsafe::release () inline
Definition at line 228 of file SymbolStringPool.h.
References llvm::StringMapEntryStorage< ValueTy >::getValue().
Referenced by LLVMOrcReleaseSymbolStringPoolEntry().
retain()
void llvm::orc::SymbolStringPoolEntryUnsafe::retain () inline
Definition at line 227 of file SymbolStringPool.h.
References llvm::StringMapEntryStorage< ValueTy >::getValue().
Referenced by LLVMOrcRetainSymbolStringPoolEntry().
take()
static SymbolStringPoolEntryUnsafe llvm::orc::SymbolStringPoolEntryUnsafe::take (SymbolStringPtr && S) inline static
Consumes the given SymbolStringPtr without releasing the pool entry.
Definition at line 207 of file SymbolStringPool.h.
References std::swap().
Referenced by LLVMOrcExecutionSessionIntern(), and LLVMOrcLLJITMangleAndIntern().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/SymbolStringPool.h