LLVM: WorkloadImportsManager Class Reference
WorkloadImportsManager Class Reference
A ModuleImportsManager that operates based on a workload definition (see -thinlto-workload-def).
Public Member Functions
WorkloadImportsManager (function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, const ModuleSummaryIndex &Index, DenseMap< StringRef, FunctionImporter::ExportSetTy > *ExportLists)
Public Member Functions inherited from ModuleImportsManager
virtual ~ModuleImportsManager ()=default
virtual void computeImportForModule (const GVSummaryMapTy &DefinedGVSummaries, StringRef ModName, FunctionImporter::ImportMapTy &ImportList)
Given the list of globals defined in a module, compute the list of imports as well as the list of "exports", i.e.
Additional Inherited Members
Static Public Member Functions inherited from ModuleImportsManager
static std::unique_ptr< ModuleImportsManager > create (function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, const ModuleSummaryIndex &Index, DenseMap< StringRef, FunctionImporter::ExportSetTy > *ExportLists=nullptr)
Protected Member Functions inherited from ModuleImportsManager
ModuleImportsManager (function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, const ModuleSummaryIndex &Index, DenseMap< StringRef, FunctionImporter::ExportSetTy > *ExportLists=nullptr)
Protected Attributes inherited from ModuleImportsManager
function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing
const ModuleSummaryIndex & Index
DenseMap< StringRef, FunctionImporter::ExportSetTy > *const ExportLists
Detailed Description
A ModuleImportsManager that operates based on a workload definition (see -thinlto-workload-def).
For modules that do not define workload roots, it applies the base ModuleImportsManager import policy.
Definition at line 435 of file FunctionImport.cpp.
Constructor & Destructor Documentation
WorkloadImportsManager()
WorkloadImportsManager::WorkloadImportsManager (function_ref< bool(GlobalValue::GUID, const GlobalValueSummary *)> IsPrevailing, const ModuleSummaryIndex & Index, DenseMap< StringRef, FunctionImporter::ExportSetTy > * ExportLists) inline
Definition at line 552 of file FunctionImport.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::count(), llvm::dbgs(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::json::fromJSON(), llvm::StringRef::front(), llvm::MemoryBuffer::getFileOrSTDIN(), I, llvm::StringMap< ValueTy, AllocatorTy >::insert(), llvm::StringSet< AllocatorTy >::insert(), LLVM_DEBUG, Name, llvm::json::parse(), llvm::report_fatal_error(), and WorkloadDefinitions.
The documentation for this class was generated from the following file:
lib/Transforms/IPO/FunctionImport.cpp