LLVM: llvm::SIFrameLowering Class Reference
llvm::SIFrameLowering Class Reference final
#include "Target/AMDGPU/SIFrameLowering.h"
Public Member Functions
SIFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align(1))
~SIFrameLowering () override=default
void emitEntryFunctionPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
StackOffset getFrameIndexReference (const MachineFunction &MF, int FI, Register &FrameReg) const override
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS=nullptr) const override
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
void determineCalleeSavesSGPR (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS=nullptr) const
void determinePrologEpilogSGPRSaves (MachineFunction &MF, BitVector &SavedRegs, bool NeedExecCopyReservedReg) const
void emitCSRSpillStores (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc &DL, LiveRegUnits &LiveUnits, Register FrameReg, Register FramePtrRegScratchCopy) const
void emitCSRSpillRestores (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc &DL, LiveRegUnits &LiveUnits, Register FrameReg, Register FramePtrRegScratchCopy) const
bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const override
bool allocateScavengingFrameIndexesNearIncomingSP (const MachineFunction &MF) const override
Control the placement of special register scavenging spill slots when allocating a stack frame.
bool isSupportedStackID (TargetStackID::Value ID) const override
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const override
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
void processFunctionBeforeFrameIndicesReplaced (MachineFunction &MF, RegScavenger *RS=nullptr) const override
processFunctionBeforeFrameIndicesReplaced - This method is called immediately before MO_FrameIndex operands are eliminated, but after the frame is finalized.
MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const override
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
bool requiresStackPointerReference (const MachineFunction &MF) const
Public Member Functions inherited from llvm::AMDGPUFrameLowering
AMDGPUFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align(1))
~AMDGPUFrameLowering () override
unsigned getStackWidth (const MachineFunction &MF) const
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align(1), bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
Align getStackAlign () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
virtual uint64_t getStackThreshold () const
getStackThreshold - Return the maximum stack size
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
Align getTransientStackAlign () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual bool isStackIdSafeForLocalArea (unsigned StackId) const
This method returns whether or not it is safe for an object with the given stack id to be bundled into the local area.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool allocateScavengingFrameIndexesNearIncomingSP (const MachineFunction &MF) const
Control the placement of special register scavenging spill slots when allocating a stack frame.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI, unsigned &MinCSFrameIndex, unsigned &MaxCSFrameIndex) const
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
virtual bool targetHandlesStackFrameRounding () const
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
virtual bool enableShrinkWrapping (const MachineFunction &MF) const
Returns true if the target will correctly handle shrink wrapping.
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual bool enableCalleeSaveSkip (const MachineFunction &MF) const
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
virtual void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const =0
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
virtual void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const =0
virtual void emitZeroCallUsedRegs (BitVector RegsToZero, MachineBasicBlock &MBB) const
emitZeroCallUsedRegs - Zeros out call used registers.
virtual void emitCalleeSavedFrameMovesFullCFA (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI) const
With basic block sections, emit callee saved frame moves for basic blocks that are in a different section.
virtual bool enableCFIFixup (MachineFunction &MF) const
Returns true if we may need to fix the unwind information for the function.
virtual void resetCFIToInitialState (MachineBasicBlock &MBB) const
Emit CFI instructions that recreate the state of the unwind information upon fucntion entry.
virtual void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Replace a StackProbe stub (if any) with the actual probe code inline.
virtual bool stackProbeFunctionModifiesSP () const
Does the stack probe function call return with a modified stack pointer?
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
virtual bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, MutableArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
virtual bool keepFramePointer (const MachineFunction &MF) const
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
virtual bool hasFP (const MachineFunction &MF) const =0
hasFP - Return true if the specified function should have a dedicated frame pointer register.
virtual bool hasReservedCallFrame (const MachineFunction &MF) const
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual StackOffset getFrameIndexReference (const MachineFunction &MF, int FI, Register &FrameReg) const
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
virtual StackOffset getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, Register &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual StackOffset getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
virtual void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS=nullptr) const
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
virtual void processFunctionBeforeFrameIndicesReplaced (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameIndicesReplaced - This method is called immediately before MO_FrameIndex operands are eliminated, but after the frame is finalized.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual bool canUseAsPrologue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a prologue for the target.
virtual bool canUseAsEpilogue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a epilogue for the target.
virtual TargetStackID::Value getStackIDForScalableVectors () const
Returns the StackID that scalable vectors should be associated with.
virtual bool isSupportedStackID (TargetStackID::Value ID) const
virtual bool isProfitableForNoCSROpt (const Function &F) const
Check if the no-CSR optimisation is profitable for the given function.
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual Register getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
virtual DwarfFrameBase getDwarfFrameBase (const MachineFunction &MF) const
Return the frame base information to be encoded in the DWARF subprogram debug info.
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp , StackGrowsDown }
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Detailed Description
Definition at line 17 of file SIFrameLowering.h.
Constructor & Destructor Documentation
SIFrameLowering()
llvm::SIFrameLowering::SIFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl = Align(1)) inline
Definition at line 19 of file SIFrameLowering.h.
~SIFrameLowering()
llvm::SIFrameLowering::~SIFrameLowering () override default
Member Function Documentation
allocateScavengingFrameIndexesNearIncomingSP()
bool SIFrameLowering::allocateScavengingFrameIndexesNearIncomingSP (const MachineFunction & MF) const override virtual
Control the placement of special register scavenging spill slots when allocating a stack frame.
If this returns true, the frame indexes used by the RegScavenger will be allocated closest to the incoming stack pointer.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1724 of file SIFrameLowering.cpp.
References llvm::SIInstrFlags::FlatScratch, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPUAS::PRIVATE_ADDRESS, and TII.
Referenced by processFunctionBeforeFrameFinalized().
assignCalleeSavedSpillSlots()
bool SIFrameLowering::assignCalleeSavedSpillSlots (MachineFunction & MF, const TargetRegisterInfo * TRI, std::vector< CalleeSavedInfo > & CSI) const override virtual
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1684 of file SIFrameLowering.cpp.
References llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getScratchSGPRCopyDstReg(), and llvm::MachineFunction::getSubtarget().
determineCalleeSaves()
void SIFrameLowering::determineCalleeSaves (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS = nullptr) const override virtual
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
The default implementation checks populates the SavedRegs bitset with all registers which are modified in the function, targets may override this function to save additional registers. This method also sets up the register scavenger ensuring there is a free register or a frameindex available. This method should not be called by any passes outside of PEI, because it may change state passed in by MF and RS. The preferred interface outside PEI is getCalleeSaves.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1553 of file SIFrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::SIMachineFunctionInfo::allocateWWMSpill(), assert(), llvm::BitVector::clearBitsInMask(), llvm::BitVector::clearBitsNotInMask(), llvm::count_if(), llvm::TargetFrameLowering::determineCalleeSaves(), determinePrologEpilogSGPRSaves(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getSubtarget(), llvm::SIMachineFunctionInfo::getWWMSpills(), llvm::MachineFrameInfo::hasTailCall(), llvm::AMDGPUMachineFunction::isChainFunction(), llvm::AMDGPUMachineFunction::isEntryFunction(), MBB, MI, llvm::MachineInstr::operands(), llvm::BitVector::reset(), llvm::SIMachineFunctionInfo::shiftSpillPhysVGPRsToLowestRange(), llvm::MachineBasicBlock::sortUniqueLiveIns(), TII, and TRI.
determineCalleeSavesSGPR()
void SIFrameLowering::determineCalleeSavesSGPR (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS = nullptr) const
Definition at line 1639 of file SIFrameLowering.cpp.
References llvm::BitVector::any(), llvm::BitVector::clearBitsInMask(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::MachineFunction::getFrameInfo(), llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), llvm::MachineFunction::getSubtarget(), llvm::MachineFrameInfo::hasCalls(), hasFP(), llvm::SIMachineFunctionInfo::hasSpilledSGPRs(), llvm::AMDGPUMachineFunction::isEntryFunction(), MRI, llvm::BitVector::reset(), llvm::BitVector::set(), and TRI.
determinePrologEpilogSGPRSaves()
void SIFrameLowering::determinePrologEpilogSGPRSaves (MachineFunction & MF, BitVector & SavedRegs, bool NeedExecCopyReservedReg) const
Definition at line 1489 of file SIFrameLowering.cpp.
References llvm::LiveRegUnits::addReg(), allStackObjectsAreDead(), llvm::BitVector::any(), assert(), findUnusedRegister(), llvm::MachineRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::SIMachineFunctionInfo::getSGPRForEXECCopy(), llvm::MachineFunction::getSubtarget(), getVGPRSpillLaneOrTempRegister(), llvm::MachineFrameInfo::hasCalls(), hasFP(), llvm::SIMachineFunctionInfo::hasPrologEpilogSGPRSpillEntry(), I, llvm::LiveRegUnits::init(), MRI, llvm::SIMachineFunctionInfo::setSGPRForEXECCopy(), and TRI.
Referenced by determineCalleeSaves().
eliminateCallFramePseudoInstr()
MachineBasicBlock::iterator SIFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions. Returns an iterator pointing to the instruction after the replaced one.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1752 of file SIFrameLowering.cpp.
References llvm::Add, llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::alignTo(), assert(), llvm::BuildMI(), DL, llvm::MachineBasicBlock::erase(), llvm::MachineFunction::getInfo(), getScratchScaleFactor(), llvm::TargetFrameLowering::getStackAlign(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), llvm::MachineFunction::getSubtarget(), llvm::TargetFrameLowering::hasReservedCallFrame(), I, llvm_unreachable, MBB, and TII.
emitCSRSpillRestores()
void SIFrameLowering::emitCSRSpillRestores (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc & DL, LiveRegUnits & LiveUnits, Register FrameReg, Register FramePtrRegScratchCopy) const
Definition at line 1001 of file SIFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), buildEpilogRestore(), llvm::BuildMI(), buildScratchExecCopy(), DL, llvm::SmallVectorBase< Size_T >::empty(), llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getPrologEpilogSGPRSpills(), llvm::MachineFunction::getSubtarget(), llvm::RegState::Kill, MBB, MBBI, llvm::PrologEpilogSGPRSpillBuilder::restore(), llvm::SIMachineFunctionInfo::splitWWMSpillRegisters(), TII, and TRI.
Referenced by emitEpilogue().
emitCSRSpillStores()
void SIFrameLowering::emitCSRSpillStores (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc & DL, LiveRegUnits & LiveUnits, Register FrameReg, Register FramePtrRegScratchCopy) const
Definition at line 915 of file SIFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::LiveRegUnits::addReg(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), buildPrologSpill(), buildScratchExecCopy(), DL, llvm::SmallVectorBase< Size_T >::empty(), llvm::LiveRegUnits::empty(), llvm::SIMachineFunctionInfo::getAllScratchSGPRCopyDstRegs(), llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getPrologEpilogSGPRSpills(), llvm::MachineFunction::getSubtarget(), llvm::RegState::Kill, MBB, MBBI, llvm::PrologEpilogSGPRSpillBuilder::save(), llvm::MachineBasicBlock::sortUniqueLiveIns(), llvm::SIMachineFunctionInfo::splitWWMSpillRegisters(), TII, and TRI.
Referenced by emitPrologue().
emitEntryFunctionPrologue()
void SIFrameLowering::emitEntryFunctionPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const
Definition at line 594 of file SIFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), allStackObjectsAreDead(), assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), DL, F, llvm::MachineFunction::front(), llvm::MachineFunction::getFrameInfo(), llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineFunction::getFunction(), llvm::SIMachineFunctionInfo::getGITPtrLoReg(), llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getNumPreloadedSGPRs(), llvm::SIMachineFunctionInfo::getPreloadedReg(), llvm::MachineFunction::getRegInfo(), getScratchScaleFactor(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::SIMachineFunctionInfo::getUserSGPRInfo(), llvm::MachineFrameInfo::hasCalls(), llvm::GCNUserSGPRUsageInfo::hasFlatScratchInit(), hasFP(), I, llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::RegState::Kill, MBB, MRI, llvm::AMDGPUFunctionArgInfo::PRIVATE_SEGMENT_BUFFER, llvm::AMDGPUFunctionArgInfo::PRIVATE_SEGMENT_WAVE_BYTE_OFFSET, requiresStackPointerReference(), llvm::ArrayRef< T >::size(), llvm::ArrayRef< T >::slice(), TII, and TRI.
Referenced by emitPrologue().
emitEpilogue()
void SIFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 1221 of file SIFrameLowering.cpp.
References llvm::Add, llvm::MachineInstrBuilder::addImm(), llvm::LiveRegUnits::addReg(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, emitCSRSpillRestores(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), findScratchNonCalleeSaveRegister(), llvm::MachineInstr::FrameDestroy, llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineFunction::getFrameInfo(), llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MachineFrameInfo::getMaxAlign(), llvm::MachineFunction::getRegInfo(), getScratchScaleFactor(), llvm::SIMachineFunctionInfo::getScratchSGPRCopyDstReg(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), hasFP(), llvm::SIMachineFunctionInfo::hasPrologEpilogSGPRSpillEntry(), initLiveUnits(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::SIMachineFunctionInfo::isStackRealigned(), MBB, MBBI, MRI, llvm::report_fatal_error(), llvm::MachineInstrBuilder::setMIFlag(), TII, TRI, and llvm::Align::value().
emitPrologue()
void SIFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 1069 of file SIFrameLowering.cpp.
References llvm::Add, llvm::MachineInstrBuilder::addImm(), llvm::LiveRegUnits::addLiveIns(), llvm::LiveRegUnits::addReg(), llvm::MachineInstrBuilder::addReg(), llvm::And, assert(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), DL, emitCSRSpillStores(), emitEntryFunctionPrologue(), llvm::LiveRegUnits::empty(), EnableSpillVGPRToAGPR, findScratchNonCalleeSaveRegister(), llvm::MachineInstr::FrameSetup, llvm::MachineFunction::getFrameInfo(), llvm::SIMachineFunctionInfo::getFrameOffsetReg(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getMaxAlign(), llvm::SIMachineFunctionInfo::getPrologEpilogSGPRSaveRestoreInfo(), llvm::MachineFunction::getRegInfo(), getScratchScaleFactor(), llvm::SIMachineFunctionInfo::getScratchSGPRCopyDstReg(), llvm::SIMachineFunctionInfo::getStackPtrOffsetReg(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), hasFP(), llvm::SIMachineFunctionInfo::hasPrologEpilogSGPRSpillEntry(), llvm::LiveRegUnits::init(), initLiveUnits(), llvm::AMDGPUMachineFunction::isChainFunction(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::RegState::Kill, MBB, MBBI, MRI, llvm::LiveRegUnits::removeReg(), llvm::report_fatal_error(), requiresStackPointerReference(), llvm::PrologEpilogSGPRSpillBuilder::save(), llvm::SIMachineFunctionInfo::setIsStackRealigned(), llvm::MachineInstrBuilder::setMIFlag(), TII, TRI, and llvm::Align::value().
getFrameIndexReference()
StackOffset SIFrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, Register & FrameReg) const override virtual
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
Returns the displacement from the frame register to the stack frame of the specified index, along with the frame register used (in output arg FrameReg).
The offset is returned directly, and the base register is returned via FrameReg.
This is the default implementation which is overridden for some targets.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1318 of file SIFrameLowering.cpp.
References llvm::StackOffset::getFixed(), llvm::MachineFunction::getFrameInfo(), llvm::SIRegisterInfo::getFrameRegister(), llvm::MachineFrameInfo::getObjectOffset(), and llvm::MachineFunction::getSubtarget().
hasFP()
bool SIFrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register.
For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 1801 of file SIFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), frameTriviallyRequiresSP(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasCalls(), llvm::AMDGPUMachineFunction::isChainFunction(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::MachineFrameInfo::isFrameAddressTaken(), and llvm::TargetMachine::Options.
Referenced by determineCalleeSavesSGPR(), determinePrologEpilogSGPRSaves(), emitEntryFunctionPrologue(), emitEpilogue(), emitPrologue(), and llvm::SIRegisterInfo::getFrameRegister().
isSupportedStackID()
bool SIFrameLowering::isSupportedStackID (TargetStackID::Value ID) const override virtual
Reimplemented from llvm::TargetFrameLowering.
Definition at line 866 of file SIFrameLowering.cpp.
References llvm::TargetStackID::Default, llvm_unreachable, llvm::TargetStackID::NoAlloc, llvm::TargetStackID::ScalableVector, llvm::TargetStackID::SGPRSpill, and llvm::TargetStackID::WasmLocal.
processFunctionBeforeFrameFinalized()
void SIFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS = nullptr) const override virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1327 of file SIFrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::RegScavenger::addScavengingFrameIndex(), allocateScavengingFrameIndexesNearIncomingSP(), llvm::SIMachineFunctionInfo::allocateVGPRSpillToAGPR(), llvm::SIMachineFunctionInfo::allocateWWMSpill(), allSGPRSpillsAreDead(), allStackObjectsAreDead(), assert(), llvm::RegScavenger::backward(), llvm::MachineFrameInfo::CreateStackObject(), llvm::BitVector::empty(), EnableSpillVGPRToAGPR, llvm::RegScavenger::enterBasicBlockEnd(), llvm::SIMachineFunctionInfo::getAGPRSpillVGPRs(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::AMDGPU::getNamedOperandIdx(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFunction::getRegInfo(), llvm::SIMachineFunctionInfo::getScavengeFI(), llvm::MachineFunction::getSubtarget(), llvm::SIMachineFunctionInfo::getVGPRSpillAGPRs(), llvm::SIMachineFunctionInfo::getWWMReservedRegs(), llvm::SIMachineFunctionInfo::hasSpilledVGPRs(), llvm::MachineFrameInfo::hasTailCall(), llvm::AMDGPUMachineFunction::isChainFunction(), llvm::AMDGPUMachineFunction::isEntryFunction(), llvm::MachineFrameInfo::isFixedObjectIndex(), llvm::HexagonInstrInfo::isLoadFromStackSlot(), llvm::HexagonInstrInfo::isStoreToStackSlot(), llvm::make_early_inc_range(), MBB, MI, MRI, llvm::SIMachineFunctionInfo::removeDeadFrameIndices(), llvm::BitVector::set(), llvm::BitVector::set_bits(), llvm::SIMachineFunctionInfo::setVGPRToAGPRSpillDead(), llvm::MachineBasicBlock::sortUniqueLiveIns(), llvm::BitVector::test(), TII, and TRI.
processFunctionBeforeFrameIndicesReplaced()
void SIFrameLowering::processFunctionBeforeFrameIndicesReplaced (MachineFunction & MF, RegScavenger * RS = nullptr) const override virtual
processFunctionBeforeFrameIndicesReplaced - This method is called immediately before MO_FrameIndex operands are eliminated, but after the frame is finalized.
This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1447 of file SIFrameLowering.cpp.
References llvm::MachineFunction::getInfo(), llvm::SIMachineFunctionInfo::getLongBranchReservedReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), llvm::SIMachineFunctionInfo::getVGPRForAGPRCopy(), MRI, llvm::SIMachineFunctionInfo::setLongBranchReservedReg(), llvm::SIMachineFunctionInfo::setVGPRForAGPRCopy(), and TRI.
requiresStackPointerReference()
bool SIFrameLowering::requiresStackPointerReference (const MachineFunction & MF) const
Definition at line 1830 of file SIFrameLowering.cpp.
References assert(), frameTriviallyRequiresSP(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::hasCalls(), llvm::AMDGPUMachineFunction::isChainFunction(), and llvm::AMDGPUMachineFunction::isEntryFunction().
Referenced by emitEntryFunctionPrologue(), and emitPrologue().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/SIFrameLowering.h
lib/Target/AMDGPU/SIFrameLowering.cpp