LLVM: llvm::VPWidenPointerInductionRecipe Class Reference
llvm::VPWidenPointerInductionRecipe Class Reference
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPWidenPointerInductionRecipe (PHINode *Phi, VPValue *Start, VPValue *Step, const InductionDescriptor &IndDesc, bool IsScalarAfterVectorization)
Create a new VPWidenPointerInductionRecipe for Phi with start value Start.
~VPWidenPointerInductionRecipe () override=default
void execute (VPTransformState &State) override
Generate vector values for the pointer induction.
bool onlyScalarsGenerated (ElementCount VF)
Returns true if only scalar values will be generated.
const InductionDescriptor & getInductionDescriptor () const
Returns the induction descriptor for the recipe.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the recipe.
Public Member Functions inherited from llvm::VPHeaderPHIRecipe
~VPHeaderPHIRecipe () override=default
void execute (VPTransformState &State) override=0
Generate the phi nodes.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override=0
Print the recipe.
VPValue * getStartValue ()
Returns the start value of the phi, if one is set.
VPValue * getStartValue () const
void setStartValue (VPValue *V)
Update the start value of the recipe.
virtual VPValue * getBackedgeValue ()
Returns the incoming value from the loop backedge.
virtual VPRecipeBase & getBackedgeRecipe ()
Returns the backedge value as a recipe.
Public Member Functions inherited from llvm::VPSingleDefRecipe
template<typename IterT >
VPSingleDefRecipe (const unsigned char SC, IterT Operands, DebugLoc DL={})
VPSingleDefRecipe (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
template<typename IterT >
VPSingleDefRecipe (const unsigned char SC, IterT Operands, Value *UV, DebugLoc DL={})
Instruction * getUnderlyingInstr ()
Returns the underlying instruction.
const Instruction * getUnderlyingInstr () const
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC, ArrayRef< VPValue * > Operands, DebugLoc DL={})
template<typename IterT >
VPRecipeBase (const unsigned char SC, iterator_range< IterT > Operands, DebugLoc DL={})
virtual ~VPRecipeBase ()=default
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
virtual void execute (VPTransformState &State)=0
The method which generates the output IR instructions that correspond to this VPRecipe, thereby "executing" the VPlan.
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator IP)
Insert an unlinked recipe into BB immediately before the insertion point IP;.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void moveBefore (VPBasicBlock &BB, iplist< VPRecipeBase >::iterator I)
Unlink this recipe and insert into BB before I.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
bool mayHaveSideEffects () const
Returns true if the recipe may have side-effects.
bool isPhi () const
Returns true for PHI-like recipes.
bool mayReadFromMemory () const
Returns true if the recipe may read from memory.
bool mayWriteToMemory () const
Returns true if the recipe may write to memory.
bool mayReadOrWriteMemory () const
Returns true if the recipe may read from or write to memory.
DebugLoc getDebugLoc () const
Returns the debug location of the recipe.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Public Member Functions inherited from llvm::VPDef
VPDef (const unsigned char SC)
virtual ~VPDef ()
VPValue * getVPSingleValue ()
Returns the only VPValue defined by the VPDef.
const VPValue * getVPSingleValue () const
VPValue * getVPValue (unsigned I)
Returns the VPValue with index I defined by the VPDef.
const VPValue * getVPValue (unsigned I) const
ArrayRef< VPValue * > definedValues ()
Returns an ArrayRef of the values defined by the VPDef.
ArrayRef< VPValue * > definedValues () const
Returns an ArrayRef of the values defined by the VPDef.
unsigned getNumDefinedValues () const
Returns the number of values defined by the VPDef.
unsigned getVPDefID () const
void dump () const
Dump the VPDef to stderr (for debugging).
virtual void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const =0
Each concrete VPDef prints itself.
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
VPUserID getVPUserID () const
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
void removeLastOperand ()
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
virtual bool usesScalars (const VPValue *Op) const
Returns true if the VPUser uses scalars of operand Op.
virtual bool onlyFirstLaneUsed (const VPValue *Op) const
Returns true if the VPUser only uses the first lane of operand Op.
virtual bool onlyFirstPartUsed (const VPValue *Op) const
Returns true if the VPUser only uses the first part of operand Op.
Public Member Functions inherited from llvm::VPValue
Value * getUnderlyingValue ()
Return the underlying Value attached to this VPValue.
const Value * getUnderlyingValue () const
VPValue (Value *UV=nullptr)
Create a live-in VPValue.
VPValue (VPDef *Def, Value *UV=nullptr)
Create a VPValue for a Def which is a subclass of VPValue.
VPValue (Value *UV, VPDef *Def)
Create a VPValue for a Def which defines multiple values.
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
virtual ~VPValue ()
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
void dump () const
Dump the value to stderr (for debugging).
unsigned getNumUsers () const
void addUser (VPUser &User)
void removeUser (VPUser &User)
Remove a single User from the list of users.
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser ()
Returns true if the value has more than one unique user.
void replaceAllUsesWith (VPValue *New)
void replaceUsesWithIf (VPValue *New, llvm::function_ref< bool(VPUser &U, unsigned Idx)> ShouldReplace)
Go through the uses list for this VPValue and make each use point to New if the callback ShouldReplace returns true for the given use specified by a pair of (VPUser, the use index).
VPRecipeBase * getDefiningRecipe ()
Returns the recipe defining this VPValue or nullptr if it is not defined by a recipe, i.e.
const VPRecipeBase * getDefiningRecipe () const
bool hasDefiningRecipe () const
Returns true if this VPValue is defined by a recipe.
bool isLiveIn () const
Returns true if this VPValue is a live-in, i.e. defined outside the VPlan.
Value * getLiveInIRValue ()
Returns the underlying IR value, if this VPValue is defined outside the scope of VPlan.
const Value * getLiveInIRValue () const
bool isDefinedOutsideVectorRegions () const
Returns true if the VPValue is defined outside any vector regions, i.e.
Additional Inherited Members
Public Types inherited from llvm::VPDef
using VPRecipeTy = enum { VPBranchOnMaskSC, VPDerivedIVSC, VPExpandSCEVSC, VPInstructionSC, VPInterleaveSC, VPReductionSC, VPReplicateSC, VPScalarIVStepsSC, VPVectorPointerSC, VPWidenCallSC, VPWidenCanonicalIVSC, VPWidenCastSC, VPWidenGEPSC, VPWidenMemoryInstructionSC, VPWidenSC, VPWidenSelectSC, VPBlendSC, VPPredInstPHISC, VPCanonicalIVPHISC, VPActiveLaneMaskPHISC, VPFirstOrderRecurrencePHISC, VPWidenPHISC, VPWidenIntOrFpInductionSC, VPWidenPointerInductionSC, VPReductionPHISC, VPFirstPHISC=VPBlendSC, VPFirstHeaderPHISC=VPCanonicalIVPHISC, VPLastHeaderPHISC=VPReductionPHISC, VPLastPHISC=VPReductionPHISC, }
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Types inherited from llvm::VPUser
enum class VPUserID { Recipe , LiveOut }
Subclass identifier (for isa/dyn_cast).
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Types inherited from llvm::VPValue
enum { VPValueSC , VPVRecipeSC }
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Static Public Member Functions inherited from llvm::VPHeaderPHIRecipe
static bool classof (const VPRecipeBase *B)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPValue *V)
Static Public Member Functions inherited from llvm::VPSingleDefRecipe
static bool classof (const VPRecipeBase *R)
static bool classof (const VPUser *U)
Static Public Member Functions inherited from llvm::VPRecipeBase
static bool classof (const VPDef *D)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPUser *U)
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator = typename ilist_select_iterator_type< OptionsT::has_iterator_bits, ilist_detail::compute_node_options< T, Options... >::type, false, false >::type
using const_self_iterator = typename ilist_select_iterator_type< OptionsT::has_iterator_bits, ilist_detail::compute_node_options< T, Options... >::type, false, true >::type
using reverse_self_iterator = typename ilist_select_iterator_type< OptionsT::has_iterator_bits, ilist_detail::compute_node_options< T, Options... >::type, true, false >::type
using const_reverse_self_iterator = typename ilist_select_iterator_type< OptionsT::has_iterator_bits, ilist_detail::compute_node_options< T, Options... >::type, true, true >::type
Protected Member Functions inherited from llvm::VPHeaderPHIRecipe
VPHeaderPHIRecipe (unsigned char VPDefID, Instruction *UnderlyingInstr, VPValue *Start=nullptr, DebugLoc DL={})
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands, VPUserID ID)
VPUser (std::initializer_list< VPValue * > Operands, VPUserID ID)
template<typename IterT >
VPUser (iterator_range< IterT > Operands, VPUserID ID)
Protected Member Functions inherited from llvm::VPValue
VPValue (const unsigned char SC, Value *UV=nullptr, VPDef *Def=nullptr)
void setUnderlyingValue (Value *Val)
Protected Attributes inherited from llvm::VPValue
Value * UnderlyingVal
VPDef * Def
Pointer to the VPDef that defines this VPValue.
Detailed Description
Definition at line 1622 of file VPlan.h.
Constructor & Destructor Documentation
VPWidenPointerInductionRecipe()
llvm::VPWidenPointerInductionRecipe::VPWidenPointerInductionRecipe (PHINode * Phi, VPValue * Start, VPValue * Step, const InductionDescriptor & IndDesc, bool IsScalarAfterVectorization) inline
Create a new VPWidenPointerInductionRecipe for Phi with start value Start.
Definition at line 1630 of file VPlan.h.
References addOperand().
~VPWidenPointerInductionRecipe()
llvm::VPWidenPointerInductionRecipe::~VPWidenPointerInductionRecipe () override default
Member Function Documentation
execute()
void VPWidenPointerInductionRecipe::execute (VPTransformState & State) override virtual
Generate vector values for the pointer induction.
Implements llvm::VPHeaderPHIRecipe.
Definition at line 9228 of file LoopVectorize.cpp.
References llvm::PHINode::addIncoming(), assert(), llvm::VPTransformState::Builder, llvm::VPTransformState::CFG, llvm::GetElementPtrInst::Create(), llvm::PHINode::Create(), llvm::IRBuilderBase::CreateAdd(), llvm::IRBuilderBase::CreateGEP(), llvm::IRBuilderBase::CreateMul(), llvm::IRBuilderBase::CreateSExtOrTrunc(), llvm::createStepForVF(), llvm::IRBuilderBase::CreateStepVector(), llvm::IRBuilderBase::CreateVectorSplat(), emitTransformedIndex(), GEP, llvm::VectorType::get(), llvm::ConstantInt::get(), llvm::VPTransformState::get(), llvm::VPlan::getCanonicalIV(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getFixedValue(), llvm::InductionDescriptor::getInductionBinOp(), llvm::IRBuilderBase::GetInsertPoint(), llvm::IRBuilderBase::getInt8Ty(), llvm::InductionDescriptor::getKind(), llvm::VPValue::getLiveInIRValue(), llvm::VPUser::getOperand(), llvm::VPRecipeBase::getParent(), llvm::VPBlockBase::getPlan(), llvm::VPTransformState::CFGState::getPreheaderBBFor(), llvm::getRuntimeVF(), llvm::VPHeaderPHIRecipe::getStartValue(), llvm::InductionDescriptor::getStartValue(), llvm::InductionDescriptor::getStep(), llvm::SCEV::getType(), llvm::Value::getType(), getType(), llvm::VPSingleDefRecipe::getUnderlyingInstr(), Idx, llvm::InductionDescriptor::IK_PtrInduction, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), llvm::vputils::onlyFirstLaneUsed(), onlyScalarsGenerated(), llvm::VPTransformState::set(), llvm::Value::setName(), llvm::VPTransformState::UF, and llvm::VPTransformState::VF.
getInductionDescriptor()
const InductionDescriptor & llvm::VPWidenPointerInductionRecipe::getInductionDescriptor () const inline
Returns the induction descriptor for the recipe.
Definition at line 1651 of file VPlan.h.
onlyScalarsGenerated()
bool VPWidenPointerInductionRecipe::onlyScalarsGenerated (ElementCount VF)
Returns true if only scalar values will be generated.
Definition at line 1609 of file VPlanRecipes.cpp.
References llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), and llvm::vputils::onlyFirstLaneUsed().
Referenced by execute().
print()
void VPWidenPointerInductionRecipe::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the recipe.
Implements llvm::VPHeaderPHIRecipe.
Definition at line 1615 of file VPlanRecipes.cpp.
References llvm::VPHeaderPHIRecipe::getStartValue(), llvm::InductionDescriptor::getStep(), and llvm::VPValue::printAsOperand().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/LoopVectorize.cpp
lib/Transforms/Vectorize/VPlanRecipes.cpp