LLVM: llvm::BitsInit Class Reference
llvm::BitsInit Class Reference final
'{ a, b, c }' - Represents an initializer for a BitsRecTy value.
#include "llvm/TableGen/Record.h"
Public Member Functions
BitsInit (const BitsInit &)=delete
BitsInit & operator= (const BitsInit &)=delete
void operator delete (void *p)
void Profile (FoldingSetNodeID &ID) const
unsigned getNumBits () const
Init * convertInitializerTo (RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This function is used to implement the bit range selection operator.
bool isComplete () const override
Is this a complete value with no unset (uninitialized) subvalues?
bool allInComplete () const
bool isConcrete () const override
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
std::string getAsString () const override
Convert this value to a literal form.
Init * resolveReferences (Resolver &R) const override
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
Init * getBit (unsigned Bit) const override
Get the Init value of the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Get the type of the Init as a RecTy.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init * getCastTo (RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This function is used to implement the bit range selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
RecordKeeper & getRecordKeeper () const
Get the record keeper that initialized this Init.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
Is this a complete value with no unset (uninitialized) subvalues?
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print this value.
virtual std::string getAsString () const =0
Convert this value to a literal form.
virtual std::string getAsUnquotedString () const
Convert this value to a literal form, without adding quotes around a string.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
virtual Init * getCastTo (RecTy *Ty) const =0
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
virtual Init * convertInitializerTo (RecTy *Ty) const =0
Convert to a value whose type is Ty, or return null if this is not possible.
virtual Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const
This function is used to implement the bit range selection operator.
virtual RecTy * getFieldType (StringInit *FieldName) const
This function is used to implement the FieldInit class.
virtual Init * resolveReferences (Resolver &R) const
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
virtual Init * getBit (unsigned Bit) const =0
Get the Init value of the specified bit.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::TrailingObjects< BitsInit, Init * >
const T * getTrailingObjects () const
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
T * getTrailingObjects ()
Returns a pointer to the trailing object array of the given type (which must be one of those specified in the class template).
TrailingObjects ()=default
TrailingObjects (const TrailingObjects &)=delete
TrailingObjects (TrailingObjects &&)=delete
TrailingObjects & operator= (const TrailingObjects &)=delete
TrailingObjects & operator= (TrailingObjects &&)=delete
Static Public Member Functions
static bool classof (const Init *I)
static BitsInit * get (RecordKeeper &RK, ArrayRef< Init * > Range)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TrailingObjects< BitsInit, Init * >
static constexpr std::enable_if_t< std::is_same_v< Foo< TrailingTys... >, Foo< Tys... > >, size_t > additionalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the size of the trailing data, if an object were allocated with the given counts (The counts are in the same order as the template arguments).
static constexpr std::enable_if_t< std::is_same_v< Foo< TrailingTys... >, Foo< Tys... > >, size_t > totalSizeToAlloc (typename trailing_objects_internal::ExtractSecondType< TrailingTys, size_t >::type... Counts)
Returns the total size of an object if it were allocated with the given trailing object counts.
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_DagInit , IK_DefInit , IK_FieldInit , IK_IntInit ,
IK_ListInit , IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit ,
IK_UnOpInit , IK_LastOpInit , IK_CondOpInit , IK_FoldOpInit ,
IK_IsAOpInit , IK_ExistsOpInit , IK_AnonymousNameInit , IK_StringInit ,
IK_VarInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit , IK_ArgumentInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
'{ a, b, c }' - Represents an initializer for a BitsRecTy value.
It contains a vector of bits, whose size is determined by the type.
Definition at line 580 of file Record.h.
Constructor & Destructor Documentation
BitsInit()
llvm::BitsInit::BitsInit (const BitsInit &) delete
Member Function Documentation
allInComplete()
bool llvm::BitsInit::allInComplete () const inline
Definition at line 613 of file Record.h.
References getBit(), getNumBits(), and llvm::Init::isComplete().
classof()
static bool llvm::BitsInit::classof (const Init * I) inline static
Definition at line 594 of file Record.h.
References I, and llvm::Init::IK_BitsInit.
convertInitializerBitRange()
Init * BitsInit::convertInitializerBitRange (ArrayRef< unsigned > Bits) const override virtual
This function is used to implement the bit range selection operator.
Given a value, it selects the specified bits, returning them as a new Init of type bits. If it is not legal to use the bit selection operator on this value, null is returned.
Reimplemented from llvm::TypedInit.
Definition at line 485 of file Record.cpp.
References get(), getBit(), getNumBits(), and llvm::TypedInit::getRecordKeeper().
convertInitializerTo()
Init * BitsInit::convertInitializerTo (RecTy * Ty) const override virtual
Convert to a value whose type is Ty, or return null if this is not possible.
This can happen if the value's type is convertible to Ty, but there are unresolved references.
Reimplemented from llvm::TypedInit.
Definition at line 458 of file Record.cpp.
References llvm::IntInit::get(), getBit(), getNumBits(), and llvm::TypedInit::getRecordKeeper().
get()
BitsInit * BitsInit::get (RecordKeeper & RK, ArrayRef< Init * > Range) static
Definition at line 436 of file Record.cpp.
References llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::Allocate(), llvm::detail::RecordKeeperImpl::Allocator, llvm::RecordKeeper::getImpl(), I, ProfileBitsInit(), and llvm::detail::RecordKeeperImpl::TheBitsInitPool.
Referenced by llvm::TypedInit::convertInitializerBitRange(), convertInitializerBitRange(), llvm::IntInit::convertInitializerBitRange(), llvm::TypedInit::convertInitializerTo(), llvm::BitInit::convertInitializerTo(), llvm::IntInit::convertInitializerTo(), resolveReferences(), and llvm::RecordVal::setValue().
getAsString()
std::string BitsInit::getAsString () const override virtual
Convert this value to a literal form.
Implements llvm::Init.
Definition at line 504 of file Record.cpp.
References getBit(), and getNumBits().
getBit()
Init * llvm::BitsInit::getBit (unsigned Bit) const inline override virtual
Get the Init value of the specified bit.
Implements llvm::Init.
Definition at line 624 of file Record.h.
References assert().
Referenced by allInComplete(), checkBitsConcrete(), convertInitializerBitRange(), convertInitializerTo(), getAsString(), isComplete(), isConcrete(), and resolveReferences().
getNumBits()
unsigned llvm::BitsInit::getNumBits () const inline
Definition at line 602 of file Record.h.
Referenced by allInComplete(), checkBitsConcrete(), convertInitializerBitRange(), convertInitializerTo(), getAsString(), isComplete(), isConcrete(), and resolveReferences().
isComplete()
bool llvm::BitsInit::isComplete () const inline override virtual
Is this a complete value with no unset (uninitialized) subvalues?
Reimplemented from llvm::Init.
Definition at line 607 of file Record.h.
References getBit(), getNumBits(), and llvm::Init::isComplete().
isConcrete()
bool BitsInit::isConcrete () const override virtual
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
Reimplemented from llvm::Init.
Definition at line 496 of file Record.cpp.
References getBit(), getNumBits(), and isConcrete().
Referenced by isConcrete().
operator delete()
void llvm::BitsInit::operator delete (void * p) inline
Definition at line 592 of file Record.h.
operator=()
BitsInit & llvm::BitsInit::operator= (const BitsInit &) delete
Profile()
void BitsInit::Profile (FoldingSetNodeID & ID) const
Definition at line 454 of file Record.cpp.
References ProfileBitsInit().
resolveReferences()
Init * BitsInit::resolveReferences (Resolver & R) const override virtual
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 518 of file Record.cpp.
References assert(), get(), llvm::Init::getBit(), getBit(), getNumBits(), llvm::TypedInit::getRecordKeeper(), and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp