LLVM: llvm::jitlink::aarch32::StubsManager_prev7 Class Reference
llvm::jitlink::aarch32::StubsManager_prev7 Class Reference
Stubs builder emits non-position-independent Arm stubs for pre-v7 CPUs.
#include "llvm/ExecutionEngine/JITLink/aarch32.h"
Public Member Functions
StubsManager_prev7 ()=default
bool visitEdge (LinkGraph &G, Block *B, Edge &E)
Implements link-graph traversal via visitExistingEdges()
Static Public Member Functions
static StringRef getSectionName ()
Name of the object file section that will contain all our stubs.
Detailed Description
Stubs builder emits non-position-independent Arm stubs for pre-v7 CPUs.
These architectures have no MovT/MovW instructions and don't support Thumb2. BL is the only Thumb instruction that can generate stubs and they can always be transformed into BLX.
Definition at line 346 of file aarch32.h.
Constructor & Destructor Documentation
StubsManager_prev7()
llvm::jitlink::aarch32::StubsManager_prev7::StubsManager_prev7 () default
Member Function Documentation
getSectionName()
static StringRef llvm::jitlink::aarch32::StubsManager_prev7::getSectionName () inline static
Name of the object file section that will contain all our stubs.
Definition at line 351 of file aarch32.h.
Referenced by visitEdge().
visitEdge()
bool llvm::jitlink::aarch32::StubsManager_prev7::visitEdge (LinkGraph & G, Block * B, Edge & E)
Implements link-graph traversal via visitExistingEdges()
Definition at line 851 of file aarch32.cpp.
References assert(), llvm::jitlink::aarch32::createStubPrev7(), llvm::dbgs(), E, llvm::orc::Exec, G, llvm::jitlink::Symbol::getBlock(), llvm::jitlink::Section::getName(), llvm::Target::getName(), llvm::jitlink::Block::getSection(), getSectionName(), LLVM_DEBUG, llvm::jitlink::aarch32::needsStub(), llvm::orc::Read, and llvm::jitlink::aarch32::Thumb_Jump24.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/JITLink/aarch32.h
lib/ExecutionEngine/JITLink/aarch32.cpp