LLVM: llvm::object::DirectX::Signature Class Reference
llvm::object::DirectX::Signature Class Reference
#include "llvm/Object/DXContainer.h"
Public Member Functions
ViewArray< dxbc::ProgramSignatureElement >::iterator begin () const
ViewArray< dxbc::ProgramSignatureElement >::iterator end () const
StringRef getName (uint32_t Offset) const
bool isEmpty () const
Error initialize (StringRef Part)
Detailed Description
Definition at line 236 of file DXContainer.h.
Member Function Documentation
begin()
ViewArray< dxbc::ProgramSignatureElement >::iterator llvm::object::DirectX::Signature::begin () const inline
Definition at line 242 of file DXContainer.h.
References llvm::object::ViewArray< T >::begin().
end()
ViewArray< dxbc::ProgramSignatureElement >::iterator llvm::object::DirectX::Signature::end () const inline
Definition at line 246 of file DXContainer.h.
References llvm::object::ViewArray< T >::end().
getName()
StringRef llvm::object::DirectX::Signature::getName (uint32_t Offset) const inline
Definition at line 250 of file DXContainer.h.
References assert(), and llvm::Offset.
initialize()
Error DirectX::Signature::initialize (StringRef Part)
Definition at line 104 of file DXContainer.cpp.
References llvm::StringRef::begin(), llvm::dxbc::ProgramSignatureHeader::FirstParamOffset, if(), llvm::dxbc::ProgramSignatureHeader::ParamCount, parseFailed(), readStruct(), llvm::StringRef::size(), Size, llvm::StringRef::substr(), and llvm::Error::success().
isEmpty()
bool llvm::object::DirectX::Signature::isEmpty () const inline
Definition at line 261 of file DXContainer.h.
References llvm::object::ViewArray< T >::isEmpty().
The documentation for this class was generated from the following files:
include/llvm/Object/DXContainer.h
lib/Object/DXContainer.cpp