LLVM: llvm::objcopy::elf::RelocationSection Class Reference
llvm::objcopy::elf::RelocationSection Class Reference
#include "ObjCopy/ELF/ELFObject.h"
Public Member Functions
RelocationSection (const Object &O)
void addRelocation (Relocation Rel)
Error accept (SectionVisitor &Visitor) const override
Error accept (MutableSectionVisitor &Visitor) override
Error removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove) override
Error removeSymbols (function_ref< bool(const Symbol &)> ToRemove) override
void markSymbols () override
void replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > &FromTo) override
const Object & getObject () const
Public Member Functions inherited from llvm::objcopy::elf::RelocSectionWithSymtabBase< SymbolTableSection >
Error initialize (SectionTableRef SecTable) override
void finalize () override
Public Member Functions inherited from llvm::objcopy::elf::RelocationSectionBase
const SectionBase * getSection () const
void setSection (SectionBase *Sec)
StringRef getNamePrefix () const
Public Member Functions inherited from llvm::objcopy::elf::SectionBase
SectionBase ()=default
SectionBase (const SectionBase &)=default
virtual ~SectionBase ()=default
virtual Error initialize (SectionTableRef SecTable)
virtual void finalize ()
virtual Error removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove)
virtual Error removeSymbols (function_ref< bool(const Symbol &)> ToRemove)
virtual Error accept (SectionVisitor &Visitor) const =0
virtual Error accept (MutableSectionVisitor &Visitor)=0
virtual void markSymbols ()
virtual void replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > &)
virtual bool hasContents () const
virtual void onRemove ()
virtual void restoreSymTabLink (SymbolTableSection &)
Static Public Member Functions
static bool classof (const SectionBase *S)
Static Public Member Functions inherited from llvm::objcopy::elf::RelocationSectionBase
static bool classof (const SectionBase *S)
Additional Inherited Members
Public Attributes inherited from llvm::objcopy::elf::SectionBase
std::string Name
Segment * ParentSegment = nullptr
uint64_t HeaderOffset = 0
uint32_t Index = 0
uint32_t OriginalIndex = 0
uint64_t OriginalFlags = 0
uint64_t OriginalType = ELF::SHT_NULL
uint64_t OriginalOffset = std::numeric_limits<uint64_t>::max()
uint64_t Addr = 0
uint64_t Align = 1
uint32_t EntrySize = 0
uint64_t Flags = 0
uint64_t Info = 0
uint64_t Link = ELF::SHN_UNDEF
uint64_t NameIndex = 0
uint64_t Offset = 0
uint64_t Size = 0
uint64_t Type = ELF::SHT_NULL
ArrayRef< uint8_t > OriginalData
bool HasSymbol = false
Protected Member Functions inherited from llvm::objcopy::elf::RelocSectionWithSymtabBase< SymbolTableSection >
RelocSectionWithSymtabBase ()=default
Protected Attributes inherited from llvm::objcopy::elf::RelocSectionWithSymtabBase< SymbolTableSection >
SymbolTableSection * Symbols
Protected Attributes inherited from llvm::objcopy::elf::RelocationSectionBase
SectionBase * SecToApplyRel = nullptr
Detailed Description
Definition at line 788 of file ELFObject.h.
Constructor & Destructor Documentation
RelocationSection()
llvm::objcopy::elf::RelocationSection::RelocationSection (const Object & O) inline
Definition at line 796 of file ELFObject.h.
Member Function Documentation
accept() [1/2]
Error RelocationSection::accept (MutableSectionVisitor & Visitor) override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 980 of file ELFObject.cpp.
References llvm::objcopy::elf::MutableSectionVisitor::visit().
accept() [2/2]
Error RelocationSection::accept (SectionVisitor & Visitor) const override virtual
Implements llvm::objcopy::elf::SectionBase.
Definition at line 976 of file ELFObject.cpp.
References llvm::objcopy::elf::SectionVisitor::visit().
addRelocation()
void llvm::objcopy::elf::RelocationSection::addRelocation (Relocation Rel) inline
Definition at line 797 of file ELFObject.h.
Referenced by initRelocations().
classof()
static bool llvm::objcopy::elf::RelocationSection::classof (const SectionBase * S) inline static
Definition at line 809 of file ELFObject.h.
References llvm::objcopy::elf::SectionBase::OriginalFlags, llvm::objcopy::elf::SectionBase::OriginalType, llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_REL, and llvm::ELF::SHT_RELA.
getObject()
const Object & llvm::objcopy::elf::RelocationSection::getObject () const inline
Definition at line 807 of file ELFObject.h.
Referenced by initRelocations(), and llvm::objcopy::elf::ELFSectionWriter< ELFT >::visit().
markSymbols()
void RelocationSection::markSymbols () override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 995 of file ELFObject.cpp.
removeSectionReferences()
Error RelocationSection::removeSectionReferences (bool AllowBrokenLinks, function_ref< bool(const SectionBase *)> ToRemove) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 880 of file ELFObject.cpp.
References llvm::createStringError(), llvm::invalid_argument, llvm::objcopy::elf::SectionBase::Name, llvm::objcopy::elf::RelocationSectionBase::SecToApplyRel, llvm::Error::success(), llvm::objcopy::elf::RelocSectionWithSymtabBase< SymbolTableSection >::Symbols, and ToRemove.
removeSymbols()
Error RelocationSection::removeSymbols (function_ref< bool(const Symbol &)> ToRemove) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 984 of file ELFObject.cpp.
References llvm::createStringError(), llvm::invalid_argument, llvm::Error::success(), and ToRemove.
replaceSectionReferences()
void RelocationSection::replaceSectionReferences (const DenseMap< SectionBase *, SectionBase * > & FromTo) override virtual
Reimplemented from llvm::objcopy::elf::SectionBase.
Definition at line 1001 of file ELFObject.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::lookup(), and llvm::objcopy::elf::RelocationSectionBase::SecToApplyRel.
The documentation for this class was generated from the following files:
lib/ObjCopy/ELF/ELFObject.h
lib/ObjCopy/ELF/ELFObject.cpp