LLVM: llvm::StackOffset Class Reference
llvm::StackOffset Class Reference
StackOffset holds a fixed and a scalable offset in bytes.
#include "llvm/Support/TypeSize.h"
Public Member Functions
StackOffset ()=default
int64_t getFixed () const
Returns the fixed component of the stack.
int64_t getScalable () const
Returns the scalable component of the stack.
StackOffset operator+ (const StackOffset &RHS) const
StackOffset operator- (const StackOffset &RHS) const
StackOffset & operator+= (const StackOffset &RHS)
StackOffset & operator-= (const StackOffset &RHS)
StackOffset operator- () const
bool operator== (const StackOffset &RHS) const
bool operator!= (const StackOffset &RHS) const
operator bool () const
Static Public Member Functions
static StackOffset getFixed (int64_t Fixed)
static StackOffset getScalable (int64_t Scalable)
static StackOffset get (int64_t Fixed, int64_t Scalable)
Detailed Description
StackOffset holds a fixed and a scalable offset in bytes.
Definition at line 33 of file TypeSize.h.
Constructor & Destructor Documentation
StackOffset()
llvm::StackOffset::StackOffset () default
Member Function Documentation
get()
static StackOffset llvm::StackOffset::get (int64_t Fixed, int64_t Scalable) inline static
Definition at line 44 of file TypeSize.h.
References llvm::Fixed.
Referenced by llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::RISCVRegisterInfo::eliminateFrameIndex(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::isAArch64FrameOffsetLegal(), and llvm::AArch64FrameLowering::resolveFrameOffsetReference().
getFixed() [1/2]
int64_t llvm::StackOffset::getFixed () const inline
Returns the fixed component of the stack.
Definition at line 49 of file TypeSize.h.
References llvm::Fixed.
Referenced by convertCalleeSaveRestoreToSPPrePostIncDec(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::RISCVFrameLowering::eliminateCallFramePseudoInstr(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::LoongArchRegisterInfo::eliminateFrameIndex(), llvm::RISCVRegisterInfo::eliminateFrameIndex(), emitDebugValueComment(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::RISCVFrameLowering::emitEpilogue(), llvm::emitFrameOffset(), emitFrameOffsetAdj(), llvm::AArch64FrameLowering::emitPrologue(), llvm::RISCVFrameLowering::emitPrologue(), getFPOffset(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::R600FrameLowering::getFrameIndexReference(), llvm::SIFrameLowering::getFrameIndexReference(), llvm::ARMFrameLowering::getFrameIndexReference(), llvm::CSKYFrameLowering::getFrameIndexReference(), llvm::HexagonFrameLowering::getFrameIndexReference(), llvm::LoongArchFrameLowering::getFrameIndexReference(), llvm::M68kFrameLowering::getFrameIndexReference(), llvm::MipsSEFrameLowering::getFrameIndexReference(), llvm::NVPTXFrameLowering::getFrameIndexReference(), llvm::RISCVFrameLowering::getFrameIndexReference(), llvm::SparcFrameLowering::getFrameIndexReference(), llvm::SystemZELFFrameLowering::getFrameIndexReference(), llvm::VEFrameLowering::getFrameIndexReference(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::AArch64FrameLowering::getFrameIndexReferencePreferSP(), llvm::X86FrameLowering::getFrameIndexReferenceSP(), llvm::AArch64FrameLowering::getNonLocalFrameIndexReference(), getStackOffset(), llvm::AArch64RegisterInfo::isFrameOffsetLegal(), llvm::AArch64InstrInfo::probedStackAlloc(), llvm::AArch64RegisterInfo::resolveFrameIndex(), llvm::AArch64FrameLowering::resolveFrameOffsetReference(), and llvm::rewriteAArch64FrameIndex().
getFixed() [2/2]
static StackOffset llvm::StackOffset::getFixed (int64_t Fixed) inline static
Definition at line 42 of file TypeSize.h.
References llvm::Fixed.
Referenced by llvm::M68kRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::SystemZELFFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::AArch64FrameLowering::getSEHFrameIndexOffset(), llvm::X86FrameLowering::getWin64EHFrameIndexRef(), llvm::isAArch64FrameOffsetLegal(), LiveDebugValues::SpillLoc::operator<(), llvm::AArch64FrameLowering::resolveFrameOffsetReference(), and llvm::X86FrameLowering::restoreWin32EHStackPointers().
getScalable() [1/2]
int64_t llvm::StackOffset::getScalable () const inline
Returns the scalable component of the stack.
Definition at line 52 of file TypeSize.h.
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), llvm::emitFrameOffset(), emitFrameOffsetAdj(), llvm::AArch64FrameLowering::emitPrologue(), llvm::RISCVFrameLowering::getFrameIndexReference(), and getSVEStackSize().
getScalable() [2/2]
static StackOffset llvm::StackOffset::getScalable (int64_t Scalable) inline static
Definition at line 43 of file TypeSize.h.
Referenced by llvm::isAArch64FrameOffsetLegal(), LiveDebugValues::SpillLoc::operator<(), and llvm::AArch64FrameLowering::resolveFrameOffsetReference().
operator bool()
llvm::StackOffset::operator bool () const inline explicit
Definition at line 82 of file TypeSize.h.
References llvm::Fixed.
operator!=()
bool llvm::StackOffset::operator!= (const StackOffset & RHS) const inline
Definition at line 77 of file TypeSize.h.
References llvm::Fixed, and RHS.
operator+()
StackOffset llvm::StackOffset::operator+ (const StackOffset & RHS) const inline
Definition at line 55 of file TypeSize.h.
References llvm::Fixed, and RHS.
operator+=()
StackOffset & llvm::StackOffset::operator+= (const StackOffset & RHS) inline
Definition at line 61 of file TypeSize.h.
References llvm::Fixed, and RHS.
operator-() [1/2]
StackOffset llvm::StackOffset::operator- () const inline
Definition at line 71 of file TypeSize.h.
References llvm::Fixed.
operator-() [2/2]
StackOffset llvm::StackOffset::operator- (const StackOffset & RHS) const inline
Definition at line 58 of file TypeSize.h.
References llvm::Fixed, and RHS.
operator-=()
StackOffset & llvm::StackOffset::operator-= (const StackOffset & RHS) inline
Definition at line 66 of file TypeSize.h.
References llvm::Fixed, and RHS.
operator==()
bool llvm::StackOffset::operator== (const StackOffset & RHS) const inline
Definition at line 74 of file TypeSize.h.
References llvm::Fixed, and RHS.
The documentation for this class was generated from the following file:
include/llvm/Support/TypeSize.h