LLVM: llvm::InsertPHIStrategy Class Reference
llvm::InsertPHIStrategy Class Reference
Strategy to insert PHI Nodes at the head of each basic block.
#include "llvm/FuzzMutate/IRMutator.h"
Public Member Functions
uint64_t getWeight (size_t CurrentSize, size_t MaxSize, uint64_t CurrentWeight) override
Provide a weight to bias towards choosing this strategy for a mutation.
void mutate (BasicBlock &BB, RandomIRBuilder &IB) override
Public Member Functions inherited from llvm::IRMutationStrategy
virtual ~IRMutationStrategy ()=default
virtual uint64_t getWeight (size_t CurrentSize, size_t MaxSize, uint64_t CurrentWeight)=0
Provide a weight to bias towards choosing this strategy for a mutation.
virtual void mutate (Module &M, RandomIRBuilder &IB)
virtual void mutate (Function &F, RandomIRBuilder &IB)
virtual void mutate (Instruction &I, RandomIRBuilder &IB)
Detailed Description
Strategy to insert PHI Nodes at the head of each basic block.
Definition at line 169 of file IRMutator.h.
Member Function Documentation
getWeight()
uint64_t llvm::InsertPHIStrategy::getWeight (size_t CurrentSize, size_t MaxSize, uint64_t CurrentWeight) inline override virtual
Provide a weight to bias towards choosing this strategy for a mutation.
The value of the weight is arbitrary, but a good default is "the number of distinct ways in which this strategy can mutate a unit". This can also be used to prefer strategies that shrink the overall size of the result when we start getting close to MaxSize.
Implements llvm::IRMutationStrategy.
Definition at line 171 of file IRMutator.h.
mutate()
void InsertPHIStrategy::mutate (BasicBlock & BB, RandomIRBuilder & IB) override virtual
Reimplemented from llvm::IRMutationStrategy.
Definition at line 540 of file IRMutator.cpp.
References llvm::PHINode::Create(), llvm::BasicBlock::front(), llvm::Function::getEntryBlock(), getInsertionRange(), llvm::BasicBlock::getParent(), I, llvm::fuzzerop::onlyType(), PHI, llvm::pred_size(), llvm::predecessors(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
The documentation for this class was generated from the following files:
include/llvm/FuzzMutate/IRMutator.h
lib/FuzzMutate/IRMutator.cpp