LLVM: llvm::detail::BCRecordCoding< ElementTy, Fields > Class Template Reference
llvm::detail::BCRecordCoding< ElementTy, Fields > Class Template Reference
Helper class for dealing with a scalar element in the middle of a record.
#include "llvm/Bitcode/BitcodeConvenience.h"
Static Public Member Functions
template<typename BufferTy , typename ElementDataTy , typename... DataTy>
static void emit (llvm::BitstreamWriter &Stream, BufferTy &buffer, unsigned code, ElementDataTy element, DataTy &&...data)
template<typename T , typename ElementDataTy , typename... DataTy>
static void read (ArrayRef< T > buffer, ElementDataTy &element, DataTy &&...data)
template<typename T , typename... DataTy>
static void read (ArrayRef< T > buffer, std::nullopt_t, DataTy &&...data)
Detailed Description
template<typename ElementTy, typename... Fields>
class llvm::detail::BCRecordCoding< ElementTy, Fields >
Helper class for dealing with a scalar element in the middle of a record.
See also
BCRecordLayout
Definition at line 186 of file BitcodeConvenience.h.
Member Function Documentation
emit()
template<typename ElementTy , typename... Fields> template<typename BufferTy , typename ElementDataTy , typename... DataTy> static void llvm::detail::BCRecordCoding< ElementTy, Fields >::emit (llvm::BitstreamWriter & Stream, BufferTy & buffer, unsigned code, ElementDataTy element, DataTy &&... data) inline static
Definition at line 189 of file BitcodeConvenience.h.
References llvm::detail::BCRecordCoding< ElementTy, Fields >::emit().
Referenced by llvm::detail::BCRecordCoding< ElementTy, Fields >::emit(), and llvm::BCGenericRecordLayout< IDField, Fields >::emitRecord().
read() [1/2]
template<typename ElementTy , typename... Fields> template<typename T , typename ElementDataTy , typename... DataTy> static void llvm::detail::BCRecordCoding< ElementTy, Fields >::read (ArrayRef< T > buffer, ElementDataTy & element, DataTy &&... data) inline static
Definition at line 200 of file BitcodeConvenience.h.
References assert(), llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::front(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), and llvm::ArrayRef< T >::slice().
Referenced by llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), and llvm::BCGenericRecordLayout< IDField, Fields >::readRecord().
read() [2/2]
template<typename ElementTy , typename... Fields> template<typename T , typename... DataTy> static void llvm::detail::BCRecordCoding< ElementTy, Fields >::read (ArrayRef< T > buffer, std::nullopt_t , DataTy &&... data) inline static
Definition at line 209 of file BitcodeConvenience.h.
References assert(), llvm::ArrayRef< T >::empty(), llvm::detail::BCRecordCoding< ElementTy, Fields >::read(), and llvm::ArrayRef< T >::slice().
The documentation for this class was generated from the following file:
include/llvm/Bitcode/BitcodeConvenience.h