LLVM: llvm::BalancedPartitioning Class Reference
llvm::BalancedPartitioning Class Reference
#include "llvm/Support/BalancedPartitioning.h"
Public Member Functions
BalancedPartitioning (const BalancedPartitioningConfig &Config)
void run (std::vector< BPFunctionNode > &Nodes) const
Run recursive graph partitioning that optimizes a given objective.
Static Protected Member Functions
static float moveGain (const BPFunctionNode &N, bool FromLeftToRight, const SignaturesT &Signatures)
Compute the move gain for uniform log-gap cost.
Friends
class BalancedPartitioningTest_MoveGain_Test
Detailed Description
Definition at line 100 of file BalancedPartitioning.h.
Constructor & Destructor Documentation
BalancedPartitioning()
BalancedPartitioning::BalancedPartitioning (const BalancedPartitioningConfig & Config)
Definition at line 69 of file BalancedPartitioning.cpp.
References I.
Member Function Documentation
moveGain()
float BalancedPartitioning::moveGain (const BPFunctionNode & N, bool FromLeftToRight, const SignaturesT & Signatures) static protected
Compute the move gain for uniform log-gap cost.
Definition at line 316 of file BalancedPartitioning.cpp.
References N, and Signatures.
run()
void BalancedPartitioning::run (std::vector< BPFunctionNode > & Nodes) const
Run recursive graph partitioning that optimizes a given objective.
Definition at line 78 of file BalancedPartitioning.cpp.
References llvm::dbgs(), llvm::format(), I, llvm::BalancedPartitioningConfig::IterationsPerSplit, LLVM_DEBUG, llvm::make_range(), llvm::BalancedPartitioningConfig::SplitDepth, llvm::stable_sort(), and llvm::BalancedPartitioningConfig::TaskSplitDepth.
Friends And Related Function Documentation
BalancedPartitioningTest_MoveGain_Test
friend class BalancedPartitioningTest_MoveGain_Test friend
Definition at line 197 of file BalancedPartitioning.h.
The documentation for this class was generated from the following files:
include/llvm/Support/BalancedPartitioning.h
lib/Support/BalancedPartitioning.cpp