LLVM: llvm::coverage::CoverageMapError Class Reference
llvm::coverage::CoverageMapError Class Reference
#include "llvm/ProfileData/Coverage/CoverageMapping.h"
Public Member Functions
CoverageMapError (coveragemap_error Err, const Twine &ErrStr=Twine())
std::string message () const override
Return the error message as a string.
void log (raw_ostream &OS) const override
Print an error message to an output stream.
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
coveragemap_error get () const
const std::string & getMessage () const
Public Member Functions inherited from llvm::ErrorInfo< CoverageMapError >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual void log (raw_ostream &OS) const =0
Print an error message to an output stream.
virtual std::string message () const
Return the error message as a string.
virtual std::error_code convertToErrorCode () const =0
Convert this error to a std::error_code.
virtual const void * dynamicClassID () const =0
virtual bool isA (const void *const ClassID) const
template<typename ErrorInfoT >
bool isA () const
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::ErrorInfo< CoverageMapError >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Detailed Description
Definition at line 78 of file CoverageMapping.h.
Constructor & Destructor Documentation
CoverageMapError()
llvm::coverage::CoverageMapError::CoverageMapError (coveragemap_error Err, const Twine & ErrStr = Twine()) inline
Definition at line 80 of file CoverageMapping.h.
References assert(), and llvm::coverage::success.
Member Function Documentation
convertToErrorCode()
std::error_code llvm::coverage::CoverageMapError::convertToErrorCode () const inline override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 89 of file CoverageMapping.h.
References llvm::coverage::make_error_code().
get()
coveragemap_error llvm::coverage::CoverageMapError::get () const inline
Definition at line 93 of file CoverageMapping.h.
Referenced by handleMaybeNoDataFoundError().
getMessage()
const std::string & llvm::coverage::CoverageMapError::getMessage () const inline
Definition at line 94 of file CoverageMapping.h.
Referenced by handleMaybeNoDataFoundError().
log()
void llvm::coverage::CoverageMapError::log (raw_ostream & OS) const inline override virtual
Print an error message to an output stream.
Implements llvm::ErrorInfoBase.
Definition at line 87 of file CoverageMapping.h.
References message(), and OS.
message()
std::string CoverageMapError::message () const override virtual
Return the error message as a string.
Reimplemented from llvm::ErrorInfoBase.
Definition at line 1569 of file CoverageMapping.cpp.
References getCoverageMapErrString().
Referenced by log().
Member Data Documentation
ID
char CoverageMapError::ID = 0 static
Definition at line 96 of file CoverageMapping.h.
The documentation for this class was generated from the following files:
include/llvm/ProfileData/Coverage/CoverageMapping.h
lib/ProfileData/Coverage/CoverageMapping.cpp