LLVM: llvm::CSKYMCCodeEmitter Class Reference
llvm::CSKYMCCodeEmitter Class Reference
#include "Target/CSKY/MCTargetDesc/CSKYMCCodeEmitter.h"
Public Member Functions
CSKYMCCodeEmitter (MCContext &Ctx, const MCInstrInfo &MII)
~CSKYMCCodeEmitter ()
void encodeInstruction (const MCInst &Inst, SmallVectorImpl< char > &CB, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const override
Encode the given Inst to bytes and append to CB.
uint64_t getBinaryCodeForInstr (const MCInst &MI, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getMachineOpValue (const MCInst &MI, const MCOperand &MO, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
template<int shift = 0>
unsigned getImmOpValue (const MCInst &MI, unsigned Idx, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getRegSeqImmOpValue (const MCInst &MI, unsigned Idx, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getRegisterSeqOpValue (const MCInst &MI, unsigned Op, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getOImmOpValue (const MCInst &MI, unsigned Idx, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getImmOpValueIDLY (const MCInst &MI, unsigned Idx, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getImmJMPIX (const MCInst &MI, unsigned Idx, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getImmOpValueMSBSize (const MCInst &MI, unsigned Idx, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getImmShiftOpValue (const MCInst &MI, unsigned Idx, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
MCFixupKind getTargetFixup (const MCExpr *Expr) const
template<llvm::CSKY::Fixups FIXUP>
unsigned getBranchSymbolOpValue (const MCInst &MI, unsigned Idx, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
template<llvm::CSKY::Fixups FIXUP>
unsigned getConstpoolSymbolOpValue (const MCInst &MI, unsigned Idx, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
template<llvm::CSKY::Fixups FIXUP>
unsigned getDataSymbolOpValue (const MCInst &MI, unsigned Idx, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getCallSymbolOpValue (const MCInst &MI, unsigned Idx, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
unsigned getBareSymbolOpValue (const MCInst &MI, unsigned Idx, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
void expandJBTF (const MCInst &MI, SmallVectorImpl< char > &CB, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
void expandNEG (const MCInst &MI, SmallVectorImpl< char > &CB, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
void expandRSUBI (const MCInst &MI, SmallVectorImpl< char > &CB, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const
Public Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter (const MCCodeEmitter &)=delete
MCCodeEmitter & operator= (const MCCodeEmitter &)=delete
virtual ~MCCodeEmitter ()
virtual void reset ()
Lifetime management.
virtual void emitPrefix (const MCInst &Inst, SmallVectorImpl< char > &CB, const MCSubtargetInfo &STI) const
Append the prefixes of given instruction to the code buffer.
virtual void encodeInstruction (const MCInst &Inst, SmallVectorImpl< char > &CB, SmallVectorImpl< MCFixup > &Fixups, const MCSubtargetInfo &STI) const =0
Encode the given Inst to bytes and append to CB.
Additional Inherited Members
Protected Member Functions inherited from llvm::MCCodeEmitter
MCCodeEmitter ()
Detailed Description
Definition at line 25 of file CSKYMCCodeEmitter.h.
Constructor & Destructor Documentation
CSKYMCCodeEmitter()
llvm::CSKYMCCodeEmitter::CSKYMCCodeEmitter (MCContext & Ctx, const MCInstrInfo & MII) inline
Definition at line 30 of file CSKYMCCodeEmitter.h.
~CSKYMCCodeEmitter()
llvm::CSKYMCCodeEmitter::~CSKYMCCodeEmitter () inline
Definition at line 33 of file CSKYMCCodeEmitter.h.
Member Function Documentation
encodeInstruction()
void CSKYMCCodeEmitter::encodeInstruction (const MCInst & Inst, SmallVectorImpl< char > & CB, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const override virtual
Encode the given Inst to bytes and append to CB.
Implements llvm::MCCodeEmitter.
Definition at line 138 of file CSKYMCCodeEmitter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addOperand(), expandJBTF(), expandNEG(), expandRSUBI(), llvm::MCInstrInfo::get(), getBinaryCodeForInstr(), MI, Size, and writeData().
expandJBTF()
void CSKYMCCodeEmitter::expandJBTF (const MCInst & MI, SmallVectorImpl< char > & CB, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 68 of file CSKYMCCodeEmitter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addOperand(), getBinaryCodeForInstr(), llvm::MCSubtargetInfo::hasFeature(), MI, and writeData().
Referenced by encodeInstruction().
expandNEG()
void CSKYMCCodeEmitter::expandNEG (const MCInst & MI, SmallVectorImpl< char > & CB, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 94 of file CSKYMCCodeEmitter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addOperand(), getBinaryCodeForInstr(), MI, Size, and writeData().
Referenced by encodeInstruction().
expandRSUBI()
void CSKYMCCodeEmitter::expandRSUBI (const MCInst & MI, SmallVectorImpl< char > & CB, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 116 of file CSKYMCCodeEmitter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addOperand(), getBinaryCodeForInstr(), MI, Size, and writeData().
Referenced by encodeInstruction().
getBareSymbolOpValue()
unsigned llvm::CSKYMCCodeEmitter::getBareSymbolOpValue (const MCInst & MI, unsigned Idx, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const inline
Definition at line 161 of file CSKYMCCodeEmitter.h.
References assert(), llvm::MCFixup::create(), llvm::CSKY::fixup_csky_pcrel_imm18_scale2, llvm::MCOperand::getExpr(), llvm::MCExpr::getKind(), getTargetFixup(), Idx, llvm::MCOperand::isExpr(), MI, and llvm::MCExpr::Target.
getBinaryCodeForInstr()
uint64_t llvm::CSKYMCCodeEmitter::getBinaryCodeForInstr (const MCInst & MI, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Referenced by encodeInstruction(), expandJBTF(), expandNEG(), and expandRSUBI().
getBranchSymbolOpValue()
template<llvm::CSKY::Fixups FIXUP> unsigned llvm::CSKYMCCodeEmitter::getBranchSymbolOpValue (const MCInst & MI, unsigned Idx, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const inline
Definition at line 99 of file CSKYMCCodeEmitter.h.
References assert(), llvm::MCFixup::create(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCExpr::getKind(), getTargetFixup(), Idx, llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), MI, and llvm::MCExpr::Target.
getCallSymbolOpValue()
unsigned llvm::CSKYMCCodeEmitter::getCallSymbolOpValue (const MCInst & MI, unsigned Idx, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const inline
Definition at line 147 of file CSKYMCCodeEmitter.h.
References assert(), llvm::MCFixup::create(), llvm::CSKY::fixup_csky_pcrel_imm26_scale2, llvm::MCOperand::getExpr(), llvm::MCExpr::getKind(), getTargetFixup(), Idx, llvm::MCOperand::isExpr(), MI, and llvm::MCExpr::Target.
getConstpoolSymbolOpValue()
template<llvm::CSKY::Fixups FIXUP> unsigned llvm::CSKYMCCodeEmitter::getConstpoolSymbolOpValue (const MCInst & MI, unsigned Idx, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const inline
Definition at line 118 of file CSKYMCCodeEmitter.h.
References assert(), llvm::MCFixup::create(), llvm::MCOperand::getExpr(), llvm::MCExpr::getKind(), getTargetFixup(), Idx, llvm::MCOperand::isExpr(), MI, and llvm::MCExpr::Target.
getDataSymbolOpValue()
template<llvm::CSKY::Fixups FIXUP> unsigned llvm::CSKYMCCodeEmitter::getDataSymbolOpValue (const MCInst & MI, unsigned Idx, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const inline
Definition at line 133 of file CSKYMCCodeEmitter.h.
References assert(), llvm::MCFixup::create(), llvm::MCOperand::getExpr(), llvm::MCExpr::getKind(), getTargetFixup(), Idx, llvm::MCOperand::isExpr(), MI, and llvm::MCExpr::Target.
getImmJMPIX()
unsigned CSKYMCCodeEmitter::getImmJMPIX (const MCInst & MI, unsigned Idx, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 278 of file CSKYMCCodeEmitter.cpp.
References assert(), Idx, and MI.
getImmOpValue()
template<int shift = 0> unsigned llvm::CSKYMCCodeEmitter::getImmOpValue (const MCInst & MI, unsigned Idx, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const inline
Definition at line 50 of file CSKYMCCodeEmitter.h.
References assert(), llvm::MCFixup::create(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), getTargetFixup(), Idx, llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), and MI.
getImmOpValueIDLY()
unsigned CSKYMCCodeEmitter::getImmOpValueIDLY (const MCInst & MI, unsigned Idx, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 39 of file CSKYMCCodeEmitter.cpp.
References assert(), llvm::MCOperand::getImm(), Idx, llvm::MCOperand::isImm(), and MI.
getImmOpValueMSBSize()
unsigned CSKYMCCodeEmitter::getImmOpValueMSBSize (const MCInst & MI, unsigned Idx, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 50 of file CSKYMCCodeEmitter.cpp.
References assert(), llvm::MCOperand::getImm(), Idx, llvm::MCOperand::isImm(), and MI.
getImmShiftOpValue()
unsigned llvm::CSKYMCCodeEmitter::getImmShiftOpValue (const MCInst & MI, unsigned Idx, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const inline
Definition at line 88 of file CSKYMCCodeEmitter.h.
References assert(), llvm::MCOperand::getImm(), Idx, llvm::MCOperand::isImm(), and MI.
getMachineOpValue()
unsigned CSKYMCCodeEmitter::getMachineOpValue (const MCInst & MI, const MCOperand & MO, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 235 of file CSKYMCCodeEmitter.cpp.
References llvm::MCRegisterInfo::getEncodingValue(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCContext::getRegisterInfo(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and llvm_unreachable.
getOImmOpValue()
unsigned CSKYMCCodeEmitter::getOImmOpValue (const MCInst & MI, unsigned Idx, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 30 of file CSKYMCCodeEmitter.cpp.
References assert(), llvm::MCOperand::getImm(), Idx, llvm::MCOperand::isImm(), and MI.
getRegisterSeqOpValue()
unsigned CSKYMCCodeEmitter::getRegisterSeqOpValue (const MCInst & MI, unsigned Op, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 265 of file CSKYMCCodeEmitter.cpp.
References llvm::MCRegisterInfo::getEncodingValue(), llvm::MCContext::getRegisterInfo(), and MI.
getRegSeqImmOpValue()
unsigned CSKYMCCodeEmitter::getRegSeqImmOpValue (const MCInst & MI, unsigned Idx, SmallVectorImpl< MCFixup > & Fixups, const MCSubtargetInfo & STI) const
Definition at line 249 of file CSKYMCCodeEmitter.cpp.
References assert(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCContext::getRegisterInfo(), Idx, and MI.
getTargetFixup()
MCFixupKind CSKYMCCodeEmitter::getTargetFixup (const MCExpr * Expr) const
Definition at line 293 of file CSKYMCCodeEmitter.cpp.
References llvm::CSKY::fixup_csky_addr32, llvm::CSKY::fixup_csky_addr_hi16, llvm::CSKY::fixup_csky_addr_lo16, llvm::CSKY::fixup_csky_got32, llvm::CSKY::fixup_csky_got_imm18_scale4, llvm::CSKY::fixup_csky_gotoff, llvm::CSKY::fixup_csky_gotpc, llvm::CSKY::fixup_csky_plt32, llvm::CSKY::fixup_csky_plt_imm18_scale4, llvm::CSKYMCExpr::getKind(), llvm_unreachable, llvm::CSKYMCExpr::VK_CSKY_ADDR, llvm::CSKYMCExpr::VK_CSKY_ADDR_HI16, llvm::CSKYMCExpr::VK_CSKY_ADDR_LO16, llvm::CSKYMCExpr::VK_CSKY_GOT, llvm::CSKYMCExpr::VK_CSKY_GOT_IMM18_BY4, llvm::CSKYMCExpr::VK_CSKY_GOTOFF, llvm::CSKYMCExpr::VK_CSKY_GOTPC, llvm::CSKYMCExpr::VK_CSKY_PLT, and llvm::CSKYMCExpr::VK_CSKY_PLT_IMM18_BY4.
Referenced by getBareSymbolOpValue(), getBranchSymbolOpValue(), getCallSymbolOpValue(), getConstpoolSymbolOpValue(), getDataSymbolOpValue(), and getImmOpValue().
The documentation for this class was generated from the following files:
lib/Target/CSKY/MCTargetDesc/CSKYMCCodeEmitter.h
lib/Target/CSKY/MCTargetDesc/CSKYMCCodeEmitter.cpp