LLVM: llvm::StructType Class Reference
llvm::StructType Class Reference
Class to represent struct types.
#include "llvm/IR/DerivedTypes.h"
Public Types
using element_iterator = Type::subtype_iterator
Public Types inherited from llvm::Type
enum TypeID {
HalfTyID = 0 , BFloatTyID , FloatTyID , DoubleTyID ,
X86_FP80TyID , FP128TyID , PPC_FP128TyID , VoidTyID ,
LabelTyID , MetadataTyID , X86_MMXTyID , X86_AMXTyID ,
TokenTyID , IntegerTyID , FunctionTyID , PointerTyID ,
StructTyID , ArrayTyID , FixedVectorTyID , ScalableVectorTyID ,
TypedPointerTyID , TargetExtTyID
}
Definitions of all of the base types for the Type system.
using subtype_iterator = Type *const *
using subtype_reverse_iterator = std::reverse_iterator< subtype_iterator >
Public Member Functions
StructType (const StructType &)=delete
StructType & operator= (const StructType &)=delete
bool isPacked () const
bool isLiteral () const
Return true if this type is uniqued by structural equivalence, false if it is a struct definition.
bool isOpaque () const
Return true if this is a type with an identity that has no body specified yet.
bool isSized (SmallPtrSetImpl< Type * > *Visited=nullptr) const
isSized - Return true if this is a sized type.
bool containsScalableVectorType (SmallPtrSetImpl< Type * > *Visited=nullptr) const
Returns true if this struct contains a scalable vector.
bool containsHomogeneousScalableVectorTypes () const
Returns true if this struct contains homogeneous scalable vector types.
bool hasName () const
Return true if this is a named struct that has a non-empty name.
StringRef getName () const
Return the name for this struct type if it has an identity.
void setName (StringRef Name)
Change the name of this type to the specified name, or to a name with a suffix if there is a collision.
void setBody (ArrayRef< Type * > Elements, bool isPacked=false)
Specify a body for an opaque identified type.
template<typename... Tys>
std::enable_if_t< are_base_of< Type, Tys... >::value, void > setBody (Type *elt1, Tys *... elts)
element_iterator element_begin () const
element_iterator element_end () const
ArrayRef< Type * > elements () const
bool isLayoutIdentical (StructType *Other) const
Return true if this is layout identical to the specified struct.
unsigned getNumElements () const
Random access to the elements.
Type * getElementType (unsigned N) const
Type * getTypeAtIndex (const Value *V) const
Given an index value into the type, return the type of the element.
Type * getTypeAtIndex (unsigned N) const
bool indexValid (const Value *V) const
bool indexValid (unsigned Idx) const
Public Member Functions inherited from llvm::Type
void print (raw_ostream &O, bool IsForDebug=false, bool NoDetails=false) const
Print the current type.
void dump () const
LLVMContext & getContext () const
Return the LLVMContext in which this type was uniqued.
TypeID getTypeID () const
Return the type id for the type.
bool isVoidTy () const
Return true if this is 'void'.
bool isHalfTy () const
Return true if this is 'half', a 16-bit IEEE fp type.
bool isBFloatTy () const
Return true if this is 'bfloat', a 16-bit bfloat type.
bool is16bitFPTy () const
Return true if this is a 16-bit float type.
bool isFloatTy () const
Return true if this is 'float', a 32-bit IEEE fp type.
bool isDoubleTy () const
Return true if this is 'double', a 64-bit IEEE fp type.
bool isX86_FP80Ty () const
Return true if this is x86 long double.
bool isFP128Ty () const
Return true if this is 'fp128'.
bool isPPC_FP128Ty () const
Return true if this is powerpc long double.
bool isIEEELikeFPTy () const
Return true if this is a well-behaved IEEE-like type, which has a IEEE compatible layout as defined by APFloat::isIEEE(), and does not have non-IEEE values, such as x86_fp80's unnormal values.
bool isFloatingPointTy () const
Return true if this is one of the floating-point types.
bool isMultiUnitFPType () const
Returns true if this is a floating-point type that is an unevaluated sum of multiple floating-point units.
const fltSemantics & getFltSemantics () const
bool isX86_MMXTy () const
Return true if this is X86 MMX.
bool isX86_AMXTy () const
Return true if this is X86 AMX.
bool isTargetExtTy () const
Return true if this is a target extension type.
bool isScalableTargetExtTy () const
Return true if this is a target extension type with a scalable layout.
bool isScalableTy () const
Return true if this is a type whose size is a known multiple of vscale.
bool isFPOrFPVectorTy () const
Return true if this is a FP type or a vector of FP.
bool isLabelTy () const
Return true if this is 'label'.
bool isMetadataTy () const
Return true if this is 'metadata'.
bool isTokenTy () const
Return true if this is 'token'.
bool isIntegerTy () const
True if this is an instance of IntegerType.
bool isIntegerTy (unsigned Bitwidth) const
Return true if this is an IntegerType of the given width.
bool isIntOrIntVectorTy () const
Return true if this is an integer type or a vector of integer types.
bool isIntOrIntVectorTy (unsigned BitWidth) const
Return true if this is an integer type or a vector of integer types of the given width.
bool isIntOrPtrTy () const
Return true if this is an integer type or a pointer type.
bool isFunctionTy () const
True if this is an instance of FunctionType.
bool isStructTy () const
True if this is an instance of StructType.
bool isArrayTy () const
True if this is an instance of ArrayType.
bool isPointerTy () const
True if this is an instance of PointerType.
bool isOpaquePointerTy () const
True if this is an instance of an opaque PointerType.
bool isPtrOrPtrVectorTy () const
Return true if this is a pointer type or a vector of pointer types.
bool isVectorTy () const
True if this is an instance of VectorType.
bool canLosslesslyBitCastTo (Type *Ty) const
Return true if this type could be converted with a lossless BitCast to type 'Ty'.
bool isEmptyTy () const
Return true if this type is empty, that is, it has no elements or all of its elements are empty.
bool isFirstClassType () const
Return true if the type is "first class", meaning it is a valid type for a Value.
bool isSingleValueType () const
Return true if the type is a valid type for a register in codegen.
bool isAggregateType () const
Return true if the type is an aggregate type.
bool isSized (SmallPtrSetImpl< Type * > *Visited=nullptr) const
Return true if it makes sense to take the size of this type.
TypeSize getPrimitiveSizeInBits () const LLVM_READONLY
Return the basic size of this type if it is a primitive type.
unsigned getScalarSizeInBits () const LLVM_READONLY
If this is a vector type, return the getPrimitiveSizeInBits value for the element type.
int getFPMantissaWidth () const
Return the width of the mantissa of this type.
bool isIEEE () const
Return whether the type is IEEE compatible, as defined by the eponymous method in APFloat.
Type * getScalarType () const
If this is a vector type, return the element type, otherwise return 'this'.
subtype_iterator subtype_begin () const
subtype_iterator subtype_end () const
ArrayRef< Type * > subtypes () const
subtype_reverse_iterator subtype_rbegin () const
subtype_reverse_iterator subtype_rend () const
Type * getContainedType (unsigned i) const
This method is used to implement the type iterator (defined at the end of the file).
unsigned getNumContainedTypes () const
Return the number of types in the derived type.
unsigned getIntegerBitWidth () const
Type * getFunctionParamType (unsigned i) const
unsigned getFunctionNumParams () const
bool isFunctionVarArg () const
StringRef getStructName () const
unsigned getStructNumElements () const
Type * getStructElementType (unsigned N) const
uint64_t getArrayNumElements () const
Type * getArrayElementType () const
StringRef getTargetExtName () const
Type * getNonOpaquePointerElementType () const
Only use this method in code that is not reachable with opaque pointers, or part of deprecated methods that will be removed as part of the opaque pointers transition.
Type * getWithNewType (Type *EltTy) const
Given vector type, change the element type, whilst keeping the old number of elements.
Type * getWithNewBitWidth (unsigned NewBitWidth) const
Given an integer or vector type, change the lane bitwidth to NewBitwidth, whilst keeping the old number of lanes.
Type * getExtendedType () const
Given scalar/vector integer type, returns a type with elements twice as wide as in the original type.
unsigned getPointerAddressSpace () const
Get the address space of this pointer or pointer vector type.
PointerType * getPointerTo (unsigned AddrSpace=0) const
Return a pointer to the current type.
Static Public Member Functions
static StructType * create (LLVMContext &Context, StringRef Name)
This creates an identified struct.
static StructType * create (LLVMContext &Context)
static StructType * create (ArrayRef< Type * > Elements, StringRef Name, bool isPacked=false)
static StructType * create (ArrayRef< Type * > Elements)
static StructType * create (LLVMContext &Context, ArrayRef< Type * > Elements, StringRef Name, bool isPacked=false)
static StructType * create (LLVMContext &Context, ArrayRef< Type * > Elements)
template<class... Tys>
static std::enable_if_t< are_base_of< Type, Tys... >::value, StructType * > create (StringRef Name, Type *elt1, Tys *... elts)
static StructType * get (LLVMContext &Context, ArrayRef< Type * > Elements, bool isPacked=false)
This static method is the primary way to create a literal StructType.
static StructType * get (LLVMContext &Context, bool isPacked=false)
Create an empty structure type.
template<class... Tys>
static std::enable_if_t< are_base_of< Type, Tys... >::value, StructType * > get (Type *elt1, Tys *... elts)
This static method is a convenience method for creating structure types by specifying the elements as arguments.
static StructType * getTypeByName (LLVMContext &C, StringRef Name)
Return the type with the specified name, or null if there is none by that name.
static bool isValidElementType (Type *ElemTy)
Return true if the specified type is valid as a element type.
static bool classof (const Type *T)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Type
static Type * getPrimitiveType (LLVMContext &C, TypeID IDNumber)
Return a type based on an identifier.
static Type * getVoidTy (LLVMContext &C)
static Type * getLabelTy (LLVMContext &C)
static Type * getHalfTy (LLVMContext &C)
static Type * getBFloatTy (LLVMContext &C)
static Type * getFloatTy (LLVMContext &C)
static Type * getDoubleTy (LLVMContext &C)
static Type * getMetadataTy (LLVMContext &C)
static Type * getX86_FP80Ty (LLVMContext &C)
static Type * getFP128Ty (LLVMContext &C)
static Type * getPPC_FP128Ty (LLVMContext &C)
static Type * getX86_MMXTy (LLVMContext &C)
static Type * getX86_AMXTy (LLVMContext &C)
static Type * getTokenTy (LLVMContext &C)
static IntegerType * getIntNTy (LLVMContext &C, unsigned N)
static IntegerType * getInt1Ty (LLVMContext &C)
static IntegerType * getInt8Ty (LLVMContext &C)
static IntegerType * getInt16Ty (LLVMContext &C)
static IntegerType * getInt32Ty (LLVMContext &C)
static IntegerType * getInt64Ty (LLVMContext &C)
static IntegerType * getInt128Ty (LLVMContext &C)
template<typename ScalarTy >
static Type * getScalarTy (LLVMContext &C)
static Type * getFloatingPointTy (LLVMContext &C, const fltSemantics &S)
static Type * getWasm_ExternrefTy (LLVMContext &C)
static Type * getWasm_FuncrefTy (LLVMContext &C)
Additional Inherited Members
Protected Member Functions inherited from llvm::Type
Type (LLVMContext &C, TypeID tid)
~Type ()=default
unsigned getSubclassData () const
void setSubclassData (unsigned val)
Protected Attributes inherited from llvm::Type
unsigned NumContainedTys = 0
Keeps track of how many Type*'s there are in the ContainedTys list.
Type *const * ContainedTys = nullptr
A pointer to the array of Types contained by this Type.
Detailed Description
Class to represent struct types.
There are two different kinds of struct types: Literal structs and Identified structs.
Literal struct types (e.g. { i32, i32 }) are uniqued structurally, and must always have a body when created. You can get one of these by using one of the StructType::get() forms.
Identified structs (e.g. foo or %42) may optionally have a name and are not uniqued. The names for identified structs are managed at the LLVMContext level, so there can only be a single identified struct with a given name in a particular LLVMContext. Identified structs may also optionally be opaque (have no body specified). You get one of these by using one of the StructType::create() forms.
Independent of what kind of struct you have, the body of a struct type are laid out in memory consecutively with the elements directly one after the other (if the struct is packed) or (if not packed) with padding between the elements as defined by DataLayout (which is required to match what the code generator for a target expects).
Definition at line 216 of file DerivedTypes.h.
Member Typedef Documentation
element_iterator
using llvm::StructType::element_iterator = Type::subtype_iterator
Definition at line 329 of file DerivedTypes.h.
Constructor & Destructor Documentation
StructType()
llvm::StructType::StructType (const StructType &) delete
Member Function Documentation
classof()
static bool llvm::StructType::classof (const Type * T) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 353 of file DerivedTypes.h.
References llvm::Type::StructTyID.
containsHomogeneousScalableVectorTypes()
bool StructType::containsHomogeneousScalableVectorTypes () const
Returns true if this struct contains homogeneous scalable vector types.
Note that the definition of homogeneous scalable vector type is not recursive here. That means the following structure will return false when calling this function. {{<vscale x 2 x i32>, <vscale x 4 x i64>}, {<vscale x 2 x i32>, <vscale x 4 x i64>}}
Definition at line 435 of file Type.cpp.
References elements(), and getNumElements().
Referenced by isSized().
containsScalableVectorType()
bool StructType::containsScalableVectorType (SmallPtrSetImpl< Type * > * Visited = nullptr) const
Returns true if this struct contains a scalable vector.
Definition at line 400 of file Type.cpp.
References elements(), llvm::Type::getSubclassData(), llvm::SmallPtrSetImpl< PtrType >::insert(), isOpaque(), and llvm::Type::setSubclassData().
create() [1/7]
StructType * StructType::create (ArrayRef< Type * > Elements) static
Definition at line 546 of file Type.cpp.
References assert(), create(), and llvm::Type::getContext().
create() [2/7]
StructType * StructType::create (ArrayRef< Type * > Elements, StringRef Name, bool isPacked = false) static
Definition at line 539 of file Type.cpp.
References assert(), create(), llvm::Type::getContext(), isPacked(), and Name.
create() [3/7]
StructType * StructType::create (LLVMContext & Context) static
Definition at line 535 of file Type.cpp.
References Context, and create().
create() [4/7]
StructType * StructType::create (LLVMContext & Context, ArrayRef< Type * > Elements) static
Definition at line 531 of file Type.cpp.
References Context, and create().
create() [5/7]
StructType * StructType::create (LLVMContext & Context, ArrayRef< Type * > Elements, StringRef Name, bool isPacked = false) static
Definition at line 524 of file Type.cpp.
References Context, create(), isPacked(), and Name.
create() [6/7]
StructType * StructType::create (LLVMContext & Context, StringRef Name) static
This creates an identified struct.
Definition at line 513 of file Type.cpp.
References llvm::LLVMContextImpl::Alloc, Context, Name, and llvm::LLVMContext::pImpl.
Referenced by addEmuTlsVar(), buildFrameType(), create(), llvm::orc::IRSpeculationLayer::emit(), llvm::OpenMPIRBuilder::emitNonContiguousDescriptor(), llvm::offloading::getEntryTy(), getIntrinsicParamType(), llvm::getOrCreateSPIRVDeviceEventPointer(), getOrCreateStructType(), llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost(), and LLVMStructCreateNamed().
create() [7/7]
template<class... Tys> static std::enable_if_t< are_base_of< Type, Tys... >::value, StructType * > llvm::StructType::create (StringRef Name, Type * elt1, Tys *... elts) inline static
Definition at line 251 of file DerivedTypes.h.
References assert(), create(), and Name.
element_begin()
element_iterator llvm::StructType::element_begin () const inline
Definition at line 331 of file DerivedTypes.h.
References llvm::Type::ContainedTys.
Referenced by elements(), and getTypePartition().
element_end()
element_iterator llvm::StructType::element_end () const inline
Definition at line 332 of file DerivedTypes.h.
References llvm::Type::ContainedTys, and llvm::Type::NumContainedTys.
Referenced by elements(), and getTypePartition().
elements()
ArrayRef< Type * > llvm::StructType::elements () const inline
Definition at line 333 of file DerivedTypes.h.
References element_begin(), and element_end().
Referenced by containsHomogeneousScalableVectorTypes(), containsScalableVectorType(), findFuncPointers(), isLayoutIdentical(), isLeakCheckerRoot(), isSized(), and LLVMGetStructElementTypes().
get() [1/3]
StructType * StructType::get (LLVMContext & Context, ArrayRef< Type * > Elements, bool isPacked = false) static
This static method is the primary way to create a literal StructType.
Definition at line 373 of file Type.cpp.
References llvm::LLVMContextImpl::Alloc, llvm::LLVMContextImpl::AnonStructTypes, Context, llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert_as(), isPacked(), and llvm::LLVMContext::pImpl.
Referenced by llvm::memtag::alignAndPadAlloca(), appendToGlobalArray(), classifyConstantWithOpaquePtr(), createAtomicLibcall(), DecodeFixedType(), get(), llvm::ConstantExpr::getAlignOf(), llvm::ConstantStruct::getTypeForElements(), getTypePartition(), insertSinCosCall(), llvm::ARMLegalizerInfo::legalizeCustom(), LLVMStructTypeInContext(), LowerFSINCOS(), lowerSubFn(), llvm::EscapeEnumerator::Next(), llvm::WasmEHPreparePass::run(), and llvm::UpgradeGlobalVariable().
get() [2/3]
StructType * StructType::get (LLVMContext & Context, bool isPacked = false) static
Create an empty structure type.
Definition at line 520 of file Type.cpp.
References Context, get(), and isPacked().
get() [3/3]
template<class... Tys> static std::enable_if_t< are_base_of< Type, Tys... >::value, StructType * > llvm::StructType::get (Type * elt1, Tys *... elts) inline static
This static method is a convenience method for creating structure types by specifying the elements as arguments.
Note that this method always returns a non-packed struct, and requires at least one element type.
Definition at line 268 of file DerivedTypes.h.
References assert(), get(), and llvm::Type::getContext().
getElementType()
Type * llvm::StructType::getElementType (unsigned N) const inline
Definition at line 342 of file DerivedTypes.h.
References assert(), llvm::Type::ContainedTys, N, and llvm::Type::NumContainedTys.
Referenced by buildFrameDebugInfo(), BuildSubAggregate(), llvm::FunctionComparator::cmpTypes(), llvm::coro::Shape::getIndexType(), llvm::coro::Shape::getSwitchResumePointerType(), getTypeAtIndex(), getTypePartition(), insertSpills(), isDenselyPacked(), and llvm::UpgradeGlobalVariable().
getName()
StringRef StructType::getName () const
Return the name for this struct type if it has an identity.
This may return an empty string for an unnamed struct type. Do not call this on an literal type.
Definition at line 590 of file Type.cpp.
References assert(), and isLiteral().
Referenced by llvm::BTFDebug::endModule(), llvm::isSpecialOpaqueType(), and setName().
getNumElements()
unsigned llvm::StructType::getNumElements () const inline
Random access to the elements.
Definition at line 341 of file DerivedTypes.h.
References llvm::Type::NumContainedTys.
Referenced by appendToGlobalArray(), buildFrameDebugInfo(), BuildSubAggregate(), llvm::FunctionComparator::cmpTypes(), containsHomogeneousScalableVectorTypes(), llvm::DataLayout::getStructLayout(), indexValid(), isDenselyPacked(), llvm::SCCPInstVisitor::isStructLatticeConstant(), llvm::UpgradeGlobalVariable(), and llvm::InlineAsm::verify().
getTypeAtIndex() [1/2]
Type * StructType::getTypeAtIndex (const Value * V) const
Given an index value into the type, return the type of the element.
Definition at line 612 of file Type.cpp.
References assert(), getElementType(), Idx, and indexValid().
Referenced by LLVMStructGetTypeAtIndex(), and markCoroutineAsDone().
getTypeAtIndex() [2/2]
Type * llvm::StructType::getTypeAtIndex (unsigned N) const inline
Definition at line 348 of file DerivedTypes.h.
References getElementType(), and N.
getTypeByName()
StructType * StructType::getTypeByName (LLVMContext & C, StringRef Name) static
Return the type with the specified name, or null if there is none by that name.
Definition at line 632 of file Type.cpp.
References llvm::CallingConv::C, and Name.
Referenced by llvm::offloading::getEntryTy(), llvm::getOrCreateSPIRVDeviceEventPointer(), getOrCreateStructType(), LLVMGetTypeByName(), and LLVMGetTypeByName2().
hasName()
bool llvm::StructType::hasName () const inline
Return true if this is a named struct that has a non-empty name.
Definition at line 304 of file DerivedTypes.h.
Referenced by llvm::isSpecialOpaqueType().
indexValid() [1/2]
bool StructType::indexValid (const Value * V) const
Definition at line 618 of file Type.cpp.
References llvm::CallingConv::C, and getNumElements().
Referenced by getTypeAtIndex().
indexValid() [2/2]
bool llvm::StructType::indexValid (unsigned Idx) const inline
Definition at line 350 of file DerivedTypes.h.
References getNumElements(), and Idx.
isLayoutIdentical()
bool StructType::isLayoutIdentical (StructType * Other) const
Return true if this is layout identical to the specified struct.
Definition at line 603 of file Type.cpp.
References elements(), isPacked(), and llvm::Other.
isLiteral()
bool llvm::StructType::isLiteral () const inline
Return true if this type is uniqued by structural equivalence, false if it is a struct definition.
Definition at line 282 of file DerivedTypes.h.
References llvm::Type::getSubclassData().
Referenced by getName().
isOpaque()
bool llvm::StructType::isOpaque () const inline
Return true if this is a type with an identity that has no body specified yet.
These prints as 'opaque' in .ll files.
Definition at line 286 of file DerivedTypes.h.
References llvm::Type::getSubclassData().
Referenced by llvm::IRMover::IdentifiedStructTypeSet::addNonOpaque(), llvm::IRMover::IdentifiedStructTypeSet::addOpaque(), containsScalableVectorType(), llvm::IRMover::IdentifiedStructTypeSet::hasType(), isLeakCheckerRoot(), isSized(), setBody(), and llvm::IRMover::IdentifiedStructTypeSet::switchToNonOpaque().
isPacked()
bool llvm::StructType::isPacked () const inline
Definition at line 278 of file DerivedTypes.h.
References llvm::Type::getSubclassData().
Referenced by llvm::FunctionComparator::cmpTypes(), create(), get(), getTypePartition(), isLayoutIdentical(), and setBody().
isSized()
bool StructType::isSized (SmallPtrSetImpl< Type * > * Visited = nullptr) const
isSized - Return true if this is a sized type.
Definition at line 552 of file Type.cpp.
References containsHomogeneousScalableVectorTypes(), elements(), llvm::Type::getSubclassData(), llvm::SmallPtrSetImpl< PtrType >::insert(), isOpaque(), llvm::Type::isScalableTy(), llvm::Type::isSized(), and llvm::Type::setSubclassData().
isValidElementType()
bool StructType::isValidElementType (Type * ElemTy) static
Return true if the specified type is valid as a element type.
Definition at line 597 of file Type.cpp.
References llvm::Type::isFunctionTy(), llvm::Type::isLabelTy(), llvm::Type::isMetadataTy(), llvm::Type::isTokenTy(), and llvm::Type::isVoidTy().
operator=()
StructType & llvm::StructType::operator= (const StructType &) delete
setBody() [1/2]
void StructType::setBody (ArrayRef< Type * > Elements, bool isPacked = false)
Specify a body for an opaque identified type.
Definition at line 445 of file Type.cpp.
References llvm::LLVMContextImpl::Alloc, assert(), llvm::Type::ContainedTys, llvm::Type::getContext(), llvm::Type::getSubclassData(), isOpaque(), isPacked(), llvm::Type::NumContainedTys, and llvm::Type::setSubclassData().
Referenced by setBody().
setBody() [2/2]
template<typename... Tys> std::enable_if_t< are_base_of< Type, Tys... >::value, void > llvm::StructType::setBody (Type * elt1, Tys *... elts) inline
Definition at line 320 of file DerivedTypes.h.
References assert(), and setBody().
setName()
void StructType::setName (StringRef Name)
Change the name of this type to the specified name, or to a name with a suffix if there is a collision.
Do not call this on an literal type.
Definition at line 462 of file Type.cpp.
References llvm::Type::getContext(), getName(), Name, llvm::LLVMContextImpl::NamedStructTypes, llvm::LLVMContextImpl::NamedStructTypesUniqueID, llvm::XCOFF::NameSize, llvm::LLVMContext::pImpl, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::StringMap< ValueTy, AllocatorTy >::remove(), llvm::SmallVectorImpl< T >::resize(), and llvm::raw_svector_ostream::str().
The documentation for this class was generated from the following files:
include/llvm/IR/DerivedTypes.h
lib/IR/Type.cpp