LLVM: llvm::object::SectionFilter Class Reference
llvm::object::SectionFilter Class Reference
Creates an iterator range of SectionFilterIterators for a given Object and predicate.
#include "llvm/Object/ObjectFile.h"
Public Member Functions
SectionFilter (SectionFilterPredicate Pred, const ObjectFile &Obj)
SectionFilterIterator begin ()
SectionFilterIterator end ()
Detailed Description
Creates an iterator range of SectionFilterIterators for a given Object and predicate.
Definition at line 437 of file ObjectFile.h.
Constructor & Destructor Documentation
SectionFilter()
llvm::object::SectionFilter::SectionFilter (SectionFilterPredicate Pred, const ObjectFile & Obj) inline
Definition at line 439 of file ObjectFile.h.
Member Function Documentation
begin()
SectionFilterIterator llvm::object::SectionFilter::begin () inline
Definition at line 441 of file ObjectFile.h.
References llvm::object::ObjectFile::section_begin(), and llvm::object::ObjectFile::section_end().
end()
SectionFilterIterator llvm::object::SectionFilter::end () inline
Definition at line 445 of file ObjectFile.h.
References llvm::object::ObjectFile::section_end().
The documentation for this class was generated from the following file:
include/llvm/Object/ObjectFile.h