LLVM: llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State > Class Template Reference
llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State > Class Template Reference
#include "llvm/ExecutionEngine/Orc/LLJIT.h"
Public Member Functions
SetterImpl & setLazyCompileFailureAddr (ExecutorAddr Addr)
Set the address in the target address to call if a lazy compile fails.
SetterImpl & setLazyCallthroughManager (std::unique_ptr< LazyCallThroughManager > LCTMgr)
Set the lazy-callthrough manager.
SetterImpl & setIndirectStubsManagerBuilder (LLLazyJITBuilderState::IndirectStubsManagerBuilderFunction ISMBuilder)
Set the IndirectStubsManager builder function.
Public Member Functions inherited from llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >
SetterImpl & setExecutorProcessControl (std::unique_ptr< ExecutorProcessControl > EPC)
Set a ExecutorProcessControl for this instance.
SetterImpl & setExecutionSession (std::unique_ptr< ExecutionSession > ES)
Set an ExecutionSession for this instance.
SetterImpl & setJITTargetMachineBuilder (JITTargetMachineBuilder JTMB)
Set the JITTargetMachineBuilder for this instance.
std::optional< JITTargetMachineBuilder > & getJITTargetMachineBuilder ()
Return a reference to the JITTargetMachineBuilder.
SetterImpl & setDataLayout (std::optional< DataLayout > DL)
Set a DataLayout for this instance.
SetterImpl & setLinkProcessSymbolsByDefault (bool LinkProcessSymbolsByDefault)
The LinkProcessSymbolsDyDefault flag determines whether the "Process" JITDylib will be added to the default link order at LLJIT construction time.
SetterImpl & setProcessSymbolsJITDylibSetup (LLJITBuilderState::ProcessSymbolsJITDylibSetupFunction SetupProcessSymbolsJITDylib)
Set a setup function for the process symbols dylib.
SetterImpl & setObjectLinkingLayerCreator (LLJITBuilderState::ObjectLinkingLayerCreator CreateObjectLinkingLayer)
Set an ObjectLinkingLayer creation function.
SetterImpl & setCompileFunctionCreator (LLJITBuilderState::CompileFunctionCreator CreateCompileFunction)
Set a CompileFunctionCreator.
SetterImpl & setPrePlatformSetup (unique_function< Error(LLJIT &)> PrePlatformSetup)
Set a setup function to be run just before the PlatformSetupFunction is run.
SetterImpl & setPlatformSetUp (LLJITBuilderState::PlatformSetupFunction SetUpPlatform)
Set up an PlatformSetupFunction.
SetterImpl & setNumCompileThreads (unsigned NumCompileThreads)
Set the number of compile threads to use.
SetterImpl & setExecutorProcessControl (ExecutorProcessControl &EPC)
Set an ExecutorProcessControl object.
Expected< std::unique_ptr< JITType > > create ()
Create an instance of the JIT.
Additional Inherited Members
Protected Member Functions inherited from llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >
SetterImpl & impl ()
Detailed Description
template<typename JITType, typename SetterImpl, typename State>
class llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State >
Definition at line 505 of file LLJIT.h.
Member Function Documentation
setIndirectStubsManagerBuilder()
template<typename JITType , typename SetterImpl , typename State > SetterImpl & llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State >::setIndirectStubsManagerBuilder (LLLazyJITBuilderState::IndirectStubsManagerBuilderFunction ISMBuilder) inline
Set the IndirectStubsManager builder function.
If this method is not called then a default, in-process IndirectStubsManager builder for the host platform will be used.
Definition at line 530 of file LLJIT.h.
References llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl().
setLazyCallthroughManager()
template<typename JITType , typename SetterImpl , typename State > SetterImpl & llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State >::setLazyCallthroughManager (std::unique_ptr< LazyCallThroughManager > LCTMgr) inline
Set the lazy-callthrough manager.
If this method is not called then a default, in-process lazy callthrough manager for the host platform will be used.
Definition at line 521 of file LLJIT.h.
References llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl().
setLazyCompileFailureAddr()
template<typename JITType , typename SetterImpl , typename State > SetterImpl & llvm::orc::LLLazyJITBuilderSetters< JITType, SetterImpl, State >::setLazyCompileFailureAddr (ExecutorAddr Addr) inline
Set the address in the target address to call if a lazy compile fails.
If this method is not called then the value will default to 0.
Definition at line 511 of file LLJIT.h.
References Addr, and llvm::orc::LLJITBuilderSetters< JITType, SetterImpl, State >::impl().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/LLJIT.h