LLVM: llvm::GlobalValue Class Reference
llvm::GlobalValue Class Reference
#include "llvm/IR/GlobalValue.h"
Classes
struct SanitizerMetadata
Public Types
enum LinkageTypes {
ExternalLinkage = 0 , AvailableExternallyLinkage , LinkOnceAnyLinkage , LinkOnceODRLinkage ,
WeakAnyLinkage , WeakODRLinkage , AppendingLinkage , InternalLinkage ,
PrivateLinkage , ExternalWeakLinkage , CommonLinkage
}
An enumeration for the kinds of linkage for global values.
enum VisibilityTypes { DefaultVisibility = 0 , HiddenVisibility , ProtectedVisibility }
An enumeration for the kinds of visibility of global values.
enum DLLStorageClassTypes { DefaultStorageClass = 0 , DLLImportStorageClass = 1 , DLLExportStorageClass = 2 }
Storage classes of global values for PE targets.
enum ThreadLocalMode {
NotThreadLocal = 0 , GeneralDynamicTLSModel , LocalDynamicTLSModel , InitialExecTLSModel ,
LocalExecTLSModel
}
enum class UnnamedAddr { None , Local , Global }
using GUID = uint64_t
Declare a type to represent a global unique identifier for a global value.
Public Types inherited from llvm::User
using op_iterator = Use *
using const_op_iterator = const Use *
using op_range = iterator_range< op_iterator >
using const_op_range = iterator_range< const_op_iterator >
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl< Use >
using const_use_iterator = use_iterator_impl< const Use >
using user_iterator = user_iterator_impl< User >
using const_user_iterator = user_iterator_impl< const User >
Public Member Functions
GlobalValue (const GlobalValue &)=delete
unsigned getAddressSpace () const
bool hasGlobalUnnamedAddr () const
bool hasAtLeastLocalUnnamedAddr () const
Returns true if this value's address is not significant in this module.
UnnamedAddr getUnnamedAddr () const
void setUnnamedAddr (UnnamedAddr Val)
bool hasComdat () const
const Comdat * getComdat () const
Comdat * getComdat ()
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
void setVisibility (VisibilityTypes V)
bool isThreadLocal () const
If the value is "Thread Local", its value isn't shared by the threads.
void setThreadLocal (bool Val)
void setThreadLocalMode (ThreadLocalMode Val)
ThreadLocalMode getThreadLocalMode () const
DLLStorageClassTypes getDLLStorageClass () const
bool hasDLLImportStorageClass () const
bool hasDLLExportStorageClass () const
void setDLLStorageClass (DLLStorageClassTypes C)
bool hasSection () const
StringRef getSection () const
PointerType * getType () const
Global values are always pointers.
Type * getValueType () const
bool isImplicitDSOLocal () const
void setDSOLocal (bool Local)
bool isDSOLocal () const
bool hasPartition () const
StringRef getPartition () const
void setPartition (StringRef Part)
bool hasSanitizerMetadata () const
const SanitizerMetadata & getSanitizerMetadata () const
void setSanitizerMetadata (SanitizerMetadata Meta)
void removeSanitizerMetadata ()
bool isTagged () const
bool isDefinitionExact () const
Return true if the currently visible definition of this global (if any) is exactly the definition we will see at runtime.
bool hasExactDefinition () const
Return true if this global has an exact defintion.
bool isInterposable () const
Return true if this global's definition can be substituted with an arbitrary definition at link time or load time.
bool canBenefitFromLocalAlias () const
bool hasExternalLinkage () const
bool hasAvailableExternallyLinkage () const
bool hasLinkOnceLinkage () const
bool hasLinkOnceAnyLinkage () const
bool hasLinkOnceODRLinkage () const
bool hasWeakLinkage () const
bool hasWeakAnyLinkage () const
bool hasWeakODRLinkage () const
bool hasAppendingLinkage () const
bool hasInternalLinkage () const
bool hasPrivateLinkage () const
bool hasLocalLinkage () const
bool hasExternalWeakLinkage () const
bool hasCommonLinkage () const
bool hasValidDeclarationLinkage () const
void setLinkage (LinkageTypes LT)
LinkageTypes getLinkage () const
bool isDiscardableIfUnused () const
bool isWeakForLinker () const
std::string getGlobalIdentifier () const
Return the modified name for this global value suitable to be used as the key for a global lookup (e.g.
GUID getGUID () const
Return a 64-bit global unique ID constructed from global value name (i.e.
bool isDeclaration () const
Return true if the primary definition of this global value is outside of the current translation unit.
bool isDeclarationForLinker () const
bool isStrongDefinitionForLinker () const
Returns true if this global's definition will be the one chosen by the linker.
const GlobalObject * getAliaseeObject () const
GlobalObject * getAliaseeObject ()
bool isAbsoluteSymbolRef () const
Returns whether this is a reference to an absolute symbol.
std::optional< ConstantRange > getAbsoluteSymbolRange () const
If this is an absolute symbol reference, returns the range of the symbol, otherwise returns std::nullopt.
void removeFromParent ()
This method unlinks 'this' from the containing module, but does not delete it.
void eraseFromParent ()
This method unlinks 'this' from the containing module and deletes it.
Module * getParent ()
Get the module that this global value is contained inside of...
const Module * getParent () const
bool canBeOmittedFromSymbolTable () const
True if GV can be left out of the object symbol table.
Materialization
Materialization is used to construct functions only as they're needed.
This is useful to reduce memory usage in LLVM or parsing work done by the BitcodeReader to load the Module.
bool isMaterializable () const
If this function's Module is being lazily streamed in functions from disk or some other source, this method can be used to check to see if the function has been read in yet or not.
Error materialize ()
Make sure this GlobalValue is fully read.
Public Member Functions inherited from llvm::Constant
void operator= (const Constant &)=delete
Constant (const Constant &)=delete
bool isNullValue () const
Return true if this is the value that would be returned by getNullValue.
bool isOneValue () const
Returns true if the value is one.
bool isNotOneValue () const
Return true if the value is not the one value, or, for vectors, does not contain one value elements.
bool isAllOnesValue () const
Return true if this is the value that would be returned by getAllOnesValue.
bool isNegativeZeroValue () const
Return true if the value is what would be returned by getZeroValueForNegation.
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value, or, for vectors, does not contain smallest signed value elements.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool isFiniteNonZeroFP () const
Return true if this is a finite and non-zero floating-point scalar constant or a fixed width vector constant with all finite and non-zero elements.
bool isNormalFP () const
Return true if this is a normal (as opposed to denormal, infinity, nan, or zero) floating-point scalar constant or a vector constant with all normal elements.
bool hasExactInverseFP () const
Return true if this scalar has an exact multiplicative inverse or this vector has an exact multiplicative inverse for each element in the vector.
bool isNaN () const
Return true if this is a floating-point NaN constant or a vector floating-point constant with all NaN elements.
bool isElementWiseEqual (Value *Y) const
Return true if this constant and a constant 'Y' are element-wise equal.
bool containsUndefOrPoisonElement () const
Return true if this is a vector constant that includes any undef or poison elements.
bool containsPoisonElement () const
Return true if this is a vector constant that includes any poison elements.
bool containsUndefElement () const
Return true if this is a vector constant that includes any strictly undef (not poison) elements.
bool containsConstantExpression () const
Return true if this is a fixed width vector constant that includes any constant expressions.
bool isThreadDependent () const
Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
Return true if the constant has users other than constant expressions and other dangling things.
bool needsRelocation () const
This method classifies the entry according to whether or not it may generate a relocation entry (either static or dynamic).
bool needsDynamicRelocation () const
Constant * getAggregateElement (unsigned Elt) const
For aggregates (struct/array/vector) return the constant that corresponds to the specified element if possible, or null if not.
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue (bool AllowUndefs=false) const
If all elements of the vector constant have the same value, return that value.
const APInt & getUniqueInteger () const
If C is a constant integer then return its value, otherwise C must be a vector of constant integers, all equal, and the common value is returned.
void destroyConstant ()
Called if some element of this constant is no longer valid.
void handleOperandChange (Value *, Value *)
This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants.
void removeDeadConstantUsers () const
If there are any dead constant users dangling off of this constant, remove them.
bool hasOneLiveUse () const
Return true if the constant has exactly one live use.
bool hasZeroLiveUses () const
Return true if the constant has no live uses.
const Constant * stripPointerCasts () const
Constant * stripPointerCasts ()
bool isManifestConstant () const
Return true if a constant is ConstantData or a ConstantAggregate or ConstantExpr that contain only ConstantData.
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
bool replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
User * getUniqueUndroppableUser ()
Return true if there is exactly one unique user of this value that cannot be dropped (that user can have multiple uses of this value).
const User * getUniqueUndroppableUser () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, bool AllowInvariantGroup=false)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
std::optional< int64_t > getPointerOffsetFrom (const Value *Other, const DataLayout &DL) const
If this ptr is provably equal to Other plus a constant offset, return that offset in bytes.
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static UnnamedAddr getMinUnnamedAddr (UnnamedAddr A, UnnamedAddr B)
static LinkageTypes getLinkOnceLinkage (bool ODR)
static LinkageTypes getWeakLinkage (bool ODR)
static bool isExternalLinkage (LinkageTypes Linkage)
static bool isAvailableExternallyLinkage (LinkageTypes Linkage)
static bool isLinkOnceAnyLinkage (LinkageTypes Linkage)
static bool isLinkOnceODRLinkage (LinkageTypes Linkage)
static bool isLinkOnceLinkage (LinkageTypes Linkage)
static bool isWeakAnyLinkage (LinkageTypes Linkage)
static bool isWeakODRLinkage (LinkageTypes Linkage)
static bool isWeakLinkage (LinkageTypes Linkage)
static bool isAppendingLinkage (LinkageTypes Linkage)
static bool isInternalLinkage (LinkageTypes Linkage)
static bool isPrivateLinkage (LinkageTypes Linkage)
static bool isLocalLinkage (LinkageTypes Linkage)
static bool isExternalWeakLinkage (LinkageTypes Linkage)
static bool isCommonLinkage (LinkageTypes Linkage)
static bool isValidDeclarationLinkage (LinkageTypes Linkage)
static bool isInterposableLinkage (LinkageTypes Linkage)
Whether the definition of this global may be replaced by something non-equivalent at link time.
static bool isDiscardableIfUnused (LinkageTypes Linkage)
Whether the definition of this global may be discarded if it is not used in its compilation unit.
static bool isWeakForLinker (LinkageTypes Linkage)
Whether the definition of this global may be replaced at link time.
static StringRef dropLLVMManglingEscape (StringRef Name)
If the given string begins with the GlobalValue name mangling escape character '\1', drop it.
static std::string getGlobalIdentifier (StringRef Name, GlobalValue::LinkageTypes Linkage, StringRef FileName)
Return the modified name for a global value suitable to be used as the key for a global lookup (e.g.
static GUID getGUID (StringRef GlobalName)
Return a 64-bit global unique ID constructed from global value name (i.e.
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
Constructor to create a '0' constant of arbitrary type.
static Constant * getAllOnesValue (Type *Ty)
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Return the value for an integer or pointer constant, or a vector thereof, with the given scalar value.
static Constant * replaceUndefsWith (Constant *C, Constant *Replacement)
Try to replace undefined constant C or undefined elements in C with Replacement.
static Constant * mergeUndefsWith (Constant *C, Constant *Other)
Merges undefs of a Constant with another Constant, along with the undefs already present.
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Member Functions
GlobalValue (Type *Ty, ValueTy VTy, Use *Ops, unsigned NumOps, LinkageTypes Linkage, const Twine &Name, unsigned AddressSpace)
unsigned getGlobalValueSubClassData () const
void setGlobalValueSubClassData (unsigned V)
void setParent (Module *parent)
~GlobalValue ()
void copyAttributesFrom (const GlobalValue *Src)
Copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
~Constant ()=default
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void eraseMetadataIf (function_ref< bool(unsigned, MDNode *)> Pred)
Erase all metadata attachments matching the given predicate.
void clearMetadata ()
Erase all metadata attached to this Value.
MDNode * getMetadataImpl (unsigned KindID) const
Get metadata for the given kind, if any.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Protected Attributes
Type * ValueType
unsigned Linkage: 4
unsigned Visibility: 2
unsigned UnnamedAddrVal: 2
unsigned DllStorageClass: 2
unsigned ThreadLocal: 3
unsigned HasLLVMReservedName: 1
True if the function's name starts with "llvm.".
unsigned IsDSOLocal: 1
If true then there is a definition within the same linkage unit and that definition cannot be runtime preempted.
unsigned HasPartition: 1
True if this symbol has a partition name assigned (see https://lld.llvm.org/Partitions.html).
unsigned HasSanitizerMetadata: 1
True if this symbol has sanitizer metadata available.
Intrinsic::ID IntID = (Intrinsic::ID)0U
The intrinsic ID for this subclass (which must be a Function).
Module * Parent = nullptr
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Static Protected Attributes
static const unsigned GlobalValueSubClassDataBits = 15
Friends
class Constant
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static constexpr unsigned MaxAlignmentExponent = 32
The maximum alignment for instructions.
static constexpr uint64_t MaximumAlignment = 1ULL << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Detailed Description
Definition at line 48 of file GlobalValue.h.
Member Typedef Documentation
GUID
using llvm::GlobalValue::GUID = uint64_t
Declare a type to represent a global unique identifier for a global value.
This is a 64 bits hash that is used by PGO and ThinLTO to have a compact unique way to identify a symbol.
Definition at line 586 of file GlobalValue.h.
Member Enumeration Documentation
DLLStorageClassTypes
enum llvm::GlobalValue::DLLStorageClassTypes
Storage classes of global values for PE targets.
Enumerator
DefaultStorageClass
DLLImportStorageClass
Function to be imported from DLL.
DLLExportStorageClass
Function to be accessible from DLL.
Definition at line 73 of file GlobalValue.h.
LinkageTypes
enum llvm::GlobalValue::LinkageTypes
An enumeration for the kinds of linkage for global values.
Enumerator
ExternalLinkage
Externally visible function.
AvailableExternallyLinkage
Available for inspection, not emission.
LinkOnceAnyLinkage
Keep one copy of function when linking (inline)
LinkOnceODRLinkage
Same, but only replaced by something equivalent.
WeakAnyLinkage
Keep one copy of named function when linking (weak)
WeakODRLinkage
Same, but only replaced by something equivalent.
AppendingLinkage
Special purpose, only applies to global arrays.
InternalLinkage
Rename collisions when linking (static functions).
PrivateLinkage
Like Internal, but omit from symbol table.
ExternalWeakLinkage
ExternalWeak linkage description.
CommonLinkage
Tentative definitions.
Definition at line 51 of file GlobalValue.h.
ThreadLocalMode
enum llvm::GlobalValue::ThreadLocalMode
Enumerator
NotThreadLocal
GeneralDynamicTLSModel
LocalDynamicTLSModel
InitialExecTLSModel
LocalExecTLSModel
Definition at line 195 of file GlobalValue.h.
UnnamedAddr
enum class llvm::GlobalValue::UnnamedAddr strong
Enumerator
None
Local
Global
Definition at line 209 of file GlobalValue.h.
VisibilityTypes
enum llvm::GlobalValue::VisibilityTypes
An enumeration for the kinds of visibility of global values.
Enumerator
DefaultVisibility
The GV is visible.
HiddenVisibility
The GV is hidden.
ProtectedVisibility
The GV is protected.
Definition at line 66 of file GlobalValue.h.
Constructor & Destructor Documentation
GlobalValue() [1/2]
llvm::GlobalValue::GlobalValue (Type * Ty, ValueTy VTy, Use * Ops, unsigned NumOps, LinkageTypes Linkage, const Twine & Name, unsigned AddressSpace) inline protected
Definition at line 80 of file GlobalValue.h.
References Linkage, Name, setLinkage(), and llvm::Value::setName().
~GlobalValue()
llvm::GlobalValue::~GlobalValue () inline protected
Definition at line 190 of file GlobalValue.h.
References llvm::Constant::removeDeadConstantUsers().
GlobalValue() [2/2]
llvm::GlobalValue::GlobalValue (const GlobalValue &) delete
Member Function Documentation
canBenefitFromLocalAlias()
bool GlobalValue::canBenefitFromLocalAlias () const
Definition at line 107 of file Globals.cpp.
References llvm::CallingConv::C, getComdat(), getLinkage(), hasDefaultVisibility(), isDeclaration(), isExternalLinkage(), and llvm::Comdat::NoDeduplicate.
Referenced by llvm::AsmPrinter::getSymbolPreferLocal().
canBeOmittedFromSymbolTable()
bool GlobalValue::canBeOmittedFromSymbolTable () const
True if GV can be left out of the object symbol table.
This is the case for linkonce_odr values whose address is not significant. While legal, it is not normally profitable to omit them from the .o symbol table. Using this analysis makes sense when the information can be passed down to the linker or we are in LTO.
Definition at line 393 of file Globals.cpp.
References hasAtLeastLocalUnnamedAddr(), hasGlobalUnnamedAddr(), and hasLinkOnceODRLinkage().
Referenced by llvm::buildModuleSummaryIndex(), canBeHidden(), and llvm::thinLTOFinalizeInModule().
classof()
static bool llvm::GlobalValue::classof (const Value * V) inline static
Definition at line 659 of file GlobalValue.h.
copyAttributesFrom()
void GlobalValue::copyAttributesFrom (const GlobalValue * Src) protected
Copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
copyAttributesFrom - copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
Definition at line 61 of file Globals.cpp.
References removeSanitizerMetadata(), setDLLStorageClass(), setDSOLocal(), setPartition(), setSanitizerMetadata(), setThreadLocalMode(), setUnnamedAddr(), and setVisibility().
Referenced by llvm::GlobalAlias::copyAttributesFrom(), and llvm::GlobalObject::copyAttributesFrom().
dropLLVMManglingEscape()
static StringRef llvm::GlobalValue::dropLLVMManglingEscape (StringRef Name) inline static
If the given string begins with the GlobalValue name mangling escape character '\1', drop it.
This function applies a specific mangling that is used in PGO profiles, among other things. If you're trying to get a symbol name for an arbitrary GlobalValue, this is not the function you're looking for; see Mangler.h.
Definition at line 566 of file GlobalValue.h.
References Name.
Referenced by llvm::DwarfUnit::addLinkageName(), llvm::DiagnosticInfoOptimizationBase::Argument::Argument(), llvm::WinException::beginFunction(), getMCSymbolForMBB(), recoverFramePointer(), llvm::lto::LTO::run(), and sanitizeFunctionName().
eraseFromParent()
void GlobalValue::eraseFromParent ()
This method unlinks 'this' from the containing module and deletes it.
Definition at line 86 of file Globals.cpp.
References llvm::Value::getValueID(), and llvm_unreachable.
Referenced by deleteIfDead(), and llvm::GlobalDCEPass::run().
getAbsoluteSymbolRange()
std::optional< ConstantRange > GlobalValue::getAbsoluteSymbolRange () const
If this is an absolute symbol reference, returns the range of the symbol, otherwise returns std::nullopt.
Definition at line 381 of file Globals.cpp.
References llvm::getConstantRangeFromMetadata().
Referenced by llvm::X86Subtarget::classifyGlobalReference(), and llvm::AMDGPUMachineFunction::getLDSAbsoluteAddress().
getAddressSpace()
unsigned llvm::GlobalValue::getAddressSpace () const inline
Definition at line 205 of file GlobalValue.h.
References llvm::PointerType::getAddressSpace(), and getType().
Referenced by addCallTargetOperands(), llvm::AMDGPUMachineFunction::allocateLDSGlobal(), llvm::convertToDeclaration(), llvm::GlobalAlias::create(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::AMDGPUMachineFunction::getLDSAbsoluteAddress(), llvm::VETargetLowering::getPICJumpTableRelocBase(), llvm::SelectionDAG::getSymbolFunctionGlobalAddress(), isDSAddress(), llvm::AMDGPU::isGlobalSegment(), llvm::AMDGPU::isGroupSegment(), llvm::AMDGPU::isReadOnlySegment(), processInternalGlobal(), removeFromUsedList(), llvm::SITargetLowering::shouldEmitFixup(), llvm::SITargetLowering::shouldEmitGOTReloc(), and SRAGlobal().
getAliaseeObject() [1/2]
GlobalObject * llvm::GlobalValue::getAliaseeObject () inline
Definition at line 635 of file GlobalValue.h.
References getAliaseeObject().
getAliaseeObject() [2/2]
const GlobalObject * GlobalValue::getAliaseeObject () const
Definition at line 368 of file Globals.cpp.
References findBaseObject().
Referenced by getAliaseeObject(), getComdat(), getGVPartitioningRoot(), llvm::Mangler::getNameWithPrefix(), llvm::TargetLoweringObjectFileMachO::getNameWithPrefix(), getSection(), getSelectionForCOFF(), llvm::ModuleSymbolTable::getSymbolFlags(), llvm::FunctionImporter::importFunctions(), llvm::TargetMachine::isLargeGlobalValue(), llvm::HexagonTargetLowering::LowerGLOBALADDRESS(), llvm::LanaiTargetLowering::LowerGlobalAddress(), and llvm::thinLTOFinalizeInModule().
getComdat() [1/2]
Comdat * llvm::GlobalValue::getComdat () inline
Definition at line 243 of file GlobalValue.h.
References getComdat().
getComdat() [2/2]
const Comdat * GlobalValue::getComdat () const
Definition at line 184 of file Globals.cpp.
References getAliaseeObject(), and getComdat().
Referenced by canBenefitFromLocalAlias(), checkMachOComdat(), deleteIfDead(), getComdat(), getComdatGVForCOFF(), getELFComdat(), getSelectionForCOFF(), getWasmComdat(), handleNonPrevailingComdat(), hasComdat(), isInPartition(), optimizeGlobalsInModule(), and llvm::GlobalDCEPass::run().
getDLLStorageClass()
DLLStorageClassTypes llvm::GlobalValue::getDLLStorageClass () const inline
Definition at line 275 of file GlobalValue.h.
References DllStorageClass.
Referenced by getEncodedDLLStorageClass(), and llvm::dxil::DXILBitcodeWriter::getEncodedDLLStorageClass().
getGlobalIdentifier() [1/2]
std::string GlobalValue::getGlobalIdentifier () const
Return the modified name for this global value suitable to be used as the key for a global lookup (e.g.
profile or ThinLTO).
Definition at line 169 of file Globals.cpp.
References getGlobalIdentifier(), getLinkage(), llvm::Value::getName(), and getParent().
Referenced by findValueInfoForFunc(), getGlobalIdentifier(), getGUID(), llvm::getIRPGONameForGlobalObject(), and llvm::thinLTOInternalizeModule().
getGlobalIdentifier() [2/2]
std::string GlobalValue::getGlobalIdentifier (StringRef Name, GlobalValue::LinkageTypes Linkage, StringRef FileName) static
Return the modified name for a global value suitable to be used as the key for a global lookup (e.g.
profile or ThinLTO). The value's original name is Name and has linkage of type Linkage. The value is defined in module FileName.
Definition at line 144 of file Globals.cpp.
References llvm::StringRef::empty(), isLocalLinkage(), llvm::kGlobalIdentifierDelimiter, Linkage, and Name.
getGlobalValueSubClassData()
unsigned llvm::GlobalValue::getGlobalValueSubClassData () const inline protected
Definition at line 175 of file GlobalValue.h.
Referenced by llvm::GlobalObject::getAlign(), llvm::GlobalVariable::getCodeModelRaw(), llvm::GlobalObject::getGlobalObjectSubClassData(), llvm::GlobalObject::hasSection(), llvm::GlobalObject::setAlignment(), llvm::GlobalVariable::setCodeModel(), and llvm::GlobalObject::setGlobalObjectSubClassData().
getGUID() [1/2]
GUID llvm::GlobalValue::getGUID () const inline
Return a 64-bit global unique ID constructed from global value name (i.e.
returned by getGlobalIdentifier()).
Definition at line 594 of file GlobalValue.h.
References getGlobalIdentifier(), and getGUID().
Referenced by llvm::ModuleSummaryIndex::addGlobalValueSummary(), addIntrinsicToSummary(), llvm::PseudoProbeHandler::emitPseudoProbe(), findValueInfoForFunc(), llvm::PseudoProbeManager::getDesc(), getGUID(), llvm::memprof::IndexedMemProfRecord::getGUID(), llvm::ModuleSummaryIndex::getOrInsertTypeIdSummary(), llvm::sampleprof::getRepInFormat(), llvm::ModuleSummaryIndex::getTypeIdSummary(), llvm::SampleProfileProber::instrumentOneFunc(), llvm::sampleprof::SampleProfileReaderExtBinaryBase::readFuncProfiles(), readMemprof(), llvm::lto::LTO::run(), setLiveRoot(), and llvm::thinLTOInternalizeModule().
getGUID() [2/2]
static GUID llvm::GlobalValue::getGUID (StringRef GlobalName) inline static
Return a 64-bit global unique ID constructed from global value name (i.e.
returned by getGlobalIdentifier()).
Definition at line 590 of file GlobalValue.h.
References llvm::sampleprof::MD5Hash().
Referenced by llvm::buildModuleSummaryIndex(), computeAliasSummary(), llvm::ModuleSummaryIndex::getGlobalValueSummary(), llvm::ModuleSummaryIndex::getOrInsertValueInfo(), llvm::FunctionImporter::importFunctions(), llvm::thinLTOFinalizeInModule(), and llvm::updateVCallVisibilityInModule().
getLinkage()
LinkageTypes llvm::GlobalValue::getLinkage () const inline
Definition at line 545 of file GlobalValue.h.
References Linkage.
Referenced by canBenefitFromLocalAlias(), llvm::orc::cloneGlobalAliasDecl(), llvm::orc::cloneGlobalVariableDecl(), copyLinkageVisibility(), llvm::GlobalAlias::create(), llvm::AsmPrinter::emitLinkage(), getEncodedLinkage(), llvm::dxil::DXILBitcodeWriter::getEncodedLinkage(), getFuncAddrForProfData(), getGlobalIdentifier(), llvm::getIRPGOObjectName(), llvm::TargetLoweringObjectFileXCOFF::getStorageClassForGlobal(), getTOCEntryTypeForMO(), hasAppendingLinkage(), hasAvailableExternallyLinkage(), hasCommonLinkage(), hasExternalLinkage(), hasExternalWeakLinkage(), hasInternalLinkage(), hasLinkOnceAnyLinkage(), hasLinkOnceLinkage(), hasLinkOnceODRLinkage(), hasLocalLinkage(), hasPrivateLinkage(), hasValidDeclarationLinkage(), hasWeakAnyLinkage(), hasWeakLinkage(), hasWeakODRLinkage(), isDiscardableIfUnused(), isInterposable(), isWeakForLinker(), makeVisible(), OptimizeGlobalAliases(), processInternalGlobal(), llvm::OpenMPIRBuilder::registerTargetGlobalVariable(), removeGlobalCtors(), replaceAliasWithAliasee(), llvm::thinLTOFinalizeInModule(), and llvm::UpgradeGlobalVariable().
getLinkOnceLinkage()
static LinkageTypes llvm::GlobalValue::getLinkOnceLinkage (bool ODR) inline static
Definition at line 368 of file GlobalValue.h.
References LinkOnceAnyLinkage, and LinkOnceODRLinkage.
getMinUnnamedAddr()
static UnnamedAddr llvm::GlobalValue::getMinUnnamedAddr (UnnamedAddr A, UnnamedAddr B) inline static
Definition at line 233 of file GlobalValue.h.
References A, B, Global, Local, and None.
getParent() [1/2]
Module * llvm::GlobalValue::getParent () inline
Get the module that this global value is contained inside of...
Definition at line 655 of file GlobalValue.h.
References Parent.
Referenced by AddAlignmentAssumptions(), addBoundsChecking(), llvm::SITargetLowering::allocateHSAUserSGPRs(), allocateHSAUserSGPRs(), llvm::SITargetLowering::allocateSpecialInputSGPRs(), llvm::AMDGPUTargetLowering::analyzeFormalArgumentsCompute(), llvm::Value::assertModuleIsMaterializedImpl(), buildDebugInfoForNoopResumeDestroyFunc(), llvm::SPIRVGlobalRegistry::buildGlobalVariable(), buildOverlapMapAndRecordDeclares(), buildUMulWithOverflowFunc(), calculateCXXStateNumbers(), llvm::calculateSEHStateNumbers(), llvm::calculateWinCXXEHStateNumbers(), callIntrinsic(), llvm::M68kSubtarget::classifyGlobalFunctionReference(), llvm::X86Subtarget::classifyGlobalFunctionReference(), llvm::AArch64Subtarget::classifyGlobalFunctionReference(), llvm::M68kSubtarget::classifyGlobalReference(), llvm::X86Subtarget::classifyGlobalReference(), llvm::AArch64Subtarget::ClassifyGlobalReference(), llvm::CloneAndPruneIntoFromInst(), llvm::CloneFunctionInto(), llvm::FunctionComparator::cmpTypes(), CompareValueComplexity(), llvm::RandomIRBuilder::connectToSink(), llvm::ConstantFoldBinaryInstruction(), llvm::MIRPrinter::convertMachineMetadataNodes(), llvm::convertToDeclaration(), llvm::GlobalAlias::create(), llvm::IRBuilderBase::CreateAssumption(), createCloneDeclaration(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemCpy(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemMove(), llvm::IRBuilderBase::CreateElementUnorderedAtomicMemSet(), llvm::IRBuilderBase::CreateFAddReduce(), createFFSIntrinsic(), llvm::IRBuilderBase::CreateFMulReduce(), llvm::IRBuilderBase::CreateFree(), llvm::IRBuilderBase::CreateGCGetPointerBase(), llvm::IRBuilderBase::CreateGCGetPointerOffset(), llvm::IRBuilderBase::CreateGCRelocate(), llvm::IRBuilderBase::CreateGCResult(), CreateGCStatepointCallCommon(), CreateGCStatepointInvokeCommon(), llvm::IRBuilderBase::CreateGlobalString(), llvm::IRBuilderBase::CreateInvariantStart(), llvm::IRBuilderBase::createIsFPClass(), llvm::IRBuilderBase::CreateLaunderInvariantGroup(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::IRBuilderBase::CreateMalloc(), llvm::createMemCpyLoopKnownSize(), llvm::IRBuilderBase::CreateMemSet(), llvm::IRBuilderBase::CreateMemSetInline(), llvm::IRBuilderBase::CreateMemTransferInst(), llvm::OpenMPIRBuilder::createOffloadEntry(), createPopcntIntrinsic(), llvm::IRBuilderBase::CreatePreserveArrayAccessIndex(), llvm::IRBuilderBase::CreatePreserveStructAccessIndex(), llvm::IRBuilderBase::CreatePreserveUnionAccessIndex(), llvm::IRBuilderBase::CreateStripInvariantGroup(), llvm::OpenMPIRBuilder::createTargetInit(), llvm::IRBuilderBase::CreateVectorReverse(), llvm::IRBuilderBase::CreateVectorSplice(), llvm::IRBuilderBase::CreateVScale(), llvm::DependenceInfo::depends(), llvm::AsmPrinter::emitAlignment(), llvm::AArch64TargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), llvm::ARMTargetLowering::emitAtomicCmpXchgNoStoreLLBalance(), llvm::AsmPrinter::emitGlobalVariable(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::emitLinkerFlagsForGlobalCOFF(), llvm::AArch64TargetLowering::emitLoadLinked(), llvm::ARMTargetLowering::emitLoadLinked(), llvm::HexagonTargetLowering::emitLoadLinked(), llvm::PPCTargetLowering::emitMaskedAtomicCmpXchgIntrinsic(), llvm::PPCTargetLowering::emitMaskedAtomicRMWIntrinsic(), llvm::AsmPrinter::emitSpecialLLVMGlobal(), llvm::AsmPrinter::emitStackUsage(), llvm::AArch64TargetLowering::emitStoreConditional(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::HexagonTargetLowering::emitStoreConditional(), llvm::PPCTargetLowering::emitTrailingFence(), llvm::Function::eraseFromParent(), llvm::GlobalAlias::eraseFromParent(), llvm::GlobalIFunc::eraseFromParent(), llvm::GlobalVariable::eraseFromParent(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::CodeExtractor::extractCodeRegion(), llvm::findAllNVVMAnnotation(), llvm::CodeExtractor::findAllocas(), llvm::findDevirtualizableCallsForTypeTest(), llvm::findOneNVVMAnnotation(), llvm::RandomIRBuilder::findOrCreateSource(), fixupDebugInfoPostExtraction(), forceRenaming(), llvm::JITSymbolFlags::fromGlobalValue(), getAlign(), llvm::IRPosition::getAssociatedFunction(), getComdatGVForCOFF(), llvm::getConstantDataArrayInfo(), llvm::ScalarEvolution::getDataLayout(), llvm::MachineIRBuilder::getDataLayout(), llvm::MachineFunction::getDataLayout(), getDefaultInlineAdvice(), llvm::TargetLoweringBase::getDefaultSafeStackPointerLocation(), getELFSectionNameForGlobal(), getGlobalIdentifier(), llvm::TargetLoweringBase::getIRStackGuard(), llvm::X86TargetLowering::getIRStackGuard(), getKernelArgAttribute(), llvm::TargetLibraryInfoImpl::getLibFunc(), llvm::getLiveRegMap(), getLoadStackGuard(), llvm::ExecutionEngine::getMangledName(), llvm::DPValue::getModule(), llvm::Trace::getModule(), llvm::BasicBlock::getModule(), llvm::Mangler::getNameWithPrefix(), getNVPTXMDNode(), getParent(), llvm::TargetLoweringBase::getSafeStackPointerLocation(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), llvm::LoopVectorizationCostModel::getSmallestAndWidestTypes(), llvm::DependenceInfo::getSplitIteration(), llvm::getStrippedSourceFileName(), llvm::SelectionDAG::getSymbolFunctionGlobalAddress(), llvm::AsmPrinter::getSymbolPreferLocal(), GetSymbolRef(), llvm::TargetLoweringObjectFile::getSymbolWithGlobalValueBase(), llvm::TargetMachine::getTLSModel(), llvm::FunctionLoweringInfo::getValueFromVirtualReg(), hasReturnsTwiceAttr(), llvm::inferAlignFromPtrInfo(), llvm::SelectionDAGBuilder::init(), llvm::MIRParserImpl::initializeConstantPool(), insertCall(), insertSinCosCall(), insertSpills(), llvm::ScalarEvolution::isBasicBlockEntryGuardedByCond(), llvm::AMDGPU::isDynamicLDS(), llvm::HexagonTargetObjectFile::isGlobalInSmallSection(), llvm::RISCVELFTargetObjectFile::isGlobalInSmallSection(), llvm::ARMSubtarget::isGVIndirectSymbol(), llvm::PPCSubtarget::isGVIndirectSymbol(), llvm::ARMSubtarget::isGVInGOT(), llvm::isImageReadOnly(), llvm::isImageReadWrite(), llvm::isImageWriteOnly(), isInterposable(), llvm::TargetLowering::isOffsetFoldingLegal(), llvm::SystemZSubtarget::isPC32DBLSymbol(), isPointerValueDeadOnEntryToFunction(), llvm::isSampler(), IsSmallObject(), llvm::AMDGPULegalizerInfo::legalizeTrapHsaQueuePtr(), LLVMGetNextGlobal(), LLVMGetNextGlobalAlias(), LLVMGetNextGlobalIFunc(), LLVMGetPreviousGlobal(), LLVMGetPreviousGlobalAlias(), LLVMGetPreviousGlobalIFunc(), llvm::LoongArchTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::AsmPrinter::lowerConstant(), llvm::TargetLowering::LowerToTLSEmulatedModel(), llvm::SparcTargetLowering::makeAddress(), llvm::ARMTargetLowering::makeDMB(), llvm::X86TargetLowering::markLibCallAttributes(), materialize(), llvm::InsertFunctionStrategy::mutate(), OptimizeGlobalAddressOfAllocation(), parseGlobalValue(), parseIRConstant(), performGlobalAddressCombine(), llvm::Value::print(), llvm::Function::print(), printMemOperand(), processInternalGlobal(), llvm::ReadByteArrayFromGlobal(), llvm::Function::removeFromParent(), llvm::GlobalAlias::removeFromParent(), llvm::GlobalIFunc::removeFromParent(), llvm::GlobalVariable::removeFromParent(), removeGlobalCtors(), llvm::RemoveRedundantDbgInstrs(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::LoopConstrainer::run(), llvm::JumpThreadingPass::runImpl(), llvm::ConstantHoistingPass::runImpl(), llvm::StackProtector::runOnFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), selectExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::FunctionLoweringInfo::set(), setCoroInfo(), llvm::setGlobalVariableLargeSection(), llvm::SITargetLowering::shouldEmitGOTReloc(), splitGlobal(), SRAGlobal(), llvm::PPCTargetLowering::supportsTailCallFor(), SwitchToLookupTable(), transformCallee(), llvm::tryPromoteCall(), TryToShrinkGlobalToBoolean(), updateIDTMetaData(), updateNVPTXMetadata(), UseTlsOffset(), useTpOffset(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
getParent() [2/2]
const Module * llvm::GlobalValue::getParent () const inline
Definition at line 656 of file GlobalValue.h.
References Parent.
getPartition()
StringRef GlobalValue::getPartition () const
Definition at line 205 of file Globals.cpp.
References llvm::Value::getContext(), llvm::LLVMContextImpl::GlobalValuePartitions, hasPartition(), and llvm::LLVMContext::pImpl.
getSanitizerMetadata()
const SanitizerMetadata & GlobalValue::getSanitizerMetadata () const
Definition at line 228 of file Globals.cpp.
References assert(), llvm::Value::getContext(), llvm::LLVMContextImpl::GlobalValueSanitizerMetadata, hasSanitizerMetadata(), and llvm::LLVMContext::pImpl.
Referenced by isTagged().
getSection()
StringRef GlobalValue::getSection () const
Definition at line 174 of file Globals.cpp.
References getAliaseeObject().
Referenced by callsShareTOCBase(), and hasSection().
getThreadLocalMode()
ThreadLocalMode llvm::GlobalValue::getThreadLocalMode () const inline
Definition at line 271 of file GlobalValue.h.
References ThreadLocal.
Referenced by llvm::orc::cloneGlobalVariableDecl(), llvm::convertToDeclaration(), getEncodedThreadLocalMode(), llvm::dxil::DXILBitcodeWriter::getEncodedThreadLocalMode(), getSelectedTLSModel(), isThreadLocal(), OptimizeGlobalAddressOfAllocation(), processInternalGlobal(), removeFromUsedList(), removeGlobalCtors(), SRAGlobal(), and TryToShrinkGlobalToBoolean().
getType()
PointerType * llvm::GlobalValue::getType () const inline
Global values are always pointers.
Definition at line 294 of file GlobalValue.h.
References llvm::Value::getType().
Referenced by llvm::MachineIRBuilder::buildGlobalValue(), canDemoteGlobalVar(), classifyGlobalCtorPointerType(), llvm::orc::cloneGlobalAliasDecl(), llvm::orc::cloneGlobalVariableDecl(), llvm::convertToDeclaration(), llvm::OpenMPIRBuilder::createTargetInit(), llvm::ExecutionEngine::emitGlobals(), llvm::AsmPrinter::emitGlobalVariable(), llvm::GlobalAddressSDNode::getAddressSpace(), getAddressSpace(), llvm::Function::getContext(), llvm::SelectionDAG::getGlobalAddress(), getTLIFunction(), llvm::SelectionDAG::InferPtrAlign(), llvm::IsConstantOffsetFromGlobal(), llvm::AMDGPU::isDynamicLDS(), llvm::AMDGPU::isLDSVariableToLower(), isUnmergeableGlobal(), llvm::Attributor::isValidFunctionSignatureRewrite(), processInternalGlobal(), llvm::GlobalAlias::setAliasee(), setCoroInfo(), splitGlobal(), and TryToShrinkGlobalToBoolean().
getUnnamedAddr()
UnnamedAddr llvm::GlobalValue::getUnnamedAddr () const inline
Definition at line 228 of file GlobalValue.h.
References UnnamedAddrVal.
Referenced by getEncodedUnnamedAddr(), hasAtLeastLocalUnnamedAddr(), hasGlobalUnnamedAddr(), and processGlobal().
getValueType()
Type * llvm::GlobalValue::getValueType () const inline
Definition at line 296 of file GlobalValue.h.
References ValueType.
Referenced by addEmuTlsVar(), llvm::AMDGPUMachineFunction::allocateLDSGlobal(), llvm::AArch64Subtarget::classifyGlobalFunctionReference(), llvm::AArch64Subtarget::ClassifyGlobalReference(), llvm::orc::cloneGlobalAliasDecl(), llvm::orc::cloneGlobalVariableDecl(), llvm::convertToDeclaration(), llvm::GlobalAlias::create(), llvm::IRBuilderBase::CreateGlobalStringPtr(), llvm::AsmPrinter::emitGlobalVariable(), llvm::ExecutionEngine::emitGlobalVariable(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::emitLinkerFlagsForGlobalCOFF(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), llvm::AMDGPU::getAlign(), llvm::getConstantDataArrayInfo(), llvm::DataLayout::getPreferredAlign(), hasTocDataAttr(), llvm::AMDGPU::isDynamicLDS(), isFunctionGlobalAddress(), llvm::HexagonTargetObjectFile::isGlobalInSmallSection(), llvm::RISCVELFTargetObjectFile::isGlobalInSmallSection(), isLeakCheckerRoot(), llvm::SystemZSubtarget::isPC32DBLSymbol(), IsSmallObject(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), OptimizeGlobalAddressOfAllocation(), performGlobalAddressCombine(), processInternalGlobal(), llvm::OpenMPIRBuilder::registerTargetGlobalVariable(), removeFromUsedList(), llvm::dxil::ResourceBase::ResourceBase(), runIPSCCP(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), llvm::AMDGPUMachineFunction::setDynLDSAlign(), llvm::GlobalVariable::setInitializer(), llvm::dxil::ConstantBuffer::setSize(), shouldConvertToRelLookupTable(), llvm::SITargetLowering::shouldEmitGOTReloc(), SRAGlobal(), llvm::SCCPInstVisitor::trackValueOfGlobalVariable(), TryToShrinkGlobalToBoolean(), llvm::UpgradeGlobalVariable(), and llvm::ObjectSizeOffsetVisitor::visitGlobalVariable().
getVisibility()
VisibilityTypes llvm::GlobalValue::getVisibility () const inline
Definition at line 248 of file GlobalValue.h.
References Visibility.
Referenced by copyLinkageVisibility(), llvm::AsmPrinter::emitGlobalVariable(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), getEncodedVisibility(), llvm::dxil::DXILBitcodeWriter::getEncodedVisibility(), replaceAliasWithAliasee(), and shouldUsePublicSymbol().
getWeakLinkage()
static LinkageTypes llvm::GlobalValue::getWeakLinkage (bool ODR) inline static
Definition at line 371 of file GlobalValue.h.
References WeakAnyLinkage, and WeakODRLinkage.
Referenced by thinLTOResolvePrevailingGUID().
hasAppendingLinkage()
bool llvm::GlobalValue::hasAppendingLinkage () const inline
Definition at line 524 of file GlobalValue.h.
References getLinkage(), and isAppendingLinkage().
Referenced by llvm::ExecutionEngine::emitGlobals(), llvm::AsmPrinter::emitSpecialLLVMGlobal(), and isSpecialLLVMGlobalArrayToSkip().
hasAtLeastLocalUnnamedAddr()
bool llvm::GlobalValue::hasAtLeastLocalUnnamedAddr () const inline
Returns true if this value's address is not significant in this module.
This attribute is intended to be used only by the code generator and LTO to allow the linker to decide whether the global needs to be in the symbol table. It should probably not be used in optimizations, as the value may have uses outside the module; use hasGlobalUnnamedAddr() instead.
Definition at line 224 of file GlobalValue.h.
References getUnnamedAddr(), and None.
Referenced by canBeOmittedFromSymbolTable().
hasAvailableExternallyLinkage()
bool llvm::GlobalValue::hasAvailableExternallyLinkage () const inline
Definition at line 511 of file GlobalValue.h.
References getLinkage(), and isAvailableExternallyLinkage().
Referenced by llvm::AsmPrinter::emitSpecialLLVMGlobal(), isDeclarationForLinker(), llvm::Function::isDefTriviallyDead(), llvm::LanaiTargetObjectFile::isGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), and llvm::thinLTOFinalizeInModule().
hasComdat()
bool llvm::GlobalValue::hasComdat () const inline
Definition at line 241 of file GlobalValue.h.
References getComdat().
Referenced by callsShareTOCBase(), and llvm::AsmPrinter::emitLinkage().
hasCommonLinkage()
bool llvm::GlobalValue::hasCommonLinkage () const inline
Definition at line 531 of file GlobalValue.h.
References getLinkage(), and isCommonLinkage().
Referenced by llvm::X86Subtarget::classifyLocalReference(), llvm::AsmPrinter::emitGlobalVariable(), llvm::JITSymbolFlags::fromGlobalValue(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), hasTocDataAttr(), llvm::RISCVELFTargetObjectFile::isGlobalInSmallSection(), llvm::ARMSubtarget::isGVIndirectSymbol(), llvm::TargetLoweringObjectFileXCOFF::SelectSectionForGlobal(), and llvm::HexagonTargetObjectFile::SelectSectionForGlobal().
hasDefaultVisibility()
bool llvm::GlobalValue::hasDefaultVisibility () const inline
Definition at line 249 of file GlobalValue.h.
References DefaultVisibility, and Visibility.
Referenced by canBenefitFromLocalAlias(), inferDSOLocal(), and isImplicitDSOLocal().
hasDLLExportStorageClass()
bool llvm::GlobalValue::hasDLLExportStorageClass () const inline
Definition at line 281 of file GlobalValue.h.
References DLLExportStorageClass, and DllStorageClass.
Referenced by llvm::emitLinkerFlagsForGlobalCOFF().
hasDLLImportStorageClass()
bool llvm::GlobalValue::hasDLLImportStorageClass () const inline
Definition at line 278 of file GlobalValue.h.
References DLLImportStorageClass, and DllStorageClass.
Referenced by llvm::X86Subtarget::classifyGlobalFunctionReference(), llvm::AArch64Subtarget::classifyGlobalFunctionReference(), llvm::X86Subtarget::classifyGlobalReference(), llvm::AArch64Subtarget::ClassifyGlobalReference(), llvm::ARMBaseInstrInfo::expandLoadStackGuardBase(), isFunction(), and llvm::TargetMachine::shouldAssumeDSOLocal().
hasExactDefinition()
bool llvm::GlobalValue::hasExactDefinition () const inline
Return true if this global has an exact defintion.
Definition at line 494 of file GlobalValue.h.
References isDeclaration(), and isDefinitionExact().
hasExternalLinkage()
bool llvm::GlobalValue::hasExternalLinkage () const inline
Definition at line 510 of file GlobalValue.h.
References getLinkage(), and isExternalLinkage().
Referenced by llvm::AArch64Subtarget::classifyGlobalFunctionReference(), llvm::ExecutionEngine::emitGlobals(), llvm::RecordStreamer::flushSymverDirectives(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::AArch64MCInstLower::GetGlobalValueSymbol(), llvm::AMDGPU::isDynamicLDS(), llvm::RISCVELFTargetObjectFile::isGlobalInSmallSection(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::HexagonTargetObjectFile::SelectSectionForGlobal(), and llvm::SITargetLowering::shouldUseLDSConstAddress().
hasExternalWeakLinkage()
bool llvm::GlobalValue::hasExternalWeakLinkage () const inline
Definition at line 528 of file GlobalValue.h.
References getLinkage(), and isExternalWeakLinkage().
Referenced by llvm::AArch64Subtarget::ClassifyGlobalReference(), llvm::ExecutionEngine::emitGlobals(), inferDSOLocal(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), isImplicitDSOLocal(), llvm::TargetMachine::shouldAssumeDSOLocal(), and llvm::ObjectSizeOffsetVisitor::visitGlobalVariable().
hasGlobalUnnamedAddr()
bool llvm::GlobalValue::hasGlobalUnnamedAddr () const inline
Definition at line 215 of file GlobalValue.h.
References getUnnamedAddr(), and Global.
Referenced by canBeOmittedFromSymbolTable(), isGOTEquivalentCandidate(), makeMergeable(), and processGlobal().
hasHiddenVisibility()
bool llvm::GlobalValue::hasHiddenVisibility () const inline
Definition at line 250 of file GlobalValue.h.
References HiddenVisibility, and Visibility.
Referenced by llvm::emitLinkerFlagsForGlobalCOFF(), and llvm::JITSymbolFlags::fromGlobalValue().
hasInternalLinkage()
bool llvm::GlobalValue::hasInternalLinkage () const inline
Definition at line 525 of file GlobalValue.h.
References getLinkage(), and isInternalLinkage().
Referenced by llvm::AArch64Subtarget::classifyGlobalFunctionReference(), getADAEntry(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), and llvm::HexagonTargetObjectFile::SelectSectionForGlobal().
hasLinkOnceAnyLinkage()
bool llvm::GlobalValue::hasLinkOnceAnyLinkage () const inline
Definition at line 515 of file GlobalValue.h.
References getLinkage(), and isLinkOnceAnyLinkage().
hasLinkOnceLinkage()
bool llvm::GlobalValue::hasLinkOnceLinkage () const inline
Definition at line 514 of file GlobalValue.h.
References getLinkage(), and isLinkOnceLinkage().
Referenced by llvm::JITSymbolFlags::fromGlobalValue(), llvm::Function::isDefTriviallyDead(), and makeVisible().
hasLinkOnceODRLinkage()
bool llvm::GlobalValue::hasLinkOnceODRLinkage () const inline
Definition at line 518 of file GlobalValue.h.
References getLinkage(), and isLinkOnceODRLinkage().
Referenced by canBeOmittedFromSymbolTable().
hasLocalLinkage()
bool llvm::GlobalValue::hasLocalLinkage () const inline
Definition at line 527 of file GlobalValue.h.
References getLinkage(), and isLocalLinkage().
Referenced by canDemoteGlobalVar(), llvm::canTrackGlobalVariableInterprocedurally(), llvm::Attributor::checkForAllCallSites(), deleteIfDead(), llvm::ExecutionEngine::emitGlobals(), externalize(), llvm::RecordStreamer::flushSymverDirectives(), forceRenaming(), llvm::JITSymbolFlags::fromGlobalValue(), llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::getIndirectSymViaGOTPCRel(), llvm::GlobalsAAResult::getModRefInfo(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::SparcELFTargetObjectFile::getTTypeGlobalReference(), hasOnlyColdCalls(), hasTocDataAttr(), inferDSOLocal(), llvm::Function::isDefTriviallyDead(), llvm::HexagonTargetObjectFile::isGlobalInSmallSection(), isImplicitDSOLocal(), isNonRenamableLocal(), makeVisible(), mayHaveOtherReferences(), OptimizeGlobalVars(), processGlobal(), replace(), llvm::X86AsmPrinter::runOnMachineFunction(), runPartiallyInlineLibCalls(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), llvm::HexagonTargetObjectFile::SelectSectionForGlobal(), llvm::XCoreTargetObjectFile::SelectSectionForGlobal(), setDLLStorageClass(), setVisibility(), shouldConvertToRelLookupTable(), llvm::Attributor::shouldUpdateAA(), shouldUsePublicSymbol(), splitGlobal(), SRAGlobal(), and upgradeDLLImportExportLinkage().
hasPartition()
bool llvm::GlobalValue::hasPartition () const inline
Definition at line 309 of file GlobalValue.h.
References HasPartition.
Referenced by getPartition(), and setPartition().
hasPrivateLinkage()
bool llvm::GlobalValue::hasPrivateLinkage () const inline
Definition at line 526 of file GlobalValue.h.
References getLinkage(), and isPrivateLinkage().
Referenced by getADAEntry(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::HexagonTargetObjectFile::getExplicitSectionGlobal(), llvm::Mangler::getNameWithPrefix(), llvm::TargetMachine::getNameWithPrefix(), llvm::TargetLoweringObjectFileCOFF::getNameWithPrefix(), hasTocDataAttr(), isLeakCheckerRoot(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), and llvm::HexagonTargetObjectFile::SelectSectionForGlobal().
hasProtectedVisibility()
bool llvm::GlobalValue::hasProtectedVisibility () const inline
Definition at line 251 of file GlobalValue.h.
References ProtectedVisibility, and Visibility.
hasSanitizerMetadata()
bool llvm::GlobalValue::hasSanitizerMetadata () const inline
Definition at line 355 of file GlobalValue.h.
References HasSanitizerMetadata.
Referenced by getSanitizerMetadata(), and isTagged().
hasSection()
bool llvm::GlobalValue::hasSection () const inline
Definition at line 290 of file GlobalValue.h.
References llvm::StringRef::empty(), and getSection().
Referenced by isNonRenamableLocal().
hasValidDeclarationLinkage()
bool llvm::GlobalValue::hasValidDeclarationLinkage () const inline
Definition at line 532 of file GlobalValue.h.
References getLinkage(), and isValidDeclarationLinkage().
hasWeakAnyLinkage()
bool llvm::GlobalValue::hasWeakAnyLinkage () const inline
Definition at line 522 of file GlobalValue.h.
References getLinkage(), and isWeakAnyLinkage().
hasWeakLinkage()
bool llvm::GlobalValue::hasWeakLinkage () const inline
Definition at line 521 of file GlobalValue.h.
References getLinkage(), and isWeakLinkage().
Referenced by llvm::JITSymbolFlags::fromGlobalValue().
hasWeakODRLinkage()
bool llvm::GlobalValue::hasWeakODRLinkage () const inline
Definition at line 523 of file GlobalValue.h.
References getLinkage(), and isWeakODRLinkage().
isAbsoluteSymbolRef()
bool GlobalValue::isAbsoluteSymbolRef () const
Returns whether this is a reference to an absolute symbol.
Definition at line 373 of file Globals.cpp.
isAppendingLinkage()
static bool llvm::GlobalValue::isAppendingLinkage (LinkageTypes Linkage) inline static
Definition at line 399 of file GlobalValue.h.
References AppendingLinkage, and Linkage.
Referenced by hasAppendingLinkage(), and thinLTOResolvePrevailingGUID().
isAvailableExternallyLinkage()
static bool llvm::GlobalValue::isAvailableExternallyLinkage (LinkageTypes Linkage) inline static
Definition at line 378 of file GlobalValue.h.
References AvailableExternallyLinkage, and Linkage.
Referenced by calculatePrevailingSummary(), hasAvailableExternallyLinkage(), isDiscardableIfUnused(), llvm::GlobalAlias::isValidLinkage(), and llvm::thinLTOFinalizeInModule().
isCommonLinkage()
static bool llvm::GlobalValue::isCommonLinkage (LinkageTypes Linkage) inline static
Definition at line 414 of file GlobalValue.h.
References CommonLinkage, and Linkage.
Referenced by llvm::JITSymbolFlags::fromSummary(), and hasCommonLinkage().
isDeclaration()
bool GlobalValue::isDeclaration () const
Return true if the primary definition of this global value is outside of the current translation unit.
Definition at line 274 of file Globals.cpp.
References assert(), and F.
Referenced by assureFPCallStub(), llvm::buildModuleSummaryIndex(), canBenefitFromLocalAlias(), llvm::Attributor::checkForAllInstructions(), llvm::CloneFunctionInto(), cxxDtorIsEmpty(), deleteIfDead(), llvm::ExecutionEngine::emitGlobals(), llvm::AsmPrinter::emitGlobalVariable(), llvm::AMDGPUAsmPrinter::emitGlobalVariable(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::emitLinkerFlagsForGlobalCOFF(), llvm::ExecutionEngine::FindGlobalVariableNamed(), hasExactDefinition(), llvm::GlobalVariable::hasInitializer(), llvm::InlineFunction(), isDeclarationForLinker(), llvm::LanaiTargetObjectFile::isGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), llvm::RISCVELFTargetObjectFile::isGlobalInSmallSection(), isPotentiallyReachable(), isReportingError(), llvm::SPIRVCallLowering::lowerCall(), OptimizeGlobalVars(), llvm::InlineCostAnnotationPrinterPass::run(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), llvm::Function::stealArgumentListFrom(), llvm::stripDebugifyMetadata(), and llvm::thinLTOFinalizeInModule().
isDeclarationForLinker()
bool llvm::GlobalValue::isDeclarationForLinker () const inline
Definition at line 617 of file GlobalValue.h.
References hasAvailableExternallyLinkage(), and isDeclaration().
Referenced by llvm::X86Subtarget::classifyLocalReference(), llvm::AsmPrinter::emitXXStructorList(), llvm::RecordStreamer::flushSymverDirectives(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::TargetLoweringObjectFileXCOFF::getSectionForExternalReference(), llvm::ARMSubtarget::isGVIndirectSymbol(), isStrongDefinitionForLinker(), llvm::TargetMachine::shouldAssumeDSOLocal(), and shouldUsePublicSymbol().
isDefinitionExact()
bool llvm::GlobalValue::isDefinitionExact () const inline
Return true if the currently visible definition of this global (if any) is exactly the definition we will see at runtime.
Non-exact linkage types inhibits most non-inlining IPO, since a differently optimized variant of the same function can have different observable or undefined behavior than in the variant currently visible. For instance, we could have started with
void foo(int *v) { int t = 5 / v[0]; (void) t; }
and "refined" it to
void foo(int *v) { }
However, we cannot infer readnone for foo, since that would justify DSE'ing a store to v[0] across a call to foo, which can cause undefined behavior if the linker replaces the actual call destination with the unoptimized foo.
Inlining is okay across non-exact linkage types as long as they're not interposable (see isInterposable), since in such cases the currently visible variant is a correct implementation of the original source function; it just isn't the only correct implementation.
Definition at line 489 of file GlobalValue.h.
Referenced by hasExactDefinition().
isDiscardableIfUnused() [1/2]
bool llvm::GlobalValue::isDiscardableIfUnused () const inline
Definition at line 547 of file GlobalValue.h.
References getLinkage(), and isDiscardableIfUnused().
Referenced by llvm::canRenameComdatFunc(), and isDiscardableIfUnused().
isDiscardableIfUnused() [2/2]
static bool llvm::GlobalValue::isDiscardableIfUnused (LinkageTypes Linkage) inline static
Whether the definition of this global may be discarded if it is not used in its compilation unit.
Definition at line 448 of file GlobalValue.h.
References isAvailableExternallyLinkage(), isLinkOnceLinkage(), isLocalLinkage(), and Linkage.
Referenced by deleteIfDead(), isGOTEquivalentCandidate(), makeVisible(), and optimizeGlobalsInModule().
isDSOLocal()
bool llvm::GlobalValue::isDSOLocal () const inline
Definition at line 305 of file GlobalValue.h.
References IsDSOLocal.
Referenced by llvm::buildModuleSummaryIndex(), llvm::GlobalObject::canIncreaseAlignment(), copyLinkageVisibility(), llvm::AsmPrinter::getSymbolPreferLocal(), isInterposable(), OptimizeGlobalAliases(), PrintDSOLocation(), llvm::TargetMachine::shouldAssumeDSOLocal(), and shouldConvertToRelLookupTable().
isExternalLinkage()
static bool llvm::GlobalValue::isExternalLinkage (LinkageTypes Linkage) inline static
Definition at line 375 of file GlobalValue.h.
References ExternalLinkage, and Linkage.
Referenced by calculatePrevailingSummary(), canBenefitFromLocalAlias(), llvm::JITSymbolFlags::fromSummary(), hasExternalLinkage(), isValidDeclarationLinkage(), llvm::GlobalAlias::isValidLinkage(), llvm::GlobalIFunc::isValidLinkage(), and thinLTOInternalizeAndPromoteGUID().
isExternalWeakLinkage()
static bool llvm::GlobalValue::isExternalWeakLinkage (LinkageTypes Linkage) inline static
Definition at line 411 of file GlobalValue.h.
References ExternalWeakLinkage, and Linkage.
Referenced by llvm::JITSymbolFlags::fromSummary(), hasExternalWeakLinkage(), isValidDeclarationLinkage(), and thinLTOInternalizeAndPromoteGUID().
isImplicitDSOLocal()
bool llvm::GlobalValue::isImplicitDSOLocal () const inline
Definition at line 298 of file GlobalValue.h.
References hasDefaultVisibility(), hasExternalWeakLinkage(), and hasLocalLinkage().
Referenced by llvm::convertToDeclaration(), OptimizeGlobalAliases(), PrintDSOLocation(), setLinkage(), setVisibility(), and shouldConvertToRelLookupTable().
isInternalLinkage()
static bool llvm::GlobalValue::isInternalLinkage (LinkageTypes Linkage) inline static
Definition at line 402 of file GlobalValue.h.
References InternalLinkage, and Linkage.
Referenced by CompareValueComplexity(), hasInternalLinkage(), and isLocalLinkage().
isInterposable()
bool GlobalValue::isInterposable () const
Return true if this global's definition can be substituted with an arbitrary definition at link time or load time.
We cannot do any IPO or inlining across interposable call edges, since the callee can be replaced with something arbitrary.
Definition at line 100 of file Globals.cpp.
References getLinkage(), getParent(), llvm::Module::getSemanticInterposition(), isDSOLocal(), and isInterposableLinkage().
Referenced by llvm::GlobalVariable::hasDefinitiveInitializer(), llvm::ObjectSizeOffsetVisitor::visitGlobalAlias(), and llvm::ObjectSizeOffsetVisitor::visitGlobalVariable().
isInterposableLinkage()
static bool llvm::GlobalValue::isInterposableLinkage (LinkageTypes Linkage) inline static
Whether the definition of this global may be replaced by something non-equivalent at link time.
For example, if a function has weak linkage then the code defining it may be replaced by different code.
Definition at line 424 of file GlobalValue.h.
References AppendingLinkage, AvailableExternallyLinkage, CommonLinkage, ExternalLinkage, ExternalWeakLinkage, InternalLinkage, Linkage, LinkOnceAnyLinkage, LinkOnceODRLinkage, llvm_unreachable, PrivateLinkage, WeakAnyLinkage, and WeakODRLinkage.
Referenced by llvm::ModuleSummaryIndex::canImportGlobalVar(), llvm::computeDeadSymbolsAndUpdateIndirectCalls(), llvm::Attributor::isInternalizable(), isInterposable(), OptimizeGlobalAliases(), qualifyCalleeCandidates(), runAttributorOnFunctions(), and llvm::thinLTOFinalizeInModule().
isLinkOnceAnyLinkage()
static bool llvm::GlobalValue::isLinkOnceAnyLinkage (LinkageTypes Linkage) inline static
Definition at line 381 of file GlobalValue.h.
References Linkage, and LinkOnceAnyLinkage.
Referenced by calculatePrevailingSummary(), hasLinkOnceAnyLinkage(), and isLinkOnceLinkage().
isLinkOnceLinkage()
static bool llvm::GlobalValue::isLinkOnceLinkage (LinkageTypes Linkage) inline static
Definition at line 387 of file GlobalValue.h.
References isLinkOnceAnyLinkage(), isLinkOnceODRLinkage(), and Linkage.
Referenced by llvm::JITSymbolFlags::fromSummary(), hasLinkOnceLinkage(), isDiscardableIfUnused(), llvm::GlobalAlias::isValidLinkage(), llvm::GlobalIFunc::isValidLinkage(), and thinLTOResolvePrevailingGUID().
isLinkOnceODRLinkage()
static bool llvm::GlobalValue::isLinkOnceODRLinkage (LinkageTypes Linkage) inline static
Definition at line 384 of file GlobalValue.h.
References Linkage, and LinkOnceODRLinkage.
Referenced by calculatePrevailingSummary(), hasLinkOnceODRLinkage(), isLinkOnceLinkage(), and thinLTOResolvePrevailingGUID().
isLocalLinkage()
static bool llvm::GlobalValue::isLocalLinkage (LinkageTypes Linkage) inline static
Definition at line 408 of file GlobalValue.h.
References isInternalLinkage(), isPrivateLinkage(), and Linkage.
Referenced by calculatePrevailingSummary(), llvm::createPGOFuncNameVar(), doImportingForModuleForTest(), getGlobalIdentifier(), llvm::getPGOFuncName(), llvm::getPGOFuncNameVarName(), hasLocalLinkage(), isDiscardableIfUnused(), isValidDLLStorageClassForLinkage(), llvm::GlobalAlias::isValidLinkage(), llvm::GlobalIFunc::isValidLinkage(), isValidVisibilityForLinkage(), qualifyCalleeCandidates(), setLinkage(), llvm::thinLTOFinalizeInModule(), thinLTOInternalizeAndPromoteGUID(), llvm::thinLTOInternalizeModule(), and thinLTOResolvePrevailingGUID().
isMaterializable()
bool GlobalValue::isMaterializable () const
If this function's Module is being lazily streamed in functions from disk or some other source, this method can be used to check to see if the function has been read in yet or not.
Definition at line 42 of file Globals.cpp.
References F.
isPrivateLinkage()
static bool llvm::GlobalValue::isPrivateLinkage (LinkageTypes Linkage) inline static
Definition at line 405 of file GlobalValue.h.
References Linkage, and PrivateLinkage.
Referenced by CompareValueComplexity(), hasPrivateLinkage(), and isLocalLinkage().
isStrongDefinitionForLinker()
bool llvm::GlobalValue::isStrongDefinitionForLinker () const inline
Returns true if this global's definition will be the one chosen by the linker.
NB! Ideally this should not be used at the IR level at all. If you're interested in optimization constraints implied by the linker's ability to choose an implementation, prefer using hasExactDefinition.
Definition at line 630 of file GlobalValue.h.
References isDeclarationForLinker(), and isWeakForLinker().
Referenced by callsShareTOCBase(), llvm::GlobalObject::canIncreaseAlignment(), llvm::GlobalVariable::hasUniqueInitializer(), and llvm::TargetMachine::shouldAssumeDSOLocal().
isTagged()
bool llvm::GlobalValue::isTagged () const inline
Definition at line 364 of file GlobalValue.h.
References getSanitizerMetadata(), hasSanitizerMetadata(), and llvm::GlobalValue::SanitizerMetadata::Memtag.
Referenced by llvm::AArch64Subtarget::ClassifyGlobalReference(), and llvm::AsmPrinter::emitGlobalVariable().
isThreadLocal()
bool llvm::GlobalValue::isThreadLocal () const inline
If the value is "Thread Local", its value isn't shared by the threads.
Definition at line 263 of file GlobalValue.h.
References getThreadLocalMode(), and NotThreadLocal.
Referenced by llvm::AsmPrinter::emitGlobalVariable(), llvm::ExecutionEngine::emitGlobalVariable(), llvm::WebAssemblyAsmPrinter::emitGlobalVariable(), llvm::SelectionDAG::getGlobalAddress(), llvm::TargetLoweringObjectFileXCOFF::getSectionForExternalReference(), isFunctionGlobalAddress(), and isUnmergeableGlobal().
isValidDeclarationLinkage()
static bool llvm::GlobalValue::isValidDeclarationLinkage (LinkageTypes Linkage) inline static
Definition at line 417 of file GlobalValue.h.
References isExternalLinkage(), isExternalWeakLinkage(), and Linkage.
Referenced by hasValidDeclarationLinkage().
isWeakAnyLinkage()
static bool llvm::GlobalValue::isWeakAnyLinkage (LinkageTypes Linkage) inline static
Definition at line 390 of file GlobalValue.h.
References Linkage, and WeakAnyLinkage.
Referenced by calculatePrevailingSummary(), hasWeakAnyLinkage(), and isWeakLinkage().
isWeakForLinker() [1/2]
bool llvm::GlobalValue::isWeakForLinker () const inline
Definition at line 551 of file GlobalValue.h.
References getLinkage(), and isWeakForLinker().
Referenced by isStrongDefinitionForLinker(), isWeakForLinker(), and thinLTOInternalizeAndPromoteGUID().
isWeakForLinker() [2/2]
static bool llvm::GlobalValue::isWeakForLinker (LinkageTypes Linkage) inline static
Whether the definition of this global may be replaced at link time.
NB: Using this method outside of the code generators is almost always a mistake: when working at the IR level use isInterposable instead as it knows about ODR semantics.
Definition at line 457 of file GlobalValue.h.
References CommonLinkage, ExternalWeakLinkage, Linkage, LinkOnceAnyLinkage, LinkOnceODRLinkage, WeakAnyLinkage, and WeakODRLinkage.
Referenced by llvm::RecordStreamer::flushSymverDirectives(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
isWeakLinkage()
static bool llvm::GlobalValue::isWeakLinkage (LinkageTypes Linkage) inline static
Definition at line 396 of file GlobalValue.h.
References isWeakAnyLinkage(), isWeakODRLinkage(), and Linkage.
Referenced by llvm::JITSymbolFlags::fromSummary(), hasWeakLinkage(), llvm::GlobalAlias::isValidLinkage(), and llvm::GlobalIFunc::isValidLinkage().
isWeakODRLinkage()
static bool llvm::GlobalValue::isWeakODRLinkage (LinkageTypes Linkage) inline static
Definition at line 393 of file GlobalValue.h.
References Linkage, and WeakODRLinkage.
Referenced by calculatePrevailingSummary(), hasWeakODRLinkage(), and isWeakLinkage().
materialize()
Error GlobalValue::materialize ()
Make sure this GlobalValue is fully read.
Definition at line 47 of file Globals.cpp.
References getParent(), and llvm::Module::materialize().
Referenced by llvm::FunctionImporter::importFunctions().
removeFromParent()
void GlobalValue::removeFromParent ()
This method unlinks 'this' from the containing module, but does not delete it.
Definition at line 74 of file Globals.cpp.
References llvm::Value::getValueID(), and llvm_unreachable.
removeSanitizerMetadata()
void GlobalValue::removeSanitizerMetadata ()
Definition at line 239 of file Globals.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::Value::getContext(), llvm::LLVMContextImpl::GlobalValueSanitizerMetadata, HasSanitizerMetadata, and llvm::LLVMContext::pImpl.
Referenced by copyAttributesFrom().
setDLLStorageClass()
void llvm::GlobalValue::setDLLStorageClass (DLLStorageClassTypes C) inline
Definition at line 284 of file GlobalValue.h.
References assert(), llvm::CallingConv::C, DefaultStorageClass, DllStorageClass, and hasLocalLinkage().
Referenced by copyAttributesFrom(), and upgradeDLLImportExportLinkage().
setDSOLocal()
void llvm::GlobalValue::setDSOLocal (bool Local) inline
Definition at line 303 of file GlobalValue.h.
References IsDSOLocal, and Local.
Referenced by llvm::convertToDeclaration(), copyAttributesFrom(), copyLinkageVisibility(), llvm::X86TargetLowering::getIRStackGuard(), getOrCreateFunction(), inferDSOLocal(), llvm::Attributor::internalizeFunctions(), maybeSetDSOLocal(), setLinkage(), and setVisibility().
setGlobalValueSubClassData()
void llvm::GlobalValue::setGlobalValueSubClassData (unsigned V) inline protected
Definition at line 178 of file GlobalValue.h.
References assert(), and GlobalValueSubClassDataBits.
Referenced by llvm::GlobalObject::GlobalObject(), llvm::GlobalObject::setAlignment(), llvm::GlobalVariable::setCodeModel(), and llvm::GlobalObject::setGlobalObjectSubClassData().
setLinkage()
void llvm::GlobalValue::setLinkage (LinkageTypes LT) inline
Definition at line 536 of file GlobalValue.h.
References DefaultStorageClass, DefaultVisibility, DllStorageClass, isImplicitDSOLocal(), isLocalLinkage(), Linkage, setDSOLocal(), and Visibility.
Referenced by llvm::CloneModule(), copyLinkageVisibility(), createProfileFileNameVar(), llvm::createProfileFileNameVar(), externalize(), GlobalValue(), handleNonPrevailingComdat(), llvm::Attributor::internalizeFunctions(), LLVMSetLinkage(), makeVisible(), OptimizeGlobalVars(), llvm::CallGraphUpdater::removeFunction(), replaceAliasWithAliasee(), runImpl(), and llvm::thinLTOFinalizeInModule().
setParent()
void llvm::GlobalValue::setParent (Module * parent) inline protected
Definition at line 186 of file GlobalValue.h.
References Parent.
setPartition()
void GlobalValue::setPartition (StringRef Part)
Definition at line 211 of file Globals.cpp.
References llvm::StringRef::empty(), llvm::Value::getContext(), llvm::LLVMContextImpl::GlobalValuePartitions, HasPartition, hasPartition(), llvm::LLVMContext::pImpl, llvm::UniqueStringSaver::save(), and llvm::LLVMContextImpl::Saver.
Referenced by copyAttributesFrom().
setSanitizerMetadata()
void GlobalValue::setSanitizerMetadata (SanitizerMetadata Meta)
Definition at line 234 of file Globals.cpp.
References llvm::Value::getContext(), llvm::LLVMContextImpl::GlobalValueSanitizerMetadata, HasSanitizerMetadata, and llvm::LLVMContext::pImpl.
Referenced by copyAttributesFrom().
setThreadLocal()
void llvm::GlobalValue::setThreadLocal (bool Val) inline
Definition at line 264 of file GlobalValue.h.
References GeneralDynamicTLSModel, NotThreadLocal, and setThreadLocalMode().
setThreadLocalMode()
void llvm::GlobalValue::setThreadLocalMode (ThreadLocalMode Val) inline
Definition at line 267 of file GlobalValue.h.
References assert(), llvm::Value::getValueID(), NotThreadLocal, and ThreadLocal.
Referenced by copyAttributesFrom(), llvm::GlobalVariable::GlobalVariable(), LLVMSetThreadLocalMode(), and setThreadLocal().
setUnnamedAddr()
void llvm::GlobalValue::setUnnamedAddr (UnnamedAddr Val) inline
Definition at line 231 of file GlobalValue.h.
References UnnamedAddrVal.
Referenced by copyAttributesFrom(), llvm::createPrivateGlobalForString(), createRelLookupTable(), LLVMSetUnnamedAddress(), processGlobal(), and runImpl().
setVisibility()
void llvm::GlobalValue::setVisibility (VisibilityTypes V) inline
Definition at line 254 of file GlobalValue.h.
References assert(), DefaultVisibility, hasLocalLinkage(), isImplicitDSOLocal(), setDSOLocal(), and Visibility.
Referenced by copyAttributesFrom(), copyLinkageVisibility(), llvm::createProfileFileNameVar(), llvm::OpenMPIRBuilder::createTargetInit(), externalize(), llvm::Attributor::internalizeFunctions(), makeVisible(), replaceAliasWithAliasee(), runImpl(), and llvm::thinLTOFinalizeInModule().
Friends And Related Function Documentation
Constant
friend class Constant friend
Definition at line 129 of file GlobalValue.h.
Member Data Documentation
DllStorageClass
unsigned llvm::GlobalValue::DllStorageClass protected
Definition at line 101 of file GlobalValue.h.
Referenced by getDLLStorageClass(), hasDLLExportStorageClass(), hasDLLImportStorageClass(), setDLLStorageClass(), and setLinkage().
GlobalValueSubClassDataBits
const unsigned llvm::GlobalValue::GlobalValueSubClassDataBits = 15 static protected
Definition at line 94 of file GlobalValue.h.
Referenced by setGlobalValueSubClassData().
HasLLVMReservedName
unsigned llvm::GlobalValue::HasLLVMReservedName protected
True if the function's name starts with "llvm.".
This corresponds to the value of Function::isIntrinsic(), which may be true even if Function::intrinsicID() returns Intrinsic::not_intrinsic.
Definition at line 109 of file GlobalValue.h.
Referenced by llvm::Function::updateAfterNameChange().
HasPartition
unsigned llvm::GlobalValue::HasPartition protected
True if this symbol has a partition name assigned (see https://lld.llvm.org/Partitions.html).
Definition at line 117 of file GlobalValue.h.
Referenced by hasPartition(), and setPartition().
HasSanitizerMetadata
unsigned llvm::GlobalValue::HasSanitizerMetadata protected
True if this symbol has sanitizer metadata available.
Should only happen if sanitizers were enabled when building the translation unit which contains this GV.
Definition at line 122 of file GlobalValue.h.
Referenced by hasSanitizerMetadata(), removeSanitizerMetadata(), and setSanitizerMetadata().
IntID
Intrinsic::ID llvm::GlobalValue::IntID = (Intrinsic::ID)0U protected
The intrinsic ID for this subclass (which must be a Function).
This member is defined by this class, but not used for anything. Subclasses can use it to store their intrinsic ID, if they have one.
This is stored here to save space in Function on 64-bit hosts.
Definition at line 173 of file GlobalValue.h.
Referenced by llvm::Function::isTargetIntrinsic(), and llvm::Function::updateAfterNameChange().
IsDSOLocal
unsigned llvm::GlobalValue::IsDSOLocal protected
If true then there is a definition within the same linkage unit and that definition cannot be runtime preempted.
Definition at line 113 of file GlobalValue.h.
Referenced by isDSOLocal(), and setDSOLocal().
Linkage
unsigned llvm::GlobalValue::Linkage protected
Definition at line 98 of file GlobalValue.h.
Referenced by llvm::Function::Create(), llvm::GlobalAlias::create(), llvm::Function::createWithDefaultAttr(), getGlobalIdentifier(), getLinkage(), GlobalValue(), isAppendingLinkage(), isAvailableExternallyLinkage(), isCommonLinkage(), isDiscardableIfUnused(), isExternalLinkage(), isExternalWeakLinkage(), isInternalLinkage(), isInterposableLinkage(), isLinkOnceAnyLinkage(), isLinkOnceLinkage(), isLinkOnceODRLinkage(), isLocalLinkage(), isPrivateLinkage(), isValidDeclarationLinkage(), isWeakAnyLinkage(), isWeakForLinker(), isWeakLinkage(), isWeakODRLinkage(), and setLinkage().
Parent
Module* llvm::GlobalValue::Parent = nullptr protected
Definition at line 183 of file GlobalValue.h.
Referenced by llvm::GlobalObject::canIncreaseAlignment(), llvm::GlobalAlias::create(), getParent(), and setParent().
ThreadLocal
unsigned llvm::GlobalValue::ThreadLocal protected
Definition at line 103 of file GlobalValue.h.
Referenced by getThreadLocalMode(), and setThreadLocalMode().
UnnamedAddrVal
unsigned llvm::GlobalValue::UnnamedAddrVal protected
Definition at line 100 of file GlobalValue.h.
Referenced by getUnnamedAddr(), and setUnnamedAddr().
ValueType
Type* llvm::GlobalValue::ValueType protected
Definition at line 92 of file GlobalValue.h.
Referenced by getValueType().
Visibility
unsigned llvm::GlobalValue::Visibility protected
Definition at line 99 of file GlobalValue.h.
Referenced by getVisibility(), hasDefaultVisibility(), hasHiddenVisibility(), hasProtectedVisibility(), setLinkage(), llvm::GlobalObject::setVCallVisibilityMetadata(), and setVisibility().
The documentation for this class was generated from the following files:
include/llvm/IR/GlobalValue.h
lib/IR/Globals.cpp