LLVM: llvm::MCPseudoProbeSections Class Reference
llvm::MCPseudoProbeSections Class Reference
Instances of this class represent the pseudo probes inserted into a compile unit.
#include "llvm/MC/MCPseudoProbe.h"
Public Types
using MCProbeDivisionMap = std::unordered_map< MCSymbol *, MCPseudoProbeInlineTree >
Public Member Functions
void addPseudoProbe (MCSymbol *FuncSym, const MCPseudoProbe &Probe, const MCPseudoProbeInlineStack &InlineStack)
const MCProbeDivisionMap & getMCProbes () const
bool empty () const
void emit (MCObjectStreamer *MCOS)
Detailed Description
Instances of this class represent the pseudo probes inserted into a compile unit.
Definition at line 295 of file MCPseudoProbe.h.
Member Typedef Documentation
MCProbeDivisionMap
using llvm::MCPseudoProbeSections::MCProbeDivisionMap = std::unordered_map<MCSymbol *, MCPseudoProbeInlineTree>
Definition at line 304 of file MCPseudoProbe.h.
Member Function Documentation
addPseudoProbe()
void llvm::MCPseudoProbeSections::addPseudoProbe (MCSymbol * FuncSym, const MCPseudoProbe & Probe, const MCPseudoProbeInlineStack & InlineStack) inline
Definition at line 297 of file MCPseudoProbe.h.
emit()
void MCPseudoProbeSections::emit (MCObjectStreamer * MCOS)
Definition at line 211 of file MCPseudoProbe.cpp.
References A, B, llvm::Block, llvm::SmallVectorImpl< T >::emplace_back(), llvm::enumerate(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getContext(), llvm::MCContext::getObjectFileInfo(), llvm::MCObjectFileInfo::getPseudoProbeSection(), I, llvm::Invalid, llvm::sampleprof::MD5Hash(), llvm::SmallVectorImpl< T >::reserve(), llvm::Sentinel, llvm::sort(), and llvm::MCStreamer::switchSection().
empty()
bool llvm::MCPseudoProbeSections::empty () const inline
Definition at line 315 of file MCPseudoProbe.h.
getMCProbes()
const MCProbeDivisionMap & llvm::MCPseudoProbeSections::getMCProbes () const inline
Definition at line 313 of file MCPseudoProbe.h.
The documentation for this class was generated from the following files:
include/llvm/MC/MCPseudoProbe.h
lib/MC/MCPseudoProbe.cpp