LLVM: llvm::DWARF5AccelTable Class Reference
llvm::DWARF5AccelTable Class Reference
#include "llvm/CodeGen/AccelTable.h"
Classes
struct UnitIndexAndEncoding
Public Member Functions
const TUVectorTy & getTypeUnitsSymbols ()
Returns type units that were constructed.
void addTypeUnitSymbol (DwarfTypeUnit &U)
Add a type unit start symbol.
void addTypeUnitSignature (DwarfTypeUnit &U)
Add a type unit Signature.
void convertDieToOffset ()
Convert DIE entries to explicit offset.
void addTypeEntries (DWARF5AccelTable &Table)
Public Member Functions inherited from llvm::AccelTable< DWARF5AccelTableData >
AccelTable ()
void addName (DwarfStringPoolEntryRef Name, Types &&... Args)
void clear ()
void addEntries (AccelTable< DWARF5AccelTableData > &Table)
const StringEntries getEntries () const
Public Member Functions inherited from llvm::AccelTableBase
void finalize (AsmPrinter *Asm, StringRef Prefix)
ArrayRef< HashList > getBuckets () const
uint32_t getBucketCount () const
uint32_t getUniqueHashCount () const
uint32_t getUniqueNameCount () const
void print (raw_ostream &OS) const
void dump () const
AccelTableBase (const AccelTableBase &)=delete
void operator= (const AccelTableBase &)=delete
Additional Inherited Members
Public Types inherited from llvm::AccelTableBase
using HashFn = uint32_t(StringRef)
using HashList = std::vector< HashData * >
using BucketList = std::vector< HashList >
Protected Types inherited from llvm::AccelTableBase
using StringEntries = MapVector< StringRef, HashData >
Protected Member Functions inherited from llvm::AccelTableBase
void computeBucketCount ()
AccelTableBase (HashFn *Hash)
Protected Attributes inherited from llvm::AccelTableBase
BumpPtrAllocator Allocator
Allocator for HashData and Values.
StringEntries Entries
HashFn * Hash
uint32_t BucketCount = 0
uint32_t UniqueHashCount = 0
HashList Hashes
BucketList Buckets
Detailed Description
Definition at line 354 of file AccelTable.h.
Member Function Documentation
addTypeEntries()
void llvm::DWARF5AccelTable::addTypeEntries (DWARF5AccelTable & Table) inline
Definition at line 383 of file AccelTable.h.
References llvm::AccelTable< DWARF5AccelTableData >::addName(), llvm::Data, and llvm::AccelTable< DataT >::getEntries().
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
addTypeUnitSignature()
void DWARF5AccelTable::addTypeUnitSignature (DwarfTypeUnit & U)
Add a type unit Signature.
Definition at line 745 of file AccelTable.cpp.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
addTypeUnitSymbol()
void DWARF5AccelTable::addTypeUnitSymbol (DwarfTypeUnit & U)
Add a type unit start symbol.
Definition at line 741 of file AccelTable.cpp.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
convertDieToOffset()
void llvm::DWARF5AccelTable::convertDieToOffset () inline
Convert DIE entries to explicit offset.
Needs to be called after DIE offsets are computed.
Definition at line 371 of file AccelTable.h.
References llvm::Data, and llvm::AccelTableBase::Entries.
Referenced by llvm::DwarfDebug::addDwarfTypeUnitType().
getTypeUnitsSymbols()
const TUVectorTy & llvm::DWARF5AccelTable::getTypeUnitsSymbols () inline
Returns type units that were constructed.
Definition at line 364 of file AccelTable.h.
Referenced by llvm::emitDWARF5AccelTable().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/AccelTable.h
lib/CodeGen/AsmPrinter/AccelTable.cpp