LLVM: llvm::VPBuilder Class Reference
llvm::VPBuilder Class Reference
VPlan-based builder utility analogous to IRBuilder.
#include "Transforms/Vectorize/LoopVectorizationPlanner.h"
Classes
class InsertPointGuard
RAII object that stores the current insertion point and restores it when the object is destroyed.
class VPInsertPoint
InsertPoint - A saved insertion point.
Public Member Functions
VPBuilder ()=default
VPBuilder (VPBasicBlock *InsertBB)
void clearInsertionPoint ()
Clear the insertion point: created instructions will not be inserted into a block.
VPBasicBlock * getInsertBlock () const
VPBasicBlock::iterator getInsertPoint () const
void restoreIP (VPInsertPoint IP)
Sets the current insert point to a previously-saved location.
void setInsertPoint (VPBasicBlock *TheBB)
This specifies that created VPInstructions should be appended to the end of the specified block.
void setInsertPoint (VPBasicBlock *TheBB, VPBasicBlock::iterator IP)
This specifies that created instructions should be inserted at the specified point.
void setInsertPoint (VPRecipeBase *IP)
This specifies that created instructions should be inserted at the specified point.
VPValue * createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, Instruction *Inst=nullptr, const Twine &Name="")
Create an N-ary operation with Opcode, Operands and set Inst as its underlying Instruction.
VPValue * createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, DebugLoc DL, const Twine &Name="")
VPInstruction * createOverflowingOp (unsigned Opcode, std::initializer_list< VPValue * > Operands, VPRecipeWithIRFlags::WrapFlagsTy WrapFlags, DebugLoc DL={}, const Twine &Name="")
VPValue * createNot (VPValue *Operand, DebugLoc DL={}, const Twine &Name="")
VPValue * createAnd (VPValue *LHS, VPValue *RHS, DebugLoc DL={}, const Twine &Name="")
VPValue * createOr (VPValue *LHS, VPValue *RHS, DebugLoc DL={}, const Twine &Name="")
VPValue * createSelect (VPValue *Cond, VPValue *TrueVal, VPValue *FalseVal, DebugLoc DL={}, const Twine &Name="", std::optional< FastMathFlags > FMFs=std::nullopt)
VPValue * createICmp (CmpInst::Predicate Pred, VPValue *A, VPValue *B, DebugLoc DL={}, const Twine &Name="")
Create a new ICmp VPInstruction with predicate Pred and operands A and B.
Detailed Description
VPlan-based builder utility analogous to IRBuilder.
Definition at line 45 of file LoopVectorizationPlanner.h.
Constructor & Destructor Documentation
VPBuilder() [1/2]
llvm::VPBuilder::VPBuilder () default
VPBuilder() [2/2]
llvm::VPBuilder::VPBuilder (VPBasicBlock * InsertBB) inline
Definition at line 70 of file LoopVectorizationPlanner.h.
References setInsertPoint().
Member Function Documentation
clearInsertionPoint()
void llvm::VPBuilder::clearInsertionPoint () inline
Clear the insertion point: created instructions will not be inserted into a block.
Definition at line 74 of file LoopVectorizationPlanner.h.
Referenced by restoreIP().
createAnd()
VPValue * llvm::VPBuilder::createAnd (VPValue * LHS, VPValue * RHS, DebugLoc DL = {}, const Twine & Name = "") inline
Definition at line 160 of file LoopVectorizationPlanner.h.
createICmp()
VPValue * VPBuilder::createICmp (CmpInst::Predicate Pred, VPValue * A, VPValue * B, DebugLoc DL = {}, const Twine & Name = "")
Create a new ICmp VPInstruction with predicate Pred and operands A and B.
TODO: add createFCmp when needed.
Definition at line 7267 of file LoopVectorize.cpp.
References A, assert(), B, DL, llvm::CmpInst::FIRST_ICMP_PREDICATE, llvm::CmpInst::LAST_ICMP_PREDICATE, and Name.
Referenced by llvm::VPRecipeBuilder::createHeaderMask().
createNaryOp() [1/2]
VPValue * llvm::VPBuilder::createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, DebugLoc DL, const Twine & Name = "") inline
Definition at line 143 of file LoopVectorizationPlanner.h.
References DL, Name, and Operands.
createNaryOp() [2/2]
VPValue * llvm::VPBuilder::createNaryOp (unsigned Opcode, ArrayRef< VPValue * > Operands, Instruction * Inst = nullptr, const Twine & Name = "") inline
Create an N-ary operation with Opcode, Operands and set Inst as its underlying Instruction.
Definition at line 134 of file LoopVectorizationPlanner.h.
References DL, Name, Operands, and llvm::VPValue::setUnderlyingValue().
Referenced by addVPLaneMaskPhiAndUpdateExitBranch(), and llvm::VPlanTransforms::adjustFixedOrderRecurrences().
createNot()
VPValue * llvm::VPBuilder::createNot (VPValue * Operand, DebugLoc DL = {}, const Twine & Name = "") inline
Definition at line 155 of file LoopVectorizationPlanner.h.
Referenced by addVPLaneMaskPhiAndUpdateExitBranch(), and llvm::VPRecipeBuilder::createEdgeMask().
createOr()
VPValue * llvm::VPBuilder::createOr (VPValue * LHS, VPValue * RHS, DebugLoc DL = {}, const Twine & Name = "") inline
Definition at line 165 of file LoopVectorizationPlanner.h.
Referenced by llvm::VPRecipeBuilder::createBlockInMask().
createOverflowingOp()
VPInstruction * llvm::VPBuilder::createOverflowingOp (unsigned Opcode, std::initializer_list< VPValue * > Operands, VPRecipeWithIRFlags::WrapFlagsTy WrapFlags, DebugLoc DL = {}, const Twine & Name = "") inline
Definition at line 148 of file LoopVectorizationPlanner.h.
Referenced by addVPLaneMaskPhiAndUpdateExitBranch().
createSelect()
VPValue * llvm::VPBuilder::createSelect (VPValue * Cond, VPValue * TrueVal, VPValue * FalseVal, DebugLoc DL = {}, const Twine & Name = "", std::optional< FastMathFlags > FMFs = std::nullopt) inline
Definition at line 170 of file LoopVectorizationPlanner.h.
Referenced by llvm::VPRecipeBuilder::createEdgeMask().
getInsertBlock()
VPBasicBlock * llvm::VPBuilder::getInsertBlock () const inline
Definition at line 79 of file LoopVectorizationPlanner.h.
getInsertPoint()
VPBasicBlock::iterator llvm::VPBuilder::getInsertPoint () const inline
Definition at line 80 of file LoopVectorizationPlanner.h.
restoreIP()
void llvm::VPBuilder::restoreIP (VPInsertPoint IP) inline
Sets the current insert point to a previously-saved location.
Definition at line 103 of file LoopVectorizationPlanner.h.
References clearInsertionPoint(), llvm::VPBuilder::VPInsertPoint::getBlock(), llvm::VPBuilder::VPInsertPoint::getPoint(), llvm::VPBuilder::VPInsertPoint::isSet(), and setInsertPoint().
Referenced by llvm::VPBuilder::InsertPointGuard::~InsertPointGuard().
setInsertPoint() [1/3]
void llvm::VPBuilder::setInsertPoint (VPBasicBlock * TheBB) inline
This specifies that created VPInstructions should be appended to the end of the specified block.
Definition at line 112 of file LoopVectorizationPlanner.h.
References assert(), and llvm::VPBasicBlock::end().
Referenced by addVPLaneMaskPhiAndUpdateExitBranch(), llvm::VPlanTransforms::adjustFixedOrderRecurrences(), llvm::VPRecipeBuilder::createHeaderMask(), restoreIP(), and VPBuilder().
setInsertPoint() [2/3]
void llvm::VPBuilder::setInsertPoint (VPBasicBlock * TheBB, VPBasicBlock::iterator IP) inline
This specifies that created instructions should be inserted at the specified point.
Definition at line 120 of file LoopVectorizationPlanner.h.
setInsertPoint() [3/3]
void llvm::VPBuilder::setInsertPoint (VPRecipeBase * IP) inline
This specifies that created instructions should be inserted at the specified point.
Definition at line 127 of file LoopVectorizationPlanner.h.
References llvm::ilist_node_impl< OptionsT >::getIterator(), and llvm::VPRecipeBase::getParent().
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/LoopVectorizationPlanner.h
lib/Transforms/Vectorize/LoopVectorize.cpp