LLVM: llvm::HexagonTargetLowering Class Reference
llvm::HexagonTargetLowering Class Reference
#include "Target/Hexagon/HexagonISelLowering.h"
Public Member Functions
HexagonTargetLowering (const TargetMachine &TM, const HexagonSubtarget &ST)
bool IsEligibleForTailCallOptimization (SDValue Callee, CallingConv::ID CalleeCC, bool isVarArg, bool isCalleeStructRet, bool isCallerStructRet, const SmallVectorImpl< ISD::OutputArg > &Outs, const SmallVectorImpl< SDValue > &OutVals, const SmallVectorImpl< ISD::InputArg > &Ins, SelectionDAG &DAG) const
IsEligibleForTailCallOptimization - Check whether the call is eligible for tail call optimization.
bool getTgtMemIntrinsic (IntrinsicInfo &Info, const CallInst &I, MachineFunction &MF, unsigned Intrinsic) const override
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory).
bool isTruncateFree (Type *Ty1, Type *Ty2) const override
Return true if it's free to truncate a value of type FromTy to type ToTy.
bool isTruncateFree (EVT VT1, EVT VT2) const override
bool isCheapToSpeculateCttz (Type *) const override
Return true if it is cheap to speculate a call to intrinsic cttz.
bool isCheapToSpeculateCtlz (Type *) const override
Return true if it is cheap to speculate a call to intrinsic ctlz.
bool isCtlzFast () const override
Return true if ctlz instruction is fast.
bool hasBitTest (SDValue X, SDValue Y) const override
Return true if the target has a bit-test instruction: (X & (1 << Y)) ==/!= 0 This knowledge can be used to prevent breaking the pattern, or creating it if it could be recognized.
bool allowTruncateForTailCall (Type *Ty1, Type *Ty2) const override
Return true if a truncation from FromTy to ToTy is permitted when deciding whether a call is in tail position.
bool isFMAFasterThanFMulAndFAdd (const MachineFunction &, EVT) const override
Return true if an FMA operation is faster than a pair of mul and add instructions.
bool shouldExpandBuildVectorWithShuffles (EVT VT, unsigned DefinedValues) const override
bool isExtractSubvectorCheap (EVT ResVT, EVT SrcVT, unsigned Index) const override
Return true if EXTRACT_SUBVECTOR is cheap for extracting this result type from this source type with this index.
bool isTargetCanonicalConstantNode (SDValue Op) const override
Returns true if the given Opc is considered a canonical constant for the target, which should not be transformed back into a BUILD_VECTOR.
bool isShuffleMaskLegal (ArrayRef< int > Mask, EVT VT) const override
Targets can use this to indicate that they only support some VECTOR_SHUFFLE operations, those with specific masks.
LegalizeTypeAction getPreferredVectorAction (MVT VT) const override
Return the preferred vector type legalization action.
LegalizeAction getCustomOperationAction (SDNode &Op) const override
How to legalize this custom operation?
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
void LowerOperationWrapper (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const override
This callback is invoked by the type legalizer to legalize nodes with an illegal operand type but legal result types.
void ReplaceNodeResults (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const override
This callback is invoked when a node result type is illegal for the target, and the operation was registered to use 'custom' lowering for that result type.
const char * getTargetNodeName (unsigned Opcode) const override
This method returns the name of a target specific DAG node.
SDValue LowerBUILD_VECTOR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerCONCAT_VECTORS (SDValue Op, SelectionDAG &DAG) const
SDValue LowerEXTRACT_VECTOR_ELT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerEXTRACT_SUBVECTOR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerINSERT_VECTOR_ELT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerINSERT_SUBVECTOR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerVECTOR_SHUFFLE (SDValue Op, SelectionDAG &DAG) const
SDValue LowerVECTOR_SHIFT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerROTL (SDValue Op, SelectionDAG &DAG) const
SDValue LowerBITCAST (SDValue Op, SelectionDAG &DAG) const
SDValue LowerANY_EXTEND (SDValue Op, SelectionDAG &DAG) const
SDValue LowerSIGN_EXTEND (SDValue Op, SelectionDAG &DAG) const
SDValue LowerZERO_EXTEND (SDValue Op, SelectionDAG &DAG) const
SDValue LowerLoad (SDValue Op, SelectionDAG &DAG) const
SDValue LowerStore (SDValue Op, SelectionDAG &DAG) const
SDValue LowerUnalignedLoad (SDValue Op, SelectionDAG &DAG) const
SDValue LowerUAddSubO (SDValue Op, SelectionDAG &DAG) const
SDValue LowerUAddSubOCarry (SDValue Op, SelectionDAG &DAG) const
SDValue LowerDYNAMIC_STACKALLOC (SDValue Op, SelectionDAG &DAG) const
SDValue LowerINLINEASM (SDValue Op, SelectionDAG &DAG) const
SDValue LowerPREFETCH (SDValue Op, SelectionDAG &DAG) const
SDValue LowerREADCYCLECOUNTER (SDValue Op, SelectionDAG &DAG) const
SDValue LowerEH_LABEL (SDValue Op, SelectionDAG &DAG) const
SDValue LowerEH_RETURN (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFormalArguments (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > &Ins, const SDLoc &dl, SelectionDAG &DAG, SmallVectorImpl< SDValue > &InVals) const override
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
SDValue LowerGLOBALADDRESS (SDValue Op, SelectionDAG &DAG) const
SDValue LowerBlockAddress (SDValue Op, SelectionDAG &DAG) const
SDValue LowerGlobalTLSAddress (SDValue Op, SelectionDAG &DAG) const
SDValue LowerToTLSGeneralDynamicModel (GlobalAddressSDNode *GA, SelectionDAG &DAG) const
SDValue LowerToTLSInitialExecModel (GlobalAddressSDNode *GA, SelectionDAG &DAG) const
SDValue LowerToTLSLocalExecModel (GlobalAddressSDNode *GA, SelectionDAG &DAG) const
SDValue GetDynamicTLSAddr (SelectionDAG &DAG, SDValue Chain, GlobalAddressSDNode *GA, SDValue InGlue, EVT PtrVT, unsigned ReturnReg, unsigned char OperandGlues) const
SDValue LowerGLOBAL_OFFSET_TABLE (SDValue Op, SelectionDAG &DAG) const
SDValue LowerCall (TargetLowering::CallLoweringInfo &CLI, SmallVectorImpl< SDValue > &InVals) const override
LowerCall - Functions arguments are copied from virtual regs to (physical regs)/(stack frame), CALLSEQ_START and CALLSEQ_END are emitted.
SDValue LowerCallResult (SDValue Chain, SDValue InGlue, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > &Ins, const SDLoc &dl, SelectionDAG &DAG, SmallVectorImpl< SDValue > &InVals, const SmallVectorImpl< SDValue > &OutVals, SDValue Callee) const
LowerCallResult - Lower the result values of an ISD::CALL into the appropriate copies out of appropriate physical registers.
SDValue LowerSETCC (SDValue Op, SelectionDAG &DAG) const
SDValue LowerVSELECT (SDValue Op, SelectionDAG &DAG) const
SDValue LowerFRAMEADDR (SDValue Op, SelectionDAG &DAG) const
SDValue LowerATOMIC_FENCE (SDValue Op, SelectionDAG &DAG) const
SDValue LowerRETURNADDR (SDValue Op, SelectionDAG &DAG) const
bool CanLowerReturn (CallingConv::ID CallConv, MachineFunction &MF, bool isVarArg, const SmallVectorImpl< ISD::OutputArg > &Outs, LLVMContext &Context) const override
This hook should be implemented to check whether the return values described by the Outs array can fit into the return registers.
SDValue LowerReturn (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::OutputArg > &Outs, const SmallVectorImpl< SDValue > &OutVals, const SDLoc &dl, SelectionDAG &DAG) const override
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG.
SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const override
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
bool mayBeEmittedAsTailCall (const CallInst *CI) const override
Return true if the target may be able emit the call instruction as a tail call.
Register getRegisterByName (const char *RegName, LLT VT, const MachineFunction &MF) const override
Return the register ID of the name passed in.
Register getExceptionPointerRegister (const Constant *PersonalityFn) const override
If a physical register, this returns the register that receives the exception address on entry to an EH pad.
Register getExceptionSelectorRegister (const Constant *PersonalityFn) const override
If a physical register, this returns the register that receives the exception typeid on entry to a landing pad.
SDValue LowerVASTART (SDValue Op, SelectionDAG &DAG) const
SDValue LowerVACOPY (SDValue Op, SelectionDAG &DAG) const
SDValue LowerConstantPool (SDValue Op, SelectionDAG &DAG) const
SDValue LowerJumpTable (SDValue Op, SelectionDAG &DAG) const
EVT getSetCCResultType (const DataLayout &, LLVMContext &C, EVT VT) const override
Return the ValueType of the result of SETCC operations.
bool getPostIndexedAddressParts (SDNode *N, SDNode *Op, SDValue &Base, SDValue &Offset, ISD::MemIndexedMode &AM, SelectionDAG &DAG) const override
Returns true by value, base pointer and offset pointer and addressing mode by reference if this node can be combined with a load / store to form a post-indexed load / store.
ConstraintType getConstraintType (StringRef Constraint) const override
Given a constraint, return the type of constraint it is for this target.
std::pair< unsigned, const TargetRegisterClass * > getRegForInlineAsmConstraint (const TargetRegisterInfo *TRI, StringRef Constraint, MVT VT) const override
Given a physical register constraint (e.g.
SDValue LowerINTRINSIC_WO_CHAIN (SDValue Op, SelectionDAG &DAG) const
SDValue LowerINTRINSIC_VOID (SDValue Op, SelectionDAG &DAG) const
bool isLegalAddressingMode (const DataLayout &DL, const AddrMode &AM, Type *Ty, unsigned AS, Instruction *I=nullptr) const override
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
bool isOffsetFoldingLegal (const GlobalAddressSDNode *GA) const override
Return true if folding a constant offset with the given GlobalAddress is legal.
bool isFPImmLegal (const APFloat &Imm, EVT VT, bool ForCodeSize) const override
isFPImmLegal - Returns true if the target can instruction select the specified FP immediate natively.
bool isLegalICmpImmediate (int64_t Imm) const override
isLegalICmpImmediate - Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
EVT getOptimalMemOpType (const MemOp &Op, const AttributeList &FuncAttributes) const override
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, EVT VT, unsigned AddrSpace, Align Alignment, MachineMemOperand::Flags Flags, unsigned *Fast) const override
Return true if the target supports a memory access of this type for the given address space and alignment.
bool allowsMisalignedMemoryAccesses (EVT VT, unsigned AddrSpace, Align Alignment, MachineMemOperand::Flags Flags, unsigned *Fast) const override
Determine if the target supports unaligned memory accesses.
SDValue getPICJumpTableRelocBase (SDValue Table, SelectionDAG &DAG) const override
Returns relocation base for the given PIC jumptable.
bool shouldReduceLoadWidth (SDNode *Load, ISD::LoadExtType ExtTy, EVT NewVT) const override
Return true if it is profitable to reduce a load to a smaller type.
void AdjustInstrPostInstrSelection (MachineInstr &MI, SDNode *Node) const override
This method should be implemented by targets that mark instructions with the 'hasPostISelHook' flag.
Value * emitLoadLinked (IRBuilderBase &Builder, Type *ValueTy, Value *Addr, AtomicOrdering Ord) const override
Perform a load-linked operation on Addr, returning a "Value *" with the corresponding pointee type.
Value * emitStoreConditional (IRBuilderBase &Builder, Value *Val, Value *Addr, AtomicOrdering Ord) const override
Perform a store-conditional operation to Addr.
AtomicExpansionKind shouldExpandAtomicLoadInIR (LoadInst *LI) const override
Returns how the given (atomic) load should be expanded by the IR-level AtomicExpand pass.
AtomicExpansionKind shouldExpandAtomicStoreInIR (StoreInst *SI) const override
Returns how the given (atomic) store should be expanded by the IR-level AtomicExpand pass into.
AtomicExpansionKind shouldExpandAtomicCmpXchgInIR (AtomicCmpXchgInst *AI) const override
Returns how the given atomic cmpxchg should be expanded by the IR-level AtomicExpand pass.
AtomicExpansionKind shouldExpandAtomicRMWInIR (AtomicRMWInst *AI) const override
Returns how the IR-level AtomicExpand pass should expand the given AtomicRMW, if at all.
Public Member Functions inherited from llvm::TargetLowering
TargetLowering (const TargetLowering &)=delete
TargetLowering & operator= (const TargetLowering &)=delete
TargetLowering (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
bool isPositionIndependent () const
virtual bool isSDNodeSourceOfDivergence (const SDNode *N, FunctionLoweringInfo *FLI, UniformityInfo *UA) const
virtual bool isReassocProfitable (SelectionDAG &DAG, SDValue N0, SDValue N1) const
virtual bool isReassocProfitable (MachineRegisterInfo &MRI, Register N0, Register N1) const
virtual bool isSDNodeAlwaysUniform (const SDNode *N) const
virtual bool getPreIndexedAddressParts (SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
Returns true by value, base pointer and offset pointer and addressing mode by reference if the node's address can be legally represented as pre-indexed load / store address.
virtual bool getPostIndexedAddressParts (SDNode *, SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
Returns true by value, base pointer and offset pointer and addressing mode by reference if this node can be combined with a load / store to form a post-indexed load / store.
virtual bool isIndexingLegal (MachineInstr &MI, Register Base, Register Offset, bool IsPre, MachineRegisterInfo &MRI) const
Returns true if the specified base+offset is a legal indexed addressing mode for this target.
virtual unsigned getJumpTableEncoding () const
Return the entry encoding for a jump table in the current function.
virtual const MCExpr * LowerCustomJumpTableEntry (const MachineJumpTableInfo *, const MachineBasicBlock *, unsigned, MCContext &) const
virtual SDValue getPICJumpTableRelocBase (SDValue Table, SelectionDAG &DAG) const
Returns relocation base for the given PIC jumptable.
virtual const MCExpr * getPICJumpTableRelocBaseExpr (const MachineFunction *MF, unsigned JTI, MCContext &Ctx) const
This returns the relocation base for the given PIC jumptable, the same as getPICJumpTableRelocBase, but as an MCExpr.
virtual bool isOffsetFoldingLegal (const GlobalAddressSDNode *GA) const
Return true if folding a constant offset with the given GlobalAddress is legal.
virtual bool isInlineAsmTargetBranch (const SmallVectorImpl< StringRef > &AsmStrs, unsigned OpNo) const
On x86, return true if the operand with index OpNo is a CALL or JUMP instruction, which can use either a memory constraint or an address constraint.
bool isInTailCallPosition (SelectionDAG &DAG, SDNode *Node, SDValue &Chain) const
Check whether a given call node is in tail position within its function.
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, const SDLoc &DL, const SDValue OldLHS, const SDValue OldRHS) const
Soften the operands of a comparison.
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, const SDLoc &DL, const SDValue OldLHS, const SDValue OldRHS, SDValue &Chain, bool IsSignaling=false) const
std::pair< SDValue, SDValue > makeLibCall (SelectionDAG &DAG, RTLIB::Libcall LC, EVT RetVT, ArrayRef< SDValue > Ops, MakeLibCallOptions CallOptions, const SDLoc &dl, SDValue Chain=SDValue()) const
Returns a pair of (return value, chain).
bool parametersInCSRMatch (const MachineRegisterInfo &MRI, const uint32_t *CallerPreservedMask, const SmallVectorImpl< CCValAssign > &ArgLocs, const SmallVectorImpl< SDValue > &OutVals) const
Check whether parameters to a call that are passed in callee saved registers are the same as from the calling function.
virtual bool findOptimalMemOpLowering (std::vector< EVT > &MemOps, unsigned Limit, const MemOp &Op, unsigned DstAS, unsigned SrcAS, const AttributeList &FuncAttributes) const
Determines the optimal series of memory ops to replace the memset / memcpy.
bool ShrinkDemandedConstant (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, TargetLoweringOpt &TLO) const
Check to see if the specified operand of the specified instruction is a constant integer.
bool ShrinkDemandedConstant (SDValue Op, const APInt &DemandedBits, TargetLoweringOpt &TLO) const
Helper wrapper around ShrinkDemandedConstant, demanding all elements.
virtual bool targetShrinkDemandedConstant (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, TargetLoweringOpt &TLO) const
bool ShrinkDemandedOp (SDValue Op, unsigned BitWidth, const APInt &DemandedBits, TargetLoweringOpt &TLO) const
Convert x+y to (VT)((SmallVT)x+(SmallVT)y) if the casts are free.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Look at Op.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Helper wrapper around SimplifyDemandedBits, demanding all elements.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, DAGCombinerInfo &DCI) const
Helper wrapper around SimplifyDemandedBits.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, DAGCombinerInfo &DCI) const
Helper wrapper around SimplifyDemandedBits.
SDValue SimplifyMultipleUseDemandedBits (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, SelectionDAG &DAG, unsigned Depth=0) const
More limited version of SimplifyDemandedBits that can be used to "look through" ops that don't contribute to the DemandedBits/DemandedElts - bitwise ops etc.
SDValue SimplifyMultipleUseDemandedBits (SDValue Op, const APInt &DemandedBits, SelectionDAG &DAG, unsigned Depth=0) const
Helper wrapper around SimplifyMultipleUseDemandedBits, demanding all elements.
SDValue SimplifyMultipleUseDemandedVectorElts (SDValue Op, const APInt &DemandedElts, SelectionDAG &DAG, unsigned Depth=0) const
Helper wrapper around SimplifyMultipleUseDemandedBits, demanding all bits from only some vector elements.
bool SimplifyDemandedVectorElts (SDValue Op, const APInt &DemandedEltMask, APInt &KnownUndef, APInt &KnownZero, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Look at Vector Op.
bool SimplifyDemandedVectorElts (SDValue Op, const APInt &DemandedElts, DAGCombinerInfo &DCI) const
Helper wrapper around SimplifyDemandedVectorElts.
virtual bool shouldSimplifyDemandedVectorElts (SDValue Op, const TargetLoweringOpt &TLO) const
Return true if the target supports simplifying demanded vector elements by converting them to undefs.
virtual void computeKnownBitsForTargetNode (const SDValue Op, KnownBits &Known, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth=0) const
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
virtual void computeKnownBitsForTargetInstr (GISelKnownBits &Analysis, Register R, KnownBits &Known, const APInt &DemandedElts, const MachineRegisterInfo &MRI, unsigned Depth=0) const
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
virtual Align computeKnownAlignForTargetInstr (GISelKnownBits &Analysis, Register R, const MachineRegisterInfo &MRI, unsigned Depth=0) const
Determine the known alignment for the pointer value R.
virtual void computeKnownBitsForFrameIndex (int FIOp, KnownBits &Known, const MachineFunction &MF) const
Determine which of the bits of FrameIndex FIOp are known to be 0.
virtual unsigned ComputeNumSignBitsForTargetNode (SDValue Op, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth=0) const
This method can be implemented by targets that want to expose additional information about sign bits to the DAG Combiner.
virtual unsigned computeNumSignBitsForTargetInstr (GISelKnownBits &Analysis, Register R, const APInt &DemandedElts, const MachineRegisterInfo &MRI, unsigned Depth=0) const
This method can be implemented by targets that want to expose additional information about sign bits to GlobalISel combiners.
virtual bool SimplifyDemandedVectorEltsForTargetNode (SDValue Op, const APInt &DemandedElts, APInt &KnownUndef, APInt &KnownZero, TargetLoweringOpt &TLO, unsigned Depth=0) const
Attempt to simplify any target nodes based on the demanded vector elements, returning true on success.
virtual bool SimplifyDemandedBitsForTargetNode (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0) const
Attempt to simplify any target nodes based on the demanded bits/elts, returning true on success.
virtual SDValue SimplifyMultipleUseDemandedBitsForTargetNode (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, SelectionDAG &DAG, unsigned Depth) const
More limited version of SimplifyDemandedBits that can be used to "look through" ops that don't contribute to the DemandedBits/DemandedElts - bitwise ops etc.
virtual bool isGuaranteedNotToBeUndefOrPoisonForTargetNode (SDValue Op, const APInt &DemandedElts, const SelectionDAG &DAG, bool PoisonOnly, unsigned Depth) const
Return true if this function can prove that Op is never poison and, if PoisonOnly is false, does not have undef bits.
virtual bool canCreateUndefOrPoisonForTargetNode (SDValue Op, const APInt &DemandedElts, const SelectionDAG &DAG, bool PoisonOnly, bool ConsiderFlags, unsigned Depth) const
Return true if Op can create undef or poison from non-undef & non-poison operands.
SDValue buildLegalVectorShuffle (EVT VT, const SDLoc &DL, SDValue N0, SDValue N1, MutableArrayRef< int > Mask, SelectionDAG &DAG) const
Tries to build a legal vector shuffle using the provided parameters or equivalent variations.
virtual const Constant * getTargetConstantFromLoad (LoadSDNode *LD) const
This method returns the constant pool value that will be loaded by LD.
virtual bool isKnownNeverNaNForTargetNode (SDValue Op, const SelectionDAG &DAG, bool SNaN=false, unsigned Depth=0) const
If SNaN is false,.
virtual bool isSplatValueForTargetNode (SDValue Op, const APInt &DemandedElts, APInt &UndefElts, const SelectionDAG &DAG, unsigned Depth=0) const
Return true if vector Op has the same value across all DemandedElts, indicating any elements which may be undef in the output UndefElts.
virtual bool isTargetCanonicalConstantNode (SDValue Op) const
Returns true if the given Opc is considered a canonical constant for the target, which should not be transformed back into a BUILD_VECTOR.
bool isConstTrueVal (SDValue N) const
Return if the N is a constant or constant vector equal to the true value from getBooleanContents().
bool isConstFalseVal (SDValue N) const
Return if the N is a constant or constant vector equal to the false value from getBooleanContents().
bool isExtendedTrueVal (const ConstantSDNode *N, EVT VT, bool SExt) const
Return if N is a True value when extended to VT.
SDValue SimplifySetCC (EVT VT, SDValue N0, SDValue N1, ISD::CondCode Cond, bool foldBooleans, DAGCombinerInfo &DCI, const SDLoc &dl) const
Try to simplify a setcc built with the specified operands and cc.
virtual SDValue unwrapAddress (SDValue N) const
virtual bool isGAPlusOffset (SDNode *N, const GlobalValue *&GA, int64_t &Offset) const
Returns true (and the GlobalValue and the offset) if the node is a GlobalAddress + offset.
virtual SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
virtual bool isDesirableToCommuteWithShift (const SDNode *N, CombineLevel Level) const
Return true if it is profitable to move this shift by a constant amount through its operand, adjusting any immediate operands as necessary to preserve semantics.
virtual bool isDesirableToCommuteWithShift (const MachineInstr &MI, bool IsAfterLegal) const
GlobalISel - return true if it is profitable to move this shift by a constant amount through its operand, adjusting any immediate operands as necessary to preserve semantics.
virtual bool isDesirableToPullExtFromShl (const MachineInstr &MI) const
GlobalISel - return true if it's profitable to perform the combine: shl ([sza]ext x), y => zext (shl x, y)
virtual AndOrSETCCFoldKind isDesirableToCombineLogicOpOfSETCC (const SDNode *LogicOp, const SDNode *SETCC0, const SDNode *SETCC1) const
virtual bool isDesirableToCommuteXorWithShift (const SDNode *N) const
Return true if it is profitable to combine an XOR of a logical shift to create a logical shift of NOT.
virtual bool isTypeDesirableForOp (unsigned, EVT VT) const
Return true if the target has native support for the specified value type and it is 'desirable' to use the type for the given node type.
virtual bool isDesirableToTransformToIntegerOp (unsigned, EVT) const
Return true if it is profitable for dag combiner to transform a floating point op of specified opcode to a equivalent op of an integer type.
virtual bool IsDesirableToPromoteOp (SDValue, EVT &) const
This method query the target whether it is beneficial for dag combiner to promote the specified node.
virtual bool supportSwiftError () const
Return true if the target supports swifterror attribute.
virtual bool supportSplitCSR (MachineFunction *MF) const
Return true if the target supports that a subset of CSRs for the given machine function is handled explicitly via copies.
virtual bool supportKCFIBundles () const
Return true if the target supports kcfi operand bundles.
virtual void initializeSplitCSR (MachineBasicBlock *Entry) const
Perform necessary initialization to handle a subset of CSRs explicitly via copies.
virtual void insertCopiesSplitCSR (MachineBasicBlock *Entry, const SmallVectorImpl< MachineBasicBlock * > &Exits) const
Insert explicit copies in entry and exit blocks.
virtual SDValue getNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOps, bool OptForSize, NegatibleCost &Cost, unsigned Depth=0) const
Return the newly negated expression if the cost is not expensive and set the cost in Cost to indicate that if it is cheaper or neutral to do the negation.
SDValue getCheaperOrNeutralNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOps, bool OptForSize, const NegatibleCost CostThreshold=NegatibleCost::Neutral, unsigned Depth=0) const
SDValue getCheaperNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOps, bool OptForSize, unsigned Depth=0) const
This is the helper function to return the newly negated expression only when the cost is cheaper.
SDValue getNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOps, bool OptForSize, unsigned Depth=0) const
This is the helper function to return the newly negated expression if the cost is not expensive.
virtual bool splitValueIntoRegisterParts (SelectionDAG &DAG, const SDLoc &DL, SDValue Val, SDValue *Parts, unsigned NumParts, MVT PartVT, std::optional< CallingConv::ID > CC) const
Target-specific splitting of values into parts that fit a register storing a legal type.
virtual bool checkForPhysRegDependency (SDNode *Def, SDNode *User, unsigned Op, const TargetRegisterInfo *TRI, const TargetInstrInfo *TII, unsigned &PhysReg, int &Cost) const
Allows the target to handle physreg-carried dependency in target-specific way.
virtual SDValue joinRegisterPartsIntoValue (SelectionDAG &DAG, const SDLoc &DL, const SDValue *Parts, unsigned NumParts, MVT PartVT, EVT ValueVT, std::optional< CallingConv::ID > CC) const
Target-specific combining of register parts into its original value.
virtual SDValue LowerFormalArguments (SDValue, CallingConv::ID, bool, const SmallVectorImpl< ISD::InputArg > &, const SDLoc &, SelectionDAG &, SmallVectorImpl< SDValue > &) const
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
std::pair< SDValue, SDValue > LowerCallTo (CallLoweringInfo &CLI) const
This function lowers an abstract call to a function into an actual call.
virtual SDValue LowerCall (CallLoweringInfo &, SmallVectorImpl< SDValue > &) const
This hook must be implemented to lower calls into the specified DAG.
virtual void HandleByVal (CCState *, unsigned &, Align) const
Target-specific cleanup for formal ByVal parameters.
virtual bool CanLowerReturn (CallingConv::ID, MachineFunction &, bool, const SmallVectorImpl< ISD::OutputArg > &, LLVMContext &) const
This hook should be implemented to check whether the return values described by the Outs array can fit into the return registers.
virtual SDValue LowerReturn (SDValue, CallingConv::ID, bool, const SmallVectorImpl< ISD::OutputArg > &, const SmallVectorImpl< SDValue > &, const SDLoc &, SelectionDAG &) const
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG.
virtual bool isUsedByReturnOnly (SDNode *, SDValue &) const
Return true if result of the specified node is used by a return node only.
virtual bool mayBeEmittedAsTailCall (const CallInst *) const
Return true if the target may be able emit the call instruction as a tail call.
virtual const char * getClearCacheBuiltinName () const
Return the builtin name for the __builtin___clear_cache intrinsic Default is to invoke the clear cache library call.
virtual Register getRegisterByName (const char *RegName, LLT Ty, const MachineFunction &MF) const
Return the register ID of the name passed in.
virtual EVT getTypeForExtReturn (LLVMContext &Context, EVT VT, ISD::NodeType) const
Return the type that should be used to zero or sign extend a zeroext/signext integer return value.
virtual bool functionArgumentNeedsConsecutiveRegisters (Type *Ty, CallingConv::ID CallConv, bool isVarArg, const DataLayout &DL) const
For some targets, an LLVM struct type must be broken down into multiple simple types, but the calling convention specifies that the entire struct must be passed in a block of consecutive registers.
virtual bool shouldSplitFunctionArgumentsAsLittleEndian (const DataLayout &DL) const
For most targets, an LLVM type must be broken down into multiple smaller types.
virtual const MCPhysReg * getScratchRegisters (CallingConv::ID CC) const
Returns a 0 terminated array of registers that can be safely used as scratch registers.
virtual ArrayRef< MCPhysReg > getRoundingControlRegisters () const
Returns a 0 terminated array of rounding control registers that can be attached into strict FP call.
virtual SDValue prepareVolatileOrAtomicLoad (SDValue Chain, const SDLoc &DL, SelectionDAG &DAG) const
This callback is used to prepare for a volatile or atomic load.
virtual void LowerOperationWrapper (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const
This callback is invoked by the type legalizer to legalize nodes with an illegal operand type but legal result types.
virtual SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
virtual void ReplaceNodeResults (SDNode *, SmallVectorImpl< SDValue > &, SelectionDAG &) const
This callback is invoked when a node result type is illegal for the target, and the operation was registered to use 'custom' lowering for that result type.
virtual const char * getTargetNodeName (unsigned Opcode) const
This method returns the name of a target specific DAG node.
virtual FastISel * createFastISel (FunctionLoweringInfo &, const TargetLibraryInfo *) const
This method returns a target specific FastISel object, or null if the target does not support "fast" ISel.
bool verifyReturnAddressArgumentIsConstant (SDValue Op, SelectionDAG &DAG) const
virtual bool ExpandInlineAsm (CallInst *) const
This hook allows the target to expand an inline asm call to be explicit llvm code if it wants to.
virtual AsmOperandInfoVector ParseConstraints (const DataLayout &DL, const TargetRegisterInfo *TRI, const CallBase &Call) const
Split up the constraint string from the inline assembly value into the specific constraints and their prefixes, and also tie in the associated operand values.
virtual ConstraintWeight getMultipleConstraintMatchWeight (AsmOperandInfo &info, int maIndex) const
Examine constraint type and operand type and determine a weight value.
virtual ConstraintWeight getSingleConstraintMatchWeight (AsmOperandInfo &info, const char *constraint) const
Examine constraint string and operand type and determine a weight value.
virtual void ComputeConstraintToUse (AsmOperandInfo &OpInfo, SDValue Op, SelectionDAG *DAG=nullptr) const
Determines the constraint code and constraint type to use for the specific AsmOperandInfo, setting OpInfo.ConstraintCode and OpInfo.ConstraintType.
virtual ConstraintType getConstraintType (StringRef Constraint) const
Given a constraint, return the type of constraint it is for this target.
ConstraintGroup getConstraintPreferences (AsmOperandInfo &OpInfo) const
Given an OpInfo with list of constraints codes as strings, return a sorted Vector of pairs of constraint codes and their types in priority of what we'd prefer to lower them as.
virtual std::pair< unsigned, const TargetRegisterClass * > getRegForInlineAsmConstraint (const TargetRegisterInfo *TRI, StringRef Constraint, MVT VT) const
Given a physical register constraint (e.g.
virtual InlineAsm::ConstraintCode getInlineAsmMemConstraint (StringRef ConstraintCode) const
virtual const char * LowerXConstraint (EVT ConstraintVT) const
Try to replace an X constraint, which matches anything, with another that has more specific requirements based on the type of the corresponding operand.
virtual void LowerAsmOperandForConstraint (SDValue Op, StringRef Constraint, std::vector< SDValue > &Ops, SelectionDAG &DAG) const
Lower the specified operand into the Ops vector.
virtual SDValue LowerAsmOutputForConstraint (SDValue &Chain, SDValue &Glue, const SDLoc &DL, const AsmOperandInfo &OpInfo, SelectionDAG &DAG) const
virtual void CollectTargetIntrinsicOperands (const CallInst &I, SmallVectorImpl< SDValue > &Ops, SelectionDAG &DAG) const
SDValue BuildSDIV (SDNode *N, SelectionDAG &DAG, bool IsAfterLegalization, SmallVectorImpl< SDNode * > &Created) const
Given an ISD::SDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number.
SDValue BuildUDIV (SDNode *N, SelectionDAG &DAG, bool IsAfterLegalization, SmallVectorImpl< SDNode * > &Created) const
Given an ISD::UDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number.
SDValue buildSDIVPow2WithCMov (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, SmallVectorImpl< SDNode * > &Created) const
Build sdiv by power-of-2 with conditional move instructions Ref: "Hacker's Delight" by Henry Warren 10-1 If conditional move/branch is preferred, we lower sdiv x, +/-2**k into: bgez x, label add x, x, 2**k-1 label: sra res, x, k neg res, res (when the divisor is negative)
virtual SDValue BuildSDIVPow2 (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, SmallVectorImpl< SDNode * > &Created) const
Targets may override this function to provide custom SDIV lowering for power-of-2 denominators.
virtual SDValue BuildSREMPow2 (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, SmallVectorImpl< SDNode * > &Created) const
Targets may override this function to provide custom SREM lowering for power-of-2 denominators.
virtual unsigned combineRepeatedFPDivisors () const
Indicate whether this target prefers to combine FDIVs with the same divisor.
virtual SDValue getSqrtEstimate (SDValue Operand, SelectionDAG &DAG, int Enabled, int &RefinementSteps, bool &UseOneConstNR, bool Reciprocal) const
Hooks for building estimates in place of slower divisions and square roots.
SDValue createSelectForFMINNUM_FMAXNUM (SDNode *Node, SelectionDAG &DAG) const
Try to convert the fminnum/fmaxnum to a compare/select sequence.
virtual SDValue getRecipEstimate (SDValue Operand, SelectionDAG &DAG, int Enabled, int &RefinementSteps) const
Return a reciprocal estimate value for the input operand.
virtual SDValue getSqrtInputTest (SDValue Operand, SelectionDAG &DAG, const DenormalMode &Mode) const
Return a target-dependent comparison result if the input operand is suitable for use with a square root estimate calculation.
virtual SDValue getSqrtResultForDenormInput (SDValue Operand, SelectionDAG &DAG) const
Return a target-dependent result if the input operand is not suitable for use with a square root estimate calculation.
bool expandMUL_LOHI (unsigned Opcode, EVT VT, const SDLoc &dl, SDValue LHS, SDValue RHS, SmallVectorImpl< SDValue > &Result, EVT HiLoVT, SelectionDAG &DAG, MulExpansionKind Kind, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
Expand a MUL or [US]MUL_LOHI of n-bit values into two or four nodes, respectively, each computing an n/2-bit part of the result.
bool expandMUL (SDNode *N, SDValue &Lo, SDValue &Hi, EVT HiLoVT, SelectionDAG &DAG, MulExpansionKind Kind, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
Expand a MUL into two nodes.
bool expandDIVREMByConstant (SDNode *N, SmallVectorImpl< SDValue > &Result, EVT HiLoVT, SelectionDAG &DAG, SDValue LL=SDValue(), SDValue LH=SDValue()) const
Attempt to expand an n-bit div/rem/divrem by constant using a n/2-bit urem by constant and other arithmetic ops.
SDValue expandFunnelShift (SDNode *N, SelectionDAG &DAG) const
Expand funnel shift.
SDValue expandROT (SDNode *N, bool AllowVectorOps, SelectionDAG &DAG) const
Expand rotations.
void expandShiftParts (SDNode *N, SDValue &Lo, SDValue &Hi, SelectionDAG &DAG) const
Expand shift-by-parts.
bool expandFP_TO_SINT (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand float(f32) to SINT(i64) conversion.
bool expandFP_TO_UINT (SDNode *N, SDValue &Result, SDValue &Chain, SelectionDAG &DAG) const
Expand float to UINT conversion.
bool expandUINT_TO_FP (SDNode *N, SDValue &Result, SDValue &Chain, SelectionDAG &DAG) const
Expand UINT(i64) to double(f64) conversion.
SDValue expandFMINNUM_FMAXNUM (SDNode *N, SelectionDAG &DAG) const
Expand fminnum/fmaxnum into fminnum_ieee/fmaxnum_ieee with quieted inputs.
SDValue expandFP_TO_INT_SAT (SDNode *N, SelectionDAG &DAG) const
Expand FP_TO_[US]INT_SAT into FP_TO_[US]INT and selects or min/max.
SDValue expandIS_FPCLASS (EVT ResultVT, SDValue Op, FPClassTest Test, SDNodeFlags Flags, const SDLoc &DL, SelectionDAG &DAG) const
Expand check for floating point class.
SDValue expandCTPOP (SDNode *N, SelectionDAG &DAG) const
Expand CTPOP nodes.
SDValue expandVPCTPOP (SDNode *N, SelectionDAG &DAG) const
Expand VP_CTPOP nodes.
SDValue expandCTLZ (SDNode *N, SelectionDAG &DAG) const
Expand CTLZ/CTLZ_ZERO_UNDEF nodes.
SDValue expandVPCTLZ (SDNode *N, SelectionDAG &DAG) const
Expand VP_CTLZ/VP_CTLZ_ZERO_UNDEF nodes.
SDValue CTTZTableLookup (SDNode *N, SelectionDAG &DAG, const SDLoc &DL, EVT VT, SDValue Op, unsigned NumBitsPerElt) const
Expand CTTZ via Table Lookup.
SDValue expandCTTZ (SDNode *N, SelectionDAG &DAG) const
Expand CTTZ/CTTZ_ZERO_UNDEF nodes.
SDValue expandVPCTTZ (SDNode *N, SelectionDAG &DAG) const
Expand VP_CTTZ/VP_CTTZ_ZERO_UNDEF nodes.
SDValue expandABS (SDNode *N, SelectionDAG &DAG, bool IsNegative=false) const
Expand ABS nodes.
SDValue expandABD (SDNode *N, SelectionDAG &DAG) const
Expand ABDS/ABDU nodes.
SDValue expandBSWAP (SDNode *N, SelectionDAG &DAG) const
Expand BSWAP nodes.
SDValue expandVPBSWAP (SDNode *N, SelectionDAG &DAG) const
Expand VP_BSWAP nodes.
SDValue expandBITREVERSE (SDNode *N, SelectionDAG &DAG) const
Expand BITREVERSE nodes.
SDValue expandVPBITREVERSE (SDNode *N, SelectionDAG &DAG) const
Expand VP_BITREVERSE nodes.
std::pair< SDValue, SDValue > scalarizeVectorLoad (LoadSDNode *LD, SelectionDAG &DAG) const
Turn load of vector type into a load of the individual elements.
SDValue scalarizeVectorStore (StoreSDNode *ST, SelectionDAG &DAG) const
std::pair< SDValue, SDValue > expandUnalignedLoad (LoadSDNode *LD, SelectionDAG &DAG) const
Expands an unaligned load to 2 half-size loads for an integer, and possibly more for vectors.
SDValue expandUnalignedStore (StoreSDNode *ST, SelectionDAG &DAG) const
Expands an unaligned store to 2 half-size stores for integer values, and possibly more for vectors.
SDValue IncrementMemoryAddress (SDValue Addr, SDValue Mask, const SDLoc &DL, EVT DataVT, SelectionDAG &DAG, bool IsCompressedMemory) const
Increments memory address Addr according to the type of the value DataVT that should be stored.
SDValue getVectorElementPointer (SelectionDAG &DAG, SDValue VecPtr, EVT VecVT, SDValue Index) const
Get a pointer to vector element Idx located in memory for a vector of type VecVT starting at a base address of VecPtr.
SDValue getVectorSubVecPointer (SelectionDAG &DAG, SDValue VecPtr, EVT VecVT, EVT SubVecVT, SDValue Index) const
Get a pointer to a sub-vector of type SubVecVT at index Idx located in memory for a vector of type VecVT starting at a base address of VecPtr.
SDValue expandIntMINMAX (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US][MIN|MAX].
SDValue expandAddSubSat (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US][ADD|SUB]SAT.
SDValue expandShlSat (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]SHLSAT.
SDValue expandFixedPointMul (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[U|S]MULFIX[SAT].
SDValue expandFixedPointDiv (unsigned Opcode, const SDLoc &dl, SDValue LHS, SDValue RHS, unsigned Scale, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]DIVFIX[SAT].
void expandUADDSUBO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::U(ADD|SUB)O.
void expandSADDSUBO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::S(ADD|SUB)O.
bool expandMULO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]MULO.
SDValue expandVecReduce (SDNode *Node, SelectionDAG &DAG) const
Expand a VECREDUCE_* into an explicit calculation.
SDValue expandVecReduceSeq (SDNode *Node, SelectionDAG &DAG) const
Expand a VECREDUCE_SEQ_* into an explicit ordered calculation.
bool expandREM (SDNode *Node, SDValue &Result, SelectionDAG &DAG) const
Expand an SREM or UREM using SDIV/UDIV or SDIVREM/UDIVREM, if legal.
SDValue expandVectorSplice (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::VECTOR_SPLICE.
bool LegalizeSetCCCondCode (SelectionDAG &DAG, EVT VT, SDValue &LHS, SDValue &RHS, SDValue &CC, SDValue Mask, SDValue EVL, bool &NeedInvert, const SDLoc &dl, SDValue &Chain, bool IsSignaling=false) const
Legalize a SETCC or VP_SETCC with given LHS and RHS and condition code CC on the current target.
virtual MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr &MI, MachineBasicBlock *MBB) const
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
virtual void AdjustInstrPostInstrSelection (MachineInstr &MI, SDNode *Node) const
This method should be implemented by targets that mark instructions with the 'hasPostISelHook' flag.
virtual bool useLoadStackGuardNode () const
If this function returns true, SelectionDAGBuilder emits a LOAD_STACK_GUARD node when it is lowering Intrinsic::stackprotector.
virtual SDValue emitStackGuardXorFP (SelectionDAG &DAG, SDValue Val, const SDLoc &DL) const
virtual SDValue LowerToTLSEmulatedModel (const GlobalAddressSDNode *GA, SelectionDAG &DAG) const
Lower TLS global address SDNode for target independent emulated TLS model.
virtual SDValue expandIndirectJTBranch (const SDLoc &dl, SDValue Value, SDValue Addr, int JTI, SelectionDAG &DAG) const
Expands target specific indirect branch for the case of JumpTable expansion.
SDValue lowerCmpEqZeroToCtlzSrl (SDValue Op, SelectionDAG &DAG) const
virtual bool isXAndYEqZeroPreferableToXAndYEqY (ISD::CondCode, EVT) const
Public Member Functions inherited from llvm::TargetLoweringBase
virtual void markLibCallAttributes (MachineFunction *MF, unsigned CC, ArgListTy &Args) const
TargetLoweringBase (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
TargetLoweringBase (const TargetLoweringBase &)=delete
TargetLoweringBase & operator= (const TargetLoweringBase &)=delete
virtual ~TargetLoweringBase ()=default
bool isStrictFPEnabled () const
Return true if the target support strict float operation.
const TargetMachine & getTargetMachine () const
virtual bool useSoftFloat () const
virtual MVT getPointerTy (const DataLayout &DL, uint32_t AS=0) const
Return the pointer type for the given address space, defaults to the pointer type from the data layout.
virtual MVT getPointerMemTy (const DataLayout &DL, uint32_t AS=0) const
Return the in-memory pointer type for the given address space, defaults to the pointer type from the data layout.
MVT getFrameIndexTy (const DataLayout &DL) const
Return the type for frame index, which is determined by the alloca address space specified through the data layout.
MVT getProgramPointerTy (const DataLayout &DL) const
Return the type for code pointers, which is determined by the program address space specified through the data layout.
virtual MVT getFenceOperandTy (const DataLayout &DL) const
Return the type for operands of fence.
virtual MVT getScalarShiftAmountTy (const DataLayout &, EVT) const
Return the type to use for a scalar shift opcode, given the shifted amount type.
EVT getShiftAmountTy (EVT LHSTy, const DataLayout &DL, bool LegalTypes=true) const
Returns the type for the shift amount of a shift opcode.
virtual LLVM_READONLY LLT getPreferredShiftAmountTy (LLT ShiftValueTy) const
Return the preferred type to use for a shift opcode, given the shifted amount type is ShiftValueTy.
virtual MVT getVectorIdxTy (const DataLayout &DL) const
Returns the type to be used for the index operand of: ISD::INSERT_VECTOR_ELT, ISD::EXTRACT_VECTOR_ELT, ISD::INSERT_SUBVECTOR, and ISD::EXTRACT_SUBVECTOR.
virtual MVT getVPExplicitVectorLengthTy () const
Returns the type to be used for the EVL/AVL operand of VP nodes: ISD::VP_ADD, ISD::VP_SUB, etc.
virtual MachineMemOperand::Flags getTargetMMOFlags (const Instruction &I) const
This callback is used to inspect load/store instructions and add target-specific MachineMemOperand flags to them.
virtual MachineMemOperand::Flags getTargetMMOFlags (const MemSDNode &Node) const
This callback is used to inspect load/store SDNode.
MachineMemOperand::Flags getLoadMemOperandFlags (const LoadInst &LI, const DataLayout &DL, AssumptionCache *AC=nullptr, const TargetLibraryInfo *LibInfo=nullptr) const
MachineMemOperand::Flags getStoreMemOperandFlags (const StoreInst &SI, const DataLayout &DL) const
MachineMemOperand::Flags getAtomicMemOperandFlags (const Instruction &AI, const DataLayout &DL) const
virtual bool isSelectSupported (SelectSupportKind) const
virtual bool shouldExpandGetActiveLaneMask (EVT VT, EVT OpVT) const
Return true if the @llvm.get.active.lane.mask intrinsic should be expanded using generic code in SelectionDAGBuilder.
virtual bool shouldExpandGetVectorLength (EVT CountVT, unsigned VF, bool IsScalable) const
virtual bool shouldExpandCttzElements (EVT VT) const
Return true if the @llvm.experimental.cttz.elts intrinsic should be expanded using generic code in SelectionDAGBuilder.
virtual bool shouldReassociateReduction (unsigned RedOpc, EVT VT) const
virtual bool reduceSelectOfFPConstantLoads (EVT CmpOpVT) const
Return true if it is profitable to convert a select of FP constants into a constant pool load whose address depends on the select condition.
bool hasMultipleConditionRegisters () const
Return true if multiple condition registers are available.
bool hasExtractBitsInsn () const
Return true if the target has BitExtract instructions.
virtual TargetLoweringBase::LegalizeTypeAction getPreferredVectorAction (MVT VT) const
Return the preferred vector type legalization action.
virtual bool softPromoteHalfType () const
virtual bool shouldExpandBuildVectorWithShuffles (EVT, unsigned DefinedValues) const
virtual bool isIntDivCheap (EVT VT, AttributeList Attr) const
Return true if integer divide is usually cheaper than a sequence of several shifts, adds, and multiplies for this target.
virtual bool hasStandaloneRem (EVT VT) const
Return true if the target can handle a standalone remainder operation.
virtual bool isFsqrtCheap (SDValue X, SelectionDAG &DAG) const
Return true if SQRT(X) shouldn't be replaced with X*RSQRT(X).
int getRecipEstimateSqrtEnabled (EVT VT, MachineFunction &MF) const
Return a ReciprocalEstimate enum value for a square root of the given type based on the function's attributes.
int getRecipEstimateDivEnabled (EVT VT, MachineFunction &MF) const
Return a ReciprocalEstimate enum value for a division of the given type based on the function's attributes.
int getSqrtRefinementSteps (EVT VT, MachineFunction &MF) const
Return the refinement step count for a square root of the given type based on the function's attributes.
int getDivRefinementSteps (EVT VT, MachineFunction &MF) const
Return the refinement step count for a division of the given type based on the function's attributes.
bool isSlowDivBypassed () const
Returns true if target has indicated at least one type should be bypassed.
const DenseMap< unsigned int, unsigned int > & getBypassSlowDivWidths () const
Returns map of slow types for division or remainder with corresponding fast types.
virtual bool isVScaleKnownToBeAPowerOfTwo () const
Return true only if vscale must be a power of two.
bool isJumpExpensive () const
Return true if Flow Control is an expensive operation that should be avoided.
bool isPredictableSelectExpensive () const
Return true if selects are only cheaper than branches if the branch is unlikely to be predicted right.
virtual bool fallBackToDAGISel (const Instruction &Inst) const
virtual bool isLoadBitCastBeneficial (EVT LoadVT, EVT BitcastVT, const SelectionDAG &DAG, const MachineMemOperand &MMO) const
Return true if the following transform is beneficial: fold (conv (load x)) -> (load (conv*)x) On architectures that don't natively support some vector loads efficiently, casting the load to a smaller vector of larger types and loading is more efficient, however, this can be undone by optimizations in dag combiner.
virtual bool isStoreBitCastBeneficial (EVT StoreVT, EVT BitcastVT, const SelectionDAG &DAG, const MachineMemOperand &MMO) const
Return true if the following transform is beneficial: (store (y (conv x)), y*)) -> (store x, (x*))
virtual bool storeOfVectorConstantIsCheap (bool IsZero, EVT MemVT, unsigned NumElem, unsigned AddrSpace) const
Return true if it is expected to be cheaper to do a store of vector constant with the given size and type for the address space than to store the individual scalar element constants.
virtual bool mergeStoresAfterLegalization (EVT MemVT) const
Allow store merging for the specified type after legalization in addition to before legalization.
virtual bool canMergeStoresTo (unsigned AS, EVT MemVT, const MachineFunction &MF) const
Returns if it's reasonable to merge stores to MemVT size.
virtual bool isCheapToSpeculateCttz (Type *Ty) const
Return true if it is cheap to speculate a call to intrinsic cttz.
virtual bool isCheapToSpeculateCtlz (Type *Ty) const
Return true if it is cheap to speculate a call to intrinsic ctlz.
virtual bool isCtlzFast () const
Return true if ctlz instruction is fast.
virtual bool isCtpopFast (EVT VT) const
Return true if ctpop instruction is fast.
virtual unsigned getCustomCtpopCost (EVT VT, ISD::CondCode Cond) const
Return the maximum number of "x & (x - 1)" operations that can be done instead of deferring to a custom CTPOP.
virtual bool isEqualityCmpFoldedWithSignedCmp () const
Return true if instruction generated for equality comparison is folded with instruction generated for signed comparison.
virtual bool preferZeroCompareBranch () const
Return true if the heuristic to prefer icmp eq zero should be used in code gen prepare.
virtual bool isMultiStoresCheaperThanBitsMerge (EVT LTy, EVT HTy) const
Return true if it is cheaper to split the store of a merged int val from a pair of smaller values into multiple stores.
virtual bool isMaskAndCmp0FoldingBeneficial (const Instruction &AndI) const
Return if the target supports combining a chain like:
virtual bool areTwoSDNodeTargetMMOFlagsMergeable (const MemSDNode &NodeX, const MemSDNode &NodeY) const
Return true if it is valid to merge the TargetMMOFlags in two SDNodes.
virtual bool convertSetCCLogicToBitwiseLogic (EVT VT) const
Use bitwise logic to make pairs of compares more efficient.
virtual MVT hasFastEqualityCompare (unsigned NumBits) const
Return the preferred operand type if the target has a quick way to compare integer values of the given size.
virtual bool hasAndNotCompare (SDValue Y) const
Return true if the target should transform: (X & Y) == Y —> (~X & Y) == 0 (X & Y) != Y —> (~X & Y) != 0.
virtual bool hasAndNot (SDValue X) const
Return true if the target has a bitwise and-not operation: X = ~A & B This can be used to simplify select or other instructions.
virtual bool hasBitTest (SDValue X, SDValue Y) const
Return true if the target has a bit-test instruction: (X & (1 << Y)) ==/!= 0 This knowledge can be used to prevent breaking the pattern, or creating it if it could be recognized.
virtual bool shouldFoldMaskToVariableShiftPair (SDValue X) const
There are two ways to clear extreme bits (either low or high): Mask: x & (-1 << y) (the instcombine canonical form) Shifts: x >> y << y Return true if the variant with 2 variable shifts is preferred.
virtual bool shouldFoldConstantShiftPairToMask (const SDNode *N, CombineLevel Level) const
Return true if it is profitable to fold a pair of shifts into a mask.
virtual bool shouldTransformSignedTruncationCheck (EVT XVT, unsigned KeptBits) const
Should we tranform the IR-optimal check for whether given truncation down into KeptBits would be truncating or not: (add x, (1 << (KeptBits-1))) srccond (1 << KeptBits) Into it's more traditional form: ((x << C) a>> C) dstcond x Return true if we should transform.
virtual bool shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd (SDValue X, ConstantSDNode *XC, ConstantSDNode *CC, SDValue Y, unsigned OldShiftOpcode, unsigned NewShiftOpcode, SelectionDAG &DAG) const
Given the pattern (X & (C l>>/<< Y)) ==/!= 0 return true if it should be transformed into: ((X <</l>> Y) & C) ==/!= 0 WARNING: if 'X' is a constant, the fold may deadlock! FIXME: we could avoid passing XC, but we can't use isConstOrConstSplat() here because it can end up being not linked in.
virtual bool optimizeFMulOrFDivAsShiftAddBitcast (SDNode *N, SDValue FPConst, SDValue IntPow2) const
virtual unsigned preferedOpcodeForCmpEqPiecesOfOperand (EVT VT, unsigned ShiftOpc, bool MayTransformRotate, const APInt &ShiftOrRotateAmt, const std::optional< APInt > &AndMask) const
virtual bool preferIncOfAddToSubOfNot (EVT VT) const
These two forms are equivalent: sub y, (xor x, -1) add (add x, 1), y The variant with two add's is IR-canonical.
virtual bool preferABDSToABSWithNSW (EVT VT) const
virtual bool preferScalarizeSplat (SDNode *N) const
virtual bool preferSextInRegOfTruncate (EVT TruncVT, EVT VT, EVT ExtVT) const
bool enableExtLdPromotion () const
Return true if the target wants to use the optimization that turns ext(promotableInst1(...(promotableInstN(load)))) into promotedInst1(...(promotedInstN(ext(load)))).
virtual bool canCombineStoreAndExtract (Type *VectorTy, Value *Idx, unsigned &Cost) const
Return true if the target can combine store(extractelement VectorTy, Idx).
virtual bool shallExtractConstSplatVectorElementToStore (Type *VectorTy, unsigned ElemSizeInBits, unsigned &Index) const
Return true if the target shall perform extract vector element and store given that the vector is known to be splat of constant.
virtual bool shouldSplatInsEltVarIndex (EVT) const
Return true if inserting a scalar into a variable element of an undef vector is more efficiently handled by splatting the scalar instead.
virtual bool enableAggressiveFMAFusion (EVT VT) const
Return true if target always benefits from combining into FMA for a given value type.
virtual bool enableAggressiveFMAFusion (LLT Ty) const
Return true if target always benefits from combining into FMA for a given value type.
virtual EVT getSetCCResultType (const DataLayout &DL, LLVMContext &Context, EVT VT) const
Return the ValueType of the result of SETCC operations.
virtual MVT::SimpleValueType getCmpLibcallReturnType () const
Return the ValueType for comparison libcalls.
BooleanContent getBooleanContents (bool isVec, bool isFloat) const
For targets without i1 registers, this gives the nature of the high-bits of boolean values held in types wider than i1.
BooleanContent getBooleanContents (EVT Type) const
SDValue promoteTargetBoolean (SelectionDAG &DAG, SDValue Bool, EVT ValVT) const
Promote the given target boolean to a target boolean of the given type.
Sched::Preference getSchedulingPreference () const
Return target scheduling preference.
virtual Sched::Preference getSchedulingPreference (SDNode *) const
Some scheduler, e.g.
virtual const TargetRegisterClass * getRegClassFor (MVT VT, bool isDivergent=false) const
Return the register class that should be used for the specified value type.
virtual bool requiresUniformRegister (MachineFunction &MF, const Value *) const
Allows target to decide about the register class of the specific value that is live outside the defining block.
virtual const TargetRegisterClass * getRepRegClassFor (MVT VT) const
Return the 'representative' register class for the specified value type.
virtual uint8_t getRepRegClassCostFor (MVT VT) const
Return the cost of the 'representative' register class for the specified value type.
virtual ShiftLegalizationStrategy preferredShiftLegalizationStrategy (SelectionDAG &DAG, SDNode *N, unsigned ExpansionFactor) const
bool isTypeLegal (EVT VT) const
Return true if the target has native support for the specified value type.
const ValueTypeActionImpl & getValueTypeActions () const
LegalizeKind getTypeConversion (LLVMContext &Context, EVT VT) const
Return pair that represents the legalization kind (first) that needs to happen to EVT (second) in order to type-legalize it.
LegalizeTypeAction getTypeAction (LLVMContext &Context, EVT VT) const
Return how we should legalize values of this type, either it is already legal (return 'Legal') or we need to promote it to a larger type (return 'Promote'), or we need to expand it into multiple registers of smaller integer type (return 'Expand').
LegalizeTypeAction getTypeAction (MVT VT) const
virtual EVT getTypeToTransformTo (LLVMContext &Context, EVT VT) const
For types supported by the target, this is an identity function.
EVT getTypeToExpandTo (LLVMContext &Context, EVT VT) const
For types supported by the target, this is an identity function.
unsigned getVectorTypeBreakdown (LLVMContext &Context, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
Vector types are broken down into some number of legal first class types.
virtual unsigned getVectorTypeBreakdownForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
Certain targets such as MIPS require that some types such as vectors are always broken down into scalars in some contexts.
virtual bool getTgtMemIntrinsic (IntrinsicInfo &, const CallInst &, MachineFunction &, unsigned) const
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory).
virtual bool isFPImmLegal (const APFloat &, EVT, bool ForCodeSize=false) const
Returns true if the target can instruction select the specified FP immediate natively.
virtual bool isShuffleMaskLegal (ArrayRef< int >, EVT) const
Targets can use this to indicate that they only support some VECTOR_SHUFFLE operations, those with specific masks.
virtual bool canOpTrap (unsigned Op, EVT VT) const
Returns true if the operation can trap for the value type.
virtual bool isVectorClearMaskLegal (ArrayRef< int >, EVT) const
Similar to isShuffleMaskLegal.
virtual LegalizeAction getCustomOperationAction (SDNode &Op) const
How to legalize this custom operation?
LegalizeAction getOperationAction (unsigned Op, EVT VT) const
Return how this operation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
virtual bool isSupportedFixedPointOperation (unsigned Op, EVT VT, unsigned Scale) const
Custom method defined by each target to indicate if an operation which may require a scale is supported natively by the target.
LegalizeAction getFixedPointOperationAction (unsigned Op, EVT VT, unsigned Scale) const
Some fixed point operations may be natively supported by the target but only for specific scales.
LegalizeAction getStrictFPOperationAction (unsigned Op, EVT VT) const
bool isOperationLegalOrCustom (unsigned Op, EVT VT, bool LegalOnly=false) const
Return true if the specified operation is legal on this target or can be made legal with custom lowering.
bool isOperationLegalOrPromote (unsigned Op, EVT VT, bool LegalOnly=false) const
Return true if the specified operation is legal on this target or can be made legal using promotion.
bool isOperationLegalOrCustomOrPromote (unsigned Op, EVT VT, bool LegalOnly=false) const
Return true if the specified operation is legal on this target or can be made legal with custom lowering or using promotion.
bool isOperationCustom (unsigned Op, EVT VT) const
Return true if the operation uses custom lowering, regardless of whether the type is legal or not.
virtual bool areJTsAllowed (const Function *Fn) const
Return true if lowering to a jump table is allowed.
bool rangeFitsInWord (const APInt &Low, const APInt &High, const DataLayout &DL) const
Check whether the range [Low,High] fits in a machine word.
virtual bool isSuitableForJumpTable (const SwitchInst *SI, uint64_t NumCases, uint64_t Range, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const
Return true if lowering to a jump table is suitable for a set of case clusters which may contain NumCases cases, Range range of values.
virtual MVT getPreferredSwitchConditionType (LLVMContext &Context, EVT ConditionVT) const
Returns preferred type for switch condition.
bool isSuitableForBitTests (unsigned NumDests, unsigned NumCmps, const APInt &Low, const APInt &High, const DataLayout &DL) const
Return true if lowering to a bit test is suitable for a set of case clusters which contains NumDests unique destinations, Low and High as its lowest and highest case values, and expects NumCmps case value comparisons.
bool isOperationExpand (unsigned Op, EVT VT) const
Return true if the specified operation is illegal on this target or unlikely to be made legal with custom lowering.
bool isOperationLegal (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target.
LegalizeAction getLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return how this load with extension should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal on this target.
bool isLoadExtLegalOrCustom (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal or custom on this target.
LegalizeAction getTruncStoreAction (EVT ValVT, EVT MemVT) const
Return how this store with truncation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isTruncStoreLegal (EVT ValVT, EVT MemVT) const
Return true if the specified store with truncation is legal on this target.
bool isTruncStoreLegalOrCustom (EVT ValVT, EVT MemVT) const
Return true if the specified store with truncation has solution on this target.
virtual bool canCombineTruncStore (EVT ValVT, EVT MemVT, bool LegalOnly) const
LegalizeAction getIndexedLoadAction (unsigned IdxMode, MVT VT) const
Return how the indexed load should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedStoreAction (unsigned IdxMode, MVT VT) const
Return how the indexed store should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedMaskedLoadAction (unsigned IdxMode, MVT VT) const
Return how the indexed load should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedMaskedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedMaskedStoreAction (unsigned IdxMode, MVT VT) const
Return how the indexed store should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedMaskedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
virtual bool shouldExtendGSIndex (EVT VT, EVT &EltTy) const
Returns true if the index type for a masked gather/scatter requires extending.
virtual bool shouldRemoveExtendFromGSIndex (SDValue Extend, EVT DataVT) const
virtual bool isLegalScaleForGatherScatter (uint64_t Scale, uint64_t ElemSize) const
LegalizeAction getCondCodeAction (ISD::CondCode CC, MVT VT) const
Return how the condition code should be treated: either it is legal, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isCondCodeLegal (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal on this target.
bool isCondCodeLegalOrCustom (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal or custom on this target.
MVT getTypeToPromoteTo (unsigned Op, MVT VT) const
If the action for this operation is to promote, this method returns the ValueType to promote to.
virtual EVT getAsmOperandValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
EVT getValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
Return the EVT corresponding to this LLVM type.
EVT getMemValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
MVT getSimpleValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
Return the MVT corresponding to this LLVM type. See getValueType.
virtual uint64_t getByValTypeAlignment (Type *Ty, const DataLayout &DL) const
Return the desired alignment for ByVal or InAlloca aggregate function arguments in the caller parameter area.
MVT getRegisterType (MVT VT) const
Return the type of registers that this ValueType will eventually require.
MVT getRegisterType (LLVMContext &Context, EVT VT) const
Return the type of registers that this ValueType will eventually require.
virtual unsigned getNumRegisters (LLVMContext &Context, EVT VT, std::optional< MVT > RegisterVT=std::nullopt) const
Return the number of registers that this ValueType will eventually require.
virtual MVT getRegisterTypeForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT) const
Certain combinations of ABIs, Targets and features require that types are legal for some operations and not for other operations.
virtual unsigned getNumRegistersForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT) const
Certain targets require unusual breakdowns of certain types.
virtual Align getABIAlignmentForCallingConv (Type *ArgTy, const DataLayout &DL) const
Certain targets have context sensitive alignment requirements, where one type has the alignment requirement of another type.
virtual bool ShouldShrinkFPConstant (EVT) const
If true, then instruction selection should seek to shrink the FP constant of the specified type to a smaller type in order to save space and / or reduce runtime.
virtual bool shouldReduceLoadWidth (SDNode *Load, ISD::LoadExtType ExtTy, EVT NewVT) const
Return true if it is profitable to reduce a load to a smaller type.
virtual bool shouldRemoveRedundantExtend (SDValue Op) const
Return true (the default) if it is profitable to remove a sext_inreg(x) where the sext is redundant, and use x directly.
bool hasBigEndianPartOrdering (EVT VT, const DataLayout &DL) const
When splitting a value of the specified type into parts, does the Lo or Hi part come first? This usually follows the endianness, except for ppcf128, where the Hi part always comes first.
bool hasTargetDAGCombine (ISD::NodeType NT) const
If true, the target has custom DAG combine transformations that it can perform for the specified node.
unsigned getGatherAllAliasesMaxDepth () const
virtual unsigned getVaListSizeInBits (const DataLayout &DL) const
Returns the size of the platform's va_list object.
unsigned getMaxStoresPerMemset (bool OptSize) const
Get maximum # of store operations permitted for llvm.memset.
unsigned getMaxStoresPerMemcpy (bool OptSize) const
Get maximum # of store operations permitted for llvm.memcpy.
virtual unsigned getMaxGluedStoresPerMemcpy () const
Get maximum # of store operations to be glued together.
unsigned getMaxExpandSizeMemcmp (bool OptSize) const
Get maximum # of load operations permitted for memcmp.
unsigned getMaxStoresPerMemmove (bool OptSize) const
Get maximum # of store operations permitted for llvm.memmove.
virtual bool allowsMisalignedMemoryAccesses (EVT, unsigned AddrSpace=0, Align Alignment=Align(1), MachineMemOperand::Flags Flags=MachineMemOperand::MONone, unsigned *=nullptr) const
Determine if the target supports unaligned memory accesses.
virtual bool allowsMisalignedMemoryAccesses (LLT, unsigned AddrSpace=0, Align Alignment=Align(1), MachineMemOperand::Flags Flags=MachineMemOperand::MONone, unsigned *=nullptr) const
LLT handling variant.
bool allowsMemoryAccessForAlignment (LLVMContext &Context, const DataLayout &DL, EVT VT, unsigned AddrSpace=0, Align Alignment=Align(1), MachineMemOperand::Flags Flags=MachineMemOperand::MONone, unsigned *Fast=nullptr) const
This function returns true if the memory access is aligned or if the target allows this specific unaligned memory access.
bool allowsMemoryAccessForAlignment (LLVMContext &Context, const DataLayout &DL, EVT VT, const MachineMemOperand &MMO, unsigned *Fast=nullptr) const
Return true if the memory access of this type is aligned or if the target allows this specific unaligned access for the given MachineMemOperand.
virtual bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, EVT VT, unsigned AddrSpace=0, Align Alignment=Align(1), MachineMemOperand::Flags Flags=MachineMemOperand::MONone, unsigned *Fast=nullptr) const
Return true if the target supports a memory access of this type for the given address space and alignment.
bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, EVT VT, const MachineMemOperand &MMO, unsigned *Fast=nullptr) const
Return true if the target supports a memory access of this type for the given MachineMemOperand.
bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, LLT Ty, const MachineMemOperand &MMO, unsigned *Fast=nullptr) const
LLT handling variant.
virtual EVT getOptimalMemOpType (const MemOp &Op, const AttributeList &) const
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
virtual LLT getOptimalMemOpLLT (const MemOp &Op, const AttributeList &) const
LLT returning variant.
virtual bool isSafeMemOpType (MVT) const
Returns true if it's safe to use load / store of the specified type to expand memcpy / memset inline.
virtual unsigned getMinimumJumpTableEntries () const
Return lower limit for number of blocks in a jump table.
unsigned getMinimumJumpTableDensity (bool OptForSize) const
Return lower limit of the density in a jump table.
unsigned getMaximumJumpTableSize () const
Return upper limit for number of entries in a jump table.
virtual bool isJumpTableRelative () const
Register getStackPointerRegisterToSaveRestore () const
If a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
virtual Register getExceptionPointerRegister (const Constant *PersonalityFn) const
If a physical register, this returns the register that receives the exception address on entry to an EH pad.
virtual Register getExceptionSelectorRegister (const Constant *PersonalityFn) const
If a physical register, this returns the register that receives the exception typeid on entry to a landing pad.
virtual bool needsFixedCatchObjects () const
Align getMinStackArgumentAlignment () const
Return the minimum stack alignment of an argument.
Align getMinFunctionAlignment () const
Return the minimum function alignment.
Align getPrefFunctionAlignment () const
Return the preferred function alignment.
virtual Align getPrefLoopAlignment (MachineLoop *ML=nullptr) const
Return the preferred loop alignment.
virtual unsigned getMaxPermittedBytesForAlignment (MachineBasicBlock *MBB) const
Return the maximum amount of bytes allowed to be emitted when padding for alignment.
virtual bool alignLoopsWithOptSize () const
Should loops be aligned even when the function is marked OptSize (but not MinSize).
virtual Value * getIRStackGuard (IRBuilderBase &IRB) const
If the target has a standard location for the stack protector guard, returns the address of that location.
virtual void insertSSPDeclarations (Module &M) const
Inserts necessary declarations for SSP (stack protection) purpose.
virtual Value * getSDagStackGuard (const Module &M) const
Return the variable that's previously inserted by insertSSPDeclarations, if any, otherwise return nullptr.
virtual bool useStackGuardXorFP () const
If this function returns true, stack protection checks should XOR the frame pointer (or whichever pointer is used to address locals) into the stack guard value before checking it.
virtual Function * getSSPStackGuardCheck (const Module &M) const
If the target has a standard stack protection check function that performs validation and error handling, returns the function.
virtual Value * getSafeStackPointerLocation (IRBuilderBase &IRB) const
Returns the target-specific address of the unsafe stack pointer.
virtual bool hasStackProbeSymbol (const MachineFunction &MF) const
Returns the name of the symbol used to emit stack probes or the empty string if not applicable.
virtual bool hasInlineStackProbe (const MachineFunction &MF) const
virtual StringRef getStackProbeSymbolName (const MachineFunction &MF) const
virtual bool isFreeAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast from SrcAS to DestAS is "cheap", such that e.g.
virtual bool shouldAlignPointerArgs (CallInst *, unsigned &, Align &) const
Return true if the pointer arguments to CI should be aligned by aligning the object whose address is being passed.
virtual void emitAtomicCmpXchgNoStoreLLBalance (IRBuilderBase &Builder) const
virtual bool shouldSignExtendTypeInLibCall (EVT Type, bool IsSigned) const
Returns true if arguments should be sign-extended in lib calls.
virtual bool shouldExtendTypeInLibCall (EVT Type) const
Returns true if arguments should be extended in lib calls.
virtual AtomicExpansionKind shouldExpandAtomicLoadInIR (LoadInst *LI) const
Returns how the given (atomic) load should be expanded by the IR-level AtomicExpand pass.
virtual AtomicExpansionKind shouldCastAtomicLoadInIR (LoadInst *LI) const
Returns how the given (atomic) load should be cast by the IR-level AtomicExpand pass.
virtual AtomicExpansionKind shouldExpandAtomicStoreInIR (StoreInst *SI) const
Returns how the given (atomic) store should be expanded by the IR-level AtomicExpand pass into.
virtual AtomicExpansionKind shouldCastAtomicStoreInIR (StoreInst *SI) const
Returns how the given (atomic) store should be cast by the IR-level AtomicExpand pass into.
virtual AtomicExpansionKind shouldExpandAtomicCmpXchgInIR (AtomicCmpXchgInst *AI) const
Returns how the given atomic cmpxchg should be expanded by the IR-level AtomicExpand pass.
virtual AtomicExpansionKind shouldExpandAtomicRMWInIR (AtomicRMWInst *RMW) const
Returns how the IR-level AtomicExpand pass should expand the given AtomicRMW, if at all.
virtual AtomicExpansionKind shouldCastAtomicRMWIInIR (AtomicRMWInst *RMWI) const
Returns how the given atomic atomicrmw should be cast by the IR-level AtomicExpand pass.
virtual LoadInst * lowerIdempotentRMWIntoFencedLoad (AtomicRMWInst *RMWI) const
On some platforms, an AtomicRMW that never actually modifies the value (such as fetch_add of 0) can be turned into a fence followed by an atomic load.
virtual ISD::NodeType getExtendForAtomicOps () const
Returns how the platform's atomic operations are extended (ZERO_EXTEND, SIGN_EXTEND, or ANY_EXTEND).
virtual ISD::NodeType getExtendForAtomicCmpSwapArg () const
Returns how the platform's atomic compare and swap expects its comparison value to be extended (ZERO_EXTEND, SIGN_EXTEND, or ANY_EXTEND).
virtual bool shouldNormalizeToSelectSequence (LLVMContext &Context, EVT VT) const
Returns true if we should normalize select(N0&N1, X, Y) => select(N0, select(N1, X, Y), Y) and select(N0|N1, X, Y) => select(N0, select(N1, X, Y, Y)) if it is likely that it saves us from materializing N0 and N1 in an integer register.
virtual bool isProfitableToCombineMinNumMaxNum (EVT VT) const
virtual bool convertSelectOfConstantsToMath (EVT VT) const
Return true if a select of constants (select Cond, C1, C2) should be transformed into simple math ops with the condition value.
virtual bool decomposeMulByConstant (LLVMContext &Context, EVT VT, SDValue C) const
Return true if it is profitable to transform an integer multiplication-by-constant into simpler operations like shifts and adds.
virtual bool isMulAddWithConstProfitable (SDValue AddNode, SDValue ConstNode) const
Return true if it may be profitable to transform (mul (add x, c1), c2) -> (add (mul x, c2), c1*c2).
virtual bool shouldUseStrictFP_TO_INT (EVT FpVT, EVT IntVT, bool IsSigned) const
Return true if it is more correct/profitable to use strict FP_TO_INT conversion operations - canonicalizing the FP source value instead of converting all cases and then selecting based on value.
bool isBeneficialToExpandPowI (int64_t Exponent, bool OptForSize) const
Return true if it is beneficial to expand an @llvm.powi.
virtual bool getAddrModeArguments (IntrinsicInst *, SmallVectorImpl< Value * > &, Type *&) const
CodeGenPrepare sinks address calculations into the same BB as Load/Store instructions reading the address.
virtual bool isLegalAddressingMode (const DataLayout &DL, const AddrMode &AM, Type *Ty, unsigned AddrSpace, Instruction *I=nullptr) const
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
virtual int64_t getPreferredLargeGEPBaseOffset (int64_t MinOffset, int64_t MaxOffset) const
Return the prefered common base offset.
virtual bool isLegalICmpImmediate (int64_t) const
Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
virtual bool isLegalAddImmediate (int64_t) const
Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register with the immediate without having to materialize the immediate into a register.
virtual bool isLegalStoreImmediate (int64_t Value) const
Return true if the specified immediate is legal for the value input of a store instruction.
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
Return true if it's significantly cheaper to shift a vector by a uniform scalar than by an amount which will vary across each lane.
virtual Type * shouldConvertSplatType (ShuffleVectorInst *SVI) const
Given a shuffle vector SVI representing a vector splat, return a new scalar type of size equal to SVI's scalar type if the new type is more profitable.
virtual bool shouldConvertPhiType (Type *From, Type *To) const
Given a set in interconnected phis of type 'From' that are loaded/stored or bitcast to type 'To', return true if the set should be converted to 'To'.
virtual bool isCommutativeBinOp (unsigned Opcode) const
Returns true if the opcode is a commutative binary operation.
virtual bool isBinOp (unsigned Opcode) const
Return true if the node is a math/logic binary operator.
virtual bool isTruncateFree (Type *FromTy, Type *ToTy) const
Return true if it's free to truncate a value of type FromTy to type ToTy.
virtual bool allowTruncateForTailCall (Type *FromTy, Type *ToTy) const
Return true if a truncation from FromTy to ToTy is permitted when deciding whether a call is in tail position.
virtual bool isTruncateFree (EVT FromVT, EVT ToVT) const
virtual bool isTruncateFree (LLT FromTy, LLT ToTy, const DataLayout &DL, LLVMContext &Ctx) const
virtual bool isTruncateFree (SDValue Val, EVT VT2) const
Return true if truncating the specific node Val to type VT2 is free.
virtual bool isProfitableToHoist (Instruction *I) const
bool isExtFree (const Instruction *I) const
Return true if the extension represented by I is free.
bool isExtLoad (const LoadInst *Load, const Instruction *Ext, const DataLayout &DL) const
Return true if Load and Ext can form an ExtLoad.
virtual bool isZExtFree (Type *FromTy, Type *ToTy) const
Return true if any actual instruction that defines a value of type FromTy implicitly zero-extends the value to ToTy in the result register.
virtual bool isZExtFree (EVT FromTy, EVT ToTy) const
virtual bool isZExtFree (LLT FromTy, LLT ToTy, const DataLayout &DL, LLVMContext &Ctx) const
virtual bool isZExtFree (SDValue Val, EVT VT2) const
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
virtual bool isSExtCheaperThanZExt (EVT FromTy, EVT ToTy) const
Return true if sign-extension from FromTy to ToTy is cheaper than zero-extension.
virtual bool signExtendConstant (const ConstantInt *C) const
Return true if this constant should be sign extended when promoting to a larger type.
virtual bool shouldSinkOperands (Instruction *I, SmallVectorImpl< Use * > &Ops) const
Return true if sinking I's operands to the same basic block as I is profitable, e.g.
virtual bool optimizeExtendOrTruncateConversion (Instruction *I, Loop *L, const TargetTransformInfo &TTI) const
Try to optimize extending or truncating conversion instructions (like zext, trunc, fptoui, uitofp) for the target.
virtual bool hasPairedLoad (EVT, Align &) const
Return true if the target supplies and combines to a paired load two loaded values of type LoadedType next to each other in memory.
virtual bool hasVectorBlend () const
Return true if the target has a vector blend instruction.
virtual unsigned getMaxSupportedInterleaveFactor () const
Get the maximum supported factor for interleaved memory accesses.
virtual bool lowerInterleavedLoad (LoadInst *LI, ArrayRef< ShuffleVectorInst * > Shuffles, ArrayRef< unsigned > Indices, unsigned Factor) const
Lower an interleaved load to target specific intrinsics.
virtual bool lowerInterleavedStore (StoreInst *SI, ShuffleVectorInst *SVI, unsigned Factor) const
Lower an interleaved store to target specific intrinsics.
virtual bool lowerDeinterleaveIntrinsicToLoad (IntrinsicInst *DI, LoadInst *LI) const
Lower a deinterleave intrinsic to a target specific load intrinsic.
virtual bool lowerInterleaveIntrinsicToStore (IntrinsicInst *II, StoreInst *SI) const
Lower an interleave intrinsic to a target specific store intrinsic.
virtual bool isFPExtFree (EVT DestVT, EVT SrcVT) const
Return true if an fpext operation is free (for instance, because single-precision floating-point numbers are implicitly extended to double-precision).
virtual bool isFPExtFoldable (const MachineInstr &MI, unsigned Opcode, LLT DestTy, LLT SrcTy) const
Return true if an fpext operation input to an Opcode operation is free (for instance, because half-precision floating-point numbers are implicitly extended to float-precision) for an FMA instruction.
virtual bool isFPExtFoldable (const SelectionDAG &DAG, unsigned Opcode, EVT DestVT, EVT SrcVT) const
Return true if an fpext operation input to an Opcode operation is free (for instance, because half-precision floating-point numbers are implicitly extended to float-precision) for an FMA instruction.
virtual bool isVectorLoadExtDesirable (SDValue ExtVal) const
Return true if folding a vector load into ExtVal (a sign, zero, or any extend node) is profitable.
virtual bool isFNegFree (EVT VT) const
Return true if an fneg operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
virtual bool isFAbsFree (EVT VT) const
Return true if an fabs operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
virtual bool isFMAFasterThanFMulAndFAdd (const MachineFunction &MF, EVT) const
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
virtual bool isFMAFasterThanFMulAndFAdd (const MachineFunction &MF, LLT) const
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
virtual bool isFMAFasterThanFMulAndFAdd (const Function &F, Type *) const
IR version.
virtual bool isFMADLegal (const MachineInstr &MI, LLT Ty) const
Returns true if MI can be combined with another instruction to form TargetOpcode::G_FMAD.
virtual bool isFMADLegal (const SelectionDAG &DAG, const SDNode *N) const
Returns true if be combined with to form an ISD::FMAD.
virtual bool generateFMAsInMachineCombiner (EVT VT, CodeGenOptLevel OptLevel) const
virtual bool isNarrowingProfitable (EVT SrcVT, EVT DestVT) const
Return true if it's profitable to narrow operations of type SrcVT to DestVT.
virtual bool shouldFoldSelectWithIdentityConstant (unsigned BinOpcode, EVT VT) const
Return true if pulling a binary operation into a select with an identity constant is profitable.
virtual bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const
Return true if it is beneficial to convert a load of a constant to just the constant itself.
virtual bool isExtractSubvectorCheap (EVT ResVT, EVT SrcVT, unsigned Index) const
Return true if EXTRACT_SUBVECTOR is cheap for extracting this result type from this source type with this index.
virtual bool shouldScalarizeBinop (SDValue VecOp) const
Try to convert an extract element of a vector binary operation into an extract element followed by a scalar operation.
virtual bool isExtractVecEltCheap (EVT VT, unsigned Index) const
Return true if extraction of a scalar element from the given vector type at the given index is cheap.
virtual bool shouldFormOverflowOp (unsigned Opcode, EVT VT, bool MathUsed) const
Try to convert math with an overflow comparison into the corresponding DAG node operation.
virtual bool aggressivelyPreferBuildVectorSources (EVT VecVT) const
virtual bool shouldConsiderGEPOffsetSplit () const
virtual bool shouldAvoidTransformToShift (EVT VT, unsigned Amount) const
Return true if creating a shift of the type by the given amount is not profitable.
virtual bool shouldFoldSelectWithSingleBitTest (EVT VT, const APInt &AndMask) const
virtual bool shouldKeepZExtForFP16Conv () const
Does this target require the clearing of high-order bits in a register passed to the fp16 to fp conversion library function.
virtual bool shouldConvertFpToSat (unsigned Op, EVT FPVT, EVT VT) const
Should we generate fp_to_si_sat and fp_to_ui_sat from type FPVT to type VT from min(max(fptoi)) saturation patterns.
virtual bool isComplexDeinterleavingSupported () const
Does this target support complex deinterleaving.
virtual bool isComplexDeinterleavingOperationSupported (ComplexDeinterleavingOperation Operation, Type *Ty) const
Does this target support complex deinterleaving with the given operation and type.
virtual Value * createComplexDeinterleavingIR (IRBuilderBase &B, ComplexDeinterleavingOperation OperationType, ComplexDeinterleavingRotation Rotation, Value *InputA, Value *InputB, Value *Accumulator=nullptr) const
Create the IR node for the given complex deinterleaving operation.
void setLibcallName (RTLIB::Libcall Call, const char *Name)
Rename the default libcall routine name for the specified libcall.
void setLibcallName (ArrayRef< RTLIB::Libcall > Calls, const char *Name)
const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
void setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC)
Override the default CondCode to be used to test the result of the comparison libcall against zero.
ISD::CondCode getCmpLibcallCC (RTLIB::Libcall Call) const
Get the CondCode that's to be used to test the result of the comparison libcall against zero.
void setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC)
Set the CallingConv that should be used for the specified libcall.
CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
Get the CallingConv that should be used for the specified libcall.
virtual void finalizeLowering (MachineFunction &MF) const
Execute target specific actions to finalize target lowering.
virtual bool shouldLocalize (const MachineInstr &MI, const TargetTransformInfo *TTI) const
Check whether or not MI needs to be moved close to its uses.
int InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
unsigned getMaxAtomicSizeInBitsSupported () const
Returns the maximum atomic operation size (in bits) supported by the backend.
unsigned getMaxDivRemBitWidthSupported () const
Returns the size in bits of the maximum div/rem the backend supports.
unsigned getMaxLargeFPConvertBitWidthSupported () const
Returns the size in bits of the maximum larget fp convert the backend supports.
unsigned getMinCmpXchgSizeInBits () const
Returns the size of the smallest cmpxchg or ll/sc instruction the backend supports.
bool supportsUnalignedAtomics () const
Whether the target supports unaligned atomic operations.
virtual bool shouldInsertFencesForAtomic (const Instruction *I) const
Whether AtomicExpandPass should automatically insert fences and reduce ordering for this atomic.
virtual bool shouldInsertTrailingFenceForAtomicStore (const Instruction *I) const
Whether AtomicExpandPass should automatically insert a trailing fence without reducing the ordering for this atomic.
virtual Value * emitMaskedAtomicRMWIntrinsic (IRBuilderBase &Builder, AtomicRMWInst *AI, Value *AlignedAddr, Value *Incr, Value *Mask, Value *ShiftAmt, AtomicOrdering Ord) const
Perform a masked atomicrmw using a target-specific intrinsic.
virtual void emitExpandAtomicRMW (AtomicRMWInst *AI) const
Perform a atomicrmw expansion using a target-specific way.
virtual void emitBitTestAtomicRMWIntrinsic (AtomicRMWInst *AI) const
Perform a bit test atomicrmw using a target-specific intrinsic.
virtual void emitCmpArithAtomicRMWIntrinsic (AtomicRMWInst *AI) const
Perform a atomicrmw which the result is only used by comparison, using a target-specific intrinsic.
virtual Value * emitMaskedAtomicCmpXchgIntrinsic (IRBuilderBase &Builder, AtomicCmpXchgInst *CI, Value *AlignedAddr, Value *CmpVal, Value *NewVal, Value *Mask, AtomicOrdering Ord) const
Perform a masked cmpxchg using a target-specific intrinsic.
virtual MachineInstr * EmitKCFICheck (MachineBasicBlock &MBB, MachineBasicBlock::instr_iterator &MBBI, const TargetInstrInfo *TII) const
virtual Instruction * emitLeadingFence (IRBuilderBase &Builder, Instruction *Inst, AtomicOrdering Ord) const
Inserts in the IR a target-specific intrinsic specifying a fence.
virtual Instruction * emitTrailingFence (IRBuilderBase &Builder, Instruction *Inst, AtomicOrdering Ord) const
Additional Inherited Members
Public Types inherited from llvm::TargetLowering
enum ConstraintType {
C_Register , C_RegisterClass , C_Memory , C_Address ,
C_Immediate , C_Other , C_Unknown
}
enum ConstraintWeight {
CW_Invalid = -1 , CW_Okay = 0 , CW_Good = 1 , CW_Better = 2 ,
CW_Best = 3 , CW_SpecificReg = CW_Okay , CW_Register = CW_Good , CW_Memory = CW_Better ,
CW_Constant = CW_Best , CW_Default = CW_Okay
}
using AsmOperandInfoVector = std::vector< AsmOperandInfo >
using ConstraintPair = std::pair< StringRef, TargetLowering::ConstraintType >
using ConstraintGroup = SmallVector< ConstraintPair >
Public Types inherited from llvm::TargetLoweringBase
enum LegalizeAction : uint8_t {
Legal , Promote , Expand , LibCall ,
Custom
}
This enum indicates whether operations are valid for a target, and if not, what action should be used to make them valid.
enum LegalizeTypeAction : uint8_t {
TypeLegal , TypePromoteInteger , TypeExpandInteger , TypeSoftenFloat ,
TypeExpandFloat , TypeScalarizeVector , TypeSplitVector , TypeWidenVector ,
TypePromoteFloat , TypeSoftPromoteHalf , TypeScalarizeScalableVector
}
This enum indicates whether a types are legal for a target, and if not, what action should be used to make them valid.
enum BooleanContent { UndefinedBooleanContent , ZeroOrOneBooleanContent , ZeroOrNegativeOneBooleanContent }
Enum that describes how the target represents true/false values.
enum SelectSupportKind { ScalarValSelect , ScalarCondVectorVal , VectorMaskSelect }
Enum that describes what type of support for selects the target has.
enum class AtomicExpansionKind {
None , CastToInteger , LLSC , LLOnly ,
CmpXChg , MaskedIntrinsic , BitTestIntrinsic , CmpArithIntrinsic ,
Expand , NotAtomic
}
Enum that specifies what an atomic load/AtomicRMWInst is expanded to, if at all.
enum class MulExpansionKind { Always , OnlyLegalOrCustom }
Enum that specifies when a multiplication should be expanded.
enum class NegatibleCost { Cheaper = 0 , Neutral = 1 , Expensive = 2 }
Enum that specifies when a float negation is beneficial.
enum AndOrSETCCFoldKind : uint8_t { None = 0 , AddAnd = 1 , NotAnd = 2 , ABS = 4 }
Enum of different potentially desirable ways to fold (and/or (setcc ...), (setcc ...)).
enum ReciprocalEstimate : int { Unspecified = -1 , Disabled = 0 , Enabled = 1 }
Reciprocal estimate status values used by the functions below.
enum class ShiftLegalizationStrategy { ExpandToParts , ExpandThroughStack , LowerToLibcall }
Return the preferred strategy to legalize tihs SHIFT instruction, with ExpansionFactor being the recursion depth - how many expansion needed.
using LegalizeKind = std::pair< LegalizeTypeAction, EVT >
LegalizeKind holds the legalization kind that needs to happen to EVT in order to type-legalize it.
using ArgListTy = std::vector< ArgListEntry >
Static Public Member Functions inherited from llvm::TargetLoweringBase
static ISD::NodeType getExtendForContent (BooleanContent Content)
Protected Member Functions inherited from llvm::TargetLoweringBase
void initActions ()
Initialize all of the actions to default values.
Value * getDefaultSafeStackPointerLocation (IRBuilderBase &IRB, bool UseTLS) const
void setBooleanContents (BooleanContent Ty)
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
void setBooleanContents (BooleanContent IntTy, BooleanContent FloatTy)
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
void setBooleanVectorContents (BooleanContent Ty)
Specify how the target extends the result of a vector boolean value from a vector of i1 to a wider type.
void setSchedulingPreference (Sched::Preference Pref)
Specify the target scheduling preference.
void setMinimumJumpTableEntries (unsigned Val)
Indicate the minimum number of blocks to generate jump tables.
void setMaximumJumpTableSize (unsigned)
Indicate the maximum number of entries in jump tables.
void setStackPointerRegisterToSaveRestore (Register R)
If set to a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
void setHasMultipleConditionRegisters (bool hasManyRegs=true)
Tells the code generator that the target has multiple (allocatable) condition registers that can be used to store the results of comparisons for use by selects and conditional branches.
void setHasExtractBitsInsn (bool hasExtractInsn=true)
Tells the code generator that the target has BitExtract instructions.
void setJumpIsExpensive (bool isExpensive=true)
Tells the code generator not to expand logic operations on comparison predicates into separate sequences that increase the amount of flow control.
void addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth)
Tells the code generator which bitwidths to bypass.
void addRegisterClass (MVT VT, const TargetRegisterClass *RC)
Add the specified register class as an available regclass for the specified value type.
virtual std::pair< const TargetRegisterClass *, uint8_t > findRepresentativeClass (const TargetRegisterInfo *TRI, MVT VT) const
Return the largest legal super-reg register class of the register class for the specified type and its associated "cost".
void computeRegisterProperties (const TargetRegisterInfo *TRI)
Once all of the register classes are added, this allows us to compute derived properties we expose.
void setOperationAction (unsigned Op, MVT VT, LegalizeAction Action)
Indicate that the specified operation does not work with the specified type and indicate what to do about it.
void setOperationAction (ArrayRef< unsigned > Ops, MVT VT, LegalizeAction Action)
void setOperationAction (ArrayRef< unsigned > Ops, ArrayRef< MVT > VTs, LegalizeAction Action)
void setLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action)
Indicate that the specified load with extension does not work with the specified type and indicate what to do about it.
void setLoadExtAction (ArrayRef< unsigned > ExtTypes, MVT ValVT, MVT MemVT, LegalizeAction Action)
void setLoadExtAction (ArrayRef< unsigned > ExtTypes, MVT ValVT, ArrayRef< MVT > MemVTs, LegalizeAction Action)
void setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action)
Indicate that the specified truncating store does not work with the specified type and indicate what to do about it.
void setIndexedLoadAction (ArrayRef< unsigned > IdxModes, MVT VT, LegalizeAction Action)
Indicate that the specified indexed load does or does not work with the specified type and indicate what to do abort it.
void setIndexedLoadAction (ArrayRef< unsigned > IdxModes, ArrayRef< MVT > VTs, LegalizeAction Action)
void setIndexedStoreAction (ArrayRef< unsigned > IdxModes, MVT VT, LegalizeAction Action)
Indicate that the specified indexed store does or does not work with the specified type and indicate what to do about it.
void setIndexedStoreAction (ArrayRef< unsigned > IdxModes, ArrayRef< MVT > VTs, LegalizeAction Action)
void setIndexedMaskedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed masked load does or does not work with the specified type and indicate what to do about it.
void setIndexedMaskedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed masked store does or does not work with the specified type and indicate what to do about it.
void setCondCodeAction (ArrayRef< ISD::CondCode > CCs, MVT VT, LegalizeAction Action)
Indicate that the specified condition code is or isn't supported on the target and indicate what to do about it.
void setCondCodeAction (ArrayRef< ISD::CondCode > CCs, ArrayRef< MVT > VTs, LegalizeAction Action)
void AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
If Opc/OrigVT is specified as being promoted, the promotion code defaults to trying a larger integer/fp until it can find one that works.
void setOperationPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
Convenience method to set an operation to Promote and specify the type in a single call.
void setOperationPromotedToType (ArrayRef< unsigned > Ops, MVT OrigVT, MVT DestVT)
void setTargetDAGCombine (ArrayRef< ISD::NodeType > NTs)
Targets should invoke this method for each target independent node that they want to provide a custom DAG combiner for by implementing the PerformDAGCombine virtual method.
void setMinFunctionAlignment (Align Alignment)
Set the target's minimum function alignment.
void setPrefFunctionAlignment (Align Alignment)
Set the target's preferred function alignment.
void setPrefLoopAlignment (Align Alignment)
Set the target's preferred loop alignment.
void setMaxBytesForAlignment (unsigned MaxBytes)
void setMinStackArgumentAlignment (Align Alignment)
Set the minimum stack alignment of an argument.
void setMaxAtomicSizeInBitsSupported (unsigned SizeInBits)
Set the maximum atomic operation size supported by the backend.
void setMaxDivRemBitWidthSupported (unsigned SizeInBits)
Set the size in bits of the maximum div/rem the backend supports.
void setMaxLargeFPConvertBitWidthSupported (unsigned SizeInBits)
Set the size in bits of the maximum fp convert the backend supports.
void setMinCmpXchgSizeInBits (unsigned SizeInBits)
Sets the minimum cmpxchg or ll/sc size supported by the backend.
void setSupportsUnalignedAtomics (bool UnalignedSupported)
Sets whether unaligned atomic operations are supported.
virtual bool isExtFreeImpl (const Instruction *I) const
Return true if the extension represented by I is free.
bool isLegalRC (const TargetRegisterInfo &TRI, const TargetRegisterClass &RC) const
Return true if the value types that can be represented by the specified register class are all legal.
MachineBasicBlock * emitPatchPoint (MachineInstr &MI, MachineBasicBlock *MBB) const
Replace/modify any TargetFrameIndex operands with a targte-dependent sequence of memory operands that is recognized by PrologEpilogInserter.
Protected Attributes inherited from llvm::TargetLoweringBase
unsigned GatherAllAliasesMaxDepth
Depth that GatherAllAliases should continue looking for chain dependencies when trying to find a more preferable chain.
unsigned MaxStoresPerMemset
Specify maximum number of store instructions per memset call.
unsigned MaxStoresPerMemsetOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxStoresPerMemcpy
Specify maximum number of store instructions per memcpy call.
unsigned MaxStoresPerMemcpyOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxGluedStoresPerMemcpy = 0
Specify max number of store instructions to glue in inlined memcpy.
unsigned MaxLoadsPerMemcmp
Specify maximum number of load instructions per memcmp call.
unsigned MaxLoadsPerMemcmpOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxStoresPerMemmove
Specify maximum number of store instructions per memmove call.
unsigned MaxStoresPerMemmoveOptSize
Likewise for functions with the OptSize attribute.
bool PredictableSelectIsExpensive
Tells the code generator that select is more expensive than a branch if the branch is usually predicted right.
bool EnableExtLdPromotion
bool IsStrictFPEnabled
Detailed Description
Definition at line 126 of file HexagonISelLowering.h.
Constructor & Destructor Documentation
HexagonTargetLowering()
HexagonTargetLowering::HexagonTargetLowering (const TargetMachine & TM, const HexagonSubtarget & ST) explicit
Definition at line 1432 of file HexagonISelLowering.cpp.
References llvm::ISD::ABS, llvm::ISD::ADD, llvm::TargetLoweringBase::AddPromotedToType(), llvm::TargetLoweringBase::addRegisterClass(), llvm::ISD::AND, llvm::ISD::ATOMIC_FENCE, llvm::ISD::BITCAST, llvm::ISD::BITREVERSE, llvm::ISD::BlockAddress, llvm::ISD::BR_CC, llvm::ISD::BR_JT, llvm::ISD::BSWAP, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, llvm::TargetLoweringBase::computeRegisterProperties(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::ConstantFP, llvm::ISD::ConstantPool, llvm::ISD::CTLZ, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::TargetLoweringBase::Custom, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_RETURN, EmitJumpTables, EnableFastMath, EnableHexSDNodeSched, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::MVT::fixedlen_vector_valuetypes(), llvm::ISD::FLDEXP, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMAXNUM, llvm::ISD::FMINNUM, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, llvm::ISD::FP16_TO_FP, llvm::ISD::FP_TO_FP16, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::MVT::fp_valuetypes(), llvm::ISD::FPOW, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSHL, llvm::ISD::FSHR, llvm::ISD::FSIN, llvm::ISD::FSINCOS, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::HexagonSubtarget::getRegisterInfo(), llvm::MVT::getVectorVT(), llvm::ISD::GLOBAL_OFFSET_TABLE, llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::HexagonSubtarget::hasV60Ops(), llvm::HexagonSubtarget::hasV66Ops(), llvm::HexagonSubtarget::hasV67Ops(), llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::MVT::integer_valuetypes(), llvm::ISD::INTRINSIC_VOID, llvm::HexagonSubtarget::isEnvironmentMusl(), llvm::ISD::JumpTable, llvm::IRSimilarity::Legal, llvm::ISD::LOAD, llvm::TargetLoweringBase::MaxStoresPerMemcpy, MaxStoresPerMemcpyCL, llvm::TargetLoweringBase::MaxStoresPerMemcpyOptSize, MaxStoresPerMemcpyOptSizeCL, llvm::TargetLoweringBase::MaxStoresPerMemmove, MaxStoresPerMemmoveCL, llvm::TargetLoweringBase::MaxStoresPerMemmoveOptSize, MaxStoresPerMemmoveOptSizeCL, llvm::TargetLoweringBase::MaxStoresPerMemset, MaxStoresPerMemsetCL, llvm::TargetLoweringBase::MaxStoresPerMemsetOptSize, MaxStoresPerMemsetOptSizeCL, MinimumJumpTables, llvm::ISD::MUL, llvm::ISD::OR, llvm::ISD::POST_INC, llvm::ISD::PREFETCH, llvm::TargetLoweringBase::Promote, llvm::ISD::READCYCLECOUNTER, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDO, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::TargetLoweringBase::setBooleanContents(), llvm::TargetLoweringBase::setBooleanVectorContents(), llvm::ISD::SETCC, llvm::TargetLoweringBase::setCondCodeAction(), llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::TargetLoweringBase::setIndexedLoadAction(), llvm::TargetLoweringBase::setIndexedStoreAction(), llvm::ISD::SETLE, llvm::TargetLoweringBase::setLibcallName(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::ISD::SETLT, llvm::TargetLoweringBase::setMaxAtomicSizeInBitsSupported(), llvm::TargetLoweringBase::setMinCmpXchgSizeInBits(), llvm::TargetLoweringBase::setMinFunctionAlignment(), llvm::TargetLoweringBase::setMinimumJumpTableEntries(), llvm::ISD::SETNE, llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setPrefFunctionAlignment(), llvm::TargetLoweringBase::setPrefLoopAlignment(), llvm::TargetLoweringBase::setSchedulingPreference(), llvm::TargetLoweringBase::setStackPointerRegisterToSaveRestore(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::SMAX, llvm::ISD::SMIN, llvm::ISD::SMUL_LOHI, llvm::Sched::Source, llvm::ISD::SPLAT_VECTOR, llvm::ISD::SRA, llvm::ISD::SRA_PARTS, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SRL_PARTS, llvm::ISD::SSUBO, llvm::ISD::STACKRESTORE, llvm::ISD::STACKSAVE, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::TRAP, llvm::ISD::TRUNCATE, llvm::ISD::UADDO, llvm::ISD::UADDO_CARRY, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::ISD::UMAX, llvm::ISD::UMIN, llvm::ISD::UMUL_LOHI, llvm::TargetLoweringBase::UndefinedBooleanContent, llvm::ISD::UREM, llvm::HexagonSubtarget::useHVXOps(), llvm::ISD::USUBO, llvm::ISD::USUBO_CARRY, llvm::ISD::VAARG, llvm::ISD::VACOPY, llvm::ISD::VAEND, llvm::ISD::VASTART, llvm::ISD::VECTOR_SHUFFLE, llvm::Sched::VLIW, llvm::ISD::VSELECT, llvm::ISD::XOR, and llvm::ISD::ZEXTLOAD.
Member Function Documentation
AdjustInstrPostInstrSelection()
void HexagonTargetLowering::AdjustInstrPostInstrSelection (MachineInstr & MI, SDNode * Node) const override virtual
This method should be implemented by targets that mark instructions with the 'hasPostISelHook' flag.
These instructions must be adjusted after instruction selection by target hooks. e.g. To fill in optional defs for ARM 's' setting instructions.
Reimplemented from llvm::TargetLowering.
Definition at line 3833 of file HexagonISelLowering.cpp.
References MI.
allowsMemoryAccess()
bool HexagonTargetLowering::allowsMemoryAccess (LLVMContext & Context, const DataLayout & DL, EVT VT, unsigned AddrSpace, Align Alignment, MachineMemOperand::Flags Flags, unsigned * Fast) const override virtual
Return true if the target supports a memory access of this type for the given address space and alignment.
If the access is allowed, the optional final parameter returns the relative speed of the access (as defined by the target).
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3775 of file HexagonISelLowering.cpp.
References llvm::TargetLoweringBase::allowsMemoryAccess(), Context, DL, llvm::CallingConv::Fast, llvm::EVT::getSimpleVT(), and llvm::HexagonSubtarget::isHVXVectorType().
allowsMisalignedMemoryAccesses()
bool HexagonTargetLowering::allowsMisalignedMemoryAccesses (EVT , unsigned AddrSpace, Align Alignment, MachineMemOperand::Flags Flags, unsigned *) const override virtual
Determine if the target supports unaligned memory accesses.
This function returns true if the target allows unaligned memory accesses of the specified type in the given address space. If true, it also returns a relative speed of the unaligned memory access in the last argument by reference. The higher the speed number the faster the operation comparing to a number returned by another such call. This is used, for example, in situations where an array copy/move/set is converted to a sequence of store operations. Its use helps to ensure that such replacements don't generate code that causes an alignment error (trap) on the target machine.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3785 of file HexagonISelLowering.cpp.
References llvm::CallingConv::Fast, llvm::EVT::getSimpleVT(), and llvm::HexagonSubtarget::isHVXVectorType().
allowTruncateForTailCall()
bool HexagonTargetLowering::allowTruncateForTailCall (Type * FromTy, Type * ToTy) const override virtual
Return true if a truncation from FromTy to ToTy is permitted when deciding whether a call is in tail position.
Typically this means that both results would be assigned to the same register or stack slot, but it could mean the target performs adequate checks of its own before proceeding with the tail call. Targets must return false when FromTy <= ToTy.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3072 of file HexagonISelLowering.cpp.
References llvm::Type::getPrimitiveSizeInBits(), and llvm::Type::isIntegerTy().
CanLowerReturn()
bool HexagonTargetLowering::CanLowerReturn (CallingConv::ID , MachineFunction & , bool , const SmallVectorImpl< ISD::OutputArg > & , LLVMContext &) const override virtual
This hook should be implemented to check whether the return values described by the Outs array can fit into the return registers.
If false is returned, an sret-demotion is performed.
Reimplemented from llvm::TargetLowering.
Definition at line 185 of file HexagonISelLowering.cpp.
References llvm::CCState::CheckReturn(), Context, llvm::MachineFunction::getSubtarget(), and llvm::HexagonSubtarget::useHVXOps().
emitLoadLinked()
Value * HexagonTargetLowering::emitLoadLinked (IRBuilderBase & Builder, Type * ValueTy, Value * Addr, AtomicOrdering Ord) const override virtual
Perform a load-linked operation on Addr, returning a "Value *" with the corresponding pointee type.
This may entail some non-trivial operations to truncate or reconstruct types that will be illegal in the backend. See ARMISelLowering for an example implementation.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3838 of file HexagonISelLowering.cpp.
References Addr, assert(), llvm::IRBuilderBase::CreateBitCast(), llvm::IRBuilderBase::CreateCall(), llvm::Intrinsic::getDeclaration(), llvm::IRBuilderBase::GetInsertBlock(), llvm::GlobalValue::getParent(), llvm::BasicBlock::getParent(), and llvm::Type::getPrimitiveSizeInBits().
emitStoreConditional()
Value * HexagonTargetLowering::emitStoreConditional (IRBuilderBase & Builder, Value * Val, Value * Addr, AtomicOrdering Ord) const override virtual
Perform a store-conditional operation to Addr.
Return the status of the store. This should be 0 if the store succeeded, non-zero otherwise.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3856 of file HexagonISelLowering.cpp.
References Addr, assert(), llvm::IRBuilderBase::CreateBitCast(), llvm::IRBuilderBase::CreateCall(), llvm::IRBuilderBase::CreateICmpEQ(), llvm::IRBuilderBase::CreateZExt(), llvm::Intrinsic::getDeclaration(), llvm::IRBuilderBase::GetInsertBlock(), llvm::IRBuilderBase::getInt32(), llvm::Type::getInt32Ty(), llvm::IRBuilderBase::getIntNTy(), llvm::GlobalValue::getParent(), llvm::BasicBlock::getParent(), llvm::Type::getPrimitiveSizeInBits(), and llvm::Value::getType().
getConstraintType()
TargetLowering::ConstraintType HexagonTargetLowering::getConstraintType (StringRef Constraint) const override virtual
Given a constraint, return the type of constraint it is for this target.
Reimplemented from llvm::TargetLowering.
Definition at line 3565 of file HexagonISelLowering.cpp.
References llvm::TargetLowering::C_RegisterClass, llvm::TargetLowering::getConstraintType(), llvm::StringRef::size(), and llvm::HexagonSubtarget::useHVXOps().
getCustomOperationAction()
TargetLoweringBase::LegalizeAction HexagonTargetLowering::getCustomOperationAction (SDNode & Op) const override virtual
How to legalize this custom operation?
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2214 of file HexagonISelLowering.cpp.
References llvm::TargetLoweringBase::Legal, and llvm::HexagonSubtarget::useHVXOps().
GetDynamicTLSAddr()
SDValue HexagonTargetLowering::GetDynamicTLSAddr (SelectionDAG & DAG, SDValue Chain, GlobalAddressSDNode * GA, SDValue InGlue, EVT PtrVT, unsigned ReturnReg, unsigned char OperandGlues) const
Definition at line 1275 of file HexagonISelLowering.cpp.
References assert(), llvm::CallingConv::C, llvm::HexagonISD::CALL, llvm::SelectionDAG::getCopyFromReg(), llvm::MachineFunction::getFrameInfo(), llvm::GlobalAddressSDNode::getGlobal(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::GlobalAddressSDNode::getOffset(), llvm::SelectionDAG::getRegister(), llvm::HexagonSubtarget::getRegisterInfo(), llvm::SelectionDAG::getRegisterMask(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SDValue::getValue(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), and llvm::MachineFrameInfo::setAdjustsStack().
Referenced by LowerToTLSGeneralDynamicModel().
getExceptionPointerRegister()
Register llvm::HexagonTargetLowering::getExceptionPointerRegister (const Constant * PersonalityFn) const inline override virtual
If a physical register, this returns the register that receives the exception address on entry to an EH pad.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 266 of file HexagonISelLowering.h.
getExceptionSelectorRegister()
Register llvm::HexagonTargetLowering::getExceptionSelectorRegister (const Constant * PersonalityFn) const inline override virtual
If a physical register, this returns the register that receives the exception typeid on entry to a landing pad.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 273 of file HexagonISelLowering.h.
getOptimalMemOpType()
EVT HexagonTargetLowering::getOptimalMemOpType (const MemOp & Op, const AttributeList & FuncAttributes) const override virtual
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
If DstAlign is zero that means it's safe to destination alignment can satisfy any constraint. Similarly if SrcAlign is zero it means there isn't a need to check it against alignment requirement, probably because the source does not need to be loaded. If 'IsMemset' is true, that means it's expanding a memset. If 'ZeroMemset' is true, that means it's a memset of zero. 'MemcpyStrSrc' indicates whether the memcpy source is constant so it does not need to be loaded. It returns EVT::Other if the type should be determined using generic target-independent logic.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3764 of file HexagonISelLowering.cpp.
getPICJumpTableRelocBase()
SDValue HexagonTargetLowering::getPICJumpTableRelocBase (SDValue Table, SelectionDAG & DAG) const override virtual
Returns relocation base for the given PIC jumptable.
Reimplemented from llvm::TargetLowering.
Definition at line 3552 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::AT_PCREL, llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetJumpTable(), llvm::SDValue::getValueType(), Idx, and llvm::HexagonII::MO_PCREL.
getPostIndexedAddressParts()
bool HexagonTargetLowering::getPostIndexedAddressParts (SDNode * N, SDNode * Op, SDValue & Base, SDValue & Offset, ISD::MemIndexedMode & AM, SelectionDAG & DAG) const override virtual
Returns true by value, base pointer and offset pointer and addressing mode by reference if this node can be combined with a load / store to form a post-indexed load / store.
Reimplemented from llvm::TargetLowering.
Definition at line 627 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::sampleprof::Base, llvm::HexagonSubtarget::getInstrInfo(), llvm::MemSDNode::getMemoryVT(), llvm::EVT::getSimpleVT(), llvm::HexagonSubtarget::isHVXVectorType(), llvm::EVT::isSimple(), llvm::HexagonInstrInfo::isValidAutoIncImm(), N, llvm::Offset, and llvm::ISD::POST_INC.
getPreferredVectorAction()
TargetLoweringBase::LegalizeTypeAction HexagonTargetLowering::getPreferredVectorAction (MVT VT) const override virtual
Return the preferred vector type legalization action.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2188 of file HexagonISelLowering.cpp.
References llvm::MVT::getVectorElementType(), llvm::MVT::getVectorMinNumElements(), llvm::isPowerOf2_32(), llvm::MVT::isScalableVector(), llvm::TargetLoweringBase::TypeScalarizeVector, llvm::TargetLoweringBase::TypeSplitVector, llvm::TargetLoweringBase::TypeWidenVector, and llvm::HexagonSubtarget::useHVXOps().
Referenced by llvm::HexagonSubtarget::isTypeForHVX().
getRegForInlineAsmConstraint()
std::pair< unsigned, const TargetRegisterClass * > HexagonTargetLowering::getRegForInlineAsmConstraint (const TargetRegisterInfo * TRI, StringRef Constraint, MVT VT) const override virtual
Given a physical register constraint (e.g.
{edx}), return the register number and the register class for the register.
Given a register class constraint, like 'r', if this corresponds directly to an LLVM register class, return a register of 0 and the register class pointer.
This should only be used for C_Register constraints. On error, this returns a register number of 0 and a null register class pointer.
Reimplemented from llvm::TargetLowering.
Definition at line 3583 of file HexagonISelLowering.cpp.
References llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::MVT::getSizeInBits(), llvm::HexagonSubtarget::hasV60Ops(), llvm::MVT::SimpleTy, llvm::StringRef::size(), TRI, and llvm::HexagonSubtarget::useHVX128BOps().
getRegisterByName()
Register HexagonTargetLowering::getRegisterByName (const char * RegName, LLT Ty, const MachineFunction & MF) const override virtual
Return the register ID of the name passed in.
Used by named register global variables extension. There is no target-independent behaviour so the default action is to bail.
Reimplemented from llvm::TargetLowering.
Definition at line 268 of file HexagonISelLowering.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), RegName, and llvm::report_fatal_error().
getSetCCResultType()
EVT llvm::HexagonTargetLowering::getSetCCResultType (const DataLayout & DL, LLVMContext & Context, EVT VT) const inline override virtual
Return the ValueType of the result of SETCC operations.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 282 of file HexagonISelLowering.h.
References llvm::CallingConv::C, llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), and llvm::EVT::isVector().
getTargetNodeName()
const char * HexagonTargetLowering::getTargetNodeName (unsigned Opcode) const override virtual
This method returns the name of a target specific DAG node.
Reimplemented from llvm::TargetLowering.
Definition at line 1890 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::ADDC, llvm::HexagonISD::ALLOCA, llvm::HexagonISD::AT_GOT, llvm::HexagonISD::AT_PCREL, llvm::HexagonISD::BARRIER, llvm::HexagonISD::CALL, llvm::HexagonISD::CALLnr, llvm::HexagonISD::CALLR, llvm::HexagonISD::COMBINE, llvm::HexagonISD::CONST32, llvm::HexagonISD::CONST32_GP, llvm::HexagonISD::CP, llvm::HexagonISD::D2P, llvm::HexagonISD::DCFETCH, llvm::HexagonISD::EH_RETURN, llvm::HexagonISD::EXTRACTU, llvm::HexagonISD::INSERT, llvm::HexagonISD::ISEL, llvm::HexagonISD::JT, llvm::HexagonISD::MFSHL, llvm::HexagonISD::MFSHR, llvm::HexagonISD::OP_END, llvm::HexagonISD::P2D, llvm::HexagonISD::PFALSE, llvm::HexagonISD::PTRUE, llvm::HexagonISD::Q2V, llvm::HexagonISD::QCAT, llvm::HexagonISD::QFALSE, llvm::HexagonISD::QTRUE, llvm::HexagonISD::READCYCLE, llvm::HexagonISD::RET_GLUE, llvm::HexagonISD::SMUL_LOHI, llvm::HexagonISD::SSAT, llvm::HexagonISD::SUBC, llvm::HexagonISD::TC_RETURN, llvm::HexagonISD::TL_EXTEND, llvm::HexagonISD::TL_TRUNCATE, llvm::HexagonISD::TSTBIT, llvm::HexagonISD::TYPECAST, llvm::HexagonISD::UMUL_LOHI, llvm::HexagonISD::USAT, llvm::HexagonISD::USMUL_LOHI, llvm::HexagonISD::V2Q, llvm::HexagonISD::VALIGN, llvm::HexagonISD::VALIGNADDR, llvm::HexagonISD::VASL, llvm::HexagonISD::VASR, llvm::HexagonISD::VEXTRACTW, llvm::HexagonISD::VINSERTW0, llvm::HexagonISD::VLSR, and llvm::HexagonISD::VROR.
getTgtMemIntrinsic()
bool HexagonTargetLowering::getTgtMemIntrinsic (IntrinsicInfo & Info, const CallInst & I, MachineFunction & MF, unsigned Intrinsic) const override virtual
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory).
If this is the case, it returns true and store the intrinsic information into the IntrinsicInfo that was passed to the function.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2079 of file HexagonISelLowering.cpp.
References DL, getUnderLyingObjectForBrevLdIntr(), llvm::MVT::getVT(), I, Info, llvm::ISD::INTRINSIC_W_CHAIN, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, and llvm::MachineMemOperand::MOVolatile.
hasBitTest()
bool HexagonTargetLowering::hasBitTest (SDValue X, SDValue Y) const override virtual
Return true if the target has a bit-test instruction: (X & (1 << Y)) ==/!= 0 This knowledge can be used to prevent breaking the pattern, or creating it if it could be recognized.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2138 of file HexagonISelLowering.cpp.
References X.
isCheapToSpeculateCtlz()
bool llvm::HexagonTargetLowering::isCheapToSpeculateCtlz (Type * Ty) const inline override virtual
Return true if it is cheap to speculate a call to intrinsic ctlz.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 152 of file HexagonISelLowering.h.
isCheapToSpeculateCttz()
bool llvm::HexagonTargetLowering::isCheapToSpeculateCttz (Type * Ty) const inline override virtual
Return true if it is cheap to speculate a call to intrinsic cttz.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 151 of file HexagonISelLowering.h.
isCtlzFast()
bool llvm::HexagonTargetLowering::isCtlzFast () const inline override virtual
Return true if ctlz instruction is fast.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 153 of file HexagonISelLowering.h.
IsEligibleForTailCallOptimization()
bool HexagonTargetLowering::IsEligibleForTailCallOptimization (SDValue Callee, CallingConv::ID CalleeCC, bool IsVarArg, bool IsCalleeStructRet, bool IsCallerStructRet, const SmallVectorImpl< ISD::OutputArg > & Outs, const SmallVectorImpl< SDValue > & OutVals, const SmallVectorImpl< ISD::InputArg > & Ins, SelectionDAG & DAG) const
IsEligibleForTailCallOptimization - Check whether the call is eligible for tail call optimization.
Targets which want to do tail call optimization should implement this function.
Definition at line 3702 of file HexagonISelLowering.cpp.
References llvm::CallingConv::C, E, llvm::CallingConv::Fast, llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), and llvm::SelectionDAG::getMachineFunction().
Referenced by LowerCall().
isExtractSubvectorCheap()
bool HexagonTargetLowering::isExtractSubvectorCheap (EVT ResVT, EVT SrcVT, unsigned Index) const override virtual
Return true if EXTRACT_SUBVECTOR is cheap for extracting this result type from this source type with this index.
This is needed because EXTRACT_SUBVECTOR usually has custom lowering that depends on the index of the first element, and only the target knows which lowering is cheap.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2163 of file HexagonISelLowering.cpp.
References assert(), llvm::EVT::getSimpleVT(), llvm::MVT::getVectorElementType(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), and llvm::EVT::isSimple().
isFMAFasterThanFMulAndFAdd()
bool HexagonTargetLowering::isFMAFasterThanFMulAndFAdd (const MachineFunction & MF, EVT VT) const override virtual
Return true if an FMA operation is faster than a pair of mul and add instructions.
fmuladd intrinsics will be expanded to FMAs when this method returns true (and FMAs are legal), otherwise fmuladd is expanded to mul + add.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2152 of file HexagonISelLowering.cpp.
References llvm::ISD::FMA, and llvm::TargetLoweringBase::isOperationLegalOrCustom().
isFPImmLegal()
bool HexagonTargetLowering::isFPImmLegal (const APFloat & Imm, EVT VT, bool ForCodeSize) const override virtual
isFPImmLegal - Returns true if the target can instruction select the specified FP immediate natively.
If false, the legalizer will materialize the FP immediate as a load from a constant pool.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3641 of file HexagonISelLowering.cpp.
isLegalAddressingMode()
bool HexagonTargetLowering::isLegalAddressingMode (const DataLayout & DL, const AddrMode & AM, Type * Ty, unsigned AS, Instruction * I = nullptr) const override virtual
isLegalAddressingMode - Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
The type may be VoidTy, in which case only return true if the addressing mode is legal for a load/store of any legal type. TODO: Handle pre/postinc as well.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3648 of file HexagonISelLowering.cpp.
References A, llvm::TargetLoweringBase::AddrMode::BaseGV, llvm::TargetLoweringBase::AddrMode::BaseOffs, DL, llvm::isAligned(), llvm::Type::isSized(), llvm::Log2(), and llvm::TargetLoweringBase::AddrMode::Scale.
isLegalICmpImmediate()
bool HexagonTargetLowering::isLegalICmpImmediate (int64_t Imm) const override virtual
isLegalICmpImmediate - Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3695 of file HexagonISelLowering.cpp.
isOffsetFoldingLegal()
bool HexagonTargetLowering::isOffsetFoldingLegal (const GlobalAddressSDNode * GA) const override virtual
Return true if folding a constant offset with the given GlobalAddress is legal.
It is frequently not legal in PIC relocation models.
Reimplemented from llvm::TargetLowering.
Definition at line 3686 of file HexagonISelLowering.cpp.
References llvm::TargetMachine::getRelocationModel(), and llvm::Reloc::Static.
isShuffleMaskLegal()
bool HexagonTargetLowering::isShuffleMaskLegal (ArrayRef< int > , EVT) const override virtual
Targets can use this to indicate that they only support some VECTOR_SHUFFLE operations, those with specific masks.
By default, if a target supports the VECTOR_SHUFFLE node, all mask values are assumed to be legal.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2182 of file HexagonISelLowering.cpp.
isTargetCanonicalConstantNode()
bool HexagonTargetLowering::isTargetCanonicalConstantNode (SDValue Op) const override virtual
Returns true if the given Opc is considered a canonical constant for the target, which should not be transformed back into a BUILD_VECTOR.
Reimplemented from llvm::TargetLowering.
Definition at line 2177 of file HexagonISelLowering.cpp.
References llvm::ISD::CONCAT_VECTORS, and llvm::TargetLowering::isTargetCanonicalConstantNode().
isTruncateFree() [1/2]
bool HexagonTargetLowering::isTruncateFree (EVT VT1, EVT VT2) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2146 of file HexagonISelLowering.cpp.
References llvm::EVT::getSimpleVT(), and llvm::EVT::isSimple().
isTruncateFree() [2/2]
bool HexagonTargetLowering::isTruncateFree (Type * FromTy, Type * ToTy) const override virtual
Return true if it's free to truncate a value of type FromTy to type ToTy.
e.g. On x86 it's free to truncate a i32 value in register EAX to i16 by referencing its sub-register AX. Targets must return false when FromTy <= ToTy.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2142 of file HexagonISelLowering.cpp.
References llvm::EVT::getEVT(), and isTruncateFree().
Referenced by isTruncateFree().
LowerANY_EXTEND()
SDValue llvm::HexagonTargetLowering::LowerANY_EXTEND (SDValue Op, SelectionDAG & DAG) const
LowerATOMIC_FENCE()
SDValue HexagonTargetLowering::LowerATOMIC_FENCE (SDValue Op, SelectionDAG & DAG) const
Definition at line 1210 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::BARRIER, and llvm::SelectionDAG::getNode().
Referenced by LowerOperation().
LowerBITCAST()
SDValue HexagonTargetLowering::LowerBITCAST (SDValue Op, SelectionDAG & DAG) const
Definition at line 2452 of file HexagonISelLowering.cpp.
References assert(), llvm::SelectionDAG::getBitcast(), llvm::MVT::getSizeInBits(), and llvm::SelectionDAG::getZExtOrTrunc().
Referenced by LowerOperation().
LowerBlockAddress()
SDValue HexagonTargetLowering::LowerBlockAddress (SDValue Op, SelectionDAG & DAG) const
Definition at line 1250 of file HexagonISelLowering.cpp.
References A, llvm::HexagonISD::AT_PCREL, llvm::HexagonISD::CONST32_GP, llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetMachine::getRelocationModel(), llvm::SelectionDAG::getTargetBlockAddress(), llvm::HexagonII::MO_PCREL, and llvm::Reloc::Static.
Referenced by LowerOperation().
LowerBUILD_VECTOR()
SDValue HexagonTargetLowering::LowerBUILD_VECTOR (SDValue Op, SelectionDAG & DAG) const
Definition at line 2927 of file HexagonISelLowering.cpp.
References A, llvm::CallingConv::C, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::DWARFExpression::Operation::getNumOperands(), llvm::SelectionDAG::getSelect(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorNumElements(), llvm::ISD::OR, P, llvm::HexagonISD::PFALSE, llvm::HexagonISD::PTRUE, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by LowerOperation().
LowerCall()
SDValue HexagonTargetLowering::LowerCall (TargetLowering::CallLoweringInfo & CLI, SmallVectorImpl< SDValue > & InVals) const override virtual
LowerCall - Functions arguments are copied from virtual regs to (physical regs)/(stack frame), CALLSEQ_START and CALLSEQ_END are emitted.
Reimplemented from llvm::TargetLowering.
Definition at line 403 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::CCValAssign::AExt, llvm::ISD::ANY_EXTEND, assert(), llvm::CCValAssign::BCvt, llvm::HexagonISD::CALL, llvm::TargetLowering::CallLoweringInfo::CallConv, llvm::TargetLowering::CallLoweringInfo::Callee, llvm::HexagonISD::CALLnr, llvm::TargetLowering::CallLoweringInfo::CB, llvm::TargetLowering::CallLoweringInfo::Chain, CreateCopyOfByValArgument(), llvm::TargetLowering::CallLoweringInfo::DAG, llvm::dbgs(), DisableArgsMinAlignment, llvm::TargetLowering::CallLoweringInfo::DL, llvm::TargetLowering::CallLoweringInfo::DoesNotReturn, llvm::SmallVectorBase< Size_T >::empty(), llvm::MachineFrameInfo::ensureMaxAlignment(), llvm::CCValAssign::Full, G, llvm::SelectionDAG::getBitcast(), llvm::HexagonRegisterInfo::getCallPreservedMask(), llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::MachineFunction::getDataLayout(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::CallBase::getFunctionType(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::FunctionType::getNumParams(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::HexagonSubtarget::getRegisterInfo(), llvm::SelectionDAG::getRegisterMask(), llvm::MachinePointerInfo::getStack(), llvm::HexagonRegisterInfo::getStackRegister(), llvm::SelectionDAG::getStore(), llvm::MVT::getStoreSizeInBits(), llvm::MachineFunction::getSubtarget(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SDValue::getValue(), llvm::CCValAssign::getValVT(), llvm::SelectionDAG::getVTList(), llvm::Function::hasStructRetAttr(), llvm::HexagonSubtarget::hasV60Ops(), llvm::HexagonII::HMOTF_ConstExtended, llvm::TargetLowering::CallLoweringInfo::Ins, IsEligibleForTailCallOptimization(), llvm::HexagonSubtarget::isEnvironmentMusl(), llvm::HexagonSubtarget::isHVXVectorType(), llvm::CCValAssign::isMemLoc(), llvm::CCValAssign::isRegLoc(), llvm::TargetLowering::CallLoweringInfo::IsTailCall, llvm::TargetLowering::CallLoweringInfo::IsVarArg, LLVM_DEBUG, llvm_unreachable, LowerCallResult(), llvm::TargetLowering::CallLoweringInfo::Outs, llvm::TargetLowering::CallLoweringInfo::OutVals, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::MachineFrameInfo::setHasCalls(), llvm::MachineFrameInfo::setHasTailCall(), llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, llvm::SmallVectorBase< Size_T >::size(), llvm::HexagonISD::TC_RETURN, llvm::ISD::TokenFactor, llvm::HexagonSubtarget::useHVXOps(), llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
LowerCallResult()
SDValue HexagonTargetLowering::LowerCallResult (SDValue Chain, SDValue Glue, CallingConv::ID CallConv, bool IsVarArg, const SmallVectorImpl< ISD::InputArg > & Ins, const SDLoc & dl, SelectionDAG & DAG, SmallVectorImpl< SDValue > & InVals, const SmallVectorImpl< SDValue > & OutVals, SDValue Callee) const
LowerCallResult - Lower the result values of an ISD::CALL into the appropriate copies out of appropriate physical registers.
This assumes that Chain/Glue are the input chain/glue to use, and that TheCall is the call being lowered. Returns a SDNode with the same number of values as the ISD::CALL.
Definition at line 349 of file HexagonISelLowering.cpp.
References llvm::CCState::AnalyzeCallResult(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getRegInfo(), llvm::SDValue::getValue(), MRI, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::SmallVectorBase< Size_T >::size(), and llvm::HexagonSubtarget::useHVXOps().
Referenced by LowerCall().
LowerCONCAT_VECTORS()
SDValue HexagonTargetLowering::LowerCONCAT_VECTORS (SDValue Op, SelectionDAG & DAG) const
Definition at line 2981 of file HexagonISelLowering.cpp.
References assert(), llvm::SmallVectorImpl< T >::clear(), llvm::HexagonISD::D2P, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::DWARFExpression::Operation::getNumOperands(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::HexagonISD::INSERT, P, llvm::HexagonISD::P2D, llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::size().
Referenced by LowerOperation().
LowerConstantPool()
SDValue HexagonTargetLowering::LowerConstantPool (SDValue Op, SelectionDAG & DAG) const
Definition at line 1111 of file HexagonISelLowering.cpp.
References assert(), llvm::HexagonISD::AT_PCREL, llvm::HexagonISD::CP, llvm::ConstantVector::get(), llvm::ConstantPoolSDNode::getAlign(), llvm::ConstantPoolSDNode::getConstVal(), llvm::IRBuilderBase::getInt8(), llvm::ConstantPoolSDNode::getMachineCPVal(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetConstantPool(), llvm::ConstantPoolSDNode::isMachineConstantPoolEntry(), llvm::TargetLowering::isPositionIndependent(), llvm::isPowerOf2_32(), llvm::HexagonII::MO_PCREL, llvm::Offset, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
Referenced by LowerOperation().
LowerDYNAMIC_STACKALLOC()
SDValue HexagonTargetLowering::LowerDYNAMIC_STACKALLOC (SDValue Op, SelectionDAG & DAG) const
Definition at line 743 of file HexagonISelLowering.cpp.
References A, llvm::HexagonISD::ALLOCA, assert(), llvm::dbgs(), llvm::SelectionDAG::getConstant(), llvm::HexagonSubtarget::getFrameLowering(), llvm::SelectionDAG::getNode(), llvm::ConstantSDNode::getSExtValue(), llvm::SelectionDAG::getVTList(), LLVM_DEBUG, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), and Size.
Referenced by LowerOperation().
LowerEH_LABEL()
SDValue llvm::HexagonTargetLowering::LowerEH_LABEL (SDValue Op, SelectionDAG & DAG) const
LowerEH_RETURN()
SDValue HexagonTargetLowering::LowerEH_RETURN (SDValue Op, SelectionDAG & DAG) const
Definition at line 3296 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::HexagonISD::EH_RETURN, llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getStore(), llvm::Offset, and llvm::HexagonMachineFunctionInfo::setHasEHReturn().
Referenced by LowerOperation().
LowerEXTRACT_SUBVECTOR()
SDValue HexagonTargetLowering::LowerEXTRACT_SUBVECTOR (SDValue Op, SelectionDAG & DAG) const
Definition at line 3050 of file HexagonISelLowering.cpp.
Referenced by LowerOperation().
LowerEXTRACT_VECTOR_ELT()
SDValue HexagonTargetLowering::LowerEXTRACT_VECTOR_ELT (SDValue Op, SelectionDAG & DAG) const
Definition at line 3042 of file HexagonISelLowering.cpp.
References llvm::MVT::getVectorElementType().
Referenced by LowerOperation().
LowerFormalArguments()
SDValue HexagonTargetLowering::LowerFormalArguments (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::InputArg > & , const SDLoc & , SelectionDAG & , SmallVectorImpl< SDValue > &) const override virtual
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
The implementation should fill in the InVals array with legal-type argument values, and return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 773 of file HexagonISelLowering.cpp.
References llvm::ISD::AND, assert(), llvm::CCValAssign::BCvt, llvm::MachineFrameInfo::CreateFixedObject(), DisableArgsMinAlignment, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::HexagonSubtarget::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::Function::getFunctionType(), llvm::TargetRegisterClass::getID(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getLoad(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::MachineFrameInfo::getNumFixedObjects(), llvm::FunctionType::getNumParams(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::SelectionDAG::getSetCC(), llvm::MVT::getSizeInBits(), llvm::MVT::getStoreSizeInBits(), llvm::CCValAssign::getValVT(), HEXAGON_LRFP_SIZE, Hexagon_PointerSize, llvm::HexagonSubtarget::isEnvironmentMusl(), llvm::HexagonSubtarget::isHVXVectorType(), llvm::CCValAssign::isMemLoc(), llvm::CCValAssign::isRegLoc(), llvm_unreachable, MRI, llvm::Offset, llvm::SmallVectorTemplateBase< T, bool >::push_back(), RegSize, llvm::HexagonMachineFunctionInfo::setFirstNamedArgFrameIndex(), llvm::ISD::SETNE, llvm::SmallVectorBase< Size_T >::size(), and llvm::HexagonSubtarget::useHVXOps().
LowerFRAMEADDR()
SDValue HexagonTargetLowering::LowerFRAMEADDR (SDValue Op, SelectionDAG & DAG) const
Definition at line 1193 of file HexagonISelLowering.cpp.
References llvm::Depth, llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::HexagonRegisterInfo::getFrameRegister(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::HexagonSubtarget::getRegisterInfo(), and llvm::MachineFrameInfo::setFrameAddressIsTaken().
Referenced by LowerOperation(), and LowerRETURNADDR().
LowerGLOBAL_OFFSET_TABLE()
SDValue HexagonTargetLowering::LowerGLOBAL_OFFSET_TABLE (SDValue Op, SelectionDAG & DAG) const
Definition at line 1266 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::AT_PCREL, llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetExternalSymbol(), HEXAGON_GOT_SYM_NAME, and llvm::HexagonII::MO_PCREL.
Referenced by LowerOperation(), LowerToTLSGeneralDynamicModel(), and LowerToTLSInitialExecModel().
LowerGLOBALADDRESS()
SDValue HexagonTargetLowering::LowerGLOBALADDRESS (SDValue Op, SelectionDAG & DAG) const
Definition at line 1216 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::AT_GOT, llvm::HexagonISD::AT_PCREL, llvm::HexagonISD::CONST32, llvm::HexagonISD::CONST32_GP, llvm::GlobalValue::getAliaseeObject(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getGLOBAL_OFFSET_TABLE(), llvm::SelectionDAG::getNode(), llvm::HexagonTargetMachine::getObjFileLowering(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetMachine::getRelocationModel(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::TargetLoweringBase::getTargetMachine(), llvm::HexagonII::MO_GOT, llvm::HexagonII::MO_PCREL, llvm::Offset, llvm::TargetMachine::shouldAssumeDSOLocal(), llvm::Reloc::Static, and llvm::HexagonSubtarget::useSmallData().
Referenced by LowerOperation().
LowerGlobalTLSAddress()
SDValue HexagonTargetLowering::LowerGlobalTLSAddress (SDValue Op, SelectionDAG & DAG) const
Definition at line 1412 of file HexagonISelLowering.cpp.
References llvm::TLSModel::GeneralDynamic, llvm::GlobalAddressSDNode::getGlobal(), llvm::TargetMachine::getTLSModel(), llvm::TLSModel::InitialExec, llvm_unreachable, llvm::TLSModel::LocalDynamic, llvm::TLSModel::LocalExec, LowerToTLSGeneralDynamicModel(), LowerToTLSInitialExecModel(), and LowerToTLSLocalExecModel().
Referenced by LowerOperation().
LowerINLINEASM()
SDValue HexagonTargetLowering::LowerINLINEASM (SDValue Op, SelectionDAG & DAG) const
Definition at line 657 of file HexagonISelLowering.cpp.
References llvm::InlineAsm::Clobber, llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::DWARFExpression::Operation::getNumOperands(), llvm::HexagonSubtarget::getRegisterInfo(), llvm::InlineAsm::Imm, llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm_unreachable, llvm::InlineAsm::Mem, llvm::InlineAsm::Op_FirstOperand, llvm::InlineAsm::RegDef, llvm::InlineAsm::RegDefEarlyClobber, and llvm::InlineAsm::RegUse.
Referenced by LowerOperation().
LowerINSERT_SUBVECTOR()
SDValue HexagonTargetLowering::LowerINSERT_SUBVECTOR (SDValue Op, SelectionDAG & DAG) const
Definition at line 3064 of file HexagonISelLowering.cpp.
Referenced by LowerOperation().
LowerINSERT_VECTOR_ELT()
SDValue HexagonTargetLowering::LowerINSERT_VECTOR_ELT (SDValue Op, SelectionDAG & DAG) const
Definition at line 3057 of file HexagonISelLowering.cpp.
References getVectorElementType().
Referenced by LowerOperation().
LowerINTRINSIC_VOID()
SDValue HexagonTargetLowering::LowerINTRINSIC_VOID (SDValue Op, SelectionDAG & DAG) const
Definition at line 728 of file HexagonISelLowering.cpp.
References Addr, llvm::HexagonISD::DCFETCH, DL, llvm::SelectionDAG::getConstant(), and llvm::SelectionDAG::getNode().
Referenced by LowerOperation().
LowerINTRINSIC_WO_CHAIN()
SDValue HexagonTargetLowering::LowerINTRINSIC_WO_CHAIN (SDValue Op, SelectionDAG & DAG) const
Definition at line 164 of file HexagonISelLowering.cpp.
Referenced by LowerOperation().
LowerJumpTable()
SDValue HexagonTargetLowering::LowerJumpTable (SDValue Op, SelectionDAG & DAG) const
Definition at line 1154 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::AT_PCREL, llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getTargetJumpTable(), Idx, llvm::TargetLowering::isPositionIndependent(), llvm::HexagonISD::JT, and llvm::HexagonII::MO_PCREL.
Referenced by LowerOperation().
LowerLoad()
SDValue HexagonTargetLowering::LowerLoad (SDValue Op, SelectionDAG & DAG) const
Definition at line 3085 of file HexagonISelLowering.cpp.
References llvm::MemSDNode::getAAInfo(), llvm::LSBaseSDNode::getAddressingMode(), llvm::MemSDNode::getAlign(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::LoadSDNode::getExtensionType(), llvm::MachineMemOperand::getFlags(), llvm::SelectionDAG::getLoad(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::LoadSDNode::getOffset(), llvm::MemSDNode::getPointerInfo(), llvm::MemSDNode::getRanges(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::EVT::getSimpleVT(), llvm::SelectionDAG::getZExtOrTrunc(), LowerUnalignedLoad(), NL, llvm::ISD::NON_EXTLOAD, llvm::ISD::SEXTLOAD, and llvm::ISD::ZEXTLOAD.
Referenced by LowerOperation().
LowerOperation()
SDValue HexagonTargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const override virtual
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
If the target has no operations that require custom lowering, it need not implement this. The default implementation of this aborts.
Reimplemented from llvm::TargetLowering.
Definition at line 3323 of file HexagonISelLowering.cpp.
References llvm::ISD::ATOMIC_FENCE, llvm::ISD::BITCAST, llvm::ISD::BlockAddress, llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, llvm::ISD::ConstantPool, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_RETURN, llvm::errs(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FRAMEADDR, llvm::ISD::GLOBAL_OFFSET_TABLE, llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::ISD::INLINEASM, llvm::ISD::INLINEASM_BR, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::ISD::JumpTable, llvm_unreachable, llvm::ISD::LOAD, LowerATOMIC_FENCE(), LowerBITCAST(), LowerBlockAddress(), LowerBUILD_VECTOR(), LowerCONCAT_VECTORS(), LowerConstantPool(), LowerDYNAMIC_STACKALLOC(), LowerEH_RETURN(), LowerEXTRACT_SUBVECTOR(), LowerEXTRACT_VECTOR_ELT(), LowerFRAMEADDR(), LowerGLOBAL_OFFSET_TABLE(), LowerGLOBALADDRESS(), LowerGlobalTLSAddress(), LowerINLINEASM(), LowerINSERT_SUBVECTOR(), LowerINSERT_VECTOR_ELT(), LowerINTRINSIC_VOID(), LowerINTRINSIC_WO_CHAIN(), LowerJumpTable(), LowerLoad(), LowerPREFETCH(), LowerREADCYCLECOUNTER(), LowerRETURNADDR(), LowerROTL(), LowerSETCC(), LowerStore(), LowerUAddSubO(), LowerUAddSubOCarry(), LowerVACOPY(), LowerVASTART(), LowerVECTOR_SHIFT(), LowerVECTOR_SHUFFLE(), LowerVSELECT(), llvm::HexagonISD::OP_BEGIN, llvm::HexagonISD::OP_END, llvm::ISD::PREFETCH, llvm::ISD::READCYCLECOUNTER, llvm::ISD::RETURNADDR, llvm::ISD::ROTL, llvm::ISD::SETCC, llvm::ISD::SHL, llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::STORE, llvm::ISD::UADDO, llvm::ISD::UADDO_CARRY, llvm::ISD::USUBO, llvm::ISD::USUBO_CARRY, llvm::ISD::VACOPY, llvm::ISD::VASTART, llvm::ISD::VECTOR_SHUFFLE, and llvm::ISD::VSELECT.
LowerOperationWrapper()
void HexagonTargetLowering::LowerOperationWrapper (SDNode * N, SmallVectorImpl< SDValue > & Results, SelectionDAG & DAG) const override virtual
This callback is invoked by the type legalizer to legalize nodes with an illegal operand type but legal result types.
Places new result values for the node in Results (their number and types must exactly match those of the original return values of the node), or leaves Results empty, which indicates that the node is not to be custom lowered after all.
It replaces the LowerOperation callback in the type Legalizer. The reason we can not do away with LowerOperation entirely is that LegalizeDAG isn't yet ready to use this callback.
TODO: Consider merging with ReplaceNodeResults.
The target places new result values for the node in Results (their number and types must exactly match those of the original return values of the node), or leaves Results empty, which indicates that the node is not to be custom lowered after all. The default implementation calls LowerOperation.
Reimplemented from llvm::TargetLowering.
Definition at line 3388 of file HexagonISelLowering.cpp.
References llvm::Function::empty(), llvm::TargetLowering::LowerOperationWrapper(), N, Results, llvm::HexagonISD::SSAT, llvm::ISD::STORE, and llvm::HexagonISD::USAT.
LowerPREFETCH()
SDValue HexagonTargetLowering::LowerPREFETCH (SDValue Op, SelectionDAG & DAG) const
Definition at line 705 of file HexagonISelLowering.cpp.
References Addr, llvm::HexagonISD::DCFETCH, DL, llvm::SelectionDAG::getConstant(), and llvm::SelectionDAG::getNode().
Referenced by LowerOperation().
LowerREADCYCLECOUNTER()
SDValue HexagonTargetLowering::LowerREADCYCLECOUNTER (SDValue Op, SelectionDAG & DAG) const
Definition at line 720 of file HexagonISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getVTList(), and llvm::HexagonISD::READCYCLE.
Referenced by LowerOperation().
LowerReturn()
SDValue HexagonTargetLowering::LowerReturn (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::OutputArg > & , const SmallVectorImpl< SDValue > & , const SDLoc & , SelectionDAG &) const override virtual
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG.
The implementation should return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 201 of file HexagonISelLowering.cpp.
References llvm::CCValAssign::AExt, llvm::CCState::AnalyzeReturn(), llvm::ISD::ANY_EXTEND, llvm::CCValAssign::BCvt, llvm::CCValAssign::Full, llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyToReg(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getRegister(), llvm::SDValue::getValue(), llvm_unreachable, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::HexagonISD::RET_GLUE, llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, llvm::SmallVectorBase< Size_T >::size(), llvm::HexagonSubtarget::useHVXOps(), llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
LowerRETURNADDR()
SDValue HexagonTargetLowering::LowerRETURNADDR (SDValue Op, SelectionDAG & DAG) const
Definition at line 1167 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::MachineFunction::addLiveIn(), llvm::Depth, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getRegClassFor(), llvm::HexagonSubtarget::getRegisterInfo(), LowerFRAMEADDR(), llvm::Offset, llvm::MachineFrameInfo::setReturnAddressIsTaken(), and llvm::TargetLowering::verifyReturnAddressArgumentIsConstant().
Referenced by LowerOperation().
LowerROTL()
SDValue HexagonTargetLowering::LowerROTL (SDValue Op, SelectionDAG & DAG) const
Definition at line 2445 of file HexagonISelLowering.cpp.
Referenced by LowerOperation().
LowerSETCC()
SDValue HexagonTargetLowering::LowerSETCC (SDValue Op, SelectionDAG & DAG) const
Definition at line 1028 of file HexagonISelLowering.cpp.
References assert(), llvm::ISD::AssertSext, llvm::CallingConv::C, CC, llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::MVT::getSizeInBits(), llvm::EVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::MVT::isScalarInteger(), llvm::MVT::isVector(), LHS, llvm::ISD::LOAD, N, RHS, and llvm::ISD::TRUNCATE.
Referenced by LowerOperation().
LowerSIGN_EXTEND()
SDValue llvm::HexagonTargetLowering::LowerSIGN_EXTEND (SDValue Op, SelectionDAG & DAG) const
LowerStore()
SDValue HexagonTargetLowering::LowerStore (SDValue Op, SelectionDAG & DAG) const
Definition at line 3123 of file HexagonISelLowering.cpp.
References llvm::TargetLowering::expandUnalignedStore(), llvm::LSBaseSDNode::getAddressingMode(), llvm::MemSDNode::getAlign(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getIndexedStore(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::StoreSDNode::getOffset(), llvm::EVT::getSimpleVT(), llvm::SelectionDAG::getTruncStore(), llvm::HexagonSubtarget::getTypeAlignment(), llvm::StoreSDNode::getValue(), and llvm::LSBaseSDNode::isIndexed().
Referenced by LowerOperation().
LowerToTLSGeneralDynamicModel()
SDValue HexagonTargetLowering::LowerToTLSGeneralDynamicModel (GlobalAddressSDNode * GA, SelectionDAG & DAG) const
Definition at line 1376 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::HexagonISD::CONST32, llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), GetDynamicTLSAddr(), llvm::SelectionDAG::getEntryNode(), llvm::GlobalAddressSDNode::getGlobal(), llvm::SelectionDAG::getNode(), llvm::GlobalAddressSDNode::getOffset(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getSubtarget(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SDValue::getValue(), llvm::HexagonII::HMOTF_ConstExtended, LowerGLOBAL_OFFSET_TABLE(), llvm::HexagonII::MO_GDGOT, llvm::HexagonII::MO_GDPLT, llvm::Offset, and Sym.
Referenced by LowerGlobalTLSAddress().
LowerToTLSInitialExecModel()
SDValue HexagonTargetLowering::LowerToTLSInitialExecModel (GlobalAddressSDNode * GA, SelectionDAG & DAG) const
Definition at line 1312 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::HexagonISD::CONST32, llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::GlobalAddressSDNode::getGlobal(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getNode(), llvm::GlobalAddressSDNode::getOffset(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::TargetLowering::isPositionIndependent(), LowerGLOBAL_OFFSET_TABLE(), llvm::HexagonII::MO_IE, llvm::HexagonII::MO_IEGOT, llvm::Offset, and Sym.
Referenced by LowerGlobalTLSAddress().
LowerToTLSLocalExecModel()
SDValue HexagonTargetLowering::LowerToTLSLocalExecModel (GlobalAddressSDNode * GA, SelectionDAG & DAG) const
Definition at line 1354 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::HexagonISD::CONST32, llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::GlobalAddressSDNode::getGlobal(), llvm::SelectionDAG::getNode(), llvm::GlobalAddressSDNode::getOffset(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::HexagonII::MO_TPREL, llvm::Offset, and Sym.
Referenced by LowerGlobalTLSAddress().
LowerUAddSubO()
SDValue HexagonTargetLowering::LowerUAddSubO (SDValue Op, SelectionDAG & DAG) const
Definition at line 3241 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getSetCC(), llvm::SDVTList::NumVTs, llvm::ISD::SETEQ, llvm::ISD::SUB, llvm::ISD::UADDO, llvm::ISD::USUBO, llvm::SDVTList::VTs, X, and Y.
Referenced by LowerOperation().
LowerUAddSubOCarry()
SDValue HexagonTargetLowering::LowerUAddSubOCarry (SDValue Op, SelectionDAG & DAG) const
Definition at line 3277 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::ADDC, llvm::CallingConv::C, llvm::SelectionDAG::getLogicalNOT(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValue(), llvm::HexagonISD::SUBC, llvm::ISD::UADDO_CARRY, X, and Y.
Referenced by LowerOperation().
LowerUnalignedLoad()
SDValue HexagonTargetLowering::LowerUnalignedLoad (SDValue Op, SelectionDAG & DAG) const
Definition at line 3153 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, llvm::Aligned, AlignLoads, llvm::TargetLoweringBase::allowsMemoryAccessForAlignment(), assert(), llvm::sampleprof::Base, DL, llvm::TargetLowering::expandUnalignedLoad(), llvm::MemSDNode::getAlign(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::TypeSize::getFixed(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMachineMemOperand(), llvm::SelectionDAG::getMemBasePlusOffset(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MVT::getSizeInBits(), llvm::HexagonSubtarget::getTypeAlignment(), llvm::SDValue::getValue(), llvm::MVT::getVectorVT(), llvm::LSBaseSDNode::isUnindexed(), P, llvm::ISD::TokenFactor, llvm::HexagonISD::VALIGN, llvm::HexagonISD::VALIGNADDR, and llvm::Align::value().
Referenced by LowerLoad().
LowerVACOPY()
SDValue HexagonTargetLowering::LowerVACOPY (SDValue Op, SelectionDAG & DAG) const
Definition at line 1011 of file HexagonISelLowering.cpp.
References assert(), DL, llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMemcpy(), and llvm::HexagonSubtarget::isEnvironmentMusl().
Referenced by LowerOperation().
LowerVASTART()
SDValue HexagonTargetLowering::LowerVASTART (SDValue Op, SelectionDAG & DAG) const
Definition at line 944 of file HexagonISelLowering.cpp.
References llvm::ISD::ADD, Addr, DL, llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getFrameIndex(), llvm::HexagonSubtarget::getFrameLowering(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getStore(), llvm::HexagonMachineFunctionInfo::getVarArgsFrameIndex(), llvm::HexagonSubtarget::isEnvironmentMusl(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and llvm::ISD::TokenFactor.
Referenced by LowerOperation().
LowerVECTOR_SHIFT()
SDValue HexagonTargetLowering::LowerVECTOR_SHIFT (SDValue Op, SelectionDAG & DAG) const
Definition at line 2398 of file HexagonISelLowering.cpp.
References A, assert(), llvm::ISD::CONCAT_VECTORS, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::HexagonISD::VASL, llvm::HexagonISD::VASR, and llvm::HexagonISD::VLSR.
Referenced by LowerOperation().
LowerVECTOR_SHUFFLE()
SDValue HexagonTargetLowering::LowerVECTOR_SHUFFLE (SDValue Op, SelectionDAG & DAG) const
Definition at line 2236 of file HexagonISelLowering.cpp.
References assert(), llvm::ArrayRef< T >::begin(), llvm::ISD::BSWAP, llvm::ShuffleVectorSDNode::commuteMask(), llvm::ArrayRef< T >::data(), llvm::ArrayRef< T >::end(), F, llvm::find_if(), llvm::SelectionDAG::getBitcast(), llvm::SelectionDAG::getNode(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::MVT::getVectorElementType(), llvm::HexagonSubtarget::isHVXVectorType(), P, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ArrayRef< T >::size(), llvm::SmallVectorBase< Size_T >::size(), std::swap(), and T1.
Referenced by LowerOperation().
LowerVSELECT()
SDValue HexagonTargetLowering::LowerVSELECT (SDValue Op, SelectionDAG & DAG) const
Definition at line 1088 of file HexagonISelLowering.cpp.
References assert(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), and llvm::MVT::isScalarInteger().
Referenced by LowerOperation().
LowerZERO_EXTEND()
SDValue llvm::HexagonTargetLowering::LowerZERO_EXTEND (SDValue Op, SelectionDAG & DAG) const
mayBeEmittedAsTailCall()
bool HexagonTargetLowering::mayBeEmittedAsTailCall (const CallInst *) const override virtual
Return true if the target may be able emit the call instruction as a tail call.
This is used by optimization passes to determine if it's profitable to duplicate return instructions to enable tailcall optimization.
Reimplemented from llvm::TargetLowering.
Definition at line 263 of file HexagonISelLowering.cpp.
References llvm::CallInst::isTailCall().
PerformDAGCombine()
SDValue HexagonTargetLowering::PerformDAGCombine (SDNode * N, DAGCombinerInfo & DCI) const override virtual
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
The semantics are as follows: Return Value: SDValue.Val == 0 - No change was made SDValue.Val == N - N was replaced, is dead, and is already handled. otherwise - N should be replaced by the returned Operand.
In addition, methods provided by DAGCombinerInfo may be used to perform more complex transformations.
Reimplemented from llvm::TargetLowering.
Definition at line 3449 of file HexagonISelLowering.cpp.
References A, llvm::EVT::bitsGT(), llvm::ISD::BUILD_PAIR, llvm::HexagonISD::COMBINE, Cond, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalizeOps(), N, llvm::ISD::OR, P, llvm::HexagonISD::P2D, llvm::HexagonISD::PFALSE, llvm::HexagonISD::PTRUE, llvm::ISD::SHL, std::swap(), T1, llvm::ISD::TRUNCATE, llvm::ISD::VSELECT, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
ReplaceNodeResults()
void HexagonTargetLowering::ReplaceNodeResults (SDNode * , SmallVectorImpl< SDValue > & , SelectionDAG &) const override virtual
This callback is invoked when a node result type is illegal for the target, and the operation was registered to use 'custom' lowering for that result type.
The target places new result values for the node in Results (their number and types must exactly match those of the original return values of the node), or leaves Results empty, which indicates that the node is not to be custom lowered after all.
If the target has no operations that require custom lowering, it need not implement this. The default implementation aborts.
Reimplemented from llvm::TargetLowering.
Definition at line 3419 of file HexagonISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::Function::empty(), llvm::SelectionDAG::getAnyExtOrTrunc(), N, P, Results, llvm::ISD::SHL, llvm::ISD::SRA, and llvm::ISD::SRL.
shouldExpandAtomicCmpXchgInIR()
TargetLowering::AtomicExpansionKind HexagonTargetLowering::shouldExpandAtomicCmpXchgInIR (AtomicCmpXchgInst * AI) const override virtual
Returns how the given atomic cmpxchg should be expanded by the IR-level AtomicExpand pass.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3895 of file HexagonISelLowering.cpp.
References llvm::TargetLoweringBase::LLSC.
shouldExpandAtomicLoadInIR()
TargetLowering::AtomicExpansionKind HexagonTargetLowering::shouldExpandAtomicLoadInIR (LoadInst * LI) const override virtual
Returns how the given (atomic) load should be expanded by the IR-level AtomicExpand pass.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3879 of file HexagonISelLowering.cpp.
References llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::TargetLoweringBase::LLOnly, and llvm::TargetLoweringBase::None.
shouldExpandAtomicRMWInIR()
AtomicExpansionKind llvm::HexagonTargetLowering::shouldExpandAtomicRMWInIR (AtomicRMWInst * RMW) const inline override virtual
Returns how the IR-level AtomicExpand pass should expand the given AtomicRMW, if at all.
Default is to never expand.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 359 of file HexagonISelLowering.h.
References llvm::TargetLoweringBase::LLSC.
shouldExpandAtomicStoreInIR()
TargetLowering::AtomicExpansionKind HexagonTargetLowering::shouldExpandAtomicStoreInIR (StoreInst * SI) const override virtual
Returns how the given (atomic) store should be expanded by the IR-level AtomicExpand pass into.
For instance AtomicExpansionKind::Expand will try to use an atomicrmw xchg.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3887 of file HexagonISelLowering.cpp.
References llvm::TargetLoweringBase::Expand, and llvm::TargetLoweringBase::None.
shouldExpandBuildVectorWithShuffles()
bool HexagonTargetLowering::shouldExpandBuildVectorWithShuffles (EVT VT, unsigned DefinedValues) const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 2158 of file HexagonISelLowering.cpp.
shouldReduceLoadWidth()
bool HexagonTargetLowering::shouldReduceLoadWidth (SDNode * Load, ISD::LoadExtType ExtTy, EVT NewVT) const override virtual
Return true if it is profitable to reduce a load to a smaller type.
Example: (i16 (trunc (i32 (load x))) -> i16 load x
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3814 of file HexagonISelLowering.cpp.
References llvm::HexagonISD::CONST32_GP, llvm::HexagonTargetMachine::getObjFileLowering(), llvm::TargetLoweringBase::getTargetMachine(), llvm::HexagonTargetObjectFile::isGlobalInSmallSection(), and llvm::TargetLoweringBase::shouldReduceLoadWidth().
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonISelLowering.h
lib/Target/Hexagon/HexagonISelLowering.cpp
lib/Target/Hexagon/HexagonISelLoweringHVX.cpp