LLVM: llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5 Class Reference
llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5 Class Reference final
#include "Target/AMDGPU/AMDGPUHSAMetadataStreamer.h"
Public Member Functions
MetadataStreamerMsgPackV5 ()=default
~MetadataStreamerMsgPackV5 ()=default
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4
MetadataStreamerMsgPackV4 ()=default
~MetadataStreamerMsgPackV4 ()=default
bool emitTo (AMDGPUTargetStreamer &TargetStreamer) override
void begin (const Module &Mod, const IsaInfo::AMDGPUTargetID &TargetID) override
void end () override
void emitKernel (const MachineFunction &MF, const SIProgramInfo &ProgramInfo) override
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamer
virtual ~MetadataStreamer ()=default
virtual bool emitTo (AMDGPUTargetStreamer &TargetStreamer)=0
virtual void begin (const Module &Mod, const IsaInfo::AMDGPUTargetID &TargetID)=0
virtual void end ()=0
virtual void emitKernel (const MachineFunction &MF, const SIProgramInfo &ProgramInfo)=0
Protected Member Functions
void emitVersion () override
void emitHiddenKernelArgs (const MachineFunction &MF, unsigned &Offset, msgpack::ArrayDocNode Args) override
void emitKernelAttrs (const Function &Func, msgpack::MapDocNode Kern) override
Protected Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4
void dump (StringRef HSAMetadataString) const
void verify (StringRef HSAMetadataString) const
std::optional< StringRef > getAccessQualifier (StringRef AccQual) const
std::optional< StringRef > getAddressSpaceQualifier (unsigned AddressSpace) const
StringRef getValueKind (Type *Ty, StringRef TypeQual, StringRef BaseTypeName) const
std::string getTypeName (Type *Ty, bool Signed) const
msgpack::ArrayDocNode getWorkGroupDimensions (MDNode *Node) const
msgpack::MapDocNode getHSAKernelProps (const MachineFunction &MF, const SIProgramInfo &ProgramInfo, unsigned CodeObjectVersion) const
void emitVersion () override
void emitTargetID (const IsaInfo::AMDGPUTargetID &TargetID)
void emitPrintf (const Module &Mod)
void emitKernelLanguage (const Function &Func, msgpack::MapDocNode Kern)
void emitKernelAttrs (const Function &Func, msgpack::MapDocNode Kern) override
void emitKernelArgs (const MachineFunction &MF, msgpack::MapDocNode Kern)
void emitKernelArg (const Argument &Arg, unsigned &Offset, msgpack::ArrayDocNode Args)
void emitKernelArg (const DataLayout &DL, Type *Ty, Align Alignment, StringRef ValueKind, unsigned &Offset, msgpack::ArrayDocNode Args, MaybeAlign PointeeAlign=std::nullopt, StringRef Name="", StringRef TypeName="", StringRef BaseTypeName="", StringRef ActAccQual="", StringRef AccQual="", StringRef TypeQual="")
void emitHiddenKernelArgs (const MachineFunction &MF, unsigned &Offset, msgpack::ArrayDocNode Args) override
msgpack::DocNode & getRootMetadata (StringRef Key)
msgpack::DocNode & getHSAMetadataRoot ()
virtual void emitVersion ()=0
virtual void emitHiddenKernelArgs (const MachineFunction &MF, unsigned &Offset, msgpack::ArrayDocNode Args)=0
virtual void emitKernelAttrs (const Function &Func, msgpack::MapDocNode Kern)=0
Additional Inherited Members
Protected Attributes inherited from llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4
std::unique_ptr< msgpack::Document > HSAMetadataDoc
Detailed Description
Definition at line 138 of file AMDGPUHSAMetadataStreamer.h.
Constructor & Destructor Documentation
MetadataStreamerMsgPackV5()
llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::MetadataStreamerMsgPackV5 () default
~MetadataStreamerMsgPackV5()
llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::~MetadataStreamerMsgPackV5 () default
Member Function Documentation
emitHiddenKernelArgs()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs (const MachineFunction & MF, unsigned & Offset, msgpack::ArrayDocNode Args) override protected virtual
Reimplemented from llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4.
Definition at line 565 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::alignTo(), DL, llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitKernelArg(), llvm::PointerType::get(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::Type::getInt16Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::MachineFunction::getSubtarget(), llvm::SIMachineFunctionInfo::getUserSGPRInfo(), llvm::AMDGPUAS::GLOBAL_ADDRESS, llvm::GCNUserSGPRUsageInfo::hasQueuePtr(), Int32Ty, llvm::AMDGPUMachineFunction::isDynamicLDSUsed(), and llvm::Offset.
emitKernelAttrs()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitKernelAttrs (const Function & Func, msgpack::MapDocNode Kern) override protected virtual
Reimplemented from llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4.
Definition at line 673 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::emitKernelAttrs(), llvm::msgpack::DocNode::getDocument(), and llvm::msgpack::Document::getNode().
emitVersion()
void llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitVersion () override protected virtual
Reimplemented from llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4.
Definition at line 558 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::getRootMetadata(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV4::HSAMetadataDoc, llvm::AMDGPU::HSAMD::VersionMajorV5, and llvm::AMDGPU::HSAMD::VersionMinorV5.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.h
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.cpp