LLVM: llvm::AVRAsmBackend Class Reference
llvm::AVRAsmBackend Class Reference
Utilities for manipulating generated AVR machine code.
#include "Target/AVR/MCTargetDesc/AVRAsmBackend.h"
Public Member Functions
AVRAsmBackend (Triple::OSType OSType)
void adjustFixupValue (const MCFixup &Fixup, const MCValue &Target, uint64_t &Value, MCContext *Ctx=nullptr) const
std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const override
void applyFixup (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo *STI) const override
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
std::optional< MCFixupKind > getFixupKind (StringRef Name) const override
Map a relocation name used in .reloc to a fixup kind.
const MCFixupKindInfo & getFixupKindInfo (MCFixupKind Kind) const override
Get information on a fixup kind.
unsigned getNumFixupKinds () const override
Get the number of target specific fixup kinds.
bool fixupNeedsRelaxation (const MCFixup &Fixup, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout) const override
Simple predicate for targets where !Resolved implies requiring relaxation.
bool writeNopData (raw_ostream &OS, uint64_t Count, const MCSubtargetInfo *STI) const override
Write an (optimal) nop sequence of Count bytes to the given output.
bool shouldForceRelocation (const MCAssembler &Asm, const MCFixup &Fixup, const MCValue &Target, const MCSubtargetInfo *STI) override
Hook to check if a relocation is needed for some target specific reason.
Public Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (const MCAsmBackend &)=delete
MCAsmBackend & operator= (const MCAsmBackend &)=delete
virtual ~MCAsmBackend ()
virtual bool allowAutoPadding () const
Return true if this target might automatically pad instructions and thus need to emit padding enable/disable directives around sensative code.
virtual bool allowEnhancedRelaxation () const
Return true if this target allows an unrelaxable instruction to be emitted into RelaxableFragment and then we can increase its size in a tricky way for optimization.
virtual void emitInstructionBegin (MCObjectStreamer &OS, const MCInst &Inst, const MCSubtargetInfo &STI)
Give the target a chance to manipulate state related to instruction alignment (e.g.
virtual void emitInstructionEnd (MCObjectStreamer &OS, const MCInst &Inst)
virtual void reset ()
lifetime management
std::unique_ptr< MCObjectWriter > createObjectWriter (raw_pwrite_stream &OS) const
Create a new MCObjectWriter instance for use by the assembler backend to emit the final object file.
std::unique_ptr< MCObjectWriter > createDwoObjectWriter (raw_pwrite_stream &OS, raw_pwrite_stream &DwoOS) const
Create an MCObjectWriter that writes two object files: a .o file which is linked into the final program and a .dwo file which is used by debuggers.
virtual std::unique_ptr< MCObjectTargetWriter > createObjectTargetWriter () const =0
virtual unsigned getMinimumNopSize () const
Returns the minimum size of a nop in bytes on this target.
virtual unsigned getMaximumNopSize (const MCSubtargetInfo &STI) const
Returns the maximum size of a nop in bytes on this target.
virtual bool writeNopData (raw_ostream &OS, uint64_t Count, const MCSubtargetInfo *STI) const =0
Write an (optimal) nop sequence of Count bytes to the given output.
virtual void finishLayout (MCAssembler const &Asm, MCAsmLayout &Layout) const
Give backend an opportunity to finish layout after relaxation.
virtual void handleAssemblerFlag (MCAssemblerFlag Flag)
Handle any target-specific assembler flags. By default, do nothing.
virtual uint32_t generateCompactUnwindEncoding (const MCDwarfFrameInfo *FI, const MCContext *Ctxt) const
Generate the compact unwind encoding for the CFI instructions.
virtual bool isMicroMips (const MCSymbol *Sym) const
Check whether a given symbol has been flagged with MICROMIPS flag.
bool isDarwinCanonicalPersonality (const MCSymbol *Sym) const
virtual bool shouldInsertExtraNopBytesForCodeAlign (const MCAlignFragment &AF, unsigned &Size)
Hook to check if extra nop bytes must be inserted for alignment directive.
virtual bool shouldInsertFixupForCodeAlign (MCAssembler &Asm, const MCAsmLayout &Layout, MCAlignFragment &AF)
Hook which indicates if the target requires a fixup to be generated when handling an align directive in an executable section.
virtual bool evaluateTargetFixup (const MCAssembler &Asm, const MCAsmLayout &Layout, const MCFixup &Fixup, const MCFragment *DF, const MCValue &Target, const MCSubtargetInfo *STI, uint64_t &Value, bool &WasForced)
virtual bool handleAddSubRelocations (const MCAsmLayout &Layout, const MCFragment &F, const MCFixup &Fixup, const MCValue &Target, uint64_t &FixedValue) const
virtual bool mayNeedRelaxation (const MCInst &Inst, const MCSubtargetInfo &STI) const
Check whether the given instruction may need relaxation.
virtual bool fixupNeedsRelaxationAdvanced (const MCFixup &Fixup, bool Resolved, uint64_t Value, const MCRelaxableFragment *DF, const MCAsmLayout &Layout, const bool WasForced) const
Target specific predicate for whether a given fixup requires the associated instruction to be relaxed.
virtual void relaxInstruction (MCInst &Inst, const MCSubtargetInfo &STI) const
Relax the instruction in the given fragment to the next wider instruction.
virtual bool relaxDwarfLineAddr (MCDwarfLineAddrFragment &DF, MCAsmLayout &Layout, bool &WasRelaxed) const
virtual bool relaxDwarfCFA (MCDwarfCallFrameFragment &DF, MCAsmLayout &Layout, bool &WasRelaxed) const
virtual std::pair< bool, bool > relaxLEB128 (MCLEBFragment &LF, MCAsmLayout &Layout, int64_t &Value) const
Additional Inherited Members
Public Attributes inherited from llvm::MCAsmBackend
const llvm::endianness Endian
const unsigned RelaxFixupKind
Fixup kind used for linker relaxation. Currently only used by RISC-V.
Protected Member Functions inherited from llvm::MCAsmBackend
MCAsmBackend (llvm::endianness Endian, unsigned RelaxFixupKind=MaxFixupKind)
Detailed Description
Utilities for manipulating generated AVR machine code.
Definition at line 29 of file AVRAsmBackend.h.
Constructor & Destructor Documentation
AVRAsmBackend()
llvm::AVRAsmBackend::AVRAsmBackend (Triple::OSType OSType) inline
Definition at line 31 of file AVRAsmBackend.h.
Member Function Documentation
adjustFixupValue()
void llvm::AVRAsmBackend::adjustFixupValue (const MCFixup & Fixup, const MCValue & Target, uint64_t & Value, MCContext * Ctx = nullptr) const
Definition at line 252 of file AVRAsmBackend.cpp.
References adjust::ldi::fixup(), Fixup, adjust::fixup_13_pcrel(), llvm::AVR::fixup_13_pcrel, llvm::AVR::fixup_16, llvm::AVR::fixup_16_pm, adjust::fixup_6(), llvm::AVR::fixup_6, adjust::fixup_6_adiw(), llvm::AVR::fixup_6_adiw, adjust::fixup_7_pcrel(), llvm::AVR::fixup_7_pcrel, adjust::fixup_call(), llvm::AVR::fixup_call, llvm::AVR::fixup_hh8_ldi, llvm::AVR::fixup_hh8_ldi_neg, llvm::AVR::fixup_hh8_ldi_pm, llvm::AVR::fixup_hh8_ldi_pm_neg, llvm::AVR::fixup_hi8_ldi, llvm::AVR::fixup_hi8_ldi_gs, llvm::AVR::fixup_hi8_ldi_neg, llvm::AVR::fixup_hi8_ldi_pm, llvm::AVR::fixup_hi8_ldi_pm_neg, llvm::AVR::fixup_ldi, adjust::fixup_lds_sts_16(), llvm::AVR::fixup_lds_sts_16, llvm::AVR::fixup_lo8_ldi, llvm::AVR::fixup_lo8_ldi_gs, llvm::AVR::fixup_lo8_ldi_neg, llvm::AVR::fixup_lo8_ldi_pm, llvm::AVR::fixup_lo8_ldi_pm_neg, llvm::AVR::fixup_ms8_ldi, llvm::AVR::fixup_ms8_ldi_neg, adjust::fixup_port5(), llvm::AVR::fixup_port5, adjust::fixup_port6(), llvm::AVR::fixup_port6, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_GPRel_4, getFixupKindInfo(), adjust::ldi::hh8(), adjust::ldi::hi8(), llvm_unreachable, adjust::ldi::lo8(), adjust::ldi::ms8(), adjust::ldi::neg(), adjust::pm(), Size, llvm::MCFixupKindInfo::TargetSize, and adjust::unsigned_width().
Referenced by applyFixup().
applyFixup()
void llvm::AVRAsmBackend::applyFixup (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target, MutableArrayRef< char > Data, uint64_t Value, bool IsResolved, const MCSubtargetInfo * STI) const override virtual
Apply the Value for given Fixup into the provided data fragment, at the offset specified by the fixup and following the fixup kind as appropriate.
Errors (such as an out of range fixup value) should be reported via Ctx. The STI is present only for fragments of type MCRelaxableFragment and MCDataFragment with hasInstructions() == true.
Implements llvm::MCAsmBackend.
Definition at line 378 of file AVRAsmBackend.cpp.
References adjustFixupValue(), assert(), llvm::Data, llvm::FirstLiteralRelocationKind, Fixup, getFixupKindInfo(), Info, and llvm::Offset.
createObjectTargetWriter()
std::unique_ptr< MCObjectTargetWriter > llvm::AVRAsmBackend::createObjectTargetWriter () const override virtual
Implements llvm::MCAsmBackend.
Definition at line 374 of file AVRAsmBackend.cpp.
References llvm::createAVRELFObjectWriter(), and llvm::MCELFObjectTargetWriter::getOSABI().
fixupNeedsRelaxation()
bool llvm::AVRAsmBackend::fixupNeedsRelaxation (const MCFixup & Fixup, uint64_t Value, const MCRelaxableFragment * DF, const MCAsmLayout & Layout) const inline override virtual
Simple predicate for targets where !Resolved implies requiring relaxation.
Implements llvm::MCAsmBackend.
Definition at line 52 of file AVRAsmBackend.h.
References llvm_unreachable.
getFixupKind()
std::optional< MCFixupKind > llvm::AVRAsmBackend::getFixupKind (StringRef Name) const override virtual
Map a relocation name used in .reloc to a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 409 of file AVRAsmBackend.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::StringSwitch< T, R >::Default(), llvm::FirstLiteralRelocationKind, and Name.
getFixupKindInfo()
MCFixupKindInfo const & llvm::AVRAsmBackend::getFixupKindInfo (MCFixupKind Kind) const override virtual
Get information on a fixup kind.
Reimplemented from llvm::MCAsmBackend.
Definition at line 424 of file AVRAsmBackend.cpp.
References assert(), llvm::FirstLiteralRelocationKind, llvm::FirstTargetFixupKind, llvm::FK_NONE, llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::MCAsmBackend::getFixupKindInfo(), getNumFixupKinds(), and llvm::AVR::NumTargetFixupKinds.
Referenced by adjustFixupValue(), and applyFixup().
getNumFixupKinds()
unsigned llvm::AVRAsmBackend::getNumFixupKinds () const inline override virtual
Get the number of target specific fixup kinds.
Implements llvm::MCAsmBackend.
Definition at line 48 of file AVRAsmBackend.h.
References llvm::AVR::NumTargetFixupKinds.
Referenced by getFixupKindInfo().
shouldForceRelocation()
bool llvm::AVRAsmBackend::shouldForceRelocation (const MCAssembler & Asm, const MCFixup & Fixup, const MCValue & Target, const MCSubtargetInfo * STI) override virtual
Hook to check if a relocation is needed for some target specific reason.
Reimplemented from llvm::MCAsmBackend.
Definition at line 508 of file AVRAsmBackend.cpp.
References llvm::FirstLiteralRelocationKind, Fixup, llvm::AVR::fixup_13_pcrel, llvm::AVR::fixup_7_pcrel, and llvm::AVR::fixup_call.
writeNopData()
bool llvm::AVRAsmBackend::writeNopData (raw_ostream & OS, uint64_t Count, const MCSubtargetInfo * STI) const override virtual
Write an (optimal) nop sequence of Count bytes to the given output.
If the target cannot generate such a sequence, it should return an error.
Returns
- True on success.
Implements llvm::MCAsmBackend.
Definition at line 497 of file AVRAsmBackend.cpp.
References assert(), and OS.
The documentation for this class was generated from the following files:
lib/Target/AVR/MCTargetDesc/AVRAsmBackend.h
lib/Target/AVR/MCTargetDesc/AVRAsmBackend.cpp