LLVM: lib/Target/CSKY/MCTargetDesc/CSKYMCTargetDesc.cpp File Reference
CSKYMCTargetDesc.cpp File Reference
#include "CSKYMCTargetDesc.h"
#include "CSKYAsmBackend.h"
#include "CSKYELFStreamer.h"
#include "CSKYInstPrinter.h"
#include "CSKYMCAsmInfo.h"
#include "CSKYMCCodeEmitter.h"
#include "CSKYTargetStreamer.h"
#include "TargetInfo/CSKYTargetInfo.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "CSKYGenInstrInfo.inc"
#include "CSKYGenRegisterInfo.inc"
#include "CSKYGenSubtargetInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
This file provides CSKY specific target descriptions.
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_REGINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Functions
static MCAsmInfo * createCSKYMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &Options)
static MCInstrInfo * createCSKYMCInstrInfo ()
static MCInstPrinter * createCSKYMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCRegisterInfo * createCSKYMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createCSKYMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCTargetStreamer * createCSKYObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
static MCStreamer * createELFStreamer (const Triple &T, MCContext &Ctx, std::unique_ptr< MCAsmBackend > &&MAB, std::unique_ptr< MCObjectWriter > &&OW, std::unique_ptr< MCCodeEmitter > &&Emitter, bool RelaxAll)
static MCTargetStreamer * createCSKYAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *InstPrinter, bool isVerboseAsm)
static MCTargetStreamer * createCSKYNullTargetStreamer (MCStreamer &S)
static MCInstrAnalysis * createCSKYInstrAnalysis (const MCInstrInfo *Info)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeCSKYTargetMC ()
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 29 of file CSKYMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
This file provides CSKY specific target descriptions.
Definition at line 28 of file CSKYMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 32 of file CSKYMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 35 of file CSKYMCTargetDesc.cpp.
Function Documentation
createCSKYAsmTargetStreamer()
static MCTargetStreamer * createCSKYAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * InstPrinter, bool isVerboseAsm) static
Definition at line 101 of file CSKYMCTargetDesc.cpp.
References OS.
Referenced by LLVMInitializeCSKYTargetMC().
createCSKYInstrAnalysis()
static MCInstrAnalysis * createCSKYInstrAnalysis (const MCInstrInfo * Info) static
Definition at line 151 of file CSKYMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeCSKYTargetMC().
createCSKYMCAsmInfo()
static MCAsmInfo * createCSKYMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT, const MCTargetOptions & Options) static
Definition at line 40 of file CSKYMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::cfiDefCfa(), and MRI.
Referenced by LLVMInitializeCSKYTargetMC().
createCSKYMCInstPrinter()
static MCInstPrinter * createCSKYMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 58 of file CSKYMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeCSKYTargetMC().
createCSKYMCInstrInfo()
static MCInstrInfo * createCSKYMCInstrInfo () static
Definition at line 52 of file CSKYMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeCSKYTargetMC().
createCSKYMCRegisterInfo()
static MCRegisterInfo * createCSKYMCRegisterInfo (const Triple & TT) static
Definition at line 66 of file CSKYMCTargetDesc.cpp.
References Info.
Referenced by LLVMInitializeCSKYTargetMC().
createCSKYMCSubtargetInfo()
static MCSubtargetInfo * createCSKYMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 72 of file CSKYMCTargetDesc.cpp.
Referenced by LLVMInitializeCSKYTargetMC().
createCSKYNullTargetStreamer()
static MCTargetStreamer * createCSKYNullTargetStreamer (MCStreamer & S) static
Definition at line 108 of file CSKYMCTargetDesc.cpp.
Referenced by LLVMInitializeCSKYTargetMC().
createCSKYObjectTargetStreamer()
static MCTargetStreamer * createCSKYObjectTargetStreamer (MCStreamer & S, const MCSubtargetInfo & STI) static
Definition at line 81 of file CSKYMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getTargetTriple().
Referenced by LLVMInitializeCSKYTargetMC().
createELFStreamer()
static MCStreamer * createELFStreamer (const Triple & T, MCContext & Ctx, std::unique_ptr< MCAsmBackend > && MAB, std::unique_ptr< MCObjectWriter > && OW, std::unique_ptr< MCCodeEmitter > && Emitter, bool RelaxAll) static
Definition at line 88 of file CSKYMCTargetDesc.cpp.
References Emitter, llvm::MCObjectStreamer::getAssembler(), and llvm::MCAssembler::setRelaxAll().
Referenced by LLVMInitializeCSKYTargetMC().
LLVMInitializeCSKYTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeCSKYTargetMC ()
Definition at line 155 of file CSKYMCTargetDesc.cpp.
References llvm::createCSKYAsmBackend(), createCSKYAsmTargetStreamer(), createCSKYInstrAnalysis(), createCSKYMCAsmInfo(), llvm::createCSKYMCCodeEmitter(), createCSKYMCInstPrinter(), createCSKYMCInstrInfo(), createCSKYMCRegisterInfo(), createCSKYMCSubtargetInfo(), createCSKYNullTargetStreamer(), createCSKYObjectTargetStreamer(), createELFStreamer(), llvm::getTheCSKYTarget(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterELFStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCAsmInfo(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrAnalysis(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), and llvm::TargetRegistry::RegisterObjectTargetStreamer().