LLVM: lib/Target/DirectX/MCTargetDesc/DirectXMCTargetDesc.cpp File Reference
DirectXMCTargetDesc.cpp File Reference
This file contains DirectX target initializer.
#include "DirectXMCTargetDesc.h"
#include "DirectXContainerObjectWriter.h"
#include "TargetInfo/DirectXTargetInfo.h"
#include "llvm/MC/LaneBitmask.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCDXContainerWriter.h"
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSchedule.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Compiler.h"
#include "llvm/TargetParser/Triple.h"
#include <memory>
#include "DirectXGenInstrInfo.inc"
#include "DirectXGenSubtargetInfo.inc"
#include "DirectXGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_HELPERS
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstPrinter * createDXILMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
MCCodeEmitter * createDXILMCCodeEmitter (const MCInstrInfo &MCII, MCContext &Ctx)
MCAsmBackend * createDXILMCAsmBackend (const Target &T, const MCSubtargetInfo &STI, const MCRegisterInfo &MRI, const MCTargetOptions &Options)
static MCSubtargetInfo * createDirectXMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCRegisterInfo * createDirectXMCRegisterInfo (const Triple &Triple)
static MCInstrInfo * createDirectXMCInstrInfo ()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeDirectXTargetMC ()
Detailed Description
This file contains DirectX target initializer.
Definition in file DirectXMCTargetDesc.cpp.
Macro Definition Documentation
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 34 of file DirectXMCTargetDesc.cpp.
GET_INSTRINFO_MC_HELPERS
#define GET_INSTRINFO_MC_HELPERS
Definition at line 35 of file DirectXMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 41 of file DirectXMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 38 of file DirectXMCTargetDesc.cpp.
Function Documentation
createDirectXMCInstrInfo()
static MCInstrInfo * createDirectXMCInstrInfo () static
Definition at line 142 of file DirectXMCTargetDesc.cpp.
Referenced by LLVMInitializeDirectXTargetMC().
createDirectXMCRegisterInfo()
static MCRegisterInfo * createDirectXMCRegisterInfo (const Triple & Triple) static
Definition at line 138 of file DirectXMCTargetDesc.cpp.
Referenced by LLVMInitializeDirectXTargetMC().
createDirectXMCSubtargetInfo()
static MCSubtargetInfo * createDirectXMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 134 of file DirectXMCTargetDesc.cpp.
Referenced by LLVMInitializeDirectXTargetMC().
createDXILMCAsmBackend()
MCAsmBackend * createDXILMCAsmBackend (const Target & T, const MCSubtargetInfo & STI, const MCRegisterInfo & MRI, const MCTargetOptions & Options)
Definition at line 126 of file DirectXMCTargetDesc.cpp.
Referenced by LLVMInitializeDirectXTargetMC().
createDXILMCCodeEmitter()
MCCodeEmitter * createDXILMCCodeEmitter (const MCInstrInfo & MCII, MCContext & Ctx)
Definition at line 121 of file DirectXMCTargetDesc.cpp.
Referenced by LLVMInitializeDirectXTargetMC().
createDXILMCInstPrinter()
static MCInstPrinter * createDXILMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 111 of file DirectXMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeDirectXTargetMC().
LLVMInitializeDirectXTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeDirectXTargetMC ()
Definition at line 144 of file DirectXMCTargetDesc.cpp.
References createDirectXMCInstrInfo(), createDirectXMCRegisterInfo(), createDirectXMCSubtargetInfo(), createDXILMCAsmBackend(), createDXILMCCodeEmitter(), createDXILMCInstPrinter(), llvm::getTheDirectXTarget(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), and X.