LLVM: lib/DebugInfo/DWARF/DWARFDebugFrame.cpp File Reference
DWARFDebugFrame.cpp File Reference
#include "llvm/DebugInfo/DWARF/DWARFDebugFrame.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/BinaryFormat/Dwarf.h"
#include "llvm/DebugInfo/DIContext.h"
#include "llvm/DebugInfo/DWARF/DWARFDataExtractor.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cinttypes>
#include <cstdint>
#include <optional>
Macros
#define ENUM_TO_CSTR(e)
#define DECLARE_OP3(OP, OPTYPE0, OPTYPE1, OPTYPE2)
#define DECLARE_OP2(OP, OPTYPE0, OPTYPE1) DECLARE_OP3(OP, OPTYPE0, OPTYPE1, OT_None)
#define DECLARE_OP1(OP, OPTYPE0) DECLARE_OP2(OP, OPTYPE0, OT_None)
#define DECLARE_OP0(OP) DECLARE_OP1(OP, OT_None)
Functions
static void printRegister (raw_ostream &OS, DIDumpOptions DumpOpts, unsigned RegNum)
constexpr uint64_t getCIEId (bool IsDWARF64, bool IsEH)
static void LLVM_ATTRIBUTE_UNUSED dumpDataAux (DataExtractor Data, uint64_t Offset, int Length)
Variables
const uint8_t DWARF_CFI_PRIMARY_OPCODE_MASK = 0xc0
const uint8_t DWARF_CFI_PRIMARY_OPERAND_MASK = 0x3f
Macro Definition Documentation
DECLARE_OP0
#define DECLARE_OP0 (OP) DECLARE_OP1(OP, OT_None)
DECLARE_OP1
#define DECLARE_OP1 (OP, OPTYPE0) DECLARE_OP2(OP, OPTYPE0, OT_None)
DECLARE_OP2
#define DECLARE_OP2 (OP, OPTYPE0, OPTYPE1) DECLARE_OP3(OP, OPTYPE0, OPTYPE1, OT_None)
DECLARE_OP3
#define DECLARE_OP3 (OP, OPTYPE0, OPTYPE1, OPTYPE2)
Value:
  do {                                                                         \
    OpTypes[OP][0] = OPTYPE0;                                                  \
    OpTypes[OP][1] = OPTYPE1;                                                  \
    OpTypes[OP][2] = OPTYPE2;                                                  \
  } while (false)
ENUM_TO_CSTR
#define ENUM_TO_CSTR (e)
Value:
  case e:                                                                      \
    return #e;
Function Documentation
dumpDataAux()
static void LLVM_ATTRIBUTE_UNUSED dumpDataAux (DataExtractor Data, uint64_t Offset, int Length) static
Definition at line 1026 of file DWARFDebugFrame.cpp.
References llvm::Data, llvm::errs(), llvm::Length, llvm::Offset, and llvm::raw_ostream::write_hex().
getCIEId()
constexpr uint64_t getCIEId (bool IsDWARF64, bool IsEH) constexpr
Definition at line 936 of file DWARFDebugFrame.cpp.
References llvm::dwarf::DW64_CIE_ID, and llvm::dwarf::DW_CIE_ID.
Referenced by llvm::dwarf::CIE::dump(), and llvm::DWARFDebugFrame::parse().
printRegister()
static void printRegister (raw_ostream & OS, DIDumpOptions DumpOpts, unsigned RegNum) static
Definition at line 31 of file DWARFDebugFrame.cpp.
References llvm::DIDumpOptions::GetNameForDWARFReg, llvm::DIDumpOptions::IsEH, OS, and RegName.
Referenced by llvm::dwarf::UnwindLocation::dump(), and llvm::dwarf::RegisterLocations::dump().
Variable Documentation
DWARF_CFI_PRIMARY_OPCODE_MASK
const uint8_t DWARF_CFI_PRIMARY_OPCODE_MASK = 0xc0
Definition at line 252 of file DWARFDebugFrame.cpp.
Referenced by llvm::dwarf::CFIProgram::parse().
DWARF_CFI_PRIMARY_OPERAND_MASK
const uint8_t DWARF_CFI_PRIMARY_OPERAND_MASK = 0x3f
Definition at line 253 of file DWARFDebugFrame.cpp.
Referenced by llvm::dwarf::CFIProgram::parse().