LLVM: lib/DWARFLinker/Parallel/DWARFLinkerImpl.cpp File Reference
DWARFLinkerImpl.cpp File Reference
#include "DWARFLinkerImpl.h"
#include "DIEGenerator.h"
#include "DependencyTracker.h"
#include "llvm/DWARFLinker/Utils.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugAbbrev.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/Parallel.h"
#include "llvm/Support/ThreadPool.h"
Functions
static void resolveRelativeObjectPath (SmallVectorImpl< char > &Buf, DWARFDie CU)
Resolve the relative path to a build artifact referenced by DWARF by applying DW_AT_comp_dir.
static uint64_t getDwoId (const DWARFDie &CUDie)
static std::string remapPath (StringRef Path, const DWARFLinker::ObjectPrefixMapTy &ObjectPrefixMap)
static std::string getPCMFile (const DWARFDie &CUDie, DWARFLinker::ObjectPrefixMapTy *ObjectPrefixMap)
Function Documentation
getDwoId()
static uint64_t getDwoId (const DWARFDie & CUDie) static
Definition at line 264 of file DWARFLinkerImpl.cpp.
References llvm::DWARFDie::find(), and llvm::dwarf::toUnsigned().
getPCMFile()
static std::string getPCMFile (const DWARFDie & CUDie, DWARFLinker::ObjectPrefixMapTy * ObjectPrefixMap) static
Definition at line 285 of file DWARFLinkerImpl.cpp.
References llvm::DWARFDie::find(), llvm::remapPath(), and llvm::dwarf::toString().
remapPath()
static std::string remapPath (StringRef Path, const DWARFLinker::ObjectPrefixMapTy & ObjectPrefixMap) static
Definition at line 273 of file DWARFLinkerImpl.cpp.
References llvm::sys::path::replace_path_prefix().
resolveRelativeObjectPath()
static void resolveRelativeObjectPath (SmallVectorImpl< char > & Buf, DWARFDie CU) static
Resolve the relative path to a build artifact referenced by DWARF by applying DW_AT_comp_dir.
Definition at line 260 of file DWARFLinkerImpl.cpp.
References llvm::sys::path::append(), and llvm::dwarf::toString().