LLVM: lib/DWP/DWP.cpp File Reference
DWP.cpp File Reference
#include "llvm/DWP/DWP.h"
#include "llvm/ADT/Twine.h"
#include "llvm/DWP/DWPError.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCTargetOptionsCommandFlags.h"
#include "llvm/Object/Decompressor.h"
#include "llvm/Object/ELFObjectFile.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MemoryBuffer.h"
#include <limits>
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Enumerations
enum llvm::AccessField { llvm::Offset , llvm::Length }
Functions
static uint64_t debugStrOffsetsHeaderSize (DataExtractor StrOffsetsData, uint16_t DwarfVersion)
static uint64_t getCUAbbrev (StringRef Abbrev, uint64_t AbbrCode)
static Expected< const char * > getIndexedString (dwarf::Form Form, DataExtractor InfoData, uint64_t &InfoOffset, StringRef StrOffsets, StringRef Str, uint16_t Version)
static Expected< CompileUnitIdentifiers > getCUIdentifiers (InfoSectionUnitHeader &Header, StringRef Abbrev, StringRef Info, StringRef StrOffsets, StringRef Str)
static bool isSupportedSectionKind (DWARFSectionKind Kind)
unsigned llvm::getContributionIndex (DWARFSectionKind Kind, uint32_t IndexVersion)
static unsigned getOnDiskSectionId (unsigned Index)
static StringRef getSubsection (StringRef Section, const DWARFUnitIndex::Entry &Entry, DWARFSectionKind Kind)
static Error sectionOverflowErrorOrWarning (uint32_t PrevOffset, uint32_t OverflowedOffset, StringRef SectionName, OnCuIndexOverflow OverflowOptValue, bool &AnySectionOverflow)
static Error addAllTypesFromDWP (MCStreamer &Out, MapVector< uint64_t, UnitIndexEntry > &TypeIndexEntries, const DWARFUnitIndex &TUIndex, MCSection *OutputTypes, StringRef Types, const UnitIndexEntry &TUEntry, uint32_t &TypesOffset, unsigned TypesContributionIndex, OnCuIndexOverflow OverflowOptValue, bool &AnySectionOverflow)
static Error addAllTypesFromTypesSection (MCStreamer &Out, MapVector< uint64_t, UnitIndexEntry > &TypeIndexEntries, MCSection *OutputTypes, const std::vector< StringRef > &TypesSections, const UnitIndexEntry &CUEntry, uint32_t &TypesOffset, OnCuIndexOverflow OverflowOptValue, bool &AnySectionOverflow)
static std::string buildDWODescription (StringRef Name, StringRef DWPName, StringRef DWOName)
static Error createError (StringRef Name, Error E)
static Error handleCompressedSection (std::deque< SmallString< 32 > > &UncompressedSections, SectionRef Sec, StringRef Name, StringRef &Contents)
Expected< InfoSectionUnitHeader > llvm::parseInfoSectionUnitHeader (StringRef Info)
void llvm::writeStringsAndOffsets (MCStreamer &Out, DWPStringPool &Strings, MCSection *StrOffsetSection, StringRef CurStrSection, StringRef CurStrOffsetSection, uint16_t Version)
void llvm::writeIndexTable (MCStreamer &Out, ArrayRef< unsigned > ContributionOffsets, const MapVector< uint64_t, UnitIndexEntry > &IndexEntries, const AccessField &Field)
void llvm::writeIndex (MCStreamer &Out, MCSection *Section, ArrayRef< unsigned > ContributionOffsets, const MapVector< uint64_t, UnitIndexEntry > &IndexEntries, uint32_t IndexVersion)
Error llvm::buildDuplicateError (const std::pair< uint64_t, UnitIndexEntry > &PrevE, const CompileUnitIdentifiers &ID, StringRef DWPName)
Error llvm::handleSection (const StringMap< std::pair< MCSection *, DWARFSectionKind > > &KnownSections, const MCSection *StrSection, const MCSection *StrOffsetSection, const MCSection *TypesSection, const MCSection *CUIndexSection, const MCSection *TUIndexSection, const MCSection *InfoSection, const object::SectionRef &Section, MCStreamer &Out, std::deque< SmallString< 32 > > &UncompressedSections, uint32_t(&ContributionOffsets)[8], UnitIndexEntry &CurEntry, StringRef &CurStrSection, StringRef &CurStrOffsetSection, std::vector< StringRef > &CurTypesSection, std::vector< StringRef > &CurInfoSection, StringRef &AbbrevSection, StringRef &CurCUIndexSection, StringRef &CurTUIndexSection, std::vector< std::pair< DWARFSectionKind, uint32_t > > &SectionLength)
Error llvm::write (MCStreamer &Out, ArrayRef< std::string > Inputs, OnCuIndexOverflow OverflowOptValue)
Variables
static mc::RegisterMCTargetOptionsFlags MCTargetOptionsFlags
Function Documentation
addAllTypesFromDWP()
static Error addAllTypesFromDWP (MCStreamer & Out, MapVector< uint64_t, UnitIndexEntry > & TypeIndexEntries, const DWARFUnitIndex & TUIndex, MCSection * OutputTypes, StringRef Types, const UnitIndexEntry & TUEntry, uint32_t & TypesOffset, unsigned TypesContributionIndex, OnCuIndexOverflow OverflowOptValue, bool & AnySectionOverflow) static
Definition at line 205 of file DWP.cpp.
References llvm::CallingConv::C, llvm::UnitIndexEntry::Contributions, E, llvm::MCStreamer::emitBytes(), llvm::DWARFUnitIndex::getColumnKinds(), llvm::getContributionIndex(), llvm::DWARFUnitIndex::Entry::SectionContribution::getOffset(), llvm::DWARFUnitIndex::getRows(), llvm::DWARFUnitIndex::getVersion(), I, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::insert(), isSupportedSectionKind(), P, sectionOverflowErrorOrWarning(), llvm::Error::success(), and llvm::MCStreamer::switchSection().
Referenced by llvm::write().
addAllTypesFromTypesSection()
static Error addAllTypesFromTypesSection (MCStreamer & Out, MapVector< uint64_t, UnitIndexEntry > & TypeIndexEntries, MCSection * OutputTypes, const std::vector< StringRef > & TypesSections, const UnitIndexEntry & CUEntry, uint32_t & TypesOffset, OnCuIndexOverflow OverflowOptValue, bool & AnySectionOverflow) static
Definition at line 254 of file DWP.cpp.
References llvm::CallingConv::C, llvm::DW_SECT_EXT_TYPES, llvm::MCStreamer::emitBytes(), llvm::getContributionIndex(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::insert(), llvm::Offset, P, sectionOverflowErrorOrWarning(), llvm::Error::success(), and llvm::MCStreamer::switchSection().
Referenced by llvm::write().
buildDWODescription()
static std::string buildDWODescription (StringRef Name, StringRef DWPName, StringRef DWOName) static
Definition at line 301 of file DWP.cpp.
References llvm::StringRef::empty(), and Name.
Referenced by llvm::buildDuplicateError().
createError()
static Error createError (StringRef Name, Error E) static
Definition at line 327 of file DWP.cpp.
References E, Name, and llvm::dwarf::toString().
Referenced by handleCompressedSection().
debugStrOffsetsHeaderSize()
static uint64_t debugStrOffsetsHeaderSize (DataExtractor StrOffsetsData, uint16_t DwarfVersion) static
Definition at line 31 of file DWP.cpp.
References llvm::dwarf::DW_LENGTH_DWARF64, llvm::DataExtractor::getU32(), llvm::Length, and llvm::Offset.
Referenced by getIndexedString(), and llvm::writeStringsAndOffsets().
getCUAbbrev()
static uint64_t getCUAbbrev (StringRef Abbrev, uint64_t AbbrCode) static
Definition at line 42 of file DWP.cpp.
References llvm::DataExtractor::getU8(), llvm::DataExtractor::getULEB128(), and llvm::Offset.
Referenced by getCUIdentifiers().
getCUIdentifiers()
static Expected< CompileUnitIdentifiers > getCUIdentifiers (InfoSectionUnitHeader & Header, StringRef Abbrev, StringRef Info, StringRef StrOffsets, StringRef Str) static
Definition at line 96 of file DWP.cpp.
References getCUAbbrev(), getIndexedString(), llvm::DataExtractor::getU64(), llvm::DataExtractor::getU8(), llvm::DataExtractor::getULEB128(), Info, Name, llvm::Offset, llvm::DWARFFormValue::skipValue(), and llvm::Expected< T >::takeError().
Referenced by llvm::write().
getIndexedString()
static Expected< const char * > getIndexedString (dwarf::Form Form, DataExtractor InfoData, uint64_t & InfoOffset, StringRef StrOffsets, StringRef Str, uint16_t Version) static
Definition at line 58 of file DWP.cpp.
References debugStrOffsetsHeaderSize(), llvm::DataExtractor::getCStr(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU24(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU8(), and llvm::DataExtractor::getULEB128().
Referenced by getCUIdentifiers().
getOnDiskSectionId()
static unsigned getOnDiskSectionId (unsigned Index) static
Definition at line 170 of file DWP.cpp.
Referenced by llvm::writeIndex().
getSubsection()
static StringRef getSubsection (StringRef Section, const DWARFUnitIndex::Entry & Entry, DWARFSectionKind Kind) static
Definition at line 174 of file DWP.cpp.
Referenced by llvm::write().
handleCompressedSection()
static Error handleCompressedSection (std::deque< SmallString< 32 > > & UncompressedSections, SectionRef Sec, StringRef Name, StringRef & Contents) static
Definition at line 335 of file DWP.cpp.
References llvm::StringRef::back(), llvm::object::Decompressor::create(), createError(), E, getFlags(), llvm::object::SectionRef::getObject(), Name, llvm::ELF::SHF_COMPRESSED, llvm::Error::success(), and llvm::Expected< T >::takeError().
Referenced by llvm::handleSection().
isSupportedSectionKind()
static bool isSupportedSectionKind (DWARFSectionKind Kind) static
Definition at line 155 of file DWP.cpp.
References llvm::DW_SECT_EXT_unknown.
Referenced by addAllTypesFromDWP(), and llvm::write().
sectionOverflowErrorOrWarning()
static Error sectionOverflowErrorOrWarning (uint32_t PrevOffset, uint32_t OverflowedOffset, StringRef SectionName, OnCuIndexOverflow OverflowOptValue, bool & AnySectionOverflow) static
Definition at line 183 of file DWP.cpp.
References llvm::WithColor::defaultWarningHandler(), and llvm::Error::success().
Referenced by addAllTypesFromDWP(), addAllTypesFromTypesSection(), and llvm::write().
Variable Documentation
MCTargetOptionsFlags
mc::RegisterMCTargetOptionsFlags MCTargetOptionsFlags static
Definition at line 28 of file DWP.cpp.