LLVM: lib/MC/DXContainerPSVInfo.cpp File Reference
DXContainerPSVInfo.cpp File Reference
#include "llvm/MC/DXContainerPSVInfo.h"
#include "llvm/BinaryFormat/DXContainer.h"
#include "llvm/MC/StringTableBuilder.h"
#include "llvm/Support/EndianStream.h"
#include "llvm/Support/raw_ostream.h"
Functions
static size_t FindSequence (ArrayRef< uint32_t > Buffer, ArrayRef< uint32_t > Sequence)
static void ProcessElementList (StringTableBuilder &StrTabBuilder, SmallVectorImpl< uint32_t > &IndexBuffer, SmallVectorImpl< v0::SignatureElement > &FinalElements, SmallVectorImpl< StringRef > &SemanticNames, ArrayRef< PSVSignatureElement > Elements)
Variables
static constexpr size_t npos = StringRef::npos
Function Documentation
FindSequence()
static size_t FindSequence (ArrayRef< uint32_t > Buffer, ArrayRef< uint32_t > Sequence) static
Definition at line 21 of file DXContainerPSVInfo.cpp.
References Idx, memcmp, npos, and llvm::ArrayRef< T >::size().
Referenced by ProcessElementList().
ProcessElementList()
static void ProcessElementList (StringTableBuilder & StrTabBuilder, SmallVectorImpl< uint32_t > & IndexBuffer, SmallVectorImpl< v0::SignatureElement > & FinalElements, SmallVectorImpl< StringRef > & SemanticNames, ArrayRef< PSVSignatureElement > Elements) static
Definition at line 35 of file DXContainerPSVInfo.cpp.
References llvm::StringTableBuilder::add(), llvm::dxbc::PSV::v0::SignatureElement::Allocated, llvm::dxbc::PSV::v0::SignatureElement::Cols, llvm::dxbc::PSV::v0::SignatureElement::DynamicMask, llvm::SmallVectorTemplateCommon< T, typename >::end(), FindSequence(), Idx, llvm::dxbc::PSV::v0::SignatureElement::IndicesOffset, llvm::SmallVectorImpl< T >::insert(), llvm::dxbc::PSV::v0::SignatureElement::Kind, llvm::dxbc::PSV::v0::SignatureElement::Mode, npos, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::dxbc::PSV::v0::SignatureElement::Rows, llvm::SmallVectorBase< Size_T >::size(), llvm::dxbc::PSV::v0::SignatureElement::StartCol, llvm::dxbc::PSV::v0::SignatureElement::StartRow, llvm::dxbc::PSV::v0::SignatureElement::Stream, and llvm::dxbc::PSV::v0::SignatureElement::Type.
Referenced by llvm::mcdxbc::PSVRuntimeInfo::write().
Variable Documentation
npos
constexpr size_t npos = StringRef::npos static constexpr
Definition at line 19 of file DXContainerPSVInfo.cpp.
Referenced by llvm::StringRef::contains(), llvm::StringRef::contains_insensitive(), llvm::StringRef::detectEOL(), llvm::StringRef::find_if(), FindSequence(), ProcessElementList(), llvm::StringRef::rfind(), llvm::StringRef::rsplit(), and llvm::StringRef::split().