LLVM: lib/FileCheck/FileCheck.cpp File Reference
FileCheck.cpp File Reference
#include "llvm/FileCheck/FileCheck.h"
#include "FileCheckImpl.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/CheckedArithmetic.h"
#include "llvm/Support/FormatVariadic.h"
#include <cstdint>
#include <list>
#include <set>
#include <tuple>
#include <utility>
Classes
struct PrefixMatcher
Functions
static unsigned nextAPIntBitWidth (unsigned BitWidth)
static APInt toSigned (APInt AbsVal, bool Negative)
static char popFront (StringRef &S)
static SMRange ProcessMatchResult (FileCheckDiag::MatchType MatchTy, const SourceMgr &SM, SMLoc Loc, Check::FileCheckType CheckTy, StringRef Buffer, size_t Pos, size_t Len, std::vector< FileCheckDiag > *Diags, bool AdjustPrevDiags=false)
static bool IsPartOfWord (char c)
static std::pair< Check::FileCheckType, StringRef > FindCheckType (const FileCheckRequest &Req, StringRef Buffer, StringRef Prefix, bool &Misspelled)
static std::pair< Check::FileCheckType, StringRef > FindCheckType (const FileCheckRequest &Req, StringRef Buffer, StringRef Prefix)
static size_t SkipWord (StringRef Str, size_t Loc)
static void addDefaultPrefixes (FileCheckRequest &Req)
static std::pair< StringRef, StringRef > FindFirstMatchingPrefix (const FileCheckRequest &Req, PrefixMatcher &Matcher, StringRef &Buffer, unsigned &LineNumber, Check::FileCheckType &CheckTy)
Searches the buffer for the first prefix in the prefix regular expression.
static Error printMatch (bool ExpectedMatch, const SourceMgr &SM, StringRef Prefix, SMLoc Loc, const Pattern &Pat, int MatchedCount, StringRef Buffer, Pattern::MatchResult MatchResult, const FileCheckRequest &Req, std::vector< FileCheckDiag > *Diags)
Returns either (1) ErrorSuccess if there was no error or (2) ErrorReported if an error was reported, such as an unexpected match.
static Error printNoMatch (bool ExpectedMatch, const SourceMgr &SM, StringRef Prefix, SMLoc Loc, const Pattern &Pat, int MatchedCount, StringRef Buffer, Error MatchError, bool VerboseVerbose, std::vector< FileCheckDiag > *Diags)
Returns either (1) ErrorSuccess if there was no error, or (2) ErrorReported if an error was reported, such as an expected match not found.
static Error reportMatchResult (bool ExpectedMatch, const SourceMgr &SM, StringRef Prefix, SMLoc Loc, const Pattern &Pat, int MatchedCount, StringRef Buffer, Pattern::MatchResult MatchResult, const FileCheckRequest &Req, std::vector< FileCheckDiag > *Diags)
Returns either (1) ErrorSuccess if there was no error, or (2) ErrorReported if an error was reported.
static unsigned CountNumNewlinesBetween (StringRef Range, const char *&FirstNewLine)
Counts the number of newlines in the specified range.
static bool ValidatePrefixes (StringRef Kind, StringSet<> &UniquePrefixes, ArrayRef< StringRef > SuppliedPrefixes)
Variables
constexpr StringLiteral SpaceChars = " \t"
static const char * DefaultCheckPrefixes [] = {"CHECK"}
static const char * DefaultCommentPrefixes [] = {"COM", "RUN"}
Function Documentation
addDefaultPrefixes()
static void addDefaultPrefixes (FileCheckRequest & Req) static
Definition at line 1640 of file FileCheck.cpp.
References llvm::FileCheckRequest::CheckPrefixes, llvm::FileCheckRequest::CommentPrefixes, DefaultCheckPrefixes, DefaultCommentPrefixes, and llvm::FileCheckRequest::IsDefaultCheckPrefix.
Referenced by llvm::FileCheck::readCheckFile().
CountNumNewlinesBetween()
static unsigned CountNumNewlinesBetween (StringRef Range, const char *& FirstNewLine) static
Counts the number of newlines in the specified range.
Definition at line 2142 of file FileCheck.cpp.
Referenced by llvm::FileCheckString::CheckNext(), and llvm::FileCheckString::CheckSame().
FindCheckType() [1/2]
static std::pair< Check::FileCheckType, StringRef > FindCheckType (const FileCheckRequest & Req, StringRef Buffer, StringRef Prefix) static
Definition at line 1622 of file FileCheck.cpp.
References llvm::Check::CheckMisspelled, llvm::Check::CheckNone, and FindCheckType().
FindCheckType() [2/2]
static std::pair< Check::FileCheckType, StringRef > FindCheckType (const FileCheckRequest & Req, StringRef Buffer, StringRef Prefix, bool & Misspelled) static
Definition at line 1532 of file FileCheck.cpp.
References llvm::Check::CheckBadCount, llvm::Check::CheckBadNot, llvm::Check::CheckComment, llvm::Check::CheckDAG, llvm::Check::CheckEmpty, llvm::Check::CheckLabel, llvm::Check::CheckNext, llvm::Check::CheckNone, llvm::Check::CheckNot, llvm::Check::CheckPlain, llvm::Check::CheckSame, llvm::FileCheckRequest::CommentPrefixes, llvm::StringRef::consume_front(), llvm::StringRef::consumeInteger(), llvm::StringRef::drop_front(), llvm::StringRef::front(), llvm::is_contained(), llvm::StringRef::ltrim(), llvm::StringRef::size(), and llvm::StringRef::starts_with().
Referenced by FindCheckType(), and FindFirstMatchingPrefix().
FindFirstMatchingPrefix()
static std::pair< StringRef, StringRef > FindFirstMatchingPrefix (const FileCheckRequest & Req, PrefixMatcher & Matcher, StringRef & Buffer, unsigned & LineNumber, Check::FileCheckType & CheckTy) static
Searches the buffer for the first prefix in the prefix regular expression.
This searches the buffer using the provided regular expression, however it enforces constraints beyond that: 1) The found prefix must not be a suffix of something that looks like a valid prefix. 2) The found prefix must be followed by a valid check type suffix using FindCheckType above.
Returns
a pair of StringRefs into the Buffer, which combines:
the first match of the regular expression to satisfy these two is returned, otherwise an empty StringRef is returned to indicate failure.
buffer rewound to the location right after parsed suffix, for parsing to continue from
If this routine returns a valid prefix, it will also shrink Buffer to start at the beginning of the returned prefix, increment LineNumber for each new line consumed from Buffer, and set CheckTy to the type of check found by examining the suffix.
If no valid prefix is found, the state of Buffer, LineNumber, and CheckTy is unspecified.
Definition at line 1715 of file FileCheck.cpp.
References assert(), llvm::StringRef::back(), llvm::Check::CheckNone, llvm::StringRef::count(), llvm::StringRef::data(), llvm::StringRef::drop_front(), llvm::StringRef::empty(), FindCheckType(), IsPartOfWord(), PrefixMatcher::match(), llvm::StringRef::size(), SkipWord(), and llvm::StringRef::substr().
Referenced by llvm::FileCheck::readCheckFile().
IsPartOfWord()
static bool IsPartOfWord (char c) static
Definition at line 1468 of file FileCheck.cpp.
Referenced by FindFirstMatchingPrefix(), and SkipWord().
nextAPIntBitWidth()
static unsigned nextAPIntBitWidth (unsigned BitWidth) static
Definition at line 123 of file FileCheck.cpp.
References llvm::APInt::APINT_BITS_PER_WORD, and llvm::BitWidth.
Referenced by llvm::BinaryOperation::eval(), and toSigned().
popFront()
static char popFront (StringRef & S) static
Definition at line 318 of file FileCheck.cpp.
References llvm::CallingConv::C, llvm::StringRef::drop_front(), and llvm::StringRef::front().
Referenced by llvm::Pattern::parseNumericSubstitutionBlock().
printMatch()
static Error printMatch (bool ExpectedMatch, const SourceMgr & SM, StringRef Prefix, SMLoc Loc, const Pattern & Pat, int MatchedCount, StringRef Buffer, Pattern::MatchResult MatchResult, const FileCheckRequest & Req, std::vector< FileCheckDiag > * Diags) static
Returns either (1) ErrorSuccess if there was no error or (2) ErrorReported if an error was reported, such as an unexpected match.
Definition at line 1974 of file FileCheck.cpp.
References assert(), llvm::Check::CheckEOF, llvm::SourceMgr::DK_Error, llvm::SourceMgr::DK_Note, llvm::SourceMgr::DK_Remark, E, llvm::formatv(), llvm::Pattern::getCheckTy(), llvm::Pattern::getCount(), llvm::Check::FileCheckType::getDescription(), llvm::handleAllErrors(), llvm::FileCheckDiag::MatchFoundAndExpected, llvm::FileCheckDiag::MatchFoundButExcluded, llvm::SourceMgr::PrintMessage(), llvm::Pattern::printSubstitutions(), llvm::Pattern::printVariableDefs(), ProcessMatchResult(), llvm::ErrorReported::reportedOrSuccess(), llvm::SMRange::Start, llvm::Pattern::MatchResult::TheError, llvm::Pattern::MatchResult::TheMatch, llvm::FileCheckRequest::Verbose, and llvm::FileCheckRequest::VerboseVerbose.
Referenced by llvm::FileCheckString::CheckDag(), and reportMatchResult().
printNoMatch()
static Error printNoMatch (bool ExpectedMatch, const SourceMgr & SM, StringRef Prefix, SMLoc Loc, const Pattern & Pat, int MatchedCount, StringRef Buffer, Error MatchError, bool VerboseVerbose, std::vector< FileCheckDiag > * Diags) static
Returns either (1) ErrorSuccess if there was no error, or (2) ErrorReported if an error was reported, such as an expected match not found.
Definition at line 2044 of file FileCheck.cpp.
References assert(), llvm::SourceMgr::DK_Error, llvm::SourceMgr::DK_Note, llvm::SourceMgr::DK_Remark, E, llvm::errs(), llvm::formatv(), llvm::Pattern::getCheckTy(), llvm::Pattern::getCount(), llvm::Check::FileCheckType::getDescription(), llvm::handleAllErrors(), llvm::FileCheckDiag::MatchNoneAndExcluded, llvm::FileCheckDiag::MatchNoneButExpected, llvm::FileCheckDiag::MatchNoneForInvalidPattern, llvm::Pattern::printFuzzyMatch(), llvm::SourceMgr::PrintMessage(), llvm::Pattern::printSubstitutions(), ProcessMatchResult(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::ErrorReported::reportedOrSuccess(), llvm::StringRef::size(), and llvm::SMRange::Start.
Referenced by reportMatchResult().
ProcessMatchResult()
static SMRange ProcessMatchResult (FileCheckDiag::MatchType MatchTy, const SourceMgr & SM, SMLoc Loc, Check::FileCheckType CheckTy, StringRef Buffer, size_t Pos, size_t Len, std::vector< FileCheckDiag > * Diags, bool AdjustPrevDiags = false) static
Definition at line 1290 of file FileCheck.cpp.
References llvm::StringRef::data(), E, End, llvm::SMLoc::getFromPointer(), and I.
Referenced by llvm::FileCheckString::Check(), llvm::Pattern::printFuzzyMatch(), printMatch(), and printNoMatch().
reportMatchResult()
static Error reportMatchResult (bool ExpectedMatch, const SourceMgr & SM, StringRef Prefix, SMLoc Loc, const Pattern & Pat, int MatchedCount, StringRef Buffer, Pattern::MatchResult MatchResult, const FileCheckRequest & Req, std::vector< FileCheckDiag > * Diags) static
Returns either (1) ErrorSuccess if there was no error, or (2) ErrorReported if an error was reported.
Definition at line 2127 of file FileCheck.cpp.
References printMatch(), printNoMatch(), llvm::Pattern::MatchResult::TheError, llvm::Pattern::MatchResult::TheMatch, and llvm::FileCheckRequest::VerboseVerbose.
Referenced by llvm::FileCheckString::Check(), llvm::FileCheckString::CheckDag(), and llvm::FileCheckString::CheckNot().
SkipWord()
static size_t SkipWord (StringRef Str, size_t Loc) static
Definition at line 1631 of file FileCheck.cpp.
References IsPartOfWord().
Referenced by FindFirstMatchingPrefix().
toSigned()
static APInt toSigned (APInt AbsVal, bool Negative) static
Definition at line 128 of file FileCheck.cpp.
References llvm::APInt::getBitWidth(), llvm::APInt::isSignBitSet(), nextAPIntBitWidth(), and llvm::APInt::zext().
ValidatePrefixes()
static bool ValidatePrefixes (StringRef Kind, StringSet<> & UniquePrefixes, ArrayRef< StringRef > SuppliedPrefixes) static
Definition at line 2467 of file FileCheck.cpp.
References llvm::errs(), llvm::StringSet< AllocatorTy >::insert(), and llvm::Regex::match().
Referenced by llvm::FileCheck::ValidateCheckPrefixes().
Variable Documentation
DefaultCheckPrefixes
const char* DefaultCheckPrefixes[] = {"CHECK"} static
Definition at line 1637 of file FileCheck.cpp.
Referenced by addDefaultPrefixes(), and llvm::FileCheck::ValidateCheckPrefixes().
DefaultCommentPrefixes
const char* DefaultCommentPrefixes[] = {"COM", "RUN"} static
Definition at line 1638 of file FileCheck.cpp.
Referenced by addDefaultPrefixes(), and llvm::FileCheck::ValidateCheckPrefixes().
SpaceChars
constexpr StringLiteral SpaceChars = " \t" constexpr
Definition at line 315 of file FileCheck.cpp.
Referenced by llvm::Pattern::parseNumericSubstitutionBlock().