LLVM: Floating Point Types
Floating Point Types
LLVM-C: C interface to LLVM » Core » Types
Functions
LLVMTypeRef LLVMHalfTypeInContext (LLVMContextRef C)
Obtain a 16-bit floating point type from a context.
LLVMTypeRef LLVMBFloatTypeInContext (LLVMContextRef C)
Obtain a 16-bit brain floating point type from a context.
LLVMTypeRef LLVMFloatTypeInContext (LLVMContextRef C)
Obtain a 32-bit floating point type from a context.
LLVMTypeRef LLVMDoubleTypeInContext (LLVMContextRef C)
Obtain a 64-bit floating point type from a context.
LLVMTypeRef LLVMX86FP80TypeInContext (LLVMContextRef C)
Obtain a 80-bit floating point type (X87) from a context.
LLVMTypeRef LLVMFP128TypeInContext (LLVMContextRef C)
Obtain a 128-bit floating point type (112-bit mantissa) from a context.
LLVMTypeRef LLVMPPCFP128TypeInContext (LLVMContextRef C)
Obtain a 128-bit floating point type (two 64-bits) from a context.
LLVMTypeRef LLVMHalfType (void)
Obtain a floating point type from the global context.
LLVMTypeRef LLVMBFloatType (void)
LLVMTypeRef LLVMFloatType (void)
LLVMTypeRef LLVMDoubleType (void)
LLVMTypeRef LLVMX86FP80Type (void)
LLVMTypeRef LLVMFP128Type (void)
LLVMTypeRef LLVMPPCFP128Type (void)
Detailed Description
Function Documentation
LLVMBFloatType()
LLVMTypeRef LLVMBFloatType (void)
Definition at line 710 of file Core.cpp.
References LLVMBFloatTypeInContext(), and LLVMGetGlobalContext().
LLVMBFloatTypeInContext()
LLVMTypeRef LLVMBFloatTypeInContext (LLVMContextRef C)
Obtain a 16-bit brain floating point type from a context.
Definition at line 682 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getBFloatTy(), and llvm::unwrap().
Referenced by LLVMBFloatType().
LLVMDoubleType()
LLVMTypeRef LLVMDoubleType (void)
Definition at line 716 of file Core.cpp.
References LLVMDoubleTypeInContext(), and LLVMGetGlobalContext().
LLVMDoubleTypeInContext()
LLVMTypeRef LLVMDoubleTypeInContext (LLVMContextRef C)
Obtain a 64-bit floating point type from a context.
Definition at line 688 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getDoubleTy(), and llvm::unwrap().
Referenced by LLVMDoubleType().
LLVMFloatType()
LLVMTypeRef LLVMFloatType (void)
Definition at line 713 of file Core.cpp.
References LLVMFloatTypeInContext(), and LLVMGetGlobalContext().
LLVMFloatTypeInContext()
LLVMTypeRef LLVMFloatTypeInContext (LLVMContextRef C)
Obtain a 32-bit floating point type from a context.
Definition at line 685 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getFloatTy(), and llvm::unwrap().
Referenced by LLVMFloatType().
LLVMFP128Type()
LLVMTypeRef LLVMFP128Type (void)
Definition at line 722 of file Core.cpp.
References LLVMFP128TypeInContext(), and LLVMGetGlobalContext().
LLVMFP128TypeInContext()
LLVMTypeRef LLVMFP128TypeInContext (LLVMContextRef C)
Obtain a 128-bit floating point type (112-bit mantissa) from a context.
Definition at line 694 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getFP128Ty(), and llvm::unwrap().
Referenced by LLVMFP128Type().
LLVMHalfType()
LLVMTypeRef LLVMHalfType (void)
Obtain a floating point type from the global context.
These map to the functions in this group of the same name.
Definition at line 707 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMHalfTypeInContext().
LLVMHalfTypeInContext()
LLVMTypeRef LLVMHalfTypeInContext (LLVMContextRef C)
Obtain a 16-bit floating point type from a context.
Definition at line 679 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getHalfTy(), and llvm::unwrap().
Referenced by LLVMHalfType().
LLVMPPCFP128Type()
LLVMTypeRef LLVMPPCFP128Type (void)
Definition at line 725 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMPPCFP128TypeInContext().
LLVMPPCFP128TypeInContext()
LLVMTypeRef LLVMPPCFP128TypeInContext (LLVMContextRef C)
Obtain a 128-bit floating point type (two 64-bits) from a context.
Definition at line 697 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getPPC_FP128Ty(), and llvm::unwrap().
Referenced by LLVMPPCFP128Type().
LLVMX86FP80Type()
LLVMTypeRef LLVMX86FP80Type (void)
Definition at line 719 of file Core.cpp.
References LLVMGetGlobalContext(), and LLVMX86FP80TypeInContext().
LLVMX86FP80TypeInContext()
LLVMTypeRef LLVMX86FP80TypeInContext (LLVMContextRef C)
Obtain a 80-bit floating point type (X87) from a context.
Definition at line 691 of file Core.cpp.
References llvm::CallingConv::C, llvm::Type::getX86_FP80Ty(), and llvm::unwrap().
Referenced by LLVMX86FP80Type().