LLVM: Instruction Builders
Instruction Builders
LLVM-C: C interface to LLVM
An instruction builder represents a point within a basic block and is the exclusive means of building instructions using the C interface.
Functions
LLVMBuilderRef LLVMCreateBuilderInContext (LLVMContextRef C)
LLVMBuilderRef LLVMCreateBuilder (void)
void LLVMPositionBuilder (LLVMBuilderRef Builder, LLVMBasicBlockRef Block, LLVMValueRef Instr)
void LLVMPositionBuilderBefore (LLVMBuilderRef Builder, LLVMValueRef Instr)
void LLVMPositionBuilderAtEnd (LLVMBuilderRef Builder, LLVMBasicBlockRef Block)
LLVMBasicBlockRef LLVMGetInsertBlock (LLVMBuilderRef Builder)
void LLVMClearInsertionPosition (LLVMBuilderRef Builder)
void LLVMInsertIntoBuilder (LLVMBuilderRef Builder, LLVMValueRef Instr)
void LLVMInsertIntoBuilderWithName (LLVMBuilderRef Builder, LLVMValueRef Instr, const char *Name)
void LLVMDisposeBuilder (LLVMBuilderRef Builder)
LLVMMetadataRef LLVMGetCurrentDebugLocation2 (LLVMBuilderRef Builder)
Get location information used by debugging information.
void LLVMSetCurrentDebugLocation2 (LLVMBuilderRef Builder, LLVMMetadataRef Loc)
Set location information used by debugging information.
void LLVMSetInstDebugLocation (LLVMBuilderRef Builder, LLVMValueRef Inst)
Attempts to set the debug location for the given instruction using the current debug location for the given builder.
void LLVMAddMetadataToInst (LLVMBuilderRef Builder, LLVMValueRef Inst)
Adds the metadata registered with the given builder to the given instruction.
LLVMMetadataRef LLVMBuilderGetDefaultFPMathTag (LLVMBuilderRef Builder)
Get the dafult floating-point math metadata for a given builder.
void LLVMBuilderSetDefaultFPMathTag (LLVMBuilderRef Builder, LLVMMetadataRef FPMathTag)
Set the default floating-point math metadata for the given builder.
void LLVMSetCurrentDebugLocation (LLVMBuilderRef Builder, LLVMValueRef L)
Deprecated: Passing the NULL location will crash.
LLVMValueRef LLVMGetCurrentDebugLocation (LLVMBuilderRef Builder)
Deprecated: Returning the NULL location will crash.
LLVMValueRef LLVMBuildRetVoid (LLVMBuilderRef)
LLVMValueRef LLVMBuildRet (LLVMBuilderRef, LLVMValueRef V)
LLVMValueRef LLVMBuildAggregateRet (LLVMBuilderRef, LLVMValueRef *RetVals, unsigned N)
LLVMValueRef LLVMBuildBr (LLVMBuilderRef, LLVMBasicBlockRef Dest)
LLVMValueRef LLVMBuildCondBr (LLVMBuilderRef, LLVMValueRef If, LLVMBasicBlockRef Then, LLVMBasicBlockRef Else)
LLVMValueRef LLVMBuildSwitch (LLVMBuilderRef, LLVMValueRef V, LLVMBasicBlockRef Else, unsigned NumCases)
LLVMValueRef LLVMBuildIndirectBr (LLVMBuilderRef B, LLVMValueRef Addr, unsigned NumDests)
LLVMValueRef LLVMBuildInvoke2 (LLVMBuilderRef, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, const char *Name)
LLVMValueRef LLVMBuildInvokeWithOperandBundles (LLVMBuilderRef, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, LLVMOperandBundleRef *Bundles, unsigned NumBundles, const char *Name)
LLVMValueRef LLVMBuildUnreachable (LLVMBuilderRef)
LLVMValueRef LLVMBuildResume (LLVMBuilderRef B, LLVMValueRef Exn)
LLVMValueRef LLVMBuildLandingPad (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef PersFn, unsigned NumClauses, const char *Name)
LLVMValueRef LLVMBuildCleanupRet (LLVMBuilderRef B, LLVMValueRef CatchPad, LLVMBasicBlockRef BB)
LLVMValueRef LLVMBuildCatchRet (LLVMBuilderRef B, LLVMValueRef CatchPad, LLVMBasicBlockRef BB)
LLVMValueRef LLVMBuildCatchPad (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMValueRef *Args, unsigned NumArgs, const char *Name)
LLVMValueRef LLVMBuildCleanupPad (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMValueRef *Args, unsigned NumArgs, const char *Name)
LLVMValueRef LLVMBuildCatchSwitch (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMBasicBlockRef UnwindBB, unsigned NumHandlers, const char *Name)
void LLVMAddCase (LLVMValueRef Switch, LLVMValueRef OnVal, LLVMBasicBlockRef Dest)
void LLVMAddDestination (LLVMValueRef IndirectBr, LLVMBasicBlockRef Dest)
unsigned LLVMGetNumClauses (LLVMValueRef LandingPad)
LLVMValueRef LLVMGetClause (LLVMValueRef LandingPad, unsigned Idx)
void LLVMAddClause (LLVMValueRef LandingPad, LLVMValueRef ClauseVal)
LLVMBool LLVMIsCleanup (LLVMValueRef LandingPad)
void LLVMSetCleanup (LLVMValueRef LandingPad, LLVMBool Val)
void LLVMAddHandler (LLVMValueRef CatchSwitch, LLVMBasicBlockRef Dest)
unsigned LLVMGetNumHandlers (LLVMValueRef CatchSwitch)
void LLVMGetHandlers (LLVMValueRef CatchSwitch, LLVMBasicBlockRef *Handlers)
Obtain the basic blocks acting as handlers for a catchswitch instruction.
LLVMValueRef LLVMGetArgOperand (LLVMValueRef Funclet, unsigned i)
void LLVMSetArgOperand (LLVMValueRef Funclet, unsigned i, LLVMValueRef value)
LLVMValueRef LLVMGetParentCatchSwitch (LLVMValueRef CatchPad)
Get the parent catchswitch instruction of a catchpad instruction.
void LLVMSetParentCatchSwitch (LLVMValueRef CatchPad, LLVMValueRef CatchSwitch)
Set the parent catchswitch instruction of a catchpad instruction.
LLVMValueRef LLVMBuildAdd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNSWAdd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNUWAdd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFAdd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildSub (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNSWSub (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNUWSub (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFSub (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildMul (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNSWMul (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNUWMul (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFMul (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildUDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildExactUDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildSDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildExactSDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFDiv (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildURem (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildSRem (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFRem (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildShl (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildLShr (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildAShr (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildAnd (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildOr (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildXor (LLVMBuilderRef, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildBinOp (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildNeg (LLVMBuilderRef, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildNSWNeg (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildNUWNeg (LLVMBuilderRef B, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildFNeg (LLVMBuilderRef, LLVMValueRef V, const char *Name)
LLVMValueRef LLVMBuildNot (LLVMBuilderRef, LLVMValueRef V, const char *Name)
LLVMBool LLVMGetNUW (LLVMValueRef ArithInst)
void LLVMSetNUW (LLVMValueRef ArithInst, LLVMBool HasNUW)
LLVMBool LLVMGetNSW (LLVMValueRef ArithInst)
void LLVMSetNSW (LLVMValueRef ArithInst, LLVMBool HasNSW)
LLVMBool LLVMGetExact (LLVMValueRef DivOrShrInst)
void LLVMSetExact (LLVMValueRef DivOrShrInst, LLVMBool IsExact)
LLVMBool LLVMGetNNeg (LLVMValueRef NonNegInst)
Gets if the instruction has the non-negative flag set.
void LLVMSetNNeg (LLVMValueRef NonNegInst, LLVMBool IsNonNeg)
Sets the non-negative flag for the instruction.
LLVMFastMathFlags LLVMGetFastMathFlags (LLVMValueRef FPMathInst)
Get the flags for which fast-math-style optimizations are allowed for this value.
void LLVMSetFastMathFlags (LLVMValueRef FPMathInst, LLVMFastMathFlags FMF)
Sets the flags for which fast-math-style optimizations are allowed for this value.
LLVMBool LLVMCanValueUseFastMathFlags (LLVMValueRef Inst)
Check if a given value can potentially have fast math flags.
LLVMBool LLVMGetIsDisjoint (LLVMValueRef Inst)
Gets whether the instruction has the disjoint flag set.
void LLVMSetIsDisjoint (LLVMValueRef Inst, LLVMBool IsDisjoint)
Sets the disjoint flag for the instruction.
LLVMValueRef LLVMBuildMalloc (LLVMBuilderRef, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildArrayMalloc (LLVMBuilderRef, LLVMTypeRef Ty, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildMemSet (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Val, LLVMValueRef Len, unsigned Align)
Creates and inserts a memset to the specified pointer and the specified value.
LLVMValueRef LLVMBuildMemCpy (LLVMBuilderRef B, LLVMValueRef Dst, unsigned DstAlign, LLVMValueRef Src, unsigned SrcAlign, LLVMValueRef Size)
Creates and inserts a memcpy between the specified pointers.
LLVMValueRef LLVMBuildMemMove (LLVMBuilderRef B, LLVMValueRef Dst, unsigned DstAlign, LLVMValueRef Src, unsigned SrcAlign, LLVMValueRef Size)
Creates and inserts a memmove between the specified pointers.
LLVMValueRef LLVMBuildAlloca (LLVMBuilderRef, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildArrayAlloca (LLVMBuilderRef, LLVMTypeRef Ty, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildFree (LLVMBuilderRef, LLVMValueRef PointerVal)
LLVMValueRef LLVMBuildLoad2 (LLVMBuilderRef, LLVMTypeRef Ty, LLVMValueRef PointerVal, const char *Name)
LLVMValueRef LLVMBuildStore (LLVMBuilderRef, LLVMValueRef Val, LLVMValueRef Ptr)
LLVMValueRef LLVMBuildGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef *Indices, unsigned NumIndices, const char *Name)
LLVMValueRef LLVMBuildInBoundsGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef *Indices, unsigned NumIndices, const char *Name)
LLVMValueRef LLVMBuildStructGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, unsigned Idx, const char *Name)
LLVMValueRef LLVMBuildGlobalString (LLVMBuilderRef B, const char *Str, const char *Name)
LLVMValueRef LLVMBuildGlobalStringPtr (LLVMBuilderRef B, const char *Str, const char *Name)
LLVMBool LLVMGetVolatile (LLVMValueRef MemoryAccessInst)
void LLVMSetVolatile (LLVMValueRef MemoryAccessInst, LLVMBool IsVolatile)
LLVMBool LLVMGetWeak (LLVMValueRef CmpXchgInst)
void LLVMSetWeak (LLVMValueRef CmpXchgInst, LLVMBool IsWeak)
LLVMAtomicOrdering LLVMGetOrdering (LLVMValueRef MemoryAccessInst)
void LLVMSetOrdering (LLVMValueRef MemoryAccessInst, LLVMAtomicOrdering Ordering)
LLVMAtomicRMWBinOp LLVMGetAtomicRMWBinOp (LLVMValueRef AtomicRMWInst)
void LLVMSetAtomicRMWBinOp (LLVMValueRef AtomicRMWInst, LLVMAtomicRMWBinOp BinOp)
LLVMValueRef LLVMBuildTrunc (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildZExt (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildSExt (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPToUI (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPToSI (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildUIToFP (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildSIToFP (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPTrunc (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildFPExt (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildPtrToInt (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildIntToPtr (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildBitCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildAddrSpaceCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildZExtOrBitCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildSExtOrBitCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildTruncOrBitCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildCast (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildPointerCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildIntCast2 (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, LLVMBool IsSigned, const char *Name)
LLVMValueRef LLVMBuildFPCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
LLVMValueRef LLVMBuildIntCast (LLVMBuilderRef, LLVMValueRef Val, LLVMTypeRef DestTy, const char *Name)
Deprecated: This cast is always signed.
LLVMOpcode LLVMGetCastOpcode (LLVMValueRef Src, LLVMBool SrcIsSigned, LLVMTypeRef DestTy, LLVMBool DestIsSigned)
LLVMValueRef LLVMBuildICmp (LLVMBuilderRef, LLVMIntPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFCmp (LLVMBuilderRef, LLVMRealPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildPhi (LLVMBuilderRef, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildCall2 (LLVMBuilderRef, LLVMTypeRef, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, const char *Name)
LLVMValueRef LLVMBuildCallWithOperandBundles (LLVMBuilderRef, LLVMTypeRef, LLVMValueRef Fn, LLVMValueRef *Args, unsigned NumArgs, LLVMOperandBundleRef *Bundles, unsigned NumBundles, const char *Name)
LLVMValueRef LLVMBuildSelect (LLVMBuilderRef, LLVMValueRef If, LLVMValueRef Then, LLVMValueRef Else, const char *Name)
LLVMValueRef LLVMBuildVAArg (LLVMBuilderRef, LLVMValueRef List, LLVMTypeRef Ty, const char *Name)
LLVMValueRef LLVMBuildExtractElement (LLVMBuilderRef, LLVMValueRef VecVal, LLVMValueRef Index, const char *Name)
LLVMValueRef LLVMBuildInsertElement (LLVMBuilderRef, LLVMValueRef VecVal, LLVMValueRef EltVal, LLVMValueRef Index, const char *Name)
LLVMValueRef LLVMBuildShuffleVector (LLVMBuilderRef, LLVMValueRef V1, LLVMValueRef V2, LLVMValueRef Mask, const char *Name)
LLVMValueRef LLVMBuildExtractValue (LLVMBuilderRef, LLVMValueRef AggVal, unsigned Index, const char *Name)
LLVMValueRef LLVMBuildInsertValue (LLVMBuilderRef, LLVMValueRef AggVal, LLVMValueRef EltVal, unsigned Index, const char *Name)
LLVMValueRef LLVMBuildFreeze (LLVMBuilderRef, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildIsNull (LLVMBuilderRef, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildIsNotNull (LLVMBuilderRef, LLVMValueRef Val, const char *Name)
LLVMValueRef LLVMBuildPtrDiff2 (LLVMBuilderRef, LLVMTypeRef ElemTy, LLVMValueRef LHS, LLVMValueRef RHS, const char *Name)
LLVMValueRef LLVMBuildFence (LLVMBuilderRef B, LLVMAtomicOrdering ordering, LLVMBool singleThread, const char *Name)
LLVMValueRef LLVMBuildAtomicRMW (LLVMBuilderRef B, LLVMAtomicRMWBinOp op, LLVMValueRef PTR, LLVMValueRef Val, LLVMAtomicOrdering ordering, LLVMBool singleThread)
LLVMValueRef LLVMBuildAtomicCmpXchg (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Cmp, LLVMValueRef New, LLVMAtomicOrdering SuccessOrdering, LLVMAtomicOrdering FailureOrdering, LLVMBool SingleThread)
unsigned LLVMGetNumMaskElements (LLVMValueRef ShuffleVectorInst)
Get the number of elements in the mask of a ShuffleVector instruction.
int LLVMGetUndefMaskElem (void)
int LLVMGetMaskValue (LLVMValueRef ShuffleVectorInst, unsigned Elt)
Get the mask value at position Elt in the mask of a ShuffleVector instruction.
LLVMBool LLVMIsAtomicSingleThread (LLVMValueRef AtomicInst)
void LLVMSetAtomicSingleThread (LLVMValueRef AtomicInst, LLVMBool SingleThread)
LLVMAtomicOrdering LLVMGetCmpXchgSuccessOrdering (LLVMValueRef CmpXchgInst)
void LLVMSetCmpXchgSuccessOrdering (LLVMValueRef CmpXchgInst, LLVMAtomicOrdering Ordering)
LLVMAtomicOrdering LLVMGetCmpXchgFailureOrdering (LLVMValueRef CmpXchgInst)
void LLVMSetCmpXchgFailureOrdering (LLVMValueRef CmpXchgInst, LLVMAtomicOrdering Ordering)
Detailed Description
An instruction builder represents a point within a basic block and is the exclusive means of building instructions using the C interface.
Function Documentation
LLVMAddCase()
void LLVMAddCase (LLVMValueRef Switch, LLVMValueRef OnVal, LLVMBasicBlockRef Dest)
Definition at line 3258 of file Core.cpp.
References llvm::unwrap().
LLVMAddClause()
void LLVMAddClause (LLVMValueRef LandingPad, LLVMValueRef ClauseVal)
Definition at line 3275 of file Core.cpp.
LLVMAddDestination()
void LLVMAddDestination (LLVMValueRef IndirectBr, LLVMBasicBlockRef Dest)
Definition at line 3263 of file Core.cpp.
References llvm::unwrap().
LLVMAddHandler()
void LLVMAddHandler (LLVMValueRef CatchSwitch, LLVMBasicBlockRef Dest)
Definition at line 3287 of file Core.cpp.
References llvm::unwrap().
LLVMAddMetadataToInst()
void LLVMAddMetadataToInst (LLVMBuilderRef Builder, LLVMValueRef Inst)
Adds the metadata registered with the given builder to the given instruction.
See also
llvm::IRBuilder::AddMetadataToInst()
Definition at line 3124 of file Core.cpp.
References llvm::unwrap().
LLVMBuildAdd()
LLVMValueRef LLVMBuildAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3355 of file Core.cpp.
References B, CreateAdd(), LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildAddrSpaceCast()
LLVMValueRef LLVMBuildAddrSpaceCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3896 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildAggregateRet()
LLVMValueRef LLVMBuildAggregateRet (LLVMBuilderRef B, LLVMValueRef * RetVals, unsigned N)
Definition at line 3150 of file Core.cpp.
References B, N, llvm::unwrap(), and llvm::wrap().
LLVMBuildAlloca()
LLVMValueRef LLVMBuildAlloca (LLVMBuilderRef B, LLVMTypeRef Ty, const char * Name)
Definition at line 3625 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildAnd()
LLVMValueRef LLVMBuildAnd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3470 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildArrayAlloca()
LLVMValueRef LLVMBuildArrayAlloca (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Val, const char * Name)
Definition at line 3630 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildArrayMalloc()
LLVMValueRef LLVMBuildArrayMalloc (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Val, const char * Name)
Definition at line 3591 of file Core.cpp.
References B, llvm::Type::getInt32Ty(), llvm::ConstantExpr::getSizeOf(), llvm::ConstantExpr::getTruncOrBitCast(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildAShr()
LLVMValueRef LLVMBuildAShr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3465 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildAtomicCmpXchg()
LLVMValueRef LLVMBuildAtomicCmpXchg (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Cmp, LLVMValueRef New, LLVMAtomicOrdering SuccessOrdering, LLVMAtomicOrdering FailureOrdering, LLVMBool SingleThread)
Definition at line 4076 of file Core.cpp.
References B, mapFromLLVMOrdering(), Ptr, llvm::SyncScope::SingleThread, llvm::SyncScope::System, llvm::unwrap(), and llvm::wrap().
LLVMBuildAtomicRMW()
LLVMValueRef LLVMBuildAtomicRMW (LLVMBuilderRef B, LLVMAtomicRMWBinOp op, LLVMValueRef PTR, LLVMValueRef Val, LLVMAtomicOrdering ordering, LLVMBool singleThread)
Definition at line 4065 of file Core.cpp.
References B, mapFromLLVMOrdering(), mapFromLLVMRMWBinOp(), op, llvm::SyncScope::SingleThread, llvm::SyncScope::System, llvm::unwrap(), and llvm::wrap().
LLVMBuildBinOp()
LLVMValueRef LLVMBuildBinOp (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3485 of file Core.cpp.
References B, LHS, map_from_llvmopcode(), Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildBitCast()
LLVMValueRef LLVMBuildBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3891 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildBr()
LLVMValueRef LLVMBuildBr (LLVMBuilderRef B, LLVMBasicBlockRef Dest)
Definition at line 3155 of file Core.cpp.
References B, llvm::unwrap(), and llvm::wrap().
LLVMBuildCall2()
LLVMValueRef LLVMBuildCall2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, const char * Name)
Definition at line 3976 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildCallWithOperandBundles()
LLVMValueRef LLVMBuildCallWithOperandBundles (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, LLVMOperandBundleRef * Bundles, unsigned NumBundles, const char * Name)
Definition at line 3985 of file Core.cpp.
References B, Name, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::unwrap(), and llvm::wrap().
LLVMBuildCast()
LLVMValueRef LLVMBuildCast (LLVMBuilderRef B, LLVMOpcode Op, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3919 of file Core.cpp.
References B, map_from_llvmopcode(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildCatchPad()
LLVMValueRef LLVMBuildCatchPad (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMValueRef * Args, unsigned NumArgs, const char * Name)
Definition at line 3209 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildCatchRet()
LLVMValueRef LLVMBuildCatchRet (LLVMBuilderRef B, LLVMValueRef CatchPad, LLVMBasicBlockRef BB)
Definition at line 3242 of file Core.cpp.
References B, llvm::unwrap(), and llvm::wrap().
LLVMBuildCatchSwitch()
LLVMValueRef LLVMBuildCatchSwitch (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMBasicBlockRef UnwindBB, unsigned NumHandlers, const char * Name)
Definition at line 3231 of file Core.cpp.
References B, llvm::Constant::getNullValue(), llvm::Type::getTokenTy(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildCleanupPad()
LLVMValueRef LLVMBuildCleanupPad (LLVMBuilderRef B, LLVMValueRef ParentPad, LLVMValueRef * Args, unsigned NumArgs, const char * Name)
Definition at line 3216 of file Core.cpp.
References B, llvm::Constant::getNullValue(), llvm::Type::getTokenTy(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildCleanupRet()
LLVMValueRef LLVMBuildCleanupRet (LLVMBuilderRef B, LLVMValueRef CatchPad, LLVMBasicBlockRef BB)
Definition at line 3248 of file Core.cpp.
References B, llvm::unwrap(), and llvm::wrap().
LLVMBuildCondBr()
LLVMValueRef LLVMBuildCondBr (LLVMBuilderRef B, LLVMValueRef If, LLVMBasicBlockRef Then, LLVMBasicBlockRef Else)
Definition at line 3159 of file Core.cpp.
References B, llvm::unwrap(), and llvm::wrap().
LLVMBuilderGetDefaultFPMathTag()
LLVMMetadataRef LLVMBuilderGetDefaultFPMathTag (LLVMBuilderRef Builder)
Get the dafult floating-point math metadata for a given builder.
See also
llvm::IRBuilder::getDefaultFPMathTag()
Definition at line 3136 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMBuilderSetDefaultFPMathTag()
void LLVMBuilderSetDefaultFPMathTag (LLVMBuilderRef Builder, LLVMMetadataRef FPMathTag)
Set the default floating-point math metadata for the given builder.
To clear the metadata, pass NULL to FPMathTag.
See also
llvm::IRBuilder::setDefaultFPMathTag()
Definition at line 3128 of file Core.cpp.
References llvm::unwrap().
LLVMBuildExactSDiv()
LLVMValueRef LLVMBuildExactSDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3430 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildExactUDiv()
LLVMValueRef LLVMBuildExactUDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3420 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildExtractElement()
LLVMValueRef LLVMBuildExtractElement (LLVMBuilderRef B, LLVMValueRef VecVal, LLVMValueRef Index, const char * Name)
Definition at line 4011 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildExtractValue()
LLVMValueRef LLVMBuildExtractValue (LLVMBuilderRef B, LLVMValueRef AggVal, unsigned Index, const char * Name)
Definition at line 4031 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFAdd()
LLVMValueRef LLVMBuildFAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3370 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildFCmp()
LLVMValueRef LLVMBuildFCmp (LLVMBuilderRef B, LLVMRealPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3963 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildFDiv()
LLVMValueRef LLVMBuildFDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3435 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildFence()
LLVMValueRef LLVMBuildFence (LLVMBuilderRef B, LLVMAtomicOrdering ordering, LLVMBool singleThread, const char * Name)
Definition at line 3728 of file Core.cpp.
References B, mapFromLLVMOrdering(), Name, llvm::SyncScope::SingleThread, llvm::SyncScope::System, llvm::unwrap(), and llvm::wrap().
LLVMBuildFMul()
LLVMValueRef LLVMBuildFMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3410 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildFNeg()
LLVMValueRef LLVMBuildFNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3506 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFPCast()
LLVMValueRef LLVMBuildFPCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3943 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFPExt()
LLVMValueRef LLVMBuildFPExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3876 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFPToSI()
LLVMValueRef LLVMBuildFPToSI (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3856 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFPToUI()
LLVMValueRef LLVMBuildFPToUI (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3851 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFPTrunc()
LLVMValueRef LLVMBuildFPTrunc (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3871 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFree()
LLVMValueRef LLVMBuildFree (LLVMBuilderRef B, LLVMValueRef PointerVal)
Definition at line 3635 of file Core.cpp.
References B, llvm::unwrap(), and llvm::wrap().
LLVMBuildFreeze()
LLVMValueRef LLVMBuildFreeze (LLVMBuilderRef B, LLVMValueRef Val, const char * Name)
Definition at line 4043 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildFRem()
LLVMValueRef LLVMBuildFRem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3450 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildFSub()
LLVMValueRef LLVMBuildFSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3390 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildGEP2()
LLVMValueRef LLVMBuildGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef * Indices, unsigned NumIndices, const char * Name)
Definition at line 3737 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildGlobalString()
LLVMValueRef LLVMBuildGlobalString (LLVMBuilderRef B, const char * Str, const char * Name)
Definition at line 3759 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildGlobalStringPtr()
LLVMValueRef LLVMBuildGlobalStringPtr (LLVMBuilderRef B, const char * Str, const char * Name)
Definition at line 3764 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildICmp()
LLVMValueRef LLVMBuildICmp (LLVMBuilderRef B, LLVMIntPredicate Op, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3956 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildInBoundsGEP2()
LLVMValueRef LLVMBuildInBoundsGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, LLVMValueRef * Indices, unsigned NumIndices, const char * Name)
Definition at line 3744 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildIndirectBr()
LLVMValueRef LLVMBuildIndirectBr (LLVMBuilderRef B, LLVMValueRef Addr, unsigned NumDests)
Definition at line 3169 of file Core.cpp.
References Addr, B, llvm::unwrap(), and llvm::wrap().
LLVMBuildInsertElement()
LLVMValueRef LLVMBuildInsertElement (LLVMBuilderRef B, LLVMValueRef VecVal, LLVMValueRef EltVal, LLVMValueRef Index, const char * Name)
Definition at line 4017 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildInsertValue()
LLVMValueRef LLVMBuildInsertValue (LLVMBuilderRef B, LLVMValueRef AggVal, LLVMValueRef EltVal, unsigned Index, const char * Name)
Definition at line 4036 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildIntCast()
LLVMValueRef LLVMBuildIntCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Deprecated: This cast is always signed.
Use LLVMBuildIntCast2 instead.
Definition at line 3937 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildIntCast2()
LLVMValueRef LLVMBuildIntCast2 (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, LLVMBool IsSigned, const char * Name)
Definition at line 3930 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildIntToPtr()
LLVMValueRef LLVMBuildIntToPtr (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3886 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildInvoke2()
LLVMValueRef LLVMBuildInvoke2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, const char * Name)
Definition at line 3174 of file Core.cpp.
References B, llvm::Catch, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildInvokeWithOperandBundles()
LLVMValueRef LLVMBuildInvokeWithOperandBundles (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Fn, LLVMValueRef * Args, unsigned NumArgs, LLVMBasicBlockRef Then, LLVMBasicBlockRef Catch, LLVMOperandBundleRef * Bundles, unsigned NumBundles, const char * Name)
Definition at line 3183 of file Core.cpp.
References B, llvm::Catch, Name, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::unwrap(), and llvm::wrap().
LLVMBuildIsNotNull()
LLVMValueRef LLVMBuildIsNotNull (LLVMBuilderRef B, LLVMValueRef Val, const char * Name)
Definition at line 4053 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildIsNull()
LLVMValueRef LLVMBuildIsNull (LLVMBuilderRef B, LLVMValueRef Val, const char * Name)
Definition at line 4048 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildLandingPad()
LLVMValueRef LLVMBuildLandingPad (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef PersFn, unsigned NumClauses, const char * Name)
Definition at line 3197 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildLoad2()
LLVMValueRef LLVMBuildLoad2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef PointerVal, const char * Name)
Definition at line 3639 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildLShr()
LLVMValueRef LLVMBuildLShr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3460 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildMalloc()
LLVMValueRef LLVMBuildMalloc (LLVMBuilderRef B, LLVMTypeRef Ty, const char * Name)
Definition at line 3582 of file Core.cpp.
References B, llvm::Type::getInt32Ty(), llvm::ConstantExpr::getSizeOf(), llvm::ConstantExpr::getTruncOrBitCast(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildMemCpy()
LLVMValueRef LLVMBuildMemCpy (LLVMBuilderRef B, LLVMValueRef Dst, unsigned DstAlign, LLVMValueRef Src, unsigned SrcAlign, LLVMValueRef Size)
Creates and inserts a memcpy between the specified pointers.
See also
llvm::IRRBuilder::CreateMemCpy()
Definition at line 3607 of file Core.cpp.
References B, Size, llvm::unwrap(), and llvm::wrap().
LLVMBuildMemMove()
LLVMValueRef LLVMBuildMemMove (LLVMBuilderRef B, LLVMValueRef Dst, unsigned DstAlign, LLVMValueRef Src, unsigned SrcAlign, LLVMValueRef Size)
Creates and inserts a memmove between the specified pointers.
See also
llvm::IRRBuilder::CreateMemMove()
Definition at line 3616 of file Core.cpp.
References B, Size, llvm::unwrap(), and llvm::wrap().
LLVMBuildMemSet()
LLVMValueRef LLVMBuildMemSet (LLVMBuilderRef B, LLVMValueRef Ptr, LLVMValueRef Val, LLVMValueRef Len, unsigned Align)
Creates and inserts a memset to the specified pointer and the specified value.
See also
llvm::IRRBuilder::CreateMemSet()
Definition at line 3600 of file Core.cpp.
References B, Ptr, llvm::unwrap(), and llvm::wrap().
LLVMBuildMul()
LLVMValueRef LLVMBuildMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3395 of file Core.cpp.
References B, CreateMul(), LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildNeg()
LLVMValueRef LLVMBuildNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3492 of file Core.cpp.
References B, CreateNeg(), Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNot()
LLVMValueRef LLVMBuildNot (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3510 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWAdd()
LLVMValueRef LLVMBuildNSWAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3360 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWMul()
LLVMValueRef LLVMBuildNSWMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3400 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWNeg()
LLVMValueRef LLVMBuildNSWNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3496 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNSWSub()
LLVMValueRef LLVMBuildNSWSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3380 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWAdd()
LLVMValueRef LLVMBuildNUWAdd (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3365 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWMul()
LLVMValueRef LLVMBuildNUWMul (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3405 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWNeg()
LLVMValueRef LLVMBuildNUWNeg (LLVMBuilderRef B, LLVMValueRef V, const char * Name)
Definition at line 3501 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildNUWSub()
LLVMValueRef LLVMBuildNUWSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3385 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildOr()
LLVMValueRef LLVMBuildOr (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3475 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildPhi()
LLVMValueRef LLVMBuildPhi (LLVMBuilderRef B, LLVMTypeRef Ty, const char * Name)
Definition at line 3972 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildPointerCast()
LLVMValueRef LLVMBuildPointerCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3925 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildPtrDiff2()
LLVMValueRef LLVMBuildPtrDiff2 (LLVMBuilderRef B, LLVMTypeRef ElemTy, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 4058 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildPtrToInt()
LLVMValueRef LLVMBuildPtrToInt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3881 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildResume()
LLVMValueRef LLVMBuildResume (LLVMBuilderRef B, LLVMValueRef Exn)
Definition at line 3227 of file Core.cpp.
References B, llvm::unwrap(), and llvm::wrap().
LLVMBuildRet()
LLVMValueRef LLVMBuildRet (LLVMBuilderRef B, LLVMValueRef V)
Definition at line 3146 of file Core.cpp.
References B, llvm::unwrap(), and llvm::wrap().
LLVMBuildRetVoid()
LLVMValueRef LLVMBuildRetVoid (LLVMBuilderRef B)
Definition at line 3142 of file Core.cpp.
References B, llvm::unwrap(), and llvm::wrap().
LLVMBuildSDiv()
LLVMValueRef LLVMBuildSDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3425 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildSelect()
LLVMValueRef LLVMBuildSelect (LLVMBuilderRef B, LLVMValueRef If, LLVMValueRef Then, LLVMValueRef Else, const char * Name)
Definition at line 3999 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildSExt()
LLVMValueRef LLVMBuildSExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3846 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildSExtOrBitCast()
LLVMValueRef LLVMBuildSExtOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3907 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildShl()
LLVMValueRef LLVMBuildShl (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3455 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildShuffleVector()
LLVMValueRef LLVMBuildShuffleVector (LLVMBuilderRef B, LLVMValueRef V1, LLVMValueRef V2, LLVMValueRef Mask, const char * Name)
Definition at line 4024 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildSIToFP()
LLVMValueRef LLVMBuildSIToFP (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3866 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildSRem()
LLVMValueRef LLVMBuildSRem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3445 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildStore()
LLVMValueRef LLVMBuildStore (LLVMBuilderRef B, LLVMValueRef Val, LLVMValueRef Ptr)
Definition at line 3644 of file Core.cpp.
References B, llvm::unwrap(), and llvm::wrap().
LLVMBuildStructGEP2()
LLVMValueRef LLVMBuildStructGEP2 (LLVMBuilderRef B, LLVMTypeRef Ty, LLVMValueRef Pointer, unsigned Idx, const char * Name)
Definition at line 3752 of file Core.cpp.
References B, Idx, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildSub()
LLVMValueRef LLVMBuildSub (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3375 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildSwitch()
LLVMValueRef LLVMBuildSwitch (LLVMBuilderRef B, LLVMValueRef V, LLVMBasicBlockRef Else, unsigned NumCases)
Definition at line 3164 of file Core.cpp.
References B, llvm::unwrap(), and llvm::wrap().
LLVMBuildTrunc()
LLVMValueRef LLVMBuildTrunc (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3836 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildTruncOrBitCast()
LLVMValueRef LLVMBuildTruncOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3913 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildUDiv()
LLVMValueRef LLVMBuildUDiv (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3415 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildUIToFP()
LLVMValueRef LLVMBuildUIToFP (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3861 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildUnreachable()
LLVMValueRef LLVMBuildUnreachable (LLVMBuilderRef B)
Definition at line 3254 of file Core.cpp.
References B, llvm::unwrap(), and llvm::wrap().
LLVMBuildURem()
LLVMValueRef LLVMBuildURem (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3440 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildVAArg()
LLVMValueRef LLVMBuildVAArg (LLVMBuilderRef B, LLVMValueRef List, LLVMTypeRef Ty, const char * Name)
Definition at line 4006 of file Core.cpp.
References B, List, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildXor()
LLVMValueRef LLVMBuildXor (LLVMBuilderRef B, LLVMValueRef LHS, LLVMValueRef RHS, const char * Name)
Definition at line 3480 of file Core.cpp.
References B, LHS, Name, RHS, llvm::unwrap(), and llvm::wrap().
LLVMBuildZExt()
LLVMValueRef LLVMBuildZExt (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3841 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMBuildZExtOrBitCast()
LLVMValueRef LLVMBuildZExtOrBitCast (LLVMBuilderRef B, LLVMValueRef Val, LLVMTypeRef DestTy, const char * Name)
Definition at line 3901 of file Core.cpp.
References B, Name, llvm::unwrap(), and llvm::wrap().
LLVMCanValueUseFastMathFlags()
LLVMBool LLVMCanValueUseFastMathFlags (LLVMValueRef Inst)
Check if a given value can potentially have fast math flags.
Will return true for floating point arithmetic instructions, and for select, phi, and call instructions whose type is a floating point type, or a vector or array thereof. See https://llvm.org/docs/LangRef.html#fast-math-flags
Definition at line 3565 of file Core.cpp.
LLVMClearInsertionPosition()
void LLVMClearInsertionPosition (LLVMBuilderRef Builder)
Definition at line 3078 of file Core.cpp.
References llvm::unwrap().
LLVMCreateBuilder()
LLVMBuilderRef LLVMCreateBuilder (void)
Definition at line 3053 of file Core.cpp.
References LLVMCreateBuilderInContext(), and LLVMGetGlobalContext().
LLVMCreateBuilderInContext()
LLVMBuilderRef LLVMCreateBuilderInContext (LLVMContextRef C)
Definition at line 3049 of file Core.cpp.
References llvm::CallingConv::C, llvm::unwrap(), and llvm::wrap().
Referenced by LLVMCreateBuilder().
LLVMDisposeBuilder()
void LLVMDisposeBuilder (LLVMBuilderRef Builder)
Definition at line 3091 of file Core.cpp.
References llvm::unwrap().
LLVMGetArgOperand()
LLVMValueRef LLVMGetArgOperand (LLVMValueRef Funclet, unsigned i)
Definition at line 3312 of file Core.cpp.
References llvm::wrap().
LLVMGetAtomicRMWBinOp()
LLVMAtomicRMWBinOp LLVMGetAtomicRMWBinOp (LLVMValueRef AtomicRMWInst)
Definition at line 3826 of file Core.cpp.
References mapToLLVMRMWBinOp().
LLVMGetCastOpcode()
LLVMOpcode LLVMGetCastOpcode (LLVMValueRef Src, LLVMBool SrcIsSigned, LLVMTypeRef DestTy, LLVMBool DestIsSigned)
Definition at line 3948 of file Core.cpp.
References llvm::CastInst::getCastOpcode(), map_to_llvmopcode(), and llvm::unwrap().
LLVMGetClause()
LLVMValueRef LLVMGetClause (LLVMValueRef LandingPad, unsigned Idx)
Definition at line 3271 of file Core.cpp.
References Idx, and llvm::wrap().
LLVMGetCmpXchgFailureOrdering()
LLVMAtomicOrdering LLVMGetCmpXchgFailureOrdering (LLVMValueRef CmpXchgInst)
Definition at line 4146 of file Core.cpp.
References mapToLLVMOrdering(), P, and llvm::unwrap().
LLVMGetCmpXchgSuccessOrdering()
LLVMAtomicOrdering LLVMGetCmpXchgSuccessOrdering (LLVMValueRef CmpXchgInst)
Definition at line 4133 of file Core.cpp.
References mapToLLVMOrdering(), P, and llvm::unwrap().
LLVMGetCurrentDebugLocation()
LLVMValueRef LLVMGetCurrentDebugLocation (LLVMBuilderRef Builder)
Deprecated: Returning the NULL location will crash.
Use LLVMGetCurrentDebugLocation2 instead.
Definition at line 3114 of file Core.cpp.
References Context, llvm::MetadataAsValue::get(), llvm::unwrap(), and llvm::wrap().
LLVMGetCurrentDebugLocation2()
LLVMMetadataRef LLVMGetCurrentDebugLocation2 (LLVMBuilderRef Builder)
Get location information used by debugging information.
See also
llvm::IRBuilder::getCurrentDebugLocation()
Definition at line 3097 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetExact()
LLVMBool LLVMGetExact (LLVMValueRef DivOrShrInst)
Definition at line 3534 of file Core.cpp.
References P.
LLVMGetFastMathFlags()
LLVMFastMathFlags LLVMGetFastMathFlags (LLVMValueRef FPMathInst)
Get the flags for which fast-math-style optimizations are allowed for this value.
Only valid on floating point instructions.
See also
LLVMCanValueUseFastMathFlags
Definition at line 3554 of file Core.cpp.
References mapToLLVMFastMathFlags(), and P.
LLVMGetHandlers()
void LLVMGetHandlers (LLVMValueRef CatchSwitch, LLVMBasicBlockRef * Handlers)
Obtain the basic blocks acting as handlers for a catchswitch instruction.
The Handlers parameter should point to a pre-allocated array of LLVMBasicBlockRefs at least LLVMGetNumHandlers() large. On return, the first LLVMGetNumHandlers() entries in the array will be populated with LLVMBasicBlockRef instances.
Parameters
CatchSwitch The catchswitch instruction to operate on.
Handlers Memory address of an array to be filled with basic blocks.
Definition at line 3295 of file Core.cpp.
References H, llvm::CatchSwitchInst::handlers(), and llvm::wrap().
LLVMGetInsertBlock()
LLVMBasicBlockRef LLVMGetInsertBlock (LLVMBuilderRef Builder)
Definition at line 3074 of file Core.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMGetIsDisjoint()
LLVMBool LLVMGetIsDisjoint (LLVMValueRef Inst)
Gets whether the instruction has the disjoint flag set.
Only valid for or instructions.
Definition at line 3570 of file Core.cpp.
References P.
LLVMGetMaskValue()
int LLVMGetMaskValue (LLVMValueRef ShuffleVectorInst, unsigned Elt)
Get the mask value at position Elt in the mask of a ShuffleVector instruction.
\Returns the result of LLVMGetUndefMaskElem() if the mask value is poison at that position.
Definition at line 4095 of file Core.cpp.
References I, P, and llvm::unwrap().
LLVMGetNNeg()
LLVMBool LLVMGetNNeg (LLVMValueRef NonNegInst)
Gets if the instruction has the non-negative flag set.
Only valid for zext instructions.
Definition at line 3544 of file Core.cpp.
References P.
LLVMGetNSW()
LLVMBool LLVMGetNSW (LLVMValueRef ArithInst)
Definition at line 3524 of file Core.cpp.
References P.
LLVMGetNumClauses()
unsigned LLVMGetNumClauses (LLVMValueRef LandingPad)
Definition at line 3267 of file Core.cpp.
LLVMGetNumHandlers()
unsigned LLVMGetNumHandlers (LLVMValueRef CatchSwitch)
Definition at line 3291 of file Core.cpp.
LLVMGetNumMaskElements()
unsigned LLVMGetNumMaskElements (LLVMValueRef ShuffleVectorInst)
Get the number of elements in the mask of a ShuffleVector instruction.
Definition at line 4089 of file Core.cpp.
References I, P, and llvm::unwrap().
LLVMGetNUW()
LLVMBool LLVMGetNUW (LLVMValueRef ArithInst)
Definition at line 3514 of file Core.cpp.
References P.
LLVMGetOrdering()
LLVMAtomicOrdering LLVMGetOrdering (LLVMValueRef MemoryAccessInst)
Definition at line 3799 of file Core.cpp.
References mapToLLVMOrdering(), P, and llvm::unwrap().
LLVMGetParentCatchSwitch()
LLVMValueRef LLVMGetParentCatchSwitch (LLVMValueRef CatchPad)
Get the parent catchswitch instruction of a catchpad instruction.
This only works on llvm::CatchPadInst instructions.
See also
llvm::CatchPadInst::getCatchSwitch()
Definition at line 3301 of file Core.cpp.
References llvm::wrap().
LLVMGetUndefMaskElem()
int LLVMGetUndefMaskElem (void)
Returns
a constant that specifies that the result of a ShuffleVectorInst is undefined.
Definition at line 4101 of file Core.cpp.
References llvm::PoisonMaskElem.
LLVMGetVolatile()
LLVMBool LLVMGetVolatile (LLVMValueRef MemoryAccessInst)
Definition at line 3769 of file Core.cpp.
References P, and llvm::unwrap().
LLVMGetWeak()
LLVMBool LLVMGetWeak (LLVMValueRef CmpXchgInst)
Definition at line 3791 of file Core.cpp.
LLVMInsertIntoBuilder()
void LLVMInsertIntoBuilder (LLVMBuilderRef Builder, LLVMValueRef Instr)
Definition at line 3082 of file Core.cpp.
References llvm::unwrap().
LLVMInsertIntoBuilderWithName()
void LLVMInsertIntoBuilderWithName (LLVMBuilderRef Builder, LLVMValueRef Instr, const char * Name)
Definition at line 3086 of file Core.cpp.
References Name, and llvm::unwrap().
LLVMIsAtomicSingleThread()
LLVMBool LLVMIsAtomicSingleThread (LLVMValueRef AtomicInst)
Definition at line 4103 of file Core.cpp.
References I, P, llvm::SyncScope::SingleThread, and llvm::unwrap().
LLVMIsCleanup()
LLVMBool LLVMIsCleanup (LLVMValueRef LandingPad)
Definition at line 3279 of file Core.cpp.
LLVMPositionBuilder()
void LLVMPositionBuilder (LLVMBuilderRef Builder, LLVMBasicBlockRef Block, LLVMValueRef Instr)
Definition at line 3057 of file Core.cpp.
References llvm::Block, llvm::BasicBlock::end(), I, and llvm::unwrap().
LLVMPositionBuilderAtEnd()
void LLVMPositionBuilderAtEnd (LLVMBuilderRef Builder, LLVMBasicBlockRef Block)
Definition at line 3069 of file Core.cpp.
References llvm::Block, and llvm::unwrap().
LLVMPositionBuilderBefore()
void LLVMPositionBuilderBefore (LLVMBuilderRef Builder, LLVMValueRef Instr)
Definition at line 3064 of file Core.cpp.
References I, and llvm::unwrap().
LLVMSetArgOperand()
void LLVMSetArgOperand (LLVMValueRef Funclet, unsigned i, LLVMValueRef value)
Definition at line 3316 of file Core.cpp.
References llvm::unwrap(), and value.
LLVMSetAtomicRMWBinOp()
void LLVMSetAtomicRMWBinOp (LLVMValueRef AtomicRMWInst, LLVMAtomicRMWBinOp BinOp)
Definition at line 3830 of file Core.cpp.
References mapFromLLVMRMWBinOp().
LLVMSetAtomicSingleThread()
void LLVMSetAtomicSingleThread (LLVMValueRef AtomicInst, LLVMBool SingleThread)
Definition at line 4118 of file Core.cpp.
References I, P, llvm::SyncScope::SingleThread, llvm::SyncScope::System, and llvm::unwrap().
LLVMSetCleanup()
void LLVMSetCleanup (LLVMValueRef LandingPad, LLVMBool Val)
Definition at line 3283 of file Core.cpp.
LLVMSetCmpXchgFailureOrdering()
void LLVMSetCmpXchgFailureOrdering (LLVMValueRef CmpXchgInst, LLVMAtomicOrdering Ordering)
Definition at line 4151 of file Core.cpp.
References mapFromLLVMOrdering(), P, and llvm::unwrap().
LLVMSetCmpXchgSuccessOrdering()
void LLVMSetCmpXchgSuccessOrdering (LLVMValueRef CmpXchgInst, LLVMAtomicOrdering Ordering)
Definition at line 4138 of file Core.cpp.
References mapFromLLVMOrdering(), P, and llvm::unwrap().
LLVMSetCurrentDebugLocation()
void LLVMSetCurrentDebugLocation (LLVMBuilderRef Builder, LLVMValueRef L)
Deprecated: Passing the NULL location will crash.
Use LLVMGetCurrentDebugLocation2 instead.
Definition at line 3108 of file Core.cpp.
References llvm::unwrap().
LLVMSetCurrentDebugLocation2()
void LLVMSetCurrentDebugLocation2 (LLVMBuilderRef Builder, LLVMMetadataRef Loc)
Set location information used by debugging information.
To clear the location metadata of the given instruction, pass NULL to Loc.
See also
llvm::IRBuilder::SetCurrentDebugLocation()
Definition at line 3101 of file Core.cpp.
References llvm::unwrap().
LLVMSetExact()
void LLVMSetExact (LLVMValueRef DivOrShrInst, LLVMBool IsExact)
Definition at line 3539 of file Core.cpp.
References P.
LLVMSetFastMathFlags()
void LLVMSetFastMathFlags (LLVMValueRef FPMathInst, LLVMFastMathFlags FMF)
Sets the flags for which fast-math-style optimizations are allowed for this value.
Only valid on floating point instructions.
See also
LLVMCanValueUseFastMathFlags
Definition at line 3560 of file Core.cpp.
References mapFromLLVMFastMathFlags(), and P.
LLVMSetInstDebugLocation()
void LLVMSetInstDebugLocation (LLVMBuilderRef Builder, LLVMValueRef Inst)
Attempts to set the debug location for the given instruction using the current debug location for the given builder.
If the builder has no current debug location, this function is a no-op.
Deprecated:
LLVMSetInstDebugLocation is deprecated in favor of the more general LLVMAddMetadataToInst.
See also
llvm::IRBuilder::SetInstDebugLocation()
Definition at line 3120 of file Core.cpp.
References llvm::unwrap().
LLVMSetIsDisjoint()
void LLVMSetIsDisjoint (LLVMValueRef Inst, LLVMBool IsDisjoint)
Sets the disjoint flag for the instruction.
Only valid for or instructions.
Definition at line 3575 of file Core.cpp.
References P.
LLVMSetNNeg()
void LLVMSetNNeg (LLVMValueRef NonNegInst, LLVMBool IsNonNeg)
Sets the non-negative flag for the instruction.
Only valid for zext instructions.
Definition at line 3549 of file Core.cpp.
References P.
LLVMSetNSW()
void LLVMSetNSW (LLVMValueRef ArithInst, LLVMBool HasNSW)
Definition at line 3529 of file Core.cpp.
References P.
LLVMSetNUW()
void LLVMSetNUW (LLVMValueRef ArithInst, LLVMBool HasNUW)
Definition at line 3519 of file Core.cpp.
References P.
LLVMSetOrdering()
void LLVMSetOrdering (LLVMValueRef MemoryAccessInst, LLVMAtomicOrdering Ordering)
Definition at line 3813 of file Core.cpp.
References mapFromLLVMOrdering(), P, and llvm::unwrap().
LLVMSetParentCatchSwitch()
void LLVMSetParentCatchSwitch (LLVMValueRef CatchPad, LLVMValueRef CatchSwitch)
Set the parent catchswitch instruction of a catchpad instruction.
This only works on llvm::CatchPadInst instructions.
See also
llvm::CatchPadInst::setCatchSwitch()
Definition at line 3305 of file Core.cpp.
LLVMSetVolatile()
void LLVMSetVolatile (LLVMValueRef MemoryAccessInst, LLVMBool IsVolatile)
Definition at line 3780 of file Core.cpp.
References P, and llvm::unwrap().
LLVMSetWeak()
void LLVMSetWeak (LLVMValueRef CmpXchgInst, LLVMBool IsWeak)
Definition at line 3795 of file Core.cpp.