LLVM: Composite Constants
Composite Constants
LLVM-C: C interface to LLVM » Core » Values » Constants
Functions in this group operate on composite constants.
Functions
LLVMValueRef LLVMConstStringInContext (LLVMContextRef C, const char *Str, unsigned Length, LLVMBool DontNullTerminate)
Create a ConstantDataSequential and initialize it with a string.
LLVMValueRef LLVMConstString (const char *Str, unsigned Length, LLVMBool DontNullTerminate)
Create a ConstantDataSequential with string content in the global context.
LLVMBool LLVMIsConstantString (LLVMValueRef c)
Returns true if the specified constant is an array of i8.
const char * LLVMGetAsString (LLVMValueRef c, size_t *Length)
Get the given constant data sequential as a string.
LLVMValueRef LLVMConstStructInContext (LLVMContextRef C, LLVMValueRef *ConstantVals, unsigned Count, LLVMBool Packed)
Create an anonymous ConstantStruct with the specified values.
LLVMValueRef LLVMConstStruct (LLVMValueRef *ConstantVals, unsigned Count, LLVMBool Packed)
Create a ConstantStruct in the global Context.
LLVMValueRef LLVMConstArray (LLVMTypeRef ElementTy, LLVMValueRef *ConstantVals, unsigned Length)
Create a ConstantArray from values.
LLVMValueRef LLVMConstArray2 (LLVMTypeRef ElementTy, LLVMValueRef *ConstantVals, uint64_t Length)
Create a ConstantArray from values.
LLVMValueRef LLVMConstNamedStruct (LLVMTypeRef StructTy, LLVMValueRef *ConstantVals, unsigned Count)
Create a non-anonymous ConstantStruct from values.
LLVMValueRef LLVMGetAggregateElement (LLVMValueRef C, unsigned Idx)
Get element of a constant aggregate (struct, array or vector) at the specified index.
LLVM_ATTRIBUTE_C_DEPRECATED (LLVMValueRef LLVMGetElementAsConstant(LLVMValueRef C, unsigned idx), "Use LLVMGetAggregateElement instead")
Get an element at specified index as a constant.
LLVMValueRef LLVMConstVector (LLVMValueRef *ScalarConstantVals, unsigned Size)
Create a ConstantVector from values.
Detailed Description
Functions in this group operate on composite constants.
Function Documentation
LLVM_ATTRIBUTE_C_DEPRECATED()
LLVM_ATTRIBUTE_C_DEPRECATED (LLVMValueRef LLVMGetElementAsConstantLLVMValueRef C, unsigned idx, "Use LLVMGetAggregateElement instead")
Get an element at specified index as a constant.
See also
ConstantDataSequential::getElementAsConstant()
LLVMConstArray()
LLVMValueRef LLVMConstArray (LLVMTypeRef ElementTy, LLVMValueRef * ConstantVals, unsigned Length)
Create a ConstantArray from values.
Deprecated:
LLVMConstArray is deprecated in favor of the API accurate LLVMConstArray2
See also
llvm::ConstantArray::get()
Definition at line 1549 of file Core.cpp.
References llvm::ConstantArray::get(), llvm::Length, llvm::unwrap(), and llvm::wrap().
LLVMConstArray2()
LLVMValueRef LLVMConstArray2 (LLVMTypeRef ElementTy, LLVMValueRef * ConstantVals, uint64_t Length)
Create a ConstantArray from values.
See also
llvm::ConstantArray::get()
Definition at line 1555 of file Core.cpp.
References llvm::ConstantArray::get(), llvm::Length, llvm::unwrap(), and llvm::wrap().
LLVMConstNamedStruct()
LLVMValueRef LLVMConstNamedStruct (LLVMTypeRef StructTy, LLVMValueRef * ConstantVals, unsigned Count)
Create a non-anonymous ConstantStruct from values.
See also
llvm::ConstantStruct::get()
Definition at line 1575 of file Core.cpp.
References llvm::ConstantStruct::get(), and llvm::wrap().
LLVMConstString()
LLVMValueRef LLVMConstString (const char * Str, unsigned Length, LLVMBool DontNullTerminate)
Create a ConstantDataSequential with string content in the global context.
This is the same as LLVMConstStringInContext except it operates on the global context.
See also
LLVMConstStringInContext()
llvm::ConstantDataArray::getString()
Definition at line 1525 of file Core.cpp.
References llvm::Length, LLVMConstStringInContext(), and LLVMGetGlobalContext().
LLVMConstStringInContext()
LLVMValueRef LLVMConstStringInContext (LLVMContextRef C, const char * Str, unsigned Length, LLVMBool DontNullTerminate)
Create a ConstantDataSequential and initialize it with a string.
See also
llvm::ConstantDataArray::getString()
Definition at line 1516 of file Core.cpp.
References llvm::CallingConv::C, llvm::ConstantDataArray::getString(), llvm::Length, llvm::unwrap(), and llvm::wrap().
Referenced by LLVMConstString().
LLVMConstStruct()
LLVMValueRef LLVMConstStruct (LLVMValueRef * ConstantVals, unsigned Count, LLVMBool Packed)
Create a ConstantStruct in the global Context.
This is the same as LLVMConstStructInContext except it operates on the global Context.
See also
LLVMConstStructInContext()
Definition at line 1569 of file Core.cpp.
References LLVMConstStructInContext(), and LLVMGetGlobalContext().
LLVMConstStructInContext()
LLVMValueRef LLVMConstStructInContext (LLVMContextRef C, LLVMValueRef * ConstantVals, unsigned Count, LLVMBool Packed)
Create an anonymous ConstantStruct with the specified values.
See also
llvm::ConstantStruct::getAnon()
Definition at line 1561 of file Core.cpp.
References llvm::CallingConv::C, llvm::ConstantStruct::getAnon(), llvm::unwrap(), and llvm::wrap().
Referenced by LLVMConstStruct().
LLVMConstVector()
LLVMValueRef LLVMConstVector (LLVMValueRef * ScalarConstantVals, unsigned Size)
Create a ConstantVector from values.
See also
llvm::ConstantVector::get()
Definition at line 1584 of file Core.cpp.
References llvm::ConstantVector::get(), Size, and llvm::wrap().
LLVMGetAggregateElement()
LLVMValueRef LLVMGetAggregateElement (LLVMValueRef C, unsigned Idx)
Get element of a constant aggregate (struct, array or vector) at the specified index.
Returns null if the index is out of range, or it's not possible to determine the element (e.g., because the constant is a constant expression.)
See also
llvm::Constant::getAggregateElement()
Definition at line 1531 of file Core.cpp.
References llvm::CallingConv::C, Idx, and llvm::wrap().
LLVMGetAsString()
const char * LLVMGetAsString (LLVMValueRef c, size_t * Length)
Get the given constant data sequential as a string.
See also
ConstantDataSequential::getAsString()
Definition at line 1543 of file Core.cpp.
References llvm::CallingConv::C, and llvm::Length.
LLVMIsConstantString()
LLVMBool LLVMIsConstantString (LLVMValueRef c)
Returns true if the specified constant is an array of i8.
See also
ConstantDataSequential::getAsString()
Definition at line 1539 of file Core.cpp.
References llvm::CallingConv::C.