LLVM: Dwarf constants dumping functions
Dwarf constants dumping functions
All these functions map their argument's value back to the corresponding enumerator name or return an empty StringRef if the value isn't known.
Functions
StringRef llvm::dwarf::TagString (unsigned Tag)
StringRef llvm::dwarf::ChildrenString (unsigned Children)
StringRef llvm::dwarf::AttributeString (unsigned Attribute)
StringRef llvm::dwarf::FormEncodingString (unsigned Encoding)
StringRef llvm::dwarf::OperationEncodingString (unsigned Encoding)
StringRef llvm::dwarf::SubOperationEncodingString (unsigned OpEncoding, unsigned SubOpEncoding)
StringRef llvm::dwarf::AttributeEncodingString (unsigned Encoding)
StringRef llvm::dwarf::DecimalSignString (unsigned Sign)
StringRef llvm::dwarf::EndianityString (unsigned Endian)
StringRef llvm::dwarf::AccessibilityString (unsigned Access)
StringRef llvm::dwarf::DefaultedMemberString (unsigned DefaultedEncodings)
StringRef llvm::dwarf::VisibilityString (unsigned Visibility)
StringRef llvm::dwarf::VirtualityString (unsigned Virtuality)
StringRef llvm::dwarf::LanguageString (unsigned Language)
StringRef llvm::dwarf::CaseString (unsigned Case)
StringRef llvm::dwarf::ConventionString (unsigned Convention)
StringRef llvm::dwarf::InlineCodeString (unsigned Code)
StringRef llvm::dwarf::ArrayOrderString (unsigned Order)
StringRef llvm::dwarf::LNStandardString (unsigned Standard)
StringRef llvm::dwarf::LNExtendedString (unsigned Encoding)
StringRef llvm::dwarf::MacinfoString (unsigned Encoding)
StringRef llvm::dwarf::MacroString (unsigned Encoding)
StringRef llvm::dwarf::GnuMacroString (unsigned Encoding)
StringRef llvm::dwarf::RangeListEncodingString (unsigned Encoding)
StringRef llvm::dwarf::LocListEncodingString (unsigned Encoding)
StringRef llvm::dwarf::CallFrameString (unsigned Encoding, Triple::ArchType Arch)
StringRef llvm::dwarf::ApplePropertyString (unsigned)
StringRef llvm::dwarf::UnitTypeString (unsigned)
StringRef llvm::dwarf::AtomTypeString (unsigned Atom)
StringRef llvm::dwarf::GDBIndexEntryKindString (GDBIndexEntryKind Kind)
StringRef llvm::dwarf::GDBIndexEntryLinkageString (GDBIndexEntryLinkage Linkage)
StringRef llvm::dwarf::IndexString (unsigned Idx)
StringRef llvm::dwarf::FormatString (DwarfFormat Format)
StringRef llvm::dwarf::FormatString (bool IsDWARF64)
StringRef llvm::dwarf::RLEString (unsigned RLE)
Detailed Description
All these functions map their argument's value back to the corresponding enumerator name or return an empty StringRef if the value isn't known.
Function Documentation
AccessibilityString()
StringRef llvm::dwarf::AccessibilityString (unsigned Access)
Definition at line 304 of file Dwarf.cpp.
References llvm::dwarf::DW_ACCESS_private, llvm::dwarf::DW_ACCESS_protected, and llvm::dwarf::DW_ACCESS_public.
Referenced by llvm::dwarf::AttributeValueString(), and llvm::AsmPrinter::emitDwarfDIE().
ApplePropertyString()
StringRef llvm::dwarf::ApplePropertyString (unsigned Prop)
Definition at line 600 of file Dwarf.cpp.
Referenced by dumpApplePropertyAttribute().
ArrayOrderString()
StringRef llvm::dwarf::ArrayOrderString (unsigned Order)
Definition at line 460 of file Dwarf.cpp.
References llvm::dwarf::DW_ORD_col_major, and llvm::dwarf::DW_ORD_row_major.
Referenced by llvm::dwarf::AttributeValueString().
AtomTypeString()
StringRef llvm::dwarf::AtomTypeString (unsigned Atom)
Definition at line 622 of file Dwarf.cpp.
References llvm::dwarf::DW_ATOM_cu_offset, llvm::dwarf::DW_ATOM_die_offset, llvm::dwarf::DW_ATOM_die_tag, llvm::dwarf::DW_ATOM_null, llvm::dwarf::DW_ATOM_qual_name_hash, llvm::dwarf::DW_ATOM_type_flags, and llvm::dwarf::DW_ATOM_type_type_flags.
Referenced by llvm::AppleAccelTableData::Atom::print().
AttributeEncodingString()
StringRef llvm::dwarf::AttributeEncodingString (unsigned Encoding)
Definition at line 231 of file Dwarf.cpp.
Referenced by llvm::dwarf::AttributeValueString(), llvm::DwarfCompileUnit::createBaseTypeDIEs(), printModuleDebugInfo(), writeDIBasicType(), writeDIExpression(), and writeDIStringType().
AttributeString()
StringRef llvm::dwarf::AttributeString (unsigned Attribute)
Definition at line 72 of file Dwarf.cpp.
Referenced by llvm::DIEAbbrev::Emit(), llvm::AsmPrinter::emitDwarfDIE(), llvm::DWARFDie::getLocations(), DOTGraphTraits< const CallsiteContextGraph< DerivedCCG, FuncTy, CallTy > * >::getNodeAttributes(), llvm::DIEAbbrev::print(), and llvm::DIE::print().
CallFrameString()
StringRef llvm::dwarf::CallFrameString (unsigned Encoding, Triple::ArchType Arch)
Definition at line 571 of file Dwarf.cpp.
References assert(), and llvm::Triple::UnknownArch.
Referenced by llvm::dwarf::CFIProgram::callFrameString().
CaseString()
StringRef llvm::dwarf::CaseString (unsigned Case)
Definition at line 414 of file Dwarf.cpp.
References llvm::dwarf::DW_ID_case_insensitive, llvm::dwarf::DW_ID_case_sensitive, llvm::dwarf::DW_ID_down_case, and llvm::dwarf::DW_ID_up_case.
Referenced by llvm::dwarf::AttributeValueString().
ChildrenString()
StringRef llvm::dwarf::ChildrenString (unsigned Children)
Definition at line 62 of file Dwarf.cpp.
References llvm::dwarf::DW_CHILDREN_no, and llvm::dwarf::DW_CHILDREN_yes.
Referenced by llvm::DIEAbbrev::Emit(), llvm::DIEAbbrev::print(), and llvm::DIE::print().
ConventionString()
StringRef llvm::dwarf::ConventionString (unsigned Convention)
Definition at line 428 of file Dwarf.cpp.
References CC.
Referenced by llvm::dwarf::AttributeValueString(), and writeDISubroutineType().
DecimalSignString()
StringRef llvm::dwarf::DecimalSignString (unsigned Sign)
Definition at line 272 of file Dwarf.cpp.
References llvm::dwarf::DW_DS_leading_overpunch, llvm::dwarf::DW_DS_leading_separate, llvm::dwarf::DW_DS_trailing_overpunch, llvm::dwarf::DW_DS_trailing_separate, and llvm::dwarf::DW_DS_unsigned.
Referenced by llvm::dwarf::AttributeValueString().
DefaultedMemberString()
StringRef llvm::dwarf::DefaultedMemberString (unsigned DefaultedEncodings)
Definition at line 317 of file Dwarf.cpp.
Referenced by llvm::dwarf::AttributeValueString().
EndianityString()
StringRef llvm::dwarf::EndianityString (unsigned Endian)
Definition at line 288 of file Dwarf.cpp.
References llvm::dwarf::DW_END_hi_user, llvm::dwarf::DW_END_lo_user, and Endian.
Referenced by llvm::dwarf::AttributeValueString().
FormatString() [1/2]
StringRef llvm::dwarf::FormatString (bool IsDWARF64)
Definition at line 836 of file Dwarf.cpp.
References llvm::dwarf::DWARF32, llvm::dwarf::DWARF64, and llvm::dwarf::FormatString().
FormatString() [2/2]
StringRef llvm::dwarf::FormatString (DwarfFormat Format)
Definition at line 826 of file Dwarf.cpp.
References llvm::dwarf::DWARF32, and llvm::dwarf::DWARF64.
Referenced by llvm::DWARFListTableHeader::dump(), llvm::DWARFDebugArangeSet::dump(), llvm::DWARFDebugPubTable::dump(), llvm::DWARFDebugLine::Prologue::dump(), llvm::dwarf::CIE::dump(), llvm::dwarf::FDE::dump(), llvm::DWARFCompileUnit::dump(), llvm::DWARFDebugAddrTable::dump(), llvm::DWARFTypeUnit::dump(), llvm::DWARFDebugNames::Header::dump(), dumpStringOffsetsSection(), and llvm::dwarf::FormatString().
FormEncodingString()
StringRef llvm::dwarf::FormEncodingString (unsigned Encoding)
Definition at line 105 of file Dwarf.cpp.
Referenced by llvm::dwarf_linker::parallel::DIEAttributeCloner::clone(), llvm::DIEAbbrev::Emit(), llvm::AppleAcceleratorTable::extract(), llvm::DWARFFormValue::getAsCString(), llvm::DWARFDie::getLocations(), llvm::DIEAbbrev::print(), llvm::DIE::print(), llvm::AppleAccelTableData::Atom::print(), and printValues().
GDBIndexEntryKindString()
StringRef llvm::dwarf::GDBIndexEntryKindString (GDBIndexEntryKind Kind)
Definition at line 641 of file Dwarf.cpp.
References llvm::dwarf::GIEK_FUNCTION, llvm::dwarf::GIEK_NONE, llvm::dwarf::GIEK_OTHER, llvm::dwarf::GIEK_TYPE, llvm::dwarf::GIEK_UNUSED5, llvm::dwarf::GIEK_UNUSED6, llvm::dwarf::GIEK_UNUSED7, llvm::dwarf::GIEK_VARIABLE, and llvm_unreachable.
Referenced by llvm::DWARFDebugPubTable::dump().
GDBIndexEntryLinkageString()
StringRef llvm::dwarf::GDBIndexEntryLinkageString (GDBIndexEntryLinkage Linkage)
Definition at line 664 of file Dwarf.cpp.
References llvm::dwarf::GIEL_EXTERNAL, llvm::dwarf::GIEL_STATIC, and llvm_unreachable.
Referenced by llvm::DWARFDebugPubTable::dump().
GnuMacroString()
StringRef llvm::dwarf::GnuMacroString (unsigned Encoding)
Definition at line 532 of file Dwarf.cpp.
Referenced by llvm::DWARFDebugMacro::dump().
IndexString()
StringRef llvm::dwarf::IndexString (unsigned Idx)
Definition at line 718 of file Dwarf.cpp.
References Idx.
InlineCodeString()
StringRef llvm::dwarf::InlineCodeString (unsigned Code)
Definition at line 446 of file Dwarf.cpp.
References llvm::dwarf::DW_INL_declared_inlined, llvm::dwarf::DW_INL_declared_not_inlined, llvm::dwarf::DW_INL_inlined, and llvm::dwarf::DW_INL_not_inlined.
Referenced by llvm::dwarf::AttributeValueString().
LanguageString()
StringRef llvm::dwarf::LanguageString (unsigned Language)
Definition at line 361 of file Dwarf.cpp.
Referenced by llvm::dwarf::AttributeValueString(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), llvm::dwarf::getLanguage(), printModuleDebugInfo(), writeDICompileUnit(), and writeDICompositeType().
LNExtendedString()
StringRef llvm::dwarf::LNExtendedString (unsigned Encoding)
Definition at line 481 of file Dwarf.cpp.
Referenced by llvm::DWARFDebugLine::LineTable::parse().
LNStandardString()
StringRef llvm::dwarf::LNStandardString (unsigned Standard)
Definition at line 470 of file Dwarf.cpp.
Referenced by getOpcodeName(), and llvm::DWARFDebugLine::LineTable::parse().
LocListEncodingString()
StringRef llvm::dwarf::LocListEncodingString (unsigned Encoding)
Definition at line 560 of file Dwarf.cpp.
Referenced by llvm::DWARFDebugLoclists::dumpRawEntry(), emitLocList(), llvm::ResolverError::log(), and writeListEntry().
MacinfoString()
StringRef llvm::dwarf::MacinfoString (unsigned Encoding)
Definition at line 492 of file Dwarf.cpp.
References llvm::dwarf::DW_MACINFO_define, llvm::dwarf::DW_MACINFO_end_file, llvm::dwarf::DW_MACINFO_invalid, llvm::dwarf::DW_MACINFO_start_file, llvm::dwarf::DW_MACINFO_undef, and llvm::dwarf::DW_MACINFO_vendor_ext.
Referenced by llvm::DWARFDebugMacro::dump(), and llvm::dwarf::getMacinfo().
MacroString()
StringRef llvm::dwarf::MacroString (unsigned Encoding)
Definition at line 521 of file Dwarf.cpp.
Referenced by llvm::DWARFDebugMacro::dump(), and llvm::dwarf::getMacro().
OperationEncodingString()
StringRef llvm::dwarf::OperationEncodingString (unsigned Encoding)
Definition at line 138 of file Dwarf.cpp.
References llvm::dwarf::DW_OP_LLVM_arg, llvm::dwarf::DW_OP_LLVM_convert, llvm::dwarf::DW_OP_LLVM_entry_value, llvm::dwarf::DW_OP_LLVM_fragment, llvm::dwarf::DW_OP_LLVM_implicit_pointer, and llvm::dwarf::DW_OP_LLVM_tag_offset.
Referenced by emitDebugValueComment(), llvm::dwarf::getOperationEncoding(), llvm::DWARFExpression::Operation::print(), llvm::printCompactDWARFExpr(), writeDIExpression(), and writeDWARFExpression().
RangeListEncodingString()
StringRef llvm::dwarf::RangeListEncodingString (unsigned Encoding)
Definition at line 549 of file Dwarf.cpp.
Referenced by llvm::DWARFListTableBase< DWARFListType >::dump(), llvm::RangeListEntry::dump(), emitRangeList(), and writeListEntry().
RLEString()
StringRef llvm::dwarf::RLEString (unsigned RLE)
Definition at line 840 of file Dwarf.cpp.
Referenced by llvm::RangeListEntry::extract().
SubOperationEncodingString()
StringRef llvm::dwarf::SubOperationEncodingString (unsigned OpEncoding, unsigned SubOpEncoding)
Definition at line 196 of file Dwarf.cpp.
References assert(), and LlvmUserOperationEncodingString().
Referenced by llvm::dwarf::getSubOperationEncoding(), and llvm::DWARFExpression::Operation::print().
TagString()
StringRef llvm::dwarf::TagString (unsigned Tag)
Definition at line 21 of file Dwarf.cpp.
Referenced by llvm::DWARFTypePrinter::appendTypeTagName(), llvm::dwarf::AtomValueString(), llvm::DIEAbbrev::Emit(), llvm::AsmPrinter::emitDwarfDIE(), llvm::dwarf::getTag(), llvm::DIEAbbrev::print(), llvm::DIE::print(), llvm::DWARF5AccelTableData::print(), llvm::AppleAccelTableTypeData::print(), llvm::AppleAccelTableStaticTypeData::print(), printModuleDebugInfo(), and llvm::logicalview::LVScopeCompileUnit::printWarnings().
UnitTypeString()
StringRef llvm::dwarf::UnitTypeString (unsigned UT)
Definition at line 611 of file Dwarf.cpp.
Referenced by llvm::DWARFCompileUnit::dump(), and llvm::DWARFTypeUnit::dump().
VirtualityString()
StringRef llvm::dwarf::VirtualityString (unsigned Virtuality)
Definition at line 342 of file Dwarf.cpp.
Referenced by llvm::dwarf::AttributeValueString(), and llvm::dwarf::getVirtuality().
VisibilityString()
StringRef llvm::dwarf::VisibilityString (unsigned Visibility)
Definition at line 330 of file Dwarf.cpp.
References llvm::dwarf::DW_VIS_exported, llvm::dwarf::DW_VIS_local, and llvm::dwarf::DW_VIS_qualified.
Referenced by llvm::dwarf::AttributeValueString().