LLVM: of functions returning DIE info.
of functions returning DIE info.
Functions
DIEInfo & llvm::dwarf_linker::parallel::CompileUnit::getDIEInfo (unsigned Idx)
Idx index of the DIE.
const DIEInfo & llvm::dwarf_linker::parallel::CompileUnit::getDIEInfo (unsigned Idx) const
Idx index of the DIE.
DIEInfo & llvm::dwarf_linker::parallel::CompileUnit::getDIEInfo (const DWARFDebugInfoEntry *Entry)
Idx index of the DIE.
const DIEInfo & llvm::dwarf_linker::parallel::CompileUnit::getDIEInfo (const DWARFDebugInfoEntry *Entry) const
Idx index of the DIE.
DIEInfo & llvm::dwarf_linker::parallel::CompileUnit::getDIEInfo (const DWARFDie &Die)
Die
const DIEInfo & llvm::dwarf_linker::parallel::CompileUnit::getDIEInfo (const DWARFDie &Die) const
Die
uint64_t llvm::dwarf_linker::parallel::CompileUnit::getDieOutOffset (uint32_t Idx)
Idx index of the DIE.
TypeEntry * llvm::dwarf_linker::parallel::CompileUnit::getDieTypeEntry (uint32_t Idx)
Idx index of the DIE.
uint64_t llvm::dwarf_linker::parallel::CompileUnit::getDieOutOffset (const DWARFDebugInfoEntry *InputDieEntry)
InputDieEntry debug info entry.
TypeEntry * llvm::dwarf_linker::parallel::CompileUnit::getDieTypeEntry (const DWARFDebugInfoEntry *InputDieEntry)
InputDieEntry debug info entry.
void llvm::dwarf_linker::parallel::CompileUnit::rememberDieOutOffset (uint32_t Idx, uint64_t Offset)
Idx index of the DIE.
void llvm::dwarf_linker::parallel::CompileUnit::setDieTypeEntry (uint32_t Idx, TypeEntry *Entry)
Idx index of the DIE.
void llvm::dwarf_linker::parallel::CompileUnit::setDieTypeEntry (const DWARFDebugInfoEntry *InputDieEntry, TypeEntry *Entry)
InputDieEntry debug info entry.
Detailed Description
Function Documentation
getDIEInfo() [1/6]
DIEInfo & llvm::dwarf_linker::parallel::CompileUnit::getDIEInfo (const DWARFDebugInfoEntry * Entry) inline
Idx index of the DIE.
Returns
DieInfo descriptor.
Definition at line 291 of file DWARFLinkerCompileUnit.h.
References llvm::DWARFUnit::getDIEIndex(), and llvm::dwarf_linker::parallel::CompileUnit::getOrigUnit().
getDIEInfo() [2/6]
const DIEInfo & llvm::dwarf_linker::parallel::CompileUnit::getDIEInfo (const DWARFDebugInfoEntry * Entry) const inline
Idx index of the DIE.
Returns
DieInfo descriptor.
Definition at line 297 of file DWARFLinkerCompileUnit.h.
References llvm::DWARFUnit::getDIEIndex(), and llvm::dwarf_linker::parallel::CompileUnit::getOrigUnit().
getDIEInfo() [3/6]
DIEInfo & llvm::dwarf_linker::parallel::CompileUnit::getDIEInfo (const DWARFDie & Die) inline
Die
Returns
PlainDieInfo descriptor.
Definition at line 303 of file DWARFLinkerCompileUnit.h.
References llvm::DWARFUnit::getDIEIndex(), and llvm::dwarf_linker::parallel::CompileUnit::getOrigUnit().
getDIEInfo() [4/6]
const DIEInfo & llvm::dwarf_linker::parallel::CompileUnit::getDIEInfo (const DWARFDie & Die) const inline
Die
Returns
PlainDieInfo descriptor.
Definition at line 309 of file DWARFLinkerCompileUnit.h.
References llvm::DWARFUnit::getDIEIndex(), and llvm::dwarf_linker::parallel::CompileUnit::getOrigUnit().
getDIEInfo() [5/6]
DIEInfo & llvm::dwarf_linker::parallel::CompileUnit::getDIEInfo (unsigned Idx) inline
Idx index of the DIE.
Returns
DieInfo descriptor.
Definition at line 283 of file DWARFLinkerCompileUnit.h.
References Idx.
Referenced by llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::assignName(), llvm::dwarf_linker::parallel::CompileUnit::cloneDIE(), llvm::dwarf_linker::parallel::DIEAttributeCloner::shouldSkipAttribute(), and llvm::dwarf_linker::parallel::DependencyTracker::updateDependenciesCompleteness().
getDIEInfo() [6/6]
const DIEInfo & llvm::dwarf_linker::parallel::CompileUnit::getDIEInfo (unsigned Idx) const inline
Idx index of the DIE.
Returns
DieInfo descriptor.
Definition at line 287 of file DWARFLinkerCompileUnit.h.
References Idx.
getDieOutOffset() [1/2]
uint64_t llvm::dwarf_linker::parallel::CompileUnit::getDieOutOffset (const DWARFDebugInfoEntry * InputDieEntry) inline
InputDieEntry debug info entry.
Returns
DieInfo descriptor.
Definition at line 329 of file DWARFLinkerCompileUnit.h.
References llvm::DWARFUnit::getDIEIndex(), llvm::dwarf_linker::parallel::CompileUnit::getOrigUnit(), and load.
getDieOutOffset() [2/2]
uint64_t llvm::dwarf_linker::parallel::CompileUnit::getDieOutOffset (uint32_t Idx) inline
Idx index of the DIE.
Returns
DieInfo descriptor.
Definition at line 315 of file DWARFLinkerCompileUnit.h.
References Idx, and load.
Referenced by llvm::dwarf_linker::parallel::CompileUnit::updateDieRefPatchesWithClonedOffsets().
getDieTypeEntry() [1/2]
TypeEntry * llvm::dwarf_linker::parallel::CompileUnit::getDieTypeEntry (const DWARFDebugInfoEntry * InputDieEntry) inline
InputDieEntry debug info entry.
Returns
type entry.
Definition at line 337 of file DWARFLinkerCompileUnit.h.
References llvm::DWARFUnit::getDIEIndex(), llvm::dwarf_linker::parallel::CompileUnit::getOrigUnit(), and load.
getDieTypeEntry() [2/2]
TypeEntry * llvm::dwarf_linker::parallel::CompileUnit::getDieTypeEntry (uint32_t Idx) inline
Idx index of the DIE.
Returns
type entry.
Definition at line 322 of file DWARFLinkerCompileUnit.h.
References Idx, and load.
Referenced by llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addDIETypeName(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::assignName(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneDieRefAttr(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneScalarAttr(), and llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneStringAttr().
rememberDieOutOffset()
void llvm::dwarf_linker::parallel::CompileUnit::rememberDieOutOffset (uint32_t Idx, uint64_t Offset) inline
Idx index of the DIE.
Returns
DieInfo descriptor.
Definition at line 345 of file DWARFLinkerCompileUnit.h.
References Idx, and llvm::Offset.
setDieTypeEntry() [1/2]
void llvm::dwarf_linker::parallel::CompileUnit::setDieTypeEntry (const DWARFDebugInfoEntry * InputDieEntry, TypeEntry * Entry) inline
InputDieEntry debug info entry.
Type entry.
Definition at line 359 of file DWARFLinkerCompileUnit.h.
References llvm::DWARFUnit::getDIEIndex(), and llvm::dwarf_linker::parallel::CompileUnit::getOrigUnit().
setDieTypeEntry() [2/2]
void llvm::dwarf_linker::parallel::CompileUnit::setDieTypeEntry (uint32_t Idx, TypeEntry * Entry) inline
Idx index of the DIE.
Type entry.
Definition at line 352 of file DWARFLinkerCompileUnit.h.
References Idx.
Referenced by llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addDIETypeName().