LLVM: methods to access OrigUnit.
methods to access OrigUnit.
Functions
DWARFUnit & llvm::dwarf_linker::parallel::CompileUnit::getOrigUnit () const
Returns paired compile unit from input DWARF.
const DWARFDebugInfoEntry * llvm::dwarf_linker::parallel::CompileUnit::getFirstChildEntry (const DWARFDebugInfoEntry *Die) const
const DWARFDebugInfoEntry * llvm::dwarf_linker::parallel::CompileUnit::getSiblingEntry (const DWARFDebugInfoEntry *Die) const
DWARFDie llvm::dwarf_linker::parallel::CompileUnit::getParent (const DWARFDebugInfoEntry *Die)
DWARFDie llvm::dwarf_linker::parallel::CompileUnit::getDIEAtIndex (unsigned Index)
const DWARFDebugInfoEntry * llvm::dwarf_linker::parallel::CompileUnit::getDebugInfoEntry (unsigned Index) const
DWARFDie llvm::dwarf_linker::parallel::CompileUnit::getUnitDIE (bool ExtractUnitDIEOnly=true)
DWARFDie llvm::dwarf_linker::parallel::CompileUnit::getDIE (const DWARFDebugInfoEntry *Die)
uint32_t llvm::dwarf_linker::parallel::CompileUnit::getDIEIndex (const DWARFDebugInfoEntry *Die) const
uint32_t llvm::dwarf_linker::parallel::CompileUnit::getDIEIndex (const DWARFDie &Die) const
std::optional< DWARFFormValue > llvm::dwarf_linker::parallel::CompileUnit::find (uint32_t DieIdx, ArrayRef< dwarf::Attribute > Attrs) const
std::optional< DWARFFormValue > llvm::dwarf_linker::parallel::CompileUnit::find (const DWARFDebugInfoEntry *Die, ArrayRef< dwarf::Attribute > Attrs) const
std::optional< uint32_t > llvm::dwarf_linker::parallel::CompileUnit::getDIEIndexForOffset (uint64_t Offset)
Detailed Description
Function Documentation
find() [1/2]
std::optional< DWARFFormValue > llvm::dwarf_linker::parallel::CompileUnit::find (const DWARFDebugInfoEntry * Die, ArrayRef< dwarf::Attribute > Attrs) const inline
Definition at line 511 of file DWARFLinkerCompileUnit.h.
References llvm::DWARFDebugInfoEntry::getAbbreviationDeclarationPtr(), and llvm::DWARFDebugInfoEntry::getOffset().
find() [2/2]
std::optional< DWARFFormValue > llvm::dwarf_linker::parallel::CompileUnit::find (uint32_t DieIdx, ArrayRef< dwarf::Attribute > Attrs) const inline
Definition at line 505 of file DWARFLinkerCompileUnit.h.
References assert(), llvm::dwarf_linker::parallel::CompileUnit::find(), and llvm::DWARFUnit::getDebugInfoEntry().
Referenced by llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addArrayDimension(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addDieNameFromDeclFileAndDeclLine(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addReferencedODRDies(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addTypeName(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addValueName(), llvm::dwarf_linker::parallel::CompileUnit::analyzeImportedModule(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneAddressAttr(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitLineTable(), llvm::dwarf_linker::parallel::CompileUnit::find(), getTypeDeduplicationCandidate(), and llvm::dwarf_linker::parallel::CompileUnit::resolveDIEReference().
getDebugInfoEntry()
const DWARFDebugInfoEntry * llvm::dwarf_linker::parallel::CompileUnit::getDebugInfoEntry (unsigned Index) const inline
Definition at line 480 of file DWARFLinkerCompileUnit.h.
References assert(), and llvm::DWARFUnit::getDebugInfoEntry().
Referenced by llvm::dwarf_linker::parallel::CompileUnit::analyzeDWARFStructure(), llvm::dwarf_linker::parallel::CompileUnit::assignTypeNames(), and llvm::dwarf_linker::parallel::CompileUnit::resolveDIEReference().
getDIE()
DWARFDie llvm::dwarf_linker::parallel::CompileUnit::getDIE (const DWARFDebugInfoEntry * Die) inline
Definition at line 490 of file DWARFLinkerCompileUnit.h.
References assert().
Referenced by llvm::dwarf_linker::parallel::CompileUnit::analyzeImportedModule(), and llvm::dwarf_linker::parallel::AcceleratorRecordsSaver::save().
getDIEAtIndex()
DWARFDie llvm::dwarf_linker::parallel::CompileUnit::getDIEAtIndex (unsigned Index) inline
Definition at line 475 of file DWARFLinkerCompileUnit.h.
References assert(), and llvm::DWARFUnit::getDIEAtIndex().
Referenced by llvm::dwarf_linker::parallel::DIEAttributeCloner::clone().
getDIEIndex() [1/2]
uint32_t llvm::dwarf_linker::parallel::CompileUnit::getDIEIndex (const DWARFDebugInfoEntry * Die) const inline
Definition at line 495 of file DWARFLinkerCompileUnit.h.
References assert(), and llvm::DWARFUnit::getDIEIndex().
Referenced by llvm::dwarf_linker::parallel::CompileUnit::cloneDIE(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneDieRefAttr(), and llvm::dwarf_linker::parallel::DIEAttributeCloner::DIEAttributeCloner().
getDIEIndex() [2/2]
uint32_t llvm::dwarf_linker::parallel::CompileUnit::getDIEIndex (const DWARFDie & Die) const inline
Definition at line 500 of file DWARFLinkerCompileUnit.h.
References assert(), and llvm::DWARFUnit::getDIEIndex().
getDIEIndexForOffset()
std::optional< uint32_t > llvm::dwarf_linker::parallel::CompileUnit::getDIEIndexForOffset (uint64_t Offset) inline
Definition at line 526 of file DWARFLinkerCompileUnit.h.
References llvm::DWARFUnit::getDIEIndexForOffset(), and llvm::Offset.
Referenced by llvm::dwarf_linker::parallel::CompileUnit::resolveDIEReference().
getFirstChildEntry()
const DWARFDebugInfoEntry * llvm::dwarf_linker::parallel::CompileUnit::getFirstChildEntry (const DWARFDebugInfoEntry * Die) const inline
Definition at line 459 of file DWARFLinkerCompileUnit.h.
References assert(), and llvm::DWARFUnit::getFirstChildEntry().
Referenced by llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addArrayDimension(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addSignature(), and llvm::dwarf_linker::parallel::CompileUnit::cloneDIE().
getOrigUnit()
DWARFUnit & llvm::dwarf_linker::parallel::CompileUnit::getOrigUnit () const inline
Returns paired compile unit from input DWARF.
Definition at line 453 of file DWARFLinkerCompileUnit.h.
References assert().
Referenced by llvm::dwarf_linker::parallel::CompileUnit::cleanupDataAfterClonning(), llvm::dwarf_linker::parallel::DIEAttributeCloner::clone(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmit(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitDebugLocations(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitDebugMacro(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitLineTable(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitRanges(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneBlockAttr(), llvm::dwarf_linker::parallel::CompileUnit::cloneDieAttrExpression(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneScalarAttr(), llvm::dwarf_linker::parallel::CompileUnit::getDIEInfo(), llvm::dwarf_linker::parallel::CompileUnit::getDieOutOffset(), llvm::dwarf_linker::parallel::CompileUnit::getDieTypeEntry(), llvm::dwarf_linker::parallel::CompileUnit::getDirAndFilenameFromLineTable(), llvm::dwarf_linker::parallel::CompileUnit::getFileName(), llvm::dwarf_linker::parallel::CompileUnit::loadInputDIEs(), llvm::dwarf_linker::parallel::CompileUnit::loadLineTable(), llvm::dwarf_linker::parallel::CompileUnit::setDieTypeEntry(), and llvm::dwarf_linker::parallel::CompileUnit::warn().
getParent()
DWARFDie llvm::dwarf_linker::parallel::CompileUnit::getParent (const DWARFDebugInfoEntry * Die) inline
Definition at line 470 of file DWARFLinkerCompileUnit.h.
References assert(), and llvm::DWARFUnit::getParent().
getSiblingEntry()
const DWARFDebugInfoEntry * llvm::dwarf_linker::parallel::CompileUnit::getSiblingEntry (const DWARFDebugInfoEntry * Die) const inline
Definition at line 465 of file DWARFLinkerCompileUnit.h.
References assert(), and llvm::DWARFUnit::getSiblingEntry().
Referenced by llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addArrayDimension(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addSignature(), and llvm::dwarf_linker::parallel::CompileUnit::cloneDIE().
getUnitDIE()
DWARFDie llvm::dwarf_linker::parallel::CompileUnit::getUnitDIE (bool ExtractUnitDIEOnly = true) inline
Definition at line 485 of file DWARFLinkerCompileUnit.h.
References assert(), and llvm::DWARFUnit::getUnitDIE().
Referenced by llvm::dwarf_linker::parallel::CompileUnit::analyzeDWARFStructure(), llvm::dwarf_linker::parallel::CompileUnit::analyzeImportedModule(), llvm::dwarf_linker::parallel::CompileUnit::assignTypeNames(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitLineTable(), and llvm::dwarf_linker::parallel::CompileUnit::loadInputDIEs().