LLVM: used to link the debug information
used to link the debug information
Emit unit's abbreviations.
Classes
struct llvm::dwarf_linker::parallel::DwarfUnit::AccelInfo
This structure keeps fields which would be used for creating accelerator table.
Enumerations
enum class llvm::dwarf_linker::parallel::DwarfUnit::AccelType : uint8_t {
llvm::dwarf_linker::parallel::DwarfUnit::AccelType::None , llvm::dwarf_linker::parallel::DwarfUnit::AccelType::Name , llvm::dwarf_linker::parallel::DwarfUnit::AccelType::Namespace , llvm::dwarf_linker::parallel::DwarfUnit::AccelType::ObjC ,
llvm::dwarf_linker::parallel::DwarfUnit::AccelType::Type
}
Functions
void * llvm::parallel::PerThreadAllocator< AllocatorTy >::Allocate (size_t Size, size_t Alignment)
Allocate Size bytes of Alignment aligned memory.
void llvm::parallel::PerThreadAllocator< AllocatorTy >::Deallocate (const void *Ptr, size_t Size, size_t Alignment)
Deallocate Ptr to Size bytes of memory allocated by this allocator.
AllocatorTy & llvm::parallel::PerThreadAllocator< AllocatorTy >::getThreadLocalAllocator ()
Return allocator corresponding to the current thread.
size_t llvm::parallel::PerThreadAllocator< AllocatorTy >::getNumberOfAllocators () const
void llvm::parallel::PerThreadAllocator< AllocatorTy >::Reset ()
Reset state of allocators.
size_t llvm::parallel::PerThreadAllocator< AllocatorTy >::getTotalMemory () const
Return total memory size used by all allocators.
size_t llvm::parallel::PerThreadAllocator< AllocatorTy >::getBytesAllocated () const
Return allocated size by all allocators.
void llvm::parallel::PerThreadAllocator< AllocatorTy >::setRedZoneSize (size_t NewSize)
Set red zone for all allocators.
void llvm::parallel::PerThreadAllocator< AllocatorTy >::PrintStats () const
Print statistic for each allocator.
void llvm::dwarf_linker::parallel::CompileUnit::warn (const Twine &Warning, const DWARFDie *DIE=nullptr)
void llvm::dwarf_linker::parallel::CompileUnit::warn (Error Warning, const DWARFDie *DIE=nullptr)
void llvm::dwarf_linker::parallel::CompileUnit::warn (const Twine &Warning, const DWARFDebugInfoEntry *DieEntry)
void llvm::dwarf_linker::parallel::CompileUnit::error (const Twine &Err, const DWARFDie *DIE=nullptr)
void llvm::dwarf_linker::parallel::CompileUnit::error (Error Err, const DWARFDie *DIE=nullptr)
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setVerbosity (bool Verbose) override
Allows to generate log of linking process to the standard output.
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setStatistics (bool Statistics) override
Print statistics to standard output.
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setVerifyInputDWARF (bool Verify) override
Verify the input DWARF.
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setNoODR (bool NoODR) override
Do not unique types according to ODR.
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setUpdateIndexTablesOnly (bool UpdateIndexTablesOnly) override
Update index tables only(do not modify rest of DWARF).
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setAllowNonDeterministicOutput (bool AllowNonDeterministicOutput) override
Allow generating valid, but non-deterministic output.
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setKeepFunctionForStatic (bool KeepFunctionForStatic) override
Set to keep the enclosing function for a static variable.
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setNumThreads (unsigned NumThreads) override
Use specified number of threads for parallel files linking.
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::addAccelTableKind (AccelTableKind Kind) override
Add kind of accelerator tables to be generated.
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setPrependPath (StringRef Ppath) override
Set prepend path for clang modules.
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setEstimatedObjfilesAmount (unsigned ObjFilesNum) override
Set estimated objects files amount, for preliminary data allocation.
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setInputVerificationHandler (InputVerificationHandlerTy Handler) override
Set verification handler which would be used to report verification errors.
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setSwiftInterfacesMap (SwiftInterfacesMapTy *Map) override
Set map for Swift interfaces.
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setObjectPrefixMap (ObjectPrefixMapTy *Map) override
Set prefix map for objects.
Error llvm::dwarf_linker::parallel::DWARFLinkerImpl::setTargetDWARFVersion (uint16_t TargetDWARFVersion) override
Set target DWARF version.
Error llvm::dwarf_linker::parallel::DwarfUnit::emitAbbreviations ()
Error llvm::dwarf_linker::parallel::DwarfUnit::emitDebugInfo (const Triple &TargetTriple)
Emit .debug_info section for unit DIEs.
Error llvm::dwarf_linker::parallel::DwarfUnit::emitDebugLine (const Triple &TargetTriple, const DWARFDebugLine::LineTable &OutLineTable)
Emit .debug_line section.
Error llvm::dwarf_linker::parallel::DwarfUnit::emitDebugStringOffsetSection ()
Emit the .debug_str_offsets section for current unit.
void llvm::dwarf_linker::parallel::DwarfUnit::warn (const Twine &Warning)
void llvm::dwarf_linker::parallel::DwarfUnit::error (const Twine &Err)
void llvm::dwarf_linker::parallel::DwarfUnit::emitPubAccelerators ()
Emit .debug_pubnames and .debug_pubtypes for Unit.
virtual void llvm::dwarf_linker::parallel::DwarfUnit::forEachAcceleratorRecord (function_ref< void(AccelInfo &)> Handler)=0
Enumerates accelerator data.
Detailed Description
Emit unit's abbreviations.
Enumeration Type Documentation
AccelType
enum class llvm::dwarf_linker::parallel::DwarfUnit::AccelType : uint8_t strong
Enumerator
None
Name
Namespace
ObjC
Type
Definition at line 113 of file DWARFLinkerUnit.h.
Function Documentation
addAccelTableKind()
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::addAccelTableKind (AccelTableKind Kind) inline override virtual
Add kind of accelerator tables to be generated.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 100 of file DWARFLinkerImpl.h.
References llvm::dwarf_linker::parallel::DWARFLinkerOptions::AccelTables, assert(), llvm::SmallVectorImpl< T >::emplace_back(), llvm::dwarf_linker::parallel::LinkingGlobalData::getOptions(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, llvm::is_contained(), and llvm::dwarf_linker::parallel::LinkingGlobalData::Options.
Allocate()
template<typename AllocatorTy > void * llvm::parallel::PerThreadAllocator< AllocatorTy >::Allocate (size_t Size, size_t Alignment) inline
Allocate Size bytes of Alignment aligned memory.
Definition at line 43 of file PerThreadBumpPtrAllocator.h.
References llvm::parallel::PerThreadAllocator< AllocatorTy >::Allocators, assert(), llvm::parallel::getThreadIndex(), llvm::parallel::PerThreadAllocator< AllocatorTy >::NumOfAllocators, and Size.
Deallocate()
template<typename AllocatorTy > void llvm::parallel::PerThreadAllocator< AllocatorTy >::Deallocate (const void * Ptr, size_t Size, size_t Alignment) inline
Deallocate Ptr to Size bytes of memory allocated by this allocator.
Definition at line 50 of file PerThreadBumpPtrAllocator.h.
References llvm::parallel::PerThreadAllocator< AllocatorTy >::Allocators, assert(), llvm::parallel::getThreadIndex(), llvm::parallel::PerThreadAllocator< AllocatorTy >::NumOfAllocators, Ptr, and Size.
emitAbbreviations()
Error DwarfUnit::emitAbbreviations ()
Definition at line 41 of file DWARFLinkerUnit.cpp.
References llvm::encodeULEB128(), llvm::dwarf_linker::parallel::SectionDescriptor::OS, and llvm::Error::success().
Referenced by llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmit(), and llvm::dwarf_linker::parallel::TypeUnit::finishCloningAndEmit().
emitDebugInfo()
Error DwarfUnit::emitDebugInfo (const Triple & TargetTriple)
Emit .debug_info section for unit DIEs.
Definition at line 92 of file DWARFLinkerUnit.cpp.
References Emitter, llvm::dwarf_linker::parallel::SectionDescriptor::OS, llvm::dwarf_linker::parallel::SectionDescriptor::setSizesForSectionCreatedByAsmPrinter(), and llvm::Error::success().
Referenced by llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmit(), and llvm::dwarf_linker::parallel::TypeUnit::finishCloningAndEmit().
emitDebugLine()
Error DwarfUnit::emitDebugLine (const Triple & TargetTriple, const DWARFDebugLine::LineTable & OutLineTable)
Emit .debug_line section.
Definition at line 123 of file DWARFLinkerUnit.cpp.
References llvm::dwarf_linker::parallel::DebugLineSectionEmitter::emit().
Referenced by llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitLineTable(), and llvm::dwarf_linker::parallel::TypeUnit::finishCloningAndEmit().
emitDebugStringOffsetSection()
Error DwarfUnit::emitDebugStringOffsetSection ()
Emit the .debug_str_offsets section for current unit.
Definition at line 130 of file DWARFLinkerUnit.cpp.
References llvm::dwarf_linker::parallel::SectionDescriptor::apply(), llvm::dwarf_linker::parallel::SectionDescriptor::emitIntVal(), llvm::dwarf_linker::parallel::SectionDescriptor::emitOffset(), llvm::dwarf_linker::parallel::SectionDescriptor::emitUnitLength(), llvm::dwarf::FormParams::getDwarfOffsetByteSize(), llvm::dwarf_linker::parallel::SectionDescriptorBase::getFormParams(), llvm::dwarf_linker::parallel::SectionDescriptor::OS, llvm::String, llvm::Error::success(), and llvm::raw_ostream::tell().
Referenced by llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmit(), and llvm::dwarf_linker::parallel::TypeUnit::finishCloningAndEmit().
emitPubAccelerators()
void DwarfUnit::emitPubAccelerators ()
Emit .debug_pubnames and .debug_pubtypes for Unit.
Definition at line 202 of file DWARFLinkerUnit.cpp.
References Info.
Referenced by llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmit(), and llvm::dwarf_linker::parallel::TypeUnit::finishCloningAndEmit().
error() [1/3]
void llvm::dwarf_linker::parallel::DwarfUnit::error (const Twine & Err) inline
Definition at line 106 of file DWARFLinkerUnit.h.
References llvm::dwarf_linker::parallel::DwarfUnit::getUnitName(), llvm::dwarf_linker::parallel::OutputSections::GlobalData, and llvm::dwarf_linker::parallel::LinkingGlobalData::warn().
error() [2/3]
void llvm::dwarf_linker::parallel::CompileUnit::error (const Twine & Err, const DWARFDie * DIE = nullptr) inline
Definition at line 556 of file DWARFLinkerCompileUnit.h.
References llvm::dwarf_linker::parallel::DwarfUnit::getUnitName(), llvm::dwarf_linker::parallel::OutputSections::GlobalData, and llvm::dwarf_linker::parallel::LinkingGlobalData::warn().
error() [3/3]
void llvm::dwarf_linker::parallel::CompileUnit::error (Error Err, const DWARFDie * DIE = nullptr) inline
Definition at line 560 of file DWARFLinkerCompileUnit.h.
References llvm::dwarf_linker::parallel::LinkingGlobalData::error(), llvm::dwarf_linker::parallel::DwarfUnit::getUnitName(), llvm::dwarf_linker::parallel::OutputSections::GlobalData, llvm::handleAllErrors(), and Info.
forEachAcceleratorRecord()
virtual void llvm::dwarf_linker::parallel::DwarfUnit::forEachAcceleratorRecord (function_ref< void(AccelInfo &)> Handler) pure virtual
Enumerates accelerator data.
Implemented in llvm::dwarf_linker::parallel::CompileUnit, and llvm::dwarf_linker::parallel::TypeUnit.
getBytesAllocated()
template<typename AllocatorTy > size_t llvm::parallel::PerThreadAllocator< AllocatorTy >::getBytesAllocated () const inline
Return allocated size by all allocators.
Definition at line 86 of file PerThreadBumpPtrAllocator.h.
References llvm::parallel::PerThreadAllocator< AllocatorTy >::Allocators, llvm::parallel::PerThreadAllocator< AllocatorTy >::getBytesAllocated(), llvm::parallel::PerThreadAllocator< AllocatorTy >::getNumberOfAllocators(), and Idx.
Referenced by llvm::parallel::PerThreadAllocator< AllocatorTy >::getBytesAllocated().
getNumberOfAllocators()
template<typename AllocatorTy > size_t llvm::parallel::PerThreadAllocator< AllocatorTy >::getNumberOfAllocators () const inline
Definition at line 62 of file PerThreadBumpPtrAllocator.h.
References llvm::parallel::PerThreadAllocator< AllocatorTy >::NumOfAllocators.
Referenced by llvm::parallel::PerThreadAllocator< AllocatorTy >::getBytesAllocated(), llvm::parallel::PerThreadAllocator< AllocatorTy >::getTotalMemory(), llvm::parallel::PerThreadAllocator< AllocatorTy >::PrintStats(), llvm::parallel::PerThreadAllocator< AllocatorTy >::Reset(), and llvm::parallel::PerThreadAllocator< AllocatorTy >::setRedZoneSize().
getThreadLocalAllocator()
template<typename AllocatorTy > AllocatorTy & llvm::parallel::PerThreadAllocator< AllocatorTy >::getThreadLocalAllocator () inline
Return allocator corresponding to the current thread.
Definition at line 56 of file PerThreadBumpPtrAllocator.h.
References llvm::parallel::PerThreadAllocator< AllocatorTy >::Allocators, assert(), llvm::parallel::getThreadIndex(), and llvm::parallel::PerThreadAllocator< AllocatorTy >::NumOfAllocators.
getTotalMemory()
template<typename AllocatorTy > size_t llvm::parallel::PerThreadAllocator< AllocatorTy >::getTotalMemory () const inline
Return total memory size used by all allocators.
Definition at line 76 of file PerThreadBumpPtrAllocator.h.
References llvm::parallel::PerThreadAllocator< AllocatorTy >::Allocators, llvm::parallel::PerThreadAllocator< AllocatorTy >::getNumberOfAllocators(), llvm::parallel::PerThreadAllocator< AllocatorTy >::getTotalMemory(), and Idx.
Referenced by llvm::parallel::PerThreadAllocator< AllocatorTy >::getTotalMemory().
PrintStats()
template<typename AllocatorTy > void llvm::parallel::PerThreadAllocator< AllocatorTy >::PrintStats () const inline
Print statistic for each allocator.
Definition at line 102 of file PerThreadBumpPtrAllocator.h.
References llvm::parallel::PerThreadAllocator< AllocatorTy >::Allocators, llvm::errs(), llvm::parallel::PerThreadAllocator< AllocatorTy >::getNumberOfAllocators(), and Idx.
Reset()
template<typename AllocatorTy > void llvm::parallel::PerThreadAllocator< AllocatorTy >::Reset () inline
Reset state of allocators.
Definition at line 70 of file PerThreadBumpPtrAllocator.h.
References llvm::parallel::PerThreadAllocator< AllocatorTy >::Allocators, llvm::parallel::PerThreadAllocator< AllocatorTy >::getNumberOfAllocators(), Idx, and llvm::parallel::PerThreadAllocator< AllocatorTy >::Reset().
Referenced by llvm::parallel::PerThreadAllocator< AllocatorTy >::Reset().
setAllowNonDeterministicOutput()
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setAllowNonDeterministicOutput (bool AllowNonDeterministicOutput) inline override virtual
Allow generating valid, but non-deterministic output.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 84 of file DWARFLinkerImpl.h.
References llvm::dwarf_linker::parallel::DWARFLinkerOptions::AllowNonDeterministicOutput, llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, and llvm::dwarf_linker::parallel::LinkingGlobalData::Options.
setEstimatedObjfilesAmount()
void DWARFLinkerImpl::setEstimatedObjfilesAmount (unsigned ObjFilesNum) override virtual
Set estimated objects files amount, for preliminary data allocation.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 88 of file DWARFLinkerImpl.cpp.
References llvm::dwarf_linker::parallel::DWARFLinkerImpl::ObjectContexts.
setInputVerificationHandler()
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setInputVerificationHandler (InputVerificationHandlerTy Handler) inline override virtual
Set verification handler which would be used to report verification errors.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 116 of file DWARFLinkerImpl.h.
References llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, llvm::dwarf_linker::parallel::DWARFLinkerOptions::InputVerificationHandler, and llvm::dwarf_linker::parallel::LinkingGlobalData::Options.
setKeepFunctionForStatic()
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setKeepFunctionForStatic (bool KeepFunctionForStatic) inline override virtual
Set to keep the enclosing function for a static variable.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 90 of file DWARFLinkerImpl.h.
References llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, llvm::dwarf_linker::parallel::DWARFLinkerOptions::KeepFunctionForStatic, and llvm::dwarf_linker::parallel::LinkingGlobalData::Options.
setNoODR()
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setNoODR (bool NoODR) inline override virtual
Do not unique types according to ODR.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 75 of file DWARFLinkerImpl.h.
References llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, llvm::dwarf_linker::parallel::DWARFLinkerOptions::NoODR, and llvm::dwarf_linker::parallel::LinkingGlobalData::Options.
setNumThreads()
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setNumThreads (unsigned NumThreads) inline override virtual
Use specified number of threads for parallel files linking.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 95 of file DWARFLinkerImpl.h.
References llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, llvm::dwarf_linker::parallel::LinkingGlobalData::Options, and llvm::dwarf_linker::parallel::DWARFLinkerOptions::Threads.
setObjectPrefixMap()
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setObjectPrefixMap (ObjectPrefixMapTy * Map) inline override virtual
Set prefix map for objects.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 126 of file DWARFLinkerImpl.h.
References llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, llvm::dwarf_linker::parallel::DWARFLinkerOptions::ObjectPrefixMap, and llvm::dwarf_linker::parallel::LinkingGlobalData::Options.
setPrependPath()
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setPrependPath (StringRef Ppath) inline override virtual
Set prepend path for clang modules.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 106 of file DWARFLinkerImpl.h.
References llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, llvm::dwarf_linker::parallel::LinkingGlobalData::Options, and llvm::dwarf_linker::parallel::DWARFLinkerOptions::PrependPath.
setRedZoneSize()
template<typename AllocatorTy > void llvm::parallel::PerThreadAllocator< AllocatorTy >::setRedZoneSize (size_t NewSize) inline
Set red zone for all allocators.
Definition at line 96 of file PerThreadBumpPtrAllocator.h.
References llvm::parallel::PerThreadAllocator< AllocatorTy >::Allocators, llvm::parallel::PerThreadAllocator< AllocatorTy >::getNumberOfAllocators(), Idx, and llvm::parallel::PerThreadAllocator< AllocatorTy >::setRedZoneSize().
Referenced by llvm::parallel::PerThreadAllocator< AllocatorTy >::setRedZoneSize().
setStatistics()
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setStatistics (bool Statistics) inline override virtual
Print statistics to standard output.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 65 of file DWARFLinkerImpl.h.
References llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, llvm::dwarf_linker::parallel::LinkingGlobalData::Options, and llvm::dwarf_linker::parallel::DWARFLinkerOptions::Statistics.
setSwiftInterfacesMap()
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setSwiftInterfacesMap (SwiftInterfacesMapTy * Map) inline override virtual
Set map for Swift interfaces.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 121 of file DWARFLinkerImpl.h.
References llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, llvm::dwarf_linker::parallel::LinkingGlobalData::Options, and llvm::dwarf_linker::parallel::DWARFLinkerOptions::ParseableSwiftInterfaces.
setTargetDWARFVersion()
Error llvm::dwarf_linker::parallel::DWARFLinkerImpl::setTargetDWARFVersion (uint16_t TargetDWARFVersion) inline override virtual
Set target DWARF version.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 131 of file DWARFLinkerImpl.h.
References llvm::createStringError(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, llvm::dwarf_linker::parallel::LinkingGlobalData::Options, llvm::Error::success(), and llvm::dwarf_linker::parallel::DWARFLinkerOptions::TargetDWARFVersion.
setUpdateIndexTablesOnly()
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setUpdateIndexTablesOnly (bool UpdateIndexTablesOnly) inline override virtual
Update index tables only(do not modify rest of DWARF).
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 78 of file DWARFLinkerImpl.h.
References llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, llvm::dwarf_linker::parallel::LinkingGlobalData::Options, and llvm::dwarf_linker::parallel::DWARFLinkerOptions::UpdateIndexTablesOnly.
setVerbosity()
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setVerbosity (bool Verbose) inline override virtual
Allows to generate log of linking process to the standard output.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 60 of file DWARFLinkerImpl.h.
References llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, llvm::dwarf_linker::parallel::LinkingGlobalData::Options, llvm::Verbose, and llvm::dwarf_linker::parallel::DWARFLinkerOptions::Verbose.
setVerifyInputDWARF()
void llvm::dwarf_linker::parallel::DWARFLinkerImpl::setVerifyInputDWARF (bool Verify) inline override virtual
Verify the input DWARF.
Implements llvm::dwarf_linker::DWARFLinkerBase.
Definition at line 70 of file DWARFLinkerImpl.h.
References llvm::dwarf_linker::parallel::DWARFLinkerImpl::GlobalData, llvm::dwarf_linker::parallel::LinkingGlobalData::Options, Verify, and llvm::dwarf_linker::parallel::DWARFLinkerOptions::VerifyInputDWARF.
warn() [1/4]
void llvm::dwarf_linker::parallel::DwarfUnit::warn (const Twine & Warning) inline
Definition at line 104 of file DWARFLinkerUnit.h.
References llvm::dwarf_linker::parallel::DwarfUnit::getUnitName(), llvm::dwarf_linker::parallel::OutputSections::GlobalData, llvm::dwarf_linker::parallel::LinkingGlobalData::warn(), and llvm::Warning.
warn() [2/4]
void llvm::dwarf_linker::parallel::CompileUnit::warn (const Twine & Warning, const DWARFDebugInfoEntry * DieEntry) inline
Definition at line 546 of file DWARFLinkerCompileUnit.h.
References llvm::dwarf_linker::parallel::CompileUnit::getOrigUnit(), llvm::dwarf_linker::parallel::DwarfUnit::getUnitName(), llvm::dwarf_linker::parallel::OutputSections::GlobalData, llvm::dwarf_linker::parallel::LinkingGlobalData::warn(), and llvm::Warning.
warn() [3/4]
void llvm::dwarf_linker::parallel::CompileUnit::warn (const Twine & Warning, const DWARFDie * DIE = nullptr) inline
Definition at line 536 of file DWARFLinkerCompileUnit.h.
References llvm::dwarf_linker::parallel::DwarfUnit::getUnitName(), llvm::dwarf_linker::parallel::OutputSections::GlobalData, llvm::dwarf_linker::parallel::LinkingGlobalData::warn(), and llvm::Warning.
Referenced by llvm::dwarf_linker::parallel::CompileUnit::analyzeImportedModule(), llvm::dwarf_linker::parallel::DIEAttributeCloner::clone(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneAddressAttr(), llvm::dwarf_linker::parallel::CompileUnit::cloneAndEmitLineTable(), llvm::dwarf_linker::parallel::CompileUnit::cloneDieAttrExpression(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneDieRefAttr(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneScalarAttr(), llvm::dwarf_linker::parallel::DIEAttributeCloner::cloneStringAttr(), and llvm::dwarf_linker::parallel::CompileUnit::getDirAndFilenameFromLineTable().
warn() [4/4]
void llvm::dwarf_linker::parallel::CompileUnit::warn (Error Warning, const DWARFDie * DIE = nullptr) inline
Definition at line 540 of file DWARFLinkerCompileUnit.h.
References llvm::dwarf_linker::parallel::DwarfUnit::getUnitName(), llvm::dwarf_linker::parallel::OutputSections::GlobalData, llvm::handleAllErrors(), Info, llvm::dwarf_linker::parallel::LinkingGlobalData::warn(), and llvm::Warning.