LLVM: lib/ProfileData/ItaniumManglingCanonicalizer.cpp File Reference
ItaniumManglingCanonicalizer.cpp File Reference
#include "llvm/ProfileData/ItaniumManglingCanonicalizer.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Demangle/ItaniumDemangle.h"
#include "llvm/Support/Allocator.h"
Classes
struct llvm::ItaniumManglingCanonicalizer::Impl
Functions
static ItaniumManglingCanonicalizer::Key parseMaybeMangledName (CanonicalizingDemangler &Demangler, StringRef Mangling, bool CreateNewNodes)
Function Documentation
parseMaybeMangledName()
static ItaniumManglingCanonicalizer::Key parseMaybeMangledName (CanonicalizingDemangler & Demangler, StringRef Mangling, bool CreateNewNodes) static
Definition at line 282 of file ItaniumManglingCanonicalizer.cpp.
References llvm::StringRef::begin(), llvm::StringRef::data(), llvm::StringRef::end(), N, llvm::StringRef::size(), and llvm::StringRef::starts_with().
Referenced by llvm::ItaniumManglingCanonicalizer::canonicalize(), and llvm::ItaniumManglingCanonicalizer::lookup().