LLVM: lib/Support/KnownBits.cpp File Reference
KnownBits.cpp File Reference
#include "llvm/Support/KnownBits.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
Functions
static KnownBits computeForAddCarry (const KnownBits &LHS, const KnownBits &RHS, bool CarryZero, bool CarryOne)
static unsigned getMaxShiftAmount (const APInt &MaxValue, unsigned BitWidth)
static KnownBits computeForSatAddSub (bool Add, bool Signed, const KnownBits &LHS, const KnownBits &RHS)
static KnownBits divComputeLowBit (KnownBits Known, const KnownBits &LHS, const KnownBits &RHS, bool Exact)
Function Documentation
computeForAddCarry()
static KnownBits computeForAddCarry (const KnownBits & LHS, const KnownBits & RHS, bool CarryZero, bool CarryOne) static
Definition at line 21 of file KnownBits.cpp.
References assert(), LHS, llvm::move(), llvm::KnownBits::One, RHS, and llvm::KnownBits::Zero.
computeForSatAddSub()
static KnownBits computeForSatAddSub (bool Add, bool Signed, const KnownBits & LHS, const KnownBits & RHS) static
Definition at line 486 of file KnownBits.cpp.
References llvm::Add, assert(), llvm::BitWidth, llvm::CallingConv::C, llvm::APInt::clearAllBits(), llvm::APInt::clearLowBits(), llvm::APInt::clearSignBit(), llvm::KnownBits::computeForAddSub(), llvm::KnownBits::getBitWidth(), llvm::APInt::getHighBitsSet(), llvm::APInt::getMaxValue(), llvm::APInt::getMinValue(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::KnownBits::hasConflict(), llvm::KnownBits::isNonNegative(), LHS, llvm::KnownBits::One, RHS, llvm::APInt::setSignBit(), Signed, and llvm::KnownBits::Zero.
Referenced by llvm::KnownBits::sadd_sat(), llvm::KnownBits::ssub_sat(), llvm::KnownBits::uadd_sat(), and llvm::KnownBits::usub_sat().
divComputeLowBit()
static KnownBits divComputeLowBit (KnownBits Known, const KnownBits & LHS, const KnownBits & RHS, bool Exact) static
Definition at line 763 of file KnownBits.cpp.
References llvm::KnownBits::hasConflict(), LHS, llvm::KnownBits::One, RHS, llvm::KnownBits::setAllZero(), llvm::APInt::setBit(), llvm::APInt::setLowBits(), and llvm::KnownBits::Zero.
Referenced by llvm::KnownBits::sdiv(), and llvm::KnownBits::udiv().
getMaxShiftAmount()
static unsigned getMaxShiftAmount (const APInt & MaxValue, unsigned BitWidth) static
Definition at line 179 of file KnownBits.cpp.
References llvm::BitWidth, llvm::APInt::extractBitsAsZExtValue(), llvm::APInt::getLimitedValue(), llvm::isPowerOf2_32(), and llvm::Log2_32().
Referenced by llvm::KnownBits::ashr(), llvm::KnownBits::lshr(), and llvm::KnownBits::shl().