LLVM: lib/Target/LoongArch/MCTargetDesc/LoongArchAsmBackend.cpp File Reference
LoongArchAsmBackend.cpp File Reference
#include "LoongArchAsmBackend.h"
#include "LoongArchFixupKinds.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/EndianStream.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/BinaryFormat/ELFRelocs/LoongArch.def"
Macros
#define DEBUG_TYPE "loongarch-asmbackend"
#define ELF_RELOC(X, Y) .Case(#X, Y)
Functions
static void reportOutOfRangeError (MCContext &Ctx, SMLoc Loc, unsigned N)
static uint64_t adjustFixupValue (const MCFixup &Fixup, uint64_t Value, MCContext &Ctx)
static void fixupLeb128 (MCContext &Ctx, const MCFixup &Fixup, MutableArrayRef< char > Data, uint64_t Value)
static std::pair< MCFixupKind, MCFixupKind > getRelocPairForSize (unsigned Size)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "loongarch-asmbackend"
Definition at line 27 of file LoongArchAsmBackend.cpp.
ELF_RELOC
#define ELF_RELOC (X, Y) .Case(#X, Y)
Function Documentation
adjustFixupValue()
static uint64_t adjustFixupValue (const MCFixup & Fixup, uint64_t Value, MCContext & Ctx) static
Definition at line 90 of file LoongArchAsmBackend.cpp.
References Fixup, llvm::LoongArch::fixup_loongarch_abs64_hi12, llvm::LoongArch::fixup_loongarch_abs64_lo20, llvm::LoongArch::fixup_loongarch_abs_hi20, llvm::LoongArch::fixup_loongarch_abs_lo12, llvm::LoongArch::fixup_loongarch_b16, llvm::LoongArch::fixup_loongarch_b21, llvm::LoongArch::fixup_loongarch_b26, llvm::LoongArch::fixup_loongarch_tls_le64_hi12, llvm::LoongArch::fixup_loongarch_tls_le64_lo20, llvm::LoongArch::fixup_loongarch_tls_le_hi20, llvm::LoongArch::fixup_loongarch_tls_le_lo12, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_Data_leb128, llvm_unreachable, llvm::MCContext::reportError(), and reportOutOfRangeError().
fixupLeb128()
static void fixupLeb128 (MCContext & Ctx, const MCFixup & Fixup, MutableArrayRef< char > Data, uint64_t Value) static
Definition at line 137 of file LoongArchAsmBackend.cpp.
References llvm::Data, Fixup, I, and llvm::MCContext::reportError().
Referenced by llvm::LoongArchAsmBackend::applyFixup().
getRelocPairForSize()
static std::pair< MCFixupKind, MCFixupKind > getRelocPairForSize (unsigned Size) inline static
Definition at line 265 of file LoongArchAsmBackend.cpp.
References llvm::FirstLiteralRelocationKind, llvm_unreachable, and Size.
Referenced by llvm::LoongArchAsmBackend::handleAddSubRelocations(), llvm::LoongArchAsmBackend::relaxDwarfCFA(), and llvm::LoongArchAsmBackend::relaxDwarfLineAddr().
reportOutOfRangeError()
static void reportOutOfRangeError (MCContext & Ctx, SMLoc Loc, unsigned N) static
Definition at line 85 of file LoongArchAsmBackend.cpp.
References llvm::maxIntN(), llvm::minIntN(), N, and llvm::MCContext::reportError().
Referenced by adjustFixupValue().