LLVM: lib/CodeGen/LowerEmuTLS.cpp File Reference
LowerEmuTLS.cpp File Reference
#include "llvm/CodeGen/LowerEmuTLS.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/GlobalsModRef.h"
#include "llvm/Analysis/ModuleSummaryAnalysis.h"
#include "llvm/Analysis/StackSafetyAnalysis.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "lower-emutls"
Functions
static bool addEmuTlsVar (Module &M, const GlobalVariable *GV)
static void copyLinkageVisibility (Module &M, const GlobalVariable *from, GlobalVariable *to)
INITIALIZE_PASS (LowerEmuTLS, DEBUG_TYPE, "Add __emutls_[vt]. variables for emultated TLS model", false, false) ModulePass *llvm
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "lower-emutls"
Definition at line 31 of file LowerEmuTLS.cpp.
Function Documentation
addEmuTlsVar()
bool addEmuTlsVar (Module & M, const GlobalVariable * GV) static
Definition at line 109 of file LowerEmuTLS.cpp.
References assert(), llvm::CallingConv::C, copyLinkageVisibility(), llvm::StructType::create(), DL, llvm::ConstantPointerNull::get(), llvm::ConstantStruct::get(), llvm::ConstantInt::get(), llvm::GlobalObject::getAlign(), llvm::GlobalVariable::getInitializer(), llvm::Value::getName(), llvm::PointerType::getUnqual(), llvm::GlobalValue::getValueType(), llvm::GlobalVariable::hasInitializer(), llvm::ConstantInt::isZero(), llvm::GlobalObject::setAlignment(), llvm::GlobalVariable::setConstant(), llvm::GlobalVariable::setInitializer(), and llvm::Align::value().
Referenced by llvm::LowerEmuTLSPass::run().
copyLinkageVisibility()
static void copyLinkageVisibility (Module & M, const GlobalVariable * from, GlobalVariable * to) static
Definition at line 48 of file LowerEmuTLS.cpp.
References llvm::GlobalObject::getComdat(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), llvm::Comdat::getSelectionKind(), llvm::GlobalValue::getVisibility(), llvm::GlobalObject::hasComdat(), llvm::GlobalValue::isDSOLocal(), llvm::GlobalObject::setComdat(), llvm::GlobalValue::setDSOLocal(), llvm::GlobalValue::setLinkage(), llvm::Comdat::setSelectionKind(), and llvm::GlobalValue::setVisibility().
Referenced by addEmuTlsVar().
INITIALIZE_PASS()
INITIALIZE_PASS (LowerEmuTLS , DEBUG_TYPE , "Add __emutls_. variables for emultated TLS model" [vt], false , false)
Definition at line 80 of file LowerEmuTLS.cpp.