LLVM: lib/DebugInfo/LogicalView/LVReaderHandler.cpp File Reference
LVReaderHandler.cpp File Reference
#include "llvm/DebugInfo/LogicalView/LVReaderHandler.h"
#include "llvm/DebugInfo/CodeView/LazyRandomTypeCollection.h"
#include "llvm/DebugInfo/LogicalView/Core/LVCompare.h"
#include "llvm/DebugInfo/LogicalView/Readers/LVCodeViewReader.h"
#include "llvm/DebugInfo/LogicalView/Readers/LVELFReader.h"
#include "llvm/DebugInfo/PDB/Native/NativeSession.h"
#include "llvm/DebugInfo/PDB/PDB.h"
#include "llvm/Object/COFF.h"
Macros
#define DEBUG_TYPE "ReaderHandler"
Functions
static std::string searchForExe (const StringRef Path, const StringRef Extension)
static std::string searchForObj (const StringRef Path, const StringRef Extension)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ReaderHandler"
Definition at line 27 of file LVReaderHandler.cpp.
Function Documentation
searchForExe()
static std::string searchForExe (const StringRef Path, const StringRef Extension) static
Definition at line 95 of file LVReaderHandler.cpp.
References llvm::consumeError(), llvm::sys::path::convert_to_slash(), llvm::Expected< T >::get(), llvm::pdb::loadDataForEXE(), llvm::pdb::Path, llvm::sys::path::replace_extension(), llvm::pdb::NativeSession::searchForPdb(), llvm::Expected< T >::takeError(), and llvm::sys::path::windows.
searchForObj()
static std::string searchForObj (const StringRef Path, const StringRef Extension) static
Definition at line 121 of file LVReaderHandler.cpp.
References llvm::sys::fs::exists(), llvm::MemoryBuffer::getFileOrSTDIN(), llvm::pdb::Path, and llvm::sys::path::replace_extension().