LLVM: lib/Target/M68k/MCTargetDesc/M68kMCTargetDesc.cpp File Reference
M68kMCTargetDesc.cpp File Reference
This file provides M68k target specific descriptions.
#include "M68kMCTargetDesc.h"
#include "M68kInstPrinter.h"
#include "M68kMCAsmInfo.h"
#include "TargetInfo/M68kTargetInfo.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MachineLocation.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "M68kGenInstrInfo.inc"
#include "M68kGenSubtargetInfo.inc"
#include "M68kGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static std::string ParseM68kTriple (const Triple &TT, StringRef CPU)
static MCInstrInfo * createM68kMCInstrInfo ()
static MCRegisterInfo * createM68kMCRegisterInfo (const Triple &TT)
static MCSubtargetInfo * createM68kMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCAsmInfo * createM68kMCAsmInfo (const MCRegisterInfo &MRI, const Triple &TT, const MCTargetOptions &TO)
static MCRelocationInfo * createM68kMCRelocationInfo (const Triple &TheTriple, MCContext &Ctx)
static MCInstPrinter * createM68kMCInstPrinter (const Triple &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeM68kTargetMC ()
Detailed Description
This file provides M68k target specific descriptions.
Definition in file M68kMCTargetDesc.cpp.
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 34 of file M68kMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 33 of file M68kMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 40 of file M68kMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 37 of file M68kMCTargetDesc.cpp.
Function Documentation
createM68kMCAsmInfo()
static MCAsmInfo * createM68kMCAsmInfo (const MCRegisterInfo & MRI, const Triple & TT, const MCTargetOptions & TO) static
Definition at line 73 of file M68kMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::cfiDefCfa(), llvm::MCCFIInstruction::createOffset(), and MRI.
Referenced by LLVMInitializeM68kTargetMC().
createM68kMCInstPrinter()
static MCInstPrinter * createM68kMCInstPrinter (const Triple & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 102 of file M68kMCTargetDesc.cpp.
References MRI.
Referenced by LLVMInitializeM68kTargetMC().
createM68kMCInstrInfo()
static MCInstrInfo * createM68kMCInstrInfo () static
Definition at line 48 of file M68kMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeM68kTargetMC().
createM68kMCRegisterInfo()
static MCRegisterInfo * createM68kMCRegisterInfo (const Triple & TT) static
Definition at line 54 of file M68kMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeM68kTargetMC().
createM68kMCRelocationInfo()
static MCRelocationInfo * createM68kMCRelocationInfo (const Triple & TheTriple, MCContext & Ctx) static
Definition at line 96 of file M68kMCTargetDesc.cpp.
References llvm::createMCRelocationInfo().
Referenced by LLVMInitializeM68kTargetMC().
createM68kMCSubtargetInfo()
static MCSubtargetInfo * createM68kMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 60 of file M68kMCTargetDesc.cpp.
References ParseM68kTriple().
Referenced by LLVMInitializeM68kTargetMC().
LLVMInitializeM68kTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeM68kTargetMC ()
Definition at line 110 of file M68kMCTargetDesc.cpp.
References llvm::createM68kAsmBackend(), createM68kMCAsmInfo(), llvm::createM68kMCCodeEmitter(), createM68kMCInstPrinter(), createM68kMCInstrInfo(), createM68kMCRegisterInfo(), createM68kMCRelocationInfo(), createM68kMCSubtargetInfo(), llvm::getTheM68kTarget(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCRelocationInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), and X.
ParseM68kTriple()
static std::string ParseM68kTriple (const Triple & TT, StringRef CPU) static
Definition at line 44 of file M68kMCTargetDesc.cpp.
Referenced by createM68kMCSubtargetInfo().