LLVM: lib/CodeGen/MachineCopyPropagation.cpp File Reference
MachineCopyPropagation.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/iterator_range.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/DebugCounter.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <iterator>
Macros
#define DEBUG_TYPE "machine-cp"
Functions
STATISTIC (NumDeletes, "Number of dead copies deleted")
STATISTIC (NumCopyForwards, "Number of copy uses forwarded")
STATISTIC (NumCopyBackwardPropagated, "Number of copy defs backward propagated")
STATISTIC (SpillageChainsLength, "Length of spillage chains")
STATISTIC (NumSpillageChains, "Number of spillage chains")
DEBUG_COUNTER (FwdCounter, "machine-cp-fwd", "Controls which register COPYs are forwarded")
INITIALIZE_PASS (MachineCopyPropagation, DEBUG_TYPE, "Machine Copy Propagation Pass", false, false) void MachineCopyPropagation
static bool isNopCopy (const MachineInstr &PreviousCopy, MCRegister Src, MCRegister Def, const TargetRegisterInfo *TRI, const TargetInstrInfo *TII, bool UseCopyInstr)
Return true if PreviousCopy did copy register Src to register Def.
static bool isBackwardPropagatableCopy (const DestSourcePair &CopyOperands, const MachineRegisterInfo &MRI, const TargetInstrInfo &TII)
static void LLVM_ATTRIBUTE_UNUSED printSpillReloadChain (DenseMap< MachineInstr *, SmallVector< MachineInstr * > > &SpillChain, DenseMap< MachineInstr *, SmallVector< MachineInstr * > > &ReloadChain, MachineInstr *Leader)
Variables
static cl::opt< bool > MCPUseCopyInstr ("mcp-use-is-copy-instr", cl::init(false), cl::Hidden)
static cl::opt< cl::boolOrDefault > EnableSpillageCopyElimination ("enable-spill-copy-elim", cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "machine-cp"
Definition at line 78 of file MachineCopyPropagation.cpp.
Function Documentation
DEBUG_COUNTER()
DEBUG_COUNTER (FwdCounter , "machine-cp-fwd" , "Controls which register COPYs are forwarded")
INITIALIZE_PASS()
INITIALIZE_PASS (MachineCopyPropagation , DEBUG_TYPE , "Machine Copy Propagation Pass" , false , false)
Definition at line 446 of file MachineCopyPropagation.cpp.
References llvm::dbgs(), LLVM_DEBUG, and TRI.
isBackwardPropagatableCopy()
static bool isBackwardPropagatableCopy (const DestSourcePair & CopyOperands, const MachineRegisterInfo & MRI, const TargetInstrInfo & TII) static
Definition at line 950 of file MachineCopyPropagation.cpp.
References llvm::DestSourcePair::Destination, llvm::MachineOperand::getReg(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isRenamable(), MRI, and llvm::DestSourcePair::Source.
isNopCopy()
static bool isNopCopy (const MachineInstr & PreviousCopy, MCRegister Src, MCRegister Def, const TargetRegisterInfo * TRI, const TargetInstrInfo * TII, bool UseCopyInstr) static
Return true if PreviousCopy did copy register Src to register Def.
This fact may have been obscured by sub register usage or may not be true at all even though Src and Def are subregisters of the registers used in PreviousCopy. e.g. isNopCopy("ecx = COPY eax", AX, CX) == true isNopCopy("ecx = COPY eax", AH, CL) == false
Definition at line 472 of file MachineCopyPropagation.cpp.
References TII, and TRI.
printSpillReloadChain()
static void LLVM_ATTRIBUTE_UNUSED printSpillReloadChain (DenseMap< MachineInstr *, SmallVector< MachineInstr * > > & SpillChain, DenseMap< MachineInstr *, SmallVector< MachineInstr * > > & ReloadChain, MachineInstr * Leader) static
Definition at line 1107 of file MachineCopyPropagation.cpp.
References llvm::Pass::dump(), E, I, and MI.
STATISTIC() [1/5]
STATISTIC (NumCopyBackwardPropagated , "Number of copy defs backward propagated")
STATISTIC() [2/5]
STATISTIC (NumCopyForwards , "Number of copy uses forwarded")
STATISTIC() [3/5]
STATISTIC (NumDeletes , "Number of dead copies deleted")
STATISTIC() [4/5]
STATISTIC (NumSpillageChains , "Number of spillage chains")
STATISTIC() [5/5]
STATISTIC (SpillageChainsLength , "Length of spillage chains")
Variable Documentation
EnableSpillageCopyElimination
cl::opt< cl::boolOrDefault > EnableSpillageCopyElimination("enable-spill-copy-elim", cl::Hidden) ("enable-spill-copy-elim" , cl::Hidden) static
MCPUseCopyInstr
cl::opt< bool > MCPUseCopyInstr("mcp-use-is-copy-instr", cl::init(false), cl::Hidden) ("mcp-use-is-copy-instr" , cl::init(false) , cl::Hidden) static