LLVM: lib/CodeGen/MachineCFGPrinter.cpp File Reference
MachineCFGPrinter.cpp File Reference
#include "llvm/CodeGen/MachineCFGPrinter.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/PassRegistry.h"
#include "llvm/Support/GraphWriter.h"
Macros
#define DEBUG_TYPE "dot-machine-cfg"
Functions
static void writeMCFGToDotFile (MachineFunction &MF)
INITIALIZE_PASS (MachineCFGPrinter, DEBUG_TYPE, "Machine CFG Printer Pass", false, true) MachineCFGPrinter
Default construct and initialize the pass.
Variables
static cl::opt< std::string > MCFGFuncName ("mcfg-func-name", cl::Hidden, cl::desc("The name of a function (or its substring)" " whose CFG is viewed/printed."))
static cl::opt< std::string > MCFGDotFilenamePrefix ("mcfg-dot-filename-prefix", cl::Hidden, cl::desc("The prefix used for the Machine CFG dot file names."))
static cl::opt< bool > CFGOnly ("dot-mcfg-only", cl::init(false), cl::Hidden, cl::desc("Print only the CFG without blocks body"))
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "dot-machine-cfg"
Definition at line 25 of file MachineCFGPrinter.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (MachineCFGPrinter , DEBUG_TYPE , "Machine CFG Printer Pass" , false , true)
Default construct and initialize the pass.
Definition at line 79 of file MachineCFGPrinter.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineCFGPrinterPass().
writeMCFGToDotFile()
static void writeMCFGToDotFile (MachineFunction & MF) static
Definition at line 40 of file MachineCFGPrinter.cpp.
References CFGOnly, llvm::errs(), llvm::MachineFunction::getName(), MCFGDotFilenamePrefix, llvm::sys::fs::OF_Text, and llvm::WriteGraph().
Variable Documentation
CFGOnly
cl::opt< bool > CFGOnly("dot-mcfg-only", cl::init(false), cl::Hidden, cl::desc("Print only the CFG without blocks body")) ("dot-mcfg-only" , cl::init(false) , cl::Hidden , cl::desc("Print only the CFG without blocks body")) static
Referenced by viewCFG(), writeCFGToDotFile(), and writeMCFGToDotFile().
MCFGDotFilenamePrefix
cl::opt< std::string > MCFGDotFilenamePrefix("mcfg-dot-filename-prefix", cl::Hidden, cl::desc("The prefix used for the Machine CFG dot file names.")) ("mcfg-dot-filename-prefix" , cl::Hidden , cl::desc("The prefix used for the Machine CFG dot file names.")) static
Referenced by writeMCFGToDotFile().
MCFGFuncName
cl::opt< std::string > MCFGFuncName("mcfg-func-name", cl::Hidden, cl::desc("The name of a function (or its substring)" " whose CFG is viewed/printed.")) ("mcfg-func-name" , cl::Hidden , cl::desc("The name of a function (or its substring)" " whose CFG is viewed/printed.")) static