LLVM: gen-regalloc-eviction-test-model Namespace Reference
gen-regalloc-eviction-test-model Namespace Reference
Functions
def get_input_signature ()
def get_output_spec_path (path)
def build_mock_model (path)
def main (argv)
Variables
str POLICY_DECISION_LABEL = "index_to_evict"
str POLICY_OUTPUT_SPEC
list PER_REGISTER_FEATURE_LIST = ["mask"]
int NUM_REGISTERS = 33
Function Documentation
build_mock_model()
def gen-regalloc-eviction-test-model.build_mock_model (path)
Build and save the mock model with the given signature.
Definition at line 43 of file gen-regalloc-eviction-test-model.py.
References get_input_signature(), get_output_spec_path(), and print().
Referenced by main().
get_input_signature()
def gen-regalloc-eviction-test-model.get_input_signature ()
Returns (time_step_spec, action_spec) for LLVM register allocation.
Definition at line 30 of file gen-regalloc-eviction-test-model.py.
Referenced by build_mock_model().
get_output_spec_path()
def gen-regalloc-eviction-test-model.get_output_spec_path (path)
Definition at line 39 of file gen-regalloc-eviction-test-model.py.
Referenced by build_mock_model().
main()
def gen-regalloc-eviction-test-model.main (argv)
Definition at line 65 of file gen-regalloc-eviction-test-model.py.
References build_mock_model(), and main().
Referenced by main().
Variable Documentation
NUM_REGISTERS
int gen-regalloc-eviction-test-model.NUM_REGISTERS = 33
Definition at line 27 of file gen-regalloc-eviction-test-model.py.
PER_REGISTER_FEATURE_LIST
list gen-regalloc-eviction-test-model.PER_REGISTER_FEATURE_LIST = ["mask"]
Definition at line 26 of file gen-regalloc-eviction-test-model.py.
POLICY_DECISION_LABEL
str gen-regalloc-eviction-test-model.POLICY_DECISION_LABEL = "index_to_evict"
Definition at line 10 of file gen-regalloc-eviction-test-model.py.
POLICY_OUTPUT_SPEC
str gen-regalloc-eviction-test-model.POLICY_OUTPUT_SPEC
Initial value:
=  """
[
    {
        "logging_name": "index_to_evict",
        "tensor_spec": {
            "name": "StatefulPartitionedCall",
            "port": 0,
            "type": "int64_t",
            "shape": [
                1
            ]
        }
    }
]
"""
Definition at line 11 of file gen-regalloc-eviction-test-model.py.