LLVM: llvm::RISCVABI Namespace Reference
llvm::RISCVABI Namespace Reference
Enumerations
enum ABI {
ABI_ILP32 , ABI_ILP32F , ABI_ILP32D , ABI_ILP32E ,
ABI_LP64 , ABI_LP64F , ABI_LP64D , ABI_LP64E ,
ABI_Unknown
}
Functions
ABI computeTargetABI (const Triple &TT, const FeatureBitset &FeatureBits, StringRef ABIName)
ABI getTargetABI (StringRef ABIName)
MCRegister getBPReg ()
MCRegister getSCSPReg ()
Enumeration Type Documentation
ABI
enum llvm::RISCVABI::ABI
Enumerator
ABI_ILP32
ABI_ILP32F
ABI_ILP32D
ABI_ILP32E
ABI_LP64
ABI_LP64F
ABI_LP64D
ABI_LP64E
ABI_Unknown
Definition at line 449 of file RISCVBaseInfo.h.
Function Documentation
computeTargetABI()
ABI llvm::RISCVABI::computeTargetABI (const Triple & TT, const FeatureBitset & FeatureBits, StringRef ABIName)
Definition at line 39 of file RISCVBaseInfo.cpp.
References ABI_ILP32E, ABI_LP64E, ABI_Unknown, llvm::StringRef::empty(), llvm::errs(), getTargetABI(), llvm::RISCVFeatures::parseFeatureBits(), llvm::report_fatal_error(), and llvm::StringRef::starts_with().
Referenced by llvm::RISCVTargetELFStreamer::RISCVTargetELFStreamer().
getBPReg()
MCRegister llvm::RISCVABI::getBPReg ()
Definition at line 103 of file RISCVBaseInfo.cpp.
Referenced by llvm::RISCVFrameLowering::determineCalleeSaves(), llvm::RISCVFrameLowering::emitPrologue(), llvm::RISCVFrameLowering::getFrameIndexReference(), and llvm::RISCVRegisterInfo::getReservedRegs().
getSCSPReg()
MCRegister llvm::RISCVABI::getSCSPReg ()
Definition at line 106 of file RISCVBaseInfo.cpp.
Referenced by emitSCSEpilogue(), and emitSCSPrologue().
getTargetABI()
ABI llvm::RISCVABI::getTargetABI (StringRef ABIName)
Definition at line 86 of file RISCVBaseInfo.cpp.
References ABI_ILP32, ABI_ILP32D, ABI_ILP32E, ABI_ILP32F, ABI_LP64, ABI_LP64D, ABI_LP64E, ABI_LP64F, ABI_Unknown, llvm::StringSwitch< T, R >::Case(), and llvm::StringSwitch< T, R >::Default().
Referenced by computeTargetABI(), and llvm::RISCVTargetMachine::getSubtargetImpl().