LLVM: llvm::parallel Namespace Reference
llvm::parallel Namespace Reference
Namespaces
namespace detail
Classes
class PerThreadAllocator
PerThreadAllocator is used in conjunction with ThreadPoolExecutor to allow per-thread allocations.
class TaskGroup
Typedefs
using PerThreadBumpPtrAllocator = PerThreadAllocator< BumpPtrAllocator >
Functions
unsigned getThreadIndex ()
size_t getThreadCount ()
Variables
ThreadPoolStrategy strategy
Typedef Documentation
PerThreadBumpPtrAllocator
using llvm::parallel::PerThreadBumpPtrAllocator = typedef PerThreadAllocator<BumpPtrAllocator>
Definition at line 115 of file PerThreadBumpPtrAllocator.h.
Function Documentation
getThreadCount()
size_t llvm::parallel::getThreadCount () inline
Definition at line 55 of file Parallel.h.
References getThreadCount().
Referenced by getThreadCount().
getThreadIndex()
unsigned llvm::parallel::getThreadIndex () inline
Definition at line 54 of file Parallel.h.
References getThreadIndex().
Referenced by llvm::parallel::PerThreadAllocator< AllocatorTy >::Allocate(), llvm::parallel::PerThreadAllocator< AllocatorTy >::Deallocate(), getThreadIndex(), and llvm::parallel::PerThreadAllocator< AllocatorTy >::getThreadLocalAllocator().
Variable Documentation
strategy
llvm::ThreadPoolStrategy llvm::parallel::strategy extern
Definition at line 20 of file Parallel.cpp.
Referenced by llvm::dwarf_linker::parallel::DWARFLinkerImpl::link(), llvm::parallelSort(), and llvm::parallelTransformReduce().