LLVM: gen-regalloc-priority-test-model Namespace Reference
gen-regalloc-priority-test-model Namespace Reference
Functions
def get_input_signature ()
def get_output_spec_path (path)
def build_mock_model (path)
def main (argv)
Variables
str POLICY_DECISION_LABEL = "priority"
str POLICY_OUTPUT_SPEC
list PER_LIVEINTERVAL_INT64_FEATURE_LIST = ["li_size", "stage"]
list PER_LIVEINTERVAL_FLOAT32_FEATURE_LIST = ["weight"]
tuple PER_LIVEINTERVAL_FEATURE_LIST
tuple CONTEXT_FEATURE_LIST = ("discount", "reward", "step_type")
Function Documentation
build_mock_model()
def gen-regalloc-priority-test-model.build_mock_model (path)
Build and save the mock model with the given signature.
Definition at line 66 of file gen-regalloc-priority-test-model.py.
References get_input_signature(), get_output_spec_path(), and print().
Referenced by main().
get_input_signature()
def gen-regalloc-priority-test-model.get_input_signature ()
Returns (time_step_spec, action_spec) for LLVM register allocation.
Definition at line 35 of file gen-regalloc-priority-test-model.py.
Referenced by build_mock_model().
get_output_spec_path()
def gen-regalloc-priority-test-model.get_output_spec_path (path)
Definition at line 62 of file gen-regalloc-priority-test-model.py.
Referenced by build_mock_model().
main()
def gen-regalloc-priority-test-model.main (argv)
Definition at line 99 of file gen-regalloc-priority-test-model.py.
References build_mock_model(), and main().
Referenced by main().
Variable Documentation
CONTEXT_FEATURE_LIST
tuple gen-regalloc-priority-test-model.CONTEXT_FEATURE_LIST = ("discount", "reward", "step_type")
Definition at line 32 of file gen-regalloc-priority-test-model.py.
PER_LIVEINTERVAL_FEATURE_LIST
tuple gen-regalloc-priority-test-model.PER_LIVEINTERVAL_FEATURE_LIST
Initial value:
=  (
    PER_LIVEINTERVAL_FLOAT32_FEATURE_LIST + PER_LIVEINTERVAL_INT64_FEATURE_LIST
)
Definition at line 29 of file gen-regalloc-priority-test-model.py.
PER_LIVEINTERVAL_FLOAT32_FEATURE_LIST
list gen-regalloc-priority-test-model.PER_LIVEINTERVAL_FLOAT32_FEATURE_LIST = ["weight"]
Definition at line 28 of file gen-regalloc-priority-test-model.py.
PER_LIVEINTERVAL_INT64_FEATURE_LIST
list gen-regalloc-priority-test-model.PER_LIVEINTERVAL_INT64_FEATURE_LIST = ["li_size", "stage"]
Definition at line 27 of file gen-regalloc-priority-test-model.py.
POLICY_DECISION_LABEL
str gen-regalloc-priority-test-model.POLICY_DECISION_LABEL = "priority"
Definition at line 11 of file gen-regalloc-priority-test-model.py.
POLICY_OUTPUT_SPEC
str gen-regalloc-priority-test-model.POLICY_OUTPUT_SPEC
Initial value:
=  """
[
    {
        "logging_name": "priority",
        "tensor_spec": {
            "name": "StatefulPartitionedCall",
            "port": 0,
            "type": "float",
            "shape": [
                1
            ]
        }
    }
]
"""
Definition at line 12 of file gen-regalloc-priority-test-model.py.