LLVM: llvm::AMDGPU::DepCtr Namespace Reference
llvm::AMDGPU::DepCtr Namespace Reference
Functions
int getDefaultDepCtrEncoding (const MCSubtargetInfo &STI)
bool isSymbolicDepCtrEncoding (unsigned Code, bool &HasNonDefaultVal, const MCSubtargetInfo &STI)
bool decodeDepCtr (unsigned Code, int &Id, StringRef &Name, unsigned &Val, bool &IsDefault, const MCSubtargetInfo &STI)
int encodeDepCtr (const StringRef Name, int64_t Val, unsigned &UsedOprMask, const MCSubtargetInfo &STI)
unsigned decodeFieldVmVsrc (unsigned Encoded)
unsigned decodeFieldVaVdst (unsigned Encoded)
unsigned decodeFieldSaSdst (unsigned Encoded)
unsigned encodeFieldVmVsrc (unsigned Encoded, unsigned VmVsrc)
unsigned encodeFieldVmVsrc (unsigned VmVsrc)
unsigned encodeFieldVaVdst (unsigned Encoded, unsigned VaVdst)
unsigned encodeFieldVaVdst (unsigned VaVdst)
unsigned encodeFieldSaSdst (unsigned Encoded, unsigned SaSdst)
unsigned encodeFieldSaSdst (unsigned SaSdst)
Variables
const CustomOperandVal DepCtrInfo []
const int DEP_CTR_SIZE
Function Documentation
decodeDepCtr()
bool llvm::AMDGPU::DepCtr::decodeDepCtr (unsigned Code, int & Id, StringRef & Name, unsigned & Val, bool & IsDefault, const MCSubtargetInfo & STI)
Definition at line 1607 of file AMDGPUBaseInfo.cpp.
References llvm::AMDGPU::decodeCustomOperand(), DEP_CTR_SIZE, DepCtrInfo, and Name.
decodeFieldSaSdst()
unsigned llvm::AMDGPU::DepCtr::decodeFieldSaSdst (unsigned Encoded)
Returns
Decoded SaSdst from given immediate Encoded.
Definition at line 1627 of file AMDGPUBaseInfo.cpp.
decodeFieldVaVdst()
unsigned llvm::AMDGPU::DepCtr::decodeFieldVaVdst (unsigned Encoded)
Returns
Decoded VaVdst from given immediate Encoded.
Definition at line 1623 of file AMDGPUBaseInfo.cpp.
decodeFieldVmVsrc()
unsigned llvm::AMDGPU::DepCtr::decodeFieldVmVsrc (unsigned Encoded)
Returns
Decoded VmVsrc from given immediate Encoded.
Definition at line 1619 of file AMDGPUBaseInfo.cpp.
encodeDepCtr()
int llvm::AMDGPU::DepCtr::encodeDepCtr (const StringRef Name, int64_t Val, unsigned & UsedOprMask, const MCSubtargetInfo & STI)
Definition at line 1613 of file AMDGPUBaseInfo.cpp.
References DEP_CTR_SIZE, DepCtrInfo, llvm::AMDGPU::encodeCustomOperand(), and Name.
encodeFieldSaSdst() [1/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldSaSdst (unsigned Encoded, unsigned SaSdst)
Returns
Encoded combined with encoded SaSdst.
Definition at line 1647 of file AMDGPUBaseInfo.cpp.
Referenced by encodeFieldSaSdst().
encodeFieldSaSdst() [2/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldSaSdst (unsigned SaSdst)
Returns
SaSdst as an encoded Depctr immediate.
Definition at line 1651 of file AMDGPUBaseInfo.cpp.
References encodeFieldSaSdst().
encodeFieldVaVdst() [1/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVaVdst (unsigned Encoded, unsigned VaVdst)
Returns
Encoded combined with encoded VaVdst.
Definition at line 1639 of file AMDGPUBaseInfo.cpp.
Referenced by encodeFieldVaVdst().
encodeFieldVaVdst() [2/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVaVdst (unsigned VaVdst)
Returns
VaVdst as an encoded Depctr immediate.
Definition at line 1643 of file AMDGPUBaseInfo.cpp.
References encodeFieldVaVdst().
encodeFieldVmVsrc() [1/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVmVsrc (unsigned Encoded, unsigned VmVsrc)
Returns
Encoded combined with encoded VmVsrc.
Definition at line 1631 of file AMDGPUBaseInfo.cpp.
Referenced by encodeFieldVmVsrc().
encodeFieldVmVsrc() [2/2]
unsigned llvm::AMDGPU::DepCtr::encodeFieldVmVsrc (unsigned VmVsrc)
Returns
VmVsrc as an encoded Depctr immediate.
Definition at line 1635 of file AMDGPUBaseInfo.cpp.
References encodeFieldVmVsrc().
getDefaultDepCtrEncoding()
int llvm::AMDGPU::DepCtr::getDefaultDepCtrEncoding (const MCSubtargetInfo & STI)
Definition at line 1594 of file AMDGPUBaseInfo.cpp.
References llvm::Default, DEP_CTR_SIZE, DepCtrInfo, and llvm::AMDGPU::getDefaultCustomOperandEncoding().
isSymbolicDepCtrEncoding()
bool llvm::AMDGPU::DepCtr::isSymbolicDepCtrEncoding (unsigned Code, bool & HasNonDefaultVal, const MCSubtargetInfo & STI)
Definition at line 1601 of file AMDGPUBaseInfo.cpp.
References DEP_CTR_SIZE, DepCtrInfo, and llvm::AMDGPU::isSymbolicCustomOperandEncoding().
Variable Documentation
DEP_CTR_SIZE
const int llvm::AMDGPU::DepCtr::DEP_CTR_SIZE
Initial value:
=
    static_cast<int>(sizeof(DepCtrInfo) / sizeof(CustomOperandVal))
Definition at line 30 of file AMDGPUAsmUtils.cpp.
Referenced by decodeDepCtr(), encodeDepCtr(), getDefaultDepCtrEncoding(), and isSymbolicDepCtrEncoding().
DepCtrInfo
const CustomOperandVal llvm::AMDGPU::DepCtr::DepCtrInfo
Initial value:
= {
  {{"depctr_hold_cnt"},  1,   1,    7,    1,   isGFX10_BEncoding},
  {{"depctr_sa_sdst"},   1,   1,    0,    1},
  {{"depctr_va_vdst"},  15,  15,   12,    4},
  {{"depctr_va_sdst"},   7,   7,    9,    3},
  {{"depctr_va_ssrc"},   1,   1,    8,    1},
  {{"depctr_va_vcc"},    1,   1,    1,    1},
  {{"depctr_vm_vsrc"},   7,   7,    2,    3},
}
Definition at line 18 of file AMDGPUAsmUtils.cpp.
Referenced by decodeDepCtr(), encodeDepCtr(), getDefaultDepCtrEncoding(), and isSymbolicDepCtrEncoding().