LLVM: lib/Target/NVPTX/NVVMIntrRange.cpp File Reference
NVVMIntrRange.cpp File Reference
#include "NVPTX.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/InstIterator.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IntrinsicsNVPTX.h"
#include "llvm/IR/PassManager.h"
#include "llvm/Support/CommandLine.h"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "nvvm-intr-range"
Functions
void llvm::initializeNVVMIntrRangePass (PassRegistry &)
INITIALIZE_PASS (NVVMIntrRange, "nvvm-intr-range", "Add !range metadata to NVVM intrinsics.", false, false) static bool addRangeMetadata(uint64_t Low
C setMetadata (LLVMContext::MD_range, MDNode::get(Context, LowAndHigh))
static bool runNVVMIntrRange (Function &F, unsigned SmVersion)
Variables
static cl::opt< unsigned > NVVMIntrRangeSM ("nvvm-intr-range-sm", cl::init(20), cl::Hidden, cl::desc("SM variant"))
uint64_t High
uint64_t CallInst * C
LLVMContext & Context = C->getParent()->getContext()
IntegerType * Int32Ty = Type::getInt32Ty(Context)
Metadata * LowAndHigh []
return true
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "nvvm-intr-range"
Definition at line 25 of file NVVMIntrRange.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (NVVMIntrRange , "nvvm-intr-range" , "Add !range metadata to NVVM intrinsics." , false , false)
runNVVMIntrRange()
static bool runNVVMIntrRange (Function & F, unsigned SmVersion) static
Definition at line 75 of file NVVMIntrRange.cpp.
References F, I, instructions, and SmVersion.
Referenced by llvm::NVVMIntrRangePass::run().
setMetadata()
C setMetadata (LLVMContext::MD_range , MDNode::get(Context, LowAndHigh))
Variable Documentation
C
uint64_t CallInst* C
Initial value:
{
  if (C->getMetadata(LLVMContext::MD_range))
    return false
Definition at line 61 of file NVVMIntrRange.cpp.
Context
LLVMContext& Context = C->getParent()->getContext()
Definition at line 66 of file NVVMIntrRange.cpp.
Referenced by llvm::adaptNoAliasScopes(), llvm::LLVMTargetMachine::addAsmPrinter(), addAsyncContextAttrs(), llvm::HexagonMCInstrInfo::addConstant(), llvm::HexagonMCInstrInfo::addConstExtender(), llvm::sampleprof::SampleProfileWriterBinary::addContext(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::addContext(), llvm::ConstantPool::addEntry(), llvm::CSKYConstantPool::addEntry(), addFramePointerAttrs(), llvm::DwarfCompileUnit::addGlobalName(), llvm::DwarfTypeUnit::addGlobalName(), llvm::DwarfCompileUnit::addGlobalNameForTypeUnit(), llvm::DwarfCompileUnit::addGlobalType(), llvm::DwarfTypeUnit::addGlobalType(), llvm::DwarfCompileUnit::addGlobalTypeUnitType(), addModuleFlags(), AddReturnAttributes(), llvm::AddrLabelMap::AddrLabelMap(), AddRuntimeUnrollDisableMetaData(), llvm::addStringMetadataToLoop(), addSwiftSelfAttrs(), adjustDuplex(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::RegAllocBase::allocatePhysRegs(), llvm::X86TargetLowering::allowsMemoryAccess(), llvm::HexagonTargetLowering::allowsMemoryAccess(), llvm::TargetLoweringBase::allowsMemoryAccess(), llvm::TargetLoweringBase::allowsMemoryAccessForAlignment(), llvm::BasicTTIImplBase< T >::allowsMisalignedMemoryAccesses(), llvm::TargetTransformInfo::allowsMisalignedMemoryAccesses(), llvm::GenericUniformityAnalysisImpl< ContextT >::analyzeControlDivergence(), llvm::LoopVersioning::annotateInstWithNoAlias(), llvm::DwarfCompileUnit::applySubprogramAttributesToDefinition(), assureFPCallStub(), llvm::AVRMCELFStreamer::AVRMCELFStreamer(), llvm::BinaryStreamError::BinaryStreamError(), llvm::DICompositeType::buildODRType(), buildSymbolDiff(), calcPredicateUsingBooleans(), calcPredicateUsingInteger(), llvm::CallGraphSCC::CallGraphSCC(), llvm::VETargetLowering::CanLowerReturn(), llvm::SITargetLowering::CanLowerReturn(), llvm::HexagonTargetLowering::CanLowerReturn(), llvm::LanaiTargetLowering::CanLowerReturn(), llvm::LoongArchTargetLowering::CanLowerReturn(), llvm::RISCVTargetLowering::CanLowerReturn(), llvm::SparcTargetLowering::CanLowerReturn(), llvm::SystemZTargetLowering::CanLowerReturn(), llvm::X86CallLowering::canLowerReturn(), canonicalizeMetadataForValue(), llvm::HexagonMCInstrInfo::canonicalizePacket(), llvm::CCState::CCState(), checkGlobalVariableScope(), llvm::cloneAndAdaptNoAliasScopes(), llvm::UnreachableInst::cloneImpl(), llvm::JumpThreadingPass::cloneInstructions(), llvm::cloneNoAliasScopes(), llvm::GenericUniformityAnalysisImpl< ContextT >::compute(), llvm::GenericCycleInfo< ContextT >::compute(), llvm::DefaultContextualFoldingSetTrait< T, Ctx >::ComputeHash(), computeMemberData(), llvm::ContextAndReplaceableUses::ContextAndReplaceableUses(), llvm::ContextualFoldingSet< T, Ctx >::ContextualFoldingSet(), llvm::ContextWorklistItem::ContextWorklistItem(), llvm::BasicBlock::Create(), llvm::StructType::create(), llvm::object::IRObjectFile::create(), llvm::createAArch64ELFStreamer(), llvm::createAArch64WinCOFFStreamer(), llvm::createAMDGPUELFStreamer(), llvm::createARMELFStreamer(), llvm::createARMWinCOFFStreamer(), llvm::createAsmStreamer(), llvm::createAVRELFStreamer(), llvm::object::createBinary(), llvm::DIBuilder::createClassType(), llvm::sampleprof::SampleContext::createCtxVectorFromStr(), llvm::DPValue::createDebugIntrinsic(), llvm::MIRParserImpl::createDummyFunction(), llvm::createDXContainerStreamer(), llvm::createELFStreamer(), CreateFailBB(), createFPFnStub(), llvm::LTOModule::createFromBuffer(), llvm::LTOModule::createFromFile(), llvm::LTOModule::createFromOpenFile(), llvm::LTOModule::createFromOpenFileSlice(), llvm::sampleprofutil::createFSDiscriminatorVariable(), llvm::DIBuilder::createFunction(), llvm::RandomIRBuilder::createFunctionDefinition(), llvm::DIBuilder::createGlobalVariableExpression(), llvm::createGOFFStreamer(), llvm::createHexagonELFStreamer(), llvm::DIBuilder::createImportedDeclaration(), llvm::DIBuilder::createImportedModule(), createImportedModule(), llvm::LTOModule::createInLocalContext(), llvm::DIBuilder::createLabel(), createLocalVariable(), llvm::createMachOStreamer(), createMCStreamer(), llvm::LLVMTargetMachine::createMCStreamer(), llvm::DIBuilder::createMethod(), llvm::createMipsELFStreamer(), llvm::createMipsNaClELFStreamer(), llvm::createMIRParser(), llvm::createMIRParserFromFile(), llvm::createNullStreamer(), createPPCELFStreamer(), llvm::createPPCELFStreamer(), createPPCXCOFFStreamer(), llvm::createPPCXCOFFStreamer(), llvm::createSPIRVStreamer(), createStringMetadata(), llvm::DIBuilder::createStructType(), llvm::object::SymbolicFile::createSymbolicFile(), llvm::DIBuilder::createTempFunctionFwdDecl(), llvm::DIBuilder::createTempGlobalVariableFwdDecl(), llvm::DIBuilder::createTemplateParameterPack(), llvm::DIBuilder::createTemplateTemplateParameter(), llvm::DIBuilder::createTemplateTypeParameter(), llvm::DIBuilder::createTemplateValueParameter(), createTemplateValueParameterHelper(), llvm::DIBuilder::createTypedef(), llvm::DwarfUnit::createTypeDIE(), llvm::createWasmStreamer(), llvm::createXCOFFStreamer(), llvm::CSKYELFStreamer::CSKYELFStreamer(), DecodeFixedType(), llvm::X86TargetLowering::decomposeMulByConstant(), llvm::HexagonMCInstrInfo::deriveDuplex(), llvm::NewArchiveMember::detectKindFromObject(), DiagHandler(), DisableAllLoopOptsOnLoop(), llvm::DITemplateParameter::DITemplateParameter(), llvm::MDNode::dropAllReferences(), llvm::DWARFCompileUnit::DWARFCompileUnit(), llvm::DWARFTypeUnit::DWARFTypeUnit(), llvm::DWARFUnit::DWARFUnit(), llvm::MCDwarfFrameEmitter::Emit(), llvm::MCDwarfLineAddr::Emit(), EmitAbsDifference(), llvm::MCStreamer::emitAbsoluteSymbolDiff(), llvm::MCStreamer::emitAbsoluteSymbolDiffAsULEB128(), llvm::AMDGPUTargetELFStreamer::EmitAmdhsaKernelDescriptor(), llvm::MipsTargetELFStreamer::emitDirectiveEnd(), llvm::MCStreamer::emitDwarfUnitLength(), emitErrorMsg(), llvm::EHStreamer::emitExceptionTable(), llvm::MCObjectStreamer::emitFill(), llvm::MipsTargetELFStreamer::emitFrame(), llvm::AMDGPUAsmPrinter::emitFunctionBodyEnd(), llvm::AMDGPUTargetELFStreamer::EmitHSAMetadata(), llvm::MipsELFStreamer::emitInstruction(), llvm::AMDGPUTargetELFStreamer::EmitISAVersion(), llvm::dwarf_linker::classic::DwarfStreamer::emitMacroTables(), llvm::MipsTargetELFStreamer::emitMipsAbiFlags(), llvm::AArch64TargetStreamer::emitNoteSection(), llvm::ARCFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::MCStreamer::emitPseudoProbe(), EmitSymbolRefWithOfs(), llvm::MCStreamer::emitWinCFIPushReg(), llvm::MCStreamer::emitWinCFISaveReg(), llvm::MCStreamer::emitWinCFISaveXMM(), llvm::MCDwarfLineAddr::encode(), llvm::MCDwarfFrameEmitter::encodeAdvanceLoc(), llvm::MCStreamer::endSection(), llvm::DefaultContextualFoldingSetTrait< T, Ctx >::Equals(), llvm::dwarf_linker::parallel::LinkingGlobalData::error(), llvm::MIRParserImpl::error(), ErrorFromHResult(), llvm::AVRMCExpr::evaluateAsRelocatableImpl(), llvm::PPCMCExpr::evaluateAsRelocatableImpl(), llvm::HexagonMCInstrInfo::extendIfNeeded(), llvm::DWARFUnitHeader::extract(), llvm::DWARFUnit::extractRangeList(), llvm::DWARFUnit::findRnglistFromOffset(), forceExpAbs(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::forEachCompileAndTypeUnit(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::forEachCompileUnit(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::forEachObjectSectionsSet(), llvm::GCNIterativeScheduler::GCNIterativeScheduler(), llvm::gcovOneInput(), llvm::GenericSyncDependenceAnalysis< ContextT >::GenericSyncDependenceAnalysis(), llvm::ConstantTokenNone::get(), llvm::ConstantDataArray::get(), llvm::MDNode::get(), llvm::MDTuple::get(), llvm::StructType::get(), llvm::ConstantDataVector::get(), llvm::DIArgList::get(), llvm::Attribute::get(), llvm::ConstantInt::get(), llvm::MDString::get(), llvm::MetadataAsValue::get(), llvm::ConstantFP::get(), llvm::ValueAsMetadata::get(), llvm::DWARFUnit::getAddrOffsetSectionItem(), getAISize(), llvm::DIAssignID::getAllDPValueUsers(), llvm::object::Archive::Child::getAsBinary(), llvm::SampleContextTracker::getBaseSamplesFor(), llvm::ConstantInt::getBool(), llvm::DINode::getCanonicalMDString(), llvm::DIMacroNode::getCanonicalMDString(), llvm::dwarf_linker::classic::DeclContextTree::getChildDeclContext(), getCompoundInsn(), llvm::LLParser::getContext(), llvm::LTOCodeGenerator::getContext(), llvm::ContextualFoldingSet< T, Ctx >::getContext(), llvm::CCState::getContext(), llvm::MachineModuleInfo::getContext(), llvm::SelectionDAG::getContext(), llvm::DWARFUnit::getContext(), llvm::ReplaceableMetadataImpl::getContext(), llvm::MDNode::getContext(), llvm::Module::getContext(), llvm::Type::getContext(), llvm::MCAssembler::getContext(), llvm::MCStreamer::getContext(), llvm::Pattern::getContext(), llvm::SampleContextTracker::getContextFor(), llvm::SampleContextTracker::getContextSamplesFor(), llvm::sampleprof::SampleContext::getContextString(), llvm::DWARFUnit::getDebugInfoExtractor(), llvm::DIAssignID::getDistinct(), llvm::MDNode::getDistinct(), llvm::MDTuple::getDistinct(), getDivRemArgList(), llvm::EVT::getDoubleNumVectorElementsVT(), llvm::getDWARFUnitIndex(), llvm::MCAsmInfo::getExprForFDESymbol(), llvm::AArch64MCAsmInfoDarwin::getExprForPersonalitySymbol(), llvm::X86_64MCAsmInfoDarwin::getExprForPersonalitySymbol(), llvm::ConstantInt::getFalse(), llvm::GenericCycleInfo< ContextT >::getFunction(), getFunctionTypeFromAsyncSuspend(), getGlobalOffsetTable(), llvm::EVT::getHalfNumVectorElementsVT(), llvm::EVT::getHalfSizedIntegerVT(), llvm::MDNode::getIfExists(), llvm::MDTuple::getIfExists(), llvm::MetadataAsValue::getIfExists(), llvm::getIntDivCycle(), llvm::EVT::getIntegerVT(), getKeyFPValMD(), getKeyValMD(), llvm::getLazyBitcodeModule(), llvm::getLazyIRFileModule(), llvm::getLazyIRModule(), llvm::BitcodeModule::getLazyModule(), llvm::ProfileSummary::getMD(), getMDNodeOperandImpl(), llvm::TargetTransformInfoImplBase::getMemcpyLoopLoweringType(), llvm::GCNTTIImpl::getMemcpyLoopLoweringType(), llvm::TargetTransformInfo::getMemcpyLoopLoweringType(), llvm::TargetTransformInfoImplBase::getMemcpyLoopResidualLoweringType(), llvm::GCNTTIImpl::getMemcpyLoopResidualLoweringType(), llvm::TargetTransformInfo::getMemcpyLoopResidualLoweringType(), llvm::SystemZTargetLowering::getNumRegisters(), llvm::TargetLoweringBase::getNumRegisters(), llvm::TargetLoweringBase::getNumRegistersForCallingConv(), llvm::AArch64TargetLowering::getNumRegistersForCallingConv(), llvm::SITargetLowering::getNumRegistersForCallingConv(), llvm::MipsTargetLowering::getNumRegistersForCallingConv(), llvm::RISCVTargetLowering::getNumRegistersForCallingConv(), llvm::SPIRVTargetLowering::getNumRegistersForCallingConv(), llvm::X86TargetLowering::getNumRegistersForCallingConv(), llvm::MDNode::getNumTemporaryUses(), llvm::DICompositeType::getODRTypeIfExists(), llvm::AMDGPU::getOprIdx(), GetOptionalAbsDifference(), llvm::DwarfUnit::getOrCreateContextDIE(), llvm::DwarfCompileUnit::getOrCreateContextDIE(), llvm::SampleContextTracker::getOrCreateContextPath(), llvm::symbolize::LLVMSymbolizer::getOrCreateModuleInfo(), llvm::getOrCreateSPIRVDeviceEventPointer(), llvm::DwarfUnit::getOrCreateTypeDIE(), getOrSelfReference(), llvm::getOutermostDivergentCycle(), llvm::getOwningLazyBitcodeModule(), llvm::DwarfUnit::getParentContextString(), llvm::EVT::getPow2VectorType(), llvm::TargetLoweringBase::getPreferredSwitchConditionType(), llvm::X86TargetLowering::getPreferredSwitchConditionType(), llvm::LTOModule::getProducerString(), getRegistersForValue(), llvm::TargetLoweringBase::getRegisterType(), llvm::TargetLoweringBase::getRegisterTypeForCallingConv(), llvm::AArch64TargetLowering::getRegisterTypeForCallingConv(), llvm::SITargetLowering::getRegisterTypeForCallingConv(), llvm::MipsTargetLowering::getRegisterTypeForCallingConv(), llvm::RISCVTargetLowering::getRegisterTypeForCallingConv(), llvm::SPIRVTargetLowering::getRegisterTypeForCallingConv(), llvm::SystemZTargetLowering::getRegisterTypeForCallingConv(), llvm::X86TargetLowering::getRegisterTypeForCallingConv(), llvm::getReplayInlineAdvisor(), llvm::CallLowering::getReturnInfo(), llvm::DWARFUnit::getRnglistOffset(), llvm::EVT::getRoundIntegerType(), llvm::RISCVTargetLowering::getSetCCResultType(), llvm::X86TargetLowering::getSetCCResultType(), llvm::GenericCycleInfo< ContextT >::getSSAContext(), llvm::InstrProfIncrementInst::getStep(), llvm::ConstantDataArray::getString(), llvm::DWARFUnit::getStringOffsetSectionItem(), GetSubDivExpr(), getSymbolicFile(), llvm::DIAssignID::getTemporary(), llvm::MDNode::getTemporary(), llvm::MDTuple::getTemporary(), getTLSGetOffset(), llvm::ConstantInt::getTrue(), llvm::Intrinsic::getType(), llvm::TargetLoweringBase::getTypeAction(), llvm::TargetLoweringBase::getTypeConversion(), llvm::ConstantStruct::getTypeForElements(), llvm::EVT::getTypeForEVT(), llvm::AMDGPUTargetLowering::getTypeForExtReturn(), llvm::TargetLoweringBase::getTypeToExpandTo(), llvm::TargetLoweringBase::getTypeToTransformTo(), llvm::X86TargetLowering::getTypeToTransformTo(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), llvm::TargetLoweringBase::getVectorTypeBreakdownForCallingConv(), llvm::AArch64TargetLowering::getVectorTypeBreakdownForCallingConv(), llvm::SITargetLowering::getVectorTypeBreakdownForCallingConv(), llvm::MipsTargetLowering::getVectorTypeBreakdownForCallingConv(), llvm::RISCVTargetLowering::getVectorTypeBreakdownForCallingConv(), llvm::X86TargetLowering::getVectorTypeBreakdownForCallingConv(), llvm::EVT::getVectorVT(), getWinCFISection(), llvm::Attribute::getWithAlignment(), llvm::Attribute::getWithAllocSizeArgs(), llvm::Attribute::getWithByRefType(), llvm::Attribute::getWithByValType(), llvm::Attribute::getWithDereferenceableBytes(), llvm::Attribute::getWithDereferenceableOrNullBytes(), llvm::Attribute::getWithInAllocaType(), llvm::Attribute::getWithMemoryEffects(), llvm::Attribute::getWithNewType(), llvm::Attribute::getWithNoFPClass(), llvm::Attribute::getWithPreallocatedType(), llvm::Attribute::getWithStackAlignment(), llvm::Attribute::getWithStructRetType(), llvm::Attribute::getWithUWTableKind(), llvm::Attribute::getWithVScaleRangeArgs(), llvm::ValueAsMetadata::handleRAUW(), handleYAMLDiag(), llvm::sampleprof::hash_value(), llvm::HexagonMCChecker::HexagonMCChecker(), llvm::HexagonMCELFStreamer::HexagonMCELFStreamer(), llvm::HexagonMCShuffle(), llvm::HexagonShuffler::HexagonShuffler(), inlineGetBaseAndOffset(), llvm::LTOModule::isBitcodeForTarget(), llvm::object::SymbolicFile::isSymbolicFile(), llvm::AMDGPU::isValidOpr(), llvm::ItaniumPartialDemangler::ItaniumPartialDemangler(), llvm::RISCVTargetLowering::joinRegisterPartsIntoValue(), llvm::dwarf_linker::classic::DWARFLinker::link(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::link(), llvm::LLLexer::LLLexer(), llvm::LLParser::LLParser(), LLVMCreateBinary(), LLVMGetCurrentDebugLocation(), LLVMGetMDNodeOperands(), LLVMGetNamedMetadataOperands(), LLVMMDNodeInContext(), LLVMMDStringInContext(), loadFile(), lookForCompound(), LowerCTLZ(), llvm::coro::LowererBase::LowererBase(), LowerFPToInt(), llvm::IntrinsicLowering::LowerIntrinsicCall(), LowerUINT_TO_FP_i64(), llvm::LTOCodeGenerator::LTOCodeGenerator(), llvm::MachineModuleInfo::MachineModuleInfo(), llvm::object::makeDuplicateResourceError(), llvm::makePostTransformationMetadata(), makeStatepointExplicitImpl(), llvm::coro::LowererBase::makeSubFnCall(), llvm::GenericUniformityAnalysisImpl< ContextT >::markDivergent(), llvm::Pattern::match(), llvm::MCStreamer::maybeEmitDwarf64Mark(), llvm::MCAssembler::MCAssembler(), llvm::MCDXContainerStreamer::MCDXContainerStreamer(), llvm::MCELFStreamer::MCELFStreamer(), llvm::MCGOFFStreamer::MCGOFFStreamer(), llvm::MCObjectStreamer::MCObjectStreamer(), llvm::MCSPIRVStreamer::MCSPIRVStreamer(), llvm::MCStreamer::MCStreamer(), llvm::MCWasmStreamer::MCWasmStreamer(), llvm::MCWinCOFFStreamer::MCWinCOFFStreamer(), llvm::MCXCOFFStreamer::MCXCOFFStreamer(), llvm::MDBuilder::MDBuilder(), llvm::MDNode::MDNode(), llvm::MetadataLoader::MetadataLoaderImpl::MetadataLoaderImpl(), llvm::MipsELFStreamer::MipsELFStreamer(), llvm::MipsRegInfoRecord::MipsRegInfoRecord(), llvm::MIRParserImpl::MIRParserImpl(), llvm::Module::Module(), llvm::ObjectSizeOffsetEvaluator::ObjectSizeOffsetEvaluator(), llvm::sampleprof::SampleContext::Hash::operator()(), llvm::sampleprof::operator<<(), llvm::OptPassGateInstrumentation::OptPassGateInstrumentation(), llvm::HexagonMCInstrInfo::padEndloop(), llvm::object::WindowsResourceParser::parse(), llvm::parseAndVerify(), llvm::parseAssembly(), llvm::parseAssemblyFile(), parseAssemblyFileWithIndex(), llvm::parseAssemblyFileWithIndex(), llvm::parseAssemblyFileWithIndexNoUpgradeDebugInfo(), llvm::parseAssemblyString(), parseAssemblyWithIndex(), llvm::parseAssemblyWithIndex(), llvm::parseBitcodeFile(), parseBitcodeFileImpl(), llvm::parseIR(), llvm::parseIRFile(), llvm::MIRParserImpl::parseIRModule(), llvm::parseModule(), llvm::BitcodeModule::parseModule(), llvm::DWARFDebugLine::SectionParser::parseNext(), llvm::Pattern::parseNumericSubstitutionBlock(), llvm::Pattern::parsePattern(), llvm::parseTypeString(), llvm::Pattern::Pattern(), postUnswitch(), llvm::PPCELFStreamer::PPCELFStreamer(), llvm::PPCXCOFFStreamer::PPCXCOFFStreamer(), llvm::LoopVersioning::prepareNoAliasMetadata(), llvm::MIPrinter::print(), llvm::MachineInstr::print(), llvm::MachineMemOperand::print(), llvm::GenericCycleInfo< ContextT >::print(), llvm::GenericUniformityAnalysisImpl< ContextT >::print(), llvm::dwarf_linker::parallel::DWARFLinkerImpl::printStatistic(), printSyncScope(), llvm::Pattern::printVariableDefs(), llvm::DefaultContextualFoldingSetTrait< T, Ctx >::Profile(), llvm::sampleprof::SampleProfileReaderBinary::readSampleContextFromTable(), llvm::RecordStreamer::RecordStreamer(), llvm::RegsForValue::RegsForValue(), llvm::ReplaceableMetadataImpl::ReplaceableMetadataImpl(), llvm::MDNode::replaceAllUsesWith(), replaceAsyncResumeFunction(), replaceCoroEnd(), llvm::HexagonMCInstrInfo::replaceDuplex(), llvm::ReplayInlineAdvisor::ReplayInlineAdvisor(), llvm::MIRParserImpl::reportDiagnostic(), llvm::ThinLTOCodeGenerator::run(), llvm::OptimizationRemarkEmitterAnalysis::run(), llvm::WasmEHPreparePass::run(), runIPSCCP(), llvm::OptimizationRemarkEmitterWrapperPass::runOnFunction(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::R600AsmPrinter::runOnMachineFunction(), llvm::ReplaceableMetadataImpl::SalvageDebugInfo(), llvm::sampleprof::SampleContext::SampleContext(), llvm::SampleContextTracker::SampleContextTracker(), ScaleAddrDelta(), llvm::DWARFDebugLine::SectionParser::SectionParser(), llvm::LoopVectorizeHints::setAlreadyVectorized(), llvm::sampleprof::SampleContext::setContext(), llvm::Loop::setLoopAlreadyUnrolled(), llvm::Loop::setLoopMustProgress(), llvm::setupLLVMOptimizationRemarks(), llvm::lto::setupLLVMOptimizationRemarks(), llvm::TargetLoweringBase::shouldNormalizeToSelectSequence(), simplifySwitchOfPowersOfTwo(), simplifyUsingControlFlow(), llvm::DWARFDebugLine::SectionParser::skip(), splitAsyncCoroutine(), llvm::splitLoopBound(), llvm::RISCVTargetLowering::splitValueIntoRegisterParts(), llvm::StandardInstrumentations::StandardInstrumentations(), llvm::MDNode::storeDistinctInContext(), transformCallee(), llvm::sampleprof::SampleContextTrimmer::trimAndMergeColdContextProfiles(), llvm::HexagonMCInstrInfo::tryCompound(), llvm::DWARFUnit::tryExtractDIEsIfNeeded(), llvm::Type::Type(), llvm::UnreachableInst::UnreachableInst(), updateCallGraphAfterCoroutineSplit(), llvm::UpgradeBitCastExpr(), llvm::UpgradeBitCastInst(), llvm::UpgradeTBAANode(), llvm::GenericConvergenceVerifier< ContextT >::verify(), llvm::GenericConvergenceVerifier< ContextT >::visit(), llvm::dwarf_linker::parallel::LinkingGlobalData::warn(), llvm::EVT::widenIntegerVectorElementType(), llvm::writeArchiveToStream(), llvm::sampleprof::SampleProfileWriterBinary::writeContextIdx(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeContextIdx(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeCSNameIdx(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeCSNameTableSection(), llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeFuncOffsetTable(), and llvm::sampleprof::SampleProfileWriterExtBinaryBase::writeSample().
High
uint64_t High
Definition at line 61 of file NVVMIntrRange.cpp.
Referenced by addRange(), llvm::SwitchCG::SwitchLowering::buildBitTests(), llvm::SwitchCG::SwitchLowering::buildJumpTable(), expandBounds(), llvm::LegalizerHelper::fewerElementsVectorShuffle(), llvm::SwitchCG::SwitchLowering::findBitTestClusters(), llvm::SwitchCG::SwitchLowering::findJumpTables(), llvm::getConstantRangeFromMetadata(), getTestUnderMaskCond(), llvm::getX86SubSuperRegister(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), insert1BitVector(), llvm::TargetLoweringBase::isSuitableForBitTests(), llvm::Intrinsic::lookupLLVMIntrinsicByName(), LowerHorizontalByteSum(), LowerMULO(), lowerUINT_TO_FP_vXi32(), llvm::Make_64(), matchFunnelShift(), llvm::TargetLoweringBase::rangeFitsInWord(), llvm::SystemZMachineFunctionInfo::setRestoreGPRRegs(), llvm::SystemZMachineFunctionInfo::setSpillGPRRegs(), llvm::SIInstrInfo::splitMUBUFOffset(), tryMergeRange(), llvm::UpgradeIntrinsicCall(), and llvm::SelectionDAGBuilder::visitSwitchCase().
Int32Ty
IntegerType* Int32Ty = Type::getInt32Ty(Context)
Definition at line 67 of file NVVMIntrRange.cpp.
Referenced by llvm::Module::addModuleFlag(), llvm::buildEnqueueKernel(), callAppendArgs(), callAppendStringN(), llvm::ShuffleVectorInst::convertShuffleMaskForBitcode(), llvm::MDBuilder::createBranchWeights(), llvm::emitAMDGPUPrintfCall(), llvm::AMDGPU::HSAMD::MetadataStreamerMsgPackV5::emitHiddenKernelArgs(), llvm::ARMTargetLowering::emitStoreConditional(), llvm::expandDivisionUpTo32Bits(), llvm::expandRemainderUpTo32Bits(), llvm::SanitizerStatReport::finish(), llvm::OpenMPIRBuilder::getKernelArgsVector(), llvm::offloading::getOffloadingEntryInitializer(), getOffsetFromIndices(), instCombineSVESDIV(), lowerLoadRelative(), llvm::KCFIPass::run(), simplifyRelativeLoad(), splitGlobal(), llvm::UpgradeModuleFlags(), validExtractValueIndex(), validInsertValueIndex(), and validShuffleVectorIndex().
LowAndHigh
Metadata* LowAndHigh[]
Initial value:
= {
      ConstantAsMetadata::get(ConstantInt::get(Int32Ty, Low)),
      ConstantAsMetadata::get(ConstantInt::get(Int32Ty, High))}
Definition at line 68 of file NVVMIntrRange.cpp.
Referenced by foldCtpop(), and foldCttzCtlz().
NVVMIntrRangeSM
cl::opt< unsigned > NVVMIntrRangeSM("nvvm-intr-range-sm", cl::init(20), cl::Hidden, cl::desc("SM variant")) ("nvvm-intr-range-sm" , cl::init(20) , cl::Hidden , cl::desc("SM variant")) static
true
return true
Definition at line 72 of file NVVMIntrRange.cpp.