LLVM: lib/DebugInfo/GSYM/ObjectFileTransformer.cpp File Reference
ObjectFileTransformer.cpp File Reference
#include <unordered_set>
#include "llvm/Object/ELFObjectFile.h"
#include "llvm/Object/MachOUniversal.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/DebugInfo/GSYM/ObjectFileTransformer.h"
#include "llvm/DebugInfo/GSYM/GsymCreator.h"
Functions
static std::vector< uint8_t > getUUID (const object::ObjectFile &Obj)
Variables
constexpr uint32_t NT_GNU_BUILD_ID_TAG = 0x03
Function Documentation
getUUID()
static std::vector< uint8_t > getUUID (const object::ObjectFile & Obj) static
Definition at line 25 of file ObjectFileTransformer.cpp.
References llvm::alignTo(), llvm::consumeError(), llvm::ArrayRef< T >::data(), llvm::StringRef::data(), E, llvm::ArrayRef< T >::empty(), llvm::StringRef::empty(), llvm::DataExtractor::getBytes(), llvm::DataExtractor::getFixedLengthString(), llvm::DataExtractor::getU32(), llvm::Triple::isLittleEndian(), llvm::object::ObjectFile::makeTriple(), Name, llvm::XCOFF::NameSize, NT_GNU_BUILD_ID_TAG, llvm::Offset, Ptr, llvm::object::ObjectFile::sections(), llvm::ArrayRef< T >::size(), llvm::StringRef::size(), and llvm::Expected< T >::takeError().
Referenced by llvm::gsym::ObjectFileTransformer::convert().
Variable Documentation
NT_GNU_BUILD_ID_TAG
constexpr uint32_t NT_GNU_BUILD_ID_TAG = 0x03 constexpr
Definition at line 23 of file ObjectFileTransformer.cpp.
Referenced by getUUID().