LLVM: lib/Target/DirectX/DirectXIRPasses/PointerTypeAnalysis.cpp File Reference
PointerTypeAnalysis.cpp File Reference
#include "PointerTypeAnalysis.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
Functions
static Type * classifyConstantWithOpaquePtr (const Constant *C, PointerTypeMap &Map)
static void classifyGlobalCtorPointerType (const GlobalVariable &GV, PointerTypeMap &Map)
Function Documentation
classifyConstantWithOpaquePtr()
static Type * classifyConstantWithOpaquePtr (const Constant * C, PointerTypeMap & Map) static
Definition at line 120 of file PointerTypeAnalysis.cpp.
References assert(), llvm::CallingConv::C, classifyConstantWithOpaquePtr(), llvm::SmallVectorImpl< T >::emplace_back(), F, llvm::StructType::get(), llvm::TypedPointerType::get(), llvm::Type::getInt8Ty(), and I.
Referenced by classifyConstantWithOpaquePtr(), and classifyGlobalCtorPointerType().
classifyGlobalCtorPointerType()
static void classifyGlobalCtorPointerType (const GlobalVariable & GV, PointerTypeMap & Map) static
Definition at line 178 of file PointerTypeAnalysis.cpp.
References classifyConstantWithOpaquePtr(), llvm::TypedPointerType::get(), llvm::GlobalVariable::getInitializer(), llvm::Type::getPointerAddressSpace(), and llvm::GlobalValue::getType().
Referenced by llvm::dxil::PointerTypeAnalysis::run().