LLVM: lib/Target/PowerPC/GISel/PPCInstructionSelector.cpp File Reference
PPCInstructionSelector.cpp File Reference
This file implements the targeting of the InstructionSelector class for PowerPC.
#include "PPC.h"
#include "PPCInstrInfo.h"
#include "PPCMachineFunctionInfo.h"
#include "PPCRegisterBankInfo.h"
#include "PPCSubtarget.h"
#include "PPCTargetMachine.h"
#include "llvm/CodeGen/GlobalISel/GIMatchTableExecutorImpl.h"
#include "llvm/CodeGen/GlobalISel/GenericMachineInstrs.h"
#include "llvm/CodeGen/GlobalISel/InstructionSelector.h"
#include "llvm/CodeGen/GlobalISel/MachineIRBuilder.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/IR/IntrinsicsPowerPC.h"
#include "llvm/Support/Debug.h"
#include "PPCGenGlobalISel.inc"
Namespaces
namespace llvm
This is an optimization pass for GlobalISel generic memory operations.
Macros
#define DEBUG_TYPE "ppc-gisel"
#define GET_GLOBALISEL_PREDICATE_BITSET
#define GET_GLOBALISEL_PREDICATES_DECL
#define GET_GLOBALISEL_TEMPORARIES_DECL
#define GET_GLOBALISEL_IMPL
#define GET_GLOBALISEL_PREDICATES_INIT
#define GET_GLOBALISEL_TEMPORARIES_INIT
Functions
static bool selectCopy (MachineInstr &I, const TargetInstrInfo &TII, MachineRegisterInfo &MRI, const TargetRegisterInfo &TRI, const RegisterBankInfo &RBI)
static unsigned selectLoadStoreOp (unsigned GenericOpc, unsigned RegBankID, unsigned OpSize)
static uint32_t findContiguousZerosAtLeast (uint64_t Imm, unsigned Num)
InstructionSelector * llvm::createPPCInstructionSelector (const PPCTargetMachine &TM, const PPCSubtarget &Subtarget, const PPCRegisterBankInfo &RBI)
Detailed Description
This file implements the targeting of the InstructionSelector class for PowerPC.
Definition in file PPCInstructionSelector.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "ppc-gisel"
Definition at line 28 of file PPCInstructionSelector.cpp.
GET_GLOBALISEL_IMPL
#define GET_GLOBALISEL_IMPL
Definition at line 85 of file PPCInstructionSelector.cpp.
GET_GLOBALISEL_PREDICATE_BITSET
#define GET_GLOBALISEL_PREDICATE_BITSET
Definition at line 34 of file PPCInstructionSelector.cpp.
GET_GLOBALISEL_PREDICATES_DECL
#define GET_GLOBALISEL_PREDICATES_DECL
Definition at line 74 of file PPCInstructionSelector.cpp.
GET_GLOBALISEL_PREDICATES_INIT
#define GET_GLOBALISEL_PREDICATES_INIT
GET_GLOBALISEL_TEMPORARIES_DECL
#define GET_GLOBALISEL_TEMPORARIES_DECL
Definition at line 78 of file PPCInstructionSelector.cpp.
GET_GLOBALISEL_TEMPORARIES_INIT
#define GET_GLOBALISEL_TEMPORARIES_INIT
Function Documentation
findContiguousZerosAtLeast()
static uint32_t findContiguousZerosAtLeast (uint64_t Imm, unsigned Num) static
Definition at line 277 of file PPCInstructionSelector.cpp.
References llvm::Hi_32(), and llvm::Lo_32().
selectCopy()
static bool selectCopy (MachineInstr & I, const TargetInstrInfo & TII, MachineRegisterInfo & MRI, const TargetRegisterInfo & TRI, const RegisterBankInfo & RBI) static
Definition at line 130 of file PPCInstructionSelector.cpp.
References llvm::RegisterBankInfo::constrainGenericRegister(), llvm::dbgs(), llvm::RegisterBankInfo::getRegBank(), getRegClass(), I, llvm::Register::isPhysical(), LLVM_DEBUG, MRI, TII, and TRI.
selectLoadStoreOp()
static unsigned selectLoadStoreOp (unsigned GenericOpc, unsigned RegBankID, unsigned OpSize) static
Definition at line 154 of file PPCInstructionSelector.cpp.
References llvm_unreachable.