LLVM: lib/CodeGen/RegAllocPriorityAdvisor.cpp File Reference
RegAllocPriorityAdvisor.cpp File Reference
#include "RegAllocPriorityAdvisor.h"
#include "RegAllocGreedy.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
Functions
INITIALIZE_PASS (RegAllocPriorityAdvisorAnalysis, "regalloc-priority", "Regalloc priority policy", false, true) namespace
Variables
static cl::opt< RegAllocPriorityAdvisorAnalysis::AdvisorMode > Mode ("regalloc-enable-priority-advisor", cl::Hidden, cl::init(RegAllocPriorityAdvisorAnalysis::AdvisorMode::Default), cl::desc("Enable regalloc advisor mode"), cl::values(clEnumValN(RegAllocPriorityAdvisorAnalysis::AdvisorMode::Default, "default", "Default"), clEnumValN(RegAllocPriorityAdvisorAnalysis::AdvisorMode::Release, "release", "precompiled"), clEnumValN(RegAllocPriorityAdvisorAnalysis::AdvisorMode::Development, "development", "for training")))
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RegAllocPriorityAdvisorAnalysis , "regalloc-priority" , "Regalloc priority policy" , false , true)
Definition at line 36 of file RegAllocPriorityAdvisor.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::RegAllocPriorityAdvisorAnalysis::Default, llvm::Pass::doInitialization(), llvm::RegAllocPriorityAdvisorAnalysis::getAdvisor(), llvm::RegAllocPriorityAdvisorAnalysis::getAnalysisUsage(), and RA.
Variable Documentation
Mode
cl::opt< RegAllocPriorityAdvisorAnalysis::AdvisorMode > Mode("regalloc-enable-priority-advisor", cl::Hidden, cl::init(RegAllocPriorityAdvisorAnalysis::AdvisorMode::Default), cl::desc("Enable regalloc advisor mode"), cl::values(clEnumValN(RegAllocPriorityAdvisorAnalysis::AdvisorMode::Default, "default", "Default"), clEnumValN(RegAllocPriorityAdvisorAnalysis::AdvisorMode::Release, "release", "precompiled"), clEnumValN(RegAllocPriorityAdvisorAnalysis::AdvisorMode::Development, "development", "for training"))) ("regalloc-enable-priority-advisor" , cl::Hidden , cl::init(RegAllocPriorityAdvisorAnalysis::AdvisorMode::Default) , cl::desc("Enable regalloc advisor mode") , cl::values(clEnumValN(RegAllocPriorityAdvisorAnalysis::AdvisorMode::Default, "default", "Default"), clEnumValN(RegAllocPriorityAdvisorAnalysis::AdvisorMode::Release, "release", "precompiled"), clEnumValN(RegAllocPriorityAdvisorAnalysis::AdvisorMode::Development, "development", "for training"))) static
Referenced by llvm::callDefaultCtor< RegAllocPriorityAdvisorAnalysis >().