LLVM: lib/Support/RISCVISAInfo.cpp File Reference
RISCVISAInfo.cpp File Reference
#include "llvm/Support/RISCVISAInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/raw_ostream.h"
#include <array>
#include <atomic>
#include <optional>
#include <string>
#include <vector>
Classes
struct ImpliedExtsEntry
struct CombinedExtsEntry
Enumerations
enum RankFlags { RF_Z_EXTENSION = 1 << 6 , RF_S_EXTENSION = 1 << 7 , RF_X_EXTENSION = 1 << 8 }
Functions
static void verifyTables ()
static void PrintExtension (StringRef Name, StringRef Version, StringRef Description)
static bool stripExperimentalPrefix (StringRef &Ext)
static size_t findLastNonVersionCharacter (StringRef Ext)
static std::optional< RISCVISAInfo::ExtensionVersion > findDefaultVersion (StringRef ExtName)
static StringRef getExtensionTypeDesc (StringRef Ext)
static StringRef getExtensionType (StringRef Ext)
static std::optional< RISCVISAInfo::ExtensionVersion > isExperimentalExtension (StringRef Ext)
static unsigned singleLetterExtensionRank (char Ext)
static unsigned getExtensionRank (const std::string &ExtName)
static Error getExtensionVersion (StringRef Ext, StringRef In, unsigned &Major, unsigned &Minor, unsigned &ConsumeLength, bool EnableExperimentalExtension, bool ExperimentalExtensionVersionCheck)
Variables
static constexpr StringLiteral AllStdExts = "mafdqlcbkjtpvnh"
static const char * RISCVGImplications []
static const RISCVSupportedExtension SupportedExtensions []
static const RISCVSupportedExtension SupportedExperimentalExtensions []
static const char * ImpliedExtsD [] = {"f"}
static const char * ImpliedExtsF [] = {"zicsr"}
static const char * ImpliedExtsV [] = {"zvl128b", "zve64d"}
static const char * ImpliedExtsXTHeadVdot [] = {"v"}
static const char * ImpliedExtsXSfvcp [] = {"zve32x"}
static const char * ImpliedExtsXSfvfnrclipxfqf [] = {"zve32f"}
static const char * ImpliedExtsXSfvfwmaccqqq [] = {"zvfbfmin"}
static const char * ImpliedExtsXSfvqmaccdod [] = {"zve32x"}
static const char * ImpliedExtsXSfvqmaccqoq [] = {"zve32x"}
static const char * ImpliedExtsZacas [] = {"a"}
static const char * ImpliedExtsZcb [] = {"zca"}
static const char * ImpliedExtsZcd [] = {"d", "zca"}
static const char * ImpliedExtsZce [] = {"zcb", "zcmp", "zcmt"}
static const char * ImpliedExtsZcf [] = {"f", "zca"}
static const char * ImpliedExtsZcmop [] = {"zca"}
static const char * ImpliedExtsZcmp [] = {"zca"}
static const char * ImpliedExtsZcmt [] = {"zca", "zicsr"}
static const char * ImpliedExtsZdinx [] = {"zfinx"}
static const char * ImpliedExtsZfa [] = {"f"}
static const char * ImpliedExtsZfbfmin [] = {"f"}
static const char * ImpliedExtsZfh [] = {"zfhmin"}
static const char * ImpliedExtsZfhmin [] = {"f"}
static const char * ImpliedExtsZfinx [] = {"zicsr"}
static const char * ImpliedExtsZhinx [] = {"zhinxmin"}
static const char * ImpliedExtsZhinxmin [] = {"zfinx"}
static const char * ImpliedExtsZicntr [] = {"zicsr"}
static const char * ImpliedExtsZicfiss [] = {"zicsr", "zimop"}
static const char * ImpliedExtsZihpm [] = {"zicsr"}
static const char * ImpliedExtsZk [] = {"zkn", "zkt", "zkr"}
static const char * ImpliedExtsZkn []
static const char * ImpliedExtsZks [] = {"zbkb", "zbkc", "zbkx", "zksed", "zksh"}
static const char * ImpliedExtsZvbb [] = {"zvkb"}
static const char * ImpliedExtsZve32f [] = {"zve32x", "f"}
static const char * ImpliedExtsZve32x [] = {"zvl32b", "zicsr"}
static const char * ImpliedExtsZve64d [] = {"zve64f", "d"}
static const char * ImpliedExtsZve64f [] = {"zve64x", "zve32f"}
static const char * ImpliedExtsZve64x [] = {"zve32x", "zvl64b"}
static const char * ImpliedExtsZvfbfmin [] = {"zve32f"}
static const char * ImpliedExtsZvfbfwma [] = {"zvfbfmin", "zfbfmin"}
static const char * ImpliedExtsZvfh [] = {"zvfhmin", "zfhmin"}
static const char * ImpliedExtsZvfhmin [] = {"zve32f"}
static const char * ImpliedExtsZvkn [] = {"zvkb", "zvkned", "zvknhb", "zvkt"}
static const char * ImpliedExtsZvknc [] = {"zvbc", "zvkn"}
static const char * ImpliedExtsZvkng [] = {"zvkg", "zvkn"}
static const char * ImpliedExtsZvknhb [] = {"zve64x"}
static const char * ImpliedExtsZvks [] = {"zvkb", "zvksed", "zvksh", "zvkt"}
static const char * ImpliedExtsZvksc [] = {"zvbc", "zvks"}
static const char * ImpliedExtsZvksg [] = {"zvkg", "zvks"}
static const char * ImpliedExtsZvl1024b [] = {"zvl512b"}
static const char * ImpliedExtsZvl128b [] = {"zvl64b"}
static const char * ImpliedExtsZvl16384b [] = {"zvl8192b"}
static const char * ImpliedExtsZvl2048b [] = {"zvl1024b"}
static const char * ImpliedExtsZvl256b [] = {"zvl128b"}
static const char * ImpliedExtsZvl32768b [] = {"zvl16384b"}
static const char * ImpliedExtsZvl4096b [] = {"zvl2048b"}
static const char * ImpliedExtsZvl512b [] = {"zvl256b"}
static const char * ImpliedExtsZvl64b [] = {"zvl32b"}
static const char * ImpliedExtsZvl65536b [] = {"zvl32768b"}
static const char * ImpliedExtsZvl8192b [] = {"zvl4096b"}
static constexpr ImpliedExtsEntry ImpliedExts []
static constexpr CombinedExtsEntry CombineIntoExts []
Enumeration Type Documentation
RankFlags
enum RankFlags
Enumerator
RF_Z_EXTENSION
RF_S_EXTENSION
RF_X_EXTENSION
Definition at line 407 of file RISCVISAInfo.cpp.
Function Documentation
findDefaultVersion()
static std::optional< RISCVISAInfo::ExtensionVersion > findDefaultVersion (StringRef ExtName) static
Definition at line 299 of file RISCVISAInfo.cpp.
References I, llvm::lower_bound(), SupportedExperimentalExtensions, and SupportedExtensions.
Referenced by getExtensionVersion(), and llvm::RISCVISAInfo::parseArchString().
findLastNonVersionCharacter()
static size_t findLastNonVersionCharacter (StringRef Ext) static
Definition at line 272 of file RISCVISAInfo.cpp.
References assert(), and isDigit().
Referenced by llvm::RISCVISAInfo::getTargetFeatureForExtension(), llvm::RISCVISAInfo::isSupportedExtensionWithVersion(), and llvm::RISCVISAInfo::parseArchString().
getExtensionRank()
static unsigned getExtensionRank (const std::string & ExtName) static
Definition at line 435 of file RISCVISAInfo.cpp.
References assert(), RF_S_EXTENSION, RF_X_EXTENSION, RF_Z_EXTENSION, and singleLetterExtensionRank().
Referenced by llvm::RISCVISAInfo::compareExtension().
getExtensionType()
static StringRef getExtensionType (StringRef Ext) static
Definition at line 329 of file RISCVISAInfo.cpp.
Referenced by llvm::RISCVISAInfo::parseArchString(), and performMemPairCombine().
getExtensionTypeDesc()
static StringRef getExtensionTypeDesc (StringRef Ext) static
Definition at line 319 of file RISCVISAInfo.cpp.
Referenced by llvm::RISCVISAInfo::parseArchString().
getExtensionVersion()
static Error getExtensionVersion (StringRef Ext, StringRef In, unsigned & Major, unsigned & Minor, unsigned & ConsumeLength, bool EnableExperimentalExtension, bool ExperimentalExtensionVersionCheck) static
Definition at line 507 of file RISCVISAInfo.cpp.
References llvm::createStringError(), llvm::StringRef::empty(), findDefaultVersion(), llvm::StringRef::getAsInteger(), llvm::invalid_argument, isDigit(), isExperimentalExtension(), llvm::RISCVISAInfo::isSupportedExtension(), llvm::StringRef::size(), llvm::StringRef::str(), and llvm::Error::success().
Referenced by llvm::RISCVISAInfo::isSupportedExtensionWithVersion(), and llvm::RISCVISAInfo::parseArchString().
isExperimentalExtension()
static std::optional< RISCVISAInfo::ExtensionVersion > isExperimentalExtension (StringRef Ext) static
Definition at line 340 of file RISCVISAInfo.cpp.
References I, llvm::lower_bound(), and SupportedExperimentalExtensions.
Referenced by getExtensionVersion(), llvm::RISCVISAInfo::getTargetFeatureForExtension(), and llvm::RISCVISAInfo::toFeatures().
PrintExtension()
static void PrintExtension (StringRef Name, StringRef Version, StringRef Description) static
Definition at line 225 of file RISCVISAInfo.cpp.
References llvm::StringRef::empty(), llvm::raw_ostream::indent(), llvm::left_justify(), Name, and llvm::outs().
Referenced by llvm::riscvExtensionsHelp().
singleLetterExtensionRank()
static unsigned singleLetterExtensionRank (char Ext) static
Definition at line 415 of file RISCVISAInfo.cpp.
References AllStdExts, assert(), llvm::StringRef::find(), llvm::StringRef::npos, and llvm::StringRef::size().
Referenced by getExtensionRank().
stripExperimentalPrefix()
static bool stripExperimentalPrefix (StringRef & Ext) static
Definition at line 261 of file RISCVISAInfo.cpp.
Referenced by llvm::RISCVISAInfo::hasExtension(), llvm::RISCVISAInfo::isSupportedExtensionFeature(), and llvm::RISCVISAInfo::parseFeatures().
verifyTables()
static void verifyTables () static
Definition at line 212 of file RISCVISAInfo.cpp.
References assert(), llvm::is_sorted(), SupportedExperimentalExtensions, and SupportedExtensions.
Referenced by llvm::RISCVISAInfo::isSupportedExtension().
Variable Documentation
AllStdExts
constexpr StringLiteral AllStdExts = "mafdqlcbkjtpvnh" static constexpr
Definition at line 40 of file RISCVISAInfo.cpp.
Referenced by llvm::RISCVISAInfo::parseArchString(), and singleLetterExtensionRank().
CombineIntoExts
constexpr CombinedExtsEntry CombineIntoExts[] static constexpr
Initial value:
= {
    {{"zk"}, {ImpliedExtsZk}},
    {{"zkn"}, {ImpliedExtsZkn}},
    {{"zks"}, {ImpliedExtsZks}},
    {{"zvkn"}, {ImpliedExtsZvkn}},
    {{"zvknc"}, {ImpliedExtsZvknc}},
    {{"zvkng"}, {ImpliedExtsZvkng}},
    {{"zvks"}, {ImpliedExtsZvks}},
    {{"zvksc"}, {ImpliedExtsZvksc}},
    {{"zvksg"}, {ImpliedExtsZvksg}},
}
Definition at line 1184 of file RISCVISAInfo.cpp.
ImpliedExts
constexpr ImpliedExtsEntry ImpliedExts[] static constexpr
Definition at line 1074 of file RISCVISAInfo.cpp.
Referenced by llvm::AArch64::CpuInfo::getImpliedExtensions().
ImpliedExtsD
const char* ImpliedExtsD[] = {"f"} static
Definition at line 1001 of file RISCVISAInfo.cpp.
ImpliedExtsF
const char* ImpliedExtsF[] = {"zicsr"} static
Definition at line 1002 of file RISCVISAInfo.cpp.
ImpliedExtsV
const char* ImpliedExtsV[] = {"zvl128b", "zve64d"} static
Definition at line 1003 of file RISCVISAInfo.cpp.
ImpliedExtsXSfvcp
const char* ImpliedExtsXSfvcp[] = {"zve32x"} static
Definition at line 1005 of file RISCVISAInfo.cpp.
ImpliedExtsXSfvfnrclipxfqf
const char* ImpliedExtsXSfvfnrclipxfqf[] = {"zve32f"} static
Definition at line 1006 of file RISCVISAInfo.cpp.
ImpliedExtsXSfvfwmaccqqq
const char* ImpliedExtsXSfvfwmaccqqq[] = {"zvfbfmin"} static
Definition at line 1007 of file RISCVISAInfo.cpp.
ImpliedExtsXSfvqmaccdod
const char* ImpliedExtsXSfvqmaccdod[] = {"zve32x"} static
Definition at line 1008 of file RISCVISAInfo.cpp.
ImpliedExtsXSfvqmaccqoq
const char* ImpliedExtsXSfvqmaccqoq[] = {"zve32x"} static
Definition at line 1009 of file RISCVISAInfo.cpp.
ImpliedExtsXTHeadVdot
const char* ImpliedExtsXTHeadVdot[] = {"v"} static
Definition at line 1004 of file RISCVISAInfo.cpp.
ImpliedExtsZacas
const char* ImpliedExtsZacas[] = {"a"} static
Definition at line 1010 of file RISCVISAInfo.cpp.
ImpliedExtsZcb
const char* ImpliedExtsZcb[] = {"zca"} static
Definition at line 1011 of file RISCVISAInfo.cpp.
ImpliedExtsZcd
const char* ImpliedExtsZcd[] = {"d", "zca"} static
Definition at line 1012 of file RISCVISAInfo.cpp.
ImpliedExtsZce
const char* ImpliedExtsZce[] = {"zcb", "zcmp", "zcmt"} static
Definition at line 1013 of file RISCVISAInfo.cpp.
ImpliedExtsZcf
const char* ImpliedExtsZcf[] = {"f", "zca"} static
Definition at line 1014 of file RISCVISAInfo.cpp.
ImpliedExtsZcmop
const char* ImpliedExtsZcmop[] = {"zca"} static
Definition at line 1015 of file RISCVISAInfo.cpp.
ImpliedExtsZcmp
const char* ImpliedExtsZcmp[] = {"zca"} static
Definition at line 1016 of file RISCVISAInfo.cpp.
ImpliedExtsZcmt
const char* ImpliedExtsZcmt[] = {"zca", "zicsr"} static
Definition at line 1017 of file RISCVISAInfo.cpp.
ImpliedExtsZdinx
const char* ImpliedExtsZdinx[] = {"zfinx"} static
Definition at line 1018 of file RISCVISAInfo.cpp.
ImpliedExtsZfa
const char* ImpliedExtsZfa[] = {"f"} static
Definition at line 1019 of file RISCVISAInfo.cpp.
ImpliedExtsZfbfmin
const char* ImpliedExtsZfbfmin[] = {"f"} static
Definition at line 1020 of file RISCVISAInfo.cpp.
ImpliedExtsZfh
const char* ImpliedExtsZfh[] = {"zfhmin"} static
Definition at line 1021 of file RISCVISAInfo.cpp.
ImpliedExtsZfhmin
const char* ImpliedExtsZfhmin[] = {"f"} static
Definition at line 1022 of file RISCVISAInfo.cpp.
ImpliedExtsZfinx
const char* ImpliedExtsZfinx[] = {"zicsr"} static
Definition at line 1023 of file RISCVISAInfo.cpp.
ImpliedExtsZhinx
const char* ImpliedExtsZhinx[] = {"zhinxmin"} static
Definition at line 1024 of file RISCVISAInfo.cpp.
ImpliedExtsZhinxmin
const char* ImpliedExtsZhinxmin[] = {"zfinx"} static
Definition at line 1025 of file RISCVISAInfo.cpp.
ImpliedExtsZicfiss
const char* ImpliedExtsZicfiss[] = {"zicsr", "zimop"} static
Definition at line 1027 of file RISCVISAInfo.cpp.
ImpliedExtsZicntr
const char* ImpliedExtsZicntr[] = {"zicsr"} static
Definition at line 1026 of file RISCVISAInfo.cpp.
ImpliedExtsZihpm
const char* ImpliedExtsZihpm[] = {"zicsr"} static
Definition at line 1028 of file RISCVISAInfo.cpp.
ImpliedExtsZk
const char* ImpliedExtsZk[] = {"zkn", "zkt", "zkr"} static
Definition at line 1029 of file RISCVISAInfo.cpp.
ImpliedExtsZkn
const char* ImpliedExtsZkn[] static
Initial value:
= {"zbkb", "zbkc", "zbkx",
                                       "zkne", "zknd", "zknh"}
Definition at line 1030 of file RISCVISAInfo.cpp.
ImpliedExtsZks
const char* ImpliedExtsZks[] = {"zbkb", "zbkc", "zbkx", "zksed", "zksh"} static
Definition at line 1032 of file RISCVISAInfo.cpp.
ImpliedExtsZvbb
const char* ImpliedExtsZvbb[] = {"zvkb"} static
Definition at line 1033 of file RISCVISAInfo.cpp.
ImpliedExtsZve32f
const char* ImpliedExtsZve32f[] = {"zve32x", "f"} static
Definition at line 1034 of file RISCVISAInfo.cpp.
ImpliedExtsZve32x
const char* ImpliedExtsZve32x[] = {"zvl32b", "zicsr"} static
Definition at line 1035 of file RISCVISAInfo.cpp.
ImpliedExtsZve64d
const char* ImpliedExtsZve64d[] = {"zve64f", "d"} static
Definition at line 1036 of file RISCVISAInfo.cpp.
ImpliedExtsZve64f
const char* ImpliedExtsZve64f[] = {"zve64x", "zve32f"} static
Definition at line 1037 of file RISCVISAInfo.cpp.
ImpliedExtsZve64x
const char* ImpliedExtsZve64x[] = {"zve32x", "zvl64b"} static
Definition at line 1038 of file RISCVISAInfo.cpp.
ImpliedExtsZvfbfmin
const char* ImpliedExtsZvfbfmin[] = {"zve32f"} static
Definition at line 1039 of file RISCVISAInfo.cpp.
ImpliedExtsZvfbfwma
const char* ImpliedExtsZvfbfwma[] = {"zvfbfmin", "zfbfmin"} static
Definition at line 1040 of file RISCVISAInfo.cpp.
ImpliedExtsZvfh
const char* ImpliedExtsZvfh[] = {"zvfhmin", "zfhmin"} static
Definition at line 1041 of file RISCVISAInfo.cpp.
ImpliedExtsZvfhmin
const char* ImpliedExtsZvfhmin[] = {"zve32f"} static
Definition at line 1042 of file RISCVISAInfo.cpp.
ImpliedExtsZvkn
const char* ImpliedExtsZvkn[] = {"zvkb", "zvkned", "zvknhb", "zvkt"} static
Definition at line 1043 of file RISCVISAInfo.cpp.
ImpliedExtsZvknc
const char* ImpliedExtsZvknc[] = {"zvbc", "zvkn"} static
Definition at line 1044 of file RISCVISAInfo.cpp.
ImpliedExtsZvkng
const char* ImpliedExtsZvkng[] = {"zvkg", "zvkn"} static
Definition at line 1045 of file RISCVISAInfo.cpp.
ImpliedExtsZvknhb
const char* ImpliedExtsZvknhb[] = {"zve64x"} static
Definition at line 1046 of file RISCVISAInfo.cpp.
ImpliedExtsZvks
const char* ImpliedExtsZvks[] = {"zvkb", "zvksed", "zvksh", "zvkt"} static
Definition at line 1047 of file RISCVISAInfo.cpp.
ImpliedExtsZvksc
const char* ImpliedExtsZvksc[] = {"zvbc", "zvks"} static
Definition at line 1048 of file RISCVISAInfo.cpp.
ImpliedExtsZvksg
const char* ImpliedExtsZvksg[] = {"zvkg", "zvks"} static
Definition at line 1049 of file RISCVISAInfo.cpp.
ImpliedExtsZvl1024b
const char* ImpliedExtsZvl1024b[] = {"zvl512b"} static
Definition at line 1050 of file RISCVISAInfo.cpp.
ImpliedExtsZvl128b
const char* ImpliedExtsZvl128b[] = {"zvl64b"} static
Definition at line 1051 of file RISCVISAInfo.cpp.
ImpliedExtsZvl16384b
const char* ImpliedExtsZvl16384b[] = {"zvl8192b"} static
Definition at line 1052 of file RISCVISAInfo.cpp.
ImpliedExtsZvl2048b
const char* ImpliedExtsZvl2048b[] = {"zvl1024b"} static
Definition at line 1053 of file RISCVISAInfo.cpp.
ImpliedExtsZvl256b
const char* ImpliedExtsZvl256b[] = {"zvl128b"} static
Definition at line 1054 of file RISCVISAInfo.cpp.
ImpliedExtsZvl32768b
const char* ImpliedExtsZvl32768b[] = {"zvl16384b"} static
Definition at line 1055 of file RISCVISAInfo.cpp.
ImpliedExtsZvl4096b
const char* ImpliedExtsZvl4096b[] = {"zvl2048b"} static
Definition at line 1056 of file RISCVISAInfo.cpp.
ImpliedExtsZvl512b
const char* ImpliedExtsZvl512b[] = {"zvl256b"} static
Definition at line 1057 of file RISCVISAInfo.cpp.
ImpliedExtsZvl64b
const char* ImpliedExtsZvl64b[] = {"zvl32b"} static
Definition at line 1058 of file RISCVISAInfo.cpp.
ImpliedExtsZvl65536b
const char* ImpliedExtsZvl65536b[] = {"zvl32768b"} static
Definition at line 1059 of file RISCVISAInfo.cpp.
ImpliedExtsZvl8192b
const char* ImpliedExtsZvl8192b[] = {"zvl4096b"} static
Definition at line 1060 of file RISCVISAInfo.cpp.
RISCVGImplications
const char* RISCVGImplications[] static
Initial value:
= {
  "i", "m", "a", "f", "d", "zicsr", "zifencei"
}
Definition at line 42 of file RISCVISAInfo.cpp.
Referenced by llvm::RISCVISAInfo::parseArchString().
SupportedExperimentalExtensions
const RISCVSupportedExtension SupportedExperimentalExtensions[] static
Initial value:
= {
    {"zacas", {1, 0}},
    {"zcmop", {0, 2}},
    {"zfbfmin", {1, 0}},
    {"zicfilp", {0, 4}},
    {"zicfiss", {0, 4}},
    {"zimop", {0, 1}},
    {"ztso", {0, 1}},
    {"zvfbfmin", {1, 0}},
    {"zvfbfwma", {1, 0}},
}
Definition at line 194 of file RISCVISAInfo.cpp.
Referenced by findDefaultVersion(), isExperimentalExtension(), llvm::RISCVISAInfo::isSupportedExtension(), llvm::RISCVISAInfo::isSupportedExtensionFeature(), llvm::RISCVISAInfo::parseFeatures(), llvm::riscvExtensionsHelp(), llvm::RISCVISAInfo::toFeatures(), and verifyTables().
SupportedExtensions
const RISCVSupportedExtension SupportedExtensions[] static
Definition at line 47 of file RISCVISAInfo.cpp.
Referenced by findDefaultVersion(), llvm::RISCVISAInfo::isSupportedExtension(), llvm::RISCVISAInfo::isSupportedExtensionFeature(), llvm::RISCVISAInfo::parseFeatures(), llvm::riscvExtensionsHelp(), llvm::RISCVISAInfo::toFeatures(), and verifyTables().