LLVM: lib/Target/RISCV/RISCVOptWInstrs.cpp File Reference
RISCVOptWInstrs.cpp File Reference
#include "RISCV.h"
#include "RISCVMachineFunctionInfo.h"
#include "RISCVSubtarget.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
Macros
#define DEBUG_TYPE "riscv-opt-w-instrs"
#define RISCV_OPT_W_INSTRS_NAME "RISC-V Optimize W Instructions"
Functions
STATISTIC (NumRemovedSExtW, "Number of removed sign-extensions")
STATISTIC (NumTransformedToWInstrs, "Number of instructions transformed to W-ops")
INITIALIZE_PASS (RISCVOptWInstrs, DEBUG_TYPE, RISCV_OPT_W_INSTRS_NAME, false, false) FunctionPass *llvm
static bool vectorPseudoHasAllNBitUsers (const MachineOperand &UserOp, unsigned Bits)
static bool hasAllNBitUsers (const MachineInstr &OrigMI, const RISCVSubtarget &ST, const MachineRegisterInfo &MRI, unsigned OrigBits)
static bool hasAllWUsers (const MachineInstr &OrigMI, const RISCVSubtarget &ST, const MachineRegisterInfo &MRI)
static bool isSignExtendingOpW (const MachineInstr &MI, const MachineRegisterInfo &MRI)
static bool isSignExtendedW (Register SrcReg, const RISCVSubtarget &ST, const MachineRegisterInfo &MRI, SmallPtrSetImpl< MachineInstr * > &FixableDef)
static unsigned getWOp (unsigned Opcode)
Variables
static cl::opt< bool > DisableSExtWRemoval ("riscv-disable-sextw-removal", cl::desc("Disable removal of sext.w"), cl::init(false), cl::Hidden)
static cl::opt< bool > DisableStripWSuffix ("riscv-disable-strip-w-suffix", cl::desc("Disable strip W suffix"), cl::init(false), cl::Hidden)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "riscv-opt-w-instrs"
Definition at line 36 of file RISCVOptWInstrs.cpp.
RISCV_OPT_W_INSTRS_NAME
#define RISCV_OPT_W_INSTRS_NAME "RISC-V Optimize W Instructions"
Definition at line 37 of file RISCVOptWInstrs.cpp.
Function Documentation
getWOp()
static unsigned getWOp (unsigned Opcode) static
Definition at line 601 of file RISCVOptWInstrs.cpp.
References llvm_unreachable.
hasAllNBitUsers()
static bool hasAllNBitUsers (const MachineInstr & OrigMI, const RISCVSubtarget & ST, const MachineRegisterInfo & MRI, unsigned OrigBits) static
Definition at line 108 of file RISCVOptWInstrs.cpp.
References llvm::bit_width(), llvm::SmallVectorBase< Size_T >::empty(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::SmallSet< T, N, C >::insert(), llvm::Register::isVirtual(), llvm::Log2_32(), MI, MRI, P, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and vectorPseudoHasAllNBitUsers().
Referenced by hasAllWUsers().
hasAllWUsers()
static bool hasAllWUsers (const MachineInstr & OrigMI, const RISCVSubtarget & ST, const MachineRegisterInfo & MRI) static
Definition at line 333 of file RISCVOptWInstrs.cpp.
References hasAllNBitUsers(), and MRI.
Referenced by isSignExtendedW().
INITIALIZE_PASS()
INITIALIZE_PASS (RISCVOptWInstrs , DEBUG_TYPE , RISCV_OPT_W_INSTRS_NAME , false , false)
Definition at line 75 of file RISCVOptWInstrs.cpp.
isSignExtendedW()
static bool isSignExtendedW (Register SrcReg, const RISCVSubtarget & ST, const MachineRegisterInfo & MRI, SmallPtrSetImpl< MachineInstr * > & FixableDef) static
Definition at line 384 of file RISCVOptWInstrs.cpp.
References B, llvm::BitWidth, D, E, llvm::SmallVectorBase< Size_T >::empty(), llvm::MachineFunction::front(), llvm::MachineOperand::getGlobal(), llvm::MachineFunction::getInfo(), getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), hasAllWUsers(), I, llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::MachineBasicBlock::instr_begin(), llvm::MachineInstr::isCall(), llvm::MachineOperand::isGlobal(), llvm::MachineRegisterInfo::isLiveIn(), llvm::MachineOperand::isReg(), llvm::RISCVMachineFunctionInfo::isSExt32Register(), isSignExtendingOpW(), llvm::Register::isVirtual(), MBB, MI, MRI, llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
isSignExtendingOpW()
static bool isSignExtendingOpW (const MachineInstr & MI, const MachineRegisterInfo & MRI) static
Definition at line 340 of file RISCVOptWInstrs.cpp.
References assert(), llvm::RISCVII::IsSignExtendingOpWMask, and MI.
Referenced by isSignExtendedW().
STATISTIC() [1/2]
STATISTIC (NumRemovedSExtW , "Number of removed sign-extensions")
STATISTIC() [2/2]
STATISTIC (NumTransformedToWInstrs , "Number of instructions transformed to W-ops")
vectorPseudoHasAllNBitUsers()
static bool vectorPseudoHasAllNBitUsers (const MachineOperand & UserOp, unsigned Bits) static
Definition at line 82 of file RISCVOptWInstrs.cpp.
References assert(), llvm::MachineOperand::getOperandNo(), llvm::MachineOperand::getParent(), llvm::RISCV::getRVVMCOpcode(), llvm::RISCVII::getSEWOpNum(), llvm::RISCV::getVectorLowDemandedScalarBits(), llvm::RISCVII::getVLOpNum(), llvm::RISCVII::hasSEWOp(), llvm::RISCVII::hasVLOp(), MI, and llvm::MCInstrDesc::TSFlags.
Referenced by hasAllNBitUsers().
Variable Documentation
DisableSExtWRemoval
cl::opt< bool > DisableSExtWRemoval("riscv-disable-sextw-removal", cl::desc("Disable removal of sext.w"), cl::init(false), cl::Hidden) ("riscv-disable-sextw-removal" , cl::desc("Disable removal of sext.w") , cl::init(false) , cl::Hidden) static
DisableStripWSuffix
cl::opt< bool > DisableStripWSuffix("riscv-disable-strip-w-suffix", cl::desc("Disable strip W suffix"), cl::init(false), cl::Hidden) ("riscv-disable-strip-w-suffix" , cl::desc("Disable strip W suffix") , cl::init(false) , cl::Hidden) static