LLVM: lib/Target/RISCV/RISCVPushPopOptimizer.cpp File Reference
RISCVPushPopOptimizer.cpp File Reference
#include "RISCVInstrInfo.h"
#include "RISCVMachineFunctionInfo.h"
Macros
#define RISCV_PUSH_POP_OPT_NAME "RISC-V Zcmp Push/Pop optimization pass"
Functions
INITIALIZE_PASS (RISCVPushPopOpt, "riscv-push-pop-opt", RISCV_PUSH_POP_OPT_NAME, false, false) static MachineBasicBlock
Macro Definition Documentation
RISCV_PUSH_POP_OPT_NAME
#define RISCV_PUSH_POP_OPT_NAME "RISC-V Zcmp Push/Pop optimization pass"
Definition at line 19 of file RISCVPushPopOptimizer.cpp.
Function Documentation
INITIALIZE_PASS()
INITIALIZE_PASS (RISCVPushPopOpt , "riscv-push-pop-opt" , RISCV_PUSH_POP_OPT_NAME , false , false)
Definition at line 45 of file RISCVPushPopOptimizer.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), MBB, MBBI, and llvm::next_nodbg().