LLVM: include/llvm/Demangle/StringViewExtras.h File Reference
StringViewExtras.h File Reference
#include "DemangleConfig.h"
#include <string_view>
Functions
DEMANGLE_NAMESPACE_BEGIN bool starts_with (std::string_view self, char C) noexcept
bool starts_with (std::string_view haystack, std::string_view needle) noexcept
Function Documentation
starts_with() [1/2]
bool starts_with (std::string_view haystack, std::string_view needle) inline noexcept
Definition at line 28 of file StringViewExtras.h.
References starts_with().
starts_with() [2/2]
DEMANGLE_NAMESPACE_BEGIN bool starts_with (std::string_view self, char C) inline noexcept
Definition at line 24 of file StringViewExtras.h.
References C, and starts_with().
Referenced by llvm::StringRef::consume_front(), AbstractManglingParser< Derived, Alloc >::consumeIf(), llvm::demangle(), llvm::dlangDemangle(), SpecialSubstitution::getBaseName(), llvm::sys::detail::getHostCPUNameForARM(), llvm::sys::detail::getHostCPUNameForRISCV(), llvm::sys::detail::getHostCPUNameForS390x(), AbstractManglingParser< Derived, Alloc >::OperatorInfo::getSymbol(), isDLangEncoding(), isItaniumEncoding(), isRustEncoding(), llvm::StringRef::LLVM_DEPRECATED(), llvm::makePostTransformationMetadata(), llvm::Triple::normalize(), AbstractManglingParser< Derived, Alloc >::parseQualifiedType(), AbstractManglingParser< Derived, Alloc >::parseSourceName(), llvm::sys::path::replace_path_prefix(), llvm::rustDemangle(), starts_with(), and llvm::sys::path::starts_with().