LLVM: llvm::HardwareLoopInfo Struct Reference
llvm::HardwareLoopInfo Struct Reference
Attributes of a target dependent hardware loop.
#include "llvm/Analysis/TargetTransformInfo.h"
Public Member Functions
HardwareLoopInfo ()=delete
HardwareLoopInfo (Loop *L)
bool isHardwareLoopCandidate (ScalarEvolution &SE, LoopInfo &LI, DominatorTree &DT, bool ForceNestedLoop=false, bool ForceHardwareLoopPHI=false)
bool canAnalyze (LoopInfo &LI)
Public Attributes
Loop * L = nullptr
BasicBlock * ExitBlock = nullptr
BranchInst * ExitBranch = nullptr
const SCEV * ExitCount = nullptr
IntegerType * CountType = nullptr
Value * LoopDecrement = nullptr
bool IsNestingLegal = false
bool CounterInReg = false
bool PerformEntryTest = false
Detailed Description
Attributes of a target dependent hardware loop.
Definition at line 97 of file TargetTransformInfo.h.
Constructor & Destructor Documentation
HardwareLoopInfo() [1/2]
llvm::HardwareLoopInfo::HardwareLoopInfo () delete
HardwareLoopInfo() [2/2]
HardwareLoopInfo::HardwareLoopInfo (Loop * L)
Definition at line 115 of file TargetTransformInfo.cpp.
References CountType, llvm::ConstantInt::get(), llvm::BasicBlock::getContext(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Type::getInt32Ty(), L, and LoopDecrement.
Member Function Documentation
canAnalyze()
bool HardwareLoopInfo::canAnalyze (LoopInfo & LI)
Definition at line 60 of file TargetTransformInfo.cpp.
References L, and llvm::LoopBlocksRPO::perform().
Referenced by llvm::PPCTTIImpl::canSaveCmp(), and llvm::ARMTTIImpl::preferPredicateOverEpilogue().
isHardwareLoopCandidate()
bool HardwareLoopInfo::isHardwareLoopCandidate (ScalarEvolution & SE, LoopInfo & LI, DominatorTree & DT, bool ForceNestedLoop = false, bool ForceHardwareLoopPHI = false)
Definition at line 123 of file TargetTransformInfo.cpp.
References llvm::LoopBase< BlockT, LoopT >::contains(), CounterInReg, CountType, llvm::DominatorTree::dominates(), ExitBlock, ExitBranch, ExitCount, ForceHardwareLoopPHI, ForceNestedLoop, llvm::IntegerType::getBitWidth(), llvm::ScalarEvolution::getExitCount(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor(), llvm::ScalarEvolution::getTypeSizeInBits(), llvm::ScalarEvolution::isLoopInvariant(), llvm::LoopBase< BlockT, LoopT >::isLoopLatch(), IsNestingLegal, L, and llvm::predecessors().
Referenced by llvm::PPCTTIImpl::canSaveCmp(), and llvm::ARMTTIImpl::preferPredicateOverEpilogue().
Member Data Documentation
CounterInReg
bool llvm::HardwareLoopInfo::CounterInReg = false
Definition at line 109 of file TargetTransformInfo.h.
Referenced by isHardwareLoopCandidate(), and llvm::ARMTTIImpl::isHardwareLoopProfitable().
CountType
IntegerType* llvm::HardwareLoopInfo::CountType = nullptr
Definition at line 104 of file TargetTransformInfo.h.
Referenced by HardwareLoopInfo(), isHardwareLoopCandidate(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), and llvm::PPCTTIImpl::isHardwareLoopProfitable().
ExitBlock
BasicBlock* llvm::HardwareLoopInfo::ExitBlock = nullptr
Definition at line 101 of file TargetTransformInfo.h.
Referenced by isHardwareLoopCandidate().
ExitBranch
BranchInst* llvm::HardwareLoopInfo::ExitBranch = nullptr
Definition at line 102 of file TargetTransformInfo.h.
Referenced by llvm::PPCTTIImpl::canSaveCmp(), and isHardwareLoopCandidate().
ExitCount
const SCEV* llvm::HardwareLoopInfo::ExitCount = nullptr
Definition at line 103 of file TargetTransformInfo.h.
Referenced by isHardwareLoopCandidate().
IsNestingLegal
bool llvm::HardwareLoopInfo::IsNestingLegal = false
Definition at line 107 of file TargetTransformInfo.h.
Referenced by isHardwareLoopCandidate(), and llvm::ARMTTIImpl::isHardwareLoopProfitable().
L
Loop* llvm::HardwareLoopInfo::L = nullptr
Definition at line 100 of file TargetTransformInfo.h.
Referenced by canAnalyze(), HardwareLoopInfo(), and isHardwareLoopCandidate().
LoopDecrement
Value* llvm::HardwareLoopInfo::LoopDecrement = nullptr
Definition at line 105 of file TargetTransformInfo.h.
Referenced by HardwareLoopInfo(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), and llvm::PPCTTIImpl::isHardwareLoopProfitable().
PerformEntryTest
bool llvm::HardwareLoopInfo::PerformEntryTest = false
Definition at line 111 of file TargetTransformInfo.h.
Referenced by llvm::ARMTTIImpl::isHardwareLoopProfitable().
The documentation for this struct was generated from the following files:
include/llvm/Analysis/TargetTransformInfo.h
lib/Analysis/TargetTransformInfo.cpp