LLVM: llvm::TargetTransformInfo::OperandValueInfo Struct Reference
llvm::TargetTransformInfo::OperandValueInfo Struct Reference
#include "llvm/Analysis/TargetTransformInfo.h"
Public Member Functions
bool isConstant () const
bool isUniform () const
bool isPowerOf2 () const
bool isNegatedPowerOf2 () const
OperandValueInfo getNoProps () const
Public Attributes
OperandValueKind Kind = OK_AnyValue
OperandValueProperties Properties = OP_None
Detailed Description
Definition at line 1068 of file TargetTransformInfo.h.
Member Function Documentation
getNoProps()
OperandValueInfo llvm::TargetTransformInfo::OperandValueInfo::getNoProps () const inline
Definition at line 1085 of file TargetTransformInfo.h.
References Kind, and llvm::TargetTransformInfo::OP_None.
Referenced by llvm::AArch64TTIImpl::getArithmeticInstrCost(), and llvm::X86TTIImpl::getArithmeticInstrCost().
isConstant()
bool llvm::TargetTransformInfo::OperandValueInfo::isConstant () const inline
Definition at line 1072 of file TargetTransformInfo.h.
References Kind, llvm::TargetTransformInfo::OK_NonUniformConstantValue, and llvm::TargetTransformInfo::OK_UniformConstantValue.
Referenced by llvm::AArch64TTIImpl::getArithmeticInstrCost(), llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::RISCVTTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), llvm::AArch64TTIImpl::getIntrinsicInstrCost(), llvm::RISCVTTIImpl::getMemoryOpCost(), llvm::X86TTIImpl::getMemoryOpCost(), and llvm::RISCVTTIImpl::getStoreImmCost().
isNegatedPowerOf2()
bool llvm::TargetTransformInfo::OperandValueInfo::isNegatedPowerOf2 () const inline
Definition at line 1081 of file TargetTransformInfo.h.
References llvm::TargetTransformInfo::OP_NegatedPowerOf2, and Properties.
Referenced by llvm::X86TTIImpl::getArithmeticInstrCost().
isPowerOf2()
bool llvm::TargetTransformInfo::OperandValueInfo::isPowerOf2 () const inline
Definition at line 1078 of file TargetTransformInfo.h.
References llvm::TargetTransformInfo::OP_PowerOf2, and Properties.
Referenced by llvm::AArch64TTIImpl::getArithmeticInstrCost(), and llvm::X86TTIImpl::getArithmeticInstrCost().
isUniform()
bool llvm::TargetTransformInfo::OperandValueInfo::isUniform () const inline
Definition at line 1075 of file TargetTransformInfo.h.
References Kind, llvm::TargetTransformInfo::OK_UniformConstantValue, and llvm::TargetTransformInfo::OK_UniformValue.
Referenced by llvm::AArch64TTIImpl::getArithmeticInstrCost(), llvm::ARMTTIImpl::getArithmeticInstrCost(), llvm::WebAssemblyTTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::AArch64TTIImpl::getIntrinsicInstrCost(), and llvm::RISCVTTIImpl::getStoreImmCost().
Member Data Documentation
Kind
OperandValueKind llvm::TargetTransformInfo::OperandValueInfo::Kind = OK_AnyValue
Definition at line 1069 of file TargetTransformInfo.h.
Referenced by llvm::LoopVectorizationCostModel::getDivRemSpeculationCost(), llvm::BasicTTIImplBase< T >::getIntrinsicInstrCost(), getNoProps(), isConstant(), and isUniform().
Properties
OperandValueProperties llvm::TargetTransformInfo::OperandValueInfo::Properties = OP_None
Definition at line 1070 of file TargetTransformInfo.h.
Referenced by isNegatedPowerOf2(), and isPowerOf2().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/TargetTransformInfo.h