LLVM: llvm::SPIRV::RequirementHandler Struct Reference
llvm::SPIRV::RequirementHandler Struct Reference
#include "Target/SPIRV/SPIRVModuleAnalysis.h"
Public Member Functions
RequirementHandler ()
void clear ()
unsigned getMinVersion () const
unsigned getMaxVersion () const
const CapabilityList & getMinimalCapabilities () const
const SmallSet< Extension::Extension, 4 > & getExtensions () const
void addCapabilities (const CapabilityList &ToAdd)
void addCapability (Capability::Capability ToAdd)
void addExtensions (const ExtensionList &ToAdd)
void addExtension (Extension::Extension ToAdd)
void addRequirements (const Requirements &Req)
void getAndAddRequirements (SPIRV::OperandCategory::OperandCategory Category, uint32_t i, const SPIRVSubtarget &ST)
void checkSatisfiable (const SPIRVSubtarget &ST) const
void initAvailableCapabilities (const SPIRVSubtarget &ST)
void addAvailableCaps (const CapabilityList &ToAdd)
bool isCapabilityAvailable (Capability::Capability Cap) const
void removeCapabilityIf (const Capability::Capability ToRemove, const Capability::Capability IfPresent)
Detailed Description
Definition at line 60 of file SPIRVModuleAnalysis.h.
Constructor & Destructor Documentation
RequirementHandler()
llvm::SPIRV::RequirementHandler::RequirementHandler () inline
Definition at line 82 of file SPIRVModuleAnalysis.h.
Member Function Documentation
addAvailableCaps()
void SPIRV::RequirementHandler::addAvailableCaps (const CapabilityList & ToAdd)
Definition at line 522 of file SPIRVModuleAnalysis.cpp.
References llvm::getSymbolicOperandCapabilities().
addCapabilities()
void SPIRV::RequirementHandler::addCapabilities (const CapabilityList & ToAdd)
Definition at line 422 of file SPIRVModuleAnalysis.cpp.
References llvm::getSymbolicOperandCapabilities().
Referenced by addCapability().
addCapability()
void llvm::SPIRV::RequirementHandler::addCapability (Capability::Capability ToAdd) inline
Definition at line 101 of file SPIRVModuleAnalysis.h.
References addCapabilities().
Referenced by addInstrRequirements(), collectReqs(), and llvm::SPIRVModuleAnalysis::runOnModule().
addExtension()
void llvm::SPIRV::RequirementHandler::addExtension (Extension::Extension ToAdd) inline
Definition at line 105 of file SPIRVModuleAnalysis.h.
References llvm::SmallSet< T, N, C >::insert().
Referenced by addInstrRequirements(), and collectReqs().
addExtensions()
void llvm::SPIRV::RequirementHandler::addExtensions (const ExtensionList & ToAdd) inline
Definition at line 102 of file SPIRVModuleAnalysis.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), and llvm::SmallSet< T, N, C >::insert().
addRequirements()
void SPIRV::RequirementHandler::addRequirements (const Requirements & Req)
Definition at line 434 of file SPIRVModuleAnalysis.cpp.
References llvm::SPIRV::Requirements::Cap, llvm::dbgs(), llvm::SPIRV::Requirements::Exts, llvm::SPIRV::Requirements::IsSatisfiable, LLVM_DEBUG, llvm::SPIRV::Requirements::MaxVer, llvm::SPIRV::Requirements::MinVer, and llvm::report_fatal_error().
Referenced by addOpDecorateReqs(), addOpTypeImageReqs(), and getAndAddRequirements().
checkSatisfiable()
void SPIRV::RequirementHandler::checkSatisfiable (const SPIRVSubtarget & ST) const
Definition at line 467 of file SPIRVModuleAnalysis.cpp.
References llvm::dbgs(), llvm::getSymbolicOperandMnemonic(), LLVM_DEBUG, and llvm::report_fatal_error().
clear()
void llvm::SPIRV::RequirementHandler::clear () inline
Definition at line 83 of file SPIRVModuleAnalysis.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::clear(), llvm::SmallSet< T, N, C >::clear(), and llvm::SmallVectorImpl< T >::clear().
getAndAddRequirements()
void SPIRV::RequirementHandler::getAndAddRequirements (SPIRV::OperandCategory::OperandCategory Category, uint32_t i, const SPIRVSubtarget & ST)
Definition at line 403 of file SPIRVModuleAnalysis.cpp.
References addRequirements().
Referenced by addInstrRequirements(), addOpTypeImageReqs(), and collectReqs().
getExtensions()
const SmallSet< Extension::Extension, 4 > & llvm::SPIRV::RequirementHandler::getExtensions () const inline
Definition at line 94 of file SPIRVModuleAnalysis.h.
getMaxVersion()
unsigned llvm::SPIRV::RequirementHandler::getMaxVersion () const inline
Definition at line 92 of file SPIRVModuleAnalysis.h.
getMinimalCapabilities()
const CapabilityList & llvm::SPIRV::RequirementHandler::getMinimalCapabilities () const inline
Definition at line 93 of file SPIRVModuleAnalysis.h.
getMinVersion()
unsigned llvm::SPIRV::RequirementHandler::getMinVersion () const inline
Definition at line 91 of file SPIRVModuleAnalysis.h.
initAvailableCapabilities()
void llvm::SPIRV::RequirementHandler::initAvailableCapabilities (const SPIRVSubtarget & ST)
Definition at line 538 of file SPIRVModuleAnalysis.cpp.
References llvm::report_fatal_error().
isCapabilityAvailable()
bool llvm::SPIRV::RequirementHandler::isCapabilityAvailable (Capability::Capability Cap) const inline
Definition at line 119 of file SPIRVModuleAnalysis.h.
References llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::contains().
removeCapabilityIf()
void SPIRV::RequirementHandler::removeCapabilityIf (const Capability::Capability ToRemove, const Capability::Capability IfPresent)
Definition at line 529 of file SPIRVModuleAnalysis.cpp.
References ToRemove.
Referenced by addInstrRequirements().
The documentation for this struct was generated from the following files:
lib/Target/SPIRV/SPIRVModuleAnalysis.h
lib/Target/SPIRV/SPIRVModuleAnalysis.cpp