LLVM: llvm::ValueDFS_Compare Struct Reference
llvm::ValueDFS_Compare Struct Reference
Public Member Functions
ValueDFS_Compare (DominatorTree &DT)
bool operator() (const ValueDFS &A, const ValueDFS &B) const
std::pair< BasicBlock *, BasicBlock * > getBlockEdge (const ValueDFS &VD) const
bool comparePHIRelated (const ValueDFS &A, const ValueDFS &B) const
Value * getMiddleDef (const ValueDFS &VD) const
const Instruction * getDefOrUser (const Value *Def, const Use *U) const
bool localComesBefore (const ValueDFS &A, const ValueDFS &B) const
Public Attributes
DominatorTree & DT
Detailed Description
Definition at line 113 of file PredicateInfo.cpp.
Constructor & Destructor Documentation
ValueDFS_Compare()
llvm::ValueDFS_Compare::ValueDFS_Compare (DominatorTree & DT) inline
Definition at line 115 of file PredicateInfo.cpp.
Member Function Documentation
comparePHIRelated()
bool llvm::ValueDFS_Compare::comparePHIRelated (const ValueDFS & A, const ValueDFS & B) const inline
Definition at line 155 of file PredicateInfo.cpp.
References A, assert(), B, DT, getBlockEdge(), llvm::DomTreeNodeBase< NodeT >::getDFSNumIn(), and llvm::DominatorTreeBase< NodeT, IsPostDom >::getNode().
Referenced by operator()().
getBlockEdge()
std::pair< BasicBlock *, BasicBlock * > llvm::ValueDFS_Compare::getBlockEdge (const ValueDFS & VD) const inline
Definition at line 145 of file PredicateInfo.cpp.
References llvm::ValueDFS::Def, PHI, llvm::ValueDFS::PInfo, and llvm::ValueDFS::U.
Referenced by comparePHIRelated().
getDefOrUser()
const Instruction * llvm::ValueDFS_Compare::getDefOrUser (const Value * Def, const Use * U) const inline
Definition at line 209 of file PredicateInfo.cpp.
Referenced by localComesBefore().
getMiddleDef()
Value * llvm::ValueDFS_Compare::getMiddleDef (const ValueDFS & VD) const inline
Definition at line 188 of file PredicateInfo.cpp.
References assert(), llvm::ValueDFS::Def, llvm::ValueDFS::PInfo, and llvm::ValueDFS::U.
Referenced by localComesBefore().
localComesBefore()
bool llvm::ValueDFS_Compare::localComesBefore (const ValueDFS & A, const ValueDFS & B) const inline
Definition at line 217 of file PredicateInfo.cpp.
References A, B, getDefOrUser(), getMiddleDef(), and llvm::valueComesBefore().
Referenced by operator()().
operator()()
bool llvm::ValueDFS_Compare::operator() (const ValueDFS & A, const ValueDFS & B) const inline
Definition at line 117 of file PredicateInfo.cpp.
References A, assert(), B, comparePHIRelated(), llvm::LN_Last, llvm::LN_Middle, and localComesBefore().
Member Data Documentation
DT
DominatorTree& llvm::ValueDFS_Compare::DT
Definition at line 114 of file PredicateInfo.cpp.
Referenced by comparePHIRelated().
The documentation for this struct was generated from the following file:
lib/Transforms/Utils/PredicateInfo.cpp