LLVM: llvm::AA::PointerInfo::State Struct Reference
llvm::AA::PointerInfo::State Struct Reference
A type to track pointer/struct usage and accesses for AAPointerInfo.
Public Member Functions
State ()=default
State (State &&SIS)=default
const State & getAssumed () const
bool isValidState () const override
See AbstractState::isValidState().
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint().
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint().
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint().
State & operator= (const State &R)
State & operator= (State &&R)
ChangeStatus addAccess (Attributor &A, const AAPointerInfo::RangeList &Ranges, Instruction &I, std::optional< Value * > Content, AAPointerInfo::AccessKind Kind, Type *Ty, Instruction *RemoteI=nullptr)
Add a new Access to the state at offset Offset and with size Size.
AAPointerInfo::const_bin_iterator begin () const
AAPointerInfo::const_bin_iterator end () const
int64_t numOffsetBins () const
const AAPointerInfo::Access & getAccess (unsigned Index) const
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
virtual bool isValidState () const =0
Return if this abstract state is in a valid state.
virtual bool isAtFixpoint () const =0
Return if this abstract state is fixed, thus does not need to be updated if information changes as it cannot change itself.
virtual ChangeStatus indicateOptimisticFixpoint ()=0
Indicate that the abstract state should converge to the optimistic state.
virtual ChangeStatus indicatePessimisticFixpoint ()=0
Indicate that the abstract state should converge to the pessimistic state.
Static Public Member Functions
static State getBestState (const State &SIS)
Return the best possible representable state.
static State getWorstState (const State &SIS)
Return the worst possible representable state.
Protected Member Functions
bool forallInterferingAccesses (AA::RangeTy Range, function_ref< bool(const AAPointerInfo::Access &, bool)> CB) const
See AAPointerInfo::forallInterferingAccesses.
bool forallInterferingAccesses (Instruction &I, function_ref< bool(const AAPointerInfo::Access &, bool)> CB, AA::RangeTy &Range) const
See AAPointerInfo::forallInterferingAccesses.
Protected Attributes
SmallVector< AAPointerInfo::Access > AccessList
AAPointerInfo::OffsetBinsTy OffsetBins
DenseMap< const Instruction *, SmallVector< unsigned > > RemoteIMap
Detailed Description
A type to track pointer/struct usage and accesses for AAPointerInfo.
Definition at line 787 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
State() [1/2]
llvm::AA::PointerInfo::State::State () default
Referenced by llvm::AA::PointerInfo::State::getBestState().
State() [2/2]
llvm::AA::PointerInfo::State::State (State && SIS) default
Member Function Documentation
addAccess()
ChangeStatus llvm::AA::PointerInfo::State::addAccess (Attributor & A, const AAPointerInfo::RangeList & Ranges, Instruction & I, std::optional< Value * > Content, AAPointerInfo::AccessKind Kind, Type * Ty, Instruction * RemoteI = nullptr)
Add a new Access to the state at offset Offset and with size Size.
The access is associated with I, writes Content (if anything), and is of kind Kind. If an Access already exists for the same I and same RemoteI, the two are combined, potentially losing information about offset and size. The resulting access must now be moved from its original OffsetBin to the bin for its new offset.
\Returns CHANGED, if the state changed, UNCHANGED otherwise.
Definition at line 928 of file AttributorAttributes.cpp.
References A, llvm::AA::PointerInfo::State::AccessList, assert(), Before, llvm::Bin, llvm::CHANGED, Content, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::dbgs(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), LLVM_DEBUG, llvm::AA::PointerInfo::State::OffsetBins, llvm::AA::PointerInfo::State::RemoteIMap, llvm::AAPointerInfo::RangeList::set_difference(), ToRemove, and llvm::UNCHANGED.
begin()
AAPointerInfo::const_bin_iterator llvm::AA::PointerInfo::State::begin () const inline
Definition at line 854 of file AttributorAttributes.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::begin(), and llvm::AA::PointerInfo::State::OffsetBins.
end()
AAPointerInfo::const_bin_iterator llvm::AA::PointerInfo::State::end () const inline
Definition at line 855 of file AttributorAttributes.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), and llvm::AA::PointerInfo::State::OffsetBins.
forallInterferingAccesses() [1/2]
bool llvm::AA::PointerInfo::State::forallInterferingAccesses (AA::RangeTy Range, function_ref< bool(const AAPointerInfo::Access &, bool)> CB) const inline protected
See AAPointerInfo::forallInterferingAccesses.
Definition at line 880 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::State::AccessList, llvm::AA::PointerInfo::State::isValidState(), and llvm::AA::PointerInfo::State::OffsetBins.
Referenced by llvm::AA::PointerInfo::State::forallInterferingAccesses().
forallInterferingAccesses() [2/2]
bool llvm::AA::PointerInfo::State::forallInterferingAccesses (Instruction & I, function_ref< bool(const AAPointerInfo::Access &, bool)> CB, AA::RangeTy & Range) const inline protected
See AAPointerInfo::forallInterferingAccesses.
Definition at line 901 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::State::AccessList, llvm::AA::PointerInfo::State::forallInterferingAccesses(), I, llvm::AA::PointerInfo::State::isValidState(), and llvm::AA::PointerInfo::State::RemoteIMap.
getAccess()
const AAPointerInfo::Access & llvm::AA::PointerInfo::State::getAccess (unsigned Index) const inline
Definition at line 858 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::State::AccessList.
getAssumed()
const State & llvm::AA::PointerInfo::State::getAssumed () const inline
Definition at line 801 of file AttributorAttributes.cpp.
getBestState()
static State llvm::AA::PointerInfo::State::getBestState (const State & SIS) inline static
Return the best possible representable state.
Definition at line 789 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::State::State().
getWorstState()
static State llvm::AA::PointerInfo::State::getWorstState (const State & SIS) inline static
Return the worst possible representable state.
Definition at line 792 of file AttributorAttributes.cpp.
indicateOptimisticFixpoint()
ChangeStatus llvm::AA::PointerInfo::State::indicateOptimisticFixpoint () inline override virtual
See AbstractState::indicateOptimisticFixpoint().
Implements llvm::AbstractState.
Definition at line 810 of file AttributorAttributes.cpp.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::indicateOptimisticFixpoint(), and llvm::UNCHANGED.
indicatePessimisticFixpoint()
ChangeStatus llvm::AA::PointerInfo::State::indicatePessimisticFixpoint () inline override virtual
See AbstractState::indicatePessimisticFixpoint().
Implements llvm::AbstractState.
Definition at line 816 of file AttributorAttributes.cpp.
References llvm::CHANGED, and llvm::IntegerStateBase< base_ty, BestState, WorstState >::indicatePessimisticFixpoint().
isAtFixpoint()
bool llvm::AA::PointerInfo::State::isAtFixpoint () const inline override virtual
See AbstractState::isAtFixpoint().
Implements llvm::AbstractState.
Definition at line 807 of file AttributorAttributes.cpp.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::isAtFixpoint().
isValidState()
bool llvm::AA::PointerInfo::State::isValidState () const inline override virtual
See AbstractState::isValidState().
Implements llvm::AbstractState.
Definition at line 804 of file AttributorAttributes.cpp.
References llvm::IntegerStateBase< base_ty, BestState, WorstState >::isValidState().
Referenced by llvm::AA::PointerInfo::State::forallInterferingAccesses().
numOffsetBins()
int64_t llvm::AA::PointerInfo::State::numOffsetBins () const inline
Definition at line 856 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::State::OffsetBins, and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size().
operator=() [1/2]
State & llvm::AA::PointerInfo::State::operator= (const State & R) inline
Definition at line 821 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::State::AccessList, llvm::AA::PointerInfo::State::OffsetBins, and llvm::AA::PointerInfo::State::RemoteIMap.
operator=() [2/2]
State & llvm::AA::PointerInfo::State::operator= (State && R) inline
Definition at line 831 of file AttributorAttributes.cpp.
References llvm::AA::PointerInfo::State::AccessList, llvm::AA::PointerInfo::State::OffsetBins, llvm::AA::PointerInfo::State::RemoteIMap, and std::swap().
Member Data Documentation
AccessList
SmallVector<AAPointerInfo::Access> llvm::AA::PointerInfo::State::AccessList protected
Definition at line 875 of file AttributorAttributes.cpp.
Referenced by llvm::AA::PointerInfo::State::addAccess(), llvm::AA::PointerInfo::State::forallInterferingAccesses(), llvm::AA::PointerInfo::State::getAccess(), and llvm::AA::PointerInfo::State::operator=().
OffsetBins
AAPointerInfo::OffsetBinsTy llvm::AA::PointerInfo::State::OffsetBins protected
Definition at line 876 of file AttributorAttributes.cpp.
Referenced by llvm::AA::PointerInfo::State::addAccess(), llvm::AA::PointerInfo::State::begin(), llvm::AA::PointerInfo::State::end(), llvm::AA::PointerInfo::State::forallInterferingAccesses(), llvm::AA::PointerInfo::State::numOffsetBins(), and llvm::AA::PointerInfo::State::operator=().
RemoteIMap
DenseMap<const Instruction *, SmallVector<unsigned> > llvm::AA::PointerInfo::State::RemoteIMap protected
Definition at line 877 of file AttributorAttributes.cpp.
Referenced by llvm::AA::PointerInfo::State::addAccess(), llvm::AA::PointerInfo::State::forallInterferingAccesses(), and llvm::AA::PointerInfo::State::operator=().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp