LLVM: llvm::CoroSplitPass Struct Reference
llvm::CoroSplitPass Struct Reference
#include "llvm/Transforms/Coroutines/CoroSplit.h"
Public Member Functions
CoroSplitPass (bool OptimizeFrame=false)
CoroSplitPass (std::function< bool(Instruction &)> MaterializableCallback, bool OptimizeFrame=false)
PreservedAnalyses run (LazyCallGraph::SCC &C, CGSCCAnalysisManager &AM, LazyCallGraph &CG, CGSCCUpdateResult &UR)
Public Member Functions inherited from llvm::PassInfoMixin< CoroSplitPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Static Public Member Functions
static bool isRequired ()
Static Public Member Functions inherited from llvm::PassInfoMixin< CoroSplitPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Public Attributes
const std::function< bool(Instruction &)> MaterializableCallback
bool OptimizeFrame
Detailed Description
Definition at line 24 of file CoroSplit.h.
Constructor & Destructor Documentation
CoroSplitPass() [1/2]
CoroSplitPass::CoroSplitPass (bool OptimizeFrame = false)
Definition at line 2171 of file CoroSplit.cpp.
CoroSplitPass() [2/2]
llvm::CoroSplitPass::CoroSplitPass (std::function< bool(Instruction &)> MaterializableCallback, bool OptimizeFrame = false) inline
Definition at line 28 of file CoroSplit.h.
Member Function Documentation
isRequired()
static bool llvm::CoroSplitPass::isRequired () inline static
Definition at line 35 of file CoroSplit.h.
run()
PreservedAnalyses CoroSplitPass::run (LazyCallGraph::SCC & C, CGSCCAnalysisManager & AM, LazyCallGraph & CG, CGSCCUpdateResult & UR)
Definition at line 2175 of file CoroSplit.cpp.
References addPrepareFunction(), llvm::PreservedAnalyses::all(), llvm::CallingConv::C, llvm::CGSCCUpdateResult::CWorklist, llvm::dbgs(), DEBUG_TYPE, llvm::SmallVectorBase< Size_T >::empty(), F, FAM, llvm::LazyCallGraph::get(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), LLVM_DEBUG, llvm::LazyCallGraph::lookupSCC(), MaterializableCallback, N, llvm::PreservedAnalyses::none(), OptimizeFrame, llvm::SmallVectorTemplateBase< T, bool >::push_back(), replaceAllPrepares(), splitCoroutine(), and updateCallGraphAfterCoroutineSplit().
Member Data Documentation
MaterializableCallback
const std::function<bool(Instruction &)> llvm::CoroSplitPass::MaterializableCallback
Definition at line 25 of file CoroSplit.h.
Referenced by run().
OptimizeFrame
bool llvm::CoroSplitPass::OptimizeFrame
Definition at line 38 of file CoroSplit.h.
Referenced by run().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Coroutines/CoroSplit.h
lib/Transforms/Coroutines/CoroSplit.cpp