LLVM: llvm::VFInfo Struct Reference
llvm::VFInfo Struct Reference
Holds the VFShape for a specific scalar to vector function mapping.
#include "llvm/IR/VFABIDemangler.h"
Public Member Functions
std::optional< unsigned > getParamIndexForOptionalMask () const
Instruction Set Architecture.
bool isMasked () const
Returns true if at least one of the operands to the vectorized function has the kind 'GlobalPredicate'.
Public Attributes
VFShape Shape
std::string ScalarName
Classification of the vector function.
std::string VectorName
Scalar Function Name.
VFISAKind ISA
Vector Function Name associated to this VFInfo.
Detailed Description
Holds the VFShape for a specific scalar to vector function mapping.
Definition at line 123 of file VFABIDemangler.h.
Member Function Documentation
getParamIndexForOptionalMask()
std::optional< unsigned > llvm::VFInfo::getParamIndexForOptionalMask () const inline
Instruction Set Architecture.
Returns the index of the first parameter with the kind 'GlobalPredicate', if any exist.
Definition at line 131 of file VFABIDemangler.h.
References llvm::GlobalPredicate, llvm::VFShape::Parameters, and Shape.
Referenced by isMasked(), and llvm::LoopVectorizationCostModel::setVectorizedCallDecision().
isMasked()
bool llvm::VFInfo::isMasked () const inline
Returns true if at least one of the operands to the vectorized function has the kind 'GlobalPredicate'.
Definition at line 142 of file VFABIDemangler.h.
References getParamIndexForOptionalMask().
Member Data Documentation
ISA
VFISAKind llvm::VFInfo::ISA
Vector Function Name associated to this VFInfo.
Definition at line 127 of file VFABIDemangler.h.
ScalarName
std::string llvm::VFInfo::ScalarName
Classification of the vector function.
Definition at line 125 of file VFABIDemangler.h.
Shape
VFShape llvm::VFInfo::Shape
Definition at line 124 of file VFABIDemangler.h.
Referenced by getParamIndexForOptionalMask().
VectorName
std::string llvm::VFInfo::VectorName
Scalar Function Name.
Definition at line 126 of file VFABIDemangler.h.
The documentation for this struct was generated from the following file:
include/llvm/IR/VFABIDemangler.h