LLVM: llvm::mcdxbc::PSVRuntimeInfo Struct Reference
llvm::mcdxbc::PSVRuntimeInfo Struct Reference
#include "llvm/MC/DXContainerPSVInfo.h"
Public Member Functions
void write (raw_ostream &OS, uint32_t Version=std::numeric_limits< uint32_t >::max()) const
void finalize (Triple::EnvironmentType Stage)
Public Attributes
bool IsFinalized = false
dxbc::PSV::v2::RuntimeInfo BaseData
SmallVector< dxbc::PSV::v2::ResourceBindInfo > Resources
SmallVector< PSVSignatureElement > InputElements
SmallVector< PSVSignatureElement > OutputElements
SmallVector< PSVSignatureElement > PatchOrPrimElements
std::array< SmallVector< uint32_t >, 4 > OutputVectorMasks
SmallVector< uint32_t > PatchOrPrimMasks
std::array< SmallVector< uint32_t >, 4 > InputOutputMap
SmallVector< uint32_t > InputPatchMap
SmallVector< uint32_t > PatchOutputMap
Detailed Description
Definition at line 47 of file DXContainerPSVInfo.h.
Member Function Documentation
finalize()
void llvm::mcdxbc::PSVRuntimeInfo::finalize (Triple::EnvironmentType Stage) inline
Definition at line 74 of file DXContainerPSVInfo.h.
References BaseData, InputElements, llvm::sys::IsBigEndianHost, IsFinalized, OutputElements, PatchOrPrimElements, Resources, llvm::dxbc::PSV::v1::RuntimeInfo::SigInputElements, llvm::dxbc::PSV::v1::RuntimeInfo::SigOutputElements, llvm::dxbc::PSV::v1::RuntimeInfo::SigPatchOrPrimElements, and llvm::dxbc::PSV::v2::RuntimeInfo::swapBytes().
write()
void PSVRuntimeInfo::write (raw_ostream & OS, uint32_t Version = std::numeric_limits<uint32_t>::max()) const
Definition at line 69 of file DXContainerPSVInfo.cpp.
References assert(), BaseData, llvm::StringTableBuilder::DXContainer, llvm::StringTableBuilder::finalize(), llvm::StringTableBuilder::getOffset(), llvm::StringTableBuilder::getSize(), I, InputElements, InputOutputMap, InputPatchMap, llvm::sys::IsBigEndianHost, IsFinalized, llvm::little, Name, llvm::dxbc::PSV::v0::SignatureElement::NameOffset, OS, OutputElements, OutputVectorMasks, PatchOrPrimElements, PatchOrPrimMasks, PatchOutputMap, ProcessElementList(), Resources, llvm::SmallVectorBase< Size_T >::size(), llvm::dxbc::PSV::v0::SignatureElement::swapBytes(), llvm::StringTableBuilder::write(), llvm::raw_ostream::write(), llvm::support::endian::write(), llvm::support::endian::write_array(), and llvm::zip().
Member Data Documentation
BaseData
dxbc::PSV::v2::RuntimeInfo llvm::mcdxbc::PSVRuntimeInfo::BaseData
Definition at line 49 of file DXContainerPSVInfo.h.
Referenced by finalize(), and write().
InputElements
SmallVector<PSVSignatureElement> llvm::mcdxbc::PSVRuntimeInfo::InputElements
Definition at line 51 of file DXContainerPSVInfo.h.
Referenced by finalize(), and write().
InputOutputMap
std::array<SmallVector<uint32_t>, 4> llvm::mcdxbc::PSVRuntimeInfo::InputOutputMap
Definition at line 64 of file DXContainerPSVInfo.h.
Referenced by write().
InputPatchMap
SmallVector<uint32_t> llvm::mcdxbc::PSVRuntimeInfo::InputPatchMap
Definition at line 65 of file DXContainerPSVInfo.h.
Referenced by write().
IsFinalized
bool llvm::mcdxbc::PSVRuntimeInfo::IsFinalized = false
Definition at line 48 of file DXContainerPSVInfo.h.
Referenced by finalize(), and write().
OutputElements
SmallVector<PSVSignatureElement> llvm::mcdxbc::PSVRuntimeInfo::OutputElements
Definition at line 52 of file DXContainerPSVInfo.h.
Referenced by finalize(), and write().
OutputVectorMasks
std::array<SmallVector<uint32_t>, 4> llvm::mcdxbc::PSVRuntimeInfo::OutputVectorMasks
Definition at line 62 of file DXContainerPSVInfo.h.
Referenced by write().
PatchOrPrimElements
SmallVector<PSVSignatureElement> llvm::mcdxbc::PSVRuntimeInfo::PatchOrPrimElements
Definition at line 53 of file DXContainerPSVInfo.h.
Referenced by finalize(), and write().
PatchOrPrimMasks
SmallVector<uint32_t> llvm::mcdxbc::PSVRuntimeInfo::PatchOrPrimMasks
Definition at line 63 of file DXContainerPSVInfo.h.
Referenced by write().
PatchOutputMap
SmallVector<uint32_t> llvm::mcdxbc::PSVRuntimeInfo::PatchOutputMap
Definition at line 66 of file DXContainerPSVInfo.h.
Referenced by write().
Resources
SmallVector<dxbc::PSV::v2::ResourceBindInfo> llvm::mcdxbc::PSVRuntimeInfo::Resources
Definition at line 50 of file DXContainerPSVInfo.h.
Referenced by finalize(), and write().
The documentation for this struct was generated from the following files:
include/llvm/MC/DXContainerPSVInfo.h
lib/MC/DXContainerPSVInfo.cpp