LLVM: llvm::orc::MachOBuilder< MachOTraits >::Section Struct Reference
llvm::orc::MachOBuilder< MachOTraits >::Section Struct Reference
#include "llvm/ExecutionEngine/Orc/MachOBuilder.h"
Public Member Functions
Section (MachOBuilder &Builder, StringRef SecName, StringRef SegName)
RelocTarget addSymbol (int32_t Offset, StringRef Name, uint8_t Type, uint16_t Desc)
void addReloc (int32_t Offset, RelocTarget Target, bool PCRel, unsigned Length, unsigned Type)
auto & rawStruct ()
Public Member Functions inherited from llvm::orc::MachOBuilder< MachOTraits >::RelocTarget
RelocTarget (const Section &S)
RelocTarget (SymbolContainer &SC, size_t Idx)
bool isSymbol ()
uint32_t getSymbolNum ()
uint32_t getSectionId ()
MachOTraits::NList & nlist ()
Public Attributes
MachOBuilder & Builder
SectionContent Content
size_t SectionNumber = 0
SymbolContainer SC
std::vector< Reloc > Relocs
Detailed Description
template<typename MachOTraits>
struct llvm::orc::MachOBuilder< MachOTraits >::Section
Definition at line 229 of file MachOBuilder.h.
Constructor & Destructor Documentation
Section()
template<typename MachOTraits > llvm::orc::MachOBuilder< MachOTraits >::Section::Section (MachOBuilder & Builder, StringRef SecName, StringRef SegName) inline
Definition at line 236 of file MachOBuilder.h.
References assert(), llvm::StringRef::data(), llvm::orc::MachOBuilder< MachOTraits >::Section::rawStruct(), and llvm::StringRef::size().
Member Function Documentation
addReloc()
template<typename MachOTraits > void llvm::orc::MachOBuilder< MachOTraits >::Section::addReloc (int32_t Offset, RelocTarget Target, bool PCRel, unsigned Length, unsigned Type) inline
Definition at line 258 of file MachOBuilder.h.
References llvm::Length, llvm::Offset, and llvm::orc::MachOBuilder< MachOTraits >::Section::Relocs.
addSymbol()
template<typename MachOTraits > RelocTarget llvm::orc::MachOBuilder< MachOTraits >::Section::addSymbol (int32_t Offset, StringRef Name, uint8_t Type, uint16_t Desc) inline
Definition at line 245 of file MachOBuilder.h.
References llvm::orc::MachOBuilder< MachOTraits >::addString(), llvm::orc::MachOBuilder< MachOTraits >::Section::Builder, llvm::MachO::N_SECT, Name, llvm::MachO::NO_SECT, llvm::Offset, llvm::orc::MachOBuilder< MachOTraits >::Section::SC, and Sym.
rawStruct()
template<typename MachOTraits > auto & llvm::orc::MachOBuilder< MachOTraits >::Section::rawStruct () inline
Definition at line 263 of file MachOBuilder.h.
Referenced by llvm::orc::MachOBuilder< MachOTraits >::Section::Section().
Member Data Documentation
Builder
template<typename MachOTraits > MachOBuilder& llvm::orc::MachOBuilder< MachOTraits >::Section::Builder
Definition at line 230 of file MachOBuilder.h.
Referenced by llvm::orc::MachOBuilder< MachOTraits >::Section::addSymbol().
Content
template<typename MachOTraits > SectionContent llvm::orc::MachOBuilder< MachOTraits >::Section::Content
Definition at line 231 of file MachOBuilder.h.
Relocs
template<typename MachOTraits > std::vector<Reloc> llvm::orc::MachOBuilder< MachOTraits >::Section::Relocs
Definition at line 234 of file MachOBuilder.h.
Referenced by llvm::orc::MachOBuilder< MachOTraits >::Section::addReloc().
SC
template<typename MachOTraits > SymbolContainer llvm::orc::MachOBuilder< MachOTraits >::Section::SC
Definition at line 233 of file MachOBuilder.h.
Referenced by llvm::orc::MachOBuilder< MachOTraits >::Section::addSymbol().
SectionNumber
template<typename MachOTraits > size_t llvm::orc::MachOBuilder< MachOTraits >::Section::SectionNumber = 0
Definition at line 232 of file MachOBuilder.h.
Referenced by llvm::orc::MachOBuilder< MachOTraits >::RelocTarget::getSectionId().
The documentation for this struct was generated from the following file:
include/llvm/ExecutionEngine/Orc/MachOBuilder.h