LLVM: llvm::dwarf_linker::parallel::SectionDescriptorBase Struct Reference
llvm::dwarf_linker::parallel::SectionDescriptorBase Struct Reference abstract
This structure keeps data of the concrete section.
#include "llvm/DWARFLinker/Parallel/DWARFLinker.h"
Public Member Functions
SectionDescriptorBase (DebugSectionKind SectionKind, dwarf::FormParams Format, llvm::endianness Endianess)
virtual ~SectionDescriptorBase ()=default
virtual StringRef getContents ()=0
Returns section content.
DebugSectionKind getKind ()
Returns section kind.
const StringLiteral & getName () const
Returns section name.
llvm::endianness getEndianess () const
Returns endianess used by section.
dwarf::FormParams getFormParams () const
Returns FormParams used by section.
Protected Attributes
DebugSectionKind SectionKind = DebugSectionKind::NumberOfEnumEntries
The section kind.
dwarf::FormParams Format = {4, 4, dwarf::DWARF32}
Output format.
llvm::endianness Endianess = llvm::endianness::little
Detailed Description
This structure keeps data of the concrete section.
Definition at line 93 of file DWARFLinker.h.
Constructor & Destructor Documentation
SectionDescriptorBase()
llvm::dwarf_linker::parallel::SectionDescriptorBase::SectionDescriptorBase (DebugSectionKind SectionKind, dwarf::FormParams Format, llvm::endianness Endianess) inline
Definition at line 94 of file DWARFLinker.h.
~SectionDescriptorBase()
virtual llvm::dwarf_linker::parallel::SectionDescriptorBase::~SectionDescriptorBase () virtual default
Member Function Documentation
getContents()
virtual StringRef llvm::dwarf_linker::parallel::SectionDescriptorBase::getContents () pure virtual
Returns section content.
Implemented in llvm::dwarf_linker::parallel::SectionDescriptor.
getEndianess()
llvm::endianness llvm::dwarf_linker::parallel::SectionDescriptorBase::getEndianess () const inline
Returns endianess used by section.
Definition at line 105 of file DWARFLinker.h.
References Endianess.
getFormParams()
dwarf::FormParams llvm::dwarf_linker::parallel::SectionDescriptorBase::getFormParams () const inline
Returns FormParams used by section.
Definition at line 107 of file DWARFLinker.h.
References Format.
Referenced by llvm::dwarf_linker::parallel::DebugLineSectionEmitter::emit(), llvm::dwarf_linker::parallel::DwarfUnit::emitDebugStringOffsetSection(), llvm::dwarf_linker::parallel::SectionDescriptor::emitOffset(), llvm::dwarf_linker::parallel::SectionDescriptor::emitUnitLength(), and llvm::dwarf_linker::parallel::SectionDescriptor::maybeEmitDwarf64Mark().
getKind()
DebugSectionKind llvm::dwarf_linker::parallel::SectionDescriptorBase::getKind () inline
Returns section kind.
Definition at line 101 of file DWARFLinker.h.
References SectionKind.
getName()
const StringLiteral & llvm::dwarf_linker::parallel::SectionDescriptorBase::getName () const inline
Returns section name.
Definition at line 103 of file DWARFLinker.h.
References llvm::dwarf_linker::getSectionName().
Member Data Documentation
Endianess
llvm::endianness llvm::dwarf_linker::parallel::SectionDescriptorBase::Endianess = llvm::endianness::little protected
Definition at line 114 of file DWARFLinker.h.
Referenced by llvm::dwarf_linker::parallel::SectionDescriptor::applyIntVal(), llvm::dwarf_linker::parallel::SectionDescriptor::emitIntVal(), getEndianess(), llvm::dwarf_linker::parallel::SectionDescriptor::getIntVal(), and llvm::dwarf_linker::parallel::SectionDescriptor::setOutputFormat().
Format
dwarf::FormParams llvm::dwarf_linker::parallel::SectionDescriptorBase::Format = {4, 4, dwarf::DWARF32} protected
Output format.
Definition at line 113 of file DWARFLinker.h.
Referenced by llvm::dwarf_linker::parallel::SectionDescriptor::apply(), llvm::dwarf_linker::parallel::SectionDescriptor::applySLEB128(), llvm::dwarf_linker::parallel::SectionDescriptor::applyULEB128(), getFormParams(), llvm::dwarf_linker::parallel::SectionDescriptor::maybeEmitDwarf64Mark(), and llvm::dwarf_linker::parallel::SectionDescriptor::setOutputFormat().
SectionKind
DebugSectionKind llvm::dwarf_linker::parallel::SectionDescriptorBase::SectionKind = DebugSectionKind::NumberOfEnumEntries protected
The section kind.
Definition at line 111 of file DWARFLinker.h.
Referenced by getKind().
The documentation for this struct was generated from the following file:
include/llvm/DWARFLinker/Parallel/DWARFLinker.h