LLVM: llvm::AMDGPUAtomicOptimizerPass Struct Reference
llvm::AMDGPUAtomicOptimizerPass Struct Reference
#include "Target/AMDGPU/AMDGPU.h"
Public Member Functions
AMDGPUAtomicOptimizerPass (TargetMachine &TM, ScanOptions ScanImpl)
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< AMDGPUAtomicOptimizerPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< AMDGPUAtomicOptimizerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 231 of file AMDGPU.h.
Constructor & Destructor Documentation
AMDGPUAtomicOptimizerPass()
llvm::AMDGPUAtomicOptimizerPass::AMDGPUAtomicOptimizerPass (TargetMachine & TM, ScanOptions ScanImpl) inline
Definition at line 232 of file AMDGPU.h.
References TM.
Member Function Documentation
run()
PreservedAnalyses AMDGPUAtomicOptimizerPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 136 of file AMDGPUAtomicOptimizer.cpp.
References llvm::PreservedAnalyses::all(), llvm::CallingConv::AMDGPU_PS, DL, F, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::TargetMachine::getSubtarget(), llvm::DomTreeUpdater::Lazy, and llvm::PreservedAnalyses::preserve().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/AMDGPU.h
lib/Target/AMDGPU/AMDGPUAtomicOptimizer.cpp