LLVM: llvm::AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo Struct Reference
llvm::AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo Struct Reference
#include "Target/AMDGPU/AMDGPUResourceUsageAnalysis.h"
Public Member Functions
int32_t getTotalNumSGPRs (const GCNSubtarget &ST) const
int32_t getTotalNumVGPRs (const GCNSubtarget &ST, int32_t NumAGPR, int32_t NumVGPR) const
int32_t getTotalNumVGPRs (const GCNSubtarget &ST) const
Public Attributes
int32_t NumVGPR = 0
int32_t NumAGPR = 0
int32_t NumExplicitSGPR = 0
uint64_t PrivateSegmentSize = 0
bool UsesVCC = false
bool UsesFlatScratch = false
bool HasDynamicallySizedStack = false
bool HasRecursion = false
bool HasIndirectCall = false
Detailed Description
Definition at line 32 of file AMDGPUResourceUsageAnalysis.h.
Member Function Documentation
getTotalNumSGPRs()
int32_t AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo::getTotalNumSGPRs (const GCNSubtarget & ST) const
Definition at line 83 of file AMDGPUResourceUsageAnalysis.cpp.
References llvm::AMDGPU::IsaInfo::getNumExtraSGPRs(), NumExplicitSGPR, UsesFlatScratch, and UsesVCC.
getTotalNumVGPRs() [1/2]
int32_t AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo::getTotalNumVGPRs (const GCNSubtarget & ST) const
Definition at line 95 of file AMDGPUResourceUsageAnalysis.cpp.
References llvm::AMDGPU::getTotalNumVGPRs().
getTotalNumVGPRs() [2/2]
int32_t AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo::getTotalNumVGPRs (const GCNSubtarget & ST, int32_t NumAGPR, int32_t NumVGPR) const
Definition at line 90 of file AMDGPUResourceUsageAnalysis.cpp.
References llvm::AMDGPU::getTotalNumVGPRs().
Member Data Documentation
HasDynamicallySizedStack
bool llvm::AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo::HasDynamicallySizedStack = false
Definition at line 41 of file AMDGPUResourceUsageAnalysis.h.
HasIndirectCall
bool llvm::AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo::HasIndirectCall = false
Definition at line 43 of file AMDGPUResourceUsageAnalysis.h.
HasRecursion
bool llvm::AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo::HasRecursion = false
Definition at line 42 of file AMDGPUResourceUsageAnalysis.h.
NumAGPR
int32_t llvm::AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo::NumAGPR = 0
Definition at line 36 of file AMDGPUResourceUsageAnalysis.h.
NumExplicitSGPR
int32_t llvm::AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo::NumExplicitSGPR = 0
Definition at line 37 of file AMDGPUResourceUsageAnalysis.h.
Referenced by getTotalNumSGPRs().
NumVGPR
int32_t llvm::AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo::NumVGPR = 0
Definition at line 35 of file AMDGPUResourceUsageAnalysis.h.
PrivateSegmentSize
uint64_t llvm::AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo::PrivateSegmentSize = 0
Definition at line 38 of file AMDGPUResourceUsageAnalysis.h.
UsesFlatScratch
bool llvm::AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo::UsesFlatScratch = false
Definition at line 40 of file AMDGPUResourceUsageAnalysis.h.
Referenced by getTotalNumSGPRs().
UsesVCC
bool llvm::AMDGPUResourceUsageAnalysis::SIFunctionResourceInfo::UsesVCC = false
Definition at line 39 of file AMDGPUResourceUsageAnalysis.h.
Referenced by getTotalNumSGPRs().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/AMDGPUResourceUsageAnalysis.h
lib/Target/AMDGPU/AMDGPUResourceUsageAnalysis.cpp