LLVM: llvm::rdf::DataFlowGraph Struct Reference
llvm::rdf::DataFlowGraph Struct Reference
#include "llvm/CodeGen/RDFGraph.h"
Classes
struct Config
struct DefStack
Public Types
using DefStackMap = std::unordered_map< RegisterId, DefStack >
Public Member Functions
DataFlowGraph (MachineFunction &mf, const TargetInstrInfo &tii, const TargetRegisterInfo &tri, const MachineDominatorTree &mdt, const MachineDominanceFrontier &mdf)
DataFlowGraph (MachineFunction &mf, const TargetInstrInfo &tii, const TargetRegisterInfo &tri, const MachineDominatorTree &mdt, const MachineDominanceFrontier &mdf, const TargetOperandInfo &toi)
NodeBase * ptr (NodeId N) const
template<typename T >
T ptr (NodeId N) const
NodeId id (const NodeBase *P) const
template<typename T >
NodeAddr< T > addr (NodeId N) const
Func getFunc () const
MachineFunction & getMF () const
const TargetInstrInfo & getTII () const
const TargetRegisterInfo & getTRI () const
const PhysicalRegisterInfo & getPRI () const
const MachineDominatorTree & getDT () const
const MachineDominanceFrontier & getDF () const
const RegisterAggr & getLiveIns () const
void build (const Config &config)
void build ()
void pushAllDefs (Instr IA, DefStackMap &DM)
void markBlock (NodeId B, DefStackMap &DefM)
void releaseBlock (NodeId B, DefStackMap &DefM)
PackedRegisterRef pack (RegisterRef RR)
PackedRegisterRef pack (RegisterRef RR) const
RegisterRef unpack (PackedRegisterRef PR) const
RegisterRef makeRegRef (unsigned Reg, unsigned Sub) const
RegisterRef makeRegRef (const MachineOperand &Op) const
Ref getNextRelated (Instr IA, Ref RA) const
Ref getNextShadow (Instr IA, Ref RA, bool Create)
NodeList getRelatedRefs (Instr IA, Ref RA) const
Block findBlock (MachineBasicBlock *BB) const
void unlinkUse (Use UA, bool RemoveFromOwner)
void unlinkDef (Def DA, bool RemoveFromOwner)
bool isTracked (RegisterRef RR) const
bool hasUntrackedRef (Stmt S, bool IgnoreReserved=true) const
Static Public Member Functions
template<uint16_t Kind>
static bool IsRef (const Node BA)
template<uint16_t Kind>
static bool IsCode (const Node BA)
static bool IsDef (const Node BA)
static bool IsUse (const Node BA)
static bool IsPhi (const Node BA)
static bool IsPreservingDef (const Def DA)
Detailed Description
Definition at line 660 of file RDFGraph.h.
Member Typedef Documentation
DefStackMap
using llvm::rdf::DataFlowGraph::DefStackMap = std::unordered_map<RegisterId, DefStack>
Definition at line 772 of file RDFGraph.h.
Constructor & Destructor Documentation
DataFlowGraph() [1/2]
llvm::rdf::DataFlowGraph::DataFlowGraph (MachineFunction & mf, const TargetInstrInfo & tii, const TargetRegisterInfo & tri, const MachineDominatorTree & mdt, const MachineDominanceFrontier & mdf)
Definition at line 637 of file RDFGraph.cpp.
DataFlowGraph() [2/2]
llvm::rdf::DataFlowGraph::DataFlowGraph (MachineFunction & mf, const TargetInstrInfo & tii, const TargetRegisterInfo & tri, const MachineDominatorTree & mdt, const MachineDominanceFrontier & mdf, const TargetOperandInfo & toi)
Definition at line 645 of file RDFGraph.cpp.
Member Function Documentation
addr()
template<typename T > NodeAddr< T > llvm::rdf::DataFlowGraph::addr (NodeId N) const inline
Definition at line 689 of file RDFGraph.h.
References N.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::Liveness::getAllReachedUses(), and llvm::rdf::Liveness::getAllReachingDefs().
build() [1/2]
void llvm::rdf::DataFlowGraph::build () inline
Definition at line 775 of file RDFGraph.h.
References build(), and Config.
Referenced by build().
build() [2/2]
void llvm::rdf::DataFlowGraph::build (const Config & config)
Definition at line 858 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, assert(), B, Blocks, llvm::rdf::DataFlowGraph::Config::Classes, DM, E, llvm::rdf::RegisterAggr::empty(), findBlock(), llvm::rdf::FuncNode::getEntryBlock(), llvm::MCRegisterInfo::getNumRegs(), getPRI(), llvm::rdf::PhysicalRegisterInfo::getTRI(), I, llvm::rdf::RegisterAggr::insert(), isTracked(), llvm::rdf::BuildOptions::KeepDeadPhis, llvm::MachineBasicBlock::liveins(), llvm::rdf::CodeNode::members(), MRI, llvm::rdf::BuildOptions::OmitReserved, llvm::rdf::DataFlowGraph::Config::Options, P, PB(), llvm::rdf::NodeAttrs::PhiRef, llvm::MachineBasicBlock::pred_empty(), llvm::rdf::NodeAttrs::Preserving, llvm::SmallVectorTemplateBase< T, bool >::push_back(), llvm::rdf::RegisterAggr::refs(), and llvm::rdf::DataFlowGraph::Config::TrackRegs.
findBlock()
Block llvm::rdf::DataFlowGraph::findBlock (MachineBasicBlock * BB) const inline
Definition at line 799 of file RDFGraph.h.
Referenced by build(), and llvm::rdf::Liveness::getNearestAliasedRef().
getDF()
const MachineDominanceFrontier & llvm::rdf::DataFlowGraph::getDF () const inline
Definition at line 699 of file RDFGraph.h.
getDT()
const MachineDominatorTree & llvm::rdf::DataFlowGraph::getDT () const inline
Definition at line 698 of file RDFGraph.h.
getFunc()
Func llvm::rdf::DataFlowGraph::getFunc () const inline
Definition at line 693 of file RDFGraph.h.
Referenced by llvm::rdf::Liveness::computeLiveIns(), and llvm::rdf::Liveness::computePhiInfo().
getLiveIns()
const RegisterAggr & llvm::rdf::DataFlowGraph::getLiveIns () const inline
Definition at line 700 of file RDFGraph.h.
Referenced by llvm::rdf::Liveness::computeLiveIns().
getMF()
MachineFunction & llvm::rdf::DataFlowGraph::getMF () const inline
Definition at line 694 of file RDFGraph.h.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::resetKills(), and llvm::rdf::Liveness::resetLiveIns().
getNextRelated()
Ref llvm::rdf::DataFlowGraph::getNextRelated (Instr IA, Ref RA) const
Definition at line 1163 of file RDFGraph.cpp.
References assert(), Cond, llvm::rdf::PhysicalRegisterInfo::equal_to(), getPRI(), llvm::rdf::NodeAttrs::Phi, RA, llvm::rdf::NodeAttrs::Stmt, and llvm::rdf::NodeAttrs::Use.
Referenced by getRelatedRefs().
getNextShadow()
Ref llvm::rdf::DataFlowGraph::getNextShadow (Instr IA, Ref RA, bool Create)
Definition at line 1225 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, assert(), RA, and llvm::rdf::NodeAttrs::Shadow.
getPRI()
const PhysicalRegisterInfo & llvm::rdf::DataFlowGraph::getPRI () const inline
Definition at line 697 of file RDFGraph.h.
Referenced by build(), getNextRelated(), isTracked(), and makeRegRef().
getRelatedRefs()
NodeList llvm::rdf::DataFlowGraph::getRelatedRefs (Instr IA, Ref RA) const
Definition at line 1136 of file RDFGraph.cpp.
References assert(), getNextRelated(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and RA.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), and llvm::rdf::Liveness::getAllReachingDefs().
getTII()
const TargetInstrInfo & llvm::rdf::DataFlowGraph::getTII () const inline
Definition at line 695 of file RDFGraph.h.
getTRI()
const TargetRegisterInfo & llvm::rdf::DataFlowGraph::getTRI () const inline
Definition at line 696 of file RDFGraph.h.
hasUntrackedRef()
bool llvm::rdf::DataFlowGraph::hasUntrackedRef (Stmt S, bool IgnoreReserved = true) const
Definition at line 1779 of file RDFGraph.cpp.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::RegisterRef::idx(), llvm::is_contained(), llvm::rdf::RegisterRef::isReg(), isTracked(), and llvm::SmallVectorTemplateBase< T, bool >::push_back().
id()
NodeId llvm::rdf::DataFlowGraph::id (const NodeBase * P) const
Definition at line 768 of file RDFGraph.cpp.
References P.
IsCode()
template<uint16_t Kind> static bool llvm::rdf::DataFlowGraph::IsCode (const Node BA) inline static
Definition at line 821 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, and llvm::rdf::NodeAttrs::Code.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), and llvm::rdf::Liveness::getAllReachingDefs().
IsDef()
static bool llvm::rdf::DataFlowGraph::IsDef (const Node BA) inline static
Definition at line 825 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::NodeAttrs::Def, and llvm::rdf::NodeAttrs::Ref.
Referenced by llvm::rdf::Liveness::getNearestAliasedRef().
IsPhi()
static bool llvm::rdf::DataFlowGraph::IsPhi (const Node BA) inline static
Definition at line 835 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::NodeAttrs::Code, and llvm::rdf::NodeAttrs::Phi.
IsPreservingDef()
static bool llvm::rdf::DataFlowGraph::IsPreservingDef (const Def DA) inline static
Definition at line 840 of file RDFGraph.h.
References llvm::rdf::NodeAttrs::Preserving, and llvm::rdf::NodeAttrs::Undef.
Referenced by llvm::rdf::Liveness::getAllReachedUses(), and llvm::rdf::Liveness::getAllReachingDefs().
IsRef()
template<uint16_t Kind> static bool llvm::rdf::DataFlowGraph::IsRef (const Node BA) inline static
Definition at line 817 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, and llvm::rdf::NodeAttrs::Ref.
Referenced by llvm::rdf::Liveness::computeLiveIns(), and llvm::rdf::Liveness::computePhiInfo().
isTracked()
bool llvm::rdf::DataFlowGraph::isTracked (RegisterRef RR) const
Definition at line 1775 of file RDFGraph.cpp.
References llvm::rdf::disjoint(), and getPRI().
Referenced by build(), and hasUntrackedRef().
IsUse()
static bool llvm::rdf::DataFlowGraph::IsUse (const Node BA) inline static
Definition at line 830 of file RDFGraph.h.
References llvm::rdf::NodeAddr< T >::Addr, llvm::rdf::NodeAttrs::Ref, and llvm::rdf::NodeAttrs::Use.
makeRegRef() [1/2]
RegisterRef llvm::rdf::DataFlowGraph::makeRegRef (const MachineOperand & Op) const
Definition at line 993 of file RDFGraph.cpp.
References assert(), llvm::LaneBitmask::getAll(), getPRI(), and makeRegRef().
makeRegRef() [2/2]
RegisterRef llvm::rdf::DataFlowGraph::makeRegRef (unsigned Reg, unsigned Sub) const
Definition at line 985 of file RDFGraph.cpp.
References assert(), llvm::TargetRegisterInfo::getSubReg(), llvm::rdf::RegisterRef::isMaskId(), llvm::rdf::RegisterRef::isRegId(), and Reg.
Referenced by makeRegRef().
markBlock()
void llvm::rdf::DataFlowGraph::markBlock (NodeId B, DefStackMap & DefM)
Definition at line 1002 of file RDFGraph.cpp.
References B, and P.
pack() [1/2]
PackedRegisterRef llvm::rdf::DataFlowGraph::pack (RegisterRef RR) inline
Definition at line 781 of file RDFGraph.h.
References llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), llvm::rdf::RegisterRef::Mask, and llvm::rdf::RegisterRef::Reg.
pack() [2/2]
PackedRegisterRef llvm::rdf::DataFlowGraph::pack (RegisterRef RR) const inline
Definition at line 784 of file RDFGraph.h.
References llvm::rdf::LaneMaskIndex::getIndexForLaneMask(), llvm::rdf::RegisterRef::Mask, and llvm::rdf::RegisterRef::Reg.
ptr() [1/2]
NodeBase * llvm::rdf::DataFlowGraph::ptr (NodeId N) const
Definition at line 761 of file RDFGraph.cpp.
References N.
Referenced by ptr().
ptr() [2/2]
template<typename T > T llvm::rdf::DataFlowGraph::ptr (NodeId N) const inline
Definition at line 683 of file RDFGraph.h.
References N, and ptr().
pushAllDefs()
void llvm::rdf::DataFlowGraph::pushAllDefs (Instr IA, DefStackMap & DM)
Definition at line 1027 of file RDFGraph.cpp.
releaseBlock()
void llvm::rdf::DataFlowGraph::releaseBlock (NodeId B, DefStackMap & DefM)
Definition at line 1009 of file RDFGraph.cpp.
References B, E, I, and P.
unlinkDef()
void llvm::rdf::DataFlowGraph::unlinkDef (Def DA, bool RemoveFromOwner) inline
Definition at line 807 of file RDFGraph.h.
unlinkUse()
void llvm::rdf::DataFlowGraph::unlinkUse (Use UA, bool RemoveFromOwner) inline
Definition at line 801 of file RDFGraph.h.
unpack()
RegisterRef llvm::rdf::DataFlowGraph::unpack (PackedRegisterRef PR) const inline
Definition at line 787 of file RDFGraph.h.
References llvm::rdf::LaneMaskIndex::getLaneMaskForIndex(), llvm::rdf::PackedRegisterRef::MaskId, and llvm::rdf::PackedRegisterRef::Reg.
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFGraph.h
lib/CodeGen/RDFGraph.cpp