LLVM: llvm::AMDGPUSimplifyLibCallsPass Struct Reference
llvm::AMDGPUSimplifyLibCallsPass Struct Reference
#include "Target/AMDGPU/AMDGPU.h"
Public Member Functions
AMDGPUSimplifyLibCallsPass ()
PreservedAnalyses run (Function &F, FunctionAnalysisManager &AM)
Public Member Functions inherited from llvm::PassInfoMixin< AMDGPUSimplifyLibCallsPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< AMDGPUSimplifyLibCallsPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 65 of file AMDGPU.h.
Constructor & Destructor Documentation
AMDGPUSimplifyLibCallsPass()
llvm::AMDGPUSimplifyLibCallsPass::AMDGPUSimplifyLibCallsPass () inline
Definition at line 66 of file AMDGPU.h.
Member Function Documentation
run()
PreservedAnalyses AMDGPUSimplifyLibCallsPass::run (Function & F, FunctionAnalysisManager & AM)
Definition at line 1664 of file AMDGPULibCalls.cpp.
References llvm::PreservedAnalyses::all(), llvm::dbgs(), E, F, llvm::AMDGPULibCalls::fold(), I, llvm::AMDGPULibCalls::initFunction(), llvm::AMDGPULibCalls::initNativeFuncs(), LLVM_DEBUG, and llvm::PreservedAnalyses::none().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/AMDGPU.h
lib/Target/AMDGPU/AMDGPULibCalls.cpp