LLVM: llvm::object::ViewArray< T > Struct Template Reference
llvm::object::ViewArray< T > Struct Template Reference
#include "llvm/Object/DXContainer.h"
Classes
struct iterator
Public Types
using value_type = T
Public Member Functions
ViewArray ()=default
ViewArray (StringRef D, size_t S)
iterator begin () const
iterator end () const
size_t size () const
bool isEmpty () const
Static Public Member Functions
static constexpr uint32_t MaxStride ()
Public Attributes
StringRef Data
uint32_t Stride = sizeof(T)
Detailed Description
template<typename T>
struct llvm::object::ViewArray< T >
Definition at line 46 of file DXContainer.h.
Member Typedef Documentation
value_type
template<typename T > using llvm::object::ViewArray< T >::value_type = T
Definition at line 53 of file DXContainer.h.
Constructor & Destructor Documentation
ViewArray() [1/2]
template<typename T > llvm::object::ViewArray< T >::ViewArray () default
ViewArray() [2/2]
template<typename T > llvm::object::ViewArray< T >::ViewArray (StringRef D, size_t S) inline
Definition at line 51 of file DXContainer.h.
Member Function Documentation
begin()
template<typename T > iterator llvm::object::ViewArray< T >::begin () const inline
Definition at line 109 of file DXContainer.h.
References llvm::StringRef::begin(), and llvm::object::ViewArray< T >::Data.
Referenced by llvm::object::DirectX::Signature::begin().
end()
template<typename T > iterator llvm::object::ViewArray< T >::end () const inline
Definition at line 111 of file DXContainer.h.
References llvm::object::ViewArray< T >::Data, and llvm::StringRef::end().
Referenced by llvm::object::DirectX::Signature::end().
isEmpty()
template<typename T > bool llvm::object::ViewArray< T >::isEmpty () const inline
Definition at line 115 of file DXContainer.h.
References llvm::object::ViewArray< T >::Data, and llvm::StringRef::empty().
Referenced by llvm::object::DirectX::Signature::isEmpty().
MaxStride()
template<typename T > static constexpr uint32_t llvm::object::ViewArray< T >::MaxStride () inline static constexpr
Definition at line 54 of file DXContainer.h.
Referenced by llvm::object::ViewArray< T >::iterator::operator*().
size()
template<typename T > size_t llvm::object::ViewArray< T >::size () const inline
Definition at line 113 of file DXContainer.h.
References llvm::object::ViewArray< T >::Data, llvm::StringRef::size(), and llvm::object::ViewArray< T >::Stride.
Referenced by llvm::object::DirectX::PSVRuntimeInfo::getResourceCount().
Member Data Documentation
Data
template<typename T > StringRef llvm::object::ViewArray< T >::Data
Definition at line 47 of file DXContainer.h.
Referenced by llvm::object::ViewArray< T >::begin(), llvm::object::ViewArray< T >::end(), llvm::object::ViewArray< T >::isEmpty(), and llvm::object::ViewArray< T >::size().
Stride
template<typename T > uint32_t llvm::object::ViewArray< T >::Stride = sizeof(T)
Definition at line 48 of file DXContainer.h.
Referenced by llvm::object::DirectX::PSVRuntimeInfo::getResourceStride(), llvm::object::DirectX::PSVRuntimeInfo::getSigElementStride(), and llvm::object::ViewArray< T >::size().
The documentation for this struct was generated from the following file:
include/llvm/Object/DXContainer.h