LLVM: llvm::IndexedInstrProf::Header Struct Reference
llvm::IndexedInstrProf::Header Struct Reference
#include "llvm/ProfileData/InstrProf.h"
Public Member Functions
size_t size () const
uint64_t formatVersion () const
Static Public Member Functions
static Expected< Header > readFromBuffer (const unsigned char *Buffer)
Public Attributes
uint64_t Magic
uint64_t Version
uint64_t Unused
uint64_t HashType
uint64_t HashOffset
uint64_t MemProfOffset
uint64_t BinaryIdOffset
uint64_t TemporalProfTracesOffset
Detailed Description
Definition at line 1040 of file InstrProf.h.
Member Function Documentation
formatVersion()
uint64_t llvm::IndexedInstrProf::Header::formatVersion () const
Definition at line 1497 of file InstrProf.cpp.
References Version.
Referenced by size().
readFromBuffer()
Expected< Header > llvm::IndexedInstrProf::Header::readFromBuffer (const unsigned char * Buffer) static
Definition at line 1502 of file InstrProf.cpp.
References llvm::bad_magic, BinaryIdOffset, llvm::IndexedInstrProf::CurrentVersion, H, HashOffset, HashType, llvm::IndexedInstrProf::Magic, Magic, MemProfOffset, llvm::IndexedInstrProf::offsetOf(), llvm::IndexedInstrProf::read(), TemporalProfTracesOffset, llvm::unsupported_version, Version, and llvm::IndexedInstrProf::Version11.
Referenced by llvm::IndexedInstrProfReader::readHeader().
size()
size_t llvm::IndexedInstrProf::Header::size () const
Definition at line 1549 of file InstrProf.cpp.
References BinaryIdOffset, llvm::IndexedInstrProf::CurrentVersion, formatVersion(), HashOffset, MemProfOffset, llvm::IndexedInstrProf::offsetOf(), TemporalProfTracesOffset, and llvm::IndexedInstrProf::Version11.
Member Data Documentation
BinaryIdOffset
uint64_t llvm::IndexedInstrProf::Header::BinaryIdOffset
Definition at line 1047 of file InstrProf.h.
Referenced by readFromBuffer(), and size().
HashOffset
uint64_t llvm::IndexedInstrProf::Header::HashOffset
Definition at line 1045 of file InstrProf.h.
Referenced by readFromBuffer(), and size().
HashType
uint64_t llvm::IndexedInstrProf::Header::HashType
Definition at line 1044 of file InstrProf.h.
Referenced by readFromBuffer().
Magic
uint64_t llvm::IndexedInstrProf::Header::Magic
Definition at line 1041 of file InstrProf.h.
Referenced by readFromBuffer().
MemProfOffset
uint64_t llvm::IndexedInstrProf::Header::MemProfOffset
Definition at line 1046 of file InstrProf.h.
Referenced by readFromBuffer(), and size().
TemporalProfTracesOffset
uint64_t llvm::IndexedInstrProf::Header::TemporalProfTracesOffset
Definition at line 1048 of file InstrProf.h.
Referenced by readFromBuffer(), and size().
Unused
uint64_t llvm::IndexedInstrProf::Header::Unused
Definition at line 1043 of file InstrProf.h.
Version
uint64_t llvm::IndexedInstrProf::Header::Version
Definition at line 1042 of file InstrProf.h.
Referenced by formatVersion(), and readFromBuffer().
The documentation for this struct was generated from the following files:
include/llvm/ProfileData/InstrProf.h
lib/ProfileData/InstrProf.cpp