LLVM: llvm::Loc::EntryValue Struct Reference
llvm::Loc::EntryValue Struct Reference
Single location defined by (potentially multiple) EntryValueInfo.
#include "CodeGen/AsmPrinter/DwarfDebug.h"
Public Member Functions
EntryValue (MCRegister Reg, const DIExpression &Expr)
void addExpr (MCRegister Reg, const DIExpression &Expr)
Public Attributes
std::set< EntryValueInfo > EntryValues
Detailed Description
Single location defined by (potentially multiple) EntryValueInfo.
Definition at line 172 of file DwarfDebug.h.
Constructor & Destructor Documentation
EntryValue()
llvm::Loc::EntryValue::EntryValue (MCRegister Reg, const DIExpression & Expr) inline explicit
Definition at line 174 of file DwarfDebug.h.
References addExpr(), and Reg.
Member Function Documentation
addExpr()
void llvm::Loc::EntryValue::addExpr (MCRegister Reg, const DIExpression & Expr) inline
Definition at line 180 of file DwarfDebug.h.
References assert(), llvm::DIExpression::convertToNonVariadicExpression(), EntryValues, and Reg.
Referenced by EntryValue().
Member Data Documentation
EntryValues
std::set<EntryValueInfo> llvm::Loc::EntryValue::EntryValues
Definition at line 173 of file DwarfDebug.h.
Referenced by addExpr().
The documentation for this struct was generated from the following file:
lib/CodeGen/AsmPrinter/DwarfDebug.h