LLVM: llvm::FileCheckString Struct Reference
llvm::FileCheckString Struct Reference
A check that we found in the input file.
#include "FileCheck/FileCheckImpl.h"
Classes
struct DagNotPrefixInfo
Hold the information about the DAG/NOT strings in the program, which are not explicitly stored otherwise.
Public Member Functions
FileCheckString (const Pattern &P, StringRef S, SMLoc L)
size_t Check (const SourceMgr &SM, StringRef Buffer, bool IsLabelScanMode, size_t &MatchLen, FileCheckRequest &Req, std::vector< FileCheckDiag > *Diags) const
Matches check string and its "not strings" and/or "dag strings".
bool CheckNext (const SourceMgr &SM, StringRef Buffer) const
Verifies that there is a single line in the given Buffer.
bool CheckSame (const SourceMgr &SM, StringRef Buffer) const
Verifies that there is no newline in the given Buffer.
bool CheckNot (const SourceMgr &SM, StringRef Buffer, const std::vector< const DagNotPrefixInfo * > &NotStrings, const FileCheckRequest &Req, std::vector< FileCheckDiag > *Diags) const
Verifies that none of the strings in NotStrings are found in the given Buffer.
size_t CheckDag (const SourceMgr &SM, StringRef Buffer, std::vector< const DagNotPrefixInfo * > &NotStrings, const FileCheckRequest &Req, std::vector< FileCheckDiag > *Diags) const
Matches "dag strings" and their mixed "not strings".
Public Attributes
Pattern Pat
The pattern to match.
StringRef Prefix
Which prefix name this check matched.
SMLoc Loc
The location in the match file that the check string was specified.
std::vector< DagNotPrefixInfo > DagNotStrings
Hold the DAG/NOT strings occurring in the input file.
Detailed Description
A check that we found in the input file.
Definition at line 816 of file FileCheckImpl.h.
Constructor & Destructor Documentation
FileCheckString()
llvm::FileCheckString::FileCheckString (const Pattern & P, StringRef S, SMLoc L) inline
Definition at line 840 of file FileCheckImpl.h.
Member Function Documentation
Check()
size_t FileCheckString::Check (const SourceMgr & SM, StringRef Buffer, bool IsLabelScanMode, size_t & MatchLen, FileCheckRequest & Req, std::vector< FileCheckDiag > * Diags) const
Matches check string and its "not strings" and/or "dag strings".
Definition at line 2164 of file FileCheck.cpp.
References assert(), llvm::cantFail(), CheckDag(), CheckNext(), CheckNot(), CheckSame(), E, llvm::Pattern::getCheckTy(), llvm::Pattern::getCount(), llvm::handleErrors(), Loc, llvm::Pattern::match(), llvm::FileCheckDiag::MatchFoundButWrongLine, llvm::StringRef::npos, Pat, Prefix, ProcessMatchResult(), reportMatchResult(), llvm::StringRef::substr(), llvm::Pattern::MatchResult::TheMatch, and llvm::FileCheckRequest::Verbose.
Referenced by llvm::FileCheck::checkInput().
CheckDag()
size_t FileCheckString::CheckDag (const SourceMgr & SM, StringRef Buffer, std::vector< const DagNotPrefixInfo * > & NotStrings, const FileCheckRequest & Req, std::vector< FileCheckDiag > * Diags) const
Matches "dag strings" and their mixed "not strings".
Definition at line 2328 of file FileCheck.cpp.
References llvm::FileCheckRequest::AllowDeprecatedDagOverlap, assert(), llvm::Block, llvm::cantFail(), llvm::Check::CheckDAG, llvm::Check::CheckNot, CheckNot(), DagNotStrings, llvm::StringRef::data(), llvm::SourceMgr::DK_Note, E, End, llvm::Pattern::getCheckTy(), llvm::SMLoc::getFromPointer(), llvm::Pattern::getLoc(), llvm::handleErrors(), I, llvm::Pattern::match(), llvm::FileCheckDiag::MatchFoundButDiscarded, MI, llvm::StringRef::npos, Pat, printMatch(), llvm::SourceMgr::PrintMessage(), reportMatchResult(), llvm::StringRef::slice(), llvm::StringRef::substr(), llvm::Error::success(), llvm::Pattern::MatchResult::TheError, llvm::Pattern::MatchResult::TheMatch, and llvm::FileCheckRequest::VerboseVerbose.
Referenced by Check().
CheckNext()
bool FileCheckString::CheckNext (const SourceMgr & SM, StringRef Buffer) const
Verifies that there is a single line in the given Buffer.
Errors are reported against SM.
Definition at line 2245 of file FileCheck.cpp.
References llvm::Check::CheckEmpty, llvm::Check::CheckNext, CountNumNewlinesBetween(), llvm::StringRef::data(), llvm::SourceMgr::DK_Error, llvm::SourceMgr::DK_Note, llvm::StringRef::end(), llvm::Pattern::getCheckTy(), llvm::SMLoc::getFromPointer(), Loc, Pat, Prefix, and llvm::SourceMgr::PrintMessage().
Referenced by Check().
CheckNot()
bool FileCheckString::CheckNot (const SourceMgr & SM, StringRef Buffer, const std::vector< const DagNotPrefixInfo * > & NotStrings, const FileCheckRequest & Req, std::vector< FileCheckDiag > * Diags) const
Verifies that none of the strings in NotStrings are found in the given Buffer.
Errors are reported against SM and diagnostics recorded in Diags according to the verbosity level set in Req.
Definition at line 2306 of file FileCheck.cpp.
References assert(), llvm::cantFail(), llvm::Check::CheckNot, E, llvm::handleErrors(), and reportMatchResult().
Referenced by Check(), and CheckDag().
CheckSame()
bool FileCheckString::CheckSame (const SourceMgr & SM, StringRef Buffer) const
Verifies that there is no newline in the given Buffer.
Errors are reported against SM.
Definition at line 2284 of file FileCheck.cpp.
References llvm::Check::CheckSame, CountNumNewlinesBetween(), llvm::StringRef::data(), llvm::SourceMgr::DK_Error, llvm::SourceMgr::DK_Note, llvm::StringRef::end(), llvm::Pattern::getCheckTy(), llvm::SMLoc::getFromPointer(), Loc, Pat, Prefix, and llvm::SourceMgr::PrintMessage().
Referenced by Check().
Member Data Documentation
DagNotStrings
std::vector<DagNotPrefixInfo> llvm::FileCheckString::DagNotStrings
Hold the DAG/NOT strings occurring in the input file.
Definition at line 838 of file FileCheckImpl.h.
Referenced by CheckDag().
Loc
SMLoc llvm::FileCheckString::Loc
The location in the match file that the check string was specified.
Definition at line 824 of file FileCheckImpl.h.
Referenced by Check(), CheckNext(), and CheckSame().
Pat
Pattern llvm::FileCheckString::Pat
The pattern to match.
Definition at line 818 of file FileCheckImpl.h.
Referenced by Check(), CheckDag(), llvm::FileCheck::checkInput(), CheckNext(), and CheckSame().
Prefix
StringRef llvm::FileCheckString::Prefix
Which prefix name this check matched.
Definition at line 821 of file FileCheckImpl.h.
Referenced by Check(), CheckNext(), and CheckSame().
The documentation for this struct was generated from the following files:
lib/FileCheck/FileCheckImpl.h
lib/FileCheck/FileCheck.cpp