LLVM: llvm::object::ViewArray< T >::iterator Struct Reference
llvm::object::ViewArray< T >::iterator Struct Reference
#include "llvm/Object/DXContainer.h"
Public Member Functions
iterator (const ViewArray &A, const char *C)
iterator (const iterator &)=default
value_type operator* ()
iterator operator++ ()
iterator operator++ (int)
iterator operator-- ()
iterator operator-- (int)
bool operator== (const iterator I)
bool operator!= (const iterator I)
Public Attributes
StringRef Data
uint32_t Stride
const char * Current
Detailed Description
template<typename T>
struct llvm::object::ViewArray< T >::iterator
Definition at line 58 of file DXContainer.h.
Constructor & Destructor Documentation
iterator() [1/2]
template<typename T > llvm::object::ViewArray< T >::iterator::iterator (const ViewArray & A, const char * C) inline
Definition at line 63 of file DXContainer.h.
iterator() [2/2]
template<typename T > llvm::object::ViewArray< T >::iterator::iterator (const iterator &) default
Member Function Documentation
operator!=()
template<typename T > bool llvm::object::ViewArray< T >::iterator::operator!= (const iterator I) inline
Definition at line 106 of file DXContainer.h.
References I.
operator*()
template<typename T > value_type llvm::object::ViewArray< T >::iterator::operator* () inline
Definition at line 67 of file DXContainer.h.
References llvm::object::ViewArray< T >::iterator::Current, llvm::object::ViewArray< T >::iterator::Data, llvm::StringRef::end(), llvm::sys::IsBigEndianHost, llvm::object::ViewArray< T >::MaxStride(), llvm::object::ViewArray< T >::iterator::Stride, and llvm::object::detail::swapBytes().
operator++() [1/2]
template<typename T > iterator llvm::object::ViewArray< T >::iterator::operator++ () inline
Definition at line 81 of file DXContainer.h.
References llvm::object::ViewArray< T >::iterator::Current, llvm::object::ViewArray< T >::iterator::Data, llvm::StringRef::end(), and llvm::object::ViewArray< T >::iterator::Stride.
operator++() [2/2]
template<typename T > iterator llvm::object::ViewArray< T >::iterator::operator++ (int) inline
Definition at line 87 of file DXContainer.h.
operator--() [1/2]
template<typename T > iterator llvm::object::ViewArray< T >::iterator::operator-- () inline
Definition at line 93 of file DXContainer.h.
References llvm::StringRef::begin(), llvm::object::ViewArray< T >::iterator::Current, llvm::object::ViewArray< T >::iterator::Data, and llvm::object::ViewArray< T >::iterator::Stride.
operator--() [2/2]
template<typename T > iterator llvm::object::ViewArray< T >::iterator::operator-- (int) inline
Definition at line 99 of file DXContainer.h.
operator==()
template<typename T > bool llvm::object::ViewArray< T >::iterator::operator== (const iterator I) inline
Definition at line 105 of file DXContainer.h.
References llvm::object::ViewArray< T >::iterator::Current, and I.
Member Data Documentation
Current
template<typename T > const char* llvm::object::ViewArray< T >::iterator::Current
Definition at line 61 of file DXContainer.h.
Referenced by llvm::object::ViewArray< T >::iterator::operator*(), llvm::object::ViewArray< T >::iterator::operator++(), llvm::object::ViewArray< T >::iterator::operator--(), and llvm::object::ViewArray< T >::iterator::operator==().
Data
template<typename T > StringRef llvm::object::ViewArray< T >::iterator::Data
Definition at line 59 of file DXContainer.h.
Referenced by llvm::object::ViewArray< T >::iterator::operator*(), llvm::object::ViewArray< T >::iterator::operator++(), and llvm::object::ViewArray< T >::iterator::operator--().
Stride
template<typename T > uint32_t llvm::object::ViewArray< T >::iterator::Stride
Definition at line 60 of file DXContainer.h.
Referenced by llvm::object::ViewArray< T >::iterator::operator*(), llvm::object::ViewArray< T >::iterator::operator++(), and llvm::object::ViewArray< T >::iterator::operator--().
The documentation for this struct was generated from the following file:
include/llvm/Object/DXContainer.h