LLVM: llvm::AAValueConstantRange Struct Reference
llvm::AAValueConstantRange Struct Reference abstract
An abstract interface for range value analysis.
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
using Base = StateWrapper< IntegerRangeState, AbstractAttribute, uint32_t >
Public Types inherited from llvm::StateWrapper< IntegerRangeState, AbstractAttribute, uint32_t >
using StateType = IntegerRangeState
Provide static access to the type of the state.
Public Types inherited from llvm::AbstractAttribute
using StateType = AbstractState
Public Types inherited from llvm::IRPosition
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
using CallBaseContext = CallBase
Public Types inherited from llvm::AADepGraphNode
using DepTy = PointerIntPair< AADepGraphNode *, 1 >
using DepSetTy = SmallSetVector< DepTy, 2 >
using iterator = mapped_iterator< DepSetTy::iterator, decltype(&DepGetVal)>
using aaiterator = mapped_iterator< DepSetTy::iterator, decltype(&DepGetValAA)>
Public Member Functions
AAValueConstantRange (const IRPosition &IRP, Attributor &A)
IntegerRangeState & getState () override
See AbstractAttribute::getState(...).
const IntegerRangeState & getState () const override
virtual ConstantRange getAssumedConstantRange (Attributor &A, const Instruction *CtxI=nullptr) const =0
Return an assumed range for the associated value a program point CtxI.
virtual ConstantRange getKnownConstantRange (Attributor &A, const Instruction *CtxI=nullptr) const =0
Return a known range for the associated value at a program point CtxI.
std::optional< Constant * > getAssumedConstant (Attributor &A, const Instruction *CtxI=nullptr) const
Return an assumed constant for the associated value a program point CtxI.
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::StateWrapper< IntegerRangeState, AbstractAttribute, uint32_t >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (const IRPosition &IRP)
virtual ~AbstractAttribute ()=default
Virtual destructor.
virtual void initialize (Attributor &A)
Initialize the state with the information in the Attributor A.
virtual bool isQueryAA () const
A query AA is always scheduled as long as we do updates because it does lazy computation that cannot be determined to be done from the outside.
virtual StateType & getState ()=0
Return the internal abstract state for inspection.
virtual const StateType & getState () const =0
const IRPosition & getIRPosition () const
Return an IR position, see struct IRPosition.
IRPosition & getIRPosition ()
void print (raw_ostream &OS) const
Helper functions, for debug purposes only.
void print (Attributor *, raw_ostream &OS) const override
virtual void printWithDeps (raw_ostream &OS) const
void dump () const
virtual const std::string getAsStr (Attributor *A) const =0
This function should return the "summarized" assumed state as string.
virtual const std::string getName () const =0
This function should return the name of the AbstractAttribute.
virtual const char * getIdAddr () const =0
This function should return the address of the ID of the AbstractAttribute.
Public Member Functions inherited from llvm::IRPosition
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
bool isFunctionScope () const
Return true if this is a function or call site position.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getCalleeArgNo () const
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
int getCallSiteArgNo () const
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Value * getAttrListAnchor () const
Return the value attributes are attached to.
AttributeList getAttrList () const
Return the attributes associated with this function or call site scope.
void setAttrList (const AttributeList &AttrList) const
Update the attributes associated with this function or call site scope.
unsigned getNumArgs () const
Return the number of arguments associated with this function or call site scope.
Value * getArg (unsigned ArgNo) const
Return theargument ArgNo associated with this function or call site scope.
Kind getPositionKind () const
Return the associated position kind.
bool isAnyCallSitePosition () const
bool isArgumentPosition () const
Return true if the position is an argument or call site argument.
IRPosition stripCallBaseContext () const
Return the same position without the call base context.
const CallBaseContext * getCallBaseContext () const
Get the call base context from the position.
bool hasCallBaseContext () const
Check if the position has any call base context.
operator void * () const
}
Public Member Functions inherited from llvm::AADepGraphNode
virtual ~AADepGraphNode ()=default
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
void print (raw_ostream &OS) const
virtual void print (Attributor *, raw_ostream &OS) const
DepSetTy & getDeps ()
Public Member Functions inherited from llvm::IntegerRangeState
IntegerRangeState (uint32_t BitWidth)
IntegerRangeState (const ConstantRange &CR)
uint32_t getBitWidth () const
Return associated values' bit width.
bool isValidState () const override
See AbstractState::isValidState()
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint()
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
ConstantRange getKnown () const
Return the known state encoding.
ConstantRange getAssumed () const
Return the assumed state encoding.
void unionAssumed (const ConstantRange &R)
Unite assumed range with the passed state.
void unionAssumed (const IntegerRangeState &R)
See IntegerRangeState::unionAssumed(..).
void intersectKnown (const ConstantRange &R)
Intersect known range with the passed state.
void intersectKnown (const IntegerRangeState &R)
See IntegerRangeState::intersectKnown(..).
bool operator== (const IntegerRangeState &R) const
Equality for IntegerRangeState.
IntegerRangeState operator^= (const IntegerRangeState &R)
"Clamp" this state with R.
IntegerRangeState operator&= (const IntegerRangeState &R)
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
virtual bool isValidState () const =0
Return if this abstract state is in a valid state.
virtual bool isAtFixpoint () const =0
Return if this abstract state is fixed, thus does not need to be updated if information changes as it cannot change itself.
virtual ChangeStatus indicateOptimisticFixpoint ()=0
Indicate that the abstract state should converge to the optimistic state.
virtual ChangeStatus indicatePessimisticFixpoint ()=0
Indicate that the abstract state should converge to the pessimistic state.
Static Public Member Functions
static bool isValidIRPositionForInit (Attributor &A, const IRPosition &IRP)
See AbstractAttribute::isValidIRPositionForInit.
static bool requiresCallersForArgOrFunction ()
See AbstractAttribute::requiresCallersForArgOrFunction.
static AAValueConstantRange & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAValueConstantRange.
Static Public Member Functions inherited from llvm::AbstractAttribute
static bool classof (const AADepGraphNode *DGN)
This function is used to identify if an DGN is of type AbstractAttribute so that the dyn_cast and cast can use such information to cast an AADepGraphNode to an AbstractAttribute.
static bool hasTrivialInitializer ()
Return false if this AA does anything non-trivial (hence not done by default) in its initializer.
static bool requiresCalleeForCallBase ()
Return true if this AA requires a "callee" (or an associted function) for a call site positon.
static bool requiresNonAsmForCallBase ()
Return true if this AA requires non-asm "callee" for a call site positon.
static bool requiresCallersForArgOrFunction ()
Return true if this AA requires all callees for an argument or function positon.
static bool isValidIRPositionForInit (Attributor &A, const IRPosition &IRP)
Return false if an AA should not be created for IRP.
static bool isValidIRPositionForUpdate (Attributor &A, const IRPosition &IRP)
Return false if an AA should not be updated for IRP.
Static Public Member Functions inherited from llvm::IRPosition
static const IRPosition value (const Value &V, const CallBaseContext *CBContext=nullptr)
Create a position describing the value of V.
static const IRPosition inst (const Instruction &I, const CallBaseContext *CBContext=nullptr)
Create a position describing the instruction I.
static const IRPosition function (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg, const CallBaseContext *CBContext=nullptr)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP, const CallBaseContext *CBContext=nullptr)
Create a position with function scope matching the "context" of IRP.
Static Public Member Functions inherited from llvm::IntegerRangeState
static ConstantRange getWorstState (uint32_t BitWidth)
Return the worst possible representable state.
static ConstantRange getBestState (uint32_t BitWidth)
Return the best possible representable state.
static ConstantRange getBestState (const IntegerRangeState &IRS)
Static Public Attributes
static const char ID = 0
Unique ID (due to the unique address)
Static Public Attributes inherited from llvm::AbstractAttribute
static constexpr Attribute::AttrKind IRAttributeKind = Attribute::None
Compile time access to the IR attribute kind.
Static Public Attributes inherited from llvm::IRPosition
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Additional Inherited Members
Public Attributes inherited from llvm::IntegerRangeState
uint32_t BitWidth
Bitwidth of the associated value.
ConstantRange Assumed
State representing assumed range, initially set to empty.
ConstantRange Known
State representing known range, initially set to [-inf, inf].
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
virtual ChangeStatus manifest (Attributor &A)
Hook for the Attributor to trigger the manifestation of the information represented by the abstract attribute in the LLVM-IR.
virtual void trackStatistics () const =0
Hook to enable custom statistic tracking, called after manifest that resulted in a change if statistics are enabled.
virtual ChangeStatus updateImpl (Attributor &A)=0
The actual update/transfer function which has to be implemented by the derived classes.
Protected Member Functions inherited from llvm::AADepGraphNode
operator AbstractAttribute * ()
Static Protected Member Functions inherited from llvm::AADepGraphNode
static AADepGraphNode * DepGetVal (const DepTy &DT)
static AbstractAttribute * DepGetValAA (const DepTy &DT)
Protected Attributes inherited from llvm::AADepGraphNode
DepSetTy Deps
Set of dependency graph nodes which should be updated if this one is updated.
Detailed Description
An abstract interface for range value analysis.
Definition at line 4883 of file Attributor.h.
Member Typedef Documentation
Base
using llvm::AAValueConstantRange::Base = StateWrapper<IntegerRangeState, AbstractAttribute, uint32_t>
Definition at line 4885 of file Attributor.h.
Constructor & Destructor Documentation
AAValueConstantRange()
llvm::AAValueConstantRange::AAValueConstantRange (const IRPosition & IRP, Attributor & A) inline
Definition at line 4886 of file Attributor.h.
Member Function Documentation
classof()
static bool llvm::AAValueConstantRange::classof (const AbstractAttribute * AA) inline static
This function should return true if the type of the AA is AAValueConstantRange.
Definition at line 4942 of file Attributor.h.
References llvm::AbstractAttribute::getIdAddr().
createForPosition()
static AAValueConstantRange & llvm::AAValueConstantRange::createForPosition (const IRPosition & IRP, Attributor & A) static
Create an abstract attribute view for the position IRP.
getAssumedConstant()
std::optional< Constant * > llvm::AAValueConstantRange::getAssumedConstant (Attributor & A, const Instruction * CtxI = nullptr) const inline
Return an assumed constant for the associated value a program point CtxI.
Definition at line 4922 of file Attributor.h.
References A, llvm::CallingConv::C, llvm::ConstantInt::get(), llvm::IRPosition::getAssociatedValue(), getAssumedConstantRange(), llvm::Type::getContext(), llvm::ConstantRange::getSingleElement(), llvm::Value::getType(), llvm::AA::getWithType(), and llvm::ConstantRange::isEmptySet().
getAssumedConstantRange()
virtual ConstantRange llvm::AAValueConstantRange::getAssumedConstantRange (Attributor & A, const Instruction * CtxI = nullptr) const pure virtual
Return an assumed range for the associated value a program point CtxI.
If I is nullptr, simply return an assumed range.
Referenced by getAssumedConstant().
getIdAddr()
const char * llvm::AAValueConstantRange::getIdAddr () const inline override virtual
See AbstractAttribute::getIdAddr()
Implements llvm::AbstractAttribute.
Definition at line 4938 of file Attributor.h.
References ID.
getKnownConstantRange()
virtual ConstantRange llvm::AAValueConstantRange::getKnownConstantRange (Attributor & A, const Instruction * CtxI = nullptr) const pure virtual
Return a known range for the associated value at a program point CtxI.
If I is nullptr, simply return a known range.
getName()
const std::string llvm::AAValueConstantRange::getName () const inline override virtual
See AbstractAttribute::getName()
Implements llvm::AbstractAttribute.
Definition at line 4935 of file Attributor.h.
getState() [1/2]
const IntegerRangeState & llvm::AAValueConstantRange::getState () const inline override virtual
Implements llvm::AbstractAttribute.
Definition at line 4901 of file Attributor.h.
getState() [2/2]
IntegerRangeState & llvm::AAValueConstantRange::getState () inline override virtual
See AbstractAttribute::getState(...).
Implements llvm::AbstractAttribute.
Definition at line 4900 of file Attributor.h.
isValidIRPositionForInit()
static bool llvm::AAValueConstantRange::isValidIRPositionForInit (Attributor & A, const IRPosition & IRP) inline static
See AbstractAttribute::isValidIRPositionForInit.
Definition at line 4890 of file Attributor.h.
References A, llvm::IRPosition::getAssociatedType(), llvm::Type::isIntegerTy(), and llvm::AbstractAttribute::isValidIRPositionForInit().
requiresCallersForArgOrFunction()
static bool llvm::AAValueConstantRange::requiresCallersForArgOrFunction () inline static
See AbstractAttribute::requiresCallersForArgOrFunction.
Definition at line 4897 of file Attributor.h.
Member Data Documentation
ID
const char AAValueConstantRange::ID = 0 static
Unique ID (due to the unique address)
Definition at line 4947 of file Attributor.h.
Referenced by getIdAddr().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/AttributorAttributes.cpp