LLVM: llvm::MIPatternMatch::UnaryOp_match< SrcTy, Opcode > Struct Template Reference
llvm::MIPatternMatch::UnaryOp_match< SrcTy, Opcode > Struct Template Reference
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
Public Member Functions
UnaryOp_match (const SrcTy &LHS)
template<typename OpTy >
bool match (const MachineRegisterInfo &MRI, OpTy &&Op)
Public Attributes
SrcTy L
Detailed Description
template<typename SrcTy, unsigned Opcode>
struct llvm::MIPatternMatch::UnaryOp_match< SrcTy, Opcode >
Definition at line 553 of file MIPatternMatch.h.
Constructor & Destructor Documentation
UnaryOp_match()
template<typename SrcTy , unsigned Opcode> llvm::MIPatternMatch::UnaryOp_match< SrcTy, Opcode >::UnaryOp_match (const SrcTy & LHS) inline
Definition at line 556 of file MIPatternMatch.h.
Member Function Documentation
match()
template<typename SrcTy , unsigned Opcode> template<typename OpTy > bool llvm::MIPatternMatch::UnaryOp_match< SrcTy, Opcode >::match (const MachineRegisterInfo & MRI, OpTy && Op) inline
Definition at line 558 of file MIPatternMatch.h.
References llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MIPatternMatch::UnaryOp_match< SrcTy, Opcode >::L, llvm::MIPatternMatch::m_MInstr(), llvm::MIPatternMatch::mi_match(), and MRI.
Member Data Documentation
L
template<typename SrcTy , unsigned Opcode> SrcTy llvm::MIPatternMatch::UnaryOp_match< SrcTy, Opcode >::L
Definition at line 554 of file MIPatternMatch.h.
Referenced by llvm::MIPatternMatch::UnaryOp_match< SrcTy, Opcode >::match().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/GlobalISel/MIPatternMatch.h