LLVM: llvm::rdf::RegisterRef Struct Reference
llvm::rdf::RegisterRef Struct Reference
#include "llvm/CodeGen/RDFRegisters.h"
Public Member Functions
constexpr RegisterRef ()=default
constexpr RegisterRef (RegisterId R, LaneBitmask M=LaneBitmask::getAll())
constexpr bool isReg () const
constexpr bool isUnit () const
constexpr bool isMask () const
constexpr unsigned idx () const
constexpr operator bool () const
size_t hash () const
bool operator< (RegisterRef) const =delete
bool operator== (RegisterRef) const =delete
bool operator!= (RegisterRef) const =delete
Static Public Member Functions
static constexpr bool isRegId (unsigned Id)
static constexpr bool isUnitId (unsigned Id)
static constexpr bool isMaskId (unsigned Id)
static constexpr RegisterId toUnitId (unsigned Idx)
static constexpr unsigned toIdx (RegisterId Id)
Public Attributes
RegisterId Reg = 0
LaneBitmask Mask = LaneBitmask::getNone()
Detailed Description
Definition at line 88 of file RDFRegisters.h.
Constructor & Destructor Documentation
RegisterRef() [1/2]
constexpr llvm::rdf::RegisterRef::RegisterRef () constexpr default
RegisterRef() [2/2]
constexpr llvm::rdf::RegisterRef::RegisterRef (RegisterId R, LaneBitmask M = LaneBitmask::getAll()) inline explicit constexpr
Definition at line 93 of file RDFRegisters.h.
Member Function Documentation
hash()
size_t llvm::rdf::RegisterRef::hash () const inline
Definition at line 108 of file RDFRegisters.h.
References llvm::LaneBitmask::getAsInteger(), Mask, and Reg.
idx()
constexpr unsigned llvm::rdf::RegisterRef::idx () const inline constexpr
Definition at line 102 of file RDFRegisters.h.
References Reg, and toIdx().
Referenced by llvm::rdf::PhysicalRegisterInfo::getUnits(), and llvm::rdf::DataFlowGraph::hasUntrackedRef().
isMask()
constexpr bool llvm::rdf::RegisterRef::isMask () const inline constexpr
Definition at line 100 of file RDFRegisters.h.
References isMaskId(), and Reg.
Referenced by llvm::rdf::PhysicalRegisterInfo::getUnits(), llvm::rdf::RegisterAggr::hasAliasOf(), llvm::rdf::RegisterAggr::hasCoverOf(), and llvm::rdf::RegisterAggr::insert().
isMaskId()
static constexpr bool llvm::rdf::RegisterRef::isMaskId (unsigned Id) inline static constexpr
Definition at line 119 of file RDFRegisters.h.
References llvm::Register::isStackSlot().
Referenced by llvm::rdf::PhysicalRegisterInfo::getAliasSet(), isMask(), and llvm::rdf::DataFlowGraph::makeRegRef().
isReg()
constexpr bool llvm::rdf::RegisterRef::isReg () const inline constexpr
Definition at line 98 of file RDFRegisters.h.
References isRegId(), and Reg.
Referenced by llvm::rdf::PhysicalRegisterInfo::getUnits(), llvm::rdf::DataFlowGraph::hasUntrackedRef(), and operator bool().
isRegId()
static constexpr bool llvm::rdf::RegisterRef::isRegId (unsigned Id) inline static constexpr
Definition at line 113 of file RDFRegisters.h.
References llvm::Register::isPhysicalRegister().
Referenced by llvm::rdf::PhysicalRegisterInfo::getAliasSet(), isReg(), and llvm::rdf::DataFlowGraph::makeRegRef().
isUnit()
constexpr bool llvm::rdf::RegisterRef::isUnit () const inline constexpr
Definition at line 99 of file RDFRegisters.h.
References isUnitId(), and Reg.
isUnitId()
static constexpr bool llvm::rdf::RegisterRef::isUnitId (unsigned Id) inline static constexpr
Definition at line 116 of file RDFRegisters.h.
References llvm::Register::isVirtualRegister().
Referenced by llvm::rdf::PhysicalRegisterInfo::getAliasSet(), isUnit(), and toIdx().
operator bool()
constexpr llvm::rdf::RegisterRef::operator bool () const inline constexpr
Definition at line 104 of file RDFRegisters.h.
References llvm::LaneBitmask::any(), isReg(), Mask, and Reg.
operator!=()
bool llvm::rdf::RegisterRef::operator!= (RegisterRef) const delete
operator<()
bool llvm::rdf::RegisterRef::operator< (RegisterRef) const delete
operator==()
bool llvm::rdf::RegisterRef::operator== (RegisterRef) const delete
toIdx()
static constexpr unsigned llvm::rdf::RegisterRef::toIdx (RegisterId Id) inline static constexpr
Definition at line 127 of file RDFRegisters.h.
References isUnitId().
Referenced by idx().
toUnitId()
static constexpr RegisterId llvm::rdf::RegisterRef::toUnitId (unsigned Idx) inline static constexpr
Definition at line 123 of file RDFRegisters.h.
References Idx, and llvm::MCRegister::VirtualRegFlag.
Member Data Documentation
Mask
LaneBitmask llvm::rdf::RegisterRef::Mask = LaneBitmask::getNone()
Definition at line 90 of file RDFRegisters.h.
Referenced by llvm::rdf::Liveness::computePhiInfo(), llvm::rdf::PhysicalRegisterInfo::getUnits(), llvm::rdf::RegisterAggr::hasAliasOf(), llvm::rdf::RegisterAggr::hasCoverOf(), hash(), llvm::rdf::RegisterAggr::insert(), llvm::rdf::PhysicalRegisterInfo::mapTo(), operator bool(), and llvm::rdf::DataFlowGraph::pack().
Reg
RegisterId llvm::rdf::RegisterRef::Reg = 0
Definition at line 89 of file RDFRegisters.h.
Referenced by llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::PhysicalRegisterInfo::getUnits(), llvm::rdf::RegisterAggr::hasAliasOf(), llvm::rdf::RegisterAggr::hasCoverOf(), hash(), idx(), llvm::rdf::RegisterAggr::insert(), llvm::rdf::CopyPropagation::interpretAsCopy(), isMask(), isReg(), isUnit(), llvm::rdf::PhysicalRegisterInfo::mapTo(), operator bool(), and llvm::rdf::DataFlowGraph::pack().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/RDFRegisters.h