LLVM: llvm::COFFYAML::SectionDataEntry Struct Reference
llvm::COFFYAML::SectionDataEntry Struct Reference
#include "llvm/ObjectYAML/COFFYAML.h"
Public Member Functions
size_t size () const
void writeAsBinary (raw_ostream &OS) const
Public Attributes
std::optional< uint32_t > UInt32
yaml::BinaryRef Binary
std::optional< object::coff_load_configuration32 > LoadConfig32
std::optional< object::coff_load_configuration64 > LoadConfig64
Detailed Description
Definition at line 70 of file COFFYAML.h.
Member Function Documentation
size()
size_t COFFYAML::SectionDataEntry::size () const
Definition at line 593 of file COFFEmitter.cpp.
References Binary, llvm::yaml::BinaryRef::binary_size(), LoadConfig32, LoadConfig64, Size, and UInt32.
writeAsBinary()
void COFFYAML::SectionDataEntry::writeAsBinary (raw_ostream & OS) const
Definition at line 611 of file COFFEmitter.cpp.
References binary_le(), OS, and writeLoadConfig().
Member Data Documentation
Binary
yaml::BinaryRef llvm::COFFYAML::SectionDataEntry::Binary
Definition at line 72 of file COFFYAML.h.
Referenced by size().
LoadConfig32
std::optional<object::coff_load_configuration32> llvm::COFFYAML::SectionDataEntry::LoadConfig32
Definition at line 73 of file COFFYAML.h.
Referenced by size().
LoadConfig64
std::optional<object::coff_load_configuration64> llvm::COFFYAML::SectionDataEntry::LoadConfig64
Definition at line 74 of file COFFYAML.h.
Referenced by size().
UInt32
std::optional<uint32_t> llvm::COFFYAML::SectionDataEntry::UInt32
Definition at line 71 of file COFFYAML.h.
Referenced by size().
The documentation for this struct was generated from the following files:
include/llvm/ObjectYAML/COFFYAML.h
lib/ObjectYAML/COFFEmitter.cpp