LLVM: LiveDebugValues::ResolvedDbgOp Struct Reference
LiveDebugValues::ResolvedDbgOp Struct Reference
A DbgOp whose ID (if any) has resolved to an actual location, LocIdx.
#include "CodeGen/LiveDebugValues/InstrRefBasedImpl.h"
Public Member Functions
ResolvedDbgOp (LocIdx Loc)
ResolvedDbgOp (MachineOperand MO)
bool operator== (const ResolvedDbgOp &Other) const
void dump (const MLocTracker *MTrack) const
Public Attributes
union {
LocIdx Loc
MachineOperand MO
};
bool IsConst
Detailed Description
A DbgOp whose ID (if any) has resolved to an actual location, LocIdx.
Used when working with concrete debug values, i.e. when joining MLocs and VLocs in the TransferTracker or emitting DBG_VALUE/DBG_VALUE_LIST instructions in the MLocTracker.
Definition at line 343 of file InstrRefBasedImpl.h.
Constructor & Destructor Documentation
ResolvedDbgOp() [1/2]
LiveDebugValues::ResolvedDbgOp::ResolvedDbgOp (LocIdx Loc) inline
Definition at line 350 of file InstrRefBasedImpl.h.
ResolvedDbgOp() [2/2]
LiveDebugValues::ResolvedDbgOp::ResolvedDbgOp (MachineOperand MO) inline
Definition at line 351 of file InstrRefBasedImpl.h.
Member Function Documentation
dump()
void ResolvedDbgOp::dump (const MLocTracker * MTrack) const
Definition at line 945 of file InstrRefBasedImpl.cpp.
References llvm::dbgs(), IsConst, Loc, LiveDebugValues::MLocTracker::LocIdxToName(), and MO.
operator==()
bool LiveDebugValues::ResolvedDbgOp::operator== (const ResolvedDbgOp & Other) const inline
Definition at line 353 of file InstrRefBasedImpl.h.
References IsConst, llvm::MachineOperand::isIdenticalTo(), Loc, MO, and llvm::Other.
Member Data Documentation
union { ... } LiveDebugValues::ResolvedDbgOp::@449
IsConst
bool LiveDebugValues::ResolvedDbgOp::IsConst
Definition at line 348 of file InstrRefBasedImpl.h.
Referenced by dump(), and operator==().
Loc
LocIdx LiveDebugValues::ResolvedDbgOp::Loc
Definition at line 345 of file InstrRefBasedImpl.h.
Referenced by dump(), and operator==().
MO
MachineOperand LiveDebugValues::ResolvedDbgOp::MO
Definition at line 346 of file InstrRefBasedImpl.h.
Referenced by dump(), and operator==().
The documentation for this struct was generated from the following files:
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.h
lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.cpp