LLVM: llvm::object::PGOAnalysisMap::Features Struct Reference
llvm::object::PGOAnalysisMap::Features Struct Reference
Bitfield of optional features to include in the PGO extended map.
#include "llvm/Object/ELFTypes.h"
Public Member Functions
bool anyEnabled () const
uint8_t encode () const
bool operator== (const Features &Other) const
Static Public Member Functions
static Expected< Features > decode (uint8_t Val)
Public Attributes
bool FuncEntryCount: 1
bool BBFreq: 1
bool BrProb: 1
Detailed Description
Bitfield of optional features to include in the PGO extended map.
Definition at line 883 of file ELFTypes.h.
Member Function Documentation
anyEnabled()
bool llvm::object::PGOAnalysisMap::Features::anyEnabled () const inline
Definition at line 889 of file ELFTypes.h.
References BBFreq, BrProb, and FuncEntryCount.
decode()
static Expected< Features > llvm::object::PGOAnalysisMap::Features::decode (uint8_t Val) inline static
Definition at line 900 of file ELFTypes.h.
References llvm::createStringError().
Referenced by decodeBBAddrMapImpl(), and llvm::AsmPrinter::emitBBAddrMapSection().
encode()
uint8_t llvm::object::PGOAnalysisMap::Features::encode () const inline
Definition at line 892 of file ELFTypes.h.
References BBFreq, BrProb, and FuncEntryCount.
operator==()
bool llvm::object::PGOAnalysisMap::Features::operator== (const Features & Other) const inline
Definition at line 911 of file ELFTypes.h.
References BBFreq, BrProb, FuncEntryCount, and Other.
Member Data Documentation
BBFreq
bool llvm::object::PGOAnalysisMap::Features::BBFreq
Definition at line 885 of file ELFTypes.h.
BrProb
bool llvm::object::PGOAnalysisMap::Features::BrProb
Definition at line 886 of file ELFTypes.h.
FuncEntryCount
bool llvm::object::PGOAnalysisMap::Features::FuncEntryCount
Definition at line 884 of file ELFTypes.h.
The documentation for this struct was generated from the following file:
include/llvm/Object/ELFTypes.h