LLVM: llvm::PatternMatch::VScaleVal_match Struct Reference
llvm::PatternMatch::VScaleVal_match Struct Reference
Matches patterns for vscale.
#include "llvm/IR/PatternMatch.h"
Public Member Functions
template<typename ITy >
bool match (ITy *V)
Detailed Description
Matches patterns for vscale.
This can either be a call to llvm.vscale or the constant expression ptrtoint(gep <vscale x 1 x i8>, <vscale x 1 x i8>* null, i32 1> under the right conditions determined by DataLayout.
Definition at line 2626 of file PatternMatch.h.
Member Function Documentation
match()
template<typename ITy > bool llvm::PatternMatch::VScaleVal_match::match (ITy * V) inline
Definition at line 2627 of file PatternMatch.h.
References GEP, llvm::PatternMatch::m_PtrToInt(), llvm::PatternMatch::m_SpecificInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::m_Zero(), match(), and Ptr.
Referenced by match().
The documentation for this struct was generated from the following file:
include/llvm/IR/PatternMatch.h