LLVM: llvm::AMDGPULibFuncBase::Param Struct Reference
llvm::AMDGPULibFuncBase::Param Struct Reference
#include "Target/AMDGPU/AMDGPULibFunc.h"
Public Member Functions
void reset ()
template<typename Stream >
void mangleItanium (Stream &os)
Static Public Member Functions
static Param getIntN (unsigned char NumElts)
static Param getFromTy (Type *Ty, bool Signed)
Public Attributes
unsigned char ArgType = 0
unsigned char VectorSize = 1
unsigned char PtrKind = 0
unsigned char Reserved = 0
Detailed Description
Definition at line 293 of file AMDGPULibFunc.h.
Member Function Documentation
getFromTy()
AMDGPULibFuncBase::Param AMDGPULibFuncBase::Param::getFromTy (Type * Ty, bool Signed) static
Definition at line 888 of file AMDGPULibFunc.cpp.
References llvm::Type::DoubleTyID, llvm::AMDGPULibFuncBase::F16, llvm::AMDGPULibFuncBase::F32, llvm::AMDGPULibFuncBase::F64, llvm::Type::FloatTyID, getBitWidth(), llvm::Type::getTypeID(), llvm::Type::HalfTyID, llvm::AMDGPULibFuncBase::I16, llvm::AMDGPULibFuncBase::I32, llvm::AMDGPULibFuncBase::I64, llvm::AMDGPULibFuncBase::I8, llvm::Type::IntegerTyID, llvm_unreachable, P, Signed, llvm::AMDGPULibFuncBase::U16, llvm::AMDGPULibFuncBase::U32, llvm::AMDGPULibFuncBase::U64, and llvm::AMDGPULibFuncBase::U8.
getIntN()
static Param llvm::AMDGPULibFuncBase::Param::getIntN (unsigned char NumElts) inline static
Definition at line 306 of file AMDGPULibFunc.h.
References llvm::AMDGPULibFuncBase::I32.
mangleItanium()
template<typename Stream > void llvm::AMDGPULibFuncBase::Param::mangleItanium (Stream & os)
reset()
void llvm::AMDGPULibFuncBase::Param::reset () inline
Definition at line 300 of file AMDGPULibFunc.h.
References ArgType, PtrKind, and VectorSize.
Referenced by llvm::AMDGPUMangledLibFunc::AMDGPUMangledLibFunc().
Member Data Documentation
ArgType
unsigned char llvm::AMDGPULibFuncBase::Param::ArgType = 0
Definition at line 294 of file AMDGPULibFunc.h.
Referenced by getArgType(), and reset().
PtrKind
unsigned char llvm::AMDGPULibFuncBase::Param::PtrKind = 0
Definition at line 296 of file AMDGPULibFunc.h.
Referenced by reset().
Reserved
unsigned char llvm::AMDGPULibFuncBase::Param::Reserved = 0
Definition at line 298 of file AMDGPULibFunc.h.
VectorSize
unsigned char llvm::AMDGPULibFuncBase::Param::VectorSize = 1
Definition at line 295 of file AMDGPULibFunc.h.
Referenced by getVecSize(), and reset().
The documentation for this struct was generated from the following files:
lib/Target/AMDGPU/AMDGPULibFunc.h
lib/Target/AMDGPU/AMDGPULibFunc.cpp