LLVM: llvm::AArch64::ArchInfo Struct Reference
llvm::AArch64::ArchInfo Struct Reference
#include "llvm/TargetParser/AArch64TargetParser.h"
Public Member Functions
bool operator== (const ArchInfo &Other) const
bool operator!= (const ArchInfo &Other) const
bool implies (const ArchInfo &Other) const
bool is_superset (const ArchInfo &Other) const
StringRef getSubArch () const
Static Public Member Functions
static std::optional< ArchInfo > findBySubArch (StringRef SubArch)
Public Attributes
VersionTuple Version
ArchProfile Profile
StringRef Name
StringRef ArchFeature
AArch64::ExtensionBitset DefaultExts
Detailed Description
Definition at line 420 of file AArch64TargetParser.h.
Member Function Documentation
findBySubArch()
std::optional< AArch64::ArchInfo > AArch64::ArchInfo::findBySubArch (StringRef SubArch) static
Definition at line 43 of file AArch64TargetParser.cpp.
References A, and llvm::AArch64::ArchInfos.
getSubArch()
StringRef llvm::AArch64::ArchInfo::getSubArch () const inline
Definition at line 467 of file AArch64TargetParser.h.
References ArchFeature, and llvm::StringRef::substr().
implies()
bool llvm::AArch64::ArchInfo::implies (const ArchInfo & Other) const inline
Definition at line 445 of file AArch64TargetParser.h.
References assert(), llvm::VersionTuple::getMajor(), llvm::VersionTuple::getMinor(), and llvm::Other.
Referenced by is_superset().
is_superset()
bool llvm::AArch64::ArchInfo::is_superset (const ArchInfo & Other) const inline
Definition at line 462 of file AArch64TargetParser.h.
References implies(), and llvm::Other.
operator!=()
bool llvm::AArch64::ArchInfo::operator!= (const ArchInfo & Other) const inline
Definition at line 431 of file AArch64TargetParser.h.
References llvm::Other.
operator==()
bool llvm::AArch64::ArchInfo::operator== (const ArchInfo & Other) const inline
Definition at line 428 of file AArch64TargetParser.h.
References llvm::Other.
Member Data Documentation
ArchFeature
StringRef llvm::AArch64::ArchInfo::ArchFeature
Definition at line 424 of file AArch64TargetParser.h.
Referenced by getSubArch().
DefaultExts
AArch64::ExtensionBitset llvm::AArch64::ArchInfo::DefaultExts
Definition at line 426 of file AArch64TargetParser.h.
Referenced by llvm::AArch64::ExtensionSet::addArchDefaults(), and llvm::AArch64::CpuInfo::getImpliedExtensions().
Name
StringRef llvm::AArch64::ArchInfo::Name
Definition at line 423 of file AArch64TargetParser.h.
Referenced by llvm::AArch64::ExtensionSet::addArchDefaults().
Profile
ArchProfile llvm::AArch64::ArchInfo::Profile
Definition at line 422 of file AArch64TargetParser.h.
Version
VersionTuple llvm::AArch64::ArchInfo::Version
Definition at line 421 of file AArch64TargetParser.h.
The documentation for this struct was generated from the following files:
include/llvm/TargetParser/AArch64TargetParser.h
lib/TargetParser/AArch64TargetParser.cpp