LLVM: llvm::AADepGraphNode Struct Reference
llvm::AADepGraphNode Struct Reference
}
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
using DepTy = PointerIntPair< AADepGraphNode *, 1 >
using DepSetTy = SmallSetVector< DepTy, 2 >
using iterator = mapped_iterator< DepSetTy::iterator, decltype(&DepGetVal)>
using aaiterator = mapped_iterator< DepSetTy::iterator, decltype(&DepGetValAA)>
Public Member Functions
virtual ~AADepGraphNode ()=default
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
void print (raw_ostream &OS) const
virtual void print (Attributor *, raw_ostream &OS) const
DepSetTy & getDeps ()
Protected Member Functions
operator AbstractAttribute * ()
Static Protected Member Functions
static AADepGraphNode * DepGetVal (const DepTy &DT)
static AbstractAttribute * DepGetValAA (const DepTy &DT)
Protected Attributes
DepSetTy Deps
Set of dependency graph nodes which should be updated if this one is updated.
Friends
struct Attributor
struct AADepGraph
Detailed Description
}
The data structure for the nodes of a dependency graph
Definition at line 501 of file Attributor.h.
Member Typedef Documentation
aaiterator
using llvm::AADepGraphNode::aaiterator = mapped_iterator<DepSetTy::iterator, decltype(&DepGetValAA)>
Definition at line 521 of file Attributor.h.
DepSetTy
using llvm::AADepGraphNode::DepSetTy = SmallSetVector<DepTy, 2>
Definition at line 505 of file Attributor.h.
DepTy
using llvm::AADepGraphNode::DepTy = PointerIntPair<AADepGraphNode *, 1>
Definition at line 504 of file Attributor.h.
iterator
using llvm::AADepGraphNode::iterator = mapped_iterator<DepSetTy::iterator, decltype(&DepGetVal)>
Definition at line 520 of file Attributor.h.
Constructor & Destructor Documentation
~AADepGraphNode()
virtual llvm::AADepGraphNode::~AADepGraphNode () virtual default
Member Function Documentation
begin()
aaiterator llvm::AADepGraphNode::begin () inline
Definition at line 524 of file Attributor.h.
References llvm::SetVector< T, Vector, Set, N >::begin(), DepGetValAA(), and Deps.
Referenced by llvm::AAPotentialConstantValues::getAssumedConstant(), llvm::AAIsDead::isLiveInstSet(), and llvm::AACallEdges::optimisticEdgesBegin().
child_begin()
iterator llvm::AADepGraphNode::child_begin () inline
Definition at line 526 of file Attributor.h.
References llvm::SetVector< T, Vector, Set, N >::begin(), DepGetVal(), and Deps.
Referenced by llvm::AADepGraph::begin().
child_end()
iterator llvm::AADepGraphNode::child_end () inline
Definition at line 527 of file Attributor.h.
References DepGetVal(), Deps, and llvm::SetVector< T, Vector, Set, N >::end().
Referenced by llvm::AADepGraph::end().
DepGetVal()
static AADepGraphNode * llvm::AADepGraphNode::DepGetVal (const DepTy & DT) inline static protected
Definition at line 512 of file Attributor.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer().
Referenced by child_begin(), and child_end().
DepGetValAA()
static AbstractAttribute * llvm::AADepGraphNode::DepGetValAA (const DepTy & DT) inline static protected
Definition at line 513 of file Attributor.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits, Info >::getPointer().
Referenced by begin(), and end().
end()
aaiterator llvm::AADepGraphNode::end () inline
Definition at line 525 of file Attributor.h.
References DepGetValAA(), Deps, and llvm::SetVector< T, Vector, Set, N >::end().
Referenced by llvm::AAIsDead::isLiveInstSet(), and llvm::AACallEdges::optimisticEdgesEnd().
getDeps()
DepSetTy & llvm::AADepGraphNode::getDeps () inline
Definition at line 533 of file Attributor.h.
References Deps.
operator AbstractAttribute *()
llvm::AADepGraphNode::operator AbstractAttribute * () inline protected
Definition at line 517 of file Attributor.h.
print() [1/2]
virtual void llvm::AADepGraphNode::print (Attributor * , raw_ostream & OS) const inline virtual
Reimplemented in llvm::AbstractAttribute.
Definition at line 530 of file Attributor.h.
References OS.
print() [2/2]
void llvm::AADepGraphNode::print (raw_ostream & OS) const inline
Definition at line 529 of file Attributor.h.
References OS, and print().
Referenced by print().
Friends And Related Function Documentation
AADepGraph
friend struct AADepGraph friend
Definition at line 536 of file Attributor.h.
Attributor
friend struct Attributor friend
Definition at line 535 of file Attributor.h.
Member Data Documentation
Deps
DepSetTy llvm::AADepGraphNode::Deps protected
Set of dependency graph nodes which should be updated if this one is updated.
The bit encodes if it is optional.
Definition at line 510 of file Attributor.h.
Referenced by begin(), child_begin(), child_end(), end(), getDeps(), llvm::AADepGraph::print(), llvm::AbstractAttribute::printWithDeps(), and llvm::Attributor::registerAA().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h