LLVM: llvm::VFRange Struct Reference
llvm::VFRange Struct Reference
A range of powers-of-2 vectorization factors with fixed start and adjustable end.
#include "Transforms/Vectorize/VPlan.h"
Classes
class iterator
Iterator to iterate over vectorization factors in a VFRange.
Public Member Functions
bool isEmpty () const
VFRange (const ElementCount &Start, const ElementCount &End)
iterator begin ()
iterator end ()
Public Attributes
const ElementCount Start
ElementCount End
Detailed Description
A range of powers-of-2 vectorization factors with fixed start and adjustable end.
The range includes start and excludes end, e.g.,: [1, 16) = {1, 2, 4, 8}
Definition at line 87 of file VPlan.h.
Constructor & Destructor Documentation
VFRange()
llvm::VFRange::VFRange (const ElementCount & Start, const ElementCount & End) inline
Definition at line 98 of file VPlan.h.
References assert(), End, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), llvm::isPowerOf2_32(), llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::isScalable(), and Start.
Member Function Documentation
begin()
iterator llvm::VFRange::begin () inline
Definition at line 127 of file VPlan.h.
References Start.
end()
iterator llvm::VFRange::end () inline
Definition at line 128 of file VPlan.h.
References assert(), End, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), and llvm::isPowerOf2_32().
isEmpty()
bool llvm::VFRange::isEmpty () const inline
Definition at line 94 of file VPlan.h.
References End, llvm::details::FixedOrScalableQuantity< LeafTy, ValueTy >::getKnownMinValue(), and Start.
Member Data Documentation
End
ElementCount llvm::VFRange::End
Definition at line 92 of file VPlan.h.
Referenced by llvm::LoopVectorizationPlanner::buildVPlans(), end(), isEmpty(), and VFRange().
Start
const ElementCount llvm::VFRange::Start
Definition at line 89 of file VPlan.h.
Referenced by begin(), isEmpty(), and VFRange().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlan.h