LLVM: llvm::AAMemoryBehavior Struct Reference
llvm::AAMemoryBehavior Struct Reference
An abstract interface for memory access kind related attributes (readnone/readonly/writeonly).
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
enum { NO_READS = 1 << 0 , NO_WRITES = 1 << 1 , NO_ACCESSES = NO_READS | NO_WRITES , BEST_STATE = NO_ACCESSES }
State encoding bits.
Public Types inherited from llvm::StateWrapper< BitIntegerState< uint8_t, 3 >, AbstractAttribute >
using StateType = BitIntegerState< uint8_t, 3 >
Provide static access to the type of the state.
Public Types inherited from llvm::AbstractAttribute
using StateType = AbstractState
Public Types inherited from llvm::IRPosition
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
using CallBaseContext = CallBase
Public Types inherited from llvm::AADepGraphNode
using DepTy = PointerIntPair< AADepGraphNode *, 1 >
using DepSetTy = SmallSetVector< DepTy, 2 >
using iterator = mapped_iterator< DepSetTy::iterator, decltype(&DepGetVal)>
using aaiterator = mapped_iterator< DepSetTy::iterator, decltype(&DepGetValAA)>
Public Types inherited from llvm::BitIntegerState< uint8_t, 3 >
using super = IntegerStateBase< uint8_t, BestState, 0 >
using base_t = uint8_t
Public Types inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
using base_t = base_ty
Public Member Functions
AAMemoryBehavior (const IRPosition &IRP, Attributor &A)
bool isKnownReadNone () const
Return true if we know that the underlying value is not read or accessed in its respective scope.
bool isAssumedReadNone () const
Return true if we assume that the underlying value is not read or accessed in its respective scope.
bool isKnownReadOnly () const
Return true if we know that the underlying value is not accessed (=written) in its respective scope.
bool isAssumedReadOnly () const
Return true if we assume that the underlying value is not accessed (=written) in its respective scope.
bool isKnownWriteOnly () const
Return true if we know that the underlying value is not read in its respective scope.
bool isAssumedWriteOnly () const
Return true if we assume that the underlying value is not read in its respective scope.
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::IRAttribute< Attribute::None, StateWrapper< BitIntegerState< uint8_t, 3 >, AbstractAttribute >, AAMemoryBehavior >
IRAttribute (const IRPosition &IRP)
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
Attribute::AttrKind getAttrKind () const
Return the kind that identifies the abstract attribute implementation.
virtual void getDeducedAttributes (Attributor &A, LLVMContext &Ctx, SmallVectorImpl< Attribute > &Attrs) const
Return the deduced attributes in Attrs.
Public Member Functions inherited from llvm::StateWrapper< BitIntegerState< uint8_t, 3 >, AbstractAttribute >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (const IRPosition &IRP)
virtual ~AbstractAttribute ()=default
Virtual destructor.
virtual void initialize (Attributor &A)
Initialize the state with the information in the Attributor A.
virtual bool isQueryAA () const
A query AA is always scheduled as long as we do updates because it does lazy computation that cannot be determined to be done from the outside.
virtual StateType & getState ()=0
Return the internal abstract state for inspection.
virtual const StateType & getState () const =0
const IRPosition & getIRPosition () const
Return an IR position, see struct IRPosition.
IRPosition & getIRPosition ()
void print (raw_ostream &OS) const
Helper functions, for debug purposes only.
void print (Attributor *, raw_ostream &OS) const override
virtual void printWithDeps (raw_ostream &OS) const
void dump () const
virtual const std::string getAsStr (Attributor *A) const =0
This function should return the "summarized" assumed state as string.
virtual const std::string getName () const =0
This function should return the name of the AbstractAttribute.
virtual const char * getIdAddr () const =0
This function should return the address of the ID of the AbstractAttribute.
Public Member Functions inherited from llvm::IRPosition
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
bool isFunctionScope () const
Return true if this is a function or call site position.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getCalleeArgNo () const
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
int getCallSiteArgNo () const
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Value * getAttrListAnchor () const
Return the value attributes are attached to.
AttributeList getAttrList () const
Return the attributes associated with this function or call site scope.
void setAttrList (const AttributeList &AttrList) const
Update the attributes associated with this function or call site scope.
unsigned getNumArgs () const
Return the number of arguments associated with this function or call site scope.
Value * getArg (unsigned ArgNo) const
Return theargument ArgNo associated with this function or call site scope.
Kind getPositionKind () const
Return the associated position kind.
bool isAnyCallSitePosition () const
bool isArgumentPosition () const
Return true if the position is an argument or call site argument.
IRPosition stripCallBaseContext () const
Return the same position without the call base context.
const CallBaseContext * getCallBaseContext () const
Get the call base context from the position.
bool hasCallBaseContext () const
Check if the position has any call base context.
operator void * () const
}
Public Member Functions inherited from llvm::AADepGraphNode
virtual ~AADepGraphNode ()=default
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
void print (raw_ostream &OS) const
virtual void print (Attributor *, raw_ostream &OS) const
DepSetTy & getDeps ()
Public Member Functions inherited from llvm::BitIntegerState< uint8_t, 3 >
BitIntegerState ()=default
BitIntegerState (base_t Assumed)
bool isKnown (base_t BitsEncoding=BestState) const
Return true if the bits set in BitsEncoding are "known bits".
bool isAssumed (base_t BitsEncoding=BestState) const
Return true if the bits set in BitsEncoding are "assumed bits".
BitIntegerState & addKnownBits (base_t Bits)
Add the bits in BitsEncoding to the "known bits".
BitIntegerState & removeAssumedBits (base_t BitsEncoding)
Remove the bits in BitsEncoding from the "assumed bits" if not known.
BitIntegerState & removeKnownBits (base_t BitsEncoding)
Remove the bits in BitsEncoding from the "known bits".
BitIntegerState & intersectAssumedBits (base_t BitsEncoding)
Keep only "assumed bits" also set in BitsEncoding but all known ones.
Public Member Functions inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
IntegerStateBase ()=default
IntegerStateBase (base_t Assumed)
bool isValidState () const override
See AbstractState::isValidState() NOTE: For now we simply pretend that the worst possible state is invalid.
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint()
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
base_t getKnown () const
Return the known state encoding.
base_t getAssumed () const
Return the assumed state encoding.
bool operator== (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Equality for IntegerStateBase.
bool operator!= (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Inequality for IntegerStateBase.
void operator^= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator+= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator|= (const IntegerStateBase< base_t, BestState, WorstState > &R)
void operator&= (const IntegerStateBase< base_t, BestState, WorstState > &R)
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()=default
virtual bool isValidState () const =0
Return if this abstract state is in a valid state.
virtual bool isAtFixpoint () const =0
Return if this abstract state is fixed, thus does not need to be updated if information changes as it cannot change itself.
virtual ChangeStatus indicateOptimisticFixpoint ()=0
Indicate that the abstract state should converge to the optimistic state.
virtual ChangeStatus indicatePessimisticFixpoint ()=0
Indicate that the abstract state should converge to the pessimistic state.
Static Public Member Functions
static bool hasTrivialInitializer ()
See AbstractAttribute::hasTrivialInitializer.
static bool isValidIRPositionForInit (Attributor &A, const IRPosition &IRP)
See AbstractAttribute::isValidIRPositionForInit.
static AAMemoryBehavior & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAMemoryBehavior.
Static Public Member Functions inherited from llvm::IRAttribute< Attribute::None, StateWrapper< BitIntegerState< uint8_t, 3 >, AbstractAttribute >, AAMemoryBehavior >
static bool hasTrivialInitializer ()
Most boolean IRAttribute AAs don't do anything non-trivial in their initializers while non-boolean ones often do.
static bool isImpliedByUndef ()
Return true if the IR attribute(s) associated with this AA are implied for an undef value.
static bool isImpliedByPoison ()
Return true if the IR attribute(s) associated with this AA are implied for an poison value.
static bool isImpliedByIR (Attributor &A, const IRPosition &IRP, Attribute::AttrKind ImpliedAttributeKind=AK, bool IgnoreSubsumingPositions=false)
Static Public Member Functions inherited from llvm::AbstractAttribute
static bool classof (const AADepGraphNode *DGN)
This function is used to identify if an DGN is of type AbstractAttribute so that the dyn_cast and cast can use such information to cast an AADepGraphNode to an AbstractAttribute.
static bool hasTrivialInitializer ()
Return false if this AA does anything non-trivial (hence not done by default) in its initializer.
static bool requiresCalleeForCallBase ()
Return true if this AA requires a "callee" (or an associted function) for a call site positon.
static bool requiresNonAsmForCallBase ()
Return true if this AA requires non-asm "callee" for a call site positon.
static bool requiresCallersForArgOrFunction ()
Return true if this AA requires all callees for an argument or function positon.
static bool isValidIRPositionForInit (Attributor &A, const IRPosition &IRP)
Return false if an AA should not be created for IRP.
static bool isValidIRPositionForUpdate (Attributor &A, const IRPosition &IRP)
Return false if an AA should not be updated for IRP.
Static Public Member Functions inherited from llvm::IRPosition
static const IRPosition value (const Value &V, const CallBaseContext *CBContext=nullptr)
Create a position describing the value of V.
static const IRPosition inst (const Instruction &I, const CallBaseContext *CBContext=nullptr)
Create a position describing the instruction I.
static const IRPosition function (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg, const CallBaseContext *CBContext=nullptr)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP, const CallBaseContext *CBContext=nullptr)
Create a position with function scope matching the "context" of IRP.
Static Public Member Functions inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
static constexpr base_t getBestState ()
Return the best possible representable state.
static constexpr base_t getBestState (const IntegerStateBase &)
static constexpr base_t getWorstState ()
Return the worst possible representable state.
static constexpr base_t getWorstState (const IntegerStateBase &)
Static Public Attributes
static const char ID = 0
Unique ID (due to the unique address)
Static Public Attributes inherited from llvm::IRAttribute< Attribute::None, StateWrapper< BitIntegerState< uint8_t, 3 >, AbstractAttribute >, AAMemoryBehavior >
static constexpr Attribute::AttrKind IRAttributeKind
Compile time access to the IR attribute kind.
Static Public Attributes inherited from llvm::AbstractAttribute
static constexpr Attribute::AttrKind IRAttributeKind = Attribute::None
Compile time access to the IR attribute kind.
Static Public Attributes inherited from llvm::IRPosition
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Additional Inherited Members
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
virtual ChangeStatus manifest (Attributor &A)
Hook for the Attributor to trigger the manifestation of the information represented by the abstract attribute in the LLVM-IR.
virtual void trackStatistics () const =0
Hook to enable custom statistic tracking, called after manifest that resulted in a change if statistics are enabled.
virtual ChangeStatus updateImpl (Attributor &A)=0
The actual update/transfer function which has to be implemented by the derived classes.
Protected Member Functions inherited from llvm::AADepGraphNode
operator AbstractAttribute * ()
Protected Member Functions inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
virtual void handleNewAssumedValue (base_t Value)=0
Handle a new assumed value Value. Subtype dependent.
virtual void handleNewKnownValue (base_t Value)=0
Handle a new known value Value. Subtype dependent.
virtual void joinOR (base_t AssumedValue, base_t KnownValue)=0
Handle a value Value. Subtype dependent.
virtual void joinAND (base_t AssumedValue, base_t KnownValue)=0
Handle a new assumed value Value. Subtype dependent.
Static Protected Member Functions inherited from llvm::AADepGraphNode
static AADepGraphNode * DepGetVal (const DepTy &DT)
static AbstractAttribute * DepGetValAA (const DepTy &DT)
Protected Attributes inherited from llvm::AADepGraphNode
DepSetTy Deps
Set of dependency graph nodes which should be updated if this one is updated.
Protected Attributes inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
base_t Known = getWorstState()
The known state encoding in an integer of type base_t.
base_t Assumed = getBestState()
The assumed state encoding in an integer of type base_t.
Detailed Description
An abstract interface for memory access kind related attributes (readnone/readonly/writeonly).
Definition at line 4624 of file Attributor.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
State encoding bits.
A set bit in the state means the property holds. BEST_STATE is the best possible state, 0 the worst possible state.
Enumerator
NO_READS
NO_WRITES
NO_ACCESSES
BEST_STATE
Definition at line 4644 of file Attributor.h.
Constructor & Destructor Documentation
AAMemoryBehavior()
llvm::AAMemoryBehavior::AAMemoryBehavior (const IRPosition & IRP, Attributor & A) inline
Definition at line 4629 of file Attributor.h.
Member Function Documentation
classof()
static bool llvm::AAMemoryBehavior::classof (const AbstractAttribute * AA) inline static
This function should return true if the type of the AA is AAMemoryBehavior.
Definition at line 4689 of file Attributor.h.
References llvm::AbstractAttribute::getIdAddr().
createForPosition()
static AAMemoryBehavior & llvm::AAMemoryBehavior::createForPosition (const IRPosition & IRP, Attributor & A) static
Create an abstract attribute view for the position IRP.
getIdAddr()
const char * llvm::AAMemoryBehavior::getIdAddr () const inline override virtual
See AbstractAttribute::getIdAddr()
Implements llvm::AbstractAttribute.
Definition at line 4685 of file Attributor.h.
References ID.
getName()
const std::string llvm::AAMemoryBehavior::getName () const inline override virtual
See AbstractAttribute::getName()
Implements llvm::AbstractAttribute.
Definition at line 4682 of file Attributor.h.
hasTrivialInitializer()
static bool llvm::AAMemoryBehavior::hasTrivialInitializer () inline static
See AbstractAttribute::hasTrivialInitializer.
Definition at line 4632 of file Attributor.h.
isAssumedReadNone()
bool llvm::AAMemoryBehavior::isAssumedReadNone () const inline
Return true if we assume that the underlying value is not read or accessed in its respective scope.
Definition at line 4659 of file Attributor.h.
References llvm::BitIntegerState< uint8_t, 3 >::isAssumed(), and NO_ACCESSES.
isAssumedReadOnly()
bool llvm::AAMemoryBehavior::isAssumedReadOnly () const inline
Return true if we assume that the underlying value is not accessed (=written) in its respective scope.
Definition at line 4667 of file Attributor.h.
References llvm::BitIntegerState< uint8_t, 3 >::isAssumed(), and NO_WRITES.
isAssumedWriteOnly()
bool llvm::AAMemoryBehavior::isAssumedWriteOnly () const inline
Return true if we assume that the underlying value is not read in its respective scope.
Definition at line 4675 of file Attributor.h.
References llvm::BitIntegerState< uint8_t, 3 >::isAssumed(), and NO_READS.
isKnownReadNone()
bool llvm::AAMemoryBehavior::isKnownReadNone () const inline
Return true if we know that the underlying value is not read or accessed in its respective scope.
Definition at line 4655 of file Attributor.h.
References llvm::BitIntegerState< uint8_t, 3 >::isKnown(), and NO_ACCESSES.
isKnownReadOnly()
bool llvm::AAMemoryBehavior::isKnownReadOnly () const inline
Return true if we know that the underlying value is not accessed (=written) in its respective scope.
Definition at line 4663 of file Attributor.h.
References llvm::BitIntegerState< uint8_t, 3 >::isKnown(), and NO_WRITES.
isKnownWriteOnly()
bool llvm::AAMemoryBehavior::isKnownWriteOnly () const inline
Return true if we know that the underlying value is not read in its respective scope.
Definition at line 4671 of file Attributor.h.
References llvm::BitIntegerState< uint8_t, 3 >::isKnown(), and NO_READS.
isValidIRPositionForInit()
static bool llvm::AAMemoryBehavior::isValidIRPositionForInit (Attributor & A, const IRPosition & IRP) inline static
See AbstractAttribute::isValidIRPositionForInit.
Definition at line 4635 of file Attributor.h.
References A, llvm::IRPosition::getAssociatedType(), llvm::IRPosition::isFunctionScope(), and llvm::Type::isPtrOrPtrVectorTy().
Member Data Documentation
ID
const char AAMemoryBehavior::ID = 0 static
Unique ID (due to the unique address)
Definition at line 4694 of file Attributor.h.
Referenced by getIdAddr(), and runAttributorLightOnFunctions().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/AttributorAttributes.cpp