LLVM: llvm::AccelTableBase::HashData Struct Reference
llvm::AccelTableBase::HashData Struct Reference
Represents a group of entries with identical name (and hence, hash value).
#include "llvm/CodeGen/AccelTable.h"
Public Member Functions
template<typename T = AccelTableData *>
auto getValues () const
Get all AccelTableData cast as a T.
void print (raw_ostream &OS) const
void dump () const
Public Attributes
DwarfStringPoolEntryRef Name
uint32_t HashValue
std::vector< AccelTableData * > Values
MCSymbol * Sym
Detailed Description
Represents a group of entries with identical name (and hence, hash value).
Definition at line 140 of file AccelTable.h.
Member Function Documentation
dump()
void llvm::AccelTableBase::HashData::dump () const inline
Definition at line 157 of file AccelTable.h.
References llvm::dbgs(), and print().
getValues()
template<typename T = AccelTableData *> auto llvm::AccelTableBase::HashData::getValues () const inline
Get all AccelTableData cast as a T.
Definition at line 147 of file AccelTable.h.
References llvm::Data, llvm::map_range(), and Values.
print()
void AccelTableBase::HashData::print (raw_ostream & OS) const
Definition at line 819 of file AccelTable.cpp.
References llvm::format(), Name, OS, llvm::Value::print(), and Sym.
Referenced by dump().
Member Data Documentation
HashValue
uint32_t llvm::AccelTableBase::HashData::HashValue
Definition at line 142 of file AccelTable.h.
Name
DwarfStringPoolEntryRef llvm::AccelTableBase::HashData::Name
Definition at line 141 of file AccelTable.h.
Sym
MCSymbol* llvm::AccelTableBase::HashData::Sym
Definition at line 144 of file AccelTable.h.
Values
std::vector<AccelTableData *> llvm::AccelTableBase::HashData::Values
Definition at line 143 of file AccelTable.h.
Referenced by getValues().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/AccelTable.h
lib/CodeGen/AsmPrinter/AccelTable.cpp