LLVM: llvm::objcopy::ConfigManager Struct Reference
llvm::objcopy::ConfigManager Struct Reference
#include "llvm/ObjCopy/ConfigManager.h"
Public Member Functions
virtual ~ConfigManager ()
const CommonConfig & getCommonConfig () const override
Expected< const ELFConfig & > getELFConfig () const override
Expected< const COFFConfig & > getCOFFConfig () const override
Expected< const MachOConfig & > getMachOConfig () const override
Expected< const WasmConfig & > getWasmConfig () const override
Expected< const XCOFFConfig & > getXCOFFConfig () const override
Public Member Functions inherited from llvm::objcopy::MultiFormatConfig
virtual ~MultiFormatConfig ()
virtual const CommonConfig & getCommonConfig () const =0
virtual Expected< const ELFConfig & > getELFConfig () const =0
virtual Expected< const COFFConfig & > getCOFFConfig () const =0
virtual Expected< const MachOConfig & > getMachOConfig () const =0
virtual Expected< const WasmConfig & > getWasmConfig () const =0
virtual Expected< const XCOFFConfig & > getXCOFFConfig () const =0
Public Attributes
CommonConfig Common
ELFConfig ELF
COFFConfig COFF
MachOConfig MachO
WasmConfig Wasm
XCOFFConfig XCOFF
Detailed Description
Definition at line 23 of file ConfigManager.h.
Constructor & Destructor Documentation
~ConfigManager()
virtual llvm::objcopy::ConfigManager::~ConfigManager () inline virtual
Definition at line 24 of file ConfigManager.h.
Member Function Documentation
getCOFFConfig()
Expected< const COFFConfig & > llvm::objcopy::ConfigManager::getCOFFConfig () const override virtual
Implements llvm::objcopy::MultiFormatConfig.
Definition at line 16 of file ConfigManager.cpp.
References llvm::objcopy::CommonConfig::AllocSectionsPrefix, COFF, Common, llvm::createStringError(), llvm::objcopy::CommonConfig::DecompressDebugSections, llvm::objcopy::CommonConfig::DiscardMode, llvm::StringMapImpl::empty(), llvm::StringRef::empty(), llvm::objcopy::NameMatcher::empty(), llvm::objcopy::CommonConfig::ExtractDWO, llvm::objcopy::CommonConfig::GapFill, llvm::invalid_argument, llvm::objcopy::CommonConfig::KeepSection, llvm::objcopy::Locals, llvm::objcopy::CommonConfig::PadTo, llvm::objcopy::CommonConfig::PreserveDates, llvm::objcopy::CommonConfig::SectionsToRename, llvm::objcopy::CommonConfig::SetSectionAlignment, llvm::objcopy::CommonConfig::SetSectionType, llvm::objcopy::CommonConfig::SplitDWO, llvm::objcopy::CommonConfig::StripDWO, llvm::objcopy::CommonConfig::StripNonAlloc, llvm::objcopy::CommonConfig::StripSections, llvm::objcopy::CommonConfig::SymbolsPrefix, llvm::objcopy::CommonConfig::SymbolsToAdd, llvm::objcopy::CommonConfig::SymbolsToGlobalize, llvm::objcopy::CommonConfig::SymbolsToKeep, llvm::objcopy::CommonConfig::SymbolsToKeepGlobal, llvm::objcopy::CommonConfig::SymbolsToLocalize, llvm::objcopy::CommonConfig::SymbolsToWeaken, and llvm::objcopy::CommonConfig::Weaken.
getCommonConfig()
const CommonConfig & llvm::objcopy::ConfigManager::getCommonConfig () const inline override virtual
Implements llvm::objcopy::MultiFormatConfig.
Definition at line 26 of file ConfigManager.h.
References Common.
getELFConfig()
Expected< const ELFConfig & > llvm::objcopy::ConfigManager::getELFConfig () const inline override virtual
Implements llvm::objcopy::MultiFormatConfig.
Definition at line 28 of file ConfigManager.h.
References ELF.
getMachOConfig()
Expected< const MachOConfig & > llvm::objcopy::ConfigManager::getMachOConfig () const override virtual
Implements llvm::objcopy::MultiFormatConfig.
Definition at line 34 of file ConfigManager.cpp.
References llvm::objcopy::CommonConfig::AllocSectionsPrefix, Common, llvm::createStringError(), llvm::objcopy::CommonConfig::DecompressDebugSections, llvm::objcopy::CommonConfig::DiscardMode, llvm::StringMapImpl::empty(), llvm::StringRef::empty(), llvm::objcopy::NameMatcher::empty(), llvm::objcopy::CommonConfig::ExtractDWO, llvm::objcopy::CommonConfig::GapFill, llvm::invalid_argument, llvm::objcopy::CommonConfig::KeepSection, llvm::objcopy::Locals, MachO, llvm::objcopy::CommonConfig::PadTo, llvm::objcopy::CommonConfig::PreserveDates, llvm::objcopy::CommonConfig::SectionsToRename, llvm::objcopy::CommonConfig::SetSectionAlignment, llvm::objcopy::CommonConfig::SetSectionFlags, llvm::objcopy::CommonConfig::SetSectionType, llvm::objcopy::CommonConfig::SplitDWO, llvm::objcopy::CommonConfig::StripAllGNU, llvm::objcopy::CommonConfig::StripDWO, llvm::objcopy::CommonConfig::StripNonAlloc, llvm::objcopy::CommonConfig::StripSections, llvm::objcopy::CommonConfig::StripUnneeded, llvm::objcopy::CommonConfig::SymbolsPrefix, llvm::objcopy::CommonConfig::SymbolsToAdd, llvm::objcopy::CommonConfig::SymbolsToGlobalize, llvm::objcopy::CommonConfig::SymbolsToKeep, llvm::objcopy::CommonConfig::SymbolsToKeepGlobal, llvm::objcopy::CommonConfig::SymbolsToLocalize, and llvm::objcopy::CommonConfig::UnneededSymbolsToRemove.
getWasmConfig()
Expected< const WasmConfig & > llvm::objcopy::ConfigManager::getWasmConfig () const override virtual
Implements llvm::objcopy::MultiFormatConfig.
Definition at line 54 of file ConfigManager.cpp.
References llvm::objcopy::CommonConfig::AddGnuDebugLink, llvm::objcopy::CommonConfig::AllocSectionsPrefix, Common, llvm::createStringError(), llvm::objcopy::CommonConfig::DiscardMode, llvm::StringMapImpl::empty(), llvm::StringRef::empty(), llvm::objcopy::NameMatcher::empty(), llvm::objcopy::CommonConfig::ExtractPartition, llvm::objcopy::CommonConfig::GapFill, llvm::invalid_argument, llvm::objcopy::None, llvm::objcopy::CommonConfig::PadTo, llvm::objcopy::CommonConfig::SectionsToRename, llvm::objcopy::CommonConfig::SetSectionAlignment, llvm::objcopy::CommonConfig::SetSectionFlags, llvm::objcopy::CommonConfig::SetSectionType, llvm::objcopy::CommonConfig::SplitDWO, llvm::objcopy::CommonConfig::SymbolsPrefix, llvm::objcopy::CommonConfig::SymbolsToAdd, llvm::objcopy::CommonConfig::SymbolsToGlobalize, llvm::objcopy::CommonConfig::SymbolsToKeep, llvm::objcopy::CommonConfig::SymbolsToKeepGlobal, llvm::objcopy::CommonConfig::SymbolsToLocalize, llvm::objcopy::CommonConfig::SymbolsToRemove, llvm::objcopy::CommonConfig::SymbolsToRename, llvm::objcopy::CommonConfig::SymbolsToWeaken, llvm::objcopy::CommonConfig::UnneededSymbolsToRemove, and Wasm.
getXCOFFConfig()
Expected< const XCOFFConfig & > llvm::objcopy::ConfigManager::getXCOFFConfig () const override virtual
Implements llvm::objcopy::MultiFormatConfig.
Definition at line 74 of file ConfigManager.cpp.
References llvm::objcopy::CommonConfig::AddGnuDebugLink, llvm::objcopy::CommonConfig::AddSection, llvm::objcopy::CommonConfig::AllocSectionsPrefix, Common, llvm::createStringError(), llvm::objcopy::CommonConfig::DecompressDebugSections, llvm::objcopy::CommonConfig::DiscardMode, llvm::objcopy::CommonConfig::DumpSection, llvm::StringMapImpl::empty(), llvm::StringRef::empty(), llvm::objcopy::NameMatcher::empty(), llvm::objcopy::CommonConfig::ExtractDWO, llvm::objcopy::CommonConfig::ExtractMainPartition, llvm::objcopy::CommonConfig::ExtractPartition, llvm::objcopy::CommonConfig::GapFill, llvm::invalid_argument, llvm::objcopy::CommonConfig::KeepSection, llvm::objcopy::None, llvm::objcopy::CommonConfig::OnlyKeepDebug, llvm::objcopy::CommonConfig::OnlySection, llvm::objcopy::CommonConfig::PadTo, llvm::objcopy::CommonConfig::PreserveDates, llvm::objcopy::CommonConfig::SectionsToRename, llvm::objcopy::CommonConfig::SetSectionAlignment, llvm::objcopy::CommonConfig::SetSectionFlags, llvm::objcopy::CommonConfig::SetSectionType, llvm::objcopy::CommonConfig::SplitDWO, llvm::objcopy::CommonConfig::StripAllGNU, llvm::objcopy::CommonConfig::StripDebug, llvm::objcopy::CommonConfig::StripDWO, llvm::objcopy::CommonConfig::StripNonAlloc, llvm::objcopy::CommonConfig::StripSections, llvm::objcopy::CommonConfig::StripUnneeded, llvm::objcopy::CommonConfig::SymbolsPrefix, llvm::objcopy::CommonConfig::SymbolsToAdd, llvm::objcopy::CommonConfig::SymbolsToGlobalize, llvm::objcopy::CommonConfig::SymbolsToKeep, llvm::objcopy::CommonConfig::SymbolsToKeepGlobal, llvm::objcopy::CommonConfig::SymbolsToLocalize, llvm::objcopy::CommonConfig::SymbolsToRemove, llvm::objcopy::CommonConfig::SymbolsToRename, llvm::objcopy::CommonConfig::SymbolsToWeaken, llvm::objcopy::CommonConfig::ToRemove, llvm::objcopy::CommonConfig::UnneededSymbolsToRemove, llvm::objcopy::CommonConfig::Weaken, and XCOFF.
Member Data Documentation
COFF
COFFConfig llvm::objcopy::ConfigManager::COFF
Definition at line 41 of file ConfigManager.h.
Referenced by getCOFFConfig().
Common
CommonConfig llvm::objcopy::ConfigManager::Common
Definition at line 39 of file ConfigManager.h.
Referenced by getCOFFConfig(), getCommonConfig(), getMachOConfig(), getWasmConfig(), and getXCOFFConfig().
ELF
ELFConfig llvm::objcopy::ConfigManager::ELF
Definition at line 40 of file ConfigManager.h.
Referenced by getELFConfig().
MachO
MachOConfig llvm::objcopy::ConfigManager::MachO
Definition at line 42 of file ConfigManager.h.
Referenced by getMachOConfig().
Wasm
WasmConfig llvm::objcopy::ConfigManager::Wasm
Definition at line 43 of file ConfigManager.h.
Referenced by getWasmConfig().
XCOFF
XCOFFConfig llvm::objcopy::ConfigManager::XCOFF
Definition at line 44 of file ConfigManager.h.
Referenced by getXCOFFConfig().
The documentation for this struct was generated from the following files:
include/llvm/ObjCopy/ConfigManager.h
lib/ObjCopy/ConfigManager.cpp