LLVM: llvm::vfs::RedirectingFileSystem::LookupResult Struct Reference
llvm::vfs::RedirectingFileSystem::LookupResult Struct Reference
Represents the result of a path lookup into the RedirectingFileSystem.
#include "llvm/Support/VirtualFileSystem.h"
Public Member Functions
LookupResult (Entry *E, sys::path::const_iterator Start, sys::path::const_iterator End)
std::optional< StringRef > getExternalRedirect () const
If the found Entry maps the input path to a path in the external file system (i.e.
void getPath (llvm::SmallVectorImpl< char > &Path) const
Get the (canonical) path of the found entry.
Public Attributes
llvm::SmallVector< Entry *, 32 > Parents
Chain of parent directory entries for E.
Entry * E
The entry the looked-up path corresponds to.
Detailed Description
Represents the result of a path lookup into the RedirectingFileSystem.
Definition at line 874 of file VirtualFileSystem.h.
Constructor & Destructor Documentation
LookupResult()
RedirectingFileSystem::LookupResult::LookupResult (Entry * E, sys::path::const_iterator Start, sys::path::const_iterator End)
Definition at line 2227 of file VirtualFileSystem.cpp.
References llvm::sys::path::append(), assert(), E, and End.
Member Function Documentation
getExternalRedirect()
std::optional< StringRef > llvm::vfs::RedirectingFileSystem::LookupResult::getExternalRedirect () const inline
If the found Entry maps the input path to a path in the external file system (i.e.
it is a FileEntry or DirectoryRemapEntry), returns that path.
Definition at line 894 of file VirtualFileSystem.h.
References E.
getPath()
void RedirectingFileSystem::LookupResult::getPath (llvm::SmallVectorImpl< char > & Path) const
Get the (canonical) path of the found entry.
This uses the as-written path components from the VFS specification.
Definition at line 2242 of file VirtualFileSystem.cpp.
References llvm::sys::path::append(), and E.
Member Data Documentation
E
Entry* llvm::vfs::RedirectingFileSystem::LookupResult::E
The entry the looked-up path corresponds to.
Definition at line 879 of file VirtualFileSystem.h.
Referenced by getExternalRedirect(), and LookupResult().
Parents
llvm::SmallVector<Entry *, 32> llvm::vfs::RedirectingFileSystem::LookupResult::Parents
Chain of parent directory entries for E.
Definition at line 876 of file VirtualFileSystem.h.
The documentation for this struct was generated from the following files:
include/llvm/Support/VirtualFileSystem.h
lib/Support/VirtualFileSystem.cpp