LLVM: llvm::BTFParser::ParseContext Struct Reference
llvm::BTFParser::ParseContext Struct Reference
Public Member Functions
ParseContext (const ObjectFile &Obj, const ParseOptions &Opts)
Expected< DataExtractor > makeExtractor (SectionRef Sec)
std::optional< SectionRef > findSection (StringRef Name) const
Public Attributes
const ObjectFile & Obj
const ParseOptions & Opts
DenseMap< StringRef, SectionRef > Sections
Detailed Description
Definition at line 77 of file BTFParser.cpp.
Constructor & Destructor Documentation
ParseContext()
llvm::BTFParser::ParseContext::ParseContext (const ObjectFile & Obj, const ParseOptions & Opts) inline
Definition at line 84 of file BTFParser.cpp.
Member Function Documentation
findSection()
std::optional< SectionRef > llvm::BTFParser::ParseContext::findSection (StringRef Name) const inline
Definition at line 95 of file BTFParser.cpp.
References Name, and llvm::BTFParser::ParseContext::Sections.
makeExtractor()
Expected< DataExtractor > llvm::BTFParser::ParseContext::makeExtractor (SectionRef Sec) inline
Definition at line 87 of file BTFParser.cpp.
References llvm::Expected< T >::get(), llvm::object::ObjectFile::getBytesInAddress(), llvm::object::SectionRef::getContents(), llvm::object::Binary::isLittleEndian(), llvm::BTFParser::ParseContext::Obj, and llvm::Expected< T >::takeError().
Member Data Documentation
Obj
const ObjectFile& llvm::BTFParser::ParseContext::Obj
Definition at line 78 of file BTFParser.cpp.
Referenced by llvm::BTFParser::ParseContext::makeExtractor().
Opts
const ParseOptions& llvm::BTFParser::ParseContext::Opts
Definition at line 79 of file BTFParser.cpp.
Sections
DenseMap<StringRef, SectionRef> llvm::BTFParser::ParseContext::Sections
Definition at line 81 of file BTFParser.cpp.
Referenced by llvm::BTFParser::ParseContext::findSection(), and llvm::BTFParser::parse().
The documentation for this struct was generated from the following file:
lib/DebugInfo/BTF/BTFParser.cpp