LLVM: llvm::rdf::RegisterAggr::ref_iterator Struct Reference
llvm::rdf::RegisterAggr::ref_iterator Struct Reference
#include "llvm/CodeGen/RDFRegisters.h"
Public Types
using MapType = std::map< RegisterId, LaneBitmask >
Public Member Functions
ref_iterator (const RegisterAggr &RG, bool End)
RegisterRef operator* () const
ref_iterator & operator++ ()
bool operator== (const ref_iterator &I) const
bool operator!= (const ref_iterator &I) const
Detailed Description
Definition at line 238 of file RDFRegisters.h.
Member Typedef Documentation
MapType
using llvm::rdf::RegisterAggr::ref_iterator::MapType = std::map<RegisterId, LaneBitmask>
Definition at line 239 of file RDFRegisters.h.
Constructor & Destructor Documentation
ref_iterator()
llvm::rdf::RegisterAggr::ref_iterator::ref_iterator (const RegisterAggr & RG, bool End)
Definition at line 394 of file RDFRegisters.cpp.
References End, llvm::BitVector::find_first(), llvm::BitVector::find_next(), and llvm::rdf::PhysicalRegisterInfo::getRefForUnit().
Member Function Documentation
operator!=()
bool llvm::rdf::RegisterAggr::ref_iterator::operator!= (const ref_iterator & I) const inline
Definition at line 266 of file RDFRegisters.h.
References I.
operator*()
RegisterRef llvm::rdf::RegisterAggr::ref_iterator::operator* () const inline
Definition at line 250 of file RDFRegisters.h.
operator++()
ref_iterator & llvm::rdf::RegisterAggr::ref_iterator::operator++ () inline
Definition at line 254 of file RDFRegisters.h.
operator==()
bool llvm::rdf::RegisterAggr::ref_iterator::operator== (const ref_iterator & I) const inline
Definition at line 260 of file RDFRegisters.h.
References assert(), and I.
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/RDFRegisters.h
lib/CodeGen/RDFRegisters.cpp