LLVM: llvm::SizeOffsetType< T, C > Struct Template Reference
llvm::SizeOffsetType< T, C > Struct Template Reference
SizeOffsetType - A base template class for the object size visitors.
#include "llvm/Analysis/MemoryBuiltins.h"
Public Member Functions
SizeOffsetType ()=default
SizeOffsetType (T Size, T Offset)
bool knownSize () const
bool knownOffset () const
bool anyKnown () const
bool bothKnown () const
bool operator== (const SizeOffsetType< T, C > &RHS) const
bool operator!= (const SizeOffsetType< T, C > &RHS) const
Public Attributes
T Size
T Offset
Detailed Description
template<typename T, class C>
struct llvm::SizeOffsetType< T, C >
SizeOffsetType - A base template class for the object size visitors.
Used here as a self-documenting way to handle the values rather than using a std::pair.
Definition at line 193 of file MemoryBuiltins.h.
Constructor & Destructor Documentation
SizeOffsetType() [1/2]
template<typename T , class C > llvm::SizeOffsetType< T, C >::SizeOffsetType () default
SizeOffsetType() [2/2]
template<typename T , class C > llvm::SizeOffsetType< T, C >::SizeOffsetType (T Size, T Offset) inline
Definition at line 199 of file MemoryBuiltins.h.
Member Function Documentation
anyKnown()
template<typename T , class C > bool llvm::SizeOffsetType< T, C >::anyKnown () const inline
Definition at line 203 of file MemoryBuiltins.h.
References llvm::SizeOffsetType< T, C >::knownOffset(), and llvm::SizeOffsetType< T, C >::knownSize().
bothKnown()
template<typename T , class C > bool llvm::SizeOffsetType< T, C >::bothKnown () const inline
Definition at line 204 of file MemoryBuiltins.h.
References llvm::SizeOffsetType< T, C >::knownOffset(), and llvm::SizeOffsetType< T, C >::knownSize().
Referenced by getBoundsCheckCond(), llvm::ObjectSizeOffsetEvaluator::visitGEPOperator(), llvm::ObjectSizeOffsetVisitor::visitLoadInst(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), and llvm::ObjectSizeOffsetEvaluator::visitSelectInst().
knownOffset()
template<typename T , class C > bool llvm::SizeOffsetType< T, C >::knownOffset () const inline
Definition at line 202 of file MemoryBuiltins.h.
References llvm::SizeOffsetType< T, C >::Offset.
Referenced by llvm::SizeOffsetType< T, C >::anyKnown(), and llvm::SizeOffsetType< T, C >::bothKnown().
knownSize()
template<typename T , class C > bool llvm::SizeOffsetType< T, C >::knownSize () const inline
Definition at line 201 of file MemoryBuiltins.h.
References llvm::SizeOffsetType< T, C >::Size.
Referenced by llvm::SizeOffsetType< T, C >::anyKnown(), and llvm::SizeOffsetType< T, C >::bothKnown().
operator!=()
template<typename T , class C > bool llvm::SizeOffsetType< T, C >::operator!= (const SizeOffsetType< T, C > & RHS) const inline
Definition at line 209 of file MemoryBuiltins.h.
References RHS.
operator==()
template<typename T , class C > bool llvm::SizeOffsetType< T, C >::operator== (const SizeOffsetType< T, C > & RHS) const inline
Definition at line 206 of file MemoryBuiltins.h.
References llvm::SizeOffsetType< T, C >::Offset, RHS, and llvm::SizeOffsetType< T, C >::Size.
Member Data Documentation
Offset
template<typename T , class C > T llvm::SizeOffsetType< T, C >::Offset
Definition at line 196 of file MemoryBuiltins.h.
Referenced by getBoundsCheckCond(), llvm::SizeOffsetType< T, C >::knownOffset(), llvm::lowerObjectSizeCall(), llvm::SizeOffsetType< T, C >::operator==(), llvm::ObjectSizeOffsetEvaluator::visitGEPOperator(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), and llvm::ObjectSizeOffsetEvaluator::visitSelectInst().
Size
template<typename T , class C > T llvm::SizeOffsetType< T, C >::Size
Definition at line 195 of file MemoryBuiltins.h.
Referenced by getBoundsCheckCond(), llvm::SizeOffsetType< T, C >::knownSize(), llvm::lowerObjectSizeCall(), llvm::SizeOffsetType< T, C >::operator==(), llvm::ObjectSizeOffsetEvaluator::visitGEPOperator(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), and llvm::ObjectSizeOffsetEvaluator::visitSelectInst().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/MemoryBuiltins.h