LLVM: llvm::AttributorLightCGSCCPass Struct Reference
llvm::AttributorLightCGSCCPass Struct Reference
A more lightweight version of the Attributor which only runs attribute inference but no simplifications.
#include "llvm/Transforms/IPO/Attributor.h"
Public Member Functions
PreservedAnalyses run (LazyCallGraph::SCC &C, CGSCCAnalysisManager &AM, LazyCallGraph &CG, CGSCCUpdateResult &UR)
Public Member Functions inherited from llvm::PassInfoMixin< AttributorLightCGSCCPass >
void printPipeline (raw_ostream &OS, function_ref< StringRef(StringRef)> MapClassName2PassName)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< AttributorLightCGSCCPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
A more lightweight version of the Attributor which only runs attribute inference but no simplifications.
Definition at line 3452 of file Attributor.h.
Member Function Documentation
run()
PreservedAnalyses AttributorLightCGSCCPass::run (LazyCallGraph::SCC & C, CGSCCAnalysisManager & AM, LazyCallGraph & CG, CGSCCUpdateResult & UR)
Definition at line 4097 of file Attributor.cpp.
References llvm::PreservedAnalyses::all(), Allocator, llvm::SetVector< T, Vector, Set, N >::back(), llvm::CallingConv::C, llvm::SetVector< T, Vector, Set, N >::empty(), FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::CallGraphUpdater::initialize(), llvm::SetVector< T, Vector, Set, N >::insert(), N, llvm::PreservedAnalyses::preserve(), llvm::PreservedAnalyses::preserveSet(), and runAttributorLightOnFunctions().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/Attributor.cpp