LLVM: llvm::orc::MachOBuilder< MachOTraits >::Segment Struct Reference
llvm::orc::MachOBuilder< MachOTraits >::Segment Struct Reference
#include "llvm/ExecutionEngine/Orc/MachOBuilder.h"
Public Member Functions
Segment (MachOBuilder &Builder, StringRef SegName)
Section & addSection (StringRef SecName, StringRef SegName)
size_t write (MutableArrayRef< char > Buf, size_t Offset, bool SwapStruct) override
Public Member Functions inherited from llvm::orc::MachOBuilderLoadCommand< MachOTraits::SegmentCmd >
MachOBuilderLoadCommand ()=default
MachOBuilderLoadCommand (ArgTs &&...Args)
Public Attributes
MachOBuilder & Builder
std::vector< std::unique_ptr< Section > > Sections
Detailed Description
template<typename MachOTraits>
struct llvm::orc::MachOBuilder< MachOTraits >::Segment
Definition at line 268 of file MachOBuilder.h.
Constructor & Destructor Documentation
Segment()
template<typename MachOTraits > llvm::orc::MachOBuilder< MachOTraits >::Segment::Segment (MachOBuilder & Builder, StringRef SegName) inline
Definition at line 272 of file MachOBuilder.h.
References assert(), llvm::StringRef::data(), llvm::StringRef::size(), llvm::MachO::VM_PROT_EXECUTE, llvm::MachO::VM_PROT_READ, and llvm::MachO::VM_PROT_WRITE.
Member Function Documentation
addSection()
template<typename MachOTraits > Section & llvm::orc::MachOBuilder< MachOTraits >::Segment::addSection (StringRef SecName, StringRef SegName) inline
Definition at line 281 of file MachOBuilder.h.
References llvm::orc::MachOBuilder< MachOTraits >::Segment::Builder, and llvm::orc::MachOBuilder< MachOTraits >::Segment::Sections.
write()
template<typename MachOTraits > size_t llvm::orc::MachOBuilder< MachOTraits >::Segment::write (MutableArrayRef< char > Buf, size_t Offset, bool SwapStruct) inline override
Definition at line 286 of file MachOBuilder.h.
References llvm::Offset, llvm::orc::MachOBuilder< MachOTraits >::Segment::Sections, and llvm::orc::writeMachOStruct().
Member Data Documentation
Builder
template<typename MachOTraits > MachOBuilder& llvm::orc::MachOBuilder< MachOTraits >::Segment::Builder
Definition at line 269 of file MachOBuilder.h.
Referenced by llvm::orc::MachOBuilder< MachOTraits >::Segment::addSection().
Sections
template<typename MachOTraits > std::vector<std::unique_ptr<Section> > llvm::orc::MachOBuilder< MachOTraits >::Segment::Sections
Definition at line 270 of file MachOBuilder.h.
Referenced by llvm::orc::MachOBuilder< MachOTraits >::Segment::addSection(), and llvm::orc::MachOBuilder< MachOTraits >::Segment::write().
The documentation for this struct was generated from the following file:
include/llvm/ExecutionEngine/Orc/MachOBuilder.h