LLVM: llvm::InstrInfoQuery Struct Reference
llvm::InstrInfoQuery Struct Reference
InstrInfoQuery provides an interface to query additional information for instructions like metadata or keywords like nsw, which provides conservative results if the users specified it is safe to use.
#include "llvm/Analysis/SimplifyQuery.h"
Public Member Functions
InstrInfoQuery (bool UMD)
InstrInfoQuery ()=default
MDNode * getMetadata (const Instruction *I, unsigned KindID) const
template<class InstT >
bool hasNoUnsignedWrap (const InstT *Op) const
template<class InstT >
bool hasNoSignedWrap (const InstT *Op) const
bool isExact (const BinaryOperator *Op) const
template<class InstT >
bool hasNoSignedZeros (const InstT *Op) const
Public Attributes
bool UseInstrInfo = true
Detailed Description
InstrInfoQuery provides an interface to query additional information for instructions like metadata or keywords like nsw, which provides conservative results if the users specified it is safe to use.
Definition at line 24 of file SimplifyQuery.h.
Constructor & Destructor Documentation
InstrInfoQuery() [1/2]
llvm::InstrInfoQuery::InstrInfoQuery (bool UMD) inline
Definition at line 25 of file SimplifyQuery.h.
InstrInfoQuery() [2/2]
llvm::InstrInfoQuery::InstrInfoQuery () default
Member Function Documentation
getMetadata()
MDNode * llvm::InstrInfoQuery::getMetadata (const Instruction * I, unsigned KindID) const inline
Definition at line 29 of file SimplifyQuery.h.
References I, and UseInstrInfo.
Referenced by llvm::computeConstantRange(), computeKnownBitsFromOperator(), isKnownNonZero(), isKnownNonZeroFromOperator(), and simplifyICmpInst().
hasNoSignedWrap()
template<class InstT > bool llvm::InstrInfoQuery::hasNoSignedWrap (const InstT * Op) const inline
Definition at line 41 of file SimplifyQuery.h.
References UseInstrInfo.
Referenced by computeKnownBitsFromOperator(), getRangeForSelectPattern(), isKnownNonZeroFromOperator(), isKnownToBeAPowerOfTwo(), isPowerOfTwoRecurrence(), setLimitsForBinOp(), simplifyAndOfICmpsWithAdd(), simplifyDivRem(), simplifyICmpWithBinOp(), simplifyInstructionWithOperands(), and simplifyOrOfICmpsWithAdd().
hasNoSignedZeros()
template<class InstT > bool llvm::InstrInfoQuery::hasNoSignedZeros (const InstT * Op) const inline
Definition at line 53 of file SimplifyQuery.h.
References UseInstrInfo.
Referenced by computeKnownFPClass().
hasNoUnsignedWrap()
template<class InstT > bool llvm::InstrInfoQuery::hasNoUnsignedWrap (const InstT * Op) const inline
Definition at line 35 of file SimplifyQuery.h.
References UseInstrInfo.
Referenced by computeKnownBitsFromOperator(), isKnownNonZeroFromOperator(), isKnownToBeAPowerOfTwo(), isPowerOfTwoRecurrence(), setLimitsForBinOp(), simplifyAndOfICmpsWithAdd(), simplifyDivRem(), simplifyICmpWithBinOp(), simplifyInstructionWithOperands(), and simplifyOrOfICmpsWithAdd().
isExact()
bool llvm::InstrInfoQuery::isExact (const BinaryOperator * Op) const inline
Definition at line 47 of file SimplifyQuery.h.
References UseInstrInfo.
Referenced by computeKnownBitsFromOperator(), isKnownToBeAPowerOfTwo(), isPowerOfTwoRecurrence(), setLimitsForBinOp(), simplifyICmpWithBinOp(), and simplifyInstructionWithOperands().
Member Data Documentation
UseInstrInfo
bool llvm::InstrInfoQuery::UseInstrInfo = true
Definition at line 27 of file SimplifyQuery.h.
Referenced by llvm::computeConstantRangeIncludingKnownBits(), computeKnownFPClass(), getMetadata(), hasNoSignedWrap(), hasNoSignedZeros(), hasNoUnsignedWrap(), isExact(), isKnownNonZeroFromOperator(), simplifyAndInst(), simplifyAShrInst(), simplifyFCmpInst(), simplifyICmpInst(), simplifyICmpWithConstant(), simplifyICmpWithZero(), simplifyLShrInst(), simplifyMulInst(), simplifyRem(), simplifyShlInst(), and trySimplifyICmpWithAdds().
The documentation for this struct was generated from the following file:
include/llvm/Analysis/SimplifyQuery.h