LLVM: llvm::DenormalFPMathState::DenormalState Struct Reference
llvm::DenormalFPMathState::DenormalState Struct Reference
#include "llvm/Transforms/IPO/Attributor.h"
Public Member Functions
bool operator== (const DenormalState Other) const
bool operator!= (const DenormalState Other) const
bool isValid () const
DenormalState unionWith (DenormalState Caller) const
Static Public Member Functions
static DenormalMode::DenormalModeKind unionDenormalKind (DenormalMode::DenormalModeKind Callee, DenormalMode::DenormalModeKind Caller)
static DenormalMode unionAssumed (DenormalMode Callee, DenormalMode Caller)
Public Attributes
DenormalMode Mode = DenormalMode::getInvalid()
DenormalMode ModeF32 = DenormalMode::getInvalid()
Detailed Description
Definition at line 5134 of file Attributor.h.
Member Function Documentation
isValid()
bool llvm::DenormalFPMathState::DenormalState::isValid () const inline
Definition at line 5146 of file Attributor.h.
References llvm::DenormalMode::isValid(), Mode, and ModeF32.
Referenced by llvm::DenormalFPMathState::isValidState().
operator!=()
bool llvm::DenormalFPMathState::DenormalState::operator!= (const DenormalState Other) const inline
Definition at line 5142 of file Attributor.h.
References Mode, ModeF32, and llvm::Other.
operator==()
bool llvm::DenormalFPMathState::DenormalState::operator== (const DenormalState Other) const inline
Definition at line 5138 of file Attributor.h.
References Mode, ModeF32, and llvm::Other.
unionAssumed()
static DenormalMode llvm::DenormalFPMathState::DenormalState::unionAssumed (DenormalMode Callee, DenormalMode Caller) inline static
Definition at line 5162 of file Attributor.h.
References unionDenormalKind().
Referenced by unionWith().
unionDenormalKind()
static DenormalMode::DenormalModeKind llvm::DenormalFPMathState::DenormalState::unionDenormalKind (DenormalMode::DenormalModeKind Callee, DenormalMode::DenormalModeKind Caller) inline static
Definition at line 5151 of file Attributor.h.
References llvm::DenormalMode::Dynamic, and llvm::DenormalMode::Invalid.
Referenced by unionAssumed().
unionWith()
DenormalState llvm::DenormalFPMathState::DenormalState::unionWith (DenormalState Caller) const inline
Definition at line 5167 of file Attributor.h.
References unionAssumed().
Referenced by llvm::DenormalFPMathState::operator^=().
Member Data Documentation
Mode
DenormalMode llvm::DenormalFPMathState::DenormalState::Mode = DenormalMode::getInvalid()
Definition at line 5135 of file Attributor.h.
Referenced by llvm::DenormalFPMathState::isModeFixed(), isValid(), operator!=(), and operator==().
ModeF32
DenormalMode llvm::DenormalFPMathState::DenormalState::ModeF32 = DenormalMode::getInvalid()
Definition at line 5136 of file Attributor.h.
Referenced by llvm::DenormalFPMathState::isModeFixed(), isValid(), operator!=(), and operator==().
The documentation for this struct was generated from the following file:
include/llvm/Transforms/IPO/Attributor.h