LLVM: lib/DWARFLinker/Parallel/SyntheticTypeNameBuilder.cpp File Reference
SyntheticTypeNameBuilder.cpp File Reference
#include "SyntheticTypeNameBuilder.h"
#include "DWARFLinkerCompileUnit.h"
#include "llvm/DebugInfo/DWARF/DWARFAcceleratorTable.h"
#include "llvm/DebugInfo/DWARF/DWARFDebugInfoEntry.h"
#include "llvm/Support/ScopedPrinter.h"
Functions
static std::optional< UnitEntryPairTy > getTypeDeduplicationCandidate (UnitEntryPairTy UnitEntryPair)
Variables
static dwarf::Attribute TypeAttr [] = {dwarf::DW_AT_type}
Function Documentation
getTypeDeduplicationCandidate()
static std::optional< UnitEntryPairTy > getTypeDeduplicationCandidate (UnitEntryPairTy UnitEntryPair) static
Definition at line 169 of file SyntheticTypeNameBuilder.cpp.
References llvm::dwarf_linker::parallel::UnitEntryPairTy::CU, llvm::dwarf_linker::parallel::UnitEntryPairTy::DieEntry, llvm::dwarf_linker::parallel::CompileUnit::find(), llvm::dwarf_linker::parallel::UnitEntryPairTy::getNamespaceOrigin(), llvm::DWARFDebugInfoEntry::getTag(), and llvm_unreachable.
Referenced by llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addDIETypeName(), and llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addParentName().
Variable Documentation
TypeAttr
dwarf::Attribute TypeAttr[] = {dwarf::DW_AT_type} static
Definition at line 61 of file SyntheticTypeNameBuilder.cpp.
Referenced by llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addParamNames(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addSignature(), llvm::dwarf_linker::parallel::SyntheticTypeNameBuilder::addTemplateParamNames(), and llvm::DWARFTypePrinter::appendTemplateParameters().