LLVM: lib/Target/SystemZ/MCTargetDesc/SystemZMCAsmBackend.cpp File Reference
SystemZMCAsmBackend.cpp File Reference
#include "MCTargetDesc/SystemZMCFixups.h"
#include "MCTargetDesc/SystemZMCTargetDesc.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/BinaryFormat/ELFRelocs/SystemZ.def"
Macros
#define ELF_RELOC(X, Y) .Case(#X, Y)
Functions
static uint64_t extractBitsForFixup (MCFixupKind Kind, uint64_t Value, const MCFixup &Fixup, MCContext &Ctx)
Macro Definition Documentation
ELF_RELOC
#define ELF_RELOC (X, Y) .Case(#X, Y)
Function Documentation
extractBitsForFixup()
static uint64_t extractBitsForFixup (MCFixupKind Kind, uint64_t Value, const MCFixup & Fixup, MCContext & Ctx) static
Definition at line 26 of file SystemZMCAsmBackend.cpp.
References llvm::FirstTargetFixupKind, Fixup, llvm::SystemZ::FK_390_PC12DBL, llvm::SystemZ::FK_390_PC16DBL, llvm::SystemZ::FK_390_PC24DBL, llvm::SystemZ::FK_390_PC32DBL, llvm::SystemZ::FK_390_S16Imm, llvm::SystemZ::FK_390_S20Imm, llvm::SystemZ::FK_390_S32Imm, llvm::SystemZ::FK_390_S8Imm, llvm::SystemZ::FK_390_TLS_CALL, llvm::SystemZ::FK_390_U12Imm, llvm::SystemZ::FK_390_U16Imm, llvm::SystemZ::FK_390_U1Imm, llvm::SystemZ::FK_390_U2Imm, llvm::SystemZ::FK_390_U32Imm, llvm::SystemZ::FK_390_U3Imm, llvm::SystemZ::FK_390_U48Imm, llvm::SystemZ::FK_390_U4Imm, llvm::SystemZ::FK_390_U8Imm, llvm_unreachable, llvm::maxIntN(), llvm::maxUIntN(), llvm::minIntN(), and llvm::MCContext::reportError().