LLVM: lib/Target/SystemZ/SystemZAsmPrinter.cpp File Reference
SystemZAsmPrinter.cpp File Reference
#include "SystemZAsmPrinter.h"
#include "MCTargetDesc/SystemZInstPrinter.h"
#include "MCTargetDesc/SystemZMCExpr.h"
#include "SystemZConstantPoolValue.h"
#include "SystemZMCInstLower.h"
#include "TargetInfo/SystemZTargetInfo.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/IR/Mangler.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/Chrono.h"
#include "llvm/Support/ConvertEBCDIC.h"
#include "llvm/Support/FormatProviders.h"
#include "llvm/Support/FormatVariadic.h"
Macros
#define LOWER_LOW(NAME) case SystemZ::NAME##64: LoweredMI = lowerRILow(MI, SystemZ::NAME); break
#define LOWER_HIGH(NAME) case SystemZ::NAME##64: LoweredMI = lowerRIHigh(MI, SystemZ::NAME); break
#define EMIT_COMMENT(Str)
Functions
static MCInst lowerRILow (const MachineInstr *MI, unsigned Opcode)
static MCInst lowerRIHigh (const MachineInstr *MI, unsigned Opcode)
static MCInst lowerRIEfLow (const MachineInstr *MI, unsigned Opcode)
static const MCSymbolRefExpr * getTLSGetOffset (MCContext &Context)
static const MCSymbolRefExpr * getGlobalOffsetTable (MCContext &Context)
static void lowerAlignmentHint (const MachineInstr *MI, MCInst &LoweredMI, unsigned Opcode)
static MCInst lowerSubvectorLoad (const MachineInstr *MI, unsigned Opcode)
static MCInst lowerSubvectorStore (const MachineInstr *MI, unsigned Opcode)
static unsigned EmitNop (MCContext &OutContext, MCStreamer &OutStreamer, unsigned NumBytes, const MCSubtargetInfo &STI)
static MCSymbolRefExpr::VariantKind getModifierVariantKind (SystemZCP::SystemZCPModifier Modifier)
static void printFormattedRegName (const MCAsmInfo *MAI, unsigned RegNo, raw_ostream &OS)
static void printOperand (const MCOperand &MCOp, const MCAsmInfo *MAI, raw_ostream &OS)
static void printAddress (const MCAsmInfo *MAI, unsigned Base, const MCOperand &DispMO, unsigned Index, raw_ostream &OS)
static std::string getProductID (Module &M)
static uint32_t getProductVersion (Module &M)
static uint32_t getProductRelease (Module &M)
static uint32_t getProductPatch (Module &M)
static time_t getTranslationTime (Module &M)
static void emitPPA1Flags (std::unique_ptr< MCStreamer > &OutStreamer, bool VarArg, bool StackProtector, bool FPRMask, bool VRMask, bool EHBlock, bool HasName)
static void emitPPA1Name (std::unique_ptr< MCStreamer > &OutStreamer, StringRef OutName)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSystemZAsmPrinter ()
Macro Definition Documentation
EMIT_COMMENT
#define EMIT_COMMENT (Str)
Value:
  OutStreamer->AddComment(Twine("Offset ")                                     \
                              .concat(utostr(Offset))                          \
                              .concat(" " Str " ")                             \
                              .concat(Sym->getName()));
LOWER_HIGH
#define LOWER_HIGH (NAME) case SystemZ::NAME##64: LoweredMI = lowerRIHigh(MI, SystemZ::NAME); break
LOWER_LOW
#define LOWER_LOW (NAME) case SystemZ::NAME##64: LoweredMI = lowerRILow(MI, SystemZ::NAME); break
Function Documentation
EmitNop()
static unsigned EmitNop (MCContext & OutContext, MCStreamer & OutStreamer, unsigned NumBytes, const MCSubtargetInfo & STI) static
Definition at line 697 of file SystemZAsmPrinter.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCContext::createTempSymbol(), llvm::MCStreamer::emitInstruction(), llvm::MCStreamer::emitLabel(), and llvm_unreachable.
emitPPA1Flags()
static void emitPPA1Flags (std::unique_ptr< MCStreamer > & OutStreamer, bool VarArg, bool StackProtector, bool FPRMask, bool VRMask, bool EHBlock, bool HasName) static
Definition at line 1116 of file SystemZAsmPrinter.cpp.
References llvm::LLVM_MARK_AS_BITMASK_ENUM.
emitPPA1Name()
static void emitPPA1Name (std::unique_ptr< MCStreamer > & OutStreamer, StringRef OutName) static
Definition at line 1204 of file SystemZAsmPrinter.cpp.
References llvm::ConverterEBCDIC::convertToEBCDIC(), llvm::XCOFF::NameSize, llvm::StringRef::size(), llvm::SmallString< InternalLen >::str(), and llvm::StringRef::substr().
getGlobalOffsetTable()
static const MCSymbolRefExpr * getGlobalOffsetTable (MCContext & Context) static
Definition at line 84 of file SystemZAsmPrinter.cpp.
References Context, llvm::MCSymbolRefExpr::create(), Name, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
getModifierVariantKind()
static MCSymbolRefExpr::VariantKind getModifierVariantKind (SystemZCP::SystemZCPModifier Modifier) static
Definition at line 858 of file SystemZAsmPrinter.cpp.
References llvm::SystemZCP::DTPOFF, llvm_unreachable, llvm::SystemZCP::NTPOFF, llvm::SystemZCP::TLSGD, llvm::SystemZCP::TLSLDM, llvm::MCSymbolRefExpr::VK_DTPOFF, llvm::MCSymbolRefExpr::VK_NTPOFF, llvm::MCSymbolRefExpr::VK_TLSGD, and llvm::MCSymbolRefExpr::VK_TLSLDM.
getProductID()
static std::string getProductID (Module & M) static
Definition at line 1033 of file SystemZAsmPrinter.cpp.
getProductPatch()
static uint32_t getProductPatch (Module & M) static
Definition at line 1056 of file SystemZAsmPrinter.cpp.
getProductRelease()
static uint32_t getProductRelease (Module & M) static
Definition at line 1049 of file SystemZAsmPrinter.cpp.
getProductVersion()
static uint32_t getProductVersion (Module & M) static
Definition at line 1042 of file SystemZAsmPrinter.cpp.
getTLSGetOffset()
static const MCSymbolRefExpr * getTLSGetOffset (MCContext & Context) static
Definition at line 77 of file SystemZAsmPrinter.cpp.
References Context, llvm::MCSymbolRefExpr::create(), Name, and llvm::MCSymbolRefExpr::VK_PLT.
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
getTranslationTime()
static time_t getTranslationTime (Module & M) static
Definition at line 1063 of file SystemZAsmPrinter.cpp.
LLVMInitializeSystemZAsmPrinter()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeSystemZAsmPrinter ()
Definition at line 1584 of file SystemZAsmPrinter.cpp.
References llvm::getTheSystemZTarget(), and X.
lowerAlignmentHint()
static void lowerAlignmentHint (const MachineInstr * MI, MCInst & LoweredMI, unsigned Opcode) static
Definition at line 95 of file SystemZAsmPrinter.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::createImm(), MI, and llvm::MCInst::setOpcode().
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
lowerRIEfLow()
static MCInst lowerRIEfLow (const MachineInstr * MI, unsigned Opcode) static
Definition at line 67 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::SystemZMC::getRegAsGR64(), and MI.
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
lowerRIHigh()
static MCInst lowerRIHigh (const MachineInstr * MI, unsigned Opcode) static
Definition at line 53 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::SystemZMC::getRegAsGRH32(), and MI.
lowerRILow()
static MCInst lowerRILow (const MachineInstr * MI, unsigned Opcode) static
Definition at line 39 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::SystemZMC::getRegAsGR32(), and MI.
lowerSubvectorLoad()
static MCInst lowerSubvectorLoad (const MachineInstr * MI, unsigned Opcode) static
Definition at line 120 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::SystemZMC::getRegAsVR128(), and MI.
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
lowerSubvectorStore()
static MCInst lowerSubvectorStore (const MachineInstr * MI, unsigned Opcode) static
Definition at line 130 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::SystemZMC::getRegAsVR128(), and MI.
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
printAddress()
static void printAddress (const MCAsmInfo * MAI, unsigned Base, const MCOperand & DispMO, unsigned Index, raw_ostream & OS) static
Definition at line 907 of file SystemZAsmPrinter.cpp.
References llvm::sampleprof::Base, OS, printFormattedRegName(), and printOperand().
Referenced by llvm::SystemZAsmPrinter::PrintAsmMemoryOperand().
printFormattedRegName()
static void printFormattedRegName (const MCAsmInfo * MAI, unsigned RegNo, raw_ostream & OS) static
Definition at line 881 of file SystemZAsmPrinter.cpp.
References llvm::AD_HLASM, assert(), llvm::MCAsmInfo::getAssemblerDialect(), llvm::SystemZInstPrinter::getRegisterName(), OS, and RegName.
Referenced by printAddress(), and printOperand().
printOperand()
static void printOperand (const MCOperand & MCOp, const MCAsmInfo * MAI, raw_ostream & OS) static
Definition at line 892 of file SystemZAsmPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm_unreachable, OS, llvm::MCExpr::print(), and printFormattedRegName().