LLVM: lib/Target/WebAssembly/MCTargetDesc/WebAssemblyMCTargetDesc.cpp File Reference
WebAssemblyMCTargetDesc.cpp File Reference
This file provides WebAssembly-specific target descriptions.
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "MCTargetDesc/WebAssemblyInstPrinter.h"
#include "MCTargetDesc/WebAssemblyMCAsmInfo.h"
#include "MCTargetDesc/WebAssemblyTargetStreamer.h"
#include "TargetInfo/WebAssemblyTargetInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/TargetRegistry.h"
#include "llvm/Support/ErrorHandling.h"
#include "WebAssemblyGenInstrInfo.inc"
#include "WebAssemblyGenSubtargetInfo.inc"
#include "WebAssemblyGenRegisterInfo.inc"
Macros
#define DEBUG_TYPE "wasm-mc-target-desc"
#define GET_INSTRINFO_MC_DESC
#define ENABLE_INSTR_PREDICATE_VERIFIER
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCAsmInfo * createMCAsmInfo (const MCRegisterInfo &, const Triple &TT, const MCTargetOptions &Options)
static MCInstrInfo * createMCInstrInfo ()
static MCRegisterInfo * createMCRegisterInfo (const Triple &)
static MCInstPrinter * createMCInstPrinter (const Triple &, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
static MCCodeEmitter * createCodeEmitter (const MCInstrInfo &MCII, MCContext &Ctx)
static MCAsmBackend * createAsmBackend (const Target &, const MCSubtargetInfo &STI, const MCRegisterInfo &, const MCTargetOptions &)
static MCSubtargetInfo * createMCSubtargetInfo (const Triple &TT, StringRef CPU, StringRef FS)
static MCTargetStreamer * createObjectTargetStreamer (MCStreamer &S, const MCSubtargetInfo &STI)
static MCTargetStreamer * createAsmTargetStreamer (MCStreamer &S, formatted_raw_ostream &OS, MCInstPrinter *, bool)
static MCTargetStreamer * createNullTargetStreamer (MCStreamer &S)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyTargetMC ()
Detailed Description
This file provides WebAssembly-specific target descriptions.
Definition in file WebAssemblyMCTargetDesc.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm-mc-target-desc"
Definition at line 26 of file WebAssemblyMCTargetDesc.cpp.
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 29 of file WebAssemblyMCTargetDesc.cpp.
GET_INSTRINFO_MC_DESC
#define GET_INSTRINFO_MC_DESC
Definition at line 28 of file WebAssemblyMCTargetDesc.cpp.
GET_REGINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Definition at line 35 of file WebAssemblyMCTargetDesc.cpp.
GET_SUBTARGETINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 32 of file WebAssemblyMCTargetDesc.cpp.
Function Documentation
createAsmBackend()
static MCAsmBackend * createAsmBackend (const Target & , const MCSubtargetInfo & STI, const MCRegisterInfo & , const MCTargetOptions &) static
Definition at line 90 of file WebAssemblyMCTargetDesc.cpp.
References llvm::createWebAssemblyAsmBackend(), and llvm::MCSubtargetInfo::getTargetTriple().
Referenced by LLVMInitializeWebAssemblyTargetMC().
createAsmTargetStreamer()
static MCTargetStreamer * createAsmTargetStreamer (MCStreamer & S, formatted_raw_ostream & OS, MCInstPrinter * , bool) static
Definition at line 107 of file WebAssemblyMCTargetDesc.cpp.
References OS.
Referenced by LLVMInitializeWebAssemblyTargetMC().
createCodeEmitter()
static MCCodeEmitter * createCodeEmitter (const MCInstrInfo & MCII, MCContext & Ctx) static
Definition at line 85 of file WebAssemblyMCTargetDesc.cpp.
References llvm::createWebAssemblyMCCodeEmitter().
Referenced by LLVMInitializeWebAssemblyTargetMC().
createMCAsmInfo()
static MCAsmInfo * createMCAsmInfo (const MCRegisterInfo & , const Triple & TT, const MCTargetOptions & Options) static
Definition at line 58 of file WebAssemblyMCTargetDesc.cpp.
References Options.
Referenced by LLVMInitializeWebAssemblyTargetMC().
createMCInstPrinter()
static MCInstPrinter * createMCInstPrinter (const Triple & , unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) static
Definition at line 76 of file WebAssemblyMCTargetDesc.cpp.
References assert(), and MRI.
Referenced by LLVMInitializeWebAssemblyTargetMC().
createMCInstrInfo()
static MCInstrInfo * createMCInstrInfo () static
Definition at line 64 of file WebAssemblyMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeWebAssemblyTargetMC().
createMCRegisterInfo()
static MCRegisterInfo * createMCRegisterInfo (const Triple &) static
Definition at line 70 of file WebAssemblyMCTargetDesc.cpp.
References X.
Referenced by LLVMInitializeWebAssemblyTargetMC().
createMCSubtargetInfo()
static MCSubtargetInfo * createMCSubtargetInfo (const Triple & TT, StringRef CPU, StringRef FS) static
Definition at line 97 of file WebAssemblyMCTargetDesc.cpp.
Referenced by LLVMInitializeWebAssemblyTargetMC().
createNullTargetStreamer()
static MCTargetStreamer * createNullTargetStreamer (MCStreamer & S) static
Definition at line 114 of file WebAssemblyMCTargetDesc.cpp.
Referenced by LLVMInitializeWebAssemblyTargetMC().
createObjectTargetStreamer()
static MCTargetStreamer * createObjectTargetStreamer (MCStreamer & S, const MCSubtargetInfo & STI) static
Definition at line 103 of file WebAssemblyMCTargetDesc.cpp.
Referenced by LLVMInitializeWebAssemblyTargetMC().
LLVMInitializeWebAssemblyTargetMC()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyTargetMC ()
Definition at line 119 of file WebAssemblyMCTargetDesc.cpp.
References createAsmBackend(), createAsmTargetStreamer(), createCodeEmitter(), createMCAsmInfo(), createMCInstPrinter(), createMCInstrInfo(), createMCRegisterInfo(), createMCSubtargetInfo(), createNullTargetStreamer(), createObjectTargetStreamer(), llvm::getTheWebAssemblyTarget32(), llvm::getTheWebAssemblyTarget64(), llvm::TargetRegistry::RegisterAsmTargetStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::TargetRegistry::RegisterNullTargetStreamer(), llvm::TargetRegistry::RegisterObjectTargetStreamer(), and X.