LLVM: lib/Target/WebAssembly/WebAssemblyDebugValueManager.cpp File Reference
WebAssemblyDebugValueManager.cpp File Reference
This file implements the manager for MachineInstr DebugValues.
#include "WebAssemblyDebugValueManager.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "WebAssembly.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/Function.h"
Functions
static bool isSameScalarConst (const MachineInstr *A, const MachineInstr *B)
static bool hasSameDebugLoc (const MachineBasicBlock *MBB, DebugLoc DL)
Detailed Description
This file implements the manager for MachineInstr DebugValues.
Definition in file WebAssemblyDebugValueManager.cpp.
Function Documentation
hasSameDebugLoc()
static bool hasSameDebugLoc (const MachineBasicBlock * MBB, DebugLoc DL) static
Definition at line 236 of file WebAssemblyDebugValueManager.cpp.
References DL, MBB, and MI.
Referenced by llvm::WebAssemblyDebugValueManager::cloneSink(), and llvm::WebAssemblyDebugValueManager::sink().
isSameScalarConst()
static bool isSameScalarConst (const MachineInstr * A, const MachineInstr * B) static
Definition at line 49 of file WebAssemblyDebugValueManager.cpp.
References A, B, llvm::MachineOperand::getFPImm(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::isFPImm(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), and llvm::WebAssembly::isScalarConst().