LLVM: lib/Target/AMDGPU/AMDGPUAttributor.cpp File Reference
AMDGPUAttributor.cpp File Reference
#include "AMDGPU.h"
#include "GCNSubtarget.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/IR/IntrinsicsR600.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Transforms/IPO/Attributor.h"
Classes
class AMDGPUInformationCache
struct AAAMDAttributes
struct AAAMDWorkGroupSize
struct AAAMDWorkGroupSizeFunction
struct AAAMDAttributesFunction
class AMDGPUAttributor
Macros
#define DEBUG_TYPE "amdgpu-attributor"
Functions
static StringRef intrinsicToAttrName (Intrinsic::ID ID, bool &NonKernelOnly, bool &IsQueuePtr)
static bool castRequiresQueuePtr (unsigned SrcAS)
static bool isDSAddress (const Constant *C)
Variables
static constexpr StringLiteral ImplicitAttrNames []
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-attributor"
Definition at line 21 of file AMDGPUAttributor.cpp.
Function Documentation
castRequiresQueuePtr()
static bool castRequiresQueuePtr (unsigned SrcAS) static
Definition at line 80 of file AMDGPUAttributor.cpp.
References llvm::AMDGPUAS::LOCAL_ADDRESS, and llvm::AMDGPUAS::PRIVATE_ADDRESS.
Referenced by AAAMDAttributesFunction::updateImpl().
intrinsicToAttrName()
static StringRef intrinsicToAttrName (Intrinsic::ID ID, bool & NonKernelOnly, bool & IsQueuePtr) static
Definition at line 38 of file AMDGPUAttributor.cpp.
Referenced by AAAMDAttributesFunction::updateImpl().
isDSAddress()
static bool isDSAddress (const Constant * C) static
Definition at line 84 of file AMDGPUAttributor.cpp.
References C, llvm::GlobalValue::getAddressSpace(), llvm::AMDGPUAS::LOCAL_ADDRESS, and llvm::AMDGPUAS::REGION_ADDRESS.
Variable Documentation
ImplicitAttrNames
constexpr StringLiteral ImplicitAttrNames[] static constexpr
Initial value:
= {
    "amdgpu-work-item-id-x",  "amdgpu-work-item-id-y",
    "amdgpu-work-item-id-z",  "amdgpu-work-group-id-x",
    "amdgpu-work-group-id-y", "amdgpu-work-group-id-z",
    "amdgpu-dispatch-ptr",    "amdgpu-dispatch-id",
    "amdgpu-queue-ptr",       "amdgpu-implicitarg-ptr"}
Definition at line 25 of file AMDGPUAttributor.cpp.
Referenced by copyFeaturesToFunction(), AAAMDAttributesFunction::initialize(), and AAAMDAttributesFunction::updateImpl().