LLVM: lib/Target/AMDGPU/AMDGPUSubtarget.cpp File Reference
AMDGPUSubtarget.cpp File Reference
Implements the AMDGPU specific subclass of TargetSubtarget.
#include "AMDGPUSubtarget.h"
#include "AMDGPU.h"
#include "AMDGPUCallLowering.h"
#include "AMDGPUInstructionSelector.h"
#include "AMDGPULegalizerInfo.h"
#include "AMDGPURegisterBankInfo.h"
#include "AMDGPUTargetMachine.h"
#include "SIMachineFunctionInfo.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/CodeGen/GlobalISel/InlineAsmLowering.h"
#include "llvm/CodeGen/MachineScheduler.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/IR/IntrinsicsAMDGPU.h"
#include "llvm/IR/IntrinsicsR600.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include <algorithm>
#include "AMDGPUGenSubtargetInfo.inc"
#include "R600GenSubtargetInfo.inc"
Macros
#define DEBUG_TYPE "amdgpu-subtarget"
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
#define AMDGPUSubtarget GCNSubtarget
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
Functions
static unsigned getReqdWorkGroupSize (const Function &Kernel, unsigned Dim)
static unsigned getMaxNumPreloadedSGPRs ()
Variables
static cl::opt< bool > DisablePowerSched ("amdgpu-disable-power-sched", cl::desc("Disable scheduling to minimize mAI power bursts"), cl::init(false))
static cl::opt< bool > EnableVGPRIndexMode ("amdgpu-vgpr-index-mode", cl::desc("Use GPR indexing mode instead of movrel for vector indexing"), cl::init(false))
static cl::opt< bool > EnableFlatScratch ("amdgpu-enable-flat-scratch", cl::desc("Use flat scratch instructions"), cl::init(false))
static cl::opt< bool > UseAA ("amdgpu-use-aa-in-codegen", cl::desc("Enable the use of AA during codegen."), cl::init(true))
Detailed Description
Implements the AMDGPU specific subclass of TargetSubtarget.
Definition in file AMDGPUSubtarget.cpp.
Macro Definition Documentation
AMDGPUSubtarget
#define AMDGPUSubtarget GCNSubtarget
Definition at line 39 of file AMDGPUSubtarget.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-subtarget"
Definition at line 35 of file AMDGPUSubtarget.cpp.
GET_SUBTARGETINFO_CTOR [1/2]
#define GET_SUBTARGETINFO_CTOR
Definition at line 38 of file AMDGPUSubtarget.cpp.
GET_SUBTARGETINFO_CTOR [2/2]
#define GET_SUBTARGETINFO_CTOR
Definition at line 38 of file AMDGPUSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC [1/2]
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 37 of file AMDGPUSubtarget.cpp.
GET_SUBTARGETINFO_TARGET_DESC [2/2]
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 37 of file AMDGPUSubtarget.cpp.
Function Documentation
getMaxNumPreloadedSGPRs()
static unsigned getMaxNumPreloadedSGPRs () static
Definition at line 909 of file AMDGPUSubtarget.cpp.
Referenced by llvm::GCNSubtarget::getMaxNumSGPRs().
getReqdWorkGroupSize()
static unsigned getReqdWorkGroupSize (const Function & Kernel, unsigned Dim) static
Definition at line 591 of file AMDGPUSubtarget.cpp.
References llvm::GlobalObject::getMetadata().
Referenced by llvm::AMDGPUSubtarget::getMaxWorkitemID(), and llvm::AMDGPUSubtarget::makeLIDRangeMetadata().
Variable Documentation
DisablePowerSched
cl::opt< bool > DisablePowerSched("amdgpu-disable-power-sched", cl::desc("Disable scheduling to minimize mAI power bursts"), cl::init(false)) ("amdgpu-disable-power-sched" , cl::desc("Disable scheduling to minimize mAI power bursts") , cl::init(false)) static
EnableFlatScratch
cl::opt< bool > EnableFlatScratch("amdgpu-enable-flat-scratch", cl::desc("Use flat scratch instructions"), cl::init(false)) ("amdgpu-enable-flat-scratch" , cl::desc("Use flat scratch instructions") , cl::init(false)) static
Referenced by llvm::GCNSubtarget::enableFlatScratch().
EnableVGPRIndexMode
cl::opt< bool > EnableVGPRIndexMode("amdgpu-vgpr-index-mode", cl::desc("Use GPR indexing mode instead of movrel for vector indexing"), cl::init(false)) ("amdgpu-vgpr-index-mode" , cl::desc("Use GPR indexing mode instead of movrel for vector indexing") , cl::init(false)) static
Referenced by llvm::GCNSubtarget::useVGPRIndexMode().
UseAA
cl::opt< bool > UseAA("amdgpu-use-aa-in-codegen", cl::desc("Enable the use of AA during codegen."), cl::init(true)) ("amdgpu-use-aa-in-codegen" , cl::desc("Enable the use of AA during codegen.") , cl::init(true)) static