LLVM: lib/Object/Archive.cpp File Reference
Archive.cpp File Reference
#include "llvm/Object/Archive.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Object/Binary.h"
#include "llvm/Object/Error.h"
#include "llvm/Support/Chrono.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <memory>
#include <string>
#include <system_error>
Functions
static Error malformedError (Twine Msg)
Variables
const char Magic [] = "!<arch>\n"
const char ThinMagic [] = "!<thin>\n"
Function Documentation
malformedError()
static Error malformedError (Twine Msg) static
Definition at line 46 of file Archive.cpp.
References llvm::object::parse_failed, and llvm::Twine::str().
Referenced by llvm::object::ArchiveMemberHeader::ArchiveMemberHeader(), llvm::object::MachOObjectFile::checkSymbolTable(), llvm::object::Archive::Child::Child(), llvm::object::ArchiveMemberHeader::getAccessMode(), llvm::object::ArchiveMemberHeader::getGID(), llvm::object::ArchiveMemberHeader::getLastModified(), llvm::object::ArchiveMemberHeader::getName(), llvm::object::Archive::Child::getNext(), llvm::object::ArchiveMemberHeader::getRawName(), llvm::object::MachOObjectFile::getSection(), llvm::object::ArchiveMemberHeader::getSize(), llvm::object::MachOObjectFile::getSymbolName(), llvm::object::MachOObjectFile::getSymbolSection(), llvm::object::ArchiveMemberHeader::getUID(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), llvm::object::ExportEntry::moveNext(), llvm::object::MachORebaseEntry::moveNext(), and llvm::object::MachOBindEntry::moveNext().
Variable Documentation
Magic
const char Magic[] = "!<arch>\n"
Definition at line 41 of file Archive.cpp.
Referenced by analyzeHeader(), appendFile(), llvm::object::Archive::Archive(), llvm::TargetLowering::BuildUDIV(), llvm::object::Archive::child_begin(), llvm::jitlink::createLinkGraphFromMachOObject(), llvm::jitlink::createLinkGraphFromObject(), llvm::object::ObjectFile::createMachOObjectFile(), llvm::CodeViewYAML::fromDebugS(), llvm::CodeViewYAML::fromDebugT(), getMemsetValue(), getMemsetValue(), llvm::sampleprof::SampleProfileReaderRawBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderExtBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderCompactBinary::hasFormat(), llvm::sampleprof::SampleProfileReaderGCC::hasFormat(), llvm::RawInstrProfReader< IntPtrT >::hasFormat(), llvm::IndexedInstrProfReader::hasFormat(), llvm::identify_magic(), initializeOptionalHeader(), llvm::IndexedInstrProfReader::readHeader(), llvm::sampleprof::SampleProfileReaderBinary::readMagicIdent(), and startswith().
ThinMagic
const char ThinMagic[] = "!<thin>\n"
Definition at line 42 of file Archive.cpp.
Referenced by llvm::object::Archive::Archive().