LLVM: lib/Target/ARC/ARCInstrInfo.cpp File Reference
ARCInstrInfo.cpp File Reference
#include "ARCInstrInfo.h"
#include "ARC.h"
#include "ARCMachineFunctionInfo.h"
#include "ARCSubtarget.h"
#include "MCTargetDesc/ARCInfo.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/TargetRegistry.h"
#include "ARCGenInstrInfo.inc"
Macros
#define GET_INSTRINFO_CTOR_DTOR
#define DEBUG_TYPE "arc-inst-info"
Enumerations
enum AddrIncType { NoAddInc = 0 , PreInc = 1 , PostInc = 2 , Scaled = 3 }
enum TSFlagsConstants { TSF_AddrModeOff = 0 , TSF_AddModeMask = 3 }
Functions
static bool isZeroImm (const MachineOperand &Op)
static bool isLoad (int Opcode)
static bool isStore (int Opcode)
static ARCCC::CondCode GetOppositeBranchCondition (ARCCC::CondCode CC)
Return the inverse of passed condition, i.e. turning COND_E to COND_NE.
static bool isUncondBranchOpcode (int Opc)
static bool isCondBranchOpcode (int Opc)
static bool isJumpOpcode (int Opc)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arc-inst-info"
Definition at line 29 of file ARCInstrInfo.cpp.
GET_INSTRINFO_CTOR_DTOR
#define GET_INSTRINFO_CTOR_DTOR
Definition at line 26 of file ARCInstrInfo.cpp.
Enumeration Type Documentation
AddrIncType
enum AddrIncType
Enumerator
NoAddInc
PreInc
PostInc
Scaled
Definition at line 31 of file ARCInstrInfo.cpp.
TSFlagsConstants
enum TSFlagsConstants
Enumerator
TSF_AddrModeOff
TSF_AddModeMask
Definition at line 38 of file ARCInstrInfo.cpp.
Function Documentation
GetOppositeBranchCondition()
static ARCCC::CondCode GetOppositeBranchCondition (ARCCC::CondCode CC) static
Return the inverse of passed condition, i.e. turning COND_E to COND_NE.
Definition at line 102 of file ARCInstrInfo.cpp.
References llvm::ARCCC::EQ, llvm::ARCCC::GE, llvm::ARCCC::GT, llvm::ARCCC::HI, llvm::ARCCC::HS, llvm::ARCCC::LE, llvm_unreachable, llvm::ARCCC::LO, llvm::ARCCC::LS, llvm::ARCCC::LT, llvm::ARCCC::NE, llvm::ARCCC::NZ, llvm::ARCCC::VC, llvm::ARCCC::VS, and llvm::ARCCC::Z.
Referenced by llvm::M68kInstrInfo::AnalyzeBranchImpl(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::ARCInstrInfo::reverseBranchCondition(), llvm::SparcInstrInfo::reverseBranchCondition(), llvm::VEInstrInfo::reverseBranchCondition(), llvm::X86InstrInfo::reverseBranchCondition(), and llvm::XCoreInstrInfo::reverseBranchCondition().
isCondBranchOpcode()
static bool isCondBranchOpcode (int Opc) static
Definition at line 139 of file ARCInstrInfo.cpp.
isJumpOpcode()
static bool isJumpOpcode (int Opc) static
Definition at line 143 of file ARCInstrInfo.cpp.
Referenced by llvm::ARCInstrInfo::analyzeBranch().
isLoad()
static bool isLoad (int Opcode) static
Definition at line 53 of file ARCInstrInfo.cpp.
Referenced by llvm::ARMBaseInstrInfo::convertToThreeAddress(), DecodeMem(), DecodeMem(), DecodeMemAS(), llvm::PPCHazardRecognizer970::EmitInstruction(), llvm::MemoryDependenceResults::getDependency(), llvm::PPCHazardRecognizer970::getHazardType(), llvm::MemoryDependenceResults::getNonLocalPointerDependency(), llvm::MemoryDependenceResults::getPointerDependencyFrom(), llvm::MemoryDependenceResults::getPointerDependencyFrom(), llvm::PPCTargetLowering::getPreIndexedAddressParts(), llvm::MemoryDependenceResults::getSimplePointerDependencyFrom(), and llvm::ARCInstrInfo::isLoadFromStackSlot().
isStore()
static bool isStore (int Opcode) static
Definition at line 58 of file ARCInstrInfo.cpp.
Referenced by CombineBaseUpdate(), llvm::PPCHazardRecognizer970::EmitInstruction(), llvm::VPWidenMemoryInstructionRecipe::execute(), llvm::PPCHazardRecognizer970::getHazardType(), llvm::ARCInstrInfo::isStoreToStackSlot(), llvm::ARMInstPrinter::printInst(), and selectLoadStoreUIOp().
isUncondBranchOpcode()
static bool isUncondBranchOpcode (int Opc) static
Definition at line 137 of file ARCInstrInfo.cpp.
isZeroImm()
static bool isZeroImm (const MachineOperand & Op) static
Definition at line 49 of file ARCInstrInfo.cpp.
Referenced by llvm::ARCInstrInfo::isLoadFromStackSlot(), llvm::XCoreInstrInfo::isLoadFromStackSlot(), llvm::ARCInstrInfo::isStoreToStackSlot(), and llvm::XCoreInstrInfo::isStoreToStackSlot().