LLVM: lib/CodeGen/AsmPrinter/AsmPrinterInlineAsm.cpp File Reference
AsmPrinterInlineAsm.cpp File Reference
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Twine.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCParser/MCTargetAsmParser.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
static void EmitMSInlineAsmStr (const char *AsmStr, const MachineInstr *MI, MachineModuleInfo *MMI, AsmPrinter *AP, uint64_t LocCookie, raw_ostream &OS)
static void EmitGCCInlineAsmStr (const char *AsmStr, const MachineInstr *MI, MachineModuleInfo *MMI, const MCAsmInfo *MAI, AsmPrinter *AP, uint64_t LocCookie, raw_ostream &OS)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 41 of file AsmPrinterInlineAsm.cpp.
Function Documentation
EmitGCCInlineAsmStr()
static void EmitGCCInlineAsmStr (const char * AsmStr, const MachineInstr * MI, MachineModuleInfo * MMI, const MCAsmInfo * MAI, AsmPrinter * AP, uint64_t LocCookie, raw_ostream & OS) static
Definition at line 273 of file AsmPrinterInlineAsm.cpp.
References llvm::Done, llvm::LLVMContext::emitError(), llvm::MCAsmInfo::getAssemblerDialect(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::MachineModuleInfo::getContext(), llvm::Module::getContext(), llvm::MCAsmInfo::getEmitGNUAsmStartIndentationMarker(), llvm::MachineModuleInfo::getModule(), llvm::InlineAsm::getNumOperandRegisters(), llvm::MachineBasicBlock::getSymbol(), isDigit(), llvm::InlineAsm::isMemKind(), llvm::AsmPrinter::MAI, MI, llvm::InlineAsm::MIOp_FirstOperand, llvm::MCSymbol::print(), llvm::AsmPrinter::PrintAsmMemoryOperand(), llvm::AsmPrinter::PrintAsmOperand(), llvm::AsmPrinter::PrintSpecial(), llvm::MCContext::registerInlineAsmLabel(), llvm::report_fatal_error(), llvm::raw_string_ostream::str(), and llvm::raw_ostream::write().
EmitMSInlineAsmStr()
static void EmitMSInlineAsmStr (const char * AsmStr, const MachineInstr * MI, MachineModuleInfo * MMI, AsmPrinter * AP, uint64_t LocCookie, raw_ostream & OS) static
Definition at line 131 of file AsmPrinterInlineAsm.cpp.
References llvm::Done, llvm::LLVMContext::emitError(), llvm::Module::getContext(), llvm::MachineModuleInfo::getModule(), llvm::InlineAsm::getNumOperandRegisters(), isDigit(), llvm::InlineAsm::isMemKind(), MI, llvm::InlineAsm::MIOp_FirstOperand, llvm::AsmPrinter::PrintAsmMemoryOperand(), llvm::AsmPrinter::PrintAsmOperand(), llvm::AsmPrinter::PrintSpecial(), llvm::report_fatal_error(), llvm::raw_string_ostream::str(), and llvm::raw_ostream::write().