LLVM: lib/IR/BuiltinGCs.cpp File Reference
BuiltinGCs.cpp File Reference
#include "llvm/IR/BuiltinGCs.h"
#include "llvm/IR/GCStrategy.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/Support/Casting.h"
Variables
static GCRegistry::Add< ErlangGC > A ("erlang", "erlang-compatible garbage collector")
static GCRegistry::Add< OcamlGC > B ("ocaml", "ocaml 3.10-compatible GC")
static GCRegistry::Add< ShadowStackGC > C ("shadow-stack", "Very portable GC for uncooperative code generators")
static GCRegistry::Add< StatepointGC > D ("statepoint-example", "an example strategy for statepoint")
static GCRegistry::Add< CoreCLRGC > E ("coreclr", "CoreCLR-compatible GC")
Variable Documentation
A
GCRegistry::Add< ErlangGC > A("erlang", "erlang-compatible garbage collector") ("erlang" , "erlang-compatible garbage collector") static
Referenced by llvm::opt::Option::accept(), llvm::Automaton< ActionT >::add(), llvm::xray::LogBuilder::add(), AADereferenceableImpl::addAccessedBytesForUse(), AddAliasScopeMetadata(), llvm::SCCPSolver::addAnalysis(), llvm::SCCPInstVisitor::addAnalysis(), llvm::MCJIT::addArchive(), addArgumentAttrs(), addArgumentReturnedAttrs(), llvm::AttributeList::addAttribute(), llvm::AttrBuilder::addAttribute(), addByteCountSuffix(), llvm::opt::ArgList::AddLastArg(), llvm::AttributeList::addParamAttribute(), addRawAttributeValue(), addReadAttr(), llvm::addRuntimeChecks(), llvm::opt::DerivedArgList::AddSynthesizedArg(), llvm::ConstraintSystem::addVariableRow(), adjustDown(), llvm::ARMAsmBackend::adjustFixupValue(), adjustUp(), llvm::AMDGPUAAResult::alias(), llvm::alignTo(), llvm::alignTo(), llvm::alignTo(), alwaysInlineImpl(), llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::InterleavedAccessInfo::analyzeInterleaving(), llvm::opt::ArgList::append(), llvm::cl::aliasopt::apply(), llvm::HexagonSubtarget::BankConflictMutation::apply(), AAIsDeadValueImpl::areAllUsesAssumedDead(), areConsecutiveOrMatch(), llvm::MemoryDepChecker::areDepsSafe(), AreEquivalentAddressValues(), llvm::PPCTTIImpl::areFunctionArgsABICompatible(), llvm::X86TTIImpl::areFunctionArgsABICompatible(), llvm::AttributeFuncs::areOutlineCompatible(), arrayDataSize(), AAValueSimplifyImpl::askSimplifiedValueFor(), AAValueSimplifyImpl::askSimplifiedValueForOtherAAs(), AAIsDeadFunction::assumeLive(), AttemptToFoldSymbolOffsetDifference(), llvm::AttrBuilder::AttrBuilder(), llvm::AttrBuilder::AttrBuilder(), llvm::AttrBuilder::AttrBuilder(), BitsProperlyConcatenate(), bothUsedInPHI(), llvm::coro::buildCoroutineFrame(), buildFrameType(), llvm::buildModuleSummaryIndex(), buildSymbolDiff(), buildSymbolDiff(), llvm::CallBase::bundleOperandHasAttr(), llvm::Automaton< ActionT >::canAdd(), llvm::Value::canBeFreed(), canBeMerged(), canLowerToLDG(), canonicalizeAbs(), canonicalizeBitSelect(), canonicalizeICmpBool(), canonicalizeSaturatedSubtract(), llvm::canReplacePointersIfEqual(), CanShareConstantPoolEntry(), AACaptureUseTracker::captured(), ceilingOfQuotient(), AAValueSimplifyImpl::checkAndUpdate(), llvm::checkedMulAdd(), llvm::checkedMulAddUnsigned(), checkForAllInstructionsImpl(), clampCallSiteArgumentStates(), clampReturnedValueStates(), llvm::orc::EPCIndirectionUtils::cleanup(), llvm::SCEVExpanderCleaner::cleanup(), coalescable(), collectBitParts(), combineADDCARRYDiamond(), combineFMA(), combineKnownAdjacentMMOs(), llvm::AA::combineOptionalValuesInAAValueLatice(), combineORToSHFL(), llvm::sys::commandLineFitsWithinSystemLimits(), llvm::commonAlignment(), llvm::commonAlignment(), llvm::commonAlignment(), llvm::InstCombinerImpl::commonShiftTransforms(), llvm::ChangedIRComparer::compare(), llvm::object::compareAddress(), llvm::IRSimilarity::IRSimilarityCandidate::compareCommutativeOperandMapping(), llvm::IRSimilarity::IRSimilarityCandidate::compareNonCommutativeOperandMapping(), llvm::ValueDFS_Compare::comparePHIRelated(), llvm::IRSimilarity::IRSimilarityCandidate::compareStructure(), llvm::ObjectSizeOffsetVisitor::compute(), llvm::BaseIndexOffset::computeAliasing(), computeAliasSummary(), llvm::HexagonBlockRanges::computeDeadMap(), llvm::computeDelta(), llvm::MCAssembler::computeFragmentSize(), computeKnownBitsFromAssume(), llvm::computeLTOCacheKey(), llvm::rdf::Liveness::computePhiInfo(), computePointerICmp(), llvm::ImmutableListFactory< T >::concat(), llvm::MDNode::concatenate(), ConstantFold(), llvm::AttrBuilder::contains(), llvm::HexagonBlockRanges::IndexRange::contains(), llvm::AttrBuilder::contains(), llvm::rdf::NodeAttrs::contains(), convertArgumentInfo(), llvm::MIRPrinter::convertCallSiteObjects(), llvm::ArrayRef< T >::copy(), llvm::StringRef::copy(), llvm::RegisterBankInfo::copyCost(), llvm::AArch64RegisterBankInfo::copyCost(), llvm::object::Slice::create(), llvm::AAExecutionDomain::createForPosition(), AAAMDAttributes::createForPosition(), AAAMDWorkGroupSize::createForPosition(), createMinMax(), llvm::ImutAVLFactory< ImutInfo >::createNode(), createTargetMachine(), llvm::DebugStr(), llvm::HexagonFrameLowering::determineCalleeSaves(), determinePointerReadAttrs(), llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), llvm::MachineDominatorTree::dominates(), llvm::MachinePostDominatorTree::dominates(), llvm::MachineDominatorTree::dominates(), llvm::MachinePostDominatorTree::dominates(), llvm::MachineDominatorTree::dominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), dominates(), llvm::DWARFFormValue::dump(), dumpAllocas(), llvm::DwarfDebug::DwarfDebug(), llvm::BitTracker::MachineEvaluator::eIMM(), llvm::yaml::SequenceTraits< ArrayDocNode >::element(), eliminateConstraints(), llvm::DwarfStringPool::emit(), llvm::AsmPrinter::emitFunctionBody(), emitOrXorXorTree(), emitWideAPInt(), llvm::json::Array::emplace(), llvm::json::Array::emplace_back(), llvm::encode(), llvm::MachineFunction::ensureAlignment(), llvm::BaseIndexOffset::equalBaseIndex(), llvm::InstrProfLookupTrait::EqualKey(), llvm::ARMConstantPoolConstant::equals(), llvm::ARMConstantPoolMBB::equals(), llvm::ARMConstantPoolSymbol::equals(), llvm::ARMConstantPoolValue::equals(), llvm::sys::fs::equivalent(), equivalentAddressValues(), llvm::rdf::DeadCodeElimination::erase(), llvm::MDAttachments::erase(), llvm::opt::ArgList::eraseArg(), llvm::HexagonEvaluator::evaluate(), llvm::MCExpr::evaluateAsRelocatableImpl(), EvaluateSymbolicAdd(), llvm::RISCVAsmBackend::evaluateTargetFixup(), llvm::SCEVExpander::expandWrapPredicate(), llvm::ModuleSummaryIndex::exportToDot(), ExposePointerBase(), llvm::DWARFAbbreviationDeclaration::extract(), extractSubModule(), FactorOutConstant(), llvm::AArch64CallLowering::fallBackToDAGISel(), fillOverallFunction(), llvm::AccelTableBase::finalize(), Find(), llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator(), llvm::MachineDominatorTree::findNearestCommonDominator(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator(), findStrip(), llvm::MCJIT::findSymbol(), findUses(), firstCommonClass(), fixupFPReturnAndCall(), floorOfQuotient(), foldAndToXor(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpOfUAddOv(), llvm::InstCombinerImpl::foldICmpShlConstConst(), llvm::InstCombinerImpl::foldICmpShrConstConst(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::InstCombinerImpl::foldICmpWithConstant(), llvm::InstCombinerImpl::foldICmpWithZero(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), llvm::InstCombinerImpl::FoldOpIntoSelect(), foldOrToXor(), foldUnsignedUnderflowCheck(), foldXorToXor(), AAAlignImpl::followUseInMBEC(), AADereferenceableImpl::followUseInMBEC(), AANonNullImpl::followUseInMBEC(), followUsesInContext(), followUsesInMBEC(), llvm::DIExpression::fragmentCmp(), llvm::DIExpression::fragmentsOverlap(), llvm::json::fromJSON(), gcd(), llvm::HexagonInstrInfo::genAllInsnTimingClasses(), genericValueTraversal(), llvm::gep_type_begin(), llvm::gep_type_end(), llvm::AttributeSetNode::get(), llvm::MDAttachments::get(), llvm::MCValue::getAccessVariant(), llvm::ScalarEvolution::getAddExpr(), llvm::AttributeSetNode::getAlignment(), llvm::MDAttachments::getAll(), llvm::AttributeSetNode::getAllocSizeArgs(), llvm::rdf::Liveness::getAllReachingDefs(), AAHeapToStackFunction::getAPInt(), llvm::FunctionLoweringInfo::getArgumentFrameIndex(), getArgumentStateFromCallBaseContext(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::SelectionDAG::getAssertAlign(), llvm::AAValueConstantRange::getAssumedConstantInt(), llvm::AA::getAssumedUnderlyingObjects(), AAReturnedValuesImpl::getAssumedUniqueReturnValue(), llvm::AttributeSetNode::getAttribute(), llvm::AttributeSetNode::getAttributeType(), llvm::IRPosition::getAttrs(), llvm::MCAsmLayout::getBaseSymbol(), llvm::ARM::getCanonicalArchName(), llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::TargetRegisterInfo::getCommonSubClass(), llvm::ExecutionEngine::getConstantValue(), getConstraint(), llvm::object::ResourceSectionRef::getContents(), getContiguousRangeOfSetBits(), llvm::AttributeSetNode::getDereferenceableBytes(), llvm::AttributeSetNode::getDereferenceableOrNullBytes(), llvm::SCCPInstVisitor::getDTU(), llvm::NonRelocatableStringpool::getEntriesForEmission(), llvm::GraphTraits< ArgumentGraphNode * >::getEntryNode(), getFPBinOp(), getFPTernOp(), llvm::DbgVariable::getFrameIndexExprs(), llvm::InstrProfSymtab::getFunctionHashFromAddress(), llvm::DefaultAnalysisGraphTraits< AnalysisT, GraphT >::getGraph(), llvm::DenseMapInfo< AAPointerInfo::Access >::getHashValue(), llvm::AccessAsInstructionInfo::getHashValue(), getHashValueImpl(), getHexUint(), llvm::AMDGPU::getIntegerAttribute(), llvm::AMDGPU::getIntegerPairAttribute(), getKnownAlignForUse(), getKnownNonNullAndDerefBytesForUse(), llvm::opt::ArgList::getLastArg(), llvm::opt::ArgList::getLastArgNoClaim(), llvm::opt::ArgList::getLastArgValue(), getLeastCommonType(), getLocalFunctionMetadata(), getMaskedICmpType(), getMaskedTypeForICmpPair(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), llvm::X86RegisterInfo::getMatchingSuperRegClass(), getMinimalBaseOfAccsesPointerOperand(), llvm::GlobalValue::getMinUnnamedAddr(), getMinVisibility(), llvm::MDNode::getMostGenericAliasScope(), llvm::MDNode::getMostGenericAlignmentOrDereferenceable(), llvm::MDNode::getMostGenericFPMath(), llvm::MDNode::getMostGenericRange(), llvm::MDNode::getMostGenericTBAA(), llvm::APIntOps::GetMostSignificantDifferentBit(), llvm::ISD::ArgFlagsTy::getNonZeroByValAlign(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead(), llvm::Value::getPointerAlignment(), llvm::Value::getPointerDereferenceableBytes(), llvm::AA::getPotentialCopiesOfStoredValue(), llvm::SCCPInstVisitor::getPredicateInfoFor(), GetQuadraticEquation(), AAValueSimplifyImpl::getReplacementValue(), llvm::RegScavenger::getScavengingFrameIndices(), AAHeapToStackFunction::getSize(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), getSpillSlotSize(), llvm::AttributeSetNode::getStackAlignment(), getSymbolOffsetImpl(), getSymTab(), llvm::ScalarEvolution::getUDivExpr(), getUnsigned(), llvm::AttributeSetNode::getVScaleRangeArgs(), llvm::Attribute::getWithAlignment(), llvm::Attribute::getWithStackAlignment(), greaterWithBias(), llvm::APIntOps::GreatestCommonDivisor(), llvm::greatestCommonDivisor(), llvm::GreatestCommonDivisor64(), AAPointerInfoFloating::handleAccess(), AAValueSimplifyFloating::handleCmp(), llvm::ChangedIRComparer::handleFunctionCompare(), AAValueSimplifyFloating::handleGenericInst(), AAValueSimplifyImpl::handleLoad(), llvm::hasAssumption(), llvm::IRPosition::hasAttr(), llvm::AttributeImpl::hasAttribute(), llvm::sampleprof::SampleContext::hasAttribute(), llvm::opt::ArgList::hasFlag(), llvm::opt::ArgList::hasFlag(), llvm::ReachingDefAnalysis::hasSameReachingDef(), HasSameValue(), llvm::SelectionDAG::haveNoCommonBitsSet(), llvm::rdf::NodeAllocator::id(), identifyAliveSuccessors(), identifyAliveSuccessors(), identifyAliveSuccessors(), identifyAliveSuccessors(), AAPrivatizablePtrArgument::identifyPrivatizableType(), AAPrivatizablePtrFloating::identifyPrivatizableType(), llvm::IRAttribute< AK, BaseType >::initialize(), AAPointerInfoImpl::initialize(), AAPointerInfoFloating::initialize(), AAPointerInfoArgument::initialize(), AANoUnwindCallSite::initialize(), AAReturnedValuesImpl::initialize(), AANoSyncCallSite::initialize(), AANoFreeCallSite::initialize(), AANonNullImpl::initialize(), AANoRecurseFunction::initialize(), AANoRecurseCallSite::initialize(), AAWillReturnImpl::initialize(), AAWillReturnFunction::initialize(), AAWillReturnCallSite::initialize(), AANoAliasFloating::initialize(), AANoAliasArgument::initialize(), AANoAliasReturned::initialize(), AANoAliasCallSiteReturned::initialize(), AAIsDeadFloating::initialize(), AAIsDeadArgument::initialize(), AAIsDeadCallSiteReturned::initialize(), AAIsDeadFunction::initialize(), AADereferenceableImpl::initialize(), AAAlignImpl::initialize(), AAAlignReturned::initialize(), AAAlignCallSiteReturned::initialize(), AANoReturnImpl::initialize(), AANoReturnCallSite::initialize(), AANoCaptureImpl::initialize(), AANoCaptureCallSiteArgument::initialize(), AAValueSimplifyImpl::initialize(), AAValueSimplifyArgument::initialize(), AAValueSimplifyFloating::initialize(), AAValueSimplifyCallSiteReturned::initialize(), AAHeapToStackFunction::initialize(), AAMemoryBehaviorImpl::initialize(), AAMemoryBehaviorArgument::initialize(), AAMemoryBehaviorCallSiteArgument::initialize(), AAMemoryBehaviorCallSiteReturned::initialize(), AAMemoryBehaviorCallSite::initialize(), llvm::mca::initializeUsedResources(), llvm::DiagnosticInfoOptimizationBase::insert(), llvm::json::Array::insert(), insertSpills(), intersect(), llvm::MDNode::intersect(), isAddSExtable(), llvm::AMDGPU::isArgPassedInSGPR(), llvm::AAReachability::isAssumedReachable(), AAIsDeadValueImpl::isAssumedSideEffectFree(), llvm::InstructionOrdering::isBefore(), IsBetterCanonical(), isClampZeroToOne(), llvm::IRSimilarity::isClose(), llvm::isConsecutiveAccess(), isContiguous(), isContiguous(), AAIsDeadFloating::isDeadStore(), AACaptureUseTracker::isDereferenceableOrNull(), llvm::AA::isDynamicallyUnique(), llvm::SlotIndex::isEarlierEqualInstr(), llvm::SlotIndex::isEarlierInstr(), llvm::AArch64CallLowering::isEligibleForTailCallOptimization(), llvm::AMDGPUCallLowering::isEligibleForTailCallOptimization(), llvm::DenseMapInfo< DebugVariable >::isEqual(), llvm::DenseMapInfo< DIExpression::FragmentInfo >::isEqual(), llvm::DenseMapInfo< object::SectionRef >::isEqual(), llvm::DenseMapInfo< SlotWithTag >::isEqual(), llvm::DenseMapInfo< std::pair< const MCSymbol *, MCSymbolRefExpr::VariantKind > >::isEqual(), llvm::SelectionDAG::isEqualTo(), llvm::RecurrenceDescriptor::isFirstOrderRecurrence(), llvm::CallBase::isFnAttrDisallowedByOpBundle(), isGuaranteedNotToBeUndefOrPoison(), isHorizontalBinOp(), AAWillReturnImpl::isImpliedByMustprogressAndReadonly(), llvm::BitTracker::MachineEvaluator::isInt(), llvm::isKnownNegation(), AANoAliasCallSiteArgument::isKnownNoAliasDueToNoAliasPreservation(), isKnownNonZero(), llvm::AAReachability::isKnownReachable(), llvm::HexagonTargetLowering::isLegalAddressingMode(), llvm::LoopVectorizationCostModel::isMoreProfitable(), isNoAliasOrByValArgument(), isOnlyUsedInEntryBlock(), llvm::SelectionDAGISel::isOrEquivalentToAdd(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::isPermutation(), isPointerBitcastEqualTo(), llvm::isPotentiallyReachable(), llvm::isPotentiallyReachable(), llvm::DominatorTreeBase< NodeT, IsPostDom >::isReachableFromEntry(), llvm::MachineDominatorTree::isReachableFromEntry(), llvm::DominatorTreeBase< NodeT, IsPostDom >::isReachableFromEntry(), llvm::SlotIndex::isSameInstr(), llvm::SITargetLowering::isSDNodeSourceOfDivergence(), StrBoolAttr::isSet(), llvm::IRSimilarity::IRSimilarityCandidate::isSimilar(), isSortedByValueNo(), llvm::GCNTTIImpl::isSourceOfDivergence(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolved(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::AMDGPUMachineModuleInfo::isSyncScopeInclusion(), isTruePredicate(), llvm::AA::isValidAtPosition(), llvm::AA::isValidInScope(), llvm::DominatorTreeBase< NodeT, IsPostDom >::isVirtualRoot(), llvm::LazyCallGraph::LazyCallGraph(), lcm(), legalizeCallAttributes(), llvm::cfg::LegalizeUpdates(), llvm::HexagonInstr::lessCore(), llvm::HexagonInstr::lessCVI(), llvm::HexagonResource::lessUnits(), llvm::HexagonResource::lessWeight(), LLVMAddAttributeAtIndex(), LLVMAddCallSiteAttribute(), LLVMAddTargetDependentFunctionAttr(), LLVMGetAttributesAtIndex(), LLVMGetCallSiteAttributes(), LLVMGetEnumAttributeKind(), LLVMGetEnumAttributeValue(), LLVMGetNextParam(), LLVMGetParams(), LLVMGetPreviousParam(), LLVMGetStringAttributeKind(), LLVMGetStringAttributeValue(), LLVMGetTypeAttributeValue(), LLVMInitializeAMDGPUAsmParser(), LLVMInitializeARMAsmParser(), LLVMInitializeARMAsmPrinter(), LLVMInitializeARMTarget(), LLVMInitializeARMTargetInfo(), LLVMInitializeMipsAsmParser(), LLVMInitializeMipsAsmPrinter(), LLVMInitializeMipsTarget(), LLVMInitializeMipsTargetInfo(), LLVMInitializePowerPCAsmParser(), LLVMInitializePowerPCTarget(), LLVMInitializeSparcAsmParser(), LLVMInitializeVEAsmParser(), LLVMIsEnumAttribute(), LLVMIsStringAttribute(), LLVMIsTypeAttribute(), LLVMSetParamAlignment(), llvm::object::ResourceSectionRef::load(), loadObj(), llvm::ValueDFS_Compare::localComesBefore(), llvm::MDAttachments::lookup(), llvm::HexagonTargetLowering::LowerBlockAddress(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), llvm::HexagonTargetLowering::LowerDYNAMIC_STACKALLOC(), LowerMUL(), LowerMULH(), LowerMULO(), LowerShift(), LowervXi8MulWithUNPCK(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), llvm::MachineFunction::makeDebugValueSubstitution(), llvm::makeIntrusiveRefCnt(), llvm::orc::makeStub(), llvm::IRAttribute< AK, BaseType >::manifest(), AAAMDWorkGroupSizeFunction::manifest(), AAAMDAttributesFunction::manifest(), AAPointerInfoImpl::manifest(), AAReturnedValuesImpl::manifest(), AAUndefinedBehaviorImpl::manifest(), AAIsDeadFloating::manifest(), AAIsDeadArgument::manifest(), AAIsDeadCallSiteArgument::manifest(), AAIsDeadReturned::manifest(), AAIsDeadFunction::manifest(), AADereferenceableImpl::manifest(), AAAlignImpl::manifest(), AAAlignArgument::manifest(), AAAlignCallSiteArgument::manifest(), AAValueSimplifyImpl::manifest(), AAValueSimplifyReturned::manifest(), AAValueSimplifyCallSiteArgument::manifest(), AAHeapToStackFunction::manifest(), AAPrivatizablePtrArgument::manifest(), AAMemoryBehaviorImpl::manifest(), AAMemoryBehaviorArgument::manifest(), AAMemoryBehaviorFunction::manifest(), llvm::yaml::MappingTraits< ArchYAML::Archive >::mapping(), llvm::yaml::MappingTraits< Argument >::mapping(), llvm::yaml::MappingTraits< SIArgument >::mapping(), llvm::SCCPSolver::markArgInFuncSpecialization(), llvm::SCCPInstVisitor::markArgInFuncSpecialization(), markTails(), matchAccessTags(), matchDeMorgansLaws(), matchesAdd(), matchesOr(), matchMinMaxOfMinMax(), matchSelectWithOptionalNotCond(), matchUAddWithOverflowConstantEdgeCases(), llvm::maximum(), llvm::maxnum(), AANoAliasCallSiteArgument::mayAliasWithArgument(), mayContainUnboundedCycle(), memAccessesCanBeReordered(), llvm::HexagonBlockRanges::IndexRange::merge(), merge(), MergeAliasResults(), llvm::DDGBuilder::mergeNodes(), MergeSeqs(), llvm::MinAlign(), llvm::minimum(), llvm::minnum(), llvm::ConstantRange::multiply(), llvm::detail::DoubleAPFloat::multiply(), llvm::NextPowerOf2(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyFinalized(), llvm::OperandBundleUse::operandHasAttr(), operator delete(), operator new(), llvm::Attribute::operator!=(), llvm::AAMDNodes::operator!=(), llvm::CHIArg::operator!=(), llvm::codeview::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), std::hash< llvm::rdf::RegisterAggr >::operator()(), std::equal_to< llvm::rdf::RegisterAggr >::operator()(), llvm::ValueDFS_Compare::operator()(), std::hash< llvm::rdf::RegisterRef >::operator()(), llvm::Attribute::operator<(), llvm::operator<(), llvm::codeview::operator<(), llvm::HexagonBlockRanges::IndexRange::operator<(), llvm::opt::operator<(), llvm::operator<(), llvm::operator<<(), llvm::codeview::operator<<(), llvm::rdf::operator<<(), llvm::operator<<(), llvm::operator<<(), llvm::codeview::operator<=(), llvm::Attribute::operator==(), llvm::AAMDNodes::operator==(), llvm::CHIArg::operator==(), llvm::operator==(), llvm::codeview::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::rdf::RegisterAggr::operator==(), llvm::operator==(), llvm::operator==(), llvm::codeview::operator>(), llvm::codeview::operator>=(), llvm::sys::fs::operator|(), llvm::sys::fs::operator|(), llvm::sys::fs::operator|=(), llvm::sys::fs::operator|=(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), orderModule(), orderModule(), llvm::IRSimilarity::IRSimilarityCandidate::overlap(), llvm::HexagonBlockRanges::IndexRange::overlaps(), llvm::AArch64::parseArch(), llvm::ARM::parseArch(), llvm::AArch64::parseArchExt(), llvm::ARM::parseArchExt(), llvm::opt::OptTable::ParseArgs(), llvm::opt::OptTable::parseArgs(), llvm::cl::ParseCommandLineOptions(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), llvm::opt::OptTable::ParseOneArg(), llvm::parseWidenableBranch(), performAddDotCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), PerformSETCCCombine(), PerformVECREDUCE_ADDCombine(), performVecReduceAddCombine(), PickMostRelevantLoop(), llvm::PowerOf2Ceil(), llvm::PowerOf2Floor(), predictUseListOrder(), predictUseListOrder(), llvm::opt::ArgList::print(), llvm::DemandedBits::print(), llvm::MemoryDef::print(), llvm::PhysicalRegisterUsageInfo::print(), llvm::json::Path::Root::printErrorContext(), llvm::Pattern::printVariableDefs(), llvm::HexagonFrameLowering::processFunctionBeforeFrameFinalized(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), ProfileFoldOpInit(), llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates(), llvm::MachineDominatorTree::properlyDominates(), llvm::MachinePostDominatorTree::properlyDominates(), llvm::MachineDominatorTree::properlyDominates(), llvm::MachinePostDominatorTree::properlyDominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates(), r0(), r1(), r2(), r3(), r4(), llvm::GVNHoist::rank(), llvm::objcarc::ProvenanceAnalysis::related(), RemoveAttribute(), llvm::AttrBuilder::removeAttribute(), llvm::AttrBuilder::removeAttributes(), llvm::object::resolveRISCV(), llvm::APIntOps::RoundingSDiv(), llvm::APIntOps::RoundingUDiv(), llvm::TypeFinder::run(), llvm::OpenMPOptCGSCCPass::run(), llvm::OpenMPOptPass::run(), runAttributorOnFunctions(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), llvm::runIPSCCP(), AMDGPUAttributor::runOnModule(), llvm::sampleprof::SampleSorter< LocationT, SampleT >::SampleSorter(), llvm::SaturatingMultiplyAdd(), llvm::HexagonDAGToDAGISel::SelectConstantFP(), llvm::HexagonDAGToDAGISel::SelectIndexedLoad(), llvm::HexagonDAGToDAGISel::SelectIndexedStore(), llvm::HexagonDAGToDAGISel::SelectVAlignAddr(), llvm::LoopVectorizationCostModel::selectVectorizationFactor(), llvm::rdf::NodeAttrs::set_flags(), llvm::rdf::NodeAttrs::set_kind(), llvm::rdf::NodeAttrs::set_type(), llvm::pdb::DbiStreamBuilder::setAge(), llvm::pdb::InfoStreamBuilder::setAge(), llvm::GVN::ValueTable::setAliasAnalysis(), llvm::MachineBasicBlock::setAlignment(), llvm::MachineFunction::setAlignment(), llvm::sampleprof::SampleContext::setAllAttributes(), llvm::FunctionLoweringInfo::setArgumentFrameIndex(), llvm::sampleprof::SampleContext::setAttribute(), llvm::CallBase::setAttributes(), llvm::GlobalVariable::setAttributes(), llvm::rdf::NodeBase::setAttrs(), setInsertionPoint(), llvm::ISD::ArgFlagsTy::setMemAlign(), llvm::ISD::ArgFlagsTy::setOrigAlign(), AACaptureUseTracker::shouldExplore(), llvm::ARMAsmBackend::shouldForceRelocation(), llvm::SIMachineFunctionInfo::SIMachineFunctionInfo(), simplifyAndOfICmpsWithSameOperands(), SimplifyAssociativeBinOp(), llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative(), simplifyICmpWithBinOp(), simplifyICmpWithMinMax(), SimplifyOrInst(), simplifyOrOfICmpsWithSameOperands(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), simplifyUnsignedRangeCheck(), llvm::InstCombinerImpl::SimplifyUsingDistributiveLaws(), simplifyValueKnownNonZero(), sinkInstruction(), sinkLoopInvariantInstructions(), sinkSpillUsesAfterCoroBegin(), llvm::yaml::SequenceTraits< ArrayDocNode >::size(), llvm::APIntOps::smax(), llvm::APIntOps::smin(), llvm::ConstantRange::smul_sat(), SolveLinEquationWithOverflow(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), llvm::APIntOps::SolveQuadraticEquationWrap(), sortGlobalExprs(), llvm::DebugLocEntry::sortUniqueValues(), llvm::StringRef::split(), llvm::StringRef::split(), SplitAddRecs(), llvm::DINode::splitFlags(), llvm::stable_hash_combine(), llvm::stable_hash_combine(), llvm::stable_hash_combine(), llvm::Function::stealArgumentListFrom(), llvm::opt::StrCmpOptionName(), llvm::opt::StrCmpOptionNameIgnoreCase(), stripAndAccumulateMinimalOffsets(), StripAttr(), stripNonValidAttributesFromPrototype(), llvm::BitTracker::MachineEvaluator::toInt(), llvm::object::ELFFile< ELFT >::toMappedAddr(), AAPointerInfoImpl::translateAndAddCalleeState(), llvm::InstCombinerImpl::tryFactorization(), TryToSinkInstruction(), llvm::APIntOps::umax(), llvm::APIntOps::umin(), unifyBitWidth(), llvm::AbstractAttribute::update(), AAAMDWorkGroupSizeFunction::updateImpl(), AAAMDAttributesFunction::updateImpl(), AAReturnedFromReturnedValues< AAType, BaseType, StateType, PropagateCallBaseContext >::updateImpl(), AAArgumentFromCallSiteArguments< AAType, BaseType, StateType, BridgeCallBaseContext >::updateImpl(), AACallSiteReturnedFromReturned< AAType, BaseType, StateType, IntroduceCallBaseContext >::updateImpl(), AAPointerInfoFloating::updateImpl(), AAPointerInfoCallSiteArgument::updateImpl(), AANoUnwindImpl::updateImpl(), AANoUnwindCallSite::updateImpl(), AAReturnedValuesImpl::updateImpl(), AANoSyncImpl::updateImpl(), AANoSyncCallSite::updateImpl(), AANoFreeImpl::updateImpl(), AANoFreeCallSite::updateImpl(), AANoFreeFloating::updateImpl(), AANoFreeCallSiteArgument::updateImpl(), AANonNullFloating::updateImpl(), AANoRecurseFunction::updateImpl(), AANoRecurseCallSite::updateImpl(), AAUndefinedBehaviorImpl::updateImpl(), AAWillReturnImpl::updateImpl(), AAWillReturnCallSite::updateImpl(), AANoAliasArgument::updateImpl(), AANoAliasCallSiteArgument::updateImpl(), AANoAliasReturned::updateImpl(), AANoAliasCallSiteReturned::updateImpl(), AAIsDeadFloating::updateImpl(), AAIsDeadCallSiteArgument::updateImpl(), AAIsDeadCallSiteReturned::updateImpl(), AAIsDeadReturned::updateImpl(), AAIsDeadFunction::updateImpl(), AADereferenceableFloating::updateImpl(), AAAlignFloating::updateImpl(), AAAlignCallSiteArgument::updateImpl(), AANoReturnImpl::updateImpl(), AANoReturnCallSite::updateImpl(), AANoCaptureImpl::updateImpl(), AANoCaptureCallSiteArgument::updateImpl(), AAValueSimplifyArgument::updateImpl(), AAValueSimplifyReturned::updateImpl(), AAValueSimplifyFloating::updateImpl(), AAValueSimplifyCallSiteReturned::updateImpl(), AAHeapToStackFunction::updateImpl(), AAPrivatizablePtrArgument::updateImpl(), AAPrivatizablePtrCallSiteArgument::updateImpl(), AAMemoryBehaviorFloating::updateImpl(), AAMemoryBehaviorCallSiteArgument::updateImpl(), AAMemoryBehaviorFunction::updateImpl(), AAMemoryBehaviorCallSite::updateImpl(), AAValueSimplifyFloating::updateWithLoad(), llvm::UpgradeIntrinsicCall(), upgradeMaskedMove(), llvm::yaml::MappingTraits< ArchYAML::Archive >::validate(), llvm::valueComesBefore(), llvm::ValueEnumerator::ValueEnumerator(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::ObjectSizeOffsetVisitor::visitArgument(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitXor(), llvm::InstCombinerImpl::visitZExt(), llvm::InnerLoopVectorizer::widenInstruction(), llvm::ScalarEvolution::willNotOverflow(), llvm::WinException::WinException(), llvm::TimeTraceProfiler::write(), writeArrayData(), writeDIExpression(), llvm::sampleprof::SampleProfileWriter::writeFuncProfiles(), llvm::InstrProfWriter::writeText(), and writeWholeProgramDevirtResolution().
B
GCRegistry::Add< OcamlGC > B("ocaml", "ocaml 3.10-compatible GC") ("ocaml" , "ocaml 3.10-compatible GC") static
Referenced by llvm::AttributeList::addAllocSizeAttr(), llvm::AttributeSet::addAttribute(), llvm::AttributeSet::addAttribute(), llvm::AttributeList::addAttribute(), llvm::AttributeList::addAttribute(), llvm::AttributeSet::addAttributes(), llvm::AttributeList::addAttributes(), llvm::Argument::addAttrs(), llvm::xray::Profile::addBlock(), llvm::jitlink::BlockAddressMap::addBlock(), llvm::jitlink::BlockAddressMap::addBlocks(), llvm::jitlink::BlockAddressMap::addBlocksWithoutChecking(), llvm::jitlink::BlockAddressMap::addBlockWithoutChecking(), llvm::FoldingSetNodeID::AddBoolean(), llvm::AttributeList::addDereferenceableAttr(), llvm::AttributeList::addDereferenceableOrNullAttr(), addDiscriminators(), llvm::codeview::DebugLinesSubsection::addLineAndColumnInfo(), llvm::codeview::DebugLinesSubsection::addLineInfo(), llvm::AttributeList::addParamAttribute(), llvm::AttributeList::addParamAttributes(), llvm::ScheduleDAGInstrs::addPhysRegDeps(), llvm::SpillPlacement::addPrefSpill(), addRawAttributeValue(), llvm::addRuntimeChecks(), llvm::AttributeList::addVScaleRangeAttr(), adjustedSumFreq(), llvm::ARMFrameLowering::adjustForSegmentedStacks(), llvm::AMDGPUAAResult::alias(), llvm::jitlink::JITLinkerBase::alignToBlock(), llvm::jitlink::JITLinkerBase::alignToBlock(), llvm::lowertypetests::ByteArrayBuilder::allocate(), allocateHSAUserSGPRs(), llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::InterleavedAccessInfo::analyzeInterleaving(), llvm::object::append(), applyAArch64MulConstCombine(), applyBuildVectorToDup(), applyDupLane(), applyExtractVecEltPairwiseAdd(), llvm::jitlink::x86_64::applyFixup(), applyFoldGlobalOffset(), applyFoldMergeToZext(), llvm::AMDGPURegisterBankInfo::applyMappingBFE(), llvm::AMDGPURegisterBankInfo::applyMappingDynStackAlloc(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::MipsRegisterBankInfo::applyMappingImpl(), llvm::AMDGPURegisterBankInfo::applyMappingLoad(), llvm::AMDGPURegisterBankInfo::applyMappingSBufferLoad(), areConsecutiveOrMatch(), llvm::Bitfield::areContiguous(), llvm::MemoryDepChecker::areDepsSafe(), AreEquivalentAddressValues(), llvm::TargetLibraryInfo::areInlineCompatible(), llvm::AttributeFuncs::areOutlineCompatible(), AttemptToFoldSymbolOffsetDifference(), BitsProperlyConcatenate(), llvm::rdf::DataFlowGraph::build(), buildAddr64RSrc(), buildBitFieldInsert(), buildCopyFromRegs(), buildCopyToRegs(), buildFrameType(), buildMul(), buildNonAtomicBinOp(), buildOffsetSrc(), buildOrChain(), llvm::AMDGPULegalizerInfo::buildPCRelGlobalAddress(), buildRSRC(), buildSymbolDiff(), buildSymbolDiff(), llvm::AMDGPURegisterBankInfo::buildVCopy(), llvm::codeview::DebugLinesSubsection::calculateSerializedSize(), canBeMerged(), canonicalizeBitSelect(), canonicalizeICmpBool(), canonicalizeSaturatedSubtract(), llvm::canReplacePointersIfEqual(), CanShareConstantPoolEntry(), llvm::castToCStr(), ceilingOfQuotient(), llvm::ChangedBlockData::ChangedBlockData(), llvm::checkedMulAdd(), llvm::checkedMulAddUnsigned(), checkOuterLoopInsts(), llvm::BitTracker::RegisterCell::cl(), clampDynamicVectorIndex(), llvm::object::MinidumpFile::classof(), llvm::object::XCOFFObjectFile::classof(), llvm::VPWidenPHIRecipe::classof(), llvm::SCEVExpanderCleaner::cleanup(), coalescable(), collectBitParts(), combineADDCARRYDiamond(), combineFMA(), combineKnownAdjacentMMOs(), llvm::Combiner::combineMachineInstrs(), llvm::AA::combineOptionalValuesInAAValueLatice(), combineORToSHFL(), llvm::codeview::DebugLinesSubsection::commit(), llvm::commonAlignment(), llvm::commonAlignment(), llvm::ChangedIRComparer::compare(), llvm::object::compareAddress(), llvm::IRSimilarity::IRSimilarityCandidate::compareCommutativeOperandMapping(), llvm::IRSimilarity::IRSimilarityCandidate::compareNonCommutativeOperandMapping(), llvm::ValueDFS_Compare::comparePHIRelated(), llvm::IRSimilarity::IRSimilarityCandidate::compareStructure(), llvm::BaseIndexOffset::computeAliasing(), llvm::computeDelta(), computeKnownBitsFromAssume(), llvm::rdf::Liveness::computeLiveIns(), computeUnlikelySuccessors(), llvm::MDNode::concatenate(), ConnectEpilog(), ConnectProlog(), llvm::AMDGPURegisterBankInfo::constrainOpWithReadfirstlane(), constrainRegToBank(), llvm::RegionBase< Tr >::contains(), llvm::rdf::NodeAttrs::contains(), llvm::MIRPrinter::convertCallSiteObjects(), convertImageAddrToPacked(), llvm::SimplifyCFGOptions::convertSwitchToLookupTable(), llvm::RegisterBankInfo::copyCost(), llvm::AArch64RegisterBankInfo::copyCost(), llvm::FeatureBitset::count(), llvm::CallBase::CountBundleInputs(), llvm::SanitizerStatReport::create(), llvm::sampleprof::SampleProfileReader::create(), llvm::sampleprof::SampleProfileReaderItaniumRemapper::create(), llvm::jitlink::x86_64::createAnonymousPointer(), CreateAssert(), CreateAssertNot(), llvm::InnerLoopVectorizer::createInductionResumeValues(), llvm::InnerLoopVectorizer::createInductionVariable(), createMaskedBitTest(), createMinMax(), llvm::createOrderedReduction(), llvm::jitlink::x86_64::createPointerJumpStubBlock(), createPowWithIntegerExponent(), CreatePrologue(), createStepForVF(), llvm::createTargetReduction(), llvm::ThunkInserter< Derived >::createThunkFunction(), llvm::TileInfo::CreateTiledLoops(), llvm::Function::createWithDefaultAttr(), llvm::BitTracker::RegisterCell::ct(), DbgGatherSalvagableDVI(), DecodeBranchTargetS(), DecodeFromCyclicRange(), decodeLLVMAttributesForBitcode(), DecodeSignedOperand(), doList(), llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), llvm::MachineDominatorTree::dominates(), llvm::MachinePostDominatorTree::dominates(), llvm::MachineDominatorTree::dominates(), llvm::MachinePostDominatorTree::dominates(), llvm::MachineDominatorTree::dominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::dominates(), dominates(), llvm::jitlink::LinkGraph::dump(), dumpMachineInstrRangeWithSlotIndex(), llvm::BitTracker::MachineEvaluator::eCLB(), llvm::BitTracker::MachineEvaluator::eCTB(), llvm::object::elf_section_iterator::elf_section_iterator(), llvm::M68kFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), eliminateConstraints(), llvm::DwarfStringPool::emit(), llvm::OnDiskChainedHashTableGenerator< Info >::Emit(), llvm::emitBCmp(), llvm::emitBinaryFloatFnCall(), llvm::emitBinaryFloatFnCall(), emitBinaryFloatFnCallHelper(), llvm::BitstreamWriter::emitBlob(), llvm::emitCalloc(), llvm::emitFPutC(), llvm::emitFPutS(), llvm::AsmPrinter::emitFunctionBody(), llvm::emitFWrite(), emitLibCall(), llvm::emitMalloc(), llvm::emitMemCCpy(), llvm::emitMemChr(), llvm::emitMemCmp(), llvm::emitMemCpyChk(), llvm::emitMemPCpy(), emitOrXorXorTree(), llvm::HexagonFrameLowering::emitPrologue(), llvm::emitPutChar(), llvm::emitPutS(), emitReciprocalU64(), llvm::emitSNPrintf(), llvm::emitSPrintf(), llvm::emitStpCpy(), llvm::emitStpNCpy(), llvm::emitStrCat(), llvm::emitStrChr(), llvm::emitStrCpy(), llvm::emitStrDup(), llvm::emitStrLCat(), llvm::emitStrLCpy(), llvm::emitStrLen(), llvm::emitStrNCat(), llvm::emitStrNCmp(), llvm::emitStrNCpy(), llvm::InnerLoopVectorizer::emitTransformedIndex(), llvm::emitUnaryFloatFnCall(), llvm::emitUnaryFloatFnCall(), emitUnaryFloatFnCallHelper(), llvm::emitVSNPrintf(), llvm::emitVSPrintf(), llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::equal_range(), llvm::BaseIndexOffset::equalBaseIndex(), llvm::InstrProfLookupTrait::EqualKey(), llvm::sys::fs::equivalent(), equivalentAddressValues(), llvm::rdf::DeadCodeElimination::erase(), llvm::MCExpr::evaluateAsRelocatableImpl(), EvaluateSymbolicAdd(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::AMDGPURegisterBankInfo::executeInWaterfallLoop(), llvm::BitstreamWriter::ExitBlock(), expandBinOp(), extendLow32IntoHigh32(), llvm::BitTracker::MachineEvaluator::eXTR(), llvm::BitTracker::RegisterCell::extract(), extractF64Exponent(), llvm::FeatureBitset::FeatureBitset(), llvm::BitTracker::RegisterCell::fill(), llvm::SimpleBitstreamCursor::fillCurWord(), llvm::opt::ArgList::filtered(), llvm::opt::ArgList::filtered_reverse(), llvm::AccelTableBase::finalize(), llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >::OrcRPCAllocation::finalizeAsync(), llvm::pdb::GSIHashStreamBuilder::finalizeBuckets(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::find(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::find(), llvm::MachineDominanceFrontier::find(), llvm::MachineDominanceFrontier::find(), findCFILocation(), findCommonType(), llvm::wholeprogramdevirt::findLowestOffset(), llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator(), llvm::MachineDominatorTree::findNearestCommonDominator(), llvm::MachinePostDominatorTree::findNearestCommonDominator(), llvm::DominatorTreeBase< NodeT, IsPostDom >::findNearestCommonDominator(), llvm::SanitizerStatReport::finish(), llvm::BitTracker::BitMask::first(), first_use_of_in_block(), firstCommonClass(), llvm::AMDGPULegalizerInfo::fixStoreSourceType(), llvm::InnerLoopVectorizer::fixupIVUsers(), floorOfQuotient(), llvm::AMDGPULibCalls::fold(), foldAndToXor(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpEquality(), foldICmpOfUAddOv(), llvm::InstCombinerImpl::foldICmpUsingKnownBits(), llvm::InstCombinerImpl::foldICmpWithConstant(), llvm::InstCombinerImpl::foldICmpWithZero(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), llvm::InstCombinerImpl::FoldOpIntoSelect(), foldOrToXor(), foldSelectICmpAndAnd(), foldUnsignedUnderflowCheck(), foldXorToXor(), llvm::format_provider< bool >::format(), llvm::format_provider< codeview::GloballyHashedType >::format(), llvm::SimplifyCFGOptions::forwardSwitchCondToPhi(), llvm::DIExpression::fragmentCmp(), llvm::DIExpression::fragmentsOverlap(), gcd(), llvm::HexagonInstrInfo::genAllInsnTimingClasses(), generateCreationChecks(), generateCreationChecksForBinOp(), llvm::ChangedIRComparer::generateFunctionData(), llvm::msf::MSFBuilder::generateLayout(), llvm::AttributeSet::get(), llvm::AttributeSetNode::get(), llvm::AttributeList::get(), llvm::VarBitInit::get(), llvm::VPTransformState::get(), llvm::MCValue::getAccessVariant(), llvm::ScalarEvolution::getAddExpr(), llvm::HexagonFrameLowering::getAlignaInstr(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::VarBitInit::getBit(), getBitcastWiderVectorElementOffset(), llvm::jitlink::BlockAddressMap::getBlockCovering(), getBlockName(), llvm::SIScheduleBlockCreator::getBlocks(), llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::RegionInfoBase< Tr >::getCommonRegion(), llvm::TargetRegisterInfo::getCommonSubClass(), getConstraint(), llvm::object::ResourceSectionRef::getContents(), llvm::getDeadRegState(), llvm::getDebugRegState(), llvm::getDefRegState(), llvm::HexagonInstrInfo::getDotNewPredJumpOp(), getEmscriptenFunction(), llvm::NonRelocatableStringpool::getEntriesForEmission(), llvm::GraphTraits< Inverse< VPBlockBase * > >::getEntryNode(), llvm::LoopBase< BasicBlock, Loop >::getExitEdges(), llvm::MachineBasicBlock::getFirstInstrTerminator(), llvm::MachineBasicBlock::getFirstTerminator(), getFPBinOp(), getFPTernOp(), llvm::DbgVariable::getFrameIndexExprs(), llvm::StatepointOpers::getGCPointerMap(), getHashValueImpl(), llvm::BlockFrequencyInfoImplBase::LoopData::getHeaderIndex(), llvm::AMDGPULegalizerInfo::getImplicitArgPtr(), llvm::getImplRegState(), llvm::SlotIndexes::getIndexBefore(), getInputSegmentList(), llvm::getInternalReadRegState(), getIntToFPVal(), llvm::getKillRegState(), llvm::MachineBasicBlock::getLastNonDebugInstr(), getLeastCommonType(), getLiveInRegsAt(), getLiveOutRegsAt(), llvm::LoopBase< BasicBlock, Loop >::getLoopPreheader(), llvm::DILocation::getMaskedDiscriminator(), getMaskedICmpType(), getMaskedTypeForICmpPair(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), llvm::X86RegisterInfo::getMatchingSuperRegClass(), llvm::GlobalValue::getMinUnnamedAddr(), getMinVisibility(), llvm::MDNode::getMostGenericAliasScope(), llvm::MDNode::getMostGenericAlignmentOrDereferenceable(), llvm::MDNode::getMostGenericFPMath(), llvm::MDNode::getMostGenericRange(), llvm::MDNode::getMostGenericTBAA(), llvm::APIntOps::GetMostSignificantDifferentBit(), llvm::rdf::Liveness::getNearestAliasedRef(), getNonDebugInstr(), getPow(), GetQuadraticEquation(), llvm::getRenamableRegState(), llvm::jitlink::getRISCVPCRelHi20(), llvm::getRuntimeVF(), llvm::GCNIterativeScheduler::getSchedulePressure(), llvm::AMDGPULegalizerInfo::getSegmentAperture(), llvm::slpvectorizer::BoUpSLP::getSpillCost(), getSqrtCall(), getStackGuard(), getStatepointArgs(), getSymbolOffsetImpl(), llvm::AttributeFuncs::getUBImplyingAttributes(), llvm::getUndefRegState(), getUnmergePieces(), llvm::jitlink::ELFLinkGraphBuilder< ELFT >::graphifySymbols(), greaterWithBias(), llvm::APIntOps::GreatestCommonDivisor(), llvm::greatestCommonDivisor(), llvm::GreatestCommonDivisor64(), llvm::AMDGPURegisterBankInfo::handleD16VData(), llvm::AMDGPULegalizerInfo::handleD16VData(), llvm::ChangedIRComparer::handleFunctionCompare(), handleMemIntrinsicPtrUse(), llvm::objcarc::hasAttachedCallOpBundle(), llvm::HexagonInstrInfo::hasEHLabel(), llvm::LoopBase< BasicBlock, Loop >::hasNoExitBlocks(), llvm::ReachingDefAnalysis::hasSameReachingDef(), HasSameValue(), llvm::hasSingleElement(), llvm::HexagonInstrInfo::hasUncondBranch(), llvm::SelectionDAG::haveNoCommonBitsSet(), hoistAndMergeSGPRInits(), llvm::SimplifyCFGOptions::hoistCommonInsts(), llvm::rdf::NodeAllocator::id(), llvm::jitlink::BlockAddressMap::includeNonNull(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::mca::initializeUsedResources(), llvm::BitTracker::RegisterCell::insert(), llvm::HexagonFrameLowering::insertCFIInstructions(), llvm::LiveIntervals::InsertMachineInstrRangeInMaps(), insertSinCosCall(), llvm::HexagonBlockRanges::InstrIndexMap::InstrIndexMap(), intersect(), llvm::MDNode::intersect(), is_empty(), llvm::InstructionOrdering::isBefore(), IsBetterCanonical(), isClampZeroToOne(), llvm::IRSimilarity::isClose(), isCommutableVPERMV3Instruction(), llvm::isConsecutiveAccess(), isContiguous(), isContiguous(), llvm::SlotIndex::isEarlierEqualInstr(), llvm::SlotIndex::isEarlierInstr(), llvm::AMDGPUCallLowering::isEligibleForTailCallOptimization(), llvm::DenseMapInfo< DebugVariable >::isEqual(), llvm::DenseMapInfo< DIExpression::FragmentInfo >::isEqual(), llvm::DenseMapInfo< object::SectionRef >::isEqual(), llvm::DenseMapInfo< SlotWithTag >::isEqual(), llvm::DenseMapInfo< std::pair< const MCSymbol *, MCSymbolRefExpr::VariantKind > >::isEqual(), llvm::SelectionDAG::isEqualTo(), llvm::RecurrenceDescriptor::isFirstOrderRecurrence(), isHorizontalBinOp(), IsInterestingCmp(), llvm::LiveRangeCalc::isJointlyDominated(), llvm::isKnownNegation(), llvm::LoopVectorizationCostModel::isMoreProfitable(), llvm::isOverflowIntrinsicNoWrap(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::isPermutation(), isPointerBitcastEqualTo(), llvm::isPotentiallyReachable(), llvm::isPotentiallyReachable(), llvm::SlotIndex::isSameInstr(), llvm::IRSimilarity::IRSimilarityCandidate::isSimilar(), isSortedByValueNo(), llvm::AArch64_AM::isSVEMoveMaskPreferredLogicalImmediate(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolved(), llvm::MCObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::MachObjectWriter::isSymbolRefDifferenceFullyResolvedImpl(), llvm::AMDGPUMachineModuleInfo::isSyncScopeInclusion(), isTruePredicate(), lcm(), llvm::AMDGPULegalizerInfo::legalizeAddrSpaceCast(), llvm::AMDGPULegalizerInfo::legalizeAtomicCmpXChg(), llvm::AMDGPULegalizerInfo::legalizeAtomicIncDec(), llvm::AMDGPULegalizerInfo::legalizeBufferAtomic(), llvm::AMDGPULegalizerInfo::legalizeBufferLoad(), llvm::AMDGPULegalizerInfo::legalizeBufferStore(), llvm::AMDGPULegalizerInfo::legalizeBuildVector(), llvm::AMDGPULegalizerInfo::legalizeBVHIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeCustom(), llvm::AMDGPULegalizerInfo::legalizeDebugTrapIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeExtractVectorElt(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFastUnsafeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFceil(), llvm::AMDGPULegalizerInfo::legalizeFDIV(), llvm::AMDGPULegalizerInfo::legalizeFDIV16(), llvm::AMDGPULegalizerInfo::legalizeFDIV32(), llvm::AMDGPULegalizerInfo::legalizeFDIV64(), llvm::AMDGPULegalizerInfo::legalizeFDIVFastIntrin(), llvm::AMDGPULegalizerInfo::legalizeFExp(), llvm::AMDGPULegalizerInfo::legalizeFFloor(), llvm::AMDGPULegalizerInfo::legalizeFlog(), llvm::AMDGPULegalizerInfo::legalizeFMad(), llvm::AMDGPULegalizerInfo::legalizeFPow(), llvm::AMDGPULegalizerInfo::legalizeFPTOI(), llvm::AMDGPULegalizerInfo::legalizeFrem(), llvm::AMDGPULegalizerInfo::legalizeFrint(), llvm::AMDGPULegalizerInfo::legalizeGlobalValue(), llvm::AMDGPULegalizerInfo::legalizeImageIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeImplicitArgPtr(), llvm::AMDGPULegalizerInfo::legalizeInsertVectorElt(), llvm::AMDGPULegalizerInfo::legalizeIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeIntrinsicTrunc(), llvm::AMDGPULegalizerInfo::legalizeIsAddrSpace(), llvm::AMDGPULegalizerInfo::legalizeITOFP(), llvm::AMDGPULegalizerInfo::legalizeLoad(), llvm::AMDGPULegalizerInfo::legalizePreloadedArgIntrin(), llvm::AMDGPULegalizerInfo::legalizeRsqClampIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeSBufferLoad(), llvm::AMDGPULegalizerInfo::legalizeShuffleVector(), llvm::AMDGPULegalizerInfo::legalizeSignedDIV_REM(), llvm::AMDGPULegalizerInfo::legalizeSinCos(), llvm::AMDGPULegalizerInfo::legalizeTrapEndpgm(), llvm::AMDGPULegalizerInfo::legalizeTrapHsa(), llvm::AMDGPULegalizerInfo::legalizeTrapHsaQueuePtr(), llvm::AMDGPULegalizerInfo::legalizeTrapIntrinsic(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM32Impl(), llvm::AMDGPULegalizerInfo::legalizeUnsignedDIV_REM64Impl(), llvm::cfg::LegalizeUpdates(), llvm::HexagonInstr::lessCore(), llvm::HexagonInstr::lessCVI(), llvm::HexagonResource::lessUnits(), llvm::HexagonResource::lessWeight(), LLVMBuildAdd(), LLVMBuildAddrSpaceCast(), LLVMBuildAggregateRet(), LLVMBuildAlloca(), LLVMBuildAnd(), LLVMBuildArrayAlloca(), LLVMBuildArrayMalloc(), LLVMBuildAShr(), LLVMBuildAtomicCmpXchg(), LLVMBuildAtomicRMW(), LLVMBuildBinOp(), LLVMBuildBitCast(), LLVMBuildBr(), LLVMBuildCall(), LLVMBuildCall2(), LLVMBuildCast(), LLVMBuildCatchPad(), LLVMBuildCatchRet(), LLVMBuildCatchSwitch(), LLVMBuildCleanupPad(), LLVMBuildCleanupRet(), LLVMBuildCondBr(), LLVMBuildExactSDiv(), LLVMBuildExactUDiv(), LLVMBuildExtractElement(), LLVMBuildExtractValue(), LLVMBuildFAdd(), LLVMBuildFCmp(), LLVMBuildFDiv(), LLVMBuildFence(), LLVMBuildFMul(), LLVMBuildFNeg(), LLVMBuildFPCast(), LLVMBuildFPExt(), LLVMBuildFPToSI(), LLVMBuildFPToUI(), LLVMBuildFPTrunc(), LLVMBuildFree(), LLVMBuildFreeze(), LLVMBuildFRem(), LLVMBuildFSub(), LLVMBuildGEP(), LLVMBuildGEP2(), LLVMBuildGlobalString(), LLVMBuildGlobalStringPtr(), LLVMBuildICmp(), LLVMBuildInBoundsGEP(), LLVMBuildInBoundsGEP2(), LLVMBuildIndirectBr(), LLVMBuildInsertElement(), LLVMBuildInsertValue(), LLVMBuildIntCast(), LLVMBuildIntCast2(), LLVMBuildIntToPtr(), LLVMBuildInvoke(), LLVMBuildInvoke2(), LLVMBuildIsNotNull(), LLVMBuildIsNull(), LLVMBuildLandingPad(), LLVMBuildLoad(), LLVMBuildLoad2(), LLVMBuildLShr(), LLVMBuildMalloc(), LLVMBuildMemCpy(), LLVMBuildMemMove(), LLVMBuildMemSet(), LLVMBuildMul(), LLVMBuildNeg(), LLVMBuildNot(), LLVMBuildNSWAdd(), LLVMBuildNSWMul(), LLVMBuildNSWNeg(), LLVMBuildNSWSub(), LLVMBuildNUWAdd(), LLVMBuildNUWMul(), LLVMBuildNUWNeg(), LLVMBuildNUWSub(), LLVMBuildOr(), LLVMBuildPhi(), LLVMBuildPointerCast(), LLVMBuildPtrDiff(), LLVMBuildPtrToInt(), LLVMBuildResume(), LLVMBuildRet(), LLVMBuildRetVoid(), LLVMBuildSDiv(), LLVMBuildSelect(), LLVMBuildSExt(), LLVMBuildSExtOrBitCast(), LLVMBuildShl(), LLVMBuildShuffleVector(), LLVMBuildSIToFP(), LLVMBuildSRem(), LLVMBuildStore(), LLVMBuildStructGEP(), LLVMBuildStructGEP2(), LLVMBuildSub(), LLVMBuildSwitch(), LLVMBuildTrunc(), LLVMBuildTruncOrBitCast(), LLVMBuildUDiv(), LLVMBuildUIToFP(), LLVMBuildUnreachable(), LLVMBuildURem(), LLVMBuildVAArg(), LLVMBuildXor(), LLVMBuildZExt(), LLVMBuildZExtOrBitCast(), LLVMInitializeAMDGPUAsmParser(), LLVMInitializeARMAsmParser(), LLVMInitializeARMAsmPrinter(), LLVMInitializeARMTarget(), LLVMInitializeARMTargetInfo(), LLVMInitializeMipsAsmParser(), LLVMInitializeMipsAsmPrinter(), LLVMInitializeMipsTarget(), LLVMInitializeMipsTargetInfo(), LLVMInitializePowerPCAsmParser(), LLVMInitializePowerPCTarget(), LLVMInitializeSparcAsmParser(), LLVMSetNormalDest(), LLVMSetUnwindDest(), llvm::object::ResourceSectionRef::load(), llvm::orc::StaticLibraryDefinitionGenerator::Load(), llvm::AMDGPULegalizerInfo::loadInputValue(), llvm::AMDGPULegalizerInfo::loadInputValue(), llvm::ValueDFS_Compare::localComesBefore(), lookForCompound(), llvm::LegalizerHelper::lowerBitCount(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::AMDGPUCallLowering::lowerFormalArgumentsKernel(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::LegalizerHelper::lowerFPTRUNC_F64_TO_F16(), lowerLoadRelative(), LowerMUL(), LowerMULH(), LowerMULO(), llvm::AMDGPUCallLowering::lowerReturn(), LowervXi8MulWithUNPCK(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), maintainNoSignedWrap(), llvm::MachineFunction::makeDebugValueSubstitution(), llvm::makeGuardControlFlowExplicit(), llvm::jitlink::makeTargetOutOfRangeError(), AAHeapToStackFunction::manifest(), llvm::rdf::DataFlowGraph::markBlock(), MarkBlocksLiveIn(), matchAArch64MulConstCombine(), matchAccessTags(), llvm::CombinerHelper::matchBitfieldExtractFromAnd(), matchDeMorgansLaws(), matchesAdd(), matchesOr(), matchMinMaxOfMinMax(), llvm::CombinerHelper::matchOverlappingAnd(), llvm::CombinerHelper::matchReassocPtrAdd(), matchSelectWithOptionalNotCond(), matchUAddWithOverflowConstantEdgeCases(), llvm::maximum(), llvm::maxnum(), mayLoopAccessLocation(), memAccessesCanBeReordered(), memoryIsNotModifiedBetween(), llvm::AttrBuilder::merge(), merge(), MergeAliasResults(), llvm::DDGBuilder::mergeNodes(), MergeSeqs(), mergeVectorRegsToResultRegs(), llvm::MIBundleBuilder::MIBundleBuilder(), llvm::MinAlign(), llvm::minimum(), llvm::minnum(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::moveFromOldBuckets(), moveInstrOut(), llvm::ConstantRange::multiply(), llvm::detail::DoubleAPFloat::multiply(), llvm::LegalizerHelper::narrowScalarCTLZ(), llvm::LegalizerHelper::narrowScalarCTTZ(), narrowSDivOrSRem(), nearest_common_dominatee(), nearest_common_dominator(), llvm::SimplifyCFGOptions::needCanonicalLoops(), llvm::AttrBuilder::operator!=(), llvm::codeview::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), llvm::operator!=(), std::equal_to< llvm::rdf::RegisterAggr >::operator()(), llvm::ValueDFS_Compare::operator()(), llvm::jitlink::EHFrameSplitter::operator()(), llvm::jitlink::EHFrameEdgeFixer::operator()(), llvm::operator<(), llvm::codeview::operator<(), llvm::HexagonInstr::operator<(), llvm::opt::operator<(), llvm::operator<(), llvm::jitlink::operator<<(), llvm::rdf::operator<<(), llvm::codeview::operator<=(), llvm::AttrBuilder::operator==(), llvm::operator==(), llvm::codeview::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::operator==(), llvm::codeview::operator>(), llvm::codeview::operator>=(), llvm::rdf::Liveness::LiveMapType::operator[](), llvm::sys::fs::operator|(), llvm::sys::fs::operator|(), llvm::sys::fs::operator|=(), llvm::sys::fs::operator|=(), llvm::FeatureBitset::operator~(), optimizeBinaryDoubleFP(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), optimizeDoubleFP(), optimizeELF_x86_64_GOTAndStubs(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), optimizeMachO_x86_64_GOTAndStubs(), optimizeMemCmpConstantSize(), optimizeTrigReflections(), optimizeUnaryDoubleFP(), llvm::outliner::OutlinedFunction::OutlinedFunction(), llvm::IRSimilarity::IRSimilarityCandidate::overlap(), llvm::AttrBuilder::overlaps(), packImage16bitOpsToDwords(), parsePhysicalReg(), parseWholeProgramDevirtResolutionByArg(), llvm::parseWidenableBranch(), llvm::PeelingModuloScheduleExpander::peelPrologAndEpilogs(), PeepholePPC64ZExtGather(), llvm::AArch64TargetLowering::PerformDAGCombine(), PerformSETCCCombine(), PerformVECREDUCE_ADDCombine(), performVecReduceAddCombine(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), PickMostRelevantLoop(), llvm::CallBase::populateBundleOperandInfos(), llvm::HexagonInstrInfo::PredicateInstruction(), llvm::lowertypetests::BitSetInfo::print(), llvm::PhysicalRegisterUsageInfo::print(), llvm::jitlink::printEdge(), printName(), printName(), llvm::Pattern::printVariableDefs(), processAbsIntrinsic(), processOverflowIntrinsic(), processUDivOrURem(), processUGT_ADDCST_ADD(), processUMulZExtIdiom(), llvm::xray::Profile::Profile(), ProfileFoldOpInit(), llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates(), llvm::MachineDominatorTree::properlyDominates(), llvm::MachinePostDominatorTree::properlyDominates(), llvm::MachineDominatorTree::properlyDominates(), llvm::MachinePostDominatorTree::properlyDominates(), llvm::DominatorTreeBase< NodeT, IsPostDom >::properlyDominates(), llvm::jitlink::prune(), r0(), r1(), r2(), r3(), r4(), llvm::BitTracker::reached(), llvm::SymbolRemappingReader::read(), readGSIHashBuckets(), reinsertVectorIndexAdd(), llvm::objcarc::ProvenanceAnalysis::related(), llvm::rdf::DataFlowGraph::releaseBlock(), llvm::AttrBuilder::remove(), llvm::AttributeSet::removeAttribute(), llvm::AttributeSet::removeAttribute(), llvm::AttributeSet::removeAttributes(), llvm::Argument::removeAttrs(), llvm::jitlink::LinkGraph::removeBlock(), llvm::MemorySSAUpdater::removeDuplicatePhiEdgesBetween(), removeUseSoftFloat(), llvm::codegen::renderBoolStringAttr(), replaceUnaryCall(), llvm::rdf::Liveness::resetKills(), llvm::rdf::Liveness::resetKills(), llvm::rdf::Liveness::resetLiveIns(), rewrite(), llvm::SSAUpdaterBulk::RewriteAllUses(), llvm::GCNTTIImpl::rewriteIntrinsicWithAddressSpace(), llvm::APIntOps::RoundingSDiv(), llvm::APIntOps::RoundingUDiv(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::run(), llvm::BitTracker::run(), llvm::DomTreeBuilder::SemiNCAInfo< DomTreeT >::runDFS(), llvm::SpeculativeExecutionPass::runImpl(), llvm::RewriteStatepointsForGC::runOnFunction(), llvm::sampleprof::SampleSorter< LocationT, SampleT >::SampleSorter(), llvm::jitlink::SectionRange::SectionRange(), llvm::AMDGPURegisterBankInfo::selectStoreIntrinsic(), llvm::LoopVectorizationCostModel::selectVectorizationFactor(), llvm::FastMathFlags::setAllowContract(), llvm::FastMathFlags::setAllowReassoc(), llvm::FastMathFlags::setAllowReciprocal(), llvm::FastMathFlags::setApproxFunc(), llvm::pdb::BulkPublic::setBucketIdx(), setBufferOffsets(), llvm::pdb::DbiStreamBuilder::setBuildNumber(), llvm::InnerLoopVectorizer::setDebugLocFromInst(), llvm::CallBrInst::setDefaultDest(), llvm::msf::MSFBuilder::setDirectoryBlocksHint(), llvm::MachineFunction::setExposesReturnsTwice(), llvm::Instruction::setFast(), llvm::FastMathFlags::setFast(), llvm::SimplifyCFGOptions::setFoldTwoEntryPHINode(), llvm::DIE::setForceChildren(), llvm::codegen::setFunctionAttributes(), llvm::AVRMachineFunctionInfo::setHasAllocas(), llvm::Instruction::setHasAllowContract(), llvm::Instruction::setHasAllowReassoc(), llvm::Instruction::setHasAllowReciprocal(), llvm::Instruction::setHasApproxFunc(), llvm::MachineFrameInfo::setHasCopyImplyingStackAdjustment(), llvm::pdb::InfoStreamBuilder::setHashPDBContentsToGUID(), llvm::MachineFunction::setHasInlineAsm(), llvm::MachineFrameInfo::setHasMustTailInVarArgFunc(), llvm::Instruction::setHasNoInfs(), llvm::Instruction::setHasNoNaNs(), llvm::Instruction::setHasNoSignedZeros(), llvm::MachineFrameInfo::setHasOpaqueSPAdjustment(), llvm::AVRMachineFunctionInfo::setHasSpills(), llvm::AVRMachineFunctionInfo::setHasStackArgs(), llvm::MachineFrameInfo::setHasVAStart(), llvm::CallBrInst::setIndirectDest(), llvm::GetElementPtrInst::setIsInBounds(), llvm::SinkAndHoistLICMFlags::setIsSink(), llvm::FastMathFlags::setNoInfs(), llvm::FastMathFlags::setNoNaNs(), llvm::InvokeInst::setNormalDest(), llvm::FastMathFlags::setNoSignedZeros(), llvm::rdf::PhiUseNode::setPredecessor(), llvm::SimplifyCFGOptions::setSimplifyCondBranch(), llvm::InvokeInst::setUnwindDest(), llvm::setWidenableBranchCond(), llvm::TargetLoweringBase::shouldLocalize(), llvm::SignExtend32(), llvm::SignExtend32(), llvm::SignExtend64(), llvm::SignExtend64(), simplifyAndOfICmpsWithSameOperands(), SimplifyAssociativeBinOp(), llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative(), simplifyICmpWithBinOp(), simplifyICmpWithMinMax(), SimplifyOrInst(), simplifyOrOfICmpsWithSameOperands(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), simplifyUnsignedRangeCheck(), llvm::InstCombinerImpl::SimplifyUsingDistributiveLaws(), simplifyValueKnownNonZero(), simplifyWithOpReplaced(), llvm::SimplifyCFGOptions::sinkCommonInsts(), sinkInstruction(), sinkLoopInvariantInstructions(), sinkSpillUsesAfterCoroBegin(), llvm::APIntOps::smax(), llvm::APIntOps::smin(), llvm::ConstantRange::smul_sat(), SolveLinEquationWithOverflow(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), llvm::APIntOps::SolveQuadraticEquationWrap(), sortGlobalExprs(), llvm::DebugLocEntry::sortUniqueValues(), llvm::AMDGPURegisterBankInfo::split64BitValueForMapping(), llvm::jitlink::LinkGraph::splitBlock(), llvm::AMDGPURegisterBankInfo::splitBufferOffsets(), llvm::AMDGPULegalizerInfo::splitBufferOffsets(), llvm::stable_hash_combine(), llvm::stable_hash_combine(), llvm::stable_hash_combine(), llvm::opt::StrCmpOptionName(), llvm::opt::StrCmpOptionNameIgnoreCase(), SwapN(), toDebugS(), toggleSPDenormMode(), llvm::object::ELFFile< ELFT >::toMappedAddr(), llvm::jitlink::LinkGraph::transferBlock(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), llvm::InstCombinerImpl::tryFactorization(), TryToSinkInstruction(), llvm::APIntOps::umax(), llvm::APIntOps::umin(), unifyBitWidth(), llvm::MemoryPhi::unorderedDeleteIncomingBlock(), llvm::HexagonPacketizerList::unpacketizeSoloInstrs(), unpackV2S16ToS32(), llvm::UnrollRuntimeLoopRemainder(), unwrapBlock(), llvm::DWARFUnit::updateAddressDieMap(), llvm::MachineBasicBlock::updateTerminator(), llvm::UpgradeAttributes(), llvm::UpgradeIntrinsicCall(), upgradeMaskedMove(), llvm::json::Value::Value(), llvm::valueComesBefore(), llvm::AssumptionCacheTracker::verifyAnalysis(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), llvm::InstCombinerImpl::visitAdd(), llvm::InstCombinerImpl::visitAnd(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::SelectionDAGBuilder::visitBitTestHeader(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFDiv(), llvm::InstCombinerImpl::visitICmpInst(), visitMaskedMerge(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitUDiv(), llvm::InstCombinerImpl::visitXor(), llvm::InnerLoopVectorizer::widenInstruction(), llvm::widenWidenableBranch(), llvm::ScalarEvolution::willNotOverflow(), llvm::MemorySSAUpdater::wireOldPredecessorsToNewImmediatePredecessor(), llvm::TimeTraceProfiler::write(), llvm::sampleprof::SampleProfileWriter::writeFuncProfiles(), llvm::object::writeStringTable(), llvm::InstrProfWriter::writeText(), llvm::DwarfUnit::~DwarfUnit(), and llvm::jitlink::Section::~Section().
C
GCRegistry::Add< ShadowStackGC > C("shadow-stack", "Very portable GC for uncooperative code generators") ("shadow-stack" , "Very portable GC for uncooperative code generators") static
Referenced by false::Chain::add(), llvm::AttributeList::addAllocSizeAttr(), llvm::AttributeList::addAllocSizeParamAttr(), addAllTypesFromDWP(), addAllTypesFromTypesSection(), llvm::AttributeSet::addAttribute(), llvm::AttributeSet::addAttribute(), llvm::AttributeList::addAttribute(), llvm::AttributeList::addAttribute(), llvm::AttributeList::addAttribute(), llvm::AttributeSet::addAttributes(), llvm::AttributeList::addAttributes(), llvm::ModuleSummaryIndex::addBlockCount(), llvm::cl::Option::addCategory(), llvm::DomTreeNodeBase< NodeT >::addChild(), llvm::SchedDFSImpl::addConnection(), addConstantComments(), llvm::PBQPRAConstraintList::addConstraint(), llvm::AttributeList::addDereferenceableAttr(), llvm::AttributeList::addDereferenceableOrNullAttr(), llvm::AttributeList::addDereferenceableOrNullParamAttr(), llvm::AttributeList::addDereferenceableParamAttr(), llvm::ConstantPool::addEntry(), AddNodeIDCustom(), llvm::InstCombiner::AddOne(), llvm::AttributeList::addParamAttribute(), llvm::AttributeList::addParamAttribute(), llvm::AttributeList::addParamAttribute(), llvm::AttributeList::addParamAttributes(), addStackMapLiveVars(), llvm::DWARFUnitVector::addUnitsForDWOSection(), llvm::DWARFUnitVector::addUnitsForSection(), llvm::ConstraintSystem::addVariableRow(), llvm::AttributeList::addVScaleRangeAttr(), adjustForFNeg(), adjustForLTGFR(), adjustForRedundantAnd(), adjustForSubtraction(), adjustForTestUnderMask(), adjustICmpTruncate(), adjustSubwordCmp(), adjustZeroCmp(), allNonInstructionUsersCanBeMadeInstructions(), analyzeGlobalAux(), llvm::Annotations::Annotations(), llvm::orc::shared::TrivialSPSSequenceDeserialization< char, std::string >::append(), llvm::append_range(), appendFile(), appendToUsedList(), llvm::PBQPRAConstraintList::apply(), llvm::PBQP::applyR1(), llvm::PBQP::applyR2(), ApplyX86MaskOn1BitsVec(), llvm::object::Archive::Archive(), AAIsDeadValueImpl::areAllUsesAssumedDead(), llvm::DiagnosticInfoOptimizationBase::Argument::Argument(), llvm::json::Array::Array(), AAValueSimplifyImpl::askSimplifiedValueFor(), llvm::TaskQueue::async(), llvm::lto::backend(), llvm::yaml::begin(), llvm::BinaryStreamError::BinaryStreamError(), llvm::SparcTargetLowering::bitcastConstantFPToInt(), BitCastConstantVector(), llvm::SwitchCG::CaseCluster::bitTests(), BrPHIToSelect(), BuildConstantFromSCEV(), llvm::MachineIRBuilder::buildConstDbgValue(), BuildExactSDIV(), buildFrameType(), llvm::PassBuilder::buildFunctionSimplificationPipeline(), llvm::PassBuilder::buildInlinerPipeline(), llvm::PassBuilder::buildModuleOptimizationPipeline(), llvm::PassBuilder::buildModuleSimplificationPipeline(), llvm::PassBuilder::buildO0DefaultPipeline(), llvm::PassBuilder::buildPerModuleDefaultPipeline(), llvm::TargetLowering::BuildSDIV(), llvm::PassBuilder::buildThinLTOPreLinkDefaultPipeline(), llvm::TargetLowering::BuildUDIV(), llvm::object_creator< C >::call(), canBeUnquotedInDirective(), canBeUnquotedInDirective(), canCreateUndefOrPoison(), llvm::canIfConvertPHINodes(), canNarrowShiftAmt(), cannotBeOrderedLessThanZeroImpl(), canonicalizeBitSelect(), llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(), canonicalizeMetadataForValue(), canonicalizeSaturatedAdd(), canonicalizeSaturatedSubtract(), canRenameComdat(), llvm::canReplacePointersIfEqual(), canScalarizeAccess(), canSinkInstructions(), canTrapImpl(), llvm::caseFoldingDjbHash(), cheapToScalarize(), CheckAndImm(), checkBoolTestSetCCCombine(), llvm::checkedMulAdd(), llvm::checkedMulAddUnsigned(), CheckInteger(), checkMachOComdat(), CheckOrImm(), llvm::object::Archive::child_begin(), chopOneUTF32(), llvm::BitTracker::RegisterCell::cl(), llvm::ManagedStatic< C, Creator, Deleter >::claim(), llvm::WasmYAML::DylinkSection::classof(), llvm::WasmYAML::NameSection::classof(), llvm::WasmYAML::LinkingSection::classof(), llvm::WasmYAML::ProducersSection::classof(), llvm::WasmYAML::TargetFeaturesSection::classof(), CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), llvm::CloneModule(), cmpExcludesZero(), llvm::VNCoercion::coerceAvailableValueToLoadTypeHelper(), CollectAddOperandsWithScales(), collectBitParts(), collectComdatMembers(), collectContributionData(), collectInsertionElements(), collectRegionsConstants(), CollectSubexprs(), combineBitcast(), combineFAndFNotToFAndn(), combineFMA(), combineMul(), combineORToSHFL(), combineScalarToVector(), combineSelect(), combineSub(), combineTargetShuffle(), llvm::InstCombinerImpl::commonShiftTransforms(), CompactSwizzlableVector(), computeAlignmentAfterScalarization(), llvm::computeConstantRange(), computeKnownBits(), llvm::SelectionDAG::computeKnownBits(), llvm::RISCVTargetLowering::computeKnownBitsForTargetNode(), computeKnownBitsFromAssume(), computeKnownBitsFromOperator(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::computeOverflowForUnsignedSub(), llvm::RegisterClassInfo::computePSetLimit(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType(), llvm::ConstantFoldBinaryOpOperands(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCastOperand(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldConstant(), llvm::ConstantFoldExtractValueInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldInsertValueInstruction(), llvm::ConstantFoldInstruction(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldLoadThroughBitcast(), llvm::ConstantFoldLoadThroughGEPConstantExpr(), llvm::ConstantFoldLoadThroughGEPIndices(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFoldUnaryInstruction(), constantFoldUser(), ConstHasGlobalValuePredicate(), StringView::consumeFront(), AbstractManglingParser< Derived, Alloc >::consumeIf(), llvm::StringRef::contains(), contains(), llvm::sys::UnicodeCharSet::contains(), contains(), llvm::StringRef::contains_insensitive(), containsOnlyConstantData(), llvm::Constant::containsPoisonElement(), containsUndefinedElement(), llvm::Constant::containsUndefOrPoisonElement(), convertAnnotation2Metadata(), convertShiftLeftToScale(), llvm::SmallString< InternalLen >::count(), llvm::StringRef::count(), llvm::ARMConstantPoolConstant::Create(), llvm::ARMConstantPoolConstant::Create(), llvm::ARMConstantPoolConstant::Create(), llvm::sampleprof::SampleProfileReader::create(), llvm::sampleprof::SampleProfileReaderItaniumRemapper::create(), llvm::ReturnInst::Create(), llvm::ARMConstantPoolMBB::Create(), llvm::ARMConstantPoolSymbol::Create(), llvm::ReturnInst::Create(), llvm::ReturnInst::Create(), llvm::sampleprof::SampleProfileReader::create(), llvm::sampleprof::SampleProfileReaderItaniumRemapper::create(), llvm::GetElementPtrConstantExpr::Create(), llvm::SelectInst::Create(), llvm::SelectInst::Create(), llvm::TargetFolder::CreateBitCast(), llvm::ConstantFolder::CreateBitCast(), llvm::NoFolder::CreateBitCast(), llvm::TargetFolder::CreateCast(), llvm::ConstantFolder::CreateCast(), llvm::NoFolder::CreateCast(), llvm::MDBuilder::createConstant(), llvm::IRBuilderBase::CreateConstrainedFPBinOp(), llvm::IRBuilderBase::CreateConstrainedFPCall(), llvm::IRBuilderBase::CreateConstrainedFPCast(), llvm::IRBuilderBase::CreateConstrainedFPCmp(), createConvergingSched(), createDevirtTriggerFunc(), llvm::TargetFolder::CreateFNeg(), llvm::ConstantFolder::CreateFNeg(), llvm::NoFolder::CreateFNeg(), llvm::TargetFolder::CreateFPCast(), llvm::ConstantFolder::CreateFPCast(), llvm::NoFolder::CreateFPCast(), llvm::CastInst::CreateFPCast(), llvm::CastInst::CreateFPCast(), createFrameHelperMachineFunction(), createGCNMaxOccupancyMachineScheduler(), llvm::createGenericSchedLive(), llvm::createGenericSchedPostRA(), llvm::TargetFolder::CreateGetElementPtr(), llvm::ConstantFolder::CreateGetElementPtr(), llvm::NoFolder::CreateGetElementPtr(), llvm::TargetFolder::CreateGetElementPtr(), llvm::ConstantFolder::CreateGetElementPtr(), llvm::NoFolder::CreateGetElementPtr(), llvm::TargetFolder::CreateGetElementPtr(), llvm::ConstantFolder::CreateGetElementPtr(), llvm::NoFolder::CreateGetElementPtr(), createILPMaxScheduler(), createILPMinScheduler(), createImportedModule(), llvm::TargetFolder::CreateInBoundsGetElementPtr(), llvm::ConstantFolder::CreateInBoundsGetElementPtr(), llvm::NoFolder::CreateInBoundsGetElementPtr(), llvm::TargetFolder::CreateInBoundsGetElementPtr(), llvm::ConstantFolder::CreateInBoundsGetElementPtr(), llvm::NoFolder::CreateInBoundsGetElementPtr(), llvm::TargetFolder::CreateInBoundsGetElementPtr(), llvm::ConstantFolder::CreateInBoundsGetElementPtr(), llvm::NoFolder::CreateInBoundsGetElementPtr(), createInstructionShuffler(), llvm::TargetFolder::CreateIntCast(), llvm::ConstantFolder::CreateIntCast(), llvm::NoFolder::CreateIntCast(), llvm::CastInst::CreateIntegerCast(), llvm::CastInst::CreateIntegerCast(), llvm::TargetFolder::CreateIntToPtr(), llvm::ConstantFolder::CreateIntToPtr(), llvm::NoFolder::CreateIntToPtr(), createIterativeGCNMaxOccupancyMachineScheduler(), createIterativeILPMachineScheduler(), llvm::jitlink::createLookupContinuation(), llvm::createMCAsmParser(), llvm::createMCMasmParser(), createMinRegScheduler(), llvm::TargetFolder::CreateNeg(), llvm::ConstantFolder::CreateNeg(), llvm::NoFolder::CreateNeg(), llvm::TargetFolder::CreateNot(), llvm::ConstantFolder::CreateNot(), llvm::NoFolder::CreateNot(), llvm::BinaryOperator::CreateNot(), llvm::createPGOFuncNameMetadata(), llvm::TargetFolder::CreatePointerBitCastOrAddrSpaceCast(), llvm::ConstantFolder::CreatePointerBitCastOrAddrSpaceCast(), llvm::NoFolder::CreatePointerBitCastOrAddrSpaceCast(), llvm::TargetFolder::CreatePointerCast(), llvm::ConstantFolder::CreatePointerCast(), llvm::NoFolder::CreatePointerCast(), createPPCMachineScheduler(), createPPCPostMachineScheduler(), llvm::TargetFolder::CreatePtrToInt(), llvm::ConstantFolder::CreatePtrToInt(), llvm::NoFolder::CreatePtrToInt(), createR600MachineScheduler(), createResumeEntryBlock(), llvm::createRISCVELFStreamer(), llvm::TargetFolder::CreateSelect(), llvm::ConstantFolder::CreateSelect(), llvm::NoFolder::CreateSelect(), llvm::IRBuilderBase::CreateSelect(), llvm::TargetFolder::CreateSExtOrBitCast(), llvm::ConstantFolder::CreateSExtOrBitCast(), llvm::NoFolder::CreateSExtOrBitCast(), createSIMachineScheduler(), llvm::TargetFolder::CreateTruncOrBitCast(), llvm::ConstantFolder::CreateTruncOrBitCast(), llvm::NoFolder::CreateTruncOrBitCast(), llvm::TargetFolder::CreateUnOp(), llvm::ConstantFolder::CreateUnOp(), llvm::NoFolder::CreateUnOp(), createVLIWMachineSched(), llvm::createX86WinCOFFStreamer(), llvm::TargetFolder::CreateZExtOrBitCast(), llvm::ConstantFolder::CreateZExtOrBitCast(), llvm::NoFolder::CreateZExtOrBitCast(), llvm::BitTracker::RegisterCell::ct(), llvm::AMDGPUDisassembler::decodeKernelDescriptor(), decodeMultiByteChar(), llvm::DecodePSHUFBMask(), llvm::DecodeVPERMIL2PMask(), llvm::DecodeVPERMILPMask(), llvm::DecodeVPPERMMask(), llvm::decomposeBitTestICmp(), llvm::PPCTargetLowering::decomposeMulByConstant(), llvm::RISCVTargetLowering::decomposeMulByConstant(), llvm::X86TargetLowering::decomposeMulByConstant(), llvm::deleteConstant(), deleteIfDead(), llvm::orc::shared::SerializationTraits< ChannelT, bool, bool, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::deserialize(), llvm::orc::shared::SequenceSerialization< ChannelT, ArgT >::deserialize(), llvm::orc::shared::SequenceSerialization< ChannelT, ArgT, ArgTs... >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::map< K, V >, DenseMap< K2, V2 > >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, Error >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, Expected< T1 >, Expected< T2 > >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, JITSymbolFlags >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, Optional< T > >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ExecutorProcessInfo >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReleaseOrFinalizeMemRequestElement >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReserveMemRequestElement >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReserveMemResultElement >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::map< K, V >, std::map< K2, V2 > >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::pair< T1, T2 >, std::pair< T3, T4 > >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::set< T >, std::set< T2 > >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::tuple< ArgTs... > >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::vector< T > >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, T, T, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value &&(std::is_same< T, uint8_t >::value||std::is_same< T, int8_t >::value||std::is_same< T, uint16_t >::value||std::is_same< T, int16_t >::value||std::is_same< T, uint32_t >::value||std::is_same< T, int32_t >::value||std::is_same< T, uint64_t >::value||std::is_same< T, int64_t >::value||std::is_same< T, char >::value)> >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, tpctypes::BufferWrite, tpctypes::BufferWrite, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, WrapperFunctionResult, WrapperFunctionResult, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, WriteT, WriteT, std::enable_if_t< std::is_same< WriteT, tpctypes::UInt8Write >::value||std::is_same< WriteT, tpctypes::UInt16Write >::value||std::is_same< WriteT, tpctypes::UInt32Write >::value||std::is_same< WriteT, tpctypes::UInt64Write >::value > >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::string, std::string, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::deserialize(), llvm::orc::shared::detail::HandlerTraits< RetT(ArgTs...)>::deserializeArgs(), llvm::orc::shared::deserializeSeq(), detectAVGPattern(), detectSSatPattern(), llvm::DWARFUnit::determineStringOffsetsTableContributionDWO(), llvm::ModuleSummaryIndex::discoverNodes(), llvm::djbHash(), doList(), dominatesMergePoint(), llvm::LLVMContextImpl::dropTriviallyDeadConstantArrays(), llvm::coverage::CounterMappingContext::dump(), llvm::coverage::CounterMappingContext::dump(), llvm::dumpAmdKernelCode(), dumpArrayType(), dumpTypeName(), dumpWithNames(), llvm::BitTracker::MachineEvaluator::eCLB(), llvm::BitTracker::MachineEvaluator::eCTB(), eliminateConstraints(), emitByte(), llvm::MipsMCCodeEmitter::EmitByte(), llvm::TargetLoweringObjectFile::emitCGProfileMetadata(), llvm::StringToOffsetTable::EmitCharArray(), EmitCMP(), emitCmp(), llvm::AsmPrinter::emitConstantPool(), emitInlineAsm(), llvm::AMDGPUAsmPrinter::emitInstruction(), llvm::R600AsmPrinter::emitInstruction(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::TargetLoweringObjectFileELF::emitModuleMetadata(), llvm::TargetLoweringObjectFileCOFF::emitModuleMetadata(), llvm::MCTargetStreamer::emitRawBytes(), GeneratedRTChecks::emitSCEVChecks(), llvm::emitStrChr(), emitThumb1LoadConstPool(), emitThumb2LoadConstPool(), EmitX86ScalarSelect(), EmitX86Select(), llvm::BitCodeAbbrevOp::EncodeChar6(), encodeComponent(), encodeCounter(), llvm::DILocation::encodeDiscriminator(), encodingBits(), ensurePromotedGV(), llvm::DataExtractor::eof(), llvm::erase_if(), llvm::erase_value(), llvm::coverage::CounterMappingContext::evaluate(), EvaluateConstantChrecAtConstant(), EvaluateExpression(), evaluateInDifferentElementOrder(), llvm::InstCombinerImpl::EvaluateInDifferentType(), expand(), llvm::TargetLowering::expandMULO(), llvm::DWARFDebugNames::Header::extract(), llvm::DWARFDebugPubTable::extract(), llvm::RangeListEntry::extract(), ExtractConstantBytes(), llvm::extractConstantMask(), extractConstantWithoutWrapping(), ExtractImmediate(), factorizeFAddFSub(), FactorOutConstant(), fastCaseFoldingDjbHash(), llvm::AMDGPU::fillValidArchListAMDGCN(), llvm::AMDGPU::fillValidArchListR600(), llvm::RISCV::fillValidCPUArchList(), llvm::RISCV::fillValidTuneCPUArchList(), llvm::filterDeadComdatFunctions(), llvm::PPCInstrInfo::finalizeInsInstrs(), llvm::SmallString< InternalLen >::find(), llvm::StringRef::find(), StringView::find(), llvm::LazyCallGraph::RefSCC::find(), llvm::SmallString< InternalLen >::find_first_not_of(), llvm::StringRef::find_first_not_of(), llvm::SmallString< InternalLen >::find_first_of(), llvm::StringRef::find_first_of(), llvm::StringRef::find_insensitive(), llvm::StringRef::find_last_not_of(), llvm::StringRef::find_last_of(), llvm::SmallString< InternalLen >::find_last_of(), findBaseObject(), llvm::SwitchCG::SwitchLowering::findBitTestClusters(), llvm::SwitchInst::findCaseValue(), llvm::SwitchInst::findCaseValue(), findConstants(), findExtractedInputToOverallInputMapping(), findExtractedOutputToOverallOutputMapping(), findFuncPointers(), llvm::FindInsertedValue(), llvm::SwitchCG::SwitchLowering::findJumpTables(), findPartitions(), llvm::findScalarElement(), findUses(), fixupFPReturnAndCall(), foldAddSubBoolOfMaskedVal(), llvm::InstCombinerImpl::foldAddWithConstant(), foldAndOrOfICmpsWithConstEq(), foldBitCastBitwiseLogic(), foldCharDwarf(), llvm::sys::unicode::foldCharSimple(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), foldConstant(), foldCttzCtlz(), foldFCmpReciprocalAndZero(), foldFDivConstantDividend(), foldFDivConstantDivisor(), foldFNegIntoConstant(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpAddOpConst(), llvm::InstCombinerImpl::foldICmpAndConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), foldICmpBitCast(), llvm::InstCombinerImpl::foldICmpDivConstant(), llvm::InstCombinerImpl::foldICmpEqIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpEquality(), llvm::InstCombinerImpl::foldICmpInstWithConstant(), llvm::InstCombinerImpl::foldICmpInstWithConstantNotInt(), llvm::InstCombinerImpl::foldICmpIntrinsicWithConstant(), llvm::InstCombinerImpl::foldICmpMulConstant(), llvm::InstCombinerImpl::foldICmpOrConstant(), llvm::InstCombinerImpl::foldICmpSelectConstant(), llvm::InstCombinerImpl::foldICmpShlConstant(), foldICmpShlOne(), llvm::InstCombinerImpl::foldICmpShrConstant(), llvm::InstCombinerImpl::foldICmpSRemConstant(), llvm::InstCombinerImpl::foldICmpSubConstant(), llvm::InstCombinerImpl::foldICmpTruncConstant(), llvm::InstCombinerImpl::foldICmpUDivConstant(), llvm::InstCombinerImpl::foldICmpWithConstant(), llvm::InstCombinerImpl::foldICmpWithDominatingICmp(), foldICmpWithZextOrSext(), llvm::InstCombinerImpl::foldICmpXorConstant(), foldLogicCastConstant(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), llvm::X86InstrInfo::foldMemoryOperandImpl(), foldOperationIntoPhiValue(), llvm::InstCombinerImpl::foldOpIntoPhi(), llvm::InstCombinerImpl::FoldOpIntoSelect(), llvm::InstCombinerImpl::foldPHIArgZextsIntoPHI(), foldSelectBinOpIdentity(), foldSelectICmpAnd(), llvm::InstCombinerImpl::foldSelectIntoOp(), foldSelectShuffleWith1Binop(), foldSetClearBits(), llvm::InstCombinerImpl::FoldShiftByConstant(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), llvm::InstCombinerImpl::foldSignBitTest(), foldToUnsignedSaturatedAdd(), llvm::InstCombinerImpl::foldVariableSignZeroExtensionOfVariableHighBitExtract(), llvm::InstCombinerImpl::foldVectorBinop(), foldVectorCmp(), llvm::ImmutableSet< ValT, ValInfo >::foreach(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::foreach(), llvm::ImutAVLTree< ImutInfo >::foreach(), llvm::ImmutableSet< ValT, ValInfo >::foreach(), genConstMult(), genericValueTraversal(), llvm::ConstantVector::get(), llvm::ConstantArray::get(), llvm::ValueLatticeElement::get(), llvm::ConstantAsMetadata::get(), llvm::AttributeSet::get(), llvm::AttributeSetNode::get(), llvm::AttributeList::get(), llvm::AttributeList::get(), llvm::AttributeList::get(), llvm::AttributeList::get(), llvm::AttributeSet::get(), llvm::AttributeSetNode::get(), llvm::PointerType::get(), llvm::AttributeList::get(), llvm::AttributeList::get(), llvm::AttributeList::get(), llvm::AttributeList::get(), llvm::IntegerType::get(), llvm::ConstantFP::get(), llvm::ConstantInt::get(), llvm::ConstantFP::get(), llvm::ConstantFP::get(), llvm::ConstantInt::get(), llvm::ConstantExpr::get(), llvm::ValueAsMetadata::get(), getAArch64Cmp(), llvm::ScalarEvolution::getAddExpr(), llvm::DataExtractor::getAddress(), getAddrSizeInt(), llvm::ConstantExpr::getAddrSpaceCast(), llvm::TargetRegisterInfo::getAllocatableSet(), llvm::AllocaInst::getAllocationSizeInBits(), getAlternateBinop(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), getArrayElements(), llvm::SITargetLowering::getAsmOperandConstVal(), llvm::AAValueConstantRange::getAssumedConstantInt(), getAvailableLoadStore(), getAVX2GatherNode(), llvm::Type::getBFloatPtrTy(), llvm::Type::getBFloatTy(), getBinOpsForFactorization(), llvm::ConstantExpr::getBitCast(), llvm::DataExtractor::getBytes(), GetCaseResults(), llvm::ConstantExpr::getCast(), llvm::BitTracker::MachineEvaluator::getCell(), getCmp(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), getCodeExtractorArguments(), llvm::PBQP::Matrix::getColAsVector(), getComdatGVForCOFF(), llvm::ValueEnumerator::getComdatID(), llvm::irsymtab::Reader::getComdatTable(), llvm::ValueAsMetadata::getConstant(), getConstantAt(), llvm::SelectionDAG::getConstantDbgValue(), llvm::BitcodeReaderValueList::getConstantFwdRef(), llvm::ValueAsMetadata::getConstantIfExists(), getConstantOrNull(), getConstantPermuteMask(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::MachineConstantPool::getConstantPoolIndex(), llvm::ExecutionEngine::getConstantValue(), getConstantVector(), llvm::AsmPrinter::GetCPISymbol(), llvm::DataExtractor::getCStr(), llvm::DataExtractor::getCStrRef(), getDefaultPersonalityFn(), llvm::Type::getDoublePtrTy(), llvm::Type::getDoubleTy(), getEdgeKind(), llvm::ConstantAggregateZero::getElementValue(), llvm::UndefValue::getElementValue(), llvm::PoisonValue::getElementValue(), getELFComdat(), getEncodedComdatSelectionKind(), llvm::DataExtractor::getError(), llvm::ConstantExpr::getExactLogBase2(), getExactSDiv(), llvm::TargetLoweringObjectFileWasm::getExplicitSectionGlobal(), llvm::InstCombiner::getFlippedStrictnessPredicateAndConstant(), llvm::Type::getFloatingPointTy(), llvm::Type::getFloatPtrTy(), llvm::Type::getFloatTy(), llvm::ConstantExpr::getFNeg(), getFoldedCast(), llvm::MemoryLocation::getForDest(), llvm::Clause::getFormattedParserClassName(), llvm::MemoryLocation::getForSource(), llvm::Type::getFP128PtrTy(), llvm::Type::getFP128Ty(), llvm::ConstantExpr::getFPCast(), llvm::ConstantExpr::getFPExtend(), getFPSequenceIfElementsMatch(), getFPTernOp(), llvm::ConstantExpr::getFPToSI(), llvm::ConstantExpr::getFPToUI(), llvm::ConstantExpr::getFPTrunc(), getFunction(), llvm::AMDGPUMangledLibFunc::getFunctionType(), getGatherNode(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getGetElementPtr(), llvm::Type::getHalfPtrTy(), llvm::Type::getHalfTy(), llvm::ConstantAsMetadata::getIfExists(), llvm::ConstantExpr::getInBoundsGetElementPtr(), llvm::ConstantExpr::getInBoundsGetElementPtr(), llvm::ConstantExpr::getInBoundsGetElementPtr(), llvm::ConstantFP::getInfinity(), getInitializer(), llvm::DWARFDataExtractor::getInitialLength(), llvm::DWARFDataExtractor::getInitialLength(), llvm::Type::getInt128Ty(), llvm::IRBuilderBase::getInt16(), llvm::Type::getInt16PtrTy(), llvm::Type::getInt16Ty(), llvm::Type::getInt1PtrTy(), llvm::Type::getInt1Ty(), llvm::IRBuilderBase::getInt32(), llvm::Type::getInt32PtrTy(), llvm::Type::getInt32Ty(), llvm::IRBuilderBase::getInt64(), llvm::Type::getInt64PtrTy(), llvm::Type::getInt64Ty(), llvm::IRBuilderBase::getInt8(), llvm::Type::getInt8PtrTy(), llvm::Type::getInt8Ty(), llvm::ConstantExpr::getIntegerCast(), llvm::Constant::getIntegerValue(), llvm::IRBuilderBase::getIntN(), llvm::Type::getIntNPtrTy(), llvm::Type::getIntNTy(), llvm::DataLayout::getIntPtrType(), getIntrinsicCmp(), getIntrinsicParamType(), getIntSequenceIfElementsMatch(), llvm::ConstantExpr::getIntToPtr(), llvm::TargetLoweringBase::getIRStackGuard(), llvm::TargetLoweringObjectFile::getKindForGlobal(), getKnownUndefForVectorBinop(), llvm::Type::getLabelTy(), llvm::DataLayout::getLargestLegalIntType(), getMaskedICmpType(), getMaskedTypeForICmpPair(), llvm::coverage::CounterMappingContext::getMaxCounterID(), llvm::sampleprof::FunctionSamples::getMaxCountInside(), getMDNodeOperandImpl(), llvm::object::Archive::Symbol::getMember(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemSetPatternValue(), getMemsetValue(), llvm::Type::getMetadataTy(), getMinFromExprs(), llvm::XCOFF::getNameForTracebackTableLanguageId(), llvm::ConstantFP::getNaN(), llvm::ConstantExpr::getNeg(), llvm::TargetLowering::getNegatedExpression(), getNegatibleInsts(), llvm::ConstantFP::getNegativeZero(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::ValueLatticeElement::getNot(), llvm::ConstantExpr::getNot(), getNotValue(), llvm::ConstantExpr::getNSWNeg(), getNumGlobalVariableUses(), llvm::ARMTTIImpl::getNumMemOps(), llvm::ConstantExpr::getNUWNeg(), llvm::AArch64CC::getNZCVToSatisfyCondCode(), llvm::DataExtractor::getOffset(), llvm::getOrCreateFunctionComdat(), llvm::OpenMPIRBuilder::getOrCreateRuntimeFunction(), llvm::AMDGPULibFunc::getOrInsertFunction(), llvm::ARMBaseInstrInfo::getOutliningCandidateInfo(), llvm::RISCVInstrInfo::getOutliningCandidateInfo(), llvm::X86InstrInfo::getOutliningCandidateInfo(), llvm::outliner::OutlinedFunction::getOutliningCost(), llvm::StackSafetyInfo::getParamAccesses(), getPermuteMask(), llvm::getPointerAtOffset(), getPowerOf2Factor(), llvm::Type::getPPC_FP128PtrTy(), llvm::Type::getPPC_FP128Ty(), llvm::LazyValueInfo::getPredicateAt(), llvm::LazyValueInfo::getPredicateAt(), llvm::LazyValueInfo::getPredicateOnEdge(), getPredicateResult(), getPrefetchNode(), llvm::Type::getPrimitiveType(), llvm::getPtrStride(), llvm::ConstantExpr::getPtrToInt(), llvm::ConstantFP::getQNaN(), GetQuadraticEquation(), llvm::DWARFDataExtractor::getRelocatedAddress(), llvm::DWARFDataExtractor::getRelocatedValue(), llvm::objcarc::getreturnRVOperand(), llvm::PBQP::Matrix::getRowAsVector(), llvm::InstCombiner::getSafeVectorConstantForBinop(), llvm::Type::getScalarTy(), getScatterNode(), llvm::ScalarEvolution::getSCEVAtScope(), llvm::TargetLoweringObjectFileCOFF::getSectionForConstant(), llvm::LanaiTargetObjectFile::getSectionForConstant(), llvm::MipsTargetObjectFile::getSectionForConstant(), llvm::RISCVELFTargetObjectFile::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileCOFF::getSectionForJumpTable(), llvm::TargetLoweringObjectFileELF::getSectionForLSDA(), llvm::ELFYAML::Object::getSectionHeaderTable(), llvm::ConstantExpr::getSelect(), getSelectionForCOFF(), getSequenceIfElementsMatch(), llvm::HexagonTargetLowering::getSetCCResultType(), llvm::AArch64TargetLowering::getSetCCResultType(), llvm::ConstantExpr::getSExt(), llvm::ConstantExpr::getSExtOrBitCast(), getShiftedValue(), llvm::ShuffleVectorInst::getShuffleMask(), getSignedIntOrFpConstant(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::AVRTargetLowering::getSingleConstraintMatchWeight(), llvm::SparcTargetLowering::getSingleConstraintMatchWeight(), llvm::SystemZTargetLowering::getSingleConstraintMatchWeight(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::ConstantExpr::getSIToFP(), llvm::DataExtractor::getSLEB128(), llvm::DataLayout::getSmallestLegalIntType(), llvm::ConstantFP::getSNaN(), getSplatConstantFP(), llvm::getSplatValue(), llvm::getStrideFromPointer(), getStringEncoding(), llvm::sys::getSwappedBytes(), llvm::sys::getSwappedBytes(), llvm::sys::getSwappedBytes(), llvm::sys::getSwappedBytes(), llvm::sys::getSwappedBytes(), llvm::sys::getSwappedBytes(), llvm::sys::getSwappedBytes(), llvm::sys::getSwappedBytes(), llvm::sys::getSwappedBytes(), llvm::getSwappedBytes(), llvm::sys::getSwappedBytes(), llvm::sys::getSwappedBytes(), llvm::sys::getSwappedBytes(), llvm::sys::getSwappedBytes(), llvm::sys::getSwappedBytes(), llvm::MachObjectWriter::getSymbolAddress(), getTargetConstantBitsFromNode(), llvm::SelectionDAG::getTargetConstantPool(), llvm::SelectionDAG::getTargetConstantPool(), getTargetVShiftByConstNode(), getTestBitOperand(), getTestBitReg(), llvm::Type::getTokenTy(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::ConstantExpr::getTrunc(), llvm::ConstantExpr::getTruncOrBitCast(), llvm::StructType::getTypeByName(), getTypeForLLT(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU24(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU64(), llvm::DataExtractor::getU8(), llvm::DataExtractor::getU8(), llvm::DataExtractor::getU8(), llvm::ConstantExpr::getUIToFP(), llvm::DataExtractor::getULEB128(), getUniformBase(), llvm::Constant::getUniqueInteger(), llvm::PointerType::getUnqual(), llvm::DataExtractor::getUnsigned(), getValueFromICmpCondition(), getValueFromOverflowCondition(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::SelectionDAG::getVectorShuffle(), llvm::object::MachOObjectFile::getVersionMinMajor(), llvm::object::MachOObjectFile::getVersionMinMinor(), llvm::object::MachOObjectFile::getVersionMinUpdate(), llvm::Type::getVoidTy(), getWasmComdat(), llvm::AA::getWithType(), llvm::Type::getX86_AMXPtrTy(), llvm::Type::getX86_AMXTy(), llvm::Type::getX86_FP80PtrTy(), llvm::Type::getX86_FP80Ty(), llvm::Type::getX86_MMXPtrTy(), llvm::Type::getX86_MMXTy(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::ConstantExpr::getZExt(), llvm::ConstantExpr::getZExtOrBitCast(), llvm::TextChangeReporter< std::string >::handleFiltered(), AAValueSimplifyImpl::handleLoad(), handleNonPrevailingComdat(), llvm::ValueAsMetadata::handleRAUW(), llvm::orc::shared::detail::ResponseHandlerImpl< ChannelT, FuncRetT, HandlerT >::handleResponse(), llvm::orc::shared::detail::ResponseHandlerImpl< ChannelT, void, HandlerT >::handleResponse(), llvm::orc::shared::detail::ResponseHandlerImpl< ChannelT, Expected< FuncRetT >, HandlerT >::handleResponse(), llvm::orc::shared::detail::ResponseHandlerImpl< ChannelT, Error, HandlerT >::handleResponse(), llvm::GEPOperator::hasAllZeroIndices(), llvm::object::hashSysV(), hasInvalidBitcodeHeader(), llvm::hasNItems(), llvm::hasNItemsOrLess(), llvm::hasNItemsOrMore(), llvm::Attribute::hasParentContext(), llvm::AttributeSet::hasParentContext(), llvm::AttributeList::hasParentContext(), llvm::hasSingleElement(), hoistAndMergeSGPRInits(), llvm::hoistRegion(), identifyAliveSuccessors(), identifyAliveSuccessors(), incorporateNewSCCRange(), llvm::StructType::indexValid(), llvm::SwitchInstProfUpdateWrapper::init(), initAndLookupTarget(), llvm::MipsMCInstLower::Initialize(), llvm::XCoreMCInstLower::Initialize(), INITIALIZE_PASS(), initializeCounts(), llvm::MCRegisterInfo::InitMCRegisterInfo(), llvm::IRBuilderBase::Insert(), insertBoundsCheck(), insertCall(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), llvm::AArch64InstrInfo::insertOutlinedCall(), llvm::ARMBaseInstrInfo::insertOutlinedCall(), llvm::X86InstrInfo::insertOutlinedCall(), insertSpills(), llvm::ExecutionEngine::InstallLazyFunctionCreator(), llvm::GCNTTIImpl::instCombineIntrinsic(), llvm::X86TTIImpl::instCombineIntrinsic(), instCombineSVELast(), llvm::FunctionAnalysisManagerCGSCCProxy::Result::invalidate(), llvm::CGSCCAnalysisManagerModuleProxy::Result::invalidate(), llvm::invertCondition(), llvm::IRSimilarity::IRInstructionData::IRInstructionData(), is_ns_hex_digit(), is_ns_word_char(), llvm::is_sorted(), llvm::MCAsmInfo::isAcceptableChar(), llvm::MCAsmInfoXCOFF::isAcceptableChar(), llvm::SystemZMCAsmInfo::isAcceptableChar(), llvm::isAllOnesOrAllOnesSplat(), llvm::LazyCallGraph::RefSCC::isAncestorOf(), llvm::LazyCallGraph::SCC::isAncestorOf(), llvm::isBitwiseNot(), isBLACompatibleAddress(), isBSwapHWordElement(), isBSwapHWordPair(), llvm::isBytewiseValue(), llvm::BitCodeAbbrevOp::isChar6(), llvm::LazyCallGraph::SCC::isChildOf(), llvm::ProfileSummaryInfo::isColdCallSite(), llvm::ProfileSummaryInfo::isColdCount(), llvm::ProfileSummaryInfo::isColdCountNthPercentile(), llvm::ConstraintSystem::isConditionImplied(), llvm::AMDGPUTargetLowering::isConstantCostlierToNegate(), isConstantIntVector(), llvm::IsConstantOffsetFromGlobal(), llvm::LazyCallGraph::SCC::isDescendantOf(), isDigit(), isDivZero(), isDSAddress(), isDSAddress(), llvm::AA::isDynamicallyUnique(), isExponentChar(), isExtendedBUILD_VECTOR(), isExtendedBUILD_VECTOR(), isFunctionMallocLike(), isGuaranteedNotToBeUndefOrPoison(), llvm::ARMTTIImpl::isHardwareLoopProfitable(), llvm::PPCTTIImpl::isHardwareLoopProfitable(), isHexDigit(), isHorizontalBinOp(), llvm::ProfileSummaryInfo::isHotCallSite(), llvm::ProfileSummaryInfo::isHotCount(), llvm::ProfileSummaryInfo::isHotCountNthPercentile(), isICmpTrue(), isIdentifierChar(), isIdentifierChar(), SCEVDbgValueBuilder::isIdentityFunction(), isInPartition(), isIntImmediate(), llvm::SelectionDAG::isKnownNeverNaN(), llvm::SelectionDAG::isKnownNeverZero(), llvm::SelectionDAG::isKnownNeverZeroFloat(), isKnownNonNaN(), isKnownNonZero(), isKnownNonZero(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), isLabelChar(), llvm::AArch64GISelUtils::isLegalArithImmed(), isLegalArithImmed(), isLower(), isMacroParameterChar(), isMulPowOf2(), isNegativeOne(), isNewlineChar(), isNonEqualMul(), isNonEqualShl(), isNonZeroModBitWidthOrUndef(), isNonZeroModBitWidthOrUndef(), llvm::isNullOrNullSplat(), isNullOrUndef(), IsNullTerminatedString(), isNumberChar(), llvm::isOneOrOneSplat(), isOnlyUsedInComparisonWithZero(), llvm::isOnlyUsedInZeroEqualityComparison(), llvm::SelectionDAGISel::isOrEquivalentToAdd(), llvm::LazyCallGraph::RefSCC::isParentOf(), llvm::LazyCallGraph::SCC::isParentOf(), isPerfectIncrement(), isPoisonShift(), isPossibleIndirectCallTarget(), isPowerOf2Constant(), isPrintableString(), isQuote(), isRebasedHexDigit(), isRegisterChar(), isRepeatedByteSequence(), isSafeSROAElementUse(), llvm::isSafeToDestroyConstant(), isSafeToPromoteArgument(), llvm::isSafeToSpeculativelyExecute(), isScaledConstantInRange(), isSignedChar(), isSignTest(), isSimpleEnoughPointerToCommit(), isSimpleEnoughValueToCommit(), isSimpleEnoughValueToCommitHelper(), llvm::isSplatValue(), isSSATMinMaxPattern(), isSuitableForBSS(), isTruePredicate(), isUpper(), isValid(), isValidHexFloatingPointPrefix(), llvm::MCAsmInfo::isValidUnquotedName(), llvm::Pattern::isValidVarNameStart(), llvm::PatternMatch::is_nan::isValue(), llvm::PatternMatch::is_nonnan::isValue(), llvm::PatternMatch::is_inf::isValue(), llvm::PatternMatch::is_noninf::isValue(), llvm::PatternMatch::is_finite::isValue(), llvm::PatternMatch::is_finitenonzero::isValue(), llvm::PatternMatch::is_any_zero_fp::isValue(), llvm::PatternMatch::is_pos_zero_fp::isValue(), llvm::PatternMatch::is_neg_zero_fp::isValue(), llvm::PatternMatch::is_non_zero_fp::isValue(), llvm::PatternMatch::is_all_ones::isValue(), llvm::PatternMatch::is_maxsignedvalue::isValue(), llvm::PatternMatch::is_negative::isValue(), llvm::PatternMatch::is_nonnegative::isValue(), llvm::PatternMatch::is_strictlypositive::isValue(), llvm::PatternMatch::is_nonpositive::isValue(), llvm::PatternMatch::is_one::isValue(), llvm::PatternMatch::is_zero_int::isValue(), llvm::PatternMatch::is_power2::isValue(), llvm::PatternMatch::is_negated_power2::isValue(), llvm::PatternMatch::is_power2_or_zero::isValue(), llvm::PatternMatch::is_sign_mask::isValue(), llvm::PatternMatch::is_lowbit_mask::isValue(), llvm::PatternMatch::icmp_pred_with_threshold::isValue(), isWhitespace(), isWhitespaceOrNull(), isWindowsSpecialChar(), llvm::LinearPolyBase< LeafTy >::isZero(), isZero(), isZero(), llvm::SwitchCG::CaseCluster::jumpTable(), lexFloatingPointLiteral(), lexName(), lexNamedVirtualRegister(), lexStringConstant(), lexVirtualRegister(), LLVMAddCallSiteAttribute(), LLVMAppendBasicBlockInContext(), LLVMBFloatTypeInContext(), LLVMConstStringInContext(), LLVMConstStructInContext(), LLVMContextDispose(), LLVMContextGetDiagnosticContext(), LLVMContextGetDiagnosticHandler(), LLVMContextSetDiagnosticHandler(), LLVMContextSetDiscardValueNames(), LLVMContextSetYieldCallback(), LLVMContextShouldDiscardValueNames(), LLVMCreateBasicBlockInContext(), LLVMCreateBuilderInContext(), LLVMCreateEnumAttribute(), LLVMCreateStringAttribute(), LLVMCreateTypeAttribute(), LLVMDoubleTypeInContext(), LLVMFloatTypeInContext(), LLVMFP128TypeInContext(), LLVMGetAsString(), LLVMGetCallSiteAttributeCount(), LLVMGetCallSiteAttributes(), LLVMGetCallSiteEnumAttribute(), LLVMGetCallSiteStringAttribute(), LLVMGetComdatSelectionKind(), LLVMGetDebugLocColumn(), LLVMGetElementAsConstant(), LLVMGetInstructionOpcode(), LLVMGetMDKindIDInContext(), LLVMGetTypeByName2(), LLVMHalfTypeInContext(), LLVMInitializePowerPCAsmParser(), LLVMInitializePowerPCTarget(), LLVMInitializePowerPCTargetMC(), LLVMInitializeSparcAsmParser(), LLVMInsertBasicBlockInContext(), LLVMInstructionClone(), LLVMInt128TypeInContext(), LLVMInt16TypeInContext(), LLVMInt1TypeInContext(), LLVMInt32TypeInContext(), LLVMInt64TypeInContext(), LLVMInt8TypeInContext(), LLVMIntPtrTypeForASInContext(), LLVMIntPtrTypeInContext(), LLVMIntTypeInContext(), LLVMIsConstantString(), LLVMIsNull(), LLVMLabelTypeInContext(), LLVMMDNodeInContext(), LLVMMDNodeInContext2(), LLVMMDStringInContext(), LLVMMDStringInContext2(), LLVMMetadataAsValue(), LLVMMetadataTypeInContext(), LLVMModuleCreateWithNameInContext(), LLVMPPCFP128TypeInContext(), LLVMRemoveCallSiteEnumAttribute(), LLVMRemoveCallSiteStringAttribute(), LLVMSetComdat(), LLVMSetComdatSelectionKind(), LLVMStructCreateNamed(), LLVMStructTypeInContext(), LLVMTokenTypeInContext(), LLVMValueAsMetadata(), LLVMVoidTypeInContext(), LLVMX86AMXTypeInContext(), LLVMX86FP80TypeInContext(), LLVMX86MMXTypeInContext(), llvm::XCoreInstrInfo::loadImmediate(), loadObj(), lookThroughCast(), LookupConstant(), llvm::LazyCallGraph::lookupRefSCC(), llvm::lower_bound(), llvm::HexagonTargetLowering::LowerAddSubCarry(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::AVRTargetLowering::LowerAsmOperandForConstraint(), llvm::LanaiTargetLowering::LowerAsmOperandForConstraint(), llvm::M68kTargetLowering::LowerAsmOperandForConstraint(), llvm::RISCVTargetLowering::LowerAsmOperandForConstraint(), llvm::SparcTargetLowering::LowerAsmOperandForConstraint(), llvm::SystemZTargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::HexagonTargetLowering::LowerBUILD_VECTOR(), lowerBuildVectorAsBroadcast(), llvm::SparcTargetLowering::LowerCall_32(), llvm::TargetLowering::lowerCmpEqZeroToCtlzSrl(), llvm::AsmPrinter::lowerConstant(), llvm::LanaiTargetLowering::LowerConstantPool(), lowerIncomingStatepointValue(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), lowerIsConstantIntrinsic(), llvm::LanaiTargetLowering::LowerMUL(), LowerRotate(), llvm::HexagonTargetLowering::LowerSETCC(), LowerShift(), llvm::LegalizerHelper::lowerU64ToF32BitOps(), llvm::lto::LTOLLVMContext::LTOLLVMContext(), llvm::PatternMatch::m_Br(), llvm::PatternMatch::m_Br(), llvm::PatternMatch::m_Constant(), llvm::PatternMatch::m_ConstantExpr(), llvm::PatternMatch::m_ConstantFP(), llvm::MIPatternMatch::m_GFCst(), llvm::PatternMatch::m_ImmConstant(), llvm::PatternMatch::m_Select(), llvm::PatternMatch::m_SelectCst(), maintainNoSignedWrap(), makeAllConstantUsesInstructions(), llvm::KnownBits::makeConstant(), llvm::ConstantRange::makeExactICmpRegion(), AAIsDeadFloating::manifest(), llvm::map_range(), llvm::ValueMapper::mapConstant(), mapInputsToGVNs(), llvm::SCCPSolver::markArgInFuncSpecialization(), llvm::SCCPInstVisitor::markArgInFuncSpecialization(), llvm::PatternMatch::apint_match::match(), llvm::PatternMatch::apfloat_match::match(), llvm::PatternMatch::cstval_pred_ty< Predicate, ConstantVal >::match(), llvm::PatternMatch::api_pred_ty< Predicate >::match(), llvm::PatternMatch::apf_pred_ty< Predicate >::match(), llvm::PatternMatch::is_zero::match(), llvm::PatternMatch::specific_fpval::match(), llvm::PatternMatch::specific_intval< AllowUndefs >::match(), llvm::PatternMatch::LogicalOp_match< LHS, RHS, Opcode >::match(), matchAliasCondition(), llvm::MCInstPrinter::matchAliasPatterns(), llvm::CombinerHelper::matchConstantOp(), llvm::matchDecomposedSelectPattern(), MatchDiv(), matchesAdd(), matchesOr(), matchICmpOperand(), llvm::CombinerHelper::matchLoadOrCombine(), matchLSNode(), matchMinMaxOfMinMax(), MatchMul(), matchOrConcat(), MatchRem(), llvm::CombinerHelper::matchRotateOutOfRange(), maybeLexConstantPoolItem(), maybeLexEscapedIRValue(), maybeLexExclaim(), maybeLexExternalSymbol(), maybeLexFixedStackObject(), maybeLexGlobalValue(), maybeLexHexadecimalLiteral(), maybeLexIdentifier(), maybeLexIndex(), maybeLexIndexAndName(), maybeLexIRBlock(), maybeLexIRValue(), maybeLexJumpTableIndex(), maybeLexMachineBasicBlock(), maybeLexMCSymbol(), maybeLexNewline(), maybeLexNumericalLiteral(), maybeLexRegister(), maybeLexStackObject(), maybeLexStringConstant(), maybeLexSubRegisterIndex(), maybeLexSymbol(), maybePrintComdat(), llvm::Constant::mergeUndefsWith(), multikeySort(), llvm::detail::DoubleAPFloat::multiply(), narrowExtractedVectorBinOp(), narrowUDivURem(), AMDGPUInformationCache::needsQueuePtr(), llvm::ConstraintSystem::negate(), NegateValue(), llvm::EscapeEnumerator::Next(), llvm::RegisterPassParser< RegistryClass >::NotifyAdd(), llvm::json::ObjectKey::ObjectKey(), operandWithNewAddressSpaceOrCreateUndef(), operator delete(), operator delete[](), operator new(), operator new[](), llvm::orc::ConcurrentIRCompiler::operator()(), llvm::CodeGenPassBuilder< DerivedT >::AddMachinePass::operator()(), llvm::ManagedStatic< C, Creator, Deleter >::operator*(), llvm::ManagedStatic< C, Creator, Deleter >::operator*(), OutputStream::operator+=(), OutputStream::operator<<(), llvm::raw_ostream::operator<<(), llvm::DiagnosticPrinterRawOStream::operator<<(), llvm::raw_ostream::operator<<(), llvm::operator<<(), llvm::pdb::operator<<(), llvm::operator<<(), llvm::raw_ostream::operator<<(), llvm::DiagnosticPrinterRawOStream::operator<<(), llvm::raw_ostream::operator<<(), llvm::DiagnosticPrinterRawOStream::operator<<(), llvm::json::ObjectKey::operator=(), llvm::ConstantAggrKeyType< ConstantClass >::operator==(), llvm::ShapeT::operator==(), OptimizeAwayTrappingUsesOfValue(), optimizeGlobalsInModule(), OptimizeGlobalVars(), llvm::opt::OptTable::OptTable(), orderValue(), orderValue(), llvm::OutlinableRegion::OutlinableRegion(), llvm::outliner::OutlinedFunction::OutlinedFunction(), outputEscapedChar(), outputHex(), outputSpaceIfNecessary(), llvm::dwarf::CFIProgram::parse(), llvm::InlineAsm::ConstraintInfo::Parse(), llvm::parseAmdKernelCodeField(), llvm::AMDGPU::parseArchAMDGCN(), llvm::AMDGPU::parseArchR600(), parseBasicType(), parseBitField(), llvm::parseConstantValue(), llvm::AArch64::parseCPUArch(), llvm::ARM::parseCPUArch(), parseField(), AbstractManglingParser< Derived, Alloc >::parseFloatingLiteral(), parseIRConstant(), parseIRValue(), llvm::PassBuilder::parsePassPipeline(), parsePhysicalReg(), llvm::LLParser::parseStandaloneConstantValue(), llvm::parseWidenableBranch(), llvm::parseWidenableBranch(), passingValueIsAlwaysUndefined(), PerformAddcSubcCombine(), PerformAddeSubeCombine(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::RISCVTargetLowering::PerformDAGCombine(), PerformExtractFpToIntStores(), performFDivCombine(), performFpToIntCombine(), performGlobalAddressCombine(), PerformLongShiftCombine(), performMULCombine(), performMulCombine(), PerformMULCombine(), PerformPREDICATE_CASTCombine(), PerformShiftCombine(), PerformSplittingMVEEXTToWideningLoad(), PerformSplittingMVETruncToNarrowingStores(), PerformSplittingToNarrowingStores(), PerformSplittingToWideningLoad(), performSRLCombine(), performSVEAndCombine(), PerformVCVTCombine(), PerformVDIVCombine(), performVectorTruncateCombine(), PerformVMOVrhCombine(), popFront(), predictValueUseListOrder(), prepareICWorklistFromFunction(), llvm::Value::print(), llvm::SpillPlacement::BlockConstraint::print(), llvm::MCSymbol::print(), llvm::printAmdKernelCodeField(), PrintByteList(), printField(), llvm::printLLVMNameWithoutPrefix(), printMetadataIdentifier(), printRefSCC(), printSCC(), processCallSite(), processCmp(), processMemAccess(), processPHI(), processSelect(), llvm::PassInstrumentation::pushBeforeNonSkippedPassCallback(), SCEVDbgValueBuilder::pushCast(), SCEVDbgValueBuilder::pushConst(), llvm::json::quote(), r0(), r1(), r2(), r3(), r4(), llvm::SwitchCG::CaseCluster::range(), llvm::BinaryStreamReader::readWideString(), llvm::CallGraphUpdater::reanalyzeFunction(), rebasedHexDigitToNumber(), ReduceSwitchRange(), llvm::BitTracker::RegisterCell::ref(), llvm::PassInstrumentationCallbacks::registerAfterAnalysisCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassCallback(), llvm::PassInstrumentationCallbacks::registerAfterPassInvalidatedCallback(), llvm::PassInstrumentationCallbacks::registerAnalysesClearedCallback(), llvm::PassInstrumentationCallbacks::registerAnalysisInvalidatedCallback(), llvm::PassBuilder::registerAnalysisRegistrationCallback(), llvm::PassBuilder::registerAnalysisRegistrationCallback(), llvm::PassBuilder::registerAnalysisRegistrationCallback(), llvm::PassBuilder::registerAnalysisRegistrationCallback(), llvm::PassInstrumentationCallbacks::registerBeforeAnalysisCallback(), llvm::PassInstrumentationCallbacks::registerBeforeNonSkippedPassCallback(), llvm::PassInstrumentationCallbacks::registerBeforeSkippedPassCallback(), llvm::PassBuilder::registerCGSCCAnalyses(), llvm::PassBuilder::registerCGSCCOptimizerLateEPCallback(), llvm::orc::shared::SerializationTraits< ChannelT, Error >::registerErrorType(), llvm::PassBuilder::registerFunctionAnalyses(), llvm::PassBuilder::registerLateLoopOptimizationsEPCallback(), llvm::PassBuilder::registerLoopAnalyses(), llvm::PassBuilder::registerLoopOptimizerEndEPCallback(), llvm::PassBuilder::registerModuleAnalyses(), llvm::PassBuilder::registerOptimizerLastEPCallback(), llvm::PassBuilder::registerParseAACallback(), llvm::PassBuilder::registerParseTopLevelPipelineCallback(), llvm::PassBuilder::registerPeepholeEPCallback(), llvm::PassBuilder::registerPipelineEarlySimplificationEPCallback(), llvm::PassBuilder::registerPipelineParsingCallback(), llvm::PassBuilder::registerPipelineParsingCallback(), llvm::PassBuilder::registerPipelineParsingCallback(), llvm::PassBuilder::registerPipelineParsingCallback(), llvm::PassBuilder::registerPipelineStartEPCallback(), llvm::PassBuilder::registerScalarOptimizerLateEPCallback(), llvm::PassInstrumentationCallbacks::registerShouldRunOptionalPassCallback(), llvm::orc::shared::registerStringError(), llvm::PassBuilder::registerVectorizerStartEPCallback(), llvm::RISCVAsmBackend::relaxDwarfLineAddr(), llvm::sys::path::remove_dots(), llvm::AttributeSet::removeAttribute(), llvm::AttributeSet::removeAttribute(), llvm::AttributeList::removeAttribute(), llvm::AttributeList::removeAttribute(), llvm::AttributeSet::removeAttributes(), llvm::AttributeList::removeAttributes(), llvm::AttributeList::removeAttributes(), RemoveDeadConstant(), llvm::LazyCallGraph::removeDeadFunction(), removeDeadUsersOfConstant(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), llvm::AttributeList::removeParamAttribute(), llvm::AttributeList::removeParamAttribute(), llvm::AttributeList::removeParamAttributes(), llvm::AttributeList::removeParamAttributes(), replaceAllPrepares(), llvm::AttributeList::replaceAttributeType(), llvm::X86InstrInfo::replaceBranchWithTailCall(), llvm::AMDGPU::replaceConstantUsesInFunction(), llvm::CombinerHelper::replaceInstWithConstant(), llvm::CombinerHelper::replaceInstWithConstant(), llvm::CombinerHelper::replaceInstWithFConstant(), replaceLongjmpWithEmscriptenLongjmp(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::Constant::replaceUndefsWith(), llvm::Value::replaceUsesWithIf(), reportIllegalCopy(), llvm::orc::shared::detail::respond(), llvm::orc::shared::detail::respond(), llvm::CCState::resultsCompatible(), llvm::reverse(), llvm::reverse(), rewriteComdat(), llvm::StringRef::rfind(), llvm::SmallString< InternalLen >::rfind(), llvm::StringRef::rfind_insensitive(), llvm::rdf::CopyPropagation::run(), llvm::InstCombinerImpl::run(), llvm::FunctionAnalysisManagerCGSCCProxy::run(), llvm::RequireAnalysisPass< AnalysisT, LazyCallGraph::SCC, CGSCCAnalysisManager, LazyCallGraph &, CGSCCUpdateResult & >::run(), llvm::CGSCCToFunctionPassAdaptor::run(), llvm::CoroSplitPass::run(), llvm::ArgumentPromotionPass::run(), llvm::AttributorCGSCCPass::run(), llvm::PostOrderFunctionAttrsPass::run(), llvm::OpenMPOptCGSCCPass::run(), llvm::DevirtSCCRepeatedPass::run(), llvm::PassManager< IRUnitT, AnalysisManagerT, ExtraArgTs >::run(), llvm::GlobalDCEPass::run(), llvm::ModuleToPostOrderCGSCCPassAdaptor::run(), llvm::LazyCallGraphPrinterPass::run(), llvm::PassInstrumentation::runAfterAnalysis(), llvm::PassInstrumentation::runAfterPass(), llvm::PassInstrumentation::runAfterPassInvalidated(), llvm::PassInstrumentation::runAnalysesCleared(), llvm::PassInstrumentation::runAnalysisInvalidated(), llvm::PassInstrumentation::runBeforeAnalysis(), llvm::PassInstrumentation::runBeforePass(), runCVP(), runImpl(), scalarConstantToHexString(), llvm::SchedDFSResult::scheduleTree(), llvm::RISCVDAGToDAGISel::Select(), llvm::HexagonDAGToDAGISel::SelectAddSubCarry(), selectELFSectionForGlobal(), selectExplicitSectionGlobal(), llvm::LoopVectorizationCostModel::selectInterleaveCount(), llvm::FastISel::selectPatchpoint(), llvm::HexagonDAGToDAGISel::SelectQ2V(), llvm::RISCVDAGToDAGISel::selectRVVSimm5(), llvm::HexagonDAGToDAGISel::SelectSHL(), llvm::HexagonDAGToDAGISel::SelectV2Q(), llvm::HexagonDAGToDAGISel::SelectVAlign(), llvm::LoopVectorizationCostModel::selectVectorizationFactor(), llvm::RISCVDAGToDAGISel::selectVLOp(), selectWasmSectionForGlobal(), llvm::RISCVDAGToDAGISel::selectZExti32(), llvm::orc::shared::detail::RespondHelper< true >::sendResult(), llvm::orc::shared::detail::RespondHelper< false >::sendResult(), llvm::orc::shared::detail::RespondHelper< true >::sendResult(), llvm::orc::shared::detail::RespondHelper< false >::sendResult(), llvm::orc::shared::SerializationTraits< ChannelT, std::vector< T >, ArrayRef< T > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, bool, bool, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::serialize(), llvm::orc::shared::SequenceSerialization< ChannelT, ArgT >::serialize(), llvm::orc::shared::SequenceSerialization< ChannelT, ArgT, ArgTs... >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::map< K, V >, DenseMap< K2, V2 > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, JITSymbolFlags >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, Optional< T > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ExecutorProcessInfo >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReleaseOrFinalizeMemRequestElement >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReserveMemRequestElement >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReserveMemResultElement >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, remote::DirectBufferWriter, remote::DirectBufferWriter, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::map< K, V >, std::map< K2, V2 > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::pair< T1, T2 >, std::pair< T3, T4 > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::set< T >, std::set< T2 > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::tuple< ArgTs... > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::vector< T > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, tpctypes::BufferWrite, tpctypes::BufferWrite, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, WrapperFunctionResult, WrapperFunctionResult, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, WriteT, WriteT, std::enable_if_t< std::is_same< WriteT, tpctypes::UInt8Write >::value||std::is_same< WriteT, tpctypes::UInt16Write >::value||std::is_same< WriteT, tpctypes::UInt32Write >::value||std::is_same< WriteT, tpctypes::UInt64Write >::value > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, Error >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, Expected< T >, Error >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, Expected< T1 >, Expected< T2 > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, T, T, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value &&(std::is_same< T, uint8_t >::value||std::is_same< T, int8_t >::value||std::is_same< T, uint16_t >::value||std::is_same< T, int16_t >::value||std::is_same< T, uint32_t >::value||std::is_same< T, int32_t >::value||std::is_same< T, uint64_t >::value||std::is_same< T, int64_t >::value||std::is_same< T, char >::value)> >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, Expected< T1 >, T2 >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::string, T, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value &&(std::is_same< T, const char * >::value||std::is_same< T, char * >::value)> >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::string, std::string, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::string, StringRef, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::serialize(), llvm::orc::shared::detail::HandlerTraits< RetT(ArgTs...)>::serializeArgs(), llvm::orc::shared::serializeSeq(), llvm::ModuleSummaryIndex::setBlockCount(), llvm::rdf::CodeNode::setCode(), llvm::GlobalObject::setComdat(), llvm::MCParsedAsmOperand::setConstraint(), setCoroInfo(), llvm::Check::FileCheckType::setCount(), llvm::Function::ProfileCount::setCount(), llvm::RegisterRegAllocBase< SubClass >::setDefault(), llvm::MachinePassRegistry< PassCtorTy >::setDefault(), llvm::GlobalValue::setDLLStorageClass(), llvm::CoroIdInst::setInfo(), setLimitsForBinOp(), setLimitsForIntrinsic(), setLimitsForSelectPattern(), llvm::MCSymbolXCOFF::setRepresentedCsect(), llvm::remarks::BitstreamRemarkSerializerHelper::setupBlockInfo(), llvm::setWidenableBranchCond(), llvm::ELFYAML::shouldAllocateFileSpace(), llvm::TargetTransformInfo::shouldBuildLookupTablesForConstant(), llvm::ARMTTIImpl::shouldBuildLookupTablesForConstant(), shouldConvert(), shouldSwapCmpOperands(), shouldTransformMulToShiftsAddsSubs(), shouldUseZeroOffsetLdSt(), ShrinkDemandedConstant(), llvm::TargetLowering::ShrinkDemandedConstant(), SimplifyAddInst(), simplifyAllocaArraySize(), SimplifyAndInst(), simplifyAndOrOfCmps(), simplifyAndOrOfICmpsWithLimitConst(), SimplifyAssociativeBinOp(), llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative(), simplifyBinaryIntrinsic(), SimplifyBSwap(), SimplifyCastInst(), simplifyCommonValuePhi(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::InstCombinerImpl::SimplifyDemandedUseBits(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), llvm::X86TargetLowering::SimplifyDemandedVectorEltsForTargetShuffle(), simplifyDiv(), SimplifyFAddInst(), SimplifyFCmpInst(), SimplifyFDivInst(), SimplifyFMAFMul(), SimplifyFMulInst(), simplifyFNegInst(), SimplifyFRemInst(), SimplifyFSubInst(), SimplifyGEPInst(), SimplifyICmpInst(), simplifyICmpWithBinOp(), simplifyICmpWithConstant(), simplifyICmpWithMinMax(), SimplifyMulInst(), simplifyNeonTbl1(), SimplifyOrInst(), SimplifyRelativeLoad(), simplifyRem(), simplifySelectBitTest(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), simplifySelectWithFCmp(), llvm::TargetLowering::SimplifySetCC(), SimplifyShift(), SimplifyShuffleVectorInst(), SimplifySubInst(), llvm::InstCombinerImpl::SimplifyUsingDistributiveLaws(), simplifyWithOpReplaced(), SimplifyXorInst(), llvm::VPlanTransforms::sinkScalarOperands(), llvm::yaml::skip(), llvm::DataExtractor::skip(), skipComment(), skipExtensionForVectorMULL(), SkipExtensionForVMULL(), skipMachineOperandComment(), skipWhitespace(), SolveQuadraticAddRecExact(), SolveQuadraticAddRecRange(), llvm::APIntOps::SolveQuadraticEquationWrap(), llvm::sort(), llvm::sort(), llvm::ARMFrameLowering::spillCalleeSavedRegisters(), llvm::SplitBlockAndInsertIfThenElse(), SplitBlockAndInsertIfThenImpl(), splitCodeGen(), llvm::formatv_object_base::splitLiteralAndReplacement(), llvm::stable_hash_combine(), llvm::stable_hash_combine(), llvm::stable_hash_combine_array(), llvm::stable_hash_combine_string(), llvm::stable_sort(), StringView::startsWith(), StrengthenNoWrapFlags(), StripAttr(), stripDeadDebugInfoImpl(), stripDebugDeclareImpl(), llvm::InstCombiner::SubOne(), supportedAddressingMode(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::MachO::swapStruct(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), symbolToken(), llvm::SystemZPostRASchedStrategy::SystemZPostRASchedStrategy(), llvm::AArch64TargetLowering::targetShrinkDemandedConstant(), llvm::ARMTargetLowering::targetShrinkDemandedConstant(), llvm::RISCVTargetLowering::targetShrinkDemandedConstant(), llvm::X86TargetLowering::targetShrinkDemandedConstant(), thinLTOResolvePrevailingGUID(), llvm::thinLTOResolvePrevailingInIndex(), llvm::cl::TokenizeGNUCommandLine(), toUTF8(), translateExtract(), translateLocChar(), tryAdjustICmpImmAndPred(), tryConstantFoldCall(), llvm::DWARFUnit::tryExtractDIEsIfNeeded(), llvm::InstCombinerImpl::tryFactorization(), llvm::HexagonDAGToDAGISel::tryLoadOfLoadIntrinsic(), tryToFindRegisterToRename(), tryToFoldExtendOfConstant(), llvm::UnaryConstantExpr::UnaryConstantExpr(), unescapeQuotedString(), llvm::PotentialValuesState< MemberTy, KeyInfo >::unionAssumed(), updateCallGraphAfterCoroutineSplit(), updateCGAndAnalysisManagerForPass(), AAAMDAttributesFunction::updateImpl(), AANoAliasReturned::updateImpl(), updateNewSCCFunctionAnalyses(), updatePostorderSequenceForEdgeInsertion(), llvm::UpgradeBitCastExpr(), llvm::UpgradeGlobalVariable(), llvm::UpgradeIntrinsicCall(), upgradeLoopTag(), UpgradeMaskedLoad(), UpgradeMaskedStore(), llvm::upper_bound(), usedInGlobalVarDef(), useFuncSeen(), llvm::yaml::MappingTraits< ArchYAML::Archive::Child >::validate(), llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::validate(), ValidLookupTableConstant(), llvm::ObjectSizeOffsetVisitor::visitAllocaInst(), llvm::InstCombinerImpl::visitAllocSite(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitExtractValueInst(), llvm::InstCombinerImpl::visitFAdd(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFMul(), llvm::InstCombinerImpl::visitFreeze(), llvm::InstCombinerImpl::visitFSub(), llvm::InstCombinerImpl::visitGetElementPtrInst(), llvm::InstCombinerImpl::visitICmpInst(), llvm::DWARFDebugLoc::visitLocationList(), llvm::DWARFDebugLoclists::visitLocationList(), visitMaskedMerge(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitOr(), llvm::LazyCallGraph::visitReferences(), llvm::InstCombinerImpl::visitSRem(), llvm::InstCombinerImpl::visitSub(), llvm::InstCombinerImpl::visitSwitchInst(), llvm::InstCombinerImpl::visitTrunc(), llvm::InstCombinerImpl::visitXor(), llvm::InstCombinerImpl::visitZExt(), llvm::InnerLoopVectorizer::widenInstruction(), llvm::widenWidenableBranch(), llvm::wouldInstructionBeTriviallyDead(), llvm::write(), llvm::raw_ostream::write(), write_padding(), writeCounter(), llvm::writeIndex(), llvm::reassociate::XorOpnd::XorOpnd(), and llvm::yaml::yaml2archive().
D
GCRegistry::Add< StatepointGC > D("statepoint-example", "an example strategy for statepoint") ("statepoint-example" , "an example strategy for statepoint") static
Referenced by llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::add(), llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::add(), llvm::SUnit::addPred(), addToFwdRegWorklist(), llvm::DWARFUnitVector::addUnitsForDWOSection(), llvm::DWARFUnitVector::addUnitsForSection(), llvm::BlockFrequencyInfoImplBase::adjustLoopHeaderMass(), llvm::MCRegisterInfo::DiffListIterator::advance(), appendDigit(), llvm::HexagonSubtarget::UsrOverflowMutation::apply(), llvm::DwarfCompileUnit::applyStmtList(), llvm::DwarfCompileUnit::attachLowHighPC(), llvm::DWARFDie::attribute_iterator::attribute_iterator(), llvm::slpvectorizer::BoUpSLP::bestOrder(), llvm::BitsToDouble(), llvm::HexagonPacketizerList::canPromoteToDotNew(), checkDependency(), checkDyldCommand(), checkDylibCommand(), llvm::VPWidenRecipe::classof(), llvm::VPWidenCallRecipe::classof(), llvm::VPWidenSelectRecipe::classof(), llvm::VPWidenGEPRecipe::classof(), llvm::VPWidenIntOrFpInductionRecipe::classof(), llvm::VPBlendRecipe::classof(), llvm::VPInterleaveRecipe::classof(), llvm::VPReplicateRecipe::classof(), llvm::VPBranchOnMaskRecipe::classof(), llvm::VPPredInstPHIRecipe::classof(), llvm::VPWidenMemoryInstructionRecipe::classof(), llvm::VPWidenCanonicalIVRecipe::classof(), llvm::VPFirstOrderRecurrencePHIRecipe::classof(), llvm::DILocation::cloneByMultiplyingDuplicationFactor(), llvm::DILocation::cloneWithBaseDiscriminator(), combineTargetShuffle(), llvm::ProfileSummaryBuilder::computeDetailedSummary(), llvm::rdf::Liveness::computeLiveIns(), llvm::rdf::Liveness::computePhiInfo(), llvm::DwarfUnit::constructContainingTypeDIEs(), llvm::DwarfCompileUnit::constructVariableDIE(), llvm::InstrProfSymtab::create(), llvm::object::Decompressor::create(), llvm::DWARFFormValue::createFromBlockValue(), llvm::mca::InstrBuilder::createInstruction(), llvm::AbstractDependenceGraphBuilder< GraphType >::createMemoryDependencyEdges(), llvm::DataDependenceGraph::DataDependenceGraph(), llvm::DataDependenceGraph::DataDependenceGraph(), debugAssign(), llvm::DILocation::decodeDiscriminator(), DecodeFixedType(), llvm::GCNIterativeScheduler::detachSchedule(), llvm::BlockFrequencyInfoImplBase::distributeIrrLoopHeaderMass(), llvm::BlockFrequencyInfoImplBase::distributeMass(), llvm::SCEVDivision::divide(), llvm::ScaledNumberBase::dump(), dumpArrayType(), dumpExampleDependence(), dumpTypeName(), llvm::MCLOHContainer::emit(), llvm::DWARFDebugInfoEntry::extractFast(), llvm::StringRef::find_insensitive(), llvm::DWARFDie::findRecursively(), llvm::DwarfCompileUnit::finishSubprogramDefinition(), llvm::UnOpInit::Fold(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::InstCombinerImpl::foldICmpEquality(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), llvm::format_provider< std::chrono::duration< Rep, Period > >::format(), llvm::InLineChangePrinter::generateIRRepresentation(), llvm::rdf::Liveness::getAllReachedUses(), llvm::json::Value::getAsInteger(), llvm::DILocation::getBaseDiscriminatorFromDiscriminator(), llvm::ScalarEvolution::getBlockDisposition(), llvm::Loop::LoopBounds::getCanonicalPredicate(), llvm::DILocation::getCopyIdentifierFromDiscriminator(), llvm::object::COFFObjectFile::getDebugPDBInfo(), llvm::DWARFDie::getDeclFile(), llvm::DependenceGraphInfo< NodeType >::getDependenceString(), llvm::DwarfUnit::getDIE(), llvm::DWARFUnit::getDIEIndex(), llvm::DILocation::getDuplicationFactorFromDiscriminator(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getEdgeAttributes(), llvm::MCLOHContainer::getEmitSize(), llvm::WebAssemblyException::getExceptionDepth(), llvm::ScaledNumber< DigitsT >::getFraction(), llvm::StatepointOpers::getGCPointerMap(), llvm::DenseMapInfo< DebugVariable >::getHashValue(), llvm::object::MachOObjectFile::getLibraryShortNameByIndex(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::ScalarEvolution::getLoopDisposition(), llvm::DILocation::getMaskedDiscriminator(), getMaskedTypeForICmpPair(), getNextComponentInDiscriminator(), getReg(), getReg(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::ScalarEvolution::getUDivCeilSCEV(), llvm::object::ELFFile< ELFT >::getVersionDefinitions(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::DWARFVerifier::handleAccelTables(), llvm::IndexedReference::hasTemporalReuse(), ignoreDependence(), llvm::MCInstrInfo::InitMCInstrInfo(), llvm::MCRegisterInfo::InitMCRegisterInfo(), llvm::DwarfUnit::insertDIE(), llvm::DwarfUnit::insertDIE(), llvm::interpretDecimal(), isCommutableVPERMV3Instruction(), llvm::rdf::TargetOperandInfo::isFixedReg(), llvm::InductionDescriptor::isFPInductionPHI(), isHorizontalBinOp(), llvm::InductionDescriptor::isInductionPHI(), llvm::InductionDescriptor::isInductionPHI(), llvm::SwingSchedulerDAG::isLoopCarriedDep(), isSafeToMove(), llvm::DwarfUnit::isShareableAcrossCUs(), llvm::PPCInstrInfo::isSignOrZeroExtended(), llvm::ImutContainerInfo< T >::KeyOfValue(), llvm::ImutContainerInfo< T * >::KeyOfValue(), llvm::LexicalScope::LexicalScope(), LLVMInitializePowerPCAsmParser(), LLVMInitializePowerPCTarget(), LLVMLinkModules2(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::LegalizerHelper::lowerFPTRUNC_F64_TO_F16(), matchIntrinsicType(), llvm::Intrinsic::matchIntrinsicVarArg(), matchMinMaxOfMinMax(), llvm::microsoftDemangle(), llvm::detail::DoubleAPFloat::multiply(), narrowUDivURem(), llvm::RegisterPassParser< RegistryClass >::NotifyAdd(), llvm::jitlink::DefineExternalSectionStartAndEndSymbols< SymbolIdentifierFunction >::operator()(), std::reverse_iterator< llvm::DWARFDie::iterator >::operator++(), llvm::object::operator<<(), llvm::pdb::operator<<(), llvm::operator<<(), llvm::ARM::parseHWDiv(), llvm::ProfOStream::patch(), populateDependencyMatrix(), preservesBackwardDependence(), preservesForwardDependence(), llvm::ScaledNumberBase::print(), processSDiv(), processSRem(), r0(), r1(), r2(), r3(), r4(), llvm::InstrProfLookupTrait::ReadData(), llvm::InstrProfLookupTrait::ReadKey(), llvm::InstrProfLookupTrait::ReadKeyDataLength(), llvm::InstrProfLookupTrait::readValueProfilingData(), llvm::SUnit::removePred(), llvm::MCContext::reportError(), llvm::MCContext::reportWarning(), llvm::rustDemangle(), llvm::InstrProfValueSiteRecord::scale(), llvm::InstrProfRecord::scale(), scale(), llvm::DbgEntity::setDIE(), llvm::GVN::ValueTable::setDomTree(), llvm::rdf::DefNode::setReachedDef(), llvm::Value::setValueSubclassData(), simplifyICmpWithBinOp(), simplifyICmpWithMinMax(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), llvm::InstCombinerImpl::SimplifyUsingDistributiveLaws(), SolveLinEquationWithOverflow(), llvm::APIntOps::SolveQuadraticEquationWrap(), llvm::SIInstrInfo::splitFlatOffset(), llvm::stable_hash_combine(), swapAntiDependences(), llvm::swapToHostOrder(), llvm::ScaledNumberBase::toString(), toStringAPFloat(), llvm::InstCombinerImpl::tryFactorization(), llvm::json::Value::Value(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::SCEVDivision::visitConstant(), visitMaskedMerge(), llvm::InstCombinerImpl::visitOr(), llvm::InstCombinerImpl::visitXor(), and llvm::VPDef::~VPDef().
E
GCRegistry::Add< CoreCLRGC > E("coreclr", "CoreCLR-compatible GC") ("coreclr" , "CoreCLR-compatible GC") static
Referenced by llvm::OverlapStats::accumulateCounts(), llvm::InstrProfRecord::accumulateCounts(), llvm::AliasSetTracker::add(), llvm::LiveRangeUpdater::add(), addAllTypesFromDWP(), addArgumentAttrs(), llvm::FunctionSummary::addCall(), llvm::jitlink::Block::addEdge(), llvm::ImmutableGraphBuilder< GraphT >::addEdge(), llvm::DGNode< NodeType, EdgeType >::addEdge(), llvm::SetTheory::addExpander(), llvm::MachineFunction::addFilterTypeInfo(), llvm::RegsForValue::AddInlineAsmOperands(), llvm::MachineBasicBlock::addLiveIn(), addLiveInRegs(), llvm::LPPassManager::addLoop(), llvm::AMDGPURegisterBankInfo::addMappingFromTable(), addMask(), llvm::MCContext::addMCGenDwarfLabelEntry(), addModuleFlags(), llvm::ilist_callback_traits< MachineBasicBlock >::addNodeToList(), llvm::PressureDiff::addPressureChange(), llvm::InstrProfSummaryBuilder::addRecord(), addRegionIntoQueue(), addRegionIntoQueue(), llvm::LiveRegUnits::addRegsInMask(), llvm::LazyCallGraph::addSplitFunction(), llvm::LazyCallGraph::addSplitRefRecursiveFunctions(), llvm::WebAssemblyException::addSubException(), llvm::opt::OptTable::addValues(), llvm::ScheduleDAGInstrs::addVRegDefDeps(), adjustForFNeg(), adjustForLTGFR(), adjustForSubtraction(), llvm::GCNSubtarget::adjustSchedDependency(), advanceToMetaBlock(), llvm::AliasSet::aliasesPointer(), llvm::AliasSet::aliasesUnknownInst(), llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >::allocate(), llvm::RegAllocBase::allocatePhysRegs(), llvm::BasicTTIImplBase< T >::allowsMisalignedMemoryAccesses(), allPhiOperandsUndefined(), allSameBlock(), allSGPRSpillsAreDead(), allStackObjectsAreDead(), llvm::BitcodeAnalyzer::analyze(), llvm::CCState::AnalyzeArgumentsSecondPass(), llvm::SIInstrInfo::analyzeBranch(), llvm::X86InstrInfo::analyzeBranchPredicate(), llvm::AIXCCState::AnalyzeCallOperands(), llvm::InterleavedAccessInfo::analyzeInterleaving(), annotateAllFunctions(), llvm::orc::shared::TrivialSPSSequenceDeserialization< SPSElementTagT, std::vector< T > >::append(), llvm::ErrorHandlerTraits< Error(&)(ErrT &)>::appliesTo(), llvm::ErrorHandlerTraits< void(&)(ErrT &)>::appliesTo(), llvm::ErrorHandlerTraits< Error(&)(std::unique_ptr< ErrT >)>::appliesTo(), llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>::appliesTo(), llvm::ErrorHandlerTraits< Error(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< void(&)(ErrT &)>::apply(), llvm::ErrorHandlerTraits< Error(&)(std::unique_ptr< ErrT >)>::apply(), llvm::ErrorHandlerTraits< void(&)(std::unique_ptr< ErrT >)>::apply(), llvm::HexagonSubtarget::UsrOverflowMutation::apply(), llvm::jitlink::x86_64::applyFixup(), llvm::AMDGPURegisterBankInfo::applyMappingImpl(), llvm::object::Archive::Archive(), llvm::RecurrenceDescriptor::areAllUsesIn(), llvm::SDNode::areOnlyUsersOf(), llvm::MachineFunction::assignBeginEndSections(), llvm::SelectionDAG::AssignTopologicalOrder(), llvm::VarStreamArray< ValueType, Extractor >::at(), llvm::VarStreamArray< ValueType, Extractor >::begin(), llvm::SUnit::biasCriticalPath(), llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), llvm::CriticalAntiDepBreaker::BreakAntiDependencies(), llvm::rdf::DataFlowGraph::build(), buildAttrMap(), llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), llvm::FileCheck::buildCheckPrefixRegex(), llvm::CFGMST< Edge, BBInfo >::buildEdges(), llvm::coro::Shape::buildFrom(), llvm::DICompositeType::buildODRType(), llvm::RISCVInstrInfo::buildOutlinedFrame(), llvm::LazyCallGraph::buildRefSCCs(), llvm::SITargetLowering::bundleInstWithWaitcnt(), llvm::VirtRegAuxInfo::calculateSpillWeightsAndHints(), llvm::Interpreter::callFunction(), llvm::EHStreamer::callToNoUnwindFunction(), canFallThroughTo(), llvm::AAResults::canInstructionRangeModRef(), llvm::canReplaceOperandWithVariable(), llvm::ResourceManager::canReserveResources(), llvm::PPCTTIImpl::canSaveCmp(), canSplitPredecessors(), llvm::cantFail(), llvm::cantFail(), canUseSiblingCall(), CasesAreContiguous(), CC_AIX(), llvm::FileCheckString::Check(), llvm::mca::ResourceManager::checkAvailability(), llvm::FileCheckString::CheckDag(), checkEFLAGSLive(), checkFunctionMemoryAccess(), llvm::SSAUpdaterImpl< UpdaterT >::CheckIfPHIMatches(), llvm::FileCheckString::CheckNot(), checkOverlappingElement(), checkRegOnlyPHIInputs(), llvm::CallLowering::checkReturn(), llvm::vfs::RedirectingFileSystem::DirectoryEntry::classof(), llvm::vfs::RedirectingFileSystem::RemapEntry::classof(), llvm::vfs::RedirectingFileSystem::DirectoryRemapEntry::classof(), llvm::vfs::RedirectingFileSystem::FileEntry::classof(), llvm::GVNExpression::DeadExpression::classof(), llvm::MCConstantExpr::classof(), llvm::MCSymbolRefExpr::classof(), llvm::MCUnaryExpr::classof(), llvm::MCBinaryExpr::classof(), llvm::MCTargetExpr::classof(), llvm::AArch64MCExpr::classof(), llvm::ARMMCExpr::classof(), llvm::AVRMCExpr::classof(), llvm::CSKYMCExpr::classof(), llvm::LanaiMCExpr::classof(), llvm::MipsMCExpr::classof(), llvm::NVPTXFloatMCExpr::classof(), llvm::NVPTXGenericMCSymbolRefExpr::classof(), llvm::PPCMCExpr::classof(), llvm::RISCVMCExpr::classof(), llvm::SparcMCExpr::classof(), llvm::VEMCExpr::classof(), llvm::X86MCExpr::classof(), llvm::HexagonMCExpr::classof(), cleanup(), CleanupPointerRootUsers(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::StringMap< ValueTy, AllocatorTy >::clear(), llvm::orc::SymbolStringPool::clearDeadEntries(), llvm::MCSubtargetInfo::ClearFeatureBitsTransitively(), llvm::X86_MC::X86MCInstrAnalysis::clearsSuperRegisters(), llvm::CloneAndPruneIntoFromInst(), llvm::cloneLoop(), llvm::CloneModule(), llvm::collectPGOFuncNameStrings(), llvm::Combiner::combineMachineInstrs(), combineWeightsBySorting(), llvm::codeview::DebugInlineeLinesSubsection::commit(), llvm::pdb::InfoStreamBuilder::commit(), llvm::pdb::DbiModuleDescriptorBuilder::commitSymbolStream(), llvm::StringRef::compare_numeric(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::compareDomSet(), llvm::DominanceFrontierBase< BasicBlock, false >::compareDomSet(), llvm::ImutAVLFactory< ImutInfo >::compareTreeWithSection(), computeAddrMap(), llvm::mca::computeBlockRThroughput(), llvm::AccelTableBase::computeBucketCount(), llvm::rdf::Liveness::computeLiveIns(), computeMemberData(), llvm::computeMinimumValueSizes(), llvm::EHStreamer::computePadMap(), llvm::mca::computeProcResourceMasks(), llvm::object::computeSymbolSizes(), llvm::RuntimeDyldImpl::computeTotalAllocSize(), llvm::computeValueLLTs(), llvm::DirectedGraph< NodeType, EdgeType >::connect(), llvm::ConstantAggregate::ConstantAggregate(), llvm::ConstantAggrKeyType< ConstantClass >::ConstantAggrKeyType(), llvm::ConstantExprKeyType::ConstantExprKeyType(), ConstantFold(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldGetElementPtr(), llvm::ConstantFoldLoadFromConstPtr(), ConstantPropUsersOf(), ConstructLoadOperandConstant(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::contains(), llvm::HexagonBlockRanges::IndexRange::contains(), llvm::ImmutableList< T >::contains(), llvm::LiveRange::Segment::containsInterval(), llvm::MIRPrinter::convert(), llvm::SIInstrInfo::convertNonUniformLoopRegion(), llvm::MIRPrinter::convertStackObjects(), convertToRelativeLookupTables(), llvm::convertUTF16ToUTF8String(), llvm::GlobalObject::copyMetadata(), llvm::StackProtector::copyToMachineFrameInfo(), llvm::vfs::RedirectingFileSystem::create(), llvm::InstrProfSymtab::create(), llvm::symbolize::SymbolizableObjectFile::create(), llvm::InstrProfReader::create(), llvm::IndexedInstrProfReader::create(), llvm::object::COFFObjectFile::create(), llvm::object::ELFObjectFile< ELFT >::create(), llvm::InstrProfSymtab::create(), llvm::sampleprof::SampleProfileReaderItaniumRemapper::create(), llvm::InstrProfReader::create(), llvm::IndexedInstrProfReader::create(), llvm::AllocationOrder::create(), llvm::remarks::createBitstreamParserFromMeta(), createBSWAPShuffleMask(), createCast(), llvm::coverage::BinaryCoverageReader::createCoverageReaderFromBuffer(), llvm::DDGBuilder::createDefUseEdge(), createError(), createError(), llvm::pdb::DIASession::createFromPdb(), llvm::AbstractDependenceGraphBuilder< GraphType >::createMemoryDependencyEdges(), llvm::DDGBuilder::createMemoryEdge(), createPtr(), llvm::DDGBuilder::createRootedEdge(), llvm::MDBuilder::createTBAATypeNode(), createTuple(), cse(), llvm::mca::InOrderIssueStage::cycleStart(), llvm::RecyclingAllocator< AllocatorType, T, Size, Align >::Deallocate(), DeleteBasicBlock(), llvm::deleteDeadLoop(), llvm::DenseMap< KeyT, ValueT, KeyInfoT, BucketT >::DenseMap(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::DenseSetImpl(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReleaseOrFinalizeMemRequestElement >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReserveMemRequestElement >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReserveMemResultElement >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::vector< T > >::deserialize(), llvm::orc::shared::SerializationTraits< ChannelT, WrapperFunctionResult, WrapperFunctionResult, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::deserialize(), llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >::deserialize(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSElementTagT >, SequenceT, std::enable_if_t< TrivialSPSSequenceSerialization< SPSElementTagT, SequenceT >::available > >::deserialize(), llvm::SmallVectorTemplateBase< T, bool >::destroy_range(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::destroyAll(), llvm::SpecificBumpPtrAllocator< T >::DestroyAll(), llvm::AbstractDependenceGraphBuilder< GraphType >::destroyEdge(), determineSVEStackObjectOffsets(), llvm::DGNode< NodeType, EdgeType >::DGNode(), llvm::PBQP::Graph< SolverT >::disconnectEdge(), llvm::DistributeRange(), llvm::dlltoolDriverMain(), llvm::AsmPrinter::doFinalization(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::DominatorTree::dominates(), llvm::DominatorTree::dominates(), doPromotion(), llvm::MDNode::dropAllReferences(), llvm::VPBasicBlock::dropAllReferences(), llvm::SDNode::DropOperands(), llvm::DbgValueHistoryMap::dump(), llvm::mca::RegisterFile::dump(), llvm::ForeachLoop::dump(), llvm::MultiClass::dump(), llvm::coverage::CounterMappingContext::dump(), llvm::jitlink::LinkGraph::dump(), llvm::DWARFDebugMacro::dump(), llvm::DWARFDebugPubTable::dump(), llvm::DWARFContext::dump(), llvm::ScaledNumberBase::dump(), false::dump_node_container(), dumpEdges(), llvm::vfs::RedirectingFileSystem::dumpEntry(), llvm::DWARFLocationTable::dumpLocationList(), dumpLoclistsSection(), dumpMachineInstrRangeWithSlotIndex(), dumpSpills(), llvm::GraphTraits< const CallGraphNode * >::edge_dest(), llvm::GraphTraits< ValueInfo >::edge_dest(), llvm::GraphTraits< ImmutableGraph< NodeValueT, EdgeValueT > * >::edge_dest(), eliminateConstraints(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::DwarfStringPool::emit(), llvm::MCDwarfFrameEmitter::Emit(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::TargetLoweringObjectFile::emitCGProfileMetadata(), emitDirectiveRelocJalr(), llvm::EHStreamer::emitExceptionTable(), emitGlobalConstantDataSequential(), llvm::MipsAsmPrinter::emitInstruction(), llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::CodeViewContext::emitLineTableForFunction(), emitLocList(), llvm::TargetLoweringObjectFileMachO::emitModuleMetadata(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::WebAssemblyAsmPrinter::EmitProducerInfo(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::AVRFrameLowering::emitPrologue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::RuntimeDyldImpl::emitSection(), emitSelectPseudo(), llvm::EHStreamer::emitTypeInfos(), llvm::MCStreamer::EmitWinCFIEndProc(), llvm::ARMAsmPrinter::emitXXStructor(), llvm::LazyCallGraph::EdgeSequence::empty(), llvm::WinEH::FrameInfo::empty(), llvm::MCDwarfFrameEmitter::EncodeAdvanceLoc(), llvm::CodeViewContext::encodeDefRange(), llvm::PPCMCCodeEmitter::encodeInstruction(), llvm::TimeTraceProfiler::end(), llvm::VarStreamArray< ValueType, Extractor >::end(), llvm::SparseMultiSet< ValueT, KeyFunctorT, SparseT >::equal_range(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::erase(), llvm::SmallSet< T, N, C >::erase(), llvm::SmallVectorImpl< T >::erase(), llvm::MachineBasicBlock::erase(), llvm::TypeFinder::erase(), llvm::TinyPtrVector< EltTy >::erase(), llvm::PriorityWorklist< T, VectorT, MapT >::erase_if(), llvm::objcarc::BundledRetainClaimRVs::eraseInst(), llvm::remarks::YAMLRemarkParser::error(), llvm::InstrProfReader::error(), EstimateRuntime(), llvm::coverage::CounterMappingContext::evaluate(), EvaluateCRExpr(), llvm::Evaluator::EvaluateFunction(), llvm::execMayBeModifiedBeforeUse(), llvm::mca::InOrderIssueStage::execute(), llvm::mca::InstructionTables::execute(), llvm::expectedToErrorOr(), llvm::expectedToOptional(), llvm::object::MachOObjectFile::exports(), llvm::ModuleSummaryIndex::exportToDot(), llvm::BitTracker::MachineEvaluator::eXTR(), llvm::DWARFDebugNames::NameIndex::extract(), llvm::DWARFDebugNames::extract(), llvm::BitTracker::RegisterCell::extract(), llvm::DWARFDebugNames::Header::extract(), llvm::DWARFListTableBase< DWARFListType >::extract(), llvm::DWARFListType< ListEntryType >::extract(), extractConstantWithoutWrapping(), extractValues(), fatalOpenError(), llvm::LegalizerHelper::fewerElementsVectorMerge(), llvm::LegalizerHelper::fewerElementsVectorMultiEltType(), llvm::LegalizerHelper::fewerElementsVectorPhi(), llvm::BitTracker::RegisterCell::fill(), llvm::opt::ArgList::filtered(), llvm::opt::ArgList::filtered_reverse(), llvm::DIBuilder::finalize(), llvm::AccelTableBase::finalize(), llvm::pdb::GSIHashStreamBuilder::finalizeBuckets(), llvm::finalizeBundle(), llvm::MCWinCOFFStreamer::finalizeCGProfile(), llvm::SITargetLowering::finalizeLowering(), llvm::SMSchedule::finalizeSchedule(), llvm::SmallPtrSetImplBase::find_imp(), llvm::CodeExtractor::findAllocas(), findArrayDimensionsRec(), llvm::SSAUpdaterImpl< UpdaterT >::FindAvailableVals(), llvm::opt::OptTable::findByPrefix(), findCommonType(), llvm::X86RegisterInfo::findDeadCallerSavedReg(), llvm::SSAUpdaterImpl< UpdaterT >::FindDominators(), llvm::DGNode< NodeType, EdgeType >::findEdgesTo(), llvm::DGNode< NodeType, EdgeType >::findEdgeTo(), findExecCopy(), llvm::SSAUpdaterImpl< UpdaterT >::FindExistingPHI(), findGlueUse(), findIBRPredecessor(), findInitTrampolineFromBB(), findIrreducibleHeaders(), FindLastAluClause(), llvm::pdb::SymbolCache::findLineNumbersByVA(), llvm::DWARFListTableBase< DWARFListType >::findList(), llvm::HexagonInstrInfo::findLoopInstr(), llvm::MCJIT::findModuleForSymbol(), findPartitions(), llvm::findPHICopyInsertPoint(), llvm::SSAUpdaterImpl< UpdaterT >::FindPHIPlacement(), findPotentialBlockers(), llvm::SSAUpdaterTraits< LDVSSAUpdater >::FindPredecessorBlocks(), llvm::DWARFUnit::findRnglistFromOffset(), llvm::slpvectorizer::BoUpSLP::findRootOrder(), findSafeStoreForStoreStrongContraction(), findStrip(), findUser(), first_use_of_in_block(), firstCommonClass(), llvm::MipsMCExpr::fixELFSymbolsInTLSFixups(), llvm::InnerLoopVectorizer::fixReduction(), llvm::fixStackStores(), fixTerminators(), llvm::PPCInstrInfo::fixupIsDeadOrKill(), fixupOrderingIndices(), foldGEPOfGEP(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), foldLogOpOfMaskedICmpsAsymmetric(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), llvm::format_provider< Enum, std::enable_if_t< dwarf::EnumTraits< Enum >::value > >::format(), llvm::format_provider< llvm::json::Value >::format(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), llvm::json::fromJSON(), gatherFileIDs(), llvm::MipsInstrInfo::genInstrWithNewOpc(), llvm::ImmutableGraphBuilder< GraphT >::get(), llvm::AttributeList::get(), llvm::VarListElementInit::get(), llvm::DWARFDebugRangeList::getAbsoluteRanges(), llvm::DWARFDebugRnglist::getAbsoluteRanges(), getAccelTable(), llvm::SelectionDAG::getAddrSpaceCast(), llvm::rdf::Liveness::getAllReachingDefs(), llvm::SelectionDAG::getAssertAlign(), llvm::AttributeSetNode::getAsString(), llvm::SelectionDAG::getAtomic(), llvm::getAttributeBasedInliningDecision(), llvm::object::COFFObjectFile::getAuxSymbol(), llvm::SelectionDAG::getBasicBlock(), llvm::MemoryPhi::getBasicBlockIndex(), llvm::getBitcodeFileContents(), llvm::SelectionDAG::getBlockAddress(), llvm::object::ELFObjectFile< ELFT >::getBuildAttributes(), getBundledUseMI(), llvm::DebugLocStream::getBytes(), llvm::objcarc::GetCallSiteClass(), llvm::getCallsiteCost(), llvm::DebugLocStream::getComments(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::object::ResourceSectionRef::getContents(), llvm::TargetRegisterInfo::getCoveringSubRegIndexes(), getDataDeps(), llvm::DWARFContext::getDebugFrame(), llvm::object::COFFObjectFile::getDebugPDBInfo(), llvm::AMDGPURegisterBankInfo::getDefaultMappingAllVGPR(), llvm::PPCInstrInfo::getDefMIPostRA(), llvm::object::ExportDirectoryEntryRef::getDllName(), getEarliestInsertPos(), llvm::DOTGraphTraits< const DataDependenceGraph * >::getEdgeAttributes(), llvm::DOTGraphTraits< MachineGadgetGraph * >::getEdgeAttributes(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::getEdgeIndex(), llvm::PBQP::Graph< SolverT >::getEdgeOtherNodeId(), llvm::BranchProbabilityInfo::getEdgeProbability(), llvm::DWARFContext::getEHFrame(), getEmscriptenInvokeSymbolName(), llvm::BitstreamEntry::getEndBlock(), llvm::MachineTraceMetrics::getEnsemble(), llvm::NonRelocatableStringpool::getEntriesForEmission(), llvm::DWARFDebugNames::NameIndex::getEntry(), llvm::objcarc::getEquivalentPHIs(), llvm::BitstreamEntry::getError(), llvm::ConstantExpr::getExactLogBase2(), llvm::SystemZConstantPoolValue::getExistingMachineCPValue(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), getExprBase(), llvm::PseudoSourceValueManager::getExternalSymbolCallEntry(), getExtractIndex(), llvm::VarStreamArray< ValueType, Extractor >::getExtractor(), llvm::VarStreamArray< ValueType, Extractor >::getExtractor(), llvm::MachineBasicBlock::getFirstInstrTerminator(), llvm::MachineBasicBlock::getFirstNonPHI(), getFirstReloc(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::jitlink::Block::getFixupAddress(), llvm::MCSchedModel::getForwardingDelayCycles(), llvm::SelectionDAG::getFrameIndex(), llvm::DWARFUnitIndex::getFromOffset(), llvm::IndexedInstrProfReader::getFunctionCounts(), llvm::SelectionDAG::getGlobalAddress(), llvm::ExecutionEngine::getGlobalValueAtAddress(), llvm::PseudoSourceValueManager::getGlobalValueCallEntry(), getHashForUdt(), llvm::DenseMapInfo< const Expression * >::getHashValue(), llvm::DenseMapInfo< const Expression * >::getHashValue(), llvm::IRSimilarity::IRInstructionDataTraits::getHashValue(), llvm::ScoreboardHazardRecognizer::getHazardType(), llvm::object::COFFObjectFile::getHintName(), llvm::sys::detail::getHostCPUNameForARM(), llvm::sys::detail::getHostCPUNameForS390x(), llvm::object::DelayImportDirectoryEntryRef::getImportAddress(), llvm::SlotIndexes::getIndexAfter(), llvm::SelectionDAG::getIndexedStore(), getInputSegmentList(), getInsertPt(), llvm::SIInstrInfo::getInstBundleSize(), getInstrBB(), llvm::SIInstrInfo::getInstrLatency(), llvm::AMDGPURegisterBankInfo::getInstrMapping(), llvm::IndexedInstrProfReader::getInstrProfRecord(), llvm::SelectionDAG::getJumpTable(), llvm::SelectionDAG::getLabelNode(), getLatestInsertPos(), llvm::getLazyIRModule(), llvm::SelectionDAG::getLifetimeNode(), GetLinearExpression(), getLiveInRegsAt(), getLiveOutRegsAt(), llvm::getLiveRegMap(), llvm::getLiveRegs(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMaskedGather(), llvm::SelectionDAG::getMaskedLoad(), llvm::SelectionDAG::getMaskedScatter(), llvm::SelectionDAG::getMaskedStore(), getMaskedTypeForICmpPair(), getMaxCalleeSavedReg(), llvm::coverage::CounterMappingContext::getMaxCounterID(), llvm::M68kRegisterInfo::getMaximalPhysRegClass(), llvm::LLVMContext::getMDKindNames(), llvm::SelectionDAG::getMDNode(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::object::ImportDirectoryEntryRef::getName(), llvm::object::DelayImportDirectoryEntryRef::getName(), llvm::rdf::Liveness::getNearestAliasedRef(), getNextBlock(), getNextMachineInstrInBB(), llvm::SlotIndexes::getNextNonNullIndex(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNode(), llvm::BFIDOTGraphTraitsBase< BlockFrequencyInfoT, BranchProbabilityInfoT >::getNodeAttributes(), llvm::SelectionDAG::getNodeIfExists(), getNonDebugInstr(), getNumberOfRelocations(), llvm::EquivalenceClasses< ElemTy >::getNumClasses(), llvm::MachineInstr::getNumExplicitDefs(), llvm::MachineInstr::getNumExplicitOperands(), llvm::ARMBaseInstrInfo::getNumLDMAddresses(), getObject(), llvm::object::getObject(), llvm::TargetTransformInfo::getOperandInfo(), llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead(), llvm::DwarfExpression::getOrCreateBaseType(), llvm::FoldingSetBase::GetOrInsertNode(), getOrSelfReference(), llvm::RISCVInstrInfo::getOutliningCandidateInfo(), getOutputSegmentMap(), getPdbPathFromExe(), llvm::SelectionDAG::getPseudoProbeNode(), llvm::MCSubtargetInfo::getReadAdvanceCycles(), llvm::MCSchedModel::getReciprocalThroughput(), llvm::MCSchedModel::getReciprocalThroughput(), llvm::BitstreamEntry::getRecord(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::getRecords(), llvm::SelectionDAG::getRegister(), llvm::MipsMCCodeEmitter::getRegisterListOpValue(), llvm::SelectionDAG::getRegisterMask(), llvm::RegsForValue::getRegsAndSizes(), getRegSeqInit(), llvm::getRegSequenceSubReg(), llvm::DWARFDataExtractor::getRelocatedValue(), llvm::CCState::getRemainingRegParmsForType(), llvm::R600RegisterInfo::getReservedRegs(), llvm::jitlink::getRISCVPCRelHi20(), getSameOpcode(), getSavedReg(), llvm::object::COFFObjectFile::getSectionContents(), llvm::object::COFFObjectFile::getSectionContents(), llvm::object::ELFObjectFile< ELFT >::getSectionContents(), llvm::BasicBlock::getSinglePredecessor(), llvm::BasicBlock::getSingleSuccessor(), getSourceLineHash(), llvm::X86InstrInfo::getSPAdjust(), llvm::ConstantVector::getSplatValue(), llvm::SelectionDAG::getSrcValue(), llvm::InstrItineraryData::getStageLatency(), llvm::SelectionDAG::getStore(), GetStringLengthH(), llvm::object::ELFFile< ELFT >::getStringTable(), llvm::BitstreamEntry::getSubBlock(), llvm::object::ExportDirectoryEntryRef::getSymbolName(), getSymbols(), llvm::IndexedInstrProfReader::getSymtab(), getTagRecordHashForUdt(), llvm::SelectionDAG::getTargetIndex(), getTargetMBB(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::getTotalMemory(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::SelectionDAG::getTruncStore(), llvm::BasicBlock::getUniquePredecessor(), llvm::BasicBlock::getUniqueSuccessor(), llvm::DWARFUnitVector::getUnitForIndexEntry(), getUnmergePieces(), getUUID(), getVDefInterval(), llvm::slpvectorizer::BoUpSLP::getVectorElementSize(), llvm::SelectionDAG::getVectorShuffle(), llvm::object::ELFFile< ELFT >::getVersionDependencies(), getWaitStatesSince(), llvm::GlobalsMetadata::GlobalsMetadata(), llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::grow(), llvm::handleAllErrors(), llvm::handleAllErrors(), HandleCallsInBlockInlinedThroughInvoke(), handleCompressedSection(), llvm::AMDGPURegisterBankInfo::handleD16VData(), llvm::AMDGPULegalizerInfo::handleD16VData(), llvm::handleExecNameEncodedBEOpts(), llvm::handleExecNameEncodedOptimizerOpts(), HandleInlinedEHPad(), HandleInlinedLandingPad(), handleMaybeNoDataFoundError(), llvm::LiveIntervals::handleMoveIntoNewBundle(), llvm::GEPOperator::hasAllConstantIndices(), llvm::GEPOperator::hasAllZeroIndices(), hasAnyUnrollPragma(), llvm::SDNode::hasAnyUseOfValue(), llvm::AttributeListImpl::hasAttrSomewhere(), llvm::MachineInstr::hasComplexRegisterTies(), llvm::MachineBasicBlock::hasEHPadSuccessor(), llvm::BitCodeAbbrevOp::hasEncodingData(), llvm::Constant::hasExactInverseFP(), hasField(), llvm::ItaniumPartialDemangler::hasFunctionQualifiers(), llvm::MachineInstr::hasImplicitDef(), hasLiveThroughUse(), llvm::coverage::InstantiationGroup::hasName(), HasNestArgument(), llvm::SDNode::hasNUsesOfValue(), hasOnlyUniformBranches(), hasProfileData(), hasReturn(), hasReturnsTwiceAttr(), hasRVVFrameObject(), llvm::hasSingleElement(), llvm::HexagonInstrInfo::hasUncondBranch(), hasUseAfterLoop(), haveSameOperands(), llvm::HexagonAsmPrinter::HexagonProcessInstruction(), hoistAndMergeSGPRInits(), llvm::SCEVExpander::hoistIVInc(), llvm::hoistRegion(), llvm::Attributor::identifyDefaultAbstractAttributes(), llvm::BumpPtrAllocatorImpl< AllocatorT, SlabSize, SizeThreshold, GrowthDelay >::identifyObject(), indirectCopyToAGPR(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::initEmpty(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS(), llvm::DbgVariable::initializeDbgValue(), llvm::DbgVariable::initializeDbgValue(), llvm::DbgVariable::initializeMMI(), llvm::mca::initializeUsedResources(), initializeWorkList(), llvm::ResourceManager::initProcResourceVectors(), llvm::ScheduleDAGMI::initQueues(), llvm::InlineFunction(), llvm::ImmutableGraph< NodeValueT, EdgeValueT >::EdgeSet::insert(), llvm::BitTracker::RegisterCell::insert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::detail::DenseSetImpl< ValueT, MapTy, ValueInfoT >::insert(), llvm::ValueMap< KeyT, ValueT, Config >::insert(), llvm::MachineBasicBlock::insert(), llvm::json::Array::insert(), llvm::json::Array::insert(), llvm::NodeSet::insert(), llvm::SmallPtrSetImpl< PtrType >::insert(), llvm::SmallSet< T, N, C >::insert(), llvm::json::Object::insert(), llvm::SmallPtrSetImplBase::insert_imp(), llvm::LazyCallGraph::RefSCC::insertIncomingRefEdge(), llvm::LiveIntervals::InsertMachineInstrRangeInMaps(), insertNoDuplicates(), insertSpills(), llvm::LazyCallGraph::RefSCC::insertTrivialCallEdge(), insertValues(), interChangeDependencies(), interleaveIntList(), interleaveStringList(), llvm::IntervalPartition::IntervalPartition(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::invalidate(), llvm::inversePermutation(), invert_find_roots(), llvm::LazyCallGraph::RefSCC::isAncestorOf(), llvm::LazyCallGraph::SCC::isAncestorOf(), llvm::mca::RegisterFile::isAvailable(), isBlock(), isBlockValidForExtraction(), llvm::isBytewiseValue(), llvm::SITargetLowering::isCanonicalized(), llvm::SITargetLowering::isCanonicalized(), isConcatMask(), isCondRelevantToAnyCallArgument(), llvm::isCriticalEdge(), llvm::ArgumentPromotionPass::isDenselyPacked(), llvm::HexagonTargetLowering::IsEligibleForTailCallOptimization(), isEphemeralValueOf(), llvm::DGEdge< NodeType, EdgeType >::isEqualTo(), llvm::X86MCExpr::isEqualTo(), isError(), llvm::Constant::isFiniteNonZeroFP(), isFNEG(), llvm::ConstantExpr::isGEPWithNoNotionalOverIndexing(), isIdentity(), isInput(), isKnownNonNaN(), isKnownNonZero(), llvm::isKnownToBeAPowerOfTwo(), llvm::SelectionDAG::isKnownToBeAPowerOfTwo(), llvm::ARM_MC::isLDMBaseRegInList(), isLeakCheckerRoot(), llvm::R600InstrInfo::isLegalToSplitMBBAt(), isLRAvailable(), llvm::Constant::isNaN(), llvm::Constant::isNormalFP(), llvm::Constant::isNotMinSignedValue(), llvm::Constant::isNotOneValue(), isOnlyReachableViaThisEdge(), llvm::SDNode::isOnlyUserOf(), llvm::LazyCallGraph::RefSCC::isParentOf(), llvm::LazyCallGraph::SCC::isParentOf(), isPoisonShift(), llvm::ARMBaseInstrInfo::isPredicated(), isProfitableToInterleave(), isRematerializable(), IsSafeAndProfitableToMove(), isSafeAndProfitableToSinkLoad(), isSafeSROAGEP(), llvm::ReachingDefAnalysis::isSafeToDefRegAt(), llvm::isSafeToLoadUnconditionally(), isSafeToMove(), llvm::ReachingDefAnalysis::isSafeToMoveBackwards(), llvm::ReachingDefAnalysis::isSafeToMoveForwards(), isScalarToVector(), isShuffle(), llvm::PPCInstrInfo::isSignOrZeroExtended(), isSSA(), llvm::DIExpression::isValid(), llvm::LiveRange::join(), llvm::BitTracker::BitMask::last(), layout(), llvm::SelectionDAG::Legalize(), llvm::SIInstrInfo::legalizeOperands(), llvm::libDriverMain(), likeBitCastFromVector(), llvm::DWARFLinker::link(), llvm::remarks::RemarkLinker::link(), LLVMGetSectionContents(), LLVMPrintModuleToFile(), LLVMRemarkParserGetNext(), llvm::LLVMRemarkSetupErrorInfo< ThisError >::LLVMRemarkSetupErrorInfo(), llvm::coverage::CoverageMapping::load(), llvm::coverage::CoverageMapping::load(), loadBinaryFormat(), llvm::xray::loadInstrumentationMap(), loadObj(), llvm::RuntimeDyldImpl::loadObjectImpl(), llvm::xray::loadProfile(), loadTestingFormat(), llvm::xray::loadTrace(), llvm::lto::localCache(), llvm::LazyCallGraph::EdgeSequence::lookup(), llvm::vfs::lookupInMemoryNode(), llvm::vfs::RedirectingFileSystemParser::lookupOrCreateEntry(), llvm::orc::OrcRPCExecutorProcessControlBase< RPCEndpointT >::lookupSymbols(), llvm::LanaiMCInstLower::Lower(), llvm::SystemZMCInstLower::lower(), llvm::WebAssemblyMCInstLower::lower(), llvm::FastISel::lowerArguments(), LowerBUILD_VECTORAsVariablePermute(), llvm::SITargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::VETargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::FastISel::lowerCallTo(), llvm::TargetLowering::LowerCallTo(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::AMDGPUAsmPrinter::lowerConstant(), llvm::R600AsmPrinter::lowerConstant(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), llvm::AMDGPUCallLowering::lowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerFP_TO_FP16(), llvm::LegalizerHelper::lowerFPTRUNC_F64_TO_F16(), llvm::AMDGPUTargetLowering::LowerINT_TO_FP32(), lowerLoadRelative(), llvm::LanaiTargetLowering::LowerMUL(), lowerObjCCall(), llvm::TargetLowering::LowerOperationWrapper(), llvm::SITargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::LegalizerHelper::lowerU64ToF32BitOps(), llvm::AMDGPUTargetLowering::lowerUnhandledCall(), LowerVECTOR_SHUFFLEv8i8(), llvm::make_error_code(), llvm::coverage::make_error_code(), llvm::codeview::make_error_code(), llvm::pdb::make_error_code(), llvm::make_error_code(), llvm::make_error_code(), llvm::msf::make_error_code(), llvm::pdb::make_error_code(), llvm::pdb::make_error_code(), llvm::make_error_code(), llvm::make_fallible_end(), llvm::make_fallible_range(), llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >::makeSafe(), llvm::jitlink::makeTargetOutOfRangeError(), mangleCoveragePath(), llvm::json::ObjectMapper::map(), llvm::json::ObjectMapper::map(), llvm::json::ObjectMapper::mapOptional(), llvm::yaml::MappingTraits< ArchYAML::Archive::Child >::mapping(), llvm::yaml::MappingTraits< ELFYAML::ARMIndexTableEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::BBAddrMapEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::BBAddrMapEntry::BBEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::CallGraphEntryWeight >::mapping(), llvm::yaml::MappingTraits< ELFYAML::GnuHashHeader >::mapping(), llvm::yaml::MappingTraits< ELFYAML::StackSizeEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::VerdefEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::VernauxEntry >::mapping(), llvm::yaml::MappingTraits< ELFYAML::VerneedEntry >::mapping(), markAliveBlocks(), llvm::SCCPInstVisitor::markArgInFuncSpecialization(), llvm::maskIsAllOneOrUndef(), llvm::maskIsAllZeroOrUndef(), llvm::Pattern::match(), MatchDiv(), llvm::Intrinsic::matchIntrinsicSignature(), MatchMul(), MatchRem(), matchScalarInAggregate(), matchSwap(), llvm::matchUnaryPredicate(), mayLoopAccessLocation(), memOpsHaveSameBaseOperands(), llvm::InstrProfRecord::merge(), mergeConditionalStoreToAddress(), mergeConstants(), mergeInlinedArrayAllocas(), mergeOperations(), llvm::VPlanTransforms::mergeReplicateRegions(), llvm::MIBundleBuilder::MIBundleBuilder(), llvm::LegalizerHelper::moreElementsVectorPhi(), llvm::SelectionDAG::MorphNodeTo(), llvm::IRMover::move(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::moveFromOldBuckets(), moveInstrOut(), llvm::object::ExportEntry::moveNext(), llvm::object::MachORebaseEntry::moveNext(), llvm::object::MachOBindEntry::moveNext(), llvm::InjectorIRStrategy::mutate(), llvm::InstDeleterIRStrategy::mutate(), llvm::LegalizerHelper::narrowScalar(), llvm::LegalizerHelper::narrowScalarAddSub(), llvm::LegalizerHelper::narrowScalarBasic(), llvm::LegalizerHelper::narrowScalarInsert(), llvm::LegalizerHelper::narrowScalarSelect(), nearest_common_dominatee(), nearest_common_dominator(), needsFP(), llvm::remarks::BitstreamRemarkParser::next(), node_class(), llvm::SelectionDAG::DAGNodeDeletedListener::NodeDeleted(), llvm::mca::ExecuteStage::notifyReservedOrReleasedBuffers(), llvm::vfs::OverlayFileSystem::openFileForRead(), operator delete(), llvm::MDNode::operator delete(), llvm::MDNode::operator new(), llvm::DGEdge< NodeType, EdgeType >::operator!=(), llvm::BitmaskEnumDetail::operator&(), llvm::FeatureBitset::operator&=(), llvm::LessRecordRegister::operator()(), llvm::ExitOnError::operator()(), llvm::ExitOnError::operator()(), llvm::coverage::CoverageMappingIterator::operator*(), llvm::LazyCallGraph::EdgeSequence::iterator::operator++(), llvm::coverage::CoverageMappingIterator::operator->(), llvm::FeatureBitset::operator<(), llvm::operator<<(), llvm::operator<<(), llvm::GVNExpression::operator<<(), llvm::operator<<(), llvm::operator<<(), llvm::operator<<(), false::operator<<(), llvm::rdf::operator<<(), llvm::rdf::operator<<(), llvm::DDGEdge::operator=(), llvm::DGEdge< NodeType, EdgeType >::operator=(), llvm::EquivalenceClasses< ElemTy >::operator=(), llvm::DDGEdge::operator=(), llvm::ConstantAggrKeyType< ConstantClass >::operator==(), llvm::ConstantExprKeyType::operator==(), llvm::detail::operator==(), llvm::DGEdge< NodeType, EdgeType >::operator==(), llvm::operator==(), llvm::AA::PointerInfo::State::operator==(), llvm::LazyCallGraph::EdgeSequence::operator[](), llvm::BitmaskEnumDetail::operator^(), llvm::FeatureBitset::operator^=(), llvm::BitmaskEnumDetail::operator|(), llvm::FeatureBitset::operator|=(), llvm::BitmaskEnumDetail::operator~(), OptimizeAwayTrappingUsesOfLoads(), OptimizeAwayTrappingUsesOfValue(), llvm::ARMBaseInstrInfo::optimizeCompareInstr(), llvm::LanaiInstrInfo::optimizeCompareInstr(), llvm::X86InstrInfo::optimizeCompareInstr(), llvm::PPCInstrInfo::optimizeCompareInstr(), optimizeDivRem(), optimizeELF_x86_64_GOTAndStubs(), OptimizeEmptyGlobalCXXDtors(), OptimizeExtractBits(), OptimizeFunctions(), llvm::slpvectorizer::BoUpSLP::optimizeGatherSequence(), OptimizeGlobalAliases(), OptimizeGlobalVars(), optimizeMachO_x86_64_GOTAndStubs(), llvm::opt::OptTable::OptTable(), llvm::SMSchedule::orderDependence(), OtherSucc(), llvm::InstrProfRecord::overlap(), llvm::HexagonBlockRanges::IndexRange::overlaps(), packCmovGroup(), packSegmentMask(), llvm::TargetLowering::parametersInCSRMatch(), llvm::SpecialCaseList::parse(), llvm::DWARFDebugFrame::parse(), llvm::DWARFDebugLine::Prologue::parse(), llvm::json::parse(), llvm::InlineAsm::ConstraintInfo::Parse(), llvm::object::WindowsResourceParser::parse(), llvm::vfs::RedirectingFileSystemParser::parse(), parseBackslash(), parseBitcodeFileImpl(), parseBlock(), llvm::AArch64::parseBranchProtection(), llvm::InlineAsm::ParseConstraints(), AbstractManglingParser< Derived, Alloc >::parseConversionExpr(), AbstractManglingParser< Derived, Alloc >::parseDecltype(), AbstractManglingParser< Derived, Alloc >::parseExpr(), AbstractManglingParser< Derived, Alloc >::parseFunctionType(), llvm::parseIR(), parseListTableHeader(), llvm::remarks::BitstreamRemarkParser::parseMeta(), llvm::parseModule(), parsePhysicalReg(), AbstractManglingParser< Derived, Alloc >::parsePrefixExpr(), llvm::remarks::BitstreamRemarkParser::parseRemark(), llvm::remarks::YAMLRemarkParser::parseRemark(), llvm::Pattern::parseVariable(), PerformADDVecReduce(), performCopyPropagation(), llvm::AMDGPUTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::ARMTargetLowering::PerformMVEExtCombine(), llvm::performOptimizedStructLayout(), PerformTruncatingStoreCombine(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::ConvergingVLIWScheduler::pickNodeFromQueue(), llvm::LatencyPriorityQueue::pop(), llvm::ResourcePriorityQueue::pop(), llvm::InstrProfReaderItaniumRemapper< HashTableImpl >::populateRemappings(), pred_L(), predictUseListOrder(), predictValueUseListOrder(), predictValueUseListOrderImpl(), prepareICWorklistFromFunction(), llvm::PrepareToSplitEntryBlock(), llvm::RISCVDAGToDAGISel::PreprocessISelDAG(), llvm::MIPrinter::print(), llvm::MIPrinter::print(), llvm::LiveRangeUpdater::print(), llvm::VPlanIngredient::print(), llvm::LiveStacks::print(), llvm::VPBlendRecipe::print(), llvm::AliasSet::print(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::print(), llvm::LoopInfoBase< BlockT, LoopT >::print(), llvm::AccelTableBase::print(), llvm::ValueEnumerator::print(), llvm::MachineFunction::print(), llvm::ValueEnumerator::print(), llvm::MachineBasicBlock::print(), llvm::MachineOperand::print(), llvm::ScaledNumberBase::print(), llvm::WebAssemblyInstPrinter::printBrList(), llvm::printCompactDWARFExpr(), printCustomRegMask(), llvm::PrintDomTree(), llvm::jitlink::printEdge(), llvm::SampleProfileLoaderBaseImpl< BT >::printEdgeWeight(), llvm::WebAssemblyInstPrinter::printInst(), ParameterPackExpansion::printLeft(), llvm::GCNRPTracker::printLiveRegs(), llvm::printLivesAt(), printMCExpr(), printName(), printName(), printNode(), printNodeDOT(), printNoMatch(), llvm::BitcodeAnalyzer::printStats(), llvm::SIFrameLowering::processFunctionBeforeFrameFinalized(), ProcessMatchResult(), processPSInputArgs(), llvm::xray::profileFromTrace(), promoteIndirectCalls(), promoteMemoryToRegister(), llvm::propagateMetadata(), llvm::SampleProfileLoaderBaseImpl< BT >::propagateThroughEdges(), llvm::jitlink::prune(), llvm::LiveIntervals::pruneValue(), llvm::LatencyPriorityQueue::push(), llvm::SchedulingPriorityQueue::push_all(), llvm::json::Array::push_back(), llvm::json::Array::push_back(), llvm::LiveRange::Query(), r0(), r1(), r2(), r3(), r4(), llvm::support::endian::read(), llvm::support::endian::read16(), llvm::support::endian::read32(), llvm::support::endian::read64(), llvm::BitstreamCursor::ReadAbbrevRecord(), readCoverageMappingData(), llvm::AMDGPUPALMetadata::readFromIR(), llvm::IndexedInstrProfReader::readHeader(), llvm::TextInstrProfReader::readNextRecord(), llvm::RawInstrProfReader< IntPtrT >::readNextRecord(), llvm::IndexedInstrProfReader::readNextRecord(), llvm::readPGOFuncNameStrings(), llvm::R600InstrInfo::readsLDSSrcReg(), llvm::ConvergingVLIWScheduler::readyQueueVerboseDump(), llvm::PBQP::Graph< SolverT >::reconnectEdge(), llvm::SSAUpdaterImpl< UpdaterT >::RecordMatchingPHIs(), llvm::LessRecordRegister::RecordParts::RecordParts(), llvm::RecursivelyDeleteTriviallyDeadInstructionsPermissive(), reduceDbgValsBackwardScan(), llvm::LegalizerHelper::reduceLoadStoreWidth(), regIsPICBase(), registerJITLoaderGDBImpl(), llvm::StringMapImpl::RehashTable(), llvm::rdf::DataFlowGraph::releaseBlock(), llvm::ConvergingVLIWScheduler::releaseBottomNode(), llvm::SchedBoundary::releasePending(), llvm::pdb::GlobalsStream::reload(), llvm::pdb::ModuleDebugStreamRef::reload(), llvm::pdb::PublicsStream::reload(), llvm::object::XCOFFObjectFile::relocations(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::remove_if(), llvm::DominanceFrontierBase< BlockT, IsPostDom >::removeBlock(), RemoveDeadAddBetweenLEAAndJT(), llvm::FastISel::removeDeadCode(), llvm::Constant::removeDeadConstantUsers(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::PBQP::Graph< SolverT >::removeEdge(), llvm::DGNode< NodeType, EdgeType >::removeEdge(), removeExternalCFGEdges(), removeExternalCFGSuccessors(), removeGlobalCtors(), llvm::LazyCallGraph::RefSCC::removeInternalRefEdge(), removeKillInfo(), llvm::ExecutionEngine::removeModule(), llvm::DirectedGraph< NodeType, EdgeType >::removeNode(), llvm::PMDataManager::removeNotPreservedAnalysis(), removeOldExitPreds(), llvm::CallBase::removeOperandBundle(), llvm::LiveRegUnits::removeRegsNotPreserved(), llvm::MachineFunction::RenumberBlocks(), llvm::SelectionDAG::ReplaceAllUsesOfValuesWith(), llvm::VPValue::replaceAllUsesWith(), replaceConstantExprOp(), replaceDominatedUses(), llvm::PPCFrameLowering::replaceFPWithRealFP(), llvm::AVRTargetLowering::ReplaceNodeResults(), llvm::ConstantUniqueMap< ConstantClass >::replaceOperandsInPlace(), replaceRegUsesAfterLoop(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::MachineBasicBlock::replaceSuccessor(), llvm::Thumb2InstrInfo::ReplaceTailWithBranchTo(), llvm::User::replaceUsesOfWith(), llvm::Value::replaceUsesWithIf(), rescheduleCanonically(), llvm::DataLayout::reset(), llvm::BitVector::reset(), llvm::SmallBitVector::reset(), llvm::BitcodeReaderValueList::resolveConstantForwardRefs(), AbstractManglingParser< Derived, Alloc >::resolveForwardTemplateRefs(), llvm::ListInit::resolveReferences(), llvm::mca::ResourceManager::ResourceManager(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::CCState::resultsCompatible(), rewriteGEPAsOffset(), rewriteMaterializableInstructions(), RewriteUsesOfClonedInstructions(), llvm::jitlink::PerGraphGOTAndPLTStubsBuilder< BuilderImplT >::run(), llvm::AMDGPUSimplifyLibCallsPass::run(), llvm::AMDGPUUseNativeCallsPass::run(), llvm::MachineFunctionPassManager::run(), llvm::DeadArgumentEliminationPass::run(), llvm::InstrProfiling::run(), llvm::runIPSCCP(), llvm::IntervalPartition::runOnFunction(), llvm::InstructionSelect::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::InsertNOPLoad::runOnMachineFunction(), llvm::DetectRoundChange::runOnMachineFunction(), llvm::FixAllFDIVSQRT::runOnMachineFunction(), llvm::PassManager< Loop, LoopAnalysisManager, LoopStandardAnalysisResults &, LPMUpdater & >::runWithLoopNestPasses(), scalarConstantToHexString(), llvm::R600SchedStrategy::schedNode(), llvm::SIScheduleDAGMI::schedule(), llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer(), llvm::object::XCOFFObjectFile::section_rel_begin(), llvm::object::XCOFFObjectFile::section_rel_end(), llvm::LiveRange::Segment::Segment(), llvm::mca::Scheduler::select(), llvm::PPCTargetLowering::SelectAddressEVXRegReg(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::FastISel::selectGetElementPtr(), llvm::FastISel::selectStackmap(), llvm::HexagonDAGToDAGISel::SelectVAlign(), separateNestedLoop(), llvm::orc::shared::SerializationTraits< ChannelT, std::vector< T >, ArrayRef< T > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::map< K, V >, DenseMap< K2, V2 > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReleaseOrFinalizeMemRequestElement >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReserveMemRequestElement >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, orcrpctpc::ReserveMemResultElement >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::map< K, V >, std::map< K2, V2 > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::set< T >, std::set< T2 > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, std::vector< T > >::serialize(), llvm::orc::shared::SerializationTraits< ChannelT, WrapperFunctionResult, WrapperFunctionResult, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::serialize(), llvm::orc::shared::detail::ResultSerializer< SPSRetTagT, Expected< T > >::serialize(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSElementTagT >, SequenceT, std::enable_if_t< TrivialSPSSequenceSerialization< SPSElementTagT, SequenceT >::available > >::serialize(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSTuple< SPSString, SPSValueT > >, StringMap< ValueT > >::serialize(), llvm::BitVector::set(), llvm::SmallBitVector::set(), llvm::set_intersect(), llvm::object::ELFObjectFileBase::setARMSubArch(), llvm::IndexedInstrProf::Summary::setEntry(), llvm::opt::OptTable::setInitialOptionsFromEnvironment(), llvm::Module::setModuleFlag(), llvm::setupLLVMOptimizationRemarks(), llvm::setupLLVMOptimizationRemarks(), llvm::lto::setupLLVMOptimizationRemarks(), llvm::RecordVal::setValue(), llvm::RecordVal::setValue(), llvm::HexagonRegisterInfo::shouldCoalesce(), llvm::AbstractDependenceGraphBuilder< GraphType >::simplify(), llvm::InstCombinerImpl::SimplifyDemandedVectorElts(), SimplifyFunction(), llvm::SimplifyInstructionsInBlock(), llvm::simplifyLoopAfterUnroll(), simplifyOneLoop(), llvm::InstCombinerImpl::SimplifySelectsFeedingBinaryOp(), sinkAndCmp0Expression(), SinkCast(), sinkCmpExpression(), sinkLastInstruction(), sinkLoopInvariantInstructions(), llvm::SIRegisterInfo::SIRegisterInfo(), llvm::rdf::DataFlowGraph::DefStack::size(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSElementTagT >, SequenceT, std::enable_if_t< TrivialSPSSequenceSerialization< SPSElementTagT, SequenceT >::available > >::size(), llvm::orc::shared::SPSSerializationTraits< SPSSequence< SPSTuple< SPSString, SPSValueT > >, StringMap< ValueT > >::size(), llvm::MachineBasicBlock::SkipPHIsAndLabels(), llvm::MachineBasicBlock::SkipPHIsLabelsAndDebug(), llvm::SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT, BucketT >::SmallDenseMap(), llvm::SmallPtrSet< PtrType, SmallSize >::SmallPtrSet(), llvm::SmallVector< T, N >::SmallVector(), sortBlocks(), sortOpts(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::MachineBasicBlock::splitAt(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::SplitIndirectBrCriticalEdges(), splitRetconCoroutine(), llvm::StackMapParser< Endianness >::StackMapParser(), llvm::sys::path::starts_with(), llvm::vfs::OverlayFileSystem::status(), llvm::StringMap< ValueTy, AllocatorTy >::StringMap(), stripDeadPrototypes(), llvm::VarStreamArray< ValueType, Extractor >::substream(), succ_L(), llvm::opt::OptTable::suggestValueCompletions(), sumEdgeCount(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToCall(), llvm::LazyCallGraph::RefSCC::switchInternalEdgeToRef(), SwitchToLookupTable(), llvm::SystemZFrameLowering::SystemZFrameLowering(), llvm::TailDuplicator::tailDuplicateBlocks(), llvm::InstrProfError::take(), llvm::SoftInstrProfErrors::takeError(), llvm::cl::TokenizeGNUCommandLine(), tokenizeWindowsCommandLineImpl(), llvm::object::ELFFile< ELFT >::toMappedAddr(), llvm::orc::shared::detail::toSPSSerializable(), llvm::toString(), llvm::detail::IEEEFloat::toString(), llvm::AMDGPUPALMetadata::toString(), llvm::ScaledNumberBase::toString(), toStringAPFloat(), transferSRADebugInfo(), llvm::ImmutableGraphBuilder< GraphT >::trim(), llvm::mca::RegisterFile::tryEliminateMoveOrSwap(), tryToFoldACImm(), TryToMergeLandingPad(), TryToShrinkGlobalToBoolean(), TryToSinkInstruction(), llvm::JumpThreadingPass::tryToUnfoldSelect(), llvm::JumpThreadingPass::tryToUnfoldSelect(), llvm::SmallVectorTemplateBase< T, bool >::uninitialized_copy(), llvm::SmallVectorTemplateBase< T, true >::uninitialized_copy(), llvm::SmallVectorTemplateBase< T, true >::uninitialized_copy(), llvm::SmallVectorTemplateBase< T, bool >::uninitialized_move(), llvm::SmallVectorTemplateBase< T, true >::uninitialized_move(), llvm::MemoryPhi::unorderedDeleteIncoming(), llvm::MemoryPhi::unorderedDeleteIncomingIf(), llvm::HexagonPacketizerList::unpacketizeSoloInstrs(), unstackifyVRegsUsedInSplitBB(), llvm::unwrap(), UpdateCallGraphAfterInlining(), updateCGAndAnalysisManagerForPass(), llvm::MemorySSAUpdater::updateForClonedLoop(), llvm::BlockFrequencyInfoImplBase::updateLoopWithIrreducible(), llvm::MemorySSAUpdater::updatePhisWhenInsertingUniqueBackedgeBlock(), updatePhysDepsUpwards(), upgrade(), llvm::UpgradeARCRuntime(), upgradeLoopArgument(), llvm::UpgradeModuleFlags(), uses(), llvm::yaml::MappingTraits< std::unique_ptr< ELFYAML::Chunk > >::validate(), llvm::json::OStream::value(), values(), VectorizePTXValueVTs(), llvm::slpvectorizer::BoUpSLP::vectorizeTree(), llvm::LiveRange::verify(), llvm::LoopInfoBase< BlockT, LoopT >::verify(), llvm::SIInstrInfo::verifyInstruction(), llvm::SystemZInstrInfo::verifyInstruction(), llvm::LoopBase< BlockT, LoopT >::verifyLoopNest(), llvm::mca::verifyOperands(), llvm::MemorySSA::verifyOrderingDominationAndDefUses(), VerifyPHIs(), llvm::MemorySSA::verifyPrevDefInPhis(), llvm::GVN::ValueTable::verifyRemoved(), llvm::xray::BlockPrinter::visit(), llvm::xray::BlockPrinter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::BlockPrinter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::xray::BlockPrinter::visit(), llvm::xray::BlockPrinter::visit(), llvm::xray::BlockIndexer::visit(), llvm::xray::BlockPrinter::visit(), llvm::xray::BlockPrinter::visit(), llvm::xray::BlockPrinter::visit(), llvm::xray::FDRTraceWriter::visit(), llvm::DWARFLocationTable::visitAbsoluteLocationList(), llvm::SampleProfileLoaderBaseImpl< BT >::visitEdge(), llvm::InstCombinerImpl::visitExtractElementInst(), llvm::InstCombinerImpl::visitGetElementPtrInst(), VisitGlobalVariableForEmission(), llvm::DWARFDebugLoc::visitLocationList(), llvm::DWARFDebugLoclists::visitLocationList(), llvm::InstCombinerImpl::visitShuffleVectorInst(), llvm::VPlanTransforms::VPInstructionsToVPRecipes(), llvm::VirtRegAuxInfo::weightCalcHelper(), llvm::InnerLoopVectorizer::widenGEP(), llvm::LegalizerHelper::widenScalar(), llvm::write(), llvm::coverage::CoverageMappingWriter::write(), llvm::coverage::CoverageFilenamesSectionWriter::write(), llvm::TimeTraceProfiler::write(), llvm::support::endian::write(), llvm::support::endian::write16(), llvm::support::endian::write32(), llvm::support::endian::write64(), llvm::writeArchive(), llvm::writeArchiveToBuffer(), llvm::writeArchiveToStream(), llvm::yaml::BinaryRef::writeAsBinary(), llvm::InstrProfWriter::writeBuffer(), writeCOFF(), writeFragment(), llvm::object::writeImportLibrary(), llvm::writeIndexTable(), writePublics(), llvm::BitcodeWriter::writeSymtab(), llvm::InstrProfWriter::writeText(), llvm::writeToOutput(), llvm::object::writeUniversalBinary(), llvm::object::writeWindowsResourceCOFF(), llvm::DataDependenceGraph::~DataDependenceGraph(), llvm::LLVMContextImpl::~LLVMContextImpl(), and llvm::StringMap< ValueTy, AllocatorTy >::~StringMap().