LLVM: llvm::IVUsersWrapperPass Class Reference
llvm::IVUsersWrapperPass Class Reference
#include "llvm/Analysis/IVUsers.h"
Public Member Functions
IVUsersWrapperPass ()
IVUsers & getIU ()
const IVUsers & getIU () const
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
bool runOnLoop (Loop *L, LPPassManager &LPM) override
void releaseMemory () override
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
void print (raw_ostream &OS, const Module *=nullptr) const override
print - Print out the internal state of the pass.
Public Member Functions inherited from llvm::LoopPass
LoopPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
getPrinterPass - Get a pass to print the function corresponding to a Loop.
virtual bool doInitialization (Loop *L, LPPassManager &LPM)
virtual bool doFinalization ()
void preparePassManager (PMStack &PMS) override
Check if available pass managers are suitable for this pass or not.
void assignPassManager (PMStack &PMS, PassManagerType PMT) override
Assign pass manager to manage this pass.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
void dump () const
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::LoopPass
bool skipLoop (const Loop *L) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 167 of file IVUsers.h.
Constructor & Destructor Documentation
IVUsersWrapperPass()
IVUsersWrapperPass::IVUsersWrapperPass ()
Definition at line 354 of file IVUsers.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeIVUsersWrapperPassPass().
Member Function Documentation
getAnalysisUsage()
void IVUsersWrapperPass::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 358 of file IVUsers.cpp.
References llvm::AnalysisUsage::addRequired(), and llvm::AnalysisUsage::setPreservesAll().
getIU() [1/2]
IVUsers & llvm::IVUsersWrapperPass::getIU () inline
Definition at line 175 of file IVUsers.h.
getIU() [2/2]
const IVUsers & llvm::IVUsersWrapperPass::getIU () const inline
Definition at line 176 of file IVUsers.h.
print()
void IVUsersWrapperPass::print (raw_ostream & OS, const Module * M = nullptr) const override virtual
print - Print out the internal state of the pass.
This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 377 of file IVUsers.cpp.
releaseMemory()
void IVUsersWrapperPass::releaseMemory () override virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 381 of file IVUsers.cpp.
runOnLoop()
bool IVUsersWrapperPass::runOnLoop (Loop * L, LPPassManager & LPM) override virtual
Implements llvm::LoopPass.
Definition at line 366 of file IVUsers.cpp.
References llvm::LoopBase< BlockT, LoopT >::getHeader(), and llvm::BasicBlock::getParent().
Member Data Documentation
ID
char IVUsersWrapperPass::ID = 0 static
Definition at line 171 of file IVUsers.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/IVUsers.h
lib/Analysis/IVUsers.cpp