LLVM: PriorityInlineOrder< PriorityT > Class Template Reference
PriorityInlineOrder< PriorityT > Class Template Reference
Public Member Functions
size_t size () override
void push (const T &Elt) override
T pop () override
const_reference front () override
void erase_if (function_ref< bool(T)> Pred) override
Public Member Functions inherited from InlineOrder< std::pair< CallBase *, int > >
virtual ~InlineOrder ()
virtual void erase_if (function_ref< bool(std::pair< CallBase *, int >)> Pred)=0
bool empty ()
Additional Inherited Members
Public Types inherited from InlineOrder< std::pair< CallBase *, int > >
using reference
using const_reference
Detailed Description
template<typename PriorityT>
class PriorityInlineOrder< PriorityT >
Definition at line 744 of file Inliner.cpp.
Member Function Documentation
erase_if()
template<typename PriorityT > void PriorityInlineOrder< PriorityT >::erase_if (function_ref< bool(T)> Pred) inline override
Definition at line 810 of file Inliner.cpp.
References P.
front()
template<typename PriorityT > const_reference PriorityInlineOrder< PriorityT >::front () inline override virtual
Implements InlineOrder< std::pair< CallBase *, int > >.
Definition at line 802 of file Inliner.cpp.
References assert(), and size().
pop()
template<typename PriorityT > T PriorityInlineOrder< PriorityT >::pop () inline override virtual
Implements InlineOrder< std::pair< CallBase *, int > >.
Definition at line 790 of file Inliner.cpp.
References assert(), and size().
push()
template<typename PriorityT > void PriorityInlineOrder< PriorityT >::push (const T & Elt) inline override virtual
Implements InlineOrder< std::pair< CallBase *, int > >.
Definition at line 780 of file Inliner.cpp.
size()
template<typename PriorityT > size_t PriorityInlineOrder< PriorityT >::size () inline override virtual
Implements InlineOrder< std::pair< CallBase *, int > >.
Definition at line 778 of file Inliner.cpp.
The documentation for this class was generated from the following file:
lib/Transforms/IPO/Inliner.cpp