LLVM: llvm::ProfileSummaryBuilder Class Reference
llvm::ProfileSummaryBuilder Class Reference
#include "llvm/ProfileData/ProfileCommon.h"
Static Public Member Functions
static const ProfileSummaryEntry & getEntryForPercentile (SummaryEntryVector &DS, uint64_t Percentile)
Find the summary entry for a desired percentile of counts.
static uint64_t getHotCountThreshold (SummaryEntryVector &DS)
static uint64_t getColdCountThreshold (SummaryEntryVector &DS)
Static Public Attributes
static const ArrayRef< uint32_t > DefaultCutoffs
A vector of useful cutoff values for detailed summary.
Protected Member Functions
ProfileSummaryBuilder (std::vector< uint32_t > Cutoffs)
~ProfileSummaryBuilder ()=default
void addCount (uint64_t Count)
This is called when a count is seen in the profile.
void computeDetailedSummary ()
Protected Attributes
SummaryEntryVector DetailedSummary
uint64_t TotalCount = 0
uint64_t MaxCount = 0
uint64_t MaxFunctionCount = 0
uint32_t NumCounts = 0
uint32_t NumFunctions = 0
Detailed Description
Definition at line 40 of file ProfileCommon.h.
Constructor & Destructor Documentation
ProfileSummaryBuilder()
llvm::ProfileSummaryBuilder::ProfileSummaryBuilder (std::vector< uint32_t > Cutoffs) inline protected
Definition at line 56 of file ProfileCommon.h.
~ProfileSummaryBuilder()
llvm::ProfileSummaryBuilder::~ProfileSummaryBuilder () protected default
Member Function Documentation
addCount()
void llvm::ProfileSummaryBuilder::addCount (uint64_t Count) inline protected
This is called when a count is seen in the profile.
Definition at line 101 of file ProfileCommon.h.
References MaxCount, NumCounts, and TotalCount.
Referenced by llvm::SampleProfileSummaryBuilder::addRecord().
computeDetailedSummary()
void ProfileSummaryBuilder::computeDetailedSummary () protected
Definition at line 125 of file ProfileSummaryBuilder.cpp.
References assert(), D, DetailedSummary, llvm::APInt::getZExtValue(), N, llvm::ProfileSummary::Scale, llvm::APInt::sdiv(), llvm::sort(), and TotalCount.
Referenced by llvm::InstrProfSummaryBuilder::getSummary(), and llvm::SampleProfileSummaryBuilder::getSummary().
getColdCountThreshold()
uint64_t ProfileSummaryBuilder::getColdCountThreshold (SummaryEntryVector & DS) static
Definition at line 166 of file ProfileSummaryBuilder.cpp.
References ColdCountThreshold, getEntryForPercentile(), ProfileSummaryColdCount, and ProfileSummaryCutoffCold.
getEntryForPercentile()
const ProfileSummaryEntry & ProfileSummaryBuilder::getEntryForPercentile (SummaryEntryVector & DS, uint64_t Percentile) static
Find the summary entry for a desired percentile of counts.
Definition at line 83 of file ProfileSummaryBuilder.cpp.
References llvm::partition_point(), and llvm::report_fatal_error().
Referenced by getColdCountThreshold(), and getHotCountThreshold().
getHotCountThreshold()
uint64_t ProfileSummaryBuilder::getHotCountThreshold (SummaryEntryVector & DS) static
Definition at line 157 of file ProfileSummaryBuilder.cpp.
References getEntryForPercentile(), ProfileSummaryCutoffHot, and ProfileSummaryHotCount.
Member Data Documentation
DefaultCutoffs
const ArrayRef< uint32_t > ProfileSummaryBuilder::DefaultCutoffs static
Initial value:
=
    DefaultCutoffsData
A vector of useful cutoff values for detailed summary.
Definition at line 65 of file ProfileCommon.h.
Referenced by llvm::sampleprof::SampleProfileReader::computeSummary(), and llvm::sampleprof::SampleProfileWriter::computeSummary().
DetailedSummary
SummaryEntryVector llvm::ProfileSummaryBuilder::DetailedSummary protected
Definition at line 49 of file ProfileCommon.h.
Referenced by computeDetailedSummary(), llvm::InstrProfSummaryBuilder::getSummary(), and llvm::SampleProfileSummaryBuilder::getSummary().
MaxCount
uint64_t llvm::ProfileSummaryBuilder::MaxCount = 0 protected
Definition at line 51 of file ProfileCommon.h.
Referenced by addCount(), llvm::InstrProfSummaryBuilder::getSummary(), and llvm::SampleProfileSummaryBuilder::getSummary().
MaxFunctionCount
uint64_t llvm::ProfileSummaryBuilder::MaxFunctionCount = 0 protected
Definition at line 52 of file ProfileCommon.h.
Referenced by llvm::SampleProfileSummaryBuilder::addRecord(), llvm::InstrProfSummaryBuilder::getSummary(), and llvm::SampleProfileSummaryBuilder::getSummary().
NumCounts
uint32_t llvm::ProfileSummaryBuilder::NumCounts = 0 protected
Definition at line 53 of file ProfileCommon.h.
Referenced by addCount(), llvm::InstrProfSummaryBuilder::getSummary(), and llvm::SampleProfileSummaryBuilder::getSummary().
NumFunctions
uint32_t llvm::ProfileSummaryBuilder::NumFunctions = 0 protected
Definition at line 54 of file ProfileCommon.h.
Referenced by llvm::SampleProfileSummaryBuilder::addRecord(), llvm::SampleProfileSummaryBuilder::computeSummaryForProfiles(), llvm::InstrProfSummaryBuilder::getSummary(), and llvm::SampleProfileSummaryBuilder::getSummary().
TotalCount
uint64_t llvm::ProfileSummaryBuilder::TotalCount = 0 protected
Definition at line 50 of file ProfileCommon.h.
Referenced by addCount(), computeDetailedSummary(), llvm::InstrProfSummaryBuilder::getSummary(), and llvm::SampleProfileSummaryBuilder::getSummary().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/ProfileCommon.h
lib/ProfileData/ProfileSummaryBuilder.cpp