LLVM: llvm::SystemZFrameLowering Class Reference
llvm::SystemZFrameLowering Class Reference
#include "Target/SystemZ/SystemZFrameLowering.h"
Public Member Functions
SystemZFrameLowering ()
bool isFPCloseToIncomingSP () const override
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI) const override
void determineCalleeSaves (MachineFunction &MF, BitVector &SavedRegs, RegScavenger *RS) const override
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const override
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBII, MutableArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo *TRI) const override
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS) const override
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
void emitPrologue (MachineFunction &MF, MachineBasicBlock &MBB) const override
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const override
void inlineStackProbe (MachineFunction &MF, MachineBasicBlock &PrologMBB) const override
Replace a StackProbe stub (if any) with the actual probe code inline.
bool hasFP (const MachineFunction &MF) const override
hasFP - Return true if the specified function should have a dedicated frame pointer register.
bool hasReservedCallFrame (const MachineFunction &MF) const override
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
StackOffset getFrameIndexReference (const MachineFunction &MF, int FI, Register &FrameReg) const override
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
MachineBasicBlock::iterator eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const override
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
unsigned getRegSpillOffset (MachineFunction &MF, Register Reg) const
int getOrCreateFramePointerSaveIndex (MachineFunction &MF) const
bool usePackedStack (MachineFunction &MF) const
unsigned getBackchainOffset (MachineFunction &MF) const
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, Align StackAl, int LAO, Align TransAl=Align(1), bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
getStackGrowthDirection - Return the direction the stack grows
unsigned getStackAlignment () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
Align getStackAlign () const
getStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned on entry to a function.
int alignSPAdjust (int SPAdj) const
alignSPAdjust - This method aligns the stack adjustment to the correct alignment.
Align getTransientStackAlign () const
getTransientStackAlignment - This method returns the number of bytes to which the stack pointer must be aligned at all times, even between calls.
bool isStackRealignable () const
isStackRealignable - This method returns whether the stack can be realigned.
virtual unsigned getStackAlignmentSkew (const MachineFunction &MF) const
Return the skew that has to be applied to stack alignment under certain conditions (e.g.
virtual bool isStackIdSafeForLocalArea (unsigned StackId) const
This method returns whether or not it is safe for an object with the given stack id to be bundled into the local area.
int getOffsetOfLocalArea () const
getOffsetOfLocalArea - This method returns the offset of the local area from the stack pointer on entrance to a function.
virtual bool assignCalleeSavedSpillSlots (MachineFunction &MF, const TargetRegisterInfo *TRI, std::vector< CalleeSavedInfo > &CSI, unsigned &MinCSFrameIndex, unsigned &MaxCSFrameIndex) const
assignCalleeSavedSpillSlots - Allows target to override spill slot assignment logic.
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
virtual bool targetHandlesStackFrameRounding () const
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
virtual bool enableShrinkWrapping (const MachineFunction &MF) const
Returns true if the target will correctly handle shrink wrapping.
virtual bool enableStackSlotScavenging (const MachineFunction &MF) const
Returns true if the stack slot holes in the fixed and callee-save stack area should be used when allocating other stack locations to reduce stack size.
virtual bool enableCalleeSaveSkip (const MachineFunction &MF) const
Returns true if the target can safely skip saving callee-saved registers for noreturn nounwind functions.
virtual void emitCalleeSavedFrameMoves (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI) const
With basic block sections, emit callee saved frame moves for basic blocks that are in a different section.
virtual void adjustForSegmentedStacks (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to have the function use segmented stacks.
virtual void adjustForHiPEPrologue (MachineFunction &MF, MachineBasicBlock &PrologueMBB) const
Adjust the prologue to add Erlang Run-Time System (ERTS) specific code in the assembly prologue to explicitly handle the stack.
virtual bool keepFramePointer (const MachineFunction &MF) const
Return true if the target wants to keep the frame pointer regardless of the function attribute "frame-pointer".
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
canSimplifyCallFramePseudos - When possible, it's best to simplify the call frame pseudo ops before doing frame index elimination.
virtual bool needsFrameIndexResolution (const MachineFunction &MF) const
virtual StackOffset getFrameIndexReferencePreferSP (const MachineFunction &MF, int FI, Register &FrameReg, bool IgnoreSPUpdates) const
Same as getFrameIndexReference, except that the stack pointer (as opposed to the frame pointer) will be the preferred value for FrameReg.
virtual StackOffset getNonLocalFrameIndexReference (const MachineFunction &MF, int FI) const
getNonLocalFrameIndexReference - This method returns the offset used to reference a frame index location.
virtual void getCalleeSaves (const MachineFunction &MF, BitVector &SavedRegs) const
Returns the callee-saved registers as computed by determineCalleeSaves in the BitVector SavedRegs.
virtual void processFunctionBeforeFrameIndicesReplaced (MachineFunction &MF, RegScavenger *RS=nullptr) const
processFunctionBeforeFrameIndicesReplaced - This method is called immediately before MO_FrameIndex operands are eliminated, but after the frame is finalized.
virtual unsigned getWinEHParentFrameOffset (const MachineFunction &MF) const
virtual void orderFrameObjects (const MachineFunction &MF, SmallVectorImpl< int > &objectsToAllocate) const
Order the symbols in the local stack frame.
virtual bool canUseAsPrologue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a prologue for the target.
virtual bool canUseAsEpilogue (const MachineBasicBlock &MBB) const
Check whether or not the given MBB can be used as a epilogue for the target.
virtual TargetStackID::Value getStackIDForScalableVectors () const
Returns the StackID that scalable vectors should be associated with.
virtual bool isSupportedStackID (TargetStackID::Value ID) const
virtual bool isProfitableForNoCSROpt (const Function &F) const
Check if the no-CSR optimisation is profitable for the given function.
virtual int getInitialCFAOffset (const MachineFunction &MF) const
Return initial CFA offset value i.e.
virtual Register getInitialCFARegister (const MachineFunction &MF) const
Return initial CFA register value i.e.
virtual DwarfFrameBase getDwarfFrameBase (const MachineFunction &MF) const
Return the frame base information to be encoded in the DWARF subprogram debug info.
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp , StackGrowsDown }
Static Public Member Functions inherited from llvm::TargetFrameLowering
static bool isSafeForNoCSROpt (const Function &F)
Check if given function is safe for not having callee saved registers.
Detailed Description
Definition at line 21 of file SystemZFrameLowering.h.
Constructor & Destructor Documentation
SystemZFrameLowering()
SystemZFrameLowering::SystemZFrameLowering ()
Definition at line 49 of file SystemZFrameLowering.cpp.
References llvm::array_lengthof(), E, llvm::IndexedMap< T, ToIndexT >::grow(), I, and Offset.
Member Function Documentation
assignCalleeSavedSpillSlots()
bool SystemZFrameLowering::assignCalleeSavedSpillSlots (MachineFunction & MF, const TargetRegisterInfo * TRI, std::vector< CalleeSavedInfo > & CSI) const override virtual
Reimplemented from llvm::TargetFrameLowering.
Definition at line 66 of file SystemZFrameLowering.cpp.
References assert(), contains(), llvm::SystemZ::ELFArgGPRs, llvm::SystemZMC::ELFCallFrameSize, llvm::SystemZ::ELFNumArgGPRs, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), getRegSpillOffset(), llvm::Function::isVarArg(), Offset, Reg, Size, TRI, and usePackedStack().
determineCalleeSaves()
void SystemZFrameLowering::determineCalleeSaves (MachineFunction & MF, BitVector & SavedRegs, RegScavenger * RS) const override virtual
This method determines which of the registers reported by TargetRegisterInfo::getCalleeSavedRegs() should actually get saved.
The default implementation checks populates the SavedRegs bitset with all registers which are modified in the function, targets may override this function to save additional registers. This method also sets up the register scavenger ensuring there is a free register or a frameindex available. This method should not be called by any passes outside of PEI, because it may change state passed in by MF and RS. The preferred interface outside PEI is getCalleeSaves.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 133 of file SystemZFrameLowering.cpp.
References contains(), llvm::TargetFrameLowering::determineCalleeSaves(), llvm::SystemZ::ELFArgGPRs, llvm::SystemZ::ELFNumArgGPRs, llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getLandingPads(), llvm::TargetSubtargetInfo::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::SystemZMachineFunctionInfo::getVarArgsFirstGPR(), hasFP(), I, llvm::Function::isVarArg(), llvm::BitVector::set(), llvm::BitVector::test(), and TRI.
eliminateCallFramePseudoInstr()
MachineBasicBlock::iterator SystemZFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const override virtual
This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them).
It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions. Returns an iterator pointing to the instruction after the replaced one.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 747 of file SystemZFrameLowering.cpp.
References assert(), llvm::MachineBasicBlock::erase(), hasReservedCallFrame(), llvm_unreachable, MBB, and MI.
emitEpilogue()
void SystemZFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
Implements llvm::TargetFrameLowering.
Definition at line 576 of file SystemZFrameLowering.cpp.
References assert(), DL, emitIncrement(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MachineFunction::getSubtarget(), llvm::CallingConv::GHC, llvm_unreachable, MBB, MBBI, and Offset.
emitPrologue()
void SystemZFrameLowering::emitPrologue (MachineFunction & MF, MachineBasicBlock & MBB) const override virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 413 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addCFIIndex(), llvm::MachineFunction::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), buildCFAOffs(), buildDefCFAReg(), llvm::BuildMI(), contains(), llvm::MCCFIInstruction::createOffset(), llvm::RegState::Define, DL, E, llvm::SystemZMC::ELFCallFrameSize, llvm::SystemZMC::ELFCFAOffsetFromInitialSP, emitIncrement(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineFunction::front(), getBackchainOffset(), llvm::Function::getCallingConv(), llvm::MachineModuleInfo::getContext(), llvm::StackOffset::getFixed(), getFrameIndexReference(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::SystemZSubtarget::getInstrInfo(), llvm::MachineFunction::getMMI(), llvm::MCContext::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::TargetSubtargetInfo::getTargetLowering(), llvm::SystemZSubtarget::getTargetLowering(), llvm::CallingConv::GHC, llvm::Function::hasFnAttribute(), hasFP(), I, llvm::RegState::Kill, llvm_unreachable, MBB, MBBI, MRI, Offset, and llvm::report_fatal_error().
getBackchainOffset()
unsigned llvm::SystemZFrameLowering::getBackchainOffset (MachineFunction & MF) const inline
Definition at line 69 of file SystemZFrameLowering.h.
References llvm::SystemZMC::ELFCallFrameSize, and usePackedStack().
Referenced by emitPrologue(), getOrCreateFramePointerSaveIndex(), and inlineStackProbe().
getFrameIndexReference()
StackOffset SystemZFrameLowering::getFrameIndexReference (const MachineFunction & MF, int FI, Register & FrameReg) const override virtual
getFrameIndexReference - This method should return the base register and offset used to reference a frame index location.
Returns the displacement from the frame register to the stack frame of the specified index, along with the frame register used (in output arg FrameReg).
The offset is returned directly, and the base register is returned via FrameReg.
This is the default implementation which is overridden for some targets.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 738 of file SystemZFrameLowering.cpp.
References llvm::SystemZMC::ELFCallFrameSize, llvm::StackOffset::getFixed(), llvm::TargetFrameLowering::getFrameIndexReference(), and Offset.
Referenced by llvm::SystemZRegisterInfo::eliminateFrameIndex(), and emitPrologue().
getOrCreateFramePointerSaveIndex()
int SystemZFrameLowering::getOrCreateFramePointerSaveIndex (MachineFunction & MF) const
Definition at line 781 of file SystemZFrameLowering.cpp.
References llvm::SystemZMC::ELFCallFrameSize, getBackchainOffset(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), and Offset.
Referenced by processFunctionBeforeFrameFinalized().
getRegSpillOffset()
unsigned SystemZFrameLowering::getRegSpillOffset (MachineFunction & MF, Register Reg) const
Definition at line 764 of file SystemZFrameLowering.cpp.
References contains(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::Function::hasFnAttribute(), llvm::Function::isVarArg(), Offset, Reg, and usePackedStack().
Referenced by assignCalleeSavedSpillSlots().
hasFP()
bool SystemZFrameLowering::hasFP (const MachineFunction & MF) const override virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register.
For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 722 of file SystemZFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::SystemZMachineFunctionInfo::getManipulatesSP(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasVarSizedObjects(), and llvm::TargetMachine::Options.
Referenced by determineCalleeSaves(), emitPrologue(), llvm::SystemZRegisterInfo::getFrameRegister(), llvm::SystemZRegisterInfo::getReservedRegs(), and restoreCalleeSavedRegisters().
hasReservedCallFrame()
bool SystemZFrameLowering::hasReservedCallFrame (const MachineFunction & MF) const override virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function.
This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 729 of file SystemZFrameLowering.cpp.
Referenced by eliminateCallFramePseudoInstr().
inlineStackProbe()
void SystemZFrameLowering::inlineStackProbe (MachineFunction & MF, MachineBasicBlock & PrologueMBB) const override virtual
Replace a StackProbe stub (if any) with the actual probe code inline.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 622 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), Align, buildCFAOffs(), buildDefCFAReg(), llvm::BuildMI(), llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_ICMP, llvm::RegState::Define, DL, llvm::SystemZMC::ELFCallFrameSize, llvm::SystemZMC::ELFCFAOffsetFromInitialSP, llvm::SystemZ::emitBlockAfter(), emitIncrement(), llvm::MachineBasicBlock::end(), getBackchainOffset(), llvm::MachineFunction::getFunction(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFunction::getSubtarget(), llvm::SystemZSubtarget::getTargetLowering(), llvm::Function::hasFnAttribute(), llvm::RegState::Kill, MBB, MBBI, MI, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOVolatile, llvm::recomputeLiveIns(), Size, llvm::SystemZ::splitBlockBefore(), and llvm::RegState::Undef.
isFPCloseToIncomingSP()
bool llvm::SystemZFrameLowering::isFPCloseToIncomingSP () const inline override virtual
isFPCloseToIncomingSP - Return true if the frame pointer is close to the incoming stack pointer, false if it is close to the post-prologue stack pointer.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 28 of file SystemZFrameLowering.h.
processFunctionBeforeFrameFinalized()
void SystemZFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS) const override virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized.
Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 315 of file SystemZFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::SystemZMC::ELFCallFrameSize, llvm::MachineFunction::front(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), getOrCreateFramePointerSaveIndex(), llvm::MachineFunction::getRegInfo(), llvm::Function::hasFnAttribute(), I, llvm::MachineBasicBlock::isLiveIn(), MRI, and usePackedStack().
restoreCalleeSavedRegisters()
bool SystemZFrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, MutableArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo * TRI) const override virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot().
If it returns true, and any of the registers in CSI is not restored, it sets the corresponding Restored flag in CSI to false. Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 259 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), assert(), llvm::BuildMI(), contains(), llvm::RegState::Define, DL, E, llvm::MachineBasicBlock::end(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), hasFP(), I, llvm::RegState::ImplicitDefine, llvm::HexagonInstrInfo::loadRegFromStackSlot(), MBB, MBBI, TII, and TRI.
spillCalleeSavedRegisters()
bool SystemZFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, ArrayRef< CalleeSavedInfo > CSI, const TargetRegisterInfo * TRI) const override virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot().
Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 199 of file SystemZFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), addSavedGPR(), assert(), llvm::BuildMI(), contains(), DL, E, llvm::SystemZ::ELFArgGPRs, llvm::SystemZ::ELFNumArgGPRs, llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getSubtarget(), I, llvm::Function::isVarArg(), MBB, MBBI, llvm::HexagonInstrInfo::storeRegToStackSlot(), TII, and TRI.
usePackedStack()
bool SystemZFrameLowering::usePackedStack (MachineFunction & MF) const
Definition at line 794 of file SystemZFrameLowering.cpp.
References llvm::Function::getCallingConv(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getSubtarget(), llvm::CallingConv::GHC, llvm::Function::hasFnAttribute(), and llvm::report_fatal_error().
Referenced by assignCalleeSavedSpillSlots(), getBackchainOffset(), getRegSpillOffset(), and processFunctionBeforeFrameFinalized().
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZFrameLowering.h
lib/Target/SystemZ/SystemZFrameLowering.cpp