LLVM: llvm::ConstantExpr Class Reference
llvm::ConstantExpr Class Reference
A constant value that is initialized with an expression using other constant values.
#include "llvm/IR/Constants.h"
Public Member Functions
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Constant)
Transparently provide more efficient getOperand methods.
bool isCast () const
Return true if this is a convert constant expression.
bool isCompare () const
Return true if this is a compare constant expression.
bool hasIndices () const
Return true if this is an insertvalue or extractvalue expression, and the getIndices() method may be used.
bool isGEPWithNoNotionalOverIndexing () const
Return true if this is a getelementptr expression and all the index operands are compile-time known integers within the corresponding notional static array extents.
unsigned getOpcode () const
Return the opcode at the root of this constant expression.
unsigned getPredicate () const
Return the ICMP or FCMP predicate value.
ArrayRef< unsigned > getIndices () const
Assert that this is an insertvalue or exactvalue expression and return the list of indices.
ArrayRef< int > getShuffleMask () const
Assert that this is a shufflevector and return the mask.
Constant * getShuffleMaskForBitcode () const
Assert that this is a shufflevector and return the mask.
const char * getOpcodeName () const
Return a string representation for an opcode.
Constant * getWithOperandReplaced (unsigned OpNo, Constant *Op) const
Return a constant expression identical to this one, but with the specified operand set to the specified value.
Constant * getWithOperands (ArrayRef< Constant * > Ops) const
This returns the current constant expression with the operands replaced with the specified values.
Constant * getWithOperands (ArrayRef< Constant * > Ops, Type *Ty, bool OnlyIfReduced=false, Type *SrcTy=nullptr) const
Get the current expression with the operands replaced.
Instruction * getAsInstruction () const
Returns an Instruction which implements the same operation as this ConstantExpr.
Public Member Functions inherited from llvm::Constant
void operator= (const Constant &)=delete
Constant (const Constant &)=delete
bool isNullValue () const
Return true if this is the value that would be returned by getNullValue.
bool isOneValue () const
Returns true if the value is one.
bool isNotOneValue () const
Return true if the value is not the one value, or, for vectors, does not contain one value elements.
bool isAllOnesValue () const
Return true if this is the value that would be returned by getAllOnesValue.
bool isNegativeZeroValue () const
Return true if the value is what would be returned by getZeroValueForNegation.
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool isNotMinSignedValue () const
Return true if the value is not the smallest signed value, or, for vectors, does not contain smallest signed value elements.
bool isMinSignedValue () const
Return true if the value is the smallest signed value.
bool isFiniteNonZeroFP () const
Return true if this is a finite and non-zero floating-point scalar constant or a fixed width vector constant with all finite and non-zero elements.
bool isNormalFP () const
Return true if this is a normal (as opposed to denormal, infinity, nan, or zero) floating-point scalar constant or a vector constant with all normal elements.
bool hasExactInverseFP () const
Return true if this scalar has an exact multiplicative inverse or this vector has an exact multiplicative inverse for each element in the vector.
bool isNaN () const
Return true if this is a floating-point NaN constant or a vector floating-point constant with all NaN elements.
bool isElementWiseEqual (Value *Y) const
Return true if this constant and a constant 'Y' are element-wise equal.
bool containsUndefOrPoisonElement () const
Return true if this is a vector constant that includes any undef or poison elements.
bool containsPoisonElement () const
Return true if this is a vector constant that includes any poison elements.
bool containsConstantExpression () const
Return true if this is a fixed width vector constant that includes any constant expressions.
bool canTrap () const
Return true if evaluation of this constant could trap.
bool isThreadDependent () const
Return true if the value can vary between threads.
bool isDLLImportDependent () const
Return true if the value is dependent on a dllimport variable.
bool isConstantUsed () const
Return true if the constant has users other than constant expressions and other dangling things.
bool needsRelocation () const
This method classifies the entry according to whether or not it may generate a relocation entry (either static or dynamic).
bool needsDynamicRelocation () const
Constant * getAggregateElement (unsigned Elt) const
For aggregates (struct/array/vector) return the constant that corresponds to the specified element if possible, or null if not.
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue (bool AllowUndefs=false) const
If all elements of the vector constant have the same value, return that value.
const APInt & getUniqueInteger () const
If C is a constant integer then return its value, otherwise C must be a vector of constant integers, all equal, and the common value is returned.
void destroyConstant ()
Called if some element of this constant is no longer valid.
void handleOperandChange (Value *, Value *)
This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants.
void removeDeadConstantUsers () const
If there are any dead constant users dangling off of this constant, remove them.
const Constant * stripPointerCasts () const
Constant * stripPointerCasts ()
bool isManifestConstant () const
Return true if a constant is ConstantData or a ConstantAggregate or ConstantExpr that contain only ConstantData.
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
std::string getNameOrAsOperand () const
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one use of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N uses.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
bool hasOneUser () const
Return true if there is exactly one user of this value.
Use * getSingleUndroppableUse ()
Return true if there is exactly one use of this value that cannot be dropped.
const Use * getSingleUndroppableUse () const
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N uses or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
void dropDroppableUsesIn (User &Usr)
Remove every use of this value in User that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isTransitiveUsedByMetadataOnly () const
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsForAliasAnalysis () const
Strip off pointer casts, all-zero GEPs, single-argument phi nodes and invariant group info.
Value * stripPointerCastsForAliasAnalysis ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
bool canBeFreed () const
Return true if the memory object referred to by V can by freed in the scope for which the SSA value defining the allocation is statically defined.
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull, bool &CanBeFreed) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Static Public Member Functions
static Constant * getAlignOf (Type *Ty)
getAlignOf constant expr - computes the alignment of a type in a target independent way (Note: the return type is an i64).
static Constant * getSizeOf (Type *Ty)
getSizeOf constant expr - computes the (alloc) size of a type (in address-units, not bits) in a target independent way (Note: the return type is an i64).
static Constant * getOffsetOf (StructType *STy, unsigned FieldNo)
getOffsetOf constant expr - computes the offset of a struct field in a target independent way (Note: the return type is an i64).
static Constant * getOffsetOf (Type *Ty, Constant *FieldNo)
getOffsetOf constant expr - This is a generalized form of getOffsetOf, which supports any aggregate type, and any Constant index.
static Constant * getNeg (Constant *C, bool HasNUW=false, bool HasNSW=false)
static Constant * getFNeg (Constant *C)
static Constant * getNot (Constant *C)
static Constant * getAdd (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getFAdd (Constant *C1, Constant *C2)
static Constant * getSub (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getFSub (Constant *C1, Constant *C2)
static Constant * getMul (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getFMul (Constant *C1, Constant *C2)
static Constant * getUDiv (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getSDiv (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getFDiv (Constant *C1, Constant *C2)
static Constant * getURem (Constant *C1, Constant *C2)
static Constant * getSRem (Constant *C1, Constant *C2)
static Constant * getFRem (Constant *C1, Constant *C2)
static Constant * getAnd (Constant *C1, Constant *C2)
static Constant * getOr (Constant *C1, Constant *C2)
static Constant * getXor (Constant *C1, Constant *C2)
static Constant * getUMin (Constant *C1, Constant *C2)
static Constant * getShl (Constant *C1, Constant *C2, bool HasNUW=false, bool HasNSW=false)
static Constant * getLShr (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getAShr (Constant *C1, Constant *C2, bool isExact=false)
static Constant * getTrunc (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getSExt (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getZExt (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPTrunc (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPExtend (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getUIToFP (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getSIToFP (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPToUI (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getFPToSI (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getPtrToInt (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getIntToPtr (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getBitCast (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getAddrSpaceCast (Constant *C, Type *Ty, bool OnlyIfReduced=false)
static Constant * getNSWNeg (Constant *C)
static Constant * getNUWNeg (Constant *C)
static Constant * getNSWAdd (Constant *C1, Constant *C2)
static Constant * getNUWAdd (Constant *C1, Constant *C2)
static Constant * getNSWSub (Constant *C1, Constant *C2)
static Constant * getNUWSub (Constant *C1, Constant *C2)
static Constant * getNSWMul (Constant *C1, Constant *C2)
static Constant * getNUWMul (Constant *C1, Constant *C2)
static Constant * getNSWShl (Constant *C1, Constant *C2)
static Constant * getNUWShl (Constant *C1, Constant *C2)
static Constant * getExactSDiv (Constant *C1, Constant *C2)
static Constant * getExactUDiv (Constant *C1, Constant *C2)
static Constant * getExactAShr (Constant *C1, Constant *C2)
static Constant * getExactLShr (Constant *C1, Constant *C2)
static Constant * getExactLogBase2 (Constant *C)
If C is a scalar/fixed width vector of known powers of 2, then this function returns a new scalar/fixed width vector obtained from logBase2 of C.
static Constant * getBinOpIdentity (unsigned Opcode, Type *Ty, bool AllowRHSConstant=false)
Return the identity constant for a binary opcode.
static Constant * getBinOpAbsorber (unsigned Opcode, Type *Ty)
Return the absorbing element for the given binary operation, i.e.
static Constant * getCast (unsigned ops, Constant *C, Type *Ty, bool OnlyIfReduced=false)
Convenience function for getting a Cast operation.
static Constant * getZExtOrBitCast (Constant *C, Type *Ty)
static Constant * getSExtOrBitCast (Constant *C, Type *Ty)
static Constant * getTruncOrBitCast (Constant *C, Type *Ty)
static Constant * getPointerCast (Constant *C, Type *Ty)
Create a BitCast, AddrSpaceCast, or a PtrToInt cast constant expression.
static Constant * getPointerBitCastOrAddrSpaceCast (Constant *C, Type *Ty)
Create a BitCast or AddrSpaceCast for a pointer type depending on the address space.
static Constant * getIntegerCast (Constant *C, Type *Ty, bool IsSigned)
Create a ZExt, Bitcast or Trunc for integer -> integer casts.
static Constant * getFPCast (Constant *C, Type *Ty)
Create a FPExt, Bitcast or FPTrunc for fp -> fp casts.
static Constant * getSelect (Constant *C, Constant *V1, Constant *V2, Type *OnlyIfReducedTy=nullptr)
Select constant expr.
static Constant * get (unsigned Opcode, Constant *C1, unsigned Flags=0, Type *OnlyIfReducedTy=nullptr)
get - Return a unary operator constant expression, folding if possible.
static Constant * get (unsigned Opcode, Constant *C1, Constant *C2, unsigned Flags=0, Type *OnlyIfReducedTy=nullptr)
get - Return a binary or shift operator constant expression, folding if possible.
static Constant * getCompare (unsigned short pred, Constant *C1, Constant *C2, bool OnlyIfReduced=false)
Return an ICmp or FCmp comparison operator constant expression.
static Constant * getICmp (unsigned short pred, Constant *LHS, Constant *RHS, bool OnlyIfReduced=false)
get* - Return some common constants without having to specify the full Instruction::OPCODE identifier.
static Constant * getFCmp (unsigned short pred, Constant *LHS, Constant *RHS, bool OnlyIfReduced=false)
static Constant * getGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList, bool InBounds=false, Optional< unsigned > InRangeIndex=None, Type *OnlyIfReducedTy=nullptr)
Getelementptr form.
static Constant * getGetElementPtr (Type *Ty, Constant *C, Constant *Idx, bool InBounds=false, Optional< unsigned > InRangeIndex=None, Type *OnlyIfReducedTy=nullptr)
static Constant * getGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList, bool InBounds=false, Optional< unsigned > InRangeIndex=None, Type *OnlyIfReducedTy=nullptr)
static Constant * getInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList)
Create an "inbounds" getelementptr.
static Constant * getInBoundsGetElementPtr (Type *Ty, Constant *C, Constant *Idx)
static Constant * getInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList)
static Constant * getExtractElement (Constant *Vec, Constant *Idx, Type *OnlyIfReducedTy=nullptr)
static Constant * getInsertElement (Constant *Vec, Constant *Elt, Constant *Idx, Type *OnlyIfReducedTy=nullptr)
static Constant * getShuffleVector (Constant *V1, Constant *V2, ArrayRef< int > Mask, Type *OnlyIfReducedTy=nullptr)
static Constant * getExtractValue (Constant *Agg, ArrayRef< unsigned > Idxs, Type *OnlyIfReducedTy=nullptr)
static Constant * getInsertValue (Constant *Agg, Constant *Val, ArrayRef< unsigned > Idxs, Type *OnlyIfReducedTy=nullptr)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
Constructor to create a '0' constant of arbitrary type.
static Constant * getAllOnesValue (Type *Ty)
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Return the value for an integer or pointer constant, or a vector thereof, with the given scalar value.
static Constant * replaceUndefsWith (Constant *C, Constant *Replacement)
Try to replace undefined constant C or undefined elements in C with Replacement.
static Constant * mergeUndefsWith (Constant *C, Constant *Other)
Merges undefs of a Constant with another Constant, along with the undefs already present.
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Value
static void dropDroppableUse (Use &U)
Remove the droppable use U.
Protected Member Functions
ConstantExpr (Type *ty, unsigned Opcode, Use *Ops, unsigned NumOps)
~ConstantExpr ()=default
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
~Constant ()=default
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Appends all metadata attached to this value to MDs, sorting by KindID.
bool hasMetadata () const
Return true if this value has any metadata attached to it.
bool eraseMetadata (unsigned KindID)
Erase all metadata attachments with the given kind.
void clearMetadata ()
Erase all metadata attached to this Value.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
MDNode * getMetadata (unsigned KindID) const
Get the current metadata attachments for the given kind, if any.
MDNode * getMetadata (StringRef Kind) const
void getMetadata (unsigned KindID, SmallVectorImpl< MDNode * > &MDs) const
Appends all attachments with the given ID to MDs in insertion order.
void getMetadata (StringRef Kind, SmallVectorImpl< MDNode * > &MDs) const
bool hasMetadata (unsigned KindID) const
Return true if this value has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
void setMetadata (unsigned KindID, MDNode *Node)
Set a particular kind of metadata attachment.
void setMetadata (StringRef Kind, MDNode *Node)
void addMetadata (unsigned KindID, MDNode &MD)
Add a metadata attachment.
void addMetadata (StringRef Kind, MDNode &MD)
Friends
struct ConstantExprKeyType
class Constant
Additional Inherited Members
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 27 }
The number of operands in the subclass.
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasMetadata: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Detailed Description
A constant value that is initialized with an expression using other constant values.
This class uses the standard Instruction opcodes to define the various constant expressions. The Opcode field for the ConstantExpr class is maintained in the Value::SubclassData field.
Definition at line 936 of file Constants.h.
Constructor & Destructor Documentation
ConstantExpr()
llvm::ConstantExpr::ConstantExpr (Type * ty, unsigned Opcode, Use * Ops, unsigned NumOps) inline protected
Definition at line 944 of file Constants.h.
~ConstantExpr()
llvm::ConstantExpr::~ConstantExpr () protected default
Member Function Documentation
classof()
static bool llvm::ConstantExpr::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 1324 of file Constants.h.
DECLARE_TRANSPARENT_OPERAND_ACCESSORS()
llvm::ConstantExpr::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Constant)
Transparently provide more efficient getOperand methods.
get() [1/2]
Constant * ConstantExpr::get (unsigned Opcode, Constant * C1, Constant * C2, unsigned Flags = 0, Type * OnlyIfReducedTy = nullptr) static
get - Return a binary or shift operator constant expression, folding if possible.
Parameters
OnlyIfReducedTy see getWithOperands() docs.
Definition at line 2288 of file Constants.cpp.
References assert(), llvm::ConstantFoldBinaryInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm::Instruction::isBinaryOp().
get() [2/2]
Constant * ConstantExpr::get (unsigned Opcode, Constant * C1, unsigned Flags = 0, Type * OnlyIfReducedTy = nullptr) static
get - Return a unary operator constant expression, folding if possible.
Parameters
OnlyIfReducedTy see getWithOperands() docs.
Definition at line 2257 of file Constants.cpp.
References assert(), C, llvm::ConstantFoldUnaryInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm::Instruction::isUnaryOp().
Referenced by computeUnlikelySuccessors(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldBinaryOpOperands(), llvm::ConstantFoldUnaryInstruction(), llvm::ConstantFoldUnaryOpOperand(), llvm::TargetFolder::CreateBinOp(), llvm::ConstantFolder::CreateBinOp(), llvm::TargetFolder::CreateUnOp(), llvm::ConstantFolder::CreateUnOp(), foldGEPOfGEP(), foldOperationIntoPhiValue(), foldOperationIntoSelectOperand(), llvm::InstCombinerImpl::FoldShiftByConstant(), llvm::InstCombinerImpl::foldVectorBinop(), getAdd(), getAnd(), getAShr(), getFAdd(), getFDiv(), getFMul(), getFNeg(), getFRem(), getFSub(), getLShr(), getMul(), getNot(), getOr(), getSDiv(), getShl(), getSRem(), getSub(), getUDiv(), getURem(), getWithOperands(), getXor(), simplifyAssocCastAssoc(), and llvm::InstCombinerImpl::SimplifyAssociativeOrCommutative().
getAdd()
Constant * ConstantExpr::getAdd (Constant * C1, Constant * C2, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2680 of file Constants.cpp.
References get(), llvm::OverflowingBinaryOperator::NoSignedWrap, and llvm::OverflowingBinaryOperator::NoUnsignedWrap.
Referenced by llvm::InstCombiner::AddOne(), BuildConstantFromSCEV(), computePointerICmp(), llvm::ConstantFoldGetElementPtr(), llvm::copyNonnullMetadata(), llvm::TargetFolder::CreateAdd(), llvm::ConstantFolder::CreateAdd(), llvm::InstCombinerImpl::foldAddWithConstant(), foldNoWrapAdd(), foldShiftOfShiftedLogic(), getAsConstantIndexedAddress(), llvm::InstCombiner::getFlippedStrictnessPredicateAndConstant(), LLVMConstAdd(), and matchFunnelShift().
getAddrSpaceCast()
Constant * ConstantExpr::getAddrSpaceCast (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2235 of file Constants.cpp.
References assert(), C, llvm::CastInst::castIsValid(), llvm::FixedVectorType::get(), getBitCast(), getFoldedCast(), llvm::PointerType::getWithSamePointeeType(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by cloneConstantExprWithNewAddressSpace(), getCast(), getPointerBitCastOrAddrSpaceCast(), getPointerCast(), LLVMConstAddrSpaceCast(), and operandWithNewAddressSpaceOrCreateUndef().
getAlignOf()
Constant * ConstantExpr::getAlignOf (Type * Ty) static
getAlignOf constant expr - computes the alignment of a type in a target independent way (Note: the return type is an i64).
Definition at line 2357 of file Constants.cpp.
References GEP, llvm::StructType::get(), llvm::ConstantInt::get(), getGetElementPtr(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Constant::getNullValue(), and getPtrToInt().
Referenced by LLVMAlignOf().
getAnd()
Constant * ConstantExpr::getAnd (Constant * C1, Constant * C2) static
Definition at line 2739 of file Constants.cpp.
References get().
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastOperand(), llvm::TargetFolder::CreateAnd(), llvm::ConstantFolder::CreateAnd(), ExtractConstantBytes(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), getMaskedICmpType(), and LLVMConstAnd().
getAShr()
Constant * ConstantExpr::getAShr (Constant * C1, Constant * C2, bool isExact = false) static
Definition at line 2768 of file Constants.cpp.
References get(), and llvm::PossiblyExactOperator::IsExact.
Referenced by llvm::TargetFolder::CreateAShr(), llvm::ConstantFolder::CreateAShr(), and LLVMConstAShr().
getAsInstruction()
Instruction * ConstantExpr::getAsInstruction () const
Returns an Instruction which implements the same operation as this ConstantExpr.
The instruction is not linked to any basic block.
A better approach to this could be to have a constructor for Instruction which would take a ConstantExpr parameter, but that would have spread implementation details of ConstantExpr outside of Constants.cpp, which would make it harder to remove ConstantExprs altogether.
Definition at line 3485 of file Constants.cpp.
References assert(), llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::CmpInst::Create(), llvm::GetElementPtrInst::Create(), llvm::UnaryOperator::Create(), llvm::ExtractValueInst::Create(), llvm::InsertValueInst::Create(), llvm::SelectInst::Create(), llvm::ExtractElementInst::Create(), llvm::InsertElementInst::Create(), llvm::GetElementPtrInst::CreateInBounds(), getIndices(), llvm::User::getNumOperands(), getOpcode(), getPredicate(), getShuffleMask(), llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::PossiblyExactOperator::IsExact, llvm::OverflowingBinaryOperator::NoSignedWrap, llvm::OverflowingBinaryOperator::NoUnsignedWrap, llvm::User::operands(), llvm::Instruction::setHasNoSignedWrap(), llvm::Instruction::setHasNoUnsignedWrap(), llvm::Instruction::setIsExact(), and llvm::Value::SubclassOptionalData.
getBinOpAbsorber()
Constant * ConstantExpr::getBinOpAbsorber (unsigned Opcode, Type * Ty) static
Return the absorbing element for the given binary operation, i.e.
a constant C such that X op C = C and C op X = C for every X. For example, this returns zero for integer multiplication. It returns null if the operator doesn't have an absorbing element.
Definition at line 2848 of file Constants.cpp.
References llvm::Constant::getAllOnesValue(), and llvm::Constant::getNullValue().
getBinOpIdentity()
Constant * ConstantExpr::getBinOpIdentity (unsigned Opcode, Type * Ty, bool AllowRHSConstant = false) static
Return the identity constant for a binary opcode.
The identity constant C is defined as X op C = X and C op X = X for every X when the binary operation is commutative. If the binop is not commutative, callers can acquire the operand 1 identity constant by setting AllowRHSConstant to true. For example, any shift has a zero identity constant for operand 1: X shift 0 = X. Return nullptr if the operator does not have an identity constant.
Definition at line 2802 of file Constants.cpp.
References assert(), llvm::ConstantFP::get(), llvm::ConstantInt::get(), llvm::Constant::getAllOnesValue(), llvm::ConstantFP::getNegativeZero(), llvm::Constant::getNullValue(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::Instruction::isBinaryOp(), llvm::Instruction::isCommutative(), and llvm_unreachable.
Referenced by llvm::ConstantFoldBinaryInstruction(), foldSelectBinOpIdentity(), llvm::InstCombinerImpl::foldSelectIntoOp(), foldSelectShuffleWith1Binop(), getIdentityValue(), llvm::InstCombiner::getSafeVectorConstantForBinop(), LinearizeExprTree(), llvm::InstCombinerImpl::SimplifyUsingDistributiveLaws(), and simplifyWithOpReplaced().
getBitCast()
Constant * ConstantExpr::getBitCast (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2223 of file Constants.cpp.
References assert(), C, llvm::CastInst::castIsValid(), getFoldedCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), BitCastConstantVector(), BuildConstantFromSCEV(), cloneConstantExprWithNewAddressSpace(), collectInsertionElements(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldLoadFromConstPtr(), ConstructLoadOperandConstant(), llvm::SanitizerStatReport::create(), llvm::SanitizerStatReport::finish(), FoldBitCast(), getAddrSpaceCast(), getCast(), getMemCmpLoad(), llvm::VNCoercion::getMemInstValueForLoadHelper(), getNegativeIsTrueBoolVec(), llvm::OpenMPIRBuilder::getOrCreateRuntimeFunction(), llvm::Module::getOrInsertFunction(), llvm::Module::getOrInsertGlobal(), getPointerBitCastOrAddrSpaceCast(), getPointerCast(), getSExtOrBitCast(), getTruncOrBitCast(), getZExtOrBitCast(), insertCall(), instrumentOneFunc(), llvm::isBytewiseValue(), llvm::Constant::isElementWiseEqual(), LLVMConstBitCast(), OptimizeGlobalAddressOfMalloc(), OptimizeGlobalAliases(), optimizeMemCmpConstantSize(), optimizeOnceStoredGlobal(), removeGlobalCtors(), replaceAliasWithAliasee(), replaceWithConstant(), llvm::CoroIdInst::setCoroutineSelf(), and SimplifyRelativeLoad().
getCast()
Constant * ConstantExpr::getCast (unsigned ops, Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Convenience function for getting a Cast operation.
Parameters
ops The opcode for the conversion
C The constant to be converted
Ty The type to which the constant is converted
OnlyIfReduced see getWithOperands() docs.
Definition at line 1978 of file Constants.cpp.
References assert(), C, llvm::CastInst::castIsValid(), getAddrSpaceCast(), getBitCast(), getFPExtend(), getFPToSI(), getFPToUI(), getFPTrunc(), getIntToPtr(), getPtrToInt(), getSExt(), getSIToFP(), getTrunc(), getUIToFP(), getZExt(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::Instruction::isCast(), and llvm_unreachable.
Referenced by llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCastOperand(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldLoadThroughBitcast(), llvm::TargetFolder::CreateCast(), llvm::ConstantFolder::CreateCast(), llvm::orc::createIRTypedAddress(), foldICmpWithZextOrSext(), llvm::InstCombinerImpl::foldOpIntoPhi(), getFPCast(), getIntegerCast(), getWithOperands(), lookThroughCast(), OptimizeAwayTrappingUsesOfValue(), simplifyAndOrOfCmps(), simplifyAssocCastAssoc(), and SimplifyICmpInst().
getCompare()
Constant * ConstantExpr::getCompare (unsigned short pred, Constant * C1, Constant * C2, bool OnlyIfReduced = false) static
Return an ICmp or FCmp comparison operator constant expression.
Parameters
OnlyIfReduced see getWithOperands() docs.
Definition at line 2388 of file Constants.cpp.
References assert(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, getFCmp(), getICmp(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, and llvm_unreachable.
Referenced by computeUnlikelySuccessors(), llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldCompareInstruction(), llvm::TargetFolder::CreateFCmp(), llvm::ConstantFolder::CreateFCmp(), llvm::TargetFolder::CreateICmp(), llvm::ConstantFolder::CreateICmp(), llvm::JumpThreadingPass::evaluateOnPredecessorEdge(), llvm::InstCombinerImpl::foldICmpSelectConstant(), llvm::InstCombinerImpl::foldICmpWithConstant(), llvm::InstCombinerImpl::foldOpIntoPhi(), llvm::InstCombinerImpl::FoldOpIntoSelect(), llvm::ValueLatticeElement::getCompare(), getWithOperands(), and llvm::GCNTTIImpl::instCombineIntrinsic().
getExactAShr()
static Constant * llvm::ConstantExpr::getExactAShr (Constant * C1, Constant * C2) inline static
Definition at line 1068 of file Constants.h.
getExactLogBase2()
Constant * ConstantExpr::getExactLogBase2 (Constant * C) static
If C is a scalar/fixed width vector of known powers of 2, then this function returns a new scalar/fixed width vector obtained from logBase2 of C.
Undef vector elements are set to zero. Return a null pointer otherwise.
Definition at line 2773 of file Constants.cpp.
References C, E, llvm::ConstantVector::get(), llvm::ConstantInt::get(), llvm::Constant::getNullValue(), I, llvm::APInt::isPowerOf2(), llvm::APInt::logBase2(), llvm::PatternMatch::m_APInt(), and llvm::PatternMatch::match().
Referenced by detectShiftUntilBitTestIdiom(), foldUDivPow2Cst(), foldUDivShl(), llvm::InstCombinerImpl::visitMul(), and llvm::InstCombinerImpl::visitSDiv().
getExactLShr()
static Constant * llvm::ConstantExpr::getExactLShr (Constant * C1, Constant * C2) inline static
Definition at line 1072 of file Constants.h.
getExactSDiv()
static Constant * llvm::ConstantExpr::getExactSDiv (Constant * C1, Constant * C2) inline static
Definition at line 1060 of file Constants.h.
Referenced by LLVMConstExactSDiv().
getExactUDiv()
static Constant * llvm::ConstantExpr::getExactUDiv (Constant * C1, Constant * C2) inline static
Definition at line 1064 of file Constants.h.
Referenced by LLVMConstExactUDiv().
getExtractElement()
Constant * ConstantExpr::getExtractElement (Constant * Vec, Constant * Idx, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2542 of file Constants.cpp.
References assert(), llvm::ConstantFoldExtractElementInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::Value::getContext(), llvm::Value::getType(), Idx, llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::Type::isVectorTy(), and llvm::LLVMContext::pImpl.
Referenced by BitCastConstantVector(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldExtractElementInstruction(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::ConstantFoldUnaryInstruction(), llvm::TargetFolder::CreateExtractElement(), llvm::ConstantFolder::CreateExtractElement(), getWithOperands(), LLVMConstExtractElement(), and SimplifyExtractElementInst().
getExtractValue()
Constant * ConstantExpr::getExtractValue (Constant * Agg, ArrayRef< unsigned > Idxs, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2637 of file Constants.cpp.
References assert(), llvm::ConstantFoldExtractValueInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::ExtractValueInst::getIndexedType(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::ConstantFoldInstruction(), llvm::TargetFolder::CreateExtractValue(), llvm::ConstantFolder::CreateExtractValue(), llvm::InstCombinerImpl::foldCmpLoadFromIndexedGlobal(), getWithOperands(), and LLVMConstExtractValue().
getFAdd()
Constant * ConstantExpr::getFAdd (Constant * C1, Constant * C2) static
Definition at line 2687 of file Constants.cpp.
References get().
Referenced by llvm::TargetFolder::CreateFAdd(), llvm::ConstantFolder::CreateFAdd(), and LLVMConstFAdd().
getFCmp()
Constant * ConstantExpr::getFCmp (unsigned short pred, Constant * LHS, Constant * RHS, bool OnlyIfReduced = false) static
Definition at line 2517 of file Constants.cpp.
References assert(), llvm::ConstantFoldCompareInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::VectorType::get(), llvm::Type::getInt1Ty(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::CmpInst::isFPPredicate(), and pred.
Referenced by evaluateFCmpRelation(), getCompare(), and LLVMConstFCmp().
getFDiv()
Constant * ConstantExpr::getFDiv (Constant * C1, Constant * C2) static
Definition at line 2723 of file Constants.cpp.
References get(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::TargetFolder::CreateFDiv(), llvm::ConstantFolder::CreateFDiv(), foldFDivConstantDividend(), foldFDivConstantDivisor(), LLVMConstFDiv(), and llvm::InstCombinerImpl::visitFMul().
getFMul()
Constant * ConstantExpr::getFMul (Constant * C1, Constant * C2) static
Definition at line 2709 of file Constants.cpp.
References get().
Referenced by llvm::TargetFolder::CreateFMul(), llvm::ConstantFolder::CreateFMul(), foldFDivConstantDividend(), LLVMConstFMul(), and llvm::InstCombinerImpl::visitFMul().
getFNeg()
Constant * ConstantExpr::getFNeg (Constant * C) static
Definition at line 2668 of file Constants.cpp.
References assert(), C, get(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::TargetFolder::CreateFNeg(), llvm::ConstantFolder::CreateFNeg(), foldFDivConstantDividend(), foldFDivConstantDivisor(), foldFNegIntoConstant(), getWithOperands(), LLVMConstFNeg(), NegateValue(), llvm::InstCombinerImpl::visitFCmpInst(), llvm::InstCombinerImpl::visitFMul(), and llvm::InstCombinerImpl::visitFSub().
getFPCast()
Constant * ConstantExpr::getFPCast (Constant * C, Type * Ty) static
Create a FPExt, Bitcast or FPTrunc for fp -> fp casts.
Parameters
C The integer constant to be casted
Ty The integer type to cast to
Definition at line 2073 of file Constants.cpp.
References assert(), C, getCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::TargetFolder::CreateFPCast(), llvm::ConstantFolder::CreateFPCast(), and LLVMConstFPCast().
getFPExtend()
Constant * ConstantExpr::getFPExtend (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2139 of file Constants.cpp.
References assert(), C, and getFoldedCast().
Referenced by getCast(), LLVMConstFPExt(), and lookThroughCast().
getFPToSI()
Constant * ConstantExpr::getFPToSI (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2184 of file Constants.cpp.
References assert(), C, getFoldedCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::InstCombinerImpl::foldFCmpIntToFPConst(), getCast(), LLVMConstFPToSI(), lookThroughCast(), and llvm::InstCombinerImpl::visitFAdd().
getFPToUI()
Constant * ConstantExpr::getFPToUI (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2173 of file Constants.cpp.
References assert(), C, getFoldedCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::InstCombinerImpl::foldFCmpIntToFPConst(), getCast(), LLVMConstFPToUI(), and lookThroughCast().
getFPTrunc()
Constant * ConstantExpr::getFPTrunc (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2127 of file Constants.cpp.
References assert(), C, getFoldedCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by getCast(), llvm::AA::getWithType(), LLVMConstFPTrunc(), and lookThroughCast().
getFRem()
Constant * ConstantExpr::getFRem (Constant * C1, Constant * C2) static
Definition at line 2735 of file Constants.cpp.
References get(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::TargetFolder::CreateFRem(), llvm::ConstantFolder::CreateFRem(), and LLVMConstFRem().
getFSub()
Constant * ConstantExpr::getFSub (Constant * C1, Constant * C2) static
Definition at line 2698 of file Constants.cpp.
References get().
Referenced by llvm::TargetFolder::CreateFSub(), llvm::ConstantFolder::CreateFSub(), LLVMConstFSub(), and llvm::InstCombinerImpl::visitFSub().
getGetElementPtr() [1/3]
static Constant * llvm::ConstantExpr::getGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList, bool InBounds = false, Optional< unsigned > InRangeIndex = None, Type * OnlyIfReducedTy = nullptr) inline static
Getelementptr form.
Value* is only accepted for convenience; all elements must be Constants.
Parameters
InRangeIndex the inrange index if present or None.
OnlyIfReducedTy see getWithOperands() docs.
Definition at line 1210 of file Constants.h.
References C, and llvm::makeArrayRef().
Referenced by llvm::VNCoercion::analyzeLoadFromClobberingMemInst(), BuildConstantFromSCEV(), llvm::ConstantFoldGetElementPtr(), ConstructLoadOperandConstant(), llvm::SanitizerStatReport::create(), llvm::TargetFolder::CreateGetElementPtr(), llvm::ConstantFolder::CreateGetElementPtr(), llvm::NoFolder::CreateGetElementPtr(), llvm::TargetFolder::CreateGetElementPtr(), llvm::ConstantFolder::CreateGetElementPtr(), llvm::TargetFolder::CreateGetElementPtr(), llvm::ConstantFolder::CreateGetElementPtr(), llvm::NoFolder::CreateGetElementPtr(), evaluateBitcastFromPtr(), foldGEPOfGEP(), getAlignOf(), llvm::VNCoercion::getMemInstValueForLoadHelper(), getOffsetOf(), getSizeOf(), llvm::ScalarEvolution::getSizeOfScalableVectorExpr(), getWithOperands(), LLVMConstGEP(), OptimizeAwayTrappingUsesOfValue(), SimplifyGEPInst(), SimplifyICmpInst(), SimplifyRelativeLoad(), splitGlobal(), and SRAGlobal().
getGetElementPtr() [2/3]
Constant * ConstantExpr::getGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList, bool InBounds = false, Optional< unsigned > InRangeIndex = None, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2427 of file Constants.cpp.
References assert(), C, llvm::ConstantFoldGetElementPtr(), llvm::LLVMContextImpl::ExprConstants, llvm::gep_type_begin(), llvm::gep_type_end(), llvm::VectorType::get(), llvm::PointerType::get(), llvm::LinearPolySize< ElementCount >::getFixed(), llvm::GetElementPtrInst::getIndexedType(), llvm::ConstantVector::getSplat(), Idx, llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm::None.
getGetElementPtr() [3/3]
static Constant * llvm::ConstantExpr::getGetElementPtr (Type * Ty, Constant * C, Constant * Idx, bool InBounds = false, Optional< unsigned > InRangeIndex = None, Type * OnlyIfReducedTy = nullptr) inline static
Definition at line 1219 of file Constants.h.
References C, and Idx.
getICmp()
Constant * ConstantExpr::getICmp (unsigned short pred, Constant * LHS, Constant * RHS, bool OnlyIfReduced = false) static
get* - Return some common constants without having to specify the full Instruction::OPCODE identifier.
Definition at line 2492 of file Constants.cpp.
References assert(), llvm::ConstantFoldCompareInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::VectorType::get(), llvm::Type::getInt1Ty(), llvm::CmpInst::isIntPredicate(), and pred.
Referenced by computePointerICmp(), llvm::ConstantFoldCompareInstruction(), evaluateICmpRelation(), llvm::InstCombinerImpl::foldICmpInstWithConstantNotInt(), getCompare(), getNegativeIsTrueBoolVec(), getUMin(), llvm::Constant::isElementWiseEqual(), LLVMConstICmp(), reuseTableCompare(), SimplifyICmpInst(), llvm::ScalarEvolution::SimplifyICmpOperands(), and llvm::InstCombinerImpl::visitCallInst().
getInBoundsGetElementPtr() [1/3]
static Constant * llvm::ConstantExpr::getInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) inline static
Create an "inbounds" getelementptr.
See the documentation for the "inbounds" flag in LangRef.html for details.
Definition at line 1237 of file Constants.h.
References C.
Referenced by llvm::IRBuilderBase::CreateGlobalStringPtr(), llvm::TargetFolder::CreateInBoundsGetElementPtr(), llvm::ConstantFolder::CreateInBoundsGetElementPtr(), llvm::NoFolder::CreateInBoundsGetElementPtr(), llvm::TargetFolder::CreateInBoundsGetElementPtr(), llvm::ConstantFolder::CreateInBoundsGetElementPtr(), llvm::TargetFolder::CreateInBoundsGetElementPtr(), llvm::ConstantFolder::CreateInBoundsGetElementPtr(), llvm::NoFolder::CreateInBoundsGetElementPtr(), FoldBitCast(), and LLVMConstInBoundsGEP().
getInBoundsGetElementPtr() [2/3]
static Constant * llvm::ConstantExpr::getInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) inline static
Definition at line 1248 of file Constants.h.
References C.
getInBoundsGetElementPtr() [3/3]
static Constant * llvm::ConstantExpr::getInBoundsGetElementPtr (Type * Ty, Constant * C, Constant * Idx) inline static
Definition at line 1241 of file Constants.h.
References C, and Idx.
getIndices()
ArrayRef< unsigned > ConstantExpr::getIndices () const
Assert that this is an insertvalue or exactvalue expression and return the list of indices.
Definition at line 1493 of file Constants.cpp.
Referenced by getAsInstruction(), and getWithOperands().
getInsertElement()
Constant * ConstantExpr::getInsertElement (Constant * Vec, Constant * Elt, Constant * Idx, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2564 of file Constants.cpp.
References assert(), llvm::ConstantFoldInsertElementInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::Value::getContext(), llvm::Value::getType(), Idx, llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::Type::isVectorTy(), and llvm::LLVMContext::pImpl.
Referenced by llvm::TargetFolder::CreateInsertElement(), llvm::ConstantFolder::CreateInsertElement(), llvm::ConstantVector::getSplat(), getWithOperands(), LLVMConstInsertElement(), and llvm::SimplifyInsertElementInst().
getInsertValue()
Constant * ConstantExpr::getInsertValue (Constant * Agg, Constant * Val, ArrayRef< unsigned > Idxs, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2613 of file Constants.cpp.
References assert(), llvm::ConstantFoldInsertValueInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::ExtractValueInst::getIndexedType(), llvm::Value::getType(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::ConstantFoldInstruction(), llvm::TargetFolder::CreateInsertValue(), llvm::ConstantFolder::CreateInsertValue(), getWithOperands(), and LLVMConstInsertValue().
getIntegerCast()
Constant * ConstantExpr::getIntegerCast (Constant * C, Type * Ty, bool IsSigned) static
Create a ZExt, Bitcast or Trunc for integer -> integer casts.
Parameters
C The integer constant to be casted
Ty The integer type to cast to
IsSigned Whether C should be treated as signed or not
Definition at line 2061 of file Constants.cpp.
References assert(), C, getCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::ConstantFoldCastOperand(), llvm::ConstantFoldCompareInstOperands(), llvm::TargetFolder::CreateIntCast(), llvm::ConstantFolder::CreateIntCast(), createMalloc(), llvm::EmitGEPOffset(), llvm::InstCombinerImpl::EvaluateInDifferentType(), GetConstantInt(), llvm::isBytewiseValue(), LLVMConstIntCast(), lookThroughCast(), llvm::AsmPrinter::lowerConstant(), processUse(), SimplifySubInst(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitTrunc().
getIntToPtr()
Constant * ConstantExpr::getIntToPtr (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2209 of file Constants.cpp.
References assert(), C, getFoldedCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::SanitizerStatReport::create(), llvm::InstCombinerImpl::foldICmpWithCastOp(), getCast(), llvm::Constant::getIntegerValue(), LLVMConstIntToPtr(), SegmentOffset(), SimplifyGEPInst(), SimplifyICmpInst(), llvm::UpgradeBitCastExpr(), and llvm::BasicBlock::~BasicBlock().
getLShr()
Constant * ConstantExpr::getLShr (Constant * C1, Constant * C2, bool isExact = false) static
Definition at line 2763 of file Constants.cpp.
References get(), and llvm::PossiblyExactOperator::IsExact.
Referenced by collectInsertionElements(), llvm::ConstantFoldBinaryInstruction(), llvm::TargetFolder::CreateLShr(), llvm::ConstantFolder::CreateLShr(), dropRedundantMaskingOfLeftShiftInput(), ExtractConstantBytes(), and LLVMConstLShr().
getMul()
Constant * ConstantExpr::getMul (Constant * C1, Constant * C2, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2702 of file Constants.cpp.
References get(), llvm::OverflowingBinaryOperator::NoSignedWrap, and llvm::OverflowingBinaryOperator::NoUnsignedWrap.
Referenced by BuildConstantFromSCEV(), llvm::ComputeMultiple(), createMalloc(), llvm::TargetFolder::CreateMul(), llvm::ConstantFolder::CreateMul(), llvm::EmitGEPOffset(), LLVMConstMul(), and llvm::InstCombinerImpl::visitCallInst().
getNeg()
Constant * ConstantExpr::getNeg (Constant * C, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2661 of file Constants.cpp.
References assert(), C, getSub(), and llvm::ConstantFP::getZeroValueForNegation().
Referenced by llvm::TargetFolder::CreateNeg(), llvm::ConstantFolder::CreateNeg(), llvm::InstCombinerImpl::foldICmpAddConstant(), llvm::InstCombinerImpl::foldICmpAndConstConst(), llvm::InstCombinerImpl::foldICmpBinOp(), llvm::ScalarEvolution::getNegativeSCEV(), LLVMConstNeg(), matchIncrement(), NegateValue(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitSDiv(), and llvm::InstCombinerImpl::visitSRem().
getNot()
Constant * ConstantExpr::getNot (Constant * C) static
Definition at line 2674 of file Constants.cpp.
References assert(), C, get(), and llvm::Constant::getAllOnesValue().
Referenced by llvm::JumpThreadingPass::computeValueKnownInPredecessorsImpl(), llvm::ConstantFoldCompareInstruction(), llvm::TargetFolder::CreateNot(), llvm::ConstantFolder::CreateNot(), dropRedundantMaskingOfLeftShiftInput(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), llvm::ScalarEvolution::getNotSCEV(), llvm::invertCondition(), LLVMConstNot(), simplifyLogicOfAddSub(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitXor().
getNSWAdd()
static Constant * llvm::ConstantExpr::getNSWAdd (Constant * C1, Constant * C2) inline static
Definition at line 1028 of file Constants.h.
Referenced by LLVMConstNSWAdd().
getNSWMul()
static Constant * llvm::ConstantExpr::getNSWMul (Constant * C1, Constant * C2) inline static
Definition at line 1044 of file Constants.h.
Referenced by LLVMConstNSWMul().
getNSWNeg()
static Constant * llvm::ConstantExpr::getNSWNeg (Constant * C) inline static
Definition at line 1025 of file Constants.h.
References C.
Referenced by LLVMConstNSWNeg().
getNSWShl()
static Constant * llvm::ConstantExpr::getNSWShl (Constant * C1, Constant * C2) inline static
Definition at line 1052 of file Constants.h.
getNSWSub()
static Constant * llvm::ConstantExpr::getNSWSub (Constant * C1, Constant * C2) inline static
Definition at line 1036 of file Constants.h.
Referenced by LLVMConstNSWSub().
getNUWAdd()
static Constant * llvm::ConstantExpr::getNUWAdd (Constant * C1, Constant * C2) inline static
Definition at line 1032 of file Constants.h.
Referenced by LLVMConstNUWAdd().
getNUWMul()
static Constant * llvm::ConstantExpr::getNUWMul (Constant * C1, Constant * C2) inline static
Definition at line 1048 of file Constants.h.
Referenced by LLVMConstNUWMul().
getNUWNeg()
static Constant * llvm::ConstantExpr::getNUWNeg (Constant * C) inline static
Definition at line 1026 of file Constants.h.
References C.
Referenced by LLVMConstNUWNeg().
getNUWShl()
static Constant * llvm::ConstantExpr::getNUWShl (Constant * C1, Constant * C2) inline static
Definition at line 1056 of file Constants.h.
Referenced by llvm::InstCombinerImpl::foldICmpAndConstConst().
getNUWSub()
static Constant * llvm::ConstantExpr::getNUWSub (Constant * C1, Constant * C2) inline static
Definition at line 1040 of file Constants.h.
Referenced by LLVMConstNUWSub().
getOffsetOf() [1/2]
Constant * ConstantExpr::getOffsetOf (StructType * STy, unsigned FieldNo) static
getOffsetOf constant expr - computes the offset of a struct field in a target independent way (Note: the return type is an i64).
Definition at line 2370 of file Constants.cpp.
References llvm::ConstantInt::get(), llvm::Type::getContext(), llvm::Type::getInt32Ty(), and getOffsetOf().
Referenced by getOffsetOf().
getOffsetOf() [2/2]
Constant * ConstantExpr::getOffsetOf (Type * Ty, Constant * FieldNo) static
getOffsetOf constant expr - This is a generalized form of getOffsetOf, which supports any aggregate type, and any Constant index.
Definition at line 2375 of file Constants.cpp.
References GEP, llvm::ConstantInt::get(), getGetElementPtr(), llvm::Type::getInt64Ty(), llvm::Constant::getNullValue(), getPtrToInt(), and llvm::PointerType::getUnqual().
getOpcode()
unsigned llvm::ConstantExpr::getOpcode () const inline
Return the opcode at the root of this constant expression.
Definition at line 1267 of file Constants.h.
Referenced by getAsInstruction(), getOpcodeName(), getWithOperands(), hasIndices(), isCast(), isCompare(), and isGEPWithNoNotionalOverIndexing().
getOpcodeName()
const char * ConstantExpr::getOpcodeName () const
Return a string representation for an opcode.
Definition at line 2868 of file Constants.cpp.
References getOpcode(), and llvm::Instruction::getOpcodeName().
getOr()
Constant * ConstantExpr::getOr (Constant * C1, Constant * C2) static
Definition at line 2743 of file Constants.cpp.
References get().
Referenced by llvm::TargetFolder::CreateOr(), llvm::ConstantFolder::CreateOr(), ExtractConstantBytes(), llvm::InstCombinerImpl::foldICmpAndConstConst(), foldLogOpOfMaskedICmps(), LLVMConstOr(), llvm::InstCombinerImpl::visitOr(), and llvm::InstCombinerImpl::visitTrunc().
getPointerBitCastOrAddrSpaceCast()
Constant * ConstantExpr::getPointerBitCastOrAddrSpaceCast (Constant * C, Type * Ty) static
Create a BitCast or AddrSpaceCast for a pointer type depending on the address space.
Parameters
C The constant to addrspacecast or bitcast
Ty The type to bitcast or addrspacecast C to
Definition at line 2050 of file Constants.cpp.
References assert(), getAddrSpaceCast(), getBitCast(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), and llvm::Type::isPtrOrPtrVectorTy().
Referenced by appendToUsedList(), llvm::TargetFolder::CreatePointerBitCastOrAddrSpaceCast(), llvm::ConstantFolder::CreatePointerBitCastOrAddrSpaceCast(), llvm::EmbedBitcodeInModule(), llvm::InstCombinerImpl::foldGEPICmp(), and setUsedInitializer().
getPointerCast()
Constant * ConstantExpr::getPointerCast (Constant * C, Type * Ty) static
Create a BitCast, AddrSpaceCast, or a PtrToInt cast constant expression.
Parameters
C The pointer value to be casted (operand 0)
Ty The type to which cast should be made
Definition at line 2035 of file Constants.cpp.
References assert(), getAddrSpaceCast(), getBitCast(), llvm::Type::getPointerAddressSpace(), getPtrToInt(), llvm::Value::getType(), and llvm::Type::isPtrOrPtrVectorTy().
Referenced by appendToGlobalArray(), llvm::ConstantFoldCastInstruction(), llvm::TargetFolder::CreatePointerCast(), llvm::ConstantFolder::CreatePointerCast(), llvm::OpenMPIRBuilder::getOrCreateSrcLocStr(), llvm::AA::getWithType(), INITIALIZE_PASS(), LLVMConstPointerCast(), and setCoroInfo().
getPredicate()
unsigned ConstantExpr::getPredicate () const
Return the ICMP or FCMP predicate value.
Assert if this is not an ICMP or FCMP constant expression.
Definition at line 1501 of file Constants.cpp.
Referenced by getAsInstruction(), and getWithOperands().
getPtrToInt()
Constant * ConstantExpr::getPtrToInt (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2195 of file Constants.cpp.
References assert(), C, and getFoldedCast().
Referenced by BuildConstantFromSCEV(), llvm::copyNonnullMetadata(), createRelLookupTable(), getAlignOf(), getCast(), getOffsetOf(), llvm::Value::getPointerAlignment(), getPointerCast(), getSizeOf(), llvm::ScalarEvolution::getSizeOfScalableVectorExpr(), LLVMConstPtrToInt(), and llvm::UpgradeBitCastExpr().
getSDiv()
Constant * ConstantExpr::getSDiv (Constant * C1, Constant * C2, bool isExact = false) static
Definition at line 2718 of file Constants.cpp.
References get(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm::PossiblyExactOperator::IsExact.
Referenced by llvm::ConstantFoldGetElementPtr(), llvm::TargetFolder::CreateSDiv(), llvm::ConstantFolder::CreateSDiv(), and LLVMConstSDiv().
getSelect()
Constant * ConstantExpr::getSelect (Constant * C, Constant * V1, Constant * V2, Type * OnlyIfReducedTy = nullptr) static
Select constant expr.
Parameters
OnlyIfReducedTy see getWithOperands() docs.
Definition at line 2410 of file Constants.cpp.
References llvm::SelectInst::areInvalidOperands(), assert(), C, llvm::ConstantFoldSelectInstruction(), and llvm::LLVMContextImpl::ExprConstants.
Referenced by cloneConstantExprWithNewAddressSpace(), llvm::ConstantFoldSelectInstruction(), llvm::TargetFolder::CreateSelect(), llvm::ConstantFolder::CreateSelect(), getUMin(), getWithOperands(), and LLVMConstSelect().
getSExt()
Constant * ConstantExpr::getSExt (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2099 of file Constants.cpp.
References assert(), C, and getFoldedCast().
Referenced by BuildConstantFromSCEV(), llvm::ConstantFoldGetElementPtr(), foldLogicCastConstant(), foldNoWrapAdd(), getCast(), getSExtOrBitCast(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::GCNTTIImpl::instCombineIntrinsic(), LLVMConstSExt(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitSExt().
getSExtOrBitCast()
Constant * ConstantExpr::getSExtOrBitCast (Constant * C, Type * Ty) static
Parameters
C The constant to sext or bitcast
Ty The type to sext or bitcast C to
Definition at line 2023 of file Constants.cpp.
References C, getBitCast(), and getSExt().
Referenced by llvm::TargetFolder::CreateSExtOrBitCast(), llvm::ConstantFolder::CreateSExtOrBitCast(), foldGEPOfGEP(), getAsConstantIndexedAddress(), and LLVMConstSExtOrBitCast().
getShl()
Constant * ConstantExpr::getShl (Constant * C1, Constant * C2, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2756 of file Constants.cpp.
References get(), llvm::OverflowingBinaryOperator::NoSignedWrap, and llvm::OverflowingBinaryOperator::NoUnsignedWrap.
Referenced by ConvertShiftToMul(), llvm::TargetFolder::CreateShl(), llvm::ConstantFolder::CreateShl(), dropRedundantMaskingOfLeftShiftInput(), llvm::InstCombinerImpl::FoldShiftByConstant(), getAlternateBinop(), getBinOpsForFactorization(), LLVMConstShl(), llvm::InstCombinerImpl::visitMul(), llvm::InstCombinerImpl::visitShl(), and llvm::InstCombinerImpl::visitTrunc().
getShuffleMask()
ArrayRef< int > ConstantExpr::getShuffleMask () const
Assert that this is a shufflevector and return the mask.
See class ShuffleVectorInst for a description of the mask representation.
Definition at line 1505 of file Constants.cpp.
Referenced by getAsInstruction(), and getWithOperands().
getShuffleMaskForBitcode()
Constant * ConstantExpr::getShuffleMaskForBitcode () const
Assert that this is a shufflevector and return the mask.
TODO: This is a temporary hack until we update the bitcode format for shufflevector.
Definition at line 1509 of file Constants.cpp.
getShuffleVector()
Constant * ConstantExpr::getShuffleVector (Constant * V1, Constant * V2, ArrayRef< int > Mask, Type * OnlyIfReducedTy = nullptr) static
Definition at line 2587 of file Constants.cpp.
References assert(), llvm::ConstantFoldShuffleVectorInstruction(), llvm::LLVMContextImpl::ExprConstants, llvm::VectorType::get(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::ShuffleVectorInst::isValidOperands(), and llvm::None.
Referenced by llvm::TargetFolder::CreateShuffleVector(), llvm::ConstantFolder::CreateShuffleVector(), evaluateInDifferentElementOrder(), foldSelectShuffle(), foldSelectShuffleWith1Binop(), llvm::ConstantVector::getSplat(), getWithOperands(), LLVMConstShuffleVector(), and SimplifyShuffleVectorInst().
getSIToFP()
Constant * ConstantExpr::getSIToFP (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2162 of file Constants.cpp.
References assert(), C, getFoldedCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::InstCombinerImpl::foldFCmpIntToFPConst(), getCast(), LLVMConstSIToFP(), lookThroughCast(), and llvm::InstCombinerImpl::visitFAdd().
getSizeOf()
Constant * ConstantExpr::getSizeOf (Type * Ty) static
getSizeOf constant expr - computes the (alloc) size of a type (in address-units, not bits) in a target independent way (Note: the return type is an i64).
Definition at line 2347 of file Constants.cpp.
References GEP, llvm::ConstantInt::get(), getGetElementPtr(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Constant::getNullValue(), getPtrToInt(), and llvm::PointerType::getUnqual().
Referenced by llvm::IRBuilderBase::CreatePtrDiff(), LLVMBuildArrayMalloc(), LLVMBuildMalloc(), and LLVMSizeOf().
getSRem()
Constant * ConstantExpr::getSRem (Constant * C1, Constant * C2) static
Definition at line 2731 of file Constants.cpp.
References get(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::ConstantFoldGetElementPtr(), llvm::TargetFolder::CreateSRem(), llvm::ConstantFolder::CreateSRem(), and LLVMConstSRem().
getSub()
Constant * ConstantExpr::getSub (Constant * C1, Constant * C2, bool HasNUW = false, bool HasNSW = false) static
Definition at line 2691 of file Constants.cpp.
References get(), llvm::OverflowingBinaryOperator::NoSignedWrap, and llvm::OverflowingBinaryOperator::NoUnsignedWrap.
Referenced by llvm::InstCombinerImpl::commonShiftTransforms(), computePointerDifference(), createRelLookupTable(), llvm::TargetFolder::CreateSub(), llvm::ConstantFolder::CreateSub(), dropRedundantMaskingOfLeftShiftInput(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), getNeg(), LLVMConstSub(), llvm::InstCombiner::SubOne(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitSExt(), llvm::InstCombinerImpl::visitSub(), and llvm::InstCombinerImpl::visitSwitchInst().
getTrunc()
Constant * ConstantExpr::getTrunc (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2085 of file Constants.cpp.
References assert(), C, and getFoldedCast().
Referenced by BuildConstantFromSCEV(), collectInsertionElements(), llvm::ConstantFoldCompareInstruction(), createRelLookupTable(), dropRedundantMaskingOfLeftShiftInput(), ExtractConstantBytes(), foldICmpWithZextOrSext(), foldLogicCastConstant(), llvm::InstCombinerImpl::foldPHIArgZextsIntoPHI(), getCast(), llvm::ScalarEvolution::getTruncateExpr(), getTruncOrBitCast(), llvm::AA::getWithType(), LLVMConstTrunc(), lookThroughCast(), narrowUDivURem(), SimplifyICmpInst(), llvm::InstCombinerImpl::visitAnd(), llvm::InstCombinerImpl::visitCallInst(), llvm::InstCombinerImpl::visitSDiv(), and llvm::InstCombinerImpl::visitTrunc().
getTruncOrBitCast()
Constant * ConstantExpr::getTruncOrBitCast (Constant * C, Type * Ty) static
Parameters
C The constant to trunc or bitcast
Ty The type to trunc or bitcast C to
Definition at line 2029 of file Constants.cpp.
References C, getBitCast(), and getTrunc().
Referenced by llvm::TargetFolder::CreateTruncOrBitCast(), llvm::ConstantFolder::CreateTruncOrBitCast(), LLVMBuildArrayMalloc(), LLVMBuildMalloc(), and LLVMConstTruncOrBitCast().
getUDiv()
Constant * ConstantExpr::getUDiv (Constant * C1, Constant * C2, bool isExact = false) static
Definition at line 2713 of file Constants.cpp.
References get(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm::PossiblyExactOperator::IsExact.
Referenced by BuildConstantFromSCEV(), llvm::TargetFolder::CreateUDiv(), llvm::ConstantFolder::CreateUDiv(), llvm::ScalarEvolution::getUDivExpr(), and LLVMConstUDiv().
getUIToFP()
Constant * ConstantExpr::getUIToFP (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2151 of file Constants.cpp.
References assert(), C, getFoldedCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::InstCombinerImpl::foldFCmpIntToFPConst(), getCast(), LLVMConstUIToFP(), and lookThroughCast().
getUMin()
Constant * ConstantExpr::getUMin (Constant * C1, Constant * C2) static
Definition at line 2751 of file Constants.cpp.
References getICmp(), getSelect(), and llvm::CmpInst::ICMP_ULT.
Referenced by llvm::InstCombinerImpl::visitTrunc().
getURem()
Constant * ConstantExpr::getURem (Constant * C1, Constant * C2) static
Definition at line 2727 of file Constants.cpp.
References get(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::TargetFolder::CreateURem(), llvm::ConstantFolder::CreateURem(), LLVMConstURem(), and llvm::InstCombinerImpl::visitCallInst().
getWithOperandReplaced()
Constant * ConstantExpr::getWithOperandReplaced (unsigned OpNo, Constant * Op) const
Return a constant expression identical to this one, but with the specified operand set to the specified value.
Definition at line 1514 of file Constants.cpp.
References assert(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Value::getType(), getWithOperands(), and llvm::User::Op().
getWithOperands() [1/2]
Constant * llvm::ConstantExpr::getWithOperands (ArrayRef< Constant * > Ops) const inline
This returns the current constant expression with the operands replaced with the specified values.
The specified array must have the same number of operands as our current one.
Definition at line 1297 of file Constants.h.
References getType().
Referenced by getWithOperandReplaced().
getWithOperands() [2/2]
Constant * ConstantExpr::getWithOperands (ArrayRef< Constant * > Ops, Type * Ty, bool OnlyIfReduced = false, Type * SrcTy = nullptr) const
Get the current expression with the operands replaced.
Return the current constant expression with the operands replaced with Ops and the type with Ty. The new operands must have the same number as the current ones.
If OnlyIfReduced is true, nullptr will be returned unless something gets constant-folded, the type changes, or the expression is otherwise canonicalized. This parameter should almost always be false.
Definition at line 1527 of file Constants.cpp.
References assert(), get(), getCast(), getCompare(), getExtractElement(), getExtractValue(), getFNeg(), getGetElementPtr(), getIndices(), getInsertElement(), getInsertValue(), llvm::User::getNumOperands(), getOpcode(), llvm::User::getOperand(), getPredicate(), getSelect(), getShuffleMask(), getShuffleVector(), llvm::Value::getType(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), llvm::User::op_begin(), and llvm::Value::SubclassOptionalData.
getXor()
Constant * ConstantExpr::getXor (Constant * C1, Constant * C2) static
Definition at line 2747 of file Constants.cpp.
References get().
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::TargetFolder::CreateXor(), llvm::ConstantFolder::CreateXor(), llvm::InstCombinerImpl::foldICmpBinOpEqualityWithConstant(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmps_NotAllZeros_BMask_Mixed(), and LLVMConstXor().
getZExt()
Constant * ConstantExpr::getZExt (Constant * C, Type * Ty, bool OnlyIfReduced = false) static
Definition at line 2113 of file Constants.cpp.
References assert(), C, and getFoldedCast().
Referenced by BuildConstantFromSCEV(), llvm::ComputeMultiple(), dropRedundantMaskingOfLeftShiftInput(), foldLogicCastConstant(), foldNoWrapAdd(), llvm::InstCombinerImpl::foldPHIArgZextsIntoPHI(), llvm::InstCombinerImpl::FoldShiftByConstant(), getCast(), llvm::ScalarEvolution::getZeroExtendExpr(), getZExtOrBitCast(), LLVMConstZExt(), narrowUDivURem(), llvm::InstCombinerImpl::visitCallInst(), and llvm::InstCombinerImpl::visitZExt().
getZExtOrBitCast()
Constant * ConstantExpr::getZExtOrBitCast (Constant * C, Type * Ty) static
Parameters
C The constant to zext or bitcast
Ty The type to zext or bitcast C to
Definition at line 2017 of file Constants.cpp.
References C, getBitCast(), and getZExt().
Referenced by llvm::TargetFolder::CreateZExtOrBitCast(), llvm::ConstantFolder::CreateZExtOrBitCast(), foldShiftIntoShiftInAnotherHandOfAndInICmp(), LLVMConstZExtOrBitCast(), and llvm::InstCombinerImpl::reassociateShiftAmtsOfTwoSameDirectionShifts().
hasIndices()
bool ConstantExpr::hasIndices () const
Return true if this is an insertvalue or extractvalue expression, and the getIndices() method may be used.
Definition at line 1488 of file Constants.cpp.
References getOpcode(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
isCast()
bool ConstantExpr::isCast () const
Return true if this is a convert constant expression.
Definition at line 1458 of file Constants.cpp.
References getOpcode(), and llvm::Instruction::isCast().
isCompare()
bool ConstantExpr::isCompare () const
Return true if this is a compare constant expression.
Definition at line 1462 of file Constants.cpp.
References getOpcode(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
isGEPWithNoNotionalOverIndexing()
bool ConstantExpr::isGEPWithNoNotionalOverIndexing () const
Return true if this is a getelementptr expression and all the index operands are compile-time known integers within the corresponding notional static array extents.
Note that this is not equivalant to, a subset of, or a superset of the "inbounds" property.
Definition at line 1466 of file Constants.cpp.
References E, llvm::gep_type_begin(), llvm::gep_type_end(), getOpcode(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm::User::op_begin().
Friends And Related Symbol Documentation
Constant
friend class Constant friend
Definition at line 938 of file Constants.h.
ConstantExprKeyType
friend struct ConstantExprKeyType friend
Definition at line 937 of file Constants.h.
The documentation for this class was generated from the following files:
include/llvm/IR/Constants.h
lib/IR/Constants.cpp