LLVM: llvm::orc::shared::SerializationTraits< ChannelT, Optional< T > > Class Template Reference
llvm::orc::shared::SerializationTraits< ChannelT, Optional< T > > Class Template Reference
#include "llvm/ExecutionEngine/Orc/Shared/Serialization.h"
Static Public Member Functions
static Error serialize (ChannelT &C, const Optional< T > &O)
Serialize an Optional<T>.
static Error deserialize (ChannelT &C, Optional< T > &O)
Deserialize an Optional<T>.
Detailed Description
template<typename ChannelT, typename T>
class llvm::orc::shared::SerializationTraits< ChannelT, Optional< T > >
Definition at line 556 of file Serialization.h.
Member Function Documentation
deserialize()
template<typename ChannelT , typename T > static Error llvm::orc::shared::SerializationTraits< ChannelT, Optional< T > >::deserialize (ChannelT & C, Optional< T > & O) inline static
Deserialize an Optional<T>.
Definition at line 569 of file Serialization.h.
References C, llvm::orc::shared::deserializeSeq(), llvm::HasValue(), and llvm::Error::success().
serialize()
template<typename ChannelT , typename T > static Error llvm::orc::shared::SerializationTraits< ChannelT, Optional< T > >::serialize (ChannelT & C, const Optional< T > & O) inline static
Serialize an Optional<T>.
Definition at line 559 of file Serialization.h.
References C, llvm::None, llvm::orc::shared::serializeSeq(), and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/Serialization.h