LLVM: llvm::orc::shared::SerializationTraits< ChannelT, std::vector< T > > Class Template Reference
llvm::orc::shared::SerializationTraits< ChannelT, std::vector< T > > Class Template Reference
SerializationTraits default specialization for std::vector.
#include "llvm/ExecutionEngine/Orc/Shared/Serialization.h"
Static Public Member Functions
static Error serialize (ChannelT &C, const std::vector< T > &V)
Serialize a std::vector<T> from std::vector<T>.
static Error deserialize (ChannelT &C, std::vector< T > &V)
Deserialize a std::vector<T> to a std::vector<T>.
Detailed Description
template<typename ChannelT, typename T>
class llvm::orc::shared::SerializationTraits< ChannelT, std::vector< T > >
SerializationTraits default specialization for std::vector.
Definition at line 582 of file Serialization.h.
Member Function Documentation
deserialize()
template<typename ChannelT , typename T > static Error llvm::orc::shared::SerializationTraits< ChannelT, std::vector< T > >::deserialize (ChannelT & C, std::vector< T > & V) inline static
Deserialize a std::vector<T> to a std::vector<T>.
Definition at line 597 of file Serialization.h.
References assert(), C, llvm::orc::shared::deserializeSeq(), E, and llvm::Error::success().
serialize()
template<typename ChannelT , typename T > static Error llvm::orc::shared::SerializationTraits< ChannelT, std::vector< T > >::serialize (ChannelT & C, const std::vector< T > & V) inline static
Serialize a std::vector<T> from std::vector<T>.
Definition at line 585 of file Serialization.h.
References C, E, llvm::orc::shared::serializeSeq(), and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/Serialization.h