LLVM: llvm::SparcTargetLowering Class Reference
llvm::SparcTargetLowering Class Reference
#include "Target/Sparc/SparcISelLowering.h"
Public Member Functions
SparcTargetLowering (const TargetMachine &TM, const SparcSubtarget &STI)
SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const override
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
bool useSoftFloat () const override
void computeKnownBitsForTargetNode (const SDValue Op, KnownBits &Known, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth=0) const override
computeKnownBitsForTargetNode - Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr &MI, MachineBasicBlock *MBB) const override
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
const char * getTargetNodeName (unsigned Opcode) const override
This method returns the name of a target specific DAG node.
ConstraintType getConstraintType (StringRef Constraint) const override
getConstraintType - Given a constraint letter, return the type of constraint it is for this target.
ConstraintWeight getSingleConstraintMatchWeight (AsmOperandInfo &info, const char *constraint) const override
Examine constraint string and operand type and determine a weight value.
void LowerAsmOperandForConstraint (SDValue Op, std::string &Constraint, std::vector< SDValue > &Ops, SelectionDAG &DAG) const override
LowerAsmOperandForConstraint - Lower the specified operand into the Ops vector.
std::pair< unsigned, const TargetRegisterClass * > getRegForInlineAsmConstraint (const TargetRegisterInfo *TRI, StringRef Constraint, MVT VT) const override
Given a physical register constraint (e.g.
bool isOffsetFoldingLegal (const GlobalAddressSDNode *GA) const override
Return true if folding a constant offset with the given GlobalAddress is legal.
MVT getScalarShiftAmountTy (const DataLayout &, EVT) const override
EVT is not used in-tree, but is used by out-of-tree target.
Register getRegisterByName (const char *RegName, LLT VT, const MachineFunction &MF) const override
Return the register ID of the name passed in.
Register getExceptionPointerRegister (const Constant *PersonalityFn) const override
If a physical register, this returns the register that receives the exception address on entry to an EH pad.
Register getExceptionSelectorRegister (const Constant *PersonalityFn) const override
If a physical register, this returns the register that receives the exception typeid on entry to a landing pad.
bool useLoadStackGuardNode () const override
Override to support customized stack guard loading.
void insertSSPDeclarations (Module &M) const override
Inserts necessary declarations for SSP (stack protection) purpose.
EVT getSetCCResultType (const DataLayout &DL, LLVMContext &Context, EVT VT) const override
getSetCCResultType - Return the ISD::SETCC ValueType
SDValue LowerFormalArguments (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > &Ins, const SDLoc &dl, SelectionDAG &DAG, SmallVectorImpl< SDValue > &InVals) const override
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
SDValue LowerFormalArguments_32 (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > &Ins, const SDLoc &dl, SelectionDAG &DAG, SmallVectorImpl< SDValue > &InVals) const
LowerFormalArguments32 - V8 uses a very simple ABI, where all values are passed in either one or two GPRs, including FP values.
SDValue LowerFormalArguments_64 (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > &Ins, const SDLoc &dl, SelectionDAG &DAG, SmallVectorImpl< SDValue > &InVals) const
SDValue LowerCall (TargetLowering::CallLoweringInfo &CLI, SmallVectorImpl< SDValue > &InVals) const override
This hook must be implemented to lower calls into the specified DAG.
SDValue LowerCall_32 (TargetLowering::CallLoweringInfo &CLI, SmallVectorImpl< SDValue > &InVals) const
SDValue LowerCall_64 (TargetLowering::CallLoweringInfo &CLI, SmallVectorImpl< SDValue > &InVals) const
SDValue LowerReturn (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::OutputArg > &Outs, const SmallVectorImpl< SDValue > &OutVals, const SDLoc &dl, SelectionDAG &DAG) const override
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG.
SDValue LowerReturn_32 (SDValue Chain, CallingConv::ID CallConv, bool IsVarArg, const SmallVectorImpl< ISD::OutputArg > &Outs, const SmallVectorImpl< SDValue > &OutVals, const SDLoc &DL, SelectionDAG &DAG) const
SDValue LowerReturn_64 (SDValue Chain, CallingConv::ID CallConv, bool IsVarArg, const SmallVectorImpl< ISD::OutputArg > &Outs, const SmallVectorImpl< SDValue > &OutVals, const SDLoc &DL, SelectionDAG &DAG) const
SDValue LowerGlobalAddress (SDValue Op, SelectionDAG &DAG) const
SDValue LowerGlobalTLSAddress (SDValue Op, SelectionDAG &DAG) const
SDValue LowerConstantPool (SDValue Op, SelectionDAG &DAG) const
SDValue LowerBlockAddress (SDValue Op, SelectionDAG &DAG) const
SDValue withTargetFlags (SDValue Op, unsigned TF, SelectionDAG &DAG) const
SDValue makeHiLoPair (SDValue Op, unsigned HiTF, unsigned LoTF, SelectionDAG &DAG) const
SDValue makeAddress (SDValue Op, SelectionDAG &DAG) const
SDValue LowerF128_LibCallArg (SDValue Chain, ArgListTy &Args, SDValue Arg, const SDLoc &DL, SelectionDAG &DAG) const
SDValue LowerF128Op (SDValue Op, SelectionDAG &DAG, const char *LibFuncName, unsigned numArgs) const
SDValue LowerF128Compare (SDValue LHS, SDValue RHS, unsigned &SPCC, const SDLoc &DL, SelectionDAG &DAG) const
SDValue LowerINTRINSIC_WO_CHAIN (SDValue Op, SelectionDAG &DAG) const
SDValue PerformBITCASTCombine (SDNode *N, DAGCombinerInfo &DCI) const
SDValue bitcastConstantFPToInt (ConstantFPSDNode *C, const SDLoc &DL, SelectionDAG &DAG) const
SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const override
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
bool ShouldShrinkFPConstant (EVT VT) const override
If true, then instruction selection should seek to shrink the FP constant of the specified type to a smaller type in order to save space and / or reduce runtime.
bool shouldInsertFencesForAtomic (const Instruction *I) const override
Whether AtomicExpandPass should automatically insert fences and reduce ordering for this atomic.
AtomicExpansionKind shouldExpandAtomicRMWInIR (AtomicRMWInst *AI) const override
Returns how the IR-level AtomicExpand pass should expand the given AtomicRMW, if at all.
void ReplaceNodeResults (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const override
This callback is invoked when a node result type is illegal for the target, and the operation was registered to use 'custom' lowering for that result type.
MachineBasicBlock * expandSelectCC (MachineInstr &MI, MachineBasicBlock *BB, unsigned BROpcode) const
Public Member Functions inherited from llvm::TargetLowering
TargetLowering (const TargetLowering &)=delete
TargetLowering & operator= (const TargetLowering &)=delete
TargetLowering (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
bool isPositionIndependent () const
virtual bool isSDNodeSourceOfDivergence (const SDNode *N, FunctionLoweringInfo *FLI, LegacyDivergenceAnalysis *DA) const
virtual bool isSDNodeAlwaysUniform (const SDNode *N) const
virtual bool getPreIndexedAddressParts (SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
Returns true by value, base pointer and offset pointer and addressing mode by reference if the node's address can be legally represented as pre-indexed load / store address.
virtual bool getPostIndexedAddressParts (SDNode *, SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
Returns true by value, base pointer and offset pointer and addressing mode by reference if this node can be combined with a load / store to form a post-indexed load / store.
virtual bool isIndexingLegal (MachineInstr &MI, Register Base, Register Offset, bool IsPre, MachineRegisterInfo &MRI) const
Returns true if the specified base+offset is a legal indexed addressing mode for this target.
virtual unsigned getJumpTableEncoding () const
Return the entry encoding for a jump table in the current function.
virtual const MCExpr * LowerCustomJumpTableEntry (const MachineJumpTableInfo *, const MachineBasicBlock *, unsigned, MCContext &) const
virtual SDValue getPICJumpTableRelocBase (SDValue Table, SelectionDAG &DAG) const
Returns relocation base for the given PIC jumptable.
virtual const MCExpr * getPICJumpTableRelocBaseExpr (const MachineFunction *MF, unsigned JTI, MCContext &Ctx) const
This returns the relocation base for the given PIC jumptable, the same as getPICJumpTableRelocBase, but as an MCExpr.
bool isInTailCallPosition (SelectionDAG &DAG, SDNode *Node, SDValue &Chain) const
Check whether a given call node is in tail position within its function.
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, const SDLoc &DL, const SDValue OldLHS, const SDValue OldRHS) const
Soften the operands of a comparison.
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, const SDLoc &DL, const SDValue OldLHS, const SDValue OldRHS, SDValue &Chain, bool IsSignaling=false) const
std::pair< SDValue, SDValue > makeLibCall (SelectionDAG &DAG, RTLIB::Libcall LC, EVT RetVT, ArrayRef< SDValue > Ops, MakeLibCallOptions CallOptions, const SDLoc &dl, SDValue Chain=SDValue()) const
Returns a pair of (return value, chain).
bool parametersInCSRMatch (const MachineRegisterInfo &MRI, const uint32_t *CallerPreservedMask, const SmallVectorImpl< CCValAssign > &ArgLocs, const SmallVectorImpl< SDValue > &OutVals) const
Check whether parameters to a call that are passed in callee saved registers are the same as from the calling function.
bool findOptimalMemOpLowering (std::vector< EVT > &MemOps, unsigned Limit, const MemOp &Op, unsigned DstAS, unsigned SrcAS, const AttributeList &FuncAttributes) const
Determines the optimal series of memory ops to replace the memset / memcpy.
bool ShrinkDemandedConstant (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, TargetLoweringOpt &TLO) const
Check to see if the specified operand of the specified instruction is a constant integer.
bool ShrinkDemandedConstant (SDValue Op, const APInt &DemandedBits, TargetLoweringOpt &TLO) const
Helper wrapper around ShrinkDemandedConstant, demanding all elements.
virtual bool targetShrinkDemandedConstant (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, TargetLoweringOpt &TLO) const
bool ShrinkDemandedOp (SDValue Op, unsigned BitWidth, const APInt &Demanded, TargetLoweringOpt &TLO) const
Convert x+y to (VT)((SmallVT)x+(SmallVT)y) if the casts are free.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Look at Op.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Helper wrapper around SimplifyDemandedBits, demanding all elements.
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedBits, DAGCombinerInfo &DCI) const
Helper wrapper around SimplifyDemandedBits.
SDValue SimplifyMultipleUseDemandedBits (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, SelectionDAG &DAG, unsigned Depth) const
More limited version of SimplifyDemandedBits that can be used to "look through" ops that don't contribute to the DemandedBits/DemandedElts - bitwise ops etc.
SDValue SimplifyMultipleUseDemandedBits (SDValue Op, const APInt &DemandedBits, SelectionDAG &DAG, unsigned Depth=0) const
Helper wrapper around SimplifyMultipleUseDemandedBits, demanding all elements.
SDValue SimplifyMultipleUseDemandedVectorElts (SDValue Op, const APInt &DemandedElts, SelectionDAG &DAG, unsigned Depth=0) const
Helper wrapper around SimplifyMultipleUseDemandedBits, demanding all bits from only some vector elements.
bool SimplifyDemandedVectorElts (SDValue Op, const APInt &DemandedEltMask, APInt &KnownUndef, APInt &KnownZero, TargetLoweringOpt &TLO, unsigned Depth=0, bool AssumeSingleUse=false) const
Look at Vector Op.
bool SimplifyDemandedVectorElts (SDValue Op, const APInt &DemandedElts, APInt &KnownUndef, APInt &KnownZero, DAGCombinerInfo &DCI) const
Helper wrapper around SimplifyDemandedVectorElts.
virtual void computeKnownBitsForTargetInstr (GISelKnownBits &Analysis, Register R, KnownBits &Known, const APInt &DemandedElts, const MachineRegisterInfo &MRI, unsigned Depth=0) const
Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
virtual Align computeKnownAlignForTargetInstr (GISelKnownBits &Analysis, Register R, const MachineRegisterInfo &MRI, unsigned Depth=0) const
Determine the known alignment for the pointer value R.
virtual void computeKnownBitsForFrameIndex (int FIOp, KnownBits &Known, const MachineFunction &MF) const
Determine which of the bits of FrameIndex FIOp are known to be 0.
virtual unsigned ComputeNumSignBitsForTargetNode (SDValue Op, const APInt &DemandedElts, const SelectionDAG &DAG, unsigned Depth=0) const
This method can be implemented by targets that want to expose additional information about sign bits to the DAG Combiner.
virtual unsigned computeNumSignBitsForTargetInstr (GISelKnownBits &Analysis, Register R, const APInt &DemandedElts, const MachineRegisterInfo &MRI, unsigned Depth=0) const
This method can be implemented by targets that want to expose additional information about sign bits to GlobalISel combiners.
virtual bool SimplifyDemandedVectorEltsForTargetNode (SDValue Op, const APInt &DemandedElts, APInt &KnownUndef, APInt &KnownZero, TargetLoweringOpt &TLO, unsigned Depth=0) const
Attempt to simplify any target nodes based on the demanded vector elements, returning true on success.
virtual bool SimplifyDemandedBitsForTargetNode (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, KnownBits &Known, TargetLoweringOpt &TLO, unsigned Depth=0) const
Attempt to simplify any target nodes based on the demanded bits/elts, returning true on success.
virtual SDValue SimplifyMultipleUseDemandedBitsForTargetNode (SDValue Op, const APInt &DemandedBits, const APInt &DemandedElts, SelectionDAG &DAG, unsigned Depth) const
More limited version of SimplifyDemandedBits that can be used to "look through" ops that don't contribute to the DemandedBits/DemandedElts - bitwise ops etc.
virtual bool isGuaranteedNotToBeUndefOrPoisonForTargetNode (SDValue Op, const APInt &DemandedElts, const SelectionDAG &DAG, bool PoisonOnly, unsigned Depth) const
Return true if this function can prove that Op is never poison and, if PoisonOnly is false, does not have undef bits.
SDValue buildLegalVectorShuffle (EVT VT, const SDLoc &DL, SDValue N0, SDValue N1, MutableArrayRef< int > Mask, SelectionDAG &DAG) const
Tries to build a legal vector shuffle using the provided parameters or equivalent variations.
virtual const Constant * getTargetConstantFromLoad (LoadSDNode *LD) const
This method returns the constant pool value that will be loaded by LD.
virtual bool isKnownNeverNaNForTargetNode (SDValue Op, const SelectionDAG &DAG, bool SNaN=false, unsigned Depth=0) const
If SNaN is false,.
bool isConstTrueVal (const SDNode *N) const
Return if the N is a constant or constant vector equal to the true value from getBooleanContents().
bool isConstFalseVal (const SDNode *N) const
Return if the N is a constant or constant vector equal to the false value from getBooleanContents().
bool isExtendedTrueVal (const ConstantSDNode *N, EVT VT, bool SExt) const
Return if N is a True value when extended to VT.
SDValue SimplifySetCC (EVT VT, SDValue N0, SDValue N1, ISD::CondCode Cond, bool foldBooleans, DAGCombinerInfo &DCI, const SDLoc &dl) const
Try to simplify a setcc built with the specified operands and cc.
virtual SDValue unwrapAddress (SDValue N) const
virtual bool isGAPlusOffset (SDNode *N, const GlobalValue *&GA, int64_t &Offset) const
Returns true (and the GlobalValue and the offset) if the node is a GlobalAddress + offset.
virtual bool isDesirableToCommuteWithShift (const SDNode *N, CombineLevel Level) const
Return true if it is profitable to move this shift by a constant amount though its operand, adjusting any immediate operands as necessary to preserve semantics.
virtual bool isTypeDesirableForOp (unsigned, EVT VT) const
Return true if the target has native support for the specified value type and it is 'desirable' to use the type for the given node type.
virtual bool isDesirableToTransformToIntegerOp (unsigned, EVT) const
Return true if it is profitable for dag combiner to transform a floating point op of specified opcode to a equivalent op of an integer type.
virtual bool IsDesirableToPromoteOp (SDValue, EVT &) const
This method query the target whether it is beneficial for dag combiner to promote the specified node.
virtual bool supportSwiftError () const
Return true if the target supports swifterror attribute.
virtual bool supportSplitCSR (MachineFunction *MF) const
Return true if the target supports that a subset of CSRs for the given machine function is handled explicitly via copies.
virtual void initializeSplitCSR (MachineBasicBlock *Entry) const
Perform necessary initialization to handle a subset of CSRs explicitly via copies.
virtual void insertCopiesSplitCSR (MachineBasicBlock *Entry, const SmallVectorImpl< MachineBasicBlock * > &Exits) const
Insert explicit copies in entry and exit blocks.
virtual SDValue getNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOps, bool OptForSize, NegatibleCost &Cost, unsigned Depth=0) const
Return the newly negated expression if the cost is not expensive and set the cost in Cost to indicate that if it is cheaper or neutral to do the negation.
SDValue getCheaperNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOps, bool OptForSize, unsigned Depth=0) const
This is the helper function to return the newly negated expression only when the cost is cheaper.
SDValue getNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOps, bool OptForSize, unsigned Depth=0) const
This is the helper function to return the newly negated expression if the cost is not expensive.
virtual bool splitValueIntoRegisterParts (SelectionDAG &DAG, const SDLoc &DL, SDValue Val, SDValue *Parts, unsigned NumParts, MVT PartVT, Optional< CallingConv::ID > CC) const
Target-specific splitting of values into parts that fit a register storing a legal type.
virtual SDValue joinRegisterPartsIntoValue (SelectionDAG &DAG, const SDLoc &DL, const SDValue *Parts, unsigned NumParts, MVT PartVT, EVT ValueVT, Optional< CallingConv::ID > CC) const
Target-specific combining of register parts into its original value.
std::pair< SDValue, SDValue > LowerCallTo (CallLoweringInfo &CLI) const
This function lowers an abstract call to a function into an actual call.
virtual void HandleByVal (CCState *, unsigned &, Align) const
Target-specific cleanup for formal ByVal parameters.
virtual bool CanLowerReturn (CallingConv::ID, MachineFunction &, bool, const SmallVectorImpl< ISD::OutputArg > &, LLVMContext &) const
This hook should be implemented to check whether the return values described by the Outs array can fit into the return registers.
virtual bool isUsedByReturnOnly (SDNode *, SDValue &) const
Return true if result of the specified node is used by a return node only.
virtual bool mayBeEmittedAsTailCall (const CallInst *) const
Return true if the target may be able emit the call instruction as a tail call.
virtual const char * getClearCacheBuiltinName () const
Return the builtin name for the __builtin___clear_cache intrinsic Default is to invoke the clear cache library call.
virtual EVT getTypeForExtReturn (LLVMContext &Context, EVT VT, ISD::NodeType) const
Return the type that should be used to zero or sign extend a zeroext/signext integer return value.
virtual bool functionArgumentNeedsConsecutiveRegisters (Type *Ty, CallingConv::ID CallConv, bool isVarArg, const DataLayout &DL) const
For some targets, an LLVM struct type must be broken down into multiple simple types, but the calling convention specifies that the entire struct must be passed in a block of consecutive registers.
virtual bool shouldSplitFunctionArgumentsAsLittleEndian (const DataLayout &DL) const
For most targets, an LLVM type must be broken down into multiple smaller types.
virtual const MCPhysReg * getScratchRegisters (CallingConv::ID CC) const
Returns a 0 terminated array of registers that can be safely used as scratch registers.
virtual SDValue prepareVolatileOrAtomicLoad (SDValue Chain, const SDLoc &DL, SelectionDAG &DAG) const
This callback is used to prepare for a volatile or atomic load.
virtual bool lowerAtomicStoreAsStoreSDNode (const StoreInst &SI) const
Should SelectionDAG lower an atomic store of the given kind as a normal StoreSDNode (as opposed to an AtomicSDNode)? NOTE: The intention is to eventually migrate all targets to the using StoreSDNodes, but porting is being done target at a time.
virtual bool lowerAtomicLoadAsLoadSDNode (const LoadInst &LI) const
Should SelectionDAG lower an atomic load of the given kind as a normal LoadSDNode (as opposed to an AtomicSDNode)? NOTE: The intention is to eventually migrate all targets to the using LoadSDNodes, but porting is being done target at a time.
virtual void LowerOperationWrapper (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const
This callback is invoked by the type legalizer to legalize nodes with an illegal operand type but legal result types.
virtual FastISel * createFastISel (FunctionLoweringInfo &, const TargetLibraryInfo *) const
This method returns a target specific FastISel object, or null if the target does not support "fast" ISel.
bool verifyReturnAddressArgumentIsConstant (SDValue Op, SelectionDAG &DAG) const
virtual bool ExpandInlineAsm (CallInst *) const
This hook allows the target to expand an inline asm call to be explicit llvm code if it wants to.
virtual AsmOperandInfoVector ParseConstraints (const DataLayout &DL, const TargetRegisterInfo *TRI, const CallBase &Call) const
Split up the constraint string from the inline assembly value into the specific constraints and their prefixes, and also tie in the associated operand values.
virtual ConstraintWeight getMultipleConstraintMatchWeight (AsmOperandInfo &info, int maIndex) const
Examine constraint type and operand type and determine a weight value.
virtual void ComputeConstraintToUse (AsmOperandInfo &OpInfo, SDValue Op, SelectionDAG *DAG=nullptr) const
Determines the constraint code and constraint type to use for the specific AsmOperandInfo, setting OpInfo.ConstraintCode and OpInfo.ConstraintType.
virtual unsigned getInlineAsmMemConstraint (StringRef ConstraintCode) const
virtual const char * LowerXConstraint (EVT ConstraintVT) const
Try to replace an X constraint, which matches anything, with another that has more specific requirements based on the type of the corresponding operand.
virtual SDValue LowerAsmOutputForConstraint (SDValue &Chain, SDValue &Flag, const SDLoc &DL, const AsmOperandInfo &OpInfo, SelectionDAG &DAG) const
SDValue BuildSDIV (SDNode *N, SelectionDAG &DAG, bool IsAfterLegalization, SmallVectorImpl< SDNode * > &Created) const
Given an ISD::SDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number.
SDValue BuildUDIV (SDNode *N, SelectionDAG &DAG, bool IsAfterLegalization, SmallVectorImpl< SDNode * > &Created) const
Given an ISD::UDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number.
virtual SDValue BuildSDIVPow2 (SDNode *N, const APInt &Divisor, SelectionDAG &DAG, SmallVectorImpl< SDNode * > &Created) const
Targets may override this function to provide custom SDIV lowering for power-of-2 denominators.
virtual unsigned combineRepeatedFPDivisors () const
Indicate whether this target prefers to combine FDIVs with the same divisor.
virtual SDValue getSqrtEstimate (SDValue Operand, SelectionDAG &DAG, int Enabled, int &RefinementSteps, bool &UseOneConstNR, bool Reciprocal) const
Hooks for building estimates in place of slower divisions and square roots.
virtual SDValue getRecipEstimate (SDValue Operand, SelectionDAG &DAG, int Enabled, int &RefinementSteps) const
Return a reciprocal estimate value for the input operand.
virtual SDValue getSqrtInputTest (SDValue Operand, SelectionDAG &DAG, const DenormalMode &Mode) const
Return a target-dependent comparison result if the input operand is suitable for use with a square root estimate calculation.
virtual SDValue getSqrtResultForDenormInput (SDValue Operand, SelectionDAG &DAG) const
Return a target-dependent result if the input operand is not suitable for use with a square root estimate calculation.
bool expandMUL_LOHI (unsigned Opcode, EVT VT, const SDLoc &dl, SDValue LHS, SDValue RHS, SmallVectorImpl< SDValue > &Result, EVT HiLoVT, SelectionDAG &DAG, MulExpansionKind Kind, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
Expand a MUL or [US]MUL_LOHI of n-bit values into two or four nodes, respectively, each computing an n/2-bit part of the result.
bool expandMUL (SDNode *N, SDValue &Lo, SDValue &Hi, EVT HiLoVT, SelectionDAG &DAG, MulExpansionKind Kind, SDValue LL=SDValue(), SDValue LH=SDValue(), SDValue RL=SDValue(), SDValue RH=SDValue()) const
Expand a MUL into two nodes.
bool expandFunnelShift (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand funnel shift.
bool expandROT (SDNode *N, bool AllowVectorOps, SDValue &Result, SelectionDAG &DAG) const
Expand rotations.
void expandShiftParts (SDNode *N, SDValue &Lo, SDValue &Hi, SelectionDAG &DAG) const
Expand shift-by-parts.
bool expandFP_TO_SINT (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand float(f32) to SINT(i64) conversion.
bool expandFP_TO_UINT (SDNode *N, SDValue &Result, SDValue &Chain, SelectionDAG &DAG) const
Expand float to UINT conversion.
bool expandUINT_TO_FP (SDNode *N, SDValue &Result, SDValue &Chain, SelectionDAG &DAG) const
Expand UINT(i64) to double(f64) conversion.
SDValue expandFMINNUM_FMAXNUM (SDNode *N, SelectionDAG &DAG) const
Expand fminnum/fmaxnum into fminnum_ieee/fmaxnum_ieee with quieted inputs.
SDValue expandFP_TO_INT_SAT (SDNode *N, SelectionDAG &DAG) const
Expand FP_TO_[US]INT_SAT into FP_TO_[US]INT and selects or min/max.
bool expandCTPOP (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand CTPOP nodes.
bool expandCTLZ (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand CTLZ/CTLZ_ZERO_UNDEF nodes.
bool expandCTTZ (SDNode *N, SDValue &Result, SelectionDAG &DAG) const
Expand CTTZ/CTTZ_ZERO_UNDEF nodes.
bool expandABS (SDNode *N, SDValue &Result, SelectionDAG &DAG, bool IsNegative=false) const
Expand ABS nodes.
SDValue expandBSWAP (SDNode *N, SelectionDAG &DAG) const
Expand BSWAP nodes.
SDValue expandBITREVERSE (SDNode *N, SelectionDAG &DAG) const
Expand BITREVERSE nodes.
std::pair< SDValue, SDValue > scalarizeVectorLoad (LoadSDNode *LD, SelectionDAG &DAG) const
Turn load of vector type into a load of the individual elements.
SDValue scalarizeVectorStore (StoreSDNode *ST, SelectionDAG &DAG) const
std::pair< SDValue, SDValue > expandUnalignedLoad (LoadSDNode *LD, SelectionDAG &DAG) const
Expands an unaligned load to 2 half-size loads for an integer, and possibly more for vectors.
SDValue expandUnalignedStore (StoreSDNode *ST, SelectionDAG &DAG) const
Expands an unaligned store to 2 half-size stores for integer values, and possibly more for vectors.
SDValue IncrementMemoryAddress (SDValue Addr, SDValue Mask, const SDLoc &DL, EVT DataVT, SelectionDAG &DAG, bool IsCompressedMemory) const
Increments memory address Addr according to the type of the value DataVT that should be stored.
SDValue getVectorElementPointer (SelectionDAG &DAG, SDValue VecPtr, EVT VecVT, SDValue Index) const
Get a pointer to vector element Idx located in memory for a vector of type VecVT starting at a base address of VecPtr.
SDValue getVectorSubVecPointer (SelectionDAG &DAG, SDValue VecPtr, EVT VecVT, EVT SubVecVT, SDValue Index) const
Get a pointer to a sub-vector of type SubVecVT at index Idx located in memory for a vector of type VecVT starting at a base address of VecPtr.
SDValue expandIntMINMAX (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US][MIN|MAX].
SDValue expandAddSubSat (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US][ADD|SUB]SAT.
SDValue expandShlSat (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]SHLSAT.
SDValue expandFixedPointMul (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[U|S]MULFIX[SAT].
SDValue expandFixedPointDiv (unsigned Opcode, const SDLoc &dl, SDValue LHS, SDValue RHS, unsigned Scale, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]DIVFIX[SAT].
void expandUADDSUBO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::U(ADD|SUB)O.
void expandSADDSUBO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::S(ADD|SUB)O.
bool expandMULO (SDNode *Node, SDValue &Result, SDValue &Overflow, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::[US]MULO.
SDValue expandVecReduce (SDNode *Node, SelectionDAG &DAG) const
Expand a VECREDUCE_* into an explicit calculation.
SDValue expandVecReduceSeq (SDNode *Node, SelectionDAG &DAG) const
Expand a VECREDUCE_SEQ_* into an explicit ordered calculation.
bool expandREM (SDNode *Node, SDValue &Result, SelectionDAG &DAG) const
Expand an SREM or UREM using SDIV/UDIV or SDIVREM/UDIVREM, if legal.
SDValue expandVectorSplice (SDNode *Node, SelectionDAG &DAG) const
Method for building the DAG expansion of ISD::VECTOR_SPLICE.
bool LegalizeSetCCCondCode (SelectionDAG &DAG, EVT VT, SDValue &LHS, SDValue &RHS, SDValue &CC, bool &NeedInvert, const SDLoc &dl, SDValue &Chain, bool IsSignaling=false) const
Legalize a SETCC with given LHS and RHS and condition code CC on the current target.
virtual void AdjustInstrPostInstrSelection (MachineInstr &MI, SDNode *Node) const
This method should be implemented by targets that mark instructions with the 'hasPostISelHook' flag.
virtual SDValue emitStackGuardXorFP (SelectionDAG &DAG, SDValue Val, const SDLoc &DL) const
virtual SDValue LowerToTLSEmulatedModel (const GlobalAddressSDNode *GA, SelectionDAG &DAG) const
Lower TLS global address SDNode for target independent emulated TLS model.
virtual SDValue expandIndirectJTBranch (const SDLoc &dl, SDValue Value, SDValue Addr, SelectionDAG &DAG) const
Expands target specific indirect branch for the case of JumpTable expanasion.
SDValue lowerCmpEqZeroToCtlzSrl (SDValue Op, SelectionDAG &DAG) const
ISD::MemIndexType getCanonicalIndexType (ISD::MemIndexType IndexType, EVT MemVT, SDValue Offsets) const
Give targets the chance to reduce the number of distinct addresing modes.
Public Member Functions inherited from llvm::TargetLoweringBase
virtual void markLibCallAttributes (MachineFunction *MF, unsigned CC, ArgListTy &Args) const
TargetLoweringBase (const TargetMachine &TM)
NOTE: The TargetMachine owns TLOF.
TargetLoweringBase (const TargetLoweringBase &)=delete
TargetLoweringBase & operator= (const TargetLoweringBase &)=delete
virtual ~TargetLoweringBase ()=default
bool isStrictFPEnabled () const
Return true if the target support strict float operation.
const TargetMachine & getTargetMachine () const
virtual MVT getPointerTy (const DataLayout &DL, uint32_t AS=0) const
Return the pointer type for the given address space, defaults to the pointer type from the data layout.
virtual MVT getPointerMemTy (const DataLayout &DL, uint32_t AS=0) const
Return the in-memory pointer type for the given address space, defaults to the pointer type from the data layout.
MVT getFrameIndexTy (const DataLayout &DL) const
Return the type for frame index, which is determined by the alloca address space specified through the data layout.
MVT getProgramPointerTy (const DataLayout &DL) const
Return the type for code pointers, which is determined by the program address space specified through the data layout.
virtual MVT getFenceOperandTy (const DataLayout &DL) const
Return the type for operands of fence.
EVT getShiftAmountTy (EVT LHSTy, const DataLayout &DL, bool LegalTypes=true) const
virtual LLVM_READONLY LLT getPreferredShiftAmountTy (LLT ShiftValueTy) const
Return the preferred type to use for a shift opcode, given the shifted amount type is ShiftValueTy.
virtual MVT getVectorIdxTy (const DataLayout &DL) const
Returns the type to be used for the index operand of: ISD::INSERT_VECTOR_ELT, ISD::EXTRACT_VECTOR_ELT, ISD::INSERT_SUBVECTOR, and ISD::EXTRACT_SUBVECTOR.
virtual MVT getVPExplicitVectorLengthTy () const
Returns the type to be used for the EVL/AVL operand of VP nodes: ISD::VP_ADD, ISD::VP_SUB, etc.
virtual MachineMemOperand::Flags getTargetMMOFlags (const Instruction &I) const
This callback is used to inspect load/store instructions and add target-specific MachineMemOperand flags to them.
MachineMemOperand::Flags getLoadMemOperandFlags (const LoadInst &LI, const DataLayout &DL) const
MachineMemOperand::Flags getStoreMemOperandFlags (const StoreInst &SI, const DataLayout &DL) const
MachineMemOperand::Flags getAtomicMemOperandFlags (const Instruction &AI, const DataLayout &DL) const
virtual bool isSelectSupported (SelectSupportKind) const
virtual bool reduceSelectOfFPConstantLoads (EVT CmpOpVT) const
Return true if it is profitable to convert a select of FP constants into a constant pool load whose address depends on the select condition.
bool hasMultipleConditionRegisters () const
Return true if multiple condition registers are available.
bool hasExtractBitsInsn () const
Return true if the target has BitExtract instructions.
virtual TargetLoweringBase::LegalizeTypeAction getPreferredVectorAction (MVT VT) const
Return the preferred vector type legalization action.
virtual bool softPromoteHalfType () const
virtual bool shouldExpandBuildVectorWithShuffles (EVT, unsigned DefinedValues) const
virtual bool isIntDivCheap (EVT VT, AttributeList Attr) const
Return true if integer divide is usually cheaper than a sequence of several shifts, adds, and multiplies for this target.
virtual bool hasStandaloneRem (EVT VT) const
Return true if the target can handle a standalone remainder operation.
virtual bool isFsqrtCheap (SDValue X, SelectionDAG &DAG) const
Return true if SQRT(X) shouldn't be replaced with X*RSQRT(X).
int getRecipEstimateSqrtEnabled (EVT VT, MachineFunction &MF) const
Return a ReciprocalEstimate enum value for a square root of the given type based on the function's attributes.
int getRecipEstimateDivEnabled (EVT VT, MachineFunction &MF) const
Return a ReciprocalEstimate enum value for a division of the given type based on the function's attributes.
int getSqrtRefinementSteps (EVT VT, MachineFunction &MF) const
Return the refinement step count for a square root of the given type based on the function's attributes.
int getDivRefinementSteps (EVT VT, MachineFunction &MF) const
Return the refinement step count for a division of the given type based on the function's attributes.
bool isSlowDivBypassed () const
Returns true if target has indicated at least one type should be bypassed.
const DenseMap< unsigned int, unsigned int > & getBypassSlowDivWidths () const
Returns map of slow types for division or remainder with corresponding fast types.
bool isJumpExpensive () const
Return true if Flow Control is an expensive operation that should be avoided.
bool isPredictableSelectExpensive () const
Return true if selects are only cheaper than branches if the branch is unlikely to be predicted right.
virtual bool fallBackToDAGISel (const Instruction &Inst) const
virtual bool isLoadBitCastBeneficial (EVT LoadVT, EVT BitcastVT, const SelectionDAG &DAG, const MachineMemOperand &MMO) const
Return true if the following transform is beneficial: fold (conv (load x)) -> (load (conv*)x) On architectures that don't natively support some vector loads efficiently, casting the load to a smaller vector of larger types and loading is more efficient, however, this can be undone by optimizations in dag combiner.
virtual bool isStoreBitCastBeneficial (EVT StoreVT, EVT BitcastVT, const SelectionDAG &DAG, const MachineMemOperand &MMO) const
Return true if the following transform is beneficial: (store (y (conv x)), y*)) -> (store x, (x*))
virtual bool storeOfVectorConstantIsCheap (EVT MemVT, unsigned NumElem, unsigned AddrSpace) const
Return true if it is expected to be cheaper to do a store of a non-zero vector constant with the given size and type for the address space than to store the individual scalar element constants.
virtual bool mergeStoresAfterLegalization (EVT MemVT) const
Allow store merging for the specified type after legalization in addition to before legalization.
virtual bool canMergeStoresTo (unsigned AS, EVT MemVT, const SelectionDAG &DAG) const
Returns if it's reasonable to merge stores to MemVT size.
virtual bool isCheapToSpeculateCttz () const
Return true if it is cheap to speculate a call to intrinsic cttz.
virtual bool isCheapToSpeculateCtlz () const
Return true if it is cheap to speculate a call to intrinsic ctlz.
virtual bool isCtlzFast () const
Return true if ctlz instruction is fast.
virtual unsigned getCustomCtpopCost (EVT VT, ISD::CondCode Cond) const
Return the maximum number of "x & (x - 1)" operations that can be done instead of deferring to a custom CTPOP.
virtual bool isEqualityCmpFoldedWithSignedCmp () const
Return true if instruction generated for equality comparison is folded with instruction generated for signed comparison.
virtual bool preferZeroCompareBranch () const
Return true if the heuristic to prefer icmp eq zero should be used in code gen prepare.
virtual bool hasBitPreservingFPLogic (EVT VT) const
Return true if it is safe to transform an integer-domain bitwise operation into the equivalent floating-point operation.
virtual bool isMultiStoresCheaperThanBitsMerge (EVT LTy, EVT HTy) const
Return true if it is cheaper to split the store of a merged int val from a pair of smaller values into multiple stores.
virtual bool isMaskAndCmp0FoldingBeneficial (const Instruction &AndI) const
Return if the target supports combining a chain like:
virtual bool convertSetCCLogicToBitwiseLogic (EVT VT) const
Use bitwise logic to make pairs of compares more efficient.
virtual MVT hasFastEqualityCompare (unsigned NumBits) const
Return the preferred operand type if the target has a quick way to compare integer values of the given size.
virtual bool hasAndNotCompare (SDValue Y) const
Return true if the target should transform: (X & Y) == Y ---> (~X & Y) == 0 (X & Y) != Y ---> (~X & Y) != 0.
virtual bool hasAndNot (SDValue X) const
Return true if the target has a bitwise and-not operation: X = ~A & B This can be used to simplify select or other instructions.
virtual bool hasBitTest (SDValue X, SDValue Y) const
Return true if the target has a bit-test instruction: (X & (1 << Y)) ==/!= 0 This knowledge can be used to prevent breaking the pattern, or creating it if it could be recognized.
virtual bool shouldFoldMaskToVariableShiftPair (SDValue X) const
There are two ways to clear extreme bits (either low or high): Mask: x & (-1 << y) (the instcombine canonical form) Shifts: x >> y << y Return true if the variant with 2 variable shifts is preferred.
virtual bool shouldFoldConstantShiftPairToMask (const SDNode *N, CombineLevel Level) const
Return true if it is profitable to fold a pair of shifts into a mask.
virtual bool shouldTransformSignedTruncationCheck (EVT XVT, unsigned KeptBits) const
Should we tranform the IR-optimal check for whether given truncation down into KeptBits would be truncating or not: (add x, (1 << (KeptBits-1))) srccond (1 << KeptBits) Into it's more traditional form: ((x << C) a>> C) dstcond x Return true if we should transform.
virtual bool shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd (SDValue X, ConstantSDNode *XC, ConstantSDNode *CC, SDValue Y, unsigned OldShiftOpcode, unsigned NewShiftOpcode, SelectionDAG &DAG) const
Given the pattern (X & (C l>>/<< Y)) ==/!= 0 return true if it should be transformed into: ((X <</l>> Y) & C) ==/!= 0 WARNING: if 'X' is a constant, the fold may deadlock! FIXME: we could avoid passing XC, but we can't use isConstOrConstSplat() here because it can end up being not linked in.
virtual bool preferIncOfAddToSubOfNot (EVT VT) const
These two forms are equivalent: sub y, (xor x, -1) add (add x, 1), y The variant with two add's is IR-canonical.
bool enableExtLdPromotion () const
Return true if the target wants to use the optimization that turns ext(promotableInst1(...(promotableInstN(load)))) into promotedInst1(...(promotedInstN(ext(load)))).
virtual bool canCombineStoreAndExtract (Type *VectorTy, Value *Idx, unsigned &Cost) const
Return true if the target can combine store(extractelement VectorTy, Idx).
virtual bool shouldSplatInsEltVarIndex (EVT) const
Return true if inserting a scalar into a variable element of an undef vector is more efficiently handled by splatting the scalar instead.
virtual bool enableAggressiveFMAFusion (EVT VT) const
Return true if target always benefits from combining into FMA for a given value type.
virtual MVT::SimpleValueType getCmpLibcallReturnType () const
Return the ValueType for comparison libcalls.
BooleanContent getBooleanContents (bool isVec, bool isFloat) const
For targets without i1 registers, this gives the nature of the high-bits of boolean values held in types wider than i1.
BooleanContent getBooleanContents (EVT Type) const
Sched::Preference getSchedulingPreference () const
Return target scheduling preference.
virtual Sched::Preference getSchedulingPreference (SDNode *) const
Some scheduler, e.g.
virtual const TargetRegisterClass * getRegClassFor (MVT VT, bool isDivergent=false) const
Return the register class that should be used for the specified value type.
virtual bool requiresUniformRegister (MachineFunction &MF, const Value *) const
Allows target to decide about the register class of the specific value that is live outside the defining block.
virtual const TargetRegisterClass * getRepRegClassFor (MVT VT) const
Return the 'representative' register class for the specified value type.
virtual uint8_t getRepRegClassCostFor (MVT VT) const
Return the cost of the 'representative' register class for the specified value type.
virtual bool shouldExpandShift (SelectionDAG &DAG, SDNode *N) const
Return true if SHIFT instructions should be expanded to SHIFT_PARTS instructions, and false if a library call is preferred (e.g for code-size reasons).
bool isTypeLegal (EVT VT) const
Return true if the target has native support for the specified value type.
const ValueTypeActionImpl & getValueTypeActions () const
LegalizeTypeAction getTypeAction (LLVMContext &Context, EVT VT) const
Return how we should legalize values of this type, either it is already legal (return 'Legal') or we need to promote it to a larger type (return 'Promote'), or we need to expand it into multiple registers of smaller integer type (return 'Expand').
LegalizeTypeAction getTypeAction (MVT VT) const
EVT getTypeToTransformTo (LLVMContext &Context, EVT VT) const
For types supported by the target, this is an identity function.
EVT getTypeToExpandTo (LLVMContext &Context, EVT VT) const
For types supported by the target, this is an identity function.
unsigned getVectorTypeBreakdown (LLVMContext &Context, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
Vector types are broken down into some number of legal first class types.
virtual unsigned getVectorTypeBreakdownForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
Certain targets such as MIPS require that some types such as vectors are always broken down into scalars in some contexts.
virtual bool getTgtMemIntrinsic (IntrinsicInfo &, const CallInst &, MachineFunction &, unsigned) const
Given an intrinsic, checks if on the target the intrinsic will need to map to a MemIntrinsicNode (touches memory).
virtual bool isFPImmLegal (const APFloat &, EVT, bool ForCodeSize=false) const
Returns true if the target can instruction select the specified FP immediate natively.
virtual bool isShuffleMaskLegal (ArrayRef< int >, EVT) const
Targets can use this to indicate that they only support some VECTOR_SHUFFLE operations, those with specific masks.
virtual bool canOpTrap (unsigned Op, EVT VT) const
Returns true if the operation can trap for the value type.
virtual bool isVectorClearMaskLegal (ArrayRef< int >, EVT) const
Similar to isShuffleMaskLegal.
LegalizeAction getOperationAction (unsigned Op, EVT VT) const
Return how this operation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
virtual bool isSupportedFixedPointOperation (unsigned Op, EVT VT, unsigned Scale) const
Custom method defined by each target to indicate if an operation which may require a scale is supported natively by the target.
LegalizeAction getFixedPointOperationAction (unsigned Op, EVT VT, unsigned Scale) const
Some fixed point operations may be natively supported by the target but only for specific scales.
LegalizeAction getStrictFPOperationAction (unsigned Op, EVT VT) const
bool isOperationLegalOrCustom (unsigned Op, EVT VT, bool LegalOnly=false) const
Return true if the specified operation is legal on this target or can be made legal with custom lowering.
bool isOperationLegalOrPromote (unsigned Op, EVT VT, bool LegalOnly=false) const
Return true if the specified operation is legal on this target or can be made legal using promotion.
bool isOperationLegalOrCustomOrPromote (unsigned Op, EVT VT, bool LegalOnly=false) const
Return true if the specified operation is legal on this target or can be made legal with custom lowering or using promotion.
bool isOperationCustom (unsigned Op, EVT VT) const
Return true if the operation uses custom lowering, regardless of whether the type is legal or not.
virtual bool areJTsAllowed (const Function *Fn) const
Return true if lowering to a jump table is allowed.
bool rangeFitsInWord (const APInt &Low, const APInt &High, const DataLayout &DL) const
Check whether the range [Low,High] fits in a machine word.
virtual bool isSuitableForJumpTable (const SwitchInst *SI, uint64_t NumCases, uint64_t Range, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const
Return true if lowering to a jump table is suitable for a set of case clusters which may contain NumCases cases, Range range of values.
bool isSuitableForBitTests (unsigned NumDests, unsigned NumCmps, const APInt &Low, const APInt &High, const DataLayout &DL) const
Return true if lowering to a bit test is suitable for a set of case clusters which contains NumDests unique destinations, Low and High as its lowest and highest case values, and expects NumCmps case value comparisons.
bool isOperationExpand (unsigned Op, EVT VT) const
Return true if the specified operation is illegal on this target or unlikely to be made legal with custom lowering.
bool isOperationLegal (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target.
LegalizeAction getLoadExtAction (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return how this load with extension should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isLoadExtLegal (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal on this target.
bool isLoadExtLegalOrCustom (unsigned ExtType, EVT ValVT, EVT MemVT) const
Return true if the specified load with extension is legal or custom on this target.
LegalizeAction getTruncStoreAction (EVT ValVT, EVT MemVT) const
Return how this store with truncation should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isTruncStoreLegal (EVT ValVT, EVT MemVT) const
Return true if the specified store with truncation is legal on this target.
bool isTruncStoreLegalOrCustom (EVT ValVT, EVT MemVT) const
Return true if the specified store with truncation has solution on this target.
virtual bool canCombineTruncStore (EVT ValVT, EVT MemVT, bool LegalOnly) const
LegalizeAction getIndexedLoadAction (unsigned IdxMode, MVT VT) const
Return how the indexed load should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedStoreAction (unsigned IdxMode, MVT VT) const
Return how the indexed store should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedMaskedLoadAction (unsigned IdxMode, MVT VT) const
Return how the indexed load should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedMaskedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedMaskedStoreAction (unsigned IdxMode, MVT VT) const
Return how the indexed store should be treated: either it is legal, needs to be promoted to a larger size, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isIndexedMaskedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
virtual bool shouldExtendGSIndex (EVT VT, EVT &EltTy) const
Returns true if the index type for a masked gather/scatter requires extending.
virtual bool shouldRemoveExtendFromGSIndex (EVT VT) const
LegalizeAction getCondCodeAction (ISD::CondCode CC, MVT VT) const
Return how the condition code should be treated: either it is legal, needs to be expanded to some other code sequence, or the target has a custom expander for it.
bool isCondCodeLegal (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal on this target.
bool isCondCodeLegalOrCustom (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal or custom on this target.
MVT getTypeToPromoteTo (unsigned Op, MVT VT) const
If the action for this operation is to promote, this method returns the ValueType to promote to.
virtual EVT getAsmOperandValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
EVT getValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
Return the EVT corresponding to this LLVM type.
EVT getMemValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
MVT getSimpleValueType (const DataLayout &DL, Type *Ty, bool AllowUnknown=false) const
Return the MVT corresponding to this LLVM type. See getValueType.
virtual unsigned getByValTypeAlignment (Type *Ty, const DataLayout &DL) const
Return the desired alignment for ByVal or InAlloca aggregate function arguments in the caller parameter area.
MVT getRegisterType (MVT VT) const
Return the type of registers that this ValueType will eventually require.
MVT getRegisterType (LLVMContext &Context, EVT VT) const
Return the type of registers that this ValueType will eventually require.
virtual unsigned getNumRegisters (LLVMContext &Context, EVT VT, Optional< MVT > RegisterVT=None) const
Return the number of registers that this ValueType will eventually require.
virtual MVT getRegisterTypeForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT) const
Certain combinations of ABIs, Targets and features require that types are legal for some operations and not for other operations.
virtual unsigned getNumRegistersForCallingConv (LLVMContext &Context, CallingConv::ID CC, EVT VT) const
Certain targets require unusual breakdowns of certain types.
virtual Align getABIAlignmentForCallingConv (Type *ArgTy, const DataLayout &DL) const
Certain targets have context sensitive alignment requirements, where one type has the alignment requirement of another type.
virtual bool shouldReduceLoadWidth (SDNode *Load, ISD::LoadExtType ExtTy, EVT NewVT) const
Return true if it is profitable to reduce a load to a smaller type.
bool hasBigEndianPartOrdering (EVT VT, const DataLayout &DL) const
When splitting a value of the specified type into parts, does the Lo or Hi part come first? This usually follows the endianness, except for ppcf128, where the Hi part always comes first.
bool hasTargetDAGCombine (ISD::NodeType NT) const
If true, the target has custom DAG combine transformations that it can perform for the specified node.
unsigned getGatherAllAliasesMaxDepth () const
virtual unsigned getVaListSizeInBits (const DataLayout &DL) const
Returns the size of the platform's va_list object.
unsigned getMaxStoresPerMemset (bool OptSize) const
Get maximum # of store operations permitted for llvm.memset.
unsigned getMaxStoresPerMemcpy (bool OptSize) const
Get maximum # of store operations permitted for llvm.memcpy.
virtual unsigned getMaxGluedStoresPerMemcpy () const
Get maximum # of store operations to be glued together.
unsigned getMaxExpandSizeMemcmp (bool OptSize) const
Get maximum # of load operations permitted for memcmp.
unsigned getMaxStoresPerMemmove (bool OptSize) const
Get maximum # of store operations permitted for llvm.memmove.
virtual bool allowsMisalignedMemoryAccesses (EVT, unsigned AddrSpace=0, Align Alignment=Align(1), MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *=nullptr) const
Determine if the target supports unaligned memory accesses.
virtual bool allowsMisalignedMemoryAccesses (LLT, unsigned AddrSpace=0, Align Alignment=Align(1), MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *=nullptr) const
LLT handling variant.
bool allowsMemoryAccessForAlignment (LLVMContext &Context, const DataLayout &DL, EVT VT, unsigned AddrSpace=0, Align Alignment=Align(1), MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *Fast=nullptr) const
This function returns true if the memory access is aligned or if the target allows this specific unaligned memory access.
bool allowsMemoryAccessForAlignment (LLVMContext &Context, const DataLayout &DL, EVT VT, const MachineMemOperand &MMO, bool *Fast=nullptr) const
Return true if the memory access of this type is aligned or if the target allows this specific unaligned access for the given MachineMemOperand.
virtual bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, EVT VT, unsigned AddrSpace=0, Align Alignment=Align(1), MachineMemOperand::Flags Flags=MachineMemOperand::MONone, bool *Fast=nullptr) const
Return true if the target supports a memory access of this type for the given address space and alignment.
bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, EVT VT, const MachineMemOperand &MMO, bool *Fast=nullptr) const
Return true if the target supports a memory access of this type for the given MachineMemOperand.
bool allowsMemoryAccess (LLVMContext &Context, const DataLayout &DL, LLT Ty, const MachineMemOperand &MMO, bool *Fast=nullptr) const
LLT handling variant.
virtual EVT getOptimalMemOpType (const MemOp &Op, const AttributeList &) const
Returns the target specific optimal type for load and store operations as a result of memset, memcpy, and memmove lowering.
virtual LLT getOptimalMemOpLLT (const MemOp &Op, const AttributeList &) const
LLT returning variant.
virtual bool isSafeMemOpType (MVT) const
Returns true if it's safe to use load / store of the specified type to expand memcpy / memset inline.
virtual unsigned getMinimumJumpTableEntries () const
Return lower limit for number of blocks in a jump table.
unsigned getMinimumJumpTableDensity (bool OptForSize) const
Return lower limit of the density in a jump table.
unsigned getMaximumJumpTableSize () const
Return upper limit for number of entries in a jump table.
virtual bool isJumpTableRelative () const
Register getStackPointerRegisterToSaveRestore () const
If a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
virtual bool needsFixedCatchObjects () const
Align getMinStackArgumentAlignment () const
Return the minimum stack alignment of an argument.
Align getMinFunctionAlignment () const
Return the minimum function alignment.
Align getPrefFunctionAlignment () const
Return the preferred function alignment.
virtual Align getPrefLoopAlignment (MachineLoop *ML=nullptr) const
Return the preferred loop alignment.
virtual bool alignLoopsWithOptSize () const
Should loops be aligned even when the function is marked OptSize (but not MinSize).
virtual Value * getIRStackGuard (IRBuilderBase &IRB) const
If the target has a standard location for the stack protector guard, returns the address of that location.
virtual Value * getSDagStackGuard (const Module &M) const
Return the variable that's previously inserted by insertSSPDeclarations, if any, otherwise return nullptr.
virtual bool useStackGuardXorFP () const
If this function returns true, stack protection checks should XOR the frame pointer (or whichever pointer is used to address locals) into the stack guard value before checking it.
virtual Function * getSSPStackGuardCheck (const Module &M) const
If the target has a standard stack protection check function that performs validation and error handling, returns the function.
virtual bool isConstantUnsignedBitfieldExtactLegal (unsigned Opc, LLT Ty1, LLT Ty2) const
virtual Value * getSafeStackPointerLocation (IRBuilderBase &IRB) const
Returns the target-specific address of the unsafe stack pointer.
virtual bool hasStackProbeSymbol (MachineFunction &MF) const
Returns the name of the symbol used to emit stack probes or the empty string if not applicable.
virtual bool hasInlineStackProbe (MachineFunction &MF) const
virtual StringRef getStackProbeSymbolName (MachineFunction &MF) const
virtual bool isFreeAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast from SrcAS to DestAS is "cheap", such that e.g.
virtual bool shouldAlignPointerArgs (CallInst *, unsigned &, unsigned &) const
Return true if the pointer arguments to CI should be aligned by aligning the object whose address is being passed.
virtual void emitAtomicCmpXchgNoStoreLLBalance (IRBuilderBase &Builder) const
virtual bool shouldExpandAtomicStoreInIR (StoreInst *SI) const
Returns true if the given (atomic) store should be expanded by the IR-level AtomicExpand pass into an "atomic xchg" which ignores its input.
virtual bool shouldSignExtendTypeInLibCall (EVT Type, bool IsSigned) const
Returns true if arguments should be sign-extended in lib calls.
virtual bool shouldExtendTypeInLibCall (EVT Type) const
Returns true if arguments should be extended in lib calls.
virtual AtomicExpansionKind shouldExpandAtomicLoadInIR (LoadInst *LI) const
Returns how the given (atomic) load should be expanded by the IR-level AtomicExpand pass.
virtual AtomicExpansionKind shouldExpandAtomicCmpXchgInIR (AtomicCmpXchgInst *AI) const
Returns how the given atomic cmpxchg should be expanded by the IR-level AtomicExpand pass.
virtual LoadInst * lowerIdempotentRMWIntoFencedLoad (AtomicRMWInst *RMWI) const
On some platforms, an AtomicRMW that never actually modifies the value (such as fetch_add of 0) can be turned into a fence followed by an atomic load.
virtual ISD::NodeType getExtendForAtomicOps () const
Returns how the platform's atomic operations are extended (ZERO_EXTEND, SIGN_EXTEND, or ANY_EXTEND).
virtual ISD::NodeType getExtendForAtomicCmpSwapArg () const
Returns how the platform's atomic compare and swap expects its comparison value to be extended (ZERO_EXTEND, SIGN_EXTEND, or ANY_EXTEND).
virtual bool shouldNormalizeToSelectSequence (LLVMContext &Context, EVT VT) const
Returns true if we should normalize select(N0&N1, X, Y) => select(N0, select(N1, X, Y), Y) and select(N0|N1, X, Y) => select(N0, select(N1, X, Y, Y)) if it is likely that it saves us from materializing N0 and N1 in an integer register.
virtual bool isProfitableToCombineMinNumMaxNum (EVT VT) const
virtual bool convertSelectOfConstantsToMath (EVT VT) const
Return true if a select of constants (select Cond, C1, C2) should be transformed into simple math ops with the condition value.
virtual bool decomposeMulByConstant (LLVMContext &Context, EVT VT, SDValue C) const
Return true if it is profitable to transform an integer multiplication-by-constant into simpler operations like shifts and adds.
virtual bool shouldUseStrictFP_TO_INT (EVT FpVT, EVT IntVT, bool IsSigned) const
Return true if it is more correct/profitable to use strict FP_TO_INT conversion operations - canonicalizing the FP source value instead of converting all cases and then selecting based on value.
virtual bool getAddrModeArguments (IntrinsicInst *, SmallVectorImpl< Value * > &, Type *&) const
CodeGenPrepare sinks address calculations into the same BB as Load/Store instructions reading the address.
virtual bool isLegalAddressingMode (const DataLayout &DL, const AddrMode &AM, Type *Ty, unsigned AddrSpace, Instruction *I=nullptr) const
Return true if the addressing mode represented by AM is legal for this target, for a load/store of the specified type.
virtual InstructionCost getScalingFactorCost (const DataLayout &DL, const AddrMode &AM, Type *Ty, unsigned AS=0) const
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
virtual bool isLegalICmpImmediate (int64_t) const
Return true if the specified immediate is legal icmp immediate, that is the target has icmp instructions which can compare a register against the immediate without having to materialize the immediate into a register.
virtual bool isLegalAddImmediate (int64_t) const
Return true if the specified immediate is legal add immediate, that is the target has add instructions which can add a register with the immediate without having to materialize the immediate into a register.
virtual bool isLegalStoreImmediate (int64_t Value) const
Return true if the specified immediate is legal for the value input of a store instruction.
virtual bool isVectorShiftByScalarCheap (Type *Ty) const
Return true if it's significantly cheaper to shift a vector by a uniform scalar than by an amount which will vary across each lane.
virtual Type * shouldConvertSplatType (ShuffleVectorInst *SVI) const
Given a shuffle vector SVI representing a vector splat, return a new scalar type of size equal to SVI's scalar type if the new type is more profitable.
virtual bool shouldConvertPhiType (Type *From, Type *To) const
Given a set in interconnected phis of type 'From' that are loaded/stored or bitcast to type 'To', return true if the set should be converted to 'To'.
virtual bool isCommutativeBinOp (unsigned Opcode) const
Returns true if the opcode is a commutative binary operation.
virtual bool isBinOp (unsigned Opcode) const
Return true if the node is a math/logic binary operator.
virtual bool isTruncateFree (Type *FromTy, Type *ToTy) const
Return true if it's free to truncate a value of type FromTy to type ToTy.
virtual bool allowTruncateForTailCall (Type *FromTy, Type *ToTy) const
Return true if a truncation from FromTy to ToTy is permitted when deciding whether a call is in tail position.
virtual bool isTruncateFree (EVT FromVT, EVT ToVT) const
virtual bool isProfitableToHoist (Instruction *I) const
bool isExtFree (const Instruction *I) const
Return true if the extension represented by I is free.
bool isExtLoad (const LoadInst *Load, const Instruction *Ext, const DataLayout &DL) const
Return true if Load and Ext can form an ExtLoad.
virtual bool isZExtFree (Type *FromTy, Type *ToTy) const
Return true if any actual instruction that defines a value of type FromTy implicitly zero-extends the value to ToTy in the result register.
virtual bool isZExtFree (EVT FromTy, EVT ToTy) const
virtual bool isSExtCheaperThanZExt (EVT FromTy, EVT ToTy) const
Return true if sign-extension from FromTy to ToTy is cheaper than zero-extension.
virtual bool shouldSinkOperands (Instruction *I, SmallVectorImpl< Use * > &Ops) const
Return true if sinking I's operands to the same basic block as I is profitable, e.g.
virtual bool hasPairedLoad (EVT, Align &) const
Return true if the target supplies and combines to a paired load two loaded values of type LoadedType next to each other in memory.
virtual bool hasVectorBlend () const
Return true if the target has a vector blend instruction.
virtual unsigned getMaxSupportedInterleaveFactor () const
Get the maximum supported factor for interleaved memory accesses.
virtual bool lowerInterleavedLoad (LoadInst *LI, ArrayRef< ShuffleVectorInst * > Shuffles, ArrayRef< unsigned > Indices, unsigned Factor) const
Lower an interleaved load to target specific intrinsics.
virtual bool lowerInterleavedStore (StoreInst *SI, ShuffleVectorInst *SVI, unsigned Factor) const
Lower an interleaved store to target specific intrinsics.
virtual bool isZExtFree (SDValue Val, EVT VT2) const
Return true if zero-extending the specific node Val to type VT2 is free (either because it's implicitly zero-extended such as ARM ldrb / ldrh or because it's folded such as X86 zero-extending loads).
virtual bool isFPExtFree (EVT DestVT, EVT SrcVT) const
Return true if an fpext operation is free (for instance, because single-precision floating-point numbers are implicitly extended to double-precision).
virtual bool isFPExtFoldable (const SelectionDAG &DAG, unsigned Opcode, EVT DestVT, EVT SrcVT) const
Return true if an fpext operation input to an Opcode operation is free (for instance, because half-precision floating-point numbers are implicitly extended to float-precision) for an FMA instruction.
virtual bool isVectorLoadExtDesirable (SDValue ExtVal) const
Return true if folding a vector load into ExtVal (a sign, zero, or any extend node) is profitable.
virtual bool isFNegFree (EVT VT) const
Return true if an fneg operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
virtual bool isFAbsFree (EVT VT) const
Return true if an fabs operation is free to the point where it is never worthwhile to replace it with a bitwise operation.
virtual bool isFMAFasterThanFMulAndFAdd (const MachineFunction &MF, EVT) const
Return true if an FMA operation is faster than a pair of fmul and fadd instructions.
virtual bool isFMAFasterThanFMulAndFAdd (const Function &F, Type *) const
IR version.
virtual bool isFMADLegal (const SelectionDAG &DAG, const SDNode *N) const
Returns true if be combined with to form an ISD::FMAD.
virtual bool generateFMAsInMachineCombiner (EVT VT, CodeGenOpt::Level OptLevel) const
virtual bool isNarrowingProfitable (EVT, EVT) const
Return true if it's profitable to narrow operations of type VT1 to VT2.
virtual bool shouldConvertConstantLoadToIntImm (const APInt &Imm, Type *Ty) const
Return true if it is beneficial to convert a load of a constant to just the constant itself.
virtual bool isExtractSubvectorCheap (EVT ResVT, EVT SrcVT, unsigned Index) const
Return true if EXTRACT_SUBVECTOR is cheap for extracting this result type from this source type with this index.
virtual bool shouldScalarizeBinop (SDValue VecOp) const
Try to convert an extract element of a vector binary operation into an extract element followed by a scalar operation.
virtual bool isExtractVecEltCheap (EVT VT, unsigned Index) const
Return true if extraction of a scalar element from the given vector type at the given index is cheap.
virtual bool shouldFormOverflowOp (unsigned Opcode, EVT VT, bool MathUsed) const
Try to convert math with an overflow comparison into the corresponding DAG node operation.
virtual bool aggressivelyPreferBuildVectorSources (EVT VecVT) const
virtual bool shouldConsiderGEPOffsetSplit () const
virtual bool shouldAvoidTransformToShift (EVT VT, unsigned Amount) const
Return true if creating a shift of the type by the given amount is not profitable.
virtual bool shouldKeepZExtForFP16Conv () const
Does this target require the clearing of high-order bits in a register passed to the fp16 to fp conversion library function.
void setLibcallName (RTLIB::Libcall Call, const char *Name)
Rename the default libcall routine name for the specified libcall.
const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
void setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC)
Override the default CondCode to be used to test the result of the comparison libcall against zero.
ISD::CondCode getCmpLibcallCC (RTLIB::Libcall Call) const
Get the CondCode that's to be used to test the result of the comparison libcall against zero.
void setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC)
Set the CallingConv that should be used for the specified libcall.
CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
Get the CallingConv that should be used for the specified libcall.
virtual void finalizeLowering (MachineFunction &MF) const
Execute target specific actions to finalize target lowering.
virtual bool shouldLocalize (const MachineInstr &MI, const TargetTransformInfo *TTI) const
Check whether or not MI needs to be moved close to its uses.
int InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
std::pair< InstructionCost, MVT > getTypeLegalizationCost (const DataLayout &DL, Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
unsigned getMaxAtomicSizeInBitsSupported () const
Returns the maximum atomic operation size (in bits) supported by the backend.
unsigned getMinCmpXchgSizeInBits () const
Returns the size of the smallest cmpxchg or ll/sc instruction the backend supports.
bool supportsUnalignedAtomics () const
Whether the target supports unaligned atomic operations.
virtual Value * emitLoadLinked (IRBuilderBase &Builder, Type *ValueTy, Value *Addr, AtomicOrdering Ord) const
Perform a load-linked operation on Addr, returning a "Value *" with the corresponding pointee type.
virtual Value * emitStoreConditional (IRBuilderBase &Builder, Value *Val, Value *Addr, AtomicOrdering Ord) const
Perform a store-conditional operation to Addr.
virtual Value * emitMaskedAtomicRMWIntrinsic (IRBuilderBase &Builder, AtomicRMWInst *AI, Value *AlignedAddr, Value *Incr, Value *Mask, Value *ShiftAmt, AtomicOrdering Ord) const
Perform a masked atomicrmw using a target-specific intrinsic.
virtual Value * emitMaskedAtomicCmpXchgIntrinsic (IRBuilderBase &Builder, AtomicCmpXchgInst *CI, Value *AlignedAddr, Value *CmpVal, Value *NewVal, Value *Mask, AtomicOrdering Ord) const
Perform a masked cmpxchg using a target-specific intrinsic.
virtual Instruction * emitLeadingFence (IRBuilderBase &Builder, Instruction *Inst, AtomicOrdering Ord) const
Inserts in the IR a target-specific intrinsic specifying a fence.
virtual Instruction * emitTrailingFence (IRBuilderBase &Builder, Instruction *Inst, AtomicOrdering Ord) const
Additional Inherited Members
Public Types inherited from llvm::TargetLowering
enum ConstraintType {
C_Register , C_RegisterClass , C_Memory , C_Immediate ,
C_Other , C_Unknown
}
enum ConstraintWeight {
CW_Invalid = -1 , CW_Okay = 0 , CW_Good = 1 , CW_Better = 2 ,
CW_Best = 3 , CW_SpecificReg = CW_Okay , CW_Register = CW_Good , CW_Memory = CW_Better ,
CW_Constant = CW_Best , CW_Default = CW_Okay
}
using AsmOperandInfoVector = std::vector<AsmOperandInfo>
Public Types inherited from llvm::TargetLoweringBase
enum LegalizeAction : uint8_t {
Legal , Promote , Expand , LibCall ,
Custom
}
This enum indicates whether operations are valid for a target, and if not, what action should be used to make them valid.
enum LegalizeTypeAction : uint8_t {
TypeLegal , TypePromoteInteger , TypeExpandInteger , TypeSoftenFloat ,
TypeExpandFloat , TypeScalarizeVector , TypeSplitVector , TypeWidenVector ,
TypePromoteFloat , TypeSoftPromoteHalf , TypeScalarizeScalableVector
}
This enum indicates whether a types are legal for a target, and if not, what action should be used to make them valid.
enum BooleanContent { UndefinedBooleanContent , ZeroOrOneBooleanContent , ZeroOrNegativeOneBooleanContent }
Enum that describes how the target represents true/false values.
enum SelectSupportKind { ScalarValSelect , ScalarCondVectorVal , VectorMaskSelect }
Enum that describes what type of support for selects the target has.
enum class AtomicExpansionKind {
None , LLSC , LLOnly , CmpXChg ,
MaskedIntrinsic
}
Enum that specifies what an atomic load/AtomicRMWInst is expanded to, if at all.
enum class MulExpansionKind { Always , OnlyLegalOrCustom }
Enum that specifies when a multiplication should be expanded.
enum class NegatibleCost { Cheaper = 0 , Neutral = 1 , Expensive = 2 }
Enum that specifies when a float negation is beneficial.
enum ReciprocalEstimate : int { Unspecified = -1 , Disabled = 0 , Enabled = 1 }
Reciprocal estimate status values used by the functions below.
using LegalizeKind = std::pair<LegalizeTypeAction, EVT>
LegalizeKind holds the legalization kind that needs to happen to EVT in order to type-legalize it.
using ArgListTy = std::vector<ArgListEntry>
Static Public Member Functions inherited from llvm::TargetLoweringBase
static ISD::NodeType getExtendForContent (BooleanContent Content)
Protected Member Functions inherited from llvm::TargetLoweringBase
void initActions ()
Initialize all of the actions to default values.
Value * getDefaultSafeStackPointerLocation (IRBuilderBase &IRB, bool UseTLS) const
void setBooleanContents (BooleanContent Ty)
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
void setBooleanContents (BooleanContent IntTy, BooleanContent FloatTy)
Specify how the target extends the result of integer and floating point boolean values from i1 to a wider type.
void setBooleanVectorContents (BooleanContent Ty)
Specify how the target extends the result of a vector boolean value from a vector of i1 to a wider type.
void setSchedulingPreference (Sched::Preference Pref)
Specify the target scheduling preference.
void setMinimumJumpTableEntries (unsigned Val)
Indicate the minimum number of blocks to generate jump tables.
void setMaximumJumpTableSize (unsigned)
Indicate the maximum number of entries in jump tables.
void setStackPointerRegisterToSaveRestore (Register R)
If set to a physical register, this specifies the register that llvm.savestack/llvm.restorestack should save and restore.
void setHasMultipleConditionRegisters (bool hasManyRegs=true)
Tells the code generator that the target has multiple (allocatable) condition registers that can be used to store the results of comparisons for use by selects and conditional branches.
void setHasExtractBitsInsn (bool hasExtractInsn=true)
Tells the code generator that the target has BitExtract instructions.
void setJumpIsExpensive (bool isExpensive=true)
Tells the code generator not to expand logic operations on comparison predicates into separate sequences that increase the amount of flow control.
void addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth)
Tells the code generator which bitwidths to bypass.
void addRegisterClass (MVT VT, const TargetRegisterClass *RC)
Add the specified register class as an available regclass for the specified value type.
virtual std::pair< const TargetRegisterClass *, uint8_t > findRepresentativeClass (const TargetRegisterInfo *TRI, MVT VT) const
Return the largest legal super-reg register class of the register class for the specified type and its associated "cost".
void computeRegisterProperties (const TargetRegisterInfo *TRI)
Once all of the register classes are added, this allows us to compute derived properties we expose.
void setOperationAction (unsigned Op, MVT VT, LegalizeAction Action)
Indicate that the specified operation does not work with the specified type and indicate what to do about it.
void setLoadExtAction (unsigned ExtType, MVT ValVT, MVT MemVT, LegalizeAction Action)
Indicate that the specified load with extension does not work with the specified type and indicate what to do about it.
void setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action)
Indicate that the specified truncating store does not work with the specified type and indicate what to do about it.
void setIndexedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed load does or does not work with the specified type and indicate what to do abort it.
void setIndexedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed store does or does not work with the specified type and indicate what to do about it.
void setIndexedMaskedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed masked load does or does not work with the specified type and indicate what to do about it.
void setIndexedMaskedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
Indicate that the specified indexed masked store does or does not work with the specified type and indicate what to do about it.
void setCondCodeAction (ISD::CondCode CC, MVT VT, LegalizeAction Action)
Indicate that the specified condition code is or isn't supported on the target and indicate what to do about it.
void AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
If Opc/OrigVT is specified as being promoted, the promotion code defaults to trying a larger integer/fp until it can find one that works.
void setOperationPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
Convenience method to set an operation to Promote and specify the type in a single call.
void setTargetDAGCombine (ISD::NodeType NT)
Targets should invoke this method for each target independent node that they want to provide a custom DAG combiner for by implementing the PerformDAGCombine virtual method.
void setMinFunctionAlignment (Align Alignment)
Set the target's minimum function alignment.
void setPrefFunctionAlignment (Align Alignment)
Set the target's preferred function alignment.
void setPrefLoopAlignment (Align Alignment)
Set the target's preferred loop alignment.
void setMinStackArgumentAlignment (Align Alignment)
Set the minimum stack alignment of an argument.
void setMaxAtomicSizeInBitsSupported (unsigned SizeInBits)
Set the maximum atomic operation size supported by the backend.
void setMinCmpXchgSizeInBits (unsigned SizeInBits)
Sets the minimum cmpxchg or ll/sc size supported by the backend.
void setSupportsUnalignedAtomics (bool UnalignedSupported)
Sets whether unaligned atomic operations are supported.
virtual bool isExtFreeImpl (const Instruction *I) const
Return true if the extension represented by I is free.
bool isLegalRC (const TargetRegisterInfo &TRI, const TargetRegisterClass &RC) const
Return true if the value types that can be represented by the specified register class are all legal.
MachineBasicBlock * emitPatchPoint (MachineInstr &MI, MachineBasicBlock *MBB) const
Replace/modify any TargetFrameIndex operands with a targte-dependent sequence of memory operands that is recognized by PrologEpilogInserter.
Protected Attributes inherited from llvm::TargetLoweringBase
unsigned GatherAllAliasesMaxDepth
Depth that GatherAllAliases should should continue looking for chain dependencies when trying to find a more preferable chain.
unsigned MaxStoresPerMemset
Specify maximum number of store instructions per memset call.
unsigned MaxStoresPerMemsetOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxStoresPerMemcpy
Specify maximum number of store instructions per memcpy call.
unsigned MaxStoresPerMemcpyOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxGluedStoresPerMemcpy = 0
Specify max number of store instructions to glue in inlined memcpy.
unsigned MaxLoadsPerMemcmp
Specify maximum number of load instructions per memcmp call.
unsigned MaxLoadsPerMemcmpOptSize
Likewise for functions with the OptSize attribute.
unsigned MaxStoresPerMemmove
Specify maximum number of store instructions per memmove call.
unsigned MaxStoresPerMemmoveOptSize
Likewise for functions with the OptSize attribute.
bool PredictableSelectIsExpensive
Tells the code generator that select is more expensive than a branch if the branch is usually predicted right.
bool EnableExtLdPromotion
bool IsStrictFPEnabled
Detailed Description
Definition at line 53 of file SparcISelLowering.h.
Constructor & Destructor Documentation
SparcTargetLowering()
SparcTargetLowering::SparcTargetLowering (const TargetMachine & TM, const SparcSubtarget & STI)
Definition at line 1408 of file SparcISelLowering.cpp.
References llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::TargetLoweringBase::addRegisterClass(), Align, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_FENCE, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::ISD::BITCAST, llvm::ISD::BlockAddress, llvm::ISD::BR_CC, llvm::ISD::BR_JT, llvm::ISD::BRCOND, llvm::ISD::BRIND, llvm::ISD::BSWAP, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::TargetLoweringBase::computeRegisterProperties(), llvm::ISD::ConstantPool, llvm::ISD::CTLZ, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::TargetLoweringBase::Custom, llvm::ISD::DEBUGTRAP, llvm::ISD::DYNAMIC_STACKALLOC, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::SparcSubtarget::fixAllFDIVSQRT(), llvm::ISD::FMA, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::ISD::FP16_TO_FP, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_FP16, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::MVT::fp_valuetypes(), llvm::ISD::FPOW, llvm::ISD::FREM, llvm::ISD::FSIN, llvm::ISD::FSINCOS, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::MVT::getIntegerVT(), llvm::SparcSubtarget::getRegisterInfo(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::SparcSubtarget::hasHardQuad(), llvm::SparcSubtarget::hasLeonCasa(), llvm::SparcSubtarget::hasLeonCycleCounter(), llvm::SparcSubtarget::hasNoFMULS(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::MVT::integer_fixedlen_vector_valuetypes(), llvm::MVT::integer_valuetypes(), llvm::ISD::INTRINSIC_WO_CHAIN, llvm::SparcSubtarget::is64Bit(), llvm::SparcSubtarget::isV9(), llvm::IRSimilarity::Legal, llvm::ISD::LOAD, llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, llvm::MVT::Other, llvm::TargetLoweringBase::Promote, llvm::ISD::READCYCLECOUNTER, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::TargetLoweringBase::setBooleanContents(), llvm::TargetLoweringBase::setBooleanVectorContents(), llvm::ISD::SETCC, llvm::TargetLoweringBase::setLibcallName(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::TargetLoweringBase::setMaxAtomicSizeInBitsSupported(), llvm::TargetLoweringBase::setMinCmpXchgSizeInBits(), llvm::TargetLoweringBase::setMinFunctionAlignment(), llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setStackPointerRegisterToSaveRestore(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::ISD::SEXTLOAD, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::SMUL_LOHI, llvm::ISD::SMULO, llvm::ISD::SRA_PARTS, llvm::ISD::SREM, llvm::ISD::SRL_PARTS, llvm::ISD::STACKRESTORE, llvm::ISD::STACKSAVE, llvm::ISD::STORE, llvm::ISD::SUBC, llvm::ISD::SUBE, TM, llvm::ISD::TRAP, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::ISD::UMUL_LOHI, llvm::ISD::UMULO, llvm::ISD::UREM, llvm::SparcSubtarget::usePopc(), llvm::SparcSubtarget::useSoftFloat(), llvm::SparcSubtarget::useSoftMulDiv(), llvm::MVT::v2i32, llvm::ISD::VAARG, llvm::ISD::VACOPY, llvm::ISD::VAEND, llvm::ISD::VASTART, llvm::TargetLoweringBase::ZeroOrOneBooleanContent, and llvm::ISD::ZEXTLOAD.
Member Function Documentation
bitcastConstantFPToInt()
SDValue SparcTargetLowering::bitcastConstantFPToInt (ConstantFPSDNode * C, const SDLoc & DL, SelectionDAG & DAG) const
Definition at line 3075 of file SparcISelLowering.cpp.
References C, DL, llvm::SelectionDAG::getBuildVector(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::MVT::i32, llvm::DataLayout::isLittleEndian(), std::swap(), and llvm::MVT::v2i32.
Referenced by LowerCall_32(), and PerformBITCASTCombine().
computeKnownBitsForTargetNode()
void SparcTargetLowering::computeKnownBitsForTargetNode (const SDValue Op, KnownBits & Known, const APInt & DemandedElts, const SelectionDAG & DAG, unsigned Depth = 0) const override virtual
computeKnownBitsForTargetNode - Determine which of the bits specified in Mask are known to be either zero or one and return them in the KnownZero/KnownOne bitsets.
isMaskedValueZeroForTargetNode - Return true if 'Op & Mask' is known to be zero.
Op is expected to be a target specific node. Used by DAG combiner.
Reimplemented from llvm::TargetLowering.
Definition at line 1867 of file SparcISelLowering.cpp.
References llvm::KnownBits::commonBits(), llvm::SelectionDAG::computeKnownBits(), llvm::Depth, llvm::KnownBits::resetAll(), llvm::SPISD::SELECT_FCC, llvm::SPISD::SELECT_ICC, and llvm::SPISD::SELECT_XCC.
EmitInstrWithCustomInserter()
MachineBasicBlock * SparcTargetLowering::EmitInstrWithCustomInserter (MachineInstr & MI, MachineBasicBlock * MBB) const override virtual
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag.
These instructions are special in various ways, which require special support to insert. The specified MachineInstr is created but not inserted into any basic blocks, and this method is called to expand it into a sequence of instructions, potentially also creating new basic blocks and control flow. As long as the returned basic block is different (i.e., we created a new one), the custom inserter is free to modify the rest of MBB.
Reimplemented from llvm::TargetLowering.
Definition at line 3110 of file SparcISelLowering.cpp.
References expandSelectCC(), llvm_unreachable, and MI.
expandSelectCC()
MachineBasicBlock * SparcTargetLowering::expandSelectCC (MachineInstr & MI, MachineBasicBlock * BB, unsigned BROpcode) const
Definition at line 3128 of file SparcISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), F, llvm::MachineBasicBlock::getBasicBlock(), llvm::SparcSubtarget::getInstrInfo(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MachineBasicBlock::getParent(), MI, and TII.
Referenced by EmitInstrWithCustomInserter().
getConstraintType()
SparcTargetLowering::ConstraintType SparcTargetLowering::getConstraintType (StringRef Constraint) const override virtual
getConstraintType - Given a constraint letter, return the type of constraint it is for this target.
Reimplemented from llvm::TargetLowering.
Definition at line 3190 of file SparcISelLowering.cpp.
References llvm::TargetLowering::C_Immediate, llvm::TargetLowering::C_RegisterClass, llvm::TargetLowering::getConstraintType(), and llvm::StringRef::size().
getExceptionPointerRegister()
Register llvm::SparcTargetLowering::getExceptionPointerRegister (const Constant * PersonalityFn) const inline override virtual
If a physical register, this returns the register that receives the exception address on entry to an EH pad.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 100 of file SparcISelLowering.h.
getExceptionSelectorRegister()
Register llvm::SparcTargetLowering::getExceptionSelectorRegister (const Constant * PersonalityFn) const inline override virtual
If a physical register, this returns the register that receives the exception typeid on entry to a landing pad.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 107 of file SparcISelLowering.h.
getRegForInlineAsmConstraint()
std::pair< unsigned, const TargetRegisterClass * > SparcTargetLowering::getRegForInlineAsmConstraint (const TargetRegisterInfo * TRI, StringRef Constraint, MVT VT) const override virtual
Given a physical register constraint (e.g.
{edx}), return the register number and the register class for the register.
Given a register class constraint, like 'r', if this corresponds directly to an LLVM register class, return a register of 0 and the register class pointer.
This should only be used for C_Register constraints. On error, this returns a register number of 0 and a null register class pointer.
Reimplemented from llvm::TargetLowering.
Definition at line 3266 of file SparcISelLowering.cpp.
References llvm::StringRef::data(), llvm::StringRef::empty(), llvm::StringRef::end(), llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::MVT::i32, llvm::MVT::i64, llvm::SparcSubtarget::is64Bit(), name, llvm::MVT::Other, llvm::StringRef::size(), TRI, and llvm::MVT::v2i32.
getRegisterByName()
Register SparcTargetLowering::getRegisterByName (const char * RegName, LLT Ty, const MachineFunction & MF) const override virtual
Return the register ID of the name passed in.
Used by named register global variables extension. There is no target-independent behaviour so the default action is to bail.
Reimplemented from llvm::TargetLowering.
Definition at line 1018 of file SparcISelLowering.cpp.
References Reg, RegName, and llvm::report_fatal_error().
getScalarShiftAmountTy()
MVT llvm::SparcTargetLowering::getScalarShiftAmountTy (const DataLayout & DL, EVT) const inline override virtual
EVT is not used in-tree, but is used by out-of-tree target.
A documentation for this function would be nice...
Reimplemented from llvm::TargetLoweringBase.
Definition at line 90 of file SparcISelLowering.h.
References llvm::MVT::i32.
getSetCCResultType()
EVT SparcTargetLowering::getSetCCResultType (const DataLayout & DL, LLVMContext & Context, EVT VT) const override virtual
getSetCCResultType - Return the ISD::SETCC ValueType
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1857 of file SparcISelLowering.cpp.
References llvm::EVT::changeVectorElementTypeToInteger(), llvm::MVT::i32, and llvm::EVT::isVector().
getSingleConstraintMatchWeight()
TargetLowering::ConstraintWeight SparcTargetLowering::getSingleConstraintMatchWeight (AsmOperandInfo & info, const char * constraint) const override virtual
Examine constraint string and operand type and determine a weight value.
Examine constraint type and operand type and determine a weight value.
The operand object must already have been set up with the operand type.
This object must already have been set up with the operand type and the current alternative constraint selected.
Reimplemented from llvm::TargetLowering.
Definition at line 3206 of file SparcISelLowering.cpp.
References C, llvm::TargetLowering::CW_Constant, llvm::TargetLowering::CW_Default, llvm::TargetLowering::CW_Invalid, llvm::TargetLowering::getSingleConstraintMatchWeight(), and info.
getTargetNodeName()
const char * SparcTargetLowering::getTargetNodeName (unsigned Opcode) const override virtual
This method returns the name of a target specific DAG node.
Reimplemented from llvm::TargetLowering.
Definition at line 1829 of file SparcISelLowering.cpp.
References llvm::SPISD::BRFCC, llvm::SPISD::BRICC, llvm::SPISD::BRXCC, llvm::SPISD::CALL, llvm::SPISD::CMPFCC, llvm::SPISD::CMPICC, llvm::SPISD::FIRST_NUMBER, llvm::SPISD::FLUSHW, llvm::SPISD::FTOI, llvm::SPISD::FTOX, llvm::SPISD::GLOBAL_BASE_REG, llvm::SPISD::Hi, llvm::SPISD::ITOF, llvm::SPISD::Lo, llvm::SPISD::RET_FLAG, llvm::SPISD::SELECT_FCC, llvm::SPISD::SELECT_ICC, llvm::SPISD::SELECT_XCC, llvm::SPISD::TLS_ADD, llvm::SPISD::TLS_CALL, llvm::SPISD::TLS_LD, and llvm::SPISD::XTOF.
insertSSPDeclarations()
void SparcTargetLowering::insertSSPDeclarations (Module & M) const override virtual
Inserts necessary declarations for SSP (stack protection) purpose.
Should be used only when getIRStackGuard returns nullptr.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 3428 of file SparcISelLowering.cpp.
References llvm::TargetLoweringBase::insertSSPDeclarations(), and llvm::SparcSubtarget::isTargetLinux().
isOffsetFoldingLegal()
bool SparcTargetLowering::isOffsetFoldingLegal (const GlobalAddressSDNode * GA) const override virtual
Return true if folding a constant offset with the given GlobalAddress is legal.
It is frequently not legal in PIC relocation models.
Reimplemented from llvm::TargetLowering.
Definition at line 3340 of file SparcISelLowering.cpp.
LowerAsmOperandForConstraint()
void SparcTargetLowering::LowerAsmOperandForConstraint (SDValue Op, std::string & Constraint, std::vector< SDValue > & Ops, SelectionDAG & DAG) const override virtual
LowerAsmOperandForConstraint - Lower the specified operand into the Ops vector.
If it is invalid, don't add anything to Ops.
Reimplemented from llvm::TargetLowering.
Definition at line 3233 of file SparcISelLowering.cpp.
References C, llvm::SelectionDAG::getTargetConstant(), and llvm::TargetLowering::LowerAsmOperandForConstraint().
LowerBlockAddress()
SDValue SparcTargetLowering::LowerBlockAddress (SDValue Op, SelectionDAG & DAG) const
Definition at line 2019 of file SparcISelLowering.cpp.
References makeAddress().
Referenced by LowerOperation().
LowerCall()
SDValue SparcTargetLowering::LowerCall (TargetLowering::CallLoweringInfo & , SmallVectorImpl< SDValue > &) const override virtual
This hook must be implemented to lower calls into the specified DAG.
The outgoing arguments to the call are described by the Outs array, and the values to be returned by the call are described by the Ins array. The implementation should fill in the InVals array with legal-type return values from the call, and return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 685 of file SparcISelLowering.cpp.
References llvm::SparcSubtarget::is64Bit(), LowerCall_32(), and LowerCall_64().
LowerCall_32()
SDValue SparcTargetLowering::LowerCall_32 (TargetLowering::CallLoweringInfo & CLI, SmallVectorImpl< SDValue > & InVals) const
Definition at line 715 of file SparcISelLowering.cpp.
References llvm::ISD::ADD, llvm::CCValAssign::AExt, llvm::CCState::AnalyzeCallOperands(), llvm::ISD::ANY_EXTEND, Arg, assert(), llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, bitcastConstantFPToInt(), C, llvm::SPISD::CALL, llvm::TargetLowering::CallLoweringInfo::CallConv, llvm::TargetLowering::CallLoweringInfo::Callee, Callee, llvm::TargetLowering::CallLoweringInfo::CB, llvm::TargetLowering::CallLoweringInfo::Chain, llvm::MachineFrameInfo::CreateStackObject(), llvm::TargetLowering::CallLoweringInfo::DAG, llvm::TargetLowering::CallLoweringInfo::DL, E, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f32, llvm::MVT::f64, llvm::CCValAssign::Full, G, llvm::TargetLowering::CallLoweringInfo::getArgs(), llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMemcpy(), llvm::CCState::getNextStackOffset(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SparcSubtarget::getRegisterInfo(), llvm::SelectionDAG::getRegisterMask(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::DataLayout::getTypeAllocSize(), llvm::SDValue::getValue(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, hasReturnsTwiceAttr(), llvm::MVT::i32, llvm::TargetLowering::CallLoweringInfo::Ins, llvm::ISD::INSERT_VECTOR_ELT, llvm::TargetLowering::isPositionIndependent(), llvm::TargetLowering::CallLoweringInfo::IsTailCall, llvm::TargetLowering::CallLoweringInfo::IsVarArg, llvm_unreachable, Offset, llvm::MVT::Other, llvm::TargetLowering::CallLoweringInfo::Outs, llvm::TargetLowering::CallLoweringInfo::OutVals, llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, Size, toCallerWindow(), llvm::ISD::TokenFactor, TRI, llvm::ISD::UNDEF, llvm::MVT::v2i32, llvm::SparcMCExpr::VK_Sparc_WDISP30, llvm::SparcMCExpr::VK_Sparc_WPLT30, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
Referenced by LowerCall().
LowerCall_64()
SDValue SparcTargetLowering::LowerCall_64 (TargetLowering::CallLoweringInfo & CLI, SmallVectorImpl< SDValue > & InVals) const
Definition at line 1092 of file SparcISelLowering.cpp.
References llvm::ISD::ADD, llvm::CCValAssign::AExt, llvm::alignTo(), llvm::CCState::AnalyzeCallOperands(), llvm::ISD::ANY_EXTEND, Arg, assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, llvm::SPISD::CALL, llvm::TargetLowering::CallLoweringInfo::CallConv, llvm::TargetLowering::CallLoweringInfo::Callee, Callee, llvm::TargetLowering::CallLoweringInfo::CB, llvm::TargetLowering::CallLoweringInfo::Chain, llvm::ISD::CopyFromReg, llvm::TargetLowering::CallLoweringInfo::DAG, llvm::TargetLowering::CallLoweringInfo::DL, DL, E, llvm::MVT::f128, llvm::MVT::f32, fixupVariableFloatArgs(), llvm::CCValAssign::Full, G, llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::CCState::getNextStackOffset(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SparcSubtarget::getRegisterInfo(), llvm::SelectionDAG::getRegisterMask(), llvm::SparcSubtarget::getStackPointerBias(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SDValue::getValue(), llvm::SelectionDAG::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, hasReturnsTwiceAttr(), llvm::MVT::i128, llvm::MVT::i32, llvm::MVT::i64, llvm::TargetLowering::CallLoweringInfo::Ins, llvm::TargetLowering::isPositionIndependent(), llvm::TargetLowering::CallLoweringInfo::IsTailCall, llvm::TargetLowering::CallLoweringInfo::IsVarArg, llvm_unreachable, Offset, llvm::ISD::OR, llvm::MVT::Other, llvm::TargetLowering::CallLoweringInfo::Outs, llvm::TargetLowering::CallLoweringInfo::OutVals, llvm::CCValAssign::SExt, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SRL, toCallerWindow(), llvm::ISD::TokenFactor, TRI, llvm::ISD::TRUNCATE, llvm::SparcMCExpr::VK_Sparc_WDISP30, llvm::SparcMCExpr::VK_Sparc_WPLT30, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
Referenced by LowerCall().
LowerConstantPool()
SDValue SparcTargetLowering::LowerConstantPool (SDValue Op, SelectionDAG & DAG) const
Definition at line 2014 of file SparcISelLowering.cpp.
References makeAddress().
Referenced by LowerOperation().
LowerF128_LibCallArg()
SDValue SparcTargetLowering::LowerF128_LibCallArg (SDValue Chain, ArgListTy & Args, SDValue Arg, const SDLoc & DL, SelectionDAG & DAG) const
Definition at line 2129 of file SparcISelLowering.cpp.
References Align, Arg, llvm::MachineFrameInfo::CreateStackObject(), DL, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getStore(), llvm::EVT::getTypeForEVT(), llvm::PointerType::getUnqual(), and llvm::TargetLoweringBase::ArgListEntry::Node.
Referenced by LowerF128Compare(), and LowerF128Op().
LowerF128Compare()
SDValue SparcTargetLowering::LowerF128Compare (SDValue LHS, SDValue RHS, unsigned & SPCC, const SDLoc & DL, SelectionDAG & DAG) const
Definition at line 2208 of file SparcISelLowering.cpp.
References llvm::ISD::AND, llvm::CallingConv::C, Callee, llvm::SPISD::CMPICC, DL, llvm::SPCC::FCC_E, llvm::SPCC::FCC_G, llvm::SPCC::FCC_GE, llvm::SPCC::FCC_L, llvm::SPCC::FCC_LE, llvm::SPCC::FCC_LG, llvm::SPCC::FCC_NE, llvm::SPCC::FCC_O, llvm::SPCC::FCC_U, llvm::SPCC::FCC_UE, llvm::SPCC::FCC_UG, llvm::SPCC::FCC_UGE, llvm::SPCC::FCC_UL, llvm::SPCC::FCC_ULE, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getExternalSymbol(), llvm::Type::getInt32Ty(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::MVT::Glue, llvm::SPCC::ICC_E, llvm::SPCC::ICC_G, llvm::SPCC::ICC_NE, llvm::SparcSubtarget::is64Bit(), is64Bit(), llvm::TargetLoweringBase::LibCall, llvm_unreachable, llvm::TargetLowering::LowerCallTo(), LowerF128_LibCallArg(), RetTy, llvm::TargetLowering::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setChain(), and llvm::TargetLowering::CallLoweringInfo::setDebugLoc().
Referenced by LowerBR_CC(), and LowerSELECT_CC().
LowerF128Op()
SDValue SparcTargetLowering::LowerF128Op (SDValue Op, SelectionDAG & DAG, const char * LibFuncName, unsigned numArgs) const
Definition at line 2156 of file SparcISelLowering.cpp.
References Align, assert(), llvm::CallingConv::C, Callee, llvm::MachineFrameInfo::CreateStackObject(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getExternalSymbol(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::TargetLoweringBase::getPointerTy(), llvm::PointerType::getUnqual(), llvm::Type::getVoidTy(), llvm::SparcSubtarget::is64Bit(), llvm::TargetLowering::LowerCallTo(), LowerF128_LibCallArg(), RetTy, llvm::TargetLowering::CallLoweringInfo::setCallee(), llvm::TargetLowering::CallLoweringInfo::setChain(), and llvm::TargetLowering::CallLoweringInfo::setDebugLoc().
Referenced by LowerF128_FPEXTEND(), LowerF128_FPROUND(), LowerFP_TO_SINT(), LowerFP_TO_UINT(), LowerOperation(), LowerSINT_TO_FP(), LowerUINT_TO_FP(), and ReplaceNodeResults().
LowerFormalArguments()
SDValue SparcTargetLowering::LowerFormalArguments (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::InputArg > & , const SDLoc & , SelectionDAG & , SmallVectorImpl< SDValue > &) const override virtual
This hook must be implemented to lower the incoming (formal) arguments, described by the Ins array, into the specified DAG.
The implementation should fill in the InVals array with legal-type argument values, and return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 367 of file SparcISelLowering.cpp.
References DL, llvm::SparcSubtarget::is64Bit(), LowerFormalArguments_32(), and LowerFormalArguments_64().
LowerFormalArguments_32()
SDValue SparcTargetLowering::LowerFormalArguments_32 (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > & Ins, const SDLoc & dl, SelectionDAG & DAG, SmallVectorImpl< SDValue > & InVals) const
LowerFormalArguments32 - V8 uses a very simple ABI, where all values are passed in either one or two GPRs, including FP values.
TODO: we should pass FP values in FP registers for fastcc functions.
Definition at line 381 of file SparcISelLowering.cpp.
References llvm::MachineFunction::addLiveIn(), llvm::MachineRegisterInfo::addLiveIn(), llvm::CCState::AnalyzeFormalArguments(), Arg, assert(), llvm::ISD::AssertSext, llvm::ISD::BITCAST, llvm::ISD::BUILD_PAIR, llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::CCState::getFirstUnallocated(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::CCState::getNextStackOffset(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineFunction::getRegInfo(), llvm::SelectionDAG::getRoot(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getValueType(), llvm::Function::hasStructRetAttr(), llvm::MVT::i32, llvm::MVT::i64, llvm::DataLayout::isLittleEndian(), llvm_unreachable, Offset, llvm::MVT::Other, Reg, llvm::report_fatal_error(), llvm::SparcMachineFunctionInfo::setVarArgsFrameOffset(), std::swap(), llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, and llvm::MVT::v2i32.
Referenced by LowerFormalArguments().
LowerFormalArguments_64()
SDValue SparcTargetLowering::LowerFormalArguments_64 (SDValue Chain, CallingConv::ID CallConv, bool isVarArg, const SmallVectorImpl< ISD::InputArg > & Ins, const SDLoc & dl, SelectionDAG & DAG, SmallVectorImpl< SDValue > & InVals) const
Definition at line 576 of file SparcISelLowering.cpp.
References llvm::MachineFunction::addLiveIn(), llvm::CCState::AnalyzeFormalArguments(), Arg, assert(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::MachineFrameInfo::CreateFixedObject(), DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::MachineFunction::getDataLayout(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::CCState::getNextStackOffset(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getRegClassFor(), llvm::SparcSubtarget::getStackPointerBias(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getValueType(), llvm::MVT::i32, llvm::MVT::i64, Offset, llvm::MVT::Other, llvm::SparcMachineFunctionInfo::setVarArgsFrameOffset(), llvm::CCValAssign::SExt, llvm::ISD::SRL, llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, and llvm::CCValAssign::ZExt.
Referenced by LowerFormalArguments().
LowerGlobalAddress()
SDValue SparcTargetLowering::LowerGlobalAddress (SDValue Op, SelectionDAG & DAG) const
Definition at line 2009 of file SparcISelLowering.cpp.
References makeAddress().
Referenced by LowerOperation().
LowerGlobalTLSAddress()
SDValue SparcTargetLowering::LowerGlobalTLSAddress (SDValue Op, SelectionDAG & DAG) const
Definition at line 2024 of file SparcISelLowering.cpp.
References llvm::ISD::ADD, assert(), llvm::sampleprof::Base, llvm::CallingConv::C, Callee, DL, llvm::TLSModel::GeneralDynamic, llvm::SparcRegisterInfo::getCallPreservedMask(), llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SparcSubtarget::getRegisterInfo(), llvm::SelectionDAG::getRegisterMask(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::TargetLoweringBase::getTargetMachine(), llvm::TargetMachine::getTLSModel(), llvm::SDValue::getValue(), llvm::SelectionDAG::getVTList(), llvm::SPISD::GLOBAL_BASE_REG, llvm::MVT::Glue, llvm::SPISD::Hi, llvm::MVT::i64, llvm::TLSModel::InitialExec, llvm::SPISD::Lo, llvm::TLSModel::LocalDynamic, llvm::TLSModel::LocalExec, llvm::TargetLowering::LowerToTLSEmulatedModel(), makeHiLoPair(), Offset, llvm::MVT::Other, llvm::MachineFrameInfo::setHasCalls(), llvm::SPISD::TLS_ADD, llvm::SPISD::TLS_CALL, llvm::SPISD::TLS_LD, llvm::TargetMachine::useEmulatedTLS(), llvm::SparcMCExpr::VK_Sparc_TLS_GD_ADD, llvm::SparcMCExpr::VK_Sparc_TLS_GD_CALL, llvm::SparcMCExpr::VK_Sparc_TLS_GD_HI22, llvm::SparcMCExpr::VK_Sparc_TLS_GD_LO10, llvm::SparcMCExpr::VK_Sparc_TLS_IE_ADD, llvm::SparcMCExpr::VK_Sparc_TLS_IE_HI22, llvm::SparcMCExpr::VK_Sparc_TLS_IE_LD, llvm::SparcMCExpr::VK_Sparc_TLS_IE_LDX, llvm::SparcMCExpr::VK_Sparc_TLS_IE_LO10, llvm::SparcMCExpr::VK_Sparc_TLS_LDM_ADD, llvm::SparcMCExpr::VK_Sparc_TLS_LDM_CALL, llvm::SparcMCExpr::VK_Sparc_TLS_LDM_HI22, llvm::SparcMCExpr::VK_Sparc_TLS_LDM_LO10, llvm::SparcMCExpr::VK_Sparc_TLS_LDO_ADD, llvm::SparcMCExpr::VK_Sparc_TLS_LDO_HIX22, llvm::SparcMCExpr::VK_Sparc_TLS_LDO_LOX10, llvm::SparcMCExpr::VK_Sparc_TLS_LE_HIX22, llvm::SparcMCExpr::VK_Sparc_TLS_LE_LOX10, withTargetFlags(), and llvm::ISD::XOR.
Referenced by LowerOperation().
LowerINTRINSIC_WO_CHAIN()
SDValue SparcTargetLowering::LowerINTRINSIC_WO_CHAIN (SDValue Op, SelectionDAG & DAG) const
Definition at line 3000 of file SparcISelLowering.cpp.
References llvm::SelectionDAG::getDataLayout(), llvm::TargetLoweringBase::getPointerTy(), and llvm::SelectionDAG::getRegister().
Referenced by LowerOperation().
LowerOperation()
SDValue SparcTargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const override virtual
This callback is invoked for operations that are unsupported by the target, which are registered to use 'custom' lowering, and whose defined values are all legal.
If the target has no operations that require custom lowering, it need not implement this. The default implementation of this aborts.
Reimplemented from llvm::TargetLowering.
Definition at line 3013 of file SparcISelLowering.cpp.
References llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_STORE, llvm::ISD::BlockAddress, llvm::ISD::BR_CC, llvm::ISD::ConstantPool, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FRAMEADDR, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::TargetLoweringBase::getLibcallName(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::SparcSubtarget::hasHardQuad(), llvm::ISD::INTRINSIC_WO_CHAIN, llvm::SparcSubtarget::isV9(), llvm_unreachable, llvm::ISD::LOAD, LowerADDC_ADDE_SUBC_SUBE(), LowerATOMIC_LOAD_STORE(), LowerBlockAddress(), LowerBR_CC(), LowerConstantPool(), LowerDYNAMIC_STACKALLOC(), LowerF128_FPEXTEND(), LowerF128_FPROUND(), LowerF128Op(), LowerFNEGorFABS(), LowerFP_TO_SINT(), LowerFP_TO_UINT(), LowerFRAMEADDR(), LowerGlobalAddress(), LowerGlobalTLSAddress(), LowerINTRINSIC_WO_CHAIN(), LowerLOAD(), LowerRETURNADDR(), LowerSELECT_CC(), LowerSINT_TO_FP(), LowerSTORE(), LowerUINT_TO_FP(), LowerUMULO_SMULO(), LowerVAARG(), LowerVASTART(), llvm::ISD::RETURNADDR, llvm::ISD::SELECT_CC, llvm::ISD::SINT_TO_FP, llvm::ISD::SMULO, llvm::ISD::STORE, llvm::ISD::SUBC, llvm::ISD::SUBE, llvm::ISD::UINT_TO_FP, llvm::ISD::UMULO, llvm::ISD::VAARG, and llvm::ISD::VASTART.
LowerReturn()
SDValue SparcTargetLowering::LowerReturn (SDValue , CallingConv::ID , bool , const SmallVectorImpl< ISD::OutputArg > & , const SmallVectorImpl< SDValue > & , const SDLoc & , SelectionDAG &) const override virtual
This hook must be implemented to lower outgoing return values, described by the Outs array, into the specified DAG.
The implementation should return the resulting token chain value.
Reimplemented from llvm::TargetLowering.
Definition at line 195 of file SparcISelLowering.cpp.
References DL, llvm::SparcSubtarget::is64Bit(), LowerReturn_32(), and LowerReturn_64().
LowerReturn_32()
SDValue SparcTargetLowering::LowerReturn_32 (SDValue Chain, CallingConv::ID CallConv, bool IsVarArg, const SmallVectorImpl< ISD::OutputArg > & Outs, const SmallVectorImpl< SDValue > & OutVals, const SDLoc & DL, SelectionDAG & DAG) const
Definition at line 206 of file SparcISelLowering.cpp.
References llvm::CCState::AnalyzeReturn(), Arg, assert(), DL, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::SDValue::getValue(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::Function::hasStructRetAttr(), llvm::MVT::i32, llvm_unreachable, llvm::MVT::Other, llvm::SPISD::RET_FLAG, and llvm::MVT::v2i32.
Referenced by LowerReturn().
LowerReturn_64()
SDValue SparcTargetLowering::LowerReturn_64 (SDValue Chain, CallingConv::ID CallConv, bool IsVarArg, const SmallVectorImpl< ISD::OutputArg > & Outs, const SmallVectorImpl< SDValue > & OutVals, const SDLoc & DL, SelectionDAG & DAG) const
Definition at line 291 of file SparcISelLowering.cpp.
References llvm::CCValAssign::AExt, llvm::CCState::AnalyzeReturn(), llvm::ISD::ANY_EXTEND, assert(), DL, llvm::CCValAssign::Full, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getRegister(), llvm::SDValue::getValue(), llvm::MVT::i32, llvm::MVT::i64, llvm_unreachable, llvm::ISD::OR, llvm::MVT::Other, llvm::SPISD::RET_FLAG, llvm::CCValAssign::SExt, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
Referenced by LowerReturn().
makeAddress()
SDValue SparcTargetLowering::makeAddress (SDValue Op, SelectionDAG & DAG) const
Definition at line 1950 of file SparcISelLowering.cpp.
References llvm::ISD::ADD, DL, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachinePointerInfo::getGOT(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::GlobalValue::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getTargetMachine(), llvm::SPISD::GLOBAL_BASE_REG, llvm::MVT::i32, Idx, llvm::TargetLowering::isPositionIndependent(), llvm::CodeModel::Large, llvm_unreachable, llvm::SPISD::Lo, makeHiLoPair(), llvm::CodeModel::Medium, llvm::MachineFrameInfo::setHasCalls(), llvm::ISD::SHL, llvm::CodeModel::Small, llvm::PICLevel::SmallPIC, llvm::SparcMCExpr::VK_Sparc_GOT10, llvm::SparcMCExpr::VK_Sparc_GOT13, llvm::SparcMCExpr::VK_Sparc_GOT22, llvm::SparcMCExpr::VK_Sparc_H44, llvm::SparcMCExpr::VK_Sparc_HH, llvm::SparcMCExpr::VK_Sparc_HI, llvm::SparcMCExpr::VK_Sparc_HM, llvm::SparcMCExpr::VK_Sparc_L44, llvm::SparcMCExpr::VK_Sparc_LO, llvm::SparcMCExpr::VK_Sparc_M44, and withTargetFlags().
Referenced by LowerBlockAddress(), LowerConstantPool(), and LowerGlobalAddress().
makeHiLoPair()
SDValue SparcTargetLowering::makeHiLoPair (SDValue Op, unsigned HiTF, unsigned LoTF, SelectionDAG & DAG) const
Definition at line 1938 of file SparcISelLowering.cpp.
References llvm::ISD::ADD, DL, llvm::SelectionDAG::getNode(), llvm::SPISD::Hi, llvm::SPISD::Lo, and withTargetFlags().
Referenced by LowerGlobalTLSAddress(), and makeAddress().
PerformBITCASTCombine()
SDValue SparcTargetLowering::PerformBITCASTCombine (SDNode * N, DAGCombinerInfo & DCI) const
Definition at line 3086 of file SparcISelLowering.cpp.
References bitcastConstantFPToInt(), llvm::MVT::f64, llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), N, and llvm::MVT::v2i32.
Referenced by PerformDAGCombine().
PerformDAGCombine()
SDValue SparcTargetLowering::PerformDAGCombine (SDNode * N, DAGCombinerInfo & DCI) const override virtual
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
The semantics are as follows: Return Value: SDValue.Val == 0 - No change was made SDValue.Val == N - N was replaced, is dead, and is already handled. otherwise - N should be replaced by the returned Operand.
In addition, methods provided by DAGCombinerInfo may be used to perform more complex transformations.
Reimplemented from llvm::TargetLowering.
Definition at line 3098 of file SparcISelLowering.cpp.
References llvm::ISD::BITCAST, N, and PerformBITCASTCombine().
ReplaceNodeResults()
void SparcTargetLowering::ReplaceNodeResults (SDNode * , SmallVectorImpl< SDValue > & , SelectionDAG &) const override virtual
This callback is invoked when a node result type is illegal for the target, and the operation was registered to use 'custom' lowering for that result type.
The target places new result values for the node in Results (their number and types must exactly match those of the original return values of the node), or leaves Results empty, which indicates that the node is not to be custom lowered after all.
If the target has no operations that require custom lowering, it need not implement this. The default implementation aborts.
Reimplemented from llvm::TargetLowering.
Definition at line 3345 of file SparcISelLowering.cpp.
References assert(), llvm::ISD::BITCAST, llvm::ISD::BUILD_PAIR, llvm::MVT::f128, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getExtLoad(), llvm::TargetLoweringBase::getLibcallName(), llvm::SelectionDAG::getNode(), llvm::SparcSubtarget::hasLeonCycleCounter(), llvm::MVT::i32, llvm::MVT::i64, llvm_unreachable, llvm::ISD::LOAD, LowerF128Op(), N, llvm::ISD::READCYCLECOUNTER, Results, llvm::ISD::SINT_TO_FP, llvm::ISD::UINT_TO_FP, and llvm::MVT::v2i32.
shouldExpandAtomicRMWInIR()
TargetLowering::AtomicExpansionKind SparcTargetLowering::shouldExpandAtomicRMWInIR (AtomicRMWInst * RMW) const override virtual
Returns how the IR-level AtomicExpand pass should expand the given AtomicRMW, if at all.
Default is to never expand.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1354 of file SparcISelLowering.cpp.
References llvm::TargetLoweringBase::CmpXChg, llvm::AtomicRMWInst::getOperation(), llvm::Type::getPrimitiveSizeInBits(), llvm::Value::getType(), llvm::TargetLoweringBase::None, and llvm::AtomicRMWInst::Xchg.
shouldInsertFencesForAtomic()
bool llvm::SparcTargetLowering::shouldInsertFencesForAtomic (const Instruction * I) const inline override virtual
Whether AtomicExpandPass should automatically insert fences and reduce ordering for this atomic.
This should be true for most architectures with weak memory ordering. Defaults to false.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 191 of file SparcISelLowering.h.
ShouldShrinkFPConstant()
bool llvm::SparcTargetLowering::ShouldShrinkFPConstant (EVT) const inline override virtual
If true, then instruction selection should seek to shrink the FP constant of the specified type to a smaller type in order to save space and / or reduce runtime.
Reimplemented from llvm::TargetLoweringBase.
Definition at line 185 of file SparcISelLowering.h.
References llvm::MVT::f128.
useLoadStackGuardNode()
bool SparcTargetLowering::useLoadStackGuardNode () const override virtual
Override to support customized stack guard loading.
Reimplemented from llvm::TargetLowering.
Definition at line 3421 of file SparcISelLowering.cpp.
References llvm::SparcSubtarget::isTargetLinux(), and llvm::TargetLowering::useLoadStackGuardNode().
useSoftFloat()
bool SparcTargetLowering::useSoftFloat () const override virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 1825 of file SparcISelLowering.cpp.
References llvm::SparcSubtarget::useSoftFloat().
withTargetFlags()
SDValue SparcTargetLowering::withTargetFlags (SDValue Op, unsigned TF, SelectionDAG & DAG) const
Definition at line 1911 of file SparcISelLowering.cpp.
References llvm::SelectionDAG::getTargetBlockAddress(), llvm::SelectionDAG::getTargetConstantPool(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::SelectionDAG::getTargetGlobalAddress(), and llvm_unreachable.
Referenced by LowerGlobalTLSAddress(), makeAddress(), and makeHiLoPair().
The documentation for this class was generated from the following files:
lib/Target/Sparc/SparcISelLowering.h
lib/Target/Sparc/SparcISelLowering.cpp