LLVM: llvm::LazyCallGraph::EdgeSequence Class Reference
llvm::LazyCallGraph::EdgeSequence Class Reference
The edge sequence object.
#include "llvm/Analysis/LazyCallGraph.h"
Classes
class call_iterator
An iterator over specifically call edges.
class iterator
An iterator used for the edges to both entry nodes and child nodes.
Public Member Functions
iterator begin ()
iterator end ()
Edge & operator[] (Node &N)
Edge * lookup (Node &N)
call_iterator call_begin ()
call_iterator call_end ()
iterator_range< call_iterator > calls ()
bool empty ()
Friends
class LazyCallGraph
class LazyCallGraph::Node
class LazyCallGraph::RefSCC
Detailed Description
The edge sequence object.
This typically exists entirely within the node but is exposed as a separate type because a node doesn't initially have edges. An explicit population step is required to produce this sequence at first and it is then cached in the node. It is also used to represent edges entering the graph from outside the module to model the graph's roots.
The sequence itself both iterable and indexable. The indexes remain stable even as the sequence mutates (including removal).
Definition at line 185 of file LazyCallGraph.h.
Member Function Documentation
begin()
iterator llvm::LazyCallGraph::EdgeSequence::begin () inline
Definition at line 257 of file LazyCallGraph.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::LazyCallGraph::begin().
call_begin()
call_iterator llvm::LazyCallGraph::EdgeSequence::call_begin () inline
Definition at line 275 of file LazyCallGraph.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by calls().
call_end()
call_iterator llvm::LazyCallGraph::EdgeSequence::call_end () inline
Definition at line 278 of file LazyCallGraph.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by calls().
calls()
iterator_range< call_iterator > llvm::LazyCallGraph::EdgeSequence::calls () inline
Definition at line 280 of file LazyCallGraph.h.
References call_begin(), call_end(), and llvm::make_range().
empty()
bool llvm::LazyCallGraph::EdgeSequence::empty () inline
Definition at line 284 of file LazyCallGraph.h.
References E.
Referenced by llvm::LazyCallGraph::buildRefSCCs(), llvm::LazyCallGraph::postorder_ref_scc_begin(), and llvm::LazyCallGraph::postorder_ref_scc_end().
end()
iterator llvm::LazyCallGraph::EdgeSequence::end () inline
Definition at line 258 of file LazyCallGraph.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::LazyCallGraph::end().
lookup()
Edge * llvm::LazyCallGraph::EdgeSequence::lookup (Node & N) inline
Definition at line 267 of file LazyCallGraph.h.
References E, and N.
operator[]()
Edge & llvm::LazyCallGraph::EdgeSequence::operator[] (Node & N) inline
Definition at line 260 of file LazyCallGraph.h.
References assert(), E, and N.
Friends And Related Symbol Documentation
LazyCallGraph
friend class LazyCallGraph friend
Definition at line 186 of file LazyCallGraph.h.
LazyCallGraph::Node
friend class LazyCallGraph::Node friend
Definition at line 187 of file LazyCallGraph.h.
LazyCallGraph::RefSCC
friend class LazyCallGraph::RefSCC friend
Definition at line 188 of file LazyCallGraph.h.
The documentation for this class was generated from the following files:
include/llvm/Analysis/LazyCallGraph.h
lib/Analysis/LazyCallGraph.cpp