LLVM: llvm::gsym::AddressRanges Class Reference
llvm::gsym::AddressRanges Class Reference
The AddressRanges class helps normalize address range collections.
#include "llvm/DebugInfo/GSYM/Range.h"
Public Member Functions
void clear ()
bool empty () const
bool contains (uint64_t Addr) const
bool contains (AddressRange Range) const
Optional< AddressRange > getRangeThatContains (uint64_t Addr) const
void insert (AddressRange Range)
size_t size () const
bool operator== (const AddressRanges &RHS) const
const AddressRange & operator[] (size_t i) const
Collection::const_iterator begin () const
Collection::const_iterator end () const
void decode (DataExtractor &Data, uint64_t BaseAddr, uint64_t &Offset)
Address ranges are decoded and encoded to be relative to a base address.
void encode (FileWriter &O, uint64_t BaseAddr) const
Static Public Member Functions
static uint64_t skip (DataExtractor &Data, uint64_t &Offset)
Skip an address range object in the specified data a the specified offset.
Protected Types
using Collection = std::vector<AddressRange>
Protected Attributes
Collection Ranges
Detailed Description
The AddressRanges class helps normalize address range collections.
This class keeps a sorted vector of AddressRange objects and can perform insertions and searches efficiently. The address ranges are always sorted and never contain any invalid or empty address ranges. This allows us to emit address ranges into the GSYM file efficiently. Intersecting address ranges are combined during insertion so that we can emit the most compact representation for address ranges when writing to disk.
Definition at line 84 of file Range.h.
Member Typedef Documentation
Collection
using llvm::gsym::AddressRanges::Collection = std::vector<AddressRange> protected
Definition at line 86 of file Range.h.
Member Function Documentation
begin()
Collection::const_iterator llvm::gsym::AddressRanges::begin () const inline
Definition at line 103 of file Range.h.
References Ranges.
clear()
void llvm::gsym::AddressRanges::clear () inline
Definition at line 89 of file Range.h.
References Ranges.
Referenced by llvm::gsym::InlineInfo::clear(), and decode().
contains() [1/2]
bool AddressRanges::contains (AddressRange Range) const
Definition at line 45 of file Range.cpp.
References llvm::gsym::AddressRange::End, Ranges, and llvm::gsym::AddressRange::size().
contains() [2/2]
bool AddressRanges::contains (uint64_t Addr) const
Definition at line 38 of file Range.cpp.
References Addr, and Ranges.
Referenced by llvm::gsym::InlineInfo::encode(), getInlineStackHelper(), and llvm::gsym::GsymCreator::hasFunctionInfoForAddress().
decode()
void AddressRanges::decode (DataExtractor & Data, uint64_t BaseAddr, uint64_t & Offset)
Address ranges are decoded and encoded to be relative to a base address.
See the AddressRange comment for the encode and decode methods for full details.
Definition at line 103 of file Range.cpp.
References clear(), llvm::Data, Offset, and Ranges.
empty()
bool llvm::gsym::AddressRanges::empty () const inline
Definition at line 90 of file Range.h.
References Ranges.
Referenced by llvm::gsym::InlineInfo::isValid(), and parseInlineInfo().
encode()
void AddressRanges::encode (FileWriter & O, uint64_t BaseAddr) const
Definition at line 95 of file Range.cpp.
References Ranges.
Referenced by llvm::gsym::InlineInfo::encode().
end()
Collection::const_iterator llvm::gsym::AddressRanges::end () const inline
Definition at line 104 of file Range.h.
References Ranges.
getRangeThatContains()
Optional< AddressRange > AddressRanges::getRangeThatContains (uint64_t Addr) const
Definition at line 57 of file Range.cpp.
References Addr, llvm::None, and Ranges.
insert()
void AddressRanges::insert (AddressRange Range)
Definition at line 20 of file Range.cpp.
References llvm::gsym::AddressRange::End, Ranges, llvm::gsym::AddressRange::size(), llvm::gsym::AddressRange::Start, and llvm::upper_bound().
Referenced by llvm::gsym::GsymCreator::addFunctionInfo(), and parseInlineInfo().
operator==()
bool llvm::gsym::AddressRanges::operator== (const AddressRanges & RHS) const inline
Definition at line 96 of file Range.h.
References Ranges.
operator[]()
const AddressRange & llvm::gsym::AddressRanges::operator[] (size_t i) const inline
Definition at line 99 of file Range.h.
References assert(), and Ranges.
size()
size_t llvm::gsym::AddressRanges::size () const inline
Definition at line 95 of file Range.h.
References Ranges.
Referenced by llvm::gsym::operator<<().
skip()
uint64_t AddressRanges::skip (DataExtractor & Data, uint64_t & Offset) static
Skip an address range object in the specified data a the specified offset.
Parameters
Data The binary stream to read the data from.
Offset The byte offset within Data.
Returns
The number of address ranges that were skipped.
Definition at line 119 of file Range.cpp.
References llvm::Data, I, Offset, and llvm::gsym::AddressRange::skip().
Referenced by skip().
Member Data Documentation
Ranges
Collection llvm::gsym::AddressRanges::Ranges protected
Definition at line 87 of file Range.h.
Referenced by begin(), clear(), contains(), contains(), decode(), empty(), encode(), end(), getRangeThatContains(), insert(), operator==(), operator[](), and size().
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/GSYM/Range.h
lib/DebugInfo/GSYM/Range.cpp