LLVM: llvm::IROutlinerPass Class Reference
llvm::IROutlinerPass Class Reference
Pass to outline similar regions.
#include "llvm/Transforms/IPO/IROutliner.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &AM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< IROutlinerPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Pass to outline similar regions.
Definition at line 351 of file IROutliner.h.
Member Function Documentation
run()
PreservedAnalyses IROutlinerPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 1807 of file IROutliner.cpp.
References llvm::PreservedAnalyses::all(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), llvm::PreservedAnalyses::none(), and llvm::IROutliner::run().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/IROutliner.h
lib/Transforms/IPO/IROutliner.cpp