LLVM: llvm::orc::shared::SerializationTraits< ChannelT, std::string, StringRef, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > > Class Template Reference
llvm::orc::shared::SerializationTraits< ChannelT, std::string, StringRef, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > > Class Template Reference
#include "llvm/ExecutionEngine/Orc/Shared/RawByteChannel.h"
Static Public Member Functions
static Error serialize (RawByteChannel &C, StringRef S)
Serialization channel serialization for std::strings.
Detailed Description
template<typename ChannelT>
class llvm::orc::shared::SerializationTraits< ChannelT, std::string, StringRef, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >
Definition at line 133 of file RawByteChannel.h.
Member Function Documentation
serialize()
template<typename ChannelT > static Error llvm::orc::shared::SerializationTraits< ChannelT, std::string, StringRef, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::serialize (RawByteChannel & C, StringRef S) inline static
Serialization channel serialization for std::strings.
Definition at line 138 of file RawByteChannel.h.
References C, llvm::StringRef::data(), llvm::orc::shared::serializeSeq(), and llvm::StringRef::size().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/RawByteChannel.h