LLVM: llvm::AMDGPU::HSAMD::MetadataStreamerV3 Class Reference
llvm::AMDGPU::HSAMD::MetadataStreamerV3 Class Reference
#include "Target/AMDGPU/AMDGPUHSAMetadataStreamer.h"
Public Member Functions
MetadataStreamerV3 ()=default
~MetadataStreamerV3 ()=default
bool emitTo (AMDGPUTargetStreamer &TargetStreamer) override
void begin (const Module &Mod, const IsaInfo::AMDGPUTargetID &TargetID) override
void end () override
void emitKernel (const MachineFunction &MF, const SIProgramInfo &ProgramInfo) override
Public Member Functions inherited from llvm::AMDGPU::HSAMD::MetadataStreamer
virtual ~MetadataStreamer ()
Protected Member Functions
void dump (StringRef HSAMetadataString) const
void verify (StringRef HSAMetadataString) const
Optional< StringRef > getAccessQualifier (StringRef AccQual) const
Optional< StringRef > getAddressSpaceQualifier (unsigned AddressSpace) const
StringRef getValueKind (Type *Ty, StringRef TypeQual, StringRef BaseTypeName) const
std::string getTypeName (Type *Ty, bool Signed) const
msgpack::ArrayDocNode getWorkGroupDimensions (MDNode *Node) const
msgpack::MapDocNode getHSAKernelProps (const MachineFunction &MF, const SIProgramInfo &ProgramInfo) const
void emitVersion ()
void emitPrintf (const Module &Mod)
void emitKernelLanguage (const Function &Func, msgpack::MapDocNode Kern)
void emitKernelAttrs (const Function &Func, msgpack::MapDocNode Kern)
void emitKernelArgs (const Function &Func, msgpack::MapDocNode Kern)
void emitKernelArg (const Argument &Arg, unsigned &Offset, msgpack::ArrayDocNode Args)
void emitKernelArg (const DataLayout &DL, Type *Ty, Align Alignment, StringRef ValueKind, unsigned &Offset, msgpack::ArrayDocNode Args, MaybeAlign PointeeAlign=None, StringRef Name="", StringRef TypeName="", StringRef BaseTypeName="", StringRef AccQual="", StringRef TypeQual="")
void emitHiddenKernelArgs (const Function &Func, unsigned &Offset, msgpack::ArrayDocNode Args)
msgpack::DocNode & getRootMetadata (StringRef Key)
msgpack::DocNode & getHSAMetadataRoot ()
Protected Attributes
std::unique_ptr< msgpack::Document > HSAMetadataDoc
Detailed Description
Definition at line 54 of file AMDGPUHSAMetadataStreamer.h.
Constructor & Destructor Documentation
MetadataStreamerV3()
llvm::AMDGPU::HSAMD::MetadataStreamerV3::MetadataStreamerV3 () default
~MetadataStreamerV3()
llvm::AMDGPU::HSAMD::MetadataStreamerV3::~MetadataStreamerV3 () default
Member Function Documentation
begin()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::begin (const Module & Mod, const IsaInfo::AMDGPUTargetID & TargetID) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Reimplemented in llvm::AMDGPU::HSAMD::MetadataStreamerV4.
Definition at line 885 of file AMDGPUHSAMetadataStreamer.cpp.
References emitPrintf(), emitVersion(), getRootMetadata(), HSAMetadataDoc, and llvm::Mod.
dump()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::dump (StringRef HSAMetadataString) const protected
Definition at line 480 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::errs().
Referenced by end().
emitHiddenKernelArgs()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitHiddenKernelArgs (const Function & Func, unsigned & Offset, msgpack::ArrayDocNode Args) protected
Definition at line 788 of file AMDGPUHSAMetadataStreamer.cpp.
References Align, assert(), DL, emitKernelArg(), llvm::Type::getInt64Ty(), llvm::Type::getInt8PtrTy(), llvm::AMDGPU::getIntegerAttribute(), llvm::AMDGPUAS::GLOBAL_ADDRESS, and Offset.
Referenced by emitKernelArgs().
emitKernel()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernel (const MachineFunction & MF, const SIProgramInfo & ProgramInfo) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 903 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::CallingConv::AMDGPU_KERNEL, assert(), emitKernelArgs(), emitKernelAttrs(), emitKernelLanguage(), llvm::msgpack::DocNode::getArray(), llvm::MachineFunction::getFunction(), getHSAKernelProps(), getRootMetadata(), and llvm::CallingConv::SPIR_KERNEL.
emitKernelArg() [1/2]
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernelArg (const Argument & Arg, unsigned & Offset, msgpack::ArrayDocNode Args) protected
Definition at line 682 of file AMDGPUHSAMetadataStreamer.cpp.
References Arg, DL, emitKernelArg(), getArgumentTypeAlign(), getValueKind(), llvm::AMDGPUAS::LOCAL_ADDRESS, Name, and Offset.
Referenced by emitHiddenKernelArgs(), emitKernelArg(), and emitKernelArgs().
emitKernelArg() [2/2]
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernelArg (const DataLayout & DL, Type * Ty, Align Alignment, StringRef ValueKind, unsigned & Offset, msgpack::ArrayDocNode Args, MaybeAlign PointeeAlign = None, StringRef Name = "", StringRef TypeName = "", StringRef BaseTypeName = "", StringRef AccQual = "", StringRef TypeQual = "") protected
Definition at line 743 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::alignTo(), Arg, DL, getAccessQualifier(), getAddressSpaceQualifier(), Name, Offset, and Size.
emitKernelArgs()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernelArgs (const Function & Func, msgpack::MapDocNode Kern) protected
Definition at line 670 of file AMDGPUHSAMetadataStreamer.cpp.
References Arg, emitHiddenKernelArgs(), emitKernelArg(), HSAMetadataDoc, and Offset.
Referenced by emitKernel().
emitKernelAttrs()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernelAttrs (const Function & Func, msgpack::MapDocNode Kern) protected
Definition at line 649 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::getTypeName(), and getWorkGroupDimensions().
Referenced by emitKernel().
emitKernelLanguage()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitKernelLanguage (const Function & Func, msgpack::MapDocNode Kern) protected
Definition at line 630 of file AMDGPUHSAMetadataStreamer.cpp.
Referenced by emitKernel().
emitPrintf()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitPrintf (const Module & Mod) protected
Definition at line 617 of file AMDGPUHSAMetadataStreamer.cpp.
References getRootMetadata(), HSAMetadataDoc, and llvm::Mod.
Referenced by begin(), and llvm::AMDGPU::HSAMD::MetadataStreamerV4::begin().
emitTo()
bool llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitTo (AMDGPUTargetStreamer & TargetStreamer) override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 881 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPUTargetStreamer::EmitHSAMetadata(), and HSAMetadataDoc.
emitVersion()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::emitVersion () protected
Definition at line 610 of file AMDGPUHSAMetadataStreamer.cpp.
References getRootMetadata(), HSAMetadataDoc, llvm::AMDGPU::HSAMD::VersionMajorV3, and llvm::AMDGPU::HSAMD::VersionMinorV3.
Referenced by begin().
end()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::end () override virtual
Implements llvm::AMDGPU::HSAMD::MetadataStreamer.
Definition at line 892 of file AMDGPUHSAMetadataStreamer.cpp.
References dump(), llvm::DumpHSAMetadata, HSAMetadataDoc, verify, and llvm::VerifyHSAMetadata.
getAccessQualifier()
Optional< StringRef > llvm::AMDGPU::HSAMD::MetadataStreamerV3::getAccessQualifier (StringRef AccQual) const protected
Definition at line 506 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPU::HSAMD::Default, and llvm::None.
Referenced by emitKernelArg().
getAddressSpaceQualifier()
Optional< StringRef > llvm::AMDGPU::HSAMD::MetadataStreamerV3::getAddressSpaceQualifier (unsigned AddressSpace) const protected
Definition at line 515 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPUAS::CONSTANT_ADDRESS, llvm::AMDGPUAS::FLAT_ADDRESS, llvm::AMDGPUAS::GLOBAL_ADDRESS, llvm::AMDGPUAS::LOCAL_ADDRESS, llvm::None, llvm::AMDGPUAS::PRIVATE_ADDRESS, and llvm::AMDGPUAS::REGION_ADDRESS.
Referenced by emitKernelArg().
getHSAKernelProps()
msgpack::MapDocNode llvm::AMDGPU::HSAMD::MetadataStreamerV3::getHSAKernelProps (const MachineFunction & MF, const SIProgramInfo & ProgramInfo) const protected
Definition at line 850 of file AMDGPUHSAMetadataStreamer.cpp.
References Align, F, llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::AMDGPUSubtarget::getKernArgSegmentSize(), llvm::MachineFunction::getSubtarget(), llvm::AMDGPUSubtarget::getWavefrontSize(), HSAMetadataDoc, and value.
Referenced by emitKernel().
getHSAMetadataRoot()
msgpack::DocNode & llvm::AMDGPU::HSAMD::MetadataStreamerV3::getHSAMetadataRoot () inline protected
Definition at line 104 of file AMDGPUHSAMetadataStreamer.h.
References HSAMetadataDoc.
getRootMetadata()
msgpack::DocNode & llvm::AMDGPU::HSAMD::MetadataStreamerV3::getRootMetadata (StringRef Key) inline protected
Definition at line 100 of file AMDGPUHSAMetadataStreamer.h.
References llvm::msgpack::DocNode::getMap(), and HSAMetadataDoc.
Referenced by begin(), llvm::AMDGPU::HSAMD::MetadataStreamerV4::begin(), emitKernel(), emitPrintf(), and emitVersion().
getTypeName()
std::string llvm::AMDGPU::HSAMD::MetadataStreamerV3::getTypeName (Type * Ty, bool Signed) const protected
Definition at line 561 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::BitWidth, llvm::Type::DoubleTyID, llvm::Type::FixedVectorTyID, llvm::Type::FloatTyID, llvm::getTypeName(), llvm::Type::HalfTyID, llvm::Type::IntegerTyID, and Signed.
getValueKind()
StringRef llvm::AMDGPU::HSAMD::MetadataStreamerV3::getValueKind (Type * Ty, StringRef TypeQual, StringRef BaseTypeName) const protected
Definition at line 534 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::AMDGPUAS::LOCAL_ADDRESS, and llvm::StringRef::npos.
Referenced by emitKernelArg().
getWorkGroupDimensions()
msgpack::ArrayDocNode llvm::AMDGPU::HSAMD::MetadataStreamerV3::getWorkGroupDimensions (MDNode * Node) const protected
Definition at line 599 of file AMDGPUHSAMetadataStreamer.cpp.
References HSAMetadataDoc.
Referenced by emitKernelAttrs().
verify()
void llvm::AMDGPU::HSAMD::MetadataStreamerV3::verify (StringRef HSAMetadataString) const protected
Definition at line 484 of file AMDGPUHSAMetadataStreamer.cpp.
References llvm::errs().
Member Data Documentation
HSAMetadataDoc
std::unique_ptr<msgpack::Document> llvm::AMDGPU::HSAMD::MetadataStreamerV3::HSAMetadataDoc protected
Initial value:
=
      std::make_unique<msgpack::Document>()
Definition at line 56 of file AMDGPUHSAMetadataStreamer.h.
Referenced by begin(), llvm::AMDGPU::HSAMD::MetadataStreamerV4::begin(), emitKernelArgs(), emitPrintf(), emitTo(), emitVersion(), end(), getHSAKernelProps(), getHSAMetadataRoot(), getRootMetadata(), and getWorkGroupDimensions().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.h
lib/Target/AMDGPU/AMDGPUHSAMetadataStreamer.cpp