LLVM: llvm::DebugInfoFinder Class Reference
llvm::DebugInfoFinder Class Reference
Utility to find all debug info in a module.
#include "llvm/IR/DebugInfo.h"
Public Types
using compile_unit_iterator
using subprogram_iterator = SmallVectorImpl<DISubprogram *>::const_iterator
using global_variable_expression_iterator
using type_iterator = SmallVectorImpl<DIType *>::const_iterator
using scope_iterator = SmallVectorImpl<DIScope *>::const_iterator
Public Member Functions
void processModule (const Module &M)
Process entire module and collect debug info anchors.
void processInstruction (const Module &M, const Instruction &I)
Process a single instruction and collect debug info anchors.
void processVariable (const Module &M, const DbgVariableIntrinsic &DVI)
Process DbgVariableIntrinsic.
void processLocation (const Module &M, const DILocation *Loc)
Process debug info location.
void processSubprogram (DISubprogram *SP)
Process subprogram.
void reset ()
Clear all lists.
iterator_range< compile_unit_iterator > compile_units () const
iterator_range< subprogram_iterator > subprograms () const
iterator_range< global_variable_expression_iterator > global_variables () const
iterator_range< type_iterator > types () const
iterator_range< scope_iterator > scopes () const
unsigned compile_unit_count () const
unsigned global_variable_count () const
unsigned subprogram_count () const
unsigned type_count () const
unsigned scope_count () const
Detailed Description
Utility to find all debug info in a module.
DebugInfoFinder tries to list all debug info MDNodes used in a module. To list debug info MDNodes used by an instruction, DebugInfoFinder uses processDeclare, processValue and processLocation to handle DbgDeclareInst, DbgValueInst and DbgLoc attached to instructions. processModule will go through all DICompileUnits in llvm.dbg.cu and list debug info MDNodes used by the CUs.
Definition at line 90 of file DebugInfo.h.
Member Typedef Documentation
compile_unit_iterator
using llvm::DebugInfoFinder::compile_unit_iterator
Initial value:
      SmallVectorImpl<DICompileUnit *>::const_iterator
Definition at line 121 of file DebugInfo.h.
global_variable_expression_iterator
using llvm::DebugInfoFinder::global_variable_expression_iterator
Initial value:
      SmallVectorImpl<DIGlobalVariableExpression *>::const_iterator
Definition at line 124 of file DebugInfo.h.
scope_iterator
using llvm::DebugInfoFinder::scope_iterator = SmallVectorImpl<DIScope *>::const_iterator
Definition at line 127 of file DebugInfo.h.
subprogram_iterator
using llvm::DebugInfoFinder::subprogram_iterator = SmallVectorImpl<DISubprogram *>::const_iterator
Definition at line 123 of file DebugInfo.h.
type_iterator
using llvm::DebugInfoFinder::type_iterator = SmallVectorImpl<DIType *>::const_iterator
Definition at line 126 of file DebugInfo.h.
Member Function Documentation
compile_unit_count()
unsigned llvm::DebugInfoFinder::compile_unit_count () const inline
Definition at line 149 of file DebugInfo.h.
compile_units()
iterator_range< compile_unit_iterator > llvm::DebugInfoFinder::compile_units () const inline
Definition at line 129 of file DebugInfo.h.
References llvm::make_range().
Referenced by printModuleDebugInfo().
global_variable_count()
unsigned llvm::DebugInfoFinder::global_variable_count () const inline
Definition at line 150 of file DebugInfo.h.
global_variables()
iterator_range< global_variable_expression_iterator > llvm::DebugInfoFinder::global_variables () const inline
Definition at line 137 of file DebugInfo.h.
References llvm::make_range().
Referenced by printModuleDebugInfo().
processInstruction()
void DebugInfoFinder::processInstruction (const Module & M, const Instruction & I)
Process a single instruction and collect debug info anchors.
Definition at line 192 of file DebugInfo.cpp.
References I, processLocation(), and processVariable().
Referenced by processModule().
processLocation()
void DebugInfoFinder::processLocation (const Module & M, const DILocation * Loc)
Process debug info location.
Definition at line 201 of file DebugInfo.cpp.
References processLocation().
Referenced by processInstruction(), and processLocation().
processModule()
void DebugInfoFinder::processModule (const Module & M)
Process entire module and collect debug info anchors.
Definition at line 148 of file DebugInfo.cpp.
References F, I, processInstruction(), and processSubprogram().
Referenced by llvm::ModuleDebugInfoPrinterPass::run(), and stripDeadDebugInfoImpl().
processSubprogram()
void DebugInfoFinder::processSubprogram (DISubprogram * SP)
Process subprogram.
Definition at line 258 of file DebugInfo.cpp.
References llvm::DIScope::getScope().
Referenced by processModule().
processVariable()
void DebugInfoFinder::processVariable (const Module & M, const DbgVariableIntrinsic & DVI)
Process DbgVariableIntrinsic.
Definition at line 281 of file DebugInfo.cpp.
References llvm::DbgVariableIntrinsic::getVariable(), and N.
Referenced by processInstruction().
reset()
void DebugInfoFinder::reset ()
Clear all lists.
Definition at line 139 of file DebugInfo.cpp.
scope_count()
unsigned llvm::DebugInfoFinder::scope_count () const inline
Definition at line 153 of file DebugInfo.h.
scopes()
iterator_range< scope_iterator > llvm::DebugInfoFinder::scopes () const inline
Definition at line 145 of file DebugInfo.h.
References llvm::make_range().
subprogram_count()
unsigned llvm::DebugInfoFinder::subprogram_count () const inline
Definition at line 151 of file DebugInfo.h.
subprograms()
iterator_range< subprogram_iterator > llvm::DebugInfoFinder::subprograms () const inline
Definition at line 133 of file DebugInfo.h.
References llvm::make_range().
Referenced by printModuleDebugInfo().
type_count()
unsigned llvm::DebugInfoFinder::type_count () const inline
Definition at line 152 of file DebugInfo.h.
types()
iterator_range< type_iterator > llvm::DebugInfoFinder::types () const inline
Definition at line 141 of file DebugInfo.h.
References llvm::make_range().
Referenced by printModuleDebugInfo().
The documentation for this class was generated from the following files:
include/llvm/IR/DebugInfo.h
lib/IR/DebugInfo.cpp