LLVM: llvm::HexagonTTIImpl Class Reference
llvm::HexagonTTIImpl Class Reference
#include "Target/Hexagon/HexagonTargetTransformInfo.h"
Public Member Functions
HexagonTTIImpl (const HexagonTargetMachine *TM, const Function &F)
InstructionCost getUserCost (const User *U, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind)
bool shouldBuildLookupTables () const
Scalar TTI Implementations
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit) const
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP)
void getPeelingPreferences (Loop *L, ScalarEvolution &SE, TTI::PeelingPreferences &PP)
TTI::AddressingModeKind getPreferredAddressingMode (const Loop *L, ScalarEvolution *SE) const
Bias LSR towards creating post-increment opportunities.
unsigned getPrefetchDistance () const override
— Vector TTI end —
unsigned getCacheLineSize () const override
Vector TTI Implementations
unsigned getNumberOfRegisters (bool vector) const
— Vector TTI begin —
unsigned getMaxInterleaveFactor (unsigned VF)
TypeSize getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const
unsigned getMinVectorRegisterBitWidth () const
ElementCount getMinimumVF (unsigned ElemWidth, bool IsScalable) const
bool shouldMaximizeVectorBandwidth () const
bool supportsEfficientVectorElementLoadStore ()
bool hasBranchDivergence ()
bool enableAggressiveInterleaving (bool LoopHasReductions)
bool prefersVectorizedAddressing ()
bool enableInterleavedAccessVectorization ()
InstructionCost getScalarizationOverhead (VectorType *Ty, const APInt &DemandedElts, bool Insert, bool Extract)
InstructionCost getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, ArrayRef< Type * > Tys)
InstructionCost getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind)
InstructionCost getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind)
InstructionCost getAddressComputationCost (Type *Tp, ScalarEvolution *SE, const SCEV *S)
InstructionCost getMemoryOpCost (unsigned Opcode, Type *Src, MaybeAlign Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getMaskedMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind=TTI::TCK_SizeAndLatency)
InstructionCost getShuffleCost (TTI::ShuffleKind Kind, Type *Tp, ArrayRef< int > Mask, int Index, Type *SubTp)
InstructionCost getGatherScatterOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I)
InstructionCost getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind=TTI::TCK_SizeAndLatency, bool UseMaskForCond=false, bool UseMaskForGaps=false)
InstructionCost getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind=TTI::TCK_RecipThroughput, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None, ArrayRef< const Value * > Args=ArrayRef< const Value * >(), const Instruction *CxtI=nullptr)
InstructionCost getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
InstructionCost getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
bool isLegalMaskedStore (Type *DataType, Align Alignment)
bool isLegalMaskedLoad (Type *DataType, Align Alignment)
Public Member Functions inherited from llvm::BasicTTIImplBase< HexagonTTIImpl >
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, bool *Fast) const
bool hasBranchDivergence ()
bool useGPUDivergenceAnalysis ()
bool isSourceOfDivergence (const Value *V)
bool isAlwaysUniform (const Value *V)
unsigned getFlatAddressSpace ()
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
bool isNoopAddrSpaceCast (unsigned FromAS, unsigned ToAS) const
unsigned getAssumedAddrSpace (const Value *V) const
Value * rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
bool isLegalAddImmediate (int64_t imm)
bool isLegalICmpImmediate (int64_t imm)
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr)
bool isIndexedLoadLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode M, Type *Ty, const DataLayout &DL) const
bool isLSRCostLess (TTI::LSRCost C1, TTI::LSRCost C2)
bool isNumRegsMajorCostOfLSR ()
bool isProfitableLSRChainElement (Instruction *I)
InstructionCost getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace)
bool isTruncateFree (Type *Ty1, Type *Ty2)
bool isProfitableToHoist (Instruction *I)
bool useAA () const
bool isTypeLegal (Type *Ty)
InstructionCost getRegUsageForType (Type *Ty)
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands)
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JumpTableSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI)
bool shouldBuildLookupTables ()
bool shouldBuildRelLookupTables () const
bool haveFastSqrt (Type *Ty)
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty)
InstructionCost getFPOpCost (Type *Ty)
unsigned getInliningThresholdMultiplier ()
unsigned adjustInliningThreshold (const CallBase *CB)
int getInlinerVectorBonusPercent ()
void getUnrollingPreferences (Loop *L, ScalarEvolution &SE, TTI::UnrollingPreferences &UP)
void getPeelingPreferences (Loop *L, ScalarEvolution &SE, TTI::PeelingPreferences &PP)
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo)
bool preferPredicateOverEpilogue (Loop *L, LoopInfo *LI, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *TLI, DominatorTree *DT, const LoopAccessInfo *LAI)
bool emitGetActiveLaneMask ()
Optional< Instruction * > instCombineIntrinsic (InstCombiner &IC, IntrinsicInst &II)
Optional< Value * > simplifyDemandedUseBitsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed)
Optional< Value * > simplifyDemandedVectorEltsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp)
InstructionCost getInstructionLatency (const Instruction *I)
virtual Optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const
virtual Optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const
virtual unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const
virtual unsigned getMaxPrefetchIterationsAhead () const
virtual bool enableWritePrefetching () const
TypeSize getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const
Optional< unsigned > getMaxVScale () const
InstructionCost getScalarizationOverhead (VectorType *InTy, const APInt &DemandedElts, bool Insert, bool Extract)
Estimate the overhead of scalarizing an instruction.
InstructionCost getScalarizationOverhead (VectorType *InTy, bool Insert, bool Extract)
Helper wrapper for the DemandedElts variant of getScalarizationOverhead.
InstructionCost getScalarizationOverhead (VectorType *RetTy, ArrayRef< const Value * > Args, ArrayRef< Type * > Tys)
Estimate the overhead of scalarizing the inputs and outputs of an instruction, with return type RetTy and arguments Args of type Tys.
InstructionCost getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, ArrayRef< Type * > Tys)
Estimate the overhead of scalarizing an instructions unique non-constant operands.
unsigned getMaxInterleaveFactor (unsigned VF)
InstructionCost getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind=TTI::TCK_RecipThroughput, TTI::OperandValueKind Opd1Info=TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info=TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo=TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo=TTI::OP_None, ArrayRef< const Value * > Args=ArrayRef< const Value * >(), const Instruction *CxtI=nullptr)
TTI::ShuffleKind improveShuffleKindFromMask (TTI::ShuffleKind Kind, ArrayRef< int > Mask) const
InstructionCost getShuffleCost (TTI::ShuffleKind Kind, VectorType *Tp, ArrayRef< int > Mask, int Index, VectorType *SubTp)
InstructionCost getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index)
InstructionCost getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index)
InstructionCost getMemoryOpCost (unsigned Opcode, Type *Src, MaybeAlign Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getMaskedMemoryOpCost (unsigned Opcode, Type *DataTy, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind)
InstructionCost getGatherScatterOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr)
InstructionCost getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond=false, bool UseMaskForGaps=false)
InstructionCost getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind)
Get intrinsic cost based on arguments.
InstructionCost getTypeBasedIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind)
Get intrinsic cost based on argument types.
InstructionCost getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind=TTI::TCK_SizeAndLatency)
Compute a cost of the given call instruction.
unsigned getNumberOfParts (Type *Tp)
InstructionCost getAddressComputationCost (Type *Ty, ScalarEvolution *, const SCEV *)
InstructionCost getTreeReductionCost (unsigned Opcode, VectorType *Ty, TTI::TargetCostKind CostKind)
Try to calculate arithmetic and shuffle op costs for reduction intrinsics.
InstructionCost getOrderedReductionCost (unsigned Opcode, VectorType *Ty, TTI::TargetCostKind CostKind)
Try to calculate the cost of performing strict (in-order) reductions, which involves doing a sequence of floating point additions in lane order, starting with an initial value.
InstructionCost getArithmeticReductionCost (unsigned Opcode, VectorType *Ty, Optional< FastMathFlags > FMF, TTI::TargetCostKind CostKind)
InstructionCost getMinMaxReductionCost (VectorType *Ty, VectorType *CondTy, bool IsUnsigned, TTI::TargetCostKind CostKind)
Try to calculate op costs for min/max reduction operations.
InstructionCost getExtendedAddReductionCost (bool IsMLA, bool IsUnsigned, Type *ResTy, VectorType *Ty, TTI::TargetCostKind CostKind)
InstructionCost getVectorSplitCost ()
Public Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind=TTI::TCK_SizeAndLatency)
InstructionCost getUserCost (const User *U, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind)
InstructionCost getInstructionLatency (const Instruction *I)
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind=TTI::TCK_SizeAndLatency) const
Public Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const TargetTransformInfoImplBase &Arg)
TargetTransformInfoImplBase (TargetTransformInfoImplBase &&Arg)
const DataLayout & getDataLayout () const
InstructionCost getGEPCost (Type *PointeeType, const Value *Ptr, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind=TTI::TCK_SizeAndLatency) const
unsigned getEstimatedNumberOfCaseClusters (const SwitchInst &SI, unsigned &JTSize, ProfileSummaryInfo *PSI, BlockFrequencyInfo *BFI) const
unsigned getInliningThresholdMultiplier () const
unsigned adjustInliningThreshold (const CallBase *CB) const
int getInlinerVectorBonusPercent () const
InstructionCost getMemcpyCost (const Instruction *I) const
BranchProbability getPredictableBranchThreshold () const
bool hasBranchDivergence () const
bool useGPUDivergenceAnalysis () const
bool isSourceOfDivergence (const Value *V) const
bool isAlwaysUniform (const Value *V) const
unsigned getFlatAddressSpace () const
bool collectFlatAddressOperands (SmallVectorImpl< int > &OpIndexes, Intrinsic::ID IID) const
bool isNoopAddrSpaceCast (unsigned, unsigned) const
unsigned getAssumedAddrSpace (const Value *V) const
Value * rewriteIntrinsicWithAddressSpace (IntrinsicInst *II, Value *OldV, Value *NewV) const
bool isLoweredToCall (const Function *F) const
bool isHardwareLoopProfitable (Loop *L, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *LibInfo, HardwareLoopInfo &HWLoopInfo) const
bool preferPredicateOverEpilogue (Loop *L, LoopInfo *LI, ScalarEvolution &SE, AssumptionCache &AC, TargetLibraryInfo *TLI, DominatorTree *DT, const LoopAccessInfo *LAI) const
bool emitGetActiveLaneMask () const
Optional< Instruction * > instCombineIntrinsic (InstCombiner &IC, IntrinsicInst &II) const
Optional< Value * > simplifyDemandedUseBitsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedMask, KnownBits &Known, bool &KnownBitsComputed) const
Optional< Value * > simplifyDemandedVectorEltsIntrinsic (InstCombiner &IC, IntrinsicInst &II, APInt DemandedElts, APInt &UndefElts, APInt &UndefElts2, APInt &UndefElts3, std::function< void(Instruction *, unsigned, APInt, APInt &)> SimplifyAndSetOp) const
void getUnrollingPreferences (Loop *, ScalarEvolution &, TTI::UnrollingPreferences &) const
void getPeelingPreferences (Loop *, ScalarEvolution &, TTI::PeelingPreferences &) const
bool isLegalAddImmediate (int64_t Imm) const
bool isLegalICmpImmediate (int64_t Imm) const
bool isLegalAddressingMode (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace, Instruction *I=nullptr) const
bool isLSRCostLess (TTI::LSRCost &C1, TTI::LSRCost &C2) const
bool isNumRegsMajorCostOfLSR () const
bool isProfitableLSRChainElement (Instruction *I) const
bool canMacroFuseCmp () const
bool canSaveCmp (Loop *L, BranchInst **BI, ScalarEvolution *SE, LoopInfo *LI, DominatorTree *DT, AssumptionCache *AC, TargetLibraryInfo *LibInfo) const
TTI::AddressingModeKind getPreferredAddressingMode (const Loop *L, ScalarEvolution *SE) const
bool isLegalMaskedStore (Type *DataType, Align Alignment) const
bool isLegalMaskedLoad (Type *DataType, Align Alignment) const
bool isLegalNTStore (Type *DataType, Align Alignment) const
bool isLegalNTLoad (Type *DataType, Align Alignment) const
bool isLegalMaskedScatter (Type *DataType, Align Alignment) const
bool isLegalMaskedGather (Type *DataType, Align Alignment) const
bool isLegalMaskedCompressStore (Type *DataType) const
bool isLegalMaskedExpandLoad (Type *DataType) const
bool hasDivRemOp (Type *DataType, bool IsSigned) const
bool hasVolatileVariant (Instruction *I, unsigned AddrSpace) const
bool prefersVectorizedAddressing () const
InstructionCost getScalingFactorCost (Type *Ty, GlobalValue *BaseGV, int64_t BaseOffset, bool HasBaseReg, int64_t Scale, unsigned AddrSpace) const
bool LSRWithInstrQueries () const
bool isTruncateFree (Type *Ty1, Type *Ty2) const
bool isProfitableToHoist (Instruction *I) const
bool useAA () const
bool isTypeLegal (Type *Ty) const
InstructionCost getRegUsageForType (Type *Ty) const
bool shouldBuildLookupTables () const
bool shouldBuildLookupTablesForConstant (Constant *C) const
bool shouldBuildRelLookupTables () const
bool useColdCCForColdCall (Function &F) const
InstructionCost getScalarizationOverhead (VectorType *Ty, const APInt &DemandedElts, bool Insert, bool Extract) const
InstructionCost getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, ArrayRef< Type * > Tys) const
bool supportsEfficientVectorElementLoadStore () const
bool enableAggressiveInterleaving (bool LoopHasReductions) const
TTI::MemCmpExpansionOptions enableMemCmpExpansion (bool OptSize, bool IsZeroCmp) const
bool enableInterleavedAccessVectorization () const
bool enableMaskedInterleavedAccessVectorization () const
bool isFPVectorizationPotentiallyUnsafe () const
bool allowsMisalignedMemoryAccesses (LLVMContext &Context, unsigned BitWidth, unsigned AddressSpace, Align Alignment, bool *Fast) const
TTI::PopcntSupportKind getPopcntSupport (unsigned IntTyWidthInBit) const
bool haveFastSqrt (Type *Ty) const
bool isFCmpOrdCheaperThanFCmpZero (Type *Ty) const
InstructionCost getFPOpCost (Type *Ty) const
InstructionCost getIntImmCodeSizeCost (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty) const
InstructionCost getIntImmCost (const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
InstructionCost getIntImmCostInst (unsigned Opcode, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind, Instruction *Inst=nullptr) const
InstructionCost getIntImmCostIntrin (Intrinsic::ID IID, unsigned Idx, const APInt &Imm, Type *Ty, TTI::TargetCostKind CostKind) const
unsigned getNumberOfRegisters (unsigned ClassID) const
unsigned getRegisterClassForType (bool Vector, Type *Ty=nullptr) const
const char * getRegisterClassName (unsigned ClassID) const
TypeSize getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const
unsigned getMinVectorRegisterBitWidth () const
Optional< unsigned > getMaxVScale () const
bool shouldMaximizeVectorBandwidth () const
ElementCount getMinimumVF (unsigned ElemWidth, bool IsScalable) const
unsigned getMaximumVF (unsigned ElemWidth, unsigned Opcode) const
bool shouldConsiderAddressTypePromotion (const Instruction &I, bool &AllowPromotionWithoutCommonHeader) const
unsigned getCacheLineSize () const
llvm::Optional< unsigned > getCacheSize (TargetTransformInfo::CacheLevel Level) const
llvm::Optional< unsigned > getCacheAssociativity (TargetTransformInfo::CacheLevel Level) const
unsigned getPrefetchDistance () const
unsigned getMinPrefetchStride (unsigned NumMemAccesses, unsigned NumStridedMemAccesses, unsigned NumPrefetches, bool HasCall) const
unsigned getMaxPrefetchIterationsAhead () const
bool enableWritePrefetching () const
unsigned getMaxInterleaveFactor (unsigned VF) const
InstructionCost getArithmeticInstrCost (unsigned Opcode, Type *Ty, TTI::TargetCostKind CostKind, TTI::OperandValueKind Opd1Info, TTI::OperandValueKind Opd2Info, TTI::OperandValueProperties Opd1PropInfo, TTI::OperandValueProperties Opd2PropInfo, ArrayRef< const Value * > Args, const Instruction *CxtI=nullptr) const
InstructionCost getShuffleCost (TTI::ShuffleKind Kind, VectorType *Ty, ArrayRef< int > Mask, int Index, VectorType *SubTp) const
InstructionCost getCastInstrCost (unsigned Opcode, Type *Dst, Type *Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction *I) const
InstructionCost getExtractWithExtendCost (unsigned Opcode, Type *Dst, VectorType *VecTy, unsigned Index) const
InstructionCost getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
InstructionCost getCmpSelInstrCost (unsigned Opcode, Type *ValTy, Type *CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, const Instruction *I) const
InstructionCost getVectorInstrCost (unsigned Opcode, Type *Val, unsigned Index) const
InstructionCost getMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction *I) const
InstructionCost getMaskedMemoryOpCost (unsigned Opcode, Type *Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind) const
InstructionCost getGatherScatterOpCost (unsigned Opcode, Type *DataTy, const Value *Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction *I=nullptr) const
unsigned getInterleavedMemoryOpCost (unsigned Opcode, Type *VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, bool UseMaskForCond, bool UseMaskForGaps) const
InstructionCost getIntrinsicInstrCost (const IntrinsicCostAttributes &ICA, TTI::TargetCostKind CostKind) const
InstructionCost getCallInstrCost (Function *F, Type *RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind) const
unsigned getNumberOfParts (Type *Tp) const
InstructionCost getAddressComputationCost (Type *Tp, ScalarEvolution *, const SCEV *) const
InstructionCost getArithmeticReductionCost (unsigned, VectorType *, Optional< FastMathFlags > FMF, TTI::TargetCostKind) const
InstructionCost getMinMaxReductionCost (VectorType *, VectorType *, bool, TTI::TargetCostKind) const
InstructionCost getExtendedAddReductionCost (bool IsMLA, bool IsUnsigned, Type *ResTy, VectorType *Ty, TTI::TargetCostKind CostKind=TTI::TCK_RecipThroughput) const
InstructionCost getCostOfKeepingLiveOverCall (ArrayRef< Type * > Tys) const
bool getTgtMemIntrinsic (IntrinsicInst *Inst, MemIntrinsicInfo &Info) const
unsigned getAtomicMemIntrinsicMaxElementSize () const
Value * getOrCreateResultFromMemIntrinsic (IntrinsicInst *Inst, Type *ExpectedType) const
Type * getMemcpyLoopLoweringType (LLVMContext &Context, Value *Length, unsigned SrcAddrSpace, unsigned DestAddrSpace, unsigned SrcAlign, unsigned DestAlign) const
void getMemcpyLoopResidualLoweringType (SmallVectorImpl< Type * > &OpsOut, LLVMContext &Context, unsigned RemainingBytes, unsigned SrcAddrSpace, unsigned DestAddrSpace, unsigned SrcAlign, unsigned DestAlign) const
bool areInlineCompatible (const Function *Caller, const Function *Callee) const
bool areFunctionArgsABICompatible (const Function *Caller, const Function *Callee, SmallPtrSetImpl< Argument * > &Args) const
bool isIndexedLoadLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
bool isIndexedStoreLegal (TTI::MemIndexedMode Mode, Type *Ty, const DataLayout &DL) const
unsigned getLoadStoreVecRegBitWidth (unsigned AddrSpace) const
bool isLegalToVectorizeLoad (LoadInst *LI) const
bool isLegalToVectorizeStore (StoreInst *SI) const
bool isLegalToVectorizeLoadChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeStoreChain (unsigned ChainSizeInBytes, Align Alignment, unsigned AddrSpace) const
bool isLegalToVectorizeReduction (const RecurrenceDescriptor &RdxDesc, ElementCount VF) const
bool isElementTypeLegalForScalableVector (Type *Ty) const
unsigned getLoadVectorFactor (unsigned VF, unsigned LoadSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
unsigned getStoreVectorFactor (unsigned VF, unsigned StoreSize, unsigned ChainSizeInBytes, VectorType *VecTy) const
bool preferInLoopReduction (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool preferPredicatedReductionSelect (unsigned Opcode, Type *Ty, TTI::ReductionFlags Flags) const
bool shouldExpandReduction (const IntrinsicInst *II) const
unsigned getGISelRematGlobalCost () const
bool supportsScalableVectors () const
bool hasActiveVectorLength () const
TargetTransformInfo::VPLegalization getVPLegalizationStrategy (const VPIntrinsic &PI) const
Additional Inherited Members
Protected Types inherited from llvm::TargetTransformInfoImplBase
typedef TargetTransformInfo TTI
Protected Member Functions inherited from llvm::BasicTTIImplBase< HexagonTTIImpl >
BasicTTIImplBase (const TargetMachine *TM, const DataLayout &DL)
virtual ~BasicTTIImplBase ()=default
Protected Member Functions inherited from llvm::TargetTransformInfoImplCRTPBase< T >
TargetTransformInfoImplCRTPBase (const DataLayout &DL)
Protected Member Functions inherited from llvm::TargetTransformInfoImplBase
TargetTransformInfoImplBase (const DataLayout &DL)
unsigned minRequiredElementSize (const Value *Val, bool &isSigned) const
bool isStridedAccess (const SCEV *Ptr) const
const SCEVConstant * getConstantStrideStep (ScalarEvolution *SE, const SCEV *Ptr) const
bool isConstantStridedAccessLessThan (ScalarEvolution *SE, const SCEV *Ptr, int64_t MergeDistance) const
Protected Attributes inherited from llvm::BasicTTIImplBase< HexagonTTIImpl >
const DataLayout & DL
Protected Attributes inherited from llvm::TargetTransformInfoImplBase
const DataLayout & DL
Detailed Description
Definition at line 33 of file HexagonTargetTransformInfo.h.
Constructor & Destructor Documentation
HexagonTTIImpl()
llvm::HexagonTTIImpl::HexagonTTIImpl (const HexagonTargetMachine * TM, const Function & F) inline explicit
Definition at line 53 of file HexagonTargetTransformInfo.h.
Member Function Documentation
enableAggressiveInterleaving()
bool llvm::HexagonTTIImpl::enableAggressiveInterleaving (bool LoopHasReductions) inline
Definition at line 97 of file HexagonTargetTransformInfo.h.
enableInterleavedAccessVectorization()
bool llvm::HexagonTTIImpl::enableInterleavedAccessVectorization () inline
Definition at line 103 of file HexagonTargetTransformInfo.h.
getAddressComputationCost()
InstructionCost HexagonTTIImpl::getAddressComputationCost (Type * Tp, ScalarEvolution * SE, const SCEV * S)
Definition at line 153 of file HexagonTargetTransformInfo.cpp.
getArithmeticInstrCost()
InstructionCost HexagonTTIImpl::getArithmeticInstrCost (unsigned Opcode, Type * Ty, TTI::TargetCostKind CostKind = TTI::TCK_RecipThroughput, TTI::OperandValueKind Opd1Info = TTI::OK_AnyValue, TTI::OperandValueKind Opd2Info = TTI::OK_AnyValue, TTI::OperandValueProperties Opd1PropInfo = TTI::OP_None, TTI::OperandValueProperties Opd2PropInfo = TTI::OP_None, ArrayRef< const Value * > Args = ArrayRef<const Value *>(), const Instruction * CxtI = nullptr)
Definition at line 262 of file HexagonTargetTransformInfo.cpp.
References CostKind, llvm::BasicTTIImplBase< HexagonTTIImpl >::DL, FloatFactor, llvm::BasicTTIImplBase< HexagonTTIImpl >::getArithmeticInstrCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), and llvm::TargetTransformInfo::TCK_RecipThroughput.
getCacheLineSize()
unsigned HexagonTTIImpl::getCacheLineSize () const override virtual
Reimplemented from llvm::BasicTTIImplBase< HexagonTTIImpl >.
Definition at line 339 of file HexagonTargetTransformInfo.cpp.
References llvm::HexagonSubtarget::getL1CacheLineSize().
getCallInstrCost()
InstructionCost HexagonTTIImpl::getCallInstrCost (Function * F, Type * RetTy, ArrayRef< Type * > Tys, TTI::TargetCostKind CostKind)
Definition at line 136 of file HexagonTargetTransformInfo.cpp.
References CostKind, F, llvm::BasicTTIImplBase< HexagonTTIImpl >::getCallInstrCost(), and RetTy.
getCastInstrCost()
InstructionCost HexagonTTIImpl::getCastInstrCost (unsigned Opcode, Type * Dst, Type * Src, TTI::CastContextHint CCH, TTI::TargetCostKind CostKind, const Instruction * I = nullptr)
Definition at line 283 of file HexagonTargetTransformInfo.cpp.
References CostKind, llvm::BasicTTIImplBase< HexagonTTIImpl >::DL, FloatFactor, llvm::TargetLoweringBase::getTypeLegalizationCost(), and llvm::TargetTransformInfo::TCK_RecipThroughput.
getCFInstrCost()
InstructionCost llvm::HexagonTTIImpl::getCFInstrCost (unsigned Opcode, TTI::TargetCostKind CostKind, const Instruction * I = nullptr) inline
Definition at line 159 of file HexagonTargetTransformInfo.h.
getCmpSelInstrCost()
InstructionCost HexagonTTIImpl::getCmpSelInstrCost (unsigned Opcode, Type * ValTy, Type * CondTy, CmpInst::Predicate VecPred, TTI::TargetCostKind CostKind, const Instruction * I = nullptr)
Definition at line 249 of file HexagonTargetTransformInfo.cpp.
References CostKind, llvm::BasicTTIImplBase< HexagonTTIImpl >::DL, FloatFactor, llvm::BasicTTIImplBase< HexagonTTIImpl >::getCmpSelInstrCost(), llvm::TargetLoweringBase::getTypeLegalizationCost(), I, llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm::TargetTransformInfo::TCK_RecipThroughput.
getGatherScatterOpCost()
InstructionCost HexagonTTIImpl::getGatherScatterOpCost (unsigned Opcode, Type * DataTy, const Value * Ptr, bool VariableMask, Align Alignment, TTI::TargetCostKind CostKind, const Instruction * I)
Definition at line 229 of file HexagonTargetTransformInfo.cpp.
References CostKind, llvm::BasicTTIImplBase< HexagonTTIImpl >::getGatherScatterOpCost(), and I.
getInterleavedMemoryOpCost()
InstructionCost HexagonTTIImpl::getInterleavedMemoryOpCost (unsigned Opcode, Type * VecTy, unsigned Factor, ArrayRef< unsigned > Indices, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind = TTI::TCK_SizeAndLatency, bool UseMaskForCond = false, bool UseMaskForGaps = false)
Definition at line 236 of file HexagonTargetTransformInfo.cpp.
References CostKind, llvm::BasicTTIImplBase< HexagonTTIImpl >::getInterleavedMemoryOpCost(), and getMemoryOpCost().
getIntrinsicInstrCost()
InstructionCost HexagonTTIImpl::getIntrinsicInstrCost (const IntrinsicCostAttributes & ICA, TTI::TargetCostKind CostKind)
Definition at line 143 of file HexagonTargetTransformInfo.cpp.
References CostKind, llvm::BasicTTIImplBase< HexagonTTIImpl >::DL, llvm::BasicTTIImplBase< HexagonTTIImpl >::getIntrinsicInstrCost(), and llvm::TargetLoweringBase::getTypeLegalizationCost().
getMaskedMemoryOpCost()
InstructionCost HexagonTTIImpl::getMaskedMemoryOpCost (unsigned Opcode, Type * Src, Align Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind = TTI::TCK_SizeAndLatency)
Definition at line 216 of file HexagonTargetTransformInfo.cpp.
References CostKind, and llvm::BasicTTIImplBase< HexagonTTIImpl >::getMaskedMemoryOpCost().
getMaxInterleaveFactor()
unsigned HexagonTTIImpl::getMaxInterleaveFactor (unsigned VF)
Definition at line 97 of file HexagonTargetTransformInfo.cpp.
getMemoryOpCost()
InstructionCost HexagonTTIImpl::getMemoryOpCost (unsigned Opcode, Type * Src, MaybeAlign Alignment, unsigned AddressSpace, TTI::TargetCostKind CostKind, const Instruction * I = nullptr)
Definition at line 159 of file HexagonTargetTransformInfo.cpp.
References Align, llvm::alignTo(), assert(), CostKind, FloatFactor, llvm::VectorType::getElementType(), llvm::TypeSize::getFixedSize(), llvm::BasicTTIImplBase< HexagonTTIImpl >::getMemoryOpCost(), llvm::Type::getPrimitiveSizeInBits(), getRegisterBitWidth(), I, llvm::Type::isFloatingPointTy(), llvm::HexagonSubtarget::isTypeForHVX(), llvm::Type::isVectorTy(), llvm::Log2(), llvm::TargetTransformInfo::RGK_FixedWidthVector, llvm::TargetTransformInfo::TCK_RecipThroughput, and llvm::MaybeAlign::valueOrOne().
Referenced by getInterleavedMemoryOpCost().
getMinimumVF()
ElementCount HexagonTTIImpl::getMinimumVF (unsigned ElemWidth, bool IsScalable) const
Definition at line 119 of file HexagonTargetTransformInfo.cpp.
References assert(), llvm::LinearPolySize< ElementCount >::getFixed(), and llvm::HexagonSubtarget::getVectorLength().
getMinVectorRegisterBitWidth()
unsigned HexagonTTIImpl::getMinVectorRegisterBitWidth () const
Definition at line 115 of file HexagonTargetTransformInfo.cpp.
References llvm::HexagonSubtarget::getVectorLength().
Referenced by getRegisterBitWidth().
getNumberOfRegisters()
unsigned HexagonTTIImpl::getNumberOfRegisters (bool vector) const
— Vector TTI begin —
Definition at line 91 of file HexagonTargetTransformInfo.cpp.
References llvm::Vector.
getOperandsScalarizationOverhead()
InstructionCost HexagonTTIImpl::getOperandsScalarizationOverhead (ArrayRef< const Value * > Args, ArrayRef< Type * > Tys)
Definition at line 131 of file HexagonTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< HexagonTTIImpl >::getOperandsScalarizationOverhead().
getPeelingPreferences()
void HexagonTTIImpl::getPeelingPreferences (Loop * L, ScalarEvolution & SE, TTI::PeelingPreferences & PP)
Definition at line 71 of file HexagonTargetTransformInfo.cpp.
References llvm::canPeel(), llvm::BasicTTIImplBase< HexagonTTIImpl >::getPeelingPreferences(), llvm::ScalarEvolution::getSmallConstantMaxTripCount(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::LoopBase< BlockT, LoopT >::isInnermost(), and llvm::TargetTransformInfo::PeelingPreferences::PeelCount.
getPopcntSupport()
TargetTransformInfo::PopcntSupportKind HexagonTTIImpl::getPopcntSupport (unsigned IntTyWidthInBit) const
Definition at line 59 of file HexagonTargetTransformInfo.cpp.
References llvm::TargetTransformInfo::PSK_FastHardware.
getPreferredAddressingMode()
TTI::AddressingModeKind HexagonTTIImpl::getPreferredAddressingMode (const Loop * L, ScalarEvolution * SE) const
Bias LSR towards creating post-increment opportunities.
Definition at line 84 of file HexagonTargetTransformInfo.cpp.
References llvm::TargetTransformInfo::AMK_PostIndexed.
getPrefetchDistance()
unsigned HexagonTTIImpl::getPrefetchDistance () const override virtual
— Vector TTI end —
Reimplemented from llvm::BasicTTIImplBase< HexagonTTIImpl >.
Definition at line 335 of file HexagonTargetTransformInfo.cpp.
References llvm::HexagonSubtarget::getL1PrefetchDistance().
getRegisterBitWidth()
TypeSize HexagonTTIImpl::getRegisterBitWidth (TargetTransformInfo::RegisterKind K) const
Definition at line 102 of file HexagonTargetTransformInfo.cpp.
References llvm::LinearPolySize< TypeSize >::getFixed(), getMinVectorRegisterBitWidth(), llvm::LinearPolySize< TypeSize >::getScalable(), llvm_unreachable, llvm::TargetTransformInfo::RGK_FixedWidthVector, llvm::TargetTransformInfo::RGK_ScalableVector, and llvm::TargetTransformInfo::RGK_Scalar.
Referenced by getMemoryOpCost().
getScalarizationOverhead()
InstructionCost HexagonTTIImpl::getScalarizationOverhead (VectorType * Ty, const APInt & DemandedElts, bool Insert, bool Extract)
Definition at line 125 of file HexagonTargetTransformInfo.cpp.
References llvm::BasicTTIImplBase< HexagonTTIImpl >::getScalarizationOverhead().
getShuffleCost()
InstructionCost HexagonTTIImpl::getShuffleCost (TTI::ShuffleKind Kind, Type * Tp, ArrayRef< int > Mask, int Index, Type * SubTp)
Definition at line 223 of file HexagonTargetTransformInfo.cpp.
getUnrollingPreferences()
void HexagonTTIImpl::getUnrollingPreferences (Loop * L, ScalarEvolution & SE, TTI::UnrollingPreferences & UP)
Definition at line 66 of file HexagonTargetTransformInfo.cpp.
References llvm::TargetTransformInfo::UnrollingPreferences::Partial, and llvm::TargetTransformInfo::UnrollingPreferences::Runtime.
getUserCost()
InstructionCost HexagonTTIImpl::getUserCost (const User * U, ArrayRef< const Value * > Operands, TTI::TargetCostKind CostKind)
Definition at line 343 of file HexagonTargetTransformInfo.cpp.
References CostKind, llvm::BasicTTIImplBase< HexagonTTIImpl >::DL, llvm::TargetTransformInfoImplBase::getDataLayout(), llvm::DataLayout::getTypeSizeInBits(), llvm::TargetTransformInfoImplCRTPBase< T >::getUserCost(), llvm::Value::hasOneUse(), Operands, and llvm::TargetTransformInfo::TCC_Free.
getVectorInstrCost()
InstructionCost HexagonTTIImpl::getVectorInstrCost (unsigned Opcode, Type * Val, unsigned Index)
Definition at line 306 of file HexagonTargetTransformInfo.cpp.
References getVectorInstrCost(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm::Type::isVectorTy().
Referenced by getVectorInstrCost().
hasBranchDivergence()
bool llvm::HexagonTTIImpl::hasBranchDivergence () inline
Definition at line 94 of file HexagonTargetTransformInfo.h.
isLegalMaskedLoad()
bool HexagonTTIImpl::isLegalMaskedLoad (Type * DataType, Align Alignment)
Definition at line 329 of file HexagonTargetTransformInfo.cpp.
References HexagonMaskedVMem, and llvm::HexagonSubtarget::isTypeForHVX().
isLegalMaskedStore()
bool HexagonTTIImpl::isLegalMaskedStore (Type * DataType, Align Alignment)
Definition at line 325 of file HexagonTargetTransformInfo.cpp.
References HexagonMaskedVMem, and llvm::HexagonSubtarget::isTypeForHVX().
prefersVectorizedAddressing()
bool llvm::HexagonTTIImpl::prefersVectorizedAddressing () inline
Definition at line 100 of file HexagonTargetTransformInfo.h.
shouldBuildLookupTables()
bool HexagonTTIImpl::shouldBuildLookupTables () const
Definition at line 370 of file HexagonTargetTransformInfo.cpp.
References EmitLookupTables.
shouldMaximizeVectorBandwidth()
bool llvm::HexagonTTIImpl::shouldMaximizeVectorBandwidth () const inline
Definition at line 88 of file HexagonTargetTransformInfo.h.
supportsEfficientVectorElementLoadStore()
bool llvm::HexagonTTIImpl::supportsEfficientVectorElementLoadStore () inline
Definition at line 91 of file HexagonTargetTransformInfo.h.
The documentation for this class was generated from the following files:
lib/Target/Hexagon/HexagonTargetTransformInfo.h
lib/Target/Hexagon/HexagonTargetTransformInfo.cpp