LLVM: llvm::orc::shared::detail::ResponseHandlerImpl< ChannelT, Error, HandlerT > Class Template Reference
llvm::orc::shared::detail::ResponseHandlerImpl< ChannelT, Error, HandlerT > Class Template Reference
#include "llvm/ExecutionEngine/Orc/Shared/RPCUtils.h"
Public Member Functions
ResponseHandlerImpl (HandlerT Handler)
Error handleResponse (ChannelT &C) override
void abandon () override
Public Member Functions inherited from llvm::orc::shared::detail::ResponseHandler< ChannelT >
virtual ~ResponseHandler ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::orc::shared::detail::ResponseHandler< ChannelT >
static Error createAbandonedResponseError ()
Detailed Description
template<typename ChannelT, typename HandlerT>
class llvm::orc::shared::detail::ResponseHandlerImpl< ChannelT, Error, HandlerT >
Definition at line 738 of file RPCUtils.h.
Constructor & Destructor Documentation
ResponseHandlerImpl()
template<typename ChannelT , typename HandlerT > llvm::orc::shared::detail::ResponseHandlerImpl< ChannelT, Error, HandlerT >::ResponseHandlerImpl (HandlerT Handler) inline
Definition at line 741 of file RPCUtils.h.
Member Function Documentation
abandon()
template<typename ChannelT , typename HandlerT > void llvm::orc::shared::detail::ResponseHandlerImpl< ChannelT, Error, HandlerT >::abandon () inline override virtual
Implements llvm::orc::shared::detail::ResponseHandler< ChannelT >.
Definition at line 761 of file RPCUtils.h.
References llvm::orc::shared::detail::ResponseHandler< ChannelT >::createAbandonedResponseError(), and llvm::report_fatal_error().
handleResponse()
template<typename ChannelT , typename HandlerT > Error llvm::orc::shared::detail::ResponseHandlerImpl< ChannelT, Error, HandlerT >::handleResponse (ChannelT & C) inline override virtual
Implements llvm::orc::shared::detail::ResponseHandler< ChannelT >.
Definition at line 745 of file RPCUtils.h.
References C, llvm::consumeError(), and llvm::Error::success().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/RPCUtils.h