LLVM: llvm::MipsInstPrinter Class Reference
llvm::MipsInstPrinter Class Reference
#include "Target/Mips/MCTargetDesc/MipsInstPrinter.h"
Public Member Functions
MipsInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
std::pair< const char *, uint64_t > getMnemonic (const MCInst *MI) override
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
void printInstruction (const MCInst *MI, uint64_t Address, raw_ostream &O)
void printRegName (raw_ostream &OS, unsigned RegNo) const override
Print the assembler register name.
void printInst (const MCInst *MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo &STI, raw_ostream &O) override
Print the specified MCInst to the specified raw_ostream.
bool printAliasInstr (const MCInst *MI, uint64_t Address, raw_ostream &OS)
void printCustomAliasOperand (const MCInst *MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
virtual bool applyTargetSpecificCLOption (StringRef Opt)
Customize the printer according to a command line option.
void setCommentStream (raw_ostream &OS)
Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
Return the name of the specified opcode enum (e.g.
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
void setPrintHexStyle (HexStyle::Style Value)
void setPrintBranchImmAsAddress (bool Value)
void setSymbolizeOperands (bool Value)
void setMCInstrAnalysis (const MCInstrAnalysis *Value)
format_object< int64_t > formatImm (int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object< int64_t > formatDec (int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object< int64_t > formatHex (int64_t Value) const
format_object< uint64_t > formatHex (uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
const char * matchAliasPatterns (const MCInst *MI, const MCSubtargetInfo *STI, const AliasMatchingData &M)
Helper for matching MCInsts to alias patterns when printing instructions.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream = nullptr
A stream that comments can be emitted to if desired.
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
const MCInstrAnalysis * MIA = nullptr
bool UseMarkup = false
True if we are printing marked up assembly.
bool PrintAliases = true
True if we prefer aliases (e.g. nop) to raw mnemonics.
bool PrintImmHex = false
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle = HexStyle::C
Which style to use for printing hexadecimal values.
bool PrintBranchImmAsAddress = false
If true, a branch immediate (e.g.
bool SymbolizeOperands = false
If true, symbolize branch target and memory reference operands.
Detailed Description
Definition at line 75 of file MipsInstPrinter.h.
Constructor & Destructor Documentation
MipsInstPrinter()
llvm::MipsInstPrinter::MipsInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 77 of file MipsInstPrinter.h.
Member Function Documentation
getMnemonic()
std::pair< const char *, uint64_t > llvm::MipsInstPrinter::getMnemonic (const MCInst * MI) override virtual
Returns a pair containing the mnemonic for MI and the number of bits left for further processing by printInstruction (generated by tablegen).
Implements llvm::MCInstPrinter.
getRegisterName()
static const char * llvm::MipsInstPrinter::getRegisterName (unsigned RegNo) static
Referenced by llvm::MipsTargetAsmStreamer::emitDirectiveCpAdd(), llvm::MipsTargetAsmStreamer::emitDirectiveCpLoad(), llvm::MipsTargetAsmStreamer::emitDirectiveCpLocal(), llvm::MipsTargetAsmStreamer::emitDirectiveCpsetup(), llvm::MipsTargetAsmStreamer::emitFrame(), llvm::MipsAsmPrinter::PrintAsmMemoryOperand(), llvm::MipsAsmPrinter::PrintAsmOperand(), llvm::MipsAsmPrinter::printOperand(), and printRegName().
printAliasInstr()
bool llvm::MipsInstPrinter::printAliasInstr (const MCInst * MI, uint64_t Address, raw_ostream & OS)
Referenced by printInst().
printCustomAliasOperand()
void llvm::MipsInstPrinter::printCustomAliasOperand (const MCInst * MI, uint64_t Address, unsigned OpIdx, unsigned PrintMethodIdx, raw_ostream & O)
printInst()
void MipsInstPrinter::printInst (const MCInst * MI, uint64_t Address, StringRef Annot, const MCSubtargetInfo & STI, raw_ostream & OS) override virtual
Print the specified MCInst to the specified raw_ostream.
Address the address of current instruction on most targets, used to print a PC relative immediate as the target address. On targets where a PC relative immediate is relative to the next instruction and the length of a MCInst is difficult to measure (e.g. x86), this is the address of the next instruction. If Address is 0, the immediate will be printed.
Implements llvm::MCInstPrinter.
Definition at line 78 of file MipsInstPrinter.cpp.
References MI, printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), and printInstruction().
printInstruction()
void llvm::MipsInstPrinter::printInstruction (const MCInst * MI, uint64_t Address, raw_ostream & O)
Referenced by printInst().
printRegName()
void MipsInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const override virtual
Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 74 of file MipsInstPrinter.cpp.
References getRegisterName(), and llvm::StringRef::lower().
The documentation for this class was generated from the following files:
lib/Target/Mips/MCTargetDesc/MipsInstPrinter.h
lib/Target/Mips/MCTargetDesc/MipsInstPrinter.cpp