LLVM: llvm::AliasSummary Class Reference
llvm::AliasSummary Class Reference
Alias summary information.
#include "llvm/IR/ModuleSummaryIndex.h"
Public Member Functions
AliasSummary (GVFlags Flags)
void setAliasee (ValueInfo &AliaseeVI, GlobalValueSummary *Aliasee)
bool hasAliasee () const
const GlobalValueSummary & getAliasee () const
GlobalValueSummary & getAliasee ()
ValueInfo getAliaseeVI () const
GlobalValue::GUID getAliaseeGUID () const
Public Member Functions inherited from llvm::GlobalValueSummary
virtual ~GlobalValueSummary ()=default
GlobalValue::GUID getOriginalName () const
Returns the hash of the original name, it is identical to the GUID for externally visible symbols, but not for local ones.
void setOriginalName (GlobalValue::GUID Name)
Initialize the original name hash in this summary.
SummaryKind getSummaryKind () const
Which kind of summary subclass this is.
void setModulePath (StringRef ModPath)
Set the path to the module containing this function, for use in the combined index.
StringRef modulePath () const
Get the path to the module containing this function.
GVFlags flags () const
Get the flags for this GlobalValue (see struct GVFlags).
GlobalValue::LinkageTypes linkage () const
Return linkage type recorded for this global value.
void setLinkage (GlobalValue::LinkageTypes Linkage)
Sets the linkage to the value determined by global summary-based optimization.
bool notEligibleToImport () const
Return true if this global value can't be imported.
bool isLive () const
void setLive (bool Live)
void setDSOLocal (bool Local)
bool isDSOLocal () const
void setCanAutoHide (bool CanAutoHide)
bool canAutoHide () const
GlobalValue::VisibilityTypes getVisibility () const
void setVisibility (GlobalValue::VisibilityTypes Vis)
void setNotEligibleToImport ()
Flag that this global value cannot be imported.
ArrayRef< ValueInfo > refs () const
Return the list of values referenced by this global value definition.
GlobalValueSummary * getBaseObject ()
If this is an alias summary, returns the summary of the aliased object (a global variable or function), otherwise returns itself.
const GlobalValueSummary * getBaseObject () const
Static Public Member Functions
static bool classof (const GlobalValueSummary *GVS)
Check if this is an alias summary.
Additional Inherited Members
Public Types inherited from llvm::GlobalValueSummary
enum SummaryKind : unsigned { AliasKind , FunctionKind , GlobalVarKind }
Sububclass discriminator (for dyn_cast<> et al.)
Protected Member Functions inherited from llvm::GlobalValueSummary
GlobalValueSummary (SummaryKind K, GVFlags Flags, std::vector< ValueInfo > Refs)
Detailed Description
Alias summary information.
Definition at line 449 of file ModuleSummaryIndex.h.
Constructor & Destructor Documentation
AliasSummary()
llvm::AliasSummary::AliasSummary (GVFlags Flags) inline
Definition at line 459 of file ModuleSummaryIndex.h.
Member Function Documentation
classof()
static bool llvm::AliasSummary::classof (const GlobalValueSummary * GVS) inline static
Check if this is an alias summary.
Definition at line 464 of file ModuleSummaryIndex.h.
References llvm::GlobalValueSummary::AliasKind.
getAliasee() [1/2]
GlobalValueSummary & llvm::AliasSummary::getAliasee () inline
Definition at line 485 of file ModuleSummaryIndex.h.
References getAliasee().
getAliasee() [2/2]
const GlobalValueSummary & llvm::AliasSummary::getAliasee () const inline
Definition at line 480 of file ModuleSummaryIndex.h.
References assert().
Referenced by getAliasee().
getAliaseeGUID()
GlobalValue::GUID llvm::AliasSummary::getAliaseeGUID () const inline
Definition at line 493 of file ModuleSummaryIndex.h.
References assert(), and llvm::ValueInfo::getGUID().
getAliaseeVI()
ValueInfo llvm::AliasSummary::getAliaseeVI () const inline
Definition at line 489 of file ModuleSummaryIndex.h.
References assert().
hasAliasee()
bool llvm::AliasSummary::hasAliasee () const inline
Definition at line 473 of file ModuleSummaryIndex.h.
References assert(), and llvm::ValueInfo::getSummaryList().
setAliasee()
void llvm::AliasSummary::setAliasee (ValueInfo & AliaseeVI, GlobalValueSummary * Aliasee) inline
Definition at line 468 of file ModuleSummaryIndex.h.
The documentation for this class was generated from the following file:
include/llvm/IR/ModuleSummaryIndex.h