LLVM: llvm::sampleprof::ProfiledCallGraph Class Reference
llvm::sampleprof::ProfiledCallGraph Class Reference
#include "llvm/Transforms/IPO/ProfiledCallGraph.h"
Public Types
using iterator = std::set<ProfiledCallGraphNode *>::iterator
Public Member Functions
ProfiledCallGraph (StringMap< FunctionSamples > &ProfileMap)
ProfiledCallGraph (SampleContextTracker &ContextTracker)
iterator begin ()
iterator end ()
ProfiledCallGraphNode * getEntryNode ()
void addProfiledFunction (StringRef Name)
void addProfiledCall (StringRef CallerName, StringRef CalleeName)
void addProfiledCalls (const FunctionSamples &Samples)
Detailed Description
Definition at line 40 of file ProfiledCallGraph.h.
Member Typedef Documentation
iterator
using llvm::sampleprof::ProfiledCallGraph::iterator = std::set<ProfiledCallGraphNode *>::iterator
Definition at line 42 of file ProfiledCallGraph.h.
Constructor & Destructor Documentation
ProfiledCallGraph() [1/2]
llvm::sampleprof::ProfiledCallGraph::ProfiledCallGraph (StringMap< FunctionSamples > & ProfileMap) inline
Definition at line 45 of file ProfiledCallGraph.h.
References addProfiledCalls(), assert(), and llvm::sampleprof::FunctionSamples::ProfileIsCS.
ProfiledCallGraph() [2/2]
llvm::sampleprof::ProfiledCallGraph::ProfiledCallGraph (SampleContextTracker & ContextTracker) inline
Definition at line 53 of file ProfiledCallGraph.h.
References addProfiledCall(), addProfiledFunction(), Callee, llvm::ContextTrieNode::getAllChildContext(), and llvm::SampleContextTracker::getRootContext().
Member Function Documentation
addProfiledCall()
void llvm::sampleprof::ProfiledCallGraph::addProfiledCall (StringRef CallerName, StringRef CalleeName) inline
Definition at line 94 of file ProfiledCallGraph.h.
References assert().
Referenced by addProfiledCalls(), and ProfiledCallGraph().
addProfiledCalls()
void llvm::sampleprof::ProfiledCallGraph::addProfiledCalls (const FunctionSamples & Samples) inline
Definition at line 103 of file ProfiledCallGraph.h.
References addProfiledCall(), addProfiledCalls(), addProfiledFunction(), llvm::sampleprof::FunctionSamples::getBodySamples(), llvm::sampleprof::FunctionSamples::getCallsiteSamples(), and llvm::sampleprof::FunctionSamples::getFuncName().
Referenced by addProfiledCalls(), and ProfiledCallGraph().
addProfiledFunction()
void llvm::sampleprof::ProfiledCallGraph::addProfiledFunction (StringRef Name) inline
Definition at line 85 of file ProfiledCallGraph.h.
References llvm::sampleprof::ProfiledCallGraphNode::Callees, and Name.
Referenced by addProfiledCalls(), and ProfiledCallGraph().
begin()
iterator llvm::sampleprof::ProfiledCallGraph::begin () inline
Definition at line 82 of file ProfiledCallGraph.h.
References llvm::sampleprof::ProfiledCallGraphNode::Callees.
end()
iterator llvm::sampleprof::ProfiledCallGraph::end () inline
Definition at line 83 of file ProfiledCallGraph.h.
References llvm::sampleprof::ProfiledCallGraphNode::Callees.
getEntryNode()
ProfiledCallGraphNode * llvm::sampleprof::ProfiledCallGraph::getEntryNode () inline
Definition at line 84 of file ProfiledCallGraph.h.
The documentation for this class was generated from the following file:
include/llvm/Transforms/IPO/ProfiledCallGraph.h