LLVM: llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >::OrcRPCAllocation Class Reference
llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >::OrcRPCAllocation Class Reference
#include "llvm/ExecutionEngine/Orc/OrcRPCExecutorProcessControl.h"
Public Member Functions
OrcRPCAllocation (OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT > &Parent, HostAllocMap HostAllocs, TargetAllocMap TargetAllocs)
~OrcRPCAllocation () override
MutableArrayRef< char > getWorkingMemory (ProtectionFlags Seg) override
Should return the address of linker working memory for the segment with the given protection flags.
JITTargetAddress getTargetMemory (ProtectionFlags Seg) override
Should return the final address in the target process where the segment will reside.
void finalizeAsync (FinalizeContinuation OnFinalize) override
Should transfer from working memory to target memory, and release working memory.
Error deallocate () override
Should deallocate target memory.
Public Member Functions inherited from llvm::jitlink::JITLinkMemoryManager::Allocation
virtual ~Allocation ()
Error finalize ()
Calls finalizeAsync and waits for completion.
Additional Inherited Members
Public Types inherited from llvm::jitlink::JITLinkMemoryManager::Allocation
using FinalizeContinuation = std::function<void(Error)>
Detailed Description
template<typename OrcRPCEPCImplT>
class llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >::OrcRPCAllocation
Definition at line 44 of file OrcRPCExecutorProcessControl.h.
Constructor & Destructor Documentation
OrcRPCAllocation()
template<typename OrcRPCEPCImplT > llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >::OrcRPCAllocation::OrcRPCAllocation (OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT > & Parent, HostAllocMap HostAllocs, TargetAllocMap TargetAllocs) inline
Definition at line 46 of file OrcRPCExecutorProcessControl.h.
References assert(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::size().
~OrcRPCAllocation()
template<typename OrcRPCEPCImplT > llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >::OrcRPCAllocation::~OrcRPCAllocation () inline override
Definition at line 54 of file OrcRPCExecutorProcessControl.h.
References assert(), and llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::empty().
Member Function Documentation
deallocate()
template<typename OrcRPCEPCImplT > Error llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >::OrcRPCAllocation::deallocate () inline override virtual
Should deallocate target memory.
Implements llvm::jitlink::JITLinkMemoryManager::Allocation.
Definition at line 131 of file OrcRPCExecutorProcessControl.h.
References llvm::orc::orcrpctpc::toWireProtectionFlags().
finalizeAsync()
template<typename OrcRPCEPCImplT > void llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >::OrcRPCAllocation::finalizeAsync (FinalizeContinuation OnFinalize) inline override virtual
Should transfer from working memory to target memory, and release working memory.
Implements llvm::jitlink::JITLinkMemoryManager::Allocation.
Definition at line 71 of file OrcRPCExecutorProcessControl.h.
References assert(), B, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::dbgs(), DEBUG_WITH_TYPE, llvm::formatv(), llvm::Error::success(), llvm::orc::orcrpctpc::toWireProtectionFlags(), llvm::orc::orcrpctpc::WPF_Exec, llvm::orc::orcrpctpc::WPF_Read, and llvm::orc::orcrpctpc::WPF_Write.
getTargetMemory()
template<typename OrcRPCEPCImplT > JITTargetAddress llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >::OrcRPCAllocation::getTargetMemory (ProtectionFlags Seg) inline override virtual
Should return the final address in the target process where the segment will reside.
Implements llvm::jitlink::JITLinkMemoryManager::Allocation.
Definition at line 65 of file OrcRPCExecutorProcessControl.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
getWorkingMemory()
template<typename OrcRPCEPCImplT > MutableArrayRef< char > llvm::orc::OrcRPCEPCJITLinkMemoryManager< OrcRPCEPCImplT >::OrcRPCAllocation::getWorkingMemory (ProtectionFlags Seg) inline override virtual
Should return the address of linker working memory for the segment with the given protection flags.
Implements llvm::jitlink::JITLinkMemoryManager::Allocation.
Definition at line 58 of file OrcRPCExecutorProcessControl.h.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), and I.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/OrcRPCExecutorProcessControl.h