LLVM: llvm::ThreadPool Class Reference
llvm::ThreadPool Class Reference
A ThreadPool for asynchronous parallel execution on a defined number of threads.
#include "llvm/Support/ThreadPool.h"
Public Types
using TaskTy = std::function<void()>
using PackagedTaskTy = std::packaged_task<void()>
Public Member Functions
ThreadPool (ThreadPoolStrategy S=hardware_concurrency())
Construct a pool using the hardware strategy S for mapping hardware execution resources (threads, cores, CPUs) Defaults to using the maximum execution resources in the system, but accounting for the affinity mask.
~ThreadPool ()
Blocking destructor: the pool will wait for all the threads to complete.
template<typename Function , typename... Args>
std::shared_future< void > async (Function &&F, Args &&... ArgList)
Asynchronous submission of a task to the pool.
template<typename Function >
std::shared_future< void > async (Function &&F)
Asynchronous submission of a task to the pool.
void wait ()
Blocking wait for all the threads to complete and the queue to be empty.
unsigned getThreadCount () const
bool isWorkerThread () const
Returns true if the current thread is a worker thread of this thread pool.
Detailed Description
A ThreadPool for asynchronous parallel execution on a defined number of threads.
The pool keeps a vector of threads alive, waiting on a condition variable for some work to become available.
Definition at line 37 of file ThreadPool.h.
Member Typedef Documentation
PackagedTaskTy
using llvm::ThreadPool::PackagedTaskTy = std::packaged_task<void()>
Definition at line 40 of file ThreadPool.h.
TaskTy
using llvm::ThreadPool::TaskTy = std::function<void()>
Definition at line 39 of file ThreadPool.h.
Constructor & Destructor Documentation
ThreadPool()
ThreadPool::ThreadPool (ThreadPoolStrategy S = hardware_concurrency())
Construct a pool using the hardware strategy S for mapping hardware execution resources (threads, cores, CPUs) Defaults to using the maximum execution resources in the system, but accounting for the affinity mask.
Definition at line 114 of file ThreadPool.cpp.
References llvm::errs().
~ThreadPool()
ThreadPool::~ThreadPool ()
Blocking destructor: the pool will wait for all the threads to complete.
Definition at line 141 of file ThreadPool.cpp.
References wait().
Member Function Documentation
async() [1/2]
template<typename Function > std::shared_future< void > llvm::ThreadPool::async (Function && F) inline
Asynchronous submission of a task to the pool.
The returned future can be used to wait for the task to finish and is non-blocking on destruction.
Definition at line 63 of file ThreadPool.h.
References F.
async() [2/2]
template<typename Function , typename... Args> std::shared_future< void > llvm::ThreadPool::async (Function && F, Args &&... ArgList) inline
Asynchronous submission of a task to the pool.
The returned future can be used to wait for the task to finish and is non-blocking on destruction.
Definition at line 54 of file ThreadPool.h.
References F.
Referenced by llvm::TaskQueue::async(), llvm::DWARFLinker::link(), and llvm::ThinLTOCodeGenerator::run().
getThreadCount()
unsigned llvm::ThreadPool::getThreadCount () const inline
Definition at line 71 of file ThreadPool.h.
isWorkerThread()
bool llvm::ThreadPool::isWorkerThread () const
Returns true if the current thread is a worker thread of this thread pool.
wait()
void ThreadPool::wait ()
Blocking wait for all the threads to complete and the queue to be empty.
It is an error to try to add new tasks while blocking on this call.
Definition at line 122 of file ThreadPool.cpp.
Referenced by llvm::DWARFLinker::link(), llvm::TaskQueue::~TaskQueue(), and ~ThreadPool().
The documentation for this class was generated from the following files:
include/llvm/Support/ThreadPool.h
lib/Support/ThreadPool.cpp