LLVM: llvm::pdb::DbiModuleDescriptor Class Reference
llvm::pdb::DbiModuleDescriptor Class Reference
#include "llvm/DebugInfo/PDB/Native/DbiModuleDescriptor.h"
Public Member Functions
DbiModuleDescriptor ()=default
DbiModuleDescriptor (const DbiModuleDescriptor &Info)=default
DbiModuleDescriptor & operator= (const DbiModuleDescriptor &Info)=default
bool hasECInfo () const
uint16_t getTypeServerIndex () const
uint16_t getModuleStreamIndex () const
uint32_t getSymbolDebugInfoByteSize () const
uint32_t getC11LineInfoByteSize () const
uint32_t getC13LineInfoByteSize () const
uint32_t getNumberOfFiles () const
uint32_t getSourceFileNameIndex () const
uint32_t getPdbFilePathNameIndex () const
StringRef getModuleName () const
StringRef getObjFileName () const
uint32_t getRecordLength () const
const SectionContrib & getSectionContrib () const
Static Public Member Functions
static Error initialize (BinaryStreamRef Stream, DbiModuleDescriptor &Info)
Friends
class DbiStreamBuilder
Detailed Description
Definition at line 23 of file DbiModuleDescriptor.h.
Constructor & Destructor Documentation
DbiModuleDescriptor() [1/2]
llvm::pdb::DbiModuleDescriptor::DbiModuleDescriptor () default
DbiModuleDescriptor() [2/2]
llvm::pdb::DbiModuleDescriptor::DbiModuleDescriptor (const DbiModuleDescriptor & Info) default
Member Function Documentation
getC11LineInfoByteSize()
uint32_t DbiModuleDescriptor::getC11LineInfoByteSize () const
Definition at line 56 of file DbiModuleDescriptor.cpp.
References llvm::pdb::ModuleInfoHeader::C11Bytes.
getC13LineInfoByteSize()
uint32_t DbiModuleDescriptor::getC13LineInfoByteSize () const
Definition at line 60 of file DbiModuleDescriptor.cpp.
References llvm::pdb::ModuleInfoHeader::C13Bytes.
getModuleName()
StringRef DbiModuleDescriptor::getModuleName () const
Definition at line 76 of file DbiModuleDescriptor.cpp.
getModuleStreamIndex()
uint16_t DbiModuleDescriptor::getModuleStreamIndex () const
Definition at line 48 of file DbiModuleDescriptor.cpp.
References llvm::pdb::ModuleInfoHeader::ModDiStream.
Referenced by llvm::pdb::NativeSession::getModuleDebugStream(), and llvm::pdb::ModuleDebugStreamRef::reload().
getNumberOfFiles()
uint32_t DbiModuleDescriptor::getNumberOfFiles () const
Definition at line 64 of file DbiModuleDescriptor.cpp.
References llvm::pdb::ModuleInfoHeader::NumFiles.
getObjFileName()
StringRef DbiModuleDescriptor::getObjFileName () const
Definition at line 78 of file DbiModuleDescriptor.cpp.
getPdbFilePathNameIndex()
uint32_t DbiModuleDescriptor::getPdbFilePathNameIndex () const
Definition at line 72 of file DbiModuleDescriptor.cpp.
References llvm::pdb::ModuleInfoHeader::PdbFilePathNI.
getRecordLength()
uint32_t DbiModuleDescriptor::getRecordLength () const
Definition at line 80 of file DbiModuleDescriptor.cpp.
References llvm::alignTo(), Size, and llvm::StringRef::str().
getSectionContrib()
const SectionContrib & DbiModuleDescriptor::getSectionContrib () const
Definition at line 44 of file DbiModuleDescriptor.cpp.
References llvm::pdb::ModuleInfoHeader::SC.
getSourceFileNameIndex()
uint32_t DbiModuleDescriptor::getSourceFileNameIndex () const
Definition at line 68 of file DbiModuleDescriptor.cpp.
References llvm::pdb::ModuleInfoHeader::SrcFileNameNI.
getSymbolDebugInfoByteSize()
uint32_t DbiModuleDescriptor::getSymbolDebugInfoByteSize () const
Definition at line 52 of file DbiModuleDescriptor.cpp.
References llvm::pdb::ModuleInfoHeader::SymBytes.
getTypeServerIndex()
uint16_t DbiModuleDescriptor::getTypeServerIndex () const
Definition at line 39 of file DbiModuleDescriptor.cpp.
References llvm::pdb::ModuleInfoHeader::Flags, llvm::pdb::ModInfoFlags::TypeServerIndexMask, and llvm::pdb::ModInfoFlags::TypeServerIndexShift.
hasECInfo()
bool DbiModuleDescriptor::hasECInfo () const
Definition at line 35 of file DbiModuleDescriptor.cpp.
References llvm::pdb::ModuleInfoHeader::Flags, and llvm::pdb::ModInfoFlags::HasECFlagMask.
initialize()
Error DbiModuleDescriptor::initialize (BinaryStreamRef Stream, DbiModuleDescriptor & Info) static
Definition at line 21 of file DbiModuleDescriptor.cpp.
References llvm::BinaryStreamReader::readCString(), llvm::BinaryStreamReader::readObject(), and llvm::Error::success().
Referenced by llvm::VarStreamArrayExtractor< pdb::DbiModuleDescriptor >::operator()().
operator=()
DbiModuleDescriptor & llvm::pdb::DbiModuleDescriptor::operator= (const DbiModuleDescriptor & Info) default
Friends And Related Symbol Documentation
DbiStreamBuilder
friend class DbiStreamBuilder friend
Definition at line 24 of file DbiModuleDescriptor.h.
The documentation for this class was generated from the following files:
include/llvm/DebugInfo/PDB/Native/DbiModuleDescriptor.h
lib/DebugInfo/PDB/Native/DbiModuleDescriptor.cpp