LLVM: llvm::orc::shared::SerializationTraits< ChannelT, tpctypes::BufferWrite, tpctypes::BufferWrite, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > > Class Template Reference
llvm::orc::shared::SerializationTraits< ChannelT, tpctypes::BufferWrite, tpctypes::BufferWrite, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > > Class Template Reference
#include "llvm/ExecutionEngine/Orc/TargetProcess/OrcRPCTPCServer.h"
Static Public Member Functions
static Error serialize (ChannelT &C, const tpctypes::BufferWrite &W)
static Error deserialize (ChannelT &C, tpctypes::BufferWrite &W)
Detailed Description
template<typename ChannelT>
class llvm::orc::shared::SerializationTraits< ChannelT, tpctypes::BufferWrite, tpctypes::BufferWrite, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >
Definition at line 203 of file OrcRPCTPCServer.h.
Member Function Documentation
deserialize()
template<typename ChannelT > static Error llvm::orc::shared::SerializationTraits< ChannelT, tpctypes::BufferWrite, tpctypes::BufferWrite, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::deserialize (ChannelT & C, tpctypes::BufferWrite & W) inline static
Definition at line 214 of file OrcRPCTPCServer.h.
References llvm::Address, C, llvm::orc::shared::deserializeSeq(), Size, and llvm::Error::success().
serialize()
template<typename ChannelT > static Error llvm::orc::shared::SerializationTraits< ChannelT, tpctypes::BufferWrite, tpctypes::BufferWrite, std::enable_if_t< std::is_base_of< RawByteChannel, ChannelT >::value > >::serialize (ChannelT & C, const tpctypes::BufferWrite & W) inline static
Definition at line 207 of file OrcRPCTPCServer.h.
References C, llvm::orc::shared::serializeSeq(), and Size.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/TargetProcess/OrcRPCTPCServer.h