LLVM: llvm::UnOpInit Class Reference
llvm::UnOpInit Class Reference
!op (X) - Transform an init.
#include "llvm/TableGen/Record.h"
Public Types
enum UnaryOp : uint8_t {
CAST , NOT , HEAD , TAIL ,
SIZE , EMPTY , GETDAGOP
}
Public Member Functions
UnOpInit (const UnOpInit &)=delete
UnOpInit & operator= (const UnOpInit &)=delete
void Profile (FoldingSetNodeID &ID) const
OpInit * clone (ArrayRef< Init * > Operands) const override
unsigned getNumOperands () const override
Init * getOperand (unsigned i) const override
UnaryOp getOpcode () const
Init * getOperand () const
Init * Fold (Record *CurRec, bool IsFinal=false) const
Init * resolveReferences (Resolver &R) const override
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
std::string getAsString () const override
Convert this value to a literal form.
Public Member Functions inherited from llvm::OpInit
OpInit (const OpInit &)=delete
OpInit & operator= (OpInit &)=delete
Init * getBit (unsigned Bit) const override
Get the Init value of the specified bit.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Get the type of the Init as a RecTy.
Init * getCastTo (RecTy *Ty) const override
If this value is convertible to type Ty, return a value whose type is Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to a value whose type is Ty, or return null if this is not possible.
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This function is used to implement the bit range selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This function is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Get the kind (type) of the value.
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
Is this a complete value with no unset (uninitialized) subvalues?
virtual bool isConcrete () const
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
void print (raw_ostream &OS) const
Print this value.
virtual std::string getAsUnquotedString () const
Convert this value to a literal form, without adding quotes around a string.
void dump () const
Debugging method that may be called through a debugger; just invokes print on stderr.
Public Member Functions inherited from llvm::FoldingSetBase::Node
Node ()=default
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const Init *I)
static UnOpInit * get (UnaryOp opc, Init *lhs, RecTy *Type)
Static Public Member Functions inherited from llvm::OpInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_DagInit , IK_DefInit , IK_FieldInit , IK_IntInit ,
IK_ListInit , IK_FirstOpInit , IK_BinOpInit , IK_TernOpInit ,
IK_UnOpInit , IK_LastOpInit , IK_CondOpInit , IK_FoldOpInit ,
IK_IsAOpInit , IK_AnonymousNameInit , IK_StringInit , IK_VarInit ,
IK_VarListElementInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::OpInit
OpInit (InitKind K, RecTy *Type, uint8_t Opc)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
!op (X) - Transform an init.
Definition at line 757 of file Record.h.
Member Enumeration Documentation
UnaryOp
enum llvm::UnOpInit::UnaryOp : uint8_t
Enumerator
CAST
NOT
HEAD
TAIL
SIZE
EMPTY
GETDAGOP
Definition at line 759 of file Record.h.
Constructor & Destructor Documentation
UnOpInit()
llvm::UnOpInit::UnOpInit (const UnOpInit &) delete
Member Function Documentation
classof()
static bool llvm::UnOpInit::classof (const Init * I) inline static
Definition at line 771 of file Record.h.
References I, and llvm::Init::IK_UnOpInit.
clone()
OpInit * llvm::UnOpInit::clone (ArrayRef< Init * > Operands) const inline override virtual
Implements llvm::OpInit.
Definition at line 780 of file Record.h.
References assert(), get(), getOpcode(), llvm::TypedInit::getType(), and Operands.
Fold()
Init * UnOpInit::Fold (Record * CurRec, bool IsFinal = false) const
Definition at line 717 of file Record.cpp.
References assert(), CAST, D, EMPTY, llvm::IntRecTy::get(), llvm::ListInit::get(), llvm::IntInit::get(), llvm::DefInit::get(), llvm::StringInit::get(), llvm::RecTy::getAsString(), getAsString(), GETDAGOP, llvm::RecordKeeper::getDef(), llvm::Record::getLoc(), llvm::Record::getNameInit(), getOpcode(), llvm::Record::getRecords(), llvm::TypedInit::getType(), HEAD, Name, NOT, llvm::PrintFatalError(), SIZE, TAIL, and llvm::RecTy::typeIsA().
get()
UnOpInit * UnOpInit::get (UnaryOp opc, Init * lhs, RecTy * Type) static
Definition at line 698 of file Record.cpp.
References Allocator, I, llvm::Init::Opc, and ProfileUnOpInit().
Referenced by clone(), llvm::TypedInit::getCastTo(), and resolveReferences().
getAsString()
std::string UnOpInit::getAsString () const override virtual
Convert this value to a literal form.
Implements llvm::Init.
Definition at line 840 of file Record.cpp.
References CAST, EMPTY, llvm::RecTy::getAsString(), GETDAGOP, getOpcode(), llvm::TypedInit::getType(), HEAD, NOT, SIZE, and TAIL.
Referenced by Fold().
getNumOperands()
unsigned llvm::UnOpInit::getNumOperands () const inline override virtual
Implements llvm::OpInit.
Definition at line 786 of file Record.h.
getOpcode()
UnaryOp llvm::UnOpInit::getOpcode () const inline
Definition at line 793 of file Record.h.
References llvm::Init::Opc.
Referenced by clone(), Fold(), getAsString(), Profile(), and resolveReferences().
getOperand() [1/2]
Init * llvm::UnOpInit::getOperand () const inline
Definition at line 794 of file Record.h.
Referenced by getOperand(), and Profile().
getOperand() [2/2]
Init * llvm::UnOpInit::getOperand (unsigned i) const inline override virtual
Implements llvm::OpInit.
Definition at line 788 of file Record.h.
References assert(), and getOperand().
operator=()
UnOpInit & llvm::UnOpInit::operator= (const UnOpInit &) delete
Profile()
void UnOpInit::Profile (FoldingSetNodeID & ID) const
Definition at line 713 of file Record.cpp.
References getOpcode(), getOperand(), llvm::TypedInit::getType(), and ProfileUnOpInit().
resolveReferences()
Init * UnOpInit::resolveReferences (Resolver & R) const override virtual
This function is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 831 of file Record.cpp.
References CAST, get(), getOpcode(), and llvm::TypedInit::getType().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp