LLVM: llvm::ArgumentPromotionPass Class Reference
llvm::ArgumentPromotionPass Class Reference
Argument promotion pass.
#include "llvm/Transforms/IPO/ArgumentPromotion.h"
Public Member Functions
ArgumentPromotionPass (unsigned MaxElements=3u)
PreservedAnalyses run (LazyCallGraph::SCC &C, CGSCCAnalysisManager &AM, LazyCallGraph &CG, CGSCCUpdateResult &UR)
Static Public Member Functions
static bool areFunctionArgsABICompatible (const Function &F, const TargetTransformInfo &TTI, SmallPtrSetImpl< Argument * > &ArgsToPromote, SmallPtrSetImpl< Argument * > &ByValArgsToTransform)
Check if callers and the callee F agree how promoted arguments would be passed.
static bool isDenselyPacked (Type *type, const DataLayout &DL)
Checks if a type could have padding bytes.
Static Public Member Functions inherited from llvm::PassInfoMixin< ArgumentPromotionPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Argument promotion pass.
This pass walks the functions in each SCC and for each one tries to transform it and all of its callers to replace indirect arguments with direct (by-value) arguments.
Definition at line 24 of file ArgumentPromotion.h.
Constructor & Destructor Documentation
ArgumentPromotionPass()
llvm::ArgumentPromotionPass::ArgumentPromotionPass (unsigned MaxElements = 3u) inline
Definition at line 28 of file ArgumentPromotion.h.
Member Function Documentation
areFunctionArgsABICompatible()
bool ArgumentPromotionPass::areFunctionArgsABICompatible (const Function & F, const TargetTransformInfo & TTI, SmallPtrSetImpl< Argument * > & ArgsToPromote, SmallPtrSetImpl< Argument * > & ByValArgsToTransform) static
Check if callers and the callee F agree how promoted arguments would be passed.
The ones that they do not agree on are eliminated from the sets but the return value has to be observed as well.
Definition at line 837 of file ArgumentPromotion.cpp.
References llvm::TargetTransformInfo::areFunctionArgsABICompatible(), Callee, F, llvm::CallBase::getCalledFunction(), and llvm::CallBase::getCaller().
Referenced by promoteArguments(), and AAPrivatizablePtrArgument::updateImpl().
isDenselyPacked()
bool ArgumentPromotionPass::isDenselyPacked (Type * type, const DataLayout & DL) static
Checks if a type could have padding bytes.
Definition at line 765 of file ArgumentPromotion.cpp.
References DL, E, llvm::StructLayout::getElementOffsetInBits(), and isDenselyPacked().
Referenced by isDenselyPacked(), promoteArguments(), and AAPrivatizablePtrArgument::updateImpl().
run()
PreservedAnalyses ArgumentPromotionPass::run (LazyCallGraph::SCC & C, CGSCCAnalysisManager & AM, LazyCallGraph & CG, CGSCCUpdateResult & UR)
Definition at line 1011 of file ArgumentPromotion.cpp.
References llvm::PreservedAnalyses::all(), assert(), C, CG, Changed, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::clear(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), N, llvm::None, llvm::PreservedAnalyses::none(), and promoteArguments().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/ArgumentPromotion.h
lib/Transforms/IPO/ArgumentPromotion.cpp