LLVM: llvm::MemoryDependenceResults Class Reference
llvm::MemoryDependenceResults Class Reference
Provides a lazy, caching interface for making common memory aliasing information queries, backed by LLVM's alias analysis passes.
#include "llvm/Analysis/MemoryDependenceAnalysis.h"
Public Types
using NonLocalDepInfo = std::vector<NonLocalDepEntry>
Public Member Functions
MemoryDependenceResults (AAResults &AA, AssumptionCache &AC, const TargetLibraryInfo &TLI, DominatorTree &DT, PhiValues &PV, unsigned DefaultBlockScanLimit)
bool invalidate (Function &F, const PreservedAnalyses &PA, FunctionAnalysisManager::Invalidator &Inv)
Handle invalidation in the new PM.
unsigned getDefaultBlockScanLimit () const
Some methods limit the number of instructions they will examine.
MemDepResult getDependency (Instruction *QueryInst)
Returns the instruction on which a memory operation depends.
const NonLocalDepInfo & getNonLocalCallDependency (CallBase *QueryCall)
Perform a full dependency query for the specified call, returning the set of blocks that the value is potentially live across.
void getNonLocalPointerDependency (Instruction *QueryInst, SmallVectorImpl< NonLocalDepResult > &Result)
Perform a full dependency query for an access to the QueryInst's specified memory location, returning the set of instructions that either define or clobber the value.
void removeInstruction (Instruction *InstToRemove)
Removes an instruction from the dependence analysis, updating the dependence of instructions that previously depended on it.
void invalidateCachedPointerInfo (Value *Ptr)
Invalidates cached information about the specified pointer, because it may be too conservative in memdep.
void invalidateCachedPredecessors ()
Clears the PredIteratorCache info.
MemDepResult getPointerDependencyFrom (const MemoryLocation &Loc, bool isLoad, BasicBlock::iterator ScanIt, BasicBlock *BB, Instruction *QueryInst=nullptr, unsigned *Limit=nullptr)
Returns the instruction on which a memory location depends.
MemDepResult getPointerDependencyFrom (const MemoryLocation &Loc, bool isLoad, BasicBlock::iterator ScanIt, BasicBlock *BB, Instruction *QueryInst, unsigned *Limit, BatchAAResults &BatchAA)
MemDepResult getSimplePointerDependencyFrom (const MemoryLocation &MemLoc, bool isLoad, BasicBlock::iterator ScanIt, BasicBlock *BB, Instruction *QueryInst, unsigned *Limit, BatchAAResults &BatchAA)
MemDepResult getInvariantGroupPointerDependency (LoadInst *LI, BasicBlock *BB)
This analysis looks for other loads and stores with invariant.group metadata and the same pointer operand.
void releaseMemory ()
Release memory in caches.
Optional< int32_t > getClobberOffset (LoadInst *DepInst) const
Return the clobber offset to dependent instruction.
Detailed Description
Provides a lazy, caching interface for making common memory aliasing information queries, backed by LLVM's alias analysis passes.
The dependency information returned is somewhat unusual, but is pragmatic. If queried about a store or call that might modify memory, the analysis will return the instruction[s] that may either load from that memory or store to it. If queried with a load or call that can never modify memory, the analysis will return calls and stores that might modify the pointer, but generally does not return loads unless a) they are volatile, or b) they load from must-aliased pointers. Returning a dependence on must-alias'd pointers instead of all pointers interacts well with the internal caching mechanism.
Definition at line 264 of file MemoryDependenceAnalysis.h.
Member Typedef Documentation
NonLocalDepInfo
using llvm::MemoryDependenceResults::NonLocalDepInfo = std::vector<NonLocalDepEntry>
Definition at line 270 of file MemoryDependenceAnalysis.h.
Constructor & Destructor Documentation
MemoryDependenceResults()
llvm::MemoryDependenceResults::MemoryDependenceResults (AAResults & AA, AssumptionCache & AC, const TargetLibraryInfo & TLI, DominatorTree & DT, PhiValues & PV, unsigned DefaultBlockScanLimit) inline
Definition at line 360 of file MemoryDependenceAnalysis.h.
Member Function Documentation
getClobberOffset()
Optional< int32_t > llvm::MemoryDependenceResults::getClobberOffset (LoadInst * DepInst) const inline
Return the clobber offset to dependent instruction.
Definition at line 472 of file MemoryDependenceAnalysis.h.
References llvm::None.
getDefaultBlockScanLimit()
unsigned MemoryDependenceResults::getDefaultBlockScanLimit () const
Some methods limit the number of instructions they will examine.
The return value of this method is the default limit that will be used if no limit is explicitly passed in.
Definition at line 1795 of file MemoryDependenceAnalysis.cpp.
Referenced by getSimplePointerDependencyFrom().
getDependency()
MemDepResult MemoryDependenceResults::getDependency (Instruction * QueryInst)
Returns the instruction on which a memory operation depends.
See the class comment for more details. It is illegal to call this on non-memory instructions.
Definition at line 645 of file MemoryDependenceAnalysis.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::clear(), llvm::ilist_node_impl< OptionsT >::getIterator(), GetLocation(), llvm::MemDepResult::getNonFuncLocal(), llvm::MemDepResult::getNonLocal(), getPointerDependencyFrom(), llvm::MemDepResult::getUnknown(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), isLoad(), llvm::isModSet(), llvm::AAResults::onlyReadsMemory(), and RemoveFromReverseMap().
Referenced by getNonLocalCallDependency().
getInvariantGroupPointerDependency()
MemDepResult MemoryDependenceResults::getInvariantGroupPointerDependency (LoadInst * LI, BasicBlock * BB)
This analysis looks for other loads and stores with invariant.group metadata and the same pointer operand.
Returns Unknown if it does not find anything, and Def if it can be assumed that 2 instructions load or store the same value and NonLocal which indicate that non-local Def was found, which can be retrieved by calling getNonLocalPointerDependency with the same queried instruction.
Definition at line 283 of file MemoryDependenceAnalysis.cpp.
References assert(), llvm::DominatorTree::dominates(), GEP, llvm::MemDepResult::getDef(), llvm::MemDepResult::getNonLocal(), llvm::LoadInst::getPointerOperand(), llvm::getPointerOperand(), llvm::MemDepResult::getUnknown(), llvm::Instruction::hasMetadata(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::Other, llvm::Value::stripPointerCasts(), and llvm::Value::uses().
Referenced by getPointerDependencyFrom().
getNonLocalCallDependency()
const MemoryDependenceResults::NonLocalDepInfo & MemoryDependenceResults::getNonLocalCallDependency (CallBase * QueryCall)
Perform a full dependency query for the specified call, returning the set of blocks that the value is potentially live across.
The returned set of results will include a "NonLocal" result for all blocks where the value is live across.
This method assumes the instruction returns a "NonLocal" dependency within its own block.
This returns a reference to an internal data structure that may be invalidated on the next non-local query or when an instruction is removed. Clients must copy this data if they want it around longer than that.
Definition at line 716 of file MemoryDependenceAnalysis.cpp.
References llvm::append_range(), assert(), AssertSorted(), llvm::PredIteratorCache::get(), getDependency(), llvm::MemDepResult::getInst(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::MemDepResult::getNonFuncLocal(), llvm::MemDepResult::getNonLocal(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::MemDepResult::isNonLocal(), LLVM_DEBUG, llvm::AAResults::onlyReadsMemory(), and llvm::sort().
getNonLocalPointerDependency()
void MemoryDependenceResults::getNonLocalPointerDependency (Instruction * QueryInst, SmallVectorImpl< NonLocalDepResult > & Result)
Perform a full dependency query for an access to the QueryInst's specified memory location, returning the set of instructions that either define or clobber the value.
Warning: For a volatile query instruction, the dependencies will be accurate, and thus usable for reordering, but it is never legal to remove the query instruction.
This method assumes the pointer has a "NonLocal" dependency within QueryInst's parent basic block.
Definition at line 842 of file MemoryDependenceAnalysis.cpp.
References llvm::Address, assert(), DL, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::MemoryLocation::get(), llvm::Module::getDataLayout(), llvm::BasicBlock::getModule(), llvm::MemDepResult::getUnknown(), isLoad(), isOrdered(), and SI.
getPointerDependencyFrom() [1/2]
MemDepResult MemoryDependenceResults::getPointerDependencyFrom (const MemoryLocation & Loc, bool isLoad, BasicBlock::iterator ScanIt, BasicBlock * BB, Instruction * QueryInst, unsigned * Limit, BatchAAResults & BatchAA)
Definition at line 246 of file MemoryDependenceAnalysis.cpp.
References assert(), getInvariantGroupPointerDependency(), getSimplePointerDependencyFrom(), llvm::MemDepResult::getUnknown(), and isLoad().
getPointerDependencyFrom() [2/2]
MemDepResult MemoryDependenceResults::getPointerDependencyFrom (const MemoryLocation & Loc, bool isLoad, BasicBlock::iterator ScanIt, BasicBlock * BB, Instruction * QueryInst = nullptr, unsigned * Limit = nullptr)
Returns the instruction on which a memory location depends.
If isLoad is true, this routine ignores may-aliases with read-only operations. If isLoad is false, this routine ignores may-aliases with reads from read-only locations. If possible, pass the query instruction as well; this function may take advantage of the metadata annotated to the query instruction to refine the result. Limit can be used to set the maximum number of instructions that will be examined to find the pointer dependency. On return, it will be set to the number of instructions left to examine. If a null pointer is passed in, the limit will default to the value of -memdep-block-scan-limit.
Note that this is an uncached query, and thus may be inefficient.
Definition at line 274 of file MemoryDependenceAnalysis.cpp.
References getPointerDependencyFrom(), and isLoad().
Referenced by getDependency(), and getPointerDependencyFrom().
getSimplePointerDependencyFrom()
MemDepResult MemoryDependenceResults::getSimplePointerDependencyFrom (const MemoryLocation & MemLoc, bool isLoad, BasicBlock::iterator ScanIt, BasicBlock * BB, Instruction * QueryInst, unsigned * Limit, BatchAAResults & BatchAA)
Definition at line 369 of file MemoryDependenceAnalysis.cpp.
References llvm::BatchAAResults::alias(), llvm::BasicBlock::begin(), llvm::BatchAAResults::callCapturesBefore(), llvm::clearMust(), llvm::MemoryLocation::get(), llvm::MemoryLocation::getAfter(), llvm::MemDepResult::getClobber(), llvm::MemDepResult::getDef(), getDefaultBlockScanLimit(), llvm::Function::getEntryBlock(), GetLocation(), llvm::BatchAAResults::getModRefInfo(), llvm::MemDepResult::getNonFuncLocal(), llvm::MemDepResult::getNonLocal(), llvm::BasicBlock::getParent(), llvm::getUnderlyingObject(), llvm::MemDepResult::getUnknown(), llvm::Instruction::hasMetadata(), I, isLoad(), llvm::isModAndRefSet(), llvm::isModOrRefSet(), llvm::BatchAAResults::isMustAlias(), llvm::isNoAliasFn(), llvm::isStrongerThanUnordered(), LLVM_FALLTHROUGH, llvm::Mod, llvm::Monotonic, llvm::AliasResult::MustAlias, llvm::AliasResult::NoAlias, llvm::NoModRef, llvm::AliasResult::PartialAlias, llvm::BatchAAResults::pointsToConstantMemory(), llvm::Ref, llvm::Release, and SI.
Referenced by getPointerDependencyFrom().
invalidate()
bool MemoryDependenceResults::invalidate (Function & F, const PreservedAnalyses & PA, FunctionAnalysisManager::Invalidator & Inv)
Handle invalidation in the new PM.
Definition at line 1776 of file MemoryDependenceAnalysis.cpp.
References F, llvm::PreservedAnalyses::getChecker(), and llvm::AnalysisManager< IRUnitT, ExtraArgTs >::Invalidator::invalidate().
invalidateCachedPointerInfo()
void MemoryDependenceResults::invalidateCachedPointerInfo (Value * Ptr)
Invalidates cached information about the specified pointer, because it may be too conservative in memdep.
This is an optional call that can be used when the client detects an equivalence between the pointer and some other value and replaces the other value with ptr. This can make Ptr available in more places that cached info does not necessarily keep.
Definition at line 1498 of file MemoryDependenceAnalysis.cpp.
References llvm::Value::getType(), llvm::PhiValues::invalidateValue(), and llvm::Type::isPointerTy().
invalidateCachedPredecessors()
void MemoryDependenceResults::invalidateCachedPredecessors ()
Clears the PredIteratorCache info.
This needs to be done when the CFG changes, e.g., due to splitting critical edges.
Definition at line 1510 of file MemoryDependenceAnalysis.cpp.
References llvm::PredIteratorCache::clear().
releaseMemory()
void llvm::MemoryDependenceResults::releaseMemory ()
Release memory in caches.
removeInstruction()
void MemoryDependenceResults::removeInstruction (Instruction * InstToRemove)
Removes an instruction from the dependence analysis, updating the dependence of instructions that previously depended on it.
Definition at line 1514 of file MemoryDependenceAnalysis.cpp.
References assert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::count(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::ilist_node_impl< OptionsT >::getIterator(), llvm::Value::getType(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::insert(), llvm::PhiValues::invalidateValue(), llvm::Type::isPointerTy(), llvm::Instruction::isTerminator(), LLVM_DEBUG, P, RemoveFromReverseMap(), and llvm::sort().
Referenced by llvm::FoldSingleEntryPHINodes(), and llvm::gvn::AvailableValue::MaterializeAdjustedValue().
The documentation for this class was generated from the following files:
include/llvm/Analysis/MemoryDependenceAnalysis.h
lib/Analysis/MemoryDependenceAnalysis.cpp