LLVM: llvm::orc::shared::SerializationTraits< ChannelT, Error > Class Template Reference
llvm::orc::shared::SerializationTraits< ChannelT, Error > Class Template Reference
#include "llvm/ExecutionEngine/Orc/Shared/Serialization.h"
Public Types
using WrappedErrorSerializer
using WrappedErrorDeserializer
Static Public Member Functions
template<typename ErrorInfoT , typename SerializeFtor , typename DeserializeFtor >
static void registerErrorType (std::string Name, SerializeFtor Serialize, DeserializeFtor Deserialize)
static Error serialize (ChannelT &C, Error &&Err)
static Error deserialize (ChannelT &C, Error &Err)
Detailed Description
template<typename ChannelT>
class llvm::orc::shared::SerializationTraits< ChannelT, Error >
Definition at line 317 of file Serialization.h.
Member Typedef Documentation
WrappedErrorDeserializer
template<typename ChannelT > using llvm::orc::shared::SerializationTraits< ChannelT, Error >::WrappedErrorDeserializer
Initial value:
      std::function<Error(ChannelT &C, Error &Err)>
Definition at line 322 of file Serialization.h.
WrappedErrorSerializer
template<typename ChannelT > using llvm::orc::shared::SerializationTraits< ChannelT, Error >::WrappedErrorSerializer
Initial value:
      std::function<Error(ChannelT &C, const ErrorInfoBase &)>
Definition at line 319 of file Serialization.h.
Member Function Documentation
deserialize()
template<typename ChannelT > static Error llvm::orc::shared::SerializationTraits< ChannelT, Error >::deserialize (ChannelT & C, Error & Err) inline static
Definition at line 374 of file Serialization.h.
References assert(), C, llvm::orc::shared::deserializeSeq(), llvm::Lock, and llvm::Error::success().
registerErrorType()
template<typename ChannelT > template<typename ErrorInfoT , typename SerializeFtor , typename DeserializeFtor > static void llvm::orc::shared::SerializationTraits< ChannelT, Error >::registerErrorType (std::string Name, SerializeFtor Serialize, DeserializeFtor Deserialize) inline static
Definition at line 327 of file Serialization.h.
References assert(), C, I, llvm::Lock, Name, and llvm::orc::shared::serializeSeq().
serialize()
template<typename ChannelT > static Error llvm::orc::shared::SerializationTraits< ChannelT, Error >::serialize (ChannelT & C, Error && Err) inline static
Definition at line 360 of file Serialization.h.
References C, llvm::handleErrors(), llvm::Lock, llvm::orc::shared::serializeSeq(), and SI.
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/Shared/Serialization.h