LLVM: llvm::SystemZSubtarget Class Reference
llvm::SystemZSubtarget Class Reference
#include "Target/SystemZ/SystemZSubtarget.h"
Public Member Functions
SystemZSubtarget (const Triple &TT, const std::string &CPU, const std::string &FS, const TargetMachine &TM)
~SystemZSubtarget ()
SystemZCallingConventionRegisters * getSpecialRegisters () const
const TargetFrameLowering * getFrameLowering () const override
const SystemZInstrInfo * getInstrInfo () const override
const SystemZRegisterInfo * getRegisterInfo () const override
const SystemZTargetLowering * getTargetLowering () const override
const SelectionDAGTargetInfo * getSelectionDAGInfo () const override
bool enableMachineScheduler () const override
bool useAA () const override
bool enableEarlyIfConversion () const override
bool enableSubRegLiveness () const override
void ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
bool hasDistinctOps () const
bool hasLoadStoreOnCond () const
bool hasLoadStoreOnCond2 () const
bool hasHighWord () const
bool hasFPExtension () const
bool hasPopulationCount () const
bool hasMessageSecurityAssist3 () const
bool hasMessageSecurityAssist4 () const
bool hasResetReferenceBitsMultiple () const
bool hasFastSerialization () const
bool hasInterlockedAccess1 () const
bool hasMiscellaneousExtensions () const
bool hasExecutionHint () const
bool hasLoadAndTrap () const
bool hasTransactionalExecution () const
bool hasProcessorAssist () const
bool hasDFPZonedConversion () const
bool hasEnhancedDAT2 () const
bool hasLoadAndZeroRightmostByte () const
bool hasMessageSecurityAssist5 () const
bool hasDFPPackedConversion () const
bool hasVector () const
bool hasMiscellaneousExtensions2 () const
bool hasGuardedStorage () const
bool hasMessageSecurityAssist7 () const
bool hasMessageSecurityAssist8 () const
bool hasVectorEnhancements1 () const
bool hasVectorPackedDecimal () const
bool hasInsertReferenceBitsMultiple () const
bool hasMiscellaneousExtensions3 () const
bool hasMessageSecurityAssist9 () const
bool hasVectorEnhancements2 () const
bool hasVectorPackedDecimalEnhancement () const
bool hasEnhancedSort () const
bool hasDeflateConversion () const
bool hasVectorPackedDecimalEnhancement2 () const
bool hasNNPAssist () const
bool hasBEAREnhancement () const
bool hasResetDATProtection () const
bool hasProcessorActivityInstrumentation () const
bool hasSoftFloat () const
bool isPC32DBLSymbol (const GlobalValue *GV, CodeModel::Model CM) const
bool isTargetELF () const
bool isTargetGOFF () const
bool isTargetXPLINK64 () const
bool isTargetzOS () const
Protected Attributes
bool HasDistinctOps
bool HasLoadStoreOnCond
bool HasHighWord
bool HasFPExtension
bool HasPopulationCount
bool HasMessageSecurityAssist3
bool HasMessageSecurityAssist4
bool HasResetReferenceBitsMultiple
bool HasFastSerialization
bool HasInterlockedAccess1
bool HasMiscellaneousExtensions
bool HasExecutionHint
bool HasLoadAndTrap
bool HasTransactionalExecution
bool HasProcessorAssist
bool HasDFPZonedConversion
bool HasEnhancedDAT2
bool HasVector
bool HasLoadStoreOnCond2
bool HasLoadAndZeroRightmostByte
bool HasMessageSecurityAssist5
bool HasDFPPackedConversion
bool HasMiscellaneousExtensions2
bool HasGuardedStorage
bool HasMessageSecurityAssist7
bool HasMessageSecurityAssist8
bool HasVectorEnhancements1
bool HasVectorPackedDecimal
bool HasInsertReferenceBitsMultiple
bool HasMiscellaneousExtensions3
bool HasMessageSecurityAssist9
bool HasVectorEnhancements2
bool HasVectorPackedDecimalEnhancement
bool HasEnhancedSort
bool HasDeflateConversion
bool HasVectorPackedDecimalEnhancement2
bool HasNNPAssist
bool HasBEAREnhancement
bool HasResetDATProtection
bool HasProcessorActivityInstrumentation
bool HasSoftFloat
Detailed Description
Definition at line 33 of file SystemZSubtarget.h.
Constructor & Destructor Documentation
SystemZSubtarget()
SystemZSubtarget::SystemZSubtarget (const Triple & TT, const std::string & CPU, const std::string & FS, const TargetMachine & TM)
Definition at line 66 of file SystemZSubtarget.cpp.
~SystemZSubtarget()
SystemZSubtarget::~SystemZSubtarget ()
Definition at line 94 of file SystemZSubtarget.cpp.
References getSpecialRegisters().
Member Function Documentation
enableEarlyIfConversion()
bool llvm::SystemZSubtarget::enableEarlyIfConversion () const inline override
Definition at line 124 of file SystemZSubtarget.h.
enableMachineScheduler()
bool llvm::SystemZSubtarget::enableMachineScheduler () const inline override
Definition at line 118 of file SystemZSubtarget.h.
enableSubRegLiveness()
bool SystemZSubtarget::enableSubRegLiveness () const override
Definition at line 96 of file SystemZSubtarget.cpp.
References UseSubRegLiveness.
getFrameLowering()
const TargetFrameLowering * llvm::SystemZSubtarget::getFrameLowering () const inline override
Definition at line 101 of file SystemZSubtarget.h.
Referenced by llvm::SystemZTargetLowering::getStackProbeSize(), and llvm::SystemZTargetLowering::LowerFormalArguments().
getInstrInfo()
const SystemZInstrInfo * llvm::SystemZSubtarget::getInstrInfo () const inline override
Definition at line 104 of file SystemZSubtarget.h.
Referenced by llvm::SystemZFrameLowering::emitPrologue(), llvm::SystemZTTIImpl::getIntImmCostInst(), and llvm::SystemZVectorConstantInfo::isVectorConstantLegal().
getRegisterInfo()
const SystemZRegisterInfo * llvm::SystemZSubtarget::getRegisterInfo () const inline override
Definition at line 105 of file SystemZSubtarget.h.
Referenced by llvm::SystemZRegisterInfo::getRegAllocationHints(), llvm::SystemZTargetLowering::LowerCall(), and llvm::SystemZTargetLowering::SystemZTargetLowering().
getSelectionDAGInfo()
const SelectionDAGTargetInfo * llvm::SystemZSubtarget::getSelectionDAGInfo () const inline override
Definition at line 111 of file SystemZSubtarget.h.
getSpecialRegisters()
SystemZCallingConventionRegisters * llvm::SystemZSubtarget::getSpecialRegisters () const inline
Definition at line 96 of file SystemZSubtarget.h.
References assert().
Referenced by llvm::SystemZRegisterInfo::getCalleeSavedRegs(), llvm::SystemZRegisterInfo::getCallPreservedMask(), llvm::SystemZRegisterInfo::getFrameRegister(), llvm::SystemZRegisterInfo::getReservedRegs(), and ~SystemZSubtarget().
getTargetLowering()
const SystemZTargetLowering * llvm::SystemZSubtarget::getTargetLowering () const inline override
Definition at line 108 of file SystemZSubtarget.h.
Referenced by llvm::SystemZFrameLowering::emitPrologue(), and llvm::SystemZFrameLowering::inlineStackProbe().
hasBEAREnhancement()
bool llvm::SystemZSubtarget::hasBEAREnhancement () const inline
Definition at line 268 of file SystemZSubtarget.h.
References HasBEAREnhancement.
hasDeflateConversion()
bool llvm::SystemZSubtarget::hasDeflateConversion () const inline
Definition at line 256 of file SystemZSubtarget.h.
References HasDeflateConversion.
hasDFPPackedConversion()
bool llvm::SystemZSubtarget::hasDFPPackedConversion () const inline
Definition at line 202 of file SystemZSubtarget.h.
References HasDFPPackedConversion.
hasDFPZonedConversion()
bool llvm::SystemZSubtarget::hasDFPZonedConversion () const inline
Definition at line 187 of file SystemZSubtarget.h.
References HasDFPZonedConversion.
hasDistinctOps()
bool llvm::SystemZSubtarget::hasDistinctOps () const inline
Definition at line 133 of file SystemZSubtarget.h.
References HasDistinctOps.
hasEnhancedDAT2()
bool llvm::SystemZSubtarget::hasEnhancedDAT2 () const inline
Definition at line 190 of file SystemZSubtarget.h.
References HasEnhancedDAT2.
hasEnhancedSort()
bool llvm::SystemZSubtarget::hasEnhancedSort () const inline
Definition at line 253 of file SystemZSubtarget.h.
References HasEnhancedSort.
hasExecutionHint()
bool llvm::SystemZSubtarget::hasExecutionHint () const inline
Definition at line 175 of file SystemZSubtarget.h.
References HasExecutionHint.
hasFastSerialization()
bool llvm::SystemZSubtarget::hasFastSerialization () const inline
Definition at line 164 of file SystemZSubtarget.h.
References HasFastSerialization.
Referenced by llvm::SystemZAsmPrinter::emitInstruction().
hasFPExtension()
bool llvm::SystemZSubtarget::hasFPExtension () const inline
Definition at line 145 of file SystemZSubtarget.h.
References HasFPExtension.
Referenced by llvm::SystemZTargetLowering::SystemZTargetLowering().
hasGuardedStorage()
bool llvm::SystemZSubtarget::hasGuardedStorage () const inline
Definition at line 213 of file SystemZSubtarget.h.
References HasGuardedStorage.
hasHighWord()
bool llvm::SystemZSubtarget::hasHighWord () const inline
Definition at line 142 of file SystemZSubtarget.h.
References HasHighWord.
Referenced by llvm::SystemZTargetLowering::SystemZTargetLowering().
hasInsertReferenceBitsMultiple()
bool llvm::SystemZSubtarget::hasInsertReferenceBitsMultiple () const inline
Definition at line 230 of file SystemZSubtarget.h.
References HasInsertReferenceBitsMultiple.
hasInterlockedAccess1()
bool llvm::SystemZSubtarget::hasInterlockedAccess1 () const inline
Definition at line 167 of file SystemZSubtarget.h.
References HasInterlockedAccess1.
hasLoadAndTrap()
bool llvm::SystemZSubtarget::hasLoadAndTrap () const inline
Definition at line 178 of file SystemZSubtarget.h.
References HasLoadAndTrap.
Referenced by llvm::SystemZInstrInfo::getLoadAndTrap().
hasLoadAndZeroRightmostByte()
bool llvm::SystemZSubtarget::hasLoadAndZeroRightmostByte () const inline
Definition at line 193 of file SystemZSubtarget.h.
References HasLoadAndZeroRightmostByte.
hasLoadStoreOnCond()
bool llvm::SystemZSubtarget::hasLoadStoreOnCond () const inline
Definition at line 136 of file SystemZSubtarget.h.
References HasLoadStoreOnCond.
Referenced by llvm::SystemZInstrInfo::canInsertSelect().
hasLoadStoreOnCond2()
bool llvm::SystemZSubtarget::hasLoadStoreOnCond2 () const inline
Definition at line 139 of file SystemZSubtarget.h.
References HasLoadStoreOnCond2.
Referenced by llvm::SystemZInstrInfo::canInsertSelect(), llvm::SystemZInstrInfo::FoldImmediate(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::SystemZTTIImpl::getCastInstrCost(), and llvm::SystemZInstrInfo::insertSelect().
hasMessageSecurityAssist3()
bool llvm::SystemZSubtarget::hasMessageSecurityAssist3 () const inline
Definition at line 152 of file SystemZSubtarget.h.
References HasMessageSecurityAssist3.
hasMessageSecurityAssist4()
bool llvm::SystemZSubtarget::hasMessageSecurityAssist4 () const inline
Definition at line 156 of file SystemZSubtarget.h.
References HasMessageSecurityAssist4.
hasMessageSecurityAssist5()
bool llvm::SystemZSubtarget::hasMessageSecurityAssist5 () const inline
Definition at line 199 of file SystemZSubtarget.h.
References HasMessageSecurityAssist5.
hasMessageSecurityAssist7()
bool llvm::SystemZSubtarget::hasMessageSecurityAssist7 () const inline
Definition at line 217 of file SystemZSubtarget.h.
References HasMessageSecurityAssist7.
hasMessageSecurityAssist8()
bool llvm::SystemZSubtarget::hasMessageSecurityAssist8 () const inline
Definition at line 221 of file SystemZSubtarget.h.
References HasMessageSecurityAssist8.
hasMessageSecurityAssist9()
bool llvm::SystemZSubtarget::hasMessageSecurityAssist9 () const inline
Definition at line 241 of file SystemZSubtarget.h.
References HasMessageSecurityAssist9.
hasMiscellaneousExtensions()
bool llvm::SystemZSubtarget::hasMiscellaneousExtensions () const inline
Definition at line 170 of file SystemZSubtarget.h.
References HasMiscellaneousExtensions.
Referenced by llvm::SystemZInstrInfo::convertToThreeAddress(), and llvm::SystemZInstrInfo::getFusedCompare().
hasMiscellaneousExtensions2()
bool llvm::SystemZSubtarget::hasMiscellaneousExtensions2 () const inline
Definition at line 208 of file SystemZSubtarget.h.
References HasMiscellaneousExtensions2.
Referenced by llvm::SystemZTTIImpl::isFoldableLoad().
hasMiscellaneousExtensions3()
bool llvm::SystemZSubtarget::hasMiscellaneousExtensions3 () const inline
Definition at line 235 of file SystemZSubtarget.h.
References HasMiscellaneousExtensions3.
Referenced by llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::SystemZTTIImpl::getMinPrefetchStride(), llvm::SystemZInstrInfo::insertSelect(), and llvm::SystemZTargetLowering::SystemZTargetLowering().
hasNNPAssist()
bool llvm::SystemZSubtarget::hasNNPAssist () const inline
Definition at line 265 of file SystemZSubtarget.h.
References HasNNPAssist.
hasPopulationCount()
bool llvm::SystemZSubtarget::hasPopulationCount () const inline
Definition at line 148 of file SystemZSubtarget.h.
References HasPopulationCount.
Referenced by llvm::SystemZTTIImpl::getPopcntSupport(), and llvm::SystemZTargetLowering::SystemZTargetLowering().
hasProcessorActivityInstrumentation()
bool llvm::SystemZSubtarget::hasProcessorActivityInstrumentation () const inline
Definition at line 275 of file SystemZSubtarget.h.
References HasProcessorActivityInstrumentation.
hasProcessorAssist()
bool llvm::SystemZSubtarget::hasProcessorAssist () const inline
Definition at line 184 of file SystemZSubtarget.h.
References HasProcessorAssist.
hasResetDATProtection()
bool llvm::SystemZSubtarget::hasResetDATProtection () const inline
Definition at line 271 of file SystemZSubtarget.h.
References HasResetDATProtection.
hasResetReferenceBitsMultiple()
bool llvm::SystemZSubtarget::hasResetReferenceBitsMultiple () const inline
Definition at line 159 of file SystemZSubtarget.h.
References HasResetReferenceBitsMultiple.
hasSoftFloat()
bool llvm::SystemZSubtarget::hasSoftFloat () const inline
Definition at line 280 of file SystemZSubtarget.h.
References HasSoftFloat.
Referenced by llvm::SystemZTargetLowering::useSoftFloat().
hasTransactionalExecution()
bool llvm::SystemZSubtarget::hasTransactionalExecution () const inline
Definition at line 181 of file SystemZSubtarget.h.
References HasTransactionalExecution.
hasVector()
bool llvm::SystemZSubtarget::hasVector () const inline
Definition at line 205 of file SystemZSubtarget.h.
References HasVector.
Referenced by llvm::SystemZTargetLowering::CanLowerReturn(), llvm::SystemZInstrInfo::copyPhysReg(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::SystemZELFRegisters::getCalleeSavedRegs(), llvm::SystemZELFRegisters::getCallPreservedMask(), llvm::SystemZTTIImpl::getCastInstrCost(), llvm::SystemZTTIImpl::getCmpSelInstrCost(), llvm::SystemZTTIImpl::getNumberOfRegisters(), llvm::SystemZTargetLowering::getRegForInlineAsmConstraint(), llvm::SystemZTTIImpl::getRegisterBitWidth(), llvm::SystemZTTIImpl::getShuffleCost(), llvm::SystemZTargetLowering::getSingleConstraintMatchWeight(), llvm::SystemZTargetLowering::isLegalAddressingMode(), llvm::SystemZVectorConstantInfo::isVectorConstantLegal(), llvm::SystemZTargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerReturn(), and llvm::SystemZTargetLowering::SystemZTargetLowering().
hasVectorEnhancements1()
bool llvm::SystemZSubtarget::hasVectorEnhancements1 () const inline
Definition at line 224 of file SystemZSubtarget.h.
References HasVectorEnhancements1.
Referenced by llvm::SystemZTTIImpl::getArithmeticInstrCost(), llvm::SystemZTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::SystemZVectorConstantInfo::isVectorConstantLegal(), and llvm::SystemZTargetLowering::SystemZTargetLowering().
hasVectorEnhancements2()
bool llvm::SystemZSubtarget::hasVectorEnhancements2 () const inline
Definition at line 244 of file SystemZSubtarget.h.
References HasVectorEnhancements2.
Referenced by llvm::SystemZTTIImpl::getCastInstrCost(), llvm::SystemZTTIImpl::getMemoryOpCost(), and llvm::SystemZTargetLowering::SystemZTargetLowering().
hasVectorPackedDecimal()
bool llvm::SystemZSubtarget::hasVectorPackedDecimal () const inline
Definition at line 227 of file SystemZSubtarget.h.
References HasVectorPackedDecimal.
hasVectorPackedDecimalEnhancement()
bool llvm::SystemZSubtarget::hasVectorPackedDecimalEnhancement () const inline
Definition at line 248 of file SystemZSubtarget.h.
References HasVectorPackedDecimalEnhancement.
hasVectorPackedDecimalEnhancement2()
bool llvm::SystemZSubtarget::hasVectorPackedDecimalEnhancement2 () const inline
Definition at line 260 of file SystemZSubtarget.h.
References HasVectorPackedDecimalEnhancement2.
isPC32DBLSymbol()
bool SystemZSubtarget::isPC32DBLSymbol (const GlobalValue * GV, CodeModel::Model CM) const
Definition at line 100 of file SystemZSubtarget.cpp.
References DL, llvm::Module::getDataLayout(), llvm::GlobalValue::getParent(), llvm::Value::getPointerAlignment(), llvm::TargetLoweringBase::getTargetMachine(), llvm::GlobalValue::getValueType(), llvm::Type::isFunctionTy(), llvm::TargetMachine::shouldAssumeDSOLocal(), and llvm::CodeModel::Small.
isTargetELF()
bool llvm::SystemZSubtarget::isTargetELF () const inline
Definition at line 286 of file SystemZSubtarget.h.
References llvm::Triple::isOSBinFormatELF().
Referenced by llvm::CC_SystemZ_I128Indirect().
isTargetGOFF()
bool llvm::SystemZSubtarget::isTargetGOFF () const inline
Definition at line 289 of file SystemZSubtarget.h.
References llvm::Triple::isOSBinFormatGOFF().
Referenced by isTargetXPLINK64().
isTargetXPLINK64()
bool llvm::SystemZSubtarget::isTargetXPLINK64 () const inline
Definition at line 292 of file SystemZSubtarget.h.
References isTargetGOFF(), and isTargetzOS().
Referenced by llvm::CC_SystemZ_I128Indirect(), and llvm::SystemZAsmPrinter::emitInstruction().
isTargetzOS()
bool llvm::SystemZSubtarget::isTargetzOS () const inline
Definition at line 295 of file SystemZSubtarget.h.
References llvm::Triple::isOSzOS().
Referenced by isTargetXPLINK64().
ParseSubtargetFeatures()
void llvm::SystemZSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef TuneCPU, StringRef FS)
useAA()
bool llvm::SystemZSubtarget::useAA () const inline override
Definition at line 121 of file SystemZSubtarget.h.
Member Data Documentation
HasBEAREnhancement
bool llvm::SystemZSubtarget::HasBEAREnhancement protected
Definition at line 73 of file SystemZSubtarget.h.
Referenced by hasBEAREnhancement().
HasDeflateConversion
bool llvm::SystemZSubtarget::HasDeflateConversion protected
Definition at line 70 of file SystemZSubtarget.h.
Referenced by hasDeflateConversion().
HasDFPPackedConversion
bool llvm::SystemZSubtarget::HasDFPPackedConversion protected
Definition at line 57 of file SystemZSubtarget.h.
Referenced by hasDFPPackedConversion().
HasDFPZonedConversion
bool llvm::SystemZSubtarget::HasDFPZonedConversion protected
Definition at line 51 of file SystemZSubtarget.h.
Referenced by hasDFPZonedConversion().
HasDistinctOps
bool llvm::SystemZSubtarget::HasDistinctOps protected
Definition at line 36 of file SystemZSubtarget.h.
Referenced by hasDistinctOps().
HasEnhancedDAT2
bool llvm::SystemZSubtarget::HasEnhancedDAT2 protected
Definition at line 52 of file SystemZSubtarget.h.
Referenced by hasEnhancedDAT2().
HasEnhancedSort
bool llvm::SystemZSubtarget::HasEnhancedSort protected
Definition at line 69 of file SystemZSubtarget.h.
Referenced by hasEnhancedSort().
HasExecutionHint
bool llvm::SystemZSubtarget::HasExecutionHint protected
Definition at line 47 of file SystemZSubtarget.h.
Referenced by hasExecutionHint().
HasFastSerialization
bool llvm::SystemZSubtarget::HasFastSerialization protected
Definition at line 44 of file SystemZSubtarget.h.
Referenced by hasFastSerialization().
HasFPExtension
bool llvm::SystemZSubtarget::HasFPExtension protected
Definition at line 39 of file SystemZSubtarget.h.
Referenced by hasFPExtension().
HasGuardedStorage
bool llvm::SystemZSubtarget::HasGuardedStorage protected
Definition at line 59 of file SystemZSubtarget.h.
Referenced by hasGuardedStorage().
HasHighWord
bool llvm::SystemZSubtarget::HasHighWord protected
Definition at line 38 of file SystemZSubtarget.h.
Referenced by hasHighWord().
HasInsertReferenceBitsMultiple
bool llvm::SystemZSubtarget::HasInsertReferenceBitsMultiple protected
Definition at line 64 of file SystemZSubtarget.h.
Referenced by hasInsertReferenceBitsMultiple().
HasInterlockedAccess1
bool llvm::SystemZSubtarget::HasInterlockedAccess1 protected
Definition at line 45 of file SystemZSubtarget.h.
Referenced by hasInterlockedAccess1().
HasLoadAndTrap
bool llvm::SystemZSubtarget::HasLoadAndTrap protected
Definition at line 48 of file SystemZSubtarget.h.
Referenced by hasLoadAndTrap().
HasLoadAndZeroRightmostByte
bool llvm::SystemZSubtarget::HasLoadAndZeroRightmostByte protected
Definition at line 55 of file SystemZSubtarget.h.
Referenced by hasLoadAndZeroRightmostByte().
HasLoadStoreOnCond
bool llvm::SystemZSubtarget::HasLoadStoreOnCond protected
Definition at line 37 of file SystemZSubtarget.h.
Referenced by hasLoadStoreOnCond().
HasLoadStoreOnCond2
bool llvm::SystemZSubtarget::HasLoadStoreOnCond2 protected
Definition at line 54 of file SystemZSubtarget.h.
Referenced by hasLoadStoreOnCond2().
HasMessageSecurityAssist3
bool llvm::SystemZSubtarget::HasMessageSecurityAssist3 protected
Definition at line 41 of file SystemZSubtarget.h.
Referenced by hasMessageSecurityAssist3().
HasMessageSecurityAssist4
bool llvm::SystemZSubtarget::HasMessageSecurityAssist4 protected
Definition at line 42 of file SystemZSubtarget.h.
Referenced by hasMessageSecurityAssist4().
HasMessageSecurityAssist5
bool llvm::SystemZSubtarget::HasMessageSecurityAssist5 protected
Definition at line 56 of file SystemZSubtarget.h.
Referenced by hasMessageSecurityAssist5().
HasMessageSecurityAssist7
bool llvm::SystemZSubtarget::HasMessageSecurityAssist7 protected
Definition at line 60 of file SystemZSubtarget.h.
Referenced by hasMessageSecurityAssist7().
HasMessageSecurityAssist8
bool llvm::SystemZSubtarget::HasMessageSecurityAssist8 protected
Definition at line 61 of file SystemZSubtarget.h.
Referenced by hasMessageSecurityAssist8().
HasMessageSecurityAssist9
bool llvm::SystemZSubtarget::HasMessageSecurityAssist9 protected
Definition at line 66 of file SystemZSubtarget.h.
Referenced by hasMessageSecurityAssist9().
HasMiscellaneousExtensions
bool llvm::SystemZSubtarget::HasMiscellaneousExtensions protected
Definition at line 46 of file SystemZSubtarget.h.
Referenced by hasMiscellaneousExtensions().
HasMiscellaneousExtensions2
bool llvm::SystemZSubtarget::HasMiscellaneousExtensions2 protected
Definition at line 58 of file SystemZSubtarget.h.
Referenced by hasMiscellaneousExtensions2().
HasMiscellaneousExtensions3
bool llvm::SystemZSubtarget::HasMiscellaneousExtensions3 protected
Definition at line 65 of file SystemZSubtarget.h.
Referenced by hasMiscellaneousExtensions3().
HasNNPAssist
bool llvm::SystemZSubtarget::HasNNPAssist protected
Definition at line 72 of file SystemZSubtarget.h.
Referenced by hasNNPAssist().
HasPopulationCount
bool llvm::SystemZSubtarget::HasPopulationCount protected
Definition at line 40 of file SystemZSubtarget.h.
Referenced by hasPopulationCount().
HasProcessorActivityInstrumentation
bool llvm::SystemZSubtarget::HasProcessorActivityInstrumentation protected
Definition at line 75 of file SystemZSubtarget.h.
Referenced by hasProcessorActivityInstrumentation().
HasProcessorAssist
bool llvm::SystemZSubtarget::HasProcessorAssist protected
Definition at line 50 of file SystemZSubtarget.h.
Referenced by hasProcessorAssist().
HasResetDATProtection
bool llvm::SystemZSubtarget::HasResetDATProtection protected
Definition at line 74 of file SystemZSubtarget.h.
Referenced by hasResetDATProtection().
HasResetReferenceBitsMultiple
bool llvm::SystemZSubtarget::HasResetReferenceBitsMultiple protected
Definition at line 43 of file SystemZSubtarget.h.
Referenced by hasResetReferenceBitsMultiple().
HasSoftFloat
bool llvm::SystemZSubtarget::HasSoftFloat protected
Definition at line 76 of file SystemZSubtarget.h.
Referenced by hasSoftFloat().
HasTransactionalExecution
bool llvm::SystemZSubtarget::HasTransactionalExecution protected
Definition at line 49 of file SystemZSubtarget.h.
Referenced by hasTransactionalExecution().
HasVector
bool llvm::SystemZSubtarget::HasVector protected
Definition at line 53 of file SystemZSubtarget.h.
Referenced by hasVector().
HasVectorEnhancements1
bool llvm::SystemZSubtarget::HasVectorEnhancements1 protected
Definition at line 62 of file SystemZSubtarget.h.
Referenced by hasVectorEnhancements1().
HasVectorEnhancements2
bool llvm::SystemZSubtarget::HasVectorEnhancements2 protected
Definition at line 67 of file SystemZSubtarget.h.
Referenced by hasVectorEnhancements2().
HasVectorPackedDecimal
bool llvm::SystemZSubtarget::HasVectorPackedDecimal protected
Definition at line 63 of file SystemZSubtarget.h.
Referenced by hasVectorPackedDecimal().
HasVectorPackedDecimalEnhancement
bool llvm::SystemZSubtarget::HasVectorPackedDecimalEnhancement protected
Definition at line 68 of file SystemZSubtarget.h.
Referenced by hasVectorPackedDecimalEnhancement().
HasVectorPackedDecimalEnhancement2
bool llvm::SystemZSubtarget::HasVectorPackedDecimalEnhancement2 protected
Definition at line 71 of file SystemZSubtarget.h.
Referenced by hasVectorPackedDecimalEnhancement2().
The documentation for this class was generated from the following files:
lib/Target/SystemZ/SystemZSubtarget.h
lib/Target/SystemZ/SystemZSubtarget.cpp