LLVM: llvm::InstrItineraryData Class Reference
llvm::InstrItineraryData Class Reference
Itinerary data supplied by a subtarget to be used by a target.
#include "llvm/MC/MCInstrItineraries.h"
Public Member Functions
InstrItineraryData ()=default
InstrItineraryData (const MCSchedModel &SM, const InstrStage *S, const unsigned *OS, const unsigned *F)
bool isEmpty () const
Returns true if there are no itineraries.
bool isEndMarker (unsigned ItinClassIndx) const
Returns true if the index is for the end marker itinerary.
const InstrStage * beginStage (unsigned ItinClassIndx) const
Return the first stage of the itinerary.
const InstrStage * endStage (unsigned ItinClassIndx) const
Return the last+1 stage of the itinerary.
unsigned getStageLatency (unsigned ItinClassIndx) const
Return the total stage latency of the given class.
int getOperandCycle (unsigned ItinClassIndx, unsigned OperandIdx) const
Return the cycle for the given class and operand.
bool hasPipelineForwarding (unsigned DefClass, unsigned DefIdx, unsigned UseClass, unsigned UseIdx) const
Return true if there is a pipeline forwarding between instructions of itinerary classes DefClass and UseClasses so that value produced by an instruction of itinerary class DefClass, operand index DefIdx can be bypassed when it's read by an instruction of itinerary class UseClass, operand index UseIdx.
int getOperandLatency (unsigned DefClass, unsigned DefIdx, unsigned UseClass, unsigned UseIdx) const
Compute and return the use operand latency of a given itinerary class and operand index if the value is produced by an instruction of the specified itinerary class and def operand index.
int getNumMicroOps (unsigned ItinClassIndx) const
Return the number of micro-ops that the given class decodes to.
Public Attributes
MCSchedModel SchedModel
Basic machine properties.
const InstrStage * Stages = nullptr
Array of stages selected.
const unsigned * OperandCycles = nullptr
Array of operand cycles selected.
const unsigned * Forwardings = nullptr
Array of pipeline forwarding paths.
const InstrItinerary * Itineraries
Array of itineraries selected.
Detailed Description
Itinerary data supplied by a subtarget to be used by a target.
Definition at line 109 of file MCInstrItineraries.h.
Constructor & Destructor Documentation
InstrItineraryData() [1/2]
llvm::InstrItineraryData::InstrItineraryData () default
InstrItineraryData() [2/2]
llvm::InstrItineraryData::InstrItineraryData (const MCSchedModel & SM, const InstrStage * S, const unsigned * OS, const unsigned * F) inline
Definition at line 120 of file MCInstrItineraries.h.
Member Function Documentation
beginStage()
const InstrStage * llvm::InstrItineraryData::beginStage (unsigned ItinClassIndx) const inline
Return the first stage of the itinerary.
Definition at line 135 of file MCInstrItineraries.h.
References llvm::InstrItinerary::FirstStage, Itineraries, and Stages.
Referenced by llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::ScoreboardHazardRecognizer::getHazardType(), llvm::MCSchedModel::getReciprocalThroughput(), getStageLatency(), llvm::HexagonInstrInfo::getUnits(), and llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer().
endStage()
const InstrStage * llvm::InstrItineraryData::endStage (unsigned ItinClassIndx) const inline
Return the last+1 stage of the itinerary.
Definition at line 141 of file MCInstrItineraries.h.
References Itineraries, llvm::InstrItinerary::LastStage, and Stages.
Referenced by llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::ScoreboardHazardRecognizer::getHazardType(), llvm::MCSchedModel::getReciprocalThroughput(), getStageLatency(), and llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer().
getNumMicroOps()
int llvm::InstrItineraryData::getNumMicroOps (unsigned ItinClassIndx) const inline
Return the number of micro-ops that the given class decodes to.
Return -1 for classes that require dynamic lookup via TargetInstrInfo.
Definition at line 228 of file MCInstrItineraries.h.
References isEmpty(), Itineraries, and llvm::InstrItinerary::NumMicroOps.
Referenced by llvm::ARMBaseInstrInfo::getNumMicroOps(), llvm::TargetSchedModel::getNumMicroOps(), and getNumMicroOpsSwiftLdSt().
getOperandCycle()
int llvm::InstrItineraryData::getOperandCycle (unsigned ItinClassIndx, unsigned OperandIdx) const inline
Return the cycle for the given class and operand.
Return -1 if no cycle is specified for the operand.
Definition at line 167 of file MCInstrItineraries.h.
References llvm::InstrItinerary::FirstOperandCycle, isEmpty(), Itineraries, llvm::InstrItinerary::LastOperandCycle, and OperandCycles.
Referenced by llvm::TargetSchedModel::computeOperandLatency(), llvm::PPCInstrInfo::getInstrLatency(), getItineraryLatency(), llvm::TargetInstrInfo::getOperandLatency(), llvm::ARMBaseInstrInfo::getOperandLatency(), getOperandLatency(), llvm::ARMTargetLowering::getSchedulingPreference(), and llvm::TargetInstrInfo::hasLowDefLatency().
getOperandLatency()
int llvm::InstrItineraryData::getOperandLatency (unsigned DefClass, unsigned DefIdx, unsigned UseClass, unsigned UseIdx) const inline
Compute and return the use operand latency of a given itinerary class and operand index if the value is produced by an instruction of the specified itinerary class and def operand index.
Definition at line 205 of file MCInstrItineraries.h.
References getOperandCycle(), hasPipelineForwarding(), and isEmpty().
Referenced by llvm::TargetInstrInfo::getOperandLatency(), and llvm::TargetInstrInfo::getOperandLatency().
getStageLatency()
unsigned llvm::InstrItineraryData::getStageLatency (unsigned ItinClassIndx) const inline
Return the total stage latency of the given class.
The latency is the maximum completion time for any stage in the itinerary. If no stages exist, it defaults to one cycle.
Definition at line 149 of file MCInstrItineraries.h.
References beginStage(), E, endStage(), isEmpty(), and llvm::Latency.
Referenced by llvm::TargetInstrInfo::getInstrLatency(), llvm::TargetInstrInfo::getInstrLatency(), and llvm::HexagonInstrInfo::getInstrTimingClassLatency().
hasPipelineForwarding()
bool llvm::InstrItineraryData::hasPipelineForwarding (unsigned DefClass, unsigned DefIdx, unsigned UseClass, unsigned UseIdx) const inline
Return true if there is a pipeline forwarding between instructions of itinerary classes DefClass and UseClasses so that value produced by an instruction of itinerary class DefClass, operand index DefIdx can be bypassed when it's read by an instruction of itinerary class UseClass, operand index UseIdx.
Definition at line 184 of file MCInstrItineraries.h.
References llvm::InstrItinerary::FirstOperandCycle, Forwardings, Itineraries, and llvm::InstrItinerary::LastOperandCycle.
Referenced by getOperandLatency().
isEmpty()
bool llvm::InstrItineraryData::isEmpty () const inline
Returns true if there are no itineraries.
Definition at line 126 of file MCInstrItineraries.h.
References Itineraries.
Referenced by llvm::TargetInstrInfo::computeDefOperandLatency(), llvm::ScheduleDAGSDNodes::computeLatency(), llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::ScoreboardHazardRecognizer::getHazardType(), llvm::TargetInstrInfo::getInstrLatency(), llvm::TargetInstrInfo::getNumMicroOps(), llvm::ARMBaseInstrInfo::getNumMicroOps(), getNumMicroOps(), getOperandCycle(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::TargetInstrInfo::getOperandLatency(), llvm::ARMBaseInstrInfo::getOperandLatency(), getOperandLatency(), llvm::ARMTargetLowering::getSchedulingPreference(), getStageLatency(), llvm::TargetSchedModel::hasInstrItineraries(), llvm::TargetInstrInfo::hasLowDefLatency(), and llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer().
isEndMarker()
bool llvm::InstrItineraryData::isEndMarker (unsigned ItinClassIndx) const inline
Returns true if the index is for the end marker itinerary.
Definition at line 129 of file MCInstrItineraries.h.
References Itineraries.
Referenced by llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer().
Member Data Documentation
Forwardings
const unsigned* llvm::InstrItineraryData::Forwardings = nullptr
Array of pipeline forwarding paths.
Definition at line 115 of file MCInstrItineraries.h.
Referenced by hasPipelineForwarding().
Itineraries
const InstrItinerary* llvm::InstrItineraryData::Itineraries
Initial value:
=
      nullptr
Array of itineraries selected.
Definition at line 116 of file MCInstrItineraries.h.
Referenced by beginStage(), endStage(), llvm::TargetInstrInfo::getNumMicroOps(), getNumMicroOps(), getOperandCycle(), hasPipelineForwarding(), llvm::HexagonSubtarget::HexagonSubtarget(), isEmpty(), and isEndMarker().
OperandCycles
const unsigned* llvm::InstrItineraryData::OperandCycles = nullptr
Array of operand cycles selected.
Definition at line 114 of file MCInstrItineraries.h.
Referenced by getOperandCycle().
SchedModel
MCSchedModel llvm::InstrItineraryData::SchedModel
Initial value:
=
      MCSchedModel::GetDefaultSchedModel()
Basic machine properties.
Definition at line 111 of file MCInstrItineraries.h.
Referenced by llvm::TargetInstrInfo::computeDefOperandLatency(), llvm::ResourcePriorityQueue::reserveResources(), and llvm::ScoreboardHazardRecognizer::ScoreboardHazardRecognizer().
Stages
const InstrStage* llvm::InstrItineraryData::Stages = nullptr
Array of stages selected.
Definition at line 113 of file MCInstrItineraries.h.
Referenced by beginStage(), and endStage().
The documentation for this class was generated from the following file:
include/llvm/MC/MCInstrItineraries.h