LLVM: llvm::AAResultBase< DerivedT > Class Template Reference
llvm::AAResultBase< DerivedT > Class Template Reference
A CRTP-driven "mixin" base class to help implement the function alias analysis results concept.
#include "llvm/Analysis/AliasAnalysis.h"
Classes
class AAResultsProxy
This proxy class models a common pattern where we delegate to either the top-level AAResults aggregation if one is registered, or to the current result if none are registered.
Public Member Functions
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Protected Member Functions
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)
AAResultBase (AAResultBase &&Arg)
AAResultsProxy getBestAAResults ()
Get a proxy for the best AA result set to query at this time.
Friends
class AAResults::Model< DerivedT >
Detailed Description
template<typename DerivedT>
class llvm::AAResultBase< DerivedT >
A CRTP-driven "mixin" base class to help implement the function alias analysis results concept.
Because of the nature of many alias analysis implementations, they often only implement a subset of the interface. This base class will attempt to implement the remaining portions of the interface in terms of simpler forms of the interface where possible, and otherwise provide conservatively correct fallback implementations.
Implementors of an alias analysis should derive from this CRTP, and then override specific methods that they wish to customize. There is no need to use virtual anywhere, the CRTP base class does static dispatch to the derived type passed into it.
Definition at line 1076 of file AliasAnalysis.h.
Constructor & Destructor Documentation
AAResultBase() [1/3]
template<typename DerivedT > llvm::AAResultBase< DerivedT >::AAResultBase () explicit protected default
AAResultBase() [2/3]
template<typename DerivedT > llvm::AAResultBase< DerivedT >::AAResultBase (const AAResultBase< DerivedT > & Arg) inline protected
Definition at line 1148 of file AliasAnalysis.h.
AAResultBase() [3/3]
template<typename DerivedT > llvm::AAResultBase< DerivedT >::AAResultBase (AAResultBase< DerivedT > && Arg) inline protected
Definition at line 1149 of file AliasAnalysis.h.
Member Function Documentation
alias()
template<typename DerivedT > AliasResult llvm::AAResultBase< DerivedT >::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI) inline
Definition at line 1164 of file AliasAnalysis.h.
References llvm::AliasResult::MayAlias.
Referenced by llvm::CFLAndersAAResult::alias(), llvm::CFLSteensAAResult::alias(), llvm::GlobalsAAResult::alias(), llvm::objcarc::ObjCARCAAResult::alias(), llvm::SCEVAAResult::alias(), llvm::ScopedNoAliasAAResult::alias(), llvm::TypeBasedAAResult::alias(), and llvm::AMDGPUAAResult::alias().
getArgModRefInfo()
template<typename DerivedT > ModRefInfo llvm::AAResultBase< DerivedT >::getArgModRefInfo (const CallBase * Call, unsigned ArgIdx) inline
Definition at line 1174 of file AliasAnalysis.h.
References llvm::ModRef.
Referenced by llvm::BasicAAResult::getArgModRefInfo().
getBestAAResults()
template<typename DerivedT > AAResultsProxy llvm::AAResultBase< DerivedT >::getBestAAResults () inline protected
Get a proxy for the best AA result set to query at this time.
When this result is part of a larger aggregation, this will proxy to that aggregation. When this result is used in isolation, it will just delegate back to the derived class's implementation.
Note that callers of this need to take considerable care to not cause performance problems when they use this routine, in the case of a large number of alias analyses being aggregated, it can be expensive to walk back across the chain.
Definition at line 1161 of file AliasAnalysis.h.
getModRefBehavior() [1/2]
template<typename DerivedT > FunctionModRefBehavior llvm::AAResultBase< DerivedT >::getModRefBehavior (const CallBase * Call) inline
Definition at line 1178 of file AliasAnalysis.h.
References llvm::FMRB_UnknownModRefBehavior.
Referenced by llvm::GlobalsAAResult::getModRefBehavior(), llvm::TypeBasedAAResult::getModRefBehavior(), llvm::GlobalsAAResult::getModRefBehavior(), llvm::objcarc::ObjCARCAAResult::getModRefBehavior(), and llvm::TypeBasedAAResult::getModRefBehavior().
getModRefBehavior() [2/2]
template<typename DerivedT > FunctionModRefBehavior llvm::AAResultBase< DerivedT >::getModRefBehavior (const Function * F) inline
Definition at line 1182 of file AliasAnalysis.h.
References llvm::FMRB_UnknownModRefBehavior.
getModRefInfo() [1/2]
template<typename DerivedT > ModRefInfo llvm::AAResultBase< DerivedT >::getModRefInfo (const CallBase * Call, const MemoryLocation & Loc, AAQueryInfo & AAQI) inline
Definition at line 1186 of file AliasAnalysis.h.
References llvm::ModRef.
Referenced by llvm::BasicAAResult::getModRefInfo(), llvm::GlobalsAAResult::getModRefInfo(), llvm::objcarc::ObjCARCAAResult::getModRefInfo(), llvm::ScopedNoAliasAAResult::getModRefInfo(), llvm::TypeBasedAAResult::getModRefInfo(), llvm::BasicAAResult::getModRefInfo(), llvm::ScopedNoAliasAAResult::getModRefInfo(), and llvm::TypeBasedAAResult::getModRefInfo().
getModRefInfo() [2/2]
template<typename DerivedT > ModRefInfo llvm::AAResultBase< DerivedT >::getModRefInfo (const CallBase * Call1, const CallBase * Call2, AAQueryInfo & AAQI) inline
Definition at line 1191 of file AliasAnalysis.h.
References llvm::ModRef.
pointsToConstantMemory()
template<typename DerivedT > bool llvm::AAResultBase< DerivedT >::pointsToConstantMemory (const MemoryLocation & Loc, AAQueryInfo & AAQI, bool OrLocal) inline
Definition at line 1169 of file AliasAnalysis.h.
Referenced by llvm::BasicAAResult::pointsToConstantMemory(), llvm::objcarc::ObjCARCAAResult::pointsToConstantMemory(), llvm::TypeBasedAAResult::pointsToConstantMemory(), and llvm::AMDGPUAAResult::pointsToConstantMemory().
Friends And Related Symbol Documentation
AAResults::Model< DerivedT >
template<typename DerivedT > friend class AAResults::Model< DerivedT > friend
Definition at line 1057 of file AliasAnalysis.h.
The documentation for this class was generated from the following file:
include/llvm/Analysis/AliasAnalysis.h