LLVM: llvm::AMDGPUAAResult Class Reference
llvm::AMDGPUAAResult Class Reference
A simple AA result that uses TBAA metadata to answer queries.
#include "Target/AMDGPU/AMDGPUAliasAnalysis.h"
Public Member Functions
AMDGPUAAResult (const DataLayout &DL)
AMDGPUAAResult (AMDGPUAAResult &&Arg)
bool invalidate (Function &, const PreservedAnalyses &, FunctionAnalysisManager::Invalidator &Inv)
Handle invalidation events from the new pass manager.
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
Public Member Functions inherited from llvm::AAResultBase< AMDGPUAAResult >
AliasResult alias (const MemoryLocation &LocA, const MemoryLocation &LocB, AAQueryInfo &AAQI)
bool pointsToConstantMemory (const MemoryLocation &Loc, AAQueryInfo &AAQI, bool OrLocal)
ModRefInfo getArgModRefInfo (const CallBase *Call, unsigned ArgIdx)
FunctionModRefBehavior getModRefBehavior (const CallBase *Call)
FunctionModRefBehavior getModRefBehavior (const Function *F)
ModRefInfo getModRefInfo (const CallBase *Call, const MemoryLocation &Loc, AAQueryInfo &AAQI)
ModRefInfo getModRefInfo (const CallBase *Call1, const CallBase *Call2, AAQueryInfo &AAQI)
Additional Inherited Members
Protected Member Functions inherited from llvm::AAResultBase< AMDGPUAAResult >
AAResultBase ()=default
AAResultBase (const AAResultBase &Arg)
AAResultBase (AAResultBase &&Arg)
AAResultsProxy getBestAAResults ()
Get a proxy for the best AA result set to query at this time.
Detailed Description
A simple AA result that uses TBAA metadata to answer queries.
Definition at line 25 of file AMDGPUAliasAnalysis.h.
Constructor & Destructor Documentation
AMDGPUAAResult() [1/2]
llvm::AMDGPUAAResult::AMDGPUAAResult (const DataLayout & DL) inline explicit
Definition at line 31 of file AMDGPUAliasAnalysis.h.
References DL.
AMDGPUAAResult() [2/2]
llvm::AMDGPUAAResult::AMDGPUAAResult (AMDGPUAAResult && Arg) inline
Definition at line 32 of file AMDGPUAliasAnalysis.h.
References DL.
Member Function Documentation
alias()
AliasResult AMDGPUAAResult::alias (const MemoryLocation & LocA, const MemoryLocation & LocB, AAQueryInfo & AAQI)
Definition at line 70 of file AMDGPUAliasAnalysis.cpp.
References A, llvm::AAResultBase< DerivedT >::alias(), llvm::CallingConv::AMDGPU_KERNEL, Arg, B, llvm::AMDGPUAS::CONSTANT_ADDRESS, F, llvm::AMDGPUAS::FLAT_ADDRESS, getAliasResult(), llvm::getUnderlyingObject(), llvm::AMDGPUAS::LOCAL_ADDRESS, llvm::AliasResult::NoAlias, llvm::AMDGPUAS::PRIVATE_ADDRESS, and std::swap().
invalidate()
bool llvm::AMDGPUAAResult::invalidate (Function & , const PreservedAnalyses & , FunctionAnalysisManager::Invalidator & Inv) inline
Handle invalidation events from the new pass manager.
By definition, this result is stateless and so remains valid.
Definition at line 38 of file AMDGPUAliasAnalysis.h.
pointsToConstantMemory()
bool AMDGPUAAResult::pointsToConstantMemory (const MemoryLocation & Loc, AAQueryInfo & AAQI, bool OrLocal)
Definition at line 122 of file AMDGPUAliasAnalysis.cpp.
References llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_KERNEL, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, Arg, llvm::sampleprof::Base, llvm::AMDGPUAS::CONSTANT_ADDRESS, llvm::AMDGPUAS::CONSTANT_ADDRESS_32BIT, F, llvm::getUnderlyingObject(), llvm::AAResultBase< DerivedT >::pointsToConstantMemory(), and llvm::CallingConv::SPIR_KERNEL.
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/AMDGPUAliasAnalysis.h
lib/Target/AMDGPU/AMDGPUAliasAnalysis.cpp