LLVM: lib/Analysis/DDGPrinter.cpp File Reference
DDGPrinter.cpp File Reference
#include "llvm/Analysis/DDGPrinter.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/GraphWriter.h"
Functions
static void writeDDGToDotFile (DataDependenceGraph &G, bool DOnly=false)
Variables
static cl::opt< bool > DotOnly ("dot-ddg-only", cl::init(false), cl::Hidden, cl::ZeroOrMore, cl::desc("simple ddg dot graph"))
static cl::opt< std::string > DDGDotFilenamePrefix ("dot-ddg-filename-prefix", cl::init("ddg"), cl::Hidden, cl::desc("The prefix used for the DDG dot file names."))
Function Documentation
writeDDGToDotFile()
static void writeDDGToDotFile (DataDependenceGraph & G, bool DOnly = false) static
Definition at line 39 of file DDGPrinter.cpp.
References DDGDotFilenamePrefix, llvm::errs(), G, llvm::sys::fs::OF_Text, llvm::Twine::str(), and llvm::WriteGraph().
Referenced by llvm::DDGDotPrinterPass::run().
Variable Documentation
DDGDotFilenamePrefix
cl::opt< std::string > DDGDotFilenamePrefix("dot-ddg-filename-prefix", cl::init("ddg"), cl::Hidden, cl::desc("The prefix used for the DDG dot file names.")) ("dot-ddg-filename-prefix" , cl::init("ddg") , cl::Hidden , cl::desc("The prefix used for the DDG dot file names.")) static
Referenced by writeDDGToDotFile().
DotOnly
cl::opt< bool > DotOnly("dot-ddg-only", cl::init(false), cl::Hidden, cl::ZeroOrMore, cl::desc("simple ddg dot graph")) ("dot-ddg-only" , cl::init(false) , cl::Hidden , cl::ZeroOrMore , cl::desc("simple ddg dot graph")) static
Referenced by llvm::DDGDotPrinterPass::run().