LLVM: lib/Support/DynamicLibrary.cpp File Reference
DynamicLibrary.cpp File Reference
#include "llvm/Support/DynamicLibrary.h"
#include "llvm-c/Support.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/Config/config.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Mutex.h"
#include <cstdio>
#include <cstring>
#include <vector>
#include "Unix/DynamicLibrary.inc"
Classes
class llvm::sys::DynamicLibrary::HandleSet
Namespaces
namespace llvm
---------------------— PointerInfo ------------------------------------—
Functions
void * llvm::SearchForAddressOfSpecialSymbol (const char *SymbolName)
LLVMBool LLVMLoadLibraryPermanently (const char *Filename)
This function permanently loads the dynamic library at the given path.
void * LLVMSearchForAddressOfSymbol (const char *symbolName)
This function will search through all previously loaded dynamic libraries for the symbol symbolName.
void LLVMAddSymbol (const char *symbolName, void *symbolValue)
This functions permanently adds the symbol symbolName with the value symbolValue.
Function Documentation
LLVMAddSymbol()
void LLVMAddSymbol (const char * symbolName, void * symbolValue)
This functions permanently adds the symbol symbolName with the value symbolValue.
These symbols are searched before any libraries.
See also
sys::DynamicLibrary::AddSymbol()
Definition at line 211 of file DynamicLibrary.cpp.
References llvm::sys::DynamicLibrary::AddSymbol().
LLVMLoadLibraryPermanently()
LLVMBool LLVMLoadLibraryPermanently (const char * Filename)
This function permanently loads the dynamic library at the given path.
It is safe to call this function multiple times for the same library.
See also
sys::DynamicLibrary::LoadLibraryPermanently()
Definition at line 203 of file DynamicLibrary.cpp.
References llvm::sys::DynamicLibrary::LoadLibraryPermanently().
LLVMSearchForAddressOfSymbol()
void * LLVMSearchForAddressOfSymbol (const char * symbolName)
This function will search through all previously loaded dynamic libraries for the symbol symbolName.
If it is found, the address of that symbol is returned. If not, null is returned.
See also
sys::DynamicLibrary::SearchForAddressOfSymbol()
Definition at line 207 of file DynamicLibrary.cpp.
References llvm::sys::DynamicLibrary::SearchForAddressOfSymbol().