LLVM: lib/Support/Host.cpp File Reference
Host.cpp File Reference
#include "llvm/Support/Host.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Config/llvm-config.h"
#include "llvm/Support/BCD.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/X86TargetParser.h"
#include "llvm/Support/raw_ostream.h"
#include <assert.h>
#include <string.h>
#include "Unix/Host.inc"
#include <sched.h>
Namespaces
namespace llvm
---------------------— PointerInfo ------------------------------------—
namespace llvm::sys
namespace llvm::sys::detail
namespace llvm::sys::detail::x86
Helper functions to extract CPU details from CPUID on x86.
Macros
#define DEBUG_TYPE "host-detection"
Functions
static std::unique_ptr< llvm::MemoryBuffer > LLVM_ATTRIBUTE_UNUSED getProcCpuinfoContent ()
VendorSignatures llvm::sys::detail::x86::getVendorSignature (unsigned *MaxLeaf=nullptr)
Returns the host CPU's vendor.
static int computeHostNumPhysicalCores ()
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "host-detection"
Definition at line 51 of file Host.cpp.
Function Documentation
computeHostNumPhysicalCores()
static int computeHostNumPhysicalCores () static
Definition at line 1473 of file Host.cpp.
Referenced by llvm::sys::getHostNumPhysicalCores().
getProcCpuinfoContent()
static std::unique_ptr< llvm::MemoryBuffer > LLVM_ATTRIBUTE_UNUSED getProcCpuinfoContent () static
Definition at line 62 of file Host.cpp.
References llvm::errs(), and llvm::MemoryBuffer::getFileAsStream().