LLVM: lib/Transforms/IPO/InferFunctionAttrs.cpp File Reference
InferFunctionAttrs.cpp File Reference
#include "llvm/Transforms/IPO/InferFunctionAttrs.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BuildLibCalls.h"
#include "llvm/Transforms/Utils/Local.h"
Macros
#define DEBUG_TYPE "inferattrs"
Functions
static bool inferAllPrototypeAttributes (Module &M, function_ref< TargetLibraryInfo &(Function &)> GetTLI)
INITIALIZE_PASS_BEGIN (InferFunctionAttrsLegacyPass, "inferattrs", "Infer set function attributes", false, false) INITIALIZE_PASS_END(InferFunctionAttrsLegacyPass
Variables
inferattrs
Infer set function attributes
Infer set function false
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "inferattrs"
Definition at line 21 of file InferFunctionAttrs.cpp.
Function Documentation
inferAllPrototypeAttributes()
static bool inferAllPrototypeAttributes (Module & M, function_ref< TargetLibraryInfo &(Function &)> GetTLI) static
Definition at line 23 of file InferFunctionAttrs.cpp.
References Changed, F, llvm::inferAttributesFromOthers(), and llvm::inferLibFuncAttributes().
Referenced by llvm::InferFunctionAttrsPass::run().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (InferFunctionAttrsLegacyPass , "inferattrs" , "Infer set function attributes" , false , false)
Variable Documentation
attributes
Infer set function attributes
Definition at line 88 of file InferFunctionAttrs.cpp.
false
Infer set function false
Definition at line 88 of file InferFunctionAttrs.cpp.
inferattrs
inferattrs
Definition at line 87 of file InferFunctionAttrs.cpp.