LLVM: lib/Target/M68k/MCTargetDesc/M68kAsmBackend.cpp File Reference
M68kAsmBackend.cpp File Reference
This file contains definitions for M68k assembler backend.
#include "MCTargetDesc/M68kBaseInfo.h"
#include "MCTargetDesc/M68kFixupKinds.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCMachObjectWriter.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
Functions
static unsigned getRelaxedOpcodeBranch (const MCInst &Inst)
cc—Carry clear GE—Greater than or equal LS—Lower or same PL—Plus CS—Carry set GT—Greater than LT—Less than EQ—Equal HI—Higher MI—Minus VC—Overflow clear LE—Less than or equal NE—Not equal VS—Overflow set
static unsigned getRelaxedOpcodeArith (const MCInst &Inst)
static unsigned getRelaxedOpcode (const MCInst &Inst)
Detailed Description
This file contains definitions for M68k assembler backend.
Definition in file M68kAsmBackend.cpp.
Function Documentation
getRelaxedOpcode()
static unsigned getRelaxedOpcode (const MCInst & Inst) static
Definition at line 141 of file M68kAsmBackend.cpp.
References llvm::MCInst::getOpcode(), getRelaxedOpcodeArith(), and getRelaxedOpcodeBranch().
Referenced by isFullyRelaxed().
getRelaxedOpcodeArith()
static unsigned getRelaxedOpcodeArith (const MCInst & Inst) static
Definition at line 135 of file M68kAsmBackend.cpp.
References llvm::MCInst::getOpcode().
Referenced by getRelaxedOpcode().
getRelaxedOpcodeBranch()
static unsigned getRelaxedOpcodeBranch (const MCInst & Inst) static
cc—Carry clear GE—Greater than or equal LS—Lower or same PL—Plus CS—Carry set GT—Greater than LT—Less than EQ—Equal HI—Higher MI—Minus VC—Overflow clear LE—Less than or equal NE—Not equal VS—Overflow set
Definition at line 97 of file M68kAsmBackend.cpp.
References llvm::MCInst::getOpcode().
Referenced by getRelaxedOpcode().