LLVM: lib/BinaryFormat/Magic.cpp File Reference
Magic.cpp File Reference
#include "llvm/BinaryFormat/Magic.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/BinaryFormat/COFF.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/BinaryFormat/MachO.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include <unistd.h>
Functions
template<size_t N>
static bool startswith (StringRef Magic, const char(&S)[N])
Function Documentation
startswith()
template<size_t N> static bool startswith (StringRef Magic, const char(&) S[N]) static
Definition at line 30 of file Magic.cpp.
References Magic, and N.
Referenced by llvm::StringRef::consume_front(), llvm::opt::OptTable::findByPrefix(), llvm::sys::detail::getHostCPUNameForARM(), llvm::sys::detail::getHostCPUNameForS390x(), llvm::identify_magic(), llvm::makePostTransformationMetadata(), and llvm::Triple::normalize().