LLVM: llvm::orc::shared::detail Namespace Reference
llvm::orc::shared::detail Namespace Reference
Classes
class AsyncCallResultHelper
class AsyncHandlerTraits
class AsyncHandlerTraits< Error(ResponseHandlerT, ArgTs...)>
class AsyncHandlerTraits< Error(std::function< Error(Error)>, ArgTs...)>
class AsyncHandlerTraits< Error(std::function< Error(Expected< ResultT >)>, ArgTs...)>
class AsyncHandlerTraits< ErrorSuccess(std::function< Error(Error)>, ArgTs...)>
class AsyncHandlerTraits< void(std::function< Error(Error)>, ArgTs...)>
class CanDeserialize
class CanSerialize
struct CWrapperFunctionResult
union CWrapperFunctionResultDataUnion
class HandlerTraits
class HandlerTraits< RetT(*)(ArgTs...)>
class HandlerTraits< RetT(ArgTs...)>
class HandlerTraits< RetT(Class::*)(ArgTs...) const >
class HandlerTraits< RetT(Class::*)(ArgTs...)>
class MemberFnWrapper
class ReadArgs
class ReadArgs< ArgT, ArgTs... >
class RespondHelper
class RespondHelper< false >
class RespondHelper< true >
class ResponseHandler
class ResponseHandlerArg
class ResponseHandlerArg< Error(Error)>
class ResponseHandlerArg< Error(Expected< ArgT >)>
class ResponseHandlerArg< ErrorSuccess(Error)>
class ResponseHandlerArg< ErrorSuccess(Expected< ArgT >)>
class ResponseHandlerImpl
class ResponseHandlerImpl< ChannelT, Error, HandlerT >
class ResponseHandlerImpl< ChannelT, Expected< FuncRetT >, HandlerT >
class ResponseHandlerImpl< ChannelT, void, HandlerT >
class ResultDeserializer
class ResultDeserializer< SPSError, Error >
class ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >
class ResultSerializer
class ResultSerializer< SPSRetTagT, Error >
class ResultSerializer< SPSRetTagT, Expected< T > >
class ResultTraits
class ResultTraits< Error >
class ResultTraits< Expected< RetT > >
class ResultTraits< void >
class RPCArgTypeCheck
class RPCArgTypeCheckHelper
class RPCArgTypeCheckHelper< P, std::tuple< T, Ts... >, std::tuple< U, Us... > >
class RPCArgTypeCheckHelper< P, std::tuple<>, std::tuple<> >
class RPCEndpointBase
Contains primitive utilities for defining, calling and handling calls to remote procedures.
class RPCFunctionArgsTuple
Provides a typedef for a tuple containing the decayed argument types.
class RPCFunctionArgsTuple< RetT(ArgTs...)>
class SequenceNumberManager
struct SPSSerializableError
Helper type for serializing Errors.
struct SPSSerializableExpected
Helper type for serializing Expected<T>s.
class SupportsErrorReturn
class SupportsErrorReturn< Error >
class SupportsErrorReturn< Expected< T > >
class WrappedHandlerReturn
class WrappedHandlerReturn< Error >
class WrappedHandlerReturn< ErrorSuccess >
class WrappedHandlerReturn< Expected< T > >
class WrappedHandlerReturn< void >
class WrapperFunctionAsyncHandlerHelper
class WrapperFunctionAsyncHandlerHelper< RetT(*)(ArgTs...), ResultSerializer, SPSTagTs... >
class WrapperFunctionAsyncHandlerHelper< RetT(ClassT::*)(ArgTs...) const, ResultSerializer, SPSTagTs... >
class WrapperFunctionAsyncHandlerHelper< RetT(ClassT::*)(ArgTs...), ResultSerializer, SPSTagTs... >
class WrapperFunctionAsyncHandlerHelper< RetT(SendResultT, ArgTs...), ResultSerializer, SPSTagTs... >
class WrapperFunctionHandlerCaller
class WrapperFunctionHandlerCaller< void >
class WrapperFunctionHandlerHelper
class WrapperFunctionHandlerHelper< RetT(*)(ArgTs...), ResultSerializer, SPSTagTs... >
class WrapperFunctionHandlerHelper< RetT(ArgTs...), ResultSerializer, SPSTagTs... >
class WrapperFunctionHandlerHelper< RetT(ClassT::*)(ArgTs...) const, ResultSerializer, SPSTagTs... >
class WrapperFunctionHandlerHelper< RetT(ClassT::*)(ArgTs...), ResultSerializer, SPSTagTs... >
Functions
template<typename WireRetT , typename HandlerRetT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT >
Error respond (ChannelT &C, const FunctionIdT &ResponseId, SequenceNumberT SeqNo, Expected< HandlerRetT > ResultOrErr)
template<typename WireRetT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT >
Error respond (ChannelT &C, const FunctionIdT &ResponseId, SequenceNumberT SeqNo, Error Err)
template<typename ChannelT , typename FuncRetT , typename HandlerT >
std::unique_ptr< ResponseHandler< ChannelT > > createResponseHandler (HandlerT H)
SPSSerializableError toSPSSerializable (Error Err)
Error fromSPSSerializable (SPSSerializableError BSE)
template<typename T >
SPSSerializableExpected< T > toSPSSerializable (Expected< T > E)
template<typename T >
Expected< T > fromSPSSerializable (SPSSerializableExpected< T > BSE)
template<typename SPSArgListT , typename... ArgTs>
WrapperFunctionResult serializeViaSPSToWrapperFunctionResult (const ArgTs &...Args)
Function Documentation
createResponseHandler()
template<typename ChannelT , typename FuncRetT , typename HandlerT > std::unique_ptr< ResponseHandler< ChannelT > > llvm::orc::shared::detail::createResponseHandler (HandlerT H)
Definition at line 774 of file RPCUtils.h.
References H.
fromSPSSerializable() [1/2]
Error llvm::orc::shared::detail::fromSPSSerializable (SPSSerializableError BSE) inline
Definition at line 423 of file SimplePackedSerialization.h.
References llvm::inconvertibleErrorCode(), and llvm::Error::success().
Referenced by llvm::orc::shared::detail::ResultDeserializer< SPSError, Error >::deserialize(), and llvm::orc::shared::detail::ResultDeserializer< SPSExpected< SPSTagT >, Expected< T > >::deserialize().
fromSPSSerializable() [2/2]
template<typename T > Expected< T > llvm::orc::shared::detail::fromSPSSerializable (SPSSerializableExpected< T > BSE)
Definition at line 438 of file SimplePackedSerialization.h.
References llvm::inconvertibleErrorCode().
respond() [1/2]
template<typename WireRetT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > Error llvm::orc::shared::detail::respond (ChannelT & C, const FunctionIdT & ResponseId, SequenceNumberT SeqNo, Error Err)
Definition at line 417 of file RPCUtils.h.
References C.
respond() [2/2]
template<typename WireRetT , typename HandlerRetT , typename ChannelT , typename FunctionIdT , typename SequenceNumberT > Error llvm::orc::shared::detail::respond (ChannelT & C, const FunctionIdT & ResponseId, SequenceNumberT SeqNo, Expected< HandlerRetT > ResultOrErr)
Definition at line 406 of file RPCUtils.h.
References C.
serializeViaSPSToWrapperFunctionResult()
template<typename SPSArgListT , typename... ArgTs> WrapperFunctionResult llvm::orc::shared::detail::serializeViaSPSToWrapperFunctionResult (const ArgTs &... Args)
Definition at line 176 of file WrapperFunctionUtils.h.
References llvm::orc::shared::WrapperFunctionResult::allocate(), and llvm::orc::shared::WrapperFunctionResult::createOutOfBandError().
Referenced by llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::call(), and llvm::orc::shared::WrapperFunction< SPSRetTagT(SPSTagTs...)>::callAsync().
toSPSSerializable() [1/2]
SPSSerializableError llvm::orc::shared::detail::toSPSSerializable (Error Err) inline
Definition at line 417 of file SimplePackedSerialization.h.
References llvm::toString().
Referenced by llvm::orc::shared::detail::ResultSerializer< SPSRetTagT, Error >::serialize(), and llvm::orc::shared::detail::ResultSerializer< SPSRetTagT, Expected< T > >::serialize().
toSPSSerializable() [2/2]
template<typename T > SPSSerializableExpected< T > llvm::orc::shared::detail::toSPSSerializable (Expected< T > E)
Definition at line 430 of file SimplePackedSerialization.h.
References E, and llvm::toString().