LLVM: llvm::DelimitedScope< Open, Close > Struct Template Reference
llvm::DelimitedScope< Open, Close > Struct Template Reference
#include "llvm/Support/ScopedPrinter.h"
Public Member Functions
DelimitedScope (ScopedPrinter &W)
DelimitedScope (ScopedPrinter &W, StringRef N)
~DelimitedScope ()
Public Attributes
ScopedPrinter & W
Detailed Description
template<char Open, char Close>
struct llvm::DelimitedScope< Open, Close >
Definition at line 353 of file ScopedPrinter.h.
Constructor & Destructor Documentation
DelimitedScope() [1/2]
template<char Open, char Close> llvm::DelimitedScope< Open, Close >::DelimitedScope (ScopedPrinter & W) inline explicit
Definition at line 354 of file ScopedPrinter.h.
References llvm::ScopedPrinter::indent(), llvm::ScopedPrinter::startLine(), and llvm::DelimitedScope< Open, Close >::W.
DelimitedScope() [2/2]
template<char Open, char Close> llvm::DelimitedScope< Open, Close >::DelimitedScope (ScopedPrinter & W, StringRef N) inline
Definition at line 359 of file ScopedPrinter.h.
References llvm::ScopedPrinter::getOStream(), llvm::ScopedPrinter::indent(), N, llvm::ScopedPrinter::startLine(), and llvm::DelimitedScope< Open, Close >::W.
~DelimitedScope()
template<char Open, char Close> llvm::DelimitedScope< Open, Close >::~DelimitedScope () inline
Definition at line 367 of file ScopedPrinter.h.
References llvm::ScopedPrinter::startLine(), llvm::ScopedPrinter::unindent(), and llvm::DelimitedScope< Open, Close >::W.
Member Data Documentation
W
template<char Open, char Close> ScopedPrinter& llvm::DelimitedScope< Open, Close >::W
Definition at line 372 of file ScopedPrinter.h.
Referenced by llvm::DelimitedScope< Open, Close >::DelimitedScope(), llvm::DelimitedScope< Open, Close >::DelimitedScope(), and llvm::DelimitedScope< Open, Close >::~DelimitedScope().
The documentation for this struct was generated from the following file:
include/llvm/Support/ScopedPrinter.h