LLVM: llvm::VPBlockUser Struct Reference
llvm::VPBlockUser Struct Reference
VPUsers instance used by VPBlockBase to manage CondBit and the block predicate.
#include "Transforms/Vectorize/VPlan.h"
Public Member Functions
VPBlockUser ()
VPValue * getSingleOperandOrNull ()
const VPValue * getSingleOperandOrNull () const
void resetSingleOpUser (VPValue *NewVal)
Public Member Functions inherited from llvm::VPUser
VPUser ()=delete
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
virtual ~VPUser ()
VPUserID getVPUserID () const
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
void removeLastOperand ()
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
Additional Inherited Members
Public Types inherited from llvm::VPUser
enum class VPUserID { Recipe , Block }
Subclass identifier (for isa/dyn_cast).
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Static Public Member Functions inherited from llvm::VPUser
static bool classof (const VPDef *Recipe)
Method to support type inquiry through isa, cast, and dyn_cast.
Protected Member Functions inherited from llvm::VPUser
void printOperands (raw_ostream &O, VPSlotTracker &SlotTracker) const
Print the operands to O.
VPUser (ArrayRef< VPValue * > Operands, VPUserID ID)
VPUser (std::initializer_list< VPValue * > Operands, VPUserID ID)
template<typename IterT >
VPUser (iterator_range< IterT > Operands, VPUserID ID)
Detailed Description
VPUsers instance used by VPBlockBase to manage CondBit and the block predicate.
Currently VPBlockUsers are used in VPBlockBase for historical reasons, but in the future the only VPUsers should either be recipes or live-outs.VPBlockBase uses.
Definition at line 355 of file VPlan.h.
Constructor & Destructor Documentation
VPBlockUser()
llvm::VPBlockUser::VPBlockUser () inline
Definition at line 356 of file VPlan.h.
Member Function Documentation
getSingleOperandOrNull() [1/2]
VPValue * llvm::VPBlockUser::getSingleOperandOrNull () inline
Definition at line 358 of file VPlan.h.
References llvm::VPUser::getNumOperands(), and llvm::VPUser::getOperand().
Referenced by llvm::VPBlockBase::getCondBit(), llvm::VPBlockBase::getCondBit(), llvm::VPBlockBase::getPredicate(), and llvm::VPBlockBase::getPredicate().
getSingleOperandOrNull() [2/2]
const VPValue * llvm::VPBlockUser::getSingleOperandOrNull () const inline
Definition at line 364 of file VPlan.h.
References llvm::VPUser::getNumOperands(), and llvm::VPUser::getOperand().
resetSingleOpUser()
void llvm::VPBlockUser::resetSingleOpUser (VPValue * NewVal) inline
Definition at line 371 of file VPlan.h.
References llvm::VPUser::addOperand(), assert(), llvm::VPUser::getNumOperands(), llvm::VPUser::removeLastOperand(), and llvm::VPUser::setOperand().
Referenced by llvm::VPBlockBase::setCondBit(), and llvm::VPBlockBase::setPredicate().
The documentation for this struct was generated from the following file:
lib/Transforms/Vectorize/VPlan.h