LLVM: llvm::ArgDescriptor Struct Reference
llvm::ArgDescriptor Struct Reference
#include "Target/AMDGPU/AMDGPUArgumentUsageInfo.h"
Public Member Functions
constexpr ArgDescriptor (unsigned Val=0, unsigned Mask=~0u, bool IsStack=false, bool IsSet=false)
bool isSet () const
operator bool () const
bool isRegister () const
MCRegister getRegister () const
unsigned getStackOffset () const
unsigned getMask () const
bool isMasked () const
void print (raw_ostream &OS, const TargetRegisterInfo *TRI=nullptr) const
Static Public Member Functions
static constexpr ArgDescriptor createRegister (Register Reg, unsigned Mask=~0u)
static constexpr ArgDescriptor createStack (unsigned Offset, unsigned Mask=~0u)
static constexpr ArgDescriptor createArg (const ArgDescriptor &Arg, unsigned Mask)
Friends
struct AMDGPUFunctionArgInfo
class AMDGPUArgumentUsageInfo
Detailed Description
Definition at line 23 of file AMDGPUArgumentUsageInfo.h.
Constructor & Destructor Documentation
ArgDescriptor()
constexpr llvm::ArgDescriptor::ArgDescriptor (unsigned Val = 0, unsigned Mask = ~0u, bool IsStack = false, bool IsSet = false) inline constexpr
Definition at line 40 of file AMDGPUArgumentUsageInfo.h.
Referenced by createArg(), createRegister(), and createStack().
Member Function Documentation
createArg()
static constexpr ArgDescriptor llvm::ArgDescriptor::createArg (const ArgDescriptor & Arg, unsigned Mask) inline static constexpr
Definition at line 54 of file AMDGPUArgumentUsageInfo.h.
References Arg, and ArgDescriptor().
Referenced by allocateVGPR32Input(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), llvm::SITargetLowering::passSpecialInputs(), and llvm::AMDGPUCallLowering::passSpecialInputs().
createRegister()
static constexpr ArgDescriptor llvm::ArgDescriptor::createRegister (Register Reg, unsigned Mask = ~0u) inline static constexpr
Definition at line 44 of file AMDGPUArgumentUsageInfo.h.
References ArgDescriptor().
Referenced by llvm::SIMachineFunctionInfo::addDispatchID(), llvm::SIMachineFunctionInfo::addDispatchPtr(), llvm::SIMachineFunctionInfo::addFlatScratchInit(), llvm::SIMachineFunctionInfo::addImplicitBufferPtr(), llvm::SIMachineFunctionInfo::addKernargSegmentPtr(), llvm::SIMachineFunctionInfo::addPrivateSegmentBuffer(), llvm::SIMachineFunctionInfo::addPrivateSegmentWaveByteOffset(), llvm::SIMachineFunctionInfo::addQueuePtr(), llvm::SIMachineFunctionInfo::addWorkGroupIDX(), llvm::SIMachineFunctionInfo::addWorkGroupIDY(), llvm::SIMachineFunctionInfo::addWorkGroupIDZ(), llvm::SIMachineFunctionInfo::addWorkGroupInfo(), allocateSGPR32InputImpl(), llvm::SITargetLowering::allocateSpecialEntryInputVGPRs(), llvm::SITargetLowering::allocateSpecialInputVGPRsFixed(), allocateVGPR32Input(), llvm::AMDGPUFunctionArgInfo::fixedABILayout(), llvm::GCNTargetMachine::parseMachineFunctionInfo(), llvm::SIMachineFunctionInfo::setPrivateSegmentWaveByteOffset(), and llvm::SIMachineFunctionInfo::SIMachineFunctionInfo().
createStack()
static constexpr ArgDescriptor llvm::ArgDescriptor::createStack (unsigned Offset, unsigned Mask = ~0u) inline static constexpr
Definition at line 49 of file AMDGPUArgumentUsageInfo.h.
References ArgDescriptor(), and Offset.
Referenced by allocateVGPR32Input(), and llvm::GCNTargetMachine::parseMachineFunctionInfo().
getMask()
unsigned llvm::ArgDescriptor::getMask () const inline
Definition at line 81 of file AMDGPUArgumentUsageInfo.h.
getRegister()
MCRegister llvm::ArgDescriptor::getRegister () const inline
Definition at line 71 of file AMDGPUArgumentUsageInfo.h.
References assert(), and Reg.
Referenced by llvm::SIMachineFunctionInfo::addDispatchID(), llvm::SIMachineFunctionInfo::addDispatchPtr(), llvm::SIMachineFunctionInfo::addFlatScratchInit(), llvm::SIMachineFunctionInfo::addImplicitBufferPtr(), llvm::SIMachineFunctionInfo::addKernargSegmentPtr(), llvm::SIMachineFunctionInfo::addPrivateSegmentBuffer(), llvm::SIMachineFunctionInfo::addPrivateSegmentWaveByteOffset(), llvm::SIMachineFunctionInfo::addQueuePtr(), llvm::SIMachineFunctionInfo::addWorkGroupIDX(), llvm::SIMachineFunctionInfo::addWorkGroupIDY(), llvm::SIMachineFunctionInfo::addWorkGroupIDZ(), llvm::SIMachineFunctionInfo::addWorkGroupInfo(), llvm::SIMachineFunctionInfo::getImplicitBufferPtrUserSGPR(), llvm::SIMachineFunctionInfo::getPrivateSegmentWaveByteOffsetSystemSGPR(), llvm::SIMachineFunctionInfo::getQueuePtrUserSGPR(), and llvm::SIMachineFunctionInfo::getWorkGroupIDSGPR().
getStackOffset()
unsigned llvm::ArgDescriptor::getStackOffset () const inline
Definition at line 76 of file AMDGPUArgumentUsageInfo.h.
References assert(), and StackOffset.
isMasked()
bool llvm::ArgDescriptor::isMasked () const inline
Definition at line 85 of file AMDGPUArgumentUsageInfo.h.
isRegister()
bool llvm::ArgDescriptor::isRegister () const inline
Definition at line 67 of file AMDGPUArgumentUsageInfo.h.
isSet()
bool llvm::ArgDescriptor::isSet () const inline
Definition at line 59 of file AMDGPUArgumentUsageInfo.h.
Referenced by operator bool().
operator bool()
llvm::ArgDescriptor::operator bool () const inline explicit
Definition at line 63 of file AMDGPUArgumentUsageInfo.h.
References isSet().
print()
void llvm::ArgDescriptor::print (raw_ostream & OS, const TargetRegisterInfo * TRI = nullptr) const
Friends And Related Symbol Documentation
AMDGPUArgumentUsageInfo
friend class AMDGPUArgumentUsageInfo friend
Definition at line 26 of file AMDGPUArgumentUsageInfo.h.
AMDGPUFunctionArgInfo
friend struct AMDGPUFunctionArgInfo friend
Definition at line 25 of file AMDGPUArgumentUsageInfo.h.
Member Data Documentation
Reg
MCRegister llvm::ArgDescriptor::Reg
Definition at line 29 of file AMDGPUArgumentUsageInfo.h.
Referenced by getRegister().
StackOffset
unsigned llvm::ArgDescriptor::StackOffset
Definition at line 30 of file AMDGPUArgumentUsageInfo.h.
Referenced by getStackOffset().
The documentation for this struct was generated from the following file:
lib/Target/AMDGPU/AMDGPUArgumentUsageInfo.h