LLVM: AAMemoryBehaviorArgument Struct Reference
AAMemoryBehaviorArgument Struct Reference
Memory behavior attribute for function argument.
Public Member Functions
AAMemoryBehaviorArgument (const IRPosition &IRP, Attributor &A)
void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
ChangeStatus manifest (Attributor &A) override
Hook for the Attributor to trigger the manifestation of the information represented by the abstract attribute in the LLVM-IR.
void trackStatistics () const override
See AbstractAttribute::trackStatistics()
Public Member Functions inherited from AAMemoryBehaviorFloating
AAMemoryBehaviorFloating (const IRPosition &IRP, Attributor &A)
ChangeStatus updateImpl (Attributor &A) override
See AbstractAttribute::updateImpl(...).
void trackStatistics () const override
See AbstractAttribute::trackStatistics()
Public Member Functions inherited from AAMemoryBehaviorImpl
AAMemoryBehaviorImpl (const IRPosition &IRP, Attributor &A)
void initialize (Attributor &A) override
See AbstractAttribute::initialize(...).
void getDeducedAttributes (LLVMContext &Ctx, SmallVectorImpl< Attribute > &Attrs) const override
See AbstractAttribute::getDeducedAttributes(...).
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
const std::string getAsStr () const override
See AbstractState::getAsStr().
Public Member Functions inherited from llvm::AAMemoryBehavior
AAMemoryBehavior (const IRPosition &IRP, Attributor &A)
bool isKnownReadNone () const
Return true if we know that the underlying value is not read or accessed in its respective scope.
bool isAssumedReadNone () const
Return true if we assume that the underlying value is not read or accessed in its respective scope.
bool isKnownReadOnly () const
Return true if we know that the underlying value is not accessed (=written) in its respective scope.
bool isAssumedReadOnly () const
Return true if we assume that the underlying value is not accessed (=written) in its respective scope.
bool isKnownWriteOnly () const
Return true if we know that the underlying value is not read in its respective scope.
bool isAssumedWriteOnly () const
Return true if we assume that the underlying value is not read in its respective scope.
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::IRAttribute< Attribute::ReadNone, StateWrapper< BitIntegerState< uint8_t, 3 >, AbstractAttribute > >
IRAttribute (const IRPosition &IRP)
ChangeStatus manifest (Attributor &A) override
See AbstractAttribute::manifest(...).
Attribute::AttrKind getAttrKind () const
Return the kind that identifies the abstract attribute implementation.
Public Member Functions inherited from llvm::StateWrapper< BitIntegerState< uint8_t, 3 >, AbstractAttribute >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const StateType & getState () const override
See AbstractAttribute::getState(...).
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (const IRPosition &IRP)
virtual ~AbstractAttribute ()
Virtual destructor.
const IRPosition & getIRPosition () const
Return an IR position, see struct IRPosition.
IRPosition & getIRPosition ()
void print (raw_ostream &OS) const override
Helper functions, for debug purposes only.
virtual void printWithDeps (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::IRPosition
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getCalleeArgNo () const
Return the callee argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
int getCallSiteArgNo () const
Return the call site argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Kind getPositionKind () const
Return the associated position kind.
bool hasAttr (ArrayRef< Attribute::AttrKind > AKs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
TODO: Figure out if the attribute related helper functions should live here or somewhere else.
void getAttrs (ArrayRef< Attribute::AttrKind > AKs, SmallVectorImpl< Attribute > &Attrs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
Return the attributes of any kind in AKs existing in the IR at a position that will affect this one.
void removeAttrs (ArrayRef< Attribute::AttrKind > AKs) const
Remove the attribute of kind AKs existing in the IR at this position.
bool isAnyCallSitePosition () const
bool isArgumentPosition () const
Return true if the position is an argument or call site argument.
IRPosition stripCallBaseContext () const
Return the same position without the call base context.
const CallBaseContext * getCallBaseContext () const
Get the call base context from the position.
bool hasCallBaseContext () const
Check if the position has any call base context.
operator void * () const
}
Public Member Functions inherited from llvm::AADepGraphNode
virtual ~AADepGraphNode ()
aaiterator begin ()
aaiterator end ()
iterator child_begin ()
iterator child_end ()
TinyPtrVector< DepTy > & getDeps ()
Public Member Functions inherited from llvm::BitIntegerState< uint8_t, 3 >
bool isKnown (base_t BitsEncoding) const
Return true if the bits set in BitsEncoding are "known bits".
bool isAssumed (base_t BitsEncoding) const
Return true if the bits set in BitsEncoding are "assumed bits".
BitIntegerState & addKnownBits (base_t Bits)
Add the bits in BitsEncoding to the "known bits".
BitIntegerState & removeAssumedBits (base_t BitsEncoding)
Remove the bits in BitsEncoding from the "assumed bits" if not known.
BitIntegerState & removeKnownBits (base_t BitsEncoding)
Remove the bits in BitsEncoding from the "known bits".
BitIntegerState & intersectAssumedBits (base_t BitsEncoding)
Keep only "assumed bits" also set in BitsEncoding but all known ones.
Public Member Functions inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
IntegerStateBase ()
IntegerStateBase (base_t Assumed)
bool isValidState () const override
See AbstractState::isValidState() NOTE: For now we simply pretend that the worst possible state is invalid.
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint()
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
base_t getKnown () const
Return the known state encoding.
base_t getAssumed () const
Return the assumed state encoding.
bool operator== (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Equality for IntegerStateBase.
bool operator!= (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Inequality for IntegerStateBase.
void operator^= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator+= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator|= (const IntegerStateBase< base_t, BestState, WorstState > &R)
void operator&= (const IntegerStateBase< base_t, BestState, WorstState > &R)
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()
Additional Inherited Members
Public Types inherited from llvm::AAMemoryBehavior
enum { NO_READS = 1 << 0 , NO_WRITES = 1 << 1 , NO_ACCESSES = NO_READS | NO_WRITES , BEST_STATE = NO_ACCESSES }
State encoding bits.
Public Types inherited from llvm::StateWrapper< BitIntegerState< uint8_t, 3 >, AbstractAttribute >
using StateType
Provide static access to the type of the state.
Public Types inherited from llvm::AbstractAttribute
using StateType = AbstractState
Public Types inherited from llvm::IRPosition
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
using CallBaseContext = CallBase
Public Types inherited from llvm::AADepGraphNode
using DepTy = PointerIntPair<AADepGraphNode *, 1>
using iterator
using aaiterator
Public Types inherited from llvm::BitIntegerState< uint8_t, 3 >
using base_t
Public Types inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
using base_t = base_ty
Static Public Member Functions inherited from AAMemoryBehaviorImpl
static void getKnownStateFromValue (const IRPosition &IRP, BitIntegerState &State, bool IgnoreSubsumingPositions=false)
Return the memory behavior information encoded in the IR for IRP.
Static Public Member Functions inherited from llvm::AAMemoryBehavior
static AAMemoryBehavior & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAMemoryBehavior.
Static Public Member Functions inherited from llvm::AbstractAttribute
static bool classof (const AADepGraphNode *DGN)
This function is used to identify if an DGN is of type AbstractAttribute so that the dyn_cast and cast can use such information to cast an AADepGraphNode to an AbstractAttribute.
Static Public Member Functions inherited from llvm::IRPosition
static const IRPosition value (const Value &V, const CallBaseContext *CBContext=nullptr)
Create a position describing the value of V.
static const IRPosition function (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F, const CallBaseContext *CBContext=nullptr)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg, const CallBaseContext *CBContext=nullptr)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP, const CallBaseContext *CBContext=nullptr)
Create a position with function scope matching the "context" of IRP.
Static Public Member Functions inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
static constexpr base_t getBestState ()
Return the best possible representable state.
static constexpr base_t getBestState (const IntegerStateBase &)
static constexpr base_t getWorstState ()
Return the worst possible representable state.
static constexpr base_t getWorstState (const IntegerStateBase &)
Static Public Attributes inherited from AAMemoryBehaviorImpl
static const Attribute::AttrKind AttrKinds [3]
The set of IR attributes AAMemoryBehavior deals with.
Static Public Attributes inherited from llvm::AAMemoryBehavior
static const char ID = 0
Unique ID (due to the unique address)
Static Public Attributes inherited from llvm::IRPosition
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
Protected Member Functions inherited from llvm::AADepGraphNode
operator AbstractAttribute * ()
Protected Member Functions inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
virtual void handleNewAssumedValue (base_t Value)=0
Handle a new assumed value Value. Subtype dependent.
virtual void handleNewKnownValue (base_t Value)=0
Handle a new known value Value. Subtype dependent.
virtual void joinOR (base_t AssumedValue, base_t KnownValue)=0
Handle a value Value. Subtype dependent.
virtual void joinAND (base_t AssumedValue, base_t KnownValue)=0
Handle a new assumed value Value. Subtype dependent.
Static Protected Member Functions inherited from llvm::AADepGraphNode
static AADepGraphNode * DepGetVal (DepTy &DT)
static AbstractAttribute * DepGetValAA (DepTy &DT)
Protected Attributes inherited from llvm::AADepGraphNode
TinyPtrVector< DepTy > Deps
Set of dependency graph nodes which should be updated if this one is updated.
Protected Attributes inherited from llvm::IntegerStateBase< base_ty, BestState, WorstState >
base_t Known = getWorstState()
The known state encoding in an integer of type base_t.
base_t Assumed = getBestState()
The assumed state encoding in an integer of type base_t.
Detailed Description
Memory behavior attribute for function argument.
Definition at line 7010 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
AAMemoryBehaviorArgument()
AAMemoryBehaviorArgument::AAMemoryBehaviorArgument (const IRPosition & IRP, Attributor & A) inline
Definition at line 7011 of file AttributorAttributes.cpp.
Member Function Documentation
initialize()
void AAMemoryBehaviorArgument::initialize (Attributor & A) inline override virtual
See AbstractAttribute::initialize(...).
Reimplemented from llvm::IRAttribute< Attribute::ReadNone, StateWrapper< BitIntegerState< uint8_t, 3 >, AbstractAttribute > >.
Reimplemented in AAMemoryBehaviorCallSiteArgument.
Definition at line 7015 of file AttributorAttributes.cpp.
References A, and Arg.
Referenced by AAMemoryBehaviorCallSiteArgument::initialize().
manifest()
ChangeStatus AAMemoryBehaviorArgument::manifest (Attributor & A) inline override virtual
Hook for the Attributor to trigger the manifestation of the information represented by the abstract attribute in the LLVM-IR.
\Return CHANGED if the IR was altered, otherwise UNCHANGED.
Reimplemented from llvm::AbstractAttribute.
Definition at line 7032 of file AttributorAttributes.cpp.
References A, getType(), and llvm::AbstractAttribute::manifest().
trackStatistics()
void AAMemoryBehaviorArgument::trackStatistics () const inline override virtual
See AbstractAttribute::trackStatistics()
Implements llvm::AbstractAttribute.
Reimplemented in AAMemoryBehaviorCallSiteArgument.
Definition at line 7047 of file AttributorAttributes.cpp.
References STATS_DECLTRACK_ARG_ATTR.
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp