LLVM: llvm::WholeProgramDevirtPass Struct Reference
llvm::WholeProgramDevirtPass Struct Reference
#include "llvm/Transforms/IPO/WholeProgramDevirt.h"
Public Member Functions
WholeProgramDevirtPass ()
WholeProgramDevirtPass (ModuleSummaryIndex *ExportSummary, const ModuleSummaryIndex *ImportSummary)
PreservedAnalyses run (Module &M, ModuleAnalysisManager &)
Public Attributes
ModuleSummaryIndex * ExportSummary
const ModuleSummaryIndex * ImportSummary
bool UseCommandLine = false
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< WholeProgramDevirtPass >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 223 of file WholeProgramDevirt.h.
Constructor & Destructor Documentation
WholeProgramDevirtPass() [1/2]
llvm::WholeProgramDevirtPass::WholeProgramDevirtPass () inline
Definition at line 227 of file WholeProgramDevirt.h.
WholeProgramDevirtPass() [2/2]
llvm::WholeProgramDevirtPass::WholeProgramDevirtPass (ModuleSummaryIndex * ExportSummary, const ModuleSummaryIndex * ImportSummary) inline
Definition at line 229 of file WholeProgramDevirt.h.
References assert(), ExportSummary, and ImportSummary.
Member Function Documentation
run()
PreservedAnalyses WholeProgramDevirtPass::run (Module & M, ModuleAnalysisManager & AM)
Definition at line 758 of file WholeProgramDevirt.cpp.
References llvm::PreservedAnalyses::all(), F, FAM, llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), and llvm::PreservedAnalyses::none().
Member Data Documentation
ExportSummary
ModuleSummaryIndex* llvm::WholeProgramDevirtPass::ExportSummary
Definition at line 224 of file WholeProgramDevirt.h.
Referenced by WholeProgramDevirtPass().
ImportSummary
const ModuleSummaryIndex* llvm::WholeProgramDevirtPass::ImportSummary
Definition at line 225 of file WholeProgramDevirt.h.
Referenced by WholeProgramDevirtPass().
UseCommandLine
bool llvm::WholeProgramDevirtPass::UseCommandLine = false
Definition at line 226 of file WholeProgramDevirt.h.
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/WholeProgramDevirt.h
lib/Transforms/IPO/WholeProgramDevirt.cpp