LLVM: llvm::RegisterTarget< TargetArchType, HasJIT > Struct Template Reference
llvm::RegisterTarget< TargetArchType, HasJIT > Struct Template Reference
RegisterTarget - Helper template for registering a target, for use in the target's initialization function.
#include "llvm/Support/TargetRegistry.h"
Public Member Functions
RegisterTarget (Target &T, const char *Name, const char *Desc, const char *BackendName)
Static Public Member Functions
static bool getArchMatch (Triple::ArchType Arch)
Detailed Description
template<Triple::ArchType TargetArchType = Triple::UnknownArch, bool HasJIT = false>
struct llvm::RegisterTarget< TargetArchType, HasJIT >
RegisterTarget - Helper template for registering a target, for use in the target's initialization function.
Usage:
Target &getTheFooTarget() { // The global target instance. static Target TheFooTarget; return TheFooTarget; } extern "C" void LLVMInitializeFooTargetInfo() { RegisterTarget<Triple::foo> X(getTheFooTarget(), "foo", "Foo description", "Foo" /* Backend Name *‍/); }
Definition at line 981 of file TargetRegistry.h.
Constructor & Destructor Documentation
RegisterTarget()
template<Triple::ArchType TargetArchType = Triple::UnknownArch, bool HasJIT = false> llvm::RegisterTarget< TargetArchType, HasJIT >::RegisterTarget (Target & T, const char * Name, const char * Desc, const char * BackendName) inline
Definition at line 982 of file TargetRegistry.h.
References llvm::RegisterTarget< TargetArchType, HasJIT >::getArchMatch(), Name, and llvm::TargetRegistry::RegisterTarget().
Member Function Documentation
getArchMatch()
template<Triple::ArchType TargetArchType = Triple::UnknownArch, bool HasJIT = false> static bool llvm::RegisterTarget< TargetArchType, HasJIT >::getArchMatch (Triple::ArchType Arch) inline static
Definition at line 988 of file TargetRegistry.h.
Referenced by llvm::RegisterTarget< TargetArchType, HasJIT >::RegisterTarget().
The documentation for this struct was generated from the following file:
include/llvm/Support/TargetRegistry.h