LLVM: AACallSiteReturnedFromReturned< AAType, BaseType, StateType, IntroduceCallBaseContext > Struct Template Reference
AACallSiteReturnedFromReturned< AAType, BaseType, StateType, IntroduceCallBaseContext > Struct Template Reference
Helper class for generic replication: function returned -> cs returned.
Public Member Functions
AACallSiteReturnedFromReturned (const IRPosition &IRP, Attributor &A)
ChangeStatus updateImpl (Attributor &A) override
See AbstractAttribute::updateImpl(...).
Detailed Description
template<typename AAType, typename BaseType, typename StateType = typename BaseType::StateType, bool IntroduceCallBaseContext = false>
struct AACallSiteReturnedFromReturned< AAType, BaseType, StateType, IntroduceCallBaseContext >
Helper class for generic replication: function returned -> cs returned.
Definition at line 636 of file AttributorAttributes.cpp.
Constructor & Destructor Documentation
AACallSiteReturnedFromReturned()
template<typename AAType , typename BaseType , typename StateType = typename BaseType::StateType, bool IntroduceCallBaseContext = false> AACallSiteReturnedFromReturned< AAType, BaseType, StateType, IntroduceCallBaseContext >::AACallSiteReturnedFromReturned (const IRPosition & IRP, Attributor & A) inline
Definition at line 637 of file AttributorAttributes.cpp.
Member Function Documentation
updateImpl()
template<typename AAType , typename BaseType , typename StateType = typename BaseType::StateType, bool IntroduceCallBaseContext = false> ChangeStatus AACallSiteReturnedFromReturned< AAType, BaseType, StateType, IntroduceCallBaseContext >::updateImpl (Attributor & A) inline override
See AbstractAttribute::updateImpl(...).
Definition at line 641 of file AttributorAttributes.cpp.
References A, assert(), llvm::clampStateAndIndicateChange(), llvm::dbgs(), llvm::IRPosition::IRP_CALL_SITE_RETURNED, LLVM_DEBUG, and llvm::IRPosition::returned().
The documentation for this struct was generated from the following file:
lib/Transforms/IPO/AttributorAttributes.cpp