LLVM: lib/Target/WebAssembly/WebAssemblyAsmPrinter.cpp File Reference
WebAssemblyAsmPrinter.cpp File Reference
This file contains a printer that converts from our internal representation of machine-dependent LLVM code to the WebAssembly assembly language.
#include "WebAssemblyAsmPrinter.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "MCTargetDesc/WebAssemblyTargetStreamer.h"
#include "TargetInfo/WebAssemblyTargetInfo.h"
#include "Utils/WebAssemblyTypeUtilities.h"
#include "Utils/WebAssemblyUtilities.h"
#include "WebAssembly.h"
#include "WebAssemblyMCInstLower.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "WebAssemblyRegisterInfo.h"
#include "WebAssemblyRuntimeLibcallSignatures.h"
#include "WebAssemblyTargetMachine.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/BinaryFormat/Wasm.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Metadata.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSectionWasm.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCSymbolWasm.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
static bool isEmscriptenInvokeName (StringRef Name)
static char getInvokeSig (wasm::ValType VT)
static std::string getEmscriptenInvokeSymbolName (wasm::WasmSignature *Sig)
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyAsmPrinter ()
Variables
cl::opt< bool > WasmKeepRegisters
cl::opt< bool > EnableEmException
cl::opt< bool > EnableEmSjLj
Detailed Description
This file contains a printer that converts from our internal representation of machine-dependent LLVM code to the WebAssembly assembly language.
Definition in file WebAssemblyAsmPrinter.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "asm-printer"
Definition at line 51 of file WebAssemblyAsmPrinter.cpp.
Function Documentation
getEmscriptenInvokeSymbolName()
static std::string getEmscriptenInvokeSymbolName (wasm::WasmSignature * Sig) static
Definition at line 134 of file WebAssemblyAsmPrinter.cpp.
References assert(), E, llvm::SmallVectorBase< Size_T >::empty(), getInvokeSig(), I, llvm::wasm::WasmSignature::Params, llvm::wasm::WasmSignature::Returns, and llvm::SmallVectorBase< Size_T >::size().
Referenced by llvm::WebAssemblyAsmPrinter::getMCSymbolForFunction().
getInvokeSig()
static char getInvokeSig (wasm::ValType VT) static
Definition at line 112 of file WebAssemblyAsmPrinter.cpp.
References llvm::wasm::EXTERNREF, llvm::wasm::F32, llvm::wasm::F64, llvm::wasm::FUNCREF, llvm::wasm::I32, llvm::wasm::I64, llvm_unreachable, and llvm::wasm::V128.
Referenced by getEmscriptenInvokeSymbolName().
isEmscriptenInvokeName()
static bool isEmscriptenInvokeName (StringRef Name) static
Definition at line 104 of file WebAssemblyAsmPrinter.cpp.
References Name.
Referenced by llvm::WebAssemblyAsmPrinter::getMCSymbolForFunction().
LLVMInitializeWebAssemblyAsmPrinter()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyAsmPrinter ()
Definition at line 670 of file WebAssemblyAsmPrinter.cpp.
References llvm::getTheWebAssemblyTarget32(), llvm::getTheWebAssemblyTarget64(), X, and Y.
Variable Documentation
EnableEmException
cl::opt<bool> EnableEmException extern
Referenced by llvm::WebAssemblyAsmPrinter::emitExternalDecls().
EnableEmSjLj
cl::opt<bool> EnableEmSjLj extern
Referenced by llvm::WebAssemblyAsmPrinter::emitExternalDecls().
WasmKeepRegisters
cl::opt<bool> WasmKeepRegisters extern
Referenced by llvm::WebAssemblyMCInstLower::lower().