LLVM: lib/Target/WebAssembly/WebAssemblyTargetMachine.cpp File Reference
WebAssemblyTargetMachine.cpp File Reference
This file defines the WebAssembly-specific subclass of TargetMachine.
#include "WebAssemblyTargetMachine.h"
#include "MCTargetDesc/WebAssemblyMCTargetDesc.h"
#include "TargetInfo/WebAssemblyTargetInfo.h"
#include "WebAssembly.h"
#include "WebAssemblyMachineFunctionInfo.h"
#include "WebAssemblyTargetObjectFile.h"
#include "WebAssemblyTargetTransformInfo.h"
#include "llvm/CodeGen/MIRParser/MIParser.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/RegAllocRegistry.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Scalar/LowerAtomic.h"
#include "llvm/Transforms/Utils.h"
Macros
#define DEBUG_TYPE "wasm"
Functions
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyTarget ()
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM, const Triple &TT)
Variables
cl::opt< bool > EnableEmException ("enable-emscripten-cxx-exceptions", cl::desc("WebAssembly Emscripten-style exception handling"), cl::init(false))
cl::opt< bool > EnableEmSjLj ("enable-emscripten-sjlj", cl::desc("WebAssembly Emscripten-style setjmp/longjmp handling"), cl::init(false))
static cl::opt< bool > WasmDisableExplicitLocals ("wasm-disable-explicit-locals", cl::Hidden, cl::desc("WebAssembly: output implicit locals in" " instruction output for test purposes only."), cl::init(false))
Detailed Description
This file defines the WebAssembly-specific subclass of TargetMachine.
Definition in file WebAssemblyTargetMachine.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "wasm"
Definition at line 34 of file WebAssemblyTargetMachine.cpp.
Function Documentation
getEffectiveRelocModel()
static Reloc::Model getEffectiveRelocModel (Optional< Reloc::Model > RM, const Triple & TT) static
Definition at line 98 of file WebAssemblyTargetMachine.cpp.
References llvm::Reloc::Static.
LLVMInitializeWebAssemblyTarget()
LLVM_EXTERNAL_VISIBILITY void LLVMInitializeWebAssemblyTarget ()
Definition at line 58 of file WebAssemblyTargetMachine.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::getTheWebAssemblyTarget32(), llvm::getTheWebAssemblyTarget64(), llvm::initializeFixFunctionBitcastsPass(), llvm::initializeLowerGlobalDtorsPass(), llvm::initializeOptimizeReturnedPass(), llvm::initializeWebAssemblyAddMissingPrototypesPass(), llvm::initializeWebAssemblyArgumentMovePass(), llvm::initializeWebAssemblyCFGSortPass(), llvm::initializeWebAssemblyCFGStackifyPass(), llvm::initializeWebAssemblyDebugFixupPass(), llvm::initializeWebAssemblyExceptionInfoPass(), llvm::initializeWebAssemblyExplicitLocalsPass(), llvm::initializeWebAssemblyFixIrreducibleControlFlowPass(), llvm::initializeWebAssemblyLateEHPreparePass(), llvm::initializeWebAssemblyLowerBrUnlessPass(), llvm::initializeWebAssemblyLowerEmscriptenEHSjLjPass(), llvm::initializeWebAssemblyMCLowerPrePassPass(), llvm::initializeWebAssemblyMemIntrinsicResultsPass(), llvm::initializeWebAssemblyNullifyDebugValueListsPass(), llvm::initializeWebAssemblyOptimizeLiveIntervalsPass(), llvm::initializeWebAssemblyPeepholePass(), llvm::initializeWebAssemblyPrepareForLiveIntervalsPass(), llvm::initializeWebAssemblyRegColoringPass(), llvm::initializeWebAssemblyRegNumberingPass(), llvm::initializeWebAssemblyRegStackifyPass(), llvm::initializeWebAssemblyReplacePhysRegsPass(), llvm::initializeWebAssemblySetP2AlignOperandsPass(), X, and Y.
Variable Documentation
EnableEmException
cl::opt< bool > EnableEmException("enable-emscripten-cxx-exceptions", cl::desc("WebAssembly Emscripten-style exception handling"), cl::init(false)) ("enable-emscripten-cxx-exceptions" , cl::desc("WebAssembly Emscripten-style exception handling") , cl::init(false))
EnableEmSjLj
cl::opt< bool > EnableEmSjLj("enable-emscripten-sjlj", cl::desc("WebAssembly Emscripten-style setjmp/longjmp handling"), cl::init(false)) ("enable-emscripten-sjlj" , cl::desc("WebAssembly Emscripten-style setjmp/longjmp handling") , cl::init(false))
WasmDisableExplicitLocals
cl::opt< bool > WasmDisableExplicitLocals("wasm-disable-explicit-locals", cl::Hidden, cl::desc("WebAssembly: output implicit locals in" " instruction output for test purposes only."), cl::init(false)) ("wasm-disable-explicit-locals" , cl::Hidden , cl::desc("WebAssembly: output implicit locals in" " instruction output for test purposes only.") , cl::init(false)) static