LLVM: lib/Target/AArch64/AArch64PBQPRegAlloc.cpp File Reference
AArch64PBQPRegAlloc.cpp File Reference
#include "AArch64PBQPRegAlloc.h"
#include "AArch64.h"
#include "AArch64RegisterInfo.h"
#include "llvm/CodeGen/LiveIntervals.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegAllocPBQP.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "aarch64-pbqp"
Functions
static bool regJustKilledBefore (const LiveIntervals &LIs, unsigned reg, const MachineInstr &MI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "aarch64-pbqp"
Definition at line 17 of file AArch64PBQPRegAlloc.cpp.
Function Documentation
regJustKilledBefore()
static bool regJustKilledBefore (const LiveIntervals & LIs, unsigned reg, const MachineInstr & MI) static
Definition at line 319 of file AArch64PBQPRegAlloc.cpp.
References llvm::LiveRange::expiredAt(), llvm::LiveIntervals::getInstructionIndex(), llvm::LiveIntervals::getInterval(), MI, and SI.
Referenced by llvm::A57ChainingConstraint::apply().