LLVM: lib/Target/AMDGPU/AMDGPUAsmPrinter.cpp File Reference
AMDGPUAsmPrinter.cpp File Reference
The AMDGPUAsmPrinter is used to print both assembly string and also binary code.
#include "AMDGPUAsmPrinter.h"
#include "AMDGPU.h"
#include "AMDGPUSubtarget.h"
#include "AMDGPUTargetMachine.h"
#include "MCTargetDesc/AMDGPUInstPrinter.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "MCTargetDesc/AMDGPUTargetStreamer.h"
#include "R600AsmPrinter.h"
#include "R600Defines.h"
#include "R600MachineFunctionInfo.h"
#include "R600RegisterInfo.h"
#include "SIDefines.h"
#include "SIInstrInfo.h"
#include "SIMachineFunctionInfo.h"
#include "SIRegisterInfo.h"
#include "TargetInfo/AMDGPUTargetInfo.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/BinaryFormat/ELF.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/IR/DiagnosticInfo.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Support/AMDGPUMetadata.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/TargetParser.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
Functions
static uint32_t getFPMode (AMDGPU::SIModeRegisterDefaults Mode)
static AsmPrinter * createAMDGPUAsmPrinterPass (TargetMachine &tm, std::unique_ptr< MCStreamer > &&Streamer)
void LLVM_EXTERNAL_VISIBILITY LLVMInitializeAMDGPUAsmPrinter ()
static bool hasAnyNonFlatUseOfReg (const MachineRegisterInfo &MRI, const SIInstrInfo &TII, unsigned Reg)
static const Function * getCalleeFunction (const MachineOperand &Op)
static unsigned getRsrcReg (CallingConv::ID CallConv)
static amd_element_byte_size_t getElementByteSizeValue (unsigned Size)
Variables
static cl::opt< uint32_t > AssumedStackSizeForExternalCall ("amdgpu-assume-external-call-stack-size", cl::desc("Assumed stack use of any external call (in bytes)"), cl::Hidden, cl::init(16384))
static cl::opt< uint32_t > AssumedStackSizeForDynamicSizeObjects ("amdgpu-assume-dynamic-stack-object-size", cl::desc("Assumed extra stack use if there are any " "variable sized objects (in bytes)"), cl::Hidden, cl::init(4096))
Detailed Description
The AMDGPUAsmPrinter is used to print both assembly string and also binary code.
When passed an MCAsmStreamer it prints assembly and when passed an MCObjectStreamer it outputs binary code.
Definition in file AMDGPUAsmPrinter.cpp.
Function Documentation
createAMDGPUAsmPrinterPass()
static AsmPrinter * createAMDGPUAsmPrinterPass (TargetMachine & tm, std::unique_ptr< MCStreamer > && Streamer) static
Definition at line 96 of file AMDGPUAsmPrinter.cpp.
Referenced by LLVMInitializeAMDGPUAsmPrinter().
getCalleeFunction()
static const Function * getCalleeFunction (const MachineOperand & Op) static
Definition at line 618 of file AMDGPUAsmPrinter.cpp.
References assert().
getElementByteSizeValue()
static amd_element_byte_size_t getElementByteSizeValue (unsigned Size) static
Definition at line 1264 of file AMDGPUAsmPrinter.cpp.
References AMD_ELEMENT_16_BYTES, AMD_ELEMENT_4_BYTES, AMD_ELEMENT_8_BYTES, llvm_unreachable, and Size.
getFPMode()
static uint32_t getFPMode (AMDGPU::SIModeRegisterDefaults Mode) static
Definition at line 88 of file AMDGPUAsmPrinter.cpp.
References FP_DENORM_MODE_DP, FP_DENORM_MODE_SP, FP_ROUND_MODE_DP, FP_ROUND_MODE_SP, and FP_ROUND_ROUND_TO_NEAREST.
getRsrcReg()
static unsigned getRsrcReg (CallingConv::ID CallConv) static
Definition at line 1171 of file AMDGPUAsmPrinter.cpp.
References llvm::CallingConv::AMDGPU_CS, llvm::CallingConv::AMDGPU_ES, llvm::CallingConv::AMDGPU_GS, llvm::CallingConv::AMDGPU_HS, llvm::CallingConv::AMDGPU_LS, llvm::CallingConv::AMDGPU_PS, llvm::CallingConv::AMDGPU_VS, LLVM_FALLTHROUGH, R_00B028_SPI_SHADER_PGM_RSRC1_PS, R_00B128_SPI_SHADER_PGM_RSRC1_VS, R_00B228_SPI_SHADER_PGM_RSRC1_GS, R_00B328_SPI_SHADER_PGM_RSRC1_ES, R_00B428_SPI_SHADER_PGM_RSRC1_HS, R_00B528_SPI_SHADER_PGM_RSRC1_LS, and R_00B848_COMPUTE_PGM_RSRC1.
hasAnyNonFlatUseOfReg()
static bool hasAnyNonFlatUseOfReg (const MachineRegisterInfo & MRI, const SIInstrInfo & TII, unsigned Reg) static
Definition at line 596 of file AMDGPUAsmPrinter.cpp.
References MRI, and TII.
LLVMInitializeAMDGPUAsmPrinter()
void LLVM_EXTERNAL_VISIBILITY LLVMInitializeAMDGPUAsmPrinter ()
Definition at line 101 of file AMDGPUAsmPrinter.cpp.
References createAMDGPUAsmPrinterPass(), llvm::createR600AsmPrinterPass(), llvm::getTheAMDGPUTarget(), llvm::getTheGCNTarget(), and llvm::TargetRegistry::RegisterAsmPrinter().
Variable Documentation
AssumedStackSizeForDynamicSizeObjects
cl::opt< uint32_t > AssumedStackSizeForDynamicSizeObjects("amdgpu-assume-dynamic-stack-object-size", cl::desc("Assumed extra stack use if there are any " "variable sized objects (in bytes)"), cl::Hidden, cl::init(4096)) ("amdgpu-assume-dynamic-stack-object-size" , cl::desc("Assumed extra stack use if there are any " "variable sized objects (in bytes)") , cl::Hidden , cl::init(4096)) static
AssumedStackSizeForExternalCall
cl::opt< uint32_t > AssumedStackSizeForExternalCall("amdgpu-assume-external-call-stack-size", cl::desc("Assumed stack use of any external call (in bytes)"), cl::Hidden, cl::init(16384)) ("amdgpu-assume-external-call-stack-size" , cl::desc("Assumed stack use of any external call (in bytes)") , cl::Hidden , cl::init(16384)) static