LLVM: lib/Target/AMDGPU/AMDGPUPostLegalizerCombiner.cpp File Reference
AMDGPUPostLegalizerCombiner.cpp File Reference
#include "AMDGPUTargetMachine.h"
#include "AMDGPULegalizerInfo.h"
#include "llvm/CodeGen/GlobalISel/Combiner.h"
#include "llvm/CodeGen/GlobalISel/CombinerHelper.h"
#include "llvm/CodeGen/GlobalISel/CombinerInfo.h"
#include "llvm/CodeGen/GlobalISel/GISelKnownBits.h"
#include "llvm/CodeGen/GlobalISel/MIPatternMatch.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/Support/Debug.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "AMDGPUGenPostLegalizeGICombiner.inc"
Classes
struct FMinFMaxLegacyInfo
struct CvtF32UByteMatchInfo
Namespaces
namespace llvm
This class represents lattice values for constants.
Macros
#define DEBUG_TYPE "amdgpu-postlegalizer-combiner"
#define AMDGPUPOSTLEGALIZERCOMBINERHELPER_GENCOMBINERHELPER_DEPS
#define AMDGPUPOSTLEGALIZERCOMBINERHELPER_GENCOMBINERHELPER_H
#define AMDGPUPOSTLEGALIZERCOMBINERHELPER_GENCOMBINERHELPER_CPP
Functions
static bool matchFMinFMaxLegacy (MachineInstr &MI, MachineRegisterInfo &MRI, MachineFunction &MF, FMinFMaxLegacyInfo &Info)
static void applySelectFCmpToFMinToFMaxLegacy (MachineInstr &MI, const FMinFMaxLegacyInfo &Info)
static bool matchUCharToFloat (MachineInstr &MI, MachineRegisterInfo &MRI, MachineFunction &MF, CombinerHelper &Helper)
static void applyUCharToFloat (MachineInstr &MI)
static bool matchCvtF32UByteN (MachineInstr &MI, MachineRegisterInfo &MRI, MachineFunction &MF, CvtF32UByteMatchInfo &MatchInfo)
static void applyCvtF32UByteN (MachineInstr &MI, const CvtF32UByteMatchInfo &MatchInfo)
INITIALIZE_PASS_BEGIN (AMDGPUPostLegalizerCombiner, DEBUG_TYPE, "Combine AMDGPU machine instrs after legalization", false, false) INITIALIZE_PASS_END(AMDGPUPostLegalizerCombiner
FunctionPass * llvm::createAMDGPUPostLegalizeCombiner (bool IsOptNone)
Variables
DEBUG_TYPE
Combine AMDGPU machine instrs after legalization
Combine AMDGPU machine instrs after false
Macro Definition Documentation
AMDGPUPOSTLEGALIZERCOMBINERHELPER_GENCOMBINERHELPER_CPP
#define AMDGPUPOSTLEGALIZERCOMBINERHELPER_GENCOMBINERHELPER_CPP
Definition at line 280 of file AMDGPUPostLegalizerCombiner.cpp.
AMDGPUPOSTLEGALIZERCOMBINERHELPER_GENCOMBINERHELPER_DEPS
#define AMDGPUPOSTLEGALIZERCOMBINERHELPER_GENCOMBINERHELPER_DEPS
Definition at line 228 of file AMDGPUPostLegalizerCombiner.cpp.
AMDGPUPOSTLEGALIZERCOMBINERHELPER_GENCOMBINERHELPER_H
#define AMDGPUPOSTLEGALIZERCOMBINERHELPER_GENCOMBINERHELPER_H
Definition at line 233 of file AMDGPUPostLegalizerCombiner.cpp.
DEBUG_TYPE
#define DEBUG_TYPE "amdgpu-postlegalizer-combiner"
Definition at line 27 of file AMDGPUPostLegalizerCombiner.cpp.
Function Documentation
applyCvtF32UByteN()
static void applyCvtF32UByteN (MachineInstr & MI, const CvtF32UByteMatchInfo & MatchInfo) static
Definition at line 210 of file AMDGPUPostLegalizerCombiner.cpp.
References assert(), B, MI, and llvm::LLT::scalar().
applySelectFCmpToFMinToFMaxLegacy()
static void applySelectFCmpToFMinToFMaxLegacy (MachineInstr & MI, const FMinFMaxLegacyInfo & Info) static
Definition at line 80 of file AMDGPUPostLegalizerCombiner.cpp.
References llvm::MachineIRBuilder::buildInstr(), llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm_unreachable, MI, X, and Y.
applyUCharToFloat()
static void applyUCharToFloat (MachineInstr & MI) static
Definition at line 150 of file AMDGPUPostLegalizerCombiner.cpp.
References B, MI, and llvm::LLT::scalar().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (AMDGPUPostLegalizerCombiner , DEBUG_TYPE , "Combine AMDGPU machine instrs after legalization" , false , false)
matchCvtF32UByteN()
static bool matchCvtF32UByteN (MachineInstr & MI, MachineRegisterInfo & MRI, MachineFunction & MF, CvtF32UByteMatchInfo & MatchInfo) static
Definition at line 181 of file AMDGPUPostLegalizerCombiner.cpp.
References llvm::MIPatternMatch::m_GLShr(), llvm::MIPatternMatch::m_GShl(), llvm::MIPatternMatch::m_GZExt(), llvm::MIPatternMatch::m_ICst(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), and MRI.
matchFMinFMaxLegacy()
static bool matchFMinFMaxLegacy (MachineInstr & MI, MachineRegisterInfo & MRI, MachineFunction & MF, FMinFMaxLegacyInfo & Info) static
Definition at line 41 of file AMDGPUPostLegalizerCombiner.cpp.
References Cond, llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::MachineFunction::getSubtarget(), llvm::AMDGPUSubtarget::hasFminFmaxLegacy(), llvm::MIPatternMatch::m_GFCmp(), llvm::MIPatternMatch::m_Pred(), llvm::MIPatternMatch::m_Reg(), MI, llvm::MIPatternMatch::mi_match(), MRI, and llvm::LLT::scalar().
matchUCharToFloat()
static bool matchUCharToFloat (MachineInstr & MI, MachineRegisterInfo & MRI, MachineFunction & MF, CombinerHelper & Helper) static
Definition at line 130 of file AMDGPUPostLegalizerCombiner.cpp.
References assert(), llvm::APInt::getHighBitsSet(), llvm::CombinerHelper::getKnownBits(), llvm::GISelKnownBits::maskedValueIsZero(), MI, MRI, and llvm::LLT::scalar().
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 351 of file AMDGPUPostLegalizerCombiner.cpp.
false
Combine AMDGPU machine instrs after false
Definition at line 352 of file AMDGPUPostLegalizerCombiner.cpp.
legalization
Combine AMDGPU machine instrs after legalization
Definition at line 352 of file AMDGPUPostLegalizerCombiner.cpp.