LLVM: lib/Target/ARM/ARMBaseRegisterInfo.cpp File Reference
ARMBaseRegisterInfo.cpp File Reference
#include "ARMBaseRegisterInfo.h"
#include "ARM.h"
#include "ARMBaseInstrInfo.h"
#include "ARMFrameLowering.h"
#include "ARMMachineFunctionInfo.h"
#include "ARMSubtarget.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "MCTargetDesc/ARMBaseInfo.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <cassert>
#include <utility>
#include "ARMGenRegisterInfo.inc"
Macros
#define DEBUG_TYPE "arm-register-info"
#define GET_REGINFO_TARGET_DESC
Functions
static unsigned getFramePointerReg (const ARMSubtarget &STI)
static MCPhysReg getPairedGPR (MCPhysReg Reg, bool Odd, const MCRegisterInfo *RI)
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "arm-register-info"
Definition at line 50 of file ARMBaseRegisterInfo.cpp.
GET_REGINFO_TARGET_DESC
#define GET_REGINFO_TARGET_DESC
Definition at line 52 of file ARMBaseRegisterInfo.cpp.
Function Documentation
getFramePointerReg()
static unsigned getFramePointerReg (const ARMSubtarget & STI) static
Definition at line 60 of file ARMBaseRegisterInfo.cpp.
References llvm::ARMSubtarget::useR7AsFramePointer().
Referenced by llvm::ARMBaseRegisterInfo::canRealignStack(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::ARMBaseRegisterInfo::getReservedRegs(), and llvm::ARMBaseRegisterInfo::isInlineAsmReadOnlyReg().
getPairedGPR()
static MCPhysReg getPairedGPR (MCPhysReg Reg, bool Odd, const MCRegisterInfo * RI) static
Definition at line 307 of file ARMBaseRegisterInfo.cpp.
References contains(), and llvm::MCRegisterInfo::getSubReg().
Referenced by llvm::ARMBaseRegisterInfo::getRegAllocationHints().