LLVM: lib/Analysis/BasicAliasAnalysis.cpp File Reference
BasicAliasAnalysis.cpp File Reference
#include "llvm/Analysis/BasicAliasAnalysis.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AssumptionCache.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/CaptureTracking.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/Analysis/MemoryLocation.h"
#include "llvm/Analysis/PhiValues.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Dominators.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GetElementPtrTypeIterator.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/User.h"
#include "llvm/IR/Value.h"
#include "llvm/InitializePasses.h"
#include "llvm/Pass.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/KnownBits.h"
#include <cassert>
#include <cstdint>
#include <cstdlib>
#include <utility>
Macros
#define DEBUG_TYPE "basicaa"
Functions
STATISTIC (SearchLimitReached, "Number of times the limit to " "decompose GEPs is reached")
SearchLimitReached / SearchTimes shows how often the limit of to decompose GEPs is reached.
STATISTIC (SearchTimes, "Number of times a GEP is decomposed")
static bool isNonEscapingLocalObject (const Value *V, SmallDenseMap< const Value *, bool, 8 > *IsCapturedCache=nullptr)
Returns true if the pointer is to a function-local object that never escapes from the function.
static bool isEscapeSource (const Value *V)
Returns true if the pointer is one which would have been considered an escape by isNonEscapingLocalObject.
static uint64_t getObjectSize (const Value *V, const DataLayout &DL, const TargetLibraryInfo &TLI, bool NullIsValidLoc, bool RoundToAlign=false)
Returns the size of the object specified by V or UnknownSize if unknown.
static bool isObjectSmallerThan (const Value *V, uint64_t Size, const DataLayout &DL, const TargetLibraryInfo &TLI, bool NullIsValidLoc)
Returns true if we can prove that the object specified by V is smaller than Size.
static uint64_t getMinimalExtentFrom (const Value &V, const LocationSize &LocSize, const DataLayout &DL, bool NullIsValidLoc)
Return the minimal extent from V to the end of the underlying object, assuming the result is used in an aliasing query.
static bool isObjectSize (const Value *V, uint64_t Size, const DataLayout &DL, const TargetLibraryInfo &TLI, bool NullIsValidLoc)
Returns true if we can prove that the object specified by V has size Size.
static APInt adjustToPointerSize (const APInt &Offset, unsigned PointerSize)
To ensure a pointer offset fits in an integer of size PointerSize (in bits) when that size is smaller than the maximum pointer size.
static unsigned getMaxPointerSize (const DataLayout &DL)
static bool isWriteOnlyParam (const CallBase *Call, unsigned ArgIdx, const TargetLibraryInfo &TLI)
Returns true if this is a writeonly (i.e Mod only) parameter.
static bool isIntrinsicCall (const CallBase *Call, Intrinsic::ID IID)
static const Function * getParent (const Value *V)
static bool notDifferentParent (const Value *O1, const Value *O2)
static AliasResult aliasSameBasePointerGEPs (const GEPOperator *GEP1, LocationSize MaybeV1Size, const GEPOperator *GEP2, LocationSize MaybeV2Size, const DataLayout &DL)
Provide ad-hoc rules to disambiguate accesses through two GEP operators, both having the exact same pointer operand.
static AliasResult MergeAliasResults (AliasResult A, AliasResult B)
INITIALIZE_PASS_BEGIN (BasicAAWrapperPass, "basic-aa", "Basic Alias Analysis (stateless AA impl)", true, true) INITIALIZE_PASS_END(BasicAAWrapperPass
basic Basic Alias Analysis (stateless AA impl)"
Variables
static cl::opt< bool > EnableRecPhiAnalysis ("basic-aa-recphi", cl::Hidden, cl::init(false))
Enable analysis of recursive PHI nodes.
static cl::opt< bool > ForceAtLeast64Bits ("basic-aa-force-at-least-64b", cl::Hidden, cl::init(true))
By default, even on 32-bit architectures we use 64-bit integers for calculations.
static cl::opt< bool > DoubleCalcBits ("basic-aa-double-calc-bits", cl::Hidden, cl::init(false))
const unsigned MaxNumPhiBBsValueReachabilityCheck = 20
Cutoff after which to stop analysing a set of phi nodes potentially involved in a cycle.
static const unsigned MaxLookupSearchDepth = 6
basic aa
basic Basic Alias true
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "basicaa"
Definition at line 63 of file BasicAliasAnalysis.cpp.
Function Documentation
adjustToPointerSize()
static APInt adjustToPointerSize (const APInt & Offset, unsigned PointerSize) static
To ensure a pointer offset fits in an integer of size PointerSize (in bits) when that size is smaller than the maximum pointer size.
This is an issue, for example, in particular for 32b pointers with negative indices that rely on two's complement wrap-arounds for precise alias information where the maximum pointer size is 64b.
Definition at line 436 of file BasicAliasAnalysis.cpp.
References assert().
aliasSameBasePointerGEPs()
static AliasResult aliasSameBasePointerGEPs (const GEPOperator * GEP1, LocationSize MaybeV1Size, const GEPOperator * GEP2, LocationSize MaybeV2Size, const DataLayout & DL) static
Provide ad-hoc rules to disambiguate accesses through two GEP operators, both having the exact same pointer operand.
Definition at line 1086 of file BasicAliasAnalysis.cpp.
References assert(), llvm::BitWidth, llvm::computeKnownBits(), DL, llvm::StructLayout::getElementOffset(), llvm::GetElementPtrInst::getIndexedType(), llvm::StructLayout::getSizeInBytes(), llvm::GetElementPtrInst::getTypeAtIndex(), llvm::isKnownNonEqual(), llvm::MayAlias, llvm::NoAlias, and llvm::LocationSize::unknown().
Analysis()
basic Basic Alias Analysis (stateless AA impl)
getMaxPointerSize()
static unsigned getMaxPointerSize (const DataLayout & DL) static
Definition at line 442 of file BasicAliasAnalysis.cpp.
References DL, DoubleCalcBits, and ForceAtLeast64Bits.
getMinimalExtentFrom()
static uint64_t getMinimalExtentFrom (const Value & V, const LocationSize & LocSize, const DataLayout & DL, bool NullIsValidLoc) static
Return the minimal extent from V to the end of the underlying object, assuming the result is used in an aliasing query.
E.g., we do use the query location size and the fact that null pointers cannot alias here.
Definition at line 240 of file BasicAliasAnalysis.cpp.
References DL.
getObjectSize()
static uint64_t getObjectSize (const Value * V, const DataLayout & DL, const TargetLibraryInfo & TLI, bool NullIsValidLoc, bool RoundToAlign = false) static
Returns the size of the object specified by V or UnknownSize if unknown.
Definition at line 181 of file BasicAliasAnalysis.cpp.
References DL, llvm::getObjectSize(), llvm::ObjectSizeOpts::NullIsUnknownSize, llvm::ObjectSizeOpts::RoundToAlign, Size, and llvm::MemoryLocation::UnknownSize.
getParent()
static const Function * getParent (const Value * V) static
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-11/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 820 of file BasicAliasAnalysis.cpp.
Referenced by llvm::orc::IRSymbolMapper::add(), llvm::CloneAndPruneIntoFromInst(), llvm::JumpThreadingPass::ComputeValueKnownInPredecessorsImpl(), llvm::RegionBase< RegionTraits< MachineFunction > >::contains(), ensureValueAvailableInSuccessor(), llvm::CodeExtractor::findAllocas(), llvm::LiveVariables::VarInfo::findKill(), llvm::getLiveRegMap(), getLocalFunctionMetadata(), llvm::FastISel::hasTrivialKill(), llvm::ilist_node_with_parent< NodeTy, ParentTy, Options >::ilist_node_with_parent(), llvm::CodeExtractor::isLegalToShrinkwrapLifetimeMarkers(), LLVMGetBasicBlockParent(), LLVMGetGlobalParent(), LLVMGetInstructionParent(), LLVMGetParamParent(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::PHITransAddr::NeedsPHITranslationFromBlock(), notDifferentParent(), llvm::Function::print(), llvm::MachineFunction::print(), llvm::NamedMDNode::print(), llvm::NamedMDNode::print(), processSwitch(), redirectValuesFromPredecessorsToPhi(), llvm::AssumptionCache::registerAssumption(), llvm::ScheduleDAGMI::schedule(), llvm::ScheduleDAGMILive::schedule(), llvm::SIScheduleDAGMI::schedule(), llvm::VLIWMachineScheduler::schedule(), and llvm::slpvectorizer::BoUpSLP::vectorizeTree().
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (BasicAAWrapperPass , "basic-aa" , "Basic Alias Analysis (stateless AA impl)" , true , true)
isEscapeSource()
static bool isEscapeSource (const Value * V) static
Returns true if the pointer is one which would have been considered an escape by isNonEscapingLocalObject.
Definition at line 164 of file BasicAliasAnalysis.cpp.
isIntrinsicCall()
static bool isIntrinsicCall (const CallBase * Call, Intrinsic::ID IID) static
Definition at line 814 of file BasicAliasAnalysis.cpp.
References llvm::IntrinsicInst::getIntrinsicID().
Referenced by llvm::BasicAAResult::getModRefInfo(), and llvm::BasicAAResult::getModRefInfo().
isNonEscapingLocalObject()
static bool isNonEscapingLocalObject (const Value * V, SmallDenseMap< const Value *, bool, 8 > * IsCapturedCache = nullptr) static
Returns true if the pointer is to a function-local object that never escapes from the function.
Definition at line 120 of file BasicAliasAnalysis.cpp.
References A, llvm::isNoAliasCall(), and llvm::PointerMayBeCaptured().
Referenced by llvm::BasicAAResult::getModRefInfo().
isObjectSize()
static bool isObjectSize (const Value * V, uint64_t Size, const DataLayout & DL, const TargetLibraryInfo & TLI, bool NullIsValidLoc) static
Returns true if we can prove that the object specified by V has size Size.
Definition at line 258 of file BasicAliasAnalysis.cpp.
References DL, llvm::getObjectSize(), Size, and llvm::MemoryLocation::UnknownSize.
isObjectSmallerThan()
static bool isObjectSmallerThan (const Value * V, uint64_t Size, const DataLayout & DL, const TargetLibraryInfo & TLI, bool NullIsValidLoc) static
Returns true if we can prove that the object specified by V is smaller than Size.
Definition at line 196 of file BasicAliasAnalysis.cpp.
References DL, llvm::getObjectSize(), llvm::isIdentifiedObject(), Size, and llvm::MemoryLocation::UnknownSize.
isWriteOnlyParam()
static bool isWriteOnlyParam (const CallBase * Call, unsigned ArgIdx, const TargetLibraryInfo & TLI) static
Returns true if this is a writeonly (i.e Mod only) parameter.
Definition at line 774 of file BasicAliasAnalysis.cpp.
References F, llvm::TargetLibraryInfo::getLibFunc(), and llvm::TargetLibraryInfo::has().
Referenced by llvm::BasicAAResult::getArgModRefInfo().
MergeAliasResults()
static AliasResult MergeAliasResults (AliasResult A, AliasResult B) static
Definition at line 1546 of file BasicAliasAnalysis.cpp.
References A, B, llvm::MayAlias, llvm::MustAlias, and llvm::PartialAlias.
notDifferentParent()
static bool notDifferentParent (const Value * O1, const Value * O2) static
Definition at line 833 of file BasicAliasAnalysis.cpp.
References getParent().
Referenced by llvm::BasicAAResult::alias(), and llvm::BasicAAResult::getModRefInfo().
STATISTIC() [1/2]
STATISTIC (SearchLimitReached , "Number of times the limit to " "decompose GEPs is reached")
SearchLimitReached / SearchTimes shows how often the limit of to decompose GEPs is reached.
It will affect the precision of basic alias analysis.
STATISTIC() [2/2]
STATISTIC (SearchTimes , "Number of times a GEP is decomposed")
Variable Documentation
aa
basic aa
Definition at line 2085 of file BasicAliasAnalysis.cpp.
DoubleCalcBits
cl::opt< bool > DoubleCalcBits("basic-aa-double-calc-bits", cl::Hidden, cl::init(false)) ("basic-aa-double-calc-bits" , cl::Hidden , cl::init(false)) static
Referenced by getMaxPointerSize().
EnableRecPhiAnalysis
cl::opt< bool > EnableRecPhiAnalysis("basic-aa-recphi", cl::Hidden, cl::init(false)) ("basic-aa-recphi" , cl::Hidden , cl::init(false)) static
Enable analysis of recursive PHI nodes.
ForceAtLeast64Bits
cl::opt< bool > ForceAtLeast64Bits("basic-aa-force-at-least-64b", cl::Hidden, cl::init(true)) ("basic-aa-force-at-least-64b" , cl::Hidden , cl::init(true)) static
By default, even on 32-bit architectures we use 64-bit integers for calculations.
This will allow us to more-aggressively decompose indexing expressions calculated using i64 values (e.g., long long in C) which is common enough to worry about.
Referenced by getMaxPointerSize().
MaxLookupSearchDepth
const unsigned MaxLookupSearchDepth = 6 static
Definition at line 96 of file BasicAliasAnalysis.cpp.
MaxNumPhiBBsValueReachabilityCheck
const unsigned MaxNumPhiBBsValueReachabilityCheck = 20
Cutoff after which to stop analysing a set of phi nodes potentially involved in a cycle.
Because we are analysing 'through' phi nodes, we need to be careful with value equivalence. We use reachability to make sure a value cannot be involved in a cycle.
Definition at line 91 of file BasicAliasAnalysis.cpp.
true
dot regions Print regions of function to dot true view regions View regions of true
Examples
/Users/rift/code/other/llvm-doxygen/llvm-project-11/llvm/include/llvm/ADT/ilist_node.h.
Definition at line 2086 of file BasicAliasAnalysis.cpp.
Referenced by llvm::DWARFUnitHeader::extract(), llvm::PPCInstrInfo::getFMAPatterns(), hasBZHI(), llvm::X86CallLowering::lowerCall(), matchIntrinsicType(), and llvm::ScopedHandle< HandleTraits >::operator bool().