LLVM: llvm::LoopPass Class Reference
llvm::LoopPass Class Reference abstract
#include "llvm/Analysis/LoopPass.h"
Public Member Functions
LoopPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const override
getPrinterPass - Get a pass to print the function corresponding to a Loop.
virtual bool runOnLoop (Loop *L, LPPassManager &LPM)=0
virtual bool doInitialization (Loop *L, LPPassManager &LPM)
virtual bool doFinalization ()
void preparePassManager (PMStack &PMS) override
Check if available pass managers are suitable for this pass or not.
void assignPassManager (PMStack &PMS, PassManagerType PMT) override
Assign pass manager to manage this pass.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Protected Member Functions
bool skipLoop (const Loop *L) const
Optional passes call this function to check whether the pass should be skipped.
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Definition at line 27 of file LoopPass.h.
Constructor & Destructor Documentation
LoopPass()
llvm::LoopPass::LoopPass (char & pid) inline explicit
Definition at line 29 of file LoopPass.h.
Member Function Documentation
assignPassManager()
void LoopPass::assignPassManager (PMStack & PMS, PassManagerType PMT) override virtual
Assign pass manager to manage this pass.
Reimplemented from llvm::Pass.
Definition at line 320 of file LoopPass.cpp.
References llvm::PMTopLevelManager::addIndirectPassManager(), assert(), P, llvm::PMT_LoopPassManager, and llvm::PMTopLevelManager::schedulePass().
createPrinterPass()
Pass * LoopPass::createPrinterPass (raw_ostream & O, const std::string & Banner) const override virtual
getPrinterPass - Get a pass to print the function corresponding to a Loop.
Implements llvm::Pass.
Definition at line 293 of file LoopPass.cpp.
doFinalization()
virtual bool llvm::LoopPass::doFinalization () inline virtual
Definition at line 50 of file LoopPass.h.
doInitialization()
virtual bool llvm::LoopPass::doInitialization (Loop * L, LPPassManager & LPM) inline virtual
Definition at line 44 of file LoopPass.h.
getPotentialPassManagerType()
PassManagerType llvm::LoopPass::getPotentialPassManagerType () const inline override virtual
Return what kind of Pass Manager can manage this pass.
Reimplemented from llvm::Pass.
Definition at line 64 of file LoopPass.h.
References llvm::PMT_LoopPassManager.
preparePassManager()
void LoopPass::preparePassManager (PMStack &) override virtual
Check if available pass managers are suitable for this pass or not.
Reimplemented from llvm::Pass.
Definition at line 304 of file LoopPass.cpp.
References llvm::PMT_LoopPassManager.
runOnLoop()
virtual bool llvm::LoopPass::runOnLoop (Loop * L, LPPassManager & LPM) pure virtual
Implemented in llvm::IVUsersWrapperPass.
skipLoop()
bool LoopPass::skipLoop (const Loop * L) const protected
Optional passes call this function to check whether the pass should be skipped.
This is the case when Attribute::OptimizeNone is set or when optimization bisect is over the limit.
Definition at line 359 of file LoopPass.cpp.
References llvm::dbgs(), F, getDescription(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BasicBlock::getParent(), llvm::Pass::getPassName(), and LLVM_DEBUG.
The documentation for this class was generated from the following files:
include/llvm/Analysis/LoopPass.h
lib/Analysis/LoopPass.cpp