LLVM: llvm::VPInstruction Class Reference
llvm::VPInstruction Class Reference
This is a concrete Recipe that models a single VPlan-level instruction.
#include "Transforms/Vectorize/VPlan.h"
Public Types
enum {
Not = Instruction::OtherOpsEnd + 1 , ICmpULE , SLPLoad , SLPStore ,
ActiveLaneMask
}
VPlan opcodes, extending LLVM IR with idiomatics instructions.
Public Types inherited from llvm::VPUser
typedef SmallVectorImpl< VPValue * >::iterator operand_iterator
typedef SmallVectorImpl< VPValue * >::const_iterator const_operand_iterator
typedef iterator_range< operand_iterator > operand_range
typedef iterator_range< const_operand_iterator > const_operand_range
Public Types inherited from llvm::VPValue
enum { VPValueSC , VPUserSC , VPInstructionSC }
An enumeration for keeping track of the concrete subclass of VPValue that are actually instantiated.
typedef SmallVectorImpl< VPUser * >::iterator user_iterator
typedef SmallVectorImpl< VPUser * >::const_iterator const_user_iterator
typedef iterator_range< user_iterator > user_range
typedef iterator_range< const_user_iterator > const_user_range
Public Types inherited from llvm::VPRecipeBase
using VPRecipeTy
An enumeration for keeping track of the concrete subclass of VPRecipeBase that is actually instantiated.
Public Member Functions
VPInstruction (unsigned Opcode, ArrayRef< VPValue * > Operands)
VPInstruction (unsigned Opcode, std::initializer_list< VPValue * > Operands)
VPInstruction * clone () const
unsigned getOpcode () const
void execute (VPTransformState &State) override
Generate the instruction.
void print (raw_ostream &O, const Twine &Indent, VPSlotTracker &SlotTracker) const override
Print the Recipe.
void print (raw_ostream &O) const
Print the VPInstruction.
void print (raw_ostream &O, VPSlotTracker &SlotTracker) const
bool mayWriteToMemory () const
Return true if this instruction may modify memory.
bool hasResult () const
Public Member Functions inherited from llvm::VPUser
VPUser ()
VPUser (ArrayRef< VPValue * > Operands)
VPUser (std::initializer_list< VPValue * > Operands)
template<typename IterT >
VPUser (iterator_range< IterT > Operands)
VPUser (const VPUser &)=delete
VPUser & operator= (const VPUser &)=delete
void addOperand (VPValue *Operand)
unsigned getNumOperands () const
VPValue * getOperand (unsigned N) const
void setOperand (unsigned I, VPValue *New)
operand_iterator op_begin ()
const_operand_iterator op_begin () const
operand_iterator op_end ()
const_operand_iterator op_end () const
operand_range operands ()
const_operand_range operands () const
Public Member Functions inherited from llvm::VPValue
VPValue (Value *UV=nullptr)
VPValue (const VPValue &)=delete
VPValue & operator= (const VPValue &)=delete
unsigned getVPValueID () const
void printAsOperand (raw_ostream &OS, VPSlotTracker &Tracker) const
void print (raw_ostream &OS, VPSlotTracker &Tracker) const
unsigned getNumUsers () const
void addUser (VPUser &User)
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
user_range users ()
const_user_range users () const
bool hasMoreThanOneUniqueUser ()
Returns true if the value has more than one unique user.
void replaceAllUsesWith (VPValue *New)
Public Member Functions inherited from llvm::VPRecipeBase
VPRecipeBase (const unsigned char SC)
virtual ~VPRecipeBase ()=default
unsigned getVPRecipeID () const
VPBasicBlock * getParent ()
const VPBasicBlock * getParent () const
void insertBefore (VPRecipeBase *InsertPos)
Insert an unlinked recipe into a basic block immediately before the specified recipe.
void insertAfter (VPRecipeBase *InsertPos)
Insert an unlinked Recipe into a basic block immediately after the specified Recipe.
void moveAfter (VPRecipeBase *MovePos)
Unlink this recipe from its current VPBasicBlock and insert it into the VPBasicBlock that MovePos lives in, right after MovePos.
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
iplist< VPRecipeBase >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
Public Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
VPRecipeBase * getPrevNode ()
const VPRecipeBase * getPrevNode () const
Get the previous node, or nullptr for the list head.
VPRecipeBase * getNextNode ()
Get the next node, or nullptr for the list tail.
const VPRecipeBase * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
static bool classof (const VPValue *V)
Method to support type inquiry through isa, cast, and dyn_cast.
static bool classof (const VPRecipeBase *R)
Method to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::VPUser
static bool classof (const VPValue *V)
Method to support type inquiry through isa, cast, and dyn_cast.
Protected Member Functions
Instruction * getUnderlyingInstr ()
void setUnderlyingInstr (Instruction *I)
Protected Member Functions inherited from llvm::VPUser
VPUser (const unsigned char SC)
VPUser (const unsigned char SC, ArrayRef< VPValue * > Operands)
Protected Member Functions inherited from llvm::VPValue
VPValue (const unsigned char SC, Value *UV=nullptr)
Value * getUnderlyingValue ()
Return the underlying Value attached to this VPValue.
const Value * getUnderlyingValue () const
void setUnderlyingValue (Value *Val)
Protected Member Functions inherited from llvm::ilist_node_with_parent< VPRecipeBase, VPBasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Friends
class VPlanSlp
Additional Inherited Members
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Attributes inherited from llvm::VPValue
Value * UnderlyingVal
Detailed Description
This is a concrete Recipe that models a single VPlan-level instruction.
While as any Recipe it may generate a sequence of IR instructions when executed, these instructions would always form a single-def expression as the VPInstruction is also a single def-use vertex.
Definition at line 678 of file VPlan.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
VPlan opcodes, extending LLVM IR with idiomatics instructions.
Enumerator
Not
ICmpULE
SLPLoad
SLPStore
ActiveLaneMask
Definition at line 683 of file VPlan.h.
Constructor & Destructor Documentation
VPInstruction() [1/2]
llvm::VPInstruction::VPInstruction (unsigned Opcode, ArrayRef< VPValue * > Operands) inline
Definition at line 707 of file VPlan.h.
Referenced by clone().
VPInstruction() [2/2]
llvm::VPInstruction::VPInstruction (unsigned Opcode, std::initializer_list< VPValue * > Operands) inline
Definition at line 711 of file VPlan.h.
Member Function Documentation
classof() [1/2]
static bool llvm::VPInstruction::classof (const VPRecipeBase * R) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 725 of file VPlan.h.
classof() [2/2]
static bool llvm::VPInstruction::classof (const VPValue * V) inline static
Method to support type inquiry through isa, cast, and dyn_cast.
Definition at line 715 of file VPlan.h.
References llvm::VPValue::VPInstructionSC.
clone()
VPInstruction * llvm::VPInstruction::clone () const inline
Definition at line 719 of file VPlan.h.
References Operands, llvm::VPUser::operands(), and VPInstruction().
execute()
void VPInstruction::execute (VPTransformState & State) override virtual
Generate the instruction.
TODO: We currently execute only per-part unless a specific instance is provided.
Implements llvm::VPRecipeBase.
Definition at line 402 of file VPlan.cpp.
References assert().
getOpcode()
unsigned llvm::VPInstruction::getOpcode () const inline
Definition at line 729 of file VPlan.h.
Referenced by hasResult(), and print().
getUnderlyingInstr()
Instruction * llvm::VPInstruction::getUnderlyingInstr () inline protected
Definition at line 700 of file VPlan.h.
References llvm::VPValue::getUnderlyingValue(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
hasResult()
bool llvm::VPInstruction::hasResult () const inline
Definition at line 752 of file VPlan.h.
References getOpcode(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by print().
mayWriteToMemory()
bool llvm::VPInstruction::mayWriteToMemory () const inline
Return true if this instruction may modify memory.
Definition at line 745 of file VPlan.h.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and SLPStore.
print() [1/3]
void VPInstruction::print (raw_ostream & O) const
Print the VPInstruction.
Definition at line 414 of file VPlan.cpp.
References llvm::VPRecipeBase::getParent(), and print().
print() [2/3]
void VPInstruction::print (raw_ostream & O, const Twine & Indent, VPSlotTracker & SlotTracker) const override virtual
Print the Recipe.
Implements llvm::VPRecipeBase.
Definition at line 408 of file VPlan.cpp.
References print().
Referenced by print(), and print().
print() [3/3]
void VPInstruction::print (raw_ostream & O, VPSlotTracker & SlotTracker) const
Definition at line 419 of file VPlan.cpp.
References ActiveLaneMask, getOpcode(), llvm::Instruction::getOpcodeName(), hasResult(), ICmpULE, Not, llvm::VPUser::operands(), llvm::VPValue::printAsOperand(), SLPLoad, and SLPStore.
setUnderlyingInstr()
void llvm::VPInstruction::setUnderlyingInstr (Instruction * I) inline protected
Definition at line 704 of file VPlan.h.
References I, and llvm::VPValue::setUnderlyingValue().
Friends And Related Symbol Documentation
VPlanSlp
friend class VPlanSlp friend
Definition at line 679 of file VPlan.h.
The documentation for this class was generated from the following files:
lib/Transforms/Vectorize/VPlan.h
lib/Transforms/Vectorize/VPlan.cpp