LLVM: llvm::LoopVectorizeHints Class Reference
llvm::LoopVectorizeHints Class Reference
Utility class for getting and setting loop vectorizer hints in the form of loop metadata.
#include "llvm/Transforms/Vectorize/LoopVectorizationLegality.h"
Public Types
enum ForceKind { FK_Undefined = -1 , FK_Disabled = 0 , FK_Enabled = 1 }
Public Member Functions
LoopVectorizeHints (const Loop *L, bool InterleaveOnlyWhenForced, OptimizationRemarkEmitter &ORE)
void setAlreadyVectorized ()
Mark the loop L as already vectorized by setting the width to 1.
bool allowVectorization (Function *F, Loop *L, bool VectorizeOnlyWhenForced) const
void emitRemarkWithHints () const
Dumps all the hint information.
unsigned getWidth () const
unsigned getInterleave () const
unsigned getIsVectorized () const
unsigned getPredicate () const
enum ForceKind getForce () const
const char * vectorizeAnalysisPassName () const
If hints are provided that force vectorization, use the AlwaysPrint pass name to force the frontend to print the diagnostic.
bool allowReordering () const
bool isPotentiallyUnsafe () const
void setPotentiallyUnsafe ()
Detailed Description
Utility class for getting and setting loop vectorizer hints in the form of loop metadata.
This class keeps a number of loop annotations locally (as member variables) and can, upon request, write them back as metadata on the loop. It will initially scan the loop for existing metadata, and will update the local values based on information in the loop. We cannot write all values to metadata, as the mere presence of some info, for example 'force', means a decision has been made. So, we need to be careful NOT to add them if the user hasn't specifically asked so.
Definition at line 45 of file LoopVectorizationLegality.h.
Member Enumeration Documentation
ForceKind
enum llvm::LoopVectorizeHints::ForceKind
Enumerator
FK_Undefined
Not selected.
FK_Disabled
Forcing disabled.
FK_Enabled
Forcing enabled.
Definition at line 83 of file LoopVectorizationLegality.h.
Constructor & Destructor Documentation
LoopVectorizeHints()
llvm::LoopVectorizeHints::LoopVectorizeHints (const Loop * L, bool InterleaveOnlyWhenForced, OptimizationRemarkEmitter & ORE)
Definition at line 71 of file LoopVectorizationLegality.cpp.
References llvm::dbgs(), llvm::VectorizerParams::isInterleaveForced(), LLVM_DEBUG, and llvm::VectorizerParams::VectorizationInterleave.
Member Function Documentation
allowReordering()
bool llvm::LoopVectorizeHints::allowReordering () const inline
Definition at line 116 of file LoopVectorizationLegality.h.
References FK_Enabled, getForce(), and getWidth().
Referenced by llvm::LoopVectorizationRequirements::doesNotMeet().
allowVectorization()
bool llvm::LoopVectorizeHints::allowVectorization (Function * F, Loop * L, bool VectorizeOnlyWhenForced) const
Definition at line 115 of file LoopVectorizationLegality.cpp.
References llvm::dbgs(), llvm::OptimizationRemarkEmitter::emit(), emitRemarkWithHints(), FK_Disabled, FK_Enabled, getForce(), llvm::LoopBase< BlockT, LoopT >::getHeader(), getIsVectorized(), llvm::Loop::getStartLoc(), LLVM_DEBUG, and vectorizeAnalysisPassName().
Referenced by isExplicitVecOuterLoop(), and llvm::LoopVectorizePass::processLoop().
emitRemarkWithHints()
void llvm::LoopVectorizeHints::emitRemarkWithHints () const
Dumps all the hint information.
Definition at line 148 of file LoopVectorizationLegality.cpp.
References llvm::OptimizationRemarkEmitter::emit(), FK_Disabled, FK_Enabled, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Loop::getStartLoc(), and LV_NAME.
Referenced by allowVectorization(), isExplicitVecOuterLoop(), and llvm::LoopVectorizePass::processLoop().
getForce()
enum ForceKind llvm::LoopVectorizeHints::getForce () const inline
Definition at line 105 of file LoopVectorizationLegality.h.
References FK_Disabled, FK_Undefined, and llvm::hasDisableAllTransformsHint().
Referenced by allowReordering(), allowVectorization(), isExplicitVecOuterLoop(), isPotentiallyUnsafe(), llvm::LoopVectorizePass::processLoop(), llvm::LoopVectorizationCostModel::selectVectorizationFactor(), and vectorizeAnalysisPassName().
getInterleave()
unsigned llvm::LoopVectorizeHints::getInterleave () const inline
Definition at line 102 of file LoopVectorizationLegality.h.
Referenced by isExplicitVecOuterLoop(), and llvm::LoopVectorizePass::processLoop().
getIsVectorized()
unsigned llvm::LoopVectorizeHints::getIsVectorized () const inline
Definition at line 103 of file LoopVectorizationLegality.h.
Referenced by allowVectorization().
getPredicate()
unsigned llvm::LoopVectorizeHints::getPredicate () const inline
Definition at line 104 of file LoopVectorizationLegality.h.
Referenced by getScalarEpilogueLowering().
getWidth()
unsigned llvm::LoopVectorizeHints::getWidth () const inline
Definition at line 101 of file LoopVectorizationLegality.h.
Referenced by allowReordering(), llvm::LoopVectorizePass::processLoop(), processLoopInVPlanNativePath(), and vectorizeAnalysisPassName().
isPotentiallyUnsafe()
bool llvm::LoopVectorizeHints::isPotentiallyUnsafe () const inline
Definition at line 125 of file LoopVectorizationLegality.h.
References FK_Enabled, and getForce().
Referenced by llvm::LoopVectorizePass::processLoop().
setAlreadyVectorized()
void llvm::LoopVectorizeHints::setAlreadyVectorized ()
Mark the loop L as already vectorized by setting the width to 1.
Definition at line 96 of file LoopVectorizationLegality.cpp.
References llvm::ConstantAsMetadata::get(), llvm::MDNode::get(), llvm::MDString::get(), llvm::ConstantInt::get(), llvm::BasicBlock::getContext(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Loop::getLoopID(), llvm::makePostTransformationMetadata(), llvm::Loop::setLoopID(), and llvm::Twine::str().
Referenced by llvm::InnerLoopVectorizer::createVectorizedLoopSkeleton(), llvm::LoopVectorizePass::processLoop(), and processLoopInVPlanNativePath().
setPotentiallyUnsafe()
void llvm::LoopVectorizeHints::setPotentiallyUnsafe () inline
Definition at line 134 of file LoopVectorizationLegality.h.
vectorizeAnalysisPassName()
const char * llvm::LoopVectorizeHints::vectorizeAnalysisPassName () const
If hints are provided that force vectorization, use the AlwaysPrint pass name to force the frontend to print the diagnostic.
Definition at line 174 of file LoopVectorizationLegality.cpp.
References llvm::OptimizationRemarkAnalysis::AlwaysPrint, FK_Disabled, FK_Undefined, getForce(), getWidth(), and LV_NAME.
Referenced by allowVectorization(), llvm::LoopVectorizationRequirements::doesNotMeet(), llvm::LoopVectorizePass::processLoop(), and llvm::reportVectorizationFailure().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/LoopVectorizationLegality.h
lib/Transforms/Vectorize/LoopVectorizationLegality.cpp