LLVM: llvm::OrcCBindingsStack Class Reference
llvm::OrcCBindingsStack Class Reference
#include "ExecutionEngine/Orc/OrcCBindingsStack.h"
Public Types
using CompileCallbackMgr = orc::JITCompileCallbackManager
using ObjLayerT = orc::LegacyRTDyldObjectLinkingLayer
using CompileLayerT = orc::LegacyIRCompileLayer<ObjLayerT, orc::SimpleCompiler>
using CODLayerT
using CallbackManagerBuilder
using IndirectStubsManagerBuilder = CODLayerT::IndirectStubsManagerBuilderT
Public Member Functions
OrcCBindingsStack (TargetMachine &TM, IndirectStubsManagerBuilder IndirectStubsMgrBuilder)
Error shutdown ()
std::string mangle (StringRef Name)
Expected< JITTargetAddress > createLazyCompileCallback (LLVMOrcLazyCompileCallbackFn Callback, void *CallbackCtx)
Error createIndirectStub (StringRef StubName, JITTargetAddress Addr)
Error setIndirectStubPointer (StringRef Name, JITTargetAddress Addr)
template<typename LayerT >
Expected< orc::VModuleKey > addIRModule (LayerT &Layer, std::unique_ptr< Module > M, std::unique_ptr< RuntimeDyld::MemoryManager > MemMgr, LLVMOrcSymbolResolverFn ExternalResolver, void *ExternalResolverCtx)
Expected< orc::VModuleKey > addIRModuleEager (std::unique_ptr< Module > M, LLVMOrcSymbolResolverFn ExternalResolver, void *ExternalResolverCtx)
Expected< orc::VModuleKey > addIRModuleLazy (std::unique_ptr< Module > M, LLVMOrcSymbolResolverFn ExternalResolver, void *ExternalResolverCtx)
Error removeModule (orc::VModuleKey K)
Expected< orc::VModuleKey > addObject (std::unique_ptr< MemoryBuffer > ObjBuffer, LLVMOrcSymbolResolverFn ExternalResolver, void *ExternalResolverCtx)
JITSymbol findSymbol (const std::string &Name, bool ExportedSymbolsOnly)
JITSymbol findSymbolIn (orc::VModuleKey K, const std::string &Name, bool ExportedSymbolsOnly)
Expected< JITTargetAddress > findSymbolAddress (const std::string &Name, bool ExportedSymbolsOnly)
Expected< JITTargetAddress > findSymbolAddressIn (orc::VModuleKey K, const std::string &Name, bool ExportedSymbolsOnly)
const std::string & getErrorMessage () const
void RegisterJITEventListener (JITEventListener *L)
void UnregisterJITEventListener (JITEventListener *L)
Static Public Member Functions
template<typename PtrTy >
static PtrTy fromTargetAddress (JITTargetAddress Addr)
Detailed Description
Definition at line 105 of file OrcCBindingsStack.h.
Member Typedef Documentation
CallbackManagerBuilder
using llvm::OrcCBindingsStack::CallbackManagerBuilder
Initial value:
      std::function<std::unique_ptr<CompileCallbackMgr>()>
Definition at line 114 of file OrcCBindingsStack.h.
CODLayerT
using llvm::OrcCBindingsStack::CODLayerT
Initial value:
        orc::LegacyCompileOnDemandLayer<CompileLayerT, CompileCallbackMgr>
Definition at line 111 of file OrcCBindingsStack.h.
CompileCallbackMgr
using llvm::OrcCBindingsStack::CompileCallbackMgr = orc::JITCompileCallbackManager
Definition at line 108 of file OrcCBindingsStack.h.
CompileLayerT
using llvm::OrcCBindingsStack::CompileLayerT = orc::LegacyIRCompileLayer<ObjLayerT, orc::SimpleCompiler>
Definition at line 110 of file OrcCBindingsStack.h.
IndirectStubsManagerBuilder
using llvm::OrcCBindingsStack::IndirectStubsManagerBuilder = CODLayerT::IndirectStubsManagerBuilderT
Definition at line 117 of file OrcCBindingsStack.h.
ObjLayerT
using llvm::OrcCBindingsStack::ObjLayerT = orc::LegacyRTDyldObjectLinkingLayer
Definition at line 109 of file OrcCBindingsStack.h.
Constructor & Destructor Documentation
OrcCBindingsStack()
llvm::OrcCBindingsStack::OrcCBindingsStack (TargetMachine & TM, IndirectStubsManagerBuilder IndirectStubsMgrBuilder) inline
Definition at line 210 of file OrcCBindingsStack.h.
References assert().
Member Function Documentation
addIRModule()
template<typename LayerT > Expected< orc::VModuleKey > llvm::OrcCBindingsStack::addIRModule (LayerT & Layer, std::unique_ptr< Module > M, std::unique_ptr< RuntimeDyld::MemoryManager > MemMgr, LLVMOrcSymbolResolverFn ExternalResolver, void * ExternalResolverCtx) inline
Definition at line 286 of file OrcCBindingsStack.h.
References llvm::AcknowledgeORCv1Deprecation, llvm::orc::ExecutionSession::allocateVModule(), llvm::detail::createGenericLayer(), llvm::orc::getConstructors(), llvm::orc::getDestructors(), and mangle().
Referenced by addIRModuleEager(), and addIRModuleLazy().
addIRModuleEager()
Expected< orc::VModuleKey > llvm::OrcCBindingsStack::addIRModuleEager (std::unique_ptr< Module > M, LLVMOrcSymbolResolverFn ExternalResolver, void * ExternalResolverCtx) inline
Definition at line 326 of file OrcCBindingsStack.h.
References addIRModule().
Referenced by LLVMOrcAddEagerlyCompiledIR().
addIRModuleLazy()
Expected< orc::VModuleKey > llvm::OrcCBindingsStack::addIRModuleLazy (std::unique_ptr< Module > M, LLVMOrcSymbolResolverFn ExternalResolver, void * ExternalResolverCtx) inline
Definition at line 335 of file OrcCBindingsStack.h.
References addIRModule(), and llvm::inconvertibleErrorCode().
Referenced by LLVMOrcAddLazilyCompiledIR().
addObject()
Expected< orc::VModuleKey > llvm::OrcCBindingsStack::addObject (std::unique_ptr< MemoryBuffer > ObjBuffer, LLVMOrcSymbolResolverFn ExternalResolver, void * ExternalResolverCtx) inline
Definition at line 357 of file OrcCBindingsStack.h.
References llvm::orc::LegacyRTDyldObjectLinkingLayer::addObject(), llvm::orc::ExecutionSession::allocateVModule(), llvm::detail::createGenericLayer(), and llvm::object::ObjectFile::createObjectFile().
Referenced by LLVMOrcAddObjectFile().
createIndirectStub()
Error llvm::OrcCBindingsStack::createIndirectStub (StringRef StubName, JITTargetAddress Addr) inline
Definition at line 275 of file OrcCBindingsStack.h.
References llvm::JITSymbolFlags::Exported.
Referenced by LLVMOrcCreateIndirectStub().
createLazyCompileCallback()
Expected< JITTargetAddress > llvm::OrcCBindingsStack::createLazyCompileCallback (LLVMOrcLazyCompileCallbackFn Callback, void * CallbackCtx) inline
Definition at line 266 of file OrcCBindingsStack.h.
References llvm::wrap().
Referenced by LLVMOrcCreateLazyCompileCallback().
findSymbol()
JITSymbol llvm::OrcCBindingsStack::findSymbol (const std::string & Name, bool ExportedSymbolsOnly) inline
Definition at line 377 of file OrcCBindingsStack.h.
References llvm::orc::LegacyIRCompileLayer< BaseLayerT, CompileFtor >::findSymbol(), mangle(), and Name.
Referenced by findSymbolAddress().
findSymbolAddress()
Expected< JITTargetAddress > llvm::OrcCBindingsStack::findSymbolAddress (const std::string & Name, bool ExportedSymbolsOnly) inline
Definition at line 392 of file OrcCBindingsStack.h.
References findSymbol(), and Name.
Referenced by LLVMOrcGetSymbolAddress().
findSymbolAddressIn()
Expected< JITTargetAddress > llvm::OrcCBindingsStack::findSymbolAddressIn (orc::VModuleKey K, const std::string & Name, bool ExportedSymbolsOnly) inline
Definition at line 409 of file OrcCBindingsStack.h.
References findSymbolIn(), and Name.
Referenced by LLVMOrcGetSymbolAddressIn().
findSymbolIn()
JITSymbol llvm::OrcCBindingsStack::findSymbolIn (orc::VModuleKey K, const std::string & Name, bool ExportedSymbolsOnly) inline
Definition at line 386 of file OrcCBindingsStack.h.
References assert(), mangle(), and Name.
Referenced by findSymbolAddressIn().
fromTargetAddress()
template<typename PtrTy > static PtrTy llvm::OrcCBindingsStack::fromTargetAddress (JITTargetAddress Addr) inline static
Definition at line 261 of file OrcCBindingsStack.h.
getErrorMessage()
const std::string & llvm::OrcCBindingsStack::getErrorMessage () const inline
Definition at line 427 of file OrcCBindingsStack.h.
Referenced by LLVMOrcGetErrorMsg().
mangle()
std::string llvm::OrcCBindingsStack::mangle (StringRef Name) inline
Definition at line 251 of file OrcCBindingsStack.h.
References llvm::Mangler::getNameWithPrefix(), and Name.
Referenced by addIRModule(), findSymbol(), findSymbolIn(), and LLVMOrcGetMangledSymbol().
RegisterJITEventListener()
void llvm::OrcCBindingsStack::RegisterJITEventListener (JITEventListener * L) inline
Definition at line 429 of file OrcCBindingsStack.h.
removeModule()
Error llvm::OrcCBindingsStack::removeModule (orc::VModuleKey K) inline
Definition at line 348 of file OrcCBindingsStack.h.
References llvm::orc::ExecutionSession::releaseVModule(), removeModule(), and llvm::Error::success().
Referenced by LLVMOrcRemoveModule(), and removeModule().
setIndirectStubPointer()
Error llvm::OrcCBindingsStack::setIndirectStubPointer (StringRef Name, JITTargetAddress Addr) inline
Definition at line 280 of file OrcCBindingsStack.h.
References Name.
Referenced by LLVMOrcSetIndirectStubPointer().
shutdown()
Error llvm::OrcCBindingsStack::shutdown () inline
Definition at line 241 of file OrcCBindingsStack.h.
References llvm::orc::LocalCXXRuntimeOverridesBase::runDestructors(), and llvm::Error::success().
UnregisterJITEventListener()
void llvm::OrcCBindingsStack::UnregisterJITEventListener (JITEventListener * L) inline
Definition at line 435 of file OrcCBindingsStack.h.
References llvm::find(), I, llvm::reverse(), and std::swap().
The documentation for this class was generated from the following file:
lib/ExecutionEngine/Orc/OrcCBindingsStack.h