LLVM: llvm::IRBuilderFolder Class Reference
llvm::IRBuilderFolder Class Reference abstract
IRBuilderFolder - Interface for constant folding in IRBuilder.
#include "llvm/IR/IRBuilderFolder.h"
Public Member Functions
virtual ~IRBuilderFolder ()
virtual Value * CreateAdd (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const =0
virtual Value * CreateFAdd (Constant *LHS, Constant *RHS) const =0
virtual Value * CreateSub (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const =0
virtual Value * CreateFSub (Constant *LHS, Constant *RHS) const =0
virtual Value * CreateMul (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const =0
virtual Value * CreateFMul (Constant *LHS, Constant *RHS) const =0
virtual Value * CreateUDiv (Constant *LHS, Constant *RHS, bool isExact=false) const =0
virtual Value * CreateSDiv (Constant *LHS, Constant *RHS, bool isExact=false) const =0
virtual Value * CreateFDiv (Constant *LHS, Constant *RHS) const =0
virtual Value * CreateURem (Constant *LHS, Constant *RHS) const =0
virtual Value * CreateSRem (Constant *LHS, Constant *RHS) const =0
virtual Value * CreateFRem (Constant *LHS, Constant *RHS) const =0
virtual Value * CreateShl (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const =0
virtual Value * CreateLShr (Constant *LHS, Constant *RHS, bool isExact=false) const =0
virtual Value * CreateAShr (Constant *LHS, Constant *RHS, bool isExact=false) const =0
virtual Value * CreateAnd (Constant *LHS, Constant *RHS) const =0
virtual Value * CreateOr (Constant *LHS, Constant *RHS) const =0
virtual Value * CreateXor (Constant *LHS, Constant *RHS) const =0
virtual Value * CreateBinOp (Instruction::BinaryOps Opc, Constant *LHS, Constant *RHS) const =0
virtual Value * CreateNeg (Constant *C, bool HasNUW=false, bool HasNSW=false) const =0
virtual Value * CreateFNeg (Constant *C) const =0
virtual Value * CreateNot (Constant *C) const =0
virtual Value * CreateUnOp (Instruction::UnaryOps Opc, Constant *C) const =0
virtual Value * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList) const =0
virtual Value * CreateGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const =0
virtual Value * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList) const =0
virtual Value * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList) const =0
virtual Value * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const =0
virtual Value * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList) const =0
virtual Value * CreateCast (Instruction::CastOps Op, Constant *C, Type *DestTy) const =0
virtual Value * CreatePointerCast (Constant *C, Type *DestTy) const =0
virtual Value * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const =0
virtual Value * CreateIntCast (Constant *C, Type *DestTy, bool isSigned) const =0
virtual Value * CreateFPCast (Constant *C, Type *DestTy) const =0
virtual Value * CreateBitCast (Constant *C, Type *DestTy) const =0
virtual Value * CreateIntToPtr (Constant *C, Type *DestTy) const =0
virtual Value * CreatePtrToInt (Constant *C, Type *DestTy) const =0
virtual Value * CreateZExtOrBitCast (Constant *C, Type *DestTy) const =0
virtual Value * CreateSExtOrBitCast (Constant *C, Type *DestTy) const =0
virtual Value * CreateTruncOrBitCast (Constant *C, Type *DestTy) const =0
virtual Value * CreateICmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const =0
virtual Value * CreateFCmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const =0
virtual Value * CreateSelect (Constant *C, Constant *True, Constant *False) const =0
virtual Value * CreateExtractElement (Constant *Vec, Constant *Idx) const =0
virtual Value * CreateInsertElement (Constant *Vec, Constant *NewElt, Constant *Idx) const =0
virtual Value * CreateShuffleVector (Constant *V1, Constant *V2, ArrayRef< int > Mask) const =0
virtual Value * CreateExtractValue (Constant *Agg, ArrayRef< unsigned > IdxList) const =0
virtual Value * CreateInsertValue (Constant *Agg, Constant *Val, ArrayRef< unsigned > IdxList) const =0
Detailed Description
IRBuilderFolder - Interface for constant folding in IRBuilder.
Definition at line 24 of file IRBuilderFolder.h.
Constructor & Destructor Documentation
~IRBuilderFolder()
IRBuilderFolder::~IRBuilderFolder () virtual
Definition at line 1172 of file IRBuilder.cpp.
Member Function Documentation
CreateAdd()
virtual Value * llvm::IRBuilderFolder::CreateAdd (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateAdd().
CreateAnd()
virtual Value * llvm::IRBuilderFolder::CreateAnd (Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateAnd().
CreateAShr()
virtual Value * llvm::IRBuilderFolder::CreateAShr (Constant * LHS, Constant * RHS, bool isExact = false) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateAShr().
CreateBinOp()
virtual Value * llvm::IRBuilderFolder::CreateBinOp (Instruction::BinaryOps Opc, Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateBitCast()
virtual Value * llvm::IRBuilderFolder::CreateBitCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateCast()
virtual Value * llvm::IRBuilderFolder::CreateCast (Instruction::CastOps Op, Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateCast().
CreateExtractElement()
virtual Value * llvm::IRBuilderFolder::CreateExtractElement (Constant * Vec, Constant * Idx) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateExtractElement().
CreateExtractValue()
virtual Value * llvm::IRBuilderFolder::CreateExtractValue (Constant * Agg, ArrayRef< unsigned > IdxList) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateExtractValue().
CreateFAdd()
virtual Value * llvm::IRBuilderFolder::CreateFAdd (Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateFCmp()
virtual Value * llvm::IRBuilderFolder::CreateFCmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateFDiv()
virtual Value * llvm::IRBuilderFolder::CreateFDiv (Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateFMul()
virtual Value * llvm::IRBuilderFolder::CreateFMul (Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateFNeg()
virtual Value * llvm::IRBuilderFolder::CreateFNeg (Constant * C) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateFNeg(), and llvm::IRBuilderBase::CreateFNegFMF().
CreateFPCast()
virtual Value * llvm::IRBuilderFolder::CreateFPCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateFPCast().
CreateFRem()
virtual Value * llvm::IRBuilderFolder::CreateFRem (Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateFSub()
virtual Value * llvm::IRBuilderFolder::CreateFSub (Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateGetElementPtr() [1/3]
virtual Value * llvm::IRBuilderFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateConstGEP1_32(), llvm::IRBuilderBase::CreateConstGEP1_64(), llvm::IRBuilderBase::CreateConstGEP2_32(), llvm::IRBuilderBase::CreateConstGEP2_64(), llvm::IRBuilderBase::CreateGEP(), and llvm::IRBuilderBase::CreateGEP().
CreateGetElementPtr() [2/3]
virtual Value * llvm::IRBuilderFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateGetElementPtr() [3/3]
virtual Value * llvm::IRBuilderFolder::CreateGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateICmp()
virtual Value * llvm::IRBuilderFolder::CreateICmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateICmp().
CreateInBoundsGetElementPtr() [1/3]
virtual Value * llvm::IRBuilderFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateConstInBoundsGEP1_32(), llvm::IRBuilderBase::CreateConstInBoundsGEP1_64(), llvm::IRBuilderBase::CreateConstInBoundsGEP2_32(), llvm::IRBuilderBase::CreateConstInBoundsGEP2_64(), llvm::IRBuilderBase::CreateInBoundsGEP(), and llvm::IRBuilderBase::CreateInBoundsGEP().
CreateInBoundsGetElementPtr() [2/3]
virtual Value * llvm::IRBuilderFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateInBoundsGetElementPtr() [3/3]
virtual Value * llvm::IRBuilderFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateInsertElement()
virtual Value * llvm::IRBuilderFolder::CreateInsertElement (Constant * Vec, Constant * NewElt, Constant * Idx) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateInsertElement().
CreateInsertValue()
virtual Value * llvm::IRBuilderFolder::CreateInsertValue (Constant * Agg, Constant * Val, ArrayRef< unsigned > IdxList) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateInsertValue().
CreateIntCast()
virtual Value * llvm::IRBuilderFolder::CreateIntCast (Constant * C, Type * DestTy, bool isSigned) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateIntCast().
CreateIntToPtr()
virtual Value * llvm::IRBuilderFolder::CreateIntToPtr (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateLShr()
virtual Value * llvm::IRBuilderFolder::CreateLShr (Constant * LHS, Constant * RHS, bool isExact = false) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateLShr().
CreateMul()
virtual Value * llvm::IRBuilderFolder::CreateMul (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateMul().
CreateNeg()
virtual Value * llvm::IRBuilderFolder::CreateNeg (Constant * C, bool HasNUW = false, bool HasNSW = false) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateNeg().
CreateNot()
virtual Value * llvm::IRBuilderFolder::CreateNot (Constant * C) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateNot().
CreateOr()
virtual Value * llvm::IRBuilderFolder::CreateOr (Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateOr().
CreatePointerBitCastOrAddrSpaceCast()
virtual Value * llvm::IRBuilderFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreatePointerBitCastOrAddrSpaceCast().
CreatePointerCast()
virtual Value * llvm::IRBuilderFolder::CreatePointerCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreatePointerCast().
CreatePtrToInt()
virtual Value * llvm::IRBuilderFolder::CreatePtrToInt (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateSDiv()
virtual Value * llvm::IRBuilderFolder::CreateSDiv (Constant * LHS, Constant * RHS, bool isExact = false) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateSDiv().
CreateSelect()
virtual Value * llvm::IRBuilderFolder::CreateSelect (Constant * C, Constant * True, Constant * False) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateSelect().
CreateSExtOrBitCast()
virtual Value * llvm::IRBuilderFolder::CreateSExtOrBitCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateSExtOrBitCast().
CreateShl()
virtual Value * llvm::IRBuilderFolder::CreateShl (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateShl().
CreateShuffleVector()
virtual Value * llvm::IRBuilderFolder::CreateShuffleVector (Constant * V1, Constant * V2, ArrayRef< int > Mask) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateShuffleVector().
CreateSRem()
virtual Value * llvm::IRBuilderFolder::CreateSRem (Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateSub()
virtual Value * llvm::IRBuilderFolder::CreateSub (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateSub().
CreateTruncOrBitCast()
virtual Value * llvm::IRBuilderFolder::CreateTruncOrBitCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateTruncOrBitCast().
CreateUDiv()
virtual Value * llvm::IRBuilderFolder::CreateUDiv (Constant * LHS, Constant * RHS, bool isExact = false) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateUDiv().
CreateUnOp()
virtual Value * llvm::IRBuilderFolder::CreateUnOp (Instruction::UnaryOps Opc, Constant * C) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateUnOp().
CreateURem()
virtual Value * llvm::IRBuilderFolder::CreateURem (Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateXor()
virtual Value * llvm::IRBuilderFolder::CreateXor (Constant * LHS, Constant * RHS) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
CreateZExtOrBitCast()
virtual Value * llvm::IRBuilderFolder::CreateZExtOrBitCast (Constant * C, Type * DestTy) const pure virtual
Implemented in llvm::TargetFolder, llvm::ConstantFolder, and llvm::NoFolder.
Referenced by llvm::IRBuilderBase::CreateZExtOrBitCast().
The documentation for this class was generated from the following files:
include/llvm/IR/IRBuilderFolder.h
lib/IR/IRBuilder.cpp