LLVM: llvm::DbgVariableIntrinsic Class Reference
llvm::DbgVariableIntrinsic Class Reference
This is the common base class for debug info intrinsics for variables.
#include "llvm/IR/IntrinsicInst.h"
Public Member Functions
Value * getVariableLocation (bool AllowNullOp=true) const
Get the location corresponding to the variable referenced by the debug info intrinsic.
bool isAddressOfVariable () const
Does this describe the address of a local variable.
DILocalVariable * getVariable () const
DIExpression * getExpression () const
Metadata * getRawVariable () const
Metadata * getRawExpression () const
Optional< uint64_t > getFragmentSizeInBits () const
Get the size (in bits) of the variable, or fragment of the variable that is described.
Public Member Functions inherited from llvm::IntrinsicInst
IntrinsicInst ()=delete
IntrinsicInst (const IntrinsicInst &)=delete
IntrinsicInst & operator= (const IntrinsicInst &)=delete
Intrinsic::ID getIntrinsicID () const
Return the intrinsic ID of this intrinsic.
Public Member Functions inherited from llvm::CallInst
TailCallKind getTailCallKind () const
bool isTailCall () const
bool isMustTailCall () const
bool isNoTailCall () const
void setTailCallKind (TailCallKind TCK)
void setTailCall (bool IsTc=true)
bool canReturnTwice () const
Return true if the call can return twice.
void setCanReturnTwice ()
void updateProfWeight (uint64_t S, uint64_t T)
Updates profile metadata by scaling it by S / T.
Public Member Functions inherited from llvm::CallBase
FunctionType * getFunctionType () const
void mutateFunctionType (FunctionType *FTy)
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
User::op_iterator data_operands_begin ()
data_operands_begin/data_operands_end - Return iterators iterating over the call / invoke argument list and bundle operands.
User::const_op_iterator data_operands_begin () const
User::op_iterator data_operands_end ()
User::const_op_iterator data_operands_end () const
iterator_range< User::op_iterator > data_ops ()
iterator_range< User::const_op_iterator > data_ops () const
bool data_operands_empty () const
unsigned data_operands_size () const
bool isDataOperand (const Use *U) const
bool isDataOperand (Value::const_user_iterator UI) const
unsigned getDataOperandNo (Value::const_user_iterator UI) const
Given a value use iterator, return the data operand corresponding to it.
unsigned getDataOperandNo (const Use *U) const
Given a use for a data operand, get the data operand number that corresponds to it.
User::op_iterator arg_begin ()
Return the iterator pointing to the beginning of the argument list.
User::const_op_iterator arg_begin () const
User::op_iterator arg_end ()
Return the iterator pointing to the end of the argument list.
User::const_op_iterator arg_end () const
iterator_range< User::op_iterator > args ()
Iteration adapter for range-for loops.
iterator_range< User::const_op_iterator > args () const
bool arg_empty () const
unsigned arg_size () const
iterator_range< User::op_iterator > arg_operands ()
iterator_range< User::const_op_iterator > arg_operands () const
unsigned getNumArgOperands () const
Value * getArgOperand (unsigned i) const
void setArgOperand (unsigned i, Value *v)
const Use & getArgOperandUse (unsigned i) const
Wrappers for getting the Use of a call argument.
Use & getArgOperandUse (unsigned i)
bool isArgOperand (const Use *U) const
bool isArgOperand (Value::const_user_iterator UI) const
unsigned getArgOperandNo (const Use *U) const
Given a use for a arg operand, get the arg operand number that corresponds to it.
unsigned getArgOperandNo (Value::const_user_iterator UI) const
Given a value use iterator, return the arg operand number corresponding to it.
bool hasArgument (const Value *V) const
Returns true if this CallSite passes the given Value* as an argument to the called function.
Value * getCalledOperand () const
const Use & getCalledOperandUse () const
Use & getCalledOperandUse ()
Function * getCalledFunction () const
Returns the function called, or null if this is an indirect function invocation.
bool isIndirectCall () const
Return true if the callsite is an indirect call.
bool isCallee (Value::const_user_iterator UI) const
Determine whether the passed iterator points to the callee operand's Use.
bool isCallee (const Use *U) const
Determine whether this Use is the callee operand's Use.
Function * getCaller ()
Helper to get the caller (the parent function).
const Function * getCaller () const
bool isMustTailCall () const
Tests if this call site must be tail call optimized.
bool isTailCall () const
Tests if this call site is marked as a tail call.
Intrinsic::ID getIntrinsicID () const
Returns the intrinsic ID of the intrinsic called or Intrinsic::not_intrinsic if the called function is not an intrinsic, or if this is an indirect call.
void setCalledOperand (Value *V)
void setCalledFunction (Function *Fn)
Sets the function called, including updating the function type.
void setCalledFunction (FunctionCallee Fn)
Sets the function called, including updating the function type.
void setCalledFunction (FunctionType *FTy, Value *Fn)
Sets the function called, including updating to the specified function type.
CallingConv::ID getCallingConv () const
void setCallingConv (CallingConv::ID CC)
bool isInlineAsm () const
Check if this call is an inline asm statement.
AttributeList getAttributes () const
Return the parameter attributes for this call.
void setAttributes (AttributeList A)
Set the parameter attributes for this call.
bool hasFnAttr (Attribute::AttrKind Kind) const
Determine whether this call has the given attribute.
bool hasFnAttr (StringRef Kind) const
Determine whether this call has the given attribute.
void addAttribute (unsigned i, Attribute::AttrKind Kind)
adds the attribute to the list of attributes.
void addAttribute (unsigned i, Attribute Attr)
adds the attribute to the list of attributes.
void addParamAttr (unsigned ArgNo, Attribute::AttrKind Kind)
Adds the attribute to the indicated argument.
void addParamAttr (unsigned ArgNo, Attribute Attr)
Adds the attribute to the indicated argument.
void removeAttribute (unsigned i, Attribute::AttrKind Kind)
removes the attribute from the list of attributes.
void removeAttribute (unsigned i, StringRef Kind)
removes the attribute from the list of attributes.
void removeParamAttr (unsigned ArgNo, Attribute::AttrKind Kind)
Removes the attribute from the given argument.
void removeParamAttr (unsigned ArgNo, StringRef Kind)
Removes the attribute from the given argument.
void addDereferenceableAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable attribute to the list of attributes.
void addDereferenceableOrNullAttr (unsigned i, uint64_t Bytes)
adds the dereferenceable_or_null attribute to the list of attributes.
bool hasRetAttr (Attribute::AttrKind Kind) const
Determine whether the return value has the given attribute.
bool paramHasAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Determine whether the argument or parameter has the given attribute.
Attribute getAttribute (unsigned i, Attribute::AttrKind Kind) const
Get the attribute of a given kind at a position.
Attribute getAttribute (unsigned i, StringRef Kind) const
Get the attribute of a given kind at a position.
Attribute getParamAttr (unsigned ArgNo, Attribute::AttrKind Kind) const
Get the attribute of a given kind from a given arg.
Attribute getParamAttr (unsigned ArgNo, StringRef Kind) const
Get the attribute of a given kind from a given arg.
bool dataOperandHasImpliedAttr (unsigned i, Attribute::AttrKind Kind) const
Return true if the data operand at index i has the attribute A.
bool doesNotCapture (unsigned OpNo) const
Determine whether this data operand is not captured.
bool isByValArgument (unsigned ArgNo) const
Determine whether this argument is passed by value.
bool isInAllocaArgument (unsigned ArgNo) const
Determine whether this argument is passed in an alloca.
bool isPassPointeeByValueArgument (unsigned ArgNo) const
Determine whether this argument is passed by value, in an alloca, or is preallocated.
bool hasInAllocaArgument () const
Determine if there are is an inalloca argument.
bool doesNotAccessMemory (unsigned OpNo) const
bool onlyReadsMemory (unsigned OpNo) const
bool doesNotReadMemory (unsigned OpNo) const
LLVM_ATTRIBUTE_DEPRECATED (unsigned getRetAlignment() const, "Use getRetAlign() instead")
MaybeAlign getRetAlign () const
Extract the alignment of the return value.
LLVM_ATTRIBUTE_DEPRECATED (unsigned getParamAlignment(unsigned ArgNo) const, "Use getParamAlign() instead")
Extract the alignment for a call or parameter (0=unknown).
MaybeAlign getParamAlign (unsigned ArgNo) const
Extract the alignment for a call or parameter (0=unknown).
Type * getParamByValType (unsigned ArgNo) const
Extract the byval type for a call or parameter.
Type * getParamPreallocatedType (unsigned ArgNo) const
Extract the preallocated type for a call or parameter.
uint64_t getDereferenceableBytes (unsigned i) const
Extract the number of dereferenceable bytes for a call or parameter (0=unknown).
uint64_t getDereferenceableOrNullBytes (unsigned i) const
Extract the number of dereferenceable_or_null bytes for a call or parameter (0=unknown).
bool isReturnNonNull () const
Return true if the return value is known to be not null.
bool returnDoesNotAlias () const
Determine if the return value is marked with NoAlias attribute.
Value * getReturnedArgOperand () const
If one of the arguments has the 'returned' attribute, returns its operand value.
bool isNoBuiltin () const
Return true if the call should not be treated as a call to a builtin.
bool isStrictFP () const
Determine if the call requires strict floating point semantics.
bool isNoInline () const
Return true if the call should not be inlined.
void setIsNoInline ()
bool doesNotAccessMemory () const
Determine if the call does not access memory.
void setDoesNotAccessMemory ()
bool onlyReadsMemory () const
Determine if the call does not access or only reads memory.
void setOnlyReadsMemory ()
bool doesNotReadMemory () const
Determine if the call does not access or only writes memory.
void setDoesNotReadMemory ()
bool onlyAccessesArgMemory () const
Determine if the call can access memmory only using pointers based on its arguments.
void setOnlyAccessesArgMemory ()
bool onlyAccessesInaccessibleMemory () const
Determine if the function may only access memory that is inaccessible from the IR.
void setOnlyAccessesInaccessibleMemory ()
bool onlyAccessesInaccessibleMemOrArgMem () const
Determine if the function may only access memory that is either inaccessible from the IR or pointed to by its arguments.
void setOnlyAccessesInaccessibleMemOrArgMem ()
bool doesNotReturn () const
Determine if the call cannot return.
void setDoesNotReturn ()
bool doesNoCfCheck () const
Determine if the call should not perform indirect branch tracking.
bool doesNotThrow () const
Determine if the call cannot unwind.
void setDoesNotThrow ()
bool cannotDuplicate () const
Determine if the invoke cannot be duplicated.
void setCannotDuplicate ()
bool cannotMerge () const
Determine if the call cannot be tail merged.
void setCannotMerge ()
bool isConvergent () const
Determine if the invoke is convergent.
void setConvergent ()
void setNotConvergent ()
bool hasStructRetAttr () const
Determine if the call returns a structure through first pointer argument.
bool hasByValArgument () const
Determine if any call argument is an aggregate passed by value.
unsigned getNumOperandBundles () const
Return the number of operand bundles associated with this User.
bool hasOperandBundles () const
Return true if this User has any operand bundles.
unsigned getBundleOperandsStartIndex () const
Return the index of the first bundle operand in the Use array.
unsigned getBundleOperandsEndIndex () const
Return the index of the last bundle operand in the Use array.
bool isBundleOperand (unsigned Idx) const
Return true if the operand at index Idx is a bundle operand.
bool isBundleOperand (const Use *U) const
Returns true if the use is a bundle operand.
bool isBundleOperand (Value::const_user_iterator UI) const
unsigned getNumTotalBundleOperands () const
Return the total number operands (not operand bundles) used by every operand bundle in this OperandBundleUser.
OperandBundleUse getOperandBundleAt (unsigned Index) const
Return the operand bundle at a specific index.
unsigned countOperandBundlesOfType (StringRef Name) const
Return the number of operand bundles with the tag Name attached to this instruction.
unsigned countOperandBundlesOfType (uint32_t ID) const
Return the number of operand bundles with the tag ID attached to this instruction.
Optional< OperandBundleUse > getOperandBundle (StringRef Name) const
Return an operand bundle by name, if present.
Optional< OperandBundleUse > getOperandBundle (uint32_t ID) const
Return an operand bundle by tag ID, if present.
void getOperandBundlesAsDefs (SmallVectorImpl< OperandBundleDef > &Defs) const
Return the list of operand bundles attached to this instruction as a vector of OperandBundleDefs.
OperandBundleUse getOperandBundleForOperand (unsigned OpIdx) const
Return the operand bundle for the operand at index OpIdx.
bool hasReadingOperandBundles () const
Return true if this operand bundle user has operand bundles that may read from the heap.
bool hasClobberingOperandBundles () const
Return true if this operand bundle user has operand bundles that may write to the heap.
bool bundleOperandHasAttr (unsigned OpIdx, Attribute::AttrKind A) const
Return true if the bundle operand at index OpIdx has the attribute A.
bool hasIdenticalOperandBundleSchema (const CallBase &Other) const
Return true if Other has the same sequence of operand bundle tags with the same number of operands on each one of them as this OperandBundleUser.
bool hasOperandBundlesOtherThan (ArrayRef< uint32_t > IDs) const
Return true if this operand bundle user contains operand bundles with tags other than those specified in IDs.
bool isFnAttrDisallowedByOpBundle (StringRef S) const
Is the function attribute S disallowed by some operand bundle on this operand bundle user?
bool isFnAttrDisallowedByOpBundle (Attribute::AttrKind A) const
Is the function attribute A disallowed by some operand bundle on this operand bundle user?
OperandBundleUse operandBundleFromBundleOpInfo (const BundleOpInfo &BOI) const
Simple helper function to map a BundleOpInfo to an OperandBundleUse.
bundle_op_iterator bundle_op_info_begin ()
Return the start of the list of BundleOpInfo instances associated with this OperandBundleUser.
const_bundle_op_iterator bundle_op_info_begin () const
Return the start of the list of BundleOpInfo instances associated with this OperandBundleUser.
bundle_op_iterator bundle_op_info_end ()
Return the end of the list of BundleOpInfo instances associated with this OperandBundleUser.
const_bundle_op_iterator bundle_op_info_end () const
Return the end of the list of BundleOpInfo instances associated with this OperandBundleUser.
iterator_range< bundle_op_iterator > bundle_op_infos ()
Return the range [bundle_op_info_begin, bundle_op_info_end).
iterator_range< const_bundle_op_iterator > bundle_op_infos () const
Return the range [bundle_op_info_begin, bundle_op_info_end).
op_iterator populateBundleOperandInfos (ArrayRef< OperandBundleDef > Bundles, const unsigned BeginIndex)
Populate the BundleOpInfo instances and the Use& vector from Bundles.
BundleOpInfo & getBundleOpInfoForOperand (unsigned OpIdx)
Return the BundleOpInfo for the operand at index OpIdx.
const BundleOpInfo & getBundleOpInfoForOperand (unsigned OpIdx) const
Public Member Functions inherited from llvm::Instruction
Instruction (const Instruction &)=delete
Instruction & operator= (const Instruction &)=delete
Instruction * user_back ()
Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
const Instruction * user_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
const Module * getModule () const
Return the module owning the function this instruction belongs to or nullptr it the function does not have a module.
Module * getModule ()
const Function * getFunction () const
Return the function this instruction belongs to.
Function * getFunction ()
void removeFromParent ()
This method unlinks 'this' from the containing basic block, but does not delete it.
SymbolTableList< Instruction >::iterator eraseFromParent ()
This method unlinks 'this' from the containing basic block and deletes it.
void insertBefore (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately before the specified instruction.
void insertAfter (Instruction *InsertPos)
Insert an unlinked instruction into a basic block immediately after the specified instruction.
void moveBefore (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
void moveBefore (BasicBlock &BB, SymbolTableList< Instruction >::iterator I)
Unlink this instruction and insert into BB before I.
void moveAfter (Instruction *MovePos)
Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right after MovePos.
bool comesBefore (const Instruction *Other) const
Given an instruction Other in the same basic block as this instruction, return true if this instruction comes before Other.
unsigned getOpcode () const
Returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isUnaryOp () const
bool isBinaryOp () const
bool isIntDivRem () const
bool isShift () const
bool isCast () const
bool isFuncletPad () const
bool isExceptionalTerminator () const
bool isIndirectTerminator () const
bool isLogicalShift () const
Return true if this is a logical shift left or a logical shift right.
bool isArithmeticShift () const
Return true if this is an arithmetic shift right.
bool isBitwiseLogicOp () const
Return true if this is and/or/xor.
bool hasMetadata () const
Return true if this instruction has any metadata attached to it.
bool hasMetadataOtherThanDebugLoc () const
Return true if this instruction has metadata attached to it other than a debug location.
bool hasMetadata (unsigned KindID) const
Return true if this instruction has the given type of metadata attached.
bool hasMetadata (StringRef Kind) const
Return true if this instruction has the given type of metadata attached.
MDNode * getMetadata (unsigned KindID) const
Get the metadata of given kind attached to this Instruction.
MDNode * getMetadata (StringRef Kind) const
Get the metadata of given kind attached to this Instruction.
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
Get all metadata attached to this Instruction.
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
This does the same thing as getAllMetadata, except that it filters out the debug location.
void getAAMetadata (AAMDNodes &N, bool Merge=false) const
Fills the AAMDNodes structure with AA metadata from this instruction.
void setMetadata (unsigned KindID, MDNode *Node)
Set the metadata of the specified kind to the specified node.
void setMetadata (StringRef Kind, MDNode *Node)
void copyMetadata (const Instruction &SrcInst, ArrayRef< unsigned > WL=ArrayRef< unsigned >())
Copy metadata from SrcInst to this instruction.
void swapProfMetadata ()
If the instruction has "branch_weights" MD_prof metadata and the MDNode has three operands (including name string), swap the order of the metadata.
void setAAMetadata (const AAMDNodes &N)
Sets the metadata on this instruction from the AAMDNodes structure.
bool extractProfMetadata (uint64_t &TrueVal, uint64_t &FalseVal) const
Retrieve the raw weight values of a conditional branch or select.
bool extractProfTotalWeight (uint64_t &TotalVal) const
Retrieve total raw weight values of a branch.
void setDebugLoc (DebugLoc Loc)
Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
Return the debug location for this node as a DebugLoc.
void setHasNoUnsignedWrap (bool b=true)
Set or clear the nuw flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedWrap (bool b=true)
Set or clear the nsw flag on this instruction, which must be an operator which supports this flag.
void setIsExact (bool b=true)
Set or clear the exact flag on this instruction, which must be an operator which supports this flag.
bool hasNoUnsignedWrap () const
Determine whether the no unsigned wrap flag is set.
bool hasNoSignedWrap () const
Determine whether the no signed wrap flag is set.
void dropPoisonGeneratingFlags ()
Drops flags that may cause this instruction to evaluate to poison despite having non-poison inputs.
bool isExact () const
Determine whether the exact flag is set.
void setFast (bool B)
Set or clear all fast-math-flags on this instruction, which must be an operator which supports this flag.
void setHasAllowReassoc (bool B)
Set or clear the reassociation flag on this instruction, which must be an operator which supports this flag.
void setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag.
void setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag.
void setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag.
void setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag.
void setHasAllowContract (bool B)
Set or clear the allow-contract flag on this instruction, which must be an operator which supports this flag.
void setHasApproxFunc (bool B)
Set or clear the approximate-math-functions flag on this instruction, which must be an operator which supports this flag.
void setFastMathFlags (FastMathFlags FMF)
Convenience function for setting multiple fast-math flags on this instruction, which must be an operator which supports these flags.
void copyFastMathFlags (FastMathFlags FMF)
Convenience function for transferring all fast-math flag values to this instruction, which must be an operator which supports these flags.
bool isFast () const
Determine whether all fast-math-flags are set.
bool hasAllowReassoc () const
Determine whether the allow-reassociation flag is set.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
bool hasAllowContract () const
Determine whether the allow-contract flag is set.
bool hasApproxFunc () const
Determine whether the approximate-math-functions flag is set.
FastMathFlags getFastMathFlags () const
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags.
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
void copyIRFlags (const Value *V, bool IncludeWrapFlags=true)
Convenience method to copy supported exact, fast-math, and (optionally) wrapping flags from V to this instruction.
void andIRFlags (const Value *V)
Logical 'and' of any supported wrapping, exact, and fast-math flags of V and this instruction.
void applyMergedLocation (const DILocation *LocA, const DILocation *LocB)
Merge 2 debug locations and apply it to the Instruction.
bool isAssociative () const LLVM_READONLY
Return true if the instruction is associative:
bool isCommutative () const
Return true if the instruction is commutative:
bool isIdempotent () const
Return true if the instruction is idempotent:
bool isNilpotent () const
Return true if the instruction is nilpotent:
bool mayWriteToMemory () const
Return true if this instruction may modify memory.
bool mayReadFromMemory () const
Return true if this instruction may read memory.
bool mayReadOrWriteMemory () const
Return true if this instruction may read or write memory.
bool isAtomic () const
Return true if this instruction has an AtomicOrdering of unordered or higher.
bool hasAtomicLoad () const
Return true if this atomic instruction loads from memory.
bool hasAtomicStore () const
Return true if this atomic instruction stores to memory.
bool mayThrow () const
Return true if this instruction may throw an exception.
bool isFenceLike () const
Return true if this instruction behaves like a memory fence: it can load or store to memory location without being given a memory location.
bool mayHaveSideEffects () const
Return true if the instruction may have side effects.
bool isSafeToRemove () const
Return true if the instruction can be removed if the result is unused.
bool isEHPad () const
Return true if the instruction is a variety of EH-block.
bool isLifetimeStartOrEnd () const
Return true if the instruction is a llvm.lifetime.start or llvm.lifetime.end marker.
const Instruction * getNextNonDebugInstruction () const
Return a pointer to the next non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getNextNonDebugInstruction ()
const Instruction * getPrevNonDebugInstruction () const
Return a pointer to the previous non-debug instruction in the same basic block as 'this', or nullptr if no such instruction exists.
Instruction * getPrevNonDebugInstruction ()
Instruction * clone () const
Create a copy of 'this' instruction that is identical in all ways except the following:
bool isIdenticalTo (const Instruction *I) const
Return true if the specified instruction is exactly identical to the current one.
bool isIdenticalToWhenDefined (const Instruction *I) const
This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which may specify conditions under which the instruction's result is undefined.
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
This function determines if the specified instruction executes the same operation as the current one.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Return true if there are any uses of this instruction in blocks other than the specified block.
unsigned getNumSuccessors () const
Return the number of successors that this instruction has.
BasicBlock * getSuccessor (unsigned Idx) const
Return the specified successor. This instruction must be a terminator.
void setSuccessor (unsigned Idx, BasicBlock *BB)
Update the specified successor to point at the provided block.
void replaceSuccessorWith (BasicBlock *OldBB, BasicBlock *NewBB)
Replace specified successor OldBB to point at the provided block.
void dropUnknownNonDebugMetadata (ArrayRef< unsigned > KnownIDs)
Drop all unknown metadata except for debug locations.
void dropUnknownNonDebugMetadata ()
void dropUnknownNonDebugMetadata (unsigned ID1)
void dropUnknownNonDebugMetadata (unsigned ID1, unsigned ID2)
Public Member Functions inherited from llvm::User
User (const User &)=delete
void operator delete (void *Usr)
Free memory allocated for User and Use objects.
void operator delete (void *Usr, unsigned)
Placement delete - required by std, called if the ctor throws.
void operator delete (void *Usr, unsigned, unsigned)
Placement delete - required by std, called if the ctor throws.
const Use * getOperandList () const
Use * getOperandList ()
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
ArrayRef< const uint8_t > getDescriptor () const
Returns the descriptor co-allocated with this User instance.
MutableArrayRef< uint8_t > getDescriptor ()
Returns the descriptor co-allocated with this User instance.
void setGlobalVariableNumOperands (unsigned NumOps)
Set the number of operands on a GlobalVariable.
void setNumHungOffUseOperands (unsigned NumOps)
Subclasses with hung off uses need to manage the operand count themselves.
bool isDroppable () const
A droppable user is a user for which uses can be dropped without affecting correctness and should be dropped rather than preventing a transformation from happening.
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
op_range operands ()
const_op_range operands () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
iterator_range< value_op_iterator > operand_values ()
const_value_op_iterator value_op_begin () const
const_value_op_iterator value_op_end () const
iterator_range< const_value_op_iterator > operand_values () const
void dropAllReferences ()
Drop all references to operands.
void replaceUsesOfWith (Value *From, Value *To)
Replace uses of one Value with another.
Public Member Functions inherited from llvm::Value
Value (const Value &)=delete
Value & operator= (const Value &)=delete
void deleteValue ()
Delete a pointer to a generic Value.
void dump () const
Support for debugging, callable in GDB: V->dump()
Type * getType () const
All values are typed, get the type of this value.
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
Return a constant reference to the value's name.
void setName (const Twine &Name)
Change the name of the value.
void takeName (Value *V)
Transfer the name from V to this value.
void replaceAllUsesWith (Value *V)
Change all uses of this to point to a new Value.
void replaceNonMetadataUsesWith (Value *V)
Change non-metadata uses of this to point to a new Value.
void replaceUsesWithIf (Value *New, llvm::function_ref< bool(Use &U)> ShouldReplace)
Go through the uses list for this definition and make each use point to "V" if the callback ShouldReplace returns true for the given Use.
void replaceUsesOutsideBlock (Value *V, BasicBlock *BB)
replaceUsesOutsideBlock - Go through the uses list for this definition and make each use point to "V" instead of "this" when the use is outside the block.
void assertModuleIsMaterializedImpl () const
void assertModuleIsMaterialized () const
bool use_empty () const
bool materialized_use_empty () const
use_iterator materialized_use_begin ()
const_use_iterator materialized_use_begin () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
iterator_range< use_iterator > materialized_uses ()
iterator_range< const_use_iterator > materialized_uses () const
iterator_range< use_iterator > uses ()
iterator_range< const_use_iterator > uses () const
bool user_empty () const
user_iterator materialized_user_begin ()
const_user_iterator materialized_user_begin () const
user_iterator user_begin ()
const_user_iterator user_begin () const
user_iterator user_end ()
const_user_iterator user_end () const
User * user_back ()
const User * user_back () const
iterator_range< user_iterator > materialized_users ()
iterator_range< const_user_iterator > materialized_users () const
iterator_range< user_iterator > users ()
iterator_range< const_user_iterator > users () const
bool hasOneUse () const
Return true if there is exactly one user of this value.
bool hasNUses (unsigned N) const
Return true if this Value has exactly N users.
bool hasNUsesOrMore (unsigned N) const
Return true if this value has N users or more.
Use * getSingleUndroppableUse ()
Return true if there is exactly one user of this value that cannot be dropped.
bool hasNUndroppableUses (unsigned N) const
Return true if there this value.
bool hasNUndroppableUsesOrMore (unsigned N) const
Return true if this value has N users or more.
void dropDroppableUses (llvm::function_ref< bool(const Use *)> ShouldDrop=[](const Use *) { return true;})
Remove every uses that can safely be removed.
bool isUsedInBasicBlock (const BasicBlock *BB) const
Check if this value is used in the specified basic block.
unsigned getNumUses () const
This method computes the number of uses of this Value.
void addUse (Use &U)
This method should only be used by the Use class.
unsigned getValueID () const
Return an ID for the concrete type of this object.
unsigned getRawSubclassOptionalData () const
Return the raw optional flags value contained in this value.
void clearSubclassOptionalData ()
Clear the optional flags contained in this value.
bool hasSameSubclassOptionalData (const Value *V) const
Check the optional flags for equality.
bool hasValueHandle () const
Return true if there is a value handle associated with this value.
bool isUsedByMetadata () const
Return true if there is metadata referencing this value.
bool isSwiftError () const
Return true if this value is a swifterror value.
const Value * stripPointerCasts () const
Strip off pointer casts, all-zero GEPs and address space casts.
Value * stripPointerCasts ()
const Value * stripPointerCastsAndAliases () const
Strip off pointer casts, all-zero GEPs, address space casts, and aliases.
Value * stripPointerCastsAndAliases ()
const Value * stripPointerCastsSameRepresentation () const
Strip off pointer casts, all-zero GEPs and address space casts but ensures the representation of the result stays the same.
Value * stripPointerCastsSameRepresentation ()
const Value * stripPointerCastsAndInvariantGroups () const
Strip off pointer casts, all-zero GEPs and invariant group info.
Value * stripPointerCastsAndInvariantGroups ()
const Value * stripInBoundsConstantOffsets () const
Strip off pointer casts and all-constant inbounds GEPs.
Value * stripInBoundsConstantOffsets ()
const Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds, function_ref< bool(Value &Value, APInt &Offset)> ExternalAnalysis=nullptr) const
Accumulate the constant offset this value has compared to a base pointer.
Value * stripAndAccumulateConstantOffsets (const DataLayout &DL, APInt &Offset, bool AllowNonInbounds)
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
This is a wrapper around stripAndAccumulateConstantOffsets with the in-bounds requirement set to false.
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
const Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {}) const
Strip off pointer casts and inbounds GEPs.
Value * stripInBoundsOffsets (function_ref< void(const Value *)> Func=[](const Value *) {})
uint64_t getPointerDereferenceableBytes (const DataLayout &DL, bool &CanBeNull) const
Returns the number of bytes known to be dereferenceable for the pointer value.
Align getPointerAlignment (const DataLayout &DL) const
Returns an alignment of the pointer value.
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
Translate PHI node to its predecessor from the given basic block.
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
void mutateType (Type *Ty)
Mutate the type of this Value to be of the specified type.
template<class Compare >
void sortUseList (Compare Cmp)
Sort the use-list.
void reverseUseList ()
Reverse the use-list.
void print (raw_ostream &O, bool IsForDebug=false) const
Implement operator<< on Value.
void print (raw_ostream &O, ModuleSlotTracker &MST, bool IsForDebug=false) const
void printAsOperand (raw_ostream &O, bool PrintType=true, const Module *M=nullptr) const
Print the name of this Value out to the specified raw_ostream.
void printAsOperand (raw_ostream &O, bool PrintType, ModuleSlotTracker &MST) const
Public Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
Instruction * getPrevNode ()
const Instruction * getPrevNode () const
Get the previous node, or nullptr for the list head.
Instruction * getNextNode ()
Get the next node, or nullptr for the list tail.
const Instruction * getNextNode () const
Get the next node, or nullptr for the list tail.
Public Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
self_iterator getIterator ()
const_self_iterator getIterator () const
reverse_self_iterator getReverseIterator ()
const_reverse_self_iterator getReverseIterator () const
bool isSentinel () const
Check whether this is the sentinel node.
Static Public Member Functions
Casting methods
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::DbgInfoIntrinsic
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::IntrinsicInst
static bool classof (const CallInst *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::CallInst
static CallInst * Create (FunctionType *Ty, Value *F, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
static CallInst * Create (FunctionType *Ty, Value *Func, ArrayRef< Value * > Args, const Twine &NameStr, Instruction *InsertBefore=nullptr)
static CallInst * Create (FunctionType *Ty, Value *Func, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > Bundles=None, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
static CallInst * Create (FunctionType *Ty, Value *F, const Twine &NameStr, BasicBlock *InsertAtEnd)
static CallInst * Create (FunctionType *Ty, Value *Func, ArrayRef< Value * > Args, const Twine &NameStr, BasicBlock *InsertAtEnd)
static CallInst * Create (FunctionType *Ty, Value *Func, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > Bundles, const Twine &NameStr, BasicBlock *InsertAtEnd)
static CallInst * Create (FunctionCallee Func, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
static CallInst * Create (FunctionCallee Func, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > Bundles=None, const Twine &NameStr="", Instruction *InsertBefore=nullptr)
static CallInst * Create (FunctionCallee Func, ArrayRef< Value * > Args, const Twine &NameStr, Instruction *InsertBefore=nullptr)
static CallInst * Create (FunctionCallee Func, const Twine &NameStr, BasicBlock *InsertAtEnd)
static CallInst * Create (FunctionCallee Func, ArrayRef< Value * > Args, const Twine &NameStr, BasicBlock *InsertAtEnd)
static CallInst * Create (FunctionCallee Func, ArrayRef< Value * > Args, ArrayRef< OperandBundleDef > Bundles, const Twine &NameStr, BasicBlock *InsertAtEnd)
static CallInst * Create (CallInst *CI, ArrayRef< OperandBundleDef > Bundles, Instruction *InsertPt=nullptr)
Create a clone of CI with a different set of operand bundles and insert it before InsertPt.
static Instruction * CreateMalloc (Instruction *InsertBefore, Type *IntPtrTy, Type *AllocTy, Value *AllocSize, Value *ArraySize=nullptr, Function *MallocF=nullptr, const Twine &Name="")
Generate the IR for a call to malloc:
static Instruction * CreateMalloc (BasicBlock *InsertAtEnd, Type *IntPtrTy, Type *AllocTy, Value *AllocSize, Value *ArraySize=nullptr, Function *MallocF=nullptr, const Twine &Name="")
CreateMalloc - Generate the IR for a call to malloc:
static Instruction * CreateMalloc (Instruction *InsertBefore, Type *IntPtrTy, Type *AllocTy, Value *AllocSize, Value *ArraySize=nullptr, ArrayRef< OperandBundleDef > Bundles=None, Function *MallocF=nullptr, const Twine &Name="")
static Instruction * CreateMalloc (BasicBlock *InsertAtEnd, Type *IntPtrTy, Type *AllocTy, Value *AllocSize, Value *ArraySize=nullptr, ArrayRef< OperandBundleDef > Bundles=None, Function *MallocF=nullptr, const Twine &Name="")
static Instruction * CreateFree (Value *Source, Instruction *InsertBefore)
Generate the IR for a call to the builtin free function.
static Instruction * CreateFree (Value *Source, BasicBlock *InsertAtEnd)
CreateFree - Generate the IR for a call to the builtin free function.
static Instruction * CreateFree (Value *Source, ArrayRef< OperandBundleDef > Bundles, Instruction *InsertBefore)
static Instruction * CreateFree (Value *Source, ArrayRef< OperandBundleDef > Bundles, BasicBlock *InsertAtEnd)
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::CallBase
static CallBase * Create (CallBase *CB, ArrayRef< OperandBundleDef > Bundles, Instruction *InsertPt=nullptr)
Create a clone of CB with a different set of operand bundles and insert it before InsertPt.
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isUnaryOp (unsigned Opcode)
static bool isBinaryOp (unsigned Opcode)
static bool isIntDivRem (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isBitwiseLogicOp (unsigned Opcode)
Determine if the Opcode is and/or/xor.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isFuncletPad (unsigned OpCode)
Determine if the OpCode is one of the FuncletPadInst instructions.
static bool isExceptionalTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator related to exception handling.
static bool isIndirectTerminator (unsigned OpCode)
Returns true if the OpCode is a terminator with indirect targets.
static bool isAssociative (unsigned Opcode)
static bool isCommutative (unsigned Opcode)
static bool isIdempotent (unsigned Opcode)
static bool isNilpotent (unsigned Opcode)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Additional Inherited Members
Public Types inherited from llvm::CallInst
enum TailCallKind : unsigned {
TCK_None = 0 , TCK_Tail = 1 , TCK_MustTail = 2 , TCK_NoTail = 3 ,
TCK_LAST = TCK_NoTail
}
using TailCallKindField = Bitfield::Element<TailCallKind, 0, 2, TCK_LAST>
Public Types inherited from llvm::CallBase
using bundle_op_iterator = BundleOpInfo *
using const_bundle_op_iterator = const BundleOpInfo *
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0 , CompareUsingScalarTypes = 1<<1 }
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
enum TermOps
enum UnaryOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum FuncletPadOps
enum OtherOps
Public Types inherited from llvm::User
using op_iterator = Use*
using const_op_iterator = const Use*
using op_range = iterator_range<op_iterator>
using const_op_range = iterator_range<const_op_iterator>
Public Types inherited from llvm::Value
enum ValueTy
Concrete subclass of this.
using use_iterator = use_iterator_impl<Use>
using const_use_iterator = use_iterator_impl<const Use>
using user_iterator = user_iterator_impl<User>
using const_user_iterator = user_iterator_impl<const User>
Static Public Attributes inherited from llvm::Value
static const unsigned MaxAlignmentExponent = 29
The maximum alignment for instructions.
static const unsigned MaximumAlignment = 1u << MaxAlignmentExponent
Protected Types inherited from llvm::CallBase
using CallInstReservedField = Bitfield::Element<unsigned, 0, 2>
using CallingConvField
Protected Types inherited from llvm::Instruction
using OpaqueField = Bitfield::Element<uint16_t, 0, 15>
template<unsigned Offset>
using AlignmentBitfieldElementT
template<unsigned Offset>
using BoolBitfieldElementT = typename Bitfield::Element<bool, Offset, 1>
template<unsigned Offset>
using AtomicOrderingBitfieldElementT
Protected Types inherited from llvm::Value
enum : unsigned { NumUserOperandsBits = 28 }
The number of operands in the subclass.
Protected Types inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
using self_iterator
using const_self_iterator
using reverse_self_iterator
using const_reverse_self_iterator
Protected Member Functions inherited from llvm::CallInst
CallInst * cloneImpl () const
Protected Member Functions inherited from llvm::CallBase
template<class... ArgsTy>
CallBase (AttributeList const &A, FunctionType *FT, ArgsTy &&... Args)
bool hasDescriptor () const
unsigned getNumSubclassExtraOperands () const
unsigned getNumSubclassExtraOperandsDynamic () const
Get the number of extra operands for instructions that don't have a fixed number of extra operands.
Instruction (const Instruction &)=delete
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::Instruction
~Instruction ()
template<typename BitfieldElement >
BitfieldElement::Type getSubclassData () const
template<typename BitfieldElement >
void setSubclassData (typename BitfieldElement::Type Value)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=nullptr)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t Size)
Allocate a User with an operand pointer co-allocated.
void * operator new (size_t Size, unsigned Us)
Allocate a User with the operands co-allocated.
void * operator new (size_t Size, unsigned Us, unsigned DescBytes)
Allocate a User with the operands co-allocated.
User (Type *ty, unsigned vty, Use *, unsigned NumOps)
void allocHungoffUses (unsigned N, bool IsPhi=false)
Allocate the array of Uses, followed by a pointer (with bottom bit set) to the User.
void growHungoffUses (unsigned N, bool IsPhi=false)
Grow the number of hung off uses.
~User ()=default
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
Value (Type *Ty, unsigned scid)
~Value ()
Value's destructor should be virtual by design, but that would require that Value and all of its subclasses have a vtable that effectively duplicates the information in the value ID.
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node_with_parent< Instruction, BasicBlock >
ilist_node_with_parent ()=default
Protected Member Functions inherited from llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >
ilist_node_impl ()=default
Static Protected Member Functions inherited from llvm::CallBase
static unsigned CountBundleInputs (ArrayRef< OperandBundleDef > Bundles)
Return the total number of values used in Bundles.
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::CallBase
AttributeList Attrs
parameter attributes for callable
FunctionType * FTy
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Hold subclass data that can be dropped.
unsigned NumUserOperands: NumUserOperandsBits
unsigned IsUsedByMD: 1
unsigned HasName: 1
unsigned HasHungOffUses: 1
unsigned HasDescriptor: 1
Static Protected Attributes inherited from llvm::CallBase
static constexpr int CalledOperandOpEndIdx = -1
The last operand is the called operand.
Detailed Description
This is the common base class for debug info intrinsics for variables.
Definition at line 94 of file IntrinsicInst.h.
Member Function Documentation
classof() [1/2]
static bool llvm::DbgVariableIntrinsic::classof (const IntrinsicInst * I) inline static
Definition at line 129 of file IntrinsicInst.h.
References I.
Referenced by classof().
classof() [2/2]
static bool llvm::DbgVariableIntrinsic::classof (const Value * V) inline static
Definition at line 139 of file IntrinsicInst.h.
References classof(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
getExpression()
DIExpression * llvm::DbgVariableIntrinsic::getExpression () const inline
Definition at line 111 of file IntrinsicInst.h.
References getRawExpression(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::SelectionDAGBuilder::dropDanglingDebugInfo(), getFragmentSizeInBits(), processDbgDeclares(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), and llvm::FastISel::selectIntrinsicCall().
getFragmentSizeInBits()
Optional< uint64_t > DbgVariableIntrinsic::getFragmentSizeInBits () const
Get the size (in bits) of the variable, or fragment of the variable that is described.
Definition at line 55 of file IntrinsicInst.cpp.
References getExpression(), llvm::DIVariable::getSizeInBits(), and getVariable().
getRawExpression()
Metadata * llvm::DbgVariableIntrinsic::getRawExpression () const inline
Definition at line 119 of file IntrinsicInst.h.
References llvm::CallBase::getArgOperand(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by getExpression().
getRawVariable()
Metadata * llvm::DbgVariableIntrinsic::getRawVariable () const inline
Definition at line 115 of file IntrinsicInst.h.
References llvm::CallBase::getArgOperand(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by getVariable().
getVariable()
DILocalVariable * llvm::DbgVariableIntrinsic::getVariable () const inline
Definition at line 107 of file IntrinsicInst.h.
References getRawVariable(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
Referenced by llvm::SelectionDAGBuilder::dropDanglingDebugInfo(), getFragmentSizeInBits(), processDbgDeclares(), llvm::SelectionDAGBuilder::resolveDanglingDebugInfo(), and llvm::FastISel::selectIntrinsicCall().
getVariableLocation()
Value * DbgVariableIntrinsic::getVariableLocation (bool AllowNullOp = true) const
Get the location corresponding to the variable referenced by the debug info intrinsic.
DbgVariableIntrinsic - This is the common base class for debug info intrinsics for variables.
Depending on the intrinsic, this could be the variable's value or its address.
Definition at line 41 of file IntrinsicInst.cpp.
References assert(), llvm::CallBase::getArgOperand(), llvm::User::getNumOperands(), llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl(), and llvm::User::Op().
Referenced by llvm::DbgDeclareInst::getAddress(), llvm::DbgAddrIntrinsic::getAddress(), and llvm::DbgValueInst::getValue().
isAddressOfVariable()
bool llvm::DbgVariableIntrinsic::isAddressOfVariable () const inline
Does this describe the address of a local variable.
True for dbg.addr and dbg.declare, but not dbg.value, which describes its value.
Definition at line 103 of file IntrinsicInst.h.
References llvm::IntrinsicInst::getIntrinsicID().
The documentation for this class was generated from the following files:
include/llvm/IR/IntrinsicInst.h
lib/IR/IntrinsicInst.cpp