LLVM: llvm::opt::DerivedArgList Class Reference
llvm::opt::DerivedArgList Class Reference final
DerivedArgList - An ordered collection of driver arguments, whose storage may be in another argument list.
#include "llvm/Option/ArgList.h"
Public Member Functions
DerivedArgList (const InputArgList &BaseArgs)
Construct a new derived arg list from BaseArgs.
const char * getArgString (unsigned Index) const override
getArgString - Return the input argument string at Index.
unsigned getNumInputArgStrings () const override
getNumInputArgStrings - Return the number of original argument strings, which are guaranteed to be the first strings in the argument string list.
const InputArgList & getBaseArgs () const
Arg Synthesis
void AddSynthesizedArg (Arg *A)
AddSynthesizedArg - Add a argument to the list of synthesized arguments (to be freed).
const char * MakeArgStringRef (StringRef Str) const override
Construct a constant string pointer whose lifetime will match that of the ArgList.
void AddFlagArg (const Arg *BaseArg, const Option Opt)
AddFlagArg - Construct a new FlagArg for the given option Id and append it to the argument list.
void AddPositionalArg (const Arg *BaseArg, const Option Opt, StringRef Value)
AddPositionalArg - Construct a new Positional arg for the given option Id, with the provided Value and append it to the argument list.
void AddSeparateArg (const Arg *BaseArg, const Option Opt, StringRef Value)
AddSeparateArg - Construct a new Positional arg for the given option Id, with the provided Value and append it to the argument list.
void AddJoinedArg (const Arg *BaseArg, const Option Opt, StringRef Value)
AddJoinedArg - Construct a new Positional arg for the given option Id, with the provided Value and append it to the argument list.
Arg * MakeFlagArg (const Arg *BaseArg, const Option Opt) const
MakeFlagArg - Construct a new FlagArg for the given option Id.
Arg * MakePositionalArg (const Arg *BaseArg, const Option Opt, StringRef Value) const
MakePositionalArg - Construct a new Positional arg for the given option Id, with the provided Value.
Arg * MakeSeparateArg (const Arg *BaseArg, const Option Opt, StringRef Value) const
MakeSeparateArg - Construct a new Positional arg for the given option Id, with the provided Value.
Arg * MakeJoinedArg (const Arg *BaseArg, const Option Opt, StringRef Value) const
MakeJoinedArg - Construct a new Positional arg for the given option Id, with the provided Value.
const char * MakeArgString (const Twine &Str) const
Public Member Functions inherited from llvm::opt::ArgList
void append (Arg *A)
append - Append A to the arg list.
const arglist_type & getArgs () const
unsigned size () const
template<typename ... OptSpecifiers>
bool hasArgNoClaim (OptSpecifiers ...Ids) const
hasArg - Does the arg list contain any option matching Id.
template<typename ... OptSpecifiers>
bool hasArg (OptSpecifiers ...Ids) const
template<typename ... OptSpecifiers>
Arg * getLastArg (OptSpecifiers ...Ids) const
Return the last argument matching Id, or null.
template<typename ... OptSpecifiers>
Arg * getLastArgNoClaim (OptSpecifiers ...Ids) const
Return the last argument matching Id, or null.
iterator begin ()
iterator end ()
reverse_iterator rbegin ()
reverse_iterator rend ()
const_iterator begin () const
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
template<typename ... OptSpecifiers>
iterator_range< filtered_iterator< sizeof...(OptSpecifiers)> > filtered (OptSpecifiers ...Ids) const
template<typename ... OptSpecifiers>
iterator_range< filtered_reverse_iterator< sizeof...(OptSpecifiers)> > filtered_reverse (OptSpecifiers ...Ids) const
void eraseArg (OptSpecifier Id)
eraseArg - Remove any option matching Id.
StringRef getLastArgValue (OptSpecifier Id, StringRef Default="") const
getLastArgValue - Return the value of the last argument, or a default.
std::vector< std::string > getAllArgValues (OptSpecifier Id) const
getAllArgValues - Get the values of all instances of the given argument as strings.
bool hasFlag (OptSpecifier Pos, OptSpecifier Neg, bool Default=true) const
hasFlag - Given an option Pos and its negative form Neg, return true if the option is present, false if the negation is present, and Default if neither option is given.
bool hasFlag (OptSpecifier Pos, OptSpecifier PosAlias, OptSpecifier Neg, bool Default=true) const
hasFlag - Given an option Pos, an alias PosAlias and its negative form Neg, return true if the option or its alias is present, false if the negation is present, and Default if none of the options are given.
template<typename ... OptSpecifiers>
void AddLastArg (ArgStringList &Output, OptSpecifiers ...Ids) const
Render only the last argument match Id0, if present.
void AddAllArgsExcept (ArgStringList &Output, ArrayRef< OptSpecifier > Ids, ArrayRef< OptSpecifier > ExcludeIds) const
AddAllArgsExcept - Render all arguments matching any of the given ids and not matching any of the excluded ids.
void AddAllArgs (ArgStringList &Output, ArrayRef< OptSpecifier > Ids) const
AddAllArgs - Render all arguments matching any of the given ids.
void AddAllArgs (ArgStringList &Output, OptSpecifier Id0, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
AddAllArgs - Render all arguments matching the given ids.
void AddAllArgValues (ArgStringList &Output, OptSpecifier Id0, OptSpecifier Id1=0U, OptSpecifier Id2=0U) const
AddAllArgValues - Render the argument values of all arguments matching the given ids.
void AddAllArgsTranslated (ArgStringList &Output, OptSpecifier Id0, const char *Translation, bool Joined=false) const
AddAllArgsTranslated - Render all the arguments matching the given ids, but forced to separate args and using the provided name instead of the first option value.
void ClaimAllArgs (OptSpecifier Id0) const
ClaimAllArgs - Claim all arguments which match the given option id.
void ClaimAllArgs () const
ClaimAllArgs - Claim all arguments.
const char * MakeArgString (const Twine &Str) const
const char * GetOrMakeJoinedArgString (unsigned Index, StringRef LHS, StringRef RHS) const
Create an arg string for (LHS + RHS), reusing the string at Index if possible.
void print (raw_ostream &O) const
void dump () const
Additional Inherited Members
Public Types inherited from llvm::opt::ArgList
using arglist_type = SmallVector<Arg *, 16>
using iterator = arg_iterator<arglist_type::iterator>
using const_iterator = arg_iterator<arglist_type::const_iterator>
using reverse_iterator = arg_iterator<arglist_type::reverse_iterator>
using const_reverse_iterator
template<unsigned N>
using filtered_iterator
template<unsigned N>
using filtered_reverse_iterator
Protected Member Functions inherited from llvm::opt::ArgList
ArgList ()=default
ArgList (ArgList &&RHS)
ArgList & operator= (ArgList &&RHS)
~ArgList ()=default
Static Protected Member Functions inherited from llvm::opt::ArgList
static OptSpecifier toOptSpecifier (OptSpecifier S)
Detailed Description
DerivedArgList - An ordered collection of driver arguments, whose storage may be in another argument list.
Definition at line 435 of file ArgList.h.
Constructor & Destructor Documentation
DerivedArgList()
DerivedArgList::DerivedArgList (const InputArgList & BaseArgs)
Construct a new derived arg list from BaseArgs.
Definition at line 231 of file ArgList.cpp.
Member Function Documentation
AddFlagArg()
void llvm::opt::DerivedArgList::AddFlagArg (const Arg * BaseArg, const Option Opt) inline
AddFlagArg - Construct a new FlagArg for the given option Id and append it to the argument list.
Definition at line 469 of file ArgList.h.
References llvm::opt::ArgList::append(), and MakeFlagArg().
AddJoinedArg()
void llvm::opt::DerivedArgList::AddJoinedArg (const Arg * BaseArg, const Option Opt, StringRef Value) inline
AddJoinedArg - Construct a new Positional arg for the given option Id, with the provided Value and append it to the argument list.
Definition at line 491 of file ArgList.h.
References llvm::opt::ArgList::append(), and MakeJoinedArg().
AddPositionalArg()
void llvm::opt::DerivedArgList::AddPositionalArg (const Arg * BaseArg, const Option Opt, StringRef Value) inline
AddPositionalArg - Construct a new Positional arg for the given option Id, with the provided Value and append it to the argument list.
Definition at line 476 of file ArgList.h.
References llvm::opt::ArgList::append(), and MakePositionalArg().
AddSeparateArg()
void llvm::opt::DerivedArgList::AddSeparateArg (const Arg * BaseArg, const Option Opt, StringRef Value) inline
AddSeparateArg - Construct a new Positional arg for the given option Id, with the provided Value and append it to the argument list.
Definition at line 484 of file ArgList.h.
References llvm::opt::ArgList::append(), and MakeSeparateArg().
AddSynthesizedArg()
void DerivedArgList::AddSynthesizedArg (Arg * A)
AddSynthesizedArg - Add a argument to the list of synthesized arguments (to be freed).
Definition at line 238 of file ArgList.cpp.
References A.
getArgString()
const char * llvm::opt::DerivedArgList::getArgString (unsigned Index) const inline override virtual
getArgString - Return the input argument string at Index.
Implements llvm::opt::ArgList.
Definition at line 445 of file ArgList.h.
getBaseArgs()
const InputArgList & llvm::opt::DerivedArgList::getBaseArgs () const inline
Definition at line 453 of file ArgList.h.
getNumInputArgStrings()
unsigned llvm::opt::DerivedArgList::getNumInputArgStrings () const inline override virtual
getNumInputArgStrings - Return the number of original argument strings, which are guaranteed to be the first strings in the argument string list.
Implements llvm::opt::ArgList.
Definition at line 449 of file ArgList.h.
MakeArgString()
const char * llvm::opt::ArgList::MakeArgString (const Twine & Str) const inline
Definition at line 352 of file ArgList.h.
Referenced by MakeFlagArg(), MakeJoinedArg(), MakePositionalArg(), and MakeSeparateArg().
MakeArgStringRef()
const char * DerivedArgList::MakeArgStringRef (StringRef Str) const override virtual
Construct a constant string pointer whose lifetime will match that of the ArgList.
Implements llvm::opt::ArgList.
Definition at line 234 of file ArgList.cpp.
References llvm::opt::InputArgList::MakeArgString().
MakeFlagArg()
Arg * DerivedArgList::MakeFlagArg (const Arg * BaseArg, const Option Opt) const
MakeFlagArg - Construct a new FlagArg for the given option Id.
Definition at line 242 of file ArgList.cpp.
References llvm::opt::Option::getName(), llvm::opt::Option::getPrefix(), MakeArgString(), and llvm::opt::InputArgList::MakeIndex().
Referenced by AddFlagArg().
MakeJoinedArg()
Arg * DerivedArgList::MakeJoinedArg (const Arg * BaseArg, const Option Opt, StringRef Value) const
MakeJoinedArg - Construct a new Positional arg for the given option Id, with the provided Value.
Definition at line 267 of file ArgList.cpp.
References llvm::opt::InputArgList::getArgString(), llvm::opt::Option::getName(), llvm::opt::Option::getPrefix(), MakeArgString(), llvm::opt::InputArgList::MakeIndex(), and llvm::StringRef::size().
Referenced by AddJoinedArg().
MakePositionalArg()
Arg * DerivedArgList::MakePositionalArg (const Arg * BaseArg, const Option Opt, StringRef Value) const
MakePositionalArg - Construct a new Positional arg for the given option Id, with the provided Value.
Definition at line 249 of file ArgList.cpp.
References llvm::opt::InputArgList::getArgString(), llvm::opt::Option::getName(), llvm::opt::Option::getPrefix(), MakeArgString(), and llvm::opt::InputArgList::MakeIndex().
Referenced by AddPositionalArg().
MakeSeparateArg()
Arg * DerivedArgList::MakeSeparateArg (const Arg * BaseArg, const Option Opt, StringRef Value) const
MakeSeparateArg - Construct a new Positional arg for the given option Id, with the provided Value.
Definition at line 258 of file ArgList.cpp.
References llvm::opt::InputArgList::getArgString(), llvm::opt::Option::getName(), llvm::opt::Option::getPrefix(), MakeArgString(), and llvm::opt::InputArgList::MakeIndex().
Referenced by AddSeparateArg().
The documentation for this class was generated from the following files:
include/llvm/Option/ArgList.h
lib/Option/ArgList.cpp