LLVM: llvm::sys::ThreadLocalImpl Class Reference
llvm::sys::ThreadLocalImpl Class Reference
#include "llvm/Support/ThreadLocal.h"
Public Member Functions
ThreadLocalImpl ()
virtual ~ThreadLocalImpl ()
void setInstance (const void *d)
void * getInstance ()
void removeInstance ()
Detailed Description
Definition at line 24 of file ThreadLocal.h.
Constructor & Destructor Documentation
ThreadLocalImpl()
llvm::ThreadLocalImpl::ThreadLocalImpl ()
Definition at line 26 of file ThreadLocal.cpp.
~ThreadLocalImpl()
llvm::ThreadLocalImpl::~ThreadLocalImpl () virtual
Definition at line 27 of file ThreadLocal.cpp.
Member Function Documentation
getInstance()
void * llvm::ThreadLocalImpl::getInstance ()
Definition at line 33 of file ThreadLocal.cpp.
References data.
Referenced by llvm::sys::ThreadLocal< T >::get().
removeInstance()
void llvm::ThreadLocalImpl::removeInstance ()
Definition at line 37 of file ThreadLocal.cpp.
References setInstance().
Referenced by llvm::sys::ThreadLocal< T >::erase().
setInstance()
void llvm::ThreadLocalImpl::setInstance (const void * d)
Definition at line 28 of file ThreadLocal.cpp.
References data.
Referenced by removeInstance(), and llvm::sys::ThreadLocal< T >::set().
Member Data Documentation
align_data
ThreadLocalDataTy llvm::sys::ThreadLocalImpl::align_data
Definition at line 32 of file ThreadLocal.h.
data
char llvm::sys::ThreadLocalImpl::data[sizeof(ThreadLocalDataTy)]
Definition at line 31 of file ThreadLocal.h.
Referenced by getInstance(), and setInstance().
The documentation for this class was generated from the following files:
include/llvm/Support/ThreadLocal.h
lib/Support/ThreadLocal.cpp