LLVM: llvm::X86Subtarget Class Reference
llvm::X86Subtarget Class Reference final
#include "Target/X86/X86Subtarget.h"
Public Types
enum X86ProcFamilyEnum { Others , IntelAtom , IntelSLM }
Public Member Functions
X86Subtarget (const Triple &TT, StringRef CPU, StringRef FS, const X86TargetMachine &TM, MaybeAlign StackAlignOverride, unsigned PreferVectorWidthOverride, unsigned RequiredVectorWidth)
This constructor initializes the data members to match that of the specified triple.
const X86TargetLowering * getTargetLowering () const override
const X86InstrInfo * getInstrInfo () const override
const X86FrameLowering * getFrameLowering () const override
const X86SelectionDAGInfo * getSelectionDAGInfo () const override
const X86RegisterInfo * getRegisterInfo () const override
Align getStackAlignment () const
Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
unsigned getMaxInlineSizeThreshold () const
Returns the maximum memset / memcpy size that still makes it profitable to inline the call.
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
const CallLowering * getCallLowering () const override
Methods used by Global ISel.
InstructionSelector * getInstructionSelector () const override
const LegalizerInfo * getLegalizerInfo () const override
const RegisterBankInfo * getRegBankInfo () const override
bool is64Bit () const
Is this x86_64? (disregarding specific ABI / programming model)
bool is32Bit () const
bool is16Bit () const
bool isTarget64BitILP32 () const
Is this x86_64 with the ILP32 programming model (x32 ABI)?
bool isTarget64BitLP64 () const
Is this x86_64 with the LP64 programming model (standard AMD64, no x32)?
PICStyles::Style getPICStyle () const
void setPICStyle (PICStyles::Style Style)
bool hasX87 () const
bool hasCmpxchg8b () const
bool hasNOPL () const
bool hasCMov () const
bool hasSSE1 () const
bool hasSSE2 () const
bool hasSSE3 () const
bool hasSSSE3 () const
bool hasSSE41 () const
bool hasSSE42 () const
bool hasAVX () const
bool hasAVX2 () const
bool hasAVX512 () const
bool hasInt256 () const
bool hasSSE4A () const
bool hasMMX () const
bool has3DNow () const
bool has3DNowA () const
bool hasPOPCNT () const
bool hasAES () const
bool hasVAES () const
bool hasFXSR () const
bool hasXSAVE () const
bool hasXSAVEOPT () const
bool hasXSAVEC () const
bool hasXSAVES () const
bool hasPCLMUL () const
bool hasVPCLMULQDQ () const
bool hasGFNI () const
bool hasFMA () const
bool hasFMA4 () const
bool hasAnyFMA () const
bool hasXOP () const
bool hasTBM () const
bool hasLWP () const
bool hasMOVBE () const
bool hasRDRAND () const
bool hasF16C () const
bool hasFSGSBase () const
bool hasLZCNT () const
bool hasBMI () const
bool hasBMI2 () const
bool hasVBMI () const
bool hasVBMI2 () const
bool hasIFMA () const
bool hasRTM () const
bool hasADX () const
bool hasSHA () const
bool hasPRFCHW () const
bool hasPREFETCHWT1 () const
bool hasPrefetchW () const
bool hasSSEPrefetch () const
bool hasRDSEED () const
bool hasLAHFSAHF () const
bool hasMWAITX () const
bool hasCLZERO () const
bool hasCLDEMOTE () const
bool hasMOVDIRI () const
bool hasMOVDIR64B () const
bool hasPTWRITE () const
bool isSHLDSlow () const
bool isPMULLDSlow () const
bool isPMADDWDSlow () const
bool isUnalignedMem16Slow () const
bool isUnalignedMem32Slow () const
int getGatherOverhead () const
int getScatterOverhead () const
bool hasSSEUnalignedMem () const
bool hasCmpxchg16b () const
bool useLeaForSP () const
bool hasPOPCNTFalseDeps () const
bool hasLZCNTFalseDeps () const
bool hasFastVariableShuffle () const
bool insertVZEROUPPER () const
bool hasFastGather () const
bool hasFastScalarFSQRT () const
bool hasFastVectorFSQRT () const
bool hasFastLZCNT () const
bool hasFastSHLDRotate () const
bool hasFastBEXTR () const
bool hasFastHorizontalOps () const
bool hasFastScalarShiftMasks () const
bool hasFastVectorShiftMasks () const
bool hasMacroFusion () const
bool hasBranchFusion () const
bool hasERMSB () const
bool hasSlowDivide32 () const
bool hasSlowDivide64 () const
bool padShortFunctions () const
bool slowTwoMemOps () const
bool LEAusesAG () const
bool slowLEA () const
bool slow3OpsLEA () const
bool slowIncDec () const
bool hasCDI () const
bool hasVPOPCNTDQ () const
bool hasPFI () const
bool hasERI () const
bool hasDQI () const
bool hasBWI () const
bool hasVLX () const
bool hasPKU () const
bool hasVNNI () const
bool hasBF16 () const
bool hasVP2INTERSECT () const
bool hasBITALG () const
bool hasSHSTK () const
bool hasCLFLUSHOPT () const
bool hasCLWB () const
bool hasWBNOINVD () const
bool hasRDPID () const
bool hasWAITPKG () const
bool hasPCONFIG () const
bool hasSGX () const
bool threewayBranchProfitable () const
bool hasINVPCID () const
bool hasENQCMD () const
bool hasSERIALIZE () const
bool hasTSXLDTRK () const
bool useRetpolineIndirectCalls () const
bool useRetpolineIndirectBranches () const
bool hasAMXTILE () const
bool hasAMXBF16 () const
bool hasAMXINT8 () const
bool useRetpolineExternalThunk () const
bool useIndirectThunkCalls () const
bool useIndirectThunkBranches () const
bool preferMaskRegisters () const
bool useGLMDivSqrtCosts () const
bool useLVIControlFlowIntegrity () const
bool useLVILoadHardening () const
bool useSpeculativeExecutionSideEffectSuppression () const
unsigned getPreferVectorWidth () const
unsigned getRequiredVectorWidth () const
bool canExtendTo512DQ () const
bool canExtendTo512BW () const
bool useAVX512Regs () const
bool useBWIRegs () const
bool isXRaySupported () const override
X86ProcFamilyEnum getProcFamily () const
bool isAtom () const
TODO: to be removed later and replaced with suitable properties.
bool isSLM () const
bool useSoftFloat () const
bool useAA () const override
bool hasMFence () const
Use mfence if we have SSE2 or we're on x86-64 (even if we asked for no-sse2).
const Triple & getTargetTriple () const
bool isTargetDarwin () const
bool isTargetFreeBSD () const
bool isTargetDragonFly () const
bool isTargetSolaris () const
bool isTargetPS4 () const
bool isTargetELF () const
bool isTargetCOFF () const
bool isTargetMachO () const
bool isTargetLinux () const
bool isTargetKFreeBSD () const
bool isTargetGlibc () const
bool isTargetAndroid () const
bool isTargetNaCl () const
bool isTargetNaCl32 () const
bool isTargetNaCl64 () const
bool isTargetMCU () const
bool isTargetFuchsia () const
bool isTargetWindowsMSVC () const
bool isTargetWindowsCoreCLR () const
bool isTargetWindowsCygwin () const
bool isTargetWindowsGNU () const
bool isTargetWindowsItanium () const
bool isTargetCygMing () const
bool isOSWindows () const
bool isTargetWin64 () const
bool isTargetWin32 () const
bool isPICStyleGOT () const
bool isPICStyleRIPRel () const
bool isPICStyleStubPIC () const
bool isPositionIndependent () const
bool isCallingConvWin64 (CallingConv::ID CC) const
unsigned char classifyLocalReference (const GlobalValue *GV) const
Classify a global variable reference for the current subtarget according to how we should reference it in a non-pcrel context.
unsigned char classifyGlobalReference (const GlobalValue *GV, const Module &M) const
unsigned char classifyGlobalReference (const GlobalValue *GV) const
Classify a global variable reference for the current subtarget according to how we should reference it in a non-pcrel context.
unsigned char classifyGlobalFunctionReference (const GlobalValue *GV, const Module &M) const
Classify a global function reference for the current subtarget.
unsigned char classifyGlobalFunctionReference (const GlobalValue *GV) const
unsigned char classifyBlockAddressReference () const
Classify a blockaddress reference for the current subtarget according to how we should reference it in a non-pcrel context.
bool isLegalToCallImmediateAddr () const
Return true if the subtarget allows calls to immediate address.
bool enableIndirectBrExpand () const override
If we are using indirect thunks, we need to expand indirectbr to avoid it lowering to an actual indirect jump.
bool enableMachineScheduler () const override
Enable the MachineScheduler pass for all X86 subtargets.
bool enableEarlyIfConversion () const override
void getPostRAMutations (std::vector< std::unique_ptr< ScheduleDAGMutation > > &Mutations) const override
AntiDepBreakMode getAntiDepBreakMode () const override
bool enableAdvancedRASplitCost () const override
Protected Types
enum X86SSEEnum {
NoSSE , SSE1 , SSE2 , SSE3 ,
SSSE3 , SSE41 , SSE42 , AVX ,
AVX2 , AVX512F
}
enum X863DNowEnum { NoThreeDNow , MMX , ThreeDNow , ThreeDNowA }
Protected Attributes
X86ProcFamilyEnum X86ProcFamily = Others
X86 processor family: Intel Atom, and others.
PICStyles::Style PICStyle
Which PIC style to use.
const TargetMachine & TM
X86SSEEnum X86SSELevel = NoSSE
SSE1, SSE2, SSE3, SSSE3, SSE41, SSE42, or none supported.
X863DNowEnum X863DNowLevel = NoThreeDNow
MMX, 3DNow, 3DNow Athlon, or none supported.
bool HasX87 = false
True if the processor supports X87 instructions.
bool HasCmpxchg8b = false
True if the processor supports CMPXCHG8B.
bool HasNOPL = false
True if this processor has NOPL instruction (generally pentium pro+).
bool HasCMov = false
True if this processor has conditional move instructions (generally pentium pro+).
bool HasX86_64 = false
True if the processor supports X86-64 instructions.
bool HasPOPCNT = false
True if the processor supports POPCNT.
bool HasSSE4A = false
True if the processor supports SSE4A instructions.
bool HasAES = false
Target has AES instructions.
bool HasVAES = false
bool HasFXSR = false
Target has FXSAVE/FXRESTOR instructions.
bool HasXSAVE = false
Target has XSAVE instructions.
bool HasXSAVEOPT = false
Target has XSAVEOPT instructions.
bool HasXSAVEC = false
Target has XSAVEC instructions.
bool HasXSAVES = false
Target has XSAVES instructions.
bool HasPCLMUL = false
Target has carry-less multiplication.
bool HasVPCLMULQDQ = false
bool HasGFNI = false
Target has Galois Field Arithmetic instructions.
bool HasFMA = false
Target has 3-operand fused multiply-add.
bool HasFMA4 = false
Target has 4-operand fused multiply-add.
bool HasXOP = false
Target has XOP instructions.
bool HasTBM = false
Target has TBM instructions.
bool HasLWP = false
Target has LWP instructions.
bool HasMOVBE = false
True if the processor has the MOVBE instruction.
bool HasRDRAND = false
True if the processor has the RDRAND instruction.
bool HasF16C = false
Processor has 16-bit floating point conversion instructions.
bool HasFSGSBase = false
Processor has FS/GS base insturctions.
bool HasLZCNT = false
Processor has LZCNT instruction.
bool HasBMI = false
Processor has BMI1 instructions.
bool HasBMI2 = false
Processor has BMI2 instructions.
bool HasVBMI = false
Processor has VBMI instructions.
bool HasVBMI2 = false
Processor has VBMI2 instructions.
bool HasIFMA = false
Processor has Integer Fused Multiply Add.
bool HasRTM = false
Processor has RTM instructions.
bool HasADX = false
Processor has ADX instructions.
bool HasSHA = false
Processor has SHA instructions.
bool HasPRFCHW = false
Processor has PRFCHW instructions.
bool HasRDSEED = false
Processor has RDSEED instructions.
bool HasLAHFSAHF = false
Processor has LAHF/SAHF instructions.
bool HasMWAITX = false
Processor has MONITORX/MWAITX instructions.
bool HasCLZERO = false
Processor has Cache Line Zero instruction.
bool HasCLDEMOTE = false
Processor has Cache Line Demote instruction.
bool HasMOVDIRI = false
Processor has MOVDIRI instruction (direct store integer).
bool HasMOVDIR64B = false
Processor has MOVDIR64B instruction (direct store 64 bytes).
bool HasPTWRITE = false
Processor has ptwrite instruction.
bool HasPREFETCHWT1 = false
Processor has Prefetch with intent to Write instruction.
bool IsSHLDSlow = false
True if SHLD instructions are slow.
bool IsPMULLDSlow = false
True if the PMULLD instruction is slow compared to PMULLW/PMULHW and.
bool IsPMADDWDSlow = false
True if the PMADDWD instruction is slow compared to PMULLD.
bool IsUAMem16Slow = false
True if unaligned memory accesses of 16-bytes are slow.
bool IsUAMem32Slow = false
True if unaligned memory accesses of 32-bytes are slow.
bool HasSSEUnalignedMem = false
True if SSE operations can have unaligned memory operands.
bool HasCmpxchg16b = false
True if this processor has the CMPXCHG16B instruction; this is true for most x86-64 chips, but not the first AMD chips.
bool UseLeaForSP = false
True if the LEA instruction should be used for adjusting the stack pointer.
bool HasPOPCNTFalseDeps = false
True if POPCNT instruction has a false dependency on the destination register.
bool HasLZCNTFalseDeps = false
True if LZCNT/TZCNT instructions have a false dependency on the destination register.
bool HasFastVariableShuffle = false
True if its preferable to combine to a single shuffle using a variable mask over multiple fixed shuffles.
bool InsertVZEROUPPER = false
True if vzeroupper instructions should be inserted after code that uses ymm or zmm registers.
bool HasFast7ByteNOP = false
True if there is no performance penalty for writing NOPs with up to 7 bytes.
bool HasFast11ByteNOP = false
True if there is no performance penalty for writing NOPs with up to 11 bytes.
bool HasFast15ByteNOP = false
True if there is no performance penalty for writing NOPs with up to 15 bytes.
bool HasFastGather = false
True if gather is reasonably fast.
bool HasFastScalarFSQRT = false
True if hardware SQRTSS instruction is at least as fast (latency) as RSQRTSS followed by a Newton-Raphson iteration.
bool HasFastVectorFSQRT = false
True if hardware SQRTPS/VSQRTPS instructions are at least as fast (throughput) as RSQRTPS/VRSQRTPS followed by a Newton-Raphson iteration.
bool HasSlowDivide32 = false
True if 8-bit divisions are significantly faster than 32-bit divisions and should be used when possible.
bool HasSlowDivide64 = false
True if 32-bit divides are significantly faster than 64-bit divisions and should be used when possible.
bool HasFastLZCNT = false
True if LZCNT instruction is fast.
bool HasFastSHLDRotate = false
True if SHLD based rotate is fast.
bool HasMacroFusion = false
True if the processor supports macrofusion.
bool HasBranchFusion = false
True if the processor supports branch fusion.
bool HasERMSB = false
True if the processor has enhanced REP MOVSB/STOSB.
bool PadShortFunctions = false
True if the short functions should be padded to prevent a stall when returning too early.
bool SlowTwoMemOps = false
True if two memory operand instructions should use a temporary register instead.
bool LEAUsesAG = false
True if the LEA instruction inputs have to be ready at address generation (AG) time.
bool SlowLEA = false
True if the LEA instruction with certain arguments is slow.
bool Slow3OpsLEA = false
True if the LEA instruction has all three source operands: base, index, and offset or if the LEA instruction uses base and index registers where the base is EBP, RBP,or R13.
bool SlowIncDec = false
True if INC and DEC instructions are slow when writing to flags.
bool HasPFI = false
Processor has AVX-512 PreFetch Instructions.
bool HasERI = false
Processor has AVX-512 Exponential and Reciprocal Instructions.
bool HasCDI = false
Processor has AVX-512 Conflict Detection Instructions.
bool HasVPOPCNTDQ = false
Processor has AVX-512 population count Instructions.
bool HasDQI = false
Processor has AVX-512 Doubleword and Quadword instructions.
bool HasBWI = false
Processor has AVX-512 Byte and Word instructions.
bool HasVLX = false
Processor has AVX-512 Vector Length eXtenstions.
bool HasPKU = false
Processor has PKU extenstions.
bool HasVNNI = false
Processor has AVX-512 Vector Neural Network Instructions.
bool HasBF16 = false
Processor has AVX-512 bfloat16 floating-point extensions.
bool HasENQCMD = false
Processor supports ENQCMD instructions.
bool HasBITALG = false
Processor has AVX-512 Bit Algorithms instructions.
bool HasVP2INTERSECT = false
Processor has AVX-512 vp2intersect instructions.
bool DeprecatedHasMPX = false
Deprecated flag for MPX instructions.
bool HasSHSTK = false
Processor supports CET SHSTK - Control-Flow Enforcement Technology using Shadow Stack.
bool HasINVPCID = false
Processor supports Invalidate Process-Context Identifier.
bool HasSGX = false
Processor has Software Guard Extensions.
bool HasCLFLUSHOPT = false
Processor supports Flush Cache Line instruction.
bool HasCLWB = false
Processor supports Cache Line Write Back instruction.
bool HasWBNOINVD = false
Processor supports Write Back No Invalidate instruction.
bool HasRDPID = false
Processor support RDPID instruction.
bool HasWAITPKG = false
Processor supports WaitPKG instructions.
bool HasPCONFIG = false
Processor supports PCONFIG instruction.
bool HasSERIALIZE = false
Processor supports SERIALIZE instruction.
bool HasTSXLDTRK = false
Processor supports TSXLDTRK instruction.
bool HasAMXTILE = false
Processor has AMX support.
bool HasAMXBF16 = false
bool HasAMXINT8 = false
bool HasFastBEXTR = false
Processor has a single uop BEXTR implementation.
bool HasFastHorizontalOps = false
Try harder to combine to horizontal vector ops if they are fast.
bool HasFastScalarShiftMasks = false
Prefer a left/right scalar logical shifts pair over a shift+and pair.
bool HasFastVectorShiftMasks = false
Prefer a left/right vector logical shifts pair over a shift+and pair.
bool UseRetpolineIndirectCalls = false
Use a retpoline thunk rather than indirect calls to block speculative execution.
bool UseRetpolineIndirectBranches = false
Use a retpoline thunk or remove any indirect branch to block speculative execution.
bool DeprecatedUseRetpoline = false
Deprecated flag, query UseRetpolineIndirectCalls and UseRetpolineIndirectBranches instead.
bool UseRetpolineExternalThunk = false
When using a retpoline thunk, call an externally provided thunk rather than emitting one inside the compiler.
bool UseLVIControlFlowIntegrity = false
Prevent generation of indirect call/branch instructions from memory, and force all indirect call/branch instructions from a register to be preceded by an LFENCE.
bool UseSpeculativeExecutionSideEffectSuppression = false
Enable Speculative Execution Side Effect Suppression.
bool UseLVILoadHardening = false
Insert LFENCE instructions to prevent data speculatively injected into loads from being used maliciously.
bool UseSoftFloat = false
Use software floating point for code generation.
bool UseAA = false
Use alias analysis during code generation.
Align stackAlignment = Align(4)
The minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function.
unsigned MaxInlineSizeThreshold = 128
Max.
bool Prefer128Bit = false
Indicates target prefers 128 bit instructions.
bool Prefer256Bit = false
Indicates target prefers 256 bit instructions.
bool PreferMaskRegisters = false
Indicates target prefers AVX512 mask registers.
bool ThreewayBranchProfitable = false
Threeway branch is profitable in this subtarget.
bool UseGLMDivSqrtCosts = false
Use Goldmont specific floating point div/sqrt costs.
Triple TargetTriple
What processor and OS we're targeting.
std::unique_ptr< CallLowering > CallLoweringInfo
GlobalISel related APIs.
std::unique_ptr< LegalizerInfo > Legalizer
std::unique_ptr< RegisterBankInfo > RegBankInfo
std::unique_ptr< InstructionSelector > InstSelector
Detailed Description
Definition at line 52 of file X86Subtarget.h.
Member Enumeration Documentation
X863DNowEnum
enum llvm::X86Subtarget::X863DNowEnum protected
Enumerator
NoThreeDNow
MMX
ThreeDNow
ThreeDNowA
Definition at line 67 of file X86Subtarget.h.
X86ProcFamilyEnum
enum llvm::X86Subtarget::X86ProcFamilyEnum
Enumerator
Others
IntelAtom
IntelSLM
Definition at line 56 of file X86Subtarget.h.
X86SSEEnum
enum llvm::X86Subtarget::X86SSEEnum protected
Enumerator
NoSSE
SSE1
SSE2
SSE3
SSSE3
SSE41
SSE42
AVX
AVX2
AVX512F
Definition at line 63 of file X86Subtarget.h.
Constructor & Destructor Documentation
X86Subtarget()
X86Subtarget::X86Subtarget (const Triple & TT, StringRef CPU, StringRef FS, const X86TargetMachine & TM, MaybeAlign StackAlignOverride, unsigned PreferVectorWidthOverride, unsigned RequiredVectorWidth)
This constructor initializes the data members to match that of the specified triple.
Definition at line 323 of file X86Subtarget.cpp.
References CallLoweringInfo, llvm::createX86InstructionSelector(), getRegisterInfo(), getTargetLowering(), llvm::PICStyles::GOT, InstSelector, is64Bit(), isPositionIndependent(), isTargetCOFF(), isTargetDarwin(), isTargetELF(), llvm::PICStyles::None, RegBankInfo, llvm::PICStyles::RIPRel, setPICStyle(), llvm::PICStyles::StubPIC, and TM.
Member Function Documentation
canExtendTo512BW()
bool llvm::X86Subtarget::canExtendTo512BW () const inline
Definition at line 779 of file X86Subtarget.h.
References canExtendTo512DQ(), and hasBWI().
Referenced by lower1BitShuffle(), LowerMUL(), LowerMULH(), LowerScalarVariableShift(), and LowerShift().
canExtendTo512DQ()
bool llvm::X86Subtarget::canExtendTo512DQ () const inline
Definition at line 776 of file X86Subtarget.h.
References getPreferVectorWidth(), hasAVX512(), and hasVLX().
Referenced by canExtendTo512BW(), lower1BitShuffle(), LowerScalarVariableShift(), LowerShift(), LowerSIGN_EXTEND_Mask(), LowerTruncateVecI1(), LowerVectorCTLZ(), LowerVectorCTLZ_AVX512CDI(), LowerVectorCTPOP(), LowerZERO_EXTEND_Mask(), and useAVX512Regs().
classifyBlockAddressReference()
unsigned char X86Subtarget::classifyBlockAddressReference () const
Classify a blockaddress reference for the current subtarget according to how we should reference it in a non-pcrel context.
Definition at line 57 of file X86Subtarget.cpp.
References classifyLocalReference().
classifyGlobalFunctionReference() [1/2]
unsigned char X86Subtarget::classifyGlobalFunctionReference (const GlobalValue * GV) const
Definition at line 173 of file X86Subtarget.cpp.
References classifyGlobalFunctionReference(), and llvm::GlobalValue::getParent().
classifyGlobalFunctionReference() [2/2]
unsigned char X86Subtarget::classifyGlobalFunctionReference (const GlobalValue * GV, const Module & M) const
Classify a global function reference for the current subtarget.
Definition at line 178 of file X86Subtarget.cpp.
References F, llvm::GlobalValue::hasDLLImportStorageClass(), is64Bit(), isTargetCOFF(), isTargetELF(), llvm::X86II::MO_COFFSTUB, llvm::X86II::MO_DLLIMPORT, llvm::X86II::MO_GOTPCREL, llvm::X86II::MO_NO_FLAG, llvm::X86II::MO_PLT, llvm::TargetMachine::shouldAssumeDSOLocal(), TM, and llvm::CallingConv::X86_RegCall.
Referenced by classifyGlobalFunctionReference().
classifyGlobalReference() [1/2]
unsigned char X86Subtarget::classifyGlobalReference (const GlobalValue * GV) const
Classify a global variable reference for the current subtarget according to how we should reference it in a non-pcrel context.
Definition at line 64 of file X86Subtarget.cpp.
References classifyGlobalReference(), and llvm::GlobalValue::getParent().
classifyGlobalReference() [2/2]
unsigned char X86Subtarget::classifyGlobalReference (const GlobalValue * GV, const Module & M) const
Definition at line 123 of file X86Subtarget.cpp.
References classifyLocalReference(), llvm::GlobalValue::getAbsoluteSymbolRange(), llvm::TargetMachine::getCodeModel(), llvm::GlobalValue::hasDLLImportStorageClass(), is64Bit(), isOSWindows(), isPositionIndependent(), isTargetCOFF(), isTargetDarwin(), isTargetELF(), llvm::CodeModel::Large, llvm::X86II::MO_ABS8, llvm::X86II::MO_COFFSTUB, llvm::X86II::MO_DARWIN_NONLAZY, llvm::X86II::MO_DARWIN_NONLAZY_PIC_BASE, llvm::X86II::MO_DLLIMPORT, llvm::X86II::MO_GOT, llvm::X86II::MO_GOTPCREL, llvm::X86II::MO_NO_FLAG, llvm::TargetMachine::shouldAssumeDSOLocal(), and TM.
Referenced by classifyGlobalReference(), llvm::X86TargetLowering::isLegalAddressingMode(), and llvm::X86TargetLowering::LowerAsmOperandForConstraint().
classifyLocalReference()
unsigned char X86Subtarget::classifyLocalReference (const GlobalValue * GV) const
Classify a global variable reference for the current subtarget according to how we should reference it in a non-pcrel context.
Definition at line 69 of file X86Subtarget.cpp.
References llvm::TargetMachine::getCodeModel(), llvm::GlobalValue::hasCommonLinkage(), is64Bit(), llvm::GlobalValue::isDeclarationForLinker(), isPositionIndependent(), isTargetCOFF(), isTargetDarwin(), isTargetELF(), llvm::CodeModel::Kernel, llvm::CodeModel::Large, llvm_unreachable, llvm::CodeModel::Medium, llvm::X86II::MO_DARWIN_NONLAZY_PIC_BASE, llvm::X86II::MO_GOTOFF, llvm::X86II::MO_NO_FLAG, llvm::X86II::MO_PIC_BASE_OFFSET, llvm::CodeModel::Small, llvm::CodeModel::Tiny, and TM.
Referenced by classifyBlockAddressReference(), and classifyGlobalReference().
enableAdvancedRASplitCost()
bool llvm::X86Subtarget::enableAdvancedRASplitCost () const inline override
Definition at line 930 of file X86Subtarget.h.
enableEarlyIfConversion()
bool X86Subtarget::enableEarlyIfConversion () const override
Definition at line 375 of file X86Subtarget.cpp.
References hasCMov(), and X86EarlyIfConv.
enableIndirectBrExpand()
bool llvm::X86Subtarget::enableIndirectBrExpand () const inline override
If we are using indirect thunks, we need to expand indirectbr to avoid it lowering to an actual indirect jump.
Definition at line 914 of file X86Subtarget.h.
References useIndirectThunkBranches().
enableMachineScheduler()
bool llvm::X86Subtarget::enableMachineScheduler () const inline override
Enable the MachineScheduler pass for all X86 subtargets.
Definition at line 919 of file X86Subtarget.h.
getAntiDepBreakMode()
AntiDepBreakMode llvm::X86Subtarget::getAntiDepBreakMode () const inline override
Definition at line 926 of file X86Subtarget.h.
getCallLowering()
const CallLowering * X86Subtarget::getCallLowering () const override
Methods used by Global ISel.
Definition at line 359 of file X86Subtarget.cpp.
References CallLoweringInfo.
getFrameLowering()
const X86FrameLowering * llvm::X86Subtarget::getFrameLowering () const inline override
Definition at line 540 of file X86Subtarget.h.
Referenced by emitLockedStackOp(), ExpandMOVImmSExti8(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::X86TargetLowering::getRegisterByName(), llvm::X86InstrInfo::isFunctionSafeToOutlineFrom(), llvm::X86InstrInfo::loadRegFromStackSlot(), and llvm::X86InstrInfo::storeRegToStackSlot().
getGatherOverhead()
int llvm::X86Subtarget::getGatherOverhead () const inline
Definition at line 686 of file X86Subtarget.h.
getInstrInfo()
const X86InstrInfo * llvm::X86Subtarget::getInstrInfo () const inline override
Definition at line 538 of file X86Subtarget.h.
Referenced by llvm::X86TargetLowering::EmitInstrWithCustomInserter(), getRegisterInfo(), llvm::X86CallLowering::lowerCall(), llvm::X86AsmPrinter::runOnMachineFunction(), and llvm::X86LegalizerInfo::X86LegalizerInfo().
getInstructionSelector()
InstructionSelector * X86Subtarget::getInstructionSelector () const override
Definition at line 363 of file X86Subtarget.cpp.
References InstSelector.
getLegalizerInfo()
const LegalizerInfo * X86Subtarget::getLegalizerInfo () const override
Definition at line 367 of file X86Subtarget.cpp.
getMaxInlineSizeThreshold()
unsigned llvm::X86Subtarget::getMaxInlineSizeThreshold () const inline
Returns the maximum memset / memcpy size that still makes it profitable to inline the call.
Definition at line 559 of file X86Subtarget.h.
References MaxInlineSizeThreshold.
Referenced by emitConstantSizeRepmov(), and llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset().
getPICStyle()
PICStyles::Style llvm::X86Subtarget::getPICStyle () const inline
Definition at line 603 of file X86Subtarget.h.
References PICStyle.
getPostRAMutations()
void X86Subtarget::getPostRAMutations (std::vector< std::unique_ptr< ScheduleDAGMutation > > & Mutations) const override
Definition at line 379 of file X86Subtarget.cpp.
References llvm::createX86MacroFusionDAGMutation().
getPreferVectorWidth()
unsigned llvm::X86Subtarget::getPreferVectorWidth () const inline
Definition at line 769 of file X86Subtarget.h.
Referenced by canExtendTo512DQ(), llvm::X86TargetLowering::canMergeStoresTo(), llvm::X86TTIImpl::enableMemCmpExpansion(), llvm::X86TargetLowering::getOptimalMemOpType(), and llvm::X86TTIImpl::getRegisterBitWidth().
getProcFamily()
X86ProcFamilyEnum llvm::X86Subtarget::getProcFamily () const inline
Definition at line 795 of file X86Subtarget.h.
References X86ProcFamily.
getRegBankInfo()
const RegisterBankInfo * X86Subtarget::getRegBankInfo () const override
Definition at line 371 of file X86Subtarget.cpp.
References RegBankInfo.
getRegisterInfo()
const X86RegisterInfo * llvm::X86Subtarget::getRegisterInfo () const inline override
Definition at line 548 of file X86Subtarget.h.
References getInstrInfo(), and llvm::X86InstrInfo::getRegisterInfo().
Referenced by llvm::X86TargetLowering::EmitInstrWithCustomInserter(), expandXorFP(), getBroadcastOpcode(), getLoadStoreRegOpcode(), llvm::X86TargetLowering::getRegisterByName(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::X86CallLowering::lowerCall(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86AsmPrinter::runOnMachineFunction(), X86Subtarget(), and llvm::X86TargetLowering::X86TargetLowering().
getRequiredVectorWidth()
unsigned llvm::X86Subtarget::getRequiredVectorWidth () const inline
Definition at line 770 of file X86Subtarget.h.
getScatterOverhead()
int llvm::X86Subtarget::getScatterOverhead () const inline
Definition at line 687 of file X86Subtarget.h.
getSelectionDAGInfo()
const X86SelectionDAGInfo * llvm::X86Subtarget::getSelectionDAGInfo () const inline override
Definition at line 544 of file X86Subtarget.h.
getStackAlignment()
Align llvm::X86Subtarget::getStackAlignment () const inline
Returns the minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function for this subtarget.
Definition at line 555 of file X86Subtarget.h.
References stackAlignment.
getTargetLowering()
const X86TargetLowering * llvm::X86Subtarget::getTargetLowering () const inline override
Definition at line 534 of file X86Subtarget.h.
Referenced by combineConcatVectorOps(), combineOrCmpEqZeroToCtlzSrl(), combineSIntToFP(), llvm::X86FrameLowering::emitPrologue(), llvm::X86FrameLowering::emitSPUpdate(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCallPreservedMask(), and X86Subtarget().
getTargetTriple()
const Triple & llvm::X86Subtarget::getTargetTriple () const inline
Definition at line 808 of file X86Subtarget.h.
References TargetTriple.
Referenced by computeBytesPoppedByCalleeForSRet(), llvm::X86TargetLowering::getIRStackGuard(), llvm::X86TargetLowering::getSafeStackPointerLocation(), llvm::X86TargetLowering::getSDagStackGuard(), llvm::X86TargetLowering::getSSPStackGuardCheck(), llvm::X86TargetLowering::insertSSPDeclarations(), llvm::X86TargetLowering::useStackGuardXorFP(), and llvm::X86TargetLowering::X86TargetLowering().
has3DNow()
bool llvm::X86Subtarget::has3DNow () const inline
Definition at line 624 of file X86Subtarget.h.
References ThreeDNow, and X863DNowLevel.
Referenced by hasPrefetchW(), hasSSEPrefetch(), and llvm::X86TargetLowering::X86TargetLowering().
has3DNowA()
bool llvm::X86Subtarget::has3DNowA () const inline
Definition at line 625 of file X86Subtarget.h.
References ThreeDNowA, and X863DNowLevel.
hasADX()
bool llvm::X86Subtarget::hasADX () const inline
Definition at line 656 of file X86Subtarget.h.
References HasADX.
hasAES()
bool llvm::X86Subtarget::hasAES () const inline
Definition at line 627 of file X86Subtarget.h.
References HasAES.
hasAMXBF16()
bool llvm::X86Subtarget::hasAMXBF16 () const inline
Definition at line 747 of file X86Subtarget.h.
References HasAMXBF16.
hasAMXINT8()
bool llvm::X86Subtarget::hasAMXINT8 () const inline
Definition at line 748 of file X86Subtarget.h.
References HasAMXINT8.
hasAMXTILE()
bool llvm::X86Subtarget::hasAMXTILE () const inline
Definition at line 746 of file X86Subtarget.h.
References HasAMXTILE.
hasAnyFMA()
bool llvm::X86Subtarget::hasAnyFMA () const inline
Definition at line 641 of file X86Subtarget.h.
References hasFMA(), and hasFMA4().
Referenced by combineFMA(), combineFneg(), combineShuffleToFMAddSub(), llvm::X86TargetLowering::getNegatedExpression(), isFMAddSubOrFMSubAdd(), llvm::X86TargetLowering::isFMAFasterThanFMulAndFAdd(), and llvm::X86TargetLowering::X86TargetLowering().
hasAVX()
bool llvm::X86Subtarget::hasAVX () const inline
Definition at line 618 of file X86Subtarget.h.
References AVX, and X86SSELevel.
Referenced by llvm::X86InstrInfo::breakPartialRegDependency(), combineBitcastvxi1(), combineConcatVectorOps(), combineConcatVectors(), combineExtInVec(), combineExtractSubvector(), combineFaddFsub(), combineHorizontalPredicateResult(), combineSelect(), combineVectorSizedSetCCEquality(), combineX86ShuffleChain(), llvm::X86InstrInfo::copyPhysReg(), CopyToFromAsymmetricReg(), createVariablePermute(), EltsFromConsecutiveLoads(), llvm::X86TTIImpl::enableMemCmpExpansion(), llvm::X86InstrInfo::expandPostRAPseudo(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticReductionCost(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::X86TTIImpl::getCastInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), getLoadStoreRegOpcode(), llvm::X86TTIImpl::getMaxInterleaveFactor(), llvm::X86TTIImpl::getMinMaxCost(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TTIImpl::getRegisterBitWidth(), llvm::X86TTIImpl::getShuffleCost(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), llvm::X86TTIImpl::isLegalMaskedLoad(), llvm::X86TTIImpl::isLegalNTStore(), LowerANY_EXTEND(), lowerBuildVectorAsBroadcast(), LowerEXTEND_VECTOR_INREG(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), LowerToHorizontalOp(), lowerUINT_TO_FP_vXi32(), lowerV2F64Shuffle(), lowerV4F32Shuffle(), LowerVectorAllZero(), LowerVSETCC(), LowerVSETCCWithSUBUS(), LowerZERO_EXTEND(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), llvm::X86TargetLowering::reduceSelectOfFPConstantLoads(), useVectorCast(), X86ChooseCmpOpcode(), and llvm::X86TargetLowering::X86TargetLowering().
hasAVX2()
bool llvm::X86Subtarget::hasAVX2 () const inline
Definition at line 619 of file X86Subtarget.h.
References AVX2, and X86SSELevel.
Referenced by combineConcatVectorOps(), combineExtractSubvector(), combineSelect(), combineShuffleOfConcatUndef(), combineTargetShuffle(), combineToExtendBoolVectorInReg(), combineVectorTruncation(), combineVSelectToBLENDV(), combineX86ShuffleChain(), convertShiftLeftToScale(), EltsFromConsecutiveLoads(), foldVectorXorShiftIntoCmp(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticReductionCost(), llvm::X86TTIImpl::getCastInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::X86InstrInfo::getExecutionDomain(), llvm::X86InstrInfo::getExecutionDomainCustom(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getMinMaxCost(), llvm::X86TTIImpl::getShuffleCost(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), hasInt256(), isHorizontalBinOp(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalNTLoad(), llvm::X86TargetLowering::isVectorClearMaskLegal(), llvm::X86TargetLowering::isVectorShiftByScalarCheap(), lower256BitShuffle(), lowerBuildVectorAsBroadcast(), LowerMGATHER(), LowerRotate(), lowerShuffleAsBlend(), lowerShuffleAsBroadcast(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsLanePermuteAndShuffle(), lowerShuffleAsRepeatedMaskAndLanePermute(), lowerShuffleAsTruncBroadcast(), lowerShuffleWithPSHUFB(), lowerShuffleWithUndefHalf(), LowerToHorizontalOp(), lowerV16I16Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV2X128Shuffle(), lowerV32I8Shuffle(), lowerV4F32Shuffle(), lowerV4F64Shuffle(), lowerV4I32Shuffle(), lowerV4I64Shuffle(), lowerV8F32Shuffle(), lowerV8I32Shuffle(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchUnaryPermuteShuffle(), llvm::X86InstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomainCustom(), llvm::X86TargetLowering::shouldProduceAndByConstByHoistingConstFromShiftsLHSOfAnd(), and SplitOpsAndApply().
hasAVX512()
bool llvm::X86Subtarget::hasAVX512 () const inline
Definition at line 620 of file X86Subtarget.h.
References AVX512F, and X86SSELevel.
Referenced by canExtendTo512DQ(), canonicalizeBitSelect(), combineBitcast(), combineBitcastvxi1(), combineCastedMaskArithmetic(), combineCompareEqual(), combineExtSetcc(), combineLoad(), combineMaskedLoad(), combineSelect(), combineSetCC(), combineStore(), combineToExtendBoolVectorInReg(), combineTruncateWithSat(), combineVectorPack(), combineVectorSignBitsTruncation(), combineX86ShuffleChain(), llvm::X86TargetLowering::convertSelectOfConstantsToMath(), convertShiftLeftToScale(), CopyToFromAsymmetricReg(), EmitAVX512Test(), llvm::X86TTIImpl::enableMemCmpExpansion(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticReductionCost(), getBroadcastOpcode(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::X86TTIImpl::getCastInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), llvm::X86TTIImpl::getIntrinsicInstrCost(), llvm::X86RegisterInfo::getLargestLegalSuperClass(), getLoadStoreRegOpcode(), llvm::X86TTIImpl::getMaskedMemoryOpCost(), llvm::X86TTIImpl::getMinMaxCost(), llvm::X86TTIImpl::getNumberOfRegisters(), llvm::X86TargetLowering::getNumRegistersForCallingConv(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getPreferredVectorAction(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TTIImpl::getRegisterBitWidth(), llvm::X86TargetLowering::getRegisterTypeForCallingConv(), llvm::X86RegisterInfo::getReservedRegs(), llvm::X86TargetLowering::getSetCCResultType(), llvm::X86TTIImpl::getShuffleCost(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), llvm::X86TargetLowering::getVectorTypeBreakdownForCallingConv(), llvm::X86TTIImpl::isLegalMaskedExpandLoad(), llvm::X86TTIImpl::isLegalMaskedGather(), llvm::X86TTIImpl::isLegalMaskedScatter(), llvm::X86TargetLowering::isLoadBitCastBeneficial(), lower1BitShuffle(), lower512BitShuffle(), LowerBITCAST(), LowerEXTEND_VECTOR_INREG(), LowerLoad(), LowerMGATHER(), LowerMLOAD(), LowerMSCATTER(), LowerMSTORE(), LowerMULH(), LowerRotate(), LowerShift(), lowerShuffleAsBitRotate(), lowerShuffleWithUndefHalf(), LowerStore(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), lowerV8F32Shuffle(), lowerV8I32Shuffle(), LowerVSETCC(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchShuffleAsBitRotate(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86InstrInfo::setExecutionDomain(), SupportedVectorShiftWithImm(), SupportedVectorVarShift(), useAVX512Regs(), useVectorCast(), X86ChooseCmpOpcode(), and llvm::X86TargetLowering::X86TargetLowering().
hasBF16()
bool llvm::X86Subtarget::hasBF16 () const inline
Definition at line 726 of file X86Subtarget.h.
References HasBF16.
hasBITALG()
bool llvm::X86Subtarget::hasBITALG () const inline
Definition at line 728 of file X86Subtarget.h.
References HasBITALG.
Referenced by llvm::X86TargetLowering::X86TargetLowering().
hasBMI()
bool llvm::X86Subtarget::hasBMI () const inline
Definition at line 650 of file X86Subtarget.h.
References HasBMI.
Referenced by foldMaskedShiftToBEXTR(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), llvm::X86TargetLowering::hasAndNotCompare(), llvm::X86TargetLowering::isCheapToSpeculateCttz(), and llvm::X86TargetLowering::X86TargetLowering().
hasBMI2()
bool llvm::X86Subtarget::hasBMI2 () const inline
Definition at line 651 of file X86Subtarget.h.
References HasBMI2.
Referenced by hasBZHI().
hasBranchFusion()
bool llvm::X86Subtarget::hasBranchFusion () const inline
Definition at line 707 of file X86Subtarget.h.
References HasBranchFusion.
Referenced by llvm::X86TTIImpl::canMacroFuseCmp().
hasBWI()
bool llvm::X86Subtarget::hasBWI () const inline
Definition at line 722 of file X86Subtarget.h.
References HasBWI.
Referenced by llvm::X86FrameLowering::assignCalleeSavedSpillSlots(), canExtendTo512BW(), combineBitcast(), combineBitcastvxi1(), combineMulToPMADDWD(), combineScalarAndWithMaskSetcc(), combineSelect(), combineSetCC(), combineStore(), combineTruncateWithSat(), combineVectorSizedSetCCEquality(), combineX86ShuffleChain(), llvm::X86InstrInfo::copyPhysReg(), CopyToFromAsymmetricReg(), createVariablePermute(), EmitAVX512Test(), ExtractBitFromMaskVector(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getCastInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getInterleavedMemoryOpCost(), getLoadStoreRegOpcode(), getMaskNode(), llvm::X86TTIImpl::getMinMaxCost(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getPreferredVectorAction(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TargetLowering::getSetCCResultType(), llvm::X86TTIImpl::getShuffleCost(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), getv64i1Argument(), llvm::X86TargetLowering::getVectorTypeBreakdownForCallingConv(), getZeroVector(), handleMaskRegisterForCallingConv(), llvm::X86TTIImpl::isLegalMaskedLoad(), llvm::X86TargetLowering::isVectorShiftByScalarCheap(), lower1BitShuffle(), lower512BitShuffle(), LowerABS(), LowerAVXExtend(), LowerBITCAST(), LowerBITREVERSE(), LowerMLOAD(), LowerMSTORE(), LowerMUL(), LowerMULH(), LowerScalarImmediateShift(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleWithPSHUFB(), lowerShuffleWithVPMOV(), LowerSIGN_EXTEND(), LowerSIGN_EXTEND_Mask(), LowerStore(), LowerTruncateVecI1(), lowerV16I16Shuffle(), lowerV16I32Shuffle(), lowerV32I16Shuffle(), lowerV64I8Shuffle(), LowerVectorCTLZ(), LowerVectorCTPOP(), LowerVSETCC(), LowerZERO_EXTEND_Mask(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchShuffleAsShift(), matchShuffleAsVTRUNC(), matchUnaryPermuteShuffle(), Passv64i1ArgInRegs(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), SupportedVectorShiftWithImm(), SupportedVectorVarShift(), useBWIRegs(), and llvm::X86TargetLowering::X86TargetLowering().
hasCDI()
bool llvm::X86Subtarget::hasCDI () const inline
Definition at line 717 of file X86Subtarget.h.
References HasCDI.
Referenced by llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), lowerBuildVectorAsBroadcast(), LowerVectorCTLZ(), and llvm::X86TargetLowering::X86TargetLowering().
hasCLDEMOTE()
bool llvm::X86Subtarget::hasCLDEMOTE () const inline
Definition at line 677 of file X86Subtarget.h.
References HasCLDEMOTE.
hasCLFLUSHOPT()
bool llvm::X86Subtarget::hasCLFLUSHOPT () const inline
Definition at line 730 of file X86Subtarget.h.
References HasCLFLUSHOPT.
hasCLWB()
bool llvm::X86Subtarget::hasCLWB () const inline
Definition at line 731 of file X86Subtarget.h.
References HasCLWB.
hasCLZERO()
bool llvm::X86Subtarget::hasCLZERO () const inline
Definition at line 676 of file X86Subtarget.h.
References HasCLZERO.
hasCMov()
bool llvm::X86Subtarget::hasCMov () const inline
Definition at line 611 of file X86Subtarget.h.
References HasCMov, is64Bit(), SSE1, and X86SSELevel.
Referenced by llvm::X86InstrInfo::canInsertSelect(), combineCMov(), enableEarlyIfConversion(), and llvm::X86TargetLowering::X86TargetLowering().
hasCmpxchg16b()
bool llvm::X86Subtarget::hasCmpxchg16b () const inline
Definition at line 689 of file X86Subtarget.h.
References HasCmpxchg16b, and is64Bit().
Referenced by llvm::X86TargetLowering::ReplaceNodeResults(), and llvm::X86TargetLowering::X86TargetLowering().
hasCmpxchg8b()
bool llvm::X86Subtarget::hasCmpxchg8b () const inline
Definition at line 607 of file X86Subtarget.h.
References HasCmpxchg8b.
Referenced by llvm::X86TargetLowering::X86TargetLowering().
hasDQI()
bool llvm::X86Subtarget::hasDQI () const inline
Definition at line 721 of file X86Subtarget.h.
References HasDQI.
Referenced by combineBitcast(), combineSIntToFP(), EmitAVX512Test(), ExtractBitFromMaskVector(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getCastInstrCost(), llvm::X86InstrInfo::getExecutionDomain(), llvm::X86InstrInfo::getExecutionDomainCustom(), insert1BitVector(), llvm::X86TargetLowering::isLoadBitCastBeneficial(), lower1BitShuffle(), lower1BitShuffleAsKSHIFTR(), LowerCONCAT_VECTORSvXi1(), LowerEXTRACT_SUBVECTOR(), LowerI64IntToFP_AVX512DQ(), lowerINT_TO_FP_vXi64(), LowerLoad(), LowerMUL(), LowerSIGN_EXTEND_Mask(), LowerStore(), LowerTruncateVecI1(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86InstrInfo::setExecutionDomain(), llvm::X86InstrInfo::setExecutionDomainCustom(), and llvm::X86TargetLowering::X86TargetLowering().
hasENQCMD()
bool llvm::X86Subtarget::hasENQCMD () const inline
Definition at line 739 of file X86Subtarget.h.
References HasENQCMD.
hasERI()
bool llvm::X86Subtarget::hasERI () const inline
Definition at line 720 of file X86Subtarget.h.
References HasERI.
hasERMSB()
bool llvm::X86Subtarget::hasERMSB () const inline
Definition at line 708 of file X86Subtarget.h.
References HasERMSB.
Referenced by emitConstantSizeRepmov().
hasF16C()
bool llvm::X86Subtarget::hasF16C () const inline
Definition at line 647 of file X86Subtarget.h.
References HasF16C.
Referenced by combineFP16_TO_FP(), combineFP_EXTEND(), combineFP_ROUND(), and llvm::X86TargetLowering::X86TargetLowering().
hasFastBEXTR()
bool llvm::X86Subtarget::hasFastBEXTR () const inline
Definition at line 702 of file X86Subtarget.h.
References HasFastBEXTR.
Referenced by foldMaskedShiftToBEXTR().
hasFastGather()
bool llvm::X86Subtarget::hasFastGather () const inline
Definition at line 697 of file X86Subtarget.h.
References HasFastGather.
Referenced by llvm::X86TTIImpl::isLegalMaskedGather().
hasFastHorizontalOps()
bool llvm::X86Subtarget::hasFastHorizontalOps () const inline
Definition at line 703 of file X86Subtarget.h.
References HasFastHorizontalOps.
Referenced by shouldUseHorizontalOp().
hasFastLZCNT()
bool llvm::X86Subtarget::hasFastLZCNT () const inline
Definition at line 700 of file X86Subtarget.h.
References HasFastLZCNT.
Referenced by llvm::X86TargetLowering::isCtlzFast().
hasFastScalarFSQRT()
bool llvm::X86Subtarget::hasFastScalarFSQRT () const inline
Definition at line 698 of file X86Subtarget.h.
References HasFastScalarFSQRT.
hasFastScalarShiftMasks()
bool llvm::X86Subtarget::hasFastScalarShiftMasks () const inline
Definition at line 704 of file X86Subtarget.h.
References HasFastScalarShiftMasks.
Referenced by llvm::X86TargetLowering::shouldFoldConstantShiftPairToMask().
hasFastSHLDRotate()
bool llvm::X86Subtarget::hasFastSHLDRotate () const inline
Definition at line 701 of file X86Subtarget.h.
References HasFastSHLDRotate.
hasFastVariableShuffle()
bool llvm::X86Subtarget::hasFastVariableShuffle () const inline
Definition at line 693 of file X86Subtarget.h.
References HasFastVariableShuffle.
Referenced by combineX86ShuffleChain(), and lowerShuffleWithUndefHalf().
hasFastVectorFSQRT()
bool llvm::X86Subtarget::hasFastVectorFSQRT () const inline
Definition at line 699 of file X86Subtarget.h.
References HasFastVectorFSQRT.
hasFastVectorShiftMasks()
bool llvm::X86Subtarget::hasFastVectorShiftMasks () const inline
Definition at line 705 of file X86Subtarget.h.
References HasFastVectorShiftMasks.
Referenced by llvm::X86TargetLowering::shouldFoldConstantShiftPairToMask().
hasFMA()
bool llvm::X86Subtarget::hasFMA () const inline
Definition at line 639 of file X86Subtarget.h.
References HasFMA.
Referenced by hasAnyFMA().
hasFMA4()
bool llvm::X86Subtarget::hasFMA4 () const inline
Definition at line 640 of file X86Subtarget.h.
References HasFMA4.
Referenced by hasAnyFMA().
hasFSGSBase()
bool llvm::X86Subtarget::hasFSGSBase () const inline
Definition at line 648 of file X86Subtarget.h.
References HasFSGSBase.
hasFXSR()
bool llvm::X86Subtarget::hasFXSR () const inline
Definition at line 629 of file X86Subtarget.h.
References HasFXSR.
hasGFNI()
bool llvm::X86Subtarget::hasGFNI () const inline
Definition at line 636 of file X86Subtarget.h.
References HasGFNI.
hasIFMA()
bool llvm::X86Subtarget::hasIFMA () const inline
Definition at line 654 of file X86Subtarget.h.
References HasIFMA.
hasInt256()
bool llvm::X86Subtarget::hasInt256 () const inline
Definition at line 621 of file X86Subtarget.h.
References hasAVX2().
Referenced by combineConcatVectorOps(), combineHorizontalPredicateResult(), combineLoad(), combineLogicBlendIntoPBLENDV(), combineSetCCMOVMSK(), combineSignExtendInReg(), convertShiftLeftToScale(), EltsFromConsecutiveLoads(), getPMOVMSKB(), LowerABS(), LowerAVXExtend(), LowerBITREVERSE(), lowerBuildVectorAsBroadcast(), LowerEXTEND_VECTOR_INREG(), LowerMUL(), LowerMULH(), LowerScalarImmediateShift(), LowerShift(), LowerSIGN_EXTEND(), LowerVectorCTLZ(), LowerVectorCTPOP(), LowerVSETCC(), matchBinaryShuffle(), matchUnaryShuffle(), SupportedVectorShiftWithImm(), SupportedVectorVarShift(), truncateVectorWithPACK(), and llvm::X86TargetLowering::X86TargetLowering().
hasINVPCID()
bool llvm::X86Subtarget::hasINVPCID () const inline
Definition at line 738 of file X86Subtarget.h.
References HasINVPCID.
hasLAHFSAHF()
bool llvm::X86Subtarget::hasLAHFSAHF () const inline
Definition at line 674 of file X86Subtarget.h.
References HasLAHFSAHF.
hasLWP()
bool llvm::X86Subtarget::hasLWP () const inline
Definition at line 644 of file X86Subtarget.h.
References HasLWP.
hasLZCNT()
bool llvm::X86Subtarget::hasLZCNT () const inline
Definition at line 649 of file X86Subtarget.h.
References HasLZCNT.
Referenced by llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), llvm::X86TargetLowering::isCheapToSpeculateCtlz(), and llvm::X86TargetLowering::X86TargetLowering().
hasLZCNTFalseDeps()
bool llvm::X86Subtarget::hasLZCNTFalseDeps () const inline
Definition at line 692 of file X86Subtarget.h.
References HasLZCNTFalseDeps.
Referenced by hasPartialRegUpdate().
hasMacroFusion()
bool llvm::X86Subtarget::hasMacroFusion () const inline
Definition at line 706 of file X86Subtarget.h.
References HasMacroFusion.
Referenced by llvm::X86TTIImpl::canMacroFuseCmp().
hasMFence()
bool llvm::X86Subtarget::hasMFence () const inline
Use mfence if we have SSE2 or we're on x86-64 (even if we asked for no-sse2).
There isn't any reason to disable it if the target processor supports it.
Definition at line 806 of file X86Subtarget.h.
References hasSSE2(), and is64Bit().
Referenced by LowerATOMIC_FENCE().
hasMMX()
bool llvm::X86Subtarget::hasMMX () const inline
Definition at line 623 of file X86Subtarget.h.
References MMX, and X863DNowLevel.
Referenced by llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), and llvm::X86TargetLowering::X86TargetLowering().
hasMOVBE()
bool llvm::X86Subtarget::hasMOVBE () const inline
Definition at line 645 of file X86Subtarget.h.
References HasMOVBE.
Referenced by llvm::X86TargetLowering::X86TargetLowering().
hasMOVDIR64B()
bool llvm::X86Subtarget::hasMOVDIR64B () const inline
Definition at line 679 of file X86Subtarget.h.
References HasMOVDIR64B.
hasMOVDIRI()
bool llvm::X86Subtarget::hasMOVDIRI () const inline
Definition at line 678 of file X86Subtarget.h.
References HasMOVDIRI.
hasMWAITX()
bool llvm::X86Subtarget::hasMWAITX () const inline
Definition at line 675 of file X86Subtarget.h.
References HasMWAITX.
hasNOPL()
bool llvm::X86Subtarget::hasNOPL () const inline
Definition at line 608 of file X86Subtarget.h.
References HasNOPL.
hasPCLMUL()
bool llvm::X86Subtarget::hasPCLMUL () const inline
Definition at line 634 of file X86Subtarget.h.
References HasPCLMUL.
hasPCONFIG()
bool llvm::X86Subtarget::hasPCONFIG () const inline
Definition at line 735 of file X86Subtarget.h.
References HasPCONFIG.
hasPFI()
bool llvm::X86Subtarget::hasPFI () const inline
Definition at line 719 of file X86Subtarget.h.
References HasPFI.
hasPKU()
bool llvm::X86Subtarget::hasPKU () const inline
Definition at line 724 of file X86Subtarget.h.
References HasPKU.
hasPOPCNT()
bool llvm::X86Subtarget::hasPOPCNT () const inline
Definition at line 626 of file X86Subtarget.h.
References HasPOPCNT.
Referenced by llvm::X86TTIImpl::getPopcntSupport(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), and llvm::X86TargetLowering::X86TargetLowering().
hasPOPCNTFalseDeps()
bool llvm::X86Subtarget::hasPOPCNTFalseDeps () const inline
Definition at line 691 of file X86Subtarget.h.
References HasPOPCNTFalseDeps.
Referenced by hasPartialRegUpdate().
hasPrefetchW()
bool llvm::X86Subtarget::hasPrefetchW () const inline
Definition at line 660 of file X86Subtarget.h.
References has3DNow(), hasPREFETCHWT1(), and hasPRFCHW().
hasPREFETCHWT1()
bool llvm::X86Subtarget::hasPREFETCHWT1 () const inline
Definition at line 659 of file X86Subtarget.h.
References HasPREFETCHWT1.
Referenced by hasPrefetchW(), and hasSSEPrefetch().
hasPRFCHW()
bool llvm::X86Subtarget::hasPRFCHW () const inline
Definition at line 658 of file X86Subtarget.h.
References HasPRFCHW.
Referenced by hasPrefetchW(), and hasSSEPrefetch().
hasPTWRITE()
bool llvm::X86Subtarget::hasPTWRITE () const inline
Definition at line 680 of file X86Subtarget.h.
References HasPTWRITE.
hasRDPID()
bool llvm::X86Subtarget::hasRDPID () const inline
Definition at line 733 of file X86Subtarget.h.
References HasRDPID.
hasRDRAND()
bool llvm::X86Subtarget::hasRDRAND () const inline
Definition at line 646 of file X86Subtarget.h.
References HasRDRAND.
hasRDSEED()
bool llvm::X86Subtarget::hasRDSEED () const inline
Definition at line 673 of file X86Subtarget.h.
References HasRDSEED.
hasRTM()
bool llvm::X86Subtarget::hasRTM () const inline
Definition at line 655 of file X86Subtarget.h.
References HasRTM.
hasSERIALIZE()
bool llvm::X86Subtarget::hasSERIALIZE () const inline
Definition at line 740 of file X86Subtarget.h.
References HasSERIALIZE.
hasSGX()
bool llvm::X86Subtarget::hasSGX () const inline
Definition at line 736 of file X86Subtarget.h.
References HasSGX.
hasSHA()
bool llvm::X86Subtarget::hasSHA () const inline
Definition at line 657 of file X86Subtarget.h.
References HasSHA.
hasSHSTK()
bool llvm::X86Subtarget::hasSHSTK () const inline
Definition at line 729 of file X86Subtarget.h.
References HasSHSTK.
hasSlowDivide32()
bool llvm::X86Subtarget::hasSlowDivide32 () const inline
Definition at line 709 of file X86Subtarget.h.
References HasSlowDivide32.
Referenced by llvm::X86TargetLowering::X86TargetLowering().
hasSlowDivide64()
bool llvm::X86Subtarget::hasSlowDivide64 () const inline
Definition at line 710 of file X86Subtarget.h.
References HasSlowDivide64.
Referenced by llvm::X86TargetLowering::X86TargetLowering().
hasSSE1()
bool llvm::X86Subtarget::hasSSE1 () const inline
Definition at line 612 of file X86Subtarget.h.
References SSE1, and X86SSELevel.
Referenced by combineAnd(), combineBitcast(), combineBitcastvxi1(), combineCMov(), combineFAndFNotToFAndn(), combineFMinNumFMaxNum(), combineOr(), combineSelect(), combineSetCC(), combineXor(), convertIntLogicToFPLogic(), createMMXBuildVector(), get64BitArgumentXMMs(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::X86TargetLowering::getByValTypeAlignment(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCallPreservedMask(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getMinMaxCost(), llvm::X86TTIImpl::getNumberOfRegisters(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TTIImpl::getRegisterBitWidth(), llvm::X86TTIImpl::getShuffleCost(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), llvm::X86TargetLowering::hasAndNot(), hasSSEPrefetch(), llvm::X86TTIImpl::isLegalNTLoad(), llvm::X86TTIImpl::isLegalNTStore(), LowerATOMIC_STORE(), LowerStore(), llvm::X86TargetLowering::LowerXConstraint(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), llvm::X86TargetLowering::ReplaceNodeResults(), X86ChooseCmpOpcode(), and llvm::X86TargetLowering::X86TargetLowering().
hasSSE2()
bool llvm::X86Subtarget::hasSSE2 () const inline
Definition at line 613 of file X86Subtarget.h.
References SSE2, and X86SSELevel.
Referenced by combineAnd(), combineBasicSADPattern(), combineBitcast(), combineBitcastvxi1(), combineCMov(), combineCompareEqual(), combineExtractWithShuffle(), combineFAndFNotToFAndn(), combineFMinNumFMaxNum(), combineHorizontalPredicateResult(), combineLogicBlendIntoPBLENDV(), combineMOVMSK(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineOr(), combinePMULH(), combineReductionToHorizontal(), combineSelect(), combineSetCC(), combineStore(), combineSubToSubus(), combineToExtendBoolVectorInReg(), combineTruncateWithSat(), combineVectorSignBitsTruncation(), combineVectorSizedSetCCEquality(), combineVectorTruncation(), combineX86ShuffleChain(), combineXor(), llvm::X86InstrInfo::commuteInstructionImpl(), convertIntLogicToFPLogic(), detectAVGPattern(), EltsFromConsecutiveLoads(), llvm::X86TTIImpl::enableMemCmpExpansion(), llvm::X86InstrInfo::findCommutedOpIndices(), foldVectorXorShiftIntoCmp(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticReductionCost(), llvm::X86TTIImpl::getCastInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getMinMaxCost(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86TTIImpl::getScalarizationOverhead(), llvm::X86TTIImpl::getShuffleCost(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), llvm::X86TTIImpl::getVectorInstrCost(), getZeroVector(), llvm::X86TargetLowering::hasAndNot(), hasMFence(), LowerATOMIC_STORE(), LowerBITCAST(), LowerBuildVectorAsInsert(), LowerEXTEND_VECTOR_INREG(), lowerFPToIntToFP(), LowerMUL(), LowerMULH(), LowerShift(), LowerStore(), lowerV4F32Shuffle(), LowerVSETCC(), LowerVSETCCWithSUBUS(), lowerX86FPLogicOp(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchPMADDWD(), matchPMADDWD_2(), matchUnaryPermuteShuffle(), matchUnaryShuffle(), MatchVectorAllZeroTest(), materializeVectorConstant(), reduceVMULWidth(), llvm::X86TargetLowering::ReplaceNodeResults(), SplitOpsAndApply(), SupportedVectorShiftWithImm(), truncateVectorWithPACK(), useVectorCast(), X86ChooseCmpOpcode(), and llvm::X86TargetLowering::X86TargetLowering().
hasSSE3()
bool llvm::X86Subtarget::hasSSE3 () const inline
Definition at line 614 of file X86Subtarget.h.
References SSE3, and X86SSELevel.
Referenced by combineFaddFsub(), combineReductionToHorizontal(), isAddSubOrSubAdd(), isAddSubOrSubAdd(), lowerAddSubToHorizontalOp(), LowerBuildVectorv4x32(), lowerShuffleAsBitRotate(), lowerShuffleAsBroadcast(), LowerToHorizontalOp(), LowerUINT_TO_FP_i64(), lowerV4F32Shuffle(), and matchUnaryShuffle().
hasSSE41()
bool llvm::X86Subtarget::hasSSE41 () const inline
Definition at line 616 of file X86Subtarget.h.
References SSE41, and X86SSELevel.
Referenced by llvm::X86TargetLowering::allowsMisalignedMemoryAccesses(), combineExtractWithShuffle(), combineHorizontalMinMaxResult(), combineHorizontalPredicateResult(), combineLogicBlendIntoPBLENDV(), combineMulToPMADDWD(), combineMulToPMULDQ(), combineReductionToHorizontal(), combineSetCCMOVMSK(), combineShiftToPMULH(), combineTruncateWithSat(), combineVectorSignBitsTruncation(), combineVectorSizedSetCCEquality(), combineVectorTruncation(), combineVSelectToBLENDV(), combineX86ShuffleChain(), llvm::X86InstrInfo::commuteInstructionImpl(), convertShiftLeftToScale(), createVariablePermute(), llvm::X86InstrInfo::findCommutedOpIndices(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getCastInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getMinMaxCost(), llvm::X86TTIImpl::getMinMaxReductionCost(), llvm::X86TTIImpl::getScalarizationOverhead(), llvm::X86TTIImpl::getShuffleCost(), getTargetVShiftNode(), llvm::X86TTIImpl::getVectorInstrCost(), LowerABS(), LowerBuildVectorAsInsert(), LowerBuildVectorv16i8(), LowerBuildVectorv4x32(), LowerBuildVectorv8i16(), LowerMUL(), LowerMULH(), LowerRotate(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleWithPACK(), lowerUINT_TO_FP_vXi32(), lowerV16I8Shuffle(), lowerV2F64Shuffle(), lowerV2I64Shuffle(), lowerV4F32Shuffle(), lowerV4I32Shuffle(), lowerV8I16Shuffle(), LowerVectorAllZero(), LowerVSETCC(), matchBinaryPermuteShuffle(), matchBinaryShuffle(), matchShuffleWithPACK(), matchShuffleWithUNPCK(), matchUnaryShuffle(), reduceVMULWidth(), llvm::X86TargetLowering::ReplaceNodeResults(), truncateVectorWithPACK(), and llvm::X86TargetLowering::X86TargetLowering().
hasSSE42()
bool llvm::X86Subtarget::hasSSE42 () const inline
Definition at line 617 of file X86Subtarget.h.
References SSE42, and X86SSELevel.
Referenced by llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getMinMaxCost(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), LowerScalarImmediateShift(), and LowerVSETCC().
hasSSE4A()
bool llvm::X86Subtarget::hasSSE4A () const inline
Definition at line 622 of file X86Subtarget.h.
References HasSSE4A.
Referenced by combineStore(), combineX86ShuffleChain(), llvm::X86TTIImpl::isLegalNTStore(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerV16I8Shuffle(), and lowerV8I16Shuffle().
hasSSEPrefetch()
bool llvm::X86Subtarget::hasSSEPrefetch () const inline
Definition at line 667 of file X86Subtarget.h.
References has3DNow(), hasPREFETCHWT1(), hasPRFCHW(), and hasSSE1().
Referenced by llvm::X86TargetLowering::X86TargetLowering().
hasSSEUnalignedMem()
bool llvm::X86Subtarget::hasSSEUnalignedMem () const inline
Definition at line 688 of file X86Subtarget.h.
References HasSSEUnalignedMem.
hasSSSE3()
bool llvm::X86Subtarget::hasSSSE3 () const inline
Definition at line 615 of file X86Subtarget.h.
References SSSE3, and X86SSELevel.
Referenced by combineAddOrSubToHADDorHSUB(), combineReductionToHorizontal(), combineSubToSubus(), combineVectorTruncation(), combineX86ShuffleChain(), createVariablePermute(), detectPMADDUBSW(), llvm::X86TTIImpl::getShuffleCost(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), lowerAddSubToHorizontalOp(), LowerBITREVERSE(), lowerShuffleAsByteRotate(), lowerShuffleAsByteRotateAndPermute(), lowerShuffleAsByteShiftMask(), lowerShuffleAsSpecificZeroOrAnyExtend(), lowerShuffleWithPSHUFB(), LowerToHorizontalOp(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV4I32Shuffle(), lowerV8I16Shuffle(), LowerVectorCTLZ(), LowerVectorCTPOP(), matchBinaryPermuteShuffle(), and llvm::X86TargetLowering::X86TargetLowering().
hasTBM()
bool llvm::X86Subtarget::hasTBM () const inline
Definition at line 643 of file X86Subtarget.h.
References HasTBM.
Referenced by foldMaskedShiftToBEXTR().
hasTSXLDTRK()
bool llvm::X86Subtarget::hasTSXLDTRK () const inline
Definition at line 741 of file X86Subtarget.h.
References HasTSXLDTRK.
hasVAES()
bool llvm::X86Subtarget::hasVAES () const inline
Definition at line 628 of file X86Subtarget.h.
References HasVAES.
hasVBMI()
bool llvm::X86Subtarget::hasVBMI () const inline
Definition at line 652 of file X86Subtarget.h.
References HasVBMI.
Referenced by combineX86ShuffleChain(), llvm::X86TTIImpl::getShuffleCost(), lowerV16I8Shuffle(), lowerV32I8Shuffle(), and lowerV64I8Shuffle().
hasVBMI2()
bool llvm::X86Subtarget::hasVBMI2 () const inline
Definition at line 653 of file X86Subtarget.h.
References HasVBMI2.
Referenced by llvm::X86TTIImpl::isLegalMaskedExpandLoad(), LowerFunnelShift(), and llvm::X86TargetLowering::X86TargetLowering().
hasVLX()
bool llvm::X86Subtarget::hasVLX () const inline
Definition at line 723 of file X86Subtarget.h.
References HasVLX.
Referenced by canExtendTo512DQ(), canonicalizeBitSelect(), combineExtractSubvector(), combineLogicBlendIntoPBLENDV(), combineScalarAndWithMaskSetcc(), combineTruncateWithSat(), combineVectorPack(), combineVectorSizedSetCCEquality(), combineX86ShuffleChain(), llvm::X86InstrInfo::copyPhysReg(), createVariablePermute(), llvm::X86InstrInfo::expandPostRAPseudo(), getBroadcastOpcode(), llvm::X86TTIImpl::getGatherScatterOpCost(), llvm::X86RegisterInfo::getLargestLegalSuperClass(), getLoadStoreRegOpcode(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TargetLowering::getSetCCResultType(), isLegalMaskCompare(), lower1BitShuffle(), lowerBuildVectorAsBroadcast(), LowerI64IntToFP_AVX512DQ(), lowerINT_TO_FP_vXi64(), LowerMGATHER(), LowerMLOAD(), LowerMSCATTER(), LowerMSTORE(), LowerShift(), lowerShuffleAsBlend(), lowerShuffleAsVALIGN(), lowerShuffleWithPACK(), lowerShuffleWithVPMOV(), LowerSIGN_EXTEND_Mask(), LowerTruncateVecI1(), lowerUINT_TO_FP_v2i32(), lowerUINT_TO_FP_vXi32(), lowerV16I16Shuffle(), lowerV16I8Shuffle(), lowerV2I64Shuffle(), lowerV2X128Shuffle(), lowerV32I8Shuffle(), lowerV4F64Shuffle(), lowerV4I64Shuffle(), lowerV8F32Shuffle(), lowerV8I16Shuffle(), lowerV8I32Shuffle(), LowerVSETCC(), LowerZERO_EXTEND_Mask(), matchBinaryPermuteShuffle(), matchShuffleAsVTRUNC(), llvm::X86TargetLowering::ReplaceNodeResults(), and llvm::X86TargetLowering::X86TargetLowering().
hasVNNI()
bool llvm::X86Subtarget::hasVNNI () const inline
Definition at line 725 of file X86Subtarget.h.
References HasVNNI.
hasVP2INTERSECT()
bool llvm::X86Subtarget::hasVP2INTERSECT () const inline
Definition at line 727 of file X86Subtarget.h.
References HasVP2INTERSECT.
hasVPCLMULQDQ()
bool llvm::X86Subtarget::hasVPCLMULQDQ () const inline
Definition at line 635 of file X86Subtarget.h.
References HasVPCLMULQDQ.
hasVPOPCNTDQ()
bool llvm::X86Subtarget::hasVPOPCNTDQ () const inline
Definition at line 718 of file X86Subtarget.h.
References HasVPOPCNTDQ.
Referenced by LowerVectorCTPOP(), and llvm::X86TargetLowering::X86TargetLowering().
hasWAITPKG()
bool llvm::X86Subtarget::hasWAITPKG () const inline
Definition at line 734 of file X86Subtarget.h.
References HasWAITPKG.
hasWBNOINVD()
bool llvm::X86Subtarget::hasWBNOINVD () const inline
Definition at line 732 of file X86Subtarget.h.
References HasWBNOINVD.
hasX87()
bool llvm::X86Subtarget::hasX87 () const inline
Definition at line 606 of file X86Subtarget.h.
References HasX87.
Referenced by combineSIntToFP(), llvm::X86TargetLowering::getOptimalMemOpType(), LowerATOMIC_STORE(), llvm::X86TargetLowering::ReplaceNodeResults(), and llvm::X86TargetLowering::X86TargetLowering().
hasXOP()
bool llvm::X86Subtarget::hasXOP () const inline
Definition at line 642 of file X86Subtarget.h.
References HasXOP.
Referenced by canonicalizeBitSelect(), combineSelect(), combineX86ShuffleChain(), llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getIntrinsicInstrCost(), llvm::X86TTIImpl::getShuffleCost(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), llvm::X86TargetLowering::isVectorShiftByScalarCheap(), LowerBITREVERSE(), LowerBuildVectorv4x32(), LowerRotate(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerShift(), lowerShuffleAsBitRotate(), LowerVSETCC(), matchUnaryPermuteShuffle(), and llvm::X86TargetLowering::X86TargetLowering().
hasXSAVE()
bool llvm::X86Subtarget::hasXSAVE () const inline
Definition at line 630 of file X86Subtarget.h.
References HasXSAVE.
hasXSAVEC()
bool llvm::X86Subtarget::hasXSAVEC () const inline
Definition at line 632 of file X86Subtarget.h.
References HasXSAVEC.
hasXSAVEOPT()
bool llvm::X86Subtarget::hasXSAVEOPT () const inline
Definition at line 631 of file X86Subtarget.h.
References HasXSAVEOPT.
hasXSAVES()
bool llvm::X86Subtarget::hasXSAVES () const inline
Definition at line 633 of file X86Subtarget.h.
References HasXSAVES.
insertVZEROUPPER()
bool llvm::X86Subtarget::insertVZEROUPPER () const inline
Definition at line 696 of file X86Subtarget.h.
References InsertVZEROUPPER.
is16Bit()
bool llvm::X86Subtarget::is16Bit () const inline
Definition at line 587 of file X86Subtarget.h.
Referenced by llvm::X86TargetLowering::getRegForInlineAsmConstraint().
is32Bit()
bool llvm::X86Subtarget::is32Bit () const inline
Definition at line 583 of file X86Subtarget.h.
Referenced by llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::X86FrameLowering::emitPrologue(), getMaskNode(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), getv64i1Argument(), maxLongNopLength(), Passv64i1ArgInRegs(), llvm::X86FrameLowering::processFunctionBeforeFrameIndicesReplaced(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), and llvm::X86TargetLowering::X86TargetLowering().
is64Bit()
bool llvm::X86Subtarget::is64Bit () const inline
Is this x86_64? (disregarding specific ABI / programming model)
Definition at line 579 of file X86Subtarget.h.
Referenced by llvm::X86InstrInfo::analyzeBranchPredicate(), llvm::X86TargetLowering::canMergeStoresTo(), classifyGlobalFunctionReference(), classifyGlobalReference(), classifyLocalReference(), combineAnd(), combineCompareEqual(), combineSelect(), combineSIntToFP(), combineStore(), computeBytesPoppedByCalleeForSRet(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::copyPhysReg(), emitLockedStackOp(), llvm::X86TargetLowering::emitStackGuardXorFP(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86TTIImpl::enableMemCmpExpansion(), expandIntrinsicWChainHelper(), ExpandMOVImmSExti8(), llvm::X86TargetLowering::findRepresentativeClass(), llvm::X86InstrInfo::foldMemoryOperandImpl(), get64BitArgumentGPRs(), get64BitArgumentXMMs(), llvm::X86TargetLowering::getByValTypeAlignment(), llvm::X86InstrInfo::getGlobalBaseReg(), getIndirectThunkSymbol(), llvm::X86TTIImpl::getIntrinsicInstrCost(), llvm::X86TargetLowering::getIRStackGuard(), getLoadStoreRegOpcode(), llvm::X86TTIImpl::getNumberOfRegisters(), llvm::X86TargetLowering::getOptimalMemOpType(), getOptimalRepmovsType(), llvm::X86TargetLowering::getPICJumpTableRelocBase(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TTIImpl::getRegisterBitWidth(), getRetOpcode(), llvm::X86TargetLowering::getSafeStackPointerLocation(), llvm::X86TargetLowering::getStackProbeSymbolName(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), hasBZHI(), hasCMov(), hasCmpxchg16b(), hasMFence(), insert1BitVector(), llvm::X86InstrInfo::isCoalescableExtInstr(), llvm::X86TargetLowering::isLegalAddressingMode(), isTargetNaCl32(), isTargetNaCl64(), isXRaySupported(), llvm::X86TargetLowering::isZExtFree(), llvm::X86TargetLowering::isZExtFree(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), LowerBITCAST(), LowerBUILD_VECTORvXi1(), llvm::X86CallLowering::lowerCall(), LowerCMP_SWAP(), LowerFSINCOS(), LowerI64IntToFP_AVX512DQ(), lowerShuffleAsBitMask(), LowerStore(), LowerVACOPY(), llvm::X86TargetLowering::markLibCallAttributes(), maxLongNopLength(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), recoverFramePointer(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::X86TargetLowering::shouldConvertPhiType(), llvm::X86TargetLowering::shouldFoldMaskToVariableShiftPair(), llvm::X86InstrInfo::shouldScheduleLoadsNear(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::X86TargetLowering::supportSwiftError(), llvm::X86TargetLowering::useLoadStackGuardNode(), llvm::X86FrameLowering::X86FrameLowering(), X86Subtarget(), and llvm::X86TargetLowering::X86TargetLowering().
isAtom()
bool llvm::X86Subtarget::isAtom () const inline
TODO: to be removed later and replaced with suitable properties.
Definition at line 798 of file X86Subtarget.h.
References IntelAtom, and X86ProcFamily.
Referenced by EmitCmp(), llvm::X86TTIImpl::enableInterleavedAccessVectorization(), llvm::X86TTIImpl::getMaxInterleaveFactor(), and llvm::X86TargetLowering::X86TargetLowering().
isCallingConvWin64()
bool llvm::X86Subtarget::isCallingConvWin64 (CallingConv::ID CC) const inline
Definition at line 867 of file X86Subtarget.h.
References llvm::CallingConv::C, llvm::CallingConv::Fast, llvm::CallingConv::Intel_OCL_BI, isTargetWin64(), llvm::CallingConv::Swift, llvm::CallingConv::Tail, llvm::CallingConv::Win64, llvm::CallingConv::X86_64_SysV, llvm::CallingConv::X86_FastCall, llvm::CallingConv::X86_StdCall, llvm::CallingConv::X86_ThisCall, and llvm::CallingConv::X86_VectorCall.
Referenced by get64BitArgumentGPRs(), get64BitArgumentXMMs(), llvm::X86FrameLowering::has128ByteRedZone(), llvm::X86CallLowering::lowerCall(), and LowerVACOPY().
isLegalToCallImmediateAddr()
bool X86Subtarget::isLegalToCallImmediateAddr () const
Return true if the subtarget allows calls to immediate address.
Definition at line 221 of file X86Subtarget.cpp.
References llvm::TargetMachine::getRelocationModel(), isTargetELF(), isTargetWin32(), llvm::Reloc::Static, and TM.
isOSWindows()
bool llvm::X86Subtarget::isOSWindows () const inline
Definition at line 852 of file X86Subtarget.h.
References llvm::Triple::isOSWindows(), and TargetTriple.
Referenced by classifyGlobalReference(), llvm::X86TargetLowering::getStackProbeSymbolName(), llvm::X86TargetLowering::hasInlineStackProbe(), isTargetWin32(), isTargetWin64(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::X86TargetLowering::shouldExpandShift(), and llvm::X86FrameLowering::spillCalleeSavedRegisters().
isPICStyleGOT()
bool llvm::X86Subtarget::isPICStyleGOT () const inline
Definition at line 858 of file X86Subtarget.h.
References llvm::PICStyles::GOT, and PICStyle.
Referenced by llvm::X86TargetLowering::getJumpTableEncoding(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), and llvm::X86TargetLowering::LowerCustomJumpTableEntry().
isPICStyleRIPRel()
bool llvm::X86Subtarget::isPICStyleRIPRel () const inline
Definition at line 859 of file X86Subtarget.h.
References PICStyle, and llvm::PICStyles::RIPRel.
Referenced by llvm::X86TargetLowering::getPICJumpTableRelocBaseExpr(), and llvm::X86AsmPrinter::PrintAsmOperand().
isPICStyleStubPIC()
bool llvm::X86Subtarget::isPICStyleStubPIC () const inline
Definition at line 861 of file X86Subtarget.h.
References PICStyle, and llvm::PICStyles::StubPIC.
Referenced by llvm::X86TargetLowering::LowerAsmOperandForConstraint().
isPMADDWDSlow()
bool llvm::X86Subtarget::isPMADDWDSlow () const inline
Definition at line 683 of file X86Subtarget.h.
References IsPMADDWDSlow.
Referenced by combineMulToPMADDWD().
isPMULLDSlow()
bool llvm::X86Subtarget::isPMULLDSlow () const inline
Definition at line 682 of file X86Subtarget.h.
References IsPMULLDSlow.
Referenced by reduceVMULWidth().
isPositionIndependent()
bool X86Subtarget::isPositionIndependent () const
Definition at line 384 of file X86Subtarget.cpp.
References llvm::TargetMachine::isPositionIndependent(), and TM.
Referenced by classifyGlobalReference(), classifyLocalReference(), and X86Subtarget().
isSHLDSlow()
bool llvm::X86Subtarget::isSHLDSlow () const inline
Definition at line 681 of file X86Subtarget.h.
References IsSHLDSlow.
Referenced by LowerFunnelShift(), and llvm::X86TargetLowering::X86TargetLowering().
isSLM()
bool llvm::X86Subtarget::isSLM () const inline
Definition at line 799 of file X86Subtarget.h.
References IntelSLM, and X86ProcFamily.
Referenced by llvm::X86TTIImpl::getArithmeticInstrCost(), llvm::X86TTIImpl::getArithmeticReductionCost(), llvm::X86TTIImpl::getCmpSelInstrCost(), llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost(), and llvm::X86TTIImpl::getVectorInstrCost().
isTarget64BitILP32()
bool llvm::X86Subtarget::isTarget64BitILP32 () const inline
Is this x86_64 with the ILP32 programming model (x32 ABI)?
Definition at line 592 of file X86Subtarget.h.
References llvm::Triple::getEnvironment(), llvm::Triple::GNUX32, llvm::Triple::isOSNaCl(), and TargetTriple.
Referenced by llvm::X86FrameLowering::determineCalleeSaves(), llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), llvm::X86FrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), getLeaOP(), llvm::X86RegisterInfo::getPtrSizedFrameRegister(), and llvm::X86RegisterInfo::getPtrSizedStackRegister().
isTarget64BitLP64()
bool llvm::X86Subtarget::isTarget64BitLP64 () const inline
Is this x86_64 with the LP64 programming model (standard AMD64, no x32)?
Definition at line 598 of file X86Subtarget.h.
References llvm::Triple::getEnvironment(), llvm::Triple::GNUX32, llvm::Triple::isOSNaCl(), and TargetTriple.
Referenced by emitRepmovs(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::X86TargetLowering::getExceptionPointerRegister(), llvm::X86TargetLowering::getExceptionSelectorRegister(), llvm::X86RegisterInfo::getPointerRegClass(), llvm::X86TargetLowering::reduceSelectOfFPConstantLoads(), and llvm::X86FrameLowering::X86FrameLowering().
isTargetAndroid()
bool llvm::X86Subtarget::isTargetAndroid () const inline
Definition at line 823 of file X86Subtarget.h.
References llvm::Triple::isAndroid(), and TargetTriple.
Referenced by llvm::X86TargetLowering::getSafeStackPointerLocation().
isTargetCOFF()
bool llvm::X86Subtarget::isTargetCOFF () const inline
Definition at line 817 of file X86Subtarget.h.
References llvm::Triple::isOSBinFormatCOFF(), and TargetTriple.
Referenced by classifyGlobalFunctionReference(), classifyGlobalReference(), classifyLocalReference(), llvm::X86AsmPrinter::runOnMachineFunction(), and X86Subtarget().
isTargetCygMing()
bool llvm::X86Subtarget::isTargetCygMing () const inline
Definition at line 850 of file X86Subtarget.h.
References llvm::Triple::isOSCygMing(), and TargetTriple.
Referenced by llvm::X86TargetLowering::getStackProbeSymbolName(), and llvm::X86TargetLowering::X86TargetLowering().
isTargetDarwin()
bool llvm::X86Subtarget::isTargetDarwin () const inline
Definition at line 810 of file X86Subtarget.h.
References llvm::Triple::isOSDarwin(), and TargetTriple.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), classifyGlobalReference(), classifyLocalReference(), LowerFSINCOS(), X86Subtarget(), and llvm::X86TargetLowering::X86TargetLowering().
isTargetDragonFly()
bool llvm::X86Subtarget::isTargetDragonFly () const inline
Definition at line 812 of file X86Subtarget.h.
References llvm::Triple::isOSDragonFly(), and TargetTriple.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks().
isTargetELF()
bool llvm::X86Subtarget::isTargetELF () const inline
Definition at line 816 of file X86Subtarget.h.
References llvm::Triple::isOSBinFormatELF(), and TargetTriple.
Referenced by classifyGlobalFunctionReference(), classifyGlobalReference(), classifyLocalReference(), isLegalToCallImmediateAddr(), X86Subtarget(), and llvm::X86TargetLowering::X86TargetLowering().
isTargetFreeBSD()
bool llvm::X86Subtarget::isTargetFreeBSD () const inline
Definition at line 811 of file X86Subtarget.h.
References llvm::Triple::isOSFreeBSD(), and TargetTriple.
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks().
isTargetFuchsia()
bool llvm::X86Subtarget::isTargetFuchsia () const inline
Definition at line 828 of file X86Subtarget.h.
References llvm::Triple::isOSFuchsia(), and TargetTriple.
Referenced by llvm::X86TargetLowering::getIRStackGuard(), and llvm::X86TargetLowering::getSafeStackPointerLocation().
isTargetGlibc()
bool llvm::X86Subtarget::isTargetGlibc () const inline
Definition at line 822 of file X86Subtarget.h.
References llvm::Triple::isOSGlibc(), and TargetTriple.
isTargetKFreeBSD()
bool llvm::X86Subtarget::isTargetKFreeBSD () const inline
Definition at line 821 of file X86Subtarget.h.
References llvm::Triple::isOSKFreeBSD(), and TargetTriple.
isTargetLinux()
bool llvm::X86Subtarget::isTargetLinux () const inline
Definition at line 820 of file X86Subtarget.h.
References llvm::Triple::isOSLinux(), and TargetTriple.
Referenced by llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::X86FrameLowering::adjustForSegmentedStacks(), and llvm::X86CallLowering::lowerCall().
isTargetMachO()
bool llvm::X86Subtarget::isTargetMachO () const inline
Definition at line 818 of file X86Subtarget.h.
References llvm::Triple::isOSBinFormatMachO(), and TargetTriple.
Referenced by llvm::X86TargetLowering::getStackProbeSymbolName(), llvm::X86TargetLowering::useLoadStackGuardNode(), and llvm::X86TargetLowering::useStackGuardXorFP().
isTargetMCU()
bool llvm::X86Subtarget::isTargetMCU () const inline
Definition at line 827 of file X86Subtarget.h.
References llvm::Triple::isOSIAMCU(), and TargetTriple.
Referenced by computeBytesPoppedByCalleeForSRet().
isTargetNaCl()
bool llvm::X86Subtarget::isTargetNaCl () const inline
Definition at line 824 of file X86Subtarget.h.
References llvm::Triple::isOSNaCl(), and TargetTriple.
Referenced by isTargetNaCl32(), and isTargetNaCl64().
isTargetNaCl32()
bool llvm::X86Subtarget::isTargetNaCl32 () const inline
Definition at line 825 of file X86Subtarget.h.
References is64Bit(), and isTargetNaCl().
isTargetNaCl64()
bool llvm::X86Subtarget::isTargetNaCl64 () const inline
Definition at line 826 of file X86Subtarget.h.
References is64Bit(), and isTargetNaCl().
Referenced by llvm::X86FrameLowering::X86FrameLowering().
isTargetPS4()
bool llvm::X86Subtarget::isTargetPS4 () const inline
Definition at line 814 of file X86Subtarget.h.
References llvm::Triple::isPS4CPU(), and TargetTriple.
isTargetSolaris()
bool llvm::X86Subtarget::isTargetSolaris () const inline
Definition at line 813 of file X86Subtarget.h.
References llvm::Triple::isOSSolaris(), and TargetTriple.
isTargetWin32()
bool llvm::X86Subtarget::isTargetWin32 () const inline
Definition at line 856 of file X86Subtarget.h.
References isOSWindows().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::X86FrameLowering::emitPrologue(), isLegalToCallImmediateAddr(), llvm::X86FrameLowering::restoreWin32EHStackPointers(), and llvm::X86AsmPrinter::runOnMachineFunction().
isTargetWin64()
bool llvm::X86Subtarget::isTargetWin64 () const inline
Definition at line 854 of file X86Subtarget.h.
References isOSWindows().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::X86InstrInfo::canMakeTailCallConditional(), llvm::X86FrameLowering::canUseAsEpilogue(), llvm::X86FrameLowering::getFrameIndexReferencePreferSP(), isCallingConvWin64(), llvm::X86TargetLowering::needsFixedCatchObjects(), and llvm::X86TargetLowering::X86TargetLowering().
isTargetWindowsCoreCLR()
bool llvm::X86Subtarget::isTargetWindowsCoreCLR () const inline
Definition at line 834 of file X86Subtarget.h.
References llvm::Triple::isWindowsCoreCLREnvironment(), and TargetTriple.
Referenced by llvm::X86FrameLowering::emitStackProbe().
isTargetWindowsCygwin()
bool llvm::X86Subtarget::isTargetWindowsCygwin () const inline
Definition at line 838 of file X86Subtarget.h.
References llvm::Triple::isWindowsCygwinEnvironment(), and TargetTriple.
isTargetWindowsGNU()
bool llvm::X86Subtarget::isTargetWindowsGNU () const inline
Definition at line 842 of file X86Subtarget.h.
References llvm::Triple::isWindowsGNUEnvironment(), and TargetTriple.
isTargetWindowsItanium()
bool llvm::X86Subtarget::isTargetWindowsItanium () const inline
Definition at line 846 of file X86Subtarget.h.
References llvm::Triple::isWindowsItaniumEnvironment(), and TargetTriple.
Referenced by llvm::X86TargetLowering::X86TargetLowering().
isTargetWindowsMSVC()
bool llvm::X86Subtarget::isTargetWindowsMSVC () const inline
Definition at line 830 of file X86Subtarget.h.
References llvm::Triple::isWindowsMSVCEnvironment(), and TargetTriple.
Referenced by llvm::X86FrameLowering::restoreWin32EHStackPointers(), and llvm::X86TargetLowering::X86TargetLowering().
isUnalignedMem16Slow()
bool llvm::X86Subtarget::isUnalignedMem16Slow () const inline
Definition at line 684 of file X86Subtarget.h.
References IsUAMem16Slow.
Referenced by llvm::X86TargetLowering::allowsMisalignedMemoryAccesses(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::X86InstrInfo::unfoldMemoryOperand(), and llvm::X86InstrInfo::unfoldMemoryOperand().
isUnalignedMem32Slow()
bool llvm::X86Subtarget::isUnalignedMem32Slow () const inline
Definition at line 685 of file X86Subtarget.h.
References IsUAMem32Slow.
Referenced by llvm::X86TargetLowering::allowsMisalignedMemoryAccesses(), and llvm::X86TTIImpl::getMemoryOpCost().
isXRaySupported()
bool llvm::X86Subtarget::isXRaySupported () const inline override
Definition at line 793 of file X86Subtarget.h.
References is64Bit().
LEAusesAG()
bool llvm::X86Subtarget::LEAusesAG () const inline
Definition at line 713 of file X86Subtarget.h.
References LEAUsesAG.
padShortFunctions()
bool llvm::X86Subtarget::padShortFunctions () const inline
Definition at line 711 of file X86Subtarget.h.
References PadShortFunctions.
ParseSubtargetFeatures()
void llvm::X86Subtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options.
Definition of function is auto generated by tblgen.
preferMaskRegisters()
bool llvm::X86Subtarget::preferMaskRegisters () const inline
Definition at line 761 of file X86Subtarget.h.
References PreferMaskRegisters.
Referenced by combineVectorSizedSetCCEquality().
setPICStyle()
void llvm::X86Subtarget::setPICStyle (PICStyles::Style Style) inline
Definition at line 604 of file X86Subtarget.h.
References PICStyle.
Referenced by X86Subtarget().
slow3OpsLEA()
bool llvm::X86Subtarget::slow3OpsLEA () const inline
Definition at line 715 of file X86Subtarget.h.
References Slow3OpsLEA.
slowIncDec()
bool llvm::X86Subtarget::slowIncDec () const inline
Definition at line 716 of file X86Subtarget.h.
References SlowIncDec.
slowLEA()
bool llvm::X86Subtarget::slowLEA () const inline
Definition at line 714 of file X86Subtarget.h.
References SlowLEA.
Referenced by combineMul().
slowTwoMemOps()
bool llvm::X86Subtarget::slowTwoMemOps () const inline
Definition at line 712 of file X86Subtarget.h.
References SlowTwoMemOps.
Referenced by llvm::X86InstrInfo::foldMemoryOperandImpl().
threewayBranchProfitable()
bool llvm::X86Subtarget::threewayBranchProfitable () const inline
Definition at line 737 of file X86Subtarget.h.
References ThreewayBranchProfitable.
useAA()
bool llvm::X86Subtarget::useAA () const inline override
Definition at line 801 of file X86Subtarget.h.
References UseAA.
useAVX512Regs()
bool llvm::X86Subtarget::useAVX512Regs () const inline
Definition at line 785 of file X86Subtarget.h.
References canExtendTo512DQ(), and hasAVX512().
Referenced by llvm::X86TTIImpl::areFunctionArgsABICompatible(), combineConcatVectorOps(), combineExtSetcc(), combineTruncateWithSat(), combineVectorSignBitsTruncation(), combineVectorSizedSetCCEquality(), combineX86ShuffleChain(), llvm::X86TTIImpl::getCastInstrCost(), llvm::X86TargetLowering::getVectorTypeBreakdownForCallingConv(), handleMaskRegisterForCallingConv(), SplitOpsAndApply(), useBWIRegs(), and llvm::X86TargetLowering::X86TargetLowering().
useBWIRegs()
bool llvm::X86Subtarget::useBWIRegs () const inline
Definition at line 789 of file X86Subtarget.h.
References hasBWI(), and useAVX512Regs().
Referenced by combineConcatVectorOps(), combineSubToSubus(), lower1BitShuffle(), SplitOpsAndApply(), and llvm::X86TargetLowering::X86TargetLowering().
useGLMDivSqrtCosts()
bool llvm::X86Subtarget::useGLMDivSqrtCosts () const inline
Definition at line 762 of file X86Subtarget.h.
References UseGLMDivSqrtCosts.
Referenced by llvm::X86TTIImpl::getArithmeticInstrCost(), and llvm::X86TTIImpl::getTypeBasedIntrinsicInstrCost().
useIndirectThunkBranches()
bool llvm::X86Subtarget::useIndirectThunkBranches () const inline
Definition at line 757 of file X86Subtarget.h.
References useLVIControlFlowIntegrity(), and useRetpolineIndirectBranches().
Referenced by llvm::X86TargetLowering::areJTsAllowed(), and enableIndirectBrExpand().
useIndirectThunkCalls()
bool llvm::X86Subtarget::useIndirectThunkCalls () const inline
Definition at line 754 of file X86Subtarget.h.
References useLVIControlFlowIntegrity(), and useRetpolineIndirectCalls().
Referenced by llvm::X86FrameLowering::adjustForSegmentedStacks().
useLeaForSP()
bool llvm::X86Subtarget::useLeaForSP () const inline
Definition at line 690 of file X86Subtarget.h.
References UseLeaForSP.
useLVIControlFlowIntegrity()
bool llvm::X86Subtarget::useLVIControlFlowIntegrity () const inline
Definition at line 763 of file X86Subtarget.h.
References UseLVIControlFlowIntegrity.
Referenced by getIndirectThunkSymbol(), useIndirectThunkBranches(), and useIndirectThunkCalls().
useLVILoadHardening()
bool llvm::X86Subtarget::useLVILoadHardening () const inline
Definition at line 764 of file X86Subtarget.h.
References UseLVILoadHardening.
useRetpolineExternalThunk()
bool llvm::X86Subtarget::useRetpolineExternalThunk () const inline
Definition at line 749 of file X86Subtarget.h.
References UseRetpolineExternalThunk.
Referenced by getIndirectThunkSymbol().
useRetpolineIndirectBranches()
bool llvm::X86Subtarget::useRetpolineIndirectBranches () const inline
Definition at line 743 of file X86Subtarget.h.
References UseRetpolineIndirectBranches.
Referenced by getIndirectThunkSymbol(), and useIndirectThunkBranches().
useRetpolineIndirectCalls()
bool llvm::X86Subtarget::useRetpolineIndirectCalls () const inline
Definition at line 742 of file X86Subtarget.h.
References UseRetpolineIndirectCalls.
Referenced by getIndirectThunkSymbol(), and useIndirectThunkCalls().
useSoftFloat()
bool llvm::X86Subtarget::useSoftFloat () const inline
Definition at line 800 of file X86Subtarget.h.
References UseSoftFloat.
Referenced by combineFMinNumFMaxNum(), combineFP16_TO_FP(), combineFP_EXTEND(), combineFP_ROUND(), combineSIntToFP(), combineStore(), get64BitArgumentXMMs(), LowerATOMIC_STORE(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::useSoftFloat(), and llvm::X86TargetLowering::X86TargetLowering().
useSpeculativeExecutionSideEffectSuppression()
bool llvm::X86Subtarget::useSpeculativeExecutionSideEffectSuppression () const inline
Definition at line 765 of file X86Subtarget.h.
References UseSpeculativeExecutionSideEffectSuppression.
Member Data Documentation
CallLoweringInfo
std::unique_ptr<CallLowering> llvm::X86Subtarget::CallLoweringInfo protected
GlobalISel related APIs.
Definition at line 486 of file X86Subtarget.h.
Referenced by getCallLowering(), and X86Subtarget().
DeprecatedHasMPX
bool llvm::X86Subtarget::DeprecatedHasMPX = false protected
Deprecated flag for MPX instructions.
Definition at line 370 of file X86Subtarget.h.
DeprecatedUseRetpoline
bool llvm::X86Subtarget::DeprecatedUseRetpoline = false protected
Deprecated flag, query UseRetpolineIndirectCalls and UseRetpolineIndirectBranches instead.
Definition at line 433 of file X86Subtarget.h.
HasADX
bool llvm::X86Subtarget::HasADX = false protected
Processor has ADX instructions.
Definition at line 183 of file X86Subtarget.h.
Referenced by hasADX().
HasAES
bool llvm::X86Subtarget::HasAES = false protected
Target has AES instructions.
Definition at line 109 of file X86Subtarget.h.
Referenced by hasAES().
HasAMXBF16
bool llvm::X86Subtarget::HasAMXBF16 = false protected
Definition at line 408 of file X86Subtarget.h.
Referenced by hasAMXBF16().
HasAMXINT8
bool llvm::X86Subtarget::HasAMXINT8 = false protected
Definition at line 409 of file X86Subtarget.h.
Referenced by hasAMXINT8().
HasAMXTILE
bool llvm::X86Subtarget::HasAMXTILE = false protected
Processor has AMX support.
Definition at line 407 of file X86Subtarget.h.
Referenced by hasAMXTILE().
HasBF16
bool llvm::X86Subtarget::HasBF16 = false protected
Processor has AVX-512 bfloat16 floating-point extensions.
Definition at line 358 of file X86Subtarget.h.
Referenced by hasBF16().
HasBITALG
bool llvm::X86Subtarget::HasBITALG = false protected
Processor has AVX-512 Bit Algorithms instructions.
Definition at line 364 of file X86Subtarget.h.
Referenced by hasBITALG().
HasBMI
bool llvm::X86Subtarget::HasBMI = false protected
Processor has BMI1 instructions.
Definition at line 165 of file X86Subtarget.h.
Referenced by hasBMI().
HasBMI2
bool llvm::X86Subtarget::HasBMI2 = false protected
Processor has BMI2 instructions.
Definition at line 168 of file X86Subtarget.h.
Referenced by hasBMI2().
HasBranchFusion
bool llvm::X86Subtarget::HasBranchFusion = false protected
True if the processor supports branch fusion.
Definition at line 302 of file X86Subtarget.h.
Referenced by hasBranchFusion().
HasBWI
bool llvm::X86Subtarget::HasBWI = false protected
Processor has AVX-512 Byte and Word instructions.
Definition at line 346 of file X86Subtarget.h.
Referenced by hasBWI().
HasCDI
bool llvm::X86Subtarget::HasCDI = false protected
Processor has AVX-512 Conflict Detection Instructions.
Definition at line 337 of file X86Subtarget.h.
Referenced by hasCDI().
HasCLDEMOTE
bool llvm::X86Subtarget::HasCLDEMOTE = false protected
Processor has Cache Line Demote instruction.
Definition at line 204 of file X86Subtarget.h.
Referenced by hasCLDEMOTE().
HasCLFLUSHOPT
bool llvm::X86Subtarget::HasCLFLUSHOPT = false protected
Processor supports Flush Cache Line instruction.
Definition at line 383 of file X86Subtarget.h.
Referenced by hasCLFLUSHOPT().
HasCLWB
bool llvm::X86Subtarget::HasCLWB = false protected
Processor supports Cache Line Write Back instruction.
Definition at line 386 of file X86Subtarget.h.
Referenced by hasCLWB().
HasCLZERO
bool llvm::X86Subtarget::HasCLZERO = false protected
Processor has Cache Line Zero instruction.
Definition at line 201 of file X86Subtarget.h.
Referenced by hasCLZERO().
HasCMov
bool llvm::X86Subtarget::HasCMov = false protected
True if this processor has conditional move instructions (generally pentium pro+).
Definition at line 97 of file X86Subtarget.h.
Referenced by hasCMov().
HasCmpxchg16b
bool llvm::X86Subtarget::HasCmpxchg16b = false protected
True if this processor has the CMPXCHG16B instruction; this is true for most x86-64 chips, but not the first AMD chips.
Definition at line 240 of file X86Subtarget.h.
Referenced by hasCmpxchg16b().
HasCmpxchg8b
bool llvm::X86Subtarget::HasCmpxchg8b = false protected
True if the processor supports CMPXCHG8B.
Definition at line 89 of file X86Subtarget.h.
Referenced by hasCmpxchg8b().
HasDQI
bool llvm::X86Subtarget::HasDQI = false protected
Processor has AVX-512 Doubleword and Quadword instructions.
Definition at line 343 of file X86Subtarget.h.
Referenced by hasDQI().
HasENQCMD
bool llvm::X86Subtarget::HasENQCMD = false protected
Processor supports ENQCMD instructions.
Definition at line 361 of file X86Subtarget.h.
Referenced by hasENQCMD().
HasERI
bool llvm::X86Subtarget::HasERI = false protected
Processor has AVX-512 Exponential and Reciprocal Instructions.
Definition at line 334 of file X86Subtarget.h.
Referenced by hasERI().
HasERMSB
bool llvm::X86Subtarget::HasERMSB = false protected
True if the processor has enhanced REP MOVSB/STOSB.
Definition at line 305 of file X86Subtarget.h.
Referenced by hasERMSB().
HasF16C
bool llvm::X86Subtarget::HasF16C = false protected
Processor has 16-bit floating point conversion instructions.
Definition at line 156 of file X86Subtarget.h.
Referenced by hasF16C().
HasFast11ByteNOP
bool llvm::X86Subtarget::HasFast11ByteNOP = false protected
True if there is no performance penalty for writing NOPs with up to 11 bytes.
Definition at line 266 of file X86Subtarget.h.
HasFast15ByteNOP
bool llvm::X86Subtarget::HasFast15ByteNOP = false protected
True if there is no performance penalty for writing NOPs with up to 15 bytes.
Definition at line 270 of file X86Subtarget.h.
HasFast7ByteNOP
bool llvm::X86Subtarget::HasFast7ByteNOP = false protected
True if there is no performance penalty for writing NOPs with up to 7 bytes.
Definition at line 262 of file X86Subtarget.h.
HasFastBEXTR
bool llvm::X86Subtarget::HasFastBEXTR = false protected
Processor has a single uop BEXTR implementation.
Definition at line 412 of file X86Subtarget.h.
Referenced by hasFastBEXTR().
HasFastGather
bool llvm::X86Subtarget::HasFastGather = false protected
True if gather is reasonably fast.
This is true for Skylake client and all AVX-512 CPUs.
Definition at line 274 of file X86Subtarget.h.
Referenced by hasFastGather().
HasFastHorizontalOps
bool llvm::X86Subtarget::HasFastHorizontalOps = false protected
Try harder to combine to horizontal vector ops if they are fast.
Definition at line 415 of file X86Subtarget.h.
Referenced by hasFastHorizontalOps().
HasFastLZCNT
bool llvm::X86Subtarget::HasFastLZCNT = false protected
True if LZCNT instruction is fast.
Definition at line 293 of file X86Subtarget.h.
Referenced by hasFastLZCNT().
HasFastScalarFSQRT
bool llvm::X86Subtarget::HasFastScalarFSQRT = false protected
True if hardware SQRTSS instruction is at least as fast (latency) as RSQRTSS followed by a Newton-Raphson iteration.
Definition at line 278 of file X86Subtarget.h.
Referenced by hasFastScalarFSQRT().
HasFastScalarShiftMasks
bool llvm::X86Subtarget::HasFastScalarShiftMasks = false protected
Prefer a left/right scalar logical shifts pair over a shift+and pair.
Definition at line 418 of file X86Subtarget.h.
Referenced by hasFastScalarShiftMasks().
HasFastSHLDRotate
bool llvm::X86Subtarget::HasFastSHLDRotate = false protected
True if SHLD based rotate is fast.
Definition at line 296 of file X86Subtarget.h.
Referenced by hasFastSHLDRotate().
HasFastVariableShuffle
bool llvm::X86Subtarget::HasFastVariableShuffle = false protected
True if its preferable to combine to a single shuffle using a variable mask over multiple fixed shuffles.
Definition at line 254 of file X86Subtarget.h.
Referenced by hasFastVariableShuffle().
HasFastVectorFSQRT
bool llvm::X86Subtarget::HasFastVectorFSQRT = false protected
True if hardware SQRTPS/VSQRTPS instructions are at least as fast (throughput) as RSQRTPS/VRSQRTPS followed by a Newton-Raphson iteration.
Definition at line 282 of file X86Subtarget.h.
Referenced by hasFastVectorFSQRT().
HasFastVectorShiftMasks
bool llvm::X86Subtarget::HasFastVectorShiftMasks = false protected
Prefer a left/right vector logical shifts pair over a shift+and pair.
Definition at line 421 of file X86Subtarget.h.
Referenced by hasFastVectorShiftMasks().
HasFMA
bool llvm::X86Subtarget::HasFMA = false protected
Target has 3-operand fused multiply-add.
Definition at line 135 of file X86Subtarget.h.
Referenced by hasFMA().
HasFMA4
bool llvm::X86Subtarget::HasFMA4 = false protected
Target has 4-operand fused multiply-add.
Definition at line 138 of file X86Subtarget.h.
Referenced by hasFMA4().
HasFSGSBase
bool llvm::X86Subtarget::HasFSGSBase = false protected
Processor has FS/GS base insturctions.
Definition at line 159 of file X86Subtarget.h.
Referenced by hasFSGSBase().
HasFXSR
bool llvm::X86Subtarget::HasFXSR = false protected
Target has FXSAVE/FXRESTOR instructions.
Definition at line 113 of file X86Subtarget.h.
Referenced by hasFXSR().
HasGFNI
bool llvm::X86Subtarget::HasGFNI = false protected
Target has Galois Field Arithmetic instructions.
Definition at line 132 of file X86Subtarget.h.
Referenced by hasGFNI().
HasIFMA
bool llvm::X86Subtarget::HasIFMA = false protected
Processor has Integer Fused Multiply Add.
Definition at line 177 of file X86Subtarget.h.
Referenced by hasIFMA().
HasINVPCID
bool llvm::X86Subtarget::HasINVPCID = false protected
Processor supports Invalidate Process-Context Identifier.
Definition at line 377 of file X86Subtarget.h.
Referenced by hasINVPCID().
HasLAHFSAHF
bool llvm::X86Subtarget::HasLAHFSAHF = false protected
Processor has LAHF/SAHF instructions.
Definition at line 195 of file X86Subtarget.h.
Referenced by hasLAHFSAHF().
HasLWP
bool llvm::X86Subtarget::HasLWP = false protected
Target has LWP instructions.
Definition at line 147 of file X86Subtarget.h.
Referenced by hasLWP().
HasLZCNT
bool llvm::X86Subtarget::HasLZCNT = false protected
Processor has LZCNT instruction.
Definition at line 162 of file X86Subtarget.h.
Referenced by hasLZCNT().
HasLZCNTFalseDeps
bool llvm::X86Subtarget::HasLZCNTFalseDeps = false protected
True if LZCNT/TZCNT instructions have a false dependency on the destination register.
Definition at line 250 of file X86Subtarget.h.
Referenced by hasLZCNTFalseDeps().
HasMacroFusion
bool llvm::X86Subtarget::HasMacroFusion = false protected
True if the processor supports macrofusion.
Definition at line 299 of file X86Subtarget.h.
Referenced by hasMacroFusion().
HasMOVBE
bool llvm::X86Subtarget::HasMOVBE = false protected
True if the processor has the MOVBE instruction.
Definition at line 150 of file X86Subtarget.h.
Referenced by hasMOVBE().
HasMOVDIR64B
bool llvm::X86Subtarget::HasMOVDIR64B = false protected
Processor has MOVDIR64B instruction (direct store 64 bytes).
Definition at line 210 of file X86Subtarget.h.
Referenced by hasMOVDIR64B().
HasMOVDIRI
bool llvm::X86Subtarget::HasMOVDIRI = false protected
Processor has MOVDIRI instruction (direct store integer).
Definition at line 207 of file X86Subtarget.h.
Referenced by hasMOVDIRI().
HasMWAITX
bool llvm::X86Subtarget::HasMWAITX = false protected
Processor has MONITORX/MWAITX instructions.
Definition at line 198 of file X86Subtarget.h.
Referenced by hasMWAITX().
HasNOPL
bool llvm::X86Subtarget::HasNOPL = false protected
True if this processor has NOPL instruction (generally pentium pro+).
Definition at line 93 of file X86Subtarget.h.
Referenced by hasNOPL().
HasPCLMUL
bool llvm::X86Subtarget::HasPCLMUL = false protected
Target has carry-less multiplication.
Definition at line 128 of file X86Subtarget.h.
Referenced by hasPCLMUL().
HasPCONFIG
bool llvm::X86Subtarget::HasPCONFIG = false protected
Processor supports PCONFIG instruction.
Definition at line 398 of file X86Subtarget.h.
Referenced by hasPCONFIG().
HasPFI
bool llvm::X86Subtarget::HasPFI = false protected
Processor has AVX-512 PreFetch Instructions.
Definition at line 331 of file X86Subtarget.h.
Referenced by hasPFI().
HasPKU
bool llvm::X86Subtarget::HasPKU = false protected
Processor has PKU extenstions.
Definition at line 352 of file X86Subtarget.h.
Referenced by hasPKU().
HasPOPCNT
bool llvm::X86Subtarget::HasPOPCNT = false protected
True if the processor supports POPCNT.
Definition at line 103 of file X86Subtarget.h.
Referenced by hasPOPCNT().
HasPOPCNTFalseDeps
bool llvm::X86Subtarget::HasPOPCNTFalseDeps = false protected
True if POPCNT instruction has a false dependency on the destination register.
Definition at line 247 of file X86Subtarget.h.
Referenced by hasPOPCNTFalseDeps().
HasPREFETCHWT1
bool llvm::X86Subtarget::HasPREFETCHWT1 = false protected
Processor has Prefetch with intent to Write instruction.
Definition at line 216 of file X86Subtarget.h.
Referenced by hasPREFETCHWT1().
HasPRFCHW
bool llvm::X86Subtarget::HasPRFCHW = false protected
Processor has PRFCHW instructions.
Definition at line 189 of file X86Subtarget.h.
Referenced by hasPRFCHW().
HasPTWRITE
bool llvm::X86Subtarget::HasPTWRITE = false protected
Processor has ptwrite instruction.
Definition at line 213 of file X86Subtarget.h.
Referenced by hasPTWRITE().
HasRDPID
bool llvm::X86Subtarget::HasRDPID = false protected
Processor support RDPID instruction.
Definition at line 392 of file X86Subtarget.h.
Referenced by hasRDPID().
HasRDRAND
bool llvm::X86Subtarget::HasRDRAND = false protected
True if the processor has the RDRAND instruction.
Definition at line 153 of file X86Subtarget.h.
Referenced by hasRDRAND().
HasRDSEED
bool llvm::X86Subtarget::HasRDSEED = false protected
Processor has RDSEED instructions.
Definition at line 192 of file X86Subtarget.h.
Referenced by hasRDSEED().
HasRTM
bool llvm::X86Subtarget::HasRTM = false protected
Processor has RTM instructions.
Definition at line 180 of file X86Subtarget.h.
Referenced by hasRTM().
HasSERIALIZE
bool llvm::X86Subtarget::HasSERIALIZE = false protected
Processor supports SERIALIZE instruction.
Definition at line 401 of file X86Subtarget.h.
Referenced by hasSERIALIZE().
HasSGX
bool llvm::X86Subtarget::HasSGX = false protected
Processor has Software Guard Extensions.
Definition at line 380 of file X86Subtarget.h.
Referenced by hasSGX().
HasSHA
bool llvm::X86Subtarget::HasSHA = false protected
Processor has SHA instructions.
Definition at line 186 of file X86Subtarget.h.
Referenced by hasSHA().
HasSHSTK
bool llvm::X86Subtarget::HasSHSTK = false protected
Processor supports CET SHSTK - Control-Flow Enforcement Technology using Shadow Stack.
Definition at line 374 of file X86Subtarget.h.
Referenced by hasSHSTK().
HasSlowDivide32
bool llvm::X86Subtarget::HasSlowDivide32 = false protected
True if 8-bit divisions are significantly faster than 32-bit divisions and should be used when possible.
Definition at line 286 of file X86Subtarget.h.
Referenced by hasSlowDivide32().
HasSlowDivide64
bool llvm::X86Subtarget::HasSlowDivide64 = false protected
True if 32-bit divides are significantly faster than 64-bit divisions and should be used when possible.
Definition at line 290 of file X86Subtarget.h.
Referenced by hasSlowDivide64().
HasSSE4A
bool llvm::X86Subtarget::HasSSE4A = false protected
True if the processor supports SSE4A instructions.
Definition at line 106 of file X86Subtarget.h.
Referenced by hasSSE4A().
HasSSEUnalignedMem
bool llvm::X86Subtarget::HasSSEUnalignedMem = false protected
True if SSE operations can have unaligned memory operands.
This may require setting a configuration bit in the processor.
Definition at line 236 of file X86Subtarget.h.
Referenced by hasSSEUnalignedMem().
HasTBM
bool llvm::X86Subtarget::HasTBM = false protected
Target has TBM instructions.
Definition at line 144 of file X86Subtarget.h.
Referenced by hasTBM().
HasTSXLDTRK
bool llvm::X86Subtarget::HasTSXLDTRK = false protected
Processor supports TSXLDTRK instruction.
Definition at line 404 of file X86Subtarget.h.
Referenced by hasTSXLDTRK().
HasVAES
bool llvm::X86Subtarget::HasVAES = false protected
Definition at line 110 of file X86Subtarget.h.
Referenced by hasVAES().
HasVBMI
bool llvm::X86Subtarget::HasVBMI = false protected
Processor has VBMI instructions.
Definition at line 171 of file X86Subtarget.h.
Referenced by hasVBMI().
HasVBMI2
bool llvm::X86Subtarget::HasVBMI2 = false protected
Processor has VBMI2 instructions.
Definition at line 174 of file X86Subtarget.h.
Referenced by hasVBMI2().
HasVLX
bool llvm::X86Subtarget::HasVLX = false protected
Processor has AVX-512 Vector Length eXtenstions.
Definition at line 349 of file X86Subtarget.h.
Referenced by hasVLX().
HasVNNI
bool llvm::X86Subtarget::HasVNNI = false protected
Processor has AVX-512 Vector Neural Network Instructions.
Definition at line 355 of file X86Subtarget.h.
Referenced by hasVNNI().
HasVP2INTERSECT
bool llvm::X86Subtarget::HasVP2INTERSECT = false protected
Processor has AVX-512 vp2intersect instructions.
Definition at line 367 of file X86Subtarget.h.
Referenced by hasVP2INTERSECT().
HasVPCLMULQDQ
bool llvm::X86Subtarget::HasVPCLMULQDQ = false protected
Definition at line 129 of file X86Subtarget.h.
Referenced by hasVPCLMULQDQ().
HasVPOPCNTDQ
bool llvm::X86Subtarget::HasVPOPCNTDQ = false protected
Processor has AVX-512 population count Instructions.
Definition at line 340 of file X86Subtarget.h.
Referenced by hasVPOPCNTDQ().
HasWAITPKG
bool llvm::X86Subtarget::HasWAITPKG = false protected
Processor supports WaitPKG instructions.
Definition at line 395 of file X86Subtarget.h.
Referenced by hasWAITPKG().
HasWBNOINVD
bool llvm::X86Subtarget::HasWBNOINVD = false protected
Processor supports Write Back No Invalidate instruction.
Definition at line 389 of file X86Subtarget.h.
Referenced by hasWBNOINVD().
HasX86_64
bool llvm::X86Subtarget::HasX86_64 = false protected
True if the processor supports X86-64 instructions.
Definition at line 100 of file X86Subtarget.h.
HasX87
bool llvm::X86Subtarget::HasX87 = false protected
True if the processor supports X87 instructions.
Definition at line 86 of file X86Subtarget.h.
Referenced by hasX87().
HasXOP
bool llvm::X86Subtarget::HasXOP = false protected
Target has XOP instructions.
Definition at line 141 of file X86Subtarget.h.
Referenced by hasXOP().
HasXSAVE
bool llvm::X86Subtarget::HasXSAVE = false protected
Target has XSAVE instructions.
Definition at line 116 of file X86Subtarget.h.
Referenced by hasXSAVE().
HasXSAVEC
bool llvm::X86Subtarget::HasXSAVEC = false protected
Target has XSAVEC instructions.
Definition at line 122 of file X86Subtarget.h.
Referenced by hasXSAVEC().
HasXSAVEOPT
bool llvm::X86Subtarget::HasXSAVEOPT = false protected
Target has XSAVEOPT instructions.
Definition at line 119 of file X86Subtarget.h.
Referenced by hasXSAVEOPT().
HasXSAVES
bool llvm::X86Subtarget::HasXSAVES = false protected
Target has XSAVES instructions.
Definition at line 125 of file X86Subtarget.h.
Referenced by hasXSAVES().
InsertVZEROUPPER
bool llvm::X86Subtarget::InsertVZEROUPPER = false protected
True if vzeroupper instructions should be inserted after code that uses ymm or zmm registers.
Definition at line 258 of file X86Subtarget.h.
Referenced by insertVZEROUPPER().
InstSelector
std::unique_ptr<InstructionSelector> llvm::X86Subtarget::InstSelector protected
Definition at line 489 of file X86Subtarget.h.
Referenced by getInstructionSelector(), and X86Subtarget().
IsPMADDWDSlow
bool llvm::X86Subtarget::IsPMADDWDSlow = false protected
True if the PMADDWD instruction is slow compared to PMULLD.
Definition at line 226 of file X86Subtarget.h.
Referenced by isPMADDWDSlow().
IsPMULLDSlow
bool llvm::X86Subtarget::IsPMULLDSlow = false protected
True if the PMULLD instruction is slow compared to PMULLW/PMULHW and.
Definition at line 223 of file X86Subtarget.h.
Referenced by isPMULLDSlow().
IsSHLDSlow
bool llvm::X86Subtarget::IsSHLDSlow = false protected
True if SHLD instructions are slow.
Definition at line 219 of file X86Subtarget.h.
Referenced by isSHLDSlow().
IsUAMem16Slow
bool llvm::X86Subtarget::IsUAMem16Slow = false protected
True if unaligned memory accesses of 16-bytes are slow.
Definition at line 229 of file X86Subtarget.h.
Referenced by isUnalignedMem16Slow().
IsUAMem32Slow
bool llvm::X86Subtarget::IsUAMem32Slow = false protected
True if unaligned memory accesses of 32-bytes are slow.
Definition at line 232 of file X86Subtarget.h.
Referenced by isUnalignedMem32Slow().
LEAUsesAG
bool llvm::X86Subtarget::LEAUsesAG = false protected
True if the LEA instruction inputs have to be ready at address generation (AG) time.
Definition at line 317 of file X86Subtarget.h.
Referenced by LEAusesAG().
Legalizer
std::unique_ptr<LegalizerInfo> llvm::X86Subtarget::Legalizer protected
Definition at line 487 of file X86Subtarget.h.
MaxInlineSizeThreshold
unsigned llvm::X86Subtarget::MaxInlineSizeThreshold = 128 protected
Max.
memset / memcpy size that is turned into rep/movs, rep/stos ops.
Definition at line 465 of file X86Subtarget.h.
Referenced by getMaxInlineSizeThreshold().
PadShortFunctions
bool llvm::X86Subtarget::PadShortFunctions = false protected
True if the short functions should be padded to prevent a stall when returning too early.
Definition at line 309 of file X86Subtarget.h.
Referenced by padShortFunctions().
PICStyle
PICStyles::Style llvm::X86Subtarget::PICStyle protected
Which PIC style to use.
Definition at line 75 of file X86Subtarget.h.
Referenced by getPICStyle(), isPICStyleGOT(), isPICStyleRIPRel(), isPICStyleStubPIC(), and setPICStyle().
Prefer128Bit
bool llvm::X86Subtarget::Prefer128Bit = false protected
Indicates target prefers 128 bit instructions.
Definition at line 468 of file X86Subtarget.h.
Prefer256Bit
bool llvm::X86Subtarget::Prefer256Bit = false protected
Indicates target prefers 256 bit instructions.
Definition at line 471 of file X86Subtarget.h.
PreferMaskRegisters
bool llvm::X86Subtarget::PreferMaskRegisters = false protected
Indicates target prefers AVX512 mask registers.
Definition at line 474 of file X86Subtarget.h.
Referenced by preferMaskRegisters().
RegBankInfo
std::unique_ptr<RegisterBankInfo> llvm::X86Subtarget::RegBankInfo protected
Definition at line 488 of file X86Subtarget.h.
Referenced by getRegBankInfo(), and X86Subtarget().
Slow3OpsLEA
bool llvm::X86Subtarget::Slow3OpsLEA = false protected
True if the LEA instruction has all three source operands: base, index, and offset or if the LEA instruction uses base and index registers where the base is EBP, RBP,or R13.
Definition at line 325 of file X86Subtarget.h.
Referenced by slow3OpsLEA().
SlowIncDec
bool llvm::X86Subtarget::SlowIncDec = false protected
True if INC and DEC instructions are slow when writing to flags.
Definition at line 328 of file X86Subtarget.h.
Referenced by slowIncDec().
SlowLEA
bool llvm::X86Subtarget::SlowLEA = false protected
True if the LEA instruction with certain arguments is slow.
Definition at line 320 of file X86Subtarget.h.
Referenced by slowLEA().
SlowTwoMemOps
bool llvm::X86Subtarget::SlowTwoMemOps = false protected
True if two memory operand instructions should use a temporary register instead.
Definition at line 313 of file X86Subtarget.h.
Referenced by slowTwoMemOps().
stackAlignment
Align llvm::X86Subtarget::stackAlignment = Align(4) protected
The minimum alignment known to hold of the stack frame on entry to the function and which must be maintained by every function.
Definition at line 460 of file X86Subtarget.h.
Referenced by getStackAlignment().
TargetTriple
Triple llvm::X86Subtarget::TargetTriple protected
What processor and OS we're targeting.
Definition at line 483 of file X86Subtarget.h.
Referenced by getTargetTriple(), isOSWindows(), isTarget64BitILP32(), isTarget64BitLP64(), isTargetAndroid(), isTargetCOFF(), isTargetCygMing(), isTargetDarwin(), isTargetDragonFly(), isTargetELF(), isTargetFreeBSD(), isTargetFuchsia(), isTargetGlibc(), isTargetKFreeBSD(), isTargetLinux(), isTargetMachO(), isTargetMCU(), isTargetNaCl(), isTargetPS4(), isTargetSolaris(), isTargetWindowsCoreCLR(), isTargetWindowsCygwin(), isTargetWindowsGNU(), isTargetWindowsItanium(), and isTargetWindowsMSVC().
ThreewayBranchProfitable
bool llvm::X86Subtarget::ThreewayBranchProfitable = false protected
Threeway branch is profitable in this subtarget.
Definition at line 477 of file X86Subtarget.h.
Referenced by threewayBranchProfitable().
TM
const TargetMachine& llvm::X86Subtarget::TM protected
Definition at line 77 of file X86Subtarget.h.
Referenced by classifyGlobalFunctionReference(), classifyGlobalReference(), classifyLocalReference(), isLegalToCallImmediateAddr(), isPositionIndependent(), and X86Subtarget().
UseAA
bool llvm::X86Subtarget::UseAA = false protected
Use alias analysis during code generation.
Definition at line 456 of file X86Subtarget.h.
Referenced by useAA().
UseGLMDivSqrtCosts
bool llvm::X86Subtarget::UseGLMDivSqrtCosts = false protected
Use Goldmont specific floating point div/sqrt costs.
Definition at line 480 of file X86Subtarget.h.
Referenced by useGLMDivSqrtCosts().
UseLeaForSP
bool llvm::X86Subtarget::UseLeaForSP = false protected
True if the LEA instruction should be used for adjusting the stack pointer.
This is an optimization for Intel Atom processors.
Definition at line 244 of file X86Subtarget.h.
Referenced by useLeaForSP().
UseLVIControlFlowIntegrity
bool llvm::X86Subtarget::UseLVIControlFlowIntegrity = false protected
Prevent generation of indirect call/branch instructions from memory, and force all indirect call/branch instructions from a register to be preceded by an LFENCE.
Also decompose RET instructions into a POP+LFENCE+JMP sequence.
Definition at line 443 of file X86Subtarget.h.
Referenced by useLVIControlFlowIntegrity().
UseLVILoadHardening
bool llvm::X86Subtarget::UseLVILoadHardening = false protected
Insert LFENCE instructions to prevent data speculatively injected into loads from being used maliciously.
Definition at line 450 of file X86Subtarget.h.
Referenced by useLVILoadHardening().
UseRetpolineExternalThunk
bool llvm::X86Subtarget::UseRetpolineExternalThunk = false protected
When using a retpoline thunk, call an externally provided thunk rather than emitting one inside the compiler.
Definition at line 437 of file X86Subtarget.h.
Referenced by useRetpolineExternalThunk().
UseRetpolineIndirectBranches
bool llvm::X86Subtarget::UseRetpolineIndirectBranches = false protected
Use a retpoline thunk or remove any indirect branch to block speculative execution.
Definition at line 429 of file X86Subtarget.h.
Referenced by useRetpolineIndirectBranches().
UseRetpolineIndirectCalls
bool llvm::X86Subtarget::UseRetpolineIndirectCalls = false protected
Use a retpoline thunk rather than indirect calls to block speculative execution.
Definition at line 425 of file X86Subtarget.h.
Referenced by useRetpolineIndirectCalls().
UseSoftFloat
bool llvm::X86Subtarget::UseSoftFloat = false protected
Use software floating point for code generation.
Definition at line 453 of file X86Subtarget.h.
Referenced by useSoftFloat().
UseSpeculativeExecutionSideEffectSuppression
bool llvm::X86Subtarget::UseSpeculativeExecutionSideEffectSuppression = false protected
Enable Speculative Execution Side Effect Suppression.
Definition at line 446 of file X86Subtarget.h.
Referenced by useSpeculativeExecutionSideEffectSuppression().
X863DNowLevel
X863DNowEnum llvm::X86Subtarget::X863DNowLevel = NoThreeDNow protected
MMX, 3DNow, 3DNow Athlon, or none supported.
Definition at line 83 of file X86Subtarget.h.
Referenced by has3DNow(), has3DNowA(), and hasMMX().
X86ProcFamily
X86ProcFamilyEnum llvm::X86Subtarget::X86ProcFamily = Others protected
X86 processor family: Intel Atom, and others.
Definition at line 72 of file X86Subtarget.h.
Referenced by getProcFamily(), isAtom(), and isSLM().
X86SSELevel
X86SSEEnum llvm::X86Subtarget::X86SSELevel = NoSSE protected
SSE1, SSE2, SSE3, SSSE3, SSE41, SSE42, or none supported.
Definition at line 80 of file X86Subtarget.h.
Referenced by hasAVX(), hasAVX2(), hasAVX512(), hasCMov(), hasSSE1(), hasSSE2(), hasSSE3(), hasSSE41(), hasSSE42(), and hasSSSE3().
The documentation for this class was generated from the following files:
lib/Target/X86/X86Subtarget.h
lib/Target/X86/X86Subtarget.cpp