LLVM: llvm::orc::RemoteObjectLayer< RPCEndpoint > Class Template Reference
llvm::orc::RemoteObjectLayer< RPCEndpoint > Class Template Reference
Base class containing common utilities for RemoteObjectClientLayer and RemoteObjectServerLayer.
#include "llvm/ExecutionEngine/Orc/RemoteObjectLayer.h"
Classes
class RemoteSymbolMaterializer
This class is used as the symbol materializer for JITSymbols returned by RemoteObjectLayerClient/RemoteObjectLayerServer – the materializer knows how to call back to the other RPC endpoint to get the address when requested.
Public Member Functions
RemoteObjectLayer (RPCEndpoint &Remote, std::function< void(Error)> ReportError)
Protected Member Functions
RemoteSymbol nullRemoteSymbol ()
Convenience function for getting a null remote symbol value.
Error teeLog (Error Err)
Creates a StringError that contains a copy of Err's log message, then sends that StringError to ReportError.
Error badRemoteSymbolIdError (RemoteSymbolId Id)
Error badObjectHandleError (ObjHandleT H)
Expected< RemoteSymbol > jitSymbolToRemote (JITSymbol Sym)
Create a RemoteSymbol wrapping the given JITSymbol.
JITSymbol remoteToJITSymbol (Expected< RemoteSymbol > RemoteSymOrErr)
Convert an Expected<RemoteSymbol> to a JITSymbol.
Protected Attributes
RPCEndpoint & Remote
std::function< void(Error)> ReportError
Additional Inherited Members
Public Types inherited from llvm::orc::RemoteObjectLayerAPI
using ObjHandleT = remote::ResourceIdMgr::ResourceId
using BadSymbolHandleError = remote::ResourceNotFound<RemoteSymbolId>
using BadObjectHandleError = remote::ResourceNotFound<ObjHandleT>
Protected Types inherited from llvm::orc::RemoteObjectLayerAPI
using RemoteSymbolId = remote::ResourceIdMgr::ResourceId
using RemoteSymbol = std::pair<RemoteSymbolId, JITSymbolFlags>
Static Protected Attributes inherited from llvm::orc::RemoteObjectLayerAPI
static const ObjHandleT InvalidObjectHandleId = 0
static const RemoteSymbolId NullSymbolId = 0
Detailed Description
template<typename RPCEndpoint>
class llvm::orc::RemoteObjectLayer< RPCEndpoint >
Base class containing common utilities for RemoteObjectClientLayer and RemoteObjectServerLayer.
Definition at line 111 of file RemoteObjectLayer.h.
Constructor & Destructor Documentation
RemoteObjectLayer()
template<typename RPCEndpoint > llvm::orc::RemoteObjectLayer< RPCEndpoint >::RemoteObjectLayer (RPCEndpoint & Remote, std::function< void(Error)> ReportError) inline
Definition at line 114 of file RemoteObjectLayer.h.
References llvm::orc::RemoteObjectLayer< RPCEndpoint >::Remote.
Member Function Documentation
badObjectHandleError()
template<typename RPCEndpoint > Error llvm::orc::RemoteObjectLayer< RPCEndpoint >::badObjectHandleError (ObjHandleT H) inline protected
Definition at line 189 of file RemoteObjectLayer.h.
References H.
badRemoteSymbolIdError()
template<typename RPCEndpoint > Error llvm::orc::RemoteObjectLayer< RPCEndpoint >::badRemoteSymbolIdError (RemoteSymbolId Id) inline protected
Definition at line 185 of file RemoteObjectLayer.h.
jitSymbolToRemote()
template<typename RPCEndpoint > Expected< RemoteSymbol > llvm::orc::RemoteObjectLayer< RPCEndpoint >::jitSymbolToRemote (JITSymbol Sym) inline protected
Create a RemoteSymbol wrapping the given JITSymbol.
Definition at line 195 of file RemoteObjectLayer.h.
References assert(), llvm::JITSymbol::getFlags(), llvm::orc::remote::ResourceIdMgr::getNext(), llvm::orc::RemoteObjectLayer< RPCEndpoint >::nullRemoteSymbol(), llvm::JITSymbol::takeError(), and llvm::orc::RemoteObjectLayer< RPCEndpoint >::teeLog().
nullRemoteSymbol()
template<typename RPCEndpoint > RemoteSymbol llvm::orc::RemoteObjectLayer< RPCEndpoint >::nullRemoteSymbol () inline protected
Convenience function for getting a null remote symbol value.
Definition at line 166 of file RemoteObjectLayer.h.
Referenced by llvm::orc::RemoteObjectLayer< RPCEndpoint >::jitSymbolToRemote(), and llvm::orc::RemoteObjectLayer< RPCEndpoint >::remoteToJITSymbol().
remoteToJITSymbol()
template<typename RPCEndpoint > JITSymbol llvm::orc::RemoteObjectLayer< RPCEndpoint >::remoteToJITSymbol (Expected< RemoteSymbol > RemoteSymOrErr) inline protected
Convert an Expected<RemoteSymbol> to a JITSymbol.
Definition at line 209 of file RemoteObjectLayer.h.
References llvm::orc::RemoteObjectLayer< RPCEndpoint >::nullRemoteSymbol().
Referenced by llvm::orc::RemoteObjectClientLayer< RPCEndpoint >::findSymbol(), and llvm::orc::RemoteObjectClientLayer< RPCEndpoint >::findSymbolIn().
teeLog()
template<typename RPCEndpoint > Error llvm::orc::RemoteObjectLayer< RPCEndpoint >::teeLog (Error Err) inline protected
Creates a StringError that contains a copy of Err's log message, then sends that StringError to ReportError.
This allows us to locally log error messages for errors that will actually be delivered to the remote.
Definition at line 175 of file RemoteObjectLayer.h.
References llvm::Error, llvm::handleErrors(), and llvm::orc::RemoteObjectLayer< RPCEndpoint >::ReportError.
Referenced by llvm::orc::RemoteObjectLayer< RPCEndpoint >::jitSymbolToRemote().
Member Data Documentation
Remote
template<typename RPCEndpoint > RPCEndpoint& llvm::orc::RemoteObjectLayer< RPCEndpoint >::Remote protected
Definition at line 224 of file RemoteObjectLayer.h.
Referenced by llvm::orc::RemoteObjectClientLayer< RPCEndpoint >::RemoteObjectClientLayer(), llvm::orc::RemoteObjectLayer< RPCEndpoint >::RemoteObjectLayer(), and llvm::orc::RemoteObjectServerLayer< BaseLayerT, RPCEndpoint >::RemoteObjectServerLayer().
ReportError
template<typename RPCEndpoint > std::function<void(Error)> llvm::orc::RemoteObjectLayer< RPCEndpoint >::ReportError protected
Definition at line 225 of file RemoteObjectLayer.h.
Referenced by llvm::orc::RemoteObjectLayer< RPCEndpoint >::teeLog().
The documentation for this class was generated from the following file:
include/llvm/ExecutionEngine/Orc/RemoteObjectLayer.h