LLVM: llvm::FieldInit Class Reference
llvm::FieldInit Class Reference
X.Y - Represent a reference to a subfield of a variable.
#include "llvm/TableGen/Record.h"
Public Member Functions
FieldInit (const FieldInit &)=delete
FieldInit & operator= (const FieldInit &)=delete
Init * getRecord () const
StringInit * getFieldName () const
Init * getBit (unsigned Bit) const override
This method is used to return the initializer for the specified bit.
Init * resolveReferences (Resolver &R) const override
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
Init * Fold (Record *CurRec) const
bool isConcrete () const override
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
std::string getAsString () const override
Convert this value to a string form.
Public Member Functions inherited from llvm::TypedInit
TypedInit (const TypedInit &)=delete
TypedInit & operator= (const TypedInit &)=delete
RecTy * getType () const
Init * getCastTo (RecTy *Ty) const override
If this initializer is convertible to Ty, return an initializer whose type is-a Ty, generating a !cast operation if required.
Init * convertInitializerTo (RecTy *Ty) const override
Convert to an initializer whose type is-a Ty, or return nullptr if this is not possible (this can happen if the initializer's type is convertible to Ty, but there are unresolved references).
Init * convertInitializerBitRange (ArrayRef< unsigned > Bits) const override
This method is used to implement the bitrange selection operator.
Init * convertInitListSlice (ArrayRef< unsigned > Elements) const override
This method is used to implement the list slice selection operator.
RecTy * getFieldType (StringInit *FieldName) const override
This method is used to implement the FieldInit class.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
Init (const Init &)=delete
Init & operator= (const Init &)=delete
virtual ~Init ()=default
virtual bool isComplete () const
This virtual method should be overridden by values that may not be completely specified yet.
void print (raw_ostream &OS) const
Print out this value.
virtual std::string getAsUnquotedString () const
Convert this value to a string form, without adding quote markers.
void dump () const
Debugging method that may be called through a debugger, just invokes print on stderr.
Static Public Member Functions
static bool classof (const Init *I)
static FieldInit * get (Init *R, StringInit *FN)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind : uint8_t {
IK_First , IK_FirstTypedInit , IK_BitInit , IK_BitsInit ,
IK_CodeInit , IK_DagInit , IK_DefInit , IK_FieldInit ,
IK_IntInit , IK_ListInit , IK_FirstOpInit , IK_BinOpInit ,
IK_TernOpInit , IK_UnOpInit , IK_LastOpInit , IK_CondOpInit ,
IK_FoldOpInit , IK_IsAOpInit , IK_StringInit , IK_VarInit ,
IK_VarListElementInit , IK_VarBitInit , IK_VarDefInit , IK_LastTypedInit ,
IK_UnsetInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T, uint8_t Opc=0)
Protected Member Functions inherited from llvm::Init
Init (InitKind K, uint8_t Opc=0)
Protected Attributes inherited from llvm::Init
uint8_t Opc
Detailed Description
X.Y - Represent a reference to a subfield of a variable.
Definition at line 1264 of file Record.h.
Constructor & Destructor Documentation
FieldInit()
llvm::FieldInit::FieldInit (const FieldInit &) delete
Member Function Documentation
classof()
static bool llvm::FieldInit::classof (const Init * I) inline static
Definition at line 1284 of file Record.h.
References I, and llvm::Init::IK_FieldInit.
Fold()
Init * FieldInit::Fold (Record * CurRec) const
Definition at line 1766 of file Record.cpp.
References llvm::Init::getAsString(), llvm::StringInit::getAsUnquotedString(), llvm::Record::getLoc(), and llvm::PrintFatalError().
get()
FieldInit * FieldInit::get (Init * R, StringInit * FN) static
Definition at line 1742 of file Record.cpp.
References Allocator, and I.
Referenced by resolveReferences().
getAsString()
std::string llvm::FieldInit::getAsString () const inline override virtual
Convert this value to a string form.
Implements llvm::Init.
Definition at line 1299 of file Record.h.
References llvm::Init::getAsString(), llvm::StringInit::getValue(), and llvm::StringRef::str().
getBit()
Init * FieldInit::getBit (unsigned Bit) const override virtual
This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 1753 of file Record.cpp.
References llvm::BitRecTy::get(), llvm::VarBitInit::get(), and llvm::TypedInit::getType().
getFieldName()
StringInit * llvm::FieldInit::getFieldName () const inline
Definition at line 1291 of file Record.h.
getRecord()
Init * llvm::FieldInit::getRecord () const inline
Definition at line 1290 of file Record.h.
isConcrete()
bool FieldInit::isConcrete () const override virtual
Is this a concrete and fully resolved value without any references or stuck operations? Unset values are concrete.
Reimplemented from llvm::Init.
Definition at line 1781 of file Record.cpp.
operator=()
FieldInit & llvm::FieldInit::operator= (const FieldInit &) delete
resolveReferences()
Init * FieldInit::resolveReferences (Resolver & R) const override virtual
This method is used by classes that refer to other variables which may not be defined at the time the expression is formed.
If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1759 of file Record.cpp.
References get(), and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
include/llvm/TableGen/Record.h
lib/TableGen/Record.cpp