LLVM: llvm::MCELFStreamer Class Reference
llvm::MCELFStreamer Class Reference
#include "llvm/MC/MCELFStreamer.h"
Public Member Functions
MCELFStreamer (MCContext &Context, std::unique_ptr< MCAsmBackend > TAB, std::unique_ptr< MCObjectWriter > OW, std::unique_ptr< MCCodeEmitter > Emitter)
~MCELFStreamer () override=default
void reset () override
state management
Public Member Functions inherited from llvm::MCObjectStreamer
void reset () override
state management
bool isIntegratedAssemblerRequired () const override
Object streamers require the integrated assembler.
void emitFrames (MCAsmBackend *MAB)
void emitCFISections (bool EH, bool Debug) override
MCFragment * getCurrentFragment () const
void insert (MCFragment *F)
MCDataFragment * getOrCreateDataFragment (const MCSubtargetInfo *STI=nullptr)
Get a data fragment to write into, creating a new one if the current fragment is not a data fragment.
void visitUsedSymbol (const MCSymbol &Sym) override
void flushPendingLabels ()
Create a data fragment for any pending labels across all Sections and Subsections.
MCAssembler & getAssembler ()
MCAssembler * getAssemblerPtr () override
void emitLabel (MCSymbol *Symbol, SMLoc Loc=SMLoc()) override
Emit a label for Symbol into the current section.
void emitAssignment (MCSymbol *Symbol, const MCExpr *Value) override
Emit an assignment of Value to Symbol.
void emitValueImpl (const MCExpr *Value, unsigned Size, SMLoc Loc=SMLoc()) override
Emit the expression Value into the output as a native integer of the given Size bytes.
void emitULEB128Value (const MCExpr *Value) override
void emitSLEB128Value (const MCExpr *Value) override
void emitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol) override
Emit an weak reference from Alias to Symbol.
void changeSection (MCSection *Section, const MCExpr *Subsection) override
Update streamer for a new active section.
void emitInstruction (const MCInst &Inst, const MCSubtargetInfo &STI) override
Emit the given Instruction into the current section.
void emitBundleAlignMode (unsigned AlignPow2) override
Set the bundle alignment mode from now on in the section.
void emitBundleLock (bool AlignToEnd) override
The following instructions are a bundle-locked group.
void emitBundleUnlock () override
Ends a bundle-locked group.
void emitBytes (StringRef Data) override
Emit the bytes in Data into the output.
void emitValueToAlignment (unsigned ByteAlignment, int64_t Value=0, unsigned ValueSize=1, unsigned MaxBytesToEmit=0) override
Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
void emitCodeAlignment (unsigned ByteAlignment, unsigned MaxBytesToEmit=0) override
Emit nops until the byte alignment ByteAlignment is reached.
void emitValueToOffset (const MCExpr *Offset, unsigned char Value, SMLoc Loc) override
Emit some number of copies of Value until the byte offset Offset is reached.
void emitDwarfLocDirective (unsigned FileNo, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator, StringRef FileName) override
This implements the DWARF2 '.loc fileno lineno ...' assembler directive.
void emitDwarfAdvanceLineAddr (int64_t LineDelta, const MCSymbol *LastLabel, const MCSymbol *Label, unsigned PointerSize)
void emitDwarfAdvanceFrameAddr (const MCSymbol *LastLabel, const MCSymbol *Label)
void emitCVLocDirective (unsigned FunctionId, unsigned FileNo, unsigned Line, unsigned Column, bool PrologueEnd, bool IsStmt, StringRef FileName, SMLoc Loc) override
This implements the CodeView '.cv_loc' assembler directive.
void emitCVLinetableDirective (unsigned FunctionId, const MCSymbol *Begin, const MCSymbol *End) override
This implements the CodeView '.cv_linetable' assembler directive.
void emitCVInlineLinetableDirective (unsigned PrimaryFunctionId, unsigned SourceFileId, unsigned SourceLineNum, const MCSymbol *FnStartSym, const MCSymbol *FnEndSym) override
This implements the CodeView '.cv_inline_linetable' assembler directive.
void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * > > Ranges, StringRef FixedSizePortion) override
This implements the CodeView '.cv_def_range' assembler directive.
void emitCVStringTableDirective () override
This implements the CodeView '.cv_stringtable' assembler directive.
void emitCVFileChecksumsDirective () override
This implements the CodeView '.cv_filechecksums' assembler directive.
void emitCVFileChecksumOffsetDirective (unsigned FileNo) override
This implements the CodeView '.cv_filechecksumoffset' assembler directive.
void emitDTPRel32Value (const MCExpr *Value) override
Emit the expression Value into the output as a dtprel (32-bit DTP relative) value.
void emitDTPRel64Value (const MCExpr *Value) override
Emit the expression Value into the output as a dtprel (64-bit DTP relative) value.
void emitTPRel32Value (const MCExpr *Value) override
Emit the expression Value into the output as a tprel (32-bit TP relative) value.
void emitTPRel64Value (const MCExpr *Value) override
Emit the expression Value into the output as a tprel (64-bit TP relative) value.
void emitGPRel32Value (const MCExpr *Value) override
Emit the expression Value into the output as a gprel32 (32-bit GP relative) value.
void emitGPRel64Value (const MCExpr *Value) override
Emit the expression Value into the output as a gprel64 (64-bit GP relative) value.
Optional< std::pair< bool, std::string > > emitRelocDirective (const MCExpr &Offset, StringRef Name, const MCExpr *Expr, SMLoc Loc, const MCSubtargetInfo &STI) override
Record a relocation described by the .reloc directive.
void emitFill (const MCExpr &NumBytes, uint64_t FillValue, SMLoc Loc=SMLoc()) override
Emit Size bytes worth of the value specified by FillValue.
void emitFill (const MCExpr &NumValues, int64_t Size, int64_t Expr, SMLoc Loc=SMLoc()) override
Emit NumValues copies of Size bytes.
void emitFileDirective (StringRef Filename) override
Switch to a new logical file.
void emitAddrsig () override
void emitAddrsigSym (const MCSymbol *Sym) override
void finishImpl () override
Streamer specific finalization.
void emitAbsoluteSymbolDiff (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) override
Emit the absolute difference between two symbols if possible.
void emitAbsoluteSymbolDiffAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo) override
Emit the absolute difference between two symbols encoded with ULEB128.
bool mayHaveInstructions (MCSection &Sec) const override
void emitFill (uint64_t NumBytes, uint8_t FillValue)
Emit NumBytes bytes worth of the value specified by FillValue.
virtual void emitFill (const MCExpr &NumBytes, uint64_t FillValue, SMLoc Loc=SMLoc())
Emit Size bytes worth of the value specified by FillValue.
virtual void emitFill (const MCExpr &NumValues, int64_t Size, int64_t Expr, SMLoc Loc=SMLoc())
Emit NumValues copies of Size bytes.
Public Member Functions inherited from llvm::MCStreamer
MCStreamer (const MCStreamer &)=delete
MCStreamer & operator= (const MCStreamer &)=delete
virtual ~MCStreamer ()
void visitUsedExpr (const MCExpr &Expr)
void setTargetStreamer (MCTargetStreamer *TS)
MCContext & getContext () const
void setUseAssemblerInfoForParsing (bool v)
bool getUseAssemblerInfoForParsing ()
MCTargetStreamer * getTargetStreamer ()
void setAllowAutoPadding (bool v)
bool getAllowAutoPadding () const
WinEH::FrameInfo * EnsureValidWinFrameInfo (SMLoc Loc)
Retreive the current frame info if one is available and it is not yet closed.
unsigned getNumFrameInfos ()
ArrayRef< MCDwarfFrameInfo > getDwarfFrameInfos () const
bool hasUnfinishedDwarfFrameInfo ()
unsigned getNumWinFrameInfos ()
ArrayRef< std::unique_ptr< WinEH::FrameInfo > > getWinFrameInfos () const
void generateCompactUnwindEncodings (MCAsmBackend *MAB)
unsigned emitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum=None, Optional< StringRef > Source=None, unsigned CUID=0)
Associate a filename with a specified logical file number.
virtual Expected< unsigned > tryEmitDwarfFileDirective (unsigned FileNo, StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum=None, Optional< StringRef > Source=None, unsigned CUID=0)
Associate a filename with a specified logical file number.
virtual void emitDwarfFile0Directive (StringRef Directory, StringRef Filename, Optional< MD5::MD5Result > Checksum, Optional< StringRef > Source, unsigned CUID=0)
Specify the "root" file of the compilation, using the ".file 0" extension.
virtual void emitCFIBKeyFrame ()
virtual bool EmitCVFileDirective (unsigned FileNo, StringRef Filename, ArrayRef< uint8_t > Checksum, unsigned ChecksumKind)
Associate a filename with a specified logical file number, and also specify that file's checksum information.
virtual bool EmitCVFuncIdDirective (unsigned FunctionId)
Introduces a function id for use with .cv_loc.
virtual bool EmitCVInlineSiteIdDirective (unsigned FunctionId, unsigned IAFunc, unsigned IAFile, unsigned IALine, unsigned IACol, SMLoc Loc)
Introduces an inline call site id for use with .cv_loc.
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * > > Ranges, codeview::DefRangeRegisterRelHeader DRHdr)
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * > > Ranges, codeview::DefRangeSubfieldRegisterHeader DRHdr)
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * > > Ranges, codeview::DefRangeRegisterHeader DRHdr)
virtual void emitCVDefRangeDirective (ArrayRef< std::pair< const MCSymbol *, const MCSymbol * > > Ranges, codeview::DefRangeFramePointerRelHeader DRHdr)
virtual void EmitCVFPOData (const MCSymbol *ProcSym, SMLoc Loc={})
This implements the CodeView '.cv_fpo_data' assembler directive.
virtual MCSymbol * getDwarfLineTableSymbol (unsigned CUID)
void emitCFIStartProc (bool IsSimple, SMLoc Loc=SMLoc())
void emitCFIEndProc ()
virtual void emitCFIDefCfa (int64_t Register, int64_t Offset)
virtual void emitCFIDefCfaOffset (int64_t Offset)
virtual void emitCFIDefCfaRegister (int64_t Register)
virtual void emitCFIOffset (int64_t Register, int64_t Offset)
virtual void emitCFIPersonality (const MCSymbol *Sym, unsigned Encoding)
virtual void emitCFILsda (const MCSymbol *Sym, unsigned Encoding)
virtual void emitCFIRememberState ()
virtual void emitCFIRestoreState ()
virtual void emitCFISameValue (int64_t Register)
virtual void emitCFIRestore (int64_t Register)
virtual void emitCFIRelOffset (int64_t Register, int64_t Offset)
virtual void emitCFIAdjustCfaOffset (int64_t Adjustment)
virtual void emitCFIEscape (StringRef Values)
virtual void emitCFIReturnColumn (int64_t Register)
virtual void emitCFIGnuArgsSize (int64_t Size)
virtual void emitCFISignalFrame ()
virtual void emitCFIUndefined (int64_t Register)
virtual void emitCFIRegister (int64_t Register1, int64_t Register2)
virtual void emitCFIWindowSave ()
virtual void emitCFINegateRAState ()
virtual void EmitWinCFIStartProc (const MCSymbol *Symbol, SMLoc Loc=SMLoc())
virtual void EmitWinCFIEndProc (SMLoc Loc=SMLoc())
virtual void EmitWinCFIFuncletOrFuncEnd (SMLoc Loc=SMLoc())
This is used on platforms, such as Windows on ARM64, that require function or funclet sizes to be emitted in .xdata before the End marker is emitted for the frame.
virtual void EmitWinCFIStartChained (SMLoc Loc=SMLoc())
virtual void EmitWinCFIEndChained (SMLoc Loc=SMLoc())
virtual void EmitWinCFIPushReg (MCRegister Register, SMLoc Loc=SMLoc())
virtual void EmitWinCFISetFrame (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void EmitWinCFIAllocStack (unsigned Size, SMLoc Loc=SMLoc())
virtual void EmitWinCFISaveReg (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void EmitWinCFISaveXMM (MCRegister Register, unsigned Offset, SMLoc Loc=SMLoc())
virtual void EmitWinCFIPushFrame (bool Code, SMLoc Loc=SMLoc())
virtual void EmitWinCFIEndProlog (SMLoc Loc=SMLoc())
virtual void EmitWinEHHandler (const MCSymbol *Sym, bool Unwind, bool Except, SMLoc Loc=SMLoc())
virtual void EmitWinEHHandlerData (SMLoc Loc=SMLoc())
MCSection * getAssociatedPDataSection (const MCSection *TextSec)
Get the .pdata section used for the given section.
MCSection * getAssociatedXDataSection (const MCSection *TextSec)
Get the .xdata section used for the given section.
virtual void emitSyntaxDirective ()
void emitRawText (const Twine &String)
If this file is backed by a assembly streamer, this dumps the specified string in the output .s file.
void Finish ()
Finish emission of machine code.
virtual bool isVerboseAsm () const
Return true if this streamer supports verbose assembly and if it is enabled.
virtual bool hasRawTextSupport () const
Return true if this asm streamer supports emitting unformatted text to the .s file with EmitRawText.
virtual void AddComment (const Twine &T, bool EOL=true)
Add a textual comment.
virtual raw_ostream & GetCommentOS ()
Return a raw_ostream that comments can be written to.
virtual void emitRawComment (const Twine &T, bool TabPrefix=true)
Print T and prefix it with the comment string (normally #) and optionally a tab.
virtual void addExplicitComment (const Twine &T)
Add explicit comment T.
virtual void emitExplicitComments ()
Emit added explicit comments.
virtual void AddBlankLine ()
AddBlankLine - Emit a blank line to a .s file to pretty it up.
MCSectionSubPair getCurrentSection () const
Return the current section that the streamer is emitting code to.
MCSection * getCurrentSectionOnly () const
MCSectionSubPair getPreviousSection () const
Return the previous section that the streamer is emitting code to.
unsigned GetSymbolOrder (const MCSymbol *Sym) const
Returns an index to represent the order a symbol was emitted in.
void PushSection ()
Save the current and previous section on the section stack.
bool PopSection ()
Restore the current and previous section from the section stack.
bool SubSection (const MCExpr *Subsection)
virtual void SwitchSection (MCSection *Section, const MCExpr *Subsection=nullptr)
Set the current section where code is being emitted to Section.
void SwitchSectionNoChange (MCSection *Section, const MCExpr *Subsection=nullptr)
Set the current section where code is being emitted to Section.
MCSymbol * endSection (MCSection *Section)
void AssignFragment (MCSymbol *Symbol, MCFragment *Fragment)
Sets the symbol's section.
virtual void emitEHSymAttributes (const MCSymbol *Symbol, MCSymbol *EHSymbol)
virtual void emitLinkerOptions (ArrayRef< std::string > Kind)
Emit the given list Options of strings as linker options into the output.
virtual void emitDataRegion (MCDataRegionType Kind)
Note in the output the specified region Kind.
virtual void emitVersionMin (MCVersionMinType Type, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
Specify the Mach-O minimum deployment target version.
virtual void emitBuildVersion (unsigned Platform, unsigned Major, unsigned Minor, unsigned Update, VersionTuple SDKVersion)
Emit/Specify Mach-O build version command.
void emitVersionForTarget (const Triple &Target, const VersionTuple &SDKVersion)
virtual void BeginCOFFSymbolDef (const MCSymbol *Symbol)
Start emitting COFF symbol definition.
virtual void EmitCOFFSymbolStorageClass (int StorageClass)
Emit the storage class of the symbol.
virtual void EmitCOFFSymbolType (int Type)
Emit the type of the symbol.
virtual void EndCOFFSymbolDef ()
Marks the end of the symbol definition.
virtual void EmitCOFFSafeSEH (MCSymbol const *Symbol)
virtual void EmitCOFFSymbolIndex (MCSymbol const *Symbol)
Emits the symbol table index of a Symbol into the current section.
virtual void EmitCOFFSectionIndex (MCSymbol const *Symbol)
Emits a COFF section index.
virtual void EmitCOFFSecRel32 (MCSymbol const *Symbol, uint64_t Offset)
Emits a COFF section relative relocation.
virtual void EmitCOFFImgRel32 (MCSymbol const *Symbol, int64_t Offset)
Emits a COFF image relative relocation.
virtual void emitXCOFFLocalCommonSymbol (MCSymbol *LabelSym, uint64_t Size, MCSymbol *CsectSym, unsigned ByteAlignment)
Emits an lcomm directive with XCOFF csect information.
virtual void emitXCOFFSymbolLinkageWithVisibility (MCSymbol *Symbol, MCSymbolAttr Linkage, MCSymbolAttr Visibility)
Emit a symbol's linkage and visibilty with a linkage directive for XCOFF.
virtual void emitXCOFFRenameDirective (const MCSymbol *Name, StringRef Rename)
Emit a XCOFF .rename directive which creates a synonym for an illegal or undesirable name.
virtual void emitLOHDirective (MCLOHType Kind, const MCLOHArgs &Args)
Emit a Linker Optimization Hint (LOH) directive.
virtual void emitBinaryData (StringRef Data)
Functionally identical to EmitBytes.
void emitValue (const MCExpr *Value, unsigned Size, SMLoc Loc=SMLoc())
virtual void emitIntValue (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers.
virtual void emitIntValueInHex (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers & prints in Hex format for certain modes.
void emitInt8 (uint64_t Value)
void emitInt16 (uint64_t Value)
void emitInt32 (uint64_t Value)
void emitInt64 (uint64_t Value)
virtual void emitIntValueInHexWithPadding (uint64_t Value, unsigned Size)
Special case of EmitValue that avoids the client having to pass in a MCExpr for constant integers & prints in Hex format for certain modes, pads the field with leading zeros to Size width.
void emitULEB128IntValue (uint64_t Value, unsigned PadTo=0)
Special case of EmitULEB128Value that avoids the client having to pass in a MCExpr for constant integers.
void emitSLEB128IntValue (int64_t Value)
Special case of EmitSLEB128Value that avoids the client having to pass in a MCExpr for constant integers.
void emitSymbolValue (const MCSymbol *Sym, unsigned Size, bool IsSectionRelative=false)
Special case of EmitValue that avoids the client having to pass in a MCExpr for MCSymbols.
void emitFill (uint64_t NumBytes, uint8_t FillValue)
Emit NumBytes bytes worth of the value specified by FillValue.
void emitZeros (uint64_t NumBytes)
Emit NumBytes worth of zeros.
MCStreamer Interface
void InitSections (bool NoExecStack) override
Create the default sections and set the initial one.
void changeSection (MCSection *Section, const MCExpr *Subsection) override
Update streamer for a new active section.
void emitLabel (MCSymbol *Symbol, SMLoc Loc=SMLoc()) override
Emit a label for Symbol into the current section.
void emitLabelAtPos (MCSymbol *Symbol, SMLoc Loc, MCFragment *F, uint64_t Offset) override
void emitAssemblerFlag (MCAssemblerFlag Flag) override
Note in the output the specified Flag.
void emitThumbFunc (MCSymbol *Func) override
Note in the output that the specified Func is a Thumb mode function (ARM target only).
void emitWeakReference (MCSymbol *Alias, const MCSymbol *Symbol) override
Emit an weak reference from Alias to Symbol.
bool emitSymbolAttribute (MCSymbol *Symbol, MCSymbolAttr Attribute) override
Add the given Attribute to Symbol.
void emitSymbolDesc (MCSymbol *Symbol, unsigned DescValue) override
Set the DescValue for the Symbol.
void emitCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
Emit a common symbol.
void emitELFSize (MCSymbol *Symbol, const MCExpr *Value) override
Emit an ELF .size directive.
void emitELFSymverDirective (StringRef AliasName, const MCSymbol *Aliasee) override
Emit an ELF .symver directive.
void emitLocalCommonSymbol (MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment) override
Emit a local common (.lcomm) symbol.
void emitZerofill (MCSection *Section, MCSymbol *Symbol=nullptr, uint64_t Size=0, unsigned ByteAlignment=0, SMLoc L=SMLoc()) override
Emit the zerofill section and an optional symbol.
void emitTBSSSymbol (MCSection *Section, MCSymbol *Symbol, uint64_t Size, unsigned ByteAlignment=0) override
Emit a thread local bss (.tbss) symbol.
void emitValueImpl (const MCExpr *Value, unsigned Size, SMLoc Loc=SMLoc()) override
Emit the expression Value into the output as a native integer of the given Size bytes.
void emitIdent (StringRef IdentString) override
Emit the "identifiers" directive.
void emitValueToAlignment (unsigned, int64_t, unsigned, unsigned) override
Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
void emitCGProfileEntry (const MCSymbolRefExpr *From, const MCSymbolRefExpr *To, uint64_t Count) override
void finishImpl () override
Streamer specific finalization.
void emitBundleAlignMode (unsigned AlignPow2) override
Set the bundle alignment mode from now on in the section.
void emitBundleLock (bool AlignToEnd) override
The following instructions are a bundle-locked group.
void emitBundleUnlock () override
Ends a bundle-locked group.
Additional Inherited Members
Protected Member Functions inherited from llvm::MCObjectStreamer
MCObjectStreamer (MCContext &Context, std::unique_ptr< MCAsmBackend > TAB, std::unique_ptr< MCObjectWriter > OW, std::unique_ptr< MCCodeEmitter > Emitter)
~MCObjectStreamer ()
bool changeSectionImpl (MCSection *Section, const MCExpr *Subsection)
void addPendingLabel (MCSymbol *label)
Assign a label to the current Section and Subsection even though a fragment is not yet present.
void flushPendingLabels (MCFragment *F, uint64_t FOffset=0)
If any labels have been emitted but not assigned fragments in the current Section and Subsection, ensure that they get assigned, either to fragment F if possible or to a new data fragment.
Protected Member Functions inherited from llvm::MCStreamer
MCStreamer (MCContext &Ctx)
WinEH::FrameInfo * getCurrentWinFrameInfo ()
virtual void EmitWindowsUnwindTables ()
virtual void emitRawTextImpl (StringRef String)
EmitRawText - If this file is backed by an assembly streamer, this dumps the specified string in the output .s file.
bool checkCVLocSection (unsigned FuncId, unsigned FileNo, SMLoc Loc)
Returns true if the the .cv_loc directive is in the right section.
Detailed Description
Definition at line 23 of file MCELFStreamer.h.
Constructor & Destructor Documentation
MCELFStreamer()
MCELFStreamer::MCELFStreamer (MCContext & Context, std::unique_ptr< MCAsmBackend > TAB, std::unique_ptr< MCObjectWriter > OW, std::unique_ptr< MCCodeEmitter > Emitter)
Definition at line 41 of file MCELFStreamer.cpp.
~MCELFStreamer()
llvm::MCELFStreamer::~MCELFStreamer () override default
Member Function Documentation
changeSection()
void MCELFStreamer::changeSection (MCSection * , const MCExpr *) override virtual
Update streamer for a new active section.
This is called by PopSection and SwitchSection, if the current section changes.
Reimplemented from llvm::MCStreamer.
Definition at line 146 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::changeSectionImpl(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::report_fatal_error(), and setSectionAlignmentForBundling().
emitAssemblerFlag()
void MCELFStreamer::emitAssemblerFlag (MCAssemblerFlag Flag) override virtual
Note in the output the specified Flag.
Reimplemented from llvm::MCStreamer.
Definition at line 120 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getBackend(), llvm::MCAsmBackend::handleAssemblerFlag(), llvm_unreachable, llvm::MCAF_Code16, llvm::MCAF_Code32, llvm::MCAF_Code64, llvm::MCAF_SubsectionsViaSymbols, llvm::MCAF_SyntaxUnified, and llvm::MCAssembler::setSubsectionsViaSymbols().
emitBundleAlignMode()
void MCELFStreamer::emitBundleAlignMode (unsigned AlignPow2) override virtual
Set the bundle alignment mode from now on in the section.
The argument is the power of 2 to which the alignment is set. The value 0 means turn the bundle alignment off.
Reimplemented from llvm::MCStreamer.
Definition at line 604 of file MCELFStreamer.cpp.
References assert(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getBundleAlignSize(), llvm::report_fatal_error(), and llvm::MCAssembler::setBundleAlignSize().
emitBundleLock()
void MCELFStreamer::emitBundleLock (bool AlignToEnd) override virtual
The following instructions are a bundle-locked group.
Parameters
AlignToEnd - If true, the bundle-locked group will be aligned to the end of a bundle.
Reimplemented from llvm::MCStreamer.
Definition at line 614 of file MCELFStreamer.cpp.
References llvm::MCSection::BundleLocked, llvm::MCSection::BundleLockedAlignToEnd, DF, llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getCurrentSectionOnly(), and llvm::report_fatal_error().
emitBundleUnlock()
void MCELFStreamer::emitBundleUnlock () override virtual
Ends a bundle-locked group.
Reimplemented from llvm::MCStreamer.
Definition at line 635 of file MCELFStreamer.cpp.
References assert(), llvm::MCSection::BundleLockedAlignToEnd, DF, llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::MCObjectStreamer::getOrCreateDataFragment(), llvm::MCSection::NotBundleLocked, llvm::report_fatal_error(), and llvm::MCEncodedFragment::setAlignToBundleEnd().
emitCGProfileEntry()
void MCELFStreamer::emitCGProfileEntry (const MCSymbolRefExpr * From, const MCSymbolRefExpr * To, uint64_t Count) override virtual
Reimplemented from llvm::MCStreamer.
Definition at line 360 of file MCELFStreamer.cpp.
References llvm::MCAssembler::CGProfile, From, and llvm::MCObjectStreamer::getAssembler().
emitCommonSymbol()
void MCELFStreamer::emitCommonSymbol (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) override virtual
Emit a common symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the symbol if non-zero. This must be a power of 2.
Implements llvm::MCStreamer.
Definition at line 290 of file MCELFStreamer.cpp.
References llvm::MCConstantExpr::create(), emitLabel(), emitValueToAlignment(), llvm::MCStreamer::emitZeros(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getCurrentSection(), llvm::MCContext::getELFSection(), P, llvm::MCAssembler::registerSymbol(), llvm::report_fatal_error(), llvm::ELF::SHF_ALLOC, llvm::ELF::SHF_WRITE, llvm::ELF::SHT_NOBITS, Size, llvm::ELF::STB_GLOBAL, llvm::ELF::STB_LOCAL, llvm::ELF::STT_OBJECT, and llvm::MCStreamer::SwitchSection().
Referenced by emitLocalCommonSymbol().
emitELFSize()
void MCELFStreamer::emitELFSize (MCSymbol * Symbol, const MCExpr * Value) override virtual
Emit an ELF .size directive.
This corresponds to an assembler statement such as: .size symbol, expression
Reimplemented from llvm::MCStreamer.
Definition at line 323 of file MCELFStreamer.cpp.
emitELFSymverDirective()
void MCELFStreamer::emitELFSymverDirective (StringRef AliasName, const MCSymbol * Aliasee) override virtual
Emit an ELF .symver directive.
This corresponds to an assembler statement such as: .symver _start, foo@SOME_VERSION
Parameters
AliasName - The versioned alias (i.e. "foo@@SOME_VERSION")
Aliasee - The aliased symbol (i.e. "_start")
Reimplemented from llvm::MCStreamer.
Definition at line 327 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::getAssembler(), and llvm::MCAssembler::Symvers.
emitIdent()
void MCELFStreamer::emitIdent (StringRef IdentString) override virtual
Emit the "identifiers" directive.
This implements the '.ident "version foo"' assembler directive.
Reimplemented from llvm::MCStreamer.
Definition at line 366 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::emitBytes(), llvm::MCStreamer::emitInt8(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::getContext(), llvm::MCContext::getELFSection(), llvm::MCStreamer::PopSection(), llvm::MCStreamer::PushSection(), llvm::ELF::SHF_MERGE, llvm::ELF::SHF_STRINGS, llvm::ELF::SHT_PROGBITS, and llvm::MCStreamer::SwitchSection().
emitLabel()
void MCELFStreamer::emitLabel (MCSymbol * Symbol, SMLoc Loc = SMLoc()) override virtual
Emit a label for Symbol into the current section.
This corresponds to an assembler statement such as: foo:
Parameters
Symbol - The symbol to emit. A given symbol should only be emitted as a label once, and symbols emitted as a label should never be used in an assignment.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MipsELFStreamer, and llvm::PPCELFStreamer.
Definition at line 99 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::emitLabel(), llvm::MCStreamer::getCurrentSectionOnly(), llvm::ELF::SHF_TLS, and llvm::ELF::STT_TLS.
Referenced by llvm::MipsELFStreamer::emitCFIEndProcImpl(), llvm::MipsELFStreamer::emitCFILabel(), llvm::MipsELFStreamer::emitCFIStartProcImpl(), emitCommonSymbol(), llvm::AMDGPUTargetELFStreamer::EmitHSAMetadata(), llvm::AMDGPUTargetELFStreamer::EmitHSAMetadata(), llvm::AMDGPUTargetELFStreamer::EmitISAVersion(), llvm::MipsELFStreamer::emitLabel(), llvm::PPCELFStreamer::emitLabel(), and llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol().
emitLabelAtPos()
void MCELFStreamer::emitLabelAtPos (MCSymbol * Symbol, SMLoc Loc, MCFragment * F, uint64_t Offset) override virtual
Reimplemented from llvm::MCObjectStreamer.
Definition at line 109 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::emitLabelAtPos(), F, llvm::MCStreamer::getCurrentSectionOnly(), llvm::ELF::SHF_TLS, and llvm::ELF::STT_TLS.
emitLocalCommonSymbol()
void MCELFStreamer::emitLocalCommonSymbol (MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment) override virtual
Emit a local common (.lcomm) symbol.
Parameters
Symbol - The common symbol to emit.
Size - The size of the common symbol.
ByteAlignment - The alignment of the common symbol in bytes.
Reimplemented from llvm::MCStreamer.
Definition at line 332 of file MCELFStreamer.cpp.
References emitCommonSymbol(), llvm::MCObjectStreamer::getAssembler(), llvm::MCAssembler::registerSymbol(), Size, and llvm::ELF::STB_LOCAL.
emitSymbolAttribute()
bool MCELFStreamer::emitSymbolAttribute (MCSymbol * Symbol, MCSymbolAttr Attribute) override virtual
Add the given Attribute to Symbol.
Implements llvm::MCStreamer.
Definition at line 190 of file MCELFStreamer.cpp.
References CombineSymbolTypes(), llvm::MCObjectStreamer::getAssembler(), llvm_unreachable, llvm::MCSA_AltEntry, llvm::MCSA_Cold, llvm::MCSA_ELF_TypeCommon, llvm::MCSA_ELF_TypeFunction, llvm::MCSA_ELF_TypeGnuUniqueObject, llvm::MCSA_ELF_TypeIndFunction, llvm::MCSA_ELF_TypeNoType, llvm::MCSA_ELF_TypeObject, llvm::MCSA_ELF_TypeTLS, llvm::MCSA_Extern, llvm::MCSA_Global, llvm::MCSA_Hidden, llvm::MCSA_IndirectSymbol, llvm::MCSA_Internal, llvm::MCSA_Invalid, llvm::MCSA_LazyReference, llvm::MCSA_LGlobal, llvm::MCSA_Local, llvm::MCSA_NoDeadStrip, llvm::MCSA_PrivateExtern, llvm::MCSA_Protected, llvm::MCSA_Reference, llvm::MCSA_SymbolResolver, llvm::MCSA_Weak, llvm::MCSA_WeakDefAutoPrivate, llvm::MCSA_WeakDefinition, llvm::MCSA_WeakReference, llvm::MCAssembler::registerSymbol(), llvm::ELF::STB_GLOBAL, llvm::ELF::STB_GNU_UNIQUE, llvm::ELF::STB_LOCAL, llvm::ELF::STB_WEAK, llvm::ELF::STT_FUNC, llvm::ELF::STT_GNU_IFUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_TLS, llvm::ELF::STV_HIDDEN, llvm::ELF::STV_INTERNAL, and llvm::ELF::STV_PROTECTED.
emitSymbolDesc()
void MCELFStreamer::emitSymbolDesc (MCSymbol * Symbol, unsigned DescValue) override virtual
Set the DescValue for the Symbol.
Parameters
Symbol - The symbol to have its n_desc field set.
DescValue - The value to set into the n_desc field.
Reimplemented from llvm::MCStreamer.
Definition at line 684 of file MCELFStreamer.cpp.
References llvm_unreachable.
emitTBSSSymbol()
void MCELFStreamer::emitTBSSSymbol (MCSection * Section, MCSymbol * Symbol, uint64_t Size, unsigned ByteAlignment = 0) override virtual
Emit a thread local bss (.tbss) symbol.
Parameters
Section - The thread local common section.
Symbol - The thread local common symbol to emit.
Size - The size of the symbol.
ByteAlignment - The alignment of the thread local common symbol if non-zero. This must be a power of 2 on some targets.
Reimplemented from llvm::MCStreamer.
Definition at line 694 of file MCELFStreamer.cpp.
References llvm_unreachable.
emitThumbFunc()
void MCELFStreamer::emitThumbFunc (MCSymbol * Func) override virtual
Note in the output that the specified Func is a Thumb mode function (ARM target only).
Reimplemented from llvm::MCStreamer.
Definition at line 680 of file MCELFStreamer.cpp.
References llvm_unreachable.
emitValueImpl()
void MCELFStreamer::emitValueImpl (const MCExpr * Value, unsigned Size, SMLoc Loc = SMLoc()) override virtual
Emit the expression Value into the output as a native integer of the given Size bytes.
This is used to implement assembler directives such as .word, .quad, etc.
Parameters
Value - The value to emit.
Size - The size of the integer (in bytes) to emit. This must match a native machine width.
Loc - The location of the expression for error reporting.
Reimplemented from llvm::MCStreamer.
Reimplemented in llvm::MipsELFStreamer.
Definition at line 342 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::emitValueImpl(), llvm::report_fatal_error(), and Size.
Referenced by llvm::MipsELFStreamer::emitValueImpl().
emitValueToAlignment()
void MCELFStreamer::emitValueToAlignment (unsigned ByteAlignment, int64_t Value, unsigned ValueSize, unsigned MaxBytesToEmit) override virtual
Emit some number of copies of Value until the byte alignment ByteAlignment is reached.
If the number of bytes need to emit for the alignment is not a multiple of ValueSize, then the contents of the emitted fill bytes is undefined.
This used to implement the .align assembler directive.
Parameters
ByteAlignment - The alignment to reach. This must be a power of two on some targets.
Value - The value to use when filling bytes.
ValueSize - The size of the integer (in bytes) to emit for Value. This must match a native machine width.
MaxBytesToEmit - The maximum numbers of bytes to emit, or 0. If the alignment cannot be reached in this many bytes, no bytes are emitted.
Reimplemented from llvm::MCStreamer.
Definition at line 350 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::emitValueToAlignment(), and llvm::report_fatal_error().
Referenced by emitCommonSymbol(), and llvm::HexagonMCELFStreamer::HexagonMCEmitCommonSymbol().
emitWeakReference()
void MCELFStreamer::emitWeakReference (MCSymbol * Alias, const MCSymbol * Symbol) override virtual
Emit an weak reference from Alias to Symbol.
This corresponds to an assembler statement such as: .weakref alias, symbol
Parameters
Alias - The alias that is being created.
Symbol - The symbol being aliased.
Reimplemented from llvm::MCStreamer.
Definition at line 164 of file MCELFStreamer.cpp.
References llvm::MCSymbolRefExpr::create(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getContext(), llvm::MCAssembler::registerSymbol(), llvm::MCSymbol::setVariableValue(), and llvm::MCSymbolRefExpr::VK_WEAKREF.
emitZerofill()
void MCELFStreamer::emitZerofill (MCSection * Section, MCSymbol * Symbol = nullptr, uint64_t Size = 0, unsigned ByteAlignment = 0, SMLoc Loc = SMLoc()) override virtual
Emit the zerofill section and an optional symbol.
Parameters
Section - The zerofill section to create and or to put the symbol
Symbol - The zerofill symbol to emit, if non-NULL.
Size - The size of the zerofill symbol.
ByteAlignment - The alignment of the zerofill symbol if non-zero. This must be a power of 2 on some targets.
Implements llvm::MCStreamer.
Definition at line 688 of file MCELFStreamer.cpp.
References llvm_unreachable.
finishImpl()
void MCELFStreamer::finishImpl () override virtual
Streamer specific finalization.
Reimplemented from llvm::MCStreamer.
Definition at line 669 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::emitFrames(), llvm::MCObjectStreamer::finishImpl(), llvm::MCObjectStreamer::getAssembler(), llvm::MCStreamer::getCurrentSectionOnly(), and setSectionAlignmentForBundling().
InitSections()
void MCELFStreamer::InitSections (bool NoExecStack) override virtual
Create the default sections and set the initial one.
Reimplemented from llvm::MCStreamer.
Definition at line 90 of file MCELFStreamer.cpp.
References llvm::MCObjectStreamer::emitCodeAlignment(), llvm::MCStreamer::getContext(), and llvm::MCStreamer::SwitchSection().
reset()
void llvm::MCELFStreamer::reset () inline override virtual
state management
Reimplemented from llvm::MCStreamer.
Definition at line 32 of file MCELFStreamer.h.
References llvm::MCObjectStreamer::reset().
The documentation for this class was generated from the following files:
include/llvm/MC/MCELFStreamer.h
lib/MC/MCELFStreamer.cpp