LLVM: llvm::orc::MaterializationResponsibility Class Reference
llvm::orc::MaterializationResponsibility Class Reference
Tracks responsibility for materialization, and mediates interactions between MaterializationUnits and JDs.
#include "llvm/ExecutionEngine/Orc/Core.h"
Public Member Functions
MaterializationResponsibility (MaterializationResponsibility &&)=default
MaterializationResponsibility & operator= (MaterializationResponsibility &&)=delete
~MaterializationResponsibility ()
Destruct a MaterializationResponsibility instance.
JITDylib & getTargetJITDylib () const
Returns the target JITDylib that these symbols are being materialized into.
VModuleKey getVModuleKey () const
Returns the VModuleKey for this instance.
const SymbolFlagsMap & getSymbols () const
Returns the symbol flags map for this responsibility instance.
const SymbolStringPtr & getInitializerSymbol () const
Returns the initialization pseudo-symbol, if any.
SymbolNameSet getRequestedSymbols () const
Returns the names of any symbols covered by this MaterializationResponsibility object that have queries pending.
Error notifyResolved (const SymbolMap &Symbols)
Notifies the target JITDylib that the given symbols have been resolved.
Error notifyEmitted ()
Notifies the target JITDylib (and any pending queries on that JITDylib) that all symbols covered by this MaterializationResponsibility instance have been emitted.
Error defineMaterializing (SymbolFlagsMap SymbolFlags)
Attempt to claim responsibility for new definitions.
void defineNonExistent (ArrayRef< SymbolStringPtr > Symbols)
Define the given symbols as non-existent, removing it from the symbol table and notifying any pending queries.
void failMaterialization ()
Notify all not-yet-emitted covered by this MaterializationResponsibility instance that an error has occurred.
void replace (std::unique_ptr< MaterializationUnit > MU)
Transfers responsibility to the given MaterializationUnit for all symbols defined by that MaterializationUnit.
MaterializationResponsibility delegate (const SymbolNameSet &Symbols, VModuleKey NewKey=VModuleKey())
Delegates responsibility for the given symbols to the returned materialization responsibility.
void addDependencies (const SymbolStringPtr &Name, const SymbolDependenceMap &Dependencies)
void addDependenciesForAll (const SymbolDependenceMap &Dependencies)
Add dependencies that apply to all symbols covered by this instance.
Friends
class MaterializationUnit
Detailed Description
Tracks responsibility for materialization, and mediates interactions between MaterializationUnits and JDs.
An instance of this class is passed to MaterializationUnits when their materialize method is called. It allows MaterializationUnits to resolve and emit symbols, or abandon materialization by notifying any unmaterialized symbols of an error.
Definition at line 410 of file Core.h.
Constructor & Destructor Documentation
MaterializationResponsibility()
llvm::orc::MaterializationResponsibility::MaterializationResponsibility (MaterializationResponsibility &&) default
Referenced by delegate().
~MaterializationResponsibility()
llvm::orc::MaterializationResponsibility::~MaterializationResponsibility ()
Destruct a MaterializationResponsibility instance.
In debug mode this asserts that all symbols being tracked have been either emitted or notified of an error.
Definition at line 184 of file Core.cpp.
References assert().
Member Function Documentation
addDependencies()
void llvm::orc::MaterializationResponsibility::addDependencies (const SymbolStringPtr & Name, const SymbolDependenceMap & Dependencies)
Definition at line 310 of file Core.cpp.
References assert(), llvm::dbgs(), LLVM_DEBUG, and Name.
Referenced by llvm::orc::ObjectLinkingLayerJITLinkContext::lookup().
addDependenciesForAll()
void llvm::orc::MaterializationResponsibility::addDependenciesForAll (const SymbolDependenceMap & Dependencies)
Add dependencies that apply to all symbols covered by this instance.
Definition at line 321 of file Core.cpp.
References llvm::dbgs(), and LLVM_DEBUG.
Referenced by llvm::orc::JITSymbolResolverAdapter::lookup().
defineMaterializing()
Error llvm::orc::MaterializationResponsibility::defineMaterializing (SymbolFlagsMap SymbolFlags)
Attempt to claim responsibility for new definitions.
This method can be used to claim responsibility for symbols that are added to a materialization unit during the compilation process (e.g. literal pool symbols). Symbol linkage rules are the same as for symbols that are defined up front: duplicate strong definitions will result in errors. Duplicate weak definitions will be discarded (in which case they will not be added to this responsibility instance).
This method can be used by materialization units that want to add additional symbols at materialization time (e.g. stubs, compile callbacks, metadata).
Definition at line 226 of file Core.cpp.
References llvm::dbgs(), LLVM_DEBUG, and llvm::Error::success().
Referenced by llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved().
defineNonExistent()
void llvm::orc::MaterializationResponsibility::defineNonExistent (ArrayRef< SymbolStringPtr > Symbols)
Define the given symbols as non-existent, removing it from the symbol table and notifying any pending queries.
Queries that lookup up the symbol using the SymbolLookupFlags::WeaklyReferencedSymbol flag will behave as if the symbol had not been matched in the first place. Queries that required this symbol will fail with a missing symbol definition error.
This method is intended to support cleanup of special symbols like initializer symbols: Queries using SymbolLookupFlags::WeaklyReferencedSymbol can be used to trigger their emission, and this method can be used to remove them from the JITDylib once materialization is complete.
delegate()
MaterializationResponsibility llvm::orc::MaterializationResponsibility::delegate (const SymbolNameSet & Symbols, VModuleKey NewKey = VModuleKey())
Delegates responsibility for the given symbols to the returned materialization responsibility.
Useful for breaking up work between threads, or different kinds of materialization processes.
Definition at line 283 of file Core.cpp.
References assert(), I, MaterializationResponsibility(), Name, and std::swap().
failMaterialization()
void llvm::orc::MaterializationResponsibility::failMaterialization ()
Notify all not-yet-emitted covered by this MaterializationResponsibility instance that an error has occurred.
This will remove all symbols covered by this MaterializationResponsibilty from the target JITDylib, and send an error to any queries waiting on these symbols.
Definition at line 242 of file Core.cpp.
References llvm::dbgs(), and LLVM_DEBUG.
Referenced by llvm::orc::ObjectLinkingLayerJITLinkContext::notifyFailed(), llvm::orc::ObjectLinkingLayerJITLinkContext::notifyFinalized(), and llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved().
getInitializerSymbol()
const SymbolStringPtr & llvm::orc::MaterializationResponsibility::getInitializerSymbol () const inline
Returns the initialization pseudo-symbol, if any.
This symbol will also be present in the SymbolFlagsMap for this MaterializationResponsibility object.
Definition at line 438 of file Core.h.
getRequestedSymbols()
SymbolNameSet llvm::orc::MaterializationResponsibility::getRequestedSymbols () const
Returns the names of any symbols covered by this MaterializationResponsibility object that have queries pending.
This information can be used to return responsibility for unrequested symbols back to the JITDylib via the delegate method.
Definition at line 189 of file Core.cpp.
getSymbols()
const SymbolFlagsMap & llvm::orc::MaterializationResponsibility::getSymbols () const inline
Returns the symbol flags map for this responsibility instance.
Note: The returned flags may have transient flags (Lazy, Materializing) set. These should be stripped with JITSymbolFlags::stripTransientFlags before using.
Definition at line 433 of file Core.h.
Referenced by llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved().
getTargetJITDylib()
JITDylib & llvm::orc::MaterializationResponsibility::getTargetJITDylib () const inline
Returns the target JITDylib that these symbols are being materialized into.
Definition at line 424 of file Core.h.
Referenced by llvm::orc::ExecutionSession::dispatchMaterialization(), and llvm::orc::ObjectLinkingLayerJITLinkContext::lookup().
getVModuleKey()
VModuleKey llvm::orc::MaterializationResponsibility::getVModuleKey () const inline
Returns the VModuleKey for this instance.
Definition at line 427 of file Core.h.
Referenced by llvm::orc::EHFrameRegistrationPlugin::notifyEmitted().
notifyEmitted()
Error llvm::orc::MaterializationResponsibility::notifyEmitted ()
Notifies the target JITDylib (and any pending queries on that JITDylib) that all symbols covered by this MaterializationResponsibility instance have been emitted.
This method will return an error if any symbols being resolved have been moved to the error state due to the failure of a dependency. If this method returns an error then clients should log it and call failMaterialize. If no dependencies have been registered for the symbols covered by this MaterializationResponsibiility then this method is guaranteed to return Error::success() and can be wrapped with cantFail.
Definition at line 213 of file Core.cpp.
References llvm::dbgs(), LLVM_DEBUG, and llvm::Error::success().
Referenced by llvm::orc::ObjectLinkingLayerJITLinkContext::notifyFinalized().
notifyResolved()
Error llvm::orc::MaterializationResponsibility::notifyResolved (const SymbolMap & Symbols)
Notifies the target JITDylib that the given symbols have been resolved.
This will update the given symbols' addresses in the JITDylib, and notify any pending queries on the given symbols of their resolution. The given symbols must be ones covered by this MaterializationResponsibility instance. Individual calls to this method may resolve a subset of the symbols, but all symbols must have been resolved prior to calling emit.
This method will return an error if any symbols being resolved have been moved to the error state due to the failure of a dependency. If this method returns an error then clients should log it and call failMaterialize. If no dependencies have been registered for the symbols covered by this MaterializationResponsibiility then this method is guaranteed to return Error::success() and can be wrapped with cantFail.
Definition at line 193 of file Core.cpp.
References assert(), llvm::JITSymbolFlags::Common, llvm::dbgs(), I, LLVM_DEBUG, and llvm::JITSymbolFlags::Weak.
Referenced by llvm::orc::ObjectLinkingLayerJITLinkContext::notifyResolved().
operator=()
MaterializationResponsibility & llvm::orc::MaterializationResponsibility::operator= (MaterializationResponsibility &&) delete
replace()
void llvm::orc::MaterializationResponsibility::replace (std::unique_ptr< MaterializationUnit > MU)
Transfers responsibility to the given MaterializationUnit for all symbols defined by that MaterializationUnit.
This allows materializers to break up work based on run-time information (e.g. by introspecting which symbols have actually been looked up and materializing only those).
Definition at line 258 of file Core.cpp.
References assert(), and LLVM_DEBUG.
Friends And Related Symbol Documentation
MaterializationUnit
friend class MaterializationUnit friend
Definition at line 411 of file Core.h.
The documentation for this class was generated from the following files:
include/llvm/ExecutionEngine/Orc/Core.h
lib/ExecutionEngine/Orc/Core.cpp