LLVM: llvm::X86AsmPrinter Class Reference
llvm::X86AsmPrinter Class Reference
#include "Target/X86/X86AsmPrinter.h"
Public Member Functions
X86AsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
StringRef getPassName () const override
getPassName - Return a nice clean name for a pass.
const X86Subtarget & getSubtarget () const
void emitStartOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the start of their file.
void emitEndOfAsmFile (Module &M) override
This virtual method can be overridden by targets that want to emit something at the end of their file.
void emitInstruction (const MachineInstr *MI) override
Targets should implement this to emit instructions.
void emitBasicBlockEnd (const MachineBasicBlock &MBB) override
Targets can override this to emit stuff at the end of a basic block.
bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, const char *ExtraCode, raw_ostream &OS) override
PrintAsmOperand - Print out an operand for an inline asm expression.
bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNo, const char *ExtraCode, raw_ostream &OS) override
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
bool doInitialization (Module &M) override
Set up the AsmPrinter when we are working on a new module.
bool runOnMachineFunction (MachineFunction &F) override
runOnMachineFunction - Emit the function body.
void emitFunctionBodyStart () override
Targets can override this to emit stuff before the first basic block in the function.
void emitFunctionBodyEnd () override
Targets can override this to emit stuff after the last basic block in the function.
Public Member Functions inherited from llvm::AsmPrinter
~AsmPrinter () override
DwarfDebug * getDwarfDebug ()
DwarfDebug * getDwarfDebug () const
uint16_t getDwarfVersion () const
void setDwarfVersion (uint16_t Version)
bool isPositionIndependent () const
bool isVerbose () const
Return true if assembly output should contain comments.
unsigned getFunctionNumber () const
Return a unique ID for the current function.
virtual const MCSymbol * getFunctionFrameSymbol () const
Return symbol for the function pseudo stack if the stack frame is not a register based.
MCSymbol * getFunctionBegin () const
MCSymbol * getFunctionEnd () const
MCSymbol * getCurExceptionSym ()
const TargetLoweringObjectFile & getObjFileLowering () const
Return information about object file lowering.
const DataLayout & getDataLayout () const
Return information about data layout.
unsigned getPointerSize () const
Return the pointer size from the TargetMachine.
const MCSubtargetInfo & getSubtargetInfo () const
Return information about subtarget.
void EmitToStreamer (MCStreamer &S, const MCInst &Inst)
void emitInitialRawDwarfLocDirective (const MachineFunction &MF)
Emits inital debug location directive.
const MCSection * getCurrentSection () const
Return the current section we are emitting to.
void getNameWithPrefix (SmallVectorImpl< char > &Name, const GlobalValue *GV) const
MCSymbol * getSymbol (const GlobalValue *GV) const
MCSymbol * getSymbolPreferLocal (const GlobalValue &GV) const
Similar to getSymbol() but preferred for references.
void recordSled (MCSymbol *Sled, const MachineInstr &MI, SledKind Kind, uint8_t Version=0)
void emitXRayTable ()
Emit a table with all XRay instrumentation points.
void emitPatchableFunctionEntries ()
void getAnalysisUsage (AnalysisUsage &AU) const override
Record analysis usage.
bool doFinalization (Module &M) override
Shut down the asmprinter.
virtual void SetupMachineFunction (MachineFunction &MF)
This should be called when a new MachineFunction is being processed from runOnMachineFunction.
void emitFunctionBody ()
This method emits the body and trailer for a function.
void emitCFIInstruction (const MachineInstr &MI)
void emitFrameAlloc (const MachineInstr &MI)
void emitStackSizeSection (const MachineFunction &MF)
void emitRemarksSection (remarks::RemarkStreamer &RS)
CFIMoveType needsCFIMoves () const
bool needsOnlyDebugCFIMoves () const
Returns false if needsCFIMoves() == CFI_M_EH for any function in the module.
bool needsSEHMoves ()
virtual void emitConstantPool ()
Print to the current output stream assembly representations of the constants in the constant pool MCP.
virtual void emitJumpTableInfo ()
Print assembly representations of the jump tables used by the current function to the current output stream.
virtual void emitGlobalVariable (const GlobalVariable *GV)
Emit the specified global variable to the .s file.
bool emitSpecialLLVMGlobal (const GlobalVariable *GV)
Check to see if the specified global is a special global used by LLVM.
void emitAlignment (Align Alignment, const GlobalObject *GV=nullptr) const
Emit an alignment directive to the specified power of two boundary.
virtual const MCExpr * lowerConstant (const Constant *CV)
Lower the specified LLVM Constant to an MCExpr.
void emitGlobalConstant (const DataLayout &DL, const Constant *CV)
Print a general LLVM constant to the .s file.
void computeGlobalGOTEquivs (Module &M)
Unnamed constant global variables solely contaning a pointer to another globals variable act like a global variable "proxy", or GOT equivalents, i.e., it's only used to hold the address of the latter.
void emitGlobalGOTEquivs ()
Constant expressions using GOT equivalent globals may not be eligible for PC relative GOT entry conversion, in such cases we need to emit the proxies we previously omitted in EmitGlobalVariable.
void emitStackMaps (StackMaps &SM)
Emit the stack maps.
virtual void emitBasicBlockStart (const MachineBasicBlock &MBB)
Targets can override this to emit stuff at the start of a basic block.
virtual MCSymbol * GetCPISymbol (unsigned CPID) const
Return the symbol for the specified constant pool entry.
virtual void emitFunctionEntryLabel ()
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function.
virtual void emitFunctionDescriptor ()
virtual void emitMachineConstantPoolValue (MachineConstantPoolValue *MCPV)
virtual void emitXXStructor (const DataLayout &DL, const Constant *CV)
Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
virtual bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const
Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
virtual void emitImplicitDef (const MachineInstr *MI) const
Targets can override this to customize the output of IMPLICIT_DEF instructions in verbose mode.
void emitNops (unsigned N)
Emit N NOP instructions.
MCSymbol * createTempSymbol (const Twine &Name) const
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
Return the MCSymbol for the specified ExternalSymbol.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
Return the MCSymbol used to satisfy BlockAddress uses of the specified basic block.
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
This is just convenient handler for printing offsets.
void emitInt8 (int Value) const
Emit a byte directive and value.
void emitInt16 (int Value) const
Emit a short directive and value.
void emitInt32 (int Value) const
Emit a long directive and value.
void emitInt64 (uint64_t Value) const
Emit a long long directive and value.
void emitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
Emit something like ".long Hi-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels.
void emitLabelDifferenceAsULEB128 (const MCSymbol *Hi, const MCSymbol *Lo) const
Emit something like ".uleb128 Hi-Lo".
void emitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label.
void emitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
Emit something like ".long Label" where the size in bytes of the directive is specified by Size and Label specifies the label.
void emitDwarfOffset (const MCSymbol *Label, uint64_t Offset) const
Emit something like ".long Label + Offset".
void emitSLEB128 (int64_t Value, const char *Desc=nullptr) const
Emit the specified signed leb128 value.
void emitULEB128 (uint64_t Value, const char *Desc=nullptr, unsigned PadTo=0) const
Emit the specified unsigned leb128 value.
void emitEncodingByte (unsigned Val, const char *Desc=nullptr) const
Emit a .byte 42 directive that corresponds to an encoding.
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
Return the size of the encoding in bytes.
void emitTTypeReference (const GlobalValue *GV, unsigned Encoding) const
Emit reference to a ttype global with a specified encoding.
void emitDwarfSymbolReference (const MCSymbol *Label, bool ForceOffset=false) const
Emit a reference to a symbol for use in dwarf.
void emitDwarfStringOffset (DwarfStringPoolEntry S) const
Emit the 4-byte offset of a string from the start of its section.
void emitDwarfStringOffset (DwarfStringPoolEntryRef S) const
Emit the 4-byte offset of a string from the start of its section.
void emitCallSiteOffset (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Encoding) const
Emit reference to a call site with a specified encoding.
void emitCallSiteValue (uint64_t Value, unsigned Encoding) const
Emit an integer value corresponding to the call site encoding.
virtual unsigned getISAEncoding ()
Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
virtual void emitDebugValue (const MCExpr *Value, unsigned Size) const
Emit the directive and value for debug thread local expression.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
template<typename T >
void emitDwarfAbbrevs (const T &Abbrevs) const
Emit Dwarf abbreviation table.
void emitDwarfAbbrev (const DIEAbbrev &Abbrev) const
void emitDwarfDIE (const DIE &Die) const
Recursively emit Dwarf DIE tree.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, const char *Code) const
Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself.
virtual void emitInlineAsmStart () const
Let the target do anything it needs to do before emitting inlineasm.
virtual void emitInlineAsmEnd (const MCSubtargetInfo &StartInfo, const MCSubtargetInfo *EndInfo) const
Let the target do anything it needs to do after emitting inlineasm.
void emitVisibility (MCSymbol *Sym, unsigned Visibility, bool IsDefinition=true) const
This emits visibility information about symbol, if this is supported by the target.
virtual void emitLinkage (const GlobalValue *GV, MCSymbol *GVSym) const
This emits linkage information about GVSym based on GV, if this is supported by the target.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Additional Inherited Members
Public Types inherited from llvm::AsmPrinter
enum class SledKind : uint8_t {
FUNCTION_ENTER = 0 , FUNCTION_EXIT = 1 , TAIL_CALL = 2 , LOG_ARGS_ENTER = 3 ,
CUSTOM_EVENT = 4 , TYPED_EVENT = 5
}
enum CFIMoveType { CFI_M_None , CFI_M_EH , CFI_M_Debug }
using GOTEquivUsePair = std::pair<const GlobalVariable *, unsigned>
Map global GOT equivalent MCSymbols to GlobalVariables and keep track of its number of uses by other globals.
Static Public Member Functions inherited from llvm::AsmPrinter
static Align getGVAlignment (const GlobalObject *GV, const DataLayout &DL, Align InAlign=Align(1))
Return the alignment for the specified GV.
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::AsmPrinter
TargetMachine & TM
Target machine description.
const MCAsmInfo * MAI
Target Asm Printer information.
MCContext & OutContext
This is the context for the output file that we are streaming.
std::unique_ptr< MCStreamer > OutStreamer
This is the MCStreamer object for the file we are generating.
MachineFunction * MF = nullptr
The current machine function.
MachineModuleInfo * MMI = nullptr
This is a pointer to the current MachineModuleInfo.
MachineDominatorTree * MDT = nullptr
This is a pointer to the current MachineDominatorTree.
MachineLoopInfo * MLI = nullptr
This is a pointer to the current MachineLoopInfo.
MachineOptimizationRemarkEmitter * ORE
Optimization remark emitter.
MCSymbol * CurrentPatchableFunctionEntrySym = nullptr
The symbol for the entry in __patchable_function_entires.
MCSymbol * CurrentFnSym = nullptr
The symbol for the current function.
MCSymbol * CurrentFnDescSym = nullptr
The symbol for the current function descriptor on AIX.
MCSymbol * CurrentFnSymForSize = nullptr
The symbol used to represent the start of the current function for the purpose of calculating its size (e.g.
MapVector< unsigned, MBBSectionRange > MBBSectionRanges
MapVector< const MCSymbol *, GOTEquivUsePair > GlobalGOTEquivs
SmallVector< XRayFunctionEntry, 4 > Sleds
Protected Member Functions inherited from llvm::AsmPrinter
AsmPrinter (TargetMachine &TM, std::unique_ptr< MCStreamer > Streamer)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
virtual MachineFunctionProperties getRequiredProperties () const
virtual MachineFunctionProperties getSetProperties () const
virtual MachineFunctionProperties getClearedProperties () const
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Protected Attributes inherited from llvm::AsmPrinter
MCSymbol * CurrentFnBegin = nullptr
SmallVector< HandlerInfo, 1 > Handlers
A vector of all debug/EH info emitters we should use.
Detailed Description
Definition at line 27 of file X86AsmPrinter.h.
Constructor & Destructor Documentation
X86AsmPrinter()
X86AsmPrinter::X86AsmPrinter (TargetMachine & TM, std::unique_ptr< MCStreamer > Streamer)
Definition at line 48 of file X86AsmPrinter.cpp.
Member Function Documentation
doInitialization()
bool llvm::X86AsmPrinter::doInitialization (Module & M) inline override virtual
Set up the AsmPrinter when we are working on a new module.
If your pass overrides this, it must make sure to explicitly call this implementation.
Reimplemented from llvm::AsmPrinter.
Definition at line 141 of file X86AsmPrinter.h.
References llvm::AsmPrinter::doInitialization(), llvm::FaultMaps::reset(), and llvm::StackMaps::reset().
emitBasicBlockEnd()
void llvm::X86AsmPrinter::emitBasicBlockEnd (const MachineBasicBlock & MBB) inline override virtual
Targets can override this to emit stuff at the end of a basic block.
Reimplemented from llvm::AsmPrinter.
Definition at line 131 of file X86AsmPrinter.h.
References llvm::AsmPrinter::emitBasicBlockEnd(), and MBB.
emitEndOfAsmFile()
void X86AsmPrinter::emitEndOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 748 of file X86AsmPrinter.cpp.
References emitNonLazyStubs(), llvm::AsmPrinter::emitStackMaps(), llvm::MachineModuleInfo::getContext(), llvm::MCContext::getOrCreateSymbol(), llvm::TargetMachine::getTargetTriple(), llvm::MCAF_SubsectionsViaSymbols, llvm::MCSA_Global, llvm::AsmPrinter::MMI, llvm::AsmPrinter::OutStreamer, llvm::FaultMaps::serializeToFaultMapSection(), llvm::AsmPrinter::TM, llvm::MachineModuleInfo::usesMSVCFloatingPoint(), and llvm::Triple::x86.
emitFunctionBodyEnd()
void X86AsmPrinter::emitFunctionBodyEnd () override virtual
Targets can override this to emit stuff after the last basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 103 of file X86AsmPrinter.cpp.
References llvm::AsmPrinter::OutStreamer.
emitFunctionBodyStart()
void X86AsmPrinter::emitFunctionBodyStart () override virtual
Targets can override this to emit stuff before the first basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 93 of file X86AsmPrinter.cpp.
References llvm::AsmPrinter::CurrentFnSym, llvm::X86MachineFunctionInfo::getArgumentStackSize(), llvm::MachineFunction::getInfo(), llvm::AsmPrinter::MF, and llvm::AsmPrinter::OutStreamer.
emitInstruction()
void X86AsmPrinter::emitInstruction (const MachineInstr *) override virtual
Targets should implement this to emit instructions.
Reimplemented from llvm::AsmPrinter.
Definition at line 2367 of file X86MCInstLower.cpp.
References llvm::X86::AC_EVEX_2_VEX, llvm::MCStreamer::AddComment(), addConstantComments(), llvm::MCInstBuilder::addExpr(), llvm::MCInstBuilder::addReg(), assert(), llvm::MCSymbolRefExpr::create(), llvm::MCBinaryExpr::createAdd(), llvm::MCBinaryExpr::createSub(), llvm::MCStreamer::emitCFIAdjustCfaOffset(), llvm::MCStreamer::emitInstruction(), llvm::MCStreamer::emitLabel(), llvm::MCStreamer::emitRawComment(), llvm::MCStreamer::getDwarfFrameInfos(), llvm::MCStreamer::getNumFrameInfos(), llvm::X86ATTInstPrinter::getRegisterName(), getRetOpcode(), llvm::X86RegisterInfo::getSlotSize(), llvm::X86FrameLowering::hasFP(), llvm::MCStreamer::isVerboseAsm(), llvm_unreachable, MBBI, MI, llvm::X86II::MO_GOT_ABSOLUTE_ADDRESS, and PrevCrossBBInst().
emitStartOfAsmFile()
void X86AsmPrinter::emitStartOfAsmFile (Module &) override virtual
This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 625 of file X86AsmPrinter.cpp.
References llvm::Triple::CODE16, llvm::MCConstantExpr::create(), llvm::AsmPrinter::emitAlignment(), llvm::MachineModuleInfo::getContext(), llvm::MCContext::getELFSection(), llvm::AsmPrinter::getObjFileLowering(), llvm::MCContext::getOrCreateSymbol(), llvm::TargetMachine::getTargetTriple(), llvm::MCObjectFileInfo::getTextSection(), llvm::ELF::GNU_PROPERTY_X86_FEATURE_1_AND, llvm::ELF::GNU_PROPERTY_X86_FEATURE_1_IBT, llvm::ELF::GNU_PROPERTY_X86_FEATURE_1_SHSTK, llvm::COFF::IMAGE_SYM_CLASS_STATIC, llvm::COFF::IMAGE_SYM_DTYPE_NULL, llvm_unreachable, llvm::MCAF_Code16, llvm::MCSA_Global, llvm::AsmPrinter::MMI, llvm::ELF::NT_GNU_PROPERTY_TYPE_0, llvm::AsmPrinter::OutStreamer, llvm::ELF::SHF_ALLOC, llvm::ELF::SHT_NOTE, llvm::AsmPrinter::TM, and llvm::Triple::x86.
getPassName()
StringRef llvm::X86AsmPrinter::getPassName () const inline override virtual
getPassName - Return a nice clean name for a pass.
This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 119 of file X86AsmPrinter.h.
getSubtarget()
const X86Subtarget & llvm::X86AsmPrinter::getSubtarget () const inline
Definition at line 123 of file X86AsmPrinter.h.
PrintAsmMemoryOperand()
bool X86AsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & OS) override virtual
Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address.
Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented from llvm::AsmPrinter.
Definition at line 586 of file X86AsmPrinter.cpp.
References llvm::InlineAsm::AD_Intel, and MI.
PrintAsmOperand()
bool X86AsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, const char * ExtraCode, raw_ostream & OS) override virtual
PrintAsmOperand - Print out an operand for an inline asm expression.
Reimplemented from llvm::AsmPrinter.
Definition at line 487 of file X86AsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::getType(), llvm::MachineOperand::isImm(), llvm::X86Subtarget::isPICStyleRIPRel(), llvm::MachineOperand::isReg(), llvm_unreachable, MI, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_Register, printAsmMRegister(), llvm::AsmPrinter::PrintAsmOperand(), and printAsmVRegister().
runOnMachineFunction()
bool X86AsmPrinter::runOnMachineFunction (MachineFunction & F) override virtual
runOnMachineFunction - Emit the function body.
Reimplemented from llvm::AsmPrinter.
Definition at line 58 of file X86AsmPrinter.cpp.
References llvm::Target::createMCCodeEmitter(), llvm::AsmPrinter::CurrentFnSym, llvm::AsmPrinter::emitFunctionBody(), llvm::AsmPrinter::emitXRayTable(), llvm::Module::getCodeViewFlag(), llvm::MachineFunction::getContext(), llvm::MachineFunction::getFunction(), llvm::X86Subtarget::getInstrInfo(), llvm::MachineFunction::getMMI(), llvm::MachineModuleInfo::getModule(), llvm::X86Subtarget::getRegisterInfo(), llvm::MachineFunction::getSubtarget(), llvm::TargetMachine::getTarget(), llvm::GlobalValue::hasLocalLinkage(), llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL, llvm::COFF::IMAGE_SYM_CLASS_STATIC, llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::X86Subtarget::isTargetCOFF(), llvm::X86Subtarget::isTargetWin32(), llvm::AsmPrinter::MF, llvm::AsmPrinter::OutStreamer, llvm::COFF::SCT_COMPLEX_TYPE_SHIFT, llvm::AsmPrinter::SetupMachineFunction(), and llvm::AsmPrinter::TM.
The documentation for this class was generated from the following files:
lib/Target/X86/X86AsmPrinter.h
lib/Target/X86/X86AsmPrinter.cpp
lib/Target/X86/X86MCInstLower.cpp