LLVM: llvm::cl::OptionValueCopy< DataType > Class Template Reference
llvm::cl::OptionValueCopy< DataType > Class Template Reference
#include "llvm/Support/CommandLine.h"
Public Member Functions
OptionValueCopy ()=default
bool hasValue () const
const DataType & getValue () const
void setValue (const DataType &V)
bool compare (const DataType &V) const
bool compare (const GenericOptionValue &V) const override
Protected Member Functions
OptionValueCopy (const OptionValueCopy &)=default
OptionValueCopy & operator= (const OptionValueCopy &)=default
~OptionValueCopy ()=default
Protected Member Functions inherited from llvm::cl::GenericOptionValue
GenericOptionValue ()=default
GenericOptionValue (const GenericOptionValue &)=default
GenericOptionValue & operator= (const GenericOptionValue &)=default
~GenericOptionValue ()=default
Detailed Description
template<class DataType>
class llvm::cl::OptionValueCopy< DataType >
Definition at line 553 of file CommandLine.h.
Constructor & Destructor Documentation
OptionValueCopy() [1/2]
template<class DataType > llvm::cl::OptionValueCopy< DataType >::OptionValueCopy (const OptionValueCopy< DataType > &) protected default
~OptionValueCopy()
template<class DataType > llvm::cl::OptionValueCopy< DataType >::~OptionValueCopy () protected default
OptionValueCopy() [2/2]
template<class DataType > llvm::cl::OptionValueCopy< DataType >::OptionValueCopy () default
Member Function Documentation
compare() [1/2]
template<class DataType > bool llvm::cl::OptionValueCopy< DataType >::compare (const DataType & V) const inline
Definition at line 577 of file CommandLine.h.
Referenced by llvm::cl::OptionValueCopy< DataType >::compare().
compare() [2/2]
template<class DataType > bool llvm::cl::OptionValueCopy< DataType >::compare (const GenericOptionValue & V) const inline override virtual
Implements llvm::cl::GenericOptionValue.
Definition at line 579 of file CommandLine.h.
References llvm::cl::OptionValueCopy< DataType >::compare().
getValue()
template<class DataType > const DataType & llvm::cl::OptionValueCopy< DataType >::getValue () const inline
Definition at line 567 of file CommandLine.h.
References assert().
hasValue()
template<class DataType > bool llvm::cl::OptionValueCopy< DataType >::hasValue () const inline
Definition at line 565 of file CommandLine.h.
operator=()
template<class DataType > OptionValueCopy & llvm::cl::OptionValueCopy< DataType >::operator= (const OptionValueCopy< DataType > &) protected default
setValue()
template<class DataType > void llvm::cl::OptionValueCopy< DataType >::setValue (const DataType & V) inline
Definition at line 572 of file CommandLine.h.
The documentation for this class was generated from the following file:
include/llvm/Support/CommandLine.h