LLVM: llvm::objcarc::PtrState Class Reference
llvm::objcarc::PtrState Class Reference
This class summarizes several per-pointer runtime properties which are propagated through the flow graph.
#include "Transforms/ObjCARC/PtrState.h"
Public Member Functions
bool IsKnownSafe () const
void SetKnownSafe (const bool NewValue)
bool IsTailCallRelease () const
void SetTailCallRelease (const bool NewValue)
bool IsTrackingImpreciseReleases () const
const MDNode * GetReleaseMetadata () const
void SetReleaseMetadata (MDNode *NewValue)
bool IsCFGHazardAfflicted () const
void SetCFGHazardAfflicted (const bool NewValue)
void SetKnownPositiveRefCount ()
void ClearKnownPositiveRefCount ()
bool HasKnownPositiveRefCount () const
void SetSeq (Sequence NewSeq)
Sequence GetSeq () const
void ClearSequenceProgress ()
void ResetSequenceProgress (Sequence NewSeq)
void Merge (const PtrState &Other, bool TopDown)
void InsertCall (Instruction *I)
void InsertReverseInsertPt (Instruction *I)
void ClearReverseInsertPts ()
bool HasReverseInsertPts () const
const RRInfo & GetRRInfo () const
Protected Member Functions
PtrState ()
Protected Attributes
bool KnownPositiveRefCount = false
True if the reference count is known to be incremented.
bool Partial = false
True if we've seen an opportunity for partial RR elimination, such as pushing calls into a CFG triangle or into one side of a CFG diamond.
unsigned char Seq: 8
The current position in the sequence.
RRInfo RRI
Unidirectional information about the current sequence.
Detailed Description
This class summarizes several per-pointer runtime properties which are propagated through the flow graph.
Definition at line 101 of file PtrState.h.
Constructor & Destructor Documentation
PtrState()
llvm::objcarc::PtrState::PtrState () inline protected
Definition at line 116 of file PtrState.h.
Member Function Documentation
ClearKnownPositiveRefCount()
void PtrState::ClearKnownPositiveRefCount ()
Definition at line 132 of file PtrState.cpp.
References llvm::dbgs(), KnownPositiveRefCount, and LLVM_DEBUG.
Referenced by llvm::objcarc::TopDownPtrState::HandlePotentialAlterRefCount(), and llvm::objcarc::TopDownPtrState::MatchWithRelease().
ClearReverseInsertPts()
void llvm::objcarc::PtrState::ClearReverseInsertPts () inline
Definition at line 161 of file PtrState.h.
References llvm::objcarc::RRInfo::ReverseInsertPts, and RRI.
Referenced by llvm::objcarc::TopDownPtrState::MatchWithRelease(), and llvm::objcarc::BottomUpPtrState::MatchWithRetain().
ClearSequenceProgress()
void llvm::objcarc::PtrState::ClearSequenceProgress () inline
Definition at line 152 of file PtrState.h.
References ResetSequenceProgress(), and llvm::objcarc::S_None.
Referenced by CheckForUseCFGHazard(), and Merge().
GetReleaseMetadata()
const MDNode * llvm::objcarc::PtrState::GetReleaseMetadata () const inline
Definition at line 133 of file PtrState.h.
References llvm::objcarc::RRInfo::ReleaseMetadata, and RRI.
GetRRInfo()
const RRInfo & llvm::objcarc::PtrState::GetRRInfo () const inline
Definition at line 165 of file PtrState.h.
References RRI.
GetSeq()
Sequence llvm::objcarc::PtrState::GetSeq () const inline
Definition at line 150 of file PtrState.h.
References Seq.
Referenced by llvm::objcarc::BottomUpPtrState::HandlePotentialAlterRefCount(), llvm::objcarc::TopDownPtrState::HandlePotentialAlterRefCount(), llvm::objcarc::BottomUpPtrState::HandlePotentialUse(), llvm::objcarc::TopDownPtrState::HandlePotentialUse(), llvm::objcarc::BottomUpPtrState::InitBottomUp(), llvm::objcarc::TopDownPtrState::InitTopDown(), llvm::objcarc::TopDownPtrState::MatchWithRelease(), llvm::objcarc::BottomUpPtrState::MatchWithRetain(), Merge(), and SetSeq().
HasKnownPositiveRefCount()
bool llvm::objcarc::PtrState::HasKnownPositiveRefCount () const inline
Definition at line 146 of file PtrState.h.
References KnownPositiveRefCount.
Referenced by llvm::objcarc::BottomUpPtrState::InitBottomUp(), and llvm::objcarc::TopDownPtrState::InitTopDown().
HasReverseInsertPts()
bool llvm::objcarc::PtrState::HasReverseInsertPts () const inline
Definition at line 163 of file PtrState.h.
References llvm::objcarc::RRInfo::ReverseInsertPts, and RRI.
Referenced by llvm::objcarc::TopDownPtrState::HandlePotentialAlterRefCount(), and llvm::objcarc::BottomUpPtrState::HandlePotentialUse().
InsertCall()
void llvm::objcarc::PtrState::InsertCall (Instruction * I) inline
Definition at line 157 of file PtrState.h.
References llvm::objcarc::RRInfo::Calls, I, and RRI.
Referenced by llvm::objcarc::BottomUpPtrState::InitBottomUp(), and llvm::objcarc::TopDownPtrState::InitTopDown().
InsertReverseInsertPt()
void llvm::objcarc::PtrState::InsertReverseInsertPt (Instruction * I) inline
Definition at line 159 of file PtrState.h.
References I, llvm::objcarc::RRInfo::ReverseInsertPts, and RRI.
Referenced by llvm::objcarc::TopDownPtrState::HandlePotentialAlterRefCount(), and llvm::objcarc::BottomUpPtrState::HandlePotentialUse().
IsCFGHazardAfflicted()
bool llvm::objcarc::PtrState::IsCFGHazardAfflicted () const inline
Definition at line 137 of file PtrState.h.
References llvm::objcarc::RRInfo::CFGHazardAfflicted, and RRI.
IsKnownSafe()
bool llvm::objcarc::PtrState::IsKnownSafe () const inline
Definition at line 119 of file PtrState.h.
References llvm::objcarc::RRInfo::KnownSafe, and RRI.
Referenced by CheckForCanReleaseCFGHazard(), and CheckForUseCFGHazard().
IsTailCallRelease()
bool llvm::objcarc::PtrState::IsTailCallRelease () const inline
Definition at line 123 of file PtrState.h.
References llvm::objcarc::RRInfo::IsTailCallRelease, and RRI.
IsTrackingImpreciseReleases()
bool llvm::objcarc::PtrState::IsTrackingImpreciseReleases () const inline
Definition at line 129 of file PtrState.h.
References llvm::objcarc::RRInfo::ReleaseMetadata, and RRI.
Referenced by llvm::objcarc::BottomUpPtrState::MatchWithRetain().
Merge()
void PtrState::Merge (const PtrState & Other, bool TopDown)
Definition at line 150 of file PtrState.cpp.
References llvm::objcarc::RRInfo::clear(), ClearSequenceProgress(), GetSeq(), KnownPositiveRefCount, llvm::objcarc::RRInfo::Merge(), MergeSeqs(), llvm::Other, Partial, RRI, llvm::objcarc::S_None, and Seq.
ResetSequenceProgress()
void PtrState::ResetSequenceProgress (Sequence NewSeq)
Definition at line 143 of file PtrState.cpp.
References llvm::objcarc::RRInfo::clear(), llvm::dbgs(), LLVM_DEBUG, Partial, RRI, and SetSeq().
Referenced by ClearSequenceProgress(), llvm::objcarc::BottomUpPtrState::InitBottomUp(), and llvm::objcarc::TopDownPtrState::InitTopDown().
SetCFGHazardAfflicted()
void llvm::objcarc::PtrState::SetCFGHazardAfflicted (const bool NewValue) inline
Definition at line 139 of file PtrState.h.
References llvm::objcarc::RRInfo::CFGHazardAfflicted, and RRI.
Referenced by CheckForUseCFGHazard(), and llvm::objcarc::BottomUpPtrState::HandlePotentialUse().
SetKnownPositiveRefCount()
void PtrState::SetKnownPositiveRefCount ()
Definition at line 127 of file PtrState.cpp.
References llvm::dbgs(), KnownPositiveRefCount, and LLVM_DEBUG.
Referenced by llvm::objcarc::BottomUpPtrState::InitBottomUp(), llvm::objcarc::TopDownPtrState::InitTopDown(), and llvm::objcarc::BottomUpPtrState::MatchWithRetain().
SetKnownSafe()
void llvm::objcarc::PtrState::SetKnownSafe (const bool NewValue) inline
Definition at line 121 of file PtrState.h.
References llvm::objcarc::RRInfo::KnownSafe, and RRI.
Referenced by llvm::objcarc::BottomUpPtrState::InitBottomUp(), and llvm::objcarc::TopDownPtrState::InitTopDown().
SetReleaseMetadata()
void llvm::objcarc::PtrState::SetReleaseMetadata (MDNode * NewValue) inline
Definition at line 135 of file PtrState.h.
References llvm::objcarc::RRInfo::ReleaseMetadata, and RRI.
Referenced by llvm::objcarc::BottomUpPtrState::InitBottomUp(), and llvm::objcarc::TopDownPtrState::MatchWithRelease().
SetSeq()
void PtrState::SetSeq (Sequence NewSeq)
Definition at line 137 of file PtrState.cpp.
References llvm::dbgs(), GetSeq(), LLVM_DEBUG, and Seq.
Referenced by llvm::objcarc::BottomUpPtrState::HandlePotentialAlterRefCount(), llvm::objcarc::TopDownPtrState::HandlePotentialAlterRefCount(), llvm::objcarc::BottomUpPtrState::HandlePotentialUse(), llvm::objcarc::TopDownPtrState::HandlePotentialUse(), and ResetSequenceProgress().
SetTailCallRelease()
void llvm::objcarc::PtrState::SetTailCallRelease (const bool NewValue) inline
Definition at line 125 of file PtrState.h.
References llvm::objcarc::RRInfo::IsTailCallRelease, and RRI.
Referenced by llvm::objcarc::BottomUpPtrState::InitBottomUp(), and llvm::objcarc::TopDownPtrState::MatchWithRelease().
Member Data Documentation
KnownPositiveRefCount
bool llvm::objcarc::PtrState::KnownPositiveRefCount = false protected
True if the reference count is known to be incremented.
Definition at line 104 of file PtrState.h.
Referenced by ClearKnownPositiveRefCount(), HasKnownPositiveRefCount(), Merge(), and SetKnownPositiveRefCount().
Partial
bool llvm::objcarc::PtrState::Partial = false protected
True if we've seen an opportunity for partial RR elimination, such as pushing calls into a CFG triangle or into one side of a CFG diamond.
Definition at line 108 of file PtrState.h.
Referenced by Merge(), and ResetSequenceProgress().
RRI
RRInfo llvm::objcarc::PtrState::RRI protected
Unidirectional information about the current sequence.
Definition at line 114 of file PtrState.h.
Referenced by ClearReverseInsertPts(), GetReleaseMetadata(), GetRRInfo(), HasReverseInsertPts(), InsertCall(), InsertReverseInsertPt(), IsCFGHazardAfflicted(), IsKnownSafe(), IsTailCallRelease(), IsTrackingImpreciseReleases(), Merge(), ResetSequenceProgress(), SetCFGHazardAfflicted(), SetKnownSafe(), SetReleaseMetadata(), and SetTailCallRelease().
Seq
unsigned char llvm::objcarc::PtrState::Seq protected
The current position in the sequence.
Definition at line 111 of file PtrState.h.
Referenced by GetSeq(), llvm::objcarc::BottomUpPtrState::HandlePotentialUse(), Merge(), and SetSeq().
The documentation for this class was generated from the following files:
lib/Transforms/ObjCARC/PtrState.h
lib/Transforms/ObjCARC/PtrState.cpp