LLVM: llvm::FileCollector Class Reference
llvm::FileCollector Class Reference
Captures file system interaction and generates data to be later replayed with the RedirectingFileSystem.
#include "llvm/Support/FileCollector.h"
Public Member Functions
FileCollector (std::string Root, std::string OverlayRoot)
Root is the directory where collected files are will be stored.
void addFile (const Twine &file)
void addDirectory (const Twine &Dir)
std::error_code writeMapping (StringRef MappingFile)
Write the yaml mapping (for the VFS) to the given file.
std::error_code copyFiles (bool StopOnError=true)
Copy the files into the root directory.
Static Public Member Functions
static IntrusiveRefCntPtr< vfs::FileSystem > createCollectorVFS (IntrusiveRefCntPtr< vfs::FileSystem > BaseFS, std::shared_ptr< FileCollector > Collector)
Create a VFS that uses Collector to collect files accessed via BaseFS.
Protected Member Functions
void addFileImpl (StringRef SrcPath)
llvm::vfs::directory_iterator addDirectoryImpl (const llvm::Twine &Dir, IntrusiveRefCntPtr< vfs::FileSystem > FS, std::error_code &EC)
Protected Attributes
std::mutex Mutex
Synchronizes access to Seen, VFSWriter and SymlinkMap.
const std::string Root
The directory where collected files are copied to in copyFiles().
const std::string OverlayRoot
The root directory where the VFS overlay lives.
StringSet Seen
Tracks already seen files so they can be skipped.
vfs::YAMLVFSWriter VFSWriter
The yaml mapping writer.
StringMap< std::string > SymlinkMap
Caches RealPath calls when resolving symlinks.
Detailed Description
Captures file system interaction and generates data to be later replayed with the RedirectingFileSystem.
For any file that gets accessed we eventually create:
a copy of the file inside Root
a record in RedirectingFileSystem mapping that maps: current real path -> path to the copy in Root
That intent is that later when the mapping is used by RedirectingFileSystem it simulates the state of FS that we collected.
We generate file copies and mapping lazily - see writeMapping and copyFiles. We don't try to capture the state of the file at the exact time when it's accessed. Files might get changed, deleted ... we record only the "final" state.
In order to preserve the relative topology of files we use their real paths as relative paths inside of the Root.
Definition at line 41 of file FileCollector.h.
Constructor & Destructor Documentation
FileCollector()
FileCollector::FileCollector (std::string Root, std::string OverlayRoot)
Root is the directory where collected files are will be stored.
OverlayRoot is VFS mapping root. Root directory gets created in copyFiles unless it already exists.
Definition at line 36 of file FileCollector.cpp.
Member Function Documentation
addDirectory()
void FileCollector::addDirectory (const Twine & Dir)
Definition at line 71 of file FileCollector.cpp.
References addDirectoryImpl(), assert(), llvm::vfs::getRealFileSystem(), and llvm::sys::fs::is_directory().
addDirectoryImpl()
llvm::vfs::directory_iterator FileCollector::addDirectoryImpl (const llvm::Twine & Dir, IntrusiveRefCntPtr< vfs::FileSystem > FS, std::error_code & EC) protected
Definition at line 111 of file FileCollector.cpp.
References addFile(), llvm::sys::fs::directory_file, llvm::sys::fs::regular_file, and llvm::sys::fs::symlink_file.
Referenced by addDirectory().
addFile()
void FileCollector::addFile (const Twine & file)
Definition at line 64 of file FileCollector.cpp.
References addFileImpl().
Referenced by addDirectoryImpl().
addFileImpl()
void FileCollector::addFileImpl (StringRef SrcPath) protected
Definition at line 77 of file FileCollector.cpp.
References llvm::sys::path::append(), llvm::sys::fs::make_absolute(), llvm::sys::path::native, llvm::sys::path::relative_path(), llvm::sys::path::remove_dots(), llvm::sys::path::remove_leading_dotslash(), and Root.
Referenced by addFile().
copyFiles()
std::error_code FileCollector::copyFiles (bool StopOnError = true)
Copy the files into the root directory.
When StopOnError is true (the default) we abort as soon as one file cannot be copied. This is relatively common, for example when a file was removed after it was added to the mapping.
Definition at line 152 of file FileCollector.cpp.
References llvm::sys::fs::copy_file(), copyAccessAndModificationTime(), llvm::sys::fs::create_directories(), llvm::sys::fs::directory_file, entry, llvm::vfs::YAMLVFSWriter::getMappings(), llvm::sys::fs::getPermissions(), llvm::sys::path::parent_path(), Root, llvm::sys::fs::setPermissions(), llvm::sys::fs::status(), llvm::sys::fs::basic_file_status::type(), and VFSWriter.
createCollectorVFS()
IntrusiveRefCntPtr< vfs::FileSystem > FileCollector::createCollectorVFS (IntrusiveRefCntPtr< vfs::FileSystem > BaseFS, std::shared_ptr< FileCollector > Collector) static
Create a VFS that uses Collector to collect files accessed via BaseFS.
Definition at line 284 of file FileCollector.cpp.
References Collector.
writeMapping()
std::error_code FileCollector::writeMapping (StringRef MappingFile)
Write the yaml mapping (for the VFS) to the given file.
Definition at line 208 of file FileCollector.cpp.
References isCaseSensitivePath(), llvm::sys::fs::OF_Text, OverlayRoot, llvm::vfs::YAMLVFSWriter::setCaseSensitivity(), llvm::vfs::YAMLVFSWriter::setOverlayDir(), llvm::vfs::YAMLVFSWriter::setUseExternalNames(), VFSWriter, and llvm::vfs::YAMLVFSWriter::write().
Member Data Documentation
Mutex
std::mutex llvm::FileCollector::Mutex protected
Synchronizes access to Seen, VFSWriter and SymlinkMap.
Definition at line 93 of file FileCollector.h.
OverlayRoot
const std::string llvm::FileCollector::OverlayRoot protected
The root directory where the VFS overlay lives.
Definition at line 99 of file FileCollector.h.
Referenced by writeMapping().
Root
const std::string llvm::FileCollector::Root protected
The directory where collected files are copied to in copyFiles().
Definition at line 96 of file FileCollector.h.
Referenced by addFileImpl(), and copyFiles().
Seen
StringSet llvm::FileCollector::Seen protected
Tracks already seen files so they can be skipped.
Definition at line 102 of file FileCollector.h.
SymlinkMap
StringMap<std::string> llvm::FileCollector::SymlinkMap protected
Caches RealPath calls when resolving symlinks.
Definition at line 108 of file FileCollector.h.
VFSWriter
vfs::YAMLVFSWriter llvm::FileCollector::VFSWriter protected
The yaml mapping writer.
Definition at line 105 of file FileCollector.h.
Referenced by copyFiles(), and writeMapping().
The documentation for this class was generated from the following files:
include/llvm/Support/FileCollector.h
lib/Support/FileCollector.cpp