LLVM: llvm::PPCDispatchGroupSBHazardRecognizer Class Reference
llvm::PPCDispatchGroupSBHazardRecognizer Class Reference
PPCDispatchGroupSBHazardRecognizer - This class implements a scoreboard-based hazard recognizer for PPC ooo processors with dispatch-group hazards.
#include "Target/PowerPC/PPCHazardRecognizers.h"
Public Member Functions
PPCDispatchGroupSBHazardRecognizer (const InstrItineraryData *ItinData, const ScheduleDAG *DAG_)
HazardType getHazardType (SUnit *SU, int Stalls) override
getHazardType - Return the hazard type of emitting this node.
bool ShouldPreferAnother (SUnit *SU) override
ShouldPreferAnother - This callback may be invoked if getHazardType returns NoHazard.
unsigned PreEmitNoops (SUnit *SU) override
PreEmitNoops - This callback is invoked prior to emitting an instruction.
void EmitInstruction (SUnit *SU) override
EmitInstruction - This callback is invoked when an instruction is emitted, to advance the hazard state.
void AdvanceCycle () override
AdvanceCycle - This callback is invoked whenever the next top-down instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
void RecedeCycle () override
RecedeCycle - This callback is invoked whenever the next bottom-up instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
void Reset () override
Reset - This callback is invoked when a new block of instructions is about to be schedule.
void EmitNoop () override
EmitNoop - This callback is invoked when a noop was added to the instruction stream.
Public Member Functions inherited from llvm::ScoreboardHazardRecognizer
ScoreboardHazardRecognizer (const InstrItineraryData *II, const ScheduleDAG *DAG, const char *ParentDebugType="")
bool atIssueLimit () const override
atIssueLimit - Return true if no more instructions may be issued in this cycle.
HazardType getHazardType (SUnit *SU, int Stalls) override
getHazardType - Return the hazard type of emitting this node.
void Reset () override
Reset - This callback is invoked when a new block of instructions is about to be schedule.
void EmitInstruction (SUnit *SU) override
EmitInstruction - This callback is invoked when an instruction is emitted, to advance the hazard state.
void AdvanceCycle () override
AdvanceCycle - This callback is invoked whenever the next top-down instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
void RecedeCycle () override
RecedeCycle - This callback is invoked whenever the next bottom-up instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
Public Member Functions inherited from llvm::ScheduleHazardRecognizer
ScheduleHazardRecognizer ()=default
virtual ~ScheduleHazardRecognizer ()
unsigned getMaxLookAhead () const
bool isEnabled () const
virtual void EmitInstruction (MachineInstr *)
This overload will be used when the hazard recognizer is being used by a non-scheduling pass, which does not use SUnits.
virtual unsigned PreEmitNoops (MachineInstr *)
This overload will be used when the hazard recognizer is being used by a non-scheduling pass, which does not use SUnits.
Additional Inherited Members
Public Types inherited from llvm::ScheduleHazardRecognizer
enum HazardType { NoHazard , Hazard , NoopHazard }
Protected Attributes inherited from llvm::ScheduleHazardRecognizer
unsigned MaxLookAhead = 0
MaxLookAhead - Indicate the number of cycles in the scoreboard state.
Detailed Description
PPCDispatchGroupSBHazardRecognizer - This class implements a scoreboard-based hazard recognizer for PPC ooo processors with dispatch-group hazards.
Definition at line 25 of file PPCHazardRecognizers.h.
Constructor & Destructor Documentation
PPCDispatchGroupSBHazardRecognizer()
llvm::PPCDispatchGroupSBHazardRecognizer::PPCDispatchGroupSBHazardRecognizer (const InstrItineraryData * ItinData, const ScheduleDAG * DAG_) inline
Definition at line 34 of file PPCHazardRecognizers.h.
Member Function Documentation
AdvanceCycle()
void PPCDispatchGroupSBHazardRecognizer::AdvanceCycle () override virtual
AdvanceCycle - This callback is invoked whenever the next top-down instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
This should increment the internal state of the hazard recognizer so that previously "Hazard" instructions will now not be hazards.
Reimplemented from llvm::ScheduleHazardRecognizer.
Definition at line 205 of file PPCHazardRecognizers.cpp.
References llvm::ScoreboardHazardRecognizer::AdvanceCycle().
EmitInstruction()
void PPCDispatchGroupSBHazardRecognizer::EmitInstruction (SUnit *) override virtual
EmitInstruction - This callback is invoked when an instruction is emitted, to advance the hazard state.
Reimplemented from llvm::ScheduleHazardRecognizer.
Definition at line 174 of file PPCHazardRecognizers.cpp.
References llvm::dbgs(), llvm::ScheduleDAG::dumpNode(), llvm::ScoreboardHazardRecognizer::EmitInstruction(), llvm::ScheduleDAG::getInstrDesc(), llvm::MCInstrDesc::isBranch(), and LLVM_DEBUG.
EmitNoop()
void PPCDispatchGroupSBHazardRecognizer::EmitNoop () override virtual
EmitNoop - This callback is invoked when a noop was added to the instruction stream.
Reimplemented from llvm::ScheduleHazardRecognizer.
Definition at line 219 of file PPCHazardRecognizers.cpp.
References llvm::PPC::DIR_PWR6, llvm::PPC::DIR_PWR7, llvm::PPC::DIR_PWR8, llvm::PPC::DIR_PWR9, llvm::MachineFunction::getSubtarget(), and llvm::ScheduleDAG::MF.
getHazardType()
ScheduleHazardRecognizer::HazardType PPCDispatchGroupSBHazardRecognizer::getHazardType (SUnit * m, int Stalls) override virtual
getHazardType - Return the hazard type of emitting this node.
There are three possible results. Either:
NoHazard: it is legal to issue this instruction on this cycle.
Hazard: issuing this instruction would stall the machine. If some other instruction is available, issue it first.
NoopHazard: issuing this instruction would break the program. If some other instruction can be issued, do so, otherwise issue a noop.
Reimplemented from llvm::ScheduleHazardRecognizer.
Definition at line 139 of file PPCHazardRecognizers.cpp.
References llvm::ScoreboardHazardRecognizer::getHazardType(), and llvm::ScheduleHazardRecognizer::NoopHazard.
PreEmitNoops()
unsigned PPCDispatchGroupSBHazardRecognizer::PreEmitNoops (SUnit *) override virtual
PreEmitNoops - This callback is invoked prior to emitting an instruction.
It should return the number of noops to emit prior to the provided instruction. Note: This is only used during PostRA scheduling. EmitNoop is not called for these noops.
Reimplemented from llvm::ScheduleHazardRecognizer.
Definition at line 155 of file PPCHazardRecognizers.cpp.
References llvm::PPC::DIR_PWR6, llvm::PPC::DIR_PWR7, llvm::PPC::DIR_PWR8, llvm::PPC::DIR_PWR9, llvm::MachineFunction::getSubtarget(), llvm::ScheduleDAG::MF, and llvm::ScheduleHazardRecognizer::PreEmitNoops().
RecedeCycle()
void PPCDispatchGroupSBHazardRecognizer::RecedeCycle () override virtual
RecedeCycle - This callback is invoked whenever the next bottom-up instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts.
Reimplemented from llvm::ScheduleHazardRecognizer.
Definition at line 209 of file PPCHazardRecognizers.cpp.
References llvm_unreachable.
Reset()
void PPCDispatchGroupSBHazardRecognizer::Reset () override virtual
Reset - This callback is invoked when a new block of instructions is about to be schedule.
The hazard state should be set to an initialized state.
Reimplemented from llvm::ScheduleHazardRecognizer.
Definition at line 213 of file PPCHazardRecognizers.cpp.
References llvm::ScoreboardHazardRecognizer::Reset().
ShouldPreferAnother()
bool PPCDispatchGroupSBHazardRecognizer::ShouldPreferAnother (SUnit *) override virtual
ShouldPreferAnother - This callback may be invoked if getHazardType returns NoHazard.
If, even though there is no hazard, it would be better to schedule another available instruction, this callback should return true.
Reimplemented from llvm::ScheduleHazardRecognizer.
Definition at line 146 of file PPCHazardRecognizers.cpp.
References llvm::ScheduleDAG::getInstrDesc(), and llvm::ScheduleHazardRecognizer::ShouldPreferAnother().
The documentation for this class was generated from the following files:
lib/Target/PowerPC/PPCHazardRecognizers.h
lib/Target/PowerPC/PPCHazardRecognizers.cpp