LLVM: llvm::ErrorDiagnostic Class Reference
llvm::ErrorDiagnostic Class Reference
Class to represent an error holding a diagnostic with location information used when printing it.
#include "Support/FileCheckImpl.h"
Public Member Functions
ErrorDiagnostic (SMDiagnostic &&Diag)
std::error_code convertToErrorCode () const override
Convert this error to a std::error_code.
void log (raw_ostream &OS) const override
Print diagnostic associated with this error when printing the error.
Public Member Functions inherited from llvm::ErrorInfo< ErrorDiagnostic >
const void * dynamicClassID () const override
bool isA (const void *const ClassID) const override
Public Member Functions inherited from llvm::ErrorInfoBase
virtual ~ErrorInfoBase ()=default
virtual std::string message () const
Return the error message as a string.
template<typename ErrorInfoT >
bool isA () const
Static Public Member Functions
static Error get (const SourceMgr &SM, SMLoc Loc, const Twine &ErrMsg)
static Error get (const SourceMgr &SM, StringRef Buffer, const Twine &ErrMsg)
Static Public Member Functions inherited from llvm::ErrorInfo< ErrorDiagnostic >
static const void * classID ()
Static Public Member Functions inherited from llvm::ErrorInfoBase
static const void * classID ()
Static Public Attributes
static char ID = 0
Detailed Description
Class to represent an error holding a diagnostic with location information used when printing it.
Definition at line 509 of file FileCheckImpl.h.
Constructor & Destructor Documentation
ErrorDiagnostic()
llvm::ErrorDiagnostic::ErrorDiagnostic (SMDiagnostic && Diag) inline
Definition at line 516 of file FileCheckImpl.h.
Member Function Documentation
convertToErrorCode()
std::error_code llvm::ErrorDiagnostic::convertToErrorCode () const inline override virtual
Convert this error to a std::error_code.
This is a temporary crutch to enable interaction with code still using std::error_code. It will be removed in the future.
Implements llvm::ErrorInfoBase.
Definition at line 518 of file FileCheckImpl.h.
References llvm::inconvertibleErrorCode().
get() [1/2]
static Error llvm::ErrorDiagnostic::get (const SourceMgr & SM, SMLoc Loc, const Twine & ErrMsg) inline static
Definition at line 525 of file FileCheckImpl.h.
References llvm::SourceMgr::DK_Error, and llvm::SourceMgr::GetMessage().
Referenced by llvm::FileCheckPatternContext::defineCmdlineVariables(), get(), llvm::BinaryOperation::getImplicitFormat(), llvm::Pattern::parseNumericSubstitutionBlock(), llvm::Pattern::parseVariable(), and llvm::ExpressionFormat::valueFromStringRepr().
get() [2/2]
static Error llvm::ErrorDiagnostic::get (const SourceMgr & SM, StringRef Buffer, const Twine & ErrMsg) inline static
Definition at line 530 of file FileCheckImpl.h.
References llvm::StringRef::data(), get(), and llvm::SMLoc::getFromPointer().
log()
void llvm::ErrorDiagnostic::log (raw_ostream & OS) const inline override virtual
Print diagnostic associated with this error when printing the error.
Implements llvm::ErrorInfoBase.
Definition at line 523 of file FileCheckImpl.h.
References llvm::SMDiagnostic::print().
Member Data Documentation
ID
char ErrorDiagnostic::ID = 0 static
Definition at line 514 of file FileCheckImpl.h.
The documentation for this class was generated from the following files:
lib/Support/FileCheckImpl.h
lib/Support/FileCheck.cpp