LLVM: llvm::TargetRegisterInfo Class Reference
llvm::TargetRegisterInfo Class Reference abstract
TargetRegisterInfo base class - We assume that the target defines a static array of TargetRegisterDesc objects that represent all of the machine registers that the target has.
#include "llvm/CodeGen/TargetRegisterInfo.h"
Classes
struct RegClassInfo
Public Types
using regclass_iterator = const TargetRegisterClass * const *
using vt_iterator = const MVT::SimpleValueType *
Public Types inherited from llvm::MCRegisterInfo
using regclass_iterator = const MCRegisterClass *
Public Member Functions
unsigned getRegSizeInBits (const TargetRegisterClass &RC) const
Return the size in bits of a register from class RC.
unsigned getSpillSize (const TargetRegisterClass &RC) const
Return the size in bytes of the stack slot allocated to hold a spilled copy of a register from class RC.
unsigned getSpillAlignment (const TargetRegisterClass &RC) const
Return the minimum required alignment in bytes for a spill slot for a register of this class.
Align getSpillAlign (const TargetRegisterClass &RC) const
Return the minimum required alignment in bytes for a spill slot for a register of this class.
bool isTypeLegalForClass (const TargetRegisterClass &RC, MVT T) const
Return true if the given TargetRegisterClass has the ValueType T.
vt_iterator legalclasstypes_begin (const TargetRegisterClass &RC) const
Loop over all of the value types that can be represented by values in the given register class.
vt_iterator legalclasstypes_end (const TargetRegisterClass &RC) const
const TargetRegisterClass * getMinimalPhysRegClass (MCRegister Reg, MVT VT=MVT::Other) const
Returns the Register Class of a physical register of the given type, picking the most sub register class of the right type that contains this physreg.
const TargetRegisterClass * getAllocatableClass (const TargetRegisterClass *RC) const
Return the maximal subclass of the given register class that is allocatable or NULL.
BitVector getAllocatableSet (const MachineFunction &MF, const TargetRegisterClass *RC=nullptr) const
Returns a bitset indexed by register number indicating if a register is allocatable or not.
unsigned getCostPerUse (MCRegister RegNo) const
Return the additional cost of using this register instead of other registers in its class.
bool isInAllocatableClass (MCRegister RegNo) const
Return true if the register is in the allocation of any register class.
const char * getSubRegIndexName (unsigned SubIdx) const
Return the human-readable symbolic target-specific name for the specified SubRegIndex.
LaneBitmask getSubRegIndexLaneMask (unsigned SubIdx) const
Return a bitmask representing the parts of a register that are covered by SubIdx.
LaneBitmask getCoveringLanes () const
The lane masks returned by getSubRegIndexLaneMask() above can only be used to determine if sub-registers overlap - they can't be used to determine if a set of sub-registers completely cover another sub-register.
bool regsOverlap (Register regA, Register regB) const
Returns true if the two registers are equal or alias each other.
bool hasRegUnit (MCRegister Reg, unsigned RegUnit) const
Returns true if Reg contains RegUnit.
virtual Register lookThruCopyLike (Register SrcReg, const MachineRegisterInfo *MRI) const
Returns the original SrcReg unless it is the target of a copy-like operation, in which case we chain backwards through all such operations to the ultimate source register.
virtual const MCPhysReg * getCalleeSavedRegs (const MachineFunction *MF) const =0
Return a null-terminated list of all of the callee-saved registers on this target.
virtual const uint32_t * getCallPreservedMask (const MachineFunction &MF, CallingConv::ID) const
Return a mask of call-preserved registers for the given calling convention on the current function.
virtual const uint32_t * getNoPreservedMask () const
Return a register mask that clobbers everything.
virtual ArrayRef< MCPhysReg > getIntraCallClobberedRegs (const MachineFunction *MF) const
Return a list of all of the registers which are clobbered "inside" a call to the given function.
bool regmaskSubsetEqual (const uint32_t *mask0, const uint32_t *mask1) const
Return true if all bits that are set in mask mask0 are also set in mask1.
virtual ArrayRef< const uint32_t * > getRegMasks () const =0
Return all the call-preserved register masks defined for this target.
virtual ArrayRef< const char * > getRegMaskNames () const =0
virtual BitVector getReservedRegs (const MachineFunction &MF) const =0
Returns a bitset indexed by physical register number indicating if a register is a special register that has particular uses and should be considered unavailable at all times, e.g.
virtual bool isAsmClobberable (const MachineFunction &MF, MCRegister PhysReg) const
Returns false if we can't guarantee that Physreg, specified as an IR asm clobber constraint, will be preserved across the statement.
virtual bool isInlineAsmReadOnlyReg (const MachineFunction &MF, unsigned PhysReg) const
Returns true if PhysReg cannot be written to in inline asm statements.
virtual bool isConstantPhysReg (MCRegister PhysReg) const
Returns true if PhysReg is unallocatable and constant throughout the function.
virtual bool isDivergentRegClass (const TargetRegisterClass *RC) const
Returns true if the register class is considered divergent.
virtual bool isCallerPreservedPhysReg (MCRegister PhysReg, const MachineFunction &MF) const
Physical registers that may be modified within a function but are guaranteed to be restored before any uses.
virtual bool isCalleeSavedPhysReg (MCRegister PhysReg, const MachineFunction &MF) const
This is a wrapper around getCallPreservedMask().
virtual void adjustStackMapLiveOutMask (uint32_t *Mask) const
Prior to adding the live-out mask to a stackmap or patchpoint instruction, provide the target the opportunity to adjust it (mainly to remove pseudo-registers that should be ignored).
MCRegister getMatchingSuperReg (MCRegister Reg, unsigned SubIdx, const TargetRegisterClass *RC) const
Return a super-register of the specified register Reg so its sub-register of index SubIdx is Reg.
virtual const TargetRegisterClass * getMatchingSuperRegClass (const TargetRegisterClass *A, const TargetRegisterClass *B, unsigned Idx) const
Return a subclass of the specified register class A so that each register in it has a sub-register of the specified sub-register index which is in the specified register class B.
virtual bool shouldRewriteCopySrc (const TargetRegisterClass *DefRC, unsigned DefSubReg, const TargetRegisterClass *SrcRC, unsigned SrcSubReg) const
virtual const TargetRegisterClass * getSubClassWithSubReg (const TargetRegisterClass *RC, unsigned Idx) const
Returns the largest legal sub-class of RC that supports the sub-register index Idx.
unsigned composeSubRegIndices (unsigned a, unsigned b) const
Return the subregister index you get from composing two subregister indices.
LaneBitmask composeSubRegIndexLaneMask (unsigned IdxA, LaneBitmask Mask) const
Transforms a LaneMask computed for one subregister to the lanemask that would have been computed when composing the subsubregisters with IdxA first.
LaneBitmask reverseComposeSubRegIndexLaneMask (unsigned IdxA, LaneBitmask LaneMask) const
Transform a lanemask given for a virtual register to the corresponding lanemask before using subregister with index IdxA.
const TargetRegisterClass * getCommonSuperRegClass (const TargetRegisterClass *RCA, unsigned SubA, const TargetRegisterClass *RCB, unsigned SubB, unsigned &PreA, unsigned &PreB) const
Find a common super-register class if it exists.
regclass_iterator regclass_begin () const
Register class iterators.
regclass_iterator regclass_end () const
iterator_range< regclass_iterator > regclasses () const
unsigned getNumRegClasses () const
const TargetRegisterClass * getRegClass (unsigned i) const
Returns the register class associated with the enumeration value.
const char * getRegClassName (const TargetRegisterClass *Class) const
Returns the name of the register class.
const TargetRegisterClass * getCommonSubClass (const TargetRegisterClass *A, const TargetRegisterClass *B) const
Find the largest common subclass of A and B.
virtual const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const
Returns a TargetRegisterClass used for pointer values.
virtual const TargetRegisterClass * getCrossCopyRegClass (const TargetRegisterClass *RC) const
Returns a legal register class to copy a register in the specified class to or from.
virtual const TargetRegisterClass * getLargestLegalSuperClass (const TargetRegisterClass *RC, const MachineFunction &) const
Returns the largest super class of RC that is legal to use in the current sub-target and has the same spill size.
virtual unsigned getRegPressureLimit (const TargetRegisterClass *RC, MachineFunction &MF) const
Return the register pressure "high water mark" for the specific register class.
virtual unsigned getRegPressureSetScore (const MachineFunction &MF, unsigned PSetID) const
Return a heuristic for the machine scheduler to compare the profitability of increasing one register pressure set versus another.
virtual const RegClassWeight & getRegClassWeight (const TargetRegisterClass *RC) const =0
Get the weight in units of pressure for this register class.
unsigned getRegSizeInBits (Register Reg, const MachineRegisterInfo &MRI) const
Returns size in bits of a phys/virtual/generic register.
virtual unsigned getRegUnitWeight (unsigned RegUnit) const =0
Get the weight in units of pressure for this register unit.
virtual unsigned getNumRegPressureSets () const =0
Get the number of dimensions of register pressure.
virtual const char * getRegPressureSetName (unsigned Idx) const =0
Get the name of this register unit pressure set.
virtual unsigned getRegPressureSetLimit (const MachineFunction &MF, unsigned Idx) const =0
Get the register unit pressure limit for this dimension.
virtual const int * getRegClassPressureSets (const TargetRegisterClass *RC) const =0
Get the dimensions of register pressure impacted by this register class.
virtual const int * getRegUnitPressureSets (unsigned RegUnit) const =0
Get the dimensions of register pressure impacted by this register unit.
virtual bool getRegAllocationHints (Register VirtReg, ArrayRef< MCPhysReg > Order, SmallVectorImpl< MCPhysReg > &Hints, const MachineFunction &MF, const VirtRegMap *VRM=nullptr, const LiveRegMatrix *Matrix=nullptr) const
Get a list of 'hint' registers that the register allocator should try first when allocating a physical register for the virtual register VirtReg.
virtual void updateRegAllocHint (Register Reg, Register NewReg, MachineFunction &MF) const
A callback to allow target a chance to update register allocation hints when a register is "changed" (e.g.
virtual bool reverseLocalAssignment () const
Allow the target to reverse allocation order of local live ranges.
virtual unsigned getCSRFirstUseCost () const
Allow the target to override the cost of using a callee-saved register for the first time.
virtual bool requiresRegisterScavenging (const MachineFunction &MF) const
Returns true if the target requires (and can make use of) the register scavenger.
virtual bool useFPForScavengingIndex (const MachineFunction &MF) const
Returns true if the target wants to use frame pointer based accesses to spill to the scavenger emergency spill slot.
virtual bool requiresFrameIndexScavenging (const MachineFunction &MF) const
Returns true if the target requires post PEI scavenging of registers for materializing frame index constants.
virtual bool requiresFrameIndexReplacementScavenging (const MachineFunction &MF) const
Returns true if the target requires using the RegScavenger directly for frame elimination despite using requiresFrameIndexScavenging.
virtual bool requiresVirtualBaseRegisters (const MachineFunction &MF) const
Returns true if the target wants the LocalStackAllocation pass to be run and virtual base registers used for more efficient stack access.
virtual bool hasReservedSpillSlot (const MachineFunction &MF, Register Reg, int &FrameIdx) const
Return true if target has reserved a spill slot in the stack frame of the given function for the specified register.
virtual bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const
Returns true if the live-ins should be tracked after register allocation.
virtual bool canRealignStack (const MachineFunction &MF) const
True if the stack can be realigned for the target.
bool needsStackRealignment (const MachineFunction &MF) const
True if storage within the function requires the stack pointer to be aligned more than the normal calling convention calls for.
virtual int64_t getFrameIndexInstrOffset (const MachineInstr *MI, int Idx) const
Get the offset from the referenced frame index in the instruction, if there is one.
virtual bool needsFrameBaseReg (MachineInstr *MI, int64_t Offset) const
Returns true if the instruction's frame index reference would be better served by a base register other than FP or SP.
virtual void materializeFrameBaseRegister (MachineBasicBlock *MBB, Register BaseReg, int FrameIdx, int64_t Offset) const
Insert defining instruction(s) for BaseReg to be a pointer to FrameIdx before insertion point I.
virtual void resolveFrameIndex (MachineInstr &MI, Register BaseReg, int64_t Offset) const
Resolve a frame index operand of an instruction to reference the indicated base register plus offset instead.
virtual bool isFrameOffsetLegal (const MachineInstr *MI, Register BaseReg, int64_t Offset) const
Determine whether a given base register plus offset immediate is encodable to resolve a frame index.
virtual bool saveScavengerRegister (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, MachineBasicBlock::iterator &UseMI, const TargetRegisterClass *RC, Register Reg) const
Spill the register so it can be used by the register scavenger.
virtual void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=nullptr) const =0
This method must be overriden to eliminate abstract frame indices from instructions which may use them.
virtual StringRef getRegAsmName (MCRegister Reg) const
Return the assembly name for Reg.
virtual bool shouldCoalesce (MachineInstr *MI, const TargetRegisterClass *SrcRC, unsigned SubReg, const TargetRegisterClass *DstRC, unsigned DstSubReg, const TargetRegisterClass *NewRC, LiveIntervals &LIS) const
Subtarget Hooks.
virtual bool shouldRegionSplitForVirtReg (const MachineFunction &MF, const LiveInterval &VirtReg) const
Region split has a high compile time cost especially for large live range.
virtual Register getFrameRegister (const MachineFunction &MF) const =0
Debug information queries.
void markSuperRegs (BitVector &RegisterSet, MCRegister Reg) const
Mark a register and all its aliases as reserved in the given set.
bool checkAllSuperRegsMarked (const BitVector &RegisterSet, ArrayRef< MCPhysReg > Exceptions=ArrayRef< MCPhysReg >()) const
Returns true if for every register in the set all super registers are part of the set as well.
virtual const TargetRegisterClass * getConstrainedRegClassForOperand (const MachineOperand &MO, const MachineRegisterInfo &MRI) const
Register getSubReg (MCRegister Reg, unsigned Idx) const
Returns the physical register number of sub-register "Index" for physical register RegNo.
Public Member Functions inherited from llvm::MCRegisterInfo
iterator_range< mc_subreg_iterator > subregs (MCRegister Reg) const
Return an iterator range over all sub-registers of Reg, excluding Reg.
iterator_range< mc_subreg_iterator > subregs_inclusive (MCRegister Reg) const
Return an iterator range over all sub-registers of Reg, including Reg.
iterator_range< mc_superreg_iterator > superregs (MCRegister Reg) const
Return an iterator range over all super-registers of Reg, excluding Reg.
iterator_range< mc_superreg_iterator > superregs_inclusive (MCRegister Reg) const
Return an iterator range over all super-registers of Reg, including Reg.
detail::concat_range< const MCPhysReg, iterator_range< mc_subreg_iterator >, iterator_range< mc_superreg_iterator > > sub_and_superregs_inclusive (MCRegister Reg) const
Return an iterator range over all sub- and super-registers of Reg, including Reg.
void InitMCRegisterInfo (const MCRegisterDesc *D, unsigned NR, unsigned RA, unsigned PC, const MCRegisterClass *C, unsigned NC, const MCPhysReg(*RURoots)[2], unsigned NRU, const MCPhysReg *DL, const LaneBitmask *RUMS, const char *Strings, const char *ClassStrings, const uint16_t *SubIndices, unsigned NumIndices, const SubRegCoveredBits *SubIdxRanges, const uint16_t *RET)
Initialize MCRegisterInfo, called by TableGen auto-generated routines.
void mapLLVMRegsToDwarfRegs (const DwarfLLVMRegPair *Map, unsigned Size, bool isEH)
Used to initialize LLVM register to Dwarf register number mapping.
void mapDwarfRegsToLLVMRegs (const DwarfLLVMRegPair *Map, unsigned Size, bool isEH)
Used to initialize Dwarf register to LLVM register number mapping.
void mapLLVMRegToSEHReg (MCRegister LLVMReg, int SEHReg)
mapLLVMRegToSEHReg - Used to initialize LLVM register to SEH register number mapping.
void mapLLVMRegToCVReg (MCRegister LLVMReg, int CVReg)
MCRegister getRARegister () const
This method should return the register where the return address can be found.
MCRegister getProgramCounter () const
Return the register which is the program counter.
const MCRegisterDesc & operator[] (MCRegister RegNo) const
const MCRegisterDesc & get (MCRegister RegNo) const
Provide a get method, equivalent to [], but more useful with a pointer to this object.
MCRegister getSubReg (MCRegister Reg, unsigned Idx) const
Returns the physical register number of sub-register "Index" for physical register RegNo.
MCRegister getMatchingSuperReg (MCRegister Reg, unsigned SubIdx, const MCRegisterClass *RC) const
Return a super-register of the specified register Reg so its sub-register of index SubIdx is Reg.
unsigned getSubRegIndex (MCRegister RegNo, MCRegister SubRegNo) const
For a given register pair, return the sub-register index if the second register is a sub-register of the first.
unsigned getSubRegIdxSize (unsigned Idx) const
Get the size of the bit range covered by a sub-register index.
unsigned getSubRegIdxOffset (unsigned Idx) const
Get the offset of the bit range covered by a sub-register index.
const char * getName (MCRegister RegNo) const
Return the human-readable symbolic target-specific name for the specified physical register.
unsigned getNumRegs () const
Return the number of registers this target has (useful for sizing arrays holding per register information)
unsigned getNumSubRegIndices () const
Return the number of sub-register indices understood by the target.
unsigned getNumRegUnits () const
Return the number of (native) register units in the target.
int getDwarfRegNum (MCRegister RegNum, bool isEH) const
Map a target register to an equivalent dwarf register number.
Optional< unsigned > getLLVMRegNum (unsigned RegNum, bool isEH) const
Map a dwarf register back to a target register.
int getDwarfRegNumFromDwarfEHRegNum (unsigned RegNum) const
Map a target EH register number to an equivalent DWARF register number.
int getSEHRegNum (MCRegister RegNum) const
Map a target register to an equivalent SEH register number.
int getCodeViewRegNum (MCRegister RegNum) const
Map a target register to an equivalent CodeView register number.
regclass_iterator regclass_begin () const
regclass_iterator regclass_end () const
iterator_range< regclass_iterator > regclasses () const
unsigned getNumRegClasses () const
const MCRegisterClass & getRegClass (unsigned i) const
Returns the register class associated with the enumeration value.
const char * getRegClassName (const MCRegisterClass *Class) const
uint16_t getEncodingValue (MCRegister RegNo) const
Returns the encoding for RegNo.
bool isSubRegister (MCRegister RegA, MCRegister RegB) const
Returns true if RegB is a sub-register of RegA.
bool isSuperRegister (MCRegister RegA, MCRegister RegB) const
Returns true if RegB is a super-register of RegA.
bool isSubRegisterEq (MCRegister RegA, MCRegister RegB) const
Returns true if RegB is a sub-register of RegA or if RegB == RegA.
bool isSuperRegisterEq (MCRegister RegA, MCRegister RegB) const
Returns true if RegB is a super-register of RegA or if RegB == RegA.
bool isSuperOrSubRegisterEq (MCRegister RegA, MCRegister RegB) const
Returns true if RegB is a super-register or sub-register of RegA or if RegB == RegA.
Static Public Member Functions
static void dumpReg (Register Reg, unsigned SubRegIndex=0, const TargetRegisterInfo *TRI=nullptr)
Debugging helper: dump register in human readable form to dbgs() stream.
Protected Member Functions
TargetRegisterInfo (const TargetRegisterInfoDesc *ID, regclass_iterator RCB, regclass_iterator RCE, const char *const *SRINames, const LaneBitmask *SRILaneMasks, LaneBitmask CoveringLanes, const RegClassInfo *const RCIs, unsigned Mode=0)
virtual ~TargetRegisterInfo ()
virtual unsigned composeSubRegIndicesImpl (unsigned, unsigned) const
Overridden by TableGen in targets that have sub-registers.
virtual LaneBitmask composeSubRegIndexLaneMaskImpl (unsigned, LaneBitmask) const
Overridden by TableGen in targets that have sub-registers.
virtual LaneBitmask reverseComposeSubRegIndexLaneMaskImpl (unsigned, LaneBitmask) const
const RegClassInfo & getRegClassInfo (const TargetRegisterClass &RC) const
Detailed Description
TargetRegisterInfo base class - We assume that the target defines a static array of TargetRegisterDesc objects that represent all of the machine registers that the target has.
As such, we simply have to track a pointer to this array so that we can turn register number into a register descriptor.
Definition at line 229 of file TargetRegisterInfo.h.
Member Typedef Documentation
regclass_iterator
using llvm::TargetRegisterInfo::regclass_iterator = const TargetRegisterClass * const *
Definition at line 231 of file TargetRegisterInfo.h.
vt_iterator
using llvm::TargetRegisterInfo::vt_iterator = const MVT::SimpleValueType *
Definition at line 232 of file TargetRegisterInfo.h.
Constructor & Destructor Documentation
TargetRegisterInfo()
TargetRegisterInfo::TargetRegisterInfo (const TargetRegisterInfoDesc * ID, regclass_iterator RCB, regclass_iterator RCE, const char *const * SRINames, const LaneBitmask * SRILaneMasks, LaneBitmask CoveringLanes, const RegClassInfo *const RCIs, unsigned Mode = 0) protected
Definition at line 51 of file TargetRegisterInfo.cpp.
~TargetRegisterInfo()
TargetRegisterInfo::~TargetRegisterInfo () protected virtual default
Member Function Documentation
adjustStackMapLiveOutMask()
virtual void llvm::TargetRegisterInfo::adjustStackMapLiveOutMask (uint32_t * Mask) const inline virtual
Prior to adding the live-out mask to a stackmap or patchpoint instruction, provide the target the opportunity to adjust it (mainly to remove pseudo-registers that should be ignored).
Definition at line 525 of file TargetRegisterInfo.h.
canRealignStack()
bool TargetRegisterInfo::canRealignStack (const MachineFunction & MF) const virtual
True if the stack can be realigned for the target.
Definition at line 459 of file TargetRegisterInfo.cpp.
References llvm::MachineFunction::getFunction(), and llvm::Function::hasFnAttribute().
Referenced by llvm::SIRegisterInfo::canRealignStack(), llvm::ARMBaseRegisterInfo::canRealignStack(), llvm::MipsRegisterInfo::canRealignStack(), llvm::SparcRegisterInfo::canRealignStack(), llvm::VERegisterInfo::canRealignStack(), llvm::X86RegisterInfo::canRealignStack(), and needsStackRealignment().
checkAllSuperRegsMarked()
bool TargetRegisterInfo::checkAllSuperRegsMarked (const BitVector & RegisterSet, ArrayRef< MCPhysReg > Exceptions = ArrayRef<MCPhysReg>()) const
Returns true if for every register in the set all super registers are part of the set as well.
Definition at line 84 of file TargetRegisterInfo.cpp.
References llvm::dbgs(), llvm::MCRegisterInfo::getNumRegs(), llvm::is_contained(), llvm::MCRegisterInfo::DiffListIterator::isValid(), and llvm::printReg().
composeSubRegIndexLaneMask()
LaneBitmask llvm::TargetRegisterInfo::composeSubRegIndexLaneMask (unsigned IdxA, LaneBitmask Mask) const inline
Transforms a LaneMask computed for one subregister to the lanemask that would have been computed when composing the subsubregisters with IdxA first.
See also
composeSubRegIndices()
Definition at line 592 of file TargetRegisterInfo.h.
References composeSubRegIndexLaneMaskImpl().
Referenced by llvm::rdf::PhysicalRegisterInfo::mapTo().
composeSubRegIndexLaneMaskImpl()
virtual LaneBitmask llvm::TargetRegisterInfo::composeSubRegIndexLaneMaskImpl (unsigned , LaneBitmask) const inline protected virtual
Overridden by TableGen in targets that have sub-registers.
Definition at line 625 of file TargetRegisterInfo.h.
References llvm_unreachable.
Referenced by composeSubRegIndexLaneMask().
composeSubRegIndices()
unsigned llvm::TargetRegisterInfo::composeSubRegIndices (unsigned a, unsigned b) const inline
Return the subregister index you get from composing two subregister indices.
The special null sub-register index composes as the identity.
If R:a:b is the same register as R:c, then composeSubRegIndices(a, b) returns c. Note that composeSubRegIndices does not tell you about illegal compositions. If R does not have a subreg a, or R:a does not have a subreg b, composeSubRegIndices doesn't tell you.
The ARM register Q0 has two D subregs dsub_0:D0 and dsub_1:D1. It also has ssub_0:S0 - ssub_3:S3 subregs. If you compose subreg indices dsub_1, ssub_0 you get ssub_2.
Definition at line 583 of file TargetRegisterInfo.h.
References composeSubRegIndicesImpl().
Referenced by getCommonSuperRegClass().
composeSubRegIndicesImpl()
virtual unsigned llvm::TargetRegisterInfo::composeSubRegIndicesImpl (unsigned , unsigned) const inline protected virtual
Overridden by TableGen in targets that have sub-registers.
Definition at line 619 of file TargetRegisterInfo.h.
References llvm_unreachable.
Referenced by composeSubRegIndices().
dumpReg()
LLVM_DUMP_METHOD void TargetRegisterInfo::dumpReg (Register Reg, unsigned SubRegIndex = 0, const TargetRegisterInfo * TRI = nullptr) static
Debugging helper: dump register in human readable form to dbgs() stream.
Definition at line 537 of file TargetRegisterInfo.cpp.
References llvm::dbgs(), llvm::printReg(), and TRI.
eliminateFrameIndex()
virtual void llvm::TargetRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = nullptr) const pure virtual
This method must be overriden to eliminate abstract frame indices from instructions which may use them.
The instruction referenced by the iterator contains an MO_FrameIndex operand which must be eliminated by this method. This method may modify or replace the specified instruction, as long as it keeps the iterator pointing at the finished product. SPAdj is the SP adjustment due to call frame setup instruction. FIOperandNum is the FI operand number.
getAllocatableClass()
const TargetRegisterClass * TargetRegisterInfo::getAllocatableClass (const TargetRegisterClass * RC) const
Return the maximal subclass of the given register class that is allocatable or NULL.
getAllocatableClass - Return the maximal subclass of the given register class that is alloctable, or NULL.
Definition at line 193 of file TargetRegisterInfo.cpp.
References getRegClass(), llvm::TargetRegisterClass::getSubClassMask(), and llvm::TargetRegisterClass::isAllocatable().
Referenced by getAllocatableSet().
getAllocatableSet()
BitVector TargetRegisterInfo::getAllocatableSet (const MachineFunction & MF, const TargetRegisterClass * RC = nullptr) const
Returns a bitset indexed by register number indicating if a register is allocatable or not.
If a register class is specified, returns the subset for the class.
Definition at line 237 of file TargetRegisterInfo.cpp.
References C, llvm::BitVector::flip(), getAllocatableClass(), getAllocatableSetForRC(), llvm::MCRegisterInfo::getNumRegs(), getReservedRegs(), and regclasses().
Referenced by llvm::AggressiveAntiDepBreaker::AggressiveAntiDepBreaker(), and llvm::RegScavenger::scavengeRegister().
getCalleeSavedRegs()
virtual const MCPhysReg * llvm::TargetRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const pure virtual
Return a null-terminated list of all of the callee-saved registers on this target.
The register should be in the order of desired callee-save stack frame offset. The first register is closest to the incoming stack pointer if stack grows down, and vice versa. Notice: This function does not take into account disabled CSRs. In most cases you will want to use instead the function getCalleeSavedRegs that is implemented in MachineRegisterInfo.
Referenced by llvm::MachineRegisterInfo::getCalleeSavedRegs().
getCallPreservedMask()
virtual const uint32_t * llvm::TargetRegisterInfo::getCallPreservedMask (const MachineFunction & MF, CallingConv::ID) const inline virtual
Return a mask of call-preserved registers for the given calling convention on the current function.
The mask should include all call-preserved aliases. This is used by the register allocator to determine which registers can be live across a call.
The mask is an array containing (TRI::getNumRegs()+31)/32 entries. A set bit indicates that all bits of the corresponding register are preserved across the function call. The bit mask is expected to be sub-register complete, i.e. if A is preserved, so are all its sub-registers.
Bits are numbered from the LSB, so the bit for physical register Reg can be found as (Mask[Reg / 32] >> Reg % 32) & 1.
A NULL pointer means that no register mask will be used, and call instructions should use implicit-def operands to indicate call clobbered registers.
Definition at line 446 of file TargetRegisterInfo.h.
Referenced by isCalleeSavedPhysReg(), and llvm::FastISel::selectPatchpoint().
getCommonSubClass()
const TargetRegisterClass * TargetRegisterInfo::getCommonSubClass (const TargetRegisterClass * A, const TargetRegisterClass * B) const
Find the largest common subclass of A and B.
Return NULL if there is no common subclass.
Definition at line 269 of file TargetRegisterInfo.cpp.
References A, B, and firstCommonClass().
Referenced by llvm::LiveStacks::getOrCreateInterval().
getCommonSuperRegClass()
const TargetRegisterClass * TargetRegisterInfo::getCommonSuperRegClass (const TargetRegisterClass * RCA, unsigned SubA, const TargetRegisterClass * RCB, unsigned SubB, unsigned & PreA, unsigned & PreB) const
Find a common super-register class if it exists.
Find a register class, SuperRC and two sub-register indices, PreA and PreB, such that:
PreA + SubA == PreB + SubB (using composeSubRegIndices()), and
For all Reg in SuperRC: Reg:PreA in RCA and Reg:PreB in RCB, and
SuperRC->getSize() >= max(RCA->getSize(), RCB->getSize()).
SuperRC will be chosen such that no super-class of SuperRC satisfies the requirements, and there is no register class with a smaller spill size that satisfies the requirements.
SubA and SubB must not be 0. Use getMatchingSuperRegClass() instead.
Either of the PreA and PreB sub-register indices may be returned as 0. In that case, the returned register class will be a sub-class of the corresponding argument register class.
The function returns NULL if no register class can be found.
Definition at line 298 of file TargetRegisterInfo.cpp.
References assert(), composeSubRegIndices(), firstCommonClass(), getRegSizeInBits(), llvm::SuperRegClassIterator::isValid(), and std::swap().
getConstrainedRegClassForOperand()
virtual const TargetRegisterClass * llvm::TargetRegisterInfo::getConstrainedRegClassForOperand (const MachineOperand & MO, const MachineRegisterInfo & MRI) const inline virtual
Definition at line 989 of file TargetRegisterInfo.h.
getCostPerUse()
unsigned llvm::TargetRegisterInfo::getCostPerUse (MCRegister RegNo) const inline
Return the additional cost of using this register instead of other registers in its class.
Definition at line 334 of file TargetRegisterInfo.h.
References llvm::TargetRegisterInfoDesc::CostPerUse.
getCoveringLanes()
LaneBitmask llvm::TargetRegisterInfo::getCoveringLanes () const inline
The lane masks returned by getSubRegIndexLaneMask() above can only be used to determine if sub-registers overlap - they can't be used to determine if a set of sub-registers completely cover another sub-register.
The X86 general purpose registers have two lanes corresponding to the sub_8bit and sub_8bit_hi sub-registers. Both sub_32bit and sub_16bit have lane masks '3', but the sub_16bit sub-register doesn't fully cover the sub_32bit sub-register.
On the other hand, the ARM NEON lanes fully cover their registers: The dsub_0 sub-register is completely covered by the ssub_0 and ssub_1 lanes. This is related to the CoveredBySubRegs property on register definitions.
This function returns a bit mask of lanes that completely cover their sub-registers. More precisely, given:
Covering = getCoveringLanes(); MaskA = getSubRegIndexLaneMask(SubA); MaskB = getSubRegIndexLaneMask(SubB);
If (MaskA & ~(MaskB & Covering)) == 0, then SubA is completely covered by SubB.
Definition at line 383 of file TargetRegisterInfo.h.
getCrossCopyRegClass()
virtual const TargetRegisterClass * llvm::TargetRegisterInfo::getCrossCopyRegClass (const TargetRegisterClass * RC) const inline virtual
Returns a legal register class to copy a register in the specified class to or from.
If it is possible to copy the register directly without using a cross register class copy, return the specified RC. Returns NULL if it is not possible to copy between two registers of the specified class.
Definition at line 713 of file TargetRegisterInfo.h.
getCSRFirstUseCost()
virtual unsigned llvm::TargetRegisterInfo::getCSRFirstUseCost () const inline virtual
Allow the target to override the cost of using a callee-saved register for the first time.
Default value of 0 means we will use a callee-saved register if it is available.
Definition at line 824 of file TargetRegisterInfo.h.
getFrameIndexInstrOffset()
virtual int64_t llvm::TargetRegisterInfo::getFrameIndexInstrOffset (const MachineInstr * MI, int Idx) const inline virtual
Get the offset from the referenced frame index in the instruction, if there is one.
Definition at line 884 of file TargetRegisterInfo.h.
getFrameRegister()
virtual Register llvm::TargetRegisterInfo::getFrameRegister (const MachineFunction & MF) const pure virtual
Debug information queries.
getFrameRegister - This method should return the register used as a base for values allocated in the current stack frame.
Referenced by llvm::MipsAsmPrinter::emitFrameDirective(), llvm::TargetFrameLowering::getDwarfFrameBase(), llvm::TargetFrameLowering::getFrameIndexReference(), and llvm::RISCVFrameLowering::getFrameIndexReference().
getIntraCallClobberedRegs()
virtual ArrayRef< MCPhysReg > llvm::TargetRegisterInfo::getIntraCallClobberedRegs (const MachineFunction * MF) const inline virtual
Return a list of all of the registers which are clobbered "inside" a call to the given function.
For example, these might be needed for PLT sequences of long-branch veneers.
Definition at line 461 of file TargetRegisterInfo.h.
getLargestLegalSuperClass()
virtual const TargetRegisterClass * llvm::TargetRegisterInfo::getLargestLegalSuperClass (const TargetRegisterClass * RC, const MachineFunction &) const inline virtual
Returns the largest super class of RC that is legal to use in the current sub-target and has the same spill size.
The returned register class can be used to create virtual registers which means that all its registers can be copied and spilled.
The default implementation is very conservative and doesn't allow the register allocator to inflate register classes.
Definition at line 722 of file TargetRegisterInfo.h.
Referenced by llvm::PPCRegisterInfo::getLargestLegalSuperClass(), and llvm::MachineRegisterInfo::recomputeRegClass().
getMatchingSuperReg()
MCRegister llvm::TargetRegisterInfo::getMatchingSuperReg (MCRegister Reg, unsigned SubIdx, const TargetRegisterClass * RC) const inline
Return a super-register of the specified register Reg so its sub-register of index SubIdx is Reg.
Definition at line 529 of file TargetRegisterInfo.h.
References llvm::MCRegisterInfo::getMatchingSuperReg(), and llvm::TargetRegisterClass::MC.
getMatchingSuperRegClass()
const TargetRegisterClass * TargetRegisterInfo::getMatchingSuperRegClass (const TargetRegisterClass * A, const TargetRegisterClass * B, unsigned Idx) const virtual
Return a subclass of the specified register class A so that each register in it has a sub-register of the specified sub-register index which is in the specified register class B.
TableGen will synthesize missing A sub-classes.
Definition at line 283 of file TargetRegisterInfo.cpp.
References A, assert(), B, firstCommonClass(), Idx, and llvm::SuperRegClassIterator::isValid().
getMinimalPhysRegClass()
const TargetRegisterClass * TargetRegisterInfo::getMinimalPhysRegClass (MCRegister Reg, MVT VT = MVT::Other) const
Returns the Register Class of a physical register of the given type, picking the most sub register class of the right type that contains this physreg.
getMinimalPhysRegClass - Returns the Register Class of a physical register of the given type, picking the most sub register class of the right type that contains this physreg.
Definition at line 210 of file TargetRegisterInfo.cpp.
References assert(), llvm::Register::isPhysicalRegister(), isTypeLegalForClass(), llvm::MVT::Other, and regclasses().
Referenced by llvm::BitTracker::MachineEvaluator::getPhysRegBitWidth(), llvm::HexagonEvaluator::getPhysRegBitWidth(), and getRegSizeInBits().
getNoPreservedMask()
virtual const uint32_t * llvm::TargetRegisterInfo::getNoPreservedMask () const inline virtual
Return a register mask that clobbers everything.
Definition at line 453 of file TargetRegisterInfo.h.
References llvm_unreachable.
getNumRegClasses()
unsigned llvm::TargetRegisterInfo::getNumRegClasses () const inline
Definition at line 678 of file TargetRegisterInfo.h.
References regclass_begin(), and regclass_end().
Referenced by getRegClass(), getRegClassInfo(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), and llvm::RegisterClassInfo::runOnMachineFunction().
getNumRegPressureSets()
virtual unsigned llvm::TargetRegisterInfo::getNumRegPressureSets () const pure virtual
Get the number of dimensions of register pressure.
Referenced by llvm::RegPressureTracker::init(), llvm::RegPressureTracker::initLiveThru(), and llvm::RegisterClassInfo::runOnMachineFunction().
getPointerRegClass()
virtual const TargetRegisterClass * llvm::TargetRegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const inline virtual
Returns a TargetRegisterClass used for pointer values.
If a target supports multiple different pointer register classes, kind specifies which one is indicated.
Definition at line 704 of file TargetRegisterInfo.h.
References llvm_unreachable.
getRegAllocationHints()
bool TargetRegisterInfo::getRegAllocationHints (Register VirtReg, ArrayRef< MCPhysReg > Order, SmallVectorImpl< MCPhysReg > & Hints, const MachineFunction & MF, const VirtRegMap * VRM = nullptr, const LiveRegMatrix * Matrix = nullptr) const virtual
Get a list of 'hint' registers that the register allocator should try first when allocating a physical register for the virtual register VirtReg.
These registers are effectively moved to the front of the allocation order. If true is returned, regalloc will try to only use hints to the greatest extent possible even if it means spilling.
The Order argument is the allocation order for VirtReg's register class as returned from RegisterClassInfo::getOrder(). The hint registers must come from Order, and they must not be reserved.
The default implementation of this function will only add target independent register allocation hints. Targets that override this function should typically call this default implementation as well and expect to see generic copy hints added.
Definition at line 402 of file TargetRegisterInfo.cpp.
References llvm::VirtRegMap::getPhys(), llvm::MachineFunction::getRegInfo(), llvm::is_contained(), MRI, and Reg.
Referenced by llvm::ARMBaseRegisterInfo::getRegAllocationHints(), and llvm::SystemZRegisterInfo::getRegAllocationHints().
getRegAsmName()
virtual StringRef llvm::TargetRegisterInfo::getRegAsmName (MCRegister Reg) const inline virtual
Return the assembly name for Reg.
Definition at line 944 of file TargetRegisterInfo.h.
References llvm::MCRegisterInfo::getName().
Referenced by llvm::TargetLowering::getRegForInlineAsmConstraint().
getRegClass()
const TargetRegisterClass * llvm::TargetRegisterInfo::getRegClass (unsigned i) const inline
Returns the register class associated with the enumeration value.
See class MCOperandInfo.
Definition at line 684 of file TargetRegisterInfo.h.
References assert(), and getNumRegClasses().
Referenced by getAllocatableClass().
getRegClassInfo()
const RegClassInfo & llvm::TargetRegisterInfo::getRegClassInfo (const TargetRegisterClass & RC) const inline protected
Definition at line 666 of file TargetRegisterInfo.h.
References llvm::TargetRegisterClass::getID(), and getNumRegClasses().
Referenced by getRegSizeInBits(), getSpillAlign(), getSpillAlignment(), getSpillSize(), and legalclasstypes_begin().
getRegClassName()
const char * llvm::TargetRegisterInfo::getRegClassName (const TargetRegisterClass * Class) const inline
Returns the name of the register class.
Definition at line 690 of file TargetRegisterInfo.h.
References llvm::MCRegisterInfo::getRegClassName().
Referenced by llvm::RegAllocBase::allocatePhysRegs(), llvm::HexagonEvaluator::mask(), llvm::LiveStacks::print(), llvm::VirtRegMap::print(), and llvm::ExecutionDomainFix::runOnMachineFunction().
getRegClassPressureSets()
virtual const int * llvm::TargetRegisterInfo::getRegClassPressureSets (const TargetRegisterClass * RC) const pure virtual
Get the dimensions of register pressure impacted by this register class.
Returns a -1 terminated array of pressure set IDs.
Referenced by llvm::RegisterClassInfo::computePSetLimit().
getRegClassWeight()
virtual const RegClassWeight & llvm::TargetRegisterInfo::getRegClassWeight (const TargetRegisterClass * RC) const pure virtual
Get the weight in units of pressure for this register class.
Referenced by llvm::RegisterClassInfo::computePSetLimit().
getRegMaskNames()
virtual ArrayRef< const char * > llvm::TargetRegisterInfo::getRegMaskNames () const pure virtual
getRegMasks()
virtual ArrayRef< const uint32_t * > llvm::TargetRegisterInfo::getRegMasks () const pure virtual
Return all the call-preserved register masks defined for this target.
Referenced by llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo().
getRegPressureLimit()
virtual unsigned llvm::TargetRegisterInfo::getRegPressureLimit (const TargetRegisterClass * RC, MachineFunction & MF) const inline virtual
Return the register pressure "high water mark" for the specific register class.
The scheduler is in high register pressure mode (for the specific register class) if it goes over the limit.
Note: this is the old register pressure model that relies on a manually specified representative register class per value type.
Definition at line 735 of file TargetRegisterInfo.h.
Referenced by llvm::ResourcePriorityQueue::ResourcePriorityQueue().
getRegPressureSetLimit()
virtual unsigned llvm::TargetRegisterInfo::getRegPressureSetLimit (const MachineFunction & MF, unsigned Idx) const pure virtual
Get the register unit pressure limit for this dimension.
This limit must be adjusted dynamically for reserved registers.
Referenced by llvm::RegisterClassInfo::computePSetLimit().
getRegPressureSetName()
virtual const char * llvm::TargetRegisterInfo::getRegPressureSetName (unsigned Idx) const pure virtual
Get the name of this register unit pressure set.
Referenced by llvm::GenericScheduler::initCandidate(), llvm::ScheduleDAGMILive::initRegPressure(), llvm::ConvergingVLIWScheduler::traceCandidate(), llvm::GenericSchedulerBase::traceCandidate(), and llvm::ScheduleDAGMILive::updateScheduledPressure().
getRegPressureSetScore()
virtual unsigned llvm::TargetRegisterInfo::getRegPressureSetScore (const MachineFunction & MF, unsigned PSetID) const inline virtual
Return a heuristic for the machine scheduler to compare the profitability of increasing one register pressure set versus another.
The scheduler will prefer increasing the register pressure of the set which returns the largest value for this function.
Definition at line 744 of file TargetRegisterInfo.h.
getRegSizeInBits() [1/2]
unsigned llvm::TargetRegisterInfo::getRegSizeInBits (const TargetRegisterClass & RC) const inline
Return the size in bits of a register from class RC.
Definition at line 272 of file TargetRegisterInfo.h.
References getRegClassInfo(), and llvm::TargetRegisterInfo::RegClassInfo::RegSize.
Referenced by getCommonSuperRegClass(), llvm::BitTracker::MachineEvaluator::getPhysRegBitWidth(), llvm::HexagonEvaluator::getPhysRegBitWidth(), llvm::BitTracker::MachineEvaluator::getRegBitWidth(), and getRegSizeInBits().
getRegSizeInBits() [2/2]
unsigned TargetRegisterInfo::getRegSizeInBits (Register Reg, const MachineRegisterInfo & MRI) const
Returns size in bits of a phys/virtual/generic register.
Definition at line 490 of file TargetRegisterInfo.cpp.
References assert(), getMinimalPhysRegClass(), getRegSizeInBits(), and MRI.
getRegUnitPressureSets()
virtual const int * llvm::TargetRegisterInfo::getRegUnitPressureSets (unsigned RegUnit) const pure virtual
Get the dimensions of register pressure impacted by this register unit.
Returns a -1 terminated array of pressure set IDs.
getRegUnitWeight()
virtual unsigned llvm::TargetRegisterInfo::getRegUnitWeight (unsigned RegUnit) const pure virtual
Get the weight in units of pressure for this register unit.
getReservedRegs()
virtual BitVector llvm::TargetRegisterInfo::getReservedRegs (const MachineFunction & MF) const pure virtual
Returns a bitset indexed by physical register number indicating if a register is a special register that has particular uses and should be considered unavailable at all times, e.g.
stack pointer, return address. A reserved register:
is not allocatable
is considered always live
is ignored by liveness tracking It is often necessary to reserve the super registers of a reserved register as well, to avoid them getting allocated indirectly. You may use markSuperRegs() and checkAllSuperRegsMarked() in this case.
Referenced by llvm::MachineRegisterInfo::freezeReservedRegs(), and getAllocatableSet().
getSpillAlign()
Align llvm::TargetRegisterInfo::getSpillAlign (const TargetRegisterClass & RC) const inline
Return the minimum required alignment in bytes for a spill slot for a register of this class.
Definition at line 290 of file TargetRegisterInfo.h.
References getRegClassInfo().
getSpillAlignment()
unsigned llvm::TargetRegisterInfo::getSpillAlignment (const TargetRegisterClass & RC) const inline
Return the minimum required alignment in bytes for a spill slot for a register of this class.
Definition at line 284 of file TargetRegisterInfo.h.
References getRegClassInfo(), and llvm::TargetRegisterInfo::RegClassInfo::SpillAlignment.
getSpillSize()
unsigned llvm::TargetRegisterInfo::getSpillSize (const TargetRegisterClass & RC) const inline
Return the size in bytes of the stack slot allocated to hold a spilled copy of a register from class RC.
Definition at line 278 of file TargetRegisterInfo.h.
References getRegClassInfo(), and llvm::TargetRegisterInfo::RegClassInfo::SpillSize.
getSubClassWithSubReg()
virtual const TargetRegisterClass * llvm::TargetRegisterInfo::getSubClassWithSubReg (const TargetRegisterClass * RC, unsigned Idx) const inline virtual
Returns the largest legal sub-class of RC that supports the sub-register index Idx.
If no such sub-class exists, return NULL. If all registers in RC already have an Idx sub-register, return RC.
TableGen generates a version of this function that is good enough in most cases. Targets can override if they have constraints that TableGen doesn't understand. For example, the x86 sub_8bit sub-register index is supported by the full GR32 register class in 64-bit mode, but only by the GR32_ABCD regiister class in 32-bit mode.
TableGen will synthesize missing RC sub-classes.
Definition at line 565 of file TargetRegisterInfo.h.
References assert(), and Idx.
Referenced by llvm::FastISel::fastEmitInst_extractsubreg().
getSubReg()
Register llvm::TargetRegisterInfo::getSubReg (MCRegister Reg, unsigned Idx) const inline
Returns the physical register number of sub-register "Index" for physical register RegNo.
Return zero if the sub-register does not exist.
Definition at line 997 of file TargetRegisterInfo.h.
References getSubReg(), and Idx.
Referenced by addSavedGPR(), llvm::BitTracker::MachineEvaluator::getRegBitWidth(), getSubReg(), and llvm::rdf::DataFlowGraph::makeRegRef().
getSubRegIndexLaneMask()
LaneBitmask llvm::TargetRegisterInfo::getSubRegIndexLaneMask (unsigned SubIdx) const inline
Return a bitmask representing the parts of a register that are covered by SubIdx.
See also
LaneBitmask.
SubIdx == 0 is allowed, it has the lane mask ~0u.
Definition at line 355 of file TargetRegisterInfo.h.
References assert(), and llvm::MCRegisterInfo::getNumSubRegIndices().
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::ScheduleDAGInstrs::getLaneMaskForMO(), llvm::rdf::Liveness::resetKills(), and llvm::LiveIntervals::shrinkToUses().
getSubRegIndexName()
const char * llvm::TargetRegisterInfo::getSubRegIndexName (unsigned SubIdx) const inline
Return the human-readable symbolic target-specific name for the specified SubRegIndex.
Definition at line 345 of file TargetRegisterInfo.h.
References assert(), and llvm::MCRegisterInfo::getNumSubRegIndices().
hasRegUnit()
bool llvm::TargetRegisterInfo::hasRegUnit (MCRegister Reg, unsigned RegUnit) const inline
Returns true if Reg contains RegUnit.
Definition at line 404 of file TargetRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid().
hasReservedSpillSlot()
virtual bool llvm::TargetRegisterInfo::hasReservedSpillSlot (const MachineFunction & MF, Register Reg, int & FrameIdx) const inline virtual
Return true if target has reserved a spill slot in the stack frame of the given function for the specified register.
e.g. On x86, if the frame register is required, the first fixed stack object is reserved as its spill slot. This tells PEI not to create a new stack frame object for the given register. It should be called only after determineCalleeSaves().
Definition at line 863 of file TargetRegisterInfo.h.
isAsmClobberable()
virtual bool llvm::TargetRegisterInfo::isAsmClobberable (const MachineFunction & MF, MCRegister PhysReg) const inline virtual
Returns false if we can't guarantee that Physreg, specified as an IR asm clobber constraint, will be preserved across the statement.
Definition at line 487 of file TargetRegisterInfo.h.
isCalleeSavedPhysReg()
bool TargetRegisterInfo::isCalleeSavedPhysReg (MCRegister PhysReg, const MachineFunction & MF) const virtual
This is a wrapper around getCallPreservedMask().
Return true if the register is preserved after the call.
Definition at line 445 of file TargetRegisterInfo.cpp.
References assert(), llvm::Function::getCallingConv(), getCallPreservedMask(), llvm::MachineFunction::getFunction(), and llvm::Register::isPhysicalRegister().
isCallerPreservedPhysReg()
virtual bool llvm::TargetRegisterInfo::isCallerPreservedPhysReg (MCRegister PhysReg, const MachineFunction & MF) const inline virtual
Physical registers that may be modified within a function but are guaranteed to be restored before any uses.
This is useful for targets that have call sequences where a GOT register may be updated by the caller prior to a call and is guaranteed to be restored (also by the caller) after the call.
Definition at line 512 of file TargetRegisterInfo.h.
isConstantPhysReg()
virtual bool llvm::TargetRegisterInfo::isConstantPhysReg (MCRegister PhysReg) const inline virtual
Returns true if PhysReg is unallocatable and constant throughout the function.
Used by MachineRegisterInfo::isConstantPhysReg().
Definition at line 500 of file TargetRegisterInfo.h.
isDivergentRegClass()
virtual bool llvm::TargetRegisterInfo::isDivergentRegClass (const TargetRegisterClass * RC) const inline virtual
Returns true if the register class is considered divergent.
Definition at line 503 of file TargetRegisterInfo.h.
isFrameOffsetLegal()
virtual bool llvm::TargetRegisterInfo::isFrameOffsetLegal (const MachineInstr * MI, Register BaseReg, int64_t Offset) const inline virtual
Determine whether a given base register plus offset immediate is encodable to resolve a frame index.
Definition at line 915 of file TargetRegisterInfo.h.
References llvm_unreachable.
isInAllocatableClass()
bool llvm::TargetRegisterInfo::isInAllocatableClass (MCRegister RegNo) const inline
Return true if the register is in the allocation of any register class.
Definition at line 339 of file TargetRegisterInfo.h.
References llvm::TargetRegisterInfoDesc::inAllocatableClass.
Referenced by llvm::MachineRegisterInfo::isAllocatable().
isInlineAsmReadOnlyReg()
virtual bool llvm::TargetRegisterInfo::isInlineAsmReadOnlyReg (const MachineFunction & MF, unsigned PhysReg) const inline virtual
Returns true if PhysReg cannot be written to in inline asm statements.
Definition at line 493 of file TargetRegisterInfo.h.
isTypeLegalForClass()
bool llvm::TargetRegisterInfo::isTypeLegalForClass (const TargetRegisterClass & RC, MVT T) const inline
Return true if the given TargetRegisterClass has the ValueType T.
Definition at line 295 of file TargetRegisterInfo.h.
References I, legalclasstypes_begin(), and llvm::MVT::Other.
Referenced by getMinimalPhysRegClass(), and llvm::TargetLowering::getRegForInlineAsmConstraint().
legalclasstypes_begin()
vt_iterator llvm::TargetRegisterInfo::legalclasstypes_begin (const TargetRegisterClass & RC) const inline
Loop over all of the value types that can be represented by values in the given register class.
Definition at line 304 of file TargetRegisterInfo.h.
References getRegClassInfo(), and llvm::TargetRegisterInfo::RegClassInfo::VTList.
Referenced by isTypeLegalForClass(), and legalclasstypes_end().
legalclasstypes_end()
vt_iterator llvm::TargetRegisterInfo::legalclasstypes_end (const TargetRegisterClass & RC) const inline
Definition at line 308 of file TargetRegisterInfo.h.
References I, legalclasstypes_begin(), and llvm::MVT::Other.
lookThruCopyLike()
Register TargetRegisterInfo::lookThruCopyLike (Register SrcReg, const MachineRegisterInfo * MRI) const virtual
Returns the original SrcReg unless it is the target of a copy-like operation, in which case we chain backwards through all such operations to the ultimate source register.
If a physical register is encountered, we stop the search.
Definition at line 513 of file TargetRegisterInfo.cpp.
References assert(), MI, and MRI.
markSuperRegs()
void TargetRegisterInfo::markSuperRegs (BitVector & RegisterSet, MCRegister Reg) const
Mark a register and all its aliases as reserved in the given set.
Definition at line 78 of file TargetRegisterInfo.cpp.
References llvm::MCRegisterInfo::DiffListIterator::isValid().
materializeFrameBaseRegister()
virtual void llvm::TargetRegisterInfo::materializeFrameBaseRegister (MachineBasicBlock * MBB, Register BaseReg, int FrameIdx, int64_t Offset) const inline virtual
Insert defining instruction(s) for BaseReg to be a pointer to FrameIdx before insertion point I.
Definition at line 899 of file TargetRegisterInfo.h.
References llvm_unreachable.
needsFrameBaseReg()
virtual bool llvm::TargetRegisterInfo::needsFrameBaseReg (MachineInstr * MI, int64_t Offset) const inline virtual
Returns true if the instruction's frame index reference would be better served by a base register other than FP or SP.
Used by LocalStackFrameAllocation to determine which frame index references it should create new base registers for.
Definition at line 893 of file TargetRegisterInfo.h.
needsStackRealignment()
bool TargetRegisterInfo::needsStackRealignment (const MachineFunction & MF) const
True if storage within the function requires the stack pointer to be aligned more than the normal calling convention calls for.
This cannot be overriden by the target, but canRealignStack can be overridden.
Definition at line 463 of file TargetRegisterInfo.cpp.
References canRealignStack(), llvm::dbgs(), F, llvm::MachineFunction::getFrameInfo(), llvm::TargetSubtargetInfo::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::MachineFrameInfo::getMaxAlign(), llvm::TargetFrameLowering::getStackAlign(), llvm::MachineFunction::getSubtarget(), and LLVM_DEBUG.
Referenced by llvm::RISCVFrameLowering::getFrameIndexReference().
regclass_begin()
regclass_iterator llvm::TargetRegisterInfo::regclass_begin () const inline
Register class iterators.
Definition at line 672 of file TargetRegisterInfo.h.
Referenced by getNumRegClasses(), and regclasses().
regclass_end()
regclass_iterator llvm::TargetRegisterInfo::regclass_end () const inline
Definition at line 673 of file TargetRegisterInfo.h.
Referenced by getNumRegClasses(), and regclasses().
regclasses()
iterator_range< regclass_iterator > llvm::TargetRegisterInfo::regclasses () const inline
Definition at line 674 of file TargetRegisterInfo.h.
References llvm::make_range(), regclass_begin(), and regclass_end().
Referenced by llvm::RegisterClassInfo::computePSetLimit(), getAllocatableSet(), getMinimalPhysRegClass(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::HexagonBlockRanges::HexagonBlockRanges(), llvm::rdf::PhysicalRegisterInfo::PhysicalRegisterInfo(), llvm::ResourcePriorityQueue::regPressureDelta(), and llvm::ResourcePriorityQueue::ResourcePriorityQueue().
regmaskSubsetEqual()
bool TargetRegisterInfo::regmaskSubsetEqual (const uint32_t * mask0, const uint32_t * mask1) const
Return true if all bits that are set in mask mask0 are also set in mask1.
Definition at line 480 of file TargetRegisterInfo.cpp.
References llvm::MCRegisterInfo::getNumRegs(), I, and N.
regsOverlap()
bool llvm::TargetRegisterInfo::regsOverlap (Register regA, Register regB) const inline
Returns true if the two registers are equal or alias each other.
The registers may be virtual registers.
Definition at line 387 of file TargetRegisterInfo.h.
requiresFrameIndexReplacementScavenging()
virtual bool llvm::TargetRegisterInfo::requiresFrameIndexReplacementScavenging (const MachineFunction & MF) const inline virtual
Returns true if the target requires using the RegScavenger directly for frame elimination despite using requiresFrameIndexScavenging.
Definition at line 846 of file TargetRegisterInfo.h.
requiresFrameIndexScavenging()
virtual bool llvm::TargetRegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const inline virtual
Returns true if the target requires post PEI scavenging of registers for materializing frame index constants.
Definition at line 840 of file TargetRegisterInfo.h.
requiresRegisterScavenging()
virtual bool llvm::TargetRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline virtual
Returns true if the target requires (and can make use of) the register scavenger.
Definition at line 828 of file TargetRegisterInfo.h.
requiresVirtualBaseRegisters()
virtual bool llvm::TargetRegisterInfo::requiresVirtualBaseRegisters (const MachineFunction & MF) const inline virtual
Returns true if the target wants the LocalStackAllocation pass to be run and virtual base registers used for more efficient stack access.
Definition at line 853 of file TargetRegisterInfo.h.
resolveFrameIndex()
virtual void llvm::TargetRegisterInfo::resolveFrameIndex (MachineInstr & MI, Register BaseReg, int64_t Offset) const inline virtual
Resolve a frame index operand of an instruction to reference the indicated base register plus offset instead.
Definition at line 908 of file TargetRegisterInfo.h.
References llvm_unreachable.
reverseComposeSubRegIndexLaneMask()
LaneBitmask llvm::TargetRegisterInfo::reverseComposeSubRegIndexLaneMask (unsigned IdxA, LaneBitmask LaneMask) const inline
Transform a lanemask given for a virtual register to the corresponding lanemask before using subregister with index IdxA.
This is the reverse of composeSubRegIndexLaneMask(), assuming Mask is a valie lane mask (no invalid bits set) the following holds: X0 = composeSubRegIndexLaneMask(Idx, Mask) X1 = reverseComposeSubRegIndexLaneMask(Idx, X0) => X1 == Mask
Definition at line 606 of file TargetRegisterInfo.h.
References reverseComposeSubRegIndexLaneMaskImpl().
Referenced by llvm::rdf::PhysicalRegisterInfo::mapTo().
reverseComposeSubRegIndexLaneMaskImpl()
virtual LaneBitmask llvm::TargetRegisterInfo::reverseComposeSubRegIndexLaneMaskImpl (unsigned , LaneBitmask) const inline protected virtual
Definition at line 629 of file TargetRegisterInfo.h.
References llvm_unreachable.
Referenced by reverseComposeSubRegIndexLaneMask().
reverseLocalAssignment()
virtual bool llvm::TargetRegisterInfo::reverseLocalAssignment () const inline virtual
Allow the target to reverse allocation order of local live ranges.
This will generally allocate shorter local live ranges first. For targets with many registers, this could reduce regalloc compile time by a large factor. It is disabled by default for three reasons: (1) Top-down allocation is simpler and easier to debug for targets that don't benefit from reversing the order. (2) Bottom-up allocation could result in poor evicition decisions on some targets affecting the performance of compiled code. (3) Bottom-up allocation is no longer guaranteed to optimally color.
Definition at line 819 of file TargetRegisterInfo.h.
saveScavengerRegister()
virtual bool llvm::TargetRegisterInfo::saveScavengerRegister (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, MachineBasicBlock::iterator & UseMI, const TargetRegisterClass * RC, Register Reg) const inline virtual
Spill the register so it can be used by the register scavenger.
Return true if the register was spilled, false otherwise. If this function does not spill the register, the scavenger will instead spill it to the emergency spill slot.
Definition at line 924 of file TargetRegisterInfo.h.
shouldCoalesce()
virtual bool llvm::TargetRegisterInfo::shouldCoalesce (MachineInstr * MI, const TargetRegisterClass * SrcRC, unsigned SubReg, const TargetRegisterClass * DstRC, unsigned DstSubReg, const TargetRegisterClass * NewRC, LiveIntervals & LIS) const inline virtual
Subtarget Hooks.
SrcRC and DstRC will be morphed into NewRC if this returns true.
Definition at line 958 of file TargetRegisterInfo.h.
Referenced by llvm::AVRRegisterInfo::shouldCoalesce().
shouldRegionSplitForVirtReg()
bool TargetRegisterInfo::shouldRegionSplitForVirtReg (const MachineFunction & MF, const LiveInterval & VirtReg) const virtual
Region split has a high compile time cost especially for large live range.
This method is used to decide whether or not VirtReg should go through this expensive splitting heuristic.
Definition at line 67 of file TargetRegisterInfo.cpp.
References llvm::TargetSubtargetInfo::getInstrInfo(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getSubtarget(), HugeSizeForSplit, MI, MRI, llvm::LiveInterval::reg, llvm::LiveRange::size(), and TII.
shouldRewriteCopySrc()
bool TargetRegisterInfo::shouldRewriteCopySrc (const TargetRegisterClass * DefRC, unsigned DefSubReg, const TargetRegisterClass * SrcRC, unsigned SrcSubReg) const virtual
Definition at line 393 of file TargetRegisterInfo.cpp.
References shareSameRegisterFile().
Referenced by llvm::X86RegisterInfo::shouldRewriteCopySrc().
trackLivenessAfterRegAlloc()
virtual bool llvm::TargetRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const inline virtual
Returns true if the live-ins should be tracked after register allocation.
Definition at line 869 of file TargetRegisterInfo.h.
Referenced by llvm::BranchFolder::OptimizeFunction().
updateRegAllocHint()
virtual void llvm::TargetRegisterInfo::updateRegAllocHint (Register Reg, Register NewReg, MachineFunction & MF) const inline virtual
A callback to allow target a chance to update register allocation hints when a register is "changed" (e.g.
coalesced) to another register. e.g. On ARM, some virtual registers should target register pairs, if one of pair is coalesced to another register, the allocation hint of the other half of the pair should be changed to point to the new register.
Definition at line 805 of file TargetRegisterInfo.h.
useFPForScavengingIndex()
virtual bool llvm::TargetRegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const inline virtual
Returns true if the target wants to use frame pointer based accesses to spill to the scavenger emergency spill slot.
Definition at line 834 of file TargetRegisterInfo.h.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/TargetRegisterInfo.h
lib/CodeGen/TargetRegisterInfo.cpp