LLVM: llvm::ARMLegalizerInfo Class Reference
llvm::ARMLegalizerInfo Class Reference
This class provides the information for the target register banks.
#include "Target/ARM/ARMLegalizerInfo.h"
Public Member Functions
ARMLegalizerInfo (const ARMSubtarget &ST)
bool legalizeCustom (LegalizerHelper &Helper, MachineInstr &MI) const override
Called for instructions with the Custom LegalizationAction.
Public Member Functions inherited from llvm::LegalizerInfo
LegalizerInfo ()
virtual ~LegalizerInfo ()=default
unsigned getOpcodeIdxForOpcode (unsigned Opcode) const
unsigned getActionDefinitionsIdx (unsigned Opcode) const
void computeTables ()
Compute any ancillary tables needed to quickly decide how an operation should be handled.
void verify (const MCInstrInfo &MII) const
Perform simple self-diagnostic and assert if there is anything obviously wrong with the actions set up.
void setAction (const InstrAspect &Aspect, LegalizeAction Action)
More friendly way to set an action for common types that have an LLT representation.
void setLegalizeScalarToDifferentSizeStrategy (const unsigned Opcode, const unsigned TypeIdx, SizeChangeStrategy S)
The setAction calls record the non-size-changing legalization actions to take on specificly-sized types.
void setLegalizeVectorElementToDifferentSizeStrategy (const unsigned Opcode, const unsigned TypeIdx, SizeChangeStrategy S)
See also setLegalizeScalarToDifferentSizeStrategy.
const LegalizeRuleSet & getActionDefinitions (unsigned Opcode) const
Get the action definitions for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (unsigned Opcode)
Get the action definition builder for the given opcode.
LegalizeRuleSet & getActionDefinitionsBuilder (std::initializer_list< unsigned > Opcodes)
Get the action definition builder for the given set of opcodes.
void aliasActionDefinitions (unsigned OpcodeTo, unsigned OpcodeFrom)
LegalizeActionStep getAction (const LegalityQuery &Query) const
Determine what action should be taken to legalize the described instruction.
LegalizeActionStep getAction (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
Determine what action should be taken to legalize the given generic instruction.
bool isLegal (const LegalityQuery &Query) const
bool isLegal (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
bool isLegalOrCustom (const MachineInstr &MI, const MachineRegisterInfo &MRI) const
virtual bool legalizeIntrinsic (LegalizerHelper &Helper, MachineInstr &MI) const
virtual unsigned getExtOpcodeForWideningConstant (LLT SmallTy) const
Return the opcode (SEXT/ZEXT/ANYEXT) that should be performed while widening a constant of type SmallTy which targets can override.
Additional Inherited Members
Public Types inherited from llvm::LegalizerInfo
using SizeAndAction = std::pair<uint16_t, LegalizeAction>
using SizeAndActionsVec = std::vector<SizeAndAction>
using SizeChangeStrategy
Static Public Member Functions inherited from llvm::LegalizerInfo
static bool needsLegalizingToDifferentSize (const LegalizeAction Action)
static SizeAndActionsVec unsupportedForDifferentSizes (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular operation consists of only supporting a specific set of type sizes.
static SizeAndActionsVec widenToLargerTypesAndNarrowToLargest (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular operation consists of widening the type to a large legal type, unless there is no such type and then instead it should be narrowed to the largest legal type.
static SizeAndActionsVec widenToLargerTypesUnsupportedOtherwise (const SizeAndActionsVec &v)
static SizeAndActionsVec narrowToSmallerAndUnsupportedIfTooSmall (const SizeAndActionsVec &v)
static SizeAndActionsVec narrowToSmallerAndWidenToSmallest (const SizeAndActionsVec &v)
static SizeAndActionsVec moreToWiderTypesAndLessToWidest (const SizeAndActionsVec &v)
A SizeChangeStrategy for the common case where legalization for a particular vector operation consists of having more elements in the vector, to a type that is legal.
static SizeAndActionsVec increaseToLargerTypesAndDecreaseToLargest (const SizeAndActionsVec &v, LegalizeAction IncreaseAction, LegalizeAction DecreaseAction)
Helper function to implement many typical SizeChangeStrategy functions.
static SizeAndActionsVec decreaseToSmallerTypesAndIncreaseToSmallest (const SizeAndActionsVec &v, LegalizeAction DecreaseAction, LegalizeAction IncreaseAction)
Helper function to implement many typical SizeChangeStrategy functions.
Detailed Description
This class provides the information for the target register banks.
Definition at line 27 of file ARMLegalizerInfo.h.
Constructor & Destructor Documentation
ARMLegalizerInfo()
ARMLegalizerInfo::ARMLegalizerInfo (const ARMSubtarget & ST)
Definition at line 66 of file ARMLegalizerInfo.cpp.
References AEABI(), llvm::LegalizeRuleSet::clampScalar(), llvm::LegalizerInfo::computeTables(), llvm::LegalizeActions::Custom, llvm::LegalizeRuleSet::customFor(), llvm::LegalizeRuleSet::customForCartesianProduct(), llvm::LegalizerInfo::getActionDefinitionsBuilder(), llvm::LegalizeRuleSet::legalFor(), llvm::LegalizeRuleSet::legalForCartesianProduct(), llvm::LegalizeActions::Libcall, llvm::LegalizeRuleSet::libcallFor(), llvm::LegalizeRuleSet::lower(), llvm::Lower, llvm::LegalizeRuleSet::lowerFor(), llvm::LLT::pointer(), llvm::LLT::scalar(), llvm::LegalizerInfo::setAction(), llvm::LegalizerInfo::setLegalizeScalarToDifferentSizeStrategy(), verify, and widen_8_16().
Member Function Documentation
legalizeCustom()
bool ARMLegalizerInfo::legalizeCustom (LegalizerHelper & Helper, MachineInstr & MI) const override virtual
Called for instructions with the Custom LegalizationAction.
Reimplemented from llvm::LegalizerInfo.
Definition at line 360 of file ARMLegalizerInfo.cpp.
References assert(), llvm::CmpInst::BAD_ICMP_PREDICATE, llvm::MachineIRBuilder::buildConstant(), llvm::MachineIRBuilder::buildICmp(), llvm::MachineIRBuilder::buildOr(), llvm::MachineIRBuilder::buildTrunc(), llvm::createLibcall(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_TRUE, llvm::StructType::get(), llvm::ConstantInt::get(), llvm::Function::getContext(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::MachineFunction::getFunction(), llvm::Type::getInt32Ty(), llvm::MachineIRBuilder::getMF(), llvm::MachineIRBuilder::getMRI(), getReg(), llvm::CmpInst::isIntPredicate(), llvm::LegalizerHelper::Legalized, MI, llvm::LegalizerHelper::MIRBuilder, MRI, Results, RetTy, llvm::LLT::scalar(), llvm::Function::size(), and Size.
The documentation for this class was generated from the following files:
lib/Target/ARM/ARMLegalizerInfo.h
lib/Target/ARM/ARMLegalizerInfo.cpp