LLVM: llvm::LoopVectorizationRequirements Class Reference
llvm::LoopVectorizationRequirements Class Reference
This holds vectorization requirements that must be verified late in the process.
#include "llvm/Transforms/Vectorize/LoopVectorizationLegality.h"
Public Member Functions
LoopVectorizationRequirements (OptimizationRemarkEmitter &ORE)
void addUnsafeAlgebraInst (Instruction *I)
void addRuntimePointerChecks (unsigned Num)
bool doesNotMeet (Function *F, Loop *L, const LoopVectorizeHints &Hints)
Detailed Description
This holds vectorization requirements that must be verified late in the process.
The requirements are set by legalize and costmodel. Once vectorization has been determined to be possible and profitable the requirements can be verified by looking for metadata or compiler options. For example, some loops require FP commutativity which is only allowed if vectorization is explicitly specified or if the fast-math compiler option has been provided. Late evaluation of these requirements allows helpful diagnostics to be composed that tells the user what need to be done to vectorize the loop. For example, by specifying #pragma clang loop vectorize or -ffast-math. Late evaluation should be used only when diagnostics can generated that can be followed by a non-expert user.
Definition at line 162 of file LoopVectorizationLegality.h.
Constructor & Destructor Documentation
LoopVectorizationRequirements()
llvm::LoopVectorizationRequirements::LoopVectorizationRequirements (OptimizationRemarkEmitter & ORE) inline
Definition at line 164 of file LoopVectorizationLegality.h.
Member Function Documentation
addRuntimePointerChecks()
void llvm::LoopVectorizationRequirements::addRuntimePointerChecks (unsigned Num) inline
Definition at line 172 of file LoopVectorizationLegality.h.
addUnsafeAlgebraInst()
void llvm::LoopVectorizationRequirements::addUnsafeAlgebraInst (Instruction * I) inline
Definition at line 166 of file LoopVectorizationLegality.h.
References I.
doesNotMeet()
bool llvm::LoopVectorizationRequirements::doesNotMeet (Function * F, Loop * L, const LoopVectorizeHints & Hints)
Definition at line 242 of file LoopVectorizationLegality.cpp.
References llvm::LoopVectorizeHints::allowReordering(), llvm::dbgs(), llvm::OptimizationRemarkEmitter::emit(), llvm::Failed(), llvm::Instruction::getDebugLoc(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::Instruction::getParent(), llvm::Loop::getStartLoc(), LLVM_DEBUG, PragmaVectorizeMemoryCheckThreshold, llvm::VectorizerParams::RuntimeMemoryCheckThreshold, and llvm::LoopVectorizeHints::vectorizeAnalysisPassName().
Referenced by llvm::LoopVectorizePass::processLoop().
The documentation for this class was generated from the following files:
include/llvm/Transforms/Vectorize/LoopVectorizationLegality.h
lib/Transforms/Vectorize/LoopVectorizationLegality.cpp