LLVM: llvm::ConstantUniqueMap< ConstantClass > Class Template Reference
llvm::ConstantUniqueMap< ConstantClass > Class Template Reference
#include "IR/ConstantsContext.h"
Public Types
using ValType = typename ConstantInfo<ConstantClass>::ValType
using TypeClass = typename ConstantInfo<ConstantClass>::TypeClass
using LookupKey = std::pair<TypeClass *, ValType>
using LookupKeyHashed = std::pair<unsigned, LookupKey>
Key and hash together, so that we compute the hash only once and reuse it.
using MapTy = DenseSet<ConstantClass *, MapInfo>
Public Member Functions
MapTy::iterator begin ()
MapTy::iterator end ()
void freeConstants ()
ConstantClass * getOrCreate (TypeClass *Ty, ValType V)
Return the specified constant from the map, creating it if necessary.
void remove (ConstantClass *CP)
Remove this constant from the map.
ConstantClass * replaceOperandsInPlace (ArrayRef< Constant * > Operands, ConstantClass *CP, Value *From, Constant *To, unsigned NumUpdated=0, unsigned OperandNo=~0u)
void dump () const
void freeConstants ()
Detailed Description
template<class ConstantClass>
class llvm::ConstantUniqueMap< ConstantClass >
Definition at line 647 of file ConstantsContext.h.
Member Typedef Documentation
LookupKey
template<class ConstantClass > using llvm::ConstantUniqueMap< ConstantClass >::LookupKey = std::pair<TypeClass *, ValType>
Definition at line 651 of file ConstantsContext.h.
LookupKeyHashed
template<class ConstantClass > using llvm::ConstantUniqueMap< ConstantClass >::LookupKeyHashed = std::pair<unsigned, LookupKey>
Key and hash together, so that we compute the hash only once and reuse it.
Definition at line 654 of file ConstantsContext.h.
MapTy
template<class ConstantClass > using llvm::ConstantUniqueMap< ConstantClass >::MapTy = DenseSet<ConstantClass *, MapInfo>
Definition at line 699 of file ConstantsContext.h.
TypeClass
template<class ConstantClass > using llvm::ConstantUniqueMap< ConstantClass >::TypeClass = typename ConstantInfo<ConstantClass>::TypeClass
Definition at line 650 of file ConstantsContext.h.
ValType
template<class ConstantClass > using llvm::ConstantUniqueMap< ConstantClass >::ValType = typename ConstantInfo<ConstantClass>::ValType
Definition at line 649 of file ConstantsContext.h.
Member Function Documentation
begin()
template<class ConstantClass > MapTy::iterator llvm::ConstantUniqueMap< ConstantClass >::begin () inline
Definition at line 705 of file ConstantsContext.h.
Referenced by llvm::LLVMContextImpl::dropTriviallyDeadConstantArrays().
dump()
template<class ConstantClass > void llvm::ConstantUniqueMap< ConstantClass >::dump () const inline
Definition at line 778 of file ConstantsContext.h.
References llvm::dbgs(), and LLVM_DEBUG.
end()
template<class ConstantClass > MapTy::iterator llvm::ConstantUniqueMap< ConstantClass >::end () inline
Definition at line 706 of file ConstantsContext.h.
Referenced by llvm::LLVMContextImpl::dropTriviallyDeadConstantArrays().
freeConstants() [1/2]
template<class ConstantClass > void llvm::ConstantUniqueMap< ConstantClass >::freeConstants () inline
Definition at line 708 of file ConstantsContext.h.
References llvm::deleteConstant(), and I.
Referenced by llvm::LLVMContextImpl::~LLVMContextImpl().
freeConstants() [2/2]
void llvm::ConstantUniqueMap< InlineAsm >::freeConstants () inline
Definition at line 783 of file ConstantsContext.h.
References I.
getOrCreate()
template<class ConstantClass > ConstantClass * llvm::ConstantUniqueMap< ConstantClass >::getOrCreate (TypeClass * Ty, ValType V) inline
Return the specified constant from the map, creating it if necessary.
Hash once, and reuse it for the lookup and the insertion if needed.
Definition at line 725 of file ConstantsContext.h.
References assert(), I, and Lookup().
remove()
template<class ConstantClass > void llvm::ConstantUniqueMap< ConstantClass >::remove (ConstantClass * CP) inline
Remove this constant from the map.
Definition at line 743 of file ConstantsContext.h.
References assert(), and I.
Referenced by llvm::ConstantUniqueMap< ConstantClass >::replaceOperandsInPlace().
replaceOperandsInPlace()
template<class ConstantClass > ConstantClass * llvm::ConstantUniqueMap< ConstantClass >::replaceOperandsInPlace (ArrayRef< Constant * > Operands, ConstantClass * CP, Value * From, Constant * To, unsigned NumUpdated = 0, unsigned OperandNo = ~0u) inline
Hash once, and reuse it for the lookup and the insertion if needed.
Definition at line 750 of file ConstantsContext.h.
References assert(), E, From, I, Lookup(), Operands, and llvm::ConstantUniqueMap< ConstantClass >::remove().
The documentation for this class was generated from the following files:
include/llvm/IR/InlineAsm.h
lib/IR/ConstantsContext.h