LLVM: llvm::FileInfo Class Reference
llvm::FileInfo Class Reference
#include "llvm/ProfileData/GCOV.h"
Classes
struct LineData
Public Member Functions
FileInfo (const GCOV::Options &Options)
void addBlockLine (StringRef Filename, uint32_t Line, const GCOVBlock *Block)
void addFunctionLine (StringRef Filename, uint32_t Line, const GCOVFunction *Function)
void setRunCount (uint32_t Runs)
void setProgramCount (uint32_t Programs)
void print (raw_ostream &OS, StringRef MainFilename, StringRef GCNOFile, StringRef GCDAFile, GCOVFile &file)
print - Print source files with collected line count information.
Protected Types
using FunctionVector = SmallVector<const GCOVFunction *, 1>
using FunctionLines = DenseMap<uint32_t, FunctionVector>
using BlockVector = SmallVector<const GCOVBlock *, 4>
using BlockLines = DenseMap<uint32_t, BlockVector>
using FuncCoverageMap = MapVector<const GCOVFunction *, GCOVCoverage>
Protected Member Functions
std::string getCoveragePath (StringRef Filename, StringRef MainFilename)
std::unique_ptr< raw_ostream > openCoveragePath (StringRef CoveragePath)
void printFunctionSummary (raw_ostream &OS, const FunctionVector &Funcs) const
printFunctionSummary - Print function and block summary.
void printBlockInfo (raw_ostream &OS, const GCOVBlock &Block, uint32_t LineIndex, uint32_t &BlockNo) const
printBlockInfo - Output counts for each block.
void printBranchInfo (raw_ostream &OS, const GCOVBlock &Block, GCOVCoverage &Coverage, uint32_t &EdgeNo)
printBranchInfo - Print conditional branch probabilities.
void printUncondBranchInfo (raw_ostream &OS, uint32_t &EdgeNo, uint64_t Count) const
printUncondBranchInfo - Print unconditional branch probabilities.
void printCoverage (raw_ostream &OS, const GCOVCoverage &Coverage) const
void printFuncCoverage (raw_ostream &OS) const
void printFileCoverage (raw_ostream &OS) const
Protected Attributes
const GCOV::Options & Options
StringMap< LineData > LineInfo
uint32_t RunCount = 0
uint32_t ProgramCount = 0
FuncCoverageMap FuncCoverages
std::vector< SourceInfo > sources
Friends
class GCOVFile
Detailed Description
Definition at line 346 of file GCOV.h.
Member Typedef Documentation
BlockLines
using llvm::FileInfo::BlockLines = DenseMap<uint32_t, BlockVector> protected
Definition at line 356 of file GCOV.h.
BlockVector
using llvm::FileInfo::BlockVector = SmallVector<const GCOVBlock *, 4> protected
Definition at line 355 of file GCOV.h.
FuncCoverageMap
using llvm::FileInfo::FuncCoverageMap = MapVector<const GCOVFunction *, GCOVCoverage> protected
Definition at line 408 of file GCOV.h.
FunctionLines
using llvm::FileInfo::FunctionLines = DenseMap<uint32_t, FunctionVector> protected
Definition at line 354 of file GCOV.h.
FunctionVector
using llvm::FileInfo::FunctionVector = SmallVector<const GCOVFunction *, 1> protected
Definition at line 353 of file GCOV.h.
Constructor & Destructor Documentation
FileInfo()
llvm::FileInfo::FileInfo (const GCOV::Options & Options) inline
Definition at line 368 of file GCOV.h.
Member Function Documentation
addBlockLine()
void llvm::FileInfo::addBlockLine (StringRef Filename, uint32_t Line, const GCOVBlock * Block) inline
Definition at line 370 of file GCOV.h.
References LineInfo.
Referenced by llvm::GCOVBlock::collectLineCounts().
addFunctionLine()
void llvm::FileInfo::addFunctionLine (StringRef Filename, uint32_t Line, const GCOVFunction * Function) inline
Definition at line 376 of file GCOV.h.
References LineInfo.
Referenced by llvm::GCOVFunction::collectLineCounts().
getCoveragePath()
std::string FileInfo::getCoveragePath (StringRef Filename, StringRef MainFilename) protected
Definition at line 582 of file GCOV.cpp.
References llvm::StringRef::equals(), llvm::MD5::final(), llvm::GCOV::Options::HashFilenames, llvm::GCOV::Options::LongFileNames, mangleCoveragePath(), llvm::GCOV::Options::NoOutput, Options, llvm::GCOV::Options::PreservePaths, llvm::StringRef::str(), and llvm::MD5::update().
Referenced by print().
openCoveragePath()
std::unique_ptr< raw_ostream > FileInfo::openCoveragePath (StringRef CoveragePath) protected
Definition at line 607 of file GCOV.cpp.
References llvm::errs(), and llvm::sys::fs::OF_Text.
Referenced by print().
print()
void FileInfo::print (raw_ostream & OS, StringRef MainFilename, StringRef GCNOFile, StringRef GCDAFile, GCOVFile & file)
print - Print source files with collected line count information.
Definition at line 619 of file GCOV.cpp.
References llvm::GCOV::Options::AllBlocks, arc, block, llvm::FileInfo::LineData::Blocks, llvm::GCOV::Options::BranchInfo, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::errs(), file, llvm::sys::path::filename(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::format(), llvm::GCOV::Options::FuncCoverage, FuncCoverages, llvm::FileInfo::LineData::Functions, getCoveragePath(), llvm::GCOVBlock::getLineCount(), llvm::Value::getName(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::insert(), llvm::GCOV::Options::Intermediate, llvm::FileInfo::LineData::LastLine, LineInfo, llvm::GCOVCoverage::LinesExec, llvm::GCOVCoverage::LogicalLines, llvm::GCOV::Options::NoOutput, llvm::sys::fs::OF_Text, openCoveragePath(), Options, llvm::outs(), printBlockInfo(), printBranchInfo(), printFileCoverage(), printFuncCoverage(), printFunctionSummary(), printUncondBranchInfo(), ProgramCount, RunCount, llvm::sort(), sources, llvm::GCOV::Options::UncondBranch, llvm::GCOV::Options::UseStdout, and llvm::GCOV::V900.
printBlockInfo()
void FileInfo::printBlockInfo (raw_ostream & OS, const GCOVBlock & Block, uint32_t LineIndex, uint32_t & BlockNo) const protected
printBlockInfo - Output counts for each block.
Definition at line 806 of file GCOV.cpp.
References llvm::format().
Referenced by print().
printBranchInfo()
void FileInfo::printBranchInfo (raw_ostream & OS, const GCOVBlock & Block, GCOVCoverage & Coverage, uint32_t & EdgeNo) protected
printBranchInfo - Print conditional branch probabilities.
Definition at line 816 of file GCOV.cpp.
References llvm::GCOVCoverage::Branches, llvm::GCOVCoverage::BranchesExec, llvm::GCOVCoverage::BranchesTaken, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::find(), llvm::format(), llvm::GCOV::Options::FuncCoverage, FuncCoverages, N, and Options.
Referenced by print().
printCoverage()
void FileInfo::printCoverage (raw_ostream & OS, const GCOVCoverage & Coverage) const protected
Definition at line 854 of file GCOV.cpp.
References llvm::GCOV::Options::BranchInfo, llvm::format(), and Options.
Referenced by printFileCoverage(), and printFuncCoverage().
printFileCoverage()
void FileInfo::printFileCoverage (raw_ostream & OS) const protected
Definition at line 885 of file GCOV.cpp.
References llvm::GCOV::Options::Intermediate, llvm::GCOV::Options::NoOutput, Options, printCoverage(), and sources.
Referenced by print().
printFuncCoverage()
void FileInfo::printFuncCoverage (raw_ostream & OS) const protected
Definition at line 875 of file GCOV.cpp.
References FuncCoverages, and printCoverage().
Referenced by print().
printFunctionSummary()
void FileInfo::printFunctionSummary (raw_ostream & OS, const FunctionVector & Funcs) const protected
printFunctionSummary - Print function and block summary.
Definition at line 789 of file GCOV.cpp.
References safeDiv().
Referenced by print().
printUncondBranchInfo()
void FileInfo::printUncondBranchInfo (raw_ostream & OS, uint32_t & EdgeNo, uint64_t Count) const protected
printUncondBranchInfo - Print unconditional branch probabilities.
Definition at line 846 of file GCOV.cpp.
References llvm::format(), and Options.
Referenced by print().
setProgramCount()
void llvm::FileInfo::setProgramCount (uint32_t Programs) inline
Definition at line 384 of file GCOV.h.
References ProgramCount.
setRunCount()
void llvm::FileInfo::setRunCount (uint32_t Runs) inline
Definition at line 383 of file GCOV.h.
References RunCount.
Friends And Related Symbol Documentation
GCOVFile
friend class GCOVFile friend
Definition at line 367 of file GCOV.h.
Member Data Documentation
FuncCoverages
FuncCoverageMap llvm::FileInfo::FuncCoverages protected
Definition at line 410 of file GCOV.h.
Referenced by print(), printBranchInfo(), and printFuncCoverage().
LineInfo
StringMap<LineData> llvm::FileInfo::LineInfo protected
Definition at line 404 of file GCOV.h.
Referenced by addBlockLine(), addFunctionLine(), and print().
Options
const GCOV::Options& llvm::FileInfo::Options protected
Definition at line 403 of file GCOV.h.
Referenced by getCoveragePath(), print(), printBranchInfo(), printCoverage(), printFileCoverage(), and printUncondBranchInfo().
ProgramCount
uint32_t llvm::FileInfo::ProgramCount = 0 protected
Definition at line 406 of file GCOV.h.
Referenced by print(), and setProgramCount().
RunCount
uint32_t llvm::FileInfo::RunCount = 0 protected
Definition at line 405 of file GCOV.h.
Referenced by print(), and setRunCount().
sources
std::vector<SourceInfo> llvm::FileInfo::sources protected
Definition at line 411 of file GCOV.h.
Referenced by print(), and printFileCoverage().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/GCOV.h
lib/ProfileData/GCOV.cpp