LLVM: llvm::pdb::HashTable< ValueT > Class Template Reference
llvm::pdb::HashTable< ValueT > Class Template Reference
#include "llvm/DebugInfo/PDB/Native/HashTable.h"
Public Types
using const_iterator = HashTableIterator<ValueT>
Public Member Functions
HashTable ()
HashTable (uint32_t Capacity)
Error load (BinaryStreamReader &Stream)
uint32_t calculateSerializedLength () const
Error commit (BinaryStreamWriter &Writer) const
void clear ()
bool empty () const
uint32_t capacity () const
uint32_t size () const
const_iterator begin () const
const_iterator end () const
template<typename Key , typename TraitsT >
const_iterator find_as (const Key &K, TraitsT &Traits) const
Find the entry whose key has the specified hash value, using the specified traits defining hash function and equality.
template<typename Key , typename TraitsT >
bool set_as (const Key &K, ValueT V, TraitsT &Traits)
Set the entry using a key type that the specified Traits can convert from a real key to an internal key.
template<typename Key , typename TraitsT >
ValueT get (const Key &K, TraitsT &Traits) const
Public Attributes
friend const_iterator
Protected Member Functions
bool isPresent (uint32_t K) const
bool isDeleted (uint32_t K) const
Protected Attributes
BucketList Buckets
SparseBitVector Present
SparseBitVector Deleted
Detailed Description
template<typename ValueT>
class llvm::pdb::HashTable< ValueT >
Definition at line 103 of file HashTable.h.
Member Typedef Documentation
const_iterator
template<typename ValueT > using llvm::pdb::HashTable< ValueT >::const_iterator = HashTableIterator<ValueT>
Definition at line 112 of file HashTable.h.
Constructor & Destructor Documentation
HashTable() [1/2]
template<typename ValueT > llvm::pdb::HashTable< ValueT >::HashTable () inline
Definition at line 115 of file HashTable.h.
References llvm::pdb::HashTable< ValueT >::Buckets.
HashTable() [2/2]
template<typename ValueT > llvm::pdb::HashTable< ValueT >::HashTable (uint32_t Capacity) inline explicit
Definition at line 116 of file HashTable.h.
References llvm::pdb::HashTable< ValueT >::Buckets.
Member Function Documentation
begin()
template<typename ValueT > const_iterator llvm::pdb::HashTable< ValueT >::begin () const inline
Definition at line 216 of file HashTable.h.
Referenced by llvm::pdb::InjectedSourceStream::begin().
calculateSerializedLength()
template<typename ValueT > uint32_t llvm::pdb::HashTable< ValueT >::calculateSerializedLength () const inline
Definition at line 157 of file HashTable.h.
References llvm::alignTo(), llvm::pdb::HashTable< ValueT >::Deleted, llvm::SparseBitVector< ElementSize >::find_last(), llvm::pdb::HashTable< ValueT >::Present, llvm::pdb::HashTable< ValueT >::size(), and Size.
capacity()
template<typename ValueT > uint32_t llvm::pdb::HashTable< ValueT >::capacity () const inline
Definition at line 213 of file HashTable.h.
References llvm::pdb::HashTable< ValueT >::Buckets.
Referenced by llvm::pdb::HashTable< ValueT >::commit(), and llvm::pdb::HashTable< ValueT >::find_as().
clear()
template<typename ValueT > void llvm::pdb::HashTable< ValueT >::clear () inline
Definition at line 206 of file HashTable.h.
References llvm::pdb::HashTable< ValueT >::Buckets, llvm::SparseBitVector< ElementSize >::clear(), llvm::pdb::HashTable< ValueT >::Deleted, and llvm::pdb::HashTable< ValueT >::Present.
commit()
template<typename ValueT > Error llvm::pdb::HashTable< ValueT >::commit (BinaryStreamWriter & Writer) const inline
Definition at line 184 of file HashTable.h.
References llvm::pdb::HashTable< ValueT >::capacity(), llvm::pdb::HashTable< ValueT >::Deleted, H, llvm::pdb::HashTable< ValueT >::Present, llvm::pdb::HashTable< ValueT >::size(), llvm::Error::success(), llvm::BinaryStreamWriter::writeInteger(), llvm::BinaryStreamWriter::writeObject(), and llvm::pdb::writeSparseBitVector().
empty()
template<typename ValueT > bool llvm::pdb::HashTable< ValueT >::empty () const inline
Definition at line 212 of file HashTable.h.
References llvm::pdb::HashTable< ValueT >::size().
end()
template<typename ValueT > const_iterator llvm::pdb::HashTable< ValueT >::end () const inline
Definition at line 217 of file HashTable.h.
Referenced by llvm::pdb::InjectedSourceStream::end(), and llvm::pdb::HashTable< ValueT >::get().
find_as()
template<typename ValueT > template<typename Key , typename TraitsT > const_iterator llvm::pdb::HashTable< ValueT >::find_as (const Key & K, TraitsT & Traits) const inline
Find the entry whose key has the specified hash value, using the specified traits defining hash function and equality.
Definition at line 222 of file HashTable.h.
References assert(), llvm::pdb::HashTable< ValueT >::Buckets, llvm::pdb::HashTable< ValueT >::capacity(), H, I, llvm::pdb::HashTable< ValueT >::isDeleted(), and llvm::pdb::HashTable< ValueT >::isPresent().
Referenced by llvm::pdb::HashTable< ValueT >::get().
get()
template<typename ValueT > template<typename Key , typename TraitsT > ValueT llvm::pdb::HashTable< ValueT >::get (const Key & K, TraitsT & Traits) const inline
Definition at line 259 of file HashTable.h.
References assert(), llvm::pdb::HashTable< ValueT >::end(), and llvm::pdb::HashTable< ValueT >::find_as().
isDeleted()
template<typename ValueT > bool llvm::pdb::HashTable< ValueT >::isDeleted (uint32_t K) const inline protected
Definition at line 267 of file HashTable.h.
References llvm::pdb::HashTable< ValueT >::Deleted, and llvm::SparseBitVector< ElementSize >::test().
Referenced by llvm::pdb::HashTable< ValueT >::find_as().
isPresent()
template<typename ValueT > bool llvm::pdb::HashTable< ValueT >::isPresent (uint32_t K) const inline protected
Definition at line 266 of file HashTable.h.
References llvm::pdb::HashTable< ValueT >::Present, and llvm::SparseBitVector< ElementSize >::test().
Referenced by llvm::pdb::HashTable< ValueT >::find_as().
load()
template<typename ValueT > Error llvm::pdb::HashTable< ValueT >::load (BinaryStreamReader & Stream) inline
Definition at line 120 of file HashTable.h.
References llvm::pdb::HashTable< ValueT >::Buckets, llvm::pdb::corrupt_file, llvm::SparseBitVector< ElementSize >::count(), llvm::pdb::HashTable< ValueT >::Deleted, H, llvm::SparseBitVector< ElementSize >::intersects(), P, llvm::pdb::HashTable< ValueT >::Present, llvm::BinaryStreamReader::readInteger(), llvm::BinaryStreamReader::readObject(), llvm::pdb::readSparseBitVector(), and llvm::Error::success().
Referenced by llvm::pdb::InjectedSourceStream::reload().
set_as()
template<typename ValueT > template<typename Key , typename TraitsT > bool llvm::pdb::HashTable< ValueT >::set_as (const Key & K, ValueT V, TraitsT & Traits) inline
Set the entry using a key type that the specified Traits can convert from a real key to an internal key.
Definition at line 254 of file HashTable.h.
References llvm::pdb::None.
size()
template<typename ValueT > uint32_t llvm::pdb::HashTable< ValueT >::size () const inline
Definition at line 214 of file HashTable.h.
References llvm::SparseBitVector< ElementSize >::count(), and llvm::pdb::HashTable< ValueT >::Present.
Referenced by llvm::pdb::HashTable< ValueT >::calculateSerializedLength(), llvm::pdb::HashTable< ValueT >::commit(), llvm::pdb::HashTable< ValueT >::empty(), and llvm::pdb::InjectedSourceStream::size().
Member Data Documentation
Buckets
template<typename ValueT > BucketList llvm::pdb::HashTable< ValueT >::Buckets protected
Definition at line 269 of file HashTable.h.
Referenced by llvm::pdb::HashTable< ValueT >::capacity(), llvm::pdb::HashTable< ValueT >::clear(), llvm::pdb::HashTable< ValueT >::find_as(), llvm::pdb::HashTable< ValueT >::HashTable(), llvm::pdb::HashTable< ValueT >::HashTable(), and llvm::pdb::HashTable< ValueT >::load().
const_iterator
template<typename ValueT > friend llvm::pdb::HashTable< ValueT >::const_iterator
Definition at line 113 of file HashTable.h.
Deleted
template<typename ValueT > SparseBitVector llvm::pdb::HashTable< ValueT >::Deleted mutable protected
Definition at line 271 of file HashTable.h.
Referenced by llvm::pdb::HashTable< ValueT >::calculateSerializedLength(), llvm::pdb::HashTable< ValueT >::clear(), llvm::pdb::HashTable< ValueT >::commit(), llvm::pdb::HashTable< ValueT >::isDeleted(), and llvm::pdb::HashTable< ValueT >::load().
Present
template<typename ValueT > SparseBitVector llvm::pdb::HashTable< ValueT >::Present mutable protected
Definition at line 270 of file HashTable.h.
Referenced by llvm::pdb::HashTable< ValueT >::calculateSerializedLength(), llvm::pdb::HashTable< ValueT >::clear(), llvm::pdb::HashTable< ValueT >::commit(), llvm::pdb::HashTable< ValueT >::isPresent(), llvm::pdb::HashTable< ValueT >::load(), and llvm::pdb::HashTable< ValueT >::size().
The documentation for this class was generated from the following file:
include/llvm/DebugInfo/PDB/Native/HashTable.h