LLVM: llvm::SyntheticCountsPropagation Class Reference
llvm::SyntheticCountsPropagation Class Reference
#include "llvm/Transforms/IPO/SyntheticCountsPropagation.h"
Public Member Functions
PreservedAnalyses run (Module &M, ModuleAnalysisManager &MAM)
Additional Inherited Members
Static Public Member Functions inherited from llvm::PassInfoMixin< SyntheticCountsPropagation >
static StringRef name ()
Gets the name of the pass we are mixed into.
Detailed Description
Definition at line 17 of file SyntheticCountsPropagation.h.
Member Function Documentation
run()
PreservedAnalyses SyntheticCountsPropagation::run (Module & M, ModuleAnalysisManager & MAM)
Definition at line 96 of file SyntheticCountsPropagation.cpp.
References llvm::PreservedAnalyses::all(), CG, F, llvm::CallBase::getCaller(), llvm::Instruction::getParent(), llvm::AnalysisManager< IRUnitT, ExtraArgTs >::getResult(), initializeCounts(), N, llvm::None, llvm::Function::PCT_Synthetic, and llvm::SyntheticCountsUtils< CallGraphType >::propagate().
The documentation for this class was generated from the following files:
include/llvm/Transforms/IPO/SyntheticCountsPropagation.h
lib/Transforms/IPO/SyntheticCountsPropagation.cpp