LLVM: llvm::HexagonInstr Class Reference
llvm::HexagonInstr Class Reference
#include "Target/Hexagon/MCTargetDesc/HexagonShuffler.h"
Public Member Functions
HexagonInstr (MCInstrInfo const &MCII, MCSubtargetInfo const &STI, MCInst const *id, MCInst const *Extender, unsigned s)
MCInst const & getDesc () const
MCInst const * getExtender () const
bool operator< (const HexagonInstr &B) const
Static Public Member Functions
static bool lessCore (const HexagonInstr &A, const HexagonInstr &B)
static bool lessCVI (const HexagonInstr &A, const HexagonInstr &B)
Friends
class HexagonShuffler
Detailed Description
Definition at line 108 of file HexagonShuffler.h.
Constructor & Destructor Documentation
HexagonInstr()
llvm::HexagonInstr::HexagonInstr (MCInstrInfo const & MCII, MCSubtargetInfo const & STI, MCInst const * id, MCInst const * Extender, unsigned s) inline
Definition at line 117 of file HexagonShuffler.h.
Member Function Documentation
getDesc()
MCInst const & llvm::HexagonInstr::getDesc () const inline
Definition at line 122 of file HexagonShuffler.h.
getExtender()
MCInst const * llvm::HexagonInstr::getExtender () const inline
Definition at line 123 of file HexagonShuffler.h.
lessCore()
static bool llvm::HexagonInstr::lessCore (const HexagonInstr & A, const HexagonInstr & B) inline static
Definition at line 131 of file HexagonShuffler.h.
References A, B, and llvm::HexagonResource::lessUnits().
Referenced by llvm::HexagonShuffler::tryAuction().
lessCVI()
static bool llvm::HexagonInstr::lessCVI (const HexagonInstr & A, const HexagonInstr & B) inline static
Definition at line 136 of file HexagonShuffler.h.
References A, B, and llvm::HexagonResource::lessUnits().
Referenced by llvm::HexagonShuffler::ValidResourceUsage().
operator<()
bool llvm::HexagonInstr::operator< (const HexagonInstr & B) const inline
Definition at line 126 of file HexagonShuffler.h.
References B, and llvm::HexagonResource::lessWeight().
Friends And Related Symbol Documentation
HexagonShuffler
friend class HexagonShuffler friend
Definition at line 109 of file HexagonShuffler.h.
The documentation for this class was generated from the following file:
lib/Target/Hexagon/MCTargetDesc/HexagonShuffler.h