LLVM: llvm::GCNRPTracker Class Reference
llvm::GCNRPTracker Class Reference
#include "Target/AMDGPU/GCNRegPressure.h"
Public Types
using LiveRegSet = DenseMap<unsigned, LaneBitmask>
Public Member Functions
const decltype(LiveRegs) & getLiveRegs () const
const MachineInstr * getLastTrackedMI () const
void clearMaxPressure ()
decltype(MaxPressure) moveMaxPressure ()
decltype(LiveRegs) moveLiveRegs ()
Static Public Member Functions
static void printLiveRegs (raw_ostream &OS, const LiveRegSet &LiveRegs, const MachineRegisterInfo &MRI)
Protected Member Functions
GCNRPTracker (const LiveIntervals &LIS_)
void reset (const MachineInstr &MI, const LiveRegSet *LiveRegsCopy, bool After)
Protected Attributes
const LiveIntervals & LIS
LiveRegSet LiveRegs
GCNRegPressure CurPressure
GCNRegPressure MaxPressure
const MachineInstr * LastTrackedMI = nullptr
const MachineRegisterInfo * MRI = nullptr
Detailed Description
Definition at line 106 of file GCNRegPressure.h.
Member Typedef Documentation
LiveRegSet
using llvm::GCNRPTracker::LiveRegSet = DenseMap<unsigned, LaneBitmask>
Definition at line 108 of file GCNRegPressure.h.
Constructor & Destructor Documentation
GCNRPTracker()
llvm::GCNRPTracker::GCNRPTracker (const LiveIntervals & LIS_) inline protected
Definition at line 117 of file GCNRegPressure.h.
Member Function Documentation
clearMaxPressure()
void llvm::GCNRPTracker::clearMaxPressure () inline
Definition at line 127 of file GCNRegPressure.h.
References llvm::GCNRegPressure::clear(), and MaxPressure.
getLastTrackedMI()
const MachineInstr * llvm::GCNRPTracker::getLastTrackedMI () const inline
Definition at line 125 of file GCNRegPressure.h.
References LastTrackedMI.
Referenced by llvm::GCNIterativeScheduler::getRegionPressure().
getLiveRegs()
const decltype(LiveRegs) & llvm::GCNRPTracker::getLiveRegs () const inline
Definition at line 124 of file GCNRegPressure.h.
References LiveRegs.
moveLiveRegs()
decltype(LiveRegs) llvm::GCNRPTracker::moveLiveRegs () inline
Definition at line 136 of file GCNRegPressure.h.
References LiveRegs.
moveMaxPressure()
decltype(MaxPressure) llvm::GCNRPTracker::moveMaxPressure () inline
Definition at line 130 of file GCNRegPressure.h.
References llvm::GCNRegPressure::clear(), and MaxPressure.
Referenced by llvm::GCNIterativeScheduler::getRegionPressure().
printLiveRegs()
void GCNRPTracker::printLiveRegs (raw_ostream & OS, const LiveRegSet & LiveRegs, const MachineRegisterInfo & MRI) static
Definition at line 500 of file GCNRegPressure.cpp.
References E, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT, BucketT >::find(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), I, llvm::Register::index2VirtReg(), LiveRegs, MRI, llvm::PrintLaneMask(), llvm::printVRegOrUnit(), and TRI.
Referenced by llvm::GCNScheduleDAGMILive::schedule().
reset()
void GCNRPTracker::reset (const MachineInstr & MI, const LiveRegSet * LiveRegsCopy, bool After) protected
Definition at line 292 of file GCNRegPressure.cpp.
References CurPressure, llvm::getLiveRegsAfter(), llvm::getLiveRegsBefore(), llvm::MachineFunction::getRegInfo(), llvm::getRegPressure(), LIS, LiveRegs, MaxPressure, MI, and MRI.
Referenced by llvm::GCNUpwardRPTracker::reset(), and llvm::GCNDownwardRPTracker::reset().
Member Data Documentation
CurPressure
GCNRegPressure llvm::GCNRPTracker::CurPressure protected
Definition at line 113 of file GCNRegPressure.h.
Referenced by llvm::GCNDownwardRPTracker::advanceBeforeNext(), llvm::GCNDownwardRPTracker::advanceToNext(), llvm::GCNUpwardRPTracker::isValid(), llvm::GCNUpwardRPTracker::recede(), and reset().
LastTrackedMI
const MachineInstr* llvm::GCNRPTracker::LastTrackedMI = nullptr protected
Definition at line 114 of file GCNRegPressure.h.
Referenced by llvm::GCNDownwardRPTracker::advance(), llvm::GCNDownwardRPTracker::advanceToNext(), getLastTrackedMI(), llvm::GCNUpwardRPTracker::recede(), and llvm::GCNDownwardRPTracker::reset().
LIS
const LiveIntervals& llvm::GCNRPTracker::LIS protected
Definition at line 111 of file GCNRegPressure.h.
Referenced by llvm::GCNDownwardRPTracker::advanceBeforeNext(), llvm::GCNUpwardRPTracker::isValid(), llvm::GCNUpwardRPTracker::recede(), and reset().
LiveRegs
LiveRegSet llvm::GCNRPTracker::LiveRegs protected
Definition at line 112 of file GCNRegPressure.h.
Referenced by llvm::GCNDownwardRPTracker::advanceBeforeNext(), llvm::GCNDownwardRPTracker::advanceToNext(), getLiveRegs(), llvm::GCNUpwardRPTracker::isValid(), moveLiveRegs(), printLiveRegs(), llvm::GCNUpwardRPTracker::recede(), and reset().
MaxPressure
GCNRegPressure llvm::GCNRPTracker::MaxPressure protected
Definition at line 113 of file GCNRegPressure.h.
Referenced by llvm::GCNDownwardRPTracker::advanceBeforeNext(), llvm::GCNDownwardRPTracker::advanceToNext(), clearMaxPressure(), moveMaxPressure(), llvm::GCNUpwardRPTracker::recede(), and reset().
MRI
const MachineRegisterInfo* llvm::GCNRPTracker::MRI = nullptr mutable protected
Definition at line 115 of file GCNRegPressure.h.
Referenced by llvm::GCNDownwardRPTracker::advanceBeforeNext(), llvm::GCNDownwardRPTracker::advanceToNext(), llvm::GCNUpwardRPTracker::isValid(), printLiveRegs(), llvm::GCNUpwardRPTracker::recede(), llvm::GCNDownwardRPTracker::reset(), and reset().
The documentation for this class was generated from the following files:
lib/Target/AMDGPU/GCNRegPressure.h
lib/Target/AMDGPU/GCNRegPressure.cpp