LLVM: llvm::GCOVBlock Class Reference
llvm::GCOVBlock Class Reference
GCOVBlock - Collects block information.
#include "llvm/ProfileData/GCOV.h"
Public Types
using EdgeIterator = SmallVectorImpl<GCOVArc *>::const_iterator
using BlockVector = SmallVector<const GCOVBlock *, 4>
using BlockVectorLists = SmallVector<BlockVector, 4>
using Edges = SmallVector<GCOVArc *, 4>
Public Member Functions
GCOVBlock (GCOVFunction &P, uint32_t N)
const GCOVFunction & getParent () const
void addLine (uint32_t N)
uint32_t getLastLine () const
uint64_t getCount () const
void addSrcEdge (GCOVArc *Edge)
void addDstEdge (GCOVArc *Edge)
size_t getNumSrcEdges () const
size_t getNumDstEdges () const
iterator_range< EdgeIterator > srcs () const
iterator_range< EdgeIterator > dsts () const
void print (raw_ostream &OS) const
void dump () const
dump - Dump GCOVBlock content to dbgs() for debugging purposes.
void collectLineCounts (FileInfo &FI)
collectLineCounts - Collect line counts.
Static Public Member Functions
static uint64_t getCycleCount (const Edges &Path)
Get the count for the detected cycle.
static void unblock (const GCOVBlock *U, BlockVector &Blocked, BlockVectorLists &BlockLists)
Unblock a vertex previously marked as blocked.
static bool lookForCircuit (const GCOVBlock *V, const GCOVBlock *Start, Edges &Path, BlockVector &Blocked, BlockVectorLists &BlockLists, const BlockVector &Blocks, uint64_t &Count)
static void getCyclesCount (const BlockVector &Blocks, uint64_t &Count)
Get the count for the list of blocks which lie on the same line.
static uint64_t getLineCount (const BlockVector &Blocks)
Get the count for the list of blocks which lie on the same line.
Public Attributes
GCOVFunction & Parent
uint32_t Number
uint64_t Counter = 0
SmallVector< GCOVArc *, 2 > pred
SmallVector< GCOVArc *, 2 > succ
SmallVector< uint32_t, 16 > Lines
Detailed Description
GCOVBlock - Collects block information.
Definition at line 265 of file GCOV.h.
Member Typedef Documentation
BlockVector
using llvm::GCOVBlock::BlockVector = SmallVector<const GCOVBlock *, 4>
Definition at line 275 of file GCOV.h.
BlockVectorLists
using llvm::GCOVBlock::BlockVectorLists = SmallVector<BlockVector, 4>
Definition at line 276 of file GCOV.h.
EdgeIterator
using llvm::GCOVBlock::EdgeIterator = SmallVectorImpl<GCOVArc *>::const_iterator
Definition at line 274 of file GCOV.h.
Edges
using llvm::GCOVBlock::Edges = SmallVector<GCOVArc *, 4>
Definition at line 277 of file GCOV.h.
Constructor & Destructor Documentation
GCOVBlock()
llvm::GCOVBlock::GCOVBlock (GCOVFunction & P, uint32_t N) inline
Definition at line 279 of file GCOV.h.
Member Function Documentation
addDstEdge()
void llvm::GCOVBlock::addDstEdge (GCOVArc * Edge) inline
Definition at line 288 of file GCOV.h.
References succ.
Referenced by llvm::GCOVFile::readGCNO().
addLine()
void llvm::GCOVBlock::addLine (uint32_t N) inline
Definition at line 282 of file GCOV.h.
References Lines, N, and llvm::SmallVectorTemplateBase< T, bool >::push_back().
addSrcEdge()
void llvm::GCOVBlock::addSrcEdge (GCOVArc * Edge) inline
Definition at line 286 of file GCOV.h.
References pred.
Referenced by llvm::GCOVFile::readGCNO().
collectLineCounts()
void GCOVBlock::collectLineCounts (FileInfo & FI)
collectLineCounts - Collect line counts.
This must be used after reading .gcno and .gcda files.
Definition at line 310 of file GCOV.cpp.
References llvm::FileInfo::addBlockLine(), llvm::GCOVFunction::getFilename(), Lines, N, and Parent.
dsts()
iterator_range< EdgeIterator > llvm::GCOVBlock::dsts () const inline
Definition at line 297 of file GCOV.h.
References llvm::make_range(), and succ.
dump()
LLVM_DUMP_METHOD void GCOVBlock::dump () const
dump - Dump GCOVBlock content to dbgs() for debugging purposes.
Definition at line 339 of file GCOV.cpp.
References llvm::dbgs(), and print().
getCount()
uint64_t llvm::GCOVBlock::getCount () const inline
Definition at line 284 of file GCOV.h.
References Counter.
getCycleCount()
uint64_t GCOVBlock::getCycleCount (const Edges & Path) static
Get the count for the detected cycle.
Definition at line 350 of file GCOV.cpp.
References E.
Referenced by lookForCircuit().
getCyclesCount()
void GCOVBlock::getCyclesCount (const BlockVector & Blocks, uint64_t & Count) static
Get the count for the list of blocks which lie on the same line.
Definition at line 428 of file GCOV.cpp.
References lookForCircuit().
Referenced by getLineCount().
getLastLine()
uint32_t llvm::GCOVBlock::getLastLine () const inline
Definition at line 283 of file GCOV.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), and Lines.
getLineCount()
uint64_t GCOVBlock::getLineCount (const BlockVector & Blocks) static
Get the count for the list of blocks which lie on the same line.
Definition at line 440 of file GCOV.cpp.
References E, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::find(), and getCyclesCount().
Referenced by llvm::FileInfo::print().
getNumDstEdges()
size_t llvm::GCOVBlock::getNumDstEdges () const inline
Definition at line 291 of file GCOV.h.
References succ.
getNumSrcEdges()
size_t llvm::GCOVBlock::getNumSrcEdges () const inline
Definition at line 290 of file GCOV.h.
References pred.
getParent()
const GCOVFunction & llvm::GCOVBlock::getParent () const inline
Definition at line 281 of file GCOV.h.
References Parent.
lookForCircuit()
bool GCOVBlock::lookForCircuit (const GCOVBlock * V, const GCOVBlock * Start, Edges & Path, BlockVector & Blocked, BlockVectorLists & BlockLists, const BlockVector & Blocks, uint64_t & Count) static
Definition at line 379 of file GCOV.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), E, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::find(), getCycleCount(), llvm::List, lookForCircuit(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorTemplateBase< T, bool >::push_back(), and unblock().
Referenced by getCyclesCount(), and lookForCircuit().
print()
void GCOVBlock::print (raw_ostream & OS) const
Definition at line 315 of file GCOV.cpp.
References Counter, llvm::SmallVectorBase< Size_T >::empty(), Lines, N, Number, pred, and succ.
Referenced by dump().
srcs()
iterator_range< EdgeIterator > llvm::GCOVBlock::srcs () const inline
Definition at line 293 of file GCOV.h.
References llvm::make_range(), and pred.
unblock()
void GCOVBlock::unblock (const GCOVBlock * U, BlockVector & Blocked, BlockVectorLists & BlockLists) static
Unblock a vertex previously marked as blocked.
Definition at line 362 of file GCOV.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::find(), and unblock().
Referenced by lookForCircuit(), and unblock().
Member Data Documentation
Counter
uint64_t llvm::GCOVBlock::Counter = 0
Definition at line 318 of file GCOV.h.
Referenced by getCount(), and print().
Lines
SmallVector<uint32_t, 16> llvm::GCOVBlock::Lines
Definition at line 321 of file GCOV.h.
Referenced by addLine(), collectLineCounts(), getLastLine(), and print().
Number
uint32_t llvm::GCOVBlock::Number
Definition at line 317 of file GCOV.h.
Referenced by print().
Parent
GCOVFunction& llvm::GCOVBlock::Parent
Definition at line 316 of file GCOV.h.
Referenced by collectLineCounts(), and getParent().
pred
SmallVector<GCOVArc *, 2> llvm::GCOVBlock::pred
Definition at line 319 of file GCOV.h.
Referenced by addSrcEdge(), getNumSrcEdges(), print(), and srcs().
succ
SmallVector<GCOVArc *, 2> llvm::GCOVBlock::succ
Definition at line 320 of file GCOV.h.
Referenced by addDstEdge(), dsts(), getNumDstEdges(), and print().
The documentation for this class was generated from the following files:
include/llvm/ProfileData/GCOV.h
lib/ProfileData/GCOV.cpp