LLVM: llvm::PredicateInfo Class Reference
llvm::PredicateInfo Class Reference
Encapsulates PredicateInfo, including all data associated with memory accesses.
#include "llvm/Transforms/Utils/PredicateInfo.h"
Public Member Functions
PredicateInfo (Function &, DominatorTree &, AssumptionCache &)
~PredicateInfo ()
void verifyPredicateInfo () const
void dump () const
void print (raw_ostream &) const
const PredicateBase * getPredicateInfoFor (const Value *V) const
Friends
class PredicateInfoAnnotatedWriter
class PredicateInfoPrinterLegacyPass
class PredicateInfoBuilder
Detailed Description
Encapsulates PredicateInfo, including all data associated with memory accesses.
Definition at line 174 of file PredicateInfo.h.
Constructor & Destructor Documentation
PredicateInfo()
llvm::PredicateInfo::PredicateInfo (Function & F, DominatorTree & DT, AssumptionCache & AC)
Definition at line 801 of file PredicateInfo.cpp.
References Builder, and F.
~PredicateInfo()
llvm::PredicateInfo::~PredicateInfo ()
Definition at line 810 of file PredicateInfo.cpp.
References assert(), llvm::Function::eraseFromParent(), llvm::Value::user_begin(), and llvm::Value::user_end().
Member Function Documentation
dump()
void llvm::PredicateInfo::dump () const
Definition at line 925 of file PredicateInfo.cpp.
References llvm::dbgs(), and F.
getPredicateInfoFor()
const PredicateBase * llvm::PredicateInfo::getPredicateInfoFor (const Value * V) const inline
Definition at line 184 of file PredicateInfo.h.
Referenced by llvm::PredicateInfoAnnotatedWriter::emitInstructionAnnot(), and llvm::replaceCreatedSSACopys().
print()
void llvm::PredicateInfo::print (raw_ostream & OS) const
Definition at line 920 of file PredicateInfo.cpp.
References F.
verifyPredicateInfo()
void llvm::PredicateInfo::verifyPredicateInfo () const
Definition at line 825 of file PredicateInfo.cpp.
Friends And Related Symbol Documentation
PredicateInfoAnnotatedWriter
friend class PredicateInfoAnnotatedWriter friend
Definition at line 190 of file PredicateInfo.h.
PredicateInfoBuilder
friend class PredicateInfoBuilder friend
Definition at line 192 of file PredicateInfo.h.
PredicateInfoPrinterLegacyPass
friend class PredicateInfoPrinterLegacyPass friend
Definition at line 191 of file PredicateInfo.h.
The documentation for this class was generated from the following files:
include/llvm/Transforms/Utils/PredicateInfo.h
lib/Transforms/Utils/PredicateInfo.cpp