LLVM: llvm::object::ExportEntry Class Reference
llvm::object::ExportEntry Class Reference
ExportEntry encapsulates the current-state-of-the-walk used when doing a non-recursive walk of the trie data structure.
#include "llvm/Object/MachO.h"
Public Member Functions
ExportEntry (Error *Err, const MachOObjectFile *O, ArrayRef< uint8_t > Trie)
StringRef name () const
uint64_t flags () const
uint64_t address () const
uint64_t other () const
StringRef otherName () const
uint32_t nodeOffset () const
bool operator== (const ExportEntry &) const
void moveNext ()
Friends
class MachOObjectFile
Detailed Description
ExportEntry encapsulates the current-state-of-the-walk used when doing a non-recursive walk of the trie data structure.
This allows you to iterate across all exported symbols using: Error Err = Error::success(); for (const llvm::object::ExportEntry &AnExport : Obj->exports(&Err)) { } if (Err) { report error ...
Definition at line 72 of file MachO.h.
Constructor & Destructor Documentation
ExportEntry()
ExportEntry::ExportEntry (Error * Err, const MachOObjectFile * O, ArrayRef< uint8_t > Trie)
Definition at line 2789 of file MachOObjectFile.cpp.
Member Function Documentation
address()
uint64_t ExportEntry::address () const
Definition at line 2840 of file MachOObjectFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
flags()
uint64_t ExportEntry::flags () const
Definition at line 2836 of file MachOObjectFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
moveNext()
void ExportEntry::moveNext ()
Definition at line 3063 of file MachOObjectFile.cpp.
References assert(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::ArrayRef< T >::begin(), llvm::Done, E, llvm::SmallVectorBase< Size_T >::empty(), malformedError(), llvm::SmallVectorTemplateBase< T, bool >::pop_back(), llvm::SmallVectorImpl< T >::resize(), and llvm::Twine::utohexstr().
name()
StringRef ExportEntry::name () const
Definition at line 2832 of file MachOObjectFile.cpp.
nodeOffset()
uint32_t ExportEntry::nodeOffset () const
Definition at line 2855 of file MachOObjectFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), and llvm::ArrayRef< T >::begin().
operator==()
bool ExportEntry::operator== (const ExportEntry & Other) const
Definition at line 2805 of file MachOObjectFile.cpp.
References llvm::Done, llvm::SmallString< InternalLen >::equals(), llvm::Other, and llvm::SmallVectorBase< Size_T >::size().
other()
uint64_t ExportEntry::other () const
Definition at line 2844 of file MachOObjectFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
otherName()
StringRef ExportEntry::otherName () const
Definition at line 2848 of file MachOObjectFile.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
Friends And Related Symbol Documentation
MachOObjectFile
friend class MachOObjectFile friend
Definition at line 88 of file MachO.h.
The documentation for this class was generated from the following files:
include/llvm/Object/MachO.h
lib/Object/MachOObjectFile.cpp