LLVM: llvm::ModuloScheduleTestAnnotater Class Reference
llvm::ModuloScheduleTestAnnotater Class Reference
Expander that simply annotates each scheduled instruction with a post-instr symbol that can be consumed by the ModuloScheduleTest pass.
#include "llvm/CodeGen/ModuloSchedule.h"
Public Member Functions
ModuloScheduleTestAnnotater (MachineFunction &MF, ModuloSchedule &S)
void annotate ()
Performs the annotation.
Detailed Description
Expander that simply annotates each scheduled instruction with a post-instr symbol that can be consumed by the ModuloScheduleTest pass.
The post-instr symbol is a way of annotating an instruction that can be roundtripped in MIR. The syntax is: MYINST %0, post-instr-symbol <mcsymbol Stage-1_Cycle-5>
Definition at line 375 of file ModuloSchedule.h.
Constructor & Destructor Documentation
ModuloScheduleTestAnnotater()
llvm::ModuloScheduleTestAnnotater::ModuloScheduleTestAnnotater (MachineFunction & MF, ModuloSchedule & S) inline
Definition at line 380 of file ModuloSchedule.h.
Member Function Documentation
annotate()
void ModuloScheduleTestAnnotater::annotate ()
Performs the annotation.
Definition at line 2189 of file ModuloSchedule.cpp.
References llvm::MachineFunction::getContext(), llvm::ModuloSchedule::getCycle(), llvm::ModuloSchedule::getInstructions(), llvm::MCContext::getOrCreateSymbol(), llvm::ModuloSchedule::getStage(), MI, and llvm::raw_svector_ostream::str().
Referenced by llvm::SwingSchedulerDAG::schedule().
The documentation for this class was generated from the following files:
include/llvm/CodeGen/ModuloSchedule.h
lib/CodeGen/ModuloSchedule.cpp