LLVM: llvm::NoFolder Class Reference
llvm::NoFolder Class Reference final
NoFolder - Create "constants" (actually, instructions) with no folding.
#include "llvm/IR/NoFolder.h"
Public Member Functions
NoFolder ()=default
Instruction * CreateAdd (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Instruction * CreateFAdd (Constant *LHS, Constant *RHS) const override
Instruction * CreateSub (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Instruction * CreateFSub (Constant *LHS, Constant *RHS) const override
Instruction * CreateMul (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Instruction * CreateFMul (Constant *LHS, Constant *RHS) const override
Instruction * CreateUDiv (Constant *LHS, Constant *RHS, bool isExact=false) const override
Instruction * CreateSDiv (Constant *LHS, Constant *RHS, bool isExact=false) const override
Instruction * CreateFDiv (Constant *LHS, Constant *RHS) const override
Instruction * CreateURem (Constant *LHS, Constant *RHS) const override
Instruction * CreateSRem (Constant *LHS, Constant *RHS) const override
Instruction * CreateFRem (Constant *LHS, Constant *RHS) const override
Instruction * CreateShl (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Instruction * CreateLShr (Constant *LHS, Constant *RHS, bool isExact=false) const override
Instruction * CreateAShr (Constant *LHS, Constant *RHS, bool isExact=false) const override
Instruction * CreateAnd (Constant *LHS, Constant *RHS) const override
Instruction * CreateOr (Constant *LHS, Constant *RHS) const override
Instruction * CreateXor (Constant *LHS, Constant *RHS) const override
Instruction * CreateBinOp (Instruction::BinaryOps Opc, Constant *LHS, Constant *RHS) const override
Instruction * CreateNeg (Constant *C, bool HasNUW=false, bool HasNSW=false) const override
Instruction * CreateFNeg (Constant *C) const override
Instruction * CreateNot (Constant *C) const override
Instruction * CreateUnOp (Instruction::UnaryOps Opc, Constant *C) const override
Constant * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList) const override
Constant * CreateGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const override
Instruction * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList) const override
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList) const override
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const override
Instruction * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList) const override
Instruction * CreateCast (Instruction::CastOps Op, Constant *C, Type *DestTy) const override
Instruction * CreatePointerCast (Constant *C, Type *DestTy) const override
Instruction * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const override
Instruction * CreateIntCast (Constant *C, Type *DestTy, bool isSigned) const override
Instruction * CreateFPCast (Constant *C, Type *DestTy) const override
Instruction * CreateBitCast (Constant *C, Type *DestTy) const override
Instruction * CreateIntToPtr (Constant *C, Type *DestTy) const override
Instruction * CreatePtrToInt (Constant *C, Type *DestTy) const override
Instruction * CreateZExtOrBitCast (Constant *C, Type *DestTy) const override
Instruction * CreateSExtOrBitCast (Constant *C, Type *DestTy) const override
Instruction * CreateTruncOrBitCast (Constant *C, Type *DestTy) const override
Instruction * CreateICmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const override
Instruction * CreateFCmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const override
Instruction * CreateSelect (Constant *C, Constant *True, Constant *False) const override
Instruction * CreateExtractElement (Constant *Vec, Constant *Idx) const override
Instruction * CreateInsertElement (Constant *Vec, Constant *NewElt, Constant *Idx) const override
Instruction * CreateShuffleVector (Constant *V1, Constant *V2, ArrayRef< int > Mask) const override
Instruction * CreateExtractValue (Constant *Agg, ArrayRef< unsigned > IdxList) const override
Instruction * CreateInsertValue (Constant *Agg, Constant *Val, ArrayRef< unsigned > IdxList) const override
Public Member Functions inherited from llvm::IRBuilderFolder
virtual ~IRBuilderFolder ()
Detailed Description
NoFolder - Create "constants" (actually, instructions) with no folding.
Definition at line 34 of file NoFolder.h.
Constructor & Destructor Documentation
NoFolder()
llvm::NoFolder::NoFolder () explicit default
Member Function Documentation
CreateAdd()
Instruction * llvm::NoFolder::CreateAdd (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 44 of file NoFolder.h.
References llvm::Instruction::setHasNoSignedWrap(), and llvm::Instruction::setHasNoUnsignedWrap().
CreateAnd()
Instruction * llvm::NoFolder::CreateAnd (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 135 of file NoFolder.h.
CreateAShr()
Instruction * llvm::NoFolder::CreateAShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 128 of file NoFolder.h.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
CreateBinOp()
Instruction * llvm::NoFolder::CreateBinOp (Instruction::BinaryOps Opc, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 147 of file NoFolder.h.
References llvm::BinaryOperator::Create().
CreateBitCast()
Instruction * llvm::NoFolder::CreateBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 245 of file NoFolder.h.
References C, CreateCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
CreateCast()
Instruction * llvm::NoFolder::CreateCast (Instruction::CastOps Op, Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 222 of file NoFolder.h.
References C, and llvm::CastInst::Create().
Referenced by CreateBitCast(), CreateIntToPtr(), and CreatePtrToInt().
CreateExtractElement()
Instruction * llvm::NoFolder::CreateExtractElement (Constant * Vec, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 292 of file NoFolder.h.
References llvm::ExtractElementInst::Create(), and Idx.
CreateExtractValue()
Instruction * llvm::NoFolder::CreateExtractValue (Constant * Agg, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 307 of file NoFolder.h.
References llvm::ExtractValueInst::Create().
CreateFAdd()
Instruction * llvm::NoFolder::CreateFAdd (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 53 of file NoFolder.h.
CreateFCmp()
Instruction * llvm::NoFolder::CreateFCmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 278 of file NoFolder.h.
References P.
CreateFDiv()
Instruction * llvm::NoFolder::CreateFDiv (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 97 of file NoFolder.h.
CreateFMul()
Instruction * llvm::NoFolder::CreateFMul (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 79 of file NoFolder.h.
CreateFNeg()
Instruction * llvm::NoFolder::CreateFNeg (Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 165 of file NoFolder.h.
References C.
CreateFPCast()
Instruction * llvm::NoFolder::CreateFPCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 241 of file NoFolder.h.
References C, and llvm::CastInst::CreateFPCast().
CreateFRem()
Instruction * llvm::NoFolder::CreateFRem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 109 of file NoFolder.h.
CreateFSub()
Instruction * llvm::NoFolder::CreateFSub (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 66 of file NoFolder.h.
CreateGetElementPtr() [1/3]
Constant * llvm::NoFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 182 of file NoFolder.h.
References C, and llvm::ConstantExpr::getGetElementPtr().
CreateGetElementPtr() [2/3]
Instruction * llvm::NoFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 195 of file NoFolder.h.
References C, and llvm::GetElementPtrInst::Create().
CreateGetElementPtr() [3/3]
Constant * llvm::NoFolder::CreateGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 187 of file NoFolder.h.
References C, llvm::ConstantExpr::getGetElementPtr(), and Idx.
CreateICmp()
Instruction * llvm::NoFolder::CreateICmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 273 of file NoFolder.h.
References P.
CreateInBoundsGetElementPtr() [1/3]
Constant * llvm::NoFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 200 of file NoFolder.h.
References C, and llvm::ConstantExpr::getInBoundsGetElementPtr().
CreateInBoundsGetElementPtr() [2/3]
Instruction * llvm::NoFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 213 of file NoFolder.h.
References C, and llvm::GetElementPtrInst::CreateInBounds().
CreateInBoundsGetElementPtr() [3/3]
Constant * llvm::NoFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 205 of file NoFolder.h.
References C, llvm::ConstantExpr::getInBoundsGetElementPtr(), and Idx.
CreateInsertElement()
Instruction * llvm::NoFolder::CreateInsertElement (Constant * Vec, Constant * NewElt, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 297 of file NoFolder.h.
References llvm::InsertElementInst::Create(), and Idx.
CreateInsertValue()
Instruction * llvm::NoFolder::CreateInsertValue (Constant * Agg, Constant * Val, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 312 of file NoFolder.h.
References llvm::InsertValueInst::Create().
CreateIntCast()
Instruction * llvm::NoFolder::CreateIntCast (Constant * C, Type * DestTy, bool isSigned) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 236 of file NoFolder.h.
References C, and llvm::CastInst::CreateIntegerCast().
CreateIntToPtr()
Instruction * llvm::NoFolder::CreateIntToPtr (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 249 of file NoFolder.h.
References C, CreateCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
CreateLShr()
Instruction * llvm::NoFolder::CreateLShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 121 of file NoFolder.h.
References llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
CreateMul()
Instruction * llvm::NoFolder::CreateMul (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 70 of file NoFolder.h.
References llvm::Instruction::setHasNoSignedWrap(), and llvm::Instruction::setHasNoUnsignedWrap().
CreateNeg()
Instruction * llvm::NoFolder::CreateNeg (Constant * C, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 156 of file NoFolder.h.
References C, llvm::BinaryOperator::CreateNeg(), llvm::Instruction::setHasNoSignedWrap(), and llvm::Instruction::setHasNoUnsignedWrap().
CreateNot()
Instruction * llvm::NoFolder::CreateNot (Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 169 of file NoFolder.h.
References C, and llvm::BinaryOperator::CreateNot().
CreateOr()
Instruction * llvm::NoFolder::CreateOr (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 139 of file NoFolder.h.
CreatePointerBitCastOrAddrSpaceCast()
Instruction * llvm::NoFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 231 of file NoFolder.h.
References C, and llvm::CastInst::CreatePointerBitCastOrAddrSpaceCast().
CreatePointerCast()
Instruction * llvm::NoFolder::CreatePointerCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 227 of file NoFolder.h.
References C, and llvm::CastInst::CreatePointerCast().
CreatePtrToInt()
Instruction * llvm::NoFolder::CreatePtrToInt (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 253 of file NoFolder.h.
References C, and CreateCast().
CreateSDiv()
Instruction * llvm::NoFolder::CreateSDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 90 of file NoFolder.h.
CreateSelect()
Instruction * llvm::NoFolder::CreateSelect (Constant * C, Constant * True, Constant * False) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 287 of file NoFolder.h.
References C, and llvm::SelectInst::Create().
CreateSExtOrBitCast()
Instruction * llvm::NoFolder::CreateSExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 261 of file NoFolder.h.
References C, and llvm::CastInst::CreateSExtOrBitCast().
CreateShl()
Instruction * llvm::NoFolder::CreateShl (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 113 of file NoFolder.h.
References llvm::Instruction::setHasNoSignedWrap(), and llvm::Instruction::setHasNoUnsignedWrap().
CreateShuffleVector()
Instruction * llvm::NoFolder::CreateShuffleVector (Constant * V1, Constant * V2, ArrayRef< int > Mask) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 302 of file NoFolder.h.
CreateSRem()
Instruction * llvm::NoFolder::CreateSRem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 105 of file NoFolder.h.
CreateSub()
Instruction * llvm::NoFolder::CreateSub (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 57 of file NoFolder.h.
References llvm::Instruction::setHasNoSignedWrap(), and llvm::Instruction::setHasNoUnsignedWrap().
CreateTruncOrBitCast()
Instruction * llvm::NoFolder::CreateTruncOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 265 of file NoFolder.h.
References C, and llvm::CastInst::CreateTruncOrBitCast().
CreateUDiv()
Instruction * llvm::NoFolder::CreateUDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 83 of file NoFolder.h.
CreateUnOp()
Instruction * llvm::NoFolder::CreateUnOp (Instruction::UnaryOps Opc, Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 173 of file NoFolder.h.
References C, and llvm::UnaryOperator::Create().
CreateURem()
Instruction * llvm::NoFolder::CreateURem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 101 of file NoFolder.h.
CreateXor()
Instruction * llvm::NoFolder::CreateXor (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 143 of file NoFolder.h.
CreateZExtOrBitCast()
Instruction * llvm::NoFolder::CreateZExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 257 of file NoFolder.h.
References C, and llvm::CastInst::CreateZExtOrBitCast().
The documentation for this class was generated from the following files:
include/llvm/IR/NoFolder.h
lib/IR/IRBuilder.cpp