LLVM: llvm::TargetLoweringObjectFileXCOFF Class Reference
llvm::TargetLoweringObjectFileXCOFF Class Reference
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
Public Member Functions
TargetLoweringObjectFileXCOFF ()=default
~TargetLoweringObjectFileXCOFF () override=default
void Initialize (MCContext &Ctx, const TargetMachine &TM) override
This method must be called before any actual lowering is done.
bool shouldPutJumpTableInFunctionSection (bool UsesLabelDifference, const Function &F) const override
MCSection * getExplicitSectionGlobal (const GlobalObject *GO, SectionKind Kind, const TargetMachine &TM) const override
Targets should implement this method to assign a section to globals with an explicit section specfied.
MCSection * getStaticCtorSection (unsigned Priority, const MCSymbol *KeySym) const override
MCSection * getStaticDtorSection (unsigned Priority, const MCSymbol *KeySym) const override
const MCExpr * lowerRelativeReference (const GlobalValue *LHS, const GlobalValue *RHS, const TargetMachine &TM) const override
MCSection * SelectSectionForGlobal (const GlobalObject *GO, SectionKind Kind, const TargetMachine &TM) const override
MCSection * getSectionForJumpTable (const Function &F, const TargetMachine &TM) const override
MCSection * getSectionForConstant (const DataLayout &DL, SectionKind Kind, const Constant *C, Align &Alignment) const override
Given a constant with the SectionKind, return a section that it should be placed in.
MCSection * getSectionForFunctionDescriptor (const Function *F, const TargetMachine &TM) const override
On targets that use separate function descriptor symbols, return a section for the descriptor given its symbol.
MCSection * getSectionForTOCEntry (const MCSymbol *Sym) const override
On targets that support TOC entries, return a section for the entry given the symbol it refers to.
MCSection * getSectionForExternalReference (const GlobalObject *GO, const TargetMachine &TM) const override
For external functions, this will always return a function descriptor csect.
MCSymbol * getTargetSymbol (const GlobalValue *GV, const TargetMachine &TM) const override
For functions, this will always return a function descriptor symbol.
MCSymbol * getFunctionEntryPointSymbol (const Function *F, const TargetMachine &TM) const override
If supported, return the function entry point symbol.
Public Member Functions inherited from llvm::TargetLoweringObjectFile
TargetLoweringObjectFile ()=default
TargetLoweringObjectFile (const TargetLoweringObjectFile &)=delete
TargetLoweringObjectFile & operator= (const TargetLoweringObjectFile &)=delete
virtual ~TargetLoweringObjectFile ()
Mangler & getMangler () const
virtual void emitPersonalityValue (MCStreamer &Streamer, const DataLayout &TM, const MCSymbol *Sym) const
virtual void emitModuleMetadata (MCStreamer &Streamer, Module &M) const
Emit the module-level metadata that the platform cares about.
virtual void getModuleMetadata (Module &M)
Get the module-level metadata that the platform cares about.
virtual MCSection * getSectionForMachineBasicBlock (const Function &F, const MachineBasicBlock &MBB, const TargetMachine &TM) const
MCSection * SectionForGlobal (const GlobalObject *GO, SectionKind Kind, const TargetMachine &TM) const
This method computes the appropriate section to emit the specified global variable or function definition.
MCSection * SectionForGlobal (const GlobalObject *GO, const TargetMachine &TM) const
This method computes the appropriate section to emit the specified global variable or function definition.
virtual void getNameWithPrefix (SmallVectorImpl< char > &OutName, const GlobalValue *GV, const TargetMachine &TM) const
virtual const MCExpr * getTTypeGlobalReference (const GlobalValue *GV, unsigned Encoding, const TargetMachine &TM, MachineModuleInfo *MMI, MCStreamer &Streamer) const
Return an MCExpr to use for a reference to the specified global variable from exception handling information.
MCSymbol * getSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix, const TargetMachine &TM) const
Return the MCSymbol for a private symbol with global value name as its base, with the specified suffix.
virtual MCSymbol * getCFIPersonalitySymbol (const GlobalValue *GV, const TargetMachine &TM, MachineModuleInfo *MMI) const
unsigned getPersonalityEncoding () const
unsigned getLSDAEncoding () const
unsigned getTTypeEncoding () const
unsigned getCallSiteEncoding () const
const MCExpr * getTTypeReference (const MCSymbolRefExpr *Sym, unsigned Encoding, MCStreamer &Streamer) const
virtual const MCExpr * getDebugThreadLocalSymbol (const MCSymbol *Sym) const
Create a symbol reference to describe the given TLS variable when emitting the address in debug info.
bool supportIndirectSymViaGOTPCRel () const
Target supports replacing a data "PC"-relative access to a symbol through another symbol, by accessing the later via a GOT entry instead?
bool supportGOTPCRelWithOffset () const
Target GOT "PC"-relative relocation supports encoding an additional binary expression with an offset?
bool supportDebugThreadLocalLocation () const
Target supports TLS offset relocation in debug section?
virtual const MCExpr * getIndirectSymViaGOTPCRel (const GlobalValue *GV, const MCSymbol *Sym, const MCValue &MV, int64_t Offset, MachineModuleInfo *MMI, MCStreamer &Streamer) const
Get the target specific PC relative GOT entry relocation.
virtual void emitLinkerFlagsForGlobal (raw_ostream &OS, const GlobalValue *GV) const
virtual void emitLinkerFlagsForUsed (raw_ostream &OS, const GlobalValue *GV) const
virtual MCSection * getSectionForCommandLines () const
If supported, return the section to use for the llvm.commandline metadata.
Public Member Functions inherited from llvm::MCObjectFileInfo
void InitMCObjectFileInfo (const Triple &TT, bool PIC, MCContext &ctx, bool LargeCodeModel=false)
MCContext & getContext () const
bool getSupportsWeakOmittedEHFrame () const
bool getSupportsCompactUnwindWithoutEHFrame () const
bool getOmitDwarfIfHaveCompactUnwind () const
bool getCommDirectiveSupportsAlignment () const
unsigned getFDEEncoding () const
unsigned getCompactUnwindDwarfEHFrameOnly () const
MCSection * getTextSection () const
MCSection * getDataSection () const
MCSection * getBSSSection () const
MCSection * getReadOnlySection () const
MCSection * getLSDASection () const
MCSection * getCompactUnwindSection () const
MCSection * getDwarfAbbrevSection () const
MCSection * getDwarfInfoSection () const
MCSection * getDwarfInfoSection (uint64_t Hash) const
MCSection * getDwarfLineSection () const
MCSection * getDwarfLineStrSection () const
MCSection * getDwarfFrameSection () const
MCSection * getDwarfPubNamesSection () const
MCSection * getDwarfPubTypesSection () const
MCSection * getDwarfGnuPubNamesSection () const
MCSection * getDwarfGnuPubTypesSection () const
const MCSection * getDwarfDebugInlineSection () const
MCSection * getDwarfStrSection () const
MCSection * getDwarfLocSection () const
MCSection * getDwarfARangesSection () const
MCSection * getDwarfRangesSection () const
MCSection * getDwarfRnglistsSection () const
MCSection * getDwarfLoclistsSection () const
MCSection * getDwarfMacinfoSection () const
MCSection * getDwarfMacroSection () const
MCSection * getDwarfDebugNamesSection () const
MCSection * getDwarfAccelNamesSection () const
MCSection * getDwarfAccelObjCSection () const
MCSection * getDwarfAccelNamespaceSection () const
MCSection * getDwarfAccelTypesSection () const
MCSection * getDwarfInfoDWOSection () const
MCSection * getDwarfTypesSection (uint64_t Hash) const
MCSection * getDwarfTypesDWOSection () const
MCSection * getDwarfAbbrevDWOSection () const
MCSection * getDwarfStrDWOSection () const
MCSection * getDwarfLineDWOSection () const
MCSection * getDwarfLocDWOSection () const
MCSection * getDwarfStrOffDWOSection () const
MCSection * getDwarfStrOffSection () const
MCSection * getDwarfAddrSection () const
MCSection * getDwarfRnglistsDWOSection () const
MCSection * getDwarfLoclistsDWOSection () const
MCSection * getDwarfMacroDWOSection () const
MCSection * getDwarfMacinfoDWOSection () const
MCSection * getDwarfCUIndexSection () const
MCSection * getDwarfTUIndexSection () const
MCSection * getDwarfSwiftASTSection () const
MCSection * getCOFFDebugSymbolsSection () const
MCSection * getCOFFDebugTypesSection () const
MCSection * getCOFFGlobalTypeHashesSection () const
MCSection * getTLSExtraDataSection () const
const MCSection * getTLSDataSection () const
MCSection * getTLSBSSSection () const
MCSection * getStackMapSection () const
MCSection * getFaultMapSection () const
MCSection * getRemarksSection () const
MCSection * getStackSizesSection (const MCSection &TextSec) const
MCSection * getDataRelROSection () const
const MCSection * getMergeableConst4Section () const
const MCSection * getMergeableConst8Section () const
const MCSection * getMergeableConst16Section () const
const MCSection * getMergeableConst32Section () const
const MCSection * getTLSTLVSection () const
const MCSection * getTLSThreadInitSection () const
const MCSection * getCStringSection () const
const MCSection * getUStringSection () const
MCSection * getTextCoalSection () const
const MCSection * getConstTextCoalSection () const
const MCSection * getConstDataSection () const
const MCSection * getDataCoalSection () const
const MCSection * getConstDataCoalSection () const
const MCSection * getDataCommonSection () const
MCSection * getDataBSSSection () const
const MCSection * getFourByteConstantSection () const
const MCSection * getEightByteConstantSection () const
const MCSection * getSixteenByteConstantSection () const
MCSection * getLazySymbolPointerSection () const
MCSection * getNonLazySymbolPointerSection () const
MCSection * getThreadLocalPointerSection () const
MCSection * getDrectveSection () const
MCSection * getPDataSection () const
MCSection * getXDataSection () const
MCSection * getSXDataSection () const
MCSection * getGFIDsSection () const
MCSection * getGLJMPSection () const
MCSection * getTOCBaseSection () const
MCSection * getEHFrameSection ()
Environment getObjectFileType () const
bool isPositionIndependent () const
const Triple & getTargetTriple () const
void setSDKVersion (const VersionTuple &TheSDKVersion)
const VersionTuple & getSDKVersion () const
Static Public Member Functions
static XCOFF::StorageClass getStorageClassForGlobal (const GlobalObject *GO)
Static Public Member Functions inherited from llvm::TargetLoweringObjectFile
static SectionKind getKindForGlobal (const GlobalObject *GO, const TargetMachine &TM)
Classify the specified global variable into a set of target independent categories embodied in SectionKind.
Additional Inherited Members
Public Types inherited from llvm::MCObjectFileInfo
enum Environment {
IsMachO , IsELF , IsCOFF , IsWasm ,
IsXCOFF
}
Protected Attributes inherited from llvm::TargetLoweringObjectFile
bool SupportIndirectSymViaGOTPCRel = false
bool SupportGOTPCRelWithOffset = true
bool SupportDebugThreadLocalLocation = true
unsigned PersonalityEncoding = 0
PersonalityEncoding, LSDAEncoding, TTypeEncoding - Some encoding values for EH.
unsigned LSDAEncoding = 0
unsigned TTypeEncoding = 0
unsigned CallSiteEncoding = 0
MCSection * StaticCtorSection = nullptr
This section contains the static constructor pointer list.
MCSection * StaticDtorSection = nullptr
This section contains the static destructor pointer list.
Protected Attributes inherited from llvm::MCObjectFileInfo
bool CommDirectiveSupportsAlignment = false
True if .comm supports alignment.
bool SupportsWeakOmittedEHFrame = false
True if target object file supports a weak_definition of constant 0 for an omitted EH frame.
bool SupportsCompactUnwindWithoutEHFrame = false
True if the target object file supports emitting a compact unwind section without an associated EH frame section.
bool OmitDwarfIfHaveCompactUnwind = false
OmitDwarfIfHaveCompactUnwind - True if the target object file supports having some functions with compact unwind and other with dwarf unwind.
unsigned FDECFIEncoding = 0
FDE CFI encoding.
unsigned CompactUnwindDwarfEHFrameOnly = 0
Compact unwind encoding indicating that we should emit only an EH frame.
MCSection * TextSection = nullptr
Section directive for standard text.
MCSection * DataSection = nullptr
Section directive for standard data.
MCSection * BSSSection = nullptr
Section that is default initialized to zero.
MCSection * ReadOnlySection = nullptr
Section that is readonly and can contain arbitrary initialized data.
MCSection * LSDASection = nullptr
If exception handling is supported by the target, this is the section the Language Specific Data Area information is emitted to.
MCSection * CompactUnwindSection = nullptr
If exception handling is supported by the target and the target can support a compact representation of the CIE and FDE, this is the section to emit them into.
MCSection * DwarfAbbrevSection = nullptr
MCSection * DwarfInfoSection = nullptr
MCSection * DwarfLineSection = nullptr
MCSection * DwarfLineStrSection = nullptr
MCSection * DwarfFrameSection = nullptr
MCSection * DwarfPubTypesSection = nullptr
const MCSection * DwarfDebugInlineSection = nullptr
MCSection * DwarfStrSection = nullptr
MCSection * DwarfLocSection = nullptr
MCSection * DwarfARangesSection = nullptr
MCSection * DwarfRangesSection = nullptr
MCSection * DwarfMacinfoSection = nullptr
MCSection * DwarfMacroSection = nullptr
MCSection * DwarfPubNamesSection = nullptr
MCSection * DwarfDebugNamesSection = nullptr
Accelerator table sections.
MCSection * DwarfAccelNamesSection = nullptr
MCSection * DwarfAccelObjCSection = nullptr
MCSection * DwarfAccelNamespaceSection = nullptr
MCSection * DwarfAccelTypesSection = nullptr
MCSection * DwarfInfoDWOSection = nullptr
MCSection * DwarfTypesDWOSection = nullptr
MCSection * DwarfAbbrevDWOSection = nullptr
MCSection * DwarfStrDWOSection = nullptr
MCSection * DwarfLineDWOSection = nullptr
MCSection * DwarfLocDWOSection = nullptr
MCSection * DwarfStrOffDWOSection = nullptr
MCSection * DwarfMacinfoDWOSection = nullptr
MCSection * DwarfMacroDWOSection = nullptr
MCSection * DwarfStrOffSection = nullptr
The DWARF v5 string offset and address table sections.
MCSection * DwarfAddrSection = nullptr
MCSection * DwarfRnglistsSection = nullptr
The DWARF v5 range list section.
MCSection * DwarfLoclistsSection = nullptr
The DWARF v5 locations list section.
MCSection * DwarfRnglistsDWOSection = nullptr
The DWARF v5 range and location list sections for fission.
MCSection * DwarfLoclistsDWOSection = nullptr
MCSection * DwarfCUIndexSection = nullptr
MCSection * DwarfTUIndexSection = nullptr
MCSection * DwarfGnuPubNamesSection = nullptr
Section for newer gnu pubnames.
MCSection * DwarfGnuPubTypesSection = nullptr
Section for newer gnu pubtypes.
MCSection * DwarfSwiftASTSection = nullptr
MCSection * COFFDebugSymbolsSection = nullptr
MCSection * COFFDebugTypesSection = nullptr
MCSection * COFFGlobalTypeHashesSection = nullptr
MCSection * TLSExtraDataSection = nullptr
Extra TLS Variable Data section.
MCSection * TLSDataSection = nullptr
Section directive for Thread Local data. ELF, MachO, COFF, and Wasm.
MCSection * TLSBSSSection = nullptr
Section directive for Thread Local uninitialized data.
MCSection * StackMapSection = nullptr
StackMap section.
MCSection * FaultMapSection = nullptr
FaultMap section.
MCSection * RemarksSection = nullptr
Remarks section.
MCSection * EHFrameSection = nullptr
EH frame section.
MCSection * StackSizesSection = nullptr
Section containing metadata on function stack sizes.
MCSection * DataRelROSection = nullptr
MCSection * MergeableConst4Section = nullptr
MCSection * MergeableConst8Section = nullptr
MCSection * MergeableConst16Section = nullptr
MCSection * MergeableConst32Section = nullptr
MCSection * TLSTLVSection = nullptr
Section for thread local structure information.
const MCSection * TLSThreadInitSection = nullptr
Section for thread local data initialization functions.
MCSection * CStringSection = nullptr
MCSection * UStringSection = nullptr
MCSection * TextCoalSection = nullptr
MCSection * ConstTextCoalSection = nullptr
MCSection * ConstDataSection = nullptr
MCSection * DataCoalSection = nullptr
MCSection * ConstDataCoalSection = nullptr
MCSection * DataCommonSection = nullptr
MCSection * DataBSSSection = nullptr
MCSection * FourByteConstantSection = nullptr
MCSection * EightByteConstantSection = nullptr
MCSection * SixteenByteConstantSection = nullptr
MCSection * LazySymbolPointerSection = nullptr
MCSection * NonLazySymbolPointerSection = nullptr
MCSection * ThreadLocalPointerSection = nullptr
MCSection * DrectveSection = nullptr
COFF specific sections.
MCSection * PDataSection = nullptr
MCSection * XDataSection = nullptr
MCSection * SXDataSection = nullptr
MCSection * GFIDsSection = nullptr
MCSection * GLJMPSection = nullptr
MCSection * TOCBaseSection = nullptr
Detailed Description
Definition at line 215 of file TargetLoweringObjectFileImpl.h.
Constructor & Destructor Documentation
TargetLoweringObjectFileXCOFF()
llvm::TargetLoweringObjectFileXCOFF::TargetLoweringObjectFileXCOFF () default
~TargetLoweringObjectFileXCOFF()
llvm::TargetLoweringObjectFileXCOFF::~TargetLoweringObjectFileXCOFF () override default
Member Function Documentation
getExplicitSectionGlobal()
MCSection * TargetLoweringObjectFileXCOFF::getExplicitSectionGlobal (const GlobalObject * GO, SectionKind Kind, const TargetMachine & TM) const override virtual
Targets should implement this method to assign a section to globals with an explicit section specfied.
The implementation of this method can assume that GO->hasSection() is true.
Implements llvm::TargetLoweringObjectFile.
Definition at line 2007 of file TargetLoweringObjectFileImpl.cpp.
References llvm::report_fatal_error().
getFunctionEntryPointSymbol()
MCSymbol * TargetLoweringObjectFileXCOFF::getFunctionEntryPointSymbol (const Function * F, const TargetMachine & TM) const override virtual
If supported, return the function entry point symbol.
Otherwise, returns nulltpr.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 2151 of file TargetLoweringObjectFileImpl.cpp.
References F, llvm::MCObjectFileInfo::getContext(), llvm::TargetLoweringObjectFile::getNameWithPrefix(), and llvm::MCContext::getOrCreateSymbol().
getSectionForConstant()
MCSection * TargetLoweringObjectFileXCOFF::getSectionForConstant (const DataLayout & DL, SectionKind Kind, const Constant * C, Align & Alignment) const override virtual
Given a constant with the SectionKind, return a section that it should be placed in.
Given a mergeable constant with the specified size and relocation information, return a section that it should be placed in.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 2097 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCObjectFileInfo::ReadOnlySection.
getSectionForExternalReference()
MCSection * TargetLoweringObjectFileXCOFF::getSectionForExternalReference (const GlobalObject * GO, const TargetMachine & TM) const override virtual
For external functions, this will always return a function descriptor csect.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 2012 of file TargetLoweringObjectFileImpl.cpp.
References assert(), llvm::MCObjectFileInfo::getContext(), llvm::SectionKind::getMetadata(), llvm::TargetLoweringObjectFile::getNameWithPrefix(), getStorageClassForGlobal(), llvm::MCContext::getXCOFFSection(), llvm::GlobalValue::isDeclarationForLinker(), Name, llvm::XCOFF::XMC_DS, llvm::XCOFF::XMC_UA, and llvm::XCOFF::XTY_ER.
Referenced by getTargetSymbol().
getSectionForFunctionDescriptor()
MCSection * TargetLoweringObjectFileXCOFF::getSectionForFunctionDescriptor (const Function * F, const TargetMachine & TM) const override virtual
On targets that use separate function descriptor symbols, return a section for the descriptor given its symbol.
Use only with defined functions.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 2159 of file TargetLoweringObjectFileImpl.cpp.
References F, llvm::MCObjectFileInfo::getContext(), llvm::SectionKind::getData(), llvm::TargetLoweringObjectFile::getNameWithPrefix(), getStorageClassForGlobal(), llvm::MCContext::getXCOFFSection(), llvm::XCOFF::XMC_DS, and llvm::XCOFF::XTY_SD.
Referenced by getTargetSymbol().
getSectionForJumpTable()
MCSection * TargetLoweringObjectFileXCOFF::getSectionForJumpTable (const Function & F, const TargetMachine & TM) const override virtual
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 2081 of file TargetLoweringObjectFileImpl.cpp.
References assert(), F, and llvm::MCObjectFileInfo::ReadOnlySection.
getSectionForTOCEntry()
MCSection * TargetLoweringObjectFileXCOFF::getSectionForTOCEntry (const MCSymbol * S) const override virtual
On targets that support TOC entries, return a section for the entry given the symbol it refers to.
TODO: Implement this interface for existing ELF targets.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 2168 of file TargetLoweringObjectFileImpl.cpp.
References llvm::XCOFF::C_HIDEXT, llvm::MCObjectFileInfo::getContext(), llvm::SectionKind::getData(), llvm::MCContext::getXCOFFSection(), llvm::XCOFF::XMC_TC, and llvm::XCOFF::XTY_SD.
getStaticCtorSection()
MCSection * TargetLoweringObjectFileXCOFF::getStaticCtorSection (unsigned Priority, const MCSymbol * KeySym) const override virtual
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 2112 of file TargetLoweringObjectFileImpl.cpp.
References llvm::report_fatal_error().
getStaticDtorSection()
MCSection * TargetLoweringObjectFileXCOFF::getStaticDtorSection (unsigned Priority, const MCSymbol * KeySym) const override virtual
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 2117 of file TargetLoweringObjectFileImpl.cpp.
References llvm::report_fatal_error().
getStorageClassForGlobal()
XCOFF::StorageClass TargetLoweringObjectFileXCOFF::getStorageClassForGlobal (const GlobalObject * GO) static
Definition at line 2128 of file TargetLoweringObjectFileImpl.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::XCOFF::C_EXT, llvm::XCOFF::C_HIDEXT, llvm::XCOFF::C_WEAKEXT, llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::getLinkage(), llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm_unreachable, llvm::GlobalValue::PrivateLinkage, llvm::report_fatal_error(), llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
Referenced by getSectionForExternalReference(), getSectionForFunctionDescriptor(), SelectSectionForGlobal(), and transformCallee().
getTargetSymbol()
MCSymbol * TargetLoweringObjectFileXCOFF::getTargetSymbol (const GlobalValue * GV, const TargetMachine & TM) const override virtual
For functions, this will always return a function descriptor symbol.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 1974 of file TargetLoweringObjectFileImpl.cpp.
References llvm::TargetLoweringObjectFile::getKindForGlobal(), getSectionForExternalReference(), getSectionForFunctionDescriptor(), llvm::report_fatal_error(), and llvm::TargetLoweringObjectFile::SectionForGlobal().
Initialize()
void TargetLoweringObjectFileXCOFF::Initialize (MCContext & ctx, const TargetMachine & TM) override virtual
This method must be called before any actual lowering is done.
Initialize - this method must be called before any actual lowering is done.
This specifies the current context for codegen, and gives the lowering implementations a chance to set up their default sections.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 2104 of file TargetLoweringObjectFileImpl.cpp.
References llvm::TargetLoweringObjectFile::Initialize(), llvm::TargetLoweringObjectFile::LSDAEncoding, llvm::TargetLoweringObjectFile::PersonalityEncoding, and llvm::TargetLoweringObjectFile::TTypeEncoding.
lowerRelativeReference()
const MCExpr * TargetLoweringObjectFileXCOFF::lowerRelativeReference (const GlobalValue * LHS, const GlobalValue * RHS, const TargetMachine & TM) const override virtual
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 2122 of file TargetLoweringObjectFileImpl.cpp.
References llvm::report_fatal_error().
SelectSectionForGlobal()
MCSection * TargetLoweringObjectFileXCOFF::SelectSectionForGlobal (const GlobalObject * GO, SectionKind Kind, const TargetMachine & TM) const override virtual
Implements llvm::TargetLoweringObjectFile.
Definition at line 2028 of file TargetLoweringObjectFileImpl.cpp.
References assert(), llvm::MCObjectFileInfo::DataSection, llvm::MCObjectFileInfo::getContext(), llvm::Module::getDataLayout(), getEntrySizeForKind(), llvm::TargetLoweringObjectFile::getNameWithPrefix(), llvm::GlobalValue::getParent(), llvm::DataLayout::getPreferredAlign(), getStorageClassForGlobal(), llvm::MCContext::getXCOFFSection(), Name, llvm::MCObjectFileInfo::ReadOnlySection, llvm::report_fatal_error(), llvm::MCObjectFileInfo::TextSection, llvm::utostr(), llvm::Align::value(), llvm::XCOFF::XMC_BS, llvm::XCOFF::XMC_RO, llvm::XCOFF::XMC_RW, llvm::XCOFF::XTY_CM, and llvm::XCOFF::XTY_SD.
shouldPutJumpTableInFunctionSection()
bool TargetLoweringObjectFileXCOFF::shouldPutJumpTableInFunctionSection (bool UsesLabelDifference, const Function & F) const override virtual
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 2090 of file TargetLoweringObjectFileImpl.cpp.
The documentation for this class was generated from the following files:
include/llvm/CodeGen/TargetLoweringObjectFileImpl.h
lib/CodeGen/TargetLoweringObjectFileImpl.cpp