LLVM: llvm::TargetFolder Class Reference
llvm::TargetFolder Class Reference final
TargetFolder - Create constants with target dependent folding.
#include "llvm/Analysis/TargetFolder.h"
Public Member Functions
TargetFolder (const DataLayout &DL)
Constant * CreateAdd (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Constant * CreateFAdd (Constant *LHS, Constant *RHS) const override
Constant * CreateSub (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Constant * CreateFSub (Constant *LHS, Constant *RHS) const override
Constant * CreateMul (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Constant * CreateFMul (Constant *LHS, Constant *RHS) const override
Constant * CreateUDiv (Constant *LHS, Constant *RHS, bool isExact=false) const override
Constant * CreateSDiv (Constant *LHS, Constant *RHS, bool isExact=false) const override
Constant * CreateFDiv (Constant *LHS, Constant *RHS) const override
Constant * CreateURem (Constant *LHS, Constant *RHS) const override
Constant * CreateSRem (Constant *LHS, Constant *RHS) const override
Constant * CreateFRem (Constant *LHS, Constant *RHS) const override
Constant * CreateShl (Constant *LHS, Constant *RHS, bool HasNUW=false, bool HasNSW=false) const override
Constant * CreateLShr (Constant *LHS, Constant *RHS, bool isExact=false) const override
Constant * CreateAShr (Constant *LHS, Constant *RHS, bool isExact=false) const override
Constant * CreateAnd (Constant *LHS, Constant *RHS) const override
Constant * CreateOr (Constant *LHS, Constant *RHS) const override
Constant * CreateXor (Constant *LHS, Constant *RHS) const override
Constant * CreateBinOp (Instruction::BinaryOps Opc, Constant *LHS, Constant *RHS) const override
Constant * CreateNeg (Constant *C, bool HasNUW=false, bool HasNSW=false) const override
Constant * CreateFNeg (Constant *C) const override
Constant * CreateNot (Constant *C) const override
Constant * CreateUnOp (Instruction::UnaryOps Opc, Constant *C) const override
Constant * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList) const override
Constant * CreateGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const override
Constant * CreateGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList) const override
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Constant * > IdxList) const override
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, Constant *Idx) const override
Constant * CreateInBoundsGetElementPtr (Type *Ty, Constant *C, ArrayRef< Value * > IdxList) const override
Constant * CreateCast (Instruction::CastOps Op, Constant *C, Type *DestTy) const override
Constant * CreateIntCast (Constant *C, Type *DestTy, bool isSigned) const override
Constant * CreatePointerCast (Constant *C, Type *DestTy) const override
Constant * CreateFPCast (Constant *C, Type *DestTy) const override
Constant * CreateBitCast (Constant *C, Type *DestTy) const override
Constant * CreateIntToPtr (Constant *C, Type *DestTy) const override
Constant * CreatePtrToInt (Constant *C, Type *DestTy) const override
Constant * CreateZExtOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreateSExtOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreateTruncOrBitCast (Constant *C, Type *DestTy) const override
Constant * CreatePointerBitCastOrAddrSpaceCast (Constant *C, Type *DestTy) const override
Constant * CreateICmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const override
Constant * CreateFCmp (CmpInst::Predicate P, Constant *LHS, Constant *RHS) const override
Constant * CreateSelect (Constant *C, Constant *True, Constant *False) const override
Constant * CreateExtractElement (Constant *Vec, Constant *Idx) const override
Constant * CreateInsertElement (Constant *Vec, Constant *NewElt, Constant *Idx) const override
Constant * CreateShuffleVector (Constant *V1, Constant *V2, ArrayRef< int > Mask) const override
Constant * CreateExtractValue (Constant *Agg, ArrayRef< unsigned > IdxList) const override
Constant * CreateInsertValue (Constant *Agg, Constant *Val, ArrayRef< unsigned > IdxList) const override
Public Member Functions inherited from llvm::IRBuilderFolder
virtual ~IRBuilderFolder ()
Detailed Description
TargetFolder - Create constants with target dependent folding.
Definition at line 32 of file TargetFolder.h.
Constructor & Destructor Documentation
TargetFolder()
llvm::TargetFolder::TargetFolder (const DataLayout & DL) inline explicit
Definition at line 43 of file TargetFolder.h.
References DL.
Member Function Documentation
CreateAdd()
Constant * llvm::TargetFolder::CreateAdd (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 49 of file TargetFolder.h.
References llvm::ConstantExpr::getAdd().
CreateAnd()
Constant * llvm::TargetFolder::CreateAnd (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 102 of file TargetFolder.h.
References llvm::ConstantExpr::getAnd().
CreateAShr()
Constant * llvm::TargetFolder::CreateAShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 98 of file TargetFolder.h.
References llvm::ConstantExpr::getAShr().
CreateBinOp()
Constant * llvm::TargetFolder::CreateBinOp (Instruction::BinaryOps Opc, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 112 of file TargetFolder.h.
References llvm::ConstantExpr::get().
CreateBitCast()
Constant * llvm::TargetFolder::CreateBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 198 of file TargetFolder.h.
References C, CreateCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
CreateCast()
Constant * llvm::TargetFolder::CreateCast (Instruction::CastOps Op, Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 176 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getCast().
Referenced by CreateBitCast(), CreateIntToPtr(), and CreatePtrToInt().
CreateExtractElement()
Constant * llvm::TargetFolder::CreateExtractElement (Constant * Vec, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 252 of file TargetFolder.h.
References llvm::ConstantExpr::getExtractElement(), and Idx.
CreateExtractValue()
Constant * llvm::TargetFolder::CreateExtractValue (Constant * Agg, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 266 of file TargetFolder.h.
References llvm::ConstantExpr::getExtractValue().
CreateFAdd()
Constant * llvm::TargetFolder::CreateFAdd (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 53 of file TargetFolder.h.
References llvm::ConstantExpr::getFAdd().
CreateFCmp()
Constant * llvm::TargetFolder::CreateFCmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 238 of file TargetFolder.h.
References llvm::ConstantExpr::getCompare(), and P.
CreateFDiv()
Constant * llvm::TargetFolder::CreateFDiv (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 78 of file TargetFolder.h.
References llvm::ConstantExpr::getFDiv().
CreateFMul()
Constant * llvm::TargetFolder::CreateFMul (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 67 of file TargetFolder.h.
References llvm::ConstantExpr::getFMul().
CreateFNeg()
Constant * llvm::TargetFolder::CreateFNeg (Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 125 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getFNeg().
CreateFPCast()
Constant * llvm::TargetFolder::CreateFPCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 193 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getFPCast().
CreateFRem()
Constant * llvm::TargetFolder::CreateFRem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 87 of file TargetFolder.h.
References llvm::ConstantExpr::getFRem().
CreateFSub()
Constant * llvm::TargetFolder::CreateFSub (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 60 of file TargetFolder.h.
References llvm::ConstantExpr::getFSub().
CreateGetElementPtr() [1/3]
Constant * llvm::TargetFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 140 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getGetElementPtr().
CreateGetElementPtr() [2/3]
Constant * llvm::TargetFolder::CreateGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 151 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getGetElementPtr().
CreateGetElementPtr() [3/3]
Constant * llvm::TargetFolder::CreateGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 144 of file TargetFolder.h.
References C, llvm::ConstantExpr::getGetElementPtr(), and Idx.
CreateICmp()
Constant * llvm::TargetFolder::CreateICmp (CmpInst::Predicate P, Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 234 of file TargetFolder.h.
References llvm::ConstantExpr::getCompare(), and P.
CreateInBoundsGetElementPtr() [1/3]
Constant * llvm::TargetFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Constant * > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 156 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getInBoundsGetElementPtr().
CreateInBoundsGetElementPtr() [2/3]
Constant * llvm::TargetFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, ArrayRef< Value * > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 167 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getInBoundsGetElementPtr().
CreateInBoundsGetElementPtr() [3/3]
Constant * llvm::TargetFolder::CreateInBoundsGetElementPtr (Type * Ty, Constant * C, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 160 of file TargetFolder.h.
References C, llvm::ConstantExpr::getInBoundsGetElementPtr(), and Idx.
CreateInsertElement()
Constant * llvm::TargetFolder::CreateInsertElement (Constant * Vec, Constant * NewElt, Constant * Idx) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 256 of file TargetFolder.h.
References llvm::ConstantExpr::getInsertElement(), and Idx.
CreateInsertValue()
Constant * llvm::TargetFolder::CreateInsertValue (Constant * Agg, Constant * Val, ArrayRef< unsigned > IdxList) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 271 of file TargetFolder.h.
References llvm::ConstantExpr::getInsertValue().
CreateIntCast()
Constant * llvm::TargetFolder::CreateIntCast (Constant * C, Type * DestTy, bool isSigned) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 182 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getIntegerCast().
CreateIntToPtr()
Constant * llvm::TargetFolder::CreateIntToPtr (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 201 of file TargetFolder.h.
References C, CreateCast(), and llvm::ilist_node_impl< ilist_detail::compute_node_options< T, Options... >::type >::ilist_node_impl().
CreateLShr()
Constant * llvm::TargetFolder::CreateLShr (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 94 of file TargetFolder.h.
References llvm::ConstantExpr::getLShr().
CreateMul()
Constant * llvm::TargetFolder::CreateMul (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 63 of file TargetFolder.h.
References llvm::ConstantExpr::getMul().
CreateNeg()
Constant * llvm::TargetFolder::CreateNeg (Constant * C, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 121 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getNeg().
CreateNot()
Constant * llvm::TargetFolder::CreateNot (Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 128 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getNot().
CreateOr()
Constant * llvm::TargetFolder::CreateOr (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 105 of file TargetFolder.h.
References llvm::ConstantExpr::getOr().
CreatePointerBitCastOrAddrSpaceCast()
Constant * llvm::TargetFolder::CreatePointerBitCastOrAddrSpaceCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 223 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast().
CreatePointerCast()
Constant * llvm::TargetFolder::CreatePointerCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 188 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getPointerCast().
CreatePtrToInt()
Constant * llvm::TargetFolder::CreatePtrToInt (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 204 of file TargetFolder.h.
References C, and CreateCast().
CreateSDiv()
Constant * llvm::TargetFolder::CreateSDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 74 of file TargetFolder.h.
References llvm::ConstantExpr::getSDiv().
CreateSelect()
Constant * llvm::TargetFolder::CreateSelect (Constant * C, Constant * True, Constant * False) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 247 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getSelect().
CreateSExtOrBitCast()
Constant * llvm::TargetFolder::CreateSExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 212 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getSExtOrBitCast().
CreateShl()
Constant * llvm::TargetFolder::CreateShl (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 90 of file TargetFolder.h.
References llvm::ConstantExpr::getShl().
CreateShuffleVector()
Constant * llvm::TargetFolder::CreateShuffleVector (Constant * V1, Constant * V2, ArrayRef< int > Mask) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 261 of file TargetFolder.h.
References llvm::ConstantExpr::getShuffleVector().
CreateSRem()
Constant * llvm::TargetFolder::CreateSRem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 84 of file TargetFolder.h.
References llvm::ConstantExpr::getSRem().
CreateSub()
Constant * llvm::TargetFolder::CreateSub (Constant * LHS, Constant * RHS, bool HasNUW = false, bool HasNSW = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 56 of file TargetFolder.h.
References llvm::ConstantExpr::getSub().
CreateTruncOrBitCast()
Constant * llvm::TargetFolder::CreateTruncOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 217 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getTruncOrBitCast().
CreateUDiv()
Constant * llvm::TargetFolder::CreateUDiv (Constant * LHS, Constant * RHS, bool isExact = false) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 70 of file TargetFolder.h.
References llvm::ConstantExpr::getUDiv().
CreateUnOp()
Constant * llvm::TargetFolder::CreateUnOp (Instruction::UnaryOps Opc, Constant * C) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 132 of file TargetFolder.h.
References C, and llvm::ConstantExpr::get().
CreateURem()
Constant * llvm::TargetFolder::CreateURem (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 81 of file TargetFolder.h.
References llvm::ConstantExpr::getURem().
CreateXor()
Constant * llvm::TargetFolder::CreateXor (Constant * LHS, Constant * RHS) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 108 of file TargetFolder.h.
References llvm::ConstantExpr::getXor().
CreateZExtOrBitCast()
Constant * llvm::TargetFolder::CreateZExtOrBitCast (Constant * C, Type * DestTy) const inline override virtual
Implements llvm::IRBuilderFolder.
Definition at line 207 of file TargetFolder.h.
References C, and llvm::ConstantExpr::getZExtOrBitCast().
The documentation for this class was generated from the following files:
include/llvm/Analysis/TargetFolder.h
lib/Analysis/ConstantFolding.cpp