LLVM: llvm::MDGlobalAttachmentMap Class Reference
llvm::MDGlobalAttachmentMap Class Reference
Multimap-like storage for metadata attachments for globals.
#include "IR/LLVMContextImpl.h"
Public Member Functions
bool empty () const
void get (unsigned ID, SmallVectorImpl< MDNode * > &Result) const
Appends all attachments with the given ID to Result in insertion order.
MDNode * lookup (unsigned ID) const
Returns the first attachment with the given ID or nullptr if no such attachment exists.
void insert (unsigned ID, MDNode &MD)
bool erase (unsigned ID)
void getAll (SmallVectorImpl< std::pair< unsigned, MDNode * > > &Result) const
Appends all attachments for the global to Result, sorting by attachment ID.
Detailed Description
Multimap-like storage for metadata attachments for globals.
This differs from MDAttachmentMap in that it allows multiple attachments per metadata kind.
Definition at line 1247 of file LLVMContextImpl.h.
Member Function Documentation
empty()
bool llvm::MDGlobalAttachmentMap::empty () const inline
Definition at line 1255 of file LLVMContextImpl.h.
erase()
bool MDGlobalAttachmentMap::erase (unsigned ID)
Definition at line 1169 of file Metadata.cpp.
References A, llvm::SmallVectorTemplateCommon< T, typename >::begin(), Changed, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), and I.
get()
void MDGlobalAttachmentMap::get (unsigned ID, SmallVectorImpl< MDNode * > & Result) const
Appends all attachments with the given ID to Result in insertion order.
If the global has no attachments with the given ID, or if ID is invalid, leaves Result unchanged.
Definition at line 1162 of file Metadata.cpp.
References A.
getAll()
void MDGlobalAttachmentMap::getAll (SmallVectorImpl< std::pair< unsigned, MDNode * > > & Result) const
Appends all attachments for the global to Result, sorting by attachment ID.
Attachments with the same ID appear in insertion order. This function does not clear Result.
Definition at line 1177 of file Metadata.cpp.
References A, and llvm::stable_sort().
insert()
void MDGlobalAttachmentMap::insert (unsigned ID, MDNode & MD)
Definition at line 1151 of file Metadata.cpp.
References llvm::SmallVectorTemplateBase< T, bool >::push_back().
lookup()
MDNode * MDGlobalAttachmentMap::lookup (unsigned ID) const
Returns the first attachment with the given ID or nullptr if no such attachment exists.
Definition at line 1155 of file Metadata.cpp.
References A.
The documentation for this class was generated from the following files:
lib/IR/LLVMContextImpl.h
lib/IR/Metadata.cpp