LLVM: lib/Support/DataExtractor.cpp File Reference
DataExtractor.cpp File Reference
#include "llvm/Support/DataExtractor.h"
#include "llvm/Support/Errc.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/LEB128.h"
#include "llvm/Support/SwapByteOrder.h"
Functions
static bool isError (Error *E)
template<typename T >
static T getLEB128 (StringRef Data, uint64_t *OffsetPtr, Error *Err, T(&Decoder)(const uint8_t *p, unsigned *n, const uint8_t *end, const char **error))
Function Documentation
getLEB128()
template<typename T > static T getLEB128 (StringRef Data, uint64_t * OffsetPtr, Error * Err, T(&)(const uint8_t *p, unsigned *n, const uint8_t *end, const char **error) Decoder) static
Definition at line 196 of file DataExtractor.cpp.
References llvm::arrayRefFromStringRef(), assert(), llvm::createStringError(), llvm::Data, error, llvm::illegal_byte_sequence, isError(), and T.
Referenced by llvm::DataExtractor::getSLEB128(), and llvm::DataExtractor::getULEB128().
isError()
static bool isError (Error * E) static
Definition at line 38 of file DataExtractor.cpp.
References E.
Referenced by llvm::DataExtractor::getBytes(), llvm::DataExtractor::getCStrRef(), getLEB128(), and llvm::DataExtractor::skip().