LLVM: lib/Support/FileUtilities.cpp File Reference
FileUtilities.cpp File Reference
#include "llvm/Support/FileUtilities.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/ErrorOr.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <cctype>
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <system_error>
Functions
static bool isSignedChar (char C)
static bool isExponentChar (char C)
static bool isNumberChar (char C)
static const char * BackupNumber (const char *Pos, const char *FirstChar)
static const char * EndOfNumber (const char *Pos)
EndOfNumber - Return the first character that is not part of the specified number.
static bool CompareNumbers (const char *&F1P, const char *&F2P, const char *F1End, const char *F2End, double AbsTolerance, double RelTolerance, std::string *ErrorMsg)
CompareNumbers - compare two numbers, returning true if they are different.
Function Documentation
BackupNumber()
static const char * BackupNumber (const char * Pos, const char * FirstChar) static
Definition at line 56 of file FileUtilities.cpp.
References isExponentChar(), isNumberChar(), and isSignedChar().
Referenced by llvm::DiffFilesWithTolerance().
CompareNumbers()
static bool CompareNumbers (const char *& F1P, const char *& F2P, const char * F1End, const char * F2End, double AbsTolerance, double RelTolerance, std::string * ErrorMsg) static
CompareNumbers - compare two numbers, returning true if they are different.
Definition at line 87 of file FileUtilities.cpp.
References EndOfNumber(), isNumberChar(), and llvm::isSpace().
Referenced by llvm::DiffFilesWithTolerance().
EndOfNumber()
static const char * EndOfNumber (const char * Pos) static
EndOfNumber - Return the first character that is not part of the specified number.
This assumes that the buffer is null terminated, so it won't fall off the end.
Definition at line 80 of file FileUtilities.cpp.
References isNumberChar().
Referenced by CompareNumbers().
isExponentChar()
static bool isExponentChar (char C) static
Definition at line 37 of file FileUtilities.cpp.
References C.
Referenced by BackupNumber(), and isNumberChar().
isNumberChar()
static bool isNumberChar (char C) static
Definition at line 47 of file FileUtilities.cpp.
References C, isExponentChar(), and isSignedChar().
Referenced by BackupNumber(), CompareNumbers(), llvm::DiffFilesWithTolerance(), and EndOfNumber().
isSignedChar()
static bool isSignedChar (char C) static
Definition at line 33 of file FileUtilities.cpp.
References C.
Referenced by BackupNumber(), and isNumberChar().