LLVM: include/llvm/Support/GraphWriter.h File Reference
GraphWriter.h File Reference
#include "llvm/ADT/GraphTraits.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/DOTGraphTraits.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cstddef>
#include <iterator>
#include <string>
#include <type_traits>
#include <vector>
Classes
class llvm::GraphWriter< GraphType >
Namespaces
namespace llvm
This class represents lattice values for constants.
namespace llvm::DOT
namespace llvm::GraphProgram
Enumerations
enum llvm::GraphProgram::Name {
llvm::GraphProgram::DOT , llvm::GraphProgram::FDP , llvm::GraphProgram::NEATO , llvm::GraphProgram::TWOPI ,
llvm::GraphProgram::CIRCO
}
Functions
std::string llvm::DOT::EscapeString (const std::string &Label)
StringRef llvm::DOT::getColorString (unsigned NodeNumber)
Get a color string for this node number.
bool llvm::DisplayGraph (StringRef Filename, bool wait=true, GraphProgram::Name program=GraphProgram::DOT)
template<typename GraphType >
raw_ostream & llvm::WriteGraph (raw_ostream &O, const GraphType &G, bool ShortNames=false, const Twine &Title="")
std::string llvm::createGraphFilename (const Twine &Name, int &FD)
template<typename GraphType >
*DumpDotGraph Just dump a dot graph to the user provided file name LLVM_DUMP_METHOD void dumpDotGraphToFile (const GraphType &G, const Twine &FileName, const Twine &Title, bool ShortNames=false, const Twine &Name="")
template<typename GraphType >
*ViewGraph Emit a dot run run gv on the postscript *then cleanup For use from the debugger *void ViewGraph (const GraphType &G, const Twine &Name, bool ShortNames=false, const Twine &Title="", GraphProgram::Name Program=GraphProgram::DOT)
Variables
*ViewGraph Emit a dot graph
*ViewGraph Emit a dot run dot
*ViewGraph Emit a dot run run gv on the postscript file
Function Documentation
dumpDotGraphToFile()
template<typename GraphType > *DumpDotGraph Just dump a dot graph to the user provided file name LLVM_DUMP_METHOD void dumpDotGraphToFile (const GraphType & G, const Twine & FileName, const Twine & Title, bool ShortNames = false, const Twine & Name = "")
Definition at line 365 of file GraphWriter.h.
References G, Name, and llvm::WriteGraph().
Referenced by llvm::SelectionDAG::dumpDotGraph().
ViewGraph()
template<typename GraphType > *ViewGraph Emit a dot run run gv on the postscript *then cleanup For use from the debugger *void ViewGraph (const GraphType & G, const Twine & Name, bool ShortNames = false, const Twine & Title = "", GraphProgram::Name Program = GraphProgram::DOT)
Definition at line 376 of file GraphWriter.h.
References llvm::DisplayGraph(), G, Name, and llvm::WriteGraph().
Referenced by annotateAllFunctions(), llvm::slpvectorizer::BoUpSLP::getTreeCost(), llvm::DOTGraphTraitsViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnFunction(), llvm::DOTGraphTraitsModuleViewer< AnalysisT, IsSimple, GraphT, AnalysisGraphTraitsT >::runOnModule(), llvm::EdgeBundles::view(), llvm::MachineBlockFrequencyInfo::view(), llvm::BlockFrequencyInfo::view(), llvm::MachineFunction::viewCFG(), llvm::Function::viewCFG(), viewCFG(), llvm::MachineFunction::viewCFGOnly(), llvm::SelectionDAG::viewGraph(), llvm::ScheduleDAG::viewGraph(), llvm::DominatorTree::viewGraph(), and llvm::ScheduleDAGMI::viewGraph().
Variable Documentation
dot
* ViewGraph Emit a dot run dot
Definition at line 372 of file GraphWriter.h.
Referenced by llvm::interpretDecimal(), and llvm::skipLeadingZeroesAndAnyDot().
file
* ViewGraph Emit a dot run run gv on the postscript file
Definition at line 372 of file GraphWriter.h.
Referenced by llvm::llvm_unreachable_internal(), and llvm::FileInfo::print().
graph
* ViewGraph Emit a dot graph
Definition at line 372 of file GraphWriter.h.