LLVM: query interface.
query interface.
Functions
Function * llvm::VFDatabase::getVectorizedFunction (const VFShape &Shape) const
Detailed Description
Retrieve the Function with VFShape Shape.
Function Documentation
getVectorizedFunction()
Function * llvm::VFDatabase::getVectorizedFunction (const VFShape & Shape) const inline
Definition at line 274 of file VectorUtils.h.
References llvm::CallBase::getCalledFunction(), llvm::Function::getFunction(), and llvm::VFShape::getScalarShape().
Referenced by llvm::LoopVectorizationCostModel::getVectorCallCost(), getVectorCallCosts(), and llvm::InnerLoopVectorizer::widenCallInstruction().