LLVM: include/llvm-c/Support.h File Reference
Support.h File Reference
#include "llvm-c/DataTypes.h"
#include "llvm-c/ExternC.h"
#include "llvm-c/Types.h"
Functions
LLVM_C_EXTERN_C_BEGIN LLVMBool LLVMLoadLibraryPermanently (const char *Filename)
This function permanently loads the dynamic library at the given path.
void LLVMParseCommandLineOptions (int argc, const char *const *argv, const char *Overview)
This function parses the given arguments using the LLVM command line parser.
void * LLVMSearchForAddressOfSymbol (const char *symbolName)
This function will search through all previously loaded dynamic libraries for the symbol symbolName.
void LLVMAddSymbol (const char *symbolName, void *symbolValue)
This functions permanently adds the symbol symbolName with the value symbolValue.
Function Documentation
LLVMAddSymbol()
void LLVMAddSymbol (const char * symbolName, void * symbolValue)
This functions permanently adds the symbol symbolName with the value symbolValue.
These symbols are searched before any libraries.
See also
sys::DynamicLibrary::AddSymbol()
Definition at line 213 of file DynamicLibrary.cpp.
References llvm::sys::DynamicLibrary::AddSymbol().
LLVMLoadLibraryPermanently()
LLVM_C_EXTERN_C_BEGIN LLVMBool LLVMLoadLibraryPermanently (const char * Filename)
This function permanently loads the dynamic library at the given path.
It is safe to call this function multiple times for the same library.
See also
sys::DynamicLibrary::LoadLibraryPermanently()
Definition at line 205 of file DynamicLibrary.cpp.
References llvm::sys::DynamicLibrary::LoadLibraryPermanently().
LLVMParseCommandLineOptions()
void LLVMParseCommandLineOptions (int argc, const char *const * argv, const char * Overview)
This function parses the given arguments using the LLVM command line parser.
Note that the only stable thing about this function is its signature; you cannot rely on any particular set of command line arguments being interpreted the same way across LLVM versions.
See also
llvm::cl::ParseCommandLineOptions()
Definition at line 2618 of file CommandLine.cpp.
References llvm::nulls(), and llvm::cl::ParseCommandLineOptions().
LLVMSearchForAddressOfSymbol()
void * LLVMSearchForAddressOfSymbol (const char * symbolName)
This function will search through all previously loaded dynamic libraries for the symbol symbolName.
If it is found, the address of that symbol is returned. If not, null is returned.
See also
sys::DynamicLibrary::SearchForAddressOfSymbol()
Definition at line 209 of file DynamicLibrary.cpp.
References llvm::sys::DynamicLibrary::SearchForAddressOfSymbol().