LLVM: lib/CodeGen/MIRPrinter.cpp File Reference
MIRPrinter.cpp File Reference
#include "llvm/CodeGen/MIRPrinter.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/None.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallBitVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/CodeGen/GlobalISel/RegisterBank.h"
#include "llvm/CodeGen/MIRYamlMapping.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/PseudoSourceValue.h"
#include "llvm/CodeGen/TargetInstrInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/CodeGen/TargetFrameLowering.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DebugInfo.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/IRPrintingPasses.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ModuleSlotTracker.h"
#include "llvm/IR/Value.h"
#include "llvm/MC/LaneBitmask.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/AtomicOrdering.h"
#include "llvm/Support/BranchProbability.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/LowLevelTypeImpl.h"
#include "llvm/Support/YAMLTraits.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetIntrinsicInfo.h"
#include "llvm/Target/TargetMachine.h"
#include <algorithm>
#include <cassert>
#include <cinttypes>
#include <cstdint>
#include <iterator>
#include <string>
#include <utility>
#include <vector>
Classes
class llvm::MIRPrinter
This class prints out the machine functions using the MIR serialization format.
class llvm::MIPrinter
This class prints out the machine instructions using the MIR serialization format.
struct llvm::yaml::BlockScalarTraits< Module >
This struct serializes the LLVM IR module.
Namespaces
namespace llvm
This class represents lattice values for constants.
namespace llvm::yaml
Functions
static void printRegMIR (unsigned Reg, yaml::StringValue &Dest, const TargetRegisterInfo *TRI)
static void printCustomRegMask (const uint32_t *RegMask, raw_ostream &OS, const TargetRegisterInfo *TRI)
static void printRegClassOrBank (unsigned Reg, yaml::StringValue &Dest, const MachineRegisterInfo &RegInfo, const TargetRegisterInfo *TRI)
template<typename T >
static void printStackObjectDbgInfo (const MachineFunction::VariableDbgInfo &DebugVar, T &Object, ModuleSlotTracker &MST)
static std::string formatOperandComment (std::string Comment)
Variables
static cl::opt< bool > SimplifyMIR ("simplify-mir", cl::Hidden, cl::desc("Leave out unnecessary information when printing MIR"))
static cl::opt< bool > PrintLocations ("mir-debug-loc", cl::Hidden, cl::init(true), cl::desc("Print MIR debug-locations"))
Function Documentation
formatOperandComment()
static std::string formatOperandComment (std::string Comment) static
Definition at line 853 of file MIRPrinter.cpp.
Referenced by llvm::MIPrinter::print().
printCustomRegMask()
static void printCustomRegMask (const uint32_t * RegMask, raw_ostream & OS, const TargetRegisterInfo * TRI) static
Definition at line 248 of file MIRPrinter.cpp.
References assert(), E, I, llvm::printReg(), and TRI.
Referenced by llvm::MIPrinter::print().
printRegClassOrBank()
static void printRegClassOrBank (unsigned Reg, yaml::StringValue & Dest, const MachineRegisterInfo & RegInfo, const TargetRegisterInfo * TRI) static
Definition at line 267 of file MIRPrinter.cpp.
References llvm::printRegClassOrBank(), TRI, and llvm::yaml::StringValue::Value.
printRegMIR()
static void printRegMIR (unsigned Reg, yaml::StringValue & Dest, const TargetRegisterInfo * TRI) static
Definition at line 193 of file MIRPrinter.cpp.
References llvm::printReg(), TRI, and llvm::yaml::StringValue::Value.
Referenced by llvm::MIRPrinter::convert(), llvm::MIRPrinter::convertCallSiteObjects(), and llvm::MIRPrinter::convertStackObjects().
printStackObjectDbgInfo()
template<typename T > static void printStackObjectDbgInfo (const MachineFunction::VariableDbgInfo & DebugVar, T & Object, ModuleSlotTracker & MST) static
Definition at line 276 of file MIRPrinter.cpp.
References llvm::MachineFunction::VariableDbgInfo::Expr, llvm::MachineFunction::VariableDbgInfo::Loc, llvm::Object, and llvm::MachineFunction::VariableDbgInfo::Var.
Referenced by llvm::MIRPrinter::convertStackObjects().
Variable Documentation
PrintLocations
cl::opt< bool > PrintLocations("mir-debug-loc", cl::Hidden, cl::init(true), cl::desc("Print MIR debug-locations")) ("mir-debug-loc" , cl::Hidden , cl::init(true) , cl::desc("Print MIR debug-locations")) static
Referenced by llvm::MIPrinter::print().
SimplifyMIR
cl::opt< bool > SimplifyMIR("simplify-mir", cl::Hidden, cl::desc("Leave out unnecessary information when printing MIR")) ("simplify-mir" , cl::Hidden , cl::desc("Leave out unnecessary information when printing MIR")) static
Referenced by llvm::MIPrinter::print(), and llvm::MIRPrinter::print().