LLVM: lib/Target/ARM/MVETailPredication.cpp File Reference
MVETailPredication.cpp File Reference
Armv8.1m introduced MVE, M-Profile Vector Extension, and low-overhead branches to help accelerate DSP applications.
#include "ARM.h"
#include "ARMSubtarget.h"
#include "ARMTargetTransformInfo.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/TargetLibraryInfo.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/CodeGen/TargetPassConfig.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicsARM.h"
#include "llvm/IR/PatternMatch.h"
#include "llvm/InitializePasses.h"
#include "llvm/Support/Debug.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
#include "llvm/Transforms/Utils/ScalarEvolutionExpander.h"
Macros
#define DEBUG_TYPE "mve-tail-predication"
#define DESC "Transform predicated vector loops to use MVE tail predication"
Functions
static bool IsDecrement (Instruction &I)
static bool IsMasked (Instruction *I)
static FixedVectorType * getVectorType (IntrinsicInst *I)
static void Cleanup (SetVector< Instruction * > &MaybeDead, Loop *L)
static Value * getNumElements (BasicBlock *Preheader, Value *BTC)
Variables
cl::opt< TailPredication::Mode > EnableTailPredication ("tail-predication", cl::desc("MVE tail-predication options"), cl::init(TailPredication::Disabled), cl::values(clEnumValN(TailPredication::Disabled, "disabled", "Don't tail-predicate loops"), clEnumValN(TailPredication::EnabledNoReductions, "enabled-no-reductions", "Enable tail-predication, but not for reduction loops"), clEnumValN(TailPredication::Enabled, "enabled", "Enable tail-predication, including reduction loops"), clEnumValN(TailPredication::ForceEnabledNoReductions, "force-enabled-no-reductions", "Enable tail-predication, but not for reduction loops, " "and force this which might be unsafe"), clEnumValN(TailPredication::ForceEnabled, "force-enabled", "Enable tail-predication, including reduction loops, " "and force this which might be unsafe")))
Detailed Description
Armv8.1m introduced MVE, M-Profile Vector Extension, and low-overhead branches to help accelerate DSP applications.
These two extensions, combined with a new form of predication called tail-predication, can be used to provide implicit vector predication within a low-overhead loop. This is implicit because the predicate of active/inactive lanes is calculated by hardware, and thus does not need to be explicitly passed to vector instructions. The instructions responsible for this are the DLSTP and WLSTP instructions, which setup a tail-predicated loop and the the total number of data elements processed by the loop. The loop-end LETP instruction is responsible for decrementing and setting the remaining elements to be processed and generating the mask of active lanes.
The HardwareLoops pass inserts intrinsics identifying loops that the backend will attempt to convert into a low-overhead loop. The vectorizer is responsible for generating a vectorized loop in which the lanes are predicated upon the iteration counter. This pass looks at these predicated vector loops, that are targets for low-overhead loops, and prepares it for code generation. Once the vectorizer has produced a masked loop, there's a couple of final forms:
A tail-predicated loop, with implicit predication.
A loop containing multiple VCPT instructions, predicating multiple VPT blocks of instructions operating on different vector types.
This pass: 1) Checks if the predicates of the masked load/store instructions are generated by intrinsic @llvm.get.active.lanes(). This intrinsic consumes the Backedge Taken Count (BTC) of the scalar loop as its second argument, which we extract to set up the number of elements processed by the loop. 2) Intrinsic @llvm.get.active.lanes() is then replaced by the MVE target specific VCTP intrinsic to represent the effect of tail predication. This will be picked up by the ARM Low-overhead loop pass, which performs the final transformation to a DLSTP or WLSTP tail-predicated loop.
Definition in file MVETailPredication.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "mve-tail-predication"
Definition at line 65 of file MVETailPredication.cpp.
DESC
#define DESC "Transform predicated vector loops to use MVE tail predication"
Definition at line 66 of file MVETailPredication.cpp.
Function Documentation
Cleanup()
static void Cleanup (SetVector< Instruction * > & MaybeDead, Loop * L) static
Definition at line 311 of file MVETailPredication.cpp.
References llvm::LoopBase< BlockT, LoopT >::blocks(), llvm::dbgs(), llvm::DeleteDeadPHIs(), llvm::LoopBase< BlockT, LoopT >::getUniqueExitBlock(), I, and LLVM_DEBUG.
Referenced by llvm::MachineFunction::addSEHCleanupHandler(), llvm::calculateClrEHStateNumbers(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitPrologue(), and llvm::formDedicatedExitBlocks().
getNumElements()
static Value * getNumElements (BasicBlock * Preheader, Value * BTC) static
Definition at line 489 of file MVETailPredication.cpp.
References Builder, llvm::dbgs(), llvm::ConstantInt::get(), llvm::BasicBlock::getTerminator(), I, and LLVM_DEBUG.
Referenced by llvm::MachineIRBuilder::buildInstr(), llvm::MachineIRBuilder::buildSplatVector(), CreateGCRelocates(), llvm::EmitGEPOffset(), EvaluateStoreInto(), extractVector(), foldBitCastSelect(), llvm::BasicTTIImplBase< T >::getCastInstrCost(), getLogBase2(), llvm::AArch64TTIImpl::getMemoryOpCost(), llvm::BasicTTIImplBase< T >::getOperandsScalarizationOverhead(), llvm::X86TTIImpl::getScalarizationOverhead(), llvm::GCNTTIImpl::getShuffleCost(), llvm::BasicTTIImplBase< T >::getTypeBasedIntrinsicInstrCost(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::SystemZTTIImpl::getVectorTruncCost(), insertVector(), llvm::AArch64TargetLowering::isLegalInterleavedAccessType(), llvm::X86TTIImpl::isLegalMaskedExpandLoad(), llvm::X86TTIImpl::isLegalMaskedLoad(), isVectorPromotionViableForSlice(), llvm::RewriteStatepointsForGC::runOnFunction(), simplifyX86pack(), llvm::InnerLoopVectorizer::truncateToMinimalBitwidths(), and llvm::UpgradeIntrinsicCall().
getVectorType()
static FixedVectorType * getVectorType (IntrinsicInst * I) static
Definition at line 235 of file MVETailPredication.cpp.
References assert(), and I.
IsDecrement()
static bool IsDecrement (Instruction & I) static
Definition at line 141 of file MVETailPredication.cpp.
References I.
IsMasked()
static bool IsMasked (Instruction * I) static
Definition at line 150 of file MVETailPredication.cpp.
References I.
Referenced by getCombineLoadStoreParts(), getMVEIndexedAddressParts(), llvm::ARMTargetLowering::getPostIndexedAddressParts(), getPostIndexedLoadStoreOp(), llvm::ARMTargetLowering::getPreIndexedAddressParts(), shouldCombineToPostInc(), and llvm::VFABI::tryDemangleForVFABI().
Variable Documentation
EnableTailPredication
cl::opt< TailPredication::Mode > EnableTailPredication("tail-predication", cl::desc("MVE tail-predication options"), cl::init(TailPredication::Disabled), cl::values(clEnumValN(TailPredication::Disabled, "disabled", "Don't tail-predicate loops"), clEnumValN(TailPredication::EnabledNoReductions, "enabled-no-reductions", "Enable tail-predication, but not for reduction loops"), clEnumValN(TailPredication::Enabled, "enabled", "Enable tail-predication, including reduction loops"), clEnumValN(TailPredication::ForceEnabledNoReductions, "force-enabled-no-reductions", "Enable tail-predication, but not for reduction loops, " "and force this which might be unsafe"), clEnumValN(TailPredication::ForceEnabled, "force-enabled", "Enable tail-predication, including reduction loops, " "and force this which might be unsafe"))) ("tail-predication" , cl::desc("MVE tail-predication options") , cl::init(TailPredication::Disabled) , cl::values(clEnumValN(TailPredication::Disabled, "disabled", "Don't tail-predicate loops"), clEnumValN(TailPredication::EnabledNoReductions, "enabled-no-reductions", "Enable tail-predication, but not for reduction loops"), clEnumValN(TailPredication::Enabled, "enabled", "Enable tail-predication, including reduction loops"), clEnumValN(TailPredication::ForceEnabledNoReductions, "force-enabled-no-reductions", "Enable tail-predication, but not for reduction loops, " "and force this which might be unsafe"), clEnumValN(TailPredication::ForceEnabled, "force-enabled", "Enable tail-predication, including reduction loops, " "and force this which might be unsafe")))