LLVM: include/llvm-c/OrcBindings.h File Reference
OrcBindings.h File Reference
#include "llvm-c/Error.h"
#include "llvm-c/ExternC.h"
#include "llvm-c/Object.h"
#include "llvm-c/TargetMachine.h"
Typedefs
typedef typedefLLVM_C_EXTERN_C_BEGIN struct LLVMOrcOpaqueJITStack * LLVMOrcJITStackRef
typedef uint64_t LLVMOrcModuleHandle
typedef uint64_t LLVMOrcTargetAddress
typedef uint64_t(* LLVMOrcSymbolResolverFn) (const char *Name, void *LookupCtx)
typedef uint64_t(* LLVMOrcLazyCompileCallbackFn) (LLVMOrcJITStackRef JITStack, void *CallbackCtx)
Functions
LLVMOrcJITStackRef LLVMOrcCreateInstance (LLVMTargetMachineRef TM)
Create an ORC JIT stack.
const char * LLVMOrcGetErrorMsg (LLVMOrcJITStackRef JITStack)
Get the error message for the most recent error (if any).
void LLVMOrcGetMangledSymbol (LLVMOrcJITStackRef JITStack, char **MangledSymbol, const char *Symbol)
Mangle the given symbol.
void LLVMOrcDisposeMangledSymbol (char *MangledSymbol)
Dispose of a mangled symbol.
LLVMErrorRef LLVMOrcCreateLazyCompileCallback (LLVMOrcJITStackRef JITStack, LLVMOrcTargetAddress *RetAddr, LLVMOrcLazyCompileCallbackFn Callback, void *CallbackCtx)
Create a lazy compile callback.
LLVMErrorRef LLVMOrcCreateIndirectStub (LLVMOrcJITStackRef JITStack, const char *StubName, LLVMOrcTargetAddress InitAddr)
Create a named indirect call stub.
LLVMErrorRef LLVMOrcSetIndirectStubPointer (LLVMOrcJITStackRef JITStack, const char *StubName, LLVMOrcTargetAddress NewAddr)
Set the pointer for the given indirect stub.
LLVMErrorRef LLVMOrcAddEagerlyCompiledIR (LLVMOrcJITStackRef JITStack, LLVMOrcModuleHandle *RetHandle, LLVMModuleRef Mod, LLVMOrcSymbolResolverFn SymbolResolver, void *SymbolResolverCtx)
Add module to be eagerly compiled.
LLVMErrorRef LLVMOrcAddLazilyCompiledIR (LLVMOrcJITStackRef JITStack, LLVMOrcModuleHandle *RetHandle, LLVMModuleRef Mod, LLVMOrcSymbolResolverFn SymbolResolver, void *SymbolResolverCtx)
Add module to be lazily compiled one function at a time.
LLVMErrorRef LLVMOrcAddObjectFile (LLVMOrcJITStackRef JITStack, LLVMOrcModuleHandle *RetHandle, LLVMMemoryBufferRef Obj, LLVMOrcSymbolResolverFn SymbolResolver, void *SymbolResolverCtx)
Add an object file.
LLVMErrorRef LLVMOrcRemoveModule (LLVMOrcJITStackRef JITStack, LLVMOrcModuleHandle H)
Remove a module set from the JIT.
LLVMErrorRef LLVMOrcGetSymbolAddress (LLVMOrcJITStackRef JITStack, LLVMOrcTargetAddress *RetAddr, const char *SymbolName)
Get symbol address from JIT instance.
LLVMErrorRef LLVMOrcGetSymbolAddressIn (LLVMOrcJITStackRef JITStack, LLVMOrcTargetAddress *RetAddr, LLVMOrcModuleHandle H, const char *SymbolName)
Get symbol address from JIT instance, searching only the specified handle.
LLVMErrorRef LLVMOrcDisposeInstance (LLVMOrcJITStackRef JITStack)
Dispose of an ORC JIT stack.
void LLVMOrcRegisterJITEventListener (LLVMOrcJITStackRef JITStack, LLVMJITEventListenerRef L)
Register a JIT Event Listener.
void LLVMOrcUnregisterJITEventListener (LLVMOrcJITStackRef JITStack, LLVMJITEventListenerRef L)
Unegister a JIT Event Listener.
Typedef Documentation
LLVMOrcJITStackRef
typedef typedefLLVM_C_EXTERN_C_BEGIN struct LLVMOrcOpaqueJITStack* LLVMOrcJITStackRef
Definition at line 32 of file OrcBindings.h.
LLVMOrcLazyCompileCallbackFn
typedef uint64_t(* LLVMOrcLazyCompileCallbackFn) (LLVMOrcJITStackRef JITStack, void *CallbackCtx)
Definition at line 36 of file OrcBindings.h.
LLVMOrcModuleHandle
typedef uint64_t LLVMOrcModuleHandle
Definition at line 33 of file OrcBindings.h.
LLVMOrcSymbolResolverFn
typedef uint64_t(* LLVMOrcSymbolResolverFn) (const char *Name, void *LookupCtx)
Definition at line 35 of file OrcBindings.h.
LLVMOrcTargetAddress
typedef uint64_t LLVMOrcTargetAddress
Definition at line 34 of file OrcBindings.h.
Function Documentation
LLVMOrcAddEagerlyCompiledIR()
LLVMErrorRef LLVMOrcAddEagerlyCompiledIR (LLVMOrcJITStackRef JITStack, LLVMOrcModuleHandle * RetHandle, LLVMModuleRef Mod, LLVMOrcSymbolResolverFn SymbolResolver, void * SymbolResolverCtx)
Add module to be eagerly compiled.
Definition at line 69 of file OrcCBindings.cpp.
References llvm::OrcCBindingsStack::addIRModuleEager(), LLVMErrorSuccess, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMOrcAddLazilyCompiledIR()
LLVMErrorRef LLVMOrcAddLazilyCompiledIR (LLVMOrcJITStackRef JITStack, LLVMOrcModuleHandle * RetHandle, LLVMModuleRef Mod, LLVMOrcSymbolResolverFn SymbolResolver, void * SymbolResolverCtx)
Add module to be lazily compiled one function at a time.
Definition at line 84 of file OrcCBindings.cpp.
References llvm::OrcCBindingsStack::addIRModuleLazy(), LLVMErrorSuccess, llvm::Mod, llvm::unwrap(), and llvm::wrap().
LLVMOrcAddObjectFile()
LLVMErrorRef LLVMOrcAddObjectFile (LLVMOrcJITStackRef JITStack, LLVMOrcModuleHandle * RetHandle, LLVMMemoryBufferRef Obj, LLVMOrcSymbolResolverFn SymbolResolver, void * SymbolResolverCtx)
Add an object file.
This method takes ownership of the given memory buffer and attempts to add it to the JIT as an object file. Clients should not dispose of the 'Obj' argument: the JIT will manage it from this call onwards.
Definition at line 99 of file OrcCBindings.cpp.
References llvm::OrcCBindingsStack::addObject(), LLVMErrorSuccess, llvm::unwrap(), and llvm::wrap().
LLVMOrcCreateIndirectStub()
LLVMErrorRef LLVMOrcCreateIndirectStub (LLVMOrcJITStackRef JITStack, const char * StubName, LLVMOrcTargetAddress InitAddr)
Create a named indirect call stub.
Definition at line 55 of file OrcCBindings.cpp.
References llvm::OrcCBindingsStack::createIndirectStub(), llvm::unwrap(), and llvm::wrap().
LLVMOrcCreateInstance()
LLVMOrcJITStackRef LLVMOrcCreateInstance (LLVMTargetMachineRef TM)
Create an ORC JIT stack.
The client owns the resulting stack, and must call OrcDisposeInstance(...) to destroy it and free its memory. The JIT stack will take ownership of the TargetMachine, which will be destroyed when the stack is destroyed. The client should not attempt to dispose of the Target Machine, or it will result in a double-free.
Definition at line 15 of file OrcCBindings.cpp.
References llvm::orc::createLocalIndirectStubsManagerBuilder(), T, llvm::unwrap(), and llvm::wrap().
LLVMOrcCreateLazyCompileCallback()
LLVMErrorRef LLVMOrcCreateLazyCompileCallback (LLVMOrcJITStackRef JITStack, LLVMOrcTargetAddress * RetAddr, LLVMOrcLazyCompileCallbackFn Callback, void * CallbackCtx)
Create a lazy compile callback.
Definition at line 44 of file OrcCBindings.cpp.
References llvm::OrcCBindingsStack::createLazyCompileCallback(), LLVMErrorSuccess, llvm::unwrap(), and llvm::wrap().
LLVMOrcDisposeInstance()
LLVMErrorRef LLVMOrcDisposeInstance (LLVMOrcJITStackRef JITStack)
Dispose of an ORC JIT stack.
Definition at line 143 of file OrcCBindings.cpp.
References llvm::unwrap(), and llvm::wrap().
LLVMOrcDisposeMangledSymbol()
void LLVMOrcDisposeMangledSymbol (char * MangledSymbol)
Dispose of a mangled symbol.
Definition at line 42 of file OrcCBindings.cpp.
LLVMOrcGetErrorMsg()
const char * LLVMOrcGetErrorMsg (LLVMOrcJITStackRef JITStack)
Get the error message for the most recent error (if any).
This message is owned by the ORC JIT Stack and will be freed when the stack is disposed of by LLVMOrcDisposeInstance.
Definition at line 29 of file OrcCBindings.cpp.
References llvm::OrcCBindingsStack::getErrorMessage(), and llvm::unwrap().
LLVMOrcGetMangledSymbol()
void LLVMOrcGetMangledSymbol (LLVMOrcJITStackRef JITStack, char ** MangledSymbol, const char * Symbol)
Mangle the given symbol.
Memory will be allocated for MangledSymbol to hold the result. The client
Definition at line 34 of file OrcCBindings.cpp.
References llvm::OrcCBindingsStack::mangle(), and llvm::unwrap().
LLVMOrcGetSymbolAddress()
LLVMErrorRef LLVMOrcGetSymbolAddress (LLVMOrcJITStackRef JITStack, LLVMOrcTargetAddress * RetAddr, const char * SymbolName)
Get symbol address from JIT instance.
Definition at line 120 of file OrcCBindings.cpp.
References llvm::OrcCBindingsStack::findSymbolAddress(), LLVMErrorSuccess, llvm::unwrap(), and llvm::wrap().
LLVMOrcGetSymbolAddressIn()
LLVMErrorRef LLVMOrcGetSymbolAddressIn (LLVMOrcJITStackRef JITStack, LLVMOrcTargetAddress * RetAddr, LLVMOrcModuleHandle H, const char * SymbolName)
Get symbol address from JIT instance, searching only the specified handle.
Definition at line 131 of file OrcCBindings.cpp.
References llvm::OrcCBindingsStack::findSymbolAddressIn(), H, LLVMErrorSuccess, llvm::unwrap(), and llvm::wrap().
LLVMOrcRegisterJITEventListener()
void LLVMOrcRegisterJITEventListener (LLVMOrcJITStackRef JITStack, LLVMJITEventListenerRef L)
Register a JIT Event Listener.
A NULL listener is ignored.
Definition at line 150 of file OrcCBindings.cpp.
References llvm::unwrap().
LLVMOrcRemoveModule()
LLVMErrorRef LLVMOrcRemoveModule (LLVMOrcJITStackRef JITStack, LLVMOrcModuleHandle H)
Remove a module set from the JIT.
This works for all modules that can be added via OrcAdd*, including object files.
Definition at line 114 of file OrcCBindings.cpp.
References H, llvm::OrcCBindingsStack::removeModule(), llvm::unwrap(), and llvm::wrap().
LLVMOrcSetIndirectStubPointer()
LLVMErrorRef LLVMOrcSetIndirectStubPointer (LLVMOrcJITStackRef JITStack, const char * StubName, LLVMOrcTargetAddress NewAddr)
Set the pointer for the given indirect stub.
Definition at line 62 of file OrcCBindings.cpp.
References llvm::OrcCBindingsStack::setIndirectStubPointer(), llvm::unwrap(), and llvm::wrap().
LLVMOrcUnregisterJITEventListener()
void LLVMOrcUnregisterJITEventListener (LLVMOrcJITStackRef JITStack, LLVMJITEventListenerRef L)
Unegister a JIT Event Listener.
A NULL listener is ignored.
Definition at line 155 of file OrcCBindings.cpp.
References llvm::unwrap().