LLVM: lib/Target/AMDGPU/R600InstrInfo.cpp File Reference
R600InstrInfo.cpp File Reference
R600 Implementation of TargetInstrInfo.
#include "R600InstrInfo.h"
#include "AMDGPU.h"
#include "AMDGPUInstrInfo.h"
#include "AMDGPUSubtarget.h"
#include "R600Defines.h"
#include "R600FrameLowering.h"
#include "R600RegisterInfo.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetRegisterInfo.h"
#include "llvm/CodeGen/TargetSubtargetInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include <algorithm>
#include <cassert>
#include <cstdint>
#include <cstring>
#include <iterator>
#include <utility>
#include <vector>
#include "R600GenDFAPacketizer.inc"
#include "R600GenInstrInfo.inc"
Macros
#define GET_INSTRINFO_CTOR_DTOR
#define GET_INSTRINFO_CTOR_DTOR
#define GET_INSTRMAP_INFO
#define GET_INSTRINFO_NAMED_OPS
#define OPERAND_CASE(Label)
Functions
static std::vector< std::pair< int, unsigned > > Swizzle (std::vector< std::pair< int, unsigned > > Src, R600InstrInfo::BankSwizzle Swz)
static unsigned getTransSwizzle (R600InstrInfo::BankSwizzle Swz, unsigned Op)
static bool NextPossibleSolution (std::vector< R600InstrInfo::BankSwizzle > &SwzCandidate, unsigned Idx)
Given a swizzle sequence SwzCandidate and an index Idx, returns the next (in lexicographic term) swizzle sequence assuming that all swizzles after Idx can be skipped.
static bool isConstCompatible (R600InstrInfo::BankSwizzle TransSwz, const std::vector< std::pair< int, unsigned > > &TransOps, unsigned ConstCount)
Instructions in Trans slot can't read gpr at cycle 0 if they also read a const, and can't read a gpr at cycle 1 if they read 2 const.
static bool isPredicateSetter (unsigned Opcode)
static MachineInstr * findFirstPredicateSetterFrom (MachineBasicBlock &MBB, MachineBasicBlock::iterator I)
static bool isJump (unsigned Opcode)
static bool isBranch (unsigned Opcode)
static MachineBasicBlock::iterator FindLastAluClause (MachineBasicBlock &MBB)
static unsigned getSlotedOps (unsigned Op, unsigned Slot)
Detailed Description
R600 Implementation of TargetInstrInfo.
Definition in file R600InstrInfo.cpp.
Macro Definition Documentation
GET_INSTRINFO_CTOR_DTOR [1/2]
#define GET_INSTRINFO_CTOR_DTOR
Definition at line 46 of file R600InstrInfo.cpp.
GET_INSTRINFO_CTOR_DTOR [2/2]
#define GET_INSTRINFO_CTOR_DTOR
Definition at line 46 of file R600InstrInfo.cpp.
GET_INSTRINFO_NAMED_OPS
#define GET_INSTRINFO_NAMED_OPS
Definition at line 51 of file R600InstrInfo.cpp.
GET_INSTRMAP_INFO
#define GET_INSTRMAP_INFO
Definition at line 50 of file R600InstrInfo.cpp.
OPERAND_CASE
#define OPERAND_CASE (Label)
Value:
  case Label: { \
    static const unsigned Ops[] = \
    { \
      Label##_X, \
      Label##_Y, \
      Label##_Z, \
      Label##_W \
    }; \
    return Ops[Slot]; \
  }
Definition at line 1278 of file R600InstrInfo.cpp.
Referenced by getSlotedOps().
Function Documentation
findFirstPredicateSetterFrom()
static MachineInstr * findFirstPredicateSetterFrom (MachineBasicBlock & MBB, MachineBasicBlock::iterator I) static
Definition at line 652 of file R600InstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), I, isPredicateSetter(), MBB, and MI.
Referenced by llvm::R600InstrInfo::insertBranch(), and llvm::R600InstrInfo::removeBranch().
FindLastAluClause()
static MachineBasicBlock::iterator FindLastAluClause (MachineBasicBlock & MBB) static
Definition at line 746 of file R600InstrInfo.cpp.
References E, llvm::MachineBasicBlock::end(), MBB, llvm::MachineBasicBlock::rbegin(), and llvm::MachineBasicBlock::rend().
Referenced by llvm::R600InstrInfo::insertBranch(), and llvm::R600InstrInfo::removeBranch().
getSlotedOps()
static unsigned getSlotedOps (unsigned Op, unsigned Slot) static
Definition at line 1290 of file R600InstrInfo.cpp.
References llvm_unreachable, and OPERAND_CASE.
Referenced by llvm::R600InstrInfo::buildSlotOfVectorInstruction().
getTransSwizzle()
static unsigned getTransSwizzle (R600InstrInfo::BankSwizzle Swz, unsigned Op) static
Definition at line 402 of file R600InstrInfo.cpp.
References llvm::R600InstrInfo::ALU_VEC_012_SCL_210, llvm::R600InstrInfo::ALU_VEC_021_SCL_122, llvm::R600InstrInfo::ALU_VEC_102_SCL_221, llvm::R600InstrInfo::ALU_VEC_120_SCL_212, assert(), and llvm_unreachable.
Referenced by isConstCompatible(), and llvm::R600InstrInfo::isLegalUpTo().
isBranch()
static bool isBranch (unsigned Opcode) static
Definition at line 669 of file R600InstrInfo.cpp.
Referenced by llvm::R600InstrInfo::analyzeBranch(), decodePCDBLOperand(), llvm::HexagonShuffler::GetPacketSummary(), llvm::HexagonMCInstrInfo::isConstExtended(), llvm::HexagonInstrInfo::isPredictedTaken(), llvm::HexagonInstrInfo::reverseBranchCondition(), translateImmediate(), tryAddingSymbolicOperand(), tryAddingSymbolicOperand(), tryAddingSymbolicOperand(), and tryAddingSymbolicOperand().
isConstCompatible()
static bool isConstCompatible (R600InstrInfo::BankSwizzle TransSwz, const std::vector< std::pair< int, unsigned > > & TransOps, unsigned ConstCount) static
Instructions in Trans slot can't read gpr at cycle 0 if they also read a const, and can't read a gpr at cycle 1 if they read 2 const.
Definition at line 515 of file R600InstrInfo.cpp.
References getTransSwizzle().
Referenced by llvm::R600InstrInfo::fitsReadPortLimitations().
isJump()
static bool isJump (unsigned Opcode) static
Definition at line 665 of file R600InstrInfo.cpp.
Referenced by llvm::R600InstrInfo::analyzeBranch().
isPredicateSetter()
static bool isPredicateSetter (unsigned Opcode) static
Definition at line 642 of file R600InstrInfo.cpp.
Referenced by llvm::R600InstrInfo::analyzeBranch(), llvm::R600InstrInfo::DefinesPredicate(), and findFirstPredicateSetterFrom().
NextPossibleSolution()
static bool NextPossibleSolution (std::vector< R600InstrInfo::BankSwizzle > & SwzCandidate, unsigned Idx) static
Given a swizzle sequence SwzCandidate and an index Idx, returns the next (in lexicographic term) swizzle sequence assuming that all swizzles after Idx can be skipped.
Definition at line 479 of file R600InstrInfo.cpp.
References llvm::R600InstrInfo::ALU_VEC_012_SCL_210, llvm::R600InstrInfo::ALU_VEC_210, assert(), and Idx.
Referenced by llvm::R600InstrInfo::FindSwizzleForVectorSlot().
Swizzle()
static std::vector< std::pair< int, unsigned > > Swizzle (std::vector< std::pair< int, unsigned > > Src, R600InstrInfo::BankSwizzle Swz) static
Definition at line 374 of file R600InstrInfo.cpp.
References llvm::R600InstrInfo::ALU_VEC_012_SCL_210, llvm::R600InstrInfo::ALU_VEC_021_SCL_122, llvm::R600InstrInfo::ALU_VEC_102_SCL_221, llvm::R600InstrInfo::ALU_VEC_120_SCL_212, llvm::R600InstrInfo::ALU_VEC_201, llvm::R600InstrInfo::ALU_VEC_210, and std::swap().
Referenced by llvm::R600InstrInfo::isLegalUpTo().