LLVM: lib/Target/AMDGPU/SIInsertSkips.cpp File Reference
SIInsertSkips.cpp File Reference
This pass inserts branches on the 0 exec mask over divergent branches branches when it's expected that jumping over the untaken control flow will be cheaper than having every workitem no-op through it.
#include "AMDGPU.h"
#include "AMDGPUSubtarget.h"
#include "SIInstrInfo.h"
#include "SIMachineFunctionInfo.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineOperand.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/DebugLoc.h"
#include "llvm/InitializePasses.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetMachine.h"
#include <cassert>
#include <cstdint>
#include <iterator>
Macros
#define DEBUG_TYPE "si-insert-skips"
Functions
INITIALIZE_PASS_BEGIN (SIInsertSkips, DEBUG_TYPE, "SI insert s_cbranch_execz instructions", false, false) INITIALIZE_PASS_END(SIInsertSkips
static bool opcodeEmitsNoInsts (const MachineInstr &MI)
static void generatePsEndPgm (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, DebugLoc DL, const SIInstrInfo *TII)
Variables
static cl::opt< unsigned > SkipThresholdFlag ("amdgpu-skip-threshold-legacy", cl::desc("Number of instructions before jumping over divergent control flow"), cl::init(12), cl::Hidden)
DEBUG_TYPE
SI insert s_cbranch_execz instructions
SI insert s_cbranch_execz false
Detailed Description
This pass inserts branches on the 0 exec mask over divergent branches branches when it's expected that jumping over the untaken control flow will be cheaper than having every workitem no-op through it.
Definition in file SIInsertSkips.cpp.
Macro Definition Documentation
DEBUG_TYPE
#define DEBUG_TYPE "si-insert-skips"
Definition at line 44 of file SIInsertSkips.cpp.
Function Documentation
generatePsEndPgm()
static void generatePsEndPgm (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, DebugLoc DL, const SIInstrInfo * TII) static
Definition at line 167 of file SIInsertSkips.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), DL, I, MBB, TII, and llvm::RegState::Undef.
INITIALIZE_PASS_BEGIN()
INITIALIZE_PASS_BEGIN (SIInsertSkips , DEBUG_TYPE , "SI insert s_cbranch_execz instructions" , false , false)
opcodeEmitsNoInsts()
static bool opcodeEmitsNoInsts (const MachineInstr & MI) static
Definition at line 104 of file SIInsertSkips.cpp.
References MI.
Variable Documentation
DEBUG_TYPE
DEBUG_TYPE
Definition at line 99 of file SIInsertSkips.cpp.
false
SI insert s_cbranch_execz false
Definition at line 100 of file SIInsertSkips.cpp.
instructions
SI insert s_cbranch_execz instructions
Definition at line 100 of file SIInsertSkips.cpp.
SkipThresholdFlag
cl::opt< unsigned > SkipThresholdFlag("amdgpu-skip-threshold-legacy", cl::desc("Number of instructions before jumping over divergent control flow"), cl::init(12), cl::Hidden) ("amdgpu-skip-threshold-legacy" , cl::desc("Number of instructions before jumping over divergent control flow") , cl::init(12) , cl::Hidden) static