LLVM: lib/Target/AMDGPU/MCTargetDesc/SIMCCodeEmitter.cpp File Reference
SIMCCodeEmitter.cpp File Reference
The SI code emitter produces machine code that can be executed directly on the GPU device.
#include "AMDGPU.h"
#include "MCTargetDesc/AMDGPUFixupKinds.h"
#include "MCTargetDesc/AMDGPUMCCodeEmitter.h"
#include "MCTargetDesc/AMDGPUMCTargetDesc.h"
#include "SIDefines.h"
#include "Utils/AMDGPUBaseInfo.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrDesc.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <cstdint>
#include <cstdlib>
#include "AMDGPUGenMCCodeEmitter.inc"
Macros
#define ENABLE_INSTR_PREDICATE_VERIFIER
Functions
template<typename IntTy >
static uint32_t getIntInlineImmEncoding (IntTy Imm)
static uint32_t getLit16IntEncoding (uint16_t Val, const MCSubtargetInfo &STI)
static uint32_t getLit16Encoding (uint16_t Val, const MCSubtargetInfo &STI)
static uint32_t getLit32Encoding (uint32_t Val, const MCSubtargetInfo &STI)
static uint32_t getLit64Encoding (uint64_t Val, const MCSubtargetInfo &STI)
static bool needsPCRel (const MCExpr *Expr)
Detailed Description
The SI code emitter produces machine code that can be executed directly on the GPU device.
Definition in file SIMCCodeEmitter.cpp.
Macro Definition Documentation
ENABLE_INSTR_PREDICATE_VERIFIER
#define ENABLE_INSTR_PREDICATE_VERIFIER
Definition at line 531 of file SIMCCodeEmitter.cpp.
Function Documentation
getIntInlineImmEncoding()
template<typename IntTy > static uint32_t getIntInlineImmEncoding (IntTy Imm) static
Definition at line 101 of file SIMCCodeEmitter.cpp.
Referenced by getLit16Encoding(), getLit16IntEncoding(), getLit32Encoding(), and getLit64Encoding().
getLit16Encoding()
static uint32_t getLit16Encoding (uint16_t Val, const MCSubtargetInfo & STI) static
Definition at line 116 of file SIMCCodeEmitter.cpp.
References llvm::MCSubtargetInfo::getFeatureBits(), and getIntInlineImmEncoding().
getLit16IntEncoding()
static uint32_t getLit16IntEncoding (uint16_t Val, const MCSubtargetInfo & STI) static
Definition at line 111 of file SIMCCodeEmitter.cpp.
References getIntInlineImmEncoding().
getLit32Encoding()
static uint32_t getLit32Encoding (uint32_t Val, const MCSubtargetInfo & STI) static
Definition at line 152 of file SIMCCodeEmitter.cpp.
References llvm::FloatToBits(), llvm::MCSubtargetInfo::getFeatureBits(), and getIntInlineImmEncoding().
getLit64Encoding()
static uint32_t getLit64Encoding (uint64_t Val, const MCSubtargetInfo & STI) static
Definition at line 188 of file SIMCCodeEmitter.cpp.
References llvm::DoubleToBits(), llvm::MCSubtargetInfo::getFeatureBits(), and getIntInlineImmEncoding().
needsPCRel()
static bool needsPCRel (const MCExpr * Expr) static
Definition at line 455 of file SIMCCodeEmitter.cpp.
References llvm::MCExpr::Binary, llvm::MCExpr::Constant, llvm::MCExpr::getKind(), llvm_unreachable, needsPCRel(), llvm::MCBinaryExpr::Sub, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, llvm::MCExpr::Unary, llvm::MCSymbolRefExpr::VK_AMDGPU_ABS32_HI, and llvm::MCSymbolRefExpr::VK_AMDGPU_ABS32_LO.
Referenced by needsPCRel().