LLVM: include/llvm/Demangle/StringView.h File Reference
StringView.h File Reference
#include "DemangleConfig.h"
#include <algorithm>
#include <cassert>
#include <cstring>
Classes
class StringView
Functions
bool operator== (const StringView &LHS, const StringView &RHS)
Function Documentation
operator==()
bool operator== (const StringView & LHS, const StringView & RHS) inline
Definition at line 119 of file StringView.h.
References StringView::begin(), StringView::end(), and StringView::size().
Referenced by llvm::ConstantRange::operator!=(), llvm::IntervalMapImpl::NodeRef::operator!=(), and llvm::BitTracker::RegisterCell::operator!=().