LLVM: llvm::WinEHFuncInfo Struct Reference
llvm::WinEHFuncInfo Struct Reference
#include "llvm/CodeGen/WinEHFuncInfo.h"
Public Member Functions
int getLastStateNumber () const
void addIPToStateRange (const InvokeInst *II, MCSymbol *InvokeBegin, MCSymbol *InvokeEnd)
WinEHFuncInfo ()
Public Attributes
DenseMap< const Instruction *, int > EHPadStateMap
DenseMap< const FuncletPadInst *, int > FuncletBaseStateMap
DenseMap< const InvokeInst *, int > InvokeStateMap
DenseMap< MCSymbol *, std::pair< int, MCSymbol * > > LabelToStateMap
SmallVector< CxxUnwindMapEntry, 4 > CxxUnwindMap
SmallVector< WinEHTryBlockMapEntry, 4 > TryBlockMap
SmallVector< SEHUnwindMapEntry, 4 > SEHUnwindMap
SmallVector< ClrEHUnwindMapEntry, 4 > ClrEHUnwindMap
int UnwindHelpFrameIdx = std::numeric_limits<int>::max()
int PSPSymFrameIdx = std::numeric_limits<int>::max()
int EHRegNodeFrameIndex = std::numeric_limits<int>::max()
int EHRegNodeEndOffset = std::numeric_limits<int>::max()
int EHGuardFrameIndex = std::numeric_limits<int>::max()
int SEHSetFrameOffset = std::numeric_limits<int>::max()
Detailed Description
Definition at line 90 of file WinEHFuncInfo.h.
Constructor & Destructor Documentation
WinEHFuncInfo()
WinEHFuncInfo::WinEHFuncInfo ()
Definition at line 1271 of file WinEHPrepare.cpp.
Member Function Documentation
addIPToStateRange()
void WinEHFuncInfo::addIPToStateRange (const InvokeInst * II, MCSymbol * InvokeBegin, MCSymbol * InvokeEnd)
Definition at line 1263 of file WinEHPrepare.cpp.
References assert().
Referenced by llvm::SelectionDAGBuilder::lowerInvokable().
getLastStateNumber()
int llvm::WinEHFuncInfo::getLastStateNumber () const inline
Definition at line 102 of file WinEHFuncInfo.h.
References CxxUnwindMap.
Referenced by addUnwindMapEntry(), and calculateCXXStateNumbers().
Member Data Documentation
ClrEHUnwindMap
SmallVector<ClrEHUnwindMapEntry, 4> llvm::WinEHFuncInfo::ClrEHUnwindMap
Definition at line 98 of file WinEHFuncInfo.h.
Referenced by addClrEHHandler(), llvm::calculateClrEHStateNumbers(), getTryAncestor(), getTryRank(), and llvm::FunctionLoweringInfo::set().
CxxUnwindMap
SmallVector<CxxUnwindMapEntry, 4> llvm::WinEHFuncInfo::CxxUnwindMap
Definition at line 95 of file WinEHFuncInfo.h.
Referenced by addUnwindMapEntry(), getLastStateNumber(), and llvm::FunctionLoweringInfo::set().
EHGuardFrameIndex
int llvm::WinEHFuncInfo::EHGuardFrameIndex = std::numeric_limits<int>::max()
Definition at line 109 of file WinEHFuncInfo.h.
Referenced by MarkEHGuard().
EHPadStateMap
DenseMap<const Instruction *, int> llvm::WinEHFuncInfo::EHPadStateMap
Definition at line 91 of file WinEHFuncInfo.h.
Referenced by llvm::calculateClrEHStateNumbers(), calculateCXXStateNumbers(), calculateSEHStateNumbers(), calculateStateNumbersForInvokes(), and llvm::calculateWinCXXEHStateNumbers().
EHRegNodeEndOffset
int llvm::WinEHFuncInfo::EHRegNodeEndOffset = std::numeric_limits<int>::max()
Definition at line 108 of file WinEHFuncInfo.h.
Referenced by llvm::X86FrameLowering::restoreWin32EHStackPointers().
EHRegNodeFrameIndex
int llvm::WinEHFuncInfo::EHRegNodeFrameIndex = std::numeric_limits<int>::max()
Definition at line 107 of file WinEHFuncInfo.h.
Referenced by llvm::X86FrameLowering::emitPrologue(), MarkEHRegistrationNode(), and llvm::X86FrameLowering::restoreWin32EHStackPointers().
FuncletBaseStateMap
DenseMap<const FuncletPadInst *, int> llvm::WinEHFuncInfo::FuncletBaseStateMap
Definition at line 92 of file WinEHFuncInfo.h.
Referenced by calculateCXXStateNumbers(), and calculateStateNumbersForInvokes().
InvokeStateMap
DenseMap<const InvokeInst *, int> llvm::WinEHFuncInfo::InvokeStateMap
Definition at line 93 of file WinEHFuncInfo.h.
Referenced by calculateStateNumbersForInvokes().
LabelToStateMap
DenseMap<MCSymbol *, std::pair<int, MCSymbol *> > llvm::WinEHFuncInfo::LabelToStateMap
Definition at line 94 of file WinEHFuncInfo.h.
PSPSymFrameIdx
int llvm::WinEHFuncInfo::PSPSymFrameIdx = std::numeric_limits<int>::max()
Definition at line 100 of file WinEHFuncInfo.h.
Referenced by llvm::X86FrameLowering::emitPrologue().
SEHSetFrameOffset
int llvm::WinEHFuncInfo::SEHSetFrameOffset = std::numeric_limits<int>::max()
Definition at line 110 of file WinEHFuncInfo.h.
Referenced by llvm::X86FrameLowering::emitPrologue().
SEHUnwindMap
SmallVector<SEHUnwindMapEntry, 4> llvm::WinEHFuncInfo::SEHUnwindMap
Definition at line 97 of file WinEHFuncInfo.h.
Referenced by addSEHExcept(), addSEHFinally(), llvm::calculateSEHStateNumbers(), and llvm::FunctionLoweringInfo::set().
TryBlockMap
SmallVector<WinEHTryBlockMapEntry, 4> llvm::WinEHFuncInfo::TryBlockMap
Definition at line 96 of file WinEHFuncInfo.h.
Referenced by addTryBlockMapEntry(), calculateCXXStateNumbers(), llvm::X86FrameLowering::processFunctionBeforeFrameFinalized(), and llvm::FunctionLoweringInfo::set().
UnwindHelpFrameIdx
int llvm::WinEHFuncInfo::UnwindHelpFrameIdx = std::numeric_limits<int>::max()
Definition at line 99 of file WinEHFuncInfo.h.
Referenced by llvm::AArch64FrameLowering::processFunctionBeforeFrameFinalized(), and llvm::X86FrameLowering::processFunctionBeforeFrameFinalized().
The documentation for this struct was generated from the following files:
include/llvm/CodeGen/WinEHFuncInfo.h
lib/CodeGen/WinEHPrepare.cpp