LLVM: llvm::rdf::NodeAttrs Struct Reference
llvm::rdf::NodeAttrs Struct Reference
#include "llvm/CodeGen/RDFGraph.h"
Public Types
enum : uint16_t {
None = 0x0000 , TypeMask = 0x0003 , Code = 0x0001 , Ref = 0x0002 ,
KindMask = 0x0007 << 2 , Def = 0x0001 << 2 , Use = 0x0002 << 2 , Phi = 0x0003 << 2 ,
Stmt = 0x0004 << 2 , Block = 0x0005 << 2 , Func = 0x0006 << 2 , FlagMask = 0x007F << 5 ,
Shadow = 0x0001 << 5 , Clobbering = 0x0002 << 5 , PhiRef = 0x0004 << 5 , Preserving = 0x0008 << 5 ,
Fixed = 0x0010 << 5 , Undef = 0x0020 << 5 , Dead = 0x0040 << 5
}
Static Public Member Functions
static uint16_t type (uint16_t T)
static uint16_t kind (uint16_t T)
static uint16_t flags (uint16_t T)
static uint16_t set_type (uint16_t A, uint16_t T)
static uint16_t set_kind (uint16_t A, uint16_t K)
static uint16_t set_flags (uint16_t A, uint16_t F)
static bool contains (uint16_t A, uint16_t B)
Detailed Description
Definition at line 264 of file RDFGraph.h.
Member Enumeration Documentation
anonymous enum
anonymous enum : uint16_t
Enumerator
None
TypeMask
Code
Ref
KindMask
Def
Use
Phi
Stmt
Block
Func
FlagMask
Shadow
Clobbering
PhiRef
Preserving
Fixed
Undef
Dead
Definition at line 265 of file RDFGraph.h.
Member Function Documentation
contains()
static bool llvm::rdf::NodeAttrs::contains (uint16_t A, uint16_t B) inline static
Definition at line 310 of file RDFGraph.h.
References A, B, Block, Code, Func, kind(), Phi, Ref, Stmt, and type().
flags()
static uint16_t llvm::rdf::NodeAttrs::flags (uint16_t T) inline static
Definition at line 295 of file RDFGraph.h.
References FlagMask.
Referenced by llvm::rdf::NodeBase::getFlags(), llvm::rdf::RefNode::getRegRef(), llvm::rdf::operator<<(), llvm::rdf::RefNode::setRegRef(), and llvm::rdf::RefNode::setRegRef().
kind()
static uint16_t llvm::rdf::NodeAttrs::kind (uint16_t T) inline static
Definition at line 294 of file RDFGraph.h.
References KindMask.
Referenced by contains(), llvm::rdf::NodeBase::getKind(), and llvm::rdf::operator<<().
set_flags()
static uint16_t llvm::rdf::NodeAttrs::set_flags (uint16_t A, uint16_t F) inline static
Definition at line 305 of file RDFGraph.h.
References A, F, and FlagMask.
Referenced by llvm::rdf::NodeBase::setFlags().
set_kind()
static uint16_t llvm::rdf::NodeAttrs::set_kind (uint16_t A, uint16_t K) inline static
Definition at line 301 of file RDFGraph.h.
References A, and KindMask.
set_type()
static uint16_t llvm::rdf::NodeAttrs::set_type (uint16_t A, uint16_t T) inline static
Definition at line 297 of file RDFGraph.h.
References A, T, and TypeMask.
type()
static uint16_t llvm::rdf::NodeAttrs::type (uint16_t T) inline static
Definition at line 293 of file RDFGraph.h.
References TypeMask.
Referenced by contains(), llvm::rdf::RefNode::getRegRef(), llvm::rdf::NodeBase::getType(), llvm::rdf::operator<<(), llvm::rdf::RefNode::setRegRef(), and llvm::rdf::RefNode::setRegRef().
The documentation for this struct was generated from the following file:
include/llvm/CodeGen/RDFGraph.h