LLVM: llvm::InlineAsmIdentifierInfo Struct Reference
llvm::InlineAsmIdentifierInfo Struct Reference
#include "llvm/MC/MCParser/MCAsmParser.h"
Classes
struct EnumIdentifier
struct LabelIdentifier
struct VariableIdentifier
Public Types
enum IdKind { IK_Invalid , IK_Label , IK_EnumVal , IK_Var }
Public Member Functions
bool isKind (IdKind kind) const
void setEnum (int64_t enumVal)
void setLabel (void *decl)
void setVar (void *decl, bool isGlobalLV, unsigned size, unsigned type)
InlineAsmIdentifierInfo ()
Public Attributes
union {
EnumIdentifier Enum
LabelIdentifier Label
VariableIdentifier Var
};
Detailed Description
Definition at line 36 of file MCAsmParser.h.
Member Enumeration Documentation
IdKind
enum llvm::InlineAsmIdentifierInfo::IdKind
Enumerator
IK_Invalid
IK_Label
IK_EnumVal
IK_Var
Definition at line 37 of file MCAsmParser.h.
Constructor & Destructor Documentation
InlineAsmIdentifierInfo()
llvm::InlineAsmIdentifierInfo::InlineAsmIdentifierInfo () inline
Definition at line 86 of file MCAsmParser.h.
Member Function Documentation
isKind()
bool llvm::InlineAsmIdentifierInfo::isKind (IdKind kind) const inline
Definition at line 65 of file MCAsmParser.h.
Referenced by setEnum(), setLabel(), and setVar().
setEnum()
void llvm::InlineAsmIdentifierInfo::setEnum (int64_t enumVal) inline
Definition at line 67 of file MCAsmParser.h.
References assert(), Enum, llvm::InlineAsmIdentifierInfo::EnumIdentifier::EnumVal, IK_EnumVal, IK_Invalid, and isKind().
setLabel()
void llvm::InlineAsmIdentifierInfo::setLabel (void * decl) inline
Definition at line 72 of file MCAsmParser.h.
References assert(), llvm::InlineAsmIdentifierInfo::LabelIdentifier::Decl, IK_Invalid, IK_Label, isKind(), and Label.
setVar()
void llvm::InlineAsmIdentifierInfo::setVar (void * decl, bool isGlobalLV, unsigned size, unsigned type) inline
Definition at line 77 of file MCAsmParser.h.
References assert(), llvm::InlineAsmIdentifierInfo::VariableIdentifier::Decl, IK_Invalid, IK_Var, llvm::InlineAsmIdentifierInfo::VariableIdentifier::IsGlobalLV, isKind(), llvm::InlineAsmIdentifierInfo::VariableIdentifier::Length, llvm::size(), llvm::InlineAsmIdentifierInfo::VariableIdentifier::Size, llvm::InlineAsmIdentifierInfo::VariableIdentifier::Type, and Var.
Member Data Documentation
[union]
union { ... } llvm::InlineAsmIdentifierInfo
Enum
EnumIdentifier llvm::InlineAsmIdentifierInfo::Enum
Definition at line 61 of file MCAsmParser.h.
Referenced by setEnum().
Label
LabelIdentifier llvm::InlineAsmIdentifierInfo::Label
Definition at line 62 of file MCAsmParser.h.
Referenced by setLabel().
Var
VariableIdentifier llvm::InlineAsmIdentifierInfo::Var
Definition at line 63 of file MCAsmParser.h.
Referenced by setVar().
The documentation for this struct was generated from the following file:
include/llvm/MC/MCParser/MCAsmParser.h