LLVM: llvm::MDNodeKeyImpl< DIModule > Struct Reference
llvm::MDNodeKeyImpl< DIModule > Struct Reference
#include "IR/LLVMContextImpl.h"
Public Member Functions
MDNodeKeyImpl (Metadata *File, Metadata *Scope, MDString *Name, MDString *ConfigurationMacros, MDString *IncludePath, MDString *APINotesFile, unsigned LineNo)
MDNodeKeyImpl (const DIModule *N)
bool isKeyOf (const DIModule *RHS) const
unsigned getHashValue () const
Public Attributes
Metadata * File
Metadata * Scope
MDString * Name
MDString * ConfigurationMacros
MDString * IncludePath
MDString * APINotesFile
unsigned LineNo
Detailed Description
Definition at line 836 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
MDNodeKeyImpl() [1/2]
llvm::MDNodeKeyImpl< DIModule >::MDNodeKeyImpl (Metadata * File, Metadata * Scope, MDString * Name, MDString * ConfigurationMacros, MDString * IncludePath, MDString * APINotesFile, unsigned LineNo) inline
Definition at line 845 of file LLVMContextImpl.h.
MDNodeKeyImpl() [2/2]
llvm::MDNodeKeyImpl< DIModule >::MDNodeKeyImpl (const DIModule * N) inline
Definition at line 851 of file LLVMContextImpl.h.
Member Function Documentation
getHashValue()
unsigned llvm::MDNodeKeyImpl< DIModule >::getHashValue () const inline
Definition at line 865 of file LLVMContextImpl.h.
References llvm::hash_combine(), and Name.
isKeyOf()
bool llvm::MDNodeKeyImpl< DIModule >::isKeyOf (const DIModule * RHS) const inline
Definition at line 857 of file LLVMContextImpl.h.
References llvm::DIModule::getLineNo(), llvm::DIModule::getRawAPINotesFile(), llvm::DIModule::getRawConfigurationMacros(), llvm::DIScope::getRawFile(), llvm::DIModule::getRawIncludePath(), llvm::DIModule::getRawName(), llvm::DIModule::getRawScope(), and Name.
Member Data Documentation
APINotesFile
MDString* llvm::MDNodeKeyImpl< DIModule >::APINotesFile
Definition at line 842 of file LLVMContextImpl.h.
ConfigurationMacros
MDString* llvm::MDNodeKeyImpl< DIModule >::ConfigurationMacros
Definition at line 840 of file LLVMContextImpl.h.
File
Metadata* llvm::MDNodeKeyImpl< DIModule >::File
Definition at line 837 of file LLVMContextImpl.h.
IncludePath
MDString* llvm::MDNodeKeyImpl< DIModule >::IncludePath
Definition at line 841 of file LLVMContextImpl.h.
LineNo
unsigned llvm::MDNodeKeyImpl< DIModule >::LineNo
Definition at line 843 of file LLVMContextImpl.h.
Name
MDString* llvm::MDNodeKeyImpl< DIModule >::Name
Definition at line 839 of file LLVMContextImpl.h.
Scope
Metadata* llvm::MDNodeKeyImpl< DIModule >::Scope
Definition at line 838 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
lib/IR/LLVMContextImpl.h