LLVM: llvm::AAIsDead Struct Reference
llvm::AAIsDead Struct Reference abstract
An abstract interface for liveness abstract attribute.
#include "llvm/Transforms/IPO/Attributor.h"
Public Types
using Base = StateWrapper<BooleanState, AbstractAttribute>
Public Types inherited from llvm::StateWrapper< BooleanState, AbstractAttribute >
using StateType
Provide static access to the type of the state.
Public Types inherited from llvm::AbstractAttribute
using StateType = AbstractState
Public Types inherited from llvm::IRPosition
enum Kind : char {
IRP_INVALID , IRP_FLOAT , IRP_RETURNED , IRP_CALL_SITE_RETURNED ,
IRP_FUNCTION , IRP_CALL_SITE , IRP_ARGUMENT , IRP_CALL_SITE_ARGUMENT
}
The positions we distinguish in the IR.
Public Types inherited from llvm::BooleanState
using super = IntegerStateBase<bool, 1, 0>
using base_t = IntegerStateBase::base_t
Public Types inherited from llvm::IntegerStateBase< bool, 1, 0 >
using base_t
Public Member Functions
AAIsDead (const IRPosition &IRP, Attributor &A)
const std::string getName () const override
See AbstractAttribute::getName()
const char * getIdAddr () const override
See AbstractAttribute::getIdAddr()
Public Member Functions inherited from llvm::StateWrapper< BooleanState, AbstractAttribute >
StateWrapper (const IRPosition &IRP, Ts... Args)
StateType & getState () override
See AbstractAttribute::getState(...).
const AbstractState & getState () const override
See AbstractAttribute::getState(...).
Public Member Functions inherited from llvm::AbstractAttribute
AbstractAttribute (const IRPosition &IRP)
virtual ~AbstractAttribute ()
Virtual destructor.
virtual void initialize (Attributor &A)
Initialize the state with the information in the Attributor A.
const IRPosition & getIRPosition () const
Return an IR position, see struct IRPosition.
IRPosition & getIRPosition ()
virtual void print (raw_ostream &OS) const
Helper functions, for debug purposes only.
void dump () const
virtual const std::string getAsStr () const =0
This function should return the "summarized" assumed state as string.
Public Member Functions inherited from llvm::IRPosition
IRPosition ()
Default constructor available to create invalid positions implicitly.
bool operator== (const IRPosition &RHS) const
bool operator!= (const IRPosition &RHS) const
Value & getAnchorValue () const
Return the value this abstract attribute is anchored with.
Function * getAssociatedFunction () const
Return the associated function, if any.
Argument * getAssociatedArgument () const
Return the associated argument, if any.
bool isFnInterfaceKind () const
Return true if the position refers to a function interface, that is the function scope, the function return, or an argument.
Function * getAnchorScope () const
Return the Function surrounding the anchor value.
Instruction * getCtxI () const
Return the context instruction, if any.
Value & getAssociatedValue () const
Return the value this abstract attribute is associated with.
Type * getAssociatedType () const
Return the type this abstract attribute is associated with.
int getArgNo () const
Return the argument number of the associated value if it is an argument or call site argument, otherwise a negative value.
unsigned getAttrIdx () const
Return the index in the attribute list for this position.
Kind getPositionKind () const
Return the associated position kind.
bool hasAttr (ArrayRef< Attribute::AttrKind > AKs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
TODO: Figure out if the attribute related helper functions should live here or somewhere else.
void getAttrs (ArrayRef< Attribute::AttrKind > AKs, SmallVectorImpl< Attribute > &Attrs, bool IgnoreSubsumingPositions=false, Attributor *A=nullptr) const
Return the attributes of any kind in AKs existing in the IR at a position that will affect this one.
void removeAttrs (ArrayRef< Attribute::AttrKind > AKs) const
Remove the attribute of kind AKs existing in the IR at this position.
bool isAnyCallSitePosition () const
operator void * () const
}
Public Member Functions inherited from llvm::BooleanState
BooleanState ()
BooleanState (base_t Assumed)
void setAssumed (bool Value)
Set the assumed value to Value but never below the known one.
void setKnown (bool Value)
Set the known and asssumed value to Value.
bool isAssumed () const
Return true if the state is assumed to hold.
bool isKnown () const
Return true if the state is known to hold.
Public Member Functions inherited from llvm::IntegerStateBase< bool, 1, 0 >
IntegerStateBase ()
IntegerStateBase (base_t Assumed)
bool isValidState () const override
See AbstractState::isValidState() NOTE: For now we simply pretend that the worst possible state is invalid.
bool isAtFixpoint () const override
See AbstractState::isAtFixpoint()
ChangeStatus indicateOptimisticFixpoint () override
See AbstractState::indicateOptimisticFixpoint(...)
ChangeStatus indicatePessimisticFixpoint () override
See AbstractState::indicatePessimisticFixpoint(...)
base_t getKnown () const
Return the known state encoding.
base_t getAssumed () const
Return the assumed state encoding.
bool operator== (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Equality for IntegerStateBase.
bool operator!= (const IntegerStateBase< base_t, BestState, WorstState > &R) const
Inequality for IntegerStateBase.
void operator^= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator+= (const IntegerStateBase< base_t, BestState, WorstState > &R)
"Clamp" this state with R.
void operator|= (const IntegerStateBase< base_t, BestState, WorstState > &R)
void operator&= (const IntegerStateBase< base_t, BestState, WorstState > &R)
Public Member Functions inherited from llvm::AbstractState
virtual ~AbstractState ()
Static Public Member Functions
static AAIsDead & createForPosition (const IRPosition &IRP, Attributor &A)
Create an abstract attribute view for the position IRP.
static bool mayCatchAsynchronousExceptions (const Function &F)
Determine if F might catch asynchronous exceptions.
static bool classof (const AbstractAttribute *AA)
This function should return true if the type of the AA is AAIsDead.
Static Public Member Functions inherited from llvm::IRPosition
static const IRPosition value (const Value &V)
Create a position describing the value of V.
static const IRPosition function (const Function &F)
Create a position describing the function scope of F.
static const IRPosition returned (const Function &F)
Create a position describing the returned value of F.
static const IRPosition argument (const Argument &Arg)
Create a position describing the argument Arg.
static const IRPosition callsite_function (const CallBase &CB)
Create a position describing the function scope of CB.
static const IRPosition callsite_returned (const CallBase &CB)
Create a position describing the returned value of CB.
static const IRPosition callsite_argument (const CallBase &CB, unsigned ArgNo)
Create a position describing the argument of CB at position ArgNo.
static const IRPosition callsite_argument (AbstractCallSite ACS, unsigned ArgNo)
Create a position describing the argument of ACS at position ArgNo.
static const IRPosition function_scope (const IRPosition &IRP)
Create a position with function scope matching the "context" of IRP.
Static Public Member Functions inherited from llvm::IntegerStateBase< bool, 1, 0 >
static constexpr base_t getBestState ()
Return the best possible representable state.
static constexpr base_t getBestState (const IntegerStateBase &)
static constexpr base_t getWorstState ()
Return the worst possible representable state.
static constexpr base_t getWorstState (const IntegerStateBase &)
Static Public Attributes
static const char ID = 0
Unique ID (due to the unique address)
Static Public Attributes inherited from llvm::IRPosition
static const IRPosition EmptyKey
Special DenseMap key values.
static const IRPosition TombstoneKey
Protected Member Functions
virtual bool isAssumedDead () const =0
The query functions are protected such that other attributes need to go through the Attributor interfaces: Attributor::isAssumedDead(...)
virtual bool isKnownDead () const =0
Returns true if the underlying value is known dead.
virtual bool isAssumedDead (const BasicBlock *BB) const =0
Returns true if BB is assumed dead.
virtual bool isKnownDead (const BasicBlock *BB) const =0
Returns true if BB is known dead.
virtual bool isAssumedDead (const Instruction *I) const =0
Returns true if I is assumed dead.
virtual bool isKnownDead (const Instruction *I) const =0
Returns true if I is known dead.
template<typename T >
bool isLiveInstSet (T begin, T end) const
This method is used to check if at least one instruction in a collection of instructions is live.
Protected Member Functions inherited from llvm::AbstractAttribute
ChangeStatus update (Attributor &A)
Hook for the Attributor to trigger an update of the internal state.
virtual ChangeStatus manifest (Attributor &A)
Hook for the Attributor to trigger the manifestation of the information represented by the abstract attribute in the LLVM-IR.
virtual void trackStatistics () const =0
Hook to enable custom statistic tracking, called after manifest that resulted in a change if statistics are enabled.
virtual ChangeStatus updateImpl (Attributor &A)=0
The actual update/transfer function which has to be implemented by the derived classes.
Protected Member Functions inherited from llvm::IntegerStateBase< bool, 1, 0 >
virtual void handleNewAssumedValue (base_t Value)=0
Handle a new assumed value Value. Subtype dependent.
virtual void handleNewKnownValue (base_t Value)=0
Handle a new known value Value. Subtype dependent.
virtual void joinOR (base_t AssumedValue, base_t KnownValue)=0
Handle a value Value. Subtype dependent.
virtual void joinAND (base_t AssumedValue, base_t KnownValue)=0
Handle a new assumed value Value. Subtype dependent.
Friends
struct Attributor
Additional Inherited Members
Protected Attributes inherited from llvm::IntegerStateBase< bool, 1, 0 >
base_t Known
The known state encoding in an integer of type base_t.
base_t Assumed
The assumed state encoding in an integer of type base_t.
Detailed Description
An abstract interface for liveness abstract attribute.
Definition at line 2500 of file Attributor.h.
Member Typedef Documentation
Base
using llvm::AAIsDead::Base = StateWrapper<BooleanState, AbstractAttribute>
Definition at line 2501 of file Attributor.h.
Constructor & Destructor Documentation
AAIsDead()
llvm::AAIsDead::AAIsDead (const IRPosition & IRP, Attributor & A) inline
Definition at line 2502 of file Attributor.h.
Member Function Documentation
classof()
static bool llvm::AAIsDead::classof (const AbstractAttribute * AA) inline static
This function should return true if the type of the AA is AAIsDead.
Definition at line 2556 of file Attributor.h.
References llvm::AbstractAttribute::getIdAddr(), and ID.
createForPosition()
static AAIsDead & llvm::AAIsDead::createForPosition (const IRPosition & IRP, Attributor & A) static
Create an abstract attribute view for the position IRP.
getIdAddr()
const char * llvm::AAIsDead::getIdAddr () const inline override virtual
See AbstractAttribute::getIdAddr()
Implements llvm::AbstractAttribute.
Definition at line 2553 of file Attributor.h.
References ID.
getName()
const std::string llvm::AAIsDead::getName () const inline override virtual
See AbstractAttribute::getName()
Implements llvm::AbstractAttribute.
Definition at line 2550 of file Attributor.h.
isAssumedDead() [1/3]
virtual bool llvm::AAIsDead::isAssumedDead () const protected pure virtual
The query functions are protected such that other attributes need to go through the Attributor interfaces: Attributor::isAssumedDead(...)
Returns true if the underlying value is assumed dead.
Referenced by llvm::Attributor::isAssumedDead(), llvm::Attributor::isAssumedDead(), and isLiveInstSet().
isAssumedDead() [2/3]
virtual bool llvm::AAIsDead::isAssumedDead (const BasicBlock * BB) const protected pure virtual
Returns true if BB is assumed dead.
isAssumedDead() [3/3]
virtual bool llvm::AAIsDead::isAssumedDead (const Instruction * I) const protected pure virtual
Returns true if I is assumed dead.
isKnownDead() [1/3]
virtual bool llvm::AAIsDead::isKnownDead () const protected pure virtual
Returns true if the underlying value is known dead.
isKnownDead() [2/3]
virtual bool llvm::AAIsDead::isKnownDead (const BasicBlock * BB) const protected pure virtual
Returns true if BB is known dead.
isKnownDead() [3/3]
virtual bool llvm::AAIsDead::isKnownDead (const Instruction * I) const protected pure virtual
Returns true if I is known dead.
isLiveInstSet()
template<typename T > bool llvm::AAIsDead::isLiveInstSet (T begin, T end) const inline protected
This method is used to check if at least one instruction in a collection of instructions is live.
Definition at line 2528 of file Attributor.h.
References assert(), llvm::IRPosition::getAssociatedFunction(), llvm::AbstractAttribute::getIRPosition(), I, isAssumedDead(), and llvm::make_range().
mayCatchAsynchronousExceptions()
static bool llvm::AAIsDead::mayCatchAsynchronousExceptions (const Function & F) inline static
Determine if F might catch asynchronous exceptions.
Definition at line 2545 of file Attributor.h.
References llvm::canSimplifyInvokeNoUnwind(), and F.
Friends And Related Symbol Documentation
Attributor
friend struct Attributor friend
Definition at line 2563 of file Attributor.h.
Member Data Documentation
ID
const char AAIsDead::ID = 0 static
Unique ID (due to the unique address)
Definition at line 2561 of file Attributor.h.
Referenced by classof(), and getIdAddr().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/IPO/Attributor.h
lib/Transforms/IPO/AttributorAttributes.cpp