LLVM: llvm::UnifyFunctionExitNodes Struct Reference
llvm::UnifyFunctionExitNodes Struct Reference
#include "llvm/Transforms/Utils/UnifyFunctionExitNodes.h"
Public Member Functions
UnifyFunctionExitNodes ()
void getAnalysisUsage (AnalysisUsage &AU) const override
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
BasicBlock * getReturnBlock () const
BasicBlock * getUnwindBlock () const
BasicBlock * getUnreachableBlock () const
bool runOnFunction (Function &F) override
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &OS, const std::string &Banner) const override
createPrinterPass - Get a function printer pass.
void assignPassManager (PMStack &PMS, PassManagerType T) override
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
PassManagerType getPotentialPassManagerType () const override
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
Pass (const Pass &)=delete
Pass & operator= (const Pass &)=delete
virtual ~Pass ()
PassKind getPassKind () const
virtual StringRef getPassName () const
getPassName - Return a nice clean name for a pass.
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
doInitialization - Virtual method overridden by subclasses to do any necessary initialization before any pass is run.
virtual bool doFinalization (Module &)
doFinalization - Virtual method overriden by subclasses to do any necessary clean up after all passes have run.
virtual void print (raw_ostream &OS, const Module *M) const
print - Print out the internal state of the pass.
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed.
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
getAdjustedAnalysisPointer - This method is used when a pass implements an analysis interface through multiple inheritance.
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
getAnalysisIfAvailable<AnalysisType>() - Subclasses use this function to get analysis information that might be around, for example to update it.
bool mustPreserveAnalysisID (char &AID) const
mustPreserveAnalysisID - This method serves the same function as getAnalysisIfAvailable, but works if you just have an AnalysisID.
template<typename AnalysisType >
AnalysisType & getAnalysis () const
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F, bool *Changed=nullptr)
getAnalysis<AnalysisType>() - This function is used by subclasses to get to the analysis information that they claim to use by overriding the getAnalysisUsage function.
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F, bool *Changed=nullptr)
Public Attributes
BasicBlock * ReturnBlock = nullptr
BasicBlock * UnwindBlock = nullptr
BasicBlock * UnreachableBlock
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::FunctionPass
bool skipFunction (const Function &F) const
Optional passes call this function to check whether the pass should be skipped.
Detailed Description
Definition at line 26 of file UnifyFunctionExitNodes.h.
Constructor & Destructor Documentation
UnifyFunctionExitNodes()
UnifyFunctionExitNodes::UnifyFunctionExitNodes ()
Definition at line 27 of file UnifyFunctionExitNodes.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeUnifyFunctionExitNodesPass().
Member Function Documentation
getAnalysisUsage()
void UnifyFunctionExitNodes::getAnalysisUsage (AnalysisUsage &) const override virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job.
If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 38 of file UnifyFunctionExitNodes.cpp.
References llvm::AnalysisUsage::addPreservedID(), llvm::BreakCriticalEdgesID, and llvm::LowerSwitchID.
getReturnBlock()
BasicBlock * llvm::UnifyFunctionExitNodes::getReturnBlock () const inline
Definition at line 41 of file UnifyFunctionExitNodes.h.
References ReturnBlock.
getUnreachableBlock()
BasicBlock * llvm::UnifyFunctionExitNodes::getUnreachableBlock () const inline
Definition at line 43 of file UnifyFunctionExitNodes.h.
References UnreachableBlock.
getUnwindBlock()
BasicBlock * llvm::UnifyFunctionExitNodes::getUnwindBlock () const inline
Definition at line 42 of file UnifyFunctionExitNodes.h.
References UnwindBlock.
runOnFunction()
bool UnifyFunctionExitNodes::runOnFunction (Function & F) override virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 51 of file UnifyFunctionExitNodes.cpp.
References llvm::PHINode::addIncoming(), llvm::BranchInst::Create(), llvm::ReturnInst::Create(), llvm::BasicBlock::Create(), llvm::PHINode::Create(), F, I, ReturnBlock, and UnreachableBlock.
Member Data Documentation
ID
char UnifyFunctionExitNodes::ID = 0 static
Definition at line 32 of file UnifyFunctionExitNodes.h.
ReturnBlock
BasicBlock* llvm::UnifyFunctionExitNodes::ReturnBlock = nullptr
Definition at line 27 of file UnifyFunctionExitNodes.h.
Referenced by getReturnBlock(), and runOnFunction().
UnreachableBlock
BasicBlock* llvm::UnifyFunctionExitNodes::UnreachableBlock
Definition at line 29 of file UnifyFunctionExitNodes.h.
Referenced by getUnreachableBlock(), and runOnFunction().
UnwindBlock
BasicBlock* llvm::UnifyFunctionExitNodes::UnwindBlock = nullptr
Definition at line 28 of file UnifyFunctionExitNodes.h.
Referenced by getUnwindBlock().
The documentation for this struct was generated from the following files:
include/llvm/Transforms/Utils/UnifyFunctionExitNodes.h
lib/Transforms/Utils/UnifyFunctionExitNodes.cpp