LLVM: llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT > Struct Template Reference
llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT > Struct Template Reference
#include "llvm/Support/CFGDiff.h"
Public Types
using DataRef = const GraphDiff<typename GT::NodeRef, InverseGraph> *
using NodeRef = std::pair<DataRef, typename GT::NodeRef>
using ChildIteratorType = decltype(child_end(std::declval<NodeRef>()))
Static Public Member Functions
template<typename Range >
static auto makeChildRange (Range &&R, DataRef DR)
static auto children (NodeRef N)
static auto child_begin (NodeRef N)
static auto child_end (NodeRef N)
Detailed Description
template<typename GraphT, bool InverseGraph = false, bool InverseEdge = false, typename GT = GraphTraits<GraphT>>
struct llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >
Definition at line 199 of file CFGDiff.h.
Member Typedef Documentation
ChildIteratorType
template<typename GraphT , bool InverseGraph = false, bool InverseEdge = false, typename GT = GraphTraits<GraphT>> using llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >::ChildIteratorType = decltype(child_end(std::declval<NodeRef>()))
Definition at line 239 of file CFGDiff.h.
DataRef
template<typename GraphT , bool InverseGraph = false, bool InverseEdge = false, typename GT = GraphTraits<GraphT>> using llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >::DataRef = const GraphDiff<typename GT::NodeRef, InverseGraph> *
Definition at line 200 of file CFGDiff.h.
NodeRef
template<typename GraphT , bool InverseGraph = false, bool InverseEdge = false, typename GT = GraphTraits<GraphT>> using llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >::NodeRef = std::pair<DataRef, typename GT::NodeRef>
Definition at line 201 of file CFGDiff.h.
Member Function Documentation
child_begin()
template<typename GraphT , bool InverseGraph = false, bool InverseEdge = false, typename GT = GraphTraits<GraphT>> static auto llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >::child_begin (NodeRef N) inline static
Definition at line 231 of file CFGDiff.h.
References llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >::children(), and N.
child_end()
template<typename GraphT , bool InverseGraph = false, bool InverseEdge = false, typename GT = GraphTraits<GraphT>> static auto llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >::child_end (NodeRef N) inline static
Definition at line 235 of file CFGDiff.h.
References llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >::children(), and N.
children()
template<typename GraphT , bool InverseGraph = false, bool InverseEdge = false, typename GT = GraphTraits<GraphT>> static auto llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >::children (NodeRef N) inline static
Definition at line 209 of file CFGDiff.h.
References C, llvm::make_filter_range(), llvm::make_range(), llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >::makeChildRange(), and N.
Referenced by llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >::child_begin(), and llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >::child_end().
makeChildRange()
template<typename GraphT , bool InverseGraph = false, bool InverseEdge = false, typename GT = GraphTraits<GraphT>> template<typename Range > static auto llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >::makeChildRange (Range && R, DataRef DR) inline static
Definition at line 204 of file CFGDiff.h.
References llvm::make_range().
Referenced by llvm::CFGViewChildren< GraphT, InverseGraph, InverseEdge, GT >::children().
The documentation for this struct was generated from the following file:
include/llvm/Support/CFGDiff.h