LLVM: lib/Target/VE/VEISelDAGToDAG.cpp File Reference
VEISelDAGToDAG.cpp File Reference
#include "VETargetMachine.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "VEGenDAGISel.inc"
Functions
static VECC::CondCode intCondCode2Icc (ISD::CondCode CC)
Convert a DAG integer condition code to a VE ICC condition.
static VECC::CondCode fpCondCode2Fcc (ISD::CondCode CC)
Convert a DAG floating point condition code to a VE FCC condition.
static uint64_t getImmVal (const ConstantSDNode *N)
getImmVal - get immediate representation of integer value
static uint64_t getFpImmVal (const ConstantFPSDNode *N)
getFpImmVal - get immediate representation of floating point value
static uint64_t convMImmVal (uint64_t Val)
convMImmVal - Convert a mimm integer immediate value to target immediate.
Function Documentation
convMImmVal()
static uint64_t convMImmVal (uint64_t Val) inline static
convMImmVal - Convert a mimm integer immediate value to target immediate.
Definition at line 117 of file VEISelDAGToDAG.cpp.
References llvm::countLeadingOnes(), and llvm::countLeadingZeros().
fpCondCode2Fcc()
static VECC::CondCode fpCondCode2Fcc (ISD::CondCode CC) inline static
Convert a DAG floating point condition code to a VE FCC condition.
Definition at line 55 of file VEISelDAGToDAG.cpp.
References llvm::VECC::CC_AF, llvm::VECC::CC_AT, llvm::VECC::CC_EQ, llvm::VECC::CC_EQNAN, llvm::VECC::CC_G, llvm::VECC::CC_GE, llvm::VECC::CC_GENAN, llvm::VECC::CC_GNAN, llvm::VECC::CC_L, llvm::VECC::CC_LE, llvm::VECC::CC_LENAN, llvm::VECC::CC_LNAN, llvm::VECC::CC_NAN, llvm::VECC::CC_NE, llvm::VECC::CC_NENAN, llvm::VECC::CC_NUM, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETFALSE, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETTRUE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, and llvm::ISD::SETUO.
getFpImmVal()
static uint64_t getFpImmVal (const ConstantFPSDNode * N) inline static
getFpImmVal - get immediate representation of floating point value
Definition at line 106 of file VEISelDAGToDAG.cpp.
References llvm::APInt::getBitWidth(), llvm::APInt::getZExtValue(), and N.
getImmVal()
static uint64_t getImmVal (const ConstantSDNode * N) inline static
getImmVal - get immediate representation of integer value
Definition at line 101 of file VEISelDAGToDAG.cpp.
References N.
intCondCode2Icc()
static VECC::CondCode intCondCode2Icc (ISD::CondCode CC) inline static
Convert a DAG integer condition code to a VE ICC condition.
Definition at line 27 of file VEISelDAGToDAG.cpp.
References llvm::VECC::CC_IEQ, llvm::VECC::CC_IG, llvm::VECC::CC_IGE, llvm::VECC::CC_IL, llvm::VECC::CC_ILE, llvm::VECC::CC_INE, llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, and llvm::ISD::SETULT.