LLVM: lib/Support/X86TargetParser.cpp File Reference
X86TargetParser.cpp File Reference
#include "llvm/Support/X86TargetParser.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Support/X86TargetParser.def"
Macros
#define X86_FEATURE(ENUM, STRING) static constexpr FeatureBitset Feature##ENUM = {X86::FEATURE_##ENUM};
#define X86_FEATURE(ENUM, STR) {{STR}, ImpliedFeatures##ENUM},
Functions
static void getFeatureBitsAsStrings (const FeatureBitset &Bits, SmallVectorImpl< StringRef > &Features)
static void getImpliedEnabledFeatures (FeatureBitset &Bits, const FeatureBitset &Implies)
static void getImpliedDisabledFeatures (FeatureBitset &Bits, unsigned Value)
Create bit vector of features that are implied disabled if the feature passed in Value is disabled.
Variables
static constexpr FeatureBitset FeaturesPentiumMMX
static constexpr FeatureBitset FeaturesPentium2
static constexpr FeatureBitset FeaturesPentium3 = FeaturesPentium2 | FeatureSSE
static constexpr FeatureBitset FeaturesPentium4
static constexpr FeatureBitset FeaturesPrescott
static constexpr FeatureBitset FeaturesNocona
static constexpr FeatureBitset FeaturesX86_64 = FeaturesPentium4 | Feature64BIT
static constexpr FeatureBitset FeaturesCore2
static constexpr FeatureBitset FeaturesPenryn = FeaturesCore2 | FeatureSSE4_1
static constexpr FeatureBitset FeaturesNehalem
static constexpr FeatureBitset FeaturesWestmere
static constexpr FeatureBitset FeaturesSandyBridge
static constexpr FeatureBitset FeaturesIvyBridge
static constexpr FeatureBitset FeaturesHaswell
static constexpr FeatureBitset FeaturesBroadwell
static constexpr FeatureBitset FeaturesKNL
static constexpr FeatureBitset FeaturesKNM
static constexpr FeatureBitset FeaturesSkylakeClient
static constexpr FeatureBitset FeaturesSkylakeServer
static constexpr FeatureBitset FeaturesCascadeLake
static constexpr FeatureBitset FeaturesCooperLake
static constexpr FeatureBitset FeaturesCannonlake
static constexpr FeatureBitset FeaturesICLClient
static constexpr FeatureBitset FeaturesICLServer
static constexpr FeatureBitset FeaturesTigerlake
static constexpr FeatureBitset FeaturesBonnell = FeaturesCore2 | FeatureMOVBE
static constexpr FeatureBitset FeaturesSilvermont
static constexpr FeatureBitset FeaturesGoldmont
static constexpr FeatureBitset FeaturesGoldmontPlus
static constexpr FeatureBitset FeaturesTremont
static constexpr FeatureBitset FeaturesGeode
static constexpr FeatureBitset FeaturesK6
static constexpr FeatureBitset FeaturesAthlon
static constexpr FeatureBitset FeaturesAthlonXP
static constexpr FeatureBitset FeaturesK8
static constexpr FeatureBitset FeaturesK8SSE3 = FeaturesK8 | FeatureSSE3
static constexpr FeatureBitset FeaturesAMDFAM10
static constexpr FeatureBitset FeaturesBTVER1
static constexpr FeatureBitset FeaturesBTVER2
static constexpr FeatureBitset FeaturesBDVER1
static constexpr FeatureBitset FeaturesBDVER2
static constexpr FeatureBitset FeaturesBDVER3
static constexpr FeatureBitset FeaturesBDVER4
static constexpr FeatureBitset FeaturesZNVER1
static constexpr FeatureBitset FeaturesZNVER2
static constexpr ProcInfo Processors []
static constexpr FeatureBitset ImpliedFeatures64BIT = {}
static constexpr FeatureBitset ImpliedFeaturesADX = {}
static constexpr FeatureBitset ImpliedFeaturesBMI = {}
static constexpr FeatureBitset ImpliedFeaturesBMI2 = {}
static constexpr FeatureBitset ImpliedFeaturesCLDEMOTE = {}
static constexpr FeatureBitset ImpliedFeaturesCLFLUSHOPT = {}
static constexpr FeatureBitset ImpliedFeaturesCLWB = {}
static constexpr FeatureBitset ImpliedFeaturesCLZERO = {}
static constexpr FeatureBitset ImpliedFeaturesCMOV = {}
static constexpr FeatureBitset ImpliedFeaturesCMPXCHG16B = {}
static constexpr FeatureBitset ImpliedFeaturesCMPXCHG8B = {}
static constexpr FeatureBitset ImpliedFeaturesENQCMD = {}
static constexpr FeatureBitset ImpliedFeaturesFSGSBASE = {}
static constexpr FeatureBitset ImpliedFeaturesFXSR = {}
static constexpr FeatureBitset ImpliedFeaturesINVPCID = {}
static constexpr FeatureBitset ImpliedFeaturesLWP = {}
static constexpr FeatureBitset ImpliedFeaturesLZCNT = {}
static constexpr FeatureBitset ImpliedFeaturesMWAITX = {}
static constexpr FeatureBitset ImpliedFeaturesMOVBE = {}
static constexpr FeatureBitset ImpliedFeaturesMOVDIR64B = {}
static constexpr FeatureBitset ImpliedFeaturesMOVDIRI = {}
static constexpr FeatureBitset ImpliedFeaturesPCONFIG = {}
static constexpr FeatureBitset ImpliedFeaturesPOPCNT = {}
static constexpr FeatureBitset ImpliedFeaturesPKU = {}
static constexpr FeatureBitset ImpliedFeaturesPREFETCHWT1 = {}
static constexpr FeatureBitset ImpliedFeaturesPRFCHW = {}
static constexpr FeatureBitset ImpliedFeaturesPTWRITE = {}
static constexpr FeatureBitset ImpliedFeaturesRDPID = {}
static constexpr FeatureBitset ImpliedFeaturesRDRND = {}
static constexpr FeatureBitset ImpliedFeaturesRDSEED = {}
static constexpr FeatureBitset ImpliedFeaturesRTM = {}
static constexpr FeatureBitset ImpliedFeaturesSAHF = {}
static constexpr FeatureBitset ImpliedFeaturesSERIALIZE = {}
static constexpr FeatureBitset ImpliedFeaturesSGX = {}
static constexpr FeatureBitset ImpliedFeaturesSHSTK = {}
static constexpr FeatureBitset ImpliedFeaturesTBM = {}
static constexpr FeatureBitset ImpliedFeaturesTSXLDTRK = {}
static constexpr FeatureBitset ImpliedFeaturesWAITPKG = {}
static constexpr FeatureBitset ImpliedFeaturesWBNOINVD = {}
static constexpr FeatureBitset ImpliedFeaturesVZEROUPPER = {}
static constexpr FeatureBitset ImpliedFeaturesX87 = {}
static constexpr FeatureBitset ImpliedFeaturesXSAVE = {}
static constexpr FeatureBitset ImpliedFeaturesRETPOLINE_EXTERNAL_THUNK = {}
static constexpr FeatureBitset ImpliedFeaturesRETPOLINE_INDIRECT_BRANCHES = {}
static constexpr FeatureBitset ImpliedFeaturesRETPOLINE_INDIRECT_CALLS = {}
static constexpr FeatureBitset ImpliedFeaturesLVI_CFI = {}
static constexpr FeatureBitset ImpliedFeaturesLVI_LOAD_HARDENING = {}
static constexpr FeatureBitset ImpliedFeaturesXSAVEC = FeatureXSAVE
static constexpr FeatureBitset ImpliedFeaturesXSAVEOPT = FeatureXSAVE
static constexpr FeatureBitset ImpliedFeaturesXSAVES = FeatureXSAVE
static constexpr FeatureBitset ImpliedFeaturesMMX = {}
static constexpr FeatureBitset ImpliedFeatures3DNOW = FeatureMMX
static constexpr FeatureBitset ImpliedFeatures3DNOWA = Feature3DNOW
static constexpr FeatureBitset ImpliedFeaturesSSE = {}
static constexpr FeatureBitset ImpliedFeaturesSSE2 = FeatureSSE
static constexpr FeatureBitset ImpliedFeaturesSSE3 = FeatureSSE2
static constexpr FeatureBitset ImpliedFeaturesSSSE3 = FeatureSSE3
static constexpr FeatureBitset ImpliedFeaturesSSE4_1 = FeatureSSSE3
static constexpr FeatureBitset ImpliedFeaturesSSE4_2 = FeatureSSE4_1
static constexpr FeatureBitset ImpliedFeaturesAVX = FeatureSSE4_2
static constexpr FeatureBitset ImpliedFeaturesAVX2 = FeatureAVX
static constexpr FeatureBitset ImpliedFeaturesAVX512F
static constexpr FeatureBitset ImpliedFeaturesAES = FeatureSSE2
static constexpr FeatureBitset ImpliedFeaturesF16C = FeatureAVX
static constexpr FeatureBitset ImpliedFeaturesFMA = FeatureAVX
static constexpr FeatureBitset ImpliedFeaturesGFNI = FeatureSSE2
static constexpr FeatureBitset ImpliedFeaturesPCLMUL = FeatureSSE2
static constexpr FeatureBitset ImpliedFeaturesSHA = FeatureSSE2
static constexpr FeatureBitset ImpliedFeaturesVAES = FeatureAES | FeatureAVX
static constexpr FeatureBitset ImpliedFeaturesVPCLMULQDQ
static constexpr FeatureBitset ImpliedFeaturesAVX512CD = FeatureAVX512F
static constexpr FeatureBitset ImpliedFeaturesAVX512BW = FeatureAVX512F
static constexpr FeatureBitset ImpliedFeaturesAVX512DQ = FeatureAVX512F
static constexpr FeatureBitset ImpliedFeaturesAVX512ER = FeatureAVX512F
static constexpr FeatureBitset ImpliedFeaturesAVX512PF = FeatureAVX512F
static constexpr FeatureBitset ImpliedFeaturesAVX512VL = FeatureAVX512F
static constexpr FeatureBitset ImpliedFeaturesAVX512BF16 = FeatureAVX512BW
static constexpr FeatureBitset ImpliedFeaturesAVX512BITALG = FeatureAVX512BW
static constexpr FeatureBitset ImpliedFeaturesAVX512IFMA = FeatureAVX512F
static constexpr FeatureBitset ImpliedFeaturesAVX512VNNI = FeatureAVX512F
static constexpr FeatureBitset ImpliedFeaturesAVX512VPOPCNTDQ = FeatureAVX512F
static constexpr FeatureBitset ImpliedFeaturesAVX512VBMI = FeatureAVX512BW
static constexpr FeatureBitset ImpliedFeaturesAVX512VBMI2 = FeatureAVX512BW
static constexpr FeatureBitset ImpliedFeaturesAVX512VP2INTERSECT
static constexpr FeatureBitset ImpliedFeaturesAVX5124FMAPS = {}
static constexpr FeatureBitset ImpliedFeaturesAVX5124VNNIW = {}
static constexpr FeatureBitset ImpliedFeaturesSSE4_A = FeatureSSE3
static constexpr FeatureBitset ImpliedFeaturesFMA4 = FeatureAVX | FeatureSSE4_A
static constexpr FeatureBitset ImpliedFeaturesXOP = FeatureFMA4
static constexpr FeatureBitset ImpliedFeaturesAMX_TILE = {}
static constexpr FeatureBitset ImpliedFeaturesAMX_BF16 = FeatureAMX_TILE
static constexpr FeatureBitset ImpliedFeaturesAMX_INT8 = FeatureAMX_TILE
static constexpr FeatureInfo FeatureInfos [X86::CPU_FEATURE_MAX]
Macro Definition Documentation
X86_FEATURE [1/2]
#define X86_FEATURE (ENUM, STR) {{STR}, ImpliedFeatures##ENUM},
Definition at line 119 of file X86TargetParser.cpp.
X86_FEATURE [2/2]
#define X86_FEATURE (ENUM, STRING) static constexpr FeatureBitset Feature##ENUM = {X86::FEATURE_##ENUM};
Definition at line 119 of file X86TargetParser.cpp.
Function Documentation
getFeatureBitsAsStrings()
static void getFeatureBitsAsStrings (const FeatureBitset & Bits, SmallVectorImpl< StringRef > & Features) static
Definition at line 540 of file X86TargetParser.cpp.
References llvm::X86::CPU_FEATURE_MAX, FeatureInfos, and Name.
Referenced by llvm::X86::getFeaturesForCPU(), and llvm::X86::getImpliedFeatures().
getImpliedDisabledFeatures()
static void getImpliedDisabledFeatures (FeatureBitset & Bits, unsigned Value) static
Create bit vector of features that are implied disabled if the feature passed in Value is disabled.
Definition at line 581 of file X86TargetParser.cpp.
References llvm::X86::CPU_FEATURE_MAX, and FeatureInfos.
Referenced by llvm::X86::getImpliedFeatures().
getImpliedEnabledFeatures()
static void getImpliedEnabledFeatures (FeatureBitset & Bits, const FeatureBitset & Implies) static
Definition at line 564 of file X86TargetParser.cpp.
References llvm::FeatureBitset::any(), llvm::X86::CPU_FEATURE_MAX, and FeatureInfos.
Referenced by llvm::X86::getImpliedFeatures().
Variable Documentation
FeatureInfos
constexpr FeatureInfo FeatureInfos[X86::CPU_FEATURE_MAX] static constexpr
Initial value:
= {
#define X86_FEATURE(ENUM, STR)
}
Definition at line 534 of file X86TargetParser.cpp.
Referenced by getFeatureBitsAsStrings(), getImpliedDisabledFeatures(), getImpliedEnabledFeatures(), and llvm::X86::getImpliedFeatures().
FeaturesAMDFAM10
constexpr FeatureBitset FeaturesAMDFAM10 static constexpr
Initial value:
=
    FeaturesK8SSE3 | FeatureCMPXCHG16B | FeatureLZCNT | FeaturePOPCNT |
    FeaturePRFCHW | FeatureSAHF | FeatureSSE4_A
Definition at line 230 of file X86TargetParser.cpp.
FeaturesAthlon
constexpr FeatureBitset FeaturesAthlon static constexpr
Initial value:
=
    FeatureX87 | FeatureCMPXCHG8B | FeatureMMX | Feature3DNOW | Feature3DNOWA
Definition at line 223 of file X86TargetParser.cpp.
FeaturesAthlonXP
constexpr FeatureBitset FeaturesAthlonXP static constexpr
Initial value:
=
    FeaturesAthlon | FeatureFXSR | FeatureSSE
Definition at line 225 of file X86TargetParser.cpp.
FeaturesBDVER1
constexpr FeatureBitset FeaturesBDVER1 static constexpr
Initial value:
=
    FeatureX87 | FeatureAES | FeatureAVX | FeatureCMPXCHG8B |
    FeatureCMPXCHG16B | Feature64BIT | FeatureFMA4 | FeatureFXSR | FeatureLWP |
    FeatureLZCNT | FeatureMMX | FeaturePCLMUL | FeaturePOPCNT | FeaturePRFCHW |
    FeatureSAHF | FeatureSSE | FeatureSSE2 | FeatureSSE3 | FeatureSSSE3 |
    FeatureSSE4_1 | FeatureSSE4_2 | FeatureSSE4_A | FeatureXOP | FeatureXSAVE
Definition at line 245 of file X86TargetParser.cpp.
FeaturesBDVER2
constexpr FeatureBitset FeaturesBDVER2 static constexpr
Initial value:
=
    FeaturesBDVER1 | FeatureBMI | FeatureFMA | FeatureF16C | FeatureTBM
Definition at line 251 of file X86TargetParser.cpp.
FeaturesBDVER3
constexpr FeatureBitset FeaturesBDVER3 static constexpr
Initial value:
=
    FeaturesBDVER2 | FeatureFSGSBASE | FeatureXSAVEOPT
Definition at line 253 of file X86TargetParser.cpp.
FeaturesBDVER4
constexpr FeatureBitset FeaturesBDVER4 static constexpr
Initial value:
=
    FeaturesBDVER3 | FeatureAVX2 | FeatureBMI2 | FeatureMOVBE | FeatureMWAITX |
    FeatureRDRND
Definition at line 255 of file X86TargetParser.cpp.
FeaturesBonnell
constexpr FeatureBitset FeaturesBonnell = FeaturesCore2 | FeatureMOVBE static constexpr
Definition at line 201 of file X86TargetParser.cpp.
FeaturesBroadwell
constexpr FeatureBitset FeaturesBroadwell static constexpr
Initial value:
=
    FeaturesHaswell | FeatureADX | FeaturePRFCHW | FeatureRDSEED
Definition at line 158 of file X86TargetParser.cpp.
FeaturesBTVER1
constexpr FeatureBitset FeaturesBTVER1 static constexpr
Initial value:
=
    FeatureX87 | FeatureCMPXCHG8B | FeatureCMPXCHG16B | Feature64BIT |
    FeatureFXSR | FeatureLZCNT | FeatureMMX | FeaturePOPCNT | FeaturePRFCHW |
    FeatureSSE | FeatureSSE2 | FeatureSSE3 | FeatureSSSE3 | FeatureSSE4_A |
    FeatureSAHF
Definition at line 235 of file X86TargetParser.cpp.
FeaturesBTVER2
constexpr FeatureBitset FeaturesBTVER2 static constexpr
Initial value:
=
    FeaturesBTVER1 | FeatureAES | FeatureAVX | FeatureBMI | FeatureF16C |
    FeatureMOVBE | FeaturePCLMUL | FeatureXSAVE | FeatureXSAVEOPT
Definition at line 240 of file X86TargetParser.cpp.
FeaturesCannonlake
constexpr FeatureBitset FeaturesCannonlake static constexpr
Initial value:
=
    FeaturesSkylakeClient | FeatureAVX512F | FeatureAVX512CD | FeatureAVX512DQ |
    FeatureAVX512BW | FeatureAVX512VL | FeatureAVX512IFMA | FeatureAVX512VBMI |
    FeaturePKU | FeatureSHA
Definition at line 185 of file X86TargetParser.cpp.
FeaturesCascadeLake
constexpr FeatureBitset FeaturesCascadeLake static constexpr
Initial value:
=
    FeaturesSkylakeServer | FeatureAVX512VNNI
Definition at line 179 of file X86TargetParser.cpp.
FeaturesCooperLake
constexpr FeatureBitset FeaturesCooperLake static constexpr
Initial value:
=
    FeaturesCascadeLake | FeatureAVX512BF16
Definition at line 181 of file X86TargetParser.cpp.
FeaturesCore2
constexpr FeatureBitset FeaturesCore2 static constexpr
Initial value:
=
    FeaturesNocona | FeatureSAHF | FeatureSSSE3
Definition at line 144 of file X86TargetParser.cpp.
FeaturesGeode
constexpr FeatureBitset FeaturesGeode static constexpr
Initial value:
=
    FeatureX87 | FeatureCMPXCHG8B | FeatureMMX | Feature3DNOW | Feature3DNOWA
Definition at line 215 of file X86TargetParser.cpp.
FeaturesGoldmont
constexpr FeatureBitset FeaturesGoldmont static constexpr
Initial value:
=
    FeaturesSilvermont | FeatureAES | FeatureCLFLUSHOPT | FeatureFSGSBASE |
    FeatureRDSEED | FeatureSHA | FeatureXSAVE | FeatureXSAVEC |
    FeatureXSAVEOPT | FeatureXSAVES
Definition at line 205 of file X86TargetParser.cpp.
FeaturesGoldmontPlus
constexpr FeatureBitset FeaturesGoldmontPlus static constexpr
Initial value:
=
    FeaturesGoldmont | FeaturePTWRITE | FeatureRDPID | FeatureSGX
Definition at line 209 of file X86TargetParser.cpp.
FeaturesHaswell
constexpr FeatureBitset FeaturesHaswell static constexpr
Initial value:
=
    FeaturesIvyBridge | FeatureAVX2 | FeatureBMI | FeatureBMI2 | FeatureFMA |
    FeatureINVPCID | FeatureLZCNT | FeatureMOVBE
Definition at line 155 of file X86TargetParser.cpp.
FeaturesICLClient
constexpr FeatureBitset FeaturesICLClient static constexpr
Initial value:
=
    FeaturesCannonlake | FeatureAVX512BITALG | FeatureAVX512VBMI2 |
    FeatureAVX512VNNI | FeatureAVX512VPOPCNTDQ | FeatureCLWB | FeatureGFNI |
    FeatureRDPID | FeatureVAES | FeatureVPCLMULQDQ
Definition at line 189 of file X86TargetParser.cpp.
FeaturesICLServer
constexpr FeatureBitset FeaturesICLServer static constexpr
Initial value:
=
    FeaturesICLClient | FeaturePCONFIG | FeatureWBNOINVD
Definition at line 193 of file X86TargetParser.cpp.
FeaturesIvyBridge
constexpr FeatureBitset FeaturesIvyBridge static constexpr
Initial value:
=
    FeaturesSandyBridge | FeatureF16C | FeatureFSGSBASE | FeatureRDRND
Definition at line 153 of file X86TargetParser.cpp.
FeaturesK6
constexpr FeatureBitset FeaturesK6 static constexpr
Initial value:
=
    FeatureX87 | FeatureCMPXCHG8B | FeatureMMX
Definition at line 219 of file X86TargetParser.cpp.
FeaturesK8
constexpr FeatureBitset FeaturesK8 static constexpr
Initial value:
=
    FeaturesAthlonXP | FeatureSSE2 | Feature64BIT
Definition at line 227 of file X86TargetParser.cpp.
FeaturesK8SSE3
constexpr FeatureBitset FeaturesK8SSE3 = FeaturesK8 | FeatureSSE3 static constexpr
Definition at line 229 of file X86TargetParser.cpp.
FeaturesKNL
constexpr FeatureBitset FeaturesKNL static constexpr
Initial value:
=
    FeaturesBroadwell | FeatureAES | FeatureAVX512F | FeatureAVX512CD |
    FeatureAVX512ER | FeatureAVX512PF | FeaturePREFETCHWT1
Definition at line 163 of file X86TargetParser.cpp.
FeaturesKNM
constexpr FeatureBitset FeaturesKNM static constexpr
Initial value:
=
    FeaturesKNL | FeatureAVX512VPOPCNTDQ
Definition at line 166 of file X86TargetParser.cpp.
FeaturesNehalem
constexpr FeatureBitset FeaturesNehalem static constexpr
Initial value:
=
    FeaturesPenryn | FeaturePOPCNT | FeatureSSE4_2
Definition at line 147 of file X86TargetParser.cpp.
FeaturesNocona
constexpr FeatureBitset FeaturesNocona static constexpr
Initial value:
=
    FeaturesPrescott | Feature64BIT | FeatureCMPXCHG16B
Definition at line 137 of file X86TargetParser.cpp.
FeaturesPenryn
constexpr FeatureBitset FeaturesPenryn = FeaturesCore2 | FeatureSSE4_1 static constexpr
Definition at line 146 of file X86TargetParser.cpp.
FeaturesPentium2
constexpr FeatureBitset FeaturesPentium2 static constexpr
Initial value:
=
    FeatureX87 | FeatureCMPXCHG8B | FeatureMMX | FeatureFXSR
Definition at line 128 of file X86TargetParser.cpp.
FeaturesPentium3
constexpr FeatureBitset FeaturesPentium3 = FeaturesPentium2 | FeatureSSE static constexpr
Definition at line 130 of file X86TargetParser.cpp.
FeaturesPentium4
constexpr FeatureBitset FeaturesPentium4 static constexpr
Initial value:
=
    FeaturesPentium3 | FeatureSSE2
Definition at line 133 of file X86TargetParser.cpp.
FeaturesPentiumMMX
constexpr FeatureBitset FeaturesPentiumMMX static constexpr
Initial value:
=
    FeatureX87 | FeatureCMPXCHG8B | FeatureMMX
Definition at line 124 of file X86TargetParser.cpp.
FeaturesPrescott
constexpr FeatureBitset FeaturesPrescott static constexpr
Initial value:
=
    FeaturesPentium4 | FeatureSSE3
Definition at line 135 of file X86TargetParser.cpp.
FeaturesSandyBridge
constexpr FeatureBitset FeaturesSandyBridge static constexpr
Initial value:
=
    FeaturesWestmere | FeatureAVX | FeatureXSAVE | FeatureXSAVEOPT
Definition at line 151 of file X86TargetParser.cpp.
FeaturesSilvermont
constexpr FeatureBitset FeaturesSilvermont static constexpr
Initial value:
=
    FeaturesBonnell | FeaturesWestmere | FeaturePRFCHW | FeatureRDRND
Definition at line 203 of file X86TargetParser.cpp.
FeaturesSkylakeClient
constexpr FeatureBitset FeaturesSkylakeClient static constexpr
Initial value:
=
    FeaturesBroadwell | FeatureAES | FeatureCLFLUSHOPT | FeatureXSAVEC |
    FeatureXSAVES | FeatureSGX
Definition at line 170 of file X86TargetParser.cpp.
FeaturesSkylakeServer
constexpr FeatureBitset FeaturesSkylakeServer static constexpr
Initial value:
=
    (FeaturesSkylakeClient & ~FeatureSGX) | FeatureAVX512F | FeatureAVX512CD |
    FeatureAVX512DQ | FeatureAVX512BW | FeatureAVX512VL | FeatureCLWB |
    FeaturePKU
Definition at line 175 of file X86TargetParser.cpp.
FeaturesTigerlake
constexpr FeatureBitset FeaturesTigerlake static constexpr
Initial value:
=
    FeaturesICLClient | FeatureAVX512VP2INTERSECT | FeatureMOVDIR64B |
    FeatureMOVDIRI | FeatureSHSTK
Definition at line 195 of file X86TargetParser.cpp.
FeaturesTremont
constexpr FeatureBitset FeaturesTremont static constexpr
Initial value:
=
    FeaturesGoldmontPlus | FeatureCLWB | FeatureGFNI
Definition at line 211 of file X86TargetParser.cpp.
FeaturesWestmere
constexpr FeatureBitset FeaturesWestmere static constexpr
Initial value:
=
    FeaturesNehalem | FeaturePCLMUL
Definition at line 149 of file X86TargetParser.cpp.
FeaturesX86_64
constexpr FeatureBitset FeaturesX86_64 = FeaturesPentium4 | Feature64BIT static constexpr
Definition at line 141 of file X86TargetParser.cpp.
FeaturesZNVER1
constexpr FeatureBitset FeaturesZNVER1 static constexpr
Initial value:
=
    FeatureX87 | FeatureADX | FeatureAES | FeatureAVX | FeatureAVX2 |
    FeatureBMI | FeatureBMI2 | FeatureCLFLUSHOPT | FeatureCLZERO |
    FeatureCMPXCHG8B | FeatureCMPXCHG16B | Feature64BIT | FeatureF16C |
    FeatureFMA | FeatureFSGSBASE | FeatureFXSR | FeatureLZCNT | FeatureMMX |
    FeatureMOVBE | FeatureMWAITX | FeaturePCLMUL | FeaturePOPCNT |
    FeaturePRFCHW | FeatureRDRND | FeatureRDSEED | FeatureSAHF | FeatureSHA |
    FeatureSSE | FeatureSSE2 | FeatureSSE3 | FeatureSSSE3 | FeatureSSE4_1 |
    FeatureSSE4_2 | FeatureSSE4_A | FeatureXSAVE | FeatureXSAVEC |
    FeatureXSAVEOPT | FeatureXSAVES
Definition at line 260 of file X86TargetParser.cpp.
FeaturesZNVER2
constexpr FeatureBitset FeaturesZNVER2 static constexpr
Initial value:
=
    FeaturesZNVER1 | FeatureCLWB | FeatureRDPID | FeatureWBNOINVD
Definition at line 270 of file X86TargetParser.cpp.
ImpliedFeatures3DNOW
constexpr FeatureBitset ImpliedFeatures3DNOW = FeatureMMX static constexpr
Definition at line 475 of file X86TargetParser.cpp.
ImpliedFeatures3DNOWA
constexpr FeatureBitset ImpliedFeatures3DNOWA = Feature3DNOW static constexpr
Definition at line 476 of file X86TargetParser.cpp.
ImpliedFeatures64BIT
constexpr FeatureBitset ImpliedFeatures64BIT = {} static constexpr
Definition at line 417 of file X86TargetParser.cpp.
ImpliedFeaturesADX
constexpr FeatureBitset ImpliedFeaturesADX = {} static constexpr
Definition at line 418 of file X86TargetParser.cpp.
ImpliedFeaturesAES
constexpr FeatureBitset ImpliedFeaturesAES = FeatureSSE2 static constexpr
Definition at line 491 of file X86TargetParser.cpp.
ImpliedFeaturesAMX_BF16
constexpr FeatureBitset ImpliedFeaturesAMX_BF16 = FeatureAMX_TILE static constexpr
Definition at line 531 of file X86TargetParser.cpp.
ImpliedFeaturesAMX_INT8
constexpr FeatureBitset ImpliedFeaturesAMX_INT8 = FeatureAMX_TILE static constexpr
Definition at line 532 of file X86TargetParser.cpp.
ImpliedFeaturesAMX_TILE
constexpr FeatureBitset ImpliedFeaturesAMX_TILE = {} static constexpr
Definition at line 530 of file X86TargetParser.cpp.
ImpliedFeaturesAVX
constexpr FeatureBitset ImpliedFeaturesAVX = FeatureSSE4_2 static constexpr
Definition at line 485 of file X86TargetParser.cpp.
ImpliedFeaturesAVX2
constexpr FeatureBitset ImpliedFeaturesAVX2 = FeatureAVX static constexpr
Definition at line 486 of file X86TargetParser.cpp.
ImpliedFeaturesAVX5124FMAPS
constexpr FeatureBitset ImpliedFeaturesAVX5124FMAPS = {} static constexpr
Definition at line 521 of file X86TargetParser.cpp.
ImpliedFeaturesAVX5124VNNIW
constexpr FeatureBitset ImpliedFeaturesAVX5124VNNIW = {} static constexpr
Definition at line 522 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512BF16
constexpr FeatureBitset ImpliedFeaturesAVX512BF16 = FeatureAVX512BW static constexpr
Definition at line 509 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512BITALG
constexpr FeatureBitset ImpliedFeaturesAVX512BITALG = FeatureAVX512BW static constexpr
Definition at line 510 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512BW
constexpr FeatureBitset ImpliedFeaturesAVX512BW = FeatureAVX512F static constexpr
Definition at line 503 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512CD
constexpr FeatureBitset ImpliedFeaturesAVX512CD = FeatureAVX512F static constexpr
Definition at line 502 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512DQ
constexpr FeatureBitset ImpliedFeaturesAVX512DQ = FeatureAVX512F static constexpr
Definition at line 504 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512ER
constexpr FeatureBitset ImpliedFeaturesAVX512ER = FeatureAVX512F static constexpr
Definition at line 505 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512F
constexpr FeatureBitset ImpliedFeaturesAVX512F static constexpr
Initial value:
=
    FeatureAVX2 | FeatureF16C | FeatureFMA
Definition at line 487 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512IFMA
constexpr FeatureBitset ImpliedFeaturesAVX512IFMA = FeatureAVX512F static constexpr
Definition at line 511 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512PF
constexpr FeatureBitset ImpliedFeaturesAVX512PF = FeatureAVX512F static constexpr
Definition at line 506 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512VBMI
constexpr FeatureBitset ImpliedFeaturesAVX512VBMI = FeatureAVX512BW static constexpr
Definition at line 514 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512VBMI2
constexpr FeatureBitset ImpliedFeaturesAVX512VBMI2 = FeatureAVX512BW static constexpr
Definition at line 515 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512VL
constexpr FeatureBitset ImpliedFeaturesAVX512VL = FeatureAVX512F static constexpr
Definition at line 507 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512VNNI
constexpr FeatureBitset ImpliedFeaturesAVX512VNNI = FeatureAVX512F static constexpr
Definition at line 512 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512VP2INTERSECT
constexpr FeatureBitset ImpliedFeaturesAVX512VP2INTERSECT static constexpr
Initial value:
=
    FeatureAVX512F
Definition at line 516 of file X86TargetParser.cpp.
ImpliedFeaturesAVX512VPOPCNTDQ
constexpr FeatureBitset ImpliedFeaturesAVX512VPOPCNTDQ = FeatureAVX512F static constexpr
Definition at line 513 of file X86TargetParser.cpp.
ImpliedFeaturesBMI
constexpr FeatureBitset ImpliedFeaturesBMI = {} static constexpr
Definition at line 419 of file X86TargetParser.cpp.
ImpliedFeaturesBMI2
constexpr FeatureBitset ImpliedFeaturesBMI2 = {} static constexpr
Definition at line 420 of file X86TargetParser.cpp.
ImpliedFeaturesCLDEMOTE
constexpr FeatureBitset ImpliedFeaturesCLDEMOTE = {} static constexpr
Definition at line 421 of file X86TargetParser.cpp.
ImpliedFeaturesCLFLUSHOPT
constexpr FeatureBitset ImpliedFeaturesCLFLUSHOPT = {} static constexpr
Definition at line 422 of file X86TargetParser.cpp.
ImpliedFeaturesCLWB
constexpr FeatureBitset ImpliedFeaturesCLWB = {} static constexpr
Definition at line 423 of file X86TargetParser.cpp.
ImpliedFeaturesCLZERO
constexpr FeatureBitset ImpliedFeaturesCLZERO = {} static constexpr
Definition at line 424 of file X86TargetParser.cpp.
ImpliedFeaturesCMOV
constexpr FeatureBitset ImpliedFeaturesCMOV = {} static constexpr
Definition at line 425 of file X86TargetParser.cpp.
ImpliedFeaturesCMPXCHG16B
constexpr FeatureBitset ImpliedFeaturesCMPXCHG16B = {} static constexpr
Definition at line 426 of file X86TargetParser.cpp.
ImpliedFeaturesCMPXCHG8B
constexpr FeatureBitset ImpliedFeaturesCMPXCHG8B = {} static constexpr
Definition at line 427 of file X86TargetParser.cpp.
ImpliedFeaturesENQCMD
constexpr FeatureBitset ImpliedFeaturesENQCMD = {} static constexpr
Definition at line 428 of file X86TargetParser.cpp.
ImpliedFeaturesF16C
constexpr FeatureBitset ImpliedFeaturesF16C = FeatureAVX static constexpr
Definition at line 492 of file X86TargetParser.cpp.
ImpliedFeaturesFMA
constexpr FeatureBitset ImpliedFeaturesFMA = FeatureAVX static constexpr
Definition at line 493 of file X86TargetParser.cpp.
ImpliedFeaturesFMA4
constexpr FeatureBitset ImpliedFeaturesFMA4 = FeatureAVX | FeatureSSE4_A static constexpr
Definition at line 526 of file X86TargetParser.cpp.
ImpliedFeaturesFSGSBASE
constexpr FeatureBitset ImpliedFeaturesFSGSBASE = {} static constexpr
Definition at line 429 of file X86TargetParser.cpp.
ImpliedFeaturesFXSR
constexpr FeatureBitset ImpliedFeaturesFXSR = {} static constexpr
Definition at line 430 of file X86TargetParser.cpp.
ImpliedFeaturesGFNI
constexpr FeatureBitset ImpliedFeaturesGFNI = FeatureSSE2 static constexpr
Definition at line 494 of file X86TargetParser.cpp.
ImpliedFeaturesINVPCID
constexpr FeatureBitset ImpliedFeaturesINVPCID = {} static constexpr
Definition at line 431 of file X86TargetParser.cpp.
ImpliedFeaturesLVI_CFI
constexpr FeatureBitset ImpliedFeaturesLVI_CFI = {} static constexpr
Definition at line 465 of file X86TargetParser.cpp.
ImpliedFeaturesLVI_LOAD_HARDENING
constexpr FeatureBitset ImpliedFeaturesLVI_LOAD_HARDENING = {} static constexpr
Definition at line 466 of file X86TargetParser.cpp.
ImpliedFeaturesLWP
constexpr FeatureBitset ImpliedFeaturesLWP = {} static constexpr
Definition at line 432 of file X86TargetParser.cpp.
ImpliedFeaturesLZCNT
constexpr FeatureBitset ImpliedFeaturesLZCNT = {} static constexpr
Definition at line 433 of file X86TargetParser.cpp.
ImpliedFeaturesMMX
constexpr FeatureBitset ImpliedFeaturesMMX = {} static constexpr
Definition at line 474 of file X86TargetParser.cpp.
ImpliedFeaturesMOVBE
constexpr FeatureBitset ImpliedFeaturesMOVBE = {} static constexpr
Definition at line 435 of file X86TargetParser.cpp.
ImpliedFeaturesMOVDIR64B
constexpr FeatureBitset ImpliedFeaturesMOVDIR64B = {} static constexpr
Definition at line 436 of file X86TargetParser.cpp.
ImpliedFeaturesMOVDIRI
constexpr FeatureBitset ImpliedFeaturesMOVDIRI = {} static constexpr
Definition at line 437 of file X86TargetParser.cpp.
ImpliedFeaturesMWAITX
constexpr FeatureBitset ImpliedFeaturesMWAITX = {} static constexpr
Definition at line 434 of file X86TargetParser.cpp.
ImpliedFeaturesPCLMUL
constexpr FeatureBitset ImpliedFeaturesPCLMUL = FeatureSSE2 static constexpr
Definition at line 495 of file X86TargetParser.cpp.
ImpliedFeaturesPCONFIG
constexpr FeatureBitset ImpliedFeaturesPCONFIG = {} static constexpr
Definition at line 438 of file X86TargetParser.cpp.
ImpliedFeaturesPKU
constexpr FeatureBitset ImpliedFeaturesPKU = {} static constexpr
Definition at line 440 of file X86TargetParser.cpp.
ImpliedFeaturesPOPCNT
constexpr FeatureBitset ImpliedFeaturesPOPCNT = {} static constexpr
Definition at line 439 of file X86TargetParser.cpp.
ImpliedFeaturesPREFETCHWT1
constexpr FeatureBitset ImpliedFeaturesPREFETCHWT1 = {} static constexpr
Definition at line 441 of file X86TargetParser.cpp.
ImpliedFeaturesPRFCHW
constexpr FeatureBitset ImpliedFeaturesPRFCHW = {} static constexpr
Definition at line 442 of file X86TargetParser.cpp.
ImpliedFeaturesPTWRITE
constexpr FeatureBitset ImpliedFeaturesPTWRITE = {} static constexpr
Definition at line 443 of file X86TargetParser.cpp.
ImpliedFeaturesRDPID
constexpr FeatureBitset ImpliedFeaturesRDPID = {} static constexpr
Definition at line 444 of file X86TargetParser.cpp.
ImpliedFeaturesRDRND
constexpr FeatureBitset ImpliedFeaturesRDRND = {} static constexpr
Definition at line 445 of file X86TargetParser.cpp.
ImpliedFeaturesRDSEED
constexpr FeatureBitset ImpliedFeaturesRDSEED = {} static constexpr
Definition at line 446 of file X86TargetParser.cpp.
ImpliedFeaturesRETPOLINE_EXTERNAL_THUNK
constexpr FeatureBitset ImpliedFeaturesRETPOLINE_EXTERNAL_THUNK = {} static constexpr
Definition at line 462 of file X86TargetParser.cpp.
ImpliedFeaturesRETPOLINE_INDIRECT_BRANCHES
constexpr FeatureBitset ImpliedFeaturesRETPOLINE_INDIRECT_BRANCHES = {} static constexpr
Definition at line 463 of file X86TargetParser.cpp.
ImpliedFeaturesRETPOLINE_INDIRECT_CALLS
constexpr FeatureBitset ImpliedFeaturesRETPOLINE_INDIRECT_CALLS = {} static constexpr
Definition at line 464 of file X86TargetParser.cpp.
ImpliedFeaturesRTM
constexpr FeatureBitset ImpliedFeaturesRTM = {} static constexpr
Definition at line 447 of file X86TargetParser.cpp.
ImpliedFeaturesSAHF
constexpr FeatureBitset ImpliedFeaturesSAHF = {} static constexpr
Definition at line 448 of file X86TargetParser.cpp.
ImpliedFeaturesSERIALIZE
constexpr FeatureBitset ImpliedFeaturesSERIALIZE = {} static constexpr
Definition at line 449 of file X86TargetParser.cpp.
ImpliedFeaturesSGX
constexpr FeatureBitset ImpliedFeaturesSGX = {} static constexpr
Definition at line 450 of file X86TargetParser.cpp.
ImpliedFeaturesSHA
constexpr FeatureBitset ImpliedFeaturesSHA = FeatureSSE2 static constexpr
Definition at line 496 of file X86TargetParser.cpp.
ImpliedFeaturesSHSTK
constexpr FeatureBitset ImpliedFeaturesSHSTK = {} static constexpr
Definition at line 451 of file X86TargetParser.cpp.
ImpliedFeaturesSSE
constexpr FeatureBitset ImpliedFeaturesSSE = {} static constexpr
Definition at line 479 of file X86TargetParser.cpp.
ImpliedFeaturesSSE2
constexpr FeatureBitset ImpliedFeaturesSSE2 = FeatureSSE static constexpr
Definition at line 480 of file X86TargetParser.cpp.
ImpliedFeaturesSSE3
constexpr FeatureBitset ImpliedFeaturesSSE3 = FeatureSSE2 static constexpr
Definition at line 481 of file X86TargetParser.cpp.
ImpliedFeaturesSSE4_1
constexpr FeatureBitset ImpliedFeaturesSSE4_1 = FeatureSSSE3 static constexpr
Definition at line 483 of file X86TargetParser.cpp.
ImpliedFeaturesSSE4_2
constexpr FeatureBitset ImpliedFeaturesSSE4_2 = FeatureSSE4_1 static constexpr
Definition at line 484 of file X86TargetParser.cpp.
ImpliedFeaturesSSE4_A
constexpr FeatureBitset ImpliedFeaturesSSE4_A = FeatureSSE3 static constexpr
Definition at line 525 of file X86TargetParser.cpp.
ImpliedFeaturesSSSE3
constexpr FeatureBitset ImpliedFeaturesSSSE3 = FeatureSSE3 static constexpr
Definition at line 482 of file X86TargetParser.cpp.
ImpliedFeaturesTBM
constexpr FeatureBitset ImpliedFeaturesTBM = {} static constexpr
Definition at line 452 of file X86TargetParser.cpp.
ImpliedFeaturesTSXLDTRK
constexpr FeatureBitset ImpliedFeaturesTSXLDTRK = {} static constexpr
Definition at line 453 of file X86TargetParser.cpp.
ImpliedFeaturesVAES
constexpr FeatureBitset ImpliedFeaturesVAES = FeatureAES | FeatureAVX static constexpr
Definition at line 497 of file X86TargetParser.cpp.
ImpliedFeaturesVPCLMULQDQ
constexpr FeatureBitset ImpliedFeaturesVPCLMULQDQ static constexpr
Initial value:
=
    FeatureAVX | FeaturePCLMUL
Definition at line 498 of file X86TargetParser.cpp.
ImpliedFeaturesVZEROUPPER
constexpr FeatureBitset ImpliedFeaturesVZEROUPPER = {} static constexpr
Definition at line 456 of file X86TargetParser.cpp.
ImpliedFeaturesWAITPKG
constexpr FeatureBitset ImpliedFeaturesWAITPKG = {} static constexpr
Definition at line 454 of file X86TargetParser.cpp.
ImpliedFeaturesWBNOINVD
constexpr FeatureBitset ImpliedFeaturesWBNOINVD = {} static constexpr
Definition at line 455 of file X86TargetParser.cpp.
ImpliedFeaturesX87
constexpr FeatureBitset ImpliedFeaturesX87 = {} static constexpr
Definition at line 457 of file X86TargetParser.cpp.
ImpliedFeaturesXOP
constexpr FeatureBitset ImpliedFeaturesXOP = FeatureFMA4 static constexpr
Definition at line 527 of file X86TargetParser.cpp.
ImpliedFeaturesXSAVE
constexpr FeatureBitset ImpliedFeaturesXSAVE = {} static constexpr
Definition at line 458 of file X86TargetParser.cpp.
ImpliedFeaturesXSAVEC
constexpr FeatureBitset ImpliedFeaturesXSAVEC = FeatureXSAVE static constexpr
Definition at line 469 of file X86TargetParser.cpp.
ImpliedFeaturesXSAVEOPT
constexpr FeatureBitset ImpliedFeaturesXSAVEOPT = FeatureXSAVE static constexpr
Definition at line 470 of file X86TargetParser.cpp.
ImpliedFeaturesXSAVES
constexpr FeatureBitset ImpliedFeaturesXSAVES = FeatureXSAVE static constexpr
Definition at line 471 of file X86TargetParser.cpp.
Processors
constexpr ProcInfo Processors[] static constexpr
Definition at line 273 of file X86TargetParser.cpp.
Referenced by llvm::X86::fillValidCPUArchList(), llvm::X86::getFeaturesForCPU(), llvm::X86::getKeyFeature(), and llvm::X86::parseArchX86().